### ISSUE TITLE
Elasticsearch-2.4.4 Does Not Load

### ISSUE THREAD

**Issue by andrewthad** [NixOS/nixpkgs#22565]
## Issue description

Elasticsearch 2.4.4 does not load correctly. I believe that the java class path may be messed up. However, I'm not very experienced at deploying java applications. I have installed the older elasticsearch 1.7.2 with nix and it appears to run fine.

### Steps to reproduce

Run the following commands:

    $ nix-env -i elasticsearch-2.4.4
    $ export ES_HOME="/some/data/dir/"
    $ elasticsearch
    Error: Could not find or load main class org.elasticsearch.bootstrap.Elasticsearch

## Technical details

* System: Ubuntu 16.04.1 LTS
* Nix version: 1.11.6
* Nixpkgs version: "17.03pre100516.01ca916"

**Comment by andrewthad** [comment]
Additionally, this problem happens when I instead run:

    nix-shell -p elasticsearch2 --run 'ES_HOME=/home/amartin/datastore/elasticsearch-2 elasticsearch'

**Comment by andrewthad** [comment]
@rickynils You are the person who most recently made changes to elasticsearch. Would you mind looking over my suggested edits? I don't know if there is a better way to fix the problem I'm encountering.

**Comment by rickynils** [comment]
@andrewthad I can reproduce your problem if I run elasticsearch manually. The NixOS service is however working fine. It looks like the service sets up ES_HOME with symlinks into the nix store: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/search/elasticsearch.nix#L142

With your changes, does the NixOS service still work correctly?

**Comment by Mic92** [comment]
@rickynils it did. I think the symlink is now obsolete.

**Comment by andrewthad** [comment]
I don't use NixOS, but I agree with @Mic92 that the symlinks in the service description should now be unneeded.
