### ISSUE TITLE
citra and yuzu-ea conflict

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#225633]
### Describe the bug
Attempting to install `citra` (3DS Emulator) and `yuzu-ea` (Switch Emulator) at the same time is not currently possible without changing the priority of one of the packages.

 > error: collision between `'/nix/store/80nnwn3v1h5rcwkg06h9mgwcc5y8vrc9-yuzu-ea-2945/share/cmake/tsl-robin-map/tsl-robin-mapTargets.cmake'`and `'/nix/store/zsk1n9q57cg3b3ygd3y7p64h9sakf5m0-citra-nightly-1873/share/cmake/tsl-robin-map/tsl-robin-mapTargets.cmake'`

Correct me if I'm wrong, but shouldn't the cmake files not be included in the final output, for either package?

### Steps To Reproduce
1. Attempt to install both packages side by side

### Expected behavior
They install and work side by side. (They did previously, I'm not sure exactly when that stopped being the case)

### Additional context
I'm installing both via Home Manager, but afaik that shouldn't cause any huge issues.

### Notify maintainers

Both packages seem to be maintained by the same four people:

     ashley / @kira64xyz 
     ivar / @IvarWithoutBones 
     joshuafern / @JoshuaFern 
     sbruder / @sbruder 
     

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.105, NixOS, 22.11 (Raccoon), 22.11.20230409.48dcbaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/40w1i37kf1s1ljj3a22ngi5b66bsd225-source`
```

**Comment by Atemu** [comment]
@lasers I take it this is an upstream issue?

**Comment by lasers** [comment]
@Atemu No idea. I just know they're not there anymore. Maybe this? https://github.com/citra-emu/citra-nightly/commit/9c81dc0dd8bca65722d31670ebe9f937bd97c2cf

Comparing: https://github.com/citra-emu/citra-nightly/compare/nightly-1873...nightly-1880
