### ISSUE TITLE
openrgb module: creates `OpenRGB.json` and `logs/` in root of filesystem

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#225762]
### Describe the bug
The OpenRGB module (`services.hardware.openrgb`) puts an `OpenRGB.json` configuration file and `logs` directory in the root of the filesystem.

### Steps To Reproduce
1. Set `services.hardware.openrgb.enable`
2. Start the `openrgb` service
3. `ls /`

### Expected behavior
I would expect the configuration to go into `/var/lib/openrgb` or something, and logs into `/var/log`. The current behaviour is surprising and works poorly with root-as-tmpfs configurations.

### Additional context
This is the code responsible for working out where to put the OpenRGB config: https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/c7b417ed8a387bec07c731027976a05c2e5a1b7e/ResourceManager.cpp#L511 (see also https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/c7b417ed8a387bec07c731027976a05c2e5a1b7e/ResourceManager.cpp#L73)

I suspect setting $HOME or $XDG_CONFIG_HOME or even just putting $PWD as `/var/lib/openrgb` would go some way towards fixing this.

### Notify maintainers

@jonringer

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230326.5f9d1bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by jonringer** [comment]
looks like setting `XDG_CONFIG_HOME` to something reasonable should do the trick. Kind of surprised this isn't the default behavior.

... after some searching...
I guess it is the default behavior for user unit files, but currently we only have this packaged as a system unit file. I see two paths:
- Configure openrgb service as a user service (will require some work to get devices to be writable by user service)
- Just set `XDG_CONFIG_HOME` to something reasonable like `/var/lib/openrgb`. Should probably set `HOME` to be something similar incase they are following other XDG paths.

**Comment by purin-aurelia** [comment]
attempted to make a pr for this, githubs made it a nightmare so ill leave the relavent change here
```
systemd = {
      tmpfiles.rules = ["d /var/lib/OpenRGB 0755 root root -"];
      services.openrgb = {
        description = "OpenRGB server daemon";
        wantedBy = [ "multi-user.target" ];
        WorkingDirectory = "/var/lib/OpenRGB";
        serviceConfig = {
          ExecStart = "${cfg.package}/bin/openrgb --server --server-port ${toString cfg.server.port}";
          Restart = "always";
        };
```
an unrelated to this issue change from that PR attempt is amd i2c module name is `i2c-piix4` not `i2c-piix`
