### ISSUE TITLE
pulsar: binary not found

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#225755]
### Describe the bug

```
[davidak@gaming:~]$ nix run nixpkgs#pulsar
error: unable to execute '/nix/store/apvf9nj79kvvh6j23qzlawxhzlxwjhc2-Pulsar-1.103.0/bin/Pulsar': No such file or directory
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior

just run it

### Additional context

Change the package name to lowercase to match the binary.

This is also required by policy:

>The pname and the version attribute must not contain uppercase letters — e.g., "mplayer" instead of“MPlayer”`.

https://nixos.org/manual/nixpkgs/stable/#sec-package-naming

### Notify maintainers

@colamaroro

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 22.11 (Raccoon), 22.11.3408.a575c243c23`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by COLAMAroro** [comment]
Could you try `nix run github:nixos/nixpkgs/unstable#pulsar` ?

As far as I can see, Pulsar hasn't been backported to 22.11

**Comment by COLAMAroro** [comment]
Ah, nice catch. I will make a small PR to fix the issue.

(I'll take the opportunity to clean up a bit more the update script)

**Comment by davidak** [comment]
> Could you try `nix run github:nixos/nixpkgs/unstable#pulsar` ?

Same issue since the command uses unstable by default i think.

```
[davidak@gaming:~]$ nix run github:nixos/nixpkgs/nixos-unstable#pulsar
error: unable to execute '/nix/store/apvf9nj79kvvh6j23qzlawxhzlxwjhc2-Pulsar-1.103.0/bin/Pulsar': No such file or directory
```

**Comment by COLAMAroro** [comment]
Just a quick heads up, I've not forgotten this issue, I'm waiting for the 1.104 release, which is probably going to happen on the 15th :slightly_smiling_face:
