### ISSUE TITLE
Imgui: Code using Imgui fails to compile when using platform backend imports

### ISSUE THREAD

**Issue by mjjs** [NixOS/nixpkgs#225791]
### Describe the bug
When trying to compile a program that uses the [sdl2 backend](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_sdl2.h) (or presumably any other) from the Imgui library, the compilation fails because the backend file imports `"imgui.h"`, which is not in the system include paths.

### Steps To Reproduce
1. Clone the Imgui repository: https://github.com/ocornut/imgui.git
2. Enter the `examples/example_sdl2_opengl3` folder inside the repository.
3. Change the imgui imports in `main.cpp` to use the system wide headers:
- `"imgui.h"` -> `<imgui/imgui.h>`
- `"imgui_impl_sdl2.h"` -> `<imgui/backends/imgui_impl_sdl2.h>`
- `"imgui_impl_opengl3.h"` -> `<imgui/backends/imgui_impl_opengl3.h>`
4. Remove the `-I$(IMGUI_DIR)` and `-I$(IMGUI_DIR)/backends` include flags from the `CXXFLAGS` in `Makefile`.
5. Enter a nix-shell: `nix-shell -p imgui SDL2 gnumake`.
6. Run `make`.

The header file `imgui_impl_opengl3.h` fails to import `"imgui.h"`:

```
In file included from main.cpp:8:
/nix/store/1s5f16kyv5bnv34xlla943ncr03drq4j-imgui-1.89.4/include/imgui/backends/imgui_impl_opengl3.h:21:10: fatal error: imgui.h: No such file or directory
   21 | #include "imgui.h"      // IMGUI_IMPL_API
      |          ^~~~~~~~~
```

### Expected behavior
The code should compile.

### Screenshots
N/A

### Additional context
I was able to fix it locally by using a patch that changes the back-end header and source files to use the `<imgui/...>` imports, but I'm not sure if this is the proper way to do it.

Also, I'm not sure how I would add the backend sources to my compiler, as the corresponding source file [needs to be compiled](https://github.com/ocornut/imgui/blob/master/docs/BACKENDS.md) as well.

### Notify maintainers
@ryantm you seem to have commited into the file previously.
@wolfangaukang you seem to be listed as the maintainer.

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05pre470275.53dad94e874`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(mjs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
Hey @mjjs, you mentioned you were able to patch it. Can you please post it? Something to also consider is that a modification on the way this is built might not be possible because some packages are dependent of it, so the patch might be the proper (if not the only solution) to this. That's why I want to check it.

**Comment by mjjs** [comment]
Here's an example patch that fixes the imports for the backends used in the linked example:

```patch
From 21b2f25c18ec056a050d8a52b4921188401e9491 Mon Sep 17 00:00:00 2001
From: mjjs <mjjs@example.com>
Date: Tue, 11 Apr 2023 21:42:43 +0300
Subject: [PATCH] fix imports

---
 backends/imgui_impl_opengl3.cpp | 4 ++--
 backends/imgui_impl_opengl3.h   | 2 +-
 backends/imgui_impl_sdl2.cpp    | 4 ++--
 backends/imgui_impl_sdl2.h      | 2 +-
 4 files changed, 6 insertions(+), 6 deletions(-)

diff --git a/backends/imgui_impl_opengl3.cpp b/backends/imgui_impl_opengl3.cpp
index 7bf26e66..84050aaf 100644
--- a/backends/imgui_impl_opengl3.cpp
+++ b/backends/imgui_impl_opengl3.cpp
@@ -95,8 +95,8 @@
 #define _CRT_SECURE_NO_WARNINGS
 #endif
 
-#include "imgui.h"
-#include "imgui_impl_opengl3.h"
+#include <imgui/imgui.h>
+#include <imgui/backends/imgui_impl_opengl3.h>
 #include <stdio.h>
 #if defined(_MSC_VER) && _MSC_VER <= 1500 // MSVC 2008 or earlier
 #include <stddef.h>     // intptr_t
diff --git a/backends/imgui_impl_opengl3.h b/backends/imgui_impl_opengl3.h
index 3a95f052..2e6cccbe 100644
--- a/backends/imgui_impl_opengl3.h
+++ b/backends/imgui_impl_opengl3.h
@@ -18,7 +18,7 @@
 //  Only override if your GL version doesn't handle this GLSL version. See GLSL version table at the top of imgui_impl_opengl3.cpp.
 
 #pragma once
-#include "imgui.h"      // IMGUI_IMPL_API
+#include <imgui/imgui.h>      // IMGUI_IMPL_API
 
 // Backend API
 IMGUI_IMPL_API bool     ImGui_ImplOpenGL3_Init(const char* glsl_version = nullptr);
diff --git a/backends/imgui_impl_sdl2.cpp b/backends/imgui_impl_sdl2.cpp
index 8ba4be2f..2f53739f 100644
--- a/backends/imgui_impl_sdl2.cpp
+++ b/backends/imgui_impl_sdl2.cpp
@@ -72,8 +72,8 @@
 //  2017-08-25: Inputs: MousePos set to -FLT_MAX,-FLT_MAX when mouse is unavailable/missing (instead of -1,-1).
 //  2016-10-15: Misc: Added a void* user_data parameter to Clipboard function handlers.
 
-#include "imgui.h"
-#include "imgui_impl_sdl2.h"
+#include <imgui/imgui.h>
+#include <imgui/backends/imgui_impl_sdl2.h>
 
 // Clang warnings with -Weverything
 #if defined(__clang__)
diff --git a/backends/imgui_impl_sdl2.h b/backends/imgui_impl_sdl2.h
index 8dcabac1..2b2471f9 100644
--- a/backends/imgui_impl_sdl2.h
+++ b/backends/imgui_impl_sdl2.h
@@ -16,7 +16,7 @@
 // Read online: https://github.com/ocornut/imgui/tree/master/docs
 
 #pragma once
-#include "imgui.h"      // IMGUI_IMPL_API
+#include <imgui/imgui.h>      // IMGUI_IMPL_API
 
 struct SDL_Window;
 struct SDL_Renderer;
-- 
2.39.2
```

But this still does not fix the problem of how to import the .cpp files when compiling something with these backends.

It looks like the approach you mentioned about setting `IMGUI_DIR` is the most sensible way to do the compilation. I wasn't aware that it's possible to get the store path of an installed package in such way in a nix file, thanks for this. I'm not sure if there is anything to fix here now. I think this could be closed, let me know what you think.
