### ISSUE TITLE
Build failure: pkgsCross.riscv64.linux_6_2 

### ISSUE THREAD

**Issue by leifhelm** [NixOS/nixpkgs#225756]
### Steps To Reproduce

1. run `nix build nixpkgs#pkgsCross.riscv64.linux_6_2`

### Build log
Console
```
error: cycle detected in build of '/nix/store/2xhadkswmwy36qjhdrv5yn2r29k6crna-linux-riscv64-unknown-linux-gnu-6.2.10.drv' in the references of output 'dev' from output 'out'
```
[log](https://gist.github.com/leifhelm/a0bc388ecdbabc3402721136ae00ab67)

### Additional context

Compiling it natively does not help (needed to disable checks in meson).

### Notify maintainers

@alyssais 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230409.fd531de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by leifhelm** [comment]
#221707 seems to be the point were it broke.

**Comment by alyssais** [comment]
This is fixed in linux_testing with #226623, and I'm hoping to get it into the next stable releases of 6.2 and 6.1.

**Comment by alyssais** [comment]
Update: [won't make it into the next round of stable kernels](https://lore.kernel.org/stable/2023041944-marvelous-barge-ec64@gregkh/), but I'll aim for the following one.

**Comment by alyssais** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/228354.
