### ISSUE TITLE
Update request: starship 1.13.1 → 1.14.1

### ISSUE THREAD

**Issue by Sntx626** [NixOS/nixpkgs#225797]
- Package name: starship
- Latest released version: 1.14.1

- Current version on the unstable channel: 1.13.1
- Current version on the stable/release channel: 1.11.0

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bbigras @danth @davidtwco @Br1ght0ne @Frostman @marsam 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kilianar** [comment]
https://github.com/NixOS/nixpkgs/pull/225686

**Comment by Sntx626** [comment]
Why did I search for open pull requests...

Closing since this is already fixed.
Thank you very much!
