### ISSUE TITLE
nix-store --optimize fails

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#22582]
## Issue description

```
nix-store --optimize
error: reading from file: Input/output erro
```

## Technical details

* System: 17.03pre100479.f7b7d8e (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre100479.f7b7d8e"

**Comment by danbst** [comment]
maybe this should be in Nix's bugtracker?

**Comment by matthiasbeyer** [comment]
I'm not sure...
