### ISSUE TITLE
Remove webkitgtk24x and packages depending on it

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixpkgs#22588]
WebkitGTK 2.4 is very old and not maintained upstream anymore. Fedora will remove it after the next stable release branchoff next month and we should follow suit, at least after 17.03 for 17.09.

See https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/ for more details.

List of packages still depending on webkitgtk24x (checked if fixed or removed):

 - [ ] gnome3.bijiben
 - [ ] gnome3.geary
 - [ ] haskellPackages.webkitgtk3
 - [ ] haskellPackages.webkitgtk3-javascriptcore
 - [ ] haskellPackages.websnap
 - [ ] emacs
 - [ ] astroid (https://github.com/astroidmail/astroid/issues/49)
 - [ ] mu
 - [ ] jumanji
 - [ ] liferea

**Comment by FRidh** [comment]
see https://github.com/NixOS/nixpkgs/issues/18312
