### ISSUE TITLE
Haskell package servant doesn't compile on darwin due to python2.7-future

### ISSUE THREAD

**Issue by Dridus** [NixOS/nixpkgs#22590]
## Issue description

The servant package has an override in configuration-common.nix which tacks on documentation building with sphinx. Sphinx depends via some path on python2.7-future which has only linux mentioned as a viable platform, so the whole build bombs during validation on darwin.

I had trouble overriding this by using `packageOverrides` and `haskell.lib.overrideCabal` but couldn't get the `postInstall` to be overridden. I tried this specifically:

```nix
  import <nixpkgs> {
    packageOverrides = pkgs: rec {
      haskellPackages = pkgs.haskellPackages.override {
        overrides = self: super: {
          servant = pkgs.haskell.lib.overrideCabal super.servant (old: {
            postInstall = "";
          });
        };
      };
    };
  }
```

I did have success `cabal2nix`ing servant and overriding servant with that copy, like this:

```nix
  import <nixpkgs> {
    packageOverrides = pkgs: rec {
      haskellPackages = pkgs.haskellPackages.override {
        overrides = self: super: {
          # Do this because the servant package is patched in nixpkgs to build the documentation, which uses sphinx. Sphinx doesn't work on Darwin
          # because python2.7-future is not available on that platform.  We don't care about the docs so instead just use a clean expression 
          # generated by cabal2nix.
          servant = self.callPackage ./servant.nix {};
        };
      };
    };
  }
```

It would be really swell if it was possible to disable the doc build like you can with other haskell packages using `dontHaddock` or similar, though just having it not blow up and not generate the docs would be fine in my view - the docs are available at http://haskell-servant.readthedocs.io/en/stable/

### Steps to reproduce

`nix-build '<nixpkgs>' -A haskellPackages.servant` fails with:

```
error: Package ‘python2.7-future-0.15.2’ in ‘/nix/store/wq90d75hc8k4rz3syd9x7sk7x295a9cf-nixpkgs-17.03pre99928.61c48d9/nixpkgs/pkgs/top-level/python-packages.nix:11828’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```
## Technical details

* System: macOS Sierra 10.12.3
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre99928.61c48d9

**Comment by domenkozar** [comment]
cc @Profpatsch

**Comment by Profpatsch** [comment]
Have you tried just removing that linux restriction for `python2.7-future`?
Maybe it builds just fine.

**Comment by Dridus** [comment]
@profpatsch I had not. I just tried it and it seems to build without error. should I make a PR to that effect?

**Comment by Profpatsch** [comment]
Yes!

**Comment by Dridus** [comment]
@Profpatsch #22837
