### ISSUE TITLE
Build failure: newsflash can't build with latest webkitgtk

### ISSUE THREAD

**Issue by dacioromero** [NixOS/nixpkgs#225986]
### Steps To Reproduce

1. `nix build github:NixOS/nixpkgs/nixpkgs-unstable#newsflash` (fe2ecaf706a5907b5e54d979fbde4924d84b65fc)

### Build log

https://gist.github.com/dacioromero/f9097f03ab3de008d9f910673e3f0553

### Additional context

> The pkg-config API version will change from webkit2gtk-5.0 to webkitgtk-5.0 as I’ve removed more vestiges of the legacy WebKit2 branding

https://webkitgtk.org/2023/03/17/webkitgtk2.40.0-released.html

The update of `webkitgtk` and removal of `webkitgtk_5_0` breaks `newsflash` (and possibly more) and `webkitgtk_6_0` isn't a direct replacement for `newsflash` since it expects `webkit2gtk`.

Two versions of `webkitgtk` might need to be packaged because of this change.

Suspected commits:

https://github.com/NixOS/nixpkgs/commit/0f4129cc5a17989e84fc0af8c01091a4524df258
https://github.com/NixOS/nixpkgs/commit/d2d4cd97d536187b0203d23966dba7894b34545b

### Notify maintainers

I'm including the maintainers of `newsflash` and the names on the commits linked above.

@bobby285271
@jtojnar
@kira-bruneau 
@Stunkymonkey 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 23.05 (Stoat), 23.05.20230409.fd531de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(xxxxx): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/store/pfl7hc27m2zqv8r3bz1dlmibdlvr80af-source`
```

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/225892#issuecomment-1505376250

**Comment by kira-bruneau** [comment]
Thanks @bobby285271 for the fix!!
