### ISSUE TITLE
upgrading 22.11 -> 23.05 removes everything from `/sys/class/backlight` 

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#225902]
### Describe the bug
I cannot change the brightness of my laptop screen (lenovo thinkpad p14s) after upgrading to 23.05

### Steps To Reproduce
1. buy thinkpad p14s 
2. install https://git.sr.ht/~mangoiv/dotfiles Rev bc5d66b2c6ee0a2d3d9bbc462ad791c70b8eba5b 
3. try out `brightnessctl` or `illum`

### Expected behavior
either of `brightnessctl` or `illum` or whatever allow to change brightness

### Additional context
Brightnessctl only shows `leds` 

I checked on gnome wayland as well, it's not the fault of the program, seems it really stopped working fundamentally. 

```
Available devices:
Device 'platform::mute' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'tpacpi::power' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'input0::scrolllock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'input0::capslock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'tpacpi::lid_logo_dot' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'tpacpi::standby' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'input0::numlock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'tpacpi::thinkvantage' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'tpacpi::kbd_backlight' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 2

Device 'platform::micmute' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

```

### Metadata 
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9-zen1, NixOS, 23.05 (Stoat), 23.05.20230411.3fb8eed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.14.0pre20230128_792d83f`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MangoIV** [comment]
looks like `/sys/class/brightness/` is completely empty

**Comment by MangoIV** [comment]
downgraded to 22.11 and works perfectly fine again.

**Comment by megheaiulian** [comment]
This looks like something kernel related. Can you try 23.05 but with a older kernel ?

**Comment by MangoIV** [comment]
Thank you. This problem indeed disappears when downgrading to 6.0 which sadly has been removed from the unstable package set.

**Comment by MangoIV** [comment]
https://github.com/NixOS/nixos-hardware/blob/3006d2860a6ed5e01b0c3e7ffb730e9b293116e2/lenovo/thinkpad/p14s/amd/gen2/default.nix#L11

**Comment by Artturin** [comment]
Same issue? https://bugs.archlinux.org/task/77056

**Comment by sahmed011** [comment]
Hi, after upgrading from 23.05 to 23.11 unstable no sort of brightness control works (other than the physical buttons on my monitor) I tried using `nixos-generate-config` which is the answer provided in the discourse [here](https://discourse.nixos.org/t/cannot-control-display-brightness-in-nixos-23-05/29157/2). When I do `light`, I get this message: `No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.
`. There's also no `/sys/class/backlight`, either :(

**Comment by Artturin** [comment]
> Hi, after upgrading from 23.05 to 23.11 unstable no sort of brightness control works (other than the physical buttons on my monitor) I tried using `nixos-generate-config` which is the answer provided in the discourse [here](https://discourse.nixos.org/t/cannot-control-display-brightness-in-nixos-23-05/29157/2). When I do `light`, I get this message: `No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s. `. There's also no `/sys/class/backlight`, either :( \n edit: my computer is an hp elitedesk

Did you make sure you are using the `kernelParams`, either manually or from the generator.

**Comment by sahmed011** [comment]
> Did you make sure you are using the `kernelParams` either manually or from the generator.

Uh, I have no idea what kernelParams is, I am a nix newbie. I just ran `nixos-generate-config` from my terminal.

**Comment by Tchekda** [comment]
I can confirm the faulty option was `acpi_backlight=none`. Either replace it with `acpi_backlight=native` or remove it from the `boot.kernelParams` list
