### ISSUE TITLE
libidn2 does not build on Darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#22595]
`wget` now depends on `libidn2`, but it fails on Darwin at present (10.12.3) with:

```
idn2.c:34:10: fatal error: 'error.h' file not found
#include "error.h"
         ^
1 error generated.
```

**Comment by copumpkin** [comment]
cc @fpletz 

I took a quick peek and those headers are marked as gnulib headers in the source:

```c
/* Gnulib headers. */
#include "error.h"
#include "gettext.h"
```

How do they normally get there on a Linux build? I don't see them in the source tree.

**Comment by vcunat** [comment]
glibc contains such a header: http://man7.org/linux/man-pages/man3/error.3.html

**Comment by copumpkin** [comment]
Dammit :)

**Comment by fpletz** [comment]
I've found a darwin machine and am trying to compile it... error.h is not in gnulib. \o/

**Comment by fpletz** [comment]
How would you feel about disabling wget's IDN support on Darwin for now?

**Comment by fpletz** [comment]
What the hell, not even the current wget compiles on darwin. :/

```
  CC       ftp.o
ftp.c:1466:19: error: no member named 'rpl_unlink' in 'struct options'
          if (opt.unlink && file_exists_p (con->target))
              ~~~ ^
../lib/unistd.h:1851:19: note: expanded from macro 'unlink'
#   define unlink rpl_unlink
                  ^
1 error generated.
```

**Comment by copumpkin** [comment]
Disabling IDN seems fine. Perhaps wget folks don't care about darwin though?

**Comment by 2426021684** [comment]
I got this error. How do I fix it?
