### ISSUE TITLE
Package request: librime-lua

### ISSUE THREAD

**Issue by cathaysia** [NixOS/nixpkgs#225956]
**Project description**

as a substitute of librime, librime-lua add lua engine to librime, so we can extend rime by lua. Many schemas of rime use librime-lua but not rime. So please add librime-lua.

**Metadata**

* homepage URL: https://github.com/hchunhui/librime-lua/wiki
* source URL: https://github.com/hchunhui/librime-lua
* license: bsd3
* platforms: linux

**Comment by jian-lin** [comment]
I do not think we have `librime-lua` in Nixpkgs.  Let's reopen this.
