### ISSUE TITLE
New functions for pkgs.haskell.lib

### ISSUE THREAD

**Issue by deemp** [NixOS/nixpkgs#225945]
**Project description**

I'd like to propose a couple of functions that should simplify the setup of Haskell projects.
I'm not aware if they're already available anywhere.

- [getHaskellPackagesDeps](https://github.com/deemp/telegram-bot-simple/blob/d5f70705c97681f18562b98e629a2e7183875197/flake.nix#L30) - provides a list of all packages from getCabalDeps of packages p1,p2,...pN minus packages p1, p2, ..., pN. This allows for developing local packages with other local packages as dependencies. Only non-local packages will be collected.

- [ghcForPackages](https://github.com/deemp/telegram-bot-simple/blob/d5f70705c97681f18562b98e629a2e7183875197/flake.nix#L42) - uses the previous function to construct a ghc with packages. It's a ghc with dependencies for local packages provided via an override of `haskell.packages`.

- It may be useful to provide a wrapper for `cabal` that puts the ghc with packages on `PATH` of `cabal`. That's a way to avoid conflicts between ghc versions in a devshell like https://github.com/NixOS/nixpkgs/issues/225895

**Comment by cdepillabout** [comment]
`getHaskellPackagesDeps` and `ghcForPackages` sort of sound related to `shellFor`.  Maybe some of the internals of `shellFor` could be factored out into separate functions?

**Comment by deemp** [comment]
What I didn't like in `shellFor` was that it created a shell. I got used to [devshell](https://github.com/numtide/devshell) and didn't find an elegant way to combine a `shellFor` and a `devshell`. The workaround was to make a `cabalFor` (let's call it so) for `cabal-install` with `ghcWithPackages` on PATH so that I could use a single `cabalFor` package in a `devShell` instead of `shellFor` or `cabal-install` + `ghcWithPackages`.

I'm currently not ready to work with factoring out the parts of `shellFor`.

**Comment by cdepillabout** [comment]
> What I didn't like in shellFor was that it created a shell.

That's why I suggested

> Maybe some of the internals of shellFor could be factored out into separate functions?

If I remember correctly, the internals of `shellFor` basically do what you're requesting.  Factoring them out seems like a reasonable path forward.

> I got used to [devshell](https://github.com/numtide/devshell) and didn't find an elegant way to combine a shellFor and a devshell

I'm not sure what `devshell` is, but guessing from the name of the repo, it sounds like it might be a reasonable request to be able to pass a `mkShell` environment to `devshell`.  Maybe it would make more sense to open up an issue on `devshell`?

**Comment by deemp** [comment]
Indeed, it is [possible](https://github.com/numtide/devshell/pull/261) to pass all `*inputs` from a `shellFor` derivation to a `mkShell` via `packagesFrom`.
