### ISSUE TITLE
Build failure: droidcam

### ISSUE THREAD

**Issue by DerDennisOP** [NixOS/nixpkgs#226055]
### Steps To Reproduce

1. build *droidcam*
2. run droidcam

### Error

```
Error: Droidcam/v4l2loopback device not found (/dev/video[0-9])
```

### Notify maintainers

@suhr 

### Metadata

Please run `"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230412.fe2ecaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by figsoda** [comment]
Have you tried using [programs.droidcam.enable](https://search.nixos.org/options?channel=unstable&show=programs.droidcam.enable)?

**Comment by suhr** [comment]
This line may be of interest: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/droidcam.nix#L14
