### ISSUE TITLE
Implement a NixOS module for the Keybase Filesystem

### ISSUE THREAD

**Issue by SuprDewd** [NixOS/nixpkgs#22603]
Based on the discussion in #22375, it would probably be a good idea to implement a module for the Keybase Filesystem (aka. KBFS). Its functionality doesn't have to be more complex than

1. making sure that /keybase exists and is writable by the correct user, and
2. doing `kbfsfuse /keybase` as the correct user.

One thing that is not clear (to me) is how this should behave in a multi-user environment, as I don't think it supports access by different keybase accounts at one mountpoint (but haven't really explored this). As a MVP it might make sense to have an option that sets which user the mount belongs to. Alternatively, it might be possible to create separate mountpoints for each user, but then one needs to make sure that the tools using KBFS (e.g. `keybase chat`) work as expected.

cc @OJFord

**Comment by SuprDewd** [comment]
Somewhat relevant: #22600, #22601.

**Comment by OJFord** [comment]
> One thing that is not clear (to me) is how this should behave in a multi-user environment, as I don't think it supports access by different keybase accounts at one mountpoint (but haven't really explored this).

I haven't explored it either, but semi-obviously (and I have tested it) Keybase doesn't let you access e.g. `/keybase/private/ojford` if the logged in (`keybase login`) user is not 'ojford'.

I would *hope* that with multiple users, you just get multiple single-username (KBFS supports sharing with other Keybase users in the form `private/user1,user2`) directories in `keybase/private`. But I don't know.

**Comment by akc** [comment]
Judging from this issue https://github.com/keybase/kbfs/issues/533 is seems that kbfs is single user, for now.

**Comment by cmacrae** [comment]
Hey guys, I have a module I've written.
It's working as expected, implemented as a user service.  

Is there someone that could help guide me with contributing this?  
I ask for help as:
- It's my first Nix module/first contribution to Nix
- I'm not sure where in the tree it should reside
- I'm not sure if there are accompanying changes that should be made (docs, etc.)
- I'm sure there are improvements to be made

**Comment by cmacrae** [comment]
Okay, I've opened [PR 25610](https://github.com/NixOS/nixpkgs/pull/25610). Any feedback welcome!

**Comment by jonafato** [comment]
Should this be closed now that #25610 has been merged?

**Comment by taktoa** [comment]
Commenting as a reminder that this should probably be closed.
