### ISSUE TITLE
Build failure: mangohud

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#226099]
### Steps To Reproduce

1. `nix build nixpkgs#mangohud`

### Build log
https://gist.github.com/aidalgol/14dea28338c3d58d0d4e7088a314d0f5

### Notify maintainers

@kira-bruneau @zeratax 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/pf0xc9gryi9dyp4c6zmynnp3blc547z9-nix-info
copying path '/nix/store/pf0xc9gryi9dyp4c6zmynnp3blc547z9-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 22.11 (Raccoon), 22.11.20230407.0040164`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by kira-bruneau** [comment]
This was already fixed in #225985 on master, but I'll leave this open until the fix gets into nixpkgs-unstable: https://hydra.nixos.org/job/nixpkgs/trunk/mangohud.x86_64-linux/all

**Comment by aidalgol** [comment]
Oops.  Sorry, I did search for open issues, but didn't think to look for recently-closed issues.

**Comment by kira-bruneau** [comment]
No worries!!
