### ISSUE TITLE
Build failure: postgresql_14 (Darwin)

### ISSUE THREAD

**Issue by caleb** [NixOS/nixpkgs#226019]
### Steps To Reproduce

Steps to reproduce the behavior (see below for the flake file I used):
1. nix build .#postgresql_14

This is the output:

```
error: output '/nix/store/jczr2y9mbk37wkp0dp78fy6zgcnfxrrz-postgresql-14.7' is not allowed to refer to the following paths:
         /nix/store/sl7pzkg7jy7wxjkpsd1r89pvi1bk7aha-clang-wrapper-11.1.0
```

### Build log
The log is empty:

```
$ nix log /nix/store/jczr2y9mbk37wkp0dp78fy6zgcnfxrrz-postgresql-14.7
```

### Additional context

My previous staging update was from March 17th (commit #7105890faf43d40b0cd15840fb85e0c9fe5ecdbd) and everything worked correctly, though I believe all of the packages were pulled from cachix.

Here is the flake.nix file I used:

```nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/staging";
    };
  };

  outputs = { self, nixpkgs }: {
    packages.aarch64-darwin.postgresql_14 = nixpkgs.legacyPackages.aarch64-darwin.postgresql_14;
  };
}
```

### Notify maintainers

@Ma27 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Ma27** [comment]
Taking a look...

**Comment by Ma27** [comment]
I can now build it on recent staging (b4cc17e0448f5c1fa8477763c43b049338d3a9d0) again, `postgresql_14` on `x86_64-darwin` results in /nix/store/09pg6vqg4d532g88203mxj0yp6hblrmi-postgresql-14.7, `aarch64-darwin` in /nix/store/w10zhqi85y11j5chgpx59ra5ij2abv1y-postgresql-14.7.
