### ISSUE TITLE
.meld-wrapped 3.16.2 cannot store configuration

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#22626]
```
$ meld dira dirb
(.meld-wrapped:29126): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```
16.09.git.89c567c (Flounder)

Steps to reproduce: Go to preferences, and try to add another file filter. This will fail rendering the program useless.

**Comment by BjornMelgaard** [comment]
Have same error

**Comment by BjornMelgaard** [comment]
resolved with `nix-env -i dconf`

**Comment by BjornMelgaard** [comment]
Im wondering, though dconf [is in dependencies of meld](https://github.com/NixOS/nixpkgs/blob/48fa032aae019298a96fc2f42a1b65bcd33f0ea6/pkgs/applications/version-management/meld/default.nix#L21), why it didn't worked ?

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/issues/11239
