### ISSUE TITLE
Update request: osmosdr 0.2.3 → 0.2.4 and support latest gnuradio

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#226296]
- Package name: osmosdr
- Latest released version: 0.2.4

- Current version on the unstable channel: 0.2.3
- Current version on the stable/release channel: 0.2.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Osmosdr is only packaged for gnuradio 3.8 but the latest version supports gnuradio 3.10 just fine.
**Notify maintainers**

@bjornfor 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by bjornfor** [comment]
@Tungsten842: Can you test https://github.com/NixOS/nixpkgs/issues/226296?
