### ISSUE TITLE
Package request: ActivityWatch 

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#226209]
The best free and open-source automated time tracker. Cross-platform, extensible, privacy-focused.

homepage URL: https://activitywatch.net/
source URL: https://github.com/ActivityWatch/activitywatch
license:  MPL-2.0 license
platforms: Linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/97379
