### ISSUE TITLE
systemd fails to install with SIGABRT

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#22627]
## Issue description
I have a nix setup running on a CentOS system with the store on an NFS share in a custom location (/share/nix) without root access.
I cannot rely on Hydra's cache so everything is recompiled.

In order to try to workaround a problem with one package failing I was recommended to use `vmTools.runInLinuxVM`.
As part of deriving this I currently get a SIGABRT causing systemd to fail to install:

    ...
    installing zh_TW.gmo as /share/nix/store/y9h79i1ar78lp0im0xmva5z308h1lw88-systemd-232-lib/share/locale/zh_TW/LC_MESSAGES/systemd.mo
    CC       i915_state.lo
    CC [M]  drivers/gpu/drm/nouveau/nvkm/subdev/clk/pllgt215.o
    CC       i915_state_derived.lo
    CC       i915_state_dynamic.lo
    CC       i915_state_emit.lo
    CC       i915_state_fpc.lo
    CC [M]  drivers/gpu/drm/nouveau/nvkm/subdev/devinit/base.o
    CC [M]  drivers/gpu/drm/nouveau/nvkm/subdev/devinit/nv04.o
    /share/nix/store/vhbka04yq2h4whzxq179d77k293kx27m-stdenv/setup: line 98:  5606 Aborted                 find $out -name "*kernel-install*" -exec rm {} \;
    builder for ‘/share/nix/store/nbjw08k00wx4lgf1s3vp6p7bvivdqay6-systemd-232.drv’ failed with exit code 134
    cannot build derivation ‘/share/nix/store/m8svh2nrm8n11l218l71lffylfyjwjxd-dbus-1.10.14.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/share/nix/store/zy5x6r2fcfx9shj9s0v38kq92p671ql4-libusb-1.0.20.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/share/nix/store/6447bh8ibs1l5v7w7hhsim5fg8vls62q-util-linux-2.29.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/share/nix/store/4vy52mq3si93qksxqqgrsriyyjxz89zq-libpulseaudio-10.0.drv’: 1 dependencies couldn't be built
    killing process 15556
    cannot build derivation ‘/share/nix/store/7frjz79sp6gyv2qq80pagjpnix8c8i3b-usbredir-0.7.1.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/share/nix/store/nfxcbq5mwf5nx2j85w4id0kjxpnsa1y7-vm-run-stage2.drv’: 1 dependencies couldn't be built
    killing process 14862
    cannot build derivation ‘/share/nix/store/3zb3l5v3vs5mnsy2d3a6xn3bqr4a2shk-vm-run.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/share/nix/store/45bikfynqajbpsa13ab7s764d47zax20-hello-2.10.drv’: 1 dependencies couldn't be built
    error: build of ‘/share/nix/store/45bikfynqajbpsa13ab7s764d47zax20-hello-2.10.drv’ failed

This currently fails on both stable and unstable channels (versions below).

### Steps to reproduce
    nix-repl
    nix-repl> :l <nixos>
    nix-repl> :b vmTools.runInLinuxVM hello

## Technical details

* System: CentOS 6.5
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1650.d2cd8a0 and 17.03pre100557.3e7dffd

**Comment by dezgeg** [comment]
Are you using nested hardware virtualization by any chance?

**Comment by Unode** [comment]
No nested virtualization.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by unode** [comment]
It has been a while and I haven't been able to replicate. Closing as obsolete.
