### ISSUE TITLE
Support for running nix from NFS - non-fatal removal of nix directories 

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#22629]
## Issue description
I have a nix setup running on a CentOS system with the store on an NFS share in a custom location (/share/nix) without root access.
This mostly works but sometimes packages fail to install due to errors during package removal.

The problem stems from NFS's way of dealing with open filehandles which lead to the creating of `.nfs*" files that cannot be removed directly. nix-store trips on these files failing to remove directories (sometimes in `nix/trash`) which ultimately lead to installation failures despite everything else succeeding.

Recently, while repairing nix with `nix-store--verify --check-contents --repair` after an accidental removal of some files I repeatedly ran into this problem.
In particular glibc packages sometimes failed with as much as 10 '.nfs*' files on the `glibc/lib` folder.
These files are likely due to programs using glibc (or other libraries).

Given all this, and considering nix already has the concept of "trash" would it be possible for nix to handle file/folder removals non-fatally? Once these filehandles are closed and software re-launched to use the fixed store locations all `.nfs` files will be gone and garbage-collecting the directory will succeed.  

## Technical details

    System: CentOS 6.5
    Nix version: nix-env (Nix) 1.11.6
    Nixpkgs version: nixos 16.09.1650.d2cd8a0 and nixunstable 17.03pre100557.3e7dffd

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by unode** [comment]
After applying https://nixos.wiki/wiki/NFS#Nix_store_on_NFS the problem mostly disappeared. Occasionally a `.nfs` file still causes problems but I haven't run into this recently.
