### ISSUE TITLE
Failed unmounting /home when RedShift is enabled

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#22633]
## Issue description

I have been observing the following issue on three different machines (a desktop, an old laptop and a recent laptop). Their configurations can be found here https://github.com/Zimmi48/dotfiles but I don't think this is really relevant for this.

After enabling the RedShift service in the following way:
```
  # RedShift changes the color of the screen to a redder tone when night is approaching
  services.redshift = {
    enable = true;
    latitude = "48.8";
    longitude = "2.3";
    extraOptions = [ "-m randr" ];
  };
```

I suddenly get the following failures at shutdown:
```
[Failed] unmounting /run/user/1000
[Failed] unmounting /home
```

I am reporting this issue even though I am not affected by it. I would like to ask though if I can safely ignore it or if I should remove the RedShift service until this issue is solved.

### Steps to reproduce

Add the lines to the configuration, reboot, do something for a while like browsing the internet or stuff in the terminal, shutdown.

## Technical details

* System: 16.09.1650.d2cd8a0 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1650.d2cd8a0

**Comment by rnhmjoj** [comment]
I had the same issue. I don't really know if it was (indirectly) caused by redshift, which I still used, but the error is gone for me. Anyway yes, it should be safe to ignore: the directories will be unmounted anyway during the shutdown process. This bug is known and it has been reported upstream: here's the issue https://github.com/systemd/systemd/issues/867

**Comment by Zimmi48** [comment]
The error is gone for me as well (I switched to 17.03 in the meantime but I don't know if it was gone before that). Closing for now.
