### ISSUE TITLE
[Feature Request] wootility: add a desktop icon

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#226338]
## Issue description

It would be nice if the `wootility` packages provided a `.desktop` icon.

### Steps to reproduce

1. Import the following in your `configuration.nix`:
    ```nix
    { pkgs, ... }:
    {
      environment.systemPackages = [ pkgs.wootility ];
    }
    ```
2. Run `nixos-rebuild switch`
3. Open up a graphical application launcher and search for Wootility.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

<pre><samp> - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.3689.fda0d99c2cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

</samp></pre>

**Comment by Pandapip1** [comment]
PR submitted that, among other things, adds a desktop-entry file.
