### ISSUE TITLE
qt6.qtbase depends on Python3

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#226312]
### Describe the bug

A dependency we'll all be better of without:

```
$ nix why-depends --all --precise .\#qt6.qtbase .\#python3
/nix/store/d8g1cqiy0v21kshgjdgrydjzkwmigplg-qtbase-6.4.3
└───libexec/qt-testrunner.py: …#!/nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.# C…
    mkspecs/features/uikit/devices.py: …#!/nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10/bin/python3.# C…
    → /nix/store/fdqpyj613dr0v1l1lrzqhzay7sk4xg87-python3-3.10.10
```

### Expected behavior

No python3 dependency.

### Notify maintainers

@milahu @nickcao @LunNova

### Ideas

Put these files in `$dev` output? Add a `$bin` output, like `qt5.qtbase`?

**Comment by wegank** [comment]
Maybe related to #226018?

**Comment by NickCao** [comment]
> Put these files in $dev output? Add a $bin output, like qt5.qtbase?

This is how it was done. But moving them requires extensive patching of the qt build system which is not worth the effort. But as these two particular files might not be actually needed by packages in nixpkgs, we do can try moving them, same for the upcoming qt 6.5.0.
