### ISSUE TITLE
Support both ref & rev in flake input url

### ISSUE THREAD

**Issue by dpc** [NixOS/nixpkgs#226389]
### Describe the bug
Currently when I try to use both `ref` and `ref` in flake input url I get:

```
error: URL 'github:ipetkov/crane?ref=v0.12.1&rev=445a3d222947632b5593112bb817850e8a9cf737' contains both a commit hash and a branch/tag name v0.12.1 445a3d222947632b5593112bb817850e8a9cf737
```

### Steps To Reproduce

Use an flake input url that has both `ref` and `rev` (that point at the same commit).

### Expected behavior

I think it should be supported. `nix` should just verify that that `ref` is still pointing at that `rev`.

`rev` is for pinning to a hash for security/reliability, while `ref` is for letting humans reading the code know which release version is it. One could put the `ref` in a comment, but then there's nothing to make sure it's not incorrect.

**Comment by figsoda** [comment]
This issue should probably be on https://github.com/NixOS/nix instead

**Comment by dpc** [comment]
Thank you. Moved to https://github.com/NixOS/nix/issues/8226
