### ISSUE TITLE
Package request: supabase cli

### ISSUE THREAD

**Issue by A-Walrus** [NixOS/nixpkgs#226464]
**Project description**
[Supabase](https://supabase.io/) is an open source Firebase alternative. We're building the features of Firebase using enterprise-grade open source tools.

This repository contains all the functionality for Supabase CLI.

**Metadata**

* homepage URL: [https://supabase.io/](https://supabase.io/)
* source URL: [https://github.com/supabase/cli](https://github.com/supabase/cli)
* license: MIT
* platforms: Linux (amd64, arm64), Darwin (amd64, arm64), Windows

**Comment by pinn3** [comment]
It has already been packaged and is available in the unstable channel

**Comment by A-Walrus** [comment]
Oh my bad, thanks!
