### ISSUE TITLE
Package request: Arianna

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#226403]
**Project description**

An ebook reader and library management app supporting ".epub" files. Arianna discovers your books automatically, and sorts them by categories, genres and authors.

**Metadata**

* homepage URL: https://apps.kde.org/arianna/
* source URL: https://invent.kde.org/graphics/arianna
* license: gpl3.0(+?)
* platforms: linux

**Comment by zendo** [comment]
#226105
