### ISSUE TITLE
Package request: rtx (asdf rust clone)

### ISSUE THREAD

**Issue by mrtolkien** [NixOS/nixpkgs#226450]
**Project description**

Polyglot runtime manager (asdf rust clone)

**Metadata**

* homepage URL: https://github.com/jdxcode/rtx#readme
* source URL: https://github.com/jdxcode/rtx
* license: MIT
* platforms: linux + mac

**Notes**

I've just started using `nix-env` so I'm very much unsure as to how to package this but [instructions are given here](https://github.com/jdxcode/rtx#nix):
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rtx-flake = {
      url = "github:chadac/rtx/add-nix-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
  };

  outputs = { self, nixpkgs, flake-utils, rtx-flake }:
    flake-utils.lib.eachDefaultSystem(system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ rtx-flake.overlay ];
        };
      in {
        devShells.default = pkgs.mkShell {
          name = "my-dev-env";
          nativeBuildInputs = with pkgs; [
            rtx
          ];
        };
      }
    );
}
```

**Comment by mrene** [comment]
Someone started working on this in #218450

**Comment by mrtolkien** [comment]
I had searched in open issues and didn't find it, my bad. Will follow ins progress!
