### ISSUE TITLE
error: opening lock file

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#22643]
## Issue description
installing ‘firefox-51.0.1’
error: opening lock file ‘/home/royadav/opt/nix/store/gxk128533fsvl3j9chgadk3gdc0l8diq-SDL-1.2.15-x11-Bypass-SetGammaRamp-when-changing-gamma.patch?id=04a3a7b1bd88c2d5502292fad27e0e02d084698d.drv.lock’: File name too long
(use ‘--show-trace’ to show detailed location information)

## Technical details
* System: Ubuntu Xenial
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre100656.3047bb2

**Comment by rasendubi** [comment]
I believe this should be fixed by #22654.
