### ISSUE TITLE
Package request:  discord-screenaudio

### ISSUE THREAD

**Issue by garaiza-93** [NixOS/nixpkgs#226504]
**Project description**
A custom discord client that supports streaming with audio on Linux. 
(because combining screen audio and mic audio is cringe)

**Metadata**

* homepage URL: https://github.com/maltejur/discord-screenaudio
* source URL:https://github.com/maltejur/discord-screenaudio
* license: gpl3
* platforms: linux

**Comment by j0lol** [comment]
see #199379 :)

**Comment by garaiza-93** [comment]
oh sick, good to know.
closing.

**Comment by ImUrX** [comment]
can this issue be reopened pls

**Comment by garaiza-93** [comment]
sure, i assume you want to request a package for this too, since https://github.com/NixOS/nixpkgs/pull/199379 was abandoned

**Comment by Unhall0w3d** [comment]
Adding a +1 on this package request. Very sad to see it's not available at this time.

**Comment by PietroCarrara** [comment]
Relevant PR: https://github.com/NixOS/nixpkgs/pull/249670
