### ISSUE TITLE
chirp: Crash on opening or saving files

### ISSUE THREAD

**Issue by witchof0x20** [NixOS/nixpkgs#226524]
### Describe the bug
Using the file manager in chirp (specifically the version used in nixpkgs-unstable) causes the program to crash

Console errors:
```
(chirp:1302680): GLib-GIO-ERROR **: 16:10:18.314: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```
Similar issues seem to have been fixed with wrapGAppsHook, but I can't seem to figure it out.

### Steps To Reproduce
1. Install `chirp` from nixpkgs-unstable
2. Try to open a file via the file->open dialogue, or try to save a file.

### Expected behavior
The program does not crash, allows file saving and loading.

### Notify maintainers
None listed so pinging last few contributors:
@mrene @wegank @pkharvey @greizgh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 22.11 (Raccoon), 22.11.20230414.fda0d99`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/791ch44m51d5q00aa6fp9bq3mzfr3gr1-source`

**Comment by wegank** [comment]
I can't reproduce the issue on both GNOME 44 and Xfce 4.18, so I'm not sure what the solution is. But maybe adding both `gsettings-desktop-schemas` and `glib` would help?

**Comment by witchof0x20** [comment]
Using i3wm myself.

Adding
```
  buildInputs = [
    glib
    gsettings-desktop-schemas
  ];
```
to the package (with the appropriate argument lines at the top) results in the same error

**Comment by witchof0x20** [comment]
Oh! Adding wrapGAppshook to nativebuildInputs as well as the above change seems to fix it.
