### ISSUE TITLE
Kitty: EGL: failed to get EGL display: Success

### ISSUE THREAD

**Issue by WilliamBehrens** [NixOS/nixpkgs#226566]
### Describe the bug
Running attempting to run kitty in sway the following error is returned
![image](https://user-images.githubusercontent.com/35979547/232359368-48b298ed-9e9e-48d3-b27f-d16ed4ad1770.png)
I'm assuming this is an error in the kitty or sway it packaged

### Additional context
Currently running in QEMU using the QXL video driver

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[will@qemu:~]$ nix-shell -p nix-info --run "nix-info -m"
```
![image](https://user-images.githubusercontent.com/35979547/232359575-29d15eed-859f-4207-850d-7f7997108ccc.png)

**Comment by teto** [comment]
usually a reboot fixes it for me

**Comment by WilliamBehrens** [comment]
> usually a reboot fixes it for me

This persist after multiple reboots, I've tried installing the glfw-wayland and egl-wayland packages and it doesn't seem to solve it.

**Comment by WilliamBehrens** [comment]
It appears it was an issue with the vm I was in not having proper opengl support.

**Comment by keydon** [comment]
For me this tool solved my issue with the exact same error message. Seems like a Nix OpenGL Issue https://github.com/guibou/nixGL

**Comment by Arroquw** [comment]
Having the same issue after updating my nixos, though OpenGL seems to be installed completely fine. Problem persists after a reboot.

**Comment by kstaniek** [comment]
+1

**Comment by rjohnsondev** [comment]
yeah running into this now as well on Arch w/ Hyprland on an intel Arc. Haven't had time to attempt to resolve just yet

**Comment by Hariss-Gills** [comment]
Thanks @igorgue. I use AMD's integrated graphics and simply downgraded the `mesa` package [using the pacman cache](https://wiki.archlinux.org/title/downgrading_packages#Using_the_pacman_cache).

**Comment by igorgue** [comment]
@Hariss-Gills I solved this later by installing Kitty from the arch repos instead of their official binary, with that I was able to update.

**Comment by SX-9** [comment]
happened with me to, im using igpu and this used to work before
