### ISSUE TITLE
Teams-for-linux using EOL version of electron (v21)

### ISSUE THREAD

**Issue by lugeha** [NixOS/nixpkgs#226562]
## Issue description

teams-for-linux will not build as electron version 21 is now tagged as EOL.

I have bumped it to version 24, seems quite stable so far.

Perhaps all packages using electron 21 will need a review.

```
 packages.${system}.teams-for-linux = let
        inherit (pkgs.callPackage "${nixpkgs}/pkgs/development/tools/electron/binary" { })
          electron_24-bin;
        in pkgs.callPackage
          "${nixpkgs}/pkgs/applications/networking/instant-messengers/teams-for-linux" {
            electron = electron_24-bin;
          };

 overlay = final: prev: {
      teams-for-linux = self.packages.${system}.teams-for-linux;
 };
```

**Comment by lilyinstarlight** [comment]
I only just noticed this issue. It was fixed by #226543, which also provided a patch to make screensharing "work" with electron 24 and wayland (which was why it was held back on 21 in the first place)

If you're still having issues, feel free to reopen!
