### ISSUE TITLE
Package request: ni

### ISSUE THREAD

**Issue by unitythemaker** [NixOS/nixpkgs#226535]
**Project description**

use the right package manager

ni assumes that you work with lockfiles (and you should)

Before it runs, it will detect your yarn.lock / pnpm-lock.yaml / package-lock.json / bun.lockb to know current package manager (or packageManager field in your packages.json if specified), and runs the corresponding commands.

**Metadata**

* homepage URL: https://github.com/antfu/ni
* source URL: https://github.com/antfu/ni
* license: mit
* platforms: unix, linux, darwin (basically all platforms that nodejs works)

**Comment by donovanglover** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/155627
