### ISSUE TITLE
services.fail2ban.bantime-increment: formula vs multipliers

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#226631]
### Describe the bug
In `services.fail2ban` NixOS module, both options `bantime-increment.formula` and `bantime-increment.multipliers` have a default value.

However, it does not make sense that both options are configured in the same time. According to the [documentation](https://github.com/fail2ban/fail2ban/blob/2b98f461bb93c6a1a1cec1481fa94b7a84342977/config/jail.conf#L70), it seems `bantime-increment.multipliers` would have priority over `bantime-increment.formula` if both are configured (emphasis is mine):

> "bantime.multipliers" used to calculate next value of ban time **instead of formula**

What am I supposed to do in order to use `bantime-increment.formula`? Set `bantime-increment.multipliers` to an empty string?

### Notify maintainers

@Izorkin You committed https://github.com/NixOS/nixpkgs/commit/f1d7dfe29f091639d935358f2d3a4ee94973d30a, do you know how to use `bantime-increment.formula`?

@pennae @ncfavier

**Comment by Izorkin** [comment]
Perhaps I got confused with options when creating PR.

@sebres please help.
Which `bantime` options are used when `bantime.increment = true` is active? And `bantime.formula` is used only when `bantime.increment = false`

**Comment by sebres** [comment]
Either `bantime.formula` or `bantime.multipliers` must be specified.
By default `bantime.formula` is `bantime * (1<<min(bancount,20)) * banfactor`, that also corresponds the multipliers `1, 2, 4, 8, 16 ...` by factor 1.

> And `bantime.formula` is used only when `bantime.increment = false`

No, by disabled `bantime.increment` no ban prolongation would happen at all.

**Comment by Izorkin** [comment]
Thanks, I'll redo configuration.

**Comment by bjornfor** [comment]
Looks like this was fixed in https://github.com/NixOS/nixpkgs/pull/226693, closing.
