### ISSUE TITLE
Missing documentation: Override compile flags for a package

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#22668]
## Issue description

I cannot find any documentation how to override compile flags for a single package.

For example, I want to build `pkgs.dmenu` with `-O3` and `-march=native`.
One step further, I'd love to have a helper function I could pass packages to, which automatically overrides certain flags, E.G.:

```nix
let
  dmenu = util.optimizeWithFlags [ "-O3", "-march=native" ] pkgs.dmenu;
  mutt = util.optimizeWithFlags [ "-march=native" ] pkgs.mutt;
in
  [ mutt dmenu ]
```

**Comment by FRidh** [comment]
I think the simplest method would be to use `overrideAttrs` and pass the new flags as you would pass any other change.

**Comment by matthiasbeyer** [comment]
I guess I'm misunderstanding something here. I always thought `overrideAttrs` would override the inputs how the package is called?

As in:

```nix
{ stdenv, pkgs, dependency }: # override "dependency"
mkDerivation { ... }
```

Also: `makeFlags` must be passed in the `buildPhase`, so I must override the `buildPhase`, am I right? But packages like `dmenu` or `mutt` do not have a `buildPhase` - how to override it then?

**Comment by FRidh** [comment]
`overrideAttrs` overrides the arguments passed to `mkDerivation`, so it overrides what you put inside of `mkDerivation { ... }`.

`makeFlags` is a parameter of `mkDerivation` so if you update it, the `buildPhase` should take that into account.

**Comment by FRidh** [comment]
The generic builder / `stdenv.mkDerivation` already defines phases https://nixos.org/nixpkgs/manual/#sec-stdenv-phases, so the `buildPhase` already exists.

In some cases we explicitly pass a `buildPhase` because we want to do things differently. In that case passing `makeFlags` won't work unless our new `buildPhase` takes that parameter in account.

**Comment by matthiasbeyer** [comment]
Okay, I came up with this:

```nix
  optimizeForThisHost = pkg:
    pkgs.lib.overrideDerivation pkg (old: {
      buildPhase = ''
        makeFlagsArray=(CFLAGS="$CFLAGS -fPIC -O3 -march=native")
      '';
    });
```

but it overrides the CFLAGS and removes the old ones (despite I use `$CFLAGS` in there).
Using `overrideAttrs` did not work:

```nix
  optimizeForThisHost = pkg:
    pkg.overrideAttrs (old: {
      makeFlags = ''${old.makeFlags} CFLAGS="$CFLAGS -fPIC -O3 -march=native'';
    });
```

results in `error: attribute ‘makeFlags’ missing`.

**Comment by FRidh** [comment]
Does the package you test against have `makeFlags` defined? If it doesn't, then obviously `old.makeFlags` is going to error.

**Comment by FRidh** [comment]
maybe use
```
makeFlags = [] ++ optionals (builtins.hasAttr 'makeFlags' old) [ "flag1" "flag2" ];
```

**Comment by matthiasbeyer** [comment]
This just does not work as I want it to:

```nix
  optimizeForThisHost = pkg:
    pkg.overrideAttrs (old: {
      makeFlags = ["-fPIC" "-O3" "-march=native"] ++
        (pkgs.stdenv.lib.optionals (builtins.hasAttr "makeFlags" old)) old.makeFlags;
        # I guess is this is what you meant with the snippet above
    });
```

gets me:

```
[...]
no configure script, doing nothing
building
make flags: SHELL=/nix/store/6yvwnldl0lzkx382ci7ljbqcg0yjg5gx-bash-4.4-p5/bin/bash -fPIC -O3 -march=native   
make: invalid option -- 'a'
make: invalid option -- 'c'
make: invalid option -- '='
make: invalid option -- 'a'
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Usage: make [options] [target] ...
Options:
[...]
```

**Comment by FRidh** [comment]
ah, you want CFLAGS instead of make flags, my bad. 
Just passing `CFLAGS` should be sufficient, however, it depends on how the configure script deals with it. 
Judging from their [script](http://git.suckless.org/dmenu/tree/config.mk) (if I get it correctly) they don't listen to what CFLAGS one passes. 

Our compiler listens to `NIX_CFLAGS_COMPILE`. If you pass your flags via that env var it should be passed along. Note that what you see during building, 
```
CFLAGS   = -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/X11R6/include/freetype2 -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -DVERSION="4.6" -DXINERAMA
```
is before the compiler actually gets to work and thus incorrect.

**Comment by matthiasbeyer** [comment]
> Note that what you see during building,
> `CFLAGS   = -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/X11R6/include/freetype2 -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -DVERSION="4.6" -DXINERAMA`
> is before the compiler actually gets to work and thus incorrect.

I'm pretty sure that's not accurate, as the `Makefile` of `dmenu` prints it...

**Comment by FRidh** [comment]
exactly, which is *before* the compiler runs. Therefore NIX_CFLAGS_COMPILE aren't shown.

**Comment by matthiasbeyer** [comment]
So, from what I understand, this snippet should be enough:

```
 pkgs.lib.overrideDerivation (pkgs.dmenu) (old: { NIX_CFLAGS_COMPILE = "-O3 -march=native"; })
```

but I have no way to check whether this gets actually passed to the compiler, as the Makefile does not print what exactly it is doing?

**Comment by matthiasbeyer** [comment]
It seems to work as intended. Please leave this issue open, I will write up this for the documentation after my exam on thursday (or before, ... as procrastination)!

**Comment by FRidh** [comment]
Indeed, `NIX_CFLAGS_COMPILE` should be documented and any some more examples would be nice to have.

**Comment by matthiasbeyer** [comment]
Closing this as #23123 is closed. Not sure whether it is in master, though.
