### ISSUE TITLE
Package request: buck2

### ISSUE THREAD

**Issue by nickgerace** [NixOS/nixpkgs#226677]
**Project description**

> "Buck2, a large scale, fast, reliable, and extensible build tool developed and used by Meta. Buck2 supports a variety of languages on many platforms.
>
> Buck2's core is written in [Rust](https://www.rust-lang.org/). [Starlark](https://github.com/bazelbuild/starlark), which is a deterministic, immutable dialect of Python, is used to extend the Buck2 build system, enabling Buck2 to be language-agnostic. With Starlark, users can define their own custom rules.
>
> Buck2 leverages the Bazel spec of [Remote Build Execution](https://bazel.build/remote/rbe) as the primary means of parallelization and caching, which increases the importance of idempotency (no matter how many times an operation is performed, it yields the same result) and hermeticity (code is sealed off from the world), giving the right results, reliably.
>
> Buck2 multi-language support includes C++, Python, Java, Go, Rust, Erlang, OCaml, and more."
>
> -- https://buck2.build/docs/

**Metadata**

* homepage URL: https://buck2.build/
* source URL: https://github.com/facebook/buck2
* license: MIT and Apache 2.0
* platforms: linux and darwin (might also work on other platforms)

**Additional Notes**

It's worth noting that `buck2` appears to be updating off the `latest` branch with a re-created `git` tag upon each "release". It may be the case that `buck2` doesn't make sense to be in `nixpkgs` right now, but perhaps folks have ideas on what it could look like to update `buck2` automatically.

EDIT (17 Apr 2023): I suspect the package will go in `pkgs/development/tools/build-managers`. It's also worth adding the following note from the source URL's `README`...

> "Build uses prebuilt `protoc` binary from [protoc-bin-vendored](https://crates.io/crates/protoc-bin-vendored) crate. If these binaries to do not work on your machine (for example, when building for NixOS), path to protoc binary and protobuf include path can be specified via `BUCK2_BUILD_PROTOC` and `BUCK2_BUILD_PROTOC_INCLUDE` environment variables."

**Comment by divanorama** [comment]
Didn't try it out myself, but this may work https://github.com/thoughtpolice/buck2-nix/blob/main/buck/nix/buck2/default.nix

**Comment by nickgerace** [comment]
I'm getting close to publishing a PR actually :) Should be up soon.

**Comment by nickgerace** [comment]
**Update:** adding packaging to the upstream flake may be the best idea for now.

Either nixpkgs will need to support Rust-based packages with nightly toolchains (unlikely and for good reasons!) or `buck2` will need to be buildable, and intentionally so, not as a hack, with stable Rust (linked issue: https://github.com/facebook/buck2/issues/265). The good news is that caching solutions exist and @thoughtpolice's work in [buck2-nix](https://github.com/thoughtpolice/buck2-nix) should provide a good bluepoint for where to start with an upstream contribution.

_Full Context: https://github.com/NixOS/nixpkgs/pull/232471#issuecomment-1553481540_

Fortunately, `reindeer` likely will not have the same issue being included in nixpkgs, so I am authoring a PR to add reindeer (issue: https://github.com/NixOS/nixpkgs/issues/232693).

**Comment by thoughtpolice** [comment]
As of yesterday, I have a flake available on my `buck2` fork that you can use to consume the `buck2` binary in your downstream projects easily. I plan on semi-regular-kinda-ish updating it and rebasing on trunk, and eventually contributing it upstream; see also https://github.com/facebook/buck2/issues/308

Flake usage is easy. Something like the following should work where you can use `b2` or `buck2.packages."${system}".buck2` inside your flake outputs to refer to it, and you can put it in your `devShells` environment, etc:

```nix
{
  description = "Buck2 demo";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    buck2.url = "github:thoughtpolice/buck2";
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay, buck2 }:
  outputs = { self, nixpkgs, flake-utils, buck2 }:
    flake-utils.lib.eachDefaultSystem (system: let
      b2 = buck2.packages."${system}".buck2;
    in ...;
}
```

You can also get a binary in your `$PATH` with `nix profile install github:thoughtpolice/buck2`

**Comment by thoughtpolice** [comment]
As of #243148, there are now buck2 binaries, thanks to the Meta team doing releases! They can be updated every two weeks easily. So that means you don't need a Flake, cache, or any expensive build steps.

Please let me know if the binary doesn't work for you; I've done some light testing, and if things are broken somehow, we can pull it or figure something out.

**Comment by thoughtpolice** [comment]
Two side notes:

- I will probably migrate the flake to a new repository, so that I don't have to keep my main development fork clean at the moment.
- We can probably close this now, I think.

**Comment by nickgerace** [comment]
Thanks for the help @thoughtpolice! I believe #243148 does close this issue since `buck2` is now in nixpkgs. Great work and thank you again :)
