### ISSUE TITLE
`nix-env -u` replaces nixos.audacious with nixos.audaciousQt5

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#22673]
I guess it's a political question whether Qt is an upgrade from Gtk, but for whatever reason the Qt version appears to have text in the toolbar instead of icons, so I'd like to stick with the inferior Gtk for now.

## Issue description

nixos.audacious{,Qt5} have the same name, but versions 3.8 and 3.8.1 respectively.

### Steps to reproduce

```
$ nix-env -iA nixos.audacious
$ nix-env -u audacious
```

## Technical details

```
$ nixos-version
17.03pre100522.01fef3f (Gorilla)
$ nix-env --version
nix-env (Nix) 1.11.6
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre100522.01fef3f"
```

**Comment by FRidh** [comment]
What I understand from [their website](http://audacious-media-player.org/download) they support both. If we want to support both they should have different names.

**Comment by Artoria2e5** [comment]
For what it's worth, the qt/gtk separation was again abolished in 7f64f213908a5e6cd10a32472eb766d34f37d6f3. I wouldn't really blame gebner for what happened though: the upstream has indeed stated that they want to focus on Qt in the future.

That said, anyone interested is still welcome to make a Qt-less build; https://aur.archlinux.org/packages/audacious-gtk3 shows it's still possible.
