### ISSUE TITLE
Some user services have undeclared dependencies on X

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#22670]
The Redshift user service needs X to be running before it can start. Currently it works because it simply fails repeatedly, and usually the delay between restarts is enough that after a while X happens to have started.

Probably the right thing to do is to depend on the new `graphical-session` user target in systemd 232.

This also affects the arbtt service, and perhaps others.

**Comment by FRidh** [comment]
I think this commit is relevant https://github.com/NixOS/nixpkgs/commit/882391a1620f5179eab0f9f4b96f85af875cbb34
cc @fpletz

**Comment by fpletz** [comment]
Yeah, the problem is that we can't depend on X directly when the user session starts. The new systemd 232 has graphical session targets which we have to try to integrate in order to fix this.

**Comment by peterhoeg** [comment]
@fpletz the problem with ```wantedBy = [ "default.target" ];``` is that a user instance spawned for root would also trigger the running of redshift which we do not want.

Have you done any work on converting the DE's to run via proper systemd targets?

**Comment by fpletz** [comment]
@peterhoeg Exactly. I haven't done any testing so far but here is some context: https://github.com/systemd/systemd/pull/3678 (also look at the linked mailing list thread).

**Comment by peterhoeg** [comment]
I know about that - I have some done some work here to make the kde services systemd activatable via dbus and use the new units in 232 to work like what Martin mentions in that PR but it is still very much work in progress and most definitely will not make it for 17.03.

**Comment by michaelpj** [comment]
Fixed some time ago.
