### ISSUE TITLE
Systemd `graphical-session.target` does nothing

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#22671]
The new `graphical-session` target is supposed to provide a common place for services that require a graphical session to be running.

However, currently (using XFCE at least) this target has no interesting dependencies, so in practice depending on it has no effect.

```
> systemctl --user list-dependencies graphical-session.target
graphical-session.target
● └─basic.target
●   ├─paths.target
●   ├─sockets.target
●   └─timers.target
```

Looking at the examples in the manual, I *think* what's supposed to happen is that you create e.g. `gnome-session.target` which has `BindsTo=graphical-session.target`, so that if you are using GNOME then that will bring up `graphical-session.target`. It's possible that we'll get this for free with some upstream units, but we currently don't for XFCE (I haven't tried any other WMs).

I came across this while trying to fix https://github.com/NixOS/nixpkgs/issues/22670.

**Comment by peterhoeg** [comment]
A lot of work has to go into converting the existing DE's to use systemd as opposed to the current session scripts and until that happens, you are not going to get proper support for ```graphical-session.target```.

I have done some work on KDE for this, but it's not ready yet.

One quick workaround is to manually define a target like ```kde-session.target``` and have it depend on ```graphical-session.target``` and structure your dependencies accordingly. You have to have another target depending on graphical-session as it cannot be activated manually.

Then after X has launched, run ```systemctl --user kde-session.target``` in a terminal.

**Comment by michaelpj** [comment]
This got fixed, I think.

**Comment by peterhoeg** [comment]
It didn't. To my knowledge none of the major DEs in NixOS have implemented support for this.

**Comment by michaelpj** [comment]
I was thinking of https://github.com/NixOS/nixpkgs/pull/26094, but perhaps that doesn't count as a "proper" fix?

**Comment by peterhoeg** [comment]
Fixed for the use-case mentioned here.
