### ISSUE TITLE
`teams` missing icon on KDE

### ISSUE THREAD

**Issue by JonBoyleCoding** [NixOS/nixpkgs#226729]
### Describe the bug

On KDE the icon for `teams` is not being loaded in the launcher. I presume it's related to the closed PR https://github.com/NixOS/nixpkgs/pull/182111, but I don't see any other effort to fix the issue (if I'm wrong I'm happy to close the issue).

### Steps To Reproduce
1. Install `teams` with a kde desktop and view in the launcher

### Expected behavior
Icon to be display in the launcher.

### Screenshots
![image](https://user-images.githubusercontent.com/630329/232626984-094d35ce-2caa-4294-a724-9e44c8b1063e.png)

### Notify maintainers

@liff @tricktron

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.3689.fda0d99c2cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(myusername): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by liff** [comment]
Opened #226903 to hopefully fix. @JonBoyleCoding can you test it to see if it helps?

**Comment by JonBoyleCoding** [comment]
@liff Looks like https://github.com/NixOS/nixpkgs/pull/226903 works!

![image](https://user-images.githubusercontent.com/630329/232937708-aeb93592-f6d6-4c51-882c-e7a908dee5ed.png)
