### ISSUE TITLE
dog installs a package which has been dead for at least 12 years 

### ISSUE THREAD

**Issue by secondhand-container** [NixOS/nixpkgs#226719]
nixpkgs.dog installs a 12 year old package, even though the most people in todays day and age would expect dogdns to install.

### Steps To Reproduce
1. nix-shell -p dog
2. [nix-shell:~]$ dog example.com
3. dog: example.com: No such file or directory

### Expected behavior
1. nix-shell -p dogdns
2. [nix-shell:~]$ dog example.com
3. A example.com. 1h15m02s   REDACTED

### Screenshots
none.

### Additional context

I'm kinda new to the nix community so please be fair if I missed something or misunderstood some concept.

However, I think most users would not expect the old dog(cat replacement) package to install, instead of the dog-dns-client package.

I tried to look up the maintainers / their repository and also could not find anything besides 2 unreachable sites.

Since the package seems dead/unmaintained/unknown i would propose renaming both packages, so (new) users would get the expected package, even without checking out nixpkgs search or running into this confusing case. 

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(viktor): `"darwin, nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/Users/viktor/.nix-defexpr/channels/nixpkgs`
```

**Comment by justinkb** [comment]
this is definitely not happening

**Comment by TheCapsLock** [comment]
> this is definitely not happening

Sorry but this happens.

```shell
dog A google.com                                                                                                                                       :(
dog: A: No such file or directory
dog: google.com: No such file or directory
```

Confirmed by : https://github.com/NixOS/nixpkgs/blob/nixos-26.05/pkgs/by-name/do/dog/package.nix#L33

**Comment by secondhand-container** [comment]
It’s not what justinkb meant, he meant that the rename will not be happening. Yes, the dog package installs the cat alternative, which is expected

Renaming any of these packages, just because of the age of the package, would very likely break stuff for people actually expecting the cat alternative

**Comment by TheCapsLock** [comment]
You're right it's not a good reason to rename a package ; what is the name of the package to install dog (dns) ? (I've searched but not found it)

**Comment by secondhand-container** [comment]
https://search.nixos.org/packages?channel=25.11&query=dogdns

**Comment by TheCapsLock** [comment]
doggo seems to replace dogdns : 

> error: 'dogdns' has been removed as it is unmaintained upstream and vendors insecure dependencies. Consider switching to 'doggo', a similar tool.

Thanks!
