### ISSUE TITLE
Package request: pytorch with vulkan support

### ISSUE THREAD

**Issue by theoparis** [NixOS/nixpkgs#226998]
**Project description**

I wanted to build pytorch with vulkan support but I can't seem to find an existing way to do it. There doesn't seem to be a vulkan option... 😕 

**Metadata**

See https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/torch/default.nix.

**Comment by kira-bruneau** [comment]
It looks like the Vulkan backend is a prototype feature: https://pytorch.org/tutorials//prototype/vulkan_workflow.html.

Have you tried torchWithRocm for AMD cards or torchWithCuda for NVIDIA cards?

**Comment by theoparis** [comment]
I have not tried ROCM but I heard it only supports specific newer AMD cards unlike vulkan...

**Comment by kira-bruneau** [comment]
Oh yep the 6600 XT isn't officially supported on ROCm, it targets gfx1030.

It looks like some people were able to get it working though by setting `HSA_OVERRIDE_GFX_VERSION=10.3.0`: https://github.com/RadeonOpenCompute/ROCm/issues/1756#issuecomment-1160386571
