### ISSUE TITLE
maintainers/scripts/generate-kde-plasma.sh is missing

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#22690]
## Issue description

pkgs/desktops/kde-5/plasma/default.nix mentions:

> 1. Update the URL in `maintainers/scripts/generate-kde-plasma.sh` and run
>    that script from the top of the Nixpkgs tree.

However that script doesn't exist neither on master nor 16.09.

Cc: @ttuegel 

## Technical details

* NixOS: 17.03.git.b9d5ad1763M (Gorilla)
* Nix: nix-env (Nix) 1.11.6
* nixpkgs: 17.03.git.663844af9aM

**Comment by FRidh** [comment]
You need to use `maintainers/scripts/fetch-kde-qt.sh` and give as argument the tree that you like to change, e.g.
```
$ maintainers/scripts/fetch-kde-qt.sh pkgs/development/libraries/kde-frameworks/
```
Furthermore, before running this, you need to update the `fetch.sh` script, in this case
```
pkgs/development/libraries/kde-frameworks/fetch.sh
```

At least, that's how I understood it. I'm currently testing the Frameworks and Applications updates. @ttuegel mentioned yesterday we keep the current Plasma, 5.8 LTS.

**Comment by ttuegel** [comment]
I updated the documentation of the affected files.
