### ISSUE TITLE
Package request: sql-language-server

### ISSUE THREAD

**Issue by NotAShelf** [NixOS/nixpkgs#226918]
**Project description**

sql-language-server is an alternative to the now archived [sqls](https://github.com/lighttiger2505/sqls). As sqls is now archived, lspconfig warns users about deprecation on startup. A minor annoyance that should be resolved by packaging sql-language-server for nixpkgs.

**Metadata**

* homepage URL: https://github.com/joe-re/sql-language-server
* source URL: https://github.com/joe-re/sql-language-server
* license: MIT
* platforms: linux, darwin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/203887

**Comment by NotAShelf** [comment]
Didn't notice, apologies.
