### ISSUE TITLE
Default NixOS VM Running Out of Memory 

### ISSUE THREAD

**Issue by rsynnest** [NixOS/nixpkgs#22696]
## Issue description

Running an upgrade (`nix-env -u`) runs out of memory using the default NixOS demo VM image with 1.5GB of RAM, despite the Nix manual recommending only 768MB RAM.

```
$ nix-env -u
GC Warning: Header allocation failed: Dropping block.
Killed
```

### Steps to reproduce
Run default NixOS VM Image with 1.5GB RAM.
Install `nix` `nix-repl`, `man` to user-profile.
run `nix-env -u`.

### Fix
Adding a swapfile is enough to fix this issue.
My recommendation is to edit the default Nix VM Image to include a swapfile by default.
Users who wish to add a swapfile themselves can simply do the following as root
```
# fallocate -l 512M /swapfile
# chmod 600 /swapfile
# mkswap /swapfile
# swapon /swapfile
```
Then edit `/etc/fstab` to add an entry for the swap file:
`/swapfile none swap defaults 0 0`

## Technical details

* System: NixOS 16.09.1502.bb58438 (Flounder)
* Nix version: 1.11.6
* Nixpkgs version: 16.09.1502.bb58438

**Comment by davidak** [comment]
The manual sais on Chapter 2. 9.: "If your machine has a limited amount of memory, you may want to activate swap devices now"

https://nixos.org/nixos/manual/#sec-installation

So when you carefully follow the manual to install NixOS it should be fine.

Do you agree @rsynnest?

**Comment by rsynnest** [comment]
That is fine, but that is in the section for installing NixOS from scratch. I am referring to the default NixOS VM provided under the [Getting NixOS page](http://nixos.org/nixos/download.html). It would make sense if that VM had swap configured and enabled by default. Or if not, then it would make sense to add the  swap recommendation in the "[Running NIx in a VirtualBox Guest](https://nixos.org/nixos/manual/#sec-instaling-virtualbox-guest)" section of the manual.

I haven't tried the AWS AMIs, but I think the same goes for them.

**Comment by davidak** [comment]
@rsynnest a Live CD should not alter the HDD. you can't just automatically create a 1 GB partition on a Windows install.

If you have already a swap partition, you could mount that. Would it be ok to just add some documentation?

You can create a PR for that. Here is the code for the linked page: https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/installation/changing-config.xml#L62

**Comment by rsynnest** [comment]
I'm not referring to a liveCD, I'm referring to the VirtualBox image provided by NixOS.
It is under the header "VirtualBox appliances" on http://nixos.org/nixos/download.html. Excerpt:
> VirtualBox appliances
This is a demo appliance for VirtualBox (in OVA format) that has X11 and KDE enabled, as well as the VirtualBox guest additions. To use it, download the OVA file, open VirtualBox, run “File → Import Appliance” from the menu, select the OVA file, and click “Import”. You can then start the virtual machine. When the KDE login screen appears, you can log in as user demo, password demo. To obtain a root shell, run sudo -i in the KDE terminal (konsole). 
> [VirtualBox appliance, 64-bit Intel/AMD (SHA-256)](https://d3g5gsiof5omrk.cloudfront.net/nixos/16.09/nixos-16.09.1694.019dcc3/nixos-16.09.1694.019dcc3-x86_64-linux.ova)

I also am curious if the AWS AMIs on that same page have the same issue. I doubt there is a way to submit a pull request to alter the Virtualbox OVA or the AWS AMIs

**Comment by matthewbauer** [comment]
:+1: to this. I don't know what the solution is. But it definitely seems like the VirtualBox VM should get swap.
