### ISSUE TITLE
qemu/9p bug mounting nix store into VM

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#22695]
## Issue description

A weird bug found while preparing ```test-driver``` script for https://github.com/NixOS/nixpkgs/issues/22648
It looks like nix store mounted into a qemu virtual machine (```test-driver```mounts it at ```/nix/.ro-store```) may have symlinks pointing to wrong random places (targets of other symlinks)

### Steps to reproduce

test.nix
```

with import <nixpkgs/nixos/lib/testing.nix> { system = builtins.currentSystem; };

(makeTest { 

  nodes = {

    client = { lib, pkgs, ... }: {
      services.xserver.enable = true;

      services.xserver.displayManager.auto.enable = true;

      services.xserver.windowManager.default = "icewm";
      services.xserver.windowManager.icewm.enable = true;
      services.xserver.desktopManager.default = "none";

      programs.bash.enableCompletion = true;
      environment.systemPackages = [
        pkgs.bash-completion
      ];
    };
  };

  testScript = ''
    startAll;

    $client->waitForX;

    $client->sleep(1);
    $client->execute("xterm &");
    $client->sleep(1);
    $client->sendKeys("alt-f10"); # maximize xterm window
    $client->sleep(1);
    $client->sendChars("ls -l /nix/.ro-store/*nixos-system-client-17.03*/sw/share/bash-completion/completions | grep font\n");
    $client->sleep(3);
    $client->screenshot("screen");
    $client->sleep(3000000);
  '';

}).driver
```

run as: ```tests='eval $ENV{testScript}' $(nix-build test.nix)/bin/nixos-test-driver```

Captured screens:

![screen-1](https://cloud.githubusercontent.com/assets/508305/22860315/de025194-f0f1-11e6-8c19-c06babe3d358.png)
![screen-2](https://cloud.githubusercontent.com/assets/508305/22860316/de093be4-f0f1-11e6-8f31-f010c92943a2.png)
![screen-3](https://cloud.githubusercontent.com/assets/508305/22860317/de0b56c2-f0f1-11e6-979a-582a8503202f.png)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03.git.11e1eef (Gorilla) 
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.6  
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.git.11e1eefa9c"

**Comment by volth** [comment]
Probably related: https://github.com/NixOS/nixpkgs/commit/a82810c7a7e62848b75739b1cccddca8f1363c75
I have not yet compiled the kernel without the patch but commenting out "veryloose" in qemu-vm.nix does solve the issue.

**Comment by volth** [comment]
Then the problem will be affect thos who still use kernel 4.4 (I use 4.4 on a laptop because of hardware issues)

**Comment by edolstra** [comment]
No, because 1) this only affects the guest kernel; and 2) the veryloose patch for 4.4 was removed a while ago already.

**Comment by volth** [comment]
1) yes, most tests use 4.9 even if there is 4.4 on host.
2) It was removed, but you just reverted it, so now veryloose patch applied to 4.4; for no purpose.

It may have sense to remove only symlink caching from the veryloose patch, keeping the rest of its features which seems stable. Or at least change "veryloose" to "loose" in the mount params.
Just reverting the patch where the veryloose was moved from 4.4 to 4.9 feels like leaving it in ruined state.

If there are no time/resources to fix/test the feature properly, I can prepare PR removing "veryloose" patch and change mount params to "loose".

**Comment by edolstra** [comment]
Ah sorry, I didn't realize the revert revived the 4.4 patch.

**Comment by edolstra** [comment]
c71a893
