### ISSUE TITLE
Package request: neovim-lsp-zero

### ISSUE THREAD

**Issue by Thiago-Assis-T** [NixOS/nixpkgs#226966]
**Project description**

A Neovim plugin that makes it easy to start an lsp and code completion, using Mason and lsp-config and nvim-cmp

The purpose of this plugin is to bundle all the "boilerplate code" necessary to have nvim-cmp (a popular autocompletion plugin) and nvim-lspconfig working together. And if you opt in, it can use mason.nvim to let you install language servers from inside neovim.

**Metadata**

* homepage URL: https://github.com/VonHeikemen/lsp-zero.nvim
* source URL: https://github.com/VonHeikemen/lsp-zero.nvim
* license: MIT
* platforms: unix, linux

**Comment by jfvillablanca** [comment]
This is available in nixos-unstable
[vimPlugins.lsp-zero-nvim](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/vim/plugins/generated.nix#L4706)
