### ISSUE TITLE
Package request: vscode-extensions.ayqy.browser

### ISSUE THREAD

**Issue by jackyliu16** [NixOS/nixpkgs#227103]
**Project description**
An embedded browser for your VS Code.

**Metadata**

* homepage URL: https://marketplace.visualstudio.com/items?itemName=ayqy.browser
* source URL: https://github.com/ayqy/browser
* license: mit
* platforms: vscode

**Comment by superherointj** [comment]
Have a look in:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/

Read the README.md:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/README.md

Edit:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/default.nix

Build as:

> nix build .#vscode-extensions.publisher-name.extension-name
