### ISSUE TITLE
Package request: vscode-extensions.live-preview

### ISSUE THREAD

**Issue by jackyliu16** [NixOS/nixpkgs#227105]
**Project description**
Hosts a local server in your workspace for you to preview your webpages on.

**Metadata**

* homepage URL: https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server#running-the-extension
* source URL: https://github.com/microsoft/vscode-livepreview
* license: MIT license
* platforms: vscode

**Comment by dooygoy** [comment]
Total beginner here, aspiring maintainer. So I tried until I hit an error:

Create a new directory for the Live Preview extension package:

```nix
nixpkgs on  master 
mkdir -p pkgs/applications/editors/vscode-extensions/live-preview
```

Create a default.nix file in the newly created directory:

```nix
$ touch pkgs/applications/editors/vscode-extensions/live-preview/default.nix
```

Edit the `default.nix`

```nix
code pkgs/applications/editors/vscode-extensions/live-preview/default.nix
```

Update the `version` and `sha256` attributes: To find the version and download URL, visit the Visual Studio Code marketplace page for the extension (http://aka.ms/live-preview) and on page (https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) copy the most recent 14 hours ago `version` number `0.5.2023042001`. To calculate the sha256 hash, use nix-prefetch-url: 

```nix
nix-prefetch-url --unpack "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/live-server/0.5.2023042001/vspackage"
path is '/nix/store/jsjmr1sjia9zr6i1xdpdgps5kg4xq9mv-vspackage'
12zg0lmwljydzgahf6kwgcdvg9m3njss0na6rv2qy7s7y3qhldn0
```

Now how do I add the package to the `all-packages.nix`, I search the section with vscode an find this entry:

```nix
  vscode-extensions = recurseIntoAttrs (callPackage ../applications/editors/vscode/extensions { });
```

Do I add the package like this?

```nix
  inherit (callPackage ../applications/editors/vscode-extensions/live-preview { }) live-preview;
```

When saving the file with this line my Vscode shows in the corner: `stdout maxBuffer length exceeded` and there is an error when building the package.

How do I proceed with this?

**Comment by jackyliu16** [comment]
Sorry, I'm another beginner, so maybe what I say below will have a kind of error.

It seems the current vscode-extension hasn't been place on `pkgs/applications/editors/vscode-extensions/`, but place in `pkgs/applications/editors/vscode/extensions/default.nix` and there is a kind of function like `buildVscodeMarketplaceExtensions` to help you 

maybe you can try to look at `pkgs/applications/editors/vscode/extensions/default.nix` commit and check how other commit to it, 
*actually in May original mind, it is not easy to get it and I have no understanding about how vscode-extension work with vscode thus i choose to make a issue about it*

**Comment by dooygoy** [comment]
OK that's very helpful! I will investigate it.
