### ISSUE TITLE
Vmware-horizon-client shows black screen on connect to remote client

### ISSUE THREAD

**Issue by THERAAB** [NixOS/nixpkgs#227262]
### Describe the bug
When accessing remote machine with vmware-horizon-client, I am able to get past authentication screens and launch a desktop, but it shows only a black screen. It started happening on nixos-unstable sometime last week, most likely after this commit: https://github.com/NixOS/nixpkgs/commit/f63a12f296b806a1b838d6fd8eef99fa65929649

### Steps To Reproduce
1. Launch VMWare client
2. Connect to a remote to a desktop
3. Black Screen instead of viewing said desktop

### Expected behavior
Connecting to the desktop

### Screenshots
It's a black screen

### Notify maintainers
@Atemu @buckley310 

### Metadata
Sorry I've already rolled back as I need VMWare for work, but it was most recent nixos-unstable pulled ~15 min ago.

**Comment by buckley310** [comment]
https://github.com/NixOS/nixpkgs/pull/227123

**Comment by THERAAB** [comment]
thanks, I will watch that PR. Should I close this?

**Comment by buckley310** [comment]
Might as well leave it open until the PR is merged.

**Comment by buckley310** [comment]
Also here is a workaround that will allow you to update.
```
nixpkgs.overlays = [
  (final: prev: {
    vmware-horizon-client =
      prev.vmware-horizon-client.override
        { buildFHSEnv = prev.buildFHSEnvChroot; };
  })
];
```

**Comment by THERAAB** [comment]
@buckley310 thank you, the workaround works fine.
