### ISSUE TITLE
haskellPackages.monky doesn’t work

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#22721]
## Issue description

https://github.com/monky-hs/monky uses `ghc` in `PATH` to compile your configuration (similar to XMonad). See https://github.com/monky-hs/monky/blob/c59cb388586ff68aba8f8a5fdd75930884bc2370/bin/Main.hs#L161.

But the GHC we typically have in `PATH` doesn’t know about the `Monky` module.

One temporary way to solve this is to use: `(haskellPackages.ghcWithPackages (ps: [ ps.monky ]))` instead of `haskellPackages.monky`, but the `monky` package causes collisions with some other packages, e.g. with `[ monky stack ]`:

```
building path(s) ‘/nix/store/saly470045shz2pfw48kwkxspicdl887-ghc-8.0.1-with-packages’
collision between `/nix/store/j4xn9576c6gfs7066m3c410jiw3gydv0-monad-loops-0.4.3/lib/ghc-8.0.1/package.conf.d/monad-loops-0.4.3-1xZFtRVMQPC4X8bjTBWqNi.conf' and `/nix/store/v6wzvbbwcracy4c5x1a88mxcp37fx3q1-monad-loops-0.4.3/lib/ghc-8.0.1/package.conf.d/monad-loops-0.4.3-1xZFtRVMQPC4X8bjTBWqNi.conf'
builder for ‘/nix/store/ajym0p4wdxszb8bqdg9q7hpq1f50xbhx-ghc-8.0.1-with-packages.drv’ failed with exit code 255
```

### Steps to reproduce

1. Add `haskellPackages.monky` to `environment.systemPackages`.
2. Rebuild.
3. Run `monky`:

```
% monky
[1 of 1] Compiling Main             ( monky.hs, build/Main.o ) [Monky.Outputs.Ascii changed]

monky.hs:1:1: error:
    Failed to load interface for ‘Monky’
    Use -v to see a list of the files searched for.

monky.hs:2:1: error:
    Failed to load interface for ‘Monky.Modules’
    Use -v to see a list of the files searched for.

monky.hs:4:1: error:
    Failed to load interface for ‘Monky.Examples.CPU’
    Use -v to see a list of the files searched for.

monky.hs:5:1: error:
    Failed to load interface for ‘Monky.Examples.Memory’
    Use -v to see a list of the files searched for.

monky.hs:7:1: error:
    Failed to load interface for ‘Monky.Outputs.Ascii’
    Use -v to see a list of the files searched for.
Compilation failed
```

## Technical details

* System: 16.09.1586.86b3957 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1586.86b3957"

**Comment by michalrus** [comment]
If you want something potentially cleaner for now, this works:

```nix
    (lib.overrideDerivation (haskellPackages.ghcWithPackages (hs: [ hs.monky ])) (oldAttrs: {
      postBuild = oldAttrs.postBuild + ''
        . ${makeWrapper}/nix-support/setup-hook
        mv $out/bin $out/libexec
        mkdir -p $out/bin
        ln -s $out/libexec/monky $out/bin/
        wrapProgram $out/libexec/monky --prefix PATH : "$out/libexec"
      '';
    }))
```

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by cdepillabout** [comment]
Looks like there hasn't been updates on this in a few years, I'll go ahead and close.

If anyone is still running into this and hoping for it to get fixed, please post a comment and we can re-open.
