### ISSUE TITLE
Tailscale: support nginx-auth

### ISSUE THREAD

**Issue by Dan-Theriault** [NixOS/nixpkgs#227380]
## Issue description

The nixpkgs tailscale package (and the NixOS module)  should support the [tailscale nginx-auth proxy](https://tailscale.com/blog/tailscale-auth-nginx/).

I have a working configuration with nginx-auth enabled:

```
  services.tailscale = {
    enable = true;
    permitCertUid = "caddy";
    package = pkgs.tailscale.override {
      buildGoModule = args: pkgs.buildGoModule (args // {
        subPackages = args.subPackages ++ [ "cmd/nginx-auth" ];
        postInstall = args.postInstall + ''
          sed -i -e "s#/usr/sbin/tailscale.#$out/bin/#" ./cmd/nginx-auth/tailscale.nginx-auth.service
          install -D -m0444 -t $out/lib/systemd/system ./cmd/nginx-auth/tailscale.nginx-auth.service
          sed -i -e "s#/var/run#/run#" ./cmd/nginx-auth/tailscale.nginx-auth.socket
          sed -i -e "/^Wants/d" ./cmd/nginx-auth/tailscale.nginx-auth.service
          sed -i -e "/^After/d" ./cmd/nginx-auth/tailscale.nginx-auth.service
          install -D -m0444 -t $out/lib/systemd/system ./cmd/nginx-auth/tailscale.nginx-auth.socket
        '';
      });
    };
  };
  systemd.sockets."tailscale.nginx-auth".wantedBy = [ "multi-user.target" ];
  systemd.services."tailscale.nginx-auth".after = [ ];
  systemd.services."tailscale.nginx-auth".wants = [ ];
```

Is there interest in getting this into nixpkgs?

**Comment by KFearsoff** [comment]
I have constructed a similar overlay myself for the sake of `nginx-auth`. I think there's no harm to include it upstream. I'll submit a PR when I have the time for it.

**Comment by bachp** [comment]
I think this is now supported

**Comment by Dan-Theriault** [comment]
It's now supported, but AFAICT only with nginx; despite the name, tailscale-nginx works with traefik and caddy as well as nginx. I use it with caddy. Happy to close this out & open tickets for caddy/traefik support.

**Comment by bachp** [comment]
@Dan-Theriault I think it makes sense to close this and open a new issue to extend support to traefik and caddy
