### ISSUE TITLE
Plasma5 can't maximize by double clicking

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#22733]
The below feature does not work on `16.09.git.89c567c (Flounder)`
![screenshot_20170213_113712](https://cloud.githubusercontent.com/assets/23479333/22880048/f1cb4dc6-f1e0-11e6-9fdd-b52ffacfdcb5.png)

**Comment by FRidh** [comment]
cc @ttuegel

**Comment by lverns** [comment]
Just for reference, setting double click to both maximize and minimize the works fine for me, but I'm running `16.09.1512.6b28bd0 (Flounder)`. I don't know if this is newer or older than the OP's version.

**Comment by fubarbaz** [comment]
The implementation of Plasma probably depends on some unreliable mechanism to get its messages to the X server. This in turn causes the problem observed. In a rebooted environment I currently do not experience the issue, but that doesn't mean the issue is fixed. (Having a reliable mechanism would).

In Emacs, there should be a message displayed saying that it tried to do a maximize, but that it failed, because of some reason.

**Comment by ttuegel** [comment]
This is clearly an upstream issue.
