### ISSUE TITLE
Update request: python3Packages.pip 23.0.1 → 23.1

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#227364]
- Package name: pip
- Latest released version: 23.1

- Current version on the unstable channel: 23.0.1
- Current version on the stable/release channel: 22.2.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by doronbehar** [comment]
cc @FRidh

**Comment by FRidh** [comment]
pip 23.1 [removed support](https://github.com/pypa/pip/issues/8559#issuecomment-1257150807) for `setup.py install` which is used to bootstrap pip. We need to find a solution.

The proper way forward is to implement bootstrapping using `build` and `installer`.
- https://github.com/NixOS/nixpkgs/pull/232451
- https://github.com/NixOS/nixpkgs/pull/105714

**Comment by doronbehar** [comment]
For anyone subscribed this may be relevant: A setup hook for `pypa/build` is added in #239969 .

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/commit/43c7517c80f96c961f4f80707b9e8fe57b3bd3d0
