### ISSUE TITLE
Can't install cookie_extractor

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#22731]
```
gem install --user cookie_extractor
WARNING:  You don't have /home/foo/.gem/ruby/2.3.0/bin in your PATH,
          gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Errno::EROFS)
    Read-only file system @ dir_s_mkdir - /nix/store/733jqj11n16qfwkx1dvlzlv37awwgr33-ruby-2.3.1-p0/lib/ruby/gems/2.3.0/extensions/x86_64-linux
```

**Comment by lheckemann** [comment]
Unfortunately it's a little more complicated on NixOS than just using the system gem out of the box. You'd either want to install ruby itself for your user (independently of nix; I'm not sure to what extent this is supported by ruby and to what extent it will work), or [package cookie_extractor with bundix](https://nixos.org/nixpkgs/manual/#sec-language-ruby) then install that.
