### ISSUE TITLE
Spotify, can't override nss

### ISSUE THREAD

**Issue by materusPL** [NixOS/nixpkgs#227449]
### Describe the bug
I'm overriding nss package to nss_latest for spotify to be able to open links in firefox. After updating inputs for my config fails.
I have `(pkgs.spotify.override {nss = pkgs.nss_latest;});` in config.

### Steps To Reproduce
1. override nss for spotify
2. try to rebuild config

### Expected behavior
Nss should get overridden successfully, not fail.

### Screenshots
![obraz](https://user-images.githubusercontent.com/28183516/233651249-72990a00-02d6-46da-b462-77c3f00e42fb.png)

### Additional context
It seems to be caused by commit adding support for macos. It seems I can only override default.nix arguments which are now `{ lib, stdenv, callPackage }:`

### Notify maintainers

@Enzime 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.11-zen1, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mcwitt** [comment]
@materusPL in the meantime, overriding `callPackage` seems to be a workaround. I'm using the following to override `deviceScaleFactor`:

```nix
pkgs.spotify.override {
  callPackage = p: attrs: pkgs.callPackage p (attrs // { deviceScaleFactor = 2.0; });
}
```

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/pull/229165

**Comment by gvolpe** [comment]
Facing the same issue, as I had an override with `deviceScaleFactor`. Looks like this was broken in #195473 (cc @Enzime ).
