### ISSUE TITLE
Build failure: boinc

### ISSUE THREAD

**Issue by ak2k** [NixOS/nixpkgs#227462]
### Steps To Reproduce

1. in configuration.nix on aarch64:
```
  services.boinc = {
    enable = true;
    dataDir = "/var/lib/boinc";    # default location where data is stored
  };
```

### Build log

```
error: i686 Linux package set can only be used with the x86 family.
```
NixOS build trace here: https://github.com/NixOS/nixpkgs/commit/f63a12f296b806a1b838d6fd8eef99fa65929649#commitcomment-110009622

### Additional context

My system is aarch64.

I think the error started in this commit: https://github.com/NixOS/nixpkgs/commit/f63a12f296b806a1b838d6fd8eef99fa65929649#commitcomment-110009622

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05pre474054.85b081528b9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by Atemu** [comment]
Can you confirm whether it works on https://github.com/NixOS/nixpkgs/commit/327a9c55a3294d58a28ddc6ca7eac5cd10b55aec?

**Comment by Atemu** [comment]
nixos-rebuild build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/327a9c55a3294d58a28ddc6ca7eac5cd10b55aec.tar.gz

**Comment by Atemu** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/227479

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/110303 would fix buildFHSEnvBubblewrap, just needs someone to pick it up
