### ISSUE TITLE
closure size: weechat

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#22746]
## Issue description
Closure for weechat's default configuration is ~470MB.

Key factors:
 - Dependency chain `weechat → guile → libtool → gcc`. I'm not 100% sure about this one, but surely one of those links isn't necessary? Guile does not depend on libtool on debian, so I suspect that that's the incorrect link.
 - Dependency on language interpreters in general — the current standard configuration pulls in guile, ruby, python, perl and tcl, and some of these account for about 50MB each (not counting their own dependencies). The only references to these interpreters are in shared libraries dedicated to them (except Python, where the wrapper script also sets some env variables), so I think it would make sense to split the weechat derivation, allowing configurations that use significantly less space while still allowing reliance on binary caches (which disabling the appropriate interpreters at build time does not). Any thoughts on the complexity/space and time trade-off? 

Version 16.09.1650.d2cd8a0 (Flounder)

**Comment by rnhmjoj** [comment]
Lua, Perl, Python, Ruby, Tcl and Guile together seems a little too much. Its description is "A fast, light and extensible chat client": sure it is extensible but not that light (at least on the disk). +1 on splitting.

**Comment by FRidh** [comment]
What keeps you from overriding the expression and turning off that you do not need?

**Comment by lheckemann** [comment]
Nothing in particular, but the way weechat is structured lends itself very well to including/excluding the features without any recompilation, so they can be enabled/disabled without losing the ability to rely on a binary cache as I mentioned in the original post. I think it would be good to take advantage of this.

**Comment by lheckemann** [comment]
I'll create a new issue for guile's closure size as it's not directly related to this.

**Comment by vcunat** [comment]
For reference, the guile problem was discussed on https://github.com/NixOS/nixpkgs/issues/22757 and fixed on master/unstable.
