### ISSUE TITLE
qutebrowser: --backend webengine does not work

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#22753]
## Issue description

The QtWebEngine backend does not seem to be built. Happens on nixos-unstable channel too.

### Steps to reproduce

Launch qutebrowser with `qutebrowser --backend webengine`

## Technical details

* System: 16.09.1647.ff7777b (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1647.ff7777b

**Comment by FRidh** [comment]
cc @abbradar

**Comment by fpletz** [comment]
Works with #22766. Merged to master. Should be in unstable channel soon.
