### ISSUE TITLE
vim: does not build reproducibly

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#227598]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A vim --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A vim)
```

### Additional context

It seems for me locally it creates a `vimdiff` symlink to the `vim` executable, where in the nix cache that only exists for the `vim-full` derivation

This package is part of the minimal iso build closure, so it shows up in http://reproducible.nixos.org/nixos-iso-minimal-r13y/

/cc @dasJ @equirosa

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/227677
