### ISSUE TITLE
closure size: guile depends on gcc

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#22757]
## Issue description
Guile depends on libtool (via propagated-native-build-inputs) and libtool depends on gcc, and I don't think this is necessary. Not sure which link is wrong though. FWIW guile doesn't depend on libtool on debian.

Version 16.09.1650.d2cd8a0 (Flounder)

**Comment by vcunat** [comment]
I staged a conservative fix for this.  I don't dare picking such things to 16.09, as they're potentially destabilizing.

**Comment by lheckemann** [comment]
Fair enough, closure size isn't exactly an issue that will break many things, and it's not too long until 17.03. Thanks!
