### ISSUE TITLE
Configuration evaluation fails with gcc.arch set

### ISSUE THREAD

**Issue by Shawn8901** [NixOS/nixpkgs#227501]
### Describe the bug
When someone wants to set gcc.arch on their system configuration the evaluation fails with the following error.

```console
error: value is null while a list was expected

       at /nix/store/0cvpq5a796zz8gbya5z4wy0qph73phr8-source/pkgs/stdenv/generic/make-derivation.nix:452:32:

          451|     } // lib.optionalAttrs (stdenv.hostPlatform.isx86_64 && stdenv.hostPlatform ? gcc.arch) {
          452|       requiredSystemFeatures = attrs.requiredSystemFeatures or [] ++ [ "gccarch-${stdenv.hostPlatform.gcc.arch}" ];
             |                                ^
          453|     } // lib.optionalAttrs (stdenv.buildPlatform.isDarwin) {

```

### Steps To Reproduce
1. Have any system config
2. set  `nixpkgs.hostPlatform.gcc.arch = "x86_64"; `  (or any other arch)
3. get the aboves error

### Expected behavior
Everything builds just fine.

### Additional context
My fantastic bisect skills (be aware of the sarcasm) nailed it down to #225512. The PR sets `requiredSystemFeatures = null;` which breaks the evaluation. 
Possibly a `requiredSystemFeatures = [];` is another solution here and that seems to fix eval for me (but i am not purposing the change as i am absolut unaware of side-effects), or the mkDerivation code needs to be changed to support `requiredSystemFeatures = null;`  in case someone sets gcc.arch.

### Notify maintainers
@Artturin (as you are the author of the PR that possibly broke the eval) 
beside that i sadly dont know whom to ping.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230420.da2e9dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - channels(shawn): `""`
 - nixpkgs: `/nix/store/4za032y0b5080vb4124nlhdzyqn4jxq7-source`

```

**Comment by Artturin** [comment]
My pr didn't add the requiredSystemFeatures line so it must have been broken since https://github.com/nixos/nixpkgs/commit/0730df1a1a1d4e4caa26bba9988b18ca3e322a39

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/227506

**Comment by Shawn8901** [comment]
> My pr didn't add the requiredSystemFeatures line so it must have been broken since [0730df1](https://github.com/NixOS/nixpkgs/commit/0730df1a1a1d4e4caa26bba9988b18ca3e322a39)

Ah sorry you are right, i had multiple PRs open and I must have picked the wrong one. :(
