### ISSUE TITLE
Signal-desktop: no sound in call

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#227668]
### Describe the bug
No sound in call

### Steps To Reproduce
1. Call someone

### Expected behavior
Can hear and can be heard

### Additional context
I think it is trying to use ALSA and there is some issue there

### Notify maintainers

@Mic92 @equirosa @urandom2 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.24, NixOS, 23.05 (Stoat), 23.05pre474575.f00994e78cd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(aroun): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by equirosa** [comment]
Hi! Sorry I never got back to you on this, was pretty occupied... Anyway, I wanted to know if you still experienced this error? I don't have anyone I can call on signal-desktop (or -beta) so I can't test it

**Comment by Zahrun** [comment]
Seems to be fixed
