### ISSUE TITLE
Package request: Gnote

### ISSUE THREAD

**Issue by Johann-Tree** [NixOS/nixpkgs#227679]
**Project description**
Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using CamelCase-style links, group together in notebooks and some extra features for everyday use.

Notes can be printed or exported as HTML documents.

Gnote also supports synchronization, making it simple to use it on multiple devices.

Gnote started as a C++ port of Tomboy and has moved its own path later.

**Metadata**

* homepage URL: https://wiki.gnome.org/Apps/Gnote
* source URL: https://gitlab.gnome.org/GNOME/gnote
* license: gpl3+
* platforms: linux

**Comment by jfvillablanca** [comment]
A [PR draft](https://github.com/NixOS/nixpkgs/pull/174827) exists although I am unsure if it's being worked on

**Comment by Johann-Tree** [comment]
What is necessary to get done there?
I'm just an experienced end user and I would like to use NixOS as my productive system.

**Comment by jfvillablanca** [comment]
In the mean time, you could create an overlay to add Gnote to your existing configuration.
I'll create a PR bumped to the latest stable version of Gnote.
