### ISSUE TITLE
Update request: Vivaldi 5.4.2753.47 → 6.0.2979.15-1

### ISSUE THREAD

**Issue by thistechguy** [NixOS/nixpkgs#227693]
- Package name: Vivaldi
- Latest released version: 6.0.2979.15-1

- Current version on the unstable channel: 5.7.2921.63
- Current version on the stable/release channel: 5.4.2753.47

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Doesn't appear to have been added to unstable channel.

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by wegank** [comment]
Closed by #227317.
