### ISSUE TITLE
Nixpkgs release tarball won't build with strange "llegal name" error

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#22788]
I have a git checkout of the Nixpkgs `master` at `~/.nix-defexpr`. Now, trying to build the Nixpkgs release tarball from that location fails:

~~~
$ nix-build ~/.nix-defexpr/pkgs/top-level/release.nix -A tarball --show-trace
error: while evaluating the attribute ‘src’ of the derivation ‘nixpkgs-tarball-17.03pre1234.abcdef’ at /home/simons/.nix-defexpr/pkgs/build-support/release/source-tarball.nix:81:5:
illegal name: ‘.nix-defexpr’
~~~

If I move the repository to some other location, i.e. `/tmp/nixpkgs`, then it works.

**Comment by globin** [comment]
Maybe nixos/nix#912?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?
