### ISSUE TITLE
Build failure: vector

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#227896]
### Steps To Reproduce

1. build *vector*

### Build log

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued                                                                         error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:2573 ~ vector_buffers[61ee]::variants::disk_v2::record::_::{impl#0}::resolve), const_param_did: None }) (after phase change to runtime-optimized) at bb4[53]:                                                             Field projection `(*_4).field[3]` specified type `rkyv::boxed::ArchivedBox<[u8]>`, but actual type is `<rkyv::with::With<rkyv::with::With<&[u8], rkyv::with::RefAsBox>, rkyv::with::CopyOptimize> as rkyv::Archive>::Archived`                  --> lib/vector-buffers/src/variants/disk_v2/record.rs:46:10
```

### Notify maintainers

@happysalada @thoughtpolice 

### Metadata

- system: `"x86_64-linux"`                            - host os: `Linux 6.2.11-zen1, NixOS, 23.05 (Stoat), 23.05.20230419.645bc49`                                - multi-user?: `no`                                   - sandbox: `yes`                                      - version: `nix-env (Nix) 2.13.3`                     - channels(root): `"nixos, nixos-22.11-small-22.11-small"`                                                  - nixpkgs: `not found`

**Comment by happysalada** [comment]
I've opened a rust compiler issue last week giving them the details.
My plan for this is to try again to see if the error persists with rust 1.69 (that should land on master in about 2-3 weeks).
I unfortunately don't have any workaround for this one.

**Comment by figsoda** [comment]
See https://github.com/NixOS/nixpkgs/pull/225778, unfortunately it didn't get in the same staging cycle, but it should be fixed in the next cycle as @happysalada said

**Comment by KFearsoff** [comment]
It looks like upstream Vector is already on Rust 1.69, where this issue does not occur. Are we just waiting for Rust 1.69 too, then? Any ETAs or band-aids in the mean time?

**Comment by figsoda** [comment]
vector should already be fixed since the last staging-next cycle was merged: https://github.com/NixOS/nixpkgs/pull/226795

**Comment by happysalada** [comment]
Ive just tested on nixpkgs latest master and can confirm that the failure is fixed.
Ill be updating vector soon with the latest version and a small improvement to the service
