### ISSUE TITLE
tor-browser does not find tor executable

### ISSUE THREAD

**Issue by r-raymond** [NixOS/nixpkgs#22781]
## Issue description
When trying to start tor-browser, a dialog pops up

    Unable to start Tor.
    The Tor executable is missing.

### Steps to reproduce

add `tor-browser` to to installed packages and start it.

## Technical details

* System: 16.09.1623.74f24c7 (Flounder)  (Also reproducible on unstable)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1623.74f24c7

**Comment by joachifm** [comment]
I cannot reproduce this. 

Could you try again with a clean profile? The path to the tor executable is written into the profile directory, but may become invalid if torbrowser is updated.

**Comment by r-raymond** [comment]
It was due to a stale ~/.torbrowser4 folder in case anybody else runs into this. Removing this folder fixes the issue.

**Comment by deepfire** [comment]
I confirm what @r-raymond says

**Comment by joachifm** [comment]
I'm working on a new version that "cannot" go stale: https://github.com/joachifm/nixpkgs/tree/tbb-new

**Comment by deepfire** [comment]
@joachifm, great! Thanks for taking care of this!

**Comment by joachifm** [comment]
Pushed ecd0e1a2c736a9a609cd820de0cb2861129482c3; hopefully a comprehensive fix.  Please let me know if you continue to experience stale references.
