### ISSUE TITLE
libvirt: Unable to migrate VMs between 2 NixOS hosts due to different qemu-kvm paths

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#22791]
Hey :)

## Issue description
When trying to migrate one VM from a NixOS based host to another NixOS based host both running libvirt it fails when checking for the QEMU capabilities. 

Error message from the target host journal:
```
libvirtd[25082]: 2017-02-14 14:02:32.400+0000: 25177: error : virQEMUCapsNewForBinaryInternal:4655 : Cannot check QEMU binary /nix/store/am11v5x17il8qfl5mczijznnfmsn8n7z-qemu-x86-only-2.7.0/bin/qemu-kvm: No such file or directory
```
The path in the error message does exist on the source host but not on the target host.

### Steps to reproduce
* Setup NixOS host (source machine) using current nixpkgs master head
* Host a VM on the machine (called examplevm)
* Wait a few weeks
* Setup another NixOS host (target machine) with a slightly newer nixpkgs commit
  * both running qemu 2.7.0 but do not have the same store paths
* try to migrate a VM from source to target with virsh
```
virsh migrate --live --persistent --undefinesource --copy-storage-all --verbose --desturi qemu+ssh://helmich@somename.dmz.wb.somedomain.de/system examplevm
```

//cc @globin @fpletz

**Comment by neilmayhew** [comment]
I was able to solve a similar problem (starting a VM I hadn't run in a long while) by using `virsh edit VMNAME` and changing the `<emulator>` value to `/run/current-system/sw/bin/qemu-kvm`.

I'm not sure how the machine definition ends up using the absolute path of the emulator, nor whether this fix will get overwritten eventually. I did get me out of a fix, though.

**Comment by globin** [comment]
This should have been fixed a while (>1-2 years) ago and I checked some machines and emulator is correctly set to `/run/libvirt/nix-emulators/qemu-kvm`.
