### ISSUE TITLE
Update request: standardnotes (stable) 3.23.69 → 3.150.45

### ISSUE THREAD

**Issue by manuel-plavsic** [NixOS/nixpkgs#227967]
- Package name:  Standard Notes
- Latest released version: 3.151.3
- Current version on the unstable channel:  3.150.45
- Current version on the stable/release channel: 3.23.69
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@M-Gregoire 
@chuangzhu 
@squalus 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by squalus** [comment]
Done!
