### ISSUE TITLE
telegram-desktop: broken webkit integration

### ISSUE THREAD

**Issue by NickCao** [NixOS/nixpkgs#227930]
### Describe the bug
The webkit integration of telegram-desktop is broken, resulting in bots using https://core.telegram.org/bots/webapps to not work properly.

### Steps To Reproduce
1. Open a chat with the demo bot [@DurgerKingBot](https://t.me/durgerkingbot).
2. Click the "Order Food" button
3. Either telegram-desktop crashes, or the webview fails to render the webpage

### Expected behavior
The webkit integration works as shown in https://core.telegram.org/bots/webapps

### Additional information
Reference: https://github.com/NixOS/nixpkgs/pull/227608

**Comment by Cryolitia** [comment]
Arch Linux related issue closed today: https://gitlab.archlinux.org/archlinux/packaging/packages/telegram-desktop/-/issues/1 , telegram-desktop now works on Arch Linux since 5.0.2.

**Comment by NickCao** [comment]
There is also improvement on our front, it now shows "tls support is not available" in stead of straight crashing:

![screenshot-2024-05-27-10-31-38](https://github.com/NixOS/nixpkgs/assets/15247171/4bf15511-331c-4287-9f12-1827b9a7e965)

**Comment by Hentioe** [comment]
I still had the "TLS support is not available" issue, which seemed to be due to the missing `GIO_MODULE_DIR` environment variable.

When I started from the terminal and set this environment variable manually, the problem was solved. For example:

```bash
GIO_MODULE_DIR=/nix/store/38linv3kvivyvv4qg58ydv3nhjj1z628-glib-networking-2.80.0/lib/gio/modules telegram-desktop
```

Same as here: https://github.com/NixOS/nixpkgs/issues/72579#issuecomment-549046678
