### ISSUE TITLE
System can not shut down with Plasma on Wayland

### ISSUE THREAD

**Issue by sheepforce** [NixOS/nixpkgs#228045]
### Describe the bug
My system cannot shutdown when running Plasma via a Wayland session. When shutting down or rebooting, it will instead infinitely wait for "A stop job is running for X11 Server" with no time limit. This does not occur when running plasma in an X11 session

### Steps To Reproduce
1. Start a Plasma session via Wayland
2. `sudo reboot` or shut down via graphical menu
3. Infinite hang of display-manager.service on shutdown

### Expected behavior
The system shut down correctly, no matter if I am running via Wayland or X11.

### Additional context
I'm running on relatively new hardware with a Ryzen 9 7900X as the primary GPU and an RX 7900 XTX via DRI_PRIME offloading on the modesetting drivers. Relevant parts:

```nix
  boot = {
    kernelPackages = pkgs.linuxKernel.packages.linux_6_2;
    kernelParams = [
      "amdgpu.sg_display=0"
      "amd_iommu=on"
      "iommu=pt"
    ];
  };

  services = {
    xserver.videoDrivers = [ "modesetting" "fbdev" ];
    #xserver.videoDrivers = [ "amdgpu" ];
  };

  hardware = {
    enableRedistributableFirmware = true;
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      extraPackages = with pkgs; [
        amdvlk
        rocm-opencl-icd
        rocm-opencl-runtime
      ];
      extraPackages32 = with pkgs; [
        driversi686Linux.amdvlk
      ];
    };
  };
```

### Notify maintainers

@abbradar @ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12, NixOS, 23.05 (Stoat), 23.05.20230423.e78d25d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
Does this happen if you instead start Plasma from a TTY (`startplasma-wayland`)?

If not, then it's probably https://bugs.kde.org/show_bug.cgi?id=445449.

**Comment by sheepforce** [comment]
It actually shuts down correctly when using `startplasma-wayland`, yes! Nice, the bug seems to be solved upstream so we are just waiting for it to reach the next release? :)

**Comment by SuperSamus** [comment]
It should be solved by now, with SDDM 0.20.0.

**Comment by sheepforce** [comment]
As it seems it will not be backported to 23.05 I can not test this at the moment to confirm :grimacing:

**Comment by zoechi** [comment]
Logout before shutdown works as a workaround for me
as mentioned in the linked issue #issuecomment-1523797685

**Comment by sheepforce** [comment]
Meanwhile I've migrated to nixos-unstable where it works without problems :)

**Comment by sheepforce** [comment]
Works now in 23.11 :)
