### ISSUE TITLE
nixos-rebuild fails due to wg-quick 

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixpkgs#228055]
### Describe the bug

I have a machine using `wg-quick` via the `configFile` option with nothing particularly special in the config file. When I `nixops deploy` or `nixos-rebuild switch` it fails due to the interface already existing:

```
× wg-quick-wg0.service - wg-quick WireGuard Tunnel - wg0
     Loaded: loaded (/etc/systemd/system/wg-quick-wg0.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-04-24 19:21:20 MDT; 337ms ago
   Duration: 1w 4d 7h 46min 7.162s
    Process: 660632 ExecStart=/nix/store/9ll9s1cyi0bjb556nkiav2y9bjk1anyn-unit-script-wg-quick-wg0-start/bin/wg-quick-wg0-start (code=exited, status=1/FAILURE)
   Main PID: 660632 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 46ms

Apr 24 19:21:20 r systemd[1]: Starting wg-quick WireGuard Tunnel - wg0...
Apr 24 19:21:20 r wg-quick-wg0-start[660639]: .wg-quick-wrapped: `wg0' already exists
Apr 24 19:21:20 r systemd[1]: wg-quick-wg0.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 19:21:20 r systemd[1]: wg-quick-wg0.service: Failed with result 'exit-code'.
Apr 24 19:21:20 r systemd[1]: Failed to start wg-quick WireGuard Tunnel - wg0.
warning: error(s) occurred while switching to the new configuration
```

If I `ip link del wg0` first, the nixos-rebuild succeeds.

### Steps To Reproduce

As per above.

### Expected behavior

I'm able to `nixos-rebuild switch` without error. 

### Additional context

I suspect that a `postStop` `ip link del` [as in the wireguard config](https://github.com/NixOS/nixpkgs/blob/c251c021fe168479f811d1496d5c4571592d8dfa/nixos/modules/services/networking/wireguard.nix#L482) would resolve this issue. I'd be happy to make a PR to this effect.

### Notify maintainers

@cab404 @ncfavier 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.20230424.f536431`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - channels(n8henrie): `"nixpkgs-22.11"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by ncfavier** [comment]
Weird, the service's ExecStop calls `wg-quick down`, which should remove the interface. Can you confirm that it runs when you rebuild?

**Comment by n8henrie** [comment]
Hmm. I waited until this had been a reproducible issue for a couple weeks, happened again after I'd manually resolved it a time or two with an `ip link del` and the problem returned, and happened with both `nixops deploy` and `nixos-rebuild switch`. But of course as soon as I post the issue, it seems to be working again. I'll close for now, if it comes back I'll try manually running the `wg-quick down` step, and re-open if needed. Thanks for your reply!

**Comment by n8henrie** [comment]
Ran into this again a few days ago. Not sure what's going on. Manually running wg-quick down resolved it for the time being.

**Comment by b-m-f** [comment]
For anyone finding this.

You can add an activationScript to remove the interfaces as a workaround.
PostDown does not work.

```
  system.activationScripts = {
    fix-wireguard-activation = ''
      ${pkgs.iproute2}/bin/ip link del wg0
     '';
  };

```

**Comment by cab404** [comment]
> I am experiencing this as well. It happens on every single machine set up with `wg-quick` and deployed with `deploy-rs`.
> 
> This seems to happen every time I update my flakes before deploying.

Do you have NM enabled?

**Comment by b-m-f** [comment]
> > I am experiencing this as well. It happens on every single machine set up with `wg-quick` and deployed with `deploy-rs`.
> > This seems to happen every time I update my flakes before deploying.
> 
> Do you have NM enabled?
```
# systemctl status NetworkManager
Unit NetworkManager.service could not be found.
```

These are all headless servers without NetworkManager.

**Comment by cab404** [comment]
hm, worth a shot. You don't happen to have a public flake?
