### ISSUE TITLE
Suspended system wakes up immediately

### ISSUE THREAD

**Issue by sheepforce** [NixOS/nixpkgs#228046]
### Describe the bug
When suspending the my system, it wakes up immediately after only a few seconds.

### Steps To Reproduce
1. `systemctl suspend` or via graphical interface in Plasma
2. Immediate wake up from suspend

### Expected behavior
Suspend to RAM should work without unexpected wakeup.

### Additional context
I'm running on relatively new hardware with a Ryzen 9 7900X as the primary GPU and an RX 7900 XTX via DRI_PRIME offloading on the modesetting drivers. Relevant parts:

```nix
  boot = {
    kernelPackages = pkgs.linuxKernel.packages.linux_6_2;
    kernelParams = [
      "amdgpu.sg_display=0"
      "amd_iommu=on"
      "iommu=pt"
    ];
  };

  services = {
    xserver.videoDrivers = [ "modesetting" "fbdev" ];
    #xserver.videoDrivers = [ "amdgpu" ];
  };

  hardware = {
    enableRedistributableFirmware = true;
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      extraPackages = with pkgs; [
        amdvlk
        rocm-opencl-icd
        rocm-opencl-runtime
      ];
      extraPackages32 = with pkgs; [
        driversi686Linux.amdvlk
      ];
    };
  };
```

This may be related to https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Instantaneous_wakeups_from_suspend (Kernel 6.2 and a new Ryzen 9 7900X) but the workaround from the Arch wiki does not apply on my system (there is no i2c device with `wakeup`).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12, NixOS, 23.05 (Stoat), 23.05.20230423.e78d25d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
Try latest linux kernel?

**Comment by sheepforce** [comment]
Updated just yesteday and switched from `pkgs.linuxKernel.packages.linux_6_2` to `config.boot.zfs.package.latestCompatibleLinuxPackages` (apparently 6.2.16, now), and you are right! It now just works! :)
