### ISSUE TITLE
Top-level kernels missing

### ISSUE THREAD

**Issue by m-bdf** [NixOS/nixpkgs#228044]
### Describe the bug

Some kernels (`pkgs.linuxKernel.kernels.linux_{zen,lqx,…}`) don't exist at the top-level (as `pkgs.linux_zen`, `pkgs.linux_lqx`, …) while others do (`pkgs.linux_latest`, `pkgs.linux_xanmod`, …).
Their corresponding packages (`pkgs.linuxPackages_{zen,lqx,…}`) are present though.

### Steps To Reproduce

1. `nix repl`
2. `:l <nixpkgs>`
3. `linux_` and press tab
4. `linuxPackages_` and press tab

### Notify maintainers

@PedroHLC

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9-zen1, NixOS, 23.05 (Stoat), 23.05.20230408.6f95dd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/pmyn8x8ilqpbg73c6d3qn8k39djn224c-source`
```

**Comment by PedroHLC** [comment]
This was already missing before I assumed these kernels, but if it's really necessary, I'll kindly add. Remember that `pkgs.linuxPackages_zen` includes a `.kernel`.

**Comment by m-bdf** [comment]
I'm in favour of making all kernels available at the top-level for consistency, and after a bit more digging (some are aliases, some are available as `linux-…` instead of `linux_` etc) I think the only ones missing are lxq and zen, so I'll make a PR.
