### ISSUE TITLE
Package request: onnxruntime-gpu

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#228093]
**Project description**

ONNX Runtime: cross-platform, high performance ML inferencing and training accelerator .

Onnxruntime is already packaged. I would like to have the version with gpu support to be able to package obs-backgroundremoval with gpu support (https://github.com/royshil/obs-backgroundremoval/pull/253).

Related: https://github.com/NixOS/nixpkgs/issues/93830

@jonringer @puffnfresh @ck3d @cbourjau @zhaofengli 

**Metadata**

* homepage URL: https://onnxruntime.ai/
* source URL: https://github.com/microsoft/onnxruntime/
* license: mit
* platforms: linux

**Comment by Zahrun** [comment]
Obs-backgroundremoval includes tensorrt_provider_factory.h to build

**Comment by pbsds** [comment]
@NixOS/cuda-maintainers @NixOS/rocm-maintainers

**Comment by Cryolitia** [comment]
need it, too

**Comment by HKalbasi** [comment]
@Zahrun Is it possible to add gpu support to the obs-backgroundremoval as this issue is closed?

**Comment by Zahrun** [comment]
> @Zahrun Is it possible to add gpu support to the obs-backgroundremoval as this issue is closed?

It may be possible. If anyone wants to open a PR for that, please base it on the current update PR https://github.com/NixOS/nixpkgs/pull/230775
