### ISSUE TITLE
Package request: EASYROAM

### ISSUE THREAD

**Issue by donni-h** [NixOS/nixpkgs#228158]
**Project description**
There is a GUI for the new easyroam connection.easyroam is a European university network with which you can get a WIFI connection at all institutions and access paywalled research papers.
Sadly, it is only available as a .deb file and I haven't been able to package it myself, due to lacking experience.
I would be very gateful, if someone would be willing to package this!

**Metadata**

* homepage URL: https://get.eduroam.de
* source URL: https://www.easyroam.de/debapp/easyroam_connect_desktop-1.3.0+1.3.0-linux.deb
* platforms: linux

**Comment by Misterio77** [comment]
FYI: Those scripts are not needed on NixOS, you can easily connect to eduroam using wpa_supplicant, for example:
```nix
{
  networking.wireless = {
    enable = true;
    networks = {
      "eduroam" = {
        auth = ''
          key_mgmt=WPA-EAP
          pairwise=CCMP
          auth_alg=OPEN
          eap=PEAP
          identity="12345678@example.com"
          password="my cool secret pass"
          phase2="auth=MSCHAPV2"
        '';
      };
    };
  };
}
```

**Comment by MaxHearnden** [comment]
It is generally not a good idea to include passwords in any .nix file as it would be readable by any process on your system

a better way to enter the password would be using a line like
```
password="@EDUROAM_PASSWORD@"
```
creating /root/wireless.env with the contents
```
EDUROAM_PASSWORD="very cool password"
```

and then setting 
`networking.wireless.environmentFile = "/root/wireless.env"`
The quotes around `/root/wireless.env` are important to keep the file out of the nix store

see https://search.nixos.org/options?channel=22.11&show=networking.wireless.environmentFile&from=0&size=50&sort=relevance&type=packages&query=networking.wireless.environmentFile for more information

**Comment by Misterio77** [comment]
Yup, agreed. I just put it that way to be a little easier to digest.

(I [use `environmentFile` on my own config](https://github.com/Misterio77/nix-config/blob/main/hosts/common/optional/wireless.nix) too)

**Comment by der-eismann** [comment]
Just a heads up - while it was easy in the past, the Linux setup now includes extracting certificates from a `.p12` file ([German howto](https://doku.tid.dfn.de/de:eduroam:easyroam#installation_der_easyroam_profile_auf_linux_geraeten)), according to my university the old process will stop working in December. The app makes this way easier.

**Comment by donni-h** [comment]
> Just a heads up - while it was easy in the past, the Linux setup now includes extracting certificates from a `.p12` file ([German howto](https://doku.tid.dfn.de/de:eduroam:easyroam#installation_der_easyroam_profile_auf_linux_geraeten)), according to my university the old process will stop working in December. The app makes this way easier.

agreed. I have already tried contacting them and for one reason or another, they do not seem to want to give out the raw source code, which might be easier to package for Nix.

**Comment by noggynoggy** [comment]
I've written a guide on how I got it working for me (VPN+WiFi):

https://nx2.site/posts/eduroam-nixos
