### ISSUE TITLE
budgie-desktop crashes when searching in budgie menu

### ISSUE THREAD

**Issue by bobby285271** [NixOS/nixpkgs#228142]
### Describe the bug

When typing something here:

<img src="https://user-images.githubusercontent.com/20080233/234295065-7378ed41-4a1f-402b-a1b9-5e83c4866e9b.png" width=50%>

The desktop crashes and you have to re-login (well it's Chinese in the screenshot but I hope you get the idea)

<img src="https://user-images.githubusercontent.com/20080233/234295442-7734af08-3d32-4672-a719-692655d21016.png" width=50%>

### Steps To Reproduce
1. Open budgie menu
2. Type something
3. See crash

### Expected behavior

No crash.

### Screenshots

See above.

### Additional context

I don't see this issue before the GNOME 44 update. Probably another issue [caused by GLib 2.76](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2935) but I haven't go deep yet.

### Notify maintainers

@FedericoSchonborn 

### Metadata

I am on https://github.com/NixOS/nixpkgs/commits/830de34f05ba01959cec62a6e47e91547b07fc66 right now, it's nixos-unstable with pull request https://github.com/NixOS/nixpkgs/pull/227526 picked.

**Comment by bobby285271** [comment]
I gave the latest HEAD (i.e. https://github.com/BuddiesOfBudgie/budgie-desktop/commit/f49821abdcc461f660cdb68cb5f51820fba2f220) a try and cannot reproduce the issue so *probably* some of the commits fixes the issue. I wonder if this can be reproduce by others and if some fixes can be backported before 23.05

**Comment by bobby285271** [comment]
Ohhh goooooood and now I am reading `#buddiesofbudgie-dev:matrix.org`, let me make some noise there

**Comment by bobby285271** [comment]
And now I am on 45d0a21ce60a3a7b9a80a514b17496bd40d01a96, which has glib 2.74. This is going to be weird because with G_SLICE=always-malloc I also cannot reproduce the crash (budgie-desktop 10.7.1), so probably not related to the slice allocator.

**Comment by bobby285271** [comment]
Okay I guess I can basically confirm it's a vala issue because I am now on 8722936374fdbc32f6d6d2a7aa44d171e1033292 and cannnot reproduce the crash, wow it's first time I know valac can really cause issues :see_no_evil:  

Bisect is too painful for my slow laptop :upside_down_face:

**Comment by EbonJaeger** [comment]
Could you try compiling and running this Vala code on the broken version to see if it also crashes? It should do the same thing as the crashing Budgie code, just without crashing your desktop. If this ends up being a Vala issue, we need a minimal reproduction program to send.

```vala
int matrix_test()
{
  var matrix = new int[5, 5];

  // Initalize the array columns
  for (int i = 0; i < 5; i++)
  {
    matrix[i, 0] = i;
  }
  for (int j = 0; j < 5; j++)
  {
    matrix[0, j] = j;
  }

  // Set stuff to the array
  for (int i = 0; i < 5; i++)
  {
    for (int j = 0; j < 5; j++)
    {
      matrix[i, j] = 10;
    }
  }

  // Return the element at the end of the matrix
  return matrix[4, 4];
}

int main()
{
  var i = matrix_test();
  message("result: %d", i);
  return 0;
}

Build and run with (assuming you put it in a file called `main.vala`):

```
valac main.vala
./main
```

**Comment by bobby285271** [comment]
I am now on 722bc3b33e9ea1039324daf60d34453b101ad3b9 and my desktop crashes, so the current range is https://github.com/GNOME/vala/compare/0.56.4...0.56.5 :upside_down_face: I am away from keyboard for the next few hours because it's midnight here but feel free to drop questions :upside_down_face: 

---

I built the program with vala 0.56.5, it exits normally with

```
** Message: 23:58:29.090: Application.vala:31: result: 10
```

**Comment by EbonJaeger** [comment]
Well, crap. I was hoping that would crash. Maybe this version when you get back? It's closer to the code in Budgie:

```vala
int matrix_test()
{
  var matrix = new int[5, 5];

  // Initalize the array columns
  for (int i = 0; i < 5; matrix[i, 0] = i++) {}
  for (int j = 0; j < 5; matrix[0, j] = j++) {}

  // Set stuff to the array
  for (int i = 0; i < 5; i++)
  {
    for (int j = 0; j < 5; j++)
    {
      var cost = 10;
      matrix[i, j] = cost;
    }
  }

  // Return the element at the end of the matrix
  return matrix[4, 4];
}

int main()
{
  var i = matrix_test();
  message("result: %d", i);
  return 0;
}
```

Of those commits, the only one that really looks suspicious to me is https://github.com/GNOME/vala/commit/1851080b245117ac1554949cf13adb86fb4e9a6a at a glance.
