### ISSUE TITLE
steam fails to start on unstable 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#22811]
## Issue description

```
$ steam --version
cp: reguläre Datei '/home/ronny/.local/share/Steam/bootstrap.tar.xz' kann nicht angelegt werden: Permission denied
/home/ronny/.local/share/Steam/steam.sh: Zeile 102: Keine Entsprechung: **:

```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by globin** [comment]
Could you delete `/home/ronny/.local/share/Steam` and then try again if you don't have anything important in that directory. Otherwise you might try fixing the owner of the file mentioned and the parent directories.

**Comment by cpages** [comment]
I just tested the one from the unstable channel and seems to work fine for me. Notice that the 'permission denied' error you're seeing is 'normal', it shouldn't prevent steam from running.

Was this a clean install? Did you try what @globin suggested?

**Comment by ikervagyok** [comment]
also you can delete `~/.steam`, dunno if that helps. i deleted both directories the few times steam broke.

**Comment by clhodapp** [comment]
For what it's worth, I'm experiencing the exact same thing as @RonnyPfannschmidt.

**Comment by cpages** [comment]
@clhodapp, @RonnyPfannschmidt can you give us more details? is this nixos? are you subscribed to steam beta? I suspect my steam.sh is not the same. Can you paste the offending line?

**Comment by RonnyPfannschmidt** [comment]
```
$ steam
cp: reguläre Datei '/home/ronny/.local/share/Steam/bootstrap.tar.xz' kann nicht angelegt werden: Permission denied
/home/ronny/.local/share/Steam/steam.sh: Zeile 102: Keine Entsprechung: **:
```

```
$ ls /home/ronny/.local/share/Steam -la
insgesamt 2656
drwx------ 1 ronny users     164 24. Mär 15:59 .
drwxr-xr-x 1 ronny users     860 24. Mär 15:59 ..
-r--r--r-- 1 ronny users 2676956 24. Mär 15:59 bootstrap.tar.xz
drwx------ 1 ronny users      36 17. Nov 2015  linux32
-rw------- 1 ronny users     826 26. Nov 2013  steamdeps.txt
-rw------- 1 ronny users    8822 26. Nov 2013  steam_install_agreement.txt
-rwx------ 1 ronny users   22532 17. Nov 2015  steam.sh
drwx------ 1 ronny users      66 17. Nov 2015  ubuntu12_32
```
line 102 is in 

```
function show_license_agreement()
{
	LICENSE="$STEAMROOT/steam_install_agreement.txt"
	if [ ! -f "$STEAMCONFIG/steam_install_agreement.txt" ]; then
		if [ ! -f "$LICENSE" ]; then
			show_message --error $"Couldn't find Steam install license agreement, aborting!"
			exit 1
		fi

		# See if they have been grandfathered in through the beta
		SSAVersion=$(find -L "$STEAMCONFIG/`detect_package`" -name sharedconfig.vdf -exec fgrep SSAVersion {} \;)

		if [ "$SSAVersion" != "" ]; then
			answer=accepted
		else
			answer=declined
			output=$(zenity --width 650 --height 500 --text-info --title=$"Steam Install Agreement" --filename="$LICENSE" --checkbox=$"I have read and accept these terms." 2>&1)
			STATUS=$?
			if echo $output | grep "status 1:" >/dev/null; then  # this is line 102
				# Zenity couldn't launch a window
				STATUS=-1
			fi
			case $STATUS in
			0)	# The agreement was accepted
				answer=accepted
				;;
			1)	# The agreement was declined
				;;
			*)	# zenity wasn't available, try a fallback
				tmpfile="$(mktemp || echo "/tmp/steam_message.txt")"
				command="more \"$LICENSE\" || cat \"$LICENSE\"; echo -n $'Do you accept the terms of this agreement? [y/N]: '; read input; if [ x\$input = xy -o x\$input = xY ]; then echo accepted >\"$tmpfile\"; fi"
				xterm -bg "#383635" -fg "#d1cfcd" -T $"Steam Install Agreement" -e "$command" || \
					/bin/bash -c "$command"
				if [ -f "$tmpfile" ]; then
					read answer <"$tmpfile"
					rm "$tmpfile"
				fi
				;;
			esac
			if [ "$answer" != "accepted" ]; then
				exit 0
			fi
		fi

		cp "$LICENSE" "$STEAMCONFIG"/
	fi
}```

**Comment by abbradar** [comment]
Can you try this patch: https://github.com/abbradar/nixpkgs/commit/c33fbe00312252c790475d1e47befeb1a8d02eff?

**Comment by RonnyPfannschmidt** [comment]
i just tested on master and in plasma5 (gnome3 is still broken according to @globin )

it starts up just fine

**Comment by RonnyPfannschmidt** [comment]
will try on 17.03 next

**Comment by abbradar** [comment]
Sadly you won't be able to test now: Steam needs to show Zenity only once to ask about license or something like that and them marks somewhere that it was done.

**Comment by RonnyPfannschmidt** [comment]
i#ll just delete all its folders

**Comment by RonnyPfannschmidt** [comment]
works on the release-17.03 branch as well

**Comment by abbradar** [comment]
Pushed to master; thank you very much for testing!

**Comment by RonnyPfannschmidt** [comment]
@abbradar i missed a grave mistake of mine, i did not actually apply your patch

**Comment by abbradar** [comment]
:D Well, you can just try to run Zenity. If it works for you so will Steam.

**Comment by RonnyPfannschmidt** [comment]
zenity already runs for me apparently without that patch (currently running a release-17.03 from about 30 minutes back)

**Comment by abbradar** [comment]
Hm, so you can't reproduce that bug now at all?

**Comment by RonnyPfannschmidt** [comment]
at least not on plasma5 (currently i cant run gnome3)

**Comment by abbradar** [comment]
Well, Zenity needed that patch anyway. Let's close this now then; please reopen if you encounter that again! (and backup `.steam`, `.local/share/steam` and others in case you do).

**Comment by RonnyPfannschmidt** [comment]
btw, one striking change is, that steam no longer tries to generate a steam.desktop file
