### ISSUE TITLE
[regression] Using `prev.*Platform` in overlays causes infinite recursion in `nixpkgs-unstable`

### ISSUE THREAD

**Issue by rvolosatovs** [NixOS/nixpkgs#228173]
### Describe the bug
Using `prev.*Platform` in overlays causes infinite recursion in `nixpkgs-unstable`, but works fine on "channel" branches

### Steps To Reproduce
1. Use e.g. `prev.hostPlatform.isLinux` to conditionally override a package in an overlay
2. Observe infinite recursion on 2362848adf8def2866fabbffc50462e929d7fffb
3. Switch to a "channel", e.g. 29c07054efdbbb8719e8e5487c86878215b7205a from `nixpkgs-22.11-darwin`
4. Observe success

Here's a reproducer https://github.com/rvolosatovs/nixpkgs-overlay-regression (try `nix flake check`)

E.g.:
```
$ nix flake check github:rvolosatovs/nixpkgs-overlay-regression
error: infinite recursion encountered

       at /nix/store/22z4n4mxs2vz3l3lg41dz3mgnq1d4wxs-source/pkgs/top-level/aliases.nix:20:6:

           19|
           20| with self;
             |      ^
           21|
(use '--show-trace' to show detailed location information)
```

```
$ nix flake check --override-input nixpkgs 'github:NixOS/nixpkgs/nixpkgs-22.11-darwin' github:rvolosatovs/nixpkgs-overlay-regression
warning: not writing modified lock file of flake 'github:rvolosatovs/nixpkgs-overlay-regression':
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/2362848adf8def2866fabbffc50462e929d7fffb' (2023-04-21)
  → 'github:NixOS/nixpkgs/29c07054efdbbb8719e8e5487c86878215b7205a' (2023-04-25)
trace: this causes an infinite recursion on `nixpkgs-unstable`
```
### Expected behavior
Success, just like on "channel" branches (see second example above)

**Comment by Artturin** [comment]
The top-level {build,host,target}Platform were deprecated in https://github.com/NixOS/nixpkgs/pull/209816 so they were moved to aliases, looks like there's a issue with aliases and some top conditionals.

Your use case is rare enough that a mention in release-notes should be enough https://github.com/NixOS/nixpkgs/pull/228343
