### ISSUE TITLE
linux-wifi-hotspot: asks for password too many times

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#228120]
### Describe the bug
Currently, it asks for password four times to create a hotspot, such as reported at https://github.com/lakinduakash/linux-wifi-hotspot/issues/185
It was fixed in https://github.com/lakinduakash/linux-wifi-hotspot/pull/205
I think in NixOS, polkit is disabled by default, so I enabled it with `security.polkit.enable = true;`, but it does not seem to make a difference.

### Notify maintainers

@onny 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25, NixOS, 23.05 (Stoat), 23.05pre476638.e78d25df6f1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(aroun): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by onny** [comment]
Thank you for the bug report! Which command are you using to create a hotspot?

**Comment by Zahrun** [comment]
I'm using the gui `wihotspot`. It asks for password once.
Then enter SSID, Password, Wifi interface, Internet Interface, go to Advanced and check 2.4Ghz.
Press Create hotspot.
I now asks for password thrice.

**Comment by Zahrun** [comment]
Ah, again it's linux-wifi-hotspot assuming it's located in /usr/bin 
https://github.com/lakinduakash/linux-wifi-hotspot/blob/aabe18aa57f8fcd88205a9b23cb3f634623b2104/src/scripts/policies/polkit.policy#L16 
https://github.com/lakinduakash/linux-wifi-hotspot/blob/aabe18aa57f8fcd88205a9b23cb3f634623b2104/src/scripts/policies/polkit.policy#L30
