### ISSUE TITLE
Bug - RaySession fails to start

### ISSUE THREAD

**Issue by PowerUser64** [NixOS/nixpkgs#228223]
### Describe the bug
The new package for [raysession](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/raysession/default.nix) fails to start due to an error involving Qt. I have reproduced this behavior on two different computers.

### Steps To Reproduce
1. Add raysession to system configuration
2. Open raysession

Raysession does not open, and produces an error in the terminal.

### The Error

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: IOT instruction (core dumped)  raysession
```

### Notify maintainers

@orivej

### Metadata
Output of `nix-shell -p nix-info --run "nix-info -m"`.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25, NixOS, 23.05 (Stoat), 23.05.20230422.6c43a34`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(user): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by PowerUser64** [comment]
I'm also experiencing this problem with the `patchance` package.

**Comment by magnetophon** [comment]
Looks like it needs ``libxcb`` and possibly add that and other qt stuff to the wrapper.

**Comment by tobiasBora** [comment]
@PowerUser64 I made a PR here, you might want to try it a bit more extensively that I did, and also submit a similar fix for the second package mentioned in https://discourse.nixos.org/t/help-fixing-raysession-package/28606
