### ISSUE TITLE
Build failure: rPackages.textshaping on aarch64-darwin

### ISSUE THREAD

**Issue by nviets** [NixOS/nixpkgs#228250]
### Steps To Reproduce

rPackages.textshaping fails to build on aarch64-darwin systems. Consequently, tidyverse won't build

`nix build -f default.nix rPackages.textshaping`

### Build log

```
...
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘textshaping’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/nix/store/hh8yxa21634787qv61iwr2hz0afm4k3w-r-textshaping-0.3.6/library/00LOCK-textshaping/00new/textshaping/libs/textshaping.so':
  dlopen(/nix/store/hh8yxa21634787qv61iwr2hz0afm4k3w-r-textshaping-0.3.6/library/00LOCK-textshaping/00new/textshaping/libs/textshaping.so, 0x0006): symbol not found in flat namespace '_fribidi_log2vis'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/nix/store/hh8yxa21634787qv61iwr2hz0afm4k3w-r-textshaping-0.3.6/library/textshaping’
```

I tried adding fribidi to the buildInputs, but it wasn't enough.

### Notify maintainers

@jbedo

**Comment by jbedo** [comment]
Fribidi is already an input: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/default.nix#L625

Seems to work fine on aarch64 linux, and other fribidi packages work fine on darwin, so I don't see anything obvious. I don't have a mac sadly so hard to work on this.
