### ISSUE TITLE
GNOME3 on master lacks ability to "Log Out"

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#22820]
## Issue description
On NixOS 16.09 with a GNOME3 desktop, you can click in the upper right corner and select ```<your user> -> Log Out```. But on master branch the whole ```<your user>``` menu seems to have vanished. I think this happened with the gnome 3.20 -> 3.22 upgrade, but not sure.

**Comment by bendlas** [comment]
Try pressing the `Alt` key when the menu is open.

**Comment by bjornfor** [comment]
When pressing ```Alt```, the "power" button changes to a "pause" button. Nothing else changes.

**Comment by bendlas** [comment]
Oh right, that was the suspend function. It's been a while since I used gnome3 ....

**Comment by bendlas** [comment]
I've just got a gnome3 open, from current master. It has the user menu along with the logout option. Could you try to start with a fresh user profile?

**Comment by jgeerds** [comment]
I'm on `17.03pre100522.01fef3f (Gorilla)` and logout works fine for me

**Comment by bjornfor** [comment]
Hm, it looks like a new (intended) behaviour in GNOME. If I add another user to my system, the user menu (with logout button) appears. But if I remove that user, the menu disappears.

It is actually possible to test this "live". Add/remove user in /etc/nixos/configuration.nix and run ```nixos-rebuild test```. The user menu / logout button (dis)appears immediately.

I guess it makes a bit sense to disable logout when there is only a single user (although I'd prefer to always have it there, for consistency), but the user menu also contains "Account Settings". So they are killing that shortcut too...

Glad to see that this is not a NixOS issue as I first thought.
