### ISSUE TITLE
libvirt: Unable to attach disk on zfs pool since bump to 3.0.0

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#22823]
## Issue description
Libvirt 3.0.0 enables qemu mount namespaces ( https://libvirt.org/news.html ) which seems to cause some issues.

I am not sure what impact the workaround mentioned below has. If you agree that workaround is ok please let me know and I will implement changes to the libvirt module to reflect it.

I think this should be resolved for 17.03

### Steps to reproduce
* Deploy nixos host with `virtualisation.libvirtd.enable = true;` since after commit a50ff980be5171db9382938e88ad178e482f5a30
* create storage pool for libvirt on a ZFS pool
* create volume on the newly created ZFS storage pool
* attach volume to a VM (e.g. as virtio disk)
* start VM

This will result in the following error logged in the journal:
```
Feb 15 10:16:28 hostnix virtlogd[13624]: 2017-02-15 10:16:28.064+0000: 13624: error : virNetSocketReadWire:1800 : End of file while reading data: Input/output error
Feb 15 10:16:28 hostnix virtlogd[13624]: 2017-02-15 10:16:28.064+0000: 13624: error : virNetSocketReadWire:1800 : End of file while reading data: Input/output error
```
And the following error in /var/log/libvirt/qemu/vmname.log
```
libvirt:  error : libvirtd quit during handshake: Input/output error
2017-02-14 15:10:30.938+0000: shutting down, reason=failed
```

The VM will not be started.

# workaround
By specifying ```namespaces = []``` in /var/lib/libvirt/qemu.conf and restarting `libvirtd.service` the VM can be started with the disk on the ZFS pool attached.

/cc @fpletz, @rickynils

**Comment by Shados** [comment]
I'm seeing the same issue with the same issue (libvirt vm using ZFS zvol as a virtio disk); your work-around also works for me (thanks for that).
