### ISSUE TITLE
Use EnvironmentFile when passing environment into systemd services

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22829]
systemd unit files have a maximum line length of 2048 characters and it's fairly easy to trip that by putting more than a handful of Nix paths into your service's `path` field, since `path` just expands to `Environment` right now. Switching all Nix-managed environment to `EnvironmentFile` would get us past that limitation.

**Comment by teh** [comment]
@copumpkin - can I hand this to you? My solution works but I don't need this urgently, I was trying to help with 17.03.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by teh** [comment]
@mmahut you hitting any issues? systemd now allows really long lines (not sure exact number, maybe 1MB?) so it's not really much of an issue any more. I think it's OK to close this.
