### ISSUE TITLE
Build failure: qt5.qtbase

### ISSUE THREAD

**Issue by Fuzen-py** [NixOS/nixpkgs#228371]
### Steps To Reproduce

1. build  qtbase v5.15.8

### Build log
https://gist.github.com/Fuzen-py/582e3192a0a3183f95b744ea0fdcab6a

### Additional context

System is build against [nixos-unstable-small](https://gitlab.com/Fuzen-py/configsreborn/-/blob/b340085a286d95e90c40d869036aafa597537252/flake.lockl)

### Notify maintainers

@qknight @tteggel @periklis @bkchr 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
melody in ~ 
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/54sf9jdagbqrxzwbj59s8nfr2p7srs6v-nix-info
copying path '/nix/store/54sf9jdagbqrxzwbj59s8nfr2p7srs6v-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230426.79688fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(aizuzu): `""`
 - channels(melody): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by vcunat** [comment]
`qtbase-6c09620`?  What's that?  `qt5.qtbase` is on cache.nixos.org

And `qt5.qtbase.meta.maintainers` are four people, not including myself.

**Comment by Fuzen-py** [comment]
It's not being pulled from the cache (by choice).  It is `qt5.qtbase`

cc: @qknight @tteggel @periklis @bkchr

**Comment by vcunat** [comment]
I see.  The src in current master is `qtbase-d3b21bc` for .9 so you might try to update master first...

**Comment by K900** [comment]
https://gist.github.com/Fuzen-py/582e3192a0a3183f95b744ea0fdcab6a#file-qtbase-5_15_8-log-L503

> #error Intel CET not available

**Comment by K900** [comment]
Can you post the exact derivation you're building, or a `nix-diff` of it compared to unchanged nixos-unstable and/or master?

**Comment by Fuzen-py** [comment]
Nix-diff against master:
https://gist.githubusercontent.com/Fuzen-py/582e3192a0a3183f95b744ea0fdcab6a/raw/16eb0c668dd1d8fb99e354816d8c6f8ad7443824/Nix-diff

**Comment by vcunat** [comment]
I expect majority of the diff is #226795 merged just hours ago.

**Comment by Fuzen-py** [comment]
Build failure is from editing cflag. Closing.

**Comment by samos667** [comment]
@LovingMelody 

While trying to build qt base with 
```nix
  nixpkgs.hostPlatform = {
    system = "x86_64-linux";
    gcc = {
      arch = "rocketlake";
      tune = "rocketlake";
    };
  };
```
I get the same error about 'qFloatToFloat16_fast' redefinition

Please tell us how and with which cflags you have successfully built QTBase5 :'(

**Comment by samos667** [comment]
yes but when setting nixpkgs.hostPlatform.gcc.tune it will normally append NIX_CFLAGS_COMPILE for C packages building.

For my case when setting for rocketlake arch it's impossible to build qtbase5 because (I think) conditional preprocessor are triggered twice:
```
global/qfloat16_f16c.c:52:6: error: redefinition of 'void qFloatToFloat16_fast(quint16*, const float*, qsizetype)'
   52 | void qFloatToFloat16_fast(quint16 *out, const float *in, qsizetype len) Q_DECL_NOEXCEPT
      |      ^~~~~~~~~~~~~~~~~~~~
global/qfloat16.cpp:253:13: note: 'void qFloatToFloat16_fast(quint16*, const float*, qsizetype)' previously defined here
  253 | static void qFloatToFloat16_fast(quint16 *, const float *, qsizetype) noexcept
      |             ^~~~~~~~~~~~~~~~~~~~
global/qfloat16_f16c.c:68:6: error: redefinition of 'void qFloatFromFloat16_fast(float*, const quint16*, qsizetype)'
   68 | void qFloatFromFloat16_fast(float *out, const quint16 *in, qsizetype len) Q_DECL_NOEXCEPT
      |      ^~~~~~~~~~~~~~~~~~~~~~
global/qfloat16.cpp:258:13: note: 'void qFloatFromFloat16_fast(float*, const quint16*, qsizetype)' previously defined here
  258 | static void qFloatFromFloat16_fast(float *, const quint16 *, qsizetype) noexcept
      |             ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by samos667** [comment]
Does anybody have a idea to 'fix' building of qtbase5 when setting 'nixpkgs.hostPlatform.gcc'.
By example restore building for this pkgs as it should be for 'vanilla x86'. Ive tried some overlay implementation but without success..
So for now I've 'banned' every qt5 deps of my config but that's not ideal
