### ISSUE TITLE
Package request: lib4sbom

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#228377]
**Project description**

A Python library to create SBOM files in several formats including SPDX and CycloneDX.

**Metadata**

* homepage URL: https://github.com/anthonyharrison/lib4sbom
* source URL: https://github.com/anthonyharrison/lib4sbom
* license: Apache-2.0
* platforms: Python

**Comment by Kranzes** [comment]
The expression for this can probably be automatically generated with a tool like nix-init, would you be down to maintain this package if I add it to nixpkgs?

**Comment by Kranzes** [comment]
Here's a generated expression, I can't get the test to pass though.

```nix
{ lib
, buildPythonPackage
, fetchFromGitHub
, pyyaml
, semantic-version
, pytestCheckHook
}:

buildPythonPackage rec {
  pname = "lib4sbom";
  version = "0.3.1";
  format = "setuptools";

  src = fetchFromGitHub {
    owner = "anthonyharrison";
    repo = pname;
    rev = "v${version}";
    hash = "sha256-RfJ7V4VRYlceGl4xlTMmm2kHNtxNryb+JHvZQakkM7w=";
  };

  propagatedBuildInputs = [
    pyyaml
    semantic-version
  ];

  nativeCheckInputs = [
    pytestCheckHook
  ];

  pythonImportsCheck = [ "lib4sbom" ];

  meta = with lib; {
    description = "Library to ingest and generate SBOMs";
    homepage = "https://github.com/anthonyharrison/lib4sbom";
    license = licenses.asl20;
    maintainers = with maintainers; [ ];
  };
}
```
