### ISSUE TITLE
SIGSEGV in digiKam 7.9.0

### ISSUE THREAD

**Issue by ThibaultLemaire** [NixOS/nixpkgs#228380]
### Describe the bug

I have recently noticed digiKam crashing. Did a sysupgrade to confirm.

It (at least) crashes when trying to save a face tag, but also simply displaying `--help` or `--version` (which is worrying)

### Steps To Reproduce

```fish
❯ digikam --version
digikam 7.9.0
fish: Job 1, 'digikam --version' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior

No crash :slightly_smiling_face: 

### Additional context

Apparently this has not always been the case, I have two other versions of digiKam 7.9.0 on my system from previous generations, one of which does not segfault:

```console
❯ /nix/store/cx88i17h9pf9baigv732znslwsldyxiz-digikam-7.9.0/bin/digikam --version # current
digikam 7.9.0
fish: Job 1, '/nix/store/cx88i17h9pf9baigv732…' terminated by signal SIGSEGV (Address boundary error)

❯ /nix/store/056pi3s2samjj065prdgqfcmiffix190-digikam-7.9.0/bin/digikam --version
digikam 7.9.0
fish: Job 1, '/nix/store/056pi3s2samjj065prdg…' terminated by signal SIGSEGV (Address boundary error)

❯ /nix/store/c05y2qz0bij8q4z70kqb2b732hd9lr7l-digikam-7.9.0/bin/digikam --version
digikam 7.9.0
```

### Notify maintainers

@Atemu @fabianhjr you have [the last commit which touched this derivation](https://github.com/NixOS/nixpkgs/commit/9bd2506458ea053ccbcde6e622d7cec9993d8f36#diff-bb3b83931cb4e07cdf709889f356a83bd63731c26c558506390671b3c42e68b0L27), which happened post update to 7.9.0

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25-xanmod1, NixOS, 23.05 (Stoat), 23.05pre477241.c8018361fa1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fabianhjr** [comment]
Can reproduce issue on current staging-next

```
digikam --version                                                  Wed 26 Apr 2023 03:30:30 PM CST
digikam 7.9.0
fish: Job 1, 'digikam --version' terminated by signal SIGSEGV (Address boundary error)
```

However application launches and runs correctly. :O

**Comment by fabianhjr** [comment]
7.10.0 has been released with the following note:

```
See below a list of major improvements included in this release:

    Fix crashes with last OpenCV 4.7.0
```

and this is currently built with opencv 4.7.0

**Comment by fabianhjr** [comment]
Even after upgrade the issue remains.

```
digikam --version                                                               984ms  Wed 26 Apr 2023 03:52:09 PM CST
digikam 7.10.0
fish: Job 1, 'digikam --version' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ThibaultLemaire** [comment]
> Can reproduce issue on current staging-next
> 
> ```
> digikam --version                                                  Wed 26 Apr 2023 03:30:30 PM CST
> digikam 7.9.0
> fish: Job 1, 'digikam --version' terminated by signal SIGSEGV (Address boundary error)
> ```
> 
> However application launches and runs correctly. :O

What do you mean by correctly? Mine still launches and runs, but spits a SIGSEGV on quit, and sometimes crashes (when saving face tags as mentioned)

**Comment by fabianhjr** [comment]
Crash on face tags might be related to the item mentioned on the 7.10.0 changelog.

I meant the same ("launches and runs but spits a SIGSEGV on quit")

**Comment by ThibaultLemaire** [comment]
No crashes (neither face tags nor cli) on ba2f6a3aa27aef45d876758891dae8ad387ea68f

**Comment by ThibaultLemaire** [comment]
> Even after upgrade the issue remains.
> 
> ```
> digikam --version                                                               984ms  Wed 26 Apr 2023 03:52:09 PM CST
> digikam 7.10.0
> fish: Job 1, 'digikam --version' terminated by signal SIGSEGV (Address boundary error)
> ```

Really? I just tested commit 1e07e5480d8fceac95be7eaaced4885d1859ed85 from your PR #228408 and I don't have any crash or error anymore

**Comment by fabianhjr** [comment]
Crash might have been related to OpenCV 4.7.0, that upgrade would have happened after the original digikam 7.9.0 version upgrade.
