### ISSUE TITLE
fetchurl should try a different mirror if the original returned unexpected contents

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#2284]
fechurl is giving me this error:

```
building path(s) `/nix/store/ycsz1z7gdf36m36yzygdyir8z5511nr1-bitcoin-0.9.1-linux.tar.gz'
building path(s) `/nix/store/dyxz4rkbciwr5fns88n596iq523zh9s6-options-db.xml'
building /nix/store/dyxz4rkbciwr5fns88n596iq523zh9s6-options-db.xml

trying http://tarballs.nixos.org/sha256/3fabc1c629007b465a278525883663d41a2ba62699f2773536a8bf59ca210425
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   797  100   797    0     0   7445      0 --:--:-- --:--:-- --:--:--  7518
output path `/nix/store/ycsz1z7gdf36m36yzygdyir8z5511nr1-bitcoin-0.9.1-linux.tar.gz' should have sha256 hash `09844755kgx86qspgwlr4sk2n6nlccv8h9c54xd4cyq0573c3arz', instead has `14agc12izsyxmp4919g8lx1z03iq6npqyig9g3p40q2cn04rnww8'
cannot build derivation `/nix/store/pzc02f74s9nvsflcy6jdh38vbrcci6x6-bitcoin-0.9.1.drv': 1 dependencies couldn't be built
cannot build derivation `/nix/store/bny0qbdksrmgpfv293hfcylw1lq7z6a9-system-path.drv': 1 dependencies couldn't be built
cannot build derivation `/nix/store/7b26bgg97zxl9x385xjb1d1s2izjlc5s-nixos-14.04pre-6b7d48d.drv': 1 dependencies couldn't be built
error: build of `/nix/store/7b26bgg97zxl9x385xjb1d1s2izjlc5s-nixos-14.04pre-6b7d48d.drv' failed
```

The problem seems to be that http://tarballs.nixos.org (which is the hashedMirror defined in fetchurl) is claiming success, but returning invalid output.

When this happens, fetchurl should delete the invalid file and try downloading from the url that was actually defined in the derivation (instead of the content-hash mirror).

In fact, if any mirror returns an invalid file, fetchurl should probably try a different mirror instead of claiming success and causing an error like the above afterwards.

**Comment by vcunat** [comment]
The complication here is that the derivation itself does **not** check the hash. That's what nix does after it finishes (just as for any fixed-output derivation). Consequently, if we add the check inside, it will always be performed twice independently (at least), which seems a waste.

**Comment by peti** [comment]
So if a large file has been modified and mirrored on 100 mirrors, then we'll download it 100 times?

**Comment by wizeman** [comment]
@peti I guess the problem you mention would also happen today if your network connection is flaky and connections break frequently, right?

e.g. If the tarball is 1 GB, but curl fails after downloading (on average) 500 MB and never completes, and you have 100 mirrors, Nix may end up downloading 50 GB of data for a 1 GB file.

So probably it wouldn't be wise to attempt to download from 100 mirrors even if this is not implemented...

**Comment by peti** [comment]
@wizeman, I'm not sure what would happen if the connection aborts. I would hope that Nix (or curl) tries to resume the download. HTTP certainly supports that feature.

**Comment by edolstra** [comment]
Yes, `fetchurl` in theory resumes partial downloads.

**Comment by Profpatsch** [comment]
(triage) any conclusion?

**Comment by siddhanathan** [comment]
Any update on this?

**Comment by peti** [comment]
My feeling is that the suggested behavior is undesirable. If a file was modified upstream, I want Nix to fail with a checksum error;  I don't want it to silently fall back to other source thereby hiding the issue. If anything, I feel that the more failure-tolerant behavior could be enabled through some config option for those who want that for some reason. Anyhow, in the absence of any recent activity and no-one volunteering to actually implement the necessary changes, I'm closing this ticket for the time being. If someone were to submit a PR that addresses this topic, then that would be more than welcome!

**Comment by Atemu** [comment]
This cropped up in a slightly different form in https://github.com/NixOS/nixpkgs/issues/125792
