### ISSUE TITLE
NixOS taskserver module seems completely broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#22846]
I have tried to use the NixOS taskserver module from the current `master` branch and I could not make it work, neither using automatically generated certificates nor using manually generated ones. I've found that the NixOS module contains some glaring issues (i.e. attempts at manual keying would not even evaluate), and now I am confused because clearly a lot of thought and effort has gone into this code at some point. So I wonder: is anyone still using this code? Can someone else confirm that this module might be broken? Or am I just doing something wrong?

Cc: @ericsagnes

**Comment by jgeerds** [comment]
If I remember correctly @matthewbauer is also involved

**Comment by ericsagnes** [comment]
Sorry, I am not using this module at all. Maybe @aszlig can help.

**Comment by aszlig** [comment]
@peti: What is the configuration(s) you were using and what is the evaluation error you got when you were manually specify keys?

**Comment by aszlig** [comment]
Also related: #22705

**Comment by peti** [comment]
> What is the evaluation error you got when you were manually specify keys?

I fixed a few days ago in bfd7fe8ba5b1b3ae5015f23bcb3ccd64bb708836. I've since managed to switch to a NixOS configuration that uses manual keying, but task server won't start in that setup.

**Comment by aszlig** [comment]
@peti: Can you check whether my [recent commits to master](https://github.com/NixOS/nixpkgs/compare/5231d0ac290f...08881b8cbe03) improve anything here?

**Comment by peti** [comment]
The setup with automatic key management worked flawlessly for me this time. I'll try setting up a manually keyed server ASAP, too.

**Comment by globin** [comment]
Does this work now?

**Comment by peti** [comment]
Yes, it does! Thank you for your efforts, @aszlig.

**Comment by globin** [comment]
:tada:
