### ISSUE TITLE
Enhance separate-debug-info.sh to be compatible compatible with clang

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#22840]
## Issue description

As seen in this build job https://travis-ci.org/NixOS/nixpkgs/jobs/201821348 (relevant section reproduced below for archival), `separate-debug-info.sh` fails on clang, which is unfortunate for packages that would otherwise be portable between linux and osx.

### Steps to reproduce

Include `separate-debug-info.sh` into a osx-enabled build, as seen here: https://github.com/NixOS/nixpkgs/pull/22824/commits/53985c5529fd2b19bd1a76887f05a5c1197dc2da

### Faillog

```
===> LD
clang-3.7: warning: argument unused during compilation: '-Wa,--compress-debug-sections'
ld: unknown option: --compress-debug-sections=zlib
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by matthewbauer** [comment]
I think Clang/Linux already works with separateDebugInfo. The main issue is getting it to work with MachO symbols. I have a wip branch to get this here:

https://github.com/matthewbauer/nixpkgs/commits/macho
