### ISSUE TITLE
Update request: gnugrep 3.7 → 3.10

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#228535]
- Package name: gnugrep
- Latest released version: 3.10

- Current version on the unstable channel: 3.7
- Current version on the stable/release channel: 3.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@edolstra @m00wl

Also, @trofi for the last version bump.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by trofi** [comment]
I think the (minor) challenge of the new version if a new `pcre2` dependency in `gzip` (instead of old `pcre`). Will need a minor but careful careful tweaking of `bootstrapTools` to package the library safely:

```
* Noteworthy changes in release 3.8 (2022-09-02) [stable]

** Changes in behavior

  The -P option is now based on PCRE2 instead of the older PCRE,
  thanks to code contributed by Carlo Arenas.
```
