### ISSUE TITLE
Bug: gnomeExtensions.extension-list - GLib.FileError

### ISSUE THREAD

**Issue by asininemonkey** [NixOS/nixpkgs#228504]
### Describe the bug
Unable to launch the `extension-list` extension due to the following error:

```console
GLib.FileError: Failed to open file “/run/current-system/sw/share/gnome-shell/extensions/extension-list@tu.berry/schemas/gschemas.compiled”: open() failed: No such file or directory
```

### Steps To Reproduce
1. Install `pkgs.gnomeExtensions.extension-list`

### Expected behavior
Extension should just launch without error

### Screenshots
![image](https://user-images.githubusercontent.com/65740649/234843581-f246218a-19b9-4d17-8108-c2569ea48e19.png)

### Notify maintainers
@piegames

### Metadata
```console
 - system: `"aarch64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05pre478022.d6b863fd9b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zendo** [comment]
Same issue with night-theme-switcher 
explanation from upstream:
https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension/-/issues/139

**Comment by daemonspudguy** [comment]
Brilliant. So, I think that means that glib-compile-schemas will need to be somehow added at runtime.

**Comment by kjhoerr** [comment]
I'm still having this issue in 23.05, it doesn't look like the fix has been backported to the stable branch yet - is there a way to kick that off?

**Comment by piegamesde** [comment]
Gnome extensions are pretty volatile in nature, and I don't know of anybody who is doing the work of maintaining them on stable releases. I personally recommend you to simply overlay the `gnomeExtensions` attribute in your configuration with an unstable channel.

**Comment by piegamesde** [comment]
I have

```nix
(self: super: {
    inherit (pkgsUnstable) gnomeExtensions;
})
```

as an overlay. How to apply something like that when using flakes, I have no idea.

**Comment by asininemonkey** [comment]
Thanks @piegamesde. Not yet using flakes but have now got this working using just the following in my NixOS config:

```
{ config, ... }:

let
  nixos-unstable = fetchTarball "https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz";
in

{
  nixpkgs.overlays = [
    (self: super: {
      inherit (import nixos-unstable {
        config = config.nixpkgs.config;
      }) gnomeExtensions;
    })
  ];
}
```

**Comment by kjhoerr** [comment]
Got it working in flakes - see my full [flake.nix here](https://github.com/kjhoerr/dotfiles/blob/5e44146ce07c5e23381514ad945f16298b6ec952/flake.nix). From how I had it laid out I just needed to add the overlays array that tracked to the pkgs spec I made for my home-manager configs, and then add that to my existing NixOS configuration outputs. Hopefully this is more adaptable to basic flake.nix usage:

```nix
{
  inputs = {
    nixos-pkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    #...
  };
  outputs = { nixpkgs, ... }:
    let
      system = "x86_64-linux";
      lib = inputs.nixos-pkgs.lib;
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };
      osOverlays = [
        (self: super: {
          # Override gnomeExtensions with unstable variant
          inherit (pkgs) gnomeExtensions;
        })
      ];
      #...
    in {
      nixosConfigurations.MyComputer = lib.nixosSystem {
        inherit system;
        modules = [
          {
            nixpkgs.overlays = osOverlays;
          }
        ];
      };
    };
}
```
