### ISSUE TITLE
Update request: meson 1.0.0 → 1.1.0

### ISSUE THREAD

**Issue by ezracelli** [NixOS/nixpkgs#228558]
- Package name: `meson`
- Latest released version: 1.1.0

- Current version on the unstable channel: 1.0.0
- Current version on the stable/release channel: 0.63.1 (nixos 22.11)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@AndersonTorres @brandonedens @jtojnar 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/226265 is already merged into staging branch. Just need to wait for it to trickle down to master via https://github.com/NixOS/nixpkgs/pull/228476
