### ISSUE TITLE
jekyll creates read-only files

### ISSUE THREAD

**Issue by league** [NixOS/nixpkgs#22858]
## Issue description

One uses `jekyll new` to create a new tree of files for generating a web site. So the intent is to edit those files. But the files produced are read-only, so user must do a `chmod` before each new file can be edited.

I haven't looked at the source yet, but I imagine this is because jekyll copies the site template out of an installed gem or something, and all the files there are 444 (read-only) because it's in the Nix store.

### Steps to reproduce

```
% nix-shell -p jekyll --command "jekyll new myweb"
% ls -l myweb
total 36
-r--r--r-- 1 league users  536 Feb 15 22:34 about.md
-r--r--r-- 1 league users  891 Feb 15 22:34 _config.yml
drwxr-xr-x 2 league users 4096 Feb 15 22:34 css
-r--r--r-- 1 league users 1291 Feb 15 22:34 feed.xml
drwxr-xr-x 2 league users 4096 Feb 15 22:34 _includes
-r--r--r-- 1 league users  506 Feb 15 22:34 index.html
drwxr-xr-x 2 league users 4096 Feb 15 22:34 _layouts
drwxr-xr-x 2 league users 4096 Feb 15 22:34 _posts
drwxr-xr-x 2 league users 4096 Feb 15 22:34 _sass
% ls -l myweb/_layouts
total 12
-r--r--r-- 1 league users 248 Feb 15 22:34 default.html
-r--r--r-- 1 league users 209 Feb 15 22:34 page.html
-r--r--r-- 1 league users 618 Feb 15 22:34 post.html
```

## Technical details

* System: NixOS 16.09.1600.140ff04 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1698.2da8a5d

**Comment by veprbl** [comment]
Have you tried reporting this upstream?

**Comment by league** [comment]
I have not. Will consider that – it seems that a fix would be a one-liner after [the copy from the site template](https://github.com/jekyll/jekyll/blob/0f2013114ccf68808bdd3e5699c6f9ad60aaa59c/lib/jekyll/commands/new.rb#L111) to do `FileUtils.chmod_R` or so.

But I'm not able to test easily if that's all that would be needed – the nixpkgs expression is quite behind, carrying jekyll 3.0.1 when current release is 3.4.1. I tried updating too, but ran into bundler problems, and I don't know much about ruby.

**Comment by veprbl** [comment]
You seem to have idea how to fix it. Should really bring this up with upstream.

I don't know much about ruby, but nixpkgs manual has a step by step guide:
http://nixos.org/nixpkgs/manual/#sec-language-ruby
Turned out to be very easy: #23471

**Comment by veprbl** [comment]
So I ran into bundler problems)

**Comment by veprbl** [comment]
Ok, I've pushed a workaround for that
