### ISSUE TITLE
Update request: tracker-miners 3.5.1

### ISSUE THREAD

**Issue by bobby285271** [NixOS/nixpkgs#228639]
- Package name: tracker-miners
- Latest released version: 3.5.1
- Current version on the unstable channel: 3.5.0
<p></p>

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

The package update itself is trivial, but I got stuck at addressing [tracker-miners!449](https://gitlab.gnome.org/GNOME/tracker-miners/-/merge_requests/449). There is now a `BTRFS_IOC_INO_LOOKUP` ioctl check [in `meson.build`](https://gitlab.gnome.org/GNOME/tracker-miners/-/blob/3.5.1/meson.build?ref_type=tags#L181) that runs:

```c
#include <errno.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <linux/btrfs.h>

int main (int argc, char *argv[]) {
    struct btrfs_ioctl_ino_lookup_args args = { 0, };
    int fd = open ("/", O_RDONLY);
    int ret = ioctl (fd, BTRFS_IOC_INO_LOOKUP, &args);
    return (ret < 0 && errno != ENOTTY) ? 1 : 0;
}
```

The program seems to build fine, but does not exit with 0:

```
Checking if "BTRFS_IOC_INO_LOOKUP ioctl is available" runs: NO (1)
```

This makes the Btrfs subvolume feature disabled:

```
Feature Support:
    BTRFS subvolumes:                       false
```

I am not sure where to get start to enable this since in [tracker-miners#267](https://gitlab.gnome.org/GNOME/tracker-miners/-/issues/267) they decide this will be a hard check on next major bump (well, it should be possible to opt-out but it should be possible [to have it enabled](https://build.opensuse.org/public/build/openSUSE:Factory/standard/x86_64/tracker-miners/_log) I guess).

@jtojnar :see_no_evil: 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by bobby285271** [comment]
I saved the program as a separate `test.c` and compiled & ran with `gcc test.c && ./a.out` as root user and it exits with 1 for me as well. `uname -a` says I am on 6.3.0. I use btrfs so `btrfs subvolume list /` as root runs fine for me (if that matters).

Hmmm then this is weird since it sounds like `BTRFS_IOC_INO_LOOKUP` is introduced [very early](https://github.com/torvalds/linux/commit/ac8e9819d71f907a0532b01b22c26b56bbbcbd21) (is this the correct place to check such info?). But later I found in [Fedora rawhide's build log](https://kojipkgs.fedoraproject.org/work/tasks/1140/100421140/build.log) the BTRFS subvolumes feature is disabled as well :thinking:

**Comment by jtojnar** [comment]
Apparently, it falls back to success since I do not use BTRFS: `-1 25 Inappropriate ioctl for device`

<details>
<summary>Modified <code>test.c</code></summary>

```c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <linux/btrfs.h>

int main (int argc, char *argv[]) {
    struct btrfs_ioctl_ino_lookup_args args = { 0, };
    int fd = open ("/", O_RDONLY);
    int ret = ioctl (fd, BTRFS_IOC_INO_LOOKUP, &args);
    printf("%d %d %s\n", ret, errno, strerror(errno));
    return (ret < 0 && errno != ENOTTY) ? 1 : 0;
}
```

</details>

So that does not really sound like a good test.

**Comment by bobby285271** [comment]
Hmmm now I wonder if their original idea is to check whether the code [compiles](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilercompiles), probably knowing `BTRFS_IOC_INO_LOOKUP` is there is already enough?

**Comment by jtojnar** [comment]
Could you try running the modified `test.c` in build sandbox to find out why specifically it fails for you?

**Comment by bobby285271** [comment]
This is using `nix-build` and putting `gcc test.c && ./a.out` in `buildPhase`:

```
building '/nix/store/rk7zkgkx6mw8rv1v00ik65kpvhcy7d0r-test.drv'...
unpacking sources
unpacking source archive /nix/store/0bsbg9ypb9wj12kfpw51dxz2m3vs14im-ci-cd-demo
source root is ci-cd-demo
patching sources
configuring
no configure script, doing nothing
building
-1 1 Operation not permitted
error: builder for '/nix/store/rk7zkgkx6mw8rv1v00ik65kpvhcy7d0r-test.drv' failed with exit code 1;
```

This is not in builder sandbox and run `gcc test.c && ./a.out` as root:

```
-1 2 No such file or directory
```

**Comment by jtojnar** [comment]
The fix is now merged upstream: https://gitlab.gnome.org/GNOME/tracker-miners/-/commit/c08fbe0650d4a2ae915a21764f54c02eda9406d5
