### ISSUE TITLE
nixos: i3lock/xlockmore can no longer verify my password through PAM

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#22862]
I've been running `i3lock` on NixOS successfully for quite a while, but two days ago it stopped working properly. It still locks the screen, alright, but I can no longer unlock it. No matter how often I enter my password, all I get is:

~~~
i3lock[6929]: pam_unix(i3lock:auth): authentication failure; logname= uid=1000 euid=1000 tty=:0.0 ruser= rhost=  user=simons
~~~

in systemd's journal. I have updated to the latest `nixos-unstable` at 17.03pre100896 (4450327), but the problem persists.

**Comment by peti** [comment]
And to add just another data point: `xlockmore` has the same problem.

Curiously enough, when I run either screen locker with "sudo" and enter `root`'s password, both of them unlock just fine! So the problem appears to be related to PAM denying the authentication for normal users.

**Comment by 7c6f434c** [comment]
Looks like an out-of-sync update (fresh `i3lock`, old system) after the #16654 merge.

What does `stat "$(readlink -f  "$(nix-build --no-out-link '<nixpkgs>' -A pam)"/bin/unix_chkpwd)"` print?

**Comment by peti** [comment]
Yes, you are right. My system follows the unstable channel, but my user's profile is based on `master`. Installing `i3lock`  from the system's version of Nixpkgs remedied the issue for me.
