### ISSUE TITLE
NixOS tests fail to run locally with unstable Nix

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#22868]
## Issue description

With unstable Nix (my gut feeling is that it matters) tests from current master fail to run locally. For example:

```
> nix-build -A tests.misc.x86_64-linux nixos/release.nix
these derivations will be built:
  /nix/store/2db5an2sxixml7ccyvfi58chl2p0lmg5-vm-test-run-misc.drv
building path(s) ‘/nix/store/yqmspfvzyg853c26svbglli8i8nrabmf-vm-test-run-misc’
starting VDE switch for network 1
pty_allocate(nonfatal): posix_openpt(): No such file or directory at /nix/store/14d7qr5sfw9v05p2hc9h467cnxnbr6i1-perl-IO-Tty-1.12/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/IO/Pty.pm line 24.
pty_allocate(nonfatal): getpt(): No such file or directory at /nix/store/14d7qr5sfw9v05p2hc9h467cnxnbr6i1-perl-IO-Tty-1.12/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/IO/Pty.pm line 24.
pty_allocate(nonfatal): openpty(): No such file or directory at /nix/store/14d7qr5sfw9v05p2hc9h467cnxnbr6i1-perl-IO-Tty-1.12/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/IO/Pty.pm line 24.
pty_allocate(nonfatal): open(/dev/ptmx): No such file or directory at /nix/store/14d7qr5sfw9v05p2hc9h467cnxnbr6i1-perl-IO-Tty-1.12/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/IO/Pty.pm line 24.
Cannot open a pty at /nix/store/k73dbm2s3kz7f8hvkinqsary635rvxj6-nixos-test-driver/bin/.nixos-test-driver-wrapped line 32.
cleaning up
builder for ‘/nix/store/2db5an2sxixml7ccyvfi58chl2p0lmg5-vm-test-run-misc.drv’ failed with exit code 2
error: build of ‘/nix/store/2db5an2sxixml7ccyvfi58chl2p0lmg5-vm-test-run-misc.drv’ failed
```

### Steps to reproduce

1. `nix-build -A tests.misc.x86_64-linux nixos/release.nix`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 4450327c062a41f7df2f6756057df4ebb6548011 (with unrelated patches on top)
* Nix version: (run `nix-env --version`) `1.12pre4997_1351b0d`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) `17.03.git.181455c7d027`

**Comment by globin** [comment]
Cannot reproduce on 6e12406e30b263ea7ce49a784c85f5a727b5fc8a, are you building with sandboxing turned on?

**Comment by abbradar** [comment]
@globin Yes. My only theory for now is that unstable Nix is to blame...

**Comment by abbradar** [comment]
(if you want to try it out, please remember that Nix will update its state database and reverting back is difficult!)

**Comment by globin** [comment]
@abbradar nah thanks not right now, reinstalled my system twice in the last few weeks %) but that really could be a reason

**Comment by abbradar** [comment]
The last comment's purpose was exactly to stop you from trying :D I'll try to spin up a fresh VM with unstable Nix later and see what happens there...

**Comment by globin** [comment]
I thought so 😉

**Comment by vcunat** [comment]
Also not reproducible here, on that commit hash but with stable nix daemon.

**Comment by abbradar** [comment]
Reproducible on a fresh VM with unstable Nix and sandbox enabled. Potentially a release blocker because unstable Nix will turn stable soon. cc @edolstra

**Comment by globin** [comment]
@abbradar unstable nix won't be default in 17.03

**Comment by dezgeg** [comment]
Yeah, in my testing `nixUnstable` and nix master are quite unstable indeed :)

**Comment by abbradar** [comment]
@globin I meant that Nix would be released from current unstable codebase, along with this bug.

**Comment by abbradar** [comment]
BTW possibly this should be moved to be a Nix issue instead but I'm not sure who's to blame here (maybe our VM code needs to be changed instead)...

**Comment by vcunat** [comment]
I thought there was no release imminent precisely because there are still some bugs.

**Comment by abbradar** [comment]
@vcunat I think so too. Maybe I formed my thoughts incorrectly: I wanted to say this should be fixed before the release of Nix/NixOS (still not sure where the bug lies) because otherwise the tests will suddenly break. It's blocker in that sense, not that it's something urgent that's breaking master.

**Comment by bobvanderlinden** [comment]
It seems this is fixed for me in the latest nixpkgs.

**Comment by orivej** [comment]
Thanks for the confirmation!
