### ISSUE TITLE
Build failure: dwl

### ISSUE THREAD

**Issue by antoniocorbi** [NixOS/nixpkgs#228706]
### Steps To Reproduce

1. build *dwl*

Download DWL stable v0.4 version from github and try to compile via make from source ( not the nixos pkg) I get this linker error:

```
gcc dwl.o util.o `pkg-config --libs wlroots wayland-server xkbcommon libinput pixman-1 xcb xcb-icccm`   `pkg-config --cflags wlroots wayland-server xkbcommon libinput pixman-1 xcb xcb-icccm` -I. -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809L -DVERSION=\"`git describe --tags --dirty 2>/dev/null || echo 0.4`\" -DXWAYLAND -pedantic -Wall -Wextra -Wdeclaration-after-statement -Wno-unused-parameter -Wno-sign-compare -Wshadow -Wunused-macros -Werror=strict-prototypes -Werror=implicit -Werror=return-type -Werror=incompatible-pointer-types -O1 -s -o dwl
/nix/store/9n9gjvzci75gp2sh1c4rh626dhizqynl-binutils-2.39/bin/ld: /nix/store/vxgpmmzidfy06mnlivq1pim4wsx7mphc-expat-2.5.0/lib/libexpat.so.1: referencia a `arc4random_buf@GLIBC_2.36' sin definir
```

### Additional context

I'm very new to nixos and don't understand very well how to build pkgs and install results into the nix store, as I use dwl and it's very  simple to compile and run locally from source I've decide to go this way for the pasts month and it worked, but since a few weeks I get this linker error:

```
'arc4random_buf@GLIBC_2.36' not defined
```

In order to make dwl compile I use this shell.nix:

```
{ pkgs ? import <nixpkgs> {}, unstable ? import <nixos-unstable> {} }:

with pkgs;
mkShell {
  # nativeBuildInputs is usually what you want -- tools you need to run
  buildInputs = [ makeWrapper pixman
                  xlibsWrapper xcbuild xcb-util-cursor xcbutilxrm xcb-imdkit
                  libxkbcommon xorg.xcbutilwm
                  xwayland unstable.wlroots_0_16
                  wayland wayland-utils wayland-scanner wayland-protocols
                  libinput xorg.libX11 xorg.libxcb libxkbcommon];

  nativeBuildInputs = [ pkg-config ];
}
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 22.11 (Raccoon), 22.11.3940.15b75800dce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable"`
 - channels(acorbi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alyssais** [comment]
This is probably because you updated your system, got a new libc, but are still using dwl objects linked against the old libc.

I don't think this is a Nixpkgs issue.

**Comment by antoniocorbi** [comment]
Thanks @alyssais !
That's what I was thinking...but don't know how to resolve it, any ideas or can you point me some place into the docs that help me resolve this?...I'm totally lost with the way nixos works even though I've been using gnu/linux since...forever .

I've also tried the 'standard' dwl (and Hyprland) nixpkgs and both of them don't work for me, I get a black screen with dwl and Hyprland, while my locally dwl-compiled worked until I got that linker error.

Meanwhile I'm using gnome wayland and it works ok but I like the simplicity of dwl.

**Comment by kirillrdy** [comment]
@antoniocorbi hi,

can you explain your motivation for building dwl outside of nixpkgs ?

nixpkgs already cotains dwl 0.4

**Comment by kirillrdy** [comment]
@antoniocorbi sorry I did re read your post, it seems like you are having issues with dwl package from nixpkgs but not dwl you have built yourself.

Can you provide a build configuration to try to reproduce the issue ? and perhaps hardware involved etc

**Comment by antoniocorbi** [comment]
Hi @kirillrdy !
Thanks for your  response :)

I'v been using a patched dwl in Arch linux and I wanted to reproduce my working environment under Nixos.

I'm not new to gnu/linux (Debian, Arch) but Nixos is another kind of beast, so I think the problem is on my side trying to grok Nixos. 
At this moment documentation is a bit confusing for me (old way commands like nix-*, new style commands like 'new subcommand ...', flakes, etc...). It is all a bit messy...the manual still recommends nix-env...but I see more advanced uers/projects using flakes that, btw, are marked as experimental. I hope 23.05 gets a section in the manual in this respect with the 'blessed' way of using nixos, it would be of much help for people starting with it like me :)

So finally I decided to try vanilla 0.4 dwl pkg with no luck. 

When I log into VT1 console and start dwl as I do under Arch I get  a black screen, then I tried vanilla sway pkg with the same black screen, so for Hyprland...it seems the only DE I got working was gnome.

The only log I got about this problem (black screen) was a 'xdg-desktop-portal.service time out' with dwl/sway/Hyprland.

Any help is much appreciated as I would like to try Nixos more in depth.

Thanks!

**Comment by kirillrdy** [comment]
@antoniocorbi greetings, and welcome !

There is certainly a lot of new things/terminologies that will overwhelm almost anybody. I agree that documentation may seem messy, and this is not just because of presence of flakes and non flakes ways of doing things, there are a lot of very different/new concepts at play here.

as for dwl, I just tried on my computer and dwl and sway work without issues

I just disabled all gnome related bits and added to `/etc/nixos/configuration.nix`

```
  programs.sway.enable = true;
```

and added 

```
dwl
dmenu
``` 
to

`environment.systemPackages`


Since, this is most likely not issue with dwl in nixpkgs, I would suggest to move this discussion to https://discourse.nixos.org/.
That way we'll keep github for more specific issues that we may discover.

otherwise, welcome to the journey :-)

**Comment by antoniocorbi** [comment]
Hi @kirillrdy !

Thx for your support, I'll give  a spin to your suggestion.

If you don't mind I've one las question:

Maybe my problems are related to installing sway/dwl/etc... with home-manager? and another one, I would like to use dwl/sway from unstable so how should I modify, i.e. the line:

```
  programs.sway.enable = true;
```

in order to get unstable.sway?

Once again, thanks for your help.

**Comment by kirillrdy** [comment]
I never used home-manager, but if you just use `/etc/nixos/configuration.nix`

```
sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs-unstable
sudo nix-channel --update
```

then in /etc/nixos/configuration.nix

`programs.sway.enable = true`
 `programs.sway.package = (import <nixpkgs-unstable> {}).sway;`

feel free to reach me out on discourse

**Comment by Artturin** [comment]
issue seems fixed
