### ISSUE TITLE
Update request: Buildbot 3.7.0 → 3.8.0

### ISSUE THREAD

**Issue by felixsinger** [NixOS/nixpkgs#228784]
- Package name: Buildbot
- Latest released version: 3.8.0

- Current version on the unstable channel: 3.7.0
- Current version on the stable/release channel: 3.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ryansydnor @lopsided98

Release notes: https://github.com/buildbot/buildbot/releases/tag/v3.8.0

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by felixsinger** [comment]
@ryantm You updated the package last time. Could you have a look at it?

**Comment by lopsided98** [comment]
#229520
