### ISSUE TITLE
`nixos-rebuild boot` not working in an `lxd` container

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#228764]
### Describe the bug

consider the following `/etc/nixos/configuration.nix` **which is running inside of a `lxd` container:**
```console
[root@nixos:~]# cat /etc/nixos/configuration.nix
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/virtualisation/lxc-container.nix"
  ];
}
```

and the corresponding system profile:
```console
[root@nixos:~]# ls -l /nix/var/nix/profiles/
total 3
drwxr-xr-x 3 root root  3 Nov 29 13:45 per-user
lrwxrwxrwx 1 root root 14 Apr 28 17:40 system -> system-23-link
lrwxrwxrwx 1 root root 85 Apr 28 17:38 system-23-link -> /nix/store/18y7msl6iwdzr28bbpmjqh7ajd0ygjc5-nixos-system-nixos-22.11.3940.15b75800dce
```

the **original** `configuration.nix` produces a store path of `18y7msl6iwdzr28bbpmjqh7ajd0ygjc5`

---

now let's modify `configuration.nix` to add a simple file to `/etc`:
```console
[root@nixos:~]# cat /etc/nixos/configuration.nix 
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/virtualisation/lxc-container.nix"
  ];

  environment.etc.foo.text = "this exists";  
}
```

instead of immediately `switch`ing to this **new** configuration, let's set it to activate on `boot`:
```console
[root@nixos:~]# nixos-rebuild boot
building Nix...
building the system configuration...
...
building '/nix/store/0fg3jhxidv9j2rc6xjv13a06sajbra6g-nixos-system-nixos-22.11.3940.15b75800dce.drv'...
```

looking at the system profile it looks like everything is in order here... the `system` symlink has been switched appropriately:
```console
[root@nixos:~]# ls -l /nix/var/nix/profiles/
total 4
drwxr-xr-x 3 root root  3 Nov 29 13:45 per-user
lrwxrwxrwx 1 root root 14 Apr 28 17:42 system -> system-24-link
lrwxrwxrwx 1 root root 85 Apr 28 17:38 system-23-link -> /nix/store/18y7msl6iwdzr28bbpmjqh7ajd0ygjc5-nixos-system-nixos-22.11.3940.15b75800dce
lrwxrwxrwx 1 root root 85 Apr 28 17:42 system-24-link -> /nix/store/b9i8zzyyvqsnqsy22mqcg01ych10cf4h-nixos-system-nixos-22.11.3940.15b75800dce
```

the **new** `configuration.nix` produces a store path of `b9i8zzyyvqsnqsy22mqcg01ych10cf4h`

let's `reboot`, `activate` the new profile, and look at the file we added to `/etc`:
```console
[root@nixos:~]# reboot

...

[root@nixos:~]# cat /etc/foo
cat: /etc/foo: No such file or directory
```

:thinking: 

what happened? what does our system profile say?

```console
[root@nixos:~]# ls -l /nix/var/nix/profiles/
total 5
drwxr-xr-x 3 root root  3 Nov 29 13:45 per-user
lrwxrwxrwx 1 root root 14 Apr 28 17:43 system -> system-25-link
lrwxrwxrwx 1 root root 85 Apr 28 17:38 system-23-link -> /nix/store/18y7msl6iwdzr28bbpmjqh7ajd0ygjc5-nixos-system-nixos-22.11.3940.15b75800dce
lrwxrwxrwx 1 root root 85 Apr 28 17:42 system-24-link -> /nix/store/b9i8zzyyvqsnqsy22mqcg01ych10cf4h-nixos-system-nixos-22.11.3940.15b75800dce
lrwxrwxrwx 1 root root 85 Apr 28 17:43 system-25-link -> /nix/store/18y7msl6iwdzr28bbpmjqh7ajd0ygjc5-nixos-system-nixos-22.11.3940.15b75800dce
```

:exploding_head:

somehow an additional system generation, the **old** system generation, was created, symlinked, and activated!

**additionally worth noting is that `nixos-rebuild switch` + `reboot` works absolutely fine**

at this point i'm completely lost :man_shrugging:

any help? :bowing_man:

### Notify maintainers

... maybe @cdepillabout has run into this before and has some insight because he seems to know what he is doing with `NixOS` running on `lxd`? or at least he can confirm whether he has this issue as well? :heart:

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.104, NixOS, 22.11 (Raccoon), 22.11.3940.15b75800dce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11.3940.15b75800dce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cdepillabout** [comment]
@aanderse I can confirm I'm seeing the same thing.  I followed basically the steps you laid out for testing this.

Before running `sudo nix-channel --update`, I am on `22.11.2939.96e18717904`.

My profiles look like this:

```console
$ ls -l /nix/var/nix/profiles/
...
lrwxrwxrwx 1 root root   14 Apr 22 11:15 system -> system-15-link
lrwxrwxrwx 1 root root   89 Mar  4 15:21 system-14-link -> /nix/store/f2ghbqw7l95m62cm2zaql0zp0srs9j7q-nixos-system-lxc-nixos-22.11.2939.96e18717904
lrwxrwxrwx 1 root root   88 Mar  7 07:36 system-15-link -> /nix/store/n8gm6yvssigrb3apzcv39x6g4ys5ylcp-nixos-system-lxc-nixos-22.11.740.7a6a010c3a1
```

I then run `sudo nix-channel --update`, and I'm now on `22.11.3955.7449971a3ec`.

I then run `sudo nixos-rebuild boot`, and my profiles look like:

```console
$ ls -l /nix/var/nix/profiles/
lrwxrwxrwx 1 root root   14 Apr 29 16:41 system -> system-16-link
lrwxrwxrwx 1 root root   89 Mar  4 15:21 system-14-link -> /nix/store/f2ghbqw7l95m62cm2zaql0zp0srs9j7q-nixos-system-lxc-nixos-22.11.2939.96e18717904
lrwxrwxrwx 1 root root   88 Mar  7 07:36 system-15-link -> /nix/store/n8gm6yvssigrb3apzcv39x6g4ys5ylcp-nixos-system-lxc-nixos-22.11.740.7a6a010c3a1
lrwxrwxrwx 1 root root   89 Apr 29 16:41 system-16-link -> /nix/store/hr85lnf0pmn1i25y29nw0skjcfxhpjnv-nixos-system-lxc-nixos-22.11.3955.7449971a3ec
```

I then run `sudo poweroff` and restart the LXC container.  After logging back in, I can confirm a new profile has been created and it is pointing to the previous profile for some reason:

```console
$ ls -l /nix/var/nix/profiles/
lrwxrwxrwx 1 root root   14 Apr 29 16:56 system -> system-17-link
lrwxrwxrwx 1 root root   89 Mar  4 15:21 system-14-link -> /nix/store/f2ghbqw7l95m62cm2zaql0zp0srs9j7q-nixos-system-lxc-nixos-22.11.2939.96e18717904
lrwxrwxrwx 1 root root   88 Mar  7 07:36 system-15-link -> /nix/store/n8gm6yvssigrb3apzcv39x6g4ys5ylcp-nixos-system-lxc-nixos-22.11.740.7a6a010c3a1
lrwxrwxrwx 1 root root   89 Apr 29 16:41 system-16-link -> /nix/store/hr85lnf0pmn1i25y29nw0skjcfxhpjnv-nixos-system-lxc-nixos-22.11.3955.7449971a3ec
lrwxrwxrwx 1 root root   88 Apr 29 16:56 system-17-link -> /nix/store/n8gm6yvssigrb3apzcv39x6g4ys5ylcp-nixos-system-lxc-nixos-22.11.740.7a6a010c3a1
```

Although, at this point, if I jump into `nix repl` and look at the nixos version, it does appear to be pointing to the latest NixOS version (which is system-16-link in my example).  So this at least looks correct??

```console
$ nix repl '<nixpkgs>'
nix-repl> lib.version
"22.11.3955.7449971a3ec"
```

I'm not sure I understand exactly the semantics of `nixos-rebuild switch` vs `nixos-rebuild boot`, or how exactly the `/nix/var/nix/profiles/` works.  It is not clear to me what is the "correct" thing to happen at each of these steps.

**Comment by cdepillabout** [comment]
I should add the following two things:

- I can also confirm that doing `sudo nixos-rebuild switch` followed by `sudo `poweroff`, and then booting the machine back up does get the correct profile setup, as @aanderse reported.

- I'm not able to confirm that `sudo nixos-rebuild boot` was ever working for me in my LXC container.  Looking at some of my previous system profiles, I see the same Nixpkgs commit hash being reused over and over again (corresponding to the bug you'd expect).  It is possible that `sudo nixos-rebuild boot` has never worked in an LXC container.  I don't have any ideas here, except that maybe the `${modulesPath}/virtualisation/lxc-container.nix` module is doing something bad?

**Comment by aanderse** [comment]
Thanks for looking and confirming @cdepillabout!

I'm not sure the answer lies in the `switch-to-configuration` script... but it is somewhere down that path so I'll ping our expert @dasJ in case they can take a look and provide any useful insight.

I'm also not exactly sure who else to ping specifically about this... so I'll just ping some random people who know a fair bit about the lower levels of NixOS in case they can provide any insight 🤷‍♂️ 

ping @infinisil @Mic92 @roberth

**Comment by dasJ** [comment]
Could you comment the switch-to-configration output as well?

**Comment by roberth** [comment]
I don't know a lot about lxc, but these unconditional commands look rather suspicious:

https://github.com/NixOS/nixpkgs/blob/5c9977a5240dcd8ba8684c325e8ba5f055dab0ef/nixos/modules/virtualisation/lxc-container.nix#L115-L116

**Comment by aanderse** [comment]
Thanks for the comments everyone! I spent a few minutes poking around and found a few things.

> I don't know a lot about lxc, but these unconditional commands look rather suspicious:

By commenting out this line the new generation is not created, though `nixos-rebuild boot`+`reboot` still doesn't activate the new generation. More on that below...


> Could you comment the switch-to-configration output as well?

- The `switch-to-configuration.pl` doesn't do much when called via `nixos-rebuild boot` - it [calls `exit` pretty early](https://github.com/NixOS/nixpkgs/blob/1a411f23ba299db155a5b45d5e145b85a7aafc42/nixos/modules/system/activation/switch-to-configuration.pl#L107).
- The `nixos-rebuild.sh` script, which calls `switch-to-configuration.pl`, looks to be [properly installing a profile](https://github.com/NixOS/nixpkgs/blob/5dab6490fe6d72b3f120ae8660181e20f396fbdf/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L520) as it should.
- Our `lxd` module includes [an activation script to replace `/sbin/init`](https://github.com/NixOS/nixpkgs/blob/1a411f23ba299db155a5b45d5e145b85a7aafc42/nixos/modules/virtualisation/lxc-container.nix#L195) which `lxd` will use to boot the new system... but since we are running `nixos-rebuild boot` this replacement of `/sbin/init` never happens, which is the cause of the problem here! I confirmed that if I manually replace `/sbin/init` and reboot everything regarding `nixos-rebuild boot` works as expected.

---

I don't think `nixos-rebuild boot` will execute any code from the module system directly (ie. activation scripts). So how do we teach `nixos-rebuild boot` to run `ln -fs $systemConfig/init /sbin/init`?

I appreciate any and all thoughts on this topic :bowing_man:

**Comment by aanderse** [comment]
> I don't think `nixos-rebuild boot` will execute any code from the module system directly (ie. activation scripts). So how do we teach `nixos-rebuild boot` to run `ln -fs $systemConfig/init /sbin/init`?

I found some time to dig into the depths of how NixOS builds systems and now have the understanding I was missing to solve this problem.
