### ISSUE TITLE
glibc-2.25 problems

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#22874]
I'll fill more information soon.

**Comment by vcunat** [comment]
I believe the mass breakage is due to glibc adding `getrandom()`.  `man getrandom` claims it's supported since linux-3.17 &ndash; @edolstra: any chance some of Hydra's build slaves running an older kernel?  The ENOSYS errors returned from python would suggest that.

**Comment by vcunat** [comment]
Right, now I found python [has already patched it](http://bugs.python.org/issue29157) upstream but not released yet, at least not yet for 2.7.

I suspect some other packages might also be doing the same mistake.  In particular, I've seen
> Error in GnuTLS initialization: Failed to acquire random data.

**Comment by vcunat** [comment]
Confirmed: gnutls detects during configure-time and then relies on working `getrandom()` call (and then fails on older kernels).  Link: https://gitlab.com/gnutls/gnutls/issues/121

**Comment by vcunat** [comment]
Hmm, 3.5 branch seems it won't suffer from it, and it seems to be preferable to just update to 3.5 branch anyway, as API+ABI reports in NEWS claim there have only been additions to the lib interfaces.

**Comment by vcunat** [comment]
Hmm, staged again, and apparently other python versions are also affected :-/  I thought there would be fewer additional problems, but at least they're not hidden anymore by failing default python 2 and 3 versions.

**Comment by vcunat** [comment]
So, upstream python won't support glibc-2.25 for 3.3 and 3.4 branches.  Any opinions on what to do about it?  Can we afford to unsupport them before 17.03?  /cc @FRidh @domenkozar.

**Comment by FRidh** [comment]
I don't care about 3.3 and 3.4 but I'm pretty sure others do so I think we should keep them in 17.03. We could try to backport the fix ourselves, or wait a couple of days for another distro. Eventually all distro's are going to face this issue.

**Comment by vcunat** [comment]
Hmm, I think I can actually keep the state as with older glibc without too much effort, and 3.3 even seems unaffected, if I read the source correctly.

**Comment by 7c6f434c** [comment]
I still remember the time when NixPkgs shipped a separate glibc version
for some software. I think it was back in the LinuxThreads vs NTPL days.

**Comment by vcunat** [comment]
All python finally fixed now, I hope, so I can get it out of my head.

**Comment by vcunat** [comment]
All is in master now.
