### ISSUE TITLE
symfony-cli prefers host's PHP binaries over binaries installed by Nix

### ISSUE THREAD

**Issue by ostrolucky** [NixOS/nixpkgs#228735]
### Describe the bug
Given you have PHP installed on your host and one installed in your Nix shell + symfony-cli, eg. with these packages `[pkgs.php82 pkgs.symfony-cli]`, running `symfony serve` will always prefer PHP installed by host. This is not an issue with Nix per se but symfony-cli, but I suggest here that symfony-cli package should be patched so that this does not happen.

### Steps To Reproduce
1. In Terminal 1
```
root@a8c5cfdd65aa:/# echo foo > index.php
root@a8c5cfdd65aa:/# which php
/usr/bin/php
root@a8c5cfdd65aa:/# php -v
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.11, Copyright (c), by Zend Technologies
root@a8c5cfdd65aa:/# nix repl
Welcome to Nix 2.13.3. Type :? for help.

nix-repl> :l <nixpkgs>

nix-repl> :u buildEnv {name="reproducer"; paths = [php82 symfony-cli];}

[nix-shell:/]# php -v
PHP 8.2.5 (cli) (built: Apr 11 2023 16:16:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

[nix-shell:/]# which php
/nix/store/sw4nmv0c60wqd0hrksj2vm2l1384lya8-reproducer/bin/php
[nix-shell:/]# symfony serve

 [OK] Web server listening
      http://127.0.0.1:8000
```
2. In terminal 2
```
root@a8c5cfdd65aa:/# curl --head localhost:8000
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Fri, 28 Apr 2023 14:15:51 GMT
Host: localhost:8000
X-Powered-By: PHP/8.1.2-1ubuntu2.11
```
### Expected behavior
Curl statement should return PHP/8.2.5, as that's the one installed by Nix. Not 8.1.2.

### Additional context
Current workaround is replacing symfony-cli with
```nix
(pkgs.symfony-cli.overrideAttrs (finalAttrs: previousAttrs: {
    nativeBuildInputs = previousAttrs.nativeBuildInputs ++ [ pkgs.makeWrapper ];
    # gotta convince symfony-cli to use php binary installed in this project and not system php
    postInstall = "wrapProgram $out/bin/symfony-cli --set PATH ${php}/bin";
}))
```

which strips out everything $PATH except ${php}/bin

### Notify maintainers

@drupol 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.26-orbstack-00155-g7f01e11590de, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/d6yq7lszskxlpx9ijw56l50sgncbn852-source
```

**Comment by jtojnar** [comment]
That does not make sense. Why does Symfony not use the correct PHP from PATH? Any proper PATH respecting program should return the same thing as `which`.

**Comment by drupol** [comment]
I agree after making a couple of tests, I believe that wrapping the binary with the PHP path is not necessary... Check the screenshot in https://github.com/NixOS/nixpkgs/pull/228766#issuecomment-1528021458

**Comment by ostrolucky** [comment]
I don't know, but this is what they use for discovery of php versions https://github.com/symfony-cli/phpstore. I've not dig depeer than having a brief looks though. And I have to remind that this is about `symfony serve` command. `symfony php` command does look to be honoring $PATH correctly.

**Comment by drupol** [comment]
> And I have to remind that this is about `symfony serve` command. `symfony php` command does look to be honoring $PATH correctly.

Does this means that `symfony-cli` does not employ the same mechanism for locating `php` in the `symfony serve` and `symfony php` commands? which seems totally uncommon. It would be nice to have the confirmation from one of the maintainers.

**Comment by ostrolucky** [comment]
I've prepared a patch at https://github.com/symfony-cli/phpstore/pull/10. I hope they will merge it soon. Otherwise we should consider adding a patch for this here.

**Comment by fabpot** [comment]
I think this issue can be closed now.

**Comment by drupol** [comment]
Yup, thanks again!

**Comment by drupol** [comment]
After thinking twice, the issue will be definitely fixed as soon as you publish a new tag and we provide an update in Nix, I'll leave it open in the meantime.

**Comment by fabpot** [comment]
5.5.7 has been released now.

**Comment by drupol** [comment]
PR is made, I'll wait for the CI to be done before merging and closing this issue.
