### ISSUE TITLE
NixOS isolinux background still uses old logo

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22889]
https://github.com/NixOS/nixpkgs/blob/88908145ead927ecc8ae811f7d31bdef30b5dc0b/nixos/modules/installer/cd-dvd/iso-image.nix#L199-L207

It points at this: ![background](https://raw.githubusercontent.com/NixOS/nixos-artwork/5729ab16c6a5793c10a2913b5a1b3f59b91c36ee/ideas/grub-splash/grub-nixos-1.png)

I'm not sure anyone's made updated splash images with the new logo, but it'd be good to standardize.

**Comment by vcunat** [comment]
Basically an instance of https://github.com/NixOS/nixpkgs/issues/11305

**Comment by copumpkin** [comment]
Oh, true. Unsure whether to leave this open as a concrete thing that can be fixed, since 11305 isn't very specific about what's left to be fixed. Or just to close it and add more detail there?

**Comment by vcunat** [comment]
Best to fix it immediately ;-)

**Comment by dezgeg** [comment]
That is actually the ISOLINUX background only. There's a separate on for GRUB: https://raw.githubusercontent.com/NixOS/nixos-artwork/7ece5356398db14b5513392be4b31f8aedbb85a2/gnome/Gnome_Dark.png
