### ISSUE TITLE
Cannot build flash for Firefox. Broken URL.

### ISSUE THREAD

**Issue by 0BobTheJanitor** [NixOS/nixpkgs#22885]
## Issue description

Download link for Flash for Firefox doesn't exist:

> replacing old ‘firefox-51.0.1’
> installing ‘firefox-51.0.1’
> these derivations will be built:
>   /nix/store/b1gjx0157flc9ghz4ikwk03nfbqkh2br-google-talkplugin_5.41.0.0-1_amd64.deb.drv
>   /nix/store/hw7068lvgqmaidasccwidcxwin25qh9z-google-talk-plugin-5.41.0.0.drv
>   /nix/store/pbxnvjvpah952dblm6pmpwbzphgskp7z-flash_player_npapi_linux.x86_64.tar.gz.drv
>   /nix/store/yxb312qp7mgmilq8rxd7pgb7adrp37b0-flashplayer-24.0.0.194.drv
>   /nix/store/m704gx81m8m3dmrbg5xksv7apq2bgy36-firefox-51.0.1.drv
> building path(s) ‘/nix/store/wi6bz061jcz6ckddgwkxvmakdnv83a7q-flash_player_npapi_linux.x86_64.tar.gz’
> building path(s) ‘/nix/store/22vsfsn1nrw1z36bjr1xagh5dg6xip2s-google-talkplugin_5.41.0.0-1_amd64.deb’

> trying http://dl.google.com/linux/talkplugin/deb/pool/main/g/google-talkplugin/google-talkplugin_5.41.0.0-1_amd64.deb
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> trying https://fpdownload.adobe.com/get/flashplayer/pdc/24.0.0.194/flash_player_npapi_linux.x86_64.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404 Not Found
> error: cannot download flash_player_npapi_linux.x86_64.tar.gz from any mirror
> builder for ‘/nix/store/pbxnvjvpah952dblm6pmpwbzphgskp7z-flash_player_npapi_linux.x86_64.tar.gz.drv’ failed with exit code 1
> cannot build derivation ‘/nix/store/yxb312qp7mgmilq8rxd7pgb7adrp37b0-flashplayer-24.0.0.194.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/m704gx81m8m3dmrbg5xksv7apq2bgy36-firefox-51.0.1.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/m704gx81m8m3dmrbg5xksv7apq2bgy36-firefox-51.0.1.drv’ faile

### Steps to reproduce

> nix-env -iA nixos.firefox

with:

> firefox = {
>   enableGoogleTalkPlugin = true;
>    enableAdobeFlash = true;
> };

> allowUnfree = true;

in config file.

## Technical details

* System: 16.09.1698.2da8a5d (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1698.2da8a5d"

**Comment by 0BobTheJanitor** [comment]
Found a working link, I'll just patch it myself

**Comment by kamilchm** [comment]
see https://github.com/NixOS/nixpkgs/pull/22792
