### ISSUE TITLE
nixos-rebuild switch fails, virtual console-related?

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#22884]
## Issue description
Running `nixos-rebuild switch` fails and gives me some errors. I believe this has been happening since I upgraded to the unstable channel a week or two ago.

Here is the error: https://hastebin.com/awiboqanuw.sql
and here is my configuration.nix as well: http://sprunge.us/NZDX

### Steps to reproduce
Not sure. I guess perhaps install the same packages as me and try a rebuild.

## Technical details

* System: 17.03pre100896.4450327 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre100896.4450327"

**Comment by globin** [comment]
Should be fixed now see #22470

**Comment by Soundtoxin** [comment]
I really didn't want to have to post here again, but I read through the other issue, rebooted, tried again and failed. I slept on it in case I was missing something obvious, but was I supposed to do one of the workarounds from that thread or something?

**Comment by Mic92** [comment]
@Soundtoxin No, actually you have to wait until your channel contains the fix. The pull request was merged into master. Probable it is already there.
