### ISSUE TITLE
Cannot configure keyboard layout in X before logging into gnome-shell.

### ISSUE THREAD

**Issue by mogria** [NixOS/nixpkgs#22895]
## Issue description

When i first boot my NixOS or i'm logging out of my account and trying to login again I get the default keyboard layout instead of my configured one (German (Switzerland)).

After I login tough i get the correct keyboard layout (I configured it in the gnome settings again), so I think the X configuration doesn't apply correctly.

After login I can also use `setxkbdmap ch` to get the correct keyboard layout, but setting `  services.xserver.layout = "ch";` doesn't seem to work.

### Steps to reproduce

I'm using the following configuration for my graphical interface:
https://github.com/mogria/nixos-config/blob/master/graphical.nix#L4
```
  services.xserver.enable = true;
  services.xserver.layout = "ch";
  services.xserver.xkbVariant = "quertz";
  services.xserver.xkbModel = "pc104";
  services.xserver.xkbOptions = "terminate:ctrl_alt_bksp, eurosign:e";

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3 = {
    enable = true;
  };
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`16.09.1698.2da8a5d (Flounder)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.6`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"16.09.1698.2da8a5d"`

**Comment by ndowens** [comment]
Try setting i18n.consoleUseXkbConfig to true suppose to set console keyboard to xservers setting

**Comment by dezgeg** [comment]
There are similar reports for this being a GDM problem: https://github.com/NixOS/nixpkgs/issues/14318.

**Comment by mogria** [comment]
@ndowens I tried setting it, but the result is the same as before. But this seems to be the same issue as dezgeg mentioned --> #14318
