### ISSUE TITLE
Touchpad is affected after suspend

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#22894]
## Issue description

This is a two-fold issue that is related to #20189.
On a laptop where the touchpad works out of the box with NixOS (HP EliteBook), that is without changing the value of any of the following two options:

    services.xserver.synaptics.enable
    services.xserver.libinput.enable

the touchpad starts bugging after suspend (pass in absolute mode as described in the aforementioned issue).

If I add:

    services.xserver.synaptics.enable = true;

to my configuration, it solves the problem.

If instead I add:

    services.xserver.libinput.enable = true;

to my configuration, it solves partially the problem but the two-fingers vertical scrolling is inverted!

Given that @dezgeg said on the other issue that

> I guess we can just set services.xserver.libinput.enable = true; by default. According to Arch wiki, the synaptics driver is deprecated / not updated anymore.

I assumed it would be better to use the latter solution than the former but it has this scrolling problem...

### Steps to reproduce

Boot, call `systemctl suspend`, wake up, try the touchpad.

## Technical details

* System: 16.09.1623.74f24c7 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1623.74f24c7"

**Comment by lheckemann** [comment]
Try setting `services.xserver.libinput.naturalScrolling` to your preference along with enabling libinput.

**Comment by Zimmi48** [comment]
Thanks! Setting it to true solved my problem. And now I understand the meaning of this option. But I don't think it is really clear what it does from just reading the description and that's why I hadn't touched it in the first place.
Still the different behavior before and after suspend when no option is set might still be an issue worth investigating so I'll leave it to someone else to close this issue.
