### ISSUE TITLE
Nextcloud dbpassFile is read at evaluation time and leaks into nix store

### ISSUE THREAD

**Issue by brainrake** [NixOS/nixpkgs#228971]
### Describe the bug
Nextcloud service reads and leaks database secret file during nix evaluation.

### Steps To Reproduce
1. Use the following NixOS configuration options:
```
nextcloud.database.createLocally = true;
nextcloud.config.dbpassFile = "/dbpass";
```
2. Build the configuration (no need to activate it)
3. The file is read during evaluation, as introduced here
https://github.com/NixOS/nixpkgs/commit/047473aa32471086d42177c3b70c573ea1b748db#diff-80ddb2d38f0f6e01125ccb8683381d7be20be1df3dce01e5c200dd74f5173623R858
4. The password leaks into the world-readable nix store.
5. If the configuration is built in a pure context, such as a flake, evaluation fails because access to absolute paths is forbidden. If built in an impure context, it might fail with a permission error.

### Expected behavior
dbpassFile is not read during evaluation, but at service runtime, and it doesn't leak.

### Notify maintainers

@ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.71, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-21.11pre312972.a51aa6523bd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
cc @onny .
I guess the `initialScript` may be removed entirely, see also my comment in https://github.com/NixOS/nixpkgs/pull/150858#discussion_r875691486.

Also, instead of this password stuff we should switch to unix socket auth and disallow setting a password IMHO (in this very case the database is on the same host).

**Comment by Misterio77** [comment]
Just a heads up: I'm currently working on this and should open up a PR soonish

**Comment by Ma27** [comment]
Awesome, thanks!
