### ISSUE TITLE
Package request: cargo-info

### ISSUE THREAD

**Issue by Nehctarg** [NixOS/nixpkgs#228947]
**Project description**

`cargo-info` is a cargo subcommand, which shows crates info from crates.io. See their [README](https://gitlab.com/imp/cargo-info/-/blob/main/README.md) for an output example.

**Metadata**

* homepage URL: https://gitlab.com/imp/cargo-info
* source URL: https://gitlab.com/imp/cargo-info
* license: mit OR apache
* platforms: unix, linux, and darwin

**Comment by figsoda** [comment]
#229157
