### ISSUE TITLE
[Stumpwm] Cannot load-modules anymore

### ISSUE THREAD

**Issue by CharlesHD** [NixOS/nixpkgs#228980]
### Describe the bug
Since #208198 PM stumpwm is now up to date but I have an issue in stumpwm module loading. SBCL will return the a package conflict error between packages "CLOSER-COMMON-LISP" and "DYNAMIC-MXINS"

### Steps To Reproduce
1. Add `windowManager.stumpwm.enable = true;` to your `/etc/nixos/configuration.nix file`
2. Download stumpwm contrib modules in an appropriate directory `git clone https://github.com/stumpwm/stumpwm-contrib.git ~/.stumpwm.d/modules`
3. Create a minimal `~/.config/stumpwm/config` file:
```lisp
(init-load-path "/path/to/home/.stumpwm.d/modules") ;; put the correct path to where you cloned stumpwm contrib
(load-module "battery-portable") ;; this is the line causing an issue
```
4. Either reboot using stumpwm or refresh the stumpwm config using `reloadrc` command (by default keystrokes are: `CTRL-t ; loadrc Enter`)

### Expected behavior
Modules are loaded as expected

### Metadata
Results of `nix-shell -p nix-info --run "nix-info -m"`:
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.313, NixOS, 23.05 (Stoat), 23.05pre478022.d6b863fd9b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(charleshd): `"home-manager, nixpkgs-23.05pre476152.2362848adf8"`
 - channels(root): `"nixos-23.05pre478022.d6b863fd9b7, nixpkgs-23.05pre476152.2362848adf8"`
 - nixpkgs: `/home/charleshd/.nix-defexpr/channels/nixpkgs`
```

**Comment by 7c6f434c** [comment]
Hm, indeed. And maybe for debugging we should provide access to the «library» version of StumpWM…

**Comment by Uthar** [comment]
We could try building using the Makefile instead of save-lisp-and-die. I did, but then there were problems with missing HOME.  Then the problem was that the stumpwm build script seems to want to remember the value of HOME from compile-time on run-time (something like "/build")

How did stumpwm work previously in nixpkgs?

**Comment by Uthar** [comment]
Can you try with this? https://github.com/NixOS/nixpkgs/issues/228980
