### ISSUE TITLE
Package request: phpactor (Vim plugin)

### ISSUE THREAD

**Issue by opdavies** [NixOS/nixpkgs#229011]
**Project description**

A Vim plugin for working with PHP.

**Metadata**

* homepage URL: https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html
* source URL: https://github.com/phpactor/phpactor
* license: MIT
* platforms: unix, linux, darwin, ...

**Comment by drupol** [comment]
Hey Oliver!

Cool to see some familiar faces in the Nix community !
