### ISSUE TITLE
sudo must be owned by uid 0 and have the setuid bit set

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#22914]
## Issue description
The sudo binary doesn't have an setuid bit that it needs to be useful.
Could be because of the pcap wrappers merge.

### Steps to reproduce
Install sudo, try to run it.

## Technical details

* System: 17.03pre101267.a9584c9 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03pre101267.a9584c9

**Comment by pstn** [comment]
It was just a broken env. Sorry to bother you.

**Comment by Mic92** [comment]
nix-user-chroot breaks sudo for instance. There might a fix for that, but I have not yet looked into it.

**Comment by globin** [comment]
@pstn's occurence was due to the setuid sudo binary being moved from `/run/setuid-wrappers` to `/run/wrappers/bin` and his PATH not yet being updated. I'll add a temporary symlink before the release.

**Comment by MP2E** [comment]
I was bit by this and was very confused for some time, but it turns out that since I was using zsh as my default shell, the PATH was being overwritten by ~/.zshenv. A line in that file was overwriting my PATH! With that line deleted and a reboot, everything works.

So if you're a zsh user bit by this bug, please check both your .zshrc and .zshenv for any lines setting PATH, and remove them.

**Comment by dezgeg** [comment]
Let's keep this issue open until the temporary symlink is added so this isn't forgotten.

**Comment by seagreen** [comment]
What's the symlink fix? I'd like to get `sudo` working again without waiting.

**Comment by 7c6f434c** [comment]
The idea of the symlink fix is just to make `/var/setuid-wrappers` a symlink to `/run/wrappers/bin`

**Comment by seagreen** [comment]
Ohhh, I tried `/run/setuid-wrappers` (from earlier in the thread), not `/var/setuid-wrappers`.

**Comment by globin** [comment]
#23641

**Comment by tinkyholloway** [comment]
I upgraded from 17.03 to 18.03 and I have this problem.

> The idea of the symlink fix is just to make `/var/setuid-wrappers` a symlink to `/run/wrappers/bin`

This did not help.
