### ISSUE TITLE
Sway does not start with Vulkan renderer on AMD GPU

### ISSUE THREAD

**Issue by GrabbenD** [NixOS/nixpkgs#229108]
### Describe the bug
After following instructions from https://nixos.wiki/wiki/Sway, the Sway DE starts just as expected. However, when you attempt to start it with `WLR_RENDERER=vulkan` it fails due to:
```console
$ WLR_RENDERER=vulkan sway
00:00:00.027 [wlr] [render/vulkan/vulkan.c:185] Could not create instance: ERROR_LAYER_NOT_PRESENT (-6)
00:00:00.027 [wlr] [render/vulkan/renderer.c:1794] creating vulkan instance for renderer failed
00:00:00.027 [wlr] [render/wlr_renderer.c:271] Failed to create a Vulkan renderer
00:00:00.027 [wlr] [render/wlr_renderer.c:333] Could not initialize renderer
00:00:00.027 [sway/server.c:79] Failed to create renderer
```

This is with amdgpu/mesa driver on a AMD RX 6800 XT. `amdvlk` is not installed since this prevents Halo Infinite from launching:

```nix
# https://wiki.archlinux.org/title/AMDGPU
{ config, pkgs, lib, ... }: {
  boot.initrd.kernelModules = [ "amdgpu" ]; # Fonts fix
  services.xserver.videoDrivers = [ "amdgpu" ]; # Wayland

  hardware.opengl = {
    # Mesa
    enable = true;

    # Vulkan
    driSupport = true;
    driSupport32Bit = true; # Steam support
  
    extraPackages = with pkgs; [
      # Vulkan
      #amdvlk # Outdated
      
      # HIP
      #rocm-opencl-icd
      #rocm-opencl-runtime

      # VAAPI
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
  
  # HIP
  #systemd.tmpfiles.rules = [
  #	"L+    /opt/rocm/hip   -    -    -     -    ${pkgs.hip}"
  #];
}

```

### Steps To Reproduce
1. Follow: https://nixos.wiki/wiki/Sway,
2. Run: `$ WLR_RENDERER=vulkan sway`

### Expected behavior
I was able to use `WLR_RENDERER=vulkan` with my previous NVIDIA GPU.

### Notify maintainers

@primeos
@Synthetica9

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.13, NixOS, 23.05 (Stoat), 23.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by GrabbenD** [comment]
Not sure if related but I've also discovered that starting Sway with default renderer (`gles2`) triggers this warning:
```console
$ sway
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
00:00:00.030 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
```
I can run Steam, games and my Brave browser without issues even though the warning is present.

**Comment by GrabbenD** [comment]
I've verified that I'm able to use `WLR_RENDERER=vulkan` with Hyprland Wayland compositor.
Is something missing in the packaging process of Sway in that case?

**Comment by vcunat** [comment]
I'd suspect version mismatch like in https://github.com/NixOS/nixpkgs/issues/228586#issuecomment-1527030148

**Comment by GrabbenD** [comment]
@vcunat Hardware acceleration through MESA works if Sway is launched with GLES2 api. Are Vulkan and GLES2 relying on different subconponents of MESA in that case (since I'm not using `amdvlk`)?

**Comment by vcunat** [comment]
I don't know the details of this, I'm afraid.

**Comment by azuwis** [comment]
Try adding:

```
environment.systemPackages = [ pkgs.vulkan-validation-layers ];
```

**Comment by GrabbenD** [comment]
Thanks @azuwis
Now there's a different error:
```shell
$ sway
2023-06-04 16:12:35 - [main.c:582] wl_display_roundtrip failed
Segmentation fault (core dumped)
```
Here's the full log from: [$ sway -d |& tee log.txt](https://github.com/NixOS/nixpkgs/files/11645851/log.txt)

**Comment by vcunat** [comment]
Let's close until proven otherwise.
