### ISSUE TITLE
Build failure: swift

### ISSUE THREAD

**Issue by usdogu** [NixOS/nixpkgs#229280]
### Steps To Reproduce

1. build swift

### Build log

https://gist.github.com/usdogu/ffe34bc27e465a02aeaa1cd4552eb409

### Additional context

N/A running `nix profile install nixpkgs#swift` fails

### Notify maintainers

@dtzWill @trepetti @dduan @trundle @stephank

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
pre-commit-hooks.nix: hooks up to date
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05.20230428.937a9d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/s9yan4kpplycs6i3iplair8q74vz5r5s-source`
```

**Comment by stephank** [comment]
I believe https://github.com/NixOS/nixpkgs/pull/225197 fixes this.
