### ISSUE TITLE
Update request: souper -> latest (using LLVM 4.0)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#22920]
## Issue description

[souper](https://github.com/google/souper) was recently updated to use LLVM 4.0, which is rather good news for my use cases.  Can we update our version to use this?

It also seems they now [more strongly prefer their own KLEE fork](https://github.com/google/souper/commit/ec1f999b5ce28d556d2a813516eb83b1be0c4967) so perhaps we should switch to using that as well?

@taktoa (maintainer)--LMK your thoughts and if you want to tackle it or want me to (I'd probably get to it this weekend).

Thanks!

**Comment by taktoa** [comment]
I'm pretty busy these days but if you're interested in updating it feel free :+1:

**Comment by dtzWill** [comment]
Sure thing!

Although actually we'll need to actually add LLVM 4.0 first, forgot that wasn't in-tree yet :innocent:.
Maybe I'll give that a go as well :+1:
(cc #22630)
