### ISSUE TITLE
Build failure: neovim-nightly (darwin)

### ISSUE THREAD

**Issue by mrcjkb** [NixOS/nixpkgs#229275]
### Steps To Reproduce

1. The [neovim-nightly-overlay build currently fails on MacOS](https://github.com/nix-community/neovim-nightly-overlay/actions/runs/4849755411/jobs/8642035984). This will eventually reach neovim-unwrapped if the cause is not fixed.

### Build log

https://github.com/nix-community/neovim-nightly-overlay/actions/runs/4849755411/jobs/8642035984

### Additional context

The cause is that [lpeg](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lpeg) is now included as a library in Neovim: https://github.com/neovim/neovim/pull/23216.
See also https://github.com/neovim/neovim/issues/23395 for more context.
The implemented workaround in Neovim works for Linux, but not for Darwin, because [bundle libraries cannot be linked with static linker flags](https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos/2339910#2339910) like `-llpeg`.

I have reached out to Roberto Ierusalimschy (the maintainer of lpeg) about adding support for building lpeg as a shared library.

In the meantime, it might make sense to apply a patch to the [lpeg package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/lua-modules/generated-packages.nix#L876).

### Notify maintainers

@teto @figsoda

**Comment by teto** [comment]
as this deals with nightly there is no urgency and I would wait for Roberto's answer. No need to churn commits on nixpkgs for unrelease software.

The patch could also go the neovim's flake or the neovim-overlay flake but likewise I would avoid churn and wait for roberto's answer. Meanwhile people can pin the version of the flake until the issue gets resolved.

**Comment by Kranzes** [comment]
@mrcjkb Is there a patch/overlay we can apply for neovim nightly that will fix the build for Darwin?

**Comment by teto** [comment]
actually I may apply a patch (if it exists) to the neovim upstream flake, I want to avoid neovim core contributors to be "nagged" by nix users else I'll have to remove the neovim's flake.nix :'(

**Comment by Kranzes** [comment]
*if that patch exists* then it seems ok (I hate darwin with a passion).

**Comment by mrcjkb** [comment]
I could look into creating a patch later (it doesn't exist as of now).
It should be enough to build lpeg as a .dylib and to pass that to neovim's `buildInputs` when building for darwin.

**Comment by mrcjkb** [comment]
I've made an attempt at patching it, but it looks like `buildLuarocksPackage` ignores the makefile and uses luarocks (i.e. the build instructions in the rockspec instead). And I can't figure out how to make the lua headers visible to gcc...

I'm going to give up on it for now. Here are my attemts so far in case someone wants to pick it up again: 

* [overlay](https://github.com/mrcjkb/lpeg/blob/liblpeg/nix/overlay.nix)
* [makefile](https://github.com/mrcjkb/lpeg/blob/liblpeg/makefile)

I would say let the darwin build of neovim-nightly rot if nobody complains about it.
It's still possible to install with homebrew.

**Comment by nifoc** [comment]
> I would say let the darwin build of neovim-nightly rot if nobody complains about it.

I will complain about it 🙃

I will also give this a go tomorrow, but `buildLuarocksPackage` ignoring the Makefile already rules out most the obvious things to try ...

**Comment by nifoc** [comment]
I don't have time to make it nicer right now, but maybe someone wants to pick this up.

Since this was mostly trial and error, I added things to the `flake.nix` from `neovim` directly. The following changes make the current neovim `master` branch compile and run on macOS:

```
neovim =
  let
    liblpeg = final.stdenv.mkDerivation {
      pname = "liblpeg";
      inherit (final.luajitPackages.lpeg) version meta src;

      buildInputs = [ final.luajit ];

      buildPhase = ''
        echo $out
        sed -i makefile -e "s/CC = gcc/CC = clang/"
        sed -i makefile -e "s/-bundle/-dynamiclib/"

        make macosx
      '';

      installPhase = ''
        mkdir -p $out/lib
        mv lpeg.so $out/lib/lpeg.dylib
      '';

      nativeBuildInputs = [ final.fixDarwinDylibNames ];
    };
  in
  final.neovim-unwrapped.overrideAttrs (oa: rec {
    version = self.shortRev or "dirty";
    src = ../.;
    preConfigure = ''
      sed -i cmake.config/versiondef.h.in -e 's/@NVIM_VERSION_PRERELEASE@/-dev-${version}/'
    '';
    nativeBuildInputs = oa.nativeBuildInputs ++ [
      liblpeg
      final.libiconv
    ];
  });
```

Current issues:

* Absolutely ugly hack
* Only works on macOS
* ???

Making this intro a proper lib (like `libluv`) and treating it just like `libluv` would probably be the best solution.

**Comment by tmillr** [comment]
Does anyone know why it works just fine with regular `nixpkgs.neovim`?

**Comment by tmillr** [comment]
> > I would say let the darwin build of neovim-nightly rot if nobody complains about it.
> 
> I will complain about it 🙃

👍 As a nix, macOS, and neovim user, I'd like to see this fixed as well. I'm currently unable to use a neovim nightly build as part of my nix setup. Plus it sounds like someone is going to have to fix it eventually anyway (e.g. before nvim v0.9.2 or v0.10), otherwise the standard nix build/install of neovim will fail completely on darwin?

I'd attempt a fix but I don't know much/enough about cmake and c compiler/linker flags (plus not an expert on nix's build system).

**Comment by mrcjkb** [comment]
Roberto (the lpeg maintainer) never got back to me.

Since I'm not a MacOS user, I won't be putting any more effort into this.

I suggest you [reach out to him](https://www.inf.puc-rio.br/~roberto/) and send him a patch based on @nifoc's workaround.

If it doesn't get accepted, you could create a `liblpeg` package in `nixpkgs`.
