### ISSUE TITLE
NixOS installer test simpleUefiGummiboot has been broken since late 2016

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22925]
http://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.installer.simpleUefiGummiboot.x86_64-linux

cc @dezgeg who added it

**Comment by dezgeg** [comment]
It detects the problem as described in https://github.com/NixOS/nixpkgs/issues/22561.

**Comment by copumpkin** [comment]
Oh, fair enough!
