### ISSUE TITLE
pianoteq: error fetching trial packages

### ISSUE THREAD

**Issue by dwf** [NixOS/nixpkgs#229307]
### Describe the bug
Installing any of the trials (I have not tried the commercial) yields a curl error.

### Steps To Reproduce
1. `NIXPKGS_ALLOW_UNFREE=1 nix shell nixpkgs#pianoteq.standard-trial --impure`

### Expected behavior
Be dropped in a nix shell with Pianoteq installed

### Screenshots
```
error: builder for '/nix/store/sq562z4x9xw19w317pn98qagsi0gxcra-pianoteq_linux_trial_v805.7z.drv' failed with exit code 6;
       last 8 log lines:
       > curl: (6) Could not resolve host: null
       > Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
       > curl: (6) Could not resolve host: null
       > Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
       > curl: (6) Could not resolve host: null
       > Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
       > curl: (6) Could not resolve host: null
       >
       For full logs, run 'nix log /nix/store/sq562z4x9xw19w317pn98qagsi0gxcra-pianoteq_linux_trial_v805.7z.drv'.
```

### Notify maintainers

@mausch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/xm7l9m8b693y34cxyha1q6zqmbdzpk3q-nix-info
copying path '/nix/store/xm7l9m8b693y34cxyha1q6zqmbdzpk3q-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-21.11, nixos-21.11.335883.7adc9c14ec7, nixos-hardware"`
 - channels(dwf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dwf** [comment]
Some more recent hashes:

* standard-trial: `pianoteq_linux_trial_v808.7z` -> `sha256-LSrnrjkEhsX9TirUUFs9tNqH2A3cTt3I7YTfcTT6EP8=`
* stage-trial: `pianoteq_stage_linux_trial_v808.7z` -> `sha256-dp0bTzzh4aQ2KQ3z9zk+3meKQY4YRYQ86rccHd3+hAQ=`
* stage 8 (paid): `pianoteq_stage_linux_v808.7z` -> `sha256-9TEIKyzKu6fsLGLt+LOHiRHqnwZS0G+QoKw2KUzjwQM=`

I tried simply overriding these but the error seems a bit more fundamental, something about their site has changed.

**Comment by mausch** [comment]
Hi, I've fixed that recently https://github.com/NixOS/nixpkgs/pull/227777
