### ISSUE TITLE
emacs manual packages miss autoload.

### ISSUE THREAD

**Issue by Vonfry** [NixOS/nixpkgs#229386]
### Describe the bug
Some emacs manual packages such as agda doesn't generate autoload.el.

### Expected behavior
Similar to installing packages by package.el or other elpa/mepla generated packages, autoload.el should be generated.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10, NixOS, 22.11 (Raccoon), 22.11.20221130.596a8e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by jian-lin** [comment]
The fix is to replace `trivialBuild` with `elpaBuild` (or `melpaBuild`, which uses `elpaBuild` under the hood).

**Comment by jian-lin** [comment]
Or do something like [this](https://github.com/NixOS/nixpkgs/pull/230997/files) if `trivialBuild` is used.

**Comment by Vonfry** [comment]
> The fix is to replace `trivialBuild` with `elpaBuild` (or `melpaBuild`, which uses `elpaBuild` under the hood).

It is not a big deal to me to modify locally.

However, there is another question whether manual packages in nixpkgs should generate the autoloaded file by default or not?

**Comment by jian-lin** [comment]
> However, there is another question whether manual packages in nixpkgs should generate the autoloaded file by default or not?

Not generating a `name-autoloads.el` file is a bug to me.

> It is not a big deal to me to modify locally.

It would be good if you make a PR.
