### ISSUE TITLE
Build failure: prismlauncher

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#229358]
### Steps To Reproduce

1. build `prismlauncher`

### Build log

`nix log /nix/store/amvb4xl7q751jg1dq06vvd2jyyw0z0rl-prismlauncher-6.3.drv`
https://gist.github.com/anna328p/4679835ad1a0268f646398b0f07f5432

Notable part:

```
CMake Warning (dev) at /nix/store/b6384n9wc85nvsvbx2xn4p18wajy1nyp-tomlplusplus-3.3.0/lib/cmake/tomlplusplus/tomlplusplusConfigVersion.cmake:45 (math):
  Unexpected character in expression at position 3: ,
  Unexpected character in expression at position 5: F
  Unexpected character in expression at position 6: a
  Unexpected character in expression at position 7: l
  Unexpected character in expression at position 8: s
  Unexpected character in expression at position 9: e
```

`/nix/store/b6384n9wc85nvsvbx2xn4p18wajy1nyp-tomlplusplus-3.3.0/lib/cmake/tomlplusplus/tomlplusplusConfigVersion.cmake` @ lines 43..48:

```
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "(8, False)")
  math(EXPR installedBits "(8, False) * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

Looks like a cmake incompatibility??

### Additional context

possibly connected to #217732?

### Notify maintainers

@Minion3665 @Scrumplex 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.23, NixOS, 23.05 (Stoat), 23.05.20230409.c5cf211`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"home-manager, musnix, nixos-22.05pre341370.4c5906c9489"`
 - channels(anna): `""`
 - nixpkgs: `/nix/store/0xavn7sfcp6awxz7cwh65xmrchza2955-source`

**Comment by Scrumplex** [comment]
Can you try building it manually against the latest nixpkgs-unstable revision using `nix build nixpkgs#prismlauncher`?

**Comment by Scrumplex** [comment]
This is really weird. Looks like something went and replace the first occurrence of `8` in the source files with `(8, False)` in `tomlplusplus`.

This is how it's supposed to look: https://github.com/marzer/tomlplusplus/blob/ad55bae8a11a6eee39e2292b01e95b529b105767/cmake/tomlplusplusConfigVersion.cmake.meson.in

**Comment by anna328p** [comment]
> Can you try building it manually against the latest nixpkgs-unstable revision using `nix build nixpkgs#prismlauncher`?

This was already built against the latest `nixpkgs-unstable-small` at the time, around an hour ago

**Comment by anna328p** [comment]
https://github.com/NixOS/nixpkgs/blob/4dc5d47fd8d1b55eeb4a4326054e88a3418b90b1/pkgs/development/libraries/tomlplusplus/default.nix#L1..L29

this looks completely normal. what is going on?

**Comment by MaxHearnden** [comment]
I have done a bisection and it appears that the first bad commit was https://github.com/nixos/nixpkgs/commit/9a0754061262b3bd5bdc56ddb5dd971f9245b112

**Comment by Scrumplex** [comment]
After bisecting Meson, this bug was introduced by https://github.com/mesonbuild/meson/commit/808d5934dd6c6a6c16f66e9dc51dae6e83e02cef and is still present in master.

**Comment by lilyinstarlight** [comment]
@MaxHearnden #229528 has been merged, but do you think you could make a PR to master to have prismlauncher use its own overriden meson and another PR to staging to undo that change, so that way prismlauncher is at least fixed in the master branch sooner than a few weeks from now and when staging hits master, it won't have that temp fix anymore?

Thank you again!

**Comment by Scrumplex** [comment]
> do you think you could make a PR to master to have prismlauncher use its own overriden meson 

Note that the package that's actually broken here is `tomlplusplus`.

But yes using a fixed version of Meson for this sounds like a good idea.
