### ISSUE TITLE
SwipeView module is missing from Qt 5.7.

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#22946]
## Issue description

Qt 5.7 comes with new modules e.g. SwipeView.

https://doc.qt.io/qt-5/qml-qtquick-controls2-swipeview.html

This module is not installed when installing qt57.qtquickcontrols

### Steps to reproduce

```bash
nix-shell -p qt57.qtquickcontrols
find /nix/store/*qtquickcontrols-5.7* -name SwipeView.qml
```

This gives no results. Perhaps, for some reason the version of QtQuick.Controls is < 2.1.

## Technical details

* Nixpkgs version: nixpkgs release 16.09 and nixpkgs master

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by ttuegel** [comment]
The module is found in `qtquickcontrols2`.
