### ISSUE TITLE
Unable to change settings in kooha

### ISSUE THREAD

**Issue by tqwewe** [NixOS/nixpkgs#229406]
### Describe the bug
After installing the kooha screen recorder, I cannot change any settings. When trying to change a setting, I get a warning in the terminal, and the setting does not update.

```console
(kooha:30633): dconf-WARNING **: 14:50:42.001: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

I tried both stable and unstable versions of kooha.

### Steps To Reproduce
1. Install kooha package
2. Run kooha
3. Go to settings, and try to change any setting

### Expected behavior
Settings should update.

### Notify maintainers
@austinbutler 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.20230407.0040164`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/store/40w1i37kf1s1ljj3a22ngi5b66bsd225-source`
```

**Comment by zendo** [comment]
Which desktop environment are you using？

**Comment by tqwewe** [comment]
KDE on NixOS @zendo

**Comment by zendo** [comment]
`programs.dconf.enable = true;`

Try this, it was needed for most gtk apps outside Gnome.

**Comment by tqwewe** [comment]
Hmm I tried adding it to my home manager config, but that failed with `The option `programs.dconf' does not exist`.
So I added it to my system config and updated... but sadly it didn't resolve the issue with kooha

**Comment by zendo** [comment]
Reboot maybe?

**Comment by skeet70** [comment]
I had the same issue on NIxOS w/sway. Set `programs.dconf.enable = true` and rebuilt, which fixed it.

**Comment by austinbutler** [comment]
Sounds like a workaround has been identified, so closing this. We can reopen if needed.
