### ISSUE TITLE
Dive: Nix version does not react to keyboard input

### ISSUE THREAD

**Issue by ostrolucky** [NixOS/nixpkgs#229455]
### Describe the bug
Running dive version that's in nixpkgs will bring you to initial screen, but program does not react to any input, not even CTRL+C. I have to kill the process by closing terminal tab. This works fine when using version from homebrew.

### Steps To Reproduce
1. `nix run nixpkgs#dive busybox`
2. Press ctrl+c

### Expected behavior
Input should work. Software shouldn't be frozen.

### Notify maintainers
@marsam @spacekookie @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixpkgs"`
 - channels(gostrolucky): `"darwin, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
Can't reproduce on Linux, works as expected, don't know why it wouldn't work on darwin.

**Comment by ostrolucky** [comment]
I don't know either. But 0.9.2 version from Nix works correctly.

**Comment by nrhtr** [comment]
I can reproduce this and version 0.11.0 in `nixos-unstable` resolves the issue for me.

**Comment by ostrolucky** [comment]
Indeed, new version works correctly, we can close
