### ISSUE TITLE
Nix NSS name service (libnss_8.so) is incompatible with Debian/Ubuntu

### ISSUE THREAD

**Issue by ashgillman** [NixOS/nixpkgs#229486]
**Describe the bug**

I'm unable to retrieve my user details with `getent` in a Nix standalone installation on Ubuntu.

**Steps To Reproduce**

```
$ /nix/store/k20hh5k7b4ll7ll5j0x72z3d6f39zazq-getent-glibc-2.37-8/bin/getent passwd <user>

$ /usr/bin/getent passwd <user>
<user>:x:<uid>:<gid>:<name>,:/home/<user>:/bin/bash
```

I do have `nscd` running:
```
sudo systemctl status nscd
● nscd.service - Name Service Cache Daemon
     Loaded: loaded (/lib/systemd/system/nscd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-20 10:49:44 AEST; 6 days ago
   Main PID: 851 (nscd)
      Tasks: 8 (limit: 38131)
     Memory: 1.1M
     CGroup: /system.slice/nscd.service
             └─851 /usr/sbin/nscd

Apr 20 10:49:44 gillman-tv systemd[1]: Starting Name Service Cache Daemon...
Apr 20 10:49:44 gillman-tv nscd[851]: 851 monitoring file `/etc/services` (1)
Apr 20 10:49:44 gillman-tv nscd[851]: 851 monitoring directory `/etc` (2)
Apr 20 10:49:44 gillman-tv systemd[1]: Started Name Service Cache Daemon.

```

**More info**
Tracing through the files of each of the commands with `strace`:

In system shell:
```
$ strace  getent passwd gil2a4 2>&1 | grep open
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnss_db.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdb-5.3.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/var/lib/misc/DB_CONFIG", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/var/lib/misc/passwd.db", O_RDONLY) = 3
openat(AT_FDCWD, "/var/lib/misc/passwd.db", O_RDONLY) = 3
```

In NIx shell:
```
$ strace  getent passwd gil2a4 2>&1 | grep open
openat(AT_FDCWD, "/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/glibc-hwcaps/x86-64-v3/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/glibc-hwcaps/x86-64-v2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/nix/store/4isa2k1vj05g0hpc5wxjqacb0fq9dg08-glibc-locales-2.37-8/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libnss_db.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/var/db/passwd.db", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

The issue seems to be that the passwd.db file location is hard-coded, on Debian systems it is at /var/lib/misc/passwd.db, but on other systems it is at /var/db/passwd.db.
I guess this is what nscd is supposed to solve, but it seems to be ignored. I'm not sure if nscd is actually monitoring /var/run/nscd/socket, it doesn't seem to be referenced above by strace.

**`nix-env --version` output**
nix-env (Nix) 2.13.3
nixpkgs https://nixos.org/channels/nixos-22.11

**Additional context**

I'm having this issue trying to get Emacs to find my home directory, https://github.com/NixOS/nixpkgs/issues/12335
Having nscd running is the proposed solution, but doesn't seem to be working for me.

Maybe relevant? https://github.com/NixOS/nixpkgs/issues/1868

**Comment by ashgillman** [comment]
Thanks @flokli 

Yes, /var/run/nscd/socket exists.

FYI, I'm on Ubuntu not NixOS.

Using Ubuntu's `getent passwd $USER`

```
20:53:06.871 >>> process getent [3979723 -> 851] len 19(19)
0000  02 00 00 00 0b 00 00 00  07 00 00 00 70 61 73 73  ............pass
0010  77 64 00                                          wd.
20:53:06.871 >>> process getent [3979723 -> 851] len 19(19)
<redacted>
20:53:06.872 >>> process nscd [851 -> 3979723] len 36(36)
<redacted>
```

The actual output of that command, `getent passwd $USER`, was:
`<user>:x:521549:521549:<name>,:/<home>:/bin/bash`

And using `nix shell nixpkgs#getent`, `getent passwd $USER`

```
20:54:00.775 >>> process getent [3980326 -> 851] len 19(19)
0000  02 00 00 00 0b 00 00 00  07 00 00 00 70 61 73 73  ............pass
0010  77 64 00                                          wd.
20:54:00.776 >>> process getent [3980326 -> 851] len 19(19)
<redacted>
20:54:00.776 >>> process nscd [851 -> 3980326] len 36(36)
<redacted>
```

The actual output of that command, ``getent passwd $USER`, was blank.

To me, it looks like both native and Nix glibs are using the socket, but only the native one is getting the right information.

**Comment by flokli** [comment]
Unfortunately the data of the request and response was redacted.

Did you spot any differences in the initial handshake, or request sent from `getent`?

**Comment by ashgillman** [comment]
Yes sorry, I'm not sure exactly what the information is so I redacted it.
But the bytes in both the handshake and the response are the same.
First getent passes "passwd", then my username, and the response is empty (so there was no need to redact)

```
09:30:07.435 >>> process getent [560725 -> 851] len 19(19)
0000  02 00 00 00 0b 00 00 00  07 00 00 00 70 61 73 73  ............pass
0010  77 64 00                                          wd.
09:30:07.435 >>> process getent [560725 -> 851] len 19(19)
<username>
0000  02 00 00 00 00 00 00 00  07 00 00 00 <username>  ............<username>
0010  <username>                                          <username>.
09:30:07.435 >>> process nscd [851 -> 560725] len 36(36)
0000  02 00 00 00 ff ff ff ff  00 00 00 00 00 00 00 00  ................
0010  ff ff ff ff ff ff ff ff  00 00 00 00 00 00 00 00  ................
0020  00 00 00 00                                       ....
```

Potentially relevant indirectly, I also get DNS requests with a blank response:

```
09:34:43.337 >>> process DNS Res~er #722 [1579026 -> 851] len 42(42)
0000  02 00 00 00 0e 00 00 00  1e 00 00 00 61 64 64 6f  ............addo
0010  6e 73 2d 70 61 2e 63 6c  69 65 6e 74 73 36 2e 67  ns-pa.clients6.g
0020  6f 6f 67 6c 65 2e 63 6f  6d 00                    oogle.com.
09:34:43.337 >>> process nscd [851 -> 1579026] len 32(32)
0000  02 00 00 00 ff ff ff ff  00 00 00 00 00 00 00 00  ................
0010  ff ff ff ff ff ff ff ff  00 00 00 00 ff ff ff ff  ................
```

I have no understanding of `nscd`, is the last line to response to a request that the original process would receive? I guess this would be consistent with the `nscd` daemon not running correctly and always giving a blank response (so a host error, not a Nix problem)?

**Comment by ashgillman** [comment]
(If not a Nixpkgs problem, apologies for using your time but thank you very much for teaching me some socket debugging tools - Google search didn't find me any useful tooks like `sockdump`)

**Comment by flokli** [comment]
I didn't fully dig into the responses, but if nscd is also not able to use the host NSS modules, it looks like there's some misconfiguration on the host.

glibc code falls back to trying to resolve locally (but can't for nix-built binaries), which might be why your `/usr/bin/getent` might work, but the nix-built `getent` does not.

Please make sure your nscd can properly read `/etc/nsswitch.conf`, and the nss modules specified in there are reachable via a dlopen of `libnss_$name.so` (so in one of the rpaths, or `LD_LIBRARY_PATH` - you should see what's going on by strace-ing `nscd`.

**Comment by ashgillman** [comment]
Thanks very much, your help is much appreciated. I'll close this now as I don't believe to to be a Nixpkgs issue.
