### ISSUE TITLE
Linux kbuild incompatible with "nix-shell -p qt5.full"

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#22945]
## Issue description
I'm trying to setup a development environment for Linux using nix-shell. In particular, I'd like to be able to run "make xconfig". The problem is how the Linux kbuild system finds 'moc'.

In ```<linux>/scripts/kconfig/Makefile```:

```
	if pkg-config --exists Qt5Core; then \
	    cflags="-std=c++11 -fPIC `pkg-config --cflags Qt5Core Qt5Gui Qt5Widgets`"; \
	    libs=`pkg-config --libs Qt5Core Qt5Gui Qt5Widgets`; \
	    moc=`pkg-config --variable=host_bins Qt5Core`/moc; \
```

So we see that 'moc' is found by running ```pkg-config --variable=host_bins Qt5Core```. But that fails:

```
$ nix-shell -p qt5.full -p pkgconfig --run "pkg-config --variable=host_bins Qt5Core"
/nix/store/7bqgvpwg2jkiwrlzw65w8664a5084j80-qtbase-5.6.1-1/bin
$ ls -l /nix/store/7bqgvpwg2jkiwrlzw65w8664a5084j80-qtbase-5.6.1-1/bin
ls: cannot access '/nix/store/7bqgvpwg2jkiwrlzw65w8664a5084j80-qtbase-5.6.1-1/bin': No such file or directory
```

Is this a (slightly) bad assumption in Linux kbuild or a bug in Nix qt5 packaging?

### Steps to reproduce
```
$ cd $linux_src
$ nix-shell -p gnumake -p ncurses -p pkgconfig -p bc -p qt5.full --run "export hardeningDisable=all; make xconfig"
  MOC     scripts/kconfig/qconf.moc
/bin/sh: /nix/store/7bqgvpwg2jkiwrlzw65w8664a5084j80-qtbase-5.6.1-1/bin/moc: No such file or directory
make[1]: *** [scripts/kconfig/Makefile:291: scripts/kconfig/qconf.moc] Error 127
make: *** [Makefile:546: xconfig] Error 2
```

**Comment by ttuegel** [comment]
I suspect this is a problem with the pkgconfig file we ship with Qt.

**Comment by bjornfor** [comment]
The multiple-outputs code moves ./bin to the 'dev' output, breaking the pkg-config file.

Isn't using moveToOutput just a recipe for disaster (in general)? After the build process has embedded paths into the build artifacts then we move the files around?! I feel our multiple-outputs mechanism is expensive in turns of man hours. It saves some megabytes but breaks a lot of code :-( \</rant\>

Anyway, I tried to do a test with adding "-bindir $dev/bin" (and "-hostbindir $dev/bin") to configureFlags. (I didn't want to sed the .pc file after the fact.) But I'm stopped by:

```
$ nix-build -A qt5.qtbase
...
WARNING: substitution variables should be valid bash names,
  "configureFlags+" isn't and therefore was skipped; it might be caused
  by multi-line phases in variables - see #14907 for details.
```

I did the same in a nix-shell, to bypass that variable expansion bug (above). The result is that qt places *some* binaries into ```$dev/bin```, but not the 'moc' tool. That stays put in ```$out/bin```. Too bad.

**Comment by ttuegel** [comment]
> Anyway, I tried to do a test with adding "-bindir $dev/bin" (and "-hostbindir $dev/bin") to configureFlags. (I didn't want to sed the .pc file after the fact.) But I'm stopped by:

You can't do this anyway, I tried. Qt hardcodes the path you give for `-bindir` into all the libraries, so you get circular references. I too would like to avoid `moveToOutput`, but it is the only way to break the circular references. Well, aside from rewriting most of qmake.

(qmake is an unqualified disaster. Literally the worst build tool ever. Folks complain about autotools and cmake, but they don't have hardcoded search and install paths. More than once I have been tempted to remove qmake from our Qt build and tell everybody with a qmake-based project to take a hike. I've never done it, though, because I'm a coward.)

One thing I have done in other packages is to replace the pkg-config file before the build. There is probably a `.pc.in` file around somewhere; for a few packages I have simply rewritten the entire thing and copied it into place in `postPatch`. This is bad, but it's not too bad: Gentoo and Debian rarely use the upstream-provided pkg-config file, IIRC.

**Comment by bjornfor** [comment]
@ttuegel: Thanks for the info. I needed that.

I've written this now (using sed in postFixup): https://github.com/bjornfor/nixpkgs/commit/a81cb9f1c08a1212d34c22ffb430becd54aff8f8

Do you want me to create a PR or just test it myself and apply to master + release-17.03?

**Comment by bjornfor** [comment]
Argh, changing the qt package means the rebuild footprint is so large that there is already a ton of breakage. It's difficult to assess the effect of the change through "nox-review wip ...". I need a Hydra... (but last time I tried to set it up it failed). Bootstrapping is hard.

**Comment by ttuegel** [comment]
I'm in the process of setting up a Hydra right now to test some unrelated mass-rebuilding changes. I'll pull your patch into my test branch when everything is ready. If all goes according to plan, everything will end up in `staging` soon.

**Comment by bjornfor** [comment]
Thanks. I'm getting another machine this weekend, I'll try setting up Hydra there too. Note that I haven't fully tested the commit above, due to recent breakage on master and release-17.03.

**Comment by ttuegel** [comment]
I have Hydra running locally now. I also foreported your changes to Qt 5.8, and some of the Darwin changes that were missing from Qt 5.7.

**Comment by ttuegel** [comment]
Well, that was short-lived. The Hydra evaluator needs far more memory than `nix-instantiate` for some reason. N.B. If Hydra runs OOM and you have to do a hard restart, Hydra will immediately OOM after you reboot... effectively making Hydra a DoS attack.

**Comment by bjornfor** [comment]
Nice...
