### ISSUE TITLE
gcc: undeterministic info pages

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#229470]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A pkgsStatic.buildPackages.gccCrossStageStatic.cc --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A pkgsStatic.buildPackages.gccCrossStageStatic.cc)
```

### Additional context

An example of a diff can be found at https://reproducible.nixos.org/nixos-iso-minimal-r13y/diff/a7ca61e3544ed4d048e59882fae1eb24dbc04f0f5e7b832202581193b2eeca67-ee6aa0602d40df3930bb7192c44be53c703d9b49512904e39ee93b7b09333eb7.html (in `/nix/store/4rll8l0q3ycfpykwn1wqk93x1jqayqkl-x86_64-unknown-linux-musl-stage-static-gcc-12.2.0.drv` which was built from da45bf6ec7bbcc5d1e14d3795c025199f28e0de0)

**Comment by trofi** [comment]
Diff says it comes from `share/info/dir` file (an `.info` index file). I wonder how many tiles it's expected to be ran against the directory: 1 per file (then install order parallelism causes unstable index), 1 per directory with reliance on file order on file system, or inherent `install-info` non-determinism.

**Comment by trofi** [comment]
Yeah, it's a per-file registration. Two builds:

```
$ nix log -f. pkgsStatic.buildPackages.gccCrossStageStatic.cc | fgrep install-info |& unnix

if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/gcc.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/gccinstall.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/cppinternals.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/cpp.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-14.0.0/share/info/gccint.info; \
```

```
$ nix log -f. pkgsStatic.buildPackages.gccCrossStageStatic.cc | fgrep install-info |& unnix

if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/cpp.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/cppinternals.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/gcc.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/gccinstall.info; \
if /<<NIX>>/bash-5.2-p15/bin/bash -c 'install-info --version' >/dev/null 2>&1; then \
    install-info --dir-file=/<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/dir /<<NIX>>/x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info/gccint.info; \
```

Note how `.info` file order is slightly different here. I think we can work it around by removing and regenerating `dir` file with something like https://nixos.org/manual/nixpkgs/stable/#sec-gnu-info-setup and rely on shell globs to do sorting for us.

**Comment by raboof** [comment]
So the saillant bit is in `gcc/Makefile.in`:

```
install-info:: doc installdirs \
    $(DESTDIR)$(infodir)/cpp.info \
    $(DESTDIR)$(infodir)/gcc.info \
    $(DESTDIR)$(infodir)/cppinternals.info \
    $(DESTDIR)$(infodir)/gccinstall.info \
    $(DESTDIR)$(infodir)/gccint.info \
    lang.install-info

$(DESTDIR)$(infodir)/%.info: doc/%.info installdirs
    rm -f $@
    if [ -f $< ]; then \
      for f in $(<)*; do \
        realfile=`echo $$f | sed -e 's|.*/\([^/]*\)$$|\1|'`; \
        $(INSTALL_DATA) $$f $(DESTDIR)$(infodir)/$$realfile; \
        chmod a-x $(DESTDIR)$(infodir)/$$realfile; \
      done; \
    else true; fi
    -if $(SHELL) -c 'install-info --version' >/dev/null 2>&1; then \
      if [ -f $@ ]; then \
        install-info --dir-file=$(DESTDIR)$(infodir)/dir $@; \
      else true; fi; \
    else true; fi;
```

I guess the root cause of the issue is that the `$(DESTDIR)$(infodir)/%.info: doc/%.info installdirs:` rule does not only output to `$(DESTDIR)$(infodir)/%.info`, but also modifies `$(DESTDIR)$(infodir)/dir` as a side effect.

I guess we could restructure the Makefile to install the makefile in a deterministic order, but I wonder if parallelism in the install phase is useful at all for gcc - might be OK to disable it entirely?

**Comment by trofi** [comment]
`gcc` does quite a bit of relinking and file copying in the install phase. I would suggest keeping install phase parallel.

Changing makefiles might be complicated as it's a recursive makefile with different compiler frontends (`c++` and `fortran`). They ought to build and install independently (in parallel). On top of that `Makefile` regeneration requires autotools dependencies for `gcc` which makes bootstrap a bit trickier.

https://nixos.org/manual/nixpkgs/stable/#sec-gnu-info-setup might be a less invasive way to do it. And I think it's generic enough that could be implemented as a hook for more packages.

**Comment by raboof** [comment]
> `gcc` does quite a bit of relinking and file copying in the install phase. I would suggest keeping install phase parallel.

:+1: 

> Changing makefiles might be complicated as it's a recursive makefile with different compiler frontends (`c++` and `fortran`). They ought to build and install independently (in parallel). On top of that `Makefile` regeneration requires autotools dependencies for `gcc` which makes bootstrap a bit trickier.

It seems the gcc sources already don't have a `gcc/Makefile`, so aren't we already (re)generating them?

> https://nixos.org/manual/nixpkgs/stable/#sec-gnu-info-setup might be a less invasive way to do it. And I think it's generic enough that could be implemented as a hook for more packages.

That's a good point. It seems the info files are *already* first generated into `<<NIX>>-x86_64-unknown-linux-musl-stage-static-gcc-12.2.0/share/info` and then somehow moved to `<<NIX>>-x86_64-unknown-linux-musl-stage-static-gcc-12.2.0-info/B/share/info` - it's not obvious to me where that happens, though?

**Comment by trofi** [comment]
`gcc/Makefile` is generated from `Makefile.in` at `./configure` time. `Makefile.in` is committed into `gcc`'s `.git` and is generated from `autogen Makefile.def` (and `Makefile.tpl`) (`autogen` is a program written in `guile`, somewhat heavy on depends).

`-info` output is split out for derivations with `outputs = ["info" ... ]` at `pkgs/build-support/setup-hooks/multiple-outputs.sh:    moveToOutput share/info "${!outputInfo}"`

**Comment by trofi** [comment]
I wonder if `install-info` itself could be fixed to generate consistent `dir` files regardless of the registration order of `.info` files added to it. It feels like that would be the best place to fix it properly. No idea if `dir` structure allows an extension for such mode.

**Comment by raboof** [comment]
> I wonder if `install-info` itself could be fixed to generate consistent `dir` files regardless of the registration order of `.info` files added to it. It feels like that would be the best place to fix it properly. No idea if `dir` structure allows an extension for such mode.

Looking closer, it looks like `install-info` *already* doesn't use the input order, but puts items in alphabetical order. The problem is the 'left' side is *missing* entries. I wonder if `install-info` supports multiple parallel processes trying to write to the same `dir`?

**Comment by raboof** [comment]
https://git.savannah.gnu.org/cgit/texinfo.git/tree/install-info/install-info.c#n2293 seems simple enough, and indeed reads/writes the dir file without any protection against parallel processes...

**Comment by trofi** [comment]
I filed https://gcc.gnu.org/PR109898 upstream to track proper resolution.

**Comment by raboof** [comment]
> I filed https://gcc.gnu.org/PR109898 upstream to track proper resolution.

Thanks! I hadn't found the time to figure out whether the problem was in gcc or further upstream in the autoconf/automake/etc templates (and wasn't sure gcc would welcome reports for such possibly-upstream problems). Great to track a proper solution :+1:
