### ISSUE TITLE
xmonad.enableContribAndExtras fails with xmonad 0.13 upgrade

### ISSUE THREAD

**Issue by tdimiduk** [NixOS/nixpkgs#22940]
## Issue description

services.xserver.windowManager.xmonad.enableContribAndExtras fails with the xmonad 0.13 release since xmonad-extras has a version constraint of < 0.13. 

I don't need extras, so an option to xmonad.enableContrib without extras would be enough to fix this for me (xmonad-extra's hasn't had a release since 2015, I don't know how hard it would be to build with the current version)

### Steps to reproduce
set 
services.xserver.windowManager.xmonad.enableContribExtras = true;

attempt to rebuild, get an error like:
...
Configuring xmonad-extras-0.12.1...
Setup: Encountered missing dependencies:
base <3,
hint >=0.3.3.3 && <0.5,
xmonad >=0.10 && <0.13,
xmonad-contrib >=0.10 && <0.13

## Technical details

* System: NixOS: 17.03pre100896.4450327 (Gorilla)
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre101267.a9584c9

**Comment by joachifm** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/d26ac6afa4cd264b6c8613a28ff09ca87eff45ee, which has yet to hit the channel.

**Comment by tdimiduk** [comment]
Ah, good, I didn't know how to jailbreak (or if it would work) and so was starting in on a patch to add an option to use only contrib (since I don't use anything out of extras), but I guess that isn't needed now.
