### ISSUE TITLE
PPTP VPN connection doesn't work on nixos-unstable's Gnome-shell

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#22947]
## Issue description

Using nixos-unstable with Gnome-shell I can't connect to a PPTP VPN connection, while I can do so on 16.09, with the same configuration.nix file. (I had to load the nf_conntrack_pptp module for it to work) 

Journalctl's relevant text:

```
febr 18 21:52:20 nixos NetworkManager[749]: Plugin /nix/store/q8m4bh25r27yxybbi9awyjgvjf4djgxi-NetworkManager-pptp-gnome-1.2.4/lib/pppd/2.4.5/nm-pptp-pppd-plugin.so loaded.
febr 18 21:52:20 nixos NetworkManager[749]: Using interface ppp0
febr 18 21:52:20 nixos NetworkManager[749]: Connect: ppp0 <--> /dev/pts/1
febr 18 21:52:20 nixos NetworkManager[749]: sh: /bin/ip: No such file or directory
febr 18 21:52:20 nixos NetworkManager[749]: sh: /bin/ip: No such file or directory
febr 18 21:52:51 nixos NetworkManager[749]: LCP: timeout sending Config-Requests
febr 18 21:52:51 nixos NetworkManager[749]: Connection terminated.
febr 18 21:52:51 nixos NetworkManager[749]: Terminating on signal 15
febr 18 21:52:51 nixos NetworkManager[749]: Modem hangup
febr 18 21:52:51 nixos NetworkManager[749]: <warn>  [1487451171.7968] vpn-connection[0x1f38110,7005c9e8-cfd3-435c-bf12-92a2f1778454,"**",0]: VPN plugin: failed: connect-failed (1)
```

### Steps to reproduce

Having the following code in configuration.nix, and issuing `nixos-rebuild switch --upgrade` after changing the default channel to either unstable or 16.09.
 
```
  boot.kernelModules = [ "nf_conntrack_pptp" ];
   services.xserver.displayManager.gdm.enable = true;
   services.xserver.displayManager.gdm.autoLogin = {
     enable = true;
     user = "";
   };
   services.xserver.desktopManager.gnome3.enable = true;
```

## Technical details

* System: 17.03pre101267.a9584c9 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1722.47fbc9c"

**Comment by globin** [comment]
Connection tracking is now disabled by default in newer kernels.

You now have to add the following:
```
networking.firewall.autoLoadConntrackHelpers = true;
```

See 8d5a4c53b8734b1fc10ab4acdcba28451b836fd9 and 8322a12ef2ce6ea5a239b2221aa6f9a2fe84d904
