### ISSUE TITLE
Update KTP for KDE 5

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#22954]
KTP is now part of KDE Applications Bundle, so the latest sources are available in Nixpkgs already, although we do not have them packaged. The older KDE 4-based packages obstruct removal of their dependencies.

Attn. @urkud

**Comment by ttuegel** [comment]
I have work-in-progress [here](https://github.com/ttuegel/nixpkgs/tree/kde-telepathy).

**Comment by joepie91** [comment]
What's the status on this? It seems that nixpkgs now ships some amount of Telepathy-related packages, but it's unclear to me how to actually *install* Telepathy.

**Comment by ttuegel** [comment]
There is not going to be a KDE Frameworks Telepathy port. In fact, the Telepathy project itself is unmaintained upstream, to say nothing of the KDE Telepathy packages. The remaining KDE 4 Telepathy packages were removed because they were broken. (I should have closed this issue when removing those packages, but I forgot it was open.)
