### ISSUE TITLE
Update Kadu for KDE 5

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#22956]
Kadu development continues [upstream](https://gitlab.com/kadu/kadu/wikis/home), but the older KDE 4-based package obstructs removal of its dependencies.

Attn. @ppietrasa

**Comment by ppietrasa** [comment]
Thanks for the info.

 Currently I'm not able to commit my private time to the upgrade. When is the deadline? Dec 2017?

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by jtojnar** [comment]
Kadu seems to have ben removed https://github.com/NixOS/nixpkgs/commit/6236dd8e2d8ebf973bba67b397a30bb52fcf0d22

**Comment by jtojnar** [comment]
It is [abandoned](https://gitlab.com/kadu/kadu/wikis/news#2017-07-18-kadu-is-no-longer-actively-maintained) so packaging alpha version with Qt5 support does not make sense.
