### ISSUE TITLE
Build failure: evcxr

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#229524]
### Steps To Reproduce

1. build *evcxr*

### Build log

https://termbin.com/s5pt

### Additional context

probably since last staging merge

### Notify maintainers

@protoben @Ma27 

### Metadata
nixpkgs e4ad893057db74091ed0e3edf509a72fb83051df

**Comment by Ma27** [comment]
See also https://github.com/evcxr/evcxr/issues/294
