### ISSUE TITLE
Update request: mopidy-soundcloud 3.0.1 → 3.0.2

### ISSUE THREAD

**Issue by chi-xigua** [NixOS/nixpkgs#229523]
- Package name: mopidy-soundcloud
- Latest released version: 3.0.2

- Current version on the unstable channel: 3.0.1
- Current version on the stable/release channel: 3.0.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@spwhitt

Release notes: https://github.com/mopidy/mopidy-soundcloud/releases/tag/v3.0.2

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/250966

**Comment by chi-xigua** [comment]
since been updated by above #250966
