### ISSUE TITLE
Update KGraphViewer for KDE 5

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#22958]
KGraphViewer development continues [upstream](https://cgit.kde.org/kgraphviewer.git/), but the older KDE 4-based version in Nixpkgs obstructs removal of its dependencies.

Attn. @lethalman

**Comment by zraexy** [comment]
Done: 3fa6afdb35c94a02d6f5a01fb1c8927814877fac

**Comment by aanderse** [comment]
@ttuegel as this has been fixed can you please close?
