### ISSUE TITLE
Build failure: paper-note

### ISSUE THREAD

**Issue by me00001** [NixOS/nixpkgs#229634]
### Steps To Reproduce

1. be in nixos-unstable
2. upgrade
3. paper-note build will failed

### Build log
https://paste.dismail.de/?091debc65105071e#f44XkR9Wsshiirpur7g1q5ALJpvs3M4rtvT7HX2VjZn

### Notify maintainers
@ocfox
@j0lol
[me@j0.lol](mailto:me@j0.lol)

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05pre478652.937a9d1ee7b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(suliman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by flokli** [comment]
The upstream github repository and official website seems to be gone - looks like the project is dead. We should probably remove it from nixpkgs?

**Comment by flokli** [comment]
Hmmh, it might be at https://gitlab.com/posidon_software/paper (so we should move references there), but according to https://gitlab.com/posidon_software/paper/-/issues/167#note_1279446605 it's currently unmaintained.

**Comment by j0lol** [comment]
agreed, it seems like the development discord guild is also gone. probably due for removal.
