### ISSUE TITLE
direnv doesn't install completely (shell is not hooked)

### ISSUE THREAD

**Issue by Twiggeh** [NixOS/nixpkgs#229645]
### Describe the bug
Hi I am uncertain whether this is intended behavior or not, excuse me if I am reporting something that is behaving the way its supposed to. 

When using direnv `nix-shell -p direnv`, it installs direnv, but it does [not hook the shell as per installation instructions](https://direnv.net/docs/hook.html), making it not do the thing its supposed to.

### Steps To Reproduce
1. nix-shell -p direnv
2. cd <into directory with a .envrc>
3. direnv allow // nothing happens because the hook is missing

### Expected behavior
That the installation processes would be complete without me needing to manually run `eval "$(direnv hook bash)"`

### Notify maintainers

@Mic92 @flokli @jfroche @zimbatm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230411.5a156c2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(albert): `""`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by flokli** [comment]
This is probably intentional - we don't hook direnv into your she'll via nix-shell - that's a job for the module system. Maybe this should be further clarified on the website.

**Comment by Mic92** [comment]
nix-shell does not provide mechanism to do that and it might be also breaking user's expectations.

You can use home-manager in nix to enable direnv for your configuration:
