### ISSUE TITLE
Wireplumber: Failed to open media device at /dev/media0: No such file or directory

### ISSUE THREAD

**Issue by jankaifer** [NixOS/nixpkgs#229727]
### Describe the bug

I just updated into the latest `nixos-unstable` and I started having this issue where I would receive a blank screen after login in. When I checked the logs I found out that `journalctl` is full of this error:

```
ERROR MediaDevice media_device.cpp:483 /dev/media0[uvcvideo]: Failed to open media device at /dev/media0: No such file or directory
```

It generates 50k of their errors each second If I'm counting correctly.

### Steps To Reproduce
I don't know yet. But this is my config: https://github.com/jankaifer/nixos/tree/908ee18b5bb7cfe29ec937e6595a0f0838464ca3

### Notify maintainers

@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05.git.1a411f23ba29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/persist/home/pearman/dev/jankaifer/nixos/modules/nixpkgs`

```

I'm using Framework Intel 12th gen

### Keywords
pipewire, wireplumber, gnome blank login

**Comment by jankaifer** [comment]
That blank login screen is a bit flaky, sometimes I can log in just fine.

I know this issue is not really actionable, but I'll try to investigate a bit more.

**Comment by K900** [comment]
This looks like https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/443, which is likely actually caused by your webcam not initializing correctly. Do you have any errors in `dmesg`?

**Comment by K900** [comment]
Something to try would be `services.pipewire.package = pkgs.pipewire.override { libcameraSupport = false; };`.

**Comment by jankaifer** [comment]
Yeah, sometimes I would get 100% from pipewire after playing steam games.

I checked `dmesg` and `grep wire` is empty.

**Comment by K900** [comment]
It wouldn't be related to wireplumber, it would be related to your camera connecting and disconnecting.

**Comment by jankaifer** [comment]
My camera is disabled by a hardware switch. So it shouldn't be connected and I don't see anything related in `dmesg`.

**Comment by K900** [comment]
It may be another device then.

**Comment by jankaifer** [comment]
This is my `dmesg` maybe you can see something interesting there:
https://gist.github.com/jankaifer/7aae764f1d9c71bf710c512ffa4dba14

I'll try that config change you suggested.

**Comment by K900** [comment]
Those USB device resets definitely aren't normal. Do you have a USB camera or capture card connected?

**Comment by jankaifer** [comment]
I have expansion cards connected. And I believe that camera behaves like a USB device but that hardware switch should disconnect it.

Also with that config change I login works. Let me try multiple times to verify.

**Comment by K900** [comment]
If you have an actual hardware switch that cuts the USB link, make sure it's fully on or fully off - it's possible your camera is connected _enough_ to make your device think there's a device, but not connected enough to actually probe successfully.

**Comment by jankaifer** [comment]
So even with that config change it's flakey. I worked 2 times and failed once.

Oh, I didn't realize that `journalctl` shows logs even from previous boots (I never hard to use it since I switched to NixOS half a year ago). It doesn't show that error now.

**Comment by jankaifer** [comment]
The `dmesg` shows that the camera reconnected exactly once. Even though it's disabled.

I'll try rebooting with camera on or off if I can spot a pattern.

**Comment by jankaifer** [comment]
> 
Those USB device resets definitely aren't normal. Do you have a USB camera or capture card connected?

Which USB device resets do you mean? There are a bunch of USB devices connecting, but that is expected. The devices connected are:
- usd-c expansion card
- usb-c expansion card
- usb-a expansion card
- hdmi expansion card

**Comment by K900** [comment]
These:

[  549.045647] usb 1-9: reset full-speed USB device number 3 using xhci_hcd
[  549.310647] usb 1-9: reset full-speed USB device number 3 using xhci_hcd

**Comment by jankaifer** [comment]
Thanks. I still see exactly 2 resets and I've taken out all expansion cards and disabled the camera and microphone.

I'll reboot a few times again and check for those.

**Comment by jankaifer** [comment]
So I found what causes the flakiness in the gnome login fails. That seems unrelated.
It fails only when I log in too quickly. When I wait a little before logging in it works fine.

After testing with and without a camera I get 2-5 USB device resets.

**Comment by jankaifer** [comment]
I installed the same config into my other framework (same computer but with i7 instead of i5).

I still get USB resets, so either the hardware switch design is wonky, or this is not a hardware issue.

**Comment by jankaifer** [comment]
I just looked into which device is resetting, and it's my fingerprint sensor Goodix.
```
[    1.952382] usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.952383] usb 1-9: Product: Goodix USB2.0 MISC
[    1.952384] usb 1-9: Manufacturer: Goodix Technology Co., Ltd.
[    1.952384] usb 1-9: SerialNumber: UIDF9285E55_XXXX_MOC_B0
...
[   14.047056] usb 1-9: reset full-speed USB device number 2 using xhci_hcd
[   15.749491] usb 1-9: reset full-speed USB device number 2 using xhci_hcd
```

**Comment by K900** [comment]
OK, I guess we can disregard that then. Can you check if /dev/media0 exists consistently? If it does, you can find out which device it is with `udevadm info /dev/media0`.

**Comment by jankaifer** [comment]
Anyway, I don't see the original error in `journalctl` anymore and my login issues seem to be unrelated to wireplumber.

And that USB reset is not great, but it shouldn't cause any issues (I'm using my fingerprint sensor to login after all).

**Comment by jankaifer** [comment]
`/dev/media0` doesn't exist.

**Comment by jankaifer** [comment]
The only issue I have now is that blanch scree after but that is unrelated, so I'll close this now.

Thanks a lot for your help.
