### ISSUE TITLE
`qemu-vm.nix` does not escape disk image path

### ISSUE THREAD

**Issue by pitkling** [NixOS/nixpkgs#229729]
### Describe the bug
The `startVM` script defined in [nixos/modules/virtualisation/qemu-vm.nix](https://github.com/NixOS/nixpkgs/blob/aad25290ee4655200f63206c2a507611a8e6338d/nixos/modules/virtualisation/qemu-vm.nix) contains a [part that creates a disk image](https://github.com/NixOS/nixpkgs/blob/aad25290ee4655200f63206c2a507611a8e6338d/nixos/modules/virtualisation/qemu-vm.nix#L117-L135) if it does not yet exist. The file name of the disk image is stored in the bash variable `NIX_DISK_IMAGE` which is [written unquoted into the bash script](https://github.com/NixOS/nixpkgs/blob/aad25290ee4655200f63206c2a507611a8e6338d/nixos/modules/virtualisation/qemu-vm.nix#L133) when creating the disk image. Thus, if `$NIX_DISK_IMAGE` contains a space, the disk image creation fails.

### Steps To Reproduce
The following is an easy way to reproduce the problem under macOS with a recent nixpkgs; not sure about a Linux example, but anything that triggers a VM creation via `qemu-vm.nix` in the current directory should do the trick.
1. Create and enter a folder with a space in its name: `mkdir ~/"foo bar" && cd ~/"foo bar"`
2. Start a VM via nix, e.g., `nix run nixpkgs#darwin.builder` (a recent builder VM for macOS).
3. (will ask for sudo password for key setup)
4. Disk image creation is triggered and fails with the following output:
    ```console
    Disk image do not exist, creating the virtualisation disk image...
    qemu-img: Invalid image size specified. You may use k, M, G, T, P or E suffixes for
    qemu-img: kilobytes, megabytes, gigabytes, terabytes, petabytes and exabytes.
    ```

### Expected behavior
The builder disk image for the VM should be created and the VM should be started. (Also seems like there is a minor typo in the error message: "Disk image ~~do~~ **does** not exist, …".)

### Notify maintainers
@RaitoBezarius 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.0`
 - channels(peter): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by RaitoBezarius** [comment]
Good point, can you send a PR?
