### ISSUE TITLE
Update request: python3Packages textual 0.15.1 -> 0.23.0

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#229701]
- Package name: textual
- Latest released version: 0.23.0

- Current version on the unstable channel: 0.15.1
- Current version on the stable/release channel:

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by schuelermine** [comment]
Does #229761 resolve this?

**Comment by armijnhemel** [comment]
> Does #229761 resolve this?

As far as I can tell: yes. Would be great to have it merged into master (so it shows up in nixpkgs-unstable at some point).

**Comment by armijnhemel** [comment]
And of course there have been two new releases in the meantime....

**Comment by armijnhemel** [comment]
Was fixed, closing.
