### ISSUE TITLE
Build failure: xwayland 23.1.1

### ISSUE THREAD

**Issue by MarceloEmmerich** [NixOS/nixpkgs#229841]
### Steps To Reproduce

1. ```sudo nixos-rebuild switch --flake .#<flake>```

### Build log 1
building the system configuration...
error: builder for '/nix/store/brbycd2bzk7xylvrmhba1aw2mf576szw-xwayland-23.1.1.drv' failed with exit code 1;
       last 10 log lines:
       > Hunk #8 succeeded at 1062 with fuzz 2 (offset 245 lines).
       > patching file hw/xwayland/xwayland-screen.h
       > Hunk #1 succeeded at 87 (offset 15 lines).
       > Hunk #2 succeeded at 136 (offset 27 lines).
       > Hunk #3 FAILED at 137.
       > 1 out of 3 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-screen.h.rej
       > patching file hw/xwayland/xwayland-window.c
       > Hunk #1 FAILED at 470.
       > Hunk #2 succeeded at 1322 (offset 502 lines).
       > 1 out of 2 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-window.c.rej
       For full logs, run 'nix log /nix/store/brbycd2bzk7xylvrmhba1aw2mf576szw-xwayland-23.1.1.drv'.
error: 1 dependencies of derivation '/nix/store/rnwzv38hiahq23lxvksdil3j6fkk7hlj-wlroots-0.15.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0bwfv1fsvvb0ih9c0ajprvb6krcki6ad-sway-unwrapped-1.8.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z2fshdq3wbxhy4i3iq0fg9pi6kvydzfd-sway-1.8.1.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-regreet-unstable-2023-02-27.drv-4': Directory not empty
error: 1 dependencies of derivation '/nix/store/bcfahmnqs1mfibvxpn55dsb9fvx3v46w-activation-script.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rpzd0islw2686wsc0l18j7h1h2xwwpyb-greetd.toml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ap5gx5pr0g6ihbmikxvylq5yjyf3c2xn-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nzxla1fs2896cjsfbikclzy7ckj2fvng-unit-greetd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r7af6xsbf3fjf6kgxqx61irf1781355r-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4dsn42dh9amv29c6l2i5ry5dqhh1ggnm-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8g6i0j2ymprcbm6fclcqsmkrq1chz5pq-nixos-system-io-23.05.20230502.1a411f2.drv' failed to build

### Build log 2 (from above)
nix log /nix/store/brbycd2bzk7xylvrmhba1aw2mf576szw-xwayland-23.1.1.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/lh0n18fvgwgvjvrh1sngxkn1vy51jnwq-xwayland-23.1.1.tar.xz
source root is xwayland-23.1.1
setting SOURCE_DATE_EPOCH to timestamp 1680092796 of file xwayland-23.1.1/xserver.ent.in
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/jyrpl7sgghsilafm2s6zw698a3cg6p1z-xwayland-vsync.patch
patching file hw/xwayland/xwayland-present.c
Hunk #1 succeeded at 889 (offset 65 lines).
applying patch /nix/store/xy8xhxsi59csgq8yj5rvydahd8qdy3lk-xwayland-hidpi.patch
patching file hw/xwayland/xwayland-cursor.c
Hunk #1 succeeded at 164 (offset -7 lines).
Hunk #2 succeeded at 197 (offset 5 lines).
Hunk #3 succeeded at 228 (offset 5 lines).
Hunk #4 succeeded at 238 (offset 5 lines).
Hunk #5 succeeded at 267 (offset 5 lines).
patching file hw/xwayland/xwayland-input.c
Hunk #1 succeeded at 507 (offset 95 lines).
Hunk #2 succeeded at 731 (offset 139 lines).
Hunk #3 FAILED at 673.
Hunk #4 succeeded at 888 (offset 147 lines).
Hunk #5 succeeded at 1384 (offset 325 lines).
Hunk #6 succeeded at 1421 (offset 325 lines).
Hunk #7 succeeded at 2112 (offset 384 lines).
Hunk #8 succeeded at 3154 (offset 438 lines).
Hunk #9 succeeded at 3166 (offset 438 lines).
Hunk #10 succeeded at 3175 (offset 438 lines).
1 out of 10 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-input.c.rej
patching file hw/xwayland/xwayland-output.c
Hunk #1 succeeded at 189 with fuzz 2 (offset -2 lines).
Hunk #2 succeeded at 600 with fuzz 1 (offset 100 lines).
Hunk #3 FAILED at 527.
Hunk #4 succeeded at 690 (offset 119 lines).
Hunk #5 succeeded at 750 (offset 136 lines).
Hunk #6 FAILED at 682.
2 out of 6 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-output.c.rej
patching file hw/xwayland/xwayland-output.h
Hunk #2 succeeded at 102 (offset 2 lines).
patching file hw/xwayland/xwayland-present.c
Hunk #1 succeeded at 764 with fuzz 2 (offset 84 lines).
patching file hw/xwayland/xwayland-screen.c
Hunk #2 succeeded at 112 (offset 1 line).
Hunk #3 succeeded at 144 with fuzz 1 (offset 10 lines).
Hunk #4 succeeded at 182 with fuzz 1 (offset 10 lines).
Hunk #5 succeeded at 681 (offset 117 lines).
Hunk #6 succeeded at 757 with fuzz 1 (offset 170 lines).
Hunk #7 succeeded at 819 (offset 173 lines).
Hunk #8 succeeded at 1062 with fuzz 2 (offset 245 lines).
patching file hw/xwayland/xwayland-screen.h
Hunk #1 succeeded at 87 (offset 15 lines).
Hunk #2 succeeded at 136 (offset 27 lines).
Hunk #3 FAILED at 137.
1 out of 3 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-screen.h.rej
patching file hw/xwayland/xwayland-window.c
Hunk #1 FAILED at 470.
Hunk #2 succeeded at 1322 (offset 502 lines).
1 out of 2 hunks FAILED -- saving rejects to file hw/xwayland/xwayland-window.c.rej

```
log here if short otherwise a link to a gist
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
› nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9, NixOS, 23.05 (Stoat), 23.05.20230403.53dad94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(marcelo): `""`
 - nixpkgs: `/nix/store/5i6bi3yx11vjkm63vmkms3gs22nvi78r-source`output here
```

**Comment by Artturin** [comment]
it's a issue on your end as those are patches that you're applying to xwayland
