### ISSUE TITLE
`jellyfin-web` 10.8.10 is unable to be used on Chrome versions lower than 80

### ISSUE THREAD

**Issue by willox** [NixOS/nixpkgs#229899]
### Describe the bug
`jellyfin-web`'s `main.jellyfin.bundle.js` file seems to be built in a way that uses more recent JavaScript features than Jellyfin's official packages.
This results in a Jellyfin client that is unable to be used on old Chrome versions (79.0.3945.130) which have no problem with the builds provided on Jellyfin's website.

Specifically, the file is using JavaScript's "optional chaining operator" (`?.`). This was not supported in Chrome/Chromium before version 80.

Supporting Chrome versions this old is necessary for TVs that are able to install Jellyfin's official app (such as the LG OLED48C14LB).

### Steps To Reproduce
1. `nix-build https://github.com/NixOS/nixpkgs/archive/353a67c4d0f4e7d0edc6c7894745b159d9a04621.tar.gz -A jellyfin-web`
2. Witness that `./result/share/jellyfin-web/main.jellyfin.bundle.js` contains usage of JavaScript's the optional chaning operator at line 2, column 1185029: 
![image](https://user-images.githubusercontent.com/1499676/236207891-24fab061-eeb7-4f19-8fd2-0a316c17378b.png)
3. Optionally you can grab Chrome 79 and load this build of jellyfin-web inside it. It'll fail on a syntax error and be stuck on an image of the Jellyfin logo.

### Expected behavior
I think the packed Javascript should be closer to Jellyfin's official packages. The following archives contain `main.jellyfin.bundle.js` files that do not contain this syntax:
https://fra1.mirror.jellyfin.org/releases/server/ubuntu/versions/stable/web/10.8.10/jellyfin-web_10.8.10-1_all.deb
https://fra1.mirror.jellyfin.org/releases/server/portable/versions/stable/web/10.8.10/jellyfin-web_10.8.10_portable.tar.gz
Local builds of Jellyfin I performed in Windows are also "correct" in this way.

I don't really know how npm, typescript, webpack, etc. work but it seems to me that Jellyfin's builds avoid emitting production code that uses this modern syntax and that somehow the approach in nixpkgs is breaking that.

### Additional context
I originally reported this on jellyfin-web before realising it was unique to the package in nixpkgs. https://github.com/jellyfin/jellyfin-web/issues/4567

This isn't a problem with the previous version of Jellyfin (10.8.9 on 575f56d82cdb3773b72a5f8e09ad8472cf4a3ddc). There's a chance it's a Jellyfin bug and not a nixpkgs bug but idk.

### Notify maintainers
@nyanloutre @minijackson @purcell @jojosch

**Comment by purcell** [comment]
Since this was filed, the NodeJS version got bumped in #230474, removing some special-casing for Jellyfin. There's a chance that might have fixed this issue, will take a look once the builds are cached.

**Comment by purcell** [comment]
I just built locally and this operator no longer seems to be used in that minified bundle, so I think this issue can be closed: I'll leave it to @willox to confirm though. Thanks for the report!

**Comment by etu** [comment]
Heya, I've had the same problem but with my LG TV (this issue was mentioned from the jellyfin-webos issue pinged here). I just tried to update to latest unstable nixos and it works on my TV so I expect that this issue is now resolved :slightly_smiling_face:

**Comment by purcell** [comment]
Thanks @etu (and @willox)!
