### ISSUE TITLE
nvidia-x11: nvidia-settings can't find libXv.so.1 and dbus error

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#22983]
## Issue description
As of 442b4d65c3, opening nvidia-settings in a terminal shows 

"** (nvidia-settings:2901): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

ERROR: libXv setup error : libXv.so.1: cannot open shared object file: No such file or directory"

Note that nvidia-settings does still run

### Steps to reproduce
Update to nixpkgs master and rebuild, run nvidia-settings in terminal instance

## Technical details

* System: 17.03.git.833523d (Gorilla)
* Nix version: 1.11.6
* Nixpkgs version: git master 833523d958

**Comment by abbradar** [comment]
Argh, they use dlopen for some reason! Fixed in https://github.com/NixOS/nixpkgs/commit/362ef377c8e5314902c313fbc1d40efabd0c9406.

BTW, could you help in testing https://github.com/NixOS/nixpkgs/pull/22666?

**Comment by MP2E** [comment]
No problem! I'll check it out
