### ISSUE TITLE
How to actually use pkgs.irssi_otr?

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#22986]
So, `pkgs.irssi_otr` doesn't actually seem to install its module in any location readable by irssi.

**Comment by peterhoeg** [comment]
Correct, it looks like we need something to wrap both irssi and the otr module to make things work.

**Comment by cpages** [comment]
The hack I'm using it to symlink .irssi/modules -> ~/.nix-profile/lib/irssi/modules. Would be nice to wrap it properly though, yes.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by stigok** [comment]
As far as I can see, OTR support is included in the normal irssi build:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/irc/irssi/default.nix#L19
