### ISSUE TITLE
Neovim Node Host Plugins

### ISSUE THREAD

**Issue by garrett-hopper** [NixOS/nixpkgs#22997]
I'm attempting to package [node-host](https://github.com/neovim/node-host) on nixos, however I can't seem to figure out npm2nix or node2nix to make it work.

I'm also not sure how NeoVim host plugins work exactly, and if they can be used in a nix way.

My main goal is to get [nvim-parinfer.js](https://github.com/clojure-vim/nvim-parinfer.js) installed in a declarative way in my nixos configuration.

**Comment by Ekleog** [comment]
@Jumblemuddle I think you would have more luck in IRC #nixos or on the Discourse (which was a mailing list at the time), the issue tracker is not really well-suited for support requests… hence the long silence, I think :)

**Comment by teto** [comment]
the project is archived and neovim can set `g:node_host_prog` without any issue so far so maybe we can close ?
