### ISSUE TITLE
zstd is pulling gcc as a runtime dependency causing curl package to be bigger than needed

### ISSUE THREAD

**Issue by clushie** [NixOS/nixpkgs#229921]
### Describe the bug
When building a docker image that contains the `curl` package I've noticed that `gcc` ends up in my `/nix/store` of the image.

When I switch to `curlMinimal` it resolves the problem, difference is that `zstd` isn't part. 

### Steps To Reproduce
1. build a docker image with just zstd 
3. look into the image with `dive`
4. `nix run nixpkgs#dive -- nixery.dev/zstd`
5. or also just look at `nix run nixpkgs#nix-tree -- /nix/store/w10in9diaqrcqqxi5lg20n3q2jfpk6pq-zstd-1.5.2`

### Screenshot
Comparing (from left to right)

* `docker run -it --rm nixery.dev/curl/ncdu ncdu /nix/store`
* `docker run -it --rm nixery.dev/zstd/ncdu ncdu /nix/store`
* `docker run -it --rm nixery.dev/curlminimal/ncdu ncdu /nix/store`

![image](https://user-images.githubusercontent.com/47661139/236256072-f3019b0c-17d1-435a-a140-69e4e60b0b1b.png)

### Expected behavior
I think no gcc would make sense, unless I overlook something

### Notify maintainers
@orivej @orivej-nixos

**Comment by kirillrdy** [comment]
greetings ! 

using latest master 416ffcd08f1f16211130cd9571f74322e98ecef6

nix-build -A curl
nix-tree ./result-bin/

shows that closure size is 53Mb, and no gcc

can you test against same commit ? maybe its fixed, or maybe something else pulls in gcc

**Comment by Artturin** [comment]
@kirillrdy only the `out` output depends on libgcc

@clushie 
full gcc isn't being depended on but only the lib output because the pzstd binary depends on libgcc `libgcc_s.so.1 => /nix/store/vaxgqbm6h3zvhpgk9xqqk97hqjp9gzvs-gcc-12.2.0-lib/lib/libgcc_s.so.1`

**Comment by kirillrdy** [comment]
@Artturin I see, thank you for clarification. Not sure why nix-build -A curl doesn't create ./result symlink to out

but I have verified using

```
nix repl 
Welcome to Nix 2.13.3. Type :? for help.

nix-repl> :l
Added 18958 variables.

nix-repl> :b curl

This derivation produced the following outputs:
  bin -> /nix/store/ql5sal36vkji1z9hq45lcs1pjv6vby5k-curl-8.0.1-bin
  debug -> /nix/store/r8n43f6wsmivd6b2x8j01bf6xk5p8f00-curl-8.0.1-debug
  dev -> /nix/store/msknlmzdydid6ya8r7qbbq12x5kxg79g-curl-8.0.1-dev
  devdoc -> /nix/store/7fq7p9mfm55m7xklr42r0i4jrg6kw92z-curl-8.0.1-devdoc
  man -> /nix/store/46c1zbn3qjsy3lkpdb610b08fddd8ir3-curl-8.0.1-man
  out -> /nix/store/yklzq364x0m0jw9bqaqvbdm11z8x6ndz-curl-8.0.1

nix-repl> 

[nix-shell:~/nixpkgs]$ nix-tree /nix/store/yklzq364x0m0jw9bqaqvbdm11z8x6ndz-curl-8.0.1
```

there is gcc, but only lib, and closure size still 53Mb

**Comment by Artturin** [comment]
the default outputsToInstall is bin and man

you have to do `curl.all` with the old cli or `curl^*` with the new cli

**Comment by clushie** [comment]
Thanks everyone for looking into this, I learned a lot by your responses and sorry for not realizing it's "just libgcc".
