### ISSUE TITLE
GNOME 44 problems with Qt-applications

### ISSUE THREAD

**Issue by MrTarantoga** [NixOS/nixpkgs#230097]
### Describe the bug
Since the Gnome 44 (under wayland) update, on multiple devices reproducible errors with Qt based applications.

### Steps To Reproduce
- nextcloud-client: The application does not show itself after first start, it is only visible in Activities as an empty frame. You have to restart the application and it works.
- keepassxc: The Drag-and-Drop functionality does not work.

This are only two errors that I found, but I think many Qt-applications are affected. The solution is to set `QT_QPA_PLATFORM=wayland` inside a shell and start the application. The errors vanish. Currently, my workaround is setting it global with
```
  environment.variables = {
    QT_QPA_PLATFORM = "wayland";
  };
```

Perhaps, can you add the variable as a default setting for each gnome under wayland session? 
Thank you

### Notify maintainers
@bobby285271
@hedning
@jtojnar
@dasj19
@maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/pgf87rgkzdbqhhsddpligy8xiwar63w8-stdenv-linux
copying path '/nix/store/pgf87rgkzdbqhhsddpligy8xiwar63w8-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05pre480050.1a411f23ba2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(goetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Could you please try if https://github.com/NixOS/nixpkgs/pull/210077 fixes it?

**Comment by MrTarantoga** [comment]
Does not solve the problem.

**Comment by KCynk** [comment]
Same issue with wireshark
QT_STYLE_OVERRIDE 
https://github.com/NixOS/nixpkgs/issues/227512#issuecomment-1534686509

**Comment by dasj19** [comment]
strawberry player is also affected. Outputs:
`10:08:56.258 DEBUG unknown                          Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. `

When running: `QT_QPA_PLATFORM=wayland strawberry` drag and drop works, without that env variable drag and drop does not work.

**Comment by Sciencentistguy** [comment]
I am also experiencing this issue, under x11. `picard`'s drag and drop does not work, which render the program almost unusable.

**Comment by bobby285271** [comment]
#237042 has possible fix for https://gitlab.gnome.org/GNOME/mutter/-/issues/2715

**Comment by timlinux** [comment]
Will this get backported to stable?

**Comment by jtojnar** [comment]
Already happened https://github.com/NixOS/nixpkgs/pull/237226
