### ISSUE TITLE
Package request: Memento

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#230021]
**Project description**

An mpv-based video player for studying Japanese 

Might actually tackle this but it's low on my list

**Metadata**

* homepage URL: https://github.com/ripose-jp/Memento
* source URL: https://github.com/ripose-jp/Memento
* license:  gpl2 
* platforms: unix, linux, darwiin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/199453

**Comment by teto** [comment]
indeed.
