### ISSUE TITLE
Can't run webpack

### ISSUE THREAD

**Issue by kephas** [NixOS/nixpkgs#230090]
### Describe the bug
Despite `webpack` and `webpack-cli` being available, the `webpack` command won't run, saying `webpack-cli` needs to be installed. (and installation fails)

### Steps To Reproduce
1. `nix-shell -p nodePackages.npm nodePackages.webpack --command webpack`
2. answer "yes" or "no

Also fails the same way:
`nix-shell -p nodePackages.npm nodePackages.webpack nodePackages.webpack-cli --command webpack`

### Expected behavior
`webpack` should run and do the build.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-7-amd64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(pierre): `"nixgl, nixos, nixos-21.05-21.05, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/pierre/.nix-defexpr/channels/nixpkgs`
```

**Comment by Nate-Wilkins** [comment]
This seems to work for me.

```
nix-shell -p nodePackages.npm nodePackages.webpack-cli --command webpack-cli
```

**Comment by pyrox0** [comment]
Please try using the new `webpack-cli` package in nixpkgs, and open a new issue if there are problems!
