### ISSUE TITLE
Package request: Deskreen

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#230001]
**Project description**

Deskreen turns any device with a web browser into a secondary screen for your computer 

**Metadata**

* homepage URL: https://deskreen.com/
* source URL: https://github.com/pavlobu/deskreen
* license: agpl3.0
* platforms: linux

**Comment by hugosenari** [comment]
Related #282044

**Comment by Zahrun** [comment]
Nice. I have been using weylus as an alternative. Let’s see how deskreen compares
