### ISSUE TITLE
simp_le build fails because of acme dependency

### ISSUE THREAD

**Issue by Nadrieril** [NixOS/nixpkgs#23008]
## Issue description
Commit https://github.com/NixOS/nixpkgs/commit/72cda1667b03ac4db3d371719207fb2663ccc75b bumps `pkgs.certbot` version to `0.11.1`, which breaks the build of `simp_le` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/simp_le/default.nix) which requires `acme<0.10,>=0.9`.

### Steps to reproduce
Try to build `pkgs.simp_le`.

## Technical details
* Nixpkgs version: 17.03.git.beb5a8af2e

**Comment by globin** [comment]
Fixed in 464529c603

**Comment by Nadrieril** [comment]
Did you just prevent simp_le from checking it's dependency's version ? Won't that risk breaking in the future ?

**Comment by globin** [comment]
Generally yes, but added running the tests and the plan is to get rid of simp_le for our acme module and use certbot so this shouldn't be used that much anyway much longer..
