### ISSUE TITLE
Not specifying ACME e-mail address produces vague error

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#230161]
### Describe the bug
If not specifying an e-mail address for ACME (through `security.acme.defaults.email` or otherwise), a vague error is produced:

```
error: cannot coerce null to a string

       at /nix/store/ihc3w1d56y04f5n5aszzmcw4vfd68sx0-nh117is9llirai9ynibnxvq23nmdvp4d-source/nixos/modules/security/acme/default.nix:381:166:

          380|         # We also need an account key. Avoids #190493
          381|         if cmp -s domainhash.txt certificates/domainhash.txt && [ -e 'certificates/${keyName}.key' -a -e 'certificates/${keyName}.crt' -a -n "$(find accounts -name '${data.email}.key')" ]; then
             |                                                                                                                                                                      ^
          382|
(use '--show-trace' to show detailed location information)
```

### Steps To Reproduce
1. Enable `security.acme.acceptTerms` but do *not* specify an e-mail address
2. Enable `enableACME` within an nginx virtual host
3. Evaluate

### Expected behavior
A clear error should be produced, explaining that an e-mail address is required; for example suggesting setting `security.acme.defaults.email` (like the documentation does).

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@m1cr0man 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.106, NixOS, 22.11 (Raccoon), 22.11.4037.cc45a3f8c98`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(sven): `""`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(Note that `morph` is being used, pointed at the latest `22.11` channel)

**Comment by m1cr0man** [comment]
Hm, this is [supposed to be asserted upon](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme/default.nix#L793-L800) and present a nice error. There must be an evaluation order problem here.

We're probably only seeing this now due to [this change](https://github.com/NixOS/nixpkgs/pull/227232/files#diff-f72bfee4e4288266759893ea9ae9b14380c9169157e61dae1a35132757b387e0L490).

**Comment by rjpcasalino** [comment]
Just ran into this. Would have been nice to avoid having google and find myself here but nevertheless, thanks @joepie91

**Comment by totoroot** [comment]
Ran into this just yesterday as well. This needs to be better documented in the ACME module or the error needs to be more descriptive.
