### ISSUE TITLE
Package request: cameractrls

### ISSUE THREAD

**Issue by leoluk** [NixOS/nixpkgs#230167]
**Project description**

cameractrls is a UI for v4l camera settings, like pan/tilt/... on fancy Logitech cameras.

**Metadata**

* homepage URL: https://github.com/soyersoyer/cameractrls
* source URL: https://github.com/soyersoyer/cameractrls
* license: MIT
* platforms: Linux

**Comment by swt30** [comment]
I'm using this successfully with the latest version,
```
version = "v0.6.6";
sha256 = "sha256-QjjLd5L+8Slxc3ywurhsWp1pZ2E1Y7NOdnCV2ZYBlqU=";
```

**Comment by mobergmann** [comment]
Is there any progress with this request?

**Comment by Aleksanaa** [comment]
@leoluk @mobergmann Please test my PR https://github.com/NixOS/nixpkgs/pull/329911. I don't have the device.

**Comment by mobergmann** [comment]
Tbh, I would like to, but I don't know how to test a custom package...

**Comment by Aleksanaa** [comment]
> Tbh, I would like to, but I don't know how to test a custom package...

For new CLI: `nix build github:Aleksanaa/nixpkgs/cameractrls#cameractrls-gtk4`
Or `nixpkgs-review pr 329911`

**Comment by mobergmann** [comment]
I executed `nix build github:Aleksanaa/nixpkgs/cameractrls#cameractrls-gtk4` and then nothing happened... I can also not find cameractrls

**Comment by Aleksanaa** [comment]
> I executed `nix build github:Aleksanaa/nixpkgs/cameractrls#cameractrls-gtk4` and then nothing happened... I can also not find cameractrls

Check your current directory, there's a `result` symlink to store, and the executable is in `result/bin`

**Comment by mobergmann** [comment]
I only tested the gui app and it seems to work fine!

**Comment by Aleksanaa** [comment]
> I only tested the gui app and it seems to work fine!

Thanks! What about the others executables? Have you tested all the functionality of the app?

**Comment by mobergmann** [comment]
I can only test the the GUI, because I don't know how to use the CLI program. But the GUI is working fine, afaict.
