### ISSUE TITLE
Build failure: futhark

### ISSUE THREAD

**Issue by DerDennisOP** [NixOS/nixpkgs#230127]
### Steps To Reproduce

1. build *futhark*

### Build log

```
<no location info>: error:
    <command line>: /nix/store/js0wf10x2hadd3fnd9i6j8l56wdn634v-language-c-quote-0.13.0.1/lib/ghc-9.2.7/x86_64-linux-ghc-9.2.7/libHSlanguage-c-quote-0.13.0.1-KfWcD4Bd2sC5r3CSAb4Aab-ghc9.2.7.so: invalid ELF header
```

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05.20230504.0d8145a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(dennis): `"nixpkgs"`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/home/dennis/.nix-defexpr/channels/nixpkgs`

**Comment by mweinelt** [comment]
Not sure why this should have blocking severity.

The package has no maintainer and only gets bumped by our haskell team.

**Comment by bitmappergit** [comment]
This seems to be a Template Haskell issue in language-c-quote anyway, but I'm not sure.

**Comment by athas** [comment]
It's a very mysterious error.  `/nix/store/js0wf10x2hadd3fnd9i6j8l56wdn634v-language-c-quote-0.13.0.1/lib/ghc-9.2.7/x86_64-linux-ghc-9.2.7/libHSlanguage-c-quote-0.13.0.1-KfWcD4Bd2sC5r3CSAb4Aab-ghc9.2.7.so` looks like a corrupted file - it starts with 640KiB of zeroes.  Could be a GHC bug.

**Comment by athas** [comment]
This builds fine now.  If the issue was indeed a corrupted cache, then it was fixed when the hashes changed.
