### ISSUE TITLE
Package request: ocis

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#230190]
"ownCloud Infinite Scale Stack" or owncloud rewritten in Go.

**Metadata**

* homepage URL: https://github.com/owncloud/ocis
* source URL: https://github.com/owncloud/ocis
* license: asl20
* platforms: unix

**Comment by squalus** [comment]
There are some hassles to deal with on this one.
- PNPM usage: https://github.com/NixOS/nixpkgs/issues/231513
- Image assets downloaded with curl (and no hashes or revisions)
- Code generation tools and code repositories downloaded by `bingo` https://github.com/bwplotka/bingo

**Comment by danth** [comment]
Note that ownCloud provide prebuilt binaries for oCIS. It's fairly simple to get these working on NixOS:

```nix
stdenv.mkDerivation {
  pname = "ocis";
  version = "5.0.0-rc.1";

  src = fetchurl {
    url = "https://github.com/owncloud/ocis/releases/download/v5.0.0-rc.1/ocis-5.0.0-rc.1-linux-amd64";
    sha256 = "8dcf8544b050638483812a0937498156300a1e711f2cdf23bf779a6f855b7d94";
  };
  dontUnpack = true;

  nativeBuildInputs = [ autoPatchelfHook ];

  installPhase = ''
    runHook preInstall
    install -D $src $out/bin/ocis
    runHook postInstall
  '';
}
```

Perhaps this can be used as a temporary solution until we can build it ourselves?

**Comment by danth** [comment]
I've been using the rc for a while and haven't had any major issues. It's probably better to go with the stable release by default though. Perhaps we could package both?

**Comment by poperigby** [comment]
Has the situation changed where the OCIS can be built from source now? I'd rather not use a proprietary binary.
