### ISSUE TITLE
"This version of Nixpkgs requires Nix >= 1.10" messages points to outdated wiki page

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#23013]
When someone tries to run nixos-rebuild with a too-old version of nix, they'll see this error message:
```This version of Nixpkgs requires Nix >= 1.10, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_Nixpkgs```

However, the [instructions at that wiki page](https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_Nixpkgs) are out of date (e.g. the URL in the example ```curl``` command gives a 404), and the wiki's being shut down in any case.

See for example [this nix-dev thread](http://lists.science.uu.nl/pipermail/nix-dev/2017-February/022848.html).

**Comment by dezgeg** [comment]
Fixed in 2e91b2d585afdb3b076b3ad655579774f100bad5.
