### ISSUE TITLE
gnome.gnome-session: outputs documentation with unreproducible ids

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#230281]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A gnome.gnome-session --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A gnome.gnome-session)
```

### Additional context

It seems it uses unstable identifiers in the documentation output (https://reproducible.nixos.org/nixos-iso-gnome-runtime/diff/7e066b3e0a9e41d38e5dda32f2bef66c64059667317775343b19bc383f64b920-944aae10257b53d61eed0269a72038e1d57ec3d9c5a5a1e5ca0694d3e6b4cb5e.html). This can often be fixed by passing the 'generate.consistent.ids' flag to docbook (see e.g. https://marc.info/?l=bind-workers&m=144228535428181).

Also, shouldn't the docs be in a separate `doc` output?

**Comment by raboof** [comment]
(this is not showing up in the latest report, may have been fixed or not reproducibly unreproducible)

**Comment by oliviacrain** [comment]
The upgrade to [`libxslt 1.1.38`](https://github.com/NixOS/nixpkgs/commit/f4dc0763b8b4010efac145d06aa1b4c8138f9c47) probably fixed this. In the [release notes](https://gitlab.gnome.org/GNOME/libxslt/-/blob/d679f4470df2c79443ff54dbc6bd95afaf4cd876/NEWS#L47-48), it mentions that the `generate-id` function (used by docbook to generate these ids) has been made deterministic.

**Comment by raboof** [comment]
Very nice!
