### ISSUE TITLE
Logseq full-text search not working

### ISSUE THREAD

**Issue by austinbutler** [NixOS/nixpkgs#230212]
### Describe the bug

Search seems to work for page titles but not page text.

### Steps To Reproduce
1. CTRL+K, look for text that's in a page

### Expected behavior

Returns results for pages that have the given text.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05pre478981.08e4dc3a907`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kraftnix** [comment]
The Issue appears to be related to NODE and Electron versions.

If you run Logseq and trigger a re-index of the graph, you will get the following error
```error
Error: The module '/nix/store/.../share/logseq/resources/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using NODE_MODULE_VERSION 107.
This version of Node.js requries NODE_MODULE_VERSION 110.
Please try re-compiling or re-installing the module.
```

Logseq upstream currently uses Electron `20.3.8`, if you override the electron version for Logseq to `electron_20`, it will work, however `electron_20` is marked as EOL in nixpkgs, so you will also need to add an exception for the insecure package.

I tried using all of the non-EOL electron versions (22-24) and they all throw the NODE version error for bettersqlite3 during re-indexing.

So for a current workaround you can apply this overlay and allow the broken electron package. as well as including the fix from #230234
```nix
final: prev: {
  logseq = prev.logseq.overrideAttrs (oldAttrs {
    postFixup = ''
      makeWrapper ${prev.electron_20}/bin/electron $out/bin/${oldAttrs.pname} \
        --set "LOCAL_GIT_DIRECTORY" ${prev.git} \
        --add-flags $out/share/${oldAttrs.pname}/resources/app \
        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
        --prefix LD_LIBRARY_PATH : "${prev.lib.makeLibraryPath [ prev.stdenv.cc.cc.lib ]}"
    '';
  });
}
```
You must re-index to get full text search back once you have Logseq with the above override running.
