### ISSUE TITLE
steam beta client can't find gsettings schemas

### ISSUE THREAD

**Issue by anund** [NixOS/nixpkgs#230246]
### Describe the bug
The steam client (beta) is attempting to access gsettings schemas and fails. 

Exporting `GSETTINGS_SCHEMA_DIR` manually as `"${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}/glib-2.0/schemas/"` fixes the issue.

### Steps To Reproduce
1. opt into the [steam client beta](https://help.steampowered.com/en/faqs/view/276C-85A0-C531-AFA3) (likely don't have gtk3/gsettings-desktop-schema already addressable on the host, not steam-run, `XDG_DATA_DIRS` path)
2. launch steam
3. generate the following error
```
(process:46129): GLib-GIO-ERROR **: 12:27:57.934: No GSettings schemas are installed on the system
<installdir>/Steam/steam.sh: line 798: 46129 Trace/breakpoint trap   (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```

### Additional context
GSetting should be looking for schema files in `XDG_DATA_DIRS`
BuildFHSEnv moves `gsetting-desktop-schema` schemas to `/usr/share/gsettings`
XDG_DATA_DIRS in the fhsenv doesn't include `/usr/share`
`gsettings-desktop-schema` is being pulled into the fhsenv via `libdbusmenu-gtk2`

It's possible just adding `/usr/share` to the _end_ of the `buildFHSEnv` `XDG_DATA_DIRS` environment variable is the fix. I'm unfamiliar with gsettings. Attempting `XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share steam` does not work as `/usr/share` in the fhsenv is missing things `buildFHSEnv` adds in `/run/opengl...`.

### Notify maintainers
@jagajaga

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.110, NixOS, 23.05 (Stoat), 23.05pre481202.3e313808bd2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(<user>): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by McDread** [comment]
Exporting GSETTINGS_SCHEMA_DIR manually did not work for me.

I left beta participation by removing the file: 
~/.local/share/Steam/package/beta

**Comment by cx405** [comment]
+1 affected by this.

This is result of recent update in Steam beta client. It happens when you have multiple Steam users on machine, which all utilize it; steam-beta client is required to use Proton on Windows-only titles.

On one machine, Steam auto-updates its client to newer version. It will start and work fine. But the other users in their $HOME data won't be able to start steam-beta anymore. So "newer steam-beta client, which gets through update, will refuse to start inside old data".

The other possible solution is probably cleaning the home from ~/.steam, ~/.config/steam and ~/.local/steam and then cloning steam data to other users, chown'ing its permissions, logging in and then re-logging as other user, removing original user.

**Comment by lboklin** [comment]
Setting GSETTINGS_SCHEMA_DIR worked once for me, but no longer after a reboot.

**Comment by reedrw** [comment]
> Setting GSETTINGS_SCHEMA_DIR worked once for me, but no longer after a reboot.

Try setting it in the extraProfile attribute in steam.override like this
```nix
{
  programs.steam = with pkgs; {
    enable = true;
    package = steam.override {
      extraProfile = ''
        export GSETTINGS_SCHEMA_DIR="${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}/glib-2.0/schemas/"
      '';
    };
  };
}
```

**Comment by lelgenio** [comment]
I was able to fix this by overriding steam, adding `gsettings-desktop-schemas` and setting `XDG_DATA_DIRS`:

```nix
# configuration.nix
{
# ...
  programs.steam.package = pkgs.steam.override {
    # Default values
    extraLibraries = pkgs: with config.hardware.opengl;
      if pkgs.hostPlatform.is64bit
      then [ package ] ++ extraPackages
      else [ package32 ] ++ extraPackages32;

    extraPkgs = pkgs: with pkgs; [
      gsettings-desktop-schemas
      xdg-user-dirs # Not obligatory, but steam tries to use it
    ];
    extraEnv = {
      XDG_DATA_DIRS = "/usr/share";
    };
  };
  # ...
}

```

**Comment by lelgenio** [comment]
> Try setting it in the extraProfile attribute in steam.override like this
> 
> ```nix
> {
>   programs.steam = with pkgs; {
>     enable = true;
>     package = steam.override {
>       extraProfile = ''
>         export GSETTINGS_SCHEMA_DIR="${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}/glib-2.0/schemas/"
>       '';
>     };
>   };
> }
> ```

This works great! Tested with reboot.

**Comment by lboklin** [comment]
> I was able to fix this by overriding steam, adding `gsettings-desktop-schemas` and setting `XDG_DATA_DIRS`:
> 
> ```nix
> # configuration.nix
> {
> # ...
>   programs.steam.package = pkgs.steam.override {
>     # Default values
>     extraLibraries = pkgs: with config.hardware.opengl;
>       if pkgs.hostPlatform.is64bit
>       then [ package ] ++ extraPackages
>       else [ package32 ] ++ extraPackages32;
> 
>     extraPkgs = pkgs: with pkgs; [
>       gsettings-desktop-schemas
>       xdg-user-dirs # Not obligatory, but steam tries to use it
>     ];
>     extraEnv = {
>       XDG_DATA_DIRS = "/usr/share";
>     };
>   };
>   # ...
> }
> ```

This worked

**Comment by repomansez** [comment]
+1 affected by this. @lelgenio's workaround does fix it.

**Comment by anund** [comment]
https://nixpk.gs/pr-tracker.html?pr=230375
