### ISSUE TITLE
wireplumber: does not generate docs deterministically

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#230288]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A wireplumber.doc --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A wireplumber)
```

### Additional context

It seems `alltitles` in `share/doc/wireplumber/html/searchindex.js` is not ordered deterministically

**Comment by drupol** [comment]
Looks like it has been fixed the 16th of September, here: https://github.com/sphinx-doc/sphinx/pull/11665

I guess we need to wait for the next version of Sphinx before revisiting this issue, the latest version is 7.2.6 released the 14th of September.

**Comment by williamvds** [comment]
fyi, Sphinx 7.3.7 was just released https://github.com/sphinx-doc/sphinx/releases/tag/v7.3.7

**Comment by drupol** [comment]
I tried to update it already without luck. Help on this is greatly appreciated.

**Comment by williamvds** [comment]
@drupol I took a shot at it here https://github.com/NixOS/nixpkgs/pull/305335

Please feel free to amend or reopen as necessary, I'll be unavailable over the next couple of days.

**Comment by goffrie** [comment]
This appears to be fixed now; at least, the `nix-build --check` command succeeds for me.
