### ISSUE TITLE
libphonenumber: not reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#230284]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A libphonenumber --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A libphonenumber)
```

### Additional context

A fix for this problem has been submitted upstream at https://github.com/google/libphonenumber/pull/2921

**Comment by delroth** [comment]
Upstream doesn't seem reactive, I'm just going to vendor that patch for now until they decide to look at it...
