### ISSUE TITLE
Spacenav module does not work in Blender

### ISSUE THREAD

**Issue by TheSirC** [NixOS/nixpkgs#230295]
### Describe the bug
With the spacenavd module active, the 3D mouse is not working.

### Steps To Reproduce
1. Set `hardware.spacenavd.enable = true`
2. Open Blender
3. The 3D Mouse is not working

### Expected behavior
With the module is active, the mouse should be detected and working in Blender

### Additional context
If you start the binary `spacenavd` with `sudo` seems to be enough for Blender to be enough for it to work.

When the blender binary detects the mouse the first line is 
`sh: line 1: lsusb : command not found` weirdly

### Notify maintainers
@Sohalt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.15, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"nix-ld, nixos"`
 - channels(sirc): `""`
 - nixpkgs: `/nix/store/vnymyf1cja5h41zlg9bxg6a9sq5chgs5-nixos-unstable-2023-03-06`
```

**Comment by flosse** [comment]
I also tried `hardware.spacenavd.enable = true` and it does not work, no matter in which application.
Running `sudo spacenavd` solves the problem, but I actually expect the mouse to work the moment i plug it in.

@Sohalt could you help?

**Comment by the-furry-hubofeverything** [comment]
It looks like spacenavd is supposed to run on a system level, instead of a user unit like @Sohalt outlined?

**Comment by Sohalt** [comment]
Ah, sorry. It used to work as a user service, until @gebner removed the patch in https://github.com/NixOS/nixpkgs/commit/3a4f71d5a08c0f350a77d134a1c7d8b7a2960d94

**Comment by Sohalt** [comment]
Iirc it doesn't work out of the box with a root/system systemd service, because of some environment issues. But you could try it. Upstream only provides an initscript.

**Comment by the-furry-hubofeverything** [comment]
> Ah, sorry. It used to work as a user service, until @gebner removed the patch in https://github.com/NixOS/nixpkgs/commit/3a4f71d5a08c0f350a77d134a1c7d8b7a2960d94

I thought you fixed the patch in #118617?

Maybe it needs an update

**Comment by Sohalt** [comment]
Ah sorry. I didn't look closely enough. 🙈
I'll update all the spacenavd related packages.

**Comment by Sohalt** [comment]
Sorry, I didn't get around to finishing this yet. Here's my work in progress: https://github.com/NixOS/nixpkgs/pull/263120

**Comment by deftdawg** [comment]
Trying to get SpaceMouse going for my [Podman Wine SketchUp container build](https://github.com/deftdawg/sketchup-container), need to get the mouse working on my NixOS host first to pass `/var/run/spnav.sock` in as a volume. 

Was about to file an issue about spacenavd needing an update from 0.8 to 1.2, but looks like @Sohalt is working on it, so I'll just hang out here... :beers:
