### ISSUE TITLE
Update request: Discord Linux Stable 0.0.26 → 0.0.27

### ISSUE THREAD

**Issue by repomansez** [NixOS/nixpkgs#230363]
- Package name: Discord
- Latest released version: 0.0.27

- Current version on the unstable channel: 0.0.26
- Current version on the stable/release channel: 0.0.26

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@MP2E 
@r-ryantm 
@tadeokondrak 
@Infinidoge 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Infinidoge** [comment]
Surprised that an auto-update didn't catch this one.
