### ISSUE TITLE
1Password: op-ssh-sign nowhere in PATH

### ISSUE THREAD

**Issue by cbr9** [NixOS/nixpkgs#230357]
Commit signing with 1Password requires op-ssh-sign. Up until now, I found that it was linked in `/run/current-system/sw/share/1password/op-ssh-sign`, which wasn't in PATH either, but at least it wasn't a file directly from the store. However, a recent update has wiped this symlink (the entire folder), and rebuilding doesn't recreate it. I had to include a path to a file in the store directly in my git config, which is not too clean.

All the 1Password binaries are in path except for this one. Isn't it possible to add this to some folder in PATH?

### Steps To Reproduce
1. run `which op-ssh-sign`
2. Not found

### Expected behavior
The program should be found

### Notify maintainers
- @timstott 
- @savannidgerinel 
- @maxeaubrey 
- @SebTM 

### Metadata
```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05pre481202.3e313808bd2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(cabero): `"home-manager, nixpkgs"`
 - channels(root): `"nixos, unstable"`
 - nixpkgs: `/home/cabero/.nix-defexpr/channels/nixpkgs`
```

**Comment by cbr9** [comment]
Nevermind, I am new to nix. I realized I could just link it as "{pkgs._1password-gui}/share/1password/op-ssh-sign"...

**Comment by maxeaubrey** [comment]
Ah, that feature seems to have a bit of a subpar UX right now, I wonder if 1p would be open to fixing that on Nix specifically. See #230767 for a fix, lemme know if that works.
