### ISSUE TITLE
Build failure: jq installCheck failure on aarch64 cross-compile

### ISSUE THREAD

**Issue by angaz** [NixOS/nixpkgs#230389]
https://github.com/NixOS/nixpkgs/blob/2137dec76549db61decde0142c0c37a72f3c2b62/pkgs/development/tools/jq/default.nix#L55 has a `postInstallCheck` which doesn't work when cross compiling because it tries to run the aarch64 binary on the host machine which will obviously not work. I made an override to disable the `doInstallCheck` and it worked just fine.

I don't know what would be the appropriate way to solve this problem properly, so I made the issue to discuss the solution.

**Comment by Artturin** [comment]
installCheckPhase is not run when build can't execute host so there's no issue

`pkgsCross.aarch64-multiplatform.jq` built on `x86_64-linux`
