### ISSUE TITLE
LLVM runtime dependency library is not found when linking application

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#23042]
## Issue description

When developing applications which uses the LLVM API, some LLVM runtime dependency libraries (`libtinfo.so` and `libz.so`) cannot be found at link time.

### Steps to reproduce

The [LLVM tutorial (chapter 3)](http://llvm.org/docs/tutorial/LangImpl03.html) provides a compiler for a _toy_ programming language. The source code is explained there and is available as [toy.cpp](https://github.com/llvm-mirror/llvm/blob/master/examples/Kaleidoscope/Chapter3/toy.cpp). It can be used to demonstrate the issue.

- Save [toy.cpp](https://raw.githubusercontent.com/llvm-mirror/llvm/master/examples/Kaleidoscope/Chapter3/toy.cpp) into a temporary working directory.

- Start a nix-shell that includes LLVM
```
$ nix-shell -p llvmPackages.llvm
```

- Compile it in a terminal with the command:
```
$ clang++ -g -O3 toy.cpp `llvm-config --cxxflags --ldflags --system-libs --libs core` -o toy
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
/nix/store/j9rvd004agvnddh80nr9gw950kjzdj6m-binutils-2.27/bin/ld: cannot find -ltinfo
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
```
cc @lovek323  @raskin @viric 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03pre101267.a9584c9 (Gorilla)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.6`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.03pre101636.183eeb3"`

**Comment by vcunat** [comment]
Well, as a simple fix, we can add those to `propagatedBuildInputs` (ncurses and zlib).

**Comment by vcunat** [comment]
Any better idea?

**Comment by romildo** [comment]
It is already there since commit https://github.com/NixOS/nixpkgs/commit/15af9082ebeb2aece84e426daf7185715cfbb203

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/llvm/3.9/llvm.nix#L46

```
propagatedBuildInputs = [ ncurses zlib ];
```

**Comment by romildo** [comment]
I had `llvmPackages.clang` in `environment.systemPackages` in the system configuration. That somehow does not work. When it is explicitly added to the _nix-shell_, it just works.

```
$ nix-shell -p llvmPackages.{llvm,clang}

$ clang++ -g -O3 toy.cpp `llvm-config --cxxflags --ldflags --system-libs --libs core` -o toy
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
```

I do not understand yet why some hooks are not triggered when a package is put in `environment.systemPackages`, but they are when used in `nix-shell`. Is this behavior explained somewhere?
