### ISSUE TITLE
**Is your feature request related to a problem? Please describe.**

### ISSUE THREAD

**Issue by ninglin9985** [NixOS/nixpkgs#230546]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_最初由 @ninglin9985 在 https://github.com/trustwallet/assets/issues/24937 发布_

**Comment by Arezoomohammadalizadeh** [comment]
Hello and thank you, I am asking you for the address of the support offices, I need you for a face-to-face meeting, consultation and guidance from the support specialist team to investigate the problems of delivering financial resources and my investments in digital currencies and OneFT Weske Token, which will be sent as a hash address. extracted from pools and reservoirs and mines and companies and projects and farms, thank you if you call me and make an appointment in person
A
al
