### ISSUE TITLE
texlive: impure glibc error when building formats

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#230519]
### Describe the bug
Regression caused by #227873: on non-NixOS (in my case, Ubuntu 22.04), building the formats causes the following error
```
sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/0z5kcds7b6qmm373s3b5w9ykvqbgw87i-glibc-2.37-8/lib/libpthread.so.0)
```

### Steps To Reproduce
1. Install nix and nixpkgs on a Ubuntu 22.04
2. Call `texlive.combine` on some custom collection of packages.
3. Alternatively: call `FORCE_SOURCE_DATE=1 TZ= faketime -f '@1980-01-01 00:00:00 x0.001' fmtutil --user --all` (after adjusting `PERL5LIB`, because `fmtutil` is not currently wrapped).

Whereas calling `fmtutil --user --all` seems to work fine, thus it's really the call to `faketime` that messes up things.

### Expected behavior
Formats should build, of course, and there should not be any mention of the impure `/lib`!

### Notify maintainers
@veprbl, also @apfelkuchen6

I don't know how to fix this one!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(pmtvlm): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs````

**Comment by veprbl** [comment]
Yeah, I don't think we can fix this. I suggest a revert and patch properly.

**Comment by xworld21** [comment]
In the meanwhile, I discovered by nix install (via the Debian package) couldn't sandbox properly. After removing the Debian package and installing nixpkgs proper, I could sandbox the build and avoid the issue. So this is in part a bug of the Debian nix package (because it does not sandbox properly).

My suspicions are also on the `system` function in perl, which calls `/bin/sh` (hardcoded!), and my current best guess as to why the impure linker is involved. Maybe the correct solution to compile perl with the correct `/bin/sh`, if that's even possible... ?

In the meanwhile, if non-sandboxed builds must be supported, we should definitely revert before 23.05 branches off.

**Comment by xworld21** [comment]
Quick note: I am fairly convinced now that `/bin/sh` is causing problem because preloading libfaketime causes a glibc conflict.

We should probably patch `$sh`, or `$targetsh`, in the perl Configure script so that perl calls a nix shell. @veprbl if you know the appropriate person to cc for perl stuff, please do, I don't think I can patch perl correctly on my own.

**Comment by veprbl** [comment]
The fact that the system function executes /bin/sh is governed by glibc. I remember this was discussed before, and there were issues with hardcoding `${bash}/bin/sh` in there.

**Comment by xworld21** [comment]
> The fact that the system function executes /bin/sh is governed by glibc. I remember this was discussed before, and there were issues with hardcoding `${bash}/bin/sh` in there.

Presumably a cycling dependency bash -> glibc -> bash, at a minimum.

The lesson: `LD_PRELOAD` is fragile and must be handled with care. Better patch fmtutil locally, like we do for mtxrun, to add faketime in front of the format calls.

(Changing the perl configuration might still be doable, though, regardless of whether it changes the behaviour of `system`. I'll give it a try.)
