### ISSUE TITLE
Booting new installation fails

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#23050]
## Issue description

I got a new SSD for my Thinkpad X220 and installed it from the previous setup (nixos unstable).

It fails booting, it either drops into emergency mode - (I don't know why, but I guess because of https://github.com/NixOS/nixpkgs/issues/20353) - or it hangs during boot with the same message as when it drops into emergency mode:

![img_20170221_172133](https://cloud.githubusercontent.com/assets/427866/23173897/f7850cae-f85a-11e6-8c42-27969540586c.jpg)

I'm at loss right now because I fail to see what went wrong here.

Details which might be important:

* /dev/sda1 is fat32 and should be mounted in /boot
* /dev/sda2 is luks encrypted ext4 and should be mounted in / (decrypting during boot works)
* No other partitions

In generation 3 (which fails into emergency mode), /boot does not get mounted properly. This should be fixed in generation 11, but when booting 11, it results in what you see in the image.

I'd provide more information if needed, of course.

**Comment by ndowens** [comment]
Just a thought, but maybe use a minimal linux iso to chroot into the partition. SOmething like Archlinux, it gives you arch-chroot which will mount /proc and other things to feel as if you are using an installed Linux, in a way. Go in and check /etc/fstab ?

Also I havent tried it, I wonder if you could mount the partition with a nixos usb and chroot into it and edit the configuration file and do a rebuild?

**Comment by fpletz** [comment]
Yes, boot from a NixOS install medium and use `nixos-install --chroot`.

**Comment by matthiasbeyer** [comment]
If I boot into generation 3, I actually can log in. I can then `nixos-rebuild switch` to get to generation 11 and log in there as normal user.

Also, my `configuration.nix` was copied from the old drive and should work as intended, I guess. So... I see no point in booting an arch or something. @fpletz not sure what the `nixos-install --chroot` command gives me in my situation?

**Comment by Mic92** [comment]
@matthiasbeyer did the uuid of your partition change? `ls -la /dev/disk/by-uuid`
These should match with your device attributes in `hardware-configuration.nix`:

```
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A767-904A"; # <-- might have change after disk upgrade
      fsType = "vfat";
    };

```

**Comment by matthiasbeyer** [comment]
I refer to the partitions by `/dev/sda1` and `/dev/sda2`.

**Comment by Mic92** [comment]
Then check which service has failed by using `journalctl -xb` in the rescue console.

**Comment by Mic92** [comment]
To get a bootable systems, you can also opt out partitions as a temporary work around.
 
```
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A767-904A";
      fsType = "vfat";
      options = ["nofail"];
    };
```

**Comment by matthiasbeyer** [comment]
When booting into generation 3 (11 does not boot to a login prompt, as the image above shows), I see the following: A disk cannot be mounted by UUID (this is because generation 3 is _before_ I moved to use `/dev/sda1` and so on).

It also tells me:

```
systemd[743]: emergency.service: Failed at step EXEC spawning /run/current-system/sw/bin/plymouth: No such file or directory
```

(I typed the above by hand from the screen, typos may be there)

I don't know why generation 11 fails...

**Comment by matthiasbeyer** [comment]
Ok, the `nofail` suggestion worked, I was able to boot into generation 12 which worked as expected now.

But, I do not understand why `/boot` couldn't be mounted. I checked the logs and it complained that `/boot` was not empty... but it mounted anyways (which simply fails then).

Can I just delete the files in `/boot` and try to boot?

**Comment by ndowens** [comment]
If you delete boot you will delete the kernel and not be able to boot again at all. With standard Linux you could after you booted and then install the kernel and run mkinitcpio but I am unsure with Nixos

**Comment by matthiasbeyer** [comment]
@ndowens nope, read again: The `/boot` directory is _not_ empty with `/dev/sda1` _not_ mounted! That's why I'm asking: While booting, it tells me that `/boot` is not empty, but mounts `/dev/sda1` anyways on it.

I don't know whether this is the error or not, that's why I'm asking whether deleting the contents would yield anything. I cannot see why else it would fail to mount it. On the other hand, it shouldn't matter whether there are things in the directory or not... at least this is what the error message tells me.

**Comment by matthiasbeyer** [comment]
Okay this is funny now: as I wrote above, I managed to boot with the `nofail` option suggested by @Mic92 . I then mounted `/dev/sda1` manually to `/boot` and `nixos-rebuild switch`ed. Now, everything just works.

I guess I will close this therefor.

**Comment by Mic92** [comment]
@matthiasbeyer To this point I thought only zfs refuses to mount a partition onto a non-empty directory.
You can do the following (while your actual boot partition is not mounted).

```
$ mv /boot/ /boot-backup
$ mount /dev/sda1 /boot
$ sudo nixos-rebuild switch
```

**Comment by ndowens** [comment]
Yeah I know what ya mean but boot contains the kernel so if you delete and then reboot then even no fail won't work. 

I came from Arch so I know if I wanted to delete everything in boot I could either arch-chroot or boot and delete everything in boot; then use pacman to install kernel then run mkinitcpio

**Comment by Mic92** [comment]
@ndowens `nixos-rebuild` will also repopulate the empty `/boot/` on nixos. `nixos-install` does the same thing. At some point I just removed `/nix/` completely and rebuild my system with `nixos-install`. So there is no need for manually using `chroot`, which I had to use previously on arch to fix missing kernel drivers.

**Comment by ndowens** [comment]
@Mic92 ah didn't know that. Haven't had to do this yet on nix 😀  Just know how on traditional setups
