### ISSUE TITLE
alacritty: `failed to find suitable GL configuration` when using nix on linux mint

### ISSUE THREAD

**Issue by michaelCTS** [NixOS/nixpkgs#230660]
### Describe the bug
When starting `alacritty` on mint, it immediately spits out the error in the title

### Steps To Reproduce
1. install linux mint
2. install nix
3. 
```sh
michael@mint-cts:~$ nix-shell -p alacritty

[nix-shell:~]$ alacritty 
Error: failed to find suitable GL configuration.
Error: "Event loop terminated with code: 1"
```

### Expected behavior

alacritty should open up, no problems

### Screenshots

 ``

### Additional context

`glxgears` (from `apt`) works without a problem, I'm able to play videos and other things that require the GPU.

### Notify maintainers

@Br1ght0ne @mic92 @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
michael@mint-cts:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-71-generic, Linux Mint, 21.1 (Vera), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by OPNA2608** [comment]
Applications from Nixpkgs that use OpenGL / Vulkan are [known-broken on non-NixOS](https://github.com/NixOS/nixpkgs/issues/9415). Have you tried [nixGL](https://github.com/guibou/nixGL)?

> `glxgears` (from `apt`) works without a problem

Have you checked the one from Nixpkgs? Package would be `glxinfo` or `mesa-demos`.

**Comment by michaelCTS** [comment]
> Have you checked the one from Nixpkgs? Package would be `glxinfo` or `mesa-demos`.

Indeed, they don't work either :(

Well, I'll close this in favor of the bug you linked. It would be great if a warning were added directly to the manual. Probably countless hours were wasted by others who ran into the same bug and tried to understand what's going on.

Thanks for the quick response @OPNA2608 ! `nixGL` works!

**Comment by OPNA2608** [comment]
The manual does have a short section saying that OpenGL-using software from Nixpkgs might need some setup on non-NixOS, it just doesn't mention the nixGL shortcut: https://nixos.org/manual/nixpkgs/unstable/#nix-on-gnulinux
