### ISSUE TITLE
Neovim module: Filetype seems detected by filetype.lua but is not applied

### ISSUE THREAD

**Issue by gautaz** [NixOS/nixpkgs#230649]
### Bug description

Hello,

This issue is related to https://github.com/neovim/neovim/issues/23522.
The initial analysis of this neovim issue seems to point a `nixpkgs` specific issue.

Here is the description of the original issue:

> I have the following line in my init.lua: `vim.filetype.add({ extension = { nosj = "json" } })`
> So I am expecting neovim to display all files with a .nosj extension as a JSON file.
>
> Currently it does not (at least on my workstation).
> For instance, opening a file named file.nosj and issuing `:echo &filetype` shows nothing (issuing the same command on a file named `file.json` shows `json`).
> 
> But issuing `:lua print(vim.filetype.match({ filename = 'file.nosj' }))` shows `json nil` which is the same result as `:lua print(vim.filetype.match({ filename = 'file.json' }))` so `filetype.lua` seems to detect the extension as expected.

### Steps To Reproduce

Here is the minimal configuration reproducing the issue (issue.lua):

```lua
vim.filetype.add({ extension = { nosj = "json" } })
```

```console
nvim --clean -u issue.lua
:lua print(vim.filetype.match({ filename = 'file.nosj' })) # shows "json nil"
:e file.nosj
:echo &filetype # shows nothing
:e file.json
:echo &filetype # shows "json"
```

### Expected behavior

```console
nvim --clean -u issue.lua
:e file.nosj
:echo &filetype # shows "json"
```

### Screenshots
N/A

### Additional context

See https://github.com/neovim/neovim/issues/23522.

I am willing to debug the issue provided that:
- I am quite new to Nix
- I need directions on how to obtain a Nix derivation using a local repository of Neovim sources.

### Notify maintainers

Identified maintainers:
@rvolosatovs 
@manveru 

Recent contributors:
@Ma27
@doronbehar
@tssm

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05.20230503.fe591de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by doronbehar** [comment]
I can confirm, with `neovim-unwrapped` tested.

IIRC @teto has some kind of development environment for Neovim? via [`contrib/flake.nix`](https://github.com/neovim/neovim/blob/master/contrib/flake.nix)? Perhaps after cloning `neovim`'s source, cd to the `contrib` directory and run:

```
nix build
./result/bin/nvim --clean -u issue.lua
```

That will build neovim from source. Note however, that the smallest change to the source, will require a full rebuild. You can also run something like this:

```
[contrib] $ nix develop
[contrib] $ mkdir ../build && cd ../build
[build] $ cmake -DCMAKE_INSTALL_PREFIX=$PWD/install-prefix  ../
[build] $ make install
[build] $ $PWD/install-prefix/bin/nvim ...
```

If you want to test a small change to the default `runtime` directory, you can edit it directly after installed, or edit the git tracked files and then run `rm -r $PWD/install-prefix` and run `make install` again.

**Comment by gautaz** [comment]
Hello @doronbehar, thanks for the insight :slightly_smiling_face:.

I didn't realize that there was already a nix flake in the `contrib` directory of neovim repository.
I have started poking around with the `nix develop` environment, seems working well :+1:.

**Comment by gautaz** [comment]
I've just tried to reproduce the issue with the following process:

```console
[contrib] $ nix develop
[contrib] $ cd ../build
[build] $ cmake -DCMAKE_INSTALL_PREFIX=$HOME/nvim  ../
[build] $ make install
[build] $ cd
[home] $ nvim/bin/nvim --clean -u issue.lua
```

I cannot reproduce, this time the `json` filetype is applied to `file.nosj`.

@doronbehar Just to be sure I have understood correctly what you meant by "I can confirm, with `neovim-unwrapped` tested", did you also reproduce the issue?

Is there a difference between the `neovim-unwrapped` derivation and the `nvim` executable built through the `nix develop` environment?

**Comment by teto** [comment]
one thing I've noted on my setup is that `echo $VIMRUNTIME` but since I run a fork of nixpkgs with neovim edits, I am not sure if that's true for your too ?

**Comment by doronbehar** [comment]
> Is there a difference between the `neovim-unwrapped` derivation and the `nvim` executable built through the `nix develop` environment?

I think there are differences in the cmake flags.

> @doronbehar Just to be sure I have understood correctly what you meant by "I can confirm, with `neovim-unwrapped` tested", did you also reproduce the issue?

Aish, actually, with `neovim-unwrapped`, I did not reproduce the issue - I had a typo when I tested the issue initially.

In my case, I have in my `$PATH` a `nvim-unwrapped` executable pointing to the `${neovim-unwrapped}/bin/nvim` executable, and that's the executable I used to test your issue.

Actually, even with _my_ wrapped `nvim` I still can't reproduce the issue. However I do some non trivial setups to via the `customRc` argument, here's a link to my full `neovim` package definition:

https://gitlab.com/doronbehar/nixos-configs/-/blob/41a21c0b2322660ca45c049b5c6a2e1a96a74f1d/overlays/shell-programs.nix#L20-88

If you use NixOS you can also use:

https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=neovim

Or just read the source from Nixpkgs to see what arguments are accepted:

https://github.com/NixOS/nixpkgs/blob/5d2c0216f513b7cd33d1733a21662594df88ea21/pkgs/applications/editors/neovim/wrapper.nix#L13-L35

I think that indeed this is a Nix specific issue but I'm not sure what it is exactly.

**Comment by gautaz** [comment]
Hello, I'd like to thanks both of you for the details :slightly_smiling_face:.
Sorry for lagging, I started having a tooth ache and I am not thinking straight lately.

The environment which is currently reproducing the issue on my side is `neovim` installed through the [home-manager](https://github.com/nix-community/home-manager). My configuration is available [here](https://github.com/gautaz/phoenix/blob/main/homes/del/neovim.nix).
I am also reproducing the issue with a more recent version of vim by using the `home-manager` [programs.neovim.package attribute](https://nix-community.github.io/home-manager/options.html#opt-programs.neovim.package):

```nix
{
    package = pkgs.neovim-unwrapped.overrideAttrs (_: {
      src = pkgs.fetchgit {
        url = "https://github.com/neovim/neovim.git";
        rev = "1cbfed03c249e7f9e67d59566fbabe46f7f7f1f9";
        sha256 = "sha256-vCXNslj3Og24Twtri7vvg2OANj0ok3OxtdUw1WIrw/0=";
      };
    });
}
```

I guess that in both cases, this must be close to the pristine derivation from `nixpkgs`.

@teto I am not sure to understand what you intended to say about `echo $VIMRUNTIME`, would you mind developing a bit?

@doronbehar I haven't tried yet `neovim` installed directly from `nixpkgs`, this will probably be my next step (I tend to prefer installing user packages from `home-manager` as all my workstations were not NixOS based at one time).
I will also poke a bit with the different cmake flags within the `home-manager` derivation to see if one of them can work around the issue.

**Comment by gautaz** [comment]
I am closing this issue as it is not nixpkgs related, see https://github.com/neovim/neovim/issues/23522 for more details.
