### ISSUE TITLE
Can't adjust laptop screen brightness running Gnome

### ISSUE THREAD

**Issue by non-Jedi** [NixOS/nixpkgs#23083]
## Issue description

Attempting to adjust screen brightness with the gnome gui does nothing. Journalctl shows the log filling with:

    Feb 22 20:48:35 nixos gnome-settings-daemon.desktop[1246]: pkexec: cannot run `/nix/store/x7g0glbq3c7kl15w1wif3qncq1016wz4-polkit-0.113/bin/pkexec': No such file or directory

This was not the case 2 weeks ago when I last updated unstable. I can, of course, still change the brightness using xbacklight.

### Steps to reproduce

While running Gnome, press hardware brightness switches or adjust slider in dropdown menu. Screen backlight will not change.

## Technical details

* System: NixOS 17.03pre101636.183eeb3 (Gorilla)
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre101636.183eeb3

**Comment by ryantm** [comment]
looks like something must have been missed when the polkit outputs were split

https://github.com/NixOS/nixpkgs/commit/2490848627b43c8393563b8ee50042cc8356a7f2

@vcunat any idea?

**Comment by ryantm** [comment]
Here's the gnome-settings-daemon configuration file: https://github.com/NixOS/nixpkgs/blob/7077a270bf625b320ab61e3951aa19c9d514b5dc/pkgs/desktops/gnome-3/3.22/core/gnome-settings-daemon/default.nix

**Comment by vcunat** [comment]
Hmm, I don't see the way how it's trying to find `pkexec`.  There might be no significant advantage of splitting `.out` and `.bin` of polkit, so if it should cause problems we can't avoid...

**Comment by ryantm** [comment]
The problem is independent of the gnome-settings daemon. See this terminal session:

```
ryantm@laptop2 ~/.nixpkgs (master)$ pkexec
pkexec: cannot run `/nix/store/x7g0glbq3c7kl15w1wif3qncq1016wz4-polkit-0.113/bin/pkexec': No such file or directory
ryantm@laptop2 ~/.nixpkgs (master)$ ls -lah `which pkexec`
-r-s--x--x 1 root root 18K Feb 22 12:11 /run/wrappers/bin/pkexec
```

**Comment by ryantm** [comment]
@vcunat Thanks! I confirmed it is fixed for me.
