### ISSUE TITLE
`buildDotnetModule` with `ReadyToRun` restricts the derivation to a single platform

### ISSUE THREAD

**Issue by natsukium** [NixOS/nixpkgs#230848]
### Describe the bug

Since .NET6, the `crossgen2` used when using R2R, has been separated from the runtime. [[1]](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/publish-readytorun-requires-restore-change)
Therefore, when R2R is specified, `nix-build -A ${pkg}.fetch-deps` gets the platform-specific crossgen2. [[2]](https://github.com/NixOS/nixpkgs/pull/229434#discussion_r1182326011)
At this time, crossgen2 for multiple platforms cannot coexist, so the platform of derivation is restricted.

### Steps To Reproduce
1. Run `nix-build -A tone.passthru.fetch-deps` on platform other than "x86_64-linux". 

### Expected behavior
The package can be built on multiple platforms.

### Additional context
Disabling "R2R" solves this problem since the platform-dependent `crossgen2` is no longer used.
In this case, we can set it as the default value for `dotnetRestoreFlags` and `dotnetBuildFlags` (or `dotnetFlags`?).

### Notify maintainers
@IvarWithoutBones, @mdarocha, @corngood
I mentioned those who have committed to `buildDotnetModule` a lot.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, NixOS, 23.05 (Stoat), 23.05.20230507.7975a3c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mdarocha** [comment]
I've also ran into problems related to Ready2Run, however for me they were related to binaries embedded in nuggets that could run in nix (related: https://github.com/NixOS/nixpkgs/issues/181373)

Can you elaborate on the problem with crossgen2 packages coexisting? It should not be a problem for multiple crossgen nuggets to be available, dotnet should choose the correct one automatically during build. All crossgen packages should also be included in the generated deps, since dotnet restore is run for every runtime specified during fetch-deps execution

**Comment by natsukium** [comment]
Thank you for sharing your case study.

This issue reports that the platform of `crossgen2` changes depending on the environment in which `fetch-deps` is run, even though we have restored using multiple rids.
For example, [this file](https://github.com/NixOS/nixpkgs/blob/d7bbeedaac9f07965cb47d0e5ec3301fd2a91aaa/pkgs/applications/audio/tone/nuget-deps.nix#LL31C3-L31C157) was generated on `x86_64-linux`, but when generated on `aarch64-darwin`, it is overwritten as follows.
``` diff
- (fetchNuGet { pname = "Microsoft.NETCore.App.Crossgen2.linux-x64"; ...
+ (fetchNuGet { pname = "Microsoft.NETCore.App.Crossgen2.osx-arm64"; ...
```
It means that `deps.nix`, which contains all of linux-x64, linux-arm64, or osx-arm64 cannot be generated.
This issue might be a problem with `nuget-to-nix`.

**Comment by mdarocha** [comment]
I've made a fix in https://github.com/NixOS/nixpkgs/pull/233422
