### ISSUE TITLE
[suggestion/idea]: would it be better to base not on stdenv but on one that is based on llvm/clang?

### ISSUE THREAD

**Issue by ppenguin** [NixOS/nixpkgs#230829]
@paveloom 

Great to see this in `nixpkgs`!
I just wanted to test-drive `codon` and noticed the derivation is based on `stdenv`, which AFAIK depends on `gcc` etc, which is arguably not needed. If this derivation would instead be based on `llvm/clang` it would probably not only avoid unnecessary deps but at the same time avoid hard-coded/manual setting of `DCMAKE_...` (not 100% sure though)?

I'm doing something similar for a `mkShell` [here](https://github.com/ppenguin/nixenvs/blob/main/dev/devshell-flutter-go.nix) which could probably work the same for `mkDerivation`?

**Comment by paveloom** [comment]
Hello there!

I am using LLVM's `stdenv`, as can be seen here:

https://github.com/NixOS/nixpkgs/blob/805ff35106cde011000c1ea0be3c9f94054b6ef8/pkgs/top-level/all-packages.nix#L14513-L14515

You're probably right that the `DCMAKE` flags for the compiler aren't necessary, though.

**Comment by ppenguin** [comment]
@paveloom Ah, of course, thanks for the enlightenment!
It's actually best like that as I now understand, because it allows for custom overrides on the package level which otherwise wouldn't work...
Also I noticed that they use a heavily patched llvm anyway, so significant parts of the `llvm sdenv` can't be used anyway.

Cheers, closing...
/close
