### ISSUE TITLE
Package request: Howdy

### ISSUE THREAD

**Issue by saikatdas0790** [NixOS/nixpkgs#230828]
**Project description**

Howdy provides Windows Hello™ style authentication for Linux. Use your built-in IR emitters and camera in combination with facial recognition to prove who you are.

Using the central authentication system (PAM), this works everywhere you would otherwise need your password: Login, lock screen, sudo, su, etc.

**Metadata**

* homepage URL: https://github.com/boltgolt/howdy
* source URL: https://github.com/boltgolt/howdy
* license: mit
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/76928

**Comment by saikatdas0790** [comment]
> Duplicate of #76928

Sorry about that. I should have checked for a duplicate. I can close this if you want and upvote the original.
