### ISSUE TITLE
singularity cannot use nvidia gpu.

### ISSUE THREAD

**Issue by misumisumi** [NixOS/nixpkgs#230851]
### Describe the bug
singularity cannot use nvidia gpu because it does not access 'nvidia-container-cli'

### Steps To Reproduce
1. add `programs.singularity.enable=true`
2. run `singularity exec --nvccli docker://nvidia/cuda:10.0-base nvidia-smi`

### Expected behavior
return result of `nvidia-smi`

### Screenshots
![image](https://user-images.githubusercontent.com/24451978/237062676-05a0a329-0303-412d-9339-49fc257de77e.png)

### Additional context
This is because the path is not listed in singularity.conf, as also in a.
It is caused by neither the option `--nv` nor `--nvccli`.
I tried to handle it with override, but since it was called in `callPackage`, I think it is impossible to handle.
Also, I created a conf file in `/usr/local/etc/singularity/` as shown in the singularity docs, but it was not read.

### Notify maintainers
@jbedo  @ShamrockLee 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05.20230430.da45bf6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ShamrockLee** [comment]
Thank you for reporting and sorry for the trouble. I'll look at the SingularityCE documentation again. (Those configuration options has been deprecated by Apptainer.)

> I tried to handle it with override, but since it was called in callPackage, I think it is impossible to handle.
Also, I created a conf file in /usr/local/etc/singularity/ as shown in the singularity docs, but it was not read.

[`overrideAttrs`](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideAttrs) shold be what you are looking for. The overriden package can be assigned to `programs.singularity.package`.

(If you would like to bypass all the overriding done by the module and directly specify the package to install for some special reason, you can assign it to ``programs.singularity.packageOverriden`.)

**Comment by misumisumi** [comment]
Thanks for the reply.
I followed your advice and tried the override and was able to use the GPU.
Here is the code
This is simply adding a process to append the nvidia-docker path to the singularity.conf
```nix
  nixpkgs.overlays = [
    (final: prev: {
      _singularity = prev.singularity.overrideAttrs (old: rec {
        postFixup =
          old.postFixup
          + ''
            ${prev.lib.optionalString true ''
              substituteInPlace "$out/etc/singularity/singularity.conf" \
                --replace "# nvidia-container-cli path =" "nvidia-container-cli path = ${prev.nvidia-docker}/bin/nvidia-container-cli"
            ''}
          '';
      });
      singularity = config.programs.singularity.packageOverriden;
    })
  ];
  programs.singularity.enable = true;
  programs.singularity.package = pkgs._singularity;
```

I mentioned earlier that when conf was entered in `/usr/local/etc/singularity`, it was not reflected, and the same is true for '/etc/singularity'.
I referred to [this docs](https://docs.sylabs.io/guides/latest/admin-guide/configfiles.html).

**Comment by misumisumi** [comment]
Adding the path of `nvidia-container-cli` to `$out/etc/singularity/singularity.conf` works well.
This once removed from consideration.

Next we have a patched version of ldconfig.
This does not append the path of `nvidia-container-cli` to the config.
The result was an error that `nvidia-container-cli` could not be found, and it could not be started.
```nix
{ config, lib, pkgs, ...}:
{
  nixpkgs.overlays = [ (final: prev: {
    _singularity =
      let
        _ldconfig = final.writeShellScript "ldconfig" ''
          cleanup() {
            rm -f "$TMP"
          }
          trap cleanup EXIT

          TMP=$(mktemp)
          ldconfig -C "$TMP" /run/opengl-driver/lib
          ldconfig -C "$TMP" $@
        '';
      in
      prev.singularity.overrideAttrs (old: {
        postFixup = old.postFixup + lib.optionalString true ''
          substituteInPlace "$out/etc/singularity/singularity.conf" \
            --replace "# ldconfig path =" "ldconfig path = ${_ldconfig}"  # I changed
        '';
      });

    singularity = config.programs.singularity.packageOverriden;
  }) ];

  programs.singularity.enable = true;
  programs.singularity.package = pkgs._singularity;
}
```

**Comment by ShamrockLee** [comment]
I tried to enable the use of external sysconfdir (https://github.com/NixOS/nixpkgs/compare/master...ShamrockLee:nixpkgs:singularity-external-config-dir), but have encountered issue trying to specify a directory under `/etc`with the NixOS module `environment.etc` (#200744).

**Comment by ShamrockLee** [comment]
@misumisumi Have you tried to apply both at the same time?

**Comment by ShamrockLee** [comment]
The SingularityCE Admin Guide says

If the value of nvidia-container-cli path is empty, SingularityCE will look for the binary on $PATH at runtime.

https://docs.sylabs.io/guides/3.11/admin-guide/configfiles.html#experimental-nvidia-container-cli-support

It should work as long as `nvidia-container-cli` is found in the run-time `PATH`, even when `nvidia-container-cli path` is not set. As nvidia-container-cli is alredy included in the PATH-prefixing wrapper, we shouldn't have to set the `nvidia-container-cli path`.

**Comment by ShamrockLee** [comment]
Update: I found a bug in the prefixed PATH of the wrapper introduced in f6e7fccfa6b22fb8928fd1c3cf8401f7fef17e11 .

The prefixing `PATH` should be specified as (in Bash)

```bash
"${defaultPathInputs// /\/bin:}${defaultPathInputs:+/bin}"
```

I forgot to add `${defaultPathInputs:+/bin}`, causing the trailing `/bin` to be missing.

**Comment by ShamrockLee** [comment]
The statement in the SingularityCE Admin Guide turns out to be wrong / irrelevant.

The source code clearly states that nvidia-container-cli will only be read from the configuration.

```go
	// cryptsetup & nvidia-container-cli paths must be explicitly specified
	// They are called as root from the RPC server in a setuid install, so this
	// limits to sysadmin controlled paths.
	// ldconfig is invoked by nvidia-container-cli, so must be trusted also.
	case "cryptsetup", "ldconfig", "nvidia-container-cli":
		return findFromConfigOnly(name)
```

https://github.com/sylabs/singularity/blob/adb9010010594d0c8c3a380d65920f90c667309b/internal/pkg/util/bin/bin.go#L47

**Comment by SomeoneSerge** [comment]
(we need to patch nvidia-container-cli, for many reasons https://discourse.nixos.org/t/using-nvidia-container-runtime-with-containerd-on-nixos/27865/28)

**Comment by SomeoneSerge** [comment]
Eh, actually, closed semi-automatically. Apptainer with `--nv` is fixed, but not with `--nvccli`. The fix doesn't concern singularity-ce either, unfortunately. Shouldn't be hard to make this work with singularity too, but I'm out of bandwidth

**Comment by devhell** [comment]
Hi folks, I've been trying to get apptainer to run this [NAMD container](https://cloud.sylabs.io/library/perminaa/default/namd) (which I've done previously with a slight ldconfig hack -- that doesn't work anymore -- on NixOS 22.11), that will make use of the machine's Tesla V100 to do some simulation stuff.

The machine is running NixOS 23.11. Using the workaround from @ShamrockLee's 9th of May post further up, I was able to get past the ldconfig issue, but now I'm getting an error saying the driver and CUDA are not in sync. Before I start posting any details (I don't want to re-open this issue, but I'm also not sure if I'm just doing something wrong) I was wondering if the current implementation of singularity/apptainer on NixOS is expected to work, and I'm just being an idiot, or if there are known breaking issues?

I've seen the other issues about singularity/apptainer here, but I'm not knowledgeable enough to make a judgement call if they are responsible for my problem or not.

Thanks very much in advance!

**Comment by SomeoneSerge** [comment]
>  saying the driver and CUDA are not in sync.

That usually means you need a reboot, and you should experience the same issue outside the container

**Comment by devhell** [comment]
> > saying the driver and CUDA are not in sync.
> 
> (If I understood the message correctly) That usually means you need a reboot, and you should experience the same issue outside the container

No, the reboot didn't help either. For some reason, though, after upgrading to 24.05, everything "just works[tm]" again. So, whatever the issue was, thanks for fixing it (probably)! :)

**Comment by ShamrockLee** [comment]
> No, the reboot didn't help either. For some reason, though, after upgrading to 24.05, everything "just works[tm]" again. So, whatever the issue was, thanks for fixing it (probably)! :)

Thanks to @SomeoneSerge, Nixpkgs 24.05 includes GPU-related changes/fixes to the `apptainer` package and the `programs.singularity` module.

**Comment by SomeoneSerge** [comment]
Well more like thanks to ShamrockLee
