### ISSUE TITLE
OC_CONFIG_PATH not set correctly in owncloud > 9

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#23088]
## Issue description
There is a patch to set the OC_CONFIG_PATH to point outside of the nix store. It dosen't work with any owncloud > 8.2

//cc @matejc

**Comment by datakurre** [comment]
@pstn Would you have any updates on this?

**Comment by pstn** [comment]
No, I don't even have a test case right now. I had to set up a quick owncloud to export something noticed it, thought I let people know and promptly forgot about it again.

Incidentally I've seen that nextcloud (the fork of which people tell me it's better than the original) supports this option in upstream, so maybe there could be a quick solution for you.
