### ISSUE TITLE
pam_mount: allow_discard not working

### ISSUE THREAD

**Issue by jzbor** [NixOS/nixpkgs#230920]
### Describe the bug
It seems like the `allow_discard` option for crypt devices is not working properly. This prohibits users users from manually trimming encrypted ssds mounted via `pam_mount`.

Maybe this is due to `%(OPTIONS)` missing from [the config](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/pam_mount.nix) in the `cryptmount` tag, although I am not quite sure..

### Steps To Reproduce
I used the following in [my NixOS config](https://github.com/jzbor/nixos-config):
```nix
  # Automount encrypted drives on login
  security.pam.mount = {
    enable = true;
    extraVolumes = [
      "<volume user=\"jzbor\" fstype=\"crypt\" path=\"/dev/disk/by-label/crypt0-home\" mountpoint=\"~\" options=\"crypto_name=crypt0,allow_discard,fstype=ext4\"/>"
      # extra drive on desktop-i5
      "<volume user=\"jzbor\" fstype=\"crypt\" path=\"/dev/disk/by-uuid/2fb1ab80-c89e-419a-96f3-ec89edbd4f16\" mountpoint=\"~/.bigdata\" options=\"crypto_name=crypt1,allow_discard,fstype=ext4\"/>"
    ];
    createMountPoints = true;

    # Kill remaining processes after final logout
    #logoutTerm = true;
    #logoutWait = 0;  # seconds
  };
```

### Expected behavior
If I run fstrim manually I would expect the device to perform the expected trim. Instead I get the following error message:
```
[jzbor@desktop-i5] ~ doas fstrim -v /home/jzbor
fstrim: /home/jzbor: the discard operation is not supported
```

The `mount` command also does not show anything special, although I am not sure if it should:
```
[jzbor@desktop-i5] ~ mount | grep /home                                                        
/dev/mapper/_dev_nvme0n1p3 on /home/jzbor type ext4 (rw,relatime,helper=crypt)
```

### Notify maintainers
@NetaliDev 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0, NixOS, 23.05 (Stoat), 23.05.20230502.44f30ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/channels/nixpkgs`

**Comment by NetaliDev** [comment]
I think that you are right with the missing `%(OPTIONS)` in the `cryptmount` tag.

If I have time, I'll take a closer look later this week and open a PR with a fix right away.

**Comment by jzbor** [comment]
Hi, how's it going. Did you have time to take a look at it yet?

**Comment by NetaliDev** [comment]
Unfortunately no, but maybe this weekend

**Comment by jzbor** [comment]
Okay thanks a lot :)
