### ISSUE TITLE
Shortwave and Tuner do not show stream title

### ISSUE THREAD

**Issue by fbewivpjsbsby** [NixOS/nixpkgs#230996]
### Describe the bug
Shortwave and Tuner do not show stream title.

### Steps To Reproduce
1. Open Shortwave or Tuner.
2. Select a station with metadata.
3. It playing and not show stream title.

### Expected behavior
Shortwave and Tuner show stream title.

### Screenshots
Shortwave
![image](https://github.com/NixOS/nixpkgs/assets/132867585/534c7c98-1a2b-477d-bc8a-0107701b5999)
Tuner
![image](https://github.com/NixOS/nixpkgs/assets/132867585/6242c688-2a1a-4cd9-b754-8a4af7a1065a)

### Additional context
When use flatpak not this issues.

### Notify maintainers

@lasandell @maintainers.abbe @wahjava

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05.20230506.897876e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lasandell** [comment]
Closing as I can no longer reproduce this on nixpkgs 24.05.
