### ISSUE TITLE
Can we make it easier to make a derivation with no source?

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#23099]
If you call `mkDerivation` without specifying `src` or `srcs`, it fails to build with

    variable $src or $srcs should point to the source

Sometimes I *want* to make a derivation that has no source, like if it only needs to combine things from other derivations.

I usually resort to

    src = builtins.filterSource (path: type: false) ./.;

Is there some more convenient way to do this?

**Comment by FRidh** [comment]
You could pass `unpackPhase = "true";`. In other cases an option might be `pkgs.runCommand`.

**Comment by LnL7** [comment]
You can also configure what [`phases`](http://nixos.org/nixpkgs/manual/#sec-stdenv-phases) should run for a derivation, but I think using a noop for the unpackPhase is generally a better solution. eg. `phases = [ "installPhase" "fixupPhase" ];`

**Comment by FRidh** [comment]
I think the question has been answered so I am closing this.

**Comment by SuperSandro2000** [comment]
Since this is a top google result I think it is important to point out some changes:

- Overwriting phases is an anti pattern and not allowed for normal packages in nixpkgs.
- Please use ``dontUnpack = true;`` instead of ``unpackPhase = "true";``.
