### ISSUE TITLE
remove-references-to: this can't be right

### ISSUE THREAD

**Issue by rhendric** [NixOS/nixpkgs#230933]
### Describe the bug

Look at the `eval` line here:
https://github.com/NixOS/nixpkgs/blob/7e14b746c01a1a8123c9d78fe01e638872a9720f/pkgs/build-support/remove-references-to/remove-references-to.sh#L33-L37

That `$i` is technically bound to the last argument provided to the script, but given the context it sure looks like it was meant to be `$region` instead.

I don't really know what this script is for so I can't test it, but I got here from looking at this Hydra log:

https://hydra.nixos.org/build/219102963/nixlog/2

Fixing `remove-references-to` may or may not resolve the build failure; I don't have the hardware to test this.

So I'm hoping that someone with one or both of the relevant expertise and the relevant hardware can look at this and confirm or refute my suspicion; sorry I can't be more directly helpful, or for abusing the ZHF label if this doesn't end up being relevant to that.

### Steps To Reproduce
1. Look at https://github.com/NixOS/nixpkgs/blob/7e14b746c01a1a8123c9d78fe01e638872a9720f/pkgs/build-support/remove-references-to/remove-references-to.sh#L35
2. Contemplate the nature of bash

### Expected behavior

Probably `$region`, but I don't know.

**Comment by alyssais** [comment]
cc @thefloweringash

**Comment by thefloweringash** [comment]
I apparently opened https://github.com/NixOS/nixpkgs/pull/162447 and forgot all about it.
