### ISSUE TITLE
Sway

### ISSUE THREAD

**Issue by ndowens** [NixOS/nixpkgs#23090]
## Issue description

Sway does not include optional dependency of xwayland to enable applications to run in sway, such as firefox, chromium, etc

@jnsaff 

### Steps to reproduce
N/A

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03pre101636.183eeb3 (Gorilla)

* Nix version: (run `nix-env --version`)
1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre101636.183eeb3"

**Comment by jnsaff** [comment]
FYI, I am planning to fix this with when updating to the next release of sway. If you need it earlier you are welcome to submit a PR.

Sway 0.12.1 has a bug that prevents it working on Nix but there is a commit (https://github.com/SirCmpwn/sway/commit/8306b886e9d24a5bbeafedf315724f97b3ae86d4) in master that should be included in the next release and fix it.

So if you need it now, submit a PR which includes xwayland on current version or wait till next Sway release to include xwayland as a dependency.

**Comment by NeQuissimus** [comment]
Should be fixed by #24639
