### ISSUE TITLE
Package request: Tuba

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#230960]
**Project description**
Tuba is a GTK Mastodon Client that looks fanstastic.

![Tuba](https://camo.githubusercontent.com/15671cb96e8323942de763b4b83af7f3802068944a8200d8af66e7ae689068b4/68747470733a2f2f692e696d6775722e636f6d2f6a4b6d465a6f752e706e67)
**Metadata**

* homepage URL: https://github.com/GeopJr/Tuba
* source URL: https://github.com/GeopJr/Tuba
* license: GPL3
* platforms: Linux

**Comment by Aleksanaa** [comment]
It's already there. https://search.nixos.org/packages?channel=unstable&show=tuba&from=0&size=50&sort=relevance&type=packages&query=tuba

**Comment by Krutonium** [comment]
How the... I looked and it didn't show up. Thanks!
