### ISSUE TITLE
i686 swap problems in tests (master)

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#23107]
## Issue description

We're reproducibly getting problems in the hibernate test, but only on i686-linux.
```
machine# [   11.350824] swapon[633]: swapon: /dev/vdb: read swap header failed
machine# [   11.358592] systemd[1]: dev-vdb.swap: Swap process exited, code=exited status=255
machine# [   11.372330] systemd[1]: Failed to activate swap /dev/vdb.
machine# [   11.377620] systemd[1]: Dependency failed for Swap.
machine# [   11.382812] systemd[1]: swap.target: Job swap.target/start failed with result 'dependency'.
machine# [   11.392925] systemd[1]: dev-vdb.swap: Unit entered failed state.
```

As a result, the channel is blocked, missing security updates, etc.  I don't know if the problem also happens outside VM or outside tests.

**Comment by abbradar** [comment]
Aaargh, I would have looked at this but I've accidentially reverted to configuration with unstable Nix! So now I need to reinstall NixOS again or I can't run tests because of https://github.com/NixOS/nixpkgs/issues/22868 D:

**Comment by vcunat** [comment]
Oh, is there not a way to go back?  I'd think you "only" need to downgrade the database schema.

**Comment by abbradar** [comment]
Actually I was just stupid and haven't read the manual good enough:

```
# nix-build -A nixUnstable -o nix-new
# nix-build -A nix -o nix-old
# nixos-rebuild switch
# nix-new/bin/nix-store --dump-db > db.nix
# mv /nix/var /nix/var.old
# systemctl restart nix-daemon.socket
# cat db.nix | nix-old/bin/nix-store --load-db
```

Not a nice procedure but better than a reinstall!

**Comment by vcunat** [comment]
It would seem nice if someone we improved the situation, as it's one of the rare things you can't just roll back.

**Comment by abbradar** [comment]
A rough sketch of how could that work:

```
  systemd.services.nix-daemon.preStart = ''
    # Check that we can read the schema somehow
    if ! check-schema; then
      backup="$(mktemp -d /nix/var/nix/db.old.XXX)"
      /nix/var/nix/current/bin/nix-store --dump-db > /nix/var/nix/db.dump
      mv /nix/var/nix/db "$backup"
      cat /nix/var/nix/db.dump | ${cfg.package}/bin/nix-store --load-db
    fi
    ln -sf /nix/var/nix/current ${cfg.package}
  '';
```

**Comment by abbradar** [comment]
I get this on this test:

```
machine# KVM internal error. Suberror: 1
machine# emulation failure
machine# EAX=d70d9dc8 EBX=00018000 ECX=0000007b EDX=00000000
machine# ESI=ceb74000 EDI=d584ee00 EBP=d70d9e24 ESP=d70d9dc4
machine# EIP=d584ee00 EFL=00010083 [--S---C] CPL=0 II=0 A20=1 SMM=0 HLT=0
machine# ES =007b 00000000 ffffffff 00c0f300 DPL=3 DS   [-WA]
machine# CS =0060 00000000 ffffffff 00c09b00 DPL=0 CS32 [-RA]
machine# SS =0068 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
machine# DS =007b 00000000 ffffffff 00c0f300 DPL=3 DS   [-WA]
machine# FS =00d8 0169f000 ffffffff 00809300 DPL=0 DS16 [-WA]
machine# GS =00e0 d7647200 00000018 00409100 DPL=0 DS   [--A]
machine# LDT=0000 00000000 ffffffff 00000000
machine# TR =0080 d7645080 0000206b 00008b00 DPL=0 TSS32-busy
machine# GDT=     d763c000 000000ff
machine# IDT=     fffba000 000007ff
machine# CR0=80050033 CR2=d603b478 CR3=0bfb3000 CR4=000006b0
machine# DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
machine# DR6=ffff0ff0 DR7=00000400
machine# EFER=0000000000000000
machine# Code=00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 <00> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by vcunat** [comment]
Well, that looks very different from the errors on Hydra.

**Comment by abbradar** [comment]
Eeeeh, first I couldn't reproduce my error anymore and now it just works.

**Comment by abbradar** [comment]
So, out of 10 runs 7 times it succeeds and 3 tiimes it fails without any visible errors. Couldn't reproduce a KVM error.

**Comment by abbradar** [comment]
I'm testing this with 84a50a6fcaee6b7a472721eb7d992a115a21485a (see https://github.com/NixOS/nixpkgs/issues/23020) now, just in case.

**Comment by abbradar** [comment]
Still no luck with determining the cause. We may just move on and mark this test as non-mandatory given that it's unstable...

**Comment by abbradar** [comment]
More testing; I think I see three distinctive patterns:

1. Test succeeds;
2. Test fails infinitely waiting for machine to respond to network request after resume. This shows up in log:
```
machine# [    1.529586] PM: Image loading progress: 100%
machine# [    1.530081] PM: Image loading done.
machine# [    1.530342] PM: Read 89340 kbytes in 0.22 seconds (406.09 MB/s)
machine# [    1.531371] Suspending console(s) (use no_console_suspend to debug)
vde_switch: EOF data port: Interrupted system call
```
i.e. something happens with `vde_switch` or `qemu`, maybe machine suddenly halts -- hot sure...
3. (rare) [Internal KVM error](https://github.com/NixOS/nixpkgs/issues/23107#issuecomment-282059070)

**Comment by vcunat** [comment]
Apparently some attempts on Hydra passed now and nixos-unstable got updated :-)

**Comment by vcunat** [comment]
I dropped it from the tested job for now, as i686 is lower-priority, etc.

**Comment by abbradar** [comment]
Possible fix: https://github.com/NixOS/nixpkgs/commit/affce1e2464f226afb6902c5185fee80d847d857.

**Comment by fpletz** [comment]
The hibernate tests for i686 has been green for a while so this is fixed.
