### ISSUE TITLE
chromium ssl certificates bogus

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#23100]
## Issue description

Similar to #12298. I'm getting
```
This site can’t provide a secure connection

mail.google.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```
![screenshot from 2017-02-22 20-15-02](https://cloud.githubusercontent.com/assets/4804/23244682/c9c0ee0a-f93b-11e6-944b-5beb041247a8.png)

### Steps to reproduce

1. nix-env -i chromium
2. navigate to mail.google.com

## Technical details
```
ryantm@laptop2 ~ (master)$ nixos-version
17.03.git.3c9e977 (Gorilla)
ryantm@laptop2 ~ (master)$ nix-env --version
nix-env (Nix) 1.11.6
ryantm@laptop2 ~ (master)$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre101636.183eeb3"
ryantm@laptop2 ~ (master)$ chromium --version
Chromium 56.0.2924.87 
```

**Comment by ryantm** [comment]
Disabling token binding in chrome://flags fixes it. @maurer says it is a bug in Chromium.

**Comment by alexozer** [comment]
Would updating Nix's Chromium version fix this? The default chromium config in Arch for instance does not have this problem.
