### ISSUE TITLE
idea.* should use bundled JRE and not system JRE

### ISSUE THREAD

**Issue by GauthierPLM** [NixOS/nixpkgs#23115]
## Issue description

IntelliJ IDEA and derived IDEs bundle a JetBrains' modified JRE which improve user experience and contains fixes not yet available in official JRE (especially for font rendering).

It's recommended by JetBrains to use it instead of the system JRE. If the user wants to use the system one, he can still choose to use it from the IDE.

Currently, system JRE is set to be used by the IDE.

**Comment by Kendos-Kenlen** [comment]
I'm trying to fix this, however I don't know if I should create a separate package and share it between all idea.* software or if it's better to patch the jre/ folder (because linker path and other stuff aren't correct) ?

**Comment by chris-martin** [comment]
Btw according to the [docs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under) IntelliJ 16 was the first version to bundle the runtime for Linux, so we have some older versions that need to remain unaffected be affected by this change.

**Comment by chris-martin** [comment]
Maybe it makes more sense to ignore the bundled JRE and instead add a new package `pkgs/development/compilers/intellij-jdk`.

https://bintray.com/jetbrains/intellij-jdk

**Comment by chris-martin** [comment]
The JetBrains runtime https://github.com/JetBrains/jdk8u is a fork of OpenJDK, so hopefully we can package this up just by making some tweaks to our openjdk8 package.

**Comment by Kendos-Kenlen** [comment]
@chris-martin I made a PR (#23297) which is supposed to remove old versions of JetBrains products, but we didn't decided yet if it should be merged or not.

I agree with @edwtjo who posted there that we should simply remove old versions and people needing old versions should use an older revision of nixpkgs. It would allow us to simply add `intellij-jdk` as dependency instead of `jdk`.

**Comment by chris-martin** [comment]
@Kendos-Kenlen I really wish we wouldn't do that, but on further consideration I don't think it matters here. We can add intellij-jdk as the dependency for old versions too, it doesn't matter that they weren't bundled with it.

**Comment by romildo** [comment]
Any progress on this issue?

**Comment by matklad** [comment]
If anybody finds it useful, here's an overlay I use to get the latest IDEA with JetBrains jdk: https://gist.github.com/matklad/3b7b5e30b4302ac2a4cc68a71252ab48.

**Comment by joncojonathan** [comment]
@GauthierPLM - the only concern I have with removing the older versions of jetbrains software is that some people have not maintained their license subscription.  As a result they're required to use their old version for which they have a perpetual license.

Thoughts?

**Comment by matklad** [comment]
Hm, as for original issue, I think it was fixed by #29634? At the moment, all JetBrains products use JetBrains JDK.

**Comment by baracoder** [comment]
> Hm, as for original issue, I think it was fixed by #29634? At the moment, all JetBrains products use JetBrains JDK.
