### ISSUE TITLE
Package Request: swift-3.0.2

### ISSUE THREAD

**Issue by silvernode** [NixOS/nixpkgs#23110]
Since it doesn't seem like any rolling distribution or any distribution for that matter seems to have a working build of the [Swift Programming Language](https://swift.org/download/) and nix handles packages very well across systems. I thought I would write a request (even though I see no evidence this is welcome here). I just started playing with Nixos last night and am already impressed. 

Keep up the good work and my apologies if this is not a place you prefer package requests. 
Cheers!

**Comment by dtzWill** [comment]
I had problems building 3.0.2 reasonably, but I've packaged up 3.1 and it works for me :).

It's not merged yet (see: https://github.com/NixOS/nixpkgs/pull/22098), and requires building with sandbox enabled (but the result works without the sandbox, at least in my experience).  It's quite the big package to compile yourself, but if you want Swift goodness you might wanna give that a go.

LMK on that PR if you have any questions or problems with it.

**Comment by silvernode** [comment]
Thanks for your hard work man, people tell me not to bother with swift on Linux but I can't see support getting any worse. I'll give it a shot.

**Comment by matthewbauer** [comment]
Good enough to close?

**Comment by benley** [comment]
Swift 3.1 has been merged into master so unless there's a specific need for 3.0.2 I'd say yeah, this can probably be closed.
