### ISSUE TITLE
Package request: doomrunner

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#231123]
**Project description**

Modern preset-oriented graphical launcher of ZDoom and derivatives (an alternative to ZDL)

**Metadata**

* homepage URL:
* source URL: https://github.com/Youda008/DoomRunner/
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/210339
