### ISSUE TITLE
Confusing appearance of postgresql on brand new system with only httpd running

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23120]
I set up a brand new NixOS system with nothing but `services.httpd.enable = true`. After switching to the new configuration, I ran `systemctl -a` and was surprised to find `postgresql.service` in there in a `not-found` and `dead` state.

I poked around and it turns out that our `apache-httpd` module refers to `postgresql.service` in its `After` section: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/apache-httpd/default.nix#L689

It sort of makes sense, because presumably you want your webserver to spin up after your database, but it feels kinda icky to give completely unrelated (in principle) services dependencies on one another, especially when some of them might not even be on your system. I suppose we could make that entry conditional on `services.postgresql.enable`, but I'm not sure what the pros and cons of that are.

**Comment by vcunat** [comment]
Yes, I'd think it should be conditional.  Units should get reloaded on system switch IIRC, before starting new services, so I see no danger in that.

**Comment by danbst** [comment]
I think, this link should be broken unconditionally. In my scenario apache-httpd is used solely for SVN web interface, and while I have running Postgresql instance, they are orthogonal (postgresql is acompanied by tomcat container/nginx pair)

**Comment by copumpkin** [comment]
Perhaps, yeah. It also appears to depend on `keys.target`, which I think is a nixops-ism.
