### ISSUE TITLE
sudo stopped working after update to 17.03pre101636.183eeb3

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#23126]
## Issue description
After `nixos-rebuild switch` to 17.03pre101636.183eeb3 (from 1 month old 17.03pre) I have this:
```
$ sudo nixos-rebuild switch
sudo: /run/current-system/sw/bin/sudo must be owned by uid 0 and have the setuid bit set
$ sudo su
sudo: /run/current-system/sw/bin/sudo must be owned by uid 0 and have the setuid bit set
```
basically, sudo stopped working.

When I start new shell, `sudo` works fine. Is this expected behavior?

**Comment by volth** [comment]
duplicate #22914

**Comment by dezgeg** [comment]
Indeed. I reopened that one and marked as blocker.
