### ISSUE TITLE
Build failure: wezterm

### ISSUE THREAD

**Issue by remi-gelinas** [NixOS/nixpkgs#231291]
### Steps To Reproduce

1. Build `wezterm` for `x86_64-darwin`, on MacOS Ventura (13.3.x)

### Build log

https://gist.github.com/remi-gelinas/fd07dce3a836a7c87f41b1a062350d9e

### Additional context

Tested builds on both a `x86_64-darwin` `hostSystem` and an `aarch64-darwin` `hostSystem` and got the same error. Metadata was obtained on an `aarch64-darwin` machine compiling for both architectures, as x86 Darwin can be compiled for on Apple Silicon.

### Notify maintainers

@SuperSandro2000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(user): `""`
 - nixpkgs: `/nix/store/00d5ysz5ws1xpfv229m9ml6in7qlkz1b-source`
```

**Comment by SuperSandro2000** [comment]
No idea and I am not really motivated to dig into why this is broken myself. If someone figures it out, please fill a PR and I'll take a look at it.
```
  = note: Undefined symbols for architecture x86_64:
            "___darwin_check_fd_set_overflow", referenced from:
                _ssh_poll in liblibssh_rs_sys-fa10a07daad3af81.rlib(poll.o)
          ld: symbol(s) not found for architecture x86_64
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by natsukium** [comment]
FYI, the sdk versions may be bad.
https://github.com/NixOS/nixpkgs/pull/195606#issuecomment-1386145750
https://github.com/curl/curl/issues/5210

**Comment by SuperSandro2000** [comment]
We are using the 11 sdk since https://github.com/nixos/nixpkgs/commit/08ccdcbc9c6cbfa5b88ddb65d0a3c51a627a54b2

maybe some dependency also needs to be linked against that version?

/cc @mimame

**Comment by alienman5k** [comment]
Is there a way to choose the binary package instead of building from source?

**Comment by softinio** [comment]
I am having the same issue since I last updated my flakes.

**Comment by SuperSandro2000** [comment]
> Is there a way to choose the binary package instead of building from source?

On MacOS you can download the wezterm binary from their page.

**Comment by remi-gelinas** [comment]
Until this is fixed I've replaced the `nixpkgs` derivation with the [MacOS universal binary](https://github.com/remi-gelinas/rosetta/blob/trunk/packages/wezterm-bin/default.nix). Working great so far.
