### ISSUE TITLE
"roy" fetchurl mirror:// is no more

### ISSUE THREAD

**Issue by evrim** [NixOS/nixpkgs#231217]
### Describe the bug

The fetchurl mirror:// called roy is no more. Apparently, they switched to gh. dhcpcd and openresolv are two derivations that fail on my system to build.

thnx,
evrim.

**Comment by mweinelt** [comment]
If the canonical upstream moved to GitHub, I expect that the remaining mirror at cflags.cc will run out of date soon.

Feel free to remove the mirror list for roy and update the sources for the mentioned packages accordingly.

**Comment by endgame** [comment]
I just hit this as well, while trying to build `dhcpcd-4.9.1.tar.xz` (I am stress-testing a new machine by building NixOS without substituters). I found a copy at a BLFS mirror: http://ftp.osuosl.org/pub/blfs/conglomeration/dhcpcd/ .

Annoyingly, some of older releases (like `dhcpcd-9.4.1`) don't have proper github releases, only tags.

`openresolv-3.12.0.tar.xz` has disappeared off the cflags.cc mirror and I can't seem to find it anywhere else. What is the correct fix for these? Doing a `fetchFromGitHub`? I might try to tackle some if I have a minute.

**Comment by endgame** [comment]
Fixed by #237693 .
