### ISSUE TITLE
Package request: librime-octagram

### ISSUE THREAD

**Issue by eval-exec** [NixOS/nixpkgs#231458]
**Project description**
It's octagram plugin for RIME
RIME〖八股文〗語法插件

**Metadata**

* homepage URL: https://github.com/lotem/librime-octagram
* source URL: https://github.com/lotem/librime-octagram
* license: gpl3
* platforms: linux

**Comment by pca006132** [comment]
I think you can do something like this:

```nix
    nixpkgs.overlays = [
      (final: prev: {
        librime = prev.librime.override {
          plugins =
            [
              (pkgs.stdenv.mkDerivation rec {
                name = "librime-lua";
                src = inputs.librime-lua;
                version = src.rev;
                propagatedBuildInputs = with pkgs; [ lua ];
                installPhase = ''
                  mkdir -p $out
                  cp -r * $out
                '';
              })
            ];
        };
      })
    ];
```

but iirc I got some issues compiling octagram, so it may require some patching or version update?

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/328396
