### ISSUE TITLE
Package request: `mpvScripts.thumbfast`

### ISSUE THREAD

**Issue by hab25** [NixOS/nixpkgs#231469]
**Project description**
From https://github.com/po5/thumbfast#:~:text=High%2Dperformance%20on,that%20calls%20thumbfast :
> High-performance on-the-fly thumbnailer for mpv.
> The script does not display thumbnails on its own, it is meant to be used alongside a UI script that calls thumbfast.

**Metadata**

* homepage URL: https://github.com/po5/thumbfast
* source URL: https://github.com/po5/thumbfast
* license: unspecified (?)
* platforms: linux,darwin,windows

**Note**

The already packaged `mpvScripts.uosc` (maintained by @apfelkuchen6) can use this and prominently mentions it in its README, perhaps `mpvScripts.uosc` should include `mpvScripts.thumbfast` in its own packaging (by default)?

**Comment by apfelkuchen6** [comment]
Closed by #231474.
