### ISSUE TITLE
NixOS Stage 1 failure when booting 22.11.4091.a08e061a4ee-x86_64 isos

### ISSUE THREAD

**Issue by wiryfuture** [NixOS/nixpkgs#231559]
### Describe the bug
The ISO image does not get past stage one for the gnome image or the kde image, with the message "cannot open blockdev ... unable to read id index table". The gnome iso provides an extra two lines about IO errors that the KDE iso does not.
The gnome one shows that it stops at sector 4597130 consistently.

### Steps To Reproduce
1. Boot either iso image off a usb
2. Select normal boot
3. wait

### Expected behavior
Continue to stage 2

### Screenshots
Gnome iso:
![IMG_20230513_012019a](https://github.com/NixOS/nixpkgs/assets/50517631/dc151744-e33d-42c1-9746-28756839bd80)
Kde iso:
![IMG_20230513_012019](https://github.com/NixOS/nixpkgs/assets/50517631/3d734666-1da3-4887-918d-02430e8060ea)

### Additional context
The laptop im testing this on is already running NixOS so it's not the laptop being funky.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by liketechnik** [comment]
Not sure if it's helpful, but anyway:

1. In a VM, I can successfully boot the (Gnome-)ISO.
2. The blockdev error seems unrelated, it occurs even on a successful boot: 
![grafik](https://github.com/NixOS/nixpkgs/assets/24209689/2099f2ab-67a1-467b-a583-9c508fadf523)
3. Just to make sure: Did you verify the hash of the .iso-File after download? ([gnome](https://releases.nixos.org/nixos/22.11/nixos-22.11.4091.a08e061a4ee/nixos-gnome-22.11.4091.a08e061a4ee-x86_64-linux.iso.sha256), [plasma](https://releases.nixos.org/nixos/22.11/nixos-22.11.4091.a08e061a4ee/nixos-plasma5-22.11.4091.a08e061a4ee-x86_64-linux.iso.sha256)) Or try with another USB?

**Comment by wiryfuture** [comment]
> Not sure if it's helpful, but anyway:
> 
>     1. In a VM, I can successfully boot the (Gnome-)ISO.
> 
>     2. The blockdev error seems unrelated, it occurs even on a successful boot:
>        ![grafik](https://user-images.githubusercontent.com/24209689/238119604-2099f2ab-67a1-467b-a583-9c508fadf523.png)
> 
>     3. Just to make sure: Did you verify the hash of the .iso-File after download? ([gnome](https://releases.nixos.org/nixos/22.11/nixos-22.11.4091.a08e061a4ee/nixos-gnome-22.11.4091.a08e061a4ee-x86_64-linux.iso.sha256), [plasma](https://releases.nixos.org/nixos/22.11/nixos-22.11.4091.a08e061a4ee/nixos-plasma5-22.11.4091.a08e061a4ee-x86_64-linux.iso.sha256)) Or try with another USB?

I forgot to verify the hashes 🤦 they're both different
My bad, I didn't think of doing it because I downloaded them multiple times. I downloaded them again today and they are working fine.

On a side note, do the links at [nixos.org](https://channels.nixos.org) use multiple storage locations? Sometimes I get a very fast download of >110MB/s, but often it's only about 5MB/s, like I'm sometimes hitting a cache but mostly I'm not.
