### ISSUE TITLE
Plasma 5: cannot disable kwallet

### ISSUE THREAD

**Issue by adfaure** [NixOS/nixpkgs#23156]
## Issue description
When using plasma 5, there is no way to disable kwallet.

* kwalletmanager is not available by default.

* And once installed (`nix-env -i kwalletmanager`), it is not possible to launch it as root so the configuration cannot be updated. 

>KDE Wallet Configuration
>You are not allowed to save the configuration

### Steps to reproduce

In configuration.nix:
```
services.xserver.desktopManager.kde5.enable = true;
```

Then try to enter a password somewhere (wifi, git push etc...).

## Technical details

```
$ nixos-version
16.09.1694.019dcc3 (Flounder)
```
```
nix-env --version
nix-env (Nix) 1.11.6
```
```
[adfaure@nixos:~]$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.1694.019dcc3"
```

Thank you very much.

**Comment by ttuegel** [comment]
If you want to run it as root, install it system-wide, or as root.

**Comment by adfaure** [comment]
Which I did, but root user is not allowed to login with the desktop manager.
