### ISSUE TITLE
Update request: cdesktopenv 2.3.2 → 2.5.1

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NixOS/nixpkgs#231519]
- Package name: cdesktopenv
- Latest released version: 2.5.1

- Current version on the unstable channel: 2.3.2
- Current version on the stable/release channel: 2.3.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mweinelt

There is no maintainers, but mweinelt last edited this package (excluding treewide edits)

This package fails to build on unstable (897876e4c484f1e8f92009fd11b7d988a121a4e7) and master (587ac4e842be36ca36900c6f3b0343b7e01117a6), but building fine on release-22.11 (062061744fcf9cedb11a9e2d2198ef0adfbd516f)

Also, upstream switched from imake to autotools, this might make it easier to build (ig)

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by mweinelt** [comment]
Fixing the build with libxcrypt was part of a treewide effort. I have no relation with that package.

**Comment by pinpox** [comment]
2.5.1 is in [unstable already](https://github.com/NixOS/nixpkgs/blob/91a22f76cd1716f9d0149e8a5c68424bb691de15/pkgs/desktops/cdesktopenv/default.nix#L12-L15)
