### ISSUE TITLE
Build failure: pkgsMusl.haskellPackages.foldl

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#231653]
### Steps To Reproduce

1. build `pkgsMusl.haskellPackages.foldl`

### Build log

https://termbin.com/bafh

### Additional context

maybe similar to issues we had in the past with libxcrypt?

### Notify maintainers

pinging mostly musl people here

@alyssais @superherointj

### Metadata

nixpkgs c56f804721f9c47a51ae41ef94df7000165493c5

**Comment by yu-re-ka** [comment]
Possibly related: https://bbs.archlinux.org/viewtopic.php?id=282429

**Comment by yu-re-ka** [comment]
Same failure case for pkgsMusl.haskellPackages.iproute. host kernel is 6.1.27

**Comment by yu-re-ka** [comment]
with the ghc94 packageset it semes to work

**Comment by cdepillabout** [comment]
Thanks for the report.

Since it sounds like this is kernel related, I'm closing in favor of #231216.
