### ISSUE TITLE
Update request: libopus 1.3.1 → 1.4

### ISSUE THREAD

**Issue by tsjnachos117** [NixOS/nixpkgs#231613]
- Package name: libopus
- Latest released version: 1.4

- Current version on the unstable channel: 1.3.1
- Current version on the stable/release channel: 1.3.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

Please update this (at least in the unstable channel) and release a version of opusTools with the new lib. Thanks.

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/231772
