### ISSUE TITLE
retroarch/libretro-mednafen-*: Rename packages

### ISSUE THREAD

**Issue by mednafen** [NixOS/nixpkgs#23163]
Please rename the libretro-mednafen-* cores packages to libretro-beetle-* or similar; the RetroArch/libretro project does not have permission nor blessings to use "Mednafen" branding for their forks, and have been cooperative in renaming the cores in light of this.

**Comment by joachifm** [comment]
cc @hrdinka

**Comment by hrdinka** [comment]
Superseded by #23176.
