### ISSUE TITLE
initrd lacks crypto module?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#23166]
## Issue description

On one of my devices, I'm not able to boot newer generations:

![img_20170224_193515](https://cloud.githubusercontent.com/assets/427866/23330190/16c7dd86-fb48-11e6-8f9c-e02ffb434971.jpg)

As it seems there is a crypto module missing in the kernel. On my other device it works, tough! I have 

```nix
boot.initrd.luks.cryptoModules = [ "aes" "sha256" "sha1" "cbc" "xts" ]
```

in my `configuration.nix".

## Technical details

* 17.03pre100896.4450327 (Gorilla)
* nix-env (Nix) 1.11.6
* "17.03pre101839.53a2baa"

**Comment by matthiasbeyer** [comment]
Okay, not things get funny: I tried to rebuild my system with the kernel not set to `linuxPackages_latest`, but `linuxPackages_4_9` and things work as expected.

Could it be that the kernel configuration changed and things are not longer included? But that could almost not be, as the kernel is not even loaded at that point - is it?

---

Pinging kernel people here: @shlevy @NeQuissimus @fpletz

**Comment by shlevy** [comment]
I didn't change the kernel config when I added 4.10 and don't know why this issue might be happening, but I am currently debugging an issue where my laptop freezes on resume in 4.10 but not 4.9 :grinning:

**Comment by shlevy** [comment]
Can you see the modules in your intird?

**Comment by shlevy** [comment]
The kernel absolutely is loaded at that point, though. The kernel is the thing that mounts the intrd.

**Comment by NeQuissimus** [comment]
I don't have any more insight into this, sorry.
I don't see any changes in 4.10 that would do this to you...

However, @shlevy, it seems `CPU_NOTIFIER_ERROR_INJECT` is gone in 4.10. When you build the config, it prints the following:

```
warning: unused option: CPU_NOTIFIER_ERROR_INJECT
```

That should not cause any issue with the crypto modules, just noticed it when I built 4.10.

**Comment by matthiasbeyer** [comment]
> Can you see the modules in your intird?

How to do this?

> The kernel absolutely is loaded at that point, though. The kernel is the thing that mounts the intrd.

Meh, I messed this up, had 4 hours sleep after a long party night when I filed this issue, sorry! :smile: :tada:

**Comment by Mic92** [comment]
@matthiasbeyer do you also use something like: `luks.devices = [ { name = "root"; device = "/dev/sda2"; } ];` ?

**Comment by matthiasbeyer** [comment]
@Mic92 Yes, here's my filesystem configuration:

```nix
  boot.kernelParams = [
    "cryptodisk=/dev/sda1"
  ];

  boot.initrd.luks.devices = [ 
    { device = "/dev/sda2"; name = "nixos-root"; }
    { device = "/dev/sda3"; name = "nixos-home"; }
  ];

  fileSystems."/boot" = {
    mountPoint = "/boot";
    device = "/dev/sda1";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/mapper/nixos-root";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/nixos-home";
    fsType = "ext4";
  };

```

It did **not** change between 4.9 and 4.10, though.

**Comment by matthiasbeyer** [comment]
I do not have this problem anymore. I don't know why.
