### ISSUE TITLE
calibre not working

### ISSUE THREAD

**Issue by 7c78** [NixOS/nixpkgs#231692]
### Describe the bug
Calibre does not work.

### Steps To Reproduce
Run `nix-shell -p calibre --run calibre`.
Error:
```
(process:23645): Gtk-WARNING **: 12:04:15.697: Locale not supported by C library.
	Using the fallback 'C' locale.
...
Could not initialize GLX
/tmp/nix-shell-19984-0/rc: line 3: 23645 Aborted                 (core dumped) calibre
```

### Notify maintainers

@kilianar @AndersonTorres 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.14-300.fc38.x86_64, Fedora Linux, 38 (Xfce), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by bobby285271** [comment]
Have you tried `export QT_XCB_GL_INTEGRATION=none` as [suggested here](https://github.com/NixOS/nixpkgs/issues/82959#issuecomment-657306112)?

**Comment by 7c78** [comment]
> Have you tried `export QT_XCB_GL_INTEGRATION=none` as [suggested here](https://github.com/NixOS/nixpkgs/issues/82959#issuecomment-657306112)?

Thanks. I try and it works.
