### ISSUE TITLE
emacs coredumps after update

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#23160]
## Issue description
I have just updated from the unstable channel and emacs coredumps

### Steps to reproduce
emacs

** (emacs:6376): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .ser
vice files
Fontconfig warning: line 142: blank doesn't take any effect anymore. please remove it from your fonts.conf

(emacs:6376): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion 'source != NULL' failed
X protocol error: BadRequest (invalid request code or no such operation) on protocol request 131
When compiled with GTK, Emacs cannot recover from X disconnects.
This is a GTK bug: https://bugzilla.gnome.org/show_bug.cgi?id=85715
For details, see etc/PROBLEMS.
.....

## Technical details

* System: lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.8 (Santiago)
Release:        6.8
Codename:       Santiago

* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "16.09pre90254.6b20d5b"

**Comment by alexvorobiev** [comment]
I wonder if it is caused by the switch to Gtk3 in https://github.com/NixOS/nixpkgs/commit/bc6b91710033bfcda7f98d9baf4118db938fd2d7

**Comment by alexvorobiev** [comment]
Apparently the reason is some kind of incompatibility between Gtk3 build of emacs and x2go I use to access the server where emacs is installed. The issue has bug reports https://bugzilla.redhat.com/show_bug.cgi?id=1349412 and https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24280 with no solution other than build with Gtk2. I have added this to my config.nix:
```
emacs-gtk2 = lowPrio (appendToName "gtk2" (emacs25.override {
        withGTK2 = true;
        withGTK3 = false;
}));
```

and emacs works again over the x2go connection. I wonder if the snippet should be added to nixpkgs so that there is an easy workaround for others with this problem.

**Comment by AndersonTorres** [comment]
I think that error is more common. I have the same problem now with VirtualBox.

**Comment by AndersonTorres** [comment]
The same type of erros is going on Calibre on unstable.
I have changed to Stable and now everything is fine.

**Comment by vmandela** [comment]
I see the same issue with nixpkgs on Ubuntu 16.04 when using NXClient to connect remotely to my desktop.

**Comment by AndersonTorres** [comment]
It was solved? After all, I have noted a strange pattern: when I use XFCE, calibre fails with the same type of error, but in KDE it opens the file dialog normally.

**Comment by Ekleog** [comment]
(triage) does anyone still see the same issue?

**Comment by Ekleog** [comment]
Let's close, then, and if someone sees that again we can reopen :)
