### ISSUE TITLE
Documentation: Breaking erdtree update not documented

### ISSUE THREAD

**Issue by Infinidoge** [NixOS/nixpkgs#231882]
## Problem

The update to erdtree found in #228335 has a number of breaking changes, which was not documented in the release notes, etc.

## Proposal

Document the breaking changes in the release notes.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by figsoda** [comment]
but erdtree was not present in the last release

**Comment by Infinidoge** [comment]
Huh. Apparently so. Nevermind then!
