### ISSUE TITLE
Package request: mcpelauncher

### ISSUE THREAD

**Issue by dch82** [NixOS/nixpkgs#231875]
**Project description**

An unofficial launcher for Minecraft Bedrock Edition

**Metadata**

* homepage URL: [https://mcpelauncher.readthedocs.io](https://mcpelauncher.readthedocs.io)
* source URL: [https://github.com/minecraft-linux/mcpelauncher-manifest](https://github.com/minecraft-linux/mcpelauncher-manifest)
* license: GPL 3.0
* platforms: Linux and Darwin

**Comment by Aleksanaa** [comment]
Working on it

**Comment by dashfader** [comment]
Any chance re-doing this? I think it's been a while since the login issue is fixed in newer version of the launcher

**Comment by atarashiryo** [comment]
plz

**Comment by WewDuck** [comment]
I assume that nobody is working on this anymore? The latest versions have been working without any issue under Gentoo for me

**Comment by dch82** [comment]
I'm going to be looking at this to see if I can do anything about it.

**Comment by Morxemplum** [comment]
Good news guys! I managed to get mcpelauncher-client working on NixOS. I just need to work on getting the Qt Launcher working optimally, and then upgrading both the client and launcher to Qt6. Some additional testing is gonna be needed ofc, but this is very promising.

https://www.youtube.com/watch?v=lRI5yo3USeI
