### ISSUE TITLE
How to mount a USB-connected Android device

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#23186]
This is a pretty common desktop-computer-user thing to want to do, so it'd be nice if we included some documentation. At present, the NixOS manual does not mention the word "Android" anywhere.

I've never gotten this working in NixOS. Anyone else have any luck?

**Comment by 7c6f434c** [comment]
I think at some point I installed go-mptfs, did a mount and it happenned
to work.

Normally I don't do that, though, normally I just SSH into the phone.

**Comment by Mic92** [comment]
Just successfully tested go-mtpfs:

```
$ mkdir ~/mnt && go-mtpfs ~/mnt
```

There is also an adb module in nixos now, which installs udev rules to use adb as user.

**Comment by chris-martin** [comment]
I'm getting a whole lot of

    detect failed: no MTP devices found

Normally when I plug my phone into a computer, I get this notification

![screenshot_20170225-175741](https://cloud.githubusercontent.com/assets/399718/23335470/3f4dec5a-fb84-11e6-8d7e-0ebdb2161597.png)

And then when I tap that, Android gives me some options, and one of them is enabling MTP.

Can we make *that* happen?

**Comment by chris-martin** [comment]
Oh, my mistake, this actually does work out of-the-box on NixOS, no configuration needed at all.

The problem is that it doesn't work over USB type-C. If I connect the device via an adapter to type-A, then it works.

So I'm not sure anymore, is this a bug or not? The only machine I have with a type-C port is running NixOS, so I don't have anything else to test with at the moment.

**Comment by 7c6f434c** [comment]
>The only machine I have with a type-C port is running NixOS, so I don't have anything else to test with at the moment. 

I would start by comparing dmesg output for two types of connection.

Also, what device nodes are created? Is anything added in /dev/bus/usb
in the type-C case?

Also, I have just recently observed a faulty cable that would work via
USB2 and fail via USB3, probably because of something wrong done with
USB3-only wires.

**Comment by castilma** [comment]
@chris-martin it does not work for me automatically. I have xfce4 installed. android devices (maybe all mtp devices) don't show up in thunar on the left(until i mount it). i can mount it with jmtpfs, but have problems with that.(unreliable with big files, hangs). 
I do not have gvfs-mtp and don't know where to get that command from. maybe that is the issue for xfce/thunar. `gvfs-mount -li` does not list my phone.

any hints to get thunar to list unmounted mtp devices?

**Comment by leo60228** [comment]
@7c6f434c No change happens in /dev/bus/usb, I don't have a USB-A to C cable to test that. My phone charges but nothing else.

**Comment by 7c6f434c** [comment]
Maybe the user account doesn't have the right to access the root-owned USB node?

**Comment by fgaz** [comment]
@7c6f434c 
Thanks, that was it. `sudo go-mtpfs /mnt` works (`mtpfs` gives me some protocol error).

**Comment by castilma** [comment]
Am 6. August 2018 11:42:03 MESZ schrieb Francesco Gazzetta <notifications@github.com>:
>@7c6f434c 
>Thanks, that was it. `sudo go-mtpfs /mnt` works (`mtpfs` gives me some
>protocol error).

Does adding your user to the plugdev group make it work without sudo?

**Comment by fgaz** [comment]
@castilma nope

**Comment by leo60228** [comment]
Nowadays this seems to Just Work\™ in KDE. Not sure about other DEs, and I think it might be using ADB (which would reduce its usefulness for most people).

**Comment by Mic92** [comment]
There is also adbfs-rootless, which might help.

**Comment by Mic92** [comment]
I am going to close this issue because we provided several methods on how to mount devices using MTP. If somebody has a more concrete bug, where this breaks in a particular configuration where it should work, please open a new one.
