### ISSUE TITLE
Package request: sfwbar

### ISSUE THREAD

**Issue by clemencyworld1** [NixOS/nixpkgs#231995]
**Project description**
SFWBar (S* Floating Window Bar) is a flexible taskbar application for wayland compositors, designed with a stacking layout in mind.

**Metadata**

* homepage URL:https://github.com/LBCrion/sfwbar
* source URL:https://github.com/LBCrion/sfwbar/archive/refs/tags/v1.0_beta11.tar.gz
* license: GPL-3.0
* platforms: unix, linux

**Comment by NotAShelf** [comment]
I'll take a look at this.

**Comment by guzz46** [comment]
Would it be possible to get this updated to version 1.0_beta14
Beta 14 has been out since Jan 2, unstable still only has beta 13
Thanks

**Comment by NotAShelf** [comment]
Please don't bump closed threads for update requests, the correct way would be to open an out of date package report in [issues](https://github.com/NixOS/nixpkgs/issues/new/choose)
