### ISSUE TITLE
Steam fails to find Steam directory if user moves it.

### ISSUE THREAD

**Issue by cmason37** [NixOS/nixpkgs#23198]
## Issue description

If the user moves their Steam directory (usually `$HOME/.local/share/Steam`) Steam will show the usual dialog with the buttons "Reinstall" & "Search".  However, if the user clicks "Search" so they can point Steam to their real Steam directory, the box will just close & the error `(zenity:<pid-of-zenity-before-it-crashed>): GLib-GIO-ERROR **: No GSettings schemas are installed on the system`

A workaround I found while digging through Steam's files is to manually set all broken symlinks under `$HOME/.steam/` & `$HOME/.steampath` to a valid steam directory, which "reinstalls" Steam.

### Steps to reproduce

1. Move Steam directory
2. Start Steam
3. Click "Search"
4. Watch Steam crash.

## Technical details

* System: 17.03pre101839.53a2baa (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03pre101839.53a2baa

**Comment by abbradar** [comment]
Can you try it with https://github.com/abbradar/nixpkgs/commit/ce6b2ed12fd14b2a2c2dba7f18cf2b1b837b2196?

**Comment by abbradar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/a381ee89cda19dc074753cee2d2c940c657c958d
