### ISSUE TITLE
Failed assertions: `security.pam.zfs.enable` requires enabling ZFS

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#232014]
### Describe the bug

Just tried to update my system and ran into:

```
       Failed assertions:
       - `security.pam.zfs.enable` requires enabling ZFS (`boot.zfs.enabled` or `boot.zfs.enableUnstable`).
```

Presumably related to https://github.com/NixOS/nixpkgs/pull/228956 ?

### Notify maintainers

@tensor5 @RaitoBezarius 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1, NixOS, 23.05 (Stoat), 23.05.20230509.6868845`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(frijters): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by RaitoBezarius** [comment]
Fixing in one minute.

**Comment by tensor5** [comment]
[The assertion](https://github.com/tensor5/nixpkgs/blob/d0f5d41b23cb9fe2ef0ec61059386b494fd54481/nixos/modules/security/pam.nix#L1290) should use the `->` operator, not `&&`.

**Comment by kirillrdy** [comment]
@RaitoBezarius thank you for addressing this so quickly.

How many people run zfs on root ?

**Comment by RaitoBezarius** [comment]
> How many people run zfs on root ?

We have a small userbase but non trivial because I get a lot of activity I imagine.
