### ISSUE TITLE
glibc linking issues

### ISSUE THREAD

**Issue by gigavinyl** [NixOS/nixpkgs#23203]
## Issue description
For some reason, status bar applications (bar-xft and dzen2, specifically) output errors like this:
```bash
lemonbar: relocation error: /nix/store/amjgskg17wv125v9kahqdfxh8sx6mxgp-glibc-2.24/lib/libpthread.so.0: symbol __libc_dl_error_tsd, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```
Installing glibc locally and running bar or dzen2 seems to solve the problem. However, this causes basic utilities like clear to output garbage, seemingly random errors with random unicode symbols. Installing glibc globally fixes the issue. I have to do this every time I reboot my computer.

### Steps to reproduce
1. Install bar-xft and use zsh as the user's shell.
2. Attempt to launch bar-xft (or "lemonbar") and receive the error.
3. `nix-shell -i glibc`
4. Launch bar.
5. Try running 'clear' and see a random spaghetti error.
6. Add "glibc" to /etc/nixos/configuration.
7. `sudo nixos-rebuild --upgrade`
8. Profit? But not really because I have to jump through these hoops every time I start my computer.

## Technical details

* System: 17.03pre101839.53a2baa (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03pre101839.53a2baa

**Comment by vcunat** [comment]
That's strange.  Are you doing some `LD_LIBRARY_PATH` or `LD_PRELOAD`?  I don't understand why adding `glibc` to `systemPackages` should change anything.

**Comment by gigavinyl** [comment]
@vcunat Oh shoot that was it. I was adding "${HOME}/.nix-profile/lib" to "LD_LIBRARY_PATH" in my `.zshrc` when I was testing the Alacritty terminal (which I didn't end up using due to its issues with bitmap fonts). Removing this from my "LD_LIBRARY_PATH" solved the issue. Thanks :smile:

**Comment by vcunat** [comment]
I tend to override such variables only for specific programs or in specific shell instances that I don't use generally...
