### ISSUE TITLE
vim: `update.py add` doesn't add the plugins to `generated.nix`

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#232078]
### Describe the bug

probably introduced in https://github.com/NixOS/nixpkgs/pull/223164

Just to let people know that I am working on a fix, I will get it done before release but a proper fix is more complex than it seems.

cc @figsoda

**Comment by teto** [comment]
This is a pain for many contributors, including myself. Sorry for that. 
I've met many problems running the different updaters and would really like to be able to add plugins without updating all of them. I'd started something for vim. fixing cache bugs along with it but it got out of hands and haven't touched this in last 4 months.

I was thinking of using pytreesitter to parse the AST, check if a node exists and if the update fails, you could just copy/paste the content of the old node ? Ofc you could also sed/grep stuff but nothing I can think of looks like a clear win.

**Comment by figsoda** [comment]
Maybe the update script can evaluate the generated file into a structure (which it then can regenerate the same exact file), and to add a single plugin without updating the rest, it just needs to add to the structure and generate the new file.

Another option is to adopt json, which should be a lot faster to parse (compared to evaluating nix code), but it would require a little more indirection on the nix side

**Comment by teto** [comment]
I htink fixed by @PerchunPak
