### ISSUE TITLE
neovide couldn't be launched by a desktop launcher in sway-wm

### ISSUE THREAD

**Issue by Zaplae** [NixOS/nixpkgs#232030]
### Describe the bug
See title, but it could be launched in terminal(type `neovide`), or in desktop launcher(`rofi/wofi/fuzzel`) which was opend in terminal

### Steps To Reproduce
1. add `neovide` into `environment.systemPackages` (in `/etc/nixos/configuration.nix`)
2. open a launcher like `rofi/wofi/fuzzel` and type `neovide` 
(Notice: the launcher should be opend by keybinding, if you oepn the launcher in terminal and type `neovide`, it could be successful )

### Expected behavior
See `neovide` launched

### Notify maintainers
@ck3d 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.27, NixOS, 23.05 (Stoat), 23.05pre481202.3e313808bd2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(jedsek): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
have you tried from terminal ? that might be due to a crash. checkout `journalctl -r` . Neovide crashes here

**Comment by teto** [comment]
@alexjp have you tried yourself ? I would love to see a flake land in neovide ^^''

**Comment by alexjp** [comment]
> @alexjp have you tried yourself ? I would love to see a flake land in neovide ^^''

yes, there has been a branch of `new-keyboard-v3` ( or similar name ) and has been working fine.

recently, they merged the work to main branch.

**Comment by Nairou** [comment]
neovide just released 0.11, release notes say wayland support was added. Really interested to test it out.

**Comment by alexjp** [comment]
> neovide just released 0.11, release notes say wayland support was added. Really interested to test it out.

Nice ! just tested it, so far, is working really good!

You can test it right away by either running the `appimage` or building it with cargo, with the help of `steam-run`

**Comment by Nairou** [comment]
> Nice ! just tested it, so far, is working really good!
> 
> You can test it right away by either running the `appimage` or building it with `cargo`, with the help of `steam-run`

Good to know!

I was trying to take a stab at updating nixpkgs, but haven't succeeded so far (`rust-skia` errors).

**Comment by mightyiam** [comment]
#247822

**Comment by teto** [comment]
tested here and it worked fine. Closing then. Feel free to reopen
