### ISSUE TITLE
nvim-treesitter grammars are not built by Hydra

### ISSUE THREAD

**Issue by hesiod** [NixOS/nixpkgs#232190]
### Describe the bug
Background: `nvim-treesitter` requires specific versions of tree-sitter grammars (see issue #147420), therefore `nvim-treesitter.{builtGrammars,withAllGramars}` was split from `tree-sitter-grammars`/`tree-sitter.{builtGrammars,withAllGramars}` in PR #198606.

However, while grammars in `tree-sitter-grammars` are built by Hydra, `nvim-treesitter` grammars are not. When using a lot of grammars or even `withAllGramars`, the grammars can take a while to build.

### Steps To Reproduce
Check Hydra status of any `nvim-treesitter` grammar (e.g. using hydra-check):
```console
$ nix run nixpkgs#hydra-check -- vimPlugins.nvim-treesitter.builtGrammars.json
Build Status for nixpkgs.vimPlugins.nvim-treesitter.builtGrammars.json.x86_64-linux on unstable
⚠ This job is not a member of the latest evaluation of its jobset. This means it was removed or had an evaluation error.
```

### Expected behavior
They should be built by Hydra, same as grammars in `tree-sitter-grammars`:
```console
$ nix run nixpkgs#hydra-check -- tree-sitter-grammars.tree-sitter-json
Build Status for nixpkgs.tree-sitter-grammars.tree-sitter-json.x86_64-linux on unstable
✔ tree-sitter-json-grammar-0.20.8 from 2023-05-14 - https://hydra.nixos.org/build/219706694
```

### Notify maintainers

@figsoda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - (`nix-info` did not actually terminate, it's stuck building some `diagnostics-multiuser` derivation, perhaps this is because I have remote builders enabled by default?)

**Comment by figsoda** [comment]
#232253
