### ISSUE TITLE
Support custom keybindings

### ISSUE THREAD

**Issue by TomSmeets** [NixOS/nixpkgs#23213]
# Problem
Defining custom keybindings requires the creation of two separate mapping files for the `virtual-console` and the `xserver`.

# Solution
A uniform way to define keybindings inside `configuration.nix`.
These should then be converted and loaded by both `kbd` and `xmodmap` (xserver).

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by TomSmeets** [comment]
No updates here, I've never implemented this. (But it shouldn't be that hard)

**Comment by TomSmeets** [comment]
This might be out of scope for NixOS.
Closing for now, but feel free to continue any discussion here.
