### ISSUE TITLE
security-wrappers: default owner/group

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixpkgs#23217]
## Issue description

While creating a submodule definition for `security.wrappers` I noticed some strange behaviour with the owner/group of setuid wrappers. Depending on what attributes are defined, regardless if they have a default value the owner and group will change it's default to nobody:nogroup.

Is this expected, if not what should it be?

### Examples

```
  security.wrappers.foo = { ... };                            # u+s,g-s,u+rx,g+x,o+x root:root
  security.wrappers.foo = { setuid = true; };                 # u+s,g-s,u+rx,g+x,o+x nobody:nogroup (default)
  security.wrappers.foo = { setgid = true; };                 # u+s,g+s,u+rx,g+x,o+x root:root
  security.wrappers.foo = { permissions = "u+rx,g+x,o+x"; };  # u+rx,g+x,o+x nobody:nobody (default)
  security.wrappers.foo = { permissions = "u+rx,g-x,o-x"; };  # u+rx,g-x,o-x nobody:nobody
```

## Technical details

* System: (NixOS: 16.09)
* Nix version: (1.11.7)
* Nixpkgs version: (17.03pre-git)

**Comment by fpletz** [comment]
cc @globin @ixmatus @bjornfor

**Comment by bjornfor** [comment]
cc @edolstra :-)

(I assume root:root should be default, but I don't really know what I'm doing.)

**Comment by ixmatus** [comment]
I wrote this code. When I'm at a computer I'll look at this. Some of that behavior is legacy, some might be unexpected since we have one interface for both but the two have slightly different behavior.

**Comment by LnL7** [comment]
Note that this is indeed similar to the way `security.setuidPrograms` and `security.setuidOwners` currently interact with eachother.

**Comment by ixmatus** [comment]
@LnL7 did you create this in response to something breaking or is this an issue for tracking weird / inconsistent behavior we should fix ASAP but not critically for **17.03**? I'll tackle this probably this weekend but if it's breaking something or this is critical for 17.03 I can prioritize it higher.

**Comment by LnL7** [comment]
@ixmatus I don't think you have to do anything unless you have thoughts about it, nothing is broken because if this AFAIK.

The reason I wanted to convert the wrappers to a submodule is to improve the error messages (it's currently pretty hard to debug an invalid wrapper). I can implement the current behaviour, just want to make sure it's what we want.

**Comment by ixmatus** [comment]
@LnL7 okay I understand. I think some of that behavior (which was replicated from legacy code) could use tuning based on your above quoted example but without better integration tests of these components I'm reluctant to change that.

**Comment by rnhmjoj** [comment]
I'm in the process of improving the `security.wrappers` module and came upon this. Can we discuss a better default? The current behavior is surprising and also it's not clear what the motivations are.

Why are `nobody:nogroup` being used here? I think that using them outside of the original motivation (mapping uid/gid in nfs) is a misappropriation and a security concern. There is already an issue tracking their removel: https://github.com/NixOS/nixpkgs/issues/55370

**Comment by rnhmjoj** [comment]
With https://github.com/NixOS/nixpkgs/pull/126289 the default values are gone: so, no more surprising wrappers. It's now necessary to specify wether the wrapper is setuid/setgid, the owner and group.
