### ISSUE TITLE
udev-worker nvidia process failing on unstable

### ISSUE THREAD

**Issue by bddvlpr** [NixOS/nixpkgs#232286]
### Describe the bug
After migrating my dotfiles from [22.11](https://github.com/bddvlpr/nix-dotfiles) to [unstable](https://github.com/bddvlpr/nix-dotfiles/tree/migrate/unstable), my nvidia gpu stopped working after rebooting. I checked journalctl and found out the udev-worker process keeps failing.

### Steps To Reproduce
1. Checkout the [migration branch](https://github.com/bddvlpr/nix-dotfiles/tree/migrate/unstable) of my dotfiles or use [963006aab35e3e8ebbf6052b6bf4ea712fdd3c28](https://github.com/NixOS/nixpkgs/commit/963006aab35e3e8ebbf6052b6bf4ea712fdd3c28).
2. Add `services.xserver.videoDrivers = [ "nvidia" ];` and enable opengl. (see [nvidia.nix](https://github.com/bddvlpr/nix-dotfiles/blob/fcd875e59e2f637c374965fababa102ffdb7a8cd/hosts/common/nvidia.nix)).
3. Build the system configuration and reboot.

### Logs

```
May 16 18:53:39 dissension (udev-worker)[1307]: nvidia: Process '/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash -c 'mknod -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'' failed with exit code 1.
May 16 18:53:39 dissension (udev-worker)[1307]: nvidia: Process '/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash -c 'for i in $(cat /proc/driver/nvidia/gpus/*/information | grep Minor | cut -d \  -f 4); do mknod -m 666 /dev/nvidia${i} c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) ${i}; done'' failed with exit code 1.
```

Full log:
```
bddvlpr@dissension ~> journalctl -b | grep nvidia
May 16 18:53:39 dissension kernel: Command line: initrd=\efi\nixos\9cl47y8ikj0yma5an5mkwmr5miqgx8i0-initrd-linux-6.1.28-initrd.efi init=/nix/store/3y8hy5ykyshicldg7715cx2yql51m1is-nixos-system-dissension-23.05.20230516.963006a/init loglevel=4 nvidia-drm.modeset=1
May 16 18:53:39 dissension kernel: Kernel command line: initrd=\efi\nixos\9cl47y8ikj0yma5an5mkwmr5miqgx8i0-initrd-linux-6.1.28-initrd.efi init=/nix/store/3y8hy5ykyshicldg7715cx2yql51m1is-nixos-system-dissension-23.05.20230516.963006a/init loglevel=4 nvidia-drm.modeset=1
May 16 18:53:39 dissension stage-1-init: [Tue May 16 18:53:28 UTC 2023] loading module nvidia...
May 16 18:53:39 dissension kernel: nvidia: loading out-of-tree module taints kernel.
May 16 18:53:39 dissension kernel: nvidia: module license 'NVIDIA' taints kernel.
May 16 18:53:39 dissension kernel: nvidia-nvlink: Nvlink Core is being initialized, major device number 248
May 16 18:53:39 dissension kernel: nvidia 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
May 16 18:53:39 dissension kernel: nvidia_uvm: module uses symbols nvUvmInterfaceDisableAccessCntr from proprietary module nvidia, inheriting taint.
May 16 18:53:39 dissension kernel: nvidia-uvm: Loaded the UVM driver, major device number 241.
May 16 18:53:39 dissension systemd-modules-load[1250]: Inserted module 'nvidia_uvm'
May 16 18:53:39 dissension (udev-worker)[1307]: nvidia: Process '/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash -c 'mknod -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'' failed with exit code 1.
May 16 18:53:39 dissension (udev-worker)[1307]: nvidia: Process '/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash -c 'for i in $(cat /proc/driver/nvidia/gpus/*/information | grep Minor | cut -d \  -f 4); do mknod -m 666 /dev/nvidia${i} c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) ${i}; done'' failed with exit code 1.
May 16 18:53:39 dissension kernel: nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  530.41.03  Thu Mar 16 19:23:04 UTC 2023
May 16 18:53:39 dissension kernel: [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
May 16 18:53:40 dissension kernel: [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:01:00.0 on minor 0
```

### Metadata

```console
bddvlpr@dissension ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05.20230516.963006a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/w18hyx1dwk4pa591rjyv5g6w0ayf3qcz-source`
```

**Comment by Kiskae** [comment]
> found out the udev-worker process keeps failing.

The udev rules have a tendency to cause errors early during startup, but then complete successfully once the gpu gets bound to the driver. So unless that error keeps happening your issue lies elsewhere.

Try and see if the device file `/dev/nvidia0` exists. If it does then the udev rules worked as intended.

**Comment by bddvlpr** [comment]
Ah, my bad, `/dev/nvidia0` does exist. I've found out that when I open any hardware accelerated program, it fails to load a bunch of mesa drivers.

``` 
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /run/opengl-driver/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open zink: /run/opengl-driver/lib/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /run/opengl-driver/lib/dri, suffix _dri)
```

**Comment by bddvlpr** [comment]
Seems like this issue is a duplicate of #224332 now, so I'm closing it.

**Comment by Daholli** [comment]
I still have this in 24.11, and whenever this happens I have to reboot my system because it is lagging to hell, as soon as anything is trying to use the GPU e.g. steam precaching shaders 

everthing else seems to be fine, and for some reason it only ever happens on the first  boot, but there it happens very consistently. I would love to not have to start and instantly reboot my system to use it, but I am out of ideas what to do.

```
nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/d3dzfy4amjl826fb8j00qp1d9887h7hm-stdenv-linux
copying path '/nix/store/d3dzfy4amjl826fb8j00qp1d9887h7hm-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuna), 24.11.20240624.2893f56`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.23.0pre20240526_7de033d6`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
 ```

**Comment by bddvlpr** [comment]
I figured out that (one of) the issues was that the compositor was fighting over which card/driver to use, those being the integrated AMD card and the dedicated Nvidia card. After blocking the AMDGPU kernel module it seems to work fine now. Do you have a configuration to replicate the issue with?

**Comment by Daholli** [comment]
my config is in my profile, but doesnt the nvidiagpu module not automatically block the amdugpu module? I thoguht i remembered something like that when looking at it

should I put this in? but i thought that those only affects actual gpus and not the onboard
```
  boot.blacklistedKernelModules = [
    "amdgpu"
  ];
```
![neofetch](https://github.com/NixOS/nixpkgs/assets/25060097/8f206959-5961-429c-8516-edaacaad09af)

**Comment by bddvlpr** [comment]
I don't think it'll auto-block but it should be turned off by default as far as I can tell, try running nvtop and see if it detects both GPU's or just the Nvidia one.

![image](https://github.com/NixOS/nixpkgs/assets/17461028/699ab6b5-b16b-4e84-868e-504a981b17d9)

What helped a lot as well, in my case, was using [nixos-hardware](https://github.com/nixos/nixos-hardware) for all the hardware niche stuff. [For example check out the following.](https://github.com/bddvlpr/resonance/blob/ac6058081b6f57562de970c28b51db893ec836fc/systems/dissension/hardware.nix#L2-L5)
```nix
  imports = with inputs.hardware.nixosModules; [
    common-pc-ssd
    common-cpu-amd
    common-gpu-nvidia-nonprime
  ];
  ```

**Comment by Daholli** [comment]
Thanks a lot for the advice! it seems like the udev thing still fails occasionally, but at least the lagging is gone from what i can tell at this point in time!

**Comment by wwevo** [comment]
I do not have a second or integrated GPU, but still the exact same behavior as the OP.

Process '/nix/store/gwgqdl0242ymlikq9s9s62gkp5cvyal3-bash-5.2p37/bin/bash -c 'mknod -m 666 /dev/nvidiactl c 195 255'' failed with exit code 1. Only some of the time, but mostly on first boot.

24.11 up-to-date and no fancy config.
