### ISSUE TITLE
Package request: SpotiFlyer

### ISSUE THREAD

**Issue by YorQat** [NixOS/nixpkgs#232315]
**Project description**

Kotlin Multiplatform Music Downloader ,supports Spotify, Youtube, Gaana, Jio-Saavn and SoundCloud.

**Metadata**

* homepage URL: https://github.com/Shabinder/SpotiFlyer
* source URL: https://github.com/Shabinder/SpotiFlyer
* license: gpl3
* platforms: unix, linux, darwin

**Comment by nim65s** [comment]
This is a duplicate of #213630
