### ISSUE TITLE
Case-sensitive SSH settings in NixOS unstable can create misleading sshd config

### ISSUE THREAD

**Issue by panchoh** [NixOS/nixpkgs#232386]
### Describe the bug
Upon migrating from NixOS 22.11 to the current unstable release (soon to be 23.05), the OpenSSH service settings for password and keyboard-interactive authentication have changed. This transition requires case-sensitive adjustments that, if not properly made, can lead to a misleading and potentially insecure `sshd` configuration file.

Here are some of the settings that have been moved since the 22.11 release (but there are [more](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/networking/ssh/sshd.nix#L103-L112)):

| NixOS 22.11 | NixOS unstable |
|---|---|
| `services.openssh.passwordAuthentication` | `services.openssh.settings.PasswordAuthentication` |
| `services.openssh.kbdInteractiveAuthentication` | `services.openssh.settings.KbdInteractiveAuthentication` |

Say that both settings were set to `false`.
If the case of these settings is not adjusted properly when migrating, NixOS does not provide any warning or error during the rebuild process. The resulting `sshd` config file contains both the default (`true/yes`) and user-specified settings (`false/no`), with the first one (undesired in this case) taking precedence due to its position in the file. This results in an `sshd` config file that essentially contains:

```
...
PasswordAuthentication yes
passwordAuthentication no
KbdInteractiveAuthentication yes
kbdInteractiveAuthentication no
...
```

### Steps To Reproduce
1. In NixOS 22.11, set `service.openssh.passwordAuthentication` and/or `service.openssh.kbdInteractiveAuthentication` to `false`.
2. Migrate to the current unstable release of nixpkgs.
3. Move these settings to `services.openssh.settings.passwordAuthentication` and `services.openssh.settings.kbdInteractiveAuthentication`, but do not adjust the case.
4. Run `nixos-rebuild switch`.
5. Examine the resulting sshd config file, `/etc/ssh/sshd_config`
6. Access the host via `ssh` and see how it allows you to enter a password to authenticate.
7. Weep.

### Expected behavior
When migrating and adjusting these settings, NixOS should provide an error if the case is not correctly adjusted. This would be similar to the error NixOS emits when you try to add a non-existent setting, such as `services.openssh.settings.MadeUpSettingThatAsExpectedIsNotSilentlyIgnored`.

### Screenshots
N/A

### Additional context
This is a problem because for `sshd`, the parameters are:
a) case insensitive
b) the first occurrence fixes the value
otherwise, `sshd` would croak and we would know that something broke.

### Notify maintainers
@teto @tokudan @infinisil @pennae

### Metadata
```console
[pancho@helium:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.2, NixOS, 23.05 (Stoat), 23.05.20230516.963006a`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `not found`
 
[pancho@helium~]$ nix flake metadata /etc/nixos
Resolved URL:  git+file:///etc/nixos
Locked URL:    git+file:///etc/nixos
Description:   Port of archify to NixOS + flakes + Home Manager.
Path:          /nix/store/m96s4rsnzx19ncgfs7glx3ayddshw54s-source
Last modified: 2023-05-17 07:30:40
Inputs:
├───disko: github:nix-community/disko/10402e31443941b50bf62e67900743dcb26b3b27
│   └───nixpkgs follows input 'nixpkgs'
├───emacs-overlay: github:nix-community/emacs-overlay/016a781cc93d3c7f7005b6ba12f667e9861056e0
│   ├───flake-utils: github:numtide/flake-utils/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
│   └───nixpkgs follows input 'nixpkgs'
├───home-manager: github:nix-community/home-manager/b7d814c5744dca7e70b3dc2638f06568dce96ca6
│   └───nixpkgs follows input 'nixpkgs'
├───hyprland: github:hyprwm/Hyprland/642030f959efe7bd2692bf6a4236d4c1b39ee51a
│   ├───hyprland-protocols: github:hyprwm/hyprland-protocols/4d29e48433270a2af06b8bc711ca1fe5109746cd
│   │   └───nixpkgs follows input 'hyprland/nixpkgs'
│   ├───nixpkgs follows input 'nixpkgs'
│   ├───wlroots: gitlab:wlroots/wlroots/6830bfc17fd94709e2cdd4da0af989f102a26e59
│   └───xdph: github:hyprwm/xdg-desktop-portal-hyprland/c0e233955568fbea4e859336f6d3d14d51294d7c
│       ├───hyprland-protocols follows input 'hyprland/hyprland-protocols'
│       └───nixpkgs follows input 'hyprland/nixpkgs'
├───nix-index-database: github:Mic92/nix-index-database/219067a5e3cf4b9581c8b4fcfc59ecd5af953d07
│   └───nixpkgs follows input 'nixpkgs'
├───nixos-hardware: github:NixOS/nixos-hardware/71ce85372a614d418d5e303dd5702a79d1545c04
├───nixpkgs: github:NixOS/nixpkgs/963006aab35e3e8ebbf6052b6bf4ea712fdd3c28
└───stylix: github:danth/stylix/a9367cea1bdc0ad35b3b0b2afc4aa9cf94cdecdb
    ├───base16: github:SenchoPens/base16.nix/6b404cda2e04ca3cf5ca7b877af9c469e1386acb
    │   └───nixpkgs follows input 'stylix/nixpkgs'
    ├───flake-compat: github:edolstra/flake-compat/35bb57c0c8d8b62bbfd284272c928ceb64ddbde9
    ├───home-manager follows input 'home-manager'
    └───nixpkgs follows input 'nixpkgs'
```

**Comment by teto** [comment]
thanks for the detailed explanation. You are actually not the first to tumble on this and I heard about similar cases which means something should be done. 
To put things in context, my initial PR adding freeform settings aimed at increasing security by making it easier to share a future/potential "hardened ssh nix profile" I missed when switching some ansible ssh hardening script to a nixos configuration.
It apparently resulted in the opposite because of my ignorance about sshd:
1. I changed the case because to be the same `man sshd_config` as I thought it made setting discovery easier. It had not crossed my mind that people would make a mistake in updating the config, 
2. nixpkgs runs the `ssh -t ` validation step of the config so I thought wrong configs would be caught.

After going to #openssh and a few tests, I usually try to avoid blaming others but I am disappointed in the ssh validation command. The whole ssh configuration in fact is awkward with some options that can be repeated across lines or inlines, some not, some separated by a space, some by commas. And the most crucial point is that there is no way (to my knowledge) to run a strict validation steps that fails when options are ignored (because set multiple times for instance).
So IMHO this is really an upstream issue where they should validate the config better but because I dont wanna patch openssh (or rather I dont have the time), I think the best "fix" is to standardize the case as openssh doesn't care either.

I've just written this which might do the trick . I will propose it to https://github.com/NixOS/nixpkgs/pull/231467
```
commit faa91bc4122a9eff4ddbb07c29aa2b88a71bc49f
Author: Matthieu Coudron <mcoudron@hotmail.com>
Date:   Fri May 19 02:27:27 2023 +0200

    attempt to fix sshd issues

diff --git a/nixos/modules/services/networking/ssh/sshd.nix b/nixos/modules/services/networking/ssh/sshd.nix
index 910b9c5e56c..7d7dc54773c 100644
--- a/nixos/modules/services/networking/ssh/sshd.nix
+++ b/nixos/modules/services/networking/ssh/sshd.nix
@@ -22,12 +22,16 @@ let
         # else if isList     v then concatStringsSep "," v
         else throw "unsupported type ${typeOf v}: ${(lib.generators.toPretty {}) v}";
 
-  # dont use the "=" operator
+  mkLowerCaseKeyValue = {
+    mkValueString ? mkValueStringDefault {}
+  }: sep: k: v:
+    "${lib.strings.escape [sep] (lib.strings.toLower k)}${sep}${mkValueString v}";
+
   settingsFormat = (pkgs.formats.keyValue {
       listsAsDuplicateKeys = true;
-      mkKeyValue = lib.generators.mkKeyValueDefault {
-      mkValueString = mkValueStringSshd;
-    } " ";});
+      mkKeyValue = mkLowerCaseKeyValue {
+        mkValueString = mkValueStringSshd;
+      } " ";});
 
   configFile = settingsFormat.generate "config" cfg.settings;
   sshconf = pkgs.runCommand "sshd.conf-validated" { nativeBuildInputs = [ validationPackage ]; } ''
   ```

**Comment by infinisil** [comment]
Nice, it looks like this was fixed with the above PR, feel free to re-open if that's not the case!
