### ISSUE TITLE
Weird evaluation behavior with nvidia driver and broken kernels

### ISSUE THREAD

**Issue by Kiskae** [NixOS/nixpkgs#232303]
## Issue description

So I've been noticing that whenever I update the nvidia driver it tries to build the `5.4` hardened kernel. The problem is that the `linuxKernel.packages.linux_5_4_hardened.kernel` package is marked as broken so it should be immediately bailing instead of trying to build.

The actual derivation that fails is the `kernel.configfile` package, but that dependency only exists through the marked-as-broken kernel package:
```console
❯ NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_BROKEN=1 nix why-depends --impure --derivation --all .#linuxKernel.packages.linux_5_4_hardened.nvidia_x11 .#linuxKernel.packages.linux_5_4_hardened.kernel.configfile
/nix/store/z1zijhaqkssvvl380nn6cidrm0z820ds-nvidia-x11-530.41.03-5.4.242.drv
└───/nix/store/i555hswsn8hyqdnniz2jpf1jbrpkc1k6-linux-5.4.242.drv
    └───/nix/store/bzy1kw1yp0vs9kj8q5c0rrcyhs3i2a8m-linux-config-5.4.242.drv
```

### Steps to reproduce

1. `NIXPKGS_ALLOW_UNFREE=1 nix build --impure nixpkgs#linuxKernel.packages.linux_5_4_hardened.nvidia_x11`
2. It then proceeds to build the `linux-config-5.4` package which errors out.

All the other kernel packages correctly bail because the kernel package is marked as broken, so I have no idea why the nvidia package is behaving this way.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1-zen1, NixOS, 23.05 (Stoat), 23.05.20230516.963006a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Kiskae** [comment]
Pinging codeowners for `pkgs/stdenv/generic/check-meta.nix`:
@Ericson2314 @matthewbauer @piegamesde

**Comment by piegamesde** [comment]
What is the error message you are getting?

**Comment by Kiskae** [comment]
No message at all, it starts building the `kernel.configfile` package even through the `kernel` package is marked as broken.

Somehow it is creating a derivation for the `linux_5_4_hardened.kernel` package, even though that package is marked as broken.

**Comment by piegamesde** [comment]
Cannot reproduce with `NIXPKGS_ALLOW_UNFREE=1 nix build -A linuxKernel.packages.linux_5_4_hardened.nvidia_x11` (fails as expected), so I guess it's a flakes related issue then?

**Comment by Kiskae** [comment]
I just checked with the flake and that is behaving correctly as well, however when I try to run `nixpkgs-review` on an old PR it still tries building the broken kernel:

`NIXPKGS_ALLOW_UNFREE=1 nix run nixpkgs#nixpkgs-review -- pr 232982`:
```console
       > error: unused option: REFCOUNT_FULL
       > warning: unused option: SECURITY_WRITABLE_HOOKS
       > warning: unused option: STRICT_DEVMEM
       For full logs, run 'nix log /nix/store/q4yd98147b318i67k7gahig7g9hwx6ya-linux-config-5.4.242.drv'.
error: 1 dependencies of derivation '/nix/store/2qazhjdy6kjakpc4m5mlws4m1q3aw1n7-linux-5.4.242.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gag9gpiig3rp0pr38ccys2ddhb30ld0c-nvidia-open-5.4.242-525.47.26.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3kh63rw7mqsq6sdwbwwfjaav3v3qn9iq-nvidia-x11-525.47.26-5.4.242.drv' failed to build
```

-----------

Turns out that [nixpkgs-review enables `allowBroken`](https://github.com/Mic92/nixpkgs-review/blob/0a0e242ac01977aba4085b4786ea9be94573c013/nixpkgs_review/buildenv.py#L37) - So now I am second-guessing myself on whether I was imagining the behavior in the OP or whether there is a cache issue.

**Comment by Kiskae** [comment]
Closing this as it appears to be intended behavior for `nixpkgs-review`, I'll reopen if I run into the issue without config overrides.
