### ISSUE TITLE
cabal version 3.8 is unsupported

### ISSUE THREAD

**Issue by dark-ether** [NixOS/nixpkgs#232423]
when creating a project via cabal init -n it generates the cabal file with the latest version of the cabal standard. when running cabal 2nix in with a cabal file generated this way it doesn't produce a nix derivation

**Comment by sternenseemann** [comment]
People regularly run into this, so it may be something sensible to do. An overlay upgrading Cabal for cabal2nix should only affect pkgs.cabal2nix (and maybe haskellPackages.cabal2nix-unstable), but not haskell.packages.*.cabal2nix, so it remains possible to use it as a library.
