### ISSUE TITLE
`./pkgs/development/node-packages/generate.sh` never ends

### ISSUE THREAD

**Issue by yajo** [NixOS/nixpkgs#232411]
### Describe the bug
Well, it actually ends at some point, but after an extreme amount of hours.

Now, https://github.com/NixOS/nixpkgs/pull/221164 has conflicts and I just can't find the time to update the PR (not because I don't have time, but because the script always takes longer than my work schedule).

### Steps To Reproduce
1. Add `"@prettier/plugin-xml"` to `node-packages.json`
2. Run `./pkgs/development/node-packages/generate.sh`

### Expected behavior
That file only has about 400 packages. It shouldn't take so many hours to complete!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/8pfc9wfmn73bfz4ha0wmxvggk2wy9mpk-nix-info
copying path '/nix/store/8pfc9wfmn73bfz4ha0wmxvggk2wy9mpk-nix-info' from 'ssh://eu.nixbuild.net'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.15-300.fc38.x86_64, Fedora Linux, 38.20230515.0 (Silverblue), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(yajo): `"nixpkgs"`
 - nixpkgs: `/var/home/yajo/.nix-defexpr/channels/nixpkgs`
```

**Comment by figsoda** [comment]
cc @NixOS/node

**Comment by winterqt** [comment]
We're not really too interested in solving this at the moment, moreso reducing the size of the set.

**Comment by lilyinstarlight** [comment]
To clarify, new packages should be using `buildNpmPackage` (or similar) instead of using the older node2nix-based method, if those packages are supported by `buildNpmPackage` (e.g. see #229475)

We don't really have enough bandwidth ourselves to maintain node2nix and it has a lot of rather problematic issues (the massive size of the `nodePackages` set, which must fetch the metadata and files of ~10k packages, included -- but also it does a lot of things wrong and is based on a rather old model of how npm works)

**Comment by NotAShelf** [comment]
Speaking of npm, would there be any chance we see the pnpm toolkit introduced to nix build procedure, perhaps somethinig like buildPnpmPackage? I vaguely recall seeing an issue/discussion on it, but couldn't find it with a quick search.

**Comment by lilyinstarlight** [comment]
> Speaking of npm, would there be any chance we see the pnpm toolkit introduced to nix build procedure, perhaps somethinig like buildPnpmPackage? I vaguely recall seeing an issue/discussion on it, but couldn't find it with a quick search.

It's on the roadmap, but not a current focus (the npm tooling is still busted enough as-is...)

We're gonna start tracking that in #231513

**Comment by yajo** [comment]
I guess this is a duplicate of https://github.com/NixOS/nixpkgs/issues/229475 then. Thanks everyone, I'll follow your suggestions 😊 

I guess the very immediate action to take would be to change the docs, because I actually came to this problem following https://nixos.org/manual/nixpkgs/stable/#id-1.5.8.21.6.10

**Comment by lilyinstarlight** [comment]
> I guess the very immediate action to take would be to change the docs, because I actually came to this problem following

Yeah the docs do need updating there for sure. I guess I should probably try to sneak a docs update in soon so it makes it into the stable release
