### ISSUE TITLE
Clarify distinction between the two seemingly unrelated sets of node packages

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23259]
I was confused for a while when I found https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/node-packages.json and a massive autogenerated https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/node-packages-generated.nix, with no apparent indication for how to update the latter.

Browsing around some more, I found the much friendlier folder https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/node-packages, which even has a README.md! While friendlier, the node-packages folder still doesn't tell me what the other set is for or how it relates to the new set. I'm obviously a Nix+node newbie but it seems like this sort of thing would be best clarified in the nixpkgs manual, but that has no information on node whatsoever.

cc @svanderburg who I think is the master of all that is node

**Comment by copumpkin** [comment]
Also unclear is how to make ad-hoc modifications to particular packages. For example, I think `leveldown` is a binding to `leveldb`, and as such needs the `leveldb` library.

**Comment by Mic92** [comment]
It seems like `top-level/node-packages.json` is generated by `npm2nix` and `development/node-packages` is generated by `node2nix`.

**Comment by copumpkin** [comment]
@Mic92 thanks! It's still really confusing to me that both exist and there appears to be no relationship between them, and one of them seems almost entirely undocumented. At first I thought it was just forgotten but then it seems like people update it frequently.

**Comment by CMCDragonkai** [comment]
I was using node2nix and found myself needing to override the configure scripts inside nodegit package, I posted an issue on node2nix issues https://github.com/svanderburg/node2nix/issues/50#issuecomment-305799513

I had previously looked at npm2nix, but it seems abandoned, with the last commit being a year ago? Also not much docs on how to use it.

Many other language infrastructures in Nix seem to have a nix specified toolchain, like buildStackProject for haskell. But it seems that there's no consensus on this for nodejs ecosystem in NixOS. Sometimes you can get packages from pkgs.nodePackages but other times you need to use node2nix within your own nix shell, I still haven't figured out how to integrate all these methods.

**Comment by svanderburg** [comment]
Added extra details to the documentation in rev: fe9cefa7e4ed4da1a0d1d9777bf0f7145fff22e3
