### ISSUE TITLE
All syncthing folders are always enabled

### ISSUE THREAD

**Issue by jupblb** [NixOS/nixpkgs#232574]
### Describe the bug
`services.syncthing.settings.folders.<name>.enable` option has no effect after merging PR https://github.com/NixOS/nixpkgs/pull/226088. `enable` is not a setting of [folder element](https://docs.syncthing.net/users/config.html#folder-element). This causes all of the folders to be enabled which is a major UX regression (see option comment: "This option is useful when you want to define all folders in one place, but not every machine should share all folders.").

### Steps To Reproduce
1. Define and enable syncthing service, something like:

``` nix
services.syncthing = {
  enable = true;
  settings.folders = {
    "/aaa/bbb".enable = false;
  };
};
```

### Expected behavior
Syncthing service runs without defining `/aaa/bbb` share.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@Xyz00777 @doronbehar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05pre485269.e6e389917a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixpkgs-unstable"`
 - channels(jupblb): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Xyz00777** [comment]
Sorry Im not deep enough in nixos to help but I contacted @Lassulus who helped me by my pr, I hope he or @doronbehar can help 🙈
