### ISSUE TITLE
Build failure: volatility

### ISSUE THREAD

**Issue by Janik-Haag** [NixOS/nixpkgs#232584]
### Steps To Reproduce

- 0. enable unfree and insecure 
- 1. build *volatility*

### Build log

```
nix-shell -p volatility        
error: distorm3-3.5.2 not supported for interpreter python2.7
```

### Additional context
volatility needes python 2.7 (hence enabling insecure) and distorm3-3.5.2 only works with python 3.5 and upwards.

### Notify maintainers

@bosu 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05.20230515.17a6895`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(janik): `"nixos, unstable"`
 - nixpkgs: `/nix/store/lwnb4h8p9zk5g7mayxxjdhryax3g40ak-source
```

**Comment by figsoda** [comment]
instead of trying to fix the build, we can perhaps package [volatility 3](https://github.com/volatilityfoundation/volatility3) instead, which is uses python 3

**Comment by Janik-Haag** [comment]
volatility 3 is already packaged. We probably want to either fix volatility or mark it as broken.

**Comment by figsoda** [comment]
good point, opened #232629
