### ISSUE TITLE
fishPlugins.hydro cannot find command "fish"

### ISSUE THREAD

**Issue by Eliot00** [NixOS/nixpkgs#232545]
### Describe the bug

the error message show in every time I start a fish session:

```
fish: Unknown command: fish
/nix/store/h44v3fqpf2pcrqjqmrr8y3dj6xqd699f-source/conf.d/hydro.fish (line 61):
    fish --private --command "
```

### Steps To Reproduce

use home manager in macos aarch:

```fish
{ pkgs, ... }:

{
  programs.fish = {
    enable = true;
    plugins = [
      { name = "hydro"; src = pkgs.fishPlugins.hydro.src; }
    ];
    shellAliases = {
      gst = "git status";
      gd = "git diff";
      gdc = "git diff --cached";
      gl = "git pull";
      gp = "git push";
      gco = "git checkout";
      gcm = "git checkout master";
      gb = "git branch";
      gcl = "git config --list";
      gcp = "git cherry-pick";
      ga = "git add";
      gaa = "git add --all";
      gsta = "git stash";
      gstp = "git stash pop";
      gstd = "git stash drop";
      cf = "git-cf";
    };
  };
}
```

### Notify maintainers

@theHedgehog0 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/cyqa3d8y0q5dn6mmpyvpr10cz946scqf-source`

```

**Comment by Eliot00** [comment]
I found plugin [nix.fish](https://github.com/kidonng/nix.fish) can fix this problem

**Comment by natsukium** [comment]
I cannot reproduce this error with `wrapFish` or `home-manager` on my `x86_64-linux` and `aarch64-darwin`.
We may be missing some others problem.

**Comment by Eliot00** [comment]
I install nix with https://zero-to-nix.com/

**Comment by nrhtr** [comment]
@Eliot00 I believe `.nix-profile` is for packages installed using `nix-env` which I don't think is what you want. I'm using fish and home-manager (+ nix-darwin) and my /etc/shells looks like this:
```
cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh

# List of shells managed by nix.
/run/current-system/sw/bin/fish
```

For some reason I can't recall, I have fish installed at the system level using `nix-darwin`, so you might want something like this instead `/etc/profiles/per-user/<your-user>/bin/fish`

**Comment by Eliot00** [comment]
I realized that this issue is not related to nixpkgs and I will close this issue.

**Comment by Eliot00** [comment]
I believe [this PR](https://github.com/nix-community/home-manager/pull/4012) fixes the issue
