### ISSUE TITLE
upterm bin not found

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#232588]
### Describe the bug

somehow upterm not found.

```
➜  ~ ls -lha /nix/store/ | grep dr- | grep upterm
dr-xr-xr-x    4 root root    4,0K Jan  1 1970 238xps8q5caipvzh93fb6y9lgyw8gcaz-upterm-0.9.0
dr-xr-xr-x    2 root root    4,0K Jan  1 1970 g7yrb4rhcwr0vrc16c6xm5j7vvj9phkd-unit-uptermd.service
dr-xr-xr-x    3 root root    4,0K Jan  1 1970 pa8k4fbfngvn1jifvvgk6wns9ijnhshv-unit-script-uptermd-pre-start
➜  ~ ls -lha /var/run/current-system/sw/bin/ | grep upterm
➜  ~ ls -lha /nix/store/238xps8q5caipvzh93fb6y9lgyw8gcaz-upterm-0.9.0/bin/
total 28M
dr-xr-xr-x 2 root root 4,0K Jan  1 1970 .
dr-xr-xr-x 4 root root 4,0K Jan  1 1970 ..
-r-xr-xr-x 2 root root  15M Jan  1 1970 upterm
-r-xr-xr-x 2 root root  14M Jan  1 1970 uptermd
➜  ~ upterm
fish: Unknown command: upterm
```

### Steps To Reproduce
1. enable uptermd services
```
  services = {
    uptermd = {
      enable = true;
    };
  };

```
2. rebuild system and run upterm
```
➜  ~ upterm
fish: Unknown command: upterm
```

### Expected behavior

upterm can work properly.

### Screenshots

![Screenshot_20230518_172243](https://github.com/NixOS/nixpkgs/assets/45872139/f363a32a-76ea-4ed9-8bd5-6f44a7bb0c27)

### Additional context
none.

### Notify maintainers

@hax404

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run 'nix-info -m'
this path will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/0jmdsgfnd6aakxdr0sl5l7zzfs59hdrw-stdenv-linux
copying path '/nix/store/0jmdsgfnd6aakxdr0sl5l7zzfs59hdrw-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1, NixOS, 22.11 (Raccoon), 22.11.4147.9656e85a15a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(hervyqa): `""`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by jchv** [comment]
Does it help if you add `upterm` to your `systemPackages`? i.e.
```nix
{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [ upterm ];
}
```
I am guessing that `services.uptermd.enable` enables the `uptermd` server locally, which might not be what you intended to do.

**Comment by hervyqa** [comment]
> Does it help if you add `upterm` to your `systemPackages`? i.e.

yes, it works

```
➜  ~ upterm
Upterm is an open-source solution for sharing terminal sessions instantly with the public internet over secure tunnels.

Usage:
  upterm [command]

Examples:
  # Host a terminal session that runs $SHELL with
  # client's input/output attaching to the host's
  $ upterm host
```

I think by just enable the service, the package will be automatically downloaded. such as mysql, jupyter, colord, fstrim, and other packages that can be used immediately by enabling the service.

**Comment by jchv** [comment]
I think the confusion here is the distinction between `upterm` and `uptermd`. `upterm` seems to be a client program that you use to share your terminal, whereas `uptermd` is a server program that is used by servers like `uptermd.upterm.dev` and connected to by the `upterm` client.

The `upterm` program doesn't seem to need any special environment, so it probably does not need a NixOS module, and it is sufficient to just add the `upterm` derivation to your `systemPackages`.

**Comment by hervyqa** [comment]
Thanks for the explanation, now i understand. I think i will delete the `uptermd` service section.
