### ISSUE TITLE
Steam-Run should not depend on Steam

### ISSUE THREAD

**Issue by dukc** [NixOS/nixpkgs#232640]
### Describe the bug
Currently, Steam-Run depends on Steam itself. This results in the annoyance of having to allow Steam as an unfree package, besides being a needless installation in itself. Note that `steam-run` used to be decoupled and considered fully free. This unwanted dependency has appeared sometime during 2021 or 2022.

### Steps To Reproduce
- Try to install `steam-run` without having unfree packages allowed, from 22.11 channel.
- Try again, adding `unfreePred = pkg: builtins.elem (pkgs.lib.getName pkg) [ "steam-run" ];` to your `configuration.nix`
- Now it refuses to evaluate because you haven't enables `steam` in your `unfreePred`.

### Expected behavior
`steam-run` should preferably not be or depend on unfree packages at all. Even if it does, it should definitely not depend on Steam application itself. It's supposed to be a general-purpose tool to run Linux binaries, not just Steam games (right?).

### Notify maintainers
@jagajaga @jonringer

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.104, NixOS, 22.11 (Raccoon), 22.11.3408.a575c243c23`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(koodi): `""`
 - channels(vanhatpelit): `""`
 - channels(root): `"autumn20-20.09, nixos-22.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by raphaelr** [comment]
Since #232284 we have a free steam-run again, but it's not well exposed yet (it's available as `steamPackages.steam-fhsenv-without-steam.run`).

**Comment by YellowOnion** [comment]
Something else that bothers me is that steam-cmd requires steam-run and so steam-cmd pulls in an entire X desktop environment, steam-cmd is designed for hosting dedicated servers mostly so this is a waste of time, and precious disk space on a VPS.

IMHO steam-run should be spun out in to a separate non-steam thing and then extended to include the stuff needed for these different environments, I've seen it recommended for running FHS binaries in situations that have nothing to do with gaming, so it makes sense here to generalize it.

**Comment by Atemu** [comment]
I think it's time for a fhs-run attribute. Everything appimages need + anything that doesn't add significant cost would be a good starting point. A headless variant for command line tools would also be interesting, but it's harder to define a solid base here IMO.

We currently have multiple of such lists of packages and we ought to deduplicate that.

steam-run would become a specific fhs-run that adds steam and a few game-specific deps in it. Similarly, we could have a lutris-run that might have the same game-specific deps plus some extra for lutris runners.

**Comment by davidak** [comment]
The steam-run license issue came up again in a discussion in social media. I support creating a general purpose tool and use it as base for specialized ones!

It's also important to document the tool in a way new users find it when needed and don't have the experience that NixOS is broken (binaries don't work).

**Comment by SuperSamus** [comment]
Is this relevant to the issue?
https://github.com/Open-Wine-Components/ULWGL-launcher

**Comment by Atemu** [comment]
No.

**Comment by discapes** [comment]
> it's available as steamPackages.steam-fhsenv-without-steam.run

Another great option is to use flatpak, for example:

```
flatpak run --filesystem=home org.freedesktop.Platform -c ~/Downloads/proprietaryapp.run
```

I'm pretty sure they both use the same container tech (bubblewrap) anyway.

**Comment by dukc** [comment]
Today, I had a problem where a Ruby Bundler package wouldn't work because it expected a FHS environment, breaking the build of my Jekyll site. Then I remembered the comment here. I'm happy to report `steamPackages.steam-fhsenv-without-steam.run` solved it just like the `steam-run` package would in the old times.

Therefore, this issue is solved. I still do agree that one or more separate "fhs-run" programs that would not have as many dependencies as `steam-run` would be good to have, like @Atemu suggested, but it's not what this issue is about.
