### ISSUE TITLE
jetbrains intellij does not automatically restart if there is no python in path

### ISSUE THREAD

**Issue by necauqua** [NixOS/nixpkgs#232654]
### Describe the bug
IntelliJ (and I'm assuming other jetbrains products) uses a Python script to restart itself whenever needed (e.g. a plugin update), and if it detects that there is no Python, it shutdowns instead.

### Steps To Reproduce
1. Run intellij. In the menu, select "File" -> "Invalidate Caches..."
2. If there is no python in path, the opened window will have a button "Invalidate and Exit"
3. If run from `nix shell nixos#python3`, it will have "Invalidate and Restart"

Same thing happens whenever it needs to restart, with/without python it shows "Restart"/"Shutdown" buttons respectively, and in some conditions it just asks "Restart now?" and then does not come back up when you agree.

I know it's easy to fix on my end, but it's not super clear that that's even an issue, and I think python should be added to dependencies and made visible to jetbrains IDEs.

And yes I don't have system-wide python installed, that's the whole point of NixOS, is it not? :)

### Notify maintainers

@edwtjo, I guess

### Metadata
```console
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.12, NixOS, 23.05 (Stoat), 23.05.20230426.d6b863f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(necauqua): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/wsci3as2flp84w6w5gzbyphxzf6ilasd-source`
```

**Comment by matthewpi** [comment]
I can confirm this affects the other JetBrains IDEs as well.  Adding `python3` to the [`lib.makeBinPath` call](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/jetbrains/linux.nix#L74) solves this problem.

I'll open a PR for it shortly.
