### ISSUE TITLE
Python dvc ‘platformdirs’ has no attribute ‘site_cache_dir’

### ISSUE THREAD

**Issue by jamesdbrock** [NixOS/nixpkgs#232790]
Hi @CMCDragonkai thanks for packaging `dvc`.

In __nixpkgs-unstable__ `dvc` currently has this problem:

https://discuss.dvc.org/t/module-platformdirs-has-no-attribute-site-cache-dir/1636

```
$ dvc add asset
ERROR: unexpected error - module 'platformdirs' has no attribute 'site_cache_dir'
```

Do you know what to do about this?

https://github.com/NixOS/nixpkgs/blob/582e084ca3c1a96fc19765280d09678f972fac16/pkgs/applications/version-management/dvc/default.nix#LL58C8-L58C8

**Comment by thornycrackers** [comment]
https://github.com/platformdirs/platformdirs/blob/main/CHANGES.rst#platformdirs-310-2023-03-03
https://github.com/iterative/dvc/blob/main/pyproject.toml#L51
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/platformdirs/default.nix#L14

Looks like dvc is looking is using and older version platformdirs (3.0.0)

**Comment by collinarnett** [comment]
Looks like platformdirs is getting upgraded in nixpkgs https://github.com/NixOS/nixpkgs/pull/232987 this should resolve the current issue. Although until that's merged dvc is still broken.

**Comment by bcdarwin** [comment]
Closing since the linked PR was merged.

**Comment by usmcamp0811** [comment]
This is a problem again..
