### ISSUE TITLE
mullvad-2023.3 openvpn plugin loading error

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#232794]
### Describe the bug

After updating to mullvad-2023.3 openvpn connections fail.
Before the update on 2022.5 this was still working fine.

```
OpenVPN 2.5.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jun 17 2021
library versions: OpenSSL 3.0.8 7 Feb 2023, LZO 2.10
PLUGIN_INIT: POST /nix/store/32cim6mwrbzfpyg8wxwzmdar6zab26l5-mullvad-2023.3/share/mullvad/libtalpid_openvpn_plugin.so '[/nix/store/32cim6mwrbzfpyg8wxwzmdar6zab26l5-mullvad-2023.3/share/mullvad/libtalpid_openvpn_plugin.so] [/tmp/talpid-openvpn-d173db26-2152-4035-aeda-fd36f185a7f5]' intercepted=PLUGIN_UP|PLUGIN_ROUTE_UP|PLUGIN_ROUTE_PREDOWN
PLUGIN_INIT: plugin /nix/store/32cim6mwrbzfpyg8wxwzmdar6zab26l5-mullvad-2023.3/share/mullvad/libtalpid_openvpn_plugin.so expressed interest in unsupported plugin types: [want=0x00011005, have=0x0000ffff]
Exiting due to fatal error
```

### Steps To Reproduce
1. update mullvad to 2023.3
2. start mullvad with openvpn enabled

### Expected behavior
OpenVPN connections should work.

### Notify maintainers

@cole-h

**Comment by arashsm79** [comment]
Same problem here with OpenVPN and local bridge.
Reverting to 2022.5 fixes the issue.

**Comment by cole-h** [comment]
I don't use the OpenVPN functionality, but it was originally contributed by @SuperSandro2000 -- maybe they have an idea on how to fix this.

**Comment by SuperSandro2000** [comment]
I just fixed the build for you 🙃 no idea

**Comment by TarCV** [comment]
Looks like this issue is caused by Mullvad 2023.3 using OpenVPN 2.6.0 with a patch adding auth failure listener (also few others, probably not related to the issue). I've given a try at fixing this.
