### ISSUE TITLE
Cannot extend preStart for dendrite service

### ISSUE THREAD

**Issue by alex-fu27** [NixOS/nixpkgs#232799]
### Describe the bug
I expected to be able to extend the pre-startup script for the `dendrite` service, but I can not.

### Steps To Reproduce
In `configuration.nix`, do
```
services.dendrite = {
  enable = true;
  # extra options to configure dendrite
};
systemd.services.dendrite.preStart = '' additional start script '';
```

Then on `nixos-rebuild`, get
```
error: The definitions for systemd unit options should be either all lists, representing repeatable options, or all non-lists, but for the option containers.dendrite.systemd.services.dendrite.serviceConfig.ExecStartPre, the definitions are a mix of list and non-list
       - In `/nix/store/58vz61iwy2j6ing7i5k08l2q2ndr16f2-nixos-22.11/nixos/nixos/modules/system/boot/systemd.nix':
           [
             "/nix/store/s2yh5fqna3hgwfllyh4p8wn9zxyj59ic-unit-script-dendrite-pre-start/bin/dendrite-pre-start"
           ]
       - In `/nix/store/58vz61iwy2j6ing7i5k08l2q2ndr16f2-nixos-22.11/nixos/nixos/modules/services/matrix/dendrite.nix':
           ''
             /nix/store/1zzfx03y0ppldq5rvdwqwrq547q7j0cl-envsubst-1.2.0/bin/envsubst \
               -i /nix/store/azbsvzbdmz02phma3waxpvjxpdfjijml-dendrite.yaml \
               -o /run/dendrite/dendrite.yaml
           ''
```

### Expected behavior
The option `ExecStartPre` will be included multiple times in the service file.

### Additional context
What I am actually doing is trying to debug the setting of the Postgresql connection url - I want to connect to a local socket AND specify a password, but not in my nixos config.

The fix for this issue should be easy, use `preStart` instead of `ExecStartPre` in [nixos/modules/services/matrix/dendrite.nix](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/services/matrix/dendrite.nix).
However, I have not really contributed to nixpkgs so far and have not yet wrapped my mind around how to actually test the changes I made to nixpkgs. Maybe I will try this weekend. :smiley: 

### Notify maintainers
Haha not that easy `lib.teams.matrix.members`... maybe @mjlbach @jian-lin ?

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.110, NixOS, 22.11 (Raccoon), 22.11.4211.55af203d468`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jian-lin** [comment]
This should work:

```
systemd.services.dendrite.serviceConfig.ExecStartPre = [ "additional start script" ];
```

**Comment by alex-fu27** [comment]
Thanks, that PR fixes it. I've upgraded to Nixos 23.05 which includes it.
