### ISSUE TITLE
Update request: calligra 3.2.1 → 3.3.0

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#232868]
- Package name: calligra
- Latest released version: 3.3.0

- Current version on the unstable channel: 3.2.1
- Current version on the stable/release channel: 3.2.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ebzzry 
@zraexy 

* https://calligra.org/news/announcements/stable/calligra-plan-version-3-3-0-released/index.html
* https://download.kde.org/stable/calligra/3.3.0/

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by MGlolenstine** [comment]
I've assigned this task to myself, but I've just realised that `Calligra` 3.3 is still in Beta and hasn't been released yet.
The above release notes are for `Calligra Plan 3.3`.
(Could someone correct me if I'm wrong?)

**Comment by SigmaSquadron** [comment]
Superseded by #337989
