### ISSUE TITLE
jdt-language-server crashes on startup

### ISSUE THREAD

**Issue by WhiteBlackGoose** [NixOS/nixpkgs#232822]
### Describe the bug
`jdt-language-server` unconditionally fails to run, crashing on startup and writing a huge ass exception in the log

### Steps To Reproduce
1. `nix shell nixpkgs#jdt-language-server`
2. `jdt-language-server`

Error:
```
Picked up _JAVA_OPTIONS: -Dsun.java2d.uiScale=2
An error has occurred. See the log file
/home/goose/.eclipse/213835391_linux_gtk_x86_64/configuration/1684495124914.log.
```

[**1684495124914.log**](https://github.com/NixOS/nixpkgs/files/11516557/1684495124914.log)

### Expected behavior
It should not crash

### Additional context
Tried with and without `JAVA_HOME` set. It wraps OpenJDK 19 to run, so it should work standalone, however, I'm not a java dev so I don't really know what else to try out

### Notify maintainers

cc @matt-snider 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.11, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by figsoda** [comment]
jdt-language-server is supposed to be used with a language server client, could you test this with your editor (with the required lsp plugins) and see if it still crashes?

**Comment by kylechui** [comment]
I've tried using Neovim with [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls), and it immediately crashes on startup:

![image](https://github.com/NixOS/nixpkgs/assets/48545987/3597ddf8-baab-4b0f-be47-b5b75a5e4d14)

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05.20230517.e6e3899`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(kylec): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Trying to run it directly from the terminal yields a similar error to WhiteBlackGoose's.

**Comment by WhiteBlackGoose** [comment]
@figsoda still crashes (tried with `nvim-jdtls`).

**Comment by WhiteBlackGoose** [comment]
Haha beat me to it

**Comment by figsoda** [comment]
I can't reproduce my error, here is my nvim-jdtls config: https://github.com/figsoda/cfg/blob/52449c9931f4a5aee49c7d6e440a95ee0e9a0421/src/programs/neovim/configure/plugins.lua#L218-L254

What is your config and the java code you are working with?

**Comment by WhiteBlackGoose** [comment]
My config:
```java
if os.getenv("JDTLS") ~= nil then                                                                  
    local jdtls_config = {                                                                         
        cmd = { os.getenv("JDTLS"), '-data' },                                                     
        root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]), 
    }                                                                                              
    require('jdtls').start_or_attach(jdtls_config)                                                 
end                                                                                                
```
Where `JDTLS` is env variable that points to the full path to jdt.

I tried yours btw, not sure what @ does in it, so removed `settings` and `init_options`, and got the same error. 

The project is a maven tomcat web app.

**Comment by kylechui** [comment]
I'm using the following configuration:

```lua
require("jdtls").start_or_attach({
    cmd = { "/etc/profiles/per-user/kylec/bin/jdt-language-server" },
    root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
})
```

I'm working on a Java compiler for an assignment.

**Comment by matt-snider** [comment]
It would be helpful to get the full command which is actually being run, not lua code or important values being hidden behind env vars. Those are things specific to your machine. Let us see what is actually being executed please.

Also some relevant entries from the log file would be a good start.

**Comment by WhiteBlackGoose** [comment]
Hi, I tried running it directly, see the issue text. There's also log attached (I don't know what relevant there, tbh, I attached the whole file). See `Steps to reproduce`

**Comment by WhiteBlackGoose** [comment]
@matt-snider 

```
/nix/store/rrjsl3r0kazsbqf5wwbv44814jhnkphm-jdt-language-server-1.21.0/bin/jdt-language-server
```
hopefully I didn't change the inputs since then

what are you trying to compare it against? I don't see any nix store path mentioned in the part you quoted

**Comment by matt-snider** [comment]
Thanks! It's just helpful to see the _exact_ derivation you're running and then the less precise but also useful jdtls version (1.21.0).

Did you search the upstream project at all? https://github.com/eclipse/eclipse.jdt.ls/issues/2194 seems to be the same (cryptic) error and the issue there was not including the `-data /path/to/my/workspace` option. It doesn't seem like you've done this when running the project manually from the command line.  Your config snippet (`cmd = { os.getenv("JDTLS"), '-data'}`) does not include a value for the `-data` option either.

[`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls) has this to say about it:

> Choose a value for -data: An absolute path to your data directory. eclipse.jdt.ls stores workspace specific information in it. This should be unique per workspace/project.

I personally use  `$XDG_CACHE_HOME/jdtls/$PWD`, which ends up being something like $XDG_CACHE_HOME/jdtls/home/matt/projects/xyz` so each project is isolated.

**Comment by matt-snider** [comment]
I think we can probably close this, as the issue seems to be that both @WhiteBlackGoose and @kylechui did not specify a value for `-data`, but please confirm

**Comment by WhiteBlackGoose** [comment]
Thanks, indeed. I didn't see it in the default config of the plugin, and the error wasn't very helpful. Thanks again

**Comment by kylechui** [comment]
This did indeed fix it for me as well, sorry for the noise!
