### ISSUE TITLE
Package rustup or update rustc-nightly more often

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#23291]
## Issue description

I have to use rustc nightly for one project, but the nightly version of nixpkgs is too old. And we do not ship rustup either, so it is not possible for me to work right now...

Can someone please provide some documentation how to update rustc unstable? That'd be the simplest solution I guess... because right now I do not understand how to update the package...

**Comment by Mic92** [comment]
I was working on a script to do this automatically: https://github.com/NixOS/nixpkgs/pull/21922 ... its not finished yet.

**Comment by Mic92** [comment]
rustup should also work without a nix package in your home.

**Comment by the-kenny** [comment]
`rustup` doesn't work as the downloaded binaries need to be patched. I started adding this functionality to rustup some time ago but never got around finishing it. Can't be done with a simple wrapper as `rustup` calls into the downloaded binaries to check their versions etc. before exiting.

**Comment by matthiasbeyer** [comment]
I don't care anymore because there is the nixpkgs overlay by mozilla now.

**Comment by the-kenny** [comment]
For people finding this issue on Google: The overlay @matthiasbeyer mentioned is available at https://github.com/mozilla/nixpkgs-mozilla

**Comment by matthiasbeyer** [comment]
Yes. If you find that `rustc` does not find `src` or `core`, have a look [here](https://github.com/mozilla/nixpkgs-mozilla/issues/21). I don't know how common this is, but I'll leave this here just in case.
