### ISSUE TITLE
Build failure: virtualbox-modules-7.0.6-6.3.3

### ISSUE THREAD

**Issue by seriousbusinessuser** [NixOS/nixpkgs#232959]
### Steps To Reproduce

1. Update to latest `nixpkgs-unstable` channel(5b1bc788f578cd83d54b48bb057d6f6703ae7725).
2. Try to install virtualbox. In my case I have `virtualisation.virtualbox.host.enable = true;` in my NixOS config file.

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/i63fs3cwjsw160vscmydd9m1kgd7vq4w-virtualbox-7.0.6-modsrc
source root is virtualbox-7.0.6-modsrc
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j8 SHELL=/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash INSTALL_MOD_PATH=\$\(out\)
=== Building 'vboxdrv' module ===
make[1]: Entering directory '/build/virtualbox-7.0.6-modsrc/vboxdrv'
make V= CONFIG_MODULE_SIG= CONFIG_MODULE_SIG_ALL= -C /nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/build M=/build/virtualbox-7.0.6-modsrc/vboxdrv SRCROOT=/build/virtualbox-7.0.6-modsrc/vboxdrv -j8 modules
make[2]: Entering directory '/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/build'
make[2]: warning: -j8 forced in submake: resetting jobserver mode.
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/SUPDrv.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/SUPDrvGip.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/SUPDrvSem.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/SUPDrvTracer.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/SUPLibAll.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/common/string/strformatrt.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/combined-agnostic1.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/combined-agnostic2.o
  CC [M]  /build/virtualbox-7.0.6-modsrc/vboxdrv/combined-os-specific.o
In file included from /build/virtualbox-7.0.6-modsrc/vboxdrv/combined-os-specific.c:43:
/build/virtualbox-7.0.6-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjNativeLockUser':
/build/virtualbox-7.0.6-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:1404:39: error: assignment of read-only member 'vm_flags'
 1404 |                 papVMAs[rc]->vm_flags |= VM_DONTCOPY | VM_LOCKED;
      |                                       ^~
/build/virtualbox-7.0.6-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjNativeMapUser':
/build/virtualbox-7.0.6-modsrc/vboxdrv/r0drv/linux/memobj-r0drv-linux.c:1876:35: error: assignment of read-only member 'vm_flags'
 1876 |                     vma->vm_flags |= VM_DONTEXPAND | VM_DONTDUMP;
      |                                   ^~
make[3]: *** [/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/source/scripts/Makefile.build:252: /build/virtualbox-7.0.6-modsrc/vboxdrv/combined-os-specific.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/source/Makefile:2025: /build/virtualbox-7.0.6-modsrc/vboxdrv] Error 2
make[2]: Leaving directory '/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/build'
make[1]: *** [/build/virtualbox-7.0.6-modsrc/vboxdrv/Makefile-footer.gmk:133: vboxdrv] Error 2
make[1]: Leaving directory '/build/virtualbox-7.0.6-modsrc/vboxdrv'
make: *** [Makefile:78: vboxdrv] Error 2
```

Looks like it's broken on Hydra too: https://hydra.nixos.org/build/220650905.

### Notify maintainers

@svanderburg 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.3, NixOS, 23.05 (Stoat), 23.05.20230519.5b1bc78`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(work): `""`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/xwx0anyv1mdfwbyga8ypcafbynvip0zr-source`

**Comment by MaxHearnden** [comment]
This will be fixed by https://github.com/NixOS/nixpkgs/pull/232770 when it merges

**Comment by seriousbusinessuser** [comment]
Fixed.

**Comment by cowboyliao** [comment]
unstable channle, try to install virtualbox,  same Metadata, Build log:
[I] randy@nixos ~ [1]> sudo nixos-rebuild switch
error: builder for '/nix/store/s715w3ac3jwrl9rd2b6p4qz9qn9iw5wh-VirtualBox-GuestAdditions-7.0.6-6.3.3.drv' failed with exit code 2;
       last 10 log lines:
       > /build/install/src/vboxguest-7.0.6/vboxguest/r0drv/linux/memobj-r0drv-linux.c: In function 'rtR0MemObjNativeMapUser':
       > /build/install/src/vboxguest-7.0.6/vboxguest/r0drv/linux/memobj-r0drv-linux.c:1876:35: error: assignment of read-only member 'vm_flags'
       >  1876 |                     vma->vm_flags |= VM_DONTEXPAND | VM_DONTDUMP;
       >       |                                   ^~
       > make[3]: *** [/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/source/scripts/Makefile.build:252: /build/install/src/vboxguest-7.0.6/vboxguest/combined-os-specific.o] Error 1
       > make[3]: *** Waiting for unfinished jobs....
       > make[2]: *** [/nix/store/bi8mfrqha64hilpk4mrhmgwi2w255gx8-linux-6.3.3-dev/lib/modules/6.3.3/source/Makefile:2025: /build/install/src/vboxguest-7.0.6/vboxguest] Error 2
       > make[1]: *** [/build/install/src/vboxguest-7.0.6/vboxguest/Makefile-footer.gmk:133: vboxguest] Error 2
       > make[1]: Leaving directory '/build/install/src/vboxguest-7.0.6/vboxguest'
       > make: *** [Makefile:49: vboxguest] Error 2
       For full logs, run 'nix log /nix/store/s715w3ac3jwrl9rd2b6p4qz9qn9iw5wh-VirtualBox-GuestAdditions-7.0.6-6.3.3.drv'.
error: 1 dependencies of derivation '/nix/store/aczi4dkzixz5h5nqg6g073i4iqcsc9mp-VirtualBox-GuestAdditions-7.0.6-6.3.3_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w655ky6hq0qdgymq97dl9f7k5l7749gw-kernel-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/89jhcyi0dnr6lllgdx3m6v52pxvlh883-linux-6.3.3-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cvx6m7xa59w75dxc4mm22m7yaas2wkw1-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v4hh3p40b994099mrkgysq80pf7k1nm3-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8z97pifijz20czflgx3qgacvp588d5xg-unit-virtualbox.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gi78c0mlrn1hkz04sq4k3q9yvkk7rcaw-xsession-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/na3k6ksci27xwahjvdzrzp1scy3ckrlr-nixos-system-nixos-23.11.20230524.f91ee30.drv' failed to build

**Comment by eclairevoyant** [comment]
@cowboyliao you're still building 7.0.6 not 7.0.8

**Comment by MaxHearnden** [comment]
@cowboyliao It looks like you are using flakes, to update your system pass `--recreate-lock-file` to nixos-rebuild.

**Comment by cowboyliao** [comment]
thanks to your advices, I really forget to update my flake lock file. I set linuxPackages_latest, then linux kernel from 6.3.3 to 6.4.2. :)   
but after I reboot I found my plasma is dead, without panel and responding, and the virtualbox still error: 

error: builder for '/nix/store/ikcfxb6x7qa7hn0jjjw4mlhwby9r9360-VirtualBox-GuestAdditions-7.0.8-6.4.2.drv' failed with exit code 2;
       last 10 log lines:
       > /build/install/src/vboxguest-7.0.8/vboxsf/regops.c:2402:48: error: 'struct iov_iter' has no member named 'iov'; did you mean '__iov'?
       >  2402 |         const struct iovec *pCurIov    = iter->iov;
       >       |                                                ^~~
       >       |                                                __iov
       > make[3]: *** [/nix/store/chrsc43yv3gxzx3f864d2f7fgbqvw6v1-linux-6.4.2-dev/lib/modules/6.4.2/source/scripts/Makefile.build:252: /build/install/src/vboxguest-7.0.8/vboxsf/regops.o] Error 1
       > make[3]: *** Waiting for unfinished jobs....
       > make[2]: *** [/nix/store/chrsc43yv3gxzx3f864d2f7fgbqvw6v1-linux-6.4.2-dev/lib/modules/6.4.2/source/Makefile:2026: /build/install/src/vboxguest-7.0.8/vboxsf] Error 2
       > make[1]: *** [/build/install/src/vboxguest-7.0.8/vboxsf/Makefile-footer.gmk:133: vboxsf] Error 2
       > make[1]: Leaving directory '/build/install/src/vboxguest-7.0.8/vboxsf'
       > make: *** [Makefile:58: vboxsf] Error 1
       For full logs, run 'nix log /nix/store/ikcfxb6x7qa7hn0jjjw4mlhwby9r9360-VirtualBox-GuestAdditions-7.0.8-6.4.2.drv'.
error: 1 dependencies of derivation '/nix/store/2qvif7c4iz0kc7rscfb6hl1vsv7a6crk-VirtualBox-GuestAdditions-7.0.8-6.4.2_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dh8afxx484l3z8fhl2p1iqmdgmx39iza-kernel-modules.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-virtualbox-7.0.8.drv-0/VirtualBox-7.0.8/src/libs': Directory not empty
error: 1 dependencies of derivation '/nix/store/kc4a44xhawmkm9v7rag0gw3zaxw2vbd1-linux-6.4.2-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w10clsxrgfbfwgin3wil9a3i3ngaz7gf-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/257zmmmqhdsxwlrscs8645cql0s0m8hc-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6arws80dbdd6pcrn21078sz481zmvv1v-unit-virtualbox.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mfp414kdxd88qfy71g3lv2763398zcnb-xsession-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b8pcvl3b0b8ks6d1i0gg2ac4w1ln8bh2-nixos-system-nixos- 23.11.20230709.408c0e8.drv' failed to build

how is this error?
  const struct iovec *pCurIov    = iter->iov;
