### ISSUE TITLE
security.dhparams: Incorrect docs

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#23290]
## Issue description

I believe this is not correct: https://github.com/NixOS/nixpkgs/blob/940492cef5e0180dc8aec51777372748f5e496e9/nixos/modules/security/dhparams.nix#L9

It should be `security.dhparams.params = { ... }`.

cc @Ekleog

**Comment by Ekleog** [comment]
Well, to me this part of the code states "in `security.dhparams`, elements [params](https://github.com/NixOS/nixpkgs/blob/940492cef5e0180dc8aec51777372748f5e496e9/nixos/modules/security/dhparams.nix#L10) and [path](https://github.com/NixOS/nixpkgs/blob/940492cef5e0180dc8aec51777372748f5e496e9/nixos/modules/security/dhparams.nix#L28) can be found". At least that's the only technical way I know of doing it.

In the documentation itself (strings in the `description` arguments), I cannot find an error, and `man configuration.nix` (autogenerated from these arguments) seems OK to me too.

Do I miss the point, or were you misled by the fact that the documentation for unstable / 17.03 don't yet have an equivalent to [this great page](https://nixos.org/nixos/options.html)?

**Comment by 3noch** [comment]
@Ekleog Yes I was using the code as docs and that's probably what happened. If that will be resolved by having the great page, then I'm fine without changing anything.

**Comment by globin** [comment]
As soon as this is in a stable release it will be on that page.
