### ISSUE TITLE
Set CONFIG_SHELL to stdenv.shell in default builder

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#233]
There are cases where chroot builds are not practical (for example, when you are still building stdenv on a platform not supported by Hydra). ./configure will take /bin/bash as shell before checking PATH, but this can be overriden with CONFIG_SHELL environment variable.

Maybe it is a good idea to set this variable? Or maybe just for stdenv and nix dependencies (afterwards it is possible to use chroot builds)

**Comment by Mathnerd314** [comment]
I think this can be closed: https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L209
