### ISSUE TITLE
matplotlib 3.7.0 fails to evaluate for python 38

### ISSUE THREAD

**Issue by WhiteBlackGoose** [NixOS/nixpkgs#233069]
### Describe the bug
```
error: matplotlib-3.7.0 not supported for interpreter python3.8
```

### Steps To Reproduce
1. `nix repl`
2. `:lf path/to/nixpkgs`
3. `outputs.legacyPackages.x86_64-linux.python38Packages.matplotlib`

Error:
```
error: matplotlib-3.7.0 not supported for interpreter python3.8
«derivation
```

### Expected behavior

There should be a working matplotlib for 3.8, and the newer one for 3.9+, I guess

### Additional context

Commit `0d5041f8054a` caused this regression. For 3.7.0:
```
disabled = pythonOlder "3.9";
```

Latest matplotlib that worked for 3.8 is 3.6.2. [I tried to pack it](https://github.com/WhiteBlackGoose/nixpkgs/tree/matplotlib-3_6_2) by simply taking the old version of `matplotlib/default.nix` (before the said commit), which builds but fails to work with tk (I'm not sure tbh how to approach it).

### Notify maintainers

@lovek323 @veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.11, NixOS, 23.05 (Stoat), 23.05.20230417.f00994e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by WhiteBlackGoose** [comment]
also cc @mweinelt

**Comment by veprbl** [comment]
Maybe, try poetry2nix or using older nixpkgs.

**Comment by davidgm94** [comment]
I tried with fea4e40b980e123b43af4f52b5fce355fea68584 but it gave me a error when trying to compile some boost library...

**Comment by mweinelt** [comment]
Sorry, but I don't have the energy to provide full support for the python package sets we don't recurse into. As such they're untested and the fast pace at which python libraries move makes it cumbersome to keep everything in working order.

**Comment by kirillrdy** [comment]
@mweinelt greetings !

https://matplotlib.org/stable/devel/dependencies.html lists python 3.8 as compatible ( sorry you need to look at html title tag to see that its for version 3.7.1

matplotlib builds with this change, tested at d2c9a3d7f48cb158f9b240dceab793170378ac74

```
  disabled = pythonOlder "3.8";
```

I appreciate how much work you put into this, so I am happy to create a PR for this


@WhiteBlackGoose 
you should be able to just override `disabled` attribute of derivation, you can refer to nixpkgs manual for that, or let us know if you need some assistance

**Comment by WhiteBlackGoose** [comment]
Thank you!

@davidgm94 you can try now to use the master branch of nixpkgs with the shell you tried before

**Comment by davidgm94** [comment]
> Thank you!
> 
> @davidgm94 you can try now to use the master branch of nixpkgs with the shell you tried before

Thank you very much everybody. This fixes it :)
