### ISSUE TITLE
sage fails to build

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#23304]
## Issue description

Building `sage` fails with the following error:

http://pastebin.com/CsSb3gcD

### Steps to reproduce

```
nix-shell -p sage
```
## Technical details

* System: 17.03pre99759.f66d782 (Gorilla)
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre101839.53a2baa

**Comment by Mic92** [comment]
I suspect it is not compatible with the GMP library it gets linked to. An upgrade to 7.5.1 could resolve this problem.

**Comment by 7c6f434c** [comment]
A few months ago I tried to «just upgrade Sage» and I have failed. It may be that some of the complicated things have become simpler since then, but Sage is a large and fragile build, apparently…
