### ISSUE TITLE
Download of ‘https://nixos.org/channels/nixpkgs/nixexprs.tar.bz2’ failed

### ISSUE THREAD

**Issue by Yury-Zakharov** [NixOS/nixpkgs#23307]
## Issue description
When trying to upgrade from unstable to stable getting the following:
Executing **nix-channel --update** results in
> downloading Nix expressions from ‘https://nixos.org/channels/nixpkgs/nixexprs.tar.bz2’...
> curl: (22) The requested URL returned error: 404 Not Found
> /nix/store/iz89ciwqjfad7n8bddw4whwfq8h5rj4x-nix-1.10/bin/nix-prefetch-url: download of ‘https://nixos.org/channels/nixpkgs/nixexprs.tar.bz2’ failed
> cannot fetch ‘https://nixos.org/channels/nixpkgs/nixexprs.tar.bz2’
> 
Executing **nixos-rebuild switch --upgrade** results in system shutdown after random period of time.

### Steps to reproduce
Execute nix-channel --update
or
Execute 
nixos-rebuild switch --upgrade

## Technical details

* System: 16.03pre73106.b1dca6c (Emu)
* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: 17.03pre102064.8fcd1a0

**Comment by Mic92** [comment]
There were problems with amazon S3 error yesterday: https://github.com/NixOS/nixpkgs/issues/14874#issuecomment-283145991

**Comment by Yury-Zakharov** [comment]
Thanks. I met the problem on Monday 27 Feb, not sure it was there earlier.
Will try again tonight.

**Comment by vcunat** [comment]
I can't see how the shutdown might be related; that's perhaps a separate issue, but note that 16.03 is not (officially) supported anymore, for a log time already.

**Comment by Yury-Zakharov** [comment]
vcunat
Thanks for reply
I've tried both 16.09 and unstable, result is the same.
One strange thing I've noticed is that the file my system tries to download is nixexprs.tar.bz2 while all channels (https://nixos.org/channels/) contain nixexprs.tar.xz. The same name, different extension.

Wrt the system shutdown while upgrading - I can't see neither but I just describing the behavior. Every time I issue **nixos-rebuild switch --upgrade** command, system shuts down after a while. Not restarts, not asking for something, just shuts down switching the power of a laptop off.

**Comment by edolstra** [comment]
There is no "nixpkgs" channel, please try "nixpkgs-unstable" instead. See here for the list of channels: https://nixos.org/channels/

IIRC, the `.tar.bz2` is a fallback when `.tar.xz` cannot be found.

**Comment by edolstra** [comment]
Also, for NixOS, you should probably use the `nixos-unstable` channel instead of `nixpkgs-unstable`. I don't remember if `nixpkgs-unstable` works as a NixOS channel.

**Comment by Yury-Zakharov** [comment]
edolstra
Thanks for your recall.  If .bz2 is just a fallback then a matter is in wrong environment configuration on my side.
Do I need both channels (one for packages and one for nixos) to be added to my nixos channels?
I'll try another attempt tonight

**Comment by vcunat** [comment]
No, both channels contain nixos and nixpkgs code, as it's just a single source tree.  Binary cache is completely shared/global.

**Comment by Yury-Zakharov** [comment]
Thanks everyone, channels  updated. 
Most probably the reason was S3 failure.
