### ISSUE TITLE
Ghost and duplicated files in Nautilus

### ISSUE THREAD

**Issue by justryanw** [NixOS/nixpkgs#233277]
### Describe the bug
Nautilus shows ghost or duplicated files when moving or deleting files, leaving and returning to the folder shows the actual files.
### Steps To Reproduce
1. Be in a folder with a few folders and files inside
2. Move a file to wastebasket or into one of the other folders.
3. A different folder/file will disappear while the file intended to be moved/deleted will remain.
4. Undoing the action will duplicate the intended file.
5. Leaving and returning to the folder the actual file structure

### Expected behavior
Show the intended file being deleted/moved.

### Screenshots
Test folder
![image](https://github.com/NixOS/nixpkgs/assets/34030157/58745876-0146-4d9a-b253-7edeef51eee2)

Attempting to remove the file
![image](https://github.com/NixOS/nixpkgs/assets/34030157/4aa28e7a-fb37-43fa-8ad4-629e857d1d3a)

Folder 1 disappears instead of the file
![image](https://github.com/NixOS/nixpkgs/assets/34030157/b69db6e5-c912-4c5c-81a9-7e27d81028ae)

Pressing undo and now the file is duplicated
![image](https://github.com/NixOS/nixpkgs/assets/34030157/cfdadd6b-a56d-4914-91f8-3ab6a35dd122)

Leaving and returning to the folder and it returns to how it should be
![image](https://github.com/NixOS/nixpkgs/assets/34030157/58745876-0146-4d9a-b253-7edeef51eee2)

### Additional context
This consistently happens on 3 different machines that I use.
My system flake is here https://github.com/justryanw/Flake

### Notify maintainers

@bobby285271 @hedning @dasj19 @maxeaubrey

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.05 (Stoat), 23.05.20230520.3005f20`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/nautilus/-/issues/2945, fix should be a patch in gtk4.
