### ISSUE TITLE
Python 3.4 broken (pyexpat)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#23325]
## Issue description

https://github.com/NixOS/nixpkgs/pull/22585#issuecomment-283264846

Example: http://hydra.nixos.org/build/49482784

- Master and 17.03

**Comment by globin** [comment]
How far are you at fixing this?

**Comment by FRidh** [comment]
Fixed with b588ed9

**Comment by Mic92** [comment]
also happens in python 3.6: https://github.com/NixOS/nixpkgs/issues/23406

**Comment by Mic92** [comment]
This also needs to ported to `17.03` when it leave staging.

**Comment by Mic92** [comment]
I open this issue again, so that we do not forget the backport.

**Comment by vcunat** [comment]
Done. https://github.com/NixOS/nixpkgs/pull/22585#issuecomment-283984867

**Comment by Mic92** [comment]
@vcunat it is not yet in master, right?

**Comment by vcunat** [comment]
Yes, it's the first commit in `master..staging` ATM.

**Comment by vcunat** [comment]
It was merged to master now.

**Comment by Mic92** [comment]
@vcunat thanks!
