### ISSUE TITLE
Build failure: linuxKernel.kernels.linux_5_4_hardened 

### ISSUE THREAD

**Issue by erdnaxe** [NixOS/nixpkgs#233268]
### Steps To Reproduce

1. build *linuxKernel.kernels.linux_5_4_hardened* (with `NIXPKGS_ALLOW_BROKEN=1`)

### Build log

```
[...]
QUESTION: Debug boot parameters, NAME: DEBUG_BOOT_PARAMS, ALTS: Y/n/?, ANSWER: 
GOT: 
QUESTION: CPA self-test code, NAME: CPA_DEBUG, ALTS: N/y/?, ANSWER: 
GOT: 
QUESTION: Debug low-level entry code, NAME: DEBUG_ENTRY, ALTS: N/y/?, ANSWER: 
GOT: 
QUESTION: NMI Selftest, NAME: DEBUG_NMI_SELFTEST, ALTS: N/y/?, ANSWER: 
GOT: 
QUESTION: Debug the x86 FPU code, NAME: X86_DEBUG_FPU, ALTS: Y/n/?, ANSWER: 
GOT: 
QUESTION: ATOM Punit debug driver, NAME: PUNIT_ATOM_DEBUG, ALTS: M/n/y/?, ANSWER: 
GOT: 
GOT: Choose kernel unwinder
GOT: > 1. ORC unwinder (UNWINDER_ORC)
GOT:   2. Frame pointer unwinder (UNWINDER_FRAME_POINTER)
CHOICE: 1-2?, ANSWER: 
GOT: 
GOT: #
GOT: # configuration written to .config
GOT: #
GOT: make: Leaving directory '/build/linux-5.4.240'
warning: unused option: DEBUG_INFO_BTF
warning: unused option: INET_DIAG_DESTROY
warning: unused option: INET_MPTCP_DIAG
warning: unused option: INET_RAW_DIAG
warning: unused option: INET_TCP_DIAG
warning: unused option: INET_UDP_DIAG
warning: unused option: IO_STRICT_DEVMEM
error: unused option: REFCOUNT_FULL
warning: unused option: SECURITY_WRITABLE_HOOKS
warning: unused option: STRICT_DEVMEM
```

### Additional context

This causes many failure in Hydra (one per module).
The non-hardened version works fine.
Other kernel versions work fine.

### Notify maintainers

@TredwellGit 
@Ma27 
@NeQuissimus 
@alyssais 
@thoughtpolice 

@RaitoBezarius (for previous ZHF discussion)

ZHF: https://github.com/NixOS/nixpkgs/issues/230712

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.13, NixOS, 22.11 (Raccoon), 22.11.20230430.db1e4ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by erdnaxe** [comment]
This is linked with commit bfef542b67ccfff0cfdc6f827db72910c965092e (Feb 21 23:41:34 2023): "use meta.broken, not assert"

**Comment by erdnaxe** [comment]
linuxKernel.kernels.linux_5_4_hardened was introduced in 3af43aa8792e654f77f3e63749a6d0f5b948fb70 and seems to build fine at this commit. I am going to `git bisect` from this point.

**Comment by erdnaxe** [comment]
The commit breaking linuxKernel.kernels.linux_5_4_hardened is 52f8cf58a4504e5e219faebffa51033e400e3aec (found via bisect).

**Comment by Kiskae** [comment]
Could this be the same as #232303?
Since the build failure is actually in `kernel.configfile`, not the actual kernel build.

**Comment by erdnaxe** [comment]
I confirm that the build failure is *linuxKernel.kernels.linux_5_4_hardened.configfile*.

It seems that `pkgs/top-level/linux-kernels.nix` specifies that `linux_5_4_hardened` uses gcc10:
```nix
     linux_5_4_hardened = recurseIntoAttrs (hardenedPackagesFor kernels.linux_5_4 {
       stdenv = gcc10Stdenv;
       buildPackages = buildPackages // { stdenv = buildPackages.gcc10Stdenv; };
     });
```
but adding `echo ${buildPackages.stdenv.cc}` in https://github.com/NixOS/nixpkgs/blob/8ee5a6fcbf8d98936fe1a336ac21ef1f31d28310/pkgs/os-specific/linux/kernel/generic.nix#L150 outputs `/nix/store/7wkshj58fcsl1f3zyi67qsxgl1p8nki1-gcc-wrapper-12.2.0`.

There is definitely something off in these Nix expressions. I don't understand why the `configfile` derivation sees gcc12 rather than gcc10.

**Comment by Kiskae** [comment]
`linuxKernel.packages.linux_5_4_hardened.kernel.stdenv.cc`:
> «derivation /nix/store/ch69410hjaid50ahciri4qq5fxwb5dmp-gcc-wrapper-10.4.0.drv»

`linuxKernel.kernels.linux_5_4_hardened.stdenv.cc`
> «derivation /nix/store/c3hq1kg9ylf72b2rp0n6xj13nl8zd8xf-gcc-wrapper-12.2.0.drv»

It looks like there is another definition here which doesn't override the stdenv:
https://github.com/NixOS/nixpkgs/blob/859e3f35c8877a5c55585ca15c6956b4fc255102/pkgs/top-level/linux-kernels.nix#L266

But since the failures are happening in the kernel package-set, I don't believe the kernel with the missing stdenv is related.
