### ISSUE TITLE
Package request: shell-mommy

### ISSUE THREAD

**Issue by dch82** [NixOS/nixpkgs#233259]
**Project description**

From the project website:
> This is a shell script that provides a `mommy` function which emulates a nurturing and supportive figure. The `mommy` function can be used to offer praise and encouraging responses to a user's actions, depending on the exit status of the command that is passed to it.

**Metadata**

* homepage URL: https://github.com/sudofox/shell-mommy
* source URL: https://github.com/sudofox/shell-mommy
* license: IDK; doesn't say on website
* platforms: everything (with a shell on it)

**Comment by donovanglover** [comment]
Not `shell-mommy` but seems to have more features and a license: https://github.com/NixOS/nixpkgs/pull/250034

**Comment by dch82** [comment]
Hmm... Ok, I will close this issue.
