### ISSUE TITLE
diffoscope: building suggests to adding "tools" to allowUnfreePredicate

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#233278]
### Describe the bug
`diffoscope` now depends on an unfree package named `tools` -- a too generic name to be used meaningfully in allowUnfreePredicate.

(Related: the fact that using diffoscope now requires accepting an unfree license is a regression since NixOS 22.11.)

### Steps To Reproduce
```
$ nix-build -A diffoscope
error: Package ‘androidsdk’ in /home/bf/nixpkgs/pkgs/development/mobile/androidenv/deploy-androidpackages.nix:64 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "tools"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

### Expected behavior
Packages having somewhat unique names, allowing `allowUnfreePredicate` to be used meaningfully.

### Notify maintainers

@dezgeg @danielfullmer

**Comment by bjornfor** [comment]
Bisecting diffoscope eval leads to 9c4e43ab70c506875684619f30d6d16f093e87d5 being the first bad commit (CC @hadilq).

**Comment by hadilq** [comment]
@bjornfor there are different answers on different levels:

- `tools` is the name of that package in the Android SDK, however, I can change the derivation's name to something like `androidenv-tools`, and if it doesn't break anything I'll create the PR, but first you need to confirm this is what you are asking here.

- as far as I remember, androidenv required `allowUnfree` before I applied any changes, so I don't understand why you found my commit!

- I have no clue what's  `allowUnfreePredicate`!

If none of the above answers are useful, please explain more.

**Comment by bjornfor** [comment]
> tools is the name of that package in the Android SDK, however, I can change the derivation's name to something like androidenv-tools, and if it doesn't break anything I'll create the PR, but first you need to confirm this is what you are asking here.

Yes, that sounds perfect.

**Comment by bjornfor** [comment]
> tools is the name of that package in the Android SDK, however, I can change the derivation's name to something like androidenv-tools, and if it doesn't break anything I'll create the PR, but first you need to confirm this is what you are asking here.

If some code relies on the `pname`, you might want to add `meta.mainProgram = "tools"` or something, to keep `lib.getExe androidDerivationThingy` working after changing `pname`.

**Comment by RaitoBezarius** [comment]
I had #221861 for this, but really I had no time with all the work. :/

**Comment by hadilq** [comment]
Please review https://github.com/NixOS/nixpkgs/pull/233461

**Comment by bjornfor** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/233461 (and https://github.com/NixOS/nixpkgs/pull/221861). Closing.
