### ISSUE TITLE
Cider: 1.6.0->1.6.1 version bump causes error on launch-fails to start application

### ISSUE THREAD

**Issue by Selmer443** [NixOS/nixpkgs#233327]
### Describe the bug
Cider application fails to start providing this error: 
`/nix/store/75ylj23za2hpr8shms7i28ma58qxvjbc-cider-1.6.1-init: line 19: /home/selmer/download/appimage-exec.sh -w /nix/store/bya3wm74vxxxp3bcbp0wpawx9icymcsz-cider-1.6.1-extracted --: No such file or directory`

This error was not present on my system when using cider 1.6.0, moving to 1.6.1 causes this issue for me.

### Steps To Reproduce
Install Cider package 1.6.1 using nixpkgs unstable

### Expected behavior
App should start and launch normally

### Notify maintainers
@cigrainger 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.3.3, NixOS, 23.05 (Stoat), 23.05.20230520.3005f20`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.15.0`
- nixpkgs: `/nix/store/ivbddh1g0p4rc85lksflqp2clcpfqfp3-source`
```

**Comment by gaykitty** [comment]
Fixed by #233209
