### ISSUE TITLE
Neomutt is broken

### ISSUE THREAD

**Issue by asdf8dfafjk** [NixOS/nixpkgs#233347]
This commit will be branched off for 23.05 today. https://github.com/NixOS/nixpkgs/commit/e43f1587688e6b3b61ae6b861a37c8a69f58022b 

However, the commit message of this commit points here https://github.com/neomutt/neomutt/releases/tag/20230512  which says that the src used in the said commit is buggy.  

Tagging: https://github.com/NixOS/nixpkgs/issues/223562 (sorry I don't deal with nixos github regularly much these days so don't know if I'm doing this right).

**Comment by RaitoBezarius** [comment]
Fixing this in few minutes.

**Comment by RaitoBezarius** [comment]
https://github.com/NixOS/nixpkgs/pull/233363

**Comment by RaitoBezarius** [comment]
Doesn't work for aarch64-darwin, x86_64-darwin for now.

**Comment by kciredor** [comment]
Indeed Darwin x86-64 build is broken :-(

**Comment by ahmedelgabri** [comment]
@RaitoBezarius Can you link to the upstream issue/pr? Because looks like it's working fine in MacPorts for example https://github.com/NixOS/nixpkgs/issues/232074#issuecomment-1572961562

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius Can you link to the upstream issue/pr? Because looks like it's working fine in MacPorts for example [#232074 (comment)](https://github.com/NixOS/nixpkgs/issues/232074#issuecomment-1572961562) also home-manager [#232074 (comment)](https://github.com/NixOS/nixpkgs/issues/232074#issuecomment-1572961562)

It was said to me on IRC by NeoMutt developers but I may have misinterpreted.

**Comment by kciredor** [comment]
Hi there. Could it be they (on irc) referred to the old release being broken? I can't imagine the new release being broken for so long upstream, the latest release was a fix release after all.

**Comment by dbaynard** [comment]
> @RaitoBezarius Can you link to the upstream issue/pr? Because looks like it's working fine in MacPorts for example [#232074 (comment)](https://github.com/NixOS/nixpkgs/issues/232074#issuecomment-1572961562) also home-manager [#232074 (comment)](https://github.com/NixOS/nixpkgs/issues/232074#issuecomment-1572961562)

That home manager link is wrong. I only showed it would work on macports. I had to roll back my own nix version.

I don't think it's an upstream issue; I think it's to do with the nix derivation. But I haven't looked into it.
