### ISSUE TITLE
Lisp-module's build-asdf-system's flags attribute is ignored.

### ISSUE THREAD

**Issue by dariof4** [NixOS/nixpkgs#233465]
### Describe the bug
The flags attribute of build-asdf-system overriden by an empty list even when it is set.

### Steps To Reproduce
1. Set the flags attribute in a derivation that uses build-asdf-system
2. `nix eval` the flags attribute of the derivation
3. The attribute is set to an empty list

### Expected behavior
The flags attribute is equal to what was set in the derivation.

### Additional context
Here's a random example of a derivation with a flags attribute where `nix eval flags` returns an empty list:
```
{ pkgs ? import <nixpkgs> { } }:

pkgs.sbcl.buildASDFSystem {
  pname = "tuple";
  version = "b74bd067d";
  flags = [ "some" "random" "flags" ];
  src = pkgs.fetchzip {
    url = "https://fossil.galkowski.xyz/tuple/tarball/b74bd067d4533ac0/tuple.tar.gz";
    sha256 = "0dk356vkv6kwwcmc3j08x7143549m94rd66rpkzq8zkb31cg2va8";
  };

}
```
I'm trying to update the nyxt package to 3.0.0, but it's failing with a `Heap exhausted during garbage collection`, so I'd need to run with a larger dynamic memory size using the `--dynamic-space-size` flag, but when I try to set the flags attribute it gets overriden by an empty list.
It seems like the problem is in `nix-cl.nix`, specifically in this piece of code (and probably the others like it that do `body // spec`):
```
  commonLispPackagesFor = spec:
    let
      build-asdf-system' = body: build-asdf-system (body // spec);
    in pkgs.callPackage ./packages.nix {
      inherit spec quicklispPackagesFor;
      build-asdf-system = build-asdf-system';
    };
```
it seems like the flags attribute in `body` gets overriden by the one set in `spec`, since swapping them around fixes the issue (though it may undesired effects, I'm not sure).
### Notify maintainers

@raskin @lukego @nagy @uthar @hraban

### Metadata
Not relevant.

**Comment by Uthar** [comment]
It's the correct behavior. The right place to use `flags` is from `wrapLisp`. 

For example:

```nix
let
  sbcl' = wrapLisp {
    pkg = sbcl;
    faslExt = "fasl";
    flags = [ "--dynamic-space-size" "4096" ];
  };
in sbcl'.pkgs.nyxt
```

Sorry, it wasn't so clear in the manual. Please let me know if it's clearer like this, or if you would word it differently: https://github.com/NixOS/nixpkgs/pull/233672/files

**Comment by Uthar** [comment]
Hmm, I think wrapLisp in default.nix will have less impact on binary cache, because only the dependencies of nyxt will be rebuilt. On the other hand, currently magicl is broken because of heap exhaustion, so increasing it globally would fix that. I'm not sure which is the best
