### ISSUE TITLE
Package request: NetworkMiner

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#233414]
**NetworkMiner**

NetworkMiner is an [open source](https://www.netresec.com/?page=NetworkMinerSourceCode) network forensics tool that extracts artifacts, such as files, images, emails and passwords, from captured network traffic in PCAP files. NetworkMiner can also be used to capture live network traffic by sniffing a network interface. Detailed information about each IP address in the analyzed network traffic is aggregated to a network host inventory, which can be used for passive asset discovery as well as to get an overview of which devices that are communicating. NetworkMiner is primarily designed to run in Windows, but can also be used in [Linux](https://www.netresec.com/?page=Blog&month=2014-02&post=HowTo-install-NetworkMiner-in-Ubuntu-Fedora-and-Arch-Linux).

**Metadata**

* homepage URL: https://www.netresec.com/?page=NetworkMiner
* source URL: https://www.netresec.com/?page=Blog&month=2014-02&post=HowTo-install-NetworkMiner-in-Ubuntu-Fedora-and-Arch-Linux
* platforms: linux

**Comment by Raymond-Reddingtonjr** [comment]
Is there a docker image made for network miner?
