### ISSUE TITLE
nixos-rebuild results in system shutdown

### ISSUE THREAD

**Issue by Yury-Zakharov** [NixOS/nixpkgs#23357]
## Issue description
Running sudo nixos-rebuild results in system shutdown.
Here is the output:

> building Nix...
> building the system configuration...
> stopping the following units: -.slice, acpid.service, alsa-store.service, cpufreq.service, cups.service, dbus-org.bluez.service, ip-up.target, kmod-static-nodes.service, network-local-commands.service, network-setup.service, nix-daemon.service, nix-daemon.socket, nscd.service, ntpd.service, rtkit-daemon.service, systemd-modules-load.service, systemd-sysctl.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, systemd-vconsole-setup.service, udisks2.service, upower.service, wpa_supplicant.service
> /nix/store/7477602hk149iq631fyf0dvn28gf0zf0-nixpkgs-17.09pre102350.fa03b82/nixpkgs/nixos/modules/installer/tools/nixos-rebuild.sh: line 235:  3106 Hangup                  "$@"
> 
> 

### Steps to reproduce
sudo nixos-rebuild

## Technical details

* System: 16.03pre73106.b1dca6c (Emu)
* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: 17.03pre101839.53a2baa

**Comment by vcunat** [comment]
If you're attempting to switch from 16.03 to 17.03, I'd *personally* recommend to use `nixos-rebuild boot` for such big upgrades instead of `nixos-rebuild switch`.  (That is not to say we don't want it to work, but it just *is* less reliable for large changes.)

**Comment by Yury-Zakharov** [comment]
Solved by upgrading gradually. 
From 16.03 Unstable to 16.03 Stable to 16.09 Stable
In my understanding the issue still remains if you are trying to skip several versions when upgrading.
