### ISSUE TITLE
joplin-desktop fails to start: `appimage-exec.sh` no such file or directory

### ISSUE THREAD

**Issue by a-0-dev** [NixOS/nixpkgs#233776]
### Describe the bug
Starting the joplin-desktop app either using gnome launcher or by running `joplin-desktop` in the terminal results in the error
```
/nix/store/a6jvhk554wcaaqsizvg16fqa1s3zxhfj-joplin-desktop-2.10.18-init: line 19: /home/a-0/appimage-exec.sh -w /nix/store/m6gakkjqqb00jfv94ypiy8czqnxw2062-joplin-desktop-2.10.18-extracted --: No such file or directory
```

It worked in previous versions on the same machine though.

### Additional context
I updated my system flake today, the app started properly before (only on second execution of the command, but it started)

### Notify maintainers
@mweinelt  (maybe?)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.3, NixOS, 23.05 (Stoat), 23.05.20230522.7084250`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

**Comment by gaykitty** [comment]
Fixed by #233209
