### ISSUE TITLE
Monitors do not wake up from sleep with nouveau and kernels 4.9 and 4.10

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#23384]
## Issue description

I'm logging this in here for tracking purposes.

With kernels 4.9 and 4.10, nouveau throws errors in the journal and makes it impossible to wake up monitors that have gone to sleep. They happens after either regular suspend/resume or at times simply if the screenlocker kicks in which case the screenlocker is still showing, but there is no way to interact with it. Sometimes it is possible to ssh in to run "loginctl unlock-sessions" and other times not.

The error in the journal:

```
nouveau 0000:01:00.0: fifo: PBDMA0: 04000000 [ACQUIRE] ch 2 [003fa63000 X[1056]] subc 0 mthd 0000 data 00000000
```

There is an upstream bug that matches: https://bugs.freedesktop.org/show_bug.cgi?id=99900

### Steps to reproduce

1) run nixos-unstable
2) use nouveau
3) wait for monitors to enter power-save mode

## Hardware

- self-built desktop
- ```01:00.0 VGA compatible controller: NVIDIA Corporation GK107 [GeForce GTX 650] (rev a1)```
- Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
- Asus Z97-PRO motherboard

## Technical details

* NixOS: 17.03.git.598b9810c3M (Gorilla)
* Nix: nix-env (Nix) 1.11.6
* nixpkgs: 17.03.git.598b9810c3M

**Comment by dtzWill** [comment]
1) Does the hang happen with 4.9 (or any other version) as well?

2) What hardware do you have? I ask both for the general information and because if you /happen/ to have the new XPS15 there's a problem that looks a fair bit like this (hanging when resuming from suspend) that needs to be fixed with a kernel parameter (or a patch). Probably not related but thought I'd mention it JIC :).

**Comment by peterhoeg** [comment]
@dtzWill, I've updated the entry above with more details (yes, 4.9 as well and a gtx650)

My *workaround* was to use the binary nvidia driver, but that doesn't work with 4.10.

**Comment by dtzWill** [comment]
Looking through the linked issue (and ones it links to) it seems there were patches merged that may resolve this.

I haven't chased down which patches made it to which releases but... can you confirm if this is still a problem for you on any of the current NixOS kernels?

**Comment by peterhoeg** [comment]
It is. Although I would really like to be able to recommend nouveau to everyone, it's just not there. Random hangs (where the screen stops updating but you can otherwise SSH in) happen about once a week on average. Nouveau is the ideological choice - not the logical one...

That being said, I still have used it exclusively on my desktop for the last year or so.

**Comment by vcunat** [comment]
I think I got this with 4.14 as well.

**Comment by Enteee** [comment]
The tracker where this bug is tracked has moved to [gitlab](https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/issues/325)

Can somebody confirm that this is still an issue on current unstable?

cc @peterhoeg , @vcunat

**Comment by vcunat** [comment]
I no longer use any Nvidia (on Linux).  _That decade-old notebook is now only for emergency when I need Windows._

**Comment by peterhoeg** [comment]
I'm not using any nvidia hardware any longer either.

**Comment by vcunat** [comment]
Let's close until someone confirms the issue.
