### ISSUE TITLE
bukut has been archived, remove it ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#233894]
## Issue description

@tgharib  do you still use bukut ? I just noticed the project was archived https://github.com/peterjschroeder/bukut . If the software is useful I wouldn't mind keeping it but the added value looks think compared to buku or rofi-buku etc. Do you still use it/should we remove it

**Comment by tgharib** [comment]
I don't. I would appreciate its removal. If not, I can remove it.

**Comment by figsoda** [comment]
#233912

**Comment by teto** [comment]
this (fig)soda is lethal ! well done
