### ISSUE TITLE
kdenlive is marked broken

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#23399]
## Issue description
It uses ``phonon-backend-vlc``, which uses ``vlc``, which is [marked broken](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/vlc/default.nix#L79) when used with ``qt 5.7.0``.
I've tried building with another qt but have failed so far.

If someone gives me a pointer I'll fix it for [17.03](https://github.com/NixOS/nixpkgs/issues/23253).

## Technical details

* System: 17.03.git.930fe75
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: warning: Nix search path entry ‘/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs’ does not exist, ignoring
"17.03pre102030.8b40d2e"

**Comment by ttuegel** [comment]
Why does it use `phonon-backend-vlc`? If at all possible, it should use `phonon-backend-gstreamer`. They should be completely interchangable.

**Comment by magnetophon** [comment]
@ttuegel Thanks, I'll try that.
