### ISSUE TITLE
fcitx do not build because fcitx-qt5 is missing

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#23395]
## Issue description
Seems nixpkgs/pkgs/tools/inputmethods/fcitx/wrapper.nix cannot find qt55.fcitx-qt5
```
error: attribute ‘fcitx-qt5’ missing, at /nix/store/65baqydk8xpzj9radfdi232yhxwk290f-nixos-17.09pre102441.45344fd/nixos/pkgs/tools/inputmethods/fcitx/wrapper.nix:6:36
```
Not sure what is the best way to fix this.

### Steps to reproduce
configuration.nix:
```
i18n.inputMethod = {
  enabled = "fcitx";
  fcitx.engines = with pkgs.fcitx-engines; [ chewing mozc ] ;
};
```
Then `nixos-rebuild build`
## Technical details

* Nixpkgs version: `17.09pre102441.45344fd`

cc @ericsagnes , thank you very much

**Comment by sib-null** [comment]
I have the exact same problem.  

I'm new to Nix and NixOS, so I may be interpreting this wrong, but I do have a `fcitx-qt5 `located in my nixstore: 

    /nix/store/b7hgv496kyyiay5zxcjychyq27m989d6-nixos-17.09pre102441.45344fd/nixos/pkgs/tools/inputmethods/fcitx/fcitx-qt5.nix

So I'm not sure what is missing.

**Comment by ericsagnes** [comment]
Thanks for reporting. I will look into this.
It seems that `qt5.fcitx-qt5` changed for `libsForQt5.fcitx-qt5`, will test and make a PR when I get it working.

**Comment by ericsagnes** [comment]
@sifmelcara @sib-null 
If you need a quickfix, rebuild nixos with #23411 applied.
