### ISSUE TITLE
PAM mount no longer able to open LUKS

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#233946]
### Describe the bug
Since #232873, `mount.crypt` fails to open LUKS home directories when invoked via `pam_mount`.

### Steps To Reproduce
1. Have a machine with `security.pam.mount.enable = true;` and `users.users.<name>.pamMount` set up.
2. Rebuild
3. Check logs

### Expected behavior
PAM mount should still be able to mount my home directory

### Screenshots
```
mai 25 09:19:29 harald lightdm[5232]: pam_unix(lightdm:session): session opened for user louis(uid=1001) by (uid=0)
mai 25 09:19:29 harald lightdm[5232]: (mount.c:68): Messages from underlying mount program:
mai 25 09:19:29 harald display-manager[5232]: (mount.c:68): Messages from underlying mount program:
mai 25 09:19:29 harald display-manager[5232]: (mount.c:72): /nix/store/xhyc7f22rd1yrig9f5f9a8yws4jj0m2h-pam_mount-2.19/bin/mount.crypt: You need to specify the mountpoint
mai 25 09:19:29 harald lightdm[5232]: (mount.c:72): /nix/store/xhyc7f22rd1yrig9f5f9a8yws4jj0m2h-pam_mount-2.19/bin/mount.crypt: You need to specify the mountpoint
mai 25 09:19:29 harald lightdm[5232]: (pam_mount.c:522): mount of /persist/home/louis.crypt failed
mai 25 09:19:29 harald display-manager[5232]: (pam_mount.c:522): mount of /persist/home/louis.crypt failed
```

### Additional context
My `cryptMountOptions` is `[]` (default)

### Notify maintainers
@NetaliDev @jzbor @yu-re-ka involved in the PR

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nix/channels/nixos`
```

**Comment by NetaliDev** [comment]
Ahh, I think the problem is, that no options are specified and `mount.crypt` is called as `mount.crypt -o %(VOLUME) %(MNTPT)` so that the volume gets interpreted as a option and the mountpoint gets interpreted as the volume and so the mountpoint parameter is missing for `mount.crypt`.

I think it is fixable by simply putting the options in quotes, so that this empty string will be interpreted as the options. I will try this later today and open a PR if it succeeds.
