### ISSUE TITLE
Package request: sddm-unstable

### ISSUE THREAD

**Issue by aviallon** [NixOS/nixpkgs#233965]
**Project description**

SDDM has not been updated in more than 3 years.
Wayland or even even non-root X11 hasn't landed in any release yet.

This causes issues with some setups, and I currently have to maintain my own SDDM-unstable package.

I thus suggest that a new, `sddm-unstable` package be created, following the project's master or even develop branch.

A new module option could then be created at `services.xserver.displayManager.sddm.package` to use the unstable package instead of the default one if the user so-chooses.

**Metadata**

* homepage URL: https://github.com/sddm/sddm
* source URL: https://github.com/sddm/sddm
* license: gpl2
* platforms: unix, linux

**Comment by alexjp** [comment]
nice :)

may I add a sddm.wayland module option that adds to the sddm.conf: 

```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland_wrapper --no-kactivities --no-lockscreen --locale1
```

or similar (this is just what I am using).

sddm wayland has been working fine for the past few months or so, even with multiple monitors.

**Comment by aviallon** [comment]
@alexjp why do you manually specify the compositor command?
I didn't need to modify anything in `sddm.conf` except for `DisplayServer=wayland`.

Also, I am wondering why you set `GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell`. What does it do?

**Comment by alexjp** [comment]
@aviallon Maybe its not needed now. I have been using wayland sddm for a long time, and it was how i learned to set it up.

from here: https://wiki.archlinux.org/title/SDDM#Running_under_Wayland and several sddm github issues like https://github.com/sddm/sddm/issues/1628 and from invent.kde.org: https://invent.kde.org/plasma/plasma-workspace/-/blob/master/sddm-wayland-session/plasma-wayland.conf

specially, the invent.kde.org file configures it that way, with the exception of the input method.

**Comment by aviallon** [comment]
@alexjp I think you should avoid modifying `CompositorCommand`, as it is already correctly handled by Nix.

I don't know the effects of `GreeterEnvironment` though.

**Comment by aviallon** [comment]
@abbradar @ttuegel Do you have any opinion on this request?

**Comment by K900** [comment]
0.20.0 is out: https://github.com/NixOS/nixpkgs/pull/239389

**Comment by aviallon** [comment]
Just saw that. Should do a PR.

**Comment by aviallon** [comment]
Not useful anymore since 0.20 got out with the required Wayland compatibility.
