### ISSUE TITLE
sssd.service doesn't start anymore

### ISSUE THREAD

**Issue by pjjonas** [NixOS/nixpkgs#233948]
## Issue description
After recent update the sssd.service doesn't start anymore.

Mai 25 10:21:56 s904 sssd_be[24405]: Starting with debug level = 0x0070
Mai 25 10:21:56 s904 sssd_be[24405]: Starting up
Mai 25 10:21:56 s904 sssd_be[24405]: 'files' provider is configured for 'id', but support wasn't built
Mai 25 10:21:56 s904 sssd_be[24405]: Unsupported provider 'files' is used in SSSD config.
Mai 25 10:21:56 s904 sssd_be[24405]: Unable to load DP configuration [1432158263]: Invalid SSSD configuration detected
Mai 25 10:21:56 s904 sssd_be[24405]: Unable to initialize DP targets [1432158263]: Invalid SSSD configuration detected
Mai 25 10:21:56 s904 sssd[24096]: Child [24405] ('FRITZ.BOX':'%BE_FRITZ.BOX') exited with code [3]
Mai 25 10:21:59 s904 sssd[24096]: Providers did not start in time, forcing services startup!
Mai 25 10:21:59 s904 sssd_nss[24406]: Starting with debug level = 0x0070
Mai 25 10:21:59 s904 sssd_nss[24406]: Starting up
Mai 25 10:21:59 s904 sssd_nss[24406]: check_file failed for [/var/lib/sss/pipes/private/sbus-dp_FRITZ.BOX].
Mai 25 10:21:59 s904 sssd_nss[24406]: Failed to connect to backend server.
Mai 25 10:21:59 s904 sssd_nss[24406]: fatal error setting up backend connector
Mai 25 10:21:59 s904 sssd_nss[24406]: sss_process_init() failed
Mai 25 10:21:59 s904 sssd[24096]: Child [24406] ('nss':'nss') exited with code [3]
Mai 25 10:21:59 s904 sssd_pam[24407]: Starting with debug level = 0x0070
Mai 25 10:21:59 s904 sssd_pam[24407]: Starting up
Mai 25 10:21:59 s904 sssd_pam[24407]: check_file failed for [/var/lib/sss/pipes/private/sbus-dp_FRITZ.BOX].
Mai 25 10:21:59 s904 sssd_pam[24407]: Failed to connect to backend server.
Mai 25 10:21:59 s904 sssd_pam[24407]: fatal error setting up backend connector
Mai 25 10:21:59 s904 sssd_pam[24407]: sss_process_init() failed
Mai 25 10:21:59 s904 sssd[24096]: Child [24407] ('pam':'pam') exited with code [3]
Mai 25 10:21:59 s904 sssd_nss[24408]: Starting with debug level = 0x0070
Mai 25 10:21:59 s904 sssd_nss[24408]: Starting up
Mai 25 10:21:59 s904 sssd_nss[24408]: check_file failed for [/var/lib/sss/pipes/private/sbus-dp_FRITZ.BOX].
Mai 25 10:21:59 s904 sssd_nss[24408]: Failed to connect to backend server.
Mai 25 10:21:59 s904 sssd_nss[24408]: fatal error setting up backend connector
Mai 25 10:21:59 s904 sssd_nss[24408]: sss_process_init() failed
Mai 25 10:21:59 s904 sssd[24096]: Child [24408] ('nss':'nss') exited with code [3]
Mai 25 10:21:59 s904 sssd_pam[24409]: Starting with debug level = 0x0070
Mai 25 10:21:59 s904 sssd_pam[24409]: Starting up
Mai 25 10:21:59 s904 sssd_pam[24409]: check_file failed for [/var/lib/sss/pipes/private/sbus-dp_FRITZ.BOX].
Mai 25 10:21:59 s904 sssd_pam[24409]: Failed to connect to backend server.
Mai 25 10:21:59 s904 sssd_pam[24409]: fatal error setting up backend connector
Mai 25 10:21:59 s904 sssd_pam[24409]: sss_process_init() failed
Mai 25 10:21:59 s904 sssd[24096]: Child [24409] ('pam':'pam') exited with code [3]
Mai 25 10:22:00 s904 sssd_be[24410]: Starting with debug level = 0x0070
Mai 25 10:22:00 s904 sssd_be[24410]: Starting up
Mai 25 10:22:00 s904 sssd_be[24410]: 'files' provider is configured for 'id', but support wasn't built
Mai 25 10:22:00 s904 sssd_be[24410]: Unsupported provider 'files' is used in SSSD config.
Mai 25 10:22:00 s904 sssd_be[24410]: Unable to load DP configuration [1432158263]: Invalid SSSD configuration detected
Mai 25 10:22:00 s904 sssd_be[24410]: Unable to initialize DP targets [1432158263]: Invalid SSSD configuration detected
Mai 25 10:22:00 s904 sssd[24096]: Child [24410] ('FRITZ.BOX':'%BE_FRITZ.BOX') exited with code [3]
Mai 25 10:22:00 s904 sssd[24096]: Process [FRITZ.BOX], definitely stopped!
Mai 25 10:22:00 s904 sssd[24096]: Exiting the SSSD. Could not restart critical service [FRITZ.BOX].
Mai 25 10:22:00 s904 sssd[24096]: Returned with: 1
Mai 25 10:22:00 s904 sssd[24096]: Terminating [pam][24409]
Mai 25 10:22:00 s904 sssd[24096]: Terminating [nss][24408]
Mai 25 10:22:00 s904 sssd[24096]: Error removing pidfile! (2 [No such file or directory])
Mai 25 10:22:00 s904 systemd[1]: sssd.service: Control process exited, code=exited, status=1/FAILURE

### Steps to reproduce

Update system

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.3, NixOS, 23.11 (Tapir), 23.11.20230524.f91ee30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(...): `""`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(...): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tomodachi94** [comment]
Pinging package maintainer @illustris. Also pinging @outergod, @arianvp, @flokli, who have worked on the module.

**Comment by illustris** [comment]
I'm not able to reproduce this issue. Can you share your sssd configs?
Also, you seem to be using a very outdated nixpkgs-unstable from May 2023. Did you try updating to either nixos-23.11 or the latest nixos-unstable?
```
commit f91ee3065de91a3531329a674a45ddcb3467a650 (HEAD)
Merge: 3a1b5769ad4e 729a169debd0
Author: Weijia Wang <9713184+wegank@users.noreply.github.com>
Date:   Wed May 24 16:37:59 2023 +0300

    Merge pull request #233806 from wegank/edge-bump

    microsoft-edge: 113.0.1774.42 -> 113.0.1774.50
```

**Comment by pjjonas** [comment]
It's working again, thanks!
