### ISSUE TITLE
PPSSPP-Qt missing app icon

### ISSUE THREAD

**Issue by DGSZink** [NixOS/nixpkgs#234056]
### Describe the bug
Missing application icon.
I looked at the ".desktop" file and inside is written "Icon = ppsspp", but I can't find an icon with that name.

### Steps To Reproduce
1. Search for "ppsspp" in KDE/Gnome or using anything that can show app icons.
2. Icon isn't shown, for example, on Gnome it just shows the default icon for binaries.

### Expected behavior
The icon appears when searching for the app.

### Notify maintainers
@AndersonTorres

### Metadata
Please run nix-shell -p nix-info --run "nix-info -m" and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.3-xanmod1, NixOS, 23.11 (Tapir), 23.11.20230524.f91ee30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/38rzi6kzh5ilbpdgpvd8aj34vksgkcfa-source`
```

**Comment by OPNA2608** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/23431373/89bbeb66-1fe2-4787-9e5b-9bc4d70a8da0)

There should be `share/icons/hicolor/<resolution>/apps/ppsspp.<format>`. Upstream has a `icons/hicolor/` directory which can be copied over as-is in the custom `installPhase`: https://github.com/hrydgard/ppsspp/tree/v1.15.3/icons/hicolor

**Comment by KarkanAlzwayed** [comment]
> ![image](https://user-images.githubusercontent.com/23431373/241039400-89bbeb66-1fe2-4787-9e5b-9bc4d70a8da0.png)
> 
> There should be `share/icons/hicolor/<resolution>/apps/ppsspp.<format>`. Upstream has a `icons/hicolor/` directory which can be copied over as-is in the custom `installPhase`: https://github.com/hrydgard/ppsspp/tree/v1.15.3/icons/hicolor

Hi, could you please explain this a little more? I went into usr/share/icons/hicolors, but I'm not sure what to do after that? You said that folder should be copied over. Where do I copy it over? What am I copying over and to where? Could you please elaborate more?
Thank you!
