### ISSUE TITLE
appimageTools.wrapType2 produces bad executable (appimage-exec.sh: No such file or directory)

### ISSUE THREAD

**Issue by robwhitaker** [NixOS/nixpkgs#234078]
### Describe the bug

Packages created via the `appimageTools.wrapType2` builder (and maybe other AppImage wrappers) fail to run the `appimage-exec.sh` script at runtime.

For example, when running the `mudlet` AppImage, I get the output:

```
/nix/store/qphyn01qrw8fnsw7d5s0viffnscv6cb4-mudlet-init: line 19: /home/rob/dotfiles/appimage-exec.sh -w /nix/store/lz1hgsd9nvqpqyns63xh7mpm5q00bmb6-mudlet-extracted --: No such file or directory
```

This occurs because it tries to run `appimage-exec.sh` from whatever directory I'm currently in (e.g. `/home/rob/dotfiles` or `/home/rob/Downloads`) instead of properly looking for the script in the Nix store.

### Steps To Reproduce

1. Create an AppImage derivation via `appimageTools.wrapType2`, doesn't matter what the AppImage is.
2. Try to run it.

### Expected behavior

The executable should find `appimage-exec.sh` in the Nix store and therefore run properly.

### Notify maintainers

@prusnak @Atemu 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.05 (Stoat), 23.05.20230522.c7eb652`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - channels(rob): `""`
 - nixpkgs: `/nix/store/18zsdx5bbf2xmxz6babq2qkmaadn0krk-source`
```

**Comment by Atemu** [comment]
Should have already been fixed by https://github.com/NixOS/nixpkgs/pull/233209 which is in unstable. Please update your channels.

**Comment by robwhitaker** [comment]
@Atemu Yup, that fixed it! I updated my unstable branch on Wednesday (the 24th), so I must have just missed that PR getting into unstable.

Sorry about the extra opened issue. I think I was searching for issues with `appimageTools` instead of `appimage-exec.sh` in the title, so not much came up.

I'll close this now. Thanks!
