### ISSUE TITLE
BeatSaberModManager: xdg-utils required for OneClick support

### ISSUE THREAD

**Issue by MyBeansAreBaked** [NixOS/nixpkgs#234039]
## Issue description
BeatSaberModManager does not launch without having xdg-utils installed.

### Steps to reproduce
Add BeatSaberModManager to package list, but not xdg-utils, try to run it. It exits with error code 255.
A log file is created containing:
`An error occurred trying to start process 'xdg-mime'`

run in `nix-shell -p xdg-utils`, and it runs with no issue.

I would make a PR, but when I tried to build the package, I got `error: attribute 'systemToDotnetRid' missing` and do not have time right now to debug.

ping maintainer: @Atemu 

Thanks.

**Comment by Atemu** [comment]
Thanks for the report, I'll take a look!

**Comment by Atemu** [comment]
I am not able to reproduce this issue on 2371c5d4659e31386d3565de6d0c3120312c34e7. I have moved my `~/.config/BeatSaberModManager` and can run `PATH= /nix/store/j00bz8d1k744w91i4z0436829ia4w3rs-BeatSaberModManager-0.0.5/bin/BeatSaberModManager` without issue.

**Comment by Atemu** [comment]
Aha, you need to enable OneClick support and then restart the app for this error to manifest itself.
