### ISSUE TITLE
hack-font: not found by Gnome (or any other app probably)

### ISSUE THREAD

**Issue by starquake** [NixOS/nixpkgs#234151]
### Describe the bug
After installing the hack font it can not be found. Probably because it's installed in the wrong folder.

### Steps To Reproduce
1. Install font-hack
2. Open up Gnome Font application
3. Look for the font hack and see it's not there
4. Run `ls /run/current-system/sw/share/fonts/` and see it's in a separate directory `/run/current-system/sw/share/fonts/hack` next to `/run/current-system/sw/share/fonts/truetype`

### Expected behavior
Font should show up in Gnome Font and other applications

### Additional context
Running nixos 23.05 beta

### Notify maintainers
@dywedir 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.05 (Stoat), 23.05beta114.3e01645c40b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MartinLoeper** [comment]
For me it seems to work when adding: 
```
  fonts.packages = [
    pkgs.hack-font
  ];
```

**Comment by dywedir** [comment]
Yeah, `fonts.packages` rearranges font files anyway. 
But it seems like a good idea to unify the output directory with other fonts.
