### ISSUE TITLE
Resend missed Nixpkgs Maintainers organization invites

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs#234293]
The automated NixOS organization invites set up after https://github.com/NixOS/rfcs/pull/39 do not allow eligible users to request an invite again in case they missed it. Ideally there should be automation to allow such users to request another invite, but alternatively a manual solution works too.

This is now the case for at least two users, @ners (who asked me personally) and @hellwolf (see [here](https://discourse.nixos.org/t/join-the-package-maintainer-team/3751/63)). If you're also affected by this issue, please leave a comment.

Due to the fact that the implementation for these automatic invites appears to be [entirely closed-source](https://github.com/NixOS/nixos-org-configurations/blob/f27bdec45066d828dba681cc0d2655a4ad8edb0e/modules/rfc39.nix#L4) (Edit: Turns out some version of the source is at least [here](https://github.com/NixOS/rfc39)), there's no way for anybody to fix this themselves. It also appears that @grahamc is the sole person responsible for maintaining this, but I haven't gotten a response for 2 weeks now after asking to re-invite a user manually.

**Comment by alyssais** [comment]
> alternatively a manual solution works too.

The manual solution is to ask any other org owner to issue an invite, no?

**Comment by hellwolf** [comment]
Is it possible to create a github workflow that would have the permission to create invite?

**Comment by infinisil** [comment]
It looks like GitHub workflows can only be triggered by people with write access to the repo: https://github.com/orgs/community/discussions/49688, so this wouldn't work. The suggested workaround is to use issues instead. I'm guessing we could set it up so that people can get a re-invite by commenting in this thread: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment

**Comment by 06kellyjac** [comment]
I personally had this issue too. Due to github email spam I mostly rely on GH notifications in the web ui but for some reason the invites don't show there.
I also wasn't expecting an immediate invite from being added to `maintainer-list.nix` and expected it to come later after some consistent contribution

Maybe mentioning "expect a github org invite in your emails" in this header: https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix#L1-L59
And maybe adding some of this comment to `CONTRIBUTING.md` would be good?

> I'm guessing we could set it up so that people can get a re-invite by commenting in this thread

That sounds good but maybe not just any comment? Maybe a specific format

**Comment by hellwolf** [comment]
I am hitting this problem again, I'd like to configure the backport label to https://github.com/NixOS/nixpkgs/pull/237722

Anything short term I could do to unblock myself being able to self service my package maintainer duties?

**Comment by 06kellyjac** [comment]
To label you need to be in the org, to be in the org you need to post here, not really an alternative other than posting elsewhere too.

If you really want a short term solution an option you have right now is to backport the changes yourself without the label automation but it's a bit more effort.
Go to release branch -> make new branch -> cherry pick commit you want -> push -> create PR against release branch

**Comment by hellwolf** [comment]
> To label you need to be in the org, to be in the org you need to post here, not really an alternative other than posting elsewhere too.

Okay.. can I haz org membership now pls?

**Comment by Artturin** [comment]
Im guessing the reason for missing some of them is that the github api is unstable and misses events

**Comment by infinisil** [comment]
I asked an org admin to add you manually @hellwolf, can you confirm that it worked?

**Comment by hellwolf** [comment]
@infinisil yes, confirmed! Thank you all!

**Comment by rardiol** [comment]
Please invite me

**Comment by NotAShelf** [comment]
I hate to piggyback this, but I've previously failed to establish communication with an org owner. I would also like an invitation, if possible.

**Comment by zimbatm** [comment]
Invited rardiol and [NotAShelf](https://github.com/NotAShelf)

**Comment by NotAShelf** [comment]
Got it, thank you.

**Comment by frogamic** [comment]
Hi there, Could I please be re-invited? I didn't see the original invite until it had expired

**Comment by zimbatm** [comment]
invited frogamic and nbraud

**Comment by FliegendeWurst** [comment]
@tu-maurice doesn't [remember getting an invite](https://github.com/NixOS/nixpkgs/issues/265948#issuecomment-1802695765) and would probably appreciate a re-invite :)

**Comment by zimbatm** [comment]
invited! :robot:

**Comment by xrelkd** [comment]
Please invite me, I maintain several packages as well.

**Comment by zimbatm** [comment]
done :robot:

**Comment by witchof0x20** [comment]
Not sure if this is where to ask, but I also missed an invite!

**Comment by Leixb** [comment]
Same here

**Comment by zimbatm** [comment]
function executed 🤖

**Comment by tomberek** [comment]
invite @YvesStraten 

(they reached out and said that their invite failed)

**Comment by YvesStraten** [comment]
The issue is resolved for me, I managed to make the link on another device, no idea why it did not work on the first one. Thank you very much @tomberek for your help 🙏

**Comment by xyven1** [comment]
Missed my invite when it came by, I wouldn't mind getting that sent by again. @zimbatm

**Comment by pbsds** [comment]
Please invite my bot account @pbsbot. I want to programmatically muck about with labels and such without fear of accidentally leaking a commit bit key

**Comment by con-f-use** [comment]
Hi, can I have an invite?

**Comment by jcaesar** [comment]
Sorry, I also missed the e-mail, I'd also like to ask for a re-invite.

**Comment by infinisil** [comment]
Since recently we have the new [GitHub org owners help desk Matrix channel](https://matrix.to/#/#org_owners:nixos.org), which is the new best place to ask for an invite!

**Comment by Lassulus** [comment]
send out the outstanding invitation here

**Comment by pwnwriter** [comment]
Hi @zimbatm , could you please send me an invitation as well? Unfortunately, I missed the original email :(.

**Comment by pbsds** [comment]
ref https://github.com/NixOS/nixpkgs-committers/issues/50#issuecomment-2996615071 @doronbehar 

Should we reopen this issue as a means of discoverable documentation?

**Comment by doronbehar** [comment]
> ref [#321665 (comment)](https://github.com/NixOS/nixpkgs-committers/issues/50#issuecomment-2996615071) [@doronbehar](https://github.com/doronbehar)
> 
> Should we reopen this issue as a means of discoverable documentation?

I think not. However perhaps the link to the [`#org_owners`](https://matrix.to/#/#org_owners:nixos.org) matrix channel should be more discoverable? `git grep org_owners` returned nothing for me, though I'm not sure where is the best place in Nixpkgs to mention this matrix channel.

**Comment by pbsds** [comment]
I think documentation about how the github team is managed is perfect to put in `maintainers/README.md`

**Comment by pbsds** [comment]
* https://github.com/NixOS/nixpkgs/pull/419690

**Comment by alerque** [comment]
This appears to have bitten me too. Can haz invite please?

Incidentally even a search in notifications for `is:repository-invitation` doesn't turn this up, I assume they must expire and disappear instead of being marked as anything and remaining traceable.
