### ISSUE TITLE
libbsd 0.8.2 and 0.8.3 fail on darwin

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#23434]
## Issue description

libbsd versions 0.8.2 and 0.8.3 fail on darwin as reported by @jwiegley:

```
building path(s) ‘/nix/store/v21fb8laviynla5mm7nivhyy7zjffrz7-libbsd-0.8.2’
unpacking sources
unpacking source archive /nix/store/gf84gw8r46pyg016mjvaavh71ks4wpik-libbsd-0.8.2.tar.xz
source root is libbsd-0.8.2
...
  CC       arc4random.lo
In file included from arc4random.c:31:
In file included from ../include/bsd/stdlib.h:37:
../include/bsd/libutil.h:42:10: fatal error: 'features.h' file not found
#include <features.h>
         ^
1 error generated.
make[2]: *** [Makefile:627: arc4random.lo] Error 1
```

### Steps to reproduce

Without a mac, I cannot reproduce it.

**Comment by LnL7** [comment]
This might help https://github.com/JackieXie168/libbsd/commit/019eba4379beac001041f2b9b19e3eb87bdfb7ab, but that patch doesn't apply anymore. 🙁

**Comment by peterhoeg** [comment]
So I've logged a case [upstream](https://github.com/JackieXie168/libbsd/issues/1) but in the mean time, should we tag the package as broken on darwin?

**Comment by LnL7** [comment]
It's already [`linux`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libbsd/default.nix#L16) only at the moment.
