### ISSUE TITLE
My DNS setup no longer works.

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#23431]
## Issue description
My local system looks up hostnames by `dnscrypt-proxy`, via a `bind` cache/forwarder. The system was built Feb 19th, with nixpkgs version "17.09pre102441.45344fd". However, trying to upgrade my OS results in DNS queries timing out now. Upon startup, the systemd service `update-dnscrypt-resolvers` fails; I'm unsure if this is a cause or effect.

The relevant stuff from my configuration.nix:

``` nix
{
  #DNSCrypt
  services.dnscrypt-proxy.enable = true;
  services.dnscrypt-proxy.resolverName = "okturtles"; 
  services.dnscrypt-proxy.ephemeralKeys = true;
  services.dnscrypt-proxy.localPort = config.myMachines.localDNSProxyPort;

  networking.dnsExtensionMechanism = true;

  services.bind =
  {
    enable = true;
    forwarders = ["127.0.0.1 port ${toString config.myMachines.localDNSProxyPort}" ];
    cacheNetworks = ["127.0.0.0/24" "10.1.1.0/24"];
  };
}
```

## Technical details

* System: "17.09pre102441.45344fd"
* Nix version: 1.11.6
* Nixpkgs version: "17.09pre102441.45344fd"

**Comment by joachifm** [comment]
Can you provide sanitized logging output for the `update-dnscrypt-resolvers` unit? It's not supposed to run at startup, but rather a few minutes after boot. `dnscrypt-proxy` should work without it. Can you inspect the contents of `/var/lib/dnscrypt-proxy`? Look for truncated or corrupted files.

**Comment by spacekitteh** [comment]
update-dnscrypt-resolvers's log is basically this over and over:

```
-- Reboot --
Mar 01 09:53:53 spaceserv.spacekitteh.moe systemd[1]: Started Update list of DNSCrypt resolvers.
Mar 01 09:53:53 spaceserv.spacekitteh.moe update-dnscrypt-resolvers-start[1780]: curl: (6) Couldn't resolve host 'download.dnscrypt.org'
Mar 01 09:53:53 spaceserv.spacekitteh.moe systemd[1]: update-dnscrypt-resolvers.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Mar 01 09:53:53 spaceserv.spacekitteh.moe systemd[1]: update-dnscrypt-resolvers.service: Unit entered failed state.
Mar 01 09:53:53 spaceserv.spacekitteh.moe systemd[1]: update-dnscrypt-resolvers.service: Failed with result 'exit-code'.

```

The contents of /var/lib/dnscrypt-proxy contains `dnscrypt-resolvers.csv` and `dnscrypt-resolvers.csv.minisig`; both appear to be intact. 

(ccing @cleverca22 )

**Comment by spacekitteh** [comment]
Extra info:

@cleverca22 helped investigate last night, and it seemed that `named` would crash but it wouldn't be cleaned up, and was marked `<defunct>` in `ps aux`; but the systemd unit was marked as `running (active)`.

**Comment by spacekitteh** [comment]
I note that it happened right around the the time [this change](https://github.com/NixOS/nixpkgs/commit/31ff2ac05792a5132ae87c968c35bd51419750d1) was made. Could it be a systemd problem?

**Comment by spacekitteh** [comment]
I also note this from `dmesg`:

```
[84740.426135] audit: type=1400 audit(1488595690.601:195): apparmor="DENIED" operation="open" profile="/nix/store/v0sb
plclh7a9ziprm8m3x3sqyhbw2gra-dnscrypt-proxy-1.9.4/bin/dnscrypt-proxy" name="/dev/random" pid=2101 comm="dnscrypt-proxy
" requested_mask="r" denied_mask="r" fsuid=499 ouid=0
```

**Comment by cleverca22** [comment]
i think apparmor is trying to prevent dnscrypt-proxy from stealing your random numbers!

**Comment by spacekitteh** [comment]
how rude

**Comment by Mic92** [comment]
Currently named is started through a through a point less script instead of `ExecStart`. Maybe the shell is still running, so the named process is not reaped. @joachifm where does the initial resolver list comes from, when the update already requires DNS? At some point the default dnscrypt resolver stopped working for me. So I switched to `dnscrypt-proxy.resolverName = "cs-de";`

**Comment by joachifm** [comment]
@Mic92 the initial list comes with the distribution tarball. Before, I used to initialize the list from GitHub. It's a bit more robust, but also more of a hassle to maintain. I'll look into adding that back. With the auto-update it's not too bad. You can always hard-code the IP to your chosen resolver to bypass the whole thing.

**Comment by jcumming** [comment]
The zombification of `named` is a symptom. 

The problem appears to be bind violating seccomp policies and being killed.

**Comment by cleverca22** [comment]
@Mic92 that shell script should have been blocking on waitpid(), and should have quit when named died, but all of the evidence i gathered showed it was just hung at the time

something felt very wrong, but i couldn't track down any obvious cause

**Comment by spacekitteh** [comment]
Is anyone else able to reproduce this?

**Comment by jcumming** [comment]
Trying this now:

```
[jack@needle:nixos]$ cat tests/bind.nix
import ./make-test.nix {
  name = "bind";

  nodes = {
    master =
      { pkgs, config, ... }:

      {
        services.bind.enable = true;
        services.bind.cacheNetworks = [ "127.0.0.0/8" ];
      };
  };

  testScript = ''
    startAll;

    $master->waitForUnit("bind");
    $master->succeed("host nixos.org");
  '';
}
```

**Comment by Mic92** [comment]
The systemd service does not apply any seccomp rules, but bind is linked against `libseccomp`. The question is which seccomp rule is violated here. For the meantime I can only suggest to use a different resolver. Bind is a pretty complex error prone software for this simple task. Unbound or dnsmasq are usually easier to handle

**Comment by spacekitteh** [comment]
i'll probably use just straight dnscrypt-proxy in the meantime, it's just curious that this seems to happen in this presumably not-uncommon scenario.

**Comment by joachifm** [comment]
Note that newer dnscrypt-proxy versions support caching, if that's all you're using the resolver for.

**Comment by spacekitteh** [comment]
It's not, but that's good to know!

**Comment by spacekitteh** [comment]
Is it enabled by default?

**Comment by joachifm** [comment]
@spacekitteh no, it's a fairly new feature so I figured it'd be better to stick with dnsmasq or unbound for now. I intend to add support for the new stuff in the next module iteration.

**Comment by joachifm** [comment]
@Mic92 it occurred to me that hostip is the most elegant solution; I think e72aaa73eacb15b82270fe702517be97d1beba37 should address the issues you've had with the resolver list going out of date.

**Comment by mguentner** [comment]
Arch Linux had a similar problem: https://bbs.archlinux.org/viewtopic.php?id=223954

**Comment by fpletz** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/eb79649414c00f4a5ac8a69f8213b891c869bc66.
