### ISSUE TITLE
Use disable-default-paths for hmatrix Haskell package once that flag has landed

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#23453]
See https://github.com/albertoruiz/hmatrix/pull/219

So far, using hmatrix made build problems because it hardcoded some paths like `/usr` when openblas is used, such as:

```
impure path `/dont/hardcode/paths/lib/openblas/lib' used in link
collect2: error: ld returned 1 exit status
```

The linked PR adds a cabal flag `disable-default-paths`, off by default, that allows disabling this.

nixpkgs should set this flag once it has landed, replacing the workaround so far [here](https://github.com/NixOS/cabal2nix/blob/3de0b842700dceff35ab18ace96c58d301bc3b04/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs#L82).

CC @peti

**Comment by HuwCampbell** [comment]
This is done and should probably be closed.

**Comment by cdepillabout** [comment]
Sounds like this is done.  Closing!
