### ISSUE TITLE
Support multiple configuration files (selectable from grub)

### ISSUE THREAD

**Issue by TomSmeets** [NixOS/nixpkgs#23458]
## Description
I was thinking if it is possible to select configurations when booting.
With configurations I mean multiple files that look like `configuration.nix` but can be selected from the boot menu (grub or efi).

NixOS could really benefit from this feature, and offer something that no other distro has.
And I would use it extensively with my laptop (different places ask for different configurations).

## Example

Here are a few example configurations that I had in mind.
These paths could be specified in the standard `configuration.nix` file.

| Path                        | Description |
|-----------------------------|------------ |
| configurations/default.nix  | Default configuration
| configurations/work.nix     | No games, different host-name and mac-address
| configurations/headless.nix | Nixos without starting the x-server
| configurations/free.nix     | disable all nonfree software
| configurations/nvidia.nix   | disable bumblebee and directly use the graphics card

## Implementation
These configurations will import common configurations (or each-other) to prevent copy-pasting.

I don't have enough knowledge to know if this is actually possible.
But I think so, because we already do something like this with the multiple bootable 'generations'.

**Comment by alexeymuranov** [comment]
How is a configuration different from a profile?

**Comment by Mic92** [comment]
Look for `profile` in the `nixos-rebuild` manpage:

```
$ nixos-rebuild switch -p test -I nixos-config=./test.nix
```

**Comment by 7c6f434c** [comment]
For on-boot choice of configuration, look at `config.nesting.children`. For advanced sharing of parts of configuration, use the module system and look at `nixpkgs/nixos/modules/profiles/`

**Comment by TomSmeets** [comment]
YES, Thanks! :+1: 
Profiles are exactly what I need.

The manual only talks very briefly about profiles and doesn't explain it's possibility's.

We should add a separate section dedicated to profiles which will improve its visibility.

Thanks for your help,
Closing this issue.

**Comment by Taeradan** [comment]
@7c6f434c Is the functionality still working ? I tried to use `config.nesting.clone` with a single option to differentiate it (a window manager), it builds but there is no entry in grub. How am I supposed to access the alternative system ?

**Comment by 7c6f434c** [comment]
I dunno if they still work, as I now use not-exactly-NixOS. Some times ago on switch it additionally created subentries for the default configuration. Maybe yet another config generation update has broken that and a bug needs to be filed… I think I have only ever used `.children`, though.

**Comment by vmandela** [comment]
@Taeradan  Below link has the information on how to switch between `config.nesting.clone` configurations at runtime.

https://nixos.org/nix-dev/2017-June/023967.html

> You can activate the alternative configuration with
>   $ sudo /run/current-system/fine-tune/child-1/bin/switch-to-configuration
> test
> 
>   To revert back either reboot, or
>   $ sudo /run/booted-system/bin/switch-to-configuration test

However the cloned configurations do not show up in the grub menu.  `config.nesting.children` might be the way to go for populating entries in grub but the documentation is sparse.
