### ISSUE TITLE
Package request: whoogle-search

### ISSUE THREAD

**Issue by hmajid2301** [NixOS/nixpkgs#234618]
**Project description**

Get Google search results, but without any ads, JavaScript, AMP links, cookies, or IP address tracking. Easily deployable in one click as a Docker app, and customizable with a single config file. Quick and simple to implement as a primary search engine replacement on both desktop and mobile

**Metadata**

* homepage URL: https://github.com/benbusby/whoogle-search
* source URL: https://github.com/benbusby/whoogle-search
* license: mit
* platforms: unix

**Comment by abathur** [comment]
Closing in favor of #167245; it already has an open PR, but it sounds like it got bogged down waiting for a merge: 
- #167249

Hopefully it isn't too hard to either get that PR over the line, or fork it and create a new one.
