### ISSUE TITLE
Reconfiguring Nixos creates unbootable generation

### ISSUE THREAD

**Issue by 0BobTheJanitor** [NixOS/nixpkgs#23467]
## Issue description

"Upgrading" from unstable channel to stable-17.03. Successful, until I boot into said new generation:

> Error loading "\efi\nixos\yx3dsrdsb0syqskmqn2ddrmnlcd3q1bg-linux-4.9.13-bzImage.efi: Not Found"
> Failed to execute Nixos (\efi\nixos\yx3dsrdsb0syqskmqn2ddrmnlcd3q1bg-linux-4.9.13-bzImage.efi): Not Found

Can still boot into the generation I'm doing the upgrade on, and the file does indeed exist in /boot/EFI/nixos, but I guess systemd-boot cannot find it.

edit: Tried updating to 16.09 from unstable, same issue. Went back to an even older generation (16.09) and the problem still persisted. At the moment, it is impossible to change current configuration and have the ability to boot into it.

### Steps to reproduce

- Change some configuration
- Do a rebuild switch/boot --upgrade
- Reboot
- Attempt to launch newest generation from systemd-boot
- Error

That's pretty much all there is to go on, don't know what caused it or how to fix it.

## Technical details

* System: `17.03beta194.5b0c9d4 (Gorilla)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.03beta194.5b0c9d4"

**Comment by 0BobTheJanitor** [comment]
Fixed it. /boot is a mess, for some reason at some point my system changed where it was storing entry changes, not in /boot, but in /boot/EFI, meaning there was a /boot/EFI/EFI. Updated this manually in hardware configuration, and modified the generation entry config file to point to nixos/<whatever> instead of /eft/nixos/<whatever> and it works.

**Comment by domenkozar** [comment]
I've recently played with `nix-store --gc` and then rebooted which resulted in similar problems. I can't point out what really happened, I will try to reproduce it tomorrow.
