### ISSUE TITLE
Build failure: gst-plugins-rs

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#234723]
### Steps To Reproduce

1. build and test *gst-plugins-rs* on Hydra

### Build log

https://hydra.nixos.org/build/220925319/log

### Additional context

Tests time out when building gst-plugins-rs on Hydra.
This was reported to occur on Darwin in #225143, but also occurs on Linux as well. Currently, there is no up-to-date build for aarch64-linux in cache.nixos.org.

- https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gst_all_1.gst-plugins-rs.x86_64-linux
- https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gst_all_1.gst-plugins-rs.aarch64-linux

See intermittent Hydra failures

### Notify maintainers

@lilyinstarlight

**Comment by lilyinstarlight** [comment]
Oof the tests timed out on aarch64 on one and livesync plugin test failed on the other. I guess I'll make that timeout longer and disabled livesync on aarch64. PR incoming in the next hour or so

> This was reported to occur on Darwin in https://github.com/NixOS/nixpkgs/pull/225143, but also occurs on Linux as well.

Darwin timed out in ofborg on the PR for other reasons (ofborg's internal timeout, not the timeout I set on the tests). It successfully built on Hydra after merging and I had tested it locally

**Comment by lilyinstarlight** [comment]
For reference, this was the test failure on livesync on aarch64:

```
     Running tests/livesync.rs (build/target/aarch64-unknown-linux-gnu/debug/deps/livesync-335f59c0161e7d2b)

running 4 tests
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
test test_audio_nonsinglesegment ... ok
test test_audio_singlesegment ... ok
test test_video_singlesegment ... ok
test test_video_nonsinglesegment ... FAILED

failures:

---- test_video_nonsinglesegment stdout ----
thread 'test_video_nonsinglesegment' panicked at 'assertion failed: `(left == right)`
  left: `20`,
 right: `10`: Bad offset', utils/livesync/tests/livesync.rs:171:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll follow-up with the gstreamer folks later and figure out what's going on with the livesync test (more uninitialized memory usage in `videotestsrc` like in `audiotestsrc` maybe 🤔)

**Comment by lilyinstarlight** [comment]
Oh hey it's actually already been reported upstream. I'll just disable it across all platforms then and will re-enable when that issue is resolved

https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/357

**Comment by lilyinstarlight** [comment]
I've opened #234771
