### ISSUE TITLE
Update request: deadd-notification-center 2022-11-07 → 2.0.2

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NixOS/nixpkgs#234893]
- Package name: deadd-notification-center
- Latest released version: 2.0.2

- Current version on the unstable channel: 2022-11-07
- Current version on the stable/release channel: 2022-04-20

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Melkor333
@S-NA

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by S-NA** [comment]
There is a regression that I want fixed before I update the package, https://github.com/phuhl/linux_notification_center/pull/221
