### ISSUE TITLE
Unityhub unusable on stable(2.3.2) and unstable(3.4.2) versions

### ISSUE THREAD

**Issue by Elkellympia** [NixOS/nixpkgs#234801]
### Describe the bug
cannot use unityhub properly on both stable(2.3.2) and unstable(3.4.2) versions
on the stable version projects are not added when picked using the file picker
on the unstable version the sign in button nor the create account button do nothing
### Steps To Reproduce
stable(2.3.2) 
1. install stable version inside configuration.nix
2. `sudo nixos-rebuild switch` on terminal
3. open unityhub either from terminal using `unityhub` or from an app menu(gnome in my case)
4. add a license
5. add an account
6. go to the projects section
7. add an existing project
8. pick the project with the file picker
9. nothing happens
unstable(3.4.2) 
1. install unstable version inside configuration.nix
2. `sudo nixos-rebuild switch` on terminal
3. open unityhub either from terminal using `unityhub` or from an app menu(gnome in my case)
4. click sign in button
5. Nothing happens 
### Expected behavior
stable(2.3.2)
the project is added succesfully to the list an can be opened
unstable(3.4.2)
the sign in opens a tab on my browser asking for an account
### Screenshots
"If applicable, add screenshots to help explain your problem."
I do not think screenshots would be helpful in this case
### Additional context
Dont know how to see any log or output info about unityhub, maybe seeing that would help

### Notify maintainers

stable(2.3.2):
@tesq0
unstable(3.4.2):
@tesq0 
@huantianad  

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
[nicksos@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.110, NixOS, 22.11 (Raccoon), 22.11.4222.6c591e7adc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(nicksos): `""`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by huantianad** [comment]
#217326 might also be related. 

For the issue on the latest Unity Hub, can you also send the log file at `~/.config/unityhub/logs/info-log.json`, after attempting to login?

**Comment by huantianad** [comment]
Thanks for the info, currently out of town but will take a look when I get home. 🙃

**Comment by huantianad** [comment]
I was unable to see anything indicating the error in the log, other than a mention of not finding `libsecret`, which is weird because that is included in the FHS env.

Can you try once again on latest unstable (3.4.2), just launching the app from command line and pushing the sign in button, and seeing if there's anything in console logs as well?

**Comment by huantianad** [comment]
Can you check if https://github.com/NixOS/nixpkgs/issues/223127#issuecomment-1590020581 fixes your issue?

**Comment by huantianad** [comment]
Awesome, I'll go ahead and reclose the issue then, if it's all fixed!
