### ISSUE TITLE
blueberry: missing library for autostart desktop file

### ISSUE THREAD

**Issue by crazyminecuber** [NixOS/nixpkgs#234833]
### Describe the bug

I get an error message when trying to exectute the autostart dektop file `blueberry-obex-agent.desktop`.

### Steps To Reproduce
1. `nix build 'nixpkgs#blueberry'`
2. `nix-shell -p dex`
3. `dex result/etc/xdg/autostart/blueberry-obex-agent.desktop`

__results__
```
[nix-shell:/tmp]$ dex result/etc/xdg/autostart/blueberry-obex-agent.desktop 

[nix-shell:/tmp]$ Traceback (most recent call last):
  File "/nix/store/0dwdzfh0zdxlarsqf95zw6a5j3q060kl-blueberry-1.4.8/lib/blueberry/.blueberry-obex-agent.py-wrapped", line 29, in <module>
    gi.require_version('Notify', '0.7')
  File "/nix/store/d8as2swdgm78cxzh4zddd0861w6pxn9i-python3.10-pygobject-3.44.1/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

### Expected behavior

Desktop file should be runnable without any problem.

### Additional context

I ran into this because I wanted to autostart all my applications that follow the xdg-autostart specification. For this, I used the program dex. When it tried to autostart all the applications following xdg-autostart, it got this error when it tried to start everything.

__Additional thoughts__

Should the two autostart files really be enabled by default, without any option to turn them off? Maybe add a NixOS module with the option to enable the two desktop file separately and default to have them disabled? Because I do not think installing a package should automatically autostart a program, just because the system is following xdg-autostart.

### Notify maintainers

@bobby285271 @romildo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
/tmp .................................................................took 4m5s
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/x6yjkzgmdppwi95y4gvm4lxi6q27936s-nix-info
copying path '/nix/store/x6yjkzgmdppwi95y4gvm4lxi6q27936s-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.11 (Tapir), 23.11.20230524.f91ee30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos````

**Comment by romildo** [comment]
Should have been fixed by https://github.com/NixOS/nixpkgs/pull/234935
