### ISSUE TITLE
vscode-lldb: libcodelldb.so not found

### ISSUE THREAD

**Issue by pearsche** [NixOS/nixpkgs#234908]
### Describe the bug
see title

### Steps To Reproduce
1. install the extension using nix
2. try to use it
3. fail

### Expected behavior
The extension works fine.

### Notify maintainers
@nigelgbanks 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1-zen1, NixOS, 23.11 (Tapir), 23.11pre488026.f91ee3065de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(pearsche): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by borgenk** [comment]
From VSCode:

> /nix/store/5yh327ma20pm7541w7vdj79y0ckm9g0n-vscode-extension-vadimcn-vscode-lldb-1.9.1/share/vscode/extensions/vadimcn.vscode-lldb/adapter/libcodelldb.so: cannot open shared object file: No such file or directory

Content in that directory:
```
codelldb
libcodelldb.a
```

Not sure if related to the latest update, but pinging @natsukium in case you know.

**Comment by natsukium** [comment]
I only changed the fronts, so I don't know the details, but I think it relates to #160874.
