### ISSUE TITLE
Package request: gtoolkit

### ISSUE THREAD

**Issue by DrRuhe** [NixOS/nixpkgs#235084]
**Project description**

[Glamorous Toolkit](https://gtoolkit.com/) is the Moldable Development environment. It empowers you to make systems explainable through experiences tailored for each problem.

**Metadata**

* homepage URL:  https://gtoolkit.com/
* source URL: https://github.com/feenkcom/gtoolkit
* license: mit
* platforms: unix, linux, darwin

**Progress**
Things that need to be packaged:
- [x] The virtual machine. @akgrant43 did this in https://github.com/akgrant43/nixpkgs/blob/akg/pkgs/development/glamoroustoolkit/default.nix
- [ ] The dynamic libraries used via FFI calls from the Pharo/GT image. Again nothing special in principle, but packaging all of them looks like a lot of work.
- [ ] The image. It should be possible to build it from a minimal Pharo image, to which packages are added one by one from source code. But figuring out the details looks like... a lot of work again.

**Just run it locally**
This is my partially completed attempt at packaging this (this is hacky and for myself, so not up to nixpkgs standart). It runs, however it throws errors as it expects the files in the nix store under `${gtoolkit-src}` to be writable.

I am not exactly sure how to manage the dependency on such a modifiable image file. Possibly wrapping the binary in a script that initializes the image?

```nix
gtoolkit-src = pkgs.fetchzip {
        url = "https://dl.feenk.com/gt/GlamorousToolkit-Linux-x86_64-v0.8.2852.zip";
        sha256 = "sha256-truhPyMlHuoEllO2f3NUhN7QLgZAXOVQ+rWadV6c+hQ=";
        stripRoot=false;
    };

gtoolkit = pkgs.buildFHSUserEnv {
    name = "gtoolkit";
    targetPkgs = pkgs: (with pkgs; [
        gtk3
        glib
        xorg.libX11
        ]);
    multiPkgs = pkgs: (with pkgs; [
        gtk3
        glib
        ]);
    runScript = "${gtoolkit-src}/bin/GlamorousToolkit";
    };
```

**Comment by DrRuhe** [comment]
In this comment, their build process gets described in a high level: https://github.com/feenkcom/gtoolkit/issues/1838#issuecomment-804705133

**Comment by DrRuhe** [comment]
It seems like there are 3 things that are required for this:

- The virtual machine. This looks like a standard piece of C code, so it should not be more difficult to package than anything else. But I don't know how different GT's VM is from the standard Pharo VM, nor how easy it is to figure out its build process.
- The dynamic libraries used via FFI calls from the Pharo/GT image. Again nothing special in principle, but packaging all of them looks like a lot of work.
- The image. It should be possible to build it from a minimal Pharo image, to which packages are added one by one from source code. But figuring out the details looks like... a lot of work again.

**Comment by akgrant43** [comment]
I've submitted a package PR at https://github.com/NixOS/nixpkgs/pull/240139
