### ISSUE TITLE
Tailscale module doesn't load TUN kernel module

### ISSUE THREAD

**Issue by winterqt** [NixOS/nixpkgs#235098]
### Describe the bug

When using the Tailscale service (setting `services.tailscale.enable = true`), the daemon fails to start:
```
systemd[1]: Starting Tailscale node agent...
tailscaled[1681]: logtail started
tailscaled[1681]: Program starting: v1.40.1, Go 1.20.4: []string{"/nix/store/favyr7g7rx93f3yisxdvkq1ciip4samw-tailscale-1.40.1/bin/tailscaled", "--cleanup"}
tailscaled[1681]: LogID: xxx
tailscaled[1681]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
tailscaled[1681]: dns: ResolvConfMode error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
tailscaled[1681]: dns: [rc=resolved nm=no resolv-conf-mode=error ret=systemd-resolved]
tailscaled[1681]: dns: using "systemd-resolved" mode
tailscaled[1681]: creating dns cleanup: route ip+net: no such network interface
tailscaled[1681]: flushing log.
tailscaled[1681]: logger closing down
tailscaled[1707]: logtail started
tailscaled[1707]: Program starting: v1.40.1, Go 1.20.4: []string{"/nix/store/favyr7g7rx93f3yisxdvkq1ciip4samw-tailscale-1.40.1/bin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641", "--tun", "tailscale0"}
tailscaled[1707]: LogID: xxx
tailscaled[1707]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
tailscaled[1707]: wgengine.NewUserspaceEngine(tun "tailscale0") ...
tailscaled[1707]: Linux kernel version: 6.1.29
systemd[1]: Started Tailscale node agent.
tailscaled[1707]: is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with:
tailscaled[1707]: wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
tailscaled[1707]: flushing log.
tailscaled[1707]: logger closing down
tailscaled[1707]: getLocalBackend error: createEngine: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
systemd[1]: tailscaled.service: Main process exited, code=exited, status=1/FAILURE
```

If I `sudo modprobe tun`, the issue expectedly goes away (because Tailscale couldn't do it itself because `/sbin/modprobe` doesn't exist).

(There's also the peculiar `creating dns cleanup: route ip+net: no such network interface` line, but I'm not sure if that's an actual issue or not.)

I presume we just need to set `boot.kernelModules = [ "tun" ]`, but how am I the first one to have run into this issue? 😄 

Considering that, I think there may be more at play. I just don't know what.

### Steps To Reproduce

```nix
networking.useNetworkd = true;
services.tailscale.enable = true;
```

### Expected behavior
It should work without having to manually `modprobe tun`.

### Notify maintainers

@danderson @martinbaillie @twitchyliquid64 @06kellyjac

### Metadata
Nixpkgs 3005f20ce0aaa58169cdee57c8aa12e5f1b6e1b3

**Comment by twitchyliquid64** [comment]
Indeed, ive never need to specify `tun`, its always been present by default. Do you have a riced kernel or a custom kconfig perhaps?

**Comment by raphaelr** [comment]
I use tailscale and networkd, and it works fine for me. In my nixos configuration `config.boot.kernelModules` already contains `"tun"`, without me explicitly setting it.

I believe the reason for this is that [boot.enableContainers](https://search.nixos.org/options?channel=unstable&show=boot.enableContainers) is true by default, and that option [enables tun](https://github.com/NixOS/nixpkgs/blob/5e871d8aa6f57cc8e0dc087d1c5013f6e212b4ce/nixos/modules/virtualisation/nixos-containers.nix#L893-L898).

**Comment by winterqt** [comment]
Interesting @raphaelr. I don't actually explicitly disable that option... so I wonder what's up here. I'm going to see if `tun` is included in my `boot.kernelModules` like it should be, and why it's not loading if not.

**Comment by winterqt** [comment]
This could be a race condition with `systemd-load-modules.service`, but... how am I the only one running into it, then?

**Comment by winterqt** [comment]
Okay, I'm putting together fixes for this, but I need some diagnostics from y'all.

@raphaelr: do you see `dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory` in your tailscaled logs? It's using the wrong DBus socket path by default, but somehow none of our other services across the tree need it manually specified? We don't set an environment variable or anything...

Everyone: what initrd do you use (systemd, or scripted (the default))?

**Comment by winterqt** [comment]
This is a me-specific issue, to my dismay; closing. Thank you all for taking the time to respond.
