### ISSUE TITLE
OCI container registry login variable expansion bug

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#235075]
### Describe the bug
The following line has issues when usernames contain the $ symbol as e.g. used by the registry harbor.
https://github.com/NixOS/nixpkgs/blob/3c7a68613bc524f028fa1f5396194eb5fdcbf4ac/nixos/modules/virtualisation/oci-containers.nix#L251

When accounts for any form of automations in harbor are created, the systems prepends "robot$" by default, leading to usernames like "robot$myapplication".
If the variable "myapplication" is unset, this results in actually trying to login as "robot".

### Steps To Reproduce
1. Setup harbor or another registry that uses `$` in their usernames.
2. Example configuration.nix settings:
```
virtualisation.oci-containers.containers.jellyfin = {
image = "reg.example.com/dockerhub/jellyfin/jellyfin:latest";
login = {
    registry = "reg.example.com";
    username = "robot$dockermirror";
    passwordFile = "/etc/password.reg.example.com";
};
}
```

### Expected behavior
podman trying to login as "robot$dockermirror".

### Additional context
A possible workaround is to escape the username in configuration.nix:
```
username = "robot\\$dockermirror";
```

### Notify maintainers
@Gerschtli @NickCao @zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25, NixOS, 22.11 (Raccoon), 22.11.4426.c8a17ce7abc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos````

**Comment by Gerschtli** [comment]
It is probably best to call `escapeShellArg` on the username, then every value would just work.
