### ISSUE TITLE
openssh: ssh-askpass is missing.

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#23500]
## Issue description

File ```${pkgs.openssh}/libexec/ssh-askpass``` is missing.
Other openssh binaries have hardcoded references to ```ssh-askpass``` and in some cases they try to launch it (e.g. when using libvirt-over-ssh)

### Steps to reproduce

![openssh](https://cloud.githubusercontent.com/assets/508305/23581765/fb55b2a0-0112-11e7-936f-35d3fb7244b7.png)

![openssh2](https://cloud.githubusercontent.com/assets/508305/23581784/7ac21114-0113-11e7-93cd-e444906f7804.png)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS 17.03.git.7431edc (Gorilla)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.7
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.git.7431edc222"

**Comment by lheckemann** [comment]
I think the programs in question will prefer to use `$SSH_ASKPASS` though, so if you set it to an appropriate value (e.g. the `libexec/x11-ssh-askpass` from `x11_ssh_askpass`) it should work.

**Comment by volth** [comment]
```$SSH_ASKPASS``` defaults to ```${pkgs.x11_ssh_askpass}/libexec/x11-ssh-askpass``` on NixOS, it seems like my ```$SSH_ASKPASS``` was empty.
