### ISSUE TITLE
Android-studio can't sign in by google to sync user setting

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#235059]
### Steps To Reproduce
1. add `android-studio`  to `home.packages` or `environment.systemPackages`
2. nixos-build switch to install android-studio
3. open android-studio and open one project
4. click the right-top button to sign to Google
5. it will open a dialog show `please sign in via the opened browser` 
6. and nothing happened

### Expected behavior
android-studio can open the default browser and success to sign in google.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/1270490/ee208d67-9ee2-4597-af2c-432682101a83)

### Notify maintainers
@alapshin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.4-zen1, NixOS, 23.11 (Tapir), 23.11.20230529.5e871d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(yswtrue): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/ry6yyi3v01cpjak7spmmjrbk6hmd4zcq-source`

```

**Comment by kotatsuyaki** [comment]
This is the same problem as #29513, which I'm experiencing. Clicking documentation links from within Android Studio does nothing other than showing a jumping icon of Firefox besides the cursor for a few seconds (on KDE Plasma, X11), while it's expected to open the page in Firefox.
