### ISSUE TITLE
[23.05]Build failure: uboot for riscv 

### ISSUE THREAD

**Issue by codehub8** [NixOS/nixpkgs#235179]
### Steps To Reproduce

Compile uboot source ( [polarfire uboot](https://github.com/polarfire-soc/u-boot/tree/mpfs-uboot-2022.01) ) for mpfs-icicle-kit (riscv)

### Build log
```
  AS      arch/riscv/lib/memcpy.o
  AS      arch/riscv/lib/crt0_riscv_efi.o
arch/riscv/cpu/mtrap.S: Assembler messages:
arch/riscv/cpu/mtrap.S:65: Error: unrecognized opcode `csrr a0,scause', extension `zicsr' required
arch/riscv/cpu/mtrap.S:66: Error: unrecognized opcode `csrr a1,sepc', extension `zicsr' required
arch/riscv/cpu/mtrap.S:67: Error: unrecognized opcode `csrr a2,stval', extension `zicsr' required
arch/riscv/cpu/mtrap.S:70: Error: unrecognized opcode `csrw sepc,a0', extension `zicsr' required
  CC      boot/bootm.o
arch/riscv/cpu/start.S: Assembler messages:
arch/riscv/cpu/start.S:65: Error: unrecognized opcode `csrw stvec,t0', extension `zicsr' required
arch/riscv/cpu/start.S:72: Error: unrecognized opcode `csrw sie,zero', extension `zicsr' required
arch/riscv/cpu/start.S:346: Error: unrecognized opcode `csrw stvec,t0', extension `zicsr' required
  CC      arch/riscv/lib/reloc_riscv_efi.o
  CC      cmd/boot.o
  CC      boot/bootm_os.o
  CC      cmd/bootm.o
  AR      cmd/riscv/built-in.o
  CC      common/main.o
make[1]: *** [scripts/Makefile.build:289: arch/riscv/cpu/mtrap.o] Error 1
  CC      cmd/panic.o
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:289: arch/riscv/cpu/start.o] Error 1
  CC      cmd/help.o
  CC      boot/pxe_utils.o
  CC      cmd/blk_common.o
  CC      common/init/board_init.o
  CC      boot/image-board.o
  CC      boot/image-fdt.o
  CC      boot/image.o
  CC      cmd/version.o
  CC      common/exports.o
  CC      cmd/source.o
  CC      common/cli_hush.o
  CC      common/autoboot.o
  CC      common/board_f.o
  CC      cmd/bdinfo.o
  CC      boot/image-fit.o
  CC      disk/part.o
  CC      disk/part_dos.o
  CC      disk/part_iso.o
  CC      common/board_r.o
  CC      cmd/blkcache.o
  CC      disk/part_efi.o
  CC      cmd/bootefi.o
arch/riscv/lib/cache.c: Assembler messages:
arch/riscv/lib/cache.c:12: Error: unrecognized opcode `fence.i', extension `zifencei' required
arch/riscv/cpu/cpu.c: Assembler messages:
arch/riscv/cpu/cpu.c:94: Error: unrecognized opcode `csrs sstatus,a5', extension `zicsr' required
arch/riscv/cpu/cpu.c:95: Error: unrecognized opcode `csrw 0x003,0', extension `zicsr' required
  CC      common/board_info.o
make[1]: *** [scripts/Makefile.build:254: arch/riscv/cpu/cpu.o] Error 1
  CC      cmd/booti.o
make[1]: *** [scripts/Makefile.build:253: arch/riscv/lib/cache.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1810: arch/riscv/cpu] Error 2
make: *** Waiting for unfinished jobs....
  CC      cmd/cpu.o
  CC      cmd/console.o
```

### Additional context

Compilation works fine when we use nixpkgs 22.11.
 ```
     #nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";
      nixpkgs.url = "github:nixos/nixpkgs/nixos-22.11";

```
The issue is reported only with 23.05. **Some extended riscv instructions are supported in gcc11 or later. So if we configure stdenv to use gcc11, it works fine.**  

With nixos-22.11 I need not to force any gcc version.

**Comment by MaxHearnden** [comment]
23.05 uses gcc 12 by default. `nixpkgs/nixos-23.05#pkgsCross.riscv64.ubootQemuRiscv64Smode` compiles fine for risc-v so it would be nice if you could provide a way to reproduce the problem.

**Comment by codehub8** [comment]
I will create a repro for you.

**Comment by codehub8** [comment]
Please clone following Github repository
`https://github.com/tattvam/nix-polarfire.git`

and run `nix-build`

It compiles uboot and kernel for Microchip polarfire SoC successfully but when we comment following line in file _icicle-kit/default.nix_

`overlays = [ (self: super: { gcc = self.gcc11; }) ];`

it will throw the error.

If you see _nixpkgs/pkgs/misc/uboot/default.nix_ in 22.11, there was a patch to workaround it:
```
ubootQemuRiscv64Smode = buildUBoot {
    defconfig = "qemu-riscv64_smode_defconfig";
    extraPatches = [
      # https://patchwork.ozlabs.org/project/uboot/patch/20220128134713.2322800-1-alexandre.ghiti@canonical.com/
      (fetchpatch {
        url = "https://patchwork.ozlabs.org/series/283391/mbox/";
        sha256 = "sha256-V0jDpx6O4bFzuaOQejdrRnLiWb5LBTx47T0TZqNtMXk=";
      })
    ];
    extraMeta.platforms = ["riscv64-linux"];
    filesToInstall = ["u-boot.bin"];
  };
```
  
But now since this patch is merged in latest uboot so it compiles successfully 23.05, but older uboot will not compile. A way to fix this is to force compilation to gcc11.

**Comment by MaxHearnden** [comment]
You can either copy the patch, or append the following to makeFlags (extraMakeFlags if you are using buildUBoot)
```
"ARCH_C=c_zicsr_zifencei"
```
This will append the required extensions to the end of the march option

**Comment by codehub8** [comment]
It works as it is, without any such changes on latest nixpkgs 22.11. Probably we are missing some fix on 23.05.

**Comment by MaxHearnden** [comment]
It was changed in binutils 2.38 according to the patch so that zifenci and zicsr were not enabled by default.

**Comment by MaxHearnden** [comment]
The breaking change was https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=aed44286efa8ae8717a77d94b51ac3614e2ca6dc which disables zifencei and zicsr by default as part of the update from 2.2 to 20191213, The patch for u-boot re enables the instructions required.

**Comment by codehub8** [comment]
Following changeset fixes the issue:
https://github.com/NixOS/nixos-hardware/pull/661
It is backward compatible.

**Comment by Artturin** [comment]
Is there anything to do nixpkgs-side? if not then close.

**Comment by tattvam** [comment]
Please close this.

**Comment by codehub8** [comment]
https://github.com/NixOS/nixos-hardware/pull/661

Fixes the issue.
