### ISSUE TITLE
Package request: gradio

### ISSUE THREAD

**Issue by SharkLava** [NixOS/nixpkgs#235184]
**Project description**
Gradio is an open-source Python library that is used to build machine learning and data science demos and web applications.

**Metadata**

* homepage URL:http://www.gradio.app/
* source URL:https://github.com/gradio-app/gradio
* license: Apache 2.0
* platforms: unix, linux, darwin, ...

**Comment by natsukium** [comment]
introduced in https://github.com/NixOS/nixpkgs/pull/241558
