### ISSUE TITLE
Is travis broken?

### ISSUE THREAD

**Issue by oxij** [NixOS/nixpkgs#23524]
## Issue description

If you'd look at raw travis log for #23520 

https://s3.amazonaws.com/archive.travis-ci.org/jobs/207911971/log.txt

you'd notice that it didn't even try to build the actual package.
I think that's rather unexpected semantics.

**Comment by joachifm** [comment]
I think the log you're linking is for the first test (nixpkgs eval & options); per https://s3.amazonaws.com/archive.travis-ci.org/jobs/207911972/log.txt the package is built (via nox review).

**Comment by oxij** [comment]
This implies that i686 and x86_64 versions should be built in a single
job. I find that to be unlikely.

**Comment by joachifm** [comment]
I don't follow. It builds on whatever platform travis is running, e.g., amd64. This is why we have a separate macos test. I expect we'd need to add something similar for i686.

**Comment by joachifm** [comment]
Or perhaps extend the nox logic to also check `pkgsi686Linux` or something to have it happen in the same travis job.

**Comment by grahamc** [comment]
(IMO) Travis is effectively a broken tool for Nixpkgs (there are many issues debating the finer points of the topic...) due to the size of nixpkgs, and how frequently Travis can't reasonably run the build.

**Comment by matthewbauer** [comment]
This seems to have improved as much as we can. Ok to close this issue?

**Comment by oxij** [comment]
Yep.
