### ISSUE TITLE
reindeer: use the new `Cargo.lock` file instead of patching/generating our own

### ISSUE THREAD

**Issue by nickgerace** [NixOS/nixpkgs#235286]
## Issue description

`reindeer` now has an available `Cargo.lock` file (https://github.com/facebookincubator/reindeer/commit/33ab6845fb9b0cb76a5ea734379d6469b0ee1aa1). There are two implications here:

1. `reindeer` should no longer use a generated/patched lockfile
2. We can use `nix-update-script` now because https://github.com/Mic92/nix-update/issues/164 is avoided (which means the custom `update.sh` can be deleted as well)

### Steps to reproduce

n/a

## Technical details

n/a

**Comment by figsoda** [comment]
#235294, I ran the update script but ran into https://github.com/facebookincubator/reindeer/pull/14

**Comment by nickgerace** [comment]
Thank you! I'll keep an eye on it as well.

**Comment by nickgerace** [comment]
Is this going to work with https://github.com/facebookincubator/reindeer/pull/14 still open?

**Comment by figsoda** [comment]
it would still run, but the package would fail to build, so r-ryantm wouldn't make a successful update until https://github.com/facebookincubator/reindeer/pull/14 is merged
