### ISSUE TITLE
Update request: reindeer unstable-2023-05-18 → unstable-2023-05-31

### ISSUE THREAD

**Issue by nickgerace** [NixOS/nixpkgs#235243]
- Package name: `reindeer`
- Latest released version: `unstable-2023-05-18`

- Current version on the unstable channel:  `unstable-2023-05-18`
- Current version on the stable/release channel: n/a

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

Filed against myself

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by nickgerace** [comment]
**Side note:** @figsoda hello! Looks like @r-ryantm has either not picked up this package for updating or the build is failing. I checked the [docs](https://ryantm.github.io/nixpkgs-update/), but am a bit stuck on where to go next. My goal is to have `reindeer` auto update on at least a weekly cadence, if possible. Thanks in advance for any and all help.

**Comment by figsoda** [comment]
Looks like @r-ryantm has not tried to update the package. You can find the logs [here](https://r.ryantm.com/log/), once it tries logs should be available at https://r.ryantm.com/log/reindeer

**Comment by nickgerace** [comment]
Thank you @figsoda that is a handy link to have! Looks like we will wait to see when it looks at `reindeer` then?

**Comment by figsoda** [comment]
yep I think so
