### ISSUE TITLE
Wayfire plugins wrapper badly written

### ISSUE THREAD

**Issue by Aleksanaa** [NixOS/nixpkgs#235325]
Wayfire plugins wrapper is not intuitive enough, and cannot easily load external plugins that users can package their own.

For example, this line is supposed to deal with standard xml paths for all plugins, instead of designating to `wf-shell` specially:
https://github.com/NixOS/nixpkgs/blob/5e871d8aa6f57cc8e0dc087d1c5013f6e212b4ce/pkgs/applications/window-managers/wayfire/wrapper.nix#L6

See [prehonor's config](https://github.com/prehonor/nixos/blob/master/nixpkgs-overlays/pkgs/applications/window-managers/wayfire/wrapper.nix) mentioned in https://github.com/NixOS/nixpkgs/issues/177708 for a possible correct solution.

Also, `applications.nix`, `wrapper.nix` and `plugins.nix` should be placed together so that their behavior can be seen more intuitively. These files expose functions to each other, making it harder to read.

@alyssais @roberth

**Comment by roberth** [comment]
I don't use this package; only did a treewide change once, so I'll unsubscribe this issue. Sorry.
@alyssais and @wineee do seem involved with the package. Next time you'll know what kind of contribution / contributor to look for.

**Comment by wineee** [comment]
Wayfire's wrapper really needs improvement, my `wcm` will repeatedly import wf-shell's configuration，and cannot correctly parse `wayfire-plugins-extra`

I refactored part of the code，still Work in progress https://github.com/NixOS/nixpkgs/pull/236041
