### ISSUE TITLE
Build failure: biber

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#235434]
### Steps To Reproduce

1. `nix-build -A biber`

### Build log

https://hydra.nixos.org/build/222252165/nixlog/1

### Additional context

https://hydra.nixos.org/build/222252165

### Notify maintainers

@tteggel

### Metadata

Confirmed locally against recent master (ddb3455e152edb633e171d51a5c1f12ae8d22641)

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.30, NixOS, 23.11 (Tapir), 23.11.20230528.4e37b4e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/39fplqnf7hlw1gpcnq9zfp4bhlrhxqgs-source`

**Comment by SamLukeYes** [comment]
There's already a PR fixing this build failure: https://github.com/NixOS/nixpkgs/pull/235347

**Comment by joshbode** [comment]
looks like this is being addressed in #235347

**Comment by SebTM** [comment]
Can confirm, fixes build-issues on unstable :)

**Comment by lilyinstarlight** [comment]
Fix has been merged. Feel free to reopen if the issue persists after the next channel bump
