### ISSUE TITLE
KDE SDDM wrongly shows `nixbld` users after installing nix

### ISSUE THREAD

**Issue by scarf005** [NixOS/nixpkgs#235546]
### Describe the bug

1. `nixbld` user UIDs ranges from `30001..30032`.
2. in `/etc/sddm.conf.d/kde_settings.conf`, default `MaximumUid` is set to 60000.
3. this causes SDDM into thinking that there are 32 more users.
4. due to increased number of available 'users', SDDM enables `username` field, which isn't desired.

<details><summary>list of nixbld users</summary>

```sh
$ cut -d: -f1,3 /etc/passwd | sort -t: -k2 -n 
# ...
scarf:1000
nixbld1:30001
nixbld2:30002
nixbld3:30003
nixbld4:30004
nixbld5:30005
nixbld6:30006
nixbld7:30007
nixbld8:30008
nixbld9:30009
nixbld10:30010
nixbld11:30011
nixbld12:30012
nixbld13:30013
nixbld14:30014
nixbld15:30015
nixbld16:30016
nixbld17:30017
nixbld18:30018
nixbld19:30019
nixbld20:30020
nixbld21:30021
nixbld22:30022
nixbld23:30023
nixbld24:30024
nixbld25:30025
nixbld26:30026
nixbld27:30027
nixbld28:30028
nixbld29:30029
nixbld30:30030
nixbld31:30031
nixbld32:30032
nobody:65534
```

</details> 

### Steps To Reproduce

1. [install nix package manager](https://nixos.org/download.html#nix-install-linux) in multi-user environment.
2. log out. (or run `sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze/`)
3. `username` field is enabled.

### Expected behavior

installing nix does not affect SDDM.

### Screenshots

| Before | After |
|--------|--------|
| ![before][before] | ![after][after] |

[before]: https://github.com/NixOS/nixpkgs/assets/54838975/c2747f72-1eca-4138-8419-d65550bff6de
[after]: https://github.com/NixOS/nixpkgs/assets/54838975/36506b01-d591-4e79-b16c-c7505f190bb0

### Additional context

to fix (or workaround), lower `MaximumUid` in `/etc/sddm.conf.d/kde_settings.conf` to 30000. then SDDM will exclude `nixbld` users.

i'm not sure how this behavior should be handled:
- make a warning message `"lower your MaximumUid"`?
- automatically reduce `MaximumUid`?

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.2-060302-generic, Ubuntu, 23.04 (Lunar Lobster), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

```
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.3.2-060302-generic (64-bit)
Graphics Platform: X11
```

**Comment by Shawn8901** [comment]
i am honestly not sure what nix should do here. Checking for all possible Login Managers seems a bit like a over reaction. The manual points out in which area the uids are (https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation). The only idea I have is to add a extra point that a user should check their login manager configuration to not show this area.

**Comment by scarf005** [comment]
I see, it would be too taxing for nix installation script to handle all possible login managers. As you mentioned, adding a note that `you may have to modify UID ranges for login managers` for both documentation and install script would be helpful, especially for people not familiar to linux DE.  I'm open to creating a patch for this, but there are a few considerations to be made:

![image](https://github.com/NixOS/nixpkgs/assets/54838975/824b7495-2bf4-4da0-afb1-4e7bd933f327)

Updating documentation would be as easy as adding some more lines at [Note](https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation).

However, I'm unsure where exactly to place the notice in the installation script:

https://github.com/NixOS/nix/blob/a15b2c01c0bac226ed34d8ba7e10a563c4a54890/scripts/install-multi-user.sh#L990-L991

    We could add a new function, notice_login_manager_uid, that outputs a message like Note: Due to nix adding multiple build users, your login manager may change its behavior if it identifies them as real users. Check the configuration of your login manager and set an appropriate UID range if you encounter unexpected behavior. This function could be called after create_build_users.
    Alternatively, we could output the message directly from either create_build_group or create_build_users.

**Comment by Shawn8901** [comment]
I personally would see that here: https://github.com/NixOS/nix/blob/a15b2c01c0bac226ed34d8ba7e10a563c4a54890/scripts/install-multi-user.sh#L702 it's the part where it's explains what it does and what to care for. An extra point for DEs/Login-Manager sounds at least for me kind of reasonable

**Comment by scarf005** [comment]
Sounds good to me. I'll open a PR later.

**Comment by scarf005** [comment]
well the problems are solved for me and now installation script is more explicit with UID ranges, so it wouldn't be too hard to diagnose and fix the error.
