### ISSUE TITLE
Package request: PyGLM

### ISSUE THREAD

**Issue by JesusSierralaya** [NixOS/nixpkgs#235502]
**Project description**

OpenGL Mathematics (GLM) library for Python

**Metadata**

* homepage URL: https://pypi.org/project/PyGLM/
* source URL: https://github.com/Zuzu-Typ/PyGLM
* license: zlib/libpng
* platforms: unix, linux

**Comment by JesusSierralaya** [comment]
I'm using version 2.5.7 without issues, but can't run the latest 2.7.0. Here's my code, which might be helpful:
configuration.nix
```
 environment.systemPackages = with pkgs; [
	wget
        # more system packages
  (python3.withPackages(ps: with ps; [
    numpy
    # more python packages
    # PyGLM the most recent version has errors
    (
    buildPythonPackage rec {
      pname = "PyGLM";
      version = "2.5.7";
      src = fetchPypi {
        inherit pname version;
        sha256 = "38fdff84e6416decffe1c5874632807d58b98c5508cca3579bb2f5332e099fd8";
      };
      doCheck = false;
      #propagaBuildInputs = [
      #];
      }
    )
    # More packages
  ]))
  ];
```

**Comment by natsukium** [comment]
introduced in https://github.com/NixOS/nixpkgs/pull/244647
