### ISSUE TITLE
Package request: privateGPT

### ISSUE THREAD

**Issue by Isomorph70** [NixOS/nixpkgs#235732]
**Project description**
Ask questions to your documents without an internet connection, using the power of LLMs. 100% private, no data leaves your execution environment at any point. You can ingest documents and ask questions without an internet connection!

**Metadata**

* homepage URL: https://github.com/imartinez/privateGPT
* source URL:  https://github.com/imartinez/privateGPT
* license: Apache
* platforms: unix, linux,

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/232681
