### ISSUE TITLE
Update request: mstflint 4.17.0-1 → 4.24.0-1

### ISSUE THREAD

**Issue by vincepri** [NixOS/nixpkgs#235796]
- Package name: mstflint
- Latest released version: 4.24.0-1

- Current version on the unstable channel: 4.17.0-1
- Current version on the stable/release channel: 4.17.0-1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mweinelt 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by raspher** [comment]
#263149

**Comment by raspher** [comment]
closing as it was merged to `unstable` and latest stable channel
