### ISSUE TITLE
pgmodeler: missing desktop icon

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#235717]
### Describe the bug

the `pgmodeler.desktop` file was not found so it is not available in the menu. inside the `/var/run/current-system/sw/share/applications/` directory is also empty.
```
➜  ~ ls -lha /var/run/current-system/sw/share/applications/ | grep pgmodeler
➜  ~
```
### Steps To Reproduce
```
  environment.systemPackages = [
    pkgs.pgmodeler
  ];
```

```
doas nixos-rebuild switch
```

### Expected behavior
the pgmodeler desktop icon is in the menu.

### Screenshots
![Screenshot_20230603_135932](https://github.com/NixOS/nixpkgs/assets/45872139/1f4b6d6c-6ba5-4f8f-b119-5dba7ea381cb)

### Additional context
there is a file that is similar to `.desktop`, but a bit different. maybe it could be a reference.
https://github.com/pgmodeler/pgmodeler/blob/main/assets/conf/schemas/desktop.sch
```
$ob Desktop $sp Entry $cb $br
[Comment=Create and deploy PostgreSQL database models] $br
[Exec=]{application} $br
[GenericName=PostgreSQL Database Modeler] $br
[Icon=]{icon} $br
[MimeType=application/dbm] $br
[Name=pgModeler] $br
[NoDisplay=false] $br
[Path=]{working-dir} $br
[StartupNotify=false] $br
[Terminal=false] $br
[TerminalOptions=] $br
[Type=Application] $br
[Categories=Development;] $br
```
### Notify maintainers
@esclear 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.419.3a70dd92993`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(hervyqa): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
PR: #349868
