### ISSUE TITLE
Missing `tail`/`head`/`awk` when calling `mount.bcachefs`

### ISSUE THREAD

**Issue by andrewbaxter** [NixOS/nixpkgs#235877]
### Describe the bug
I was thinking of trying bcachefs out, but I hit an issue with .mount.bcachefs.sh-wrapped (via mount -t bcachefs).

When I run it I get `awk: command not found` `tail: command not found` and then it says `uuid MYUUID not found`.

I see the script in the upstream repo, but I didn't see the script referred to in the nix files there so I assume it's maintained separately... but if that's wrong I'd be glad to bring it up there.

### Steps To Reproduce
1. `mount -t bcachefs MYUUID /some/dir`

### Expected behavior
The fs should mount.

### Notify maintainers
@davidak 
@Madouura 

### Metadata
Sorry, I'm running in a qemu VM and don't have a good way to copy/paste atm, this is paraphrasing

```console
system x86_64-linux
host os Linux 6.3, NixOS, 23.11 Tapir, 23.11pre490780.95be94370d0
multi-user yes
sandbox yes
version nix-env Nix 2.13.3
nixpkgs /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by andrewbaxter** [comment]
I think it's also failing calls to `bcachefs` from the same package
```
[pid  1414] newfstatat(AT_FDCWD</home/...>, "/nix/store/zs39mqfazj1b9s4z77mlajhzl088wa02-getopt-1.1.6/bin/bcachefs",  <unfinished ...>
[pid  1414] newfstatat(AT_FDCWD</home/...>, "/nix/store/mjj7p66mgh3hm775lcff963fgddhsgxc-util-linux-2.39-bin/bin/bcachefs", 0x7ffd418f1430, 0) = -1 ENOENT (No such file or directory)
[pid  1414] newfstatat(AT_FDCWD</home/...>, "/nix/store/l8g5py3i39sq8afzi9vfmpw5igbqs84r-coreutils-9.1/bin/bcachefs", 0x7ffd418f1430, 0) = -1 ENOENT (No such file or directory)
[pid  1414] newfstatat(AT_FDCWD</home/...>, "/nix/store/rw2r8jqvbsmpq5kmgwvkv9pd833k9h3z-gawk-5.2.1/bin/bcachefs", 0x7ffd418f1430, 0) = -1 ENOENT (No such file or directory)
[pid  1414] newfstatat(AT_FDCWD</home/...>, "/no-such-path/bcachefs", 0x7ffd418f1430, 0) = -1 ENOENT (No such file or directory)
```

stracing, execve for `.mount.bcachefs.sh-wrapped` only has this in PATH (after I tried adding gawk and util-linux):
```
"PATH=/nix/store/zs39mqfazj1b9s4z77mlajhzl088wa02-getopt-1.1.6/bin:/nix/store/mjj7p66mgh3hm775lcff963fgddhsgxc-util-linux-2.39-bin/bin:/nix/store/l8g5py3i39sq8afzi9vfmpw5igbqs84r-coreutils-9.1/bin:/nix/store/rw2r8jqvbsmpq5kmgwvkv9pd833k9h3z-gawk-5.2.1/bin:/no-such-path"
```
i.e. PATH doesn't contain the package's own bin dir.

**Comment by JohnRTitor** [comment]
Not an issue anymore on the latest bcachefs-tools, I believe, feel free to reopen if this has not been fixed for you yet.
