### ISSUE TITLE
Documentation: `darwin.builder` does not belong to the `Builder` part

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#235858]
### Describe the bug

`darwin.builder` sets up a **remote builder**. According to the documentation, it is not a [Nix function](https://nixos.org/manual/nix/stable/language/constructs.html#functions) that produce a [derivation](https://nixos.org/manual/nix/stable/language/derivations.html), and its documentation should not be put under that part.

### Steps To Reproduce
1. Visit https://nixos.org/manual/nixpkgs/stable/#sec-darwin-builder

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 4.14.186-g3813583ccf55`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/k916pxv4jfsxcyjjc86ah552qjy5jwvb-source`
```

**Comment by FRidh** [comment]
This probably belongs best under `Packages`, which is essentially a space for bigger / more important / different packages to be described.
