### ISSUE TITLE
ffsend segfaults after upload

### ISSUE THREAD

**Issue by Brawl345** [NixOS/nixpkgs#235936]
### Describe the bug
When using ffsend from nixpkgs, after uploading a file, the program segfaults. Using **Nix on macOS with an M1 chip**, but also tested it in a NixOS VM (**arm64**). Don't know if it works on x86.

### Steps To Reproduce

```bash
echo "test" > test.txt
nix run nixpkgs#ffsend -- upload test.txt

# Shows:
Upload complete
Segmentation fault: 11
```

### Expected behavior
The link to the file should be shown.

### Additional context
Using the version from homebrew on macOS works. It even works when compiling it from source using cargo through nixpkgs (on macOS):

```bash
git clone https://github.com/timvisee/ffsend.git
cd ffsend
nix run nixpkgs#cargo -- build --release
echo "test" > test.txt
./target/release/ffsend upload test.txt

# Shows:
Upload complete
https://send.vis.ee/download/<redacted>
```

### Notify maintainers

@marsam only changed the version last time and @lilyball's last edit was four years ago

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

macOS:

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/wyk42w7za708i150kkidfnc2avcw1kpz-source`
```

NixOS:

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.29, NixOS, 23.11 (Tapir), 23.11.20230604.a53a3be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/wyk42w7za708i150kkidfnc2avcw1kpz-source`
```

**Comment by MaxHearnden** [comment]
What version of rustc are you using to compile ffsend outside of nix?

**Comment by Brawl345** [comment]
I'm not familiar with Rust, I just ran `nix run nixpkgs#cargo -- build --release` in the ffsend git directory and it "just worked" so whichever version is currently in nixpkgs (at least on macOS). I haven't installed Rust on my machine.

**Comment by MaxHearnden** [comment]
Thanks, I have performed a bisection on nixpkgs and the regression was introduced in 63f869f5ff10b570fcf3a0d002a7aa25938f6f9f, so I just wanted to check that it could work with the latest rustc
