### ISSUE TITLE
Package request: tree-sitter-typst

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#235938]
**Project description**

A tree-sitter parser for the typst file format
**Metadata**

* homepage URL: https://github.com/SeniorMars/tree-sitter-typst
* source URL: https://github.com/SeniorMars/tree-sitter-typst
* license: apache 2

**Comment by slashformotion** [comment]
perhaps https://github.com/frozolotl/tree-sitter-typst should be used instead because it is more up to date

**Comment by Icy-Thought** [comment]
Since the PR was recently merged, I will close this issue. And if you are not satisfied with the outcome, then do re-open this issue!
