### ISSUE TITLE
services.phpfpm.phpOptions has no effect

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#23598]
## Issue description

setting something in this option (even syntax errors) has no effect on phpfpm
reverting ae67f060f28028c31b091460167bb598bd8d3e6d. solves the problem for me

### Steps to reproduce

on 17.03 write anything in services.phpfpm.phpOptions. And check the used php.ini in `systemctl status phpfpm-bla.service`

## Technical details

* System: 17.03.git.5b0c9d4

**Comment by joachifm** [comment]
I believe this was just fixed by d7674dabba39d21f24578d414da926d74a8ceb17

**Comment by globin** [comment]
Was just fixed on master and 17.03 (d37b68d)

**Comment by globin** [comment]
Ah too late \o/
