### ISSUE TITLE
Run grub-install when either boot-device or /boot/grub-device changes

### ISSUE THREAD

**Issue by alexanderkjeldaas** [NixOS/nixpkgs#2359]
Adding an issue since I was bitten by this today.

There is already a FIXME in nixos/modules/system/boot/loader/grub/install-grub.pl regarding running grub-install when the boot-device changes.

In addition, the partition where /boot/grub is located can change, and in that case grub-install should also be run.

**Comment by jagajaga** [comment]
Isn't it ok now for you?

**Comment by Profpatsch** [comment]
(triage) still a problem?
