### ISSUE TITLE
Package request: OpenUtau

### ISSUE THREAD

**Issue by yavko** [NixOS/nixpkgs#236003]
**Project description**
Open singing synthesis platform / Open source UTAU successor

**Metadata**

* homepage URL: http://www.openutau.com/
* source URL: https://github.com/stakira/OpenUtau
* license: mit
* platforms: linux, darwin

**Comment by yavko** [comment]
For anyone wanting to package, here is some info I've acquired from my attempts to package (I eventually gave up, as I have no real dotnet knowledge). It's built made in dotnet, and uses avalonia ui. Seems to target dotnet 6.0, but the arch aur packages all use dotnet 7.0, so both probably work.

**Comment by r3n3gad3p3arl** [comment]
I found this issue while trying to package this too! I also don't know anything about dotnet and I've been pulling my hair out trying to figure out why my package fails during the install phase. Hope someone who knows more can figure it out lol. I've been using the osu-lazer package as a reference, maybe that will be helpful to someone?

**Comment by Ashvith10** [comment]
@yavko @r3n3gad3p3arl I've tried working on this too, and had no luck. I've not used any references, but as you've said, I'm going to look into Ryujinx and osu-lazer : although I highly doubt if they're going to be any helpful. Here's what I was able to come up with:

```nix
{
  pkgs ? import <nixpkgs> {},
  lib ? pkgs.lib,
  fetchFromGitHub ? pkgs.fetchFromGitHub,
  buildDotnetModule ? pkgs.buildDotnetModule,
  dotnetCorePackages ? pkgs.dotnetCorePackages,
  libICE ? pkgs.xorg.libICE,
  libSM ? pkgs.xorg.libSM,
  libXi ? pkgs.xorg.libXi,
  libXcursor ? pkgs.xorg. libXcursor,
  libXext ? pkgs.xorg.libXext,
  libXrandr ? pkgs.xorg.libXrandr,
  fontconfig ? pkgs.fontconfig,
  glew ? pkgs.glew
}:

buildDotnetModule rec {
  pname = "openutau";
  version = "0.1.184";

  src = fetchFromGitHub {
    owner = "stakira";
    repo = "OpenUtau";
    rev = "build/${version}";
    sha256 = "1axasz9smzg0crkf67597rx7pyjr61h6yby6by28807wrlh0g6vw";
  };
  
  runtimeDeps = [
    libICE
    libSM
    libXi
    libXcursor
    libXext
    libXrandr
    fontconfig
    glew
  ];

  projectFile = "OpenUtau/OpenUtau.csproj";
  testProjectFile  = "OpenUtau.Test/OpenUtau.Test.csproj";
  doCheck = true;
  nugetDeps = ./deps.nix;
  selfContainedBuild = true;
  buildType = "Release";

  meta = with lib; {
    homepage = "https://www.openutau.com/";
    description = "Open singing synthesis platform / Open source UTAU successor ";
    longDescription = ''
    OpenUtau is a free, open-source editor made for the UTAU community.
    '';
    license = licenses.mit;
    platforms = platforms.linux;
  };
}
```

The stuff after `?` needs to be removed for nixpkgs, but since I'm trying this out on nix-build, I had to add them.

**Comment by lilyinstarlight** [comment]
See #249843. I actually hadn't see this issue before making that 😅

**Comment by Ashvith10** [comment]
@lilyinstarlight will the build be cached? It takes a significant amount of time for NuGet to download the dependencies, followed by the build.

**Comment by lilyinstarlight** [comment]
Right now it will not be cached by Hydra, no, since the resampler does not seem to have a license (or source code) and so is not necessarily legally distributable, as far as I could tell

If you can find evidence otherwise, though, I can update the license or I can get creative in allowing it to be cached without the resampler and then symlink it in a new derivation or something

**Comment by stakira** [comment]
> Right now it will not be cached by Hydra, no, since the resampler does not seem to have a license (or source code) and so is not necessarily legally distributable, as far as I could tell
> 
> If you can find evidence otherwise, though, I can update the license or I can get creative in allowing it to be cached without the resampler and then symlink it in a new derivation or something

https://github.com/stakira/OpenUtau/commit/8b1d8b33557865a87c48e1586b361ea8c287b634

**Comment by lilyinstarlight** [comment]
> Thanks for adding OpenUtau to NixOS. Would the below statement be enough for redistribution?

I think that's probably sufficient, sure. Thank you for adding that! ❤️

I'll update the package today in nixpkgs to remove the "unfree" bit
