### ISSUE TITLE
several lv2 plugins always segfault

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#23603]
## Issue description
When I open helm or distroh in either ardour5 or jalv.gtk, I get:
```
The program 'jalv.gtk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadShmSeg (invalid shared segment parameter)'.
  (Details: serial 56 error_code 128 request_code 130 minor_code 2)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

## Technical details

* System: 17.03.git.bdc00d9 (Gorilla)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: warning: Nix search path entry ‘/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs’ does not exist, ignoring
"17.03pre102030.8b40d2e"

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by magnetophon** [comment]
Seems fixed, sorry for not updating!
