### ISSUE TITLE
lxc-start: broken on NixOS 16.09 and 17.03

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#23604]
## Issue description

lxc-start tries to use ```/var/lib/lxc/rootfs``` as root dir of the container instead of ```/var/lib/lxc/my-container/rootfs```.

### Steps to reproduce

```virtualisation.lxc.enable = true``` in ```/etc/nixos/configuration.nix```

```
mkdir /var/lib/lxc
lxc-create -t download -n my-container
lxc-start -F -n my-container
```

![lxc1](https://cloud.githubusercontent.com/assets/508305/23665215/c077e312-034f-11e7-822b-68fdc7c0ad55.png)

![lxc2](https://cloud.githubusercontent.com/assets/508305/23665223/c26c647c-034f-11e7-8c3d-052c48223fc4.png)

the same version of LXC (2.0.7) works well in Linux Mint

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03.git.caf427e (Gorilla)
reproducible in 16.09
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.7
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.git.caf427ed84M"

**Comment by volth** [comment]
sorry, my fault
```/var/lib/lxc/rootfs``` is not the container root, it is just an empty directory which must exist

**Comment by fpletz** [comment]
Yes, but this directory should be created by the lxc module. You shouldn't have to do that manually.
