### ISSUE TITLE
git SSL issues with recent Nix on darwin

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#23605]
```
$ git pull
fatal: unable to access 'https://github.com/....git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
$ nix-env --version
nix-env (Nix) 1.11.7
$ which git
/Users/admin/.nix-profile/bin/git

```

Workaround:

```
$ SSL_CERT_FILE=$NIX_SSL_CERT_FILE git pull
```

cc @edolstra did we patch git?

**Comment by edolstra** [comment]
I think you need this patch: https://github.com/NixOS/nixpkgs/commit/942dbf89c6120cb5b52fb2ab456855d1fbf2994e

**Comment by domenkozar** [comment]
It seems it never hit master: https://github.com/NixOS/nixpkgs/commit/811b876fab58ba8795727b35897f9d35f7aa9407

**Comment by domenkozar** [comment]
@edolstra any objections using that patch (minus the print line)?

**Comment by shanemikel** [comment]
I just did an upgrade and It's broken.

Has the darwin support status changed?
I'm on nixpkgs-unstable channel

**Comment by globin** [comment]
This only affects darwin, right? I don't see a reason for the milestone then? :)

**Comment by domenkozar** [comment]
I'd like to fix it for release as well.

**Comment by LnL7** [comment]
I think so, I'm pretty sure the nixos modules set `SSL_CERT_FILE` but a linux single user install might also have issues.

**Comment by domenkozar** [comment]
This is now in staging, once built also needs to go to master and 17.03

**Comment by domenkozar** [comment]
It has been fixed in 17.03, but it's still in staging for master.

**Comment by LnL7** [comment]
I thought all of those cert related changes where in master now, with the last staging merge.

**Comment by domenkozar** [comment]
This is now on master and 17.03.
