### ISSUE TITLE
createHome does not set permissions

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#23619]
## Issue description
The documentation of `users.users.<user>.createHome` states that if the directory already exists the permissions will be modified to match the user however this does not seem to work

### Steps to reproduce

```
# mkdir /home/arian
```

Now make a user arian:

```nix
users.users.arian = {
  isNormalUser = true;
  createHome = true;
};
```

Now `ls -al /home/arian`. Owner is root instead of Arian. 

## Technical details
 Clean Nixos 16.09 install 
* System: 16.09.1021.0cb2838

**Comment by arianvp** [comment]
Reasons why you'd manually create the directory : you set up a btrfs subvolume

**Comment by joachifm** [comment]
I don't see this borne out in the logic: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/update-users-groups.pl#L180 (the only reference to `createHome`). A quick glance at that suggests to me that it won't modify the permissions if the dir exists, though I've not studied the code carefully, so take that with a pinch of salt.

**Comment by fpletz** [comment]
@joachifm Yes, it does not and that is the problem. At least if you count owner and directories as permissions and not the mode, as that is done on creation. Again if the directory does not exist. :smiley:

I've create a PR to fix the problem, with a question: #23623

**Comment by arianvp** [comment]
Thanks! :)

**Comment by arianvp** [comment]
One final note, would it be worth backporting it to 16.09?  Or because 17.03 can be released any time there is no need?

**Comment by fpletz** [comment]
Oh, I also backported it to 16.09. Sorry for not mentioning. ;)

**Comment by jtrees** [comment]
This still doesn't fully work as I would expect with nested directories.

For instance, if I set the home path to `/foo/bar` and neither of those directories exists, `/foo/bar` will be created with the correct ownership but `/foo` will belong to `root:root`. And since the execute permission on `/foo` is only set for the owner, the respective user can't even `cd` into their own home directory!
