### ISSUE TITLE
build error with hardware.bumblebee.driver = "nouveau";

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#23628]
## Issue description and Steps to reproduce

when building unstable with 

```
hardware.bumblebee = {
    enable = true;
    connectDisplay = true;
    driver = "nouveau";
  };
```

i get 
```
$ nixos-rebuild build
building Nix...
building the system configuration...
error: cannot coerce null to a string, at /nix/store/isr4qfjhl62khy86kji9nsr4l4rn3wqg-nixos-17.09pre102667.2839b10/nixos/lib/strings.nix:85:38
(use ‘--show-trace’ to show detailed location information)
```

when i build with

```
 hardware.bumblebee = {
    enable = true;
    connectDisplay = true;
  #  driver = "nouveau";
  };
```

 it builds the system

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by RonnyPfannschmidt** [comment]
the underlying cause seems to be that `primus.glvnd` may be null and isn't filtered for library paths of primusrun

**Comment by FRidh** [comment]
cc @abbradar

**Comment by abbradar** [comment]
Thanks for reporting!

**Comment by RonnyPfannschmidt** [comment]
@FRidh any idea when this one will hit 17.03 ? does it need a backport

**Comment by abbradar** [comment]
You are right, I've forgotten to cherry-pick this. Done now.

**Comment by RonnyPfannschmidt** [comment]
@abbradar thanks for the quick response

**Comment by RonnyPfannschmidt** [comment]
@abbradar i just tried building on a recently updated unstable and it doesn't seem to be there, is this a hydra issue or a backport issue?

**Comment by abbradar** [comment]
@RonnyPfannschmidt Sadly it's still not in unstable.

**Comment by RonnyPfannschmidt** [comment]
@abbradar is there anything i can do tho speed this up/enable it?

**Comment by abbradar** [comment]
You can checkout your own nixpkgs tree:

```
$ git clone git://github.com/nixpkgs/nixpkgs
$ cd nixpkgs
$ git remote add channels git://github.com/nixpkgs/nixpkgs-channels
$ git fetch channels
$ git checkout nixos-unstable # or nixos-17.03
$ git cherry-pick f36b72107c57f5a5c7cbd3a8f9cb63f5f0231e76
# nixos-rebuild switch -I nixpkgs=$PWD
```

**Comment by RonnyPfannschmidt** [comment]
@abbradar i finally got around applying this, and after a reboot the x server keeps crashing, i suspect something different that's required got removed

i attached the 2 x11 log files i found in my system, please reopen the issue

[X.0.log.txt](https://github.com/NixOS/nixpkgs/files/854467/X.0.log.txt)

[X.0.log.old.txt](https://github.com/NixOS/nixpkgs/files/854468/X.0.log.old.txt)

**Comment by abbradar** [comment]
I'll check this on my system; thanks for testing!

**Comment by RonnyPfannschmidt** [comment]
as additional details, i do use a lenovo W541 and the normal nvidia drivers also didnt work

**Comment by abbradar** [comment]
The last thing is strange (I use bumblebee on more or less daily basis). I'll think of what logs may be useful later; let's try to fix it for the blob first and then proceed to nouveau (so I can postpone `switch`ing my system). 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RonnyPfannschmidt** [comment]
@abbradar any suggestion for pinning certain generations when removing others/all others - im starting to get quite the load of broken generations on top of the last one that works

**Comment by abbradar** [comment]
You can build the working one with `nixos-rebuild switch -p good` and then you'd have "NixOS - Profile 'good'" in GRUB.

**Comment by abbradar** [comment]
And for pinning you can do `nixos-rebuild build` -- it will generate a symlink which makes the generation stay while it exists.

**Comment by RonnyPfannschmidt** [comment]
@abbradar but i already have a existing good generation, is there a way to pin it without having to figure how to restore the build conditions, because currently it does not build and i'm not fluent with the nix tooling around generations, history and restoring it

**Comment by abbradar** [comment]
You can clean up symlinks in `/nix/var/nix/profiles` manually and then run `nix-collect-garbage` without `-d`; there's nothing better that I can remember off the top of my head.

**Comment by RonnyPfannschmidt** [comment]
[X.0.log.old.txt](https://github.com/NixOS/nixpkgs/files/858665/X.0.log.old.txt)
[X.bumblebee.log.txt](https://github.com/NixOS/nixpkgs/files/858666/X.bumblebee.log.txt)

**Comment by RonnyPfannschmidt** [comment]
[X.0.log.txt](https://github.com/NixOS/nixpkgs/files/858699/X.0.log.txt)

**Comment by RonnyPfannschmidt** [comment]
[lastboot.log.txt](https://github.com/NixOS/nixpkgs/files/858724/lastboot.log.txt)

**Comment by RonnyPfannschmidt** [comment]
[lastboot.log.txt](https://github.com/NixOS/nixpkgs/files/858770/lastboot.log.txt)

**Comment by RonnyPfannschmidt** [comment]
@abbradar helped me to discover the true issue, its reported in #24172
