### ISSUE TITLE
iproute2's buildFlags do not reference the derivation

### ISSUE THREAD

**Issue by alphor** [NixOS/nixpkgs#23625]
## Issue description

Currently, iproute2's confdir points to the conventional confdir, which doesn't exist in NixOS. Config will be generated in the store, but at runtime it will look for conf in /etc/iproute2. An easy fix would be to prepend $(out) to [ assignment in the line here.](https://github.com/NixOS/nixpkgs/blob/08d1f28818cd4518f96f838bd0d99df9d0b8c9e9/pkgs/os-specific/linux/iproute/default.nix#L37) turning this:
``` nix
  buildFlags = [
    "CONFDIR=/etc/iproute2"
  ];
```

into this:
``` nix
   buildFlags = [
      "CONFDIR=$(out)/etc/iproute2"
   ];
```

### Steps to reproduce

Declare/Install iproute2, add a table to rt_tables (or any arbitrary configuration that belongs in /etc/iproute2 on a regular linux environment):

``` nix
   nixpkgs.config.packageOverrides = pkgs:
     {
       iproute = pkgs.stdenv.lib.overrideDerivation pkgs.iproute (attrs: {
         postInstall = ''
           echo 21 eth0 >> $out/etc/iproute2/rt_tables
           echo 22 eth1 >> $out/etc/iproute2/rt_tables
         '';
         });
     };
```

Note iproute does not have a postInstall phase declared currently, so there is no need to retrieve it with ${attrs.postInstall}

Then run the following to observe the binary looking for config in the wrong place:
``` bash
strace ip route add default via 172.29.1.1 table eno1
```
The route, ip address, and interface name are all arbitrary to repro, just ask to amend some routing table that isn't stock.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1821.0cb2838 (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.7

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.1821.0cb2838"

**Comment by lheckemann** [comment]
Making this change would prevent later integration of the config into a NixOS module, and mean having to modify iproute2 to modify its configuration. I'd say adding a configuration module to generate `/etc/iproute2` feels like the "right" way to solve this problem. I'm guessing that (or manual configuration in /etc) is what @wkennington had in mind in fa0b84c446a7 as well.

**Comment by alphor** [comment]
Thanks for digging up the commit. I figured it might have been intentional, and wanted to see why it was done. Ooc, why can't this be reverted when it is integrated? Isn't where the configuration is located opaque to the user anyway?

In the meantime, I've worked around this by overriding the build flags. For anyone else running into the same problem, there's a description of [how to do that here](http://nixos.org/nixos/manual/index.html#sec-customising-packages).

**Comment by lheckemann** [comment]
> Isn't where the configuration is located opaque to the user anyway?
Not really, the user is free to put whatever they want into /etc wherever it doesn't interfere with nixos's generated config. It's not "The NixOS Way" but it will work.

**Comment by alphor** [comment]
Closing since this is intended config.

**Comment by coretemp** [comment]
It seems that the issue of creating route tables is valid, but that there is simply no NixOS module to configure this. Shouldn't this be reopened until such a module exists?

**Comment by globin** [comment]
You can do this for now:
```
  environment.etc."iproute2/rt_tables".text = ''
    200 hetzner
  '';
```
