### ISSUE TITLE
input-remapper service does not start

### ISSUE THREAD

**Issue by rolfschr** [NixOS/nixpkgs#236441]
### Describe the bug

I cannot use the `input-remapper` package. The service doesn't start. The error message is `ERROR: Is the service already running? (g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.83" is not allowed to own the service "inputremapper.Control" due to security policies in the configuration file (9))`

### Steps To Reproduce

```bash
sudo nix-env -iA nixos.input-remapper
sudo systemctl enable-then-start input-remapper.service # even after reboot
```

### Expected behavior

Service starts. `input-mapper-gtk` can be launched afterwards.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/1188465/9da4970d-80fa-4acc-81c7-d7acba3ef03f)

### Additional context

I feel like this is a problem with polkit/systdem/dbus but I have no clue about these frameworks.

I realize that the following lines might be missing. I added them to `preFixup` for testing purposes (i.e. during `postInstall`, the files are not yet in `$out/...`)
```bash
    sed -r "s#/usr/bin/input-remapper-control#$out/bin/input-remapper-control#g" -i $out/share/polkit-1/actions/input-remapper.policy
    sed -r "s#/usr/bin/input-remapper-control#$out/bin/input-remapper-control#g" -i $out/usr/share/input-remapper/input-remapper.policy
```

I used them like so but the newly installed service was still not working for me:

```nix
# Install with nix-env -if <file.nix>
{ pkgs ? import <nixpkgs> {} }:

pkgs.input-remapper.overrideAttrs (oldAttrs: {
  preFixup = oldAttrs.preFixup + ''
    sed -r "s#/usr/bin/input-remapper-control#$out/bin/input-remapper-control#g" -i $out/share/polkit-1/actions/input-remapper.policy
    sed -r "s#/usr/bin/input-remapper-control#$out/bin/input-remapper-control#g" -i $out/usr/share/input-remapper/input-remapper.policy
  '';
})



```

### Notify maintainers

@LunNova @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.112, NixOS, 22.11 (Raccoon), 22.11.4369.99fe1b87052`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(rolf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by SuperSandro2000** [comment]
> ### Steps To Reproduce
> Steps to reproduce the behavior:
> 
> ```shell
> sudo nix-env -iA nixos.input-remapper
> sudo systemctl enable-then-start input-remapper.service # even after reboot
> ```

that will not work, use the nixos module.

**Comment by LunNova** [comment]
`services.input-remapper.enable = true;` should be all you need in your nixos config, adhoc installation without the module isn't expected to work.

In general if a service has a nixos module that's the supported way to use it.

**Comment by rolfschr** [comment]
@SuperSandro2000 @LunNova Thanks, this works as expected. I didn't know there was a module.

Would you like me to open a PR with the `sed` commands I mentioned above? It is apparently not needed but maybe for the sake of consistency?
