### ISSUE TITLE
catch_conflicts.py is using substantial amounts of cpu

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#23647]
I'm packaging some python and packages that take ~5 seconds to build and test then execute  `catch_conflicts.py` for up to 30s. 

I'm not sure why yet but also don't want to forget about this.

**Comment by dezgeg** [comment]
It sounded like https://github.com/NixOS/nixpkgs/pull/23600 solves it.

**Comment by teh** [comment]
Apologies, I searched and still missed that. Closing.
