### ISSUE TITLE
Haskell documentation suggestions

### ISSUE THREAD

**Issue by taktoa** [NixOS/nixpkgs#23645]
## Intro

This isn't really an issue so much as a braindump of some ideas I've had lately that I'd be interested in hearing feedback on. I might implement some of these things in the medium term (i.e. 3-6 months from now), depending on reception from other Haskell + NixOS people.

### Dash/Zeal Documentation Generation

Dash is a (proprietary) documentation browser for Mac OS, and Zeal is a format-compatible free software substitute. A Dash/Zeal docset (heretofore referred to as a "Zeal docset") comprises everything needed to browse documentation for a given piece of software. Currently there is a program called [haddocset][] on [Hackage][haddocset-hackage] that can generate a docset from the output of Haddock, and I have tested it and it seems to work pretty well with Zeal at least. There is also a program called [dash-haskell][] with similar goals but its last commit was 2 years ago, versus 7 months ago for haddocset, so unless it's drastically better in some dimension I am not aware of, I think haddocset is probably the way to go.

My plans regarding Zeal / haddocset are as follows:

1. Figure out how to integrate Zeal docsets with the Zeal Nix expression; currently when you install Zeal it simply downloads the docsets you want into `~/.local/share/Zeal/...`, but I think it would be nice if there were some Nix infrastructure for Zeal (e.g.: setting up Zeal to expect immutable docsets in `~/.nix-profile/share/zeal`) so that you can get documentation straight out of a Nix build and into Zeal.
2. Figure out how best to integrate haddocset into a Nix build, so that, for example, duplication of all the generated documentation is avoided. I mean, the duplication isn't _that_ big of a deal since you can just run `nix-store --optimise`, but I'd rather avoid the extra downloads and such. I _think_ this shouldn't be hard to accomplish; haddocset has two sub-commands: `haddocset create` and `haddocset add <path-to-haddock>`, so all I would have to do is write a deduplication script that works on a single Haskell package (this is nice because it means that the simple `O(n^2)` approach of matching every file against every other file won't be too terrible, though it might still be easier to implement it with hashing).
3. If desirable, upstream a Nix expression similar to `ghcWithHoogle` that can generate a set of packages along with a Hoogle dataset, a Zeal docset, and Haddock documentation with the usual index. While I'm working with that stuff, I would also be interested in making a new alternative to `ghcWith*` that simply accepts `enableHoogle` and `enableZeal` as extra arguments; I don't relish the idea of having `ghcWithHoogle`, `ghcWithZeal`, and `ghcWithHoogleAndZeal`.

[haddocset]: https://github.com/philopon/haddocset
[haddocset-hackage]: https://hackage.haskell.org/package/haddocset
[dash-haskell]: https://github.com/jfeltz/dash-haskell

### Improved Haddock Documentation

[This](https://github.com/lamefun/haddock) branch of Haddock has some really good-looking improvements to its UX; you can see an example of its output [here](https://lamefun.github.io). I know that it would be a bit weird to have nixpkgs switch to some random GitHub branch of Haddock just for a prettier UI, but since the Haddock generation happens during the build, any change to Haddock will result in a mass rebuild. I thought about just waiting for it to go upstream, but there are two issues with that: firstly, even if it did go upstream, it probably wouldn't be the default, and secondly, Haddock's pace of development is _very_ slow from what I've seen, so I suspect it will be a long wait. Most of the interesting changes in that repository are changes to the CSS and JS of the generated documentation, but there are also some changes to the way Haddock generates documentation. A while ago, I made an attempt to rebase those 9 commits onto Haddock upstream master, but it turned out to be a bit tricky and I was too busy to work more on it. In any case, I think that switching to this modified Haddock would basically be pure win: the small minority of people who don't like the new documentation can just go on Hackage or build their own packages, and the rest of us get a shinier UI. Of course, there are also correctness/stability/security/maintainability concerns, but given the small scope of these modifications to Haddock, I suspect those won't be much of a problem.

One possible alternative to the above thoughts on Haddock is that we could refactor haskellPackages so that there is a separate documentation derivation for every package. This would alleviate the situation in which every change to Haddock requires a haskellPackages mass-rebuild. I am not an expert on the precise runtime performance of Nix, but I suspect this would increase evaluation times for haskellPackages at least a little bit, and since haskellPackages already takes an insanely long time to evaluate, I think that makes this alternative a non-starter for now (though I have my fingers crossed that someone is going to delve into the source code of Nix and make it do more JIT to improve efficiency).

**Comment by hussein-aitlahcen** [comment]
Would be awesome, you still plan to implement it ?

**Comment by evanjs** [comment]
This sounds quite interesting. 

I've long been a Dash user--at least until Dash for iOS was [discontinued](https://kapeli.com/dash_ios). 

Zeal has been my go to for desktop devices (whenever I'm not on a Mac, of course), and it would be very interesting to see this more deeply integrated with NixOS.

**Comment by cdepillabout** [comment]
Seems like there hasn't been any activity on this in a few years, I'll go ahead and close.

If there is someone still interested in working on this, feel free to post and we can re-open this issue.
