### ISSUE TITLE
Caffe fails to build

### ISSUE THREAD

**Issue by changlinli** [NixOS/nixpkgs#23658]
## Issue description

Trying to install caffe fails out with a build error.

### Steps to reproduce

Neither adding `caffe` to `configuration.nix` under NixOS nor running `nix-env -iA nixos.caffe` completely successfully.

They both result in the fulling error:

    include/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined

This looks like [a](http://stackoverflow.com/questions/34959032/nvcc-and-boost-1-60-error-identifier-float128-is-undefined) [problem](https://github.com/FFTW/fftw3/issues/18) [that](https://github.com/BVLC/caffe/issues/3578) other people have faced.

It is part of a longer error message that looks like this

    CXX src/caffe/layers/multinomial_logistic_loss_layer.cpp
    CXX src/caffe/layers/cudnn_pooling_layer.cpp
    CXX src/caffe/internal_thread.cpp
    CXX src/caffe/common.cpp
    CXX src/caffe/syncedmem.cpp
    CXX src/caffe/layer_factory.cpp
    CXX src/caffe/data_transformer.cpp
    CXX src/caffe/net.cpp
    NVCC src/caffe/util/im2col.cu
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    In file included from /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/cuda_runtime.h:62:0,
                     from <command-line>:0:
    /nix/store/awrlhrs9w22ikh3hqjzl8gilzp3r7awl-cudatoolkit-7.0.28/include/host_config.h:105:2: warning: #warning -- unsupported GNU version! gcc 4.10 and up are not supported! [-Wcpp]
     #warning -- unsupported GNU version! gcc 4.10 and up are not supported!
      ^
    include/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined
    
    1 error detected in the compilation of "/tmp/nix-build-caffe-git-2015-07-02.drv-0/tmpxft_00000675_00000000-16_im2col.compute_50.cpp1.ii".
    make: *** [Makefile:531: .build_release/cuda/src/caffe/util/im2col.o] Error 1
    builder for ‘/nix/store/cnlhdci51q9i9vby8ijrjygpihqqp265-caffe-git-2015-07-02.drv’ failed with exit code 2
    error: build of ‘/nix/store/cnlhdci51q9i9vby8ijrjygpihqqp265-caffe-git-2015-07-02.drv’ failed

## Technical details

* System: 16.09.1803.40de598 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1803.40de598"

**Comment by changlinli** [comment]
@ndowens If you have the changes, I can apply them on my system and give it a shot

**Comment by yegortimoshenko** [comment]
`caffe` now served from binary cache, meaning it builds.
