### ISSUE TITLE
noisetorch missing capabilities and hence fails to run

### ISSUE THREAD

**Issue by haizaar** [NixOS/nixpkgs#236577]
### Describe the bug
noisetorch doesn't work because of missing capabilities
![image](https://github.com/NixOS/nixpkgs/assets/58201/132cffc4-b612-4459-a4a6-fc8bc173d2e6)

Granting them post factum dosn't work obviously:
```
$ sudo setcap 'CAP_SYS_RESOURCE=+ep' /nix/store/4j0n2jd7z5v70sc6ixwxjml7wzlrpzsn-NoiseTorch-0.12.0/bin/noisetorch
Failed to set capabilities on file '/nix/store/4j0n2jd7z5v70sc6ixwxjml7wzlrpzsn-NoiseTorch-0.12.0/bin/noisetorch': Read-only file system
```

The manual [says](https://github.com/noisetorch/NoiseTorch#download--install)  to run `setcap 'CAP_SYS_RESOURCE=+ep'` on the binary.

### Steps To Reproduce
1. install noisetorch
2. try to use it.

### Expected behavior
UI with show up.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/58201/bc924a2d-20a3-4fef-bc7b-e5469d8412ff)
### Notify maintainers

@panaeon @lom @SuperSandro2000 can you please have a look?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.112, NixOS, 22.11 (Raccoon), 22.11.4478.eaf03591711`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos````

**Comment by PanAeon** [comment]
Hi, do you use it, as a nixos module (e.g. `programs.noisetorch.enable = true`) or as a regular package? I believe necessary capabilities are added when noisetorch is used as a module.

**Comment by haizaar** [comment]
Yeap, the module indeed sets the caps properly. Thank you for the quick reply!
