### ISSUE TITLE
Libreoffice fails to build

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#23662]
### Issue description
Libreoffice can't be built, tested on two machines (Laptop and Desktop)
The error is:
```
In file included from /tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/i18npool/source/breakiterator/breakiterator_unicode.cxx:27:0:
/nix/store/ajlnqc90b5k6263pgjv7kxz6ng9z2wn1-icu4c-58.2-dev/include/unicode/rbbi.h: In member function 'void com::sun::star::i18n::OOoRuleBasedBreakIterator::publicSetBreakType(int32_t)':
/nix/store/ajlnqc90b5k6263pgjv7kxz6ng9z2wn1-icu4c-58.2-dev/include/unicode/rbbi.h:657:10: error: 'void icu_58::RuleBasedBreakIterator::setBreakType(int32_t)' is private
     void setBreakType(int32_t type);
          ^
/tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/i18npool/source/breakiterator/breakiterator_unicode.cxx:68:13: error: within this context
             setBreakType(type);
             ^
In file included from /tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/i18npool/source/breakiterator/breakiterator_unicode.cxx:27:0:
/nix/store/ajlnqc90b5k6263pgjv7kxz6ng9z2wn1-icu4c-58.2-dev/include/unicode/rbbi.h:657:10: error: 'void icu_58::RuleBasedBreakIterator::setBreakType(int32_t)' is private
     void setBreakType(int32_t type);
          ^
/tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/i18npool/source/breakiterator/breakiterator_unicode.cxx:68:30: error: within this context
             setBreakType(type);
                              ^
make[1]: *** [/tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/solenv/gbuild/LinkTarget.mk:191: /tmp/nix-build-libreoffice-5.2.5.1.drv-0/libreoffice-5.2.5.1/workdir/CxxObject/i18npool/source/breakiterator/breakiterator_unicode.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:260: build] Error 2
builder for ‘/nix/store/0s8k8k4shwk0bn3q5fszd16g634fp0wk-libreoffice-5.2.5.1.drv’ failed with exit code 2
```

### Steps to reproduce
`git pull upstream; nixos-rebuild boot -I $MyNixPath`

**Comment by 7c6f434c** [comment]
Yes, our version Libreoffice Still (but not Fresh) seems to be incompatible with the freshest ICU (which in turn is a requirement for fresh Firefox). Maybe a bump to 5.2.6.2 will help, not sure yet

**Comment by 7c6f434c** [comment]
OK, it doesn't help…

**Comment by 7c6f434c** [comment]
Well, building it is not the real interesting problem, looks like both versions of LibreOffice are broken by some recent update…

**Comment by 7c6f434c** [comment]
I think current `master` version builds `libreoffice-still`, but I haven't fixed the problem with `G_IS_LO_MENU` yet

**Comment by ikervagyok** [comment]
Thank you for looking into the subject. Please tell me if I can help you

**Comment by c0bw3b** [comment]
(best to exchange here rather than commenting on a commit)
LibreOffice failing to build with ICU 58.x has been fixed in [this commit](https://gerrit.libreoffice.org/gitweb?p=core.git;a=commitdiff;h=3e42714c76b1347babfdea0564009d8d82a83af4) / [this change](https://gerrit.libreoffice.org/#/c/30487/).

I am trying to figure in which release of LO it was shipped.

**Comment by 7c6f434c** [comment]
Not «none», Fresh-only…

**Comment by 7c6f434c** [comment]
It looks like the patch applies, maybe it will even build.

**Comment by 7c6f434c** [comment]
ICU 58 for LibreOffice Still committed to `master`. The broken menu seems to be a long-running problem, not sure when it has started

**Comment by vcunat** [comment]
> LibreOffice 5.2.5.1 and 5.2.6.2 seems to use function setBreakType that was public in ICU 57.1 and is private in ICU 58.1 and ICU 58.2.

That's strange.  `APIChangeReport.html` included in icu (58.2) tarball doesn't mention that function at all.  It actually doesn't mention removing anything in 57 -> 58, only deprecating some APIs, etc.

**Comment by 7c6f434c** [comment]
Well, the LibreOffice commit mentioned in this issue explicitly mentions
that the function has been moved from protected to private in C++ API.

**Comment by vcunat** [comment]
I'm currently wondering what to do about icu on stable branches, as we need to keep updating Firefox because of security.  I thought I'd rely on `APIChangeReport.html` but it doesn't seem that much reliable...

**Comment by 7c6f434c** [comment]
Maybe the patch would apply to 5.1.x, have you tried?

**Comment by vcunat** [comment]
Patching LibreOffice might be an alternate approach on master as well, but I haven't tried.  First I'm mainly wondering which of the libs to update *system-wide* on stable releases.

**Comment by 7c6f434c** [comment]
I have patched LO-Still on master already to work with ICU58.

**Comment by 7c6f434c** [comment]
I have just checked: my LibreOffice problem was a hard dependency on existence of a DBus session. Wasn't a requirement previously.

@ikervagyok any remaining issues or should this be closed?

**Comment by ikervagyok** [comment]
i'm rebuilding my laptop and workstation atm, soon i'll be able to test this

**Comment by ikervagyok** [comment]
my laptop is still rebuilding, as my hardrive filled up last night, but LO on my workstation seems to work.
closing, as this issue is resolved for me. reopen, if you think there's more to do.
