### ISSUE TITLE
Keyd settings can't remap non alpha keys

### ISSUE THREAD

**Issue by leg7** [NixOS/nixpkgs#236622]
### Describe the bug
When using services.keyd.settings it's not possible to remap special characters and numbers.

```
error: syntax error, unexpected invalid token

       at /nix/store/gqbz75affx5x5yi6zd4bfwkxdjix4r5r-source/modules/base.nix:137:9:

          136|
          137|         ` = "$";
             |         ^
          138|         1 = "&";
(use '--show-trace' to show detailed location information)
```

### Steps To Reproduce
Code I used:
```
  services.keyd = {
    enable = true;
    ids = [ "03eb:ff01" "0001:0001" ];
    settings = {
      main = {
        capslock = "escape";
        escape = "capslock";

        ` = "$";
        1 = "&";
        2 = "[";
        3 = "{";
        4 = "}";
        5 = "(";
        6 = "=";
        7 = "*";
        8 = ")";
        9 = "+";
        0 = "]";
        - = "!";
        = = "#";

        q = ";";
        w = ",";
        e = ".";
        r = "p";
        t = "y";
        y = "f";
        u = "g";
        i = "c";
        o = "r";
        p = "l";
        [ = "/";
        ] = "@";

        a = "a";
        s = "o";
        d = "e";
        f = "u";
        g = "i";
        h = "d";
        j = "h";
        k = "t";
        l = "n";
        ; = "s";
        ' = "-";

        z = "'";
        x = "q";
        c = "j";
        v = "k";
        b = "x";
        n = "b";
        m = "m";
        , = "w";
        . = "v";
        / = "z";

      };
      shift = {
        ` = "~";
        1 = "1";
        2 = "2";
        3 = "3";
        4 = "4";
        5 = "5";
        6 = "6";
        7 = "7";
        8 = "8";
        9 = "9";
        0 = "0";
        - = "%";
        = = "`";

        ] = "^";
      };
    };
  };
```

### Additional context
Maybe I'm missing something syntax wise?

### Notify maintainers
@woojiq 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230605.7409480`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by woojiq** [comment]
@leg7 you need to take non alpha keys in quotes. This is not related to keyd service but to nix language. So this works for me:
```nix
services.keyd = {
    enable = true;
    ids = [ "*" ];
    settings = {
      main = {
        "`" = "$";
};};};
```

**Comment by leg7** [comment]
> @leg7 you need to take non alpha keys in quotes. This is not related to keyd service but to nix language. So this works for me:
> 
> ```nix
> services.keyd = {
>     enable = true;
>     ids = [ "*" ];
>     settings = {
>       main = {
>         "`" = "$";
> };};};
> ```

Thank you this works. I did try that but I guess I must have missed one so I thought it didn't work. Maybe it would be good to add this to the example?

**Comment by woojiq** [comment]
> Maybe it would be good to add this to the example?

If I add something new to the service, I'll add an example like this. But I don't want to create a PR just for this change.
I'm glad I helped you. If there are no questions, feel free to close the issue 😇

**Comment by leg7** [comment]
kk

**Comment by woojiq** [comment]
Yes, something strange happens when writing `"=" = "1"`. If you look at the generated `/etc/keyd/default.conf` file, you will see `\==1` but expected is `==1`. This is also related to the nix language. I don't know why it escapes "=" with backslash, I'll try to investigate.

**Comment by leg7** [comment]
Yep this works great thanks a lot!

If you get the chance to update the service I think it would be very helpful to mention these pitfalls.

o/
