### ISSUE TITLE
Can't enable the qbittorrent-nox@.service SystemD service unit

### ISSUE THREAD

**Issue by Amilton78** [NixOS/nixpkgs#236736]
### Describe the bug
Can't start/enable the qbittorrent-nox@.service unit because it is not in the usual systemd directories, if  qbittorrent-nox is installed systemwide, the unit is in /run/booted-system/sw/lib/systemd/system/qbittorrent-nox@.service
or if it is installed to a specific user it can be found in /etc/profiles/per-user/(username here)/lib/systemd/system/qbittorrent-nox@.service
From what I understand, units should be placed either in /usr/lib/systemd/system/(not present on NixOS) or in /etc/systemd/system/

### Steps To Reproduce
1. Install qbittorrent-nox, systemwide or to a specific user
2. Try to start or enable qbittorrent-nox@(your username).service
3. See the unit can't be found

### Expected behavior
The unit would be in the correct place and could be enabled/started

### Notify maintainers
@5aaee9 (sorry if you're not the right person)

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.553.e7603eba51f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(my username): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
No, this is not how systemd services are enabled on NixOS. Adapting the example mentioned in https://github.com/NixOS/nixpkgs/issues/80933#issuecomment-1295396500:

```nix
  environment.systemPackages = [pkgs.qbittorrent-nox];
  systemd = {
    packages = [pkgs.qbittorrent-nox];
    services."qbittorrent-nox@example" = {
      overrideStrategy = "asDropin";
      wantedBy = ["multi-user.target"];
    };
  };
```
(replace `example` here, of course.)
