### ISSUE TITLE
mpc: name clash causes mutual exclusion in nix-env

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#2367]
I wanted to install `mpc`, the MPD client.

```
[shana@lenalee:~/programming]$ nix-env -qa | grep mpc
gmpc-11.8.16
libmpcdec-1.2.6
mpc-0.25
mpc-1.0.1
mpc123-0.2.4
ncmpc-0.21
ncmpcpp-0.5.10
pypy2.2-stompclient-0.3.2
python2.7-stompclient-0.3.2
python3.3-stompclient-0.3.2
python3.4-stompclient-0.3.2
```

Cool, it's packaged. I proceed to `nix-env -i mpc` and then try to run it.

```
[shana@lenalee:~]$ nix-env -i mpc
replacing old `mpc-1.0.1'
installing `mpc-1.0.1'

[shana@lenalee:~]$ mpc
The program ‘mpc’ is currently not installed. You can install it by typing:
  nix-env -i mpc
```

Huh?

After few minutes I realised that there are actually 2 packages called `mpc` in nixpkgs: [`mpc-0.25`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/mpc/default.nix) is the MPD client but [`mpc-1.0.1`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/mpc/default.nix) is an arithmetic package.

OK, I think, I'll just explicitly state that I want the client version:

```
[shana@lenalee:~/programming]$ nix-env -i mpc-0.25
replacing old `mpc-1.0.1'
installing `mpc-0.25'
these paths will be fetched (0.20 MiB download, 2.01 MiB unpacked):
  /nix/store/946nk6id0gpxjp911j3fcvymq9hq50wp-libmpdclient-2.9
  /nix/store/z6icszjx38dhgj5ckffal8k6qnp4fg2s-mpc-0.25
fetching path `/nix/store/946nk6id0gpxjp911j3fcvymq9hq50wp-libmpdclient-2.9'...

*** Downloading ‘http://cache.nixos.org/nar/0aadjf3qcjzwbil94bjp0s3l9ks4xh56vhzsy6w77n4slsfafhbw.nar.xz’ to ‘/nix/store/946nk6id0gpxjp911j3fcvymq9hq50wp-libmpdclient-2.9’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164k  100  164k    0     0   339k      0 --:--:-- --:--:-- --:--:--  339k

fetching path `/nix/store/z6icszjx38dhgj5ckffal8k6qnp4fg2s-mpc-0.25'...

*** Downloading ‘http://cache.nixos.org/nar/1kz93vcgr3mxghk0i89qa76w3lahdvpwnr5gmx59044hckhxd23y.nar.xz’ to ‘/nix/store/z6icszjx38dhgj5ckffal8k6qnp4fg2s-mpc-0.25’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38408  100 38408    0     0   117k      0 --:--:-- --:--:-- --:--:--  117k

building path(s) `/nix/store/8isagz6mmhvwr4wgn66h2hiwlwxkl9lr-user-environment'
created 2775 symlinks in user environment
```

What‽ It replaced `mpc`, the arithmetic library!

This is a big problem, two completely different programs can't co-exist because they have the same name! Come on guys, this is why package namespaces exist! What will happen if I state `mpc` as a dependency for my package? I'll currently get the library. What if `mpc`-the-client decides to start numbering with major versions? In 6 months I might get `mpc`-the-client and not `mpc`-the-library. Big problem.

**Comment by amurrayc** [comment]
It is also a problem that, after installing mpc_cli correctly using the nixos.pkgs.mpc_cli attribute path,
nix-env -u "upgrades" it to nixos.pkgs.mpc (the other package).

**Comment by vcunat** [comment]
Ah, I forgot this. I'll do that renaming.

**Comment by vcunat** [comment]
Fixed in staging, autoclosing when hits master.
