### ISSUE TITLE
Many Travis tests are failing due to xen not working on i686

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#23690]
## Issue description

Here is an example but there are loads more:
https://travis-ci.org/NixOS/nixpkgs/jobs/209637602

```
Package ‘xen-4.5.5’ in ‘/home/travis/build/NixOS/nixpkgs/pkgs/applications/virtualization/xen/generic.nix:210’ is not supported on ‘i686-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set

  { nixpkgs.config.allowBroken = true; }

in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add

  { allowBroken = true; }

to ~/.config/nixpkgs/config.nix.
```

**Comment by ttuegel** [comment]
We should be setting `NIXPKGS_ALLOW_BROKEN = 1` in the builder environment.

**Comment by dezgeg** [comment]
No, actually this means the NixOS manual doesn't evaluate on i686. Sounds like the `nixos/modules/virtualisation/xen-dom0.nix` module should be disabled on i686.

**Comment by oxij** [comment]
No, actually, this is just a bug I introduced with `916fa0a6102a75325dbc3ffca5e88ec435aeffa4`.

Merge https://github.com/oxij/nixpkgs/tree/nixos/xen-oops to fix.

**Comment by oxij** [comment]
Well, even more precisely, the actual bug here is that nixos modules evaluate `default` even when `defaultText` is given.
But the nixos/xen-oops branch should be an okay temporary fix for now.

**Comment by globin** [comment]
Pushed as 2822bacd60

**Comment by tanzeelrana** [comment]
tanzeel@tanzeel-HP-Compaq-dx7500-SFF:~/cardano-sl$ nix-build -A cardano-sl-static --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0
error: Package ‘rocksdb-5.1.2’ in /nix/store/vjar9blzzimkbfq1p0xmqx4jkqqhplax-61fbdb47a69f78998f55207e64122a0798047b5d.tar.gz-unpacked/pkgs/development/libraries/rocksdb/default.nix:66 is not supported on ‘i686-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
