### ISSUE TITLE
Clementine refuses to install because dependency libplist-1.12 is marked as insecure

### ISSUE THREAD

**Issue by xvapx** [NixOS/nixpkgs#23696]
## Issue description
[clementine](https://github.com/NixOS/nixpkgs/blob/3d104ab2b3e578cb4599b6fffbcc019b09547521/pkgs/applications/audio/clementine/default.nix) has an optional dependency on [libplist,](https://github.com/NixOS/nixpkgs/blob/8f60b43d9c46ac59722262d545025f23bfb8bb68/pkgs/development/libraries/libplist/default.nix), wich has been marked as insecure in [this](https://github.com/NixOS/nixpkgs/commit/30cea5f02245a20022ea93f8eec2f4fe053ad97a) commit.
It is possible to install it by adding "libplist-1.12" to nixpkgs.config.permittedInsecurePackages, but given that it is an optional dependency, it might be preferable to build clementine without it.

### Steps to reproduce

`nix-env -i clementine`

## Technical details

* System: NixOS: 17.09pre102667.2839b10 (Hummingbird)
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre102667.2839b10

### Suggestion

I would like to submit a PR to add config.clementine switches to be able to easily deactivate any optional dependencies.

**Comment by 0xABAB** [comment]
Can you contact the author of libplist with the kind request to fix the problems he created in the first place?

**Comment by xvapx** [comment]
I see that @grahamc did already contact them. 
As you can see in [issue 96](https://github.com/libimobiledevice/libplist/issues/96), @grahamc did even offer to help. 
In the meantime, with this patch, at least we are able to build clementine without ipod support to avoid depending on libplist.
It can easily be activated back if anybody wants to have ipod support, even if it is insecure.
