### ISSUE TITLE
Firefox non-ESR cannot access microphone

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#23702]
## Issue description
(originally reported by @rardiol on IRC some months ago, then encountered by me as well)
Firefox seem unable to access the microphone, some online tests report that the system doesn't have a microphone while it actually does, other tests hang.
Installing firefox ESR 

I don't have a webcam so I don't know whether this applies to it or to the audio part only. Also I don't know if this is an upstream bug or if it applies to nixos only.

### Steps to reproduce

nix-env -i nixos.firefox → installs firefox 51.0.1 at present
go to some online tests like https://www.onlinemictest.com/ or https://www.webrtc-experiment.com/RecordRTC/ and see them not working

nix-env -e firefox
nix-env -iA nixos.firefox-esr -> installs 45.7.0
same tests can access microphone

## Technical details

* System: 16.09.1827.f89ab94 (Flounder)
* Nix version: 1.11.7

**Comment by 7c6f434c** [comment]
Does setting media.navigator.audio.full_duplex to false in about:config
change the situation for the fresh Firefox?

**Comment by zarelit** [comment]
@7c6f434c After restarting Firefox, yes it does

**Comment by zarelit** [comment]
@7c6f434c Thank you very much for your help, it seems that Arch has [this issue](https://wiki.archlinux.org/index.php/Firefox#Firefox_WebRTC_module_cannot_detect_a_microphone) as well, so I think it's to be considered an upstream bug, right?

**Comment by 7c6f434c** [comment]
The workaround I have given you comes from an upstream discussion, so if
it works for you too, it is still the same (or closely related) upstream
issue.

**Comment by vandenoever** [comment]
Setting media.navigator.audio.full_duplex to false in about:config solves the issue for me too. Still no video though even though camera works with gnome3.cheese.
