### ISSUE TITLE
nm-applet uses the 'memory' GSettings backend

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#23700]
## Issue description

`nm-applet` is using the _memory_ GSettings backend on my unstable NixOS system. Because of that it forgets any change in its settings done by the user.

The window manager used is `openbox`. The system configuration has `pkgs.gnome3.dconf` in `services.dbus.packages`.

Before the latest change (https://github.com/NixOS/nixpkgs/commit/8aa73bbf55884d2a94db0e54aa5ceb92a513371b) `${gnome3.dconf}/lib/gio/modules` was added to `GIO_EXTRA_MODULES` in an explicitly wrapper, which was replaced by `wrapGAppsHook`. There is no explicitly mention of `dconf` anymore in the nix expression after this change. Can it be related?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.09pre102667.2839b10 (Hummingbird)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.7`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.09pre102667.2839b10"`

**Comment by abbradar** [comment]
Yeah, this is related -- my fault. Thanks!
