### ISSUE TITLE
Package request: SteamCMD

### ISSUE THREAD

**Issue by ldesgoui** [NixOS/nixpkgs#23719]
EDIT: steamcmd can be ran using steam-run

Hello,

I've tried making steamcmd work on NixOS (17.09pre102441.45344fd) but I was stopped by my lack of knowledge, I attempted patching the ELF binary following http://sandervanderburg.blogspot.fr/2015/10/deploying-prebuilt-binary-software-with.html, sadly it's throwing me 
`-bash: ./result/bin/steamcmd: Accessing a corrupted shared library`

Seems like steamcmd is not distributed by version either, would that refrain it from being a nixos package?

https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by pstn** [comment]
Could you post the code of what you did? I think you are trying to link it to 64bit libraries.

**Comment by ldesgoui** [comment]
Sadly I deleted the code, but it wasn't far from 

    with import <nixpkgs> {};
    
    stdenv.mkDerivation {
      name = "steamcmd-20170309";
    
      src = ...
    
      installPhase = ''
        mkdir -p $out/{lib,bin}
        cp steamcmd $out/bin
        cp lib*.so.* $out/bin
        patchelf \
            --set-interpreter ${stdenv.glibc}/lib/ld-linux-x86-64.so.2 \
            --set-rpath $out/lib \
            $out/bin/steamcmd
      '';
    }

I am indeed running 64bit, while trying to hack it together using already-existing closures(?) in the nix/store, it did complain about 32/64 ELF values.

**Comment by ldesgoui** [comment]
EDIT: I recovered the

**Comment by ldesgoui** [comment]
Oops

**Comment by abbradar** [comment]
I've tried it locally, but that doesn't work because of unknown reason (exit code after update, no segfault):

```
{ stdenv, lib, fetchurl }:
    
stdenv.mkDerivation {
  name = "steamcmd";

  src = fetchurl {
    url = "http://media.steampowered.com/installer/steamcmd_linux.tar.gz";
    sha256 = "1f7rl3mhb6rqxw4w5x6nnv04myv8gyknmz91pdp06i2s3pw85qy7";
  };
    
  buildCommand = ''
    unpackPhase
    install -Dm755 steamcmd.sh $out/bin/steamcmd
    patchShebangs $out/bin/steamcmd
    sed -i "s,^STEAMROOT=.*,STEAMROOT=$out/libexec,g" $out/bin/steamcmd
    install -Dm755 linux32/steamcmd $out/libexec/linux32/steamcmd
    patchelf \
      --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) \
      --set-rpath "${lib.makeLibraryPath [ stdenv.cc.cc ]}" \
      $out/libexec/linux32/steamcmd
  '';
}
```

(call with `callPackage_i686`).

**Comment by abbradar** [comment]
Worst-case you can use `steam-run` to run it: `steam-run ./steamcmd.sh`.

**Comment by AndersonTorres** [comment]
As far as I remember, Steam is a bit annoying to run ina NixOS-like environment. It requires a FHS-compliant system, and "patchelf"-ing doesn't work because it checksums itself.

There is a different way to deal with steam and similar packages, but I don't remember perfectly. Googling, I found some links:

Closed Issue #11227 (https://github.com/NixOS/nixpkgs/issues/11227)

https://nixos.org/wiki/Steam
http://sandervanderburg.blogspot.com.br/2013/09/composing-fhs-compatible-chroot.html
https://git.stoo.org/infra/nixpkgs/commit/28d8e938714a77af473a549e647e07573cc4b959
https://marc.info/?l=nix-commits&m=142316268901580&w=1

**Comment by ldesgoui** [comment]
Oh, steam-run works perfectly. Should I close the issue as my problem has been resolved?

**Comment by benley** [comment]
You could still add a derivation for steamcmd that invokes it using steam-run, if you're so inclined.  Otherwise yes, go ahead and close this issue.
