### ISSUE TITLE
Update request: fontmatrix 0.6.0-qt5 → 0.9.100

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#237150]
- Package name: fontmatrix
- Latest released version: 0.9.00

- Current version on the unstable channel: 0.6.0-qt5
- Current version on the stable/release channel: 0.6.0-qt5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@vbgl hi again :) You are listed as the person that last updated this.

-----

Note for maintainers: The QT5 port [is merged it seems](https://github.com/fontmatrix/fontmatrix/releases/tag/v0.9.100), but a version bump just led to a different insecure package in `qtwebkit-5.212.0-alpha4`. I can probably find time to look into this, but I’m unfamiliar with Qt & C++.

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/250964

**Comment by natsukium** [comment]
closed by #250964
