### ISSUE TITLE
albert is not working: no result for queries

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#23710]
## Issue description

Latest versions of [Albert](https://albertlauncher.github.io/) is not working as expected in NixOS. The latest one that works is version 0.8.11.

I have also opened an issue in albert's repository: https://github.com/albertlauncher/albert/issues/397

![albert](https://cloud.githubusercontent.com/assets/1217934/23799043/d76fed98-0585-11e7-8dc2-f885ff4f1e28.png)

### Steps to reproduce

Open albert (using a hotkey or from the system tray icon) and type a query in the input box. A list of applications should be shown so that the user could choose one to be executed. But no result is appearing.

[Albert's github page](https://github.com/albertlauncher/albert) has an animated image demonstrating how it would work.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
   `17.09pre102667.2839b10 (Hummingbird)`

* Nix version: (run `nix-env --version`)
   `nix-env (Nix) 1.11.7`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
   `"17.09pre102667.2839b10"`

**Comment by PierreR** [comment]
I have the same issue.

**Comment by PierreR** [comment]
@ericsagnes do you know of any trick that could be used in `default.nix` to get a 'wrapper' that would set the plugin path automatically ?

**Comment by ericsagnes** [comment]
Upstream is looking for plugins in hardcoded [paths](https://github.com/albertlauncher/albert/blob/1dc801973e1fb7b340f4948d1d6528ed22efd9b9/src/lib/albert/src/pluginsystem/extensionmanager.cpp#L53-L57).
This is indeed not working well in nix case as albert plugins are in the nix store.
A workaround could be to use `makeWrapper`/`wrapQtProgram` to automatically set the plugin path with `-p` as you pointed like:

```
wrapQtProgram $out/bin/albert --add-flags "-p $out/lib/albert/plugins/"
```

**Comment by PierreR** [comment]
@ericsagnes Thanks. I have just PR the suggested change. It works nicely.

**Comment by ericsagnes** [comment]
Nice! But be aware that this is more a workaround than a real fix, as using the `-p` flag with the PR version will override the one passed in `--add-flags` and shadow the default plugins.

Ideally, this should be adressed upstream by providing a more flexible way to point plugins like a dedicated environment variable.

**Comment by romildo** [comment]
It would be better to modify albert source code to add the plugins directory (in the store location for albert) in to the list of directories used to search plugins.

With the following snippet of code added to `default.nix`, albert works, without the need to use the `-p` command line option.

``` nix
  postPatch = ''
    sed -i "/QStringList dirs = {/a    \"$out/lib\"," \
      src/lib/albert/src/pluginsystem/extensionmanager.cpp
  '';
```
