### ISSUE TITLE
Booting takes longer and shows errors in NixOS 17.03

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#23729]
Ever since I upgraded to NixOS 17.03beta251.c0ecd31 (Gorilla) on my laptop, I'm getting these ACPI errors on boot:

```
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Needed [Buffer/String/Package], found [Integer] ffff96421e330dc8 (20160831/exresop-594)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [OpcodeName unavailable] (20160831/dswexec-461)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WVPO] (Node ffff96422089a668), AE_AML_OPERAND_TYPE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WMPV] (Node ffff96422089a6b8), AE_AML_OPERAND_TYPE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo audit: NETFILTER_CFG table=filter family=10 entries=24
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Needed [Buffer/String/Package], found [Integer] ffff9642165a7318 (20160831/exresop-594)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [OpcodeName unavailable] (20160831/dswexec-461)
mars 10 22:44:45 hp-elitebook-theo audit[632]: SYSCALL arch=c000003e syscall=54 success=yes exit=0 a0=4 a1=29 a2=40 a3=eae320 items=0 ppid=503 pid=632 auid=4294967295 uid=0 gid=0 euid=0 suid=
mars 10 22:44:45 hp-elitebook-theo audit: PROCTITLE proctitle=6970367461626C6573002D77002D4100494E505554002D6A006E69786F732D6677
mars 10 22:44:45 hp-elitebook-theo systemd[1]: Started Firewall.
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WVPO] (Node ffff96422089a668), AE_AML_OPERAND_TYPE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: 
mars 10 22:44:45 hp-elitebook-theo kernel: Method parse/execution failed 
mars 10 22:44:45 hp-elitebook-theo kernel: [\_SB.WMIV.WMPV] (Node ffff96422089a6b8)
mars 10 22:44:45 hp-elitebook-theo kernel: , AE_AML_OPERAND_TYPE
mars 10 22:44:45 hp-elitebook-theo kernel:  (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Needed [Buffer/String/Package], found [Integer] ffff9642165a75a0 (20160831/exresop-594)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [OpcodeName unavailable] (20160831/dswexec-461)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WVPO] (Node ffff96422089a668), AE_AML_OPERAND_TYPE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WMPV] (Node ffff96422089a6b8), AE_AML_OPERAND_TYPE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: input: HP WMI hotkeys as /devices/virtual/input/input13
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Attempt to CreateField of length zero (20160831/dsopcode-168)
mars 10 22:44:45 hp-elitebook-theo audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=firewall comm="systemd" exe="/nix/store/4mhj2swvnacffi9zyj54gd5ig343jwga-system
mars 10 22:44:45 hp-elitebook-theo systemd[1]: Started Network Time Synchronization.
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WVPI] (Node ffff96422089a618), AE_AML_OPERAND_VALUE (20160831/psparse-543)
mars 10 22:44:45 hp-elitebook-theo kernel: ACPI Error: Method parse/execution failed [\_SB.WMIV.WMPV] (Node ffff96422089a6b8), AE_AML_OPERAND_VALUE (20160831/psparse-543)
```

And then booting lags for a few seconds while showing `Started udev Wait for Complete Device Initialization.` In journalctl here are some lines around this message:

```
mars 10 22:45:00 hp-elitebook-theo kernel: mei_wdt mei::05b79a6f-4628-4d7f-899d-a91514cb32ab:02: Could not register event ret=-22
mars 10 22:45:00 hp-elitebook-theo kernel: mei_wdt: probe of mei::05b79a6f-4628-4d7f-899d-a91514cb32ab:02 failed with error -22
mars 10 22:45:00 hp-elitebook-theo systemd[1]: Started udev Wait for Complete Device Initialization.
```

One can observe a 15 seconds delay between these two points (although it seemed to me that it was a bit shorter in reality). My laptop has a full SSD drive and before the upgrade the whole booting took at most a few seconds.

I don't know if the two problems I'm reporting are linked to each other though.

**Comment by abbradar** [comment]
This seems like either an ACPI bug that was previously masked by something or a kernel regression. Possible steps:

1. Search your laptop model across the kernel bug tracker;
2. Update BIOS (often helps but check if you can rollback, just in case);
3. Try various `acpi_osi=` options. Warning, this can break other things in subtle ways (for example you may get rid of errors but backlight buttons stop working).

**Comment by Zimmi48** [comment]
Would you say then that the two problems I described are linked to each other?

> Search your laptop model across the kernel bug tracker

I found [this issue](https://bugzilla.kernel.org/show_bug.cgi?id=194671) where the error messages look kind of similar even if my problem is much less critical (it's just a slowdown at boot).

> Update BIOS (often helps but check if you can rollback, just in case)

I'm not really feeling confident enough to do that, and given that the laptop is barely three month old, it shouldn't be needed, should it?

> you may get rid of errors but backlight buttons stop working

Actually, I already had problems with backlight buttons (even before I switched to 17.03) that I fixed manually in [my configuration](https://github.com/Zimmi48/dotfiles/blob/master/hp-elitebook-theo.nix). This backlight button problem seems to be the one described [here](https://bugzilla.kernel.org/show_bug.cgi?id=60670) BTW.

**Comment by abbradar** [comment]
> Would you say that the two problems I described are linked to each other then?

Those problems could be separate; try to blacklist `mei_wdt` module.

> I'm not really feeling confident enough to do that, and given that the laptop is barely three month old, it shouldn't be needed, should it?

It may be the opposite, ACPIs are often very buggy and fixes come often -- this depends on the vendor and I don't know how good is HP in that field. Anyway let's skip it, can be dangerous after all.

> Actually, I already had problems with backlight buttons (even before I switched to 17.03) that I fixed manually in my configuration. This backlight button problem seems to be the one described here BTW.

It seems to have no connection with ACPI (and that's good :D).

**Comment by Zimmi48** [comment]
> Those problems could be separate; try to blacklist `mei_wdt` module.

Thanks! It solved only the `udev Wait for Complete Device Initialization` problem (which was the real annoying one). My laptop now boots again in a few seconds but I can see that the ACPI problems are still there when using `journalctl`. I can't claim that they weren't there before upgrading to 17.03 though because the booting is so fast.

What do I risk losing by keeping this kernel module blacklisted? And are these ACPI failures really a concern or should I close this issue now that my real problem is gone?

**Comment by fmthoma** [comment]
For the record, I experienced the same problem with `systemd-udev-settle` on my Thinkpad T460s, and it was also fixed by blacklisting the `mei_wdt` kernel module.

@Zimmi48 one request though: Could you somehow add »systemd-udev-settle« and/or »Started udev Wait for Complete Device Initialization« in the issue title, so this is easier to find? (Took me several hours of googling and trying to mask `systemd-udev-settle`, until I found this).

**Comment by Zimmi48** [comment]
@fmthoma Done! Sorry that my lack of a better title made you lose a few hours. I will try to keep this in mind when opening issues in the future.

**Comment by fmthoma** [comment]
@Zimmi48 Thanks, let's hope this helps other people as well! Not a problem for me, I could have searched the NixOS issues more thoroughly before resorting to ArchWiki and others ;-)
