### ISSUE TITLE
Update request: electrum 4.4.0 → 4.4.4

### ISSUE THREAD

**Issue by jonnyniv** [NixOS/nixpkgs#237219]
- Package name: electrum
- Latest released version: 4.4.4

- Current version on the unstable channel: 4.4.0
- Current version on the stable/release channel: 4.4.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@prusnak

-----

Note for maintainers: Please tag this issue in your PR.

Reporters Note:
Tried the update locally and got the error 
```substituteStream(): WARNING: pattern 'libsecp256k1.so.0' doesn't match anything in file './electrum/ecc_fast.py'```

Looking at the diff on the electrum github I see the substituteInPlace pattern will no longer match:
 https://github.com/spesmilo/electrum/compare/4.4.0...4.4.4#diff-7c7d9d552278eadc4c993a183c23fd0b983f5b0dbc4e6320c04f54ac41c572bc
In: `electrum/ecc_fast.py`

**Comment by prusnak** [comment]
PR in https://github.com/NixOS/nixpkgs/pull/237247
