### ISSUE TITLE
nixos unstable will not build firefox or firefox-esr

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#23720]
## Issue description
checking for nss-config... /nix/store/mjbccpz6whnaj54z8dmzv055r0w97y8b-nss-3.28.1-dev/bin/nss-config
checking for NSS - version >= 3.28.3... no
configure: error: you don't have NSS installed or your version is too old
DEBUG: <truncated - see config.log for full output>
DEBUG: #include <malloc.h>
DEBUG:                   #include <stddef.h>
DEBUG:                   size_t malloc_usable_size(const void *ptr);
DEBUG: int main() {
DEBUG: return malloc_usable_size(0);
DEBUG: ; return 0; }
DEBUG: configure:9923: checking for valloc in malloc.h
DEBUG: configure:9948: checking for valloc in unistd.h
DEBUG: configure:10103: checking NSPR selection
DEBUG: configure:10203: checking for nspr-config
DEBUG: configure:10238: checking for NSPR - version >= 4.13.1
DEBUG: configure:10314: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10333: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10381: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10420: checking for libevent
DEBUG: configure:10427: checking MOZ_LIBEVENT_CFLAGS
DEBUG: configure:10432: checking MOZ_LIBEVENT_LIBS
DEBUG: configure:10605: checking for nss-config
DEBUG: configure:10640: checking for NSS - version >= 3.28.3
DEBUG: configure: error: you don't have NSS installed or your version is too old
ERROR: old-configure failed
builder for ‘/nix/store/yag51knblmw3zlydgrxy1rhg4qp8lh5h-firefox-esr-unwrapped-52.0esr.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dyfp6l09n7215p684xvxv7pjs90qf89c-firefox-52.0esr.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/444f6d621mg1fprgkg0chw4dxcjsd71y-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/c6d6aprdj1bqbmvkffc8fqk8qfsc70v6-nixos-system-toadman-17.09pre102933.26625c9.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c6d6aprdj1bqbmvkffc8fqk8qfsc70v6-nixos-system-toadman-17.09pre102933.26625c9.drv’ failed

### Steps to reproduce
add firefox to package list in your nix
then nixos-rebuild switch

## Technical details
17.09pre102933.26625c9 (Hummingbird)
nix-env (Nix) 1.11.7
"17.09pre102933.26625c9"

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by bendlas** [comment]
I've been seeing those build failures too. Investigating recent firefox updates ...

**Comment by joachifm** [comment]
See https://github.com/NixOS/nixpkgs/commit/32bcda741a9f58d376ad1f1de0b051571cddc3d2

**Comment by vcunat** [comment]
The firefox tests [segfault now](http://hydra.nixos.org/build/50004395), on both x86 platforms, so the channel would not update.  I haven't heard of real-life problems with the updated firefox, though.

**Comment by clacke** [comment]
If tests block the channel, how could FF 52 get into the channel when it wouldn't even build?

Were the segfaults related to #23857 ?

Anyway, seems fixed now. Latest channel update has nss 3.28.3 and updated icu and sqlite, and FF is available from hydra.

**Comment by vcunat** [comment]
I'm not sure how this happened.  Maybe it was some misunderstanding.  I certainly agree to close.
