### ISSUE TITLE
texlive.combine: package 'combine' from CTAN not usable

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#237227]
The attribute `texlive.combine` masks the package `combine` from TeX Live, which is thus not accessible for normal use. In the future, TeX Live could at any time ship `bin`, `combined`, `tlpdb`, which would also be masked by the current `texlive` implementation.

If anybody can think of a clever, non-breaking fix for 23.05...

For 23.11, I am working on a new interface (like `texlive.withPackages`, or `texlive.scheme-*.withPackages`, or something else of the sort) and since it would be a breaking change, we will be free to resolve the issue properly by e.g. moving the packages under `texlive.packages`.

### Steps To Reproduce
According to the docs, to get the `combine` package, one should use
```nix
texlive.combine {
  inherit (texlive) scheme-infraonly combine;
}
```
which does not work as intended, because `texlive.combine` is not a TeX Live package but a special Nixpkgs builder.

Edit: let me add that the package `combine` can still be used by adding `collection-latexextra`, since the dependencies are created while building the `tl` attrset, well away from the final `texlive` attrset. Brave users can even fish `combine` out of `collection-latexextra`.

### Notify maintainers
@veprbl
Cc @apfelkuchen6

**Comment by apfelkuchen6** [comment]
Some work for this has been done in #120578.

**Comment by xworld21** [comment]
This now works using with `texliveSmall.withPackages`.
