### ISSUE TITLE
Package request: Clipboard

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#237200]
**Project description**

Clipboard is a tool to manage your os clipboard. You can save filles as well as text.

**Metadata**

* homepage URL: https://github.com/Slackadays/Clipboard
* source URL: https://github.com/Slackadays/Clipboard
* license: agpl3Only
* platforms: unix

I'm happy to help maintain it.
I tried building it but I'm getting some weird cmake errors that I understand nothing about.
```
 CMake Error at /nix/store/ysiy2fyxlj0q9cm73946zj0dghp72jxp-cmake-3.25.3/share/cmake-3.25/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile):
       >   Failed to configure test project build system.
       > Call Stack (most recent call first):
       >   /nix/store/ysiy2fyxlj0q9cm73946zj0dghp72jxp-cmake-3.25.3/share/cmake-3.25/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
       >   CMakeLists.txt:6 (project)
       >
       >
       > -- Configuring incomplete, errors occurred!
```

I anyone has more knownledge on CMakeList.txt, I'd be happy to help maintain the package.

**Comment by Aleksanaa** [comment]
It's already in [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=clipboard-jh&from=0&size=50&sort=relevance&type=packages&query=clipboard-jh), although not the latest version. You can update it if you need it.

**Comment by happysalada** [comment]
my bad for not finding it! Thanks for your help!
