### ISSUE TITLE
Package request: govulncheck-db

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#237338]
**Project description**

The database used by govulncheck. https://go.dev/security/vuln/database

**Reason**

govulncheck by default downloads the db during runtime. This behaviour makes it impossible to run govulncheck as part of a flake check (since flake checks are network sandboxed). It would be great if the db would be packed in nixpkgs so one could use the -db flag of govulncheck to pass the path to a local db (that could be used inside a flake check).
Since this is more or less static data (but should be kept as up-to-date as possible), it would be best if this wasn't manually updated from time to time but automated by some bot or github action or whatever.

@jk @SuperSandro2000 since you are the maintainers of govulncheck

**Metadata**

* homepage URL: https://vuln.go.dev/
* source URL: https://vuln.go.dev/index/*.json
* license: ?
* platforms: all

**Comment by SuperSandro2000** [comment]
> Since this is more or less static data

No, it isn't. If the db is not updated you will not receive new advisories and constantly bumping the db in nixpkgs creates an unreasonable amount of noise. Also backporting the bumps to stable creates more work.

If you want to run the check in flake check I would recommend to download the db yourself or you run the checks in a none sandboxed environment.
