### ISSUE TITLE
catppuccin-kde does not install any files

### ISSUE THREAD

**Issue by NotAShelf** [NixOS/nixpkgs#237360]
### Describe the bug
The package `catppuccin-kde` is installed with empty files.

### Steps To Reproduce
1. `nix build nixpkgs#catppuccin-kde`
2. `cd` to the result/ directory
3. Open any file
The files will be empty

### Expected behavior
The files are populated according to their original source.

### Additional context
Likely a result of running an install script.

### Notify maintainers

@michaelBelsanti 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"                    
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5-xanmod1, NixOS, 23.11 (Tapir), 23.11.20230611.75a5ebf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.17.0pre20230604_518ce77`
 - nixpkgs: `/nix/store/3lv5x5bn3bvy0xmd35ds3dsmvk23591w-source`
```

**Comment by michaelBelsanti** [comment]
Thank you for bringing it to my attention. It was broken by #228274, an auto update that I missed the noti for.
