### ISSUE TITLE
Nonfree package "infra" (Elastic License)

### ISSUE THREAD

**Issue by nemobis** [NixOS/nixpkgs#237376]
### Describe the bug
The "infra" package is nonfree.

### Steps To Reproduce
1. https://github.com/NixOS/nixpkgs/blob/release-23.05/pkgs/tools/admin/infra/default.nix
2. https://github.com/infrahq/infra/blob/v0.21.0/LICENSE

### Expected behavior
The package should only contain free software.

### Additional context

The "infrahq/infra" repository uses the infamous nonfree license "Elastic License" since [April 2022](https://github.com/infrahq/infra/commit/676b37ca2f2712c51508a5369bfe16f436297f56). The nixpkg incorrectly states that it's under MIT license. The package needs to be removed, reverted to the [last known free version](https://github.com/infrahq/infra/releases/tag/v0.10.0) or manually cleansed from nonfree code (via a fork?).

### Notify maintainers

@peterromfeldhk @pdevine

**Comment by figsoda** [comment]
#237405

**Comment by nemobis** [comment]
A bit funny that this proprietary software was kept but https://github.com/NixOS/nixpkgs/issues/260848 was completely removed.
