### ISSUE TITLE
Build failure: python 3.10 - anyio 3.6.2

### ISSUE THREAD

**Issue by ManoftheSea** [NixOS/nixpkgs#237398]
### Steps To Reproduce

1. build `netbox` from amd64 for an arm64 host

### Build log

```
test_run_in_custom_limiter[asyncio]
...
test_run_in_custom_limiter[asyncio+uvloop]
tests/test_to_thread.py:82: in test_run_in_custom_limiter
    assert num_active_threads == 3
E   assert 2 == 3
```

### Additional context

error: builder for '/nix/store/2b0xf4i0nrcfzcqr4js4zjybblj9sb95-python3.10-hpack-4.0.0.drv' failed with exit code 1
error: builder for '/nix/store/mfmlrsh0rihsfmxhclc7ifgdaihygi0k-python3.10-s3transfer-0.6.0.drv' failed with exit code 1;

Should I report these separately or in this thread?

### Notify maintainers

I'm not sure who to tag for Python packages

### Metadata

```
• Updated input 'nixos':
    'github:nixos/nixpkgs/85bcb95aa83be667e562e781e9d186c57a07d757' (2023-06-09)
  → 'github:nixos/nixpkgs/d3bb401dcfc5a46ce51cdfb5762e70cc75d082d2' (2023-06-10)
```

**Comment by figsoda** [comment]
> I'm not sure who to tag for Python packages

You can find the maintainers here

https://github.com/NixOS/nixpkgs/blob/443629518cf00ca7cedc7e357ac8027e7c40f150/pkgs/development/python-modules/anyio/default.nix#L106

**Comment by ManoftheSea** [comment]
Additional context:
Lily helped me discover that I have "environment.noXlibs = true;" which causes an overlay for python.  

When this is set to false, the system is able to build from the cache.  So, should I close my error report, or is it still of use to fix?

github.com/ManoftheSea/SeaofDirac commit 1d2c209e5c1073ca352b631d7213093db7fa08a6 is the failing configuration.

**Comment by mweinelt** [comment]
Sorry, apparently I missed this and now it is obsolete.
