### ISSUE TITLE
Package request: kbin

### ISSUE THREAD

**Issue by NULLx76** [NixOS/nixpkgs#237307]
**Project description**

kbin is an open source reddit-like content aggregator and microblogging platform for the [fediverse](https://en.wikipedia.org/wiki/Fediverse) it is an alternative to software like lemmy, but does interoperate with it and other ActivityPub software.

**Metadata**

* homepage URL: https://kbin.pub/en
* source URL: https://git.kbin.pub/
* license: agpl v3
* platforms: linux

**Comment by pbsds** [comment]
Will likely have to wait until #225401 is merged

**Comment by lorenzleutgeb** [comment]
In reply to @pbsds:

> Will likely have to wait until #225401 is merged

It seems that the `php.buildComposerProject` has landed via https://github.com/NixOS/nixpkgs/pull/248184

**Comment by pbsds** [comment]
Would love to have a crack at it, but I'll be busy until friday next week

**Comment by drupol** [comment]
I guess a NixOS module will be mandatory here since `kbin` is an application. Right?

Packaging it is the easiest part now, I believe... but I'm curious to see how you're going to do with that request.

**Comment by lorenzleutgeb** [comment]
@andres-nav @augustebaum @imincik @kubaneko and me started working on this, see https://github.com/ngi-nix/ngipkgs/compare/mob/algae-kbin

**Comment by drupol** [comment]
Excellent, looking forward to see the outcome!

**Comment by Ultra980** [comment]
Any progress on this?

**Comment by lorenzleutgeb** [comment]
https://github.com/ngi-nix/ngipkgs/pull/98

**Comment by drupol** [comment]
I've got some questions about the `ngipkgs` repo. What's the deal with contributing to it? Wouldn't it make more sense to eventually merge stuff into `NixOS/nixpkgs`? That way, we're really getting our money's worth from the public funds the European Commission puts in. Why keep them separate?

**Comment by augustebaum** [comment]
> I've got some questions about the `ngipkgs` repo. What's the deal with contributing to it?

From what I gather, there are at least 2 reasons:
- It functions as a central place that can be pointed at for the NGI funders to see  the result of their funding efforts (we also mention the nixpkgs PRs in that repo)
- It allows for more experimental packaging than nixpkgs, which make Summer of Nix teams more efficient in their 3 months part-time work.

@fricklerhandwerk will be able to make this answer more precise :)

**Comment by drupol** [comment]
Thank you for explaining on the motivations behind maintaining the `ngipkgs` repository separately from the main `nixpkgs` repo. I definitly appreciate the efforts to showcase the outcomes of NGI funding and the need for a space to experiment with more experimental packages that might not yet be ready for the broader `nixpkgs` community. These points do clarify the rationale behind the current setup. Fine.

However, I'd like to express a concern from a broader community and public funding effectiveness perspective. The core of my concern revolves around the visibility and accessibility of the work funded by funders. If contributions remain within the `ngipkgs` repository without a clear path or intention for integration into the main `nixpkgs`, are we not limiting the impact and reach of these publicly funded contributions? My worry is that such a strategy may inadvertently keep valuable developments from a vast majority of the NixOS community, who might benefit significantly from these efforts but are not aware of or do not engage with the `ngipkgs` repository.

Thinking about it further, wouldn’t it make a lot of sense to have a clear plan for moving the good stuff from `ngipkgs` over to `nixpkgs`? This way, we’d make sure that the cool projects we’re putting public money into are getting seen and used by as many people as possible. Plus, it’s kind of what open source is all about, right? Sharing and improving together. If we had a straightforward way to get these contributions into `nixpkgs`, it’d mean that everyone in the NixOS community could benefit, which is the whole point of funding this stuff in the first place.

Last thing, it’s super important that when we bring new folks in through initiatives like "Summer of Nix" we really dive into how to contribute back to `nixpkgs` effectively. We’ve got this great opportunity to mentor and guide new contributors, helping them understand not just the how, but the why of contributing back to the main repository. This way, we’re not just growing the number of contributions, but also fostering a community that’s savvy about where and how their efforts can make the biggest impact.

**Comment by fricklerhandwerk** [comment]
@augustebaum yes that's correct. @drupol fully agreed; in practice we have to take into account even more constraints than just velocity, such as who's going to maintain any given piece of code. Ideally we'd want project authors or their communities to do that, but we can't and don't want to force everyone into the Nixpkgs community, on which a portion of the effort would also fall inevitably. In the next months we'll clarify the processes and see how to reduce the friction for making things accessible (and transferring responsibility if needed).
