### ISSUE TITLE
Discussion: libcryptui

### ISSUE THREAD

**Issue by butterflya** [NixOS/nixpkgs#23752]
libcryptui is an optional dependency of `evolution`. 

https://github.com/GNOME/libcryptui states it's likely to be deprecated, but meanwhile the last commit was as recent as yesterday, which seems to suggest only libcryptui2 is to be deprecated and not libcryptui3.

As long as Evolution uses the library, we could just ignore such remarks. What do you think?

**Comment by AndersonTorres** [comment]
The update is just in the Lithuan translation.

**Comment by jtojnar** [comment]
It is mostly in maintenance mode with intent to deprecate it in the future. However, there is not a replacement yet so projects like Evolution and Almanah still depend on it. I packaged it together with Almanah in https://github.com/NixOS/nixpkgs/pull/57001

**Comment by jtojnar** [comment]
Do we want to add it to Evolution dependencies?

**Comment by maxeaubrey** [comment]
3561cddb357e780b79ab97d69e55b4712b70c705
