### ISSUE TITLE
runCommand derivations have incorrect meta.position

### ISSUE THREAD

**Issue by Dioprz** [NixOS/nixpkgs#237589]
Hello

I was trying to review just now the source code that 'rstudioWrapper' uses. When I hit source from nixos-search I was redirected to this link

[https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/build-support/trivial-builders/default.nix](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/build-support/trivial-builders/default.nix)

However after checking in [all-packages.nix](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/top-level/all-packages.nix), I noticed that the expression that runs 'rstudioWrapper' is this one

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/r-modules/wrapper-rstudio.nix

I'm not sure why this is happening, nor if the report should be here or in nixpkgs. In case I made a mistake, I would appreciate if you let me know so I can open another report.

Thank you very much for nixos-search, I can't imagine the Nix experience without this amazing search engine.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/237594

**Comment by Dioprz** [comment]
Oh, that was fast. Thanks for your help! I stay tuned if I can/should do anything.

**Comment by Dioprz** [comment]
@ncfavier Hello again!

I'm just seeing that your PR has already been merged. Do you agree if we close this issue, or is there anything left? nix-search unstable already perfectly references rStudioWrapper! Thank you very much for your help.

**Comment by ncfavier** [comment]
This is probably not completely solved yet (uses of `runCommand` without arguments would still have incorrect position information) but there's nothing actionable left to do so we might as well close it.
