### ISSUE TITLE
libCPR 

### ISSUE THREAD

**Issue by rmrfallcode** [NixOS/nixpkgs#237554]
when adding libcpr as a dependenc in replit.nix file, or command `nix-shell -p libcpr` is run, error `error: undefined variable 'libcpr'` at (string):1:94 is thrown, and the installation fails

steps to reproduce
1) create a new replit.com progect 
2a) add libcpr to replit.nix under packages 
or
2b)run`nix-shell -p libcpr`

**Comment by FliegendeWurst** [comment]
`nix-shell -p libcpr` works for me.
