### ISSUE TITLE
Xdg-open does not work in steam-run

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#237581]
### Describe the bug
Xdg-open does not work in steam-run, meaning that if an app tries to open a link, it will just fail. It is quite an issue, for instance some programs need to send a link to work…

### Steps To Reproduce
```
$ steam-run bash
$ xdg-open https://test.com
```

this is true even with
```
  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
  };

```

### Expected behavior
I expect this to open in, e.g., firefox.

## System

I’m running on 2caf4ef5005ecc68141ecb4aac271079f7371c44

### Notify maintainers

@LunNova  : I have no idea who I should notify, but I saw that you worked on this related PR that is certainly related https://github.com/NixOS/nixpkgs/issues/160923

**Comment by LunNova** [comment]
Unfortunately works on my machine under steam-run, on nixos-unstable with xdgOpenUsePortal enabled which isn't useful for debugging.

I'm not seeing the `(objectpath '/org/freedesktop/portal/desktop/request/1_1853/t',)` output that typically shows up when that is in use.

Is `$NIXOS_XDG_OPEN_USE_PORTAL` set in that shell as expected? Is your steam-run also from a recent nixpkgs?

**Comment by lilyinstarlight** [comment]
Does `xdg-open https://nixos.org/` work from a terminal or no?

Also if you run `dbus-update-activation-environment --systemd --all` from a terminal and try again does it work?

It's possibly an issue with the graphical session's environment variables not getting importing into the systemd user scope

**Comment by kirillrdy** [comment]
@tobiasBora does this help to fix the issue  ? https://github.com/NixOS/nixpkgs/issues/237581

it fixes the issue I've discovered

```
xdg-open https://test.com

[kirillvr@tsutenkaku:~/nixpkgs]$ XPCOMGlueLoad error for file /nix/store/vly249ilmirndhn2n69lixpl410b1d8b-firefox-114.0.2/lib/firefox/libxul.so:
/lib64/libssl3.so: version `NSS_3.80' not found (required by /nix/store/vly249ilmirndhn2n69lixpl410b1d8b-firefox-114.0.2/lib/firefox/libxul.so)
Couldn't load XPCOM.

```

**Comment by tobiasBora** [comment]
So it seems like a reboot fixed the problem, but somehow we need to enable it by default and tell the user to reboot. Also, another bug in xdgOpenUsePortal made me unable to open images in dolphin, but seems like this has been solved on master so I need to upgrade my system.

**Comment by kirillrdy** [comment]
@tobiasBora is this still an issue ?

**Comment by kirillrdy** [comment]
feel free to reopen if still an issue
