### ISSUE TITLE
emacsWithPackagesFromUsePackage fails at build time

### ISSUE THREAD

**Issue by jkozak** [NixOS/nixpkgs#237559]
### Steps To Reproduce
1.  a `configuration.nix` containing something like this
```nix
let
  myEmacs = pkgs.emacsWithPackagesFromUsePackage {
    config = ./init.el;     # this can be empty
    package = pkgs.emacs-unstable;
    alwaysEnsure = true;
  };
  # ...
```
2.  run `nixos-rebuild build --upgrade`
3. fails so
```console
unpacking channels...
building Nix...
building the system configuration...
error: anonymous function at /nix/store/ca2dnwrp8hya3j29hk0m9c7prwpg7fl9-nixos-22.11/nixos/pkgs/top-level/emacs-packages.nix:58:53 called with unexpected argument 'elpaDevelPackages'

       at /nix/store/ca2dnwrp8hya3j29hk0m9c7prwpg7fl9-nixos-22.11/nixos/lib/customisation.nix:72:16:

           71|     let
           72|       result = f origArgs;
             |                ^
           73|
(use '--show-trace' to show detailed location information)
```

### Expected behavior
successful build!

### Other context

This worked fine until a couple of days ago.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.110, NixOS, 22.11 (Raccoon), 22.11.4091.a08e061a4ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(jk): `""`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by leungbk** [comment]
> error: anonymous function at /nix/store/ca2dnwrp8hya3j29hk0m9c7prwpg7fl9-nixos-22.11/nixos/pkgs/top-level/emacs-packages.nix:58:53 called with unexpected argument 'elpaDevelPackages'

`22.11` is deprecated, so newer versions of the `emacs-overlay` will not work. You should either update to `23.05` or stick to an older revision of the overlay.

BTW `emacsWithPackagesFromUsePackage` is specific to the overlay, and does not exist in upstream nixpkgs.

**Comment by leungbk** [comment]
If you need to stick to `22.11` and simultaneously use a newer revision of the overlay, you can alternatively wait till https://github.com/NixOS/nixpkgs/pull/237675 makes it way into the `22.11` channel.
