### ISSUE TITLE
Update request: realesrgan-ncnn-vulkan 0.1.3.2 → 0.2.0

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#237603]
- Package name: realesrgan-ncnn-vulkan
- Latest released version: 0.2.0

- Current version on the unstable channel: 0.1.3.2
- Current version on the stable/release channel: 0.1.3.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@TilCreator

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by iynaix** [comment]
Fixed by #264727
