### ISSUE TITLE
Build failure: batctl for riscv64

### ISSUE THREAD

**Issue by codehub8** [NixOS/nixpkgs#237690]
### Steps To Reproduce
Failed to cross compile batctl package for riscv64 using nixpkgs on **Ubuntu**.  Nix is not able to meat the dependency for the package:

`Makefile:116: *** No libnl-3.0 development libraries found!.  Stop.`

While the package successfully cross compiles on a **NixOS** machine. 

1. Install nix environment on a Ubuntu machine. and cross compile batctl package for riscv64. Below is the command I am using:
`   nix-build '<nixpkgs>' -A pkgsCross.riscv64.batctl`

### Build log

attached

### Metadata

nix-info not availble on Ubuntu

[log.txt.txt](https://github.com/NixOS/nixpkgs/files/11742539/log.txt.txt)

**Comment by MaxHearnden** [comment]
can you give the version of nix and the revision of nixpkgs (it might be in a file called .git-revision).

**Comment by Artturin** [comment]
> nixpkgs on Ubuntu

is the sandbox enabled

**Comment by MaxHearnden** [comment]
Turns out I couldn't reproduce it because my machine has riscv emulation enabled, the makefile is calling a riscv version of pkg-config. I'm testing a fix to the problem at the moment
