### ISSUE TITLE
Package request: linux-wallpaperengine

### ISSUE THREAD

**Issue by hagenest** [NixOS/nixpkgs#237762]
**Project description**

linux-wallpaperengine aims to reproduce the background functionality of Wallpaper Engine on Linux systems. There already is a wallpaper-engine implementation packaged, but it only works on KDE, while this project should work with most Wayland-compositors and window-managers.

**Metadata**

* homepage URL: https://github.com/Almamu/linux-wallpaperengine
* source URL: https://github.com/Almamu/linux-wallpaperengine
* license: gpl3
* platforms: linux

---

I tried to package it myself, but the "just compare with other packages" approach of the nixpkgs documentation was very confusing to me. If someone can point me to other documentation or anything helpful I'd be happy to try it again.

**Comment by I-Want-ToBelieve** [comment]
https://github.com/NixOS/nixpkgs/pull/188136/files

**Comment by eclairevoyant** [comment]
> this project should work with most Wayland-compositors and window-managers.

Sort of, it still runs under X fyi

> I tried to package it myself, but the "just compare with other packages" approach of the nixpkgs documentation was very confusing to me.

My rough process:
* check the repo of whatever you're packaging to see what language and tooling it uses
* read the nixpkgs manual for the language and tooling that you're building with
* find examples of other expressions in nixpkgs that use the same tooling to get an idea of the structure
* use something like `nix-init` to generate the boilerplate for the expression
* `nix-build`, get an error, use `nix-locate` to find the required dependency (repeat this step until there are no more build errors)
* submit PR
