### ISSUE TITLE
NixOS: systemd couldn't unmount NFS mount

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#2377]
I just tried to reboot my machine and systemd became stuck trying to unmount an NFS mount (or at least, it was taking much longer than it should).

It seems that the NetworkManager service was stopped before the filesystem was unmounted. Since it was a network filesystem, probably it was trying but was unable to communicate with the server.

I'm guessing this could potentially cause data loss if there was unwritten data still sitting in the client's buffers...

**Comment by Profpatsch** [comment]
(triage) has this been fixed?

If not, can you provide more info?

**Comment by wizeman** [comment]
I haven't seen this problem in a long time, so I guess it can be closed :)

**Comment by Profpatsch** [comment]
cc @lethalman

**Comment by aragnon** [comment]
I found a problem related to this; NixOS is not pure w.r.t. the current working directory. That is, the directory in which the nixos-rebuild command is being executed in, has an influence on the semantics of nixos-rebuild, which IMHO, should not happen. (For example when umounting that directory.) 

In the scripts I write myself, I usually change directory to /tmp before doing anything; I'd expect nixos-rebuild to also do that internally.

**Comment by Profpatsch** [comment]
@aragnon Is that related to NFS? Maybe you can open another issue with a demonstration?

**Comment by Profpatsch** [comment]
close @zimbatm

**Comment by aragnon** [comment]
@Profpatsch No, the same issue would likely also be the case if one would try to umount any file system which is currently in use by merely being inside a directory on that file system. This behaviour exists on every Linux system I know. I don't think it belongs in NixOS, because it breaks an abstraction.

**Comment by zimbatm** [comment]
Systemd is going to kill all those processes before unmounting so that's not going to be an issue here. If you can reproduce the issue of systemd not unmounting during shutdown I will re-open the issue.
