### ISSUE TITLE
Lemmy 0.17.4 is out and update.sh is malfunctioning

### ISSUE THREAD

**Issue by matejc** [NixOS/nixpkgs#237717]
### Describe the bug

Lemmy update.sh produces:

```
❯  cat pin.json
{
  "version": "0.17.4",
  "serverSha256": "sha256-lF5/Y8VAM0NGJDKcfvKQWRg4zQ2gCvNhVQLNmuUjdg8=",
  "serverCargoSha256": "      . 205052 exec nix-build -A lemmy-server",
  "uiSha256": "sha256-g72EQOYHtBZ3vCu8aSmoPILuOJ8yiC4W7nDOtmFqK0o=",
  "uiYarnDepsSha256": "      . 205057 exec nix-build -A lemmy-ui"
}
```
Please see the entries: serverCargoSha256 and uiYarnDepsSha256

### Steps To Reproduce
1. cd to .../nixpkgs/pkgs/servers/web-apps/lemmy
2. run ./update.sh and it does succeed (exits with 0)

### Expected behavior
To fill pin.json with hash values.

### Notify maintainers

@happysalada @billewanick 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.11 (Tapir), 23.11.20230609.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/matejc/workarea/nixpkgs`
```

**Comment by happysalada** [comment]
can you try 
```
nix-shell -p oil
oil --version
```
I've just run the script on darwin on the latest unstable, and it runs fine
https://github.com/NixOS/nixpkgs/pull/237740
I'm thinking this could be an oil version problem. If it is, I can think of something.

**Comment by matejc** [comment]
```
❯  oil --version
OSH version 0.15.0
Release Date: 2023-05-03 19:03:21+00:00
Arch: x86_64
OS: Linux
Platform: #1-NixOS SMP PREEMPT_DYNAMIC Tue May 30 13:17:29 UTC 2023
Compiler: GCC 12.3.0
Interpreter: OVM
Interpreter version: 2.7.13
Bytecode: bytecode-opy.zip
```

**Comment by matejc** [comment]
The part that is not working is that `nix-build -A lemmy-server` fails, and it does that because its looking for `default.nix` in the `nixpkgs/pkgs/servers/web-apps/lemmy` since I am running it from there.

The workaround is to change directory to root of `nixpkgs` directory and run like so: `./pkgs/servers/web-apps/lemmy/update.sh`
This works because `nixpkgs` dir has `default.nix` and it has an attribute `lemmy-server`
