### ISSUE TITLE
[17.03] DBus activation fails for user installed packages

### ISSUE THREAD

**Issue by rycee** [NixOS/nixpkgs#23770]
## Issue description

I just tried updating my laptop from 16.09 to 17.03-beta and ran into the following issue when starting gnome-terminal:
```
$ gnome-terminal

** (gnome-terminal:4652): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Error creating terminal: The name org.gnome.Terminal was not provided by any .service file
```
I have gnome-terminal installed in my user profile and `~/.nix-profile/share/dbus-1/services/org.gnome.Terminal.service` exists.

I believe I have managed to narrow my problem to the removal of `<standard_session_servicedirs/>` from the DBus session configuration file, see #22864. Adding this XML tag back to the file made gnome-terminal start up fine.

### Steps to reproduce

As a user install and run gnome-terminal. Presumably a similar error will occur for any program relying on DBus activation.

```
$ nix-env -f '<nixpkgs>' -iA gnome3.gnome_terminal
…
$ gnome-terminal 

** (gnome-terminal:5357): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Error creating terminal: The name org.gnome.Terminal was not provided by any .service files
```

## Technical details

* System: 17.03beta320.ade5837 (Gorilla)
* Nix version: nix-env (Nix) 1.11.7

**Comment by abbradar** [comment]
Sigh, DBus is tricky. I didn't know that `standard_session_servicedirs` includes XDG directories and removed it to increase purity. Sorry for that, fixed it and leaved a comment for others.

**Comment by rycee** [comment]
Thank you @abbradar. You really improved the dbus stuff and I understand the thinking behind removing standard_session_servicedirs. But yeah, unfortunately it also affected the user installed services.
