### ISSUE TITLE
Virtualbox crashes when opening file selection dialog

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#23785]
## Issue description

Virtualbox crashes when calling any file selection dialog.
But the error disappears when virtualbox is executed by root (`sudo VirtualBox`)

### Steps to reproduce

> Run VirtualBox on cmdline
> Create a machine the regular way
> In the menu, Settings > Storage, try to insert a disk or DVD image (calling the dialog)
> Voilà, crash!

Terminal output:

> 
> ** (VirtualBox:14517): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> Qt WARNING: libpng warning: iCCP: known incorrect sRGB profile
> 
> (VirtualBox:14517): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
> Trace/breakpoint trap
> 

Opinion: I think the error is related to the last line, GLib-GIO-ERROR. There are some other apps with the same behaviour, as Emacs (related in #23160).

## Technical details

* System: NixOS 17.09pre102667.2839b10 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: coincides with the system one

**Comment by dezgeg** [comment]
It sounds like #23770 is the root cause.

**Comment by AndersonTorres** [comment]
@dezgeg it also fixes the same problem in Emacs #23160 ?

**Comment by abbradar** [comment]
I think it's because of https://github.com/NixOS/nixpkgs/issues/23474 -- Qt 5 uses GTK3's file dialogs now, so it needs `gsettings_desktop_schemas`. Let's close this as duplicate?

**Comment by AndersonTorres** [comment]
I will test, and then we can close it 👍 :)

**Comment by abbradar** [comment]
#23474 is not yet fixed so there's noting to test :P I'm working on it.

**Comment by AndersonTorres** [comment]
OK, then. I only added gsettings to virtualbox.
So I will close as duplicate.
