### ISSUE TITLE
Update request: rstudio-server 2022.07.1+554 → 2023.06.0+421

### ISSUE THREAD

**Issue by lkupcsik** [NixOS/nixpkgs#237878]
- Package name: rstudio-server
- Latest released version: 2023.06.0+421

- Current version on the unstable channel: 2022.07.1+554
- Current version on the stable/release channel: 2022.07.1+554

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cfhammill @ciil 

Warning message:
R graphics engine version 16 is not supported by this version of RStudio. The **Plots tab will be disabled** until a newer version of RStudio is installed. 

And the Plots tab is disabled indeed. It prints to pdf by default. Quarto requires newer version also.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by hervyqa** [comment]
Yes, I also need the latest versions of R, rstudio and quarto. There is a bug in the visual preview [#8989](https://github.com/NixOS/nixpkgs/issues/210826) that bothers me.
