### ISSUE TITLE
Kubeswitch pkg missing the script that makes it work

### ISSUE THREAD

**Issue by e-minguez** [NixOS/nixpkgs#237886]
### Describe the bug
Kubeswitch requires both the binary and a script https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md#switch-command

### Steps To Reproduce
1. Install kubeswitch
2. Try to use `switch`

### Expected behavior
Kubeconfig is set as intended

### Additional context
https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/tools/kubeswitch/default.nix only adds the binary, not the script itself.

On the other hand, I'm not using nix directly but via fleek.

### Notify maintainers
@bryanasdev000

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/fqjg9y9pwh9cg2izs76kkv0wwwpsqp1v-source`
```

**Comment by bryanasdev000** [comment]
Hey @e-minguez, happy first issue!

About the kubeswitch, indeed, I did make this mistake as I am using it on my work machine which is not NixOS and I had done the standard installation in the past, so I got the binary from Nix, but not the script.

Honestly, I need time and a little bit of searching on how to handle scripts, as I have only messed with Go or Python packages (which have a nice interface, BTW).

**Comment by sandangel** [comment]
```nix
      flake.overlays.default = final: prev: with prev; {
        kubeswitch = kubeswitch.overrideAttrs (o: rec {
          postInstall = ''
            mv $out/bin/main $out/bin/switcher
          '';
        });
      };
```

This will help fix it.

**Comment by bryanasdev000** [comment]
> ```nix
>       flake.overlays.default = final: prev: with prev; {
>         kubeswitch = kubeswitch.overrideAttrs (o: rec {
>           postInstall = ''
>             mv $out/bin/main $out/bin/switcher
>           '';
>         });
>       };
> ```
> 
> This will help fix it.

I did not test, but thanks.

@sandangel are you willing to do fix it?

**Comment by sandangel** [comment]
Hi, sorry I want to but do not have much time recently.
