### ISSUE TITLE
Package request: SGDBoop

### ISSUE THREAD

**Issue by daemonspudguy** [NixOS/nixpkgs#237833]
**Project description**
SGDBoop is a program that is used to add custom artwork to games on Steam, including non-Steam games

**Metadata**

* homepage URL: https://www.steamgriddb.com/boop
* source URL: https://github.com/SteamGridDB/SGDBoop
* license: CC-BY-NC-SA 4.0
* platforms: linux

**Comment by bayazidbh** [comment]
Seems to be duplicate of #220937

**Comment by puffnfresh** [comment]
Yeah, closing as duplicate.
