### ISSUE TITLE
Blank screen on AMD GPU during boot after changing to 23.05 release

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#237891]
### Describe the bug

I used to be able to see the LUKS password prompt during boot before upgrading to release-23.05. Now I basically have to enter the password blind, and the boot text output shows up a few seconds later.

### Steps To Reproduce

1. Unset [`services.xserver.videoDrivers`](https://nixos.org/manual/nixos/stable/options.html#opt-services.xserver.videoDrivers) as per the 23.05 release notes. Also remove "amdgpu" from `boot.initrd.kernelModules`, since that's presumably referencing the same driver.
2. Rebuild NixOS.
3. Reboot.

### Expected behavior

The boot process should work as before, showing the process up to and including the LUKS password prompt.

### Additional context

This problem seems to be specific to AMD, since two laptops I keep in sync with this configuration (except for the hardware-specific bits) work fine.

### Notify maintainers

@K900 as commit 82964d16945b77a3db503ff6db6c693ca6c20476 author.

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.33, NixOS, 23.05 (Stoat), 23.05.997.ddf4688dc7a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by K900** [comment]
> Also remove "amdgpu" from boot.initrd.kernelModules, since that's presumably referencing the same driver.

This part is wrong, it is not in fact the same driver, things are just confusingly named. Put it back.
