### ISSUE TITLE
Update cups to version 2.2.2

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#23793]
## Issue description

Currently nixpkgs' cups have not been updated for a year (it have more than one thousand commits since last update), and it is not working with my new printer.

I have tried to update cups by myself, but it causes a mass rebuild and I currently have no machine to build those packages. (mainly because many packages depends on cups, for example, chromium)

It would be great if someone can help update cups to the newest version, thank you.

**Comment by vcunat** [comment]
It's updated in staging branch.  I expect it will take a few days to produce binaries, and a few more to get merged into master and get into nixos-unstable channel.

**Comment by abbradar** [comment]
@vcunat nice, you figured out how to split `lib`!

**Comment by vcunat** [comment]
:-) Hopefully no substantial problems will come.  It "only" took a few hours of work.
