### ISSUE TITLE
Github-desktop broken since update to NixOS 23.05 due to dependency on openssl-1.1.1u

### ISSUE THREAD

**Issue by icodeforyou-dot-net** [NixOS/nixpkgs#237944]
### Describe the bug
Since updating my systems to NixOS 23.05 the package `github-desktop` is no longer usable. It depends on `openssl-1.1.1u` which is marked as insecure. 

### Steps To Reproduce
1. Run NixOS 23.05
2. Attempt to add `github-desktop` to your configuration

### Expected behavior
The system / home-manager flake is supposed to build with `github-desktop`. 

### Additional context

I get the following error shown below. Nix then tells me to do a bunch of workarounds such as `export NIXPKGS_ALLOW_INSECURE=1` or adding the package into the list of allowed packages. Which is not ideal for my flakes-based setup with multiple machines.

I am not sure why `github-desktop` depends on an outdated version of openssl in the first place, but maybe there is another way to get this solved permanently?

```console
error: Package ‘openssl-1.1.1u’ in /nix/store/0yzh1r9mhsr4vp5w96y3i0jgz3m2qzv6-source/pkgs/development/libraries/openssl/default.nix:210 is marked as insecure, refusing to evaluate.


Known issues: 
- OpenSSL 1.1 is reaching its end of life on 2023/09/11 and cannot be supported through the NixOS 23.05 release cycle. https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
```

### Notify maintainers
@dan4ik605743

**Comment by icodeforyou-dot-net** [comment]
Alright, I did a little digging since nothing appears to be happening here. I found this issue on the Linux Github Desktop Github - yeah this one: https://github.com/shiftkey/desktop/issues/809

It appears we are not the only people which had openssl issues. Arch Linux did too. If I am not mistaken, the issue behind all this in the fact that the current `github-desktop` app is based on Electron 22, which in turn is based on nodejs 16.17.1. Nodejs got openssl 3 support only in version 17 and onward.

Workaround might be to pass some special flags to nodejs when building from source as indicated in the issue above.

Problem is, our nix derivation is based on the `*.deb` release, and hence not built from source directly.

**Comment by icodeforyou-dot-net** [comment]
As of right now this appears to be working again, I will close this issue

**Comment by guruswarupa** [comment]
it's not fixed yet. 22:54 IST Aug 21 
![image](https://github.com/NixOS/nixpkgs/assets/112751363/95a13d01-024e-4855-8b8e-a1d6fc5014f1)

**Comment by guruswarupa** [comment]
> As of right now this appears to be working again, I will close this issue
 its not yet solved.
![image](https://github.com/NixOS/nixpkgs/assets/112751363/70aee7bb-4dfa-4648-a26a-f45291caca35)

**Comment by icodeforyou-dot-net** [comment]
@guruswarupa 

Is it possible you are not getting this from nixpkgs unstable?

Try running this flake with `nix develop` and see if you get github desktop:

```nix
{
  description = "Nix flake for GitHub Desktop";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/master";

  outputs = { self, nixpkgs }:
    let
      pkgs = import nixpkgs {
        system = "x86_64-linux";
      };
    in
    {
      devShells.x86_64-linux.default = pkgs.mkShell {
        name = "GitHub Desktop";
        nativeBuildInputs = with pkgs; [
          bashInteractive
        ];
        buildInputs = with pkgs; [
          github-desktop
        ];
      };
    };
}
```
