### ISSUE TITLE
Corrupt fontconfig files

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#23798]
## Issue description

The latest 17.03 seems to produce an empty font config for me, which results in no fonts working at all, as can be seen in this screenshot:

![2017-03-12-125902_1920x1080_scrot](https://cloud.githubusercontent.com/assets/20878/23834298/152a3fcc-074c-11e7-877b-cf040476b78c.png)

### Steps to reproduce

With the following configuration:

```nix
{
  imports = [];

  boot = {
    loader.grub = {
      version = 1;
      device = "/dev/sda";
    };
  };

  fileSystems."/" =
    { device = "/dev/sda1";
      fsType = "ext4";
    };
}
```

Run 

```
NIXOS_CONFIG=/path/to/configuration-above.nix nixos-rebuild build
```

Observe that `result/etc/fonts/2.11/fonts.conf` is the empty file.

If you were to boot this configuration, `fc-list` will result in `Fontconfig error: line 1: not well-formed`.

## Technical details

* Nixpkgs version: `17.03beta320.ade5837`

**Comment by abbradar** [comment]
I can't reproduce this too, only I tried `build-vm` instead. Together with https://github.com/NixOS/nixpkgs/issues/23799 It seems there's something seriously wrong with your FS D:

**Comment by ocharles** [comment]
Yep, --verify also shows fontconfig paths corrupt :( Might be time for a
new drive!

**Comment by abbradar** [comment]
Let'c close both of those -- not a NixOS bug.

**Comment by ocharles** [comment]
I was going to keep them open until I've actually confirmed that repairing those paths fixed the problem, but I'm easy either way.

**Comment by abbradar** [comment]
Indeed, I may have been hasty. Please test and reopen on any suspicion!
