### ISSUE TITLE
update ocamlPackages.llvm to the latest version of LLVM

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#23790]
## Issue description

The OCaml bindings for LLVM are becoming too old on nixpkgs. We are approaching the release of LLVM 4 and the latest available bindings are still for version 3.7.1 from 05 Jan 2016. Since then there were versions 3.8.0, 3.8.1, 3.9.0 and 3.9.1, and soon 4.0 for LLVM.

Please, update the package.

Maybe it will be more difficult to upgrade because LLVM has moved from autotools to CMake.

/cc @vbgl

**Comment by vbgl** [comment]
It would be nice if you could test and comment PR #23803. Thanks.

**Comment by romildo** [comment]
It works for me. See https://github.com/NixOS/nixpkgs/pull/23803#issuecomment-286008062.
