### ISSUE TITLE
Bug: "coreutils" options not recognized for "du" and "ls" --block-size command

### ISSUE THREAD

**Issue by matleborgne** [NixOS/nixpkgs#237975]
### Describe the bug
The **du** command has unrecognized options, like **--block-size**, but only in NixOS.
Same error for **ls** command, but strangely not for **df** command.

### Steps To Reproduce
1. Add **coreutils** to environment packages
2. Try for instance `du -h` command => everything ok
3. Try `du -BMB` or `du --block-size=MB` and it does not work
4. The output is "command unrecognized -B"

### Additional context
The command `man du` tells me that `du --block-size` and `du -B` are correct.
I have the same error for `du --version` which is not recognized.

I tried on other distros, no problem
I have a **workaround** for NixOS, which is `nix-shell -p coreutils`, and then `du -BMB` works.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.589.a558f7ac29f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by matleborgne** [comment]
Here are the output

Outside nix-shell
```console
[user@system:~]$realpath "$(command -v du)"
/nix/store/a337cxw655v0pjq9cpi8f0w36grib2m5-busybox-1.36.1/bin/busybox
```

Inside nix-shell
```console
[user@system:~]$realpath "$(command -v du)"
/nix/store/ahkfdxq8mcpsb5kvdvgqr1wv8zjngbh4-coreutils-9.1/bin/coreutils
```

**Comment by matleborgne** [comment]
Ok, you were right : when I remove `busybox` from my `environment.systemPackages`, the command works correctly.

So it would be a conflict between `busybox` and `coreutils` ?
I don't understand NixOS so deeply, so I can't say why `busybox` has priority over `coreutils` when calling `du` in standard shell, but coreutils takes the priority when calling `nix-shell -p busybox`.

But ok, I could say the problem is solved.
Thank you !

**Comment by figsoda** [comment]
I don't really understand the difference in behavior when busybox is in `environment.systemPackages` vs `nix-shell` either

> But ok, I could say the problem is solved.

I'll close this issue then
