### ISSUE TITLE
Update request: davinci-resolve 17.4.3 → 18.1.4

### ISSUE THREAD

**Issue by BKSalman** [NixOS/nixpkgs#238026]
- Package name: davinci-resolve
- Latest released version: 18.1.4

- Current version on the unstable channel: 17.4.3
- Current version on the stable/release channel: 17.4.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jshcmpbll 

-----

Note for maintainers: Please tag this issue in your PR.

I tried to update it myself, but I have no idea how, any help would be appreciated :)

I'm guessing the package was left out of date because it breaks too much, if so, is there a better way to install it on nixos?

**Comment by icodeforyou-dot-net** [comment]
I too had some issues with breakage lately. Assuming a "better" way than a nix derivation that works reliably would include a non-Nix way: You could try to install it inside Distrobox or a docker container. Maybe that works. If it does work properly I might be interested in knowing what you did exactly!

**Comment by BKSalman** [comment]
@icodeforyou-dot-net Hello! :), I haven't managed to get the distrobox solution to work for some reason (probably because I was losing IQ at the time), but now I got it working by having a local derivation and use it as an overlay

here's the file https://gist.github.com/BKSalman/53dc4a4bd3eb3989f88ce25b66d82853
it uses a local davinci resolve zip file that you add with prefetch rather than downloading it

I took inpiration from other derivations as well, so it's not all me :)

**Comment by icodeforyou-dot-net** [comment]
but they are already on 18.1.4 while we are still on 17.4.3. So maybe 17.4.3 still requires Python 2?

**Comment by icodeforyou-dot-net** [comment]
All I know it that getting Davinci Resolve run on NixOS in the first place at all was quite a battle. There was a longer discussion here on GitHub somewhere regarding this. It would be awesome to update it though to get rid of this Python problem. Right now it is a kind defunct.
