### ISSUE TITLE
Build failure: emacs on macOS 13.4 (aarch64-darwin)

### ISSUE THREAD

**Issue by nanzhong** [NixOS/nixpkgs#238087]
Trying to build the emacs package results in the build hanging on the step `make -C ../admin/grammars all EMACS="../../src/bootstrap-emacs"`. `bootstrap-emacs` processes are stuck sitting idle.

```console
› ps aux | grep bootstrap
nan              15404   0.0  0.0 408629104   1616 s004  R+    8:39am   0:00.00 /nix/store/27kz2hi95sy9fs3vlkklfcfpkb3h2l7q-gnugrep-3.11/bin/grep --color=auto bootstrap
56930            12232   0.0  0.0 410067936  63168   ??  S     8:37am   0:01.00 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/wisent/grammar -f wisent-batch-make-parser -o ../../lisp/cedet/srecode/srt-wy.el srecode-template.wy
56930            12193   0.0  0.0 410067936  62736   ??  S     8:37am   0:01.01 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/wisent/grammar -f wisent-batch-make-parser -o ../../lisp/cedet/semantic/wisent/python-wy.el python.wy
56930            12022   0.0  0.0 410515424  64176   ??  S     8:37am   0:01.11 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/wisent/grammar -f wisent-batch-make-parser -o ../../lisp/cedet/semantic/wisent/js-wy.el js.wy
56930            11944   0.0  0.0 410515424  63792   ??  S     8:37am   0:01.14 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/wisent/grammar -f wisent-batch-make-parser -o ../../lisp/cedet/semantic/wisent/javat-wy.el java-tags.wy
56930            11937   0.0  0.0 410515424  63456   ??  S     8:37am   0:01.15 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/wisent/grammar -f wisent-batch-make-parser -o ../../lisp/cedet/semantic/grammar-wy.el grammar.wy
56930            11880   0.0  0.0 410646496  63824   ??  S     8:37am   0:01.18 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/bovine/grammar -f bovine-batch-make-parser -o ../../lisp/cedet/semantic/bovine/scm-by.el scheme.by
56930            11718   0.0  0.0 410253280  63952   ??  S     8:37am   0:01.22 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/bovine/grammar -f bovine-batch-make-parser -o ../../lisp/cedet/semantic/bovine/make-by.el make.by
56930            11630   0.0  0.0 410777568  63520   ??  S     8:37am   0:01.19 ../../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -l semantic/bovine/grammar -f bovine-batch-make-parser -o ../../lisp/cedet/semantic/bovine/c-by.el c.by
56930            11628   0.0  0.0 408859616   4928   ??  S     8:37am   0:00.02 make -C ../admin/grammars all EMACS=../../src/bootstrap-emacs
56930            11355   0.0  0.0 408877024   5664   ??  S     8:37am   0:00.02 make -C ../lisp autoloads EMACS=../src/bootstrap-emacs
```

### Steps To Reproduce

1. Build emacs forcing a rebuild to avoid the cache `nix build github:nixos/nixpkgs#emacs --rebuild --print-build-logs`

### Build log

https://gist.github.com/nanzhong/3bbfda6d7889c5cc68bf92cc81876f4e#file-build_emacs-log

### Additional context

A process sample of `bootstrap-emacs` processes shows that they seem to be stuck after trying to make a call to `ns_can_use_native_image_api`. I am not sure why that is being called while making grammar parsers...

Link to a process sample: https://gist.github.com/nanzhong/3bbfda6d7889c5cc68bf92cc81876f4e#file-sample_bootstrap-emacs-txt

### Notify maintainers

@AndersonTorres @Atemu @jwiegley @lovek323 @matthewbauer

### Metadata

```console
› nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/xfnvqy8cnn9i4pc1nipw76a41j59ibld-source`
```

**Comment by Atemu** [comment]
Given that the build farm's macs are able to build it (it's in the cache), this is an issue with your machine.

I'd recommend you to ask on the Discourse whether someone has seen something like this before.

Do you have any antivirus snakeoil running? That might be blocking things.

**Comment by nanzhong** [comment]
I've been able to reproduce this on two different machines (one intel Mac which does have antivirus and other endpoint device management software, and this arm Mac with no antivirus or anything else) both with fresh installs of nix. I did install nix on both machines with https://github.com/DeterminateSystems/nix-installer (v0.9.1), I'm not familiar with installation differences between the official installer and that one (aside from the documented differences, which all seem harmless).

One thing of note is that this does not happen when I build `emacs-nox`. In particular it's the `withNS` option that causes this.

Thanks for the discord suggestion, I will reach out.

**Comment by Atemu** [comment]
Perhaps try the regular Nix installer.

\*Discourse. Though there is an unofficial Discord too I believe. I don't like Discord very much though.

I just tried to reproduce the error but couldn't. eaebbdf59ac1c9dd72011854d8bbad18b22e4cff builds emacs fine on my aarch64-darwin machine on 13.4.

**Comment by nanzhong** [comment]
I had some more time to debug this and I've discovered that the reason for this failure is actually `auto-allocate-uids`. I'm not familiar enough with nix or that experimental feature to have a sense for why the would cause this type of build issue, but leaving it here for posterity if anyone else runs into this issue.
