### ISSUE TITLE
Update request: mkdocs-material 9.1.13 → 9.1.16

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#238140]
- Package name: python311Packages.mkdocs-material, python310Packages.mkdocs-material
- Latest released version: 9.1.16

- Current version on the unstable channel: 9.1.13
- Current version on the stable/release channel: 9.1.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dali99

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/commit/643c7448eac02c139a4fd7cbda614b2ff657c830
