### ISSUE TITLE
Package request: mcpelauncher

### ISSUE THREAD

**Issue by Dekomoro** [NixOS/nixpkgs#238155]
**Project description**
A launcher for minecraft bedrock for linux that utilizes legitimate copies

**Metadata**

* homepage URL: https://mcpelauncher.readthedocs.io/
* source URL: https://github.com/minecraft-linux/mcpelauncher-manifest
* license: gpl3
* platforms: linux

**Comment by figsoda** [comment]
duplicate of #231875
