### ISSUE TITLE
Sublime Text 3 failing to invoke gksu

### ISSUE THREAD

**Issue by jeremejevs** [NixOS/nixpkgs#23816]
## Issue description

When opening a root-owned file, like `/etc/nixos/configuration.nix`, with user-launched Sublime, and trying to save it, I get the following error:

```
Failed to run cp '/tmp/<snip>.tmp' '<snip>' as user root.

Failed to communicate with gksu-run-helper.

Received:
 Unable to run /run/wrappers/bin/su: No such file or directory
While expecting:
 gksu: waiting
```

## Technical details

* System: 16.09.1827.f89ab94
* Nix version: 1.11.7
* Nixpkgs version: same as System, but I'm using **unstable** for sublime3

**Comment by jeremejevs** [comment]
@wmertens @codyopel @zimbatm (as per @mention-bot in my ST-related PR)

**Comment by zimbatm** [comment]
Are you able to invoke gksu directly?

What is the output of `ls -la /run/wrappers/bin/su` ?

**Comment by jeremejevs** [comment]
@zimbatm Yes, I can invoke gksu after installing it (or doing `nix-shell` of `sublime3`). And I have no `/run/wrappers` on my system.

**Comment by zimbatm** [comment]
Setuid wrappers are a bit awkward to use right now. Because the /nix/store doesn't store them they have to be installed by nixos with a systemd service. See http://nixos.org/nixos/options.html#security.setuidprograms

**Comment by jeremejevs** [comment]
Sorry, I'm really out of my depth on this one 🙂 What does that mean for ST and gksu?

**Comment by zimbatm** [comment]
No worries :)

Basically as a user you would expect all required the dependencies to be installed with sublime but it's not.

To get the su dependencies try to add the following to configuration.nix:
```nix
{
  environment.systemPackages = [ pkgs.su ];
  security.setuidprograms = ["su"];
}
```

**Comment by jeremejevs** [comment]
Hmm, added that, but nothing has changed, same error. Thing is, `gksu` works by itself, even though `libgksu` refers to `/run/wrappers/bin/su`. On my system `su` is in `/var/setuid-wrappers`, not `/run/wrappers/bin`.

**Comment by zimbatm** [comment]
Yeah that might be the issue, the wrappers have changed location

**Comment by jeremejevs** [comment]
Okay, thanks, that was indeed the issue. FrankenNix is a thing too :)
