### ISSUE TITLE
tor-browser-bundle-bin: unusable

### ISSUE THREAD

**Issue by nektro** [NixOS/nixpkgs#238204]
### Describe the bug
Unable to launch the app.

### Steps To Reproduce
- `[meghan@nixos:~]$ nix-shell-unstable -p tor-browser-bundle-bin`
- `[nix-shell:~]$ tor-browser `
- `nix-shell-master: command not found`

### Notify maintainers

@felschr @panicgh @joachifm @hax404

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102, NixOS, 22.11 (Raccoon), 22.11.3196.cd34d6ed7ba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(meghan): `""`
 - channels(root): `"nixos-22.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by panicgh** [comment]
* What is `nix-shell-unstable`? I don't have that command.
* The error complains about a `nix-shell-master` command. I don't know that command. Where does it come from?
* You're on NixOS 22.11. There was a new release 23.05 two weeks ago, which you may (or may not) consider updating to.

Assuming `nix-shell-unstable` is an alias for a `nix-shell -I nixpkgs=channel:nixpkgs-unstable`, I created a VM with NixOS 22.11 and ran this nix-shell there. TBB ran fine.

<details>
<summary>configuration.nix for VM</summary>

```nix
{ config, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/virtualisation/qemu-vm.nix>
  ];

  virtualisation.memorySize = 3072;
  virtualisation.diskSize = 6000;
  virtualisation.writableStore = true;
  virtualisation.writableStoreUseTmpfs = false;

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  services.xserver.enable = true;

  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  users.users.alice = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    packages = with pkgs; [
      firefox
      tree
    ];
    initialPassword = "testpw";
  };

  system.stateVersion = "22.11";
}
```
</details>

Build and start the VM:

```console
$ nix-build '<nixpkgs/nixos>' -A vm -I nixpkgs=channel:nixos-22.11 -I nixos-config=./configuration.nix
$ ./result/bin/run-nixos-vm
```

In the VM login as `alice`/`testpw` and open a console, then run:

```console
[alice@nixos:~]$ nix-shell -I nixpkgs=channel:nixpkgs-unstable -p tor-browser-bundle-bin
[nix-shell:~]$ tor-browser
```

TBB started fine, connected to Tor and opened a webpage.

**Comment by nektro** [comment]
`nix-shell-unstable` is

```
nix-shell-unstable() {
  nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz $@
}
```

i have no idea where `nix-shell-master`, i dont define that

**Comment by nektro** [comment]
using your command I get the same result

![image](https://github.com/NixOS/nixpkgs/assets/5464072/d186315f-4abf-44e9-8d3b-75e76a68f733)

however, I will update to 23.05 and report back

**Comment by nektro** [comment]
huh, `strace tor-browser` starts it up just fine...

**Comment by nektro** [comment]
did some more digging, it is my fault. so sorry
