### ISSUE TITLE
Package request: TickTick

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#238389]
**TickTick** is one of the very first to-do list apps to creatively integrate features such as Calendar, Pomodoro Timer, Habit, into one functional app. 

**Metadata**

* homepage URL: https://www.ticktick.com/
* source URL: https://www.ticktick.com/about/download
* platforms: linux

**Comment by btctrl** [comment]
sorry if this is the wrong place but can macos download be added?

`aarch64-darwin`
