### ISSUE TITLE
Package request: tremotesf2

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#238483]
**Project description**

Remote GUI for transmission-daemon

**Metadata**

* homepage URL: https://github.com/equeim/tremotesf2
* source URL: https://github.com/equeim/tremotesf2
* license: GPLv3
* platforms: Linux

**Comment by sochotnicky** [comment]
This was just merged to master yesterday: https://github.com/NixOS/nixpkgs/pull/232488

Not backported yet and nixos unstable channel is having some issues currently (https://status.nixos.org/) but you should be able to rebuild.

**Comment by sochotnicky** [comment]
I'll wait until the backport (https://github.com/NixOS/nixpkgs/pull/239146) is released and then I'll close this.

**Comment by sochotnicky** [comment]
It's now available as per: https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=tremotesf
