### ISSUE TITLE
Netdata broken on unstable

### ISSUE THREAD

**Issue by THERAAB** [NixOS/nixpkgs#238415]
### Describe the bug
Netdata cannot build on unstable with default service.  I suspect it's due to https://github.com/NixOS/nixpkgs/commit/701679e94e40ab4c3e08c4246e4ec9ee173e0e7a

### Steps To Reproduce
1. Try to build netdata service in unstable with example like below
2. Build fails with error (logs in additional context section)
3. Same service config works when rolling back to 23.05

```nix
  services.netdata = {
    enable = true;
    configText = ''
      [global]
        update every = 5
      [ml]
        enabled = no
      [logs]
        debug log = none
        error log = none
        access log = none
    '';
  };
```
### Expected behavior
Netdata builds

### Additional context
error:

       … while calling the 'head' builtin

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/attrsets.nix:784:11:

          783|         || pred here (elemAt values 1) (head values) then
          784|           head values
             |           ^
          785|         else

       … while evaluating the attribute 'value'

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/modules.nix:759:9:

          758|     in warnDeprecation opt //
          759|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          760|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'claim_token_file' missing

       at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/nixos/modules/services/monitoring/netdata.nix:272:32:

          271|         PrivateMounts = true;
          272|       } // (lib.optionalAttrs (cfg.claim_token_file != null) {
             |                                ^
          273|         LoadCredential = [

### Notify maintainers

@RaitoBezarius 

### Metadata

I already rolled back to 23.05, but here's my metadata for that

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.7, NixOS, 23.05 (Stoat), 23.05.20230614.ddf4688`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/6kp2ql3nww07p270y2qfjpl4habskbkb-source`
```

**Comment by RaitoBezarius** [comment]
The fix has been sitting here. #238289

**Comment by RaitoBezarius** [comment]
The fix has been merged, it should propagate soon.

**Comment by THERAAB** [comment]
thank you @RaitoBezarius
