### ISSUE TITLE
`nc4nix` was not supposed to be used and packaged

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#238405]
After discussing with @ajs124 in the news issue, which lead to #238402.

We learned that `nc4nix` had no license information when it was introduced in https://github.com/NixOS/nixpkgs/pull/197373 and was rehosted on your Git @onny in violation of their copyright.

Furthermore, the author has no plan to support `nc4nix` in nixpkgs, therefore, it has become a liability more than anything else at this point.

@onny please remove `nc4nix` from nixpkgs and let's start looking for another solution for auto-updates, one which can also be compatible with the licensing information problem.

cc @Ma27

**Comment by ajs124** [comment]
it's fine now, the powers that be (my boss) decided that we'll publish this under MIT and there's a mirror here now https://github.com/helsinki-systems/nc4nix/
