### ISSUE TITLE
Firefox 52.0 FTBFS (NSS < 3.28.3)

### ISSUE THREAD

**Issue by clacke** [NixOS/nixpkgs#23843]
## Issue description

Firefox fails to build from source. Current version of NSS in nixpkgs is 3.28.1, but firefox needs 3.28.3.

```
DEBUG: configure:10605: checking for nss-config
DEBUG: configure:10640: checking for NSS - version >= 3.28.3
DEBUG: configure: error: you don't have NSS installed or your version is too old
ERROR: old-configure failed
builder for ‘/nix/store/p68zgmj2bqsjbd93lkcmm78kgwsiw3n7-firefox-unwrapped-52.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/bm6xm1cjpr5f4fm87hifa91ahngfp3fg-firefox-52.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/bm6xm1cjpr5f4fm87hifa91ahngfp3fg-firefox-52.0.drv’ failed
```

### Steps to reproduce

    $ nix-build  -A firefox '<nixpkgs>'

## Technical details

 * Ubuntu 16.04.2 LTS xenial
 * nix-env (Nix) 1.11.7
 * Nixpkgs 17.09pre102933.26625c9

**Comment by 7c6f434c** [comment]
I think the current `master` state has fresh enough nss.

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nixpkgs/issues/23720

**Comment by vcunat** [comment]
It's duplicate in any case.

**Comment by clacke** [comment]
Ok, just not in the channels yet. Thanks!
