### ISSUE TITLE
NixOS: increase default value of vm.max_map_count

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#238412]
### Describe the bug
Applications are starting to allocate more times than allowed by the default value of vm.max_map_count, 65530.

For instance, this situation arises in applications such as Ryujinx (https://github.com/Ryujinx/Ryujinx/pull/4702) and newer Windows games like Hogwarts Legacy (https://github.com/HansKristian-Work/vkd3d-proton/issues/1420).

SteamOS has already addressed this matter by augmenting the aforementioned value, while Fedora intends to implement the same modification in Fedora 39 (https://www.phoronix.com/news/Fedora-39-Max-Map-Count-Approve, https://fedoraproject.org/wiki/Changes/IncreaseVmMaxMapCount).

**Comment by RaitoBezarius** [comment]
Please feel free to send PRs, it's hard to track those issues as you don't mention any owner.

**Comment by SuperSamus** [comment]
The line to add is:
```
boot.kernel.sysctl."vm.max_map_count" = mkDefault n;
```

The questions are:
- How big should n be? 2147483642? 1048576?
- In which file should I add it? At the bottom of nixos/modules/config/sysctl.nix?

**Comment by RaitoBezarius** [comment]
> The line to add is:
> 
> ```
> boot.kernel.sysctl."vm.max_map_count" = mkDefault n;
> ```
> 
> The questions are:
> 
> * How big should n be? 2147483642? 1048576?
> * In which file should I add it? At the bottom of nixos/modules/config/sysctl.nix?

You mentioned other distros were thinking about bumping it, let's follow Fedora lead

In the relevant file, a quick grep shows indeed that sysctl is one of the best candidate. :)

**Comment by yu-re-ka** [comment]
For the policy discussion: I'm all in favor of doing this soon(m). It is not really dangerous and as people have explained the previous default has been there for historical reasons and 32 bit systems.
