### ISSUE TITLE
SDDM xsessions doesn't work?

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#23848]
## Issue description

I'm using SDDM. Regardless of which desktop session I select (e.g. 'none + xmonad'), SDDM uses to the default display manager set in `configuration.nix` and xterm. 

Reviewing the xsession script provided in sddm.conf, it looks like somehow the xsession script gets called with unexpected arguments, since it does everything else - e.g. it sources my .xprofile and runs feh to set a background.

### Steps to reproduce

In `configuration.nix`:
```nix
  services.xserver = {
    displayManager.sddm.enable = true;
  }
  windowManager = {
    i3.enable = true;
    xmonad.enable = true;
    default = "i3";
  }
```

Restart X. Note that SDDM provides a dropdown for i3 and xmonad with and without xterm, but regardless what's selected, you get i3 and an xterm.

## Technical details

* System:  16.09.1803.40de598 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1803.40de598"

## Additional notes

My current workaround was simply to copy the xsession configured for SDDM into a personal .xsession and edit out the "setup" part. It means that I need to edit that file to choose my session, but at least I *can.* It'll also mean more work when updates happen (since the store paths of displayManagers are embedded in the file), so I'd prefer it as a temporary solution.

I'd hoped to be able to fix this for myself, but debugging proved difficult. To get a version of xsession that I could edit to add logging, I copied it, the desktops directory and the sddm.conf into a directory, edited them to refer to one another, and then linked /etc/sddm.conf to my edited config. Although the system log indicates that sddm-greeter read the .desktop files, the session dropdown is empty, and SDDM fails to provide any login at all - i.e. after accepting a password it simply stops. The log indicates that the fallback session is corrupt or something: `
sddm[5800]: Failed to find XDG session type for session "/var/lib/sddm/.desktop"`. I've got no idea why sddm-greeter doesn't like my .desktop files or how to proceed from here.

**Comment by flosse** [comment]
I'm using `awesome` and there are similar problems :-\

**Comment by laMudri** [comment]
At all related to #18238? What happens if you have `services.xserver.desktopManager.xterm.enable = false`?

**Comment by Mic92** [comment]
This should fix the problem: https://github.com/NixOS/nixpkgs/pull/23264

**Comment by primeos** [comment]
A fix should soon be backported to `17.03`.

Workaround: `services.xserver.desktopManager.default = "none"` (should "disable" xterm).

**Comment by jcrben** [comment]
seems like this might be fixed? haven't tested it (yet)...

**Comment by primeos** [comment]
Yes, I guess - If not please reopen this issue or drop a comment.
