### ISSUE TITLE
Emacs "No GSettings schemas" error

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#23845]
## Issue description
I installed emacs via configuration.nix, but when I try open file dialog it crashes with error 

`* (emacs:4798): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(emacs:4798): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(emacs:4798): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Fatal error 5: Trace/breakpoint trap
Backtrace:
emacs[0x509edc]
emacs[0x4ef82b]
emacs[0x50827e]
emacs[0x5084a9]
emacs[0x508549]
/nix/store/68sa3m89shpfaqq1b9xp5p1360vqhwx6-glibc-2.25/lib/libpthread.so.0(+0x11840)[0x7fa04bc9a840]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libglib-2.0.so.0(+0x4f731)[0x7fa04eec5731]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libglib-2.0.so.0(g_log_default_handler+0xcc)[0x7fa04eec67bc]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libglib-2.0.so.0(g_logv+0x1f4)[0x7fa04eec6ae4]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libglib-2.0.so.0(g_log+0x8f)[0x7fa04eec6cef]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgio-2.0.so.0(+0x107db2)[0x7fa04f4e3db2]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(+0x1517b)[0x7fa04f19f17b]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_object_new_valist+0x163)[0x7fa04f1a0a53]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_object_new+0xf1)[0x7fa04f1a0fa1]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(+0x1c332c)[0x7fa0509f332c]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(+0x1c6820)[0x7fa0509f6820]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(+0x1bee54)[0x7fa0509eee54]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_closure_invoke+0x145)[0x7fa04f199a85]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(+0x21a71)[0x7fa04f1aba71]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xfbc)[0x7fa04f1b481c]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_signal_emit_by_name+0x4a5)[0x7fa04f1b5015]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(+0x1ccd24)[0x7fa0509fcd24]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(+0x1cd026)[0x7fa0509fd026]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_object_set_property+0x20b)[0x7fa04f1a1d6b]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(+0x151e9)[0x7fa04f19f1e9]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_object_new_valist+0x163)[0x7fa04f1a0a53]
/nix/store/k5qdcln2yvdwy55xlkmgl998a2hfb427-glib-2.50.3/lib/libgobject-2.0.so.0(g_object_new+0xf1)[0x7fa04f1a0fa1]
/nix/store/w1r76jqpwqy34lcm9y0a3r4bbk6i4af1-gtk+3-3.22.8/lib/libgtk-3.so.0(gtk_file_chooser_dialog_new+0x74)[0x7fa0509ef6a4]
emacs[0x4de2c0]
emacs[0x4e1868]
emacs[0x4cede4]
emacs[0x565ff7]
emacs[0x59f163]
emacs[0x565e2b]
emacs[0x59f163]
emacs[0x565e2b]
emacs[0x59f163]
emacs[0x565e2b]
emacs[0x59f163]
emacs[0x56556d]
emacs[0x568ac7]
...
Trace/breakpoint trap`

I opened default.nix of emacs, but "wrapGAppsHook" is already used. 

### Steps to reproduce

1. open emacs;

2. try to open file or create new

## Technical details

* System: NixOS 17.03beta320.ade5837 (Gorilla)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.03beta320.ade5837"

**Comment by frigatefreedom** [comment]
Using info from here: https://github.com/NixOS/nixpkgs/issues/23160 
I added in configuration.nix:

`
nixpkgs.config = {
 
    packageOverrides = pkgs: {
        emacs = pkgs.lib.overrideDerivation (pkgs.emacs.override {
            # Use gtk2
            withGTK2 = true;
            withGTK3 = false;
        });
    };
};
`

After building emacs with gtk2 issue was resolved.
Why don't make emacs build with gtk2 by default?

**Comment by abbradar** [comment]
Can you try it with #23858?

We try to move from GTK2 currently; that's why when it's possible we use other toolkits.

**Comment by frigatefreedom** [comment]
@abbradar, thanks this fix works for me.

**Comment by abbradar** [comment]
Thank you for testing!
