### ISSUE TITLE
fatal error: 'os/availability.h' file not found #include <os/availability.h>

### ISSUE THREAD

**Issue by ftpronk** [NixOS/nixpkgs#23859]
## Issue description
I'm trying to compile VTK 6.3.0 using nix. During compilation I encounter the error:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:21:10: fatal error: 'os/availability.h' file not found
#include <os/availability.h>
```
The full error message is:

>  [53%] Building CXX object Rendering/OpenGL/CMakeFiles/vtkRenderingOpenGL.dir/vtkCocoaRenderWindowInteractor.mm.o
In file included from /Users/ftpronk/packages/VTK-6.3.0/Rendering/OpenGL/vtkCocoaRenderWindowInteractor.mm:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:21:10: fatal error: 'os/availability.h' file not found
#include <os/availability.h>

### Steps to reproduce
1. My `default.nix` used for the nix-shell environment is:
```
with import <nixpkgs> {};
stdenv.mkDerivation rec {
  name = "env";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
    bash-completion
    clang_39
    cmakeCurses
    gnumake42
    llvm_39
    llvmPackages.stdenv
    python27Full
    python27Packages.matplotlib
    python27Packages.numba
    python27Packages.numpy
    python27Packages.parsedatetime
    python27Packages.pip
    python27Packages.ipython
    qt4
    ];
}
```
2. Download/Unpack VTK 6.3.0
3. Make a `build` directory, enter,  copy `default.nix`, run `nix-shell .`
3. Run `ccmake ../`, and enable the following options:
    * CMAKE_BUILD_TYPE : Release
    * VTK_Group_Qt : ON
    * VTK_PYTHON_VERSION : 2
    * VTK_QT_VERSION : 4
    * VTK_RENDERING_BACKEND : OpenGL
    * VTK_USE_SYSTEM_FREETYPE : ON
4. Build with `make`

## Technical details

* System: Mac OS X 10.11.6, El Capitan
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.09pre102933.26625c9"

**Comment by copumpkin** [comment]
It's a bad sign that it's using `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h` in the first place, which indicates that the build is impure.

**Comment by ftpronk** [comment]
Mm..  I was assuming (probably wrongly?) that I would need a semi-impure build to allow linking with system libraries needed for the OpenGL rendering. But to be honest, I'm way out of my depth here with this low-level stuff.. (And discovering Nix at the same time, so that doesn't help)

Is there a way to have native OpenGL rendering support using pure nix packages?

**Comment by dmjio** [comment]
I'm running into this same issue as well.

**Comment by bcdarwin** [comment]
Closing since VTK 6 is obsolete and VTK 8.x and 9.x are available in tree.
