### ISSUE TITLE
nixos-containers: add support for creating containers by specifing nixos file

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#2385]
Currently the only way to create nixos containers are by specifing a string, which is not very usefull if i want to test my deployment configurations. It would be great if i could specify configuration file that would get built. Also there should be an option to make rebuilts of containers outside of containers. I manage all of my machines using nixops and don't want to rely on nixos-rebuild.

**Comment by Profpatsch** [comment]
Works, you can do `container.<name>.config =` now. close cc @jagajaga

**Comment by kamilchm** [comment]
@Profpatsch I have a configuration file called ``container.nix`` and I want to use it as a initial configuration used by
```
nixos-container create foo --config conatiner.nix
```
I don't want to specify and rebuilt all my containers that I'm using for different testing purposes when I rebuilt my system.

**Comment by Profpatsch** [comment]
@kamilchm Why? Only stuff that has changed gets rebuilt/downloaded, so why not keep it declarative?

**Comment by kamilchm** [comment]
I thought about something like project specific containers that I place in different repos like Vagrantfiles. I doesn't look elegant for me if I need to modify my main configuration.nix when I clone/move/delete project workspaces.

**Comment by Profpatsch** [comment]
I use `containers.mycontainer.config = ./mycontainer.nix`.

But you should take a look at `containers.<name>.path`, which is exactly what you want.
