### ISSUE TITLE
nixos-containers: add support for running on non nixos, non systemd machines

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#2386]
Currently nixos-containers could be only run on nixos machines. It would be great if it would be possible to run them on non nixos linux machines using something like `lxc` or `libvirt-lxc`. I already made this possible, but it's a hackup `https://github.com/kiberpipa/nix-rehash/blob/master/container.nix`.

**Comment by Profpatsch** [comment]
(triage) status of this?

**Comment by danbst** [comment]
@offlinehacker solution is nice, but not very in-line with currently selected approach. https://github.com/erikarvstedt/extra-container is a step in more convenient way.

I've described in https://github.com/erikarvstedt/extra-container/issues/1 that it is possible to run NixOS containers on Ubuntu, so maybe I should push more here and integrate `extra-container` into current `container.pl`.
