### ISSUE TITLE
tiny-cuda-nn: Build fails due to unquoted environment variable export

### ISSUE THREAD

**Issue by ConnorBaker** [NixOS/nixpkgs#238617]
Originally spotted by @nviets (thank you!).

### Steps To Reproduce

Steps to reproduce the behavior (assuming `allowUnfree` and `cudaSupport` are both `true`):

`nix build .#tiny-cuda-nn`

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/v6q53k8zlkm2ccd8dlms65fwm65xzp0k-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
/nix/store/j0xzghjmynydvw37zihdbw598j0iwly9-stdenv-linux/setup: line 127: 61: command not found
/nix/store/j0xzghjmynydvw37zihdbw598j0iwly9-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

### Additional context

The `TCNN_CUDA_ARCHITECTURES` environment variable contains semicolons and must be quoted, otherwise bash will interpret the semicolons as command separators.

https://github.com/NixOS/nixpkgs/blob/6764cc2a0909396c435ee4c915c72c7db1be6bae/pkgs/development/libraries/science/math/tiny-cuda-nn/default.nix#L83-L85

**Comment by nviets** [comment]
@ConnorBaker, @samuela, @SomeoneSerge - Hey, I am not sure how to clean up the mess I just made on 222778. Really embarrassed. I intended to rebase and hit merge instead, which pulled in 10k changes.

**Comment by ConnorBaker** [comment]
No worries! Happens to everyone at some point :)

Personally, I'd just open a new PR.

**Comment by nviets** [comment]
Here it is: #238622. Does the commit history look clean enough? I'll try to rebase it later, but I am concerned about retagging all of those folks.

**Comment by samuela** [comment]
> do we recommend squashing before merge? I know I typically just do force pushes to avoid any commit history :l

I don't think we have an official stance on this. Contributors use their best judgement for whatever keeps the commit history simplest and easiest to use
