### ISSUE TITLE
ccacheStdenv does not pass libc tests

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#2387]
I'm trying to use ccacheStdenv. I use max-jobs 6, cores 6, use-chroot true, and the following .nixpkgs/config.nix for my user:

```
{ pkgs }:

{
  replaceStdenv = { pkgs }: pkgs.ccacheStdenv;

  packageOverrides = pkgs: {
    ccacheWrapper = pkgs.ccacheWrapper.override {
      extraConfig = ''
        CCACHE_COMPRESS=1
        CCACHE_DIR=/bin/.ccache
      '';
    };
  };
}
```

I ran `nix-shell ~/nixpkgs/ -A ccacheStdenv` as user.

Only showing the failed tests below:

```
=====================================================
   GNU coreutils 8.21: gnulib-tests/test-suite.log   
=====================================================

3 of 289 tests failed.  (28 tests were not run).  

.. contents:: :depth: 2


FAIL: test-fdutimensat (exit: 134)
==================================

test-utimens.h:103: assertion failed

FAIL: test-utimens (exit: 134)
==============================

test-utimens.h:130: assertion failed

FAIL: test-utimensat (exit: 134)
================================

test-utimens.h:119: assertion failed

======================================
3 of 289 tests failed
(28 tests were not run)
See gnulib-tests/test-suite.log
Please report to bug-coreutils@gnu.org
======================================
make[6]: *** [test-suite.log] Error 1
make[6]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21/gnulib-tests'
[q[qmake[5]: *** [check-TESTS] Error 2
make[5]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21/gnulib-tests'
[q[qmake[4]: *** [check-am] Error 2
make[4]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21/gnulib-tests'
[q[qmake[3]: *** [check-recursive] Error 1
make[3]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21/gnulib-tests'
[q[qmake[2]: *** [check] Error 2
make[2]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21/gnulib-tests'
[q[qmake[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/tmp/nix-build-coreutils-8.21.drv-1/coreutils-8.21'
[q[qmake: *** [check] Error 2
```

**Comment by fread2281** [comment]
ccache is erroring with `ccache: error: Failed to create directory /nix/var/ccache/tmp: Permission denied` (chroot disabled) using @wmertens's config for me

**Comment by vcunat** [comment]
@fread2281, I suspect you didn't follow:

**Comment by wizeman** [comment]
@lethalman When you opened this issue, were you using ZFS, by any chance? If so, you were probably running into #5652, which caused the exact same failures.

**Comment by fread2281** [comment]
@vcunat I did. /etc/nix/nix.conf has `build-use-chroot = false` and `/var/cache/ccache` in `build-chroot-dirs`. So does /etc/nixos/configuration.nix, and I'm using `--option build-extra-chroot-dirs /var/cache/ccache=/var/cache/ccache/ --option build-use-chroot false` (I switched to `/var/cache/ccache`).

**Comment by fread2281** [comment]
As I suspected, I had to rebuild to get nix to take either `build-use-chroot` or `build-extra-chroot-dirs` (`--option` on nixos-rebuild didn't work, copying and editing /etc/nix/nix.conf didn't work)

**Comment by garbas** [comment]
@lethalman were you running ZFS this on ZFS? looks like this might be related to that as @wizeman pointed out.

**Comment by Profpatsch** [comment]
triage: what’s the status?
