### ISSUE TITLE
Disable travis [take 526]

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23887]
I know we've raised this before, but it's getting ridiculous. Every email I get from it is "still broken", and everything in the commit log for the past few days has been a red X. It's providing negative value right now, and I think we should just turn it off until someone has time to put against fixing it or replacing it with a more tailored solution.

@edolstra @shlevy @domenkozar @grahamc

**Comment by grahamc** [comment]
I fully agree.

**Comment by domenkozar** [comment]
It happens on stdenv rebuild. Our documentation depends on pandoc, which takes ages to build and travis-ci can't handle it.

**Comment by dezgeg** [comment]
I think this time it's that nixpkgs tarball job (or specifically eval-release.nix) takes more memory than is available in Travis.

**Comment by copumpkin** [comment]
The specifics seem less important than the gist. I largely just ignore the emails because I don't trust the system to do anything useful for me. Does anyone get any value out of it, and enough value to justify the amount of noise it causes for everyone else?

**Comment by shlevy** [comment]
+1million.

**Comment by shlevy** [comment]
Shockingly I'm still getting bullshit emails. Now that hydra can build PRs I think we really need to just kill this.

**Comment by FRidh** [comment]
Let's just reduce it to checking evaluation only.

**Comment by shlevy** [comment]
Even that breaks spuriously at times. Can you honestly say you've ever gotten value out of these travis checks?

**Comment by shlevy** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/d0b4c5fef7bba8865ac210b7a5ad089ddc419bdb

**Comment by 7c6f434c** [comment]
I cna say that I have got some value out of Travis build logs when reviewing some PRs, but still the situation is ridiculous.
