### ISSUE TITLE
Package request: gdrive 3

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#238815]
**Project description**

To interact with Google Drive via the command line, there are `drive` and `gdrive`, both no longer maintained and now in my experience unable to authenticate with Google. `gdown` still works, but it only targets public files and folders.

There is a spiritual successor / fork of gdrive (2): gdrive 3

**Metadata**

* homepage URL: https://github.com/glotlabs/gdrive
* source URL: https://github.com/glotlabs/gdrive
* license: mit
* platforms: unix

**Comment by figsoda** [comment]
#238860
