### ISSUE TITLE
wiki: PulseAudio

### ISSUE THREAD

**Issue by jsmaniac** [NixOS/nixpkgs#23883]
https://nixos.org/wiki/PulseAudio

Things to change while migrating (I don't have permission to update them directly on the old wiki):
* In the `MPlayer` section, the first block of code should be
     ```
     cat > ~/.nix-defexpr/mplayer.nix <<EOF
     …
     EOF
     ```
  instead of the current syntax (which fails at least on ZSH, since it expects `EOF` alone on its line, and probably fails on bash too)
     ```
     cat <<EOF
     …
     EOF > ~/.nix-defexpr/mplayer.nix
     ```
* Still in the `MPlayer` section, `nix-env -iA mplayer` should be changed to `nix-env -f '<nixpkgs>' -iA mplayer`, otherwise one gets `error: attribute ‘MPlayer’ missing, at /home/me/.nix-defexpr/mplayer.nix:4:3`

**Comment by globin** [comment]
Works for me in zsh
```
cat > ~/.nix-defexpr/mplayer.nix <<EOF
…
EOF
```

**Comment by gleber** [comment]
Last archive.org snapshot:
https://web.archive.org/web/20160911012143/https://nixos.org/wiki/PulseAudio

**Comment by prusnak** [comment]
There is no Mplayer section in the current Pulseaudio page: https://nixos.wiki/wiki/PulseAudio
