### ISSUE TITLE
Compression support missing from GDAL GeoTIFF driver

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#238882]
### Describe the bug

[LERC is one of the GDAL `buildInputs`](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/gdal/default.nix#L124), and [GDAL is one of the QGIS `pythonBuildInputs`](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/gis/qgis/unwrapped.nix#L57), but `import osgeo.gdal; osgeo.gdal.GetDriverByName("GTiff").GetMetadata()['DMD_CREATIONOPTIONLIST']` doesn't include LERC in the `COMPRESS` option list. Am I looking at the wrong thing, or is this dependency missing in the end result?

The same seems to apply to WEBP. Related: [WEBP support build instructions for Ubuntu 22.04](https://github.com/linz/elevation/blob/13121ef45962529040cbc4fce6ecc8a2dea97fae/docs/tiff-compression/README.md#lerc-support-in-gdalqgis-on-ubuntu-linux-2204-long-term-support-lts)

Cc @palmerj @NixOS/geospatial  

### Steps To Reproduce

1. `nix-shell -p qgis --run qgis`
2. Open the Python console (Ctrl-Alt-p)
3. Run `import osgeo.gdal; osgeo.gdal.GetDriverByName("GTiff").GetMetadata()['DMD_CREATIONOPTIONLIST']`

Alternatively, one level down:

1. `nix-build -A gdal`
2. `./result/bin/gdalinfo --format gtiff`

### Expected behavior

The strings `<Value>LERC</Value>` and `<Value>WEBP</Value>` should appear in the `COMPRESS` option names.

### Notify maintainers

@lsix @sikmir @willcohen

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.1156.ad157fe26e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by imincik** [comment]
@l0b0 ,

I just checked GDAL build messages, and it looks like GDAL is correctly built with LERC. 

If I try `mrf` driver, I can see LERC in the list of available compressions:
```
import osgeo.gdal; osgeo.gdal.GetDriverByName("mrf").GetMetadata()['DMD_CREATIONOPTIONLIST']


"<CreationOptionList>   <Option name='COMPRESS' type='string-select' default='PNG' description='PPNG = Palette PNG; DEFLATE = zlib '>       <Value>JPEG</Value>       <Value>PNG</Value>       <Value>PPNG</Value>       <Value>JPNG</Value>       <Value>TIF</Value>       <Value>DEFLATE</Value>       <Value>NONE</Value>       <Value>LERC</Value>       <Value>ZSTD</Value>   </Option>   <Option name='INTERLEAVE' type='string-select' default='PIXEL'>       <Value>PIXEL</Value>       <Value>BAND</Value>   </Option>\n   <Option name='ZSIZE' type='int' description='Third dimension size' default='1'/>   <Option name='QUALITY' type='int' description='Compression dependent control value, for JPEG best=99, bad=0, default=85'/>\n   <Option name='BLOCKSIZE' type='int' description='Block size, both x and y, default 512'/>\n   <Option name='BLOCKXSIZE' type='int' description='Block x size, default=512'/>\n   <Option name='BLOCKYSIZE' type='int' description='Block y size, default=512'/>\n   <Option name='NETBYTEORDER' type='boolean' description='Force endian for certain compress options, default is host order'/>\n   <Option name='CACHEDSOURCE' type='string' description='The source raster, if this is a cache'/>\n   <Option name='UNIFORM_SCALE' type='int' description='Scale of overlays in MRF, usually 2'/>\n   <Option name='NOCOPY' type='boolean' description='Leave created MRF empty, default=no'/>\n   <Option name='DATANAME' type='string' description='Data file name'/>\n   <Option name='INDEXNAME' type='string' description='Index file name'/>\n   <Option name='SPACING' type='int' description='Leave this many unused bytes before each tile, default=0'/>\n   <Option name='PHOTOMETRIC' type='string-select' default='DEFAULT' description='Band interpretation, may affect block encoding'>\n       <Value>MULTISPECTRAL</Value>       <Value>RGB</Value>       <Value>YCC</Value>   </Option>\n   <Option name='OPTIONS' type='string' description='\n     Compression dependent parameters, space separated:\n       ZSTD - boolean, enable libzstd as final stage, preferred over DEFLATE\n       DEFLATE - boolean, enable zlib as final stage\n       GZ - boolean, for DEFLATE enable gzip headers instead of zlib ones when using zlib\n       RAWZ - boolean, for DEFLATE disable all zlib headers\n       Z_STRATEGY - Z_HUFFMAN_ONLY | Z_FILTERED | Z_RLE | Z_FIXED: restricts DEFLATE and PNG strategy\n       LERC_PREC - numeric, set LERC precision, defaults to 0.5 for int and 0.001 for float\n       V1 - boolean, use LERC V1 (older) format\n       L2_VER - numeric, encode specific version of Lerc, default is library default\n                except for single band or INTERLEAVE=BAND, when it defaults to 2\n       OPTIMIZE - boolean, for JPEG, enables Huffman table optimization\n       JFIF - boolean, for JPEG, disable brunsli encoding\n'/></CreationOptionList>\n"
```

**Comment by imincik** [comment]
> HI @imincik do you see it compiled in for the Geotiff driver? That Victor needs it.
> 
> ```
> 'COMPRESS' in osgeo.gdal.GetDriverByName("GTiff").GetMetadata()['DMD_CREATIONOPTIONLIST']
> ```

No, I don't see LERC compression available for GTiff driver, but I see it present for mrf (as I said above). I don't have any idea why.
