### ISSUE TITLE
Package request: dbeaver-ce

### ISSUE THREAD

**Issue by staticdev** [NixOS/nixpkgs#238899]
**Project description**

DBeaver Community is a free cross-platform database tool for developers, database administrators, analysts, and everyone working with data. It supports all popular SQL databases like MySQL, MariaDB, PostgreSQL, SQLite, Apache Family, and more.

**Metadata**

* homepage URL: https://dbeaver.io/
* source URL: https://github.com/dbeaver/dbeaver
* license: Apache 2.0
* platforms: ALL

**Comment by wegank** [comment]
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=dbeaver
