### ISSUE TITLE
appimage-run: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by MeTheFlea** [NixOS/nixpkgs#238820]
### Describe the bug
Running certain AppImages, such as [Tahoma2d](https://tahoma2d.org/download.html) or [Yuzu](https://github.com/pineappleEA/pineapple-src/releases) fail to launch with the following error:

```console
Cannot load library /nix/store/0ixdrv8hand6fnalahyfm4bmzn6sx638-qtbase-5.15.9-bin/lib/qt-5.15.9/plugins/platforms/libqxcb.so: (/nix/store/0ixdrv8hand6fnalahyfm4bmzn6sx638-qtbase-5.15.9-bin/lib/qt-5.15.9/plugins/platforms/../../../../../cqyd8jhw3kipp2i6rgg38x64s9pvnplm-qtbase-5.15.9/lib/libQt5XcbQpa.so.5: undefined symbol: _ZTI27QPlatformServiceColorPicker, version Qt_5_PRIVATE_API)
QLibraryPrivate::loadPlugin failed on "/nix/store/0ixdrv8hand6fnalahyfm4bmzn6sx638-qtbase-5.15.9-bin/lib/qt-5.15.9/plugins/platforms/libqxcb.so" : "Cannot load library /nix/store/0ixdrv8hand6fnalahyfm4bmzn6sx638-qtbase-5.15.9-bin/lib/qt-5.15.9/plugins/platforms/libqxcb.so: (/nix/store/0ixdrv8hand6fnalahyfm4bmzn6sx638-qtbase-5.15.9-bin/lib/qt-5.15.9/plugins/platforms/../../../../../cqyd8jhw3kipp2i6rgg38x64s9pvnplm-qtbase-5.15.9/lib/libQt5XcbQpa.so.5: undefined symbol: _ZTI27QPlatformServiceColorPicker, version Qt_5_PRIVATE_API)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

Interestingly, this only appears to happen when using the plasma5 DE, with:
```console
services.xserver.displayManager.sddm.enable = true;
services.xserver.desktopManager.plasma5.enable = true;
```
Using another DE like Gnome does not trigger this error.

### Steps To Reproduce
1. Enable plasma5 DE
2. Download [Yuzu](https://github.com/pineappleEA/pineapple-src/releases) AppImage
3. Run `appimage-run ./<downloaded file>`

### Expected behavior
The application launches.

### Additional context
It seems like this issue can be worked around by either using a different DE, or by prepending the `appimage-run` command with `QT_PLUGIN_PATH=/home/<user>/.cache/appimage-run/<hash of extracted AppImage>`:

```console
QT_PLUGIN_PATH=/home/martin/.cache/appimage-run/2545a47879f369ed8df4d5b5bb345b984b012d906a58811b493ec654a73011fb/ appimage-run ./Tahoma2D.AppImage
```

### Notify maintainers
@eduarrrd @K900  @timokau

(Sorry if I've wrongly pinged someone, I'm trying to ping people who've touched the plasma5 package or the appimage-run) 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.05 (Stoat), 23.05.20230619.ad157fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/swbfb53ws0yjjl43n6nlv3gksyr34qlb-source`
```

**Comment by K900** [comment]
Appimages suck, appimages that bundle old Qt versions extra suck, you can unset QT_PLUGIN_PATH if you really want them to work, but please don't.

**Comment by MeTheFlea** [comment]
Ah, setting QT_PLUGIN_PATH to that cache dir specifically was useless, thanks for that information.

**Comment by K900** [comment]
What's happening here is that the AppImage bundles an old version of Qt, and we set QT_PLUGIN_PATH to our new Qt version (and a bunch of other things), and the old Qt version tries to load the new Qt plugins and explodes. Ideally, the appimage would just not leak that into the environment, but alas.

**Comment by MeTheFlea** [comment]
When using a non-plasma DE I guess the newer Qt version is not even in the QT_PLUGIN_PATH so then the AppImage works - am I assuming that correctly?

**Comment by K900** [comment]
Yes, non-Plasma DEs generally don't set QT_PLUGIN_PATH, but Plasma relies on it for discovering its own plugins, and so does most other KDE software.

**Comment by MeTheFlea** [comment]
I see, thanks for the explanation!

**Comment by K900** [comment]
I'm just going to close this because this isn't really a NixOS issue.
