### ISSUE TITLE
overrideDerivation, buildInputs, and buildPython* is awkward

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23897]
I tried today to call something like the following:

```nix
somePythonPackage.overrideDerivation (orig: {
  propagatedBuildInputs = orig.propagatedBuildInputs ++ [ pythonPackages.foo ];
}
```

Can you guess what happened? It wasn't what I expected 😄 It did nothing at all!

Hint: think native

**Comment by FRidh** [comment]
An own kind of override function is I think needed, just as is done with Haskell.

**Comment by dezgeg** [comment]
Doesn't `overrideAttrs` do the right thing here?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by FRidh** [comment]
we have `overridePythonAttrs`.
