### ISSUE TITLE
Python: Cannot import `tkinter`

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#238990]
### Describe the bug / Steps To Reproduce

This fails:

```
$ nix shell --impure --expr 'with builtins.getFlake "nixpkgs"; with legacyPackages.${builtins.currentSystem}; python3.withPackages(ps: [ps.tkinter])' --command python -c "import tkinter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

### Expected behavior

No failure.

### Additional context

Maybe https://github.com/NixOS/nixpkgs/pull/235268 is related. EDIT: On branch `release-23.05` it doesn't fail.

### Notify maintainers

Maybe @wegank or @FRidh can help.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.11 (Tapir), 23.11.20230618.e4bca8e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/grai7z02irhi8yd6k9ccqslkbjddpld3-source`
```

**Comment by wegank** [comment]
> Maybe https://github.com/NixOS/nixpkgs/pull/235268 is related.

I'm not sure: [tk-8_6_13-find-library.patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/tk/tk-8_6_13-find-library.patch) is pretty much the same as [different-prefix-with-tcl.patch](https://github.com/NixOS/nixpkgs/blob/a86e1f5dac8aac6629cacc9ccf99725d082e1f02/pkgs/development/libraries/tk/different-prefix-with-tcl.patch), which was accidentally dropped on the last Tk upgrade.

**Comment by wegank** [comment]
I built Python 3.10.11 on master by modifying `pkgs/development/interpreters/python/default.nix`, the issue was not present. So it's probably related to the 3.10.11 -> 3.10.12 bump.

**Comment by doronbehar** [comment]
> Rebuilt 3.10.12 and the issue was gone.
> 
> Conclusion: the official binary cache is shipping a faulty `python3.override { x11Support = true; }`.

Indeed peculiar! Could you make the extra diff compare the logs?

**Comment by wegank** [comment]
The log on Hydra is at https://hydra.nixos.org/log/xlb9h04hjnari8gncwzdnc1phzn0jg8d-python3-3.10.12.drv:

```
*** WARNING: renaming "_tkinter" since importing it failed: /nix/store/glk21f0vr9lfjjmw6qh0rky9haslhijr-expat-2.5.0/lib/libexpat.so.1: invalid ELF header
```

I'm not able to reproduce it by doing `nix-build -A python310Packages.tkinter.src --check`.

**Comment by doronbehar** [comment]
BTW, perhaps you'd be interested in: https://github.com/NixOS/nixpkgs/pull/239047 .

**Comment by doronbehar** [comment]
I too can't reproduce that warning with `nix build --rebuild` - says output is not deterministic and that outputs differ.

**Comment by natsukium** [comment]
It also seems to happen on python3.11.4 on `x86_64/aargh64-darwin`.
For example, pysimplegui in https://hydra.nixos.org/build/224592959 and async-tkinter-loop in https://github.com/NixOS/nixpkgs/pull/235802/checks?check_run_id=14432073030

**Comment by wegank** [comment]
And that's reproducible on my machine:

```
*** WARNING: renaming "_tkinter" since importing it failed: dlopen(/private/tmp/nix-build-python3-3.11.4.drv-0/Python-3.11.4/build/lib.macosx-11.0-arm64-3.11/_tkinter.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_TclBN_mp_clear'

Following modules built successfully but were removed because they could not be imported:
_tkinter             
```

**Comment by wegank** [comment]
For the Python 3.11 issue on macOS, these lines look suspicious:

https://github.com/NixOS/nixpkgs/blob/13c9bc70606f9544ed21501cf1d5384c1731b77c/pkgs/development/interpreters/python/cpython/default.nix#L269-L271

The patch is only applied on Python 3.{9,10}, and it basically disables detection, if I'm not mistaken:

https://github.com/NixOS/nixpkgs/blob/13c9bc70606f9544ed21501cf1d5384c1731b77c/pkgs/development/interpreters/python/cpython/3.9/darwin-tcl-tk.patch#L9-L12

So I guess a new patch for Python 3.11 is needed, and should probably be applied for all platforms?

**Comment by wegank** [comment]
Opened #239173 for the Python 3.11 issue on macOS.

I'm not sure about the solution for Python 3.10 on Linux, probably abort the build when there's `$out/${python3.sitePackages}/lib-dynload/*_failed.so`? Or just ask @vcunat to retrigger the build?

**Comment by vcunat** [comment]
Rebuild of what build?

**Comment by wegank** [comment]
I suppose rebuilding `python310Packages.tkinter.src` and `python310Packages.tkinter` on `x86_64-linux` should be sufficient.

**Comment by FRidh** [comment]
> I suppose rebuilding `python310Packages.tkinter.src` and `python310Packages.tkinter` on `x86_64-linux` should be sufficient.

There is no explicit job for `python310Packages.tkinter.src`.

**Comment by vcunat** [comment]
I don't think it's really possible to trigger a rebuild for successful builds.  The best I can think of is pushing a inconsequential change that still causes a change in hash.

**Comment by doronbehar** [comment]
BTW I'll note that the issue is not present now according to my tests.

**Comment by vcunat** [comment]
OK, let's close until confirmed again.

**Comment by AngryAnt** [comment]
In that case, shouldn't this be added to nixpkgs tests as a canary?

**Comment by doronbehar** [comment]
Here's an attempt: https://github.com/NixOS/nixpkgs/pull/247868

**Comment by hakan-demirli** [comment]
@doronbehar I can reproduce this issue in a python venv. Global or shell installation works.
* If I install the tkinter for all it works:
```nix
      (python310.withPackages (ps: with ps; [ pandas tkinter ]))
```
* If I install it for venv it fails. I can install other packages such as pandas or Pillow. Only tkinter is failing, hence I think this is a bug.
```nix
      ...
      python310 # only python, venv for packages
      ...
```
```bash
$ >
      python -m venv .venv
      source .venv/bin/activate
```
After that install tkinter either using requirements.txt or directly with pip.
```bash
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.11 (Tapir), 23.11.20230827.cf2004a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by doronbehar** [comment]
> After that, install tkinter either using requirements.txt or directly using pip.

How do you do that? That's the most interesting part. Because https://pypi.org/project/tkinter/ is 404.

**Comment by hakan-demirli** [comment]
Yea you are right. I just learned tk is not tkinter but tensorflowkit. I should have been more careful. Even the error path points to /nix/store and not the virtual environment. I am sorry for bothering you.

**Comment by andreivolt** [comment]
@hakan-demirli install Nix, create `shell.nix` in the repo, and run `nix-shell`, it'll just work:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  pythonWithTk = pkgs.python3.buildEnv.override {
    extraLibs = with pkgs.python3Packages; [ 
      tkinter
      pip
      virtualenv
    ];
    ignoreCollisions = true;
  };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    pythonWithTk
    clang
    llvmPackages.libcxx
    cmake
    pkg-config
    ffmpeg
    git
    tcl
    tk
  ];

  shellHook = ''
    export VENV_DIR="$PWD/.venv"
    if [ ! -d "$VENV_DIR" ]; then
      ${pythonWithTk}/bin/python -m venv $VENV_DIR
      source $VENV_DIR/bin/activate
      pip install --upgrade pip setuptools wheel
    else
      source $VENV_DIR/bin/activate
    fi

    export PYTHONPATH="${pythonWithTk}/${pkgs.python3.sitePackages}:$PYTHONPATH"
    export TCL_LIBRARY="${pkgs.tcl}/lib/tcl${pkgs.tcl.version}"
    export TK_LIBRARY="${pkgs.tk}/lib/tk${pkgs.tk.version}"

    pip install --upgrade "onnxruntime-silicon==1.13.1"

    if [ -f requirements.txt ]; then
      pip install -r requirements.txt --upgrade
    fi
  '';
}
```

**Comment by benedikt-weyer** [comment]
Thank you @andreivolt ! That was exactly what I was looking for. I modified your version a bit and it's a bit more minimalistic and works with python 3.13:

``` nix
# Import nixpkgs from the unstable channel
{ pkgs ? import (fetchTarball "https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz") {} }:

let
  # Define a Python 3.13 environment with Tkinter support
  pythonWithTk = pkgs.python313.withPackages (ps: with ps; [
    pip
    tkinter
  ]);
in
pkgs.mkShell {
  # Specify the packages needed in the development environment
  buildInputs = with pkgs; [
    pythonWithTk
    tcl
    tk
  ];

  # Shell initialization script
  shellHook = ''
    export VENV_DIR="$PWD/.venv"

    # create the virtual environment if it doesn't exist
    if [ ! -d "$VENV_DIR" ]; then
      ${pythonWithTk}/bin/python -m venv $VENV_DIR
    fi

    # Activate the virtual environment
    source $VENV_DIR/bin/activate


    # Set up Python and Tcl/Tk paths
    export PYTHONPATH="${pythonWithTk}/lib/python3.13/site-packages:$PYTHONPATH"
    export TCL_LIBRARY="${pkgs.tcl}/lib/tcl${pkgs.tcl.version}"
    export TK_LIBRARY="${pkgs.tk}/lib/tk${pkgs.tk.version}"


    # Install dependencies if requirements.txt exists
    if [ -f requirements.txt ]; then
      pip install -r requirements.txt
    fi


    # Display Python version for verification
    PYTHON_VERSION=$(python --version)
    echo ""
    echo -e "\033[1;32mWelcome to your development environment!\033[0m Running: (\033[1;34m$PYTHON_VERSION\033[0m)"
    '';
  }
```
Maybe usefull or helpfull for someone
