### ISSUE TITLE
Package request: btrfs-assistant

### ISSUE THREAD

**Issue by RMED24** [NixOS/nixpkgs#238909]
**Project description**

 BTRFS Assistant aims to be a utility to make managing BTRFS partitions easier, with tools such as balancing and managing backups through snapper. 

**Metadata**

* homepage URL: https://gitlab.com/btrfs-assistant/btrfs-assistant (They don't have a typical website or homepage)
* source URL: https://gitlab.com/btrfs-assistant/btrfs-assistant
* license: gpl3-or-later
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/232444

**Comment by RMED24** [comment]
Apologies. I searched for surfshark and no results but I forgot to do the same for btrfs assistant. Will close this issue now
