### ISSUE TITLE
branches for channels

### ISSUE THREAD

**Issue by adnelson** [NixOS/nixpkgs#23896]
## Issue description

Nix channel snapshots are a great way to keep your expressions up to date, but being read-only it makes them hard to hack on when something needs to be changed, and without knowing what commit it is, it's hard to PR changes if necessary. For example, as of this writing the current nixpkgs-unstable commit is `26625c9`. I know this only by looking at the effective url of `https://nixos.org/channels/nixpkgs-unstable` -- if there's another solution, I don't know what it is.

 I think it would be a good idea to maintain branches for channels, so that users could clone `nixpkgs` and do something like

```
$ cd nixpkgs
$ git checkout nixpkgs-unstable
$ git pull
```

This would be really helpful for development, and also provide a well-established mechanism for updates/rollbacks/etc.

An alternative, or complementary, approach is to make a tag whenever a channel is released. For example the aforementioned `26625c9` commit might be tagged `nixpkgs-unstable-2017-08-03` or somesuch.

**Comment by edolstra** [comment]
We already have branches for channels in the nixpkgs-channels repo. See https://nixos.org/nixos/manual/index.html#sec-getting-sources.

**Comment by bennofs** [comment]
You can do:

```
$ git remote add channels https://github.com/NixOS/nixpkgs-channels
$ git fetch channels
$ git checkout nixos-unstable
```

**Comment by adnelson** [comment]
OK, I didn't realize that they were in a different remote. Not sure why that is, but thanks! :smile:
