### ISSUE TITLE
rq: build error when checking hashes

### ISSUE THREAD

**Issue by 4e6** [NixOS/nixpkgs#23899]
## Issue description

Got an error trying to install `rq`
Fails on channel nixos-17.03 as well as on master

```
nix-env -i rq
...
output path ‘/nix/store/6x2bagn4ijyhg1am3pi57cdy5hz2gb61-rq-0.9.2-fetch’ has r:sha256 hash ‘0y6y66mfnlpks7bhvf6kdp5smnl0jfglq4iv2z49wjr6dv10c65p’ when ‘1pci9iwf4y574q32b05gbc490iqw5i7shvqgb1gblchrihvlkddq’ was expected
cannot build derivation ‘/nix/store/mdz29fvczm0mqybk35snynx76bifk4cr-rq-0.9.2.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/mdz29fvczm0mqybk35snynx76bifk4cr-rq-0.9.2.drv’ failed
```

### Steps to reproduce

```
nix-env -i rq
```

## Technical details

* System: Arch Linux 4.10.1-1-ARCH
* Nix version: 1.11.7
* Nixpkgs version: "17.03beta320.ade5837"

**Comment by zimbatm** [comment]
Note that the package is marked as broken in nixpkgs. @aristidb is the maintainer.

**Comment by 4e6** [comment]
Oh, I see, I totally missed that. 

When the hashes are fixed, it fails later during v8-rs compilation. I also tried to bump version but wasn't able to get Cargo dependencies right.

Since the package is marked broken, it's not an issue anymore.

**Comment by zimbatm** [comment]
Yeah feel free to fix it but yeah, it's probably not straight-forward :)
