### ISSUE TITLE
Package request: CLBlast

### ISSUE THREAD

**Issue by gunar** [NixOS/nixpkgs#239031]
**Project description**

> CLBlast is a lightweight, performant and tunable OpenCL BLAS library written in C++11. It is designed to leverage the full performance potential of a wide variety of OpenCL devices from different vendors, including desktop and laptop GPUs, embedded GPUs, and other accelerators. CLBlast implements BLAS routines: basic linear algebra subprograms operating on vectors and matrices.

I'd like to be able to use CLBlast on NixOS so I can run [whisper.cpp on my Thinkad X1 Nano Gen2 on the GPU (more efficient) instead of on the CPU](https://github.com/ggerganov/whisper.cpp#opencl-gpu-support-via-clblast).

**Metadata**

* homepage URL: https://github.com/CNugteren/CLBlast
* source URL: https://github.com/CNugteren/CLBlast
* license: Apache
* platforms: unix, linux, darwin

**Comment by natsukium** [comment]
CLBlast has already added in #234020

**Comment by gunar** [comment]
Indeed it has. Thank you.
