### ISSUE TITLE
Request: tmpOnTmpfs size option

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#23912]
## Issue description
`boot.tmpOnTmpfs` defaults to the tmpfs defaults: 50% of RAM.
What do you think about making it configurable? tmpfs has no real overhead when not used and just like normal memory, it can be swapped out if memory gets tight.

### Motivation:
I have a hp microserver n40l with 8GB RAM and i can't rebuild the linux kernel with `nixos-rebuild boot -j 1 -I nixpkgs=$HOME/nixpkgs`, as my /tmp fills up even though i have a bit of RAM left.

**Comment by ikervagyok** [comment]
I know i can do this instead (copied from one of my machines):

```
let
  tmpfsOpts = [ "nosuid" "nodev" "relatime" "size=14G" ];
in
...
  fileSystems."/tmp" = {
    fsType = "tmpfs";
    device = "tmpfs";
    options = tmpfsOpts;
  };
...
```

but I don't like having a nice option for this, and still using the "manual" way.

**Comment by timokau** [comment]
@ikervagyok since you have already found a solution for this, have you considered opening a PR?

**Comment by ikervagyok** [comment]
@timokau i don't find that conversation atm (discussion was probably on irc?). anyway, my "fix" was too liberal in
1. what it accepts as input (bool and string) and
2. it didn't reuse the original systemd template/unit file.
feel free to reuse this as a basis for your own pr or give me pointers how i could do that in a few lines and without messing around with the `fileSystems."/tmp"` option.

maybe i'll try a pr with the `fileSystems."/tmp"` solution, but thats more of a hack. thanks for the reminder, that this is still an issue.

**Comment by timokau** [comment]
Why is `fileSystems."/tmp"` a hack?

**Comment by ikervagyok** [comment]
@timokau because it doesn't automatically get new features from the upstream systemd unit file.
that was the main part of point two. whenever systemd gets a new feature, the unit files in every distro get automatic upgrades - just nixos would need manual intervention.

**Comment by timokau** [comment]
Oh I wasn't aware how this is currently done. Is it realistic to expect new "features" for a filesystem mount? Maybe my imagination is lacking, but I have no idea what that might be.

**Comment by ikervagyok** [comment]
@timokau see https://github.com/NixOS/nixpkgs/pull/27189

**Comment by falsifian** [comment]
This still seems like a desirable feature, especially since nix builds happen in /tmp.

**Comment by alexeymuranov** [comment]
still desirable

**Comment by alexeymuranov** [comment]
still desirable

**Comment by pinpox** [comment]
Any activity on this? I've a build failing, even though boot.tmpOnTmpfs is set to false
```
^[error: builder for '/nix/store/vmvgis89265yki26i34750m3gr698dkd-wezterm-nightly-20210502-nightly.drv' failed with exit code 101;
       last 10 log lines:
       > warning:   379 | }
       > warning:       | ^
       > warning: compilation terminated.
       > warning: harfbuzz/src/hb-ot-layout.cc:1991:1: fatal error: error writing to /build/ccYnkJ0r.s: No space left on device
       > warning:  1991 | }
       > warning:       | ^
       > warning: compilation terminated.
       >
       > LLVM ERROR: IO failure on output stream: No space left on device
       > error: build failed
       For full logs, run 'nix log /nix/store/vmvgis89265yki26i34750m3gr698dkd-wezterm-nightly-20210502-nightly.drv'.
       note: build failure may have been caused by lack of free disk space
error: 1 dependencies of derivation '/nix/store/ybhcyd5slkgfmmb4r3y2hiwrr0zypayq-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/38zidvjdgdip4wqxyx1ikm744h82zhvs-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9zmhgaigdy9pnfj1281h9zv1qgpiq2vd-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rwzb0p96mmm5j5a3qq5c5xvn65jnvjdp-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w6r75i6z5hb1ck3cblx4rr13xhgn5mzh-nixos-system-kartoffel-21.05.20210506.6358647.drv' failed to build
warning: Git tree '/var/src/machine-config' is dirty
building the system configuration...
warning: Git tree '/var/src/machine-config' is dirty
building '/nix/store/vmvgis89265yki26i34750m3gr698dkd-wezterm-nightly-20210502-nightly.drv'...
^C

<pinpox/nixos> on  main [±] via 🌙 took 3m10s
✦ ×  df -h /tmp
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/disk/by-uuid/8dcfb3f0-4dba-4c32-af96-84024706ff76  472G  128G  321G  29% /
```

**Comment by kirillrdy** [comment]
@pinpox  have you tried increasing size of /tmp ?
eg 

```
services.logind.extraConfig = ''
    RuntimeDirectorySize=20G
  '';
```

**Comment by pinpox** [comment]
@kirillrdy Where is the RuntimeDirectory located? I thought that should be `/tmp`, which on my system is pretty big:
```
✦ ×  df -h /tmp
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/disk/by-uuid/8dcfb3f0-4dba-4c32-af96-84024706ff76  472G  128G  321G  29% /
```

I'll try to add that option to my config, not sure I fully understand what it does though, is it documented in more detail somewhere?_

**Comment by kirillrdy** [comment]
sorry i made mistake in my post when i mentioned `/tmp` because its really not that one

on my system it's 
```
tmpfs            20G   68K   10G   1% /run/user/1000
```

You can look up systemd documentation for RuntimeDirectory

**Comment by anniekatlin** [comment]
> @pinpox have you tried increasing size of /tmp ? eg
> 
> ```
> services.logind.extraConfig = ''
>     RuntimeDirectorySize=20G
>   '';
> ```

```nix
services.logind.extraConfig = ''
  RuntimeDirectorySize=20G
  RuntimeDirectoryInodesMax=1M  
  '';
```

**Comment by jamesward** [comment]
There is now an option for this:
```
boot.tmpOnTmpfsSize = "5%"
```

**Comment by PedroRegisPOAR** [comment]
For those who end up here, my problem was that for some reason `boot.tmpOnTmpfs` was set to `false`.

```bash
  boot.tmpOnTmpfs = true;
  boot.tmpOnTmpfsSize = "95%";
```

Tip: just change the value `95%` and inspect the result with `df -h`.
