### ISSUE TITLE
vector: broken geoip support

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#239127]
### Steps To Reproduce
1. Definie [enrichment_tables](https://vector.dev/docs/reference/configuration/global-options/#enrichment_tables.geoip) with `type: geoip` in configuration
2. ...
3. ...

### Notify maintainers

@thoughtpolice 
@happysalada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by happysalada** [comment]
Can you give us a bit more detail ?
What does your config look like and what does the error say ?

**Comment by genofire** [comment]
that the geoip.so could not be found
