### ISSUE TITLE
buildNpmPackage / prefetch-npm-deps doesn't support proxy

### ISSUE THREAD

**Issue by stasjok** [NixOS/nixpkgs#239190]
### Describe the bug
`prefetch-npm-deps` doesn't support proxy. I have `http_proxy` and `https_proxy` environment variables defined, but it doesn't work which make it impossible to build something in closed corporate environments. Also I suspect that `NIX_SSL_CERT_FILE` environment (ca-certificates bundle) would not work also.

### Steps To Reproduce
1. A PC without direct Internet access. Only proxy is available for Internet access.
2. `http_proxy`, `https_proxy`, `NIX_SSL_CERT_FILE` environment variables are defined for nix-daemon.service.
3. Build any `buildNpmPackage` package. Or run `nix run nixpkgs#prefetch-npm-deps -- package-lock.json` inside some npm repository.

### Expected behavior
Npm dependencies successfully fetched.

### Screenshots
I've got an error "**Network is unreachable (os error 101)**". Example failed build log:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/pgqsk8sdh6gg9kdqi8iijhw6sng6qwiv-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
node_modules/@babel/cli
node_modules/is-boolean-object
node_modules/@babel/plugin-transform-destructuring
node_modules/babel-plugin-dynamic-import-node
node_modules/string-width
node_modules/path-parse
Error: https://registry.npmjs.org/@babel/cli/-/cli-7.16.0.tgz: Connection Failed: Connect error: Network is unreachable (os error 101)

Caused by:
    Network is unreachable (os error 101)
```

### Additional context
Most of the fetchers work via proxy which intercepted ssl. This one not. I think all fetchers should support it.

### Notify maintainers

@winterqt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.18-59.34-default, SLES, 15-SP3, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs-22.05pre338599.f6e14b6ada8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by lilyinstarlight** [comment]
Thank you for this report! It's a known problem, but we did not yet have an open issue for it, so this will be good for tracking

I was hoping we can swap out `ureq` for `isahc`, which uses libcurl and should automatically handle that, but last I touched my branch for that, it was having TLS cert validation issues

I'll hopefully get to this sometime in the next few weeks, unless someone else wants to work from my isahc branch and get it working before me (my work-in-progress commit is at https://github.com/lilyinstarlight/nixpkgs/commit/3b524a7f485c0071240b166f5d4f5f10da1f5b5c)
