### ISSUE TITLE
ucx: enableCuda in an overlay causes infinite recursion

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#239182]
### Describe the bug

A regression in the `config.cudaSupport = true` package set. Affected attributes:

0: "blender"​
1: "colmapWithCuda"​
2: "cudaPackages.cuda_compat"
3: "cudaPackages.cutensor"
4: "cudaPackages.libcudla"
5: "python3Packages.jax"
6: "python3Packages.jaxlib"
7: "python3Packages.tensorflowWithCuda"
8: "python3Packages.torch"
9: "python3Packages.torchvision"
10: "tts"

Cf. https://hercules-ci.com/github/SomeoneSerge/nixpkgs-cuda-ci/jobs/4832 for logs

Probably caused by the 11.7 -> 11.8 update

### Notify maintainers

@NixOS/cuda-maintainers

**Comment by ConnorBaker** [comment]
Will take a look shortly -- that's odd!

I was able to build blender just now, will try the others soon.

**Comment by ConnorBaker** [comment]
Looks like `cuda_compat` is an ARM only library: https://github.com/NixOS/nixpkgs/blob/437d2a8aac9e3b1f35eff77cd0bb03efca7afd96/pkgs/development/compilers/cudatoolkit/redist/manifests/redistrib_11.8.0.json#L38-L48

**Comment by ConnorBaker** [comment]
@SomeoneSerge I think I figured out the PyTorch failure. Not sure about the others/unable to reproduce.

I suspect that your CI managed to grab a commit in-between when CUDA 11.8 was made the default (which broke dynamically linked Magma due to the binary size increase) and when I made Magma default to static builds for CUDA.

**Comment by SomeoneSerge** [comment]
Ok, it seems that the original issue does not belong in nixpkgs, but I don't know how to move issues between repos.
What is a nixpkgs issue, is that `(import <nixpkgs> { overlays = [ (final: prev: { ucx = prev.ucx.cudaSupport = true; }) ]; }).ucx` is an infinite recursion, because of:

https://github.com/NixOS/nixpkgs/blob/d409d42ce7d2f863dddbf19c12c6ccc989a637d6/pkgs/development/compilers/cudatoolkit/common.nix#L127-L131

This is exactly what happens at 
https://github.com/SomeoneSerge/nixpkgs-cuda-ci/blob/8b461ff67bae99323d1b8913f89f387aa92bc020/nix/overlays.nix#L32-L34

**Comment by SomeoneSerge** [comment]
Temporary work-around is to update the overlays like so:

```
        cudaPackages = prev.cudaPackages.overrideScope' (fin: pre: {
          cudatoolkit = pre.cudatoolkit.override { ucx = final.ucx.override { enableCuda = false; }; };
        });


        ucx = prev.ucx.override {
          enableCuda = true;
        };
```
Mid-term, we can update `ucx` to use the redist packages.
The longer-term solution is to deprecate `cudaPackages.cudatoolkit` since it's a bootstrap nightmare

**Comment by SomeoneSerge** [comment]
@ConnorBaker thank you a lot for all the tests you've run!

**Comment by SomeoneSerge** [comment]
This must've been addressed by https://github.com/NixOS/nixpkgs/pull/271078 or https://github.com/NixOS/nixpkgs/pull/272063
