### ISSUE TITLE
Program linked to the wrong libc.so.6 after updated nixpkgs flake input to 23.05 (version `GLIBC_ABI_DT_RELR' not found)

### ISSUE THREAD

**Issue by samchan0221** [NixOS/nixpkgs#239111]
### Describe the bug
When I upgraded to nixpkgs to 23.05, the following happens to my rust program which was fine in 22.11.
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/demo`
target/debug/demo: /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libdl.so.2)
target/debug/demo: /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libpthread.so.0)
```

And then I looked at the library we linked to and maybe the library we want to linked to.

```
$ readelf -sW /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6 | grep GLIBC_ABI
<empty-output>
```

```
$ readelf -sW /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6 | grep GLIBC_ABI
   814: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS GLIBC_ABI_DT_RELR
  6589: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS GLIBC_ABI_DT_RELR
```

Is there something wrong with the linker?

### Steps To Reproduce
run my minimal repo:  https://github.com/samchan0221/nix-reqwest-demo

### Expected behavior
It should run, maybe the linker should use the glibc-2.37 instead of 2.25?

### Additional context
For less noise I commented out all my rustc flags in ~/.cargo/config.toml

### Notify maintainers

don't know if I @ the right person.
@amjoseph-nixpkgs

### Metadata
Channels should not matter because I'm using flake. But I'll put it there as well.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, Ubuntu, 20.10 (Groovy Gorilla), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(sam_chan): `"nixpkgs-22.11.tar.gz, rust-overlay"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by samchan0221** [comment]
Issue solved by using `rustls` for reqwest btw, but I'd still leave this issues open because using `rustls` is just making the program independent of `glibc` but not actually solving the original problem.

**Comment by amjoseph-nixpkgs** [comment]
> using `rustls` is just making the program independent of `glibc`

Are you sure about that?  I find it hard to believe that the final result doesn't use libc at all...

**Comment by amjoseph-nixpkgs** [comment]
Are you able to reproduce this using a build that occurs inside a derivation?  Ideally one for which you can post a `nix` expression that reproduces the issue.

Your issue shows you running `cargo` from the command line -- which, frankly, is a strategy laden with landmines.  `cargo` will happily look all over the filesystem for `libc`s to link with; nothing is constraining its view of what are/aren't acceptable paths.

**Comment by samchan0221** [comment]
> Are you able to reproduce this using a build that occurs inside a derivation? Ideally one for which you can post a `nix` expression that reproduces the issue.
> 
> Your issue shows you running `cargo` from the command line -- which, frankly, is a strategy laden with landmines. `cargo` will happily look all over the filesystem for `libc`s to link with; nothing is constraining its view of what are/aren't acceptable paths.

You're right, when I build and run it as a derivation like this, it doesn't reproduce the error. I'm still too naive on nix. Thank you!
```nix
naersk'.buildPackage ({
  name = "demo";
  src = ./demo;
  buildInputs = [
    openssl
    pkg-config
  ];
});
```
