### ISSUE TITLE
Package request: libmagic1

### ISSUE THREAD

**Issue by royaldevops** [NixOS/nixpkgs#239263]
sudo apt-get install libmagic1
* platforms: unix, linux, darwin, ...

**Comment by emilytrau** [comment]
libmagic is available as part of the [file](https://search.nixos.org/packages?channel=23.05&show=file&from=0&size=50&sort=relevance&type=packages&query=file) package

**Comment by royaldevops** [comment]
@emilytrau Its worked thanks.

**Comment by basavaraja-v** [comment]
check out working replit https://replit.com/@royaldevops/pymagicexample#main.py
