### ISSUE TITLE
Package webapp-manager

### ISSUE THREAD

**Issue by StephanJ91** [NixOS/nixpkgs#239218]
Run websites as if they were apps.

Utility to run websites as apps.

**Metadata**

* homepage URL: https://github.com/linuxmint/webapp-manager
* source URL: https://github.com/linuxmint/webapp-manager
* license: gplv3
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/212089 and https://github.com/NixOS/nixpkgs/issues/217927

**Comment by das-g** [comment]
Closing as duplicate of #212089.
