### ISSUE TITLE
python3Packages.torch: incorrect pybind option used during build

### ISSUE THREAD

**Issue by ConnorBaker** [NixOS/nixpkgs#239215]
### Describe the bug

Instead of setting `USE_SYSTEM_PYBIND11`, we set `USE_SYSTEM_BIND11`:

https://github.com/NixOS/nixpkgs/blob/49b66bd9ef03f97e13b76846a562207c627e790f/pkgs/development/python-modules/torch/default.nix#L223-225

https://github.com/pytorch/pytorch/blob/0d653730ce4314c4c48da0e336c1e1c6259ada28/CMakeLists.txt#L404

**Comment by breakds** [comment]
I suspect that this is related: when I create a python environment with both `torch` and `pybind11` in it:

```nix
  packages = let pythonDevEnv = python3.withPackages (pyPkgs: with pyPkgs; [ torchWithCuda pybind11 ]);
```

I am running into a collision like this:

```
warning: creating dangling symlink `/nix/store/cbzl659i5b86jdn8iwibjpz1pr1ymvqj-python3-3.10.11-env//include/python3.10/python3.10m' -> `/nix/store/lwzzgbnj41d657lpxczk
6l5f7d5zcnj1-python3-3.10.11/include/python3.10/python3.10m' -> `../python3.10m'
error: collision between `/nix/store/1wan18dqk50qs3a6mna4lnr3wlwh62xc-python3.10-torch-2.0.1-dev/include/pybind11/cast.h' and `/nix/store/m78gq5l1bnpb0q5q14pxbdcq37vpik
ix-python3.10-pybind11-2.10.4/include/pybind11/cast.h
```

The hypothesis is that torch was using its own pybind11 instead of the "system" pybind11, leading to this collision.

**Comment by breakds** [comment]
Confirmed that by having the overlay with

```nix
      pytorchWithCuda = python-prev.pytorchWithCuda.overrideAttrs (oldAttrs: {
        USE_SYSTEM_PYBIND11 = true;
      });
```

The collision issue is gone. Is there any caveats that I should pay attention to before submitting a PR for this?

**Comment by ConnorBaker** [comment]
@breakds not that I'm aware of -- I should be able to merge it fairly quickly if you do, just tag me as a reviewer and I'll get to it ASAP.

**Comment by breakds** [comment]
Sure, I have created https://github.com/NixOS/nixpkgs/pull/250632 
It seems that I cannot assign reviewers at this moment.
