### ISSUE TITLE
cannot coerce a set to a string at nixos/modules/system/boot/systemd-lib.nix:65:8

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#23921]
## Issue description
Got error:
```
cannot coerce a set to a string at .../nixos/modules/system/boot/systemd-lib.nix:65:8
```
when trying to override `serviceConfig.Type` attribute:
```
systemd.services.tomcat.serviceConfig.Type = lib.mkForce "forking";
```
Inspecting source shows that some warning occured and warning generation crashed.
Inspecting the warning shows that ` "Systemd ${group} field ${name} cannot have value ${attr.${name}}.";`
But `"forking"` is a normal service type.

Looks like `mkForce` cannot be used here, which is very unintuitive.

## Technical details

* System: 17.03, was on 16.09 and 16.03 too

**Comment by copumpkin** [comment]
I'm guessing this is because `serviceConfig` isn't a submodule in the current systemd module, which prevents us from using module-like machinery like `mkForce` in it (as well as not giving us merge behavior and other niceties). Would be nice to convert it into a submodule...

**Comment by jb55** [comment]
I just hit this today when trying to override openvpn's `serviceConfig.Type`. Overriding `ExecStart` seemed to work though. As a workaround I had to `mkForce` on the entire `serviceConfig`.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by danbst** [comment]
should be fixed with https://github.com/NixOS/nixpkgs/pull/41446
