### ISSUE TITLE
Package request: dool

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#239275]
**Project description**

> Dool is a Python3 compatible fork of [Dstat](https://github.com/dagwieers/dstat).
> 
> After Dag Wieers ceased development of Dstat I forked the project to continue development.

**Metadata**

* homepage URL: https://github.com/scottchiefbaker/dool
* source URL: https://github.com/scottchiefbaker/dool
* license: gpl3
* platforms: linux

**Comment by figsoda** [comment]
#239279
