### ISSUE TITLE
Update request: gnomeExtensions.desktop-icons-ng-ding

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#239373]
- Package name: `gnomeExtensions.desktop-icons-ng-ding`
Please update: `gnomeExtensions.desktop-icons-ng-ding` to the latest version on `nixos-unstable`
Current version has bug, more details here:
https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/288
Could you check? @piegames @piegamesde

**Comment by piegamesde** [comment]
#246866
