### ISSUE TITLE
770 line incomprehensible error message

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#239351]
**Describe the bug**

I want to apply for the award for the worst error message with this one.

https://gist.github.com/davidak/e91d0eb63c002ca0afcc5d2d75fa8432

The error message is about 770 lines long, mentions files i haven't touched and error at the end does not make sense to me.

>error: evaluation aborted with the following error message: 'unsupported platform for the pure Linux stdenv'

I used `--system i686-linux`, so that is not supported?

@trofi said in chat:

>It tells that nixpkgs does not have i686-linux bootstrap binaries for musl libc.

**Steps To Reproduce**

This produces the same error, easier, but the messages are ordered the opposite way for some reason. The error is on the top instead of the bottom.

`nix eval -f '<nixpkgs>' pkgsMusl.hello --argstr system i686-linux --show-trace`

**Expected behavior**

Short and clear error message i can act on.

**`nix-env --version` output** nix-env (Nix) 2.11.1

**Additional context**

It's fun rebuilding every package from staging.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
Since i686 gets limited support, I think we can close this.
