### ISSUE TITLE
Package request: Polonium

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#239369]
**Project description**
"An (unofficial) successor to Bismuth built on KWin 5.27."

Now that Bismuth is being [deprecated](https://github.com/Bismuth-Forge/bismuth/issues/471#issuecomment-1410969462) it would nice to package this newer tiling extension that is in development.

**Metadata**

* homepage URL: https://zeroxoneafour.github.io/polonium/
* source URL: https://github.com/zeroxoneafour/polonium
* license: `mit`
* platforms: `linux`

**Comment by Alanazane** [comment]
Just noticed the corresponding PR has been merged, so I think this can be closed as completed :partying_face:
Thank you for adding this!

**Comment by ciferkey** [comment]
Really appreciate this getting in! Are there any plans to back port it to 23.11?
