### ISSUE TITLE
Avidemux startup error, missing library (libADM_coreVideoCodec6.so)

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#239424]
### Describe the bug
[avidemux](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/avidemux/default.nix) could not be started since a few days/weeks. (Worked well before).

### Steps To Reproduce
1. nix-shell -p avidemux
2. avidemux
3. message: avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory

### Expected behavior
The application starts without any problems, as it does some days (and `nixos-rebuild switch --upgrade`) cycles before.

### Additional context
I sadly have no idea, since when the error occurs exactly, and why. Because the package itself wasn't touched for a while:
https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/applications/video/avidemux/default.nix
and it definitely worked with this last [commit](https://github.com/NixOS/nixpkgs/commit/a5a292c7a82c694129c1045a4ee8a5078db37d71). So something other have to be changed, or it is just on my side. Hopefully someone could verify it the 'steps to reproduce' works for other people?

I searched for the missing library in the path where it seems to be missed:
"**/nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1**/bin/avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory"
and found it two times:
* /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib/libADM_coreVideoEncoder6.so (symlinked from lib64)
* /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib64/libADM_coreVideoCodec6.so

### Notify maintainers
@abbradar 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 23.11 (Tapir), 23.11pre496992.e603dc5f061`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels({user}): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Thanks in advance for any support ❤️

**Comment by revuwa** [comment]
Tried:
`sudo nix store repair /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1`
to enforce rebuild the package, and after that by override an attribute inside my configuration.nix, which let avidemux recompile completely. With the same result/error.

Grateful for any hint.

**Comment by mgurlitz** [comment]
I used `git bisect` to identify https://github.com/NixOS/nixpkgs/pull/223861 as the possible breaking change, and as you noticed avidemux seems to be expecting the missing library in its lib64 directory.

I'm not sure how to fix the derivation, but setting `LD_LIBRARY_PATH` to  /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib/ should work. For example: `LD_LIBRARY_PATH=$(dirname $(readlink -f $(which avidemux)))/../lib/ avidemux`

**Comment by revuwa** [comment]
> I used `git bisect` to identify #223861 as the possible breaking change, and as you noticed avidemux seems to be expecting the missing library in its lib64 directory.
> 
> I'm not sure how to fix the derivation, but setting `LD_LIBRARY_PATH` to /nix/store/4m7z30fmc4pkivr55ww84sjpqxy4gppi-avidemux-2.8.1/lib/ should work. For example: `LD_LIBRARY_PATH=$(dirname $(readlink -f $(which avidemux)))/../lib/ avidemux`

Thanks for looking into this. 💕
In my case `which avidemux` points to `/run/current-system/sw/`, and under its `lib` folder, the missing lib doesn't exists.

I tried setting the environment variable over my configuration.nix like this:
```
environment.variables = {
LD_LIBRARY_PATH = "${lib.getLib pkgs.avidemux}/lib";
};
```

Whith this result:
```
$ set | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH /nix/store/jdzg2ghp71gg07yn3cvwdp66fgc5z8pd-avidemux-2.8.1/lib
```
(Also tried:  `[...]-avidemux-2.8.1/lib/`).

But still with the same result:
`/nix/store/jdzg2ghp71gg07yn3cvwdp66fgc5z8pd-avidemux-2.8.1/bin/avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory`

Thanks again, it sounded promising. 🚀

**Comment by revuwa** [comment]
Short summary, because in the meanwhile I know that other people have the same issue with unstable:
`$ nix run nixpkgs#avidemux`
/nix/store/jdzg2ghp71gg07yn3cvwdp66fgc5z8pd-avidemux-2.8.1/bin/avidemux: error while loading shared libraries: libADM_coreVideoCodec6.so: cannot open shared object file: No such file or directory

But stable (23.05) works like a charm:
`$ nix run nixpkgs/nixos-23.05#avidemux`

If someone is searching for a workaround...

**Comment by Pauan** [comment]
@mgurlitz I can confirm that `env LD_LIBRARY_PATH=$(dirname $(readlink -f $(which avidemux)))/../lib/ avidemux` does work.

**Comment by mgurlitz** [comment]
I tried messing with `patchelf` and `makeWrapper` to fix the issue but wasn't able to. When I run `strace` on the broken `avidemux`, it looks for these .so files in many directories, but I was only able to control this search using `LD_LIBRARY_PATH`.

If you want to embed that workaround in an overlay for now, I ended up using this:

```
final: prev:
{
  avidemux = prev.avidemux.overrideAttrs (oldAttrs: {
    buildCommand = oldAttrs.buildCommand + ''
      mv $out/bin/avidemux $out/bin/avidemux3
      echo 'LD_LIBRARY_PATH=$(dirname $(readlink -f $(which avidemux3)))/../lib/ avidemux3 "$@"' >> $out/bin/avidemux
      chmod +x $out/bin/avidemux

      mv $out/bin/avidemux3_cli $out/bin/avidemux3_cli_old
      echo 'LD_LIBRARY_PATH=$(dirname $(readlink -f $(which avidemux3_cli)))/../lib/ avidemux3_cli_old "$@"' >> $out/bin/avidemux3_cli
      chmod +x $out/bin/avidemux3_cli
      '';
  });
}```

**Comment by revuwa** [comment]
I'm so sorry for my https://github.com/NixOS/nixpkgs/issues/239424#issuecomment-1611761675 whilte this seems to work, but I forgot that I've wrapped avidemux with firejail. 🙄

So the workarounds from https://github.com/NixOS/nixpkgs/issues/239424#issuecomment-1611540248 and https://github.com/NixOS/nixpkgs/issues/239424#issuecomment-1629630745 works for me, too (without firejail wrap).

For those who're interested in the firejail-wrap, the following works for me:
```
firejail = {
  enable = true;
  wrappedBinaries = {
    "avidemux" = {
      executable = "${lib.getBin pkgs.avidemux}/bin/avidemux";
      extraArgs = [ "--env=QT_QPA_PLATFORM=xcb" "--env=LD_LIBRARY_PATH=${lib.getLib pkgs.avidemux}/lib"]
    };
  };
};
```
Very big thanks to all of you 🥰
