### ISSUE TITLE
vscode-extensions.vadimcn.vscode-lldb: python interpreter fails with invalid pathname on module load

### ISSUE THREAD

**Issue by hcsch** [NixOS/nixpkgs#239403]
### Describe the bug
The python interpreter fails to be set up during the first debugging session of a given VSCode window (afterwards it's still broken, but it won't be restarted from what I can tell). The following message is printed into the "LLDB" extension output:
```
[ERROR codelldb::debug_session] Initialize Python interpreter: Error:  Fail
    Error Message:
    error: module importing failed: invalid pathname
```

With a broken python interpreter neither pretty-printers (e.g. for Rust `String`s) nor conditional breakpoints work. This makes debugging quite a lot harder, as you for example can't easily inspect `String`, or `Vec` contents anymore, and you also can't break only when a given `String` variable has a certain value. Basic debugging, i.e. stopping on regular breakpoints, stepping through code, etc. still works though.

### Steps To Reproduce
1. Enable VSCode (in my case VSCodium) with home-manager, using the `vadimcn.vscode-lldb` and `rust-lang.rust-analyzer` extensions.
2. Start debugger for a Rust binary or test that uses a `String` variable with a breakpoint set so it can be observed
3. Observe not pretty-printed `String` in variables section
4. Open "Output" pane and switch to "LLDB", the above error message will be displayed there

### Expected behavior
The python interpreter starts successfully, without errors, and is available for use with pretty-printers and conditional breakpoints.

### Additional context
The issues has only started appearing since a week to at most a month or so. I have not yet gotten around to bisecting

### Notify maintainers

@nigelgbanks 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 23.11 (Tapir), 23.11.20230622.e603dc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MichaelPachec0** [comment]
I have looked at the package and have fixed it locally (tested using neovim + dap and &str's are now deref'ed and show the underplaying u8 slice), will see about sending in a pr tomorrow.
