### ISSUE TITLE
syncthing: device names are not properly escaped

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#239421]
### Describe the bug

Configuring `service.syncthing.devices` with special characters (like `'`) causes the Syncthing service to fail:

```
systemd[1]: Starting Syncthing configuration updater...
cg9zpg3j8j0ank9l6skk1swqc9z1ga94-merge-syncthing-config[6402]: /nix/store/cg9zpg3j8j0ank9l6skk1swqc9z1ga94-merge-syncthing-config: 41: Syntax error: Unterminated quoted string
systemd[1]: syncthing-init.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: syncthing-init.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Syncthing configuration updater.
```

### Steps To Reproduce

```
services.syncthing = {
  enable = true;
  devices."Bob's your uncle".id = "...";
};
```

### Expected behavior

Device names may be any string that Syncthing supports via its UI. Syncthing does support `'`.

### Notify maintainers

(guessing based on `blame`) @ncfavier @bjornfor @Lassulus 

### Metadata

- system: `"armv7l-linux"`
- `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.19700101.dirty`
- nixpkgs @ 3a70dd92993182f8e514700ccf5b1ae9fc8a3b8d

**Comment by ncfavier** [comment]
Could you confirm https://github.com/NixOS/nixpkgs/pull/239427 fixes the issue?

https://github.com/NixOS/nixpkgs/pull/230196 would also fix it

**Comment by Majiir** [comment]
Yep, https://github.com/NixOS/nixpkgs/pull/239427 fixes it. Thanks!
