### ISSUE TITLE
qalculate-qt pulls in a lot of run-time dependencies 

### ISSUE THREAD

**Issue by padhia** [NixOS/nixpkgs#239487]
### Describe the bug
Installing `qalculate-qt` causes large dependencies such as `clang` and `llvm` to be pulled in at run-time

### Steps To Reproduce
1. Install `qalculate-qt`
2. run `nix path-info --recursive --closure-size --size --human-readable /nix/store/*qalculate-qt-4.6.1`
3. observe that some of the large dependencies such as `clang` are pulled in.

### Expected behavior
I'd expect `clang` and `llvm` to be build-time dependencies, and as such shouldn't be needed at run-time

### Additional context
The additional dependencies are being pulled in due to `qtttools`, which itself should be a build dependency. 

FWIW, [Arch package](https://archlinux.org/packages/extra/x86_64/qalculate-qt/) declares `qt6-tools` as a *make* dependency

### Notify maintainers
@alyaeanyx 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.11 (Tapir), 23.11.20230622.e603dc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(xxxxxx): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by alyaeanyx** [comment]
not the maintainer for -qt (@4825764518 is), but I took a quick look at it nevertheless and it seems that `qttools` gets added to `QT_PLUGIN_PATH` in the `makeCWrapper` invocation for `$out/bin/qalculate-qt` even if it is moved to `nativeBuildInputs`. Unfortunately I don't know enough about the Qt ecosystem to tell why this is the case.

**Comment by Tungsten842** [comment]
I think that the issue lies in qttools itself, for some reason after https://github.com/NixOS/nixpkgs/pull/223271, qttools depends on clang and llvm at runtime
https://github.com/NixOS/nixpkgs/blob/3ae20aa58a6c0d1ca95c9b11f59a2d12eebc511f/pkgs/development/libraries/qt-6/modules/qttools.nix#L12-L15
This doesn't seem to be the case on [arch](https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-tools/-/blob/main/PKGBUILD#L14) and [fedora](https://src.fedoraproject.org/rpms/qt6-qttools/blob/rawhide/f/qt6-qttools.spec#_52) /packaging/packages/qt6-tools/-/blob/main/PKGBUILD#L14 @wineee @NickCao

**Comment by wineee** [comment]
qttools provides a qt plugin `libqquickwidget.so`，so wrapQtAppsHook will add `qttools` to ‘QT_PLUGIN_PATH’ automatically，Unfortunately, the packaging of qttools is not subdivided, all output is almost in one package，this leads to the addition of unnecessary runtime dependencies. ( Actually even `libqquickwidget.so` may not be needed

`llvm/clang` is required by `qdoc` and `lupdate`, 

https://wiki.qt.io/Lupdate_clang-based_c%2B%2B_parser
https://doc.qt.io/qt-6/01-qdoc-manual.html


lupdate seems to be just a optional feature dependency on clang，but  `remove-references-to` is not feasible，we have to recompile to disable this feature
```
./result/bin/lupdate: error while loading shared libraries: libclang.so.11.1: cannot open shared object file: No such file or directory
```

Splitting into multiple packages should be a better solution，qdoc/lupdate are often used to generate documentation/translations, almost no software runtime depends on them

**Comment by NickCao** [comment]
I think it's easier to add a `forQtDoc` flag to qttools, and only use that variant for building the docs.

**Comment by NickCao** [comment]
> @padhia `qttools` should be `nativeBuildInputs`, set `strictDeps=true` can prevent qttools from being recognized as a runtime dependency

If that helps, maybe https://github.com/NixOS/nixpkgs/pull/239781 is no longer necessary?

**Comment by NickCao** [comment]
> But not sure if there is a package need qttools (qt plugin `libqquickwidget.so`) as runtime dependency

I checked all packages that depends on qttools, and found that most if not all of them have a runtime reference on qttools due to it being in `QT_PLUGIN_PATH`. So this problem is actually widespread, we can have the workaround in https://github.com/NixOS/nixpkgs/pull/239781 for now.
