### ISSUE TITLE
Package request: SamRewritten

### ISSUE THREAD

**Issue by Redhawk18** [NixOS/nixpkgs#239494]
**Steam Achievement Manager For Linux. Rewritten in C++.**  

**Metadata**

* homepage URL: https://github.com/PaulCombal/SamRewritten
* source URL: https://github.com/PaulCombal/SamRewritten
* license: gpl3
* platforms: linux

the appimage in their release does not work.

**Comment by Krutonium** [comment]
NGL I was extremely excited for a moment for a port of Pajama Sam. This is good too.
