### ISSUE TITLE
ACME certificate generation fails with "The client sent an unacceptable anti-replay nonce :: JWS has invalid anti-replay nonce"

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixpkgs#23947]
## Issue description

Generation of a new certificate with `simp_le` (i.e. the ACME client used for `security.acme.certs` machinery) fails with
```
ACME server returned an error: urn:acme:error:badNonce :: The client sent an unacceptable anti-replay nonce :: JWS has invalid anti-replay nonce dnxG3dHfIa7yJavdnCUn-smm4B5sJ76qO5J7WRtySac
```
## Steps to reproduce

Setting
``` nix
    security.acme.certs."imap.example.com" = {
      email = "admin@example.com";
      webroot = "/var/lib/haproxy";
    };
```
Results in the generation of a systemd service calling a shell script like this:
```
#! /nix/store/gabjbkwga2dhhp2wzyaxl83r8hjjfc37-bash-4.3-p48/bin/bash -e
cd '/var/lib/acme/imap.example.com'
set +e
simp_le '-v' '-d' 'imap.example.com' '--default_root' '/var/lib/haproxy' '--valid_min' '2592000' '--email' 'admin@example.com' '-f' 'fullchain.pem' '-f' 'key.pem' '-f' 'account_key.json'
EXITCODE=$?
set -e
echo "$EXITCODE" > /tmp/lastExitCode
exit "$EXITCODE"
```
Executing the given `simp_le` command fails with the error message above. Hence, the service fails and the whole certificate generation fails. I haven't checked regeneration yet.

Note: There are a few pecularities in my setup using haproxy and https://github.com/janeczku/haproxy-acme-validation-plugin/ for presenting the challenge. Certificate generation worked before, although for another domain. I also think that this happens before the actual challenge is written to disk.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`16.09.1836.067e66a`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.7`

**Comment by fpletz** [comment]
We don't support 16.09 anymore. You shouldn't encounter this on 17.03+.
