### ISSUE TITLE
Package request: Pyfa

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#239454]
**Project description**

[**Pyfa**](https://github.com/pyfa-org/Pyfa) is Python Fitting Assistant, a cross-platform ship fitting tool for EVE Online.

![](https://user-images.githubusercontent.com/275209/66119992-864be080-e5e2-11e9-994a-3a4368c9fad7.png)

**Metadata**

* homepage URL: https://forums.eveonline.com/t/pyfa-the-python-fitting-assistant/27156
* source URL: https://github.com/pyfa-org/Pyfa
* license: GPL-3.0
* platforms: Windows, macOS, Linux

**Comment by Majiir** [comment]
Depends on a solution for https://github.com/pyfa-org/Pyfa/issues/2502 because nixpkgs has `sqlalchemy` at `2.0.18`.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/314934
