### ISSUE TITLE
shared nix store with qemu, strange problem again

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#23957]
## Issue description

When I start 3-4 qemu machines at once, sometimes (approx each 10-20th run), one or two of the virtual machines do not start.
The reason is always the same, kernel panic due to ```init``` cannot find ```systemd```:

![9p](https://cloud.githubusercontent.com/assets/508305/24008958/4b225f34-0a6b-11e7-89d0-9598f24a9e39.png)

I tried kernels ```4.1```, ```4.4```, ```4.9``` and tried to remove "cache=loose" from ```9p``` mount options with no success.

maybe related #22695

**Comment by abbradar** [comment]
Also possibly related: https://github.com/NixOS/nixpkgs/issues/23020

**Comment by volth** [comment]
Very likely it is #23020's duplicate
Just tried @dezgeg patch, the issue seems disappear.
I am going to backport it to kernel 4.4 and test harder (4.9 does not allow me to connect an external display to the laptop).

**Comment by dezgeg** [comment]
Yeah, I think #23020 needs a really high amount of inode cache activity (i.e. files accessed) to show up.

At $work I have 20+ qemus being launched by a CI system simultaneously (on a 40-core system) and haven't seen this problem. I am using the `runInLinuxVM` thingy instead of full NixOS vm's though.

**Comment by volth** [comment]
My setup is rather modest: a Thinkpad X220 and something similar to ```test-driver```, a script which prepares system clusures and launch qemus ising kernel, initrd and init from the closures.
Inserting ```sleep(1)``` between launching qemus solves the issue. This makes me think that there is a race condition in qemu or kernel 9p driver when ```systemd``` executable or one of their ```.so``` files are being read.

**Comment by dezgeg** [comment]
The 9p server is implemented completely in qemu userspace code, so I don't see that the problem could be in the kernel.

**Comment by volth** [comment]
on qemu's 9p-server it looks like the guest sends ```TFlush``` (a request to cancel a pending operation)
```
v9fs_getattr tag 1 id 24 fid 75 request_mask 6143
v9fs_flush tag 2 id 108 flush_tag 1
v9fs_rerror tag 1 id 24 err 4
```
There are three cases:
1. guest does not send ```TFlush``` - ok
2. guest sends ```TFlush``` when there is no pending operation - ok
2. guest sends ```TFlush``` when there is a pending operation (I saw only ```v9fs_getattr```), the operation is interrupted, the server answers with ```EINTR``` resulting in ```systemd: file not found```.

**Comment by dezgeg** [comment]
The only source of tflush is a signal interruption:

````
  772         if ((err == -ERESTARTSYS) && (c->status == Connected)) {                                                                                          
 773                 p9_debug(P9_DEBUG_MUX, "flushing\n");                                                                                                     
 774                 sigpending = 1;                                                                                                                           
 775                 clear_thread_flag(TIF_SIGPENDING);                                                                                                        
 776                                                                                                                                                           
 777                 if (c->trans_mod->cancel(c, req))                                                                                                         
 778                         p9_client_flush(c, req);       // <-- sends TFLUSH                                                                                                   
````                                                                                

So is there something still alive on the initrd sending signals to others?

**Comment by volth** [comment]
I have not found the source of the signal yet.
What looks suspicious, is that ```cancel``` (line 777 in your snippet) is [p9_virtio_cancel](https://github.com/torvalds/linux/blob/v4.4/net/9p/trans_virtio.c#L207):
```
/* We don't currently allow canceling of virtio requests */
static int p9_virtio_cancel(struct p9_client *client, struct p9_req_t *req)
{
	return 1;
}
```

it it does not allow canceling of virtio requests, shouldn't it return 0 instead of 1 ?

**Comment by dezgeg** [comment]
Some debugging ideas: set `ftrace_dump_on_oops` on the kernel command line and enable ftrace for `signal_deliver` and/or `signal_generate`.

**Comment by volth** [comment]
only ```SIGCHLD``` (17):

![sigchld](https://cloud.githubusercontent.com/assets/508305/24120316/0f8042fe-0dac-11e7-909e-99b25212eca2.png)

there is even no need to launch ```systemd```, just adding ```if [ ! -s /run/current-system/systemd/lib/systemd/systemd ]; then echo "bug!"; /bin/sh; fi```
to ```<nixpkgs/nixos/modules/system/boot/stage-2-init.sh>``` before actual ```systemd```  is enough to hit the bug.

I am really thinking about replacing 9p with something else (nfs? samba?), we found so many 9p bugs recently...

**Comment by dezgeg** [comment]
Indeed, 9p is somewhat buggy... but there really shouldn't be child processes executing/exiting during the time we transition from initrd to the real init!

**Comment by volth** [comment]
there are dozens of ```sig=17```, even if the bug is not hit.
```init``` is ```stage-2-init.sh```, it launches many programs: ```chmod```, ```mkdir```, ```hwclock```, ```ln```, ...

**Comment by dezgeg** [comment]
Oops, do'h, indeed that doesn't reveal the culprit. What I was looking for the process id/name that causes SIGCHLD to be sent to init such that it causes some system call made by bash to be interrupted and return EINTR. 

But indeed this seems to be an 9p bug as essentially any filesystem call can return EINTR! Does `s/wait_for_event_interruptible/wait_for_event_killable/` on this line: http://lxr.free-electrons.com/source/net/9p/client.c#L752 help?

**Comment by volth** [comment]
Yes, it helps.

**Comment by dezgeg** [comment]
Time for me to spam LKML with some patches then...

**Comment by volth** [comment]
```wait_event_interruptible``` might be ok too as long as no ```tflush``` is sent (or ignored by qemu)
Then it would be the [case 2](https://github.com/NixOS/nixpkgs/issues/23957#issuecomment-287365769)

**Comment by dezgeg** [comment]
In case 2 this happens:

````
780                 /* if we received the response anyway, don't signal error */
781                 if (req->status == REQ_STATUS_RCVD)
782                         err = 0;
````

So it's timing dependent, not something that can be reliably triggered.

**Comment by volth** [comment]
@dezgeg has the bug ["9pfs hangs since 4.7"](https://lkml.org/lkml/2016/11/24/721) been fixed? I do not see it among the nixpkgs issues.

**Comment by dezgeg** [comment]
This seems to be in QEMU master:

````
commit 0d78289c3dca3de8e614a551a3d4a9415168ace0
Author: Greg Kurz <groug@kaod.org>
Date:   Fri Jan 13 18:18:20 2017 +0100

    9pfs: fix off-by-one error in PDU free list
    
    The server can handle MAX_REQ - 1 PDUs at a time and the virtio-9p
    device has a MAX_REQ sized virtqueue. If the client manages to fill
    up the virtqueue, pdu_alloc() will fail and the request won't be
    processed without any notice to the client (it actually causes the
    linux 9p client to hang).
    
    This has been there since the beginning (commit 9f10751365b2 "virtio-9p:
    Add a virtio 9p device to qemu"), but it needs an agressive workload to
    run in the guest to show up.
    
    We actually allocate MAX_REQ PDUs and I see no reason not to link them
    all into the free list, so let's fix the init loop.
    
    Reported-by: Tuomas Tynkkynen <tuomas@tuxera.com>
    Suggested-by: Al Viro <viro@ZenIV.linux.org.uk>
    Signed-off-by: Greg Kurz <groug@kaod.org>
````

**Comment by volth** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/24143 except the ```qemu``` fix which could also be made as patch until new version of ```qemu``` be released.
Or we could upgrade ```qemu``` to git version.
