### ISSUE TITLE
Package request: Morewaita

### ISSUE THREAD

**Issue by dch82** [NixOS/nixpkgs#239550]
**Project description**

Extended Adwaita icon theme for third-party icons.
Requires the built-in Adwaita icon theme.

**Metadata**

* homepage URL: https://github.com/somepaulo/MoreWaita
* source URL: https://github.com/somepaulo/MoreWaita
* license: GPL 3.0
* platforms: Linux

**Comment by sylvester-roos** [comment]
This seems to be the associated PR: https://github.com/NixOS/nixpkgs/pull/214057

**Comment by erlefloch** [comment]
> This seems to be the associated PR: #214057

the PR has been merged last week :)
