### ISSUE TITLE
Package request: librenms

### ISSUE THREAD

**Issue by ppauly** [NixOS/nixpkgs#239566]
Network Monitoring System

A network monitoring system that pulls information from the monitored systems using primarily snmp to report and graph system performance and availability. 

**Metadata**

* homepage URL: https://www.librenms.org/
* source URL:  https://github.com/librenms/librenms
* license: mit, GPLv3
* platforms: linux

**Comment by NetaliDev** [comment]
There is already a PR for this #233991
