### ISSUE TITLE
boot.loader.grub.useOSProber doesn't seem to work.

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#23958]
## Issue description

Specifying `boot.loader.grub.useOSProber` in my /etc/nixos.configuration.nix and running `nixos-rebuild switch` results in the following error:

```
building Nix...
building the system configuration...
updating GRUB 2 menu...
/nix/store/010yd8jls8w4vcnql4zhjbnyp2yay5pl-bash-4.4-p5/bin/bash: /etc/grub.d/30_os-prober: No such file or directory
```

I'm very new to NixOS so I could be doing something wrong, any help would be appreciated.

* System: 17.09pre102667.2839b10 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: 17.09pre102667.2839b10

**Comment by pbogdan** [comment]
This seems to come down to my system using EFI grub and `$grub` variable not being set in https://github.com/NixOS/nixpkgs/blob/427edf1e5d677795d20ebd8c8729a5f1bee20c96/nixos/modules/system/boot/loader/grub/install-grub.pl#L448 Switching that over to `$grubEfi` seems to fix the issue and the menu entries getting updated.

**Comment by globin** [comment]
cc @symphorien

**Comment by pbogdan** [comment]
I believe something along the lines of https://github.com/pbogdan/nixpkgs/commit/ad06cfceaf8748a74f3afb12773461a5b58f8b37 would be needed to make it work with both "plain" and EFI versions. Can't test against "plain" version but it works as expected on my EFI system:

```
$ sudo nixos-rebuild switch                                      
building Nix...
building the system configuration...
updating GRUB 2 menu...
lsblk: /dev/mapper/no*[0-9]: not a block device
lsblk: /dev/mapper/raid*[0-9]: not a block device
lsblk: /dev/mapper/disks*[0-9]: not a block device
Found Debian GNU/Linux 9 (stretch) on /dev/sda3
Found Windows Boot Manager on /dev/sda7@/EFI/Microsoft/Boot/bootmgfw.efi
activating the configuration...
setting up /etc...
setting up tmpfiles
the following new units were started: systemd-vconsole-setup.service
$ sudo grep -c Debian /boot/grub/grub.cfg
15
$ sudo grep -c Windows /boot/grub/grub.cfg
1
```

**Comment by symphorien** [comment]
Apparently https://github.com/NixOS/nixpkgs/blob/427edf1e5d677795d20ebd8c8729a5f1bee20c96/nixos/modules/system/boot/loader/grub/install-grub.pl#L550 and https://github.com/NixOS/nixpkgs/blob/427edf1e5d677795d20ebd8c8729a5f1bee20c96/nixos/modules/system/boot/loader/grub/install-grub.pl#L567 don't seem incompatible.
That suggest (I didn't check) that both grubEfi and grub can in some cases be installed at the same time.
Then, your code would take none of the two branch.

**Comment by pbogdan** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/24206, closing.
