### ISSUE TITLE
Update request: betterbird 102.8.0-bb30 → 102.12.0-bb37

### ISSUE THREAD

**Issue by rkunschke** [NixOS/nixpkgs#239531]
- Package name: betterbird
- Latest released version: 102.12.0-bb37
- Current version on the unstable channel: 102.8.0-bb30
- Current version on the stable/release channel: 102.8.0-bb30

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000 

The package is outdated since a while. I hope it can be updated in the near feature. Thank you :)

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by emilazy** [comment]
see https://github.com/NixOS/nixpkgs/pull/241560
