### ISSUE TITLE
Spideroak GUI does not work in unstable

### ISSUE THREAD

**Issue by minkkinen** [NixOS/nixpkgs#23960]
## Issue description

Spideroak GUI does not work in NixOS unstable. When running `spideroak`, I get this error:
```py
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__SpiderOakONE__.py", line 181, in <module>
  File "__main__SpiderOakONE__.py", line 166, in main
  File "oak/Oak.py", line 24, in <module>
  File "PyQt4/QtGui.py", line 26, in <module>
  File "PyQt4/QtGui.py", line 17, in _bbfreeze_import_dynamic_module
ImportError: /nix/store/ryr8czzrj0mz55hilim215l7ydaryarq-spideroak-6.0.1/opt/SpiderOakONE/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /nix/store/lbq1pdql98h7xh25j4rx8k7gyrvy77fa-libpng-apng-1.6.28/lib/libpng16.so.16)
```

As far as I am able to tell, headless mode runs fine.

### Steps to reproduce

Install spideroak and try to run `spideroak`.

## Technical details

* System: 17.09pre102667.2839b10 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.09pre102667.2839b10"

**Comment by FRidh** [comment]
Python uses the default zlib which is currently 1.2.11.

I see the following options:
- override Python expression and use an older version of zlib
- let spideroak use our version of libpng.

cc @vcunat @Fuuzetsu

**Comment by vcunat** [comment]
Well the package's approach is strange to me.  It installs private versions of libs that depend on libs not installed, and at the same time, some of the missing libs naturally depend on libs that are also installed privately (on zlib, for example).   You can try such tweaks to find what will work now, but I'm afraid it's likely to remain fragile.
