### ISSUE TITLE
Cant get pcloud appimage to work on nixos neighter from the package or the app image itself. Help!

### ISSUE THREAD

**Issue by leier69** [NixOS/nixpkgs#239661]
I'm really dependant on running pcloud appimage on my machine, but it does not work because its probably looking for library paths not present.

appimage-run pcloud
Error: Dynamic Linking Error: libfuse.so.2: cannot
open shared object file: No such file or directory

I've downloaded libfuse and tried linking to it from various locations without any luck. And please dont mention rsync. I know it works but its slow... I've tried many settings with rsync

Is there anything I can do to make it work, and is there anything we can to do make the package more reproducible?

CC a few people I know that probably have gotten it to work @239 @R-VdP @risicle

**Comment by R-VdP** [comment]
Duplicate of #226339.

There are temporary workarounds mentioned in that issue, did you try those?

**Comment by leier69** [comment]
@R-VdP I assume you're reffering to this workaround: https://gist.github.com/R-VdP/999dd803c96aee0cb6a176eadef0978e right?

Do you know something I can do to fix this error :sweat_smile: 

```
[me@desktop:~]$ sudo nixos-rebuild switch --flake ~/.config/nixos#desktop
building the system configuration...
error: attribute 'currentSystem' missing

       at /nix/store/xpns0xrmibrkm4gllybl6n7lgyandvrx-source/pkgs/top-level/impure.nix:17:43:

           16|   # (build, in GNU Autotools parlance) platform.
           17|   localSystem ? { system = args.system or builtins.currentSystem; }
             |                                           ^
           18|
(use '--show-trace' to show detailed location information)
```

my flake.nix
```
{
  description = "dotfiles";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.05";
    home-manager.url = "github:nix-community/home-manager/release-23.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs {
        system = "x86_64-linux";
        config = { allowUnfree = true; };
      };
      lib = nixpkgs.lib;
      mkSystem = pkgs: system: hostname:
        pkgs.lib.nixosSystem {
          inherit system;
          modules = [
            { networking.hostName = hostname; }
            { system.stateVersion = "23.05"; }
            (./. + "/hosts/${hostname}/configuration.nix")
            home-manager.nixosModules.home-manager {
              home-manager = {
                  useUserPackages = false;
                  useGlobalPkgs = true;
                  users.leier = {
                    imports = [ (./. + "/hosts/${hostname}/home") ];
                    home.stateVersion = "23.05";
                  };
              };
            }
          ];
        };

    in {
      nixosConfigurations = {
        desktop = mkSystem nixpkgs "x86_64-linux" "desktop";
      };
    };
}
```

I just simply created pcloud.nix and imported it through configuration.nix

**Comment by R-VdP** [comment]
Disclaimer: all of these workaround are ugly hacks depending on an EOL nixpkgs release, but it's the best we have until someone figures out the patchelf issue.

Oh, hmm, I didn't try this with home-manager, and that module you linked to was meant for non-flake NixOS systems.

If you use flakes though, you can solve it by having a 22.11 nixpkgs input and doing mostly the same. I adapted your flake here: https://gist.github.com/R-VdP/7da32fb0ae0f9ddb6b8f5b199d1996a7

I didn't test it though, so possible that you need to fix some minor things, but it should show you the idea.

**Comment by leier69** [comment]
We back! Thanks alot @R-VdP, but I found it funny that I did not need the "overrideAttrs" part at all, just pulling the package from nixpkgs_22_11 works on its own. Is it something that I'm missing about the temporary solution??

**Comment by R-VdP** [comment]
That also works, but gives you an outdated version of pcloud.

**Comment by leier69** [comment]
ahh I see. Ok thnx
