### ISSUE TITLE
Package request: transfer.sh

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#239627]
**Project description**

A pastebin server with everything you need to create your own instance. It provides easy and fast file sharing from the command-line and supports S3 as backend for storage

EDIT: The project's upstream already provides a [flake.nix](https://github.com/dutchcoders/transfer.sh/blob/main/flake.nix) file with package and module. Might still be worth to have in nixpkgs

**Metadata**

* homepage URL:https://github.com/dutchcoders/transfer.sh
* source URL:https://github.com/dutchcoders/transfer.sh
* license: mit
* platforms: unix, linux

**Comment by raspher** [comment]
It was packaged here https://github.com/NixOS/nixpkgs/pull/283660

[search.nixos.org](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=transfer.sh)
