### ISSUE TITLE
Package request: SSVOpenHexagon (clone of "Super Hexagon", game)

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#239769]
**Project description**

C++20 FOSS clone of "Super Hexagon". Depends on SSVStart, SSVEntitySystem, SSVLuaWrapper, SSVMenuSystem, JSONcpp, SFML2.0. Features JSON/LUA customizable game files, a soundtrack by BOSSFIGHT, pseudo-3D effects.

**Metadata**

* homepage URL: https://openhexagon.org/
* source URL: https://github.com/vittorioromeo/SSVOpenHexagon
* license: [afl](https://github.com/vittorioromeo/SSVOpenHexagon/blob/master/LICENSE)
* platforms: [linux](https://github.com/vittorioromeo/SSVOpenHexagon/wiki/Building-Instructions#building-on-linux), darwin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/223292

**Comment by revuwa** [comment]
Oh no, thanks for pointing to that issue. 
Not found that before opening this request, so sorry.
