### ISSUE TITLE
ripgrep 0.5.0 build broken on Darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#23972]
This upgrade breaks on darwin, apparently because a dependency download is expecting SSL certificates to live someplace that only occurs on Linux:

```
Using rust registry from /nix/store/4ihzgvxjxvaidg732i03rz48b2fiaqjy-rustRegistry-2017-03-13-e5b7b45
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
    Updating registry `file:///nix/store/4ihzgvxjxvaidg732i03rz48b2fiaqjy-rustRegistry-2017-03-13-e5b7b45`
 Downloading libc v0.2.21 (registry file:///nix/store/4ihzgvxjxvaidg732i03rz48b2fiaqjy-rustRegistry-2017-03-13-e5b7b45)
error: unable to get packages from source

Caused by:
  [77] Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none)
builder for ‘/nix/store/vjkxdg2rkwzmncfpb13z9n1f2mbnfx50-ripgrep-0.5.0-fetch.drv’ failed with exit code 101
```

Due to 363cfbd23dd6653a12fd2a5deba97befe8816426

**Comment by LnL7** [comment]
I'm pretty sure the issue here is related to https://github.com/NixOS/nix/issues/921 and https://github.com/NixOS/nixpkgs/issues/23605, not the update.

<img width="1097" alt="screen shot 2017-03-17 at 08 11 22" src="https://cloud.githubusercontent.com/assets/689294/24032653/62f5f426-0ae9-11e7-8b26-105855049cce.png">

**Comment by LnL7** [comment]
Is this still a issue for you? I think you can force a local build with `nix-build -A rustPlatform.rustRegistry --check`.
http://hydra.nixos.org/build/50577913

**Comment by jwiegley** [comment]
Appears fixed now, thank you.
