### ISSUE TITLE
Build failure: nixos-23.05 -> spotdl

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#239733]
### Steps To Reproduce

https://hydra.nixos.org/job/nixos/release-23.05/nixpkgs.spotdl.x86_64-linux

Failure happens locally as well when trying to build spotdl on the nixos-23.05 branch.

### Logs:

this the tail of the log:
```
=========================== short test summary info ============================
FAILED tests/providers/audio/test_youtube.py::test_yt_search - spotdl.providers.audio.base.AudioProviderError: YT-DLP download error - htt...
=========== 1 failed, 49 passed, 14 deselected, 5 warnings in 8.88s ============
/nix/store/5wdlffjhcr4i43sfajxcvx3lvnkryh5y-stdenv-linux/setup: line 1604: pop_var_context: head of shell_variables not a function context
```
The last line is apparently unrelated:
https://github.com/NixOS/nixpkgs/issues/214822

### Notify maintainers

@dotlambda (maintainer) @fabaff (recent bumps)

**Comment by dariof4** [comment]
This test doesn't fail if spotdl is built using `yt-dlp` version `2023-06-21` from this nixpkgs commit `https://github.com/NixOS/nixpkgs/commit/e9210dc5980ea699c910feb85a9e7fdce796531b`, I'm not sure if this is an upstream issue with spotdl while using newer yt-dlp versions.
