### ISSUE TITLE
NixOS image for Google Compute Engine fails to build

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#23973]
When I try to build the NixOS image for Google Compute Engine on
latest `nixos-unstable`, the build process errors out with complaints
about trying to create hard links to directories:
<https://gist.github.com/8573/53dfc5542f95cbf11127b6df915b7500>.

**Comment by globin** [comment]
cc @fadenb who had similar problems with the azure image.

**Comment by fadenb** [comment]
We solved the issue with the azure images by using rsync instead of cp: See 097ef6e435d5b3fcde92e67abbaaaaaf05c0723d

**Comment by globin** [comment]
Thanks couldn't find that commit anymore.

**Comment by 8573** [comment]
Thanks; I've filed pull request #24264 to apply the same change to the GCE image build.

**Comment by globin** [comment]
Thanks :)
