### ISSUE TITLE
Package request: video-downloader

### ISSUE THREAD

**Issue by RMED24** [NixOS/nixpkgs#239832]
**Project description**

This is a GTK GUI application based on yt-dlp which makes downloading videos very easy. Currently, it is only officially supported on snap, flatpak, fedora and the AUR.

 **Metadata**

* homepage URL: https://github.com/Unrud/video-downloader
* source URL: https://github.com/Unrud/video-downloader
* license: gpl-v3
* platforms: Linux

**Comment by FliegendeWurst** [comment]
PR: #264447
