### ISSUE TITLE
GNOME and Hyprland Incompatible on NixOS

### ISSUE THREAD

**Issue by paladhammika** [NixOS/nixpkgs#239886]
### The bug

After much trial and error I've found that, at least on my system, enabling GNOME and Hyprland at the same time raises issues for Hyprland usage for whatever reason. It seems to do with the xdg-desktop-portal.

Using both in NixOS

```
services.xserver.desktopManager.gnome.enable = true;
programs.hyprland.enable = true;
```

Makes GTK applications sluggish. For example, the volume doesn't raise  when attempting to alter the volume with `swayosd --output-volume raise` nor do I receive a notification until about 30+ seconds later. The same with using `nwg-panel` and opening `nautilus`. Opening `wezterm` and `emacs` however is not an issue. 

I then tried to log into GNOME first and then attempt to launch Hyprland from `wezterm` which fails but then switching to the TTY and launching Hyprland worked. After using GNOME and launching serveral applications, then switching to TTY and launching Hyprland I found that this GTK sluggishness stopped. So there seems to be a disconnect with the `xdg-desktop-portal-*` or GTK in general. 

### Steps To Reproduce
1. Enable both of the above modules
2. Launch directly in Hyprland from the display manager
3. Try opening `nautilus` or any other GTK application

### Expected behavior
Smooth sailing in Hyprland

### Notify maintainers

@wozeparrot @fufexan

### Metadata
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.05 (Stoat), 23.05.1092.c7ff1b9b956`
 - multi-user?: `yes`
```

**Comment by paladhammika** [comment]
When attempting to open nautilus in Hyprland. The process hangs at "Connecting to..." until finally opening.
![image](https://github.com/NixOS/nixpkgs/assets/93992898/8a2f2ffc-7aac-4092-822a-000e6664f04a)


---

Often time rebuilding home-manager produces the below issue:

```
❯ home-update
/nix/store/vvd50x0m9imrafrxp19qmpjvrwg980d1-home-manager-generation
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
Activating linkGeneration
Cleaning up orphan links from /home/paladhammika
No change so reusing latest profile generation 16
Creating home file links in /home/paladhammika
Activating onFilesChange
Activating reloadSystemd
The user systemd session is degraded:
  UNIT                                LOAD   ACTIVE SUB    DESCRIPTION                             
● xdg-desktop-portal-hyprland.service loaded failed failed Portal service (Hyprland implementation)

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
Attempting to reload services anyway...
```

**Comment by fufexan** [comment]
Hyprland is *not recommended* to be used when other *big* DE is enabled. So when using KDE or GNOME alongside Hyprland, you may want to attempt @chadcatlett's suggestions.

**Comment by wozeparrot** [comment]
Enabling GNOME should pull in `xdg-desktop-portal-gnome` which is specifically not recommended to be enabled with `xdg-desktop-portal-hyprland` https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

Maybe there should be a warning if there are extra portals enabled? Not sure if that's possible with the way modules are merged.

**Comment by fufexan** [comment]
@wozeparrot Hyprland actually checks `/usr/share/xdg-desktop-portal/portals` for portals other than xdph, and displays a warning if they're found. I just recently learned about its existence, so we could patch it to look in `$XDG_DESKTOP_PORTAL_DIR` instead.

**Comment by wozeparrot** [comment]
Yea, that would work, a build warning would be better than a runtime warning but a runtime warning is better than nothing. :smile:

**Comment by fufexan** [comment]
I think we could make an assertion in the Hyprland NixOS module.

**Comment by paladhammika** [comment]
Is there no way to kill `xdg-desktop-portal-gnome` when logging into a Hyprland session or to otherwise override `xdg-desktop-portal-gnome` with `xdg-desktop-portal-hyprland`?

**Comment by fufexan** [comment]
You can do that yourself with `exec-once`s. Also no, we cannot override the gnome portal with the hyprland portal, as that will render the GNOME session broken, more so than using Hyprland with the wrong portals. The best way is to avoid having both enabled at the same time.

**Comment by berbiche** [comment]
Another idea would be to have an override in the user unit that adds conditional execution to the service with `serviceConfig.ExecCondition = sh -c 'test "${XDG_CURRENT_DESKTOP:-none}" = "Gnome"'` for Gnome's portal and the same one for Hyprland (or something like that, I don't have a Gnome/Wayland system atm to test this on).

There's also `ConditionEnviroment = XDG_CURRENT_DESKTOP=gnome` but I don't remember when it gets evaluated and if it completely prevents the service from starting even if the condition became true (i.e. the unit is started/evaluated before XDG_CURRENT_DESKTOP is imported in systemd's environment).

**Comment by fufexan** [comment]
I've never seen that, but if we can make it work, sounds good to me. I might play around with it.

**Comment by fufexan** [comment]
The runtime check is now in place, it will land in Nixpkgs with the next Hyprland version. By that time, I hope to also figure out a build-time check at least, and hopefully implement @berbiche's idea.

**Comment by LiGoldragon** [comment]
>  a runtime warning is better than nothing. smile

That's incorrect. Rust is a good example if you need help understanding how.

**Comment by LiGoldragon** [comment]
To fix this would mean changing the `xdg.extraPortals` to a more complex system. It would almost certainly involve other deep components.

**Comment by paladhammika** [comment]
Been AFK for months, I'm wondering is there a quick fix workaround that can be posted here until something more structural comes about?

**Comment by fufexan** [comment]
Have you updated since then? XDG portals no longer conflict with one another.

**Comment by paladhammika** [comment]
I've upgraded to Hyprland 0.31 but still experience sluggishness with opening Gnome applications like nautilus.

**Comment by Janov911** [comment]
same here, switched back to a sway/gnome combo because hyprland just does not work on nixos for me atm
