### ISSUE TITLE
`matrix-synapse` 1.86.0 unable to launch: `sqlite3.IntegrityError: UNIQUE constraint failed: temp_user_filters.user_id`

### ISSUE THREAD

**Issue by JonBoyleCoding** [NixOS/nixpkgs#239833]
### Describe the bug
The upgrade to matrix-synapse 1.86.0 is causing a failure when used on at least a number of systems outside of nix https://github.com/matrix-org/synapse/issues/15809

`sqlite3.IntegrityError: UNIQUE constraint failed: temp_user_filters.user_id` is the specific error

I'm having this issue as well when I did the upgrade. I have identical output to the issue above. This version has been backported to 22.11 and 23.05.

This is an original software error, I do not know what can be done on this end - thought it was worth reporting here in case anyone has the same error.

### Steps To Reproduce
1. Upgrade from matrix-synapse 1.85.2 to the current 23.05/22.11 commits
2. When service starts, the above issue happens causing the server to not be able to start

### Expected behavior

Service is able to start.

### Additional context

I have currently locked my nix flake to commit to 4bbecb600a1c753bd04c63a6d3a237b8f9fc1949 to keep at the previous version for now. 

### Notify maintainers

@ma27 @fadenb @mguentner @ralith @dandellion @sumnerevans

**Comment by anoadragon453** [comment]
The issue was introduced in Synapse v1.86.0. The solution is to rollback to v1.85.0 until a fix (wip: https://github.com/matrix-org/synapse/pull/15817) is introduced in a new release; likely v1.87.0, expected to release July 4th 2023.

**Comment by JonBoyleCoding** [comment]
> > This is an original software error,
> 
> There is an element of the packaging community failing to catch it and delivering broken software as "stable", though.

Indeed. Presumably this works fine when not upgrading a database so a test for this would be tricky to implement.

Either way, at least there's a workaround.

**Comment by crawford** [comment]
@egasimus, you can avoid the rebuild by using an overlay to override the package with the version from the older, working release:

```nix
{
  nixpkgs.overlays = let
    pinned = import (builtins.fetchTarball {
      name = "nixos-22.11-working-matrix";
      url = "https://github.com/nixos/nixpkgs/archive/03091c9ffd7033ea855d0216111c4a9975c5780f.tar.gz";
      sha256 = "1xawkcf31r7a9hdrrqpsyz9c9lnchy2msv2pkcsvcxkxay9sjm7c";
    }) {
      config = config.nixpkgs.config;
    };
  in [
    (final: prev: {
      matrix-synapse = pinned.matrix-synapse;
    })
  ];
}
```

**Comment by Ma27** [comment]
> Indeed. Presumably this works fine when not upgrading a database so a test for this would be tricky to implement.

Well, upgrades are of course tested by maintainers before merging this. However, we all use postgres I guess.

**Comment by Lakr233** [comment]
Same here, and going back for now.

**Comment by crawford** [comment]
Where did you see that note about database recommendations? I've been using Synapse for years with a SQLite database. I didn't realize I was living on the edge.

**Comment by Ma27** [comment]
E.g. in https://matrix-org.github.io/synapse/latest/setup/installation.html#using-postgresql, but also at the very top is a brief note: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html.

> Maybe we should add a services.matrix-synapse.YesIWantToUseSqliteThisIsNotAProductionServer to at least notify old stateVersion users that their database is not production capable.

Adding a note to the manual is fine, but I don't think we should implement safe-guards for _every single_ thing people might do wrong. This is IMHO not our responsibility as maintainers anymore.

**Comment by crawford** [comment]
Ah, thanks. It looks like those notes were added after I did my installation (added in [2021](https://github.com/matrix-org/synapse/commit/f95e7a03fa66e00b581d11f17244bf1701559f6c) and [2022](https://github.com/matrix-org/synapse/commit/3c758d9808ddc00ee96c5426dda3caea356c8745)). I'll have to figure out the migration process.

I think a note in the upgrade instructions of the manual would be sufficient - just something to retroactively draw attention to the deprecation upstream.

**Comment by dali99** [comment]
>Adding a note to the manual is fine, but I don't think we should implement safe-guards for every single thing people might do wrong. This is IMHO not our responsibility as maintainers anymore.

Then we should remove the automatic switch on state version and force sqlite users to configure it themselves. The fact that we default to this behavior makes it _a little_ our responsibility

**Comment by Ma27** [comment]
> Then we should remove the automatic switch on state version and force sqlite users to configure it themselves. The fact that we default to this behavior makes it a little our responsibility

Which behavior specifically?

Also, sqlite is the upstream default as well:

> Do note however that the database defaults to SQLite, which is not recommended for production usage.

(source: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html)

**Comment by dali99** [comment]
https://github.com/NixOS/nixpkgs/blob/0ad0cc50395a085200bd7901258118e75a1c63ba/nixos/modules/services/matrix/synapse.nix#L473

Since we no longer automatically provision the database, we can just remove this stateversion switch, default to postgres, and just fail early for sqlite users if not explicitly set.
