### ISSUE TITLE
Impressive broken

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#23980]
## Issue description
```
Welcome to Impressive version 0.11.1
Detected screen size: 1680x1050 pixels
FATAL: failed to load the SDL library
This likely means that your graphics driver or hardware is too old.
```

### Steps to reproduce
`$ nix-shell -p impressive --run 'impressive some/presentation.pdf'`

## Technical details
- System: 17.03beta320.ade5837 (Gorilla)
- Nix version: nix-env (Nix) 1.11.7
- Nixpkgs version: "17.03beta320.ade5837" ; also occurs on master.

**Comment by dilumaluthge** [comment]
You need to install SDL-1.2: https://www.libsdl.org/download-1.2.php

After installing SDL, you may need to recompile pygame.

**Comment by lheckemann** [comment]
This isn't how Nix works — libraries aren't installed.

**Comment by dilumaluthge** [comment]
Try the following steps - they worked for me on a fresh VirtualBox.

Step 1: Add the following lines (taken from [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/my-env/default.nix)) to `~/.config/nixpkgs/config.nix`:
```
{
  packageOverrides = pkgs : with pkgs; {
    sdlEnv = pkgs.myEnvFun {
        name = "sdl";
        buildInputs = [ stdenv SDL SDL_image SDL_ttf SDL_gfx cmake SDL_net  pkgconfig];
    };
  };
}
```

Step 2: Install the environment:
```nix-env -i env-sdl```

Step 3: Load the environment:
```load-env-sdl```

Step 4: Download a sample PDF:
```nix-shell -p wget --run "wget http://web.mit.edu/rsi/www/pdfs/beamer-tutorial.pdf"```

Step 5: Open the PDF in Impressive:
```nix-shell -p pdftk -p impressive --run "impressive beamer-tutorial.pdf"```

**Comment by dilumaluthge** [comment]
Try the following steps - they worked for me on a fresh VirtualBox.

Step 1: Add the following lines (taken from [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/my-env/default.nix)) to `~/.config/nixpkgs/config.nix`:
```
{
  packageOverrides = pkgs : with pkgs; {
    sdlEnv = pkgs.myEnvFun {
        name = "sdl";
        buildInputs = [ stdenv SDL SDL_image SDL_ttf SDL_gfx cmake SDL_net  pkgconfig];
    };
  };
}
```

Step 2: Install the environment:
```nix-env -i env-sdl```

Step 3: Load the environment:
```load-env-sdl```

Step 4: Download a sample PDF:
```nix-shell -p wget --run "wget http://web.mit.edu/rsi/www/pdfs/beamer-tutorial.pdf"```

Step 5: Open the PDF in Impressive:
```nix-shell -p pdftk -p impressive --run "impressive beamer-tutorial.pdf"```

**Comment by lheckemann** [comment]
Yep, that works, thanks for the input! However, this *should* not be the only way it works — particularly because myEnvFun is deprecated in favour of nix-shell. I'll see if I can fix the packaging.
