### ISSUE TITLE
Package request: goldendict-ng

### ISSUE THREAD

**Issue by paladhammika** [NixOS/nixpkgs#239921]
**Project description**

A fork of Golden Dictionary which fixes many old bugs, provides improvement, and is being actively developed.

It might be better to switch to `goldendict-ng` altogether instead of continuing to maintain `goldendict`.

**Metadata**

* homepage URL: https://xiaoyifang.github.io/goldendict-ng/
* source URL: https://github.com/xiaoyifang/goldendict-ng
* license: gplv3
* platforms: linux

**Comment by wegank** [comment]
> It might be better to switch to `goldendict-ng` altogether instead of continuing to maintain `goldendict`.

`goldendict` doesn't seem too inactive now: they even had a new release last month.

**Comment by DCsunset** [comment]
I think it might be a good idea to have both versions as `goldendict-ng` provides extra features and bug fixes if that's possible.
