### ISSUE TITLE
nginx: `forceSSL` breaks `enableACME`

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#239987]
### Describe the bug
I am experiencing that when these two options are enabled at the same time, the certificate fails to be generated as when Let's encrypt tries to request the authorization token, it gets a "connection refused" from the machine. This does not happen when `forceSSL` is not enabled.

Once the ceritificate is generated properly without `forceSSL`, then one can enable the option and successive deployments do work.

### Steps To Reproduce
Enable both `forceSSL` end `enableACME` on a new `virtualHost` in an `nginix` configuration.

### Expected behavior
The new configuration is applied without errors.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-21.11, nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by arximboldi** [comment]
I'm actually not sure anymore this was the root cause, as some investigation seems to imply that it was some of the other options at play...

**Comment by Sleepful** [comment]
Yeah I had something similar happen to me. I definitely was doing double-deploys, first without the virtualhost and only with the catchall for the challenge, and a second deploy with the virtualhost after the cert was generated.

**Comment by Sleepful** [comment]
Can this be re-opened? there should be an update on the docs at least?

**Comment by ChrisDeadman** [comment]
Same issue here, I always have to do double-deploys.

**Comment by Sleepful** [comment]
@ChrisDeadman 

I am no longer using `forceSSL`, now I use `onlySSL` and it works better.
First you add a catchall for the challenge:

```
      "acmechallenge.domain.tld" = {
        # Catchall vhost, will redirect users to HTTPS for all vhosts
        serverAliases = [ "*.domain.tld" ];
        locations."/.well-known/acme-challenge" = {
          root = acme.webroot;
        };
        locations."/" = {
          return = "301 https://$host$request_uri";
        };
```
Then you add your vhosts with `onlySSL`

```
      "subdomain.domain.tld " = {
        onlySSL = true;
        useACMEHost = "domain.tld";
      };
```

This requires

```
  security.acme.certs."domain.tld" = {
    webroot = acme.webroot;
    extraDomainNames = [ "subdomain.domain.tld" ];
  };
```
The problem with `forceSSL` is that it creates a vhost for the `http` route which redirects to the `https` version, this obscures the catch-all for the challenge.
