### ISSUE TITLE
qt6ct and qt6Packages.qtstyleplugins-kvantum are not working together

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#239909]
### Describe the bug
Setting `QT_QPA_PLATFORMTHEME=qt5ct` or `QT_QPA_PLATFORMTHEME=qt6ct` and `QT_STYLE_OVERRIDE=kvantum` is not working. This is what happens when I run the `qt6ct` application via command-line:

```console
$ qt6ct
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: qt6ct-style, Windows, Fusion
Configuration path: "/home/thiagoko/.config/qt6ct"
# ...
```

However doing the same and running `qt5ct` works as expected. I am assuming we are missing a wrap or something here.

### Steps To Reproduce
1. `nix-shell -p qt6Packages.qtstyleplugin-kvantum qt6ct`
2. Run `export QT_QPA_PLATFORMTHEME=qt6ct` `export QT_STYLE_OVERRIDE=kvantum`
3. Run `qt6ct`

### Expected behavior
`qt6ct` should work correctly and you should see `kvantum` styles in the `Style` dropdown.

### Screenshots

- qt5ct
![2023-06-26_12-05-18-screenshot](https://github.com/NixOS/nixpkgs/assets/844343/5af379ad-b605-46a9-987b-63a661e6ca71)

- qt6ct
![2023-06-26_11-58-28-screenshot](https://github.com/NixOS/nixpkgs/assets/844343/74615679-d1ac-46ab-982a-920adfb00fbc)

Ignore the `The application is not configured correctly`. This happens because of the `QT_STYLE_OVERRIDE=kvantum`, and while this is not recommended by `qt6ct` [it is recommended by `kvantum`](https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md).

### Additional context
I am using the [qt module in Home-Manager](https://github.com/nix-community/home-manager/blob/master/modules/misc/qt.nix), but in case of issues in the module I am happily to port any fixes to it.

### Notify maintainers

- kvantum maintainers: @romildo @Scrumplex 

- qt6ct maintainers: @Flakebi @Scrumplex 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.4-zen1, NixOS, 23.11 (Tapir), 23.11.20230623.3ae20aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/h26619k1aq8xj025905p5qqsxj8xdcmm-source`
```

**Comment by Flakebi** [comment]
I can reproduce an issue with inconsistent looking themes, but qt6ct works with kvantum for me. I have some dark theming in qt5 and qt6, but the style is inconsistent.

In addition to your settings, I also have this in `.config/qt6ct/qt6ct.conf`:
```ini
[Appearance]
style=kvantum
…
```

My `.config/Kvantum/kvantum.config`:
```ini
[General]
theme=KvArcDark
```

Config, that I have that is related to theming:
```
  environment.systemPackages = with pkgs; [
      arc-kde-theme
      libsForQt5.frameworkintegration
      kde-gtk-config
      kwayland-integration
      qt5.qtwayland
      libsForQt5.qtstyleplugin-kvantum
      qt6.qtwayland
      kvantumQt6
      qt6ct
      qtstyleplugin-kvantum-qt4
  ];

    environment.variables = {
      QT_STYLE_OVERRIDE = "kvantum";
      QT_QPA_PLATFORMTHEME = lib.mkForce "qt6ct";
  };

    qt = {
      enable = true;
      platformTheme = "qt5ct";
    };
```

**Comment by Scrumplex** [comment]
If you set `QT_QPA_PLATFORMTHEME` to qt6ct, Qt 5 apps will not be themed using either qt5ct or qt6ct. If you set it to qt5ct both Qt 5 and Qt 6 app should use qt5ct and qt6ct respectively.

You shouldn't need to add qt6ct to `environment.systemPackages` either as that's already done by `qt.platformTheme = "qt5ct"`

**Comment by thiagokokada** [comment]
Ok, so if I set:

```
# NixOS
qt = {
  enable = true;
  platformTheme = "qt5ct";
};
```

It works for both `qt5ct` and `qt6ct`, however:

```
# Home-Manager
qt = {
  enable = true;
  platformTheme = "qtct";
};
```

Only works in `qt5ct`, even if it basically does the same (export `QT_QPA_PLATFORMTHEME=qt5ct`). If you set both in NixOS and Home-Manager it also works.

So I assume the issue here is either that `qt5ct` only works when added to `environment.systemPackages` (but doesn't work with the Home-Manager equivalent, `home.packages`) or is that the NixOS module is adding extra packages that are missing in the Home-Manager module.

**Comment by thiagokokada** [comment]
I double checked the packages that the NixOS modules adds vs Home-Manager and it doesn't seem they're doing anything different (both add `libsForQt5.qtstyleplugin-kvantum` and `qt6Packages.qtstyleplugin-kvantum` when `qt.platformTheme = "qt{,5}ct"` is set). So I assume it is something that `environment.systemPackages` is doing that makes it work.

I am also curious why `home.packages` works in `qt5ct` and not in `qt6ct`. Maybe whatever `qt5ct` is doing could be backported to `qt6ct` so this could be fixed for every use case.

**Comment by Scrumplex** [comment]
Maybe this? https://github.com/NixOS/nixpkgs/blob/094681cd1e14261333f503bcbfacbb62362b686a/nixos/modules/config/qt.nix#L111-L116

It's very important that both Qt 5 and Qt 6 plugin paths are linked

**Comment by thiagokokada** [comment]
> Maybe this?
> 
> https://github.com/NixOS/nixpkgs/blob/094681cd1e14261333f503bcbfacbb62362b686a/nixos/modules/config/qt.nix#L111-L116
> 
> It's very important that both Qt 5 and Qt 6 plugin paths are linked

Interesting that the Qt modules in Home-Manager does neither of them, and `qt5ct` still works.

But I will try this later.

**Comment by thiagokokada** [comment]
> Maybe this?
> 
> https://github.com/NixOS/nixpkgs/blob/094681cd1e14261333f503bcbfacbb62362b686a/nixos/modules/config/qt.nix#L111-L116
> 
> It's very important that both Qt 5 and Qt 6 plugin paths are linked

Just setting those 2 environment variables in my config did the trick. So I think this is actually an bug with Home-Manager module where we need to setup those 2 variables too.

**Comment by thiagokokada** [comment]
Going to close this issue since I opened a PR in Home-Manager to fix this issue: https://github.com/nix-community/home-manager/pull/4579

**Comment by diniamo** [comment]
I have this exact issue, with the only difference being that it happens even with both the NixOS and the HM module enabled, I have also tried enabling either one. My configuration has been working for a while, and I didn't change anything, meaning it broke because of updating nixpkgs. Any ideas?

**Comment by eljamm** [comment]
This happened to me lately as well. Bisecting nixpkgs, I traced the issue back to [qt6: 6.7.3 -> 6.8.0 · NixOS/nixpkgs@d4f7b84](https://github.com/NixOS/nixpkgs/commit/d4f7b842c6eb8a34930566274249602964a301fc)

**Comment by diniamo** [comment]
@K900 any idea what's going on?

**Comment by K900** [comment]
Fixed in staging-next, please don't necropost.

**Comment by Scrumplex** [comment]
@diniamo @eljamm see #350514

**Comment by diniamo** [comment]
I couldn't find that issue when I last looked.
