### ISSUE TITLE
Trying to make use of `lib.systems.architectures.features`

### ISSUE THREAD

**Issue by spikespaz** [NixOS/nixpkgs#240045]
I have looked into [`lib/systems/architectures.nix`](https://github.com/NixOS/nixpkgs/blob/master/lib/systems/architectures.nix) and found that the predicates at the bottom of the file are used [here](https://github.com/NixOS/nixpkgs/blob/548c591cb971db62395589e1ff88af25068096c2/lib/systems/default.nix#L234).

I have a Ryzen 7 4750u and desire to enable all the available features that GCC can use and/or compile with.
When `import nixpkgs`, I tried setting `localSystem` to:
```
{
  system = "x86_64-linux";
  gcc.arch = "znver2";
}
```

This results in the following error:
```
error: a 'x86_64-linux' with features {gccarch-znver2} is required to build '/nix/store/zy4h2yj3ssv8q582lzl613w64zgi5z3m-bootstrap-stage0-glibc-bootstrapFiles.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

What is the intended usage of these platform feature flags? I could set them individually, but when there's already machinery in place to handle this, well...

**Comment by Shawn8901** [comment]
You need to set system feature for the nix daemon. So it does not know that it is able to build znver2 things in your case.

That can be archived by setting something like
```nix
  nix.settings.system-features = ["gccarch-znver2" "benchmark" "big-parallel" "kvm" "nixos-test"];
```
Not sure if you need to set everything after gccarch-znver2, possibly that is already set by the system. 
After that change is enabled you should be able to bootstrap the system.

**Comment by yl3dy** [comment]
You have to set `system-features` for Nix for `localSystem` to work correctly, the error message says exactly that. E.g. in `configuration.nix`:

```nix
nix.extraOptions = ''
  system-features = system-features = nixos-test benchmark big-parallel kvm gccarch-znver2
'';
```

However, it's not guaranteed that an actual `-march=znver2` will be used, `stdenv.hostSystem.*` functions have to be explicitly used in a derivation. An alternative might be to wrap stdenv with `wrapCFlags` and specify desired ones. See also [wiki](https://nixos.wiki/wiki/Build_flags).

But next time please use https://discourse.nixos.org for support questions.
