### ISSUE TITLE
Incorrect dependencies for cmp-related vimPlugins

### ISSUE THREAD

**Issue by stasjok** [NixOS/nixpkgs#240108]
### Describe the bug
Many cmp-* plugins have dependencies like curl, fish, tmux etc. But those are not plugins. In result those programs are added to nvim runtimepath. Looks like it was introduced by https://github.com/NixOS/nixpkgs/commit/60ba9d65d326687bfec3a68f2c734a32cbbdd038.

### Steps To Reproduce
1. Build package e.g. `neovim.override {configure = {packages.myVimPackage = {start = [vimPlugins.cmp-git];};};}`
2. vim-pack-dir now contains curl and git directories.

### Expected behavior
Binaries should not be linked to runtimepath. Paths to binaries should be replaced in plugin source code or added to nvim's PATH (does it work with propagatedBuildInputs?).

### Notify maintainers

@theHedgehog0, @figsoda, @teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by figsoda** [comment]
#242327
