### ISSUE TITLE
"nix-shell -p pythonPackages.setuptools" not working

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#24011]
## Issue description

```nix-shell -p pythonPackages.setuptools``` doesn't create an environment where "setuptools" can be imported.

### Steps to reproduce

```
$ NIX_PATH=nixpkgs=$PWD nix-shell -p pythonPackages.setuptools --run "python -c 'import setuptools'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools
```

However, if I replace ```pythonPackages.setuptools``` above with something random like ```pythonPackages.mechanize```, the "import setuptools" statement runs just fine!

## Technical details

* System: NixOS
* Nix version: 1.11.7
* Nixpkgs version: 17.09.git.beb3493 (master as of today). Also happens on release-16.09 branch.

**Comment by FRidh** [comment]
Add the `--pure` flag and see what happens.

Spoiler: `setuptools` doesn't propagate `python` so you're using your system Python.

**Comment by FRidh** [comment]
We can add `python` to `propagatedBuildInputs` for consistency. Note that unstable will have https://github.com/NixOS/nixpkgs/pull/22210 soon.

**Comment by bjornfor** [comment]
@FRidh: You're absolutely right.

Adding --pure:

```
NIX_PATH=nixpkgs=$PWD nix-shell --pure -p pythonPackages.setuptools --run "python -c 'import setuptools'"
/run/user/1000/nix-shell.HQesmE/rc: line 1: python: command not found
```

Adding python:

```
NIX_PATH=nixpkgs=$PWD nix-shell --pure -p pythonPackages.setuptools -p python --run "python -c 'import setuptools'"
(no error)
```

Thank you!

I find it weird that it worked with 'mechanize' (arbitrary package) but not 'setuptools' though...

**Comment by bjornfor** [comment]
> We can add python to propagatedBuildInputs for consistency. 

Yes please :-)

**Comment by FRidh** [comment]
> I find it weird that it worked with 'mechanize' (arbitrary package) but not 'setuptools' though...

`mechanize` uses `buildPythonPackage` which adds `python`. `setuptools` is build differently.

> > We can add python to propagatedBuildInputs for consistency.
> Yes please :-)

Let's wait till Hydra has catched up since this is a mass-rebuild.
