### ISSUE TITLE
The LLVM expressions are copied and pasted like crazy

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24015]
Very frustrating having to update the exact same code in a dozen locations, and to account for silly issues introduced by accidental differences between them. It'd be nice to factor the expressions more nicely.

**Comment by vcunat** [comment]
I've seen quite a few people suggesting that, but so far noone has found the time...

**Comment by copumpkin** [comment]
> Well, of course _I_ don't have the time, but all of you...

**Comment by mmahut** [comment]
I guess we can close this, anyone with spare time can improve it with a pull request.
