### ISSUE TITLE
buildNpmPackage fails to build git dependencies

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#240243]
### Describe the bug
I'm trying to package `pyright` with `buildNpmPackage`, but it fails when it tries to install a npm dependency which points to public git repository.

Pyright depends in jackspeak==2.1.4 which in turn depends on `"cliui": "github:isaacs/cliui#isaacs/esm-cjs-consistency"`. 

When I try to build the expression below, it fails with:
```shell
...
ERROR: npm failed to install dependencies

Here are a few things you can try, depending on the error:
1. Set `makeCacheWritable = true`
  Note that this won't help if npm is complaining about not being able to write to the logs directory -- look above that for the actual error.
2. Set `npmFlags = [ "--legacy-peer-deps" ]`
```
Unfortunately, using neither `makeCacheWritable`, nor `npmFlags` help.

With the `--verbose` flags, it seems to be that `prefetch-npm-deps` didn't handle the git repository correctly, and `npm ci` tries to refetch it, hence it fails on nix sandbox.
```shell
...
Installing dependencies
npm verb cli /nix/store/8lmzw9jisghs9kih9xqxk5cypn6d678z-nodejs-18.16.1/bin/node /nix/store/8lmzw9jisghs9kih9xqxk5cypn6d678z-nodejs-18.16.1/bin/npm
npm info using npm@9.5.1
npm info using node@v18.16.1
npm verb logfile could not create logs-dir: Error: EACCES: permission denied, mkdir '/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_logs'
npm verb title npm ci
npm verb argv "ci" "--loglevel" "verbose" "--ignore-scripts" "--omit" "optional"
npm verb logfile logs-max:10 dir:/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_logs/2023-06-28T01_48_33_215Z-
npm verb logfile could not be created: Error: ENOENT: no such file or directory, open '/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_logs/2023-06-28T01_48_33_215Z-debug-0.log'
npm verb logfile no logfile created
npm verb stack Error: EACCES: permission denied, mkdir '/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_cacache/tmp'
npm verb cwd /private/tmp/nix-build-pyright-1.1.316.drv-1/source
npm verb Darwin 20.6.0
npm verb node v18.16.1
npm verb npm  v9.5.1
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_cacache/tmp
npm ERR! errno -13
npm verb Error: EACCES: permission denied, mkdir '/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps/_cacache/tmp' 
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 301:30000 "/nix/store/nhs2z4k96x9yafy454vc8mxww2wj1h5q-pyright-1.1.316-npm-deps"
npm verb exit -13
npm verb unfinished npm timer reify 1687916913847
npm verb unfinished npm timer reify:unpack 1687916913969
npm verb unfinished npm timer reifyNode:node_modules/jackspeak/node_modules/cliui 1687916913984
npm verb code -13
...
```

### Steps To Reproduce
1. Use the following expression:
   ``` nix
   { lib, buildNpmPackage, fetchFromGitHub }:

   buildNpmPackage rec {
     pname = "pyright";
     version = "1.1.316";

     src = fetchFromGitHub {
       owner = "microsoft";
       repo = "pyright";
       rev = version;
       hash = "sha256-o4SErHXbnL+glnHmZ1ZEeDqnoh7DptJ2h0hzxqjMFBE=";
     };

     npmDepsHash = "sha256-NVcjgQqB48I3Vxkl86+JoEQW+w+NAsoeToXUC/Lb3iY=";

     forceGitDeps = true;

     npmInstallFlagsArray = [
       "--omit=optional"
     ];
   }
   ```
2. it fails

### Expected behavior
buildNpmPackage/prefetch-npm-deps should handle git dependencies

### Notify maintainers
@winterqt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs-22.05pre335126.391f93a83c3"`
 - nixpkgs: `/Users/marsam/code/nix-config/nixpkgs`

```

**Comment by lilyinstarlight** [comment]
If you need `forceGitDeps = true`, then it's an upstream issue and unlikely to work in any reproducible manner (because the dev deps needed to build git dependencies aren't locked anywhere)

**Comment by lilyinstarlight** [comment]
I'll take a look at this particular derivation in a bit though and see what I can come up with to workaround it

**Comment by lilyinstarlight** [comment]
Looking at it, I think your best options here are to either 1) bug upstream at https://github.com/isaacs/cliui to add a package-lock.json, 2) bug upstream to publish to npm registry (so that way it can be downloaded as a dep pre-built), or 3) patch out the build scripts from cliui package and manually run `tsc` yourself on that dep

**Comment by lilyinstarlight** [comment]
Unfortunately this isn't (yet) something we can do anything about

I have some questionably bad ideas to deal with specific cases of dependencies that lack integrity hashes and/or resolved URLs in lockfiles that could be generalized to this kind of problem for transitive dev deps too, but I doubt it would work well and it'll be a bit before I have the stuff together to make even that work (I'm having to rewrite lockfile fixup)

Really if every dependency is not locked, there's no much we can do about it that isn't a major hack in the end

**Comment by SuperSandro2000** [comment]
I think this should be mentioned in the error message as it is not very obvious even from the verbose log.
