### ISSUE TITLE
SmartGit Flatpak unable to access Nix Store

### ISSUE THREAD

**Issue by x80486** [NixOS/nixpkgs#240240]
### Describe the Bug

NixOS installs/places most files as references on the Nix Store. Flatpak applications, on the other hand, are sandboxed — for good reasons.

What currently happens with SmartGit, and probably with many other Flatpak applications as well, is that SmartGit is unable to access the Git config file, or the SSH config file, because these are syslinks to somewhere in the Nix Store.

### Steps To Reproduce

1. Manage your Git and/or SSH configuration with Home Manager
2. Install SmartGit Flatpak
3. Try to clone (or do any operation for that matter with) any repository

### Expected behavior

Flatpaks should be able to access the files and behave accordingly.

### Additional context

In this case, SmartGit does have `host` access, so in theory it should even have access to the entire system, but it doesn't.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[x80486@uplink:~]$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.05 (Stoat), 23.05.1272.ecb441f2206`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(x80486): `"home-manager-23.05.tar.gz"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Have you enabled the flatpak module
