### ISSUE TITLE
R2modman cant launch steam games

### ISSUE THREAD

**Issue by uricot** [NixOS/nixpkgs#240369]
### Describe the bug
When you try to start any game from r2modman both modded and vanilla you get a terminal like window saying that 

"You are missing the following 32-bit libraries, and steam may not run:
libc.so.6
Press enter to continue: "

After pressing enter the terminal like window closes

### Steps To Reproduce
1. Install r2modman 
2. Launch any game using r2modman

### Expected behavior
The game should launch 

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/76900289/5af4b588-a7de-47c3-99d5-cb555dc057e7)

### Additional context
Steam is installed using nixos options

### Notify maintainers
@huantianad 
@aidalgol 

(I might be stupid or something but i cant find where meta.maintainers list is)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[uricot@nixos-uricot:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.11 (Tapir), 23.11pre499022.e18dc963075`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(uricot): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aidalgol** [comment]
This is a known issue, and I am still unsure of the best way to solve it.  On NixOS, if you want to launch a Steam game from outside the Steam launcher, you would have to run it via `steam-run`.  I chose not to wrap r2modman in the Steam FHS environment, because it can be used with non-Steam games, but doing so may be the most reliable way to let it run non-Steam games as well.

The way I have been using r2modman is only to install mods, then modify the launch command for the game in Steam to run the game through the r2modman profile for said game.

@huantianad Do you think we should wrap r2modman in an FHS environment like we do for Lutris and Heroic?

**Comment by huantianad** [comment]
Honestly I'm not too sure either. One downside of using `steam-run` as part of r2modman is that it makes the package depend on a non-free derivation, but that's not too big of a deal. 

Is there a way to have the steam runner in `~/.steam/steam` use the steam fhs env? That seems like what r2modman is trying to run. However, this doesn't solve the issue of non-steam games.

What exactly is the best user experience for those running non-steam games? I think using a FHS env is the only way to get those games to run. Ideally I wouldn't like to maintain a FHS environment specifically for r2modman as well, could we borrow the steam fhs env?

**Comment by uricot** [comment]
> This is a known issue, and I am still unsure of the best way to solve it. On NixOS, if you want to launch a Steam game from outside the Steam launcher, you would have to run it via `steam-run`. I chose not to wrap r2modman in the Steam FHS environment, because it can be used with non-Steam games, but doing so may be the most reliable way to let it run non-Steam games as well.
> 
> The way I have been using r2modman is only to install mods, then modify the launch command for the game in Steam to run the game through the r2modman profile for said game.
> 
> @huantianad Do you think we should wrap r2modman in an FHS environment like we do for Lutris and Heroic?

So what should i do for now? Can you please share the command to launch modded version of the game?

**Comment by huantianad** [comment]
If you want to find the additional launch arguments to give to steam to launch the modded version, r2modman displays it in the help section:
![image](https://github.com/NixOS/nixpkgs/assets/20760920/c9e00b2f-d1fa-4422-94fa-c640f5bfbe51)

**Comment by uricot** [comment]
Thanks!

**Comment by aidalgol** [comment]
Reopening, as I do want to address this issue in the `r2modman` package somehow.

**Comment by mibmo** [comment]
@aidalgol hi there. Are you perhaps planning on contributing [your change](https://github.com/mkg20001/nixpkgs/commit/01ed37376e8221bf68c9307e0e892fa3137f25e0) into nixpkgs?

**Comment by aidalgol** [comment]
@mibmo Yes, please open a separate ticket.
