### ISSUE TITLE
nixos-rebuild: error with glibc-2.37

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#240366]
### Describe the bug
I use NixOS 23.05 with the hardened kernel and home manager. I have installed almost all programs with home manager and I can update them normally. But when I run  `sudo nixos-rebuild boot` to update the system I get the following error message: 

`error: getting status of '/nix/store/gkx2vhaac9bja05ip3ah91qd98l6ccf9-glibc-2.37.tar.xz': No such file or directory`

Otherwise, no other error messages occurred

### Metadata

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.32-hardened1, NixOS, 23.11 (Tapir), 23.11pre493630.75a5ebf473c`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(name): `"home-manager"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Closing because account got deleted
