### ISSUE TITLE
Drop the automation for #118661

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#240314]
### Describe the bug
GitHub action for monitoring direct pushes to master generates random false positives with no true positives in recent memory

### Steps To Reproduce
1. Merge a PR using the GitHub button
2. Get slightly unlucky.
3. Get noise notification from the action.

### Expected behavior
Nothing after the merge.

### Screenshots
#118661 is full of references to the noise notifications.

### Notify maintainers

@domenkozar I guess?

**Comment by infinisil** [comment]
I just opened an RFC to disallow direct pushes, which would resolve this: https://github.com/NixOS/rfcs/pull/156

**Comment by infinisil** [comment]
The bot is now removed, see https://github.com/NixOS/nixpkgs/issues/249117 and https://github.com/NixOS/nixpkgs/pull/249151 :smile:
