### ISSUE TITLE
Update request: obs-studio-plugins.input-overlay 5.0.0 → 5.0.4

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#240407]
- Package name: obs-studio-plugins.input-overlay
- Latest released version: 5.0.4

- Current version on the unstable channel: 5.0.0
- Current version on the stable/release channel: 5.0.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@glittershark 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/250960

**Comment by pbsds** [comment]
closed in https://github.com/NixOS/nixpkgs/pull/250960
