### ISSUE TITLE
Package request: CRONOMIX

### ISSUE THREAD

**Issue by arnvgh** [NixOS/nixpkgs#240540]
**Project description**

# Cronomix

**All-in-one timer, stopwatch, pomodoro, alarm, todo and time tracker gnome-shell extension**

![preview](https://github.com/zagortenay333/cronomix/raw/master/data/images/screenshots/todo.png)

**Metadata**

* homepage URL: https://github.com/zagortenay333/cronomix
* source URL: https://github.com/zagortenay333/cronomix
* license: mit
* platforms: unix, linux

**Comment by AndrewKvalheim** [comment]
Have you seen [`gnomeExtensions.cronomix`](https://search.nixos.org/packages?type=packages&channel=23.11&show=gnomeExtensions.cronomix)?
