### ISSUE TITLE
Update request: ultrastardx 2021-04-03 → v2023.6.0

### ISSUE THREAD

**Issue by pfirpfel** [NixOS/nixpkgs#240524]
- Package name: ultrastardx
- Latest released version: [v2023.6.0](https://github.com/UltraStar-Deluxe/USDX/releases/tag/v2023.6.0)
- Current version on the unstable channel: 2021-04-03
- Current version on the stable/release channel: 2021-04-03
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Profpatsch

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/250959
