### ISSUE TITLE
Rebuilt and switched to NixOS 17.03 and rebooting results in "Unsupported bzimage"

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#24055]
I was upgrading from a 16.03 to 17.03 (from nixpkgs channels).

After running nixos-rebuild switch it resulted in some errors, but sudo broke so I had to restart.

Upon restarting, the systemd boot tells me about 2 NixOS generations, trying to launch either one results in: `Error loading \efi\nixos\6126kaj2jq...-linux-4.1.38-bzImage.efi: Unsupported`.

Then I booted into my second boot partition, successfully ran `nixos-rebuild switch --install-bootloaders`, still resulted in the same error.

Something's wrong with the systemd-boot and/or the bzimage efi on 17.03.

**Comment by vcunat** [comment]
If the process got interrupted, perhaps some of the files in there are broken.  If possible, I'd personally try to clear the boot stuff and reinstall it anew by `nixos-rebuild`.

**Comment by CMCDragonkai** [comment]
Might try that next but I'll have to refresh my memory on how my luks keys are stored.

**Comment by globin** [comment]
`systemd-boot` has worked for me flawlessly on 17.03

**Comment by CMCDragonkai** [comment]
Reinstalled and recopied so it's fine now.
