### ISSUE TITLE
building with bazel

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#24063]
I want to add [google/re2](https://github.com/google/re2/tree/master/re2) to the [libraries](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries).

I saw that re2 was not available yet, I decided to give it a shot.

```
git clone git@github.com:google/re2.git
cd re2
nix-env -i bazel
bazel build re2
```

```
INFO: Found 1 target...
ERROR: /home/gui/re/re2/BUILD:11:1: Linking of rule '//:re2' failed: Process exited with status 1 [sandboxed].
src/main/tools/linux-sandbox-pid1.cc:598: "execvp(/usr/bin/ar, 0x9cbc70)": No such file or directory
Use --strategy=CppLink=standalone to disable sandboxing for the failing actions.
Target //:re2 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.889s, Critical Path: 6.76s
```

I'm new to Bazel, I took a look to the documentation. It look like I need to use a [custom toolchain](https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain#introduction).

**Comment by dtzWill** [comment]
I'm not familiar with bazel either, but it looks like re2 has support for building with `make` --and in fact that's what [the re2 README](https://github.com/google/re2/blob/f439f24f4038bd97209500aba44c01bfa6890df1/README#L8) suggests using.  I gave it a try and it seems to work here.  As an aside we kinda do build re2 but not individually, it's built as part of bloaty (git submodule).

Anyway, my first attempt to reproduce failed (in that I built it without problem) on 17.03, doing something like:

```
$ nix-shell -p bazel
$ bazel build re2
```

Looking at your error it seems the difference is the missing `ar`--and indeed:

```
$ which ar
/home/will/.nix-profile/bin/ar
```

Trying again with `nix-shell --pure -p bazel` produces the same error you encountered.

Looking at [how we build bazel](https://github.com/NixOS/nixpkgs/blob/1f709ad136ff18b209638372a0b48345cf1f4fa6/pkgs/development/tools/build-managers/bazel/default.nix) it looks like we add `stdenv.cc` to `PATH` which is our gcc-wrapper and contains `cc`/`as`/`ld` but not `ar`.

Sounds like the fix would be to add `ar` to bazel's PATH as well?

**Comment by dtzWill** [comment]
I've been bitten by this before, is there a reason to not propagate `ar` in the cc-wrapper [like we do `as`](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/build-support/cc-wrapper/default.nix#L160)?

**Comment by MasseGuillaume** [comment]
yeah I can also do: `nix-env -i binutils`.

**Comment by dtzWill** [comment]
Yep! Although installing binutils directly was temporarily broken [until recently](https://github.com/NixOS/nixpkgs/issues/18839) in case you run into that.

**Comment by MasseGuillaume** [comment]
Ha I don't know how I missed it:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/re2/default.nix#L3

**Comment by dtzWill** [comment]
Hahaha, awesome.  Should this be closed, then?

**Comment by MasseGuillaume** [comment]
Yeah I guess. The feature request still hold :)
