### ISSUE TITLE
Autogen seems to be broken now

### ISSUE THREAD

**Issue by ndowens** [NixOS/nixpkgs#24069]
## Issue description

Says guile development packages not found

### Steps to reproduce

nox-review pr 24067 and others that need autogen

## Technical details

checking pkg-config is at least version 0.9.0... yes
configure: checking for guile 2.0
configure: checking for guile 1.8
configure: error:
No Guile development packages were found.

Please verify that you have Guile installed.  If you installed Guile
from a binary distribution, please verify that you have also installed
the development packages.  If you installed it yourself, you might need
to adjust your PKG_CONFIG_PATH; see the pkg-config man page for more.

builder for ‘/nix/store/djcjs536mxjkabkm8dyha2fh8g6c4y4m-autogen-5.18.7.drv’ failed with exit code 1

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by copumpkin** [comment]
@LnL7 says https://github.com/NixOS/nixpkgs/pull/24066 probably caused it

**Comment by LnL7** [comment]
I assume so, it looks for `1.8` and `2.0` but the version is `2.2` now

**Comment by 7c6f434c** [comment]
Sorry… Fixed now.

**Comment by aggarwalanubhav** [comment]
> ## Issue description
> Says guile development packages not found
> 
> ### Steps to reproduce
> nox-review pr 24067 and others that need autogen
> 
> ## Technical details
> checking pkg-config is at least version 0.9.0... yes
> configure: checking for guile 2.0
> configure: checking for guile 1.8
> configure: error:
> No Guile development packages were found.
> 
> Please verify that you have Guile installed. If you installed Guile
> from a binary distribution, please verify that you have also installed
> the development packages. If you installed it yourself, you might need
> to adjust your PKG_CONFIG_PATH; see the pkg-config man page for more.
> 
> builder for ‘/nix/store/djcjs536mxjkabkm8dyha2fh8g6c4y4m-autogen-5.18.7.drv’ failed with exit code 1
> 
> * System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
> * Nix version: (run `nix-env --version`)
> * Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

I get the same error in mac os Catalina 10.15.4. How do I resolve this issue?

**Comment by vcunat** [comment]
I don't know.  Apparently it [doesn't happen on Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/autogen.x86_64-darwin).  My first guess would be that sandboxing could mitigate the issue.
