### ISSUE TITLE
NixOS install-grub.pl script doesn't handle GPT bios boot partition

### ISSUE THREAD

**Issue by yuriy-yarosh** [NixOS/nixpkgs#24065]
## Issue description
[install-grub.pl](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/grub/install-grub.pl) script doesn't handle GPT bios boot partitions properly.

In case of using GPT with the bios boot partition `install-grub.pl` thinks that it's a `/boot` volume. It also uses the `/dev/disk/by-partuuid` instead of `/dev/disk/uuid` for the `search` grub command, which causes `$grubBoot->path` to be incorrect, and grub simply can't find respective the `$grubBoot` device.

So, here's what I'm [getting now](http://pastebin.com/raw/ypUKTNGt).
Drive1 with `partuuid` `786ea1be-eb0f-46d3-9938-90698c48246d` is the bios boot partition, and Drive2 is the root partition with `uuid` `27f31e25-fdc9-4b2b-bf2b-1c7ad25d47a0`.

The problem is that Drive1 with the respective `partuuid` can't be found with the `search` grub command that way. Bios boot partition simply has no `uuid` and it has no filesystem obviously.

I'm using [nixos-in-place](https://github.com/jeaye/nixos-in-place/) to replace some of my current  Arch production servers with Nixos.

I have to reinstall grub second time because `install-grub.pl` script uses `--root-directory` option instead of `--boot-directory`. `--root-directory` is obsolete and `grub-install` will not write the respective image into the bios boot partition with the `--root-directory` option. In my case, I've got Arch's grub image there already, so it should be rewritten.

I also posted this in [gitter chat room](https://gitter.im/NixOS/chat)

### Steps to reproduce
1. Partition a GPT with first bios boot partition and a second root partition, without any EFI related stuff.
2. Populate with default config via `nixos-generate-config`.
3. Set the respective boot.loader.grub.device, boot.loader.grub.storePath and fileSystems config options.
4. Install the system with `nixos-install` script.
5. Watch the boot errors due inability to locate the respective partition. Although it doesn't prevent system from booting it's not viable behaviour for a production ready system.

## Technical details

* System: `16.09.1836.067e66a (Flounder)` minimal iso on Upstream ArchLinux `2017.03.01`
* Nix version: `nix-env (Nix) 1.11.7`
* Nixpkgs version: `16.09.1836.067e66a`

**Comment by butterflya** [comment]
The installation instructions for NixOS (don't know about `nixos-in-place`) are flawed in my experience in the sense that it doesn't take into account device naming semantics on Linux. 

I'd say that should be the first problem that needs to be fixed; afterwards more advanced usecases, like the one you are describing could be resolved.

**Comment by yuriy-yarosh** [comment]
@butterflya well, device naming had been changed like several times already - there are distro's that just can't keep up with all the `enp0s3` stuff. I do not understand how, and why device naming could be an actual issue.

GPT and ESP are very common nowadays, there's nothing really advanced about it.

`install-grub.pl` could simply check the partition GUID with `blkid -p` which would be always `21686148-6449-6E6F-744E-656564454649`. Which in fact an ASCII string "Hah!IdontNeedEFI".
So, there's nothing really complicated about it :D

**Comment by butterflya** [comment]
@yuriy-yarosh It was not my intention to start a discussion regarding what is or is not advanced. Fact is that device naming semantics is not integrated into the user guide of NixOS. The general point I tried to make is that NixOS installation procedure has a lot to be desired and in turn that users shouldn't expect too much of it, currently. 

NixOS currently requires one to understand and be aware of these limitations.

**Comment by mmahut** [comment]
I believe this is fixed in the latest installer? Can you double check?

**Comment by yuriy-yarosh** [comment]
@mmahut does not look like so, and I'm way too busy right now to check this.

**Comment by ne9z** [comment]
GRUB does handle GPT-BIOS.  Currently [Root on ZFS guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html) uses a GPT disk with both legacy BIOS and EFI enabled.  You just need to set `boot.loader.grub.devices` correctly.

**Comment by samueldr** [comment]
I'm closing as I believe there is no issue with GPT + bios boot partitions. I've used that particular setup successfully in the past.

@yuriy-yarosh: If this is not right, please feel free to re-open.

Anyone else: feel free to cross-reference this issue in a new issue if you think it is relevant and are hitting issues with setting up GRUB + GPT + legacy boot.
