### ISSUE TITLE
kdeconnect: fatal SSL Error: "The Certificate has expired"

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixpkgs#240606]
### Describe the bug

Using my iPhone and Arch (on i3), kdeconnect worked (though I last tried a few months ago, so this may have changed). Trying on NixOS results in an SSL error. I don't know if this is a NixOS problem, a kdeconnect problem, wayland issue, iOS, or user error; I don't see relevant issues here or on my first look through the KDE bug tracker, but since it worked on arch previously I thought I'd start here. 

The machine in question is NixOS on x86 on sway and an iPhone 13 Pro. 

### Steps To Reproduce
1. `sudo systemctl stop firewall`
2. Run the command below and refresh kdeconnect on the iPhone to see the error:
```console
$(nix build --print-out-paths nixpkgs#kdeconnect)/libexec/kdeconnectd
kdeconnect.core: Disconnecting due to fatal SSL Error:  "The certificate has expired"
```
3. The connection fails and disappears from the iphone, no relevant kdeconnect-cli commands work.

### Expected behavior

kdeconnectd should run without SSL errors, kdeconect-cli command should succeed.

### Notify maintainers

None listed

@pennae per git blame

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.05 (Stoat), 23.05.20230629.d8bb78c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - channels(n8henrie): `""`
 - nixpkgs: `/nix/store/hq5s8rm90w3jgd805059lv2alxmzxbbi-source`
```

**Comment by n8henrie** [comment]
Ah, my quick and dirty look at the blame showed you with both the most recent (by a decent margin) and roughly most numerous lines changed, but I didn't look at the content. Will look deeper.

**Comment by n8henrie** [comment]
Cc @fridh

**Comment by toloveru** [comment]
I messed with this for hours now, and finally found the solution. I was looking at KDE Connect's source code, strace'd the executable, tried to use KDE Connect on Android, iOS and iPadOS... Hours upon hours wasted on this, and many profanities exclaimed along the way. Eventually I found that it's as easy as selecting the two options below and restarting the app. Hopefully it will help you and possibly others coming across this issue.

![IMG_2959](https://github.com/NixOS/nixpkgs/assets/19938179/0159781f-13dc-497e-8006-d39382664f9c)

**Comment by toloveru** [comment]
As for the certificates themselves, it's likely that the iOS application only has a certificate validity of 2 years. Meanwhile the Linux application appears to have a validity of 10 years (at least on Debian). I don't know when exactly I purchased my iPhone anymore, but it may be older than the key on my Linux box. The certificate on my Linux box had a validity from 2021-07-19 until 2031-07-19. It appeared to thus still be valid, but the elapsed validity period of 2 years and 3 days seemed very peculiar to me. In the last 3 days, I don't remember using KDE Connect either. So it may be a matter of 2 years exactly.

**Comment by n8henrie** [comment]
Yup, it took several tries but this eventually got a working connection. Thank you!
