### ISSUE TITLE
IPTSD commands missing, and `/dev/ipts/0` does not exist when building with surface pro kernel

### ISSUE THREAD

**Issue by fdgefgd** [NixOS/nixpkgs#240612]
### Context:
I am trying to use nixos on a surface pro 7 and have imported the surface pro intel software from the nixos-hardware repository, the single finger touch is working, but IPTSD (multitouch and pen drawing) isn't working. I have imported IPTSD package alongside using the surface kernel.

## Bug:
After doing the imports, I can run `iptsd`, but it does not function, and returns 
```
ERROR: ../src/control.c:139: Failed to open /dev/ipts/0: No such file or directory
ERROR: ../src/main.c:106: Failed to start IPTS: No such file or directory
```

While `iptsd` runs (before returning an error`, I have also tried the other 3 commands that go with the iptsd package, and they are not recognized as commands at all.

```console
[user@system:~]$ iptsd-find-hidraw
iptsd-find-hidraw: command not found
```

I do apologise if this is a problem relating to the NixOS surface pro hardware repos rather than the package, but I cannot determine which is causing the error.

### Steps To Reproduce
1. Be on surface pro 7 (8GB RAM, 256GB SSD)
2. Use and update the nixOS-hardware channel
3. Paste `<nixos-hardware/microsoft/surface/surface-pro-intel>` into my `imports` section
4. Put `microsoft-surface.kernelVersion = "6.1.18";` into my configuration.nix
5. Add `pkgs.iptsd` into the configuration.nix file. 
6. Enter the command `sudo nixos-rebuild switch`

Steps 2, 3, and 4 are optional, and the bug will persist even if those steps are not taken.

https://github.com/NixOS/nixos-hardware/issues/658

### Expected behavior
It is expected that the commands `iptsd-find-service` `iptsd-find-hidraw`  `iptsd-check-device` would be available when I have added the `iptsd` package to my nix configuration, but it is somehow unavailable. It is also expected that the IPTSD service will run, rather than returning the error message that it does not exist.

### configuration.nix file
```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
	<nixos-hardware/microsoft/surface/surface-pro-intel>
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  microsoft-surface.kernelVersion = "6.1.18";

  networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/London";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_GB.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the KDE Plasma Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;

  # Configure keymap in X11
  services.xserver = {
    layout = "us";
    xkbVariant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.usr ={
    isNormalUser = true;
    description = "usr";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      firefox
      kate
    #  thunderbird
    ];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;


  #systemd.packages = [ pkgs.iptsd ];
  #services.udev.packages = [ pkgs.iptsd ];

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
  #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #  wget
     pkgs.iptsd
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "22.11"; # Did you read the comment?

}
```

### Notify maintainers
@tomberek @dotlambda 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.18, NixOS, 22.11 (Raccoon), 22.11.4726.6610eb320ef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
This is a nixos-hardware issue.
You are supposed to add `pkgs.iptsd` to `systemd.packages` and `services.udev.packages`.

**Comment by fdgefgd** [comment]
Thank you for your response. I have added `pkgs.iptsd` to `systemd.packages` and `services.udev.packages`, but the same error still persists. I have not gotten any response from nixos-hardware. Can you please help me fix this error?

**Comment by dotlambda** [comment]
I suggest you don't use nixos-hardware. Then iptsd should work fine as long as you use the correct kernel.

**Comment by fdgefgd** [comment]
Alright. How do I use the correct kernel, if I am not using nixos-hardware?

**Comment by fdgefgd** [comment]
@dotlambda sorry to ping, but where do you get the surface kernel if not from nixos-hardware?

**Comment by dotlambda** [comment]
This is what I currently use:
```nix
{ lib, pkgs, ... }:

{
  boot.kernelPackages = pkgs.linuxPackages_6_4;
  boot.kernelPatches = [ {
    name = "linux-surface-config";
    patch = null;
    extraStructuredConfig = with lib.kernel; {
      STAGING_MEDIA = yes;
      FUNCTION_ERROR_INJECTION = yes;
    };
    extraConfig = lib.replaceStrings [ "CONFIG_" "=" ] [ "" " " ] (lib.readFile
      /home/foobar/linux-surface/configs/surface-6.4.config
    );
  } ] ++ map (pname: {
    name = "linux-surface-${pname}";
    patch = /home/foobar/linux-surface/patches/6.4/${pname}.patch;
  }) [
    "0001-surface3-oemb"
    "0002-mwifiex"
    "0003-ath10k"
    "0004-ipts"
    "0005-ithc"
    "0006-surface-sam-over-hid"
    "0007-surface-button"
    "0008-surface-typecover"
    "0009-surface-shutdown"
    "0010-surface-gpe"
    "0011-cameras"
    "0012-amd-gpio"
    "0013-rtc"
  ];

  services.udev.packages = [
    pkgs.iptsd
    pkgs.surface-control
  ];
  systemd.packages = [
    pkgs.iptsd
  ];

  nixpkgs.overlays = [
    (self: super: {
      libwacom = self.callPackage (self.path + "/pkgs/development/libraries/libwacom/surface.nix") {
        inherit (super) libwacom;
      };
    })
  ];
}
```
where `/home/foobar/linux-surface` is a checkout of https://github.com/linux-surface/linux-surface.
You will have to comment out `CONFIG_IPC_CLASSES=y` in `/home/foobar/linux-surface/configs/surface-6.4.config`.

**Comment by dotlambda** [comment]
Here's an improved version of my config.
```nix
{ lib, pkgs, ... }:

let
  kernelVersion = lib.foldl
    (v1: v2: if lib.versionAtLeast v1 v2 then v1 else v2)
    "0.0"
    (lib.attrNames (lib.filterAttrs (n: v: v == "directory") (
      builtins.readDir <linux-surface/patches>
    )));
in {
  boot.kernelPackages = pkgs.${"linuxPackages_" + lib.replaceStrings [ "." ] [ "_" ] kernelVersion};
  boot.kernelPatches = [ {
    name = "linux-surface-config";
    patch = null;
    extraStructuredConfig = with lib.kernel; {
      STAGING_MEDIA = yes;
      FUNCTION_ERROR_INJECTION = yes;
    };
    extraConfig = lib.replaceStrings [ "CONFIG_" "=" ] [ "" " " ] (lib.readFile (
      <linux-surface> + "/configs/surface-${kernelVersion}.config"
    ));
  } ] ++ map (pname: {
    name = "linux-surface-${pname}";
    patch = <linux-surface> + "/patches/${kernelVersion}/${pname}.patch";
  }) [
    "0001-surface3-oemb"
    "0002-mwifiex"
    "0003-ath10k"
    "0004-ipts"
    "0005-ithc"
    "0006-surface-sam-over-hid"
    "0007-surface-button"
    "0008-surface-typecover"
    "0009-surface-shutdown"
    "0010-surface-gpe"
    "0011-cameras"
    "0012-amd-gpio"
    "0013-rtc"
  ];

  hardware.sensor.iio.enable = lib.mkDefault true;

  environment.systemPackages = with pkgs; [ surface-control ];
  users.groups.surface-control = { };
  services.udev.packages = [
    pkgs.iptsd
    pkgs.surface-control
  ];
  systemd.packages = [
    pkgs.iptsd
  ];

  nixpkgs.overlays = [
    (self: super: {
      libwacom = self.callPackage (self.path + "/pkgs/development/libraries/libwacom/surface.nix") {
        inherit (super) libwacom;
      };
    })
  ];
}
```
Make sure to use `nixos-rebuild -I linux-surface=/path/to/linux-surface` or use some other way of populating `<linux-surface>`.
Maybe someone should adapt this in nixos-hardware but I'm not sure there's a way to use `<linux-surface>` there. cc @Mic92

**Comment by Mic92** [comment]
Normal nixos modules inside nixos-hardware will work but not NIX_PATH entries since we also use it with flakes.

**Comment by dotlambda** [comment]
Would a module that only works with flakes or only works without be acceptable?

**Comment by lVentus** [comment]
> Here's an improved version of my config.
> 
> ```nix
> { lib, pkgs, ... }:
> 
> let
>   kernelVersion = lib.foldl
>     (v1: v2: if lib.versionAtLeast v1 v2 then v1 else v2)
>     "0.0"
>     (lib.attrNames (lib.filterAttrs (n: v: v == "directory") (
>       builtins.readDir <linux-surface/patches>
>     )));
> in {
>   boot.kernelPackages = pkgs.${"linuxPackages_" + lib.replaceStrings [ "." ] [ "_" ] kernelVersion};
>   boot.kernelPatches = [ {
>     name = "linux-surface-config";
>     patch = null;
>     extraStructuredConfig = with lib.kernel; {
>       STAGING_MEDIA = yes;
>       FUNCTION_ERROR_INJECTION = yes;
>     };
>     extraConfig = lib.replaceStrings [ "CONFIG_" "=" ] [ "" " " ] (lib.readFile (
>       <linux-surface> + "/configs/surface-${kernelVersion}.config"
>     ));
>   } ] ++ map (pname: {
>     name = "linux-surface-${pname}";
>     patch = <linux-surface> + "/patches/${kernelVersion}/${pname}.patch";
>   }) [
>     "0001-surface3-oemb"
>     "0002-mwifiex"
>     "0003-ath10k"
>     "0004-ipts"
>     "0005-ithc"
>     "0006-surface-sam-over-hid"
>     "0007-surface-button"
>     "0008-surface-typecover"
>     "0009-surface-shutdown"
>     "0010-surface-gpe"
>     "0011-cameras"
>     "0012-amd-gpio"
>     "0013-rtc"
>   ];
> 
>   hardware.sensor.iio.enable = lib.mkDefault true;
> 
>   environment.systemPackages = with pkgs; [ surface-control ];
>   users.groups.surface-control = { };
>   services.udev.packages = [
>     pkgs.iptsd
>     pkgs.surface-control
>   ];
>   systemd.packages = [
>     pkgs.iptsd
>   ];
> 
>   nixpkgs.overlays = [
>     (self: super: {
>       libwacom = self.callPackage (self.path + "/pkgs/development/libraries/libwacom/surface.nix") {
>         inherit (super) libwacom;
>       };
>     })
>   ];
> }
> ```
> 
> Make sure to use `nixos-rebuild -I linux-surface=/path/to/linux-surface` or use some other way of populating `<linux-surface>`. Maybe someone should adapt this in nixos-hardware but I'm not sure there's a way to use `<linux-surface>` there. cc @Mic92

How should I set config of iptsd now? I am confused.
I tried services.iptsd.Touch.DisableOnPalm = true;
Seems doesn't work.
I found that, I should calibrate iptsd, but iptsd-calibrate is commond not found.
I can't run any commonds above, neither.
How should I exactly do?
