### ISSUE TITLE
build-support/fetchgit: fails with repository containing submodules when enabling `leaveGitDir` and `fetchSubmodules`

### ISSUE THREAD

**Issue by 13k** [NixOS/nixpkgs#240797]
### Describe the bug

`fetchgit` fails when using `leaveGitDir = true` and `fetchSubmodules = true` with repositories that contain submodules.

A checked-out repository that contains modules will have `.git` *files* pointing to `.git/modules/<submodule_path>`. git uses `.git` files to "link" submodules gitdirs to the root `.git/modules/<submodule>` path. I'm not sure if this is new git behavior and thus it broke `nix-prefetch-git`. See below in the reproduction section.

`nix-prefetch-git:clone_user_rev()` ([here](https://github.com/NixOS/nixpkgs/blob/67b08d46a1cf2fe7caa4439226f96a0434855b1b/pkgs/build-support/fetchgit/nix-prefetch-git#L327-L329)) tries to list `.git` directories and get their parent paths with `readlink(1)`, but finds `.git` files and `readlink` fails. [Because it's invoked in a command substitution as an argument for another command](https://www.shellcheck.net/wiki/SC2312), it fails silently and won't return an error to the parent shell (and won't trigger `errexit`), so in these cases `make_deterministic_repo ""` is called and fails with "not a git repository" errors.

A possible fix is to use `find "$dir" -type d -name ".git"` to filter directories. I believe this option/value is portable. This will only give `readlink` directory paths and avoid the very subtly error.

### Steps To Reproduce

Checked-out repository with submodule:

```console
> cd "$(mktemp -d)"
> git init
Initialized empty Git repository in /tmp/tmp.rQmCGRJ5ey/.git/
> git submodule add --depth 1 https://github.com/NixOS/rfcs
> git submodule status
e364d5f0cddc03d164f0d7dfc8d6c4f1616364b7 rfcs (heads/master)
> stat rfcs/.git
  File: rfcs/.git
  Size: 29        	Blocks: 8          IO Block: 4096   regular file
  ...
> cat rfcs/.git
gitdir: ../.git/modules/rfcs
```

Emulating the `leaveDotGit = true` branch:

```console
> find "$PWD" -name .git | while read -r gitdir; do echo "make_deterministic_repo '$(readlink -f "$gitdir/..")'"; done
make_deterministic_repo ''
make_deterministic_repo '/tmp/tmp.rQmCGRJ5ey'

> find "$PWD" -name .git
/tmp/tmp.rQmCGRJ5ey/rfcs/.git
/tmp/tmp.rQmCGRJ5ey/.git

> echo "$(readlink -f "/tmp/tmp.rQmCGRJ5ey/rfcs/.git/..")" | xxd
00000000: 0a                                       .
          ^ `echo` receives an empty string and just prints a newline

> readlink -f "/tmp/tmp.rQmCGRJ5ey/rfcs/.git/.."; echo $?
1
```

### Expected behavior

Expected `fetchgit` to correctly fetch a repository with submodules and leave `.git` directories intact when `leaveDotGit` is true.

### Notify maintainers

I'm not sure who are `fetchgit` owners. I'm tagging the last 3 who touched `nix-prefetch-git`: @marsam @domenkozar @fetsorn

### Metadata

```console
> nix shell nixpkgs#nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8-100.fc37.x86_64, Fedora Linux, 37 (KDE Plasma), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - channels(k): `"nixpkgs"`
 - nixpkgs: `/home/k/.nix-defexpr/channels/nixpkgs`
```

**Comment by domenkozar** [comment]
Could be triggered by #238733, if you revert it does it work?

**Comment by 13k** [comment]
I can't test right now, but from a cursory reading, I think it indeed does, because it changed behavior from A) manually getting all submodules urls and manually cloning the repos, which will result in `.git` **directories**, to B) `git submodule update --init --recursive`, which generates `.git` **files**, like I described above.

**Comment by domenkozar** [comment]
> A possible fix is to use find "$dir" -type d -name ".git" to filter directories. I believe this option/value is portable. This will only give readlink directory paths and avoid the very subtly error.

Sounds good, can you make a PR? This also means that probably the hash is now different.

**Comment by luizribeiro** [comment]
I tried adding `-type d` to both of these `find` instances:

https://github.com/NixOS/nixpkgs/blob/48273d596109a034cf154e450dee69705ca2d620/pkgs/build-support/fetchgit/nix-prefetch-git#L323-L329

But I ended up with a non-deterministic hash for some reason - every `nix build` run would result in a different hash.

Reverting #238733 does fix the issue though. @domenkozar, should we revert that commit until this is sorted out?

**Comment by domenkozar** [comment]
I can help fix it if you find a good example within nixpkgs repo to test with.

**Comment by luizribeiro** [comment]
@domenkozar, there are only a few cases where both flags are used in nixpkgs. At least from searching with `rg -C5 fetchSubmodules | grep leaveDotGit | grep -v false`.

Only one I could find was `rippled`:

https://github.com/NixOS/nixpkgs/blob/ac1acba43b2f9db073943ff5ed883ce7e8a40a2c/pkgs/servers/rippled/default.nix#L32-L39

But for some reason it doesn't reproduce this issue.

I'm not sure we currently have a derivation in nixpkgs that reproduces this. I've been able to reproduce this easily with a derivation which uses this `src`:

```nix
stdenv.mkDerivation {
  name = "bedrock-viz";
  src = pkgs.fetchFromGitHub {
    owner = "bedrock-viz";
    repo = "bedrock-viz";
    rev = "6ea2724f7695452fcf4307bbf002ca456c293849";
    hash = "sha256-WsY5jAYl7LB3Sgppi9bE5Lqck5Z9g1o7fakurEUr+C4=";
    fetchSubmodules = true;
    deepClone = true;
    leaveDotGit = true;
  };
}
```

**Comment by Aleksanaa** [comment]
I can reproduce this issue in the following case:

```nix
pname = "appimagelauncher";
  version = "3.0.0-alpha-1";

  src = fetchFromGitHub {
    owner = "TheAssassin";
    repo = pname;
    rev = "v${version}";
    fetchSubmodules = true;
    leaveDotGit = true;
    hash = "";
  };
```

**Comment by domenkozar** [comment]
Could you test #249733

**Comment by 13k** [comment]
I tested with

```nix
  pname = "rubyfmt";
  version = "0.9.5";

  src = fetchFromGitHub {
    owner = "fables-tales";
    repo = "rubyfmt";
    rev = "v${version}";
    leaveDotGit = true;
    fetchSubmodules = true;
    hash = lib.fakeHash;
  };
```

and it worked.

The repository in question [uses `git` to determine revisions at build time](https://github.com/fables-tales/rubyfmt/blob/46e08ebde71f5e816bdde0065c5100f33ee638a7/librubyfmt/build.rs#L231-L232) and even [updates submodules manually](https://github.com/fables-tales/rubyfmt/blob/46e08ebde71f5e816bdde0065c5100f33ee638a7/librubyfmt/build.rs#L42-L43), which triggers the bug in `nix-prefetch-git`.

I wasn't sure what's the best practice when dealing with projects relying on git to build correctly and since it's hardcoded in that project's build script with no trivial solution (like setting an env var or passing a CLI flag), I was actually trying to build it as-is.

Now that I see #215651 landed, my question was answered: just patch it out.

Anyway, the bug still exists and it seems #249733 works for this specific repository, even with all the `git` shenanigans at build time.

Thanks @Aleksanaa @domenkozar
