### ISSUE TITLE
Update request: hal-hardware-analyzer 3.3.0 → 4.2.0

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#240729]
- Package name: hal-hardware-analyzer
- Latest released version: 4.2.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

I tried to do it myself, but I encountered issues with the vendored dependencies. This is an upstream limitation that should be reported. I tried to patch `hal`'s cmake files to allow support for unvendored dependencies, and then add that patch to my Nixpkgs checkout, though without success. My progress is at:

- https://github.com/NixOS/nixpkgs/compare/master...doronbehar:nixpkgs:pkg/hal-hardware-analyzer
- https://github.com/emsec/hal/compare/master...doronbehar:hal:no-vendoring

I encountered this issue while working on https://github.com/NixOS/nixpkgs/pull/240714 .

**Notify maintainers**

@ris @shamilton

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by tobim** [comment]
cc @SCOTT-HAMILTON @risicle.

**Comment by risicle** [comment]
@doronbehar you were 99% of the way there. I've got it working now - will tidy & post tomorrow thanks to your efforts.
