### ISSUE TITLE
Allow use of "mac" as a pinentry flavor

### ISSUE THREAD

**Issue by seh** [NixOS/nixpkgs#240819]
### Describe the bug
At present, the _pkgs/tools/security/pinentry/default.nix_ file defines six supported flavors:
- _curses_
- _emacs_
- _gnome3_
- _gtk2_
- _tty_
- _qt_

The sibling _mac.nix_ file allows use of the _pinentry-mac_ program, but it doesn't enroll it as a supported flavor. Configuration options such as `services.gpg-agent.pinentryFlavor` then don't work correctly with _pinentry-mac_.

### Steps To Reproduce
1. Add "pinentry_mac" to the `home.packages` configuration option.
2. Set the `services.gpg-agent.pinentryFlavor` to "mac".
3. Observe that this configuration is not valid, making it difficult to set the "pinentry-program" option for _gpg-agent_.

### Expected behavior
If the the current operating system is Darwin, and perhaps if the "pinentry_mac" package was loaded, [add "mac" as an enabled pinentry flavor](https://github.com/NixOS/nixpkgs/blob/9790f3242da2152d5aa1976e3e4b8b414f4dd206/pkgs/tools/security/pinentry/default.nix#L5-L7).

### Additional context
I'm not sure what will happen if I try to set the "pinentry-program" option myself. I can see that I can set `services.gpg-agent.pinentryFlavor` to null, and that will disable the automatic writing the "pinentry-program" option. However, that's less convenient than the "flavor" system already in place.

### Notify maintainers
@ttuegel
@fpletz
@Steven0351
@midchildan

### Metadata
```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qb3dg4cx5jzk3pa8szzi0ziwnqy33p50-source`
```

**Comment by seh** [comment]
Only now did I realize that [`services.gpg-agent` is not supported on macOS](https://github.com/nix-community/home-manager/blob/0f71012724b151aa02c8f05f2dc0e121e7a4371e/modules/services/gpg-agent.nix#L266-L268). It uses _systemd_, which won't work there.

**Comment by midchildan** [comment]
This seems to a Home Manager problem. The `services.gpg-agent` should probably just accept a path to the pinentry binary rather than taking a flavor string and figuring the path. The current approach disallows using custom pinentry builds or pinentry builds from a different Nixpkgs commit.

**Comment by midchildan** [comment]
As for `pkgs.pinentry.flavors`, I don't think it's meant to represent all builds of pinentry available in Nixpkgs. The various pinentry flavors excluding `pinentry_mac` is built as part of a single derivation. It shares the source code, is built from the same build recipe in the same build job. But each flavor gets assigned a different path in the Nix store. What `pkgs.pinentry.flavors` represent is the build time configuration that's supplied to the build job.

`pkgs.pinentry_mac` is something entirely different. It uses a different source code, build recipe, and build job.

**Comment by midchildan** [comment]
Currently, I just manually configure `gpg-agent.conf` using `home.file`:

```nix
lib.mkIf pkgs.stdenv.isDarwin {
  home.file.".gnupg/gpg-agent.conf".text = ''
    pinentry-program ${pkgs.pinentry_mac}/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac
  '';
}
```

https://github.com/midchildan/dotfiles/blob/003d2035ee2c257d363476660e286bb375cd1a21/nix/home/modules/gnupg/default.nix

**Comment by seh** [comment]
Thank you for this discussion and analysis. Do you think that I should file an issue with Home Manager about dissociating the _gpg-agent_ configuration options from `pkgs.pinentry.flavors`?

I appreciate you sharing your configuration for _gpg-agent_. This gives me plenty to study.

**Comment by midchildan** [comment]
I'm glad it helped. Yes, I think it should be reported to Home Manager.

**Comment by seh** [comment]
> I'm glad it helped.

Separately from this particular issue, I've been reading the files in your _dotfiles_ repository, and I have so many questions, but I don't know where to ask them.

Do you know of a document I can read that explains how these files work, their evaluation model, as in which parameters or references they accept and what they must produce for whatever is consuming them?

I've read the Nix language guide, and have read many examples of flakes, but I still haven't found something that explains the skeleton and data flow into and out of the constituent files.

**Comment by midchildan** [comment]
These were my main sources of information when I started using Nix:

* [official docs](https://nixos.org/learn.html)
* [Nix Pills](https://nixos.org/guides/nix-pills)
* [NixOS Wiki](https://nixos.wiki/)
* [NixOS Discourse](https://discourse.nixos.org)
* Nixpkgs repo (issues and code)

Maybe the NixOS wiki entry on [NixOS modules](https://nixos.wiki/wiki/NixOS_modules) and [Flakes](https://nixos.wiki/wiki/Flakes) might help answer some of your questions.

I don't know what the currently optimal path for learning Nix is, though. I hear that more tutorials have been made in recent years. [nix.dev](https://nix.dev) and [Zero to Nix](https://zero-to-nix.com) are the ones I hear about often. I'm sure there's more.

If you have more questions regarding my dotfiles repo, I just enabled [GitHub discussions](https://github.com/midchildan/dotfiles/discussions/new/choose), so please feel free to ask there.

**Comment by Aleksanaa** [comment]
Closing this since NixOS modules (modules in Nixpkgs, this repo) doesn't support macOS currently. Home manager is a separate project, and all related issues should be raised there.
