### ISSUE TITLE
Package request: evince on macos

### ISSUE THREAD

**Issue by cathaysia** [NixOS/nixpkgs#240823]
**Project description**

homebrew provides an evince installation method on macos: [evince formulae](https://formulae.brew.sh/formula/evince#default). Is this possible for nix?

* homepage URL: https://formulae.brew.sh/formula/evince
* source URL: https://github.com/Homebrew/homebrew-core/blob/1d647932d0c46f64891d6494a6191791d8e51326/Formula/evince.rb
* license: gpl2+
* platforms: darwin

**Comment by cathaysia** [comment]
@bobby285271 @tormeh

Are you interested in this?

**Comment by tormeh** [comment]
Not sure if I'm the right person to tag. Don't think I've ever been involved in anything related

**Comment by OPNA2608** [comment]
Seems to build fine at least, just needs to have `meta.platforms` expanded to `unix`.
https://github.com/NixOS/nixpkgs/blob/b72aa95f7f096382bff3aea5f8fde645bca07422/pkgs/desktops/gnome/core/evince/default.nix#L140
![Screenshot_macOS_2023-07-01_12:09:56](https://github.com/NixOS/nixpkgs/assets/23431373/234aa1a9-ea86-4539-8416-d23faa55831e)

**Comment by cathaysia** [comment]
thanks very much :)
