### ISSUE TITLE
1password-gui doesn't support PAM

### ISSUE THREAD

**Issue by JJ-Atkinson** [NixOS/nixpkgs#240810]
### Describe the bug
The 1password polkit action configuration file is not placed in `/usr/share/polkit-1/actions/com.1password.1Password.policy`.

https://support.1password.com/system-authentication-linux/

### Steps To Reproduce

1. Install `_1password-gui`
2. See `ls /usr/share/polkit-1/actions/` and `/run/current-system/sw/share/polkit-1/actions/`. Neither contain the 1password policy document.

### Additional context
I've tried to figure out how to copy the file from the nix store (accessible at this path: `"${pkgs._1password-gui}/share/1password/com.1password.1Password.policy.tpl"`), but I can't seem to copy files into `/run/current-system/sw` with `system.activationScripts`. I have been able to copy the file into `/usr/share/polkit-1/actions`, but it appears that in nix polkit only looks in `/run/current-system/sw`. If anyone knows how to link the file from the nix store into the proper location in `/run/current-system/sw`, I'd be happy to make a PR that fixes this. 

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/misc/1password-gui/default.nix#L58

### Notify maintainers

@timstott @maxeaubrey @SebTM @savannidgerinel

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.05 (Stoat), 23.05.1375.9790f3242da`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by maxeaubrey** [comment]
Please use the module, not the package. This is expected behaviour.

**Comment by rbjorklin** [comment]
> Please use the module, not the package. This is expected behaviour.

It's not obvious to me what this means. Should I be doing this?
```nix
programs = {
    _1password.enable = true;
    _1password-gui.enable = true;
    _1password-gui.polkitPolicyOwners = [ "rbjorklin" ];
};
```

**Comment by SebTM** [comment]
Yes, you can follow that through - the polkitPolicyOwner is passed in the package here https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/programs/_1password-gui.nix#L39 and then used inside the package here https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/misc/1password-gui/linux.nix#L106 to write the needed policy-file.

You only need the _1password-gui option for the desktop-application, _1password is for the op-cli.

**Comment by JJ-Atkinson** [comment]
I don't recall which of these settings were important, but these may be of aid to you since I did get the configuration working:


```nix
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = ["jarrett"];
  };
  programs._1password.enable = true;


  security.pam.services = {
    login.u2fAuth = true;
    sudo.u2fAuth = true;
    polkit-1.u2fAuth = true;
  };
```

**Comment by amaxine** [comment]
Gnome keyring shouldn't be in any way breaking 1p - it doesn't for me. That might warrant reaching out to 1p support proper, they shouldn't interact adversely.

**Comment by JJ-Atkinson** [comment]
IIRC I had to disable the gnome keyring because I'm using a yubikey as a pam module as well. But, again, I don't recall exactly haha. I didn't leave a informative enough comment for myself :/.
