### ISSUE TITLE
mozillavpn fails to launch with libGL error after upgrade to nixos-23.05

### ISSUE THREAD

**Issue by slg-developer** [NixOS/nixpkgs#240826]
### Describe the bug
After upgrading from nixos-22.11 to nixos-23.05, mozillavpn fails to launch.  Seems like a similar issue to the following
https://github.com/NixOS/nixpkgs/issues/95806
https://github.com/NixOS/nixpkgs/issues/221250

### Steps To Reproduce
1. Add nix channel :  nix-channel --add https://channels.nixos.org/nixos-23.05 nixos
2. Upgrade:  sudo nixos-rebuild switch --upgrade
3. Login to KDE Plasma / Wayland
4. Use the launcher to start MozillaVPN.  The application window opens and then immediately disappears.
5. Launch mozillavpn from a terminal window.  Here's the output:

libGL error: MESA-LOADER: failed to open iris: /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/5zzbdhg945bafahn0x9xwsx8rm1f615d-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/5zzbdhg945bafahn0x9xwsx8rm1f615d-llvm-15.0.7-lib/lib/libLLVM-15.so) (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Aborted

### Notify maintainers
 @andersk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.05 (Stoat), 23.05.1471.b72aa95f7f0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FliegendeWurst** [comment]
Works fine for me. Please reopen if you still see it.
