### ISSUE TITLE
Make gem config overridable by version

### ISSUE THREAD

**Issue by mguentner** [NixOS/nixpkgs#24080]
## Issue description

the ruby gem tzinfo exists in two different versions/branches which are both maintained.
the 0.3.xx branch does not contain the file `lib/tzinfo/zoneinfo_data_source.rb` referenced by nixpkgs, only 1.x does.

Ref: https://github.com/tzinfo/tzinfo/tree/0.3/lib/tzinfo

Extract from pkgs/development/ruby-modules/gem-config/default.nix:
```
  tzinfo = attrs: {
    dontBuild = false;
    postPatch = ''
      substituteInPlace lib/tzinfo/zoneinfo_data_source.rb \
        --replace "/usr/share/zoneinfo" "${tzdata}/share/zoneinfo"
    '';
  };
 ```

I fixed it by overwriting tzinfo (again!) but this is not a good solution :/

```
env = pkgs.bundlerEnv {
      name = "foo_env";
      gemfile  = ./Gemfile;
      lockfile = ./Gemfile.lock;
      gemset   = ./gemset.nix;
      gemConfig = pkgs.defaultGemConfig // { tzinfo = attrs: {dontBuild = false;}; };
      inherit ruby;
   };
```

cc @zimbatm 🍰 
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by zimbatm** [comment]
Hmm. I don't remember by heart, is `attrs.version` available? If yes we could switch based on the version.

Pseudo code:
```
tzinfo = attrs: if lib.versionGreaterThan attrs.version, "1.3" then 
  {
    dontBuild = false;
    postPatch = ''
      substituteInPlace lib/tzinfo/zoneinfo_data_source.rb \
        --replace "/usr/share/zoneinfo" "${tzdata}/share/zoneinfo"
    '';
  }
 else {};
```
