### ISSUE TITLE
Steam: Borderlands 3 don't start anymore

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#240964]
### Steps To Reproduce
1. Start Steam
2. Start Borderlands 3
3. It does not start

### Expected behavior
game starts

### Additional context
it did work 5 days ago and i think there was no steam update and i did not make a nixos update. my RAM (32GB) is 60% full, maybe thats not enough

Some failing stuff in terminal output: https://gist.github.com/davidak/3e718b0f96932b5463536f9d22d6f6a2

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 22.11 (Raccoon), 22.11.4588.93fddcf640c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Steam-Version:  1687386907
Steam-Client: Build-Datum:  Mi., 21. Juni 23:18 UTC -08:00
Steam: Webbuild-Datum:  Do., 22. Juni 0:26 UTC -08:00
Steam-API-Version:  SteamClient020

**Comment by soupglasses** [comment]
Can be related to #238101

**Comment by davidak** [comment]
@soupglasses no, steam and other games work fine.

it might just be that the game needs a lot of RAM which wasn't free. after i closed the browser, it worked most of the times
