### ISSUE TITLE
plex fails to start due to permissions problem

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#24090]
## Original Issue Title
"plex fails to run, can't find needed libraries"
## Issue description

Plex fails to run, fails to find needed libraries.

### Steps to reproduce

```
$ nix-build '<nixos>' -A plex
/nix/store/wywsml8sybwkfgjpxnvh4akf147p4l0i-plex-1.3.3.3148
$ /nix/store/wywsml8sybwkfgjpxnvh4akf147p4l0i-plex-1.3.3.3148/usr/lib/plexmediaserver/Plex\ Media\ Server
/nix/store/wywsml8sybwkfgjpxnvh4akf147p4l0i-plex-1.3.3.3148/usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Looks like [we already take steps to make this available by symlinking it over](https://github.com/NixOS/nixpkgs/blob/cbe1218cc90de4ddc79b37c52c348b0b4b062edc/pkgs/servers/plex/default.nix#L47), not sure what broke between that doing the trick and now.

Haven't looked much further into this, sorry.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
**`17.03beta501.acb7958`**
* Nix version: (run `nix-env --version`)
**`nix-env (Nix) 1.11.7`**
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
**`"17.03beta501.acb7958"`**

**Comment by dtzWill** [comment]
cc'ing maintainers so it's on their docket: @colemickens @forkk @thoughtpolice

**Comment by colemickens** [comment]
Might check this out: https://github.com/NixOS/nixpkgs/pull/24138

cc: @pjones for any input

(Unfortunately, I've not been using NixOS for nearly a year and I don't have the bandwidth to take a look.)

**Comment by pjones** [comment]
@dtzWill I suggest that you look at the systemd configuration in
`nixpkgs/nixos/modules/services/misc/plex.nix`.  You probably want to
run this as a system service via:

~~~
services.plex.enable = true;
~~~

**Comment by dtzWill** [comment]
@colemickens will give that a look, thanks!

@pjones - that's actually what I tried first, that results in plex failing to start:

```
$ systemctl status plex
● plex.service - Plex Media Server
   Loaded: loaded (/nix/store/n9lnz3dgn42dbk8sfrakl74c1k67k5yw-unit-plex.service/plex.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-03-21 14:07:00 CDT; 412ms ago
  Process: 15532 ExecStart=/bin/sh -c /nix/store/wywsml8sybwkfgjpxnvh4akf147p4l0i-plex-1.3.3.3148/usr/lib/plexmediaserver/Plex\ Media\ Server (code=exited, status=255)
  Process: 15511 ExecStartPre=/nix/store/n3brk8k2908n1zrkkl522jydnq523p62-unit-script/bin/plex-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 15532 (code=exited, status=255)
      CPU: 120ms

Mar 21 14:07:00 dtznix systemd[1]: plex.service: Failed with result 'exit-code'.
Mar 21 14:07:00 dtznix systemd[1]: plex.service: Service hold-off time over, scheduling restart.
Mar 21 14:07:00 dtznix systemd[1]: Stopped Plex Media Server.
Mar 21 14:07:00 dtznix systemd[1]: plex.service: Start request repeated too quickly.
Mar 21 14:07:00 dtznix systemd[1]: Failed to start Plex Media Server.
Mar 21 14:07:00 dtznix systemd[1]: plex.service: Unit entered failed state.
Mar 21 14:07:00 dtznix systemd[1]: plex.service: Failed with result 'exit-code'.
```

Which is why I ended up trying to run the program myself to see what was going wrong.

**Comment by LnL7** [comment]
Have you looked at https://github.com/NixOS/nixpkgs/pull/24138?

**Comment by dtzWill** [comment]
cherry-picked onto nixos-17.03-small, same error (and fails when run as a service).

@pjones (or anyone with plex working) can you run "LD_DEBUG=libs /nix/store/.../usr/lib/plexmediaserver/Plex\ Media\ Server" to show what's different? Are you on NixOS?

**Comment by dtzWill** [comment]
The problem appears to be the lack of `patchelf`'ing the shared libraries themselves, so libstdc++ never apppears on their rpath.  Here's the tail of what's produced with `LD_DEBUG=all`:

```
     17099:	file=libstdc++.so.6 [0];  needed by /nix/store/d92jbixghazz4lqcg1i562smfkhnvhx0-plex-1.5.0.3501/usr/lib/plexmediaserver/libavcodec.so.57 [0]
     17099:	find library=libstdc++.so.6 [0]; searching
     17099:	 search cache=/nix/store/vn6fkjnfps37wa82ri4mwszwvnnan6sk-glibc-2.25/etc/ld.so.cache
     17099:	 search path=/nix/store/vn6fkjnfps37wa82ri4mwszwvnnan6sk-glibc-2.25/lib		(system search path)
     17099:	  trying file=/nix/store/vn6fkjnfps37wa82ri4mwszwvnnan6sk-glibc-2.25/lib/libstdc++.so.6
     17099:	
/nix/store/d92jbixghazz4lqcg1i562smfkhnvhx0-plex-1.5.0.3501/usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by dtzWill** [comment]
Looks like permissions on /var/lib/plex/.skeleton aren't set properly after being created the first time.

[This fixed the problem for me](https://github.com/dtzWill/nixpkgs/commit/2ffcb153995c9ab90d8bfc9d3498a3e8bcaf06e7).

Since the 'plex' package doesn't put anything in 'bin' I think we can leave the library problem alone and just fix the permissions issue.

Sorry for the misdirection, can someone review/cherry-pick that commit?
