### ISSUE TITLE
Build failure: opencolorio-2.2.0.drv, prevents blender-3.5.1.drv and system-path.drv from building

### ISSUE THREAD

**Issue by spacebanana420** [NixOS/nixpkgs#241125]
### Steps To Reproduce

1. Change branch to nixos-unstable
2. Add to your configuration.nix ```environment.systemPackages = with pkgs; [blender]```
3. Update with `sudo nixos-rebuild switch --upgrade`

### Build log
[**Full log here**](https://gist.github.com/spacebanana420/f7cb4f002be2abe747b93e304fc30e92)
```console
error: builder for '/nix/store/kk0vyrxba9ijf7gl6jiy67ckdpc90r0z-opencolorio-2.2.0.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/ylg6cfg3s85wkipf6v9qnvjvn7f3if0k-blender-3.5.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/931ax5x0d41xhrw5kgzvivjv1n19x9fv-system-path.drv' failed to build
building '/nix/store/a5rwmsfv8y0pvq84d0hqzl28fs49n8rd-unit-nix-daemon.service.drv'...
building '/nix/store/3rg3cdv41npwik7sxi9q9qq7ynzwfzkv-unit-nix-optimise.service.drv'...
building '/nix/store/xgk3k2msw2igzmx0ly0szziliyqykybg-unit-nix-optimise.timer.drv'...
building '/nix/store/yzxblpvyizr6nyci5vyh5rra70kj4wsz-unit-pipewire.service-disabled.drv'...
building '/nix/store/57s2927128nh4bj5iiv8mclsifkb28gy-unit-pipewire.socket-disabled.drv'...
building '/nix/store/526h7v9cn446xf53z7pscy7y2359saai-unit-script-nix-gc-start.drv'...
building '/nix/store/754x0yfghqw288mmr97m6djak4p5cvf6-unit-systemd-udevd.service.drv'...
building '/nix/store/ly5hhn2mb93jvlfx79x3b9mf4qi5h2jd-unit-wireplumber.service-disabled.drv'...
error: 1 dependencies of derivation '/nix/store/0rbhvciky3bk7lfvaw8qkjv7yrnnfnqm-nixos-system-CirnOS-23.11pre500267.645ff62e09d.drv' failed to build
```

### Notify maintainers

@cillianderoiste 
@veprbl
@rastertail 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.9, NixOS, 23.11 (Tapir), 23.11pre498616.6b3d1b1cf13`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(space): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cafkafk** [comment]
If you're using a flake, this is how I was able to mitigate this until it's fixed.

I rolled back the changes from #238978 in a branch on my fork, and used it as an overlay for the affected packages like this:
```nix
  inputs = {
    ...
    nixpkgs-colorio-fix.url =
      "github:cafkafk/nixpkgs/cafkafkdev-colorio-downgrade";
    ...
  };
```

This is how you would add them to your overlay:
```nix
overlay = final: prev: {
  ...
  inherit (nixpkgs-colorio-fix.legacyPackages.${prev.system})
    zlib-ng minizip-ng;
  ...
}
```

Ofc, depending on how you do stuff, you'll have to fiddle with it a bit to get it to work.

I found this helpful: https://astrid.tech/2022/11/03/0/overlay-nixpkgs-pr/

**Comment by spacebanana420** [comment]
The fix is now on the nixos-unstable branch, but I still cannot build my system after updating, with the same build failure for opencolorio. Is this expected?

**Comment by wegank** [comment]
Probably not, since [opencolorio](https://hydra.nixos.org/job/nixpkgs/trunk/opencolorio.x86_64-linux) and [blender](https://hydra.nixos.org/job/nixpkgs/trunk/blender.x86_64-linux) both build on Hydra.

**Comment by spacebanana420** [comment]
Oh thank you, this is very bizarre. I will ask on the forum what's going on
