### ISSUE TITLE
enabling texture floats in Mesa

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#24116]
## Issue description
The GL_ARB_texture_floats OpenGL extension is disabled by default in Mesa due to patent concern (US  #6,650,327). Without texture floats the radeonsi drived is severely limited (OpenGL 2.1 vs 4.5).
It can be enabled with `mesa_noglu.override { enableTextureFloats = true; }` but this requires a significant amount of compiling on every update.

Other distros are already building mesa with it: [arch linux](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mesa#n75) and [debian](https://anonscm.debian.org/cgit/pkg-xorg/lib/mesa.git/tree/debian/rules#n126) for example.
Can we enable it as well? What do you think?

**Comment by abbradar** [comment]
At first glance this is risky but Debian usually is very scrict (and therefore a good indicator patent-wise) and yet they enable it. It's interesting to find out their reasoning -- maybe this is not as concerning as it soinds.

**Comment by vcunat** [comment]
It's enough to override `mesa_drivers` that way you won't need to recompile any reverse dependencies.

**Comment by rnhmjoj** [comment]
@vcunat, thanks. I did:

```
  mesa_drivers = (mesa_noglu.override {
    enableTextureFloats = true;
  }).drivers;
```

and nix only recompiled mesa. Anyway I think it can be quite confusing since users (myself included) expect the driver to be OpenGL 3.x or 4.x and texture floats don't look immediately related to this problem. See issue #12380.

**Comment by rnhmjoj** [comment]
Perhaps it should be mentioned [here](https://nixos.org/nixos/manual/#idm140737316388800) in the manual.

**Comment by vcunat** [comment]
Better use `mesa_drivers.override` instead of `mesa_noglu.override`, as there could be other differences, e.g. `grsecEnabled` ATM.  `mesa_drivers` is meant just as a build-time dependency for packages that need it.

**Comment by rnhmjoj** [comment]
I tried that first but apparently it's missing the override:
```
$ nix-repl
Welcome to Nix version 1.11.7. Type :? for help.

nix-repl> :l <nixpkgs>
Added 7224 variables.

nix-repl> mesa_drivers.override
error: attribute ‘override’ missing, at (string):1:1
```

**Comment by vcunat** [comment]
Oh, I haven't realized that.  Well, you can at least set `grsecEnabled` by hand in the override for now.  (There's supposed to be some impact on speed somewhere.)

**Comment by vcunat** [comment]
Personally I think we can allow (potentially) patented stuff even into the default drivers.  Most users should be at no risk, especially within the EU.  Note that in case of freetype we do include code with patent risks.  With mesa we've been dragging the default for many years now, since ee0822153a.

But, to be sure, we already have `hardware.opengl.s3tcSupport` option so we can do it similarly.  (Or perhaps generalize it to both/all mesa patent risks.)

**Comment by abbradar** [comment]
Some background: a user [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757393) a possible patent issue to Debian but it seem to be lost in the limbo. So there indeed may be some risk.

Given that Debian does this too (and they are much bigger than we) we may just enable this by default, but I can't assess the risk for U.S. users (I'm not one of them).

**Comment by vcunat** [comment]
US/international companies are likely to be more cautious (and more at risk), especially if they don't plan to play games ;-)

**Comment by globin** [comment]
If debian has it enabled by default I think we can and should, too.

**Comment by rnhmjoj** [comment]
@abbradar `enableTextureFloats = (splitString "/" config.time.timeZone) != "America";` ?
;)

**Comment by globin** [comment]
done in #24162
