### ISSUE TITLE
How to build with clang 4.0?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#24115]
I have a program with a [default.nix](https://github.com/raptorjit/raptorjit/blob/master/default.nix) that builds using the `clang` C compiler. I would like to pin this to always use a specific version of `clang` (4.0 for now but subject to change). Can somebody tell me how to do this please?

Just now I am using `import <nixpkgs>` to get `clangStdenv` but the problem is that this builds with clang 3.8 on my NixOS machine and clang 3.9 on Travis-CI but I want clang 4.0 on both.

Relatedly: I would also like to ensure that clang and other build dependencies are available from a binary cache. Can somebody tell me how to do that too please? (I have a Hydra instance at my disposal if that helps.)

See also https://github.com/raptorjit/raptorjit/pull/50#issuecomment-287704071 where I have a CI job failing due to nixpkgs mismatch between developer machine and CI machine.

**Comment by dezgeg** [comment]
In `all-packages.nix`, `clangStdenv` is defined as:
````
clangStdenv = if stdenv.isDarwin then stdenv else lowPrio llvmPackages.stdenv;
````

So it sounds like you can replace your use of `clangStdenv` with `llvmPackages_4.stdenv`.

**Comment by lukego** [comment]
Thanks @dezgeg. I think that I also need to somehow specify a suitable version of `nixpkgs` to use to avoid a dependency on the user's own setup of `nix`? (Thinking that in practice today most of the machines I am working on will not have `llvmPackages_4` available in their default `nixpkgs`.)

**Comment by lukego** [comment]
Can I somehow update this line:

```
{ pkgs ? (import <nixpkgs> {}) # Use default nix distro (for now...)
```

Such that it will use a specific nixpkgs release that has `llvm4` available?

My first attempt is:

```
{ pkgs ? (builtins.fetchurl https://nixos.org/channels/nixos-17.03-small/nixexprs.tar.xz)
```

... but this downloads incredibly slowly (need to reference a mirror?) and is potentially wasteful (will Travis-CI cache this download or do I need to use another method?)

**Comment by domenkozar** [comment]
@lukego I usually do https://github.com/hercules-ci/hercules/blob/master/pkgs.nix and use it as https://github.com/hercules-ci/hercules/blob/master/haskell-packages.nix#L1

**Comment by lukego** [comment]
@domenkozar Thanks for the hint. Pity to use a random commit ID instead of a well-defined release tag? For one thing makes it non-obvious when it makes sense to update?

**Comment by lukego** [comment]
@domenkozar I also seem to have fairly lousy bandwidth from the Github tarball URL... ~50KB/sec and so it takes many minutes to download... wonder if there is a better location to snarf a nixpkgs definition from.

**Comment by domenkozar** [comment]
I run http://howoldis.herokuapp.com/ that will one day gain ability for history (once https://github.com/NixOS/nixos-channel-scripts/pull/11 is merged).

I bump once I need some new software and then test everything works. This does exclude you from security updates though.

You can also use https://github.com/NixOS/nixpkgs-channels/tree/nixos-16.09-small for github access.

If neither S3 or Github are fast enough, you might be hitting an old bug, what's your nixpkgs version that you're using?

**Comment by lukego** [comment]
@domenkozar I dunno what nixpkgs I am using. This is a machine you are familiar with i.e. `interlaken`.

**Comment by domenkozar** [comment]
```
Testing download speed........................................
Download: 9.86 Mbit/s
Testing upload speed..................................................
Upload: 2.00 Mbit/s
```

It needs to download a 9M file so that takes 9s as expected

**Comment by lukego** [comment]
I have been watching this for many minutes now...
```
[luke@interlaken:~/git/raptorjit]$ nix-build
downloading ‘https://github.com/NixOS/nixpkgs-channels/archive/6a0155d2b7cb10aef1c63b654a2b172d78fd89b4.tar.gz’... [6927/0 KiB, 41.2 KiB/s]
```

**Comment by lukego** [comment]
Oh! Seems to be a local problem with my internet connection. Embarrassing :). I tested from another machine and I see 2.7MB/sec instead of 0.05MB/sec.

**Comment by lukego** [comment]
Thanks for the help @domenkozar @dezgeg! I am fairly happy with where I ended up for now with the nix expressions in https://github.com/raptorjit/raptorjit/pull/52/commits/c025664d8c293f81cdb6ad8207c02bf20b28b16c.

**Comment by domenkozar** [comment]
@lukego awesome :) Are you happy with the solution for clang? You could also assert in Nix code for `clang.version` to start with `4`.

**Comment by copumpkin** [comment]
Keep in mind that the libc++ in 3.8 and above broke a bunch of c++ builds (supposedly more standards-compliant!) so a few packages will break. I've been fixing them because we're moving the Darwin stdenv to LLVM 4 and I want the upgrade to go smoothly, but there are still some known breakages.

Also, for historical reasons, most LLVM-specific package adjustments are conditioned on `stdenv.isDarwin` rather than `stdenv.cc.isClang`, so some packages might have LLVM fixes but you might not get them.

**Comment by lukego** [comment]
@domenkozar I am comfortable enough having the nixpkgs pinned and referring specifically to `llvmPackages_4.stdenv` that it should use the version I want.

@copumpkin Thanks for the heads up. I only have one package that I want to build with clang 4.0 so I don't think I will have these issues.

**Comment by domenkozar** [comment]
Great :) Closing!

**Comment by lukego** [comment]
@domenkozar Follow-on question, if you will excuse me following up on a closed issue, and risking this being lost:

You have a [nice trick](https://github.com/hercules-ci/hercules/blob/master/pkgs.nix) for downloading a pinned version of nixpkgs with `fetchTarball`. Question is, could this be optimized by somehow supplying the expected sha256 hash? This way nix could reuse a local copy without having to make any network request.

Looks like `fetchTarball` cannot take a sha256 hash so perhaps one would rebuild that on `fetchurl` somehow?

**Comment by domenkozar** [comment]
@lukego Nix 1.12 will [support specifying sha256](https://github.com/NixOS/nix/commit/06bbfb6004942bfcddd930e746ee7a2bfe5c3872), but it's in development for more than a year. Lots of new changes, we are slowly pushing for a release.

Meanwhile there aren't many alternatives. Upgrading to Nix 1.12 trivial, but it's not trivial to downgrade (due to sqlite schema changes).

**Comment by lukego** [comment]
Thanks for the info! 👍

**Comment by copumpkin** [comment]
I just import from fetchFromGitHub, and do it all the time. We discourage IFD in nixpkgs but it works fine and has the properties you desire

**Comment by domenkozar** [comment]
Recursive Nix has a lot of downsides, for example builds happen during evaluation. It's a good compromise though :)

**Comment by copumpkin** [comment]
Only builds needed by fetchFromGitHub itself (i.e., stdenv) would happen
during eval here, but yes, worth being careful about :)
