### ISSUE TITLE
The new NIX_SSL_CERT_FILE changes break terraform (and probably other go projects) on Darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24124]
I just upgraded to Nix 1.11.7 and found that terraform breaks in a hard-to-track manner as a result. I think it's because all Go projects reimplement everything from scratch so none of our patches to standard HTTP libraries like `curl` affect it.

The tricky problem that arises is that each Go project pulls in its own full set of dependencies, often "vendored" right into the project repository, so there's no single place for us to patch the Go http libraries. I can fix Terraform in a one-off way since it's pretty painful, but we'll probably need a better solution to teach Go about `NIX_CERT_FILE`.

cc @edolstra @kamilchm

**Comment by kamilchm** [comment]
We can start with the patch for terraform and see if there's something that can be extracted to `buildGoPackage` or can be done as part of go2nix if we found that it can't be done in pure nix.

**Comment by copumpkin** [comment]
See #24058 which might fix it

**Comment by copumpkin** [comment]
Apparently it's not as tricky as I thought since crypto/x509 doesn't usually get vendored.

**Comment by LnL7** [comment]
Fixed by #27598
