### ISSUE TITLE
Update request: wayshot 1.2.2 → 1.3.0

### ISSUE THREAD

**Issue by Shinyzenith** [NixOS/nixpkgs#241274]
- Package name: wayshot
- Latest released version: 1.3.0
- Current version on the unstable channel: 1.2.2
- Current version on the stable/release channel: 1.2.2
- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dit7ya 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by dit7ya** [comment]
Resolved in #241468.

**Comment by Shinyzenith** [comment]
Thank you!
