### ISSUE TITLE
Package request: Extension manager

### ISSUE THREAD

**Issue by Sitolam** [NixOS/nixpkgs#241280]
**Project description**

A utility for browsing and installing GNOME Shell Extensions.

Features:

- Browse extensions.gnome.org right inside the app
- Manage the extensions you already have installed

credits to: Matthew Jakeman

**Metadata**

* homepage URL: https://github.com/mjakeman/extension-manager
* source URL: https://flathub.org/apps/com.mattjakeman.ExtensionManager
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by pinn3** [comment]
[It's already packaged](https://search.nixos.org/packages?query=gnome-extension-manager)
