### ISSUE TITLE
Build failure: vscode-extensions.vadimcn.vscode-lldb

### ISSUE THREAD

**Issue by cathaysia** [NixOS/nixpkgs#241235]
### Steps To Reproduce

> nix-shell -p vscode-extensions.vadimcn.vscode-lldb

### Build log

https://gist.github.com/cathaysia/6b8c165b6d3812fc7dde327486c63c07

### Additional context

this works well for linux x86_64

### Notify maintainers

@nigelgbanks 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by becknik** [comment]
This seems to be a mac-only issue...

Here a my build log following OPs example: [gist](https://gist.github.com/becknik/cee851ab390cf20eaf293b20c8b1da84)

#### Metadata

```bash
$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/jbecker/.nix-defexpr/channels/nixpkgs`
```

I worked around this by disabling the installation of all plugins atm...

**Comment by cathaysia** [comment]
What does the content generated by nix4vscode look like?
________________________________

**Comment by cathaysia** [comment]
emm, I don't use this package, sorry. so I just close this.

**Comment by becknik** [comment]
well, thanks for nothing
