### ISSUE TITLE
gdc: eval failure

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#241341]
### Steps To Reproduce

1. `nix-shell --show-trace -p tumiki-fighters`

### Build log

<details>
<summary>Click to expand build log</summary>
<pre><code>
error:
       … while evaluating the attribute 'buildInputs' of the derivation 'shell'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       … while evaluating the attribute 'nativeBuildInputs' of the derivation 'tumiki-fighters-0.21'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:303:7:

          302|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          303|       name =
             |       ^
          304|         let

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'getOutput'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:892:23:

          891|   */
          892|   getOutput = output: pkg:
             |                       ^
          893|     if ! pkg ? outputSpecified || ! pkg.outputSpecified

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:244:13:

          243|       (map (drv: drv.__spliced.buildBuild or drv) (checkDependencyList "depsBuildBuild" depsBuildBuild))
          244|       (map (drv: drv.__spliced.buildHost or drv) (checkDependencyList "nativeBuildInputs" nativeBuildInputs'))
             |             ^
          245|       (map (drv: drv.__spliced.buildTarget or drv) (checkDependencyList "depsBuildTarget" depsBuildTarget))

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:117:29:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                             ^
          118|

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix:117:32:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                                ^
          118|

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:216:81:

          215|   checkDependencyList = checkDependencyList' [];
          216|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
             |                                                                                 ^
          217|     if lib.isDerivation dep || dep == null || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/stdenv/generic/make-derivation.nix:217:8:

          216|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
          217|     if lib.isDerivation dep || dep == null || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep
             |        ^
          218|     else if lib.isList dep then checkDependencyList' ([index] ++ positions) name dep

       … while calling 'isDerivation'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:636:5:

          635|     # Value to check.
          636|     value: value.type or null == "derivation";
             |     ^
          637|

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:15388:9:

        15387|   # using C/C++ libraries in D packages
        15388|   gdc = wrapCC (gcc.cc.override {
             |         ^
        15389|     name = "gdc";

       … while calling 'wrapCC'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:16741:12:

        16740|
        16741|   wrapCC = cc: wrapCCWith {
             |            ^
        16742|     inherit cc;

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:16741:16:

        16740|
        16741|   wrapCC = cc: wrapCCWith {
             |                ^
        16742|     inherit cc;

       … while calling 'wrapCCWith'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:16710:5:

        16709|   wrapCCWith =
        16710|     { cc
             |     ^
        16711|     , # This should be the only bintools runtime dep with this sort of logic. The

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:16729:7:

        16728|     } @ extraArgs:
        16729|       callPackage ../build-support/cc-wrapper (let self = {
             |       ^
        16730|     nativeTools = stdenv.targetPlatform == stdenv.hostPlatform && stdenv.cc.nativeTools or false;

       … while calling 'callPackageWith'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:128:35:

          127|   */
          128|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          129|     let

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:179:34:

          178|
          179|     in if missingArgs == [] then makeOverridable f allArgs else abort error;
             |                                  ^
          180|

       … while calling 'makeOverridable'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:78:24:

           77|   */
           78|   makeOverridable = f: origArgs:
             |                        ^
           79|     let

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:80:16:

           79|     let
           80|       result = f origArgs;
             |                ^
           81|

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/build-support/cc-wrapper/default.nix:8:1:

            7|
            8| { name ? ""
             | ^
            9| , lib

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/top-level/all-packages.nix:15388:17:

        15387|   # using C/C++ libraries in D packages
        15388|   gdc = wrapCC (gcc.cc.override {
             |                 ^
        15389|     name = "gdc";

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:88:32:

           87|       # Re-call the function but with different arguments
           88|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                ^
           89|       # Change the result of the function call by applying g to it

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:88:41:

           87|       # Re-call the function but with different arguments
           88|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                         ^
           89|       # Change the result of the function call by applying g to it

       … while calling 'makeOverridable'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:78:24:

           77|   */
           78|   makeOverridable = f: origArgs:
             |                        ^
           79|     let

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:80:16:

           79|     let
           80|       result = f origArgs;
             |                ^
           81|

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:90:54:

           89|       # Change the result of the function call by applying g to it
           90|       overrideResult = g: makeOverridable (copyArgs (args: g (f args))) origArgs;
             |                                                      ^
           91|     in

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:90:60:

           89|       # Change the result of the function call by applying g to it
           90|       overrideResult = g: makeOverridable (copyArgs (args: g (f args))) origArgs;
             |                                                            ^
           91|     in

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:97:29:

           96|           ${if result ? overrideAttrs then "overrideAttrs" else null} = fdrv:
           97|             overrideResult (x: x.overrideAttrs fdrv);
             |                             ^
           98|         }

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:90:63:

           89|       # Change the result of the function call by applying g to it
           90|       overrideResult = g: makeOverridable (copyArgs (args: g (f args))) origArgs;
             |                                                               ^
           91|     in

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/development/compilers/gcc/12/default.nix:1:1:

            1| { lib, stdenv, targetPackages, fetchurl, fetchpatch, noSysDirs
             | ^
            2| , langC ? true, langCC ? true, langFortran ? false

       error: assertion '(! langD)' failed

       at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/development/compilers/gcc/12/default.nix:45:1:

           44| #   error: GDC is required to build d
           45| assert !langD;
             | ^
           46|
</code></pre>
</details>

### Notify maintainers

@fgaz

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.36, NixOS, 23.05 (Stoat), 23.05.1501.0de86059128`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by fgaz** [comment]
It's actually gdc that is failing eval, pinging @Synthetica9 @vcunat @Ericson2314 (@NixOS/gcc doesn't exist anymore??)

**Comment by vcunat** [comment]
See PR #241628
gdc seriously lacks someone in nixpkgs who would take care of it.
