### ISSUE TITLE
Package request: recyclarr

### ISSUE THREAD

**Issue by noelpilled** [NixOS/nixpkgs#241368]
**Project description**
Automatically sync TRaSH guides to your Sonarr and Radarr instances 
**Metadata**

* homepage URL: https://recyclarr.dev/
* source URL: https://github.com/recyclarr/recyclarr
* license: mit
* platforms: linux, macOS, windows

**Comment by figsoda** [comment]
duplicate of #239851, there is a PR in progress: #240119
