### ISSUE TITLE
tree-sitter fails to build with webUISupport set to true

### ISSUE THREAD

**Issue by ErinvanderVeen** [NixOS/nixpkgs#241304]
### Describe the bug
webUISupport is needed for the `tree-sitter playground` command. However, enabling this flag fails the tree-sitter build.

### Steps To Reproduce
1. `cd` to your favorite checkout of nixpkgs
2. run `nix-build -E 'with (import ./default.nix {}); tree-sitter.override { webUISupport = true; }'`

### Expected behavior
A successful build.

### Screenshots
I'll give you a section of the build log instead:
```
  File "/nix/store/h0m18s9pb6y3n38vyxfcnxswqi8n28ap-emscripten-3.1.42/share/emscripten/emcc.py", line 548, in get_js_sym_info
    with filelock.FileLock(cache.get_path(cache.get_path('symbol_lists.lock'))):
  File "/nix/store/h0m18s9pb6y3n38vyxfcnxswqi8n28ap-emscripten-3.1.42/share/emscripten/tools/filelock.py", line 330, in __enter__
    self.acquire()
  File "/nix/store/h0m18s9pb6y3n38vyxfcnxswqi8n28ap-emscripten-3.1.42/share/emscripten/tools/filelock.py", line 278, in acquire
    self._acquire()
  File "/nix/store/h0m18s9pb6y3n38vyxfcnxswqi8n28ap-emscripten-3.1.42/share/emscripten/tools/filelock.py", line 391, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/nix/store/h0m18s9pb6y3n38vyxfcnxswqi8n28ap-emscripten-3.1.42/share/emscripten/cache/symbol_lists.lock'
/nix/store/blpvf60m29q02c0lc5fyhim30ma4y1vv-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

### Notify maintainers
@Profpatsch 
@oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.33, NixOS, 23.05 (Stoat), 23.05.20230614.ddf4688`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(erin): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rupurt** [comment]
@ErinvanderVeen I still get this error with tree-sitter 0.20.9 in a Nix flake. Did setting the emcc cache outside the nix store fix the build for you?

**Comment by ErinvanderVeen** [comment]
@rupurt 

If I try to reproduce it, I get this error:
```text
       > emcc: error: undefined exported symbol: "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__grow_byEmmmmmm" [-Wundefined] [-Werror]
       > /nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```
Which looks similar, but I think is a distinct issue. I do not think this is related to the emcc cache. I think it's best if you open a new issue for this.

The emcc cache is not set in the Nix store btw, it is set in a nix build directory, wherever that may be. You can generally not set the emcc cache somewhere outside of the nix sandbox.

**Comment by rupurt** [comment]
Sounds good. Thanks for the clarification. Wasn't sure if there was a setting I was missing

**Comment by philiptaron** [comment]
I've got a PR out (see above) to fix this new issue.

**Comment by rupurt** [comment]
Awesome. Thank you @philiptaron
