### ISSUE TITLE
Package request: nct6687d

### ISSUE THREAD

**Issue by Wolframme** [NixOS/nixpkgs#241348]
**Project description**

> This kernel module permit to recognize the chipset Nuvoton NCT6687-R in lm-sensors package. This sensor is present on some B550 motherboard such as MSI or ASUS.

Essential to view temperatures and control fan speeds on certain motherboards.

**Metadata**

* homepage URL: https://github.com/Fred78290/nct6687d
* source URL: https://github.com/Fred78290/nct6687d
* license: gpl2
* platforms: linux

**Comment by bjornfor** [comment]
Instead of packaging it in nixpkgs, it could be upstreamed in linux.

**Comment by Cloudef** [comment]
```nix
boot.kernelModules = [ "zenpower" "nct6687d" ];
boot.extraModulePackages = let
  kernel = config.boot.kernelPackages.kernel;
  nct6687d = pkgs.stdenv.mkDerivation {
    pname = "nct6687d";
    version = kernel.version;

    src = pkgs.fetchFromGitHub {
      owner = "Fred78290";
      repo = "nct6687d";
      rev = "df1565ad8e9689ca7d9614d656836b32656de0ae";
      hash = "sha256-B59M29d2K0qn6O+KTL4e5+sGmFJonAmjz9C2xbyGbUw=";
    };

    nativeBuildInputs = kernel.moduleBuildDependencies;
    makeFlags = kernel.makeFlags ++ [
      "-C"
      "${kernel.dev}/lib/modules/${kernel.modDirVersion}/build"
      "M=$(PWD)"
    ];

    buildFlags = [ "modules" ];
    installFlags = [ "INSTALL_MOD_PATH=$(out)" ];
    installTargets = [ "modules_install" ];
  };
in [
  config.boot.kernelPackages.zenpower
  nct6687d
];
```

I leave this here, though I don't need this module anymore myself

**Comment by pwaller** [comment]
Looks like it's in unstable: https://github.com/NixOS/nixpkgs/pull/258397
