### ISSUE TITLE
clang multilib? "clang -m32" on 64bit NixOS?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#24136]
## Issue description

Does NixOS support creating (perhaps with a wrapper/override) a multilib-capable 'clang'?

### Steps to reproduce

No steps to reproduce, but my steps were something like:

* Want to build 32bit code on 64bit system
* Notice that "gcc_multi" exists
* Notice that "clang_multi" does not
* Try and fail a few times to convince clang to find multilib bits (bonus points if this can be done by putting together appreciate environment instead of recompiling)
* Hope someone has sorted this out previously and file an issue to discuss

:innocent:

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by dtzWill** [comment]
Well I'm kicking myself for not trying this earlier, but as a workaround it seems that:

```
$ nix-shell -p pkgsi686Linux.clang
```

Gets a working 32bit clang compiler on 64bit NixOS.

**Comment by mmahut** [comment]
Is it okay to close this?

**Comment by attila-lendvai** [comment]
i'm facing the same issue. compiling works, but linking fails. i'm new to nixos, so i may be screwing up something.

```
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/hq3ps9kak12kw08hgacpjr4y4i9ias2l-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/libgcc.a when searching for -lgcc
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: cannot find -lgcc
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/4x7cr4gj12gccmkv6z1p76c1255rky1n-glibc-multi-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: cannot find libgcc_s.so.1
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: skipping incompatible /nix/store/hq3ps9kak12kw08hgacpjr4y4i9ias2l-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/libgcc.a when searching for -lgcc
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ld: cannot find -lgcc
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by alexshpilkin** [comment]
Given that `clang_multi` from the linked PR has been merged in 2017 and remains unbroken, I believe this can be closed. (If you want a Clang with more general cross bits working, which I think you currently can’t get, this should probably be a separate issue.)

@attila-lendvai, if you still care about this, and everybody else who hits this issue: to get an x86 Clang with both `clang -m32` and `clang -m64` functional, use the `clang_multi` package, obtained through `nix-shell -p clang_multi`, `nix shell nixpkgs#clang_multi`, or in any of the other usual ways; for your `mkDerivation` and `mkShell.override` needs there also is `clangMultiStdenv`. Alternatively, in `pkgsi686Linux.clang` you will find a Clang targeting 32-bit x86 only.
