### ISSUE TITLE
Tracking Issue: Remove cargoSha256 attribute

### ISSUE THREAD

**Issue by tjni** [NixOS/nixpkgs#241408]
I personally believe that we do not need this attribute in `buildRustPackage`. It lets us slightly simplify code and documentation, but mainly it's because, despite efforts, I always experience OCD-like compulsion to make it consistent.

I have read https://github.com/NixOS/rfcs/pull/131 and see that reasonable minds differ, so I offer this issue as a discussion for Rust infra and package maintainers focused only on our Rust ecosystem.

I'm in favor of doing this and willing to put up some PRs for it (even if it only is until we find a way to move away from these hashes and their abuse of FODs altogether), so I'm especially interested in hearing objections. I'll seed the main concerns against doing this that I see expressed in that RFC:

1. To support copying hash values in non-SRI formats from external sources, old versions of nix, or automation scripts.
2. To maintain backwards compatibility.

to which I'll add a third:

3. Not worth the time (e.g. reviewing, rebuilding, potentially fixing breakages). 

/cc @NixOS/rust

**Comment by figsoda** [comment]
I'm ok with requiring usage of `cargoHash` instead of `cargoSha256` in newly added Rust packages, but I don't think actively changing existing packages is worth the time.
