### ISSUE TITLE
Make `stdenv` setup time (SOURCE_DATE_EPOCH) use POSIX compliant ref

### ISSUE THREAD

**Issue by sambacha** [NixOS/nixpkgs#241522]
## [`SOURCE_DATE_EPOCH`](https://github.com/NixOS/nixpkgs/blob/9fa6434de950a688b190694b5635fc2cd0c73dbc/pkgs/stdenv/generic/setup.sh#L407)

IEEE Std 1003.1-1988 (POSIX.1) legislates that a `time_t` value of `536457599` SHALL correspond to "Wed Dec 31 23:59:59 GMT 1986." 

https://github.com/NixOS/nixpkgs/blob/9fa6434de950a688b190694b5635fc2cd0c73dbc/pkgs/stdenv/generic/setup.sh#L407

> It is important that the interpretation of time names and seconds since the Epoch values be consistent across conforming systems. That is, it is important that all conforming systems interpret " 536457599 seconds since the Epoch" as 59 seconds, 59 minutes, 23 hours 31 December 1986 , regardless of the accuracy ~ [IEEE Std 1003.1-1988](https://nvlpubs.nist.gov/nistpubs/Legacy/FIPS/fipspub151-1.pdf)[^1]

[^1]: Federal Information Processing Standards Publication: IEEE standard portable operating system interface for computer environments 

### Suggestion

```diff
- : "${SOURCE_DATE_EPOCH:=315532800}" 
+ : "${SOURCE_DATE_EPOCH:=536457599}"
```

> **Note**
> Also notwithstanding the current usage is also incorrect, [https://reproducible-builds.org/docs/source-date-epoch/](https://reproducible-builds.org/docs/source-date-epoch/) and [https://wiki.debian.org/ReproducibleBuilds/StandardEnvironmentVariables#Checklist](https://wiki.debian.org/ReproducibleBuilds/StandardEnvironmentVariables#Checklist)

### Bazel[^2]
```c 
static const u4 kDefaultTimestamp =
    30 << 25 | 1 << 21 | 1 << 16;  // January 1, 2010 in DOS time
```
[^2]: https://github.com/bazelbuild/bazel/blob/92f0d6aace87d0bf1fed8249fe834d07cff733be/third_party/ijar/zip.cc#L78-#L79

### NPM[^3]

```diff 
+   // Provide a specific date in the 1980s for the benefit of zip,
+   // which is confounded by files dated at the Unix epoch 0.
+    mtime: new Date('1985-10-26T08:15:00.000Z'),
```

![Time_Circuits_BTTF](https://github.com/NixOS/nixpkgs/assets/32783916/44048cb7-9942-417b-9e4f-c74cb897cb76)

[^3]: https://github.com/npm/cli/commit/58d2aa58d5f9c4db49f57a5f33952b3106778669#diff-eabad0b45ec780b8b57ae6e3d47fd7d063680bea3acdc6b98a4b45ba3b808ccc

### Debian Packaging[^4]

'2017-05-08T00:00:00Z' [stretch](https://github.com/debuerreotype/debuerreotype/blob/6e907e3e90cc841178a62e566b1a18a1ce58b935/docker-run.sh#L16C39-L16C59)

[^4]: https://wiki.debian.org/ReproducibleInstalls

**Comment by Artturin** [comment]
> It is important that the interpretation of time names and seconds since the Epoch values be consistent across conforming systems. That is, it is important that all conforming systems interpret " 536457599 seconds since the Epoch" as 59 seconds, 59 minutes, 23 hours 31 December 1986 , regardless of the accuracy ~ [IEEE Std 1003.1-1988](https://nvlpubs.nist.gov/nistpubs/Legacy/FIPS/fipspub151-1.pdf)[1](https://github.com/NixOS/nixpkgs/issues/241522#user-content-fn-1-dd278a09e807c681ee66b5d39eadf9fc)

this just means
536457599 seconds since the Epoch == 59 seconds, 59 minutes, 23 hours 31 December 1986
so not related to SOURCE_DATE_EPOCH. We're not interpreting epoch values
