### ISSUE TITLE
gnome-solanum fails to start in nixos-23.05

### ISSUE THREAD

**Issue by jeffa5** [NixOS/nixpkgs#241569]
### Describe the bug

Trying to run `gnome-solanum` on NixOS 23.05 gives the following error:
```
thread 'main' panicked at 'assertion failed: !self.ptr.is_null()', /build/solanum-3.0.1-vendor.tar.gz/gtk4/src/subclass/widget.rs:1284:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps To Reproduce
1. `nix run github:NixOS/nixpkgs/aed4b19d312525ae7ca9bceb4e1efe3357d0e2eb#gnome-solanum`
hash is from the nixos-23.05 branch

### Expected behavior

The program should start and be usable, seems to be fixed by https://github.com/NixOS/nixpkgs/pull/236789 perhaps this could be backported?

### Notify maintainers

@linsui 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(andrew): `"home-manager, nixpkgs-21.03pre257949.d25e1ac4260"`
 - nixpkgs: `/home/andrew/.nix-defexpr/channels/nixpkgs`
```

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/pull/241592 Does this work for you?

**Comment by jeffa5** [comment]
Yes, that is working for me, thank you!
