### ISSUE TITLE
Package request: vim-terminator

### ISSUE THREAD

**Issue by dellmonitor** [NixOS/nixpkgs#241561]
**Project description**

Vim-terminator runs your current file. Out of the box it comes with support for 47 languages and can be extended for any vim file type. Using

**Metadata**

* homepage URL: https://github.com/erietz/vim-terminator
* source URL: https://github.com/erietz/vim-terminator
* license: gpl3
* platforms: unix, linux, darwin

**Comment by figsoda** [comment]
#241564
