### ISSUE TITLE
Package request: Gridcoin

### ISSUE THREAD

**Issue by GiggleSquid** [NixOS/nixpkgs#241573]
**Project description**
Gridcoin is a POS-based cryptocurrency that rewards users for participating on the [BOINC](https://boinc.berkeley.edu/) network. Gridcoin uses peer-to-peer technology to operate with no central authority - managing transactions, issuing money and contributing to scientific research are carried out collectively by the network.

**Metadata**

* homepage URL: https://gridcoin.us/
* source URL: https://github.com/gridcoin-community/Gridcoin-Research
* license: MIT
* platforms: linux, windows, mac

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/187264

**Comment by GiggleSquid** [comment]
> Duplicate of #187264

My bad, lack of search skills at 1:30am

**Comment by GiggleSquid** [comment]
> Duplicate of #187264

My bad, lack of search skills at 1:30am
