### ISSUE TITLE
keyd: keyd-application-mapper not working from nix settings.

### ISSUE THREAD

**Issue by stuv** [NixOS/nixpkgs#241557]
### Describe the bug
[Application specific remapping](https://github.com/rvaiya/keyd#application-specific-remapping-experimental)

This is not yet working from the services.keyd settings, as that all writes to default.conf and not app.conf.

### Steps To Reproduce
1.  

Add yourself to the keyd group:

`usermod -aG keyd <user>`

The user group keyd doesn't exit. The `keyd-application-mapper` command does work, but it seems the application specific part isn't working with the current default.nix of keyd.

### Expected behavior
I like to have the application specific settings of the keyd-applicationd daemon.

Also the `man keyd` command doesn't work, as the keyd program is not in the PATH. Maybe the manual could still be included?

Currently testing the command(brightnessctl set 5%-) option to bind with one of the keys. So far no luck, but I am not yet sure whether this is because of the implementation in nix, as there is no group keyd, so I don't know who I need to give access to the video group.

### Notify maintainers

```

**Comment by stuv** [comment]
Update: It doesn't seem to be that the my test line works:

```
main = {
  f9 = "command(echo 'test'>>/home/stuv/test.nix)";
};
```

there is nothing being added to the file, so maybe it doesn't have the right privileges to issue a command?

I am mostly trying to see if i can use this program, keyd, to set the brightness in the VT.

**Comment by woojiq** [comment]
@stuv, firstly, I wasn't notified, the only reason I found this issue was `/` on github (global search). How do you notify me that I didn't receive an email but my nickname is in global search? Currently `keyd-application-mapper` should not work as I believe it should be a separate service inside `home-manager`. See [#226346 (comment)](https://github.com/NixOS/nixpkgs/issues/226346#issuecomment-1549879480)

**Comment by stuv** [comment]
Thanks for the clear explanation in the other comment. 
I am relatively new to Github so maybe the notification didn't work, because I deleted the link and only the text remained.

@woojiq 

vs.

@woojiq

So it needs to be built as a separate service. I might learn how to do so at some point down the line, if i get to be a bit more familiar with the nix packages in general.
