### ISSUE TITLE
eigen: Header files should be in $out/include not $out/include/eigen3

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#241517]
### Describe the bug
Placing header files in a subdirectory of `$out/include` stops `NIX_CFLAGS_COMPILE` from working.

### Steps To Reproduce
1. `echo '#include <Eigen/Core>' >eigen-test.cc`
2. `nix-shell --pure -p eigen pkg-config`
3. `g++ -c eigen-test.cc` --> eigen-test.cc:1:10: fatal error: Eigen/Core: No such file or directory
4. `g++ -c $(pkg-config --cflags eigen3) eigen-test.cc` --> OK

### Expected behavior
Library client programs should be buildable without using `pkg-config`.

### Additional context
```shellsession
$ echo $NIX_CFLAGS_COMPILE 
... -isystem /nix/store/w23kfp00x2lgwyqyjk23v6cn69zvsfsa-eigen-3.4.0/include ...
$ pkg-config --cflags eigen3
-I/nix/store/w23kfp00x2lgwyqyjk23v6cn69zvsfsa-eigen-3.4.0/include/eigen3
```

### Notify maintainers

@svanderburg @7c6f434c

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.114, NixOS, 22.11 (Raccoon), 22.11.4773.ea4c80b39be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(user): `"nixpkgs"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by bjornfor** [comment]
Isn't using the subdir an upstream decision? I don't think we should aim for never needing to get compiler flags from pkg-config, as that would duplicate info between nixpkgs and upstream.

Now that I think of it, could/should we make a setup hook that copies pkg-config flags to the nixpkgs compiler wrappers? That would be DRY and fix this general issue. Not sure if/what downsides there are.

**Comment by neilmayhew** [comment]
You make a good point. However, the subdir in this case is purely to segregate the library's headers from other headers, and I don't think that serves any purpose in a nix setting. The only time it would matter is if a package wanted to be able to build against two dependencies and there was a clash of header names. Even then, the situation couldn't be solved using `pkg-config` alone.

I can see, however, that `pkg-config --cflags` might still be needed for other reasons, such as setting macro values, and trying to undo the `-I` option while leaving the others would be messy. So I agree that "never needing to get compiler flags from `pkg-config`" isn't something we should aim for.

The setup hook approach sounds nice, but I assume it would a very pervasive change.
