### ISSUE TITLE
Build failure: ubootTools

### ISSUE THREAD

**Issue by Skallwar** [NixOS/nixpkgs#241641]
### Steps To Reproduce

```nix
# test.nix
with import <nixpkgs> {
  crossSystem = {
    config = "aarch64-unknown-linux-gnu";
  };
};

mkShell {
  nativeBuildInputs = [
    ubootTools
  ];
}
```

1. `nix-shell test.nix`

### Build log
https://gist.github.com/Skallwar/ae5b337b4f5e2e438cba4fa39479f016

### Additional context

It's working correctly when not using a crossSystem and puting `ubootTools` in `buildInputs`.
It used to work before

### Notify maintainers

@bartsch
@dezgeg 
@samueldr 
@lopsided98 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/k57fgpvjv1z5lk7w5p5lhp9ikvj04i0i-nix-info
copying path '/nix/store/k57fgpvjv1z5lk7w5p5lhp9ikvj04i0i-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.9, NixOS, 23.11 (Tapir), 23.11.20230623.3ae20aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(esteban): `"nixos-unstable, nixpkgs"`
 - channels(root): `"nixos-22.11, nixos-hardware"`
 - nixpkgs: `/home/esteban/.nix-defexpr/channels/nixpkgs`
```

**Comment by Majiir** [comment]
What is a commit or NixOS version where this was working? When I `nix build .#pkgsCross.aarch64-multiplatform.ubootTools`, it's broken going back at least as far as 22.05.

**Comment by lopsided98** [comment]
This seems to be working now, reopen if not.
