### ISSUE TITLE
rxvt-unicode 9.31 gives prompt in the middle of the screen

### ISSUE THREAD

**Issue by Ten0** [NixOS/nixpkgs#241646]
### Describe the bug
Same thing as https://bugs.archlinux.org/task/77062: prompt is in the middle of the screen.
This doesn't happen on urxvt 9.30.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/9094255/a1da4643-9af5-47c4-8bff-d7bd7a161b86)

### Steps To Reproduce
Probably i3 + urxvt

### Expected behavior
Prompt at top of the screen.

### Additional context
Apparently this is a known bug on the Arch side, and the linked issue gives a patch that fixes it.
https://bugs.archlinux.org/task/77062

### Notify maintainers

@rnhmjoj

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.28, NixOS, 23.11 (Tapir), 23.11.20230701.645ff62`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/12b8sml63980nacpjvh0rlf0w5fg7g8l-source`

**Comment by rnhmjoj** [comment]
"It's not a bug, it's a feature". Seriously, read this [thread](http://lists.schmorp.de/pipermail/rxvt-unicode/2023q2/002661.html). 
Personally I think it's stupid, but I know nothing about terminal emulation. There are two workarounds:

1. If you don't care about text rewrap when you shrink the window, set the resource `urxvt.rewrapMode: never`, which is basically what the default used to be before 9.30.

2. If you want to always rewrap text (I do) just set a very large initial geometry. The prompt will be always out of screen and it will be positioned on the first row when i3 resizes (shrink vertically) the window. I do `URxvt*geometry: 80x240+0+0` for this.

In any case, this is an upstream choice and I don't want to patch urxvt to go against it.

**Comment by Ten0** [comment]
`rewrapMode: never` doesn't seem to change anything for me.
However `geometry: 80x240+0+0` did work.

**Comment by ndrnk** [comment]
I had the same problem. Solved by adding `URxvt*geometry: 80x240+0+0` in .**Xresources**. 
(Gentoo Linux, bash, rxvt-unicode, i3wm)

Thanks a lot!
