### ISSUE TITLE
Package request: keyring-pass

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#241660]
**Project description**

Password Store (pass) backend for python's keyring 

**Metadata**

* homepage URL: https://pypi.org/project/keyring-pass/
* source URL: https://github.com/nazarewk/keyring_pass
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by Freed-Wu** [comment]
[keyrings-passwordstore](https://search.nixos.org/packages?query=keyrings-passwordstore) has broken due to <https://github.com/stv0g/keyrings.passwordstore/issues/2>. Perhaps we can change this alternative.
@shlevy

**Comment by YarekTyshchenko** [comment]
I still haven't managed to fully set all of it up on NixOS, it seems that python keyring and gnome one keep fighting. Would be nice to end up with a wiki entry for this, as its not trivial

**Comment by Freed-Wu** [comment]
Recently looks test failed?
