### ISSUE TITLE
Package request: py-notifier

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#241694]
**Project description**

Python3 module for sending notifications.

**Metadata**

* homepage URL: https://pypi.org/project/py-notifier/
* source URL: https://github.com/YuriyLisovskiy/pynotifier
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by Kranzes** [comment]
Check out [nix-init](https://github.com/nix-community/nix-init), it helps with automating the packaging process of many packages.

**Comment by pbsds** [comment]
please test https://github.com/NixOS/nixpkgs/pull/306122
