### ISSUE TITLE
Package request: pytest-pudb

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#241678]
**Project description**

Pytest PuDB debugger integration based on pytest PDB integration

**Metadata**

* homepage URL: https://pypi.org/project/pytest-pudb/
* source URL: https://github.com/wronglink/pytest-pudb
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by mmlb** [comment]
@Freed-Wu pudb is in nixpkgs now, can you close this please?
