### ISSUE TITLE
VsCode is NOT unfree software

### ISSUE THREAD

**Issue by bckelley** [NixOS/nixpkgs#241716]
### Describe the bug
looking [here](https://search.nixos.org/packages?channel=unstable&show=vscode&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%5D%2C%22package_license_set%22%3A%5B%22Unfree%22%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=alpha_desc&type=packages&query=code) you list vscode as 'License: Unfree' but you can clearly see from their [repo](https://github.com/microsoft/vscode) that it's not it is clearly licensed under MIT. This makes it really hard to install using configuration.nix  when first installing NixOS

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Shawn8901** [comment]
Possibly that here is related to the reason that the precompiled binary is marked as unfree https://github.com/microsoft/vscode/issues/60#issuecomment-161792005

**Comment by bckelley** [comment]
the package itself is MIT free to use the code is not as long as you keep the code the same and only use the package which is my understanding of nix, it should still fall under MIT
