### ISSUE TITLE
Package request: jello

### ISSUE THREAD

**Issue by gkanapathy** [NixOS/nixpkgs#241730]
**jello: Filter JSON and JSON Lines data with Python syntax**

jello is similar to jq in that it processes JSON and JSON Lines data except jello uses standard python dict and list syntax.

JSON or JSON Lines can be piped into jello via STDIN or can be loaded from a JSON file or JSON Lines files (JSON Lines are automatically slurped into a list of dictionaries). Once loaded, the data is available as a python list or dictionary object named ‘_’. Processed data can be output as JSON, JSON Lines, bash array lines, or a grep-able schema.

**Metadata**

* homepage URL: https://kellyjonbrazil.github.io/jello/
* source URL: https://github.com/kellyjonbrazil/jello
* license: MIT
* platforms: unix, linux, darwin, windows (anything with Python)

**Comment by figsoda** [comment]
#241737
