### ISSUE TITLE
protonmail-bridge Get version_linux.json context canceled error

### ISSUE THREAD

**Issue by ElnuDev** [NixOS/nixpkgs#241787]
### Describe the bug
When running `protonmail-bridge`, it gives the following error:

```
ERRO[Jul  5 15:56:24.979] Get "https://proton.me/download/bridge/version_linux.json": context canceled, Attempt 1 
FATA[Jul  5 15:56:24.979] no frontend specified, use --cli, --grpc or --noninteractive 
```

I may have missed something, but I've looked through both nixpkgs issues and upstream and couldn't find another instance of this. Any ideas what's going wrong?

### Steps To Reproduce
1. Install `protonmail-bridge`
2. Run `protonmail-bridge`

### Expected behavior
Proton Mail Bridge runs without errors.

### Notify maintainers

@mrfreezeex

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[elnu@elnu:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.0, NixOS, 23.11 (Tapir), 23.11.20230701.645ff62`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MrFreezeex** [comment]
Hi! Is it the full error? I would expect "context" cancelled to be something upon a ctrl-c/some signal to close protonmail-bridge... How did you run it `nix-shell -p protonmail-bridge` and launch it in your shell?

**Comment by ElnuDev** [comment]
Yes, this is the full error. This is the full console output:

```console
[elnu@elnu:~]$ protonmail-bridge
INFO[0000] Migrating keychain helper                    
NAME:
   ProtonMailBridge - Proton Mail IMAP and SMTP Bridge

USAGE:
   ProtonMailBridge [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --cpu-prof, -p               Generate CPU profile (default: false)
   --mem-prof, -m               Generate memory profile (default: false)
   --log-level value, -l value  Set the log level (one of panic, fatal, error, warn, info, debug)
   --grpc, -g                   Start the gRPC service (default: false)
   --cli, -c                    Start the command line interface (default: false)
   --noninteractive, -n         Start the app in non-interactive mode (default: false)
   --log-imap value             Enable logging of IMAP communications (all|client|server) (may contain decrypted data!)
   --log-smtp                   Enable logging of SMTP communications (may contain decrypted data!) (default: false)
   --help, -h                   show help
ERRO[Jul  5 17:12:02.728] Get "https://proton.me/download/bridge/version_linux.json": context canceled, Attempt 1 
FATA[Jul  5 17:12:02.728] no frontend specified, use --cli, --grpc or --noninteractive
```

I installed it in my configuration (via home manager), and just launched it in my terminal. I didn't press Ctrl+C or anything, it just instantaneously gave the output (not really any wait before the error came up). Thanks!

**Comment by MrFreezeex** [comment]
Yeah so the "real error" is actually the help text. What probably happen is that the bridge use goroutine and cancel other requests instead of checking early that it should exit and print the help message directly.

So for instance if you run `protonmail-bridge -c` it should get you to the cli and you should be able to do stuff in there for instance

**Comment by ElnuDev** [comment]
Alright, I managed to get the bridge all working! The errors seem like they can be safely ignored; I think they've gone away after actually logging in a user through the CLI. Thanks for the help!
