### ISSUE TITLE
Build failure: Filebot

### ISSUE THREAD

**Issue by jshcmpbll** [NixOS/nixpkgs#241821]
### Steps To Reproduce

1. build filebot

### Build log

```
trying https://web.archive.org/web/20230418205553/https://get.filebot.net/filebot/FileBot_5.0.3/FileBot_5.0.3-portable.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0 11650    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0 11650    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0^M  0 11650    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
curl: (22) The requested URL returned error: 503
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0 11650    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503
error: cannot download FileBot_5.0.3-portable.tar.xz from any mirror
```

### Additional context

Tried building my system after upgrading to 23.05 and realize the internet archive was down - 

Curious if we could add a conditional to fetch the package directly from filebot and use internet archive as a backup:
`https://get.filebot.net/filebot/FileBot_5.0.3/FileBot_5.0.3-portable.tar.xz`

I think it makes sense to use the internet archive if the source is down but adding additional usage to their infrastructure is unnecessary if the source is up. Just my 2 cents.
  
### Notify maintainers

@gleber @felschr

**Comment by jshcmpbll** [comment]
I also dont know much about the stability of the source and see it was used back in 2021 so if its just unstable and its easier to pin to the internet archive I understand - https://github.com/NixOS/nixpkgs/commit/2ceafcc27ea25cf0904d10af69ba4bef5845dcdb

Feel free to close if thats the case.

**Comment by felschr** [comment]
The issue with the original source was, that they frequently updated it without changing the version number in the URL and thus the hash would not match anymore. I've just verified that the build using archive.org is working again.

I guess we could add the filebot.net source as a fallback to `fetchurl`'s `srcs`, but I wouldn't want to make it the primary source since I think `fetchurl` doesn't try other URLs in case of a hash mismatch.
