### ISSUE TITLE
Nixos test driver: Test are failing when busybox is installed

### ISSUE THREAD

**Issue by dummy987654321** [NixOS/nixpkgs#241938]
### Describe the bug

Test driver is failing when busybox is installed

### Steps To Reproduce
Run this test (tested against commit`f292b4964cb71f9dfbbd30dc9f511d6165cd109b` (unstable branch the 6th of July))  :
```
{
  nixpkgs ? <nixpkgs>,
}: let
  nixos-lib = import (nixpkgs + "/nixos/lib") { };
  inherit (nixos-lib) runTest;
in runTest (
    {
      name = "Test";

      hostPkgs = import nixpkgs {};

      nodes = {
        machine = ({
          pkgs,
          ...
        }: {
        environment.systemPackages = [
          pkgs.busybox
        ];

        });
      };

      testScript = ''
        start_all()
        machine.wait_for_unit("multi-user.target")
        '';
    }
  )
```
Relevant output:
```
machine: Spawning backdoor root shell...

machine: connected to guest root shell
machine: (connecting took 80.61 seconds)
(finished: waiting for the VM to finish booting, in 80.61 seconds)
machine # [   79.791019] (udev-worker)[800]: eth1: Config file /etc/systemd/network/40-eth1.link is applied to device based on potentially unpredictable interface name.
machine # [   79.826603] (udev-worker)[808]: Network interface NamePolicy= disabled on kernel command line.
machine # [   79.840705] (udev-worker)[800]: Network interface NamePolicy= disabled on kernel command line.
machine # base64: unrecognized option '--wrap'
machine # BusyBox v1.36.1 () multi-call binary.
machine # 
machine # Usage: base64 [-d] [-w COL] [FILE]
machine # 
machine # Base64 encode or decode FILE to standard output
machine # 
machine #       -d      Decode data
machine #       -w COL  Wrap lines at COL (default 76, 0 disables)
cleanup
kill machine (pid 6)
machine # qemu-kvm: terminating on signal 15 from pid 4 (/nix/store/1r6n7v2wam7gkr18gxccpg7p5ywgw551-python3-3.10.12/bin/python3.10)
(finished: cleanup, in 0.04 seconds)
Traceback (most recent call last):
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/__init__.py", line 112, in main
    driver.run_tests()
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 147, in run_tests
    self.test_script()
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/driver.py", line 143, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 2, in <module>
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 454, in wait_for_unit
    retry(check_active, timeout)
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 127, in retry
    if fn(False):
  File "/nix/store/nzz7xim7mixhxjqfmh0ah664ahbrmwgs-nixos-test-driver-1.1/lib/python3.10/site-packages/test_driver/machine.py", line 435, in check_active
    state = info["ActiveState"]
KeyError: 'ActiveState'
kill vlan (pid 5)
```

### Expected behavior
Test should pass.

### Additional context

The test is failing as a consequence of  `base64` invocation here : https://github.com/NixOS/nixpkgs/blob/fe258c0d3f42fbd8a85538a33c99fc6734970fdc/nixos/lib/test-driver/test_driver/machine.py#L536

This can be easily fixed by changing the `--wrap` flag to `-w` (the latest being supported by busybox) in the line above but I don't know how to correctly test my fix since it is a change in a core feature of nixpkgs (For the moment I only tested it on the above test). However I strongly believe it won't break things.

### Notify maintainers

There is no maintainers https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/test-driver/default.nix

@R-VdP is the last one to have modified the faulty line according to git blame

cc @RaitoBezarius also

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-76-generic, Ubuntu, 22.04.2 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by bjornfor** [comment]
If it's inside the VM the problem appears, shouldn't we use abspath to the correct base64 instead of hoping the one in PATH is compatible?

**Comment by R-VdP** [comment]
Hmm, yeah, but that would introduce a stronger coupling between the test-driver and the VM.
Using `/run/current-system/sw/base64` is equally unreliable, because some VMs could have `busybox` added to the system path, in which case we could still end up with the wrong `base64` there.

Using the actual store path would completely avoid these issues, but it would also mean that the test-driver needs to have a lot more information about the VM it runs.

I also have a personal use-case where I use the test-driver with non-NixOS VMs, which would not be possible anymore if we tie it more closely to NixOS. This is not an argument against such coupling in and of itself, and I can always adapt by carrying my own patches or fork, but there might be other such uses around.

**Comment by bjornfor** [comment]
Ok, making it compatible with busybox sounds fine.
