### ISSUE TITLE
vdirsyncer: Update in stable nixos?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#24199]
## Issue description

[Here](https://github.com/pimutils/vdirsyncer/issues/606) is a discussion that "vdirsyncer" is old in nixpkgs. It is current in unstable and master, but not in 17.03, so I'm asking: Should we update this package in the stable nixos channel or what's the procedure here?

**Comment by globin** [comment]
17.03 has vdirsyncer 0.14.1?
```
nix-build -A vdirsyncer
/nix/store/6csgfxf9ap9x8zb7g7mm0nbjcrbc9fmy-vdirsyncer-0.14.1
```

**Comment by matthiasbeyer** [comment]
Hm. Then I wonder why @unitaker said that there is an old version in nixpkgs. :curly_loop:

**Comment by globin** [comment]
Probably in 16.09 because 17.03 is in beta

**Comment by matthiasbeyer** [comment]
So I guess I can close this.

**Comment by untitaker** [comment]
0.14.1 is not the latest vdirsyncer version by the way.

**Comment by untitaker** [comment]
I'm even more confused right now. @globin says 17.03 is beta, @matthiasbeyer says in https://github.com/pimutils/vdirsyncer/issues/606 that 17.03 is stable. Which is it?

**Comment by untitaker** [comment]
It appears 17.03 really is beta.

In either case, both channels are outdated. 0.15 is the latest vdirsyncer version.

**Comment by matthiasbeyer** [comment]
@untitaker I got that wrong. 17.03 is about to become stable.

**Comment by untitaker** [comment]
@matthiasbeyer could you update vdirsyncer in 17.03 then?
