### ISSUE TITLE
zen kernels have their features disabled via kernel config

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#241986]
### Describe the bug
I see that the custom CPU scheduler, zen's main feature is disabled:
```
   zgrep CONFIG_SCHED_ALT /proc/config.gz
# CONFIG_SCHED_ALT is not set
```
This raises a question: does nixpkgs' zen actually differs from the default kernel or nixpkgs disables all the customizations by applying the same config as to the default kernel?

Moreover, nixpkgs provides the -lqx variant with the same config but the main difference between -zen and -lqx variants is the config: liquorix provides a pre-defined config with its Debian/Arch packages and when I see lqx in the repos, I expect nixpkgs to use it as well as there's no source code difference. The -lqx variant seem to be poorly maintained in nixpkgs in general, it lags behind -zen variant (6.4.1 vs 6.3.11 in current nixos-unstable).

### Steps To Reproduce
1. `zgrep CONFIG_SCHED_ALT /proc/config.gz`

### Expected behavior
-zen should have its features enabled more or less, the -lqx variant MUST use [the upstream config](https://github.com/damentz/liquorix-package/blob/6.4/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-64) (and probably be available only for x86_64). See the [AUR -lqx package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-lqx#n152) for example. Would be nice to have variants with different schedulers like the AUR package allows, preferably pre-built on Hydra (well, I don't have a powerful enough hardware to build kernels).

### Notify maintainers
@TredwellGit @Ma27 @NeQuissimus @alyssais

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.4-zen1, NixOS, 23.11 (Tapir), 23.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/etc/static/nixpkgs`
```

**Comment by ilya-fedin** [comment]
It might be a good idea to also have a xanmod variant built with [upstream config](https://sourceforge.net/projects/xanmod/files/releases/main/6.3.12-xanmod1/patch-6.3.12-xanmod1.xz/download).

**Comment by thiagokokada** [comment]
> This raises a question: does nixpkgs' zen actually differs from the default kernel or nixpkgs disables all the customizations by applying the same config as to the default kernel?

I created a PR that should fix this: https://github.com/NixOS/nixpkgs/pull/242722

> Moreover, nixpkgs provides the -lqx variant with the same config but the main difference between -zen and -lqx variants is the config: liquorix provides a pre-defined config with its Debian/Arch packages and when I see lqx in the repos, I expect nixpkgs to use it as well as there's no source code difference.

I took a look at the Arch config for -zen and it looks like it is basically the vanilla kernel with `CONFIG_ZEN_INTERACTIVE=y` and some tweaks to the RCU/Preempt/tick. So this is what I did above. For the -lqx variation, I activated the PDS process scheduler, BBR2 and other tricks that seems to make Liquorix kernel (according to the site: https://liquorix.net/).

> The -lqx variant seem to be poorly maintained in nixpkgs in general, it lags behind -zen variant (6.4.1 vs 6.3.11 in current nixos-unstable).

This is not exactly true, the release of the -lqx variant generally lags between major kernel releases, so while -zen gets to X.Y.Z, -lqx will stay in X.Y-1.Z for some weeks (I imagine for stability purposes, but I am not familiar with upstream).

> the -lqx variant MUST use [the upstream config](https://github.com/damentz/liquorix-package/blob/6.4/master/linux-liquorix/debian/config/kernelarch-x86/config-arch-64)

This will be difficult, because we can't simply take its configuration as-is. If the current approach in the PR above is not acceptable, I would say it is better to just remove the -lqx from nixpkgs.

> Would be nice to have variants with different schedulers like the AUR package allows

We already don't seem to have that many users of the current variants considering you're the first person to note that we are compiling the packages without the customizations. So unless there is really a strong demand I would say let's not do so and just keep 2 variations of this kernel that should be enough for most users.

**Comment by ilya-fedin** [comment]
> This will be difficult, because we can't simply take its configuration as-is. If the current approach in the PR above is not acceptable, I would say it is better to just remove the -lqx from nixpkgs.

It's acceptable as a first step but why can't we?

**Comment by ilya-fedin** [comment]
> We already don't seem to have that many users of the current variants considering you're the first person to note that we are compiling the packages without the customizations.

I guess the minority checks actually? I periodically see in Arch groups how people try -zen thinking they get all the features for better responsiveness but don't see a difference and don't even think about checking what scheduler they run actually.

**Comment by thiagokokada** [comment]
> > This will be difficult, because we can't simply take its configuration as-is. If the current approach in the PR above is not acceptable, I would say it is better to just remove the -lqx from nixpkgs.
> 
> It's acceptable as a first step but why can't we?

It would be really difficult to use upstream configuration as-is. I mean, I don't think it is impossible, but I definitely don't want to be the person to do so.

> > We already don't seem to have that many users of the current variants considering you're the first person to note that we are compiling the packages without the customizations.
> 
> I guess only the minority checks actually? I periodically see in Arch groups how people try -zen thinking they get all the features for better responsiveness but don't see a difference and don't even think about checking what scheduler they run actually.

What I mean is mostly that I don't think most people care anyway. Even users of those custom kernels doesn't seems to care too much if they're actually using a custom scheduler it seems, considering again you're the first person to note this issue and this kernel is in nixpkgs for a long time already.

So considering that nobody is that interested in the first place I think adding another variation of those kernels is too much. We definitely can do in the future if there is enough people that wants those though.

**Comment by ilya-fedin** [comment]
> What I mean is mostly that I don't think most people care anyway.

What I mean is they do care, it's just they don't know how to check. They see -zen and believe they get all the features out of the box.
