### ISSUE TITLE
golly: not drawing center area

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#24204]
## Issue description

I can run golly just fine, it seems to compute, but it doesn't draw the playing field (center area) at all.

### Steps to reproduce
1. `nix-shell -p golly --run golly`
2. center area not redrawn

## Technical details

* System: 17.09pre-git
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre102667.2839b10

**Comment by 7c6f434c** [comment]
Oh how interesting. Apparently, Golly uses OpenGL in some complicated way: the drawing works for me with `DRI_PRIME=1` but not without (i.e. it works via `nouveau` but not via `i965`/`modesetting`).

Maybe takin upstream beta release from their Git will help, no idea. Will try at some point.

**Comment by yorickvP** [comment]
This is as far as I got from git, doesn't seem to want to compile, something with fpermissive.

```nix
pkgs.golly.overrideDerivation (attr: rec {
      version = "20170322";
      name = "golly-${version}";
      src = pkgs.fetchgit {
        url = "git://git.code.sf.net/p/golly/code";
        rev = "9d9c61b019759115559d9fac756a5d745f533b59";
        sha256 = "0wpg2wk17kn4qywjvwyjmf2s09c4bf5gm5rlxapb63n2cr867apc";
      };
      sourceRoot="code-9d9c61b/gui-wx/configure";
      NIX_CFLAGS_COMPILE = "-fpermissive";
      buildInputs = with pkgs; attr.buildInputs ++ [ autoconf automake ];
      preConfigure = ''
        ${attr.preConfigure}
        patchShebangs autogen.sh
        ./autogen.sh
      '';
    })
```

**Comment by 7c6f434c** [comment]
OK, I added 2.9b2 just to test; on my system it is not better — maybe you will be more lucky. I have DRI_PRIME mode anyway…

**Comment by yorickvP** [comment]
Hmm, yeah, I don't have DRI_PRIME mode. I'll try it on the nvidia system.

2017-03-22 16:55 GMT+01:00 Michael Raskin <notifications@github.com>:

**Comment by 7c6f434c** [comment]
Well, maybe `golly-beta` would work better for you, although the chances
are not too high.

Actually, what _should_ fix something is what I have just pushed to 
master: a switch to fresher wxGTK.

**Comment by yorickvP** [comment]
Seems to be working now.
