### ISSUE TITLE
Build failure: davinci-resolve: > curl: (3) URL rejected: Malformed input to a URL function

### ISSUE THREAD

**Issue by pearsche** [NixOS/nixpkgs#242091]
### Steps To Reproduce

1. build davinci-resolve

### Build log

```
curl: (3) URL rejected: Malformed input to a URL function
```

### Notify maintainers
@jshcmpbll 

Uh, also while checking, in search.nixos.org the source link for davinci-resolve points to [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/build-support/build-fhsenv-bubblewrap/default.nix#L226) instead of [here](https://github.com/NixOS/nixpkgs/blob/73d174c62ba412c79358895282b6ecee9497469a/pkgs/applications/video/davinci-resolve/default.nix#L30)
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.4-zen1, NixOS, 23.11 (Tapir), 23.11.20230627.e18dc96`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jshcmpbll** [comment]
@pearsche I tried building off of f8043b5259ee2f92a2aab1c264accceda7a7e315 and it seemed to build fine

How are you building it so I can try to replicate the issue?

**Comment by pearsche** [comment]
I updated my home-manager flake, and the reported commit hash it now uses says its from 2 days ago so I just have to wait then. Thank you.

**Comment by bew** [comment]
According to the PR tracker (https://nixpk.gs/pr-tracker.html?pr=242043), the PR behind f8043b5 is available in `nixos-unstable-small`

But when I try to use it using:
`NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:nixos/nixpkgs/nixos-unstable-small#davinci-resolve`
(`nixos-unstable-small` is currently at 986caf51a859110e3adba09ac5e0240e192014cd)

But I'm getting the same error, do I need something else to try it?

**Comment by bew** [comment]
I was also on Nix 2.15.1, testing with 2.16.1 give the same error.
```console
$ nix shell unstable#nixVersions.nix_2_16 -c zsh

$ nix --version
nix (Nix) 2.16.1

$ NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:nixos/nixpkgs/986caf51a8#davinci-resolve
error: builder for '/nix/store/gg4zdpkqb69x3sn0ydg4i53paapzd50x-davinci-resolve-src.zip.drv' failed with exit code 3;
       last 1 log lines:
       > curl: (3) URL rejected: Malformed input to a URL function
       For full logs, run 'nix log /nix/store/gg4zdpkqb69x3sn0ydg4i53paapzd50x-davinci-resolve-src.zip.drv'.
error: 1 dependencies of derivation '/nix/store/9v4fmg8b2n7pn282bvnz4ryrd8s9y1p0-davinci-resolve-18.1.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w9rqbpn1x5m4m9fv89xd8bmj8dcjdvxz-davinci-resolve-usr-target.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yj1lgbqz5188zm2bc5ffzznvzlzs5xhz-davinci-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8pc064agdhr5pzrfmzfpvl3jqyipijyq-davinci-resolve-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nbgi6pb44qdimpqs3znsfqaga45pxlby-davinci-resolve-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q82i2hgglpcgbhi73w5pdx19viqgl4wi-davinci-resolve.drv' failed to build
```

**Comment by jshcmpbll** [comment]
@bew When you have a moment can you post the full build log - `nix log /nix/store/gg4zdpkqb69x3sn0ydg4i53paapzd50x-davinci-resolve-src.zip.drv`

**Comment by bew** [comment]
Adding an echo of the resolved url immediately shows the issue:
```diff
diff --git a/pkgs/applications/video/davinci-resolve/default.nix b/pkgs/applications/video/davinci-resolve/default.nix
index 459208f411c..e4bfad2e8f3 100644
--- a/pkgs/applications/video/davinci-resolve/default.nix
+++ b/pkgs/applications/video/davinci-resolve/default.nix
@@ -89,20 +89,21 @@ let
           --header 'Content-Type: application/json;charset=UTF-8' \
           --header "Referer: https://www.blackmagicdesign.com/support/download/$REFERID/Linux" \
           --header 'Accept-Encoding: gzip, deflate, br' \
           --header 'Accept-Language: en-US,en;q=0.9' \
           --header 'Authority: www.blackmagicdesign.com' \
           --header 'Cookie: _ga=GA1.2.1849503966.1518103294; _gid=GA1.2.953840595.1518103294' \
           --data-ascii "$REQJSON" \
           --compressed \
           "$SITEURL")
 
+        echo "Resolved URL: $RESOLVEURL"
         curl \
           --retry 3 --retry-delay 3 \
           --header "Host: sw.blackmagicdesign.com" \
           --header "Upgrade-Insecure-Requests: 1" \
           --header "$USERAGENT" \
           --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" \
           --header "Accept-Language: en-US,en;q=0.9" \
           --compressed \
           "$RESOLVEURL" \
           > $out
```

And the log is:
```
Resolved URL: Error: Must register to be able to perform the download
curl: (3) URL rejected: Malformed input to a URL function
```

**Comment by stelcodes** [comment]
Running into the same issue and error message myself

**Comment by jshcmpbll** [comment]
@stelcodes Yeah, @bew is right. Even the [arch package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=davinci-resolve)  where a lot of this is source from is suffering from the same error. Trying to see if I can get it to work rn, stay tuned

**Comment by jshcmpbll** [comment]
Ah, they added a street requirement for the form haha. Im going to set it to the chamber of commerce in Utrecht since thats where the Nix foundation is registered

**Comment by jshcmpbll** [comment]
Should be able to build off of: `NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:jshcmpbll/nixpkgs/jc/davinci_registration_payload#davinci-resolve`

**Comment by bew** [comment]
> `NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:jshcmpbll/nixpkgs/jc/davinci_registration_payload#davinci-resolve`

getting the source worked, but now davinci-resolve drv is failing with:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rfxva36fcys7lmmqlmdjh1m6006zmgzy-davinci-resolve-src.zip
source root is /build
setting SOURCE_DATE_EPOCH to timestamp 1677805864 of file /build/DaVinci_Resolve_18.1.4_Linux.run
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile or custom buildPhase, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Uncompress DaVinci_Resolve_18.1.4_Linux.run of type 02 @ offset 193760

Write on output file failed because No space left on device

FATAL ERROR: writer: failed to write file /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/Onboarding/lib/libQt5Core.so.5
DaVinci_Resolve_18.1.4_Linux.run is now installed in /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e
/build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/AppRun: line 346: /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/installer: No such file or directory
Copying '/nix/store/j8r6n62rac9g3avws5nbhrvs3a2s413f-davinci-resolve.desktop/share/applications/davinci-resolve.desktop' into '/nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4/share/applications'
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4
checking for references to /build/ in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4...
patching script interpreter paths in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4
ln: failed to create symbolic link '/nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4/libs/libcrypt.so.1': No such file or directory
/nix/store/blpvf60m29q02c0lc5fyhim30ma4y1vv-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

**Comment by bew** [comment]
Now I can DL the sources, but uncompressing fills up the build folder and ends in a `No space left on device` error :/
(which is seemingly not catched as the execution seems to follow afterward)
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rfxva36fcys7lmmqlmdjh1m6006zmgzy-davinci-resolve-src.zip
source root is /build
setting SOURCE_DATE_EPOCH to timestamp 1677805864 of file /build/DaVinci_Resolve_18.1.4_Linux.run
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile or custom buildPhase, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Uncompress DaVinci_Resolve_18.1.4_Linux.run of type 02 @ offset 193760

Write on output file failed because No space left on device

FATAL ERROR: writer: failed to write file /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/Onboarding/lib/libQt5Core.so.5
DaVinci_Resolve_18.1.4_Linux.run is now installed in /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e
/build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/AppRun: line 346: /build/home/.cache/appimage-run/cab14d6a6a873f649e79e1a8b6a2a446e5762bae012fc7b3d318c9d9bee5500e/installer: No such file or directory
Copying '/nix/store/j8r6n62rac9g3avws5nbhrvs3a2s413f-davinci-resolve.desktop/share/applications/davinci-resolve.desktop' into '/nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4/share/applications'
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4
checking for references to /build/ in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4...
patching script interpreter paths in /nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4
ln: failed to create symbolic link '/nix/store/n3xwz7wspbcs4ixb03ldax1plwv5m9mz-davinci-resolve-18.1.4/libs/libcrypt.so.1': No such file or directory
/nix/store/blpvf60m29q02c0lc5fyhim30ma4y1vv-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
```

I tried setting `TMPDIR` to a folder on a partition with lot's of space without success :/ Do you know how to avoid this?

**Comment by jshcmpbll** [comment]
@bew Honestly im not sure. Checking my `/nix/store` it looks like the source is about 3.0GiB

```bash
~ du -sh /nix/store/rfxva36fcys7lmmqlmdjh1m6006zmgzy-davinci-resolve-src.zip
3.0G    **/nix/store/rfxva36fcys7lmmqlmdjh1m6006zmgzy-davinci-resolve-src.zip
```
So it filling up your `tmpfs` at `3,8G` makes sense.. Reading up on some other issues I think this might be what you are looking for if you are on NixOS, just adjust the tmpfs size larger than the default 50%:

https://search.nixos.org/options?channel=23.05&show=boot.tmp.tmpfsSize&from=0&size=50&sort=relevance&type=packages&query=tmpfs

https://github.com/NixOS/nixpkgs/issues/54707
https://github.com/NixOS/nixpkgs/issues/23912

**Comment by bew** [comment]
> Should be able to build off of: `NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:jshcmpbll/nixpkgs/jc/davinci_registration_payload#davinci-resolve`

Thanks, I confirm that works, I can build davinci-resolve (now I just need to find a suitable GPU.... 😅)

**Comment by tnichols217** [comment]
I tested @jshcmpbll 's patch to the package, and it wasnt working for me. I found out that the Host for the second curl request to blackmagic's download site was mismatched, so I updated the host to their new site and also updated the street address to the actual location of the nix non-profit (found on the KVK's business lookup). I've tested on all (3) my machines and it builds successfully so if anyone else here would like to try, that would be great.

Heres the PR: #246074
And my fork is at `github:tnichols217/nixpkgs`#davinci-resolve

**Comment by tnichols217** [comment]
Just tried rebuilding today and having the same issue. Looks like blackmagic moved back to the sw.blackmagicdesign.com host and have blocked sw.cloud.blackmagicdesign.com. Maybe we should just remove the host header entirely from the curl command? If we are having hashed outputs verified, then it wouldnt matter which host it comes from?

**Comment by jshcmpbll** [comment]
Yeah, sounds like they may be doing some sort of canary release for new infrastructure or something. I agree, that makes sense to remove it.

**Comment by tnichols217** [comment]
Should I submit a new pull?

**Comment by tnichols217** [comment]
New PR at #246647

**Comment by borttappat** [comment]
Had a problem when building today.

warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/5rzyih1f2d6g9gnxiin0xi34pk3jijgj-davinci-resolve-src.zip.drv^*'
downloadid is f38fc270c4c040bea4782182d0fbb367
curl: (3) URL rejected: Malformed input to a URL function
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
