### ISSUE TITLE
Travis PR builds get killed in nix-instantiate of `eval-release.nix` while building nixpkgs-tarball-17.09pre1234.abcdef.drv

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#24200]
No Travis PR build succeeded in the last 10 hours.

All of the failures I've seen to have one thing in common:

```
*** Downloading ‘https://cache.nixos.org/nar/079bb500c9337awi8jsl5m4bifxdzbf3h655k5pysrlxgjm990ij.nar.xz’ to ‘/nix/store/q3f9hj13hysgdb5yx5a50mnqmjgcjp5p-stdenv’...
building path(s) ‘/nix/store/pl254j9qpwmlyh2j0p8i0d1fgailh9w0-nixpkgs-tarball-17.09pre1234.abcdef’
unpacking sources
unpacking source archive /nix/store/gaw0bxd8kb2j3sqmdnq38b7gilff79cw-nixpkgs
source root is nixpkgs
patching sources
autoconfPhase
No bootstrap, bootstrap.sh, configure.in or configure.ac. Assuming this is not an GNU Autotools package.
configuring
release name is nixpkgs-17.09pre1234.abcdef
building
no Makefile, doing nothing
running tests
pkgs/os-specific/linux/musl/default.nix:  # nix-build "<nixpkgs/pkgs/stdenv/linux/make-bootstrap-tools.nix>"
pkgs/applications/virtualization/virtualbox/guest-additions/default.nix:  # Forced to 1.18 in <nixpkgs/nixos/modules/services/x11/xserver.nix>
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
checking Nixpkgs on i686-linux
checking Nixpkgs on x86_64-linux
checking Nixpkgs on x86_64-darwin
checking eval-release.nix
/nix/store/q3f9hj13hysgdb5yx5a50mnqmjgcjp5p-stdenv/setup: line 936:  1988 Killed                  nix-instantiate --eval --strict --show-trace ./maintainers/scripts/eval-release.nix > /dev/null
build time elapsed:  0m0.036s 0m0.056s 4m22.732s 0m31.680s
builder for ‘/nix/store/kyyxxaa6b1mq6hsda2sbx0nrf8fj4s50-nixpkgs-tarball-17.09pre1234.abcdef.drv’ failed with exit code 137
error: build of ‘/nix/store/kyyxxaa6b1mq6hsda2sbx0nrf8fj4s50-nixpkgs-tarball-17.09pre1234.abcdef.drv’ failed
```

**Comment by globin** [comment]
Probably OOM

**Comment by grahamc** [comment]
Maybe a recursion issue?

**Comment by deepfire** [comment]
Why does this only happen on Travis?

**Comment by 7c6f434c** [comment]
The total virtual memory size requirement is a bit above 4GiB: 4.25 GiB VMEM is not enough, 4.5GiB is OK. GC complains about OOM at 3662MiB pure heap. I tested with ulimit, so on a 4GiB RAM VM you could use disk-backed pages for executables, but hitting OOM is still very likely. I guess people who use Nix on <6GiB RAM computers consider these computers weak and don't run pointless integrity checks there…

**Comment by matthewbauer** [comment]
We can disable "nixpkgs-tarball" in .travis.yml. Usually, it works because the tarball is already in the binary cache. We wanted it in there to make sure no ps are breaking/modifying the taball (usually they don't touch it though). It will always fail when [nixpkgs:trunk:tarball](https://hydra.nixos.org/job/nixpkgs/trunk/tarball) fails.

**Comment by deepfire** [comment]
If there is no other way (i.e. this particular computation is unavodably over the space limit AND the limit cannot be raised) -- who can effect the change @matthewbauer proposes? @grahamc, @globin?

**Comment by 7c6f434c** [comment]
Well, I think `eval-release` could be made less hungry by running 27 evaluations one after another (a-z and non-alpha first character in the top-level attribute name)…
