### ISSUE TITLE
Imprecise meta.position with buildFHSEnv

### ISSUE THREAD

**Issue by jshcmpbll** [NixOS/nixpkgs#242093]
https://github.com/NixOS/nixpkgs/issues/242091

> Uh, also while checking, in search.nixos.org the source link for davinci-resolve points to [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/build-support/build-fhsenv-bubblewrap/default.nix#L226) instead of [here](https://github.com/NixOS/nixpkgs/blob/73d174c62ba412c79358895282b6ecee9497469a/pkgs/applications/video/davinci-resolve/default.nix#L30)

If you search for the package in [`23.05`](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=davinci) its fine but [`unstable`](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=davinci) points to `build-fhsenv-bubblewrap`

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/242099
