### ISSUE TITLE
No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file on MacOS

### ISSUE THREAD

**Issue by Rizary** [NixOS/nixpkgs#24211]
## Issue description
Hi, I'm finally able to build and compile my haskell project. But I got the following error:

`2017-03-22 21:07:20.683 frontend[79041:2235329] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting`

is there any way to know how to add info.plist to my program? is it in default.nix or else?

### Steps to reproduce

build using webkitgtk-2.4.11

## Technical details

* System: (MacOs)
* Nix version: (run `1.11.7`)
* Nixpkgs version: (17.09pre-git)

**Comment by matthewbauer** [comment]
You're going to have to create an [app](https://en.wikipedia.org/wiki/Bundle_(macOS)) [bundle](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1). The basic structure is:

```
MyApp.app/
   Contents/
      Info.plist
      MacOS/
        <binary here>
      Resources/
```

Info.plist is tricky, but you can find some examples looking in /Applications/. Here is the source from [Emacs](https://bitbucket.org/mituharu/emacs-mac/src/2c7094c3affa620011b762a7f93268fdf8a7f75e/mac/templates/Info.plist.in?at=master&fileviewer=file-view-default).

**Comment by Rizary** [comment]
@matthewbauer hi, yeah i see it when my app build like this:

```
Linking dist/build/frontend/frontend ...
Creating application bundle directory dist/build/frontend.app
Copying executable frontend into place from dist/build/frontend/frontend to dist/build/frontend.app/Contents/MacOS/frontend
Copying macos/Info.plist to dist/build/frontend.app/Contents/Info.plist
Running: /Applications/XCode.app/Contents/Developer/Tools/Rez Carbon.r -o dist/build/frontend.app/Contents/MacOS/frontend
Running: /Applications/XCode.app/Contents/Developer/Tools/SetFile -a C dist/build/frontend.app/Contents
```

After i manage to build it. However, there is no dist/build/frontend, so i recreated it once again, but still I cannot run and got the following report:

```
Application Specific Information:
abort() called
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'

```

So do I need to create the frontend.app manually every time I finish my compilation ?

**Comment by matthewbauer** [comment]
Could you provide your current setup? The issue is probably in your build files.

**Comment by matthewbauer** [comment]
Can we close this due to inactivity?
