### ISSUE TITLE
nix-prefetch-url --unpack needs unzip or it fails

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#24213]
```bash
$ nix-prefetch-url --unpack ...
downloading ...
unpacking...
error: executing 'unzip': No such file or directory
```

It seems this is an oversight. `unzip` should be installed as a dependency of `nix-prefetch-url` either visibly or invisibly.

**Comment by 3noch** [comment]
Installing `unzip` fixes it, of course.

**Comment by globin** [comment]
cc @edolstra @shlevy

**Comment by domenkozar** [comment]
This is a bug in Nix, it should claim dependency on `unzip` at runtime: https://github.com/NixOS/nix/blob/master/src/nix-prefetch-url/nix-prefetch-url.cc#L173

**Comment by domenkozar** [comment]
Relevant is https://github.com/NixOS/nix/issues/1234

**Comment by ledettwy** [comment]
Ran into this today, seems like a really silly issue.

**Comment by 3noch** [comment]
Is this fixed?

**Comment by 3noch** [comment]
Was this fixed?

**Comment by edolstra** [comment]
Closing this since it's a Nix (not Nixpkgs) issue. It should be fixed because we're using libarchive now.

**Comment by 3noch** [comment]
Great!
