### ISSUE TITLE
Google Chrome is super buggy/broken after a recent upgrade

### ISSUE THREAD

**Issue by SimonBrandner** [NixOS/nixpkgs#242113]
### Describe the bug
Google Chrome is super buggy/broken after a recent upgrade

### Steps To Reproduce

Use the config from [here](https://github.com/SimonBrandner/dotfiles/tree/main/Root/etc/nixos) (the Tuxedo version) with an up to date nix channel

### Expected behavior

Google Chrome to work flawlessly

### Screenshots
![Screenshot_20230707_201601](https://github.com/NixOS/nixpkgs/assets/25768714/be1478a3-edd7-4116-8bcb-001cc3c1ce51)
![Screenshot_20230707_201633](https://github.com/NixOS/nixpkgs/assets/25768714/b159bf1d-1427-4354-84a9-887191fc2d0b)
![Screenshot_20230707_201649](https://github.com/NixOS/nixpkgs/assets/25768714/82479f93-800e-4b73-80cc-aa4f9a5122cf)
![Screenshot_20230707_201711](https://github.com/NixOS/nixpkgs/assets/25768714/2a2c1090-005f-4dc7-9419-9564c9888f43)

### Additional context

Possibly related: https://github.com/NixOS/nixpkgs/issues/238416, https://github.com/NixOS/nixpkgs/issues/241337

### Metadata
```console
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/91hwyc6c4r474zs56n9idbqj17dlcnna-stdenv-linux
copying path '/nix/store/91hwyc6c4r474zs56n9idbqj17dlcnna-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.05 (Stoat), 23.05.1532.aed4b19d312`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SimonBrandner** [comment]
Visual Studio Code doesn't seem to launch for me at all

**Comment by SimonBrandner** [comment]
Element Desktop also seems to suffer from the same symptoms

**Comment by SimonBrandner** [comment]
Discord and VS Code do seem to run though

**Comment by SimonBrandner** [comment]
Seems to be this: https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

**Comment by SimonBrandner** [comment]
Hah, found a fix/the cause, as described in https://bbs.archlinux.org/viewtopic.php?pid=2098657#p2098657, do `rm -rf .config/google-chrome/Default/GPUCache/`

**Comment by imincik** [comment]
For the record, `rm -rf .config/google-chrome/Default/GPUCache/` fixed my issues with browser as well.

**Comment by matousss** [comment]
### For people for whom the solution above does not work
I had exactly the same problem but removing cache **did not** solve the issue :(. Today I discovered that **disabling hardware acceleration** fixes the UI for me.

Hope this will help someone.

**Comment by SimonBrandner** [comment]
It would also be good to note that this happens quite frequently to me after updates

**Comment by dbalmain** [comment]
> For the record, `rm -rf .config/google-chrome/Default/GPUCache/` fixed my issues with browser as well.

@imincik  I'm not sure if you were in the same situation as me, but this didn't work for me because I'm using Chrome profiles. I had to delete all of the GPUCache folders.

```sh
find .config/google-chrome/ -type d -name GPUCache -exec rm -rf "{}" \;
```
