### ISSUE TITLE
build-support: need a "fetch from git-repo"

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#24228]
Referring to [git-repo](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-repo/default.nix), not Git.

Should allow local manifests and specified repo repositories (who fucking decided repo was a good name for this tool?!)

The problem is how to do it without wasting a huge amount of bandwidth/disk space...?

**Comment by mmahut** [comment]
Why can such a repo not be fetched with current tools?

**Comment by spacekitteh** [comment]
Not sure about the current status.
