### ISSUE TITLE
Module request: inadyn

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#242330]
ddclient was removed in #241462, with inadyn being the closest suggested replacement. inadyn is packaged in Nixpkgs, but does not have a NixOS module. An inadyn NixOS module would be useful as a replacement.

**Comment by Emantor** [comment]
The first step is fixing inadyn itself, since it currently won't start due to a wrongly configured `localstatedir`, see #243785.

**Comment by lunik1** [comment]
We will also need to decide if it's better to run as a systemd service, timer, or give the user the option to choose. I lean towards the latter.

**Comment by Emantor** [comment]
AFAICS inadyn does not contain additional logic to detect IP address changes. Because of this I would also lean towards the timer functionality.

**Comment by lunik1** [comment]
I think it does. Looking at [inadyn.conf(5)](https://man.archlinux.org/man/inadyn.conf.5.en), inadyn will only update the ip if changed every `preroid` seconds and always update it every `forced-update` seconds. I'm not clear on how those options behave in oneshot mode.

**Comment by sjau** [comment]
Well, so far I called ddclient with cron, since the machine running will not easil see altered public IP change. I tried to use inadyn but can't get it to work with desec.io / dedyn.io.

**Comment by lunik1** [comment]
I've had some time to poke around this a bit more, and it seems like inadyn cannot read credentials from the environment or a file separate to the config, so all your DDNS credentials will end up world-readable in the store.

**Comment by lunik1** [comment]
I've made a pretty barebones module for my personal config here https://gitlab.com/lunik1/nix-config/-/blob/master/modules/system/inadyn.nix?ref_type=heads. It runs inadyn in oneshot mode using a timer, and is configured entirely by specufying a `configFile`.

**Comment by lunik1** [comment]
Submitted a full NixOS module as https://github.com/NixOS/nixpkgs/pull/260962, I would appreciate if inadyn users could test it :slightly_smiling_face:.

**Comment by sjau** [comment]
> Submitted a full NixOS module as #260962, I would appreciate if inadyn users could test it 🙂.

Add a small example for how to use it?

**Comment by lunik1** [comment]
Sure, here's a config to use namecheap:

```nix
  services.inadyn = {
    enable = true;
    # controls how often your IP is checked, should be a format a systemd timer will understand
    interval = "*-*-* *:*:00";
    # these settings map 1:1 to those in inadyn.conf, check inadyn.conf (5)
    settings = {
      allow-ipv6 = false;
      forced-update = 60;
      custom."namecheap" = {
        # you can use include to keep your auth info in a seperate file and manage it with e.g. sops-nix
        include     = ./auth.txt;
        ddns-server = "dynamicdns.park-your-domain.com";
        ddns-path   = "/update?domain=%u&password=%p&host=%h&ip=%i";
        hostname    = [ "@" "*" ];
      };
    };
    # alternatively to settings, just speify a full config file
    # configFile = ./your/existing/inadyn.conf;
  };
```
