### ISSUE TITLE
Package request: feishin

### ISSUE THREAD

**Issue by jcmolinajr** [NixOS/nixpkgs#242373]
**Project description**

 full-featured Subsonic/Jellyfin compatible desktop music player

**Metadata**

* homepage URL: http://feishin.vercel.app/
* source URL: https://github.com/jeffvli/feishin
* license: GPL-3.0
* platforms: linux, darwin

**Comment by Gecked-Deck** [comment]
Could this possibly be based on the sonixd package? I'd imagine they share some similar properties.

**Comment by jcmolinajr** [comment]
Indeed. Feishin is a complete rewrite of Sonixd by the same developer.

From: https://github.com/jeffvli/sonixd

> NOTICE: Maintenance Mode
> The application is undergoing a full rewrite under the name Feishin. [Check it out here!](https://github.com/jeffvli/feishin)
> 
> Sonixd has entered maintenance mode as of 0.15.4. Only breaking bugs will be fixed. The application will continue to be available for download and use, but no new features will be added. The application will be maintained until the rewrite is complete.

**Comment by onny** [comment]
Solved with https://github.com/NixOS/nixpkgs/pull/219005 🥳
