### ISSUE TITLE
sddm fails to start on 17.03, master

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#24246]
## Issue description

sddm fails to start, complaining many times about being unable to find 'QtQuick'.

My configuration works on c458d7cf94ebe181665511a7daaa3cb337a04bc4 but fail on current `nixos-17.03`, `release-17.03`, and `master` branches.

It seems this was missed because the NixOS test for SDDM uses an auto-login mechanism that apparently avoids the problem.  Modifying the test to instead just let SDDM run reproduces the issue.  See below.

### Steps to reproduce

AFAIK simply adding `xserver.displayManager.sddm.enable = true;` to configuration.nix does the trick, however here's a NixOS test that demonstrates the issue.  It works for me on the mentioned good-commit above, and fails on current master:

```
import ./make-test.nix ({ pkgs, ...} : {
  name = "sddm";

  machine = { lib, ... }: {
    imports = [ ./common/user-account.nix ];
    services.xserver.enable = true;
    services.xserver.displayManager.sddm.enable = true;
    services.xserver.windowManager.default = "icewm";
    services.xserver.windowManager.icewm.enable = true;
    services.xserver.desktopManager.default = "none";
  };

  enableOCR = true;

  testScript = { nodes, ... }: let
    user = nodes.machine.config.users.extraUsers.alice;
  in ''
    startAll;
    $machine->waitForText(qr/ALICE/);
    $machine->screenshot("sddm");
    $machine->sendChars("${user.password}\n");
    $machine->waitForFile("/home/alice/.Xauthority");
    $machine->succeed("xauth merge ~alice/.Xauthority");
    $machine->waitForWindow("^IceWM ");
  '';
})
```

Save this to a file named `sddm-manual.nix` in `nixos/tests/` (next to the existing `sddm.nix` test), and execute it:

```
$ nix-build ./sddm-manual.nix
```

You'll see the QtQuick errors spewed many times before giving up.  Note that this test is a bit weak due to its OCR usage and in particular the hardcoding of 'ALICE' in caps due to the default slim theme.

LMK if you have any trouble reproducing this.

(PS: **WOW** these NixOS tests are powerful and amazing!! Haha GJ all involved :heart:)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by dtzWill** [comment]
cc @abradar @ttuegel (SDDM maintainers, and recent SDDM/plasma activity that seems related)

**Comment by grahamc** [comment]
Marked as a blocker by request to ensure it is triaged in time.

**Comment by ttuegel** [comment]
I was (trying) to bisect this on master just now. I wasn't having any success, because master is totally broken right now. Perhaps I will have more luck on release-17.03.

Thanks for writing this test; it seems much better than the one we have now.

**Comment by ttuegel** [comment]
@dtzWill Your test never completes on my machine. Is there anything we can do to speed it up?

**Comment by ttuegel** [comment]
Oh, that's my mistake. The indicated "good" commit is in fact bad, but for another reason.

**Comment by dtzWill** [comment]
@ttuegel it should complete on c458d7cf94ebe181665511a7daaa3cb337a04bc4, does it not?

On current master/17.03 it does not complete, I didn't make it fail particularly gracefully -- it'll just look forever for SDDM to start (which it doesn't due to the QtQuick errors).

If you've fixed those errors, it's possible the OCR isn't matching the theme used on newer nixpkgs.  You can check this by [running the test manually](https://nixos.org/nixos/manual/#sec-running-nixos-tests).

**Comment by dtzWill** [comment]
Looks like the test should actually finish after 900 times of (*check OCR* + 1 second sleep), which means at least 15 minutes (which I certainly didn't wait for :innocent:).  If you're doing a bisect this does seem much to slow, it'd probably be worth putting together a fast-fail test that checks for the QtQuick error or something.  Would that be useful? (Also, are you on IRC? :))

**Comment by ttuegel** [comment]
> Looks like the test should actually finish after 900 times of ('check OCR' + 1 second sleep), which means at least 15 minutes (which I certainly didn't wait for 😇).

I don't have the fastest test machine, but it was over 40 minutes. It is fixed on the release branch now. I am pushing it to master with your improved test after I check if this also fixes the Plasma test failure. If you wanted to make a PR to master for a faster-failing test, that would be most welcome!

**Comment by dtzWill** [comment]
Oh wow that seems wrong.  This is my first NixOS test (mostly looked to the lightdm test for inspiration) so I apologize if it does something silly that resulted in wasting your time.

Anyway, thanks for looking into this and for the fix! I'll confirm shortly.

**Comment by dtzWill** [comment]
Err, nevermind.  It doesn't seem to evaluate for me currently? It's not your change.  Lemme cherry-pick your fix over to a different branch ...

**Comment by dtzWill** [comment]
I cherry-picked 056db1c725be6d9db031dcc420c41cc30b36028b onto nixos-17.03-small (b1097b9cb3ab040badf526e9d15cfe798442d910) and ... it works! :+1:

**Comment by ttuegel** [comment]
> Oh wow that seems wrong. This is my first NixOS test (mostly looked to the lightdm test for inspiration) so I apologize if it does something silly that resulted in wasting your time.

It's no problem! I was actually very confused because on Hydra, the tests have a very constraining timeout window. I guess that doesn't apply if you run the tests locally? I couldn't find out how the timeouts are implemented...

In any case, this was actually unrelated to the Plasma problem in master, but this fix is in master and release now.

**Comment by globin** [comment]
Test actually completes in 22 secs here:
```
nix-build sddm-test.nix --check  1.06s user 0.11s system 5% cpu 22.853 total
```

**Comment by ttuegel** [comment]
Is that for the failing case, though? It is quite fast when it succeeds.

**Comment by dtzWill** [comment]
(FWIW now that release-17.03 evaluation has been fixed, I tested that and as expected works as well)

**Comment by globin** [comment]
Ah yeah failing test cases sadly always take 15 minutes to time out..
