### ISSUE TITLE
Package request: JDownloader2

### ISSUE THREAD

**Issue by Froztmuffins** [NixOS/nixpkgs#242408]
**Project description**
Download manager, written in Java, for one-click hosting sites like Rapidshare and Megaupload. Uses its own updater.

**Metadata**

* homepage URL:https://jdownloader.org/jdownloader2
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by Shawn8901** [comment]
Seems to be a duplicate of #41321
