### ISSUE TITLE
Package request: Komorebi

### ISSUE THREAD

**Issue by Froztmuffins** [NixOS/nixpkgs#242410]
**Project description**
Komorebi is an awesome animated wallpapers manager for all Linux platforms

Komorebi is an awesome animated wallpapers manager for all Linux platforms
**Metadata**

* homepage URL:
* source URL:https://github.com/cheesecakeufo/komorebi
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by kaleocheng** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/190814
