### ISSUE TITLE
Package request: Portmaster

### ISSUE THREAD

**Issue by Froztmuffins** [NixOS/nixpkgs#242409]
**Project description**
Portmaster is a free and open-source application firewall that does the heavy lifting for you. Restore privacy and take back control over all your computer's network activity.

**Metadata**

* homepage URL:https://safing.io/
* source URL:https://github.com/safing/portmaster
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by dit7ya** [comment]
https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+portmaster&type=issues

**Comment by figsoda** [comment]
duplicate of #174194
