### ISSUE TITLE
Unable to upgrade packages on ubuntu 16.04

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#24242]
## Issue description

I am running Ubuntu 16.04 + nixpkgs. When I run 

`nix-env -u -b`

I am seeing an assertion from a darwin package.

<pre>
~$ nix-env -u -b --show-trace
error: while trying to find an upgrade for ‘emacs-25.1’:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘emacs-25.1-mac-6.1’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/applications/editors/emacs/macport.nix:8:3:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘apple-framework-AppKit’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:66:5:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘apple-framework-AudioToolbox’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:66:5:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘apple-framework-AudioUnit’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:66:5:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘apple-framework-Carbon’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:66:5:
while evaluating the attribute ‘propagatedNativeBuildInputs’ of the derivation ‘apple-framework-ApplicationServices’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-sdk/default.nix:66:5:
while evaluating ‘getOutput’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/lib/attrsets.nix:453:23, called from undefined position:
while evaluating ‘getCrossDrv’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/stdenv/generic/default.nix:133:21, called from undefined position:
while evaluating the attribute ‘CF’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-source-releases/default.nix:192:5:
while evaluating ‘callPackageWith’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/lib/customisation.nix:95:35, called from /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-source-releases/default.nix:192:23:
while evaluating ‘makeOverridable’ at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/lib/customisation.nix:54:24, called from /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/lib/customisation.nix:99:8:
while evaluating anonymous function at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-source-releases/CF/default.nix:1:1, called from /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/lib/customisation.nix:56:12:
assertion failed at /nix/store/59jwrj96v84l74psgr3pqc8si6yx6l84-nixpkgs-17.09pre104029.fff8cc7/nixpkgs/pkgs/os-specific/darwin/apple-source-releases/CF/default.nix:4:1
</pre>

### Steps to reproduce

Run `nix-env -u -b`.  I can provide the list of packages I am using if the above trace does not provide enough information.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.7

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre104029.fff8cc7"

**Comment by vcunat** [comment]
This is triggered by you setting `allowBroken = true` &ndash; bad `meta.platforms` is one way for packages to be considered broken.

Our "macport" version of emacs has name `emacs` and version `25.1-mac-6.1`, and that's a rather fragile setup by itself.  /cc maintainer @jwiegley.  Suggestion: if regular emacs doesn't make sense on Darwin, re-use the same attribute; otherwise use a different name, e.g. `emacs-mac`.

**Comment by vmandela** [comment]
setting `allowBroken = false` fixed my issue. thank you.
