### ISSUE TITLE
Update request: libplacebo 5.264.1 → 6.338.1

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#242503]
- Package name: [libplacebo](https://code.videolan.org/videolan/libplacebo)
- Latest released version: [6.338.1](https://code.videolan.org/videolan/libplacebo/-/tags/v6.338.1)

- Current version on the unstable channel: [5.264.1](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/libplacebo/default.nix#L64)
- Current version on the stable/release channel: [5.264.1](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/libplacebo/default.nix#L64)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@tadeokondrak
@Kranzes 

-----
Note for maintainers: Please tag this issue in your PR.

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/243134

**Comment by arthsmn** [comment]
Done here: https://github.com/NixOS/nixpkgs/pull/269415.
