### ISSUE TITLE
Update request: obs-studio 29.0.2 → 29.1

### ISSUE THREAD

**Issue by Dekomoro** [NixOS/nixpkgs#242636]
- Package name: obs-studio
- Latest released version: 29.1
- Current version on the unstable channel: 29.0.2
- Current version on the stable/release channel: 29.0.2
- [*] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jb55 
@MP2E 
@miangraham 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by CutestNekoAqua** [comment]
lets update this to 29.1.3 instead?

**Comment by CutestNekoAqua** [comment]
feel welcome to review / test the PR :)

**Comment by cole-h** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/242814.
