### ISSUE TITLE
Package request: esbuild

### ISSUE THREAD

**Issue by eduronqui** [NixOS/nixpkgs#242648]
**Project description**

esbuild: An extremely fast bundler for the web

**Metadata**

* homepage URL: https://esbuild.github.io
* source URL: https://github.com/evanw/esbuild
* license: MIT
* platforms: all (node npm package)

**Comment by marsam** [comment]
esbuild is already available on nixpkgs https://search.nixos.org/packages?channel=23.05&show=esbuild&sort=alpha_asc&type=packages&query=esbuild
