### ISSUE TITLE
fluidsynth: CMake config broken

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#242623]
### Describe the bug
Adding a `dev` output to `fluidsynth` in #226253 (CC @trofi) broke its `export()`-generated CMake config.

```
CMake Error at /nix/store/m9w00irsx5f1lc0fqm0mgvl73ww9d1da-fluidsynth-2.3.2-dev/lib/cmake/fluidsynth/FluidSynthTargets.cmake:94 (message):
  The imported target "FluidSynth::libfluidsynth" references the file

     "/nix/store/m9w00irsx5f1lc0fqm0mgvl73ww9d1da-fluidsynth-2.3.2-dev/lib/libfluidsynth.so.3.2.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/nix/store/m9w00irsx5f1lc0fqm0mgvl73ww9d1da-fluidsynth-2.3.2-dev/lib/cmake/fluidsynth/FluidSynthTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /nix/store/m9w00irsx5f1lc0fqm0mgvl73ww9d1da-fluidsynth-2.3.2-dev/lib/cmake/fluidsynth/FluidSynthConfig.cmake:148 (include)
  builds/cmake/Modules/PlayerFindPackage.cmake:54 (find_package)
  CMakeLists.txt:1010 (player_find_package)
```

The generated CMake code in `FluidSynthTargets.cmake` determines an import prefix relative to the location of the the file.
```cmake
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()
```

And then proceeds to append the expected library location to that prefix in `FluidSynthTargets-release.cmake` when it prepares the corresponding CMake target.
```cmake
# Import target "FluidSynth::libfluidsynth" for configuration "Release"
set_property(TARGET FluidSynth::libfluidsynth APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FluidSynth::libfluidsynth PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libfluidsynth.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libfluidsynth.so.3"
  )
```

### Steps To Reproduce
1. Build something that uses `fluidsynth`'s CMake config (I've noticed it while bumping `easyrpg-player` and trying to add `fluidsynth` to its `buildInputs`)
2. Observe error

### Expected behavior
The config should have a valid path and using it should work fine.

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers

@cillianderoiste 
@lovek323 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.30-xanmod1, NixOS, 23.05 (Stoat), 23.05.419.3a70dd92993`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(bt1cn): `"unstable"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trofi** [comment]
Let's revert it for now as https://github.com/NixOS/nixpkgs/pull/242635 and check the details meanwhile.

**Comment by OPNA2608** [comment]
I can submit a proper fix.

[The code responsible for generating that CMake code](https://github.com/Kitware/CMake/blob/5709a7e572df220655659155d26b2f56cb97acf3/Source/cmExportInstallFileGenerator.cxx#L198-L254) is capable of hardcoding the used `CMAKE_INSTALL_PREFIX` instead of walking up the tree from `CMAKE_CURRENT_LIST_FILE`, but only if the export target gets installed to an absolute `DESTINATION`.

[The code that installs the export](https://github.com/FluidSynth/fluidsynth/blob/a85aa9811ca511809964fd55f692120baa362640/src/CMakeLists.txt#L527-L531) uses `DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/fluidsynth`.

And `CMAKE_INSTALL_LIBDIR` isn't absolute in `fluidsynth` anymore because of this workaround:
https://github.com/NixOS/nixpkgs/blob/e423abb13680d9f3671f20ceef9e849981972b9e/pkgs/applications/audio/fluidsynth/default.nix#L27-L28

Which works around [a bad `${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}` concatenation](https://github.com/FluidSynth/fluidsynth/blob/a85aa9811ca511809964fd55f692120baa362640/CMakeLists.txt#L393-L396) in `fluidsynth`.

---

If we instead do
```nix
postPatch = ''
  substituteInPlace CMakeLists.txt \
    --replace "\''${CMAKE_INSTALL_PREFIX}/\''${CMAKE_INSTALL_LIBDIR}" "\''${CMAKE_INSTALL_FULL_LIBDIR}"
'';
```

(or even better, submit this fix upstream and `fetchpatch` it), then we should be good.
