### ISSUE TITLE
Package request: lenovo-legion

### ISSUE THREAD

**Issue by realsnick** [NixOS/nixpkgs#242668]
The package seems to exist
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/lenovo-legion/app.nix

but when i try to `nix-shell -p lenovo-legion` i get `undefined variable`

![image](https://github.com/NixOS/nixpkgs/assets/1440852/2bb7b12f-e403-489b-8e7c-bdb9f3af0df7)

**Comment by pinn3** [comment]
It does indeed exist in the unstable channel as you pointed out with the link. However by the look of the paths in your output, it seems like you're using the stable 23.05 channel. This one does not include the package
