### ISSUE TITLE
Stale mailman lock files not cleared on reboot

### ISSUE THREAD

**Issue by sysvinit** [NixOS/nixpkgs#242650]
### Describe the bug

Mailman uses lock files to manage concurrency, and the NixOS module configures mailman to store these lock files under `/var/lib/mailman/lock`, which I presume is intended to be a path backed by persistent storage. However, this means that if the host machine shuts down unexpectedly without stopping mailman correctly, then mailman will fail to start during the next boot due to stale lock files. (In this context, an unexpected shutdown could be e.g. power loss, or a fault with an underlying hypervisor, etc.)

These lock files only stay valid as long as the machine is running, and when it's next rebooted this state should be cleared.

### Steps To Reproduce
1. Enable and configure the mailman module on a test host.
2. Shut down the host abnormally without using the regular shutdown process.
3. Restart the test host.
4. The mailman service should fail to start, printing an error in the system journal about to stale locks.

### Expected behavior
The mailman service should recover gracefully from unexpected/unclean machine restarts where possible; ephemeral locking state should be discarded when it becomes invalid.

### Additional context
On the mailman host where we've observed this problem, I've worked around this issue by setting `services.mailman.settings."paths_fhs".lock_dir = lib.mkForce "/run/mailman";` to force the locks to be stored on a tmpfs, and `systemd.services.mailman.runtimeConfig.RuntimeDirectoryPreserve = "yes"` to ensure that the locks are not deleted by systemd (during a single boot of the system).

It might also be possible to work around this using `systemd-tmpfiles` to clear out `/var/lib/mailman/lock` on first boot, but I haven't investigated this option.

We've observed this problem on a 22.11 host, however the lock directory configuration for the mailman module is the same in 23.05 and unstable.

### Notify maintainers

@alyssais  @Ma27 @lheckemann 

### Metadata

```console
molly@[mailman host] ~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.118, NixOS, 22.11 (Raccoon), 22.11.2583.3654c4e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by bjornfor** [comment]
If the locks are only for the service itself (meaning there's no use in having the locks when the service is stopped), another option could be to remove the lock files with ExecStartPre=.

**Comment by alyssais** [comment]
Want to send a PR to put them in /run?  Test coverage in the Mailman test would also be appreciated.
