### ISSUE TITLE
Package request: llama-cpp-python

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#242792]
## **Project description**

Simple Python bindings for @ggerganov's llama.cpp library. This package provides:

-   Low-level access to C API via ctypes interface.
-   High-level Python API for text completion
    -   OpenAI-like API
    -   LangChain compatibility

## **Metadata**

* homepage URL: https://llama-cpp-python.readthedocs.io
* source URL: https://github.com/abetlen/llama-cpp-python
* license: mit
* platforms: unix, linux, darwin, ...

## Related:

<https://github.com/NixOS/nixpkgs/issues/224921>

**Comment by mausch** [comment]
I doubt llama-cpp-python will be interested in maintaining its own flake?
But we can just put the flake anywhere of course :slightly_smiling_face: 
https://gist.github.com/mausch/f525326eb70528f04b626fb9e01fcb58
Just need https://github.com/NixOS/nixpkgs/pull/244564 to build the OpenAI-compatible server.

**Comment by hoh** [comment]
It's been almost a year since this issue was open and `llama-cpp` is now well in `nixpkgs`. 

Would it now make sense to reconsider adding `llama-cpp-python` into `nixpkgs` ?
