### ISSUE TITLE
switch-to-configuration tries to stop .mount units and fails

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#242737]
### Describe the bug
The `switch-to-configuration` script is apparently trying to stop and start
changed .mount units, presumably to cause a `remount`?
If that happens the script fails and the new configuration is not activated.
Worse, the system is left in a broken state with some of the stopped (as part
of the switch) units never restarted.

### Steps To Reproduce
1. change the value of `fileSystems."/".fsType`, for example from `ext4` to `auto`.
2. run `nixos-rebuild test`

### Expected behavior
The unit should probably not be stopped and the switch should succeed.

### Screenshots
```
# nixos-rebuild switch
stopping the following units: -.mount
warning: error(s) occurred while switching to the new configuration
```
If using `--target-host` remotely also the SSH connection drops.

### Additional context

NixOS version: 23.05.1194.b6c73c5fe53 (Stoat)

The filesystem entry is:
```
  fileSystems."/" =
    { device = "/dev/main/nixos";
      fsType = "ext4";
    };
```

### Notify maintainers

@dasJ 

cc: @Artturin

**Comment by billksun** [comment]
I just ran into this error myself. I am unsure of which configuration change caused this. But I was changing `networking` config and I think `nixos-rebuild` was saying some setting conflicts with my `stateVersion`, which was at `20.09`. So I updated to `23.05` and then `nixos-rebuild switch` flashed me this error:

```
Failed to stop -.mount: Job type stop is not applicable for unit -.mount 
```

 before giving me a black screen and send me to the login prompt.

**Comment by billksun** [comment]
@rnhmjoj were you ever able to fix your issue?

**Comment by rnhmjoj** [comment]
No fix, I'm pretty sure changing the unit will trigger a stop.

**Comment by dasJ** [comment]
Unfortunately, you are correct. I do have a fix in the pipeline though.
#250316 improves the handling of mount units (`systemd.units.mounts`) and I plan to adapt this to fstab mounts as well (`fileSystems`). This is currently being blocked by the fstab parser not having any tests but I plan on writing them. Will keep this issue in mind.

**Comment by dasJ** [comment]
Now that I look at the code again… it already looks correct. Can someone with this issue post a diff of their fstab?
Something like `diff -u /nix/var/nix/profiles/system-$(n - 1)-link/etc/fstab /etc/fstab` should do.
