### ISSUE TITLE
Package request: https://github.com/kjuulh/tree-sitter-hurl

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#242805]
**Project description**

I contribute to https://github.com/rest-nvim/rest.nvim and I would like to test if I can interface the plugin with hurl as well.
I haven't tested but the grammar seems to be useful and hurl's upstream is interested in having a grammar so eventually we will get a tree-sitter hurl grammar (and when that time comes, we can just swap upstreams).

**Metadata**

* homepage URL: https://github.com/kjuulh/tree-sitter-hurl
* source URL: https://github.com/kjuulh/tree-sitter-hurl
* license: mit 
* platforms: unix

**Comment by figsoda** [comment]
It was added to nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/pull/5065 and #242856 is adding it to nixpkgs with the nvim-treesitter update

**Comment by teto** [comment]
thanks
