### ISSUE TITLE
Wrap mold inside script so dynamic linking works

### ISSUE THREAD

**Issue by gotlougit** [NixOS/nixpkgs#242816]
[mold](https://github.com/rui314/mold) is a fast and multi threaded modern linker. We already have it in Nixpkgs, however, unlike `lld`, it has not been wrapped in a package so that it can find the libraries to dynamically link against. Hence, dynamic linking in `mold` in NixOS fails.

This issue is created so that we can wrap mold inside a shell script, like what happens to `lld` when it is installed through `llvmPackages.bintools` or even normal `ld`. I would be open to helping port such a script for `mold`.

**Comment by gotlougit** [comment]
After some discussion on Matrix (thanks @K900 !), I was able to get mold working in a dev shell by using the following snippet:
```nix
let
  mkShell = pkgs.mkShell.override { stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv; };
in mkShell { ... }
```

Is there any way we can just expose this as a wrapped mold in Nixpkgs so we don't have to add this to every shell we need mold in?

**Comment by paveloom** [comment]
Is this relevant anymore? In addition to `useMoldLinker,` we also have `mold-wrapped` now.

**Comment by Artturin** [comment]
Further work is to rename `mold` to `mold-unwrapped` so users have to choose explicitly
