### ISSUE TITLE
stage-1-init.sh/luksroot.nix: LUKS-encrypted LVM-LVs not working (LUKS on top of LVM)

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#24289]
## Issue description

Normally having a LUKS-encrypted LVM logical volume should work by setting `preLVM = false;`. The `preLVM` option does work properly by executing the `cryptsetup luksOpen ...` command in the correct phase:
```nix
    boot.initrd.preLVMCommands = concatStrings (mapAttrsToList openCommand preLVM);
    boot.initrd.postDeviceCommands = concatStrings (mapAttrsToList openCommand postLVM);
```
https://github.com/NixOS/nixpkgs/blob/release-17.03/nixos/modules/system/boot/luksroot.nix#L466

However the [`lvm vgchange -ay`](https://github.com/NixOS/nixpkgs/blob/d496f23df0f9573873221887bcc87b668d31353f/nixos/modules/system/boot/stage-1-init.sh#L182) command doesn't seem to actually activate the the logical volumes (at least on my system (Dell XPS 13)) for some reason (it seems like my SSD is actually only recognized after all `postDeviceCommands`). If I add the `cryptsetup luksOpen ...` command to `postMountCommands` everything works as expected.

I also noticed that there is not test for this case. Can we add one to this file: [nixos/tests/partition.nix](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/tests/partition.nix)?

### Steps to reproduce

Verifying this with a NixOS test would probably be the best idea. Reproducing this manually is a bit annoying but with an existing LVM setup it shouldn't be that difficult.

An example:
```bash
lvcreate --name <name> --size 1G lv_test <volume-group>
```
```nix
boot.initrd.luks.devices."crypt-test" = {
  preLVM = false;
  device = "/dev/mapper/<volume-group>-lv_test"; # etc., or:
  #device = "/dev/disk/by-uuid/<UUID>";
```
```bash
reboot
```

## Technical details

* System: (NixOS: `17.03beta675.3a368d7 (Gorilla)`)

**Comment by poelzi** [comment]
I have the same problem. I have one generation hat actually worked, but have problems reproducing it.

**Comment by primeos** [comment]
IIRC shortly after creating this issue I dropped that setup and encrypted the whole VG (instead of only certain LVs) which worked without any issues.

I'll close this issue because I don't know if this problem still exists and I don't have time (/ enough interest) to do something about it (sorry).
(But I can re-open it if someone is willing to work on it.)
