### ISSUE TITLE
Provide ghcHEAD which is actually closer to HEAD

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#2428]
Currently the ghcHEAD package is from March and over a month old package can hardly be called HEAD. It's older than the latest stable release!

I'm currently looking for a place where a source tarball for newer version but I thought I'd open up an issue in case someone has one already.

Honestly, the package should pull from git but I don't think nix is able to do that at the moment: we need to know the exact version and SHA ahead of time, right?

**Comment by peti** [comment]
We have a bleeding edge HEAD compiler these days.

**Comment by Fuuzetsu** [comment]
Can you expand on this? Do you mean that currently in nixpkgs with have recent HEAD or that we have a system which can track HEAD more closely than we could in the past?

**Comment by peti** [comment]
We currently have a very recent HEAD snapshot, but no system that updates the expression automatically.
