### ISSUE TITLE
Update request: microsoft-edge 113.0.1774.50 → 114.0.1823.79

### ISSUE THREAD

**Issue by akr2002** [NixOS/nixpkgs#242884]
- Package name: microsoft-edge
- Latest released version: 114.0.1823.79

- Current version on the unstable channel: 113.0.1774.50
- Current version on the stable/release channel: 111.0.1661.44

- [ *] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

[Azure Zanculmarktum](https://github.com/zanculmarktum) 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/242891
