### ISSUE TITLE
Package request: Universal Android Debloater

### ISSUE THREAD

**Issue by shreyanparajuli** [NixOS/nixpkgs#242847]
**Project description**

Cross-platform GUI written in Rust using ADB to debloat non-rooted android devices. Improve your privacy, the security and battery life of your device.

**Metadata**

* homepage URL:
* source URL: https://github.com/0x192/universal-android-debloater
* license: gpl-3.0
* platforms: linux, darwin

**Comment by imincik** [comment]
This is duplicate to https://github.com/NixOS/nixpkgs/issues/199619
