### ISSUE TITLE
Get IntelliJ Idea suite of programs running on Darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24296]
Currently our expressions all throw if you're not on Linux, but the underlying programs work fine on Darwin. Our Nix expressions should too!

**Comment by cbarrett** [comment]
I'm an Android Studio user, it'd be great to get this from Nix instead of updating it manually. Assign it to me and I'll take a look at hacking on it over the next few weeks. :)

**Comment by copumpkin** [comment]
Thanks! I don't think I can assign it to you if you're not a member of the NixOS organization, but anyone reading this will know you're doing it 😄

**Comment by Artturin** [comment]
fixed in 01f0c10ba229f281dcf7caa6e4cbaaade97f0197
