### ISSUE TITLE
SDDM  can not find QtQuick module

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#24290]
## Issue description

After system upgrade SDDM do not show interface, there is just black screen with white cursor. LightDM works properly.

In journalctl a lot of errors like this:

'мар 24 17:36:54 ASUS sddm-greeter[1022]: qrc:/theme/Main.qml:26:1: module "QtQuick" is not installed
мар 24 17:36:54 ASUS sddm-greeter[1022]: Fallback to embedded theme'

### Steps to reproduce

Put in configuration.nix: 'services.xserver.displayManager.sddm.enable = true;'
Upgrade system via 'nixos-rebuild switch --upgrade'

## Technical details

* System: 17.03beta667.6b9a2f6 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03beta667.6b9a2f6"

**Comment by globin** [comment]
This is fixed on master and the release branch, may not be in the channel yet.

**Comment by bachp** [comment]
@globin Do you know what commit this was fixed? I'm seeing this error again on master: f1b45f7d4136a04526d5b4ab09664e1dc005d38d

And I think the same happened on [hydra](https://hydra.nixos.org/build/56404757).
