### ISSUE TITLE
Update request: wayland-protocols 1.31 → 1.32

### ISSUE THREAD

**Issue by Lord-Valen** [NixOS/nixpkgs#243090]
- Package name: wayland-protocols
- Latest released version: 1.32

- Current version on the unstable channel: 1.31
- Current version on the stable/release channel: 1.31

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@primeos

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by eclairevoyant** [comment]
fixed in #243095
