### ISSUE TITLE
Suggestion of change to lib/maintainers.nix

### ISSUE THREAD

**Issue by crocket** [NixOS/nixpkgs#24309]
It currently accepts only real names with email addresses.

I propose two things.

* maintainers.nix should allow well-known pseudonyms.
  * I believe most people have reasons to avoid revealing their real government identity.
  * I feel really uncomfortable with revealing my real name online. My real name is a weakness that can be utilized by bad actors(hackers) or stalkers(Think about ex-boy friend). I don't want my real name to be floating on the public internet.
  * There are plenty of ways to stop bad actors without knowing their real names. They are going to use fake names anyway, though.
  * You can vet maintainers in pull requests without knowing their real names. Well-known pseudonyms are ok. Also, there is little or no danger of spamming.
* Other convenient communication channels than email should be allowed
  * Some people want to avoid exposing their email addresses on the public internet. Spammers will invariably scan lib/maintainers.nix.
  * For example, a github issue tracker dedicated to package maintenance could be used. Each gentoo overlay is associated with a github repository.

Those two things are important for online hygiene.
Or, it should be possible to submit a package without listing me as a designated maintainer.
If email has to be provided, it should be hidden from the general public and only accessible by a few moderators.

**Comment by vcunat** [comment]
It *is* common to submit a package without listing any maintainer, and I think one could even get push access without being listed in `lib/maintainers.nix`.

`meta.maintainers` field doesn't mean much in reality &ndash; it's mainly a contact &ndash; for the build farm to notify about changes in build status and for people interested e.g. in doing a larger change in the maintained package.

**Comment by crocket** [comment]
So, the community policy is that people don't have to specify the maintainer field. Void Linux doesn't allow people from omitting the maintainer field. This is good. I've almost completely bought into NixOS. I'll definitely prepare to migrate from ArchLinux to NixOS within this year.

Do you think this issue is solved? If you think so, please close it.

**Comment by vcunat** [comment]
If the (main) point is ability to submit packages without claiming some real identity, I do consider it "solved".

**Comment by vcunat** [comment]
I'd say the community is unusually liberal, especially w.r.t. "hard rules".

**Comment by 7c6f434c** [comment]
I would say that `lib/maintainers.nix` does contain a few violations of the policy. Furthermore, if you format a pseudonym so that it looks like it could be a real name, it would be extremely rude to do any verification or even to ask too many questions.

As for email — I dunno, maybe it is a good idea to keep a whitelist of reasonable non-spam markers for filters. I mean, Hydra emails are generated in a very specific (and relatively stable) format. I guess the current norm for asking about major changes is a GitHub mention anyway.

**Comment by 8573** [comment]
[Nixpkgs manual section 12.2] requires new packages to have
maintainers (or, more precisely, requires PR reviewers to require new
packages to have maintainers). Will this stipulation be removed to
reflect actual practice?

[Nixpkgs manual section 12.2]: <https://nixos.org/nixpkgs/manual/#idm140737317581056>

**Comment by vcunat** [comment]
Well, the *must* word there feels a bit strong to me.  Of course it would be best if every package had at least one maintainer... but if I'm put before the choice, I'd rather push the package without one, as it may work well for years without being touched.

**Comment by crocket** [comment]
`must` should be removed. People should have freedom to not expose their email addresses on the public internet. They should have a choice to protect themselves from spammers.
