### ISSUE TITLE
SOLR version is way out of date

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#24306]
Both nixpkgs 17.03 and master feature SOLR 4.10.3. This version was released in 2014. It would be nice to provide a newer version. The current version at ticket creation time is 6.4.2.

**Comment by ericsagnes** [comment]
cc maintainers @rickynils @domenkozar 

For what it is worth, I have a nix expression for solr 6.5.1 [here](https://gist.github.com/ericsagnes/a28aab3c3f9ccdb80f4fe2158689464a), it is working ok if the required env vars are set correctly (`SOLR_LOGS_DIR`, `SOLR_PID_DIR`, `SOLR_HOME`, ...).

The problem being to upgrade the nixos module, as solr configuration is using many files and directories that make it nontrivial to abstract in a clean way.

**Comment by ckauhaus** [comment]
Not me, but I'd love to see it integrated :)

**Comment by tomberek** [comment]
(triage) still on 4.10.3, either bump or close.

**Comment by ckauhaus** [comment]
We should at least remove the "first bug" label as this it not as trivial as it might seem on first glance.

**Comment by ckauhaus** [comment]
Would still be happy to see action here. Unfortunately I'm not deep enough into SOLR to do it by myself.

**Comment by aanderse** [comment]
@ckauhaus Solved by https://github.com/NixOS/nixpkgs/pull/49283.
