### ISSUE TITLE
nftables service cannot be restarted due to checkscript

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#24318]
## Issue description

When disabling the standard firewall, enabling `nftables` and rebuilding you get this error:

```
Mar 25 14:13:28 aaa systemd[1]: Starting nftables firewall...
Mar 25 14:13:28 aaa zzsj0icb2fam0z873ysn9aqwycs89i45-nftables-check[3800]: Unload ip_tables before using nftables!
Mar 25 14:13:28 aaa systemd[1]: nftables.service: Main process exited, code=exited, status=1/FAILURE
```

I thought maybe I need to reboot. So I rebooted, and checked the status of the service:

```
$ sudo systemctl status nftables
● nftables.service - nftables firewall
   Loaded: loaded (/nix/store/9mp8sip91shc3vv4dnlss26jmljaln9v-unit-nftables.service/nftables.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2017-03-25 14:25:47 CET; 13s ago
  Process: 703 ExecStart=/nix/store/zzsj0icb2fam0z873ysn9aqwycs89i45-nftables-check (code=exited, status=0/SUCCESS)
 Main PID: 703 (code=exited, status=0/SUCCESS)
```

It is started, however when I try to restart it I get this error:

```
$ sudo systemctl restart nftables
Job for nftables.service failed because the control process exited with error code.
See "systemctl status nftables.service" and "journalctl -xe" for details.

$ sudo systemctl status nftables
● nftables.service - nftables firewall
   Loaded: loaded (/nix/store/9mp8sip91shc3vv4dnlss26jmljaln9v-unit-nftables.service/nftables.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-03-25 14:26:04 CET; 961ms ago
  Process: 1526 ExecStop=/nix/store/ahi094q2ylp1j3afapim2x49frsbvj5r-nftables-0.7/bin/nft flush ruleset (code=exited, status=0/SUCCESS)
  Process: 1535 ExecStart=/nix/store/zzsj0icb2fam0z873ysn9aqwycs89i45-nftables-check (code=exited, status=1/FAILURE)
 Main PID: 1535 (code=exited, status=1/FAILURE)
      CPU: 14ms

Mar 25 14:26:04 aaa systemd[1]: Starting nftables firewall...
Mar 25 14:26:04 aaa zzsj0icb2fam0z873ysn9aqwycs89i45-nftables-check[1535]: Unload ip_tables before using nftables!
Mar 25 14:26:04 aaa systemd[1]: nftables.service: Main process exited, code=exited, status=1/FAILURE
Mar 25 14:26:04 aaa systemd[1]: Failed to start nftables firewall.
Mar 25 14:26:04 aaa systemd[1]: nftables.service: Unit entered failed state.
Mar 25 14:26:04 aaa systemd[1]: nftables.service: Failed with result 'exit-code'.
```

This also happens when you make changes to nftables and run `nixos-rebuild switch`.
Which forces you to reboot everytime you make changes to the ruleset.

## Steps to reproduce

1. Add the following to your `configuration.nix`:

   ```
   networking.firewall.enable = false;

   networking.nftables = {
     enable  = true;
     ruleset = ''
       table ip filter {
         chain input {
           type filter hook input priority 0;
           policy drop;

           iifname lo accept;

           ct state {established, related} accept;
         }

         chain output {
           type filter hook output priority 0;
           policy accept;
         }

         chain forward {
           type filter hook forward priority 0;
           policy accept;
         }
       }
     '';
   };
   ```

2. Run `sudo nixos-rebuild switch`
3. You should see the service failure
4. Reboot
5. Make changes to your nftables ruleset
6. Run `sudo nixos-rebuild switch`
7. You should see the service failure

## Environment

```
$ nixos-version
17.03beta685.1dbb962 (Gorilla)
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-17.03
```

## What I have tried so far

I tried unloading the `ip_tables` module, but I couldn't do that:

```
$ sudo modprobe -r ip_tables
modprobe: FATAL: Module ip_tables is in use.
```

I checked that the blacklisting actually is there:

```
$ nixos-option boot.blacklistedKernelModules
Value:
[ "usblp" "ip_tables" "nouveau" "nvidiafb" ]
```

I checked that the modprobe config actually contains the module:

```
$ cat /etc/modprobe.d/nixos.conf | grep ip_tables
blacklist ip_tables
```

I checked dmesg for information about the module. Seems like it is not allowed
to be loaded, but then it is loaded anyway:

```
$ dmesg | grep ip_tables
[    3.833365] systemd[1]: Module 'ip_tables' is blacklisted
[   10.286336] ip_tables: (C) 2000-2006 Netfilter Core Team
```

I checked `lsmod` for information about modules loaded in relation to
`ip_tables`:

```
$ lsmod | grep ip_tables
ip_tables              24576  2 iptable_filter,iptable_nat
x_tables               28672  5 ip_tables,iptable_filter,ipt_MASQUERADE,xt_addrtype,xt_conntrack
```

I checked module information of `ip_tables`:

```
$ modinfo ip_tables
filename:       /run/current-system/kernel-modules/lib/modules/4.9.17/kernel/net/ipv4/netfilter/ip_tables.ko.xz
description:    IPv4 packet filter
author:         Netfilter Core Team <coreteam@netfilter.org>
license:        GPL
depends:        x_tables
intree:         Y
vermagic:       4.9.17 SMP mod_unload
```

I checked module information of `x_tables`:

```
$ modinfo x_tables
filename:       /run/current-system/kernel-modules/lib/modules/4.9.17/kernel/net/netfilter/x_tables.ko.xz
description:    {ip,ip6,arp,eb}_tables backend module
author:         Harald Welte <laforge@netfilter.org>
license:        GPL
depends:
intree:         Y
vermagic:       4.9.17 SMP mod_unload
```

cc @Jookia @Mic92

Please let me know if I can provide anymore information!

**Comment by rzetterberg** [comment]
Ok, I have found the culpit that loads the `ip_tables` module again.

It's **Docker**. 

Apparently when Docker is started it loads the `ip_tables` and then sets up NAT:ing using it.

Since [Docker does not have nftables support](https://github.com/docker/docker/issues/26824) your only option to use both nftables and Docker is to start Docker without iptables and setup NAT:ing manually in nftables.

I had this set in my `configuration.nix` before:

```
    virtualisation.docker = {
      enable        = true;
      storageDriver = "overlay";
    };
```

To disable iptables I changed it to this:

```diff
     virtualisation.docker = {
       enable        = true;
       storageDriver = "overlay";
+      extraOptions  = "--iptables=False";
     };
```

After rebuilding and rebooting the problem I was having was gone:

```
$ lsmod | grep _tables
nf_tables_ipv4         16384  4
nf_tables              69632  11 nft_ct,nft_set_hash,nf_tables_ipv4,nft_meta,nft_set_rbtree
nfnetlink              16384  1 nf_tables
```

**Comment by bgamari** [comment]
Note that even the above isn't solution isn't completely reliable due to an apparent [Docker bug](https://github.com/moby/moby/issues/35777).

**Comment by icewind1991** [comment]
> however, when i tried to get it working, it failed because `nft` wasn't in the `PATH` visible to docker. i looked into trying to override dependencies to add nftables, but based on the way other tools like iptables are made visible to docker, i couldn't find an easy way to do it: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/virtualization/docker/default.nix#L173-L184

You can add extra packages with `virtualisation.docker.extraPackages`.

For anyone else finding this ticket

```nix
virtualisation.docker = {
  extraPackages = with pkgs; [nftables];
  extraOptions = "--firewall-backend=nftables";
}
```

Seems to work to make everything work

**Comment by lucasfcnunes** [comment]
> > however, when i tried to get it working, it failed because `nft` wasn't in the `PATH` visible to docker. i looked into trying to override dependencies to add nftables, but based on the way other tools like iptables are made visible to docker, i couldn't find an easy way to do it: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/virtualization/docker/default.nix#L173-L184
> 
> You can add extra packages with `virtualisation.docker.extraPackages`.
> 
> For anyone else finding this ticket
> 
> virtualisation.docker = {
>   extraPackages = with pkgs; [nftables];
>   extraOptions = "--firewall-backend=nftables";
> }
> Seems to work to make everything work

If @icewind1991 is corrrect, this should be done in the background when `networking.nftables.enable`.
