### ISSUE TITLE
Documentation: Restructure staging workflow description

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixpkgs#243177]
## Problem

The section structure does not introduce concepts in a meaningful order. Details:

https://github.com/NixOS/nixpkgs/pull/225920#pullrequestreview-1384701494

## Proposal

@NixOS/documentation-team Implement suggestions in the linked comment.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by infinisil** [comment]
In https://github.com/NixOS/nixpkgs/pull/245243 I effectively rewrote those parts of the contribution manual. There's now a dedicated section to explain which branch should be used [here](https://github.com/NixOS/nixpkgs/blob/f03d4e0eec54bd1b344977bfc172446c56c95987/CONTRIBUTING.md#branch-conventions) (linked to from a new section on how to make a pull request [here](https://github.com/NixOS/nixpkgs/blob/f03d4e0eec54bd1b344977bfc172446c56c95987/CONTRIBUTING.md#how-to-create-pull-requests)), and a section explaining how merged PR's propagate [here](https://github.com/NixOS/nixpkgs/blob/f03d4e0eec54bd1b344977bfc172446c56c95987/CONTRIBUTING.md#flow-of-merged-pull-requests).

It's not perfect, but it's better than before, and maybe good enough for this to be closable.
