### ISSUE TITLE
Package request: Pipewire Screenaudio

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#243147]
**Project description**

Extension to passthrough pipewire audio to WebRTC Screenshare

Here's a working [configuration](https://github.com/IceDBorn/IceDOS/tree/main/system/programs/self-built/pipewire-screenaudio) for installing the package, but I'm looking for someone that can improve it.

**Metadata**

* homepage URL: https://github.com/IceDBorn/pipewire-screenaudio
* source URL: https://github.com/IceDBorn/pipewire-screenaudio
* license: mit
* platforms: linux

**Comment by IceDBorn** [comment]
Here's the [AUR package](https://aur.archlinux.org/packages/pipewire-screenaudio) for anyone that might need the PKGBUILD

**Comment by jim3692** [comment]
@IceDBorn Please update the license in the description. The license is GPL, not MIT.

**Comment by luzpaz** [comment]
Note: https://github.com/NixOS/nixpkgs/issues/270108
