### ISSUE TITLE
vim framework does not recognize "knownPlugins" anymore?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#24328]
## Issue description

When rebuilding nixos, it tells me that "vim-trailing-whitespace" is not known, though I have it in my "knownPlugins".

### Steps to reproduce

```nix
vam = {
    knownPlugins = pkgs.vimPlugins // # a plugin which is not in pkgs.vimPlugins;
    pluginDictionaries = [
        "the new plugin"
    ];
}
```

## Technical details

* System: 17.09pre102667.2839b10 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.09pre104379.6e0b727"

**Comment by matthiasbeyer** [comment]
It seems that reverting

* 4b9ec73288288a693576795494705f42a626fadd
* dcab4279083a4c04c5d64d40eda3a98e903085b9

solves this problem on current unstable.

The commits were written by @edanaher - could you please investigate?

**Comment by alibabzo** [comment]
[This](https://github.com/NixOS/nixpkgs/blob/dcab4279083a4c04c5d64d40eda3a98e903085b9/pkgs/misc/vim-plugins/vim-utils.nix#L415) is the line which causes the issue, as noted by @pikajude on https://github.com/NixOS/nixpkgs/commit/dcab4279083a4c04c5d64d40eda3a98e903085b9

**Comment by matthiasbeyer** [comment]
Seems like a solution is WIP. I will leave this open until a fix is applied. Thanks for pointing me to this!

**Comment by edanaher** [comment]
I was hoping to get some testing before submitting the PR, but I went ahead and created #24353.

@matthiasbeyer, if you can test that fix and confirm that it works, that would be great. Alternatively, if you could give me the exact configuration you're using (i.e., fill in the placeholders in your reproduction steps with the content you're using for vim-trailing-whitespace), I'll go ahead and test it, and then if anything else is wrong, I can fix that as well.

**Comment by edanaher** [comment]
Looks like this is now in unstable; @matthiasbeyer, can you close this if the fix solves your problem?

**Comment by matthiasbeyer** [comment]
@edanaher I close this now. I cannot update my system to 0a6a06346a3c928a3115dfd700993c5c06b0a1e9 because of another package, but at least the packages can be evaluated, which wouldn't work if this would still be broken, I assume.

Thanks for fixing this!
