### ISSUE TITLE
Version mismatch of plasma download file vs its sha256 hash on downloads page

### ISSUE THREAD

**Issue by jodobear** [NixOS/nixpkgs#243269]
### Describe the bug
There seems to be a mismatch in version #s of the plasma download file vs its SHA256 hash.

### Steps To Reproduce
1. Check the download file name at [NixOS Plasma x86_64](https://channels.nixos.org/nixos-23.05/latest-nixos-plasma5-x86_64-linux.iso)
2. Check the [sha256sum](https://channels.nixos.org/nixos-23.05/latest-nixos-plasma5-x86_64-linux.iso.sha256) of the above download file both are different versions.

### Expected behavior
Both should be the same versions.

### Screenshots
Downloaded file (version # 23.05.1875):
![nixos](https://github.com/NixOS/nixpkgs/assets/36855907/c448c64c-ed61-4712-8412-12345f416de2)

SHA256 on website (version # 23.05.1935):
![nixos-sha256-website](https://github.com/NixOS/nixpkgs/assets/36855907/c0046d4d-7964-4008-ac1f-84d61760a13a)

**Comment by wegank** [comment]
The download link on the website does resolve to [nixos-plasma5-23.05.1935.98da3dd0de6-x86_64-linux.iso](https://releases.nixos.org/nixos/23.05/nixos-23.05.1935.98da3dd0de6/nixos-plasma5-23.05.1935.98da3dd0de6-x86_64-linux.iso) for me. Probably a network or CDN issue on your end?

**Comment by jodobear** [comment]
Yep! Cleared cache and it works now. Thanks
