### ISSUE TITLE
cups-config broken with b8685dd (nixos-unstable)

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#24339]
## Issue description
With the split of cups into more parts the tool cups-config which provides library paths etc stopped working. Cups filters use this command to pinpoint locations. Without a working cups-config for example `cups-dymo` stopped building ( http://sprunge.us/cTha )

It seems the setting of the configure flags in pkgs/misc/cups/default.nix#35 results in the hardcoded string `$(lib)` and `$(out)`:
```
~/nixpkgs /nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config 
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 19: lib: command not found
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 20: lib: command not found
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 25: out: command not found
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 26: out: command not found
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 28: out: command not found
/nix/store/gfwpsv3vp9hvjkmg69schp5yxiyf4a4f-cups-2.2.2-dev/bin/cups-config: line 29: lib: command not found
Usage: cups-config --api-version
       cups-config --build
       cups-config --cflags
       cups-config --datadir
       cups-config --help
       cups-config --ldflags
       cups-config [--image] [--static] --libs
       cups-config --serverbin
       cups-config --serverroot
       cups-config --version
```

### Steps to reproduce

`nix-shell -p cups --run cups-config`

## Technical details

* System: 17.03.git.53a2baa (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 64f96732bbd87172a154ed3d1c51d575b56e7340

cc @vcunat

**Comment by vcunat** [comment]
I'm sorry for that.  It's a bit complicated.  Hopefully fixing that script will be enough.

**Comment by vcunat** [comment]
Well, I just tested some fixup of `cups-config` and those error lines are gone from the build log of `cups-dymo`, but the fatal ones like `error: 'FILE' does not name a type` don't go away and don't seem related.

**Comment by vcunat** [comment]
`cups-config` itself should be OK now on staging.  (GitHub will auto-close when merged to master.)

**Comment by vcunat** [comment]
Oh, /cc maintainer @jgeerds with this fix, to keep him informed :-)

**Comment by makefu** [comment]
@vcunat you are correct, cups-dymo does not build with cups 2.2 anymore. There were simply 2 issues which smashed together at the wrong time ;)
I will to upstream this issue and in the meantime patch the header with stdio includes where needed
