### ISSUE TITLE
Supertab (vim plugin) is broken in NixOS 17.03

### ISSUE THREAD

**Issue by therealpxc** [NixOS/nixpkgs#24336]
## Issue description
If you use Supertab in your [vim_customizable conifguration or whatever](https://github.com/therealpxc/pxc.nix.d/blob/eff01d6549d4e09ad15acc84edbf1f8f155c14b0/profiles/elements/my-packages.nix#L51), you are interrupted with an error message every time you open Vim.

### Steps to reproduce
    /e/nixos   master *  vim                                                                    Sat 25 Mar 2017 01:14:53 PM MST
    Error detected while processing /nix/store/pq7dqsa2wg2p7l0mncl4zx2nw6kyc7d6-vimplugin-Supertab-2016-11-27/share/vim-plugins/Supertab/plugin/supertab.vim:
    line 1000:
    E475: Invalid argument: pumvisible() ? "\<C-P>" : "\<S-Tab>"
    Press ENTER or type command to continue

## Technical details

* System: NixOS: 17.03.git.15bf095 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: ["17.03.git.15bf09567f"](https://github.com/therealpxc/nixpkgs/tree/15bf09567f0f312ab9a64f9136301bc0f78108ed)

**Comment by edanaher** [comment]
I took a quick look at this; it looks like it's actually an interaction between YouCompleteMe and Supertab (at least, Supertab alone didn't reproduce for me).  My guess is that NixOS 17.03 has a newer version of one or both, and it's actually an upstream problem, but will likely dig a bit more over the next couple days as I have time.

**Comment by edanaher** [comment]
I was right - commit 936a6c0f8f016f74425b2a6175f904d77b08df84 is the breaking commit; it switches a bunch of git fetch paths from git:// to http://, and also bumps a bunch of versions.  Notably for this, it bumps youcompleteme from 1d1a4f4cff04ed32ab924dda20666e67eabdefb4 to 39659caf34c664c7419cadb41cb813158e0749fa; switching back to the old version fixes it.  It looks like the newest version also works; I'll make sure of that and submit a PR to upgrade it if so.

**Comment by edanaher** [comment]
That was a bit more work than I thought, since I also had to upgrade ycmd, but #24417 should fix things for you.  (I don't use youcompleteme, so I couldn't do a full test, but it appeared to start up fine...)

**Comment by therealpxc** [comment]
Thank you very much. I will reenable and verify functionality when I get
the chance.

**Comment by therealpxc** [comment]
@edanaher

I cherry-picked the commits from your fix for my use on NixOS 17.03, and the fix has worked fine. :-)

Thanks!
