### ISSUE TITLE
Update request: Quarto 1.2.475 → 1.3.433

### ISSUE THREAD

**Issue by EchosinEchos** [NixOS/nixpkgs#243341]
- Package name:1.3.433
- Latest released version: 1.2.475
- Current version on the unstable channel: 1.2.475
- Current version on the stable/release channel: 1.2.475

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

(a PR exist https://github.com/NixOS/nixpkgs/pull/228984, but it's open by a bot, and they seem stuck)

**Notify maintainers**
@minijackson 
@MrTarantoga 

-----

Note for maintainers: Please tag this issue in your PR.

I'm kind a new here, so I don't know what to do...

I already update Quarto to the last stable version on my local nixpkgs repo : https://github.com/EchosinEchos/nixpkgs

I use the existing default.nix, changed version, and add the fix for dart-sass change of version output, to work properly. I did the quarto check, and compile some small project, everything look good (but I'm not an expert).

The problem is that we need Pandoc 3 for this version, and I update by copying the existing up-to-date version of haskellPacket to the main one (ex copying pandoc_
3_1_3 derivation to pandoc). It's a crap fix, but it works at the end. I'm not a Haskell dev, so I cannot confirm that it works (work was done by other so... I suppose yes).

I don't know what to do. I can put a PR of what's needed, or maybe wait that packet will be updated by itself ?

Best regards. Thibault
(Excuse my English, I'm French, oui oui baguette)

**Comment by thiagokokada** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/253065
