### ISSUE TITLE
vscode: fails to find libGLESv2.so.2, which causes gpu acceleration to be disabled

### ISSUE THREAD

**Issue by pearsche** [NixOS/nixpkgs#243372]
### Describe the bug
I've been trying to see why vscode had rather laggy scrolling and high cpu usage when scrolling on wayland with `NIXOS_OZONE_WL` set to 1, and upon discovering `code --verbose` and `code --status` , I saw that the libGLESv2.so.2 library isn't found by it, causing the app to fall back to software rendering. Disabling the env variable and starting vscode like that shows that on xwayland it does start up with gpu acceleration.

Doing the same thing described [here](https://github.com/NixOS/nixpkgs/issues/158947#issuecomment-1575106532), VScode does start with GPU acceleration working. and no longer complains about the libGLESv2.so.2 library

### Steps To Reproduce
1. Start VScode with `NIXOS_OZONE_WL=1` set and with the `--verbose` flag, so it starts with wayland support and outputs details about the startup and other  stuff
2. Notice how it complains about the libGLESv2.so.2 library.
3. Run `code --status` to see check that it's indeed using software rendering.

### Expected behavior
The library is found, there are no complaints, and GPU acceleration is enabled. 

### Additional context
I am on an Intel laptop.

### Notify maintainers
@eadwu  @Synthetica9 @maxeaubrey @bobby285271 @Enzime 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.11, NixOS, 23.11 (Tapir), 23.11.20230706.3c74875`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Whats the exact log? vscode vendors that library and it is located in our package at lib/vscode/libGLESv2.so.

**Comment by pearsche** [comment]
Relevant lines from `vscode --verbose`
`[347618:0719/215414.133193:ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[347618:0719/215414.134162:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[347632:0719/215414.151686:ERROR:egl_util.cc(44)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[347632:0719/215414.152695:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization`

**Comment by eadwu** [comment]
`--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by 999eagle** [comment]
Same error happens on VSCodium where running with `NIXOS_OZONE_WL=1` on Wayland frequently crashes on startup.
`strace`ing `codium --verbose` yields a lot of `openat(AT_FDCWD, "/nix/store/.../lib/libGLESv2.so.2", ...) = -1 ENOENT` lines before the logged error, including this particularly interesting one:

`openat(AT_FDCWD, "/nix/store/kkb8w8jg1as4n9hqn4638pds7m544xzs-vscodium-1.80.0.23188/lib/vscode/libGLESv2.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`
The file `/nix/store/kkb8w8jg1as4n9hqn4638pds7m544xzs-vscodium-1.80.0.23188/lib/vscode/libGLESv2.so.2` doesn't actually exist, only `/nix/store/kkb8w8jg1as4n9hqn4638pds7m544xzs-vscodium-1.80.0.23188/lib/vscode/libGLESv2.so` does, so apparently VSCodium is looking for `libGLESv2.so.2` while only `libGLESv2.so` is vendored.

If `libglvnd` is added to the `LD_LIBRARY_PATH`, `/nix/store/4a2wldbmd9pmnkkv3ayn6gzl2hj2v2xh-libglvnd-1.6.0/lib/libGLESv2.so.2` is found as a symlink to the actual library and `strace`ing again confirms that this library is loaded by VSCodium.

**Comment by joaojacome** [comment]
@999eagle 

Adding `libglvnd` to the library path did the trick for me, thanks!

```nix
pkgs.vscodium.overrideAttrs(old: {
  libPath = lib.makeLibraryPath [pkgs.libglvnd];
})
```

**Comment by pearsche** [comment]
I can't get it to work with vscode sadly.

`vscode = super.vscode.overrideAttrs (super: {
	libPath = lib.makeLibraryPath [pkgs.libglvnd];
});`

**Comment by dan4ik605743** [comment]
How soon will the changes get into nixos-unstable?

**Comment by drupol** [comment]
2 days max ?

**Comment by drupol** [comment]
You can follow the PR here: https://nixpk.gs/pr-tracker.html?pr=245705

**Comment by anilanar** [comment]
This is still broken for me:

```
Failed to load GLES library: /nix/store/pj28fgr2jj4wn5az6x26px6dsbgc09p7-vscodium-1.80.2.23209/lib/vscode/libGLESv2.so
```

In fact, that file is missing. `libGLESv2.so.2` is missing too. I can also confirm that the wrapper contains:

```
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+':'$LD_LIBRARY_PATH':'}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH/':''/nix/store/1k87lf3ar245hg06kw4fynv4vmcj6pzc-libglvnd-1.6.0/lib'':'/':'}
LD_LIBRARY_PATH='/nix/store/1k87lf3ar245hg06kw4fynv4vmcj6pzc-libglvnd-1.6.0/lib'$LD_LIBRARY_PATH
LD_LIBRARY_PATH=${LD_LIBRARY_PATH#':'}
LD_LIBRARY_PATH=${LD_LIBRARY_PATH%':'}
export LD_LIBRARY_PATH
```

So what gives? How did this work for others but not me?

**Comment by anilanar** [comment]
I'm guessing the last PR fixed it for wayland/`NIXOS_OZONE_WL` but broke it for others?

**Comment by pearsche** [comment]
please open a bug @anilanar !
