### ISSUE TITLE
Package request: mission-center

### ISSUE THREAD

**Issue by 9p4** [NixOS/nixpkgs#243327]
**Project description**

GUI system monitor.

I've done most of the work for packaging already: https://git.sr.ht/~fd/nix-configs/tree/main/item/custompkgs/mission-center

It can't be backported as it requires blueprint-compiler >=0.8 (in unstable only).

**Metadata**

* homepage URL: https://missioncenter.io/
* source URL: https://gitlab.com/mission-center-devs/mission-center
* license: gpl3
* platforms: linux

**Comment by lelgenio** [comment]
As discussed in https://gitlab.com/mission-center-devs/mission-center/-/issues/36, `mission-center` currently has a hard dependency on `libnvtop`, which we currently do not have.

**Comment by 9p4** [comment]
I worked around that by downloading libnvtop and bundling it as part of the application (since patches needed to happen anyway).

From the package I built already:

```
  nvtop = fetchFromGitHub {
    owner = "Syllo";
    repo = "nvtop";
    rev = "9a8458b541a195a0c5cadafb66e240962c852b39";
    hash = "sha256-iFBZbESRTuwgLSUuHnjcXwmpvdeQrd3oUJd7BRyxu84=";
  };
```

**Comment by GaetanLepage** [comment]
I made a PR #244632 :)
