### ISSUE TITLE
`podman` package run-time requires `catatonit`, but isn't including it

### ISSUE THREAD

**Issue by mtalexan** [NixOS/nixpkgs#243350]
### Describe the bug

The (latest?) `podman` package now requires `catatonit` at run-time, but isn't including it in what's installed when the `podman` package installed.

### Steps To Reproduce
1. `nix profile install 'nixpkgs#podman'` (or equivalent `nix shell`, `nix develop`, `nix-shell`, or `nix-env`)
2. From within the environment, `podman run ...` any container
3. See Error

### Expected behavior
Installing `podman` gives a runnable `podman` program, excluding things that can't possibly be handled by nix (e.g. subuid, subgid, global container storage and registry config, etc).  
It shouldn't need running an extra `nix profile install 'nixpkgs#catatonit'` to make it runnable.

### Screenshots
N/A

### Additional context

Example error:
```
Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory
```

### Notify maintainers

@zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
...snip...
- system: `"x86_64-linux"`
- host os: `Linux 5.15.0-76-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.15.0`
- nixpkgs: `/nix/store/rspism4p5xvwms84p5wfsnj93c87avmf-source`
```

**Comment by katexochen** [comment]
@mtalexan is this still an issue? I've tried to reproduce it on NixOS/unstable and Fedora 38/nixpkgs23.05 but it worked on both systems as expected.

`catatonit` was added as a dependency to the podman package end of February this year: https://github.com/NixOS/nixpkgs/pull/218355
Maybe your system didn't include that change at the time of opening this issue?

**Comment by mtalexan** [comment]
It doesn't seem to be a problem anymore. It might have been something with the default config in Fedora 38 at some prior time (since Nix podman doesn't include a config). I just installed it a few different times on different systems and I'm not getting the problem anymore.

**Comment by mtalexan** [comment]
The Ubuntu 20.04 shipped with a very old and unmaintained podman, so installing the host version to get the config may have been configuring for catatonit as the default init when `--init` was used, and then requiring that to be present regardless of whether or not you used the init flag. 

Multiple installs to Ubuntu 22.04 have worked after massaging the `/usr/share/containers` config files the distro-provided version includes. Notably Ubuntu's podman config files no longer default to catatonit and don't install it as a dependency themselves anymore (possibly only in 22.04 though?).

Regardless, I'm blaming this on the config files I had to come up with.
