### ISSUE TITLE
home-assistant: abode no module named jaraco

### ISSUE THREAD

**Issue by JamieMagee** [NixOS/nixpkgs#243344]
### Describe the bug
When attempting to configure the `abode` integration I get an error in Home Assistant

### Steps To Reproduce
1. Add `abode` to `services.home-assistant.extraComponents`
2. Try to configure `abode` integration from Home Assistant UI
3. `Error occurred loading flow for integration abode: No module named 'jaraco'`

### Expected behavior
Able to configure `abode`

### Notify maintainers

@mweinelt @dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"aarch64-linux"`
- host os: `Linux 6.1.21, NixOS, 23.11 (Tapir), 23.11.20230712.2de8efe`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.16.1`
- nixpkgs: `/nix/store/3j9garb3574mxikwbi6zn594j8mjd19s-source`
```

**Comment by mweinelt** [comment]
The `jaraco-abode` package does not eval on master right now, because of a dependency being flagged as disabled for python 3.11. Though I'd be surprised if that is your issue.

```
nix-repl> home-assistant.python.pkgs.jaraco-abode
error:
       … while evaluating the attribute 'drvPath'

         at /home/hexa/git/nixos/master/lib/customisation.nix:222:7:

          221|     in commonAttrs // {
          222|       drvPath = assert condition; drv.drvPath;
             |       ^
          223|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'drvPath'

         at /home/hexa/git/nixos/master/lib/customisation.nix:222:7:

          221|     in commonAttrs // {
          222|       drvPath = assert condition; drv.drvPath;
             |       ^
          223|       outPath = assert condition; drv.outPath;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: cherrypy-18.8.0 not supported for interpreter python3.11

**Comment by dotlambda** [comment]
Regardless, https://github.com/NixOS/nixpkgs/pull/243359 at least makes `python311.pkgs.jaraco-abode` evaluate.
