### ISSUE TITLE
Calibre - invalid style override 'kvantum'

### ISSUE THREAD

**Issue by DrymarchonShaun** [NixOS/nixpkgs#243329]
### Describe the bug
Calibre won't use kvantum for theming. Upon launch it gives the error
```
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
```
### Steps To Reproduce
With  
```
qt6Packages.qtstyleplugin-kvantum ( I also have libsForQt5.qtstyleplugin-kvantum, if it matters)
calibre
```
installed, run calibre with `QT_STYLE_OVERRIDE=kvantum calibre` 
### Expected behavior
calibre to use kvantum for theming

### Notify maintainers

Calibre: @pSub  @AndersonTorres 
Kvantum: @romildo @Scrumplex 

### Metadata

```console
shaun@natrix ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230711.f240619`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/6w0n7ivwnbvfh32xw3cb0yrvdw3l4q89-source`
```

**Comment by Scrumplex** [comment]
*How* did you install `qtstyleplugin-kvantum`? 

You might need to make sure it's installed in `environment.systemPackages` to properly link the Qt plugin directories.

Relevant code (`qt.enable = true;`):

https://github.com/NixOS/nixpkgs/blob/712d6cf98e420943f14bf112d1ba450c21a4c500/nixos/modules/config/qt.nix#L110-L115

**Comment by DrymarchonShaun** [comment]
Apologies then, I was using home manager. I guess there must be an issue on the home manager side with qt6 then, kvantum was working fine with qt5 previously.
