### ISSUE TITLE
TeX Live: `mptopdf` is broken

### ISSUE THREAD

**Issue by williamyaoh** [NixOS/nixpkgs#24343]
## Issue description

The `mptopdf` executable installed as part of `texlive.combined.scheme-basic` errors out no matter
what arguments it's called with, with an error:

    /nix/store/.../bin/bash -S: invalid option

### Steps to reproduce

1. Install the basic TeX Live setup
   `nix-env -f '<nixpkgs>' -iA texlive.combined.scheme-basic`
2. Run `mptopdf`

### Notes

The problem seems to come from these lines at the very beginning of the `mptopdf.pl` Perl script that
the TeX Live derivation wraps around:

```bash
eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}' && eval 'exec perl -S $0 $argv:q'
        if 0;
```

It's using `exec` and `$0` to do what a shebang does instead of... just using a shebang.
The Perl call is expecting `$0` to point directly to the `mptopdf.pl` script, but the Nix wrapper
script is setting `$0` to whatever command it was called with; in this case, the raw string `"mptopdf"`.

Placing these lines in a separate executable file (let's say `mptopdf.sh`) and simulating
what the wrapper script does, reproduces the error message:

```bash
$ bash -c 'exec -a mptopdf ./mptopdf.sh
/nix/store/.../bin/bash -S: invalid option
```

After replacing the instance of `perl` in the first exec call with an absolute store path,
and `$0` with the store path to `mptopdf.pl`, the command above then works and calls `mptopdf`
as intended.

The TeX Live distribution installed on my Ubuntu setup looks like it just replaced those first
two lines in `mptopdf.pl` with `#! /usr/bin/perl -w`. So it seems like the easiest way would be either
to patch `mptopdf.pl` to use a shebang line pointing directly to Perl, or to patch the wrapper script
created around `mptopdf` to pass something else as `$0`; that is, change this line in the wrapper
script:

```bash
exec -a "$0" "/nix/store/...-mptopdf-2016/scripts/context/perl/mptopdf.pl"  "${extraFlagsArray[@]}" "$@"
```

to this:

```bash
exec "/nix/store/...-mptopdf-2016/scripts/context/perl/mptopdf.pl"  "${extraFlagsArray[@]}" "$@"
```

so that the Perl script can find and call itself.

## Technical details

* System: `17.03beta685.1dbb962 (Gorilla)`
* Nix version: `1.11.8`
* Nixpkgs version: `17.03beta685.1dbb962`

**Comment by williamyaoh** [comment]
There are some other Perl scripts in the TeX Live source repo that *also* have this weird
pseudo-shebang line:

https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/scripts/context/perl/

They're not installed as part of the `basic-scheme` derivation, but they might be installed as
part of other TeX packages, and would likely need patching as well.

**Comment by vcunat** [comment]
I haven't noticed this ticket; it should be OK now on both master and 17.03.

These ugly pseudo-shebangs are now detected and wrapped by `perl -w` instead of bash.
