### ISSUE TITLE
Mouse and keyboard doesn't work with X.Org after update

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#24348]
## Issue description
After updating NixOS to latest unstable channel mouse and keyboard doesn't work at all using X.Org, I could only restart my computer with Magic SysRq key. 
Here is the journalctl log (only kernel messages) from the boot:
[https://gist.github.com/Mounium/1000bb203662473e34aca5dbf57fc0bf](url)

Using `-p err` these two logs show up (although the second one is normal, it happens during normal boot as well without any appearant problem)
```
márc 26 11:57:15 eni kernel: usb 1-3: device descriptor read/64, error -71
márc 26 11:57:17 eni kernel: amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
```

## Technical details

* System: 17.09pre104410.65593e6 (Hummingbird)

**Comment by globin** [comment]
Could you try with 785e45ac06209295531955c0da302f72cb01e4ff reverted?

**Comment by Mounium** [comment]
It didn't solve the problem unfortunately, I still get the same kernel error. By the way I am using Gnome shell with gdm, maybe relevant?

**Comment by vcunat** [comment]
IIRC gnome forces using libinput instead of evdev.

**Comment by abbradar** [comment]
And more importantly, Gnome 3 is sadly broken currently.

**Comment by globin** [comment]
gnome3 works with gdm as of master a few secons ago :)

**Comment by vcunat** [comment]
Meaning this input issue has been fixed recently, right?

**Comment by OCmylife** [comment]
gdm seems to be the culprit, as I have no issues with my keyboard and mouse using lightdm as my loginmanager

**Comment by Mounium** [comment]
Mouse and keyboard indeed works with master, but unfortunately now I can't seem to change the keyboard layout from English from the settings nor with services.xserver.layout (the first option worked with previous gnome versions) nor the wallpaper, not even with gnome-tweak-tools, although I can get by without it :D  Should I create a separate issue for it?

**Comment by vcunat** [comment]
*If* it's the case that gnome3 now uses wayland instead of X by default, I wouldn't expect `xserver.layout` to work...

**Comment by OCmylife** [comment]
I've found a workaround to set the Keyboard-Layout directly with ibus: ibus list-engine && ibus engine xkb.xx.yy.zz
Ibus-setup doesn't work with Gnome, but there's already two bug reports open since last year. But unfortunately my workaround doesn't stick after a reboot. Maybe a script could help, that runs this command, after the boot process has finished
