### ISSUE TITLE
openresolv is missing sed in its wrapper

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#243564]
### Describe the bug

openresolv is missing sed in PATH
I just tried to run that command on unstable
```
nix build .#openresolv
➜ result/bin/resolvconf -R
/nix/store/r0iw20jzng26chwk29pzpmpyrqmdmq2g-openresolv-3.12.0/sbin/.resolvconf-wrapped: line 765: sed: command not found
```

### Expected behavior
according to the help, I was expecting the command:
`-R Show the system service restart command`

### Additional context
was trying to refresh some DNS entry in the cache

### Metadata
nixos-unstable as of today

**Comment by Artturin** [comment]
Are you going to remake that PR?

**Comment by teto** [comment]
yes I put it there https://github.com/NixOS/nixpkgs/pull/243691

**Comment by teto** [comment]
closing since the tradeoff was not worth it see linked PR
