### ISSUE TITLE
List of available haskell packages at hackage should not contain broken packages

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#243512]
The Haskell Hackage database allows distros to report which packages they ship, and include a link. Right now, it seems that nixpkgs reports all haskell packags, including broken ones. This makes for a bad user experience – I might see on hackage that nixos comes with a certain package, and then happily go ahead trying to use it, only later to get the dreaded 
```
error: Package ‘proteaaudio-0.9.4’ in /home/jojo/build/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:236858 is marked as broken, refusing to evaluate.
```
error message.

Same actually for repology, reporting packages as available that we know do not build is not great.

**Comment by Et7f3** [comment]
We intend to support all package. We just need haskell maintainer

**Comment by nomeata** [comment]
Oh, absolutely! Maybe I shouldn't say “supported” but “available”.

**Comment by maralorn** [comment]
> We intend to support all package. We just need haskell maintainer

No, we don't. We only intend to support packages which have value to our users. Hackage is append only and contains a lot of dead or niche packages.

**Comment by maralorn** [comment]
I agree this should have been fixed long ago.
