### ISSUE TITLE
surfraw error

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#24351]
$ nix-shell -p surfraw --run 'surfraw wikipedia nixos'surfraw ERROR: couldn't find global config in /nix/store/jlyxvw06yyrasps2fdi53mxwvzyn8id5-surfraw-2.2.9/etc/xdg/surfraw/conf or $XDG_CONFIG_DIRS

**Comment by pSub** [comment]
This is not nixpkgs problem. Surfraw searches in $XDG_CONFIG_DIRS if the variable is set and stops the search if no configuration file is found. I've submitted a patch for this in kisom/surfraw/pull/2.

**Comment by pSub** [comment]
It seems that I've submitted the PR to the wrong repository. Therefore I've filled one again against the correct repository https://gitlab.com/surfraw/Surfraw/merge_requests/1.

**Comment by pSub** [comment]
The PR was merged by upstream. The fix will be included in the next release of surfraw.
