### ISSUE TITLE
vivaldi-ffmpeg-codecs broken in newest version

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#243618]
### Describe the bug
Proprietary HTML5 videos break the whole site

Workaround is to disable `proprietaryCodecs`.

### Steps To Reproduce
1. Override Vivaldi package with `proprietaryCodecs = true`
2. Use the package in your Configuration (home-manager)
3. Open YouTube

### Expected behavior
YouTube should display and the video should play.
### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/86004375/34c3b0c7-03fa-42e6-be44-38a28ba65001)

### Notify maintainers

@otwieracz @badmutex @betaboon @cawilliamson @lluchs 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.1-xanmod1, NixOS, 23.11 (Tapir), 23.11.20230713.e74e684`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/3z2ddp392iwz4dm4f040p55gylzcxyfg-source`
```

**Comment by FPtje** [comment]
I hit this issue myself yesterday as well. I had reported it to Vivaldi before I realized it was indeed an outdated chromium-ffmpeg dependency. See [this forum post](https://forum.vivaldi.net/topic/88884/page-crash-due-to-read-out-of-range-on-nixos). I wrote a PR at https://github.com/NixOS/nixpkgs/pull/243786 to fix this. For a quick fix, here's the code I have in my overlay to work around this straight away:

```nix
vivaldi-ffmpeg-codecs = previous.vivaldi-ffmpeg-codecs.overrideAttrs (prev: rec {
    version = "111306";
    src = final.fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/XXzVIXswXKHqlUATPqGCj2w2l7BxosS8_34.snap";
      sha256 = "sha256-Dna9yFgP7JeQLAeZWvSZ+eSMX2yQbX2/+mX0QC22lYY=";
    };

    buildInputs = with final; [squashfsTools];

    unpackPhase = ''
      unsquashfs -dest . $src
    '';

    installPhase = ''
      install -vD chromium-ffmpeg-${version}/chromium-ffmpeg/libffmpeg.so $out/lib/libffmpeg.so
    '';
  });
```

**Comment by Mikilio** [comment]
I just saw it. Thanks a lot! I will close this issue now as you already created an issue for discussion.
