### ISSUE TITLE
[tor-browser] Opening Tor Browser twice results in an error and unusable window

### ISSUE THREAD

**Issue by Industrial** [NixOS/nixpkgs#243605]
### Describe the bug
Tor Browser crashes when you execute the command twice

### Steps To Reproduce
1.

    services.tor.client.enable = true;
    services.tor.enable = true;
    services.tor.openFirewall = true;
  
    environment.systemPackages = with pkgs; [
      tor-browser-bundle-bin
    ];
2. `tor-browser`
3. `tor-browser`
4. Tor Browser is already running, but is not responding. To use Tor Browser, you must first close the existing Tor Browser process, restart your device, or use a different profile.

### Expected behavior
Two windows (or a new tab if you add `--new-tab` for example).

### Notify maintainers
@felschr @panicgh 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230712.2de8efe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by felschr** [comment]
I think it's intended behavior that Tor Browser cannot be started twice with the same profile, it should be possible to start it with different profiles, however.
Currently the Tor Browser package in nixpkgs hard codes the profile directory, though, so this doesn't work.

I'm looking into it.

**Comment by Industrial** [comment]
@felschr is this now solved? :)

**Comment by felschr** [comment]
You should be able to launch multiple instances of Tor Browser when using different profiles.

```console
# to create profiles
tor-browser --profilemanager

# to launch
tor-browser -P ~/.tor\ project/firefox/my-profile
tor-browser -P ~/.tor\ project/firefox/other-profile
```

---

I have a home-manager module for Firefox, Tor Browser & Mullvad Browser based on home-manager's own Firefox module that allows you to manage profiles via Nix:
https://gitlab.com/felschr/nixos-config/-/blob/main/home/modules/firefox

It's exposed via the [flake](https://gitlab.com/felschr/nixos-config/-/blob/e60d1ebeb032f5d727f96c41fd3ed59b8c7ffd3c/flake.nix#L102-104) and [here](https://gitlab.com/felschr/nixos-config/-/blob/e60d1ebeb032f5d727f96c41fd3ed59b8c7ffd3c/home/browsers/mullvad-browser.nix) is my example config for Mullvad Browser.
