### ISSUE TITLE
Errors with fwupd 

### ISSUE THREAD

**Issue by eskimor** [NixOS/nixpkgs#24376]
## Issue description
Firing up fwupdmgr:
```
fwupdmgr get-updates
Error calling StartServiceByName for org.freedesktop.fwupd: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit fwupd.service not found.
```

So fwupd cannot be started automatically, so I start it manually:

```
/nix/store/pdlbih1qhwn48w0f99fvy047y9sz25c7-fwupd-0.8.1/libexec/fwupd/fwupd 

(fwupd:5552): Fu-WARNING **: disabling plugin because: failed to coldplug raspberrypi: Raspberry PI firmware updating not supported, no /boot/start.elf

(fwupd:5552): Fu-WARNING **: disabling plugin because: failed to coldplug synapticsmst: MST firmware updating not supported, missing kernel support.

```
which kinda works, but not fully:

```
fwupdmgr refresh
Failed to download https://s3.amazonaws.com/lvfsbucket/downloads/firmware.xml.gz.asc: SSL handshake failed
```

listing devices with `get-devices` works fine though.

### Steps to reproduce

1. Install fwupd by adding it to environment.systemPackages in /etc/nixos/configuration.nix
2. Also add it to services.dbus.packages (thought that might help)
3. Try to run fwupdmgr as listed above

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03.git.5e4b43d (Gorilla)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.7`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03beta542.5e4b43d"

**Comment by eskimor** [comment]
@shlevy am I doing something wrong?

**Comment by shlevy** [comment]
You need to set up the fwupd systemd service as well. `systemd.packages = [ pkgs.fwupd ];`

**Comment by eskimor** [comment]
Thank you! Although the second error messages persists and also when firing up fwupdmgr now I get:

```
fwupdmgr get-devices
^C^C^C^C^C^C^C^C^C^C^C^CError calling StartServiceByName for org.freedesktop.fwupd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.fwupd': timed out

```

Reason being:

```
-- Unit fwupd.service has begun starting up.
Mar 30 11:25:08 xps13 systemd[9314]: fwupd.service: Failed at step NAMESPACE spawning /nix/store/5bmh4ikv3fldp069mh4p29dsplx6f1nh-fwupd-0.8.1/libexec/fwupd/fwupd: No such file or directory
-- Subject: Process /nix/store/5bmh4ikv3fldp069mh4p29dsplx6f1nh-fwupd-0.8.1/libexec/fwupd/fwupd could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /nix/store/5bmh4ikv3fldp069mh4p29dsplx6f1nh-fwupd-0.8.1/libexec/fwupd/fwupd could not be executed and failed.
```

which is weird, because the file exists and works just fine when executing it by hand - but still refresh not working.

**Comment by shlevy** [comment]
Ah, you need to create /var/lib/fwupd. I suppose this should all be in a NixOS service... https://github.com/hughsie/fwupd/issues/94

**Comment by shlevy** [comment]
See also https://github.com/hughsie/fwupd/issues/95

**Comment by eskimor** [comment]
Many thanks! The service works now, but the ssl problem persists, even after adding gnome3.glib_networking to systemPackages and restarting fwupd service. Any ideas? Thank you!

**Comment by shlevy** [comment]
This is in my `configuration.nix`:
```nix
environment.variables =
        { GIO_EXTRA_MODULES = "${pkgs.glib_networking.out}/lib/gio/modules:${pkgs.gnome3.dconf}/lib/gio/modules";
          GSETTINGS_SCHEMA_DIR = "${pkgs.gsettings_desktop_schemas}/share/gsettings-schemas/gsettings-desktop-schemas-3.22.0/glib-2.0/schemas";
        };
```

**Comment by eskimor** [comment]
We are getting somewhere, now I get a different error for fwupdmgr refresh:

```
Failed to update metadata: Error openening ..... /etc/pki/fwupd-metadata
```
hmmm ...

**Comment by shlevy** [comment]
Ah, there are a bunch of files in `${fwupd}/etc/pki` that should be linked in.

**Comment by eskimor** [comment]
Thank you! Now refresh seems to work! Let's see whether I can upgrade my firmware too ;-)

**Comment by eskimor** [comment]
Ok everything seems to work, but it does not find any updates for my WD15 Docking Station (or anything else). In any case, this bug can be closed now. Thanks again!

**Comment by ksouf** [comment]
> See also [fwupd/fwupd#95](https://github.com/fwupd/fwupd/issues/95)

Hey i'm sorry i'm newbee on nixos how do you  ensure that /var/lib/fwupd what is the cmd that you used

**Comment by eskimor** [comment]
Sorry, I no longer have the faintest idea. :-(
