### ISSUE TITLE
Vintagestory .net 7 experimental build

### ISSUE THREAD

**Issue by GiggleSquid** [NixOS/nixpkgs#243716]
## Issue description
Vintage Story's upstream binary is currently built on .net 4 and the derivation runtime is mono.

Future releases will eventually be built on .net 7
https://www.vintagestory.at/blog.html/news/v1186-stable-security-patch-r360/
> In future, we plan for upcoming 1.19.x and later versions of Vintage Story to be released in .NET 7.0 only, so this .NET 7.0 build can be seen as a sneak preview of that!

A .net 7 experimental build is being released alongside the stable releases since 1.18.6-rc.1
https://info.vintagestory.at/v118-net7

## Technical details
I have started work on a [branch on my fork](https://github.com/GiggleSquid/nixpkgs/tree/pkgs/vintagestory-dotnet7) to include an override in the package to allow for selecting the experimental build.
This comes with laying the foundations in the derivative for supporting dotnet-runtime_7.

Currently my local fork package successfully builds both the .net 4 (mono) and .net 7 builds of the upstream binaries on x86_64-linux (there may be missing runtime libraries in the .net 7 build).

Further work is needed on supporting Windows and Mac on the .net 7 build

## Future
Maybe think about supporting the game server similar to minecraft.

## Notify Maintainers
@Artturin

**Comment by CutestNekoAqua** [comment]
@GiggleSquid do you want to upstream your work yourself or let someone else do it?

**Comment by GiggleSquid** [comment]
> @GiggleSquid do you want to upstream your work yourself or let someone else do it?

I'm happy to do it myself. I'm still testing at the moment. Got some mouse cursor issues which I think are missing dependency related.

Also got another package in a PR with my maintainer add commit. So I'll have to plan swapping that commit.

You're welcome to branch my branch if you feel you can work on something as well.
Or maybe just do some additional testing on the experimental build.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/243996

**Comment by GiggleSquid** [comment]
> #243996

That works too ;)

Would you like me to add myself as a maintainer when I'm on the list?

**Comment by Artturin** [comment]
Added you in that PR

**Comment by GiggleSquid** [comment]
Just seen it. That's fantastic, thank you
