### ISSUE TITLE
`extra-utils` is not allowed to refer to the following paths `util-linux-2.39-mount`

### ISSUE THREAD

**Issue by nifoc** [NixOS/nixpkgs#243820]
### Describe the bug

Trying to update a system to the latest `nixpkgs-unstable` "release" (`29bcead8405c`) results in the following error:

```
error: output '/nix/store/ibzgyvbn19ddwf40j49rsqxcyiy7bxzp-extra-utils' is not allowed to refer to the following paths:
         /nix/store/qhvwgvvm60s6df4samryixrrzblrlnha-util-linux-2.39-mount
error: 1 dependencies of derivation '/nix/store/8k5bsbpa3ndpji6r9wv70pab1gapaz0n-stage-1-init.sh.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hkwswshix57mzc34by49rk2ibxsa2jsb-initrd-linux-6.3.12.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yg32jyqpr85306rbqysvqrfyagjrppl6-nixos-system-tanker-23.11.20230715.29bcead.drv' failed to build
```

### Steps To Reproduce

I don't know how to easily reproduce this. At least for me, it seems to happen because the [ZFS module](https://github.com/NixOS/nixpkgs/blob/29bcead8405cfe4c00085843eb372cc43837bb9d/pkgs/os-specific/linux/zfs/generic.nix#L69) needs to adjusted. So:

Try to update a system that (at least) uses ZFS I guess ...

### Expected behavior

No build failure.

### Screenshots

N/A

### Additional context

It looks like this was caused by #236463.

I'm not sure if the ZFS module is the only place that needs to be adjusted after this PR has landed.

### Notify maintainers

@lheckemann (authored the PR mentioned above)
@ElvishJerricco (approved the PR mentioned above)
@jcumming @jonringer @globin @raitobezarius (ZFS maintainers)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.12, NixOS, 23.11 (Tapir), 23.11.20230715.46ed466`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/b6vnb230hgq98bbp7xpgszm7bk2m0bz5-source`
```

**Comment by RaitoBezarius** [comment]
For now, I'm not sure, I can reproduce on 23.11pre504982.664361e485b.
It seems like the fix is obvious though.

**Comment by nifoc** [comment]
While I understand how to adjust the two lines in `substituteInPlace`, I don't know how to deal with the other occurrences of `util-linux` in that file.

**Comment by Mic92** [comment]
Usually you can replace "${util-linux}/bin/mount" with just "mount" and let the $PATH lookup handle where this binary actually is.

**Comment by SuperSandro2000** [comment]
I have a potentially fix in #244033

**Comment by RaitoBezarius** [comment]
Someone should prove that before the fix, this was broken with a NixOS test ideally and with this fix, this is unbroken.

**Comment by lheckemann** [comment]
I suspect it's related to https://github.com/NixOS/nixpkgs/blob/9f6bb855c25bc32ad09a92ba30acd8230f98d27e/nixos/modules/system/boot/stage-1.nix#L113-L127 and that that's not covered by any of the existing nixos tests.

**Comment by lheckemann** [comment]
And that in turn can't trivially be tested end-to-end because nixos-generate-config doesn't actually support non-legacy zfs mounts...

I've written a test and a little prose about the issue: https://github.com/lheckemann/nixpkgs/commit/f8c6c29d82d441d28ece49ddac7a612c03637751

**Comment by SuperSandro2000** [comment]
> And that in turn can't trivially be tested end-to-end because nixos-generate-config doesn't actually support non-legacy zfs mounts...

Maybe we should consider adding them. Using new mounts is rather convenient when the disk needs to be mounted in a live iso.

**Comment by pmarreck** [comment]
Ran into the same exact issue over here. Also running on ZFS root.

```
bash> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.12, NixOS, 23.11 (Tapir), 23.11pre503950.e74e68449c3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(pmarreck): `""`
 - channels(root): `"nixos, nixos-hardware, nixos-master, nixos-stable-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by ElvishJerricco** [comment]
Fix reverted because it broke basically the entire nixos test suite: https://github.com/NixOS/nixpkgs/pull/244445

**Comment by RossComputerGuy** [comment]
I get this with NixOS 23.05.

**Comment by lheckemann** [comment]
@RossComputerGuy are you sure it's exactly that? The util-linux split isn't even on 23.05 so that would be very weird.

**Comment by RossComputerGuy** [comment]
@lheckemann Yes
```
Resolved URL:  git+file:///etc/nixos
Locked URL:    git+file:///etc/nixos
Description:   A Flake of my NixOS machines
Path:          /nix/store/4mly5qmka894sd9ixvh2z595547qvks0-source
Last modified: 2023-08-01 11:20:18
Inputs:
├───darwin: github:lnl7/nix-darwin/d3529322dcaaddf0c50cb277c9c2a355f3a36a3b
│   └───nixpkgs follows input 'expidus-sdk'
├───expidus-sdk: github:ExpidusOS/sdk/95ddd8dd4475a0d36684470a3b11bee0006125df
│   ├───disko: github:nix-community/disko/4015740375676402a2ee6adebc3c30ea625b9a94
│   ├───flake-utils: github:numtide/flake-utils/919d646de7be200f3bf08cb76ae1f09402b6f9b4
│   │   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e
│   ├───home-manager follows input 'home-manager'
│   ├───mobile-nixos: github:NixOS/mobile-nixos/56fc9f9619f305f0865354975a98d22410eed127
│   └───nixpkgs follows input 'nixpkgs'
├───home-manager: github:nix-community/home-manager/07c347bb50994691d7b0095f45ebd8838cf6bc38
├───nixos-unstable: github:NixOS/nixpkgs/66aedfd010204949cb225cf749be08cb13ce1813
├───nixpkgs: github:NixOS/nixpkgs/e9ca92b55bed47696cc7cc25d3f854a1e2e01f86
└───nur: github:nix-community/NUR/c64100ba2b7d6c2831712fc59d3168265f9d93eb
---
error: output '/nix/store/60jfm0i05dnx7dmdcd6m59zvspqqhxvj-extra-utils' is not allowed to refer to the following paths:
         /nix/store/z9d9l57d40537vl2px0zwas26srgnfay-util-linux-2.39-mount
error: 1 dependencies of derivation '/nix/store/4h2q6y8f2jcqsnn1qnb2nmn8vw1yqlaz-stage-1-init.sh.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c881n41cczp1j1zar1mmz3wgxxidlzl3-initrd-linux-6.1.42.drv' failed to build
```

**Comment by RossComputerGuy** [comment]
I have unstable for Alacrity which is an application, I don't see how that would affect initramfs generation.

**Comment by lheckemann** [comment]
And I don't see how you'd get a split util-linux from 23.05, since #236463 wasn't backported there.

**Comment by ElvishJerricco** [comment]
Indeed:

```
$ nix eval github:NixOS/nixpkgs/nixos-23.05#util-linux.outputs
[ "bin" "dev" "out" "lib" "man" "debug" ]
```

And in fact:

```
$ nix eval github:NixOS/nixpkgs/nixos-23.05#util-linux.version
"2.38.1"
```

Which is a different util-linux version number than we see in your error message.

Finally, your nix flake metadata says your using e9ca92b55bed47696cc7cc25d3f854a1e2e01f86, and:

```
$ nix eval github:NixOS/nixpkgs/e9ca92b55bed47696cc7cc25d3f854a1e2e01f86#util-linux.version
"2.38.1"
```

So something fishy is going on here. You've got an overlay or override or something that's pulling in a different util-linux from unstable. Either that or there's some other build that's occurring as an unexpected transitive dependency that's building a nixos system using an unstable nixpkgs that doesn't contain the fix. Either way, I feel fairly confident in saying this is some obscure and subtle user error.
