### ISSUE TITLE
tcl: can't find tzdata

### ISSUE THREAD

**Issue by akho** [NixOS/nixpkgs#243831]
### Describe the bug

On current NixOs unstable:

```console
> nix run nixpkgs#eltclsh                                   

              eltclsh1.18 - Copyright (C) 2001-2020 LAAS-CNRS

eltclsh > set t [clock scan {2004-10-30 05:00:00} \
-format {%Y-%m-%d %H:%M:%S} \
-timezone :America/New_York]

time zone ":America/New_York" not found
```

### Steps To Reproduce

As above

### Expected behavior

Correct handling of timezone

### Additional context

Tcl can either use system tzdata from a list of directories, or install its own. Installation of  Tcl’s own tzdata is disabled in nixpkgs via commit 02bae3913260296447fe80ffb44276f48239e317, as NixOs installs its own tzdata.

However, `clock.tcl` [uses](https://core.tcl-lang.org/tcl/file?name=library/clock.tcl) a fixed list of paths to look for tzdata:

```tcl
    # Paths at which binary time zone data for the Olson libraries are known
    # to reside on various operating systems

    variable ZoneinfoPaths {}
    foreach path {
	/usr/share/zoneinfo
	/usr/share/lib/zoneinfo
	/usr/lib/zoneinfo
	/usr/local/etc/zoneinfo
    } {
	if { [file isdirectory $path] } {
	    lappend ZoneinfoPaths $path
	}
    }
```

This list, unsurprisingly, does not include `${pkgs.tzdata}/share/zoneinfo`. So on NixOs clock does not see any tzdata, and on non-NixOs it sees tzdata from outside the store, which may be a reproducibility issue.

### Notify maintainers

@siraben (I don’t see any maintainers listed, mentioning author of last version bump)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"                     
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.2, NixOS, 23.11 (Tapir), 23.11.20230713.e74e684`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-hardware"`
 - channels(akho): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SkyLeite** [comment]
Ran into a similar issue with Golang. It looks for the `zoneinfo` directory in those same paths, which are not included in NixOS. Looking at [this page](https://www.unix.com/man-page/linux/4/zoneinfo/), it seems like `/etc/zoneinfo` is non-standard. I feel like symlinking `/etc/zoneinfo` to `/usr/share/zoneinfo` by default makes sense

**Comment by akho** [comment]
> Right. I think we're talking about different issues here. For a package built with Nix this makes absolute sense, but in a NixOS system software that _isn't_ built by Nix should be able to rely on `zoneinfo` existing in a standard location.

Yes, that's a different issue (and probably beyond the scope of this thread?). 

I think that this is a minor obstacle to running binaries on NixOS, all things considered. Probably `buildFHSUserEnv` should put zoneinfo in the FHS-defined location (`/usr/share/zoneinfo/`), but doing this by default rather masks the kind of issue I was talking about earlier. Same as the other FHS dirs.
