### ISSUE TITLE
Is linuxPackages.perf dependable on non-NixOS hosts?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#24382]
Question: Is it safe to use the package `linuxPackages.perf` in Nix expressions that will run on non-NixOS Linux hosts (for example Ubuntu or RHEL)?

My concern is that perf may interface with the kernel using an unstable private interface and be sensitive to the exact running kernel version i.e. be an impure dependency that will be prone to breakage.

Great if that is not a problem in practice but I don't have the platforms available to test with so I am looking for crowdsourced wisdom...

**Comment by dezgeg** [comment]
It should be safe, at least in theory. There aren't (or at least shouldn't be) any userspace-kernel interfaces that aren't stable. Or at least Linus shouts at people who try to break any interface. :)

**Comment by lukego** [comment]
@dezgeg On the one hand that's true, on the other hand I think that most distros distribute a separate version of perf userspace for each supported kernel? (and that it doesn't work unless you use the right one?) Seems like that has been my experience although I don't know how to reconcile that with well-known kernel policies.

**Comment by lukego** [comment]
(Closing to avoid clutter but don't know the answer yet. Possibly have to try running it in a bunch of VMs of different distros.)
