### ISSUE TITLE
Unifi Controller wants MongoDB 4.2 which was dropped.

### ISSUE THREAD

**Issue by vifino** [NixOS/nixpkgs#243819]
### Describe the bug
Since #236259, MongoDB 4.2 was dropped.
However, the Unifi Controller still depends on it:
https://github.com/NixOS/nixpkgs/blob/af8279f65fe71ce5a448408034a8c06e2b4b2c66/nixos/modules/services/networking/unifi.nix#L45

### Steps To Reproduce
1. `services.unifi.enable = true;`
2. BANG

### Expected behavior
Unifi Controller enables and works as expected.

### Additional context
Unifi Controller bundles a stone age MongoDB, 4.2 worked fine however.
I am unsure if later versions work without manually hacking around, but I think more care should've been taken
to ensure it still works.

### Notify maintainers
@pennae - Unifi Controller
@wegank - Author of the 4.2 removal PR

**Comment by hughobrien** [comment]
Master seems to have 4_4 specfied: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/unifi.nix#L45

**Comment by Janik-Haag** [comment]
Yes master has 4_4 specified and unstable has 4_4 and the update is already live on unstable. And 4_2 is still available on 23.11 So I think we can close this ^^ 
https://nixpk.gs/pr-tracker.html?pr=236259

When did you encounter that? You might want to update the system state version at some point.

**Comment by vifino** [comment]
... Huh. Apologies, I was under the impression that it's still the old version. Haven't tried it, but I hope it upgrades on its own.
