### ISSUE TITLE
KeePass won't start - wrong quotation marks in .keepass-wrapped

### ISSUE THREAD

**Issue by shokinn** [NixOS/nixpkgs#24387]
## Issue description
KeePass won't open because there is a missing quotation mark after `mono` and one to much after `KeePass.exe` 
```
#! /nix/store/fibk8jc2iwswn1q1d7aw98pcw2l3lzjf-bash-4.4-p12/bin/bash -e
exec "/nix/store/9m51rc30dkxymllz5mcahs40f8b3pw4k-mono-4.0.4.1/bin/mono "/nix/store/9q9r5ymw0al217w9ms9g1xyls9z7iyfv-keepass-2.35/lib/dotnet/keepass/KeePass.exe""  "${extraFlagsArray[@]}" "$@"
```

### Steps to reproduce
* Use unstable Channel.
* Install KeePass
* just try to start KeePass via `keepass`

## Technical details

* System: 17.09pre104410.65593e6 (Hummingbird)
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre104410.65593e6
* pkg-name: keepass-2.35

**Comment by abbradar** [comment]
Thanks for reporting!

**Comment by globin** [comment]
(It actually just takes a minute or so after pushing the commit)

**Comment by abbradar** [comment]
@globin You outran me in cherry-picking ~_^

**Comment by globin** [comment]
Hrhr 👿

**Comment by shokinn** [comment]
Just a little question. I'm new on NixOS, so what I've to do to get keepass working again?
Just wait and update?

**Comment by abbradar** [comment]
@shokinn Sorry for the late response -- this should be available in channels now, but generally if you need something ASAP you need to checkout nixpkgs repository at the latest unstable commit and cherry-pick needed patches.
