### ISSUE TITLE
Chrome does not display pages properly

### ISSUE THREAD

**Issue by Djabx** [NixOS/nixpkgs#243939]
### Describe the bug

On branch nixos-23.05 I've got a configuration (with a chrome on gnome) that work properly.
* chrome is working here :heavy_check_mark: 0de86059128
* chrome does not work here :negative_squared_cross_mark: e11142026e2

### Steps To Reproduce

1. build nixos with chrome 
2. open a web page
3. the page is not properly displayed

### Expected behavior

Chrome should be able to render pages properly.

### Screenshots

Chrome is working properly on 0de86059128
![chrome_124](https://github.com/NixOS/nixpkgs/assets/69534/7b25e934-ab4a-4cff-8e5a-87227ed1ed90)

Chrome is not work*ing properly on e11142026e2
![chrome_125](https://github.com/NixOS/nixpkgs/assets/69534/509a2f20-8b94-41fe-8c62-042c38dbf47e)

### Additional context

I'm not sur it's a chrome issue, but it's the only issue I have recorded.
Could it be the graphic driver ?

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.0, NixOS, 23.05 (Stoat), 23.05.1501.0de86059128`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(alex): `"nixos-unstable, nixpkgs-unstable, nixuns"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

# lspci
00:00.0 Host bridge: Intel Corporation Comet Lake-U v1 4c Host Bridge/DRAM Controller (rev 0c)
00:02.0 VGA compatible controller: Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 0c)
00:1c.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #5 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #9 (rev f0)
```

**Comment by surfaceflinger** [comment]
`rm -rf ~/.config/google-chrome/Default/GPUCache/`

#242113

**Comment by Djabx** [comment]
@surfaceflinger Thanks !
