### ISSUE TITLE
Build failure: python3.10-maxminddb-2.4.0

### ISSUE THREAD

**Issue by e-minguez** [NixOS/nixpkgs#243998]
### Steps To Reproduce

1. Try to install ansible on OSX 13.4 (via fleek)

### Build log

https://gist.github.com/e-minguez/b8ad1a50d67fc07ce6cf52d250fd1bc3

### Additional context

I'm not using nix vanilla but fleek

### Notify maintainers

@fabaff

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/b63zicy7mkwlp4vmca056kawsrmxfr36-source`
```

**Comment by kciredor** [comment]
Just hit this one too, on aarch64-darwin.

**Comment by duckpuppy** [comment]
I have this issue on x86_64-darwin as well, so it's not architecture specific.

**Comment by tjni** [comment]
@reckenrode I remember you investigated this and had a fix in mind. Just putting this issue on your radar.

**Comment by reckenrode** [comment]
I do. The multiprocessing tests don’t work on Darwin. I was going to open a PR after my clang 16 test flake finished building, but I’ll cherry-pick and open one now since the issue is affecting users.
