### ISSUE TITLE
Initrd-SSH and Host Key generation

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#24399]
Currently initrd SSH requires you to specify your own host key. But the SSHD service auto generates the host key and there's no option to specify your own host key.

Should these to be aligned with each other, so either we always can set our own host key for both services, or both are autogenerated, and preferably they should be autogenerated to the same key right?

There's a complication in that the autogeneration is done through a service: https://github.com/NixOS/nixpkgs/blob/release-17.03/nixos/modules/services/networking/ssh/sshd.nix#L178-L194 While the initrd SSH keys needs to be generated immediately and placed into the initrd.

The service however just works as a one-shot service that checks if the key is already created, and if not, creates it.

To align the both (and use the same host key), perhaps activationScripts can be used.

**Comment by abbradar** [comment]
The same host key would be a bad idea now because of no private Nix files -- to have the (private)key in initrd it needs to be in Nix store so it becomes globally accessible. Hence a warning in option's description; for now you'd be better with a different key.

**Comment by CMCDragonkai** [comment]
Could we use this: `  boot.initrd.prepend = ["${/initrdsshkey.cpio.gz}"];`? Would that allow us to store something into the initrd without exposing it to the global nix store? If this is possible, it could be done via a systemd one shot service similar to how sshd autogenerates the host key.
