### ISSUE TITLE
Missing Haskell dependency when installing a haskellPackage

### ISSUE THREAD

**Issue by adelbertc** [NixOS/nixpkgs#24398]
## Issue description
When installing [sarsi](https://hackage.haskell.org/package/sarsi) via `nix-env -f "<nixpkgs>" -iA haskellPackages.sarsi` it eventually terminates with

```
Configuring msgpack-1.0.0...
Setup: Encountered missing dependencies:
binary ==0.7.*
builder for ‘/nix/store/1bjf7530f09z1h4kc6ah4kfpb9yjfbjw-msgpack-1.0.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ry54z948rm02yvr55904wqflqh2b68pi-sarsi-0.0.3.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ry54z948rm02yvr55904wqflqh2b68pi-sarsi-0.0.3.0.drv’ failed
```

I thought Nixpkgs automatically had all Hackage dependencies, so I'm a bit confused at the error message.

### Steps to reproduce
`nix-env -f "<nixpkgs>" -iA haskellPackages.sarsi`

## Technical details

* System: Mac OS X El Capitan 10.11.6
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre104446.09c91f5

cc @peti

**Comment by peti** [comment]
Nixpkgs has `binary`, of course, but the version we use is far newer than `== 0.7.*`, which is what `msgpack` requires. You should probably contact the author of `msgpack` and ask them to release an update of his package that correctly deals with current versions of `binary`.

**Comment by adelbertc** [comment]
Hm right, [`msgpack`](https://hackage.haskell.org/package/msgpack) wants `binary (==0.7.*)` whereas the latest [`binary`](https://hackage.haskell.org/package/binary) is 0.9.0.0.

That being said, does Nixpkgs only ever keep the latest version (at the time of the channel update) of a Haskell library around? Or equivalently, does that mean any Haskell package that currently is installable through Nixpkgs that uses binary is compatible with binary 0.9.0.0?

**Comment by peti** [comment]
Nixpkgs follows [Stackage LTS 8.x](https://www.stackage.org/lts) to choose the versions we distribute by default. Oftentimes, that is the respective latest version but not always. In case of `binary`, the version used during builds is determined by the GHC version because `binary` is a core library that cannot easily be replaced in user builds.

**Comment by adelbertc** [comment]
Ahhh gotcha, thank you!

**Comment by bbarker** [comment]
@peti How does one get around this sort if issue:

> the version used during builds is determined by the GHC version because binary is a core library that cannot easily be replaced in user builds.

I assume that's what is happening for me. On nixpkgs revision 6a3f5bcb061e1822f50e299f5616a0731636e4e7 we [can see ](https://raw.githubusercontent.com/NixOS/nixpkgs/6a3f5bcb061e1822f50e299f5616a0731636e4e7/pkgs/development/haskell-modules/hackage-packages.nix) that the versions of `base-compat-batteries` and `bifunctors` seem to agree with what the error message says, yet it still errors:

```
Warning: base-compat-batteries.cabal: Unknown fields: build-tool-depends (line
224)
Fields allowed in this section:
type, main-is, test-module, buildable, build-tools, build-depends,
cpp-options, cc-options, ld-options, pkgconfig-depends, frameworks,
extra-framework-dirs, c-sources, js-sources, default-language,
other-languages, default-extensions, other-extensions, extensions,
extra-libraries, extra-ghci-libraries, extra-lib-dirs, includes,
install-includes, include-dirs, hs-source-dirs, other-modules,
ghc-prof-options, ghcjs-prof-options, ghc-shared-options,
ghcjs-shared-options, ghc-options, ghcjs-options, jhc-options,
hugs-options, nhc98-options
Configuring base-compat-batteries-0.10.1...
Setup: Encountered missing dependencies:
bifunctors >=5.5.2 && <5.6
```

Note that I'm using ghc8.0.2 (`ghc802`) in this build.

**Comment by peti** [comment]
ghc-8.0.2 has been dropped from Nixpkgs a while ago, so I can't say much about that. I know that `haskell.packages.ghc822.base-compat-batteries` builds fine, though.

**Comment by bbarker** [comment]
@peti - thanks for the feedback - unfortunately, i'm not sure I have much flexibility - this is to build https://github.com/google/codeworld, which is a modified version of Haskell for teaching (mainly aimed at kids), and relies on a specific version of the haskell compiler that is patched.
