### ISSUE TITLE
ghc 9.6 - foundation patch doesn't compile 

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#243984]
### Describe the bug
The patch [here](https://github.com/NixOS/nixpkgs/blob/79e00681e2f273a68af5dd55c8ea819706a69b9a/pkgs/development/haskell-modules/configuration-ghc-9.6.x.nix#L127C4-L127C62) apparently is incompatible with the version of `foundation` pulled in by `hackage`. 

### Steps To Reproduce

- depend on `foundation`

**Comment by MangoIV** [comment]
needs label "haskell"

**Comment by teto** [comment]
removing the patch works fine IIRC

**Comment by MangoIV** [comment]
So it should be removed because it’s applied specifically for 9.6

**Comment by sternenseemann** [comment]
If desparation sets in you can try fast tracking 974363bfc16a9979b3e718357f269d520ab20957 from #240387—or even better help out with that PR in order to get it merged soon.

**Comment by MangoIV** [comment]
Nono patches = [] worked for me very well for foundation so this is just to track this is broken atm

**Comment by JonathanLorimer** [comment]
@MangoIV How do you override patches and set them `[]` I am only seeing `appendPatch` in the regular functions, and this is not working for me:
```nix
          foundation = overrideCabal (drv: { patches = []; }) (hprev.foundation {});
```

**Comment by MangoIV** [comment]
this should do it. perhaps you don't apply it properly.

**Comment by JonathanLorimer** [comment]
I get this error:
```
error: value is a function while a set was expected

       at /nix/store/gds8ccai5palk10iaa3604z7pjmczjym-source/pkgs/development/haskell-modules/lib/compose.nix:38:28:

           37|    */
           38|   overrideCabal = f: drv: (drv.override (args: args // {
             |                            ^
           39|     mkDerivation = drv: (args.mkDerivation drv).override f;
(use '--show-trace' to show detailed location information)
```

**Comment by JonathanLorimer** [comment]
argggg, the version exported from lib.nix has the args reversed, thats annoying.

**Comment by MangoIV** [comment]
You need the ones from the compose attr set. This is poorly documented

**Comment by MangoIV** [comment]
Thanks @sternenseemann
