### ISSUE TITLE
stdenv: assertion '(final).hasSharedLibraries' failed

### ISSUE THREAD

**Issue by vkryachko** [NixOS/nixpkgs#244045]
### Describe the bug
Nix fails to build `nix` on nixpkgs master.

### Steps To Reproduce
1. on unstable channel
2. nix-channel --update
3. This works: `nix-build -E 'with import <nixpkgs> {}; nix'`
4. This fails: `nix-build -E 'with import <nixpkgs> {}; let unused = {whatever.extensions =[];}; in nix' --show-trace`
5. Assertion failure:
```console
error: assertion '(final).hasSharedLibraries' failed

       at /nix/store/v63vjk8lz2fsj52qkfgbbw1mbgplcdmc-nixpkgs/nixpkgs/lib/systems/default.nix:89:25:

           88|       extensions = rec {
           89|         sharedLibrary = assert final.hasSharedLibraries;
             |                         ^
           90|           /**/ if final.isDarwin  then ".dylib"
```

### Expected behavior
Both invocations should succeed as they are isomorphic, i.e. `4.` has an unused let binding that causes `nix` to fail.

### Additional context

Looks like this PR may have introduced the assert that causes the problem #238154 , [commit](https://github.com/NixOS/nixpkgs/commit/6980e6b35aacccd4e75a76a384f9dec30f31fa55)

After some investigation a colleague pointed out that the issue may have to do with the instability of attrset comparison due to laziness in nix, comparison happens here https://github.com/NixOS/nixpkgs/blob/5136088b472fb723588f62df6f59467d36b0e2c2/pkgs/stdenv/booter.nix#L105-L108

and looks like invocation in `4.` somehow cause a different evaluation order of attrset attribute comparison:
- if isStatic is compared first we don't see the assert
- If extensions compares first we stumble on the assert and fail.

```console
nix-repl> pkgs.stdenv.hostPlatform.extensions
{ executable = ""; library = ".so"; sharedLibrary = ".so"; staticLibrary = ".a"; }

nix-repl> pkgsStatic.stdenv.hostPlatform.extensions
{ executable = ""; library = ".a"; sharedLibrary = «error: error: assertion '(final).hasSharedLibraries' failed

       at /nix/store/v63vjk8lz2fsj52qkfgbbw1mbgplcdmc-nixpkgs/nixpkgs/lib/systems/default.nix:89:25:

           88|       extensions = rec {
           89|         sharedLibrary = assert final.hasSharedLibraries;
             |                         ^
           90|           /**/ if final.isDarwin  then ".dylib"»; staticLibrary = ".a"; }
```

### Notify maintainers

@amjoseph-nixpkgs who added the assert that fails
@edolstra @lovesegfault @Artturin nix package maintainers

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.25-1rodete1-amd64`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by trofi** [comment]
With something like https://github.com/NixOS/nix/pull/8711 we can deterministically crash the eval:

```
$ NIX_VALIDATE_EVAL_NONDETERMINISM=1 nix-instantiate -E 'with import <nixpkgs> {}; nix'
error:
...
       error: assertion '(final).hasSharedLibraries' failed
```

**Comment by Artturin** [comment]
Same issue in https://github.com/NixOS/nix/issues/8701

**Comment by amjoseph-nixpkgs** [comment]
This was my fault.

The fix is: https://github.com/NixOS/nixpkgs/pull/244118

Unfortunately we can't provide useful error messages when people use sub-attributes of `{host,target,build}Platform`, because it is expected that you can compare two `*Platform` attrsets using `==`, which will force the `throw "error message"`.

We should probably move anything fallible (like `extensions.sharedLibrary`) out of these `*Platform` attrsets, so we can provide useful error messages instead of just returning `null`.
