### ISSUE TITLE
MySQL breaks when dataDir is set

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#24400]
## Issue description

If `dataDir` is specified for `services.mysql`, MySQL system service won't start and gives an error:

```
mysql_install_db: [ERROR] unknown variable 'pid-file=/run/mysqld/mysqld.pid'
[ERROR]   Unrecognized options
mysql.service: Control process exited, code=exited status=1
```

(I don't understand why it complains about `pid-file` option when setting `dataDir`.)

### Steps to reproduce

Add this to the nix configuration:
```
services.mysql = {
  enable = true;
  package = pkgs.mysql57;
  dataDir = "/var/db/mysql";
};
```

Run `nixos-rebuild switch` and you'll see the error on `mysql.service` failing.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
17.09pre104410.65593e6 (Hummingbird)
```

* Nix version: (run `nix-env --version`)

```
# nix-env --version
nix-env (Nix) 1.11.8
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09pre104410.65593e6"
```

**Comment by copumpkin** [comment]
Looks like [this snippet](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/mysql.nix#L195-L200) is the culprit:

```bash
            if ! test -e ${cfg.dataDir}/mysql; then
                mkdir -m 0700 -p ${cfg.dataDir}
                chown -R ${cfg.user} ${cfg.dataDir}
                ${mysql}/bin/mysql_install_db ${mysqldOptions}
                touch /tmp/mysql_init
            fi
```

So basically, if the `dataDir` isn't already set up it calls `mysql_install_db` with the same command-line options as it passes to the main daemon (which makes little sense to me), so `mysql_install_db` gets passed `--pid-file` which breaks it.

**Comment by grahamc** [comment]
I think one of these is a dupe: https://github.com/NixOS/nixpkgs/issues/25418 pid-file changed IIRC.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by aanderse** [comment]
This was fixed several releases ago.
