### ISSUE TITLE
linux gasket kernel module for google coral tpu devices

### ISSUE THREAD

**Issue by evilbulgarian** [NixOS/nixpkgs#244009]
### Describe the bug
There is a issue when trying to add this ( https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/os-specific/linux/gasket/default.nix#L29 ) to the boot.extraModulePackages list. As noted by clever in irc "all out-of-tree modules should be in packagesFor, which lets you just boot.extraModulePackages = [config.boot.kernelPackages.gasket ];"

### Steps To Reproduce
boot.extraModulePackages = [ (pkgs.gasket.override { kernel = config.boot.kernelPackages.kernel; }) ]; is what is needed but  boot.extraModulePackages = [config.boot.kernelPackages.gasket ]; is the expected.

### Expected behavior
boot.extraModulePackages = [config.boot.kernelPackages.gasket ]; in the hardware-configuration.nix

### Additional context
This is needed to get the gasket kernel module added so that /dev/apex_X devices show up under /dev/

### Notify maintainers
@kylehendricks 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by kylehendricks** [comment]
I think [this PR](https://github.com/NixOS/nixpkgs/pull/232136) is supposed to solve this?  I just don't know how to get it unstuck.

**Comment by kylehendricks** [comment]
I used this for a work-around:
```
boot.extraModulePackages = [                                                                                                                                            
    (config.boot.kernelPackages.callPackage (builtins.fetchurl {                                                                                                        
        url = "https://github.com/NixOS/nixpkgs/raw/eb0f101b8aa0b704e103164699350fd3914c298c/pkgs/os-specific/linux/gasket/default.nix";                                
        sha256 = "0hi6cnb36qqwnspb2r94pkw99zn7b22b7hxl70c6iwb0hcg7j0bz";                                                                                                
        }) {})                                                                                                                                                          
];
```

**Comment by jcollie** [comment]
There's a new patch that allows building with 6.4 kernels as well. https://github.com/google/gasket-driver/commit/8aca235839fb5ba4d5ef6cfbe783837667e381f1
