### ISSUE TITLE
konsole opens links with google chrome even when the default browser is firefox

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#24404]
## Issue description

when opening a link in konsole, its opened in google chrome, even if firefox is the default browser

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by mmahut** [comment]
I cannot reproduce this, is this still an issue?

**Comment by RonnyPfannschmidt** [comment]
Haven't been using nixos since a year
