### ISSUE TITLE
syncthing with fixed key sets wrong permissions on key file

### ISSUE THREAD

**Issue by wuyoli** [NixOS/nixpkgs#244059]
### Describe the bug
I'm trying to install syncthing with a fixed key, which is set via sops-nix, but the service fails on startup with the error
```
WARNING: Failed to load/generate certificate: save key: open /var/lib/syncthing/.config/syncthing/key.pem: permission denied
```
### Steps To Reproduce
1. set following options:
```
{
  services.syncthing = {
    enable = true;
    key = "/run/secrets/syncthing_key"; # use key which was put there by sops-nix

    devices.mobilePhone = { ... };
    folders.sync = { ... };
  };
  users.users.syncthing.extraGroups = [ config.users.groups.keys.name ]; # allow the syncthing user to read the keys
}
```
2. rebuild
3. The syncthing service fails with the following error:
```
WARNING: Failed to load/generate certificate: save key: open /var/lib/syncthing/.config/syncthing/key.pem: permission denied
```
bacause the pre-start-script contains 
```
install -Dm400 -o syncthing -g syncthing /run/secrets/syncthing_key /var/lib/syncthing/.config/syncthing/key.pem
```
which does not allow the syncthing user to overwrite this file when the unit is started again.

### Expected behavior
the service takes the key and starts

### Notify maintainers
none set

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.O
```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230711.f240619`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by universenox** [comment]
I encountered this as well. You need to provide both `key` and `cert` else syncthing just attempts to generate its own.

**Comment by wuyoli** [comment]
I had another look at it in my configuration, it works now (I believe my mistake was that i set key, cert AND configDir, though I'm not sure about this)

**Comment by Sveske-Juice** [comment]
It seems that i am running into the same issue. Whenever i specify `key` and `cert` syncthing crashes. For some reason the syncthing-copy-keys script is installing the files with read-only (400) permissions. Wasn't this fixed to install with permission 600? The file paths are supplied with sops-nix - my config:
```nix
sops.secrets."syncthing/certpem" = {
  owner = config.services.syncthing.user;
  group = config.services.syncthing.group;
};

sops.secrets."syncthing/keypem" = {
  owner = config.services.syncthing.user;
  group = config.services.syncthing.group;
};
services.syncthing = {
    enable = true;
    openDefaultPorts = true;
    guiAddress = "127.0.0.1:${toString guiPort}";
    overrideDevices = true;
    overrideFolders = true;
    cert = config.sops.secrets."syncthing/certpem".path;
    key = config.sops.secrets."syncthing/keypem".path;
}
```

The output of `cat /nix/store/b9idb3ww2prr3qyjw75nxwbxx7z82wkd-syncthing-copy-keys` outputs:
```sh
#! /nix/store/1q9lw4r2mbap8rsr8cja46nap6wvrw2p-bash-interactive-5.2p37/bin/bash
install -dm700 -o syncthing -g syncthing /var/lib/syncthing/.config/syncthing
install -Dm400 -o syncthing -g syncthing /run/secrets/syncthing/certpem /var/lib/syncthing/.config/syncthing/cert.pem

install -Dm400 -o syncthing -g syncthing /run/secrets/syncthing/keypem /var/lib/syncthing/.config/syncthing/key.pe
```

My `nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.13.7-zen1, NixOS, 25.05 (Warbler), 25.05.20250515.e06158e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - nixpkgs: `/nix/store/126fp22lvqmnfv1p290vcpmbf8yab4a5-source
```
