### ISSUE TITLE
Python3Packages.pyudev is broken (no module named pytest)

### ISSUE THREAD

**Issue by xwvvvvwx** [NixOS/nixpkgs#24415]
## Issue description

pyudev does not install as pytest seems to be missing when executing the tests.

output [here](https://gist.github.com/xwvvvvwx/3e9aba798b8bd5463b4c3fb5d4f05a6b)

### Steps to reproduce

1. `nix-shell -p python3Packages.pyudev`

## Technical details

* System: NixOS: `17.09pre102667.2839b10 (Hummingbird)`
* Nix version: `1.11.7`
* Nixpkgs version: `17.09pre104410.65593e6`

**Comment by FRidh** [comment]
Fixed with 078412521e4fbbec261b3a1a0a8296bfad0a47c3
