### ISSUE TITLE
gnome-logs-3.20.1 fails to start with error Settings schema 'org.gnome.desktop.interface' is not installed

### ISSUE THREAD

**Issue by Reilithion** [NixOS/nixpkgs#24419]
## Issue description

Attempting to run gnome-logs while not in the GNOME desktop environment results in the error:

(gnome-logs:25409): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' is not installed

Simply installing the package gsettings-desktop-schemas-3.20.0 is not sufficient to resolve this error.

### Steps to reproduce

Install gnome-logs with nix-env -i gnome-logs. Do not install GNOME (I am using xfce4 + xmonad). Try to run gnome-logs.

## Technical details

* System: NixOS 16.09.1799.058983a (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1799.058983a

**Comment by jtojnar** [comment]
This was fixed in #28053
