### ISSUE TITLE
Update request: tenacity 1.3-beta2 → 1.3.1

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#244229]
- Package name: tenacity
- Latest released version: 1.3.1

- Current version on the unstable channel: 1.3-beta2
- Current version on the stable/release channel: 1.3-beta2

So, wanted to use tenacity because _i'm not letting my grudge against muse go, sorry_, when i noticed something odd: the version in nixpkgs is older than the latest release.

appears there's no mechanism to alert maintainers of updates for this automatically so here's an issue i guess

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@IreneKnapp @lheckemann 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by IreneKnapp** [comment]
oh hey yep, that's me! thanks for the heads up, I'll get on that

**Comment by IreneKnapp** [comment]
(and I feel similarly about the whole audacity mess, it's why I packaged tenacity. I think this will be the first time there's been a proper stable tenacity release in nixpkgs, I'm looking forward to it.)
