### ISSUE TITLE
Digikam 5.4.0 can't thumbnail/play videos

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#24426]
## Issue description
Following https://bugs.kde.org/show_bug.cgi?id=366387 it seems that QtAv is required for Digikam to thumbnail/play videos. Unfortunately, https://github.com/wang-bin/QtAV isn't yet packaged.

### Steps to reproduce
Add a video to an album and view it with digikam. You'll get something like this:

digikam.dimg: "/z/media/Event|Ägyptenreise Feb 2014-2/GOPR3239.MP4"  : QIMAGE file identified
digikam.dimg.qimage: Can not load " "/z/media/Event|Ägyptenreise Feb 2014-2/GOPR3239.MP4" " using DImg::QImageLoader!
digikam.general: mimetype =  ""  ext =  "MP4"
digikam.general: Cannot create thumbnail for  "/z/media/Event|Ägyptenreise Feb 2014-2/GOPR3239.MP4"
digikam.general: Thumbnail is null for  "/z/media/Event|Ägyptenreise Feb 2014-2/GOPR3239.MP4"
digikam.metaengine: Cannot load metadata from file   (Error # 11 :  /z/media/Event|Ägyptenreise Feb 2014-2/GOPR3240.MP4: The file contains data of an unknown image type

## Technical details

* System: 17.03beta773.38b2e27 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03beta773.38b2e27

**Comment by jraygauthier** [comment]
@clefru : did you start package qtav yet?

**Comment by jraygauthier** [comment]
I may already have something for the packaging of libqtav. Still need some testing.

**Comment by clefru** [comment]
@jraygauthier: Sorry, I failed to see your message. I started packaging and noticed that I have very little clue on the cmake/qmake build process. Thanks for taking that of my hands.

May I offer you a small tip in Bitcoin for saving me a couple of hours? If yes, leave your address here :)

**Comment by jraygauthier** [comment]
@clefru: my pleasure. Here's the address: `1v3UXrPFPSy1cPq5xgJnxswd7pfKgwufh`.

**Comment by clefru** [comment]
Thanks again. Works for me (video play & thumbnails). Enjoy your BTC :)
