### ISSUE TITLE
znapzend service: reload is broken

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#24438]
## Issue description

The znapzend service's reload is broken.

```
Mar 29 09:25:22 dermetfan-server systemd[1]: Reloading ZnapZend - ZFS Backup System.
Mar 29 09:25:22 dermetfan-server znapzend-reload[23060]: /nix/store/xw5wryif0b6syfd2bj48cnh7bcm7dyrf-unit-script/bin/znapzend-reload: line 2: /bin/kill: No such file or directory
Mar 29 09:25:22 dermetfan-server systemd[1]: znapzend.service: Control process exited, code=exited status=127
Mar 29 09:25:22 dermetfan-server systemd[1]: Reload failed for ZnapZend - ZFS Backup System.
```

The [fix](https://github.com/dermetfan/nixpkgs/commit/47cf1317892abbccb92b8758f92aebf76117ba00) is obvious, but now znapzend seems to receive a SIGTERM instead of the sent SIGHUP:

```
Mar 29 10:44:36 dermetfan systemd[1]: Reloading ZnapZend - ZFS Backup System.
Mar 29 10:44:36 dermetfan znapzend[10356]: SIGTERM received.
Mar 29 10:44:36 dermetfan znapzend[10356]: terminating znapzend (PID=10356) ...
Mar 29 10:44:37 dermetfan znapzend[10356]: znapzend (PID=10356) terminated.
Mar 29 10:44:37 dermetfan systemd[1]: Reloaded ZnapZend - ZFS Backup System.
```

After taking a look at `systemctl status znapzend` I noticed that `$MAINPID` is not znapzend itself:

```
● znapzend.service - ZnapZend - ZFS Backup System
   Loaded: loaded (/nix/store/yq8xm7wm8q1m3zhvf3cl8axdc4qk3l87-unit-znapzend.service/znapzend
   Active: active (running) since Wed 2017-03-29 23:35:18 CEST; 4s ago
 Main PID: 6749 (znapzend-start)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/znapzend.service
           ├─6749 /nix/store/010yd8jls8w4vcnql4zhjbnyp2yay5pl-bash-4.4-p5/bin/bash -e /nix/st
           └─6751 /nix/store/pbs5sfnp9bfv27vz9m7h64w3zgkavfqd-perl-5.22.2/bin/perl -I/nix/sto

Mar 29 23:35:18 dermetfan znapzend[6751]: refreshing backup plans...
Mar 29 23:35:18 dermetfan znapzend-start[6749]: cannot open 'tank/data': dataset does not exist
...
```

The main PID is associated with `znapzend-start` instead of `znapzend`. My guess it that when SIGHUP is sent to `znapzend-start` (which is a shell), it sends SIGTERM to all its children, the only one being `znapzend` (the supposed `$MAINPID`).

Looking at the module source, I saw the author used `script` instead of `serviceConfig.ExecStart` and did not start znapzend as daemon to prevent this from happening. `script`'s description says: `Shell commands executed as the service's main process.`.

~~Therefore I conclude that `systemd.services.<name>.script` may be broken.~~
_The script forks, see #25009._

### Steps to reproduce

```sh
systemctl reload znapzend
```

## Technical details

* System: `17.09.git.8b512b1 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `"17.09pre102667.2839b10"`

**Comment by joachifm** [comment]
cc @otwieracz

**Comment by johnramsden** [comment]
Not sure if this is related.

I have enabled znapzend but the service isn't being started.

```
systemctl status znapzend
● znapzend.service - ZnapZend - ZFS Backup System
   Loaded: loaded (/nix/store/3bmsi4s20b46n61i0n8mjzjm3jsin3b6-unit-znapzend.service/znapzend.service; link
   Active: inactive (dead)
```

Shouldn't it be started and enabled after setting `znapzend.enable = true;`?

**Comment by dermetfan** [comment]
Yes, looks like you're experiencing the same problem. When you activate the new configuration the service is started and then reloaded, killing it.
