### ISSUE TITLE
Adding fvwm to the list of available window managers. [needs attention]

### ISSUE THREAD

**Issue by noisecrew** [NixOS/nixpkgs#24435]
Hello;
trying to add 
```
    xserver.desktopManager.default = "none";
    xserver.desktopManager.fvwm.enable = false;
    xserver.windowManager.default = "fvwm";
    xserver.windowManager.fvwm.enable = true;

```

causes to return errors about the service doesn't exist. So please add them.
this option is needed to set fvwm for display-managers like lightdm or sddm.
Thanks

* Linux noisecrew 4.9.17 #1-NixOS SMP Wed Mar 22 11:44:07 UTC 2017 x86_64 GNU/Linux

* nix-env (Nix) 1.11.8

**Comment by edanaher** [comment]
FYI, you can do this yourself (as I have been):
```
    services.xserver.desktopManager.default = "fvwm";
    services.xserver.desktopManager.session =
      [ { manage = "desktop";
          name = "fvwm";
          start = ''
            ${fvwm}/bin/fvwm &
            waitPID=$!
          '';
        }
      ];
```
However, now that I'm not just getting started with Nix, I should really commit that...  I'll add it as my next nixpkgs TODO.

**Comment by noisecrew** [comment]
rror: undefined variable ‘fvwm’ at /etc/nixos/services.nix:20:15
(use ‘--show-trace’ to show detailed location information)
building Nix...
error: undefined variable ‘fvwm’ at /etc/nixos/services.nix:20:15
(use ‘--show-trace’ to show detailed location information)
building the system configuration...
error: undefined variable ‘fvwm’ at /etc/nixos/services.nix:20:15
(use ‘--show-trace’ to show detailed location information)

**Comment by edanaher** [comment]
Ah; I had a bit of other infrastructure that I filtered out.  Try using ${pkgs.fvwm} instead?

**Comment by noisecrew** [comment]
wouldn't be better to add it to nixos tree.

**Comment by noisecrew** [comment]
cc @ttuegel

**Comment by lheckemann** [comment]
Given that the module has now been added and is available in nixos-unstable, I think this issue can be closed?
