### ISSUE TITLE
SDDM KDE Plasma 5 theme

### ISSUE THREAD

**Issue by noisecrew** [NixOS/nixpkgs#24436]
I wanted to know if it is possible (and HOW? if it is) to have kde5 plasma theme for sddm without installing the whole kde5.
 

> 
>     Linux noisecrew 4.9.17 #1-NixOS SMP Wed Mar 22 11:44:07 UTC 2017 x86_64 GNU/Linux
> 
>     nix-env (Nix) 1.11.8

**Comment by globin** [comment]
@ttuegel

**Comment by ttuegel** [comment]
As per [`nixos/modules/services/x11/desktop-managers/plasma5.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/plasma5.nix#L211), setting
```.nix
{
  services.xserver.displayManager.sddm.package = pkgs.sddmPlasma5;
}
```
in your `/etc/nixos/configuration.nix` will do it. The Plasma 5 theme has many dependencies, so do not be alarmed if this requires you to download many new packages.
