### ISSUE TITLE
Package request: qpsolvers

### ISSUE THREAD

**Issue by alin742** [NixOS/nixpkgs#244480]
**Project description**

qpsolvers is python library for solving quadratic programming problems. It contains wrappers for multiple solvers like osqp, cvxopt, quadprog and much more.

**Metadata**

* homepage URL: https://github.com/qpsolvers/qpsolvers
* source URL: https://github.com/qpsolvers/qpsolvers
* license: LGPLv3
* platforms: platform independent (python3.10)

**Comment by renesat** [comment]
This package wants new version of `scs` and new package - `daqp`. I will try add PR today, but now you can use my NUR repo if you want: https://github.com/renesat/nur-renesat 🙂
