### ISSUE TITLE
Package request: HybridBar

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#244433]
**Project description**

A simple status bar focused on wlroots Wayland compositors, usable with KDE and tiling window managers like Hyprland.

**Metadata**

* homepage URL:  https://github.com/vars1ty/HybridBar
* source URL:  https://github.com/vars1ty/HybridBar
* license: mit
* platforms: linux

**Comment by Aleksanaa** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/195684
