### ISSUE TITLE
cudaPackages_10_1.cudatoolkit: postFixup broken

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#244429]
### Describe the bug

```
$ nix-build -A python3Packages.caffeWithCuda
...
> patchelf: getting info about '/nix/store/ixjdw1wbz64f9wk96md1xd7b60xlv2ik-cudatoolkit-10.1.243/lib64/libnvrtc.so': No such file or directory
...
For full logs, run 'nix log /nix/store/n1girlx7gmxmdfks834gp0zkxsxn6rlx-cudatoolkit-10.1.243.drv'
```

Cf. https://github.com/NixOS/nixpkgs/blob/d3185b8a568d81a4dab14f9e19a632fc857bd49f/pkgs/development/compilers/cudatoolkit/common.nix#L181

### Possible solution

```
while IFS= read ... ; do
  patchelf ...
done < <(find ...)
```

**Comment by samuela** [comment]
> Possible solution
>
>while IFS= read ... ; do
>  patchelf ...
>done < <(find ...)

is there a reason to prefer this over an `optionalString` based on the major cuda version?

**Comment by SomeoneSerge** [comment]
> is there a reason to prefer this over an optionalString based on the major cuda version?

I suppose it's ok for upstream to move files around between the releases and we don't really have to watch them all that closely.

> The error in the terminal (while blender is still running) is of the same kind as SomeoneSerge described.

Close but not exactly. The original issue was about `cudatoolkit`'s autopatchelf phase failing. Looks like in your case cudatoolkit is "built" without failures (I'll test and reopen the issue if that's not the case), but the blender plug-in fails at runtime.

I think you should file a new issue and link your original comment. It would be helpful if you ran the same thing as `LD_DEBUG=libs blender ...` and posted the results, so we can see which library is trying (and failing) to load `libnvrtc-builtins.so`

**Comment by SomeoneSerge** [comment]
> Just so you know, LuxCoreRender only runs on old versions of Blender – so fixing this issue would be helpful. (And [the package for that project was removed](https://github.com/NixOS/nixpkgs/commit/c8935386b3b7b8fbd48c82045d6a0af8106b509a) a few months ago.)

Jaja, maybe you could re-introduce the package (if you have time to maintain it): https://github.com/LuxCoreRender/LuxCore/releases/tag/luxcorerender_v2.8alpha1
