### ISSUE TITLE
Musescore 4.1.0 segfault on launch

### ISSUE THREAD

**Issue by huantianad** [NixOS/nixpkgs#244409]
### Describe the bug
Running musescore 4.1.0 from nixpkgs master causes a segfault on launch.

### Steps To Reproduce
1. Run musescore via `nix run nixpkgs/master#musescore`
2. Application starts to launch, with a small window appearing for a brief second, before crashing.

### Log file
```
nix run nixpkgs/master#musescore
13:51:44.623 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/huantian/.local/share/MuseScore/MuseScore4/logs/MuseScore_230719_135144.log
13:51:44.623 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.1.0, build number  ===
13:51:44.624 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
13:51:44.624 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
13:51:44.624 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
13:51:44.624 | INFO  | 139704377599680 | IpcServer  | listen: id: "312d7b4729a348df8a494861a9a2e50a" 
13:51:44.639 | WARN  | main_thread | DiagnosticsModule | onInit: crash handling disabled
13:51:44.657 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: /home/huantian/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
13:51:44.657 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
13:51:44.657 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so
13:51:44.657 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
13:51:44.657 | WARN  | main_thread | Qt         | QIODevice::read (QFile, "/home/huantian/.local/share/MuseScore/MuseScore4/shortcuts.xml"): device not open
13:51:44.658 | WARN  | main_thread | Qt         | QIODevice::read (QFile, "/home/huantian/.local/share/MuseScore/MuseScore4/midi_mappings.xml"): device not open
13:51:44.666 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/huantian/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
13:51:44.666 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/huantian/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
13:51:44.844 | ERROR | main_thread | PluginsConfiguration | updatePluginsConfiguration: [401] The file does not exist
[1]    50556 segmentation fault (core dumped)  nix run nixpkgs/master#musescore
```

### Notify maintainers
@doronbehar @turion @vandenoever 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230718.684c17c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - channels(huantian): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`

```

**Comment by turion** [comment]
I can reproduce. I wonder whether this is only when starting it via the shell. If no, then we need to bisect, since https://github.com/NixOS/nixpkgs/pull/243298 seems to have worked for multiple people.

**Comment by turion** [comment]
The integration test succeeded, https://github.com/NixOS/nixpkgs/runs/15106442611. Also, `nix build .#nixosTests.musescore` succeeds for me on master. It produces e.g. the following screenshot:

![image](https://github.com/NixOS/nixpkgs/assets/303489/99ef0378-2109-4b52-b860-65e1d038b004)

So this must be because of starting it in a shell. Probably, Qt plugin resolution or something like that fails when starting in a shell.

**Comment by doronbehar** [comment]
I too can't reproduce. Sometimes with these Qt programs, you have to delete your ~/.config/MuseScore` or delete your `~/.cache/MusesScore` directories, because some of your previous settings are not compatible with the new version, and upstream has unfortunately failed to program MuseScore to detect those incompatibilities correctly and handle them gracefully.

**Comment by turion** [comment]
>  Sometimes with these Qt programs, you have to delete your ~/.config/MuseScore or delete your ~/.cache/MusesScore directories

I tried to move these directiories away, and also `~/.local/share/MuseScore`, but still I have the crash.

> I can't reproduce. 

Can you not reproduce from a shell??

**Comment by doronbehar** [comment]
> Can you not reproduce from a shell??

I ran `nix run nixpkgs/master#musescore` from a shell.

**Comment by turion** [comment]
Ok, apologies, then I agree, the only way I can imagine then is some state in `~`.

**Comment by huantianad** [comment]
Unfortunately, removing those directories did not fix the crash for me.
One thing to note is that I hear a buzzing sound in my speakers for ~1s before crashing. Unsure if that is relevant info.

Could the issue be some incompatibility with some system configuration?

**Comment by doronbehar** [comment]
I'd contact upstream about this issue.

**Comment by huantianad** [comment]
Let me know if there's any other info that should be included in the issue :+1:

**Comment by doronbehar** [comment]
One more thing you can do which might help them, is to build `musescore` from nixpkgs' source with:

```diff
diff --git i/pkgs/applications/audio/musescore/default.nix w/pkgs/applications/audio/musescore/default.nix
index fa166051db6..da39772598d 100644
--- i/pkgs/applications/audio/musescore/default.nix
+++ w/pkgs/applications/audio/musescore/default.nix
@@ -80,6 +80,7 @@ in stdenv'.mkDerivation rec {
     # Don't bundle qt qml files, relevant really only for darwin, but we set
     # this for all platforms anyway.
     "-DMUE_COMPILE_INSTALL_QTQML_FILES=OFF"
+    "-DCMAKE_BUILD_TYPE=Debug"
   ];
 
   qtWrapperArgs = [
```

And then after it crashes, you'll be able to share with upstream the backtrace of of the crash, via `coredumpctl debug -1`. Then in that prompt, running `backtrace` will print all the backtrace of all functions from which the crash started.

**Comment by huantianad** [comment]
Posted the backtrace and also confirmed it crashes on my laptop as well, also running nixos with kde but on wayland.

**Comment by turion** [comment]
Can you create a new user and try for that one?

**Comment by doronbehar** [comment]
> Posted the backtrace and also confirmed it crashes on my laptop as well, also running nixos with kde but on wayland.

Do you set `QT_QPA_PLATFORM` in your environment? Musescore is wrapped with `--set-default QT_QPA_PLATFORM xcb`.

**Comment by turion** [comment]
When I do `echo $QT_QPA_PLATFORM`, I get nothing, and it crashes for me as well.

**Comment by doronbehar** [comment]
Maybe it'd be worth trying with `QT_QPA_PLATFORM=wayland`

**Comment by huantianad** [comment]
Still crashes on new user and with `QT_QPA_PLATFORM=wayland`.

**Comment by twahtera** [comment]
I have the same crash. I was able to get musescore running again by removing `gtk-font-name=Noto Sans,10` from my `~/.config/gtk-3.0/settings.ini`. Didn't do any testing on whether it's the font itself that's somehow the problem.

**Comment by huantianad** [comment]
That seems consistent with my discoveries in the other thread, it seems like MuseScore is having trouble when it tries to render something using the Noto Sans font for some reason.

**Comment by huantianad** [comment]
@doronbehar should we pull in the patch from https://github.com/musescore/MuseScore/pull/19000 to nixpkgs? 

Should probably ask @turion if the patch fixes it for your system too.

**Comment by doronbehar** [comment]
Yes, do it please, I'm too busy at the moment.
