### ISSUE TITLE
Documentation: `nixos-rebuild` manpages not included on non-nixos

### ISSUE THREAD

**Issue by sullyj3** [NixOS/nixpkgs#244450]
## Problem

I'm using `nixos-rebuild` on non-nixos with the `--target-host` flag as a deployment tool. I have it in a devShell, like so:

```nix
devShells.default = pkgs.mkShell {
  buildInputs = [
    pkgs.nixos-rebuild
  ];
};
```
However, both `man nixos-rebuild` and `nixos-rebuild --help`, give
```
No manual entry for nixos-rebuild
```

## Proposal

I propose that the relevant manpage be included in the package.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by doronbehar** [comment]
Fix suggested at https://github.com/NixOS/nixpkgs/pull/248701 .
