### ISSUE TITLE
Emacs complains about missing arch-dependent data dir

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#24445]
Running `emacs` from current `master` gives the following (non-fatal) warning:

~~~
$ emacs
Warning: arch-dependent data dir '/nix/store/9ng0phrd7gx72r2gk78lfpcav4k84sl4-emacs-25.1/libexec/emacs/25.1/x86_64-unknown-linux-gnu/': Not a directory
~~~

**Comment by ahmedtd** [comment]
It looks like `makeWrapper` is getting invoked on the _directory_ `/libexec/emacs`, and happily trying to produce a nonsense wrapper script for it.  The directory itself gets renamed to `.emacs-wrapped`.

**Comment by ahmedtd** [comment]
The culprit is wrapGAppsHook:
````
  if [ -z "$dontWrapGApps" ]; then
    for i in $prefix/bin/* $prefix/libexec/*; do
      echo "Wrapping app $i"
      wrapProgram "$i" "${gappsWrapperArgs[@]}"
    done
  fi
````

**Comment by ahmedtd** [comment]
I'm working on a fix

**Comment by matthewbauer** [comment]
Looks to be fixed. Reopen if it's not. Thanks!
