### ISSUE TITLE
Update request: jamesdsp 2.5.1 → 2.6.0

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#244548]
- Package name: jamesdsp
- Latest released version: 2.6.0

- Current version on the unstable channel: 2.6.0
- Current version on the stable/release channel: ~~2.4~~ **2.5.1**

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Found #243423 which updated the package for unstable, but i don't think this would break things to prevent a 23.05 backport.

actually why aren't backports the default? i think most updates shouldn't break things, so most of the time a backport is warranted.
despite that, though, it's not always done, resulting in needlessly out-of-date packages.

**Notify maintainers**

@pasqui23 @wineee 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/blob/402a5fb93f43a86138dedd88a91674435fefb7a4/CONTRIBUTING.md?plain=1#L169

jamesdsp should be able to backport, but I only use the unstable channel, it is not convenient to test whether it can run normally on the release channel

**Comment by FavoritoHJS** [comment]
works on my machine:tm:. don't close as it's 2.5.1 and not 2.6.0, but i can live with that

ps: is there a way to, in effect, build a single nix file straight from nixpkgs?

**Comment by wineee** [comment]
```
git clone https://github.com/NixOS/nixpkgs.git --branch backport-243423-to-release-23.05 --depth=1
# If you don't need git history
cd nixpkgs

nix-build -A jamesdsp
# Or use flake
nix build .#jamesdsp
```

**Comment by FavoritoHJS** [comment]
appears like the pr got merged, so we're done.
JAMES JAMES JAMES JAMES JAMES JAMES JAMES JAMES JAMES
