### ISSUE TITLE
NixOS flake config won't build because of missing attribute

### ISSUE THREAD

**Issue by td5038** [NixOS/nixpkgs#244556]
### Describe the bug
`nixos-rebuild` won't build my dotfiles I ripped from @fufexan because boot.kernelPackages.extend does not exists.

### Steps To Reproduce
1. Use a flakes-based config
2. Don't use a default kernel
3. Watch it blow up

### Expected behavior
I expected it to build correctly.

### Screenshots
![Screenshot_20230720_122919](https://github.com/NixOS/nixpkgs/assets/93895804/d64b2d57-c7c4-4ced-9450-2971118ee246)

### Additional context
It doesn't change whether I used an out-of-nixpkgs or in-nixpkgs kernel.

### Notify maintainers
@TredwellGit 
@Ma27 
@NeQuissimus 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.2084.08700de174b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
Please provide some code that triggers the problem. A screenshot and a config that was "ripped from $repository" isn't very helpful for investigating the problem.

**Comment by td5038** [comment]
`boot.kernelPackages = inputs.chaotic.packages.x86_64-linux.linux_cachyos`
That's taken out of [my config](https://github.com/td5038/dotfiles-fubased)

**Comment by Ma27** [comment]
You have to use `linuxPackages_cachyos` rather than `linux_cachyos`. The latter only refers to the kernel, not the package-set _for_ a linux kernel (including kernel modules etc).

Anyways, overriding kernelPackages in nixpkgs works fine, so if something else breaks with that, it's most likely an issue with nyx.
