### ISSUE TITLE
eject tries to use /bin/umount

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#24456]
## Issue description
I tried to eject a mounted USB storage volume...
```
eject: unable to exec /bin/umount of `/mnt'
eject: unmount of `/mnt' failed
```

### Steps to reproduce
1. Plug in USB stick
2. Mount USB stick manually
3. `eject /dev/sdX`

## Technical details
- System: 17.03beta617.f3a9ccc (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03beta617.f3a9ccc"

**Comment by matthewbauer** [comment]
Don't forget to close this!
