### ISSUE TITLE
release-17.03 is currently broken, missing entry in lib/maintainers.nix

### ISSUE THREAD

**Issue by drdaeman** [NixOS/nixpkgs#24457]
## Issue description

Currently, `release-17.03` branch (I know, it's beta) is broken, because [this PR](https://github.com/NixOS/nixpkgs/pull/23678/files) made it there (from `master`), but [this one](https://github.com/NixOS/nixpkgs/pull/23606/files) didn't.

Please consider cherry-picking 0f72dee0002ff94e1f1620b5cd56c8cb985b0dff to `release-17.03`.

### Steps to reproduce

    $ nox something
    Refreshing cache
    error: undefined variable ‘xnwdd’ at /nix/store/w68y6y7vn1pgizr10xhxwz79i7nplqlf-nixos-17.03beta773.38b2e27/nixos/pkgs/applications/version-management/gitkraken/default.nix:74:39
    Error: An error occured while running nix (displayed above). Maybe the nixpkgs eval is broken.

## Technical details

* System: NixOS: 17.03beta773.38b2e27 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03beta773.38b2e27

**Comment by benley** [comment]
fixed, thanks for pointing it out.
