### ISSUE TITLE
zfs: udevadm[2006]: systemd-udev-settle.service is deprecated. Please fix `zfs-import-${pool}.service` not to pull it in.

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#244562]
### Describe the bug
systemd/udevadm complains about `zfs-import-*` services using deprecated features. In journalctl you can see the message from the title being emitted during an early boot.

Nothing is broken quite yet, but it may break sooner or later if left untreated. And filesystems are sirious stuff™, so we better stay on top of it.

### Steps To Reproduce
1. Set up ZFS using NixOS modules, and boot
2. Check journalctl.

### Expected behavior

Using ZFS does not result in deprecation warnings in journal

### Notify maintainers

:shrug:

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.33, NixOS, 23.11 (Tapir), 23.11.20230614.ba1a6ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - channels(nagisa): `""`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by Gerg-L** [comment]
this is a upstream issue
https://github.com/openzfs/zfs/issues/10891

**Comment by SuperSandro2000** [comment]
we also have some ocurences of systemd-udev-settle but they where checked as part of #73095 and closing this with the same reason as https://github.com/NixOS/nixpkgs/issues/73095#issuecomment-1703959214
