### ISSUE TITLE
JetBrains IDEs are put under wrong scope

### ISSUE THREAD

**Issue by miltador** [NixOS/nixpkgs#24453]
## Issue description
JetBrains IDEs are currently at `pkgs/applications/editors/idea` which is kind of confusing because the packages here aren't all under `IDEA` name.
For example WebStorm, PhpStorm, PyCharm and so on - these are properties of JetBrains.
Therefore I think it will be good to move all them under `pkgs/applications/editors/jetbrains` and rename `makeIdeaProduct` to `makeJetBrainsProduct`.

**Comment by Mic92** [comment]
Do you want to make a pull request?
