### ISSUE TITLE
jsoncpp: Broken symlink with enableStatic

### ISSUE THREAD

**Issue by bryceberger** [NixOS/nixpkgs#244525]
### Describe the bug
As described in [this issue](https://github.com/open-source-parsers/jsoncpp/issues/1245) and fixed in [this pr](https://github.com/open-source-parsers/jsoncpp/pull/1263), jsoncpp no longer appends `_static` to the static library path (except under MSVC). This breaks enableStatic, introduced in [this pr](https://github.com/NixOS/nixpkgs/pull/166415).

### Steps To Reproduce
See [attached archive](https://github.com/NixOS/nixpkgs/files/12111989/reproduce.zip). TLDR:
1. Make package that depends on `pkgs.jsoncpp.override { enableStatic = true; })`
2. Compile and statically link `jsoncpp`.
3. Error involving `libjsoncpp.a` being a broken symlink.

### Additional context
Could be fixed by either specifying `-DSTATIC_SUFFIX="_static"` to cmake or just removing the `postInstall` hook, not sure which would be preferred.

### Notify maintainers

@tfc as the submitter of the original PR, @tteggel @cpages as listed in `meta.maintainers`.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37, NixOS, 23.11 (Tapir), 23.11pre501608.f292b4964cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

[reproduce.zip](https://github.com/NixOS/nixpkgs/files/12111989/reproduce.zip)

**Comment by tfc** [comment]
This particular thing is also fixed in this PR: https://github.com/NixOS/nixpkgs/pull/235024

**Comment by bryceberger** [comment]
Closing as completed in mentioned PR.
