### ISSUE TITLE
nixos-install fails if /mnt is not empty

### ISSUE THREAD

**Issue by mode89** [NixOS/nixpkgs#244643]
### Describe the bug
If there are any files under `/mnt` (of the target's root file system), `nixos-install` fails.

### Steps To Reproduce
1. Boot into NixOS live CD.
2. Mount target's root partition as `/mnt`.
3. Mount target's boot partition as `/mnt/boot`.
4. Create `/mnt/mnt` directory.
5. Create a file under `/mnt/mnt`: `touch /mnt/mnt/file`.
6. Generate configuration files: `nixos-generate-config --root /mnt`.
7. Run `nixos-install`.

### Expected behavior
`nixos-install` should finish normally.

### Additional context
The last lines of `nixos-install`'s output:
```
installing the boot loader...
setting up /etc...
updating GRUB 2 menu...
installing the GRUB 2 boot loader on /dev/sda...
Installing for i386-pc platform.
Installation finished. No error reported.
rmdir: failed to remove '/mnt': Directory not empty
```

In my usage scenario I keep the NixOS configuration files on a separate partition that should be mounted as a directory under the target's `/mnt`, and `/etc/nixos/configuration.nix` is a relative symbolic link pointing to that location.

I can confirm that `nixos-install` on NixOS 22.05 doesn't have this issue.

I think that the culprit could be [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/tools/nixos-install.sh#L209) line, and probably `rmdir` should be replaced by `rm -r`.

### Notify maintainers

@rnhmjoj
@ncfavier

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: "x86_64-linux"
- host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05pre-git`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.13.3`
- channels(root): `"nixos-23.05pre-git"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rnhmjoj** [comment]
> I think that the culprit could be [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/tools/nixos-install.sh#L209) line

Yeah, it's certainly that.

> and probably rmdir should be replaced by rm -r

I don't really agree. The installer should not be removing files it didn't create in the first place: there's a potential for disaster doing this.

Anyway, It seems that you started with a non-empty /mnt/mnt, NixOS was installed (?) and you're left with /mnt/mnt as it was before. What's the issue?

**Comment by mode89** [comment]
Hi @rnhmjoj :)

I have a partition mounted on `/mn/mnt/data`, which has a repository with the NixOS configuration files, and `/mnt/etc/nixos/configuration.nix` is a symbolic link to one of those files.

We are making an embedded system, and to simplify maintenance I want to keep all the source code (required during development) in one place and outside of the system partition.

**Comment by kirillrdy** [comment]
@mode89 

> The installer should not be removing files it didn't create in the first place: there's a potential for disaster doing this.

I agree with this statement, less unexpected behaviors is better.

Is there a reason why you can simply use `nixos-install -I nixos-config=/path/to/configuration.nix` ?

**Comment by mode89** [comment]
Hi @kirillrdy.

> Is there a reason why you can simply use nixos-install -I nixos-config=/path/to/configuration.nix

I guess, I could do it. Though, in that case I would have to have two copies of the configuration repository: one on the temporary filesystem made by the live CD, and the second - on the target's drive.

**Comment by mode89** [comment]
If `/mnt/mnt` isn't allowed to be populated during the installation, perhaps it should be outlined in the documentation, or `nixos-install` should check it before the installation and show an appropriate message in the beginning. `rmdir`'s message isn't very informative (not even a pointer to a line in source code), so I had to repeat the whole process again several times: format the target's `/` and `/boot`, mount them and wait until `nixos-install` downloaded all of the dependencies, just to make sure that I have a correct final state.

**Comment by rnhmjoj** [comment]
> If /mnt/mnt isn't allowed to be populated during the installation

There's actually nothing against it: the bind mount command used by the installer handles non-empty directories just fine, the only "problem" is that rmdir fails, but it's harmless.

I think the error can be ignored completely, something like `rmdir "$mountPoint" 2>/dev/null || true` should do.

**Comment by mode89** [comment]
Thank you @rnhmjoj :)

> `rmdir "$mountPoint" 2>/dev/null || true` should do.

That would work for me. Should I make a pull request?

**Comment by rnhmjoj** [comment]
Yes, please.

**Comment by ISibboI** [comment]
Please see #241356. The changes made in #246746 now simply hide that issue. Not sure if that was intended, since now, if the `rmdir` problem exists, but `/mnt` is empty, it won't be removed as intended.
