### ISSUE TITLE
NixOS iso doesn't boot, but other distros work.

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#244673]
### Describe the bug
I flashed the latest nixos-unstable with dd in to a flash drive. The usb doesn't boot in UEFI mode(you can only see 1 cursor), it works on other laptops and other distros work just fine. If I disable UEFI mode the usb boots.

Laptop: dell 5290 2 in 1

Same issue as https://discourse.nixos.org/t/nix-iso-unable-to-boot-in-uefi-mode-but-other-distros-can/16473
@RaitoBezarius

**Comment by chasecaleb** [comment]
I'm encountering this as well when attempting to create a VMware Workstation VM using UEFI. At my work we create a custom NixOS ISO that's intended for use in UEFI mode, and sometime within the last month or so it stopped booting. 

Screenshot of VMware bug:
![image](https://github.com/NixOS/nixpkgs/assets/5241169/8f0d1f48-4082-4ba7-add1-46d8a623065f)

Does any know what's going on?

**Comment by bb2020** [comment]
I had the same issue and completed the installation with 23.05 unstable.

**Comment by bb2020** [comment]
I had the same issue and completed the installation with 23.05 unstable instead of 23.11.

**Comment by adevoss** [comment]
Same here. Using iso file installing VM in Proxmox using OVMF. SeaBIOS boots.

**Comment by Tungsten842** [comment]
I am not sure about what changed, but the latest nixos-unstable iso works fine now.

**Comment by fabi20750** [comment]
Not Sure if this is still relevant but I just had the same problem with NixOS 23.11.6759 and VMWare 17.5.0. After disabling 3D acceleration I could boot and install normally
