### ISSUE TITLE
lldb 16.0.6 broken

### ISSUE THREAD

**Issue by Ninja3047** [NixOS/nixpkgs#244609]
### Describe the bug
lldb 16.0.6 does not run

### Steps To Reproduce
```console
$ nix run nixpkgs#lldb_16 
/nix/store/l2iidv87qb7gfdafd5s3fg3hc1h869qp-lldb-16.0.6/bin/lldb: error while loading shared libraries: libclang-cpp.so.16: cannot open shared object file: No such file or directory
```

### Expected behavior
It should run.

### Additional context
I believe it worked with earlier versions of lldb 16. It works with lldb_15.

### Notify maintainers

@dtzWill
@ericson2314
@rrbutani
@raitobezarius

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230720.5df4d78`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/3z2ddp392iwz4dm4f040p55gylzcxyfg-source`
```

**Comment by GiulioCocconi** [comment]
I also have this problem

**Comment by Itaros** [comment]
Peculiar, 16.0.1 does run though. I wonder what happened in-between.

**Comment by Itaros** [comment]
I did git bisect(that took a while). The commit in question which broke it is 251c55700d3ef977506c3f664888780f707f4a55
There is some new weird machinery which fell under the bus and runtime deps are lost in transit.
