### ISSUE TITLE
Improve error message for (faulty) list in `buildInputs`

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#24462]
## Issue description
Issue described in
http://unix.stackexchange.com/questions/350997/in-a-new-nixos-derivation-based-on-a-binary-distribution-why-am-i-getting-an-e?stw=2

The error message should be: 
```
'buildInputs' should contain only derivations. 'xorg' is a set, no a derivation 
```
Though I don't know how to introspect code and get that `xorg` string.

I've hit this kind of problem myself several times in a past.

**Comment by lheckemann** [comment]
For introspection:

If you're looking for functionality built in to nix, I think builtins.trace is your only option.

`nix-repl` tends to be helpful for this sort of thing. If you use `nix-repl '<nixpkgs>'` you can see that xorg is a set, and that it contains a variety of attributes including libraries, utilities, and the server itself.

As an alternative to introspection, you can inspect the source code. For the example of xorg, if you look at `all-packages.nix` you'll see that it refers to pkgs/servers/x11/xorg/default.nix`, which is a function to return a set containing all of the attributes.

`nix-repl` is probably the easiest option for this, particularly with its tab completion.

**Comment by lheckemann** [comment]
I don't see how seeing
```applewmproto fontjismisc libXdmcp mkfontscale xcursorgen xf86videointel xineramaproto appres fontmicromisc libXext pixman xcursorthemes xf86videomach64 xinit bdftopcf fontmisccyrillic libXfixes presentproto xdm xf86videomga xinput bigreqsproto fontmiscethiopic libXfont printproto xdpyinfo xf86videoneomagic xkbcomp compositeproto fontmiscmeltho libXfont2 randrproto xdriinfo xf86videonewport xkbevd damageproto fontmiscmisc libXft recordproto xev xf86videonouveau xkbprint dmxproto fontmuttmisc libXi recurseForDerivations xextproto xf86videonv xkbutils dri2proto fontschumachermisc libXinerama renderproto xeyes xf86videoopenchrome xkeyboardconfig dri3proto fontscreencyrillic libXmu resourceproto xf86bigfontproto xf86videoqxl xkill encodings fontsonymisc libXp scrnsaverproto xf86dgaproto xf86videor128 xlibsWrapper fixesproto fontsproto libXpm sessreg xf86driproto xf86videorendition xlsatoms fontadobe100dpi fontsunmisc libXpresent setxkbmap xf86inputevdev xf86videos3virge xlsclients fontadobe75dpi fontutil libXrandr smproxy xf86inputjoystick xf86videosavage xlsfonts fontadobeutopia100dpi fontwinitzkicyrillic libXrender twm xf86inputkeyboard xf86videosiliconmotion xmag fontadobeutopia75dpi fontxfree86type1 libXres utilmacros xf86inputlibinput xf86videosis xmessage fontadobeutopiatype1 gccmakedep libXt videoproto xf86inputmouse xf86videosisusb xmodmap fontalias glproto libXtst windowswmproto xf86inputsynaptics xf86videosuncg6 xorgcffiles fontarabicmisc iceauth libXv x11perf xf86inputvmmouse xf86videosunffb xorgdocs fontbh100dpi imake libXvMC xauth xf86inputvoid xf86videosunleo xorgserver fontbh75dpi inputproto libXxf86dga xbacklight xf86miscproto xf86videotdfx xorgsgmldoctools fontbhlucidatypewriter100dpi kbproto libXxf86misc xbitmaps xf86videoamdgpu xf86videotga xpr fontbhlucidatypewriter75dpi libAppleWM libXxf86vm xcbproto xf86videoark xf86videotrident xprop fontbhttf libFS libdmx xcbutil xf86videoast xf86videov4l xproto fontbhtype1 libICE libfontenc xcbutilcursor xf86videoati xf86videovesa xrandr fontbitstream100dpi libSM libpciaccess xcbutilerrors xf86videochips xf86videovmware xrdb fontbitstream75dpi libWindowsWM libpthreadstubs xcbutilimage xf86videocirrus xf86videovoodoo xrefresh fontbitstreamtype1 libX11 libxcb xcbutilkeysyms xf86videodummy xf86videowsfb xset fontcronyxcyrillic libXScrnSaver libxkbfile xcbutilrenderutil xf86videofbdev xf86videoxgi xsetroot fontcursormisc libXau libxshmfence xcbutilwm xf86videogeode xf86vidmodeproto xtrans fontdaewoomisc libXaw lndir xclock xf86videoglide xfs xvinfo fontdecmisc libXcomposite luit xcmiscproto xf86videoglint xgamma xwd fontibmtype1 libXcursor makedepend xcmsdb xf86videoi128 xgc xwininfo fontisasmisc libXdamage mkfontdir xcompmgr xf86videoi740 xhost xwud```

would help significantly, and I don't think introspecting incorrect values that may be huge (consider accidentally passing the entirety of pkgs rather than just xorg) is the responsibility of the error message.

**Comment by Mic92** [comment]
A check could be added to `nixpkgs/pkgs/stdenv/default.nix`

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by lheckemann** [comment]
no

**Comment by mmahut** [comment]
Well, do we agree this is something we want? I agree that dumping the whole set doesn't really make any sense. Should we just add it into the manual for general knowledge without adding a specific check?

**Comment by lheckemann** [comment]
Opened #157106 to address this at least somewhat.
