### ISSUE TITLE
parcellite is out of date

### ISSUE THREAD

**Issue by paperdigits** [NixOS/nixpkgs#24464]
Please update to [version 1.2.1](https://github.com/rickyrockrat/parcellite/releases/tag/1.2.1).

**Comment by ndowens** [comment]
Will work on this

**Comment by paperdigits** [comment]
When I launch version 1.1.9, the tray icon fails to show up. Perhaps this can also be taken care of in the 1.2.1 update? 

Many thanks for taking the time to update this package!

**Comment by ndowens** [comment]
@paperdigits it did for me, but the icon image didn't look right, but it could be b/c I dont use a desktop manager

**Comment by paperdigits** [comment]
@ndowens I appreciate you taking a look at it, I'll check it out when I get home in a few hours.
