### ISSUE TITLE
Document support tiers in Nixpkgs manual

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixpkgs#244686]
After [RFC046](https://github.com/NixOS/rfcs/pull/46) got merged, no documentation was added to the nixpkgs manual regarding support tiers.

[This](https://github.com/NixOS/rfcs/pull/46#issuecomment-669019148) is the last state of the conversation.

cc @7c6f434c

**Comment by infinisil** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/143732 (discussed in the docs team meeting today)

**Comment by fricklerhandwerk** [comment]
Closed by #254741
