### ISSUE TITLE
Easyeffects gets forced sigkilled

### ISSUE THREAD

**Issue by NopeNopeGuy** [NixOS/nixpkgs#244778]
### Steps To Reproduce
1. Install Easyeffects
2. Launch it
3. See that it doesn't launch and instead gets killed 

### Expected behavior
The app was expected to launch properly but instead gets killed after a few seconds with no error

### Additional context
I do remember it crashing before it didn't start anymore, it happened when I turn off the speech recognition thing or something along that line. See the log here: https://pastebin.com/raw/b0ajLe8M

### Notify maintainers

@redshifttt 
@wegank 

### Metadata

```console
anonimized@nixos ~ [1]> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.1852.510d721ce09`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by redshifttt** [comment]
What version of easyeffects are you using? I had similar issues on 7.0.4 and wasn't able to find the cause as seen here https://github.com/wwmm/easyeffects/issues/2407#issuecomment-1615246568. Updating to 7.0.5 seemed to fix the issue which is obviously not the most helpful thing ever as who knows what was happening. I'd be curious to know if this was happening on 7.0.5 as well.

**Comment by bjornfor** [comment]
I think this is an upstream issues, let's close here. (If you disagree, ping me and I'll re-open.)
