### ISSUE TITLE
nixos.home-assistant: allow extending the DeviceAllow-list

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#244726]
If you use a module (such as https://github.com/thecode/ha-rpi_gpio) which uses a device (such as `/dev/gpiochip0`), you somehow need a way to allow the home-assistent systemd service to access that device (by adding something like `/dev/gpiochip0 rw` to `DeviceAllow`).

Perhaps something to build on top of https://github.com/NixOS/nixpkgs/pull/160346

**Comment by oddlama** [comment]
It won't be necessary to change anything in nixpkgs to allow this. You can already add additional devices by setting

```nix
systemd.services.home-assistant.serviceConfig.DeviceAllow = ["/dev/gpiochip0"];
```
