### ISSUE TITLE
Improve Okular without KDE

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#24472]
## Issue description

Okular currently mostly works when started from Nix store. However to save files it requires several KDE daemons started: `kinit` and `plasma-workspace` installed to the system environment solve the problem. I haven't tested if user environment is sufficient. Maybe we want to propagate those packages to environment from Okular? Or even propagate them for all KDE applications?

### Steps to reproduce

1. Run `nix-shell -p okular --run okular`;
2. Try to save file; observe an error;
3. Add `kinit`, `plasma-workspace` to `environment.systemPackages` and rebuild the system;
4. Run `okular` and observe that saving works now.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 186cc512a68e228d8768f4c817f072b112b922d3

cc @ttuegel

**Comment by ttuegel** [comment]
In my `wrapProgramsHook` branch, which I believe we have discussed before, all such service packages will be propagated automatically. In part this is related to removing `kdeWrapper`.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by ttuegel** [comment]
Such dependencies are now propagated automatically.
