### ISSUE TITLE
nextcloud-notify_push fails to start

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#244712]
### Describe the bug
I enabled `nextcloud-notify_push` through the following configuration:

```nix
notify_push = {
  enable = true;
  # Allow using the push service without hard-coding my IP in the configuration
  bendDomainToLocalhost = true;
};
```

When I switch my configuration, I get the following error from `nextcloud-notify_push` which fails to start:

<details>
<summary>Logs</summary>

```
Jul 19 08:29:11 porthos systemd[1]: Starting Push daemon for Nextcloud clients...
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: ✓ redis is configured
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: 🗴 using unencrypted http for push server is strongly discouraged
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: ✓ push server is receiving redis messages
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: ✓ push server can load mount info from database
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: ✓ push server can connect to the Nextcloud server
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: ✓ push server is a trusted proxy
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: 🗴 failed to get binary version: Client error: `POST <nextcloud-url>/push/test/version` resulted in a `405 Method Not Allowed` response:
Jul 19 08:29:12 porthos nextcloud-notify_push-post-start[868633]: HTTP method not allowed
Jul 19 08:29:12 porthos systemd[1]: nextcloud-notify_push.service: Control process exited, code=exited, status=1/FAILURE
Jul 19 08:29:12 porthos systemd[1]: nextcloud-notify_push.service: Failed with result 'exit-code'.
Jul 19 08:29:12 porthos systemd[1]: Failed to start Push daemon for Nextcloud clients.
Jul 19 08:29:12 porthos systemd[1]: nextcloud-notify_push.service: Consumed 715ms CPU time, received 20.0K IP traffic, sent 6.9K IP traffic.
Jul 19 08:29:17 porthos systemd[1]: nextcloud-notify_push.service: Scheduled restart job, restart counter is at 11602.
Jul 19 08:29:17 porthos systemd[1]: Stopped Push daemon for Nextcloud clients.
Jul 19 08:29:17 porthos systemd[1]: nextcloud-notify_push.service: Consumed 715ms CPU time, received 20.0K IP traffic, sent 6.9K IP traffic.
Jul 19 08:29:17 porthos systemd[1]: Starting Push daemon for Nextcloud clients...
Jul 19 08:29:18 porthos nextcloud-notify_push-post-start[8
```

</details>

### Steps To Reproduce
1. Enable the service.
2.Switch configuration.
3. Observe the failure

[Here](https://git.belanyi.fr/ambroisie/nix-config/src/branch/main/modules/services/nextcloud/default.nix) is my full configuration.

### Expected behavior
I would expect the service to Just Work :tm:.

### Additional context
I wonderer if it was an issue of `nginx` having access to the socket. But changing `serviceConfig.Group` to `nginx` did not solve the issue.

### Notify maintainers

@ajs124, @SuperSandro2000, @tensor5 (pinged all non-trivial committers on the file, since `meta.maintainers` is empty...).

**Comment by SuperSandro2000** [comment]
I didn't have time to look at your config but do you have declarative or imperative the companion nextcloud app installed?

**Comment by ambroisie** [comment]
@SuperSandro2000 imperative app installed, I don't use declarative apps for nextcloud.

**Comment by SuperSandro2000** [comment]
Maybe some dependency on nextcloud is missing or nextcloud reports early that it is ready while it isn't. If you restart the notify service after some time, does it then work?

**Comment by ambroisie** [comment]
Restarting the service does not change the outcome.

As for a missing dependency, I don't think that's the issue: the logs from the after-start script show that everything is OK leading to the 405 (with a warning about using HTTP, which is fine since I'm connecting to `localhost`).

**Comment by SuperSandro2000** [comment]
This is likely an issue in your nginx configuration which maybe changes some headers or so. AFAIK I am using the standard module options for this part of nextcloud and it works for me.

**Comment by ambroisie** [comment]
For future reference, the reason it didn't work was that I was missing `config.services.nextcloud.https = true`, and that probably didn't interact well with other configurations I setup.
