### ISSUE TITLE
luarocks-admin miss shell completions

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#244833]
### Describe the bug

```
luarocks-admin completion {bash,zsh,fish}
```

### Notify maintainers

@raskin @teto

Another Problem:

- [Luarocks-nix break completion](https://github.com/nix-community/luarocks-nix/issues/23)
- [Luarocks is not a lua package](https://discourse.nixos.org/t/luarocks-doesnt-exist-in-lua-environment/30802)

**Comment by teto** [comment]
in pkgs/development/tools/misc/luarocks/default.nix, the call to generate completion should be moved to before the wrapping. 
And it should be called for luarocks-admin too thanks for noticing. Let me know if you wanna do it.

**Comment by teto** [comment]
If u wanna test https://github.com/NixOS/nixpkgs/pull/288761
