### ISSUE TITLE
Downloading an OS in GNOME Boxes crashes display manager (?)

### ISSUE THREAD

**Issue by akr2002** [NixOS/nixpkgs#244863]
### Describe the bug
Same as title. But unsure if it is the DE or the display manager. I couldn't find anything helpful in journalctl. 

### Steps To Reproduce
1. Get GNOME Boxes
```nix
nix shell nixpkgs#gnome.gnome-boxes
```
2. Run `gnome-boxes`
3. Click on the '+' button, select an OS (Ubuntu 22.04 in my case)
4. Instant crash.

Version: 44.2
Tried running both on X11 and Wayland. Same result.

### Expected behavior
The OS downloads and the virtual machine should be in install phase.

### Notify maintainers
@bobby285271 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230721.9ca7856`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(user): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I am unsure if this issue is specific to GNOME or unique to NixOS.

**Comment by bobby285271** [comment]
So this is probabaly https://github.com/NixOS/nixpkgs/issues/226355? The upstream issue is at https://gitlab.gnome.org/GNOME/gnome-session/-/issues/113

**Comment by blitz** [comment]
Yes, this is the same issue. Closing as duplicate.

But the good news is that it might be fixed by upstream! https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/97
