### ISSUE TITLE
kdenlive stores absolute path to melt in configuration file

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#24489]
## Issue description

From `~/.config/kdenliverc`:
```
[env]
...
mltpath[$e]=/nix/store/jfr123xr49bvaibnj2s7z9cp0xgv8lav-mlt-6.2.0/share/mlt/profiles/
rendererpath[$e]=/nix/store/jfr123xr49bvaibnj2s7z9cp0xgv8lav-mlt-6.2.0/bin/melt
```

Using an outdated version of melt can cause rendering to fail. (I got some obscure error message about xcb.)

Somehow kdenlive uses ffmpeg from /run/current-system:
```
ffmpegpath[$e]=/run/current-system/sw/bin/ffmpeg
ffprobepath[$e]=/run/current-system/sw/bin/ffprobe
```
This is not perfect either but a lot more likely to work. I guess it picks up ffmpeg from $PATH, so maybe melt should be included in $PATH as well as a workaround.

### Steps to reproduce

Run kdenlive and check config file `~/.config/kdenliverc`.

## Technical details

* System: 17.03.git.925a617

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by drozdziak1** [comment]
# Rendering workaround
* Ask `kdenlive` to generate a script for your render.
* Open a `nix-shell -p mlt` shell in a terminal
* run `melt -progress ~/Videos/kdenlive-renderqueue/your_project.mlt`

**Comment by turion** [comment]
I believe this issue does not exist anymore. Feel free to reopen if it occurs again.
