### ISSUE TITLE
Package request: MControlCenter

### ISSUE THREAD

**Issue by Yvonne-Aizawa** [NixOS/nixpkgs#244881]
**Project description**

This application allows one with select msi laptops to control fanspeed/battery settings/Keyboard lighting/camara toggle
This is basicly a replacement to dragon center on windows

**Metadata**

* homepage https://github.com/dmitry-s93/MControlCenter:
* source https://github.com/dmitry-s93/MControlCenter:
* license: Gpl 3.0
* platforms: linux

**Comment by nadimkobeissi** [comment]
Worked a little bit on this today. It's pretty complicated due to the kernel module, dbus service, etc.

**Comment by nadimkobeissi** [comment]
@Yvonne-Aizawa Good news! A package definition is now available:
https://github.com/dmitry-s93/MControlCenter/pull/123
