### ISSUE TITLE
systemd 233

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#24497]
I know `systemd` is always a lovely topic :)

Do we plan on moving to 233? Has anybody looked at it?
<https://github.com/systemd/systemd/blob/master/NEWS>

**Comment by Mic92** [comment]
Seems that it will unbrick docker.

**Comment by globin** [comment]
working on it

**Comment by copumpkin** [comment]
Docker is bricked in 17.03?

**Comment by globin** [comment]
No we have a patch in our systemd fork fixing it.

**Comment by NeQuissimus** [comment]
Have not run into any issues (and use Docker on 17.03 every day) but maybe @Mic92 has a special use-case :)

**Comment by peterhoeg** [comment]
With 233 being merged in dfebb66f65 and using the ```hybrid``` control group mode by default, ```systemd-run --user --scope``` is now broken:

```
$ systemd-run --user --scope ls
Job for run-r10fe931d0f274e928de3e0f1ee904bdd.scope failed.
See "systemctl status run-r10fe931d0f274e928de3e0f1ee904bdd.scope" and "journalctl -xe" for details.

Jun 05 17:03:57 mildred systemd[1665]: run-r10fe931d0f274e928de3e0f1ee904bdd.scope: Failed to add PIDs to scope's control group: Permission denied
Jun 05 17:03:57 mildred systemd[1665]: Failed to start /run/current-system/sw/bin/ls.
```

**Comment by peterhoeg** [comment]
Turns out it's documented here:
https://github.com/systemd/systemd/blob/v233/NEWS#L31

Workaround is to use ```legacy``` mode.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/26231

**Comment by tokudan** [comment]
With the switch to 17.09beta the systemd user scope issue is now relevant again.
@peterhoeg how was this solved for you? I don't see how to enable legacy mode.

**Comment by peterhoeg** [comment]
@tokudan it "works" with hybrid mode if you set the permissions on the cgroup. I manually run this script once after bootup:

```sh
#!/usr/bin/env bash

set -euo pipefail

uid=$(id -u)

cgroups=(/sys/fs/cgroup/unified/user.slice/user-${uid}.slice/cgroup.procs
         /sys/fs/cgroup/user.slice/user-${uid}.slice/cgroup.procs)

found=0
for file in ${cgroups[@]} ; do
  if [ -e $file ] ; then
    found=1
    sudo chown ${uid}:root $file
    sudo chmod g+w         $file
  fi
done

if [ $found -eq 0 ] ; then
  echo "Unable to find cgroup file. Aborting..."
  exit 1
fi

systemctl --user reset-failed

```
