### ISSUE TITLE
Package request: kWinFT

### ISSUE THREAD

**Issue by kunihir0** [NixOS/nixpkgs#244921]
**Project description**
Wayland compositor and X11 window manager (a reboot of KWin)

- homepage URL: https://gitlab.com/kwinft/kwinft
- source URL: https://gitlab.com/kwinft/kwinft
- license: gpl
- platforms: linux

**Comment by Aleksanaa** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/197356 and https://github.com/NixOS/nixpkgs/issues/158827
