### ISSUE TITLE
Cannot create bootable config with systemd-boot and ZFS

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#24495]
## Issue description

Cannot create bootable config with systemd-boot and ZFS.  

I am running ZFS on root and I keep getting:  "Warning: do not know how to make this configuration bootable; please enable a boot loader.

systemd-boot does work with ZFS I'm using it right now on arch.

### Steps to reproduce

Set systemd-boot as bootloader and try to build config on a ZFS root.

## Technical details

* System: (NixOS: nix-env (Nix) 1.11.8 )

**Comment by 8573** [comment]
To be sure, does your `/boot` directory refer to a EFI system
partition formatted as a FAT filesystem?

**Comment by johnramsden** [comment]
Yep.

Made with gdisk ef00

```
  fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/6E67-E683";
        fsType = "vfat";
      };
```

**Comment by 8573** [comment]
I don't know what the problem is, but [my configuration], which works
as far as I know, doesn't mention `efiSysMountPoint` or the obsolete
`gummiboot`, uses Boolean `false` rather than string `"false"` for
`forceImportAll`/`forceImportRoot`, and has `"vfat"` in both
`supportedFilesystems` options. Making these changes in your
configuration *might* help, though I doubt it will solve your problem.

[my configuration]: <https://github.com/8573/nixos-config/blob/master/sections/boot/default.nix>

**Comment by johnramsden** [comment]
What are you doing with ```c74d-params.ZFS.enable "zfs"```?

Also, why are you using both grub and systemd-boot with this?

```
  boot.loader = {
    efi = {
      canTouchEfiVariables = config.boot.loader.systemd-boot.enable;
    };
    grub = {
      enable = config.c74d-params.firmware.type == "BIOS";
      zfsSupport = config.c74d-params.ZFS.enable;
    };
    systemd-boot = {
      enable = config.c74d-params.firmware.type == "EFI";
    };
  };
```

---

I am doing my install from a [chroot](https://nixos.org/wiki/How_to_install_NixOS_from_Linux) so maybe that's the issue... I'll give it a shot from the live iso and see if that helps.

**Comment by 8573** [comment]
In retrospect, I oughtn't have linked to my configuration; it's much
too convoluted for that. The differences from yours that I described
are true for installations using ZFS on EFI systems, but my
configuration is intended to be configurable to support installations
with BIOS and without ZFS, resulting in the complexity with which I've
unnecessarily distracted you (my apologies).

**Comment by johnramsden** [comment]
So I just tried again with the ISO and it built fine. I guess it was the chroot that was causing the problem.

Thank you for your time.
