### ISSUE TITLE
utop fails to run

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#24496]
## Issue description

When running `utop` on unstable NixOS I get the following error:
```
$ utop
/nix/store/hjbj55zxa0vj6f7kxgckj67qb4v84kik-utop-1.19.3/bin/utop not found or is not a bytecode executable file
```

## Technical details

* System: `17.09pre104652.08c87ee (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `"17.09pre104652.08c87ee"`

**Comment by ndowens** [comment]
Weird, it is working for me in unstable-small.

**Comment by romildo** [comment]
I forget to say that it happens with `ocamlPackages_latest.utop`.

**Comment by vbgl** [comment]
Thanks for the report. Please check #24524.

**Comment by romildo** [comment]
It fixes `utop` for me.

**Comment by pmahoney** [comment]
The `wrapProgram` helper by default runs `exec -a $0 .../.utop-wrapped`. I can avoid this issue by running `exec .../.utop-wrapped`, i.e. just removing the `-a $0` part.

This can be accomplished be invoking `wrapProgram --argv0 "" ...`.

**Comment by Mic92** [comment]
I guess this is fixed now.
