### ISSUE TITLE
WiFi broken in current nixos-unstable 

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#24500]
After updating my system to 8a919af, the WiFi interface is broken, i.e. I connect to any network. wpa_supplicant shows the following errors:

~~~
Successfully initialized wpa_supplicant
wlp2s0: SME: Trying to authenticate with c8:0e:14:2a:14:cc (SSID='My Secret ESSID' freq=5180 MHz)
wlp2s0: Trying to associate with c8:0e:14:2a:14:cc (SSID='My Secret ESSID' freq=5180 MHz)
wlp2s0: Associated with c8:0e:14:2a:14:cc
wlp2s0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
wlp2s0: WPA: Key negotiation completed with c8:0e:14:2a:14:cc [PTK=CCMP GTK=CCMP]
wlp2s0: CTRL-EVENT-CONNECTED - Connection to c8:0e:14:2a:14:cc completed [id=0 id_str=]
wlp2s0: CTRL-EVENT-DISCONNECTED bssid=c8:0e:14:2a:14:cc reason=4 locally_generated=1
wlp2s0: SME: Trying to authenticate with c8:0e:14:2a:14:cc (SSID='My Secret ESSID' freq=5180 MHz)
wlp2s0: SME: Trying to authenticate with c8:0e:14:2a:14:cc (SSID='My Secret ESSID' freq=5180 MHz)
wlp2s0: SME: Trying to authenticate with c8:0e:14:2a:14:cc (SSID='My Secret ESSID' freq=5180 MHz)
wlp2s0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="My Secret ESSID" auth_failures=1 duration=10 reason=CONN_FAILED
~~~

Reverting back to the previous channel state at 65593e6 fixed the issue.

**Comment by noisecrew** [comment]
I had the same thing here. I was solved by first creating the vanilla **wpa_supplicant.conf** file like this:
`ctrl_interface=/var/run/wpa_supplicant
update_config=1
`
remember that you can't even declare the **GROUP=wheel** at this file and you have to set the wheel group can change wpa_supplicant in your .nix config file. 
then reboot the system. I don't know why but **systemctl** would send the wifi service to limbo phase.
then installing the **wpa_gui** and connection the preferred AP. and after that the setting would be updated on wpa config file and would be save for next reboots. 
I worth to mention that this behaviour is not NixOS specific

**Comment by peti** [comment]
I've new information. After reverting to the NixOS old version, the same problem occurred again! A reboot fixed it. So whatever it is that causes my WiFi to misbehave, it's clearly not related to that particular NixOS version I reported above, and it actually looks like an issue in the kernel and/or the wpa_supplicant code a.k.a. upstream software.
