### ISSUE TITLE
Package request: android-ndk

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#245048]
**Project description**

Android C/C++ developer kit

Refer:

- [ArchLinux](https://aur.archlinux.org/packages/android-ndk)

**Metadata**

* homepage URL: <https://developer.android.com/ndk/>
* source URL: https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
* license: lgpl
* platforms: unix, linux, darwin, ...

**Comment by NickCao** [comment]
See https://nixos.org/manual/nixpkgs/unstable/#android
