### ISSUE TITLE
Package request: android-sdk

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#245050]
**Project description**

Google Android SDK

Refer:
- [ArchLinux](https://aur.archlinux.org/packages/android-sdk)

**Metadata**

* homepage URL: https://developer.android.com/studio/releases/sdk-tools.html
* source URL: https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
* license: unfree
* platforms: linux

**Comment by NickCao** [comment]
See https://nixos.org/manual/nixpkgs/unstable/#android

**Comment by Freed-Wu** [comment]
```shell
export NIXPKGS_ACCEPT_ANDROID_SDK_LICENSE=1
nix-shell -p androidenv.androidPkgs_9_0.androidsdk --impure
```
