### ISSUE TITLE
Cannot  build python36Packages.pycairo

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#24501]
## Issue description

Trying to build `pycairo` fails with `AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'`. This is a known issue as indicated [here](https://bugs.freedesktop.org/show_bug.cgi?id=76759) and [here](https://svnweb.freebsd.org/ports/head/graphics/py3-cairo/files/pycairo-1.10.0-waf-py3_5.patch?revision=401900&view=markup).

### Steps to reproduce

`nix-shell -p python36Packages.pycairo`

## Technical details

* System: 17.09pre104652.08c87ee (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.09pre104652.08c87ee"

**Comment by vaibhavsagar** [comment]
`nix-shell -p python35Packages.pycairo` works without any issues.

**Comment by vaibhavsagar** [comment]
It looks like [this line](https://github.com/NixOS/nixpkgs/blob/00689b20a8a1c9c6c24891c46669b0e6b0f7d68c/pkgs/development/python-modules/pycairo/default.nix#L36) needs to be updated to work with `isPy36` as well.

**Comment by FRidh** [comment]
This is fixed now.
