### ISSUE TITLE
NixOS Syncthing "merge-syncthing-config" fails configuration updater preventing Syncthing service from running

### ISSUE THREAD

**Issue by mfed3** [NixOS/nixpkgs#245121]
### Describe the bug
In unstable channel, NixOS Syncthing `merge-syncthing-config` fails to run the configuration updater preventing Syncthing service from running. The error seems to have to do with additional unnecessary quotes being injected into the Syncthing config such as the characters ''. (See below). 

### Steps To Reproduce
1. Switch from nix pkgs stable to unstable using a syncthing config containing a `settings` section (switches from version 1.23.4 to 1.23.6.
2. Note that the schema changes in 1.23.6 to add `services.syncthing.settings` instead of `services.syncthing` (used when defining folders and devices)
2a. See 1.23.4: https://search.nixos.org/options?channel=23.05&show=services.syncthing.devices&from=0&size=50&sort=relevance&type=packages&query=syncthing 
2b. See 1.23.6: https://search.nixos.org/options?channel=unstable&show=services.syncthing.settings.devices&from=0&size=50&sort=relevance&type=packages&query=syncthing
4. Run `nixos-rebuild switch --upgrade`. The build will pass compilation check but fail in the syncthing config update phase, preventing the service from running

### Expected behavior

`merge-syncthing-config` should not throw `jq: error: syntax error, unexpected INVALID_CHARACTER` error and should successfully populate the Syncthing config as it did in the previous version

### Screenshots

```
[myuser@mycomputer:~]$ sudo nixos-rebuild switch --upgrade
unpacking channels...
building Nix...
building the system configuration...
activating the configuration...
setting up /etc...
reloading user units for myuser...
setting up tmpfiles
warning: the following units failed: syncthing-init.service

× syncthing-init.service - Syncthing configuration updater
     Loaded: loaded (/etc/systemd/system/syncthing-init.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-07-23 20:15:30 EDT; 38ms ago
    Process: 44451 ExecStart=/nix/store/jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config (code=exited, status=3)
   Main PID: 44451 (code=exited, status=3)
         IP: 26.9K in, 1.7K out
        CPU: 8ms

Jul 23 20:15:30 mycomputer systemd[1]: Starting Syncthing configuration updater...
Jul 23 20:15:30 mycomputer jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config[44459]: jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 2:
Jul 23 20:15:30 mycomputer jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config[44459]:         "devices": (''[]'' + .devices),
Jul 23 20:15:30 mycomputer jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config[44459]: jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 3:
Jul 23 20:15:30 mycomputer jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config[44459]:         "folders": (''[]'' + .folders)
Jul 23 20:15:30 mycomputer jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config[44459]: jq: 2 compile errors
Jul 23 20:15:30 mycomputer systemd[1]: syncthing-init.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jul 23 20:15:30 mycomputer systemd[1]: syncthing-init.service: Failed with result 'exit-code'.
Jul 23 20:15:30 mycomputer systemd[1]: Failed to start Syncthing configuration updater.
Jul 23 20:15:30 mycomputer systemd[1]: syncthing-init.service: Consumed 8ms CPU time, received 26.9K IP traffic, sent 1.7K IP traffic.
warning: error(s) occurred while switching to the new configuration



× syncthing-init.service - Syncthing configuration updater
     Loaded: loaded (/etc/systemd/system/syncthing-init.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-07-23 20:15:30 EDT; 38ms ago
    Process: 44451 ExecStart=/nix/store/jgvf4vcqfnk9xdfk44ck0jx7awiqcwgz-merge-syncthing-config (code=exited, status=3)
   Main PID: 44451 (code=exited, status=3)
         IP: 26.9K in, 1.7K out
        CPU: 8ms
```

### Additional context

Note that this merge function will fail even with a blank settings defined like so, proving that there are no issues in my user specific config:

```
{ config, lib, pkgs, ... }:

{  
  services.syncthing = {
    enable = true;
    dataDir = "/home/myuser";
    user = "myuser";
    openDefaultPorts = true;
    overrideDevices = true;
    overrideFolders = true;
    settings = {

    };
  };
}
```

### Notify maintainers

For situational awareness, adding maintainer of `pkgs/applications/networking/syncthing/default.nix`
~~@r-ryantm~~

Developers who last modified `nixos/modules/services/networking/syncthing.nix`
@Lassulus and @doronbehar 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.4.4, NixOS, 23.11 (Tapir), 23.11pre506474.12303c652b8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by theotheroracle** [comment]
also experiencing this

**Comment by doronbehar** [comment]
Aish... Indeed `nixosTest.syncthing-init` fails as well. I'm so sorry we didn't catch that in https://github.com/NixOS/nixpkgs/pull/233386 ... For sure https://github.com/NixOS/nixpkgs/pull/230196 should fix that. That mixed `jq` and Nix code is pretty hard to debug, so perhaps you'd be willing to test #230196 ? And with your approval it will get in faster? What do you think @Lassulus ?

**Comment by doronbehar** [comment]
#230196 just got merged, so this should be fixed. I will keep this open in the meantime until #230196 gets into the channels so people will find this issue.

**Comment by kquote03** [comment]
> #230196 just got merged, so this should be fixed. I will keep this open in the meantime until #230196 gets into the channels so people will find this issue.

Thank you for the fix, how long does it usually take for it to get into channels? Thank you

**Comment by Lassulus** [comment]
usually 1-2 days, it seems there is a build problem on unstable right now: https://status.nixos.org/ so maybe a bit longer until that has been fixed, progress can be tracked via https://nixpk.gs/pr-tracker.html?pr=230196

**Comment by mfed3** [comment]
Cool, I'll re-test when I see it get into the channels. What would I want to follow to know when a merged commit gets built into unstable repo?

**Comment by theotheroracle** [comment]
seems to be fixed for me

**Comment by doronbehar** [comment]
#230196 has landed in `nixos-unstable`. Closing.
