### ISSUE TITLE
gccStdenv on Darwin broken (locally?)

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#245167]
### Describe the bug
Trying to use a `gccStdenv` on Darwin locally is broken for me. A good test for this is `acme-client`.

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/yhgcqdkp09pxcihllw2b1j3h8645y7hf-acme-client-1.3.2.tar.gz
source root is acme-client-1.3.2
setting SOURCE_DATE_EPOCH to timestamp 1686437304 of file acme-client-1.3.2/usr.sbin/acme-client/parse.c
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
configure flags: --disable-dependency-tracking --prefix=/nix/store/p5y4jvndi9p9qjlmvr6lnwjx0wm6vwah-acme-client-1.3.2
checking build system type... i386-apple-darwin17.7.0
checking host system type... i386-apple-darwin17.7.0
checking for a BSD-compatible install... /nix/store/8fr8kndrn5ga5agybsnncl966spqs5fv-coreutils-9.3/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/8fr8kndrn5ga5agybsnncl966spqs5fv-coreutils-9.3/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-acme-client-1.3.2.drv-2/acme-client-1.3.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

```
configure:3244: checking for C compiler version
configure:3253: gcc --version >&5
ld: unknown option: -fPIC
```

But fetching built derivations from cache.nixos.org works fine?

### Steps To Reproduce
1. Nixpkgs https://github.com/NixOS/nixpkgs/commit/9ca785644d067445a4aa749902b29ccef61f7476
2. `nix-build -A acme-client` downloads fine from cache.nixos.org
3. `nix-build -A acme-client --check` fails with the above error

### Expected behavior
`gccStdenv` works locally.

### Screenshots
n/a

### Additional context
- Disabling PIC hardening instead makes it complain about `-O2`.
- Starts to fail between 69eb0416d54 and 2bc2bf30f78 on nixos-unstable, trying to bisect.

### Notify maintainers
I'm not sure what broke this & where, and the stdenvs & cc-wrapper derivations & files don't have any listed maintainers. Maybe @reckenrode because you recently touched Darwin stdenv?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-darwin"`
- host os: `Darwin 17.7.0, macOS 10.13.6`
- multi-user?: `no`
- sandbox: `no`
- version: `nix-env (Nix) 2.13.3`
- channels(puna): `"nixpkgs"`
- nixpkgs: `/users/puna/.nix-defexpr/channels/nixpkgs`
```

**Comment by reckenrode** [comment]
I think I know what the problem is, but it doesn’t make sense to me. The stdenv rework included a change to make use of response files conditional based on the size of `ARG_MAX`. acme-client builds locally for me because I’m on aarch64-darwin (where it’s large enough not to need response files). _However_, if I manually force it to use a response file …

```console
$ NIX_CC_USE_RESPONSE_FILE=1 gcc
ld: unknown option: -fPIC
collect2: error: ld returned 1 exit status
```

If I hack up the cc-wrapper script to put the response file in a file, it works. Does GCC not support response files when they’re created via process substitution?

**Comment by reckenrode** [comment]
I’m working on a patch for cc-wrapper to address this issue. It needs to rebuild the stdenv before I can test and confirm the build works for acme-client.
