### ISSUE TITLE
Can not have flake8 and ipython in the same python env

### ISSUE THREAD

**Issue by orivej** [NixOS/nixpkgs#24517]
## Issue description

Trying to install python env with flake8 and ipython in NixOS unstable fails:
```
building path(s) ‘/nix/store/ija4agg1iyf7541y56pdgxfmkxbf34v2-python-2.7.13-env’
collision between `/nix/store/12kp93bhx28ii1713p3xz9g0naz1hd3k-python2.7-configparser-3.5.0/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/nn8chrxk6dk2k6css8x7v171ry8kw6js-python2.7-backports.shutil_get_terminal_size-1.0.0/lib/python2.7/site-packages/backports/__init__.py'
builder for ‘/nix/store/16jjbk3kg1b1yd6q48pvj7i6zygi0kyp-python-2.7.13-env.drv’ failed with exit code 25
```

### Steps to reproduce

1. Upgrade NixOS unstable to `nixos-17.09pre104652.08c87ee`
2. Append `[(pkgs.pythonFull.withPackages (ps: with ps; [flake8 ipython]))]` to `environment.systemPackages` and try to switch.

## Technical details

* System: 17.09.git.72a18ef (this is 08c87ee with a few irrelevant commits on top)
* Nix version: 1.11.8
* Nixpkgs version: 17.09.git.72a18efebaM

**Comment by FRidh** [comment]
That's correct. The solution here is to use `python.buildEnv` and pass `ignoreCollisions`. Check the Nixpkgs manual for details. The reason this collision occurs on Python 2 is because the packages here are namespace packages. `withPackages` by default does not ignore collisions although we might want to change that behavior.

**Comment by orivej** [comment]
Thank you! This was surprising even though I have read the manual. Created #24537 to clarify the documentation.

**Comment by bennofs** [comment]
What's the actual
