### ISSUE TITLE
Update request: 8.0.100-preview.5.23303.2 → 8.0.100-preview.6.23330.14

### ISSUE THREAD

**Issue by thangchung** [NixOS/nixpkgs#245163]
- Package name: nixos.dotnet-sdk_8, nixos.dotnet-runtime_8
- Latest released version: 8.0.100-preview.6.23330.14
- Current version on the unstable channel: 8.0.100-preview.5.23303.2 => https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/compilers/dotnet/versions/8.0.nix

**Notify maintainers**

-----

@felschr

Note for maintainers: Please tag this issue in your PR.

**Comment by felschr** [comment]
@kuznero @mdarocha
