### ISSUE TITLE
ricochet package doesn't launch

### ISSUE THREAD

**Issue by theotheroracle** [NixOS/nixpkgs#245239]
### Describe the bug

the ricochet package fails with the error "the tor process was not started successfully, this is most likely an instalation or system error execvp: no such file or directory"

### Steps To Reproduce
1. `nix run nixpkgs#ricochet`

### Expected behavior
ricochet to launch

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/20211219/d918ea92-4be5-4f4d-89bc-6b7c7d4c3e9b)

### Additional context
the package should probably be updated to use ricochet-refresh, but that's currently segfaulting for an unknown reason
https://github.com/blueprint-freespeech/ricochet-refresh/issues/175

### Notify maintainers

@codsl 
@jgillich 
@np 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[I] hive@uranus : ~ ඞ
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.39, NixOS, 23.11 (Tapir), 23.11pre506474.12303c652b8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(hive): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by theotheroracle** [comment]
ok ! i created a new package for ricochet-refresh and i'm getting the same issue :thinking:

**Comment by theotheroracle** [comment]
couldn't find any documentation to suggest i'm using it wrong, and the error is generic enough to not really communicate anything, skimming the source code didn't really show any obvious issues, here's [my package](https://fem.mint.lgbt/theotheroracle/ricochet-refresh-nixpkgs) and here's an issue on the package side discussing the issue, https://github.com/blueprint-freespeech/ricochet-refresh/issues/175

**Comment by theotheroracle** [comment]
alright ! i figured out the issue, qt just couldn't find the tor binary, so i added it to the qtwrapper and it's working fine now !

**Comment by KiaraGrouwstra** [comment]
would you have a sample snippet or PR for this?

**Comment by aktaboot** [comment]
ricochet is deprecated in favour of ricochet-refresh, it has been removed from nixpkgs as of #291452 

I guess this can be closed now :)

**Comment by edgar-vincent** [comment]
The exact same issue is affecting ricochet-refresh here.
