### ISSUE TITLE
Thunderbird 115 calendar not visible

### ISSUE THREAD

**Issue by bburdette** [NixOS/nixpkgs#245263]
### Describe the bug
When I open thunderbird 115, the calendar is not visible.  

There's a [thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1843007) about it, a problem in the upstream libicu I think.  They are using a patched libicu.  

### Steps To Reproduce

1. install thunderbird from unstable
2. look at the calendar
3. nothing
4. go back to stable thunderbird
5. calendar events visible.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/157330/028431ed-e766-442d-81d1-deb70aa9064a)

### Additional context
See above, thunderbird bug, libicu.  

### Notify maintainers
@lovesegfault @pierron @vcunat

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.05 (Stoat), 23.05.20230713.fcc147b`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - nixpkgs: `not found`

**Comment by mohe2015** [comment]
This should've been fixed pretty recently. Maybe try updating nixpkgs to the latest version.

**Comment by vcunat** [comment]
Not even very latest.  We merged it on July 13: https://github.com/NixOS/nixpkgs/pull/243179#event-9807798831

**Comment by bburdette** [comment]
Ok, there's the issue.  Missed that in my search.  Its working for me now, thanks.
