### ISSUE TITLE
Setting environment related options on non DE setups!

### ISSUE THREAD

**Issue by noisecrew** [NixOS/nixpkgs#24534]
Hello;
Running a fluxbox only system I face some problems setting basic things such as:

- Mouse/cursor Theme
- Default (preferred) application (like changing something instead of xterm as default terminal)
- Setting system wide values (like default  authentication agent line xdg-su or gksu).
- managing system wide aliases (like ls -gpH and others)
I am sure there are ways to set these; but I am on the dark. So please shed some light on these matters.
Thank You :)

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by FliegendeWurst** [comment]
Seems better suited to ask on https://discourse.nixos.org/
