### ISSUE TITLE
Package request: LibreTranslate

### ISSUE THREAD

**Issue by xxxcrow** [NixOS/nixpkgs#245376]
**Project description**

Free and Open Source Machine Translation API, entirely self-hosted. Unlike other APIs, it doesn't rely on proprietary providers such as Google or Azure to perform translations. Instead, its translation engine is powered by the open source Argos Translate library.

**Metadata**

* homepage URL:  https://libretranslate.com
* source URL: https://github.com/LibreTranslate/LibreTranslate
* license: GNU Affero General Public License v3
* platforms: Python

**Comment by misuzu** [comment]
Already packaged: https://github.com/NixOS/nixpkgs/pull/228563

**Comment by xxxcrow** [comment]
Oh, sorry, I didn't check unstable

**Comment by xxxcrow** [comment]
Or I checked, but in options
And it seems there's no options

**Comment by misuzu** [comment]
> @misuzu sorry, but how do I add librentranslate as a service? 🥹

https://github.com/NixOS/nixpkgs/pull/243050

In the meantime something like this should work too:

```nix
{
  systemd.services.libretranslate = {
    description = "LibreTranslate service";
    after = [ "network.target" ];
    wantedBy = [ "multi-user.target" ];
    environment = {
      HOME = "/var/lib/libretranslate";
    };
    serviceConfig = {
      ExecStart = "${cfg.package}/bin/libretranslate";
      DynamicUser = true;
      WorkingDirectory = "/var/lib/libretranslate";
      StateDirectory = "libretranslate";
    };
  };
}
```

**Comment by TheProfessionalSillyGoose** [comment]
I'm experiencing an issue attempting to translate from spanish to english 

"from sacremoses.tokenize import MosesTokenizer, MosesDetokenizer
ModuleNotFoundError: No module named 'sacremoses'" 

Does anyone else have this error? Other languages translated to english work fine. I've attempted to download the sacremoses python package to both environment and user but to no avail.
