### ISSUE TITLE
spdlog fails to build on nixos with latest unstable and master

### ISSUE THREAD

**Issue by pimeys** [NixOS/nixpkgs#245336]
### Describe the bug

Spdlog package is called with wrong parameters in some point of nixpkgs. It expects `fmt_9` but gets `fmt`.

### Steps To Reproduce
1. `git clone https://github.com/pimeys/nixos`
2. `nix flake update`
3. `nixos-rebuild --flake '.#purrpurr' build`

### Expected behavior
The flake builds successfully.

### Screenshots
Instead we get an error:

```console
❯ nixos-rebuild --flake '.#purrpurr' build
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error:
       … while calling the 'head' builtin

         at /nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while evaluating the attribute 'value'

         at /nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source/lib/modules.nix:768:9:

          767|     in warnDeprecation opt //
          768|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          769|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'fmt'

       at /nix/store/nhk2gnp8jf1xshlym3g63m6k7v35p21h-source/pkgs/development/libraries/spdlog/default.nix:1:1:

            1| { lib
             | ^
            2| , stdenv
       Did you mean fmt_9?
```

### Additional context
Works well if I don't update the flakes, so this error happened in the past week or so.

### Notify maintainers

Pinging @doronbehar due to you updating something similar to the package the last time, and @obadz who's the maintainer of the package.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/skjaxjyjqf933mw7pcnhxzms9hk593q9-nix-info
copying path '/nix/store/skjaxjyjqf933mw7pcnhxzms9hk593q9-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230715.8acef30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(pimeys): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pimeys** [comment]
Linking the pull request that might've caused this https://github.com/NixOS/nixpkgs/pull/240730

**Comment by doronbehar** [comment]
It's weird, CI was green when I merged #240730, and newly opened PRs still have a green CI - meaning that evaluation in `master` within nixpkgs is OK. Running with `--show-trace` implies that this has something to do with the `waybar` home-manager module. I'm keep investigating.

**Comment by pimeys** [comment]
That comes from the Wayland overlay... Maybe update that or I'll switch to the packages from unstable.

**Comment by K900** [comment]
Closing here as it's not a nixpkgs issue.
