### ISSUE TITLE
blackbox-terminal: confirmation dialog for closing a tab or window when there are running commands doesn't work

### ISSUE THREAD

**Issue by pearsche** [NixOS/nixpkgs#245310]
### Describe the bug
Basically, it doesn't ever appear. Tabs or windows can be closed without giving any kind of confirmation.

### Steps To Reproduce
1. open htop for example
2. close tab or window
3. it just closes

### Expected behavior
It should show a dialog to ask the user whether they want to close the window because there's running processes still

### Notify maintainers
@chuangzhu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.13, NixOS, 23.11 (Tapir), 23.11.20230722.12303c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by chuangzhu** [comment]
cc @tfmoraes

**Comment by chuangzhu** [comment]
For some reason, the arrow function defined in https://gitlab.gnome.org/raggesilver/blackbox/-/blob/v0.14.0/src/widgets/Terminal.vala#L467-475 is never called. I don't know why but changing it back to a named function solves this problem. I'll open a MR to the upstream shortly.
