### ISSUE TITLE
glibcLocales: locale-archive not reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#245360]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A glibcLocales --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A glibcLocales)
```

### Additional context

https://reproducible.nixos.org/nixos-iso-minimal-r13y/diff/a5b3d7c7fa7c4b466f81cc390b0c87c59fc78a650e277a7e8f5339f84a54dff2-038a1fe81e3a2e2fe8bc7e3ff517c0cf41494c88116a14d502a6589dbae6af39.html

according to [this manpage](https://www.man7.org/linux/man-pages/man1/localedef.1.html), "A locale archive is a memory-mapped file which contains all the system-provided locales" - oh great

**Comment by trofi** [comment]
AFAIU locale generation consists of roughly 2 steps:
1. parallel building of individual locales with `localedef` calls (`build-one-locale` macro in `glibc`'s  `localedata/Makefile`)
2. final merge into `locale-archive`

1. Should not depend on the order of excution (but might depend on the environment?)
2. Should not either as it's ran after `[1.]` complete (but might depend on file list on disk?)

I hope for a simple bug somewhere in `glibc's` `Makefile`.

**Comment by trofi** [comment]
Adding a bit of logging:

```diff
--- a/localedata/Makefile
+++ b/localedata/Makefile
@@ -465,6 +465,9 @@ define build-one-locale
        echo -n `echo $$locale | sed 's/\([^\@]*\)\(\@.*\)*/\2/'`; \
        echo -n '...'; \
        input=`echo $$locale | sed 's/\([^.]*\)[^@]*\(.*\)/\1\2/'`; \
+       echo $(LOCALEDEF) $$flags --alias-file=../intl/locale.alias \
+                    -i locales/$$input -f charmaps/$$charset \
+                    $(addprefix --prefix=,$(install_root)) $$locale; \
        $(LOCALEDEF) $$flags --alias-file=../intl/locale.alias \
                     -i locales/$$input -f charmaps/$$charset \
                     $(addprefix --prefix=,$(install_root)) $$locale \
```

here are the commands used to populate locale archive:

```
I18NPATH=. GCONV_PATH=/build/build/iconvdata LC_ALL=C localedef --little-endian --prefix=/build --alias-file
=../intl/locale.alias -i locales/zh_SG -f charmaps/UTF-8 zh_SG.UTF-8
```

It's a bit worrying that `--no-archive` flag is not passed there. It probably means we do update `locale-archive` in multiple processes.

**Comment by trofi** [comment]
Proposed disabling ot parallel locale building for now as: https://github.com/NixOS/nixpkgs/pull/246049

**Comment by trofi** [comment]
Gentoo for example uses the following: https://gitweb.gentoo.org/proj/locale-gen.git/tree/locale-gen

- `--no-archive` for parallel phase
- `--add-to-archive` for sequential phase

Would be nice if upstream glibc did it for us.

**Comment by amjoseph-nixpkgs** [comment]
> according to [this manpage](https://www.man7.org/linux/man-pages/man1/localedef.1.html), "A locale archive is a memory-mapped file which contains all the system-provided locales" - oh great

I am totally unsurprised...  glibc is full of these kinds of things... unnecessary use of advanced OS features without forethought for the grief they might cause.

**Comment by amjoseph-nixpkgs** [comment]
> Gentoo for example uses the following: https://gitweb.gentoo.org/proj/locale-gen.git/tree/locale-gen

I wonder if it's worth us packaging this and using it.

**Comment by vcunat** [comment]
A fix reached master.
