### ISSUE TITLE
Recursive overlays

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#245417]
**Is your feature request related to a problem? Please describe.**
Some packages are nested, e.g. `vimPlugins`, `mpvScripts`. Overlaying custom packages to these sets is a bit annoying, because you need to manually extend them.

**Describe the solution you'd like**
These package sets are already marked as such (with `recurseIntoAttr`), so it would be nice if they can be automatically merged recursively.

This way, you can just index your custom packages like this:

`pkgs.nix`
```nix
{ pkgs ? (import <nixpkgs>) { } }: {
  some = package;
  more = packages;
  mpvScripts = pkgs.lib.recurseIntoAttr {
    foo = pkgs.callPackage ./bar.nix { }
  };
}
```

And now you can just drop it straight into your overlays:

`configuration.nix`
```nix
nixpkgs.overlays = [ 
  final: prev: import ./pkgs.nix
];
```

**Describe alternatives you've considered**
For now, if you want to extend the packages inside these sets, you need to treat it specially with `.extend`:

```nix
_: prev: {
  vimPlugins = prev.vimPlugins.extend (_: _: {
    foo = bar;
  });
}
```

or for plain attribute sets, with `//`:

```nix
_: prev: {
  mpvScripts = prev.mpvScripts // {
    foo = bar;
  });
}
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Artturin** [comment]
I think that would add a lot of complexity for a little gain

Right now the overlay mechanism is simple with lib.extends https://github.com/NixOS/nixpkgs/blob/12f21439d54693eb07647b27ba05c9e2163ab2b4/pkgs/top-level/stage.nix#L286



Sets like those should use makeScope so they get `.overrideScope`
