### ISSUE TITLE
Some Emacs packages got broken with 17.03

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#24540]
## Issue description

Hi.
Some Emacs packages which were ok at 16.09 got broken with 17.03

### Steps to reproduce

- Adding `zerodark-theme` leads to `output path ‘/nix/store/s2id04jc7lrhnilsc9vgi8i1p1003jxy-font-lock+.el’ has sha256 hash ‘0iajkgh0n3pbrwwxx9rmrrwz8dw2m7jsp4mggnhq7zsb20ighs30’ when ‘0ffs2c7gyhfa2mskdh7a1yp0na99kk282zm4zn56ljp55rrnnnh0’ was expected` error
- If I activate `ergoemacs-mode`, Emacs shows the error `Opening output file: No such file or directory, /home/gnidorah/.emacs.d/ergoemacs-extras/ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz`. It doesn't matter whether it was installed from `melpaStablePackages` or `melpaPackages`. One from `elpaPackages` loads but produces a warning `Invalid slot name: #<ergoemacs-theme-component-map-list ergoemacs-theme-component-map-list>, standard`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by mdorman** [comment]
With regard to the sha issue with `font-lock+.el`---I think this is just an inherent conflict between melpa being willing to get code off of emacswiki.org, and nix's desire for stable identifiers---if you look at the sha on `master`, it matches what is expected, but it only dates back to 2017-03-02.

@ttuegel should we update the sha in the `font-lock+.el` expression for the release?

**Comment by mdorman** [comment]
With regard to `ergoemacs-mode`---whatever it's baroque initialization code is doing, it is apparently not smart enough to simply `mkdir ~/.emacs.d/ergoemacs-extras/`, instead electing to get itself into some infinite-seeming loop.  I would suggest reporting a bug upstream.

Doing that `mkdir` manually allowed it to start, at which point I discovered it was apparently written by someone who doesn't actually like emacs---I barely escaped. :)  Good luck!

**Comment by rzetterberg** [comment]
I have the same problem with a fresh NixOS 17.03. Script to reproduce this problem:

```bash
#!/usr/bin/env bash

test_dir=$(mktemp -d)

pushd $test_dir

cat <<EOF > default.nix
{ pkgs ? import <nixpkgs> {} }:

let
  emacsWithPackages = (pkgs.emacsPackagesNgGen pkgs.emacs).emacsWithPackages;
in
  emacsWithPackages (epkgs: (with epkgs.melpaStablePackages; [
    zerodark-theme
  ]))
EOF

nix-build default.nix

popd

rm -rf $test_dir
```

Will produce the following output:

```
these derivations will be built:
  /nix/store/5dazdrnv260bg23sdfmjjv0ymzwxff3j-font-lock-plus.drv
  /nix/store/zbxigj6v897gf2vmjlx5lc3qdr50qp79-font-lock+.el.drv
  /nix/store/y77x6znrqmbla3mpbi1h8x5cvafsvl55-emacs-font-lock-plus-20170101.947.drv
  /nix/store/18f3aimx2pxx6d819r19mfxh74rcv21y-emacs-all-the-icons-2.2.0.drv
  /nix/store/hbl6hqrkvph25qcnimwhv13jnbm1bz10-pkg-info.drv
  /nix/store/zcr3vd4nwdm8vv1mlbs528hpwzznwjgg-pkg-info.el-f9bb471ee95d1c5fe9adc6b0e98db2ddff3ddc0e-src.drv
  /nix/store/v0ab1dr7glx1lg9sva5ncik7vq6232lb-emacs-pkg-info-0.6.drv
  /nix/store/pbj4qrcpk318zzl18f5x15sgqnf2a1dy-let-alist-1.0.5.el.drv
  /nix/store/wiwjwkrplqi1mbbzxqj8zn8bj8sv6h7p-emacs-let-alist-1.0.5.drv
  /nix/store/pl97nfwc1k04vxdzkcgppwxlh87r5h12-emacs-flycheck-30.drv
  /nix/store/b2l6glxi8nl03213yq1b670gdaqqw3ij-emacs-zerodark-theme-4.2.drv
  /nix/store/49rjkx6f4bjjm9l9y9wflkg4qf8z53cd-emacs-packages-deps.drv
  /nix/store/aqrgfjymwa8vysg1886b89rjvkf5cvc6-emacs-with-packages-25.1.drv
building path(s) ‘/nix/store/s2id04jc7lrhnilsc9vgi8i1p1003jxy-font-lock+.el’

trying https://www.emacswiki.org/emacs/download/font-lock+.el
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19202    0 19202    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
output path ‘/nix/store/s2id04jc7lrhnilsc9vgi8i1p1003jxy-font-lock+.el’ has sha256 hash ‘0iajkgh0n3pbrwwxx9rmrrwz8dw2m7jsp4mggnhq7zsb20ighs30’ when ‘0ffs2c7gyhfa2mskdh7a1yp0na99kk282zm4zn56ljp55rrnnnh0’ was expected
cannot build derivation ‘/nix/store/y77x6znrqmbla3mpbi1h8x5cvafsvl55-emacs-font-lock-plus-20170101.947.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/3cygxp1xk8364yhvkw739y4y602ibvgy-let-alist-1.0.5.el’
cannot build derivation ‘/nix/store/18f3aimx2pxx6d819r19mfxh74rcv21y-emacs-all-the-icons-2.2.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/b2l6glxi8nl03213yq1b670gdaqqw3ij-emacs-zerodark-theme-4.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/aqrgfjymwa8vysg1886b89rjvkf5cvc6-emacs-with-packages-25.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/aqrgfjymwa8vysg1886b89rjvkf5cvc6-emacs-with-packages-25.1.drv’ failed
```

**Comment by gnidorah** [comment]
@mdorman Thank you much for fixing!
