### ISSUE TITLE
[FYI] pykde4 broken on master

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#24548]
## Issue description

According to hydra ([Latest builds for job nixpkgs:trunk:kde4.pykde4.x86_64-linux](https://hydra.nixos.org/job/nixpkgs/trunk/kde4.pykde4.x86_64-linux/all?page=1)) `kde4.pykde4` is broken since 2017-03-10. I.e. the between 32bcda741a9f58d376ad1f1de0b051571cddc3d2 and 665a89c4a4d2b8c9b450da92a66aa23368fa5ec1. Looking at the history I suspect it was a0f3590c5bf23bd8ac877ff6b88d06163e4b1757 (pyqt4: 4.11.3 -> 4.12). Seems like it doesn't work with the new version...

cc @vbgl @FRidh @ttuegel @Phreedom @abbradar - Any ideas how we could fix this?

**Comment by FRidh** [comment]
The build fails due to a wrapper in another package. Likely it tries to import the script instead of running it. That is something that should be possible with Python scripts but is broken with our Python infra (and as far as I can tell impossible to fix):
```
cp ../config.xml config.xml
xml2po --expand-all-entities -l da -p ../po/da.po -o chfn.1.xml ../chfn.1.xml
  File "/nix/store/wgvhfq8vpf9j4zi1wcbybw4y368ignkx-gnome-doc-utils-0.20.10/bin/.xml2po-wrapped", line 24
    import sys;import site;import functools;import sys; import os; try: sys.argv[0] = os.environ[NIX_PYTHON_NAME]; except KeyError: pass;;functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/wgvhfq8vpf9j4zi1wcbybw4y368ignkx-gnome-doc-utils-0.20.10/lib/python2.7/site-packages','/nix/store/nb115pmskvbyk2plj0lm6xb41zi3kwjb-libxml2+py-2.9.4/lib/python2.7/site-packages','/nix/store/4fbgiyv86624li05hzwfnlg6ypzf2qcs-libxml2-2.9.4-py/lib/python2.7/site-packages','/nix/store/44psbfr2rgkg8l8rnrx16qlkvnkx23py-python2.7-setuptools-30.2.0/lib/python2.7/site-packages'], site._init_pathinfo());
                                                                     ^
SyntaxError: invalid syntax
```

**Comment by FRidh** [comment]
I suppose this package is also going to be removed since we're getting rid of KDE4.
