### ISSUE TITLE
how to run espanso-wayland with systemd service?

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#245466]
### Describe the bug
how to run `espanso-wayland` with systemd service if there is no options `services.espanso.package` to replace `espanso` to `espanso-wayland`?
https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=espanso

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior
provide options `services.espanso.package` to replace `espanso` to `espanso-wayland`.

### Screenshots
no options `services.espanso.package`

![Screenshot_20230726_082552](https://github.com/NixOS/nixpkgs/assets/45872139/33274cb1-d950-482e-a6ed-f76805cd5cdb)

### Notify maintainers
@kimat 
@theHedgehog0 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.05 (Stoat), 23.05.1998.f64b9738da8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(hervyqa): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hervyqa** [comment]
cc: @bobvanderlinden is also [did the last commit](https://github.com/NixOS/nixpkgs/pull/231062).

**Comment by rastarr** [comment]
wondering if there is any update on this? trying to get espanso-wayland to work as well

**Comment by n8henrie** [comment]
May be resolved by https://github.com/NixOS/nixpkgs/pull/298530

**Comment by n8henrie** [comment]
`package` option now exists: https://search.nixos.org/options?channel=unstable&show=services.espanso.package&from=0&size=50&sort=relevance&type=packages&query=espanso
