### ISSUE TITLE
Missing `libnvJitLink.so.12` for `libcusparse`

### ISSUE THREAD

**Issue by herberteuler** [NixOS/nixpkgs#245519]
This is about an issue raised during my attempt to solve the CUDALink problem our Mathematica package has been having. So I was trying to upgrade to `cudaPackages_12`, and while preparing the CUDA environment, I got this error:

```
error: builder for '/nix/store/6dxhhqkc0f533imn2kid75l3a9yrmzxl-libcusparse-12.0.1.140.drv' failed with exit code 1;
       last 10 log lines:
       >     libnvJitLink.so.12 -> not found!
       > setting RPATH to: $ORIGIN
       > auto-patchelf: 2 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libnvJitLink.so.12 wanted by /nix/store/g980kynqblwjc9iyljp3c4diy776cs8f-libcusparse-12.0.1.140/lib/libcusparse.so.12.0.1.140
       > error: auto-patchelf could not satisfy dependency libnvJitLink.so.12 wanted by /nix/store/g980kynqblwjc9iyljp3c4diy776cs8f-libcusparse-12.0.1.140/lib/stubs/libcusparse.so
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/qqfn6c8jv0p90vg91z9b0axmqcxya9l1-stdenv-linux/setup: line 87: pop_var_context: head of shell_variables not a function context
       > /nix/store/qqfn6c8jv0p90vg91z9b0axmqcxya9l1-stdenv-linux/setup: line 1459: pop_var_context: head of shell_variables not a function context
       > /nix/store/qqfn6c8jv0p90vg91z9b0axmqcxya9l1-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/6dxhhqkc0f533imn2kid75l3a9yrmzxl-libcusparse-12.0.1.140.drv'.
error: 1 dependencies of derivation '/nix/store/wsl89apv5dwwmnbf87a1hgv2i6i4zias-mathematica-cuda-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/va8fki5rw73dmxyfjpk7fx8f8x8l55gq-mathematica-cuda-13.3.0.drv' failed to build
```

Seeing [libnvjitlink](https://github.com/NixOS/nixpkgs/blob/c9cf0708f00fbe553319258e48ca89ff9a413703/pkgs/development/compilers/cudatoolkit/redist/manifests/redistrib_12.0.1.json#L902) exists for CUDA 12, I [added it to the definition of `cudaEnv` here](https://github.com/herberteuler/nixpkgs/blob/87fdcde8291d4cdde8b0f1f68f7734a57426266a/pkgs/applications/science/math/mathematica/generic.nix#L58) but the error persisted.

I searched for `libnvjitlink` and found this related [build log](https://gist.github.com/ConnorBaker/1065033fe0d45f9f30f11a25501f4520) from [an earlier PR](https://github.com/NixOS/nixpkgs/pull/240457).

What is the resolution of this issue?

**Comment by herberteuler** [comment]
@NixOS/cuda-maintainers

**Comment by SomeoneSerge** [comment]
> builder for '/nix/store/...-libcusparse-12.0.1.140.drv

Seems like you need to add libnvjitlink to libcusparse's inputs, conditioned on cudaVersion. Have a look at cudatoolkit/redist/overrides.nix, in particular at the example handling libnvrtc-builtins.so

**Comment by fangjunzhou** [comment]
I'm trying to install pytorch with poetry2nix. And it seems that it is not using `cudaPackages.libcusparse` in nixpkg.

I saw this dependency was added to libcusparse in nixpkg explicitly by overlay:

![image](https://github.com/NixOS/nixpkgs/assets/79500078/66fb2033-863c-48b1-8a05-dd982eba5699)

Is there a particular reason `autipatchelf` cannot resolve `libnvjitlink`?

Is it possible to solve this problem for the poetr2nix version cusparse?

**Comment by SomeoneSerge** [comment]
@herberteuler https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F1lb2mkqzkqphvxz2pidgk9ds3l778azi-libcusparse-12.1.2.141.drv/log?via-job=4a656720-547f-4d45-bdb9-e8ff8755db7a looks like a successful build for `cudaPackages_12.libcusparse`. Can you confirm whether the issue persists? I lost the track of this

> I'm trying to install pytorch with poetry2nix. And it seems that it is not using cudaPackages.libcusparse in nixpkg.
> Is it possible to solve this problem for the poetr2nix version cusparse?

I think the proper solution is to add (by default) overrides to `poetry2nix` to rewrite all of the references to pypi cuda wheels with references to nixpkgs' `cudaPackages` which are already being patchelfed correctly more often than not.

The reason the poetry2nix-generated derivation's autoPatchelf "cannot resolve libnvjitlink" is because it has to be added to `buildInputs` for `autoPatchelf` to detect it.

**Comment by fangjunzhou** [comment]
I'll try to override poetry2nix package later. But I guess I'll try to just use nix for python package management

**Comment by SomeoneSerge** [comment]
>  I guess I'll try to just use nix for python package management

Offtopic but I genuinely find this to be the easier option. It would be nice to work out a smooth experience for poetry2nix though, at some point

**Comment by brumik** [comment]
Can someone provide me an example how to fix this? I understand that you probably have a grasp of what going on, and I was able to kinda understand it, but somebody fairly new to nix, trying to use langchain in python with poetry, I have no idea what to do here.

I spent a day with it without luck.

```
      in {
        default = let
          poetryEnv = mkPoetryEnv {
            projectDir = self;
            preferWheels = true;
          };
        in poetryEnv.env.overrideAttrs(old: {
          buildInputs = with pkgs.${system}; [
            cudaPackages_12.libnvjitlink.lib
            # https://github.com/NixOS/nixpkgs/issues/245519
          ];
        });

```

I tried this without success, also as a `buildInput`/`nativeBuildInput` for the shell itself, but the error is always the same.

@SomeoneSerge if you can do a setup for poetry python (or pip) without poetry2nix reliably, I would be glad to see an example working for LLM libs.

**Comment by SomeoneSerge** [comment]
@brumik You didn't include the error message so I can only guess, but you probably need to add libnvjitlink to buildInputs of a specific dependency using poetry2nix's "overrides" (e.g. I see the commit quoted above, 7c103f4, uses mkPoetryEnv with the "overrides" argument - that's probably it, although I"m by no means proficient with poetry2nix).

However, let's please proceed with this conversation on discourse.nixos.org or in https://matrix.to/#/%23users%3Anixos.org. The original issue wasn't about poetry2nix

**Comment by SomeoneSerge** [comment]
```
❯ nix build -f '<nixpkgs>' -I nixpkgs=flake:github:NixOS/nixpkgs/master cudaPackages_12.libcusparse --print-out-paths
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
/nix/store/x3fvp0j8m1scwbdpnib6kbdcm8zr0875-libcusparse-12.1.2.141
```

Cannot reproduce the original error anymore. I presume it's been fixed
