### ISSUE TITLE
steam: openssl/libcrypto errors in various games

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#24555]
## Issue description

Causes launch failure.

`
./runner: relocation error: ./runner: symbol ENGINE_load_builtin_engines, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference
`

So far I've seen this error message in:

- Life Is Strange
- Cook, Serve, Delicious!

### Steps to reproduce

Install Steam. Install one of the above games.  Run steam in a terminal where you can see the log output.  Run one of those games.  See it fail.  Sadface.

## Technical details

* System: NixOS 17.03
* Nix version: 1.11.8
* Nixpkgs version: 0c041520c308057159ba806457c02432920f372f

**Comment by FRidh** [comment]
That's https://github.com/NixOS/nixpkgs/issues/20726

**Comment by benley** [comment]
whoops, I didn't notice the existing issue - thanks.
