### ISSUE TITLE
Move wagtail out of the python package set

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#245552]
## Issue description
Wagtail is an application, not a library, and should therefore not live in the python package set.

Noticed due to breakage when moving the default django version from 3 to 4 in #245436.

```
wagtail> ERROR: Could not find a version that satisfies the requirement Django<4.2,>=3.2 (from wagtail) (from versions: none)
wagtail> ERROR: No matching distribution found for Django<4.2,>=3.2
```

## Remediation

Move the wagtail package into `pkgs/servers/web-apps/`. For its extensions use `packageOverrides` to `callPackage` those derivations.

Example applications doing this are home-assistant or apache-airflow.

## Reasoning

The package set moves at a pace that applications cannot be updated at. Workarounds, like overriding specific packages, are only possibly outside the common python package set, inside the package specific overriden package set.

@sephii

**Comment by sephii** [comment]
Wagtail is not meant to be used as a standalone application, but is used as a library for other projects to use its CMS capabilities (see [the docs](https://docs.wagtail.org/en/stable/topics/pages.html) for more information). It can probably be used as a standalone application, which would be a bit like using a standalone Wordpress without any customization, but I don’t think anyone would use it as-is, except maybe for trying out the product.

If you check [the exposed `wagtail` entrypoint](https://github.com/wagtail/wagtail/blob/39a723f9d1e585100a10054686835847b54198a6/wagtail/bin/wagtail.py#L398), you’ll see the only exposed command is a `start` project, allowing you to create a new Django project with dependencies on Wagtail.

So I don’t think Wagtail should be packaged as a Python application (but maybe I’m missing something).

**Comment by mweinelt** [comment]
Thanks for making the argument.
