### ISSUE TITLE
scdoc does not work as `nativeBuildInputs` with `strictDeps = true`

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#245645]
### Describe the bug

While updating yambar I tried to enable strictDeps. However the meson configure phase failed to find scdoc.
I fixed this by changing it from `nativeBuildInputs` to `buildInputs`

https://github.com/NixOS/nixpkgs/pull/245643

### Steps To Reproduce

1. put scdoc as a nativeBuildInput instead of buildInput
2. build yambar
3. wait for the complains of Meson...

### Expected behavior

scdoc should be found

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230720.2d82894`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
It's looked for with the build pkg-config, so you need `depsBuildBuild = [ pkg-config ];` for the correct hooks to run

**Comment by AndersonTorres** [comment]
Please can you explain?
