### ISSUE TITLE
intel-media-driver FOD mismatch

### ISSUE THREAD

**Issue by brianmcgee** [NixOS/nixpkgs#245687]
### Describe the bug

When building a NixOS config this morning, I started seeing this:

```
error: hash mismatch in fixed-output derivation '/nix/store/mq2hnv52ajivkyjm6f94d87lddg8fmaw-0002-Remove-settings-based-on-ARCH.patch.drv':
         specified: sha256-f4M0CPtAVf5l2ZwfgTaoPw7sPuAP/Uxhm5JSHEGhKT0=
            got:    sha256-o/Pg0S53SYh3O7L+AwxOPl1Bx4TS6iKB8ql8GhhHI/o=
```

It would appear that [this patch](https://salsa.debian.org/multimedia-team/intel-media-driver-non-free/-/raw/master/debian/patches/0002-Remove-settings-based-on-ARCH.patch) has changed.

### Steps To Reproduce
1. Create a NixOS build relying on `intel-media-driver` using latest nixos-unstable

### Expected behavior
It should build cleanly and not complain about the FOD hash mismatch.

### Notify maintainers
@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.39, NixOS, 23.05 (Stoat), 23.05.20230723.ac1acba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(brian): `""`
 - nixpkgs: `/nix/store/01m13r1z6m86vwa0i3aydxpmhyjjpma5-5kzk1ii7nq6a5ch8jwbib8whvi1ri1rl-source`
```

**Comment by brianmcgee** [comment]
Last commit was 3 weeks ago. I've tried building with a URL using a few specific commits going back 6 months and all have the same effect. Could this have been a force push?

**Comment by SuperSandro2000** [comment]
That's because Debian does useless rebases of their patches with no actual changes. We should just pin it to some commit.

**Comment by SuperSandro2000** [comment]
#245687
