### ISSUE TITLE
network-manager segfaults after nixos-rebuild switch

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#24564]
## Issue description

After nixos-rebuild switch, the network-manager service goes down and immediately segfaults every time it tries to come up again.

### Steps to reproduce

1. `nixos-rebuild switch`
2. `sudo systemctl start network-manager.service`
3. check journalctl for the segfault message or something, anyway, at this point I don't have working network anymore.

## Technical details

nixos 17.09pre104870.cc779bc421

**Comment by ben0x539** [comment]
Specifically it segfaults because `.../resolvconf -d NetworkManager` returns a non-zero exit status (saying "No resolv.conf for interface NetworkManager"); the segfault itself appears fixes in their HEAD. I haven't checked whether that makes it actually work, yet, but maybe we could arrange for it to have a resolv.conf in the meantime, whatever that means.

**Comment by Mic92** [comment]
In which commit it was fixed?

**Comment by ben0x539** [comment]
https://github.com/NetworkManager/NetworkManager/commit/4e8eddd100bbc8429806a70620c90b72cfd29cb1

**Comment by Mic92** [comment]
Does this also happen in 17.03?

**Comment by ben0x539** [comment]
Happens with both the 17.03 tag and the 17.03 channel.

Looks like cherry-picking the above commit as a patch for our network-manager lets it work correctly, btw.

**Comment by Mic92** [comment]
also fixed in 17.03: f6558e671a558a292cdba9d0f80da8a5e51ed52f
