### ISSUE TITLE
nextcloud occ can't find previewgenerator commands

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#245691]
### Describe the bug
I am trying to write a module for the nextcloud apps "previewgenerator" 
https://github.com/teto/home/blob/main/nixos/modules/nextcloud.nix (the full configuration of nextcloud being at https://github.com/teto/home/blob/15d453238e0f5f64484a2f23ce4620710b393a52/hosts/neotokyo/nextcloud.nix#L44 , i.e., previewgenerator is part of the installed applications) 

I've restarted the phpfm-nextcloud service but even then:
```
Jul 27 10:33:46 myserver systemd[1]: Failed to start nextcloud-previewgenerator-cron.service.
Jul 27 10:33:46 myserver systemd[1]: nextcloud-previewgenerator-cron.service: Failed with result 'exit-code'.
Jul 27 10:33:46 myserver systemd[1]: nextcloud-previewgenerator-cron.service: Main process exited, code=exited, status=1/FAILURE
Jul 27 10:33:46 myserver nextcloud-occ[133702]:                                                   
Jul 27 10:33:46 myserver nextcloud-occ[133702]:       preview:reset-rendered-texts
Jul 27 10:33:46 myserver nextcloud-occ[133702]:       preview:repair
Jul 27 10:33:46 myserver nextcloud-occ[133702]:       preview:generate
Jul 27 10:33:46 myserver nextcloud-occ[133702]:       notification:generate
Jul 27 10:33:46 myserver nextcloud-occ[133702]:   Did you mean one of these?
Jul 27 10:33:46 myserver nextcloud-occ[133702]:                                                   
Jul 27 10:33:46 myserver nextcloud-occ[133702]:   Command "preview:pre-generate" is not defined.
Jul 27 10:33:46 myserver nextcloud-occ[133702]:                             
```
Seems like the commands installed by preview generator exist https://github.com/nextcloud/previewgenerator/tree/main/lib/Command 
but probably `occ` doesn't see them, not sure how nix installs those commands (or nextcloud for what matters).

### Metadata
nixos-unstable

**Comment by teto** [comment]
@Ma27 did I do something wrong ? how do nextcloud app "commands" get visible from the occ executable ?

**Comment by teto** [comment]
cc @onny since you seem to be on a nextcloud PR streak :)

**Comment by Ma27** [comment]
Haven't found anything obvious wrong[1], so let's try to find out what's wrong exactly.
Does the app appear when listing all installed apps (can be done with `nextcloud-occ app:list`)? Because considering that none of the commands from the app in question appear in the error-text (even though their names are fairly similar) is a strong indicator that this isn't the case.

[1] well, your comment regarding disabling `news` is incorrect, `news` is not compatible with nc27 currently, that's why it cannot be used ;-)

**Comment by teto** [comment]
damn it was disabled ! I remember disabling some default modules but not that one :s . Nextcloud could warn the user that the command is ~ disabled (I might open a ticket if none exists). Seems to work now thanks !

**Comment by teto** [comment]
btw is this something that could be made declarative ? e.g. disabling app would fail in UI because a file is readonly or sthg like that ? So that I can force enabling the app from the nix module.
