### ISSUE TITLE
Basename of current directory goes into derivation

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#24575]
## Issue description

I found that when I build two perfectly identical directory tries (e.g. 2 clones of the same repository, e.g. `myproject` and `myproject2`) with `nix-build`, they get different hashes *if the name of the parent directory is different*.

## Technical details

This is because the `basename` of the directory is used [in the default `unpackPhase` here](https://github.com/NixOS/nixpkgs/blame/6648b04381b8fefb704824f5db898813f22dafbb/pkgs/stdenv/generic/setup.sh#L490).

This creates all kinds of problems, such as build derivations on the Jenkins continuous integration (which creates random temporary directories for builds) being different from those I build on my own computer.

To me this seems wrong: Why should something _above_ my project go into the derivation hash?

If yes, what would be a good workaround for this (how can I enforce that my dir always has the same name, independent of the parent directory's name)?

**Comment by dezgeg** [comment]
> This is because the basename of the directory is used in the default unpackPhase here.

That is not related. It's happening on the `src` line in constructs like:
````
stdenv.mkDerivation {
    name = "foo";
    src = ./.;
}
````

... where when copying the `./.` reference to the store the current directory name is used.

Avoiding that needs some new Nix builtin.

**Comment by nh2** [comment]
> That is not related

@dezgeg I may not have been clear -- yes, I use `./.`, but that uses the `basename` of the directory, and then that goes into the `unpackPhase`.

It seems that I can work around it with

```
  # Make build dir name stable (independent from source dir basename, see )
  unpackCmd = "cp -rp $curSrc mystablename";
```

But that only works for things that use `mkDerivation` directly, e.g. it doesn't work for the current generic Haskell builder.

**Comment by nh2** [comment]
> It seems that I can work around it with

Hmm no, that's not it yet. This sets the directory name inside the build directory to something fixed, but the derivation is still different.

**Comment by nh2** [comment]
I think I now understand what @dezgeg meant.

@dezgeg, where in nix(pkgs) is the `./.` bit implemented that turns `path/to/my/package1/./.` into `/nix/store/abc123abc123-package1`? I guess that's where I need to change things to get things stable.

**Comment by nh2** [comment]
I see, it's actually `filterSource`'s fault: [the basename is used here](https://github.com/NixOS/nix/blob/3ecb09a40a8500d1052b087295b589ca4856fd7a/src/libexpr/primops.cc#L1072)

```c++
static void prim_filterSource(EvalState & state, const Pos & pos, Value * * args, Value & v)
{
    ...
    Path dstPath = settings.readOnlyMode
        ? state.store->computeStorePathForPath(path, true, htSHA256, filter).first
        : state.store->addToStore(baseNameOf(path), path, true, htSHA256, filter, state.repair);
```

**Comment by nh2** [comment]
OK I have a workaround!

Make symlink to the directory itself: `ln -s . code/`.

And then use `filterSource mypredicate ./code` instead of `filterSource mypredicate ./.`.

That way, the basename will be `code`, independent of what the parent dir's basename is.

**Comment by nh2** [comment]
Closing in favour of https://github.com/NixOS/nix/issues/1305 because this is really a `nix` bug, not a `nixpkgs` one.

**Comment by nh2** [comment]
Linking the solution for convenience: https://github.com/NixOS/nix/issues/1305#issuecomment-415902068
