### ISSUE TITLE
Mounting error for HDD (ntfs) 

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#245715]
### Describe the bug
Following the transition from NixOS stable to NixOS unstable, I encountered an issue when attempting to access my NTFS HDD. Remarkably, ntfs3g worked flawlessly before the switch to the unstable channel.

### Error
Error mounting /dev/sda1 at /run/media/user/HDD EXT.:wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.

### Steps To Reproduce
1.  Switch from NixOS stable to unstable.
2.  Try to access an NTFS HDD.

### Expected behavior
Opening the HDD (with write permissions) without encountering issues.

### Additional context
**```boot.supportedFilesystems = [ "ntfs" ];```** does not work as a solution.

### Notify maintainers

@dezgeg 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - host os: `Linux 6.4.4, NixOS, 23.11 (Tapir), 23.11pre507322.b12803b6d90`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(user): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
Duplicate of #243234?

**Comment by W-Y-R** [comment]
The only successful solution was formatting it. By the way, formatting it into NTFS worked perfectly fine, so that's an option worth considering.
