### ISSUE TITLE
Xen-bridge sets incorrect netmask when using non default values for bridge adress/netmask

### ISSUE THREAD

**Issue by praduca** [NixOS/nixpkgs#24588]
## Issue description
The xen bridge configuration set both the address and the netmask as `virtualisation.xen.bridge.address = 172.16.0.1`  and `virtualisation.xen.bridge.prefixLength = 16`. However, modifying the default behaviour only works for the address, the mask alters strangely.

### Steps to reproduce
Set `virtualisation.xen.bridge.address` to `10.3.0.1`  - works
Set `virtualisation.xen.bridge.prefixLength` to 23 gives 8 bit mask (255.0.0.0)

## Technical details

* System: 17.03.873.0c041520c3 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.873.0c041520c3"

Obs: this happens with the previous version of NixOS too (16.09).

**Comment by praduca** [comment]
Apart from the bug, there is any place with a minimal valid configuration for xen on nixos (with  networking)? I must say it is being much a challenge to me to do it work - haven't to this time :(

**Comment by oxij** [comment]
I plan to eventually split dom0 module into two:

* most of the current dom0,
* "normal networking setup profile",

But, currently, I just comment out the networking part of dom0 module
and configure things by hand, unfortunately :(

Your best bet, AFAICS, is, too, to comment out networking setup in dom0,
check that your VMs boot, and then reimplement networking you want using
other modules (define bridges as `networking.bridges`, run your own
`dnsmasq` and so on).

Clearly, not enough people are using Xen on NixOS to make something
generic. I don't have spare time for NixOS Xen ATM, but I hope to get
some later. So, please, share your results in meantime.

(/me sends rays of Xen-love your way)

**Comment by praduca** [comment]
Thanks, I will. My problem is I am VERY new to nixos, so even find the way to do simple things is being a challenge :) 
By the way, enabling and configuring ovswitch by default for this (xen) is a good idea? On other systems (I used Ubuntu just this way for more than a year) this is kinda easy to do, at least for basic networking, and seems easier (at least on the configuration part). Closer to an actual config on real hardware, i mean.

**Comment by michalpalka** [comment]
Hi @praduca, can you check if pull request #25281 solves your problem?

Overall, I agree that the networking code in the xen service needs rework, but we can fix this particular issue easily, as the code setting the netmask was simply missing.

**Comment by praduca** [comment]
I dont have access to the machine right now, but will check ASAP.

**Comment by praduca** [comment]
I will need to build xen myself to verify that? i'm really new to NixOS, and folowing the manual i couldn't find how to do that... Starting to dig the nixpkgs manual now...

**Comment by michalpalka** [comment]
This link might be helpful: http://anderspapitto.com/posts/2015-11-01-nixos-with-local-nixpkgs-checkout.html
Also the [nix manual section on `NIX_PATH`](http://nixos.org/nix/manual/#sec-common-env).

What you want to do is to get a repo with the right version of `nixpkgs`, and then run `nixos-rebuild -I nixpkgs=/path/to/your/nixpkgs boot`. Using the `-I` option is the same as overriding `NIX_PATH`.

**Comment by praduca** [comment]
Hey thanks, that's useful. The unstable channel will have this change or i need to merge myself the changes?

**Comment by praduca** [comment]
Yes, this code solve this issue. I'm marking this as closed.
