### ISSUE TITLE
fontconfig warning when starting konsole

### ISSUE THREAD

**Issue by butterflya** [NixOS/nixpkgs#24596]
```
$ konsole
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
```
`/etc/fonts/fonts.conf` contains a <blank> section which should be removed to resolve this. 
Version: 17.03

**Comment by vcunat** [comment]
Hmm, I think it's actually supposed to use `/etc/fonts/2.11/fonts.conf` which does not contain that section.  This error line actually doesn't happen for me on (older) 17.03.

**Comment by vcunat** [comment]
I verified some stuff even on the newest 17.03 and still no luck.  @butterflya: do you set some `FONTCONFIG_*` variables in the environment?

**Comment by butterflya** [comment]
No

```
env| grep FONTCONFIG
FONTCONFIG_FILE=/etc/fonts/fonts.conf
```

`nixos-version`:  `17.03.git.b152bbd (Gorilla)`

**Comment by vcunat** [comment]
Well, that's the variable causing it.  It forces fontconfig to use pre-2.11 config.

**Comment by vcunat** [comment]
I'm convinced `17.03` NixOS doesn't put this variable into your environment unless you force it somehow.

**Comment by butterflya** [comment]
@vcunat Agreed.
