### ISSUE TITLE
NixOS 17.03 is broken on ARM

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#24594]
## Issue description

As far as I can see, NixOS 17.03 seems to be broken on ARM architectures.

The first issue I ran into was this one: #24170 

After finding a workaround for the issue above, I ran into an issue described in the comments of this commit (specifically, the `shell-init: ...` errors): https://github.com/NixOS/nixpkgs/commit/8bfa9f528c88243578246798c7c2ddde045e0de0

The comments in the commit above seem to indicate that the following commits need to be backported to 17.03 in order to fix aarch64 builds:
* dff0ba38a243603534c99f2cf1af81c793cad98e
* 20d9edff1723363b0df1d7f44301cefffd8b3881

Also, I believe the bootstrap tools need to be updated for `armv7l` (and probably other armv* architectures?) and backported to 17.03, to fix the issue described above.

CC @dezgeg

**Comment by vcunat** [comment]
Another thing is that Hydra doesn't do anything with ARM on 17.03, so even huge (accidental) breakages might go unnoticed.

**Comment by globin** [comment]
Yes aarch64 will only be supported at the earliest with 17.09. but we already build for unstable, but it isn't stable enough to be supported properly in a release and you should go for unstable for ARM currently and not expect too much.

**Comment by vielmetti** [comment]
I'm bringing up NixOS on Packet's type 2A server right now, which is aarch64.

**Comment by dezgeg** [comment]
Fixed on master: 28f87e414186e2f16a094ac354dfe079965e8fe5 and applied to release-17.09: 1ff02f894779a6ada9e9ba9af82fc8d916adbc08, a98a83523a7ad123b03b054c4f8925842464f703, a7ebf59aa7e146791d4a40e5d5e55a721fc8130c.

**Comment by wizeman** [comment]
Seems to be working. Thanks @dezgeg!
