### ISSUE TITLE
haskellPackages.liquid missing dependencies

### ISSUE THREAD

**Issue by alibabzo** [NixOS/nixpkgs#24598]
## Issue description
When trying to install haskellPackages.liquid the build breaks with missing dependencies.

I think the package needs to be jailbroken, but my uninformed fiddling in `pkgs/development/haskell-modules/configuration-common.nix` didn't manage to get it working.

### Steps to reproduce
`nix-env -iA nixos.haskellPackages.liquid`

```
...
Configuring liquid-0.1.0.3...
Setup: Encountered missing dependencies:
QuickCheck >=2.8.2 && <2.9,
aeson >=0.11.2.1 && <0.12,
lens ==4.14.*
builder for ‘/nix/store/865i8mkmxck2sikar5vv9d5qxix4rpkz-liquid-0.1.0.3.drv’ failed with exit code 1
```

## Technical details

* System: `17.09pre104924.438ac662aa (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `"17.09pre104924.438ac662aa"`

**Comment by mmahut** [comment]
This has been marked as broken, if anyone is interested in maintaining this package, please open a pull request.
