### ISSUE TITLE
Update request: semgrep 1.27.0 → 1.34.0

### ISSUE THREAD

**Issue by skorpy2009** [NixOS/nixpkgs#245961]
- Package name:
- Latest released version: 1.34.0

- Current version on the unstable channel: 1.27.0
- Current version on the stable/release channel: 1.27.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@06kellyjac @ambroisie 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ambroisie** [comment]
Note: the update script isn't working on my system, I assume that's why @r-ryantm has not uploaded any updates.

**Comment by 06kellyjac** [comment]
Ill take a look tomorrow :)
