### ISSUE TITLE
Derivation inputs determined by another derivation? (metaprogramming question)

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#24590]
Question about Nix programming style which I _hope_ is on topic for this repo! (Or maybe I should have posted to `nixos/nix`?)

Is there a straightforward idiom for defining derivations whose inputs are calculated dynamically e.g. where one derivation determines the inputs to another?

For example suppose that I have this file at url `http://foo.com/foo.yaml`:

```
sources:
  - http://foo.com/a.tar.gz
  - http://foo.com/b.tar.gz
  - http://foo.com/c.tar.gz
```

and now I want to write a nix expression that first "manually" fetches `http://foo.com/foo.yaml` and then also "automatically" fetches each of the sources that are listed in that file?

The use case is processing log files with nix. The simple case is to process the log from one process (e.g. `a.tar.gz`). The hard case is making it possible to define a set of processes whose logs should be processed in combination (that's what `foo.yaml` is for.)

**Comment by abbradar** [comment]
There is a feature that does just that, named "import from derivation": you can do `import "${foo}/bar.nix"`.

**Comment by copumpkin** [comment]
Except `builtins.fetchurl` caches and is hard to force-expire the cache. See https://github.com/NixOS/nix/issues/1223

**Comment by lukego** [comment]
Thanks for the info guys. Let me just check if I understand correctly before closing this issue.

> There is a feature that does just that, named "import from derivation": you can do import "${foo}/bar.nix"

Neat. So in my example I could have a first derivation (`d1`) that downloads the `foo.yaml` file and transforms it into a nix expression listing some sources, then a second derivation (`d2`) that loads this from the output of the first?

```nix
let d1 = mkDerivation { src = fetchurl "http://foo.com/foo.yaml"; ... };
    d2 = mkDerivation { src = import "${d1}/inputs.nix"; ... }; in
```

and this would be perfectly valid nix code and nothing to be ashamed about? :-)

**Comment by abbradar** [comment]
@lukego We try to avoid it in nixpkgs because this makes determining and printing build plan impossible (Those will be built...., those will be fetched....), but that's completely okay in general!

**Comment by lukego** [comment]
Thank you for the very helpful explanations!
