### ISSUE TITLE
nginx: add ModSecurity Nginx Connector

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#24599]
Is it possible to add a module ModSecurity Nginx Connector? - https://github.com/SpiderLabs/ModSecurity-nginx
Thanks.

**Comment by Izorkin** [comment]
I assembled the module in this way:
I have added a line to nixpkgs/pkgs/top-level/all-packages.nix

`libmodsecurity = callPackage ../tools/security/libmodsecurity { };`

nixpkgs/pkgs/tools/security/libmodsecurity/default.nix
```
{ stdenv, lib, fetchFromGitHub, pkgconfig
, curl,  pcre, apr, aprutil, libxml2, geoip, lmdb, yajl, autoreconfHook, git }:

stdenv.mkDerivation rec {
  name = "libmodsecurity-${version}";
  version = "3.0.0";

  src = fetchFromGitHub {
    owner = "SpiderLabs";
    repo = "ModSecurity";
    fetchSubmodules = true;
    rev = "ba070c9eaa79659ac1592d7967a274f086a8fb3f";
  };

  nativeBuildInputs = [ autoreconfHook pkgconfig ];
  buildInputs = [ curl pcre apr aprutil libxml2 lmdb geoip yajl git];
  configureFlags = [
    "--enable-static"
    "--with-curl=${curl.dev}"
    "--with-pcre=${pcre.dev}"
    "--with-libxml=${libxml2.dev}"
#    "--with-lmdb=${lmdb.dev}"
    "--with-yajl=${yajl}"
    "--with-geoip=${geoip}"
  ];

  meta = {
    description = "libModSecurity";
    homepage = https://modsecurity.org/;
    platforms = stdenv.lib.platforms.all;
  };
}
```
nixpkgs/pkgs/servers/http/nginx/modules.nix

```
  modsecurity-nginx = {
    src = fetchFromGitHub {
      owner = "SpiderLabs";
      repo = "ModSecurity-nginx";
      fetchSubmodules = false;
      rev = "3de175bdcbfa704a308d0e26fa8e34c0bb6b21ac";
      sha256 = "0s8fbmy2fdzsbybzishbk7vwbd1dqzpfsri1gym5bzn6j7xgpbkz";
    };
    inputs = [ pkgs.libmodsecurity pkgs.curl pkgs.libxml2 pkgs.yajl pkgs.geoip pkgs.lmdb ];
  };
```
I installed nginx mod-security 3.0.0 through such a configuration file
{ callPackage, nginxModules }:
callPackage <nixpkgs/pkgs/servers/http/nginx/mainline.nix> {
  modules = [
    nginxModules.dav
    nginxModules.moreheaders
    nginxModules.modsecurity-nginx
  ];
}
Is it possible to add changes to the repository? Probably it will be needed to correct the configuration files.

**Comment by bachp** [comment]
@Izorkin Could you provide a PR that puts your changes into nixpkgs?

**Comment by Izorkin** [comment]
https://github.com/NixOS/nixpkgs/pull/32075
