### ISSUE TITLE
Package request: GoatCounter

### ISSUE THREAD

**Issue by rotten777** [NixOS/nixpkgs#245902]
**Project description**

GoatCounter is an open source web analytics platform available as a (free) hosted service or self-hosted app. It aims to offer easy to use and meaningful privacy-friendly web analytics as an alternative to Google Analytics or Matomo.

There are two ways to run this: as hosted service on [goatcounter.com](https://www.goatcounter.com/), or run it on your own server. The source code is completely Open Source/Free Software, and it can be self-hosted without restrictions.

go, golang, analytics

* homepage URL: https://www.goatcounter.com/
* source URL: https://github.com/arp242/goatcounter
* license: a slightly modified version of European Union
Public License (EUPL) 1.2; the only difference is that the “Compatible Licenses”
Appendix removes some licenses, but is otherwise identical.

* platforms: any platform supported by Go

**Comment by jzbor** [comment]
Hi, I have tried to create an overlay for it using `buildGoModule`:
```Nix
self: super:

{
  goatcounter = super.callPackage (
    { pkgs, lib, buildGoModule, fetchFromGitHub }:

    buildGoModule rec {
      pname = "goatcounter";
      version = "2.4.1";

      src = fetchFromGitHub {
        owner = "arp242";
        repo = pname;
        rev = "v${version}";
        sha256 = "sha256-L4310L+L2Qn8NkRMqze7KNwZ18LXz8PAoXCCpYa5J4I=";
      };

      vendorSha256 = "sha256-nKfqZ5hGGVLBY/hnJJPCrS/9MlGoR2MWFUWDnpwWgyM=";
    }
  ) {};
}
```

Unfortunately the build fails with the following log:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/g4yx979f6wqnnnyx7k0qm329m6lq9am8-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building subPackage .
Building subPackage ./acme
Building subPackage ./bgrun
main module (zgo.at/goatcounter/v2) does not contain package zgo.at/goatcounter/v2/bgrun
```

I do not have a lot of insights into `buildGoModule` or go builds in general, but I'd guess it has something to do with [these lines](https://github.com/arp242/goatcounter/blob/b4126b7165aa65a17353e06ef0b7bf7127d76004/go.mod#L49). Maybe someone with more experience around go packaging can help?

**Comment by jzbor** [comment]
Nevermind, I found [this flake](https://github.com/connorfeeley/goatcounter-flake) with working `buildGoModule` code.
