### ISSUE TITLE
Update request: armcord 3.2.0 → 3.2.1

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#246059]
- Package name: armcord
- Latest released version: 3.2.1

- Current version on the unstable channel: 3.2.0
- Current version on the stable/release channel: 3.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wrmilling 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by wrmilling** [comment]
Looks like @antonmosich is working on it, will review the PR when they have it submitted.
