### ISSUE TITLE
Package request: SQLite Studio

### ISSUE THREAD

**Issue by arcbra** [NixOS/nixpkgs#246083]
**Project description**

A free, open source, multi-platform SQLite database manager written in C++, with use of Qt framework.

**Metadata**

* homepage URL: https://sqlitestudio.pl/
* source URL: https://github.com/pawelsalawa/sqlitestudio/tree/master
* license: SQLiteStudio is licensed under the GNU General Public License version 3 with the addition of the a special exception
* platforms: Linux

**Comment by felipelalli** [comment]
Duplicated with #126536 - please close it.

**Comment by winterqt** [comment]
Duplicate of #126536. Please be more careful when opening issues in the future, a simple search would have avoided this.
