### ISSUE TITLE
Steam fails to start via `steam.desktop` when `PrefersNonDefaultGPU=true` is present

### ISSUE THREAD

**Issue by CobaltCause** [NixOS/nixpkgs#246007]
### Describe the bug
Title. Removing the line in `steam.desktop` that contains `PrefersNonDefaultGPU=true` makes it work, and running `steam` from `$PATH` also works since that doesn't involve `steam.desktop` at all.

### Steps To Reproduce
1. Try to start steam via its desktop entry (e.g. via `wofi --show drun`)
2. The main window never opens
3. If you check `journalctl --user -f` you'll see segfaults from `steamwebhelper`

### Expected behavior
Steam should start via `steam.desktop`.

### Additional context

My NixOS configuration at the time of opening this issue is [here](https://or.computer.surgery/charles/dotfiles/-/tree/14c6621a616112cd770b40b20ccc15ee2bb6be5c/nixos).

#### Affected system (`compy`)

* Hyprland (wayland)
* System type: desktop
* CPU: 7950X
* GPU: 7900 XTX (amdgpu + mesa)

I'm guessing it fails on this system because it's trying to run on the iGPU since the dGPU is probably the default as far as `steam.desktop` is concerned, and this system isn't running KDE so it doesn't understand `X-KDE-RunOnDiscreteGpu=true`.

#### Unaffected system (`worky`)

* Hyprland (Wayland)
* System type: laptop
* CPU: i7-1185G7
* GPU: iGPU of aforementioned CPU (i915 + mesa)

I'm guessing it works on this system because there is only one GPU.

#### Unaffected system (not mine)

* KDE (Wayland and X11)
* System type: desktop
* CPU: i7-6700K
* GPU: GTX 1080 (proprietary drivers)

I'm guessing it works on this system because `X-KDE-RunOnDiscreteGpu=true` is also in `steam.desktop` and this system is running KDE.

### Notify maintainers

@jagajaga, @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.6, NixOS, 23.11 (Tapir), 23.11.20230726.c9cf070`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/9kf2q1cd2nqy7azvgvv3bvm3n4mrvmrb-source`
```

**Comment by fin444** [comment]
I have an Optimus laptop, can confirm. When I have NVIDIA drivers disabled (I use two boot profiles), Steam's GUI crashes on start like described, but works perfectly fine from CLI. When drivers are enabled, Steam works from the desktop file.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.6, NixOS, 23.05 (Stoat), 23.05.2385.48e82fe1b1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fin444** [comment]
What makes this issue completed?

**Comment by SuperSandro2000** [comment]
I closed a bunch of none actionable steam issues in the last half an hour. This is likely an upstream bug or yet another PRIME issue of which there are many.
