### ISSUE TITLE
Salah

### ISSUE THREAD

**Issue by Salaheldean** [NixOS/nixpkgs#246054]
### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Salaheldean** [comment]
هل يمكن ان نصنع مستقبل ع اتم استعداد للنظام بيئي نظيف ومحترم ونزرع فيه العادات والتقاليد الأصيله اللي بجد

**Comment by hervyqa** [comment]
@Salaheldean what dou you mean? english please.
