### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#24600]
There's a lot of talk on [Mastodon](https://github.com/tootsuite/mastodon) about wanting more people to run servers. The current recommended deploy environment is Docker. It'd be nice if we could provide NixOS support. I've already seen several of y'all on Mastodon, so we ought to be able to get this done :smiley:  I may work on this myself if I find time.

**Comment by Profpatsch** [comment]
Any update?

**Comment by chris-martin** [comment]
Not from me, I've been spending all my time shooting the shit on Mastodon.

**Comment by fpletz** [comment]
It's on my immediate todo-list. Probably this weekend.

As it's a rails app and I've already done lots of rails nixos modules, it should be easy. If anyone wants to beat me, just look at the gitlab or frab module.

**Comment by ashyon** [comment]
This would be really neat! How's it coming along?

**Comment by fpletz** [comment]
Unfortunately it's little bit more complicated because it needs lots of NodeJS dependencies for the frontend stuff and node2nix fails to produce working nix expressions. Also, some gems need overrides because they won't build either.

**Comment by ashyon** [comment]
Ah that sucks. Let me know if there's anything I can do to help, but i'm just a newbie to NixOS really.

**Comment by chris-martin** [comment]
Is it feasible to half-ass the JS/Ruby dependencies by just pulling them at runtime when the server starts?

**Comment by chris-martin** [comment]
Just tried running `node2nix` 1.2.0 on Mastodon.

> error: ‘buildNodePackage’ at /home/chris/code/mastodon/node-env.nix:198:22 called without required argument ‘version’, at /home/chris/code/mastodon/node-packages.nix:16677:13

... wow that's a lot of output.

**Comment by taohansen** [comment]
Where are we on this? Can I help?

**Comment by paperdigits** [comment]
Is there an update to this? I'd be awesome to deploy mastodon on Nix!

**Comment by erictapen** [comment]
I think I'm doing some progress on this. I can't reproduce the failing `node2nix` anymore and I managed to build the ruby environment (took some overrides as @fpletz suggested).

My progress is currently [here](https://github.com/erictapen/nixpkgs/tree/mastodon).

I never really tested running the server yet, as there is quite a lot to do before that works. But I think, that the dependencies are almost in place.

Biggest pain point atm is the Node environment. I basically copied the approach from [`base-16-builder`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/base16-builder/default.nix). That builds, but what bothers me is 

* that it [uses `pkgs`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/base16-builder/default.nix#L1)
* I had to [patch a file generated by `node2nix`](https://github.com/erictapen/nixpkgs/commit/91545bebe27ea7f0cf225fbf2fc398020979e604).
* and that it seems to be impure. I already experienced a rebuild after two subsequent runs of `nix-build -A pkgs.mastodon`.

Would be nice if someone with more NodeJS domain knowledge would look onto that.

**Comment by andir** [comment]
Do you know what would be required to test that using VM tests?

I was thinking of having 2 mastodon instances and maybe using API-clients to post and fetch messages?

**Comment by erictapen** [comment]
I never looked into NixOS VM tests, but iirc Mastodon would be well suited for that. One could test federation and client-server-communication as you described.

This would definitely depend on a working service expression. Additionally there needs to be a way to create users from the command line (I'm sure there is) and a Mastodon CLI client ([there are some](https://github.com/ihabunek/toot)).

**Comment by erictapen** [comment]
I made the mistake to take a break in the development. In that time, Nixpkgs moved considerably as well as Mastodon. The package doesn't even build anymore.

This might be too complex for my current state of knowledge of Ruby and Node. I give up.

I rebased my progress ontop of `nixos-unstable` and added a minor fix. Maybe someone else has luck with it:

https://github.com/erictapen/nixpkgs/tree/mastodon

If I ever try to package a Fediverse app again, I may try [Pleroma](https://git.pleroma.social/pleroma/pleroma), which seems to be more leightweight.

**Comment by brainrape** [comment]
Can we close this until someone opens a PR? Seems to have lost momentum.

**Comment by erictapen** [comment]
I'd think it would make sense to close it. Haven't heard of any progress in a while.

**Comment by brainrape** [comment]
@chris-martin Can we close this until someone opens a PR?

**Comment by chris-martin** [comment]
Sounds reasonable to me.

**Comment by petabyteboy** [comment]
I have an instance runnng on https://social.pbb.lc
The module I wrote is available at https://git.pbb.lc/petabyteboy/nixfiles/src/branch/master/pkgs/mastodon/default.nix
https://git.pbb.lc/petabyteboy/nixfiles/src/branch/master/modules/mastodon.nix
It will need a few changes for nixpkgs, I will open a PR soon.

**Comment by costrouc** [comment]
@petabyteboy any plans to open a PR. I have plans to deploy a mastadon server via nix. I could help get this started of you would like

**Comment by matthiasbeyer** [comment]
Yeah please do this!

**Comment by petabyteboy** [comment]
there is a PR at #60788
