### ISSUE TITLE
How do u use or install this default.nix from pkgs

### ISSUE THREAD

**Issue by lsrhazaki** [NixOS/nixpkgs#246141]
## Issue description
And by watching from yt im on home-manager which i use 
How do i configure that default.nix for app to work

**Comment by R-VdP** [comment]
Sorry, but what is your question exactly? You'll need to provide a bit more context here.

Also, home-manager is a separate project: https://github.com/nix-community/home-manager

**Comment by Artturin** [comment]
`(pkgs.callPackage ./something/default.nix)`
