### ISSUE TITLE
Enable gpg-agent replacement for ssh-agent

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#24613]
So one can use GPG keys, etc, for SSH auth. It's done with `gpg-agent --daemon --enable-ssh-support`.

**Comment by Zimmi48** [comment]
Looks fixed: cf. `nixos-option programs.gnupg.agent.enableSSHSupport` in NixOS 17.10.

**Comment by puffnfresh** [comment]
It doesn't add the exact flag from the issue description, but I'm pretty sure it achieves the same thing. Vote to close!
