### ISSUE TITLE
Allow unlocking of keyring from greetd

### ISSUE THREAD

**Issue by b-m-f** [NixOS/nixpkgs#246197]
Both [LightDM](https://github.com/NixOS/nixpkgs/blob/51ba3f1ac9b5225112ceadf3473af0a2ba63ffea/nixos/modules/services/x11/display-managers/lightdm.nix#L275) and [GDM](https://github.com/NixOS/nixpkgs/blob/51ba3f1ac9b5225112ceadf3473af0a2ba63ffea/nixos/modules/services/x11/display-managers/gdm.nix#L314) include the login module where a keyring can be unlocked, for example by setting `
 security.pam.services.login.enableGnomeKeyring = true; `.

I suggest adding the following:
```

text = ''
auth      substack      login
account   include       login
password  substack      login
session   include       login
'';
```
to 
https://github.com/NixOS/nixpkgs/blob/d3a6adc9b6f11e260da168714ad8dcc938621610/nixos/modules/services/display-managers/greetd.nix#L59

and maybe hide them behind a boolean?

Maybe someone with more knowledge of the PAM system could give some feedback on this, as I am not sure if there could be negative or unforeseen consequences lurking.

**Comment by b-m-f** [comment]
@luc65r, you are mentioned as the maintainer so I tought I ping you on this :)

**Comment by Aleksanaa** [comment]
You can use `security.pam.services.greetd.enableGnomeKeyring = true`. But yeah a template for all those login managers makes sense.

**Comment by fazo96** [comment]
I have had success with `security.pam.services.greetd.enableGnomeKeyring = true`

**Comment by pluiedev** [comment]
`security.pam.services.greetd.enableGnomeKeyring = true` works just fine for me, although IMO forcing people to do this manually is quite dumb — I would propose to enable this if `services.gnome.gnome-keyring.enable` is set to true.

**Comment by martijnboers** [comment]
Still cannot get this to work for the live of me. I'm using Hyprland with greetd but my default keyring remains locked on boot. My config [hyprland.nix](https://github.com/martijnboers/nixos/blob/e3f4cc0815e809bdfd7efc424c9fc0abb06d598d/nixos/modules/hyprland.nix#L37-L53)

**Comment by guttermonk** [comment]
I'm having issues with this as well. Can someone that reported this as fixed please share their config?

Here’s the error message I’m getting at login:
`
“The application ‘Brave’ has requested to open the wallet ‘Default keyring’. Please enter the password for this wallet below.”
`

My config looks similar to @martijnboers config above.

**Comment by martijnboers** [comment]
> I'm having issues with this as well. Can someone that reported this as fixed please share their config?
> 
> Here’s the error message I’m getting at login:
> `
> “The application ‘Brave’ has requested to open the wallet ‘Default keyring’. Please enter the password for this wallet below.”
> `
> 
> My config looks similar to @martijnboers config above.

I run auto start programs that will request to unlock the keyring. Didn't get it to work

**Comment by guttermonk** [comment]
This may be a related open bug: https://github.com/NixOS/nixpkgs/issues/86884

Also I've been trying to get the second solution from [this stack](https://unix.stackexchange.com/questions/344402/how-to-unlock-gnome-keyring-automatically-in-nixos) to work, as I've seen a [similar solution for Arch users on reddit](https://www.reddit.com/r/swaywm/comments/13idzjz/greetd_gnome_keyring/?rdt=41014).

**Comment by guttermonk** [comment]
Adding this line `security.pam.services.login.enableGnomeKeyring = true;` seems to have fixed it for me (credit to [worldofpeace](https://discourse.nixos.org/t/unlocking-gnome-keyring-automatically-upon-login-with-kde-sddm/6966/3)). 

Also, starting the browser with `brave --password-store=gnome-libsecret` helps, which should work with any chromium based browser.

**Comment by noisesfromspace** [comment]
@guttermonk looks like those lines are already present in my `/etc/pam.d/greetd` config file. Do you have any updates on this?

**Comment by guttermonk** [comment]
There's [a thread](https://discourse.nixos.org/t/login-keyring-did-not-get-unlocked-hyprland/40869/25) going where a user reported that it was working using the config I posted, but it's still only working intermittently for me.

I'm currently having to type my password in 2-3 times from boot. Ideally, I would just type it in once for LUKS but it [looks like](https://discourse.nixos.org/t/automatically-unlocking-the-gnome-keyring-using-luks-key-with-greetd-and-hyprland/54260/5) that dream is a ways off for Hyprland/greetd.

**Comment by guttermonk** [comment]
Does anyone know if the continued issues here are related to a specific front-end for greetd, like tuigreet, or if this is a tuigreet issue? Wondering if it would be worth reopening this issue or if a new issue should be made for tuigreet.
