### ISSUE TITLE
ngrok is out-of-date

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#24612]
`ngrok` is now at major version 2 but we still have `1.7`. I don't know how to update go packages or I would do it myself.

**Comment by matthiasbeyer** [comment]
Do you mean https://github.com/inconshreveable/ngrok ? There is no version 2 tag in the repository!

From the repository:

> ngrok 2.x is the successor to 1.x and the focus of all current development effort. Its source code is not available.

I am not sure how we should update, then...

**Comment by 3noch** [comment]
I just realized the same thing. It looks like the latest ngrok is no longer OSS. We may want to deprecate this package.

**Comment by matthiasbeyer** [comment]
:+1: for renaming it to `ngrok-1` and throwing a warning on `ngrok`. Feel free to submit a PR for this!
