### ISSUE TITLE
Package request: Preload

### ISSUE THREAD

**Issue by bbfc5** [NixOS/nixpkgs#246106]
**Project description**

Runs as a daemon and records statistics about usage of programs using Markov chains; files of more frequently-used programs are, during a computer's spare time, loaded into memory.

**Metadata**

* homepage URL: https://sourceforge.net/projects/preload/
* source URL: https://sourceforge.net/projects/preload/
* license: gpl2
* platforms: linux

**Comment by LDprg** [comment]
Same here! Preload can really help out when using Linux on older hardware or when using programs that generally take long to start.
