### ISSUE TITLE
Package request: hwatch for platforms.darwin / platforms.all

### ISSUE THREAD

**Issue by yoav-lavi** [NixOS/nixpkgs#246199]
**Project description**

hwatch - A modern alternative to the `watch` command, records the differences in execution results

(Rust, currently distributed via `brew` [Homebrew], `port` [MacPorts], `paru` [Arch Linux AUR], and `cargo` [Rust])

At the moment hwatch is only available for `platforms.linux` on nixpkgs

**Metadata**

* source URL: https://github.com/blacknon/hwatch
* license: MIT
* platforms: All

**Comment by figsoda** [comment]
It has been available since 22.11: https://github.com/NixOS/nixpkgs/pull/177188

**Comment by yoav-lavi** [comment]
@figsoda That's weird, it didn't work for me when I tried it last time so I switched it to homebrew via nix-darwin. Let me retry

**Comment by yoav-lavi** [comment]
@figsoda I see the issue, it's Linux only

**Comment by yoav-lavi** [comment]
@figsoda updated, thank you!

**Comment by figsoda** [comment]
could you take a look at #246204?

**Comment by yoav-lavi** [comment]
Approved, thank you for being awesome @figsoda!
