### ISSUE TITLE
Update Documentation: "~/.config/nixpkgs/config.nix" doesn't work

### ISSUE THREAD

**Issue by dfordivam** [NixOS/nixpkgs#24611]
The documentation need to be updated (especially https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure)

At least on my nixos the "~/.config/nixpkgs/config.nix" doesn't work, "~/.nixpkgs/config.nix" works.

**Comment by lheckemann** [comment]
It [should work](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/impure.nix#L30)...

**Comment by dfordivam** [comment]
I see this is a recent change... I have nixos with 1609 and in that this path doesn't work.
commit 9d6a55aefd771f047d2aa3085c9a3f8a2f452333 

Closing this issue as the documentation is up to date...

**Comment by vcunat** [comment]
Even the change is documented in [17.03 release notes](https://nixos.org/nixos/manual/release-notes.html#sec-release-17.03-notable-changes).  (We only have notes for nixos, not separate for nixpkgs.)

**Comment by neocris** [comment]
i'm using nixos 17.09 virtualbox appliance on win10 and have no nixpkgs folder on ~/.config. where can i edit config.nix then?

**Comment by vcunat** [comment]
@neocris: you simply create the necessary directories and file ;-)

**Comment by neocris** [comment]
oh, i thought it was supposed to be some setup already included in the distribution, but i realize instead it is a sort of userspace custom config. thx a lot for the enlightenment @vcunat
