### ISSUE TITLE
Update request: gnubg 1.06.002 → 1.07.001

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#246168]
- Package name: gnubg
- Latest released version: 1.07.001

- Current version on the unstable channel: 1.06.002
- Current version on the stable/release channel: 1.06.002

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ehmry 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ehmry** [comment]
I packaged this in 2015 and I have no idea why.
