### ISSUE TITLE
Package request: LIKWID

### ISSUE THREAD

**Issue by jariji** [NixOS/nixpkgs#246110]
**Project description**

> This is an effort to develop easy to use but yet powerful performance tools and library for the GNU Linux operating system.

> A tool to measure hardware performance counters on recent Intel and AMD processors. It can be used as wrapper application without modifying the profiled code or with a marker API to measure only parts of the code.

**Metadata**

* homepage URL: https://github.com/RRZE-HPC/likwid/wiki
* source URL: https://github.com/RRZE-HPC/likwid 
* license: GPL-3.0
* platforms: Linux

**Comment by MordragT** [comment]
I did package likwid some time ago, but I believe my cpu did not support the necessary things why I then switched to a university VM. So i am not quite sure if everything works, but maybe this is a starting point: https://github.com/MordragT/nixos/blob/master/pkgs/likwid.nix
