### ISSUE TITLE
Package request: immer, lager and zug

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#246247]
**Project description**

* [arximboldi/immer: Postmodern immutable and persistent data structures for C++ — value semantics at scale](https://github.com/arximboldi/immer)
* [arximboldi/lager: C++ library for value-oriented design using the unidirectional data-flow architecture — Redux for C++](https://github.com/arximboldi/lager)
* [arximboldi/zug: Transducers for C++ — Clojure style higher order push/pull sequence transformations](https://github.com/arximboldi/zug)

Next krita version (5.2.0) will depend on these 3 libraries

@arximboldi I wonder if you would like to maintain these 3 packages in nixpkgs? I can open PRs and be maintainer if you are not interested. Thanks for creating the libraries!

**Metadata**

* homepage URL:
* source URL:
* license: boost, mit, boost
* platforms: all

**Comment by arximboldi** [comment]
Thanks a lot @sifmelcara for this. I would be very happy for you to maintain this, as I do not have a lot of time nor experience maintaining packages in `nixpkgs`, but feel free to add me as co-maintainer so I can chim in when you're not available or help with stuff when I can.

**Comment by sifmelcara** [comment]
Done in #261138
