### ISSUE TITLE
pythonPackages.basemap: Python interpreter cannot import basemap

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#24621]
## Issue description
I'm trying to run a nix-shell with several python packages. One of them is basemap.
I cannot successfully import basemap however.
Oddly enough it works when using `ipython` as REPL.

### Steps to reproduce

```
nix-shell -p pythonPackages.basemap  --pure --run "python -c 'import mpl_toolkits.basemap'"
```
outputs: `ImportError: No module named basemap`

However if we use `ipython` it works:

```
nix-shell -p pythonPackages.basemap pythonPackages.ipython --pure --run "ipython -c 'import mpl_toolkits.basemap'"
```

## Technical details

* System: openSUSE13
* Nix version: 1.11.6
* Nixpkgs version: "17.09pre104446.09c91f5"

**Comment by FRidh** [comment]
That's a funny one. The following does function:
```
nix-shell -p 'python.withPackages(ps: with ps; [basemap])'  --pure --run "python -c 'import mpl_toolkits.basemap'"
```

Also, when I fix the expression to build a wheel like we normally do I can import it as well. Seems like that's the proper fix :)
