### ISSUE TITLE
Should buildFHSUserEnv set ACLOCAL_PATH?

### ISSUE THREAD

**Issue by demin-dmitriy** [NixOS/nixpkgs#24620]
## Issue description

When using autotools with `buildFHSUserEnv`, aclocal won't look into directory /usr/share/aclocal.
`aclocal --print-ac-dir` prints `/nix/store/...-automake-1.15/share/aclocal`.

Currently you have to set ACLOCAL_PATH manually to make it find those files.

## Technical details

* System: 17.09.git.08c87ee (Hummingbird)
* Nix version: 1.12pre4997_1351b0d
* Nixpkgs version: 17.09.git.08c87eed00

**Comment by abbradar** [comment]
Thanks for reporting!
