### ISSUE TITLE
Lack of option to customize configration for avahi-daemon service

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#24622]
## Issue description

Currently, config file for avahi-daemon is generate by limited options, there's no way to do extra customization, for example, enable reflector.

## Technical details

* System:  16.09.1024.c859ea0 (Flounder)
* Nix version:  nix-env (Nix) 1.11.4
* Nixpkgs version:  16.09.1024.c859ea0

**Comment by Profpatsch** [comment]
What functionality do you need?
We are a lazy operation, packaging mostly happens as needed. :P

**Comment by yuchangyuan** [comment]
I need to enable reflector for avahi daemon, so I need to put below content in to `avahi-daemon.conf` which used by avahi-daemon.
<pre>
[REFLECTOR]
enable-reflector=yes
</pre>

**Comment by Profpatsch** [comment]
There has been a `services.avahi.reflector` boolean option since 2017-04-24.

**Comment by yuchangyuan** [comment]
Thank you for your reminding.
