### ISSUE TITLE
Package request: Coolero

### ISSUE THREAD

**Issue by CipherJay** [NixOS/nixpkgs#246308]
Coolero is a program to monitor and control your cooling devices.
It offers an easy-to-use user interface with various control features and also provides live thermal performance details.

It is a frontend and enhancement of [liquidctl](https://github.com/liquidctl/liquidctl) and [hwmon](https://hwmon.wiki.kernel.org/) with a focus on cooling device control under Linux.
Written in [Python](https://www.python.org/) it uses [PySide](https://wiki.qt.io/Qt_for_Python) for the UI and [Poetry](https://python-poetry.org/) for dependency management.

This project is currently in active development and slowly working it's way towards it's first major release.

source URL: https://github.com/codifryed/coolero
license: GPL v3
platforms: unix, linux

**Comment by gp2112** [comment]
The original project - CoolerControl - is in gitlab. Coolero is not receiving updates anymore.

> The Project has undergone a name and implementation change. Please check out CoolerControl for new developments. 

And we already have an open issue requesting CoolerControl package in #245746

**Comment by gp2112** [comment]
@CipherJay you're welcome! Please, feel free to contribute any time :)
