### ISSUE TITLE
Package request: miniupnpd-nftables

### ISSUE THREAD

**Issue by alanpearce** [NixOS/nixpkgs#246345]
We already have [miniupnpd](https://github.com/miniupnp/miniupnp) in [nixpkgs](https://github.com/NixOS/nixpkgs/tree/0d117d7ad5d590991d23ccc7bd88c4e627cccf17/pkgs/tools/networking/miniupnpd), but only with iptables support. It would be nice to have the nftables version available as well.

**Comment by arsfeld** [comment]
Being worked on in #239028, I'm trying to test myself but couldn't make it to work yet.

**Comment by chayleaf** [comment]
I think it's ready now, testing welcome!

**Comment by jerrita** [comment]
Maybe add an option for `upnp_table_name` will be better?
