### ISSUE TITLE
Nvidia Drivers 530.41.03 Legacy Support

### ISSUE THREAD

**Issue by PoisonPhang** [NixOS/nixpkgs#246396]
After recent changes to `NixOS/nixpkgs/release-23.05/pkgs/os-specific/linux/nvidia-x11/default.nix`, it's impossible to intentionally select Nvidia drivers for version 530.41.03. 

All newer versions of the Nvidia (what's available in beta/latest/production) drivers currently result in screen flickering on my secondary display.

I believe this is caused by having two G-Sync enabled monitors, but that's a problem for Nvidia to fix. In the meantime, I would appreciate having 530.41.03 available via legacy driver selection.

**Comment by PoisonPhang** [comment]
I've opened a discussion on the Nvidia forums in hopes of having this addressed:
[Screen Flickering on 535.86.05 x86_64-linux](https://forums.developer.nvidia.com/t/screen-flickering-on-535-86-05-x86-64-linux/261609)

**Comment by blablablerg** [comment]
see this thread, last couple of comments.  https://github.com/NixOS/nixpkgs/pull/245653

**Comment by PoisonPhang** [comment]
Marking this as resolved as the function defined in NixOS/nixpkgs#240075 allows for driver downgrading. The actual fix for newer drivers is up to Nvidia.
