### ISSUE TITLE
[nix Mac OS X Sierra 10.12.4] mu-0.9.18 cannot install due to pmccabe-2.6 error 

### ISSUE THREAD

**Issue by ag91** [NixOS/nixpkgs#24636]
## Issue description

Hello,

Huge thanks for contributing to nix! I am trying to use this great package manager with a Mac, and I am having some issues trying to install my favourite email client. 

### Steps to reproduce

When I try to install mu with nix-env -I mu, I get the following error:
```
installing ‘mu-0.9.18’
error: Package ‘pmccabe-2.6’ in ‘/nix/store/p95wisxzddaqm41921jg1x9imwfai5jv-nixpkgs-17.09pre104948.c34db6e419/nixpkgs/pkgs/development/tools/misc/pmccabe/default.nix:25’ is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

## Technical details

I checked the pmccabe derivation, and it has indeed a constraint on the platform: platforms = platforms.linux;.
Any way this derivation can work on Mac OS X x64?
Thanks,

Andrea

* System: Mac OS X Sierra 10.12.4
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre104948.c34db6e419

**Comment by LnL7** [comment]
It seems the `pmccabe` dependency is not used or at least optional, this builds fine without it. 
```nix
mu.override { pmccabe = null; }
```

**Comment by joachifm** [comment]
cc @peterhoeg added it, I think. iirc, that dep is for the test suite.

**Comment by peterhoeg** [comment]
This isn't the first time I'm breaking the build on Darwin. How do other people test properly without access to a mac?

**Comment by ag91** [comment]
Thanks, this works!

**Comment by LnL7** [comment]
@peterhoeg You can use `nix-instantiate --argstr system x86_64-darwin` to check evaluation for darwin or other platforms. That should catch simple cases like this if you don't have `allowBroken` enabled in your config.

**Comment by peterhoeg** [comment]
Thanks for the pointer @LnL7. I think the trick is to get darwin running in a VM instead...
