### ISSUE TITLE
Colima packaged in 23.05 has a bug that prevents colima from starting

### ISSUE THREAD

**Issue by erikkrieg** [NixOS/nixpkgs#246380]
### Describe the bug
I wanted to point out for anyone else trying to use colima on the stable channel (v23.05 at time of writing), that the version of `colima` has a bug that causes `colima start` to hang. The version of colima on stable is 0.5.4 and the fix for this issue is available on 0.5.5, which is currently available on the unstable channel.

Here are verbose logs from trying to start colima (v0.5.4):
```
❯ colima start --very-verbose
TRAC[0000] cmd ["limactl" "info"]
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]
TRAC[0000] error retrieving running instance: instance 'colima' does not exist
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
TRAC[0000] cmd ["/nix/store/4c7rffhcila3r78kb5rvpfq5qfr2ksg6-colima-0.5.4/bin/colima" "daemon" "status" "default"]
TRAC[0000] cmd ["/nix/store/4c7rffhcila3r78kb5rvpfq5qfr2ksg6-colima-0.5.4/bin/colima" "daemon" "start" "default" "--gvproxy" "--verbose"]
INFO[0000] creating and starting ...                     context=vm
TRAC[0000] cmd ["limactl" "start" "--tty=false" "/tmp/colima.yaml"]
> Terminal is not available, proceeding without opening an editor
> "Attempting to download the image from \"https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.0-2/alpine-lima-clm-3.16.2-x86_64.iso\"" digest="sha512:e9e118498f3a0745574ffc3686105d2c9777f7142164fe50ee47909dabd504c80ac29aeb76f9582706173310d1488d3b6f0ee9018e2a6aadc28eefb7767b63ec"
> Using cache "/Users/erik.krieg/Library/Caches/lima/download/by-url-sha256/e1cbaef56fc8e75af106d934389a17618643fcecfa066302d45ffb0390709851/data"
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/erik.krieg/.lima/colima/serial.log")
> SSH Local Port: 63289
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Driver stopped due to error: "exit status 255"
> [hostagent] Shutting down the host agent
> [hostagent] failed to exit SSH master
> [hostagent] Shutting down QEMU with ACPI
> [hostagent] failed to open the QMP socket "/Users/erik.krieg/.lima/colima/qmp.sock", forcibly killing QEMU
> [hostagent] failed to kill QEMU
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
```

### Steps To Reproduce
1. Use stable channel (v23.05)
2. `nix-shell -p colima docker`
3. `colima start`

### Expected behavior
I'd expect the version of colima on the stable channel to be a viable version of the package.

### Additional context
I am on MacOS (intel). I haven't tested on Linux. I'm not entirely sure the nature of this bug other than it seems to involve SSH (into the vm?)

Once I realized that this was fixed by using version 0.5.5, I updated my configurations to use unstable channel for this package, which worked. I'm not sure what the process for apply fixes to stable looks like, I'd get it if patching the version of colima in stable is considered too risky. At the very least hoping that having this issue opened might save someone some time.

### Notify maintainers

@aaschmid @zowoq @r-ryantm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(erik.krieg): `"unstable"`
 - channels(root): `"nixpkgs, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by gp2112** [comment]
I've just made a backport PR on #246384

**Comment by erikkrieg** [comment]
Thanks for the super quick response!
