### ISSUE TITLE
Update request: threema-desktop 1.2.27→ 1.2.31

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#246431]
- Package name: threema-desktop
- Latest released version: 1.2.31

- Current version on the unstable channel: 1.2.27
- Current version on the stable/release channel: 1.2.27

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@WolfangAukang  @saltrocks You commented [here](https://github.com/NixOS/nixpkgs/blob/391e8db1f06c3f74c2d313a73135515023af3993/pkgs/applications/networking/instant-messengers/threema-desktop/default.nix#L9C1-L10) that you are waiting for threema to populate their releases on GitHub with the current workaround being to upload the binaries to web.archive.org. 

Their releases seem to be there now, at least here are all the versions listed under `tags`: https://github.com/threema-ch/threema-web-electron/tags

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by CutestNekoAqua** [comment]
tags is not what was meant in the code comment, but .deb releases etc for the app
