### ISSUE TITLE
Automate updating JetBrains products

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#24643]
We currently get a trickle of PRs on each JetBrains product whenever somebody feels like updating the thing they use. They release fairly often, so it would be nice to write some automation for this process.

JetBrains [pointed me to](https://twitter.com/jetbrains/status/849192589626548224) an XML URL which seems to tell what the latest build number of each product is:

https://www.jetbrains.com/updates/updates.xml

On the downloads pages they also provide sha256 checksums, which will come in handy.

**Comment by volth** [comment]
What would the policy for such updates?
1. Update nixpkgs as soon as new version is released?
2. Update to the latest versions on, say, Mondays?
3. Update to the version which are out there at least a week to let early adopters step into oops-issues (like one we recently had with scala-2.11.9)?
4. ???

**Comment by chris-martin** [comment]
@volth I imagine master would be updated just whenever somebody feels like running the script. Are you asking what the policy would be for backporting into releases?

**Comment by volth** [comment]
you are right, since we have the unstable branch, it is not so important.

**Comment by volth** [comment]
I tried to automate it yesterday (to make https://github.com/NixOS/nixpkgs/pull/26753 ), it is not easy: the xml file has no direct download links, only links to dowload page, which has links only to EAP (unstable) versions of the products. To get download links to *.tar.gz and *.tar.gz.sha256 of stable products, one more html to be parsed.
They could change layout of the website prior to we run the script next time :(

**Comment by Mic92** [comment]
The download urls are stable and could be hard-coded for sake of simplicity. Therefore only having the version should.

**Comment by Mic92** [comment]
Is also back-ported most of the updates back to stable (minor-releases).
