### ISSUE TITLE
imhex: File opening does not work

### ISSUE THREAD

**Issue by snicket2100** [NixOS/nixpkgs#246512]
### Describe the bug

The "Open file" feature does not work.

### Steps To Reproduce

1. Start `imhex`.
2. Select "File" -> "Open File..." from the main menu.
3. See the error message:

![error](https://github.com/NixOS/nixpkgs/assets/57048005/108a068f-da6d-49a4-bc57-02daddef0e3c)

### Expected behavior

The open file dialog works.

### Notify maintainers

@Luis-Hebendanz 

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"                                                                                                                                           ✔ 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.39, NixOS, 23.05 (Stoat), 23.05.2385.48e82fe1b1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by Luis-Hebendanz** [comment]
Ahh yes this is known behavior. This isn't a bug of imhex but most probably a configuration issue with your desktop. I assume you are using i3 or something like that?
