### ISSUE TITLE
[Feature request] Extensible submodules

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#24653]
Currently one can create additional NixOS options. But I'd like to add local option
```
services.nginx.virtualHosts.*.locations.*.tomcatProxy = mkOption { type = types.bool; };
```
which desugars into custom lines for `services.nginx.virtualHosts.*.locations.*.extraConfig`.

Currently I see no way to do this except patching nixpkgs/nixos subtree.

**Comment by ericsagnes** [comment]
@nbp can probably provide better insight on this, but IIRC submodules by themselves are extensible, see how `fileSystems` are declared in mutiple modules for example.

The main problem is when, like in the provided example, one wants to extend a submodule that is inside multiple level of `listOf`/`attrsOf` submodules.

For the moment, I think that [replacing the concerned module](https://github.com/NixOS/nixpkgs/pull/22764) can be a "reasonable" approach for such cases.

**Comment by danbst** [comment]
I see: `nixos/modules/tasks/filesystems.nix`, `nixos/modules/tasks/encrypted-devices.nix` and `nixos/modules/system/boot/stage-1.nix`. Last two modules use `options` argument, which is marked "obsolete" in `lib/options.nix`.

Replacing a module is a workaround, thanks (though didn't yet tested that).

**Comment by ericsagnes** [comment]
> Last two modules use options argument, which is marked "obsolete" in lib/options.nix.

Correct, but I think this remark is even more obsolete as it is refering to `types.optionSet`, that is the submodules ancestor and also obsolete :)
If you are interested, the logic used to merge submodules is in [`mergeOptionDecls` in `lib/module.nix`](https://github.com/NixOS/nixpkgs/blob/212efab7ace3b6a42f7955bf48286c78e218bfa0/lib/modules.nix#L242-L280).

I suppose that there might be something to do by moving the submodule merging logic to the the type level like done with [extensible option types](http://nixos.org/nixos/manual/index.html#sec-option-declarations-eot), but submodules are still a wild beast to me.

**Comment by nbp** [comment]
> Correct, but I think this remark is even more obsolete as it is refering to types.optionSet, that is the submodules ancestor and also obsolete :)

submodules are not obsolete, and is the only proper way to nest options.

> But I'd like to add local option [...] Currently I see no way to do this except patching nixpkgs/nixos subtree.

Submodules are extensible. The `filesystems.*.<option>` are not all defined in the same files.  They can also be defined locally without modifying NixOS.

```nix
{ lib, ... }:
with lib;
{
  options = {
    services.nginx.virtualHosts = mkOption {
      type = types.attrsOf (types.submodule ({ ... }: {
        options = {
          locations = mkOption {
            type = types.attrsOf (types.submodule ({ config, ... }: {
              options = {
                tomcatProxy = mkOption { type = types.bool; };
              };
              config = {
                extraConfig = "tomcat-proxy ${if config.tcomcatProxy then "true" else "false"}";
              };
            }));
          };
        };
      }));
    };
}
```

**Comment by danbst** [comment]
wow, that's great news and it actually works for me!
