### ISSUE TITLE
Package request: markwhen CLI

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#246624]
A CLI program that renders Markdown timeline as HTML

https://docs.markwhen.com/cli.html

Announced: https://news.ycombinator.com/item?id=36944152

**Metadata**

* homepage URL: https://docs.markwhen.com/cli.html
* source URL: https://github.com/mark-when/mw
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by dotlambda** [comment]
Since upstream has a `package-lock.json` this should be pretty simple using `buildNpmPackage`.
