### ISSUE TITLE
nix-shell doesn't work in the background

### ISSUE THREAD

**Issue by ashkitten** [NixOS/nixpkgs#24661]
## Issue description
nix-shell will not work in the background, at least when used from a shebang. It immediately stops and does not continue until foregrounded.

### Steps to reproduce
- Create file "test" with contents:
```bash
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p bash
echo "This should print immediately and exit"
```
- set file to be executable
- execute in the background - `./test &`
- line does not print
- foreground the process - `fg`
- it will print the line and exit now

## Technical details

* System: NixOS 17.09pre104936.b0d07aa894 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.09pre104936.b0d07aa894"

**Comment by copumpkin** [comment]
This feels like it belongs in the https://github.com/NixOS/nix tracker

**Comment by mmahut** [comment]
If this is still an issue, please open the issue in the ``nix`` tracker.
