### ISSUE TITLE
Update request: jetbrains.plugins nixidea 0.4.0.9 → 0.4.0.10

### ISSUE THREAD

**Issue by p-rintz** [NixOS/nixpkgs#246634]
- Package name: jetbrains.plugins nixidea
- Latest released version: 0.4.0.10

- Current version on the unstable channel: 0.4.0.9
- Current version on the stable/release channel: n/a

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@dritter 

-----

Download link of new version is: https://plugins.jetbrains.com/files/8607/370632/NixIDEA-0.4.0.10.zip

Release on Github: https://github.com/NixOS/nix-idea/releases/tag/v0.4.0.10
It supports Build 222 up to 232.

Note for maintainers: Please tag this issue in your PR.

**Comment by pinpox** [comment]
Isn't this closed by https://github.com/NixOS/nixpkgs/pull/247219 ?

**Comment by dritter** [comment]
You are right @pinpox .
Thanks.
