### ISSUE TITLE
Update request: lemmy-{server,ui} 0.18.2 → 0.18.3

### ISSUE THREAD

**Issue by arjan-s** [NixOS/nixpkgs#246620]
- Package name: lemmy-server and lemmy-ui
- Latest released version: 0.18.3

- Current version on the unstable channel: 0.18.2
- Current version on the stable/release channel: 0.17.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@happysalada @billewanick @adisbladis

https://github.com/LemmyNet/lemmy/releases/tag/0.18.3
https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md

This release brings major performance optimizations and security improvements.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by happysalada** [comment]
hey, thanks for creating this issue!
if you want to generate an update yourself next time, lemmy has an update script
you can run `./pkgs/servers/web-apps/lemmy/update.py`
this is how I generated https://github.com/NixOS/nixpkgs/pull/246940
if you have time to test of course, it's always appreciated.

**Comment by arjan-s** [comment]
Thanks!
Yeah, I know about updating packages, but `nix-update -u lemmy-server` returned an error I didn't understand and I didn't have much time to look into it. Right now it works as expected, so it must have been a glitch in the Matrix...

**Comment by happysalada** [comment]
Its not a glitch.
Lemmy is a little more complicated than the normal package, so it has a custom update script that needs to be run (which i referenced in the previous comment).
A normal update will not work when there actually is a new version.

**Comment by arjan-s** [comment]
That's why I used the `-u` in the command :)
But anyway, it works again so it was just a glitch yesterday.
Thanks for updating the package! I'll try to make some time tonight to test it.

**Comment by happysalada** [comment]
I didnt know about that flag, well today i learned.
Thanks for making time to test !
