### ISSUE TITLE
hplip: "printer stopped, filter failed" status

### ISSUE THREAD

**Issue by bugaev** [NixOS/nixpkgs#24662]
## Issue description
Using a network printer LaserJet 500 M551 from HP.
Shortly after submission of any document, the CUPS "printers" tab of the http interface reports status "**stopped, filter failed**".

### Steps to reproduce

- Install NixOS 16.09
- Switch to nixos-16.09 channel for updates `nix-channel --add https://nixos.org/channels/nixos-16.09 nixos`

Follow [https://nixos.org/wiki/Printers](url) to modify "/etc/nixos/configuration.nix" and to 
choose the HP driver printer with the "hp-setup" utility from the "hplip" package:

-  /etc/nixos/configuration.nix:
<pre><code>
services.printing = {
    enable = true;
    gutenprint = true;
    drivers = [ pkgs.hplipWithPlugin ];
};
</pre></code>

- run  `$(nix-build '<nixpkgs>' --no-out-link -A hplip)/bin/hp-setup` to select the network printer and the driver `<hash>-python2.7-hplip-3.16.5/share/ppd/HP/hp-laserjet_500_color_m551-ps.ppd.gz`, which matches exactly the model of the printer

- Print a test page

- Check the printing job status: direct your browser to http://localhost:631/printers/HP_LaserJet_500_color_M551 and find the **printer stopped, filter failed** status.

- Check the CUPS service log (as suggested by redditor _saae_): `journalctl -b -e _SYSTEMD_UNIT=cups.service` and find a Python error message **OSError: [Errno 2] No such file or directory**.

<pre><code>
    -- Logs begin at Sun 2016-10-09 18:54:26 CDT, end at Fri 2017-03-17 16:21:43 CDT. --
    Mar 17 16:06:09 foo cups-pre-start[794]: Updated /var/lib/cups/ppd/max.ppd using gutenprint.5.2://bjc-MAXIFY-MB5320/expert
    Mar 17 16:06:09 foo cups-pre-start[794]: Updated 1 PPD file, 1 skipped.
    Mar 17 16:06:09 foo cupsd[918]: No limit for Validate-Job defined in policy default and no suitable template found.
    Mar 17 16:06:09 foo cupsd[918]: No limit for Cancel-Jobs defined in policy default - using Pause-Printer's policy.
    Mar 17 16:06:09 foo cupsd[918]: No limit for Cancel-My-Jobs defined in policy default - using Send-Document's policy.
    Mar 17 16:06:09 foo cupsd[918]: No limit for Close-Job defined in policy default - using Send-Document's policy.
    Mar 17 16:06:09 foo cupsd[918]: No limit for CUPS-Get-Document defined in policy default - using Send-Document's policy.
    Mar 17 16:06:09 foo cupsd[918]: No JobPrivateAccess defined in policy default - using defaults.
    Mar 17 16:06:09 foo cupsd[918]: No JobPrivateValues defined in policy default - using defaults.
    Mar 17 16:06:09 foo cupsd[918]: No SubscriptionPrivateAccess defined in policy default - using defaults.
    Mar 17 16:06:09 foo cupsd[918]: No SubscriptionPrivateValues defined in policy default - using defaults.
    Mar 17 16:06:09 foo cupsd[918]: Remote access is disabled.
    Mar 17 16:06:09 foo cupsd[918]: Loaded configuration file "/etc/cups/cupsd.conf"
    Mar 17 16:06:09 foo cupsd[918]: Configured for up to 100 clients.
    Mar 17 16:06:09 foo cupsd[918]: Allowing up to 100 client connections per host.
    Mar 17 16:06:09 foo cupsd[918]: Using policy "default" as the default.
    Mar 17 16:06:09 foo cupsd[918]: Full reload is required.
    Mar 17 16:06:09 foo cupsd[918]: Loaded MIME database from "/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/share/cups/mime" and "/etc/cups": 49 types, 84 filters...
    Mar 17 16:06:10 foo cupsd[918]: Loading job cache file "/var/cache/cups/job.cache"...
    Mar 17 16:06:10 foo cupsd[918]: Loading from cache...
    Mar 17 16:06:10 foo cupsd[918]: Loading from cache...
    Mar 17 16:06:10 foo cupsd[918]: Loading attributes...
    Mar 17 16:06:10 foo cupsd[918]: Full reload complete.
    Mar 17 16:06:10 foo cupsd[918]: Cleaning out old files in "/var/cache/cups".
    Mar 17 16:06:10 foo cupsd[918]: CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: Registering ICC color profiles for "HP_LaserJet_500_color_M551".
    Mar 17 16:06:10 foo cupsd[918]: CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: CreateProfile failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: Registering ICC color profiles for "max".
    Mar 17 16:06:10 foo cupsd[918]: CreateDevice failed: org.freedesktop.DBus.Error.ServiceUnknown:The name org.freedesktop.ColorManager was not provided by any .service files
    Mar 17 16:06:10 foo cupsd[918]: Listening to 127.0.0.1:631 on fd 7...
    Mar 17 16:06:10 foo cupsd[918]: Listening to /var/run/cups/cups.sock on fd 8...
    Mar 17 16:06:10 foo cupsd[918]: Resuming new connection processing...
    Mar 17 16:06:43 foo cupsd[918]: Saving printers.conf...
    Mar 17 16:07:20 foo cupsd[918]: Unloading...
    Mar 17 16:07:47 foo cupsd[918]: Adding start banner page "none".
    Mar 17 16:07:47 foo cupsd[918]: Queued on "HP_LaserJet_500_color_M551" by "supremacsy".
    Mar 17 16:07:47 foo cupsd[918]: REQUEST localhost - - "POST /printers/HP_LaserJet_500_color_M551 HTTP/1.1" 200 550 Create-Job successful-ok
    Mar 17 16:07:47 foo cupsd[918]: Auto-typing file...
    Mar 17 16:07:47 foo cupsd[918]: Request file type is application/postscript.
    Mar 17 16:07:47 foo cupsd[918]: File of type application/postscript queued by "supremacsy".
    Mar 17 16:07:47 foo cupsd[918]: Adding end banner page "none".
    Mar 17 16:07:47 foo cupsd[918]: time-at-processing=1489784867
    Mar 17 16:07:47 foo cupsd[918]: 2 filters for job:
    Mar 17 16:07:47 foo cupsd[918]: pstops (application/postscript to application/vnd.cups-postscript, cost 66)
    Mar 17 16:07:47 foo cupsd[918]: hpps (application/vnd.cups-postscript to printer/HP_LaserJet_500_color_M551, cost 0)
    Mar 17 16:07:47 foo cupsd[918]: job-sheets=none,none
    Mar 17 16:07:47 foo cupsd[918]: argv[0]="HP_LaserJet_500_color_M551"
    Mar 17 16:07:47 foo cupsd[918]: argv[1]="32"
    Mar 17 16:07:47 foo cupsd[918]: argv[2]="supremacsy"
    Mar 17 16:07:47 foo cupsd[918]: argv[3]="foo-bar-baz.pdf"
    Mar 17 16:07:47 foo cupsd[918]: argv[4]="1"
    Mar 17 16:07:47 foo cupsd[918]: argv[5]="noCollate finishings=3 fit-to-page media=Letter number-up=1 outputorder=normal page-bottom=10 page-left=10 page-right=10 page-top=10 portrait sides=one-sided job-uuid=urn:uuid:81171d57-9302-38b8-79aa-073857009f8e job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1489784867 time-at-processing=1489784867 document-name-supplied=okularYG1533.ps Duplex=None PageSize=Letter"
    Mar 17 16:07:47 foo cupsd[918]: argv[6]="/var/spool/cups/d00032-001"
    Mar 17 16:07:47 foo cupsd[918]: envp[0]="PATH=/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/filter:/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/bin"
    Mar 17 16:07:47 foo cupsd[918]: envp[1]="CUPS_CACHEDIR=/var/cache/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[2]="CUPS_DATADIR=/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/share/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[3]="CUPS_DOCROOT=/nix/store/d9vkkl19f1b91mxnaaxsghsj1awiiw1r-cups-2.1.4/share/doc/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[4]="CUPS_FONTPATH=/nix/store/d9vkkl19f1b91mxnaaxsghsj1awiiw1r-cups-2.1.4/share/cups/fonts"
    Mar 17 16:07:47 foo cupsd[918]: envp[5]="CUPS_REQUESTROOT=/var/spool/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[6]="CUPS_SERVERBIN=/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[7]="CUPS_SERVERROOT=/etc/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[8]="CUPS_STATEDIR=/var/run/cups"
    Mar 17 16:07:47 foo cupsd[918]: envp[9]="HOME=/tmp"
    Mar 17 16:07:47 foo cupsd[918]: envp[10]="SERVER_ADMIN=root@foo"
    Mar 17 16:07:47 foo cupsd[918]: envp[11]="SOFTWARE=CUPS/2.1.4"
    Mar 17 16:07:47 foo cupsd[918]: envp[12]="TMPDIR=/tmp"
    Mar 17 16:07:47 foo cupsd[918]: envp[13]="USER=root"
    Mar 17 16:07:47 foo cupsd[918]: envp[14]="CUPS_MAX_MESSAGE=2047"
    Mar 17 16:07:47 foo cupsd[918]: envp[15]="CUPS_SERVER=/var/run/cups/cups.sock"
    Mar 17 16:07:47 foo cupsd[918]: envp[16]="CUPS_ENCRYPTION=IfRequested"
    Mar 17 16:07:47 foo cupsd[918]: envp[17]="IPP_PORT=631"
    Mar 17 16:07:47 foo cupsd[918]: envp[18]="CHARSET=utf-8"
    Mar 17 16:07:47 foo cupsd[918]: envp[19]="LANG=en_US.UTF-8"
    Mar 17 16:07:47 foo cupsd[918]: envp[20]="PPD=/etc/cups/ppd/HP_LaserJet_500_color_M551.ppd"
    Mar 17 16:07:47 foo cupsd[918]: envp[21]="RIP_MAX_CACHE=128m"
    Mar 17 16:07:47 foo cupsd[918]: envp[22]="CONTENT_TYPE=application/postscript"
    Mar 17 16:07:47 foo cupsd[918]: envp[23]="DEVICE_URI=hp:/net/HP_LaserJet_500_color_M551?hostname=foo.bar.baz"
    Mar 17 16:07:47 foo cupsd[918]: envp[24]="PRINTER_INFO=HP LaserJet 500 color M551 Postscript (recommended)"
    Mar 17 16:07:47 foo cupsd[918]: envp[25]="PRINTER_LOCATION="
    Mar 17 16:07:47 foo cupsd[918]: envp[26]="PRINTER=HP_LaserJet_500_color_M551"
    Mar 17 16:07:47 foo cupsd[918]: envp[27]="PRINTER_STATE_REASONS=none"
    Mar 17 16:07:47 foo cupsd[918]: envp[28]="CUPS_FILETYPE=document"
    Mar 17 16:07:47 foo cupsd[918]: envp[29]="FINAL_CONTENT_TYPE=application/vnd.cups-postscript"
    Mar 17 16:07:47 foo cupsd[918]: envp[30]="AUTH_I****"
    Mar 17 16:07:47 foo cupsd[918]: Started filter /nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/filter/pstops (PID 1566)
    Mar 17 16:07:47 foo cupsd[918]: Started filter /nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/filter/hpps (PID 1567)
    Mar 17 16:07:47 foo cupsd[918]: Started backend /nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/backend/hp (PID 1568)
    Mar 17 16:07:47 foo cupsd[918]: REQUEST localhost - - "POST /printers/HP_LaserJet_500_color_M551 HTTP/1.1" 200 8581436 Send-Document successful-ok
    Mar 17 16:07:47 foo cupsd[918]: Page = 612x792; 12,12 to 600,780
    Mar 17 16:07:47 foo cupsd[918]: slow_collate=0, slow_duplex=0, slow_order=0
    Mar 17 16:07:47 foo cupsd[918]: Before copy_comments - %!PS-Adobe-3.0
    Mar 17 16:07:47 foo cupsd[918]: %!PS-Adobe-3.0
    Mar 17 16:07:47 foo cupsd[918]: %Produced by poppler pdftops version: 0.47.0 (http://poppler.freedesktop.org)
    Mar 17 16:07:47 foo cupsd[918]: %%Creator: ROOT Version 5.34/04
    Mar 17 16:07:47 foo cupsd[918]: %%Title: foo-bar-baz.pdf
    Mar 17 16:07:47 foo cupsd[918]: %%LanguageLevel: 2
    Mar 17 16:07:47 foo cupsd[918]: %%DocumentSuppliedResources: (atend)
    Mar 17 16:07:47 foo cupsd[918]: %%DocumentMedia: Letter 612 792 0 () ()
    Mar 17 16:07:47 foo cupsd[918]: %%BoundingBox: 0 0 612 792
    Mar 17 16:07:47 foo cupsd[918]: %%Pages: 1
    Mar 17 16:07:47 foo cupsd[918]: %%EndComments
    Mar 17 16:07:47 foo cupsd[918]: Before copy_prolog - %%BeginDefaults
    Mar 17 16:07:47 foo cupsd[918]: Before copy_setup - %%BeginSetup
    Mar 17 16:07:47 foo cupsd[918]: Before page loop - %%Page: 1 1
    Mar 17 16:07:47 foo cupsd[918]: Copying page 1...
    Mar 17 16:07:47 foo cupsd[918]: pagew = 592.0, pagel = 772.0
    Mar 17 16:07:47 foo cupsd[918]: bboxx = -233, bboxy = 224, bboxw = 568, bboxl = 384
    Mar 17 16:07:47 foo cupsd[918]: PageLeft = 10.0, PageRight = 602.0
    Mar 17 16:07:47 foo cupsd[918]: PageTop = 782.0, PageBottom = 10.0
    Mar 17 16:07:47 foo cupsd[918]: PageWidth = 612.0, PageLength = 792.0
    Mar 17 16:07:47 foo cupsd[918]: STATE: +connecting-to-device
    Mar 17 16:07:47 foo cupsd[918]: Traceback (most recent call last):
    Mar 17 16:07:47 foo cupsd[918]: File \"/nix/store/1103r300n8wknaa0d5kvdyr2kh3lsb0j-python2.7-hplip-3.16.5/lib/cups/filter/.hpps-wrapped\", line 204, in <module>
    Mar 17 16:07:47 foo cupsd[918]: p = subprocess.Popen([\'hostname\', \'-s\'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    Mar 17 16:07:47 foo cupsd[918]: File \"/nix/store/a21ahiimxzb3gc9vgdvxqlv4p4n5iph8-python-2.7.13/lib/python2.7/subprocess.py\", line 390, in __init__
    Mar 17 16:07:47 foo cupsd[918]: errread, errwrite)
    Mar 17 16:07:47 foo cupsd[918]: File \"/nix/store/a21ahiimxzb3gc9vgdvxqlv4p4n5iph8-python-2.7.13/lib/python2.7/subprocess.py\", line 1024, in _execute_child
    Mar 17 16:07:47 foo cupsd[918]: raise child_exception
    Mar 17 16:07:47 foo cupsd[918]: OSError: [Errno 2] No such file or directory
    Mar 17 16:07:47 foo cupsd[918]: PID 1567 (/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/filter/hpps) stopped with status 1.
    Mar 17 16:07:47 foo cupsd[918]: Hint: Try setting the LogLevel to "debug" to find out more.
    Mar 17 16:07:47 foo cupsd[918]: STATE: -connecting-to-device
    Mar 17 16:07:47 foo cupsd[918]: STATE: -media-empty-error,media-jam-error,hplip.plugin-error,cover-open-error,toner-empty-error,other
    Mar 17 16:07:47 foo cupsd[918]: Wrote 1 pages...
    Mar 17 16:07:47 foo cupsd[918]: PID 1566 (/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/filter/pstops) exited with no errors.
    Mar 17 16:07:55 foo cupsd[918]: ready to print
    Mar 17 16:07:55 foo cupsd[918]: PID 1568 (/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/backend/hp) exited with no errors.
    Mar 17 16:07:55 foo cupsd[918]: Job stopped due to filter errors; please consult the error_log file for details.
    Mar 17 16:07:56 foo cupsd[918]: Unloading...
    Mar 17 16:08:18 foo cupsd[918]: Saving job.cache...
    Mar 17 16:08:47 foo cupsd[918]: [Client 128] Started "/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/cgi-bin/printers.cgi" (pid=1710, file=13)
    Mar 17 16:08:47 foo cupsd[918]: PID 1710 (/nix/store/bkn53cvgh4vsnq16qsgm8d7xm0hn2smb-cups-progs/lib/cups/cgi-bin/printers.cgi) exited with no errors.
</pre></code>

## Technical details

* System: NixOS  16.09.1836.067e66a (Flounder)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: 16.09.1836.067e66a

**Comment by vcunat** [comment]
Side note: 16.09 is expected to be supported only until about the end of the month.  (But I don't know if this particular issue has been fixed yet, e.g. in 17.03.)

**Comment by jpotier** [comment]
Then, maybe this should be tested against 17.03, @bugaev did you upgrade already?

**Comment by bugaev** [comment]
@vcunat @jpotier: I have installed 17.03 on a different system, from scratch. The same error messages persist in both CUPS Web interface and in a log of "cups.service":

```Apr 06 17:43:13 irene cupsd[929]: STATE: +connecting-to-device
Apr 06 17:43:13 irene cupsd[929]: Traceback (most recent call last):
Apr 06 17:43:13 irene cupsd[929]: File \"/nix/store/z14zvcilg3f44syrjnajzfqw2612c22i-hplip-3.16.5/lib/cups/filter/.hpps-wrapped\", line 204, in <module>
Apr 06 17:43:13 irene cupsd[929]: p = subprocess.Popen([\'hostname\', \'-s\'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Apr 06 17:43:13 irene cupsd[929]: File \"/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/subprocess.py\", line 390, in __init__
Apr 06 17:43:13 irene cupsd[929]: errread, errwrite)
Apr 06 17:43:13 irene cupsd[929]: File \"/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/subprocess.py\", line 1024, in _execute_child
Apr 06 17:43:13 irene cupsd[929]: raise child_exception
Apr 06 17:43:13 irene cupsd[929]: OSError: [Errno 2] No such file or directory
Apr 06 17:43:13 irene cupsd[929]: STATE: -connecting-to-device
Apr 06 17:43:13 irene cupsd[929]: STATE: -media-empty-error,media-jam-error,hplip.plugin-error,cover-open-error,toner-empty-error,other
Apr 06 17:43:13 irene cupsd[929]: PID 1659 (/nix/store/5v0sch1w3p8nspzx4frp8havqch2dlrx-cups-progs/lib/cups/filter/hpps) stopped with status 1.
```

**Comment by ericsagnes** [comment]
Had the same issue with a HP Envy 5530, but upgrading to the latest unstable (17.09pre105060.0a6a06346a) fixed the problem.

**Comment by bugaev** [comment]
@ericsagnes  Thank you for letting us know! I wonder if you updated all your system packages from the unstable branch or there is a trick to install only hplip.

**Comment by bugaev** [comment]
I have upgraded the system to
```
> nixos-version
17.09pre105060.0a6a06346a (Hummingbird)
```
The error messages are the same.

Then I realized that the driver picker started by
 `$(nix-build '<nixpkgs>' --no-out-link -A hplip)/bin/hp-setup`
 offers **`hp-laserjet_500_color_m551-ps.ppd.gz`** exactly matching the model of my printer, which **is not offered by the CUPS Web interface**. That made me think that `hp-laserjet_500_color_m551-ps.ppd.gz` is tainted somehow and I better try some other driver that is in the options offered by the CUPS.

I made a short in the dark and picked "HP Color LaserJet 5, hpcups 3.16.11" from the CUPS list.
**The selected driver works fine with my printer**.

**Comment by jpotier** [comment]
Great \o/

So, your problem is solved, right? If so, it may be time to close this issue.

**Comment by bugaev** [comment]
Closing the issue with a word of advice: after finishing with `hp-setup`, go to the CUPS Web interface and make sure your driver is one of the options there, too. If not, choose something else.

**Comment by karolchmist** [comment]
Just in case it helps someone : I had a similar problem and it was solved by enabling printing with `hplipWithPlugin` as well as installing `hplip` in `environment.systemPackages`.
