### ISSUE TITLE
Including full ubuntu kmod blacklist isn't customizable

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#24675]
## Issue description

We're using the i6300esb watchdog in our virtual machines and want the module loaded. When trying to customize this we noticed that normal distributions provide the blacklist and ask users to edit it and comment out the modules they want.

This isn't a feasable approach for NixOS and we just resorted to overriding the full ubuntu etc object with our own copy. It would be nice if you could use a more fine-grained approach on the NixOS module/configuration level.

### Steps to reproduce

* Start VM with NixOS where the virtual hardware has the watchdog enabled
* Check whether the kernel module (i6300esb) is loaded after boot

## Technical details

* System: 15.09 (but it still applies to master right now, just with a different version of the ubuntu list)
* Nix version: n/a
* Nixpkgs version: n/a

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by ctheune** [comment]
I think this isn't any issue any longer.
