### ISSUE TITLE
Rename the httpd module to apache

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#24670]
## Issue description

`httpd` is a generic name for an http daemon, and is [not specific to the apache HTTP server](https://en.wikipedia.org/wiki/Httpd).  
To avoid confusion and put apache to an equal level with other http daemons available in NixOS, the `services.httpd` module namespace should be renamed to `services.apache`.

**Comment by edolstra** [comment]
The Apache project has many subprojects of which `httpd` is only one. So *if* we're going to rename it, it should be to `apacheHttpd` or `apache-httpd`. But I'm kind of "meh" on renaming it...

**Comment by danbst** [comment]
`apache-httpd` is very ok

**Comment by nixy** [comment]
This is kind of an arbitrary thing. Some distributions such as Debian and Ubuntu call it apache, but others call it httpd. I think changing the name to something like apacheHttpd would be silly as its quite long and nonstandard. I feel `httpd` is fine as other distributions use this so its pretty familiar to users of Red Hat like distributions.

**Comment by ericsagnes** [comment]
Agreeing with the majority, thanks for the feedback!
