### ISSUE TITLE
grafana-agent: ships without web ui

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#246742]
### Describe the bug
I started grafana-agent in flow mode, and tried to access the http API at http://localhost:12345.

Unfortunately, instead of providing a web interface to debug the current list of components, I get a "404 page not found".

### Steps To Reproduce
1. Run grafana-agent in flow mode.
2. Access port 12345 via HTTP

### Expected behavior
I'd expect grafana-agent to ship with the web interface.

### Screenshots
-

### Additional context
-

### Notify maintainers
@emilylange @flokli 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by flokli** [comment]
It looks like `web/ui` is what's building the frontend. Unfortunately, the web interface seems managed by yarn (and has a yarn.lock), so we'd need to first provide a `package-lock.json`.

I tried to have `npm` resolve the dependency, but it seems it's not able to:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: grafana-agent@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @grafana/ui@9.5.2
npm ERR! node_modules/@grafana/ui
npm ERR!   @grafana/ui@"^9.5.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/flokli/.npm/_logs/2023-08-02T09_11_41_196Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flokli/.npm/_logs/2023-08-02T09_11_41_196Z-debug-0.log
```

**Comment by flokli** [comment]
I manually patched things in `package.json` to bump `@grafana/ui` to a more recent version, compatible with the react version that's mentioned in `package.json`, but ugh, I'm not really sure why it's that way. I'll ask upstream.

**Comment by emilylange** [comment]
yeah, sorry, I don't use flow mode (yet?) and the nixos module does not support it either, as far as I am aware.

I can try looking into it as well, first, before you raise an issue upstream.
While the nixos module might lack support for it (for now?), I believe we should try fix it nonetheless :)

**Comment by flokli** [comment]
Yeah, we should probably have a second NixOS module for flow mode, it's very different and the existing config structure doesn't make much sense - for now I just did ship my own custom systemd unit for it:

```nix
  systemd.services.grafana-agent-flow = {
    wantedBy = [ "multi-user.target" ];
    environment.AGENT_MODE = "flow";
    serviceConfig =
      let
        configFile = (pkgs.writeText "config.river" ''
          prometheus.remote_write "vm" {
            endpoint {
              url = "http://localhost:8428/vm/api/v1/write"
            }
          }

          prometheus.scrape "example" {
            targets = [{
              __address__ = "example.com:80",
            }]

            forward_to = [prometheus.remote_write.vm.receiver]
          }
        '');
      in
      {
        ExecStart = "${lib.getExe pkgs.grafana-agent} run ${configFile} --storage.path /var/lib/grafana-agent-bornhack";
        Restart = "always";
        DynamicUser = true;
        RestartSec = 2;
        StateDirectory = "grafana-agent-flow";
        Type = "simple";
      };
  };
```

But yeah, without the web ui it's quite annoying to debug, so we should probably get that sorted out first, before providing a module and getting more people to use it.

**Comment by emilylange** [comment]
#246853 fyi

**Comment by emilylange** [comment]
We should prefer yarn simply due to upstream having an `yarn.lock` instead of a `package-lock.json` :)

> Try to respect the package manager originally used by upstream (and use the upstream lock file)

^ https://nixos.org/manual/nixpkgs/stable/#javascript-upstream-package-manager
