### ISSUE TITLE
Package request: GLAuth

### ISSUE THREAD

**Issue by codyjamestechnical** [NixOS/nixpkgs#246893]
**Project description**
Go-lang LDAP Authentication (GLAuth) is a secure, easy-to-use, LDAP server w/ configurable backends.

**Metadata**

* homepage URL: https://glauth.github.io
* source URL: https://github.com/glauth/glauth
* license: mit
* platforms: linux, darwin, windows

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/239396
