### ISSUE TITLE
Albert not running natively on wayland

### ISSUE THREAD

**Issue by matthias-t** [NixOS/nixpkgs#246841]
### Describe the bug
Starting from 01e1c5bd408a6d5298a7c7c7f4ac983470b892ae the `albert` package will not run natively on Wayland anymore.
```console
$ albert
12:00:00 [warn:qt.qpa.plugin] Could not find the Qt platform plugin "wayland" in ""
…
^C
$ albert --platform wayland
21:15:02 [warn:qt.qpa.plugin] Could not find the Qt platform plugin "wayland" in ""
21:15:02 [fatal:default] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, offscreen, vnc, minimal, xcb, minimalegl, linuxfb, eglfs.
  --  [(null)]
Segmentation fault (core dumped)
```

When running without `--platform wayland`, on my machine the program will launch fine with some minor quirks, presumably using XCB and XWayland.

### Expected Behavior

The program should launch using the Wayland Qt platform plugin.

### Steps To Reproduce
Install `albert` and `sway` on the latest unstable channel.

```nix
programs.sway.enable = true;
programs.sway.extraPackages = with pkgs; [ albert ];
```

Then open a `sway` session. Inside a terminal emulator, launch `albert`.

### Additional context

Possibly because of upstream release [`v0.18.0`](https://github.com/albertlauncher/albert/blob/v0.18.0/CHANGELOG.md) updating to Qt6. However, adding `pkgs.qt6.qtwayland` to environment does not fix this issue.

### Notify maintainers

@Flakebi @ericsagnes @Synthetica9 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.6, NixOS, 23.11 (Tapir), 23.11pre509514.9e1960bc196b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(mth): `"nixpkgs"`
 - nixpkgs: `/home/mth/.nix-defexpr/channels/nixpkgs`
```

**Comment by Flakebi** [comment]
I get the same error as you when I **do not** have `qt6.qtwayland` in the environment.
But albert works fine for me on wayland with Qt6 qtwayland available.
```
environment.systemPackages = with pkgs; [ qt6.qtwayland ];
programs.sway.extraPackages = with pkgs; [ albert ];
```

**Comment by AlecsFerra** [comment]
Same issue
