### ISSUE TITLE
Wrapped babashka caused compatibility issues

### ISSUE THREAD

**Issue by sg-qwt** [NixOS/nixpkgs#246839]
### Describe the bug
The latest PR on https://github.com/NixOS/nixpkgs/pull/241119 introduced babashka and babashka-unwrapped.

However it introduced rlwrap as default for babashka, this caused compatibility issues. 

Example:
```
> cat bb.edn 
{
 :tasks
 {clean (println "clean")
  haha  (println "haha")}
}
```

`bb tasks|bb -io '(->> *input* (drop 2) (map #(-> % (str/split #" ") first)))'`
Running with babashka-unwrapped/bin/bb
```
> bb tasks|bb -io '(->> *input* (drop 2) (map #(-> % (str/split #" ") first)))'
clean
haha

```
Note: one empty line

Running with babashka/bin/bb
```
> bb tasks|bb -io '(->> *input* (drop 2) (map #(-> % (str/split #" ") first)))'
clean
haha


```
Note: two empty lines

As discussed with Michiel Borkent, upstream assumed the bb is shipped without rlwrap, that's the only bb supported by upstream.

So, this case we cannot introduce the default bb with rlwrap, which will cause all kinds of weird bugs and compatibility issues aroud io if upstream and all other distributions assume bb is without rlwrap.

Propose:
1. Right now simply revert #241119 or remove rlwrap from #241119
2. I don't mind having a rlwrap version of bb, as long as the binary in bin called something else, maybe `/bin/bbb`. Since upstream hasn't standardized naming conventions like clj/clojure. But bottom line is, rlwrapped one's binary should NOT be bb!

cc @jlesquembre @thiagokokada @bennyandresen @borkdude

**Comment by bennyandresen** [comment]
I agree with the revert course of action. I never pipe to babashka, which is why I didn't consider that use-case.

**Comment by jlesquembre** [comment]
IMO it's better to only remove rlwrap, that's the only part causing issues

**Comment by thiagokokada** [comment]
I think the best option would be to add `rlwrap` as an option of the wrap,
and set it to false by default.

**Comment by jlesquembre** [comment]
@sg-qwt 
see https://github.com/NixOS/nixpkgs/pull/248207
