### ISSUE TITLE
Slack blank window

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#24685]
## Issue description

With slack-2.5.1 and slack-2.5.2, starting slack results in a blank window with only the menu.

There is an error in the `~/.config/Slack/logs/renderer-\d+.log` file that must be the issue: `Error: libxkbfile.so.1: cannot open shared object file: No such file or directory`. Full log: https://gist.github.com/98e4f710f3679ac6fb7d9a6540c0bbc9

/cc @fooblahblah @Kendos-Kenlen @FaustXVI

### Steps to reproduce

```
$ nix-env -iA nixos.slack
$ slack
```

## Technical details

* System: 17.09.git.f18a600 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: 17.09pre104936.b0d07aa894

**Comment by zimbatm** [comment]
I wonder if node is trying to do FFI. libxkb seems to be linked properly:
```
[@x1:.../store/0rsk3x4jssb12b8r8dyx3djamy1n8qnh-slack-2.5.2]$ find -type f -executable | xargs ldd | grep libxkbfile
	libxkbfile.so.1 => /nix/store/8bbh82g70fqalqghnhl0c3rv9bdf5gyq-libxkbfile-1.0.9/lib/libxkbfile.so.1 (0x00007f2d91fb5000)
```

**Comment by fooblahblah** [comment]
I'm running slack-2.5.2 on NixOS 17.03 without issue. @zimbatm how long have you been on 17.09?

**Comment by zimbatm** [comment]
It's been at least a month now that I have been having the issue and avoiding it by using the browser instead. I got a change that potentially fixes the issue here: ^^

**Comment by jonafato** [comment]
@zimbatm Slack's been working for me for quite a while now. Is there anything more to be done on this issue at the moment?

**Comment by zimbatm** [comment]
all good
