### ISSUE TITLE
installing `vim_configurable.customize{...}` doesn't make vim's manpage available

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#24691]
## Issue description

The wrapper only has `.../bin/vim`, so the corresponding `.../share/man/...` where `man` would check for manpages is absent.

### Steps to reproduce

* don't have regular vim installed
* install something like `vim_configurable.customize{name="vim"; vimrcConfig={};}`
* `man vim`

## Technical details

17.09pre104936.b0d07aa894

**Comment by therealpxc** [comment]
You can find a fix in [this PR](https://github.com/NixOS/nixpkgs/pull/26111)/[this commit](7465a113406711ff718c96a31d9b82212f2b877a)
