### ISSUE TITLE
gnome3 improvements

### ISSUE THREAD

**Issue by viric** [NixOS/nixpkgs#247]
Quick guide on gnome3 https://wiki.gnome.org/SysAdminGuide
- GTK3 env vars https://developer.gnome.org/gtk3/stable/gtk-running.html
- Mailing list with important (security) issues for distributors: https://mail.gnome.org/mailman/listinfo/distributor-list

List of issues to be fixed:
- [ ] Documentation for GNOME 3 packaging (see #16285)
- [x] Seahorse crashes when clicking on a private key found from the gnome-shell search. Since 3.12, it does not even show in the applications.
- [ ] Grilo upnp does not show in the totem sidebar [**possibly fixed**]
- [ ] Other browsers installed from nix-env cannot be chosen as default application. [**possibly fixed**]
- [ ] GNOME sometimes loses the background/lock settings [**possibly fixed**]
- [ ] The default background cannot be chosen from the list of possible backgrounds. [**upstream issue**]
- [ ] Icons of user-installed applications via `nix-env` are missing from the gnome-shell activity [**possibly fixed**]
- [x] Cheese is able to show the webcam, but cannot take photos. Something is wrong with gst plugins or such... Maybe relevant: https://bugzilla.redhat.com/show_bug.cgi?id=1227010
- [x] Update gdm to 3.18, there's some wip code for 3.16. Now we're at 3.14.
- [x] Could not compile gtkmm 3.18 with new pangomm for weird c++11/libsigc++ errors.
- [ ] Cannot update profile in gnome-control-center. https://github.com/NixOS/nixpkgs/issues/10025
- [x] There's some bluetooth support, but somehow GNOME cannot find adapters/devices, nothing shows up. See http://lists.usefulinc.com/pipermail/gnome-bluetooth/2016-July/001515.html.

Some journalctl warnings to cleanup:
- [ ] `org.gnome.Calculator.SearchProvider[12182]: Error: ErrorCode.UNKNOWN_VARIABLE` [**possibly fixed**]
- [ ] `org.gnome.Characters.BackgroundService[4183]: (gjs:5031): Gjs-WARNING **: JS ERROR: Error: Requiring GjsPrivate, version none: Typelib file for namespace 'Gtk', version '3.0' not found` [**possibly fixed**]

Missing [core packages](https://download.gnome.org/core/3.18/3.18.0/sources/) left to be packaged:
- [ ] ~~seed~~
- [ ] mousetweaks [**is it needed?**]
- [ ] mm-common [**is it needed?**]
- [x] gtkmm

List of [apps](https://download.gnome.org/apps/3.18/3.18.0/sources/) to be packaged:
- [x] gnome-color-manager [**integrated into GNOME Control Center?**]
- ~~gnome-initial-setup~~ (not nixos friendly)
- [ ] gnome-sound-recorder [**broken**]
- [x] nemiver
- [x] orca
- [ ] rygel
- [x] gnome-tweak-tool

**Comment by geerds** [comment]
Missing application icons should be fixed with 1ce5c9683656f4aabe316f59cdafa74a7ce1b123

**Comment by lethalman** [comment]
@geerds thanks. The issue I stated in the check-list however is about `nix-env` installed applications. I've clarified the issue.

**Comment by geerds** [comment]
Default background (and screensaver) fixed with 97dd0dae7489cda16d8897aa289c3a9cd4f7ac56

**Comment by lethalman** [comment]
:beers: great!

**Comment by geerds** [comment]
@lethalman 1ce5c9683656f4aabe316f59cdafa74a7ce1b123 should also fix missing icons for user installed applications (via `nix-env`). Did you test it?

I just installed *dwb* and *midori* in my environment. The first application ships an icon under `$out/share/pixmaps` and the latter one `$out/share/icons/hicolor`. Both are working for me. Don't forget to restart gnome shell

**Comment by vcunat** [comment]
No, I don't think so, as other than system environments don't run the regenerators (still AFAIK).

**Comment by lethalman** [comment]
That's problem. You should not restart gnome-shell to see them in the
activities. It's not a problem of icons. It's that apps are not shown until
gnome is restarted. That's probably because nix-env substitutes the
symlink, while gnome is still watching the old directory.

On Fri, Jul 31, 2015 at 7:47 PM, Jascha Geerds <notifications@github.com>
wrote:

> @lethalman <https://github.com/lethalman> 1ce5c96
> <https://github.com/NixOS/nixpkgs/commit/1ce5c9683656f4aabe316f59cdafa74a7ce1b123>
> should also fix missing icons for user installed applications (via nix-env).
> Did you test it?
>
> I just installed *dwb* and *midori* in my environment. The first
> application ships an icon under $out/share/pixmaps and the latter one
> $out/share/icons/hicolor. Both are working for me. Don't forget to
> restart gnome shell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/247#issuecomment-126769535>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by geerds** [comment]
@lethalman I've fixed the gnome-tweak-tools issues in my branch: c10d0cb987b288b22bb6584381cf7f2b6bc367e0. What do you think? Should I push it?

(I'm going to fix this upstream but for now we should take these patches)

**Comment by lethalman** [comment]
@geerds :+1: push if it works

**Comment by geerds** [comment]
Now in nixpkgs:

[apps]
- gnome-weather
- gnome-maps
- gnome-logs

[devel]
- gnome-devel-docs

[games]
- gnome-sudoku
- aisleriot
- hitori
- five-or-more
- four-in-a-row
- gnome-chess
- gnome-klotski
- gnome-mahjongg
- gnome-mines
- gnome-nibbles
- gnome-robots
- gnome-tetravex
- gnome-taquin

If you find any bugs just ping me

**Comment by lethalman** [comment]
What an awesome work @geerds going to be the best gnome distro ever, step by step...

**Comment by geerds** [comment]
@lethalman thanks!

I've just added a few more:
- gnome-characters
- gnome-calendar
- accerciser

This issue is older than 2 years and constantly growing. Maybe we should close it and file separate issues for the outstanding things?

**Comment by lethalman** [comment]
@geerds there are still some major things to be done so I prefer keeping this opened.

**Comment by clacke** [comment]
I get only prefix search in gnome-shell, whereas on my Ubuntu Gnome I get a substring search. "inat" will find the "terminator" app. Do I add this here, or should it be a separate issue?

**Comment by lethalman** [comment]
@clacke depends if it's a particular ubuntu gnome feature (like a patch) or not. We can discuss here the findings...

**Comment by geerds** [comment]
@clacke Probably because we have no `gnome-software` in NixOS: https://bugzilla.gnome.org/show_bug.cgi?id=707594

@lethalman What do you think? Maybe we could bring `gnome-software` to NixOS (without the GUI application) and use the search provider

**Comment by lethalman** [comment]
@geerds if by available app it means .desktop files, certainly we can...

**Comment by geerds** [comment]
I guess it won't work because `gnome-software` depends on packagekit. There's no abstraction layer for nix, right? So `gnome-software` wouldn't return results for substring searches

**Comment by lethalman** [comment]
Correct. Again, depends if the search provider only works with .desktop files instead of system-wide installed apps.

**Comment by lethalman** [comment]
From a quick look at the code there's no plugin for looking into raw desktop files.

**Comment by lethalman** [comment]
GNOME 3.18 now in staging. I've added a couple of new issues to the list.

**Comment by meteficha** [comment]
It won't make it into 15.09, right?

**Comment by domenkozar** [comment]
Nope.

**Comment by domenkozar** [comment]
GNOME 3.18 is now merged, removing milestone.

**Comment by vcunat** [comment]
I checked a few things that were clearly done, some of them now in f412fb1.

**Comment by SShrike** [comment]
What is the status now, some of these bugs seem pretty serious. Blocking me from using NixOS as a daily driver.

**Comment by lethalman** [comment]
@SShrike those issues are still there, we've been barely able to update to 3.20 during this week

**Comment by SShrike** [comment]
@lethalman Ah okay :)

If you ever need help, I should be available on the weekends. I'm new to Nix/NixOS though, so you'd have to bear with some stupid mistakes probably.

**Comment by lethalman** [comment]
@SShrike of course, we need help for a lot of things. I'd say start from what you find inconvenient. That is, use the gnome desktop, do X because you need it, realize X is broken, work for fixing it.

**Comment by garbas** [comment]
to all: i'm not personally using gnome, but you made it possible for few of my family members to use nixos :) thank you

**Comment by lethalman** [comment]
@garbas ahah good to hear, and you should try it too... you know, it only takes a nixos config row :D

**Comment by Mounium** [comment]
I believe that solving https://github.com/NixOS/nixpkgs/issues/12757 _(gnome's activity tab doesn't contain freshly installed apps until new login)_ could be achieved by https://github.com/NixOS/nixpkgs/issues/3033   , namely setting correct dates on the .nix-profile/share folder's symbolic links (and possibly elsewhere as well), because after a bit of digging into the source codes of Gnome-shell, -menu and even glib I couldn't find anything hardcoded that wouldn't be compatible with NixOS's uniqe folder structure, the only necessity is the correct usage of XDG variables _(and under Gnome-shell XDG_DATA_DIRS is already filled with the themes icons' source folders as well as with the user's .nix-profile/share, which contains the newly installed apps' .desktop files)_. 

Unfortunately I am not versed in the inner workings of NixOS, and am not sure whether modifying dates inside .nix-profile would go against the NixOS philosophy, but considering that they are only symlinks, maybe they can contain the time of install.. Also, I am not good with the Nix language so I'm afraid I can't help (and probably for the better) with the actual issue..

**Comment by vcunat** [comment]
@Mounium: everything in the nix store is forced to fixed timestamps (unix time 1 IIRC).

**Comment by Mounium** [comment]
@vcunat /nix/var has some different timestamps. Symbolic links can have different timestamps from what they link to, can't they? So /nix/store can have 1970 everywhere, only /nix/var/nix/profiles/per-user/USER/.../share would be different (and the profiles themselves have an actual timestamp even currently as it seems). Nix should simply apply the profile's date of creation to the rest of it's subdirectories and files.

**Comment by Mounium** [comment]
@vcunat Strangely the profile link's have correct timestamps, but I see that the profiles themselves point to nix-store entries... Then maybe some temporary folder should be created (by copying the current profile) in which everything is modifyed to have the same timestamp as the profile link itself? Although I think it isn't 
 only a gnome problem

**Comment by vcunat** [comment]
Hmm, you'd have to do this copying everytime the profile is switched, etc... I don't much like that (nix itself would have to be changed).

**Comment by Mounium** [comment]
Then patch glib? I don't see any other option :(

**Comment by olejorgenb** [comment]
According to https://git.gnome.org/browse/devhelp/tree/README 

> When you build (or install) a GNOME library, it will build an
API reference for you and install it into:
>
>  $datadir/gtk-doc/html/$PACKAGE. 
>
>Along with the HTML files, a .devhelp and/or .devhelp2 index file is
>also generated automatically. Thus Devhelp can simply scan that folder
>for those index files and display the books they represent.

IIRC such documentation is usually separated out in a separate output $derivation.doc-somthing

That seems to be the case for `gnome3.glib`, but not eg. `gnome3.gnome_shell` and `gnome3.mutter`

It would be great if the `devdoc` output was available for all eligible gnome packages. 

Even better if `gnome3.devhelp` would find the available documentation - at least if run from a nix-shell with the devdoc outputs.

**Comment by vcunat** [comment]
I expect getting the docs would mostly be as simple as adding `"devdoc"` into outputs and adding `gtk-doc` to `nativeBuildInputs`.

**Comment by garbas** [comment]
Is somebody actively working on the checklist in the description?

/cc @lethalman

**Comment by jtojnar** [comment]
Most of these are either irreproducible, upstream bugs or other issues are opened. I am working on documentation in #16285. I added some annotations to the OP. The packages could be still added but I think it is better to open separate issues. I would close this as too broad.

**Comment by garbas** [comment]
I'm closing this issue as it is quite old and togeneral

@viric i hope this ok with you. please reopen the issue if you think it should stay open.

**Comment by Spass1966** [comment]
I have a bunch of GNOME apps which still don't run on NixOS with various errors in a GNOME 3 session. I'd be happy to open issues for them but first I am interested to know if it's an issue I have personally or if it applies to anyone running a GNOME session.

Boxes, Books, Music, Files, and Weather don't start and of course there's still the issue setting default apps (they can't be changed). All of these apps are included by default when `desktopManager.gnome3.enable=true;`

**Comment by jtojnar** [comment]
Personally, I have not encountered these problems but feel free to open issues and we will triage it.

As for `config.firefox.enableGnomeExtensions` only enables the native host connector – you will still need to install the [browser extension](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/) and enable the daemon:

https://github.com/NixOS/nixpkgs/blob/23453d2d8c7189d479e26de0cf87906cb5189870/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix#L37

**Comment by romildo** [comment]
I have an issue with `gnome-boxes`. After my (unstable) NixOS system is updated I cannot start my virtual machines anymore because the configuration files reference old paths for qemu in `/nix/store`. I have to manually edit the configuration files to update the qemu path so the new location is seen.
