### ISSUE TITLE
standardnotes: Selected text isn't highlighted

### ISSUE THREAD

**Issue by duxovni** [NixOS/nixpkgs#247053]
### Describe the bug

In standardnotes 3.167.2 from nixos-unstable, when selecting text, there's no visual indicator that the text is selected. It can still be cut, copied, dragged, etc, but it isn't highlighted in any way, making it very difficult to actually do anything involving selecting text.

### Steps To Reproduce
1. Create a note in standardnotes
2. Type some text in the note
3. Select the text

### Expected behavior
The selected text should be highlighted.

### Additional context
This bug is present whether I'm running standardnotes normally or in wayland-native mode, and is present when I update the derivation to use the latest version 3.167.28. When I revert #241831 and then re-run the update script to get the latest standardnotes using the upstream AppImage, the bug disappears, so it seems to be specifically tied to nixpkgs' electron.

### Notify maintainers

@mgregoire @chuangzhu @squalus

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.33-rt11, NixOS, 23.11 (Tapir), 23.11.20230802.66aedfd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by squalus** [comment]
I can reproduce this.

**Comment by duxovni** [comment]
This seems to be resolved, I can no longer reproduce the bug with standardnotes 3.178.4 from the current nixos-unstable.
