### ISSUE TITLE
Missing dependency of mendeley on gconftool-2

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#24709]
Following the Mendeley update in 37315d6, `mendeleydesktop` refuses to launch on one of my machine and spits out some errors half in French half in English:
```
/nix/store/0z9hhgzxwgcl1jk9x97bpri2sz6mzr13-mendeley-1.17.8-stable_amd64/bin/.install-mendeley-link-handler.sh-wrapped:
Erreur lors de la définition de la valeur : Le contact du serveur de configuration a échoué ; la cause la plus courante plus d'informations. (Détails -  1: GetIOR a échoué : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name 
Erreur lors de la définition de la valeur : Le contact du serveur de configuration a échoué ; la cause la plus courante plus d'informations. (Détails -  1: GetIOR a échoué : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name
```

This led me to think that the problem was with `.install-mendeley-link-handler.sh-wrapped` and calling it specifically gives:
```
which: no gconftool-2 in (/home/theo/bin:/run/wrappers/bin:/run/wrappers/bin:/home/theo/.nix-profile/bin:/home/theo/.nisbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current
Unable to find gconftool-2.  The mendeley:// link handler may not be installed correctly.
Usage: .install-mendeley-link-handler.sh-wrapped [options] <path>
 -u : Uninstall the mendeley:// link handler

Install the mendeley:// link handler to launch <path>
```

So the problem seems to be a missing dependency on `gconftool-2`.
Installing it with `nix-env -iA nixos.gnome2.GConf` fixed the problem for me. And this correlates with the fact that on my other machines (where I have XFCE installed), I had no problem launching Mendeley but that on this machine (where I only have i3 installed), I had such problems.

I'm not sure how to fix the problem in the derivation though.

cc @dtzWill @vcunat @FRidh

**Comment by Zimmi48** [comment]
Actually the other machines I have are laptops on which I have network-manager-applet and this is dependent on gconf. That's why Mendeley could run there.

**Comment by dtzWill** [comment]
I can confirm this is a problem, and will look into fixing it. Starting with the GConf stuff--what does installing it accomplish that we're not?

I mean we /could/ include gconf2 in "propagatedUserEnvPkgs" but hopefully that's not necessary.

**Comment by dtzWill** [comment]
Please let me know if #26942 doesn't fix this for you, sorry for the delay!
