### ISSUE TITLE
Update request: zig 0.10.1 → 0.11.0

### ISSUE THREAD

**Issue by Shinyzenith** [NixOS/nixpkgs#247069]
- Package name: zig
- Latest released version: 0.11.0
- Current version on the unstable channel: 0.10.1
- Current version on the stable/release channel: 0.10.1
- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aiotter 
@AndersonTorres
@andrewrk 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by AndersonTorres** [comment]
I'm not at home now. I'll look at it later.

Reading the release notes, I see that support for macos catalina 10.15 was dropped. It can be a bit problematic for us I suppose.
