### ISSUE TITLE
Timeshift can't create an rsync snapshot. Always 0% progress

### ISSUE THREAD

**Issue by gelerum** [NixOS/nixpkgs#247092]
### Describe the bug
Timeshift just doesn't backup and doesn't show estimating time.

### Steps To Reproduce
1. I innstalled with `nix-shell -p timeshift`
2. I launched `timeshift-launcher` as non-root user. Timeshift asked for the password
3. Tried to create an rsync snapshot on different encrypted disks with ext4 filesystem. The result is same each time.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/85288915/d5199154-82dc-45db-b3a4-662287f425af)

### Additional context
``` console
(timeshift-gtk:168624): dbind-WARNING **: 16:03:01.437: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
App config loaded: /etc/timeshift/timeshift.json
Mounted '/dev/dm-0 (nvme0n1p6)' at '/run/timeshift/168624/backup'
selected device: /dev/dm-2
E: Failed to execute child process “/root/.temp/ohfItTJ6/16911398134131654473.sh” (No such file or directory)
E: Failed to unmount

** (timeshift-gtk:168624): CRITICAL **: 16:03:33.566: tee_jee_logging_log_error: assertion 'message != NULL' failed
Mounted '/dev/dm-2' at '/run/timeshift/168624/backup'
App config saved: /etc/timeshift/timeshift.json

E: Failed to execute child process “/root/.temp/ohfItTJ6/1691139865504870587.sh” (No such file or directory)
E: Failed to estimate system size

** (timeshift-gtk:168624): CRITICAL **: 16:04:25.156: tee_jee_logging_log_error: assertion 'message != NULL' failed

** (timeshift-gtk:168624): CRITICAL **: 16:04:25.156: tee_jee_logging_log_error: assertion 'message != NULL' failed
App config saved: /etc/timeshift/timeshift.json


------------------------------------------------------------------------------
Estimating system size...
E: Failed to execute child process “/root/.temp/ohfItTJ6/16911398652749723382.sh” (No such file or directory)
E: Failed to estimate system size

** (timeshift-gtk:168624): CRITICAL **: 16:04:25.436: tee_jee_logging_log_error: assertion 'message != NULL' failed

** (timeshift-gtk:168624): CRITICAL **: 16:04:25.436: tee_jee_logging_log_error: assertion 'message != NULL' failed
App config saved: /etc/timeshift/timeshift.json
Creating new snapshot...(RSYNC)
Saving to device: /dev/dm-2, mounted at path: /run/timeshift/168624/backup
Syncing files with rsync...
E: AsyncTask.begin()
E: Failed to execute child process “/root/.temp/ohfItTJ6/2023-08-04_16-04-25/script.sh” (No such file or directory)
Terminatedmplete (??? remaining)
```
### My assumption
Maybe the problem is with dbus? I don't know anything about dbus, i haven't configured it on my machine. But i heard some problems with dbus on NixOS

### Notify maintainers
@ShamrockLee 
@bobby285271

### Metadata
Timeshift v22.11.2 
NixOS channel v23.05

**Comment by bobby285271** [comment]
Please test the above PR.

```
nix-build -A timeshift https://github.com/NixOS/nixpkgs/archive/dd0180e72fb2efd5b1007eb1612192ef2e95d62e.tar.gz
sudo ./result/bin/timeshift-gtk
```

**Comment by ShamrockLee** [comment]
There should probably a NixOS test or VM-based package test for its functionality. I didn't know how to write one the time when I contributed this package.

**Comment by bobby285271** [comment]
There is a NixOS test for [snapper](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/snapper.nix) for reference, I am not sure if I can look into that soon though :thinking:

**Comment by gelerum** [comment]
It works properly. Thank you for your work! I just don't understand why there wasn't open issue for this bug, because timeshift is really popular.

**Comment by ShamrockLee** [comment]
BTW, when inspecting how a NixOS test for Timeshift should be like, I notice that the PATH is hard-coded to FHS ones in the `/etc/cron.d/timeshift-hourly` crontab.

```crontab
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=""

0 * * * * root timeshift --check --scripted
```

This apparently won't work unless the user is on a FHS distro (say Debian) with FHS-installed Timeshift.

I wonder how we should change it so it works before and after updates?

**Comment by bobby285271** [comment]
> before and after updates?

Probably use stable paths like `/run/current-system/sw/bin` (did not test)?
