### ISSUE TITLE
broadcom-sta fails to build in combination with grsecurity/Pax 

### ISSUE THREAD

**Issue by tongeren** [NixOS/nixpkgs#24718]
## Issue description

While trying to build Nixos .17:03 with grsecurity/Pax support. The build fails on compiling broadcom-sta:
<code> <p>from /tmp/nix-build-broadcom-sta-6.30.223.271-4.9.20.drv-0/broadcom-sta/src/wl/sys/wl_cfg80211_hybrid.c:26:<br>
  /nix/store/y6320ln7x2fw7300ga1jdgawwdg22j9c-linux-4.9.20-dev/lib/modules/4.9.20-grsec/source/arch/x86/include/asm/string_64.h:56:7: note: expected 'void *' but argument is of type 'const struct wl_cfg80211_event_loop *' <br>
void *memset(void *s, int c, size_t n); <br>
        ^</p></code>

### Steps to reproduce

Hardware needs broadcom-sta and in configuration.nix:

nixpkgs.config.allowUnfree = true;
security.grsecurity.enable = true;

## Technical details

* System: NixOS: 17:03
* Nix version: 1.11.8
* Nixpkgs version: 17.03.899.c87abfae79

**Comment by joachifm** [comment]
Unfortunately, out-of-tree modules are apt to break with grsec, and it's not much we can do about it on our end. I think you'll have more luck reporting this upstream.

**Comment by joachifm** [comment]
If you have powerful hardware, you can experiment with disabling some of the PaX plugins (constification, &c).

**Comment by tongeren** [comment]
Thank you for the explanation. 

I tried to get nixos to build via experimenting with disabling GrSecurity and PaX settings as you mentioned, but I unfortunately I could not obtain a succesful build. Is there a way to explicitely exclude out-of-tree modules like broadcom-sta from the hardening process?

**Comment by joachifm** [comment]
Unfortunately, grsec is no longer supported.
