### ISSUE TITLE
Firefox changed the way the timeZone is returned

### ISSUE THREAD

**Issue by mawis** [NixOS/nixpkgs#247105]
### Describe the bug
Since I updated to NixOS 23.05 I noticed, that several Elm programmed sites were broken in Firefox. I finally now had the time to dig deeper in that and I found the underlying problem: The way the timezone is returned by Firefox has changed with NixOS 23.05. When running the command `Intl.DateTimeFormat().resolvedOptions().timeZone` in the Firefox console, up until NixOS 22.11 the returned value on my system was `Europe/Berlin`, but with NixOS 23.05 it's no just `CET`.

I checked with Firefox on Ubuntu, MacOS and Windows. All still return `Europe/Berlin` in the current version of Firefox, so I think the problem has been introduced by NixOS and not by Firefox.

This change breaks the (at least) the [`timezone-data`](https://package.elm-lang.org/packages/justinmimbs/timezone-data/latest/) package of the Elm ecosystem, as it is now returning a `TimeZone.error` instead of a `Time.Zone`.

BTW: chromium on NixOS is still returning the expected value of `Europe/Berlin` on my system.

### Steps To Reproduce
1. Open Firefox
2. Open the tools for web developers (Ctrl-Shift-I)
3. Execute the following expression: `Intl.DateTimeFormat().resolvedOptions().timeZone`

### Expected behavior
Firefox should return the timezone as `Europe/Berlin` as it does on other platforms and as chromium does as well.

### Screenshots

Result on NixOS 23.05/Firefox 115 is:

![grafik](https://github.com/NixOS/nixpkgs/assets/2042030/85f6efb2-0e97-45f4-a3b5-6e7261f4c432)

Result on Windows 10 is:

![grafik](https://github.com/NixOS/nixpkgs/assets/2042030/337969fd-f917-4b20-8395-2060c87508ff)

### Notify maintainers
@lovesegfault @hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.2385.48e82fe1b1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, old-22.05, unstable"`
 - channels(matthias): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
Maybe this is #238025?

**Comment by mawis** [comment]
Thanks @bobby285271 

I first thought it's different, as I do get a timezone (and not UTC). But setting the TZ environment variable fixed my problem as well, so I guess it's a duplicate. Thanks for pointing out.
