### ISSUE TITLE
Package request: lanraragi

### ISSUE THREAD

**Issue by aicynide** [NixOS/nixpkgs#247103]
**Project description**

**Metadata**

* homepage URL: https://lrr.tvc-16.science/
* source URL: https://github.com/Difegue/LANraragi
* license: mit
* platforms: unix, linux, darwin

**Comment by TomaSajt** [comment]
It looks like I got it working. I will try to make a PR in the near future.

**Comment by TomaSajt** [comment]
Oh, sorry, kind of forgot about this.

About the progress:
I needed to add quite a few new perl packages to nixpkgs
I couldn't yet figure out how to get `Sys::CpuAffinity` working, so in the meantime I will be hardcoding `getNumCpus` to 1.
I will try to post the PR this weekend
