### ISSUE TITLE
nix-shell cannot coerce a set to a string

### ISSUE THREAD

**Issue by husnoo** [NixOS/nixpkgs#24726]
## Issue description
error:
```
$ nix-shell
error: cannot coerce a set to a string, at /home/nawal/data/analysis/default.nix:1:6
```
default.nix:
```
with import {};

python.buildEnv.override {
    extraLibs = [ pkgs.pythonPackages.pyramid ];
    ignoreCollisions = true;
}
```
this follows the documentation here: http://nixpkgs.readthedocs.io/en/latest/reference-guide/python.html

## Technical details
```
$ nixos-version 
17.03.git.1f1de8d (Gorilla)
$ nix-env --version
nix-env (Nix) 1.11.8
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.git.1f1de8d2e0M"
```

**Comment by FRidh** [comment]
Those are old, outdated docs. I've removed them but it seems to take some time before they're actually taken offline.

Please see the Nixpkgs manual instead
https://nixos.org/nixpkgs/manual/

Furthermore, read the examples carefully. The expression you refer to is for when its used with `nix-build`. When you want to use `nix-shell`, you need to add a little bit more:
```
with import {};

(python.buildEnv.override {
    extraLibs = [ pkgs.pythonPackages.pyramid ];
    ignoreCollisions = true;
}).env
```

**Comment by husnoo** [comment]
Brilliant thank you :-)
