### ISSUE TITLE
Failing nixops deployment when using `boot.initrd.network.ssh`

### ISSUE THREAD

**Issue by mbrgm** [NixOS/nixpkgs#24727]
I filed this here and not in the nixops repo, as the commit introducing the problem is in nixpkgs.

## Steps to reproduce

Using nixpkgs on 0a6a06346a, nixops from the same nixpkgs tree.

1. Create a nixops machine definition including a section for
   `boot.initrd.network.ssh`.
2. In that section, set the hostRSAKey to point to a raw (unquoted) path:
   ```
   boot.initrd.network.ssh = {
     enable = true;
     hostRSAKey = /some/path/to/a/key;
     ...
   };
   ```
3. `nixops deploy`

## Expected behavior

nixops deploys the definition successfully.

## Observed behavior

The deployment fails with the following errors:

```
$ nixops deploy
building all machine configurations...
host1> copying closure...
testdeployment> closures copied successfully
host1> cp: cannot stat '/some/path/to/a/key': No such file or directory
host1> Traceback (most recent call last):
host1>   File "/nix/store/nx0kav7cj0qy9s3hw0dvyb32rj94nrr5-systemd-boot-builder.py", line 149, in <module>
host1>     main()
host1>   File "/nix/store/nx0kav7cj0qy9s3hw0dvyb32rj94nrr5-systemd-boot-builder.py", line 144, in main
host1>     write_entry(gen, machine_id)
host1>   File "/nix/store/nx0kav7cj0qy9s3hw0dvyb32rj94nrr5-systemd-boot-builder.py", line 52, in write_entry
host1>     subprocess.check_call([append_initrd_secrets, "/boot%s" % (initrd)])
host1>   File "/nix/store/jmh1011sv7fwa9c3zgqgqgvvnz4nixkx-python3-3.5.3/lib/python3.5/subprocess.py", line 271, in check_call
host1>     raise CalledProcessError(retcode, cmd)
host1> subprocess.CalledProcessError: Command '['/nix/store/aii12czb6238vfi65pakwnch3lh9dqfw-append-initrd-secrets/bin/append-initrd-secrets', '/boot/efi/nixos/7i91ak3l5x049bp9wj0vl2xfl5mgkrkv-initrd-initrd.efi']' returned non-zero exit status 1
host1> error: unable to activate new configuration
error: activation of 1 of 1 machines failed (namely on ‘host1’)
```

## Interpretation

Instead of copying the key (defined with a raw path) from the orchestrating host to the target machine, the script on the target machine tries to copy that key from within its own filesystem. As the file does not exist there, this is not possible. 59c0977300..3a26d09e15 introduced a way to avoid storing the keys world-readable in the nix store. However, this only seems to work when the key points to a local path.

## Possible solutions

I disussed those solutions with @shlevy, who introduced the initrd secret facility, on IRC.

* ~~Store the key in a nixops `deployment.keys` key, then point the `hostRSAKey` value to the `/run/keys/...` path.~~ --> `deployment.keys.<name>.text` can   only contain data, which is representable as a nix string. However, dropbear's privkey format is binary data.
* ~~Use a base64 encoded version of the key for a `deployment.keys` key, then decode and use on the target.~~ --> not possible as there's no way to decode in between.
* ~~Set `boot.loader.supportsInitrdSecrets = lib.mkForce false;`.~~ --> Activation script will still try to copy the key.
* Make nixops transfer the key to the target machine, but store it outside of the nix store. Then copy from there and remove the data from the target machine. Seems complicated, too specific and "not quite right".
* Allow supplying a standard openssh private key for `hostRSAKey` etc. (this could be checked) and if the privkey is in OpenSSH format, dropbearconvert it on the target machine before copying. This would eliminate having to figure out that the privkey is in a different format from OpenSSH, which can be confusing at first.
* Allow `deployment.keys` to handle binary data. This seems like a simple solution, but I don't know if it can be done.

I'd be happy to hear your thoughts on this.

**Comment by mbrgm** [comment]
Currently, the only working solution for me was to revert b09490a3229dd5ac4169248ee38ca22e357c0aa2.

**Comment by mbrgm** [comment]
@shlevy Any news on this?

**Comment by shlevy** [comment]
The right solution here is to have `deployment.keys` handle binary data. I haven't worked on it, though.

**Comment by ejpcmac** [comment]
Hi! I’ve just hit this issue during a NixOS 19.03 install from the installation media (not using NixOps). The script building the `initrd` keeped saying the file did not exist, where I would `cat` it by just copy-pasting the “missing” path. Not sure it has the exact same cause, but the error message is the very same.
