### ISSUE TITLE
services.mysqlBackup don't work with default settings

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#24728]
## Issue description

the backup files get created but are empty.

### Steps to reproduce

1. configure mysqlBackup

```
  services.mysqlBackup = {
    enable = true;
    databases = [ "mysql" "piwik" "satzgenerator" ];
    location = "/var/backup/mysql";
    period = "0 4 * * *";
    singleTransaction = true;
  };
```

2. wait one day
3. see created archives

```
[root@atomic:~]# ll /var/backup/mysql/
insgesamt 12
-rw-r--r-- 1 mysql mysql 20  7. Apr 04:00 mysql.gz
-rw-r--r-- 1 mysql mysql 20  7. Apr 04:00 piwik.gz
-rw-r--r-- 1 mysql mysql 20  7. Apr 04:00 satzgenerator.gz
```

4. display content: `zcat /var/backup/mysql/mysql.gz` (nothing)

running the cron command manually (as root) works.

`/nix/store/d2bkgmfk8q1ak2iz17bw5bk08gq8k44v-mariadb-10.1.21/bin/mysqldump --single-transaction mysql | /nix/store/w1vlvxlavmz39by5xpnhva36q2lbi9hf-gzip-1.8/bin/gzip -c > test.gz`

i can't log in as user mysql, so maybe that is the problem?

```
[root@atomic:~]# su - mysql
This account is currently not available.
```

/cc @rbvermaa (creator of module)

## Technical details

* System: NixOS 17.03.902.536d3cac2e (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.902.536d3cac2e
* MySQL is actually MariaDB 10.1.21

**Comment by davidak** [comment]
OK, this is something:

mysqldump: Got error: 1045: "Access denied for user 'mysql'@'localhost' (using password: NO)" when trying to connect

**Comment by Mic92** [comment]
The code is from 2009 and I do not see, where a password is set. It also uses cron instead of systemd timer. I suppose it needs a major overhaul.

**Comment by davidak** [comment]
The `mysql` user has no home directory, so i can't place a `.my.cnf` there.

So i just changed the `user = "root";`

@Mic92 is there a practical reason to use systemd timers over cronjobs? Or just to migrate every aspect of the system to systemd?

**Comment by Mic92** [comment]
timer have the following advantages:

- no extra daemon
- systemctl list-timer shows you when timer will be started the next time/when they were triggered
- you can easily inspect the log output and the exit status of the last run of the service using `systemctl status <service>`
- you do not have to care about what your command write to stdout/stderr, because systemd won't send you an email
- you can also trigger jobs manually for testing
- way more option how the service should be executed (ressource-control, permissions etc)
- for machines, which are not always on there is an option to run the service after boot if a run was missed.
- (the cronjob timespec is hard to remember)

**Comment by davidak** [comment]
It works now after my change yesterday.

@Mic92 that are some nice to have features, thanks!

>systemd won't send you an email

i like to get notified when something goes wrong.

So to resolve this issue:

1. the module needs to get rewritten with systemd timers
2. it should work out of the box (or tell how mysql permissions need to be set)

**Comment by Mic92** [comment]
You can still get emails as described [here](https://wiki.archlinux.org/index.php/Systemd/Timers#MAILTO). The defaults here are also saner, since no email is send, if the program has any output to stdout,

**Comment by florianjacob** [comment]
A nice way to solve the user login problem would be to use [unix socket authentication](https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/), I think, which would not need a password or a `my.cnf` file then.

One could have a special `backup` unix user, that is authenticated via socket authentication, and then allowed to read all databases for dumping them, with SQL commands like this:
```
INSTALL PLUGIN unix_socket SONAME 'auth_socket';                                                                                                                                        

CREATE USER 'backup'@'localhost' IDENTIFIED VIA unix_socket;
GRANT  SELECT, LOCK TABLES ON *.* TO 'backup'@'localhost';
```

Maybe I'll find the time some day to create a proper fix for this.
