### ISSUE TITLE
Package request: pricehist

### ISSUE THREAD

**Issue by chrpinedo** [NixOS/nixpkgs#247241]
**Project description**

A command-line tool for fetching and formatting historical price data, with support for multiple data sources and output formats. 
It is a price fetcher for accounting tools already packaged such as ledger-cli, hledger and beancount.

**Metadata**

* homepage URL: https://gitlab.com/chrisberkhout/pricehist
* source URL: https://gitlab.com/chrisberkhout/pricehist
* license: mit
* platforms: unix, linux, darwin, ...

It is a python CLI application built with poetry. I tried to use poetry2nix but I am totally new to nix and I was incapable of doing it.

**Comment by WolfangAukang** [comment]
@chrpinedo I was able to package it:

- First you will need `curlify`:
```
> cat pkgs/development/python-modules/curlify/default.nix
{ buildPythonPackage, fetchFromGitHub, requests }:

buildPythonPackage {
  pname = "curlify";
  version = "unstable-2019-07-19";
  format = "setuptools";

  src = fetchFromGitHub {
    owner = "ofw";
    repo = "curlify";
    rev = "b914625b12f9b05c39f305b47ebd0d1f061af24d";
    hash = "sha256-yDHmH35TtQDJB0na1V98RtBuVHX5TmKC72hzzs1DQK8=";
  };

  propagatedBuildInputs = [
    requests
  ];
}
```
- Then, you can build `pricehist`:
```
> cat pkgs/tools/misc/pricehist/default.nix
{ buildPythonApplication
, fetchFromGitLab
, requests
, lxml
, cssselect
, curlify
, poetry-core
}:

buildPythonApplication rec {
  pname = "pricehist";
  version = "1.4.5";
  format = "pyproject";

  src = fetchFromGitLab {
    owner = "chrisberkhout";
    repo = "pricehist";
    rev = version;
    hash = "sha256-sCad5lQqkW6mZlI/0+DFSj9FleCOyBLJG264RrtqByA=";
  };

  propagatedBuildInputs = [
    requests
    lxml
    cssselect
    curlify
    poetry-core
  ];
}
```

I was able to get their example working:
```
> ./result/bin/pricehist fetch ecb EUR/AUD -s 2023-08-15 -e 2023-08-22
date,base,quote,amount,source,type
2023-08-15,EUR,AUD,1.6888,ecb,reference
2023-08-16,EUR,AUD,1.6895,ecb,reference
2023-08-17,EUR,AUD,1.6931,ecb,reference
2023-08-18,EUR,AUD,1.6999,ecb,reference
2023-08-21,EUR,AUD,1.6995,ecb,reference
2023-08-22,EUR,AUD,1.6878,ecb,reference
```

Let me know if you want to maintain it.

**Comment by chrpinedo** [comment]
Thanks  @WolfangAukang ! I am quite new with nix packages, but I could provide PR when there are new versions since I use this package usually.

**Comment by WolfangAukang** [comment]
I want to avoid adding myself as a maintainer, so I will make it available at [NUR](https://github.com/nix-community/nur).

**Comment by WolfangAukang** [comment]
Package has been merged
