### ISSUE TITLE
pinentry-mac build is impure when it probably doesn't need to be

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24734]
It goes out of its way to ask for /usr/bin/xcodebuild, which is why it never builds on Hydra. Now that we have `xcbuild`, it seems like that should work, but when I tried to add `xcbuild` to `buildInputs`, I got the following error:

```
building path(s) ‘/nix/store/qcygffsy5pinslpm0j7yrvc8zkjhc09w-pinentry-mac-0.9.4’
unpacking sources
unpacking source archive /nix/store/6h56fvzy42wh7nqma3bzrg5w2rl22689-v0.9.4.tar.gz
source root is pinentry-mac-0.9.4
setting SOURCE_DATE_EPOCH to timestamp 1435839525 of file pinentry-mac-0.9.4/pinentry-mac.xcodeproj/project.pbxproj
patching sources
configuring
no configure script, doing nothing
building
running xcodebuild
error: unable to find product type com.apple.product-type.application
error: couldn't create target environment for pinentry-mac
Build settings from the command line:
    DERIVED_DATA_DIR=.
    OTHER_CFLAGS=-F/nix/store/4jmvgz8jdvnarmgl9xqxm4w46nh49r2q-CF-osx-10.9.5/Library/Frameworks -isystem /nix/store/fmqyqyjf0q9jj1abc4vlzqwsaw32q9s1-libc++-4.0.0/include
    OTHER_CPLUSPLUSFLAGS=-F/nix/store/4jmvgz8jdvnarmgl9xqxm4w46nh49r2q-CF-osx-10.9.5/Library/Frameworks -isystem /nix/store/fmqyqyjf0q9jj1abc4vlzqwsaw32q9s1-libc++-4.0.0/include
    OTHER_LDFLAGS=-rpath /nix/store/qcygffsy5pinslpm0j7yrvc8zkjhc09w-pinentry-mac-0.9.4/lib  -L/nix/store/fmqyqyjf0q9jj1abc4vlzqwsaw32q9s1-libc++-4.0.0/lib
    SDKROOT=macosx10.10

=== BUILD TARGET pinentry-mac OF PROJECT pinentry-mac WITH THE DEFAULT CONFIGURATION (Release) ===

builder for ‘/nix/store/lv15067wjbz257jvpy0qmrhaww13raqg-pinentry-mac-0.9.4.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ak6wakwijj0lf3smmf5imm7l66nwmb8a-gnupg-2.0.30.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ak6wakwijj0lf3smmf5imm7l66nwmb8a-gnupg-2.0.30.drv’ failed
```

@matthewbauer do you know what's up with the missing product type `com.apple.product-type.application`?

**Comment by matthewbauer** [comment]
We need to add a definition to xcbuild/platform.nix. I don't think I've ever gotten it working but you can use this for example: 6558864bce696f556b50ce8ac46bd1ef3938b5f4. It's been a while since I've looked at it, but something didn't work right when I setup pinentry.

**Comment by copumpkin** [comment]
Ah, it wants ibtool

**Comment by copumpkin** [comment]
\*hack\* \*hack\* \*hack\*

**Comment by matthewbauer** [comment]
Do you have any ideas? Only thing I can find that could work is: [https://github.com/davidquesada/ibtool/](davidquesada/ibtool).

**Comment by copumpkin** [comment]
Not really any ideas yet. I was hoping the CLTools would contain it but it doesn't. Do you have a sense of what functionality `xcbuild` uses from `ibtool`?

**Comment by matthewbauer** [comment]
I think it's mainly to compile the .xib files into .nibs. It's definitely not trivial functionality anyway. Would it be possible to make like a wrapper of ```/usr/bin/ibtool```?

**Comment by matthewbauer** [comment]
Here's a wip branch for setting up ibtool:

https://github.com/NixOS/nixpkgs/compare/master...matthewbauer:ibtool
