### ISSUE TITLE
kakoune connection breaks due changed TMPDIR inside nix-shell

### ISSUE THREAD

**Issue by tripokey** [NixOS/nixpkgs#24738]
## Issue description

kakoune fails to create new splits when run inside a nix-shell.

kakoune uses the TMPDIR environment variable when deciding where to create its session sockets and nix-shell changes TMPDIR rendering it unable to find the session socket to connect to after creating a new tmux split. 

### Steps to reproduce

```
$ tmux
$ nix-shell -p hello
$ kak
```
While in kakoune type :new and press <CR>.

## Technical details

* System: 17.03.902.536d3cac2e (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.902.536d3cac2e"

**Comment by Mic92** [comment]
Workaround set `TMPDIR` to `export TMPDIR=/run/user/$(id -u)` in your shell. `/tmp/` is currently not a tmpfs, which `/run/user/<uid>` is.

**Comment by Mic92** [comment]
Actually I don't know why they are different historically. Probably `/run/user/` is better shielded against interference of other user.

**Comment by tripokey** [comment]
Thanks!

Considering that TMPDIR might differ for tmux and kakoune regardless of wether NixOS is used or not I filed an issue for this in the kakoune repository:
https://github.com/mawww/kakoune/issues/1319
