### ISSUE TITLE
TLP gives warnings on 17.03

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#24737]
## Issue description

Hi @abbradar 
TLP shows the following in `tlp stat` output:
```
Notice: systemd-rfkill@.service is not masked -- invoke "systemctl mask systemd-rfkill@.service" to correct this!
Notice: systemd-rfkill.service is not masked -- invoke "systemctl mask systemd-rfkill.service" to correct this!
```
Anything to do with it?
Thanks.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by joachifm** [comment]
I believe the tlp module could be made to set `enable = false` for those systemd units

**Comment by abbradar** [comment]
Fixed, thanks for your report!
