### ISSUE TITLE
Documentation: Specilisation Old Generation Boot Entries

### ISSUE THREAD

**Issue by sagar-chandarana** [NixOS/nixpkgs#247507]
## Problem

NixOS specialisations are supposed to have their own entries in the Grub menu for previous generations according to the [nixos wiki page](https://nixos.wiki/wiki/Specialisation#Boot_entries). However in practice that is not the case. The older generations do not hold any boot entry for the specialisations, but only the default entry.

nixpkgs: `nixos-23.05`

## Proposal

I am not sure, whether to update the wiki to correctly mention current behavior, or whether to fix the grub module to generate entries for specialisations for older generations.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

**Comment by samueldr** [comment]
Fixed by #245739.
