### ISSUE TITLE
nzbget config WebDir contains garbage collectable path

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#24769]
## Issue description
Ran garbage collection this morning. Later I noticed that the nzbget webinterface only returns a 404 error.
nzbget.conf contains
`WebDir=/nix/store/aj6qgqyxaw2ggb31fi37shackxipzsxh-nzbget-17.0-r1686/share/nzbget/webui`
which no longer exists (and apparently is from an old version)

### Steps to reproduce
* enable nzbget service
* wait until new version is available
* update system
* garbage collect
* try to access nzbget webinterface

### notes
This can probably fixed by extending the preStart script at (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nzbget.nix#L59) to configure a fallback.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by fadenb** [comment]
I believe this was fixed in #30943 but I do no longer use it so I can not tell for sure.
I'll close the issue for now.
