### ISSUE TITLE
Zig 0.11 incompatible with zigHook build flags

### ISSUE THREAD

**Issue by booniepepper** [NixOS/nixpkgs#247696]
Using `zigHook` sets some build flags:

https://github.com/NixOS/nixpkgs/blob/aa255c2790130a72342c5fa183527fe044ca0404/pkgs/development/compilers/zig/setup-hook.sh#L23

But in Zig 0.11, `-Drelease-safe=true` is not valid, and the replacement would be `-Doptimize=ReleaseSafe`

I'm not yet enough of a Nix wizard to know exactly how to override this, or how to fix it.

It looks like there has been much discussion on this already:

https://github.com/NixOS/nixpkgs/blob/aa255c2790130a72342c5fa183527fe044ca0404/pkgs/development/compilers/zig/setup-hook.sh#L3C1-L21C70

**Comment by booniepepper** [comment]
Not sure the best person to notify, so... cc @AndersonTorres who seemed to be working on the introduction of Zig 0.11 in https://github.com/NixOS/nixpkgs/issues/247069

**Comment by AndersonTorres** [comment]
Are you using the latest release of Nixpkgs? Because the script is different, and it should set the flags according to version.

**Comment by booniepepper** [comment]
Apologies in advance if I'm doing something silly or weird.

I'm trying to develop against the master branch of nixpkgs to introduce a new tool:

https://github.com/booniepepper/nixpkgs/tree/init/dt

https://github.com/booniepepper/nixpkgs/commit/f7f6b0052990ff4d8568b59ed4c495848dc388b4

**Comment by AndersonTorres** [comment]
Sorry, I was reviewing a recent code. Indeed the change didn't land on Master branch yet.

**Comment by AndersonTorres** [comment]
Update: I merged the new code now.
Please update your master branch and update this issue accordingly.

**Comment by booniepepper** [comment]
Obrigado! It was fixed in 6acf0bf645f8826940bc7aca9efd46fbdae69eae
