### ISSUE TITLE
Update request: python3Packages.qiskit 0.41.1 → 0.44.1

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#247718]
- Package name: python3Packages.qiskit
- Latest released version: [0.44.1](https://qiskit.org/documentation/release_notes.html#qiskit-0-44-1)
- Current version on the unstable channel: 0.41.1
- Current version on the stable/release channel: 0.41.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@drewrisinger @pandaman

Last updated by @mweinelt 

**Additional information**
The installation of `qiskit` is currently failing because the dependency `qiskit-terra` is marked as broken.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by evilmav** [comment]
The segfault causing brokenness of `qiskit-terra` tests seems to be related to `openblas` conflict between `scipy`/`numpy` and `symengine->flint`. The latter seems to be building an own version and if this is loaded prior to the `scipy` call it ends up failing. Using something like
```nix
(symengine.override {
  symengine=pkgs.symengine.override{
    pkgs.flint.override{
      withBlas = false;
    };
  };
})
```

in qiskit-terra's `buildInputs` seems to fix the issue as a workaround, although I am not sure why the difference is there in the first place. @drewrisinger

**Comment by raspher** [comment]
Current version on the unstable channel: 0.45.1
Current version on the stable/release channel: 0.41.1

**Comment by kilianar** [comment]
@raspher, thank you for highlighting that `qiskit` has been updated in nixpkgs. However, attempting to install `qiskit` still results in an error, because the dependency `qiskit-aer` is currently marked as broken.
