### ISSUE TITLE
Segfault using nmtui

### ISSUE THREAD

**Issue by ThibaultRiviere** [NixOS/nixpkgs#24774]
## Issue description

Segfault using ```nmtui```
kernel: nmtui[4819]: segfault at 0 ip 00007f9cf6a7dc3a sp 00007ffdd40a4158 error 4 in libc-2.23.so[7f9cf69f1000+194000]

## Technical details

* System: (NixOS)
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: (17.09pre105258.01a8de97eb)

**Comment by abbradar** [comment]
I can't reproduce that on current master (7f8202bf839e150b3824dbbcba585725a076bed2), nor on . Can you try to run it from there (with `nix-build`)?

**Comment by ThibaultRiviere** [comment]
I did and now it's ok. I guess we can close this one.
