### ISSUE TITLE
Package request: hyprload

### ISSUE THREAD

**Issue by Kazuto** [NixOS/nixpkgs#247740]
**Project description**

A [Hyprland](https://github.com/hyprwm/Hyprland) plugin manager

**Metadata**

* homepage URL: https://github.com/Duckonaut/hyprload
* source URL: https://github.com/Duckonaut/hyprload
* license: none
* platforms: linux

**Comment by fufexan** [comment]
Hyprload is superseded by the builtin `hyprpm`, or by the HM option `hyprland.plugins`.
