### ISSUE TITLE
Update request: picom-next unstable-2023-01-29 → unstable-2023-08-03

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#247765]
- Package name: picom-next
- Latest released version: regrettably, v10.2 (released December 2022) is _still_ the latest upstream release

- Current version on the unstable channel: unstable-2023-01-29
- Current version on the stable/release channel: unstable-2023-01-29

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

There's at least one bugfix since the start of the year that would be nice to have: https://github.com/yshui/picom/issues/1096

**Notify maintainers**

@ertes @twey @thiagokokada @GKasparov

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by thiagokokada** [comment]
@sersorrel Can you help reviewing it? https://github.com/NixOS/nixpkgs/pull/247992

**Comment by sersorrel** [comment]
Apologies for not testing this for you, I couldn't immediately work out how to do so. I've now opened #248390 to hopefully make it a little easier next time.
