### ISSUE TITLE
Build failure: llvmPackages_rocm.llvm

### ISSUE THREAD

**Issue by Dox5** [NixOS/nixpkgs#247801]
### Steps To Reproduce

Steps to reproduce the behaviour:
I have been unable to build the `llvmPackages_rocm.llvm` package against in any of these ways, all failing with the same issue:

1. `nix build -L --rebuild .#llvmPackages_rocm.llvm`
2. `nix-build  --verbose --check -A llvmPackages_rocm.llvm .`
3. `nix develop --ignore-environment .#llvmPackages_rocm.llvm`
    4. Then following the build flow: `unpackPhase` -> `cd source/llvm` -> `patchPhase` -> `cmakeConfigurePhase` -> `ninjaBuildPhase` -> `ninjaCheckPhase`

### Build log
Full build log here: https://gist.github.com/Dox5/da5a85062ae166cf863dbefacd140cae

Section with failure:
```
rocm-llvm-llvm> --
rocm-llvm-llvm> Exit Code: 1
rocm-llvm-llvm> Command Output (stderr):
rocm-llvm-llvm> --
rocm-llvm-llvm> ls: cannot access '/tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/test/Other/ChangePrinters/DotCfg/Output/print-changed-dot-cfg.ll.tmp/*.pdf': No such file or directory
rocm-llvm-llvm> Expected 4 lines, got 1.
rocm-llvm-llvm> --
rocm-llvm-llvm> ********************
rocm-llvm-llvm> Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
rocm-llvm-llvm> ********************
rocm-llvm-llvm> Failed Tests (1):
rocm-llvm-llvm>   LLVM :: Other/ChangePrinters/DotCfg/print-changed-dot-cfg.ll
rocm-llvm-llvm> Testing Time: 120.23s
rocm-llvm-llvm>   Skipped          :    58
rocm-llvm-llvm>   Unsupported      : 18604
rocm-llvm-llvm>   Passed           : 30522
rocm-llvm-llvm>   Expectedly Failed:    70
rocm-llvm-llvm>   Failed           :     1
rocm-llvm-llvm> 1 warning(s) in tests
rocm-llvm-llvm> FAILED: CMakeFiles/check-all /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/CMakeFiles/check-all
rocm-llvm-llvm> cd /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build && /nix/store/a5k7x5mn7i7rcji4n99mwiqhmgjdzxmk-python3-3.10.12/bin/python3.10 /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/./bin/llvm-lit -sv /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/utils/lit /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/test
rocm-llvm-llvm> ninja: build stopped: subcommand failed.
error: builder for '/nix/store/gfjjxbpp41ljb43pzg4shjva5yi5nqry-rocm-llvm-llvm-5.4.4.drv' failed with exit code 1;
       last 10 log lines:
       >   Skipped          :    58
       >   Unsupported      : 18604
       >   Passed           : 30522
       >   Expectedly Failed:    70
       >   Failed           :     1
       >
       > 1 warning(s) in tests
       > FAILED: CMakeFiles/check-all /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/CMakeFiles/check-all
       > cd /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build && /nix/store/a5k7x5mn7i7rcji4n99mwiqhmgjdzxmk-python3-3.10.12/bin/python3.10 /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/./bin/llvm-lit -sv /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/utils/lit /tmp/nix-build-rocm-llvm-llvm-5.4.4.drv-0/source/llvm/build/test
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/gfjjxbpp41ljb43pzg4shjva5yi5nqry-rocm-llvm-llvm-5.4.4.drv'.
```

### Additional context

I'm relatively new to Nix, so if apologies if I have done something silly! I am very confused as to why I cannot build this package, given that [this hydra build](https://hydra.nixos.org/build/228623581/nixlog/1)  has succeeded and I can indeed download this built version off of cache.nixos.org. A cursory check of the hashes for one of the builds I tried indicates that I should be trying to build the exact same package?

I am having to build this package as the openai-triton package tweaks some LLVM parameters and that build doesn't appear to be in the cache, I've chased this issue back to the simplest form - trying to build `llvmPackages_rocm.llvm`

I have tried the build against 23.05 (4ecab3273592f27479a583fb6d975d4aba3486fe) and master (eb746c3fcda) and get the same issue with both nixpkgs revisions.

I _have_ managed to build this package using `nix develop .#llvmPackages_rocm.llvm` and following the build flow. I eventually tracked this down to [llvm using external programs](https://github.com/llvm/llvm-project/blob/bddaa35177861545fc329123e55b6a3b34549507/llvm/lib/Support/GraphWriter.cpp#L268) to create the PDF that the test is looking for, which are not included in the build environment but i do happen to have installed on my system. I don't understand how the hydra build succeeded with this missing dependency though!

I am running Nix on debian testing, using the debian package for nix

### Notify maintainers

@acowley @lovesegfault @Madouura @Flakebi 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.0-1-amd64, Debian GNU/Linux, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(james): `"nixpkgs-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/james/channels/nixpkgs`
```

**Comment by kirillrdy** [comment]
greetings !

It looks like your nix is not configured to have sandbox build enabled, without sandbox builds are happening on /tmp and it's possible in your set something about /tmp ( I am guessing at this point ) is not right

in general its encouraged to have sandbox enabled 
https://nixos.org/manual/nixpkgs/stable/#submitting-changes-tested-with-sandbox

give this a try

**Comment by Dox5** [comment]
Ah, thank you! I've got it building now :)

I uninstalled and reinstalled nix using the installation script (rather than the debian packages I was previously using) which seems to have done the trick as that now works with sandboxing turned on.

Closing as this is resolved now

**Comment by jljusten** [comment]
Since the debian nix package version `2.17.1+dfsg-1` (12 Oct 2023), sandbox mode can be enabled, and think it should fix this llvm build error.
