### ISSUE TITLE
Emacs creates native-lisp directories unconditionally

### ISSUE THREAD

**Issue by tmuehlbacher** [NixOS/nixpkgs#247804]
### Describe the bug

Emacs will try to create a directory structure like
`share/emacs/native-lisp/29.1-ef7c54ae/` for every path in
`$NIX_PROFILES`. This seems to be because of the code in
`pkgs/applications/editors/emacs/site-start.el`.

On NixOS, the `NIX_PROFILES` environment variable may contain invalid
paths, for example `~/.nix-profile` may not exist. This causes Emacs to
create the full directory structure for that path. This also causes
issues if Nix afterwards wants to create `~/.nix-profile` as a symlink
but it already exists as a directory.

### Steps To Reproduce

```console
$ for i in $NIX_PROFILES; do file $i; done
/run/current-system/sw: symbolic link to /nix/store/d2p2vm19a44pf51c4pcjcw8p9hliv6x4-system-path
/nix/var/nix/profiles/default: symbolic link to /nix/var/nix/profiles/per-user/root/profile
/etc/profiles/per-user/tom: symbolic link to /etc/static/profiles/per-user/tom
/home/tom/.nix-profile: cannot open `/home/tom/.nix-profile' (No such file or directory)

$ emacs
C-x C-e

$ for i in $NIX_PROFILES; do file $i; done
/run/current-system/sw: symbolic link to /nix/store/d2p2vm19a44pf51c4pcjcw8p9hliv6x4-system-path
/nix/var/nix/profiles/default: symbolic link to /nix/var/nix/profiles/per-user/root/profile
/etc/profiles/per-user/tom: symbolic link to /etc/static/profiles/per-user/tom
/home/tom/.nix-profile: directory
```

### Expected behavior

The code in `site-start.el` should filter `NIX_PROFILES` down to only
paths that already exist.

### Additional context

Ideally, `NIX_PROFILES` would only include paths that exist in the first
place, but this is not the case. #241518 also seems related.

### Notify maintainers

@AndersonTorres
@adisbladis
@atemu
@jwiegley
@lovek323
@matthewbauer

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20230807.5a8e924`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

**Comment by Gerg-L** [comment]
> Ideally, NIX_PROFILES would only include paths that exist in the first
place, but this is not the case. https://github.com/NixOS/nixpkgs/pull/241518 also seems related.

This isn't really possible with the current handling of nix_path see this comment: https://github.com/NixOS/nixpkgs/pull/241518#issuecomment-1641782032

**Comment by tmuehlbacher** [comment]
> This isn't really possible with the current handling of NIX_PROFILES see this comment: [#241518 (comment)](https://github.com/NixOS/nixpkgs/pull/241518#issuecomment-1641782032)

:+1:  yes, I hope it didn't sound like I feel antagonistic to your PR, I really hope that it lands because I do enjoy a clean `$HOME`. :smile: I more wanted to show that my proposed solution is necessary because invalid paths in `NIX_PROFILES` are pretty much inevitable.

**Comment by jian-lin** [comment]
I cannot reproduce it.

Steps:
```
> echo $NIX_PROFILES
/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/me /home/me/.nix-profile

> rm -f ~/.nix-profile

> nix run github:NixOS/nixpkgs/ce5e4a6ef2e59d89a971bc434ca8ca222b9c7f5e#emacs29 -- -q --init-directory=/tmp/init-dir

> # exit Emacs

> file ~/.nix-profile
/home/me/.nix-profile: cannot open `/home/me/.nix-profile' (No such file or directory)
```

BTW, the value of `native-comp-eln-load-path` is `("/tmp/init-dir/eln-cache/" "/nix/store/hash-emacs-29.1-rc1/lib/emacs/29.1/native-lisp/")`, which indicates another bug: adding NIX_PROFILES to `native-comp-eln-load-path` in [site-start.el](https://github.com/NixOS/nixpkgs/blob/8a390e0210770ca386ed49a251a13b9e52776b79/pkgs/applications/editors/emacs/site-start.el#L39-L46) does not take effect.

**Comment by jian-lin** [comment]
> BTW, the value of native-comp-eln-load-path is ("/tmp/init-dir/eln-cache/" "/nix/store/hash-emacs-29.1-rc1/lib/emacs/29.1/native-lisp/"), which indicates another bug: adding NIX_PROFILES to native-comp-eln-load-path in [site-start.el](https://github.com/NixOS/nixpkgs/blob/8a390e0210770ca386ed49a251a13b9e52776b79/pkgs/applications/editors/emacs/site-start.el#L39-L46) does not take effect.

The bug I mention only happens in Emacs 29.

I can reproduce your issue in Emacs 28.

https://github.com/NixOS/nixpkgs/pull/251529 fixes this issue.

**Comment by tmuehlbacher** [comment]
> I cannot reproduce it.

I'm sorry, I should have done more testing to isolate the issue. I tested out which of my packages is the culprit and the issue goes away if i remove this from my `init.el`:

```elisp
(use-package ido-completing-read+
  :config
  (ido-ubiquitous-mode))
```

Maybe it has something to do with the `ido-completing-read+` dependency `memoize`? (I am unfortunately not proficient enough with elisp to really be able to figure it out.)
