### ISSUE TITLE
Please package patchwork

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#24784]
## Issue description

I'm not a npm/js/node/whatever guy, so I cannot do this, but I really would love to have this packaged for nixpkgs: https://github.com/ssbc/patchwork. Can someone please do that?

**Comment by bjornfor** [comment]
Oh, I thought you meant http://jk.ozlabs.org/projects/patchwork/ :-)

**Comment by c0bw3b** [comment]
#61530
