### ISSUE TITLE
Can't boot with kernel 6.1.43

### ISSUE THREAD

**Issue by rhogenson** [NixOS/nixpkgs#247942]
### Describe the bug
After upgrading my system to kernel 6.1.43, it won't boot. When I press the power button, the monitor turns on to show the POST screen, then the OS starts showing some diagnostic messages. Normally, the next thing to happen would be the graphics drivers would be loaded, and the monitor resolution would increase. Instead, the monitor turns off, and the system appears to enter a crashed state, and it does not respond to the power button. I needed to hold the power button down to get the machine to turn back off.

### Steps To Reproduce
1. Press the power button
2. Monitor turns off and system enters a crashed state

### Expected behavior
NixOS boots normally

### Additional context
Selecting a rollback entry from the boot manager allows me to boot normally to kernel 6.1.42. Upgrading the kernel to version 6.4.8 with `boot.kernelPackages = pkgs.linuxPackages_latest` also allows me to boot normally. There's something broken between 6.1.43 and 6.4.8.

I'm using Wayland with the river compositor (a wl-roots based compositor)

My PC has a Radeon 7900 XT graphics card. This wouldn't be the first time I had difficulties with drivers for this card.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

This is the output from the system after upgrading to kernel 6.4.8. I wasn't able to capture output from the broken system, since I wasn't able to get it to boot.

```console
[I] [06:36] rose@alissa ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11pre511168.5a8e9243812b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mastermindaxe** [comment]
I think I had the same problem. I was trying to update my system and it always hung at initializing amdgpu and then went to a black screen.

As you mentioned I just added the line
```
boot.kernelPackages = pkgs.linuxPackages_latest
```
and it booted up fine. Tried playing a game and basic stuff and it seems to work great!
Was looking all over this repo for this. Thank you!

**Comment by rbozan** [comment]
I have the same problem.

**Comment by rhogenson** [comment]
closing as obsolete
