### ISSUE TITLE
Lemmy Caddy Config broken (does not serve static files)

### ISSUE THREAD

**Issue by Freakmiko** [NixOS/nixpkgs#247978]
### Describe the bug
When trying to run a Lemmy instance with caddy enabled, the site is completely broken due to the caddy config not properly handling the requests to the static files for the lemmy-ui.

### Steps To Reproduce
On unstable nixpkgs as of today.
```
  services.lemmy = {
    enable = true;
    database.createLocally = true;
    settings = { hostname = "localhost"; };
    caddy.enable = true;
  };
```

### Expected behavior
The served lemmy site should not be broken. Calls such as  `http://localhost/static/undefined/js/client.js` should work.
The site works with `nginx.enable = true` as expected.

### Screenshots
This is what happens with the current caddy handling
![image](https://github.com/NixOS/nixpkgs/assets/2048635/98925909-2479-40ca-82c4-3864eaffa68c)

This is what should happen
![image](https://github.com/NixOS/nixpkgs/assets/2048635/64e9f773-12f9-48c4-9d30-980ba6e0629a)

### Additional context
I temporarily ""fixed"" this to produce the second screenshot by modifying the following line: https://github.com/NixOS/nixpkgs/blob/5a8e9243812ba528000995b294292d3b5e120947/nixos/modules/services/web-apps/lemmy.nix#L159
to 
```
handle_path /static/undefined/* {
```
However, I'm not sure if this is the proper fix for this.

### Notify maintainers
@happysalada

**Comment by happysalada** [comment]
Looking at the nginx configuration, they just pass through everything that is not a json request to the ui to serve.
How about something like
```
            handle_path /static/* /static/undefined/* {
              root * ${cfg.ui.package}/dist
              file_server
            }
```

we can add missing paths to the end of this if you find any others.

**Comment by Freakmiko** [comment]
I'm not very well versed with caddy config so I don't know if this can be handled in a better way. It looks like `handle_path` can only handle a single argument and thus multiple paths like this don't work unless you copy the whole block again.

**Comment by happysalada** [comment]
you're right, I had a look at the docs, and indeed, this needs a new block
https://caddyserver.com/docs/caddyfile/directives/handle_path
(handle_path is just handle with `uri strip /prefix`)
Would you mind making a PR to add the other block ?
(no worries if you are busy or unavailable, just let me know).

**Comment by Freakmiko** [comment]
Sorry for the delay, I've added the pull request.
