### ISSUE TITLE
Update request: jacktrip 1.5.3 → 1.10.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#247933]
- Package name: jacktrip
- Latest released version: 1.10.1

Release: https://github.com/jacktrip/jacktrip/releases/tag/v1.10.1

- Current version on the unstable channel: 1.5.3
- Current version on the stable/release channel: 1.5.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

CC @iwanb 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by iwanb** [comment]
I tried updating to 1.10.1, but compilation fails with this error:
```
...
qmake5 found: YES (/nix/store/dg22lkxp1jfcyw1i971zlydi87w837ad-qtbase-5.15.9-dev/bin/qmake) 5.15.9
Could not find: Core Qt5Core in /nix/store/dg22lkxp1jfcyw1i971zlydi87w837ad-qtbase-5.15.9-dev/lib
Run-time dependency qt5 (modules: Core, Gui, Network, NetworkAuth, Qml, Quick, QuickControls2, Svg, WebSockets, Widgets) found: NO (tried pkgconfig and config-tool)

meson.build:178:12: ERROR: Dependency "qt5" not found, tried pkgconfig and config-tool
```

Even though Qt5Core is defined here: `/nix/store/dg22lkxp1jfcyw1i971zlydi87w837ad-qtbase-5.15.9-dev/lib/pkgconfig/Qt5Core.pc`.

I'm not really familiar with those build tools, so not sure how to further debug this.

The change is here: https://github.com/iwanb/nixpkgs/commit/00520caf1d8a41eb95fdc4ec40493675d384fd7f

**Comment by ntonnaett** [comment]
I don't know much about Nix, but usually pkgconfig has one directory to collect all pc files. If Qt's pc files are not in that default path you have to add that directory to the PKG_CONFIG_PATH env variable or add it to the meson configuration. Something like:

```bash
meson setup builddir
cd builddir
meson configure -Dpkg_config_path=/nix/store/dg22lkxp1jfcyw1i971zlydi87w837ad-qtbase-5.15.9-dev/lib/pkgconfig
```
