### ISSUE TITLE
`code tunnel` doesn't work since update to VS Code 1.81.0

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#247921]
### Describe the bug
`code tunnel` doesn't work anymore due to a missing binary in the VS Code package. I do not yet know whether it is an upstream issue or not.

### Steps To Reproduce
1. `NIXPKGS_ALLOW_UNFREE=1 nix shell --impure nixpkgs#vscode-fhs` (FHS required for vscode-server to work properly, because it downloads arbitrary binaries)
2. `code tunnel`
3. Observe `ENOENT` error due to a missing file

### Expected behavior
`code tunnel` runs successfully 

### Screenshots
n/a

### Additional context
Bisection revealed 754c7b7c0261225b9581cb7464394e1b52c92410 as the commit introducing the bug.

### Notify maintainers
 - @K900 as author of the commit revealed by bisection
 - @eadwu @Synthetica9 @maxeaubrey @bobby285271 @Enzime as maintainers

**Comment by K900** [comment]
Huh. There is no `code-tunnel` anywhere in the official distribution.

**Comment by K900** [comment]
Oh great it's just broken upstream: https://github.com/microsoft/vscode/issues/189383

**Comment by vikanezrimaya** [comment]
Oh well. I thought this could be an upstream issue, and turns out it indeed was.

**Comment by fpletz** [comment]
Fixed by #248438.
