### ISSUE TITLE
Cannot use a different xdg desktop portal with hyprland

### ISSUE THREAD

**Issue by fazo96** [NixOS/nixpkgs#247952]
### Describe the bug
Setting `programs.hyprland.portalPackage` to a pkg that isn't `xdg-desktop-portal-hyprland` causes the following error when applying the Nixos configuration:

```
error: function 'anonymous lambda' called with unexpected argument 'hyprland-share-picker'
```

This seems to be caused by this override: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/hyprland.nix#L9-L13

### Steps To Reproduce

Set the following in your Nixos Configuration, using the unstable channel:

```nix
programs.hyprland = {
  enable = true;   
  portalPackage = pkgs.xdg-desktop-portal-wlr;
};
```

### Expected behavior

The specified package, `xdg-desktop-portal-wlr`, is used as xdg portal and the nixos configuration switch completes successfully.

### Additional context

I looked into doing this because the default portal for hyprland does not work anymore with screen sharing a window or region, and only works with a full screen. This stopped working when I switched from 23.05 to unstable. [I reported this issue upstream](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/74) but I am unable to use a different portal due to this Nix issue.

I guess it would also be good to understand if that screen share problem is a Nix problem and not an upstream one.

### Notify maintainers

I think @fufexan maintains hyperland on Nix.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.43, NixOS, 23.11 (Tapir), 23.11pre511168.5a8e9243812b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - channels(fazo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fufexan** [comment]
`programs.hyprland.portalPackage` exists so that users can override `xdp-hyprland` from Nixpkgs with the one from [the flake](https://github.com/hyprwm/xdg-desktop-portal-hyprland). It's not supposed to be used to change the actual program, like replacing `xdp-hyprland` with `xdp-wlr`.

Also, using `xdp-wlr` instead would not help you either, since it only allows fullscreen sharing. Window and region sharing were added only by `xdp-hyprland`.

In any case, I'll look into the issue.

**Comment by fufexan** [comment]
Fix ready in #247008.

**Comment by tmarkov** [comment]
I'm still getting the error `function 'anonymous lambda' called with unexpected argument 'hyprland-share-picker'` when trying to use `xdg-desktop-portal-wlr`, on latest unstable (rev. b12803b6d90e2e583429bb79b859ca53c348b39a).

**Comment by fufexan** [comment]
> It's not supposed to be used to change the actual program, like replacing `xdp-hyprland` with `xdp-wlr`.
