### ISSUE TITLE
Package request: leptosfmt

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#248032]
**Project description**

A formatter for the leptos `view!` macro. Leptos is a Rust wasm framework.

**Metadata**

* homepage URL: https://github.com/bram209/leptosfmt
* source URL: https://github.com/bram209/leptosfmt
* license: mit, apache
* platforms: unix, linux, darwin, ...

**Comment by srid** [comment]
Note to contributors: It should be possible package this similar to https://github.com/NixOS/nixpkgs/pull/244487

**Comment by figsoda** [comment]
#248148
