### ISSUE TITLE
`NIXPKGS_ALLOW_UNFREE` doesn't work with `nix shell`

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#248037]
### Describe the bug
`NIXPKGS_ALLOW_UNFREE` doesn't work with `nix shell`.

### Steps To Reproduce
All of the below doesn't work:
```bash
nix shell nixpkgs#gpu-screen-recorder-gtk

NIXPKGS_ALLOW_UNFREE=1 nix shell nixpkgs#gpu-screen-recorder-gtk

export NIXPKGS_ALLOW_UNFREE=1
nix shell nixpkgs#gpu-screen-recorder-gtk
```

### Expected behavior
The package should install.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.20230726.f3fbbc3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/7gfqnq3bgpyfl8xv80r3wbzqkyv4bwc1-source`
```

**Comment by bobby285271** [comment]
Have you tried passing `--impure` as suggested in error message?

https://github.com/NixOS/nixpkgs/blob/43b03482680169dab7ed2f60f370fb23178cbd78/pkgs/stdenv/generic/check-meta.nix#L155-L157

**Comment by musjj** [comment]
Ah, thanks I missed that line.
