### ISSUE TITLE
Zig Issue Tracking

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#248016]
Some issues arose around Nixpkgs and Zig: cross-compilation, reproducibility, code refactoring etc.

## Links

https://github.com/NixOS/nixpkgs/pull/247714

https://github.com/NixOS/nixpkgs/issues/247719

https://github.com/NixOS/nixpkgs/pull/247437

https://github.com/NixOS/nixpkgs/issues/224266

https://github.com/NixOS/nixpkgs/issues/185665

https://github.com/NixOS/nixpkgs/issues/214356

**Comment by AndersonTorres** [comment]
Now the most important issue is cross-compilation, especially how to set variables and commandline flags to guarrantee the correct flags are being set.

This is a bit problematic because, basically, there is no "API" to help this.

**Comment by uninsane** [comment]
in case it helps anyone generalize cross compilation, here's an overlay i've been using for `mepo` the past few weeks (x86_64 build, aarch64 host):
```nix
  mepo = (super.mepo.override {
    # nixpkgs mepo correctly puts `zig_0_11.hook` in nativeBuildInputs,
    # but for some reason that tries to use the host zig instead of the build zig.
    zig_0_11 = buildPackages.zig_0_11;
  }).overrideAttrs (upstream: {
    nativeBuildInputs = upstream.nativeBuildInputs ++ [
      # zig hardcodes the /lib/ld-linux.so interpreter which breaks nix dynamic linking.
      # this shouldn't have to be buildPackages.autoPatchelfHook...
      # but without specifying `buildPackages` the host coreutils ends up on the builder's path and breaks things
      buildPackages.autoPatchelfHook

      # zig hard-codes `pkg-config` inside lib/std/build.zig
      (buildPackages.writeShellScriptBin "pkg-config" ''
        exec $PKG_CONFIG $@
      '')
    ];
    
    # somehow the `-isystem` paths are subtly different, not sure if zig issue, SDL quirk, or weirdness in my pkg-config hack
    postPatch = (upstream.postPatch or "") + ''
      substituteInPlace src/sdlshim.zig \
        --replace 'cInclude("SDL2/SDL2_gfxPrimitives.h")' 'cInclude("SDL2_gfxPrimitives.h")' \
        --replace 'cInclude("SDL2/SDL_image.h")' 'cInclude("SDL_image.h")' \
        --replace 'cInclude("SDL2/SDL_ttf.h")' 'cInclude("SDL_ttf.h")'
      substituteInPlace build.zig \
        --replace 'step.linkSystemLibrary("curl")' 'step.linkSystemLibrary("libcurl")' \
        --replace 'exe.install();' 'exe.install(); if (true) { return; } // skip tests when cross compiling'
    '';
    
    zigBuildFlags = [ "-Dtarget=aarch64-linux-gnu" ];
    dontUseZigCheck = true;
    # skip the mepo -docman self-documenting invocation
    postInstall = ''
      install -d $out/share/man/man1
    '';
  });
```

super hacky, but that overlay's worked for zig 0.9, 0.10 and 0.11 (mepo 1.1.0, 1.1.2, 1.2.0 respectively) so it's not particularly volatile. zig isn't my expertise, but i'm happy to try ideas, lend eyes or do testing for any PRs that let me shrink this overlay 😉 feels like if the pkg-config hacks could be removed, the rest could be cleaned up enough to meet nixpkgs quality.

**Comment by AndersonTorres** [comment]
I believe it should be interesting to write a setup hook for cross compilation.

**Comment by figsoda** [comment]
I think we should try to use the same setup hook, just make it work for cross compilation

**Comment by AndersonTorres** [comment]
If the idea is to reuse the current one, it will require at least some form of platform detection, possibly mapping the platform description of Nixpkgs to a set of obscure Zig flags.

Also, I have no idea how that splicing beast works. When I created `waf.hook`, it broke cross compilation, and the fixup was  a ridiculous `wafHook =  waf.hook`.
What if the current `zig_0_x.hook` is not spliceable?

Since then I joined the anti-splicing party. But it is a story for another day.

**Comment by figsoda** [comment]
> If the idea is to reuse the current one, it will require at least some form of platform detection, possibly mapping the platform description of Nixpkgs to a set of obscure Zig flags.

This sounds like what I was expecting, I think rust is also doing something similar with environment variables.

> What if the current `zig_0_x.hook` is not spliceable?

I hope it is, having a matrix of flattened attributes just feels bad and tedious.
