### ISSUE TITLE
gitea: using remote postgres server does not work

### ISSUE THREAD

**Issue by voidzero** [NixOS/nixpkgs#248009]
### Describe the bug

I've installed a gitea server with the following settings among other things, which I expected would use my remotely configured postgresql server. However, the database.host setting seems to be ignored and has installed a local postgresql server instead, and gitea is using that instead of using the remote server.

Maybe there is something else that needs to be set before I can use the remote server, but it is unclear to me what that should be.

Settings:

```
services.gitea = {
  enable = true;
  appName = "Toot toot Gitea";
  database = {
    host = "postgresql.localdomain";
    type = "postgres";
    passwordFile = config.age.secrets.giteadbpw.path;
  };
  stateDir = "/keep/gitea";
  settings = {
    database = {
      LOG_SQL = false;
    };

```

### Notify maintainers

🍀 @srhb @Ma27 @theHedgehog0 🍀 

Much thanks,
-voidzero

**Comment by theHedgehog0** [comment]
You have not disabled creating a local database instance, which can be done by setting `services.gitea.database.createDatabase` to `false`. Please add this to your configuration and retry!

**Comment by voidzero** [comment]
Ahh, that works. Fantastic. Thanks!
