### ISSUE TITLE
openvpn/networkmanager: dbus message rejected errors on connect

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#24806]
## Issue description
Trying to set up an OpenVPN connection using the NetworkManager gui (in plasma5, but in theory it should be the same as in gnome, right?), and connections are failing immediately after a successful connection with the following error messages in syslog:

```
dbus[2381]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.129" (uid=217 pid=22761 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ") interface="org.freedesktop.NetworkManager.VPN.Plugin" member="SetConfig" error name="(unset)" requested_reply="0" destination=":1.124" (uid=0 pid=22461 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ")
dbus[2381]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.129" (uid=217 pid=22761 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ") interface="org.freedesktop.NetworkManager.VPN.Plugin" member="SetIp4Config" error name="(unset)" requested_reply="0" destination=":1.124" (uid=0 pid=22461 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ")
dbus[2381]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.129" (uid=217 pid=22761 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ") interface="org.freedesktop.NetworkManager.VPN.Plugin" member="SetIp6Config" error name="(unset)" requested_reply="0" destination=":1.124" (uid=0 pid=22461 comm="/nix/store/57gfjpm4mb689p0ih6jv90l3rnjclhna-Networ")
nm-openvpn[22464]: Initialization Sequence Completed
nm-openvpn[22464]: Connection reset, restarting [0]
```

Then the connection starts again and it repeats forever.

## Technical details

* System: 17.03 at 12a39478fd79ee514a76e593f40345f319d9f5a1
* Nix version: 1.11.8
* Nixpkgs version: 17.03pre 12a39478fd79ee514a76e593f40345f319d9f5a1

**Comment by benley** [comment]
Does the nm-openvpn user need to be added to the `networkmanager` unix group for this to work?

**Comment by benley** [comment]
The connection reset in my log snippet may actually be caused by https://github.com/NixOS/nixpkgs/issues/24808 but I suspect that the dbus rejected sends are still a problem.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by benley** [comment]
I don't think I have encountered this bug for quite a while, but I also haven't been using OpenVPN recently.  Are you still seeing the same error messages?

**Comment by mmahut** [comment]
I did not, just doing triage. I'm going to close this, but feel free to reopen it if it surfaces again.
