### ISSUE TITLE
`julia`, `libgit2-glib` (and therefore `gitg`) broken by `libgit2` upgrade

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#24807]
## Issue description

`libgit2-glibg` depends on `libgit2-0.24.X`. b4c7979363f52ccc0f71823f3bcd2c8e9e7b52c3 upgrades this to `libgit2-0.25.1`, which breaks `libgit2-glib`.  While that could be upgraded to an unstable version, that, in turn, breaks `gitg`.

### Steps to reproduce

Attempt to build `gitg` at HEAD.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by FRidh** [comment]
Looks like you need to upgrade to https://github.com/GNOME/libgit2-glib/releases/tag/v0.25.0

**Comment by mdorman** [comment]
I had assumed, though perhaps I'm incorrect in that, that `libgit2-glib` follows the "even version == stable" numbering system that the rest of gnome does.  So yes, 0.25 was what I was referring to as unstable.

Similarly, the only version of `gitg` that works with `libgit2-glib-0.25` is _definitely_ an unstable version, and my attempt to just pull in a patch or two didn't work.

**Comment by mdorman** [comment]
This also breaks `julia`:

```
Exception running test libgit2 :
On worker 3:
LoadError: ReadOnlyMemoryError()
while loading /tmp/nix-build-julia-0.5.0.drv-0/julia-0.5.0/test/libgit2.jl, in expression starting on line 130
ERROR: LoadError: Some tests exited with errors.
 in (::##11#19)() at /tmp/nix-build-julia-0.5.0.drv-0/julia-0.5.0/test/runtests.jl:72
 in cd(::##11#19, ::String) at ./file.jl:59
while loading /tmp/nix-build-julia-0.5.0.drv-0/julia-0.5.0/test/runtests.jl, in expression starting on line 26
make[1]: *** [Makefile:12: all] Error 1
make[1]: Leaving directory '/tmp/nix-build-julia-0.5.0.drv-0/julia-0.5.0/test'
make: *** [Makefile:575: testall] Error 2
builder for ‘/nix/store/s68vjaiwv2mcfkns5hsr6wzpfxrm04p4-julia-0.5.0.drv’ failed with exit code 2
error: build of ‘/nix/store/s68vjaiwv2mcfkns5hsr6wzpfxrm04p4-julia-0.5.0.drv’ failed
nix-env failed with error code 100.
```

**Comment by mdorman** [comment]
@fpletz It seems to me like, given the number of things this broke, that this should be reverted.

**Comment by Mic92** [comment]
julia also needs an update to 0.5.1. libgit2-glib is fixed.

**Comment by fpletz** [comment]
Fixed on master.
