### ISSUE TITLE
Documentation: Improve section on how to use Quicklisp/ASDF/other library manager for `lisp-modules`

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#248132]
## Problem
 I feel like the documentation isn't helping a lot on how I can use `quickload`, `asdf:load-system` or any other alternative library/packaging solution. 

I've been trying to figure out how to use [`lisp-modules`](https://nixos.org/manual/nixpkgs/stable/#lisp) to create a [Nix package](https://github.com/Ashvith10/nixpkgs/tree/add-lem-to-nixpkgs) - the project I'm trying to nix-ify is [`lem`](https://github.com/lem-project/lem).

[This](lem-project/lem#890) issue should give an insight on what problem I'm dealing with - it's about the package `QL`. Alternatively, I've also tried replacing `quickload` with `asdf:load-system`, but then, it complains about the package `ASDF` missing.

The three packages that I'm in need of:
- `quick-patch`
- `lem-ncurses`
- `lem-sdl2`

## Proposal
\-

## Checklist
- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Ping maintainers
@Uthar 
@7c6f434c

**Comment by Uthar** [comment]
Hi Ashvith10 - lisp-modules doesn't use Quicklisp or ASDF's `~/common-lisp` - instead, all systems are in the Nix store. You can discover what systems are packaged in `nix repl`: 

```
nix-repl> :l <nixpkgs>
nix-repl> builtins.attrNames sbcl.pkgs
``` 

Then, you can build a wrapper like this: 

```
nix-repl> :b sbcl.withPackages (ps: [ ps.alexandria ps.bordeaux-threads ])
```

Then, you can load the systems like this:

```
$ /nix/store/abc...-sbcl-with-packages/bin/sbcl
* (load (sb-ext:posix-getenv "ASDF"))
* (asdf:load-system 'alexandria)
* (asdf:load-system 'bordeaux-threads)
```

Notice that ASDF is `load`'ed directly instead of using `(require 'asdf)` - this is to ensure the same version of ASDF is used on run time as was used on build time.

`sbcl.pkgs.quick-patch` seems to already exist - I don't know if that's the version that you need?. `lem-ncurses` and `lem-sdl2` are not packaged yet.

I'm not familiar with Lem build system but looks like we have to package a bunch of extensions

For examples of how to package, see [packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/lisp-modules/packages.nix). You can start with `pname`, `version`, `src` and `systems` and work your way through the errors.

**Comment by Ashvith10** [comment]
@Uthar thanks for answer. However, looks like I'm in the wrong here - I should have updated my progress and the misinformation in the top post. `lem-ncurses` and `lem-sdl2` are the packages we're trying to make. The first one is the text editor for terminal, and the second one offers an interface using SDL. The issue right now is when I try to run the build script, it fails because QL does not exist:
```console
NIXPKGS_ALLOW_UNFREE=1 nix-build ~/Desktop/nixpkgs/ -A lem
this derivation will be built:
  /nix/store/4953l3j2q6xny16aa2ciwcgdhwllyqlb-lem-2.1.0.drv
building '/nix/store/4953l3j2q6xny16aa2ciwcgdhwllyqlb-lem-2.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/1l32gh6cdg0817gnhdzyjv81hinglicy-lem
source root is lem
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
This is SBCL 2.3.7.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
While evaluating the form starting at line 1, column 0
  of #P"/build/lem/scripts/patch-build-ncurses.lisp":

debugger invoked on a SB-C::INPUT-ERROR-IN-LOAD in thread
#<THREAD tid=35 "main thread" RUNNING {1001098003}>:
  READ error during LOAD:

    Package QL does not exist.

      Line: 1, Column: 13, File-Position: 12

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /build/lem/scripts/patch.lisp" {10010EB113}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT   ] Abort loading file "/build/lem/scripts/patch.lisp".
  1: [RETRY   ] Retry EVAL of current toplevel form.
  2: [CONTINUE] Ignore error and continue loading file "/build/lem/scripts/patch-build-ncurses.lisp".
  3:            Abort loading file "/build/lem/scripts/patch-build-ncurses.lisp".
  4:            Ignore runtime option --load "scripts/patch-build-ncurses.lisp".
  5:            Skip rest of --eval and --load options.
  6:            Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10010EC0A3}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /build/lem/scripts/patch.lisp" {10010EB113}>)
0] 

debugger invoked on a SB-C::INPUT-ERROR-IN-LOAD in thread
#<THREAD tid=35 "main thread" RUNNING {1001098003}>:
  READ error during LOAD:

    Package QL does not exist.

      Line: 3, Column: 13, File-Position: 41

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /build/lem/scripts/patch-build-ncurses.lisp" {10010E9303}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT   ] Abort loading file "/build/lem/scripts/patch-build-ncurses.lisp".
  1: [CONTINUE] Ignore runtime option --load "scripts/patch-build-ncurses.lisp".
  2:            Skip rest of --eval and --load options.
  3:            Skip to toplevel READ/EVAL/PRINT loop.
  4: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10010EF413}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /build/lem/scripts/patch-build-ncurses.lisp" {10010E9303}>)
0] 
* @nix { "action": "setPhase", "phase": "installPhase" }
installing
TODO: Install phase jobs...
post-installation fixup
error: builder for '/nix/store/4953l3j2q6xny16aa2ciwcgdhwllyqlb-lem-2.1.0.drv' failed to produce output path for output 'out' at '/nix/store/4953l3j2q6xny16aa2ciwcgdhwllyqlb-lem-2.1.0.drv.chroot/nix/store/j0w36vr2as8kfq18da52sw78bz6rszy3-lem-2.1.0'
```

As you can see here:

https://github.com/NixOS/nixpkgs/commit/3580e652c4f5f5ef9d0dd55bffdc9a6cb77438b5#diff-747ef7569291a19b3bf100b11871e130bd1b1457e6cbc430f5deff0acc1a8f4cR32-R35

```nix
  sbcl' = pkgs.sbcl.withPackages (ps: with ps; [
    quick-patch
    external-program
    log4cl    // Reason mentioned
    esrap    // below for adding them
    cl-charms
  ]);

  nativeBuildInputs = [ sbcl' ];

  buildPhase = ''
    ${sbcl'}/bin/sbcl \
    --load scripts/patch-build-ncurses.lisp
  '';
```

This is the file we're trying to run to build:

https://github.com/lem-project/lem/blob/df71cf266e5cd0bcb64cb73ccd6201212f67b23c/scripts/patch-build-ncurses.lisp#L1-L7

which is trying to run this file:

https://github.com/lem-project/lem/blob/df71cf266e5cd0bcb64cb73ccd6201212f67b23c/scripts/patch.lisp#L1-L10

Since we didn't need this (because the very packages were updated to the same commit in nixpkgs as mentioned here in the patch), I got rid of it in my personal copy of the project, added them through the Nix packages.

Now, here's where the problem starts:

https://github.com/lem-project/lem/blob/df71cf266e5cd0bcb64cb73ccd6201212f67b23c/scripts/patch-build-ncurses.lisp#L3

and

https://github.com/lem-project/lem/blob/df71cf266e5cd0bcb64cb73ccd6201212f67b23c/scripts/patch-build-sdl2.lisp#L3

Since ql:quickload isn't working, it fails here. These "packages" are in the root of the repo, and I'm not able to figure out how to add them.

**Comment by Uthar** [comment]
We could try to avoid this build script, and use asdf:load-system instead. 

There were two other places with references to QL, I patched them out.

To add Lem, we can do something like this : https://github.com/Uthar/nixpkgs/commit/7c51d8ed0f015303a4cc3a58b8929600a2bcf8cd

For now I'm running it like this:

```
$ NIX_PATH=nixpkgs=https://github.com/uthar/nixpkgs/archive/lem.tar.gz nix-shell -p 'sbcl.withPackages (ps: [ ps.lem-ncurses ])'
$ sbcl
* (load (sb-ext:posix-getenv "ASDF"))
* (asdf:load-system 'lem-ncurses)
* (lem:main)
```

There is some warning about missing font, I skip it with space.

I need some help packaging the extensions, it's a lot of work

**Comment by Ashvith10** [comment]
@Uthar let's not discuss more about `lem` here, it's my bad that I didn't create a separate issue. I'll create one shortly under "package request" and tag you there. This was with regards to improving the documentation, especially in cases like this, where instructions from [this section](https://nixos.org/manual/nixpkgs/stable/#lisp-importing-packages-from-quicklisp) isn't clear, and we might want to improve on this.

**Comment by Ashvith10** [comment]
With regards to the first few improvement I can think of is:

https://github.com/NixOS/nixpkgs/blob/044b56eb42730951627bbb7369bc7b2278207dec/doc/languages-frameworks/lisp.section.md?plain=1#L40-L48

In the above snippet, the symlink `result` is missing.

and

https://github.com/NixOS/nixpkgs/blob/044b56eb42730951627bbb7369bc7b2278207dec/doc/languages-frameworks/lisp.section.md?plain=1#L74-L80

Both of them don't work, if I just type it on my console. I was however, able to figure out how to make the last one work - `cd` to `nixpkgs/pkgs/development/lisp-modules` and then run the command. There might be other such incomplete parts in the documentation that I've forgotten, because I've not touched in two weeks.

**Comment by Uthar** [comment]
thanks for catching that, I fixed those issues in commit https://github.com/NixOS/nixpkgs/pull/251006/commits/952781729fbc137349a043daf2aaa2aa0e2e023c

regarding [Importing packages from Quicklisp](https://nixos.org/manual/nixpkgs/stable/#lisp-importing-packages-from-quicklisp), I can see some further issues with it:

- It says that packages are 'imported', but doesn't say to where - perhaps we should say up front that the result of the import process is the file `imported.nix` (this is mentioned further down, but maybe should be said earlier). Maybe also say that the goal of the import process is to save people some work of writing Nix expressions by auto generating those expressions and hoping they just work - I don't remember the numbers now, but a majority of them do work.
- It mentions the untracked "packages.sqlite" file, but doesn't say that the file can be deleted at will
- It says that the maintainer should "re-run" the `ql-import.lisp` script, but doesn't explicitly say when - it's mentioned that the script pulls the latest data from Quicklisp, but maybe we should explicitly say that the script should run when there is a new Quicklisp release.

> I'm still not able to grasp why we're creating extensions and adding them in packages.nix

This seems to be an issue with the [Defining packages manually inside Nixpkgs](https://nixos.org/manual/nixpkgs/stable/#lisp-defining-packages-inside) section. In an ideal world, we just import the Quicklisp data, add native dependencies and everything works, but some packages decide to do weird stuff like creating files other than FASL during compilation. Other packages simply don't exist in Quicklisp. For these packages, we override them in `packages.nix`

> lem-ncurses and lem-sdl should only be exposed to the lem package, right?

Wchichever you prefer - though the convention so far has been to package things as one ASDF system per expression in `packages.nix`. Then apps such as StumpWM or Nyxt (or Lem) can use things from `sbcl.pkgs` as inputs. The advantage of having it in `packages.nix` is that it will appear in all supported CL implementations: `sbcl.pkgs.lem`, `ccl.pkgs.lem`, `ecl.pkgs.lem` etc. If you place it somewhere else, you don't have access to `build-asdf-system`, only to `<lisp>.buildASDFSystem`, which is specific to one CL.
