### ISSUE TITLE
pythonRelaxDepsHook fails to remove dependencies when `pythonRemoveDeps = true;`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#248185]
### Describe the bug
`pythonRelaxDepsHook` is failing to remove requirements as requested by the setting of `pythonRemoveDeps`.

### Steps To Reproduce
Attempt to build
```nix
{ buildPythonPackage
, fetchFromGitHub
, pythonRelaxDepsHook
}:

buildPythonPackage rec {
  pname = "minichain";
  version = "unstable-2023-08-09";

  src = fetchFromGitHub {
    owner = "srush";
    repo = pname;
    rev = "b79ebc51bdedb836c9265eec2fcc21cd60b17327";
    hash = "sha256-h41Cdl78u92eZVYh3wbnqGmd3BcQOB2KPlOjc8Zf45Q=";
  };

  nativeBuildInputs = [ pythonRelaxDepsHook ];

  # Neither or these work:
  # pythonRemoveDeps = [ "datasets" ];
  pythonRemoveDeps = true;
}
```

Upon building:
```
...
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/source/dist /build/source
Processing ./minichain-0.3.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement datasets (from minichain) (from versions: none)
ERROR: No matching distribution found for datasets
```

Tested on e1cf47876a2ee94302f0055892fb6e3c4433fb45. 

### Expected behavior
`pythonRelaxDepsHook` to remove the dependencies as https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pythonrelaxdepshook-using-pythonrelaxdepshook specifies.

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers
Latest committers to python-relax-deps-hook.sh: @delroth @thiagokokada @FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯   nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-153-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(samuelainsworth): `"home-manager-22.11.tar.gz, nixgl"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by FRidh** [comment]
> > Why are these names different? Why isn't the wheel named minichain-unstable-2023-08-09-*.whl?
> 
> Probably because the wheel name is based on the package metadata.
> 
> Maybe we should just ignore the version during the matching?

Yes, we should.

**Comment by thiagokokada** [comment]
Created a PR: https://github.com/NixOS/nixpkgs/pull/248516

**Comment by samuela** [comment]
Closing now that https://github.com/NixOS/nixpkgs/pull/248516 has been merged.
