### ISSUE TITLE
vscode missing libGLESv2.so, gpu accel disabled

### ISSUE THREAD

**Issue by anilanar** [NixOS/nixpkgs#248200]
### Describe the bug
With the last [PR that fixed wayland gpu acceleration for vscode](https://github.com/NixOS/nixpkgs/pull/245705), gpu acceleration broke for non-wayland.

Error code: 

```
Failed to load GLES library: /nix/store/pj28fgr2jj4wn5az6x26px6dsbgc09p7-vscodium-1.80.2.23209/lib/vscode/libGLESv2.so
```

I can confirm that I have gpu acceleration working when I pin vscode nixpkgs to https://github.com/NixOS/nixpkgs/commit/e8d56b900b2fb1d2237b5511d8a6e1d544943744 which is the parent commit of https://github.com/NixOS/nixpkgs/pull/245705.

I also tried the following, linking libglvnd's libGLESv2 into vscode directory. The error changed and terminal rendering completely broke with a black screen:

      postInstall = ''
        ln -sf ${pkgs.libglvnd}/lib/libGLESv2.so $out/lib/vscode/libGLESv2.so
      '';
    

### Steps To Reproduce
1. Start VScode with the --verbose flag, so it outputs details about the startup and other stuff
2. Notice how it complains about missing libGLESv2.so library.
3. Run code --status to see check that it's indeed using software rendering.

### Expected behavior
VSCode uses gpu acceleration.

### Additional context
See https://github.com/NixOS/nixpkgs/issues/243372

### Notify maintainers

@eadwu @Synthetica9 @maxeaubrey @bobby285271 @Enzime

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.43, NixOS, 23.05 (Stoat), 23.05.20230807.011567f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(aanar): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by S-NA** [comment]
In general when you are not loading bundled/vendor libraries, then all the libraries ideally should be loaded from the system (especially if they are related) otherwise you run into problems.

Try doing what you did in `postInstall` but also for `libEGL.so` which is provided by the `libGL` package. I think `libGL` also provides `libGLESv2.so` for that matter.

**Comment by anilanar** [comment]
Almost works. There is a different error now. `code --status` says `enabled_readback` for gpu accel instead of `disabled`.

```
[28792:0810/105035.591542:ERROR:gl_display.cc(508)] EGL Driver message (Error) eglCreateContext: EGL_BAD_MATCH error: In eglCreateContext: Failure in argument parsing
[28792:0810/105035.591691:ERROR:gl_display.cc(508)] EGL Driver message (Error) eglCreateContext: EGL_BAD_MATCH error: In eglCreateContext: Failure in argument parsing
[28792:0810/105035.591806:ERROR:gl_context_egl.cc(370)] eglCreateContext failed with error EGL_BAD_MATCH
[28792:0810/105035.591920:ERROR:gles2_command_buffer_stub.cc(336)] ContextResult::kFatalFailure: Failed to create context.
```

**Comment by anilanar** [comment]
Maybe I should go ahead and do the same for `libvulkan`, `libvk_swiftshader`, `libffmpeg` too.

**Comment by S-NA** [comment]
Try:
```
postInstall = ''
  patchelf --add-needed ${lib.getLib libglvnd}/lib/libGLESv2.so.2 $out/lib/vscode/code
'';
```

**Comment by anilanar** [comment]
It's still looking for a `/lib/vscode/libGLESv2.so` after `patchelf --add-needed` either `libGLESv2.so` or `libGLESv2.so.2`.

```
Failed to load GLES library: /nix/store/ljjryfkpg6j7a6dn8awwfh1kcrd31zs4-vscode-1.80.2/lib/vscode/libGLESv2.so: /nix/store/ljjryfkpg6j7a6dn8awwfh1kcrd31zs4-vscode-1.80.2/lib/vscode/libGLESv2.so: cannot open shared object file: No such file or directory
```

**Comment by anilanar** [comment]
Would it make sense to bring bundled `/lib/vscode/libGLESv2.so` back so that it works for everybody? Would bringing it back break https://github.com/NixOS/nixpkgs/pull/245705?

**Comment by S-NA** [comment]
I think if you have the `patchelf --add-needed` it should continue to work for Wayland, and if you remove the `rm` it should work for X11 (it seems to explicitly try to load the bundled library). If you can test that and it does actually work it is probably a good enough solution.
