### ISSUE TITLE
Terraform tests seem super flaky

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24833]
All sorts of our evaluations are getting failed terraform builds on all platforms. See for example http://hydra.nixos.org/eval/1347513?filter=terraform&compare=1347493&full=.

@zimbatm recently removed some of the tests but I don't think they're enough, since the failure above is a different set.

cc @shlevy @peterhoeg 

Those of you who have looked into the flaky tests, do you know if upstream is aware of them?

**Comment by copumpkin** [comment]
Actually, they still seem to be failing in more recent evaluations: http://hydra.nixos.org/eval/1348875?filter=terraform&compare=1348775&full=#tabs-still-fail

**Comment by copumpkin** [comment]
Looks like the current failure is handled by https://github.com/hashicorp/terraform/issues/13230

**Comment by zimbatm** [comment]
Closing as 0.11 is working fairly smoothly. terraform-0.9.11 is still a bit flakey and should be removed over time
