### ISSUE TITLE
Package request: Forgejo/Gitea Runner

### ISSUE THREAD

**Issue by MTRNord** [NixOS/nixpkgs#248353]
**Project description**
This is essentially an extension/companion of #207601

Foregejo Runner is a GitHub Actions alike CI Runner for the Forgejo Actions.
It also exists I believe for Gitea. It's an extension to forgejo essentially providing to declare a host as a runner which then
can be used inside forgejo for CI.

**Metadata**

* homepage URL: https://forgejo.org/
* source URL: https://code.forgejo.org/forgejo/runner
* license: MIT
* platforms: linux (not sure if others are supported)

**Comment by Kranzes** [comment]
We already have it packaged and we have a module for it.

![image](https://github.com/NixOS/nixpkgs/assets/56614642/3af8e295-1933-49dd-9014-d50357b3956d)
