### ISSUE TITLE
Package request: tailwindcss-language-server

### ISSUE THREAD

**Issue by gekoke** [NixOS/nixpkgs#248384]
**Project description**

[Language Server Protocol](https://github.com/Microsoft/language-server-protocol) implementation for [Tailwind CSS](https://tailwindcss.com/)

**Metadata**

* homepage URL: https://github.com/tailwindlabs/tailwindcss-intellisense
* source URL: https://github.com/tailwindlabs/tailwindcss-intellisense/tree/HEAD/packages/tailwindcss-language-server
* license: mit
* platforms: unix, linux, darwin

**Comment by pinn3** [comment]
See https://github.com/NixOS/nixpkgs/issues/200244#issuecomment-1339402133

**Comment by gekoke** [comment]
> See [#200244 (comment)](https://github.com/NixOS/nixpkgs/issues/200244#issuecomment-1339402133)

Thanks!
