### ISSUE TITLE
Package request: Whisparr

### ISSUE THREAD

**Issue by hufforguk** [NixOS/nixpkgs#248396]
**Project description**

Whisparr is an adult movie collection manager for Usenet and BitTorrent users, similar to Radarr and Sonarr

**Metadata**

* homepage URL: https://wiki.servarr.com/whisparr
* source URL: https://github.com/Whisparr/Whisparr
* license: gpl3
* platforms: linux

**Comment by paveloom** [comment]
https://github.com/NixOS/nixpkgs/pull/244172

**Comment by avinashkanaujiya** [comment]
Not visible in https://search.nixos.org/packages.

**Comment by poperigby** [comment]
@avinashkanaujiya it hasn't been merged yet.

**Comment by FliegendeWurst** [comment]
Should stay open until #244172 is merged.
