### ISSUE TITLE
anki: UI controls in the "preferences" pages are broken

### ISSUE THREAD

**Issue by euank** [NixOS/nixpkgs#248357]
### Describe the bug

The anki package has some broken UI controls in 'preferences'.
The core functionality works, but not all of the UX toggles do.

### Steps To Reproduce

Go to 'Tools -> Preferences -> Review' and try to click any of the checkboxes.

### Expected behavior

Checkboxes should check.
### Additional context

This occurs on the 2.1.65 package too: https://github.com/NixOS/nixpkgs/pull/229480

I've only tried to reproduce it on X, I'm unsure if it reproduces under wayland.

### Notify maintainers

@euank oh hey that's me

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.7, NixOS, 23.11 (Tapir), 23.11.20230802.66aedfd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`

$ anki --version
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Anki 2.1.61
```

**Comment by euank** [comment]
I had a feeling this might be a qt6 or pyqt6 issue since I believe that UX is a pyqt rendered thing.

Switching it over to pyqt5 makes those checkboxes work on my machine, and the core functionality (studying) still works. The core functionality is all rust + javascript at this point I think, with basically no QT, so it makes sense this wouldn't impact it.

I think the pragmatic thing is to package this with pyqt5 for now, and then once upstream stops supporting pyqt5, we can see if this bug is fixed, and if not properly understand it then.

**Comment by euank** [comment]
I've found an even better workaround than using qt5 for this (fyi @mohe2015, since you originally reported this).

On my machine, if I go to:

Tools -> Preferences -> Appearance (tab) -> User Interface (section) -> Style

and select the 'Style' as 'Native' instead of 'Anki' in the dropdown, then all the other preference controls also start to work.

It looks like this jbug impacts the 'Anki' style, which is the default.

Changing to the 'Native' style seems like an okay workaround for now since the style doesn't even influence that much of anki.

**Comment by antecrescent** [comment]
I stumbled upon this issue when bumping the Anki ebuild for Gentoo. In my case, PyQt6 was lacking support for the SVG image format. Compiling PyQt6 with `--enable=QtSvg --enable=QtSvgWidgets` fixed the issue.

If you unzip the compiled `aqt*.wheel` you'll find several SVG checkbox icons under `_aqt/data/qt/icons/check*.svg`.

**Comment by euank** [comment]
Thanks so much for the pointer @antecrescent, very much appreciated!

Applying the following diff locally did seem to work! Within the anki theme, checkboxes seemed to toggle just fine after that, so it seems likely that's the culprit.

```diff
--- a/pkgs/games/anki/default.nix
+++ b/pkgs/games/anki/default.nix
@@ -150,6 +150,7 @@ python3.pkgs.buildPythonApplication {

   buildInputs = [
     qt6.qtbase
+    qt6.qtsvg
   ] ++ lib.optional stdenv.isLinux qt6.qtwayland;
```

I'll open a PR shortly after clicking around a bit more and making sure all seems well with the anki theme
