### ISSUE TITLE
Update request: pnpm 8.5.1 → 8.6.x

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#248366]
- Package name: `nodePackages_latest.pnpm` or `nodePackages.pnpm`
- Latest released version: 8.6.12
- Current version on the unstable channel: 8.6.11
- Current version on the stable/release channel: 8.5.1
- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@happysalada 
@dotlambda 

Personal note: Having both `nodePackages_latest.pnpm` or `nodePackages.pnpm` doesn't make any sense in either of the branches, if they're both pointing to the same version (both are 8.5.1 in release and 8.6.11 in unstable branch).

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by happysalada** [comment]
The _latest one is built with the latest node version, while the one without is built with the lte version.
Most times they wont be that different, but the latest one breaks more often.

Im making a PR for the update.
Do you know how to make such a PR yourself if you need to in the future ?

There is a generate.sh script in the node_packages directory, running will generate the diff for you.

Let me know if anything doesnt make sense of course.

**Comment by Ashvith10** [comment]
@happysalada I know how to make PRs, have also merged some of them before, but since I've tried and failed in the process of making packages previously, I'm a little apprehensive about touching nixpkgs. Do share the particular PR number, so that I may learn from the changes, and be able to update the package in the future :smile: .

**Comment by happysalada** [comment]
the following PR https://github.com/NixOS/nixpkgs/pull/248402 which updates all the nodePakages (and _latest as well)
was created by running `./pkgs/development/node-packages/generate.sh` from the top of the nixpkgs repo.
(before running this, make sure to pull latest master).
if you ever need an update for a package, you can run this and make the PR yourself.
The program takes about an hour to run though on a modern machine with a decent connection (this is why we don't run it so often).
