### ISSUE TITLE
greetd's tuigreet needs `/var/cache/tuigreet`

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#248323]
### Describe the bug
`tuigreet` requires `/var/cache/tuigreet` in order to store persistent information about the last session and user for the `--remember*` flags.

### Steps To Reproduce

```nix
{pkgs, ... }: {
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
          command = ''
            ${pkgs.greetd.tuigreet}/bin/tuigreet \
              --sessions /run/current-system/sw/share/wayland-sessions/:/run/current-system/sw/share/xsessions/ \
              --remember \
              --remember-user-session \
              --user-menu \
              --power-shutdown /run/current-system/systemd/bin/systemctl poweroff \
              --power-reboot /run/current-system/systemd/bin/systemctl reboot
          '';
        };
    };
  };
}
```

### Expected behavior

`tuigreet` remembers the session I picked.

### Additional context
Basically the same as https://github.com/apognu/tuigreet/issues/33 .

My hotfix so far:

```nix
{... }: {
  systemd.tmpfiles.rules = [
    "d '/var/cache/tuigreet' - greeter greeter - -"
  ];
}
```

### Notify maintainers
@luc65r
@ivar

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.20230808.7828754`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by katexochen** [comment]
Pinging @queezle as greetd module maintainer.

I'm not sure about the best way to fix this. Maybe we can add `StateDirectory=tuigreet` to the systemd unit of the greed module?
