### ISSUE TITLE
Package request: @tailwindcss/language-server

### ISSUE THREAD

**Issue by kenos1** [NixOS/nixpkgs#248413]
**Project description**

Tailwind CSS Language Server

[Language Server Protocol](https://github.com/Microsoft/language-server-protocol) implementation for [Tailwind CSS](https://tailwindcss.com/), used by [Tailwind CSS IntelliSense for VS Code](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss).

**Metadata**

* homepage URL: https://www.npmjs.com/package/@tailwindcss/language-server
* source URL: https://github.com/tailwindlabs/tailwindcss-intellisense
* license: mit
* platforms: it's a node package.

**Comment by natsukium** [comment]
We already have `nodePackages."@tailwindcss/language-server"`.
Would you please try `nix shell nixpkgs#nodePackages."@tailwindcss/language-server"`?

**Comment by gepbird** [comment]
Also it was moved to a top level package in https://github.com/NixOS/nixpkgs/pull/264899
