### ISSUE TITLE
Package request: p2pool (monero)

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#248489]
**Project description**

Decentralized pool for Monero mining which fixes common issues that has more economical payouts and mitigates negative impact on monero's value such as network attacks by centralized pool admins.

**Metadata**

* homepage URL: https://p2pool.io/
* source URL: https://github.com/SChernykh/p2pool
* license: gpl3
* platforms: linux, freebsd, android, darwin, windows

**Comment by TanvirOnGH** [comment]
@Kreyren It's already available in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/p2pool/default.nix#L51

**Comment by Kreyren** [comment]
> @Kreyren It's already available in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/p2pool/default.nix#L51 -- @TanvirOnGH (https://github.com/NixOS/nixpkgs/issues/248489#issuecomment-1731543172)

Oh didn't notice it before, thanks!
