### ISSUE TITLE
Build failure: azure-cli

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#248539]
### Steps To Reproduce

1. `nix-build . -A azure-cli`

### Build log

https://gist.github.com/katexochen/738e12e2b64308fb931a91d3b811eb61

### Notify maintainers

@akechishiro
@jonringer

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.3, NixOS, 23.11 (Tapir), 23.11.20230711.f240619`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(katexochen): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/6w0n7ivwnbvfh32xw3cb0yrvdw3l4q89-source`
```

**Comment by AkechiShiro** [comment]
This should get fixed once #248187 is merged, thanks for reporting this issue.

The build is successful on the latest version, see this comment : https://github.com/NixOS/nixpkgs/pull/248187#issuecomment-1672796682

I'll close it once, the merge is done.
