### ISSUE TITLE
clickhouse: `ParquetMetadata` format is missing

### ISSUE THREAD

**Issue by edwardw** [NixOS/nixpkgs#248596]
### Describe the bug
Since version `22.4`, clickhouse adds an input format `ParquetMetadata`. One can use it to inspect the metadata of a parquet file but the current unstable nixpkgs build of clickhouse doesn't have it.

### Steps To Reproduce
1. Run the following:
```bash
> clickhouse local --query "SELECT * FROM s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/uk-house-prices/parquet/house_prices_all.parquet', ParquetMetadata)"
```
2. An error appears:
```
Code: 73. DB::Exception: Unknown format ParquetMetadata. (UNKNOWN_FORMAT)
```

### Expected behavior
If run the same command from an official build of clickhouse like so:
```bash
> curl https://clickhouse.com/ | sh
```
then it does spit out a blob of parquet metadata as expected.

### Additional context
At the time of writing this bug report, the version of nixpkgs clickhouse is `23.3.8.1`, and the official one `23.8.1.1325`:
```bash
> clickhouse local --version
```

The clickhouse conveniently has a `system.formats` table which lists all available input/output formats:
```bash
> clickhouse local --query "SELECT count() FROM system.formats"
```
The nixpkgs build reports 91 total formats, the official build 96. Among them `ParquetMetadata` and `PrettyJSONEachRow` are missing.

Judging from the output of `system.build_options` table,
```bash
> clickhouse local --query "SELECT * FROM system.build_options"
```
there ain't noticeable differences between the two builds that could lead to this bug. It puzzles me.

### Notify maintainers
@yu-re-ka @orivej

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info
copying path '/nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.44-1-lts, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(username): `"nixpkgs"`
 - nixpkgs: `/home/username/.nix-defexpr/channels/nixpkgs`
```

**Comment by yu-re-ka** [comment]
It's very simple. We are packaging the "lts" releases, while the official one you downloaded is from the "stable" releases channel.

You say this metadata format was added in version 22.4, but the "lts" release branch is still at 22.3.x.

**Comment by edwardw** [comment]
Mystery solve then. The versioning scheme of Clickhouse is misleading here, lts version `23.3.*` is actually `22.3` in term of the source code branch.

Thanks.
