### ISSUE TITLE
substitute* should fail when `--replace` fails

### ISSUE THREAD

**Issue by figsoda** [NixOS/nixpkgs#248565]
## Issue description

Currently, it only prints a warning, which can easily get hidden in the build log. A lot of the missing substitutions only fails at runtime, which can be problematic and hard to debug.

This is the logic that prints the warning, we should be able to just add a non-0 return value like `--subst-var` and `*)`:

https://github.com/NixOS/nixpkgs/blob/fb5e53615b4734ca6eaeeb54b84b8000cdae0389/pkgs/stdenv/generic/setup.sh#L848

### Steps to reproduce

```console
$ nix-shell -p
$ touch foo
$ substitute foo /dev/stdout --replace a b
substituteStream(): WARNING: pattern 'a' doesn't match anything in file 'foo'
$ echo $?
0
```

Pinging people that touched `setup.sh` recently (relatively, this file doesn't get changed much)

@Artturin @roberth @sternenseemann @trofi @ncfavier @SuperSandro2000

**Comment by trofi** [comment]
I think it's a reasonable change, but there are a few cases where globs are used to do blanket changes, like:

    pkgs/development/python-modules/remi/default.nix:    substituteInPlace test/test_*.py

I suspect those have quite a few cases when no replacement happens and migtn need some form of opt-in to restore permissive behaviour.

**Comment by ncfavier** [comment]
Those cases can be handled with `|| true`.

**Comment by trofi** [comment]
`|| true` will only work if `substituteInPlace` will not stop on the first failed file and will return status after all substitutions attempted.

**Comment by roberth** [comment]
This would be a lot less painful if we'd introduce a new flag or a new function.
I'll note that I don't like some of its variations/behavior either:
- https://github.com/NixOS/nixpkgs/issues/237216

I wouldn't be opposed to a new function, clean slate, encourage good practices.

**Comment by AndersonTorres** [comment]
No way.
I am using it in my codes for TDE.
Their old tqt3 code uses a custom ersatz autotools script, and it searches in hardcoded paths.
Worse, they ship configuration codes for a plethora of OSes, and many of them do not have identical hardcoded paths.

I can survive a warning, but not an error.

**Comment by Artturin** [comment]
I think `--fail` and `--quiet` would be good flags.

**Comment by pbsds** [comment]
Thanks for the ping, I just dusted of an old PR: #248565

**Comment by pbsds** [comment]
> I think `--fail` and `--quiet` would be good flags.

In the PR above, i opted to deprecate `--replace` in favor of `--replace-fail` `--replace-warn` and `--replace-quiet`, since a `--fail`  and `--quiet` would not affect `--subst-var` and `--subst-var`.

**Comment by Atemu** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/260776
