### ISSUE TITLE
Unable to build fortran programs that link to HDF5-fortran

### ISSUE THREAD

**Issue by nialov** [NixOS/nixpkgs#248503]
### Describe the bug
I have been trying to build a complex set of scientific libraries (if interested, see e.g. <https://github.com/nialov/nix-extra/blob/feat-package-dfnworks/overlays/packages/pflotran/default.nix>) but have gotten stuck on getting one of them to build with successful linking `hdf5-fortran`. The build fails with log messages as follows:

~~~
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: main.f90:(.text+0x773): undefined reference to `__h5f_MOD_h5fclose_f'
~~~

### Steps To Reproduce

I have isolated the problem to a simple `nix` project here:

<https://github.com/nialov/hdf5-fortran-test>

I am building a fortran example from here: <https://portal.hdfgroup.org/display/HDF5/Examples+by+API> (Read / Write to External Dataset). The code is found in the `main.f90` file in the repository. The could be truncated to e.g. just `CALL h5open_f(hdferr)` and the error would persist. I just wanted to have a known working `fortran` example so I could try to isolate the problem further. But the code logic is irrelevant as I understand.

1. `nix build github:nialov/hdf5-fortran-test#`

### Expected behavior

I expected the build to work.

### Additional context

I have tried every linking method, flags and so on that I could think of. But nothing has produced results. It is entirely possible I am missing something basic and fundamental here as I am not a `fortran` developer by any means. But I am not able to find examples in `nixpkgs` that could provide help.

### Notify maintainers

No maintainers are set for `hdf5` but I saw @Stunkymonkey to have done some recent additions. Sorry for the tag if not valid! 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, NixOS, 23.11 (Tapir), 23.11.20230712.2de8efe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/3j9garb3574mxikwbi6zn594j8mjd19s-source`

```

**Comment by xbreak** [comment]
Not a fortran dev either but this worked (using libraries from `h5fc -show`):

```diff
diff --git a/default.nix b/default.nix
index 5fc7fe0..432e2ba 100644
--- a/default.nix
+++ b/default.nix
@@ -16,7 +16,8 @@ stdenv.mkDerivation {
   # NIX_LDFLAGS = "-lhdf5 -L${hdf5-fortran.dev}/include";
   # NIX_DEBUG = 1;
   buildPhase = ''
-    gfortran -I${hdf5-fortran}/lib -I${hdf5-fortran.dev}/include -lhdf5 -o main main.f90 
+    gfortran -L${hdf5-fortran}/lib -I${hdf5-fortran.dev}/include -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lz -ldl -lm -o main main.f90
+
   '';
   # FFLAGS = [ "-std=legacy" "-fPIC" ];
   # FCFLAGS = [ "-std=legacy" "-fPIC" ];
```

**Comment by nialov** [comment]
Thank you @xbreak !!! Testing now in my more complex builds. Will close the issue if things work as expected.

**Comment by nialov** [comment]
Fix worked! Closing.

Had to meddle with the flags a bit more (<https://github.com/nialov/nix-extra/blob/52df84bcce588bf0a1f9ac1861a00e67ccac9b1f/overlays/packages/pflotran/default.nix#L17>) but eventually got it working. 

This was partly due to me also needing `mpi` support in `hdf5` which did not work from the `nixpkgs` version of `hdf5` (`fortran` and `mpi` support could not both be enabled at the same time or else it did not build correctly). I found a workaround by using `hdf5` package definition from here: <https://github.com/kilzm/lmix/blob/50f6805406d69e2f383f575a77eb13620c06d164/pkgs/HDF5/default.nix> and overriding it like so: <https://github.com/nialov/nix-extra/blob/52df84bcce588bf0a1f9ac1861a00e67ccac9b1f/overlays/default.nix#L97>.

Probably forgetting something but eventually things started working :D.
