### ISSUE TITLE
Update request: gcc13 13.1.0 → 13.2.0

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#248657]
- Package name: gcc13
- Latest released version: 13.2
- Current version on the unstable channel: 13.1
- Current version on the stable/release channel: 13.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Synthetica9 @vcunat @Ericson2314 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by vcunat** [comment]
🔮  https://github.com/NixOS/nixpkgs/pull/248552

**Comment by vcunat** [comment]
> Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

🤔 not sure where that went wrong.  https://github.com/NixOS/nixpkgs/pulls?q=gcc13+is%3Aopen

**Comment by trofi** [comment]
Ah, sorry. Somehow missed it. Closing.
