### ISSUE TITLE
Many Haskell packages depend on GHC and GCC

### ISSUE THREAD

**Issue by blucoat** [NixOS/nixpkgs#248620]
### Describe the bug
Many ordinary Haskell packages seem to depend on GHC and GCC.  This causes the closure size, even for simple haskell packges, to be huge.  For example, any program that uses the `vector` package has a closure size of, at minimum, 2.6G:

```
$ nix path-info --closure-size --human-readable nixpkgs#haskellPackages.vector
/nix/store/31l730pfbwxyzjqxsydzf4p4j5chszsl-vector-0.12.3.1	   2.6G
```

### Steps To Reproduce
Inspect the closure of your favorite Haskell package:

```
$ nix path-info --recursive nixpkgs#haskellPackages.vector | grep ghc
/nix/store/9mbrmbvi4kqshfmnki68gfrbqmn66grj-ghc-9.2.8-doc
/nix/store/706qlf8yhggnhi6lbzyk4nyf00i5vccb-ghc-9.2.8
```

### Expected behavior
Haskell packages should generally not depend on GHC and GCC.

### Additional context
The haskell.nix folks seem to have run into this issue, or a related one, in the past: <https://github.com/input-output-hk/haskell.nix/issues/829>

### Notify maintainers

@cdepillabout 
@expipiplus1 
@maralorn 
@sternenseemann 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.43, NixOS, 23.11 (Tapir), 23.11.20230808.844ffa8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cdepillabout** [comment]
Let's see why Haskell packages depend on GHC.

First, build `vector`:

```console
$ nix-build -A haskellPackages.vector
/nix/store/w48a8111pw8cwv8b1v96iqc90hxcxy3d-vector-0.13.0.0
```

Find its GHC dependency:

```console
$ nix-store --query -R /nix/store/w48a8111pw8cwv8b1v96iqc90hxcxy3d-vector-0.13.0.0 | grep -i ghc
/nix/store/9b726wmi7q8003fsxpaf5raa92s72cx5-ghc-9.4.6-doc
/nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.4.6
```

Find out file causes vector to depend on ghc:

```console
$ nix why-depends -a --precise /nix/store/w48a8111pw8cwv8b1v96iqc90hxcxy3d-vector-0.13.0.0 /nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.
4.6 | cat
/nix/store/w48a8111pw8cwv8b1v96iqc90hxcxy3d-vector-0.13.0.0
├───lib/ghc-9.4.6/package.conf.d/vector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh.conf: …th-cxx-6.2.1/lib.    /nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.4.6/lib..library-dirs-sta…
│   lib/ghc-9.4.6/x86_64-linux-ghc-9.4.6/libHSvector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh-ghc9.4.6.so: ….4.6.so.libgmp.so.10./nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.4.6/lib/ghc-9.4.6/ar
ray-0…
│   lib/ghc-9.4.6/x86_64-linux-ghc-9.4.6/vector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh/Data/Vector/Fusion/Bundle/Monadic.dyn_hi: …...................../nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-gh
c-9.4.6/lib/ghc-9.4.6/rts/inc…
│   lib/ghc-9.4.6/x86_64-linux-ghc-9.4.6/vector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh/Data/Vector/Fusion/Bundle/Monadic.hi: …...................../nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.
4.6/lib/ghc-9.4.6/rts/inc…
│   lib/ghc-9.4.6/x86_64-linux-ghc-9.4.6/vector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh/Data/Vector/Fusion/Bundle/Monadic.p_hi: …................b..../nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-
9.4.6/lib/ghc-9.4.6/rts/inc…
│   lib/ghc-9.4.6/x86_64-linux-ghc-9.4.6/vector-0.13.0.0-3W9cV5Nx58ZJW9PdUODEAh/Data/Vector/Fusion/Bundle.dyn_hi: …...................../nix/store/dbimp2biq6d8lmnwlqc2612qni37k2z0-ghc-9.4.6/
lib/ghc-9.4.6/rts/inc…
...
```

It looks like the GHC dependency is being pulled in by quite a few files, like package.conf files, shared objects, other build outputs, etc.

> Haskell packages should generally not depend on GHC

I'm somewhat surprised to hear this opinion.  Vector (and other Haskell packages) almost certainly depend on the Haskell boot libraries, which all come from the GHC derivation.  As well as using things like the RTS, which comes from GHC.

How are you imagining building packages like Vector without depending on GHC?  Maybe you're suggesting that the boot libraries, the RTS, etc should be packaged into their own derivations?  I'm not sure how easy something like that would be to do, or if it would even be possible.

-------------------------------------------------------------------------

Most users seem pretty happy with `justStaticExecutables`, which makes Haskell executables have all their Haskell dependencies statically linked.

For instance, `nix-tree` is a Haskell application built with `justStaticExecutables`:

```console
$ nix-build -A haskellPackages.nix-tree
$ ldd ./result/bin/nix-tree 
        linux-vdso.so.1 (0x00007ffde1db7000)
        libm.so.6 => /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib/libm.so.6 (0x00007ff7b50ec000)
        libncursesw.so.6 => /nix/store/1ql93amj3rmq5yg7qry7ky6gwpbvdgxp-ncurses-6.4/lib/libncursesw.so.6 (0x00007ff7b5078000)
        libgmp.so.10 => /nix/store/4mkb67p6x2d5raj6m7xnpjq3vgj4zpwd-gmp-with-cxx-6.2.1/lib/libgmp.so.10 (0x00007ff7b4fd8000)
        libc.so.6 => /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib/libc.so.6 (0x00007ff7b4df2000)
        librt.so.1 => /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib/librt.so.1 (0x00007ff7b4deb000)
        libdl.so.2 => /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib/libdl.so.2 (0x00007ff7b4de6000)
        libffi.so.8 => /nix/store/bg6dzgvw2wpg61v8a7f0x6fkm31k26hh-libffi-3.4.4/lib/libffi.so.8 (0x00007ff7b4dd9000)
        /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/lib/ld-linux-x86-64.so.2 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007ff7b5
1ce000)
$ nix path-info --closure-size --human-readable ./result
/nix/store/37pk0yb72jxmn0frm9hlil4l74vcl0qf-nix-tree-0.3.1        47.5M
```

**Comment by maralorn** [comment]
I would add that it is really not a problem for a library to depend on ghc because the only thing we use libraries for is to develop or compile with them and for that you need the compiler anyway. 

If on the other hand you want to install a binary, then you often don't want to include the compiler. For that there is justStaticExecutables or enableSeparateBinOutput which I personally prefer.

**Comment by blucoat** [comment]
Thanks for the clarification.  I think I was imagining that Haskell worked a bit like e.g. C, where the standard library is packaged separately from the compiler and dynamic libraries don't need to depend on the compiler.  I'll look into `justStaticExecutables` and `enableSeparateBinOutput`; one of them will probably satisfy my needs.

**Comment by maralorn** [comment]
I will close this issue as resolved. Feel free to reach out if there is still a problem or if you need help.
