### ISSUE TITLE
Build failure: haskellPackages.vty (cross-compiled)

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#248752]
### Steps To Reproduce

1. build `pkgsCross.armv7l-hf-multiplatform.haskellPackages.vty`

### Build log

```
[20 of 40] Compiling Graphics.Vty.Input.Classify ( src/Graphics/Vty/Input/Classify.hs, dist/build/Graphics/Vty/Input/Classify.o, dist/build/Graphics/Vty/Input/Classify.dyn_o )
[21 of 40] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, dist/build/Graphics/Vty/Input/Loop.o, dist/build/Graphics/Vty/Input/Loop.dyn_o )
ghc: Couldn't find a target code interpreter. Try with -fexternal-interpreter
```

[Full log](https://gist.githubusercontent.com/Majiir/ab9ba36360eec2a4414274a0d5cc6354/raw/18eb3b5f4049ff7580d92fbeaebba02fa081c701/jdz01hzz62fm4l7k5gn0mpxjp6jjfjbn-vty-armv7l-unknown-linux-gnueabihf-5.37.drv.log)

### Additional context

- Not sure if this affects only `armv7l` or other cross-compiled targets as well.
- `vty` is a dependency of `nix-tree`.

### Notify maintainers

@NixOS/haskell 

### Metadata

Building with nixpkgs @ fb5e53615b4734ca6eaeeb54b84b8000cdae0389 (recent `master`).

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.12, NixOS, 23.05 (Stoat), 23.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(majiir): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by sternenseemann** [comment]
Compiling `vty` evidently requires `TemplateHaskell` which requires executing host code via `-fexternal-interpreter`. This is currently not supported by the nixpkgs Haskell infrastructure in a first class way (I believe `haskell.nix` does if you are in a hurry). I've opened #248979 to track this.

**Comment by amjoseph-nixpkgs** [comment]
Yep, I got one step farther than this using `qemu-user`, but not much.  See #248979.  Don't get your hopes up.
