### ISSUE TITLE
arm64: firefox install is very slow on pre-alpha NixOS Packet 2A if you don't explicitly use --cores 96 -j 96

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixpkgs#24876]
## Issue description

Firefox build with `nix-env --install firefox` built from source is a very slow build on a fast machine, perhaps because the `make` used is not exercising all of the cores on a 96-core machine (Packet Type 2A).

### Steps to reproduce

1. Install NixOS 17.03 on Packet 2A server http://packet.net ; there are some known issues related to the server not phoning home to register, but I was able to get by them.
2. Run `nix-env --install screen htop` to get some tooling
3. Run `nix-env --install firefox` in another window
4. Watch `htop`, notice that only 1 of the 96 cores is busy during build.
5. Wait patiently for the compile to complete.

Solve by running as

```
nix-env --install firefox -j 96 --cores 96
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
[root@ed-nixos-nrt-2:~]# nixos-version
17.09.git.01a8de9 (Hummingbird)
```

* Nix version: (run `nix-env --version`)

```
[root@ed-nixos-nrt-2:~]# nix-env --version
nix-env (Nix) 1.11.8
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
[root@ed-nixos-nrt-2:~]# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09.git.01a8de9"
```

**Comment by vcunat** [comment]
Well, of course, if you don't use `--cores` or equivalent, there's no make-level parallelism.  On nixos you can e.g. set `nix.buildCores = 0;`.  The default `= 1` is perhaps questionable...

**Comment by vielmetti** [comment]
Where do I do that setting, @vcunat ? That seems like a sensible default to change on a manycore machine.

**Comment by vcunat** [comment]
@vielmetti: in your `/etc/nixos/configuration.nix` or some equivalent place in your setup.

**Comment by vielmetti** [comment]
done! thanks and closing
