### ISSUE TITLE
Package request: pymc3

### ISSUE THREAD

**Issue by kemalmao19** [NixOS/nixpkgs#248880]
**Project description**

PyMC3 is a new open source Probabilistic Programming framework written in Python that uses Theano to compute gradients via automatic differentiation as well as compile probabilistic programs on-the-fly to C for increased speed. Contrary to other Probabilistic Programming languages, PyMC3 allows model specification directly in Python code.

**Metadata**

* homepage URL: https://www.pymc.io/welcome.html
* source URL: https://github.com/pymc-devs/pymc
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by fabaff** [comment]
See https://search.nixos.org/packages?channel=unstable&show=python311Packages.pymc

**Comment by kemalmao19** [comment]
> See https://search.nixos.org/packages?channel=unstable&show=python311Packages.pymc

thanks,
