### ISSUE TITLE
Package request: waypaper

### ISSUE THREAD

**Issue by I-like-stuff** [NixOS/nixpkgs#248837]
**Project description**
GUI wallpaper setter for Wayland-based window managers

   GUI wallpaper setter for Wayland-based window managers that works as a frontend for popular backends like swaybg and swww.
  If wallpaper does not change, make sure that swaybg or swww is installed.
**Metadata**

* homepage URL: https://github.com/anufrievroman/waypaper
* source URL: https://github.com/NixOS/nixpkgs/blob/21cdec0ddcdf5a6fe991dbb98e65d80c07bd3d6b/pkgs/applications/misc/waypaper/default.nix
* license:gpl3Only
* platforms: linux

**Comment by LudovicoPiero** [comment]
It's already available in nixpkgs.
