### ISSUE TITLE
Documentation: Warn, that `nixos-install` deletes existing files under /home

### ISSUE THREAD

**Issue by lions-tech** [NixOS/nixpkgs#248896]
## Problem

I have a separate partition for my /home directory. I tried to install NixOS and therefore mounted it under /mnt/home. Then I ran `nixos-install --flake '.#MSI-PX60' --no-root-passwd`. Unfortunately all user folders were deleted and replaced by empty ones.

## Proposal

A little warning regarding this would be nice - I think a separate /home partition is a common use case and - in my experience - other Linux distributions just leave /home in peace, if it contains something.

## Checklist

- [X] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [X] checked [open documentation issues] for possible duplicates
- [X] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by RaitoBezarius** [comment]
This is certainly not what `nixos-install` does… We need more information about your problem.

**Comment by Atemu** [comment]
It smells to me like you simply didn't declare your home partition in `fileSystems`. Check `mount` whether there's actually anything mounted at `/home`.

**Comment by lions-tech** [comment]
Thank your, for the quick replies.

> This is certainly not what `nixos-install` does… We need more information about your problem.

Ok, good to know :sweat_smile: 

The disk has four partitions:
- sda1, `1024M`, `fat32` mounted at `/mnt/boot`
- sda2, `79.5G`, `ext4`  mounted at `/mnt`
- sda3, `16G`, `swap` activated with `mkswap -L swap /dev/sda3; swapon /dev/sda3`
- sda4, `369.3G`, `ext4` mounted at `/mnt/home`

`ls -laR /mnt/home` shows, the directories it contains are now empty.

> It smells to me like you simply didn't declare your home partition in `fileSystems`. Check `mount` whether there's actually anything mounted at `/home`.

My configuration is on GitHub: https://github.com/lions-tech/personal-machine-config

Anything else, you need to know?

**Comment by Atemu** [comment]
Please provide the exact steps, including any steps done before nixos-install.

If you unmount the home partition, is there anything in `/mnt/home`?

**Comment by lions-tech** [comment]
Trying to `umount /mnt/home` I received the error message `umount: /mnt/home: not mounted.`. The weird thing is, that `lsblk` shows that `/dev/sda4` is mounted under `/mnt/home`. If I `mount /dev/sda4 /mnt/home`, `lsblk` will show `/mnt/home` as mountpoint _twice_ (never seen such output before). 

It seems like this is not `nixos-install`'s fault. I will close this issue - thank you for your help.
