### ISSUE TITLE
asciidoctor-with-extensions: Remove asciidoctor-rouge gem

### ISSUE THREAD

**Issue by hybras** [NixOS/nixpkgs#248806]
https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/tools/typesetting/asciidoctor-with-extensions/Gemfile

### Describe the bug

The aforementioned ruby library is deprecated. Is functionality has been subsumed into asciidoctor.

### Steps To Reproduce

N/A

### Expected behavior

The dependency on this gem should be removed.

### Additional context

There is no change required from end users. Asciidoctor allows specifying which extensions should be used. Any users of this extension can omit it, and document conversion should be unaffected (included those that depended on this extension). 

### Notify maintainers

@doronbehar 

### Metadata

N/A

**Comment by doronbehar** [comment]
Thanks for the notice! How did you notice this? Fix is at https://github.com/NixOS/nixpkgs/pull/248869 .

**Comment by hybras** [comment]
Hugo (a static site generator) mentioned it in its docs, but asciidoctor doesn't in *its* docs, so I searched for references to the gem.

**Comment by doronbehar** [comment]
Why reopened?

**Comment by hybras** [comment]
Sorry, I'm sure why this was marked reopened.
