### ISSUE TITLE
Update request: duplicati 2.0.6.3 → 2.0.7.1

### ISSUE THREAD

**Issue by tnxz** [NixOS/nixpkgs#248951]
- Package name: duplicati
- Latest released version: 2.0.7.1

- Current version on the unstable channel: 2.0.6.3
- Current version on the stable/release channel: 2.0.6.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@adisbladis
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by LudovicoPiero** [comment]
#249144
