### ISSUE TITLE
Xonsh adds unwanted entries to PATH

### ISSUE THREAD

**Issue by amacfie** [NixOS/nixpkgs#248978]
### Describe the bug
Using xonsh in a `nix-shell` environment can override the Python interpreter, which is a problem if the environment is supposed to use a specific one.

### Steps To Reproduce
```bash
sudo docker run -ti --rm nixos/nix bash
nix-channel --update
```
Then create `shell.nix` containing
```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  packages = [
    (pkgs.python311.withPackages (ps: [
      ps.requests
    ]))
    pkgs.xonsh
  ];
}
```
Then inside xonsh, a different Python interpreter is used:
```bash
nix-shell
xonsh
python -c "import requests"  # -> ModuleNotFoundError: No module named 'requests'
```

### Expected behavior
Running xonsh should not modify the `PATH` such that a different `python` executable is used. In the above, when we run `python` we should get the `requests` library.

### Workarounds

Running `$PATH.pop(0)` removes the problematic PATH entry but this is pretty hacky.

### Notify maintainers

@vrthra

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by charmoniumQ** [comment]
I think the recommended way to do this is to add an override to xonsh.

```
      (pkgs.xonsh.override {
        extraPackages = pypkgs: ps: [ ps.requests ];
      })
```

**Comment by amacfie** [comment]
> I think the recommended way to do this is to add an override to xonsh.
> 
> ```
>       (pkgs.xonsh.override {
>         extraPackages = pypkgs: ps: [ ps.requests ];
>       })
> ```
> 
> See #240246

That's a help but if I launch a nested xonsh by running `xonsh -i` in xonsh, the extra packages are gone.

**Comment by amacfie** [comment]
@SamLukeYes since your PR was [reverted](https://github.com/NixOS/nixpkgs/pull/301449) is this issue still fixed?

**Comment by SamLukeYes** [comment]
> @SamLukeYes since your PR was [reverted](https://github.com/NixOS/nixpkgs/pull/301449) is this issue still fixed?
> 
> ETA: looks ok but if anyone still has `dontWrapPythonPrograms = true` in their config they should probably remove it before upgrading xonsh or they may get #301444.

To make it clear, `dontWrapPythonPrograms = true` was reapplied in https://github.com/NixOS/nixpkgs/pull/302385, while reverting https://github.com/NixOS/nixpkgs/pull/297628.

**Comment by SamLukeYes** [comment]
Oops, it seems we have re-introduced this issue in https://github.com/NixOS/nixpkgs/pull/314728
