### ISSUE TITLE
glibc manual is not available

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#24893]
## Issue description
It is not possible to use the glibc manual with info.

## Technical details
The make target info builds the manual, but it is not called.

## Workaround
Download info files from https://www.gnu.org/software/libc/manual/ and install it by our own.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by vcunat** [comment]
Well, if anyone wants to attack this issue, I'd suggest to create a separate derivation, so that stdenv bootstrapping isn't complicated by documentation.  _I don't know if it's this case as well, but e.g. it's common that you need heavy dependencies to generate docs._

**Comment by FliegendeWurst** [comment]
Works since #35071 is merged
