### ISSUE TITLE
cross-compilers should be supported better/more available

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#24899]
Currently there’s close to none support for crosscompilation from nixos. It is very inconvenient.

I feel like Nix has a lot of potential here. Adding cross-compilers could be as simple as:

```
let myCrossTargets =  ["x86_64-pc-windows-gnu" "mips-unknown-linux-gnu" ...] in
  pkgs = { 
    gcc.crossTargets = myCrossTargets;
    rustNightly.rustc.crossTargets = myCrossTargets;
    clang.crossTargets = myCrossTargets;
    etc etc
  };
```

especially painful are the gcc crosscompilation toolchains, so if nix supported this use-case, it would be hella awesome.

**Comment by vcunat** [comment]
I don't think it's too bad, really.  Some targets work a bit, even if it's not well documented.  In my experience it's often about finding patches to individual packages to make them cross-compile, and I think there's still very few nixpkgs users/maintainers of cross-compiling stuff.  We do CI of a few examples: http://hydra.nixos.org/jobset/nixpkgs/cross-trunk#tabs-jobs

**Comment by nagisa** [comment]
@vcunat maybe you’re misunderstanding? I want cross compilers to be available, not cross-compiled packages or cross-compilation of packages themselves.

**Comment by vcunat** [comment]
Well, the toolchain is the first thing you need for each cross-platform.  When you have that, you just "evaluate all packages with it", though most packages won't compile without changing their expressions.  I think all I've written applies to compilers as well.

**Comment by nagisa** [comment]
So, turns out cross-compilers (C ones, at least) are pretty easy to make by doing something like this:

```
let
  pkgs = import <nixpkgs> {
    config = {
      packageOverrides = super: {
        gcc = super.gcc6;
      };
    };
    crossSystem = rec {
      config = "powerpc64-linux-gnu";
      bigEndian = true;
      arch = "powerpc64";
      float = "hard";
      withTLS = true;
      libc = "glibc";
      platform = {
        kernelMajor = "2.6";
        kernelArch = "powerpc";
        kernelHeadersBaseConfig = "pseries_defconfig";
        kernelBaseConfig = "pseries_defconfig";
        gcc = {
          cpu_64 = "power8";
          cpu_32 = "power8";
        };
      };
      openssl.system = "linux-generic32";
      inherit (platform) gcc;
    };
  };
in pkgs.stdenv.mkDerivation {
  name = "shell";
}
```

This could at least be documented better.

**Comment by Ericson2314** [comment]
@nagisa I've been doing a ton of work on cross compilation lately. I've also tried to document things in a new cross compilation section of the manual. I would like rust to eventually leverage this (https://github.com/mozilla/nixpkgs-mozilla/issues/26 for example). Any feedback would be much appreciated.

I do agree that being able to get some tools without reevaluating all of nixpkgs would be nice, but not sure how to support both without greatly complicating things.

**Comment by nagisa** [comment]
@Ericson2314 My greatest problem with the two ways to get crosscompilers in nixos (expression above, AFAICT, is the legacy method) lies within the lack of examples, rather than documentation. 

It took me a long while to get the expression above going, and even then I could not make it work alongside the rust compiler. Getting a rust with both host libraries and target libraries into the expression above would strip the host libraries (no matter what I did), breaking them in the process and by extension breaking compilation of libraries that depend on build scripts.

I would gladly try the alternatives, but I do not want to spend hours fiddling with nix either.

**Comment by Ericson2314** [comment]
The new `pkgsCross` short-hand should make this stuff easy enough to stumble upon. CC @matthewbauer
