### ISSUE TITLE
Should `security.pki.caCertificateBlacklist` warn instead of error when encountering certificates not in the trust store?

### ISSUE THREAD

**Issue by whentze** [NixOS/nixpkgs#249080]
### Describe the bug

You can use [security.pki.caCertificateBlacklist](https://search.nixos.org/options?channel=23.05&show=security.pki.caCertificateBlacklist&from=0&size=50&sort=relevance&type=packages&query=caCertificateBlacklist) to opt out of importing certain certificates from Mozilla's trust store. This is a very useful option for people who want to be extra cautious.

However, if a certificate that's on the blocklist gets removed by upstream (which is quite common, the lesser-known and lesser-trustworthy CAs are both the most likely to get blocklisted and to get removed upstream), the module will give a build error like this:

```
Certs in blocklist but not in cert store: {'Hongkong Post Root CA 1'}
```

In practice, this has some quite regrettable consequences. Folks who are proactive about CA management are punished by frequent breakage when they update nixpkgs. Worse: if you then remove those CAs from the blocklist, everything builds fine, but if the CAs are re-added to the original trust store (for instance because you downgraded nixpkgs again) you will silently start trusting them again! It is also highly inconvenient for anybody trying to write re-usable NixOS modules using this option that are supposed to work on several NixOS releases.

I think it would be much better if this was a warning, not a build error.

This behavior is inherited from `buildcatrust`: https://github.com/lukegb/buildcatrust/blob/2f613c36ddb3d0e032d2e145fe05bc4c7eb3d7d9/buildcatrust/cli.py#L128
Therefore, we might have to carry more patches for that if we want to change it.

### Notify maintainers

This module doesn't seem to have any maintainers declared.

**Comment by whentze** [comment]
Pinging @fpletz and @lukegb who are listed as maintainers for `pkgs.cacert`

**Comment by lukegb** [comment]
I'm not sure there's a great way of dealing with this.

This is deliberately a fatal error because, if it isn't, it's easy to end up not distrusting what you thought you were distrusting because the name doesn't match exactly.

If you're paranoid enough to want to distrust arbitrary CAs then you should already be keeping up to date with every cacerts bump anyway, because each new release might add a new CA that meets your criteria for being dropped. You can also parameterize your distrust list based on the cacerts version if you think you'll be moving backwards and forwards often.

In terms of finding a middle ground, though: I'd be supportive of adding an option to buildcatrust to downgrade the error to a warning and then expose that in the module as an option, though.

**Comment by whentze** [comment]
Hey, thanks so much for the quick respones :)

> If you're paranoid enough to want to distrust arbitrary CAs then you should already be keeping up to date with every cacerts bump anyway, because each new release might add a new CA that meets your criteria for being dropped. You can also parameterize your distrust list based on the cacerts version if you think you'll be moving backwards and forwards often.

That is a good point. In fact, I think a bunch of people would like an allowlist-type option instead.
You can of course remove the entire trust-store and provide your own PEMs, but that is quite a steep usability cliff.
Do you think an allowlist-by-name option that still takes the certificates thus named from the trust-store would be a good idea?

**Comment by whentze** [comment]
Taking another look at this in the interest of [Spring Cleaning](https://discourse.nixos.org/t/its-issue-spring-cleaning-time-first-edition-2024/43793).

I think @lukegb's reasoning is sound, and the current somewhat inconvenient way is better than one that will silently fail to meet security requirements.

We can still consider an allowlist-style option in a future issue, but I'll close this for now.
