### ISSUE TITLE
pipewire 0.3.77 (upstream) pavucontrol and plasma-pa device duplication

### ISSUE THREAD

**Issue by GiggleSquid** [NixOS/nixpkgs#249179]
### Describe the bug
This issue is intended to track the upstream issue.

When a system resumes from a suspend state, or profile switch, audio devices will duplicate.

Regression has been identified in 0.3.77

https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/820ca90705ae78124958f1b96de3bdc7889c2d1e
fixes the issue on arch (have not tested in nixos)

### Steps To Reproduce
1. resume from session suspend or switch profile

### Expected behavior
Devices should appear once

### Additional context
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3414

Temp fix for users:
`systemctl --user restart plasma-plasmashell.service`

### Notify maintainers
@Kranzes
@K900 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.9, NixOS, 23.11 (Tapir), 23.11pre513713.100a1550b0e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos, nixos-23.05-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by vs49688** [comment]
I wonder if it's worth backporting the fix in the meantime?
This is for purely selfish reasons - this is blocking me, and I don't want to rebuild the world.

**Comment by GiggleSquid** [comment]
Honestly, pipewire's point releases, historically, are roughly 1.5 weeks apart.
I wouldn't be surprised if we see 0.3.78 in the next 2-5 days

**Comment by K900** [comment]
You can do something like 

```nix
services.pipewire.package = pkgs.pipewire.overrideAttrs(old: {
    patches = old.patches ++ [ pkgs.fetchpatch({
        url = "https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/820ca90705ae78124958f1b96de3bdc7889c2d1e.diff";
        hash = "";  # fill this in with the hash you get when it fails
    }) ];
});
```

**Comment by vs49688** [comment]
> You can do something like
> 
> ```nix
> services.pipewire.package = pkgs.pipewire.overrideAttrs(old: {
>     patches = old.patches ++ [ pkgs.fetchpatch({
>         url = "https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/820ca90705ae78124958f1b96de3bdc7889c2d1e.diff";
>         hash = "";  # fill this in with the hash you get when it fails
>     }) ];
> });
> ```

Hash is `sha256-jpo6vw3/Ng7GrLAysHblXClc5LwavUtT73jLpUXMHbk=`, and the build fails:
```
[663/973] Compiling C object src/modules/libpipewire-module-protocol-pulse.so.p/module-protocol-pulse_manager.c.o
FAILED: src/modules/libpipewire-module-protocol-pulse.so.p/module-protocol-pulse_manager.c.o
gcc -Isrc/modules/libpipewire-module-protocol-pulse.so.p -Isrc/modules -I../src/modules -I. -I.. -Isrc -I../src -Ispa/include -I../spa/include -I/nix/store/jva3mqpnfhp4r9ah0hg22axddygs37x2-systemd-minimal-253.6-dev/include -I/nix/store/dlj6ph90bmlqi3wl9snw8jn9072hrhh7-dbus-1.14.8-de>
../src/modules/module-protocol-pulse/manager.c: In function 'registry_event_global_remove':
../src/modules/module-protocol-pulse/manager.c:644:24: error: 'struct pw_manager_object' has no member named 'change_mask'
  644 |                 o->this.change_mask = ~0;
      |                        ^
[664/973] Compiling C object src/modules/libpipewire-module-echo-cancel.so.p/module-echo-cancel.c.o
```

I'll just wait until the next point release, I cbf debugging this right now ^_^

**Comment by K900** [comment]
I guess there are more prerequisite commits to be backported then.

**Comment by vs49688** [comment]
Or I'm a moron and forgot to update nixpkgs before applying the patch. I was still on `0.3.74`. System's rebuilding now, will report back.

**Comment by GiggleSquid** [comment]
Closed by #250793

**Comment by K900** [comment]
Let's keep this open until staging-next is merged.

**Comment by GiggleSquid** [comment]
My bad, good shout

**Comment by K900** [comment]
The fix is now in all affected channels.
