### ISSUE TITLE
Policy change: pushing to protected branches is now blocked

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#249117]
Starting this week, we[^1] are enabling branch protection on Nixpkgs to require pull requests for all commits to the `master` and `release-*` branches. This will prevent the almost 200 Nixpkgs committers from pushing directly to those branches, which already [almost never](https://github.com/tweag/rfcs/blob/no-direct-pushes/rfcs/0156-no-direct-pushes.md#direct-pushes-listing) happens anyways.

[^1]: @zimbatm will enable it, with support by @infinisil

Unless this causes major problems, we intend to keep this enabled permanently. Please use this issue to report any problems you encounter because of this.

## What branches are affected?

The `master` and `release-*` branches that are consumed by Hydra.

## What if I need to push?

Please contact the release managers as they will be added to the exception list.

In general, we expect that the PR workflow will be enough for the vast majority of cases.

## Background

This change was originally proposed almost 3 years ago with closed [RFC 79](https://github.com/NixOS/rfcs/pull/79) when direct pushes were way more frequent at [about 5%](https://github.com/NixOS/rfcs/pull/156#discussion_r1271478363). Very recently a new attempt was started with [RFC 156](https://github.com/NixOS/rfcs/pull/156), for which @infinisil computed that nowadays [only 0.05%](https://github.com/tweag/rfcs/blob/no-direct-pushes/rfcs/0156-no-direct-pushes.md#direct-pushes-listing) of commits are pushed directly. The RFC was struggling to get enough shepherds, when @zimbatm rightly [pointed out](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$2iwqtCYk2v02KqhELQulRdzQb20TuckPaKUIhk5myIU?via=nixos.org&via=matrix.org&via=nixos.dev) that such simple decisions shouldn't be blocked, following up with the proposal to just enable it and try it out.

**Comment by zimbatm** [comment]
I also created @NixOS/nixpkgs-release-managers to track who has push access. Please don´t abuse this to ping them :)

**Comment by infinisil** [comment]
Note that releases should also work without direct pushes, which is being discussed in https://github.com/NixOS/release-wiki/pull/70, so this exception should be removed in the future

**Comment by infinisil** [comment]
@Ma27 [pointed out](https://github.com/NixOS/rfcs/pull/156#issuecomment-1677672565) that it looks like PR's can't be merged anymore when a committer requested changes (though it seems like those reviews can be dismissed?), additionally auto-merge seems to be available now:
![2023-08-14_19-15](https://github.com/NixOS/nixpkgs/assets/20525370/320775ea-1da5-4487-a09e-11f5adc95597)

It doesn't seem inherently bad, but I did not expect that to happen.

**Comment by infinisil** [comment]
@FRidh I'm pretty sure that setting is not enabled. Indeed as an example, https://github.com/NixOS/nixpkgs/pull/249150 was merged 1 hour ago (when the setting was already in effect), and it was merged without any reviews.

The good thing is that dismissing reviews does allow merging then, and even better: To dismiss reviews you have to give a reason, I tested this here: https://github.com/infinisil/github-test/pull/2#pullrequestreview-1577305009

**Comment by infinisil** [comment]
Fyi, we do have the option to turn off allowing auto-merges, see [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#managing-auto-merge).

**Comment by infinisil** [comment]
I think we should disable the auto-merge feature because it works only based on the reviews and completely ignores the OfBorg status. And until we have more solid CI we cannot also require CI checks to pass before merging.

**Comment by zimbatm** [comment]
I turned off auto-merges.

**Comment by rnhmjoj** [comment]
> The RFC was struggling to get enough shepherds, when @zimbatm rightly [pointed out](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$2iwqtCYk2v02KqhELQulRdzQb20TuckPaKUIhk5myIU?via=nixos.org&via=matrix.org&via=nixos.dev) that such simple decisions shouldn't be blocked, following up with the proposal to just enable it and try it out.

Meh. I don't oppose this policy, but I don't like how this decision sidesteps the RFC process.
Does this imply proposals can be tacitly approved if they don't get enough attention? It doesn't seem right.

**Comment by Ma27** [comment]
> The good thing is that dismissing reviews does allow merging again, even if it's your own PR. And even better: To dismiss reviews you have to give a reason, I tested this here: infinisil/github-test#2 (review)

@infinisil for the record, I'm fine with that and I withdraw my skepticism :) 
The problem I had with the previous behavior was that there was _no_ way to override it (and from my experience almost every rule tends to have an exception ;-) ). I haven't checked it so far, but if it's possible to dismiss now while having to provide a reason for that seems good to me, thanks :+1: 

> https://discourse.nixos.org/t/policy-change-pushing-to-protected-branches-is-now-blocked/31719/1

OK with this one being pinned globally, my other issue is also resolved, this provides reasonable visibility for each committer.

IIRC we haven't had notable config changes in the repo for a while and I'm not sure if there are follow-ups planned to this, but for the future I'd like to suggest to always communicate it via a globally pinned discourse topic (and perhaps even cc all of the committers in $github_issue).

**Comment by infinisil** [comment]
> Meh. I don't oppose this policy, but I don't like how this decision sidesteps the RFC process.
> Does this imply proposals can be tacitly approved if they don't get enough attention? It doesn't seem right.

@rnhmjoj I know it looks a bit like we pulled a Flake again, but:
- The change does not have any long-lasting API or user implications, it can be reverted at any point without problems
- The change has a very low negative impact, [only ~0.05%](https://github.com/tweag/rfcs/blob/no-direct-pushes/rfcs/0156-no-direct-pushes.md#direct-pushes-listing) of commits were direct pushes
- Meanwhile, the change has a _significant_ positive impact, especially for security

Considering this, I don't think it's necessary to have an RFC for this, because it _should_ be an uncontroversial change, and indeed, we haven't seen any _good_ reason in [the RFC](https://github.com/NixOS/rfcs/pull/156) to not do this.

But also a big argument is that going through an RFC for something so minor distracts people from more important problems to fix. Not having to maintain this RFC for months frees up time for me to e.g. focus on implementing accepted NixOS/rfcs#140, which is considerably more impactful.

**Comment by zimbatm** [comment]
Closing as this was up long enough
