### ISSUE TITLE
document distributed builds and add test case

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#24914]
## Issue description

It's time consuming to set up distributed builds properly, no test case for that mechanism as well.
When configured improperly, error messages are not very useful.

### Steps to reproduce

1. Open /nixos/modules/tests folder
2. grep for "distributedBuilds" and "buildMachines" options
3. Observe empty output

1. Open NixOS documentation (1 html page)
2. Search for "distributed"

## Technical details

* System: NixOS: up to 17.03

**Comment by 3noch** [comment]
For reference: http://nixos.org/nix/manual/#chap-distributed-builds

**Comment by symphorien** [comment]
I rewrote the nixos.wiki entry about this: https://nixos.wiki/wiki/Distributed_build
The article mentions that there is a NixOS test: https://github.com/NixOS/nix/blob/master/tests/remote-builds.nix#L46-L58

**Comment by katyo** [comment]
I failed to get it works on **nixos-18.03**. I have en error:

```
error: unable to start any build; either increase '--max-jobs' or enable remote builds
```

My configuration just like an example:

```nix
  ...
  nix = {
    autoOptimiseStore = true;
    maxJobs = 0; # disable build on local machine
    buildCores = 4;
    buildMachines = [
      {
        hostName = "builder";
        system = "x86_64-linux";
        maxJobs = 4;
        supportedFeatures = [ ];
        mandatoryFeatures = [ ];
      }
    ];
    distributedBuilds = true;
    extraOptions = ''
      builders-use-substitutes = true
    '';
  };
```

Of course, the root have access to builder and can run nix commands:

```bash
[root@nixie-laptop:~]# ssh builder nix-store --version
Warning: Permanently added 'debi,192.168.13.139' (ECDSA) to the list of known hosts.
nix-store (Nix) 2.0.2

[root@nixie-laptop:~]# nix ping-store --store ssh://builder
Warning: Permanently added 'debi,192.168.13.139' (ECDSA) to the list of known hosts.
```

**Comment by symphorien** [comment]
What are you trying to build ? can you try to build with `-vvvvvv` ?
For example, nixos-tests need `supportedFeatures=[ "kvm" "nixos-test"]` otherwise nix will silently ignore the builders.

**Comment by katyo** [comment]
It seems to be works when I added `"big-parallel"` to the `supportedFeatures`.

**Comment by symphorien** [comment]
I updated the article to talk about features. Feel free to edit according to your experience.

**Comment by katyo** [comment]
@symphorien Thanks

**Comment by spinus** [comment]
@3noch @symphorien @katyo : thank you!
