### ISSUE TITLE
bug: do not hardcode the location of ca-certificates.crt

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#24911]
## Issue description

There are quite a few packages in nixpkgs where the certificate file is hardcoded to /etc/ssl/certs/ca-certificates.crt which on my Fedora system leads to for example this error:

$ git fetch origin
fatal: unable to access 'https://github.com/NixOS/nixpkgs.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

as Fedora uses different names for the certificates.

### Steps to reproduce

1. install Fedora
2. install Nix
3. install Git
4. run Git with some operation (like push)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by copumpkin** [comment]
Yeah, there are a few instances of linux packages hardcoded to NixOS assumptions that make it pretty annoying to run nixpkgs on another linux distro (or on Darwin, for that matter).

**Comment by shanemikel** [comment]
@copumpkin isn't this a recent issue for git in particular?  I could have sworn I saw a PR for this in staging...

**Comment by FRidh** [comment]
This is still a major issue https://github.com/NixOS/nixpkgs/issues/8247.
Another relevant discussion regarding the Python requests package and certificates https://github.com/NixOS/nixpkgs/commit/768c970c8d339f76947976c31ad2c8723247a8f3

**Comment by Ekleog** [comment]
(triage) I think this is a duplicate of #8247, let's focus the discussion there? :)
