### ISSUE TITLE
Gparted reports incorrect partition schemes when zfs is present

### ISSUE THREAD

**Issue by praduca** [NixOS/nixpkgs#24912]
## Issue description
Gparted is reporting some zfs partitions, on gpt, as occupying the entire device, when they are not.

### Steps to reproduce
Create a gpt device on disk
put some partitions (on my case, swap, one ntfs and two zfs, and a grub boot volume)
open gparted, it shows the entire disk with one of the zfs volumes.

## Technical details

* System: NixOS 17.03
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.914.a00c4aea5f"

Obs: probably is something related to libparted, but this is the default version of gparted for 17.03, so I'm reporting here to give an opportunity of some downgrade

**Comment by vcunat** [comment]
The last parted release (3.2) is relatively old (almost 3 years), so I suppose we would better apply some patches, e.g. https://anonscm.debian.org/cgit/parted/debian/parted.git/tree/debian/patches/zfs.patch

**Comment by praduca** [comment]
I think some kind of upgrade occurred from 16.04 to 17.03, cause gparted reported correctly the same partitions. Actually, I noticed just before upgrading, that the version on unstable reported incorrectly, and the version on 16.04 stable reported the partitions correctly.

**Comment by vcunat** [comment]
@praduca: by 16.04 you mean 16.03 or 16.09?

**Comment by praduca** [comment]
16.09, sorry :p

**Comment by vcunat** [comment]
Parted wasn't (directly) changed in any way between 16.09 and 17.03, only gparted was simply updated.

**Comment by praduca** [comment]
hm, ok, it's really more probably that it's just gparted.

**Comment by vcunat** [comment]
We have 0.30 now &ndash; do you/someone (still) use such a setup?

**Comment by praduca** [comment]
From some time now, I use the unstable channel. But even using the last version, it still reports a single partition, while `Disks` report the partitions correctly.

**Comment by bergey** [comment]
[Ticket on gparted](https://gitlab.gnome.org/GNOME/gparted/issues/14) says this is an issue with `blkid`. 

I confirm that on my computer, `blkid` reports correct labels & types for /dev/sda1 .. /dev/sda3, but for /dev/sda (whole disk) it has a surprising mix of GPT & zpool.  Probably /dev/sda & /dev/sda3 shouldn't have the same UUID.

I haven't found a fix or workaround yet; will post if I learn more.

```
15:14:52 21 prandtl 0 $ blkid /dev/sda
/dev/sda: LABEL="zpool" UUID="7391117795939420635" UUID_SUB="17114677486215839739" TYPE="zfs_member" PTUUID="242cda8d-e2db-11e7-8765-507b9d44a347" PTTYPE="gpt"
15:15:36 22 prandtl 0 $ blkid /dev/sda1
/dev/sda1: UUID="7A1C-4850" TYPE="vfat" PARTLABEL="efi" PARTUUID="3110f1b1-67cc-482f-9d73-963e6ba54f71"
15:15:38 23 prandtl 0 $ blkid /dev/sda2
/dev/sda2: UUID="adAxDg-80yI-8yYi-ls3P-f4CX-prc6-jWKSc0" TYPE="LVM2_member" PARTLABEL="lvm" PARTUUID="8703bdfd-ed54-4712-859a-a620aba4ffd9"
15:15:39 24 prandtl 0 $ blkid /dev/sda3
/dev/sda3: LABEL="zpool" UUID="7391117795939420635" UUID_SUB="17114677486215839739" TYPE="zfs_member" PARTLABEL="zpool" PARTUUID="c3f64887-a7fe-43b3-bb7f-3a5ea2637fde"
```

**Comment by praduca** [comment]
Man...
The ticket on gparted (mentioned by @bergey ) was closed with label "not gnome"...
I wil try to reproduce (i dont have the pool anymore, and upgraded nixos)
if incapable of reproducing, i will close this.

**Comment by bergey** [comment]
`gparted-1.1.0` now shows all 4 partitions on my disk, with correct sizes.  Output today from `blkid` is also much more reasonable:

```
02:45:50 164 prandtl 0 $ sudo blkid /dev/sda
/dev/sda: PTUUID="242cda8d-e2db-11e7-8765-507b9d44a347" PTTYPE="gpt"
02:45:59 165 prandtl 0 $ blkid /dev/sda1
/dev/sda1: UUID="7A1C-4850" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="efi" PARTUUID="3110f1b1-67cc-482f-9d73-963e6ba54f71"
02:46:13 166 prandtl 0 $ blkid /dev/sda2
/dev/sda2: UUID="8006dab3-3e3c-4ceb-b325-b8ed98d72f66" TYPE="swap" PARTUUID="dbe588cd-afe6-3242-b899-f3e2e1998de4"
02:46:15 167 prandtl 0 $ blkid /dev/sda3
/dev/sda3: LABEL="zpool" UUID="7391117795939420635" UUID_SUB="17114677486215839739" BLOCK_SIZE="4096" TYPE="zfs_member" PARTLABEL="zpool" PARTUUID="c3f64887-a7fe-43b3-bb7f-3a5ea2637fde"
02:46:16 168 prandtl 0 $ blkid --version
blkid from util-linux 2.35.1  (libblkid 2.35.1, 31-Jan-2020)```

**Comment by praduca** [comment]
Ah that's great. The version of util-linux is far greater than the one that showed this problem, so i will close this. Thanks to all!
