### ISSUE TITLE
17.03 fails to boot the installer

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#24923]
Using the `dd` method, `nixos-minimal-17.03.976.76c63133c5-x86_64-linux.iso` doesn't boot (mounting root timeouts).

Using `nixos-minimal-16.09.1932.f2bde3c7df-x86_64-linux.iso` works.

I'll add more as I figure out the details.

**Comment by seelmann** [comment]
I used `nixos-minimal-17.03.934.a56392363e-x86_64-linux.iso` which worked for me, both legacy BIOS and UEFI.

**Comment by lheckemann** [comment]
`nixos-minimal-17.03.982.b647a67dfe-x86_64-linux.iso` works for me, just another data point...

**Comment by bjornfor** [comment]
```nixos-minimal-17.03.982.b647a67dfe-x86_64-linux.iso``` also works for me. Tested both BIOS and UEFI boot. (ISO burnt with ```dd if=iso of=/dev/sdX```.

**Comment by dezgeg** [comment]
Did you use the same USB stick / whatever for both images? Sounds like there's some kernel module missing from the initrd.

**Comment by domenkozar** [comment]
I'll try to boot 17.03 again on that machine this weekend.

**Comment by domenkozar** [comment]
I never took this forward, it works now so whatever :)
