### ISSUE TITLE
`xorgxrdp` uses unpatched `xrdp` sources

### ISSUE THREAD

**Issue by adomixaszvers** [NixOS/nixpkgs#249273]
### Describe the bug
`xrdp` sources are patched with additional [fields](https://github.com/NixOS/nixpkgs/blob/b51db7ec1be773cc478a3f7060e04721f2a5c881/pkgs/applications/networking/remote/xrdp/dynamic_config.patch#L9) of xrdp client config. Unfortunately, `xorgxrdp` packaged with unpatched `xrdp` sources as seen [here](https://github.com/NixOS/nixpkgs/blob/b51db7ec1be773cc478a3f7060e04721f2a5c881/pkgs/applications/networking/remote/xrdp/default.nix#L31). This causes `model` and `layout` fields be overridden by value of `rsakeys_ini_file`.

### Steps To Reproduce
1. Enable `xrdp` service by
```nix
{ services.xrdp.enable = true; }
```
2. Login to xrdp session.
3. Check xkb settings.
```console
$ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/base...
Trying to load rules file /nix/store/01s51slwz2i6z019p6qb9298ws86zmq5-setxkbmap-1.3.2/share/X11/xkb/rules/base...
Success.
Applied rules from base:
rules:      base
model:      /run/xrdp/rsakeys.ini
layout:     s.ini
Trying to build keymap using the following components:
keycodes:   xfree86+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+s.ini
geometry:   pc(pc104)
xkb_keymap {
	xkb_keycodes  { include "xfree86+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+s.ini"	};
	xkb_geometry  { include "pc(pc104)"	};
};
```

### Expected behavior
xkb settings should contain appropriate values. For example: `model` - pc104 and and `layout` - us.

### Notify maintainers
@chvp 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.44, NixOS, 23.05 (Stoat), 23.05.20230809.9034b46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `""`
 - nixpkgs: `/home/adomas/.config/flakeInputs/nixpkgs`
```

**Comment by chvp** [comment]
PR at #250189
