### ISSUE TITLE
i2pd: service fails to start automatically

### ISSUE THREAD

**Issue by zetok** [NixOS/nixpkgs#24925]
## Issue description
Service failed to start automatically both after rebuild and reboot.

Starting service manually (`systemctl start i2pd`) works.

Service probably tries to start before network is up.

### Steps to reproduce
1. `services.i2pd.enable = true;`
2. `nixos-rebuild switch`

## Technical details

* System: 17.09pre105553. da20d0e488 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.09pre105553.da20d0e488"

**Comment by joachifm** [comment]
cc @edwtjo

**Comment by edwtjo** [comment]
This should be fixed in both master and 17.03, as of ad0a973ea029287ab600e0c927ba1a38beef5335
