### ISSUE TITLE
Package request: python3.pyinstaller

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#249327]
**Project description**

Freeze (package) Python programs into stand-alone executables.

**Metadata**

* homepage URL: https://www.pyinstaller.org
* source URL: https://github.com/pyinstaller/pyinstaller
* license: gpl2
* platforms: unix, linux, darwin

**Comment by nodupe** [comment]
I would love to see it packaged too.

**Comment by GetPsyched** [comment]
So, I did some digging on previous attempts at `pyinstaller` and found some abandoned PRs:
- #129344 packaged `pyinstaller` in [this commit](https://github.com/NixOS/nixpkgs/pull/129344/commits/a9e10daa84ba04175708489e217003b34293897d) itself but got abandoned due to complexity.
- #224865 was in partial effort of packaging `pyinstaller` by packaging one of its dependencies.
- #261218 also added `pyinstaller` as a dependency for another package [here](https://github.com/NixOS/nixpkgs/pull/261218/files#diff-c1c2c6c4d339a97a035ec66ddae82ccf1f356d8c0ebea9ba31908aa9305fd2d9).

**Comment by rupurt** [comment]
I would also love to figure out how to build pyinstaller projects as a nix derivation

**Comment by GetPsyched** [comment]
> I would also love to figure out how to build pyinstaller projects as a nix derivation

I believe you're looking for [`buildPythonApplication`](https://nixos.org/manual/nixpkgs/unstable/#buildpythonapplication-function)?

This issue is for how to package `pyinstaller` itself and not packaging projects using `pyinstaller`.
