### ISSUE TITLE
hibernate not resume

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#24933]
## Issue description
after resume from hibernate the system doesn't load 
(just a blinking underscore on the upper left corner)
i have to use the reset button to use my laptop again

### Steps to reproduce
execute: systemctl hibernate

## Technical details

* System: 16.09.1932.f2bde3c7df (Flounder)
* Nix version: nix-env (Nix) 1.11.8
* [configuration.nix](https://github.com/StillerHarpo/nixosconfiguration/blob/master/configuration.nix) (i was trying it without the sleep and boot.resumeDevice option before)

**Comment by danbst** [comment]
you may be interested in my findings described in https://github.com/NixOS/nixpkgs/issues/18356
the high-note is - this bug is very hardware specific

**Comment by StillerHarpo** [comment]
upgrade to 17.03 fixed it
