### ISSUE TITLE
clojure package is moving to new download location

### ISSUE THREAD

**Issue by puredanger** [NixOS/nixpkgs#249396]
### Describe the bug

Hello, I'm the Clojure CLI developer. The clojure downloads are moving from download.clojure.org to using GitHub releases at https://github.com/clojure/brew-install as the primary download location as of version 1.11.1.1386.

This file needs to be updated with the new link in line 9:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/clojure/default.nix

This line should now be:

```
url = "https://github.com/clojure/brew-install/releases/download/${finalAttrs.version}/clojure-tools-${finalAttrs.version}.tar.gz";
```

Everything else is staying the same.

### Notify maintainers

@jlesquembre 
@thiagokokada

Thanks!

**Comment by thiagokokada** [comment]
Opened a PR updating Clojure to the latest release and fixing the URL: https://github.com/NixOS/nixpkgs/pull/249413
