### ISSUE TITLE
 collision between texlive and asymptote (#29671 back from the dead?)

### ISSUE THREAD

**Issue by mikelygee** [NixOS/nixpkgs#249467]
### Describe the bug
Having both `asymptote` and the `asymptote` package for `latex` in my `home.nix` produces the following:

```
error: builder for '/nix/store/msia59pmw2ff2pvh1ns7h58sdy0whn54-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/7ca0pf5f3dy8ijsxw41433i8739jizi0-asymptote-2.85/share/info/asymptote.info' and `/nix/store/x3aqpz5kf4gwfr71cla2fnriv4cmlc1l-texlive-combined-2022/share/info/asymptote.info'
       For full logs, run 'nix log /nix/store/msia59pmw2ff2pvh1ns7h58sdy0whn54-home-manager-path.drv'.
error: 1 dependencies of derivation '/nix/store/70v7qvfyniklfrjb0gqz2416pv8ny8gi-home-manager-generation.drv' failed to build
```

This sounds exactly like https://github.com/NixOS/nixpkgs/issues/29671

### Steps To Reproduce
Try to install `asymptote` and `texlive.combined.scheme-full` together.

It also occurs with  `texlive.combined.scheme-small`, if you add the `asymptote` package.

### Notify maintainers
@7c6f434c ([Michael Raskin](https://github.com/7c6f434c) <[7c6f434c@mail.ru](mailto:7c6f434c@mail.ru)>)
@veprbl  [Dmitry Kalinkin](https://github.com/veprbl) <[veprbl@gmail.com](mailto:veprbl@gmail.com)>

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/yq14d7gqbrqiygfjqmfwcipicg13sqmm-nix-info
copying path '/nix/store/yq14d7gqbrqiygfjqmfwcipicg13sqmm-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.110, NixOS, 23.05 (Stoat), 23.05.20230723.ac1acba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 7c6f434c** [comment]
That's worse, because asymptote is the easy one to override, but unlike `.sty` its documentation is useful without TeXLive, too…

**Comment by veprbl** [comment]
cc @apfelkuchen6 @xworld21

**Comment by xworld21** [comment]
Ouch, although not surprising: right now texlive.asymptote exports everything, so even `bin/asy` will clash. If you want the docs, the official solution is to modify `pkgFilter` to install the texlive docs for asymptote. Is there something else that asymptote offers, but is not available in texlive.asymptote?

Still, `pkgFilter` is nasty, so in the short term I'll override away the asymptote docs & binaries from texlive. Users will need to install asymptote by hand to use it. We can backtrack on this once texlive gets a sane interface and a straightforward overriding mechanism (hopefully in time for 23.11).

**Comment by 7c6f434c** [comment]
Oh, TeXLive has catched up on versions, nice. But I think the TeXLive package does not provide the binary, which is why one needs to install `asymptote` too.

**Comment by 7c6f434c** [comment]
I think it doesn't matter if the sty is older, and it's a question about upstream packaging at TeXLive.

But if TeXLive way includes the fresh binary, maybe the answer here is that there is no reason to install both?

**Comment by xworld21** [comment]
> But if TeXLive way includes the fresh binary, maybe the answer here is that there is no reason to install both?

Yeah I don't think one needs to install both. Are there any other reasons for using `asymptote` instead of `texlive.asymptote`? Installing the docs via `pkgFilter` is tricky, but other than that, the texlive package seems to have everything, even the emacs package (in the wrong folder though).

Does that mean we can close the issue (possibly with a reminder to flag this in the release notes)?

**Comment by 7c6f434c** [comment]
I don't know of a convincing reason for a normal user to install asymptote separately (it is useful on its own, but it wants to call TeX for some tasks anyway!)

I guess fully documenting this would also include the Nixpkgs manual

**Comment by xworld21** [comment]
> I don't know of a convincing reason for a normal user to install asymptote separately

All right, so to conclude, @mikelygee could you please confirm that using `texlive.combine` only, without installing `asymptote` as well, works as you wish? The binaries for asymptote should already be included in `texlive.combine`. Please close the issue if that works ok.

**Comment by xworld21** [comment]
There were no more complaints, I figure the current TeX Live arrangements must be good enough!
