### ISSUE TITLE
fritzing, cura: No GSettings schemas upon file picker dialog

### ISSUE THREAD

**Issue by ix** [NixOS/nixpkgs#24943]
## Issue description

Both Fritzing and Cura fail to open/save files with the same error (which are likely closely related):

```
(Fritzing:4503): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
(python3:5202): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

They both end in a trace trap and crash. The second one may be more related to Python than Cura. This also only happened after I switched from xmonad to XFCE.

Likely closely related to #24880 and #21647.

### Steps to reproduce

Fritzing:
- `nix-env -i fritzing`
- Run Fritzing
- Attempt to save the current project
- Examine trace trap

Cura:
- `nix-env -i cura`
- Run Cura
- Attempt to open the file picker and select an STL
- Examine trace trap

## Technical details

* System: NixOS 17.09pre102441.45344fd (Hummingbird)
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre102441.45344fd

**Comment by Mic92** [comment]
Usually this can be fixed the following way: https://github.com/NixOS/nixpkgs/pull/24868/commits/deeddbd495dffe78163430aa49b2487d9d10681c

**Comment by abbradar** [comment]
I plan to fix this and several similar issues later but I'm a bit short on time nowadays; if someone outruns me I won't hold a grudge :D

**Comment by abbradar** [comment]
`cura` should already be okay on master since a40b7d07e9013fcc21d54cbb4a01bcfc9c6e68cb.
