### ISSUE TITLE
rxvt-unicode has broken unicode

### ISSUE THREAD

**Issue by ryantrinkle** [NixOS/nixpkgs#249451]
### Describe the bug
In rxvt-unicode, some unicode is displayed incorrectly.  Escape sequences may also have problems, but I am not sure.

### Steps To Reproduce
1. `nix-shell -p rxvt-unicode --run "urxvt -e bash -c 'printf \"\\u203B\" ; read'"`
2. Output will look like ![image](https://github.com/NixOS/nixpkgs/assets/1156448/2ac1c6b2-3737-4871-9165-e0f751f8efae)

### Expected behavior
Output should look like ![image](https://github.com/NixOS/nixpkgs/assets/1156448/6c24270d-6b52-4281-8f3c-18071dbd3ab8)

### Screenshots
Broken: ![image](https://github.com/NixOS/nixpkgs/assets/1156448/2ac1c6b2-3737-4871-9165-e0f751f8efae)
Working: ![image](https://github.com/NixOS/nixpkgs/assets/1156448/6c24270d-6b52-4281-8f3c-18071dbd3ab8)

### Additional context
I bisected this down to **known-good** commits aa0f09558c29bac6021370bf0fe681f54d7a9410, 4b6463704e295e19f0414a39de09237df6f41d74, and d45279b3a8bbe37a07b008e2e4e2cef224335e7f and **bad commit** f41621432fbf15ff8f8e51eaa978bf394b171953.  35524da260fbef727fcfe38927ed4a4e6b594ec6 and 82a0774af60d88d2331911323eacc85b3662380f did not build so either of them or f41621432fbf15ff8f8e51eaa978bf394b171953 could be the one that introduces the issue.

### Notify maintainers
@stigtsp @rnhmjoj 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - channels(ryan): `"nixpkgs-search-22.11pre386147.e0a42267f73"`
 - nixpkgs: `/home/ryan/.config/nixpkgs/nixpkgs`
```

**Comment by ryantrinkle** [comment]
@stigtsp Do you have any insight into this?

**Comment by rnhmjoj** [comment]
Ah, on master it's probably this issue: https://github.com/NixOS/nixpkgs/pull/249166

**Comment by stigtsp** [comment]
Hi!

Merged https://github.com/NixOS/nixpkgs/pull/249166

**Comment by rnhmjoj** [comment]
The fix reached [unstable](https://nixpk.gs/pr-tracker.html?pr=249166), closing.
