### ISSUE TITLE
No way to customize manim's LaTeX package

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#249566]
### Describe the bug
I find no easy way to customize the LaTeX package used by manim. As a result, I cannot use packages like mathtools since only very few packages are included by default:

https://github.com/NixOS/nixpkgs/blob/62730f2c3107f2f9e4684f05236ea9dc8066568d/pkgs/applications/video/manim/default.nix#L126-L131

### Steps To Reproduce
1. `nix-shell -p manim`
2. Create a file `test.py` containing:
```
from manim import *

template = TexTemplate(preamble=r'\usepackage{mathtools}')

class Intro(Scene):
    def construct(self):

        termsTitle = Tex(r"a \coloneqq b", tex_template=template)
        self.play(FadeIn(termsTitle.to_edge(UP)))
        self.wait()
```
3. Run `manim -pql test.py Intro` and observe "LaTeX Error: File `mathtools.sty' not found.".

### Expected behavior

I would like to be able to use my custom LaTeX distribution, like `texlive.combined.scheme-full`.

### Notify maintainers

@friedelino

**Comment by xworld21** [comment]
This should be easier since 23.11: you can override manim's `texliveInfraOnly` attribute to include more packages, for instance
```nix
manim.overrideAttrs { texliveInfraOnly = texliveInfraOnly.withPackages (ps: [ ps.mathtools ]); }
```
If that's enough for what you need @tobiasBora please close the issue.

I think the better alternative is to remove texlive from the wrapper altogether, but that's something that requires discussion with the maintainers and it would be a breaking change for some people.

**Comment by tobiasBora** [comment]
Great, thanks a lot, this seems good enough for my need. And I guess I can specify `texliveInfraOnly =  texlive.combined.scheme-full;` if I don't want to worry about installed packages.

**Comment by rasmus-kirk** [comment]
Neither of these seem to work for me with the following flake:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      # Systems supported
      allSystems = [
        "x86_64-linux" # 64-bit Intel/AMD Linux
        "aarch64-linux" # 64-bit ARM Linux
        "x86_64-darwin" # 64-bit Intel macOS
        "aarch64-darwin" # 64-bit ARM macOS
      ];

      # Helper to provide system-specific attributes
      forAllSystems = f: nixpkgs.lib.genAttrs allSystems (system: f {
        pkgs = import nixpkgs {
          inherit system;
        };
      });
    in
    {
      devShells = forAllSystems ({ pkgs } : {
        default = pkgs.mkShell {
          packages = with pkgs; [
            (manim.overrideAttrs { texliveInfraOnly = texliveInfraOnly.withPackages (ps: [ ps.mathtools ]); })
            # (manim.overrideAttrs { texliveInfraOnly = texlive.combined.scheme-full; })
            ruff
            pyright
            (pkgs.python3.withPackages (p: with p; [
              pyright
            ]))
          ];
        };
      });
    };
}
```
