### ISSUE TITLE
How to patch a program which relies on /proc/[pid]/exe?

### ISSUE THREAD

**Issue by jeremejevs** [NixOS/nixpkgs#24955]
XTerm has an action called [`spawn-new-terminal`](http://invisible-island.net/xterm/manpage/xterm.html#Actions:spawn-new-terminal), which launches another instance of XTerm by executing its own `/proc/[pid]/exe`. Problem is, `exe` points at `.xterm-wrapped`, instead of `xterm`. This results in `XAPPLRESDIR` env var never being set, and XTerm is loaded without the default config file (it looks for `$XAPPLRESDIR/XTerm`).

This isn't game-breaking, I just use `exec-formatted("xterm", SELECT)` instead, but I'm curious, how one would go about making XTerm (or some other program relying on `/proc/[pid]/exe`) use the `xterm` shell script, instead of launching the `.xterm-wrapped` binary directly?

In case anybody wants to tackle this, `spawn-new-terminal` needs to be enabled explicitly:

```nix
packageOverrides = pkgs: rec {
  xterm = pkgs.xterm.overrideAttrs (oldAttrs: {
    configureFlags = oldAttrs.configureFlags ++ ["--enable-exec-xterm"];
  });
};
```

And then you can bind it to a key combo or something:

```
xterm*VT100.translations: #override Ctrl Shift <Key>N: spawn-new-terminal()
```

**Comment by joachifm** [comment]
I suppose you could replace all instances of `/proc/self/exe` with the path to `$out/bin/xterm`, but perhaps I'm missing a nuance in the question?

**Comment by jeremejevs** [comment]
No, you aren't, I'm just new to Nix, learning the tricks. So, replacing [this line](https://github.com/joejulian/xterm/blob/defc6dd5684a12dc8e56cb6973ef973e7a32caa3/misc.c#L794) with `child_exe = "<whatever $out/bin/xterm evaluates to>";` before compilation is the way to go? What would be preferred, a `sed` or a `.patch`? I was also thinking that maybe the behavior of `/proc/[pid]/exe` could be adjusted (to point at the wrapping script), but it appears that's an infeasible task.

**Comment by joachifm** [comment]
@jeremejevs yes, that'd be the general idea. Though in this case some care is needed, as it seems the `Readlink` procedure allocates storage for the pathname, so I expect you couldn't simply blindly replace it. Something like `char child_exe[] = "$out/bin/xterm"` might work (to be clear, it should look like `char child_exe[] = "/nix/store/.../bin/xterm";` in the patched source file).

The problem with a standalone patch in this case is that it has to be created prior to the build so it must use a placeholder value for `$out`  which you then substitute at build time after applying the patch.
An alternative would be to use two sed subsittutions, one to delete the original declaration and one to replace the `Readlink` thing with a static declaration.

I've no idea if it's possible to somehow make `/proc/self/exe` point to the wrapper itself, as it does an implicit `exec` on the unwrapped binary.

**Comment by FRidh** [comment]
Maybe argv[0] contains the full path so you could use that?

**Comment by lheckemann** [comment]
`argv[0]` should be the wrapped program as well, so the same problem would occur.

**Comment by ben0x539** [comment]
Shouldn't the newly spawned xterm process inherit the environment variable from its parent?

**Comment by joachifm** [comment]
You mean just set the appropriate dir in `XAPPLRESDIR` to begin with? That sounds like it should work. Not as interesting as patching though!

**Comment by lheckemann** [comment]
No, the initial xterm should have `XAPPLRESDIR` set by the wrapper, and that should be inherited by the child process.

**Comment by joachifm** [comment]
> No, the initial xterm should have XAPPLRESDIR set by the wrapper, and that should be inherited by the child process.

That is what I meant :)

**Comment by jeremejevs** [comment]
Thanks for the replies! XTerm had too many quirks to my liking, and I'm now using Termite instead, so there's no incentive for me to fix this anymore. I suppose if somebody else needs this, they can open a separate issue.
