### ISSUE TITLE
logcheck's homepage contains questionable links

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#24952]
## Issue description
I happened to notice that the site we point people to for [logcheck's homepage](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/logcheck/default.nix#L39) contains links to gambling services. Now, I understand people need to make money, but I wonder if we really want to be complicit in driving traffic to this stuff ... More generally, should we actively "censor" upstream homepages with "bad" content?

**Comment by joachifm** [comment]
The obvious alternative in logcheck's case is to link to https://packages.debian.org/sid/logcheck instead; debian.org seems to do all the hosting for source, mailing lists, &c, anyway, so I don't know what the current homepage site owners are really providing.

**Comment by vcunat** [comment]
Well, Debian points to http://logcheck.alioth.debian.org/ as the homepage.  It seems possible that logcheck.org is a copy of the real homepage, made by someone not really related to the project.

**Comment by globin** [comment]
👍 for using http://logcheck.alioth.debian.org/

**Comment by joachifm** [comment]
Ah, I was under the impression that the alioth page was down, but seeing as it's very much up and running makes me even more suspicious about logcheck dot org.

**Comment by joachifm** [comment]
Thanks all :)
