### ISSUE TITLE
Package request: Intel OneVPL-intel-gpu

### ISSUE THREAD

**Issue by PJungkamp** [NixOS/nixpkgs#249596]
**Project description**

The `OneVPL-intel-gpu` library is needed as a dependency of `intel-media-sdk` to support QSV hardware acceleration on intel alderlake and newer GPUs. Currently `libmfx` in `intel-media-sdk` tries to dispatch to the OneVPL backend and fails.

**Metadata**

* homepage URL: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onevpl.html
* source URL: https://github.com/oneapi-src/oneVPL-intel-gpu
* license: mit
* platforms: linux

**Comment by SemMulder** [comment]
@midchildan as maintainer of `intel-media-sdk`: do you have any thoughts on this. See also Intel's deprecation notice of `intel-media-sdk` in favor of OneVPL (https://www.intel.com/content/www/us/en/developer/articles/tool/media-sdk.html).

**Comment by SemMulder** [comment]
Adding the `ffmpeg` error so that other people can find this ticket as well:
```
[AVHWDeviceContext @ 0x24321c0] Error initializing an MFX session: -3.
Device creation failed: -1313558101.
Failed to set value 'qsv=qs@va' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

**Comment by midchildan** [comment]
This is unfortunate, because Intel seems to have deprecated Media SDK without leaving a migration path for owners of older CPUs. Looking at the [README](https://github.com/oneapi-src/oneVPL-intel-gpu), OneVPL isn't supported on CPUs older than 3 years.

[Media SDK's repo](https://github.com/Intel-Media-SDK/MediaSDK) also mentions something about a security issue...

**Comment by evanrichter** [comment]
Yeah, I would still like to make progress on my PR, but last time I tried to verify my package, I couldn't get ffmpeg rebuilt with the necessary flags.

I also am concerned about the lack of upgrade path for older CPUs because I think the configure flags for ffmpeg are in conflict. That could mean supporting two builds of ffmpeg

**Comment by SemMulder** [comment]
With regards to the migration path. I think Intel's solution is to keep `intel-media-sdk` around on the system, but make it dispatch to `oneVPL` at runtime on Alder Lake+. Quoting the `intel-media-sdk` readme:

> Pay attention that Intel® Media SDK has forward compatibility with new VPL runtime (libmfx-gen.so.1.2) in the scope of API features supported by both 1.x and 2.x API series. As such, if application is built against Intel® Media SDK, it still can work on new platforms. For that purpose Media SDK Dispatcher loads either Media SDK Legacy Runtime (libmfxhw64.so.1) or VPL Runtime (libmfx-gen.so.1.2) depending on the underlying platform. See support matrix below.

Then existing applications can just be compiled against `intel-media-sdk`, but they will use `oneVPL` under the hood on newer systems.

That would provide us with an easy path forward for the time being as well, I think. At least, that should buy us some time for the community to come to a consensus on how to move forward.

**Comment by SemMulder** [comment]
Reading some more, I believe `oneVPL` can dispatch back to `intel-media-sdk` as well:

> oneVPL dispatcher can work with the Intel® Media SDK GPU runtime to support legacy GPUs and the Intel® VPL GPU implementation for newer GPUs.
> 
> Source: https://www.intel.com/content/www/us/en/docs/onevpl/upgrade-from-msdk/2023-1/onevpl-hardware-support-details.html

So when applications are ready to switch over to `oneVPL` we can still support old hardware by ensuring `intel-media-sdk` is on the system.

**Comment by SemMulder** [comment]
@evanrichter

So I think that means you shouldn't have to change ffmpeg flags for the moment?

**Comment by PJungkamp** [comment]
I ran into this problem when I tried to run Jellyfin with QuickSync hardware acceleration and noticed the error that @SemMulder posted [above](https://github.com/NixOS/nixpkgs/issues/249596#issuecomment-1682251439).
I actually managed to make it work:

- Nixpkgs needs `OneVPL` and `OneVPL-intel-gpu` packages, `OneVPL` dispatches to a backend, which can be either `intel-media-sdk` or `OneVPL-intel-gpu`.
- `ffmpeg`'s flags do have to be changed. The `ffmpeg` derivation in Nixpkgs only supports `libmfx` (with `--enable-libmfx`) which calls directly into `intel-media-sdk`. To use hardware acceleration on Alder Lake and later, `ffmpeg` needs to be built with the `--enable-onevpl` flag. This uses the OneVPL dispatcher that chooses either `OneVPL-intel-gpu` or `intel-media-sdk` depending on the platform. The `--enable-libmfx` flag conflicts with `--enable-onevpl`.

I'll post my derivations when I get home. I hadn't seen the https://github.com/NixOS/nixpkgs/pull/242359 PR I'll leave some notes there (`onevpl` would probably be a better name for that PR/package).

**Comment by PJungkamp** [comment]
> With regards to the migration path. I think Intel's solution is to keep `intel-media-sdk` around on the system, but make it dispatch to `oneVPL` at runtime on Alder Lake+. Quoting the `intel-media-sdk` readme:
> 
> > Pay attention that Intel® Media SDK has forward compatibility with new VPL runtime (libmfx-gen.so.1.2) in the scope of API features supported by both 1.x and 2.x API series. As such, if application is built against Intel® Media SDK, it still can work on new platforms. For that purpose Media SDK Dispatcher loads either Media SDK Legacy Runtime (libmfxhw64.so.1) or VPL Runtime (libmfx-gen.so.1.2) depending on the underlying platform. See support matrix below.
> 
> Then existing applications can just be compiled against `intel-media-sdk`, but they will use `oneVPL` under the hood on newer systems.
> 
> That would provide us with an easy path forward for the time being as well, I think. At least, that should buy us some time for the community to come to a consensus on how to move forward.

I checked the `intel-media-sdk` code. The MSDK uses the `-DMFX_MODULES_DIR` CMake option to determine the directory in which the `libmfxhw64.so` and `libmfx-gen.so` are searched for. This directory is both the search and install directory for the `libmfxhw64.so`. This means we have to create a build time dependency on `oneVPL-intel-gpu` to `intel-media-sdk` and add a `postInstall` hook that copies or links the the `libmfx-gen.so` from `oneVPL-intel-gpu` into the `MFX_MODULES_DIR`. `MFX_MODULES_DIR` defaults to the CMake library path.

**Comment by RyanGibb** [comment]
> I'll post my derivations when I get home.

@PJungkamp I'm trying to replicate your setup, is there any chance you could share your derivations?

**Comment by RyanGibb** [comment]
> I posted them in the related PRs comments.
> 
> [#242359 (comment)](https://github.com/NixOS/nixpkgs/pull/242359#issuecomment-1689534630)

Thanks @PJungkamp! I ended up doing this to get it working for me https://github.com/RyanGibb/nixos/commit/55aca5b360f734f8db8d426c2a6b803e164cf531

**Comment by evanrichter** [comment]
#264621 has been merged 🎉

**Comment by J-Swift** [comment]
Nice job @evanrichter, thanks for sticking with it
