### ISSUE TITLE
Package request: Tlauncher

### ISSUE THREAD

**Issue by XxPRxBoyxX** [NixOS/nixpkgs#249576]
Sorry i am an idiot please close this

**Comment by MatcraftouOff** [comment]
Do you know that Tlauncher contains malware code?
It does things that a Malware would do, and the actual Tlauncher owners did some unscrupulous practices.
I am not a packages I just wanted to disclose this.

**Comment by XxPRxBoyxX** [comment]
Sorry i didn’t know mb

**Comment by aloiscochard** [comment]
@MatcraftouOff this is not true anymore: https://isp.page/news/tlauncher-safety-in-2023-is-tlauncher-still-considered-a-virus/#gsc.tab=0

On light of this, could someone re-open this issue or should I create a new one?
