### ISSUE TITLE
cross-compilation from x86_64 to arm64

### ISSUE THREAD

**Issue by innat-asj** [NixOS/nixpkgs#249593]
I am seeking for some tools and encounter this packages (nixpkgs) from this [comment](https://github.com/pypa/setuptools/issues/2679#issuecomment-881891719). Apologies if it is not aligned with the issue protocol. 

**Target**

I have some python scripts and using Cython I can obfuscate them. I am using Windows (WSL) with x86_64 arch. The obfuscated compiled (`.so`) will be run on Jeston TX2 (an aarch64 arch) device. Now using standard setup tools, I have faced several issues while trying to cross compilation. 

Installing cross-compiler toolchain.

```bash
sudo apt update
sudo apt install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
sudo apt install g++-aarch64-linux-gnu
```

```python
# main.py
from distutils.core import setup
from distutils.extension import Extension                       
from Cython.Distutils import build_ext  

ext_modules = [
    Extension(
        "main",  
        ["main.py"],
    )
]
setup(
    name = 'Excavator Detection',
    cmdclass = {'build_ext': build_ext},                     
    ext_modules = ext_modules,
    extra_compile_args=['-march=armv8-a', '-mcpu=cortex-a57']
)
```
```bash
# bash.sh
export CC=aarch64-linux-gnu-gcc
export CXX=aarch64-linux-gnu-g++
python setup.py build_ext --inplace
```

It doesn't work.  There are also semantic level issue with setup tools in this case, [such as](https://github.com/cython/cython/issues/5009).

Now, I was wondering if I can solve this using nixpkgs. 
Sorry I didn't dig enough about nixpkgs and its doc. However any suggestion would be highly appreciated. thnx.

**Comment by Majiir** [comment]
nixpkgs has built-in tooling for cross-compilation. Generally, you don't need to configure cross-compilation flags yourself.

For example, `ranger` is a Python application. You can cross-compile it for a Raspberry Pi by building `pkgsCross.aarch64-multiplatform.ranger`. You can see that the [package expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/file-managers/ranger/default.nix) for `ranger` doesn't mention cross-compilation anywhere. Host and build architecture flags are set in the nixpkgs builder scripts instead, which are shared across packages.

That is my _rough_ understanding of it as a user of nixpkgs cross-compilation features, anyway.
