### ISSUE TITLE
buildbot-master: masterCfg defaults to null but expects a String

### ISSUE THREAD

**Issue by tsurai** [NixOS/nixpkgs#24951]
## Issue description
The option masterCfg of buildbot-master expects a string but defaults to null causing an error when trying to build the system configuration.

``error: The option value `services.buildbot-master.masterCfg' in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/services/continuous-integration/buildbot/master.nix' is not a string.``

### Steps to reproduce
Don't configure the option masterCfg of  buildbot-master.

## Technical details

* System: 17.03.981.a7ebf59aa7 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.981.a7ebf59aa7

**Comment by joachifm** [comment]
I believe this was fixed by 3f116702cc1242e34d008a8f1793e6f542e79472 (on master).

**Comment by tsurai** [comment]
oh, sorry I didnt check the master properly. Thanks

**Comment by joachifm** [comment]
The fix has been picked to release so should show up when the channel moves ahead :)

**Comment by joachifm** [comment]
Fixes like this can slip by without going to the release branch. Thank you for the report.
