### ISSUE TITLE
Naming of `datadog_trace` instead of `ddtrace` in PHP Extensions

### ISSUE THREAD

**Issue by baptistepottier** [NixOS/nixpkgs#249599]
### Describe the bug
php is unable to find datadog-trace.so (and it's normal)

### Steps To Reproduce
1. create a shell with php and datadog_trace extension
php.withExtensions ({ enabled, all }: with all; [ xdebug curl opcache openssl datadog_trace])
2. run nix-shell and run php -v
3. it display "Warning: PHP Startup: Unable to load dynamic library '/nix/store/qi72nhxwvbysg35nbvf89q3ywad46xyc-php-datadog_trace-0.89.0/lib/php/extensions/datadog_trace.so' (tried: /nix/store/........;" and the extension isnt' loaded

### Additional context
the extension is well installed but php configuration is looking for a wrong one (the original should be named ddtrace.so and the package is looking for datadog_trace.so

### Notify maintainers

@drupol

**Comment by drupol** [comment]
Thanks for creating the issue :)

Fixed in https://github.com/NixOS/nixpkgs/pull/249563

**Comment by baptistepottier** [comment]
You ask me for that i think it's normal, it's a minimum :)
NOw we just have to wait to make it work so ? have a nive evening (i'm in
france)

Le mer. 16 août 2023 à 21:29, Pol Dellaiera ***@***.***> a
écrit :

**Comment by drupol** [comment]
You can monitor the progress of this PR by using the following tool: [nixpkgs PR Tracker](https://nixpk.gs/pr-tracker.html?pr=249563).

If you are using Nix tools from the `master` branch, they should already be available to you, but they will need to be compiled on your machine. This means that you'll have to wait for the compilation process to finish before you can use them.

However, if you can wait for one or two days until this PR reaches `nixpkgs-unstable`, the binaries will be hosted on `cache.nixos.org`. At that point, they will become immediately available, and you won't have to deal with the hassle of recompilation.

Greetings from Belgium.

**Comment by baptistepottier** [comment]
no probleme to compile, l try !!!

yes !

[image: image.png]

[image: image.png]





Le mer. 16 août 2023 à 21:43, Pol Dellaiera ***@***.***> a
écrit :
