### ISSUE TITLE
`/etc` handling (`overlayfs`, with case study on a non-NixOS Nix-based system)

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#24967]
### Current NixOS practice

Currently, NixOS activation spends non-negligible amount of time traversing `/etc` for dangling `/etc/static` links. Also, when new entries are added, `/etc` is refilled non-atomically.

### Proposed solution

What I use on my current system (which is not NixOS but uses NixPkgs and reuses some parts of the NixOS tooling) is the following construction:

`/bin`, `/usr`, `/etc/` are symlinks into `/run/current-system/global`

`/run/current-system/global/{bin,usr,etc-static}` are just statically built somehow.

`/run/current-system/global/etc` (target of `/etc` symlink) is again a symbolic link to (say) `/var/etc-overlay/[system-hash]/`

`/var/etc-overlay/[system-hash]/` is an `overlayfs` union mount of the corresponding system's `global/etc-static` from Nix store and `/var/etc` that keeps the non-Nix-managed parts. `overlayfs` also wants a so-called `workdir` which I put into `/var/etc-workdir/[system-hash]/`. Maybe putting the `overlayfs` magic into `/run` is a better idea long term, though.

During activation, an `-t overlay` mount is established before the `current-system` link switch, and when the link gets updated, the new mount becomes the current one automatically.

### Drawbacks

Currently, I don't see any append-only mode for `overlayfs` (`aufs` does have one). So, opening one of the read-only files as root will create a copy in `/var/etc` and allow changes.

Also, if there is a pre-existing copy in `/var/etc`, it will take precedence (again, `aufs` can be configured otherwise, but has its own drawbacks)

The current solution requires explicit replacement of the symlink (slightly more resilient), but cannot stop such replacement.

### Pitfalls of a wrong implementation

Two layers of `/etc` link are actually necessary in this construction as-is. One could just use a mountpoint inside store, but `nix-store --gc` will happily recursively remove files on an `overlayfs` mounted inside the store path it collects (should Nix behaviour be changed here, too?)

Another option would be using a staging ground in `/run` or `/var` per-system-generation and point `/run/current-system` link there, but having `/run/current-system` point into store simplifies GC root management.

### Side benefits for Nix-based system coexistence

Multiple Nix-based systems having different ideas about proper `/etc/` management but agreeing that `/etc/` is a symlink to `/run/current-system/global/etc` can be used on the same store and the same root FS without interfering too much; `/etc/` management as done by NixOS right now has more state.

### People who pushed me to write it as an issue as is

@copumpkin @grahamc

**Comment by volth** [comment]
Why does atomicity of adding files to ```/etc``` matter? Is there any service watching for new files in ```/etc``` instead of rereading files when a signal arrives?

**Comment by 7c6f434c** [comment]
With multi-second race windows there is a chance that a random user-started tool will read an intermediate state. Union-mount approach can also be made faster than creating/removing many symlinks, so atomicity is not the only point.

**Comment by copumpkin** [comment]
There's also the interruption concern, if there's a bug in the script or some other sort of failure, the etc preparation script can leave the system in a weird state.

**Comment by 7c6f434c** [comment]
I thought about interruption concerns, but they seem to be reboot-fixable, so I didn't mention them in my reply.

**Comment by volth** [comment]
A race could happen even if the change is atomic. For example ```file1``` has ```include 'file2'``` and ```/etc``` is changed atomically after ```file1``` is read but before ```file2``` is read

**Comment by 7c6f434c** [comment]
That's true, but this race can occur even without a switch. Slow switch creates new interesting combinations of states by introducing hanging symlinks, though.

**Comment by volth** [comment]
Also, how typical is to have not-nix-managed files in ```/etc``` ?
I mean, besides the dozen of workstations we use to hack nix.
On servers, in containers, in nixops deployments?

**Comment by 7c6f434c** [comment]
I would expect that a majority of systems running NixOS have not-store-symlinks files in `/etc`. Namely, one of the following:

* `/etc/ssh/ssh_host_rsa_key`
* `/etc/machine-id`
* `/etc/resolv.conf`
* `/etc/passwd`
* `/etc/cups/`

**Comment by Mic92** [comment]
I only want to note, that overlayfs does not work on top of zfs.

**Comment by Mic92** [comment]
One improvement, which could be made on Linux is to use the `RENAME_EXCHANGE` feature of the system call `renameat2` to update the `static` directory with the new version.

**Comment by 7c6f434c** [comment]
Re:ZFS — ouch.

Why FUSE union solutions are so much more predictable and simple… But worse performance, I know.

Well, another approach is enumerating allowed uses of mutable data accessible through `/etc/` and creating symlinks for them. SSH and CUPS shouldn't be a problem. `machine-id` is DBus, after all, but there is a hope. 

`resolv.conf` and `passwd` get `rename`d into place on change, which can require annoying patching…

**Comment by 7c6f434c** [comment]
After various experiments (and sometimes issues) I decided that thw way I personally want to go is fully read-only `/etc/` with symlinks to mutable paths when needed, and with a separate helper for `passwd` manipulation.
