### ISSUE TITLE
 failed to create symbolic link '/nix/store/2qywk18bv432ca2znk21964hbm1xkl41-user-units/xdg-desktop-portal-hyprland.service': File exists

### ISSUE THREAD

**Issue by sacsbrainz** [NixOS/nixpkgs#249645]
### Describe the bug
this was my fomer nixos config before i was told i did it wrongly

```
...
  services = {
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      wireplumber.enable = true;
    };
  };
...

  home-manager.users.sacs = {pkgs, ...}: {
    home.username = "sacs";
    home.homeDirectory = "/home/sacs";
    fonts.fontconfig.enable = true;
    home.packages = with pkgs; [
      ...
      xdg-desktop-portal-hyprland
  ];
....
```
but now i corrected it to this

```
...
  services = {
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      wireplumber.enable = true;
    };
  };
...
  xdg = {
    portal = {
      enable = true;
      extraPortals = with pkgs; [
       xdg-desktop-portal-hyprland
      ];
    };
 };
```

when i run
`sudo nixos-rebuild switch`

i get this error

```
these 4 derivations will be built:
  /nix/store/0kw6sk6x7mrhq4p0pac6l80vijmxbff1-user-units.drv
  /nix/store/apwvimnnphh38d2xp47s05bm2i2gsk0v-system-units.drv
  /nix/store/561lg1xs9klpz6h0qrpp860h54b5qrgb-etc.drv
  /nix/store/2lql1yw4r9fwpmlflvd3f0kff8wwhzaz-nixos-system-nixos-23.11pre509514.9e1960bc196b.drv
building '/nix/store/apwvimnnphh38d2xp47s05bm2i2gsk0v-system-units.drv'...
building '/nix/store/0kw6sk6x7mrhq4p0pac6l80vijmxbff1-user-units.drv'...
ln: failed to create symbolic link '/nix/store/2qywk18bv432ca2znk21964hbm1xkl41-user-units/xdg-desktop-portal-hyprland.service': File exists
error: builder for '/nix/store/0kw6sk6x7mrhq4p0pac6l80vijmxbff1-user-units.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/561lg1xs9klpz6h0qrpp860h54b5qrgb-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2lql1yw4r9fwpmlflvd3f0kff8wwhzaz-nixos-system-nixos-23.11pre509514.9e1960bc196b.drv' failed to build
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[sacs@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.11 (Tapir), 23.11pre509514.9e1960bc196b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by makusu720** [comment]
There has been a recent change, you no longer need to pass the `xdg-desktop-portal-hyprland` package to extraPortals. The Hyprland package does it automatically: `programs.hyprland.portalPackage` has `programs.hyprland.portalPackage` set by default.

**Comment by sacsbrainz** [comment]
any example on how to add it to my configuration.nix file?

**Comment by makusu720** [comment]
You do not need it. It is now enabled by default.

**Comment by sacsbrainz** [comment]
ok then why am i unable to screen share in google meet

**Comment by sacsbrainz** [comment]
how do i update my packages to pick up the new updates?

i am currently on unstable channel

**Comment by Mikilio** [comment]
Maybe your browser doesn't have pipewire and ozone enabled.

**Comment by sacsbrainz** [comment]
> Maybe your browser doesn't have pipewire and ozone enabled.

i have tried both firefox and chrome and chromium

on chrome i enabled the it the graphics of the app become horrible still didnt work

**Comment by sacsbrainz** [comment]
> Maybe your browser doesn't have pipewire and ozone enabled.

i have tried both firefox and chrome and chromium

on chrome i enabled the it the graphics of the app become horrible still didnt work

**Comment by Mikilio** [comment]
As mentioned before in this thread you don't need to add the desktop portal manually. It is in the hyprland nixos-module which makes hyperland work as intended with almost no extra lines. If you have trouble configuring hyprland on NixOS I can recommend you look at fufexan's repo featured at the hyprland wiki or even mine. They are both very complete configurations providing the functionality of a full-fledged desktop environment.

**Comment by sacsbrainz** [comment]
Turns out all i needed to do was to remove gnome
