### ISSUE TITLE
imageio-ffmpeg: declares build-time dependency on wheel. audit why

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#249637]

**Comment by dotlambda** [comment]
I'm confused about this issue. I didn't open it

**Comment by tjni** [comment]
You might have accidentally clicked the "Convert to issue" button:
<img width="1078" alt="Screenshot 2023-08-22 at 10 58 41 AM" src="https://github.com/NixOS/nixpkgs/assets/3806110/39ea57ee-d731-411f-899a-5057763b1a49">

**Comment by dotlambda** [comment]
Possible
