### ISSUE TITLE
zsh option 'interactiveShellInit' not respecting set value

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#24963]
## Issue description

I have set `programs.zsh.interactiveShellInit` to a block of shell script In order to set a few environment variables. I've also set `programs.zsh.promptInit = "";` For some reason the system seems to be appending some more configuration to the end of my settings.

For example, I've explicitly set my `$HISTFILE` variable and it is being overridden by the system. I looked in the /etc/zshrc file and it looks like the settings I have set are there, but there is additional settings below my settings. So it looks like:

```
<my settings from programs.zsh.interactiveShellInit>

<additional settings>

```

Since I have set `programs.zsh.interactiveShellInit` shouldn't all that is in that configuration file be what I have set it to? Looking at [the zsh.nix file](https://github.com/NixOS/nixpkgs/blob/release-17.03/nixos/modules/programs/zsh/zsh.nix) it seems like the only thing in that file should be what I have set `programs.zsh.interactiveShellInit` to. Am I missing something? Could it be something to do with an `environment.etc` option?

### Steps to reproduce

Set   `programs.zsh.interactiveShellInit = ''<zsh options>"`

## Technical details

* System: (NixOS: 17.03.928.69d9061908 (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.928.69d9061908")

**Comment by lheckemann** [comment]
You can use `nixos-option programs.zsh.interactiveShellInit` to see (at the bottom of its output) where the value of the option comes from, which might be helpful.

**Comment by johnramsden** [comment]
@lheckemann as I thought it's declared by:

```
Declared by:
  "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/programs/zsh/zsh.nix"

Defined by:
  "/etc/nixos/users/shells/oh-my-zsh"
  "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/programs/zsh/zsh.nix"
  "/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/programs/command-not-found/command-not-found.nix"
```

So i'm not sure why it's being appended to.

**Comment by lheckemann** [comment]
`/etc/nixos/users/shells/oh-my-zsh` is probably your problems.

**Comment by johnramsden** [comment]
@lheckemann That's my config, this is all it is:

```
{ config, pkgs, ... }:

{
  ##  ZSH Configuration  ##
  programs.zsh.interactiveShellInit = ''
  # My ohmyzsh config ...
  '';

  programs.zsh.promptInit = "";
}
```

**Comment by lheckemann** [comment]
What does your omz config look like?

**Comment by johnramsden** [comment]
[Here](https://github.com/johnramsden/NixOS/blob/master/users/shells/oh-my-zsh/default.nix)

```

{ config, pkgs, ... }:

{
  ##  ZSH Configuration  ##
  programs.zsh.interactiveShellInit = ''
    COMPUTER="atom";
    ZSH=${pkgs.oh-my-zsh}/share/oh-my-zsh/                    # OMZ install
    HISTFILE=$HOME/Computer/Profiles/oh-my-zsh/zsh_history
    ZSH_CUSTOM=$HOME/Computer/Profiles/oh-my-zsh/custom       # OMZ directory
    ZSH_THEME="af-magic"
    DISABLE_AUTO_UPDATE=true
    plugins=(git systemd ruby gem history sudo node npm nvm zsh-autosuggestions )
    source $ZSH/oh-my-zsh.sh
    ## -------- MISC -------- ##
    export XDG_CONFIG_HOME=$HOME/.config
    export ELECTRON_TRASH=kioclient5
    export EDITOR="nano"
    export XENVIRONMENT=$HOME/.Xdefaults
  '';

  programs.zsh.promptInit = "";
}

```

**Comment by lheckemann** [comment]
Looking at the zsh module again it looks like it expects you to set not `programs.zsh.interactiveShellInit` but `environment.interactiveShellInit`, that way the defaults provided by zsh.nix will come before (and be overridden by) your settings. Alternatively, you could set `programs.zsh.interactiveShellInit` to `lib.mkForce (your-settings)`, but in this case most of the functionality provided by the module will be removed.

**Comment by johnramsden** [comment]
@lheckemann Excellent! That did it! `environment.interactiveShellInit` works.
