### ISSUE TITLE
Update request: vikunja-api 0.20.4 → 0.21.0, vikunja-frontend 0.20.5 → 0.21.0

### ISSUE THREAD

**Issue by balacij** [NixOS/nixpkgs#249649]
- Package name: vikunja-api, vikunja-frontend
- Latest released version: 0.20.4, 0.20.5, respectively
- Current version on the unstable channel: 0.20.4, 0.20.5, respectively
- Current version on the stable/release channel: 0.20.4, 0.20.5, respectively
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@leona-ya @mweinelt 

I would love to help out, but I'm struggling to calculate the `vendorSha256` field of updated package. The updated `src` hash for vikunja-api is `sha256-mWWUJzkGtnizP3j4LBWPoqdZluQFTKd0p7OTnsWv8g8=`, and the updated src hash for vikunja-frontend is `sha256-7FnY24B2EjAoMxFnNXBQ9zvbW0F5PPXEfWCs+fH93BI=`.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by mweinelt** [comment]
Updating vikunja-api fails to realize the vendor FOD.

```
code.vikunja.io/api/pkg/version imports
        code.vikunja.io/api/pkg/swagger: no required module provides package code.vikunja.io/api/pkg/swagger; to add it:
        go get code.vikunja.io/api/pkg/swagger
```

I asked in the upstream chat and kolaente mentioned we should use `mage do-the-swag` before building, or use `mage build`.

I won't have time to dig into this in the foreseeable future.

**Comment by kolaente** [comment]
We've changed this again in the code so that now you won't need to generate the swagger docs prior to building. It's not released yet as a stable version so maybe we just skip 0.21.0 and upgrade to 0.22.0 once that's released.

**Comment by balacij** [comment]
Ah, I was going to submit a PR with a patch that contains the swagger docs generated manually, but I think that sounds better. I'll close this PR in favour of waiting for 0.22.0.
