### ISSUE TITLE
Caddyfile gets created differently in unstable compared to 23.05

### ISSUE THREAD

**Issue by savyajha** [NixOS/nixpkgs#249698]
### Describe the bug
I don't know if this is a bug or expected behaviour, but I've found that the caddyfile gets built differently depending on whether I'm using the unstable module or the 23.05 module with a base of 23.05. Specifically, it seems that the location of the contents of `extraConfig` in the caddyfile change.

In 23.05 (caddy version 2.6.x), I find that the contents of the caddyfile are added in the following sequence:

```
globalConfig

extraConfig

Virtual Hosts
```

However, using unstable, it's changed to:

```
globalConfig

Virtual Hosts

extraConfig
```

Now this is a problem because I use `extraConfig` to define a few common variables which are then used by my virtual hosts. Can this behaviour be changed or made explicit? Or can we have a `prependedConfig` option which comes after `globalConfig` but before Virtual Hosts?

### Steps To Reproduce
1. Use the unstable caddy module on a nixos 23.05 installation
2. Have a global config section, an extra Config section, and a few virtual hosts
3. `nixos-rebuild` and then check the way the caddyfile is made. 

### Expected behavior
The caddyfile to be made in the same way as it was in 23.05.

### Notify maintainers
@emilylange - Pinging you because I see that you're the one who updated the package to the 2.7.x series.

### Metadata

```console
[user@system:~]$ nix shell nixpkgs/nixos-23.05\#nix-info --command nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.20230816.b30c686`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `not found`
```

**Comment by emilylange** [comment]
I am unable to reproduce this.
Could you please share a minimal reproducer/code snippet for `services.caddy`?

Thanks!

**Comment by savyajha** [comment]
Update: This only happens when you mix channels, and not when you stick to unstable. I got the chance to try it out right now.

**Comment by emilylange** [comment]
While I am not sure whether this is a general issue deep in the merging order of the nixos module system when using `disabledModules`, I at least know how to workaround it.

You can simply force the order via
```nix
services.caddy.extraConfig = lib.mkBefore (builtins.readFile ./extra-caddy.conf);
```
for now.

I'll probably file an PR tomorrow or so that fixes this in the caddy module itself by using `lib.mkAfter` in https://github.com/NixOS/nixpkgs/blob/49f76fea56b505da7837466b7e54ffddea9dcd06/nixos/modules/services/web-servers/caddy/default.nix#L343

Very interesting issue/edge case. Thanks for reporting!

**Comment by savyajha** [comment]
Thanks for giving me a solution! It works perfectly. I will leave it to you to close this bug report post your PR, if you wish.
