### ISSUE TITLE
Update request: gpu-screen-recorder 1.0.0 (2022-03-23) → 2023-08-15

### ISSUE THREAD

**Issue by dec05eba** [NixOS/nixpkgs#249654]
- Package name: gpu-screen-recorder
- Latest released version: 2023-08-15
- Current version on the unstable channel: 1.0.0 (2022-03-23)
- Current version on the stable/release channel: 1.0.0  (2022-03-23)

The package was created (by somebody else than the author) when the program was made public and at that time it had many bugs that has been long fixed and it only supports a fraction of the functionality that exists upstream. The NixOS package has never been updated since it was added. The package should either be removed or updated, since it's broken in many ways.

(I'm the author of the program and I receive bug reports from the NixOS package that were fixed more than a year and half ago).

**Comment by fabaff** [comment]
> Latest released version: 2023-08-15

Is the repo still located at https://git.dec05eba.com/gpu-screen-recorder/? If so, it looks like that the latest release is [3.0.0](https://git.dec05eba.com/gpu-screen-recorder/tree/project.conf#n4) but I can't find the tag for this.

It up to @babbaj to decide what to do.

**Comment by dec05eba** [comment]
> > Latest released version: 2023-08-15
> 
> Is the repo still located at https://git.dec05eba.com/gpu-screen-recorder/? If so, it looks like that the latest release is [3.0.0](https://git.dec05eba.com/gpu-screen-recorder/tree/project.conf#n4) but I can't find the tag for this.
> 
> It up to @babbaj to decide what to do.

Yes that's the correct repo. There are no tags, the latest release is always the recommended version as there are sometimes new driver bugs that need workarounds.

**Comment by keenanweaver** [comment]
I've got a working build with the latest commit, but can't test on an Nvidia card. It's working for me on an AMD card using all the various switches and recording types. Wayland is working with monitor capture, sound with Pipewire/virtual sinks, etc.. The only downside I can see is since wrapProgram is used, the instructions on the site for saving/stopping replay mode don't work since the program is called '.gpu-screen-recorder' when wrapped, so you have to kill '.gpu-screen-recorder'.

I'm also a new contributor to NixOS, so if there are any tips to make this package better, please let me know.

``` nix
{ stdenv
, lib
, fetchgit
, makeWrapper
, pkg-config
, cudatoolkit
, glew
, libX11
, libXcomposite
, glfw
, libpulseaudio
, ffmpeg
, wayland
, libdrm
, libva
, libcap
, libglvnd
, libXrandr
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "gpu-screen-recorder";
  version = "3.0.0";

  src = fetchgit {
    url = "https://repo.dec05eba.com/gpu-screen-recorder";
    rev = "d6cf3b73549f48bb1a640e6359fc45ee776b7188";
    hash = "sha256-5aUmuf2p7lL28OiLkhT+UX0w+K3Vsf/2uPxydj33+5E=";
  };

  nativeBuildInputs = [
    pkg-config
    makeWrapper
  ];

  buildInputs = [
    glew
    libX11
    libXcomposite
    glfw
    libpulseaudio
    ffmpeg
    wayland
    libdrm
    libcap
    libva
    libglvnd
    libXrandr
  ];

  buildPhase = ''
    ./build.sh
  '';

  installPhase = ''
    install -Dt $out/bin gpu-screen-recorder
    install -Dt $out/bin gsr-kms-server
    wrapProgram $out/bin/gpu-screen-recorder --prefix LD_LIBRARY_PATH : ${libglvnd}/lib --prefix PATH : $out/bin
  '';

  meta = with lib; {
    description = "A screen recorder that has minimal impact on system performance by recording a window using the GPU only";
    homepage = "https://git.dec05eba.com/gpu-screen-recorder/about/";
    license = licenses.gpl3Only;
    maintainers = with maintainers; [ babbaj keenanweaver ];
    platforms = [ "x86_64-linux" ];
  };
})

```

**Comment by keenanweaver** [comment]
@dec05eba Thanks for the notes! I believe these are all doable--I just have to learn how to do it! Going to play around with it and try to make this and the GTK frontend work with all the niceities.

Quick question regarding the root permission: does that also apply for monitor capture mode? Speaking as a user now. Right now I'm using an Arch distrobox on NixOS and doing current window capture 'cause I was pretty annoyed at the password prompt for monitor mode.

**Comment by dec05eba** [comment]
@keenanweaver Yeah the password prompt is specifically for monitor capture, and on wayland there is no window capture option so you dont have any option to avoid the password prompt otherwise.

**Comment by sersorrel** [comment]
that error is probably because `all-packages.nix` passes in (a specific version of) `cudatoolkit`:

```
  gpu-screen-recorder = callPackage ../applications/video/gpu-screen-recorder {
    # rm me as soon as this package gains the support for cuda 11
    inherit (cudaPackages_10) cudatoolkit;
  };
```

also, if you want to keep the binary named `gpu-screen-recorder`, you could try using `makeWrapper` by hand, like is done with wine: https://github.com/NixOS/nixpkgs/blob/39104a4d5755d940517483879a3b06b28ef5ff6d/pkgs/applications/emulators/wine/base.nix#L169-L181

**Comment by keenanweaver** [comment]
Thanks for that, @sersorrel! I've been playing around with it and I'm still undecided on how to go about this. Here are the comparisons

``` nix
  postInstall = ''
    install -Dt $out/bin gpu-screen-recorder gsr-kms-server
    wrapProgram $out/bin/gpu-screen-recorder \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
  '';
```
As described above, this works fine, but the user would need to know the actual process will be called '.gpu-screen-recorder' and will need to adjust accordingly. 

``` nix
  postInstall = ''
    install -Dt $out/bin gpu-screen-recorder gsr-kms-server
    makeWrapper "$out/bin/gpu-screen-recorder" "$out/bin/gpu-screen-recorder-wrapped" \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
  '';
```
This method keeps the original binary named gpu-screen-recorder, but the user will need to run the wrapped binary for it to work, otherwise the PATHs don't get read:
```
Info: audio codec is forcefully set to aac at the moment because of issues with opus/flac. This is a temporary issue
gsr error: gsr_egl_load: failed to load libEGL.so.1, error: libEGL.so.1: cannot open shared object file: No such file or directory
gsr error: failed to load opengl
```

``` nix
  postInstall = ''
    install -Dt $out/bin gpu-screen-recorder gsr-kms-server
    mv $out/bin/gpu-screen-recorder $out/bin/.gpu-screen-recorder
    mv $out/bin/gsr-kms-server $out/bin/.gsr-kms-server
    makeWrapper "$out/bin/.gpu-screen-recorder" "$out/bin/gpu-screen-recorder" \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
    makeWrapper "$out/bin/.gsr-kms-server" "$out/bin/gsr-kms-server" \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
  '';
```
And finally this horrible concotion which is basically just the wrapProgram method again.

Currently leaning towards the second one as nothing upstream would need to be changed aside from a small note that Nix users would need to run `gpu-screen-recorder-wrapped`

Haven't really looked into the module quite yet, but I don't think it'd be too difficult to get working as expected.

Greatly appreciate any feedback!

**Comment by sersorrel** [comment]
would something like this work? then the user still just runs `gpu-screen-recorder`, and the process name remains the same.

```nix
  postInstall = ''
    install -Dt $out/bin gpu-screen-recorder gsr-kms-server
    mkdir $out/bin/.wrapped
    mv $out/bin/gpu-screen-recorder $out/bin/.wrapped/
    makeWrapper "$out/bin/.wrapped/gpu-screen-recorder" "$out/bin/gpu-screen-recorder" \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
  '';
```

(it's maybe not ideal to put the `.wrapped` directory in `$out/bin`, but you get the idea)

**Comment by NateWright** [comment]
Seems like this is a working config with all of your ideas put together.
```
{ stdenv
, lib
, fetchgit
, makeWrapper
, pkg-config
, glew
, libX11
, libXcomposite
, glfw
, libpulseaudio
, ffmpeg
, wayland
, libdrm
, libva
, libcap
, libglvnd
, libXrandr
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "gpu-screen-recorder";
  version = "2023.11.18";

  src = fetchgit {
    url = "https://repo.dec05eba.com/gpu-screen-recorder";
    rev = "5a8900e3c199c5e25a0819992f002614867c924e";
    hash = "sha256-it+Ur/pUCGo8OyA8ih2CZy16KqrUcfQRjCQO1auWR8c=";
  };

  nativeBuildInputs = [
    pkg-config
    makeWrapper
  ];

  buildInputs = [
    glew
    libX11
    libXcomposite
    glfw
    libpulseaudio
    ffmpeg
    wayland
    libdrm
    libcap
    libva
    libglvnd
    libXrandr
  ];

  buildPhase = ''
    ./build.sh
  '';

  postInstall = ''
    install -Dt $out/bin gpu-screen-recorder gsr-kms-server
    mkdir $out/bin/.wrapped
    mv $out/bin/gpu-screen-recorder $out/bin/.wrapped/
    makeWrapper "$out/bin/.wrapped/gpu-screen-recorder" "$out/bin/gpu-screen-recorder" \
    --prefix LD_LIBRARY_PATH : ${libglvnd}/lib \
    --prefix PATH : $out/bin
  '';


  meta = with lib; {
    description = "A screen recorder that has minimal impact on system performance by recording a window using the GPU only";
    homepage = "https://git.dec05eba.com/gpu-screen-recorder/about/";
    license = licenses.gpl3Only;
    maintainers = with maintainers; [ babbaj keenanweaver ];
    platforms = [ "x86_64-linux" ];
  };
})
```
