### ISSUE TITLE
`apx` is not working on NixOS

### ISSUE THREAD

**Issue by coxde** [NixOS/nixpkgs#249727]
### Describe the bug
When I run `apx` on NixOS, the output shows `Unsupported setup detected, set a default distro and package manager in the config file`.

### Steps To Reproduce
1. run `apx` in terminal.
2. output shows `Unsupported setup detected, set a default distro and package manager in the config file`.

### Expected behavior
It should find the config.json file in $out/etc/apx/config.json and run as expected.

### Additional context
I'm not very familiar with NixOS, but it seems that apx will look for config.json in /usr/share/apx/. But NixOS won't follow FHS, the config.json is located in $out/etc/apx/config.json. Related issue: https://github.com/Vanilla-OS/apx/issues/238

### Notify maintainers
Thank you! @dit7ya @fabaff

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.10, NixOS, 23.11 (Tapir), 23.11.20230816.caac0eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
Fixed in #266262
