### ISSUE TITLE
Package request: stacer

### ISSUE THREAD

**Issue by ObvMamut** [NixOS/nixpkgs#249814]
**Project description**

System optimization and monitoring tool.

**Metadata**

* homepage URL: https://github.com/oguzhaninan/Stacer
* source URL: https://github.com/oguzhaninan/Stacer
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by dawidd6** [comment]
It seems like the project was abandoned https://github.com/oguzhaninan/Stacer/commit/a44d0565a05c996b1058f950f1d308e1964c8320

**Comment by dit7ya** [comment]
Stacer is in nixpkgs already - https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=stacer
