### ISSUE TITLE
CAVA built without Pipewire support

### ISSUE THREAD

**Issue by colin-heffernan** [NixOS/nixpkgs#249876]
### Describe the bug
CAVA is built without support for Pipewire, meaning that it cannot use Pipewire as an input to visualize audio.

### Steps To Reproduce
1. Install CAVA.
2. Set the input to Pipewire. A minimal config is as follows:
```
[input]
method = pipewire
source = alsa:pcm:1
```
3. Launch CAVA

### Expected behavior
CAVA should launch and visualize the audio using Pipewire.

### Screenshots
Not exactly a screenshot, but here's my terminal output verbatim:
```console
~ ❯ cava
shader file is empty, creating default shader file
shader file is empty, creating default shader file
shader file is empty, creating default shader file
Error loading config. cava was built without 'pipewire' input support
```

### Additional context
I tried using `overrideAttrs` to add `pipewire` to the `buildInputs`, but the build failed after failing to find `spa/param/audio/format-utils.h`.

### Notify maintainers
@offlinehacker @mirrexagon 

### Metadata
```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.11 (Tapir), 23.11.20230816.caac0eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/hwp2x4k2p6ar2xpzbmjbl278sqxmxv0s-source`
```

**Comment by majiru** [comment]
I believe I have addressed this with this https://github.com/NixOS/nixpkgs/pull/250025, could you verify that it fixes the problem for you?

**Comment by NotAShelf** [comment]
seems to fix the problem for me

**Comment by maglore9900** [comment]
I just added unstable cava version 0.9.1 to my system and I get the same error. What is the fix exactly?

**Comment by NickCao** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/254805
