### ISSUE TITLE
Update request: BlueJ 5.1.0 → 5.2.0

### ISSUE THREAD

**Issue by TristanAppDev** [NixOS/nixpkgs#249811]
- Package name: bluej
- Latest released version: 5.2.0

- Current version on the unstable channel: 5.1.0
- Current version on the stable/release channel: 5.1.0

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@chvp 
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by chvp** [comment]
On it. I sadly still haven't found a good way of keeping up with releases, and I only actively use it myself from the end of september through to december.

**Comment by chvp** [comment]
PR at #249926
