### ISSUE TITLE
Update request: raycast 1.55.2 → 1.57.1

### ISSUE THREAD

**Issue by tnxz** [NixOS/nixpkgs#249875]
- Package name: raycast
- Latest released version: 1.57.1

- Current version on the unstable channel: 1.55.2
- Current version on the stable/release channel: 1.51.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@lovesegfault @stepbrobd
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by stepbrobd** [comment]
Closing as the PR has merged
