### ISSUE TITLE
Broken Haskell package `arion-compose` on `haskell-updates` branch

### ISSUE THREAD

**Issue by peterbecich** [NixOS/nixpkgs#249868]
### Describe the bug
On the `haskell-updates` branch:

```
$ nix build .#haskellPackages.arion-compose
error:
       … in the left operand of the update (//) operator

         at /nix/store/yziw8dhvlc0x9bscqiap5ghi871s9vvy-source/pkgs/development/haskell-modules/lib/compose.nix:40:7:

           39|     mkDerivation = drv: (args.mkDerivation drv).override f;
           40|   })) // {
             |       ^
           41|     overrideScope = scope: overrideCabal f (drv.overrideScope scope);

       error: assertion '((super).arion-compose.version == "0.2.0.0")' failed

       at /nix/store/yziw8dhvlc0x9bscqiap5ghi871s9vvy-source/pkgs/development/haskell-modules/configuration-common.nix:241:30:

          240|   # 2023-07-27: Allow base-4.17
          241|   arion-compose = dontCheck (assert super.arion-compose.version == "0.2.0.0"; doJailbreak super.arion-compose);
             |                              ^
          242|
```

On `nixpkgs-unstable` and `master` it is fine

### Steps To Reproduce
```
nix build github:nixos/nixpkgs/haskell-updates#haskellPackages.arion-compose
```

### Expected behavior

Command should succeed like
```
$ nix build .#haskellPackages.text_2_0_2   
```

### Additional context

https://hackage.haskell.org/package/arion-compose

https://search.nixos.org/packages?channel=unstable&show=haskellPackages.arion-compose&from=0&size=50&sort=relevance&type=packages&query=arion-compose

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-11-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(peterbecich): `"nixos, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/peterbecich/.nix-defexpr/channels/nixpkgs`


```

**Comment by peterbecich** [comment]
Notifying maintainer @roberth , thank you

**Comment by peterbecich** [comment]
PR to `haskell-updates`: https://github.com/NixOS/nixpkgs/pull/249870

**Comment by roberth** [comment]
Looks like my upstream fix has made its way to the update branch and the Haskell team has already taken care of the cleanup. They use this pattern to help keep the code clean.

Thanks for taking the time to help with the Haskell updates! That's much appreciated.

**Comment by peterbecich** [comment]
Thanks @roberth , here are some additional fixes for `hls-plugin-api`, `lsp` 2, and `ghcide`: https://github.com/NixOS/nixpkgs/pull/250095
I don't know if these have also been fixed upstream

**Comment by roberth** [comment]
That's great. I don't normally do these reviews but I think I had something helpful to say anyway. Thanks!
