### ISSUE TITLE
Update request: libsndfile 1.2.0 → 1.2.2

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#249834]
- Package name: libsndfile
- Latest released version: 1.2.2
- Current version on the unstable channel: 1.2.0
- Current version on the stable/release channel: 1.2.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@lovek323 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by LudovicoPiero** [comment]
#249904, idk why it didn't automatically close the issue.

**Comment by luzpaz** [comment]
Thanks!
