### ISSUE TITLE
Build failure: nvfetcher

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#249962]
### Steps To Reproduce

1. `NIXPKGS_ALLOW_BROKEN=1 nix-build -A nvfetcher`

### Build log

Relevant bits:

```
       > Error: Setup: Encountered missing or private dependencies:
       > aeson >=1.5.6 && <2.1
```

### Additional context

Marked broken in 72573db36b51713115046b1831873b9da583017c.

### Notify maintainers

@berberman 

### Metadata

https://hydra.nixos.org/build/231635785

**Comment by berberman** [comment]
I just made a new release that should compile: https://hackage.haskell.org/package/nvfetcher-0.6.2.0

**Comment by GaetanLepage** [comment]
Thanks for fixing @amarshall !
Have you made a PR to ship the fix upstream ?

**Comment by GaetanLepage** [comment]
> @GaetanLepage I haven’t fixed anything. There is already a fix upstream (see above by berberman). No update in nixpkgs yet, and I’m not familiar enough with haskellPackages to know how to properly update just one package (I only see docs about updating all of them), I just hacked on the autogenerated file for testing.

Ok makes sense !
Let's wait for the patch then :)

**Comment by bestlem** [comment]
Any progress on this?

**Comment by teutat3s** [comment]
I guess you can follow https://github.com/NixOS/nixpkgs/pull/249708 for updates.

**Comment by cdepillabout** [comment]
Just a heads up, https://github.com/NixOS/nixpkgs/pull/249708 won't contain nvfetcher-0.6.2.0.  That update should happen in the next haskell-updates PR.

**Comment by chayleaf** [comment]
I suppose this should be solved by #255037

**Comment by cdepillabout** [comment]
I've marked nvfetcher as non-broken in 4fec13e83269, which is included in https://github.com/NixOS/nixpkgs/pull/255037.

**Comment by chayleaf** [comment]
this isn't merged yet though
