### ISSUE TITLE
Package request: WebCord

### ISSUE THREAD

**Issue by lisbonjoker** [NixOS/nixpkgs#249934]
A Discord and SpaceBar electron-based client implemented without Discord API.
- Hardened for privacy
- Follows the best security practises
- Customizable
- ARM-friendly and Linux mobile support

**Metadata**

* homepage URL: NaN
* source URL: https://github.com/SpacingBat3/WebCord
* license: MIT
* platforms: Linux, MAC and Windows

**Comment by Laurent2916** [comment]
Hi @lisbonjoker !

The Webcord package is already available in nixpkgs.
You can search it using [search.nixos.org](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=webcord).

Closing the issue now. Thanks !
