### ISSUE TITLE
tpm_crb: probe of MSFT0101:00 failed with error 378

### ISSUE THREAD

**Issue by CnTeng** [NixOS/nixpkgs#250166]
### Describe the bug
I use tpm + luks, but recently when the kernel updating to 6.4.11, the `tpm_crb` can't find `tpm` devices. 
And, if I switch to old kernel like 6.1, it can't work too.

### Steps To Reproduce
1. Use the latest unstable
2.
```nix
  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "tpm"
        "tpm_tis"
        "tpm_crb"
      ];
      systemd.enable = true;
    };

    tmp.useTmpfs = true;
  };
```

### Expected behavior
`tpm` work correctly.

### Screenshots
![图片](https://github.com/NixOS/nixpkgs/assets/56501688/3cad3f0a-a2c7-4798-9a46-00c7391edcb1)
![图片](https://github.com/NixOS/nixpkgs/assets/56501688/fe4b2707-c65a-48d4-ae05-49bcd6c1dae8)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(yufei): `""`
 - nixpkgs: `/nix/store/5mj1vfslaf052b8s9nnbz31fb2l1qwdi-source`
```

**Comment by keithpl** [comment]
I have the same exact behavior with 6.4.11 and 6.1.46, however I am using Arch Linux. I imagine this is not a NixOS specific problem.

**Comment by nitro424** [comment]
Same here with Fedora 38 after latest Kernel (6.4.11) update.

**Comment by panda2134** [comment]
Same here with nixOS unstable and kernel version 6.1.46.

**Comment by Cryolitia** [comment]
Also on my cumputer

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.46, NixOS, 23.11 (Tapir), 23.11pre515819.8ecc900b2f69`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(cryolitia): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by CoelacanthusHex** [comment]
> I use tpm + luks, but recently when the kernel updating to 6.4.11, the `tpm_crb` can't find `tpm` devices. And, if I switch to old kernel like 6.1, it can't work too.

All bugfix patches will be backported to all maintenance branches, so the latest version of both the 6.4 and 6.1 branches has the same buggy commit. If you meet some bug and want to roll back to dig out the problem, you should roll back to the last working version you have used, rather than a version that looks older.

**Comment by CnTeng** [comment]
> > I use tpm + luks, but recently when the kernel updating to 6.4.11, the `tpm_crb` can't find `tpm` devices. And, if I switch to old kernel like 6.1, it can't work too.
> 
> All bugfix patches will be backported to all maintenance branches, so the latest version of both the 6.4 and 6.1 branches has the same buggy commit. If you meet some bug and want to roll back to dig out the problem, you should roll back to the last working version you have used, rather than a version that looks older.

Ok, thanks

**Comment by nadimkobeissi** [comment]
This exact error is happening on openSUSE too:

```
Linux archangel.home 6.4.11-1-default #1 SMP PREEMPT_DYNAMIC Thu Aug 17 04:57:43 UTC 2023 (2a5b3f6) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Lyndeno** [comment]
Out of curiosity, what hardware is everyone using? I thought this was causing my boot failure on my XPS 9560, but it turns out it was a different kernel bug causing boot to fail.
My specs:
XPS 9560
i7-7700HQ

Not quite sure atm how to get TPM model.

**Comment by adamlwgriffiths** [comment]
Asrock z370 with i5-8600K

The issue prevented me booting my Windows 11 VM (running as close to the "metal" as possible with GPU Passthrough) after updating to 23.05 (and emulated TPM doesn't work ootb).

I had to manually apply the above referenced PR to my kernel last night after spending a number of hours tracking down the source of the problem (single-GPU passthrough makes this a bit difficult). After an hour or so compilation it was resolved. 
I'm sure there are others out there with issues that haven't identified what is causing it.

**Comment by Cryolitia** [comment]
I'm using HP Gaming Pavilion - 15 with i7-9750H inside.

**Comment by Lyndeno** [comment]
Hmm okay:

My XPS 9560 boots fine with TPM decryption. Suspending and resuming does not got any errors with the TPM.

My desktop with Ryzen 5950X and Asus Prime X570-Pro boots fine with TPM decryption. I do not have suspend enabled on that machine due it's home-server setup, so I cannot test.

**Comment by panda2134** [comment]
I use i9-13900k, with TPM included in the CPU.

**Comment by kevinquillen** [comment]
Still happens to me under 6.4.15.

>  Sep 13 19:08:29 fedora kernel: tpm_crb: probe of MSFT0101:00 failed with error 378

**Comment by Nick1296** [comment]
I am sorry to reopen this issue but I have a very similar problem on nixos 23.11 on a Raspberry Pi 4.
The module `tmp-crb` is not found on kernel 6.1.21.2023.0405 (the current version of linux_rpi4 in the nixos23.11 branch)
As a workaround for now I am using the following code to allow missing kernel modules when rebuilding the kernel:
```
  nixpkgs.overlays = [
    (final: super: {
      makeModulesClosure = x:
        super.makeModulesClosure (x // { allowMissing = true; });
    })
  ];
```

I am not 100% sure that this is a nixpkgs issue, but I could not find any references to this problem on the Raspberry Pi 4 for now.
