### ISSUE TITLE
Build failure: julia_19

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#250172]
### Steps To Reproduce

1. `nix build --no-link  --accept-flake-config  --print-build-logs github:NixOS/nixpkgs#legacyPackages.aarch64-linux.julia_19` 

### Build log
[log](https://gist.github.com/573/53113baba745d842a9617d718042db21)

### Additional context

I came up with the idea of building julia_19 for that platform as a possible resort as the binary artifact does not work as is on my hardware, causing a `ReadOnlyMemoryError()`, see also [this discussion](https://github.com/t184256/nix-on-droid/discussions/262).

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90.1-microsoft-standard-WSL2, NixOS, 22.11 (Raccoon), 22.11.20230417.de66115`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/bmyw96kdilalipziklp47rva12f0fhbz-source`
```

**Comment by NickCao** [comment]
The failure is also reproducible on hydra: https://hydra.nixos.org/job/nixpkgs/trunk/julia_19.aarch64-linux, looks like the flaky tests that have been plaguing us for a long time.
