### ISSUE TITLE
Build failure: pysideShiboken

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#250106]
### Steps To Reproduce

1. build `python311Packages.pysideTools` or `python311Packages.pysideShiboken`

### Build log

https://gist.github.com/GetPsyched/867ff381a5fb2ff43ecd5dadcb961329

### Additional context

`pysideTools` breaks at build time (when put in `buildInputs`)

### Notify maintainers

@chaoflow (removed from maintainers)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.42, NixOS, 23.11 (Tapir), 23.11.20230802.66aedfd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/store/vr3d056k1n1r8fmm9qkz3d1r4cj03bza-source`
```

**Comment by GetPsyched** [comment]
Help?

**Comment by GetPsyched** [comment]
🚶🏻

**Comment by bjornfor** [comment]
```
$ cd nixpkgs
$ git checkout master
$ git pull
$ nix-build -A python311Packages.pysideTools
error: attribute 'pysideTools' in selection path 'python311Packages.pysideTools' not found
$ nix-build -A python311Packages.pysideShiboken
error: attribute 'pysideShiboken' in selection path 'python311Packages.pysideShiboken' not found
```

Please provide a reproducer.

**Comment by GetPsyched** [comment]
So weird. I swear those packages existed before. Anyway, I switched to using `pyside2-tools` which seem to provide the executables I needed. Thanks.

**Comment by bjornfor** [comment]
Maybe they did. A lot can happen in the master branch in a few weeks 😀

**Comment by GetPsyched** [comment]
Right, haha.
