### ISSUE TITLE
Bottles: Doesn't complete setup when installed

### ISSUE THREAD

**Issue by saikatdas0790** [NixOS/nixpkgs#250159]
### Describe the bug
When the Bottles package starts for the first time, it's supposed to perform some post startup installation for the first time. It gets stuck on this step and keeps coming back to this screen.
![image](https://github.com/NixOS/nixpkgs/assets/7412443/4cb986f8-fd1e-4005-8d1d-03567c7835de)
Essentially clicking on Continue just brings it back to this same screen.

### Steps To Reproduce
1. Open bottles for the first time
2. Click on "Continue"
3. Wait for some time for it to finish processing and come back to the same screen

### Expected behavior
Bottles should start letting the user lands on the bottles page

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/7412443/4cb986f8-fd1e-4005-8d1d-03567c7835de)

### Additional context
Additionally, starting Bottles from the terminal gives us logs of the issue and it shows us this:
![image](https://github.com/NixOS/nixpkgs/assets/7412443/f450709d-0e35-499a-88db-829ef7fc1f75)

### Notify maintainers

@khaneliman @SuperSamus @psydvl @SCOTT-HAMILTON 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[saikat@pc-nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.11 (Tapir), 23.11pre514857.caac0eb6bdca`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
Cannot reproduce.
Maybe try deleting its data, then try again? (It's located in `$XDG_DATA_HOME/bottles`)

**Comment by saikatdas0790** [comment]
@SuperSamus This happens on a fresh install of NixOS that is using the `unstable` channel

I can make the problem go away by installing `bottles-unwrapped` package, uninstalling `bottles-unwrapped` and then installing the normal `bottles` package.

I think the normal `bottles` package is unable to install/locate the underlying `dxvk`, `vkd3d`, etc.

Also, I can see that `$XDG_DATA_HOME` is not set for me. Any other ideas?

**Comment by SuperSamus** [comment]
`$XDG_DATA_HOME` defaults to `~/.local/share`.

**Comment by saikatdas0790** [comment]
Deleted the entire `bottles` folder there and restarted but still seeing this:
![image](https://github.com/NixOS/nixpkgs/assets/7412443/fdfa2f74-84ae-4b32-a1ba-5fead16d251e)

Any idea why I'm getting those "Could not get index for installers repository" error?

**Comment by saikatdas0790** [comment]
@SuperSamus Okay, I think it might be on the Bottles devs.

Quite a few people complaining about it

https://github.com/bottlesdevs/Bottles/issues/2421

I believe they might be using Cloudflare to act as a CDN for some of their config and runtime files and it might be rejecting requests from certain networks/countries.

That is what might be causing this..

**Comment by saikatdas0790** [comment]
@SuperSamus 
Okay, got it to install by using a VPN that connects to the Netherlands.

Quite strange.

![image](https://github.com/bottlesdevs/Bottles/assets/7412443/c1b7488b-447c-4c21-8296-890d0a09e8d2)

**Comment by whoslucifer** [comment]
Fixed this by installing vulkan-tools which has most dependencies of bottles then rebooted
