### ISSUE TITLE
Bpftune crashes when suspending

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#250137]
### Describe the bug
When the computer suspends bpftune crashes.

### Steps To Reproduce
Press the power button to suspend the laptop.
The bpftune service stops.

### Additional context
```
❯ journalctl -u bpftune.service
Aug 19 10:10:50 nixos-dell systemd[1]: Started BPF-based auto-tuning of system parameters.
Aug 19 10:10:50 nixos-dell bpftune[7957]: bpftune works fully
Aug 19 10:10:50 nixos-dell bpftune[7957]: bpftune supports per-netns policy (via netns cookie)
Aug 19 10:11:41 nixos-dell bpftune[7957]: ring_buffer__poll: Interrupted system call
Aug 19 10:11:43 nixos-dell systemd[1]: bpftune.service: Deactivated successfully.
Aug 19 10:11:43 nixos-dell systemd[1]: bpftune.service: Consumed 4.180s CPU time, no IO, no IP traffic.

```
### Notify maintainers

 @NickCao 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20230805.5faab29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/run/current-system/nixpkgs`

```

**Comment by NickCao** [comment]
I suspect this could by an upstream issue, may you open an issue at https://github.com/oracle/bpftune

**Comment by Tungsten842** [comment]
> I suspect this could by an upstream issue, may you open an issue at https://github.com/oracle/bpftune

Done https://github.com/oracle/bpftune/issues/53

**Comment by Tungsten842** [comment]
Fixed in the latest version: https://github.com/NixOS/nixpkgs/pull/250727
