### ISSUE TITLE
Package request: typora

### ISSUE THREAD

**Issue by v411e** [NixOS/nixpkgs#250200]
**Project description**

Typora is a distraction free markdown editor.
Developed by @abnerlee 

**Metadata**

* homepage URL: https://typora.io/
* source URL: Not open source :( Github Organization: https://github.com/typora
* license: https://support.typora.io/License-Agreement/
* platforms: [linux](https://typora.io/#linux), darwin

**Comment by v411e** [comment]
Hmmm I found this issue: https://github.com/NixOS/nixpkgs/issues/138329

Looks like the *not open source* thing is a problem here

**Comment by lelgenio** [comment]
Just checked, It seems to work fine with `steam-run`, so using buildFHSEnv should work.       
As https://github.com/NixOS/nixpkgs/issues/138329#issuecomment-1562284473 says, there's nothing preventing this from being present in nixpkgs, as long as it works.
