### ISSUE TITLE
Package request: yambar-hyprland-wses

### ISSUE THREAD

**Issue by LiamKearn** [NixOS/nixpkgs#250221]
**Project description**

Enable [Yambar](https://codeberg.org/dnkl/yambar) to show [Hyprland](https://hyprland.org/) workspaces.

**Metadata**

* homepage URL: https://github.com/jonhoo/yambar-hyprland-wses
* source URL: https://github.com/jonhoo/yambar-hyprland-wses
* license: mit || apache
* platforms: linux

**Comment by LudovicoPiero** [comment]
I'm using Yambar on the unstable version with the [example configuration](https://codeberg.org/dnkl/yambar/src/branch/master/examples/configurations/laptop.conf) + https://codeberg.org/dnkl/yambar/issues/296. It's displaying workspaces correctly.

**Comment by LiamKearn** [comment]
@LudovicoPiero Thank you, didn't think to check unstable :~)

**Comment by LiamKearn** [comment]
Ah I think I forgot what this issue was about, I'm looking specifically for packaging of a rust that *listens* for workspace info from hyprland's IPC.

**Comment by LudovicoPiero** [comment]
Alright, I'm currently working on it. 
![image](https://github.com/NixOS/nixpkgs/assets/44255157/26a7f93b-8d7a-44db-a2ba-569013f972aa)

**Comment by LiamKearn** [comment]
@LudovicoPiero TYVM!
