### ISSUE TITLE
Reorganization of "altcoins"

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#25025]
It looks like the "altcoins" set [originated](https://github.com/NixOS/nixpkgs/pull/1375) as a set of Bitcoin derivations with slightly different parameters, but eventually started to contain a bunch of cryptocurrency-related things.

People (myself included) end up submitting patches like [this one](https://github.com/NixOS/nixpkgs/pull/24819/files) with a useless layer of indirection:

* `pkgs/applications/altcoins/default.nix`

      ethrun = callPackage ./ethrun.nix { };

* `pkgs/top-level/all-packages.nix`

      ethrun = self.altcoins.ethrun;

Also the name is rather a misnomer. There are some cryptocurrency-related tools in here (or not in here yet but that belong grouped with these packages), not just the "coin" nodes themselves. And I believe some would vehemently disagree with the classification of Ethereum as an "altcoin".

So I propose we:

* Rename `pkgs/applications/altcoins` to `pkgs/applications/cryptocurrency`
* Move everything from `pkgs/applications/altcoins/default.nix` into `pkgs/top-level/all-packages.nix`
* Move various packages into `pkgs/applications/cryptocurrency`:
  * `pkgs/tools/misc/libbitcoin` - includes the `bx` command-line tool for Bitcoin-related things
  * `pkgs/applications/misc/qtbitcointrader` - Bitcoin trading client
  * `pkgs/tools/security/secp256k1` - technically isn't *specifically* cryptocurrency-related, but it's the elliptic curve popularized by Bitcoin and the library is maintained by bitcoin-core
  * `pkgs/servers/trezord` - daemon for using a Bitcoin hardware wallet
  * `pkgs/applications/misc/vanitygen` - a Bitcoin vanity address generator
  * `pkgs/applications/misc/electrum` - a Bitcoin wallet
  * `pkgs/applications/misc/cgminer` - a Bitcoin GPU miner

**Comment by matthewbauer** [comment]
Sounds pretty reasonable. We do have the related problem that ```all-packages.nix``` has gotten really huge. I don't know of a good solution to it but probably we'll need to split up in some way. Anyway, I don't think 10-20 extra lines is going to make anything much worse.

I do find the naming of some of the directories a little hard to remember. For instance games go in ```pkgs/games```, but emulators go in ```pkgs/misc/emulators```. Both emulators and games are almost always considered "applications" but they don't live in ```pkgs/applications``` even though we even have a directory names ```pkgs/applications/misc````. Does anyone know of any standard for directory names in nixpkgs? I couldn't find anything.

**Comment by chris-martin** [comment]
I also have thoughts on the larger organization problem, but I'm hoping to keep the scope of this issue more narrow :)

**Comment by koenigmaximilian** [comment]
I suggest renaming it to "blockchain" or "blockchains" instead of "cryptocurrency", since not every blockchain is used as a currency and I see no reason to differentiate between currencies and non-currencies.

**Comment by chris-martin** [comment]
I can agree with that, yeah. The meaning of "blockchain" has gotten a bit overloaded but I think it's the word most people will associate with this category of software.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by jb55** [comment]
ACK, I get triggered evertime I see `altcoins.bitcoin` or `altcoins.clightning`

we should just do away with the attrset entirly and just categorize it like everthing else in nixpkgs, in a specific folder like `blockchains` or `databases`?

**Comment by mmahut** [comment]
@jb55 +1 for ```blockchains```, I guess that technology will only grow.
