### ISSUE TITLE
Waydroid module needs ashmem

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#250302]
### Describe the bug
When trying to add Waydroid, I got this assertion
```
error:
       Failed assertions:
       - CONFIG_ANDROID_BINDER_IPC is not enabled!
       - CONFIG_ANDROID_BINDERFS is not enabled!
       - CONFIG_ASHMEM is not enabled!
```

### Steps To Reproduce
1. Add `virtualisation.waydroid.enable = true;` on NixOs 23.05

### Expected behavior
Config should work

### Additional context
Using [nixos-apple-silicon](https://github.com/tpwrules/nixos-apple-silicon) for Apple M1 Pro support.

### Notify maintainers

@eclairevoyant

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.3.0-asahi, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
*Yes, I know it says 23.11pre-git but I am on NixOS 23.05 in my Flake.*

**Comment by vs49688** [comment]
If you're using `nixos-apple-silicon`, you'd be using their kernel. They have their own kernel config, it's not using nixpkgs's:
https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/linux-asahi/config

This bug should be filed there.

**Comment by RossComputerGuy** [comment]
@vs49688 The problem goes a bit beyond `nixos-apple-silicon`'s kernel. `ashmem` was dropped in kernel 5.18 and yet the Waydroid module mentions this but nobody has changed it.

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/virtualisation/waydroid.nix#L37

**Comment by RossComputerGuy** [comment]
Tried enabling the needed config options with this:
```nix
  boot.kernelPatches = [{
    name = "waydroid";
    patch = null;
    extraStructuredConfig = with lib.kernel; {
      ANDROID_BINDER_IPC = yes;
      ANDROID_BINDERFS = yes;
      ANDROID_BINDER_DEVICES = "binder,hwbinder,vndbinder";
    };
  }];
```

Same assertion error, checked `config.boot.kernelPackages.kernel.config.isSet` with the required config and all return false on `x86_64` with the stock kernel and `aarch64` with the Asahi kernel. Might not be as simple as just enabling the option.

**Comment by Angraman** [comment]
> @vs49688 The problem goes a bit beyond `nixos-apple-silicon`'s kernel. `ashmem` was dropped in kernel 5.18 and yet the Waydroid module mentions this but nobody has changed it.
> 
> https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/virtualisation/waydroid.nix#L37

Have you tried to use ashmem as described in wiki?

**Comment by RossComputerGuy** [comment]
@Angraman No because the kernel config system in Nixpkgs would not be able to detect that.

**Comment by eclairevoyant** [comment]
Yeah these are assertions thrown during evaluation. I've also not yet narrowed down the cause, as even with the default latest kernel, ASHMEM is not set but assertion doesn't fail

**Comment by eclairevoyant** [comment]
I mean, I could PR to limit the ASHMEM check to below 5.18, but that doesn't help the remaining two assertions 🤔

**Comment by RossComputerGuy** [comment]
`ASHMEM` is set only when the kernel version is between 5.0 and 5.18 as defined in [Nixpkgs here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/common-config.nix#L1025). My non-Asahi stock NixOS system is 6.1.43 and my Asahi NixOS system is 6.3.0. I doubt this is an Asahi NixOS specific problem and might more be of Nixpkgs isn't picking up the config right.

**Comment by Angraman** [comment]
> `ASHMEM` is set only when the kernel version is between 5.0 and 5.18 as defined in [Nixpkgs here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/common-config.nix#L1025). My non-Asahi stock NixOS system is 6.1.43 and my Asahi NixOS system is 6.3.0. I doubt this is an Asahi NixOS specific problem and might more be of Nixpkgs isn't picking up the kernel config right.
> 
> Plus I did set other kernel config like `ANDROID_BINDER_IPC` to `y` (as mentioned earlier) which the error mentions needing to be set. Despite it being set, it still throws the error saying that option isn't set but it is. So just "enabling ashmem" would not work, especially since `ASHMEM` was removed from the kernel in 5.18 which is in that version's changelog.

memfd, supposed ashmem replacement for 5.18+ doesn't work on mac m1-2 i get properly?

**Comment by RossComputerGuy** [comment]
If memfd has to do with the config option `CONFIG_MEMFD_CREATE`, then it should work on M1 since it's already enabled.

**Comment by Angraman** [comment]
> If memfd has to do with the config option `CONFIG_MEMFD_CREATE`, then it should work on M1 since it's already enabled.

In wiki it says you need to tell waydroid to use memfd, in /var/lib/waydroid/waydroid_base.prop

https://nixos.wiki/wiki/WayDroid

**Comment by RossComputerGuy** [comment]
But how do I change that when I can't even enable Waydroid in the first place?

**Comment by Angraman** [comment]
> But how do I change that when I can't even enable Waydroid in the first place?

Have you tried to create that file first and then try to enable that option maybe?

**Comment by RossComputerGuy** [comment]
Isn't that a file inside the container? I can't even make it without Waydroid enabled. Plus how would that fix the error coming from NixOS? I'm using a Flake so there's no way for it to purely get to that file.

**Comment by eclairevoyant** [comment]
> > But how do I change that when I can't even enable Waydroid in the first place?
> 
> Have you tried to create that file first and then try to enable that option maybe?

This is not how nix nor the module system works. Creating some random file on the filesystem does not influence evaluation, and has nothing to do with the assertions in https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/virtualisation/waydroid.nix#L37. If you have another idea, fine, but let's drop this idea about enabling memfd via some random file in `/var/lib`.

The wiki is also full of nonsense, so let's not bring it into the discussion.

**Comment by CajuM** [comment]
@RossComputerGuy there seems to be something weird about nixos-apple-silicon's kernel. It does not parse `extraStructuredConfig`. But it does use `extraConfig` https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/linux-asahi/default.nix#L41-L42. Concerning ASHMEM, I think we can remove the check and replace it with MEMFD_CREATE. That may be a bit paranoid because it's enabled by default on all NixOS kernels newer than v4.18

**Comment by RossComputerGuy** [comment]
```nix
  boot.kernelPatches = [{
    name = "waydroid";
    patch = null;
    extraConfig = ''
      ANDROID_BINDER_IPC y
      ANDROID_BINDERFS y
      ANDROID_BINDER_DEVICES binder,hwbinder,vndbinder
      CONFIG_ASHMEM y
      CONFIG_ANDROID_BINDERFS y
      CONFIG_ANDROID_BINDER_IPC y
    '';
  }];
```
I got it to not assert now.
