### ISSUE TITLE
admadl-sdk: required file ADL_SDK_6.0.zip is no longer available for download

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#25033]
`pkgs/development/misc/amdadl-sdk` requires `ADL_SDK_6.0.zip` from http://developer.amd.com/tools-and-sdks/graphics-development/display-library-adl-sdk/, but the oldest version available to download from that page is `7.0`.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by Artturin** [comment]
package not in nixpkgs anymore
