### ISSUE TITLE
flatpak no launch some apps after update

### ISSUE THREAD

**Issue by tredeneo** [NixOS/nixpkgs#250451]
### Describe the bug
after update flatpak (nix package), the desktop file is not update the new flatpak location. flatpaks apps after update works

### Steps To Reproduce
install flatpak apps in user
update flatpak package

### Expected behavior
open app via menu

### Additional context
example with filelight without update

```
$org.kde.filelight
/home/dnl/.local/share/flatpak/exports/bin/org.kde.filelight: linha 2: /nix/store/c26251y1a8ndncj92qjmx525m1vz1pjs-flatpak-1.14.4/bin/flatpak: No such file or directory
```
desktop file
```
#!/bin/sh
exec /nix/store/c26251y1a8ndncj92qjmx525m1vz1pjs-flatpak-1.14.4/bin/flatpak run --branch=stable --arch=x86_64 org.kde.filelight "$@"
```

steam (flatpak) after update

```
#!/bin/sh
exec flatpak run --branch=stable --arch=x86_64 com.valvesoftware.Steam "$@"
```

is there way update automatic desktop file without reinstall all not updated apps?
without ```flatpak repair --reinstall-all --user``` 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.1-zen1, NixOS, 23.05 (Stoat), 23.05.2918.4cdad15f34e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(dnl): `"home-manager, nixpkgs"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/home/dnl/.nix-defexpr/channels/nixpkgs`

**Comment by vlinkz** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/222678 on the latest nixos-unstable releleases. Now the desktop file just uses `flatpak` without an absolute path to the Nix store.
