### ISSUE TITLE
Package request: python310Packages.pygame-ce

### ISSUE THREAD

**Issue by dtasada** [NixOS/nixpkgs#250417]
**Project description**

pygame - Community Edition is a FOSS Python library for multimedia applications (like games). Built on top of the excellent SDL library. I have in fact attempted to package it on my own but I haven't quite been able to get it to work, so I figured in the meanwhile I'd make a request.

**Metadata**

I have compiled a few sources though:
```
(
      buildPythonPackage rec {
        pname = "pygame-ce";
        version = "2.3.1";
        src = fetchPypi {
          inherit pname version;
          sha256 = "sha256-xr7Ly4wWYjl9ptZ7nKtp5dFn/+rD2ZPrFUncHDe+eD4=";
        };
        doCheck = false;
        propagatedBuildInputs = with pkgs; [
          # Specify dependencies
	 dpkg
	 python310
	 python310Packages.numpy
	 SDL2
	 SDL2_mixer
	 SDL2_image
	 SDL2_ttf
	 SDL2_gfx
        ];
      }
)
```
The above should work as far as I know, take this as base.

* GitHub URL: https://github.com/pygame-community/pygame-ce
* PyPi URL: https://pypi.org/project/pygame-ce/
* Source URL (tar.gz download link): https://files.pythonhosted.org/packages/29/1f/8acc9e552047358688875e7a1ef8f5b5419a7bc5c1eeee3a5beab5a995ff/pygame-ce-2.3.1.tar.gz
* license: GNU-LGPL 2.1
* platforms: unix, linux, darwin, windows (anything that runs a Python interpreter)

**Comment by Starbuck5** [comment]
Hello, I'm one of the pygame-ce authors and just happened to stumble across this today. ^SDL2_gfx is not needed for the compilation, pygame-ce's source code has it bundled in.

**Comment by pbsds** [comment]
please test https://github.com/NixOS/nixpkgs/pull/304472
