### ISSUE TITLE
pnpm detects a node version different from the one in the shell

### ISSUE THREAD

**Issue by larsivi** [NixOS/nixpkgs#250427]
### Describe the bug
I have a shell.nix that installs nodejs_18 and nodePackages_latest.pnpm

When running nix-shell I have the correct version of node (18.17.1) and the noted version of pnpm (not the actual latest, but a recent one). In one of the packages in the pnpm workspace, engine is specified as 18.

Running pnpm install gives me the warning:
modules/foo                         |  WARN  Unsupported engine: wanted: {"node":"18"} (current: {"node":"v20.5.1","pnpm":"8.5.1"})

I don't know where the 20.5.1 comes from, it is not explicitly part of any of my environments.

### Steps To Reproduce
1. Have a pnpm managed project where at least one package has "engines": { "node": "18" } in package.json
2. Have a nix-shell with nodejs_18 and nodePackages_latest.pnpm
3. Run pnpm install

### Expected behavior
No warning about node versions

### Notify maintainers
@happysalada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[nix-shell:~/code/foo]$ nix-shell -p nix-info --run "nix-info -m"
Make some Foo
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.2918.4cdad15f34e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
Try using `nodePackages.pnpm` instead.

**Comment by happysalada** [comment]
Exactky, nodePackages_latest is the node version used to install a particular oackage (pnpm in your case ) . so pnpm will think that node is 20.5 (latest) when what yiu want is 18

**Comment by happysalada** [comment]
Im going to close this, but feel free to reopen if this doesnt solve your problem.

**Comment by larsivi** [comment]
Thank you! This solved it :) A quick question on pnpm versions, as that was what I was looking for the latest on - when/how often is the package updated?

**Comment by happysalada** [comment]
You can also make a PR to update thibgs yourself if you find that its missing a version that you really want.
- get at the root of nixpkgs and pull latest master
- run "./pkgs/development/node-packages/generate.sh"
It takes about an hour on a beefy machine.
Feel free to tag me and i will be happy yo help you get it merged.
