### ISSUE TITLE
Apptainer is missing the /var/lib/apptainer/mnt/session directory

### ISSUE THREAD

**Issue by nobodyinperson** [NixOS/nixpkgs#250581]
### Describe the bug

The `apptainer` derivation is missing the `/var/lib/apptainer/mnt/session` directory to work properly.

### Steps To Reproduce

```
❯ nix-shell -p apptainer --run 'apptainer run docker://alpine echo Hi'
INFO:    Using cached SIF image
FATAL:   container creation failed: failed to resolve session directory /var/lib/apptainer/mnt/session: lstat /var/lib/apptainer: no such file or directory
```

### Expected behavior

`Hi` is output without error.

### Additional context

This can be fixed by creating the `/var/lib/apptainer/mnt/session` directory manually (`sudo mkdir -p /var/lib/apptainer/mnt/session`). I guess this could be added to the derivation. 🤷

### Notify maintainers

@jbedo @ShamrockLee 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.2403.d57e8c535d4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ShamrockLee** [comment]
1. The NixOS module `programs.singularity` provides those top-level directories.

2. I discussed with one of the main Apptainer developer in https://github.com/apptainer/apptainer/issues/1283 . He think it should be easy to specify a directory that will always exist at build time.

   Regalding this, I'm considering the possibility to put those dilectories under the derivation store path. Not sure if there would be potential problem using a store path as a mount point, but it seems to work without problem.

**Comment by ShamrockLee** [comment]
@nobodyinperson Could you help me take a look at #250949?

**Comment by ShamrockLee** [comment]
@nobodyinperson If you have time, please help me test the PR #250949. It should fundamentally solve this issue. If applied, you no longer need the NixOS module or `sudo mkdir -p /var/lib/{apptainer,singularity}/mnt/session` just to run images.

It specifies the LOCALSTATEDIR as `$out/var/lib/{apptainer,singularity}/mnt/session`, making both Apptainer and Sylabs SingularityCE works without `/var/lib/{apptainer,singularity}/mnt/session`.

(The image running still depends on `/etc/resolv.conf` and `/etc/hosts` to run images, which might be the final obstacle to build images as a package without invoking a virtual machine. Other than that, it should not be an issue for most users, as `/etc/{resolv.conf,hosts}` are available on most of the UNIX/UNIX-like systems.)

**Comment by nobodyinperson** [comment]
I removed `/var/lib/apptainer/mnt/session` (the temporary fix for this issue) and ran the following and it seems to work fine:

```bash
yann in yann-desktop-nixos in ~ 
🐟 ❯ nix-shell -p apptainer -I nixpkgs=https://github.com/ShamrockLee/nixpkgs/archive/refs/heads/apptainer-localstatedir.zip --run 'apptainer run docker://alpine echo Hi'
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /run/user/1000, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 96526aa774ef done  
Copying config e175fa54c5 done  
Writing manifest to image destination
Storing signatures
2023/11/14 13:05:32  info unpack layer: sha256:96526aa774ef0126ad0fe9e9a95764c5fc37f409ab9e97021e7b4775d82bf6fa
2023/11/14 13:05:32  warn xattr{etc/shadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2023/11/14 13:05:32  warn xattr{/run/user/1000/build-temp-1961815878/rootfs/etc/shadow} destination filesystem does not support xattrs, further warnings will be suppressed
INFO:    Creating SIF file...
Hi
```

Thank you for this fix!

**Comment by ShamrockLee** [comment]
Glad to hear that!

Would you mind approving #250949 ? I've heard that committers tend to merge PRs getting two approvals.

**Comment by nobodyinperson** [comment]
✅ Done!
