### ISSUE TITLE
Build failure: pureref

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#250520]
### Steps To Reproduce

1. Add **pureref** package to either home-manager or configuration.nix.
2. Try to build with **sudo nixos-rebuild switch**.

### Build log

```
error: builder for '/nix/store/49an4n3jhr6b95vka6bdhj23nkvbznay-PureRef-1.11.1_x64.Appimage.drv' failed with exit code 1;
       > ***
       > Unfortunately, we cannot download file PureRef-1.11.1_x64.Appimage automatically.
       > Please go to https://www.pureref.com/download.php to download it yourself, and add it to the Nix store
       > using either
       >   nix-store --add-fixed sha256 PureRef-1.11.1_x64.Appimage
       > or
       >   nix-prefetch-url --type sha256 file:///path/to/PureRef-1.11.1_x64.Appimage
```

### Notify maintainers

@ElnuDev 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.9, NixOS, 23.11 (Tapir), 23.11.20230810.ce5e4a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ElnuDev** [comment]
Please read the error message. Because the pureref website has a captcha system before downloading, it's impossible for Nix to download the .Appimage file automatically. As the error message says, go to pureref's website, download it, and then run ` nix-store --add-fixed sha256 PureRef-1.11.1_x64.Appimage` to add it to the Nix store. If you then try rebuilding again, it should work without issue.

**Comment by W-Y-R** [comment]
Thank you for the support you've provided, your assistance is sincerely valued.

**Comment by Misterio77** [comment]
> I remember being told doing something similar in Nix wouldn't be feasible, but I don't remember why, it's been a while. If you want to figure out a way to get this to work feel free to open a PR.

It actually is! You can use a Fixed Output Derivation to do anything (including network access), the only caveat is you have to specify the hash of the resulting files (similarly to fetchurl and friends, they're all FODs in the end). For this usecase, it doesn't have any drawbacks, really. Will see if I can get a PR for it.
