### ISSUE TITLE
compton as a service causes gray screen of death

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nixpkgs#25054]
## Issue description
I have a system where I use xomand+none. And had `compton` on as a service in configuration.nix. Everything worked fine until I added `terminator` to my systemPackages. After doing so, and rebooting, my system was a noninteractive gray screen of death after login. Removing `terminator` restored the function of the system. 

you can see the `configuration.nix` file here: http://lpaste.net/6822723740615311360

After some help from _clever_ on IRC, and poking around the journal. I moved `compton` from being a service to being a package, and now `terminator` causes no problems.

Weirdly, if I installed terminator ad hoc, it worked, until I reboot (giving the gray screen of death). Forcing me to 
1. login as root via `xterm`
2. login as myself via `su - isaac`
3. remove the ad-hoc package
4. reboot
5. login as me again
6. reinstall ad hoc so I can use terminator 
Oy!

Here is the journal for one such frustrating session: http://lpaste.net/5291960017220534272

### Steps to reproduce

1. Build a system with the above `configuration.nix`.  
1. Login as `isaac`. 
1. Witness gray screen of death.
1. Logout with `Mod+shift+q`
1. Login as `root` with `xterm`
1. edit the `configuration.nix` and remove `terminator`
1. run `nixos rebuild switch`
1. reboot
1. Login as `isaac`
1. Witness that things work.
1. edit `configuration.nix` so that `compton` is a package instead of a service, and put back `terminator`
1. run `nixos rebuild switch`
1. reboot
1. login as `isaac`
1. Witness that things work.

## Technical details

* System: nixos 17.03
* Nix version: 1.11.8
* Nixpkgs version: "17.03.873.0c041520c3"

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by Fresheyeball** [comment]
This is working fine now
