### ISSUE TITLE
Update request: flutter 3.10.5 → 3.13.0

### ISSUE THREAD

**Issue by NANASHI0X74** [NixOS/nixpkgs#250519]
- Package name: flutter
- Latest released version: 3.13.0
- Current version on the unstable channel: 3.10.5
- Current version on the stable/release channel: 3.10.0
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NixOS/flutter

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Henry-Hiles** [comment]
I agree, this would be great. I'll see if I can make a PR, but I'm fairly new to this so not sure.

**Comment by hacker1024** [comment]
Closed by #251409

**Comment by I-Want-ToBelieve** [comment]
The Flutter SDK is  [3.13.2](https://storage.flutter-io.cn/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.2-stable.tar.xz)  now
