### ISSUE TITLE
fetchbzr: always fetches the same revision, "rev" parameter is ignored

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25055]
## Issue description

```fetchbzr``` always fetches the same revision, ```rev``` parameter is ignored

### Steps to reproduce

```
#!/usr/bin/env nix-shell
#!nix-shell -p nix -i "nix-build --option use-binary-caches false"

{ pkgs ? import <nixpkgs> {} }:

pkgs.fetchbzr {
  url = "http://bazaar.launchpad.net/~phablet-team/process-cpp/trunk";
  rev = "anything-here";
  sha256 = "10529r9nhry80w4m2424il561xbirz7b5fx0s0sw02qcjp362afp";
}
```

related: https://github.com/NixOS/nixpkgs/pull/25015

## Technical details

* System: 17.09.git.68fb01d (Hummingbird)
* Nix version: 1.12pre5152_915f62f
* Nixpkgs version: 17.09.git.68fb01d4da

**Comment by Lassulus** [comment]
Have you tried changing the sha256? afair the revision check is skipped If the source with the matching hash already exists in the store.

**Comment by volth** [comment]
ah, that is the case; sorry
