### ISSUE TITLE
gnome session no longer aware of user and kezboard layout

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#25060]
## Issue description

gnome/session no longer lets me configure my keyboard layout, and lacks logout&screen locking

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by unlmtd** [comment]
I'v been having the same issue for a few weeks. Had been told it was already reported. I guess I should have verified. So gnome doesnt respect the global layout settings, neither does gdm, but up until this bug we were able to set it manually in the gnome settings. There may be a gsettings override to change the keyboard?

**Comment by thall** [comment]
The same problem for me!

**Comment by tohl** [comment]
same here since upgrade to 17.03

**Comment by bjornfor** [comment]
> lacks logout&screen locking

Same as this? https://github.com/NixOS/nixpkgs/issues/22820

Even with only one user account, there is the "key-lock" button next to the power button, for locking the screen with a mouse. Do you have that? (Tested on NixOS 17.03 and master.)

**Comment by tohl** [comment]
I can log out, but there is no "lock screen" menu/button.

Another new and strange thing is a slider, the first one above mic and
light, which doesn't have any icon and it is not clear to me, what does
it control.  Just a new slider appeared and I don't know what for.

**Comment by thall** [comment]
Anyone who have an temporary solution for this?

**Comment by jonafato** [comment]
This appears to be fixed for me on `master`. Can others still reproduce it?

**Comment by eqyiel** [comment]
This is probably fixed since https://github.com/NixOS/nixpkgs/pull/26113.
