### ISSUE TITLE
Update request: tailscale 1.46.1 → 1.48.1

### ISSUE THREAD

**Issue by mfrw** [NixOS/nixpkgs#250647]
- Package name:
- Latest released version:

- Current version on the unstable channel:
- Current version on the stable/release channel:

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by dotlambda** [comment]
You don't need to open an issue if you're going to make a PR right after.

**Comment by mfrw** [comment]
> You don't need to open an issue if you're going to make a PR right after.

Apologies, my bad. I was not aware :(. I am only 1 day & 1 PR old here.
