### ISSUE TITLE
Package request: CODELITE

### ISSUE THREAD

**Issue by EilTalrent** [NixOS/nixpkgs#250616]
**Project description**

CodeLite is an open source, free, cross platform IDE, specialized in C, C++, Rust, Python, PHP and JavaScript (mainly for backend developers using Node.js) programming languages which runs best on all major Platforms ( OSX, Windows and Linux )

**Metadata**

* homepage URL: https://codelite.org/
* source URL: https://github.com/eranif/codelite
* license: gpl2+
* platforms: OSX, Windows, Linux

**Comment by romildo** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/238337
