### ISSUE TITLE
Update request: telegram-desktop 4.8.4 → 4.9.1

### ISSUE THREAD

**Issue by LudovicoPiero** [NixOS/nixpkgs#250682]
- Package name: telegram-desktop
- Latest released version: 4.9.1

- Current version on the unstable channel: 4.8.4
- Current version on the stable/release channel: 4.8.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NickCao 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/pull/244598

Due to telegram-desktop's use of unstable glib/glibmm which is not currently available in nixpkgs, we have to delay the update.
