### ISSUE TITLE
KDE Plasma Activities reset on reboot

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#250619]
### Describe the bug
After every reboot reboot, my KDE Plasma Activities (not Virtual Desktops) are unavailable in the Activity Switcher on my panel.  I can get them back by going to System Settings→Workspace Behaviour→Activities and renaming each activity (and renaming back), but all activities other than the one my session booted into have been reset to defaults, as if they were just created.

### Steps To Reproduce
1. Create more than one activity
2. Change wallpaper on and add a widget to all activities
3. Reboot
4. Log in

### Expected behavior
For all activities to persist across reboots.

### Additional context
This probably isn't relevant, but just in case, my rootfs is a tmpfs, with all directories in `/` mounted from ZFS datasets.
<details>
<summary>filesystems in NixOS configuration</summary>

```nix
_: {
  # /tmp is backed by disk instead of being a tmpfs, in order to save RAM.
  # Wipe it on boot.
  boot.tmp.cleanOnBoot = true;
  fileSystems =
    {
      "/" = {
        device = "none";
        fsType = "tmpfs";
        options = ["mode=755"];
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/F4D3-E3D5";
        fsType = "vfat";
        options = ["X-mount.mkdir" "x-gvfs-hide"];
      };

      "/boot2" = {
        device = "/dev/disk/by-uuid/F4DB-E940";
        fsType = "vfat";
        options = ["X-mount.mkdir" "x-gvfs-hide"];
      };
    }
    // builtins.mapAttrs (mountpoint: dataset: {
      device = dataset;
      fsType = "zfs";
      options = ["zfsutil" "x-gvfs-hide"];
    })
    {
      # NixOS
      "/tmp" = "rpool/nixos/tmp";
      "/nix" = "rpool/nixos/nix";
      "/etc" = "rpool/nixos/etc";
      "/var" = "rpool/nixos/var";
      "/var/lib" = "rpool/nixos/var/lib";
      "/var/log" = "rpool/nixos/var/log";
      "/var/spool" = "rpool/nixos/var/spool";
      # User data
      "/home" = "rpool/userdata/home";
      "/root" = "rpool/userdata/home/root";
      "/home/aidan" = "rpool/userdata/home/aidan";
    };
}
```
</details>

### Notify maintainers
Unsure of maintainers, so tagging some recent recurring contributors to `nixos/modules/services/x11/desktop-managers/plasma5.nix`
@K900 @laalsaas @eduarrrd @lheckemann 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.46, NixOS, 23.11 (Tapir), 23.11.20230819.d680ded`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

Note: NixOS configuration is a flake.

**Comment by alexjp** [comment]
Hi,

Using Nixos Unstable: I just tested on a new user: logging in on plasma wayland, creating activity with "meta+q", adding one plasma element on one activity and another on the other activity and rebooted. 

It worked fine upon reboot

**Comment by aidalgol** [comment]
OK, so there's probably something else about my setup causing this.  I'm using X11 still if that matters.  What can I do to troubleshoot this further?  Is there some logging I should look at?

**Comment by alexjp** [comment]
can you check if you have the files and that they are RW:
`kactivitymanagerdrc`
`~/.local/share/kactivitymanagerd/resources/database*`

also, can you try out moving to unstable? I find it weird that it might be an error with stable release, but i have only used unstable.

also before you changing to unstable, i will try it with x11 and update this comment in a few hours, i just can't try it right now!

**Comment by aidalgol** [comment]
All of those files are read-writable, and I am already tracking `nixos-unstable`.

**Comment by aidalgol** [comment]
I have not had this issue in a while, and now Plasma 6 is in NixOS unstable, so I'm going to close this.
