### ISSUE TITLE
unclutter continually restarting

### ISSUE THREAD

**Issue by alunduil** [NixOS/nixpkgs#25073]
## Issue description

After enabling unclutter via the service module (`services.unclutter.enable`), I find that it errors due to an incorrectly specified display parameter and simply continually restarts.

The journal entries:

```
Apr 20 19:46:41 elijah unclutter[9322]: /nix/store/ww4js6z4j66iipvr22nzmc0qrs5g8fjg-unclutter-8/bin/unclutter: could not open display
Apr 20 19:46:41 elijah systemd[2765]: unclutter.service: Main process exited, code=exited, status=1/FAILURE
Apr 20 19:46:41 elijah systemd[2765]: unclutter.service: Unit entered failed state.
Apr 20 19:46:41 elijah systemd[2765]: unclutter.service: Failed with result 'exit-code'.
Apr 20 19:46:43 elijah systemd[1375]: unclutter.service: Service hold-off time over, scheduling restart.
```

Contents of unit:

```
# /nix/store/j1xnd7r2pjrk5lqw66fgxhqmxvajmp2l-unit-unclutter.service/unclutter.service
[Unit]
Description=unclutter

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/1arhqhqgb2dzdd3iz4xfv5xkpfvm8jjf-glibc-locales-2.25/lib/locale/locale-archive"
Environment="PATH=/nix/store/4d6f8hg5gv20nsbq7b52qzn6bcs4fvlh-coreutils-8.26/bin:/nix/store/f3vl26f3n18khgq1kybnzvwjbm0r9grg-findutils-4.6.0/bin:/nix/store/28kkn4w4k4ay6aihbi1x1hpmicz3wq88-gnugrep-3.0/bin:/nix/store/0xwrn1p8fp
Environment="TZDIR=/nix/store/8dra7y257c6a69wjbns3f8gc9j1wkb20-tzdata-2016j/share/zoneinfo"



ExecStart=/nix/store/ww4js6z4j66iipvr22nzmc0qrs5g8fjg-unclutter-8/bin/unclutter \
  -idle 2 \
  -display : \
  -jitter 0 \
   \
   \
  -not  \

Restart=always
RestartSec=3
```

I'm pretty sure there is a symbol conflict causing the display to be an unadorned colon but I am not sure.

### Steps to reproduce

1. enable unclutter—`services.unclutter.enable`
2. observe running unclutter's behavior

## Technical details

* System: 17.03.1016.c558d093ab (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1016.c558d093ab"

**Comment by joachifm** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/24601/commits/c91c3209f3dbaf9dacef69395e071a9dee59bbee in master. I suppose we can pick that to release as well.

**Comment by joachifm** [comment]
The fix should be included in the next release channel update.
