### ISSUE TITLE
Build failure: radicle-upstream

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#250744]
### Steps To Reproduce

1. build `radicle-upstream`

### Build log

https://hydra.nixos.org/build/230798461

```
setting interpreter of /nix/store/356czrh003r1h1dija9cpxq3yvs3l47i-git-remote-rad-0.3.0/bin/git-remote-rad
searching for dependencies of /nix/store/356czrh003r1h1dija9cpxq3yvs3l47i-git-remote-rad-0.3.0/bin/git-remote-rad
    libgcc_s.so.1 -> not found!
auto-patchelf: 1 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/356czrh003r1h1dija9cpxq3yvs3l47i-git-remote-rad-0.3.0/bin/git-remote-rad
auto-patchelf failed to find all the required dependencies.
Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
/nix/store/rk3g4mxrs84bv1vanqnzpdkhm73ksr0z-stdenv-linux/setup: line 87: pop_var_context: head of shell_variables not a function context
/nix/store/rk3g4mxrs84bv1vanqnzpdkhm73ksr0z-stdenv-linux/setup: line 1459: pop_var_context: head of shell_variables not a function context
/nix/store/rk3g4mxrs84bv1vanqnzpdkhm73ksr0z-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context
```

### Additional context

Encountered build failure when ran unrelated `nixpkgs-review` on a minor change at https://github.com/NixOS/nixpkgs/pull/250500

The bisect is not very precise as most commits don't even evaluate:

$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
86ca0faff759bb28901079e643c55c3f6a4ea47d
d7fe0a5548413fedb2c23d8b7d9864c99350e226
c6bd37a69160e7e436d9b8fba1ff12d0678ccf1a
fed2300bea5e0451c6fe55535f0a8f471a5d8c35
7553d0fe29801938bcb280bb324b579ef9016aea
96588eb3de55931e8b92a4f78f44342598f7ed5c
5f57c2e0f97a83bf5691ac3a29da6ef9b44535c4

### Notify maintainers

@d-xo

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/225963

**Comment by eclairevoyant** [comment]
removed in #309050
