### ISSUE TITLE
Meson build fails if boot.binfmt.emulatedSystems contains x86_64-windows

### ISSUE THREAD

**Issue by MarSoft** [NixOS/nixpkgs#250745]
### Describe the bug
NixOS supports using `binfmt` for starting Wine when one tries to launch a Windows EXE file, which is enabled by putting a string `x86_64-windows` to `boot.binfmt.emulatedSystems` array.
Under the hood, EXE files are determined by their extension rather than by signature:
```
    # nixos/modules/system/boot/binfmt.nix
    x86_64-windows = {
      magicOrExtension = "exe";
      recognitionType = "extension";
    };
```
```
# /etc/binfmt.d/nixos.conf
:x86_64-windows:E::exe::/run/binfmt/x86_64-windows:
```

This causes an issue with files which are executable and are proper ELF binaries but have `.exe` suffix. One of the examples is a sanity check performed by `meson` build system: it creates a C file `sanitycheckc.c` and compiles it to `sanitycheckc.exe` (regardless of the platform!) and tries to run it. As a result, the system tries to run it as `wine` executable and fails.

### Steps To Reproduce
1. Enable wine binfmt: put `x86_64-windows` to `boot.binfmt.emulatedSystems` and `nixos-rebuild switch`
2. Try to build some meson project. Here is a derivation I tried to build:
```
stdenv.mkDerivation rec {
        pname = "iio-sensor-proxy";
        version = "3.5";
        src = prev.fetchFromGitLab {
          domain = "gitlab.freedesktop.org";
          owner = "hadess";
          repo = pname;
          rev = version;
          sha256 = "pFu+nJzj45s7yIKoLWLeiv2AT5vLf6JpdWWQ0JZfnvY=";
        };
        buildInputs = with prev; [
          glib gtk3 gtk-doc libgudev systemd
        ];
        nativeBuildInputs = with prev; [
          meson ninja pkg-config breakpointHook
        ];
}
```
3. You will get the following error: `meson.build:1:0: ERROR: Executables created by c compiler gcc are not runnable.`

Or without meson:

2. ```echo -e '#!/bin/sh\necho hello world' > test.exe && chmod +x test.exe && ./test.exe```
3. Get an error message from wine:
```
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
```

### Expected behavior
The ELF file should run as is, even if it is named `something.exe`.
Same for bash scripts.

This could be achieved by matching files by signature (aka magic) rather than their extension. For example, in Arch Linux the similar binfmt feature is implemented with the following string in `/etc/binfmt.d/wine.conf`:
```
:DOSWin:M::MZ::/usr/bin/wine:
```
Which could be written as follows in `nixos/modules/system/boot/binfmt.nix`:
```
{
  magicOrExtension = ''MZ'';
  mask = ''\xff\xff'';
}
```

### Notify maintainers

@matthewbauer @bdd 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.05 (Stoat), 23.05.2613.011567f35433`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, unstable"`
 - channels(mars): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by adamcstephens** [comment]
It looks like this is already fixed in master and unstable. https://github.com/NixOS/nixpkgs/pull/250974
