### ISSUE TITLE
Package request: zfs-replicate

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#250750]
[zfs-replicate](https://github.com/alunduil/zfs-replicate) is currently at 3.0.0 but the most recent version in nixpkgs is 1.2.3.

@alunduil Could you please update the package?

**Comment by alunduil** [comment]
I've just updated zfs-replicate to 3.1.0 and will put together a pull request for this version.  If you're comfortable, you can submit version bumps in the future, and I should be able to sign off on them.

**Comment by gepbird** [comment]
This package is currently on the latest 3.2.13 version
