### ISSUE TITLE
Quickemu - Unable to Start/Install MacOS Virtual Machine

### ISSUE THREAD

**Issue by omernaveedxyz** [NixOS/nixpkgs#250849]
### Describe the bug
As a result of a recent update, Quickemu MacOS VM's now fail to start and crash. This is a NixOS issue as everything is working properly on my other device running on Arch Linux. Quickemu nor QEMU have been updated in Nixpkgs within the last month, so it looks to be some dependency that is breaking in NixOS.

Windows VM's still work fine.

### Steps To Reproduce
1. install quickemu
2. run the following in terminal
```bash
quickget macos catalina
quickemu --vm macos-catalina.conf --display spice
```
4. After the QEMU window opens, use cursor keys and enter key to select the `macOS Base System`
5. MacOS boot up will crash after a few seconds (~30)

### Expected behavior
MacOS will boot up successfully.

### Screenshots
Hangs at this step
![2023-08-22_23-40](https://github.com/NixOS/nixpkgs/assets/112912585/870d0523-44be-465d-9278-17b71cd5d5c9)

Then crashes like so
![2023-08-22_17-39](https://github.com/NixOS/nixpkgs/assets/112912585/0cb15a90-73b6-42d5-a1c5-032a47c9c009)

### Additional context
This is using the latest version of nixos-unstable. This has broken within the last month as August 1 was the last time I updated my flake inputs.

Works in rev `0368b2615773d63b96fd24947f9d4ea65d7f52ad` (nixpkgs-unstable) (August 1)

### Notify maintainers

@FedX-sudo (listed as maintainer of quickemu)

### Metadata
It shows my nixpkgs channel as "nixos" but I am using "nixos-unstable" in my system flake.nix.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11.20230821.91a22f7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Things I've tried (with no luck)
- Downgrade QEMU from 8.0.3 to 8.0.2
- Downgrade Quickemu from 4.8 to 4.7
- Downgrade kernel from 6.4.11 (latest) to 6.1.46 (lts)

**Comment by omernaveedxyz** [comment]
**Update**: Seems to be specific to the hardware on my desktop. I was not able to replicate the issue on my laptop even with the same nixos-config flake.

This has become a lot more troublesome for me specifically.

**Comment by omernaveedxyz** [comment]
**Update 2**: After a lot of git bisecting, I was able to find the cause of the issue. It is an issue with the Linux kernel. I had to downgrade the LTS kernel from 6.1.46 to 6.1.43 in order to resolve this issue.

That means there is some regression introduced in 6.1.44 that breaks MacOS virtualisation on AMD cpus...

**Comment by omernaveedxyz** [comment]
This has been fixed in latest LTS kernel (6.1.49)

**Comment by OrhanYigitDurmaz** [comment]
i must've say crazy debugging. how did you even found that out? Im kind of having the same issues on Arch Linux 6.8.5 as well. I cant seem to install macos'es, is there a debug output that i can look for? my CPU is an Intel i5-6500

**Comment by OrhanYigitDurmaz** [comment]
by the way, when installing macos, i can accept the aggreements etc.
