### ISSUE TITLE
Package request: Dorion

### ISSUE THREAD

**Issue by pagusupu** [NixOS/nixpkgs#250873]
**Project description**

> Dorion is an alternative Discord client aimed and lower-spec or storage-sensitive
PCs that supports themes, plugins, and more! 

**Metadata**

* homepage URL: https://spikehd.github.io/projects/dorion/
* source URL: https://github.com/SpikeHD/Dorion
* license: gpl3
* platforms: linux, macos, windows

**Comment by Nyabinary** [comment]
Would love this to be added lol

**Comment by knarkzel** [comment]
Working on Dorion here: https://github.com/NixOS/nixpkgs/pull/252627

**Comment by Nyabinary** [comment]
@AndersonTorres Were stuck in trying to package this app, can you help maybe if you can?

**Comment by knarkzel** [comment]
It should be working now, waiting for merge
