### ISSUE TITLE
zyrthm: Stuck at initial configuration

### ISSUE THREAD

**Issue by ThibaultLemaire** [NixOS/nixpkgs#250804]
### Describe the bug
Zrythm loops between the "Welcome" and "Setup Zrythm" popups forever.

### Steps To Reproduce
1. nix run nixpkgs#zrythm
2. OK
3. OK
4. GOTO 2.

### Expected behavior
Being able to get past the Initial Configuration screens and use Zrythm normally

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/21345269/f1105331-4360-4f63-a9dc-edc62c89b162)
![image](https://github.com/NixOS/nixpkgs/assets/21345269/efc9778d-9096-4384-aa26-f6e92d32d021)

### Additional context
I'll try to investigate a workaround. Maybe it's expecting some folder somewhere

### Notify maintainers

@tshaynik @magnetophon @yuuyins 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.37-xanmod1, NixOS, 23.11 (Tapir), 23.11pre506474.12303c652b8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"home-manager, nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by PowerUser64** [comment]
I assume this can be closed now?

**Comment by ThibaultLemaire** [comment]
I assume zrythm still does not work without dconf, and still does not provide useful info about what went wrong.

However I haven't used it since, and don't plan to use it again in the near future.

I agree to close this for triaging. I'll know where to find it again the day I get back to zrythm.
