### ISSUE TITLE
plamashell does not load correctly [latest 17.03]

### ISSUE THREAD

**Issue by luispedro** [NixOS/nixpkgs#25087]
## Issue description

Plasmashell fails to start. The logs (full log below) show the following error, which I am guessing is the culprit:

   "Error loading QML file.\n20: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"

### Steps to reproduce

Login with "plama 5" as environment. An error box appears, warning "All shell packages missing".

Running "plasmashell" on a terminal produces the log below.

## Technical details

* System: 
17.03.1015.5d611adde6 (Gorilla)
* Nix version:
nix-env (Nix) 1.11.8
* Nixpkgs version: 
"17.03.1015.5d611adde6"

## Full log

    Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    Icon theme "oxygen" not found.
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    Recreating ksycoca file ("/home/luispedro/.cache/ksycoca5_en_WDMFnOvfFuTmSBg6L_WiyBYYy8Q=", version 303)
    kf5.kservice.sycoca: Parse error in  "/home/luispedro/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"
    Menu "applications-kmenuedit.menu" not found.
    Saving
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    Failed to connect to the kglobalaccel daemon QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kglobalaccel received signal 6")
    "file:///nix/store/6zylxl6qnx8ky0xw1b7asrpnqhfr4gn5-plasma-desktop-5.8.6/share/plasma/shells/org.kde.plasma.desktop/contents/applet/AppletError.qml" 
    "Error loading QML file.\n20: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"
    "file:///nix/store/6zylxl6qnx8ky0xw1b7asrpnqhfr4gn5-plasma-desktop-5.8.6/share/plasma/shells/org.kde.plasma.desktop/contents/applet/AppletError.qml" 
    "Error loading QML file.\n20: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"
    QQmlComponent: Component is not ready
    "file:///nix/store/6zylxl6qnx8ky0xw1b7asrpnqhfr4gn5-plasma-desktop-5.8.6/share/plasma/packages/org.kde.desktoptoolbox/contents/ui/ToolBoxRoot.qml" 
    "Error loading QML file.\n105: Type ToolBoxItem unavailable\n22: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/luispedro/.local/share", "/nix/store/rj7893690p8k3a0kagww7bbl0qp18is8-kde-application/share", "/nix/store/hkc4x3w1phr3csl5jls4mhj3kwx8l88a-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8", "/run/opengl-driver/share", "/home/luispedro/.nix-profile/share", "/nix/var/nix/profiles/default/share", "/run/current-system/sw/share")
    "file:///nix/store/6zylxl6qnx8ky0xw1b7asrpnqhfr4gn5-plasma-desktop-5.8.6/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml" 
    "Error loading QML file.\n20: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"
    Could not set containment property on rootObject
    "file:///nix/store/6zylxl6qnx8ky0xw1b7asrpnqhfr4gn5-plasma-desktop-5.8.6/share/plasma/shells/org.kde.plasma.desktop/contents/views/Panel.qml" 
    "Error loading QML file.\n20: plugin cannot be loaded for module \"QtQuick.Layouts\": The plugin '/nix/store/1h5wgm6f3p9i95964nr1gg9fq0jvqhnm-qtdeclarative-5.8.0/lib/qt5/qml/QtQuick/Layouts/libqquicklayoutsplugin.so' uses incompatible Qt library. (5.8.0) [release]\n"
    Could not set containment property on rootObject

**Comment by ttuegel** [comment]
Qt 5.8 is not available in the latest NixOS 17.03. You must have packages from an older release or from the master branch installed into a user profile, or the system profile.

**Comment by luispedro** [comment]
Thanks. Yes, the base system is 17.03, but my user profile was on unstable with two kde-offending packages: `kde-gtk-config kdeconnect`. Removing them, fixed it.

From my POV, this can be closed, but I'm not sure if this is the intended behaviour or if it is a failure of isolating plasmashell from other packages.

**Comment by ttuegel** [comment]
> I'm not sure if this is the intended behaviour or if it is a failure of isolating plasmashell from other packages.

It's both. ☹️ If Plasma were completely isolated from the environment, then you wouldn't be able to install new Plasmoids or KCMs, i.e. neither `kde-gtk-config` or `kdeconnect` would be very useful. On the other hand, if even one package gets installed with the wrong Qt version, it will poison Plasma.

**Comment by instantepiphany** [comment]
This just hit me as well, I had installed "spectacle" to take a screenshot, it pulled in some QT libraries and `nix-env -e spectacle` let plasma start correctly again. 

I am mostly commenting just to help this issue be more visible in google, but is this worth documenting in the manual? I guess the subset of users that have their channel set to unstable while their system is set to stable might not be that large.
