### ISSUE TITLE
GHC962 fails to build using `pkgsStatic`

### ISSUE THREAD

**Issue by FPtje** [NixOS/nixpkgs#250833]
### Describe the bug

- On `nixpkgs-unstable` revision 0b07d4957ee1bd7fd3bdfd12db5f361bd70175a6
- Build `pkgsStatic.haskell.packages.ghc962.ghc`
- Find that this fails on both X86_64-linux and ARM64-linux.

Build logs, note that the ARM build and one of the x86_64-linux builds are on revision d2b52322f35597c62abf56de91b0236746b2a03d. I only re-did one build with the latest nixpkgs to save some time.
https://gist.github.com/FPtje/c894b10abd08d3af77ee80a3d0d67540

Found while building this flake: https://github.com/FPtje/GLuaFixer/tree/fp/update-flake-lock

### Expected behavior

A successful build. GHC 9.4 has been doing swimmingly, at least on previous revisions.

### Notify maintainers

I think @nh2 would be a good person to ask for advice on next steps. I'm not familiar with the static build internals of Nix, nor the build specifics of GHC in Nix. Is this a Nixpkgs issue, or a GHC issue?

I found this related issue, which has a similar error message about a file not being produced: https://gitlab.haskell.org/ghc/ghc/-/issues/21807, which seemed to be more of an issue of using the build system.  

### Metadata

```console
❱ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11.20230713.e74e684`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(falco): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bgamari** [comment]
Indeed it seems likely that this is a Hadrian (the GHC build system) bug. Unfortunately, I've found it very hard to debug, or even reproduce outside of `nixpkgs`.

**Comment by FPtje** [comment]
This appears to be a duplicate of https://github.com/NixOS/nixpkgs/issues/208959

Closing
