### ISSUE TITLE
perl 5.24.1 fails to build on darwin on staging

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25090]
## Issue description

Perl fails and therefore also Clang it seems.

Commit https://github.com/NixOS/nixpkgs/commit/f78c0329340172aa0819d7a2fdc36b0a8fbb6d2a
Hydra log https://nix-cache.s3.amazonaws.com/log/a7bc859lhc4bd0mmswccxzq7b9xc4jzv-perl-5.24.1.drv

cc @Mic92 and @plumps 
and for Darwin cc @LnL7 @copumpkin 

Issue was also brought up by @vcunat at https://github.com/NixOS/nixpkgs/pull/24832#issuecomment-295133194

**Comment by LnL7** [comment]
http://hydra.nixos.org/build/51877884

**Comment by FRidh** [comment]
All jobs were aborted.
http://hydra.nixos.org/build/51879930
```
Aborted: program ‘/nix/store/ny0pf6qlq28pjpncn79lr5a6w5i63fyc-nix-1.11.8/libexec/nix/resolve-system-dependencies.pl’ failed due to signal 11 (Segmentation fault: 11) (log, raw, tail)
```

**Comment by vcunat** [comment]
Oh, mac machines on Hydra have been occasionally doing that lately; no idea why.

**Comment by vcunat** [comment]
Well, perl itself builds, but the Darwin slaves are very unreliable.  /cc @edolstra @rbvermaa *Correct me if it's better to (also) ping someone/somehow else about Hydra maintenance.*
