### ISSUE TITLE
Backporting action links to non-existing CONTRIBUTING section

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#250917]
### Describe the bug

The backporting action links to:

```
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#criteria-for-backporting-changes
```

but this section does not exist in the `CONTRIBUTING.md` file.

Pinging both accounts that were involved in the backporting action and the contributing file:

@mweinelt @Mic92 @AndersonTorres @infinisil

**Comment by infinisil** [comment]
Thanks for the report! I did miss this one, but it was also later reported after which I fixed it here: https://github.com/NixOS/nixpkgs/pull/253621
