### ISSUE TITLE
libguestfs 1.29.5 build fails on 17.03 due to missing buildInput

### ISSUE THREAD

**Issue by tjg1** [NixOS/nixpkgs#25092]
## Issue description

Building libguestfs on 17.03 fails with `cannot find -lapparmor`. This works fine on unstable as it includes `libapparmor` in `buildInputs`.

2f73d5f856d2448a4779401d54a64b55ba6f6bae should be backported to 17.03 in order to fix this. 

The following commit cf68f546b1d5648c1d83f33e265c019c9f971c10 introduced more dependencies, but building the current version (1.29.5) succeeds without them.

### Steps to reproduce

Try installing libguestfs on NixOS 17.03. It fails to compile. Adding this to configuration.nix fixes the build:

```
nixpkgs.config.packageOverrides = pkgs: {
  libguestfs = pkgs.libguestfs.overrideAttrs (oldAttrs: rec {
    buildInputs = oldAttrs.buildInputs ++ [ pkgs.libapparmor ];
  });
};
```

## Technical details

* System: NixOS 17.03.1016.c558d093ab (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1016.c558d093ab

**Comment by joachifm** [comment]
The fix should be included in the next release channel update.

**Comment by tjg1** [comment]
Thanks!
