### ISSUE TITLE
Build failure: python310Packages.debugpy

### ISSUE THREAD

**Issue by x10an14** [NixOS/nixpkgs#251045]
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs/a2eca347ae1e542af3f818274c38305c1e00604c#python310Packages.debugpy`

### Build log
[paste.sr.ht pastie](https://paste.sr.ht/~x10an14/d213e54972f637ca7c46e0206fa364a32fbbf3f4) (warning: veeery long)

### Additional context
Seems caused by https://github.com/NixOS/nixpkgs/pull/250298?
Also previously reported (if I'm reading the many thousands of lines of output right) to be another instance of https://github.com/NixOS/nixpkgs/issues/230030.

Breaks: [vscode-extensions.ms-python.python](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/editors/vscode/extensions/ms-python.python/default.nix#L80).

### Notify maintainers
@kira-bruneau 

### Metadata
```console
-> $ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20230808.844ffa8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(x10an14): `""`
 - nixpkgs: `/nix/store/qx67jipw01zps1rqgmmpl7as1irff275-source`
```

**Comment by buckley310** [comment]
This appears to have been fixed somewhere between cf2004afe4d4b95a295c63c911e949e40915eedb and a999c1cc0c9eb2095729d5aa03e0d8f7ed256780

**Comment by x10an14** [comment]
I have no idea how you tested, but after a `nix flake update` (pulling `master` branch), I fail to build this same package.
Now with the newer hash: `cddebdb60de376c1bdb7a4e6ee3d98355453fe56'`
```
# Just in case you don't test the same way I report, here's a `nix build` that fails on this package...
nix build github:nixos/nixpkgs/cddebdb60de376c1bdb7a4e6ee3d98355453fe56#python310Packages.debugpy
```

I vote for this issue to be marked as "prematurely-closed", and thus re-opened.

**Comment by buckley310** [comment]
debugpy was blocking my nixos rebuilds through cf2004afe4d4b95a295c63c911e949e40915eedb. Updating to a999c1cc0c9eb2095729d5aa03e0d8f7ed256780 resolved it for me.
That's about all the testing I did at the time, and figured it was good.

**Comment by kira-bruneau** [comment]
Looks like this is related to flaky process test timeouts (which are more likely to fail on less powerful devices). #252070 should fix this!

**Comment by kira-bruneau** [comment]
You can checkout https://nixpk.gs/pr-tracker.html?pr=252070 to see when the fix will be applied to the channel you're using.
