### ISSUE TITLE
golangci-lint built with go1.21

### ISSUE THREAD

**Issue by ptman** [NixOS/nixpkgs#251099]
### Describe the bug
```console
golangci-lint has version 1.54.2 built with go1.20.7 from v1.54.2 on 19700101-00:00:00

../../../../nix/store/zrdn5v1dix3g46nr3lv1n3ii8ngs9zzv-go-1.21.0/share/go/src/slices/sort.go:97:7: undefined: max (typecheck)
		m = max(m, x[i])
```

### Steps To Reproduce
1. Use golangci-lint on a project built with go1.21

### Expected behavior
golangci-lint 1.54.2 should support go1.21

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.20230822.a16f7eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `""`
 - channels(ptman): `"home-manager-23.05.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/etc/nixpkgsPath`
```

**Comment by kirillrdy** [comment]
@ptman currently default go in `nixpkgs` is go1.20 you can rebuild golangci-lint with go1.21 using 

`
golangci-lint.override { buildGoModule = buildGo121Module; }
`

**Comment by ptman** [comment]
Fair enough.
