### ISSUE TITLE
Update request: abaddon 0.1.10 → 0.1.11

### ISSUE THREAD

**Issue by josphh** [NixOS/nixpkgs#251028]
- Package name: abaddon
- Latest released version: 0.1.11

- Current version on the unstable channel: 0.1.10
- Current version on the stable/release channel: 0.1.10

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GenericNerdyUsername 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by GenericNerdyUsername** [comment]
Can you run `nix run github:genericnerdyusername/nixpkgs/abaddon-update#abaddon` and test things out, especially voice calls?
