### ISSUE TITLE
PATH not set in mksh (or sh) over non-interactive SSH connection

### ISSUE THREAD

**Issue by rqcy** [NixOS/nixpkgs#25100]
## Issue description

I have a user with `shell = "/run/current-system/sw/bin/mksh"` and
openssh enabled.

I'm not able to execute almost any command with:

    ssh nixhost command

e.g.,

    $ ssh nixhost ls
    mksh: ls: not found

because PATH env variable does not seem to be set correctly:

    $ ssh nixhost 'echo $PATH'
    /usr/bin:/bin:/usr/sbin:/sbin:/nix/store/wk90g951ybhh67qmbzq6g2y867356rcq-openssh-7.4p1/bin

It's particularly problematic for git-fetch:

    $ git fetch me@nixhost:some/repo
    mksh: git-upload-pack: not found
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

There's the same issue with `sh`, but `zsh` and `bash` seem to work
correctly.

### Steps to reproduce

1. Set mksh as the loging shell
2. Enable openssh
3. Execute non-interactively a command over ssh: `ssh nixhost ls`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

      $ nixos-version
      17.03.1016.c558d093ab (Gorilla)

* Nix version: (run `nix-env --version`)

      $ nix-env --version
      nix-env (Nix) 1.11.8

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Mic92** [comment]
While bash will source `/etc/bashrc` and zsh will source `/etc/zshenv` in non-interactive shells, there is no equivalent in `mksh`. You will need to invent your own wrapper command around `mksh` to source `/etc/profile` or make mksh a login shell.

**Comment by rqcy** [comment]
> While bash will source `/etc/bashrc` and zsh will source `/etc/zshenv`
> in non-interactive shells, there is no equivalent in `mksh`. You will
> need to invent your own wrapper command around `mksh` to source
> `/etc/profile` or make mksh a login shell.

1. If I understand correctly, mksh is set as the login shell by setting
`users.users.<name?>.shell = "/run/current-system/sw/bin/mksh"`.  Right?


2. I think, I have made some mistakes in the original description of the
problem.  It seems that when I do:

    $ ssh nixhost command

then no shell is actually started.  man ssh seems to confirm that: `If
command is specified, it is executed on the remote host instead of a
login shell.` (I have originally thought that in such case
non-interactive shell is started and `command` is executed.)

So the issue is that with a users having bash or zsh as default login
shells, sshd sets the PATH correctly, but when the default shells are sh
or mksh.

Where/when does sshd source /etc/profile and why is it shell dependent?


Cheers,
Adam

**Comment by rqcy** [comment]
> So the issue is that with a users having bash or zsh as default login
> shells, sshd sets the PATH correctly, but when the default shells are sh
> or mksh.

should be: […], but *not* when the default shells are sh or mksh

**Comment by Mic92** [comment]
The shell set for the user will be always used by sshd. This is how restricted git shells works for instance.
By default most shells only source `/etc/profile` is only sourced if the shell is a so called login shell, which is a subset of an interactive shell session. This is the case if ssh is called without a command. Note that also not sshd sets the PATH, but the shell itself. The reason that zsh/bash set the PATH accordingly is that they also always source `/etc/bashrc` and `/etc/zshenv` even when they are not started as login shells (these files also source /etc/profile accordingly).
mksh does not implement something similar so the only workaround is doing something like:

```
shell = "/path/to/wrapper-script"
```

```
#!/bin/sh
# /path/to/wrapper-script
. /etc/profile
exec /run/current-system/sw/bin/mksh "$@"
```

**Comment by rqcy** [comment]
> The shell set for the user will be always used by sshd. This is how
> restricted git shells works for instance.  By default most shells only
> source `/etc/profile` is only sourced if the shell is a so called
> login shell, which is a subset of an interactive shell session. This
> is the case if ssh is called without a command. Note that also not
> sshd sets the PATH, but the shell itself. The reason that zsh/bash set
> the PATH accordingly is that they also always source `/etc/bashrc` and
> `/etc/zshenv` even when they are not started as login shells (these
> files also source /etc/profile accordingly).  mksh does not implement
> something similar so the only workaround is doing something like:
>
> ```
> shell = "/path/to/wrapper-script"
> ```
>
> ```
> #!/bin/sh
> # /path/to/wrapper-script
> . /etc/profile
> exec /run/current-system/sw/bin/mksh "$@"
> ```

Thanks for the workaround, but it feels really "hacky."  Another
possibility (also just a workaround) is to enable PermitUserEnvironment
in sshd_config and set PATH in ~/.ssh/environment.

I want to stress out, that there's the same issue when /bin/sh is set as
the default shell!

Furthermore, man bash says that /etc/profile is executed for login
shells and sourcing it does not seem right, because then it's also
executed for non-login shells.  It looks that sourcing /etc/profile from
/etc/bashrc covers some deeper problem.  Debian does it the other way
around: /etc/bashrc is sourced from /etc/profile.

I would really like to say where the problem lies, but don't have enough
knowledge of sshd and shells.  I only see that there are some
inconsistencies and setting /bin/sh as the default shell makes `git
pull` unusable (which should not be the case).

Cheers,
Adam

PS what do you think about re-opening the issue (as it's not really
fixed) or discussing it further elsewhere (mailing list?) with other
devs?
