### ISSUE TITLE
`error: executing 'git': No such file or directory` when executing `nixos-rebuild switch` with `doas`

### ISSUE THREAD

**Issue by iivvaannxx** [NixOS/nixpkgs#251254]
### Describe the bug
So I just rewrote my NixOS system flake and I decided to give a try to `doas` instead of `sudo`. I enabled it in the configuration with the following values.

```nix

  security.doas.enable = true;
  security.doas.extraRules = [
  
    { users = [ "iivvaannxx" ]; keepEnv = true; }
  ];
```

But whenever I try to rebuild the system with `doas nixos-rebuild switch --flake .#desktop` I get the following error: 

```
error: getting the HEAD of the Git tree '/home/iivvaannxx/.nixos-config' failed with exit code 1:
       error: executing 'git': No such file or directory
```

And this doesn't happen with sudo. At first I thought that the option keepEnv would fix it as it seemed a problem with the `$PATH` environment variable, but it did not fix it. Here are the values for the environment variable `$PATH` (got from `env | grep "PATH")`:

With `doas`:
```
$PATH=/bin:/sbin:/usr/bin:/usr/sbin:/run/wrappers/bin:/run/current-system/sw/bin:/run/current-system/sw/sbin:/usr/local/bin:/usr/local/sbin
```

Without `doas`:
```
$PATH=/nix/store/dfkvqi6182s94jdf123z3rqn0i84mr1c-git-2.41.0/bin:/nix/store/plhal7yavzpaqwy7lr4fk90sx2mrwksk-glib-2.76.2-bin/bin:/run/wrappers/bin:/home/iivvaannxx/.nix-profile/bin:/etc/profiles/per-user/iivvaannxx/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```
What confuses me more is that if I `doas echo $PATH`  directly then it's correct the `$PATH` is the same. I am probably missing something somewhere in the documentation, but I couldn't find anything similar.

### Steps To Reproduce
I just pushed the flake into [this repository](https://github.com/iivvaannxx/nixos-config) and then I noticed the bug, so:

1. Clone the repository
2. Try to build the flake (there's only one host at the moment named `desktop`) with `sudo nixos-rebuild switch --flake .#desktop` so it can be built properly. The flake will disable `sudo` and enable `doas`. Then try to rebuild with `doas` instead.
3. It should prompt the same error.

### Expected behavior
It should detect git is installed and build normally.

### Additional context
`git` is installed through the configuration of my main user `iivvaannxx` which uses `home-manager`. The configuration is in the file `hosts/desktop/users/iivvaannxx/home.nix`. HM is installed as a module. To be able to build what I am doing is change the `.git` folder name for a moment, build and then rename it back.

### Notify maintainers
@cole-h 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.20230813.720e61e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by cole-h** [comment]
`doas echo $PATH` is working because your shell substitutes `$PATH` before `doas` runs `echo`. A more indicative test would be `doas sh -c 'echo $PATH'` (the single quotes are important) and see if that returns what you'd expect.

Does it work if you move `git` to your system config rather than your user's config?

**Comment by iivvaannxx** [comment]
I tried executing `doas sh -c 'echo $PATH'` and the output was the same as `doas env`. Seems that it's not inheriting the correct path neither.

If I install git through the `environment.systemPackages` then it works as expected (even though the `$PATH` remains the same as before). 

Although I would prefer to keep using the `home-manager` git version, as it has a module which abstracts out some of the configuration.

**Comment by iivvaannxx** [comment]
For the moment I went and disabled `doas` to keep tweaking my flake without headaches, but any insight on how to solve the issue is greatly appreciated.

**Comment by chrissound** [comment]
Using a fresh install of nixos 22.11.4773.ea4c80b39be4 (Raccoon)

I get a similar error:

```
nixos-rebuild switch --max-jobs 2 --show-trace'
building Nix...
building the system configuration...
error: executing 'git': No such file or directory
error: program 'git' failed with exit code 1

       … while fetching the input 'git+file:///root/gitrepo/************'
 ```
 
 I'm just using `builtins.fetchGit`:
 ```
 (import (builtins.fetchGit {
    url = "${repoHost}/root/gitrepo/*******";
    rev = "*********";
  }) {});
  ```
  
  I solved(?) this error by just doing `nix-env -i git`.

**Comment by SebastianStork** [comment]
> Does it work if you move `git` to your system config rather than your user's config?

I had the same issue and this fixed it for me too. Thanks.

> Although I would prefer to keep using the `home-manager` git version, as it has a module which abstracts out some of the configuration.

You can still use the home-manager module and it's abstraction.
