### ISSUE TITLE
X server not listening even with xserver.enableTCP

### ISSUE THREAD

**Issue by res0nat0r** [NixOS/nixpkgs#25125]
## Issue description

X is not listening via TCP even when setting `services.xserver.enableTCP = true`

### Steps to reproduce

* Set `services.xserver.enableTCP = true` in `/etc/nixos/configuration.nix`

* See that X is still setting `-nolisten tcp` via `ps`:

```bash
root       872   851  0 19:53 tty7     00:00:00 /nix/store/hy0k0x1jmwk98cniwv4nq7vsb9791x2f-xorg-server-1.19.3/bin/X -listen tcp -config /nix/store/wxxrcqpv341dz3cj18jn6m98jgpd7gxa-xserver.conf -xkbdir /nix/store/1s3a5kfbl1ppj47rh91191vbknyr0rgq-xkeyboard-config-2.20/etc/X11/xkb -verbose 3 -logfile /dev/null -terminate -logfile /var/log/X.0.log :0 -seat seat0 -auth /run/root/:0 -nolisten tcp vt7 -novtswitch
```

```bash
$ sudo netstat -tlpn| grep X
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```bash
$ nixos-version
17.09pre105622.f0fac3b578 (Hummingbird)
```
* Nix version: (run `nix-env --version`)

```bash
$ nix-env --version
nix-env (Nix) 1.11.8
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```bash
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09pre105622.f0fac3b578"
```

**Comment by Mic92** [comment]
What is your display manager?

**Comment by res0nat0r** [comment]
I am using lightDM via: `xserver.displayManager.lightdm.enable = true;`

**Comment by pbogdan** [comment]
FWIW I was able to get this working on 17.03 by adding:

```
services.xserver.displayManager.lightdm.extraSeatDefaults = ''
xserver-allow-tcp=true
'';
services.xserver.displayManager.xserverArgs = [ "-listen tcp" ];
```

```
~  ps uax | grep bin/X
root      9779  2.3  0.3 441276 64512 tty7     Ssl+ 18:42   0:04 /nix/store/bf2rschjnypqvq0lx2xfxhcyjvmkhhjh-xorg-server-1.19.2/bin/X -terminate -config /nix/store/b11pxm9z613zx0zq2v138is8ak8ymxzp-xserver.conf -xkbdir /nix/store/syrngcziqwii2qhvs4nfgv28xxmr5c96-xkeyboard-config-2.20/etc/X11/xkb -verbose 3 -logfile /dev/null -dpi 192 -listen tcp -logfile /var/log/X.0.log :0 -seat seat0 -auth /run/root/:0 vt7 -novtswitch
~  sudo netstat -tlpn| grep X
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN      9779/X
tcp6       0      0 :::6000                 :::*                    LISTEN      9779/X
```

which seems a bit convoluted but would appear to be working for me. Haven't tested this on unstable but you could give it a try. HTH.

**Comment by res0nat0r** [comment]
Thanks @pbogdan that is working for me. 👍

**Comment by pbogdan** [comment]
I wonder if it would perhaps make sense to make lightdm module set those automatically if `services.xserver.enableTCP` is set to true. Not sure how that's handled in other display managers. Any thoughts on this?

**Comment by spinus** [comment]
would be nice to add a test case for a flag.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by jakobrs** [comment]
This happens on SDDM as well. I was able get it working using:

```nix
{
  services.xserver.enableTCP = true;
  services.xserver.displayManager.xserverArgs = [ "-listen tcp" ]; # Probably not necessary
  services.xserver.displayManager.sddm.extraConfig = ''
    [X11]
    ServerArguments=-listen tcp
  '';
}
```

Could be relevant: https://github.com/sddm/sddm/issues/325
