### ISSUE TITLE
Package request: lua-pam

### ISSUE THREAD

**Issue by MobSenpai** [NixOS/nixpkgs#251375]
**Project description**

**A module for lua to use PAM.**

* homepage URL: https://github.com/RMTT/lua-pam
* source URL: https://github.com/RMTT/lua-pam
* license: mit
* platforms: linux

I just want a native nix package and don't want to build it myself. Also I know I can use distrobox to run it but still a native package would be more useful as I want to integrative it with my awesomeWM custom lockscreen written in lua. Please if you can do, add it :)

**Comment by teto** [comment]
since it's not in luarocks one should add it at the bottom of pkgs/top-level/lua-packages.nix

**Comment by MobSenpai** [comment]
Ah I didn't think of this. Could you check if I can install using this type of config : https://github.com/rxyhn/yuki/blob/main/modules/nixos/awesome.nix.
Also is this the best you can do?

**Comment by MobSenpai** [comment]
> since it's not in luarocks one should add it at the bottom of pkgs/top-level/lua-packages.nix

Ah I didn't think of this. Could you check if I can install using this type of config : https://github.com/rxyhn/yuki/blob/main/modules/nixos/awesome.nix.
Also is this the best you can do?

**Comment by MobSenpai** [comment]
If there's no option then, there's no use keeping it open, it'll just clog the repo. I am closing it with this answer:

> since it's not in luarocks one should add it at the bottom of pkgs/top-level/lua-packages.nix
