### ISSUE TITLE
Package request: nautilus-data

### ISSUE THREAD

**Issue by SayantanRC** [NixOS/nixpkgs#251437]
**Project description**

This is a nautilus extension.

This package is required for Desktop Icons NG extension to work as mentioned [here](https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/284#note_1530571949) by the developer.

**Metadata**

* homepage URL: 
* source URL: I could not find the exact source, but here is a link from debian: https://packages.debian.org/sid/nautilus-data
* license: should be same as nautilus
* platforms: linux

**Comment by rastersoft** [comment]
nautilus-data contains these files/folders:

```
/usr
/usr/share
/usr/share/doc
/usr/share/doc/nautilus-data
/usr/share/doc/nautilus-data/changelog.Debian.gz
/usr/share/doc/nautilus-data/copyright
/usr/share/glib-2.0
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml
/usr/share/gnome-shell
/usr/share/gnome-shell/search-providers
/usr/share/gnome-shell/search-providers/org.gnome.Nautilus.search-provider.ini
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/org.gnome.Nautilus.svg
/usr/share/icons/hicolor/symbolic
/usr/share/icons/hicolor/symbolic/apps
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Nautilus-symbolic.svg
/usr/share/nautilus
/usr/share/nautilus/ontology
/usr/share/nautilus/ontology/nautilus.description
/usr/share/nautilus/ontology/nautilus.ontology
/usr/share/tracker3
/usr/share/tracker3/domain-ontologies
/usr/share/tracker3/domain-ontologies/org.gnome.Nautilus.domain.rule
```

The key file for DING is `/usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml`. (in fact, I'm surprised that nautilus can work without it...)

**Comment by SayantanRC** [comment]
We do have a `glib-2.0` directory under `/run/current-system/sw/share/` but it's empty.

![image](https://github.com/NixOS/nixpkgs/assets/25128924/4670d4a2-5fb6-40c6-81fa-2dbf56922fe1)

**Comment by SayantanRC** [comment]
The `org.gnome.nautilus.gschema.xml` file is present though.

![image](https://github.com/NixOS/nixpkgs/assets/25128924/782cb272-c58a-4ebb-8902-c8b1862aba06)

**Comment by rastersoft** [comment]
It's not enough because that's the "source" file; all the schemas are compiled into a "gschemas.compiled" file. You have to run

    sudo glib-compile-schemas

inside that folder

**Comment by SayantanRC** [comment]
We do have a `schemas.compiled` file in the same directory.

![image](https://github.com/NixOS/nixpkgs/assets/25128924/cad94cb3-1de5-4e3b-ac1e-09a8e6a573d7)

**Comment by rastersoft** [comment]
Mmm... Is Nautilus running on some kind of container? Like a "flatpak"?

**Comment by SayantanRC** [comment]
yes, in nixos they have something called "nix store" where all the application files reside.

**Comment by rastersoft** [comment]
Oook... that explains why DING, which runs outside, can't find the configuration.

**Comment by rastersoft** [comment]
So that seems to be a problem with your OS.

**Comment by SayantanRC** [comment]
sad. is there nothing that can be done?

**Comment by rastersoft** [comment]
Link the gschema.xml file at /usr/share/glib-2.0/schemas folder, run there "sudo glib-compile-schemas", and try again. If it works, great. If not, just remove the link and run again "sudo glib-compile-schemas" to undo the changes.
