### ISSUE TITLE
When fish is login shell `env: command not found` is printed on login

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#25141]
## Issue description

```
/nix/store/hi4j75r312lsjhpdln9p8blyixs59hbs-bash-4.4-p12/bin/bash: env: command not found
```

is printed out on every single login attempt over ssh or locally.

### Steps to reproduce

```
programs.fish.enable = true;
environment.systemPackages = [fish];
users.defaultUserShell = "/run/current-system/sw/bin/fish";
```

then

```
sudo login
```

## Technical details

* System: 17.09pre105622.f0fac3b578
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09pre105622.f0fac3b578

**Comment by florianjacob** [comment]
I don't have this on 17.09.git.e993880, but I don't have fish included in environment.systemPackages. Could that be the problem? programs.fish.enable should be enough, I had many issues with fish while I added fish via systemPackages in the past.

**Comment by nagisa** [comment]
Removed `fish` from systemPackages, and the issue persists.

**Comment by florianjacob** [comment]
Still can't reproduce, the only difference from the parts you posted to my system was that I didn't set the default shell but the login shell for my user, like this:

```
users.extraUsers.florian = {
    …
    shell = pkgs.fish;
    …
};
```

but even with setting fish as default shell for everybody and not setting it in the user, no env error. I also threw in a reboot to be sure.

Maybe it's something in your fish configs that's not NixOS compatible?

**Comment by nagisa** [comment]
Oh, I see where the problem is now.

`PATH DEFAULT=${HOME}/.local/bin:${PATH}` in `.pam_environment` seems to be the cause for some weird reason. This is something I imported from my old arch system.

I guess I can call this "solved", though it would be nice if `fenv` stuff didn’t assume that `PATH` components set before login shell is invoked are meaningless.
