### ISSUE TITLE
Remove linux-chromiumos-3.14.nix

### ISSUE THREAD

**Issue by zx2c4** [NixOS/nixpkgs#25145]
3.14 is no longer supported upstream by kernel.org and thus no longer receives security patches. The git commit mentioned in this .nix isn't even available in the linked repository -- https://chromium.googlesource.com/chromiumos/third_party/kernel -- so I think this .nix might be dead anyway. Finally, it specifies `3.14.0`, which is so ridiculously old (the latest was `3.14.79`) that nobody develops for it.

**Comment by dezgeg** [comment]
The last commit there is 32 hours old. Doesn't sound very unmaintained.

**Comment by zx2c4** [comment]
It's not maintained by kernel.org anymore. However, if you'd alternatively prefer to switch the .nix here to a more recent commit from the chromeos people, and then make sure to track their git repo carefully, that'd be a satisfactory solution to me. But IMHO it's easier and probably better to just get rid of ancient kernels.
