### ISSUE TITLE
shellAliases are not properly escaped (also escapeShellArg does not handle newlines)

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#25143]
## Issue description

Strings for shell aliases are not properly escaped

### Steps to reproduce

```
environment.shellAliases.time = "/usr/bin/time -f'%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv';
```

produces 

```
alias time='/usr/bin/time -f'%P (%e real, %S kernel, %U user); %Mk resident
%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts
%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv''
```

in bashrc (also invalid for other shells such as fish) rather than something resembling

```
alias time='/usr/bin/time -f'"'"'%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv'"'"
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Mic92** [comment]
There is `lib.escapeShellArg` to escape this in `modules/programs/bash/bash.nix` and `modules/programs/zsh/zsh.nix`

**Comment by nagisa** [comment]
Did this:

```
time = let ls = lib.concatStringsSep "\n" [
    "%P (%e real, %S kernel, %U user); Mk resident" 
    "%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts"
    "%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv"
]; in "/run/current-system/sw/bin/time -f${lib.escapeShellArg ls}";
```

got 

```
alias time='/run/current-system/sw/bin/time -f'%P (%e real, %S kernel, %U user); Mk resident
%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts
%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv''
```

in both bashrc and fish.conf. Am I using it wrong?

**Comment by lheckemann** [comment]
AFAIU all of this

```
-f'%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv';
```

is a single argument to `time`, so what I think you want is

```
time = let timeArg = "-f'%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv';"
in "time ${lib.escapeShellArg timeArg}";
```

**Comment by nagisa** [comment]
@lheckemann `-f` and the rest can as well be separate as long as the other side is somehow passed in as a single argument.

Basically the program needs to get these arguments in argv (one per line):

```
0: time
1: -f
2: %P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv
```

or 

```
0: time
1: -f%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv
```

That being said I still tried your approach and it still resulted in invalid bashrc:

```
alias time='time '-f'\''%P (%e real, %S kernel, %U user); %Mk resident
%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts
%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv'\''''
```

**Comment by lheckemann** [comment]
Actually in this case they aren't newlines — they aren't handled by the shell parsing, but by the program (or builtin) the text is getting passed to, as you can see by running `echo '\n'`. So what's happening here is that *nix* is interpreting the escape sequence too early, and you want to pass the literal characters `\` and `n` to `time` — so you'll want to put `\\n` in the nix expression.

**Comment by Mic92** [comment]
For complex cases I usually use a shell script instead of an alias:

e.x.:
```nix
systemPackages = [
 (pkgs.writeScriptBin "rust-doc" ''
    #! ${pkgs.stdenv.shell} -e
    browser="$BROWSER"
    if [ -z "$browser" ]; then
      browser="$(type -P xdg-open || true)"
      if [ -z "$browser" ]; then
        browser="$(type -P w3m || true)"
        if [ -z "$browser" ]; then
          echo "$0: unable to start a web browser; please set \$BROWSER"
          exit 1
        fi
      fi
    fi
    exec "$browser" "${rustc.doc}/share/doc/rust/html/index.html"
 '')
];
```

**Comment by lheckemann** [comment]
@Mic92 any particular reason not to make that a shell function rather than a separate script?

But yes, I agree that a different solution would probably be better for this use case. Maybe write a function and have an alias for that (the function can't be called `time` because it's a shell keyword):

```nix
environment.interactiveShellInit = ''
  time_() {
    time -f '%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv;' "$@"
  }
  alias time=time_
'';
```
(not tested)

**Comment by nagisa** [comment]
> the function can't be called time because it's a shell keyword

not in fish

**Comment by lheckemann** [comment]
Oh yeah, then you can probably do `builtin time` within the function to avoid recursion.

**Comment by 8573** [comment]
I believe this is a duplicate of #16973.

**Comment by nagisa** [comment]
Sure.
