### ISSUE TITLE
Add skypeforlinux client

### ISSUE THREAD

**Issue by PanAeon** [NixOS/nixpkgs#25152]
## Issue description
Microsoft has released a beta version of skypeforlinux software which will eventually replace old qt based linux client. Besides adding new features such as new smiles and formatting new client also fixes some compatibility issues.

## Technical details
Right now Microsoft provides only deb and rpm packages on their [official website](https://www.skype.com/en/download-skype/skype-for-linux/)
Although it is called 'beta' I have successfully used it for about a year (it was alpha then), it supports almost all features that windows client provides and has far fewer problems then linux qt client.

* System: NixOS: 17.03
* Nix version: 1.11.8
* Nixpkgs version: 17.03.1033.99dfb6dce3"

**Comment by FRidh** [comment]
#25155 was merged
