### ISSUE TITLE
Package request: Azote

### ISSUE THREAD

**Issue by kevb1973** [NixOS/nixpkgs#251538]
**Project description**

Wallpaper manager for wlroots-based compositors and some other WMs

**Metadata**

* homepage URL: https://nwg-piotr.github.io/nwg-shell/azote
* source URL: https://github.com/nwg-piotr/azote
* license: GPL3.0, COLORTHIEF
* platforms: Linux

**Comment by gekoke** [comment]
Duplicate of #217492

**Comment by kevb1973** [comment]
Ah, somehow missed that. Closing.
