### ISSUE TITLE
Package request: Universal Android Debloater GUI

### ISSUE THREAD

**Issue by bangzek** [NixOS/nixpkgs#251561]
**Project description**

Cross-platform GUI written in Rust using ADB to debloat non-rooted android devices. Improve your privacy, the security and battery life of your device. 

**Metadata**

* homepage URL:
* source URL: https://github.com/0x192/universal-android-debloater
* license: gpl-3
* platforms: linux, macos, windows

**Comment by Ayhem-k** [comment]
How long does it take for a package to be created after a package request? I want to use it on NixOS but haven't found a way. I've tried everything possible, including both the normal and OpenGL versions, but couldn't get it to work. Additionally, this could be a great package to add to the Nix packages collection, as it helps with degoogling Android phones and reclaiming privacy by completely removing unnecessary apps, telemetry, spyware (Google apps), and more. I hope this package gets added soon to the Nix package collection."

**Comment by WolfangAukang** [comment]
Duplicate of #199619
