### ISSUE TITLE
fetchpatch with GitHub changed hashes

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#25154]
## Issue description

If you try to build something that uses `fetchpatch` to get patches from GitHub commits, the hash is different from what it used to be.

### Steps to reproduce

1. Try to build `octoprint-plugins.m33-fio` (you can force re-building the patch by changing one symbol in its `sha256` sum;
2. Observe completely different checksum.

Notice that for example `pcsxr` which gets patches from Debian doesn't suffer from this; the problem seems to be GitHub-specific.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

Tested also on `gpodder`. Example error:

```
output path ‘/nix/store/d5r4j5vgybgmnw4drsiqzwlgpbsbssfl-Fix-soundcloud-feeds.patch’ has sha256 hash ‘0jvk64ga1p2ik0ra8b4qzz5ybyw9clrfli7wd993y9rndjki0jj8’ when ‘0xkl1wnp46546jrzsnb9p0yj23776byg3nvsqwbblhqbsfipl48w’ was expected
```

Not sure if it's another source of nondeterminism or maybe d550c9071206013cb90ee9317080db82e286f69b is the reason (then we need to determine what hashes broke and fix them).

**Comment by abbradar** [comment]
Oh, I haven't noticed @vcunat already discovered this: https://github.com/NixOS/nixpkgs/commit/d550c9071206013cb90ee9317080db82e286f69b#commitcomment-21867547

**Comment by vcunat** [comment]
For short-term I suggest to either revert or just bring back the older version just for `fetchpatch`.

**Comment by dezgeg** [comment]
Yup. Reverted in 814772e93e1dd38d0a097521296350e7e0be4926.
