### ISSUE TITLE
lib/modules: how can we find the line number of the declaration of an option

### ISSUE THREAD

**Issue by inclyc** [NixOS/nixpkgs#251556]
### Describe the bug

For packages, we can easily find where is the derivation defined (`stdenv.mkDerivation` handled this I guess). But the declaration of options, there are only "path" information preserved. Can we preserve line numbers of option declarations also?

### Steps To Reproduce

For nix packages, we can extract the position by selecting `meta.position`:

```
Welcome to Nix 2.17.0. Type :? for help.

nix-repl> pkgs = import <nixpkgs> { } 

nix-repl> pkgs.python3.meta.position  
"/nix/store/5srgmzb2sqj4y8mngzi1bd2c116hnhrb-nixos-23.05.20230505.3e31380/nixos/pkgs/development/interpreters/python/cpython/default.nix:530"

nix-repl> 
```

And already implemented for some language service[^1], and also official nix[^2]: 

[^1]: goto-definition for nix lsp: [link](https://github.com/nix-community/nixd/blob/55d989cc0ab226aaf24300e7c5324003bca79c38/nixd/lib/Server/EvalWorker.cpp#L105)
[^2]: for official nix, it is used for finding package filename: [link](https://github.com/NixOS/nix/blob/50f40ac4c03bcb742cda29de04c40e1a29367acc/src/libexpr/attr-path.cc#L114)

However, options, there are only paths available:

```
nix-repl> nixosConfigurations.adrastea.options.nixpkgs.config.declarations
[ "/nix/store/bvyfa81gq72lghmk6vj0ny9aa4kfp0zn-source/nixos/modules/misc/nixpkgs.nix" ]
                                                                                   ^
                                                                                Can we provide any line numbers here?                                                                                                            

nix-repl>  
```

### Expected behavior

Some thing like: 

```diff
nix-repl> nixosConfigurations.adrastea.options.nixpkgs.config.declarations
- [ "/nix/store/bvyfa81gq72lghmk6vj0ny9aa4kfp0zn-source/nixos/modules/misc/nixpkgs.nix" ]   
+ [ "/nix/store/bvyfa81gq72lghmk6vj0ny9aa4kfp0zn-source/nixos/modules/misc/nixpkgs.nix:123" ]
nix-repl>  
```

### Notify maintainers

CC: @roberth @infinisil @edolstra (from `git blame` of `lib/modules.nix`)

### Metadata

N/A

**Comment by roberth** [comment]
We might be able to take advantage of `builtins.getUnsafeAttrPos` on the right attributes within `options`, or perhaps even the `mkOption` parameters such as `type` or `description`.
That could give a more accurate position including a line number.
The current solution attaches a file name to the whole module, which is more predictable than `getUnsafeAttrPos`, but also less valuable, and unreliable in its own way: no file info at all for modules that aren't imported by file. The current solution also doesn't understand `import`, although using `import` is questionable anyway.

**Comment by infinisil** [comment]
There is a recent PR for this! https://github.com/NixOS/nixpkgs/pull/249243

**Comment by inclyc** [comment]
Closing because #249243 has been merged
