### ISSUE TITLE
Package request: skiff-desktop

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#251526]
**Project description**
Skiff, now on a Linux Desktop near you!

**Metadata**
* homepage URL: https://github.com/FyraLabs/skiff-desktop/
* source URL: https://github.com/FyraLabs/skiff-desktop/
* license: gpl3
* platforms: unix

**Dependencies**
- [ ] [libhelium](https://github.com/NixOS/nixpkgs/issues/250997) (application framework)

**Comment by Ashvith10** [comment]
skiff-desktop branch is ready at https://github.com/Ashvith10/nixpkgs/tree/skiff-desktop. Looking for GTK maintainers to review this branch before I push this as PR.

**Comment by Aleksanaa** [comment]
> Looking for GTK maintainers to review this branch before I push this as PR.

You should make a PR first to let others review. I've seen your branch and it looks okay.

**Comment by Ashvith10** [comment]
@Aleksanaa I am closing this issue, as I do not want to continue.
