### ISSUE TITLE
Unable to install `displaylink`.

### ISSUE THREAD

**Issue by aloiscochard** [NixOS/nixpkgs#25169]
## Issue description

I'm trying to install `displaylink` support, as I got a usb adapter that provide display output as well.
The package fail to compile (tried with unstable, and then with latest successful trunk from hydra).

### Steps to reproduce

- Add `services.xserver.modules = [ config.boot.kernelPackages.displaylink ];` in your system configuration
- `nixos-rebuild switch`

## Technical details

* System: NixOS - 17.03.889.9626bc7db7 (Gorilla)
* Nix version:  1.11.8
* Nixpkgs version: 17.03.1033.99dfb6dce3

## Log

```
configure.in:17: installing './compile'
configure.in:6: installing './install-sh'
/tmp/nix-build-displaylink-1.1.62.drv-0/evdi-fe779940ff9fc7b512019619e24a5b22e4070f6a-src/module/evdi_modeset.c: In function 'evdi_modeset_init':
/tmp/nix-build-displaylink-1.1.62.drv-0/evdi-fe779940ff9fc7b512019619e24a5b22e4070f6a-src/module/evdi_modeset.c:375:2: error: implicit declaration of function 'drm_mode_create_dirty_info_property' [-Werror=implicit-function-declaration]
  drm_mode_create_dirty_info_property(dev);
  ^
configure.in:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
Makefile.am: installing './depcomp'
cc1: some warnings being treated as errors
make[4]: *** [/nix/store/p0la7ablq2mv27gv951frf4s2q1wx12v-linux-4.9.24-dev/lib/modules/4.9.24/source/scripts/Makefile.build:294: /tmp/nix-build-displaylink-1.1.62.drv-0/evdi-fe779940ff9fc7b512019619e24a5b22e4070f6a-src/module/evdi_modeset.o] Error 1
make[3]: *** [/nix/store/p0la7ablq2mv27gv951frf4s2q1wx12v-linux-4.9.24-dev/lib/modules/4.9.24/source/Makefile:1490: _module_/tmp/nix-build-displaylink-1.1.62.drv-0/evdi-fe779940ff9fc7b512019619e24a5b22e4070f6a-src/module] Error 2
make[2]: *** [Makefile:150: sub-make] Error 2
make[1]: *** [Makefile:24: __sub-make] Error 2
make[1]: Leaving directory '/nix/store/p0la7ablq2mv27gv951frf4s2q1wx12v-linux-4.9.24-dev/lib/modules/4.9.24/build'
make: *** [Makefile:55: module] Error 2
builder for ‘/nix/store/4x4xq042xzpzrnxsynn3phr7mp3ak3gq-displaylink-1.1.62.drv’ failed with exit code 2
building path(s) ‘/nix/store/c9b1pczhw6gkzwbmdn6cijb4lzqw4ni9-ghc-8.0.2-with-packages’
cannot build derivation ‘/nix/store/y15kvw1n9v2bhjda1ivimll7jirj537s-xserver.conf.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/gdnkkh0w3wf8qi5gqi7nwhbsmg895rg2-etc.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/x76andw3pa96ay2vq3csnn3vwcq7wmvg-google-talk-plugin-5.41.3.0’
building path(s) ‘/nix/store/m2dd2qp1niq5zbgg7gkypq5g3mkx27yv-grub-config.xml’
building path(s) ‘/nix/store/rq24rjj6dz60gm0pf4gg2f09pzal89vy-initrd-fsinfo’
building path(s) ‘/nix/store/y65wlaxyp9gr8rjingw6dxpcwxgdsla0-kernel-modules’
cannot build derivation ‘/nix/store/iffrqxi3d1hi7kx17360xqyxzwb9myj2-nixos-system-opus-17.09.git.5c7f466.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/iffrqxi3d1hi7kx17360xqyxzwb9myj2-nixos-system-opus-17.09.git.5c7f466.drv’ failed
```

I'm not sure what action I could take to investigate this?

Thanks for your help

**Comment by spinus** [comment]
There is compilation error, which can be incompatibilities between application and xorg. Make sure that application version/module version is compatible with xorg. If not probably some patch is needed.

**Comment by aloiscochard** [comment]
Okay makes sense, thanks for deciphering the log, I'll give it a try if I succeed at understanding the culprit.

Pinging @abbradar and @chris-martin, in case they are still using it or/and can help fixing this.

**Comment by chris-martin** [comment]
Sorry, I only used it briefly because I was really disappointed with how low the frame rate was.

**Comment by abbradar** [comment]
I'll try to update it but keep in mind I don't have the hardware -- hope it'll work.

**Comment by abbradar** [comment]
@aloiscochard Can you test https://github.com/abbradar/nixpkgs/commits/displaylink branch?

**Comment by aloiscochard** [comment]
@abbradar thanks a lot for giving help on this!

I just tried to rebuild my system using your branch, but I got what seems to be the same error but the log is somewhat different, so here it is:

```

**Comment by peterhoeg** [comment]
@aloiscochard, you are not using the correct branch. If you were you would see version 1.3.52 and not 1.1.62.


1. Set the proper display driver (in configuration.nix):
``` nix
{
  services.xserver.videoDrivers = [ "displaylink" ];
}
```

2. Then build against @abbraddar's branch:
``` shell
sudo nixos-rebuild boot -I nixpkgs=https://github.com/abbradar/nixpkgs/archive/displaylink.tar.gz
```

3. Reboot

**Comment by aloiscochard** [comment]
Thanks @peterhoeg, it solve the installation issue!

Still had problem to get my device running, but it might be device specific so I'm closing for now.

Thanks all

**Comment by abbradar** [comment]
I've pushed driver update to master and 17.03.
