### ISSUE TITLE
Cannot add account to etesync-dav

### ISSUE THREAD

**Issue by devurandom** [NixOS/nixpkgs#251635]
### Describe the bug

I cannot add my EteSync 2.0 account to etesync-dav in NixOS 23.05.20230819.4cdad15.

### Steps To Reproduce

1. I have an EteSync 2.0 account and I do have a username and password for it.
2. I have etesync-dav installed and running (`services.etesync-dav.enable = true`).
3. I navigate to http://localhost:37358/.web/add/ in my web browser.
4. I enter account username and password and press "Add".
5. etesync-dav responds with `NotFound` (see screenshot below).

### Expected behavior

The etesync account should be added to etesync-dav.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/63082/524322c2-2965-4f14-8b30-2021e4bfc869)

### Notify maintainers

@thyol, @Valodim (from https://search.nixos.org/packages?channel=23.05&show=etesync-dav&from=0&size=50&sort=relevance&type=packages&query=etesync-dav)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.10, NixOS, 23.05 (Stoat), 23.05.20230819.4cdad15`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jyniybinc** [comment]
Try using `https://api.etebase.com` as the `apiUrl`. It seems the default is `https://api.etesync.com`, which does not work.

https://github.com/NixOS/nixpkgs/blob/317484b1ead87b9c1b8ac5261a8d2dd748a0492d/nixos/modules/services/misc/etesync-dav.nix#L26

**Comment by devurandom** [comment]
> Try using `https://api.etebase.com` as the `apiUrl`. It seems the default is `https://api.etesync.com`, which does not work.
> 
> https://github.com/NixOS/nixpkgs/blob/317484b1ead87b9c1b8ac5261a8d2dd748a0492d/nixos/modules/services/misc/etesync-dav.nix#L26

Thanks a lot!

I changed:
```nix
    services.etesync-dav = {
      enable = true;
    };
```
to:
```nix
    services.etesync-dav = {
      enable = true;
      apiUrl = "https://api.etebase.com";
    };
```
in `/etc/nixos/configuration.nix`, ran `sudo nixos-rebuild switch`, and was able to log in on `http://localhost:37358/.web/add/`.

**Comment by Lcchy** [comment]
Just wanted to say that this also affected me and the proposed solution worked as well.
