### ISSUE TITLE
Package request: Vinegar

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#251690]
**Project description**
 An open-source, minimal, configurable, fast bootstrapper for running Roblox on Linux. 

Modern wrapper for running Roblox in Linux.

* homepage URL: https://vinegarhq.github.io/
* source URL: https://github.com/vinegarhq/vinegar
* license: GPL-3.0.
* platforms: linux

**Comment by robryk** [comment]
This seems to have been fixed by #270020

**Comment by Ryoschin** [comment]
Am I just missing something, or is the Studio not working by default?

**Comment by h7x4** [comment]
@Ryoschin In that case, I think you should open a new issue
