### ISSUE TITLE
pythonPackages.capstone is broken

### ISSUE THREAD

**Issue by kristoff3r** [NixOS/nixpkgs#25176]
## Issue description
The capstone python package is broken, because the patch applied to it has a different hash value than expected. Changing the hash seems to fix the issue, but I'm hesitant to make a pull request when I don't know why it changed.

ping @bennofs.

### Steps to reproduce
nix-shell -p python27Packages.capstone

```
output` path ‘/nix/store/jvzqbfqbz88bwg4wib1y30qzr3x34iaj-23fe9f36622573c747e2bab6119ff245437bf276.patch’ has sha256 hash ‘0gsj1sdzcprv1ha026f897qa2xzb8cm9d0gdyiax94ardp07dqpc’ when ‘0yizqrdlxqxn16873593kdx2vrr7gvvilhgcf9xy6hr0603d3m5r’ was expected
cannot build derivation ‘/nix/store/jxpyzi51b7j0b2jicdaxpgpccq0a1vck-python3.5-capstone-3.0.4.drv’: 1 dependencies couldn't be built
```
## Technical details

* System: 17.09pre105622.f0fac3b578 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09pre105622.f0fac3b578

**Comment by pbogdan** [comment]
Possibly related - https://github.com/NixOS/nixpkgs/issues/25154

**Comment by kristoff3r** [comment]
> Possibly related - #25154

Ah thanks, that is indeed the issue. I'll close this then, since the commit has already been reverted.
