### ISSUE TITLE
Steam fails to start, wrong permissions on bootstrap.tar.xz

### ISSUE THREAD

**Issue by dag-h** [NixOS/nixpkgs#251811]
### Describe the bug
Steam fails to start with the following message
```
cp: cannot create regular file '/home/dag/.local/Steam/bootstrap.tar.xz': Permission denied
```

### Steps To Reproduce
1. Run `steam`

### Expected behavior
Steam starts properly.

### Additional context
Removing the file allows Steam to start once, then fails with the same error on next startup.

### Notify maintainers
@jagajaga @jonringer 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11.20230819.d680ded`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/s4jqyj35hii03rs7j5n6vn7gpgp6ja81-source`
```

**Comment by jonringer** [comment]
This should be fixed by running `steam` again

https://github.com/NixOS/nixpkgs/blob/9e7b9ff8b5c00f4d9667d00dec7d9e1e836b6a79/pkgs/games/steam/fhsenv.nix#L51-L57

**Comment by jonringer** [comment]
For context, steam will download that file, and either they or our sandboxing makes it read-only. So when it goes to delete the file, it's unable to and hard fails.

**Comment by jonringer** [comment]
`/home/dag/.local/Steam/bootstrap.tar.xz` interesting that this doesn't use `$HOME/.local/share/Steam` though.... Do you have any `$XDG_...` variables set to non-standard paths?

**Comment by dag-h** [comment]
Oh that’s totally my bad, I had my `XDG_DATA_HOME` set to `$HOME/.local` instead of `$HOME/.local/share`.

**Comment by coreyoconnor** [comment]
Re-opening this because the hardcoded `~/.local/share/Steam` appears to be specific to certain environments - even if `XDG_DATA_HOME` is not changed.

**Comment by coreyoconnor** [comment]
I think, based on https://www.reddit.com/r/linux_gaming/comments/ar6llf/comment/egm8ec1/?utm_source=share&utm_medium=web2x&context=3 , that `~/.steam` is a legacy location. Which makes sense given the non-XDG location.

Not sure how to move steam, but probably safe to extend the paths checked for `bootstrap.tar.xz`. Will try that.

**Comment by coreyoconnor** [comment]
something like:

https://github.com/coreyoconnor/nixpkgs/commit/5ef6b1647d01ba40d02dc495f9dee4c9bfb6a4e1

**Comment by coreyoconnor** [comment]
I'm struggling to find why my steam install insists to use `~/.steam`. Everything that would determine this is at the defaults. *shrug* I'm guessing that fix is needed. I'll post a PR with the change proposed above.

**Comment by SuperSandro2000** [comment]
Steam doesn't allow changing that directory, so there is nothing we can do.
