### ISSUE TITLE
Update request: vintagestory 1.17.11 → 1.18.8

### ISSUE THREAD

**Issue by br4yd** [NixOS/nixpkgs#251815]
- Package name: vintagestory
- Latest released version: 1.18.8

- Current version on the unstable channel: 1.18.8
- Current version on the stable/release channel: 1.17.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Artturin 
@GiggleSquid 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Artturin** [comment]
Already updated on unstable, if you want it on stable then make a backport.

**Comment by GiggleSquid** [comment]
I'm not sure it's worth backporting anyways. It'll just have to be backported after every update.

Could you use something like
`sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable`

Then in configuration.nix
```
let
  nixpkgs-unstable = import <nixpkgs-unstable> { };
in
{
  environment.systemPackages = [
    pkgs.everythingElse
    nixpkgs-unstable.somePackage
  ];
}
```

**Comment by Artturin** [comment]
or `callPackage` the file from unstable
