### ISSUE TITLE
NixOS boots to tty1 instead of graphical session

### ISSUE THREAD

**Issue by lboklin** [NixOS/nixpkgs#251974]
### Describe the bug

I suspect this has been the case since SDDM was [updated to 0.20.0](https://github.com/NixOS/nixpkgs/pull/239389) (I've suffered and lived with it for a while). The OS loads into tty1 for some reason, and I have to manually go to tty2 for the display manager to start. I haven't messed with any defaults myself and my config did not change when this began happening, so something broke in an update.

### Steps To Reproduce

1. Use Plasma as DE (X11) on NixOS.
2. Turn on the computer.

### Expected behavior

Be greeted by SDDM/Plasma desktop after boot.

### Additional context

No apparent errors when checking with `journalctl -b`. SDDM starts automatically when I switch to tty2. Autologin is enabled (but I don't believe that matters).

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20230808.844ffa8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lboklin** [comment]
> Can you check whether SDDM actually runs on tty2? Normally it should start on tty7 (upstream default is tty1, and I have a hack to support this on my system, but nixpkgs patches it to tty7).

Above I said:

> I have to manually go to tty2 for the display manager to start.

Do you mean something else that isn't answered by that? What step would I have to take to answer your question?

**Comment by alois31** [comment]
Sorry if I wasn't clear. Normally SDDM automatically switches to the tty it started on, no matter what that might be. I want to know whether SDDM starts on tty2 (which it shouldn't) and the automatic switching doesn't work either, or if the switch to tty2 somehow causes SDDM to start on and switch to tty7.

Please log in on tty6 after SDDM has started, run `loginctl` and report the TTY column where USER is sddm.

**Comment by lboklin** [comment]
Thanks for clarifying. Here's the output:

```console
$ loginctl
SESSION  UID USER   SEAT  TTY
      1 1002 ludvig seat0 tty2
      3 1002 ludvig seat0 tty6

2 sessions listed.
```

**Comment by alois31** [comment]
I can reproduce the starting on the wrong tty, with the default x11 greeter only, but the switching still works (albeit quite slowly, it takes almost 10 seconds sometimes). It seems there is an upstream issue about the wrong tty issue too: https://github.com/sddm/sddm/issues/1650. Could you also try the x11-user greeter (`services.xserver.displayManager.sddm.settings.General.DisplayServer = "x11-user"`) and report whether that works? It seems to be unaffected by the tty issue on my system.

**Comment by lboklin** [comment]
> I can reproduce the starting on the wrong tty, with the default x11 greeter only, but the switching still works (albeit quite slowly, it takes almost 10 seconds sometimes). It seems there is an upstream issue about the wrong tty issue too: [sddm/sddm#1650](https://github.com/sddm/sddm/issues/1650). Could you also try the x11-user greeter (`services.xserver.displayManager.sddm.settings.General.DisplayServer = "x11-user"`) and report whether that works? It seems to be unaffected by the tty issue on my system.

Nice, that works for me

**Comment by lainconn** [comment]
@alois31 I am sorry if my question is stupid, but i am new to Nixos. Where do i have to paste the following code: `services.xserver.displayManager.sddm.settings.General.DisplayServer = "x11-user"`

**Comment by mksafavi** [comment]
I'm getting the same issue. is this an Nvidia problem?
It only happens when I switched back the LTS kernel  (6.6) and downgraded the nvidia driver to production(550).

**Comment by SuperSandro2000** [comment]
Can't reproduce this on Intel or Nvidia. Going to close since the initial issue is a year old.

**Comment by jaymehta-g** [comment]
> @alois31 I am sorry if my question is stupid, but i am new to Nixos. Where do i have to paste the following code: `services.xserver.displayManager.sddm.settings.General.DisplayServer = "x11-user"`

Thanks for this, I had the same issue and this worked!
