### ISSUE TITLE
linux: 6.4.10 -> 6.4.11 (and higher versions) breaks TPMs on some machines

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#251967]
### Describe the bug
When booted with 6.4.11 or higher, `/dev/tpm0` and `/dev/tpmrm0` disappeared from my machine (Huawei Matebook 16s). Notably, this resulted in `systemd-cryptsetup` not being able to unlock a LUKS volume provisioned using `systemd-cryptenroll` and its TPM support.

I am relying on this to allow my laptop to boot into a trusted system unattended (Secure Boot is enabled and I am using my own keys to sign UKIs).

(to be honest, I was spooked when my laptop suddenly requested a passphrase after an update, only to discover that booting into a previous configuration unlocked my LUKS volume as usual)

### Steps To Reproduce
1. Verify that `/dev/tpmrm0` exists on your machine when booted with 6.4.10 or lower. (You need a TPM on your machine)
2. Boot with 6.4.11 or higher.
3. Observe `/dev/tpm0` and `/dev/tpmrm0` not existing.

### Expected behavior
`/dev/tpm0` and `/dev/tpmrm0` exist, providing access to the TPM.

### Screenshots
n/a

### Additional context
Culprit (1541cb8cdd91fe141ea7c325120f0b5287719788) was revealed via bisection and a subsequent reboot to check whether a volume provisioned with `systemd-cryptenroll --tpm2-device=auto` unlocks without a passphrase.

6.4 currently corresponds to `linuxPackages_latest`. However, `linuxPackages` (at least 6.1.47) is also seemingly affected. I have not performed a bisection to see which update introduced this behavior on `linuxPackages`, but I suspect it might've been introduced in a neighboring update commit batch.

### Notify maintainers

Kernel maintainers: @TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice

**Comment by vikanezrimaya** [comment]
Using 738688f069d3a7add23e2efb5e19a1f279818624 just for the kernel packages and having rest of the system be latest unstable seemed to work, further confirming that this problem is kernel-related.

**Comment by Lyndeno** [comment]
LUKS decryption works for me on Linux 6.4.12. Unsure if a fix was implemented since 6.4.11

**Comment by vikanezrimaya** [comment]
@Lyndeno this issue is specifically about unlocking using a TPM. Passphrase unlocking works as usual.

I've traced the issue to `/dev/tpm0` and `/dev/tpmrm0` missing from the system somehow. I do not know why are they missing on the newer kernels while being present on the old. Loading modules with `tpm` in the name doesn't seem to help.

**Comment by Lyndeno** [comment]
> @Lyndeno this issue is specifically about unlocking using a TPM. Passphrase unlocking works as usual.

That is what I meant. TPM LUKS decryption is working for me on both of my systems.

**Comment by vikanezrimaya** [comment]
Oh, sorry for assuming. Perhaps it is only specific TPMs are broken. This looks like a kernel bug or a regression. I wonder if it's worth it to bisect the kernel itself to find it.

**Comment by vikanezrimaya** [comment]
I have amended the issue description to better reflect the problem.

**Comment by vikanezrimaya** [comment]
Looking at the [diff between `v6.4.10` and `v6.4.11`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/?id=v6.4.11&id2=v6.4.10&dt=2) I don't see any specific things that might be resulting in my TPM being broken. Weird.

**Comment by vikanezrimaya** [comment]
Duplicate of #250166. Closing.
