### ISSUE TITLE
List of strings in binaryCachePublicKeys borks nix.conf

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nixpkgs#25193]
## Issue description
`binaryCachePublicKeys` in `configuration.nix` looks deceptively like it takes a list of strings. However, if you do this with your public keys, it screws up `nix.conf`, making an illegal line. Since that file is in the read-only land, this is a pain in much butt. I recommend that either some assertions are made about `binaryCachePublicKeys` or its type be changed to just a string. Or it support multiple strings.

### Steps to reproduce
1. put more than one string in the list of strings in `binaryCachePublicKeys` in your `configuration.nix`.
1. `nixos-rebuild switch`
1. do any nixy thing, notice that now you can't because `nix.conf` is messed up.

If you want to fix it this works:
1. `sudo su`
1. `cp /etc/nix.conf /home/<user>/nix.conf`
1. fix the nix.conf file in the home folder
1. `export NIX_CONF_DIR=/home/<user>/`
1. `unset NIX_REMOTE`
1. make sure `configuration.nix` now only has one string in `binaryCachePublicKeys`
1. `nixos-rebuild switch`

## Technical details

* System: 17.03.873.0c041520c3 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.873.0c041520c3"

**Comment by fpletz** [comment]
This works for me. Do you have examples of strings that fail for you?

**Comment by Fresheyeball** [comment]
@fpletz can you show me your example? What worked for you?

**Comment by Fresheyeball** [comment]
@fpletz look, just having my public keys in multiple strings caused this. It's very easy to reproduce.

**Comment by fpletz** [comment]
This works for me: 

    nix.binaryCachePublicKeys = [
      "hydra.mayflower.de:9knPU2SJ2xyI0KTJjtUKOGUVdR2/3cOB4VNDQThcfaY="
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];

And produces:

    binary-cache-public-keys = hydra.mayflower.de:9knPU2SJ2xyI0KTJjtUKOGUVdR2/3cOB4VNDQThcfaY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

**Comment by Fresheyeball** [comment]
This is what I had:

```
    binaryCachePublicKeys =
      [ "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" 
       "hydra.dev.somatix.ai-1:H6ocVYt1qB/9NPLKy9OBsyrhbIGnPQkHxnoXlOD5nPs=" 
       "ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=" ];
```

And it messed up. Or could I have had it wrong another way?

**Comment by mmahut** [comment]
Are there any updates on this issue, please?
