### ISSUE TITLE
Package request: LunarVim

### ISSUE THREAD

**Issue by oceaster** [NixOS/nixpkgs#251986]
LunarVim is a NeoVim distribution. By default NixOS is unable to install LunarVim due to it trying to install pip modules to the system executable which NixOS doesn't allow.

**Metadata**

* homepage URL: https://www.lunarvim.org/
* source URL: https://github.com/LunarVim/LunarVim
* license: GNU GENERAL PUBLIC LICENSE
* platforms: Linux, MacOS, Windows, Docker

**Comment by kashw2** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/178488
