### ISSUE TITLE
linuxPackages_custom does not compile linux with parallelism

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#25208]
## Issue description

Despite of `nix.buildCores` being set to `16` or `0`, kernel make is run with `-j1` explicitly when a custom linux kernel is specified.

### Steps to reproduce

Set

```
  boot.kernelPackages = pkgs.linuxPackages_custom {
    version = "4.11.0-rc8";
    src = pkgs.fetchurl {
      url = "mirror://kernel/linux/kernel/v4.x/testing/linux-4.11-rc8.tar.xz";
      sha256 = "acda201845186cb347b036f23f9bea4990f03f4f604e3bf30837284d99567348";
    };
    configfile = /etc/nixos/kernel.config;
  };

  nix.maxJobs = 16;
  nix.buildCores = 0;
```

and run `sudo nixos-rebuild switch`. Observe the `make -j` being run.

## Technical details

* System: 17.09pre105622.f0fac3b578 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8

**Comment by evrim** [comment]
ping @thoughtpolice @joachifm 

Is it possible to fix commonMakeFlags in manual-config.nix? 
It takes so long with the current -j1.

**Comment by joachifm** [comment]
Looks like this was fixed by https://github.com/NixOS/nixpkgs/pull/31887. Please reopen if that is not the case.
