### ISSUE TITLE
Build failure: diffoscope

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#252045]
### Steps To Reproduce

1. `nix-build -A diffoscope` (on x86_64-linux, at least)

### Build log

```
=================================== FAILURES ===================================
_____________________________ test_nested_symlink ______________________________

nested_differences = [<Difference file list -- file list []>, <Difference filetype from file(1) -- filetype from file(1) []>, <Difference dir/link -- dir/link []>, <Difference dir/text -- dir/text []>]

    @skip_unless_tools_exist("cpio")
    @skip_unless_tool_is_at_least("dumpimage", dumpimage_version, "2021.01")
    @skip_unless_tools_exist("fdtdump")
    def test_nested_symlink(nested_differences):
>       assert nested_differences[1].source1 == "dir/link"
E       AssertionError: assert 'filetype from file(1)' == 'dir/link'
E         - dir/link
E         + filetype from file(1)

tests/comparators/test_fit.py:128: AssertionError
_________________________ test_nested_compressed_files _________________________

nested_differences = [<Difference file list -- file list []>, <Difference filetype from file(1) -- filetype from file(1) []>, <Difference dir/link -- dir/link []>, <Difference dir/text -- dir/text []>]

    @skip_unless_tools_exist("cpio")
    @skip_unless_tool_is_at_least("dumpimage", dumpimage_version, "2021.01")
    @skip_unless_tools_exist("fdtdump")
    def test_nested_compressed_files(nested_differences):
>       assert nested_differences[2].source1 == "dir/text"
E       AssertionError: assert 'dir/link' == 'dir/text'
E         - dir/text
E         + dir/link
```

### Additional context

https://hydra.nixos.org/build/232823318. Reproduced on latest master (efed6046cf64a6c64d0f62ff38840a238e882adc).

### Notify maintainers

@dezgeg @danielfullmer @RaitoBezarius 

### Metadata

n/a, see Hydra.

**Comment by RaitoBezarius** [comment]
It is a known issue from staging fallout. I am on vacations though, so I
hope other maintainers will be able to take a look.

It is suspected to be buried in the file binary upgrade.

Le mar. 29 août 2023 à 00:57, Andrew Marshall ***@***.***> a
écrit :

**Comment by tjni** [comment]
It seems they did in test_cpio.py and test_uimage.py but missed the ones in tests/comparators/test_fit.py. It should be easy to fix following that same pattern.

**Comment by aij** [comment]
Thanks! I hit this and tracked it down to the `staging-next` merge in f900e733c1602b4c46064a9ef0514bb2345a8949. 

I see the fix hit `nixos-unstable-small` today and it works for me. :+1:

**Comment by aij** [comment]
Filed https://github.com/NixOS/nixpkgs/issues/256896 for the new issue since it's unrelated other than that the diffoscope tests are failing again.
