### ISSUE TITLE
Ipv6 support for https://nixos.org

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#25203]
## Issue description

According to this document https://aws.amazon.com/blogs/aws/aws-ipv6-update-global-support-spanning-15-regions-multiple-aws-services/ there is ipv6 support for eu-west-1, where the website is apparently hosted. When we also have ipv6 support for the homepage, ipv6 support is complete.

### Steps to reproduce

```
$ dig AAAA nixos.org

; <<>> DiG 9.10.4-P6 <<>> AAAA nixos.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27168
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nixos.org.                     IN      AAAA

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 25 10:03:41 CEST 2017
;; MSG SIZE  rcvd: 38
```

**Comment by edolstra** [comment]
The NixOS/nixos-org-configurations repo is more appropriate for this kind of issue.

**Comment by Mic92** [comment]
moved to https://github.com/NixOS/nixos-org-configurations/issues/29
