### ISSUE TITLE
Package request: plex-desktop

### ISSUE THREAD

**Issue by Guekka** [NixOS/nixpkgs#252131]
**Project description**

Streaming media player for Plex

**Metadata**

* homepage URL: https://www.plex.tv/fr/media-server-downloads/#plex-app
* source URL: https://snapcraft.io/plex-desktop
* license: proprietary
* platforms: linux

---

Unfortunately, this app is only available as a Snap or a Flatpak. It looks like Snap is easier to unpack, as we have [one example with Spotify](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spotify/linux.nix).

There is also [an AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plex-desktop), which appears to be unmaintened.

**Comment by cenunix** [comment]
would also appreciate this being packaged, the flatpak version does not start for me ( I don't like using flatpak anyways).

**Comment by Kernald** [comment]
It also supports Darwin and Windows.

**Comment by Redhawk18** [comment]
Just to be clear this is not this package

https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/video/plex-media-player/default.nix#L47

This is a completely different package with different build steps that just looks the exact same.

**Comment by detroyejr** [comment]
Submitted a draft PR that adds this to nixpkgs. What's there now works on my machine&trade; (3 of them). I'd appreciate people testing this out on different hardware and suggesting any improvements that makes this more reliable. I have a couple more things I'd like to do before officially submitting this.
