### ISSUE TITLE
Unable to pass crossSystem as an argument to nix-build

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#25215]
## Issue description

Trying to pass `--arg crossSystem something` has no effect on the build.

### Steps to reproduce

With `aarch64.nix` with contents:

```nix
let
  aarch64 = rec {
    config = "aarch64-linux-gnu";
    bigEndian = false;
    arch = "aarch64";
    withTLS = true;
    libc = "glibc";
    platform = (import ./lib/systems/platforms.nix).aarch64-multiplatform;
    inherit (platform) gcc;
    openssl.system = "linux-generic64";
  };

in

import ./default.nix {
  crossSystem = aarch64;
}
```

and `crosspkgs.nix` with contents:

```nix
rec {
  config = "aarch64-linux-gnu";
  bigEndian = false;
  arch = "aarch64";
  withTLS = true;
  libc = "glibc";
  platform = (import ./lib/systems/platforms.nix).aarch64-multiplatform;
  inherit (platform) gcc;
  openssl.system = "linux-generic64";
}
```

Observe that `nix-build aarch64.nix -A hello` produces the expected (cross compiled) `hello`.

Observe that `nix-build ./. --arg crossSystem 'import ./crosspkgs.nix' -A pkgs.hello` produces the unexpected native `hello` derivation.

## Technical details

- System: 17.03.945.5acb454e2a (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: 17.09pre-git

**Comment by matthewbauer** [comment]
I suspect the issue is with impure.nix because this seems to work fine:

```sh
nix-build pkgs/top-level/default.nix --arg crossSystem "import ./crosspkgs.nix" --arg localSystem "{system = builtins.currentSystem;}" -A pkgs.hello
```

**Comment by dezgeg** [comment]
It's actually how nix handles `--arg` which I'd consider a bug. The function in `impure.nix` doesn't have `crossSystem` as an explicit named parameter but rather has `{ ... } @ args:` and Nix doesn't know how to pass `--arg`s to those, for some reason.

**Comment by matthewbauer** [comment]
Interesting... 281e690be6832f46f28dd8f22c7f2e6119ea44b4 is a temporary fix for that but I wonder if  there is an open issue for this in Nix? At the very least it needs to be mentioned in documentation. I peaked around in Nix internals before giving up. But the bad logic is probably right here: https://github.com/NixOS/nix/blob/master/src/libexpr/eval.cc#L1110

**Comment by expipiplus1** [comment]
One improvement would be to error out when arguments are ignored in this
manner.

**Comment by Ericson2314** [comment]
Fixed for now with https://github.com/NixOS/nixpkgs/pull/25301 . I suppose the conversation about Nix itself​ should talk place in that linked issue.
