### ISSUE TITLE
rPackages: IRKernel

### ISSUE THREAD

**Issue by jbaum98** [NixOS/nixpkgs#25211]
## Issue description

`IRKernel` was removed in commit f4595fa55533. Why was this, and will it be added back?

**Comment by Mic92** [comment]
why it was removed (quote from the commit message):

```
r-modules: drop broken irkernel package set

We can no longer update that package set since, apparently, it has moved
to a different packaging scheme.
```

Will it be back? It will be added back, if someone fix the expression and opens a pull request.

**Comment by jbaum98** [comment]
What does it mean that it has moved to a different packaging scheme? I'd be up to try and fix it but I don't understand what's wrong.

**Comment by FRidh** [comment]
perhaps @peti can explain

**Comment by peti** [comment]
IRKernel is distributed in a way that differs from other CRAN repositories. I don't know the details myself, I just know that the `generate-r-packages.R` tool we use to generate all other package sets (and which generated the IRKernel set in the past) no longer works. If someone else figures out how to remedy that issue, we'll be more than happy to merge such a PR. Personally, I am not going to work on that subject, though.

**Comment by krey** [comment]
For anyone else running into this issue, JuniperKernel is now in CRAN (and hence also in nixpkgs), and works just as well as IRKernel
