### ISSUE TITLE
Unable to cross compile pkgs.gcc

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#25212]
## Issue description

One is unable to cross compile a native wrapped gcc.

### Steps to reproduce

Given `cross.nix` in the nixpkgs root

```nix
let
  aarch64 = rec {
    config = "aarch64-linux-gnu";
    bigEndian = false;
    arch = "aarch64";
    withTLS = true;
    libc = "glibc";
    platform = (import ./lib/systems/platforms.nix).aarch64-multiplatform;
    inherit (platform) gcc;
    openssl.system = "linux-generic64";
  };
in
import <nixpkgs> {
  crossSystem = aarch64;
}
```

The command `nix-instantiate --show-trace cross.nix -A pkgs.gcc` fails with the following error message:

```
error: while evaluating the attribute ‘shell’ of the derivation ‘gcc-wrapper-5.4.0-aarch64-linux-gnu-aarch64-linux-gnu’ at /tmp/src/nixpkgs/pkgs/stdenv/adapters.nix:87:11:
value is a string while a set was expected, at /tmp/src/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:283:13
```

It is possible to build `pkgs.gcc.cc` however.

It is possible to build `pkgs.buildPackages.gcc` too.

It is possible to build `pkgs.gcc` without `crossSystem` being set.

## Technical details

* System: 17.03.945.5acb454e2a (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09pre-git

**Comment by expipiplus1** [comment]
If I hack together something to get the correct shell, the glibc dependency in the cross compiled gcc wrapper is incorrect: it is for the build system, not the host.

**Comment by CMCDragonkai** [comment]
What's the difference between "wrapped" gcc and not-wrapped?

**Comment by Ericson2314** [comment]
@bgamari does your work now fix this?

**Comment by hlandau** [comment]
@Ericson2314 This is still failing. Trying to build `-A pkgs.gcc`:

```
checking attr/xattr.h usability... no
checking attr/xattr.h presence... no
checking for attr/xattr.h... no

FATAL ERROR: attr/xattr.h does not exist.
Install the extended attributes (attr) development package.
Alternatively, run "make install-dev" from the attr source.
builder for ‘/nix/store/b0fk9rjavxi7v24m1p5ljk0901d53ivl-acl-2.2.52-aarch64-linux-gnu.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/lcs4f4xdjhm8jb8czf41r7172pffjx9q-coreutils-8.28-aarch64-linux-gnu.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/7gsd921a1b583lhg6y80svvwlscdh0ww-gmp-6.1.2-aarch64-linux-gnu’, ‘/nix/store/dlbb6hqw1c0qc9pz5ypx7dv7qcr84f4i-gmp-6.1.2-aarch64-linux-gnu-info’, ‘/nix/store/pdk5cn5ipdqdg48hrixrn8lqkr0ly9zz-gmp-6.1.2-aarch64-linux-gnu-dev’
cannot build derivation ‘/nix/store/rw53v088bfmsb8xbdpv6f24vr3ysnyyd-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/rw53v088bfmsb8xbdpv6f24vr3ysnyyd-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu.drv’ failed
```

Looks like the issue is the right includes aren't being included in the environment variables for the `acl` package build environment because the setup scripts don't emit them for buildInputs when crossing; the `acl` package's `nativeBuildInputs` (gettext) are present in the build environment, but not the `buildInputs` (attr).

I used the above cross.nix, and nixpkgs master.

**Comment by bgamari** [comment]
```
checking attr/xattr.h usability... no
checking attr/xattr.h presence... no
checking for attr/xattr.h... no

FATAL ERROR: attr/xattr.h does not exist.
```
I have also observed this on my branch rebased onto `master` (as of a few days ago).

**Comment by bgamari** [comment]
To fill in some further details on the failure mentioned above. The failing derivation is `/nix/store/2i6zfkwgfp601rmrvxrgda1bnaw1jwnf-acl-2.2.52-armv7l-unknown-linux-gnueabihf.drv`. `configure` is invoked with ` --build=x86_64-unknown-linux-gnu --host=armv7l-unknown-linux-gnueabihf` as expected. However, the environment tells a different story,
```
declare -x BUILD_AR="armv7l-unknown-linux-gnueabihf-ar"
declare -x BUILD_AS="armv7l-unknown-linux-gnueabihf-as"
declare -x BUILD_CC="armv7l-unknown-linux-gnueabihf-gcc"
declare -x NIX_BUILD_CC="/nix/store/jmsx7j3d9p08v0i5rrrx0clh0mglrn3w-armv7l-unknown-linux-gnueabihf-gcc-cross-wrapper-6.4.0-armv7l-unknown-linux-gnueabihf-stage-final"
declare -x NIX_BUILD_CC="/nix/store/jmsx7j3d9p08v0i5rrrx0clh0mglrn3w-armv7l-unknown-linux-gnueabihf-gcc-cross-wrapper-6.4.0-armv7l-unknown-linux-gnueabihf-stage-final"
declare -x NIX_BUILD_CC="/nix/store/jmsx7j3d9p08v0i5rrrx0clh0mglrn3w-armv7l-unknown-linux-gnueabihf-gcc-cross-wrapper-6.4.0-armv7l-unknown-linux-gnueabihf-stage-final"
declare -x nativeBuildInputs="/nix/store/gnlarkmq2kfmmw6y4qadbmph0m446alp-gettext-0.19.8-armv7l-unknown-linux-gnueabihf"
declare -x propagatedBuildInputs="/nix/store/s1njv9ykr485dsmsxm86k24yf5gwlrdj-attr-2.4.47-armv7l-unknown-linux-gnueabihf-dev"
declare -x propagatedNativeBuildInputs=""
```

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/32403 + https://github.com/NixOS/nixpkgs/issues/26805 fixed this.

**Comment by hlandau** [comment]
@Ericson2314 This still doesn't seem to be fixed. With staging, it eventually gets to this point:
```
$ nix-build cross.nix -A pkgs.gcc
these derivations will be built:
  /nix/store/07qrqrr5kx7y8y9i2j9xps3by2n3z3r8-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu.drv
building path(s) ‘/nix/store/9w461vzr3p5hzp7qg5ax0adznsmvq1jx-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu-man’, ‘/nix/store/hxggaky813xwqx933kr6wadmxsak5yk4-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu’
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
/nix/store/ai9wa11232w5dpws5fbgp3m224w0n2xf-stdenv/setup: line 1224: /nix/store/27cmm567jkagbap1ip7q4kva784w7cb5-coreutils-8.29-aarch64-linux-gnu/bin/mkdir: cannot execute binary file: Exec format error
builder for ‘/nix/store/07qrqrr5kx7y8y9i2j9xps3by2n3z3r8-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu.drv’ failed with exit code 126
error: build of ‘/nix/store/07qrqrr5kx7y8y9i2j9xps3by2n3z3r8-gcc-wrapper-6.4.0-aarch64-linux-gnu-aarch64-linux-gnu.drv’ failed
```

cross.nix:
```
let
  aarch64 = rec {
    config = "aarch64-linux-gnu";
    bigEndian = false;
    arch = "aarch64";
    withTLS = true;
    libc = "glibc";
    platform = nixpkgs.lib.systems.platforms.aarch64-multiplatform;
    inherit (platform) gcc;
    openssl.system = "linux-generic64";
  };

  nixpkgs = import ./default.nix { crossSystem = aarch64; };
in nixpkgs
```

**Comment by Ericson2314** [comment]
@hlandau that's just a problem with the wrapper script. Should be easy to fix.

**Comment by TravisWhitaker** [comment]
@Ericson2314 What is the easy fix for the wrapper script? I just ran into this.

**Comment by TravisWhitaker** [comment]
It looks like cc-wrapper's expression goes to the trouble to figure out what coreutils_bin should be but never actually uses it. Just tried doing the dumbest possible thing, replacing `mkdir` with `${coreutils_bin}/bin/mkdir` and it seems to work.

**Comment by Ericson2314** [comment]
@TravisWhitaker I'd have said, make sure coreutils (like every tool in cc-wrapper) comes from `buildPackages`. But it looks like it does? this seems to be the coreutils in stdenv causing problems, which is very odd, all the tools in stdenv should come from `buildPackages` too.

**Comment by TravisWhitaker** [comment]
Ah sorry, that might've been a red herring, I hit the same issue at a later stage when cross compiling.

I don't see how the tools in cc-wrapper always come from `buildPackages` (and this seems to be confirmed by `cannot execute binary file: Exec format error`). It looks like cc-wrapper gets called all over the place without `buildPackages` specified (it defaults to `{}`) in `all-packages.nix`. In `pkgs/stdenv/*/default.nix`, it looks like `coreutils` comes from the previous bootstrapping phase "prevStage", is that supposed to always contain executables that run on the current `buildPlatform`?

**Comment by TravisWhitaker** [comment]
I was wrong again; `ccWrapperFun` uses `callPackage` so inherits the `buildPackages` in scope in `all-packages.nix`. 

This (https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/linux/default.nix#L96) still seems a bit suspicious  me, though; are packages from a previous stage always executable on the current `buildPlatform`?

**Comment by Ericson2314** [comment]
> Are packages from a previous stage always executable on the current `buildPlatform`?

Yes! These are the axioms that makes the cross infrastructure tick:
 - `buildPackages.hostPlatform = pkgs.buildPlatform`
 - `buildPackages.targetPlatform = pkgs.hostPlatform`
 - `buildPackages.targetPackages = pkgs`
 - `pkgs = targetPackages.buildPackages`
 ...

The annoying cruft is that per https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/booter.nix#L101-L104 is that `{build,target}Packages` doesn't always resolve the adjacent stages, which used by the legacy native stdenv boostrapping. When those are redone, that will go away. The good thing is since those bad stages are all native, the platform (as opposed to package set) rules are still true.

**Comment by TravisWhitaker** [comment]
Ahh, thanks for the explanation. This is a lot clearer now.

For what it's worth, this tweak to cc-wrapper allowed me to cross compilation working.

```
  coreutils_bin = if (buildPlatform != hostPlatform)
                  then getBin buildPackages.coreutils
                  else (if nativeTools
                        then ""
                        else getBin coreutils
                       );
```

I'm sure some part of that is redundant, but it seems to work.

**Comment by Ericson2314** [comment]
Ah I found the problem. The short answer is cc-wrapper depends on binutils, whose setup hooks changes the PATH to include .

The long answer has to do with a) the fuzzy way deps work on master b) the non-compositionality of `.override`, two separate nasty corners of things. The wrappers probably shouldn't change the PATH anyways, but more immediately that setup hook shouldn't be run, because bintools-wrapper is a run-time dep. It indeed wouldn't be because cross gets rid of the fuzzy dep logic that runs it, except `stdenvNoCC` `.override`s stdenv again throwing away the previous changes. Shit show!

I need to make a patch making it easier to opt out of fuzzy-deps anyways, and I'll include this in that.

**Comment by TravisWhitaker** [comment]
Is there some mechanism in particular you mean by "fuzzy deps?"

**Comment by TravisWhitaker** [comment]
Oh, and thanks for all your work on cross compilation!

**Comment by Ericson2314** [comment]
Yes, https://github.com/NixOS/nixpkgs/commit/469fd8983276d851c19827cd9e78a89dd53a5914 precisely. That commit was a greenfield, but imitates the previous behavior for a smoother transition. Soon, we ought to have a branch working towards its obsolescent, which is best way to ensure cross doesn't bit-rot going forward.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/40529 and https://github.com/NixOS/nixpkgs/pull/40539 should fix the cc-wrapper problem

**Comment by expipiplus1** [comment]
Yay, thanks John!
