### ISSUE TITLE
Package request: firefox-wayland

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#252161]
**Project description**
Firefox built without Xorg dependencies 

Firefox recently introduced build options to create Firefox, excluding Xorg dependencies and vice versa.
https://www.phoronix.com/news/Firefox-116-Available

* homepage URL: https://www.mozilla.org/en-US/firefox/
* source URL: https://hg.mozilla.org/mozilla-central/
* license: MPL 2.0
* platforms: linux

**Comment by sanderhollaar** [comment]
https://www.mozilla.org/en-US/firefox/121.0beta/releasenotes/
> On Linux, Firefox now defaults to the Wayland compositor when available instead of XWayland.

**Comment by Nyabinary** [comment]
> https://www.mozilla.org/en-US/firefox/121.0beta/releasenotes/
> 
> > On Linux, Firefox now defaults to the Wayland compositor when available instead of XWayland.
> 
> #269244 - firefox-{beta,devedition}-unwrapped: 120.0b9 -> 121.0b2

Isn't the same thing, I mean to build firefox without xorg dependencies leading to fewer dependencies. But it is nice that they're finally defaulting to Wayland lol

**Comment by vcunat** [comment]
The nixpkgs firefox was defaulting to wayland already.

**Comment by mweinelt** [comment]
> Isn't the same thing, I mean to build firefox without xorg dependencies leading to fewer dependencies.

This means having to build multiple flavors of the same package, because you would want it cached. I'm not sure that the benefit outweights the cost here.
