### ISSUE TITLE
sudo-rs: package and use as replacement for 'sudo'

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#252193]
**Project description**

`sudo-rs` (a Rust-written `sudo`-compatible replacement) is having a stable first release: https://www.memorysafety.org/blog/sudo-first-stable-release/

It would be nice to have this in nixpkgs, and have an option to use it in place of the traditional sudo.

(this would be in addition to `please` that is available in Nixpkgs already, which is a sudo-alternative also written in rust)

**Metadata**

* homepage URL: https://github.com/memorysafety/sudo-rs and more info: https://www.memorysafety.org/initiative/sudo-su/
* source URL: https://github.com/memorysafety/sudo-rs
* license: **mit** and **apl2**
* platforms: **unix**, **linux** (maybe darwin too?)

**Comment by pvdrz** [comment]
Just dropping my 2 cents: sudo-rs only supports linux for now.

**Comment by Nyabinary** [comment]
Needs an option too

**Comment by R-VdP** [comment]
@Nyabinary there's already a `package` option in the existing sudo module that we could use to select sudo-rs.
But it's currently not a drop-in replacement and so the module would need some adapting to cater to both sudo and sudo-rs.

**Comment by alsvartr** [comment]
> On it ;3

Wouldn't work. Sudo-rs needs rust 1.70, which is in unstable.

**Comment by yanganto** [comment]
Hi @alsvartr,
Rust 1.70 is stable at 2023, Jun 01.
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html

Just excited about this, so subscribe to this issue.  
Is it possible to upgrade the Rust version to stable? 
If something I can help with, please kindly let me know.

**Comment by Nyabinary** [comment]
You can just package sudo-rs for the unstable repo too.

**Comment by yanganto** [comment]
> You can just package sudo-rs for the unstable repo too.

Hmm... I think it is not really used `sudo-rs` even in unstable now, even with #252418
The package is built but there is no optional toggle to switch `sudo` to `sudo-rs` for now

```nix
  config = mkIf cfg.enable {
    assertions = [
      { assertion = cfg.package.pname != "sudo-rs";
        message = "The NixOS `sudo` module does not work with `sudo-rs` yet."; }
    ];
```

**Comment by yanganto** [comment]
> You can just package sudo-rs for the unstable repo too.

Got it, I will try unstable first.

**Comment by mkg20001** [comment]
I've created https://github.com/NixOS/nixpkgs/issues/253465 to track the remaining tasks
