### ISSUE TITLE
Package request: python310Packages.wikitextparser

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#252159]
**Project description**

A simple to use WikiText parsing library for [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki).

The purpose is to allow users easily extract and/or manipulate templates, template parameters, parser functions, tables, external links, wikilinks, lists, etc. found in wikitexts.

**Metadata**

* homepage URL: https://pypi.org/project/wikitextparser/ 
* source URL: https://github.com/5j9/wikitextparser
* license: gpl-3.0
* platforms: unix, linux

**Comment by Steinhagen** [comment]
This is added in PR [#253303](https://github.com/NixOS/nixpkgs/pull/253303).

**Comment by Steinhagen** [comment]
The package was merged into master.
