### ISSUE TITLE
Librewolf can't be updated with update script

### ISSUE THREAD

**Issue by squalus** [NixOS/nixpkgs#252276]
### Describe the bug
Librewolf can't be updated to latest version with the existing update script.

Git submodules were removed. They were replaced with [`wget` commands](https://gitlab.com/librewolf-community/browser/source/-/blob/32e0ca7bf6a23995965d758d160aa603c2b20980/scripts/librewolf-patches.py#L116). There are a few reproducibility deficiencies. First, the files are fetched from a moving target (master branch). Second, there is no hash pinning or checking.

Doing this in a Nix build without upstream changes would involve making a guess about the settings repository version. We could look at the time of commit (or tag, or release?) in the Librewolf repository, then find the closest matching commit in the settings repository. Then, we could record the rev and sha256 hash in a JSON lock file in nixpkgs.

I probably won't be available to work on this for a few weeks.

**Comment by squalus** [comment]
Upstream issue: https://codeberg.org/librewolf/issues/issues/1590

**Comment by samhh** [comment]
The latest version of Firefox, and therefore presumably Librewolf, includes a fix [^fix] for a critical security vulnerability [^vuln]. Could we possibly push this one release out manually?

[^fix]: https://www.mozilla.org/en-US/firefox/117.0.1/releasenotes/
[^vuln]: https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/
