### ISSUE TITLE
mozc on fcitx fails to work on Chromium

### ISSUE THREAD

**Issue by mt-caret** [NixOS/nixpkgs#25228]
## Issue description

after a `nixos-rebuild switch --upgrade`, fcitx cannot switch to mozc __only in chromium__.
journalctl gives me
```
Apr 26 11:15:59 dn xsession[1721]: [1964:1964:0426/111559.859723:ERROR:browser_main_loop.cc(279)] Gtk: GModule (/nix/store/9phpwkfbpfp7cwjm00lxz6vy6qbrnkpx fcitx-with-plugins-4.2.9.1/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so) initialization check failed: GLib version too old (micro mismatch)
Apr 26 11:15:59 dn xsession[1721]: [1964:1964:0426/111559.859743:ERROR:browser_main_loop.cc(279)] Gtk: Loading IM context type 'fcitx' failed
```

### Steps to reproduce

```nix
...
i18n.inputMethod = {
  enabled = "fcitx";
  fcitx.engines = with pkgs.fcitx-engines; [ mozc ];
}
...
programs.chromium.enable = true;
...
```

`nixos-rebuild switch --upgrade # with nixos-unstable`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre106117.c90998d5cf (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.8

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre106117.c90998d5cf"

* `fcitx --version`

fcitx version: 4.2.9.1

* `chromium --version`

Chromium 57.0.2987.133

**Comment by ericsagnes** [comment]
Thanks for reporting! Will look into this.
