### ISSUE TITLE
Package request: Onedriver

### ISSUE THREAD

**Issue by Lordraven19** [NixOS/nixpkgs#252398]
**Project description**

onedriver is a native Linux filesystem for Microsoft OneDrive. It contains GUI and CLI tools for mounting Onedrive cloud shares as local drives, downloading files accessed on demand.

**Metadata**

* homepage URL: https://github.com/jstaf/onedriver
* source URL: https://github.com/jstaf/onedriver
* license: gpl3
* platforms: linux

**Comment by Plarpoon** [comment]
I am very excited about this one, I am actually a DM in a D&D campaign and onedriver has always been my best tool for rapid storage and edit of the stuff. Thanks everyone!
