### ISSUE TITLE
akonadiselftest does not show icons

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#25238]
## Issue description

akonadiselftest, a diagnostic part of akonadi, does not show the icons with the tests. This makes it hard to read the status.

akonadi, installed in an empty user account should be fully functional, even when there is no other part of KDE, such as Plasma, installed.

### Steps to reproduce

* setup NixOS system without KDE
* log into X with xterm
* install akonadi
* start akonadiselftest
* observe that no icons are shown for error, warning or ok.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03.902.536d3..
* Nix version: (run `nix-env --version`)
1.11.8
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.03.902.536d3..

wrong:
![screenshot_20170425_094605](https://cloud.githubusercontent.com/assets/608417/25424969/88c682e2-2a6a-11e7-9cc8-368fb93f069f.png)

correct:
![correct](https://cloud.githubusercontent.com/assets/608417/25425083/052c87d2-2a6b-11e7-9c3a-52d94131bcae.png)

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by vandenoever** [comment]
In NixOS 19.03, the icons are shown. This issue has been fixed.
