### ISSUE TITLE
Package request: karousel

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#252349]
**Project description**

Karousel is a KWin tiling script with scrolling, similar to window managers such as [PaperWM](https://github.com/paperwm/PaperWM) and [Cardboard](https://gitlab.com/cardboardwm/cardboard).

**Metadata**

* homepage URL:
* source URL: https://github.com/peterfajdiga/karousel
* license: GPL-3.0
* platforms: linux (KDE)

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/335040 (https://github.com/NixOS/nixpkgs/pull/335040/commits/32109a4116bfb4bb07046eafebb344675f27f378), this package is available as `kdePackages.kdePackages.karousel`
