### ISSUE TITLE
Build failure: PACKAGENAME

### ISSUE THREAD

**Issue by sammyfilly** [NixOS/nixpkgs#252330]
<details><summary>Details</summary>
<p>

</p>
</details> # Steps To Reproduce

1. build *X*

### Build log

```
log here if short otherwise a link to a gist
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
mail: openworkspacesource@gmail.com

**Comment by mkg20001** [comment]
You haven't provided any details. Please open a new issue with actual details about the problem.
