### ISSUE TITLE
resholve API: Can’t write keep directive with absolute Nix-store path

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#252360]
### Describe the bug
[Resholve’s Nix API](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/misc/resholve#using-resholves-nix-api) is structured in a way that makes it impossible to write a [keep directive](https://github.com/abathur/resholve/blob/fa79ccac778fb14402a2b1f41ff4ff378e09cf62/docs/resholve.1.txt#L86) for an absolute path that’s in the Nix store. 

### Steps To Reproduce
Try to build this Nix expression:
```nix
# 🅭🄍1.0 This file is dedicated to the public domain using the CC0 1.0
# Universal Public Domain Dedication
# <https://creativecommons.org/publicdomain/zero/1.0/>.
with import <nixpkgs> { };

let
  git-rev-parse = "${git}/libexec/git-core/git-rev-parse";
in
resholve.writeScript "example"
{
  keep."${git-rev-parse}" = true;
  inputs = [ ];
  interpreter = "${bash}/bin/bash";
} ''
  ${git-rev-parse} HEAD
''
```

It will give you this error:

```
error: the string '/nix/store/nqdyqplahmhdgz8pzzd5nip17zf3ijzx-git-2.40.1/libexec/git-core/git-rev-parse' is not allowed to refer to a store path (such as '!out!/nix/store/fyxzsx7fd2s35hqhch3l57h2d5z80b4k-git-2.40.1.drv')

       at «none»:0: (source not available)
(use '--show-trace' to show detailed location information)
```

### Expected behavior
That Nix expression builds successfully.

### Additional context
[It looks like the names of attributes can’t contain paths in the Nix store.](https://discourse.nixos.org/t/not-allowed-to-refer-to-a-store-path-error/5226) To workaround this problem, you can use a fake directive…

```nix
# 🅭🄍1.0 This file is dedicated to the public domain using the CC0 1.0
# Universal Public Domain Dedication
# <https://creativecommons.org/publicdomain/zero/1.0/>.
with import <nixpkgs> { };

let
  git-rev-parse = "${git}/libexec/git-core/git-rev-parse";
in
resholve.writeScript "example"
{
  fake.external = [ "${git-rev-parse}" ];
  inputs = [ ];
  interpreter = "${bash}/bin/bash";
} ''
  ${git-rev-parse} HEAD
''
```

…or you can use a keep directive that refers to a variable instead of an absolute path:

```nix
# 🅭🄍1.0 This file is dedicated to the public domain using the CC0 1.0
# Universal Public Domain Dedication
# <https://creativecommons.org/publicdomain/zero/1.0/>.
with import <nixpkgs> { };

let
  git-rev-parse = "${git}/libexec/git-core/git-rev-parse";
in
resholve.writeScript "example"
{
  keep."$git_rev_parse" = true;
  inputs = [ ];
  interpreter = "${bash}/bin/bash";
} ''
  readonly git_rev_parse=${git-rev-parse}
  "$git_rev_parse" HEAD
''
```

### Notify maintainers

@abathur

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.05 (Stoat), 23.05.3056.ea5234e7073d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by abathur** [comment]
I think it might be a misfeature to make this work the way you're trying it--you don't need to interpolate the absolute store path into the script:

```nix
with import <nixpkgs> { };

resholve.writeScript "example"
{
  inputs = [
    "${git}/libexec/git-core"
  ];
  interpreter = "${bash}/bin/bash";
  execer = [
    "cannot:${git}/libexec/git-core/git-rev-parse"
  ];
} ''
  git-rev-parse HEAD
''
```


```console
 $ nix-build example.nix
this derivation will be built:
  /nix/store/nn7d5p7f1kswi9b5nn7960k4vk6qsypn-example.drv
building '/nix/store/nn7d5p7f1kswi9b5nn7960k4vk6qsypn-example.drv'...
[resholve context] : invoking resholve with PWD=/private/tmp/nix-build-example.drv-0
[resholve context] RESHOLVE_LORE=/nix/store/8zd1vlfm9hsj4jbnw3c4xcpsqz23z37f-more-binlore
[resholve context] RESHOLVE_EXECER=cannot:/nix/store/djp8m01ix9v536bv4rzfiw3a20x36rvn-git-2.39.1/libexec/git-core/git-rev-parse
[resholve context] RESHOLVE_INPUTS=/nix/store/djp8m01ix9v536bv4rzfiw3a20x36rvn-git-2.39.1/libexec/git-core
[resholve context] RESHOLVE_INTERPRETER=/nix/store/1r1zhjpzpwr0m8w3di7n8phympxw2d3d-bash-5.2-p15/bin/bash
[resholve context] /nix/store/gsf38p2p71w850hahv4wdyyyg1aw6s7g-resholve-0.9.0/bin/resholve --overwrite /nix/store/ijxvz115yar89gm5cgcrd9fd576lymv0-example
Overwrote '/nix/store/ijxvz115yar89gm5cgcrd9fd576lymv0-example'
/nix/store/ijxvz115yar89gm5cgcrd9fd576lymv0-example

$ cat result
#!/nix/store/1r1zhjpzpwr0m8w3di7n8phympxw2d3d-bash-5.2-p15/bin/bash
/nix/store/djp8m01ix9v536bv4rzfiw3a20x36rvn-git-2.39.1/libexec/git-core/git-rev-parse HEAD

### resholve directives (auto-generated) ## format_version: 3
# resholve: keep /nix/store/djp8m01ix9v536bv4rzfiw3a20x36rvn-git-2.39.1/libexec/git-core/git-rev-parse
```

The API could debatably be improved here by implicitly adding `package/libexec/*/` to the path and generate/collect lore for those locations. (I'm not _certain_ that'd be an improvement; I'd probably need to census existing libexec directories and see if the stuff in them is likely to clash with the contents of other `package/bin/` directories...)

**Comment by Jayman2000** [comment]
> I think it might be a misfeature to make this work the way you're trying it--you don't need to interpolate the absolute store path into the script:

Now that I know that I can do `inputs = [ "${git}/libexec/git-core" ]`, I’m inclined to agree.

> The API could debatably be improved here by implicitly adding `package/libexec/*/` to the path and generate/collect lore for those locations. (I'm not _certain_ that'd be an improvement; I'd probably need to census existing libexec directories and see if the stuff in them is likely to clash with the contents of other `package/bin/` directories...)

I wouldn’t add `package/libexec/*/` to the path by default. It would be confusing because installing `git` or running `nix-shell -p git` doesn’t add `libexec/git-core` to your `PATH`.

The thing that would have really helped me here would have been improved documentation. [The current documentation says](https://github.com/NixOS/nixpkgs/blob/e8db8bb6baae0524a54747fc3207aaf8710d95ce/pkgs/development/misc/resholve/README.md#options)

> ## Options
> 
> `resholve.mkDerivation` maps Nix types/idioms into the flags and environment variables
> that the `resholve` CLI expects. Here's an overview:
> 
> | Option | Type | Containing |
> |--------|------|------------|
> | … | … | … |
> | inputs | `<packages>` | Packages to resolve external dependencies from.

That quote and the code examples made me assume that I was only allowed to put packages in the `inputs` list. If I had known that I could put paths to directories that contain executables, then I would have probably done that instead of trying to put an absolute store path into the script.

**Comment by abathur** [comment]
> That quote and the code examples made me assume that I was only allowed to put packages in the inputs list. If I had known that I could put paths to directories that contain executables, then I would have probably done that instead of trying to put an absolute store path into the script.

Thanks for this--my next question was going to be whether you had a sense of what the right breadcrumb would've been. (Left to my own devices, I would've gone off adding an admonition to the documentation for keep directives...)
