### ISSUE TITLE
ipython broken on python2.7

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixpkgs#25234]
## Issue description

The ipython update introduced in 60eaa476ab only supports for python3.

/cc @FRidh

### Steps to reproduce

```
$ nix-shell -p pythonPackages.ipython
error: ipython-6.0.0 not supported for interpreter python2.7
```

## Technical details

* Nixpkgs version: (9e764af72f)

**Comment by FRidh** [comment]
That's because from 6.0.0 on upstream only supports 3.3 and up. See the mail I sent about it earlier.

**Comment by LnL7** [comment]
Yes, but shouldn't we keep a 5.x version around? python2.7 is still the default version in nixpkgs.

**Comment by FRidh** [comment]
If someone wants to add and support it I suppose they could add it. I wonder how long having multiple packages will work though due to upgrades of dependencies.
