### ISSUE TITLE
perlPackages.version test failures after update to perl 5.24.1

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#25242]
## Issue description
Test failures that, apparently, should pass trivially.  For example:

```
#   Failed test '"$version" eq "v1.2.3_4"'
#   at t/coretests.pm line 351.
#          got: 'v1.2.3_4'
#     expected: 'v1.2.3_4'

#   Failed test '"$version" eq "v1.2.3_4" (from eval)'
#   at t/coretests.pm line 353.
#          got: 'v1.2.3_4'
#     expected: 'v1.2.3_4'
```

### Steps to reproduce

I bisected this down to being caused by https://github.com/NixOS/nixpkgs/commit/f78c0329340172aa0819d7a2fdc36b0a8fbb6d2a "perl: init 5.24.1 and set as default perl", so CC'ing @plumps & @Mic92.

**Comment by mdorman** [comment]
Dup of #25229

**Comment by jerith666** [comment]
D'oh, that wasn't there when I went to bed last night -- should've searched again in the morning! 😃
