### ISSUE TITLE
mkForce for the kernel package in grsecurity.enable is a bit awkward

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#25246]
## Issue description

I'm trying to create an Amazon EC2 image with `security.grsecurity.enable = true`. Unfortunately the default kernel it uses is incompatible with EC2 and doesn't boot (which is a pain to debug thanks to AWS not having a real console). Unfortunately, the design of the current `grsecurity` module uses `mkForce` on the `kernelPackages`, so even though we have an EC2-compatible grsecurity kernel in nixpkgs, I need to jump through a couple of hoops to use it easily.

What I'd do instead is give the `grsecurity` NixOS module a `linuxPackages-grsec` option (I'm bad at naming, so pick something not awful) that defaults to the one you currently use `mkForce` on, then use that in the module config. Then in the `amazon-image.nix` module (and other virtualized systems like it), we'd also set `security.grsecurity.linuxPackages` to the suitable kernel. That wouldn't have any effect unless someone used `security.grsecurity.enable = true`, but would make things work sensibly out of the box for most users.

Does that make sense? It seems like an easy fix but I wanted to run it by folks first.

cc @joachifm @jammerful

**Comment by joachifm** [comment]
I had initially used asserts to make sure the kernel was sensible, but that turned out to not work at all ... Without being able to use assert, I really would prefer not exposing the option to end-users.

I made the choice of kernel non-optional after receiving multiple reports that eventually turned out to be misconfiguration. If we do add a `kernelPackages` option it needs to make clear not to change from default willy nilly.

**Comment by copumpkin** [comment]
Why didn't asserts work? I agree that it makes sense to make it hard to screw up; mostly just want to make sure this works sensibly in more scenarios. Building an image/machine that doesn't boot out of the box isn't the best user experience 😄

**Comment by joachifm** [comment]
See my comment on 98935c7103927690b4ca366a2763140081615794 about asserts on the kernel. It's possible I was using it incorrectly, so if you have the inclination, please do try something similar.

I wonder, do you get enough console output to determine why the default kernel fails to boot?

**Comment by copumpkin** [comment]
Yes, but it takes a while and you need to know what to look for. The EC2 console mechanism Something about `xen_blkfront` being missing I think.

I'll poke around at `requiredKernelConfig`, thanks. I assume the asserts got lost somewhere along the way.

**Comment by joachifm** [comment]
See also e99228db3014131255e19b88ba78e47b46a4bff8 which actually made the kernel non-optional.

**Comment by joachifm** [comment]
AFAIK, the most pertinent differences between the stock and the xen variants are kernexec and uderef. The latter can be disabled at boot time, so if that's what keeping you from booting there is a way around it without switching kernels, fwiw.

**Comment by copumpkin** [comment]
I guess the module is gone now, so I'll close this.
