### ISSUE TITLE
Update request: zrythm 1.0.0-beta.4.9.1 → 1.0.0-beta.4.12.34

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#252561]
- Package name: zrythm
- Latest released version: v1.0.0-beta.4.12.34

- Current version on the unstable channel:  1.0.0-beta.4.9.1
- Current version on the stable/release channel: 1.0.0-beta.4.6.3

- [ X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@yuuyins 
@magnetophon 
@tshaynik 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ShalokShalom** [comment]
1.0 is about to release 🥳

**Comment by ShalokShalom** [comment]
They are now packaging it, see the last entry in this issue :)

You can close it

**Comment by PowerUser64** [comment]
Superseded by #306959 (Merged)
