### ISSUE TITLE
Update request: _86Box 3.11 → 4.0

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#252553]
- Package name: _86Box
- Latest released version: 4.0

- Current version on the unstable channel: 3.11
- Current version on the stable/release channel: 3.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jchv

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by jchv** [comment]
I'm a bit busy but I'll try to get back to this on the weekend. I want to check the build system and deps to make sure there's nothing I should be updating there beyond swapping the version numbers, it looks like a decently large changelog.
