### ISSUE TITLE
SDDM not loading /etc/sddm.conf

### ISSUE THREAD

**Issue by farnoy** [NixOS/nixpkgs#252577]
### Describe the bug

SDDM is not using the configuration file that the NixOS module has prepared for it.

### Steps To Reproduce
1. My setup using NixOS 23.05
```nix
  services.xserver.enable = true;
  services.xserver.displayManager.sddm = {
    enable = true;
    settings = {
      General.DisplayServer = "wayland";
    };
  };
  programs.xwayland.enable = true;
  programs.sway.enable = true;
```
2. `$ grep DisplayServer /etc/sddm.conf` outputs `DisplayServer=wayland` as expected
3. `sytemctl status display-manager.service` shows `xorg-server` running, also includes a log line that says `sddm[23833]: Loading theme configuration from ""`

### Expected behavior

I expected it to use wayland as prescribed.

### Additional context

I tried switching from lightdm to a wayland display manager, as having xserver running claims my GPUs which then Oops the kernel when I try to use VFIO passthrough on them. VFIO and device rebinding seems to work fine with wayland, so I need to use a display manager running on it as opposed to X.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.12, NixOS, 23.05 (Stoat), 23.05.20230829.2ab91c8`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager, nixos"`
 - channels(kuba): `"home-manager, nixpkgs"`
 - nixpkgs: `not found`
```

**Comment by alois31** [comment]
23.05 has SDDM 0.19, which does not support running the greeter on Wayland at all. Even unstable, which has 0.20, still requires special setup. The theme warning appears to be unrelated.

**Comment by farnoy** [comment]
That explains it. There's no bug here then, good to close?

**Comment by alois31** [comment]
Yes, I'd say there is no bug here. If you want to follow the progress on Wayland support, there's https://github.com/NixOS/nixpkgs/pull/242009.

**Comment by farnoy** [comment]
Yep, thanks!
