### ISSUE TITLE
x2go server

### ISSUE THREAD

**Issue by mboisson** [NixOS/nixpkgs#25253]
Is there any recipe to install x2go server through Nix ? I did not find a recipe, and failed to make one myself. Anybody has done this ?

**Comment by volth** [comment]
[There](https://github.com/NixOS/nixpkgs/pull/23865) is ```xrdp``` module which may be a superior option unless you are stick to the x2go protocol.

**Comment by mboisson** [comment]
I don't know `xrdp`. Does it use SSH/PAM/LDAP to authenticate ? This is for a public server, security is an issue that x2go solves, but VNC does not for example.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by wavewave** [comment]
it seems like it was packaged recently: https://github.com/NixOS/nixpkgs/pull/65283

**Comment by baracoder** [comment]
> it seems like it was packaged recently: #65283
