### ISSUE TITLE
steam-run is unfree, but needed to run random binaries

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#252568]
## Issue description

`steam-run` is often recommended to run random binaries on NixOS, but it is unfree. That harms the claim that NixOS is open source.

We should provide a way to run random binaries on NixOS like people used from other distributions, that does not involve unfree packages. We should document that in a way new users find it when needed and don't have the experience that NixOS is broken.

This point was brought up in a discussion on the Fediverse: 

>any dynamically linked binary that's not specifically packaged for NixOS needs steam-run (non-free!!) How did this ever become normal?

([source](https://chaos.social/@hut/110984165026142895))

### Steps to reproduce

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=steam-run

**Comment by TheBrainScrambler** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/232640

**Comment by davidak** [comment]
@TheBrainScrambler thanks. I have not found it.
