### ISSUE TITLE
Statically linking readline fails

### ISSUE THREAD

**Issue by lambdax-x** [NixOS/nixpkgs#25267]
## Issue description

Statically linking a binary with static readline library fails: `undefined reference to 'readline'` with `LDFLAGS=-static -lreadline`.

### Steps to reproduce

shell.nix:
```nix
with import <nixpkgs> {};
let
  static = makeStaticLibraries stdenv;
  readline = pkgs.readline.override { stdenv = static; };
in
stdenv.mkDerivation {
  name = "project";
  hardeningDisable = [ "all" ];
  buildInputs = [ glibc.static readline ];
}
```

main.c:
```C
#include <stdlib.h>
#include <stdio.h>
#include <readline/readline.h>

int main(int argc, char *argv[])
{
	char *line = NULL;
	line = readline("");
	free(line);
	return EXIT_SUCCESS;
}
```

```bash
nix-shell
gcc -static -lreadline main.c 
/run/user/1000/ccKRapZ8.o: In function `main':
main.c:(.text+0x1d): undefined reference to `readline'
collect2: error: ld returned 1 exit status
```

## Technical details

* System: NixOS: 17.03.1051.090ffd5fab (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1051.090ffd5fa

**Comment by cleverca22** [comment]
gcc is very sensitive to the order of libraries and .o files

``gcc -static main.c -lreadline `` gives a very different error, i think its missing ncurses

**Comment by lheckemann** [comment]
Yeah, the order matters as @cleverca22 mentions, but you also need to link against the entire static dependency closure of the application you're compiling. Dependencies can be resolved automatically for dynamic libraries, because they include references to the libraries that they in turn require, while static libraries do not.

**Comment by lambdax-x** [comment]
Yes thanks. From gcc's man page:

> It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified.  Thus, foo.o -lz bar.o searches library z after file foo.o but before bar.o.  If bar.o refers to functions in z, those functions may not be loaded.

It has been a nightmare to compile with readline statically.

**Comment by steve-chavez** [comment]
To compile readline statically nowadays you need to do:

```
$ nix-shell -p pkgsStatic.readline pkgsStatic.musl

$ gcc -static main.c `pkg-config --static --libs readline`
```

Using `glibc.static` fails with `undefined reference` errors but `pkgsStatic.musl` works. Also note the order of the source file (`main.c`), it needs to be first. Putting it at the end of the command will fail with `undefined reference`  (which is very unintuitive).
