### ISSUE TITLE
Add piwik package and service

### ISSUE THREAD

**Issue by florianjacob** [NixOS/nixpkgs#25266]
## Issue description
I'm working on a piwik package for Nix and service for NixOS . I turns out it's not trivial to split state files from the other parts of piwik, so it's taking time. I asked piwik devs for help, see https://github.com/piwik/piwik/issues/11654 .

My current progress with the package can be viewed here:
https://github.com/florianjacob/nixpkgs/tree/piwik-package

This is mainly for others to see to avoid duplicate work or to join my efforts. I'll create a pull request as soon as I was able to resolve the problems.

**UPDATE:** Pull Request at #26073

**Comment by alphor** [comment]
This is great! I was just thinking this would be nice to have. I'm new at packaging and don't know if I'd be able to help, but I figured I should post just to thank you for taking the initiative.

**Comment by florianjacob** [comment]
@alphor Well, this is actually my first nix package. 😉 You already helped me with https://jarmac.org/posts/time-machine.html though, I'm using something similar like your „Filesystem structure“ part now as I could not find another solution, too. 😆 

I could solve the big problems in the mean time, hurray! 🎉  @alphor Do you have an unstable NixOS machine where you could test this independently of me once I added some finishing touches?

**Comment by alphor** [comment]
> I'm using something similar like your „Filesystem structure“ part now as I could not find another solution, too.

Yeah I wouldn't suggest that, it bothers me _every_ time I reboot. I'll ask freenode's #nixos what is recommended nowadays. Let me know when you want me to test. Alternatively, I can pull in your fork and test straight from it if you want me to do it before you merge.

> Do you have an unstable NixOS machine where you could test this independently of me once I added some finishing touches?

I'm fine with using my website, I'm not running anything beyond a web server anyway. I just need to point it to unstable.

**Comment by florianjacob** [comment]
@alphor my branch is ready for testing! 😄 Yeah, please use my branch and let's test it before the merge.
I think I won't give you any directions so we can see whether it is documented well enough. 😉 
Do you use nginx?

Did you find a better way regarding filesystem structure? It seems like quite a few packages I studied use a similar approach with a custom systemd unit that sets everything up, so at least it's not totally wrong I think…

**Comment by alphor** [comment]
Sorry for the late response.

[One of the recommendations](https://botbot.me/freenode/nixos/2017-04-17/?msg=84100151&page=1) was instead to use systemd-tmpfiles for ensuring directory structure beforehand. But if you want persistent directory structure (for databases and stateful config) an alternative would be adding a home for the program in as most modules do in /var/lib/. 

I've also considered using a lockdir (so it persists across boots) with an arbitrary version so I can check for its existence, if not, do changes and have a new directory tree setup, but then there is the problem of migrating the data by hand. Perhaps there is a way to do it in the spirit of Nix but making directories is easy enough as it is.

[This](https://github.com/florianjacob/nixpkgs/tree/piwik-package) is the branch, right?

**Comment by florianjacob** [comment]
@alphor nothing to be sorry about. 😃 Yes, `piwik-package` the right branch. I just updated to piwik 3.0.4 and noticed a problem, it seems like php-fpm is not reloaded, only nginx, and therefore piwik_setup_update is not triggered to perform a database upgrade… ☹️ I'll ask in #nixos, or do you know how to do this?

Regarding the filesystem structure: I also thought about a lockdir as I could create and use them easily, but also could not solve the migrate and cleanup issue automatically…

`tmpfiles` was new to me, but only a partial solution because the other part needs to be persistent, at least as long the install wizard has to be run by hand.
This part from the `systemd.tmpfiles.rules` docs makes me wonder where I can actually apply them at all:

        You should not use this option to create
        files required by systemd services, since there is no
        guarantee that <command>systemd-tmpfiles</command> runs when
        the system is reconfigured using
        <command>nixos-rebuild</command>.

**Comment by florianjacob** [comment]
fixed the issue, php-fpm is now restartet on each upgrade, and with it is php_setup_update. :smile:

**Comment by alphor** [comment]
@florianjacob 

Piwik is now up and running on my domain 👍 

A couple of notes on an otherwise flawless installation:

It seems like it's possible to use something like an alternate port instead of a subdomain when using something like nginx, as using a subdomain makes it necessary to update DNS config. This isn't bad at all (especially when the roundtrip is made either way), just something extra to note. 

At first I thought why not just use [vhost-options.nix](https://github.com/NixOS/nixpkgs/blob/release-17.03/nixos/modules/services/web-servers/nginx/vhost-options.nix) as a submodule definition to allow for other mechanisms to access piwik, but implementing something like this generally looks like a lot of pain. Perhaps it's possible to merge a submodule obtained from cfg and merge it with the [relevant lines here](https://github.com/NixOS/nixpkgs/compare/master...florianjacob:piwik-package#diff-f8c1b8b576a6940611cf0574b73b4c0dR151). I'm not even sure this is a good idea, but it came to mind.

As it is now, though, a subdomain is perfectly fine.

I used mysqladmin to create the database and user as referenced in the docstring for the piwik enable option, but the nixos module for mysql does provides an interface for initial database config. I'll test this in the next couple of hours (not experienced at all with mysql) but I figured I'd give you an update anyway.

Two thumbs up!  🎉

**Comment by alphor** [comment]
Addendum:

I nuked my external host and restored from a snapshot to test setting up mysql via nixos module. It went well (with one oddity noted below).
``` nix
  services.mysql = {
    enable = true;
    dataDir = "/var/db/mysql";
    package = pkgs.mysql55;  # make sure not to use mysql 5.7, see below for issue explaining why
    initialScript = pkgs.writeText "piwik-sql-init" ''
      CREATE USER 'piwikuser'@'localhost' IDENTIFIED BY '${builtins.readFile ./secrets/piwikCreds}';
      GRANT ALL PRIVILEGES ON analytics . * TO 'piwikuser'@'localhost';
    '';
  };
```
No need to muck about doing it manually.

See #24400 for why I don't use pkgs.mysql57.

The strange exception was that I had [this same issue](https://github.com/NixOS/nixpkgs/issues/15580) when building from the piwik-package branch this time around (but not before). xsltproc would run oom while parsing nixos-manpages. Not sure what is going on here.

**Comment by florianjacob** [comment]
> as using a subdomain makes it necessary to update DNS config
Not if you use wildcard DNS records for your hostname. 😉 But I agree that there are many possibilities how someone would like /need their nginx vhost to be configured and thought about using vhost-options.nix as well. The problem was that I have no idea whether or how such a merge with what I specify as default vhost options for piwik can be done, and could not find any other service with an example doing so. So I settled on doing this subdomain config, and if other things are needed, people can copy the nginx config from the service to their own config and modify it.

Regarding mysql, the problem with initialScript (and initialDbs) is that they are only executed on the *very first* start of mysql, i.e. when your dataDir is empty. So they're useless if you already had mysql running for something else. Otherwise I'd might use them to at least create the database. See #6963 and #25950.

I'm currently investigating using unix socket authentication instead of a password: https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/ (essentially: a unix user „piwik“ is automatically authenticated as mysql user „piwik“, same for „root“. If you did not know like me, the mysql root user of nixos is free for all by default… ) this would resolve the issue of telling the user an e.g. randomly generated password that they then would have to enter in the web interface.

Regarding your manpages error, no idea. ☹️  I can't reproduce that error, and danbst from IRC did test it for the restart problem and at least did not say anything.
I just rebased on current master, maybe that'll fix it?

Thanks alot for your testing! 😄 I'm glad I managed to make it explanatory enough.

**Comment by alphor** [comment]
Rebasing on master did fix it. Strange.

With socket auth correctly set up, users of piwik would enter in the unix user password of the piwik user in the setup dialog, right?

Anything else you'd like me to test?

**Comment by florianjacob** [comment]
@alphor You're right, it's enough for one PR. I documented loose ends, rebased, rewrote history, wrapped everything up and put together #26073. Database and setup improvements can wait for an update, and need some base work being done in nix / piwik.

With socket auth correctly set up, you don't need any password at all, i.e. the piwik unix user under which php-fpm is run can connect as piwik@localhost to mysql without a password, but other unix users are not allowed to connect as piwik@localhost. I really wonder why this is used nowhere in NixOS as it reduces state as well as secrets, probably no one knows about it, like me a week ago? 😉 If you're interested in this and want to test it once I was able to put something together, I can mention you again. 😄

In principle, I executed this, which alters the root user (instead of adding a root password) and creates a piwik user to use that method.
```
INSTALL PLUGIN unix_socket SONAME 'auth_socket';
ALTER USER root IDENTIFIED VIA unix_socket;
CREATE DATABASE piwik;
CREATE USER 'piwik'@'localhost' IDENTIFIED VIA unix_socket;
GRANT ALL PRIVILEGES ON piwik.* TO 'piwik'@'localhost';
```
Then you can leave the password empty in the piwik setup, but you need to replace the wizard's default database host of `127.0.0.1` with `localhost`.
