### ISSUE TITLE
Enable autologin for tty consoles

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#25262]
This is a question.

The nixos installer will automatically log you in as root.

How can I enable this feature  once nixos is already installed?

Anytime I switch to tty0 - 6 i would like to auto login as root.

**Comment by dezgeg** [comment]
The installers enable it like this: 
https://github.com/NixOS/nixpkgs/blob/a6968ad43c1b6ab7fc341ddba4ed0a082a24229b/nixos/modules/profiles/installation-device.nix#L36

**Comment by ob7** [comment]
Thank you
