### ISSUE TITLE
current marathon 1.4.1 depends on mesos 1.1.1

### ISSUE THREAD

**Issue by Azulinho** [NixOS/nixpkgs#25260]
## Issue description

Minimum mesos release for marathon 1.4.1 is mesos 1.1.1, however both master and release-17.03 have mesos 1.1.0.
As a result of deploying that combo, marathon apps are not deployed 'remain in waiting state'

### Steps to reproduce

deploy a mesos cluster, deploy marathon, deploy a marathon app.
it will remain in 'waiting state'

## Technical details

* System: (NixOS: `17.03`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by fpletz** [comment]
Fixe in #25258.
