### ISSUE TITLE
How to tell nix-build/nix-shell to pick up config and overlays from nixos configuration?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25264]
## Issue description

NixOS configuration (```/etc/nixos/configuration.nix```) might include modules which define ```nixpkgs.config``` and ```nixpkgs.overlays``` (for example there could be a NixOs module which defines
```
nixpkgs.config.allowUnfree =  true;
nixpkgs.overlays = [ (super: self: { jre = self.oraclejre; } ) ];
```

```nix-build``` and ```nix-shell``` do not have options to eval a nixos configuration and pick up config and overlays from there. Instead they look into ```~/.config/nixpkgs/``` for ```config.nix``` and ```overlays/```

Is there a way to tell ```nix-build``` and ```nix-shell``` about config and overlays in NixOs configuration nicer than to eval the configuration and fill ```~/.config/nixpkgs/``` with files?

**Comment by copumpkin** [comment]
There are a couple of hacks we could do here to make it work, but ultimately I think the file-centric nature of a lot of our imports and channels stuff is hindering us here.

One hack: create a "fake channel" for local use that has a default.nix that imports the real channel and imports the nixos config to apply the overlays. Then `<nixpkgs>` on the system will point at that by default, rather than a "real channel". Of course, if someone uses `nixpkgs.path` they'll be able to see through the overlays, but that's less probable.

**Comment by volth** [comment]
I solved this by creating ```~/.config/nixpkgs/config.nix```:
```
let
  system = builtins.currentSystem;

  pkgs = import <nixpkgs> {
    inherit system;
    config   = {}; # in prevents reading ~/.config/nixpkgs
    overlays = [];
  };

  ccc = import <nixpkgs/nixos/lib/eval-config.nix> {
    inherit system pkgs;
    modules = [ /path-to/configuration.nix ];
  };
in
  ccc.config.nixpkgs.config
```

and ```~/.config/nixpkgs/overlays/fake-overlays.nix```:

```
let
  system = builtins.currentSystem;

  pkgs = import <nixpkgs> {
    inherit system;
    config   = {}; # in prevents reading ~/.config/nixpkgs
    overlays = [];
  };

  lib = pkgs.stdenv.lib;

  ccc = import <nixpkgs/nixos/lib/eval-config.nix> {
    inherit system pkgs;
    modules = [ /path-to/configuration.nix ];
  };
in
  lib.foldl' (lib.composeExtensions) (self: super: {}) ccc.config.nixpkgs.overlays
```

so ```nix-build``` and ```nix-shell``` are forced to eval nixos configuration.

**Comment by volth** [comment]
The same in a form of a single module which could be added as ```imports = [ ./nix-config.nix ];``` into ```/etc/nixos/configuration.nix``` freeing the user form maintaining files in ```$HOME/.config/nixpkgs```

```nix
{ ... }:

# this module forces nix-{build,shell} to take 'config' and 'overlays'
# from <nixos-config> (for example /etc/nixos/configuration.nix) instead
# of $HOME/.config/nixpkgs/config.nix $HOME/.config/nixpkgs/overlays/

{
  config = {
    nixpkgs.overlays = [
      (self: super: {
        nix = super.nixUnstable.overrideDerivation(old:
          let
            fakeClosure = self.writeText "fake-closure.nix" ''
              { system ? builtins.currentSystem }:

              let
                pkgs = import <nixpkgs> {
                  inherit system;
                  inherit (ccc.config.nixpkgs) config overlays;
                };

                ccc = import <nixpkgs/nixos/lib/eval-config.nix> {
                  inherit system pkgs;
                  modules = [ <nixos-config> /* or explicitly: /etc/nixos/configuration.nix */ ];
                };
              in
                ccc
            '';
            fakeConfig = self.writeText "fake-config.nix" ''
              (import ${fakeClosure}).config.nixpkgs.config
            '';
            fakeOverlays = self.writeTextDir "fake-overlay.nix" ''
              lib.foldl' lib.composeExtensions (self: super: {}) (import ${fakeClosure}).config.nixpkgs.overlays
            '';
          in {
            buildInputs = old.buildInputs ++ [ self.makeWrapper ];
            postFixup = ''
              for f in $out/bin/nix-build $out/bin/nix-shell $out/bin/nix; do
                wrapProgram $f \
                  --set NIXPKGS_CONFIG ${fakeConfig} \
                  --prefix NIX_PATH : nixpkgs-overlays=${fakeOverlays}
              done
            '';
            doInstallCheck = false;
          });
      })
    ];
  };
}

```

**Comment by Mic92** [comment]
I export `nixpkgs-overlays` globally in my configuration to achieve this: https://github.com/Mic92/nixos-configuration/blob/master/configuration.nix#L54

**Comment by volth** [comment]
@Mic92: What I am trying to achieve is a bit different: to have ```/etc/nixos/configuration.nix``` (or another single file ```<nixos-config>``` could point to) a single source of configuration, avoiding looking to ```/etc/nix/nixpkgs-config.nix```,  ```/etc/nixos/overlays``` or ```$HOME/.config/nixpkgs```.

Basically, any closure (the workstation or a VM image or a closure deployed to a remote server) is a function of only 3 arguments:
1. ```<nixpkgs>``` (maybe a github url)
2. ```<nixos-config>``` (```/etc/nixos/configuration.nix``` for the workstation) containing all overlays
3. ```system``` (mostly "x86_64-linux", sometimes  "i686-linux")

Files ```/etc/nix/nixpkgs-config.nix```,  ```/etc/nixos/overlays```, ```$HOME/.config/nixpkgs``` are to confusing when nix-build makes a package or a closure for a remote machine so my goal is to avoid them.

**Comment by Mic92** [comment]
Then I would export the expression to the nix store from `configuration.nix`:

```diff
nix = {
  nixPath = [
    "/etc/nixos"
    "nixos-config=/etc/nixos/configuration.nix"
    "nspawn-container=/etc/nixos/nspawn-container"
-   "nixpkgs-overlays=/etc/nixos/overlays"
+   "nixpkgs-overlays=${/etc/nixos/overlays}"
  ];
};

```

**Comment by knedlsepp** [comment]
I also just realized the power of setting the `nixpkgs-overlays` for `nix.nixPath` in the `/etc/nixos/configuration.nix`. This makes for a really clean way to point to your personal nixpkgs-overlays in a central repository:
```
nix.nixPath = [ "nixpkgs=https://nixos.org/channels/nixos-17.03/nixexprs.tar.xz" "nixpkgs-overlays=https://github.com/knedlsepp/nixpkgs-
overlays/archive/master.tar.gz"];
```
I was however just wondering if you guys knew how to combine multiple of those. Somehow I got the feeling that the way that `nixpkgs-overlays` is currently implemented via `$NIX_PATH` is not really well fit. A better fit would probably be if `nixpkgs`, `localpkgs`, `nixpkgs-16.09` in the `$NIX_PATH` would actually point to a _list of paths/URLs/tarballs_ instead of a single path. Each element after the first being an overlay of the previous one.
This would make it trivial to "subscribe" to somebody's personal overlays.

**Comment by volth** [comment]
That is also a reason why I do not use ```nixpkgs-overlays``` directory and define overlay in modules instead.

At the cost of a little boilerplate, I get a nested structure of modules explicitly pointing to each other instead of flat directory, for example, ```module1.nix```:

```nix
{ config, lib, ... }:

{
  imports = [
    ./module2.nix # which can also have ```imports```
    ./module3.nix
  ];
  config = {

    nixpkgs.overlays = [
      (self: super: {
         #####
      })
    ];
  };
}
```
also, 
1. a module could have own configuration option, each of them could have ```modulename.enable``` switch, etc
2. unlike overlays in ```nixpkgs-overlays``` directory overlay-in-module could depend on ```config```,  it could have hacks like ```if config.networking.hostName == "xxxx" then .... else ....``` useful for debugging and A/B testing.

**Comment by volth** [comment]
solved

**Comment by vyp** [comment]
@Mic92 setting `<nixpkgs-overlays>` in `nix.nixPath` does not seem to work though? See https://github.com/NixOS/nixpkgs/issues/24907.

**Comment by knedlsepp** [comment]
I'm using the following to get things working:
```
nix.nixPath = [
  "nixpkgs=https://nixos.org/channels/nixos-17.03/nixexprs.tar.xz"
  "nixos-config=/etc/nixos/configuration.nix"
  "knedlsepp-overlays=https://github.com/knedlsepp/nixpkgs-overlays/archive/master.tar.gz"
];

nixpkgs.overlays = [ (import <knedlsepp-overlays>) ];
```

**Comment by vyp** [comment]
@knedlsepp Thanks, I haven't tried it, but so you're saying nix-shell picks up that overlay?

**Comment by knedlsepp** [comment]
Yes. It should.

**Comment by vyp** [comment]
@knedlsepp So I tried that but strangely I had trouble even just getting `nixpkgs.overlays` to work with `(import <knedlsepp-overlays>)`, let alone testing nix-shell. However volth's above solution to use `~/.config/nixpkgs/overlays/fake-overlay.nix` works for me.

Just out of curiosity, I think you should test to see if nix-shell works for you by making a non-existing attribute in your overlay, (e.g. `fake-package`), and then doing `nix-shell -p fake-package`. (Because if that indeed works then for example it could be considered for documentation, cause it's probably less of a 'hack' than volth's solution.) If you don't have time to test it out, then that's cool. :+1:

**Comment by knedlsepp** [comment]
I'm running a webserver on AWS using a [configuration.nix](https://github.com/knedlsepp/knedlsepp.at/blob/master/configuration.nix#L35)
that makes use of my [overlay](https://github.com/knedlsepp/nixpkgs-overlays/blob/master/default.nix#L53), which includes sandman2 (which is not in the official nixpkgs).
When I do `nix-shell -p pythonPackages.sandman2`, this puts me in a shell with sandman2 just fine.
There is however an issue I'm having with this setup: Searching the packages does not work correctly for some reason.
While the following works:
```
nix-shell -p nixUnstable --run "nix search flask-hello-world"
```
and finds:
```
Attribute name: nixpkgs.flask-helloworld
Package name: python2.7-flask-hello-world
Version: 0.1.0
Description: 
```
The search for sandman2 does however not reveal anything:
```
nix-shell -p nixUnstable --run "nix search sandman"
```
I'm not sure if this is an issue with nix-1.12 or if my overlay needs some changes.

**Comment by volth** [comment]
I ended up with making wrappers named ```nixos-shell``` and ```nixos-build``` which act like ```nix-shell``` and ```nix-build``` but took into account overlays and config from ```/etc/nixos/configuration.nix```.

Although ```nixos-shell```/```nixos-build``` are used more frequently than classic ```nix-shell```/```nix-build```, both have its use cases.

**Comment by vyp** [comment]
Ok interesting. I was using a local (absolute) path for the `<knedlsepp-overlays>` value, which is maybe why it wasn't being picked up. :confused:

I don't know about the search, but maybe search for "sandman2"?

**Comment by husseinraoouf** [comment]
I think this issue should be opened again, the current solution isn't satisfying and the experience could be greetly impoved

maybe we can allow to define the shell.nix file as a function that takes the global pkgs ( with applied overrides and overlayes ) like this
```
{ pkgs }:
  pkgs.mkShell {
    buildInputs = [ 
      pkgs.hello
    ];
}
```
