### ISSUE TITLE
nixos: how to set priority (metric) of different network interfaces?

### ISSUE THREAD

**Issue by league** [NixOS/nixpkgs#25278]
## Issue description

Today for the first time, I discovered that after plugging my laptop into a docking port that provides wired ethernet, my computer still tried to connect using wifi. Thanks to some responses on superuser, I discovered some commands to troubleshoot and (temporarily) correct the problem:

```
% route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.22.112.1    0.0.0.0         UG    303    0        0 wlp3s0
0.0.0.0         148.4.40.66     0.0.0.0         UG    309    0        0 enp0s20u3u1u3
148.4.40.0      0.0.0.0         255.255.255.0   U     309    0        0 enp0s20u3u1u3
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.22.112.0    0.0.0.0         255.255.240.0   U     303    0        0 wlp3s0
192.168.56.0    0.0.0.0         255.255.255.0   U     0      0        0 vboxnet0
```

That command shows that `wlp3s0` (wireless) has a lower `metric` number, which gives it a higher priority. The wired interface is `enp0s20u3u1u3`, and it works but with lower priority. I successfully used some commands to change the priorities, by dropping and adding interfaces from the routing table:

```
# route del -net 0.0.0.0 gw 148.4.40.66 netmask 0.0.0.0 dev enp0s20u3u1u3
# route add -net 0.0.0.0 gw 148.4.40.66 netmask 0.0.0.0 dev enp0s20u3u1u3 metric 300
```

Now the wired shows up with higher priority and is used just fine… temporarily. After some timeout (or certainly after suspend/resume), the kernel seems to reassign priorities and my changes are lost.

**So the question is whether it's possible to specify these metric numbers as NixOS options.** I see  `networking.defaultGateway.metric` but it seems like I'd have to specify the address and interface too… and those would change as I move my laptop between different networks.

There are also the options under `networking.interfaces.XYZ` but there doesn't seem to be one there for the metric value, and besides would I have to specify all the details that DHCP already figures out?

Some answers for Ubuntu _et al._ referenced configuring this in `/etc/network/interfaces`. Is there something in `networking.dhcpcd.extraConfig` that would do this?

I've never seen this problem pop up before today, was using NixOS with this hardware for 4 full months, and Arch Linux for years before that.

Thanks.

## Technical details

* System: 17.03.1015.5d611adde6 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1015.5d611adde6

**Comment by fpletz** [comment]
This is the default behaviour of dhcpcd which we are using by default for DHCP. The metric of interface routes can currently only be changed in `networking.dhcpcd.extraConfig` with for instance:

```
      interface enp0s25
      metric 100

      interface vpn
      metric 42

      interface wlp3s0
      metric 200

      ssid myhomewifi
      metric 23
```

And dhcpcd even lets you configure options by ssid. :smile: See the `dhcpcd.conf(5)` manpage for more information about configuring dhcpcd.

But it would probably make sense to add these options into the NixOS modules system. We're currently also missing a module for setting static routes apart from the default gateway.

Another hint: the `route` command is deprecated. You should use the `iproute2` suite with `ip route` instead. [Here is a cool overview](http://baturin.org/docs/iproute2/).

**Comment by league** [comment]
Nice, thanks, that does it.

I'm happy to close this issue, unless we'd like to keep it as a flag to add these options into the dhcpcd module.

**Comment by coretemp** [comment]
I am interested in such a feature too. The module should auto configure based on common scenarios (e.g. deprioritize wifi and 4G connections).

**Comment by NatKarmios** [comment]
Some extra context for people searching about this; if you use `networkmanager`, your `dhcpcd.extraConfig` is ignored by default.

I successfully set metrics via `networkmanager.settings`, like so:
```nix
# Prioritise WiFi connections over Bluetooth tethering
networking.networkmanager.settings = {
  connection-wifi = {
    match-device = "type:wifi";
    "ipv4.route-metric" = 100;
    "ipv6.route-metric" = 100;
  };

  connection-bluetooth = {
    match-device = "type:bt";
    "ipv4.route-metric" = 500;
    "ipv6.route-metric" = 500;
  };
};
```
