### ISSUE TITLE
Package request: JUCE

### ISSUE THREAD

**Issue by multivac61** [NixOS/nixpkgs#252737]
**Project description**

JUCE is an open-source cross-platform C++ application framework for creating high quality desktop and mobile applications, including VST, VST3, AU, AUv3, AAX and LV2 audio plug-ins and plug-in hosts. JUCE can be easily integrated with existing projects via CMake, or can be used as a project generation tool via the [Projucer](https://github.com/juce-framework/JUCE#the-projucer), which supports exporting projects for Xcode (macOS and iOS), Visual Studio, Android Studio, Code::Blocks and Linux Makefiles as well as containing a source code editor.

**Metadata**

* homepage URL: https://juce.com/
* source URL: https://github.com/juce-framework/JUCE
* license: See below
* platforms: unix, linux, darwin, windows, android...

#### Building JUCE Projects

- __C++ Standard__: 17+
- __macOS/iOS__: Xcode 10.1 (macOS 10.13.6)
- __Windows__: Windows 8.1 and Visual Studio 2017
- __Linux__: g++ 7.0 or Clang 6.0 (for a full list of dependencies, see
[here](/docs/Linux%20Dependencies.md)).
- __Android__: Android Studio on Windows, macOS or Linux

#### Deployment Targets

- __macOS__: macOS 10.9
- __Windows__: Windows Vista
- __Linux__: Mainstream Linux distributions
- __iOS__: iOS 9.0
- __Android__: Jelly Bean (API 16)

## Licensing

The core JUCE modules (juce_audio_basics, juce_audio_devices, juce_core and juce_events) are permissively licensed under the terms of the [ISC license](http://www.isc.org/downloads/software-support-policy/isc-license/). Other modules are covered by a [GPL](https://www.gnu.org/licenses/gpl-3.0.en.html)/Commercial license.

There are multiple commercial licensing tiers for JUCE, with different terms for each:
- JUCE Personal (developers or startup businesses with revenue under 50K USD) - free
- JUCE Indie (small businesses with revenue under 500K USD) - $40/month or $800 perpetual
- JUCE Pro (no revenue limit) - $130/month or $2600 perpetual
- JUCE Educational (no revenue limit) - free for bona fide educational institutes

**Comment by multivac61** [comment]
[Here is a derivation for macOS](https://github.com/ianacaburian/journix/wiki/3.2-Nixing-Juce).

**Comment by kashw2** [comment]
Hey @multivac61.

I've created a derivation that works but just wanted to check with you that it's outputting the correct binaries first.

My derivation outputs:
- juce_lv2_helper
- juce_vst3_helper
- juceaide

Is this correct? 

I'd tried using the releases upstream provides and noticed that they provide both a DemoRunner and a Projucer executable instead.

**Comment by multivac61** [comment]
Super cool @kashw2!

Having the [Projucer](https://github.com/juce-framework/JUCE#the-projucer)  (optional executable to bootstrap JUCE projects) and DemoRunner executable available would be very nice. [Here is the build step for the DemoRunner](https://github.com/juce-framework/JUCE#building-examples). 

Will the derivation also expose the library headers when developing using the JUCE application framework?

**Comment by kashw2** [comment]
At the moment I haven't had much luck getting Projucer running without core dumping less than a minute in. I've been able to get the DemoRunner to run though and could add that.

At the moment it's just exposing `juce_lv2_helper`, `juce_vst3_helper` and the `juceaide`. A quick look looks like `juce_vst3_helper` allows you to create modules by running `juce_vst3_helper -create mymodule`.

Do you have a link to documentation on the library headers?

**Comment by kashw2** [comment]
Hi @multivac61

In the linked Pull Request I've now added the library headers. You'll be able to access them via the `/lib` and `/include` directories inside the package.
