### ISSUE TITLE
OpenMW not launching

### ISSUE THREAD

**Issue by AbleTheAbove** [NixOS/nixpkgs#252760]
### Describe the bug
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

### Steps To Reproduce
1. install `openmw`
2. run openmw-launcher

### Expected behavior
The openmw launcher opens

### Notify maintainers

@abbradar 
@marius851000 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.730.85bcb95aa83`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by TheBrainScrambler** [comment]
Sorry for the late reply, I suspect this is because the Darwin folk broke it in https://github.com/NixOS/nixpkgs/pull/220750. Strange that no one reported it before though ...
There is an update going on in https://github.com/NixOS/nixpkgs/pull/245433 which should fix it, but it's stalling.

**Comment by cjbayliss** [comment]
this is a temporary workaround:

```nix
{ config, pkgs, ... }:

with pkgs;
let
  openmw-with-qt = openmw.overrideAttrs (_: rec { dontWrapQtApps = false; });
in {
  # ...
  # I'm using home-manager, but environment.systemPackages should work too
  home.packages = with pkgs; [
    # ...
    openmw-with-qt
    # ...
  ];
}
```

**Comment by cjbayliss** [comment]
sadly, while the luncher launches with the above changes, the game won't load. I can't even open the options menu.

**Comment by icodeforyou-dot-net** [comment]
Got the same problem here with `openmw-launcher`, I hope someone fixes this for an update :smile:

**Comment by TheBrainScrambler** [comment]
With the update to 0.48.0 it now works again for me.

**Comment by cjbayliss** [comment]
I can also confirm that with the update to 0.48 openmw launches and runs the game. :partying_face:

**Comment by poperigby** [comment]
@AbleTheAbove should you close this issue?
