### ISSUE TITLE
Update request: build2 0.15.0 → 0.16.0

### ISSUE THREAD

**Issue by wroyca** [NixOS/nixpkgs#252797]
- Package name: build2
- Latest released version: 0.16.0

- Current version on the unstable channel: 0.15.0
- Current version on the stable/release channel: 0.15.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@vale981 
@r-burns 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by vale981** [comment]
working on it. let's see if I get it done today :P

**Comment by r-burns** [comment]
Still working on this? Happy to take over if you're busy with other stuff.

**Comment by vale981** [comment]
i got some things working but it died off half-way through

here's what i've got so far: https://github.com/vale981/nixpkgs/tree/update_build2
