### ISSUE TITLE
Update request: sklearn-deap 0.2.3 → 0.3.0

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#252825]
- Package name: [sklearn-deap](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/sklearn-deap/default.nix)
- Latest released version: 0.3.0
- Current version on the unstable channel: 0.2.3
- Current version on the stable/release channel: 0.2.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@PsyanticY, this package has been marked as broken for 2 years. There must be some update to fix this (in `scikit-learn` perhaps). Me and my friends use this for our lab work. Would be really helpful if this was fixed. Thanks.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by natsukium** [comment]
Hi, @GetPsyched san. Could you please try #253042?
Thanks!

**Comment by GetPsyched** [comment]
Woah, that was quick. Thank you so much, I'll try this out. Do I just have to put the commit hash in `nixpkgs.url` or something more specific?

**Comment by natsukium** [comment]
Yes, if you use flake, please change `nixpkgs.url` to `github:natsukium/nixpkgs/sklearn-deap/update`.
