### ISSUE TITLE
Is nixpkgs-channels/nixpkgs-unstable deprecated or broken?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25292]
The last commit to https://github.com/NixOS/nixpkgs-channels/commits/nixpkgs-unstable was 4 days ago.
Before that it was updated many times per day.
Is it deprecated or broken?

**Comment by copumpkin** [comment]
No, I assume the hydra job that updates it is just blocked on some failure.

**Comment by edolstra** [comment]
It's broken: http://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-status

Specifically stdenvBootstrapTools.x86_64-darwin.stdenv  fails to build: http://hydra.nixos.org/build/51981431 (@copumpkin?)

**Comment by copumpkin** [comment]
@edolstra it seems to turn into `https://nix-cache.s3.amazonaws.com/log/q61lk01yrmm8d9gcw84ssm76gfm91prw-evaluated-to-false.drv`

**Comment by copumpkin** [comment]
Is this something related to what @Ericson2314 has been up to?

**Comment by copumpkin** [comment]
@edolstra the log file for that build is not available, and it seems to build fine locally for me. How can I get the failed log?

**Comment by copumpkin** [comment]
@edolstra oh I guess it was just unlucky enough to run on the box with the misconfigured Nix? http://hydra.nixos.org/build/51882571

**Comment by copumpkin** [comment]
@edolstra can you clear the failed status and we can retry?

**Comment by primeos** [comment]
https://github.com/NixOS/hydra/issues/476 - Is this related? Feel free to close it if that isn't an issue.

**Comment by vcunat** [comment]
@copumpkin: restarted, getting this log:
```
dyld: Library not loaded: /usr/lib/system/libsystem_symptoms.dylib
  Referenced from: /nix/store/amzf62r92lrwc2a85smfqig3ad65nwng-bootstrap-tools/lib/libSystem.B.dylib
  Reason: image not found
builder for ‘/nix/store/2w654d0963ld7g9wynkbl3i25zf24jrd-bootstrap-Libsystem.drv’ failed due to signal 5 (Trace/BPT trap: 5)
```

**Comment by vcunat** [comment]
All tests should become green now, and channel update is expected to follow some time today.

**Comment by volth** [comment]
Again.
No updates for 5 days.

**Comment by vcunat** [comment]
It's been quite common to get week-long lags, especially if noone often watches channels and fixes up blockers...

**Comment by volth** [comment]
As far as I undestand what is going on http://hydra.nixos.org, the reason of mass failures is ```No space left on device``` (e.g http://hydra.nixos.org/build/52673432/nixlog/2)

**Comment by vcunat** [comment]
The problems vary.  This one is a transient out-of-space problem.  Currently the nixpkgs channel is blocked by a [timeouted job](http://hydra.nixos.org/build/52922275); I now restarted it.

**Comment by vcunat** [comment]
The unstable job [succeeded now](http://hydra.nixos.org/build/52945583), so now it should "only" wait for those remaining thousands of rebuilds...

**Comment by volth** [comment]
> The unstable job succeeded now
What branch does is correspond to ?
I see no https://github.com/NixOS/nixpkgs-channels/commits/nixpkgs-unstable nor https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable were updated.

**Comment by vcunat** [comment]
As I tried to imply, Hydra always waits for all builds from corresponding evaluation to finish.

**Comment by volth** [comment]
What is the best way to maintain a NixOS box up to date?
I do not need "channel", git branch is ok (even preferred over channel, as I cherry-pick not-yet-approved or not-yet-submitted PRs anyway).

```master``` have no binary caches, even if I will compile the packages on-site (which is not good idea due to bad performance and lack of ECC memory on my laptop), it is often broken, the compilation may end up with error.

```nixos-channel``` and ```nixpkgs-channel``` fit the task much better, they have binary caches and they are result of successful compilation. But they have lag and eventually could stop updating at all (seems like no one except me is upset when they stop).

**Comment by vcunat** [comment]
- When building from git, you get whatever binaries are in cache, as they are uploaded at the moment each build finishes.  On master it will typically have binaries for most of jobs, but there may be temporary exceptions (even though such rebuilds *should* go through staging).
- People do get upset and do something about those, but it's when the lag is larger (two weeks typically) or when very important security problems are fixed.  The stable branches tend to have less breakages and faster channel updates.
- There isn't one way to fit all.  That's why there are -small channels, too.

**Comment by vcunat** [comment]
BTW, if you use a Linux, nixos channels are better than nixpkgs-unstable, IMHO.  They get more thorough testing and aren't hindered by darwin-specific problems.

**Comment by volth** [comment]
yes, ```nixos-unstable-small``` is a good choice here. thank you!
