### ISSUE TITLE
Package request: Salmon

### ISSUE THREAD

**Issue by Kupac** [NixOS/nixpkgs#252992]
Salmon is a bioinformatics tool to produce a highly accurate, transcript level quantification estimates from short-read RNA-seq data.
It's mostly written in C++. There's a similar tool already in nixpkgs (Kallisto), but they both have a few unique features, so packaging Salmon is still useful. It's also quite a popular tool.

* homepage URL: https://salmon.readthedocs.io/en/latest/index.html
* source URL: https://github.com/COMBINE-lab/salmon
* license: GLP v3.0
* platforms: linux, others?

**Comment by Kupac** [comment]
I started packaging it, and made good progress. It's a way for me to learn Nix, but may need a few pointers to get it done

**Comment by AndersonTorres** [comment]
Open a draft PR, then.
