### ISSUE TITLE
Package request: OpenProject

### ISSUE THREAD

**Issue by jplhome** [NixOS/nixpkgs#252956]
**Project description**

self-managed, free and open source software for secure project management 
**OpenProject Community edition*

* homepage URL: https://www.openproject.org/community-edition/
* source URL: https://github.com/opf/openproject
* license: gpl 3.0
* platforms: linux

**Comment by raspher** [comment]
closing as it's duplicate of https://github.com/NixOS/nixpkgs/issues/191159
