### ISSUE TITLE
Referencing a package from config.nix seems to imply a different stdenv

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#2530]
On Darwin, I've created the following `config.nix` file:

``` nix
{ packageOverrides = pkgs: with pkgs; rec {

systemToolsEnv = pkgs.buildEnv {
    name = "systemTools";
    paths = [
      coreutils findutils gnused gnutar httrack iperf mosh mtr multitail
      p7zip parallel pdnsd gnupg pinentry pv rsync silver-searcher socat
      stow watch xz
    ];
  };

}; }
```

If I install that list of dependencies manually, using:

```
nix-env -i <paths>
```

Then everything installs fine.  But if I install the buildEnv above with:

```
nix-env -iA nixpkgs.systemToolsEnv
```

Then it tries to pull in `binutils`, `gcc-apple-wrapper`, and different derivations for `bash`, `coreutils`, and several other packages.  It *seems* like it's trying to build these paths using a different stdenv than what gets used by `all-packages.nix`.

How can I determine the "decision chain" which is leading to it trying to use `binutils` when installed one way, but not the other?

**Comment by gridaphobe** [comment]
@jwiegley is this still an issue?

**Comment by peti** [comment]
I believe we found out at some point that there's a difference between `pkgs.foo` and `pkgs.pkgs.foo` in the context of `packageOverrides = pkgs: { ... }`. The name `pkgs` refers to the package set without overrides applied, and the latter refers to the package set after overrides have been applied. Thus, it's important to distinguish which package set is used to resolve references. In the Haskell package set world, we usually call these two sets `self` and `super`.

After figuring all this out, I re-wrote my `~/.nixpkgs/config.nix` file to read:

    {
      packageOverrides = super: let self = super.pkgs; in {
        ...
      };
    }

Now, I can override a package like so:

    rWrapper = super.rWrapper.override {
      packages = with self.rPackages; [ assertthat ];
    };
