### ISSUE TITLE
Helix package does not include any clipboard library by default

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#253049]
### Describe the bug
A key feature of Helix editor is to yank the text input to clipboard. This feature, however does not work by default, and users have to include a clipboard library in their configuration. In my case, I use `wl-clipboard`, but I believe X11 equivalent `xsel/xclip` should also work just fine.

The solution is to include either of `wl-clipboard` or `xsel/xclip` as `buildInput`.

### Steps To Reproduce
1. Open a text file in Helix
2. Try to yank a line
3. Clipboard won't yank to system clipboard

### Expected behavior
Text should be yanked to either of the three clipboards

### Screenshots
Not applicable

### Additional context
Not applicable

### Notify maintainers
@danth
@zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.05 (Stoat), 23.05.3085.2ab91c8d65c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ashvith10** [comment]
This could be counted as a https://github.com/NixOS/nixpkgs/labels/3.skill%3A%20good-first-bug.

**Comment by Artek52** [comment]
How do we check if the user is running wayland or x11?

**Comment by Ashvith10** [comment]
`echo $XDG_SESSION_TYPE` will inform us if we are in Wayland or X11, but if it's about choosing between `wl-copy` and `x-clip`, Helix has hard-coded them based on the display protocol, (I think), so both packages may have to be installed as `buildInput`. For Mac, you're going to have to target their dedicated solution (I don't use Mac, so I have no idea about that).

It does not warn in Helix when you use `:clipboard-yank`, neither does it inform that either of the libraries are installed.
