### ISSUE TITLE
Update request: v2raya 2.0.5 → 2.2.2

### ISSUE THREAD

**Issue by Easedge** [NixOS/nixpkgs#253039]
- Package name: v2raya
- Latest released version: 2.2.2

- Current version on the unstable channel: 2.0.5
- Current version on the stable/release channel: 2.0.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Eliot00 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Easedge** [comment]
Sorry, new release has landed 2.2.3.
Maybe should be noticed the newest version.

**Comment by Easedge** [comment]
The latest version is 2.2.4. 
Since the last version so far, the following features have been added：
- XRay-core support
- Reality support
- TLS Flow support
- uTLS Fingerprint support
- [Juicity](https://github.com/juicity/juicity)/Tuic support

**Comment by Easedge** [comment]
@mzz2017 needed for help

**Comment by iopq** [comment]
https://github.com/NixOS/nixpkgs/pull/254738

**Comment by Easedge** [comment]
> https://github.com/NixOS/nixpkgs/pull/254738
> 
> was this closed because of force pushing the master on the branch?

Yeah, i got it. I will close this issue

**Comment by Eliot00** [comment]
@Easedge https://github.com/NixOS/nixpkgs/pull/262647
