### ISSUE TITLE
Package request: Ida Pro (free)

### ISSUE THREAD

**Issue by joshspicer** [NixOS/nixpkgs#253024]
**Project description**

I'm looking to install (the free version of) IDA Pro decompiler software. 

**Metadata**

* homepage URL: https://hex-rays.com/ida-free/#download
* source URL: (n/a that I can find, see https://out7.hex-rays.com/files/idafree83_linux.run)
* license: non-free
* platforms: they say "linux"

**Comment by ius** [comment]
There's a PR which is waiting for feedback to be addressed, but otherwise testing it might expedite getting it merged: https://github.com/NixOS/nixpkgs/pull/217753
