### ISSUE TITLE
Package request: KWordQuiz

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#253021]
**Project description**

KWordQuiz is a general purpose flash card program. It can be used for vocabulary learning and many other subjects. It provides an editor and five different flashcard quiz modes. It uses the KVTML file format and contributed files can be downloaded from within the application.

**Metadata**

* homepage URL: https://apps.kde.org/kwordquiz
* source URL: https://invent.kde.org/education/kwordquiz
* license: [GPL-2.0+](https://spdx.org/licenses/GPL-2.0+.html)
* platforms: linux

![](https://cdn.kde.org/screenshots/kwordquiz/home.png)

**Comment by cimm** [comment]
I was trying to package this application as an exercise and got stuck on:

```
CMake Error at CMakeLists.txt:87 (find_package):
  By not providing "FindLibKEduVocDocument.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "LibKEduVocDocument", but CMake did not find one.
```

Seems to be needing the LibKEduVocDocument library, which, as far as I can tell, is not yet packaged in `nixpkgs`.

I am not a Nix package or Qt expert by any stretch. Someone else might have better luck.

**Comment by cimm** [comment]
Indeed, the [package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/kde/gear/kwordquiz/default.nix) is now in [unstable](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=KWordQuiz) and can be installed via `nix-shell -p kdePackages.kwordquiz`. I tried it, and it seems to work fine.

@hervyqa, I will close this issue. Feel free to reopen if you think something is missing.
