### ISSUE TITLE
Package request: BalenaEtcher

### ISSUE THREAD

**Issue by Eternumkr** [NixOS/nixpkgs#253020]
**Project description**

Flash OS images to SD cards & USB drives

**Metadata**

* homepage URL: https://balenaetcher.org/
* source URL: https://github.com/balena-io/etcher
* license: mit, bsd, gpl2+ , ...
* platforms: linux Windows, IOS

**Comment by linsui** [comment]
It's already packaged.

**Comment by Eternumkr** [comment]
Where? Ive only found
 https://search.nixos.org/packages?channel=23.05&show=etcher&from=0&size=50&sort=relevance&type=packages&query=etcher 
Which doesnt actually work.

**Comment by linsui** [comment]
What's the difference?

**Comment by Eternumkr** [comment]
im currently installing etcher so i will let you know when its done. 
Etcher has a EOL dependency so normally you wont be able to install it.

**Comment by linsui** [comment]
The package needs update. :shrug:
