### ISSUE TITLE
Build failure: rust-hypervisor-firmware / cargo-auditable

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#253193]
### Steps To Reproduce

1. `nix-build 'https://github.com/NixOS/nixpkgs/archive/41c7605718399dcfa53dd7083793b6ae3bc969ff.tar.gz' -A rust-hypervisor-firmware`

### Build log

```
   Doc-tests auditable-extract
error: doctest failed, to rerun pass `-p auditable-extract --doc`

Caused by:
  could not execute process `rustdoc --edition=2018 --crate-type lib --crate-name auditable_extract --test /build/source/auditable-extract/src/lib.rs --target x86_64-unknown-linux-gnu -L dependency=/build/source/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/build/source/target/release/deps --test-args --test-threads=96 --extern auditable_extract=/build/source/target/x86_64-unknown-linux-gnu/release/deps/libauditable_extract-dd1904617e4b78db.rlib --extern binfarce=/build/source/target/x86_64-unknown-linux-gnu/release/deps/libbinfarce-2ba09d21aed0de1a.rlib -C embed-bitcode=no --error-format human` (never executed)

Caused by:
  No such file or directory (os error 2)
```

### Additional context

The build fails when building the `cargo-auditable` dependency, or rather when running its `doCheck` tests. Building `cargo-auditable` directly works fine.

Upon a surface-level inspection this seems to be a situation where we're crosscompiling to some target without host tool support or someething along those lines, but a `doCheck` still attempts to execute those tools (even though it shouldn't be run in the first place.) Either that, or this is the lovely interpreter mismatch kinda deal we're all too familiar with. Interestingly meta for `cargo-auditable` does specify that the package is broken during crosscompile, but the assertion does not fire, so this might not be what I’m guessing it is, after all?

### Notify maintainers

@astro for rust-hypervisor-firmware
@figsoda for cargo-auditable

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.43, NixOS, 23.11 (Tapir), 23.11.20230808.41c7605`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by figsoda** [comment]
Could you try this on the current master? I was able to build it on 12aaefa78d85ac6a3de62e5ac51a4e2d834e5ae5, #248236 might have fixed this

**Comment by nagisa** [comment]
I can't really try master as tensorflow is broken, but I managed to find a commit in between that works. Thanks!
