### ISSUE TITLE
Package request: mcpelauncher

### ISSUE THREAD

**Issue by I-like-stuff** [NixOS/nixpkgs#253137]
**Project description**
unofficial launcher for the Android version of Minecraft: Bedrock Edition on linux and macOS

**Metadata**
* homepage URL: https://github.com/minecraft-linux/mcpelauncher-manifest
* license: GPL-3.0
* platforms: linux, macos

**Comment by Aleksanaa** [comment]
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/231875
