### ISSUE TITLE
Broken package `spago`

### ISSUE THREAD

**Issue by peterbecich** [NixOS/nixpkgs#253198]
### Describe the bug

```
error: builder for '/nix/store/b5ipclnswinvi5dk47yl0czpwdmzl0xz-spago-0.20.9.drv' failed with exit code 1;
       last 10 log lines:
       >    |
       > 33 |   let config = Watch.defaultConfig { Watch.confDebounce = Watch.NoDebounce }
       >    |                                      ^^^^^^^^^^^^^^^^^^
       >
       > src/Spago/Watch.hs:33:59: error:
       >     Not in scope: data constructor ‘Watch.NoDebounce’
       >     Module ‘System.FSNotify’ does not export ‘NoDebounce’.
       >    |
       > 33 |   let config = Watch.defaultConfig { Watch.confDebounce = Watch.NoDebounce }
       >    |                                                           ^^^^^^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/b5ipclnswinvi5dk47yl0czpwdmzl0xz-spago-0.20.9.drv'.
```

### Steps To Reproduce

```
nix build github:nixos/nixpkgs#spago 
```

or

```
nix build github:nixos/nixpkgs/nixpkgs-unstable#spago 
```

### Expected behavior
Successful build

### Additional context

https://github.com/purescript/spago

https://search.nixos.org/packages?channel=unstable&show=spago&from=0&size=50&sort=relevance&type=packages&query=spago

### Notify maintainers

no maintainers listed

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-11-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(peterbecich): `"nixos, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/peterbecich/.nix-defexpr/channels/nixpkgs`


```

**Comment by peterbecich** [comment]
I will submit a PR to Spago that fixes the dependency on `fsnotify`.

It needs `NoDebounce`: https://hackage.haskell.org/package/fsnotify-0.3.0.1/docs/System-FSNotify.html#t:Debounce

`NoDebounce` has been removed from `fsnotify` 4: https://search.nixos.org/packages?channel=unstable&show=haskellPackages.fsnotify&from=0&size=50&sort=relevance&type=packages&query=fsnotify

**Comment by peterbecich** [comment]
Should be fixed for FSNotify 4 here: https://github.com/purescript/spago/pull/989

**Comment by peterbecich** [comment]
Still failing on a different dependency, `versions` library version 6: https://hackage.haskell.org/package/versions-6.0.1

**Comment by peterbecich** [comment]
Also dependent on `attoparsec-aeson-2.2.0.0`

**Comment by peterbecich** [comment]
Need to fix `aeson_2_2_0_0`: https://github.com/NixOS/nixpkgs/issues/254183

**Comment by peterbecich** [comment]
`spago` is also available in this overlay: https://github.com/thomashoneyman/purescript-overlay#usage

**Comment by sternenseemann** [comment]
#305970

**Comment by harryprayiv** [comment]
Still broken.

**Comment by t4ccer** [comment]
Builds for me on master as of now (c8bc846341f769ac788654f60df3add4e608cacb) on x86_64-linux

**Comment by peterbecich** [comment]
Great, agreed it works
```
nix build github:nixos/nixpkgs#spago 
```

**Comment by peterbecich** [comment]
I suggest this package be renamed `spago-legacy`: https://github.com/NixOS/nixpkgs/pull/324944

Dependency for this change: https://github.com/purescript/spago-legacy/pull/3
