### ISSUE TITLE
davinci-resolve: version missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#253232]
![Screenshot from 2023-09-04 09-31-25](https://github.com/NixOS/nixos-search/assets/91113/50243b74-3aef-481a-9969-8451bcdb7e27)

The version exist in the package definition, but is not shown.

https://github.com/NixOS/nixpkgs/blob/84e8b009ee98ece64d6faa9fbde9c88584d4a08e/pkgs/applications/video/davinci-resolve/default.nix#L31

Not the reason:

- unfree license (works for other unfree packages)
- using insecure dependency (not anymore on unstable)

**Comment by davidak** [comment]
Another issue with this package is that it does not show up at https://repology.org/project/davinci-resolve

Maybe that's the same issue.

**Comment by samueldr** [comment]
This has now seemingly been resolved.

![image](https://github.com/NixOS/nixpkgs/assets/132835/b0d5505a-fb6c-4ac8-b5db-b57ec282729f)
