### ISSUE TITLE
Symlink available commands to bin

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#25322]
This is another question.

Many times we run commands or write scripts that access common paths in linux, such as /bin/bash.

How can I make nixos automatically symlink all commands to the bin directory?

**Comment by matthewbauer** [comment]
The "Nix" way to do this is to avoid these paths.```#!/usr/bin/env $bin``` should work in all cases.

You definitely can set up a symlink from /bin to /run/current-system/sw/bin but you could also just use the current-system path. Either way though there's probably a better way that doesn't involve hard coding a path.

**Comment by ob7** [comment]
Ok thanks Matthew that is good to know...
Its just a lot of my scripts have /bin/bash at the top.
A lot of scripts I get off the internet also have something like /bin/bash at the top.

Are you saying those scripts can have something other than /bin/bash at the top that will still get the job done?

**Comment by Mic92** [comment]
No, @matthewbauer meant you should place the interpreter inplace of `$bin`: ex.: `#!/usr/bin/env bash`, `#!/usr/bin/env php` or `#!/usr/bin/env python`

**Comment by ob7** [comment]
Thank you! You are my hero.

**Comment by Mic92** [comment]
```
$ cat ./foo.awk
#!/usr/bin/env -S awk -f
END { printf "WORKS" }
$ ./foo.awk </dev/null
WORKS
```

**Comment by truthadjustr** [comment]
Thanks. `-S` now works after updating my coreutils to 8.30.  https://stackoverflow.com/questions/1418245/invoking-a-script-which-has-an-awk-shebang-with-parameters-vars
