### ISSUE TITLE
Documentation: Speech Dispatcher for Firefox

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#253258]
## Problem

Speech Dispatcher for Firefox hasn't been documented properly, and may cause confusion for users who want to use speech synthesis.

## Proposal

Add [`nixpkgs.config.firefox.speechSynthesisSupport`](https://github.com/NixOS/nixpkgs/pull/210453#issuecomment-1410035331) option in the Nixpkg manual.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by Nyabinary** [comment]
It should default to true imo; it's an accessibility option.

**Comment by felipelalli** [comment]
> It should default to true imo; it's an accessibility option.

For yesterday.

**Comment by felipelalli** [comment]
Disagree :-1:
