### ISSUE TITLE
Add package field for the Grocy web-app NixOS module

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#253374]
## Issue description

The Grocy module does not have any package fields : https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/web-apps/grocy.nix

I wanted to specify which package to use Grocy 4.0.0 (unstable one) similar to this that I do with Jellyfin : 

```nix
{config, pkgs, ...}:
let
  pkgsUnstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
in {
    services.jellyfin.package = pkgsUnstable.jellyfin;
   ...
```

### Steps to reproduce

Try to set services.grocy.package, this will resolve into an error at build time because the grocy module does not have a package field.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.11 (Tapir), 23.11pre522189.3c15feef7770`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos, nixos-unstable, nixpkgs-unstable"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Here are my channel lists : 
```
nixos https://nixos.org/channels/nixpkgs-unstable
nixos-unstable https://nixos.org/channels/nixos-unstable
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```

Tagging the maintainer of Grocy @n0emis 

I'm not sure exactly how I could work around the absence of this field, but maybe there is a way using overlay or overrides, not really sure.

**Comment by antonmosich** [comment]
I don't think that this attribute really should be added. A package option has its place with e.g. minecraft-server, where there are quite a few different servers (papermc, bukkit, etc) which are exchangeable. In this case I think you should do it either by using overlays, or just replacing the module with the unstable one, that should also run 4.0.0.
See the documentation: https://nixos.org/manual/nixos/stable/#sec-replace-modules
I also think that would be the best way for jellyfin as well

**Comment by n0emis** [comment]
Yes, I think the same, since the module has things specific to the current grocy-version (e.g. php version)

**Comment by AkechiShiro** [comment]
Thanks, I'll do that then.
