### ISSUE TITLE
Package request: opentofu

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#253469]
**Project description**

OpenTofu is a fork of Terraform, which is no longer under a free license (and should be marked as unfree for releases >= 1.6.0). This fork is from the free sources before the license change to a source-available BSL license.

**Metadata**

* homepage URL: https://opentofu.org/
* source URL: https://github.com/opentofu/opentofu
* license: mpl
* platforms: unix

**Comment by davidak** [comment]
cc some active maintainers of terraform: @marsam @zowoq @techknowlogick

**Comment by techknowlogick** [comment]
Related issue: https://github.com/NixOS/nixpkgs/issues/253470

**Comment by xfix** [comment]
I think it would be a good idea to wait for it to be actually named, see https://github.com/opentffoundation/opentf/issues/296.

**Comment by dylanmtaylor** [comment]
https://www.theregister.com/2023/09/20/terraform_fork_opentf_opentofu/

**Comment by gmemstr** [comment]
Pull request has been opened, if the current Terraform maintainers are okay with it I can add them to the maintainers section of the new package. Otherwise more than happy to take responsibility for it.
