### ISSUE TITLE
Package request: headphones-toolbox

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#253494]
**Project description**
Ploopy headphone manager and updater

Ploopy headphones 

**Metadata**

* homepage URL: https://github.com/george-norton/headphones-toolbox
* source URL: https://github.com/george-norton/headphones-toolbox
* license: gpl3
* platforms: linux, darwin

**Comment by knarkzel** [comment]
I'll fix this.

**Comment by Nyabinary** [comment]
@kradalby Could you make a PR for nixpkgs?

**Comment by knarkzel** [comment]
See https://github.com/NixOS/nixpkgs/pull/254611

**Comment by lelgenio** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/254611
