### ISSUE TITLE
Jaxlib for aarch64-darwin

### ISSUE THREAD

**Issue by mjjohns1** [NixOS/nixpkgs#253493]
Requesting support for the Jaxlib Nix package on Apple silicon

**Comment by Aleksanaa** [comment]
But here shows [jaxlib](https://search.nixos.org/packages?channel=unstable&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%22aarch64-darwin%22%5D%7D&sort=relevance&type=packages&query=jaxlib) is already packaged. Would you submit a build failure?
