### ISSUE TITLE
gnome keyboard selection misses "English (intl., with AltGr dead keys)"

### ISSUE THREAD

**Issue by rck** [NixOS/nixpkgs#253474]
### Describe the bug
This is a fresh gnome desktop installation as of today (NixOS 23.05). I did set my usual keyboard layout in `configuration.nix`, which looks all good:

```
 # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_AT.UTF-8";
    LC_IDENTIFICATION = "de_AT.UTF-8";
    LC_MEASUREMENT = "de_AT.UTF-8";
    LC_MONETARY = "de_AT.UTF-8";
    LC_NAME = "de_AT.UTF-8";
    LC_NUMERIC = "de_AT.UTF-8";
    LC_PAPER = "de_AT.UTF-8";
    LC_TELEPHONE = "de_AT.UTF-8";
    LC_TIME = "de_AT.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.exportConfiguration = true;

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
  services.gnome.core-utilities.enable = false;

  # Configure keymap in X11
  services.xserver = {
    layout = "us";
    xkbVariant = "altgr-intl";
    xkbModel = "pc105";
  };
```

`localectl status` gives me

```
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=de_AT.UTF-8
               LC_TIME=de_AT.UTF-8
               LC_MONETARY=de_AT.UTF-8
               LC_PAPER=de_AT.UTF-8
               LC_NAME=de_AT.UTF-8
               LC_ADDRESS=de_AT.UTF-8
               LC_TELEPHONE=de_AT.UTF-8
               LC_MEASUREMENT=de_AT.UTF-8
               LC_IDENTIFICATION=de_AT.UTF-8
  VC Keymap: us
  X11 Layout: us
  X11 Model: pc105
  X11 Variant: altgr-intl
  X11 Options: terminate:ctrl_alt_bksp
```

grepping my nix store for the layout gives me:

```
grep altgr-intl /nix/store/1gp9xys79qzfbrs148fp6rv68846f1g3-xkeyboard-config-2.39/share/X11/xkb/rules/xorg.lst
  altgr-intl      us: English (intl., with AltGr dead keys)
```

The problem is that this layout can not be added in the gnome settings keyboard dialog (see screenshot)

### Expected behavior
"English (intl., with AltGr dead keys)" is available

### Screenshots
The black "Add an Input source" dialog on the right is from NixOs, where this particular option is missing (it has some "intl" variants, but the "AltGr" one is missing). The white one on the left is from a Debian Live VM, the layout I want is the one at the bottom of the list.

![gnomebug](https://github.com/NixOS/nixpkgs/assets/42089/b8cb3870-7aa7-437e-bc54-2af4f73a2073)

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.05 (Stoat), 23.05.3103.841889913dfd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(roland): `"nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rck** [comment]
again a screenshot from the installer, this time from the gnome keyboard dialog where this layout is also available
![image](https://github.com/NixOS/nixpkgs/assets/42089/b86bdcc3-d978-449a-8fce-72b515aad484)

**Comment by rck** [comment]
after the install in the VM it was still there and set. Just for fun I added plain "English (US)" and removed "English (intl., with AltGr dead keys)" and now I can no longer find it in the list. I think this is completely broken

**Comment by acarrico** [comment]
@rck, thanks for the tip. This issue might be worth keeping open or alerting whoever makes the installer.

In these live images:
  nixos-gnome-22.11.1315.6a0d2701705-x86_64-linux.iso
  nixos-gnome-23.05.3759.261abe8a44a7-x86_64-linux.iso

22.11 works fine, but there is only one English (United States) variant listed in 23.05. Specifically, in "Gnome settings->Keyboard->Input Sources->"+"->Add an Input Source->English(United States)" only one variant is listed, "English (US)". All the normal variants seem to be missing.

I used @rck's  dconf-editor trick to set org.gnome.desktop.input-sources.sources to ```[('xkb', 'us') ('xkb' 'us+dvorak')]``` , then both input sources work. ```$ nix-shell -p gnome.dconf-editor``` makes dconf-editor available.
