### ISSUE TITLE
Terraform >= 1.6.0 has a new unfree license and should have metadata updated to reflect this

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#253470]
### Describe the bug

The licensing for versions of Terraform > 1.6.0 has been changed to a non-free but source available BSL license.

### Notify maintainers

@Chili-Man
@babariviere
@kalbasit
@marsam
@maxeaubrey
@timstott
@zimbatm
@zowoq
@techknowlogick

**Comment by figsoda** [comment]
terraform 1.5.6 still seems to have MPL 2.0
https://github.com/hashicorp/terraform/blob/v1.5.6/LICENSE

The license change happened in https://github.com/hashicorp/terraform/commit/b145fbcaadf0fa7d0e7040eac641d9aef2a26433 which is first tagged in [v1.6.0-alpha20230816](https://github.com/hashicorp/terraform/releases/tag/v1.6.0-alpha20230816) and not yet in a stable release.

**Comment by dylanmtaylor** [comment]
> terraform 1.5.6 still seems to have MPL 2.0 https://github.com/hashicorp/terraform/blob/v1.5.6/LICENSE
> 
> The license change happened in [hashicorp/terraform@b145fbc](https://github.com/hashicorp/terraform/commit/b145fbcaadf0fa7d0e7040eac641d9aef2a26433) which is first tagged in [v1.6.0-alpha20230816](https://github.com/hashicorp/terraform/releases/tag/v1.6.0-alpha20230816) and not yet in a stable release.

Updated to reflect this for accuracy.

**Comment by techknowlogick** [comment]
Related issue: https://github.com/NixOS/nixpkgs/issues/253469

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/259101
