### ISSUE TITLE
Build failure: chromiumDev

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#253497]
### Steps To Reproduce

1. build *chromiumDev*

(In my case, I made use of nix-shell -p chromiumDev)

### Build log

https://gist.github.com/Ashvith10/1fa992a73b5ff298847ee24264f2f7db

### Additional context

I'm using the unstable channel (to-be 23.11).

### Notify maintainers

@primeos
@thefloweringash
@networkException
@Artturin
@amjoseph-nixpkgs 
@Stunkymonkey 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.11 (Tapir), 23.11pre521611.e56990880811`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(ashvith): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
Building `chromiumDev` works for me on commit 3a38e4d0974f7ecca07e71f814ade9b93741f213

**Comment by Artturin** [comment]
With what @FliegendeWurst said I'm inclined to believe that the reporter just ran out of memory.

**Comment by Ashvith10** [comment]
@Artturin @FliegendeWurst is `chromiumDev` cached? I'm on "Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre530560.f5892ddac112"  right now. For some reason, it's been more than six hours and the package is still not built.

**Comment by FliegendeWurst** [comment]
> @Artturin @FliegendeWurst is `chromiumDev` cached? I'm on "Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre530560.f5892ddac112" right now. For some reason, it's been more than six hours and the package is still not built.

Quoting https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/README.md

> chromiumBeta and chromiumDev: For testing purposes only (not build on Hydra). We use these channels for testing and to fix build errors in advance so that chromium updates are trivial and can be merged fast.

Building Chromium easily takes 12 hours or more.
