### ISSUE TITLE
Storage issues on XPS 15 9560 due to kernel regression; failing cryptsetup

### ISSUE THREAD

**Issue by lf-** [NixOS/nixpkgs#253418]
There are several reports of storage issues all on this one laptop model here, so I am filing a bug: https://discourse.nixos.org/t/nvme-drive-not-detecting-after-calameres-initiates/32108/

Live posts of me doing debugging: https://matrix.to/#/!DBFhtjpqmJNENpLDOv:nixos.org/$9zWPOBSxYIou5aEGILjwnDFgEJLuIi7JTuUUo7iQkyw?via=nixos.org&via=matrix.org&via=tchncs.de

Results of testing on my machine yesterday:
Kernels I believe are ok: 6.4.9, 6.1.44
Kernels I believe are bad: 6.5.0, 6.5.1, 6.1.51, 6.1.49(?)

Debug log of a failing boot: https://gist.github.com/lf-/58fb6bfd13e4f3d09d8e2c39b279b46a

### Describe the bug
Various storage-not-detected/io error symptoms on the XPS 15 9560, with the internal SSD. Seems to not matter *massively* what SSD it is, since there are people having it with the original SSD as far as I can tell.

Reproduced on this aftermarket drive (there's a firmware rev in here somewhere right?):

```
$ nvme id-ctrl /dev/nvme0
<snip>
mn        : WD Blue SN570 1TB
fr        : 234110WD
rab       : 4
ieee      : 001b44
cmic      : 0
mdts      : 7
cntlid    : 0
ver       : 0x10400
rtd3r     : 0x7a120
rtd3e     : 0xf4240
oaes      : 0x200
ctratt    : 0x2
rrls      : 0
cntrltype : 1
<snip>
```

Most relevant part of failed boot log:

```
Sep 04 11:56:38 localhost kernel: nvme nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0xffff
Sep 04 11:56:38 localhost kernel: nvme nvme0: Does your device have a faulty power saving mode enabled?
Sep 04 11:56:38 localhost kernel: nvme nvme0: Try "nvme_core.default_ps_max_latency_us=0 pcie_aspm=off" and report a bug
Sep 04 11:56:38 localhost kernel: nvme 0000:04:00.0: Unable to change power state from D3cold to D0, device inaccessible
Sep 04 11:56:38 localhost kernel: nvme nvme0: Disabling device after reset failure: -19
Sep 04 11:56:38 localhost systemd-cryptsetup[169]: Device /dev/disk/by-uuid/b80aedf8-ddd4-46fa-8d09-5215d5f286b9 READ lock released.
Sep 04 11:56:38 localhost systemd-cryptsetup[169]: IO error while decrypting keyslot.
Sep 04 11:56:38 localhost systemd-cryptsetup[169]: Keyslot 0 (luks2) open failed with -5.
```

I have not yet tried the alleged workaround given in the message here. I might try it on NixCon hacking day when I don't need my computer to work.

### Steps To Reproduce

1. Use bad kernel
2. ???
3. Suffering

### Expected behavior

Disk works, system boots.

### Additional context
This is a regression between nixos-unstable revisions ce5e4a6 and 3efb0f6 which I have debugged to be kernel-version induced. systemd and cryptsetup versions are constant across both

### Notify maintainers
@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.9, NixOS, 23.11 (Tapir)
, 23.11.20230902.e569908`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by lf-** [comment]
plausibly might be: https://marc.info/?l=linux-kernel&m=169282223025290&w=2

**Comment by dcarosone** [comment]
Thankyou, this is really valuable testing effort I just did not have the chance to get to

**Comment by lf-** [comment]
Upstream bug https://bugzilla.kernel.org/show_bug.cgi?id=217802

**Comment by lf-** [comment]
I have filed a PR to just patch the kernels to revert the offending commit. It seems to have restored the 6.1 series to booting properly, at least. The rest of them I will set building overnight on my fast machine and test later.

**Comment by alyssais** [comment]
@lf- @kgreunke I've merged the revert for now, but it would be really great if you could test what's supposedly the actual [fix](https://lore.kernel.org/lkml/37b1afb997f14946a8784c73d1f9a4f5@realtek.com/) and send them a Tested-by if it works for you.

**Comment by lf-** [comment]
Yep I just compiled that patch now that I fixed my desktop computer, going to test it tomorrow.

For reference, the patch is this one (you may have crlf related problems after downloading the raw version of the message and `git am`): https://lore.kernel.org/lkml/37b1afb997f14946a8784c73d1f9a4f5@realtek.com/

**Comment by alyssais** [comment]
Looks like they still didn't get any Tested-by.  Could somebody please?  I really don't want to have to keep a patch around forever for this.

**Comment by lf-** [comment]
I have tested it, but Gmail on Android is very unable to send plain text emails. When I get to my computer I'll send them one.

**Comment by jkozak** [comment]
I have what looks very like this bug on a Dell 7090 micro with two NVMe drives running unstable; error occurs about once a day, always on the Crucial P3 2TB drive.  I have just taken the system backlevel to kernel 6.1.94 and will monitor and report back.

**Comment by lf-** [comment]
That's going to be a different bug, whatever it is. Best of luck!!

I hope you can pull kernel logs, though I understand these things have their way of making themselves hard to diagnose. A possible suggestion: can you run journalctl -f and dmesg -w over ssh from another machine, tee'd into a file, perhaps? It should at least cause logs to survive the disk screwing up, if that's in fact what's going on.

**Comment by jkozak** [comment]
Happened after three days
