### ISSUE TITLE
nextcloud: Argument #2 ($key) cannot be empty in file...

### ISSUE THREAD

**Issue by jzbor** [NixOS/nixpkgs#253536]
### Describe the bug
This is another bug in Nextcloud I have hit on the server. I can't access the "Security" tab in the admin settings and I am not able to use my Nextcloud as an OAuth provider anymore.

The log looks something like this:
```json
{
    "reqId": "********************",
    "level": 3,
    "time": "2023-09-05T22:09:46+00:00",
    "remoteAddr": "*************************************",
    "user": "*****",
    "app": "index",
    "method": "GET",
    "url": "/settings/admin/security",
    "message": "{\"Exception\":\"Exception\",\"Message\":\"hash_hkdf(): Argument #2 ($key) cannot be empty in file /nix/store/7lihj0wc690gzd7nlvhazp5xqz981jbb-nextcloud-27.0.2/lib/private/Security/Crypto.php line 160\", <... A LOT more lines here, I am a little afraid to leak any sensitive information>}",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0",
    "version": "27.0.2.1"
}
```

There is an upstream issue I think is related to this problem: [#34012](https://github.com/nextcloud/server/issues/34012). There is a [proposal for a patch](https://github.com/nextcloud/server/issues/34012#issuecomment-1471752423), but no verification or update on implementation of the patch in the upstream project.

I am not sure if there is anything that can be done in nixpkgs right now. If that is the case this is probably more of a tracking issue until upstream is fixed.

### Steps To Reproduce
I am not sure whether or how this is reproducible.

### Expected behavior
I should be able to access the "Security" settings in my Nextcloud.

### Notify maintainers
@schneefux @bachp @globin @Ma27

### Metadata
```
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.47, NixOS, 23.11 (Tapir), 23.11.20230822.a2eca34`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/channels/nixpkgs`
```

**Comment by jzbor** [comment]
Hi this issue still persists here and upstream (nextcloud/server#34012). Sadly there does not seem to be an intent to fix this upstream, and I am not quite sure how to fix this in NixOS myself...

**Comment by Ma27** [comment]
And you're nto affected by the following case? https://github.com/nextcloud/server/issues/34012#issuecomment-1807093454

Regarding the patch: since it seems completely untested (from what the author says) and isn't even a proper patch, but the method with the patch applied, I don't think that we should apply this to nixpkgs.

You however can like this:

```nix
nextcloud.overrideAttrs ({ patches ? [], ... }: {
  patches = patches ++ [ ./your-fix.patch ];
})
```

**Comment by jzbor** [comment]
> And you're nto affected by the following case? [nextcloud/server#34012 (comment)](https://github.com/nextcloud/server/issues/34012#issuecomment-1807093454)

I though I was, but changing it didn't fix the issue. I would be fine with replacing it, discarding the old secret store altogether, but I can't figure out how to do this.

> You however can like this:

Thanks! I'll try it and report back...

**Comment by Ma27** [comment]
So the thing is, this is clearly an upstream issue and with all the information I got so far, this has nothing to do with how Nextcloud is packaged here. That being said, I don't see anything actionable here which is why I'd like to close this if you agree (and I'm not missing something).

If you need help with e.g. applying the patch to your system, let me know!

**Comment by jzbor** [comment]
I have not tried applying the patch (in part, because I don't want to mess up my installation even worse that it is now), but somehow this problem also occurs when upgrading, preventing me from updating to the latest 24.05 version. I don't think there is anything that can be done about it, just wanted to let you guys know.
