### ISSUE TITLE
fastfetch: (darwin) wrong icon, colors, and macOS version are shown

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nixpkgs#253545]
### Describe the bug
Fastfetch (on Darwin) have wrong icon, accent colors, and macOS version shown

### Steps To Reproduce
1. nix run nixpkgs#fastfetch

### Expected behavior
Correct icon, accent color, and macOS version are shown

### Screenshots
(nixpkgs's fastfetch, and homebrew's fastfetch)
<img width="827" alt="Screenshot 2023-09-06 at 7 43 12 AM" src="https://github.com/NixOS/nixpkgs/assets/68757440/4345abf6-5bd7-4e73-8fd7-e134e3e4da2f">

### Notify maintainers

@Gerg-L @FedericoSchonborn @khaneliman 

### Metadata
(I have no idea why is it saying I am on macOS 10.16, I am on macOS 13.5.1 instead)
(username removed)
```
~ ❯ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/Users/username/.nix-defexpr/channels/nixpkgs`
```

**Comment by khaneliman** [comment]
Interesting... I can't recreate. But, I also have it installed and a config file. 
<img width="733" alt="image" src="https://github.com/NixOS/nixpkgs/assets/1778670/aaff3b23-2a3e-470b-b2e1-9d420d45856a">

**Comment by Guanran928** [comment]
> It looks like it's properly reporting what nix tells it. Your nix-info command returns the details that the fastfetch is reporting, as well..
> <img alt="image" width="733" src="https://user-images.githubusercontent.com/1778670/267117109-aaff3b23-2a3e-470b-b2e1-9d420d45856a.png">
> 
> My nix-info returns correct, so it must be something with your nix config. <img alt="image" width="653" src="https://user-images.githubusercontent.com/1778670/267119237-6c6b4ce8-bfe7-43d1-b05c-d54c7abfa2ef.png">

Hmm, that's weird. I can't find anything in my config related to macOS version.
Since it appears the issue isn't related to fastfetch itself, I'll close it for now.

**Comment by wegank** [comment]
That's normal: we support macOS 10.12+ (or 10.13+, probably next year) on x86_64, and consequently macOS [should report 10.16 for compatibility reasons](https://eclecticlight.co/2020/08/13/macos-version-numbering-isnt-so-simple/).

https://github.com/NixOS/nixpkgs/blob/187a4d6ffc74a65cb55891a2d011fb9aacb4f6ec/lib/systems/default.nix#L228-L233

If the question mark really bothers you, do `SYSTEM_VERSION_COMPAT=0 fastfetch`, or use something like

```nix
  (fastfetch.overrideAttrs {
    preBuild = lib.optionalString stdenv.isDarwin ''
      export MACOSX_DEPLOYMENT_TARGET=11.0
    '';
  })
```
