### ISSUE TITLE
Update request: betterbird 102.14.0-bb39 → 102.15.0-bb40

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#253589]
- Package name: betterbird
- Latest released version: 102.15.0-bb40

- Current version on the unstable channel: 102.14.0
- Current version on the stable/release channel: 102.1**2**.0

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000

-----

Note for maintainers: **Can you please also backport to 23.05?** Please tag this issue in your PR.

**Comment by SuperSandro2000** [comment]
> Note for maintainers: **Can you please also backport to 23.05?** Please tag this issue in your PR.

Anyone who is a maintainer can put that label on which would help me tremendously because I do not have a machine with NixOS stable and cannot verify if the graphical stack works.

**Comment by SuperSandro2000** [comment]
https://github.com/NixOS/nixpkgs/pull/253635

**Comment by Schweber** [comment]
Thank you!
