### ISSUE TITLE
Update request: openutau 0.1.158 → 0.1.201

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#253596]
- Package name: openutau
- Latest released version:
- Current version on the unstable channel: 0.1.158
- Current version on the stable/release channel: -
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@lilyinstarlight

I don't mind sending a PR to bump the version. I've tried building OpenUtau-0.1.201 on my device, and it works just like the previous instances.

The app, however, crashes, when I use any key, just like the current version, for which I've created stakira/OpenUtau#822.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by lilyinstarlight** [comment]
That version is marked as a beta/pre-release upstream. I don't mind bumping to that version if it fixes things for you, though

**Comment by Ashvith10** [comment]
@lilyinstarlight actually, I don't have a Mac, so I also wanted to make sure that bumping this didn't cause any issue with other platforms out there. Looks like the app-crash behavior still exists in the newer version on Linux.

**Comment by Ashvith10** [comment]
Slightly out of topic, but if license is going to be an issue, would it be okay for you to add [lessampler](https://github.com/YuzukiTsuru/lessampler) and [SpaceWorld](https://github.com/LovelyA72/SpaceWorld) instead? They're both open-source compatible. They may have to be added as plugins for OpenUtau. In the same spirit, we can also make Worldline-R a plugin.

**Comment by lilyinstarlight** [comment]
License isn't an issue for me, but I'll try later to see if I can't make a derivation without the proprietary bits if it's a concern for you

I vaguely recall thinking the code always expects to find the worldline .so, though, so I'll have to double check what that would take later

**Comment by lilyinstarlight** [comment]
Alternatively, if upstream could clarify in-writing the license situation for the worldline.so (e.g. as unfree source but freely redistributable) then that could also be sufficient for your use-case

**Comment by lilyinstarlight** [comment]
Fix for crashes is in #254538 and license question has been asked at https://github.com/stakira/OpenUtau/discussions/837

**Comment by lilyinstarlight** [comment]
Also given your interest in this package, would you like to be a co-maintainer for the OpenUtau derivation in nixpkgs?

**Comment by Ashvith10** [comment]
@lilyinstarlight I don't have any experience with C# and dotnet applications, but if it involves only bumping the version and removing the temporary patches for dotnet and Avalonia 11.0.4, I could do that.

**Comment by lilyinstarlight** [comment]
It's up to you! I'm happy to have assistance for bumps and stuff if nothing else, but you don't have to add yourself as maintainer unless you want to :)

**Comment by Ashvith10** [comment]
I have no issue with adding myself as the co-maintainer, but it looks like you'd have to wait for  #251846 to get merged, because I've added myself there in the `maintainer-list.nix`. file

**Comment by lilyinstarlight** [comment]
License update in #254823 too now, btw
