### ISSUE TITLE
highest rebuild count should NEVER be grayed out

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nixpkgs#253500]
I work on stdenv a lot.  Nearly all of that work is mass-rebuild PRs.  Here's what the right column on a mass rebuild looks like:

<img src=https://github.com/NixOS/nixpkgs/assets/54836058/95263c7a-3c55-4af0-88e8-9a1e418816d3 width="300">

Very helpful.  I see this so often that I have a routine for checking it: scan for the red tags, find the largest number value in a red tag, assess that number.  Rebuilding stdenv?  Definitely a mass rebuild.  Rebuilding 5001 packages?  Definitely a mass rebuild.

Okay, let's try the same thing on this PR:

- https://github.com/NixOS/nixpkgs/pull/227900

Here's what the right column looks like:

<img src=https://github.com/NixOS/nixpkgs/assets/54836058/8f3d9114-ae6b-41f8-9efa-252a9db4afd9 width="300">

Run the algorithm again: 501 packages is not a mass rebuild in my book.  Possibly not even a "large rebuild", but if somebody else considers that to be large I won't argue with them.

I'm not a UI designer, but even so: if somebody says there is a good reason why the *most important information here is grayed out*, I will argue with them about that.  There is no good reason for that.

Could somebody with github superpowers please fix this?  I don't enjoy being called a "table flipper".

Thanks.

**Comment by zimbatm** [comment]
New setting:
![image](https://github.com/NixOS/nixpkgs/assets/3248/886b09f8-708d-409d-bb26-9d909260e35f)

**Comment by Artturin** [comment]
BTW all committers can change the labels

**Comment by amjoseph-nixpkgs** [comment]
https://github.com/NixOS/nixpkgs/issues/50105

**Comment by drupol** [comment]
@Artturin How about defining those labels in a Github config file ?

Just like I do [here](https://github.com/loophp/collection/blob/bafda9ef323f039386da475f69ec8378e6d6abec/.github/settings.yml#L24) ?

**Comment by zimbatm** [comment]
It makes it too easy to give admin to a user on the repo, and then they can do whatever they want. It also extends the attack surface in case a third-party app gets hacked.

A better approach would be to have a separate repo with the configuration. See https://github.com/NixOS/nixos-org-configurations/issues/310
