### ISSUE TITLE
Tracking: llvmPackages deduplication

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#253671]
merged:
https://github.com/NixOS/nixpkgs/pull/230387
https://github.com/NixOS/nixpkgs/pull/253533
https://github.com/NixOS/nixpkgs/pull/253573
https://github.com/NixOS/nixpkgs/pull/253546
https://github.com/NixOS/nixpkgs/pull/268812

unmerged:

Notes
[compiler-rt libcxxabi argument](https://github.com/NixOS/nixpkgs/pull/268812/commits/f6749cddad78531de21e0779c0251f66976e8098)

**Comment by rrbutani** [comment]
See: #299807, #303479, #303449, #303448, #303447, #303438.
