### ISSUE TITLE
beamPackages.hackney doesn't build

### ISSUE THREAD

**Issue by elitak** [NixOS/nixpkgs#25363]
## Issue description

`nix-build -A beamPackages.hackney` fails for me on master. I believe the problem is that `mix`, invoked by the `buildPhase` of `buildMix`, finds the dep `idna`, but not its metadata, so insists on trying to fetch it, which is disallowed in offline mode. The fix I found was to revise `buildMix.buildPhase` to include `export MIX_NO_DEPS=1`, but I'm uncertain if this is appropriate for all builds.

### Steps to reproduce
`nix-build -A beamPackages.hackney`

### Technical Details
* System: "17.09.git.a62bc943cd"
* Nix version: nix-env (Nix) 1.12pre5152_915f62fa
* Nixpkgs version: 17.09.git.a62bc943cd (Hummingbird)

**Comment by rasendubi** [comment]
Please, don't omit the technical details. They provide important info that helps pinpoint the issue (whether it is nixos-specific or not) as well as help to reproduce it (as the master branch is constantly moving).

**Comment by elitak** [comment]
Okay; added.

Are you able to reproduce this?

**Comment by rasendubi** [comment]
**Disclaimer: I am not familiar with Erlang, Mix, etc.**

Yes.
```
building
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:9

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

** (Mix) Hex is running in offline mode and the registry entry for package idna is not cached locally
builder for ‘/nix/store/gxfl7wlxa002mcpcwhxajdjj34jgca39-hackney-1.6.0.drv’ failed with exit code 1
```

From [Mix 1.3.2 release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.3.2), it seems like `MIX_NO_DEPS` was introduced for Nix. There is little documentation on the option, but from what I see, it should be fine to use here. So I would try that.

Also, could the missing metadata be caused by `idna` being built with `buildRebar3` and not `buildMix`?

**Comment by elitak** [comment]
Yes, deps built with `buildMix` seem to include the metadata whereas those built with `buildRebar3` do not. I'm not terribly familiar with either myself, so I don't know if rebar3 can produce the same metadata that Mix does or not.

How do I add smoke tests to Hydra to catch failing builds like this? Is that advisable?

Thanks for having a look.

**Comment by rasendubi** [comment]
I think adding [`recurseIntoAttrs`](https://github.com/NixOS/nixpkgs/blob/a53fb88d33917e052e7239392be67f10821713e2/pkgs/top-level/all-packages.nix#L55-L57) for `beamPackages` will make Hydra evaluate the set.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by elitak** [comment]
Still broken and my fix doesn't seem to work anymore. Someone who maintains the erlang/rebar stuff should have a look.

@grahamcofborg build beamPackages.hackney

**Comment by cw789** [comment]
As the outdated hex package set snapshot has been removed with https://github.com/NixOS/nixpkgs/pull/71393,
I think this issue should be closed now.
