### ISSUE TITLE
Python: clean up old versions of packages

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25375]
## Issue description

Occasionally we add multiple versions of Python libraries because certain packages cannot use the current/latest version. Sometimes these older versions are left behind or upgrading to the latest version wasn't attempted. Let's check whether we still need all these old versions.

The following is a list of attributes that contain a version (thanks to @orivej) and that could be older versions.

- [ ] amqp_1. Needed for kombu_3 which is needed for oslo which isn't maintained.
- [ ] click_5. Needed for platformio. @mogorman (note that your handle doesn't match your GH name)
- [ ] kombu_3. See amgp_1.
- [x] beautifulsoup4. Upstream name.
- [x] boto3. Upstream name
- [x] deform2. Duplicate 63550e35fb4f4de3f0ecd6c294f62f2088826c4c
- [x] gmpy2. Upstream name.
- [x] pycurl2. Upstream name.
- [x] pyparsing1. Used in mwlib. 6c467b7448c25d25ddbe9f7dec22303305386dbc
- [x] pyro3. Upstream name is `Pyro`. Package is only used by `openopc` https://github.com/NixOS/nixpkgs/commit/f6dd52cd6933e401cc79f4381ac6eaca98ec3f35
- [x] requests2. We should rename this to `requests` and see whether we can get rid of the current `requests`. https://github.com/NixOS/nixpkgs/commit/f63eb5857352705665411130d4f1638d55dd8c58
- [x] tqdm4. a33f9b0ff0e59d642a57511037f01dc67f02922c
- [x] beautifulsoup_4_1_3. Only used by flexget. See https://github.com/NixOS/nixpkgs/pull/21636 https://github.com/NixOS/nixpkgs/commit/c1cbae5a1e2a36454ddbe3160dc0759413e8538a
- [x] dateutil_2_2 Only used by csvkit. @vrthra perhaps upgrade csvkit? https://github.com/NixOS/nixpkgs/pull/25404
- [ ] dateutil_1_5. Used by couple older packages.
- [x] dateutil_2_1. Only needed by flexget https://github.com/NixOS/nixpkgs/pull/21636 https://github.com/NixOS/nixpkgs/commit/c1cbae5a1e2a36454ddbe3160dc0759413e8538a
- [x] pathspec 0.3.4: Only used by pants. @copumpkin does pants really need this version? Looking at its setup.py it is very conservative with its dependencies. https://github.com/NixOS/nixpkgs/commit/afad43064b6139f3bd93e75bc1b9433cab8a7c78
- [x] django_1_9. @lsix I know this has been brought up before, but which versions are we going to keep again?
- [x] django_1_8
- [x] django_1_6
- [x] lxml_3_5. Not used at all so lets get rid of it. d3cebfb907f71dfc2352ba2b6907cd406653abee
- [x] mccabe_0_5. Not used at all so lets get rid of it. 12b2fbf7fb2a56ed0b156a22435da8262ea20b89
- [x] openpyxl_2_2_0_b1. @vrthra another dependency of csvkit. https://github.com/NixOS/nixpkgs/pull/25404
- [ ] pymongo_2_9_1. Used by eve and flask-pymongo. Both expressions don't seem to be maintained. 
- [x] sqlalchemy8. Needed for two packages but its been broken for a long time. Let's remove it. 1376c661a9487f58ac0a8ceac339aebb86ab3452
- [x] sqlalchemy_1_0. This will be the only version left.
- [x] zc_buildout2 @garbas which versions do we need? 63993e7e1fc767e07ad0623cda39f91c0999c378
- [x] zc_buildout221
- [x] zc_buildout171
- [x] zc_buildout152
- [x] billiard_33. Not used. Let's remove it. 4847ef5428498f2978ef1b8acb6f9400ef828a1f
- [x] llfuse-0-41. Only used for attic. @bjornfor attic isn't maintained. Are we going to keep the expressions? https://github.com/NixOS/nixpkgs/commit/e75096142cf2f55a22c599469a2de0ef9f0e58b6
- [x] boto-230. Only used by gsutil which is an application with strict requirements. gsutil should probably be moved out of python-packages.nix along with its specific requirements. 7491bc98e98dc58c7be6646f318525dfc96a8f88

**Comment by FRidh** [comment]
@Denommus you've added the eve package in https://github.com/NixOS/nixpkgs/pull/12222. Could we get a eve upgrade so we can get rid of the older version of pymongo?

**Comment by bjornfor** [comment]
We can remove attic. Perhaps set meta.broken now and remove after next release?

**Comment by FRidh** [comment]
@bjornfor do you think we have attic users that would choose to keep using this backup software even when its unmaintained and marked as broken? I highly doubt they would so I think we can just remove it right away.

**Comment by FRidh** [comment]
@domenkozar @cillianderoiste does any of you still use almir? It depends on the broken sqlalchemy8 that I like to remove.

**Comment by domenkozar** [comment]
It doesn't build with sqlalchemy9?

**Comment by bjornfor** [comment]
@FRidh: I have no idea if there are attic users left, so I thought a deprecation period could be helpful (in case there are). I myself have moved to borgbackup, so for me personally you can remove it right now.

**Comment by orivej** [comment]
I guess it could help to collect per derivation download statistics from cache.nixos.org, if possible.

**Comment by FRidh** [comment]
@domenkozar I couldn't get it to work with the latest version. Anyway, because it wasn't working anymore I decided to mark it as broken.

**Comment by domenkozar** [comment]
Sounds good.

**Comment by lsix** [comment]
Requarding Django : the ideal solution would be to only maintain Django-1.11, which is the last LTS release (since 1 month).

- Django 1.9 is officially not maintained since april so it would make sense to drop it.
- Django 1.6 is officially not maintained since april 2015 so we should drop it.
- Django 1.10 will be maintained until the end of the year. It would be preferable to not have it in 17.09 since it will not be maintained for entire lifetime of this nixos release.
- Django 1.8 will be maintained upstream until the end of 2018 so there is no objection keeping it.

I’ll have a look at the various versions that could be dropped, bet they have all been kept because they are referenced by other derivations. I’ll review this ASAP.

**Comment by 7c6f434c** [comment]
>- Django 1.9 is officially not maintained since april so it would make sense to drop it.
>- Django 1.8 will be maintained upstream until the end of 2018 so there is no objection keeping it.

django_hijack currently uses 1.9 (I don't use it, but hit an evaluation
problem). Is there an update for it, or should it use 1.8?

**Comment by FRidh** [comment]
@7c6f434c django packages should always depend on `django`, not on a specific version. When one then wants to use the packages with a specific version of django they can override the `django` attribute

**Comment by lsix** [comment]
@7c6f434c django_hijack supports django 1.10. I was just checking if the current release supports django 1-11, but apparently not. We will have to wait until upstream brings support (or do it ourself).

I also saw that the PR I had for django-1.11 brings the evaluation problem. I am checking what I can do about that.

**Comment by 7c6f434c** [comment]
@lsix I think the evaluation and even build part is done now.

@FRidh the package in question doesn't support the default django at all.

**Comment by FRidh** [comment]
@7c6f434c maybe add a note? If we start using specific versions of django we often end up with multiple versions in a closure.

**Comment by 7c6f434c** [comment]
`django_hijack` seems to be pretty good at failing when its closure
contains multiple versions.

**Comment by garbas** [comment]
I'm not sure who is using zcbuildout I'm not using it. I guess removing and keeping the latest would be a safe way to go forward.

**Comment by FRidh** [comment]
@datakurre @chaoflow @cillianderoiste you were the last ones contributing to the zc.buildout expressions. Can we remove all but the latest versions?

**Comment by copumpkin** [comment]
@FRidh for pants, yes unfortunately the old pants will _build_ fine with a newer pathspec but it'll fail at runtime. The moment they release 0.13 final (so we can get rid of the stable version) we can kill the old pathspec.

**Comment by copumpkin** [comment]
@FRidh what I'll do is move (as I said elsewhere) pants to its own file and then only keep the old pathspec in there, rather than in the global package set.

**Comment by wizzup** [comment]
Will you cleanup `pkgs/top-level/python-packages.nix` too?
* [Expressions for Python libraries are supposed to be in `pkgs/development/python-modules/<name>/default.nix`.](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L3)
* `buildPythonPackage` should be replaced by `callPackage`

I would love to help on this, should I make PR incrementally while working on some packages and refer to this issue?

**Comment by FRidh** [comment]
That should be `mypackage = callPackage ../development/python-modules/mypackage/default.nix { };`.
Please, go ahead. A commit per package and indeed a reference here would be helpful.

**Comment by FRidh** [comment]
Closing this issue because basically all older packages have been (re)moved.
