### ISSUE TITLE
blank screen after login

### ISSUE THREAD

**Issue by andrewufrank** [NixOS/nixpkgs#25377]
## Issue description
press login - screen goes blank for a while before the logo appears - then goes blank again. the first blank is very unsettling for a new user (first time start nixos: is it working? is it dead?).
i am on very slow hardware (eeePC with slow sd car - i was just testing). 

it would be ok when the login screen just shows a differen cursor (hourglass, circle) to indicate that something is happening.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`) 1.11.8 - default config after installation
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by thineye** [comment]
Which desktop manager and display manager are you using?
Which graphics card has your pc? intel?

**Comment by rasendubi** [comment]
Please, fill in the technical details section as well.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by rasendubi** [comment]
I'm closing this as we don't have enough details to debug it. It is also likely to have been fixed since 2017.

Should this happen again, feel free to reopen.
