### ISSUE TITLE
`bootstrapFiles` should be updated periodically to avoid arcane bugs in stale binaries

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#253713]
Current `bootstrapFiles` in `pkgs/stdenv/linux/bootstrap-files` are not that current. Some of then come from 2019, some of them are more recent.

This causes various issues when newer packages (usually toolchains like `gcc`) fail to build against old tools.

A few recent examples:
- https://github.com/NixOS/nixpkgs/issues/253274: outdated `patchelf` does not understand 64-bit inodes (newer binary is fine)
- https://github.com/NixOS/nixpkgs/issues/208412: outdated `libgcc` does not provide basic atopic primitives needed by newer toolchain
- https://github.com/NixOS/nixpkgs/pull/229898#issuecomment-1589179355: outdated `make` enforces serial build when freshed one whould Just Work

**Suggestion: update `bootstrapFiles` as part of the `NixOS` [release process](https://nixos.github.io/release-wiki/Release-Process.html) at least for the platforms supported by Hydra. That way we would get guaranteed 6 month cadence of updates.**

**Comment by trofi** [comment]
Another example where update of `bootstrapTools` update is worth it is missing files to produce `PIE` and `static-PIE` files:
- https://github.com/NixOS/nixpkgs/pull/252310

**Comment by Artturin** [comment]
@lovesegfault 

I have created this script for you to hopefully help you update the bootstrap files.

```sh
#!/usr/bin/env bash

# before running git check out the latest eval revision here https://hydra.nixos.org/jobset/nixpkgs/cross-trunk
# hydra-check only checks the newest evaluation

crossSystems=()
mapfile -t crossSystems < <(nix eval --impure --expr 'let rel-cross = (import ./pkgs/top-level/release-cross.nix {}).bootstrapTools; in builtins.attrNames rel-cross' --json | jq '.[]' --raw-output)

whatToGet=(bootstrapFiles.bootstrapTools bootstrapFiles.busybox)

for system in "${crossSystems[@]}"; do
    echo ""
    echo "$system"
    for what in "${whatToGet[@]}"; do
        if nix run "github:nix-community/hydra-check" -- --arch "" --jobset "nixpkgs/cross-trunk" "bootstrapTools.${system}.${what}" 1>/dev/null; then
            echo -n "${what}:"
            nix build --quiet --no-link --json -f pkgs/top-level/release-cross.nix "bootstrapTools.${system}.${what}" | jq '.[] | .outputs | .out' --raw-output
        else
            echo "${what} for ${system} did not build in this evaluation and may have to be built manually"
            echo "\$ nix build --quiet --no-link --json -f pkgs/top-level/release-cross.nix \"bootstrapTools.${system}.${what}\" | jq '.[] | .outputs | .out' --raw-output"
            echo ""
        fi
    done
done
```




in https://github.com/NixOS/nixpkgs/pull/151399#issuecomment-1004268585 you asked for the `sha256sum` of all the on-server components, however shouldn't it be okay to directly upload the packages from `bootstrapFiles`
https://github.com/NixOS/nixpkgs/blob/e009fad56f56b517f51768e2f3eec5c66d507d52/pkgs/stdenv/linux/make-bootstrap-tools.nix#L230-L233

**Comment by Ma27** [comment]
cc @NixOS/nixos-release-managers and @vcunat

**Comment by vcunat** [comment]
For the record, I believe it is _practical_ for us to regenerate bootstrap tools once in a while, at least for the better supported platforms.  Though twice a year might be an excessive rate IMO; every other year would probably still be OK.

**Comment by vcunat** [comment]
I know that some people in the community would prefer to go the other way and reduce the binaries as much as possible.  ([quick example](https://guix.gnu.org/en/blog/2023/the-full-source-bootstrap-building-from-source-all-the-way-down/))

However as it is now, making the bootstrap sequence much longer would make it very painful to change some parts like stdenv's `setup.sh`, even if the early bootstrap phases don't need them.  If people are interested in that, I think we'd need to do those steps "separately"... basically like an independent method of producing good-enough tools that would then be plugged into our current bootstrapping instead of the binaries.

**Comment by vcunat** [comment]
Ah, thanks.  I missed or forgot that one.

**Comment by trofi** [comment]
Another casualty of stale binaries:

`gcc-8` (used in `bootstrapTools`) uses response files for a linker as soon as there are response files in it's inputs.
`gcc-12` does not exhibit this behaviour. Normally it would not be an issue if `expand-response-params` would alsays be available. But it's not available in early bootstrap.

This makes it harder to use response files unconditionally for things like https://github.com/NixOS/nixpkgs/pull/255192

**Comment by lovesegfault** [comment]
Alright, taking this weekend to handle this, also I re-installed Element on my devices so that folks can reach me on Matrix.

Sorry for all the delays, work has been insane :)

**Comment by alyssais** [comment]
Oh, convenient that this is going on — I've just got Hydra to start building native bootstrap binaries for x86_64-unknown-linux-musl and aarch64-unknown-linux-musl (previously these were built, uh, not by Hydra), so if those could also be included in any bootstrap update, that'd be great!  The process should be exactly the same as for all the other platforms with native Hydra builds.

**Comment by alyssais** [comment]
Do we still have time to get this done for 23.11?

**Comment by RaitoBezarius** [comment]
It's unclear to me what should be done to unblock this, are we waiting on OP or a merge?

**Comment by alyssais** [comment]
AIUI it's a matter of somebody with the permissions to upload to tarballs.nixos.org having the time and knowledge to do that.  Usually that's @lovesegfault — I don't know if there's anybody else who meets those requirements.

**Comment by trofi** [comment]
I think we need a process to be:
- documented
- automated with a script
- executed periodically

**Comment by RaitoBezarius** [comment]
> I think we need a process to be:
> - documented
> - automated with a script
> - executed periodically

Agreed, I am trying to understand if we would like to get this cycle done even manually and who would be up to build this process and submit it to infrastructure people so we can implement it for 24.05 probably.

**Comment by Artturin** [comment]
One of the bootstrap-files are failing to build
https://github.com/NixOS/nixpkgs/pull/258032
Would fix it but I don't know if it's the correct way

**Comment by trofi** [comment]
I wonder if reverting https://github.com/NixOS/nixpkgs/pull/238154 is still an option. It brought in quite a few regressions for various cross-targets.

**Comment by RaitoBezarius** [comment]
I think given the original author is usually unresponsive, if you can make the case of how we can improve things by such a revert, I would consider it.

**Comment by amjoseph-nixpkgs** [comment]
> I wonder if reverting #238154 is still an option.

No, it is not.

> It brought in quite a few regressions for various cross-targets.

Love that vague wording there.

**Comment by trofi** [comment]
> > I wonder if reverting #238154 is still an option.
> 
> No, it is not.
> 
> > It brought in quite a few regressions for various cross-targets.
> 
> Love that vague wording there. Care to provide a list of unfixed regressions?

The comment list of original PR contains it. This very thread contains some of it. But I can do it again:
- https://github.com/NixOS/nixpkgs/issues/243614
- https://github.com/NixOS/nixpkgs/issues/252590

And a few past examples that required workarounds for toolchains that used to build successfully:
- https://github.com/NixOS/nixpkgs/issues/243613
- https://github.com/NixOS/nixpkgs/issues/243326

**Comment by amjoseph-nixpkgs** [comment]
> Care to provide a list of unfixed regressions?

Hrm, that's quite a lot of screenspace to take up in order to note just one unfixed issue.  

And that sole unfixed issue manifests only on mainframe hardware which none of us own (or are ever likely to own).

Rather unpersuasive, I'd say.

**Comment by amjoseph-nixpkgs** [comment]
By the way @trofi, since you care so deeply about these mainframe architectures, have you taken the time to add CI for them?  Or for any other cross-compilation expression?

**Comment by zimbatm** [comment]
@amjoseph-nixpkgs please keep it civil. It creates a bad atmosphere and also reduces the chances of finding a positive outcome.

Is anybody interested in writing an updater script? Something that pulls the latest bootstrap and pushes it into the tarballs bucket? The infra team can then deploy this along the channel updater script.

**Comment by trofi** [comment]
> just one unfixed issue.

I don't think `s390` is special. I see `libgcc` failures on `ppc32` and `alpha`. I managed to use both in the recent past.

<details>
<summary>
$ NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix build -f. stdenv --arg crossSystem '{ config = "powerpc-unknown-linux-gnu"; }'
</summary>
...
/nix/store/zv27y5p2a9gx4nkd8y7xrfyy2qsf61nv-powerpc-unknown-linux-gnu-binutils-2.40/bin/powerpc-unknown-linux-gnu-ld: _ctors_s.o:/build/build/powerpc-unknown-linux-g
nu/libgcc/../../../gcc-12.3.0/libgcc/libgcc2.c:2449: multiple definition of `__DTOR_LIST__'; /build/build/./gcc/ecrti.o:(.dtors+0x0): first defined here
/nix/store/zv27y5p2a9gx4nkd8y7xrfyy2qsf61nv-powerpc-unknown-linux-gnu-binutils-2.40/bin/powerpc-unknown-linux-gnu-ld: _ctors_s.o:/build/build/powerpc-unknown-linux-g
nu/libgcc/../../../gcc-12.3.0/libgcc/libgcc2.c:2448: multiple definition of `__CTOR_LIST__'; /build/build/./gcc/ecrti.o:(.ctors+0x0): first defined here
/nix/store/zv27y5p2a9gx4nkd8y7xrfyy2qsf61nv-powerpc-unknown-linux-gnu-binutils-2.40/bin/powerpc-unknown-linux-gnu-ld: warning: /build/build/./gcc/ecrtn.o: missing .n
ote.GNU-stack section implies executable stack
/nix/store/zv27y5p2a9gx4nkd8y7xrfyy2qsf61nv-powerpc-unknown-linux-gnu-binutils-2.40/bin/powerpc-unknown-linux-gnu-ld: NOTE: This behaviour is deprecated and will be
removed in a future version of the linker
/nix/store/zv27y5p2a9gx4nkd8y7xrfyy2qsf61nv-powerpc-unknown-linux-gnu-binutils-2.40/bin/powerpc-unknown-linux-gnu-ld: warning: ./libgcc_s.so.1.tmp has a LOAD segment
 with RWX permissions
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:995: libgcc_s.so] Error 1
make[1]: Leaving directory '/build/build/powerpc-unknown-linux-gnu/libgcc'
make: *** [Makefile:12949: all-target-libgcc] Error 2
</details>
<details>
<summary>
$NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix build -f. stdenv --arg crossSystem '{ config = "alpha-unknown-linux-gnu"; }'
</summary>
...
       > make[1]: *** No rule to make target '../../../gcc-12.3.0/libgcc/config/alpha/crti.S', needed by 'crti.o'.  Stop.
       > make[1]: *** Waiting for unfinished jobs....
       > /nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/bin/bash ../../../gcc-12.3.0/libgcc/../move-if-change tmp-libgcc_tm.h libgcc_tm.h
       > echo timestamp > libgcc_tm.stamp
       > make[1]: Leaving directory '/build/build/alpha-unknown-linux-gnu/libgcc'
       > make: *** [Makefile:12952: all-target-libgcc] Error 2
       For full logs, run 'nix log /nix/store/icg5iq2h3xd09vpdslky01bz3l67xzvm-alpha-unknown-linux-gnu-stage-static-gcc-12.3.0.drv'.
</details>

**Comment by amjoseph-nixpkgs** [comment]
> I see `libgcc` failures on `ppc32` and `alpha`.

@trofi, it's not a regression if there is no test coverage for it.  Please add a test if you care about these platforms.  Nobody else has, so it stands to reason that nobody else does.  You can be the first!

You've been dredging up a sequence of increasingly-obscure platforms in order to argue for reverting a project I invested an extraordinary amount of time in.  Two of these platforms are no longer available for sale and the third of which is a multi-million-dollar mainframe.  I find it very hard to believe that you own an S390 or use a DEC Alpha on a regular basis.

Taking into account all of the above, you seem to be going out of your way to make this personal.  Please don't do that.

**Comment by trofi** [comment]
It has nothing personal about it. Debian occasionally asks me to debug the bugs on ports they care about. I think it's reasonable to try and help them. I only point out they used to work and proposed a possible solution to make them work again.

But I can stop responding to any threads you are in on github (or anywhere else) if you think it's personal and it will make you feel better.

**Comment by vcunat** [comment]
I agree we shouldn't block progress of anything on regressions for very "exotic" platforms (e.g. alpha, s390*).  Some basic guidance was agreed on on https://github.com/nixos/rfcs/blob/master/rfcs/0046-platform-support-tiers.md

**Comment by lovesegfault** [comment]
FWIW, even without a script, I am willing to take a whole day to update all bootstrap files on each release of NixOS for the foreseeable future.

If that's what folks want, I can propose a process that would allow me to do it in a single day. I don't think what we're lacking is automation, primarily, but coordination.

**Comment by alyssais** [comment]
What coordination is lacking? Isn't it a case of downloading the latest builds of stdenvBootstrapTools (and maybe the cross versions for non-Hydra architectures), uploading them to tarballs.nixos.org, and updating the URLs and hashes?  What is it that you need from other people?

**Comment by lovesegfault** [comment]
Well, that's roughly it, but there are two important bits missing:
1. I can't keep up with everything that's going on. Someone needs to prepare a "bootstrapFiles manifest" with everything that needs uploading and the associated info (see below for what that means)
2. I can upload bootstrap tarballs, but I cannot remove them, so I am cautious when performing the upload as I cannot undo mistakes.

Here's the process I follow to upload a new tarball, @amjoseph-nixpkgs is probably the person most familiar with this, since I've uploaded a number of tarballs for them:

1. Look at the Hydra build linked on GH, make sure nothing is off (built the
right thing, on the right pkgs instance/channel/etc)
2. Check the build logs on Hydra, make sure there are no glaring issues that did
not end up failing the build
3. Get the nix-store path, and sha256's from GH
4. `nix build -L $storePath`
5. Get the `nixpkgs` commit which generated the tarball
6. Check it out, build it, make sure it's reproducible
7. Figure out the correct subpath for this tarball
    1. `x86_64-darwin` → `stdenv-darwin/x86_64`
8. Check that the hashes within match the ones from GH
9. Construct the upload path
    1. `s3://nixpkgs-tarballs/$os/$arch/$nixpkgs_commit`
    2. e.g. `s3://nixpkgs-tarballs/stdenv-darwin/x86_64/05ef940b94fe76e7ac06ea45a625adc8e4be96f9`
10. Upload it
    1. e.g. `aws s3 cp --recursive --acl public-read /nix/store/9h4d7s313wv3gkfwi493yr1wvdsz9lf2-stdenv-bootstrap-tools/on-server/ s3://nixpkgs-tarballs/stdenv-darwin/x86_64/05ef940b94fe76e7ac06ea45a625adc8e4be96f9`
11. Download the uploaded tarballs, check hashes from Hydra match the hashes from the local build and match the hashes that were downloaded.

Here's an example of this process being followed: https://github.com/NixOS/nixpkgs/pull/188334

This is very manual, and is a lot of work for me.

I think the coordination I'd like to see is:
1. A `boostrapTarballManifest` file, which contains all the info above for all the tarballs we want to upload.
3. A review process where, after the manifest is created for a given nixpkgs revision, folks share the burden of validating the tarballs (i.e. the work I do of looking through build logs, re-building the tarballs and verifying that they are reproducible, etc.)
4. A tool I can use to ingest said manifest after it's been reviewed, and upload all the tarballs

I am happy to hack on (3), but I can't do the work of figuring out what (1) and (2) should look like, I think the stakeholders here should collaborate to define that.

**Comment by lovesegfault** [comment]
A follow-on thought, one thing that deserves consideration is the structure of the files in s3, it's kind of nonsensical right now.

If the plan for the future is "we always update all the tarballs periodically", perhaps it should be:
```
bootstrap/<nixpkgs-commit>/<arch>/<contents>
```

So, for example, we'd have:
```
bootstrap/05ef940b94fe76e7ac06ea45a625adc8e4be96f9/x86_64-apple-darwin/<stuff>
bootstrap/05ef940b94fe76e7ac06ea45a625adc8e4be96f9/aarch64-apple-darwin/<stuff>
bootstrap/05ef940b94fe76e7ac06ea45a625adc8e4be96f9/x86_64-unknown-linux-gnu/<stuff>
...
```

(cc. @Ericson2314, @amjoseph-nixpkgs b/c of platform naming)

**Comment by sdht0** [comment]
Any chance this is still happening for 23.11?

**Comment by trofi** [comment]
Filed https://github.com/NixOS/nixpkgs/issues/272750 to provide a mechanism to override `bootstrapFiles` on user's side.

**Comment by trofi** [comment]
Proposed a script that automatically generates bootstrap script update as:
- https://github.com/NixOS/nixpkgs/pull/284541

Example PR for `i686-unknown-linux-gnu`:
- https://github.com/NixOS/nixpkgs/pull/284542

**Comment by trofi** [comment]
Proposed a small unification on `darwin` side to get closer to `linux` WRT seed file location:
- https://github.com/NixOS/nixpkgs/pull/284628

**Comment by Ma27** [comment]
OK, just re-discovered this in my open tabs.

From what I can see, we have the necessary tooling, so the only thing missing is the process to do this periodically, correct? At least I didn't find anything in the release wiki about making sure this happens on each release.
