### ISSUE TITLE
Update request: gpodder 3.11.1 → 3.11.2

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#253836]
- Package name: gpodder
- Latest released version: 3.11.2
- Current version on the unstable channel: 3.11.1
- Current version on the stable/release channel: 3.10.21
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Changes: https://github.com/gpodder/gpodder/releases/tag/3.11.2

**Notify maintainers**

@svenkeidel  
@Mic92

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kilianar** [comment]
gpodder has been updated to version 3.11.3 in #257872
