### ISSUE TITLE
Heroic white screens seconds after launch

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#253887]
### Describe the bug
Upon launching, [`heroic`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/heroic/default.nix) white screens without any visible errors.

### Steps To Reproduce
1. Install `heroic` or `heroic-unwrapped`
2. Run the app
3. See white screen

### Expected behavior
It works without white screening

### Additional context
- Since `heroic` runs fine when using its pre-built AppImage, I don't suspect that there is any issue with my hardware, drivers, or software.
- After testing, I have found out that the issue exists on `i3` specifically. It works fine on KDE. (Note: I haven't tried on similar environments like Sway)
- Running `stalonetray` produces the following output upon exiting `heroic`:
    ```
    X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
    X11 error: BadWindow (invalid Window parameter) (request: X_MapWindow, resource 0x8)
    X11 error: BadWindow (invalid Window parameter) (request: X_GetWindowAttributes, resource 0x3)
    X11 error 3 detected at debug.c:156:print_icon_data
    X11 error: BadWindow (invalid Window parameter) (request: X_ChangeWindowAttributes, resource 0x2)
    X11 error: BadWindow (invalid Window parameter) (request: X_UnmapWindow, resource 0xa)
    X11 error: BadWindow (invalid Window parameter) (request: X_ReparentWindow, resource 0x7)
    X11 error: BadWindow (invalid Window parameter) (request: X_ConfigureWindow, resource 0xc)
    X11 error: BadWindow (invalid Window parameter) (request: X_MapWindow, resource 0x8)
    X11 error 3 detected at xutils.c:115:x11_get_server_timestamp
    X11 error: BadWindow (invalid Window parameter) (request: X_SendEvent, resource 0x19)
    X11 error 3 detected at xutils.c:260:x11_get_window_size
    ```

### Notify maintainers

Hello, @aidalgol 👋🏻 

### Metadata
```console
[getpsyched@potato:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230830.e7f38be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/jfji1id0l3xxy8mgph757dwyngsjaamr-source`
```

**Comment by GetPsyched** [comment]
I am thinking of adding a `heroic-bin` package so that any user facing this or similar issues can use pre-built binaries as a instant solution than waiting for existing nix expressions to be fixed.

Please guide me if you guys think this should/can be done. (The NixOS manual doesn't provide much help with wrappers around AppImages)

**Comment by aidalgol** [comment]
Could you please run `heroic` in a terminal (in the environment where the issue occurs) and paste the output in a comment, in a [collapsed section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections#creating-a-collapsed-section).

I also have a few questions,
1. Do you get those same errors when you run `heroic` from the terminal?
2. Is this X11 KDE, or Wayland KDE?
3. What is your GPU, and which drivers are you using?

> I am thinking of adding a `heroic-bin` package so that any user facing this or similar issues can use pre-built binaries as a instant solution than waiting for existing nix expressions to be fixed.

I don't think we should do this.  If a user wants to run pre-built binaries from upstream, there are straightforward ways to do so.  Since Heroic ships an AppImage, you can use [`appimage-run`](https://search.nixos.org/packages?query=appimage-run).

**Comment by GetPsyched** [comment]
I've already tried running heroic from a terminal and weirdly, there's absolutely no error that shows up. Which makes me think it's a purely front-end error given heroic uses electron.

1. Yes, I do.
2. Wayland AFAIK (I'll have to confirm with my friend who I tested this with)
3. Nvidia. My driver setup is contained in [this file](https://github.com/GetPsyched/nix-config/blob/master/system/nvidia.nix)

Yeah, that makes sense. But how do I make sure it's always installed on my system? Do I have to run `appimage-run <the-image>` every single time I need to launch?

**Comment by GetPsyched** [comment]
Update: I have tested this in Sway as well and the app does white screen with no errors in the terminal.

**Comment by aidalgol** [comment]
Try running Heroic from the branch I just pushed to see if it resolves the issue.  I've changed the Electron version the package uses to match that of the upstream package, as there seems to be a regression in the latest version of Electron.
```sh
nix shell github:aidalgol/nixpkgs/heroic-white-screen-fix#heroic -c heroic
```

**Comment by GetPsyched** [comment]
Just tested this. I don't get the white screen anymore!!

**Comment by Henry-Hiles** [comment]
This happens for me now, trying the nix shell now.

**Comment by Henry-Hiles** [comment]
That fixed it, thanks!
