### ISSUE TITLE
Package request: jinja2-cli

### ISSUE THREAD

**Issue by e-minguez** [NixOS/nixpkgs#253866]
**Project description**

A CLI interface to Jinja2

**Metadata**

* homepage URL: https://github.com/mattrobenolt/jinja2-cli
* source URL: https://github.com/mattrobenolt/jinja2-cli
* license: bsd2
* platforms: unix, linux, darwin

** Other info **

This was closed https://github.com/NixOS/nixpkgs/pull/178911

**Comment by figsoda** [comment]
#254140
