### ISSUE TITLE
Package request: Eza (Exa replacement)

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#253868]
**Project description**

Eza is a replacement for the now unmaintained Exa (https://github.com/ogham/exa), both a replacement for *ls*.  Probably need to add Eza to nixpkgs and deprecate Exa.

**Metadata**

* homepage URL:  https://github.com/eza-community/eza
* source URL:  https://github.com/eza-community/eza
* license: mit
* platforms: unix, linux, darwin

**Comment by traxys** [comment]
It is already packaged https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/eza/default.nix

**Comment by byrongibson** [comment]
Oops, I only checked 23.05 not unstable, thx.
