### ISSUE TITLE
figma-linux: misssing  wrapGAppsHook

### ISSUE THREAD

**Issue by Sigmanificient** [NixOS/nixpkgs#253925]
### Describe the bug
Cannot open figma-linux settings panel due to missing  GSettings schemas

### Steps To Reproduce
![Peek 2023-09-08 02-41](https://github.com/NixOS/nixpkgs/assets/53050011/cf4083e8-dbc5-4632-9685-b77391c4a328)

### Notify maintainers

@ercao

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.05 (Stoat), 23.05.20230907.4f77ea6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - channels(bacon): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Adding `wrapGAppsHook` to `nativeBuildInputs` should fix this.

**Comment by Sigmanificient** [comment]
> ~Adding `wrapGAppsHook` to `nativeBuildInputs` should fix this.~ You already had it in the title, make a PR?

done
