### ISSUE TITLE
Unity3d Playmode Crashing After a Few Seconds

### ISSUE THREAD

**Issue by ilikefrogs101** [NixOS/nixpkgs#253998]
### Steps To Reproduce
1. Open any project in 2021.3.30f1 (I say 2021.3.30f1 cause its the only one I have tried it with)
2. Try and enter playermode
3. Unity crashes

### Expected behavior
Unity should enter play mode without crashing

### Error
```
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Broken pipe).  Continuing.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
assert_20230908191911_3.dmp[14186]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230908191911_3.dmp
assert_20230908191911_3.dmp[14186]: Finished uploading minidump (out-of-process): success = no
assert_20230908191911_3.dmp[14186]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20230908191911_3.dmp[14186]: file ''/tmp/dumps/assert_20230908191911_3.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
```
From unity's Editor.log

### Notify maintainers
@tesq0 
@huantianad 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.05 (Stoat), 23.05.3242.da5adce0ffaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - channels(ilikefrogs101): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by huantianad** [comment]
Can you see if you can reproduce this crash with a blank project? If it only happens in one project, it may be a bug in your project's code/setup.

**Comment by ilikefrogs101** [comment]
Interesting, Sorry to bug you but it appears its  the steam manager.cs script causing it to crash. Sorry to notify you over nothing

**Comment by huantianad** [comment]
All good, glad to see it resolved!

**Comment by ilikefrogs101** [comment]
I don't suppose you would know how to fix steammanager.cs crashing the editor lmao?

**Comment by huantianad** [comment]
I don't know anything off the top of my head haha, I'd probably just be googling, the same as you.
