### ISSUE TITLE
No SoapySDR input in SDRangel

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#254052]
### Describe the bug
The SoapySDR input is missing in SDRangel

### Steps To Reproduce
1. Install and run SDRangel

### Expected behavior
SoapySDR should be available in SDRangel.

### Additional information

```
  nixpkgs.overlays = [
    inputs.nur.overlay
    (final: prev: {
      soapysdr-with-plugins = prev.soapysdr.override { extraPackages = [ prev.soapysdrplay ]; };
    })
  ];
```

### Notify maintainers

@alkeryn @Tungsten842 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.1, NixOS, 23.11 (Tapir), 23.11.20230906.0bffda1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alkeryn** [comment]
hmm, i'm not sure you'd want soapy to be within sdrangel's derivation, not everyone need or want soapy installed.

**Comment by suhr** [comment]
I definitely want soapy since sdrangel does not support sdrplay without it.

**Comment by Tungsten842** [comment]
@suhr I have added optional(I can't enable it by default because it is unfree) sdrplay support in https://github.com/NixOS/nixpkgs/pull/254283, can you test that it works for you?

> I definitely want soapy since sdrangel does not support sdrplay without it.

**Comment by suhr** [comment]
Indeed it works with this option on.
