### ISSUE TITLE
Package request: ripsecrets

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#254043]
**Project description**

A command-line tool to prevent committing secret keys into your source code. It has a few features that distinguish it from other secret scanning tools.

**Metadata**

* homepage URL: https://github.com/sirwart/ripsecrets
* source URL: https://github.com/sirwart/ripsecrets
* license: mit
* platforms: linux, darwin

**Comment by figsoda** [comment]
#254163
