### ISSUE TITLE
Unable to build a nixosConfigurations vm on darwin host

### ISSUE THREAD

**Issue by krostar** [NixOS/nixpkgs#254065]
### Steps To Reproduce

Given the following `flake.nix` file
```nix
{
  inputs.nixos.url = "github:NixOS/nixpkgs/nixos-23.05";

  outputs = {nixos,...  }: {
    nixosConfigurations.testvm = nixos.lib.nixosSystem {
      modules = [
        ({modulesPath, ...}: {
          imports = [(modulesPath + "/virtualisation/qemu-vm.nix")];
          nixpkgs.hostPlatform = "aarch64-linux";
        })
      ];
    };
  };
}
```
and `flake.lock`
```json
{
  "nodes": {
    "nixos": {
      "locked": {
        "lastModified": 1694048570,
        "narHash": "sha256-PEQptwFCVaJ+jLFJgrZll2shQ9VI/7xVhrCYkJo8iIw=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "4f77ea639305f1de0a14d9d41eef83313360638c",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-23.05",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixos": "nixos"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

when I try to build this nixos configuration as a vm with

```sh
nix build .#'nixosConfigurations.testvm.config.system.build.vm'
```
it fails due to a hash musmatch.

Am I missing something obvious ?
It seems like the error is due to a hash of something provided in nixpkgs that changed for some reasons for my build ; I tried to look for this hash in nixpkgs, but I didnt find where its defined.

### Build log
```
error: hash mismatch importing path '/nix/store/pbd9fm3dhrcyx0i0n0dnrshxx05yw0ip-nixos-generate-config';
         specified: sha256:1rhgmgnld072vd64bm71wnq6p68bhm8nnf24jqxsjj5jjsyff3rl
         got:       sha256:00zm238xzazyjj23pd6zgr3n1am7arlr0hg7xh2zn8n5dk3cggg0
error: builder for '/nix/store/jnaypca5fp1f8pmkazssal7787jpyrqz-nixos-generate-config.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/9yv8jd7jdibp7src86pzahyz4n8bjgsi-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hrv26x7pb0xdvj73m65awyavfwpk31pk-nixos-system-nixos-23.05.20230907.4f77ea6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qma8vc695xqc7q0vndhgdwnswsj8wjcs-nixos-vm.drv' failed to build
```

### Additional context

Running the command above on a mac M1 configured with nix-darwin, through a linux builder (due to the system being aarch64-darwin and the vm being aarch64-linux)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels($MYUSER): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

If you need more context or if you need me to execute stuff, don't hesitate!
Thank you by advance for your help.

**Comment by michelav** [comment]
Facing similar problem here. Did you fix it?

**Comment by krostar** [comment]
Hi!

I just tried, and I don't have this issue anymore (with the exact same flake.lock as provided above I am able to run the command provided above without error).

Probably related to this, during today's test I realized that nix is going through a builder (the one I'm using comes from nix-darwin `nix.linux-builder.enable = true`) to build the vm described in the flake, and the builder vm running today on my host certainly received some updates since the time I opened this issue, which could explain why its working now with the exact same flake.lock. I guess this indicate the issue is not directly related to nixpkgs.

If you are using the same builder as me through nix-darwin, maybe the solution is just to upgrade it.
The version I'm using is the following:
```
      "locked": {
        "lastModified": 1705915768,
        "narHash": "sha256-+Jlz8OAqkOwJlioac9wtpsCnjgGYUhvLpgJR/5tP9po=",
        "owner": "lnl7",
        "repo": "nix-darwin",
        "rev": "1e706ef323de76236eb183d7784f3bd57255ec0b",
        "type": "github"
      },
      "original": {
        "owner": "lnl7",
        "ref": "master",
        "repo": "nix-darwin",
        "type": "github"
      }
```

Since the issue is fixed for me, I'll close the issue, feel free to re-open it again if the idea above does not work for you!
