### ISSUE TITLE
Upgrade python27Packages pants13-pre to latest (currently 1.3.0.dev19)

### ISSUE THREAD

**Issue by bhmiller** [NixOS/nixpkgs#25401]
## Issue description

Want the latest 1.3.0 dev release of pants (to get a particular bug fix).

### Steps to reproduce

Just running pants w/in nix-shell w/ trying to use the latest version.

## Technical details

* System: OSX
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre106045.7369fd0b51"

**Comment by copumpkin** [comment]
Fixed in https://github.com/bhmiller/nixpkgs/commit/064882e52ab3e5c96e8c9bd1495228ed84b83a10
