### ISSUE TITLE
Steam dont work in zsh

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#25406]
## Issue description
can't execute steam in zsh, but in bash.

### Steps to reproduce
$ steam
zsh: no such file or directory: /usr/bin/steam

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by pstn** [comment]
I use zsh but can use steam just fine. Please edit your post with the commands given to you in the footer.

Also please try to run steam with a zsh spawned with an empty ``.zshrc`` and see if the issue persists.

**Comment by StillerHarpo** [comment]
Sorry this was my fault. I had an alias for steam in my .zshrc
