### ISSUE TITLE
MySQL Service breaks on 5.7 due to `unknown variable 'pid-file`

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#25418]
## Issue description

```
zoidberg> ● mysql.service - MySQL Server
zoidberg>    Loaded: loaded (/nix/store/q256611xkpigpn61qj2ndslza7ggyfha-unit-mysql.service/mysql.service; enabled; vendor preset: enabled)
zoidberg>    Active: failed (Result: exit-code) since Tue 2017-05-02 00:31:54 UTC; 42ms ago
zoidberg>   Process: 30675 ExecStartPre=/nix/store/qw60rdjv0wbgfdbmcqm2syng142fjnn2-unit-script/bin/mysql-pre-start (code=exited, status=1/FAILURE)
zoidberg> 
zoidberg> May 02 00:31:54 zoidberg systemd[1]: Starting MySQL Server...
zoidberg> May 02 00:31:54 zoidberg mysql-pre-start[30675]: mysql_install_db: [ERROR] unknown variable 'pid-file=/run/mysqld/mysqld.pid'
zoidberg> May 02 00:31:54 zoidberg mysql-pre-start[30675]: 2017-05-02 00:31:54 [ERROR]   Unrecognized options
zoidberg> May 02 00:31:54 zoidberg systemd[1]: mysql.service: Control process exited, code=exited status=1
zoidberg> May 02 00:31:54 zoidberg systemd[1]: Failed to start MySQL Server.
zoidberg> May 02 00:31:54 zoidberg systemd[1]: mysql.service: Unit entered failed state.
zoidberg> May 02 00:31:54 zoidberg systemd[1]: mysql.service: Failed with result 'exit-code'.
```

### Steps to reproduce

```
      mysql = {
        enable = true;
        package = pkgs.mysql55;
      };
```

## Technical details

`17.03.981.a7ebf59aa7`

**Comment by pierrebeaucamp** [comment]
I can reproduce this issue on 18.09

**Comment by shreyanshk** [comment]
Same. Can reproduce.

**Comment by agarden** [comment]
It looks to me like this problem has been fixed in changeset [21e9c35f5f0b3bb48bafe44f69ae6e14670c1633](https://github.com/NixOS/nixpkgs/commit/21e9c35f5f0b3bb48bafe44f69ae6e14670c1633).

**Comment by fpletz** [comment]
`mysql55` works on 18.09 but `mysql59` does not with the same pid file error. 21e9c35f5f0b3bb48bafe44f69ae6e14670c1633 does indeed fix the issue on master.

Backported to 18.09 and verified by running the NixOS test with MariaDB, `mysql55` and `mysql57`.

**Comment by kssgsw** [comment]
Why not just move Lines 269ff up before the if?

        preStart =
          ''
            if ! test -e ${cfg.dataDir}/mysql; then
                mkdir -m 0700 -p ${cfg.dataDir}
                chown -R ${cfg.user} ${cfg.dataDir}
                ${mysql}/bin/mysql_install_db ${installOptions}
                touch /tmp/mysql_init
            fi
            mkdir -m 0755 -p ${cfg.pidDir}
            chown -R ${cfg.user} ${cfg.pidDir}
          '';
