### ISSUE TITLE
Python: setuptools can fetch from PyPI

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25428]
## Issue description

@LnL7 noticed that setuptools was able to download from PyPI.

While we tell pip not to fetch (with the `--no-index` option), setuptools can do so itself.
In the past we used a `distutils.cfg` with `allow-hosts = None` to prevent `setuptools` from fetching itself. This was [removed](https://github.com/NixOS/nixpkgs/pull/11086/files#diff-2562f94de4e4fd2ddc677187fa2e2848L69) when we started building wheels.

If this method still works we could add it back as a `buildInput`.

**Comment by FRidh** [comment]
@domenkozar can you recall why this was removed?

**Comment by domenkozar** [comment]
Hmm, I don't remember. Shouldn't you get an error if sandboxing is turned on?

**Comment by RonnyPfannschmidt** [comment]
setuptools will blindly run easy_install for missing setup_requires dependencies

**Comment by FRidh** [comment]
@LnL7 noticed it in https://github.com/NixOS/nixpkgs/pull/25414. Yes, sandboxing will prevent it, but ideally we wouldn't need sandboxing to prevent it. Let's see whether we can use the distutils.cfg again.

**Comment by domenkozar** [comment]
Ah ok. I think sandboxing is way more simple and powerful protection against such impurities than fixing all edge cases one by one. We're trading miliseconds of build time for hours of development time.

**Comment by LnL7** [comment]
Not everybody uses the sandbox and building without it will work even when you have missing dependencies (see the dogpile.cache pr). This isn't a reason not to use the sandbox, just extra protection to prevent implicit dependencies that won't build on hydra.

**Comment by domenkozar** [comment]
I'd still rather invest making private networking faster so we can turn on sandboxing by default: https://github.com/NixOS/nix/issues/179#issuecomment-273178956

**Comment by copumpkin** [comment]
@domenkozar we still need to make sandboxing work again on Darwin 😦

**Comment by domenkozar** [comment]
Sigh. Do we have a plan for that? Is there an issue open?
