### ISSUE TITLE
Package request: extdlib

### ISSUE THREAD

**Issue by jzbor** [NixOS/nixpkgs#254211]
Extended C library utility

> The extdc core library is made with care and is meant to simplify and improve C development.

It is sort of a extended standard library for core with many "modern" features, like fibres, results, unit tests, etc.
I think it has the potential to greatly improve the usability of C for modern programs and would like to start using it in my personal projects. As I do not have any experience with packaging libraries for Nix I thought I might just open a request.

The project's README puts an emphasis on portability, so I _think_ darwin builds should not be an issue, but I don't have a darwin system, so I am not able to try.

**Metadata**

* homepage URL: https://github.com/cute-engineering/extdlib
* source URL: https://github.com/cute-engineering/extdlib
* license: mit
* platforms:  linux

**Comment by AndersonTorres** [comment]
The project looks too cute.
However I am afraid it doesn't match the criteria for inclusion.

https://github.com/NixOS/nixpkgs/tree/master/pkgs#quick-start-to-adding-a-package

> Is the package ready for general use?

- [The project have only six commits](https://github.com/cute-engineering/extdlib/commits/main). 
- [The website does not exist yet]( https://cute.engineering/)

> Does the project have a clear license statement? 

Yes.

> How realistic is it that it will be used by other people? 

As I have seen, the code is too young.
4 starts, 1 eye, 0 forks. 
No issues, no PRs.

> Are you willing to maintain the package?

I am interested. However I believe it should be on NUR first.
I will reactivate my personal NUR and include it.

**Comment by jzbor** [comment]
> > Is the package ready for general use?
> 
>     * [The project have only six commits](https://github.com/cute-engineering/extdlib/commits/main).
> 
>     * [The website does not exist yet](https://cute.engineering/)

I see how this might be a deal breaker, but it seems like the code was previously part of the [Brutal OS](https://github.com/brutal-org/brutal).

> > Does the project have a clear license statement?
> 
> Yes.
> 
> > How realistic is it that it will be used by other people?
> 
> As I have seen, the code is too young. 4 starts, 1 eye, 0 forks. No issues, no PRs.

Yeah that is true, it does not seem to be as mature, as I thought it to be.
 
> > Are you willing to maintain the package?
> 
> I am interested. However I believe it should be on NUR first. I will reactivate my personal NUR and include it.

It would be great to have it in NUR. I would have created an overlay for it myself, however I have no clue how to package libraries on Nix. I would be very greatful if you could provide the overlay, let me know :)

**Comment by AndersonTorres** [comment]
In a certain sense, package a library is not too different from packaging another piece of software. The problem is how to use it after installed - pkg-config, explicit paths for GCC command line...
