### ISSUE TITLE
Update request: bun 0.8.1 → 1.0.0

### ISSUE THREAD

**Issue by knarkzel** [NixOS/nixpkgs#254224]
- Package name: bun
- Latest released version: 1.0.0
- Current version on the unstable channel: 0.8.1
- Current version on the stable/release channel: 0.6.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@DAlperin @thilobillerbeck @cdmistman

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by natsukium** [comment]
bun is already updated in #254046
