### ISSUE TITLE
Package request: riscv-gnu-toolchain

### ISSUE THREAD

**Issue by godalming123** [NixOS/nixpkgs#254258]
**Project description** Allows compiling c into riscv binarys from non riscv computers

**Metadata**

* source URL: https://github.com/riscv-collab/riscv-gnu-toolchain
* license: Custom
* platforms: linux

**Comment by pineapplehunter** [comment]
This may be not the same, but I have been using `pkgCross.riscv64.stdenv.cc` or `pkgCross.riscv64-embedded.stdenv.cc` which gives me a cross compiler.

**Comment by wineee** [comment]
duplicate: https://github.com/NixOS/nixpkgs/issues/98220
