### ISSUE TITLE
Nvidia ftp server is discounted

### ISSUE THREAD

**Issue by AnotherBugworm** [NixOS/nixpkgs#25431]
## Issue description
As said here https://devtalk.nvidia.com/default/topic/1005867/unix-graphics-announcements-and-news/discontinuing-ftp-access-to-download-nvidia-com , you can't download nvidia drivers from ftp, and `services.xserver.videoDrivers = [ "nvidia" ]` downloads it from there.

### Steps to reproduce
Place `services.xserver.videoDrivers = [ "nvidia" ]` in your `configuration.nix`
`nixos-rebuild swith`

## Technical details

* System: NixOS `17.03.945.5acb454e2a (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `17.03.945.5acb454e2a`

**Comment by joachifm** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/25333
