### ISSUE TITLE
Deluge uses outdated libtorrent but the package definition is up-to-date

### ISSUE THREAD

**Issue by wietsedv** [NixOS/nixpkgs#254338]
### Describe the bug
Deluge 2.x is compatible with libtorrent 2.0.9, but the current deluge install will use the old libtorrent 1.2.11 (both in 23.05 and unstable). This is unexpected, because the [deluge package](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/networking/p2p/deluge/default.nix) should build with the up-to-date [libtorrent-rasterbar](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/libtorrent-rasterbar/default.nix) and not the old [libtorrent-rasterbar-1_2_x](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/libtorrent-rasterbar/1.2.nix).

### Steps To Reproduce
```console
$ nix-shell -p deluged --command "deluge --version"
deluge 2.1.1
libtorrent: 1.2.11.0
Python: 3.10.12
OS: Linux 6.5.1
```

```console
$ nix why-depends nixpkgs#deluged nixpkgs#libtorrent-rasterbar-1_2_x
/nix/store/zn0in76hk3krmwcpqli4kba5wbfzpdv5-python3.10-deluged-2.1.1
└───/nix/store/7mywcp1jkhwi1qgy2g7x77qc0al03vv1-libtorrent-rasterbar-1.2.11-python
    └───/nix/store/cbnpmrqsdj5ipfdmxwkbh1j02iwjjdwn-libtorrent-rasterbar-1.2.11
```

```console
$ nix why-depends nixpkgs#deluged nixpkgs#libtorrent-rasterbar
this path will be fetched (1.80 MiB download, 7.65 MiB unpacked):
  /nix/store/vkbw2wvzqmnhisv4cx1864z8kkg38s86-libtorrent-rasterbar-2.0.9
'flake:nixpkgs#deluged' does not depend on 'flake:nixpkgs#libtorrent-rasterbar'
```

### Expected behavior
- libtorrent version reported by deluge should be `2.0.9`
- `deluged` should not depend on `libtorrent-rasterbar-1_2_x`
- `deluged` should depend on `libtorrent-rasterbar`

### Additional context
When I manually rebuild deluge by copying the default.nix with no edits, I get the recent libtorrent version, with both the 23.05 as well as the unstable channels. Might it therefore be a cache problem?

```console
$ nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
$ ./result/bin/deluge -v
.deluge-wrapped 2.1.1
libtorrent: 2.0.8.0
Python: 3.10.12
OS: Linux 6.5.1
```

```console
$ nix-build -E 'with import <nixos-unstable> {}; callPackage ./default.nix {}'
$ ./result/bin/deluge -v
.deluge-wrapped 2.1.1
libtorrent: 2.0.9.0
Python: 3.10.12
OS: Linux 6.5.1
```

Currently, I have have this seemingly meaningless line in my NixOS configuration to fix the issue:
``` nix
{ services.deluge.package = pkgs.deluged.override { libtorrent-rasterbar = pkgs.libtorrent-rasterbar; }; }
```

### Notify maintainers

@domenkozar @ebzzry 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.1, NixOS, 23.05 (Stoat), 23.05.20230907.4f77ea6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(wietse): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 1sixth** [comment]
`libtorrent-rasterbar` is overridden in all-packages.nix: <https://github.com/NixOS/nixpkgs/blob/14821ae8a8d0029a229172a89964935b07d3c10d/pkgs/top-level/all-packages.nix#L7393>.

**Comment by wietsedv** [comment]
Oh that explains it! Github search did not show this to me when I searched for it.

Should this override be removed? Upstream Deluge has no constraints so a normal pypi install will use 2.0.x by default (even though 1.2.x is still [supported](https://github.com/deluge-torrent/deluge/blob/develop/DEPENDS.md?plain=1#L44)). Moreover, the test version is [pinned](https://github.com/deluge-torrent/deluge/blob/develop/requirements-tests.txt#L1) to 2.0.x.
