### ISSUE TITLE
mpdscribble: Listenbrainz implementation actually not supported

### ISSUE THREAD

**Issue by riotbib** [NixOS/nixpkgs#254365]
### Describe the bug
According to [nixos/modules/services/audio/mpdscribble.nix](https://github.com/NixOS/nixpkgs/blame/master/nixos/modules/services/audio/mpdscribble.nix) scrobbling to [Listenbrainz](https://listenbrainz.org/) should be supported. But [according to mpdscribble's Issue Tracker](https://github.com/MusicPlayerDaemon/mpdscribble/issues/29) this feature is not yet implemented. Even more, I could not get it to run (see log output beneath).

### Steps To Reproduce
1. Enable `mpdscribble` module with proposed Listenbrainz configuration
2. Watch it fail

### Expected behavior
`mpdscribble` scrobbles to Listenbrainz.

### Additional context

NixOS configuration
```nix
{
  services.mpdscribble = {
    enable = true;
    endpoints = {
      "listenbrainz" = {
        passwordFile = "redacted";
        username = "redacted";
      };
    };
  };
}
```

Log output to systemd
```bash
mpdscribble[3648499]: 2023-09-02T13:13:10+0200 loaded 0 songs from /var/lib/mpdscribble/listenbrainz.journal
mpdscribble[3648499]: 2023-09-02T13:13:11+0200 [listenbrainz] waiting 60 seconds before trying again
mpdscribble[3648499]: 2023-09-02T13:14:11+0200 [listenbrainz] waiting 120 seconds before trying again
mpdscribble[3648499]: 2023-09-02T13:16:12+0200 [listenbrainz] waiting 240 seconds before trying again
```

### Notify maintainers

@sohalt

(Thanks a lot for packaging and providing the module!)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[lennart:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.553.e7603eba51f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Sohalt** [comment]
Afaict listenbrainz should support scrobbling with your musicbrainz ID as the username and listenbrainz authorization token as password (inside the passwordFile). What's not supported according to the issue is scrobbling the musicbrainz ID.

**Comment by riotbib** [comment]
Wow, thanks a lot for the fast help! This is very much appreciated.

```bash
mpdscribble[96369]: 2023-09-10T12:15:35+0200 [listenbrainz] OK
```

Using the User token from [the profile page of listenbrainz](https://listenbrainz.org/profile/) solved it.

I'd open a PR improving documentation for Listenbrainz in the module soon.
