### ISSUE TITLE
kodiPackages is not extensible

### ISSUE THREAD

**Issue by M-Gregoire** [NixOS/nixpkgs#254364]
### Describe the bug

I'm currently trying to use a locally defined kodi package. Based on:
https://nixos.wiki/wiki/Overlays#Overriding_a_package_inside_a_scope
and
https://github.com/NixOS/nixpkgs/blob/2d1fbe6294441ad22f4d1ed354ee3c0dc0402fd1/lib/customisation.nix#L259

I expected to be able to do something close to
```
   myKodiPackages = pkgs.kodiPackages.overrideScope'
       (self: super: { my-package = ./callPackage ./my-package.nix { }; });
```
But this fails with `error: attribute 'overrideScope' missing`.

Digging in the source code, I'm wondering whether this is linked to the way the scope is created:
Kodi uses `newScope` directly ([here](https://github.com/NixOS/nixpkgs/blob/b0d76c306b876e5da14dacbf452cc8baf9bbfdc4/pkgs/top-level/kodi-packages.nix#L14)) while other packages use the wrapper function `makeScope` ([like coq](https://github.com/NixOS/nixpkgs/blob/2ff96cc899c4e0d9af4261583a571ae68775bc98/pkgs/top-level/coq-packages.nix#L168)).

Before digging any further, I wanted to make sure whether this might have been intentional, and to ask how you usually go with local declaration of kodi packages.

Thank you

### Notify maintainers

(Hopefully the notification is not too wide!)
@aanderse 
@cpages 
@edwtjo 
@minijackson 
@peterhoeg 
@sephalon

**Comment by aanderse** [comment]
You're correct that this is a missing feature. There hasn't been desire enough for anyone to find the time to write this up. If you did I would be happy to review and test the change.

**Comment by M-Gregoire** [comment]
Thank you for taking the time to answer! I'll give a crack at it to see If I can manage to make it work.

In the meantime, can I ask how you usually go with kodi addons packaging then? Do you have a full copy of nixpkgs for local development to try it out before pushing to `nixpkgs`?

**Comment by peterhoeg** [comment]
> Do you have a full copy of nixpkgs for local development to try it out before pushing to nixpkgs?

This is pretty much what everybody who contributes to nixpkgs does.

**Comment by nvmd** [comment]
Hi @M-Gregoire! Have you also checked these unmerged PRs: https://github.com/NixOS/nixpkgs/pull/209580, https://github.com/NixOS/nixpkgs/pull/126675?
Can't check exactly right now, but I believe at least one of them should do what you want. I'm using them in my fork rebased on top of the latest `nixos-23.05`.

**Comment by aanderse** [comment]
accomplished in #304097
