### ISSUE TITLE
Steam doesn't use KDE cursor

### ISSUE THREAD

**Issue by bugworm** [NixOS/nixpkgs#25444]
## Issue description
Steam use default cursor when trying to use breeze or oxygen cursors. Manually installed cursors (for example this https://store.kde.org/p/999970/ ) works fine

### Steps to reproduce
Pick one of default cursors
Launch steam

## Technical details

* System: NixOS 17.03.1082.4aab5c5798 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1082.4aab5c5798

**Comment by ttuegel** [comment]
IIRC, Breeze and Oxygen cursors are SVG; some applications cannot handle SVG cursors. It is also possible that Steam hardcodes XDG search paths, so it find user-installed themes but not system-installed themes.

CC: @jagajaga

**Comment by SuperSamus** [comment]
Breeze cursor works fine on my end.
![image](https://user-images.githubusercontent.com/40663462/199707812-b4ba6eda-944b-41cf-ba5f-d22853700f87.png)

**Comment by doublevoid** [comment]
Breeze cursor _does not_ work fine on my end. I'm on Plasma 6 on the unstable channel.
![image](https://github.com/NixOS/nixpkgs/assets/28327839/61020ba9-c9b3-4e44-9fe3-29af86c6ad82)
Adding a manual override to the steam package fixes the cursor.
```nix
  programs.steam.package = pkgs.steam.override {
    extraPkgs = p: [
      p.kdePackages.breeze
    ];
  };
```

**Comment by SuperSamus** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/40663462/5eb62d9f-5ad1-42ce-867c-6c2cf555d96d)
I can't reproduce.

**Comment by doublevoid** [comment]
@SuperSamus Installed through Flatpak or nixpkgs?

**Comment by SuperSamus** [comment]
```
programs.steam.enable = true;
```

**Comment by doublevoid** [comment]
Weird to say the least.

**Comment by SuperSamus** [comment]
Try deleting all theme related files/folders (like `.config/gtk*`) and reapplying the theme on KDE's settings?

**Comment by doublevoid** [comment]
Gave that a try right now, sadly didn't work.
I wonder why adding the breeze package directly into Steam `extraPkgs` makes it work though.

**Comment by Kommynct** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/10808 probably related to this
