### ISSUE TITLE
Impurity in haskell builds

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#25447]
Unfortunately I wasn't able to reproduce this, but I'm guessing it has something to do with parallel builds being on... One time when building `vector-algorithms` I got:

> properties: internal error: evacuate: strange closure type 0
>     (GHC version 8.0.2 for x86_64_unknown_linux)
>     Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

but a subsequent build succeeded.

**Comment by shlevy** [comment]
@peti

**Comment by peti** [comment]
It's probably more appropriate to report this issue to the authors of `vector-algorithms` and/or `ghc` since it's not terribly likely that this would be a Nix-specific issue.

**Comment by shlevy** [comment]
Sure, but nix needs to decide whether or not to keep parallel builds on right?

**Comment by peti** [comment]
What evidence is there for parallel builds being the cause of this issue?

**Comment by shlevy** [comment]
Not a huge amount, but it's more likely as a source of non-determinism than other things. I'm not suggesting we turn this off just based on this one report, but if we get more of these then I think we should consider it.

**Comment by peti** [comment]
Yes, that makes sense.
