### ISSUE TITLE
Webcord turns blank after a few seconds of use

### ISSUE THREAD

**Issue by Nocxium** [NixOS/nixpkgs#254539]
### Describe the bug
webcord window turns blank after a few seconds of use.
The issue started about a week ago after an update.

running under -v gives this output:

Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.

### Steps To Reproduce
1. install webcord on unstable branch
2. open app and wait for a few seconds

### Expected behavior
open the app without a crash

### Notify maintainers
@huantianad 

### Metadata
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.1, NixOS, 23.11 (Tapir), 23.11.20230908.db9208a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/9incrwprw2s90minyy0gpmwbxmrkcx1v-source`

**Comment by JulianFP** [comment]
Yes, I can reproduce this. This is a known upstream bug in Electron, and it has already been reported on both [webcord](https://github.com/SpacingBat3/WebCord/issues/452) and [electron](https://github.com/electron/electron/issues/39515) repos. The only workaround for now is to revert back to Electron 25 (for example the [AUR package](https://aur.archlinux.org/packages/webcord) over on Arch has already done this).

I suggest that the webcord package should revert back to electron 25 until electron 27 comes out (which seems to not have this problem anymore).

**Comment by Nocxium** [comment]
Thanks :)
