### ISSUE TITLE
Update request: libheif 1.15.2 → 1.16.2

### ISSUE THREAD

**Issue by linyinfeng** [NixOS/nixpkgs#254500]
- Package name: libheif
- Latest released version: 1.16.2

- Current version on the unstable channel: 1.15.2
- Current version on the stable/release channel: 1.15.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@gebner

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by vcunat** [comment]
Done by PR #274003
(but it can take a while to reach whatever channels you use)
