### ISSUE TITLE
Slack: Screensharing broken (4.33.84/4.33.90)

### ISSUE THREAD

**Issue by SebTM** [NixOS/nixpkgs#254522]
### Describe the bug
Try to screenshare in a huddle - when clicking screensharing icon slack crashes. Applied Option B of the mesa-fix already, tried with/without hardware-acceleration, with/without `--disable-gpu`-flag, with/without wayland-flags.

### Steps To Reproduce
1. Open Huddle in a channel
2. Try to screenshare
3. Slack will crash (because of segfault)

### Expected behavior
Screensharing working

### Additional context
Coredump: https://pastebin.com/FmLv4yEZ

### Notify maintainers
@mmahut
@maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.1, NixOS, 23.11 (Tapir), 23.11.20230910.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/jy6rzyvpsx43x0k0vwk9faymw4aa2y0m-source`
```

**Comment by kirillrdy** [comment]
greetings I just tried screensharing in slack  4.34.115 64-bit ( master )

worked for me

```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.11 (Tapir), 23.11.20230912.35e3b6f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(kirillvr): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

also this is using wayland

**Comment by SebTM** [comment]
Can confirm, cherry-picking [this](https://github.com/NixOS/nixpkgs/commit/acdede901e1ff4e6afaf3d117c79de5818b6b338) commit to my nixpkgs-unstable checkout solves the issue. Would leave it open for others having problems until it lands in unstable - just side node (not relevant for me) can't open Help -> About anymore after update (when I wanted to check version)

**Comment by kirillrdy** [comment]
@SebTM do you mean `Help -> About Slack` ?  this also works for me

**Comment by SebTM** [comment]
> @SebTM do you mean `Help -> About Slack` ? this also works for me

Correct, I can see the following in logs:

```
[09/23/23, 15:56:57:752] info: Store: CREATE_WINDOW {
  "type": "about-box"
}
[09/23/23, 15:56:57:752] info: Store: CREATE_WINDOW {
  "type": "about-box"
}
[09/23/23, 15:56:59:191] info: Store: CREATE_WINDOW {
  "type": "about-box"
}
[09/23/23, 15:56:59:191] info: Store: CREATE_WINDOW {
  "type": "about-box"
}
```

Tried multiple times to open it and can see this events but main windows is not blocked (still usable) and no new window can be found.

**Comment by SebTM** [comment]
Fixed in latest release, Backport for it coming up so going to close it. #257149
