### ISSUE TITLE
Building packages for custom NIX_STORE_DIR fails

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#25462]
## Issue description
I am unable to build nix-store to a custom location. It builds up several packages fine but fails while shrinking RPATHs or ELF executables and libraries.

### Steps to reproduce
Get all the dependency and build custom nix in a docker container with ubuntu:16.04 and run a nix-env -iA nixpkgs.nix with -v `pwd/nix:$NIX_STORE_DIR in the container. I am not sure if the issue is because I am trying to build this via a docker container or something else is screwed up. 

This is repeatable irrespective of the channels I am using 16.09/17.03 or latest nixpkgs.

## Technical details
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
   Distributor ID: Ubuntu
   Description:    Ubuntu 16.04.1 LTS
   Release:        16.04
   Codename:       xenial

* Nix version: (run `nix-env --version`)
   nix-env (Nix) 1.11.9

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.09pre106045.7369fd0b51

==============================================
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /home/scratch/royadav/opt/nix/store/8armd0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29
shrinking /home/scratch/royadav/opt/nix/store/8armd0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29/bin/tar
shrinking /home/scratch/royadav/opt/nix/store/8armd0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29/libexec/rmt
gzipping man pages under /home/scratch/royadav/opt/nix/store/8armd0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29/share/man/
stripping (with flags -S) in /home/scratch/royadav/opt/nix/store/8armd0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29/libexec  /home/scratch/royadav/opt/nix/store/8arm
d0rx7kdmalqpvcx0zhxvdjdh6a42-gnutar-1.29/bin
shrinking RPATHs of ELF executables and libraries in /home/scratch/royadav/opt/nix/store/5nb9v5zrp9dndd6lzw7n9vxr5qzpd212-gnutar-1.29-info
error (ignored): getting status of ‘/tmp/nix-build-gnutar-1.29.drv-0/tar-1.29/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/
confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdi
r3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/con
fdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/
confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdi
r3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/con
fdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/
confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdi
r3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/con
fdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/
confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdi
r3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3’: File name too long

**Comment by rowhit** [comment]
It was an issue with building nix inside a docker container. However, it builds fine in lxc container or chroot.

**Comment by peculiarity** [comment]
I experience the same issue. What is the solution? Is there a solution to that problem apart of changing the container type ?
