### ISSUE TITLE
Set CMAKE_CROSSCOMPILING and CMAKE_SYSTEM_NAME when cross compiling with cmake

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#25477]
## Issue description

`CMAKE_CROSSCOMPILING` is not set when a cross compile is in progress.

https://cmake.org/cmake/help/v3.0/variable/CMAKE_CROSSCOMPILING.html

This is necessary for several packages, such as LLVM, to cross compile correctly.

When `buildPlatform != hostPlatform` the additional cmake argument `-DCMAKE_CROSSCOMPILING=True` should be used

**Comment by aneeshusa** [comment]
@Ericson2314 mentioned this may be more elegant with https://github.com/NixOS/rfcs/pull/13.

**Comment by matthewbauer** [comment]
Okay closing #47192 in favor of this one.

**Comment by expipiplus1** [comment]
Thanks!
