### ISSUE TITLE
nix-env and nixpkgs/config.nix matches no derivations

### ISSUE THREAD

**Issue by husnoo** [NixOS/nixpkgs#25474]
## Issue description
```
$ cat .config/nixpkgs/config.nix 
# nix-env -i all

with import <nixpkgs> {};

{
    allowUnfree = true;
    
    all = with pkgs; buildEnv {
        name = "all";
        paths = [
            vlc     
        ];
    };
}
```

### Steps to reproduce
```
$ nix-env -i all
error: selector â€˜allâ€™ matches no derivations

$ nix-env -Q -iA nixos.all
error: attribute â€˜allâ€™ in selection path â€˜nixos.allâ€™ not found

$ nix-env -Q -iA all
error: attribute â€˜allâ€™ in selection path â€˜allâ€™ not found

$ nix-env -Q -iA nixpkgs.all
error: attribute â€˜nixpkgsâ€™ in selection path â€˜nixpkgs.allâ€™ not found
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
$ nixos-version
17.03.1082.4aab5c5798 (Gorilla)

$ nix-env --version
nix-env (Nix) 1.11.8

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1082.4aab5c5798"

```

**Comment by copumpkin** [comment]
You want `packageOverrides`; see http://nixos.org/nixpkgs/manual/#sec-modify-via-packageOverrides. I consider it bad that we don't check the schema of config.nix, but you could set `all = throw "haha";` and it would never fail because nothing refers to it.

**Comment by husnoo** [comment]
Doesn't work... To recap: I'm trying to create a user profile of programs to install.

```
$ cat ~/.config/nixpkgs/config.nix 
# nix-env -i all                

with import <nixpkgs> {};

{
    allowUnfree = true;

    packageOverrides = pkgs: rec {
        foo = pkgs.foo.override {
            packages = [
                vlc
            ];
        };
    };
}

$ nix-env -i pkgs.foo
error: attribute â€˜fooâ€™ missing, at /home/nawal/.config/nixpkgs/config.nix:9:15
```

**Comment by Ekleog** [comment]
In this this case I think an [overlay](https://nixos.org/nixpkgs/manual/#chap-overlays) would handle the problem quite well.

Closing as this kind of questions would be better-located on the [discourse](https://discourse.nixos.org/), feel free to open a thread there if this answer doesn't work for you!

**Comment by sneak** [comment]
Found this issue Googling whilst trying to figure out the same issue.  If someone finds a solution, please link it here.

**Comment by sneak** [comment]
The `config.nix` contents here seems to work:

https://nixos.org/nixpkgs/manual/#sec-building-environment
