### ISSUE TITLE
Git-flow missing runtime dependencies git and getopt

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#25487]
I'm not sure whether purely runtime dependencies should be defined or not. Anyway, [gitflow](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-and-tools/gitflow/default.nix) isn't specifying git and getopt as its propagated build inputs although those packages are required for gitfow to work properly. So should they be added?

**Comment by jluttine** [comment]
Hmm.. Perhaps this is just related to the fact that I'm using FHS user environment. It works in normal nix shell if I run `nix-shell -p gitAndTools.gitflow`.

**Comment by jluttine** [comment]
Actually it turned out that with pure nix shell, it doesn't work. So here's a more comprehensive bug(?) report. I'm not sure if this is a bug or is this just how it's supposed to be. To me, this seems weird.

## Issue description

`gitAndTools.gitflow` doesn't work without manually adding build time dependencies `git` and `getopt` to the environment.

### Steps to reproduce

Let's create some playground:
```
$ mkdir /tmp/foobar
$ cd /tmp/foobar
```

Gitflow doesn't install git so it cannot be used:
```
$ nix-shell --pure -p gitAndTools.gitflow
$ git init
bash: git: command not found
$ exit
```

Also, getopt is missing:
```
$ nix-shell --pure -p gitAndTools.gitflow -p git
$ git init
$ git commit --allow-empty -m "initial commit"
$ git flow init
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 158: _flags_fatal: command not found
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 273: [: too many arguments
/nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /nix/store/m6yvaai1hdijfy52f544nw2fxc5sq27a-gitflow-1.10.2/bin/gitflow-shFlags: line 739: getopt: command not found
flags:FATAL unable to parse provided options with getopt.
$ exit
```

With both git and getopt given, it gitflow works:
```
$ nix-shell --pure -p gitAndTools.gitflow -p git -p getopt
$ git flow init
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ nixos-version
17.09.git.88fe719 (Hummingbird)
```

* Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.9
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09.git.88fe719e64M"
```

**Comment by FRidh** [comment]
How does `git` find extra commands defined in other packages?

**Comment by jluttine** [comment]
I guess `getopt` dependency can be fixed by wrapping all necessary executables in `$out/bin` similarly as only `$out/bin/git-flow` is currently wrapped. I can do that if that is the correct way.

But I don't know how to fix `git` dependency.

**Comment by jluttine** [comment]
Actually, I think I got it now.

Replaced
```
  buildInputs = optionals (stdenv.isDarwin) [ pkgs.makeWrapper ];
```
with
```
  buildInputs = [ pkgs.makeWrapper ];
```

Replaced
```
  postInstall = optional (stdenv.isDarwin) ''
    wrapProgram $out/bin/git-flow \
      --set FLAGS_GETOPT_CMD ${pkgs.getopt}/bin/getopt
  '';
```
with
```
  postInstall = ''
    wrapProgram $out/bin/git-flow \
      --set FLAGS_GETOPT_CMD ${pkgs.getopt}/bin/getopt \
      --suffix PATH : ${pkgs.git}/bin
  '';
```

Now, one can use `git-flow` successfully. If the user wants `git` and use `git flow` instead of `git-flow`, (s)he needs to install `git`. Makes sense.

Any thoughts? I don't know why there were conditionings on `isDarwin`. Should I remove the conditioning or add `or isLinux`?

**Comment by FRidh** [comment]
Seems like a good fix to me. Open a PR I'd say.
