### ISSUE TITLE
Build failure: mpfi

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#254809]
### Steps To Reproduce

1. build `mpfi`

### Build log

```
building '/nix/store/qgnqv0sw8lmg33sp6cldjx0ifs4xlfyz-mpfi-1.5.4.tgz.drv'...

trying https://gforge.inria.fr/frs/download.php/file/38111/mpfi-1.5.4.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   162    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download mpfi-1.5.4.tgz from any mirror
```

### Additional context

The download URL seems to be dead. Maybe it's related to other restructuring on INRIA infrastructure (see e.g. https://github.com/NixOS/nixpkgs/pull/252997).

### Notify maintainers

@7c6f434c 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-82-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by 7c6f434c** [comment]
Annoyingly, it looks like no form of the tarball has survived the migration (i.e. the fix is not just a URL change, but also autoreconf)…

**Comment by zeuner** [comment]
Well, if the tarball cannot be recovered somehow, I can only offer the workaround I use here: https://github.com/NixOS/nixpkgs/pull/254814

Since I never had the original tarball, I can't see what this might change. Apparently, they tagged an unbuildable state on gitlab...

**Comment by 7c6f434c** [comment]
We can definitely get the old tarball from cache.nixos.org. Actually the lead author has some tarball on the homepage, I have not checked if it is the same. The tarball seems to have the missing file; tagged version contains the declaration of the missing function… 

The file has appeared in the Git history two weeks after the release tag, literally in the next commit. Which at least builds.

**Comment by 7c6f434c** [comment]
Some rev-deps also build. Sage in process. Not sure if the tests there cover div_ext, though

**Comment by 7c6f434c** [comment]
So, what do we do? Close your PR and merge mine? Or is anything missing in the «grab the next commit when the file was added» approach?

**Comment by zeuner** [comment]
Your PR looks cleaner to me. I'd just prefer if it wouldn't silently fetch the same commit in case the package is updated to a new version some day.
