### ISSUE TITLE
Update request: `wasm-pack` 0.11.1 → 0.12.1

### ISSUE THREAD

**Issue by eureka-cpu** [NixOS/nixpkgs#254882]
- Package name: wasm-pack
- Latest released version: 0.12.1

- Current version on the unstable channel: 0.12.1
- Current version on the stable/release channel: 0.11.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@dhl 🙏🏻 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pbsds** [comment]
fixed in #240214
