### ISSUE TITLE
Systemd services should allow wildcards in some attributes like `requiredBy`

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#254946]
The regular expression that validates some attributes for system services in the nixos module is too restrictive. For example this snippet of a service definition:

```nix
{
  systemd.services.generate-acme-secret = {
    requiredBy = [ "acme-*.service" ];
    before = [ "acme-*.service" ];
    # ...
  };
  # ...
}
```
would be valid, were it not for:
```
error: A definition for option `systemd.services.generate-acme-secret.before."[definition 1-entry 1]"' is not of type `string matching the pattern [a-zA-Z0-9@%:_.\-]+[.](service|socket|device|mount|automount|swap|target|path|timer|scope|slice)'. Definition values:
       - In `/nix/store/6pldlypc20h6lkv4z1srl7wjjyx3km8p-source/machines/acme.nix': "acme-*.example.com.service"
```

**Comment by chasevasic** [comment]
for RequiredBy, at least, i get this when I try to use a wildcard:
Failed to enable unit: "acme-*.service" is not a valid unit name.

**Comment by con-f-use** [comment]
Hmm... you right, I'm very sorry, it works with eg. `journalctl -u acme*.service` and a few other select things, but I must have imagined using in requiredBy. :eyes: Kinda disappointing.
