### ISSUE TITLE
kodi dont react to xbox controller after update to 17.03

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#25490]
## Issue description

I have a htpc with nixos 16.10 installed and a wireless xbox controller connected to a usb receiver. Which works fine in 16.09 but if I upgrade to 17.03 it stopps working.

### Steps to reproduce

related settings:
```
  services.xserver.desktopManager.kodi.enable = true; 
  services.xserver.displayManager.slim = {
    defaultUser = "...";
    autoLogin = true;
  };
  boot.blacklistedKernelModules = [ "xpad" ];

  systemd.services.xboxdrv = {
    wantedBy = [ "multi-user.target" ]; 
    after = [ "network.target" ];
    serviceConfig = {   
      Type = "forking";
      User = "root";
      ExecStart = "${pkgs.xboxdrv}/bin/xboxdrv --daemon --detach --pid-file /var/run/xboxdrv.pid --dbus disabled --silent --detach-kernel-driver --deadzone 4000 --deadzone-trigger 10% --mimic-xpad-wireless";
    };
  };

  services.xserver.config = ''
   Section "InputClass"
        Identifier "joystick catchall"
          MatchIsJoystick "on"
       	  MatchDevicePath "/dev/input/event*"
      	  # MatchDevicePath "/dev/input/js*"
          #Driver "joystick"
  	Driver "evdev"
          Option "StartKeysEnabled" "False"
          Option "StartMouseEnabled" "False"
        # Option "MapAxis1" "deadzone=4000"
        # Option "MapAxis2" "deadzone=4000"
   EndSection
  '';
```

Build it.... test your xbox wireless controller

## Technical details

I tried to comment out all in case the standard xpad driver can handle the wireless controller. I looked into the new input settings Interfaces inside kodi but it was grayed out always.

If I activate mouse support in kodi, I can use one analog stick as mouse.

**Comment by spiderbit** [comment]
I think the new kodi-joystick package is missing like here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855115

**Comment by spiderbit** [comment]
I tried to add kodi support it did build and kind of install, but neither is the controller working nor do I find even a category peripheral in the plugins menu inside kodi.

https://gist.github.com/spiderbit/1b11d2e2d1eef6c9d3a0aa516fe95ff2

I put the 2 files for now into gist I might push it to a proper nixpkgs fork later... just not time for that right now.

**Comment by edwtjo** [comment]
I've cherry picked some of the latest kodi plugins fixes, which includes the abi joystick support. Please let me know how it works out.

**Comment by spiderbit** [comment]
So sorry for the late answer, but it seems to have fixed nothing for me.

I: Bus=0003 Vendor=045e Product=028e Version=0110
N: Name="Microsoft X-Box 360 pad"
P: Phys=
S: Sysfs=/devices/virtual/input/input17
U: Uniq=
H: Handlers=event15 js0 
B: PROP=0
B: EV=b
B: KEY=7cdb000000000000 0 0 0 0
B: ABS=3003f

* /proc/bus/input/devices


[144125.085] (**) evdev: TPPS/2 IBM TrackPoint: Device: "/dev/input/event15"
[144125.086] (II) evdev: TPPS/2 IBM TrackPoint: Configuring as mouse

I changed that line in the Xconfig path:
 MatchDevicePath "/dev/input/event*"
to
 MatchDevicePath "/dev/input/event15"

but apperently on that laptop I just test that cause I dont want to test it on my production htpc the device apperently gets configured / detected as mouse.

so is there a way to prioratise my services.xserver.config over autodetection or the default xserver config in nixos?

**Comment by spiderbit** [comment]
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x45e product 0x28e version 0x110
Input device name: "Microsoft X-Box 360 pad"Event: time 1499635491.265476, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 1
Event: time 1499635491.265476, -------------- SYN_REPORT -----------

the xboxdrv driver itself works evtests reacts to it.

**Comment by spiderbit** [comment]
Wait a second, is that current X log?
[144104.457] (++) Log file: "/var/log/X.0.log", Time: Sun Jul  9 18:06:26 2017

Thats the right date but its 11-12 p.m. when I did that tests. I am confused

**Comment by spiderbit** [comment]
ok so I just found the time to test it outside of nixos with a fresh fedora 26 installation.

I had no luck with it too. It seems that either xboxdrv itstelf or my xbox rfid dongle thing is not supported by kodi anymore somehow.

its pretty straight forward:

xboxdrv --mimic-xpad print all button events. this package is pretty old there are no new regressions.

I don't see button events in the debug log, it just gets ignored.

When I pin back the repositories for fedora24 (for some dependencies) and rpmfusion 24 where the last kodi 16.x version is and I install that, the controller just works.

So for me it seems that the kodi team removed support for wireless xbox360 controllers for good or xboxdrv / xpad driver support at all.

As far as I understand this kodi joystick plugin thing is installed when this joystick configuration dialog is in the settings, and that it is.

So its not fixable except with patches upstream that ignores aperently all xboxdrv / xpad devices in the system.

So you can close this, cause thats a upstream distroindependend bug, I am aperently the only person on the planet that uses a xbox controller + linux + kodi. Thought one advantage with opensource is no planed obsoleszenz but apperently I am supposed to throw that controller in the trash and buy a steam controller if I even want to upgrade kodi in my live again.

**Comment by a1rwulf** [comment]
https://github.com/NixOS/nixpkgs/blob/19879836d10f64a10658d1e2a84fc54b090e2087/pkgs/applications/video/kodi/plugins.nix#L152

For kodi krypton this should look like:

`
  joystick = mkKodiABIPlugin rec {
    namespace = "peripheral.joystick";
    version = "1.3.2";
    plugin = namespace;

    src = fetchFromGitHub {
      owner = "kodi-game";
      repo = namespace;
      rev = "b464260082cc1c6edeb41b70af00da7ce8c9844c";
      sha256 = "<new sha>";
    };

    meta = with stdenv.lib; {
      description = "Binary addon for raw joystick input.";
      platforms = platforms.all;
      maintainers = with maintainers; [ edwtjo ];
    };

    extraBuildInputs = [ libusb pcre-cpp ];

  };
`

**Comment by a1rwulf** [comment]
And for the record, this is an absolute nogo for any official distro:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/kodi/plugins.nix#L102

It's a plugin that promotes piracy and offers illegal content!

**Comment by spiderbit** [comment]
```
  joystick = mkKodiABIPlugin rec {
    namespace = "peripheral.joystick";
    version = "1.3.2";
    plugin = namespace;

    src = fetchFromGitHub {
      owner = "kodi-game";
      repo = namespace;
      rev = "96171dd32899553ffe8fc775fca66e8df5ff5cf1";
      sha256 = "18m61v8z9fbh4imvzhh4g9629r9df49g2yk9ycaczirg131dhfbh";
    };
```

that works well partialy. I still have to link the addon in my user repository with:

ln -s /nix/store/f3x0r6k6qq79liqvl27z7vgswkgpb6md-kodi-plugin-peripheral.joystick-1.3.2/share/kodi/addons/peripheral.joystick .

but other than that, it seems to work. I think on my test machine I am now in nixos 18.03 (a fresh checkout of git master) but this should be working for 17.03 and 17.10 too cause its all the same kodi version 17.x

**Comment by spiderbit** [comment]
Maybe that commit would be better, still version 1.3.2 so compatible with kodi 17.x but a few commits later:
62c8dc38e0a0cbc1ac3ebcf089687feefdb1a8fc

But it must be one with the 1.3.2 version else its api incompatible and does not work.

**Comment by cpages** [comment]
Kodi 18 just landed in master, and I updated the joystick plugin for it. It works for me with a wired xbox controller, but I don't have any wireless one to try. Would be nice if someone can test and see if we can close this

**Comment by cpages** [comment]
I'm closing this, outdated
