### ISSUE TITLE
Fix CoreCLR

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#25498]
## Issue description

CoreCLR is currently marked as broken, because it's tricky to get building. @obadz helpfully posted a comment with issues encountered, which I'm just going to reproduce here. cc @ForNeVeR who's expressed interest in resurrecting CoreCLR too.

From @obadz:
> My recollection is quite hazy on the details but basically it was never clear (or documented in a way that I could find) where I was expected to fetch a bootstrapping compiler, where I was expected to put it, what commands I was expected to invoke to run the build, and even: after the the build, what was the relevant output files to keep and how should they be organized in a certain directory structure to be usable.
> 
> coreclr is only one of the subprojects that one needs to build to get to a useful setup. There's also corefx and a few others. Was also not clear to me what the exhaustive list was.
> 
> Here are some relevant issues/pulls:
> 
> dotnet/corefx#6770 (comment)
> dotnet/coreclr#917
> dotnet/coreclr#1198
> dotnet/coreclr#7573
> dotnet/coreclr#7675

(see https://github.com/NixOS/nixpkgs/commit/1dd16a93741c425880ac81d1e611af7be050c96b#commitcomment-21961855 for full context)

**Comment by baracoder** [comment]
There are some prebuild packages. Would it be easier to use them instead? https://www.microsoft.com/net/download/linux

**Comment by copumpkin** [comment]
Probably easier, but we generally try to build from source where possible. But if it's a choice between not working at all or using prebuilt packages, I'll take the latter 😄

**Comment by obadz** [comment]
There seems to be some useful information here: https://github.com/dotnet/source-build (thanks @janvorli for pointing me to it here: https://github.com/dotnet/corefx/issues/6770#issuecomment-324491220).

I might give a go at building .NET Core on Nix again. Let's centralize communication on this topic on this issue.

**Comment by obadz** [comment]
I gave up without much of an attempt (sorry). Focusing my dev efforts on nimlang instead.

**Comment by kuznero** [comment]
I would like to jump on this and help. But I am trying to make an attempt upgrading it in the same time (coreclr 2.0.0). Currently it fails on build step complaining about glibc header:

```
...
In file included from /tmp/nix-build-coreclr-2.0.0.drv-0/coreclr-v2.0.0-src/src/pal/src/cruntime/file.cpp:22:
In file included from /tmp/nix-build-coreclr-2.0.0.drv-0/coreclr-v2.0.0-src/src/pal/src/include/pal/palinternal.h:578:
In file included from /nix/store/g65l985579ri87i8m3906a2nmyrl24a2-gcc-6.4.0/include/c++/6.4.0/stdlib.h:30:
/nix/store/zsfnlmvw8k7akg1s0ypdy5jd1kq0d8hn-glibc-2.25-49-dev/include/stdlib.h:63:5: error: typedef redefinition with different types ('struct DUMMY_div_t' vs 'struct DUMMY_div_t')
  } div_t;
    ^
/tmp/nix-build-coreclr-2.0.0.drv-0/coreclr-v2.0.0-src/src/pal/src/include/pal/palinternal.h:163:15: note: expanded from macro 'div_t'
#define div_t DUMMY_div_t
              ^
/tmp/nix-build-coreclr-2.0.0.drv-0/coreclr-v2.0.0-src/src/pal/inc/pal.h:5171:3: note: previous definition is here
} div_t;
  ^
/tmp/nix-build-coreclr-2.0.0.drv-0/coreclr-v2.0.0-src/src/pal/src/include/pal/palinternal.h:163:15: note: expanded from macro 'div_t'
#define div_t DUMMY_div_t
              ^
1 error generated.
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/build.make:63: src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:281: src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...
```

I can see that there is an assumption for coreclr to be compatible with glibc coming from ubuntu 14.04 which is `2.19` whether in nix it is `2.25`. Is that the issue that others observe as well or am I just doing something wrong?

**Comment by janvorli** [comment]
@kuznero this is strange, the mechanism in pal.h / palinternal.h with #define div_t DUMMY_div_t / #undef is supposed to prevent this kind of issue from happening. 
You have mentioned 2.0.0 - does it mean you have checked out sources at release/2.0.0 branch?

**Comment by kuznero** [comment]
@janvorli I think it checks out archive released by 2.0.0 tag. So, I don't think it is a branch. Basically I just changed the version and a hash.

**Comment by janvorli** [comment]
@kuznero I have thought you are just trying to build coreclr repo by itself, but now looking back at the discussion, I guess you are trying to use the source_build repo, right? If that's the case, I would recommend to wait a bit since there is now ongoing effort to remove patches that the build from sources applies to various repos it builds and make it all sustainable w.r.t. changes in the repos it includes in the build. You can also help with this effort if you want. @weshaggard and @eerhardt are driving that.

**Comment by obadz** [comment]
I had to add these things to build this way back when. Maybe they are now causing the issue?

https://github.com/NixOS/nixpkgs/blob/1dd16a93741c425880ac81d1e611af7be050c96b/pkgs/development/compilers/coreclr/default.nix#L50-L63

**Comment by kuznero** [comment]
@obadz thanks, will try to play with it

**Comment by kuznero** [comment]
@obadz That seem to help. So, it just works. Do you have a chance to try it as well? On [this](https://github.com/kuznero/nixpkgs/blob/e77c9df6006e751085711c10caeb376722e394c2/pkgs/development/compilers/coreclr/default.nix) repo: `nix-env -f . -i coreclr`.

**Comment by ForNeVeR** [comment]
I've checked if the coreclr builds; it looks okay. But does anyone have idea what we'll do next? CoreCLR is only a runtime part of the .NET Core SDK, right? Does that mean we still need to build `dotnet-cli`? Something else?

**Comment by kuznero** [comment]
corefx and then nuget packages

**Comment by simendsjo** [comment]
I'm interested in getting dotnet running on nixos, but I don't even have a working knowledge of nix (I'm cargo-culting everything). Anything I can do to help?

**Comment by leo60228** [comment]
This bug is fixed. However, a large part of this issue seems to be building .NET Core from source, which is still not done. Perhaps that should be a separate issue?

**Comment by janvorli** [comment]
There is a dotnet/source-build repo that is the intended way to build .NET Core from sources in various Linux repos. It seems it would make sense to try that.

**Comment by leo60228** [comment]
I tried that a while back. If I recall correctly, there was no clear way to
do the build without network access.

**Comment by leo60228** [comment]
https://github.com/dotnet/source-build/issues/1887

**Comment by janvorli** [comment]
As far as I know, it should work without network access. I believe the build in source-build repo would produce a source tarball and that's what you'd use for the build on your NixOS.

**Comment by leo60228** [comment]
Yeah, I think I was mixing it up with whatever the predecessor to
source-build was. Do you know if pregenerated source tarballs are available
anywhere?

**Comment by janvorli** [comment]
I don't know, it would be better to ask in the dotnet-source repo. But since the tarball already contains RID of the target platform, I guess it would not help you. And since NiXOS RID is not supported in .NET Core, it seems you'd need to add it first - either as a patch in the source-build (there is a support for automatically applying patches before build) or in the runtime and installer repos. 
But I am no expert on source-build, so it would be preferable to get more details from folks working on the repo itself.
