### ISSUE TITLE
Firefox in 'master' crashes every time I try to download a file

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#25505]
After a recent Nixpkgs git update, my Firefox browser can no longer download files to the local disk. At the point where the file browser is supposed to pop up to let me choose the directory in which to save the file, the entire browser just crashes. The console doesn't say much:

~~~
$ firefox 

(firefox:20999): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(firefox:20999): Gtk-WARNING **: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(firefox:20999): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap
~~~

This issue occurs in c5badb123a2dd6e2b38dcd2ddbe73e13dc6b554f and earlier. I'll try to find a commit that causes the issue by way of git bisect, but that's no not easy to pull off (for obvious reasons).

**Comment by 7c6f434c** [comment]
There are `gsettings_desktop_schemas` and `gtk3`; there are `/share` and `/share/gsettings-schemas/gsettings-desktop-schemas-*`. Adding some combination of these to `XDG_DATA_DIRS` could help. I guess the wrapper needs updating…

**Comment by vcunat** [comment]
This one should be just `${gtk3.out}/share` IIRC.

**Comment by vcunat** [comment]
I don't understand why on 17.03 it doesn't crash.

**Comment by peti** [comment]
The fix worked! Thank you very much.
