### ISSUE TITLE
Package request: JetBrains RustRover

### ISSUE THREAD

**Issue by Astralchroma** [NixOS/nixpkgs#255001]
**Project description**

JetBrain's Rust IDE, currently only in EAP.

**Metadata**

* homepage URL: [https://www.jetbrains.com/rust/download/#section=linux](https://www.jetbrains.com/rust/download/#section=linux)
* source URL: None
* license: Proprietary
* platforms: Linux

**Comment by shymega** [comment]
This can be closed, #255283 was merged. Or we can wait until it's backported to 23.05?

**Comment by kashw2** [comment]
I think we can close this issue as while it isn't currently available in 23.05 without a backport, is available in [nixpkgs-unstable and nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=255283) channels. Keeping it open would probably just cause it to get forgotten about and sit on the already high numbered pile of issues. It'll inevitably find its way into the default release channel whether that's in 23.05 (with a backport), 23.11 or a future release.
