### ISSUE TITLE
perl 5.24.1 fails to build on linux on staging

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25500]
## Issue description

This time its not failing on [darwin](https://github.com/NixOS/nixpkgs/issues/25090) but linux.

https://nix-cache.s3.amazonaws.com/log/ik0c1jdmzp3nsm6hrf5p6j70wxhbqw3r-perl-5.24.1.drv

* Nixpkgs version: staging at 2dd351

cc @vcunat @plumps @Mic92

**Comment by vcunat** [comment]
I saw no relevant error message in the log, and I couldn't reproduce failure locally nor on Hydra: http://hydra.nixos.org/build/52352025#tabs-buildsteps

Feel free to reopen if you find something of concern.

**Comment by FRidh** [comment]
Odd, it indeed builds. Check http://hydra.nixos.org/eval/1356007?filter=perl&compare=1355720, and look at the "Still failing jobs` tab, and "Still succeeding jobs" tab. `perl524.x86_64-linux` is in the failing tab and `perl.x86_64-linux` in the succeeding while `perl` points to `perl524`.
