### ISSUE TITLE
Package request: Surrealist

### ISSUE THREAD

**Issue by jhackenberg** [NixOS/nixpkgs#255193]
**Project description**

Surrealist is a simple to use query playground and database explorer for [SurrealDB](https://surrealdb.com/). You can connect to any SurrealDB server and execute queries in a graphical interface, including table & variable auto completion, syntax highlighting, and much more. Switch to the explorer view to browse database tables, edit record contents, and traverse graph relationships. Use the designer view to create or modify your database schema, and manage logins and scopes with the authentication view.

**Metadata**

* homepage URL: https://surrealist.starlane.studio/
* source URL: https://github.com/StarlaneStudios/Surrealist
* license: mit
* platforms: unix, linux, darwin

**Comment by MDM23** [comment]
I could provide a working derivation with a precompiled Linux binary from the official deb-package. Building from source would be a bit more difficult as the upstream repo uses pnpm for the frontend and it does not have a regular `package-lock.json` file.
