### ISSUE TITLE
Kitty terminfo

### ISSUE THREAD

**Issue by flanfly** [NixOS/nixpkgs#255121]
### Describe the bug
When running a nix-shell environment with kitty and tmux starting tmux with TERM=xterm-kitty results in `missing or unsuitable terminal: xterm-kitty`. On deb or rpm based distros the terminfo data comes with the kitty package.

### Steps To Reproduce
1. Open kitty, ssh into a system with nix installed.
2. nix-shell -p neovim -p tmux -p kitty
3. tmux

### Expected behavior
tmux starts.

### Additional context
I installed nix using the single user install (but with global /nix store) in Ubuntu 22.04.3.

### Notify maintainers
@tex @rvolosatovs @Luflosi @adamcstephens

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/896332rjx4f470lksz06l7vanb6b9j2k-nix-info
copying path '/nix/store/896332rjx4f470lksz06l7vanb6b9j2k-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-83-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/home/kai/.nix-defexpr/channels/nixpkgs`
```

**Comment by flanfly** [comment]
Adding `--pure` doesn't help/

**Comment by adamcstephens** [comment]
The kitty package in nixpkgs comes with the terminfo, but you need to configure your terminal to read them.

```
─❯ ls /nix/store/2grb5kjvjj405y1qmzmxjvz20vb5fpkk-kitty-0.29.2/lib/kitty/terminfo/
 kitty.termcap   kitty.terminfo   x
```

**Comment by flanfly** [comment]
Thanks. `TERM=kitty tmux` does the trick. The xterm-kitty vs kitty thing seems to be an upstream issue.

**Comment by Luflosi** [comment]
Actually it should work with TERM=xterm-kitty by using the file `/nix/store/...-kitty-0.29.2/lib/kitty/terminfo/x/xterm-kitty`.
What does `echo "$TERMINFO_DIRS"` output?
