### ISSUE TITLE
xdg-utils: broken sed magic

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25511]
## Issue description

bash scripts in ```xdg-utils``` look broken after [being processed](https://github.com/NixOS/nixpkgs/blob/a4868509923aebd66b2aa9aa1d260d882e159b5e/pkgs/tools/X11/xdg-utils/default.nix#L39) by ```sed```:

### Steps to reproduce

![](http://i.imgur.com/jA8akbK.png)
![](http://i.imgur.com/gngc0Q3.png)

## Technical details

* System: 17.09.git.c422348 (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5308_2f21d522
* Nixpkgs version: "17.09.git.c42234875a"

**Comment by lheckemann** [comment]
Seems like it would be more sensible to wrap the utilities and add file and such to its PATH.

**Comment by dezgeg** [comment]
That's probably not done to avoid polluting PATH. A better way would be to add something like this after the shebang line:

````
file() { ${file}/bin/file "$@" }
grep() { ${gnugrep}/bin/grep "$@" }
````

etc.
