### ISSUE TITLE
Package request: guymager

### ISSUE THREAD

**Issue by tylerstyle** [NixOS/nixpkgs#255285]
Guymager is a tool many forensics folk rely on for imaging devices and needed for creating a rounded forensics OS.

Info from site:
Guymager is a free forensic imager for media acquisition. 

Its main features are:
Easy user interface in different languages
Runs under Linux
Really fast, due to multi-threaded, pipelined design and multi-threaded data compression
Makes full usage of multi-processor machines
Generates flat (dd), EWF (E01) and AFF images, supports disk cloning
Free of charges, completely open source

**Metadata**

guymager:
* homepage URL: https://guymager.sourceforge.io/
* source URL: https://sourceforge.net/p/guymager/code/HEAD/tree/
* license: GPLv2
* platforms: linux

libguytools:
* source URL: https://sourceforge.net/p/libguytools/code/HEAD/tree/
* license: GPLv2
* platforms: linux

**Comment by antonmosich** [comment]
I tried to package guymager, and ended up with whats in antonmosich/nixpkgs in the guymager branch. I haven't managed to actually run it so far though.

**Comment by tylerstyle** [comment]
I can't find any reference to Guymager in your repo.
Where should I look?

**Comment by antonmosich** [comment]
https://github.com/antonmosich/nixpkgs/tree/guymager
It is there, in that branch.
