### ISSUE TITLE
Telegram Desktop doesn't work if installed from user space

### ISSUE THREAD

**Issue by bugworm** [NixOS/nixpkgs#25527]
## Issue description
It gives me a strange error:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

Available platform plugins are: wayland-org.kde.kwin.qpa, minimal, offscreen, xcb, vnc.

Reinstalling the application may fix this problem.
[1]    1895 abort      telegram-desktop

```
Works fine if I add it to system config

### Steps to reproduce
`nix-env -iA nixos.tdesktop`
`telegram-desktop`

## Technical details

* System: NixOS: 17.03.1098.a162c6c828 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1098.a162c6c828"

**Comment by lheckemann** [comment]
https://github.com/NixOS/nixpkgs/issues/24256

**Comment by ttuegel** [comment]
This is fixed in `master`, but I will have to see if the patch is eligible to be backported.

**Comment by iblech** [comment]
Unfortunately, it seems that the bug resurfaced.

On a perhaps two weeks old nixos-unstable, `nix-shell -p tdesktop` does not result in a usable Telegram desktop client (SIGABRT immediately on startup), while installing it using `/etc/nixos/configuration.nix` works nicely.
