### ISSUE TITLE
Intel AX210 family (Framework Laptop wifi) regression between kernel 6.4.15 and 6.5.1

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#255288]
### Describe the bug
The Intel AX210-family Wifi in my Framework 13 (11th gen) is recognized by an old generation install (kernel 6.4.8), not by a new install with kernel 6.5.1, but again if I move kernelPackages to linuxPackages_6_4 and get kernel version 6.4.15.

### Steps To Reproduce
1. install nixos with `kernelPackages = linuxPackages_latest;` on a Framework 13 11th gen
2. Note wifi not listed in ifconfig, only loopback
3. rebuild NixOS with `kernelPackages = linuxPackages_6_4;` and switch (an Ethernet adapter is necessary!)
4. Wifi is now working

### Expected behavior
Wifi works on latest kernel.

### Additional context
I can provide dmesg dumps after work from the failing kernel version if these are deemed helpful.

### Notify maintainers

@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.15, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Infinidoge** [comment]
Can also reproduce (was very confused when I rebuilt after fixing a corruption issue to find WiFi suddenly gone.)

**Comment by Infinidoge** [comment]
Did some further testing, and this doesn't seem to be specifically a kernel issue, and instead the version of some other software. Tested and found WiFi to be working in kernel 6.5.8, and after pinning the kernel to 6.4.15, rebooted and found WiFi no longer working

**Comment by alyssais** [comment]
It can't find its firmware.  Do you have `hardware.enableRedistributableFirmware` enabled?

**Comment by Infinidoge** [comment]
I will later today, I have things I need to finish before I can start dedicating time to it.

**Comment by Infinidoge** [comment]
Bisected the commit, and it turned out to be quite straightforward.
https://github.com/NixOS/nixpkgs/commit/c4c5e2a4d3a7b382a058a5d67e650e1bcea1421f is the bad commit.

Conveniently though, https://github.com/NixOS/nixpkgs/commit/21cb9b713093e2ed4973997e79a229bc0d30d64f fixed the problem!

**Comment by alyssais** [comment]
Great! So we can close this?

**Comment by Infinidoge** [comment]
For anyone who wants to just pull the latest `linux-firmware`, here is an overlay for it: 
```nix
final: prev: {
  # https://nixpk.gs/pr-tracker.html?pr=264420
  linux-firmware = prev.linux-firmware.overrideAttrs {
    version = "20231030";
    src = final.fetchzip {
      url = "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20231030.tar.gz";
      hash = "sha256-ocqikHJfvs4gWqnBeLgSnXHzUTPi8l8cSfNarhD8G3w=";
    };
    outputHash = "sha256-vaMYuAqkkuyY+bAxAe0uAokWZ7HlaR62UTu4L8yOofs=";
  };
}
```

But yeah, I think this can be closed, unless we want to wait until it hits `nixos-unstable`/`nixpkgs-unstable`, which is probably unnecessary.

**Comment by Infinidoge** [comment]
The update is now on unstable channels, so closing now.
