### ISSUE TITLE
Build failure: frozen-bubble

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#255381]
### Steps To Reproduce

1. build *frozen-bubble*

### Build log

<https://gist.github.com/Jayman2000/392f9c071b5b708c044e52b4619ee99b>

### Additional context

frozen-bubble works fine on NixOS 23.05. It’s just NixOS Unstable that’s affected.

### Notify maintainers

@puckipedia

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.11 (Tapir), 23.11pre525725.f2ea252d23eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by puckipedia** [comment]
Looks like caused by Perl; probably requires a cherrypick of https://github.com/PerlGameDev/SDL/pull/304
