### ISSUE TITLE
Firefox sync module broken (fails to build)

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#25530]
## Issue description
```
stripping (with flags -S) in /nix/store/zy76r0fblp0p0agzs9bsiqbisj8p350j-python2.7-tokenserver-1.2.11/lib
patching script interpreter paths in /nix/store/zy76r0fblp0p0agzs9bsiqbisj8p350j-python2.7-tokenserver-1.2.11
Found duplicated packages in closure for dependency 'requests':
  requests 2.13.0 (/nix/store/h2lxx5afm9hs736x72x2dsvazv2xccjh-python2.7-requests-2.13.0/lib/python2.7/site-packages)
  requests 1.2.3 (/nix/store/mp4wamnzacdb1142bv1nbwvv8ig7j7wm-python2.7-requests-1.2.3/lib/python2.7/site-packages)

Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
builder for ‘/nix/store/a6vnwbqf10vngy7kw6vn2pqb0qmq0dn4-python2.7-tokenserver-1.2.11.drv’ failed with exit code 1
```

### Steps to reproduce

Set `services.firefox.syncserver.enable = true;` and rebuild

## Technical details
- System: 17.03.1091.dc7dc77cde (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1091.dc7dc77cde"

**Comment by lheckemann** [comment]
This seems to be because sphinx depends on `requests2` while everything else wants `requests`.

**Comment by FRidh** [comment]
we need to see whether we can get of `requests`

**Comment by lheckemann** [comment]
I tried just removing requests and replacing all references to it with requests2. This allowed the sync server to build, but it still doesn't start. In addition, it seems to be very out of date, and the current service runs on Node and not python. I'm guessing the appropriate course of action would be simply to remove the packages completely?

**Comment by FRidh** [comment]
I think I recall this has been brought up before and that indeed the conclusion was that we had to replace the package.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/25506 needs a bit more work but that would detect such issues already during evaluation.

**Comment by FRidh** [comment]
At e33848568d3321c4f042d8352168a8cf006646e6 it fails with
```
$ nix-build -A python.pkgs.syncserver
error: Package ‘python2.7-umemcache-1.6.3’ in ‘/home/freddy/Data/Data/Code/libraries/nixpkgs/pkgs/top-level/python-packages.nix:25731’ is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```
@nbp @lsix you last touched syncserver. Are you maintaining it or can we drop it?

**Comment by lheckemann** [comment]
I presume that, seeing as it's been superseded by the node-based thing, dropping it would be the appropriate action to take.

**Comment by Infinisil** [comment]
@lheckemann What node-based thing are you talking about? The [official repo for the syncserver 1.5](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html) is still getting commits every now and then.

Btw the Dockerfile included in the repo does work, for the ones who really want to run the syncserver right now. Quick how to:

- Install Docker (`virtualisation.docker.enable = true` in configuration.nix)
- `git clone https://github.com/mozilla-services/syncserver && cd syncserver`
- `docker build -t syncserver .`
- `docker run -p 127.0.0.1:5000:32768 syncserver`

Should work like this, using docker for that is a bit pathetic though heh

**Comment by nbp** [comment]
@FRidh 
> you last touched syncserver. Are you maintaining it or can we drop it?

I stopped maintaining it as I noticed that I needed to package the "firefox account" as well in order to have a truly self-hosted service.

Thus I am totally fine if we drop it, as I am not going to package "firefox account" services anytime soon.

Having an expression which depends on an external service to access a service which is self-hosted sounds entirely pointless from my point of view.

**Comment by lheckemann** [comment]
Right, I misunderstood. It's only the Accounts server that's based on node. Since I'm interested in self-hosting this stuff, I've been looking into it and can take over maintainership if I get it working, so I don't think it should be dropped yet.

**Comment by Nadrieril** [comment]
Same here, I care about this and would be happy to help maintaining it

**Comment by Nadrieril** [comment]
I have a few PRs waiting (https://github.com/NixOS/nixpkgs/pull/28186, https://github.com/NixOS/nixpkgs/pull/28187, https://github.com/NixOS/nixpkgs/pull/28188) that will fix the module once merged.
I have been running the service for a week now and it seems to work well.

**Comment by lheckemann** [comment]
Great, glad to hear it! Sorry I never got around to it, I'll take a look at your PRs though :)

**Comment by Nadrieril** [comment]
I now consider this fixed. Thanks @FRidh for your help and super merging speed :)

**Comment by lheckemann** [comment]
Thanks @Nadrieril and @FRidh !

**Comment by mogorman** [comment]
I seem to be having a similar problem as this old one https://github.com/NixOS/nixpkgs/issues/29058
