### ISSUE TITLE
Package request: mercury-browser-bin

### ISSUE THREAD

**Issue by redxtech** [NixOS/nixpkgs#255399]
**Project description**

Mercury is a firefox fork that implements patches that focus on speed, security, and privacy.

**Highlights:**
* Compiler optimizations include AVX, AES, LTO and PGO.
* Learn more about these compiler optimizations and how they work [Here](https://thorium.rocks/optimizations).
* [Patches and UI changes](https://github.com/Alex313031/Mercury/blob/main/docs/PATCHES.md) that enhance useability, and strengthen privacy/security.
Many of these come from LibreWolf, Waterfox, PlasmaFox, and GNU IceCat

**Metadata**

* homepage URL: https://thorium.rocks/mercury
* source URL: https://github.com/Alex313031/Mercury
* license: MPL-2.0
* platforms: unix, linux, (unsure if it will build on darwin, they don't release prebuilt binaries for it and I can't test it)

**Comment by ProminentRetail** [comment]
I wanted to try Mercury out of curiosity and built this:

<details>

<summary>package.nix</summary>

```nix
{ lib
, stdenv
, fetchurl
, autoPatchelfHook
, dpkg
, wrapGAppsHook
, alsa-lib
, browserpass
, bukubrow
, cairo
, cups
, dbus
, dbus-glib
, ffmpeg
, fontconfig
, freetype
, fx-cast-bridge
, glib
, glibc
, gnome-browser-connector
, gtk3
, harfbuzz
, libcanberra
, libdbusmenu
, libdbusmenu-gtk3
, libglvnd
, libjack2
, libkrb5
, libnotify
, libpulseaudio
, libva
, lyx
, mesa
, nspr
, nss
, opensc
, pango
, pciutils
, pipewire
, plasma5Packages
, sndio
, speechd
, tridactyl-native
, udev
, uget-integrator
, vulkan-loader
, xdg-utils
, xorg
}:

stdenv.mkDerivation rec {
  pname = "mercury-browser";
  version = "115.4.0";

  src = fetchurl {
    url = "https://github.com/Alex313031/Mercury/releases/download/v.${version}/mercury-browser_${version}_amd64.deb";
    hash = "sha256-78b2QEgf312TDBIy4lXzYUBtTfdNui3VJBbyDfXqOtc=";
  };

  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
    wrapGAppsHook
  ];

  buildInputs = [
    stdenv.cc.cc.lib
    alsa-lib
    browserpass
    bukubrow
    cairo
    cups
    dbus
    dbus-glib
    ffmpeg
    fontconfig
    freetype
    fx-cast-bridge
    glib
    glibc
    gnome-browser-connector
    gtk3
    harfbuzz
    libcanberra
    libdbusmenu
    libdbusmenu-gtk3
    libglvnd
    libjack2
    libkrb5
    libnotify
    libpulseaudio
    libva
    lyx
    mesa
    nspr
    nss
    opensc
    pango
    pciutils
    pipewire
    plasma5Packages.plasma-browser-integration
    sndio
    speechd
    tridactyl-native
    udev
    uget-integrator
    vulkan-loader
    xdg-utils
    xorg.libxcb
    xorg.libX11
    xorg.libXcursor
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXi
    xorg.libXrandr
    xorg.libXrender
    xorg.libXtst
    xorg.libXxf86vm
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out
    cp -r usr/* $out

    substituteInPlace $out/share/applications/mercury-browser.desktop \
      --replace Exec=mercury-browser Exec=$out/bin/mercury-browser \
      --replace StartupWMClass=mercury StartupWMClass=mercury-default \
      --replace Icon=mercury Icon=$out/share/icons/hicolor/512x512/apps/mercury.png
    addAutoPatchelfSearchPath $out/lib/mercury
    substituteInPlace $out/bin/mercury-browser \
      --replace 'export LD_LIBRARY_PATH' "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:${ lib.makeLibraryPath buildInputs }:$out/lib/mercury" \
      --replace /usr $out

    runHook postInstall
  '';

  meta = with lib; {
    description = "Compiler-optimized private Firefox fork";
    homepage = "https://thorium.rocks/mercury";
    sourceProvenance = with sourceTypes; [ binaryNativeCode ];
    license = licenses.unfree;
    platforms = [ "x86_64-linux" ];
    mainProgram = "mercury-browser";
  };
}
```

</details>

But I decided I wasn't going to use it, so I'll leave this here in case it's helpful to anyone. It seems to work just fine, but I haven't tested it very much.

**Comment by redxtech** [comment]
I'll give it a try, and if it works well, I could submit a PR adding this to `nixpkgs`.

**Comment by AlecsFerra** [comment]
Any news related to this?

**Comment by redxtech** [comment]
> Any news related to this?

It's been working fine for me all week, I'll make a PR after I'm off work

**Comment by phrogg** [comment]
> > Any news related to this?
> 
> It's been working fine for me all week, I'll make a PR after I'm off work

Hey, sounds great any progress?

**Comment by redxtech** [comment]
> > > Any news related to this?
> > 
> > 
> > It's been working fine for me all week, I'll make a PR after I'm off work
> 
> Hey, sounds great any progress?

Whoops, I kinda forgot about this. I have stopped using mercury in favour of just using firefox devedition, but I can change the package name and make a PR, but I'd rather not be the sole maintainer for it.

**Comment by formula-spectre** [comment]
any update on this?

**Comment by redxtech** [comment]
> any update on this?

There's a PR but it's segfaulting so it's currently blocked by that

**Comment by formula-spectre** [comment]
> > any update on this?
> 
> There's a PR but it's segfaulting so it's currently blocked by that  

ah I see

**Comment by mweinelt** [comment]
https://github.com/Alex313031/Mercury/tags

Looks like it is dead, but also insufficient security posture with skipped releases like on Thorium Browser or in this case quite a number of versions behind upstream..
