### ISSUE TITLE
services.nginx: Support both HTTP and HTTPS in a single virtualHost

### ISSUE THREAD

**Issue by edanaher** [NixOS/nixpkgs#25533]
The nginx module currently only has a single listenString in each record, which means that if you enableSSL, you disable HTTP.  So if you want both, you have to have two nearly-identical records (not the end of the world, but ugly.)

I think that for most uses, forceSSL is the better option, but there are some cases (e.g., my single-page site willcaltrainsucktoday.com) where it seems silly to add another round trip by forcing a redirect to HTTPS.

This also applies to apache-httpd, and presumably any other web servers in NixOS.

I also found it extremely confusing that enableSSL *disables* non-SSL; that option seems misnamed and poorly documented: "Whether to enable SSL (https) support." does not imply to me that it disables http.

(Incidentally, I'd also like to see multiple hostnames in a single vhost; e.g., willcaltrainsucktoday.com and www.willcaltrainsucktoday.com.  But that's less annoying to me, and a more complicated question, especially when SSL gets involved, so I'll defer that for later.)

**Comment by fadenb** [comment]
enableSSL confusion same as in https://github.com/NixOS/nixpkgs/issues/23711

**Comment by danbst** [comment]
Luckily for nginx it's an easy fix:
```
 enableSSL = true;
 extraConfig = ''
   listen 80;
 '';
```
I was bitten by this too.

----
As for additional hostnames, there exist https://nixos.org/nixos/options.html#serveraliases

**Comment by edanaher** [comment]
@danbst - Thanks for the workaround and pointer to serveraliases!  I forgot that extraConfig existed, and just didn't see serveraliases among the multitude of options nginx supports ;)

Honestly, given the amount of effort to refactor the config in a way that is backwards compatible or sufficiently better to justify breakage, I'd be happy keeping things as they are and just updating the documentation with the fact that enableSSL disables HTTP, as well as the extraConfig workaround to re-enable it.

Incidentally, while looking for related issues I found #22067; maybe if that ends up going somewhere the server-agnostic combined config could handle this issue better.  But lacking a larger change like that, I'm certainly not motivated enough to figure out a clean way to handle this.

**Comment by globin** [comment]
See https://github.com/NixOS/nixpkgs/pull/25604#issuecomment-299822827 for my opinion

**Comment by wmertens** [comment]
fixed with #27426
