### ISSUE TITLE
vscode: [packaging improvement]: lift `version`, `src`,`rev` one level higher to make it more convenient to override

### ISSUE THREAD

**Issue by ppenguin** [NixOS/nixpkgs#255456]
## Issue description

Since for me `vscode` on `wayland` is quite unstable as-is (frequent crashes), but for some versions (like `1.82` now) it _always_ crashes on start, I wanted to use an overlay a bit like so:

```nix
    (final: prev: {
      vscode =
        let
          plat = {
            x86_64-linux = "linux-x64";
            x86_64-darwin = "darwin";
            aarch64-linux = "linux-arm64";
            aarch64-darwin = "darwin-arm64";
            armv7l-linux = "linux-armhf";
          }.${prev.system};
        in prev.vscode.overrideAttrs (_: {
          version = "1.81.1";
          src = prev.fetchurl {
            name = "VSCode_${version}_${plat}.tar.gz";
            url = "https://update.code.visualstudio.com/${version}/${plat}/stable";
            # sha256 = "0g49765pnimh107pw3q7dlgd6jcmr5gagsvxrdx8i93mbxb0xm0c";
            sha256 = prev.lib.fakeSha256;
          };
        });
    })
   ...
```

but this doesn't work because the significant variables (like `version`) to be overridden do not appear in `vscode.nix` but as an argument to `callPackage` therein. It should be possible to lift these one level higher and the do `callPackage { ... version = version; ...}` etc.?

Possibly having a simple function for the platform would be good so this boilerplate can be done away with as well?

**Comment by ppenguin** [comment]
Oops, it was just my mistace: a `rec` in `prev.vscode.overrideAttrs (_:  rec { ...` makes this actually work.

Sorry for the noise...

**Comment by heinwol** [comment]
Thanks for the overlay snippet by the way ^^. It really helped me to rollback a crashing version!
