### ISSUE TITLE
[Albert help request]: open file with nautilus instead of chrome

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#25556]
## Issue description
Albert is opening files in `chrome` instead of nautilus

### Steps to reproduce
(using a tiling manager such as xmonad, not a complete gnome environment)
- Install albert
- Install nautilus
- Install google-chrome
- Open Albert (`ctrl-space` and type a name of a folder or file)

## Technical details

* System: 17.03.1098.a162c6c828 (Gorilla)
* Nix version: 1.11.8

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: false

**Comment by PierreR** [comment]
@ericsagnes @romildo This is probably related to a nixos settings somehow and not an Albert issue per se. I do have installed `shared_mime_info` and `xdg_utils`.

**Comment by pbogdan** [comment]
Does:

```
$ xdg-mime default nautilus.desktop inode/directory
```

help with the folders issue? If needed you can revert this by removing the entry from .`~/.local/share/applications/mimeapps.list` and / or `~/.config/mimeapps.list`

**Comment by PierreR** [comment]
@pbogdan Thanks for your quick answer.

> xdg-mime default nautilus.desktop inode/directory

Nope. I have actually tried this before but with no luck.

**Comment by pbogdan** [comment]
Sorry, that should have been:

```
$ xdg-mime default org.gnome.Nautilus.desktop inode/directory 
```

Does this make any difference at all? Seems to work on my xmonad set up but otherwise I'm unsure what could be the issue :-(.

**Comment by PierreR** [comment]
> Does this make any difference at all?

Nope. I will try with another file manager just to be sure it is not a nautilus issue.

**Comment by 7c6f434c** [comment]
I would run `strace` and look at all `execve` calls and also `open` outside of `/nix/`

**Comment by ericsagnes** [comment]
AFAIK, Albert should use xdg defaults, what is the output of the following command:

```
$ xdg-mime query default inode/directory
```

**Comment by PierreR** [comment]
@ericsagnes sorry for the late reply.

```
→ xdg-mime query default inode/directory
org.gnome.Nautilus.desktop
```
Still any files or directories would be opened by `Chrome` in `Albert`

**Comment by PierreR** [comment]
As a note I can see that chrome is automatically adding a file in ` .local/share/applications/` while `nautilus` does not. 

```
cat .local/share/applications/chrome-aohghmighlieiainnegkcijnfilokake-Default.desktop 
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Docs
Exec=/nix/store/3i18r5xq1jnvjr2rvwm2rnwqjgkmal80-google-chrome-63.0.3239.108/share/google/chrome/google-chrome --profile-directory=Default --app-id=aohghmighlieiainnegkcijnfilokake
Icon=chrome-aohghmighlieiainnegkcijnfilokake-Default
NoDisplay=true
StartupWMClass=crx_aohghmighlieiainnegkcijnfilokake
```

ime query default inode/directory
org.gnome.Nautilus.desktop

**Comment by PierreR** [comment]
Here is the output of an strace:

http://nixpaste.lbr.uno/CMbK8vJV?sh

**Comment by PierreR** [comment]
Found a solution ! Apparently I need to:
`XDG_CURRENT_DESKTOP='X-Generic' xdg-open ~`

**Comment by PierreR** [comment]
Well now the icons won't show up anymore in Albert ...

**Comment by PierreR** [comment]
`xdg-open` is using `xdg-mime` to get the filetype associated to a file or directory. They might be something missing in nixos concerning `xdg-mime`:

```
λ ~ → xdg-mime query filetype /home/vagrant

λ ~ → xdg-mime query filetype /home/vagrant/.zshrc 

λ ~ → XDG_CURRENT_DESKTOP='X-Generic' xdg-mime query filetype /home/vagrant
inode/directory

λ ~ → XDG_CURRENT_DESKTOP='X-Generic' xdg-mime query filetype /home/vagrant/.zshrc 
text/plain
```

**Comment by PierreR** [comment]
Ok tracking this down to the `xdg-mime` script I have figured out that installing `gvfs ` would solve the issue. How imature is the state of some linux utils ...
