### ISSUE TITLE
NixOPS deploy to Citrix XenServer

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#25553]
Just another question.

Can anyone point me to details on integrating NixOS with XenServer?  
I'm thinking NixOS may be better than Debian in terms of Virtualizing simple servers running apache.

**Comment by davidak** [comment]
I would look how the other implementations of NixOPS work and see if i can use the Xen API (or xapi).
Ist that any helpful?

**Comment by ob7** [comment]
Yes sir, thank you very much.
