### ISSUE TITLE
Update request: jq 1.6 → 1.7

### ISSUE THREAD

**Issue by leiserfg** [NixOS/nixpkgs#255527]
- Package name: jq
- Latest released version: 1.7

- Current version on the unstable channel: 1.6
- Current version on the stable/release channel: 1.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@raskin @globin @artturin 

I tried to do the bump myself, but Nix complained about a circular dependency between outputs.
the new sha is `sha256-QCoNaXXZRub05ITRqEMgQUoP+Ots9J0sEdFE1NNE22I=`, and the patch is not needed anymore.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/246515
