### ISSUE TITLE
kdevelop! built-in console commands don't work

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#25559]
## Issue description

KDevelop has a feature where you can use KDevelop-specific commands in the built-in konsole, ending in `!`, which interact with the rest of the KDevelop GUI, such as `create! file.txt` to create the file in the current directory and open it in a tab. They don't work.

### Steps to reproduce

1. Put `kdevelop` and `kdevplatform` in `systemPackages`
2. Start `kdevelop`
3. Open the Konsole panel
4. Type `create! foo.txt`

Expected result: foo.txt is created and opened in a tab

Actual result: `create!: command not found`

Also, the terminal prompt should have an `!` prepended to indicate that the extension is active, and it does not.

## Technical details

* System: `17.03.1082.4aab5c5798 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `"17.03.1082.4aab5c5798"`
* Sandboxing enabled: `build-use-sandbox = false`

(KDevelop and KDevPlatform both 5.0.3.)

## Suspected problem

I can't modify `/nix/store` directly to verify it, but I suspect the cause of the problem is that the `'/nix/store/5vd8qc0g26m8hrx6wb9mzj4nnjd4y00c-kdevelop-5.0.3/bin/kdevelop!'` wrapper script invokes the actual `'/nix/store/5vd8qc0g26m8hrx6wb9mzj4nnjd4y00c-kdevelop-5.0.3/bin/.kdevelop!-wrapped'` script using `exec -a "$0"` to give it the same value for `$0` as the wrapper, and the wrapped script in fact depends on `$0` via `export KDEV_BASEDIR=$(dirname $0)`, which it uses to run `bash --init-file $KDEV_BASEDIR/kdevplatform_shell_environment.sh -i`.

But based on my experiments, `exec -a` only "works" for binaries, not for scripts. For binaries `argv[0]` contains either the command as it was written in the terminal (so no full path unless you happened to have written one), or the value passed by `exec -a`. For scripts, `$0` always seems to contain the actual full path of the script file no matter what. (Which the script in question also seems to be depending on, in fact -- the command automatically executed by KDevelop when you open the konsole is e.g. `kdevelop! -s "{1579ce41-d419-4776-8509-e124a4eead87}"`, i.e. *not* using the full path.)

(And all this wouldn't be an issue if `.kdevelop!-wrapped` happened to be in the same directory in `/nix/store` as `kdevplatform_shell_environment.sh`, but one of them is from `kdevplatform` and the other is from `kdevelop` so they aren't.)

```bash
$ cat '/nix/store/5vd8qc0g26m8hrx6wb9mzj4nnjd4y00c-kdevelop-5.0.3/bin/kdevelop!'
#! /nix/store/fi3mbd2ml4pbgzyasrlnp0wyy6qi48fh-bash-4.4-p5/bin/bash -e
export PATH=/nix/store/4bprwpb073arhf19wfwgd4ilm7m0rmza-qttools-5.6.2/bin${PATH:+:}$PATH
exec -a "$0" "/nix/store/5vd8qc0g26m8hrx6wb9mzj4nnjd4y00c-kdevelop-5.0.3/bin/.kdevelop!-wrapped"  "${extraFlagsArray[@]}" "$@"
```

```bash
$ cat '/nix/store/5vd8qc0g26m8hrx6wb9mzj4nnjd4y00c-kdevelop-5.0.3/bin/.kdevelop!-wrapped'
#!/nix/store/fi3mbd2ml4pbgzyasrlnp0wyy6qi48fh-bash-4.4-p5/bin/sh

# This file is part of KDevelop
# Copyright 2011 David Nolden <david.nolden.kdevelop@art-master.de>
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
# 
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

export KDEV_BASEDIR=$(dirname $0)
export APPLICATION=KDevelop

if ! [ "$KDEV_ATTACHED_PID" ]; then
    ARGS=""
    if [ $# -eq 0 ]; then
        ARGS="-pss"
    else
        ARGS="$@"
    fi
    export KDEV_ATTACHED_PID=$($KDEV_BASEDIR/kdevelop $ARGS --pid)
fi

if ! [ "$KDEV_ATTACHED_PID" ]; then
    echo "Error: Failed retrieving a pid."
    exit 5
fi

# Make sure we didn't capture garbage instead of the pid (must be 1 word only)
# note: keep compatible on FreeBSD: https://bugs.kde.org/show_bug.cgi?id=311186
if [ "$(echo $KDEV_ATTACHED_PID | wc -w | sed 's/ //g')" != 1 ]; then
    echo "Error: Got no valid pid."
    exit 6
fi

if ! [ "$(which qdbus)" ]; then
    echo "Error: The qdbus utility is missing."
    exit 7
fi

export KDEV_DBUS_ID="org.kdevelop.kdevelop-$KDEV_ATTACHED_PID"

bash --init-file $KDEV_BASEDIR/kdevplatform_shell_environment.sh -i
```

**Comment by glaebhoerl** [comment]
(Oh, just as another data point, it used to work before upgrading to 17.03 (so this is a regression) -- based on grub.cfg the previous version was `16.09.841.cadc55f`.)

**Comment by ttuegel** [comment]
CC: @ambrop72

**Comment by ambrop72** [comment]
Hi @glaebhoerl, thanks for reporting this, I don't myself use the kdevelop shell. I am currently testing out a patch that fixes up the kdevelop! script (hardcodes KDEV_BASEDIR to ${kdevplatform}/bin and also hardcodes $KDEV_BASEDIR/kdevelop to $out/bin since the former would break it). I will probably make a pull request that updates to 5.0.4 as well.

**Comment by glaebhoerl** [comment]
@ambrop72 Thanks a lot! :-) I can confirm that the fix works.
