### ISSUE TITLE
hdajackretask (from alsaTools) segfaults

### ISSUE THREAD

**Issue by timor** [NixOS/nixpkgs#25558]
## Issue description
Trying to re-assign the sound card jack connection functions, I encountered this.
The hdajackretask tool from the alsaUtils package segfaults.

It has also been mentioned here: #13213

### Steps to reproduce
running
`nix-shell -p alsaTools --run hdajackretask`
gives:

```
/tmp/nix-shell.exZPFD/rc: line 1: 17086 Segmentation fault      hdajackretask
```

## Technical details

* System: 17.03.1098.a162c6c828 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1098.a162c6c828
* Sandboxing enabled: true

**Comment by timor** [comment]
strace suggests that the problem could be missing user_pin_config files in the `/sys/class/sound/hw*/` folder.

I tried bumping alsaTools to 1.1.3, but the problem persists.

**Comment by timor** [comment]
Turns out recompiling the kernel with CONFIG_SND_HDA_RECONFIG set creates the missing files.
hdajackretask does not work like intended though, since it uses shell scripting and wants to perform operations that don't make sense on NixOS.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by timor** [comment]
The issue with the segmentation fault should have been fixed a long time ago by #26123.

What specific problems are you experiencing?

**Comment by mmahut** [comment]
None, just doing triage, thank you.

**Comment by timor** [comment]
I haven't checked lately, but the binaries that come with the package are probably still broken.
