### ISSUE TITLE
protonmail-bridge GUI missing

### ISSUE THREAD

**Issue by neunenak** [NixOS/nixpkgs#255523]
### Describe the bug

When I try to run `protonmail-bridge`, I get console error output similar to what is described in https://github.com/NixOS/nixpkgs/issues/241787, i.e. a cli help message and then some error messages, at which point the program quits:

```
❯ nix run nixpkgs#protonmail-bridge
WARN[0002] Failed to get test credentials from keychain  error="exit status 2: gpg: decryption failed: No secret key\n" helper="*pass.Pass"
INFO[0002] Migrating keychain helper                    
WARN[Sep 16 12:26:43.543] The vault is corrupt and has been wiped   
USAGE:
   ProtonMailBridge [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --cpu-prof, -p               Generate CPU profile (default: false)
   --mem-prof, -m               Generate memory profile (default: false)
   --log-level value, -l value  Set the log level (one of panic, fatal, error, warn, info, debug)
   --grpc, -g                   Start the gRPC service (default: false)
   --cli, -c                    Start the command line interface (default: false)
   --noninteractive, -n         Start the app in non-interactive mode (default: false)
   --log-imap value             Enable logging of IMAP communications (all|client|server) (may contain decrypted data!)
   --log-smtp                   Enable logging of SMTP communications (may contain decrypted data!) (default: false)
   --help, -h                   show help
ERRO[Sep 16 12:26:43.544] Get "https://proton.me/download/bridge/version_linux.json": context canceled, Attempt 1 
FATA[Sep 16 12:26:43.544] no frontend specified, use --cli, --grpc or --noninteractive 
```

### Steps To Reproduce
1. run `nix run nixpkgs#protonmail-bridge`

### Expected behavior

I was expecting the behavior I see when I use a non-nixpkgs version of the protonmail-bridge application, namely that a GUI window pop ups inviting me to log in with my protonmail account.

### Notify maintainers

@MrFreezeex 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.12-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager"`
 - channels(greg): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/greg/.nix-defexpr/channels/nixpkgs`

```

**Comment by MrFreezeex** [comment]
Hi @neunenak, yes unfortunately there is no support for the gui in nixpkgs atm

**Comment by neunenak** [comment]
> Hi @neunenak, yes unfortunately there is no support for the gui in nixpkgs atm

Hm, this is surprising - is there any reason it's difficult to provide GUI support in nixpkgs? Is this a deliberate decision?

**Comment by MrFreezeex** [comment]
Well the main reason for me is that I don't use the gui. But there's two different programs to launch the GUI with two different build system as well...

**Comment by adingbatponder** [comment]
Problem is the GUI is needed to show the password to enter into e.g. Thunderbird to set up proton mail via the bridge.... so this seems to prevent use of proton mail in nixos . I set this up in Ubuntu no probs.

**Comment by MrFreezeex** [comment]
> Problem is the GUI is needed to show the password to enter into e.g. Thunderbird to set up proton mail via the bridge.... so this seems to prevent use of proton mail in nixos . I set this up in Ubuntu no probs.

You can do that with the info command in the cli

**Comment by adingbatponder** [comment]
Thanks. Sorry to be so dim, nix newbie....  but I do not have any such command available with what I have in my config file and the command line output nor in -cli "mode".

1) my config file bit about proton bridge:

 # 28-10-2023 suggested by @phileas@infosec.exchange responding to issue with proton bridge
  # services.gnome.gnome-keyring.enable = true;
  # 28-10-23 from https://www.reddit.com/r/NixOS/comments/vpbqs7/issues_with_getting_protonmailbridge_openrazer/ 
  services.gnome.gnome-keyring.enable = true;
  systemd.user.services.protonmail-bridge = {          
  description = "Protonmail Bridge";          
  enable = true;          
  script = "${pkgs.protonmail-bridge}/bin/protonmail-bridge --noninteractive --log-level info";          
  path = [ pkgs.gnome3.gnome-keyring ]; # HACK: https://github.com/ProtonMail/proton-bridge/issues/176          
  wantedBy = [ "graphical-session.target" ];          
  partOf = [ "graphical-session.target" ];        };


___________________________________________________
2) my command line gives me this:

[---@thinky1:~]$ protonmail-bridge -i
Incorrect Usage: flag provided but not defined: -i

NAME:
   ProtonMailBridge - Proton Mail IMAP and SMTP Bridge

USAGE:
   ProtonMailBridge [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --cpu-prof, -p               Generate CPU profile (default: false)
   --mem-prof, -m               Generate memory profile (default: false)
   --log-level value, -l value  Set the log level (one of panic, fatal, error, warn, info, debug)
   --grpc, -g                   Start the gRPC service (default: false)
   --cli, -c                    Start the command line interface (default: false)
   --noninteractive, -n         Start the app in non-interactive mode (default: false)
   --log-imap value             Enable logging of IMAP communications (all|client|server) (may contain decrypted data!)
   --log-smtp                   Enable logging of SMTP communications (may contain decrypted data!) (default: false)
   --help, -h                   show help
FATA[0000] flag provided but not defined: -i            

[----@thinky1:~]$ protonmail-bridge info
INFO[0000] Migrating keychain helper                    
WARN[Oct 29 09:43:30.167] Failed to create lock file; another instance is running 

[-----@thinky1:~]$ protonmail-bridge -c
INFO[0000] Migrating keychain helper                    
WARN[Oct 29 09:44:05.339] Failed to create lock file; another instance is running

**Comment by adingbatponder** [comment]
I pasted from config into this github field and the formatting went crazy... of course markup ... sorry... new to this.. but fat stuff in after the hash..... i.e. comments.. sorry

**Comment by MrFreezeex** [comment]
When you launch in `--cli` mode you need to `login` and then get the info you need for thunderbird with `info`.

> WARN[Oct 29 09:44:05.339] Failed to create lock file; another instance is running

If you don't see the CLI (it prints a little bridge in ASCI and wait for input( that's probably because of that try to kill the running bridge or remove manually the lockfile (I don't know where it is though).
