### ISSUE TITLE
gamescope w/ steam (and steam-gamescope) don't work

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#255787]
### Describe the bug

`steam` fails to launch properly when run under gamescope.

it works fine running naively under sway.

not sure if this is upstream issue or not, I have filed it upstream: https://github.com/ValveSoftware/gamescope/issues/951

I'm testing on `nixos-unstable` with the `3.12.5` merged locally: https://github.com/NixOS/nixpkgs/pull/255293

cc: @nrdxp

**Comment by PedroHLC** [comment]
Did you try with and without `programs.gamescope.capSysNice`?

**Comment by colemickens** [comment]
Yes, I did think to try that (I'm desperate to test HDR while I have access to an HDR display for a couple weeks). Still no luck. I even (trivially) managed to launch Sway under `gamescope` and then starting Steam... same result.

I even tried undo-ing some quirky things (like having steam's homedir pollution moved to a separate zfs dataset, not sure if that would affect any sort of FHS-y stuff?) but that didn't help either.

It's rather odd - the only hits for the error message I (maybe) identified point to a missing font, which, as evidenced by Steam running bare under Sway, shouldn't be an issue.

**Comment by colemickens** [comment]
Hi @PedroHLC, following up from our Matrix chat, I've not had any success yet.

I've tried:
- removing the color management flag
- removing the HDR flag
- booting with a "regular" (aka non-HDR-patched) kernel
- adding `--prefer-vk-device "1002:73ef"`

context:
```
❯ lspci -nnvvv | grep 6700S
pcilib: Error reading /sys/bus/pci/devices/0000:00:08.3/label: Operation not permitted
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
```

and it's still giving the same result.

Something else I noticed: when I start `gamescope ...` the screen goes black (looks like the laptop is off, really) and it stays that way until I press any key on the keyboard and then it seems to immediately finishing crashing and returns to the TTY.

**Comment by colemickens** [comment]
I don't get it. I removed `~/.steam` and `~/.local/share/Steam` and re-setup Steam. Now it works fine under gamescope. (HDR is probably even working, from what I can see). ref: https://github.com/ValveSoftware/gamescope/issues/951#issuecomment-1732557921
