### ISSUE TITLE
Package request: backlight-auto

### ISSUE THREAD

**Issue by 2gn** [NixOS/nixpkgs#255798]
**Project description**

The missing backlight auto adjusting program for Linux.

**Metadata**

* homepage URL: https://len.falken.directory/backlight-auto.html
* source URL: https://len.falken.directory/backlight-auto.html (zip file)
* license: unknown
* platforms: linux
* virustotal: https://www.virustotal.com/gui/file/bec345eba2bb1db1ac9ae183da52c73d8ab7355df92287b1e5b4ccfa6218c04b?nocache=1

**Comment by lf-** [comment]
I feel like shaving a yak. I'll take this.

**Comment by lf-** [comment]
Actually.... among other things the source here is a pain and basically impossible to make reproducible. Pretty annoying so I shall email the author.

**Comment by lf-** [comment]
```nix
{ lib, stdenv, zig, libyuv, runCommand, unzip }:
stdenv.mkDerivation {
  pname = "backlight-auto";
  version = "0.0.1";

  src = runCommand "source" { } ''
    ${unzip}/bin/unzip -d $out ${./backlight-auto.zip}
  '';

  nativeBuildInputs = [
    zig.hook
  ];

  buildInputs = [
    libyuv
  ];
}
```

here is a package in the interim.

**Comment by 2gn** [comment]
fyi, I found the GitHub repository

https://github.com/lf94/backlight-auto

**Comment by lf-** [comment]
Oh, nice. Still needs a license though before we can include it.

**Comment by fabaff** [comment]
>  Still needs a license though before we can include it.

Not a blocker from my point of view. Package can be `unfree` till the licensing situation is clear.

**Comment by lf-** [comment]
Author is on it re both of these things, btw! I would just give him a day or two.

**Comment by 2gn** [comment]
It's now MIT licensed.

**Comment by lf-** [comment]
PR filed.
