### ISSUE TITLE
Update request: pythonPackages.debugpy

### ISSUE THREAD

**Issue by maxeonyx** [NixOS/nixpkgs#255758]
**Project description**
debugpy is an implementation of the Debug Adapter Protocol for Python.

**Metadata**

homepage URL: https://pypi.org/project/debugpy/
source URL: https://github.com/microsoft/debugpy
license: mit
platforms: unix, linux, darwin

**Update details**

Upstream has updated and has changed the supported python versions. The [issue mentioned in the code](https://github.com/microsoft/debugpy/issues/1107) has been fixed.

v 1.7.0 Adds 3.11 support https://github.com/microsoft/debugpy/releases/tag/v1.7.0'
v 1.8.0 Drops 3.7 Support https://github.com/microsoft/debugpy/releases/tag/v1.8.0

See the nix package definition here
https://github.com/NixOS/nixpkgs/blob/b6fb0591e004cb6ffa47ab4edee06da8a38f9500/pkgs/development/python-modules/debugpy/default.nix#L25-L30

**Comment by antonmosich** [comment]
This was already done in 04b53be12571675e9ddea719b420dc237c9b10f4, wasn't it?

**Comment by maxeonyx** [comment]
Seems so! Thanks @gepbird, @antonmosich

**Comment by kira-bruneau** [comment]
Completed in #255379
