### ISSUE TITLE
webcord-vencord: segfault on run

### ISSUE THREAD

**Issue by Anomalocaridid** [NixOS/nixpkgs#255729]
### Describe the bug
After recently updating NixOS, webcord-vencord regularly segfaults upon running it. Normal webcord does not appear to have the same problem.

### Steps To Reproduce
1. Install webcord-vencord
2. Run webcord-vencord in a terminal with `webcord`
3. A blank window appears for a moment and then disappears. The terminal output will say it had a segfault.

### Expected behavior
I expected it to not segfault and run normally

### Screenshots
N/A

### Additional context
I have a flake-based setup
My dotfiles: https://github.com/Anomalocaridid/dotfiles

I have tried deleting the data in `~/.config/WebCord,` and it sort of worked, but then after closing and re-opening webcord-vencord once, it resumed crashing with a segfault.

Output when I run webcord-vencord in a terminal:
```
[WebSocket] Listening at port 6463.
[1]    274720 segmentation fault (core dumped)  webcord
```

### Notify maintainers
@FlafyDev
@NotAShelf 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.3-xanmod1, NixOS, 23.11 (Tapir), 23.11.20230915.ace5093`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `not found`
```

**Comment by FliegendeWurst** [comment]
Fixed by #261143, which will be in nixos-unstable soon.
