### ISSUE TITLE
virt-manager forgets everything 

### ISSUE THREAD

**Issue by siryoussef** [NixOS/nixpkgs#255837]
### Describe the bug
virt-manager doesn't save settings or connections after closure (starts as if it is the first time each time).

### Steps To Reproduce
1. add virt-manager to the enviroment.systemPackages in your NixOS configuration file, add virtualisation.libvirtd.enable = true; & add libvirtd to the extraGroups in users.users."your user name"
2. rebuild the system configuration (typically nixos rebuild switch)
3. start virt-manager, add connections & change some settings then close it & start it again.

### Expected behavior
virt-manager starts the 2nd time with the settings that were changed & with the previously added connections from the first time.

### Additional context
I use kde-plasma as a desktop If that has any effect !

**Comment by Gerg-L** [comment]
Have the same issue, I use an ephemeral `/` so I assumed it was that.

**Comment by the-furry-hubofeverything** [comment]
I can't replicate this on 23.05, I have an entire libvirt setup for a windows vm.

Are you on unstable?

**Comment by the-furry-hubofeverything** [comment]
Do you have dconf enabled? `programs.dconf.enable = true;`

**Comment by Gerg-L** [comment]
> Do you have dconf enabled? `programs.dconf.enable = true;`
Enabling dconf did it!
CC: @siryoussef
