### ISSUE TITLE
Mounting NFS volumes stopped working

### ISSUE THREAD

**Issue by lamarios** [NixOS/nixpkgs#255803]
### Describe the bug
Mounting NFS volumes stopped working without configuration change other than updates.

### Steps To Reproduce
1. Get updated system as of 2023-09-18 from stable
2. Try to mount a nfs volume
3.  Get the error
```
sudo mount.nfs 192.168.7.2:/volume/xxx/xxx /mnt/test
Failed to start rpc-statd.service: Unit rpc-statd.service not found.
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified

```

### Expected behavior
The volume to be mounted

### Notify maintainers

@abbradar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.3, NixOS, 23.05 (Stoat), 23.05.3580.5d017a8822e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by nevivurn** [comment]
I am having the same issue, with very similar messages:

```
Sep 18 20:00:02 taiyi sudo[12581]: nevivurn : TTY=pts/0 ; PWD=/home/nevivurn ; USER=root ; COMMAND=/run/wrappers/bin/mount -t nfs4 [snip]:/data /mnt/[snip]/
Sep 18 20:00:02 taiyi sudo[12581]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Sep 18 20:00:02 taiyi kernel: SELinux: Unable to set superblock options before the security server is initialized
Sep 18 20:00:02 taiyi kernel: SELinux: Unable to set superblock options before the security server is initialized
Sep 18 20:00:02 taiyi kernel: SELinux: Unable to set superblock options before the security server is initialized
```

I am running:

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.05 (Stoat), 23.05.20230917.5d017a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(nevivurn): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

It happened between 360a7d31c30abefdc490d203f80e3221b7a24af2...5d017a8822e0907fb96f7700a319f9fe2434de02, the only suspicious changes are kernel changes.

In particular, both 6.5.2->6.5.3 and 6.1.52->6.1.53 include the patch "vfs, security: Fix automount superblock LSM init problem, preventing NFS sb sharing" which I think seems suspicious, but I don't know enough to dig any further.

Any help would be appreciated.

**Comment by someplaceguy** [comment]
Gentoo [has ran into the same problem](https://bugs.gentoo.org/914204). In that bug, someone bisected the kernel and identified the patch that @nevivurn mentioned as the culprit.

This link to a kernel patch that fixes the issue was also posted and verified to work: https://www.spinics.net/lists/linux-fsdevel/msg249428.html

**Comment by nevivurn** [comment]
I am guessing it will be fixed in upstream soonish, will it be fixed in NixOS like the gentoo folks did?

For now, I have confirmed the above patch works on my configuration: nevivurn/nixos-config@97b957e3b27f20c35fbcdf9dbd83ba13364bd1ac

**Comment by lamarios** [comment]
The patch worked for me, didn't know it was that easy to apply one

**Comment by Mic92** [comment]
cc @pogobanane

**Comment by alpacathunder1** [comment]
> I am guessing it will be fixed in upstream soonish, will it be fixed in NixOS like the gentoo folks did?
> 
> For now, I have confirmed the above patch works on my configuration: [nevivurn/nixos-config@97b957e](https://github.com/nevivurn/nixos-config/commit/97b957e3b27f20c35fbcdf9dbd83ba13364bd1ac)

This patch works great!  This issue still appears in `6.1.54`, but the patch still seems to works if applied to that version.
