### ISSUE TITLE
Package request: anyrun

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#255958]
**Project description**
 A wayland native, highly customizable runner. 

**Metadata**

* homepage URL: https://github.com/Kirottu/anyrun
* source URL: https://github.com/Kirottu/anyrun
* license: gpl3
* platforms: linux

**Comment by teto** [comment]
NB: they have a flake

**Comment by Nyabinary** [comment]
@teto You have to compile it if you add the flake and the Cachix currently doesn't work. I rather added it to nixpkgs because it way more dependent here.
