### ISSUE TITLE
Update request: ollama 0.0.17 → 0.0.19 (added GPU support)

### ISSUE THREAD

**Issue by thenbe** [NixOS/nixpkgs#255934]
- Package name: ollama
- Latest released version: 0.0.19

- Current version on the unstable channel: 0.0.17
- Current version on the stable/release channel:

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@dit7ya

-----

Note for maintainers: Please tag this issue in your PR.

### Extra info

ollama [added](https://github.com/jmorganca/ollama/issues/259) linux gpu support. To enable gpu support, there is a slight [change](https://github.com/jmorganca/ollama/pull/454#issuecomment-1721735024) to the build [process](https://github.com/jmorganca/ollama/blob/c345053a8bf47d5ef8f1fe15d385108059209fba/docs/development.md#building-on-linux-with-gpu-support).

I was able to run successfully by entering the following nix shell, then running `go generate ./... && go build .` (The difference in speed is quite stark!). However, I'm not sure how to translate this to the ollama derivation in nixpkgs. I faced some issues trying to make the `go generate ./...` command work with some of the git submodules.

```nix
devShells = {
  default = pkgs.mkShell {
    packages = with pkgs; [
      cmake
      cudaPackages_12_2.cudatoolkit
      cudaPackages_12_2.cuda_nvcc
    ];
    shellHook = ''
      export CUDA_VERSION=$(${pkgs.cudaPackages_12_2.cuda_nvcc}/bin/nvcc --version | ${pkgs.gnused}/bin/sed -n 's/^.*release \([0-9]\+\)\.\([0-9]\+\).*$/\1/p')
    '';
  };
};
```

**Comment by marcusramberg** [comment]
Guess this same request applies to 0.1.0 now :)

**Comment by thenbe** [comment]
I'm getting the following error when trying to build `v0.1.0`:

```
$ go generate ./...
-- cuBLAS found
CMake Error: File /nix/store/g921h51w23s9vi573qrxzzwwf1srax8h-cudatoolkit-12.2.0-lib/lib/libcublas.so does not exist.
CMake Error at CMakeLists.txt:278 (configure_file):
  configure_file Problem configuring file


CMake Error: File /nix/store/g921h51w23s9vi573qrxzzwwf1srax8h-cudatoolkit-12.2.0-lib/lib/libcublasLt.so does not exist.
CMake Error at CMakeLists.txt:279 (configure_file):
  configure_file Problem configuring file
```

It's looking for the files (`libcublasLt.so` and `libcublasLt.so`) in the wrong location. Here is where it should be looking for them:

```bash
ls -la "$(nix eval --raw nixpkgs#cudaPackages_12_2.cudatoolkit --impure)/lib"
```

The paths are being set from these three [lines](https://github.com/jmorganca/ollama/blob/v0.1.0/llm/llama.cpp/patches/0001-copy-cuda-runtime-libraries.patch?plain=1#L18-L20). If we change them by hand, ollama will build successfully.

```diff
-+        configure_file(${CUDAToolkit_LIBRARY_DIR}/libcudart.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcudart.so.${CUDAToolkit_VERSION_MAJOR}.0 COPYONLY)
-+        configure_file(${CUDAToolkit_LIBRARY_DIR}/libcublas.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcublas.so.${CUDAToolkit_VERSION_MAJOR} COPYONLY)
-+        configure_file(${CUDAToolkit_LIBRARY_DIR}/libcublasLt.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcublasLt.so.${CUDAToolkit_VERSION_MAJOR} COPYONLY)
++        configure_file(/nix/store/g921h51w23s9vi573qrxzzwwf1srax8h-cudatoolkit-12.2.0-lib/lib/libcudart.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcudart.so.${CUDAToolkit_VERSION_MAJOR}.0 COPYONLY)
++        configure_file(/nix/store/s5zsq62j7sdwasv2dmfl84qgdgr8fgy7-cudatoolkit-12.2.0/lib/libcublas.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcublas.so.${CUDAToolkit_VERSION_MAJOR} COPYONLY)
++        configure_file(/nix/store/s5zsq62j7sdwasv2dmfl84qgdgr8fgy7-cudatoolkit-12.2.0/lib/libcublasLt.so ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/libcublasLt.so.${CUDAToolkit_VERSION_MAJOR} COPYONLY)
```

But I'm not sure what's the proper way to point it to the correct path, or how to best translate this into the existing ollama nix derivation.

**Comment by IogaMaster** [comment]
I am attempting a solution.

I think that the best path would be to make a patch that changes CUDAToolkit_LIBRARY_DIR to two env vars.

 LIBCUDART_PATH
  LIBCUBLAS_PATH
  
  each with a proper nix store path

It's not working yet but I'll keep updating on if it works

**Comment by IogaMaster** [comment]
Something like this in pre build

` LIBCUDART_PATH="${cudaPackages_12_2.cudatoolkit.lib}" `

**Comment by karthink** [comment]
I cannot get newer versions of Ollama to build even without GPU support.  Specifically, adding the `go generate ./...` step (which is now required) as a  `preBuild` step causes the build to error with the following messages:

```sh
error: builder for '/nix/store/2wxs5jhzxaza47xlj43j4rh4pxrw2pya-ollama-0.1.5.drv' failed with exit code 1;
       last 10 log lines:
       >   golang.org/x/sys@v0.11.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >   golang.org/x/term@v0.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >  golang.org/x/text@v0.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >  google.golang.org/protobuf@v1.30.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >         gopkg.in/yaml.v3@v3.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >
       >   To ignore the vendor directory, use -mod=readonly or -mod=mod.
       >         To sync the vendor directory, run:
       >             go mod vendor
       > /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/2wxs5jhzxaza47xlj43j4rh4pxrw2pya-ollama-0.1.5.drv'.
```

When I add `go mod vendor` to `preBuild`, it errors differently:

```sh
error: builder for '/nix/store/ni91yrj7hmfj7cg9r735df36kxnrfm2x-ollama-0.1.5.drv' failed with exit code 1;
       last 10 log lines:
       >   github.com/mitchellh/colorstring: module lookup disabled by GOPROXY=off
       > go: github.com/jmorganca/ollama/server imports
       >        github.com/gin-contrib/cors: module lookup disabled by GOPROXY=off
       > go: github.com/jmorganca/ollama/server imports
       >     github.com/gin-gonic/gin: module lookup disabled by GOPROXY=off
       > go: github.com/jmorganca/ollama/server imports
       >        golang.org/x/exp/slices: module lookup disabled by GOPROXY=off
       > go: github.com/jmorganca/ollama/server imports
       >         golang.org/x/sync/errgroup: module lookup disabled by GOPROXY=off
       > /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux/setup: line 144: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/ni91yrj7hmfj7cg9r735df36kxnrfm2x-ollama-0.1.5.drv'.
```

I'm not familiar with the Go build process (I mean even without Nix) so I'm not sure what I'm doing wrong.

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/pull/257760
