### ISSUE TITLE
Moving to Go 1.21 by default in nixpkgs

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#255907]
The current default version for Go in nixpkgs is 1.20, we should attempt for the next release to switch to Go 1.21 as a default version rather than keeping 1.20 as it is already quite old, see https://endoflife.date/go.

More and more packages are adopting `buildGo121Package` as it appears that 1.21 is being required by downstream packages.

This is a tracking issue for this problem.

**Maintainers**

cc @kalbasit @Mic92 @zowoq @qbit

**Comment by juliusrickert** [comment]
> More and more packages are adopting buildGo121Package as it appears that 1.21 is being required by downstream packages.

Go 1.21 introduces the [`toolchain` directive](https://go.dev/doc/toolchain) to the `go.mod` and `go.work` files.
Go 1.20 and prior do not know about this directive. Therefore, they fail to compile.

I stumbled upon this when trying to update a Go application. I was searching for guidance on whether to patch out the `toolchain` directive or to explicitly require Go 1.21, but couldn't find any.
