### ISSUE TITLE
Update request: graphviz 8.1.0 → 9.0.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#255938]
- Package name: graphviz
- Latest released version: 9.0.0
- Current version on the unstable channel: 8.1.0
- Current version on the stable/release channel: 7.1.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bjornfor  
@7c6f434c

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by l0b0** [comment]
Completed in #256066.
