### ISSUE TITLE
Segmentation fault in update-desktop-database

### ISSUE THREAD

**Issue by adamcstephens** [NixOS/nixpkgs#255953]
### Describe the bug

Segmentation fault in `update-desktop-database` in `system-path` while processing application desktop files.

`system-path> /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 22:    31 Segmentation fault      (core dumped) /nix/store/723nhfsks9yhm1dig5pbldjivglnnj1m-desktop-file-utils-0.26/bin/update-desktop-database $out/share/applications`

### Steps To Reproduce
Build this nixosConfiguration

```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = inputs @ {...}: {
    nixosConfigurations.testutil = inputs.nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        (inputs.nixpkgs + "/nixos/modules/profiles/qemu-guest.nix")
        ({pkgs, ...}: {
          fileSystems."/" = {device = "/dev/vda1";};
          boot.loader.systemd-boot.enable = true;

          environment.systemPackages = [
            pkgs.helix # helix includes a desktop application file
          ];
          
          programs.fish.enable = true; # or use fish, which also includes one
        })
      ];
    };
  };
}
```

### Expected behavior
I expect to be able to build the system.

### Additional context
I've bisected the problem to https://github.com/NixOS/nixpkgs/pull/249924

### Notify maintainers

There are no maintainers listed for either `util-linux` or `desktop-file-utils`

**Comment by trofi** [comment]
Did you have a chance to extract the backtrace? Something like might get it for you:

```
$ sudo coredumpctl debug -r update-desktop-database
gdb > bt
```

`util-linux` does not seem to be directly involved in `SIGSEGV`. It's either a miscompilation of `update-desktop-database` or a non-deterministic crash and you might have landed on a wrong commit. Second sounds more plausible given that we did not have many reports yet.

Is `build-vm` enough to trigger the failure? What command did you use to reproduce? It did not fail for me.

```
$ nixos-rebuild build-vm --flake .#testutil
building the system configuration...
warning: Git tree '/home/slyfox/dev/bugs/nixpkgs-util-linux' is dirty

Done.  The virtual machine can be started by running /nix/store/cxfhpm6hjx2vhrn7x2mzaqq09vmc2zhh-nixos-vm/bin/run-nixos-vm
```

**Comment by delroth** [comment]
I'd also suggest `nix-store --verify --check-contents` and a `memtest86+` just to be sure :)

**Comment by adamcstephens** [comment]
I am using `nix build .#nixosConfigurations.testutil.config.system.boot.toplevel`, but `nixos-rebuild build-vm --flake .#testutil` is good enough. I've run this on a fresh system isolated from my own binary cache and am unable to reproduce it. Sorry, I'll try that first next time.

Thanks @delroth for the suggestion @delroth, I'm running those now. I'll assume this is a *me* problem.

---

```
adam@blank ~/tmp/util-repro took 5s
─❯ nix log /nix/store/v5fngxa34wzafyk7ajc50syjb4nn1mz9-system-path.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/v5fngxa34wzafyk7ajc50syjb4nn1mz9-system-path.drv^*'
created 6351 symlinks in user environment
/build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 22:    31 Segmentation fault      (core dumped) /nix/store/723nhfsks9yhm1dig5pbldjivglnnj1m-desktop-file-utils-0.26/bin/update-desktop-database $out/share/applications

adam@blank ~/tmp/util-repro
─❯ sudo journalctl -k -e --lines 2 | bat
Sep 18 16:02:49 blank kernel: update-desktop-[2367595]: segfault at 0 ip 00007ffff7ecd001 sp 00007fffffff7290 error 6 in libglib-2.0.so.0.7600.4[7ffff7e9c000+97000] likely on CPU 16 (core 4, socket 0)
Sep 18 16:02:49 blank kernel: Code: 48 89 ef e8 11 fe ff ff 48 85 db 75 ec 48 8b 7d 08 48 85 ff 74 0d e8 9e 7b ff ff 48 c7 45 08 00 00 00 00 48 83 7d 00 00 74 00 <00> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by trofi** [comment]
`$ nix build .#nixosConfigurations.testutil.config.system.build.toplevel` also works for me.

> Sep 18 16:02:49 blank kernel: update-desktop-[2367595]: segfault at 0 ip 00007ffff7ecd001 sp 00007fffffff7290 error 6 in libglib-2.0.so.0.7600.4[7ffff7e9c000+97000] likely on CPU 16 (core 4, socket 0)
> Sep 18 16:02:49 blank kernel: Code: 48 89 ef e8 11 fe ff ff 48 85 db 75 ec 48 8b 7d 08 48 85 ff 74 0d e8 9e 7b ff ff 48 c7 45 08 00 00 00 00 48 83 7d 00 00 74 00 <00> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Sequence of zeroes looks suspicious. `+97000` (or `00007ffff7ecd001`)  is probably exacly a page start. Might be truncated file on disk or corrupted page cache?

+1 for running `$ nix-store --verify --check-contents` at least for `glib` or at least rebooting and checking if it still happens.

**Comment by adamcstephens** [comment]
Thanks to both of you for quick responses and suggestions. It was/is indeed a corrupted store path.
