### ISSUE TITLE
error: The option `services.gnome3.gnome-disks' defined in `/etc/nixos/configuration.nix' does not exist.

### ISSUE THREAD

**Issue by liamwigney** [NixOS/nixpkgs#25606]
## Issue description
I'm quite new to Nix and NixOS so I might be missing something/
I have 
`services.xserver.displayManager.gdm.enable = true;`
`services.xserver.desktopManager.gnome3.enable = true;`
in my config to install gnome but I realised it doesn't come with gnome-disks.
Checking the repo I see that there is a service that you can enable that sets it up and it should be on by default. However for some reason it isn't and I can't seem to set it manually.
I'm trying `  services.gnome3.gnome-disks.enable = true;` but that's what's causing the error.

I can install via environment.systemPackages but it doesn't seem as clean and I'd like to sort it out.

### Steps to reproduce

Have a default configuration.nix with 
`services.xserver.displayManager.gdm.enable = true;`
`services.xserver.desktopManager.gnome3.enable = true;`
 `  services.gnome3.gnome-disks.enable = true;`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS
* Nix version: (run `nix-env --version`)
1.11.9
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.09pre106916.c5badb123a
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
Nope

**Comment by pbogdan** [comment]
Where do you see this service defined? A quick grep for `gnome-disks` isn't turning up anything for me.

**Comment by liamwigney** [comment]
nixos/modules/services/desktops/gnome3/gnome-disks.nix is the service.

**Comment by pbogdan** [comment]
That looks to have been added only 3 days ago whereas c5badb123a is 6 days old and doesn't include that commit (am assuming your NixOS installation is based on c5badb123a).
Seems you might be on unstable channel so you would need to wait for it to update, you can check its status at http://howoldis.herokuapp.com/

**Comment by liamwigney** [comment]
Oh god that's embarrassing that I didn't notice that. Thank you!

**Comment by liamwigney** [comment]
Works now for me.
