### ISSUE TITLE
Package request: Librum

### ISSUE THREAD

**Issue by tralph3** [NixOS/nixpkgs#256018]
**Project description**

Librum is an e-book reader that can download books from a personal online library.

**Metadata**

* homepage URL: https://librumreader.com/
* source URL: https://github.com/Librum-Reader/Librum
* license: gpl3
* platforms: gnu/linux, macos, windows

**Comment by ASHGOLDOFFICIAL** [comment]
I'm interested in this package, so here's my two cents comment.

**Comment by TanvirOnGH** [comment]
Very interested as well.

**Comment by benley** [comment]
I'm taking a stab at this.  Nothing to show for it yet, but I will share my draft later.  Need to learn some cmake stuff to figure out how to make it use a nixpkgs-provided mupdf build instead of doing an in-tree vendored build of it.

**Comment by smkuehnhold** [comment]
I got a basic flake working in my fork of the librum client [here](https://github.com/smkuehnhold/Librum). Hopefully this can help get the ball rolling. Not sure how much time I can commit to this, so anyone feel free to take over if you are more motivated. To my untrained eye, it doesn't seem too complicated IMO. Its just a few patches here and there mainly to remove the in-tree deps. 

**Disclaimer**: This is basically a script kiddies-approach. I'm not very proficient with nix and even less so with cmake. There could be _several_ issues.

![librum-nix](https://github.com/NixOS/nixpkgs/assets/15946089/170d7b13-2dde-4fa1-886a-95654436511c)

On a side-note, I'd like to request the packaging of the [Librum-Server](https://github.com/Librum-Reader/Librum-Server) along with the client. I'm not sure if that should be rolled into its own issue, but I'm more-or-less just saying it here to announce that it is something I might look into myself. 

BTW it seems that self-hosting the Librum-Server [currently requires a patch/rebuild of the client](https://github.com/Librum-Reader/Librum-Server/blob/main/self-hosting/self-host-installation.md#configuration-for-the-client-application). I'm not sure how that coupling complicates things on the nixos module side of things, so just throwing that out there.

**Comment by Ahwxorg** [comment]
Is there any update on the Librum-Server package?
