### ISSUE TITLE
Update request: adi1090x-plymouth-themes 2020-12-28 → 1.0

### ISSUE THREAD

**Issue by sochotnicky** [NixOS/nixpkgs#256068]
- Package name: adi1090x-plymouth-themes
- Latest released version: v1.0 (yay)

- Current version on the unstable channel: 2020-12-28
- Current version on the stable/release channel: 2020-12-28

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

There's been a few fixes added recently and the release is fairly fresh but I thought I'd create this

**Notify maintainers**
@slwst 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by slwst** [comment]
LGTM, thanks :smile:
