### ISSUE TITLE
using Qt5 from CMake fails due to not finding libGL

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#2560]
Qt5 projects can be built with cmake. This currently fails for packages that depend on QtGui. CMake looks for libGL.so but does not find it because it is not in ~/.nix-profile/lib/ but in /run/opengl-driver/lib.

This snippet CMakeLists.txt shows the problem:
 ====
project (Qt5Test CXX)

cmake_minimum_required(VERSION 2.8.11)

set(QT_MIN_VERSION "5.1.1")
find_package(Qt5PrintSupport)
find_package(Qt5WebKitWidgets)
 ====
Put that snippet in a file CMakeLists.txt and run 'cmake .' after installing qt5 and cmake.
This gives:
 $ cmake .
CMake Error at /home/oever/.nix-profile/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:16 (message):
  Failed to find "GL" in "".
Call Stack (most recent call first):
  $HOME/.nix-profile/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:48 (_qt5gui_find_extra_libs)
  $HOME/.nix-profile/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:125 (include)
  $HOME/.nix-profile/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:84 (find_package)
  $HOME/.nix-profile/lib/cmake/Qt5PrintSupport/Qt5PrintSupportConfig.cmake:84 (find_package)
  CMakeLists.txt:6 (find_package)

The error goes away when the location of libGL is specified:
 $ cmake -DCMAKE_LIBRARY_PATH=/run/opengl-driver/lib .

**Comment by ttuegel** [comment]
This should not be a problem with latest Qt 5, but please re-open if it is.
