### ISSUE TITLE
Package request: uutils-coreutils-noprefix

### ISSUE THREAD

**Issue by jzbor** [NixOS/nixpkgs#256149]
**Project description**

The alternative coreutils package from uutils is already packaged, although with a prefix infront of the binaries. It is possible to override the `prefix` argument, however this results in long build times as it is not covered by hydra builds. It would be nice to have a package available without the prefix, as a replacement for GNU's coreutils. I know it is not ready to be used on a system level as it is not 1:1 compatible with GNU (yet), however I have been using it just fine for the last couple of months in my user session (with home-manager).

@siraben @SuperSandro2000 

**Metadata**

* homepage URL: https://github.com/uutils/coreutils
* source URL: https://github.com/uutils/coreutils
* license: mit
* platforms:  linux, darwin

**Comment by SuperSandro2000** [comment]
Please create a PR for this otherwise I consider this wont fix.

**Comment by jzbor** [comment]
Ok I have opened a PR. Should have done it immediately. It's just one line :)

**Comment by jzbor** [comment]
Closing this as the PR has been merged. Thanks for reviewing :)
