### ISSUE TITLE
CMake complains with "sh: ps: command not found" in Nix on darwin

### ISSUE THREAD

**Issue by wavewave** [NixOS/nixpkgs#2561]
CMake seems to use ps command internally, but looks like CMake in nix on darwin can not find ps command, so it complains with message "sh: ps: command not found." (very many times)  Although this does not seem to harm build, it is desirable if this can be solved quite easily by some simple patch.

**Comment by gridaphobe** [comment]
This was fixed as part of the new darwin stdenv.
