### ISSUE TITLE
transmission: lacks useful mainProgram

### ISSUE THREAD

**Issue by jchv** [NixOS/nixpkgs#256134]
### Describe the bug
The Transmission derivation lacks a meaningful `mainProgram`. This goes for `transmission-qt` and `transmission-gtk` as well. This leads to `nix run nixpkgs#transmission-qt` failing like so:

```console
$ nix run nixpkgs#transmission-qt
error: unable to execute '/nix/store/8d7lh21m6rx58ngmf69jyly3cfnjd8z9-transmission-3.00/bin/transmission': No such file or directory
```

### Steps To Reproduce
1. Run `nix run nixpkgs#transmission-qt`.

### Expected behavior
Ideally, transmission-qt would be executed, as the `mainProgram` for transmission-qt ought to be, transmission-qt.

### Additional context
I would normally just propose a fix, but due to the way the Transmission derivation is structured, I'm not sure the best way to go about introducing a proper `mainProgram` would be. Should it be passed in from the top, or should it be derived through a series of conditionals to determine the most suitable program? The latter seems uglier to me as it would mean needing to pick a favored option when both Qt and GTK are enabled.

I can make a PR to improve this if it sounds OK to add an argument and have it passed in from above.

### Notify maintainers
@astsmtl 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11.20230915.ace5093`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(john): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kirillrdy** [comment]
@jchv I have A solution in https://github.com/NixOS/nixpkgs/pull/256866

**Comment by kirillrdy** [comment]
@jchv I've also learned that we have `transmission_4` :-)

**Comment by drupol** [comment]
Can we then close this issue ?

**Comment by jchv** [comment]
Sorry! Yes, we certainly can. Thank you @kirillrdy.
