### ISSUE TITLE
GlusterFS python tools all have import errors

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#25620]
## Issue description

```
[root@gluster-cluster-1:~]# gluster-mountbroker 
Traceback (most recent call last):
  File "/run/current-system/sw/bin/gluster-mountbroker", line 5, in <module>
    from gluster.cliutils import (execute, Cmd, node_output_ok,
ImportError: No module named gluster.cliutils

[root@gluster-cluster-1:~]# glusterfind 
Traceback (most recent call last):
  File "/run/current-system/sw/bin/glusterfind", line 14, in <module>
    from glusterfind.main import main
ImportError: No module named glusterfind.main

[root@gluster-cluster-1:~]# gluster-georep-sshkey 
Traceback (most recent call last):
  File "/run/current-system/sw/bin/gluster-georep-sshkey", line 26, in <module>
    from gluster.cliutils import (node_output_ok, execute, execute_in_peers,
ImportError: No module named gluster.cliutils

[root@gluster-cluster-1:~]# gluster-eventsapi 
Traceback (most recent call last):
  File "/run/current-system/sw/bin/gluster-eventsapi", line 22, in <module>
    import requests
ImportError: No module named requests
```

### Steps to reproduce

Install `glusterfs`; I tried this on nixpkgs commit `250c8900`.

## Technical details

I think the problem is that these scripts don't have PYTHONPATH set so that it can import gluster's own Python libs (`gluster.cliutils`) or other required python modules (`requests`).

These scripts got their `#!/usr/bin/env python` replaced by nix, but it points directly to a python interpreter binary in `/nix/store`, not to a wrapper that sets `PYTHONPATH`.

I'm not sure what the correct way to fix it is. Do we need to `wrapProgram --prefix PYTHONPATH` each individual script [around here](https://github.com/NixOS/nixpkgs/blob/16e12a6c42186436f9f06f846a100f907d02d16d/pkgs/tools/filesystems/glusterfs/default.nix#L50)? Or is there a way to do it for all of them?

**Comment by nh2** [comment]
Hmm, looks like other apps like `wicd` also use (the equivalent of) `makeWrapper` on every single executable Python script: https://github.com/NixOS/nixpkgs/blob/66d3b9a02d78cddc7ac0623fda44ac5895cd5951/pkgs/tools/networking/wicd/default.nix#L33-L49

**Comment by nh2** [comment]
Another example: `nmap`

https://github.com/NixOS/nixpkgs/blob/e3d9f438c357377d524036f88c45e9245c3809fc/pkgs/tools/security/nmap/default.nix#L37-L39

**Comment by nh2** [comment]
The nixpkgs manual and https://github.com/NixOS/nixpkgs/commit/e760c7bd6a76ed27d156d7df3d493af2a9558f11 suggest that a helper like `buildPythonApplication` can automatically `makeWrapper` all python scripts

But that doesn't seem to be the right thing for GlusterFS as it is mainly a C application.

**Comment by FRidh** [comment]
@nh2 in this case its likely best to use `wrapProgram` and `set PYTHONPATH`, not `--prefix PYTHONPATH`. You could also consider using `wrapPythonPrograms`.

**Comment by FRidh** [comment]
cc maintainer @7c6f434c

**Comment by nh2** [comment]
> this case its likely best to use wrapProgram and set PYTHONPATH, not --prefix PYTHONPATH

@FRidh can you elaborate a bit why that is better? I am not very familiar with this.

Also, where can I read about `wrapPythonPrograms`?

**Comment by FRidh** [comment]
@nh2 `buildPythonpackage` and `buildPythonApplication` are for building Python packages, typically `setuptools` packages. They build from source/sdist a wheel which is then installed.

They use the shell function `wrapPythonPrograms` that patches Python scripts to set their name (which is incorrect when Python scripts are wrapped because Python doesn't respect `exec -a`) and hardcodes their Python dependencies (using `site`) . The `wrapPythonPrograms` function is defined in the `wrapPython` package. 

In this case you only have scripts that need a Python interpreter that can find the modules provided by this package. Then its most straightforward, and least error prone, to use `wrapProgram`. We use `set PYTHONPATH` instead of `--prefix PYTHONPATH` because otherwise programs may break because of a leaking `PYTHONPATH`.

**Comment by nh2** [comment]
@FRidh Thanks for the explanations, I'll give that a try.

For my reference, `wrapPythonPrograms` is [defined here](https://github.com/NixOS/nixpkgs/blob/7cbe538e942e2ae753f83225f97c8dc22cbd4817/pkgs/development/interpreters/python/wrap.sh).

**Comment by nh2** [comment]
Follow-up on IRC:

```
nh2: FRidh: should that be `set` or `--set` to makeWrapper?
FRidh: nh2: --set
nh2: FRidh: for some reason, that makes me end up with just `export PYTHONPATH=":"`; `--prefix` doesn't have this problem
nh2: FRidh: I'm using
nh2: wrapProgram $out/bin/gluster-eventsapi --set PYTHONPATH : "$(toPythonPath $out):$(toPythonPath ${python2Packages.requests}):$(toPythonPath ${python2Packages.prettytable}):$PYTHONPATH"
nh2: am I invoking it incorrectly?
nh2: maybe that ` : `?
FRidh: nh2: the colon should indeed be removed in the case of --set
nh2: I guess that's what `separator="${params[$((n + 2))]}";` does for --prefix
nh2: sometimes I have to shiver in presence of the amount of shell scripting in nixpkgs
FRidh: then you're not the only one
nh2: FRidh: I can run `gluster-eventsapi` now without import error. But there's still the problem that it says ".gluster-eventsapi-wrapped: error: too few arguments" instead of "gluster-eventsapi: error: too few arguments" -- the "wrapped" makes it into argv[0]. I think this is related to the `exec -a` you mentioned, and which I can see in the wrapper script. But I didn't understand from your reply: Is there a fix for that?
FRidh: nh2: Unfortunately not. wrapPythonPrograms patches the script to set `sys.argv[0]` so that does solve some issues
```

**Comment by nh2** [comment]
I have a solution with the help of @cleverca22: https://gist.github.com/nh2/dbf8eb5801d9d221ef7a51c11c17bb89#file-working-with-tests-nix

I still get the error

```
# gluster system:: execute georep-sshkey.py node-generate .
Unable to end. Error : Success
```

but will hopefully fix that too, an then PR the whole thing.

**Comment by FRidh** [comment]
You could also just open a PR already as it may help in getting feedback.

**Comment by nh2** [comment]
I finally got what the error with `gluster system:: execute georep-sshkey.py node-generate .` is.

I did so by instrumenting `glusterd-geo-rep.c` so that `glusterd_op_sys_exec()` logs the stderr of programs it invokes, by adding the lines

```c
        runner_redir (&runner, STDERR_FILENO, RUN_PIPE); // nh2
```

and

```c
        do {
                ptr = fgets(buf, sizeof(buf), runner_chio (&runner, STDERR_FILENO));
                if (ptr) {
                        runner_log (&runner, "nh2 glusterd-geo-rep", GF_LOG_DEBUG, "STDERR ptr OK");
                        runner_log (&runner, "nh2 glusterd-geo-rep STDERR output", GF_LOG_DEBUG, ptr);
                } else {
                        runner_log (&runner, "nh2 glusterd-geo-rep", GF_LOG_DEBUG, "STDERR ptr NULL");
                }
        } while (ptr);
```

before their respective counterparts for stdout.

In other words, gluster 3.10.1 is discarding the stderr of failing commands in `glusterd_op_sys_exec()`.

The stderr of the failing command (`/nix/store/0h89pi4d8wchzhpzklfdlssfg7cmwhl8-glusterfs-3.10.1/libexec/glusterfs/peer_georep-sshkey.py node-generate .` in my case) is:

```
Traceback (most recent call last):
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/libexec/glusterfs/.peer_georep-sshkey.py-wrapped", line 116, in <module>
    runcli()
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/lib/python2.7/site-packages/gluster/cliutils/cliutils.py", line 224, in runcli
    cls.run(args)
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/libexec/glusterfs/.peer_georep-sshkey.py-wrapped", line 75, in run
    node_output_ok(data)
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/lib/python2.7/site-packages/gluster/cliutils/cliutils.py", line 61, in node_output_ok
    out = {"ok": True, "nodeid": get_node_uuid(), "output": message}
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/lib/python2.7/site-packages/gluster/cliutils/cliutils.py", line 35, in get_node_uuid
    rc, out, err = execute(cmd)
  File "/nix/store/wncl4hn1698l0m8r7hc0yg0nf3cn0bmc-glusterfs-3.10.1/lib/python2.7/site-packages/gluster/cliutils/cliutils.py", line 74, in execute
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/nix/store/3c598gvxavyiv2h0n2lbxgq7sf0rxf1p-python-2.7.13-env/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/3c598gvxavyiv2h0n2lbxgq7sf0rxf1p-python-2.7.13-env/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nh2** [comment]
Ah, easy.

https://github.com/gluster/glusterfs/blob/ff5e91a60887d22934fcb5f8a15dd36019d6e09a/extras/cliutils/cliutils.py#L34-L35

```
    cmd = ["gluster", "system::", "uuid", "get", "--xml"]
    rc, out, err = execute(cmd)
```

`gluster` is not on the `PATH`.

**Comment by nh2** [comment]
I filed two upstream GlusterFS bugs for this topic:

*  **errno used incorrectly or misleadingly in error messages** (https://bugzilla.redhat.com/show_bug.cgi?id=1449416)
* ** glusterd-geo-rep.c doesn't log stderr on failure to execute subprocesses** https://bugzilla.redhat.com/show_bug.cgi?id=1449861

**Comment by nh2** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/25709

**Comment by nh2** [comment]
For completeness, the command I ultimately wanted to work (and which works now) is `gluster-georep-sshkey generate`.

**Comment by nh2** [comment]
Upstream has indicated that they'd [accept a patch](https://bugzilla.redhat.com/show_bug.cgi?id=1450546#c5) that removes the hardcoded paths that I have already patched out with my NixOS patch in my PR.

So I'll try to upstream that patch for some future GlusterFS release.

**Comment by nh2** [comment]
CC @bachp as you added the glusterfs NixOS service and may be interested in the above.

**Comment by nh2** [comment]
I found another issue that makes stuff fail at runtime, and it solution. Will update PR tomorrow.

**Comment by nh2** [comment]
> I found another issue that makes stuff fail at runtime, and it solution. Will update PR tomorrow.

`gluster checks presence of version too late` - https://bugzilla.redhat.com/show_bug.cgi?id=1452705

**Comment by nh2** [comment]
> Will update PR tomorrow.

Done.
