### ISSUE TITLE
Update request: bandwhich v0.20.0 → v0.21.0

### ISSUE THREAD

**Issue by hpfr** [NixOS/nixpkgs#256240]
[First release in almost three years](https://github.com/imsnif/bandwhich/releases/tag/v0.21.0). The current version crashes on unstable.

- Package name: bandwhich
- Latest released version: v0.21.0

- Current version on the unstable channel: v.0.20.0
- Current version on the stable/release channel: v0.20.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+bandwhich)

**Notify maintainers**

@Br1ght0ne @figsoda

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Br1ght0ne** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/256105.
