### ISSUE TITLE
the bundle command doesn't work with the rake package

### ISSUE THREAD

**Issue by AtnNn** [NixOS/nixpkgs#25623]
## Issue description

There seems to be a few issues with rake and bundle:

* The `bundler` and `rake` package have a conflicting `bundle` command
* The `bundle` command in `rake` is broken, the wrapper sets environment variables such as `BUNDLE_GEMFILE` that make it impossible to use
* `rake` runs rakefiles with an unwrapped `bundle` in the `PATH`
* The wrapper for `rake` also sets `BUNDLE_*` environment variables, making it impossible to use `bundle` in a rakefile

### Steps to reproduce

`rake` comes with `bundle`. Maybe it shouldn't?

```
$ nix-env -iA nixos.rake
collision between ‘/nix/store/n2gn7ypf9q3ikl1sd7h4m6y065shx6l2-rake-11.1.1/bin/bundle’ and ‘/nix/store/7kac6gqigv4gppm9zvsbcyjy10ns7d70-bundler-1.14.6/bin/bundle’;
```

The `bundle` command it ships with doesn't work. But the one in the `bundler` package does:

```
$ /nix/store/n2gn7ypf9q3ikl1sd7h4m6y065shx6l2-rake-11.1.1/bin/bundle config gemfile
Set via BUNDLE_GEMFILE: "/nix/store/cb368ag4q1pxgfry3gwrakjrrijra50b-gemfile-and-lockfile/Gemfile"

$ /nix/store/7kac6gqigv4gppm9zvsbcyjy10ns7d70-bundler-1.14.6/bin/bundle config gemfile
You have not configured a value for `gemfile`
```

The `bundle` in `PATH` inside a rakefile is not wrapped and doesn't work:

```
$ cat Rakefile
task :default do sh 'which bundle' end
$ rake
/nix/store/gvj0hbkqdnaafgfv6vhcr96v05ixh2jg-rake-11.1.1/lib/ruby/gems/2.3.1/bin/bundle
```

Even using a working `bundle` fails, because the wrapper for `rake` sets `BUNDLE_GEMFILE` and other environment variables.

```
$ cat Rakefile
task :default do sh '/nix/store/7kac6gqigv4gppm9zvsbcyjy10ns7d70-bundler-1.14.6/bin/bundle config gemfile' end
$ rake
Set via BUNDLE_GEMFILE: "/nix/store/5dpc159y8m98l2xymrhrfy9gjkmk8jkl-gemfile-and-lockfile/Gemfile"
```

## Technical details

* System: NixOS
* Nix version: 1.11.4
* Nixpkgs version: 17.09pre106916.c5badb123a

**Comment by peterhoeg** [comment]
The problem is that you cannot currently have 2 ruby programs in the same environment (user or system) as they will clash, which is what you are seeing here.

The way to work around that is to do the following:

a) Only stick bundler in your environment as you will need this to bootstrap the remaining ruby bits

b) Create a ```Gemfile``` that references ```rake``` and whichever other gems you need

c) Use ```direnv``` in the directory with the Gemfile so that all gems are self-contained.

It's really quite ugly, yes, but that's how I'm doing it here.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by peterhoeg** [comment]
I think this is safe to close.
