### ISSUE TITLE
clang -std=c++11 does not find C++ headers

### ISSUE THREAD

**Issue by attilaolah** [NixOS/nixpkgs#256360]
### Describe the bug
Given an example `hello_world.cc` file like this:

```cc
#include <iostream>

auto main() -> int {
    std::cout << "Hello, World!" << std::endl;
    return EXIT_SUCCESS;
}
```

`clang` fails to compile it with the command:

```sh
clang -std=c++11 -c hello_world.cc
```

The `clang` installed by the underlying system (Arch) has no trouble compiling this file.

And yes, there is `clang++` for C++ files, but Bazel only invokes `clang` (or `CC` for that matter), and running Bazel with `CC=clang` seems to fail whenever it encounters a C++ compilation unit that uses the standard library, which is pretty much all of them.

### Steps To Reproduce

1. Create the `hello_world.cc` from above.
2. Run `clang -std=c++11 -c hello_world.cc`

### Expected behavior

There should be no errors and a 0 exit status, with a `hello_world.o` file generated.

### Additional context

I have Arch linux as my base system which runs the Nix systemd service, with `clang` installed via `home-manager`. 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/bysc0bn22cdwy1wzrn0n3rdid07d9cla-nix-info
copying path '/nix/store/bysc0bn22cdwy1wzrn0n3rdid07d9cla-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.3-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/home/atl/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by attilaolah** [comment]
Still not sure whether or not this is working as intended, but it seems that explicitly passing something like `-isystem /nix/store/nrc9pw6a2kf5rm6indqyj4yvk3bb6wwb-libcxx-11.1.0-dev/include/c++/v1` to `clang` solves the issue.

It still doesn't solve the issue with Bazel's auto-configured toolchain, since it would not recognise the `/nix/store/…` path as a system include path and wouldn't add it, not even as a user-defined `--cxxopt` since it is outside the execution root.

**Comment by attilaolah** [comment]
Solved by adding the following line to my `.bazelrc`:

```conf
build --cxxopt=-xc++ --host_cxxopt=-xc++
```

Not sure why this is required by the flavour of `clang` shipped with Bazel, maybe some version incompatibility since Nix still gives me version 11, while the one on the host OS is version 16.

Anyway, since I'm not sure whether this is a bug or working as intended, I'll keep it open, but since my problem is now solved, feel free to close this if this is expected behaviour.

**Comment by Artturin** [comment]
You're supposed to compile c++ files with `clang++` right?

**Comment by attilaolah** [comment]
Ah sorry I didn't find #150655. Let me close this one as duplicate then. I'm not sure I agree with the fact that this is a Bazel bug, since arguably Bazel uses the compilers "correctly", except it doesn't use the provided wrappers that automatically add the C++ header files, which is ultimately down to flexibility since one might want to use a different standard library (or ship their own). But that's besides the point.

Eventually I got things to compile using Clang $CC with the right C++ flags though, but I can't find the right incarnation now. I'll close this bug and update it if I find the right set of commands.
