### ISSUE TITLE
Package request: Bavarder

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#256319]
**Project description**

Bavarder is a software application that allows users to engage in chat-based conversations with an artificial intelligence interface. It boasts a variety of features including but not limited to the implementation of a local AI system, an interactive chat mode, system prompts for user guidance, and fine-tuning capabilities.

**Metadata**

* source URL: https://github.com/Bavarder/Bavarder
* license: gpl3Plus
* platforms: linux (flatpak)

**Comment by langfingaz** [comment]
See pull request https://github.com/NixOS/nixpkgs/pull/228585
