### ISSUE TITLE
i3 config generation uses absolute path for dmenu_run in nix store

### ISSUE THREAD

**Issue by tripokey** [NixOS/nixpkgs#25633]
## Issue description

The i3 window manager generates a default configuration containing an absolute path to dmenu_run:
bindsym $mod+d exec /nix/store/fslvwld2p4vrjrlvrhls9jgns8i0n6j5-dmenu-4.6/bin/dmenu_run

This needs to be manually corrected when that path is garbage collected after an upgrade.

### Steps to reproduce

1. Install and set i3 as window manager.
2. Start an i3 session and let it generate a config file in .config/i3

## Technical details

* System: 17.03.902.536d3cac2e (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1123.4a7a03913d"
* Sandboxing enabled: build-use-sandbox = false

**Comment by primeos** [comment]
This also affects `i3status`.

There was a thread on the ML as well: [[Nix-dev] paths in user's i3 configs broken by upgrade](https://mailman.science.uu.nl/pipermail/nix-dev/2017-April/023326.html).

IMHO we should revert #12873 and introduce the following option: `services.xserver.windowManager.i3.extraPackages` defaulting to `with pkgs; [ dmenu i3status i3lock ]` (`i3lock` is optional but why not...).

**Comment by joachifm** [comment]
cc @ericsagnes
