### ISSUE TITLE
Certain package do not respect the `NIXOS_OZONE_WL` environment variable

### ISSUE THREAD

**Issue by IogaMaster** [NixOS/nixpkgs#256401]
### Describe the bug
A few electron applications do not use `NIXOS_OZONE_WL` environment variable to change settings.
This causes a black screen when using these packages on wayland.

Packages I have found not to work:

- postman
- beekeeper-studio

This was made known to me by @redyf on Discord.

### Steps To Reproduce
`nix-shell -p beekeeper-studio`
`beekeeper-studio`
Black screen.

### Expected behavior
![image](https://github.com/NixOS/nixpkgs/assets/67164465/1bef5f3a-72ea-4ecf-aa2e-5d4631fb3cfa)

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/67164465/12859d43-8cd5-4b02-9f97-7fa0637ad09d)

### Additional context
A temporary work around is to run the application with the `--use-gl=desktop` flag.

### Notify maintainers

I will work on this myself.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.11 (Tapir), 23.11.20230914.f2ea252`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.17.0`
 - channels(iogamaster): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by IogaMaster** [comment]
If any other packages are exhibiting this behavior please let me know on this issue.

**Comment by IogaMaster** [comment]
Can confirm, I'll create a new pr.

**Comment by IogaMaster** [comment]
@prTopi 
#264506

**Comment by abmantis** [comment]
Ferdium also does not respect the env (and I assume Ferdi and Franz by looking at their sources).

**Comment by abmantis** [comment]
For some reason the following is not working: https://github.com/NixOS/nixpkgs/compare/master...abmantis:nixpkgs:patch-2
But this is: https://github.com/NixOS/nixpkgs/compare/master...abmantis:nixpkgs:ferdium_wayland

I do have both NIXOS_OZONE_WL and WAYLAND_DISPLAY set.
