### ISSUE TITLE
libusb broken?

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#25642]
## Issue description
Trying to run any of `xsane`, `simple-scan` gives me:
```
$ simple-scan
/home/danbst/.nix-profile/bin/simple-scan: error while loading shared libraries: /nix/store/chpxpl713q2ibdip4k9pkvlrzyvhpwva-libusb-1.0.20/lib/libusb-1.0.so.0: invalid ELF header
```
Seems like the mentioned file is broken:
```
$ hexdump -C /nix/store/chpxpl713q2ibdip4k9pkvlrzyvhpwva-libusb-1.0.20/lib/libusb-1.0.so.0.1.0
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
0001d840  00 00 00 00 00 00 00 00                           |........|
0001d848
```

### Steps to reproduce
Try to run `xsane` or `simple-scan`

## Technical details

* System: 17.09.pre.7f3b857 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: 17.09pre106916.c5badb123a
* Sandboxing enabled: no

**Comment by danbst** [comment]
cc @groxxda

**Comment by 7c6f434c** [comment]
File with all zeros in the header looks more like store corruption. 
Maybe apply `nix-store --verify --repair --check-contents` to the store path?

**Comment by danbst** [comment]
looks like it! lot's of corruption...
