### ISSUE TITLE
fetchFromGitHub: http download should fall back to fetchgit

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25647]
## Issue description

It happens sometimes that HTTP GET of ```https://github.com/$owner/$repo/archive/$commithash.tar.gz``` returns 404.

I think, in this case ```fetchFromGitHub``` should fall back and try to use ```fetchgit``` to get the files using git protocol

**Comment by FRidh** [comment]
I don't think that's possible:

1. `fetchFromGitHub` and `fetchgit` are Nix functions. If the `GET` fails, then building the derivation fails. Nix doesn't handle having A or B as far as I know.
2. the hashes of the result of each would/could be different.
