### ISSUE TITLE
Package request: Fastfetch

### ISSUE THREAD

**Issue by Twig6943** [NixOS/nixpkgs#256521]
fastfetch is a cl utility that is neofetch but faster

**Metadata**

* homepage URL: https://github.com/fastfetch-cli/fastfetch
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...
Linux, Android and Windows

**Comment by OPNA2608** [comment]
Was added to Nixpkgs last month: https://github.com/NixOS/nixpkgs/pull/241997

It's available on the unstable channel, currently at version 2.0.5.
![image](https://github.com/NixOS/nixpkgs/assets/23431373/2484ea51-dca1-41f0-93eb-9c092f5e5b11)

**Comment by Gerg-L** [comment]
Fastfetch could be back-ported
Here's a discourse post about grabbing a single package from unstable: https://discourse.nixos.org/t/installing-only-a-single-package-from-unstable/5598
