### ISSUE TITLE
Warn users when they try to install libraries into a profile?

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#25671]
I'm not sure how exactly this would be done, but I think it would be useful to let users know that installing a library into a profile is unlikely to be what they want and that they should probably be using nix-shell instead. This would probably avoid a lot of confusion and repeated asking of the same question in various places. See #25637, #23039, IRC channel, mailing list…

**Comment by lheckemann** [comment]
I've written https://github.com/nixos-users/wiki/wiki/FAQ#i-installed-a-library-but-my-compiler-is-not-finding-it-why as a stock reponse to the question, but it would be nice to warn users automatically if they try to do this.

**Comment by FRidh** [comment]
Partial duplicate of https://github.com/NixOS/nixpkgs/issues/19692

**Comment by FRidh** [comment]
See also https://github.com/NixOS/nix/issues/1100#issuecomment-255139904

**Comment by lheckemann** [comment]
Good catch, I suppose I'll close this then.

**Comment by JohnAZoidberg** [comment]
But #19692 is just about Python libraries. This issues is also about e.g. C libraries?

**Comment by FRidh** [comment]
Python is between parenthesis. It's a general way of working in Nixpkgs; we do not promote installing libraries and may go as far as simply not supporting it.
