### ISSUE TITLE
`blackbox-terminal` is using way too much memory

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#256721]
### Describe the bug
`blackbox-terminal` is using too much memory, and all of this gets filled in within minutes. Initially on starting, it takes about 68.7 MB, and after a few minutes of usage, spikes up to about 5.0 GB!

### Steps To Reproduce
1. Open `blackbox-terminal`
2. Run a few commands (ex: vim, top, ssh, etc)
3. Terminal will become incredibly slow, hog about 70-75% of the memory and crash

### Expected behavior
Terminal apps shouldn't need so much memory

### Screenshots

Here's the screenshot for `top`:
![Screenshot from 2023-09-22 21-37-27](https://github.com/NixOS/nixpkgs/assets/113123021/252d3795-4b8e-4557-aa0a-91513b356fae)

I am not sure if this is related to the problem, but for some reason, Sixel support is enabled on a disabled option, possibly from the old cache from the previous installation. Could this perhaps be the reason for hogging memory?

![image](https://github.com/NixOS/nixpkgs/assets/113123021/955cef1f-cdf6-4423-99d7-675e00bc2f72)

### Additional context
\-

### Notify maintainers
@chuangzhu
@PJungkamp 
@AndersonTorres 
@tfmoraes 
@schuelermine 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.11 (Tapir), 23.11pre526521.970a59bd19ef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(ashvith): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by AndersonTorres** [comment]
I am not the maintainer of this  package. But I am interested.

**Comment by tfmoraes** [comment]
I think this is the problem https://gitlab.gnome.org/raggesilver/blackbox/-/issues/312

About the Sixel support it's not enabled because the VTE compiled in Nixpkgs isn't compiled with sixel support (it's  experimental).

**Comment by Ashvith10** [comment]
@tfmoraes Apologies, I forgot to share the main screenshot, can you check that out the top post again? This looks like more of a RAM hogging and less of a CPU hog to me. Perhaps, there's CPU hog too, but maybe I've not noticed it?

**Comment by tfmoraes** [comment]
@Ashvith10 other blackbox-terminal user reported this [bug report](https://gitlab.gnome.org/raggesilver/blackbox/-/issues/333). Maybe it's the same problem. There is also a flatpack version too https://flathub.org/apps/com.raggesilver.BlackBox

**Comment by Ashvith10** [comment]
@tfmoraes looks like the new issue you've share matches with mine as well. I'm sticking with Tilix temporarily, so all is good for now.

**Comment by mambucodev** [comment]
This is happening again. I was not even using the terminal, and it went up to 25GB of memory usage, out of nowhere.

**Comment by 766F6964** [comment]
> This is happening again. I was not even using the terminal, and it went up to 25GB of memory usage, out of nowhere. Edit: I have 32GB total.

I can confirm the same issue - Arch Linux system, and blackbox after normal usage takes up over 25GB of memory.
