### ISSUE TITLE
Enabling 'xmr-stak' service results in build error

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#256703]
### Describe the bug
When attempting to enable the 'xmr-stak' service in the NixOS configuration by setting `services.xmr-stak.enable = true;` and then running `nixos-rebuild switch`, an error is encountered. This issue aims to report the error and seek resolution.

### Steps To Reproduce
1. Add `services.xmr-stak.enable = true;` to the NixOS configuration.
2. Run: `nixos-rebuild switch`.

### Expected behavior
The 'xmr-stak' service should be able to install its required files and binaries into the system, and the rebuild process should proceed without encountering any errors.

### Error Details:
The error message received during the execution is as follows:
```nix
[user@system:~]$ doas nixos-rebuild switch
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/vkkna3cgzxd1nm0qka0xvpllszyacriy-nixos/nixos/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while evaluating the attribute 'value'

         at /nix/store/vkkna3cgzxd1nm0qka0xvpllszyacriy-nixos/nixos/lib/modules.nix:800:9:

          799|     in warnDeprecation opt //
          800|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          801|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'cudaSupport'

       at /nix/store/vkkna3cgzxd1nm0qka0xvpllszyacriy-nixos/nixos/pkgs/applications/misc/xmr-stak/default.nix:1:1:

            1| { stdenv, lib, fetchpatch
             | ^
            2| , fetchFromGitHub, cmake, libmicrohttpd, openssl         
```

### Notify maintainers

@bfortz, @trofi

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.3-xanmod1, NixOS, 23.11 (Tapir), 23.11pre525972.ace5093e36ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trofi** [comment]
The error tells you that something passes `cudaSupport` parameter to `xmr-stak`. That parameter does not exist there. I removed the parameter in a5ce71d4e8cbe1d3311aeddc86a8d847989d6099 when noticed it was broken for a while.

`nixos/modules/services/misc/xmr-stak.nix` is still passing the option. Let's remove it as well. Meanwhile try to disable the option explicitly as:

```nix
services.xmr-stak.cudaSupport.enable = false;
```

**Comment by trofi** [comment]
Also /cc @fpletz who added the initial module.

**Comment by trofi** [comment]
> services.xmr-stak.cudaSupport.enable = false;

Ah, sorry. It does not work as it tries to hass non-existent `cudaSupport = false`. I'll send a PR to rip out the option entirely.

**Comment by trofi** [comment]
Proposed the fix as https://github.com/NixOS/nixpkgs/pull/256725
