### ISSUE TITLE
When updating `nixpkgs-check-by-name`, it should be run on Nixpkgs

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs#256789]
When the `nixpkgs-check-by-name` tooling is updated, it should be run on Nixpkgs in the same PR. This also relates to https://github.com/NixOS/nixpkgs/issues/256788.

This could be achieved using `passthru.tests` on the `tests.nixpkgs-check-by-name` derivation which copies Nixpkgs to the store and then runs the tooling on it in a derivation. This would then automatically be run when a commit with the `tests.nixpkgs-check-by-name: ` prefix is in the PR. This is however fairly slow and expensive due to the Nixpkgs copy.

**Comment by roberth** [comment]
> This is however fairly slow and expensive due to the Nixpkgs copy.

OfBorg performs checkouts all the time. I don't think this is significant.

To run it locally, this style of test runner is not great, but we can refer readers to the instructions for a manual run.

**Comment by infinisil** [comment]
> OfBorg performs checkouts all the time. I don't think this is significant.

It's not just a local checkout though, if we use derivations to run the check, then Nixpkgs also needs to be copied into the store. Should probably be fine though, other parts of Nixpkgs also copy Nixpkgs into the store.

**Comment by infinisil** [comment]
I don't think this should be done after all. With the latest idea [here](https://github.com/NixOS/nixpkgs/issues/256788#issuecomment-1760610982), the latest version of the tooling in Nixpkgs needs to stay independent of the pinned version used for CI.

**Comment by Ericson2314** [comment]
Agree that for the PR checking, the currently implemented approach is fine. However, I think it is still good to have the "simple" version that doesn't refer to other Nixpkgs / channels as a `tests` attribute.

The point of this is not to catch CIs, but to just sanity check with hydra after the fact that everything worked out the way it should. The impure tricky business with channels is still necessary, but the idea is that it is an *optimization* and the simple self-contained `tests.<blah>` version is the *reference implementation* that ultimately defines the behavior we want.

**Comment by infinisil** [comment]
Implemented in https://github.com/NixOS/nixpkgs/issues/256789
