### ISSUE TITLE
`sudo` module broken

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#256713]
### Describe the bug

       error: attribute 'sudo' missing

       at /nix/store/p0vbrwdawc1n0mvk2lls06scl61lvzjq-source/nixos/modules/security/sudo.nix:13:31:

           12|     with config.security;
           13|     pam.enableSSHAgentAuth && pam.sudo.sshAgentAuth;
             |                               ^
           14|

### Steps To Reproduce

Build a system that includes `pam.enableSSHAgentAuth

### Expected behavior

That it should beuild

### Additional context

This appears to be a consequence of 8742134c80539b3f8e9c7c51b13a225a92e97b9a

### Notify maintainers

@nbraud this appears to be your change?

**Comment by mkg20001** [comment]
Should be solved now
