### ISSUE TITLE
libreoffice and libreoffice-qt packages use icon names incompatible with icon themes

### ISSUE THREAD

**Issue by jilinoleg** [NixOS/nixpkgs#256752]
### Describe the bug
Libreoffice desktop files seems to be using names for icons that are not adopted by icons packs and also are sometimes overlap with other existing icons like calc. I'm not sure if it's a upstream change in libreoffice source, but since I only had this issue in NixOS, I'm writing about it here.

### Steps To Reproduce
1. Install libreoffice or libreoffice-qt in system packages
2. Install and apply papirus-icon-theme
3. See how only icon changed is calc, which now shows calculator icon

### Expected behavior
.desktop file using libreoffice-* icons instead of * icons (like libreoffice-calc instead of calc)

### Screenshots
![Screenshot showing how libreoffice uses icons not from current theme but](https://github.com/NixOS/nixpkgs/assets/65215026/a8060b39-b19f-4924-90a4-3a68d46858e6)

### Additional context
I have only tested it with Papirus icons with KDE, and have not found the issue simmilar to this one in nixpkgs or papirus icons issue trackers.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/gd9mmij8iifhldkhjsgbr08i55nm4lsg-nix-info
copying path '/nix/store/gd9mmij8iifhldkhjsgbr08i55nm4lsg-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.05 (Stoat), 23.05.20230921.55ac2a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by RAVENz46** [comment]
I cannot specify which commit but it was fixed for me.
