### ISSUE TITLE
buildNpmPackage / fetch-npm-deps runs into rate limiting

### ISSUE THREAD

**Issue by orangecms** [NixOS/nixpkgs#256873]
AIUI, requests are being sent out over and over again, and I do not understand why.
For a single build, that already runs into rate limits when buildings apps.

Native npm would use its cacache to avoid unnecessary requests.
Is there a chance to only request files that are not yet downloaded?

For implementation, I can help witht the Rust part, but Nix is too complicated for me at this point.

**Comment by orangecms** [comment]
Addendum:
Currently, one would see "unknown error", either with a request that GitHub rejected or partial file transfer.
I have hacked around a bit in the Rust code to figure out the actual error. I may file some PRs to improve the feedback, not too soon though. :)

**Comment by BlankParticle** [comment]
Oh My god, I was losing my mind while trying update `vencord` to latest version, the build kept failing, please help to fix it as soon as possible.

**Comment by RaitoBezarius** [comment]
cc @lilyinstarlight do we track something like this somewhere?

**Comment by TheArcaneBrony** [comment]
Looks like I ran into the same issue. Seems to happen on our home connection (12mbps) but not on our server's connection (gigabit).

I wonder if this is a "too many concurrent connections" issue rather than "too many consecutive requests"?

**Comment by lilyinstarlight** [comment]
For people on this issue instead of the other, see my comment at https://github.com/NixOS/nixpkgs/issues/257805#issuecomment-1751344432. Having someone test that would be helpful

**Comment by lilyinstarlight** [comment]
Pleases try #260011
