### ISSUE TITLE
Update request: gnome-shell 44.4 → 45.0

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#256826]
- Package name: gnome-shell
- Latest released version: 45.0

- Current version on the unstable channel: 44.4
- Current version on the stable/release channel: 44.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jtojnar 
@Ashvith10 (me)

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by the-furry-hubofeverything** [comment]
#247766?

**Comment by Ashvith10** [comment]
@the-furry-hubofeverything thank you for sharing it. I'll close this issue.
