### ISSUE TITLE
Update request: zabbix 6.0.14 → 6.4.6

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#256991]
- Package name: zabbix
- Latest released version: 6.4.6
- Current version on the unstable channel: 6.0.14
- Current version on the stable/release channel: 6.0.14
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mmahut
@PsyanticY
@aanderse

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by aanderse** [comment]
unfortunately we cannot support `zabbix` releases which are not LTS because they have such a [short lifespan](https://www.zabbix.com/life_cycle_and_release_policy) - `zabbix` version `6.4` will be EOL before the next version of NixOS is released!
