### ISSUE TITLE
Build failure: python38.pkgs.numpy

### ISSUE THREAD

**Issue by pedohorse** [NixOS/nixpkgs#256939]
### Steps To Reproduce

1. build `nix build nixpkgs#python38.pkgs.numpy`

### Build log

```
 > building
 > Executing setuptoolsBuildPhase
 > Traceback (most recent call last):
 >   File "nix_run_setup", line 8, in <module>
 >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
 >   File "setup.py", line 22, in <module>
 >     raise RuntimeError("Python version >= 3.9 required.")
 > RuntimeError: Python version >= 3.9 required.
```

### Additional context

fails to build in master and nixos-unstable branches,
builds fine on nixos-23.05 branch

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.43, NixOS, 23.05 (Stoat), 23.05.20230805.9607b91`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `/nix/store/97s3080dx00wbygfki2nyqhjg97pl6bc-source`
```

**Comment by l0b0** [comment]
[NumPy 1.25.1 does not support Python < 3.9](https://github.com/numpy/numpy/releases/tag/v1.25.1), so I believe this should be as simple as changing [`disabled = pythonOlder "3.7";`](https://github.com/l0b0/nixpkgs/blob/f723b546999fd38444e950dd33f2ae65278c1ea7/pkgs/development/python-modules/numpy/default.nix#L46) to `disabled = pythonOlder "3.9";`. Is there any reason not to do this, @FRidh?

**Comment by pedohorse** [comment]
@l0b0  But what do I do if I need python3.8 with any compatible version of numpy ?

**Comment by l0b0** [comment]
You can [search for older versions compatible with Python 3.8](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=python3.8-numpy). Not exactly obvious, but the service is there.

**Comment by pedohorse** [comment]
wow, that's actually a very useful site!
i wish there was an official search service like that from nix project...
