### ISSUE TITLE
Get GitHub to pick up and display our license properly

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#25705]
GitHub has a nice little license widget that helps people better understand software licenses of projects. Unfortunately it only looks for a file called LICENSE or LICENSE.md, and ours is called COPYING so we don't get that goodness. If we just rename our file, that will solve ALL the problems. That's right. All of them!

**Comment by copumpkin** [comment]
Actually, I think the issue is that our COPYING file has a note at the bottom that breaks GitHub's understanding of the license 😦 That note might be better represented in the README, but I'm curious what others think.

**Comment by c0bw3b** [comment]
It seems that GH uses the `licensee` Ruby gem from https://ben.balter.com/licensee/

This tool picks up the COPYING file but it is not able to identify the license with enough confidence.
Here is a local test :
```bash
$ ./result/bin/licensee ~/.nox/nixpkgs/
License: Other
Matched files: ["COPYING"]
COPYING:
  Content hash: 1a275a760c40a06ff4beee9826964d5273e26f77
  Attribution: Copyright (c) 2003-2017 Eelco Dolstra and the Nixpkgs/NixOS contributors
  License: Other
  Closest licenses:
    * BSD-3-Clause-Clear similarity: 46.15%
```

Now if we remove the foot note entirely :
```shell
License: MIT License
Matched files: ["COPYING"]
COPYING:
  Content hash: d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution: Copyright (c) 2003-2017 Eelco Dolstra and the Nixpkgs/NixOS contributors
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
```


So +1 on moving this footnote into another file. README is already quite crowded...
What about creating a new NOTICE file that would says something like "_see COPYING_" plus the important note ?
