### ISSUE TITLE
Package request: wio (fork)

### ISSUE THREAD

**Issue by zeronobody0** [NixOS/nixpkgs#257000]
**Project description**

Wayland compositor similar to Plan 9's rio (mirror).
Note that the upstream for this software was [removed previously](https://github.com/NixOS/nixpkgs/pull/228632) due to being unmaintained and depending on an outdated wlroots. I am proposing that this fork of that software is added to pkgs and the entry for the original in aliases.nix is amended to point to the fork. Note also that the only changes made from the original wio derivation to build the software (other then changing `src`) is the addition of `preConfigure = ''sed -i "16 a '-Wno-maybe-uninitialized'," meson.build'';`. I am pinging @AndersonTorres because they where the maintainer of the deprecated software that this addition will posthumously replace.

**Metadata**

* homepage URL: https://github.com/Rubo3/wio
* source URL: https://github.com/Rubo3/wio
* license: BSD 3-Clause
* platforms: linux

**Comment by AndersonTorres** [comment]
I am happy to know!
