### ISSUE TITLE
nvidia-x11 4.10 kernel patch url is borken

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#25702]
## Issue description

I tried to update my NixOS and found it fails to fetch a kernel patch required here:
https://github.com/NixOS/nixpkgs/blob/b5c35862896e228305c402c4174720c09c12a8f6/pkgs/os-specific/linux/nvidia-x11/generic.nix#L61

### Steps to reproduce

1. Use nixpkgs version 17.09pre107265.0afb6d789c
2. specify `boot.kernelPackages = pkgs.linuxPackages_4_10` and `services.xserver.videoDrivers = [ "nvidiaBeta" ];` in configuration.nix
3. nixos-rebuild boot

## Technical details

* System: 17.09pre105622.f0fac3b578 (Hummingbird)
* Nixpkgs version: 17.09pre107265.0afb6d789c
* Sandboxing enabled: true

cc @MP2E who added this patch, thank you!

**Comment by AnotherBugworm** [comment]
Same thing on `17.03.1123.4a7a03913d (Gorilla)` with `nvidia` videodriver
```
trying https://git.archlinux.org/svntogit/packages.git/plain/trunk/kernel_4.10.patch?h=packages/nvidia
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download nvidia from any mirror
builder for ‘/nix/store/b504xk2j9s72d6j4hkxfpq75zc6ma831-nvidia.drv’ failed with exit code 1
```

**Comment by lheckemann** [comment]
This is probably because the latest version of the nvidia driver supports 4.10 without patches. #25698 should hopefully fix it simply because it won't need the patch anymore, although I didn't remove the reference in case someone does want to use the older driver.

**Comment by lheckemann** [comment]
https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/nvidia&id=358fcb0a5336bd502ef0117bd6bcf88dbcc0709d this is what broke it. We can probably still refer to an older version from the history. I'll add it to my PR.

**Comment by sifmelcara** [comment]
I am not sure if `nvidiaBeta` (378.13) supports 4.10 without the patch. (I guess no)
Anyway, 378.13 seems outdated according to [nvidia's Unix Driver Archive](http://www.nvidia.com/object/unix.html), @lheckemann it would be great if you can also update `nvidiaBeta` to the newest version.

**Comment by MP2E** [comment]
thanks for the ping, have addressed this by updating the nvidia stable and beta drivers to their latest versions
