### ISSUE TITLE
NIX_CXXSTDLIB_COMPILE missing in stdenv

### ISSUE THREAD

**Issue by natto1784** [NixOS/nixpkgs#257051]
### Describe the bug
`stdenv` environments do not contain `NIX_CXXSTDLIB_COMPILE ` variable unlike `NIX_CFLAGS_COMPILE`. Having this variable would be useful for say, having `clangd` see LLVM's `libcxx` which is not present under `include/` but `include/c++/v1`. `cc-wrapper `already adds this under `NIX_CXXSTDLIB_COMPILE@saltSuffix@` in `add-flags.sh` so adding this in `setup-hook.sh` shouldn't be a huge issue but doing this the straightforward way would cause entire nixpkgs to be rebuilt from what I understand. Please correct me if I am wrong or missing something.

@Artturin @Ericson2314 @Mic92
Do you have any insights on this?

Note that my specific case can be solved by just adding the path by myself in a shellHook or something but I am not sure if there can be a more elegant approach.

**Comment by natto1784** [comment]
Now that I see more, setup-hook.sh seems to be independently setting `NIX_CFLAGS_COMPILE`. I am not sure how we can add `libcxx` here

**Comment by Mic92** [comment]
I recently also learned that clangd is leaked unwrapped in the clang package.
Does the wrapper for clangd in clang-tools work for you?

```console
$ cat /nix/store/f6ksjvjcxi039yf62109h5xg91ybxbg6-clang-tools-14.0.6/bin/clangd
#!/nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/sh

buildcpath() {
  local path after
  while (( $# )); do
    case $1 in
        -isystem)
            shift
            path=$path${path:+':'}$1
            ;;
        -idirafter)
            shift
            after=$after${after:+':'}$1
            ;;
    esac
    shift
  done
  echo $path${after:+':'}$after
}

export CPATH=${CPATH}${CPATH:+':'}$(buildcpath ${NIX_CFLAGS_COMPILE} \
                                               $(</nix/store/3dbhq59c8xpkhsypksmcd2ras9ydpj0p-clang-wrapper-14.0.6/nix-support/libc-cflags)):/nix/store/3dbhq59c8xpkhsypksmcd2ras9ydpj0p-clang-wrapper-14.0.6/resource-root/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}${CPLUS_INCLUDE_PATH:+':'}$(buildcpath ${NIX_CFLAGS_COMPILE} \
                                                                                      $(</nix/store/3dbhq59c8xpkhsypksmcd2ras9ydpj0p-clang-wrapper-14.0.6/nix-support/libcxx-cxxflags) \
                                                                                      $(</nix/store/3dbhq59c8xpkhsypksmcd2ras9ydpj0p-clang-wrapper-14.0.6/nix-support/libc-cflags)):/nix/store/3dbhq59c8xpkhsypksmcd2ras9ydpj0p-clang-wrapper-14.0.6/resource-root/include
```

This also takes care of c++ stdlib headers.

**Comment by natto1784** [comment]
OH, I completely overlooked where you add flags from `libcxx-cxxflags`. So, yes, the issue I originally addressed is resolved. But the problems remains with `clangd` since we use `llvmPackages.clang` and not `llvmPackages.libcxxClang`. Using the latter solves the issue. At least the problem is now much more simpler. Will create a separate issue for this, apologies to everyone.

**Comment by natto1784** [comment]
https://github.com/NixOS/nixpkgs/pull/257060
