### ISSUE TITLE
Enabling NetworkD doesn't appear to symlink the resolv.conf

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#25706]
I recently enabled networkd, and I found that `/etc/resolv.conf` is missing (it has been converted to a backup file). The arch wiki says that when using systemd-networkd, to maintain compatibility with applications expecting `/etc/resolv.conf`, there should be a symlink:

```
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

Without this file, some applications refuse to run or build. For example building nodePackages.tern fails because one of the dependencies expects there to be `/etc/resolv.conf`.

**Comment by CMCDragonkai** [comment]
There should probably be a script that is executed here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces-systemd.nix that sets up the symlink.

**Comment by Mic92** [comment]
It is not intuitive, but if you set:

```
services.dnsmasq.resolveLocalQueries = false;
```

You will have your /etc/resolv.conf link back.

**Comment by CMCDragonkai** [comment]
@Mic92 What if you want dnsmasq to resolve local queries? I just manually added the symlink.

**Comment by Mic92** [comment]
Then just use:

```
networking.nameservers = [ "127.0.0.1" ];
```

dnsmasq will then take by default the dns server it got from dhcp (networkd) by default.

**Comment by CMCDragonkai** [comment]
I see, but that seems like a bit of a hack, what's wrong with injecting a

```
"dnsmasq-resolv.conf".source = "/run/systemd/resolve/resolv.conf";
"resolv.conf".source = "/run/systemd/resolve/resolv.conf";
```

Both at line: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/networking.nix#L227

**Comment by Mic92** [comment]
Then dnsmasq will be not used resolve your local dns queries. Depends on what you want to achieve actually...

**Comment by CMCDragonkai** [comment]
@Mic92 Can you explain what you mean here? Why would dnsmasq not resolve local queries with such a patch? My manually symlinked /etc/resolv.conf currently has:

```
nameserver 127.0.0.1
nameserver 192.168.88.1
nameserver 202.171.191.10
```

I had networkd enabled, dnsmasq enabled, resolve local queries, but without explicit `networking.nameservers = [ "127.0.0.1" ];`. Something in NixOS modules or systemd-networkd will put "nameserver 127.0.0.1" there. Therefore local queries should still be resolved right?

In fact `dig google.com` shows that it's 127.0.0.1 that's resolving my query.

**Comment by Mic92** [comment]
If you still use the glibc resolver and not systemd-resolved, it will eventually also use the other nameserver from my experience. Do you have something in your .network files, which creates the 127.0.0.1 entry?

**Comment by Mic92** [comment]
This is the origin: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/dnsmasq.nix#L76

**Comment by CMCDragonkai** [comment]
Ok I understand, to make sure dnsmasq is the only resolver, we must only have `nameserver 127.0.0.1` there, otherwise as you said, the other nameservers may be used.

Still I think there should be better solution than:

```
networking.nameservers = [ "127.0.0.1" ];
services.dnsmasq.resolveLocalQueries = false;
```

Since resolveLocalQueries sets `networking.nameservers = [ "127.0.0.1" ];` anyway, then instead of making it a symlink, we should write the actual file here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/networking.nix#L227

Something like:

```
"resolv.conf".text = ''
nameserver 127.0.0.1
''
```

It can be done because dnsmasqResolve comes from these 2 booleans: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/networking.nix#L10-L11

**Comment by Mic92** [comment]
"resolveAllQueriesLocally" sounds like it would not use other recursive nameserver but process queries on its own (by querying root server directly) . The reason why you see additional entries, that those are come from dhcp. Systemd-resolved, which is currently enabled on your system, will take
nameserver server from its configuration:

```
cat /etc/systemd/resolved.conf 
[Resolve]
DNS=127.0.0.1 # this option was set by networking.nameservers = [ "127.0.0.1" ];
LLMNR=true
DNSSEC=false
```

And will combine it with the nameserver it got from systemd-networkd. You can disable this behavior
by toggling `UseDNS=` (https://github.com/Mic92/nixos-configuration/blob/master/network-configuration.nix#L222). If resolved is enabled, you will also see a stub resolver added to your system (libnss_resolv.so).

```
#/etc/nsswitch.conf
passwd:    files mymachines
group:     files mymachines
shadow:    files

hosts:     files mymachines resolv [!UNAVAIL=return] dns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

systemd-resolved is smarter then the glibc resolver. It will always prefer the nameserver, you specified in configuration and fallback to other nameserver if the first one is down. It also has the concept of interfaces, so if it get an nameserver via an interface it will only use it on this interface including search domains. But the libnss_resolv.so will not work at the moment until is https://github.com/NixOS/nixpkgs/pull/21178 merged.

**Comment by Mic92** [comment]
Ok. systemd's stub resolver should work properly.

**Comment by CMCDragonkai** [comment]
Also relevant: https://github.com/NixOS/nixpkgs/commit/9827d5f95cc71cf47eeaec1d1ddf08633e8490cb

**Comment by CMCDragonkai** [comment]
@Mic92 Awesome thanks. Other readers do note the discussion at: https://github.com/NixOS/nixpkgs/commit/9827d5f95cc71cf47eeaec1d1ddf08633e8490cb

**Comment by CMCDragonkai** [comment]
After updating to 17.09 I have this situation.

```
networking.useNetworkd = true;
dnsmasq.resolveLocalQueries = true;
```

I didn't set the `networking.nameservers`.

Now I see that /etc/resolv.conf -> /etc/static/resolv.conf -> /nix/store/50ln38azsnzlv5181mfa10hhmdxqmqxf-systemd-234/lib/systemd/resolv.conf:

```
# This is a static resolv.conf file for connecting local clients to
# systemd-resolved via its DNS stub listener on 127.0.0.53.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
```

And also /etc/dnsmasq-resolv.conf -> /etc/static/dnsmasq-resolv.conf -> /run/systemd/resolve/resolv.conf:

```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.1
nameserver 192.168.88.1
nameserver 202.171.191.10
```

Shouldn't my `/etc/resolv.conf` be pointing to the same list of nameservers? I want forward all DNS queries to dnsmasq which is on 127.0.0.1. And my dig currently shows the data being received from 127.0.0.53, which is systemd-resolvd's stub listener.

**Comment by CMCDragonkai** [comment]
Do you think this is because of `useNetworkd`? Could that be the problem, it is described as experimental.

**Comment by CMCDragonkai** [comment]
After disabling useNetworkd, this is the result.

`/etc/resolv.conf`:

```
# Generated by resolvconf
nameserver 127.0.0.1
options edns0
```

`/etc/dnsmasq-resolv.conf`:

```
# Generated by resolvconf
nameserver 192.168.88.1
nameserver 202.171.191.10
```

Running dig now shows that it's using dnsmasq 127.0.0.1 instead of systemd-resolvd 127.0.0.53.

So while one thing got fixed above, another thing is still confusing as to how I'm supposed to get useNetworkd is actually use dnsmasq which is on 127.0.0.1. Is it really necessary to also set `networking.nameservers = [ "127.0.0.1" ];`? I'm still not sure about the interaction between all these services from all these options and how this affects the /etc/resolv.conf and /etc/dnsmasq-resolv.conf. This is all quite complex.
