### ISSUE TITLE
cabal2nix unusable from within a nix-shell

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#25717]
## Issue description
cabal2nix uses nix-prefetch-url which is unusable within a shell (or inside runCommand if we're doing something gross)

```
[nix-shell:~/programming/alphasheets/nix]$ cabal2nix https://github.com/qrilka/xlsx.git
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
Initialized empty Git repository in /run/user/1000/git-checkout-tmp-v8NioZ1R/xlsx/.git/
remote: Counting objects: 63, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 63 (delta 1), reused 22 (delta 0), pack-reused 0
Unpacking objects: 100% (63/63), done.
From https://github.com/qrilka/xlsx
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
abort: HTTP Error 406: Not Acceptable

^Csvn: E200015: Caught signal
failed to open trace file: [Errno 2] No such file or directory: ':/.bzr.log'
Not checking SSL certificate for github.com.
bzr: ERROR: Not a branch: "https://github.com/qrilka/xlsx.git/".
*** f
```

### Steps to reproduce
Seen above

## Technical details
```
{
  "owner": "NixOS",
  "repo": "nixpkgs-channels",
  "rev": "09c91f5fea73746c2ea85b37834e7ec450923d18",
  "sha256": "1gxcz8hcq57b1gra91skqhcw2h9ifq9y3bgibhykfmszf0wmjsjv"
}
```

**Comment by Fuuzetsu** [comment]
work-around: set `NIX_REMOTE="daemon"`

**Comment by peti** [comment]
This issue is difficult to fix. `cabal2nix` downloads the source code of those packages it needs to convert so that it can determine the hash of the given package. Now, we use the `nix-prefetch-xxx` scripts to do that, because these tools have the added benefit of inserting these downloads into the store, therefore they don't need to be downloaded again when the generated Nix expression is eventually built.

The downside is, of course, that these programs don't work without a functioning Nix installation.

If we would like to make sure that `cabal2nix` can do these things without Nix, then we'd have to implement the appropriate downloaders ourselves and add them to the executable, so that it works stand-alone. Of course, this would also lose the neat caching feature.

Personally, I fee that it's reasonable to assume that someone running `cabal2nix` has a working Nix installation, so I'm not particularly motivated to make that change. Also, I want to spend my time hacking on this tool worrying about how to map Cabal to Nix. I'd rather not spend my time worrying about how to download remote code archives and repos using half a dozen VCS systems.

Anyhow, these are my 2 cents. I'm not sure how other see this?

Maybe the answer is to document the need for `NIX_REMOTE="daemon"` somewhere?

**Comment by Fuuzetsu** [comment]
Perhaps I should have outlined my use-case as motivation.

Currently we have a Haskell project that developers use stack on. However as we all know, as far as nix is concerned, stack-things are just blobs. Notably if you want to enable developers to use stack but want to use nix for some things (deploys, CI, builds), you have to meet half way somehow.

I met half way like this. Start with an LTS package set matching LTS package set used in project. This is easy enough, nixpkgs does this already. Stack has a feature where you can however stray from this LTS package set and specify packages with specific versions from Hackage. Question is how to accommodate for this without developers having to change nix expressions. My nix solution is as follows.

* `runCommand` a Haskell program that parses stack.yaml, extracts these versions and spits out expressions that are themselves `runCommand`
* in these `runCommand`s call cabal2nix on those packages and make $out the generated expression. Indeed I set `NIX_REMOTE = "daemon";` in the `env` of this runCommand as necessary.
* in my package set my overrides just become `haskellPackages.callPackage run-command-output-expression`

However this is not enough. Even if NIX_REMOTE=daemon, nix-daemon might not be running. In my experience with developers so far, it's not.

There are couple of ways forward here:
* document NIX_REMOTE and nix-daemon requirement: I think this is quite bad because cabal2nix just won't work in some use cases without it
* modify cabal2nix such that it doesn't use nix-prefetch-url (if given some flag): we lose cache of the few MBs the Haskell package might be but everything works regardless of env
* modify nix-prefetch-* so that it does not copy to the store if given some flag and allow cabal2nix make use of that functionality

My favourite is the second option but I understand your reasoning for not wanting to do that too. Last option would be nice but depending on implementation, the most work.

I hope you can at least see why this is a problem: `nix-build` suddenly becomes "hey why doesn't it work, I didn't read the doc, make it work" or some ugly wrapper scripts (with same issue).

In the end it's your call.

**Comment by peti** [comment]
@Fuuzetsu, are you aware of the `callHackage` function? If you run

    $ nix-build -E 'with import <nixpkgs> {}; haskellPackages.callHackage "hsdns" "1.0" {}'

then you'll automatically get a compiled `hsdns-1.0`, or whatever other package you want. `callHackage` gives you full access to all of Hackage.

There's also `callCabal2nix` and any other goodies in `pkgs/development/haskell-modules/make-package-set.nix`.

Maybe that helps?

**Comment by Fuuzetsu** [comment]
I did not know of these things, sounds useful, will check it out

**Comment by domenkozar** [comment]
So following is true on my NixOS using Nix 1.11.10:

```
$ nix-shell -p bash --run "echo $NIX_REMOTE"
daemon
```

**Comment by Fuuzetsu** [comment]
it's not true for developers withoutNixOS at least by default

**Comment by peti** [comment]
> It's not true for developers without NixOS at least by default.

People who install Nix and the `nix-daemon` on a non-NixOS host system ought to make sure that their user shells are  configured correctly, IMHO, i.e. by means of `/etc/profile` or other, similar mechanisms. I don't believe that configuring `nix-shell`is the responsibility of cabal2nix, nor do I believe that cabal2nix should jump through hoops to function in an incorrectly configured environment.

**Comment by Fuuzetsu** [comment]
If it's not a usecase you want to support then feel free to close as WONTFIX.

**Comment by domenkozar** [comment]
It could at least provide a user message when `NIX_REMOTE` is not correctly set to instruct what action should be taken.

**Comment by peti** [comment]
Well, I guess `nix-prefetch-url` could suggest setting `NIX_REMOTE` if it runs into permission problems accessing the store. I don't think `cabal2nix` should deal with this issue.
