### ISSUE TITLE
UX - virt-manager and dconf on non-gnome desktops

### ISSUE THREAD

**Issue by the-furry-hubofeverything** [NixOS/nixpkgs#257171]
## Issue description
I've collected multiple issues regarding `virt-manager` not being able to save its settings due to `programs.dconf.enable = true;` wasn't set. (Sorted from most recent to least, #255837 #67736 #52777 #42433  #11844 #2448) 

This problem has been happening since 2014, spanning almost ten years. 

To my knowledge, because Gnome requires dconf, this option isn't needed to be set on Gnome. Several people suggested to have dconf as a dependency to `virt-manager`, but as a response from https://github.com/NixOS/nixpkgs/issues/42433#issuecomment-419614845 mentioned - 

>  gnome3.dconf is a system service that needs to be added to services.dbus.packages by your desktop environment. If you create your own environment, you will need to add it yourself (adding programs.dconf.enable = true; to configuration.nix should work). Nix does not contain a mechanism for representing a dependency on a service.

Under almost every issue mentioned ideas to improve UX (except #11844 which was marked as a duplicate of #2448), but as far as I know, there's no progress. 

Also, to the best of my knowledge, there's also no mention of this problem in the NixOS manual. The line is included in [nixos.wiki](https://nixos.wiki/wiki/Virt-manager), but with no explanation as to why.

## Some ideas to explore

- Have `programs.dconf.enable = true;` inside virt-manager by making a `programs.virt-manager.enable` option 
  - https://github.com/NixOS/nixpkgs/issues/2448#issuecomment-1685118080, https://github.com/NixOS/nixpkgs/issues/67736#issuecomment-59752161
- Include some sort of warning when building the nixos configuration when dconf is not detected on system 
  - https://github.com/NixOS/nixpkgs/issues/52777#issuecomment-449866799
- Add documentation in the NixOS manual to set `programs.dconf.enable = true;`

@qknight @fpletz @globin @offlinehacker

**Comment by bjornfor** [comment]
> Have programs.dconf.enable = true; inside virt-manager by making a programs.virt-manager.enable option

+1
