### ISSUE TITLE
Firefox plugin icedtea/jre stopped working

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#25710]
## Issue description
I have
```
{
  allowUnfree = true;
  firefox.jre = true;
  firefox.enableAdobeFlash = true;
...
```
```
$ nix-env -qaP --description firefox
nixos.firefox-esr    firefox-52.1.0esr  A web browser built from Firefox Extended Support Release source tree (with plugins: flashplayer-25.0.0.148, oraclejre-with-plugin-8u131)
nixpkgs.firefox-esr  firefox-52.1.1esr  A web browser built from Firefox Extended Support Release source tree (with plugins: flashplayer-25.0.0.171, oraclejre-with-plugin-8u131)
nixos.firefox        firefox-53.0       A web browser built from Firefox source tree (with plugins: flashplayer-25.0.0.148, oraclejre-with-plugin-8u131)
nixpkgs.firefox      firefox-53.0.2     A web browser built from Firefox source tree (with plugins: flashplayer-25.0.0.171, oraclejre-with-plugin-8u131)
```

I install firefox via `buildEnv`:
```
with import <nixpkgs> {};
buildEnv {
  name = "danbst-tools-env";
  ignoreCollisions = true;
  paths = [
    firefox
    ....
  ];
}
```
But JRE plugin isn't recognized by Firefox, about:plugins shows:
- OpenH264 Video Codec provided by Cisco Systems, Inc.
- Shockwave Flash

Same for icedtea - it isn't recognized.

This happend not a long time ago, I still have profile with working Icedtea plugin (firefox version Mozilla Firefox 52.0.2)

### Steps to reproduce
Install firefox with jre (or icedtea) and flash plugins. Then go to about:plugins

## Technical details

* System: 17.09.pre.7f3b857 (Hummingbird)
* Nix version: 1.11.9
* Nixpkgs version: "17.09pre106916.c5badb123a"
* Sandboxing enabled: false

**Comment by tohl** [comment]
You need firefox-esr.  Web browsers don't support plugins like java
anymore.

**Comment by danbst** [comment]
If that's official, would be nice to see a warning or even abort build. Meanwhile, firefox-esr works, thank you.

**Comment by gentoofreak** [comment]
See 1st sentence in "changed" section:
https://www.mozilla.org/en-US/firefox/52.0/releasenotes/

And the announcement from 2015:
https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/

**Comment by danbst** [comment]
I've solved my problem in a complex way 
https://gist.github.com/danbst/30165b59996fb403068c74a95b108d6f
