### ISSUE TITLE
Syncthing module does not support unix sockets for `guiAddress`

### ISSUE THREAD

**Issue by stelcodes** [NixOS/nixpkgs#257152]
### Describe the bug

Syncthing supports running the GUI over a unix socket instead of a port on localhost. Unix sockets are much more secure because they can use typical linux permissions to limit access. I believe the syncthing module could support unix sockets by changing the `curl` commands to use the `--unix-socket` flag that curl provides. There could be an extra option to indicate whether the address is a unix socket, but we might be able to get away with just testing whether the first character in the address is a `/`.

### Steps To Reproduce

1. Try to set `services.syncthing.guiAddress = "/tmp/st.sock";` and notice how it doesn't work.

### Expected behavior

Syncthing module supports running the GUI over a unix socket.

### Additional context

Curl has supported sending requests to unix sockets for 9 years now so I think it's safe to rely on this feature.
https://github.com/curl/curl/releases/tag/curl-7_40_0

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.11 (Tapir), 23.11.20230915.ace5093`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos"`
 - channels(stel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Majiir** [comment]
There's a PR up for this: https://github.com/NixOS/nixpkgs/pull/247343

**Comment by KucharczykL** [comment]
The PR has been merged so this should probably be closed?
