### ISSUE TITLE
lubuntu 12.04 lightdm login to linux domain problem

### ISSUE THREAD

**Issue by alexrodgt** [NixOS/nixpkgs#25711]
## Issue description
every time i startup the computer, lightdm login shows up, the first few times I try to login to domain it wont login and no error message displayed just prompts again for credentials.  I have to wait 2 to 3 minutes for the login to be successful.

Cheking the log (var/log/auth.log) i can see that on the failed attempts, lightdm fails to send the user to the domain:

lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost= 

while waiting 2 or 3 minutes, on the succesful login, the user is passed on the call:

pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "v.jimenez"
pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost=  user=v.jimenez

### Here are de logs for this attempts

May 11 11:29:18 it-oca575 lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost= 
May 11 11:29:18 it-oca575 lightdm: pam_winbind(lightdm:auth): getting password (0x00000388)
May 11 11:29:18 it-oca575 lightdm: pam_winbind(lightdm:auth): pam_get_item returned a password
May 11 11:29:20 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:20 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:20 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:20 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:20 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:20 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:21 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:21 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:21 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:21 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:21 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:21 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:26 it-oca575 lightdm: pam_unix(lightdm:auth): check pass; user unknown
May 11 11:29:26 it-oca575 lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost= 
May 11 11:29:26 it-oca575 lightdm: pam_winbind(lightdm:auth): getting password (0x00000388)
May 11 11:29:26 it-oca575 lightdm: pam_winbind(lightdm:auth): pam_get_item returned a password
May 11 11:29:28 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:28 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:28 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:28 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:28 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:28 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:31 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:31 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:31 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:31 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:31 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:31 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:37 it-oca575 lightdm: pam_unix(lightdm:auth): check pass; user unknown
May 11 11:29:37 it-oca575 lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost= 
May 11 11:29:37 it-oca575 lightdm: pam_winbind(lightdm:auth): getting password (0x00000388)
May 11 11:29:37 it-oca575 lightdm: pam_winbind(lightdm:auth): pam_get_item returned a password
May 11 11:29:39 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:39 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:39 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:39 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:39 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:39 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:41 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:41 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:41 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:41 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:41 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:41 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:49 it-oca575 lightdm: pam_unix(lightdm:auth): check pass; user unknown
May 11 11:29:49 it-oca575 lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost= 
May 11 11:29:49 it-oca575 lightdm: pam_winbind(lightdm:auth): getting password (0x00000388)
May 11 11:29:49 it-oca575 lightdm: pam_winbind(lightdm:auth): pam_get_item returned a password
May 11 11:29:51 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:51 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:51 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:51 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:51 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:51 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:29:59 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:29:59 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:29:59 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:29:59 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:29:59 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:29:59 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:30:03 it-oca575 lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "r.torres"
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:30:05 it-oca575 lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "it"
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:30:05 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:30:05 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:30:10 it-oca575 lightdm: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "v.jimenez"
May 11 11:30:12 it-oca575 lightdm: pam_unix(lightdm:auth): authentication failure; logname= uid=0 euid=0 tty=:0 ruser= rhost=  user=v.jimenez
May 11 11:30:12 it-oca575 lightdm: pam_winbind(lightdm:auth): getting password (0x00000388)
May 11 11:30:12 it-oca575 lightdm: pam_winbind(lightdm:auth): pam_get_item returned a password
May 11 11:30:13 it-oca575 lightdm: pam_winbind(lightdm:auth): user 'v.jimenez' granted access
May 11 11:30:13 it-oca575 lightdm: pam_unix(lightdm:session): session closed for user lightdm
May 11 11:30:16 it-oca575 lightdm: pam_unix(lightdm:session): session opened for user v.jimenez by (uid=0)
May 11 11:30:16 it-oca575 lightdm: pam_ck_connector(lightdm:session): nox11 mode, ignoring PAM_TTY :0
May 11 11:30:17 it-oca575 gnome-keyring-daemon[1505]: couldn't set environment variable in session: The name org.gnome.SessionManager was not provided by any .service files
May 11 11:30:17 it-oca575 gnome-keyring-daemon[1505]: couldn't set environment variable in session: The name org.gnome.SessionManager was not provided by any .service files
May 11 11:30:19 it-oca575 polkitd(authority=local): Registered Authentication Agent for unix-session:/org/freedesktop/ConsoleKit/Session2 (system bus name :1.16 [/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1], object path /org/gnome/PolicyKit1/AuthenticationAgent, locale es_GT.UTF-8)
May 11 11:31:27 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:31:27 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:31:27 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:31:27 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:31:27 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:31:27 it-oca575 lightdm: PAM adding faulty module: pam_mount.so
May 11 11:31:27 it-oca575 lightdm: pam_unix(lightdm:session): session opened for user lightdm by (uid=0)
May 11 11:31:27 it-oca575 lightdm: pam_ck_connector(lightdm:session): nox11 mode, ignoring PAM_TTY :0
May 11 11:31:28 it-oca575 dbus[549]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.11" (uid=103 pid=1085 comm="/usr/sbin/lightdm-gtk-greeter ") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination=":1.9" (uid=0 pid=1004 comm="/usr/sbin/console-kit-daemon --no-daemon ")
May 11 11:31:28 it-oca575 lightdm: PAM unable to dlopen(pam_cap.so): /lib/security/pam_cap.so: cannot open shared object file: No such file or directory
May 11 11:31:28 it-oca575 lightdm: PAM adding faulty module: pam_cap.so
May 11 11:31:28 it-oca575 lightdm: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
May 11 11:31:28 it-oca575 lightdm: PAM adding faulty module: pam_gnome_keyring.so
May 11 11:31:28 it-oca575 lightdm: PAM unable to dlopen(pam_mount.so): /lib/security/pam_mount.so: cannot open shared object file: No such file or directory
May 11 11:31:28 it-oca575 lightdm: PAM adding faulty module: pam_mount.so

## Technical details

* System: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"

**Comment by mmahut** [comment]
Are there any updates on this issue, please
