### ISSUE TITLE
NVMe Issues on recent kernels.

### ISSUE THREAD

**Issue by fabianhjr** [NixOS/nixpkgs#257159]
### Describe the bug

/dev/nvme0 becomes unavailable and causes / to unmount leading to an unresponsive system. 

<details><summary>Smartctl output</summary>

```
sudo smartctl -a /dev/nvme0
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.5] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Force MP600
Serial Number:                      [REDACTED]
Firmware Version:                   EGFM11.0
PCI Vendor/Subsystem ID:            0x1987
IEEE OUI Identifier:                0x6479a7
Total NVM Capacity:                 2,000,398,934,016 [2.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            6479a7 2161894542
Local Time is:                      Sun Sep 24 17:44:05 2023 CST
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005d):     Comp DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x08):         Telmtry_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     70 Celsius
Critical Comp. Temp. Threshold:     90 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +    10.73W       -        -    0  0  0  0        0       0
 1 +     7.69W       -        -    1  1  1  1        0       0
 2 +     6.18W       -        -    2  2  2  2        0       0
 3 -   0.0490W       -        -    3  3  3  3     2000    2000
 4 -   0.0018W       -        -    4  4  4  4    25000   25000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         2
 1 -    4096       0         1

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        55 Celsius
Available Spare:                    100%
Available Spare Threshold:          5%
Percentage Used:                    16%
Data Units Read:                    339,743,326 [173 TB]
Data Units Written:                 439,068,487 [224 TB]
Host Read Commands:                 11,765,950,011
Host Write Commands:                6,832,718,155
Controller Busy Time:               17,515
Power Cycles:                       2,923
Power On Hours:                     18,937
Unsafe Shutdowns:                   435
Media and Data Integrity Errors:    0
Error Information Log Entries:      2,690
Warning  Comp. Temperature Time:    59
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, 16 of 63 entries)
Num   ErrCount  SQId   CmdId  Status  PELoc          LBA  NSID    VS
  0       2690     0  0x0008  0x4004  0x028            0     0     -
```
</details>

### Steps To Reproduce

NVMe + 6.5 kernel (either on main branch, staging-next branch, or staging-next + gnome branch)

### Expected behavior
Not like this UnU

### Screenshots

<details><summary>Error messages before rebooting</summary>

![IMG20230924173611](https://github.com/NixOS/nixpkgs/assets/303897/23c11adc-9acb-4cb0-8782-70883f86c52b)

![IMG20230924173707](https://github.com/NixOS/nixpkgs/assets/303897/78668b26-eed7-4bed-a591-7ff81536ac63)
</details>

### Additional context

Related to #253418

Related to https://bbs.archlinux.org/viewtopic.php?id=288316
Related to https://discussion.fedoraproject.org/t/laptop-does-not-show-luks-password-prompt-as-nvme-fails-with-kernel-6-4-11-kernel-6-4-12/88622
Related to https://lore.kernel.org/lkml/30b69186-5a6e-4f53-b24c-2221926fc3b4@sapience.com/T/
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2232838

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.git.49bb21b4a2e5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos, nixos-small"`
 - channels(fabian): `"home-manager, nixos-19.03-19.03, nixos-19.09-19.09, nixos-20.03-20.03, nixos-20.09-20.09, nixos-21.05-21.05, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

hw-probe: https://linux-hardware.org/?probe=007bb33fbf

**Comment by fabianhjr** [comment]
Already reported on NixOS discourse: https://discourse.nixos.org/t/nvme-drive-not-detecting-after-calameres-initiates/32108

**Comment by fabianhjr** [comment]
It's annoying to capture but finally managed to get more info

![image](https://github.com/NixOS/nixpkgs/assets/303897/a64db929-e69e-47d5-ae63-21ca0fcd93e3)
![image](https://github.com/NixOS/nixpkgs/assets/303897/5d023157-1b5c-4cde-b4c6-d750ace02a64)

**Comment by blitz** [comment]
Should we revert the patch mentioned here or wait for a new upstream kernel release? https://lkml.org/lkml/2023/8/16/1363

**Comment by fabianhjr** [comment]
Seems like 6.5.6-rc1 fixed the issue for me, still doing some testing.

Besides the revert already on nixos there are 2 commits regarding nvme:

- a null pointer dereference, and
- something around no NUMA nodes and NVMe

https://lore.kernel.org/stable/20231005013330.6499-1-sj@kernel.org/T/#mb1a49d27e5143194a8dc113678be83a26918c217

**Comment by fabianhjr** [comment]
nvm still crashing

**Comment by lf-** [comment]
> Should we revert the patch mentioned here or wait for a new upstream kernel release? https://lkml.org/lkml/2023/8/16/1363

Hey they fixed this one already. I believe y'all have a different bug. What machine is this on?

**Comment by fabianhjr** [comment]
hw-probe: https://linux-hardware.org/?probe=007bb33fbf

6.5.6 does seem like it did fix it.

**Comment by lf-** [comment]
Ok yes it's definitely a different bug. But I'm glad it's fixed I guess.

**Comment by Hubro** [comment]
Still happens to me on 6.5.6.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.6, NixOS, 23.05 (Stoat), 23.05.4112.5a237aecb572`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

![Error](https://github.com/NixOS/nixpkgs/assets/597206/297d6e97-6a96-4c27-a745-38a5959735a0)

Symptoms are the same as reported by @fabianhjr, root filesystem is remounted as read-only, applications crash and system becomes unresponsive. PC must be forcefully shut down with the power button. This happens at least daily, and almost always while I'm away from the PC for a while, which makes the message "Does your device have a faulty power saving mode enabled?" message sound like it's probably onto something.

---

<details><summary><code>$ nix-shell -p smartmontools --run "sudo smartctl -a /dev/nvme0"</code></summary>

```
nix-shell -p smartmontools --run "sudo smartctl -a /dev/nvme0"
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.5.6] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       INTEL SSDPEKKW256G7
Serial Number:                      BTPY64540C11256D
Firmware Version:                   PSF100C
PCI Vendor/Subsystem ID:            0x8086
IEEE OUI Identifier:                0x5cd2e4
Controller ID:                      1
NVMe Version:                       1.2
Number of Namespaces:               1
Namespace 1 Size/Capacity:          256,060,514,304 [256 GB]
Namespace 1 Formatted LBA Size:     512
Local Time is:                      Wed Oct 11 21:10:46 2023 CEST
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0006):   Format Frmw_DL
Optional NVM Commands (0x001e):     Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat
Log Page Attributes (0x03):         S/H_per_NS Cmd_Eff_Lg
Maximum Data Transfer Size:         32 Pages
Warning  Comp. Temp. Threshold:     70 Celsius
Critical Comp. Temp. Threshold:     80 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     9.00W       -        -    0  0  0  0        5       5
 1 +     4.60W       -        -    1  1  1  1       30      30
 2 +     3.80W       -        -    2  2  2  2       30      30
 3 -   0.0700W       -        -    3  3  3  3    10000     300
 4 -   0.0050W       -        -    4  4  4  4     2000   10000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        33 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    3%
Data Units Read:                    51,873,813 [26.5 TB]
Data Units Written:                 16,447,878 [8.42 TB]
Host Read Commands:                 997,282,540
Host Write Commands:                351,517,300
Controller Busy Time:               2,492
Power Cycles:                       296
Power On Hours:                     9,876
Unsafe Shutdowns:                   60
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    1103
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, 16 of 64 entries)
No Errors Logged
```

</details>

**Comment by lf-** [comment]
@Hubro which machine is this? I expect it's a firmware bug in the motherboard most likely.

**Comment by Hubro** [comment]
> @Hubro which machine is this? I expect it's a firmware bug in the motherboard most likely.

It's an [ASRock A520M-ITX/ac](https://www.asrock.com/mb/AMD/A520M-ITXac/index.asp).

I tried booting with the kernel parameters suggested in the error log now, hopefully that does something.

**Comment by fabianhjr** [comment]
If you are using LUKS something that helped me reduce the frequency of errors (mitigation) was enabling triming (fstrim) in NixOS options

Also, it seems like a relative new drive but has a very high warning temperature time; errors might be thermal related. (Additionally the command and status errors are different, your logs indicate that it was during writes)

**Comment by Hubro** [comment]
I don't use LUKS. The temperature warnings must be old, because I haven't caught the SSD go above 36 celsius in the current PC location, so I don't think the errors are temperature related.

I let the PC sit over night with the suggested kernel parameters, and it hasn't crashed yet :crossed_fingers:
