### ISSUE TITLE
Update request: graalvm-ce 22.3.1 -> jdk-21.0.0

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#257292]
- Package name: `graalvm-ce`
- Latest released version:

- Current version on the unstable channel: 22.3.1
- Current version on the stable/release channel: 22.3.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bennyandresen @hlolli @glittershark @babariviere @ericdallo @thiagokokada (of course :P)

-----

Note for maintainers: Please tag this issue in your PR.

-----

So I took an early look at this bump and there is a bunch of changes upstream that we will need to adapt. To start they changed the way they do versions so this is why it seems that we are "downgrading" the version instead of upgrading: the versions now match the JDK version that GraalVM is based on. Also, thanks to this change all URLs are changed.

Also, each of the sub-products (e.g.: GraalPy) are now released independently from the GraalVM main releases and have their own version (it is on 23.1.0 right now, but I expect that they diverge in the future). They also seem to be self contained and not rely in having GraalVM installed anymore, so we can just stop bundling all the packages together in a "super" derivation as we do right now and just split each sub-product in its own package. Thanks to this change, they also don't ship `jar` anymore, they are all in `.tar.bz2` format that should make our lifes easier.

**Comment by diegobfernandez** [comment]
Hello @thi
