### ISSUE TITLE
`qt5.qtbase` build failure on darwin

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#25723]
## Issue description
`qt5.qtbase` stopped building on darwin recently. The errors are of the form `error: no member named 'signbit' in the global namespace` (with various substitutions for the `signbit` part). This looks a lot like an [issue](https://github.com/Andersbakken/rtags/issues/937) that @copumpkin both discovered and apparently resolved, but I do not know how to apply the lessons of that bug report to this situation.

### Steps to reproduce
Consult the hydra build log for an example.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by periklis** [comment]
@acowley can you check with NIX_DEBUG if the stdlibc++ is listed correctly?

**Comment by periklis** [comment]
i suppose this cmath error is triggered by the compiler switch -std=c++11 in the mkspecs of qmake/qt for the mac plattform. We heavily sed the files in qtbase/default.nix L103-105. From there on you can play with the include path ordering of libc++ and c-std-headers.

**Comment by acowley** [comment]
I figured I'd open the issue as, unless I'm misremembering, something changed to break this build, so maybe there's a common fix we can apply here without investing too much time in the autopsy, or, better, maybe there's something we should do to the stdenv to prevent this. When @copumpkin ran into this in the linked issue he was working on `rtags`, but I don't see anything in his commit on that derivation that obviously addresses this problem. This makes me think that there's something in the update to llvm-4 that jostled this build, but I haven't had time to look into it yet.

**Comment by periklis** [comment]
Ok, i evaluated the code of our stdenv libc++ and it uses the same include_next hack like gcc/stdlibc++. This hack protect c++ userland programmers from masking issues when they use either `<cmath>` or `<math.h>` in their code to default on the headers of the libc++ and not on the system header `math.h`. Thus, the solution of qt5.qtbase should be to keep an eye on the qmake build system not to falsely include the system header `math.h` before libc++ is included.

**Comment by periklis** [comment]
I think i found the error. We compile with two different STL libraries on our include search paths.
1. First we include `/nix/store/fhzn73xw9azi28zrpkk59y0qw0mbsdf9-MacOS_SDK-10.10/include` which is the GNU libstdc++ v4.2.1. Afaik, this is the old libstdc++ from the pre-llvm-time of darwin and that is a time before C++11. Thus, the old buggy cheater-way piggy-packing on the system c-library for stuff like stdlib, math, stdio (See my link for an deeper explanation to the article of John Wakely above).

2. Second we include `/nix/store/m2yr2w7fpwhcf912lbkz5dgg6rbszs9b-libc++-4.0.0/include/c++/v1` which is the one of our stdenv and for sure the C++11 compatible one, which QT expects for C++11 builds. (Afaik, we could get a c++11 build with qt and a newer GNU libstdc++, too, but let's stick with the llvm one of our stdenv).

Our current search path order:
```
 -isystem
  /nix/store/fhzn73xw9azi28zrpkk59y0qw0mbsdf9-MacOS_SDK-10.10/include
  -F/nix/store/fhzn73xw9azi28zrpkk59y0qw0mbsdf9-MacOS_SDK-10.10/Library/Frameworks
  -isystem
  /nix/store/szr4ngmviqlbk40aphlgdf1lwrppq41j-libiconv-osx-10.11.6/include
  -DNIXPKGS_QPA_PLATFORM_PLUGIN_PATH="/nix/store/22a7g9kj4l30g1vq3m002gacxcfl1yhm-qtbase-5.8.0/lib/qt5/plugins"
  -isystem
  /nix/store/m2yr2w7fpwhcf912lbkz5dgg6rbszs9b-libc++-4.0.0/include/c++/v1
```

The question is:
Do we fix this by setting the libc++ first and the macos-sdk-libstdc++ second in the include search paths in our compiler wrapper or should we fix this per package? (cc: @copumpkin)

**Comment by LnL7** [comment]
The MacOS_SDK-10.10 come from `darwin.apple_sdk.sdk`, using that often results in issues like this.

**Comment by periklis** [comment]
i see. i thought @copumpkin cherry-picked that on master.
