### ISSUE TITLE
Build failure: nushellPlugin.query, nushellPlugin.formats and nushellPlugin.gstat

### ISSUE THREAD

**Issue by eboskma** [NixOS/nixpkgs#257218]
### Steps To Reproduce

1. build `nushellPlugin.query` / `nushellPlugin.formats` / `nushellPlugin.gstat`

### Build log

All plugins show the same error with a different hash when building, I only included the log from `nushellPlugin.gstat`:
```
$ nix build .#nushellPlugins.gstat
error: hash mismatch in fixed-output derivation '/nix/store/njkm7jm39lb1f6fi7dnc9dv2zbcx97sg-nushell_plugin_gstat-0.85.0-vendor.tar.gz.drv':
         specified: sha256-Fj70uKYzEKxeZeNrqlwM7ZFJ+K1tz10RqLndrdY40CE=
            got:    sha256-6luY3SIRRd9vaY9KIJcj8Q974FW0LtAvRjVpdpzkdLo=
error: 1 dependencies of derivation '/nix/store/l9xi8mhbhaxlx4kbdvsvw9ks5xhrl3gk-nushell_plugin_gstat-0.85.0.drv' failed to build
```

### Additional context

The `cargoHash`es were updated with #256330 but the plugins fail with a hash mismatch on two machines I tried it on. Both are x86_64 machines running NixOS unstable. I can make a PR to update the hashes, but I want to make sure I'm not missing something. 

### Notify maintainers

@viraptor @mrkkrp @happysalada 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4, NixOS, 23.11 (Tapir), 23.11.20230922.e35dcc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/cz973qsjldbw4x7fx0rwcvhr9k645vz2-source`
```

**Comment by happysalada** [comment]
I've just opened a PR to fix this, if you have time to review, it would be great, otherwise no worries. I won't wait too long before merging since everything is broken.

**Comment by eboskma** [comment]
Looks good to me, those are the same hashes I got.
