### ISSUE TITLE
skypeforlinux hash mismatch

### ISSUE THREAD

**Issue by phile314-fh** [NixOS/nixpkgs#25729]
## Issue description

skypeforlinux doesn't build:

<pre>
output path ‘/nix/store/xpd37szphzwvryjghp2z4kg7bjgvgmqz-skypeforlinux-64.deb’ has sha256 hash ‘1dwyj5wm2amkysbnzxsskq6sl7rbqggm6n4sabnq7wd5xnbq4i06’ when ‘18v861x0n2q2jaglap8193sia476dwkwr0ccfzl29mi5ijma24ml’ was expected
</pre>

### Steps to reproduce

``nix-build -A skypeforlinux``

## Technical details

* System: 17.09.git.d282d6b (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09.git.7746327080M
* Sandboxing enabled: No

cc @PanAeon

**Comment by Mic92** [comment]
Oh snap. It is not a stable url:

```
      fetchurl {                                                                                                                                                             
        url = "https://repo.skype.com/latest/skypeforlinux-64.deb";                                                                                                          
        sha256 = "18v861x0n2q2jaglap8193sia476dwkwr0ccfzl29mi5ijma24ml";                                                                                                     
      }
```

We need a more stable mirror here. Otherwise it will always break.

**Comment by Mic92** [comment]
Should be taken from here: https://repo.skype.com/deb/pool/main/s/skypeforlinux/

**Comment by phile314-fh** [comment]
Thank you for fixing this, works for me now.
