### ISSUE TITLE
The FDK AAC codec is under an incorrect license

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#257324]
### Describe the bug
The FDK AAC codec is under the Apache License and not Non-free Redistributable as would be expected from its actual license text.

This is probably because the library that is being used to get the codec (opencore-amr) is under the Apache License but the _FDK library_ is very much not.

### Expected behavior
Have the FDK codec under Non-free Redistributable, or ideally a variant that allows a cached executable to be distributed.

### Additional context
https://github.com/NixOS/nixpkgs/blob/715d72e967ec1dd5ecc71290ee072bcaf5181ed6/pkgs/development/libraries/fdk-aac/default.nix#L23

### Notify maintainers

@codyopel

**Comment by FavoritoHJS** [comment]
Also paging @OPNA2608 @trofi since the maintainer seems inactive.

**Comment by trofi** [comment]
https://fedoraproject.org/wiki/Licensing/FDK-AAC and https://en.wikipedia.org/wiki/Fraunhofer_FDK_AAC say it's a custom free license.

Should be a matter of adding an entry in https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix and referring in the file.

Do you want to give it a go?

**Comment by FavoritoHJS** [comment]
done, see #257338. just be warned, i haven't touched this side of development at all so be prepared for disaster

**Comment by OPNA2608** [comment]
> https://fedoraproject.org/wiki/Licensing/FDK-AAC and https://en.wikipedia.org/wiki/Fraunhofer_FDK_AAC say it's a custom free license.

Debian considers it non-free according to their criteria: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=694257

> I've tried to get a
> clarification about whether or not the license allows a commercial
> software, with or without access to the (possibly modified) source
> code and the answer was basically "we cannot answer your question".
> 
> Thus, I believe that the package will have to go to non-free.

I don't know what our definition of "free" is or if we follow anyone else's system in that regard though.

**Comment by vcunat** [comment]
> ideally a variant that allows a cached executable to be distributed

Current policy for our infra is not to build, test, or cache any unfree packages (even if redistributable).

**Comment by vcunat** [comment]
It's quite rare for definitions of "free" to disagree.  By which I mean e.g. stance of Debian, OSI and FSF.  I don't think we have a policy for such cases (yet).
