### ISSUE TITLE
Xmonad is broken

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#25730]
## Issue description

xmonad recompilation is broken

```
Error detected while loading xmonad configuration file: /home/nick/.xmonad/xmonad.hs
Failed to load interface for ‘Data.Default.Instances.Containers’
There are files missing in the ‘data-default-instances-containers-0.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
```

### Steps to reproduce

Issue `xmonad --recompile`

## Technical details

* System: 17.09pre107265.0afb6d789c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre107265.0afb6d789c"
* Sandboxing enabled: yes

This exact config compiles fine on my other nixos machine, at version 17.09pre106117.c90998d5cf

**Comment by Ma27** [comment]
would you mind showing is your nix expression to build XMonad (`services.xserver.windowManager.xserver` etc...)

I'm on `17.09pre107265.0afb6d789c (Hummingbird)` with Nix v1.11.9 and disabled sandboxing and `xmonad --recompile` works fine (I'm using XMonad on a daily basis and I didn't see any issues in the last weeks)

**Comment by NickHu** [comment]
I had actually broken something in my ghc config, I'll close this now

**Comment by r-raymond** [comment]
Mind sharing what you broke? I have the same problem on `nixos-18.03pre121706.b9347167822`

**Comment by Ma27** [comment]
could you please share your config with us?

And did your setup ever work? (just asking as I'd like to figure out if this is a newly introduced issue or a configuration mistake on your side :))

**Comment by r-raymond** [comment]
Sure. My config is

configuration.nix
```
  services.xserver = {
    enable = true;
    layout = "us";
    xkbOptions = "eurosign:e";
    #videoDrivers = [ "ati_unfree" ];  

    displayManager.sddm.enable = true;

    desktopManager = {
      #kde4.enable = true;
      #gnome3.enable = true;
      xterm.enable = false; 
      xfce.enable = true;
    };
    windowManager.xmonad = {
      enable = true;
      enableContribAndExtras = true;
    };
    windowManager.default = "xmonad";
  };
```

It did work before - in fact I'm using xmonad right now. I just can't recompile it anymore. Let's hope I figure this out before my binary breaks ^^
