### ISSUE TITLE
Update request: Rio 0.0.19 → 0.0.27

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#257334]
- Package name: rio
- Latest released version: 0.0.27

- Current version on the unstable channel: 0.0.19
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@otavio 
@oluceps 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by oluceps** [comment]
```
 > error: package `copa v0.0.20 (/build/source/copa)` cannot be built because it requires rustc 1.72.1 or newer, while the currently active rustc version is 1.72.0
```

Seems one of the dependence of `rio` depends on `rustc 1.72.1` which not entered master yet (see https://nixpk.gs/pr-tracker.html?pr=256310). I'll handle this once it gets ready.

**Comment by otavio** [comment]
Not sure why it requires it. Maybe removing this requirement?

**Comment by oluceps** [comment]
And it's an critical component that could not be remove.

**Comment by Nyabinary** [comment]
@otavio https://nixpk.gs/pr-tracker.html?pr=256310 1.72.1 merged into master

**Comment by zh4ngx** [comment]
:+1: Looking forward to this as well. Hopefully fixes https://github.com/raphamorim/rio/issues/233

**Comment by Nyabinary** [comment]
https://nixpk.gs/pr-tracker.html?pr=259989
Still not merged into master, merged into staging-next though.

**Comment by Nyabinary** [comment]
@otavio 1.73 has been merged into master.

**Comment by otavio** [comment]
@Nyabinary I sent the update 👍🏻
