### ISSUE TITLE
grsec fix kernel version

### ISSUE THREAD

**Issue by evrim** [NixOS/nixpkgs#25743]
## Issue description
Hello, 

How can I fix the kernel version and continue with the grsec kernel?

# nixos-rebuild switch
building Nix...
building the system configuration...
error: Upstream has ceased free support for grsecurity/PaX.

See https://grsecurity.net/passing_the_baton.php
and https://grsecurity.net/passing_the_baton_faq.php
for more information.

(use ‘--show-trace’ to show detailed location information)

## Technical details
* System: 17.03.1057.c545296adc (Gorilla)

**Comment by vcunat** [comment]
I suppose that would really only work for a limited time, as pinning to old kernel would stop you from receiving security updates to it...

**Comment by vcunat** [comment]
See also #25277.

**Comment by joachifm** [comment]
You *could* use https://github.com/minipli/linux-unofficial_grsec/tree/linux-4.9.x-unofficial_grsec but there's no telling how long that'll keep going.

**Comment by joachifm** [comment]
Also, there's the issue of bugs in grsec/PaX itself: who'd you report them to and who'd be qualified to fix them? There have been serious bugs before, there's no reason to believe the last public test patch is "perfect".

**Comment by mrobbetts** [comment]
I definitely see some value in offering the latest grsec-patched kernel version, at least for a while. Is it a big maintenance burden to do that?

**Comment by vcunat** [comment]
Note: if this is revived, we probably [shouldn't](https://grsecurity.net/passing_the_baton_faq.php) call it grsec(urity) anymore.

**Comment by evrim** [comment]
Hello @joachifm ,

Trying minipli kernel as you have suggested. I'm stuck at this plugin stuff. I've searched around and it seems you already have the experience, maybe you can help me. I see buildLinux/manual-config.nix has buildInputs = [gmp..] yet unable to find necessary headers.

make[1]: Leaving directory '/tmp/nix-build-linux-4.9.40.drv-1/build'
building
make flags: SHELL=/nix/store/7nyn92bnz2qhvwbb8l3pynj1lfiq6rl4-bash-4.4-p5/bin/bash O=$(buildRoot) ARCH=x86_64  KBUILD_BUILD_VERSION=1-NixOS bzImage vmlinux modules KBUILD_BUILD_TIMESTAMP=Thu Jan  1 00:00:01 UTC 1970
make[1]: Entering directory '/tmp/nix-build-linux-4.9.40.drv-1/build'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
  HOSTCC  scripts/basic/bin2c
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
  CHK     include/config/kernel.release
  UPD     include/config/kernel.release
  Using /tmp/nix-build-linux-4.9.40.drv-1/linux-unofficial_grsec-74213b1-src as source for kernel
  GEN     ./Makefile
  WRAP    arch/x86/include/generated/asm/clkdev.h
  WRAP    arch/x86/include/generated/asm/cputime.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  CC      arch/x86/purgatory/purgatory.o
  AS      arch/x86/purgatory/stack.o
  AS      arch/x86/purgatory/setup-x86_64.o
  CC      arch/x86/purgatory/sha256.o
  AS      arch/x86/purgatory/entry64.o
  CC      arch/x86/purgatory/string.o
  LD      arch/x86/purgatory/purgatory.ro
  BIN2C   arch/x86/purgatory/kexec-purgatory.c
In file included from /nix/store/4v7975ckk1gaiwvik0yh1pmw23lbyvgl-gcc-5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/plugin/include/gcc-plugin.h:28:0,
                 from /nix/store/4v7975ckk1gaiwvik0yh1pmw23lbyvgl-gcc-5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/plugin/include/plugin.h:23,
                 from /tmp/nix-build-linux-4.9.40.drv-1/linux-unofficial_grsec-74213b1-src/scripts/gcc-plugins/gcc-common.h:8,
                 from <stdin>:1:
/nix/store/4v7975ckk1gaiwvik0yh1pmw23lbyvgl-gcc-5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/plugin/include/system.h:662:17: fatal error: gmp.h: No such file or directory
compilation terminated.
Cannot use CONFIG_GCC_PLUGINS: your gcc installation does not support plugins, perhaps the necessary headers are missing?
PAX_MEMORY_STACKLEAK and other features will be less secure
make[1]: *** [scripts/Makefile.gcc-plugins:116: gcc-plugins-check] Error 1
make[1]: Leaving directory '/tmp/nix-build-linux-4.9.40.drv-1/build'
make: *** [Makefile:150: sub-make] Error 2
note: keeping build directory ‘/tmp/nix-build-linux-4.9.40.drv-1’

**Comment by NeQuissimus** [comment]
Not sure how much it helps @mrobbetts but we do have the Copperhead kernel in nixpkgs (https://github.com/copperhead/linux-hardened). They integrate and update regularly and a lot of changes are based on PaX/grsec (Repo says "Changes from PaX / grsecurity are marked as such")

**Comment by evrim** [comment]
I integrated minipli kernel (4.9.40-unofficial+grsec) using a custom module, compiling it right atm. I'll be able to tell more  this week, I hope.

**Comment by NeQuissimus** [comment]
Cool, curious to see how that goes :)

**Comment by evrim** [comment]
After fiddling with the computer, it decided to work.

$ uname -a
Linux hostname 4.9.40-unofficial+grsec #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
$ journalctl -k -f
-- Logs begin at Fri 2017-04-21 07:05:08 +03. --
Jul 31 18:52:02 hostname kernel: grsec: denied read of sensitive /proc/pid/maps entry via fd passed across exec by /nix/store/q1idzrdisw0ikqi4kvv7rlz8930kxkhl-firefox-unwrapped-54.0.1/lib/firefox-54.0.1/firefox[Web Content:1554] uid/euid:1000/1000 gid/egid:100/100, parent /nix/store/q1idzrdisw0ikqi4kvv7rlz8930kxkhl-firefox-unwrapped-54.0.1/lib/firefox-54.0.1/firefox[Gecko_IOThread:1375] uid/euid:1000/1000 gid/egid:100/100
Jul 31 18:52:02 hostname kernel: grsec: more alerts, logging disabled for 10 seconds

If #25208 is fixed, I'll be very happy. It takes ages to compile. 

What should we do now, revive?

**Comment by NeQuissimus** [comment]
You could just sent in a PR with a kernel derivation to that of Copperhead?!
It should just work if you switch out the variables and URL

**Comment by NeQuissimus** [comment]
@evrim Did you want me to create the PR?

**Comment by evrim** [comment]
I've used the following if you are interested in compiling.

<pre>
{ stdenv, hostPlatform, fetchFromGitHub, perl, buildLinux, ...}@args:
let
  kernelPath = <nixpkgs> + "/pkgs/os-specific/linux/kernel/";
  branch = "4.9";
  version = branch + ".40";
  revision = "74213b1";
in import (kernelPath + "/generic.nix") (args // {
   inherit version;
   ignoreConfigErrors = true;
   extraMeta.branch = branch;
   modDirVersion = version + "-unofficial+grsec";
   src = fetchFromGitHub {
     owner = "minipli";
     repo = "linux-unofficial_grsec";
     rev = revision;
     sha256 = "1rv345hciwc1mjz6r8wx8f0fqd4mkc84q36nna7xq1rlgml8m933";
   };
   kernelPatches = args.kernelPatches;
   features.iwlwifi = true;
   features.efiBootStub = true;
   features.needsCifsUtils = true;
   features.netfilterRPFilter = true;
} // (args.argsOverride or {}))
</pre>

**Comment by evrim** [comment]
won't fix.
