### ISSUE TITLE
emacs hexl-mode

### ISSUE THREAD

**Issue by evrim** [NixOS/nixpkgs#25756]
## Issue description

emacs 25.1 hexl mode does not work, wrapper failure.

### Steps to reproduce

M-x hexl-mode
Searching for program: No such file or directory, /nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/emacs/25.1/x86_64-unknown-linux-gnu/hexl

$ find /nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/update-game-score
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/profile
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/movemail
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/hexl
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/rcs2log
/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/emacs

## Technical details
17.03.1123.4a7a03913d (Gorilla)

**Comment by evrim** [comment]
seems like emacs is looking for a wrong path for hexl. any suggestions to fix it in .emacs.d/init.el?

**Comment by pbogdan** [comment]
I haven't tried it but perhaps you can use `hexl-program` variable to override the path, and point it at `/nix/store/jkh5n5f7fw64rfkbb28nr82klpvjl9zp-emacs-25.1/libexec/.emacs-wrapped/25.1/x86_64-unknown-linux-gnu/hexl` (with the downside of needing to be updated if the hash of the package changes for any reason).

```
hexl-program is a variable defined in ‘hexl.el’.
Its value is "hexl"

  This variable may be risky if used as a file-local variable.

Documentation:
The program that will hexlify and dehexlify its stdin.
‘hexl-program’ will always be concatenated with ‘hexl-options’
and "-de" when dehexlifying a buffer.

You can customize this variable.
```

**Comment by ttuegel** [comment]
This is actually a bug in `wrapGAppsHook`. It is generating a wrapper for the directory `libexec/emacs`, probably because it is "executable" and so the wrapper generator thinks it should be wrapped.
