### ISSUE TITLE
Mixxx package: USB HID devices are not being detected; "account needs write access to USB HID controllers"

### ISSUE THREAD

**Issue by nPrevail** [NixOS/nixpkgs#257502]
### Describe the bug
In the Mixxx software, when you plug in a device recognized with USB HID, you're met with this issued warning:

`Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.`

### Steps To Reproduce
1. Plug in USB MIDI device that gets recognized as 'USB HID' in Mixxx
2. Start Mixxx software via terminal
3. Warning will show up in terminal

### Expected behavior
DJ controller's MIDI/HID signals will not respond, be recognized, or operate in Mixxx. 

However, the audio interface will be recognized in Sound Hardware, and you can select all the audio routing options from the sound card.

### Screenshots
![Screenshot from 2023-09-26 20-21-40](https://github.com/NixOS/nixpkgs/assets/57690587/b1822ebb-f426-4aff-b312-45cff0dca72e)

### Additional context
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Warning [Main]: faad2::LibLoader - Failed to load  ("libfaad.so.2", "libfaad.so") ,  "Cannot load library libfaad.so: (libfaad.so: cannot open shared object file: No such file or directory)"
Warning [Main]: SoundSourceProviderRegistry - SoundSource provider "Nero FAAD2" does not support any file extensions
Warning [Main]: SoundSourceProxy - Failed to register SoundSource provider "Nero FAAD2"
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2737:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[Master]" , "skin_settings" )
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[Microphone]" , "show_microphone" )
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[VinylControl]" , "show_vinylcontrol" )
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[PreviewDeck]" , "show_previewdeck" )
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[Library]" , "show_coverart" )
Warning [Main]: ControlDoublePrivate::getControl returning NULL for ( "[Master]" , "maximize_library" )
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning []: Engine thread not scheduled with the real-time policy SCHED_FIFO

### Notify maintainers
@goibhniu @bfortz @lovek323

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
- system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.05 (Stoat), 23.05.3759.261abe8a44a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.05 (Stoat), 23.05.3759.261abe8a44a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Artturin** [comment]
You have to add the package to `services.udev.packages`

**Comment by nPrevail** [comment]
> You have to add the package to `services.udev.packages`


`services.udev.packages = [ pkgs.mixxx ];`

This works! Thank you!
