### ISSUE TITLE
python27Packages.pillow doesn't include header files

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#25764]
## Issue description
Pillow is meant to come with both py/pyc files for use from python, and .h files for python-friendly use from C. However, the pillow package in Nixpkgs doesn't include the header files. This makes it impossible to build things like minecraft-overviewer that call PIL from C as well as from python.

### Steps to reproduce
Instantiate pillow (using, e.g., `nix-shell -p python27Packages.pillow`)
```
$ find /nix/store -name Imaging.h
$
```
This nixpkgs derivation for pillow looks reasonable to me, but I don't know much about buildPythonPackage.

**Comment by FRidh** [comment]
Are the headers included in the sdist? We may also have to update Pillow again.

**Comment by ToxicFrog** [comment]
They are, yes: https://github.com/python-pillow/Pillow/tree/master/libImaging

**Comment by FRidh** [comment]
Do you know whether they're installed when you pip install in a virtualenv?

**Comment by ToxicFrog** [comment]
I can check! How do I do that? Just `pip install Pillow` and then rummage around wherever it put the files?

**Comment by FRidh** [comment]
Yep

**Comment by FRidh** [comment]
Did you check it? I haven't but I doubt we're doing something wrong so I am closing this. If I am wrong, please tell me and I (or someone else) reopens this issue.

**Comment by ToxicFrog** [comment]
Sorry, this kind of fell between the cracks.

I tried it, but it turns out I can't install pillow on Nix using pip:

```
$ nix-shell -p python27Packages.pip -p zlib
$ pip --user install pillow
Collecting pillow
  Using cached Pillow-4.1.1.tar.gz
Requirement already satisfied: olefile in ./.local/lib/python2.7/site-packages (from pillow)
Installing collected packages: pillow
  Running setup.py install for pillow ... error
[lots of logging elided]
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
```

I assume I'm holding it wrong, but I've never used pip before, and I thought that with `nix-shell -p zlib` the zlib headers would be available; `echo $buildInputs` shows the correct path.

**Comment by FRidh** [comment]
```
$ `nix-shell -p zlib`
$ env | grep FLAGS
```
You'll see the flags, however, these are `NIX_...` flags, and `setuptools` likely doesn't see this. Checking the Nix expression for `pillow`, there's quite some patching involved to make it find its dependencies.

Unfortunately just using `pip` as you would on another distro isn't so trivial with NixOS.
