### ISSUE TITLE
Update request: libreoffice-fresh 7.5.4.1 → 7.6.2

### ISSUE THREAD

**Issue by nadir-yttrium** [NixOS/nixpkgs#257657]
- Package name: libreoffice-fresh
- Latest released version: 7.6.2

- Current version on the unstable channel: 7.5.4.1
- Current version on the stable/release channel: 7.5.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@raskin
@doronbehar

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by doronbehar** [comment]
I'm working on it, along with a general rewrite of the expression...

**Comment by nadir-yttrium** [comment]
Hey, no worries. Just didn't see anything anywhere regarding the update. 

Maybe with this issue open, people might at least know for sure that it's being worked on.

Thank you.

**Comment by doronbehar** [comment]
@nadir-yttrium if you have time to test the build, a PR is available at #257853.

**Comment by nadir-yttrium** [comment]
@doronbehar 

I totally would help testing, it's just that I'm still kind of a newbie and haven't personally built anything  as complex as libreoffice. 

If I try to build it as usual using `nix-build -E 'let pkgs = import <nixpkgs> { }; in pkgs.callPackage ./default.nix {}'`, I get:

```
error:
       … while calling the 'abort' builtin

         at /nix/store/9gzb6bb0ghi5njm63sghyl7ia47n1ncn-source/lib/customisation.nix:173:65:

          172|
          173|     in if missingArgs == [] then makeOverridable f allArgs else abort error;
             |                                                                 ^
          174|

       error: evaluation aborted with the following error message: 'Function called without required argument "ArchiveZip" at /home/yt/code/libreoffice/nixpkgs/pkgs/applications/office/libreoffice/default.nix:10'
```

**Comment by doronbehar** [comment]
Thanks for the report @nadir-yttrium . Why do you build it like that? If you have a checkout of the PR, why not simply run `nix-build -A libreoffice-fresh` or `nix-build -A libreoffice-qt` in the root of Nixpkgs? In any case, indeed there was an evaluation error (different though) that is now fixed, including a few other errors. Still I haven't tested the builds fully, only checked that `configurePhase` of all `libreoffice-*` attributes are not broken.

Also, it's great to report on build issues such as this in [the PR](https://github.com/NixOS/nixpkgs/pull/257853).

**Comment by nadir-yttrium** [comment]
Well that would be because I didn't know what I was doing. Thanks for the advice. I've tried to build it. Will comment on the issue.
