### ISSUE TITLE
Package request: quarkus

### ISSUE THREAD

**Issue by xwoker** [NixOS/nixpkgs#257622]
**Project description**

Quarkus is a Kubernetes-native Java framework tailored for GraalVM and HotSpot, crafted from best-of-breed Java libraries and standards.

**Metadata**

* homepage URL: https://quarkus.io
* source URL: https://github.com/quarkusio
* license: apache 2.0
* platforms: kubernetes

**Comment by Vinetos** [comment]
Shipped with https://github.com/NixOS/nixpkgs/pull/298149
