### ISSUE TITLE
Package request: llvmPackages_17

### ISSUE THREAD

**Issue by kuznetsss** [NixOS/nixpkgs#257654]
**Project description**
The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. 

**Metadata**

* homepage URL: https://llvm.org/
* source URL: https://github.com/llvm/llvm-project
* license: Apache License v2.0 with LLVM Exceptions
* platforms: x86_64-darwin, aarch64-darwin, aarch64-linux, i686-linux, x86_64-linux

**Comment by RaitoBezarius** [comment]
Hi there, I don't think it will happen soon unfortunately as we still need to pick up the pieces of the last LLVM16/LLVM git divergences.

**Comment by RaitoBezarius** [comment]
@RossComputerGuy Please ensure that llvmPackages_git and llvmPackages_16 are sync with llvmPackages_17 if you do so. Each time, we give in to not stabilizing the divergences, we lose the opportunity to make it work for everything we learned about in the past release.

**Comment by RossComputerGuy** [comment]
Alright, I'll keep that in mind. Didn't realize there was a llvm git package, I only copied the stuff from llvm 16 to make 17 and after removing a couple patches, it seems to be working so far (compiler-rt built, clang just finished). There will probably have to be some patch changes but so far, things are working.

**Comment by reckenrode** [comment]
I have a couple of Darwin-related questions:

1. #256590 fixes Darwin cross. Should I wait for that to be merged before suggesting Darwin cross changes (or do it in a separate PR depending on timing)?
2. libc++ 17 [requires][1] the 10.13. SDK. Is the plan to revert https://github.com/llvm/llvm-project/commit/c73c3a078a130c4180a9d3626dcbc408992d53f9 (and hope nothing else requiring 10.13 has crept into libc++), or is x86_64-darwin going to be broken until the SDK is bumped?

[1]: https://discourse.llvm.org/t/libc-bumping-minimal-deployment-target-for-building-the-dylib-static-library-on-macos/68912

**Comment by RossComputerGuy** [comment]
@reckenrode I can try things out since my ARM machine is Apple Silicon. I'm mainly focused on Linux on ARM but I can try out the ARM Darwin support and patch if necessary.

**Comment by reckenrode** [comment]
> @reckenrode I can try things out since my ARM machine is Apple Silicon. I'm mainly focused on Linux on ARM but I can try out the ARM Darwin support and patch if necessary.

aarch64-darwin should be fine. Its SDK is 11.0. The issue with x86_64-darwin is it’s still using the 10.12 SDK by default (see #101229), and work on the update is still in progress. This doesn’t affect #234710, but it’ll be an issue for the Darwin stdenv once LLVM 18 is released next year.

**Comment by Artturin** [comment]
Should we just remove `_git`? Opened https://github.com/NixOS/nixpkgs/pull/269994 for discussion.
