### ISSUE TITLE
cabal2nix: assumes index is in ~/.cabal

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#25777]
## Issue description

Trying to run `cabal2nix` results in 

```
cabal2nix: /home/nagisa/.cabal/packages/hackage.haskell.org/00-index.tar: openBinaryFile: does not exist (No such file or directory)
```

The file is instead in a different location configured by cabal configuration file.

### Steps to reproduce

```
cabal2nix --sha256=0 --shell cabal://SOMETHING
```

with index in a non-standard location.

## Technical details

* System: 17.09pre107265.0afb6d789c (Hummingbird)

**Comment by ianweatherhogg** [comment]
Perhaps of some use, I was reading this [excellent](https://github.com/Gabriel439/haskell-nix/blob/master/project1/README.md) tutorial which suggested `cabal update` to address this issue.

**Comment by nagisa** [comment]
`cabal update` would only help if the index file was placed in default location.

**Comment by peti** [comment]
Please call `cabal2nix` with the option `--hackage-db=PATH`.
