### ISSUE TITLE
cabal2nix: tries to use nix-prefetch-zip which was removed 3 months ago

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#25776]
## Issue description

```
$ nix-shell -p cabal2nix --run "cabal2nix kazlauskas.cabal --sha256=0 --shell > shell.nix"
*** parsing cabal file: ./kazlauskas.cabal/.: openBinaryFile: inappropriate type (Not a directory)
cabal2nix: nix-prefetch-zip: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

### Steps to reproduce

Run cabal2nix on [this](https://github.com/nagisa/kazlauskas.me/blob/master/kazlauskas.cabal)

## Technical details

* System: 17.09pre107265.0afb6d789c (Hummingbird)

**Comment by domenkozar** [comment]
You are using master commit from February 20th, upgrade to at least something in March :)

**Comment by 3noch** [comment]
I still see this using latest unstable.

**Comment by razvan-panda** [comment]
Using latest unstable currently works
