### ISSUE TITLE
Update request: glib-networking 2.76.1 → 2.78.0

### ISSUE THREAD

**Issue by 9p4** [NixOS/nixpkgs#257712]
- Package name: glib-networking
- Latest released version: 2.78.0

- Current version on the unstable channel: 2.76.1
- Current version on the stable/release channel: 2.76.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jtojnar 
@NixOS/gnome

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by jtojnar** [comment]
Part of #247766
