### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by mrtuxa** [NixOS/nixpkgs#257879]
firefox has in unstable an older version than stable

**Comment by trzpiot** [comment]
So I use nixpkgs-unstable & have the current version `118.0`. Were the old version `117.0.1` installed for you or are you referring to the version displayed at https://search.nixos.org/packages?channel=unstable&show=firefox?

**Comment by donovanglover** [comment]
It takes some time for the website to update. Firefox 118 is [already in nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=257265).

**Comment by K900** [comment]
Not an issue, channels can be out of sync sometimes.
