### ISSUE TITLE
Occasionally, buildNpmPackage fails to download node_modules

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#257805]
### Describe the bug

Sometimes, I get network related errors when I try to produce a `buildNpmPackage`. Here's an example:

```
node_modules/@jridgewell/gen-mapping
node_modules/@xtuc/long
node_modules/@xtuc/ieee754
node_modules/accepts
node_modules/astral-regex
node_modules/basic-auth
node_modules/bl
node_modules/brace-expansion
node_modules/decompress-tar/node_modules/bl
Error: unknown error
Caused by:
    [55] Failed sending data to the peer
```

From this ofborg attempt: https://logs.ofborg.org/?key=nixos/nixpkgs.257662&attempt_id=77d3e9d9-ef98-4308-b021-afff5f6c0015

I cannot reproduce this easily, and sometimes after a retry it works, so that's all the information I have to give.

https://github.com/NixOS/nixpkgs/pull/238452 and https://github.com/NixOS/nixpkgs/issues/225586 might be related?

**Comment by fwam** [comment]
I believe it might be `npm`'s issue, rather than nix's, actually.

**Comment by lilyinstarlight** [comment]
I think this is likely the same issue as #256873, I just haven't had time to dig into it

> I believe it might be `npm`'s issue, rather than nix's, actually.

It happens before `npm` touches stuff, so it's definitely something in our tooling

**Comment by squalus** [comment]
I see the same problem with fetch-npm-deps. If I run it with `NIX_BUILD_CORES=1`, it seems to work (or at least work more often).

**Comment by lilyinstarlight** [comment]
So curl error 55 should be considered a network error and be retried, but it seems it isn't doing that. I'm wondering if we just need to bump `curl-sys` crate, so could someone who can replicate the issue test with the flake output `github:lilystarlight/nixpkgs/upd/prefetch-npm-deps-deps#prefetch-npm-deps` and see if it works with that?

**Comment by orangecms** [comment]
When I added some more debug prints and searched for the error, I found people suggesting that it might be rate limiting - could be too many parallel or duplicate requests. WDYT?

Re npm: I do not face this issue in a regular `npm install` for an app that would error with Nix via `fetch-npm-deps`.

**Comment by Gerg-L** [comment]
i can reproduce this quite consistently with my 32 threads
running with `--cores 1` works so if anyone needs a temporary work around do that

**Comment by lilyinstarlight** [comment]
Okay new branch for anyone who can test it: `github:lilyinstarlight/nixpkgs/fix/prefetch-npm-deps-network-error-recovery`

I think I've got it working now and will turn that branch into a PR soon

**Comment by Gerg-L** [comment]
```console
$ nix build github:lilyinstarlight/nixpkgs/fix/prefetch-npm-deps-network-error-recovery#webcord
[1/28/33 built, 34 copied (35.2/35.4 MiB), 49.0 MiB DL] building prefetch-npm-deps-0.1.0 (checkPhase):    Compiling isahc v1.7.2
```
Looks like it's stuck
