### ISSUE TITLE
erlang and elixir broken on macOS Sonoma

### ISSUE THREAD

**Issue by fbettag** [NixOS/nixpkgs#257880]
### Describe the bug
Since upgrading to macOS Sonoma today, neither erl nor elixir work anymore. Both yield a "Bus error: 10".

The same behavior has been reported since January on the Elixir Forums https://elixirforum.com/t/bus-error-after-upgrading-to-sonoma-beta/56354

I've also just re-installed nixos on my mac entirely, wiping /nix etc. Same behavior.

### Steps To Reproduce
1. Update from Ventura to Sonoma
2. run nix-shell -p elixir
3. run elixir -V or erl -V
4. see "Bus error: 10"

### Expected behavior
Have them both work as expected? :)

### Notify maintainers
@ankhers @Br1ght0ne @DianaOlympos @gleber @happysalada @minijackson @yurrriq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
````

**Comment by jeffutter** [comment]
Looks like there's something broken with the JIT on OTP25: https://github.com/erlang/otp/issues/7687#issuecomment-1737184968
The comment includes compiler options as a workaround. Hopefully, the workaround won't be needed and a fix will be released upstream.

**Comment by fbettag** [comment]
i just noticed that R26 is in nixpkgs now, that one seems to work nicely.

**Comment by zoedsoupe** [comment]
> i just noticed that R26 is in nixpkgs now, that one seems to work nicely.

Indeed! however some packages doesn’t support R26 for now, like `elixir-ls`, making impossible to use it. Workaround for now is to disable jit on the erlang build step 😕

**Comment by zoedsoupe** [comment]
Plug-n-play for lazy nix users (like me) that want to use elixir-ls, as it doesn’t support R26:

```nix
{pkgs,…}: let
  erl = pkgs.beam.interpreters.erlang_25.overrideAttrs (old: {
    configureFlags = [“—disable-jit”] ++ old.configureFlags;
  });
  beam = pkgs.beam.packagesWith erl;
in beam.elixir-ls;
```

notice that it will build/compile erlang from source, so it will take a while!

**Comment by c4710n** [comment]
And, you can also use an overlay for this:

```nix
_final: prev: {
  beam = prev.beam // {
    interpreters = prev.beam.interpreters // {
      erlang_26 = prev.beam.interpreters.erlang_26.overrideAttrs (_finalAttrs: prevAttrs: {
        configureFlags = prevAttrs.configureFlags ++ [ "--disable-jit" ];
      });

      erlang_25 = prev.beam.interpreters.erlang_25.overrideAttrs (_finalAttrs: prevAttrs: {
        configureFlags = prevAttrs.configureFlags ++ [ "--disable-jit" ];
      });
    };
  };
}
```

> I don't know how to override a nested attrset so far. Sorry for the ugly code.
