### ISSUE TITLE
pg_selfupdate doesn't build with postgresql-16 on macos

### ISSUE THREAD

**Issue by robx** [NixOS/nixpkgs#257827]
### Describe the bug

This works (`postgresql_15.withPackages(p: [p.pg_safeupdate])`):

```
$ nix build -I nixpkgs=flake:nixpkgs --impure --expr '(with import <nixpkgs> {}; postgresql_15.withPackages(p: [p.pg_safeupdate]))'
```

This fails (`postgresql_16.withPackages(p: [p.pg_safeupdate])`):

```
$ nix build -I nixpkgs=flake:nixpkgs --impure --expr '(with import <nixpkgs> {}; postgresql_16.withPackages(p: [p.pg_safeupdate]))'
error: builder for '/nix/store/f283g787wa80sj9ck95r2ni6m7grx6s3-pg-safeupdate-1.4.drv' failed with exit code 1;
       last 10 log lines:
       > source root is source
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > build flags: SHELL=/nix/store/dvk14kpsjv70jcqlj6z3izxwchka3ic3-bash-5.2-p15/bin/bash
       > cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -O2  -fvisibility=hidden -I. -I./ -I/nix/store/nm0qqgi36p8jb8v9gm4wdg83sx23v8lg-postgresql-16.0/include/server -I/nix/store/nm0qqgi36p8jb8v9gm4wdg83sx23v8lg-postgresql-16.0/include/internal -I/nix/store/pxkr1rdqdbnpbf081ydfw6avbmrxnsv4-icu4c-73.2-dev/include -I/nix/store/khl24xnhdvddh40w9q0zx8kn41mv9i4g-libxml2-2.11.5-dev/include/libxml2 -I/nix/store/jx3nl1cnf6niza5i8255bvff156ni4hr-lz4-1.9.4-dev/include -I/nix/store/gwcfgzcz4rhiahi3g27l0n548gfw9kn8-zstd-1.5.5-dev/include   -c -o safeupdate.o safeupdate.c
       > cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -O2  -fvisibility=hidden safeupdate.o -L/nix/store/1qipb24pnm55f9l2k6l7d89k0jl8sp7k-postgresql-16.0-lib/lib  -L/nix/store/i6skdxjya738cq5hcmx45cd5kdyq3xii-libxml2-2.11.5/lib -L/nix/store/xi3i64k4l3p7pxazixsmhf4y05s9g5pz-lz4-1.9.4/lib -L/nix/store/aklwi0pvynly8mv7n9ckjvv1lhz87a1y-zstd-1.5.5/lib  -Wl,-dead_strip_dylibs  -fvisibility=hidden -bundle -bundle_loader /nix/store/nm0qqgi36p8jb8v9gm4wdg83sx23v8lg-postgresql-16.0/bin/postgres -o safeupdate.dylib
       > installing
       > install: cannot stat 'safeupdate.so': No such file or directory
```

This works (`postgresql_16.withPackages(p: [p.pg_safeupdate])` patched to cp `.dylib` to `.so`):

```
$ nix build -I nixpkgs=flake:nixpkgs --impure --expr '(with import <nixpkgs> {}; postgresql_16.withPackages(p: [(p.pg_safeupdate.overrideAttrs (old: {installPhase="mkdir -p $out/bin; cp safeupdate.dylib safeupdate.so; install -D safeupdate.so -t $out/lib";}))]))'
```

I have no idea what exactly changed, but it looks like make implicit rules are involved? I think the build is done via https://github.com/eradman/pg-safeupdate/blob/master/Makefile in the end...

### Additional context

https://github.com/PostgREST/postgrest/issues/2973

### Notify maintainers

@thoughtpolice @danbst

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(rob): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by robx** [comment]
It seems that this applies to quite a few (but not all) extensions, see https://github.com/PostgREST/postgrest/pull/2958#issuecomment-1739880652.

**Comment by steve-chavez** [comment]
FYI, pg commit that introduced this change: https://github.com/postgres/postgres/commit/b55f62abb2c2e07dfae99e19a2b3d7ca9e58dc1a

**Comment by dbaynard** [comment]
> Peter Eisentraut wrote:
> > Tom Lane wrote:
> >> Doesn't this amount to a fundamental ABI break for extensions?
> >> Yesterday they had to ship foo.so, today they have to ship foo.dylib.
>
> > Extensions generally only load the module files using the extension-free 
> > base name.  And if they do specify the extension, they should use the 
> > provided DLSUFFIX variable and not hardcode it.  So I don't see how this 
> > would be a problem.
>
> Hm.  Since we force people to recompile extensions for new major versions
> anyway, maybe it'd be all right.  I'm sure there is *somebody* out there
> who will have to adjust their build scripts, but it does seem like it
> shouldn't be much worse than other routine API changes.

So it seems the builds should use `DLSUFFIX`, and this should also work on previous versions, too — does this sound reasonable?

**Comment by steve-chavez** [comment]
Don't know how to make `DLSUFFIX` work but `pkgs.hostPlatform.extensions.sharedLibrary` works great like: 

```nix
{ lib, stdenv, fetchFromGitHub, postgresql, hostPlatform }:

stdenv.mkDerivation rec {
  pname = "periods";
  version = "1.2.2";

  src = fetchFromGitHub {
    owner = "xocolatl";
    repo = pname;
    rev = "v${version}";
    sha256 = "sha256-ezt+MtDqPM8OmJCD6oQTS644l+XHZoxuivq0PUIXOY8=";
  };

  buildInputs = [ postgresql ];

  installPhase = ''
    install -D -t $out/lib *${hostPlatform.extensions.sharedLibrary}
    install -D -t $out/share/postgresql/extension *.sql
    install -D -t $out/share/postgresql/extension *.control
  '';

  meta = with lib; {
    description = "PostgreSQL extension implementing SQL standard functionality for PERIODs and SYSTEM VERSIONING";
    homepage = "https://github.com/xocolatl/periods";
    maintainers = with maintainers; [ ivan ];
    platforms = postgresql.meta.platforms;
    license = licenses.postgresql;
    broken = versionOlder postgresql.version "9.5";
  };
}
```

I guess we need to apply that for all extensions. Not sure if `.dylib` libs are generated for pg <= 15, so it should be applied conditionally.

**Comment by dbaynard** [comment]
Following some digging through the postgres history, I was able to get the original to build using this.

```nix
pg_safeupdate.overrideAttrs (old: {
  buildFlags = [ ''DLSUFFIX=".so"'' ];
});
```

This fixes it the _other_ way, ensuring that the build script creates the `.so` file.

So there are two options; I'm not sure which is preferable, but the same one should be rolled out across all the plugin definitions. I think the right option is to follow the change from postgres, and use the `hostPlatform` shared library extension.

**Comment by dbaynard** [comment]
Ah: the inner quotes around `.so` in my expression causes issues, I think.

```
error: builder for '/nix/store/f2j6b2w6fzr1c1z73cxj0f5fw34f26cv-pg_ed25519-0.2.drv' failed with exit code 2;
       last 10 log lines:
       >       _pg_sign in pg_ed25519.o
       >   "_VARDATA_ANY", referenced from:
       >       _pg_sign in pg_ed25519.o
       >       _pg_verify in pg_ed25519.o
       >   "_VARSIZE_ANY_EXHDR", referenced from:
       >       _pg_sign in pg_ed25519.o
       >       _pg_verify in pg_ed25519.o
       > ld: symbol(s) not found for architecture arm64
       > clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       > make: *** [/nix/store/aag1jq1gyll5sn9agi29jlw1pm607szv-postgresql-16.0/lib/pgxs/src/makefiles/../../src/Makefile.shlib:278: pg_ed25519".so"] Error 1
       For full logs, run 'nix log /nix/store/f2j6b2w6fzr1c1z73cxj0f5fw34f26cv-pg_ed25519-0.2.drv'.
```

However, this change does fix many builds, including `postgis`. I've added an extra file to https://gist.github.com/dbaynard/4af11b18b78573fe71eaf3921160548b with the success and failures.

| extension           |  15   |   16   |
|---------------------|:-----:|:------:|
| apache_datasketches | Built | Failed |
| jsonb_deep_sum      | Built | Built  |
| periods             | Built | Built  |
| pg_auto_failover    | Built | Failed |
| pg_bigm             | Built | Failed |
| pg_cron             | Built | Built  |
| pg_ed25519          | Built | Failed |
| pg_hint_plan        | Built | Failed |
| pg_hll              | Built | Failed |
| pg_ivm              | Built | Failed |
| pg_net              | Built | Built  |
| pg_partman          | Built | Built  |
| pg_rational         | Built | Built  |
| pg_relusage         | Built | Built  |
| pg_repack           | Built | Built  |
| pg_safeupdate       | Built | Built  |
| pg_similarity       | Built | Failed |
| pg_topn             | Built | Built  |
| pgaudit             | Built | Failed |
| pgjwt               | Built | Built  |
| pgroonga            | Built | Built  |
| pgrouting           | Built | Built  |
| pgsql-http          | Built | Built  |
| pgtap               | Built | Built  |
| pgvector            | Built | Built  |
| plpgsql_check       | Built | Built  |
| plr                 | Built | Built  |
| postgis             | Built | Built  |
| repmgr              | Built | Built  |
| rum                 | Built | Built  |
| smlar               | Built | Failed |
| temporal_tables     | Built | Failed |
| timescaledb         | Built | Failed |
| timescaledb-apache  | Built | Failed |
| tsearch_extras      | Built | Built  |
| wal2json            | Built | Built  |
