### ISSUE TITLE
slim starts without xauth

### ISSUE THREAD

**Issue by KaiLemke** [NixOS/nixpkgs#25780]
## Issue description

display-manager[727]: /nix/store/f8xgfgh4x18pz6ag50yijz2dh2v28266-xauth-1.0.9/bin/xauth:  file /var/run/slim.auth does not exist

With lightdm as display manager this doesn't occure.

### Steps to reproduce

enable slim as display manager without further config

## Technical details

* System: 17.03.1098.a162c6c828 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1098.a162c6c828
* Sandboxing enabled: false

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by KaiLemke** [comment]
Does not occur in 19.03.
