### ISSUE TITLE
Package request: QAdwaitaDecorations

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#257869]
**Project description**
 Qt decoration plugin implementing Adwaita-like client-side decorations  (Replacement for [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform#qgnomeplatform))

**Metadata**

* homepage URL: https://github.com/FedoraQt/QAdwaitaDecorations
* source URL: https://github.com/FedoraQt/QAdwaitaDecorations
* license: LGPL2.1
* platforms: linux

**Comment by Nyabinary** [comment]
QGnomePlatform is discontinued and will no longer receive updates the replacement is QAdwaitaDecorations.

**Comment by K900** [comment]
CC @NixOS/gnome
