### ISSUE TITLE
dlopen RTLD_LAZY problem

### ISSUE THREAD

**Issue by tomhrr** [NixOS/nixpkgs#25796]
## Issue description

When using `dlopen`, the `RTLD_LAZY` mode appears to behave in the same way as the `RTLD_NOW` mode, in that it resolves function symbols at load time.  I can't find any configuration options or environment variables that might be causing this to happen.

### Steps to reproduce

    [demo@nixos:~]$ cat test_inner.c
    int nonexistent_inner(void) { return 1; }
    [demo@nixos:~]$ gcc -fPIC -shared -o libtest_inner.so test_inner.c
    [demo@nixos:~]$ cat test.c
    int nonexistent_inner(void);

    int nonexistent(void) { return nonexistent_inner(); }
    [demo@nixos:~]$ gcc -fPIC -shared -o libtest.so test.c
    [demo@nixos:~]$ cat main.c
    #include <stdio.h>
    #include <dlfcn.h>

    int main(void)
    {
            void *ptr = dlopen("/home/demo/libtest.so", RTLD_LAZY);
            if (!ptr) {
                    printf("%s\n", dlerror());
            } else {
                    printf("dlopen successful: %p\n", ptr);
            }
    }

    [demo@nixos:~]$ gcc -ldl main.c
    [demo@nixos:~]$ ./a.out
    /home/demo/libtest.so: undefined symbol: nonexistent_inner
    [demo@nixos:~]$

## Technical details

* System: 17.03.1098.a162c6c828 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: [Same as for 'System', except without the '(Gorilla)' suffix.]
* Sandboxing enabled: false

**Comment by dtzWill** [comment]
Default gcc hardening flags includes "bindnow" behavior with `-z now`.  Try exporting `hardeningDisable=bindnow` and recompiling the various bits and it should work as expected!

(confirmed locally)

**Comment by tomhrr** [comment]
Excellent, works as expected, thanks very much.
