### ISSUE TITLE
Updating JaneStreet's core to v0.9.0

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#25794]
Hey, I've been trying to write the updated version for those packages, but got stuck haflway there.

My partial attempt is available here:

https://github.com/Ptival/nixpkgs/commit/5c48a6fcf5b19e839337fbebe8128b030e853145

So far I have done:

- added a `noConfigure` option, because `ppx-core` and `ppx-driver` no longer seem to contain a `configure` script
- bumped `minimumSupportedOcamlVersion` to 4.03 because I got weird errors with 4.02, though I don't know if that's necessary
- passed `jbuilder` and a couple other things around, though I have no idea whether they should be `buildInputs` or `propagatedBuildInputs`
- updated a couple hashes when they failed

I am stuck with `ppx-driver` at the following step:

```
      ocamlc src/ppx_driver__Import.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /nix/store/82gvjw76q55gj0zx151ibcw11sxa8c05-ocaml-4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /nix/store/82gvjw76q55gj0zx151ibcw11sxa8c05-ocaml-4.03.0/lib/ocaml/compiler-libs -I /nix/store/9f74smspaid0wlkj6g5jb499aj244x77-ocaml4.03.0-ocaml-migrate-parsetree-0.7/lib/ocaml/4.03.0/site-lib/ocaml-migrate-parsetree -I /nix/store/cmdl7vl8g8am8vw1bdj0654by0pqjrmm-ocaml4.03.0-ppx_core-133.33.01+4.03/lib/ocaml/4.03.0/site-lib/ppx_core -I /nix/store/gdz0g3dqvnwsg4l5xsc4ad1di11cm8m8-ocaml4.03.0-ppx_optcomp-113.33.00+4.03/lib/ocaml/4.03.0/site-lib/ppx_optcomp -I print-diff -no-alias-deps -I src -open Ppx_driver__ -o src/ppx_driver__Import.cmo -c -impl src/import.ml)
File "src/import.ml", line 6, characters 15-36:
Error: Unbound module Out_channel
```

AFAIU, `Out_channel` is a module of `ppx-core`, but my attempts at passing it around did not seem to succeed.

Any input appreciated, I am very much a newbie at OCaml packaging and Nix, so I mostly tried blindly.

**Comment by Ptival** [comment]
Paging @vbgl if you have some interest in this. :-)

**Comment by Zimmi48** [comment]
@Ptival See #25658

**Comment by Ptival** [comment]
@Zimmi48 Awesome! Closing this...
