### ISSUE TITLE
[bash-completion, btrfs-progs] Bash-completion doesn't work with btrfs

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#25793]
## Issue description
* `btrfs <TAB>` doesn't suggest any btrfs sub-command

### Steps to reproduce
* use following configuration in /etc/nixos/configuration.nix

    environment.systemPackages = with pkgs; [ btrfs-progs  ];
    programs.bash.enableCompletion = true;
* `nixox-rebuild switch`
* reboot the system

## Technical details

* System: NixOS: `17.09pre107265.0afb6d789c (Hummingbird)`
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre107265.0afb6d789c"
* Sandboxing enabled: build-use-sandbox = false

## Additional information
* bash-completion is working with git

    $ git \<TAB\>
    add    branch     clone    filter-branch    imap-send    mv     reflog     rm    submodule 
    ....

I know `btrfs` have `bash-completion` support. I use it on Arch Linux before. It should already be in `btrfs-progs`. 

Do I miss something?

**Comment by lheckemann** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git/tree/btrfs-completion the completion is included with btrfs-progs source so it should just be a matter of installing it.
