### ISSUE TITLE
Package request: linuxKernel.packages.linux_6_*.rtw89

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#257953]
**Project description**

linux 6.x or latest for rtw69 driver 
Driver for Realtek 8852AE, 8852BE, and 8853CE, 802.11ax devices

**Metadata**

* homepage URL: https://github.com/lwfinger/rtw89
* source URL: https://github.com/lwfinger/rtw89
* license: gpl2+
* platforms: linux

CC Maintainer rtw69 driver linux4 & linux5: @TvoroG

**Comment by K900** [comment]
rtw89 is included in mainline kernels now. Do you really need the very latest?

**Comment by hervyqa** [comment]
@K900 great, thank you so much.
fix my wifi issue.
```
kernelPackages = pkgs.linuxPackages_latest;
```
