### ISSUE TITLE
Pulseaudio and sound.extraConfig step on each other

### ISSUE THREAD

**Issue by dfoxfranke** [NixOS/nixpkgs#25790]
Setting `hardware.pulseaudio.enable` to `true` while setting `sound.extraConfig` to any non-empty value will cause a build failure because alsa.nix and pulseaudio.nix both attempt to create /etc/asound.conf. The correct result would be for the contents of `sound.extraConfig` to be written out at the end of /etc/asound.conf, after the stanzas provided by pulseaudio.

Somewhat relatedly, the `!` in `pcm.!default` and `ctl.!default` in pulseaudio's generated config doesn't make a whole lot of sense. `!` means "override", currently there is nothing for it to override, and we would like user config to override generated config, not the other way around. However, as long as user config is placed in the file *after* generated config then I don't think the `!` actually makes any difference.

**Comment by rybern** [comment]
I am having this issue as well. Easily replicated by setting those two options.

**Comment by Mic92** [comment]
Can you make a pull request?

**Comment by bennofs** [comment]
Should be fixed with #27000. If there still is a problem, please reopen this issue.
