### ISSUE TITLE
Using nix-env -qa on systems without 'less' command returns error

### ISSUE THREAD

**Issue by viniciuscr** [NixOS/nixpkgs#25799]
## Issue description
On systems that does not have the `less` command installed by default the `nix-env -qa program` returns error: 
> sh: /usr/bin/less: not found

Even after installing less using nix it still returning the same error

### Steps to reproduce
In any OS without less installed execute `nix-env -qa python` 

## Technical details
I belieave the problem is that the call for less command is hardcoded to the path  /usr/bin/less
It should be able to use the less command installed by nix.

* System: ChromeOS  58.0.3029.89 (64-bit)
* Nix version: nix-env (Nix) 1.11.7
* Nixpkgs version: "17.09pre104029.fff8cc7"
* Sandboxing enabled: didn't work

**Comment by pbogdan** [comment]
What does:

```
$ echo $PAGER
```
say in your shell? Just wondering if you are perhaps overriding the pager via your environment?

**Comment by viniciuscr** [comment]
>$ echo $PAGER
/usr/bin/less

I set `PAGER=less` and now it works!
Sorry, I didn't know about the $PAGER

**Comment by viniciuscr** [comment]
Thanks pbogdan,
Seam like the $PATH is correctly set.
At least, it is working.

>/home/chronos/user/.nix-profile/bin:/home/chronos/user/.nix-profile/sbin:/usr/local/bin:/usr/bin:/bin:/opt/bin
