### ISSUE TITLE
keyd configuration is order-sensitive but the order is not being preserved

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#258083]
Composite layers in keyd MUST always be defined after regular layers (see
https://github.com/rvaiya/keyd/blob/6dc2d5c4ea76802fd192b143bdd53b1787fd6deb/docs/keyd.scdoc#L235 )

Currently it seems to be impossible to keep the settings order

@woojiq

**Comment by woojiq** [comment]
Hello. I didn't know about these `keyd` possibilities (composite layers and `:<modifier set>`).
Unforntunately in nix, there is no easy way to preserve the order of attributes. See:
[1](https://stackoverflow.com/questions/60429398/nix-maintain-original-order-of-a-set)
[2](https://github.com/nix-community/home-manager/issues/2519)

The simplest solution I can see is to add the `extraConfig` option to the `keyboards.<name>` option. E.g:
```nix
keyd = {
  enable = true;
  keyboards = {
    default = {
      settings = {
        main = {
          capslock = "layer(capslock)";
        };
      };
      extraConfig = ''
        [capslock:C]
        [capslock+shift]
        h = left
      '';
    };
  };
};
```

Will this solution satisfy you?

**Comment by pshirshov** [comment]
Yep, that would work. Though, I think that it's possible to preserve the order by using arrays instead of dictionaries.

E.g. 

```
settings = [
 {main = {capslock = ...}}
  {"capslock:C" = {h = ...}}
]
```

**Comment by woojiq** [comment]
At this point, I think I'll add `extraConfig`. Why?
1. Someone will want to save their config in raw string format (when moving from another OS).
1. Though your suggestion looks fine to me, it's breaking changes anyway.

Maybe in the future, if there are more advantages in your syntax, we will rewrite the module.
