### ISSUE TITLE
jax requires jaxlib at runtime

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#258089]
### Describe the bug

When disabling the `checkPhase` on jax, the import check fails because it cannot import `jaxlib`, which reveals it to be a runtime dependency.

### Steps To Reproduce
1. Set `doCheck = false`, so the `pythonImportsCheck` has no access to the `nativeCheckInputs`
2. Build jax and notice how it fails during `pythonImportsCheck`

### Expected behavior
Jaxlib should be propagated, if it gets imported at `jax/_src/lib/__init__.py`.

### Error log
```python3
jax> Check whether the following modules can be imported: jax
jax> Traceback (most recent call last):
jax>   File "/nix/store/vy0df04fz29psjg9nwl265mnjb248jyk-python3.10-jax-0.4.16/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 25, in <module>
jax>     import jaxlib as jaxlib
jax> ModuleNotFoundError: No module named 'jaxlib'
jax> 
jax> The above exception was the direct cause of the following exception:
jax> 
jax> Traceback (most recent call last):
jax>   File "<string>", line 1, in <module>
jax>   File "<string>", line 1, in <lambda>
jax>   File "/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
jax>     return _bootstrap._gcd_import(name[level:], package, level)
jax>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
jax>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
jax>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
jax>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
jax>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
jax>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
jax>   File "/nix/store/vy0df04fz29psjg9nwl265mnjb248jyk-python3.10-jax-0.4.16/lib/python3.10/site-packages/jax/__init__.py", line 39, in <module>
jax>     from jax import config as _config_module
jax>   File "/nix/store/vy0df04fz29psjg9nwl265mnjb248jyk-python3.10-jax-0.4.16/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
jax>     from jax._src.config import config  # noqa: F401
jax>   File "/nix/store/vy0df04fz29psjg9nwl265mnjb248jyk-python3.10-jax-0.4.16/lib/python3.10/site-packages/jax/_src/config.py", line 27, in <module>
jax>     from jax._src import lib
jax>   File "/nix/store/vy0df04fz29psjg9nwl265mnjb248jyk-python3.10-jax-0.4.16/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 27, in <module>
jax>     raise ModuleNotFoundError(
jax> ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.
```

### Notify maintainers
@samuela 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.11 (Tapir), 23.11.20230922.e35dcc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by samuela** [comment]
This is intentional. Upstream separated the jax and jaxlib packages by design such that neither is an `install_requires` dependency on the other. This allows users to swap out compute backends without having to rebuild and reinstall the jax frontend in the process. So we follow that pattern in nixpkgs.

**Comment by mweinelt** [comment]
The reason I disabled tests in the first place is because they are annoyingly slow (~50 minutes) and h.n.o's linux builders (amd64 & aarch64), as well as my local Zen 3 builder, currently crash reliably in `tests_sparse.py`.

https://hydra.nixos.org/build/236948549
https://hydra.nixos.org/build/236947391

With jax being a dependency to tensorflow-bin, and me maintaing a number of downstream consumers, I really want jax to succeed on hydra, so I'll follow up with a PR to disable those tests for the time being.

**Comment by mweinelt** [comment]
Additionally, peak memory usage during tests with -j3 was ~15 GB for me, so I suggest we give pytest-xdist another chance, because that reduced test time down to 17 minutes.

**Comment by samuela** [comment]
> Fatal Python error: Segmentation fault

I've also seen these segfaults, and I find them to be concerning... If you (or any internet friends) have any ideas, I'd love to debug somehow. Seems like it only happens on certain CPUs.

> Additionally, peak memory usage during tests with -j3 was ~15 GB for me, so I suggest we give pytest-xdist another chance, because that reduced test time down to 17 minutes.

Ah yeah, this is a tough one. Enabling parallelism broke builds for me on nixpkgs-upkeep, hence the removal of pytest-xdist. I'm open to re-enabling pytest-xdist, so long as it doesn't break nixpkgs-upkeep builds.

> peak memory usage during tests with -j3 was ~15 GB for me, so I suggest we give pytest-xdist another chance

Not sure I follow... shouldn't increasing parallelism increase memory pressure?

**Comment by mweinelt** [comment]
> I've also seen these segfaults, and I find them to be concerning... If you (or any internet friends) have any ideas, I'd love to debug somehow. Seems like it only happens on certain CPUs.

I lack experience debugging crashes, and I would hope that the stack traces in the build logs are sufficient to go upstream. Especially because we see this on multiple machines. But I kinda expect Google not to care for our issues anyway.

> Ah yeah, this is a tough one. Enabling parallelism broke builds for me on nixpkgs-upkeep, hence the removal of pytest-xdist. I'm open to re-enabling pytest-xdist, so long as it doesn't break nixpkgs-upkeep builds.

I'm unaware of the specs of your nixpkgs-upkeep builders, but the ideal outcome would be to have it cached on cache.nixos.org.

> Not sure I follow... shouldn't increasing parallelism increase memory pressure?

Yes, I'm just saying this was peak memory usage while the test suite was running on my Ryzen 5600.

**Comment by samuela** [comment]
> I'm unaware of the specs of your nixpkgs-upkeep builders, but the ideal outcome would be to have it cached on cache.nixos.org.

Agreed, and it is currently cached on cache.nixos.org. nixpkgs-upkeep helps to alert me when it fails to build -- either by me merging something silly or something in the dependency closure breaking.

**Comment by mweinelt** [comment]
It is currently failing on nixos-unstable, has been like that for 8 days.

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python310Packages.jax.aarch64-linux
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python310Packages.jax.x86_64-linux

**Comment by samuela** [comment]
Well, I mean in nominal operation :P

**Comment by Mic92** [comment]
> > I'm unaware of the specs of your nixpkgs-upkeep builders, but the ideal outcome would be to have it cached on cache.nixos.org.
> 
> Agreed, and it is currently cached on cache.nixos.org. nixpkgs-upkeep helps to alert me when it fails to build -- either by me merging something silly or something in the dependency closure breaking.

If you move your project to nix-community than you can configure bigger builders: https://nix-community.org/continuous-integration/

**Comment by samuela** [comment]
Thanks @Mic92 -- I didn't realize that was an option! I'd be open to moving nixpkgs-upkeep into nix-community. Seems like that could be a win-win?
