### ISSUE TITLE
nix-gc-start[19181]: error: $XDG_CONFIG_HOME and $HOME are not set

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#25805]
## Issue description

nix-gc service fails to run on 17.03 using nixUnstable.  Seems likely it's the same basic problem as [nix-daemon issue with same error](https://github.com/NixOS/nix/pull/1366).  Hopefully the fix is similarly straightforward?

### Steps to reproduce

* (On 17.03)
* Use nixUnstable as `nix.package`
* Enable `nix.gc.automatic` in configuration.nix
* Let it run or start it manually
* Observe error message about XDG_CONFIG_HOME/HOME and service failure

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by edolstra** [comment]
Fixed by https://github.com/NixOS/nix/commit/465cb6824401541d82489e11b5223dbfd50bb132.

**Comment by dtzWill** [comment]
Great, thank you! :+1:
