### ISSUE TITLE
Postman throws OpenSSL error

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#258007]
### Describe the bug
When sending API requests, Postman throws the following error in the console:
```
Error: write EPROTO 60610599165384:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../../../src/third_party/boringssl/src/ssl/tls_record.cc:242:
```

### Steps To Reproduce
1. Run postman
2. Send an API request
3. Check console for descriptive error

### Expected behavior
The API call occurs and returns the data

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/43472218/977d27d3-d20f-4720-96fe-6ef66e34385d)
![image](https://github.com/NixOS/nixpkgs/assets/43472218/736fc371-74cb-4d2e-b456-aff2b22d2c31)

### Additional context
Although I could not confirm this yet, but it might have occurred after adding OpenSSL as a build dependency in [this PR](https://github.com/NixOS/nixpkgs/pull/257123). As the comment in commit suggests, it is unknown which version of OpenSSL expects and that's precisely what the error I got says.

### Notify maintainers
We meet again, @johnrichardrinehart

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m" - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20230925.6500b45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/i6hq63805y784dml4j8pgkrz3lryxzld-source`
```

**Comment by johnrichardrinehart** [comment]
Oooohhhh, no. Somehow I figured that OpenSSL was only used for that initial cert generation and not for runtime TLS. Let me test a couple of fixes. I should be able to get something up today.

Sorry @GetPsyched et al.!

**Comment by GetPsyched** [comment]
Haha, no worries. I'm making the shift to `hoppscotch` anyways. Figuring out some CORS issues there. Thought I'd mention it here since a lot of other people would have their package broken.

**Comment by johnrichardrinehart** [comment]
Hm, I can't seem to reproduce.

```bash
$ git remote get-url origin       
git@github.com:/nixos/nixpkgs
$ git rev-parse HEAD
ff75cea66debc664ef1b4791e2eaa046068323c3
$ NIXPKGS_ALLOW_UNFREE=1 nix shell --impure .\#postman
```
and then an `https` request to `google.com` yields
![PostmanSSLOnMaster](https://github.com/NixOS/nixpkgs/assets/6321578/a04d6b00-7b6d-46cf-87d0-4814ae8d6103)

**Comment by johnrichardrinehart** [comment]
Seems like this specific issue might crop up if the server doesn't support TLS: https://stackoverflow.com/questions/62658941/error-write-eproto-34557064error100000f7ssl-routinesopenssl-internalwrong . Given that you're running a local HTTP server this is my guess as to what's happening.

**Comment by GetPsyched** [comment]
Weird, I cannot repro the issue anymore either. I tried both with `HTTP` and `HTTPS` and the requests seem to be going through

**Comment by GetPsyched** [comment]
Closing since I don't use Postman anymore and this probably isn't an issue anymore either (given I couldn't reproduce it anymore and no one else has come to this issue).
