### ISSUE TITLE
upowerd: critical action configuration

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#25815]
## Issue description

The Thinkpad T460p (and, it seems, a lot of the Lenovo Thinkpad line) have a problem resuming from suspend. It may only be an issue if the battery expires before a full suspend complete. Regardless, the workaround is to disable hibernation, especially in low-power situations.

It'd be great if the upowerd module had a "criticalAction" attribute, and maybe "batteryLevels" to control the UPower.conf file

### Steps to reproduce

In my case: leave laptop in office where power is turned off at night. Come back to laptop that must be opened and have the motherboard battery unplugged.

Current workaround: `upowerd.enable = false`

## Technical details

* System: 17.03.1033.99dfb6dce3 (Gorilla) 
* Nix version: nix-env (Nix) 1.11.8 
* Nixpkgs version: "17.03.1033.99dfb6dce3"

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by nyarly** [comment]
@mmahut I disabled upowerd and forgot about it. I ought to spend some time on the module and get a PR in.

**Comment by mmahut** [comment]
@nyarly thank you, please do that, feel free to tag me in the PR for review.
