### ISSUE TITLE
No Boot Logs

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#25820]
## Issue description

For whatever reason I don't seem to have any boot logs. The earliest log that I have in journalctl are related to starting syncthing. 

I also noticed that in dmesg the following shows up: 

```
[    3.564464] systemd-journald[2269]: Received request to flush runtime journal from PID 1 
```

I don't know if maybe that is related to the problem? 

Here is the start of my logs after booting, unless I'm mistaken there should be starting a lot earlier.: 

```
-- Reboot --
May 15 22:03:30 atom syncthing-inotify[2840]: [WARNING] Cannot connect to Syncthing: Get http://127.0.0.1:8
May 15 22:03:30 atom syncthing[2839]: [CYABX] 22:03:30 INFO: syncthing v0.14.23 "Dysprosium Dragonfly" (go1
May 15 22:03:30 atom syncthing[2839]: [CYABX] 22:03:30 INFO: My ID: CYABX2H-IJ5IQJS-Z7GDTIW-HFQNKLD-66FEX52
May 15 22:03:30 atom syncthing-inotify[2840]: [WARNING] Cannot connect to Syncthing: Get http://127.0.0.1:8
May 15 22:03:30 atom syncthing[2839]: [CYABX] 22:03:30 INFO: Single thread SHA256 performance is 461 MB/s u
May 15 22:03:31 atom syncthing[2839]: [CYABX] 22:03:31 INFO: Hashing performance with weak hash is 387.66 M
May 15 22:03:31 atom syncthing-inotify[2840]: [WARNING] Cannot connect to Syncthing: Get http://127.0.0.1:8
May 15 22:03:31 atom syncthing[2839]: [CYABX] 22:03:31 INFO: Hashing performance without weak hash is 448.3
May 15 22:03:31 atom syncthing[2839]: [CYABX] 22:03:31 INFO: Weak hash enabled, as it has an acceptable per
May 15 22:03:31 atom systemd[2891]: Reached target Paths.
May 15 22:03:31 atom systemd[2891]: Reached target Timers.
May 15 22:03:31 atom systemd[2891]: Reached target Sockets.
May 15 22:03:31 atom systemd[2891]: Reached target Basic System.
May 15 22:03:31 atom systemd[2891]: Starting SSH Agent...
May 15 22:03:31 atom systemd[2891]: Started SSH Agent.
May 15 22:03:31 atom systemd[2891]: Reached target Default.
May 15 22:03:31 atom systemd[2891]: Startup finished in 18ms
```

## Technical details

I'm running ZOL with /var/log/journal in a separate data set with posixacls turned on.

* System: (NixOS: 17.03.1091.dc7dc77cde (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.1091.dc7dc77cde")
* Sandboxing enabled: (build-use-sandbox = true)

**Comment by dezgeg** [comment]
Did you run journalctl as root?

**Comment by johnramsden** [comment]
@dezgeg Yes. Tried as root and as user.

**Comment by Mic92** [comment]
Also for earlier boots?
sudo journalctl -b -1
sudo journalctl -b -2

**Comment by johnramsden** [comment]
@Mic92 Same thing.

**Comment by dezgeg** [comment]
Is your `/var/log/journal` mounted before journald starts?

**Comment by johnramsden** [comment]
@dezgeg How would I check? I would assume that by default it would be mounted before starting journald.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by Mic92** [comment]
@johnramsden you could set `services.journald.extraConfig = "Storage=volatile";` to make journald log to memory, to check if it is related to mounting partition.

**Comment by Mic92** [comment]
Issuer creator seems unresponsive. Please re-open if this is still an issue.
