### ISSUE TITLE
Fontconfig config/cache derivation for when fonts are required during build-time

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25828]
## Issue description

I'm using Nix to generate some plots using matplotlib. Matplotlib requires a fontconfig cache but none is available during a `nix-build`. There is a `fontconfig` module that generates the proper files. Perhaps we can use that code in a separate derivation for building a configuration and cache when one is needed?

Edit:

Now I see we have
```
  makeFontsConf = let fontconfig_ = fontconfig; in {fontconfig ? fontconfig_, fontDirectories}:
    callPackage ../development/libraries/fontconfig/make-fonts-conf.nix {
      inherit fontconfig fontDirectories;
    };

  makeFontsCache = let fontconfig_ = fontconfig; in {fontconfig ? fontconfig_, fontDirectories}:
    callPackage ../development/libraries/fontconfig/make-fonts-cache.nix {
      inherit fontconfig fontDirectories;
    };
```

**Comment by vcunat** [comment]
So, the issue is "fixed"?

**Comment by FRidh** [comment]
Unfortunately not as I get an error when using the config. It would be
really convenient if there would be a hook that would set up a usable
fontconfig though you likely would have to pass in fonts.

**Comment by vcunat** [comment]
These are used on a few places, so I thought they worked.

**Comment by FRidh** [comment]
I guess it is working and that I just forgot setting `FONTCONFIG_FILE`. Next up seems how to get matplotlib to build its cache in a directory it can actually write to. I'll keep this open till it is fully working.

**Comment by FRidh** [comment]
To get matplotlib working I had to set `$HOME` because matplotlib needs a cache as well. Note that an absolute path is required or else we run into https://github.com/matplotlib/matplotlib/issues/3823#issuecomment-302001141.

The following is an example of what worked for me:
```nix
  plot = let
    fontsConf = pkgs.makeFontsCache {
      fontDirectories = [
        "${pkgs.ghostscript}/share/ghostscript/fonts"
      ];
    };
  in runCommand "propagation-plots" {
      buildInputs = [
        (python.withPackages(ps: with ps; [ acoustics h5store matplotlib]) )
        texlive.combined.scheme-full
        fontconfig
        pkgs.ghostscript
      ];
      FONTCONFIG_FILE=fontsConf;
    } ''
      # We set $HOME because matplotlib needs to build a cache in order to plot.
      export HOME=$(readlink -f ".");
      mkdir -p $out
      python3 ${./plot.py} ${computations} $out

    '';
```

**Comment by FRidh** [comment]
I now wrote a hook as well:

```
# Note that we do not use a phase because the hook is
# used with runCommand

# preConfigurePhases+=" matplotlibPhase"

# matplotlibPhase() {
runHook preMatplotlib
export FONTCONFIG_FILE=@fontsConf@
export HOME=$(readlink -f ".");
echo $FONTCONFIG_FILE
echo $HOME
runHook postMatplotlib
# }
```
although it now appears it might not be needed.

**Comment by vcunat** [comment]
BTW, those gigabytes of `scheme-full` are probably an overkill...

**Comment by FRidh** [comment]
Yep, they are. I always manage to miss something though. In the beginning I would put together my own set for texlive but eventually I decided to just use the whole package :smile:
