### ISSUE TITLE
KDE wallet doesn't unlock on SDDM

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#258296]
### Describe the bug
Same issue as #87945 #101904.

Enabling kwallet with `security.pam.services.sddm.enableKwallet = true;` doesn't work.

### Steps To Reproduce
1. Install 23.05 Plasma
2. Add `security.pam.services.sddm.enableKwallet = true;` to configuration.nix and rebuild
3. Go to KDE Wallet ->Select wallet to use as default -> New -> Classic -> blowfish -> enter the same password as your user password (set the wallet name to kdewallet)
4. Create a wallet
5. Reboot
6. Access the wallet: connect to a wifi network (or on VM go to KDE Wallet -> Launch Wallet Manager -> Open

### Expected behavior
After having a wallet set up with the pam service, when accessing the wallet, it shouldn't prompt for a password.

### Screenshots
![Untitled](https://github.com/NixOS/nixpkgs/assets/29818440/c0537e5b-a8d8-4596-a883-e9911c0e4191)

### Additional context
Starting KWalletManager from GUI will close without opening a window.
These commands segfault:
```console
$ kwalletd5
Segmentation fault (core dumped)

$ kwalletmanager5 
Segmentation fault (core dumped)
```

### Notify maintainers
@FRidh @ttuegel 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.3881.5cfafa12d573`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Majiir** [comment]
I think this happens because the `sddm` module hardcodes PAM text that points to the `login` rules. Can you try this workaround?

```nix
{
  security.pam.services.login.enableKwallet = true;
}
```

The proper fix is to refactor `security.pam` so that desktop managers don't need to hardcode PAM rule files. You can help by [reviewing this PR](https://www.github.com/NixOS/nixpkgs/pull/255547).

**Comment by anthr76** [comment]
The above didn't work for me I wonder if it's in conflict with 

`security.pam.enableSSHAgentAuth = true;`

**Comment by dedsm** [comment]
@Majiir the PR you referred is merged but I still don't know how that would fix the issue, can you please enlighten me?

**Comment by Shawn8901** [comment]
That's just the starting pr, that changed pam system needs to be adapted in the sddms module. That is not yet done.

**Comment by SuperSandro2000** [comment]
Came reproduce this issue on my end, kwallet always unlocks in the default plasma 6 settings.

**Comment by atomicptr** [comment]
Still doesn't unlock on (presumably) anything but Plasma. At least I was under the assumption that this should also work with other setups :thinking:

**Comment by SuperSandro2000** [comment]
Then I got mislead by the initial post and the real issue is, that kwallet unlock via PAM doesn't work.

**Comment by SuperSandro2000** [comment]
I assume with [`8be79e5` (#286522)](https://github.com/NixOS/nixpkgs/pull/286522/commits/8be79e54c597eeeb0965127da236c8b7d6ac1af8) and #331278 this should work?

**Comment by atomicptr** [comment]
Sadly not :(

**Comment by dedsm** [comment]
I was having this issue and after using all the hints from here, I noticed I was missing adding:

`${pkgs.kdePackages.kwallet-pam}/libexec/pam_kwallet_init` in my window manager startup script, after that kwallet works

**Comment by SuperSandro2000** [comment]
see https://github.com/NixOS/nixpkgs/blob/a84cbd30518116a940d07eafb9ee367071e9c013/nixos/modules/services/desktop-managers/plasma6.nix#L266-L280

**Comment by atomicptr** [comment]
I'm not sure why but after adding both dedsm suggestions and the security.pam.services.kde subtree (I only had used login until now with the same setup) it worked? This has some black magic vibes lol, thanks!

**Comment by SuperSandro2000** [comment]
pam is usually a bit complicated, I myself can't explain the details of that either.

**Comment by dedsm** [comment]
@atomicptr I think the reason is explained in the https://github.com/KDE/kwallet-pam/tree/master README
