### ISSUE TITLE
gtk+ 2 doesn't recognize default themes

### ISSUE THREAD

**Issue by shosti** [NixOS/nixpkgs#25838]
## Issue description

gtk+ 2 comes with a few default themes ("Default", "Raleigh", and "Emacs"), but by default gtk apps don't seem to be able to pick them up.

### Steps to reproduce

1. Install `chromium` (through /etc/nixos/configuration.nix)
2. `echo 'gtk-key-theme-name="Emacs"' >> ~/.gtkrc-2.0`
3. Launch chromium
4. Try using Emacs keybindings (for instance, C-a in the search bar)

Expected: Uses Emacs keybindings
Actual: Uses default keybindings

(I was able to work around the issue by copying from the nix store for gtk to ~/.themes.)

## Technical details

* System: NixOS `17.03.1152.22da5d0246 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `"17.03.1152.22da5d0246"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by pbogdan** [comment]
Would be interested in this as well, currently my `/etc/nixos/configuration.nix` features:

```
  # this is needed so that gtk can find emacs key theme
  environment.extraInit = ''
    # argh
    mkdir ~/.themes/ 2>/dev/null
    ln -sf "${pkgs.gnome2.gtk}/share/themes/Emacs" ~/.themes/

    export XDG_DATA_DIRS="${pkgs.gnome3.gtk}/share:$XDG_DATA_DIRS"
  '';
```

:/

**Comment by Mic92** [comment]
@pbogdan and with this change it works for you?

**Comment by pbogdan** [comment]
@Mic92  yes, it does. Once I adjust `.config/gtk-3.0/settings.ini` and `.gtkrc-2.0` to use Emacs key theme I get them working in both gtk+2 and gtk+3 apps.

**Comment by Mic92** [comment]
if you install `gnome2.gtk` in systemPackages or via `nix-env`, it will get a symlink in `~/.nix-profile/share/themes` or `/run/current-system/sw/share/themes`. Since these directories are also in `XDG_DATA_DIR`, they should be picked up by applications like Chrome. This should at least for gtk3. I am not sure about gtk2 though.

**Comment by Mic92** [comment]
Just tested it and the chromium example worked for me.

**Comment by pbogdan** [comment]
IIRC gtk+2 won't search through any of `$XDG_DATA_DIRS` but has hardcoded list of folders `~/.themes` and `$GTK_DATA_PREFIX`/share/themes (the latter must contain a single path I think).
Did you install gtk system wide or into your profile?
The issue then is that you can't have both in a single profile due to collisions.

**Comment by pbogdan** [comment]
Some digging turned up this patch from our Guix friends 😄 - https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/gtk2-theme-paths.patch - which enables gtk+2 to search through `$XDG_DATA_DIRS`

**Comment by Mic92** [comment]
I had it in my profile, but system wide should working the same following the logic.

**Comment by pbogdan** [comment]
Odd, gtk+2 doesn't look at  `$XDG_DATA_DIRS` AFAIK. What's your `$GTK_DATA_PREFIX` set to?

**Comment by Mic92** [comment]
Seems like I that this at some point:

```
$ echo $GTK_DATA_PREFIX                        
/run/current-system/sw
```

**Comment by pbogdan** [comment]
Anything under `/run/current-system/sw/share/themes/` ? I would guess that's where it gets picked up from though it would be strange for a package installed via user profile. Unless you have anything under `~/.themes` perhaps?

**Comment by shosti** [comment]
All installations for me are global, and I'm using xmonad (gnome isn't installed and I'd like to avoid installing it if possible). It looks like the themes don't end up in `/run/current-system/sw/share/themes/`:

```
~ $ echo $XDG_DATA_DIRS
/nix/store/wgghc6zvhc1jjy8h76czp6z16kg0qk3g-emacs-25.1/share:/nix/store/zp3zcinsx7d5fa6mc407pz1bndk7wl2v-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8:/nix/store/9755bvfhzln5yrbjnjarl6p5vczmsgnl-gsettings-desktop-schemas-3.22.0/share/gsettings-schemas/gsettings-desktop-schemas-3.22.0:/nix/store/wgghc6zvhc1jjy8h76czp6z16kg0qk3g-emacs-25.1/share:/nix/store/zp3zcinsx7d5fa6mc407pz1bndk7wl2v-gtk+3-3.22.8/share/gsettings-schemas/gtk+3-3.22.8:/nix/store/9755bvfhzln5yrbjnjarl6p5vczmsgnl-gsettings-desktop-schemas-3.22.0/share/gsettings-schemas/gsettings-desktop-schemas-3.22.0:/run/opengl-driver/share:/home/shosti/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
~ $ echo $GTK_DATA_PREFIX
/nix/store/d0f84nizpwdj6aiss7051ixn0aqakqwh-system-path
~ $ ls /run/current-system/sw/share/themes/
~ $ 
```

**Comment by Mic92** [comment]
You do not need to install gnome, but gnome.gtk2 in systemPackages, which is already there (but not in /nix/store/d0f84nizpwdj6aiss7051ixn0aqakqwh-system-path) if you already have any gtk2 application like chromium.

**Comment by shosti** [comment]
Oh, sorry, misunderstood. It's definitely not linked in my case, either to `/run/current-system/sw/share/themes/`, or to `$GTK_DATA_PREFIX/share/themes/`.

**Comment by Mic92** [comment]
I mean you have to explicitly add it to `systemPackages`

**Comment by shosti** [comment]
Oh, actually that seems to have done the trick. Incidentally, I'd tried that
earlier with gtk2-x11 but it didn't work—what is the difference between the two
packages?

I still feel like it might make sense to either document the behavior better or
to auto-link when it isn't explicitly included in `systemPackages` though.

**Comment by shosti** [comment]
Actually I spoke too soon--it is linked to `/run/current-system/sw/share/themes/` but chromium still isn't picking it up.

**Comment by Mic92** [comment]
this is actually the same as the system-path package:

```
$ ls -al /run/current-system/sw
lrwxrwxrwx 1 root root 55 Jan  1  1970 /run/current-system/sw -> /nix/store/rqgbn2syh1d5av1kb4sl5dkdsi7zmizh-system-path/
```

**Comment by pbogdan** [comment]
@shosti shot in the dark - you wouldn't happen to be running `xsettingsd` or another settings daemon like `gnome-settings-daemon`? Does stop / starting that help at all?

And sorry to bug - @Mic92 @shosti what display manager you are using?

**Comment by shosti** [comment]
Oh, actually I got it working--the problem was that `GTK_DATA_PREFIX` didn't get reset on `nix-rebuild switch`, so I had to log out and log in (it was pointing to the old system path). 

(For the record, using xmonad.)

**Comment by Mic92** [comment]
@pbogdan https://github.com/Mic92/nixos-configuration/blob/master/configuration.nix#L44

**Comment by Mic92** [comment]
I will also port the GUIX patch to nixos: https://github.com/NixOS/nixpkgs/pull/25881
