### ISSUE TITLE
assert in 'users-groups.nix' which requires superuser with password

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#25834]
## Issue description

There is [assert in 'users-groups.nix'](https://github.com/NixOS/nixpkgs/blob/77f572f07234e500d0d3aeecd03a2af96cc3da06/nixos/modules/config/users-groups.nix#L543) which requires superuser with password in order to prevent to ```locks them out of the system```

But it has sense only for workstations.

I just hit this assert falsely the second time, first when made non-interactive test-driver VMs, and now with system with auto-login ```services.xserver.displayManager.auto.enable = true;```

It is easy to work around by setting up a dummy password but it would create a security hole, because that needless superuser password would be stored as plain text in the source code.

**Comment by lheckemann** [comment]
>superuser password would be stored as plain text in the source code.

[not necessarily](https://nixos.org/nixos/options.html#users.users.+hashedpassword)

**Comment by edolstra** [comment]
Yeah, you could use `hashedPassword` to set an impossible password hash (e.g. anything starting with `!`).

But I guess it would be good to have an option to disable this check altogether.
