### ISSUE TITLE
insync: sync does not work due to problem regarding /etc/mtab

### ISSUE THREAD

**Issue by thinkrapido** [NixOS/nixpkgs#258359]
### Describe the bug
After installing and connecting to remote Drive, the syncing is prevented.

![image](https://github.com/NixOS/nixpkgs/assets/1568087/df83e64b-7d36-48e4-8d9a-3e39a8e76537)

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.3881.5cfafa12d573`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(jbc): `"home-manager-23.05.tar.gz"`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
insync version: 3.8.6.50504

**Comment by kossLAN** [comment]
So the behavior I'm currently observing is that a sync location on my main drive does actually sync but still shows this error, however files do not sync when using a different mounted drive. Both instances report the same error however.

**Comment by waldman** [comment]
Got the same error on `unstable` today... I'm installing 23.05 now to see if it works

**Comment by kossLAN** [comment]
That would be because the 23.05 and unstable package are the same package, so the issue persists on both.

**Comment by kossLAN** [comment]
If you want to use the package in some capacity running insync with `insync start --no-daemon` works without error on my end aswell.

**Comment by waldman** [comment]
@kossLAN amazing! Indeed it works! Thanks a ton man! =)))

**Comment by hellwolf** [comment]
I think I fixed it, if anyone wants to give it a try before I merge it to unstable and backport to 23.11: https://github.com/NixOS/nixpkgs/pull/279426

**Comment by Atemu** [comment]
Could someone bisect what caused this issue in the first place?

**Comment by hellwolf** [comment]
> Could someone bisect what caused this issue in the first place?

It seems highly related to bubblewrap, so not many people can do that digging. I am looking into it, but I only started to get familiar with the bubblewarp code in nixpkgs.

**Comment by Atemu** [comment]
You don't need to be familiar with any code in order to bisect, you just need to be able to observe the effects of the code.

I'm the opposite; I'm familiar with the buildFHSEnv code but have never used insync and don't intend to do so.

**Comment by hellwolf** [comment]
@Atemu perhaps you could give some guidelines, is there anyways of "chrooting"/entering into a bubble wrapped environment to debug, with insync qt program itself, it's a bit tricky.




Though, on a quick thought, I could hack it and make it a bash wrapper instead just to debug what's going on.

**Comment by Atemu** [comment]
@hellwolf I've been meaning to give easier access to this sort of thing but haven't found the time to do so.

You should be able to simply replace the `runScript` with `bash` and then run your wrapper manually for debugging purposes. See `steam-run` for inspiration; I intended to emulate that experience.

**Comment by hellwolf** [comment]
FYI: Also, a new package for nautilus users: https://github.com/NixOS/nixpkgs/pull/302422 please give a :+1: for faster merging!
