### ISSUE TITLE
Sage cannot start Jupyter notebook

### ISSUE THREAD

**Issue by Wulfsta** [NixOS/nixpkgs#258458]
### Describe the bug
Running `sage -n jupyter` fails.

### Steps To Reproduce
1. Add `sageWithDocs` to `systemPackages`.
2. Run `sage -n jupyter`.
3. Observe error.

### Additional context
Error log:
```
sage -n jupyter                    
/nix/store/y63dna6c1kbilzzm56l9376xpi0z0mjs-python3-3.10.12-env/lib/python3.10/site-packages/sage/repl/ipython_kernel/install.py:271: UserWarning: the kernel named sagemath does not seem to correspond to this installation of SageMath; check your Jupyter configuration (see https://docs.jupyter.org/en/latest/use/jupyter-directories.html)
  warnings.warn(f'the kernel named {ident} does not seem to correspond to this '
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.0, Release Date: 2023-05-20                    │
│ Using Python 3.10.12. Type "help()" for help.                      │
└────────────────────────────────────────────────────────────────────┘
Please wait while the Sage Jupyter Notebook server starts...
Traceback (most recent call last):
  File "/nix/store/x0v3x539321f7krfhaai5g5mahjj0ka3-sage-with-env-10.0/bin/sage-notebook", line 32, in __init__
    from notebook.notebookapp import main
ModuleNotFoundError: No module named 'notebook.notebookapp'
The Jupyter notebook is not installed (at least not in this Sage installation).
You can install it by running
  sage -i notebook
Alternatively, you can follow the instructions at
  https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation
to use Sage with an existing Jupyter notebook installation.

```

### Notify maintainers

@collares 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.39, NixOS, 23.11 (Tapir), 23.11pre530560.f5892ddac112`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by collares** [comment]
Thank you for the report and sorry for the delay. I'm looking into it now.

**Comment by collares** [comment]
This is a consequence of the `notebook` upgrade in 690e58e11de69953a1e76d0b9cc5f8caee63badd, I will see if there is an option better than waiting for sagemath/sage#36129.

@Wulfsta Is `sage -n nbclassic` an acceptable alternative?

**Comment by Wulfsta** [comment]
> @Wulfsta Is `sage -n nbclassic` an acceptable alternative?

I haven’t really been using the notebook, just writing code and then running it by calling sage. I’m not sure how much benefit there is to using the notebook.

**Comment by zeuner** [comment]
> This is a consequence of the `notebook` upgrade in [690e58e](https://github.com/NixOS/nixpkgs/commit/690e58e11de69953a1e76d0b9cc5f8caee63badd), I will see if there is an option better than waiting for [sagemath/sage#36129](https://github.com/sagemath/sage/pull/36129).

I tried overriding `notebook` back to `6.5.2`, which makes the `notebook.notebookapp` error disappear, but leads to another one:
```
Please wait while the Sage Jupyter Notebook server starts...
Traceback (most recent call last):
  File "/nix/store/5smz6dxvbnw8mrl88nhfzql1fjxzl8s2-python3-3.11.5-env/lib/python3.11/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5smz6dxvbnw8mrl88nhfzql1fjxzl8s2-python3-3.11.5-env/lib/python3.11/site-packages/traitlets/traitlets.py", line 2009, in _resolve_string
    return import_item(string)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/5smz6dxvbnw8mrl88nhfzql1fjxzl8s2-python3-3.11.5-env/lib/python3.11/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_server.contents'
```

**Comment by collares** [comment]
@zeuner Truly sorry for the delay here! Sage 10.3.beta0 has the `notebook` upgrade patch, so it will be easy to import the upgrade patch once we have Sage 10.2 in Nixpkgs. My plan is to do that in the next couple of weeks, but hopefully in the meantime `sage -n nbclassic` is a viable alternative.

**Comment by zeuner** [comment]
Thanks for the pointer, this works fairly well.

Considering the time to expect until upstream has support for recent `notebook`, I'm not sure whether it would make sense to add `nbclassic` as a dependency and document the situation, so users have somewhat seamless access to notebook functionality.

Anyway, I'm glad it's usable for now.

**Comment by zeuner** [comment]
> This is a consequence of the `notebook` upgrade in [690e58e](https://github.com/NixOS/nixpkgs/commit/690e58e11de69953a1e76d0b9cc5f8caee63badd)

Maybe a test can be added that fails when the notebook functionality gets broken. Ideally, this would help catch updates of dependencies that would break it again.
