### ISSUE TITLE
Update request: newsflash 2.3.1 → 3.0.1

### ISSUE THREAD

**Issue by huantianad** [NixOS/nixpkgs#258497]
- Package name: newsflash
- Latest released version: 3.0.1

- Current version on the unstable channel: 2.3.1
- Current version on the stable/release channel: 2.3.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@kira-bruneau 
@Stunkymonkey 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Stunkymonkey** [comment]
please see at #258567 sadly blocked by #247766
