### ISSUE TITLE
Couldn't open links in vscode/ium-fhs with Brave Browser in KDE Plasma.

### ISSUE THREAD

**Issue by kostek001** [NixOS/nixpkgs#258464]
### Describe the bug
Couldn't open links in vscode/ium-fhs with Brave Browser in KDE Plasma.

### Steps To Reproduce
1. Try to open link in vscode-fhs or vscodium-fhs
2. Confirm box will popup
3. After confirmation nothing happens

### Expected behavior
The link opens normally.

### Screenshots
Confirm box:
![image](https://github.com/NixOS/nixpkgs/assets/69671514/4fd50894-f076-45fe-8b44-6a695901256f)

### Additional context
**Solution:
Add execution rights to brave-browser.desktop.**

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.11 (Tapir), 23.11.20230917.970a59b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(kostek): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by SuperSandro2000** [comment]
> Confirm box:

I don't know the language in the screenshot and can't tell you what the actual problem is but it is surely not that chmod +x is missing on the desktop file. I checked some desktop files on my system and they all didn't have it.

**Comment by kostek001** [comment]
Yes, I'm using vscodium-fhs.

When I use Firefox as your default browser, the problem does not occur.
Firefox shortcut by default has execution permissions:
![image](https://github.com/NixOS/nixpkgs/assets/69671514/6f34f32a-8a3b-4500-ab2a-cbd871202ef1)

Confirm box in english:
![image](https://github.com/NixOS/nixpkgs/assets/69671514/dca35e08-e335-4cc2-b10b-4e8e25ad087d)

I can't reproduce this with xdg-open, it only happens in vscod(e/ium)-fhs.
On vscod(e/ium), the problem does not occur.

**Comment by SuperSandro2000** [comment]
> I can't reproduce this with xdg-open, it only happens in vscode/ium-fhs.

I think the problem is generally related to the fhs, similar to #160923

**Comment by kostek001** [comment]
For anyone with this issue, here is fix:
`
xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
  };
`

**Comment by Prn-Ice** [comment]
Remember to restart after adding this, learnt that the hard way.

> For anyone with this issue, here is fix: `xdg.portal = { enable = true; xdgOpenUsePortal = true; };`
