### ISSUE TITLE
pyside6: does not include pyside6-uic

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#258437]
### Describe the bug
pyside6 does not include any of the pyside tooling such as `pyside6-uic`. This is included in `pyside2-tools` but not for pyside6.

### Expected behavior
`pyside6-uic` is an available command and/or is provided by a new package (`pyside6-tools`)

### Additional context
I searched for this on multiple forums. Might be worth looking at this one: https://stackoverflow.com/questions/66672292/how-compile-uic-with-pyside6

### Notify maintainers

@gebner @Enzime

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20230925.6500b45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/i6hq63805y784dml4j8pgkrz3lryxzld-source`
```

**Comment by GetPsyched** [comment]
I'm still fairly unaware of this topic so I could be wrong about this being a "bug". I made this issue so that it's either resolved or I get insight on how to use `pyside6-uic` otherwise.

**Comment by GetPsyched** [comment]
Anything on this?

**Comment by GetPsyched** [comment]
Perhaps [this](https://pypi.org/project/PySide6-Addons/) might be the package that needs bundling?

**Comment by GetPsyched** [comment]
Found it in PySide6 Essentials.

**Comment by GetPsyched** [comment]
Hi, @vegaelle! I've raised an issue for the PySide6 package not including these binaries; track it here #277849.

> However, `PySide6-Essentials` isn’t present in `nixpkgs`, so how did you actually manage to get these binaries running under NixOS?

I wrote a package for it myself. I've PRd it to `nixpkgs` but I build it locally for use currently; find it here: #269569.

**Comment by vegaelle** [comment]
thanks, i did not see this one
