### ISSUE TITLE
Build failure: pyside6

### ISSUE THREAD

**Issue by pearsche** [NixOS/nixpkgs#258442]
### Steps To Reproduce

1. build pyside6
2. fail

### Build log

https://gist.github.com/pearsche/0bd4b22481b6e1d02d5706bb76d1cdda

### Notify maintainers

@gebner @Enzime 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5-zen1, NixOS, 23.11 (Tapir), 23.11.20230927.8a86b98`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `""`
 - nixpkgs: `not found`
```
:sweat_smile: I guess it says not found because i have no channels (i use flakes)

**Comment by Jesin** [comment]
This same failure is causing syncplay to fail to install on my system.

**Comment by pearsche** [comment]
yeah thats how i knew lol

**Comment by chewblacka** [comment]
I'm trying to package something which relies on pyside6. Package builds fine on nixos-stable but fails under nixos-unstable due to pyside6 not building.
