### ISSUE TITLE
electron No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#258560]
In element-desktop, clicking on a picture to open it externally, crashes the application:

```

(electron:190114): GLib-GIO-ERROR **: 12:40:06.281: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

#254423

**Comment by Artturin** [comment]
The pre-built is using wrapGAppsHook https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/electron/binary/generic.nix
So it should be a ok solution for the source built too.

**Comment by yu-re-ka** [comment]
It already was using that (see `pkgs/development/tools/electron/wrapper.nix`), but the hook did not work properly and additional buildInputs were missing.
