### ISSUE TITLE
`stretchly` unable to load preload script welcome.js

### ISSUE THREAD

**Issue by chitao1234** [NixOS/nixpkgs#258542]
### Describe the bug
`stretchly` launches, but cannot select language in the welcome screen. If I open the "preference" from tray, no text is displayed.

### Steps To Reproduce
1. `nix-shell -p stretchly`
2. `stretchly`
3. Use Ctrl+Shift+I to open devtools, found error.

### Expected behavior
The app should display normally.

### Screenshots

![Screenshot_20231002_151349](https://github.com/NixOS/nixpkgs/assets/25598632/934145eb-83f9-4cbc-8664-6471d63aac34)
![Screenshot_20231002_152235](https://github.com/NixOS/nixpkgs/assets/25598632/f50b745c-705e-4d47-b880-2bb69b360483)

### Additional context
Running on NixOS unstable.
The log from devtool:
```
VM4 sandbox_bundle:2 Unable to load preload script: /nix/store/zj6g4zs6jaddv4msa6sf5lbj1pqhjkjb-stretchly-1.8.1/share/stretchly/app.asar/welcome.js
(anonymous) @ VM4 sandbox_bundle:2

VM4 sandbox_bundle:2 Error: module not found: @electron/remote
    at preloadRequire (VM4 sandbox_bundle:2:82751)
    at <anonymous>:3:16
    at runPreloadScript (VM4 sandbox_bundle:2:83503)
    at VM4 sandbox_bundle:2:83762
    at VM4 sandbox_bundle:2:83917
    at ___electron_webpack_init__ (VM4 sandbox_bundle:2:83921)
    at VM4 sandbox_bundle:2:84044
```

### Notify maintainers
@oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4-xanmod1, NixOS, 23.11 (Tapir), 23.11pre529873.8a86b98f0ba1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Charging1948** [comment]
This is still an issue, and i think the current maintainer is @1000101.
