### ISSUE TITLE
NixOS 23.11 — Release Schedule

### ISSUE THREAD

**Issue by figsoda** [NixOS/nixpkgs#258640]
Hi, we are [figsoda](https://github.com/figsoda) & [Ryan Lahfa](https://github.com/RaitoBezarius), the [release managers](https://nixos.github.io/release-wiki/Release-Managers.html) for NixOS 23.11 ("_Tapir_").

We're also happy to work with [Alejandro Sánchez Medina](https://github.com/alejandrosame) and [Lennart](https://lnrt.de/) [Mühlenmeier](https://github.com/riotbib/), who will be the [release editors](https://nixos.github.io/release-wiki/Release-Editors.html) for this NixOS release.

Below you can find the release calendar for the next two months running up to the planned release at the end of November 2023. If something feels unclear to you, don't hesitate to reach out, we are here to guide the process and make sure this will be a satisfying release for all of us.

Stay tuned for updates!

<table>
    <tr>
        <td></td>
        <td>Date</td>
        <td>Affects</td>
        <td>Events</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-10-04</td>
        <td>—</td>
        <td>Start <a href="https://github.com/NixOS/nixpkgs/issues/259040">discussion</a> about "Feature Freeze & Release Blockers" with ecosystem maintainers</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-10-19</td>
        <td>all branches</td>
        <td>Restrict breaking changes to <a href="https://nixos.github.io/release-wiki/Release-Critical-Packages.html">Release Critical Packages</a></td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-10-30</td>
        <td>all branches</td>
        <td>Restrict all breaking changes with the exception of desktop environments</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2023-11-06</td>
        <td><tt>master</tt></td>
        <td>Wait for <tt>staging-next</tt> merge into <tt>master</tt>; begin first <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Begin Zero Hydra Failures campaign</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2023-11-13</td>
        <td><tt>master</tt></td>
        <td>Wait for first <tt>staging-next</tt> merge into <tt>master</tt>; begin second <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>staging</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td rowspan="8">:heavy_check_mark:</td>
        <td rowspan="8">2023-11-20</td>
        <td><tt>master</tt></td>
        <td>Wait for second <tt>staging-next</tt> merge into <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>staging-next</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Mark failing packages as broken</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.11</tt></td>
        <td>Branch-off</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.11</tt></td>
        <td>Tag <tt>23.11-beta</tt> on <tt>release-23.11</tt><br /> and <tt>23.11-unstable</tt> on <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.11</tt></td>
        <td>Create release channels</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.11</tt></td>
        <td>ZHF fixes go into <tt>master</tt> and need to be backported to <tt>release-23.11</tt></td>
    </tr>
    <tr>
        <td><tt>release-23.11</tt></td>
        <td>Prepare for release, finish remaining issues</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-11-29</td>
        <td><tt>release-23.11</tt></td>
        <td>Release! Also, ZHF ends</td>
    </tr>
    <tr>
        <td></td>
        <td>2023-12-09</td>
        <td>—</td>
        <td>Release Retrospective, everyone is invited to give feedback!</td>
    </tr>
</table>

---

## Definitions

- Backport
  - Cherry-picking a change from `master` into `release-23.11`
  - Use the backport action by applying the `backport: release-23.11` tag
- Breaking change
  - A change that is likely to break downstream consumers
- Ecosystem maintainers
  - Maintainer teams that have enabled `enableFeatureFreezePing` in [`maintainers/team-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix)
- [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
  - List of packages that usually cause widespread breakages
- Restriction
  - Changes of the mentioned kind cannot be merged while the restriction is active
- ZHF
  - Zero Hydra Failures
  - Period in which contributors focus on stabilizing packages
  - Usually through PRs targeted at the `master` branch

**Comment by Atemu** [comment]
Yes. In fact that sort of already happened: https://github.com/NixOS/nixpkgs/pull/251878 (part of https://github.com/NixOS/nixpkgs/pull/257792).

**Comment by figsoda** [comment]
The date for restricting breaking changes to Release Critical Packages has been delayed for #241692 (llvmPackages: 11 -> 16 on Darwin and Linux), in particular we are waiting for #253031 and #253009

**Comment by figsoda** [comment]
Breaking changes to [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html) are now restricted. That means the following packages should not receive any more breaking changes:
- `binutils`
- `gcc`
- `glibc`
- `llvm`
- `systemd`

Note that some breaking changes are still in the staging branch, so the master branch will still receive these changes once they are merged in, but other new breaking changes should be held off until branch-off.

**Comment by TheRealGramdalf** [comment]
Apologies if this is the wrong place to ask (yes, I've looked at the Gnome 44 -> 45 PR), but is Gnome 45 aimed for release along with 23.11? I ask primarily because of Gnome Extensions.

**Comment by vcunat** [comment]
Yes, it is.

**Comment by LunNova** [comment]
@figsoda  @RaitoBezarius Looking for input on whether it would be appropriate to merge at this point. It's not intentionally breaking but the answer may still be no as there's risk?

https://github.com/NixOS/nixpkgs/pull/259070#issuecomment-1776030017

**Comment by figsoda** [comment]
Breaking changes are now restricted with the exception of desktop environments.

**Comment by figsoda** [comment]
The first `staging-next` merge into `master` has been delayed since it is still not ready to be merged. Depending on how things go, it is possible that #263535 will be the last staging cycle of this release period, combining the 2023-11-13 and 2023-11-20 checkpoint.

**Comment by mastermach50** [comment]
Will this release support secure boot out of the box?

**Comment by Janik-Haag** [comment]
No but you can watch #263713 for progress.

**Comment by figsoda** [comment]
Branch-off has been postponed since the current procedure doesn't work with the recently added branch protection rules. We will try again tomorrow if we manage to get in contact with one of the repository admins.

**Comment by drakon64** [comment]
> Where can I find the instructions to upgrade from nixos 23.05 to 23.11

https://nixos.org/manual/nixos/stable/#sec-upgrading

**Comment by mastermach50** [comment]
@drakon64 

I did see that article but it seems old as it still refers to 23.05 as the current stable. Should I still follow it?

**Comment by drakon64** [comment]
@mastermach50 Change the channel name to `nixos-23.11` and you should be good.

```
nix-channel --add https://channels.nixos.org/nixos-23.11 nixos
nix-channel --update nixos
```

Then the usual update commands
