### ISSUE TITLE
kdeconnect-kde needs ports 1714:1764 open for udp and tcp

### ISSUE THREAD

**Issue by jtara1** [NixOS/nixpkgs#258690]
### Describe the bug
kdeconnect-kde needs certain ports open for tcp and udp

### Steps To Reproduce
Install the pkg as user or system pkg
```
{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    libsForQt5.kdeconnect-kde
  ];
}
```

```
sudo nixos-rebuild switch
```

Install the app from the relevant app store on your phone

Connect computer and phone to same network.

Attempt to discover device in either app. It's not there.

### Expected behavior
Devices should be available for pairing

### Solution
in your nixos config, add
```
  networking.firewall.interfaces.enp42s0.allowedUDPPortRanges = [
    {
      from = 1714;
      to = 1764;
    }
  ];
  networking.firewall.interfaces.enp42s0.allowedTCPPortRanges = [
    {
      from = 1714;
      to = 1764;
    }
  ];
```
```
sudo nixos-rebuild switch
```

close then open the kdeconnect app on computer

### Additional context
https://userbase.kde.org/KDEConnect#I_have_two_devices_running_KDE_Connect_on_the_same_network.2C_but_they_can.27t_see_each_other

### Notify maintainers

@FRidh 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.20230927.5cfafa1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(j): `""`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

tested with kdeconnect-kde from unstable nixpkgs

**Comment by Shawn8901** [comment]
I assume you should try the module that exists, instead of adding the package manually, as the module does already open the firewall as requested. https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=kdeconnect.enable

**Comment by jtara1** [comment]
That works, thanks.
