### ISSUE TITLE
Wrong default Transmission directory causes service fail to start

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#258636]
https://github.com/NixOS/nixpkgs/blob/3c4a65f323dd8c6ec34b1c1a63eb968b0ee4fb67/nixos/modules/services/torrent/transmission.nix#L339

Default Transmission watch directory is `watchdir` without a hyphen.

When setting `watch-dir-enabled = true;` without the existence of directory `watch-dir`, then Transmission fails on first start.

**Comment by tomodachi94** [comment]
Pinging @ju1m (who has done extensive work on the module) and @astsmtl (the maintainer of the associated package).

**Comment by ju1m** [comment]
@Sepero, AFAICS it was fixed in https://github.com/NixOS/nixpkgs/pull/270034 and backported to `release-23.11` in https://github.com/NixOS/nixpkgs/pull/272957. Please update, I'm closing the issue, please reopen if the problem remains after that.
