### ISSUE TITLE
Update request: gtk4 4.10.4 → 4.13.1

### ISSUE THREAD

**Issue by yuuyins** [NixOS/nixpkgs#258634]
Update https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gtk/4.x.nix to 4.13.1 (https://gitlab.gnome.org/GNOME/gtk/-/tags/4.13.1). Needed for https://github.com/NixOS/nixpkgs/pull/253765. See
- https://github.com/NixOS/nixpkgs/pull/253765#issuecomment-1712910525
- https://gitlab.zrythm.org/zrythm/zrythm/-/blob/master/meson.build?ref_type=heads#L894

---

- Package name: gtk4
- Latest released version: 4.13.1

- Current version on the unstable channel: 4.10.4
- Current version on the stable/release channel: 4.10.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@7c6f434c 

`lib.teams.gnome.members`

@bobby285271
@hedning
@jtojnar
@dasj19
@amaxine

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by jtojnar** [comment]
Part of #247766

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/247766 will have 4.12.3. 

4.13.1 is an unstable release, we likely won't start looking at it before we start packaging GNOME 46.

Looking at [the zrythm commit](https://gitlab.zrythm.org/zrythm/zrythm/-/commit/859879528ef1a31a9fb9a16d758d7420665d684c) that bumps the GTK version requirement, it makes use of `GskPath`, `GskPathBuilder`, according to the [GTK NEWS](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/NEWS), these APIs are still considered experimental, and may change until 4.14.

**Comment by yuuyins** [comment]
@bobby285271 I am sorry, I was confused. Thank you for explaining it to me.

PS: For reference, stable releases are https://gitlab.gnome.org/GNOME/gtk/-/releases
