### ISSUE TITLE
Closure size: Docker depends on GCC and Go

### ISSUE THREAD

**Issue by zielmicha** [NixOS/nixpkgs#25861]
## Issue description

Closure of Docker contains GCC and Go, but there are not needed. [docker/default.nix](https://github.com/NixOS/nixpkgs/blob/f3c989babdcadb296b8e98b8b7572d229a3838fb/pkgs/applications/virtualization/docker/default.nix#L135) at least seems to try to remove the references to GCC, but it fails (`docker` binary contains the string `/nix/store/haqh3hshg8w1779xgyzr4pk9q706ra30-gcc-5.4.0/`).

### Steps to reproduce

```
$ nix-env -i docker
$ du -sch $(nix-store -qR /nix/store/ncx58msanqw9kr713swbrkzv0zn2qjrs-docker-1.10.3) | sort -h 
11M	/nix/store/07axizqswlwc819xcd8dk2m1q0ylddmh-coreutils-8.25
12M	/nix/store/dh5wwrzyva4yp6inmf7534vrnj3hq89l-ncurses-6.0
20M	/nix/store/hz458cm56al0zgn1blrk7fyzbrbxy3fr-systemd-231
22M	/nix/store/98s2znxww6x7h2ch7cj1w5givahxmdna-glibc-2.23
40M	/nix/store/ncx58msanqw9kr713swbrkzv0zn2qjrs-docker-1.10.3
51M	/nix/store/3wl86vswinz1cam7jmzdvvaglg2566l6-python-2.7.12
116M	/nix/store/haqh3hshg8w1779xgyzr4pk9q706ra30-gcc-5.4.0
170M	/nix/store/vdmxbdp21d2fw8dv7d536vyfd9bs6hv1-go-1.4.3
538M	total
```

## Technical details

* System: Ubuntu 16.04
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre87900.c062028"
* Sandboxing enabled: not applicable

**Comment by copumpkin** [comment]
Curious why it depends on python, as well.

**Comment by Mic92** [comment]
618f9aa52c4b5792c86dd8d6f2623f57d5fe930f fixes this on master.

**Comment by copumpkin** [comment]
@Mic92 does that also fix the python dependency?

**Comment by Mic92** [comment]
seems so.

**Comment by copumpkin** [comment]
Thanks!
