### ISSUE TITLE
Update request: komikku 1.23.0 → 1.26.0

### ISSUE THREAD

**Issue by zk395** [NixOS/nixpkgs#258671]
- Package name: komikku
- Latest released version: 1.26.0

- Current version on the unstable channel: 1.23.0
- Current version on the stable/release channel: 1.21.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@chuangzhu @infinitivewitch

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by chuangzhu** [comment]
\>= 1.25.1 depends on gtk 4.12 and libadwaita 1.4, which is currently blocked by #247766. It does seem possible to be updated to 1.25.0 though

**Comment by chuangzhu** [comment]
Oh it uses libadwaita breakpoints since 1.25.0, so we are only able to update it to 1.24.2 for now

**Comment by chuangzhu** [comment]
#270683
