### ISSUE TITLE
Rustup can't find crate "std"

### ISSUE THREAD

**Issue by mythmon** [NixOS/nixpkgs#25863]
## Issue description

After installing rust via rustup (installed via nix-shell or nix-env), trying to build even a simple hello world rust program results in `error[E0463]: can't find crate for 'std'`

I performed these tests on nixpkgs commit 6d599b791ec5d04504b90743447c23d3d23e10fc, which is the latest commit as I am writing this.

### Steps to reproduce

```
[mythmon@gallium:~]$ nix-shell --pure -p rustup
[nix-shell:~]$ BASE=/tmp/rustup-test-$$
[nix-shell:~]$ export RUSTUP_HOME=$BASE
[nix-shell:~]$ export CARGO_HOME=$BASE
[nix-shell:~]$ mkdir $BASE
[nix-shell:~]$ cd $BASE
[nix-shell:/tmp/rustup-test-9987]$ rustup toolchain list
[nix-shell:/tmp/rustup-test-9987]$ rustup toolchain install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.17.0 (56124baa9 2017-04-24)
[nix-shell:/tmp/rustup-test-9987/test_project]$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
[nix-shell:/tmp/rustup-test-9987]$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.17.0 (56124baa9 2017-04-24)
[nix-shell:/tmp/rustup-test-9987]$ cargo new --bin test_project
     Created binary (application) `test_project` project
[nix-shell:/tmp/rustup-test-9987]$ cd test_project
[nix-shell:/tmp/rustup-test-9987/test_project]$ cargo run
   Compiling test_project v0.1.0 (file:///tmp/rustup-test-9987/test_project)
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `test_project`.

To learn more, run the command again with --verbose.
```

## Technical details

* System: 17.09pre106916.c5badb123a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre106916.c5badb123a"
* Sandboxing enabled: build-use-sandbox = false

**Comment by flosse** [comment]
I can agree to this problem (using `17.09pre106299.7f3b857d0d (Hummingbird)`)

**Comment by Mic92** [comment]
Yeah, unfortunately it is still broken. So what I did to run the unmodified toolchain, was to patch rustup to always to pass the executable as first argument to `ld-linux-x86-64.so.2` to avoid the use of patchelf. This worked well, however rust internally uses `/proc/self/exe` to find where its toolchain lives. Usually this works as `rustc` is the `/proc/self/exe`. However in our case it is the link loader `ld-linux-x86-64.so.2` outside of ~/.rustup. This is why everything break horrible. A hack around it, would be to copy `ld-linux-x86-64.so.2` to `~/.rustup/toolchains/<toolchain>/bin`.

I probably will mark this as broken, so other people will not waste their time and use the other options to install rust.

**Comment by retrry** [comment]
What I do in my project. I've added this line to my default.nix shellHook:
```
export RUSTFLAGS="-L $HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/"
```
I don't really like this hardcoded way, but I at least I can use rustup.

**Comment by retrry** [comment]
Also @Mic92 please don't remove it, or at least leave some way of installing it :) For me it is way easier to use rustup for nightly compiler, even with this workaround (my project requires nightly).

**Comment by Mic92** [comment]
oh, good idea. This would be a less uglier workaround, which could be integrate into rustup.

**Comment by bkchr** [comment]
For rust and Nixos I would propose to use the rust-overlay https://github.com/mozilla/nixpkgs-mozilla
Then you don't have to play any environment variable tricks :)

**Comment by Mic92** [comment]
it does not address cross-compilers if I remember correctly.

**Comment by retrry** [comment]
@Mic92 I wasn't able to get cross compiling working. I've tried to compile musl target.

**Comment by Mic92** [comment]
I meant `nixpkgs-mozilla`.

**Comment by bkchr** [comment]
I have a pull request open for cross compilation to support(https://github.com/mozilla/nixpkgs-mozilla/pull/24).

**Comment by joepie91** [comment]
For anybody who has ended up here while trying to figure out how to get Xargo working; you'll want to have a look at mozilla/nixpkgs-mozilla#51, which includes a workaround.

**Comment by unode** [comment]
Any progress here?

I'm currently getting two rustup related issues. The one discussed in this thread and https://github.com/rust-lang-nursery/rustup.rs/issues/1062 which seems to be fixed in newer versions of rustup.

To note, the latest version of rustup at the time of writing is 1.9.0. Nixpkgs has 1.3.0.

**Comment by bkchr** [comment]
Did you tried the overlay? I'm using it for cross compilation.

**Comment by unode** [comment]
Overlay works fine but no rustup there.

**Comment by bkchr** [comment]
Why do you need rustup? Rustup defeats the purpose of Nixpkgs/NixOS(yeah I know, the overlay is also not standard compliant).

**Comment by unode** [comment]
Convinence mostly. Being able to script around rustup and have it work on multiple platforms.

**Comment by bkchr** [comment]
Yeah, that will be complicated on Nixos. The main problem is, that you would need to run `patchelf` manually on the downloaded toolchain. 
I'm currently updating `rustup` and will send a pull request in the next hour, I hope that fixes some of your problems.

**Comment by retrry** [comment]
Are you talking about stable? Because on unstable rustup works correctly.

**Comment by unode** [comment]
I'm talking about nixos-17.09, if that's what you refer by stable.

**Comment by Mic92** [comment]
If you could test if `cbe326feb88c380dbee2a9b500fd32a307f71cf6` works correctly on `17.09`, I can back port this patch.

**Comment by ysndr** [comment]
@Mic92 a quick test today seemed to work alright using the nixpkgs master branch. Can't tell about cross compiling though. Thanks for the effort

**Comment by Mic92** [comment]
backported in b1be17c5870ce5e7f1b4ba29f7ede260ce3ae8b0

**Comment by vandenoever** [comment]
@bkchr  I'd like to experiment with rust for wasm and raspberry on nixos. What is currently best way of compiling for those targets?

**Comment by bkchr** [comment]
I think you should use the Mozilla nix overlay.
```
(latest.rustChannels.nightly.rust.override { extensions = [ "rust-src" ]; targets = [ "wasm-unknown-linux-unknown" ];})
```

That should give you a rust with all the things you need :) (I'm unsure if the target name is correct, but it print a list of available targets if something is not correct)

**Comment by Mic92** [comment]
Rustup also worked for me when I compiled for the musl target. So both the overlay and rustup should be ok.

**Comment by Mic92** [comment]
I think this issue was solved.

**Comment by alehander92** [comment]
i had this problem when copying the `rustc` binary/link from my nix setup instead of linking to it: linking to it resolved it
