### ISSUE TITLE
Add core_bench to ocaml-modules

### ISSUE THREAD

**Issue by pmwhite** [NixOS/nixpkgs#25878]
core_bench is missing from the list of ocaml packages. I would submit a PR myself, but I can't figure out how to make it work. Somebody who knows how could probably do it pretty quickly.

**Comment by Zimmi48** [comment]
See #25658

**Comment by Zimmi48** [comment]
The PR has been merged. This issue should be closed.

**Comment by pmwhite** [comment]
Awesome, well done on the PR; thanks.
