### ISSUE TITLE
Package request: Bruno

### ISSUE THREAD

**Issue by kolaente** [NixOS/nixpkgs#258765]
**Project description**

From their homepage:

> Bruno is a new and innovative open source API client, aimed at revolutionizing the status quo represented by Postman, Insomnia and similar tools out t[here](https://github.com/usebruno/bruno/discussions/269).
>
> Bruno stores your collections directly in a folder on your filesystem. We use a plain text markup language, Bru, to save information about API requests.
>
> You can use git or any version control of your choice to collaborate over your API collections.
> 
> Bruno is offline-only. There are no plans to add cloud-sync to Bruno, ever. We value your data privacy and believe it should stay on your device. Read our long-term vision here.**Metadata**

It's similar to Postman but stores all api requests locally, without vendor lock in or complicated set up.

Looks like an electron app, should be relatively easy to package. We could also patch the appimage they provide.

* homepage URL: https://www.usebruno.com/
* source URL: https://github.com/usebruno/bruno
* license: MIT
* platforms: being an electron app, everything that's supported by electron

**Comment by bew** [comment]
I think there can be a separate package for the CLI as well, which would be very lightweight since it has no dependency on electron.

**Comment by 3rd** [comment]
Packaged by @water-sucks https://github.com/NixOS/nixpkgs/pull/258341
