### ISSUE TITLE
qtcreator fails to build in nixus-unstable

### ISSUE THREAD

**Issue by pbek** [NixOS/nixpkgs#258786]
### Describe the bug

Currently, when I try to "install" qtcreator from nixos-unstable (via nix-shell or via configuration.nix) it tries to build (no cache entry found) and fails.
These are the last lines of the build log:

```
...
qtcreator> /build/qt-creator-opensource-src-11.0.2/src/tools/qml2puppet/qml2puppet/editor3d/generalhelper.cpp:805:12: error: use of undeclared identifier 'mat44'; did you mean 'QSSGUtils::mat44'?
qtcreator>     return mat44::getPosition(sceneTransform);
qtcreator>            ^~~~~
qtcreator>            QSSGUtils::mat44
qtcreator> /nix/store/7fapnghfgj4in7y4xdsklg6r28cbjasy-qtquick3d-6.5.3/include/QtQuick3DUtils/6.5.3/QtQuick3DUtils/private/qssgutils_p.h:66:11: note: 'QSSGUtils::mat44' declared here
qtcreator> namespace mat44 {
qtcreator>           ^
qtcreator> 1 error generated.
qtcreator> [578/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/dockwidget.cpp.o
qtcreator> [579/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/dockoverlay.cpp.o
qtcreator> [580/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/floatingdockcontainer.cpp.o
qtcreator> [581/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/floatingdragpreview.cpp.o
qtcreator> [582/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/dockwidgettab.cpp.o
qtcreator> [583/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/dockcontainerwidget.cpp.o
qtcreator> [584/3893] Building CXX object src/tools/qml2puppet/CMakeFiles/qml2puppet.dir/qml2puppet/editor3d/selectionboxgeometry.cpp.o
qtcreator> [585/3893] Building CXX object src/tools/qml2puppet/CMakeFiles/qml2puppet.dir/qml2puppet/iconrenderer/iconrenderer.cpp.o
qtcreator> [586/3893] Building CXX object src/tools/qml2puppet/CMakeFiles/qml2puppet.dir/qml2puppet_autogen/mocs_compilation.cpp.o
qtcreator> [587/3893] Building CXX object src/libs/advanceddockingsystem/CMakeFiles/AdvancedDockingSystem.dir/dockmanager.cpp.o
qtcreator> [588/3893] Building C object src/libs/sqlite/CMakeFiles/SqliteC.dir/__/3rdparty/sqlite/sqlite3.c.o
qtcreator> ninja: build stopped: subcommand failed.
```

@wineee, do you maybe have the same issue?

### Steps To Reproduce
1. `nix-shell -p qtcreator` while on the unstable channel
2. See above error

### Expected behavior

qtcreator builds or is downloaded from the public cache servers.

### Notify maintainers

@rewine

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11.20230929.f5892dd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

**Comment by pbek** [comment]
I tried three different machines using https://github.com/pbek/nixcfg so far.

**Comment by khaneliman** [comment]
I saw it failed with the current version in unstable, but the version from master built. So you just have to wait until that version is released, I believe.

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/pull/258394 merged to [nixpkgs-unstable](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/development/tools/qtcreator/default.nix) now, it should be merged into the `nixos-unstable` branch soon


A temporary solution is install qtcreator form `nixpkgs-unstable`

`nix profile install github:nixos/nixpkgs/nixpkgs-unstable#qtcreator`

**Comment by pbek** [comment]
Ah, thank you for letting me know, @khaneliman and @wineee! I started worrying it failed just on my systems, because I even tried to pin down qtcreator on my last working flake nixpkgs commit hash, but the build process still failed...

**Comment by pbek** [comment]
`nixos-unstable` was merged and `qtcreator` works again! Thanks a lot!
