### ISSUE TITLE
Package request: SpiderOakONE Backup

### ISSUE THREAD

**Issue by cejsr** [NixOS/nixpkgs#258742]
**Project description**
Backup client from SpiderOak

**Metadata**

* homepage URL:https://crossclave.com/opendownload/#one
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by damccull** [comment]
Also want to use this, but fyi, it's already in nixpkgs. It just can't find the download source, indicating that SpiderOAK the company probably removed the download location. It's trying to get it from https://spideroak.com/release/spideroak/slack_tar_x64, but that no longer seems to exist.
