### ISSUE TITLE
Using `gnu = true;` fails due to `services.xserver.startGnuPGAgent` no longer being an option.

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#258877]
### Describe the bug
When I set `gnu = true;` in `configuration.nix`, the rebuild fails as `services.xserver.startGnuPGAgent` is no longer a valid option.

### Steps To Reproduce
1. Set `gnu = true;`
2. `sudo nixos-rebuild switch`
3. Error thrown:
> Failed assertions:
       - The option definition `services.xserver.startGnuPGAgent' in `/nix/store/bfg7xzgvbhxhs7vnl7lynaxmjhmvc4j0-nixos/nixos/nixos/modules/config/gnu.nix' no longer has any effect; please remove it.
       See the 16.09 release notes for more information.

### Expected behavior
`gnu = true;` should not fail.

### Screenshots
\-

### Additional context
\-

### Notify maintainers
@ajs124 
@pennae 
@prusnak 
@Ericson2314 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre530560.f5892ddac112`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(ashvith): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ajs124** [comment]
Having had a look at that module (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/gnu.nix), IMO it should just be removed.

`lsh`? really?

**Comment by MikaelFangel** [comment]
Other question is when you look at the history they removed lsh 7 years ago because it was unmaintained, but then the commit got reverted later? 🤔

**Comment by Aleksanaa** [comment]
This module doesn't make sense at all. GNU stuff and non-GNU ones usually can't fully replace each other, and it's up to the users to decide which one to use.
