### ISSUE TITLE
python-jenkins-0.4.11 can not be built with pbr 2.0

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#25888]
## Issue description
As per topic.

### Steps to reproduce
Try building pythonPackages.python-jenkins

## Technical details
nixos-unstable channel

Trivial update to python-jenkins-0.4.14 solves the issue.

**Comment by Fuuzetsu** [comment]
update non-trivial, requires `kerberos` dependency addition too; will submit patch sometime if noone does

**Comment by Fuuzetsu** [comment]
To update: I no longer require this myself so it's far lower in queue.

**Comment by matthewbauer** [comment]
Fixed in nixpkgs-unstable.
