### ISSUE TITLE
SSH connection to systemd container freezes

### ISSUE THREAD

**Issue by juselius** [NixOS/nixpkgs#25882]
## Issue description
I create a systemd container with ssh enabled, and log in and create a normal user. I can then successfully ssh into the container, but after 15-30 seconds the connection freezes. It's still possible to log in using `nixos-container login foo`, but no matter what I try the ssh connection remains frozen. Any subsequent attempt to ssh into the container just hangs. In fact, waiting 30-60 seconds after starting the container, sshd is already not responding anymore. There is nothing in the system logs (journalctl) on either side, which would give any clue to what is going on.

### Steps to reproduce
```
# nixos-container create foo --config 'services.openssh.enable = true;'
# nixos-container root-login foo
# useradd foo; passwd foo; exit
$ ssh foo@foo
```
## Technical details

* System: NixOS: 17.09pre107265.0afb6d789c (Hummingbird)
* Nix version: 1.11.9
* Nixpkgs version: 17.09pre107265.0afb6d789c
* Sandboxing enabled: false

**Comment by rnhmjoj** [comment]
I am at 0afb6d789c too but I can't reproduce it. OpenSSH is working fine for me: no freeze or disconnections.

**Comment by Mic92** [comment]
When sshd no longer responds, what it is the output of `systemctl status sshd` in the container?

**Comment by juselius** [comment]
There was no sshd running in the container, and I could not restart the service either. I have no idea what might have happened, but when I create a new container it works perfectly! Something must have gotten corrupted somehow, but how is beyond me.
