### ISSUE TITLE
nixos/paperless: paperless-scheduler.service fails to start: Failed to set up mount namespacing

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#258823]
### Describe the bug
My paperless-ngx install has been broken for some time; it looks like paperless-scheduler.service fails to start, which means that paperless-consumer.service and paperless-web.service can't run:

```
systemd[1]: Starting Paperless Celery Beat...
(re-start)[3839110]: paperless-scheduler.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/paperless-scheduler.service/memory.pressure: No such file or directory
(re-start)[3839110]: paperless-scheduler.service: Failed at step NAMESPACE spawning /nix/store/z7g0qz9wyrhv5qkgmaimbz5ckmv6sflz-unit-script-paperless-scheduler-pre-start/bin/paperless-scheduler-pre-start: No such file or directory
systemd[1]: paperless-scheduler.service: Control process exited, code=exited, status=226/NAMESPACE
systemd[1]: paperless-scheduler.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Paperless Celery Beat.
```

I don't have any idea at all how to debug this, sorry.

### Steps To Reproduce
Steps to reproduce the behavior: `systemctl start paperless-web.service`

### Expected behavior
paperless should work!

### Notify maintainers

paperless-ngx maintainers: @lukegb @gador @erikarvstedt @leona-ya
nixos/paperless maintainers: @erikarvstedt @Flakebi @leona-ya

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4, NixOS, 23.11 (Tapir), 23.11.20230929.f5892dd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by Xyz00777** [comment]
+1 habe die selbe fehlermeldung

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.35, NixOS, 23.11 (Tapir), 23.11pre531320.0c7ffbc66e6d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by erikarvstedt** [comment]
Here's the [failing test on Hydra](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.paperless.x86_64-linux).

**Comment by leona-ya** [comment]
Will try to find this later, or do you want to do that @erikarvstedt?

**Comment by leona-ya** [comment]
Started a bisect.

**Comment by leona-ya** [comment]
The more invasive fix is to set `serviceConfig.ProtectControlGroups=false`. I actually don't know whether this a regression in systemd or intented. Also there's surely a better fix (maybe with the new systemd option `DelegateSubgroup`?), so what should we do?
