### ISSUE TITLE
vscodium doesn't work

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#258836]
### Describe the bug
codium doesn't work

### Screenshots
![Screenshot from 2023-10-03 18-57-50](https://github.com/NixOS/nixpkgs/assets/23100970/82c5529c-82e2-4a71-b470-668a126c1faa)

![Screenshot from 2023-10-03 19-01-27](https://github.com/NixOS/nixpkgs/assets/23100970/a511e5df-157d-4b18-bbb1-ad018d7bea9c)

### Notify maintainers  
@Patrick Hilhorst @nix@hilhorst.be @nix@hilhorst.be
@Bobby Rong @https://github.com/bobby285271 @rjl931189261@126.com
@Ludovico Piero @lewdovico@gnuweeb.org @lewdovico@gnuweeb.org

```
[root@97a3e1b08:/var/log/journal/0b8a5b5426d54d63a9b6dcaf89a9d503] nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre530560.f5892ddac112`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Nyabinary** [comment]
Try deleting the vscodium folder and trying again

**Comment by kouyk** [comment]
> Try deleting the vscodium folder and trying again

I don't think this works, if you run `codium --verbose` it will complain about linking failure, with the most relevant line below:

```
[151946:1003/105146.180005:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
```

Running `codium --disable-gpu` will work, but without graphic acceleration rendering might be more CPU intensive.

**Comment by bobby285271** [comment]
https://github.com/microsoft/vscode/issues/190437

**Comment by SeineEloquenz** [comment]
Try removing `.config/VSCodium/GPUCache`, this solved the problem for me.

**Comment by futu2** [comment]
Any gpu info?
It seems a common problem for electron app.
https://nixos.wiki/wiki/Wayland
```nix
environment.sessionVariables.NIXOS_OZONE_WL = "1";
```
It works for me
