### ISSUE TITLE
Package request: SearXNG

### ISSUE THREAD

**Issue by gianmarcogg03** [NixOS/nixpkgs#258844]
**Project description**

SearXNG is a privacy-friendly meta-search engine, derived from the old Searx project, which aggregates results from more than 70 search services.

**Metadata**

* homepage URL: https://searxng.org
* source URL: https://github.com/searxng/searxng
* license: AGPL v3
* platforms: Linux

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/web-apps/searxng/default.nix
