### ISSUE TITLE
Reduce target host ssh roundtrip by moving `systemd-run` logic out of `nixos-rebuild`

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#258974]
When using `--target-host`, this is an extra ssh roundtrip that could be avoided if we make `switch-to-configuration` responsible for re-execing itself in `systemd-run` - ie move all the new logic into that command (or a custom wrapper for it).

_Originally posted by @roberth in https://github.com/NixOS/nixpkgs/pull/258571#discussion_r1345481867_

**Comment by Majiir** [comment]
Not only is it another roundtrip, it also adds another `sudo` invocation with `--use-remote-sudo`. A simple `nixos-rebuild boot` can require entering the password three times, users with a security key must enter a PIN or confirm user presence three times, etc.

**Comment by roberth** [comment]
I've written a design for a solution to this problem among others in #266290.
