### ISSUE TITLE
borgbackup not cached and unable to build

### ISSUE THREAD

**Issue by onemoresuza** [NixOS/nixpkgs#259000]
### Describe the bug

the [borgbackup package][borgbackup] is not cached and fails to build on rev [f227f12][rev] of the `nixpkgs-unstable` channel.

[borgbackup]: <https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/backup/borgbackup/default.nix>
[rev]: <https://github.com/NixOS/nixpkgs/commit/f227f12d246b1e7916993c1e4c66f9f185d94586>

### Steps To Reproduce
1. `nix-shell -p borgbackup`

### Expected behavior
The `borgbackup` package should be downloaded from `https://cache.nixos.org`.

### Additional context
Here are the last ten log lines:

> error: builder for '/nix/store/x21rz472mf8xp1agihjympbg8bjp8msj-borgbackup-1.2.6.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED archiver.py::RemoteArchiverTestCase::test_sparse_file - AssertionError: 2 != 0
       > FAILED archiver.py::RemoteArchiverTestCase::test_strip_components - AssertionError: 2 != 0
       > FAILED archiver.py::ArchiverCorruptionTestCase::test_cache_files - AssertionError: 2 != 0
       > FAILED archiver.py::RemoteArchiverTestCase::test_symlink_extract - AssertionError: 2 != 0
       > FAILED archiver.py::ArchiverCorruptionTestCase::test_chunks_archive - AssertionError: 2 != 0
       > FAILED archiver.py::ArchiverCorruptionTestCase::test_old_version_interfered - AssertionError: 2 != 0
       > FAILED archiver.py::DiffArchiverTestCase::test_sort_option - AssertionError: 2 != 0
       > FAILED archiver.py::DiffArchiverTestCase::test_time_diffs - AssertionError: 2 != 0
       > ================ 406 failed, 865 passed, 261 skipped in 29.03s =================
       > /nix/store/3pfjacvdg9f491lfqc9qb2d0nknx73fb-stdenv-linux/setup: line 1596: pop_var_context: head of shell_variables not a function context

Checking the full log, the following message appear after most, if not all, errors:

> ----------------------------- Captured stdout call -----------------------------
You do not have a supported version of the msgpack python package installed. Terminating.
This should never happen as specific, supported versions are required by our setup.py.
Do not contact borgbackup support about this.

### Notify maintainers

@dotlambda @globin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(user1): `"nixpkgs"`
 - channels(nix-tf): `"nixgl, nixpkgs"`
 - nixpkgs: `/home/user1/.nix-defexpr/channels/nixpkgs`
```

**Comment by sciyoshi** [comment]
will be fixed upstream with https://github.com/borgbackup/borg/pull/7851

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/258881

**Comment by lodi** [comment]
Thank you very much!
