### ISSUE TITLE
qpwgraph: UI missing top toolbar

### ISSUE THREAD

**Issue by nPrevail** [NixOS/nixpkgs#259134]
### Describe the bug
The UI doesn't properly appear when running the package. UI is missing the main toolbars at the top.

### Steps To Reproduce
1. Run the package

### Screenshots
![Screenshot from 2023-10-05 00-50-20](https://github.com/NixOS/nixpkgs/assets/57690587/886ee4fc-d9aa-40ce-b88f-5f495cb6670a)

### Additional context
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

### Notify maintainers
@kanashimia @exi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.05 (Stoat), 23.05.4065.3b79cc4bcd9c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by FraYoshi** [comment]
Have the same problem on Arch Linux. running on xorg
```
qpwgraph 0.5.3
Qt: 6.5.3
libpipewire: 0.3.80 (headers: 0.3.79)
```

**Comment by dsheeler** [comment]
Ctrl-m toggles the menu. I had the same problem :).

**Comment by FraYoshi** [comment]
I actually stopped using qpwgraph because of this 😅
I think it should be somewhat notified the first time that shortcut is pressed, accidentally or not.. Found out totally randomly a month ago.. but forgot there was this issue opened.. Thanks @dsheeler for the ping!
Yes, it was the shortcut also for me : )

**Comment by nPrevail** [comment]
> Ctrl-m toggles the menu. I had the same problem :).

This solution works! Thank you!
