### ISSUE TITLE
obs-studio is vendoring libcef

### ISSUE THREAD

**Issue by deviant** [NixOS/nixpkgs#259165]
## Issue description

libcef is [vendored into obs-studio](https://github.com/NixOS/nixpkgs/blob/275432f57622307e7d829f82fee58a71d45129ca/pkgs/applications/video/obs-studio/default.nix#L117-L127). Space-wise this is a little wasteful, and makes tracking file provenance less easy. If possible, it would be preferable to use symlinks instead.

[Quoting @delroth](https://github.com/NixOS/nixpkgs/issues/258048#issuecomment-1748663865):

> OTOH if this is really just vendored without any modifications it should probably be symlinked instead. Not only would that help us with security tracking in cases like this, but it's a 300MB binary duplicated for (likely?) no good reason.

**Comment by materusPL** [comment]
Since my change is merged, everything related to libcef should be symlinked.
