### ISSUE TITLE
Valgrind's memcheck reporting many false positives

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#25917]
## Issue description
This issue is caused by 33ff74ced6faad7fe15b3724c453d8646e10b6e5, which removes the valgrind suppressions in libdrm introduced by 6437b2108d7d0a576d290f9d3071c47665c86a90.

### Steps to reproduce
Save as sdltest.c:
```c
#include <SDL2/SDL.h>
#include <time.h>

int main() {
    SDL_Init(SDL_INIT_VIDEO);
}
```
Save as default.nix:
```nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  src = lib.cleanSource ./.;
  name = "sdltest";
  buildInputs = [SDL2];
  phases = [ "unpackPhase" "buildPhase" ];
  buildPhase = ''
    mkdir -p $out/bin
    gcc -o $out/bin/sdltest sdltest.c -lSDL2
  '';
}
```
Build and run `valgrind result/bin/sdltest`. This should not produce any errors, but does.

## Technical details

- Sandboxing enabled: yes
- System: 17.03.1123.4a7a03913d (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1123.4a7a03913d"

**Comment by lheckemann** [comment]
@wkennington @vcunat thoughts on how to deal with this? It makes valgrind practically unusable for GUI applications, but fixing that, as mentioned in 6437b21, introduces new mass-rebuild chains.

**Comment by vcunat** [comment]
I suspect libdrm isn't the only problem there at all.  Looking at valgrind's default.supp, there are lines like `/usr/*lib*/libXaw.so*` which just won't match on nix packages.  For libdrm and other missing stuff we only need to append to valgrind's default.supp file; I thing it shouldn't be difficult to find the suppressions in libdrm's tarball and valgrind's builder can do that.

Side note: I don't think valgrind would automatically find the libdrm suppression file anyway, as they're in different prefixes.

**Comment by lheckemann** [comment]
So we create the dependency the other way round, just adding libdrm's suppressions into valgrind's defaults?

**Comment by vcunat** [comment]
Build-time dependency on the tarball is a rather light thing IMO.

**Comment by lheckemann** [comment]
Of course, it was just to confirm my understanding of what you said. I'll have a look and see if I can work this out.

**Comment by lheckemann** [comment]
By the looks of it, libdrm actually contains [code](https://cgit.freedesktop.org/mesa/drm/tree/intel/intel_bufmgr_gem.c#n1219) that instructs valgrind to ignore some regions as opposed to using a simple suppression list at runtime, so this approach won't be possible.

**Comment by vcunat** [comment]
Oh, I see.  Basically all of the build-time closure bloat comes from gdb, so I think it will be enough to just avoid that dependency.

**Comment by lheckemann** [comment]
Is the build-time closure size actually the problem though, as opposed to the mass-rebuild chains? Because so much depends on libdrm, and that would mean that every change to valgrind would also mean a rebuild of libdrm...

**Comment by vcunat** [comment]
Rebuild can only be caused by something in build-time closure, so it's basically the same.  I don't think valgrind itself changes a lot (or perl &ndash; the other dependency).

I'd suggest f99114e59a6d8 for the next staging iteration.  If valgrind should be changing a lot, we could refine how `valgrind-light` is created; only a few headers are needed for libdrm.

**Comment by lheckemann** [comment]
Oh right, of course. Great!

**Comment by lheckemann** [comment]
So what's the plan for that to get into nixpkgs? Will you PR it to staging at some point?

**Comment by vcunat** [comment]
Right, I pushed it to staging now.

**Comment by lheckemann** [comment]
Thanks!

**Comment by vcunat** [comment]
Binaries in cache, commit in master.  I hope it really helps the valgrind output.

**Comment by lheckemann** [comment]
By the looks of it mesa needs support for it too. 6e26510cfe7d52de405334584a9bc1af7ab65332 should do the trick, I think.
