### ISSUE TITLE
Update request: transformers 4.33.2 → 4.34.0

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#259167]
- Package name: python310Packages.transformers
- Latest released version: 4.34.0

- Current version on the unstable channel: 4.33.2
- Current version on the stable/release channel:

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@pashashocky @happysalada

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by happysalada** [comment]
Hey thank you for coming here !
Do you know how to make an update PR ?

You can use nix-update .
If you want detailled instructions, just let me know.
If you make a PR i can help get it merged.

**Comment by suhr** [comment]
Updating `transformers` requires updating `tokenizers` together with the `Cargo.lock` file. So applying `nix-update` is not sufficient.

**Comment by suhr** [comment]
This error of nix-update proves it: https://gist.github.com/suhr/5bf624db1f6b823cb45e2907c6052867

**Comment by happysalada** [comment]
If you look at the error message, its a 404 error.
The release tag format has changed. You will need to change the rev attribute to remove the python- prefix.
Does this make sense ?

**Comment by suhr** [comment]
Already did that, but there was a different error. Probably because the dirs of the repo also changed.

I appreciate the "go fix it yourself" attitude and even would rather go fix it myself, if it was not for python. With python packaging I always expect a lot of extra mess to unfold, so I prefer to let the nixpkgs experts to fix it.

I also consider packaging llama-cpp-python instead, since packaging is easier with C++.

**Comment by happysalada** [comment]
If you open a PR with what you have and the error , im happy to have a look at it. Any contribution is appreciated. If youre short in time, ill have a look at this this weekend.
