### ISSUE TITLE
Build failure: python311Packages.moddb a dependency of lutris on staging-next

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#259290]
### Steps To Reproduce

1. build python311Packages.moddb

### Build log

https://hydra.nixos.org/build/237091074/nixlog/2

```
ImportError: cannot import name 'RequestRate' from 'pyrate_limiter' (/nix/store/ihs3g4hh44yl0fqhxm2f8rzvyjfmcwgk-python3.11-pyrate-limiter-3.1.0/lib/python3.11/site-packages/pyrate_limiter/__init__.py)
```

### Additional context

Upstream issue https://github.com/ClementJ18/moddb/issues/36

```nix
  postPatch = ''
    # RequestRate in pyrate-limiter has been renamed to Rate
    substituteInPlace moddb/{client.py,utils.py} \
      --replace "RequestRate" "Rate"
  '';
```

Did not work
`python3.11-moddb> AttributeError: 'Rate' object has no attribute 'now'`

### Notify maintainers

@Kranzes @Madouura

**Comment by vcunat** [comment]
https://github.com/ClementJ18/moddb/pull/44#issuecomment-1928000065

**Comment by K900** [comment]
Let's just revert it again: https://github.com/NixOS/nixpkgs/pull/297130

**Comment by vcunat** [comment]
Let's hope it stays this time.
