### ISSUE TITLE
syncthing fails to delete old folders

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#259256]
### Describe the bug
if a folder is a substring of another folder, we don't delete it even if we have overrideFolders and the substring id got removed from the config.

### Steps To Reproduce
1. define a folder with id "xxx"
2. define a folder with id "yyyzzzxxx";
3. remove folder with id "xxx" from config
4. it never gets removed

### Expected behavior
folder "xxx" should have been removed after removing it from config 

### Notify maintainers
@doronbehar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by doronbehar** [comment]
> * define a folder with id "xxx"
> 
> * define a folder with id "yyyzzzxxx";

Thanks for spotting the issue and reporting :) It sounds to me like a `grep -q` issue not being accurate... Maybe only the 1st commit in https://github.com/NixOS/nixpkgs/pull/259259 does the job?

**Comment by Lassulus** [comment]
yes, the first commit solves the issue with substring ids. the second commit solves the issue with ids like "hello/world". I tried escaping the id to send a DELETE request but couldn't find out how to correctly escape the / in the id

**Comment by doronbehar** [comment]
> yes, the first commit solves the issue with substring ids. the second commit solves the issue with ids like "hello/world". I tried escaping the id to send a DELETE request but couldn't find out how to correctly escape the / in the id

I'd never imagine someone would do that LOL. What if we'd impose a check in the module that would prevent such ids? Is it even supported upstream?

**Comment by Lassulus** [comment]
well it works in the webinterface. so it seems supported? also the default value for the id in our nixos module is the key, which also is the path. I usually do something like

```
settings.folders."/home/lass/sync".devices = [ "laptop" "desktop" ];
```

so all those ids are broken. as a workaround we could replace all / in the id, but that would break interaction with non nixos setups. PUTing the config seems to not have that issue. Were there any problems with PUTing the config if we want to override folders and devices anyway?

**Comment by doronbehar** [comment]
> I usually do something like
> 
> ```
> settings.folders."/home/lass/sync".devices = [ "laptop" "desktop" ];
> ```

Could you perhaps give more context? I don't understand what kind of a json object is passed to the `jq` commands when you do that. I also observed in the below code that "/" are taken care of in a special way?

https://github.com/NixOS/nixpkgs/blob/34585a2b76ea47c98cf23217a0afba607aca4ed6/nixos/modules/services/networking/syncthing.nix#L328-L342

> Were there any problems with PUTing the config if we want to override folders and devices anyway?

As I in #259259, I don't like how the code diverges in the `if else`, and it seems to me it doesn't handle the case where you want to delete a stale folder, and you don't `overrideDevices`.

**Comment by Lassulus** [comment]
yeah the PR sadly isn't complete, I just used it as a test for my local systems where I just override everything. I guess we need to handle individual overrides better, but not sure how.

setting
```
settings.folders."/home/lass/sync".devices = [ "laptop" "desktop" ];
```

wold result in a nixos configuration of
```
settings.folders."/home/lass/sync" = {
  path = "/home/lass/sync";
  id = "/home/lass/sync";
  devices = [ "laptop" "desktop" ];
};
```

when I initially wrote this module this seemed unique enough and like a sane default. I thought about hashing the key for the id, but this would have ended in unnecessary long keys.

**Comment by doronbehar** [comment]
I see. I think that using such IDs for folders and devices is very uniqe usage... I tend towards suggesting to take the 1st commit of the PR, and `throw` a message when evaluating the script, in case the folders' IDs contain "/", _and_ `overrideFolders` is true. However, that would not solve your particular, usage. Perhaps we can talk with upstream about it? They are rather responsive from my experience.

**Comment by Lassulus** [comment]
that sounds like an idea. I'm busy the next couple of days, but you can cherry pick the first commit from my PR and close it and we will continue with this once we have some better idea how to handle things and we maybe have an answer from upstream?
