### ISSUE TITLE
Update request: peazip 9.9.0 → 9.4.0

### ISSUE THREAD

**Issue by donovanglover** [NixOS/nixpkgs#259270]
- Package name: peazip
- Latest released version: 9.4.0
- Current version on the unstable channel: 9.9.0
- Current version on the stable/release channel: n/a

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@auroraanna Looks like upstream released [9.9.0](https://github.com/peazip/PeaZip/tags) by mistake and the latest version is actually 9.4.0.

**Comment by auroraanna** [comment]
Yep, the developer even told me that 9.9.0 was an accident but I must've forgot when making the PR. Makes me wonder why he didn't take the tag down again.
