### ISSUE TITLE
splix: Is `DISABLE_JBIG=1` still needed?

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#25929]
I note that the `splix` package sets `DISABLE_JBIG=1` in
`makeFlags`.[(1)] OpenPrinting.org says [(2)] that the reason to
disable "JBIG" is patent concerns, that disabling it removes support
for many printers, and that "The patent will expire on April 4, 2012".
Given the last, need we still disable this feature?

[(1)]: <https://github.com/NixOS/nixpkgs/blob/8e462995ba6deaeec9fd6dc6d3b9a110c08e5955/pkgs/misc/cups/drivers/splix/default.nix#L14>
[(2)]: <https://openprinting.org/driver/splix/license>

**Comment by peti** [comment]
I don't think so. openSUSE enabled it, too. Other distributions might have done the same, not sure.

**Comment by peti** [comment]
A PR that implements this change request would be very welcome. I'd rather not have this issue lying around, though, without someone having committed to actually work on it.
