### ISSUE TITLE
Package request: vesktop / vencord-desktop

### ISSUE THREAD

**Issue by bayazidbh** [NixOS/nixpkgs#259297]
**Project description**

> A cross platform electron-based desktop app aiming to give you a snappier Discord experience with Vencord pre-installed

Basically just Discord with Vencord pre-installed. There is already a [webcord-vencord](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vencord) package, but I prefer using Vesktop which is more directly maintained by Vencord for Vencord.

**Metadata**

* homepage URL: https://vencord.dev/
* source URL: https://github.com/Vencord/Vesktop
* license: [GPL-3.0 license](https://github.com/Vencord/Vesktop/blob/main/LICENSE)
* platforms: Linux (Darwin option also exists I think?)

**Comment by eclairevoyant** [comment]
How is this different from below?
```nix
(pkgs.discord.override {
  withVencord = true;
})
```

**Comment by bayazidbh** [comment]
It doesn't seem to be fully finished yet, but for a cursory looks, they've added some things to be built in into their client:

> Vesktop (AppImage version)

![image](https://github.com/NixOS/nixpkgs/assets/26621899/da9d32b3-2e8e-49c8-a9f0-09c3e24347e9)

> (pkgs.discord.override { withVencord = true; })

![image](https://github.com/NixOS/nixpkgs/assets/26621899/fda1bf7f-80fc-4c21-8e08-41bfee1acf5a)
