### ISSUE TITLE
kdiff3: segfault on quit

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#259257]
### Describe the bug
KDiff3 produces a segmentation fault on quitting instead of exiting cleanly.  This makes it unusable as a Git mergetool, because it always reports failure.

### Steps To Reproduce
1. From a terminal, run `kdiff3`
2. Dismiss the file-selection dialog.
3. Invoke the "Quit" command via either <kbd>Ctrl+Q</kbd> or the menu File->Quit

### Expected behavior
Kdiff3 exits cleanly (exit code `0`) and without errors.

### Additional context
This is a regression in `1.10.5`, as the issue is not present in `1.10.4`.

### Notify maintainers
@peterhoeg 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.53, NixOS, 23.11 (Tapir), 23.11.20230917.970a59b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by peterhoeg** [comment]
Indeed. I'll need to take a look.
