### ISSUE TITLE
Manual does not list types.attrs as possible option type

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#25935]
## Issue description

https://nixos.org/nixos/manual/#idm140737315352288 lacks `types.attrs`.

**Comment by joachifm** [comment]
This could be a simple oversight, but it's possibly best left unmentioned to encourage use of `attrsOf`  or submodules instead, which I believe offer better docs and type checking compared to `attrs`.

**Comment by nh2** [comment]
@joachifm These two types don't seem to address the case though when you don't have any information to typecheck on, for example for an option that allows an arbitrary set of unknown contents that the user may specify (e.g for the purpose of turning it into JSON).

Neither submodules nor `attrsOf` seem to address that use case.

Also, it seems to me that in any case a documented option that suggests better alternatives (as you did here) is better than an undocumented option that doesn't suggest anything.

**Comment by joachifm** [comment]
Sure, what I mean is it's not that often that "stuff" is the best you can do in describing the values an option can take on, and it can become an easy out in cases where you just can't be bothered to specify a proper type.

**Comment by Ekleog** [comment]
`types.attrs` is now documented.
