### ISSUE TITLE
Update request: soundconverter 4.0.3 → 4.0.4

### ISSUE THREAD

**Issue by bayazidbh** [NixOS/nixpkgs#259338]
- Package name: soundconverter
- Latest released version: [4.0.4](https://github.com/kassoulet/soundconverter/releases/latest)

- Current version on the unstable channel: [4.0.3](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=soundconverter)
- Current version on the stable/release channel: [4.0.3](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=soundconverter)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jakubgs 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by jakubgs** [comment]
There is a PR, but it's stuck:

* https://github.com/NixOS/nixpkgs/pull/259343

Specifically due to [this comment about multiple wrappers](https://github.com/NixOS/nixpkgs/pull/259343#discussion_r1475495667).

I wasn't able to make it work without that wrapper and I don't have the time.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/324731
