### ISSUE TITLE
Package request: wazuh

### ISSUE THREAD

**Issue by homelabhero** [NixOS/nixpkgs#259304]
**Project description**

Wazuh is a security agent used to collect data on the host to upload to the centralized logging server. 

**Metadata**

* homepage URL: https://wazuh.com/
* source URL: https://github.com/wazuh/wazuh
* license: GNU General Public License (version 2)
* platforms: linux, darwin

**Comment by MikaelFangel** [comment]
Closed as duplicate of #230623.

**Comment by AkechiShiro** [comment]
@MikaelFangel I do believe this is not a duplicate there is both wazuh the wazuh server and wazuh-agent which connects to the server, is that correct ? @homelabhero ?

**Comment by MikaelFangel** [comment]
The description of this issue describes the agent and the title of the other issue is wazuh-agent. Hence, I assume that both issues are requesting the agent. 😊

**Comment by AkechiShiro** [comment]
You are correct, sorry for jumping too fast to the wrong conclusion, I should've taken more time to read this issue.
