### ISSUE TITLE
Build failure: retroarchFull (various packages, unstable,23.05)

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#259488]
### Steps To Reproduce

1. build retroarchFull

### Build log

```
trying https://github.com/libretro/mame/archive/f7761a9902d59030882c58d4482446196e748c50.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  177M    0  177M    0     0  1442k      0 --:--:--  0:02:06 --:--:-- 1425k
unpacking source archive /tmp/nix-build-source.drv-0/f7761a9902d59030882c58d4482446196e748c50.tar.gz
hash mismatch in fixed-output derivation '/nix/store/4gg4hbm3ipmkgqr9248qgqb5r34ghxa1-source':
  wanted: sha256:0y23ijwhibzys8yvi5ymkxdrss8xwpj7s0xfcb01d23xrc0dczl3
  got:    sha256:1gadbzz3vp69yrzbg1n6x6kd2b6ayckbjr9dx5xi02smsm3b5fdw
cannot build derivation '/nix/store/qc0kglbn6pfvpg30byca7zi7wls6fcbd-libretro-mame-unstable-2023-03-13.drv': 1 dependencies couldn't be built
building '/nix/store/rbcag54mwns1941ly17lvnl6z074hnyg-source.drv'...
cannot build derivation '/nix/store/cwrrrpv5cm8s7gwqxhx89c3gcfvg48q8-retroarch-with-cores-1.15.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/cwrrrpv5cm8s7gwqxhx89c3gcfvg48q8-retroarch-with-cores-1.15.0.drv' failed
```

### Additional context

The hash at https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/emulators/retroarch/hashes.json#L223 does not match what is downloaded. Does anyone have the previous download of https://github.com/libretro/mame/ rev  f7761a9902d59030882c58d4482446196e748c50 available, so we can see what was changed?

I tried checking out f7761a9902d59030882c58d4482446196e748c50 by git, and diffing it with the derivation output got this:
```
diff -Naurd x/3rdparty/lua-zlib/lua_zlib.c y/3rdparty/lua-zlib/lua_zlib.c
--- x/3rdparty/lua-zlib/lua_zlib.c	2023-10-07 01:39:23.859671334 +0200
+++ y/3rdparty/lua-zlib/lua_zlib.c	1970-01-01 01:00:01.000000000 +0100
@@ -392,7 +392,7 @@
 
     SETLITERAL("_COPYRIGHT", "Copyright (c) 2009-2010 Brian Maher");
     SETLITERAL("_DESCRIPTION", "Yet another binding to the zlib library");
-    SETLITERAL("_VERSION", "lua-zlib $Id: b619258c75f480717fad20c113c3b1a35f888ce0 $ $Format:%d$");
+    SETLITERAL("_VERSION", "lua-zlib $Id: b619258c75f480717fad20c113c3b1a35f888ce0 $ ");
 
     /* Expose this to lua so we can do a test: */
     SETINT("_TEST_BUFSIZ", LUAL_BUFFERSIZE);
```
(`x` being the git checkout, `y` the derivation output)

A similar diff could also be observed for https://github.com/NixOS/nixpkgs/issues/259462

Could better reproducibility be achieved by using `fetchgit` instead of `fetchFromGitHub` here?

### Notify maintainers

@matthewbauer @aanderse @edwtjo @MP2E @thiagokokada @kolbycrouch

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/jlx0nh7j7lfsi1sfjlvsp7f0bfjgnnaf-nix-info
copying path '/nix/store/jlx0nh7j7lfsi1sfjlvsp7f0bfjgnnaf-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-23-amd64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixpkgs-23.05.4065.3b79cc4bcd9c, nixos-23.05-23.05.4065.3b79cc4bcd9c"`
 - nixpkgs: `/nix/store/7nxyk1qxrsgc84pqxyb6xmlrillay4nh-nixpkgs-23.05.4065.3b79cc4bcd9c/nixpkgs`
```

**Comment by Artturin** [comment]
It's an issue in the https://github.com/libretro/mame/archive/3d612fb19eb95c0ae322c3cab343857b14a65a9c.tar.gz too so it's not an issue in our fetchers

**Comment by zeuner** [comment]
I don't know. Just noticing that in presence of such GitHub HTTPS URL content weirdness, using `fetchgit` like this (https://github.com/zeuner/nixpkgs/commit/b4da7790568bb8b3847367fe1a9133cbc794e7f5) allowed me to retrieve the source code of some cores in a way so it matched the hashes in `hashes.json`. Which makes kind of sense considering that git was designed to have an immutable and hash-protected history, while HTTPS URLs on some web server provide no such guarantee.

Of course, if there is a better way to solve this, I'm also happy.

**Comment by thiagokokada** [comment]
At https://github.com/NixOS/nixpkgs/pull/308926 I added `fetch_submodule=True` to force a `git clone` instead of fetching the tarballs from GitHub.

I think this fixes the issue, but if the issue persists please open another issue.
