### ISSUE TITLE
Package request: overskride

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#259489]
**Project description**

A simple yet powerful bluetooth client. 

**Metadata**

* homepage URL: https://github.com/kaii-lb/overskride
* source URL: https://github.com/kaii-lb/overskride
* license: gpl3
* platforms: linux

**Comment by eclairevoyant** [comment]
This one needs libadwaita >= 1.4, which is blocked by #247766; also, it seems very new and lacking in basic functionality
