### ISSUE TITLE
[qt5] chmod: operation not permitted on Darwin

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#25946]
## Issue description

Lots of qt5 submodules on Darwin fail with the same error:

```
chmod: changing permissions of '/nix/store/zmp7bafl20xm82gqx3wdjidmkalhpnc9-qtx11extras-5.8.0/lib/cmake/Qt5/Qt5Config.cmake': Operation not permitted
```

It seems like it should be a straightforward fix but I can't figure out where the chmod is coming from. Here's a list of them:

- qtx11extras
- qtsvg
- qtxmlpatterns
- qttools
- qtsvg
- qtserialport
- qtserialport

full hydra build log: http://hydra.nixos.org/build/52892789/nixlog/1

/cc @ttuegel @periklis @acowley @copumpkin @LnL7

**Comment by periklis** [comment]
does it work again?

**Comment by matthewbauer** [comment]
@periklis 

The build log seems to not have the issue:

https://hydra.nixos.org/build/62739078

Are you still getting a similar problem?
