### ISSUE TITLE
Build failure: systemd >=254-rc1 (cross-compiling to armv7l-linux)

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#259400]
### Steps To Reproduce

1. build *pkgsCross.armv7l-hf-multiplatform.systemd*

### Build log

```
[649/1779] Generating src/boot/efi/addonarm.efi.stub with a custom command
FAILED: src/boot/efi/addonarm.efi.stub 
/build/source/tools/elf2efi.py --version-major=254 --version-minor=0 --efi-major=1 --efi-minor=1 --subsystem=10 --minimum-sections=7 src/boot/efi/addonarm.elf.stub src/boot/efi/addonarm.efi.stub
Traceback (most recent call last):
  File "/build/source/tools/elf2efi.py", line 593, in <module>
    main()
  File "/build/source/tools/elf2efi.py", line 589, in main
    elf2efi(parser.parse_args())
  File "/build/source/tools/elf2efi.py", line 493, in elf2efi
    pe_reloc_s = convert_elf_relocations(elf, opt, sections)
  File "/build/source/tools/elf2efi.py", line 384, in convert_elf_relocations
    raise RuntimeError("ELF .dynamic section is missing.")
RuntimeError: ELF .dynamic section is missing.
```

Full log: https://gist.github.com/2xsaiko/8543deb0e54d467ef71d177e0079a173

### Additional context

Bisected to fe6e29938174d1548bdcf02e0100824b272442ed.

### Notify maintainers

@flokli @Kloenk @Mic92 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11.20231005.9aae4ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by 2xsaiko** [comment]
Same issue on master, since that PR is already merged, most likely not.

**Comment by 2xsaiko** [comment]
Ah! My bad, I should have cherry-picked it in the first place. That PR indeed fixes it.

**Comment by flokli** [comment]
No problem, thanks for confirming!

You can track the progress of this to hit the channels here: https://nixpk.gs/pr-tracker.html?pr=258373

Let's close this issue, nothing actionable here anymore.
