### ISSUE TITLE
nautilus-open-any-terminal appears not to create relevant schemas

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#259586]
### Describe the bug
this package for me seemed to not yet work out of the box as-is

### Steps To Reproduce
1. install `nautilus-open-any-terminal`
2. try running e.g. `gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal alacritty` as per [repo instructions](https://github.com/Stunkymonkey/nautilus-open-any-terminal#via-command-line)
3. encounter error:
> No such schema “com.github.stunkymonkey.nautilus-open-any-terminal”

### Expected behavior
schemas are handled as per [`postInstall` script](https://github.com/NixOS/nixpkgs/blame/9b25ba863c1751d8d1acbadd16ba70ee4fb5427c/pkgs/tools/misc/nautilus-open-any-terminal/default.nix#L51C32-L51C54)

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers

@stunkymonkey 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20231006.fea7f3f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(kiara): `"home-manager"`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Nyabinary** [comment]
Can confirm as well

**Comment by Stunkymonkey** [comment]
can confirm as well, but I do not know the fix for it...

**Comment by KiaraGrouwstra** [comment]
@vcunat @jtojnar any ideas?

**Comment by vcunat** [comment]
Why me, I wonder?

**Comment by jtojnar** [comment]
This is expected, see https://github.com/NixOS/nixpkgs/issues/33277. We do not expose schemas globally to avoid conflicts.

**Comment by KiaraGrouwstra** [comment]
@vcunat apologies, you appeared knowledgeable on the schemas over at #26702.
@jtojnar's script didn't work for me directly, given the schema wasn't in the given locations for me (`./share/gsettings-schemas/*/glib-2.0/schemas` of any `nix-store --query --references "$profile"` of a nix profile).
with a bit of trial and error knowing where it got installed tho, for me it managed to run a:

```sh
env XDG_DATA_DIRS="/nix/store/clxazrcbdjf64fc2hb4fq39c7vs9ky70-python3.10-nautilus-open-any-terminal-0.4.0/share/gsettings-schemas/python3.10-nautilus-open-any-terminal-0.4.0/" gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal wezterm
```

i guess this raises questions:

- might nixos users (e.g. at https://nixos.wiki/wiki/GNOME) be instructed to use `gsettings` in the way suggested by @jtojnar for in as far as they might be willing to put up with potential conflicts?
- might the packager consider any particular locations to provide/link schemas?

**Comment by vcunat** [comment]
No problem, I was mainly curious.  I've touched really many things over my contribution history, I still have way too many things to do around nixos.org...

**Comment by langfingaz** [comment]
While this does not solve the problem of missing schemas, here is how with Home Manager nautilus-open-any-terminal can be configured:

```Nix
{ config, pkgs, ... }:
{
  programs.dconf.enable = true;
  home-manager.users.<USERNAME> = { osConfig, config, pkgs, ... }: {
    dconf.settings = {
      "com/github/stunkymonkey/nautilus-open-any-terminal" = {
        terminal = "gnome-terminal";
      };
    };
  };
}
```

**Comment by KiaraGrouwstra** [comment]
maybe this is a duplicate of #168651
