### ISSUE TITLE
Failure: running taskwarrior (2.6.2) on NixOS Stoat (23.05) results in segmentation fault

### ISSUE THREAD

**Issue by pimvh** [NixOS/nixpkgs#259550]
### Describe the bug

Taskwarrior produces a segmentation fault when run. This happens when the directory specified in the config does not exist. It might be productive to create this directory, but I am not sure how that would be achieved.

After doing triage, this is an upstream issue, which could in some way be solved by Nix, but the best solution is probably upstream.

I'll open an issue there later, and will reference it here.

### Steps To Reproduce

1. build *taskwarrior*
2. configuration: 

```
data.location=/home/user/.local/share/task
```
3. run the program. 

When the path (data.location) exists, it works fine, otherwise: 

```console
➜ task
zsh: segmentation fault (core dumped)  task
```

I am running zsh here, but the shell does not seem to matter (bash gives same result).

4. Create the directory specific in `data.location`
3. run program again
5. it works.

### Expected behavior

The program should run instead, and not seg-fault.

### Additional context

Build log: https://gist.github.com/pimvh/ad763decacb8b9eaccfed984b2d15a49

The build completes fine, and all tests pass. The issue does not occur there, but during run-time.

It looks it might be related to: 
- https://github.com/GothenburgBitFactory/taskwarrior/issues/2708
- https://github.com/GothenburgBitFactory/taskwarrior/issues/3103 (duplicate)

I've tried debugging the program with gdb, but I am not super familiar with C++ debugging.

```console
➜ nix-shell -p taskwarrior gdb

[nix-shell:~/.config/home-manager]$ which task
/nix/store/wjzarj754yqmsy3jshwzv6fq9sca95vy-taskwarrior-2.6.2/bin/task

[nix-shell:~/.config/home-manager]$ gdb
GNU gdb (GDB) 13.1
...
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file /nix/store/wjzarj754yqmsy3jshwzv6fq9sca95vy-taskwarrior-2.6.2/bin/task
Reading symbols from /nix/store/wjzarj754yqmsy3jshwzv6fq9sca95vy-taskwarrior-2.6.2/bin/task...
(No debugging symbols found in /nix/store/wjzarj754yqmsy3jshwzv6fq9sca95vy-taskwarrior-2.6.2/bin/task)
(gdb) run
Starting program: /nix/store/wjzarj754yqmsy3jshwzv6fq9sca95vy-taskwarrior-2.6.2/bin/task
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000646cf4 in Path::expand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
(gdb) bt
#0  0x0000000000646cf4 in Path::expand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x000000000064734c in Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#2  0x00000000006475dd in File::File(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3  0x0000000000647a49 in Directory::Directory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x000000000064a711 in Directory::create(int) ()
```

I've both tried running this package as part of a NixOS configuration, and a Home-manager one, which both did not work. This leads me to the conclusion that something is wrong with the package.

I cannot test it, but it seems to work fine on: 
``` 
❯ nixos-version
23.11pre533083.e462c9172c68 (Tapir)
```

But not for: 

```
➜ nixos-version
23.05.20231003.3b79cc4 (Stoat)
```

I've tried both the version from the current unstable (snippet from flake.lock below) and the version from NixOs Stoat (23.05), both on Stoat.

``` 
    "nixpkgs-unstable": {
      "locked": {
        "lastModified": 1696375444,
        "narHash": "sha256-Sv0ICt/pXfpnFhTGYTsX6lUr1SljnuXWejYTI2ZqHa4=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "81e8f48ebdecf07aab321182011b067aafc78896",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },

```

As mentioned above, the issue occurs due to the path in data.location not being created, and the application not having enough rights to create it.

### Notify maintainers

The maintainers: @marcweber @oxalica 
The file was also edited by: @doronbehar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.20231003.3b79cc4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(superpim): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/store/v4vrwzcjk2aa9nv7l22j157l6v3dd0vn-source`
```

**Comment by matthiasbeyer** [comment]
This sounds like an upstream issue, I would open an issue there.
