### ISSUE TITLE
Unable to build simple Go program that makes use of C bindings

### ISSUE THREAD

**Issue by javgh** [NixOS/nixpkgs#25959]
## Issue description

Using go + stdenv.cc I am unable to build a simple Go program that makes use of C bindings. The program is a testcase from the Go compiler repository ( https://raw.githubusercontent.com/golang/go/master/misc/cgo/errors/issue14669.go ) . The build fails with an error message like this:

```
# command-line-arguments
cgo-dwarf-inference:2:8: error: enumerator value for '__cgo_enum__0' is not an integer constant
cgo-dwarf-inference:5:8: error: enumerator value for '__cgo_enum__2' is not an integer constant
cgo-dwarf-inference:8:2: error: initializer element is not constant
cgo-dwarf-inference:8:2: note: (near initialization for '__cgodebug_data[0]')
cgo-dwarf-inference:10:2: error: initializer element is not constant
cgo-dwarf-inference:10:2: note: (near initialization for '__cgodebug_data[2]')
```

### Steps to reproduce

```
nix-shell --pure -p stdenv.cc go wget
wget https://raw.githubusercontent.com/golang/go/master/misc/cgo/errors/issue14669.go
go build issue14669.go

warning: GOPATH set to GOROOT (/nix/store/56c4drb35ww6475r8w43i6706mzyma6p-go-1.8.1/share/go) has no effect
# command-line-arguments
cgo-dwarf-inference:2:8: error: enumerator value for '__cgo_enum__0' is not an integer constant
cgo-dwarf-inference:5:8: error: enumerator value for '__cgo_enum__2' is not an integer constant
cgo-dwarf-inference:8:2: error: initializer element is not constant
cgo-dwarf-inference:8:2: note: (near initialization for '__cgodebug_data[0]')
cgo-dwarf-inference:10:2: error: initializer element is not constant
cgo-dwarf-inference:10:2: note: (near initialization for '__cgodebug_data[2]')
```

Another example is geth, the go ethereum client, in version 1.6.1:

```
nix-shell --pure -p stdenv.cc go wget
wget https://github.com/ethereum/go-ethereum/archive/v1.6.1.tar.gz
tar xf v1.6.1.tar.gz
cd go-ethereum-1.6.1
make

[ ... some output omitted ... ]
github.com/ethereum/go-ethereum/vendor/github.com/naoina/toml
github.com/ethereum/go-ethereum/p2p/nat
github.com/ethereum/go-ethereum/vendor/github.com/gizak/termui
# github.com/ethereum/go-ethereum/vendor/github.com/karalabe/hid
cgo-dwarf-inference:2:8: error: enumerator value for '__cgo_enum__0' is not an integer constant
cgo-dwarf-inference:10:8: error: enumerator value for '__cgo_enum__7' is not an integer constant
cgo-dwarf-inference:18:2: error: initializer element is not constant
cgo-dwarf-inference:18:2: note: (near initialization for '__cgodebug_data[0]')
cgo-dwarf-inference:25:2: error: initializer element is not constant
cgo-dwarf-inference:25:2: note: (near initialization for '__cgodebug_data[7]')
github.com/ethereum/go-ethereum/internal/jsre
github.com/ethereum/go-ethereum/console
github.com/ethereum/go-ethereum/crypto
[ ... some output omitted ... ]
github.com/ethereum/go-ethereum/miner
github.com/ethereum/go-ethereum/light
github.com/ethereum/go-ethereum/eth/gasprice
util.go:44: exit status 2
exit status 1
make: *** [Makefile:15: geth] Error 1
```

Switching to clang instead seems to be a workaround for the problem:

```
nix-shell --pure -p clang go wget
wget https://raw.githubusercontent.com/golang/go/master/misc/cgo/errors/issue14669.go
go build issue14669.go
```

This last command builds successfully.

## Technical details

* System: 17.09.git.bb37fc9 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: 17.09.git.bb37fc90c7
* Sandboxing enabled: false

**Comment by matthewbauer** [comment]
I think this has to do with how Go handles GOROOT. It expects to be able to write to $GOROOT even though it's a read-only path. Could you try the buildCommand in go-ethereum:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/altcoins/go-ethereum.nix#L18-L21

**Comment by javgh** [comment]
Aw, I was wondering how to get rid of that warning. The warning is gone, but it doesn't seem to have helped:

```
nix-shell --pure -p stdenv.cc go wget which
export GOROOT=$(mktemp -d --suffix=-goroot)
which go
  /nix/store/56c4drb35ww6475r8w43i6706mzyma6p-go-1.8.1/bin/go
ln -sv /nix/store/56c4drb35ww6475r8w43i6706mzyma6p-go-1.8.1/share/go/* $GOROOT
ln -svf /nix/store/56c4drb35ww6475r8w43i6706mzyma6p-go-1.8.1/bin $GOROOT 
wget https://raw.githubusercontent.com/golang/go/master/misc/cgo/errors/issue14669.go
go build issue14669.go

# command-line-arguments
cgo-dwarf-inference:2:8: error: enumerator value for '__cgo_enum__0' is not an integer constant
cgo-dwarf-inference:5:8: error: enumerator value for '__cgo_enum__2' is not an integer constant
cgo-dwarf-inference:8:2: error: initializer element is not constant
cgo-dwarf-inference:8:2: note: (near initialization for '__cgodebug_data[0]')
cgo-dwarf-inference:10:2: error: initializer element is not constant
cgo-dwarf-inference:10:2: note: (near initialization for '__cgodebug_data[2]')
```

I originally ran into this issue when I tried to upgrade that linked Nix expression. Version 1.4.7 of go-ethereum compiles just fine, but 1.6.1 doesn't, because now one of the dependencies makes use of some kind of C bindings.

While playing around with it I also switched over to using `buildGoPackage` in the Nix expression, but that also didn't help. Switching to clang helped in the end. That version can be found here: https://github.com/javgh/nixpkgs/blob/go-ethereum/pkgs/applications/altcoins/go-ethereum.nix

But that's just a workaround and I would assume that other Go packages will at some point also run into this problem when they just use `stdenv.cc` or `buildGoPackage`.

**Comment by hhomar** [comment]
I ran into this problem adding seccomp support to the docker package. It's caused by the -O2 optimization flag which is being added by the fortify hardening flag.

A possible fix would be to add hardeningDisable = [ "fortify" ]; to the buildGoPackage.

**Comment by prusnak** [comment]
I can't no longer reproduce this on my system so I guess the issue is fixed?

`nixos-20.03pre198214.4cd2cb43fb3`

**Comment by javgh** [comment]
I can confirm that I also cannot reproduce this anymore on my system. I am closing this - thanks!
