### ISSUE TITLE
Update request: rustc 1.72.1 → 1.73.0

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#259575]
- Package name: rustc
- Latest released version: 1.73.0

- Current version on the unstable channel: 1.72.0
- Current version on the stable/release channel: 1.69.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cstrahan 
@Havvy 
@globin 
@figsoda 
@Mic92 
@tjni 
@winterqt 
@zowoq 

-----

Note for maintainers: Please tag this issue in your PR.
Note: 1.72.1 is currently on staging-next
https://nixpk.gs/pr-tracker.html?pr=256310

**Comment by FliegendeWurst** [comment]
Fixed by #259989
