### ISSUE TITLE
Steam doesn't run ("libGL error: failed to load driver: swrast")

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#25957]
```
> steam
cp: cannot create regular file '/home/chris/.local/share/Steam/bootstrap.tar.xz': Permission denied
Running Steam on nixos 17.03.git.32d6569b62 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Installing breakpad exception handler for appid(steam)/version(1493162727)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

NixOS 17.03

Hardware:
- Intel NUC NUC6i7KYK
- Intel Iris Pro Graphics 580

**Comment by lheckemann** [comment]
Did you enable [the 32-bit OpenGL option](https://nixos.org/nixos/options.html#drisupport32bit) as [documented in the manual](https://nixos.org/nixpkgs/manual/#sec-steam-play)?

**Comment by chris-martin** [comment]
Yes - This is the config I tried https://github.com/chris-martin/home/blob/a08b6c1683719e23c1ee27b295b07b852a950afe/nix/os/cubby.nix

**Comment by lheckemann** [comment]
This looks pretty wrong to me, could you check the permissions on .local/share/Steam?

```
cp: cannot create regular file '/home/chris/.local/share/Steam/bootstrap.tar.xz': Permission denied```

I also don't think it should be using the swrast driver at all... But no idea if the two issues are related.

**Comment by chris-martin** [comment]
`.local/share/Steam` is 0700, but `Steam/bootstrap.tar.xz` is 0444

**Comment by vcunat** [comment]
Steam has been spitting this permission line as long as I can remember, without experiencing any actual problems.

**Comment by vcunat** [comment]
I think trying swrast is typically a symptom of driver problems.  SW rasterization is often not feasible in (3D) games anyway.

**Comment by vcunat** [comment]
BTW, steam seems fine on my [micro-desktop](http://www.dell.com/en-us/work/shop/productdetails/optiplex-7040-micro-desktop) with i7-6700T on NixOS-17.03. (I don't run everything on the same nixpkgs commit.)

**Comment by qrvaelet** [comment]
`  environment.systemPackages = with pkgs; [ (steam.override { newStdcpp = true; }) ];`

With the above line it's working fine with mesa drivers.

**Comment by chris-martin** [comment]
@qrvaelet Thank you, that workaround is working!

**Comment by MP2E** [comment]
Hi there, just wanted to state that I have had the same issue with Steam on my Lenovo Thinkpad X240 with an Intel integrated gpu, but do not see this issue on my desktop which uses the proprietary Nvidia drivers.

The workaround states makes steam run perfectly on my laptop

**Comment by pshendry** [comment]
Add one more to the list of people for whom @qrvaelet's suggestion worked like a charm after a reboot; I was getting a "Pins potentially out-of-date, rebuilding..." message followed by some "read only filesystem" errors as Steam tried to modify a Nix store path. This is on an XPS 13 2-in-1 i5-7Y54.

**Comment by chris-martin** [comment]
I have no idea whether this is a related issue, but might as well mention it, I guess. This is what happens when I try to launch Civ VI:

![Screenshot of Civ VI failing to launch](https://user-images.githubusercontent.com/399718/30087296-e0ac1060-926d-11e7-81c0-8a43c685cd39.png)

I'm getting this with the `newStdcpp = true;` workaround applied.

**Comment by srhb** [comment]
If someone could test and review #29180 -- particularly if you're using a dedicated setup, that would be grand.

**Comment by Mic92** [comment]
was merged.
