### ISSUE TITLE
Customizing vim breaks gvim and xxd symlinks

### ISSUE THREAD

**Issue by ivantomac** [NixOS/nixpkgs#25970]
## Issue description

Having `vim_configurable` in `environment.systemPackages` correctly exposes `gvim` and `xxd`.
Overriding settings using `vim_configurable.customize { ... }` as described in `pkgs/misc/vim-plugins/vim-utils.nix` hides `gvim` and `xxd`.

On IRC it has been suggested to add `vimHugeX`, which is in `pkgs/top-level/all-packages.nix` defined as `vimHugeX = vim_configurable`, as a low priority package to work around this issue and while this did expose `gvim`, it didn't use any of the settings overrides.

My current workaround for `gvim` is to add `gvim = "vim -g"` to `programs.bash.shellAliases`.

### Steps to reproduce

Add `vim_configurable.customize { ... }` to `environment.systemPackages` and run `nixos-rebuild switch`.
`gvim` and `xxd` are not in the path.

Replace the above expression with just `vim_configurable` and `gvim` and `xxd` work correctly.

## Technical details

* System: (NixOS: `17.03.1160.f2c4af4e3b (Gorilla)`)
* Nix version: (`nix-env (Nix) 1.11.8`)
* Nixpkgs version: (`17.03.1160.f2c4af4e3b`)
* Sandboxing enabled: (`build-use-sandbox = true`)

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by ivantomac** [comment]
I just noticed xxd works now. gvim link is still broken.

**Comment by 8573** [comment]
The workaround I've been using since 2016 is to replace `vim_configurable` with a package whose build script, for each of the various Vim commands, makes a copy of the wrapper script that `vim_configurable.customize` produces and changes the command that the wrapper script ultimately runs: <https://github.com/8573/nixos-config/blob/2ef6dd04e63473bdc3aac4cc43b951e871a3d145/modules/programs/vim/default.nix#L77-L118>.

**Comment by sersorrel** [comment]
I'm pretty sure the way to fix this is to pass `wrapGui = true`: https://github.com/NixOS/nixpkgs/blob/1c145df9ae6f06d96e1e3127011ec3513b09dd3e/pkgs/misc/vim-plugins/vim-utils.nix#L438 (though I have only tested with home-manager's home.packages, not environment.systemPackages, so there could be some difference).

**Comment by ivantomac** [comment]
> I'm pretty sure the way to fix this is to pass `wrapGui = true`:
> 
> https://github.com/NixOS/nixpkgs/blob/1c145df9ae6f06d96e1e3127011ec3513b09dd3e/pkgs/misc/vim-plugins/vim-utils.nix#L438
> 
> (though I have only tested with home-manager's home.packages, not environment.systemPackages, so there could be some difference).

Thank you.

I can confirm that fixes the problem for `gvim`.
`gvimdiff` is still not working but I'll close the ticket since it was specifically about `gvim` and `xxd`.

**Comment by dtzWill** [comment]
Not ideal, but as a bit of a workaround:

`alias vimdiff='vim -d'`
`alias gvim='vim -g'`
`alias gvimdiff='vim -g -d'`

Not sure if there's a similar flag to make vim act like `xxd`, though.

**Comment by ivantomac** [comment]
`xxd` is a program that ships with `vim` and was previously not being exposed and wasn't working. It is working now as I mentioned in the comment from 2020/02/28.
As for the aliases, I mentioned in the ticket description that that was what I used as a workaround.

**Comment by dtzWill** [comment]
> `xxd` is a program that ships with `vim` and was previously not being exposed and wasn't working. It is working now as I mentioned in the comment from 2020/02/28.
> As for the aliases, I mentioned in the ticket description that that was what I used as a workaround.

Indeed, my mistake.  Sorry for the noise, have a good one! :+1:
