### ISSUE TITLE
Build failure: exodus

### ISSUE THREAD

**Issue by iopq** [NixOS/nixpkgs#259735]
### Steps To Reproduce

add `exodus` to the package list and try to download it

### Build log

```
error: builder for '/nix/store/bp3h0i585x7ljx88qyr94r0apzhamgp3-source.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://downloads.exodus.com/releases/exodus-linux-x64-23.5.22.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0  6053    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 403
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/bp3h0i585x7ljx88qyr94r0apzhamgp3-source.drv'.
error: 1 dependencies of derivation '/nix/store/803xzpmsa78dvxfn49z7ach2pbkp85ri-exodus-23.5.22.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6sdvp4yfgq68y9hglcky973k8kacrrch-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/y3dmy20fxqr2fjh0mip128sd66n1js9z-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zf7bp6iw00fga9z7g8c6pf6i88cbv5l4-nixos-system-desktop-23.11.20230919.5ba549e.drv' failed to build

```

### Additional context

curl -I https://downloads.exodus.com/releases/exodus-linux-x64-23.5.22.zip fails with 403

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.54, NixOS, 23.11 (Tapir), 23.11.20230919.5ba549e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(iopq): `""`
 - channels(root): `"nixos, stable-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by oluceps** [comment]
Hmm, seems the webpage requires a User Agent to download.

**Comment by SoftwareRat** [comment]
Reopen issue, problem is back
```
trying https://downloads.exodus.com/releases/exodus-linux-x64-23.5.8.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  6071    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download source from any mirror
error: builder for '/nix/store/ls9cp8426c4agvpi1sx5khdyjb3w98xz-source.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/3aywkp4dpgvqlbjjz4b4h2dxgyrfxp9f-exodus-23.5.8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/86qkr70s142k7q8kzpmpdyvm55546af1-exodus-23.5.8_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f2nmxqwdl2am6mkgvn2h145s0bvkb0r7-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b6rsdiyilf202wqh5k08qdf07sg59xps-system-path.drv' failed to build
building '/nix/store/21ifwpzv4d050n4pf56jb6318jh5ifb2-time-1.9_fish-completions.drv'...
building '/nix/store/aaimp8hy3xr0x0xj1ssqmj6a1n886bfi-totem-43.0_fish-completions.drv'...
error: 1 dependencies of derivation '/nix/store/hgd3iaxa9f4sk6vklr48gssrzdfb1fps-nixos-system-SRT-SURFACE-NIXOS-23.05.4392.b5f8ec6be261.drv' failed to build
```

**Comment by oluceps** [comment]
> Reopen issue, problem is back
> 
> ```
> trying https://downloads.exodus.com/releases/exodus-linux-x64-23.5.8.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0  6071    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 403
> error: cannot download source from any mirror
> error: builder for '/nix/store/ls9cp8426c4agvpi1sx5khdyjb3w98xz-source.drv' failed with exit code 1
> error: 1 dependencies of derivation '/nix/store/3aywkp4dpgvqlbjjz4b4h2dxgyrfxp9f-exodus-23.5.8.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/86qkr70s142k7q8kzpmpdyvm55546af1-exodus-23.5.8_fish-completions.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/f2nmxqwdl2am6mkgvn2h145s0bvkb0r7-man-paths.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/b6rsdiyilf202wqh5k08qdf07sg59xps-system-path.drv' failed to build
> building '/nix/store/21ifwpzv4d050n4pf56jb6318jh5ifb2-time-1.9_fish-completions.drv'...
> building '/nix/store/aaimp8hy3xr0x0xj1ssqmj6a1n886bfi-totem-43.0_fish-completions.drv'...
> error: 1 dependencies of derivation '/nix/store/hgd3iaxa9f4sk6vklr48gssrzdfb1fps-nixos-system-SRT-SURFACE-NIXOS-23.05.4392.b5f8ec6be261.drv' failed to build
> ```

Try `wget -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" https://downloads.exodus.com/releases/exodus-linux-x64-23.5.8.zip`

**Comment by SoftwareRat** [comment]
> wget -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" https://downloads.exodus.com/releases/exodus-linux-x64-23.5.8.zip

On my macOS it works

**Comment by iopq** [comment]
The problem reappeared again for me

**Comment by jalbstmeijer** [comment]
Think similar issue, with NixOS 24.05 stable.

I get java script back. Are they doing a browser check?

On the browser I can download.

```
error: builder for '/nix/store/l3a2xsx03y6db1b2ljibnkj7ib9ddxpp-exodus-linux-x64-24.19.4.zip.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://downloads.exodus.com/releases/exodus-linux-x64-24.19.4.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0  9434    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (56) The requested URL returned error: 403
       > error: cannot download exodus-linux-x64-24.19.4.zip from any mirror
```

**Comment by tomodachi94** [comment]
Duplicate https://github.com/NixOS/nixpkgs/issues/313548. Some workarounds (such as `nix-prefetch-url`) are listed there.
