### ISSUE TITLE
Check if `libpng = libpng12` overrides in all-packages.nix are still necessary

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#259879]
- [x] `winhelpcgi` #270123
- [ ] `tetex` #270107
- [x] `ploticus` #270146
- [x] `pngtoico` #269020
- [x] `sng` #269022
- [x] `extremetuxracer` #270174
- [ ] `speed_dreams` #270194
- [x] `voxelands` #269024
- [x] `xsane` #270223

If the override is still necessary then move it directly to the `default.nix` with a comment about why.

**Comment by kirillrdy** [comment]
> If the override is still necessary then move it directly to the default.nix with a comment about why.

may I ask why ? I though preferred way is to override in all-packages. This is also preferred way in pkgs/by-name
https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#changing-implicit-attribute-defaults

**Comment by Artturin** [comment]
> > If the override is still necessary then move it directly to the default.nix with a comment about why.
> 
> may I ask why ? I though preferred way is to override in all-packages. This is also preferred way in pkgs/by-name [`master`/pkgs/by-name#changing-implicit-attribute-defaults](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name?rgh-link-date=2023-11-03T21%3A14%3A40Z#changing-implicit-attribute-defaults)

Because `callPackage` overrides are kinda hidden and can result in confusion, the reason I created this issue was because a person on matrix was confused why one package used libpng12

**Comment by kirillrdy** [comment]
> In preparation of the great `by-name` migration, doing fixes like the ones linked ^ should be encouraged for all packages in `all-packages.nix`. Is there a general consensus on this?

No idea, i thought that this was https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#changing-implicit-attribute-defaults
general consensus.

**Comment by pbsds** [comment]
Would this make sense?
```
, libpng12
, libpng ? libpng12
```

CC @infinisil

**Comment by infinisil** [comment]
@pbsds If `libpng` exists in the scope it will be passed, so the default would be ignored. (see also https://github.com/NixOS/nixpkgs/pull/131271)

**Comment by pbsds** [comment]
@Artturin, the unmerged PRs that are left all need move the `libpng12` dependency into the derivation, which goes against the by-name recommendation. Do you want these merged or should we close this issue?

**Comment by Stunkymonkey** [comment]
ping @Artturin

**Comment by Artturin** [comment]
Let's close the unmerged PRs
