### ISSUE TITLE
gnat compiler results in error when run

### ISSUE THREAD

**Issue by AveryGlitch** [NixOS/nixpkgs#25986]
## Issue description

The gnat compiler results in the error

```
/nix/store/dg5qd5a8rhmyh3bx53m5046lbfvm1571-gnat-wrapper-4.5.4/bin/gnatbind -aI/nix/store/6z9y17l0anahhvyzcb7sa1nqrqf3sf75-gnat-4.5.4/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/adainclude -aO/nix/store/6z9y17l0anahhvyzcb7sa1nqrqf3sf75-gnat-4.5.4/lib/gcc/x86_64-unknown-linux-gnu/4.5.4/adalib -x hello_world.ali
/nix/store/dg5qd5a8rhmyh3bx53m5046lbfvm1571-gnat-wrapper-4.5.4/bin/gnatlink hello_world.ali
gnat1: warning: command line option "-Wformat" is valid for C/C++/ObjC/ObjC++ but not for Ada
gnat1: warning: command line option "-Wformat-security" is valid for C/C++/ObjC/ObjC++ but not for Ada
gnat1: error: unrecognized command line option "-fstack-protector-strong"
gnatmake: *** link failed.
```

### Steps to reproduce

`nix-env -iA nixos.gnat`
`gnat make hello_world.adb`

hello_world.adb can be found [here](https://en.wikibooks.org/wiki/Ada_Programming/Basic)

## Technical details

* System: 17.03.1180.27b488f28e (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1180.27b488f28e"
* Sandboxing enabled: yes

**Comment by vcunat** [comment]
Right, this can be worked around by an environment variable, e.g. `hardeningDisable=all`.

More background: https://github.com/NixOS/nixpkgs/issues/18995

**Comment by AveryGlitch** [comment]
Thankyou!
I'll close the issue.
