### ISSUE TITLE
rustdesk: can not display any CJK characters on GNOME wayland

### ISSUE THREAD

**Issue by pokon548** [NixOS/nixpkgs#259890]
### Describe the bug
It looks like rustdesk in NixOS cannot display any CJK characters on GNOME wayland. See below for screenshot (some information were marked out for privacy).

### Steps To Reproduce
1. Download rustdesk
2. Open it under GNOME wayland
3. Switch to any languages that requires displaying CJK characters (Japanese, Chinese, etc.)

### Expected behavior
rustdesk should display any CJK characters correctly.

### Screenshots
![截图 2023-10-09 09-39-42](https://github.com/NixOS/nixpkgs/assets/65808665/271edd09-a6c5-480e-b40e-d06e1c4df8f4)

### Additional context
I also packaged a rustdesk distribution directly from official binary for testing, and it works without this issue. So maybe we should not blame upstream. See https://github.com/nix-community/nur-combined/blob/master/repos/pokon548/pkgs/rustdesk-bin/default.nix

### Notify maintainers
@ocfox @leixb

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20231006.87828a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/g68f5abh3xhcz8xsdlfw7wkgkkcx3nwy-source`
```

**Comment by Leixb** [comment]
I just tried it on Hyprland with `LC_ALL=ja_JP.UTF-8 NIXPKGS_ALLOW_UNFREE=1 nix run nixpkgs#rustdesk --impure` and it seems to work correctly (with a warning about falling back to the `C` locale, which may be related). Does rustdesk give any information when running from the terminal?

![rustdesk_japanese](https://github.com/NixOS/nixpkgs/assets/17183803/4212e4d0-e846-4617-aebf-86cf5ee8ced1)

**Comment by pokon548** [comment]
> I had `noto-fonts-cjk` installed in my system, if I remove it I get the same results as you. (I assume this is not the issue but I will mention it just in case)

After adding `noto-fonts-cjk`, it indeed solve my problem! But that's weird, it should also read CJK fonts from `noto-fonts` package (I only have it on my system before, and it works for other programs). 

Maybe we should adding `noto-fonts-cjk` as a dependency for this package?

**Comment by Leixb** [comment]
Removing `noto-fonts-cjk` also breaks Japanese fonts on my browser and other apps so T don't think `noto-fonts` includes them. I checked and `pkgs.noto-fonts-cjk` contains `NotoSansCJK-VF.otf.ttc`  `NotoSansMonoCJK-VF.otf.ttc` which are not included in `pkgs.noto-fonts`. I am not sure why other apps work for you without them.

Be that as it may, I don't think adding `noto-fonts-cjk` as a dependency of rustdesk would make sense.

**Comment by pokon548** [comment]
I think you are right, keeping this package as-is should be a better choice.
I'm closing this as it is not related to package issue, thanks for taking time to troubleshoot this issue anyway :)
