### ISSUE TITLE
silent microphone

### ISSUE THREAD

**Issue by lambdax-x** [NixOS/nixpkgs#25993]
## Issue description

I am using pulseaudio, audio output works but input doesn't.
Microphones are detected (running as shown by `pacmd list-source`), source selected, channels aren't muted, volume up.
I don't really know how to check if it comes from pulseaudio or not actually and don't know what kind of information I should provide here.

### Steps to reproduce

```nix
hardware.pulseaudio = {                                                        
  enable = true;
  support32Bit = true;
};
```

## Technical details

* System: 17.03.1188.9fd6417e27 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1188.9fd6417e27"
* Sandboxing enabled: build-use-sandbox = false

**Comment by cillianderoiste** [comment]
@lambdax-x Have you also checked the settings in `alsamixer`?

**Comment by 7c6f434c** [comment]
Also, there is sometimes a magic invocation with `amixer sset [name] cap`

**Comment by lambdax-x** [comment]
Everything seems okay in alsamixer (nothing muted, volumes up).
Also I found an option to enable the microphone in the bios but it's set up correctly.

**Comment by lambdax-x** [comment]
Sorry, closed the issue unintentionally...

**Comment by lambdax-x** [comment]
It should be ok with amixer :

```bash
$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 74
  Mono: Playback 67 [91%] [-7.00dB] [on]
Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 74
  Mono:
  Front Left: Playback 74 [100%] [0.00dB] [on]
  Front Right: Playback 74 [100%] [0.00dB] [on]
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 74
  Mono:
  Front Left: Playback 65 [88%] [-9.00dB] [on]
  Front Right: Playback 65 [88%] [-9.00dB] [on]
Simple mixer control 'PCM',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 255
  Mono:
  Front Left: Playback 255 [100%] [0.00dB]
  Front Right: Playback 255 [100%] [0.00dB]
Simple mixer control 'Mic Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 4
  Front Left: 4 [100%] [40.00dB]
  Front Right: 4 [100%] [40.00dB]
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Beep',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 7
  Mono: Playback 1 [14%] [-24.00dB] [off]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 80
  Front Left: Capture 80 [100%] [6.00dB] [on]
  Front Right: Capture 80 [100%] [6.00dB] [on]
Simple mixer control 'Auto-Mute Mode',0
  Capabilities: enum
  Items: 'Disabled' 'Enabled'
  Item0: 'Enabled'
Simple mixer control 'Digital',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 120
  Front Left: Capture 120 [100%] [30.00dB]
  Front Right: Capture 120 [100%] [30.00dB]
Simple mixer control 'Internal Mic Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 4
  Front Left: 4 [100%] [48.00dB]
  Front Right: 4 [100%] [48.00dB]
```

**Comment by 7c6f434c** [comment]
Please run `amixer sset Capture cap`, from the output I see that you do need to run it.

**Comment by lambdax-x** [comment]
I don't think I need to:
```bash
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 80
  Front Left: Capture 80 [100%] [6.00dB] [on]   # <-- is on
  Front Right: Capture 80 [100%] [6.00dB] [on]  # <-- also
```

**Comment by 7c6f434c** [comment]
on/off, numeric scale and cap/nocap are three different dimensions, you
reference the lines showing the first two of them.

**Comment by lambdax-x** [comment]
Could you please elaborate on how you see that? Because I can't see and experience any difference after executing this command.

**Comment by 7c6f434c** [comment]
`cswitch` + similarity to the layout of my card where I had a lot of headbanging with that.

Hm. Are there any hardware buttons that could be capture-related? Also, do you have a combined jack with headphones without microphone inserted? Also, what `amixer contents` say, it is more detailed than `amixer`…

**Comment by lambdax-x** [comment]
It's kind of obscure but after the night, the mic input is no longer muted...
Looks like there has been a sacrifice for the alsa devil.

**Comment by jkarpov** [comment]
My mic was auto muted and capture audio was off. I went through alsamixer and just messed with it.. You have to make sure auto mute is off and capture audio is on(the higher, the better your mic pics up). To see all sound options use f1 to see what sound card options you have(im running headphones with mic on them). f6 for sound card then see what other options you have for sound cards. If any options, mess around with them, find mic options and capture and that should do it. I fixed it without having to mess with any code.
