### ISSUE TITLE
nixos-unstable branch hasn't been updated in three months

### ISSUE THREAD

**Issue by andyjscott** [NixOS/nixpkgs#26001]
The `nixos-unstable` branch was last updated 2017-02-20 [0] but the channel was last updated 2017-05-11[1].

[0] - https://github.com/NixOS/nixpkgs-channels/branches
[1] - https://nixos.org/channels/

**Comment by copumpkin** [comment]
cc @edolstra perhaps something wonky going on with Hydra?

**Comment by matthewbauer** [comment]
That's not really true. The author date is 2017-02-20 but the commit date is from 2017-05-10.

**Comment by copumpkin** [comment]
Oh, good point. I'll close this ticket then, since they seem to be on the same commit ID.
