### ISSUE TITLE
Package request: mapclassify

### ISSUE THREAD

**Issue by nanophilip** [NixOS/nixpkgs#260099]
**Project description**

mapclassify is an open-source python library for Choropleth map classification. It is part of [PySAL](https://github.com/pysal/pysal) the Python Spatial Analysis Library.

**Metadata**

* homepage URL: https://pysal.org/mapclassify/
* source URL: https://github.com/pysal/mapclassify
* license: BSD-3-Clause license

**Comment by timlinux** [comment]
Even nicer if we could get pysal itself - there are some QGIS plugins that depend on it.
