### ISSUE TITLE
GTK3 immodules.cache causes crashes with custom IME (Fcitx5)

### ISSUE THREAD

**Issue by chayleaf** [NixOS/nixpkgs#260076]
### Describe the bug
I'm using GIMP 2.99 from a custom overlay. It works fine, but there are crashes when entering Japanese text in certain textboxes using Fcitx5 IME (and since Japanese is my primary input language, I often do it by accident, and often need to use it on purpose). The backtrace was showing gdk, and after building gtk3 from source, it turned out the upstream code works fine. The issue is introduced with [this](https://github.com/NixOS/nixpkgs/blob/514b109a314498c66dad5c1982423f692253cdd2/pkgs/development/libraries/gtk/patches/3.0-immodules.cache.patch) patch. I'm not sure what exactly causes the crash, here's the backtrace:

```
#0  0x00007ffff710bec4 in calculate_moved_to_rect_result () from /nix/store/5y5gmfp3pjr60rlsvrc1zk8pds14kzzv-gtk+3-3.24.38/lib/libgdk-3.so.0
#1  0x00007ffff710c251 in xdg_popup_configure () from /nix/store/5y5gmfp3pjr60rlsvrc1zk8pds14kzzv-gtk+3-3.24.38/lib/libgdk-3.so.0
#2  0x00007ffff6063a3a in ffi_call_unix64 () from /nix/store/35badg7gpxkhyzcrdyh2dfi9wfd43phz-libffi-3.4.4/lib/libffi.so.8
#3  0x00007ffff6062935 in ffi_call_int () from /nix/store/35badg7gpxkhyzcrdyh2dfi9wfd43phz-libffi-3.4.4/lib/libffi.so.8
#4  0x00007ffff6063518 in ffi_call () from /nix/store/35badg7gpxkhyzcrdyh2dfi9wfd43phz-libffi-3.4.4/lib/libffi.so.8
#5  0x00007ffff5d7d7e6 in wl_closure_invoke () from /nix/store/9a9hfbv339z3jla9j59ql9q17wrs8sk1-wayland-1.22.0/lib/libwayland-client.so.0
#6  0x00007ffff5d79bd9 in dispatch_event.isra () from /nix/store/9a9hfbv339z3jla9j59ql9q17wrs8sk1-wayland-1.22.0/lib/libwayland-client.so.0
#7  0x00007ffff5d7b534 in wl_display_dispatch_queue_pending ()
   from /nix/store/9a9hfbv339z3jla9j59ql9q17wrs8sk1-wayland-1.22.0/lib/libwayland-client.so.0
#8  0x00007ffff70fec54 in _gdk_wayland_display_queue_events () from /nix/store/5y5gmfp3pjr60rlsvrc1zk8pds14kzzv-gtk+3-3.24.38/lib/libgdk-3.so.0
#9  0x00007ffff70c63d0 in gdk_display_get_event () from /nix/store/5y5gmfp3pjr60rlsvrc1zk8pds14kzzv-gtk+3-3.24.38/lib/libgdk-3.so.0
#10 0x00007ffff70fe972 in gdk_event_source_dispatch () from /nix/store/5y5gmfp3pjr60rlsvrc1zk8pds14kzzv-gtk+3-3.24.38/lib/libgdk-3.so.0
#11 0x00007ffff7978ead in g_main_context_dispatch () from /nix/store/1c6x8n47mq5rcivsp72b0dyqgjghi6yx-glib-2.76.4/lib/libglib-2.0.so.0
#12 0x00007ffff7979158 in g_main_context_iterate.constprop () from /nix/store/1c6x8n47mq5rcivsp72b0dyqgjghi6yx-glib-2.76.4/lib/libglib-2.0.so.0
#13 0x00007ffff79791ec in g_main_context_iteration () from /nix/store/1c6x8n47mq5rcivsp72b0dyqgjghi6yx-glib-2.76.4/lib/libglib-2.0.so.0
#14 0x00007ffff772256d in g_application_run () from /nix/store/1c6x8n47mq5rcivsp72b0dyqgjghi6yx-glib-2.76.4/lib/libgio-2.0.so.0
#15 0x0000000000672903 in app_run (full_prog_name=0xb23e60 "/home/user/code/cpp/gimp/_build/app/gimp-2.99", filenames=<optimized out>, 
    alternate_system_gimprc=alternate_system_gimprc@entry=0x0, alternate_gimprc=alternate_gimprc@entry=0x0, session_name=<optimized out>, 
    batch_interpreter=<optimized out>, batch_commands=0x0, quit=0, as_new=0, no_interface=0, no_data=0, no_fonts=0, no_splash=0, be_verbose=0, 
    use_shm=1, use_cpu_accel=1, console_messages=0, use_debug_handler=0, show_playground=1, show_debug_menu=1, 
    stack_trace_mode=GIMP_STACK_TRACE_QUERY, pdb_compat_mode=GIMP_PDB_COMPAT_WARN, 
    backtrace_file=0xb05650 "/home/user/.config/GIMP/2.99/CrashLog/gimp-crash-1696885823.txt") at ../app/app.c:317
#16 0x00000000004ba887 in main (argc=<optimized out>, argv=<optimized out>) at ../app/main.c:796
```

Either way, it seems GTK doesn't like immodule cache files, so I think it would be nice to either fix it upstream or drop the patch.

### Steps To Reproduce
1. Install Fcitx5
2. Run Gnome 2.99 (Gnome 2 uses GTK2, so the issue doesn't appear there). You can do it via `nix run github:chayleaf/dotfiles#gimp`.
3. Open the text edit tool and try entering any text to the font selection textbox using Fcitx5

### Expected behavior
No crashes happening.

### Additional context
My full setup is available at https://github.com/chayleaf/dotfiles

 If I set `GTK_IM_MODULE_FILE` to an empty string, I can't type in Japanese, but yeah the crash doesn't happen.
 
 If I override `GTK_IM_MODULE_FILE` with the output of `gtk-query-immodules-3.0` or `gtk-query-immodules-3.0 ~/.nix-profile/lib/gtk-3.0/3.0.0/immodules/*.so`, it still crashes, even when it's as minimal as
 
 ```
 "/nix/store/ijvz5lsjay2wyidnb1xqgl1cd0picyvl-fcitx5-gtk-5.1.0/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
"fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/nix/store/ijvz5lsjay2wyidnb1xqgl1cd0picyvl-fcitx5-gtk-5.1.0/locale" "ja:ko:zh:*"
 ```
 
For what it's worth, `/nix/store/ijvz5lsjay2wyidnb1xqgl1cd0picyvl-fcitx5-gtk-5.1.0/locale` doesn't exist, but replacing it with GTK3's locale dir doesn't make the issue disappear.

### Notify maintainers

@7c6f434c @bobby285271 @hedning @jtojnar @dasj19 @amaxine

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20231004.3dc2b4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by wengxt** [comment]
Hi this is fcitx dev here. I came across this bug through google search. I don't think it's a bug relevant to nix os. Instead, it's doing the right thing that allows you to use fcitx im module on nix.

I suggest you open a issue on https://github.com/fcitx/fcitx5-gtk/ and explain how to the step to produce this while using gimp 2.99.

**Comment by chayleaf** [comment]
This seems like a GIMP or GTK issue, so I'm closing this. I'll report it upstream.
