### ISSUE TITLE
Netdata sends telemetry by default

### ISSUE THREAD

**Issue by pkel** [NixOS/nixpkgs#260035]
### Describe the bug

Netdata telemetry collection is not (fully) disabled by default.

### Steps To Reproduce
1. Set `services.netdata.enable = true`
2. Visit http://localhost:19999
3. Open the network tools and filter for requests to `app.posthog.com`
4. Observe that telemetry is not disabled
5. Additionally set
    ```
    netdata.configDir.".opt-out-from-anonymous-statistics" = pkgs.writeText ".opt-out-from-anonymous-statistics" "";
    ```
6. Refresh the web gui
7. Observe that there are no more requests to `app.posthog.com`

### Expected behavior
There should be no requests to `app.posthog.com` with default settings.

### Screenshots
IMO not necessary. I'm can ship them on request.

### Additional context

Relevant deep links:

- Netdata documentation: https://learn.netdata.cloud/docs/configuring/securing-netdata-agents/anonymous-telemetry-events
- Netdata nixos module option: https://github.com/NixOS/nixpkgs/blob/87828a0e03d1418e848d3dd3f3014a632e4a4f64/nixos/modules/services/monitoring/netdata.nix#L171-L180
- Netdata messing with the opt-out mechanism: https://github.com/netdata/netdata/pull/12126
- Nixpkgs commit adding the option: https://github.com/NixOS/nixpkgs/commit/5d81fcdf3726eb6140ca53de5780fda5aea14afd

After reading this, I tried to fix the problem myself by replacing `DO_NOT_TRACK` with `DISABLE_TELEMETRY` in the netdata module. This did not disable telemetry.

https://github.com/NixOS/nixpkgs/blob/87828a0e03d1418e848d3dd3f3014a632e4a4f64/nixos/modules/services/monitoring/netdata.nix#L219

I can try submitting a PR implementing step 5 above. I.e., create the hidden config file instead of setting the environment variable. But I'm not sure whether this is the right approach.

### Notify maintainers

- netdata package maintainer: @raitobezarius
- option author: @DeeUnderscore 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.git.3acb5c4264c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I'm deploying with colmena to a different host. I pasted the output from the target host.

**Comment by DeeUnderscore** [comment]
From skimming Netadata source, it does look like `DO_NOT_TRACK`/`DISABLE_TELEMETRY` is honored mostly by Netdata's bespoke install scripts, and upon seeing that that is set, they output the `.opt-out-from-anonymous-statistics` file as part of the installation. Just provisioning the file on our side might be the most expedient way to accomplish this.

**Comment by RaitoBezarius** [comment]
I will take a look and find a way to fix this.
