### ISSUE TITLE
Package request: teams

### ISSUE THREAD

**Issue by eku** [NixOS/nixpkgs#260142]
**Project description**

There's an existing [Nix package for MS Teams](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/teams/default.nix). Unfortunately Microsoft dropped the support for Linux and therefore 
https://github.com/NixOS/nixpkgs/commit/133b5d2343e03c900fa22fba9ab69df3bd4783a1 removes Linux from the package. Fortunately, there is an open-source replacement for Linux that could replace the distant Microsoft implementation.

**Metadata**

* homepage URL: https://github.com/IsmaelMartinez/teams-for-linux
* source URL: https://github.com/IsmaelMartinez/teams-for-linux
* license:gplv3
* platforms: linux

**Comment by dschrempf** [comment]
This package is already packaged. The package name is name is `teams-for-linux`. It has an unfree license though.
