### ISSUE TITLE
babashka (GraalVM) have broken UTF-8 support

### ISSUE THREAD

**Issue by diegobfernandez** [NixOS/nixpkgs#260161]
### Describe the bug

After #257292 babashka can't display Unicode characters

I have a babashka script that outputs the following JSON:
```json
{"text":"󰖨","alt":"light","tooltip":"light","class":["light"]}
```
The text is a Nerd Font Symbol code point.

After 88c5afe1535bc94ee275432ac5fcf50dd6579581 the output is:
```json
{"text":"?","alt":"light","tooltip":"light","class":["light"]}
```

### Steps To Reproduce
```console
[user@system:~]$ bb -e '(prn "bépo àê")'
"b??po ????"
```

### Expected behavior
```console
[user@system:~]$ bb -e '(prn "bépo àê")'
"bépo àê"
```

### Additional context

This has been fixed in the past by #153457

I did not test other packages that could be affected by the PR.

### Notify maintainers

@thiagokokada 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.05 (Stoat), 23.05.20231007.5a237ae`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(zealouscupuacu): `"nixos-22.11, nixos-unstable"`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thiagokokada** [comment]
Pretty sure this is related to this bug in GraalVM upstream: https://github.com/oracle/graal/issues/7502

I am curious if this is affecting projects using GraalVM 21.0.0 vanilla or if not, how is it working and why it is broken in `nixpkgs`.

**Comment by thiagokokada** [comment]
It does seem that even setting up `LC_ALL` inside the C compiler environment is not sufficient to make it work.

CC @heyarne to see if they have more context on what the possibly issue is.

**Comment by floscr** [comment]
I was able to fix this issue on my system by setting the `LOCALE_ARCHIVE` env:
```nix
LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
```
https://github.com/floscr/dotfiles/blob/0d741a75e513d51dffc4bf4b26ef7d644edcbce8/modules/shell/zsh.nix#L57

**Comment by thiagokokada** [comment]
> Shall we always sync the same version of graavm as upstream build ci? babashka/babashka#1640

I don't think this is the issue and even if it was, it is not like babashka is the only GraalVM package we have.

**Comment by thiagokokada** [comment]
I know that folks can't reproduce this issue with `babashka` upstream, but I also can't reproduce it with GraalVM using Java, e.g.:

```java
// HelloWorld.java
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello World");
    System.out.println("bépo àê");
  }
}
```
```console
$ javac HelloWorld.java
$ native-image -H:+UnlockExperimentalVMOptions -H:-CheckToolchain -H:+ReportExceptionStackTraces HelloWorld --verbose -march=compatibility
$ ./helloworld | fgrep 'Hello World'
$ ./helloworld | fgrep 'bépo àê' # works fine
```

A patch if anyone wants to test to be applied to `graalvm-ce`:

```diff
diff --git a/pkgs/development/compilers/graalvm/community-edition/buildGraalvm.nix b/pkgs/development/compilers/graalvm/community-edition/buildGraalvm.nix
index d7396d5f2d5c..a2e5aa427322 100644
--- a/pkgs/development/compilers/graalvm/community-edition/buildGraalvm.nix
+++ b/pkgs/development/compilers/graalvm/community-edition/buildGraalvm.nix
@@ -171,6 +171,7 @@ let
         public class HelloWorld {
           public static void main(String[] args) {
             System.out.println("Hello World");
+            System.out.println("bépo àê");
           }
         }
       ''} > HelloWorld.java
@@ -183,16 +184,19 @@ let
       echo "Ahead-Of-Time compilation"
       $out/bin/native-image -H:+UnlockExperimentalVMOptions -H:-CheckToolchain -H:+ReportExceptionStackTraces HelloWorld
       ./helloworld | fgrep 'Hello World'
+      ./helloworld | fgrep 'bépo àê'
 
       ${# --static is only available in Linux
       lib.optionalString (stdenv.isLinux && !useMusl) ''
         echo "Ahead-Of-Time compilation with -H:+StaticExecutableWithDynamicLibC"
         $out/bin/native-image -H:+UnlockExperimentalVMOptions -H:+StaticExecutableWithDynamicLibC HelloWorld
         ./helloworld | fgrep 'Hello World'
+        ./helloworld | fgrep 'bépo àê'
 
         echo "Ahead-Of-Time compilation with --static"
         $out/bin/native-image --static HelloWorld
         ./helloworld | fgrep 'Hello World'
+        ./helloworld | fgrep 'bépo àê'
       ''}
 
       ${# --static is only available in Linux
@@ -200,6 +204,7 @@ let
         echo "Ahead-Of-Time compilation with --static and --libc=musl"
         $out/bin/native-image --static HelloWorld --libc=musl
         ./helloworld | fgrep 'Hello World'
+        ./helloworld | fgrep 'bépo àê'
       ''}
 
       runHook postInstallCheck
```

So, can anyone reproduce this issue with GraalVM Native Image itself? If not, the only thing I can think is that the issue here is the `babashka` GCC (i.e.: non-static) version (upstream compiles with `musl` by default). Or something else.

**Comment by thiagokokada** [comment]
So I got this warning:
```
/nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed in a future release. Please refer to the GraalVM release notes.
```
But this was after `native-image` already started to build, so I assume this is the same issue as https://github.com/oracle/graal/issues/7502 and need to be fixed upstream.

**Comment by thiagokokada** [comment]
> So I got this warning:
> 
> ```
> /nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed in a future release. Please refer to the GraalVM release notes.
> ```
> 
> But this was after `native-image` already started to build, so I assume this is the same issue as [oracle/graal#7502](https://github.com/oracle/graal/issues/7502) and need to be fixed upstream.

To explain in more details why I think this is an upstream issue: I don't get the same `warning: setlocal` in the initial part of the build, only when the build starts that I get this warning.

So what I assume `native-image` is doing:
- Running the CC (C Compiler) inside a shell with clean environment
- Since this shell environment has no environment variables (at least, not the environment variables that we need), this ends up breaking macOS compilation and locale (Unicode) support in Linux

Not sure why it works in GraalVM itself though yet. This is all really strange.

**Comment by thiagokokada** [comment]
> And I do find https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemInOutErrSupport.java it's using `System.getProperty("sun.stdout.encoding")`, so I thought if I added those two into build args, maybe it'd work. And indeed it seems to work..

Thanks @sg-qwt for investigating this issue. Opened https://github.com/NixOS/nixpkgs/pull/267861 so we can have this fixed.
