### ISSUE TITLE
What is the state of idrisPackages.*?

### ISSUE THREAD

**Issue by yurrriq** [NixOS/nixpkgs#26014]
I'm unable to build any of them and thus unable to use `build-idris-package` on a recent checkout of `master`. I can provide the commit hash if useful, though it looks like `pkgs/development/idris-modules/` hasn't changed in a while.

`nix-build` fails, complaining, essentially, that nothing ends up in `$out`.

I've got half a mind to rework the Idris infrastructure to meet my needs, but don't want to duplicate efforts or take the wrong approach.

Please advise.

/cc @shlevy

**Comment by shlevy** [comment]
Hey @yurrriq! Sorry about this, I haven't used the idris infra in a while and it's probably just bitrotten. If you want to pair up on this, or work on it and ask questions as you go, that works for me! Let me know if not and I'll add fixing this up to my todo list, though it may bea few weeks before I can get to it.

**Comment by yurrriq** [comment]
@shlevy, no worries! I'm going to do some experimenting locally and I'll ping you when I push to my fork. One idea I have already is to add a `pkgName` parameter (similar to `lein-nix-build` iirc).

**Comment by Mic92** [comment]
ping @siddharthist

**Comment by mpickering** [comment]
I am giving the idrisPackages some spring cleaning currently. Did you do any work on this @yurrriq ?

**Comment by yurrriq** [comment]
@mpickering, awesome! I can check, but I don’t think I came up with anything particularly polished, if anything. Given my current schedule, I’d be happy to test, but can’t commit to any serious work.

**Comment by mpickering** [comment]
@yurrriq I have a first draft of a refactored implementation now that you can try if you like. It is modelled more closely on how haskellPackages works but still quite a bit different. It is my first bigger nix project so would be glad to hear comments on the design.

https://github.com/mpickering/nixpkgs/commit/de2725a46373d5fd9faea82560d45a8092024c51

**Comment by yurrriq** [comment]
Cool! I'll check it out when I get a chance.

**Comment by Infinisil** [comment]
Has been working well for a while now.
