### ISSUE TITLE
Package request: httptoolkit

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#260213]
**HTTP Toolkit is an open-source tool for debugging, testing and building with HTTP(S) on Windows, Linux & Mac.**

[demo video](https://httptoolkit.com/http-mock-demo.mp4)

**Metadata**

* homepage URL: https://httptoolkit.com/
* source URL: https://github.com/httptoolkit/httptoolkit-desktop
* license: AGPL v3.0
* platforms: linux, darwin

**Comment by TomaSajt** [comment]
Sorry, wasn't able to get it working. The httptoolkit-server is the difficult part. I tried building from source, however one of the dependencies tries to npm install more stuff in prebuild, so it wasn't building properly. I tried packaging the prebuilt binary but it's trying to do some auto updating and also package node with itself. I could have patched this when building from source, however the prebuilt one is minified & obfuscated so I couldn't do that.

**Comment by Et7f3** [comment]
Have you a branch to continue the work ?

**Comment by jh-devv** [comment]
+1

**Comment by Granitosaurus** [comment]
I've started a small bounty of 20$ on this: https://gitpay.me/#/task/843
It's not much but it would be great to have this tool on nix!

**Comment by TomaSajt** [comment]
I made another attempt at packaging this and I'm pretty close to getting httptoolkit-server to compile from source. This should help with patching out stuff, since we can do it before it gets obfuscated.

**Comment by Granitosaurus** [comment]
if anyone needs to run this on nix the appimage provided by HttpToolkit works pretty well on nix with no extra dependencies. See [the releases section](https://github.com/httptoolkit/httptoolkit-desktop/releases) and then `$ appimage-run HttpToolkit-1.17.2.AppImage`

Would still be great to have this as a nix package though.

**Comment by Granitosaurus** [comment]
Hey @TomaSajt thanks for adding this! You can claim the gitpay bounty here: https://gitpay.me/#/task/843 (I've tried to find your email to invite you but didn't have much luck) or email me at granitosaurus@pm.me

**Comment by TomaSajt** [comment]
Sent you an email, @Granitosaurus
