### ISSUE TITLE
Update request: Update Foliate to the GTK4 branch.

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#260232]
- Package name: [foliate](https://github.com/johnfactotum/foliate)
- Latest released version: 2.6.4

- Current version on the unstable channel: 2.6.4
- Current version on the stable/release channel: 2.6.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Seeing as the GTK3 branch (master) is pretty EOL and the app hasn't been updated for more than a year, I think it's a good idea to update to the latest commit of the GTK4 branch since that's the branch that being worked on.
**Notify maintainers**
@onny 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by onny** [comment]
the gtk4 branch is now stable
