### ISSUE TITLE
Adjust Linux Kernel Option `CONFIG_CMA_SIZE_MBYTES` 32 -> 128 to avoid `DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory` on OLIMEX Teres-I (AllWinner A64)

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#260222]
### Describe the bug

It seems that both stable and unstable channels on nixos are affected by https://gitlab.freedesktop.org/mesa/mesa/-/issues/8198

```console
$ journalctl -f
...
říj 10 15:33:30 tsvetan gnome-shell[1585]: DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory
...
```

### Steps To Reproduce
Try any kind of rendering on AllWinner A64-based system e.g. loading youtube page on epiphany

### Expected behavior

Allocate memory correctly

### Additional context

It makes the device progressively unusable starting with gnome failing to render correctly and eventually resulting in frozen system and halt.

The issue was supposedly fixed in https://gitlab.freedesktop.org/mesa/mesa/-/commit/c426e5677f36c3b0b8e8ea199ed4f2c7fad06d47, but seems to regressed back

### Armbian not affected on mesa 23.2.1-1 (debian sid)

```
root@olimex-teres-a64:/home/raptor# apt list --installed | grep mesa

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libegl-mesa0/unstable,unstable,now 23.2.1-1 arm64 [installed,automatic]
libgl1-mesa-dri/unstable,unstable,now 23.2.1-1 arm64 [installed]
libglapi-mesa/unstable,unstable,now 23.2.1-1 arm64 [installed,automatic]
libglx-mesa0/unstable,unstable,now 23.2.1-1 arm64 [installed]
mesa-utils-bin/unstable,unstable,now 8.5.0-1 arm64 [installed,automatic]
mesa-utils/unstable,unstable,now 8.5.0-1 arm64 [installed]
```

The issue doesn't seem to show up on debian (armbian)

### Armbian with mesa-23.1.6 is not affected

The issue was not observed on bookworm and trixie releases of armbian's debian

### Notify maintainers

CC @primeos @vcunat

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.5.0, NixOS, 23.11 (Tapir), 23.11.20230830.e7f38be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05"`
 - channels(root): `"nixos-23.05.3580.5d017a8822e0"`
 - nixpkgs: `/home/raptor/.nix-defexpr/channels/nixpkgs`
```

**Comment by alyssais** [comment]
> Heads-up: @[\]asahilina (blamed developer for the cause of the issue starting https://gitlab.freedesktop.org/mesa/mesa/-/commit/2adab724e59c662a046cb1da8bfb3177330e01da)

We don't need to ping upstream developers in Nixpkgs issues when the issue has already been reported upstream.

**Comment by alyssais** [comment]
If it's still broken upstream, then this should be reported upstream.  If it's a Nixpkgs-specific breakage, then the upstream developers don't need to be pinged.  Either way, pinging an upstream developer in a Nixpkgs issue is not the thing to do.

**Comment by Kreyren** [comment]
I tried mesa_22_3 package also with the same issue, the behavior is weird as when playing a video through `epiphany` it's the gnome-shell that reports the issue and starts to break while the video is lagging and seems to play okay otherwise

**Comment by AndreySV** [comment]
What CMA size is set for this platform? 64Mb? Have you tried increase it to 256Mb?

CONFIG_CMA_SIZE_MBYTES=256

**Comment by Kreyren** [comment]
> What CMA size is set for this platform? 64Mb? Have you tried increase it to 256Mb?
> 
> CONFIG_CMA_SIZE_MBYTES=256 -- @AndreySV (https://github.com/NixOS/nixpkgs/issues/260222#issuecomment-1869774655)

I didn't, can you elaborate why do you think it can affect the issue? (it's very difficult to get any cooperation from the blamed developer on what's causing the issue)

I am trying to compile the kernel with this change and will get back to you.

Additionally the AllWinner A64 doesn't seem to have any relevant information in terms of CMA in it's documentation (https://linux-sunxi.org/A64#Documentation)

**Comment by Kreyren** [comment]
Setting the CMA_SIZE_MBYTES on 128 seems to fix the issue, thanks @AndreySV!

Sorry for the delay i wasn't able to build a functional kernel on nixos due to kernel thermal driver development introducing regression

---

It's not sustainable to expect users to add:
```nix
boot.kernelPatches = [ {
		name = "teres_i-config";
		patch = null;
		extraConfig = ''
			CMA_SIZE_MBYTES 128
		'';
	} ];
```

As the kernel takes a long time to build and not everyone (my included) has a powerful enough arm64 system to build it in a reasonable time -> Can we adjust the CMA_SIZE_MBYTES in NixOS's kernel?

**Comment by uninsane** [comment]
> As the kernel takes a long time to build and not everyone (my included) has a powerful enough arm64 system to build it in a reasonable time -> Can we adjust the CMA_SIZE_MBYTES in NixOS's kernel?

there's the compile-time default, and boot-time overrides. if you don't want to recompile kernels, then set the value at boot time:
```nix
boot.kernelParams = [
  "cma=128M"
];
```

**Comment by Kreyren** [comment]
> > As the kernel takes a long time to build and not everyone (my included) has a powerful enough arm64 system to build it in a reasonable time -> Can we adjust the CMA_SIZE_MBYTES in NixOS's kernel?
> 
> there's the compile-time default, and boot-time overrides. if you don't want to recompile kernels, then set the value at boot time:
> 
> ```nix
> boot.kernelParams = [
>   "cma=128M"
> ];
> ``` -- @uninsane (https://github.com/NixOS/nixpkgs/issues/260222#issuecomment-1974893008)

Agree, the `cma` kernel parameter mitigates this issue.

**Comment by Kreyren** [comment]
The CMA seems to be a sufficient fix, closing

**Comment by uninsane** [comment]
good defaults are worth striving for: i shared the `boot.kernelParams` solution because i found that after spending several hours digging, so it would be better for all if CMA worked well out-of-the-box.

i lack the understanding for where the fix for this default _belongs_ (nixpkgs, nixos-hardware, documentation, upstream... somewhere), but please do feel free to re-open if nixpkgs has some role in that.

i wonder in the meantime @Kreyren if you know enough about the systems at play here that there might be a Wiki page to document this on? https://nixos.wiki/wiki/NixOS_on_ARM seems to be the toplevel for ARM-specific stuff, [mesa](https://nixos.wiki/wiki/Mesa) page if that's more appropriate.

**Comment by Kreyren** [comment]
> good defaults are worth striving for: i shared the boot.kernelParams solution because i found that after spending several hours digging, so it would be better for all if CMA worked well out-of-the-box.
>
> i lack the understanding for where the fix for this default belongs (nixpkgs, nixos-hardware, documentation, upstream... somewhere), but please do feel free to re-open if nixpkgs has some role in that.
>
> i wonder in the meantime @Kreyren if you know enough about the systems at play here that there might be a Wiki page to document this on? https://nixos.wiki/wiki/NixOS_on_ARM seems to be the toplevel for ARM-specific stuff, [mesa](https://nixos.wiki/wiki/Mesa) page if that's more appropriate. -- @uninsane (https://github.com/NixOS/nixpkgs/issues/260222#issuecomment-1998911932)

As i understood from info from @samueldr it should go in [nixos-hardware](https://github.com/NixOS/nixos-hardware) or project alike (i don't like the way nixos-hardware is doing the management so trying to implement a better solution in https://github.com/kreyren/nixware atm).
In terms of kernel there are more changes needed e.g. enabling [CEDRUS](https://linux-sunxi.org/Sunxi-Cedrus) i am currently trying to document the kernel modules in https://linux-sunxi.org/Olimex_Teres-A64#Linux_Kernel_Configuration_Reference to get distribution support more manageable to address the very common issues with insufficient kernel configuration across linux and *BSD.

The option is documented in https://linux-sunxi.org/Olimex_Teres-A64#Contiguous_Memory_Allocator_.28CMA.29 which is very known reference for teres users, the distribution wikis are kept only for distro-specific issues e.g. https://wiki.postmarketos.org/wiki/OLIMEX_Teres_i#Disfunctional_display_when_BL31.bin_is_compiled_with_SUNXI_SETUP_REGULATORS=0 and the teres page on NixOS wiki is already actively maintained by me https://nixos.wiki/wiki/NixOS_on_ARM/OLIMEX_Teres-A64.
