### ISSUE TITLE
error: path '/nix/store/52k8rqihijagzc2lkv17f4lw9kmh4ki6-gnugrep-3.11-info' is not valid

### ISSUE THREAD

**Issue by MobSenpai** [NixOS/nixpkgs#260288]
### Describe the bug
This is the error I am having after latest 'nix flake update' and then 'sudo nixos-rebuild switch --flake ...'
```
error: path '/nix/store/52k8rqihijagzc2lkv17f4lw9kmh4ki6-gnugrep-3.11-info' is not valid
```

### Steps To Reproduce
1. nix flake update
2. sudo nixos-rebuild switch --flake .#acer

### Expected behavior
nixos-rebuild should succeed without error

### Additional context
This happened with me around one week ago, and then I had to revert back to previous update. I thought if would be fixed in the new updates but even now I am not able to build. Please help!
my dotfile: https://github.com/MobSenpai/dotfiles.git

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20230925.6500b45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/i6hq63805y784dml4j8pgkrz3lryxzld-source`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5, NixOS, 23.11 (Tapir), 23.11.20230925.6500b45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/i6hq63805y784dml4j8pgkrz3lryxzld-source`
```

**Comment by Kranzes** [comment]
Probably related to https://github.com/NixOS/nix/issues/9052

**Comment by MobSenpai** [comment]
> Probably related to [NixOS/nix#9052](https://github.com/NixOS/nix/issues/9052)

What should I do then?

**Comment by Kranzes** [comment]
Not use 2.18. For about a week now unstable has reverted nixUnstable to be 2.17.

**Comment by MobSenpai** [comment]
I tried changing this line https://github.com/MobSenpai/dotfiles/blob/f9d579a0cdca6ed6eec35af9e5faca292e9e9c76/hosts/shared/nix.nix#L44 to pkgs.nixVersions.nix_2_17
but it didn't work

> Not use 2.18. For about a week now unstable has reverted nixUnstable to be 2.17.

**Comment by Kranzes** [comment]
You daemon also has to use 2.17, did you try rebooting?

**Comment by MobSenpai** [comment]
I think I somehow broke my nixos install. Reinstalling fixes it.
