### ISSUE TITLE
Package request: TurboWarp Desktop

### ISSUE THREAD

**Issue by TheBunnyMan123** [NixOS/nixpkgs#260277]
**Project description**
TurboWarp is a mod of Scratch that compiles into javascript and allows for more extensions. I would like it to be able to be installed locally without a flatpak

**Metadata**

* homepage URL: https://turbowarp.org/
* source URL: https://github.com/TurboWarp/desktop
* license: GPL 3.0
* platforms: linux, darwin

**Comment by MikaelFangel** [comment]
I think this package request should wait until they have updated their release tag > 1.9.3 because it would contain a fix for a know vulnerability (;

**Comment by TheBunnyMan123** [comment]
> I think this package request should wait until they have updated their release tag > 1.9.3 because it would contain a fix for a known vulnerability (;

I might start working on it and then update it to 1.9.3

**Comment by erenard** [comment]
The latest stable release is now `1.10.1`.
