### ISSUE TITLE
rust: 1.17

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#26022]
## Issue description

Please update to [1.17](https://blog.rust-lang.org/2017/04/27/Rust-1.17.html)!

Also, our current version (1.15) doesn't support LLVM 4 :(.

I tried tackling this but the build changed (requires rustbuild now?) and I'm not sure how that should be handled in NixOS.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by dtzWill** [comment]
cc rustc maintainers for input and so this is at least in their inbox: @madjar @cstrahan @wizeman @globin @havvy @wkennington @retrry

If folks have ideas how to handle this but not time, I'd be willing to do the grunt work with some guidance O:).

**Comment by retrry** [comment]
I had almost working 1.16 with rustbuild, but I didn't have time to finish.

I copied rustbuild configuration from, I think, Fedora RPM spec file for rustc. The only thing with 1.17 is that, I think, vendored libs are only included in tarball. So you would need to change rustbuild to not use fetchgit when building release version.

**Comment by retrry** [comment]
cc @LnL7 as he is active in rust pull requests :)

**Comment by bachp** [comment]
Does anyone have a work in progress branch?

**Comment by dtzWill** [comment]
My colleague @jcranmer was awesome and put together enough to get a working rustStable! :tada:

With his permission, I've pushed his work to the ['update/rust-1.17' branch](https://github.com/dtzWill/nixpkgs/tree/update/rust-1.17).

It'll need some more work (particularly handling the rustBeta/rustNightly bits) but hopefully serves as a good starting point!

**Comment by LnL7** [comment]
@dtzWill let me know if you want help testing/fixing the changes on darwin, altho I don't want to stall the update (a second time) if it's too tricky to get working.

**Comment by dtzWill** [comment]
I don't plan on working on this in the near future, FWIW, so this is open to anyone who's to the task! :).

**Comment by anderspapitto** [comment]
I took it a bit further, with updates to beta and nightly as well, and also a bit of cleaning up. If I don't hit any bugs I'll send a PR (or anyone else who's in a hurry is welcome to test it a bit and send the PR themselves)

https://github.com/anderspapitto/nixpkgs/commits/rust-updates

**Comment by FlorentBecker** [comment]
Do send a PR (even if with a "don't merge" warning) so that we can do review. I, for one, can't wait!

**Comment by anderspapitto** [comment]
@FlorentBecker https://github.com/NixOS/nixpkgs/pull/26275
