### ISSUE TITLE
rtmidi: propagate alsaLib

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#26028]
## Issue description
rtmidi.pc (package-config) requires alsa. However alsaLib is not propagated so it must be added explicitly

### Steps to reproduce
try to compile something in a nix-shell requiring rtmidi

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by OPNA2608** [comment]
In #111621, I changed the `Requires:` section in the pc file to `Requires.private:` like we did in rtaudio, I think this can be closed.
