### ISSUE TITLE
Build failure: ghcjs

### ISSUE THREAD

**Issue by sgrb** [NixOS/nixpkgs#260271]
### Steps To Reproduce

`nix-shell -p haskell.compiler.ghcjs`

### Build log
https://gist.github.com/sgrb/ac7cb89025d1b18de94e8c6980f597b0

### Additional context
ghcJS in nixpkgs seems to be broken. it fails on configuring of integer-gmp:
```
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: integer-gmp
Trying configure anyway.
Configuring integer-gmp-1.0.3.0...
configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg
checking for js-ghcjs-gcc... /nix/store/67wdkwmpfjfzis6a26f4xcpm8zyq3za2-ghcjs-8.10.7/lib/ghcjs-8.10.7/bin/emcc
checking whether the C compiler works... no
```

### Notify maintainers
@obsidian-systems-maintenance

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20231004.7131f3c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `""`
 - channels(slava): `""`
 - nixpkgs: `/etc/nix/nixpkgs`
```
nixpkgs revision: 7131f3c223a2d799568e4b278380cd9dac2b8579
(the same result observed with current HEAD)

**Comment by sternenseemann** [comment]
Can this be closed?

**Comment by sgrb** [comment]
Yes, i think. Actually ghcjs is now broken again, but due to another reason.
