### ISSUE TITLE
please consider switching uClibc to uClibc-ng

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#26020]
## Issue description

uClibc seems to be unmaintained. A fork called uClibc-ng actually seems to be maintained: https://www.uclibc-ng.org/

it might be worth switching to that instead.

**Comment by gentoofreak** [comment]
yeah, last uclibc release was 5 years ago. Gentoo Linux switched to uclibc-ng some time ago without much problems. I think it got even way better than with uclibc before.

**Comment by mmahut** [comment]
Are there any updates on this issue, please

**Comment by armijnhemel** [comment]
yup, fixed in a31984ecdaf7b011163c3c71679eb285d951d735 it seems, closing.
