### ISSUE TITLE
Completion support in nix-shell

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#26031]
We do have nice completion support for `nix-env`-installed programs, but as someone who primarily uses `nix-shell`, I'm sad to not get completions, even though `man` pages and other niceties work. Does anyone know what it would take to make completions work?

**Comment by matthewbauer** [comment]
Just to clarify, you want completion for commands within ```nix-shell``` not for ```nix-shell``` itself? (because there definitely is at least ZSH support for completion of ```nix-*``` commands.

I wonder if we could have an output called something like "completion" that would use paths ```/share/bash-completion/completions``` and ```/share/zsh/site-functions```? Obviously it wouldn't be a huge win for closure sizes, but would make things a little cleaner.

I have this in my ```.bashrc``` that should work:

```
# Check whether we're running a version of Bash that has support for
# programmable completion. If we do, enable all modules installed in
# the system (and user profile).
if shopt -q progcomp &>/dev/null; then
    . "@bash-completion@/etc/profile.d/bash_completion.sh"
    nullglobStatus=$(shopt -p nullglob)
    shopt -s nullglob
    for m in "@out@/etc/bash_completion.d/"* "@out@/share/bash-completion/completions/"*; do
        . $m
    done
    eval "$nullglobStatus"
    unset nullglobStatus p m
fi
```
You should be able to use that in nix-shell I think (replacing @out@ and @bash-completion@ of course).

**Comment by roberth** [comment]
for p in ${buildInputs}; do XDG_DATA_DIRS="$XDG_DATA_DIRS:$p/share"; done

This does the trick and should get bonus points for using the lazy loading that bash supports.
You can even run it when the nix-shell is already up, so it's quite flexible.

I suppose we could add this as a default shell hook in stdenv, or possibly in stdenv itself. I can imagine that in rare cases, build scripts use this variable, so it would fix those. I suppose it should be `nativeBuildInputs` in that case though...

On more thing is that we should probably check the existence of `$p/share` before adding it. And `p` should be a local variable.

Perhaps someone who's more familiar with the cross compiling stuff can chip in?

**Comment by gomain** [comment]
important to me :)

**Comment by roberth** [comment]
Almost done. I've added support for file based shells in https://github.com/NixOS/nixpkgs/pull/103501. Remember to use `nativeBuildInputs`.

Will write a Nix pr for the nix-shell command line.

**Comment by roberth** [comment]
Nixpkgs supports completion for `nativeBuildInputs` in `shell.nix` files. `nix-shell -p` completions can not be implemented properly in Nixpkgs itself, so here's issue https://github.com/NixOS/nix/issues/4254 and a PR that solves it https://github.com/NixOS/nix/pull/4452.

If completions don't work for you, it's more effective to open a new issue.
