### ISSUE TITLE
SABnzbd in Unstable has wrong version of SABCtools

### ISSUE THREAD

**Issue by hbjydev** [NixOS/nixpkgs#260395]
### Describe the bug

When booting up SABnzbd having done an update recently (5min ago at time of writing), I'm getting the following errors:

![image](https://github.com/NixOS/nixpkgs/assets/22327045/a722e076-ea70-4639-9871-ee15afc2cf87)

### Steps To Reproduce
1. In your `configuration.nix` on NixOS using current unstable, include the following:

```nix
let
  mkMediaService = (attrs:
    {
      enable = true;
      group = "media";
    } // attrs
  );
in
{
  # ...

  services.sabnzbd = mkMediaService {};

  # ...
}
```

3. Run `nixos-rebuild switch --flake .#<profile>`.

### Expected behavior
I expected it to pick up SABCtools 7.1.2, but it got 7.0.2 instead.

### Screenshots
See above

### Additional context
N/a

### Notify maintainers

@fridh @jojosch @adamcstephens

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4, NixOS, 23.11 (Tapir), 23.11.20231008.2646b29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by adamcstephens** [comment]
Opened a PR to fix this and provide better testing.
