### ISSUE TITLE
`prefetch-npm-deps` and `npmBuildPackage` fail to resolve npm dependencies

### ISSUE THREAD

**Issue by dukeofcool199** [NixOS/nixpkgs#260331]
### Describe the bug
when I attempt to build an npm package using `npmBuildPackage` or prefetch the npm dependencies with `prefetch-npm-deps` i am met with the following error

```
Error: https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.1.tgz: Dns Failed: resolve dns name 'registry.npmjs.org:443': Device or resource busy (os error 16)

Caused by:
    Device or resource busy (os error 16)
```

### Steps To Reproduce
1. clone my sample repo https://github.com/dukeofcool199/astrojs-nix
2. try to fetch the dependencies with `prefetch-npm-deps package-lock.json`
3. (optional) try to build the package with `nix build`

### Expected behavior
I expected 
  * `prefetch-npm-deps` to give me a hash
  * `npmBuildPackage` to build my node package

### Additional context
thread on nixos matrix chat with @lilyinstarlight 
https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$-UCOzrYvqiM8Jh_T28Eb7apvkQq7oyvkli2rEHN3tyc?via=nixos.org&via=matrix.org&via=tchncs.de

### Notify maintainers
@lilyinstarlight 

### Metadata 

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.51, NixOS, 23.05 (Stoat), 23.05.20230907.4f77ea6`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.17.0`
 - channels(jenkin): `""`
 - channels(root): `"nixos-22.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lilyinstarlight** [comment]
I can't seem to replicate this with prefetch-npm-deps from either nixos-unstable or nixos-23.05 (or nixos-22.11, since I see that it is still in your root channel list...)

Could you tell me more about your environment? Like what kind of network you are connected to, whether there is a proxy, etc and also can you share the exact way you are running `prefetch-npm-deps` and/or getting it into your `PATH` to run?

Thanks for the report!

**Comment by dukeofcool199** [comment]
Thanks for looking into this.

I just now realized that when I made that repo, I forgot to commit the inclusion of the `npm-prefetch-deps` as a part of the devShell defined in the flake before pushing it up.  I have pushed up those changes just now.

in the repo that i created for this issue, it has a flake with a devShell defined in it that contains the `prefetch-npm-deps` executable.  for this case I am running `nix develop` and then running `prefetch-npm-deps package-lock.json`

as for my environment.
location: my home so this is not a work environment
internet service: starlink
lan: connected to a starlink router over wifi


proxies: none

**Comment by dukeofcool199** [comment]
@lilyinstarlight 

I just ran another test my connecting my PC to my phone hotspot and now `prefetch-npm-deps` works as expected.  So i am now convinced that it has something to do with my internet connection.  Does `prefetch-npm-deps` have any kind of fault tolerance when something goes awry with the internet connection?

**Comment by lilyinstarlight** [comment]
There is some fault tolerance for transient (vs permanent) errors. #260011 fixes some problems with that, though

Can you `curl https://registry.npmjs.org/` on your starlink connection? Also maybe try `getent hosts registry.npmjs.org` and see what you get?

**Comment by dukeofcool199** [comment]
here is the output from the mentioned commands

'curl'
```console
{
  "db_name": "registry",
  "engine": "couch_bt_engine",
  "doc_count": 4759724,
  "doc_del_count": 332,
  "update_seq": 47084306,
  "purge_seq": 0,
  "compact_running": false,
  "sizes": {
    "active": 103525805254,
    "external": 266248341972,
    "file": 104936349859
  },
  "disk_size": 104936349859,
  "data_size": 103525805254,
  "other": {
    "data_size": 266248341972
  },
  "instance_start_time": "1697013782795008",
  "disk_format_version": 7,
  "committed_update_seq": 47084305,
  "compacted_seq": 47056398,
  "uuid": "3a4ad341a4111dd254daa731f37b37ae"
}
```

getent
```console
2606:4700::6810:1c22 registry.npmjs.org
2606:4700::6810:223 registry.npmjs.org
2606:4700::6810:1822 registry.npmjs.org
2606:4700::6810:1e22 registry.npmjs.org
2606:4700::6810:1f22 registry.npmjs.org
2606:4700::6810:323 registry.npmjs.org
2606:4700::6810:1d22 registry.npmjs.org
2606:4700::6810:1922 registry.npmjs.org
2606:4700::6810:123 registry.npmjs.org
2606:4700::6810:23 registry.npmjs.org
2606:4700::6810:1a22 registry.npmjs.org
2606:4700::6810:1b22 registry.npmjs.org
```

**Comment by lilyinstarlight** [comment]
You're getting the error messages from the older ureq fetcher. I looked at your flake and I noticed it is using an old version of nixpkgs, because it seems this line was typo'd as `github:NixOS/nixpkgs/23.05` instead of `github:NixOS/nixpkgs/nixos-23.05`:

https://github.com/dukeofcool199/astrojs-nix/blob/a56caea3113b0910301b85528982a8e041f2b516/flake.nix#L3

Can you fix that, `nix flake update`, and try again?

**Comment by dukeofcool199** [comment]
I changed the flake input to the following

`inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";`

and both `prefetch-npm-deps`  and `buildNpmPackage` function as expected

sorry this ended up being a versioning/fat fingering issue.  I greatly appreciate your help and your patience.

I will close this issue now.

**Comment by lilyinstarlight** [comment]
> and both `prefetch-npm-deps` and `buildNpmPackage` function as expected

I'm glad to hear it was that simple of a fix :)

> sorry this ended up being a versioning/fat fingering issue. I greatly appreciate your help and your patience.

No worries! It happens, and I appreciate you reporting it
