### ISSUE TITLE
TeamViewer package missing systemd service

### ISSUE THREAD

**Issue by robertosw** [NixOS/nixpkgs#260390]
### Steps To Reproduce
1. Install the current teamviewer package from nixpkgs ( v15.38.3 both in stable and unstable )
2. Start, will result in this error in TeamViewer UI:
  translated: "TeamViewer Daemon not running. As root, start with `teamviewer --daemon start`
  ![image](https://github.com/NixOS/nixpkgs/assets/47303535/a7f5f8fd-ab5b-4a1a-a54d-fad3e1a884c7)
4. `$ sudo teamviewer --daemon start`
```console
systemctl start teamviewerd.service
Failed to start teamviewerd.service: Unit teamviewerd.service not found.
```
5. Running `find ./  | grep .service` in `/nix/store/byig1ak6qwjzrvi3ll9y0rjfzhy521qg-teamviewer-15.38.3/share/teamviewer` results in
```console
./tv_bin/script/com.teamviewer.TeamViewer.Desktop.service
./tv_bin/script/com.teamviewer.TeamViewer.service
```

### Possible Fix
1. Download `x86-64bit` under `Other Systems (not officially supported)` from https://www.teamviewer.com/de/download/linux/ and unpack the tar.xz
2. running `find ./ | grep .service` in `~/Downloads/teamviewer`:
```console
./tv_bin/script/com.teamviewer.TeamViewer.Desktop.service
./tv_bin/script/com.teamviewer.TeamViewer.service
./tv_bin/script/teamviewerd.service
```
3. I dont know how NixPkgs work, so maybe just add this `teamviewerd.service` file?

### Note
The version I downloaded is 15.46.5 and NOT the .deb file. Maybe the service was simply missing in v15.38.3 (which is in the nix store) or the .deb file is missing the systemd service and the tar.xz has this included

### Notify maintainers
@jagajaga 
@jraygauthier
@gador 

### Metadata
```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.4112.5a237aecb572`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by robertosw** [comment]
I'd love to help with this, but I dont really understand how this process (going from some .tar / .deb / etc.  to a nixpkg) works

**Comment by robertosw** [comment]
I noticed that the teamviewerd.service file is manually deleted here: https://github.com/NixOS/nixpkgs/blob/f99e5f03cc0aa231ab5950a15ed02afec45ed51a/pkgs/applications/networking/remote/teamviewer/default.nix#L44C3-L51C137

[Later](https://github.com/NixOS/nixpkgs/blob/f99e5f03cc0aa231ab5950a15ed02afec45ed51a/pkgs/applications/networking/remote/teamviewer/default.nix#L81) in the same file, the existing two services are installed. I suppose its necessary to add install instructions for the teamviewerd.service
I dont know alot about systemd services and how they are installed, otherwise I would have made a pull request

**Comment by gador** [comment]
Your error message
>Failed to start teamviewerd.service: Unit teamviewerd.service not found.
 
indicates that you are not using the provided systemd service from NixOS.

Teamviewer will only really work in NixOS with the service enabled. (See [here](https://search.nixos.org/options?channel=unstable&show=services.teamviewer.enable&from=0&size=50&sort=relevance&type=packages&query=teamview)). The reason we delete the provided systemd file is because we create a cusom one (https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/monitoring/teamviewer.nix)

Do you use NixOS? If so, did you enable the service?

**Comment by robertosw** [comment]
Thank you 👍🏼 

It would be nice if this is stated [here](https://search.nixos.org/packages?channel=unstable&show=teamviewer&from=0&size=50&sort=relevance&type=packages&query=teamviewer)
Not only for users adding teamviewer to their config, but also for users who just want to try out teamviewer in a nix-shell
