### ISSUE TITLE
nix-env fails with "feedgenerator: no such file or directory" error

### ISSUE THREAD

**Issue by lufia** [NixOS/nixpkgs#26045]
## Issue description

Today, I updated nixpkgs repository.
After updated, `nix-env` fails **'feedgenerator': No such file or directory**

```
error: while evaluating anonymous function at /Users/lufia/nixpkgs/lib/meta.nix:42:54, called from /Users/lufia/nixpkgs/lib/attrsets.nix:199:52:
while evaluating ‘isDerivation’ at /Users/lufia/nixpkgs/lib/attrsets.nix:295:18, called from /Users/lufia/nixpkgs/lib/meta.nix:42:62:
while evaluating the attribute ‘feedgenerator’ at /Users/lufia/nixpkgs/pkgs/top-level/python-packages.nix:10801:3:
while evaluating ‘callPackageWith’ at /Users/lufia/nixpkgs/lib/customisation.nix:95:35, called from /Users/lufia/nixpkgs/pkgs/top-level/python-packages.nix:10801:19:
while evaluating ‘makeOverridable’ at /Users/lufia/nixpkgs/lib/customisation.nix:54:24, called from /Users/lufia/nixpkgs/lib/customisation.nix:99:8:
getting status of ‘/Users/lufia/nixpkgs/pkgs/development/python-modules/feedgenerator’: No such file or directory
```

ec117f761f01bc47c11dc24528faf4506f57ece1 has no error. but 7bb98bb02cd25fb4764aa120bd990d669f74d17f has above error.

### Steps to reproduce

1. `export NIX_PATH=nixpkgs=nixpkgs-repository`
1. `cd nixpkgs-repository`
2. `git pull`
3. `nix-env -qa --show-trace '.*rust.*'`

## Technical details

* System: macOS 10.12.5
* Nix version: 1.11.9
* Nixpkgs version: 17.09pre-git
* Sandboxing enabled: no

**Comment by utdemir** [comment]
@Mic92 It looks like you forgot to checkout the file for `feedgenerator` in your commit https://github.com/NixOS/nixpkgs/commit/7bb98bb02cd25fb4764aa120bd990d669f74d17f .

**Comment by utdemir** [comment]
See: https://github.com/NixOS/nixpkgs/pull/26030#commitcomment-22256173 .

**Comment by Mic92** [comment]
sorry for inconvenience. error corrected.
