### ISSUE TITLE
Package request: evolution

### ISSUE THREAD

**Issue by falavu** [NixOS/nixpkgs#260428]
**Project description**
It wouldt be nice to download  Evolution for MacOS/Darwin. 
* platforms: darwin, ...

**Comment by jfvillablanca** [comment]
can you provide metadata for this package request? tnx

- homepage URL: 
- source URL: 
- license:

**Comment by l0b0** [comment]
I expect they mean [GNOME Evolution](https://search.nixos.org/packages?channel=23.11&show=evolution&from=0&size=50&sort=relevance&type=packages&query=evolution), which is [currently only supported on Linux](https://github.com/NixOS/nixpkgs/blob/5ab08ad057499977d489f1b378e79d166a684e6c/pkgs/applications/networking/mailreaders/evolution/evolution/default.nix#L133).
