### ISSUE TITLE
Package request: Ollama (local LLM runner)

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#260491]
**Project description**

Ollama is an application for Mac and Linux that makes it easy to locally run open-source LLMs, including Llama-2.  Ollama supports a list of open-source models available on [ollama.ai/library](https://ollama.ai/library), or you can import custom ones.  Ollama can integrate with IDEs via tools like [Continue.dev](https://continue.dev/docs/reference/Models/ollama).

**Metadata**

* homepage URL:  https://ollama.ai/
* source URL:  https://github.com/jmorganca/ollama
* license: mit
* platforms: unix, linux, darwin

**Comment by natsukium** [comment]
Ollama is already added to [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/ollama/default.nix#L30).
