### ISSUE TITLE
Put docstrings for types in types.nix

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#26055]
https://github.com/NixOS/nixpkgs/pull/21875 intoduced `coercedTo`, but didn’t bother to document the type in any way.

Introducing a new (non-trivial) type means including
1) A docstring with a short explanation
2) An entry [in the manual](https://nixos.org/nixos/manual/index.html#sec-option-types) with extensive description and a usage example.

**Comment by abbradar** [comment]
@Profpatsch Thanks -- to be honest I haven't found any documentation in `types.nix` itself and (wrongly) assumed that there are no other places where it might be added. I've placed a warning to others in `types.nix`.  What do you mean by a docstring?

**Comment by abbradar** [comment]
(reopening because I'm not sure what @Profpatsch meant by docstrings)

**Comment by Profpatsch** [comment]
I’d like every function to have a (short) description directly over the definition, otherwise you have to always look stuff up in the manual. Like a short refresher on what it does.

**Comment by abbradar** [comment]
Ah, good idea! I just haven't seen anything for existing types in `types.nix` and figured out that you might have been meaning something else. Let's do those for other types too; I'll work on this a bit later.
