### ISSUE TITLE
simple-scan has no icon

### ISSUE THREAD

**Issue by montag451** [NixOS/nixpkgs#26054]
## Issue description

Its desktop file specify that the icon is named simple-scan but no icon with such name exists. This commit e7cc2de7dda5ccb04e6d169158225072e4ff23b9  by @jraygauthier solves the problem but @peterhoeg has removed the fix in this commit f2c3e29ac47f24518968f3bcc3e8129476b8a887. I can submit a pull request to restore the fix but I would like to know if there is a reason why the fix has been removed before doing so.

## Technical details

* System: NixOS 17.03.1180.27b488f28e (Gorilla) with Gnome3
* Nix version: 1.11.8
* Nixpkgs version: 17.03.1180.27b488f28e
* Sandboxing enabled: yes

**Comment by peterhoeg** [comment]
I off-hand don't remember why. Let me check a little later tonight and update you.

**Comment by peterhoeg** [comment]
@montag451, a PR to restore the icons would *very* welcome, thanks!
