### ISSUE TITLE
no linuxKernel.packages.linux_latest

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#260636]
### Describe the bug
while we have `linuxKernel.packages.linux_{latest_libre,xanmod_latest}` and the actual latest in `linux_6_5`
and `linuxPackages_latest`
we don't have `linuxKernel.packages.linux_latest`

### Steps To Reproduce
1. in `nix repl '<nixpkgs>'`,
2. `linuxKernel.packages.`, press \<tab> and see no `linuxKernel.packages.linux_latest`

### Expected behavior
`linuxKernel.packages.linux_latest` to exist
or if `linuxKernel.packages` is equivalent to `linuxPackages_*` is equivalent and unmaintained, `linuxKernel.packages` to be deprecated?

### Notify maintainers

no listed maintainers for `linuxKernel.packages.linux_6_5` so pinging the maintainers of `linux_latest`
@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.12, NixOS, 23.11 (Tapir), 23.11.git.d2b5f3e28e2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"musnix, nixos, nixos-hardware"`
 - channels(evils): `"home-manager, nixos-unstable, nixpkgs"`
 - nixpkgs: `/home/evils/.nix-defexpr/channels/nixpkgs`
```

**Comment by eclairevoyant** [comment]
Couple things:
* Syntax is wrong, it should be `nix repl -f '<nixpkgs>'`
* You'll want to make sure you've updated your channels, and if you have no user channel named `nixpkgs`, you'll want to update the root `nixos` channel.

**Comment by eclairevoyant** [comment]
And I realised I didn't read your actual question - but `linuxPackages_latest` exists and refers to `linuxKernel.packageAliases.linux_latest` which is likely what you wanted to look for

**Comment by evils** [comment]
dunno why this was closed
there's still no `linuxKernel.packages.linux_latest` on either master or staging
that there's an equivalent reference elsewhere doesn't mean there's one where i was expecting one

**Comment by eclairevoyant** [comment]
I don't understand the issue here, the latest kernel exists.

**Comment by evils** [comment]
i don't know how to phrase it any better than i did in the original description at the top here :(
the alias for the latest kernel, `linuxKernel.packages.linux_latest` does not exist

you pointed out `linuxPackages_latest`, and i'm using that now,
but i think the `linuxKernel.packages` set should have an alias to the latest kernel as well,
or one of these two to be deprecated, if they're indeed equivalent

**Comment by danwdart** [comment]
Strangely, whilst I didn't see it in the searchable list, a meta component did exist so I could just do `kernelPackages = pkgs.linuxPackages_latest;` in my config at the time. Is there a new recommended way to do it?
