### ISSUE TITLE
Package update request: Unity3D: 5.5.3xf1 -> 5.6.1xf1

### ISSUE THREAD

**Issue by lboklin** [NixOS/nixpkgs#26061]
Relevant default.nix: 
https://github.com/NixOS/nixpkgs/blob/2090aa4f65e860567af03cb3b7aa042df7168ead/pkgs/development/tools/unity3d/default.nix

Binary/package download available here: 
https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/#post-3070212

**Comment by abbradar** [comment]
I haven't tested it extensively, only verified that it runs (it still required some fixes in how we add RPATHs).
