### ISSUE TITLE
systembus-notify: "sd_bus_default_user: Permission denied"

### ISSUE THREAD

**Issue by xnumad** [NixOS/nixpkgs#260694]
### Describe the bug
systembus-notify (v1.1) isn't able to send notifications when enabled via `services.systembus-notify.enable = true;`

### Steps To Reproduce
1. Add `services.systembus-notify.enable = true;` to system `configuration.nix`
2. `sudo nixos-rebuild switch`
3. Run `dbus-send --system / net.nuetzlich.SystemNotifications.Notify 'string:summary text only'`
4. bug: You don't receive a notification in your desktop environment.

### Expected behavior
Get a notification in your desktop environment.

### Additional context

```console
[user@system:~]$ systemctl --user status systembus-notify
× systembus-notify.service - system bus notification daemon
     Loaded: loaded (/etc/systemd/user/systembus-notify.service; enabled; preset: enabled)
    Drop-In: /nix/store/96xnc61lbw6xl8hws1hd3paf4xqkaspr-user-units/systembus-notify.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Thu 2023-10-12 15:33:42 CEST; 19min ago
   Duration: 4ms
   Main PID: 69872 (code=exited, status=4)
        CPU: 35ms

Oct 12 15:33:42 nixos systemd[1829]: systembus-notify.service: Scheduled restart job, restart counter is at 5.
Oct 12 15:33:42 nixos systemd[1829]: systembus-notify.service: Start request repeated too quickly.
Oct 12 15:33:42 nixos systemd[1829]: systembus-notify.service: Failed with result 'exit-code'.
Oct 12 15:33:42 nixos systemd[1829]: Failed to start system bus notification daemon.
```

journalctl:
```
Oct 12 14:00:00 nixos systembus-notify[23911]: connecting to d-bus user   bus: fatal: sd_bus_default_user: Permission denied
```
Originating from code line: https://github.com/rfjakob/systembus-notify/blob/v1.1/main.c#L81

### Workaround

It works however if you
1. run `nix-shell -p systembus-notify` (or add the package to `environment.systemPackages` for a permanent install)
2. Run `systembus-notify` in a terminal _and keep it open_
3. do step 3 from reproduction steps (_in another terminal_)
4. Get notification ![plasma-notification](https://github.com/NixOS/nixpkgs/assets/34810600/7ca062bf-5064-4065-950e-955b9c364360)

### Notify maintainers

@peterhoeg 

### Metadata
(nixpkgs-unstable)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11pre532072.81e8f48ebdec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(xnumad): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by solson** [comment]
I just noticed this bug, too. Same error in journalctl for me.
