### ISSUE TITLE
Spurious messages when setting environment.usrbinenv to null

### ISSUE THREAD

**Issue by stephen-huan** [NixOS/nixpkgs#260658]
### Describe the bug

If `environment.usrbinenv` is set to `null` in `configuration.nix`
```nix
environment.usrbinenv = null;
```
then `nixos-rebuild switch` prints
```
rmdir: failed to remove '/usr/bin': No such file or directory
rmdir: failed to remove '/usr': No such file or directory
Activation script snippet 'usrbinenv' failed (1)
```
This is because the current [logic](https://github.com/NixOS/nixpkgs/blob/ba0e049eb2ddf9fa3c6ae6f246c7332096dbc724/nixos/modules/system/activation/activation-script.nix#L261-L264)
```nix
      else ''
        rm -f /usr/bin/env
        rmdir --ignore-fail-on-non-empty /usr/bin /usr
      '';
```
ignores the non-existence of `/usr/bin/env` but does not check whether `/usr/bin` or `/usr` exist before the `rmdir`.

As `rmdir` does not have a `-f` flag it's a bit awkward, but I think just adding an idempotent `mkdir` should be ok. 
```nix
      else ''
        rm -f /usr/bin/env
        mkdir -p /usr/bin
        rmdir --ignore-fail-on-non-empty /usr/bin /usr
      '';
```

### Steps To Reproduce
1. Create a `configuration.nix` like
```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running `nixos-help`).

{ config, lib, pkgs, modulesPath, ... }:
{
  ...
  environment.usrbinenv = null;
}
```
2. Run `nixos-rebuild switch`.

### Expected behavior
No errors printed to console.

### Notify maintainers

I'm not quite sure who to ping, maybe @roberth and @dasJ?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -I nixpkgs=flake:nixpkgs -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.11 (Tapir), 23.11.20231009.f99e5f0`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `not found`
```
(I'm using a flake with nixpkgs pinned to f99e5f03cc0aa231ab5950a15ed02afec45ed51a)

**Comment by stephen-huan** [comment]
Somewhat related, `systemd-update-done.service` will error when it tries to `stat` the (non-existent) `/usr`.

Wrapping the service to make `/usr` and remove it again seems to work.
```nix
  systemd.services.systemd-update-done.serviceConfig.ExecStart = [
    "" # clear
    (
      pkgs.writeShellScript "systemd-update-done-wrapper" ''
        mkdir -p /usr
        ${pkgs.systemd}/lib/systemd/systemd-update-done
        rmdir --ignore-fail-on-non-empty /usr
      ''
    )
  ];
```

The implementation of the first fix proposed above also seems to work.
```nix
  system.activationScripts.usrbinenv =
    lib.mkIf (config.environment.usrbinenv == null) (
      lib.mkForce ''
        rm -f /usr/bin/env
        mkdir -p /usr/bin
        rmdir --ignore-fail-on-non-empty /usr/bin /usr
      ''
    );
```

**Comment by roberth** [comment]
I really don't like the extra operations. Those just make it slower and more chaotic.
The nicest solution would involve improving `mkdir` itself.
Short of that, you could `test -d` and only run `rmdir` if it makes sense to do so.

Something like `if test -e /usr/bin; then rmdir /usr/bin; fi` and the same line for `/usr`.
This actually also makes it ever so slightly faster in the common case, because `test` does not create a process.

**Comment by stephen-huan** [comment]
Sure, something like
```nix
  system.activationScripts.usrbinenv =
    lib.mkIf (config.environment.usrbinenv == null) (
      lib.mkForce ''
        rm -f /usr/bin/env
        if test -e /usr/bin; then
          rmdir --ignore-fail-on-non-empty /usr/bin
        fi
        if test -e /usr; then
          rmdir --ignore-fail-on-non-empty /usr
        fi
      ''
    );
```
works fine.

I think `-e` is preferable to `-d` as we might want to warn if either `/usr/bin` or `/bin` are files rather than silently ignore.

**Comment by stephen-huan** [comment]
@roberth I opened #264523. On second thought `-d` is preferable to `-e` because if for whatever reason `/usr/bin` or `/usr` are files we probably shouldn't touch them. Rather, it should basically be a perfect inverse of

```bash
        mkdir -p /usr/bin
        chmod 0755 /usr/bin
        ln -sfn ${config.environment.usrbinenv} /usr/bin/.env.tmp
        mv /usr/bin/.env.tmp /usr/bin/env # atomically replace /usr/bin/env
```
