### ISSUE TITLE
lxc-container: Why is "LoadCredential=" overwritten

### ISSUE THREAD

**Issue by marrobHD** [NixOS/nixpkgs#260670]
### Describe the bug
The systemd drop-in `systemd-lxc-service-overrides` in [lxc-container.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/lxc-container.nix)  overrides `LoadCredential`(`LoadCredential=` is set). Why is it necessary to overwrite LoadCredential?
```nix
    # Add the overrides from lxd distrobuilder
    # https://github.com/lxc/distrobuilder/blob/05978d0d5a72718154f1525c7d043e090ba7c3e0/distrobuilder/main.go#L630
    systemd.packages = [
      (pkgs.writeTextFile {
        name = "systemd-lxc-service-overrides";
        destination = "/etc/systemd/system/service.d/zzz-lxc-service.conf";
        text = ''
          [Service]
          ProcSubset=all
          ProtectProc=default
          ProtectControlGroups=no
          ProtectKernelTunables=no
          NoNewPrivileges=no
          LoadCredential=
        '' + lib.optionalString cfg.privilegedContainer ''
          # Additional settings for privileged containers
          ProtectHome=no
          ProtectSystem=no
          PrivateDevices=no
          PrivateTmp=no
          ProtectKernelLogs=no
          ProtectKernelModules=no
          ReadWritePaths=
        '';
      })
    ];
```

I use `LoadCredential` in my systemd units and allowing it in an lxc has not caused any issues on my side so far.

Previously I copied the overrides from [lxc-container.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/lxc-container.nix) and commented it out, and it got overwritten. That does not work anymore...
As far as I know, it merges based on priority (and both would be default), but that shouldn't cause disabling LoadCredential upstream anyway.

I tried to overwrite with `(lib.hiPrio (pkgs.writeTextFile ...` but that was not successful.
What can I do to fix my system?

### Steps To Reproduce
1. Attach the following config & build:
<details><summary>lxc-container.nix</summary><br>

```nix
{ modulesPath, pkgs, lib, config, ... }:
{
  imports = [
   (modulesPath + "/virtualisation/lxc-container.nix")
  ];

    # override  bc it breaks step-ca
    systemd.packages = [
      (lib.hiPrio (pkgs.writeTextFile {
        name = "systemd-lxc-service-overrides";
        destination = "/etc/systemd/system/service.d/zzz-lxc-service.conf";
        text = ''
          [Service]
          ProcSubset=all
          ProtectProc=default
          ProtectControlGroups=no
          ProtectKernelTunables=no
          NoNewPrivileges=no
          # LoadCredential=   
        '' + lib.optionalString config.virtualisation.lxc.privilegedContainer ''
          # Additional settings for privileged containers
          ProtectHome=no
          ProtectSystem=no
          PrivateDevices=no
          PrivateTmp=no
          ProtectKernelLogs=no
          ProtectKernelModules=no
          ReadWritePaths=
        '';
      }))
    ];
}
```

</details>
3. View `/etc/systemd/system/service.d/zzz-lxc-service.conf` and see that `LoadCredential=` is not commented out.

### Expected behavior
`LoadCredential=` should be commented out.

### Notify maintainers
@adamcstephens

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.16-10-pve, NixOS, 23.11 (Tapir), 23.11.20231009.f99e5f0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.11pre523424.f718d9b5d27a"`
 - nixpkgs: `/nix/store/902j4afzd3glcviwv1kzkqq3bb05y736-source`
```

**Comment by adamcstephens** [comment]
As mentioned in the associated comment, this override file comes directly from upstream distrobuilder. "Why" would need to be directed to them, but it's not clear from the initial implementation upstream the actual reason. https://github.com/lxc/distrobuilder/pull/501

The merging for this override happens at that systemd level. I've not tried personally to turn it back on.

Are you saying you have success using systemd credentials in an LXC container?
Is it a nested or privileged container?
Did you have to implement the following?

```nix
    boot.specialFileSystems = {
      "/run".options = ["shared"];
    };
  };
```

**Comment by marrobHD** [comment]
> Are you saying you have success using systemd credentials in an LXC container? Is it a nested or privileged container? Did you have to implement the following?
It is an unprivileged container with fuse and nesting enabled. 
No extra config was required. I was able to get step-ca (which uses LoadCredential) running in an lxc.
Sadly I cannot overwrite "LoadCredential=" anymore...
```
[root@nix-exp1:~]# mount | grep run
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=32945600k,mode=755,uid=100000,gid=100000,inode64)
ramfs on /run/keys type ramfs (rw,nosuid,nodev,relatime,mode=750)
tmpfs on /run/wrappers type tmpfs (rw,nodev,relatime,size=65891196k,mode=755,uid=100000,gid=100000,inode64)
none on /run/secrets-for-users.d type ramfs (rw,nosuid,nodev,relatime,mode=751)
none on /run/secrets.d type ramfs (rw,nosuid,nodev,relatime,mode=751)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=13178236k,nr_inodes=3294559,mode=700,uid=100000,gid=100000,inode64)
```

**Comment by adamcstephens** [comment]
Can you show me an example of how you use `LoadCredential`? I'm open to changing this on our end, since we don't use systemd-sysusers, but I actually want to write a test for this so we can ensure it continues to work.

**Comment by marrobHD** [comment]
I configured step-ca.

`services.step-ca.intermediatePasswordFile` propagates LoadCredential
See: https://github.com/NixOS/nixpkgs/blob/08a8f7903da8d35dfdd71ded28bcd9032053eba2/nixos/modules/services/security/step-ca.nix#L112C15-L113C15

**Comment by marrobHD** [comment]
Hi,
can I provide more information, if needed, so you can build the test?

Thanks for the effort :>

**Comment by adamcstephens** [comment]
No, I understand the problem and have an idea of how to test it. It's just a matter of time and priority. If you're interested in attempting this, I plan to `nixos/tests/lxd/container.nix`:

- add to the release configuration a simple service which will read a credential and write an output file with the data
- a check that will compare and verify the output file matches the original content

**Comment by marrobHD** [comment]
Ahh okay. Just wanted to make sure that this won't get forgotten.
Thanks :>

**Comment by adamcstephens** [comment]
My solution for this is https://github.com/NixOS/nixpkgs/pull/264929
It may still be a bit until I can get a committer to review and merge my two PRs.

In development of that change I discovered our porting of the logic was incorrect, and LoadCredential should not be disabled for nested containers.

**Comment by adamcstephens** [comment]
@marrobHD can you verify if this is resolved for you now?

**Comment by marrobHD** [comment]
> @marrobHD can you verify if this is resolved for you now?
> 
> It did not make 23.11 unfortunately.

Yes its solved. Thanks <3

**Comment by Pascal-Vtx** [comment]
Hi,  I drop here my  'quick and dirty' solution for removing the LoadCredential override in lxc containers (**for nixos 23.11**)
if it can be useful to someone encountering this issue ...

```nix
imports = [
    ## Quick and dirty fix for https://github.com/NixOS/nixpkgs/issues/260670
    # "${toString modulesPath}/virtualisation/lxc-container.nix"
    (builtins.toFile "lxc-container.nix" (builtins.replaceStrings
      [ "LoadCredential=" "./lxc-instance-common.nix" ]
      [ "#LoadCredential=" "${toString modulesPath}/virtualisation/lxc-instance-common.nix" ]
      (builtins.readFile "${toString modulesPath}/virtualisation/lxc-container.nix")))
  ];
```

**Comment by srd424** [comment]
I think I've misunderstood this bug a bit .. I'm still having problems with buildbot (which uses LoadCredential) in 24.05, trying to run directly in an lxc container in incus (with incus running on non-nixos.) ` /run/systemd/system/service.d/zzz-lxc-service.conf` gets created now (note in `/run` not `/etc`) and still disables LoadCredential. Should this have been fixed, or did we only fix the NixOS part of this problem?

**Comment by srd424** [comment]
Turns out this file ending up in `/run` makes it a right nuisance to override. I'm a bit of a nix newbie and have ended up with the following - I'd be surprised if there wasn't a better way, but if anyone else is desperate..
```
systemd.generators.lxc-override = pkgs.writeShellApplication {
    name = "lxc-override-generator";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      DIR=/run/systemd/system/buildbot-worker.service.d
      mkdir -p $DIR
      cat >/$DIR/zzz-lxc-service.conf <<EOF
      [Service]
      ProcSubset=all
      ProtectProc=default
      ProtectControlGroups=no
      ProtectKernelTunables=no
      NoNewPrivileges=no
      #LoadCredential=
      PrivateNetwork=no
      EOF
    '';
  } + "/bin/lxc-override-generator";
```

**Comment by adamcstephens** [comment]
Are you enabling `security.nesting=true` on your container? I would guess not, which is why LoadCredential is being overwritten.

In general, it's strongly recommended to use nested containers with NixOS. While the OS technically works without it, I think nesting is required even for simple nix builds.

The configuration in /run only gets created if nested https://github.com/lxc/distrobuilder/blob/f03da024aa1b45624214e8020eccd1b9dda9cf43/distrobuilder/lxc.generator#L177-L182

And is verified in our tests https://github.com/NixOS/nixpkgs/blob/097350409e37e6fd7d6f93610107fa15f6d82911/nixos/tests/incus/container.nix#L109

Note that we patch that upstream generator here https://github.com/NixOS/nixpkgs/blob/af52c7b5155c9b0f68690ecddfcd8957c8214495/pkgs/tools/virtualization/distrobuilder/nixos-generator.patch

**Comment by srd424** [comment]
Ah, I think I may have really misunderstood the earlier conversation, apologies! I assumed the nested container stuff applied to actual nesting of full containers, but I guess systemd does a lot with namespaces etc that may also require it (and probably explains the restrictions upstream's script it enforcing when it's off.) And as you say, nix's sandboxing probably needs it too. I will update my container config later - thank you for the pointer.
