### ISSUE TITLE
Package request: OmniSharp package

### ISSUE THREAD

**Issue by lboklin** [NixOS/nixpkgs#26060]
To enable auto-completion in various editors.
https://github.com/OmniSharp/omnisharp-roslyn

Related editor plugins:
https://github.com/OmniSharp/omnisharp-emacs
https://github.com/OmniSharp/omnisharp-vim

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding this package here.

**Comment by lboklin** [comment]
Fair enough :) I'll be sure to drop by once I manage to set aside some time for it.
