### ISSUE TITLE
Package request: imaginary

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#260774]
**Project description**

Fast, simple, scalable, Docker-ready HTTP microservice for high-level image processing. Recommended by [NextCloud Documentation](https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews) for generating image previews.

**Metadata**

* homepage URL: https://fly.io/docs/app-guides/run-a-global-image-service/
* source URL: https://github.com/h2non/imaginary
* license: mit
* platforms: linux

**Comment by eclairevoyant** [comment]
already in nixpkgs
https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/imaginary/default.nix

also has a nixos module
