### ISSUE TITLE
Update request: dorion 1.2.1 → 2.1.0

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#260737]
- Package name: dorion
- Latest released version: 2.1.0

- Current version on the unstable channel: 1.2.1
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by Nyabinary** [comment]
cc: @AndersonTorres since you were the last packager of Dorion.

**Comment by wegank** [comment]
Closed by #274209.
