### ISSUE TITLE
webkitgtk: need upgrade and cleanup

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#26098]
## Issue description

https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/webkitgtk

```nixpkgs``` has two version of ```webkitgtk```: ```2.4.11``` and ```2.14.5```; both version are outdated (current ```2.16.3```/```2.17.1```) and has security issues.
Moreover ```pkgs.webkitgtk``` points to ```2.14``` and ```pkgs.webkitgtk2``` points to older ```2.4``` which is confusing and it forces some packages to use the oldest version.

I would like to deprecate ```2.4``` and upgrade ```2.14``` to ```2.16```.

The problem is there are few darwin-related patches which I could not reproduce due to absence a Mac and experience with it, so I am afraid a straightforward upgrade may break something on Mac.

The package has no maintainer.

cc: @shlevy @hamishmack

**Comment by vcunat** [comment]
See https://github.com/NixOS/nixpkgs/issues/18312 and other related issues.  Some packages weren't so easy to update to newer webkit.  I'm not sure if it has changed much since then.

**Comment by volth** [comment]
I hope those who survived upgrade up to ```2.14``` should work with ```2.16```.
There is also ```wxGTK30```'s dependency on ```2.4``` which might be wrong.

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/pull/26104
https://github.com/NixOS/nixpkgs/pull/26125
