### ISSUE TITLE
LuaRocks does not respect $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by offsetcyan** [NixOS/nixpkgs#260951]
### Describe the bug
The default LuaRocks configuration generated at `$out/etc/luarocks/config-<version>.lua` hardcodes one of the `rocks _trees` as `$HOME/.luarocks`. LuaRocks by default [explicitly respects the XDG_CONFIG_HOME environment variable](https://github.com/luarocks/luarocks/wiki/Config-file-format) and so this behaviour provides a slightly degraded user experience. 

### Steps To Reproduce
1. Install LuaRocks as a lua Package (`lua5_3.withPackages(ps: [ ps.luarocks ])`)

### Expected behavior
LuaRocks to default to generating user/local configuration in `$XDG_CONFIG_HOME/luarocks/`.

### Notify maintainers

@7c6f434c  @teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[23:10:35] dch@cognac /home/dch [SIGINT] 
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.20231011.bd1cde4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(dch): `"unstable"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by teto** [comment]
xdg support is "recent" I think, postdates the nix implementation at least. I am doing a lua update so I will include this, thanks for the report.

**Comment by teto** [comment]
sry I forgot about that when merging my previous MR. To add to your first post, here is an excerpt of the generated config:
```
rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/nix/store/kc12r3m5dpb989ayhr74a3qliszl0rdk-luarocks-3.9.1" };
}
```
Turns out this is generated by upstream:
https://github.com/luarocks/luarocks/blob/4cfcf9d8df1abd7cca9f2c3590402ada543df327/GNUmakefile#L38C30-L38C34
we could work around it by adding a tree that points to the xdg folder but I would recommend opening a ticket upstream. I am not planning to do it myself but can review contributions

**Comment by teto** [comment]
Report this to luarocks if it really bothers you but note the chances of it happening is low if you dont proivde a patch. Luarocks is a bit starved in terms of maintainership
