### ISSUE TITLE
mpv crashed on macOS 14 Sonoma (aarch64-darwin)

### ISSUE THREAD

**Issue by Endle** [NixOS/nixpkgs#261072]
### Steps To Reproduce
1. add `pkgs.mpv` to `darwin-configuration.nix` then `darwin-rebuild switch`  
2. I can see `/Applications/Nix Apps/mpv.app/`  
3. I can play a video by typing in terminal `"/Applications/Nix Apps/mpv.app/Contents/MacOS/mpv" video.mp4` and it works perfect  
4. I right-clicked the video file, Get Info, Open With, select mpv, Click Change All  
5. I double-clicked the video file, the mpv player disappeared within one second  

### Additional context

[This question has been discussed at Matrix](https://matrix.to/#/!lheuhImcToQZYTQTuI:nixos.org/$ZsUQH38c1LkOph_y1Jh4yVMgekP_Pg8iwYumSl8VFeE?via=nixos.org&via=matrix.org&via=nixos.dev)

### Notify maintainers

@doronbehar

### Metadata
```
bash-3.2$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by doronbehar** [comment]
I'm sorry but I can't help to debug this, as I'm using x86_64-linux. Try to ask for help on discourse, I added the `6.topic: darwin` label. Feel free to ping me for any PR for review.

**Comment by Endle** [comment]
This is fixed by https://github.com/NixOS/nixpkgs/pull/265529

I tested the last mpv package, and it worked well
