### ISSUE TITLE
Convention for unstable package naming

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#26108]
Nixpkgs manual [says](https://nixos.org/nixpkgs/manual/#sec-package-naming):

> If a package is not a release but a commit from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also append "unstable" to the name - e.g., "pkgname-unstable-2014-09-23".

This was first added in #6539 by @jagajaga, then further refined in #17331 by @FRidh. This was enforced on `coq_HEAD` in #21822 by @rht.

I don't understand how this was chosen as the convention. In particular, I don't understand why this comment https://github.com/NixOS/nixpkgs/pull/6539#issuecomment-76030812 was not taken more into account. For software which have upcoming versions, it's better to use `"${upcoming}pre-${short commit}"` because it allows for easy comparison. `builtins.compareVersions` says: x.y < x.y.z < x.y+1pre-stuff < x.y+1, and this is pretty standard indeed.

Moreover, having the hash in the version is good for preciseness and allows to have a revision automatically picked based on the version attribute (see e.g. my update to `coq_HEAD` [here](https://github.com/Zimmi48/nixpkgs/commit/ef821469d376b395b88452318afb67ed4eaadd50#diff-f31e21359d86a923d5a2faf3601886ee)).

**Comment by fpletz** [comment]
But the short commit hashes have no order so updates with `nix-env -u` wouldn't work in some cases for two different pre versions. You would need to have a counter, for instance a commit counter like in `git describe` relative to a tag.

**Comment by Zimmi48** [comment]
@fpletz That's a good point.

**Comment by FRidh** [comment]
The only possible improvement I could see is appending a short hash to the date, but as @fpletz pointed out, we are going to need a counter like a date. @Zimmi48 do you want to discuss this further or can we close this?

**Comment by vcunat** [comment]
If you use a date, the ordering should be determined well-enough, as it seems unlikely to use two different commits from the same day.

**Comment by Zimmi48** [comment]
This issue was two-folded. Following @fpletz's comment I agree that the date of the commit should be used instead of the short hash. But I think the package naming conventions should allow for pre-release versions which are marked as such. See my proposal in #26173.

@Mic92 Can you re-open? I don't have the permissions to do it.

**Comment by Mic92** [comment]
@Zimmi48 what should I reopen?

**Comment by Zimmi48** [comment]
Closing because there is clearly no consensus to go in the direction that I proposed.
