### ISSUE TITLE
Update request:  krita 5.1.5 → krita 5.2.0

### ISSUE THREAD

**Issue by Anseryde** [NixOS/nixpkgs#261012]
- Package name: krita
- Latest released version: 5.2.0

- Current version on the unstable channel: 5.1.5
- Current version on the stable/release channel: 5.1.5

- [ ✓] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ramirez7** [comment]
I tried bumping to 5.2.0

I ran into the need for new libraries, immer lager zug: https://github.com/NixOS/nixpkgs/issues/246247

immer is in nixpkgs. zug is in PR https://github.com/NixOS/nixpkgs/pull/247777 lager isn't anywhere yet

**Comment by ramirez7** [comment]
Looks like it needs this too https://github.com/adah1972/libunibreak

**Comment by ramirez7** [comment]
I pushed a draft PR https://github.com/NixOS/nixpkgs/pull/261146, but looks like @nek0 beat me to it! https://github.com/NixOS/nixpkgs/pull/261138

**Comment by luzpaz** [comment]
Krita 5.2.1 released: https://krita.org/en/item/krita-5-2-1-released/

**Comment by luzpaz** [comment]
Krita 5.2.2 released: https://krita.org/en/item/krita-5-2-2-released/

**Comment by sifmelcara** [comment]
5.2.0 has been merged in #261138

Opened #275793 for 5.2.2
