### ISSUE TITLE
Package request: apple-color-emoji

### ISSUE THREAD

**Issue by chefnaphtha** [NixOS/nixpkgs#261100]
**Project description**

apple color emoji in ttf format, ripped and ported straight from apple's proprietary products so i'm not sure if this will actually be added

the github project hosting the port has been up for [almost 5 years at this point](https://api.github.com/repos/samuelngs/apple-emoji-linux) so i don't think apple really cares, considering [how eager they seem to be to take down projects they don't like
](https://github.com/search?q=repo%3Agithub%2Fdmca+path%3Aapple&type=code)
**Metadata**

* homepage URL: https://github.com/samuelngs/apple-emoji-linux
* source URL: https://github.com/samuelngs/apple-emoji-linux
* license: proprietary
* platforms: linux, [bsd? probably not darwin but whats the point](https://github.com/samuelngs/apple-emoji-linux/issues/12)

**Comment by eclairevoyant** [comment]
Apple's emoji set is under copyright, and they have in fact cracked down in the past: https://blog.emojipedia.org/apples-emoji-crackdown/

This should not be added to nixpkgs.

**Comment by chefnaphtha** [comment]
understandable. it is in the [AUR](https://aur.archlinux.org/packages/noto-fonts-emoji-apple) thoughever, [twice](https://aur.archlinux.org/packages/ttf-apple-emoji) even. coming from arch having installed nixos 2 days ago this makes things feel a bit more limited desu

not to be an asshole or anything senpai but the article you linked only refers to 2 (two) cases, where relatively unpopular apps got rejected from the Apple App Store®™ back in 2017 for using emojis in the app as a design element, if you can even consider it a design element

considering that snapchat, an app thats been sponsored by/was partnering with apple, one of the most popular apps of the last decade, undisputably uses emojis as a major design element, i think its more likely that it was a case of a rogue employee or some exec making some stupid decisions and reverting them later

anyways im going off topic but in my personal opinion™ i think its worth adding apple emojis to nixpkgs because it saves like 2 minutes when reinstalling a machine but its no big deal if it has to be installed manually

**Comment by eclairevoyant** [comment]
whatever happens in the AUR is immaterial here, as this is not the AUR. that is basically unmoderated user content.

**Comment by MikaelFangel** [comment]
An option could be to create your own derivation or flake in one of your own repos. This would allow you to use it declaratively (the Nix way) without imposing the potential licensing trouble on the nixpkgs repo 😇

**Comment by surfaceflinger** [comment]
What if this was done using runCommandLocal? good src would have to be figured out, maybe it's somehow possible to download fonts from apple without pulling whole macos recovery image?

**Comment by chefnaphtha** [comment]
> What if this was done using runCommandLocal? good src would have to be figured out, maybe it's somehow possible to download fonts from apple without pulling whole macos recovery image?

i'm sure apple's file servers support the Range http header so one might be able to figure out a byte offset where the font is located in the dmg file and a way to extract the font without having the entire dmg but it's way too much work for such a simple thing

**Comment by oxcl** [comment]
I wrote a flake for Apple Emojis check it out:
[https://github.com/oxcl/nix-flake-apple-emoji](https://github.com/oxcl/nix-flake-apple-emoji). It has a NixOS module and Nixpkgs overlay.

**Comment by eclairevoyant** [comment]
That overlay is wrong. You should always use the `final` nixpkgs instance to `callPackage`; don't inject a new nixpkgs instance.

Also `flake = false;` is a massive code smell, just use a regular fetcher, or `npins` to manage hashes for you...

The module is also one line and unnecessary.

**Comment by oxcl** [comment]
Thank you for your feedback. Why is flake = false a code smell?

**Comment by eclairevoyant** [comment]
It's not a flake, so don't use a flake input 😉 Flake fetching has bad performance - it's done in eval therefore single-threaded like any other built-in fetcher. There's zero reason to make it a flake input. We even ban all built-in fetchers in nixpkgs.


EDIT:
I also see `inputs.nixpkgs.url = "github:nixos/nixpkgs";` - that is pointing at `master` branch, you don't want that as nothing will be properly tested or prebuilt.

"Option 2: Use the overlay directly" is also wrong, users should be using the overlay in the `nixpkgs.overlays` option modularly, not also creating _their own_ nixpkgs instance (that would now be 3(!) nixpkgs instances for a package that just fetches a ttf file...)

**Comment by oxcl** [comment]
I mean the reason why I use it is because then I can manage updates with Nix flake update command and it is very easy

**Comment by eclairevoyant** [comment]
Use `npins` for that.
Or really, end users can just use `npins` in their own config without a need for an extra flake input 🤷 
The package could be simply using `nativeBuildInputs = [ installFonts ];` as well: https://github.com/nixos/nixpkgs/blob/master/pkgs/build-support/setup-hooks/install-fonts.sh

**Comment by oxcl** [comment]
@eclairevoyant i applied your suggestions. thank you for your feedback.

EDIT:
off topic but i also have another flake at https://github.com/oxcl/nix-flake-helium-browser
i appreciate if you could take a look at that as well. thanks
