### ISSUE TITLE
krita gmic non-functional

### ISSUE THREAD

**Issue by Anseryde** [NixOS/nixpkgs#261165]
### Describe the bug
An error occurs upon selecting gmic in filter menu within krita with an open krita document, saying that the gmic plugin was not found.

### Steps To Reproduce
1. Open Krita
2. Open new krita document
3. Open filter menu and select gmic

### Expected behavior
Gmic opens successfully

### Additional context
Another issue similar to this one was opened but seemed to be effectively dead, and I do not have the experience with nix necessary to implement the fix outlined by @sifmelcara in that issue.
(Issue #163645)

I will not have access to my Nix OS computer for a few weeks and cannot post my system's output to the bug template's info commands.

**Comment by luzpaz** [comment]
Duplicate ? Move discussion to #163645

**Comment by lelgenio** [comment]
Closing as duplicate for https://github.com/NixOS/nixpkgs/issues/163645
