### ISSUE TITLE
signal-desktop not using wayland when available

### ISSUE THREAD

**Issue by hughobrien** [NixOS/nixpkgs#261101]
If `signal-desktop` is started without args it runs under `Xwayland`, starting with the magic flags `--enable-features=UseOzonePlatform --ozone-platform=wayland` will prevent this.

Is there a way for it to determine the presence of a wayland session automatically?

https://github.com/NixOS/nixpkgs/blob/5e4c2ada4fcd54b99d56d7bd62f384511a7e2593/pkgs/applications/networking/instant-messengers/signal-desktop/generic.nix#L116

**Comment by equirosa** [comment]
We had originally disabled it in #222163 but I suppose we could test again for any changes? (given that new versions are released rather often)

**Comment by Mic92** [comment]
I recently tried signal again with native wayland but it still seems to crash after a while.

**Comment by hughobrien** [comment]
Interesting, I haven't seen that yet but certainly better to be safe. Is there a way to run it with crash logs so I can report upstream if/when it happens to me?

**Comment by hughobrien** [comment]
this appears to be resolved
