### ISSUE TITLE
haskellPackages.webify: unsatisfied dependencies

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#26122]
## Issue description

```haskellPackages.webify``` is [an old and abandoned project](https://github.com/ananthakumaran/webify) but it is used by some ```Haxe``` frameworks, where it is shipped as pre-compiled binary. Pre-compiled binary works well on Windows but on NixOS it is unable to locate some old Haskell .so (```libgmp.so.10``` and ```libffi.so.6```).

```haskellPackages.webify``` depends on old ```haskellPackages.optparse-applicative``` (``` >=0.5.2 && <0.8.0```, but there is ```0.13.2.0``` in ```nixpkgs```), which depends on some other old and missing Haskell libs, etc.

### Steps to reproduce

```nix-build -E 'with import <nixpkgs> { }; haskellPackages.webify'```

**Comment by srhb** [comment]
I really think this ought to be fixed upstream, as that version of optparse-applicative is ancient, and bumping it to a NixOS-provided version breaks it.

However, I think the required changes are trivial and I've tried to implement them here. If you could test them (I haven't, since I'm not sure of the required behaviour of the options parser,) I'll try to get them pushed upstream. Does that sound ok?

https://github.com/srhb/webify/commit/4e9fc01607326193a9361ae8451cec1a01e95961

**Comment by volth** [comment]
Thank you!

**Comment by srhb** [comment]
I've filed https://github.com/ananthakumaran/webify/pull/20
If you've experienced any problems, please let me know so I can try to fix it.

**Comment by volth** [comment]
@srhb It works well, thank you!
Until the fix is accepted by upstream, [my Haxe PR picks the patch from your repo](https://github.com/NixOS/nixpkgs/pull/25953/files#diff-a37f7b8806b9a116b14727930435520bR8), so please do delete it.

**Comment by srhb** [comment]
I am become upstream, apparently, so do you have a chance to check if everything is working with the hackage package before I cut the actual release?

http://hackage.haskell.org/package/webify-0.1.8.0/candidate

**Comment by volth** [comment]
Not actually, I tried ```hackage2nix``` once and the generated nix file appear much different than the one in nix distribution. So it would be easier to wait few days until it regenerates on the server reflecting new version of hackage, then check if ```nix-build '<nixpkgs>' -A haskellPackages.webify``` compiles

**Comment by volth** [comment]
fixed with webify update 0.1.7.0 -> 0.1.8.0 in https://github.com/NixOS/nixpkgs/commit/534a8efe170215aeb840c7e840d184de5d1b5e28
