### ISSUE TITLE
vcluster: incorrect version reported

### ISSUE THREAD

**Issue by mausch** [NixOS/nixpkgs#261373]
### Describe the bug

```
$ nix run github:nixos/nixpkgs/nixpkgs-unstable#vcluster -- version
vcluster version 0.0.1
```

Expected this to show 0.15.6 instead of 0.0.1

### Notify maintainers

@peterromfeldhk @berryp @QJoly 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0-34-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - channels(mauricio): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by shabbir-genetech** [comment]
Upon a cursory review this seems like an issue with upstream and not nixpkgs.

See the search results for 0.0.1 in upstream @ https://github.com/search?q=repo%3Aloft-sh%2Fvcluster+%2F%5B%5E.%5D0%5C.0%5C.1%5B%5E%3A%5D%2F&type=code .

**Comment by mausch** [comment]
Pretty sure it's controlled by the RELEASE_VERSION env var, which the nix package currently doesn't seem to set.
