### ISSUE TITLE
sway 1.8.1 crashed randomly on NixOs 23.11

### ISSUE THREAD

**Issue by alexandru0-dev** [NixOS/nixpkgs#261369]
### Describe the bug
Sway 1.8.1 crashed randomly, sway is installed from the nixos module enable from stable and not using home-manager or unstable repo.

### Steps To Reproduce
I don't know if it's reproducible as I only opened a terminal and crashed.

### Additional context
[Stacktrace here](https://pastebin.com/3R2RUw1Y)

### Notify maintainers
@primeos 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.4, NixOS, 23.11 (Tapir), 23.11.20230922.e35dcc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Probably not a nixpkgs issue, report it upstream only if you can reproduce it
