### ISSUE TITLE
azure-cli uses wrong dependencies

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#261386]
### Describe the bug
I hit the following bug https://github.com/Azure/azure-cli/issues/27598#issuecomment-1764108451 when using azure-cli from nixpkgs. 
When I used azure-cli from master because it had the latest 2.53 version I was surprised to see the same traceback with 
/nix/store/xxxxxx-azure-mgmt-authorization-3.0.0 as a store path when azure-mgmt-authorization is at version 4 https://github.com/NixOS/nixpkgs/blob/fb3723fe52894c49bd4b2fb92244a289d4124b1f/pkgs/development/python-modules/azure-mgmt-authorization/default.nix#L14 (and explicitly marked as such in the setup.py).
Turns out azure-mgmt-authorization is overriden with an old version here https://github.com/NixOS/nixpkgs/blob/fb3723fe52894c49bd4b2fb92244a289d4124b1f/pkgs/tools/admin/azure-cli/python-packages.nix#L310

What surprises me is that the python installer doesn't complain when the version is <4 ? 
Removing the override fixed my issue.

 @akechishiro @jonringer @mwilsoncoding

**Comment by AkechiShiro** [comment]
@teto thanks for reporting this issue, I'll remove the override and open a PR (tagging this issue), when I started maintaining the package, there were lots of those overrides, not sure if they are necessary anymore.

I'll review the other python package overrides as well, and make sure that they are not (harmful in the same way currently).
