### ISSUE TITLE
erofs-utils 1.7 is broken

### ISSUE THREAD

**Issue by nikstur** [NixOS/nixpkgs#261394]
### Describe the bug

erofs-utils is broken since 1.7.

### Steps To Reproduce

Build an filesystem image with erofs-utils 1.7 and try to access file on from a running VM.

### Expected behavior

Accessing files from a filesystem image created with erofs-utils should work.

### Additional context

This was reported first in https://github.com/NixOS/nixpkgs/pull/256937

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by blitz** [comment]
I see this when building a /nix/store image. With 1.7 I get the following. With 1.6 everything is ok.

```console
[admin@nixos:~]$ du -d1 /nix/store > /dev/null
[   24.768545] erofs: (device sda3): erofs_read_inode: bogus i_mode (0) @ nid 0
du: cannot access '/nix/store/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/Acre': Structure needs cleaning
[   24.772263] erofs: (device sda3): erofs_read_inode: bogus i_mode (0) @ nid 0
du: cannot access '/nix/store/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/DeNoronha': Structure needs cleaning
[   24.777193] erofs: (device sda3): erofs_read_inode: bogus i_mode (0) @ nid 0
du: cannot access '/nix/store/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/East': Structure needs cleaning
```

**Comment by blitz** [comment]
@ehmry @LeSuisse Should we downgrade or does upstream already have a fix we can backport?

**Comment by hsiangkao** [comment]
can you give me some dataset to reproduce it?

**Comment by blitz** [comment]
If you clone this branch: https://github.com/blitz/nixos-appliance-example/tree/erofs-borken

You can do:

```console
$ nix -L build .\#nixosConfigurations.image.config.system.build.image 
$ mkdir /tmp/erofs
$ sudo mount -t erofs result/image.linux-generic.raw /tmp/erofs
$ du -d1 /tmp/erofs > /dev/null
du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/Acre': Structure needs cleaning
du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/DeNoronha': Structure needs cleaning
du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/East': Structure needs cleaning
du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/West': Structure needs cleaning
du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Canada/Atlantic': Structure needs cleaning
...
```

This references some pretty experimental nixpkgs, so it might build a while. But none of the nixpkgs changes should be relevant to the broken erofs image.

**Comment by hsiangkao** [comment]
> If you clone this branch: https://github.com/blitz/nixos-appliance-example/tree/erofs-borken
> 
> You can do:
> 
> ```
> $ nix -L build .\#nixosConfigurations.image.config.system.build.image 
> $ mkdir /tmp/erofs
> $ sudo mount -t erofs result/image.linux-generic.raw /tmp/erofs
> $ du -d1 /tmp/erofs > /dev/null
> du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/Acre': Structure needs cleaning
> du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/DeNoronha': Structure needs cleaning
> du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/East': Structure needs cleaning
> du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Brazil/West': Structure needs cleaning
> du: cannot access '/tmp/foo/dk5vk3c9zknbjzzxmiglzv46qgv32gb0-tzdata-2023c/share/zoneinfo/Canada/Atlantic': Structure needs cleaning
> ...
> ```
> 
> This references some pretty experimental nixpkgs, so it might build a while. But none of the nixpkgs changes should be relevant to the broken erofs image.

I just also found a case to reproduce that, would you mind trying if the following patch could fix the issue?
https://lore.kernel.org/linux-erofs/20231017144420.289469-1-hsiangkao@linux.alibaba.com

I think I need to release an erofs-utils 1.7.1 to fix the issue finally.

**Comment by hsiangkao** [comment]
> @hsiangkao I can wormhole the filesystem image, if that's easier. You can ping me on Matrix: @js:ukvly.org.

I don't have Matrix, yet I think a patched erofs-utils will resolve this issue, could you help confirm this?

**Comment by nikstur** [comment]
@yu-re-ka has identified another problem: https://github.com/NixOS/nixpkgs/pull/261661#issuecomment-1766787027

**Comment by hsiangkao** [comment]
> FWIW I just hit the same error message, symptoms with erofs-utils 1.8.2 (?). My use case was using the mounted erofs dir as a lower dir for an overlay, and when I tried to do stuff on the overlay those errors appeared. Sorry, I don't have a good setup to reproduce or dig in, I had to switch to squashfs, but in case anyone else is seeing the same.
> 
> FWIW it worked (strangely) on my desktop (within an nspawn container I had granted loop device access + related capabilities, to boot) but not on the system I was deploying to, for whatever reason.

I don't have more ideas if you don't provide more informations.
IOWs, you means you can read all data by using dirs, but it failed with overlayfs?  Do I understand correctly?

**Comment by andrewbaxter** [comment]
No worries, sorry I don't have more information. No, the setup was the same (overlayfs) on both systems, it just had these errors on one.  IIRC everything I tried failed, both reading and chown.

**Comment by hsiangkao** [comment]
> No worries, sorry I don't have more information. No, the setup was the same (overlayfs) on both systems, it just had these errors on one. IIRC everything I tried failed, both reading and chown.

I mean can you read the data in the filesystem without overlayfs? does this issue only happen when working with overlayfs?
