### ISSUE TITLE
calibre broken by RPATH check

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#26140]
## Issue description

94d164dd7f introduces an RPATH check that causes `calibre` to fail to build

### Steps to reproduce

Try to rebuild `calibre`, you'll end up with the following failure:

```
[q[pchecking for references to /tmp/nix-build-calibre-2.84.0.drv-0 in /nix/store/q2q28k9y6jqx5av2kwpkhlvn080yb53q-calibre-2.84.0...
RPATH of binary /nix/store/q2q28k9y6jqx5av2kwpkhlvn080yb53q-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so contains a forbidden reference to /tmp/nix-build-calibre-2.84.0.drv-0
```

This is after the following shows up in the log:
```
[pshrinking RPATHs of ELF executables and libraries in /nix/store/q2q28k9y6jqx5av2kwpkhlvn080yb53q-calibre-2.84.0
shrinking /nix/store/q2q28k9y6jqx5av2kwpkhlvn080yb53q-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so
```

Duplicating the changes made in, say, cbdcc20e77, don't fix the issue.

@edolstra, @vcunat

**Comment by vcunat** [comment]
Well, it's not in my power to fix everything.  Let me /cc the maintainers: @viric, @domenkozar, @pSub, @AndersonTorres.

**Comment by mdorman** [comment]
This has been fixed.  Closing.
