### ISSUE TITLE
Darwin: gdb job was killed after log exceeded 64 MB

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#26145]
## Issue description

gdb on Darwin likes to output a lot it seems.

```
building of ‘/nix/store/q006jca5vxb07d9jkai6waaxsp77nf84-gdb-7.12.1’ killed after writing more than 67108864 bytes of log output
```
http://hydra.nixos.org/build/53302813

Nixpkgs master at 00672dec8a1367a1d559660aa7a125b31f3f6562

**Comment by LnL7** [comment]
Might be fixed on staging http://hydra.nixos.org/eval/1362999?filter=.x86_64-darwin&compare=1362638&full=#tabs-now-succeed

**Comment by vcunat** [comment]
Seems OK now on the very same derivation.  I suppose it was some random error that won't frequently happen.

**Comment by vcunat** [comment]
Hmm, [happened again now](http://hydra.nixos.org/build/53940203).  Perhaps the build is simply too chatty.
