### ISSUE TITLE
Some new app requests

### ISSUE THREAD

**Issue by jarry9** [NixOS/nixpkgs#26148]
Hi,

I would request some packges for nix (I could not found anywhere else to write). 

All below apps are open source and free. And all of them have both installers and both standalone packages for linux.

DOCFETCHER: Text scanner on media files (text, doc, docx, pdf...)
FIREFOX DEVELOPER EDITION: This official edition has many features for web developers
PEAZIP: The most powerfull full featured archive manager for linux
SOAPUI: SOAP Serivce test app for developers
ONBOARD: virtual screen keyboard

Thank you

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding these packages here.

**Comment by AndersonTorres** [comment]
@jarry9 : if anything, send me an e-mail!
