### ISSUE TITLE
spotify: 1.0.53.758 -> 1.0.55.487 breaking builds in 17.03 and unstable

### ISSUE THREAD

**Issue by Sophia-Gold** [NixOS/nixpkgs#26141]
It appears the change in Spotify versions from 1.0.53.758 to 1.0.55.487 committed three days ago is breaking builds. I've tested this under both NixOS 17.03 and unstable and get the following errors:

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download spotify-client_1.0.53.758.gde3fc4b2-33_amd64.deb from any mirror
builder for ‘/nix/store/8qxhs3zgr81ysk5525gk0xiwi5c8bm9l-spotify-client_1.0.53.758.gde3fc4b2-33_amd64.deb.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/b5xadif5rl3i3fd2p0sz5rl7jd2ynhmp-spotify-1.0.53.758.gde3fc4b2-33.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/5pqjfxf2l1rkqry6xgbn68ar6fzllr5b-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/dbzi8az32h8favh81fsafdrw1hvc54a8-nixos-system-nixos-17.03.1203.58e227052d.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dbzi8az32h8favh81fsafdrw1hvc54a8-nixos-system-nixos-17.03.1203.58e227052d.drv’ failed
```
* System: NixOS-17.03 _and_ NixOS-unstable
* Nix version: 1.11.8
* Nixpkgs version: 17.03.1203.58e227052d
* Sandboxing enabled: build-use-sandbox = false

**Comment by fpletz** [comment]
You're building 1.0.53.758, not 1.0.55.487. That means you don't have the update (b7290d3af5f9ea27ed4e60635bae469899e5e83e) yet. It hasn't been backported to 17.03 yet.

**Comment by fpletz** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/9f4a10220c5e1ad636440415131c92264ed3bc24.

**Comment by Sophia-Gold** [comment]
@fpletz could you please clarify? I knew a commit from three days ago wouldn't have been captured in 17.03, which is why I tried switching to unstable. Shouldn't it be included in that?
