### ISSUE TITLE
closure size: strongswan depends on GCC

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#26159]
## Issue description
This bloats the closure of networkmanager-applet.

## Technical details

- System: 17.03.1203.58e227052d (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1203.58e227052d"
- Sandboxing enabled: true

**Comment by lheckemann** [comment]
Caused, by the looks of it, by 7777b4cdbd5980bc45cf884ee7667bcd583ee562 which was added to fix #4925.

**Comment by vcunat** [comment]
`-lgcc_s` only adds `${gcc}.lib` which is < 5 MB.

**Comment by lheckemann** [comment]
Alright, not that then. My bad!

**Comment by vcunat** [comment]
`dontPatchELF = true;` leads to RPATHS not being shrinked, though I'm not sure how it gets stuff like `${gcc}/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0` into RPATH anyway.

**Comment by dezgeg** [comment]
Just for note, this is the cause of `dontPatchELF`: https://github.com/NixOS/patchelf/issues/45. Seems quite hard to fix in patchelf, most likely the package source should be checked if the export of the `lib` symbol is intentional, which I doubt it is.

**Comment by dezgeg** [comment]
Bah, there apparently is deliberately a global variable named `lib` in strongswan...

**Comment by vcunat** [comment]
It seems OK now.
```
$ nix path-info -rf. strongswan | xargs du -sc | sort -n
...
2616    /nix/store/mdm7f4mka3dqdkvj1nz8gckzzad1hqqq-iptables-1.6.2
3516    /nix/store/10lh4y4japz71ilb0yidzc9s5krhadnw-db-4.8.30
3616    /nix/store/9kr8r78bwk12050ppywfbhg1vrsd6dp8-openssl-1.0.2p
4536    /nix/store/7kg61ssbxfnqws8smp81k87ld1ir9i71-strongswan-5.6.3
5636    /nix/store/zk5zj2307zxaq7dx585yia3dn5k4qlsl-gcc-7.3.0-lib
8496    /nix/store/gj5qw8c2ji9cpa600gf1yxwcf3k89v98-openssl-1.1.0i
10772   /nix/store/wm8va53fh5158ipi0ic9gir64hrvqv1z-coreutils-8.29
26428   /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27
84184   total
```
