### ISSUE TITLE
Downgrade glibc in FHS user environment

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#26167]
## Issue description
The update to glibc 2.25 broke some programs I used to run in a environment made with `buildFHSUserEnv`. Can you override glibc in the environment to use version 2.24?
I tried adding an overridden version to the targetPkgs but /usr/lib/libc.so still points to glibc-2.25.
The only way I found was fetching an older nixpkgs version and using its `buildFHSUserEnv`.

**Comment by abbradar** [comment]
@rnhmjoj Try adding `lib.hiPrio glibc` -- does that help?

**Comment by rnhmjoj** [comment]
It causes collisions in the store:
```
collision between `/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib64/libgcc_s.so.1' and `/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib64/libgcc_s.so.1'
collision between `/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib64/libgcc_s.so' and `/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib64/libgcc_s.so'
collision between `/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib/libgcc_s.so.1' and `/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib/libgcc_s.so.1'
collision between `/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib/libgcc_s.so' and `/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib/libgcc_s.so'
collision between `/nix/store/si9s0j5cv7vnwy9wggrx4f4n286lhkmp-shadow-4.4/etc/pam.d' and `/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/pam.d'
collision between `/nix/store/si9s0j5cv7vnwy9wggrx4f4n286lhkmp-shadow-4.4/etc/login.defs' and `/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/login.defs'
collision between `/nix/store/1jqcpc9z2adzy87bjfih73ap73b2df5g-fontconfig-2.12.1/etc/fonts' and `/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/fonts'
collision between `/nix/store/3j2sqx5dmi5gpxz4m3k92r6g6xpir6al-systemd-232/etc/pam.d' and `/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/pam.d'
```
and running the environment in nix-shell gives this error
```
bash: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
```

**Comment by abbradar** [comment]
Uh-oh, that's because new glibc is very incompatible it seems. I don't think anything short of using old nixpkgs can help then (but admittedly I didn't think hard enough). 

On May 28, 2017 2:59:23 PM GMT+03:00, Michele Guerini Rocco <notifications@github.com> wrote:
>It causes collisions in the store:
>```
>collision between
>`/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib64/libgcc_s.so.1'
>and
>`/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib64/libgcc_s.so.1'
>collision between
>`/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib64/libgcc_s.so'
>and
>`/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib64/libgcc_s.so'
>collision between
>`/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib/libgcc_s.so.1'
>and
>`/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib/libgcc_s.so.1'
>collision between
>`/nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib/libgcc_s.so'
>and
>`/nix/store/j9cmbxgfzm949wid3xxy8307z8qzfb7y-glibc-multi-2.25/lib/libgcc_s.so'
>collision between
>`/nix/store/si9s0j5cv7vnwy9wggrx4f4n286lhkmp-shadow-4.4/etc/pam.d' and
>`/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/pam.d'
>collision between
>`/nix/store/si9s0j5cv7vnwy9wggrx4f4n286lhkmp-shadow-4.4/etc/login.defs'
>and
>`/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/login.defs'
>collision between
>`/nix/store/1jqcpc9z2adzy87bjfih73ap73b2df5g-fontconfig-2.12.1/etc/fonts'
>and
>`/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/fonts'
>collision between
>`/nix/store/3j2sqx5dmi5gpxz4m3k92r6g6xpir6al-systemd-232/etc/pam.d' and
>`/nix/store/6cxcanndk2gwczg0brdp3fw9j7x5nrry-game-chrootenv-etc/etc/pam.d'
>```
>and running the environment in nix-shell gives this error
>```
>bash: error while loading shared libraries: __vdso_time: invalid mode
>for dlopen(): Invalid argument
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/issues/26167#issuecomment-304509344

-- 
Nikolay.

**Comment by rnhmjoj** [comment]
Thanks anyway. This will do for a while.

**Comment by vcunat** [comment]
You probably unintentionally created a mixup of several glibc versions in one running process.  This might help to explain but I don't know any details: https://stackoverflow.com/a/13675167/587396

**Comment by rnhmjoj** [comment]
Now this is becoming problematic. After a channel update I'm getting:
```
/usr/lib/libc.so.6: version `GLIBC_2.25' not found (required by /nix/store/hfxg6wnh0vm1vybn6973yfskwf55ih2m-expat-2.2.1/lib/libexpat.so.1)
```

It means I must be doing something wrong as I thought nothing depending on the newer libc could have been pulled in. This is (part) of the expression I'm using.
```nix
{ pkgs ? import <nixpkgs> {} }:

let
  pkgsOld = import (pkgs.fetchFromGitHub {
    owner  = "NixOS";
    repo   = "nixpkgs-channels";
    rev    = "55cc7700e968001c9ac79190fbcf25ed3620680a";
    sha256 = "0mpg08hzgzp0ncr3z741w9sb9chi0xc70pshyv34zazgjk13nn4k";
  }) {};

  deps = pkgs:
  with pkgs;
  with pkgs.xorg; [
    alsaLib udev freetype fontconfig
    glib cairo pango gtk2 gdk_pixbuf
    zlib xdg_utils SDL2 mesa_glu openal
    libSM libpng12 libogg curl
    libnghttp2 libssh2 openssl 
    libX11 libXxf86vm libXcursor
    libXft libXrandr libXext 
    libXi libXinerama
  ];

  fhs = {
    name = "sandbox";
    multiPkgs = deps; 
    runScript = ''
      #!${pkgs.stdenv.shell}
      exec "$1" "''${@:2}"
    '';
  };

in pkgsOld.buildFHSUserEnv fhs
```

**Comment by aeat** [comment]
is this issue related to 
https://stackoverflow.com/questions/50725596/ubuntu-18-nixpkgs-conda-relocation-error-libc-so-6-symbol-dl-exception-create ?

**Comment by Shados** [comment]
@rnhmjoj I don't know if it's the cause of your issue, but your `runScript` definition is using the top-level (new) `pkgs`, not the one provided to the `FHSUserEnv`. I'd suggest calling either the top-level `pkgs` or the one used in the `multiPkgs` function something else -- shadowing variable names is always a problem just waiting to happen.

**Comment by rnhmjoj** [comment]
@Shados thank you, fortunately the bug introduced in glibc 2.25 has been fixed for a while.

**Comment by jonringer** [comment]
@rnhmjoj do you mind closing this if it's no longer relevant?

**Comment by rnhmjoj** [comment]
Yeah, sure.
