### ISSUE TITLE
Update request: python311Packages.openrazer 3.5.1 → 3.6.1

### ISSUE THREAD

**Issue by Jackaed** [NixOS/nixpkgs#261639]
- Package name: python311Packgaes.openrazer
- Latest released version: 3.6.1

- Current version on the unstable channel: 3.5.1
- Current version on the stable/release channel: 3.5.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----
@evanjs 
@roelvandijk 
@Lucus16 

Last update pull request was made by: @SuperSandro2000 
Note for maintainers: Please tag this issue in your PR.

**Comment by SuperSandro2000** [comment]
#264068
