### ISSUE TITLE
Running nixos-rebuild switching from systemd-run breaks LXC containers due to missing `ln` on $PATH

### ISSUE THREAD

**Issue by josephst** [NixOS/nixpkgs#261691]
### Describe the bug
A recent change introduced `systemd-run` (https://github.com/NixOS/nixpkgs/pull/258571) which runs `nixos-rebuild switch` by using systemd-run. This brings with it better isolation of the new system/ a cleaner execution environment, although the new environment appears to be lacking most/all of `$PATH` from the currently running system. This means that the `ln` command in [`install-lxd-sbin-init.sh`](https://github.com/NixOS/nixpkgs/blob/caf5ba6d92d748f683cc7b4176c55cc7b760c15d/nixos/modules/virtualisation/lxc-container.nix#L67C56-L67C80) cannot be found when the script is run inside of systemd-run. 

This has been breaking my NixOS install within OrbStack. I've been able to fix the problem by including the absolute path to `ln` (ie `${pkgs.coreutils}/bin/ln`); PR coming shortly. 

### Steps To Reproduce
1. Within LXD container: run `nixos-rebuild switch`

Error message: 
```
/nix/store/37l6gd92za7p3ldikmpx3k8xkxcfd44p-install-lxd-sbin-init.sh: line 2: ln: command not found
warning: error(s) occurred while switching to the new configuration
```

### Expected behavior
Should switch to new system configuration without errors

### Additional context
Content of `/nix/store/37l6gd92za7p3ldikmpx3k8xkxcfd44p-install-lxd-sbin-init.sh`
```
#!/nix/store/4qp96hwq3wqkqhv99m76g2rp8sdjcl4v-bash-5.2-p15/bin/bash
ln -fs "$1/init" /sbin/init
```

Command producing error: 
```
sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER -- systemd-run -E LOCALE_ARCHIVE --collect --no-ask-password --pty --quiet --same-dir --service-type=exec --unit=nixos-rebuild-switch-to-configuration --wait /nix/store/baq0plc2bz9brs7608snz4kx57955pv7-nixos-system-nixos-orbstack-23.11.20231015.12bdeb0/bin/switch-to-configuration switch
```

### Notify maintainers

@aanderse 
@mkg20001 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.5.7-orbstack-00109-gd8500ae6683d, NixOS, 23.11 (Tapir), 23.11.20231017.3d9a893`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.05.4335.898cb2064b6e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Samuel-Martineau** [comment]
@josephst I am also affected by this issue. Could you tell me how you fixed it locally? I saw the change you made in your pull request, but I am new to NixOS and am unsure of how to apply a local path…
