### ISSUE TITLE
python36.pkgs.simplejson build fails on macOS

### ISSUE THREAD

**Issue by KentJames** [NixOS/nixpkgs#26171]
## Issue description

matplotlib-2.0.2 gets about halfway through its build and fails an assertion test due to floating point rounding error. 

All other tests are completely fine up until then. Unfortunately I simply don't know how to override the test in this case. 

`packageOverrides = pkgs: with pkgs; {
    myPythonEnv = python36.withPackages(ps: with ps; [numpy astropy ipython scipy cython matplotlib]);

};`

### Steps to reproduce

Build matplotlib or specify it as input to python35/python36 build.

## Technical details

* System: macOS Sierra 10.12.5
* Nix version: nix-1.11.7
* Nixpkgs version: "17.09pre108026.7596d21f69"
* Sandboxing enabled: No

**Comment by FRidh** [comment]
can you tell which exact test it is?

**Comment by FRidh** [comment]
All tests run on NixOS with 3.6.

**Comment by KentJames** [comment]
Sorry for the command line dump, but here is the terminal output:

`post-installation fixup
stripping (with flags -S) in /nix/store/gx8zd4g78rm7zqymwj45c68j1kbg2j2x-python3.6-simplejson-3.8.1/lib
patching script interpreter paths in /nix/store/gx8zd4g78rm7zqymwj45c68j1kbg2j2x-python3.6-simplejson-3.8.1
running install tests
running test
/nix/store/y3w8qnkn9py20lb8kpipn0pr440h5zgp-python3.6-setuptools-30.2.0/lib/python3.6/site-packages/site.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp  # Avoid import loop in Python >= 3.3
...................................................F.................ss...................................................s
======================================================================
FAIL: test_floats (simplejson.tests.test_float.TestFloat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/by/mw_ml3rx2hg25s45hc_j5_fm0000gn/T/nix-build-python3.6-simplejson-3.8.1.drv-0/simplejson-3.8.1/simplejson/tests/test_float.py", line 26, in test_floats
    self.assertEqual(float(json.dumps(num)), num)
AssertionError: 1.9275814160560202e-50 != 1.9275814160560206e-50

----------------------------------------------------------------------
Ran 123 tests in 1.242s

FAILED (failures=1, skipped=3)
builder for ‘/nix/store/9w27l8pkp69rg1d9crc3jc3kycyi8ky2-python3.6-simplejson-3.8.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/pi8sjx92sfngaiw3rl6f4pwda543ajgi-python3.6-Sphinx-1.5.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/gmkdmmmf8hgnc6hziva1bz0lkna765yi-python3.6-matplotlib-2.0.0.drv’: 1 dependencies couldn't bebuilt
cannot build derivation ‘/nix/store/yssxvk459qx8crc340nwzx0c0q67spn3-python3-3.6.1-env.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/yssxvk459qx8crc340nwzx0c0q67spn3-python3-3.6.1-env.drv’ failed`


It's simple floating point rounding error, I'm just not sure how I can override this test.

**Comment by KentJames** [comment]
Here is the terminal dump:


'''
 post-installation fixup
stripping (with flags -S) in /nix/store/gx8zd4g78rm7zqymwj45c68j1kbg2j2x-python3.6-simplejson-3.8.1/lib
patching script interpreter paths in /nix/store/gx8zd4g78rm7zqymwj45c68j1kbg2j2x-python3.6-simplejson-3.8.1
running install tests
running test
/nix/store/y3w8qnkn9py20lb8kpipn0pr440h5zgp-python3.6-setuptools-30.2.0/lib/python3.6/site-packages/site.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp  # Avoid import loop in Python >= 3.3
...................................................F.................ss...................................................s
======================================================================
FAIL: test_floats (simplejson.tests.test_float.TestFloat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/folders/by/mw_ml3rx2hg25s45hc_j5_fm0000gn/T/nix-build-python3.6-simplejson-3.8.1.drv-0/simplejson-3.8.1/simplejson/tests/test_float.py", line 26, in test_floats
    self.assertEqual(float(json.dumps(num)), num)
AssertionError: 1.9275814160560202e-50 != 1.9275814160560206e-50

----------------------------------------------------------------------
Ran 123 tests in 1.242s

FAILED (failures=1, skipped=3)
builder for ‘/nix/store/9w27l8pkp69rg1d9crc3jc3kycyi8ky2-python3.6-simplejson-3.8.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/pi8sjx92sfngaiw3rl6f4pwda543ajgi-python3.6-Sphinx-1.5.2.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/gmkdmmmf8hgnc6hziva1bz0lkna765yi-python3.6-matplotlib-2.0.0.drv’: 1 dependencies couldn't bebuilt
cannot build derivation ‘/nix/store/yssxvk459qx8crc340nwzx0c0q67spn3-python3-3.6.1-env.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/yssxvk459qx8crc340nwzx0c0q67spn3-python3-3.6.1-env.drv’ failed
'''

It just looks like standard floating point rounding error to me.

**Comment by FRidh** [comment]
can you try with https://github.com/NixOS/nixpkgs/commit/d0f2361bc1ffdff631fc7ebb9c2ec1b08b135898?

**Comment by KentJames** [comment]
I did, and unfortunately it doesn't work :( 

Looks like this might be an upstream issue for SimpleJson on Darwin? Which is a major pain in ass if it is. 

I think cython has a dodgy unit test on darwin too, and you are able to run a hook that pulls the wrong result out and subs a dummy one in to get it to finish and build successfully. Unfortunately that is way beyond my knowledge of nix.

**Comment by FRidh** [comment]
I can imagine upstream doesn't test on Darwin as much. I recommend you report the issues upstream. For here in Nixpkgs you could
- report the issues and, even better, try to fix them
- discuss with Darwin maintainers about possibly disabling tests altogether, though that should be an absolute last resort.

**Comment by KentJames** [comment]
Yeah I guess I'll fix it, but I think this issue should be closed until I can generate a PR and useful commit.

**Comment by KentJames** [comment]
Okay so I've been looking into this more now. The source downloaded and installed manually sans-Nix  perfectly fine. It also builds fine. Something about the nix build step is causing a tiny floating point error which is throwing off the test. 

Is there a hook to selectively disable the tests for just this module? Disabling all tests on Darwin I feel is far too hamfisted.

I re-built it in an isolated as possible system and no change unfortunately. I am not sure if its a problem with my specific nix install but I doubt it. I'd be interested to hear if anyone has had this problem, because this breaks a load of pretty popular packages on Darwin.

But if its built outside of nix, then there is seemingly no problem. Which is weird.

**Comment by FRidh** [comment]
Pass `doCheck = !stdenv.isDarwin;`

**Comment by KentJames** [comment]
Okay that seems to work, Pr submitted. #26405
