### ISSUE TITLE
Systemd Bootstrap Complexity

### ISSUE THREAD

**Issue by blitz** [NixOS/nixpkgs#261795]
### Describe the bug

systemd depends on libraries (e.g. libfido2) which in turn depend on systemd. This cycle is currently broken by using `systemdMinimal`, a systemd version with all optional dependencies disabled. This has these problems:

- people have to manually opt-in to `systemdMinimal` when they need udev or libsystemd or risk a dependency cycle
- people misuse `systemdMinimal` to get a minimal systemd (which it is not really intended)
- everyone gets two copies of systemd binaries and libraries in their system closure wasting 10-15 MiB.

@RaitoBezarius suggested that this could use a real bootstrap flow. Another solution would be to split building systemd libraries into a separate derivation. One wrinkle here is that libsystemd.so seems to hardcode the systemd `bin/` path...

### Notify maintainers

@RaitoBezarius @flokli @Mic92 @Kloenk

**Comment by flokli** [comment]
@blitz do you think this is sufficiently solved by https://github.com/NixOS/nixpkgs/pull/261798, or what'd be the next steps?

**Comment by blitz** [comment]
> @blitz do you think this is sufficiently solved by #261798, or what'd be the next steps?

I think it's good enough for now.
