### ISSUE TITLE
Package request: Thorium-browser

### ISSUE THREAD

**Issue by xkkx3** [NixOS/nixpkgs#261700]
**Project description**

It's a super fast chromium-based browser. Apparently, it's the fastest browser out there.

**Metadata**

* homepage URL: https://thorium.rocks/
* source URL: https://github.com/Alex313031/thorium
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by SoftwareRat** [comment]
It must be added to NixOS immediately

**Comment by eclairevoyant** [comment]
duplicate of #184823
