### ISSUE TITLE
Support initrd secrets in GRUB

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#26175]
## Issue description

Ditto. I have noticed this accidentially whily working at #26165.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 65477dcd341dcdcdc58b01e362e18a903bf94874

cc @shlevy

**Comment by symphorien** [comment]
You can puts secrets in an additionnal initrd readable by root only, and use `boot.loader.grub.extraInitrd`
See https://github.com/NixOS/nixpkgs/pull/22969

**Comment by abbradar** [comment]
There is more generic option now, `boot.initrd.secrets`. We probably want to merge those.
