### ISSUE TITLE
Package request: presenterm

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#261897]
**Project description**

A terminal based slideshow tool.

**Metadata**

* homepage URL: https://github.com/mfontanini/presenterm
* source URL: https://github.com/mfontanini/presenterm
* license: bsd 2 clause
* platforms: unix, linux

---

CC: @minijackson

**Comment by MikaelFangel** [comment]
@pacien You can follow the status of the pr/package [here](https://nixpk.gs/pr-tracker.html?pr=261909)

**Comment by andsnap** [comment]
Please include presenterm-export as well, or a new presenterm-export package

https://mfontanini.github.io/presenterm/guides/pdf-export.html
https://github.com/mfontanini/presenterm-export
