### ISSUE TITLE
Update request: adw-gtk3 4.9 → 5.1

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#261826]
- Package name: adw-gtk3
- Latest released version: 5.1

- Current version on the unstable channel: 4.9
- Current version on the stable/release channel: 4.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ciferkey 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ciferkey** [comment]
Thanks for opening this. Going to bump to 5.1 since that's now latest. [PR](https://github.com/NixOS/nixpkgs/pull/262288).

**Comment by ciferkey** [comment]
This merged and now [almost](https://nixpk.gs/pr-tracker.html?pr=262288) in unstable.

**Comment by ciferkey** [comment]
Merged now.
