### ISSUE TITLE
Can't open gnome-tweak-tool on Arch Linux.

### ISSUE THREAD

**Issue by kvenixcs** [NixOS/nixpkgs#26193]
## Issue description

Can't open gnome-tweak-tool.

Tested on arch-linux, kernel:
ArchLinux 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux

### Steps to reproduce

Just open it in the shell.

## Technical details

Full log:

DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.shell>
DEBUG   : Shell version: [3, 22, 2]
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.shell.overrides>
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.desktop.input-sources>
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.desktop.interface>
DEBUG   : Schema not translated org.gnome.mutter (domain: @GETTEXT_DOMAIN)
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.mutter>
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.desktop.peripherals.mouse>
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.settings-daemon.peripherals.mouse>
INFO    : GSettings missing key org.gnome.desktop.interface (key gtk-enable-primary-paste)
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.desktop.peripherals.touchpad>

(gnome-tweak-tool:32548): GLib-GIO-ERROR **: Settings schema 'org.gnome.shell' does not contain a key named 'disable-user-extensions'
Trace/breakpoint trap (imagem do núcleo gravada)

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by vkomodey** [comment]
The same.
Distro - manjaro gnome 17.0

**Comment by Tristan971** [comment]
Same on gnome 3.26.0 on Debian Sid

**Comment by bric3** [comment]
```
➜  ~ gnome-tweak-tool -d
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Schema not translated org.gnome.shell (domain: gnome-shell)
DEBUG   : Caching gsettings: <gtweak.gsettings._GSettingsSchema: org.gnome.shell>
DEBUG   : Shell version: [3, 26, 1]
```

**Comment by jgeerds** [comment]
I can't reproduce this issue. Could you please check if the error still occurs?

(I'm on Debian testing with "18.03pre128510.c64639b54ca")

**Comment by bric3** [comment]
Indeed this appear fixed for me. 

GNOME Tweaks 3.26.4
GNOME Shell 3.26.2
GTK+ 3.22.28

**Comment by jtojnar** [comment]
Re-open if still an issue.
