### ISSUE TITLE
No way to set network broadcast address from config

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#26196]
I'm having difficulties doing a manual network setup from a configuration file.
I need to set the broadcast address manually on a network interface but I cannot seem to find a valid way to do so from a config file.
I've tried networking.dhcpcd.extraConfig = ''
  option broadcast-address 12.34.56.789
'';
But it doesn't make a difference when I run ifconfig -a, the broadcast address is still just 0.0.0.0.

Can someone with more experience tell me what I'm doing wrong?

**Comment by ob7** [comment]
Ended up using:
```
networking.localCommands = ''
ifconfig eth0 broadcast 192.some.ip.address
'';
```

**Comment by bledari** [comment]
Why did you close this? 

Doing:
networking.localCommands = ''
ifconfig eth0 broadcast 192.some.ip.address
'';

is not the nix way. This should be a feature request I guess
