### ISSUE TITLE
Build failure: OctoPrint (FOD hash mismatch)

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#261934]
### Steps To Reproduce

1. `nix build nixpkgs#octoprint`

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/dnij0v1c6gf63j8ff7dc485yi01xgj0w-source.drv':
         specified: sha256-SYN/BrcukHMDwk70XGu/pO45fSPr/KOEyd4wxtz2Fo0=
            got:    sha256-71uE8JvcS++xH8WSVWj5x0+9s3XIwf3A64c6YtxpSRc=
error: 1 dependencies of derivation '/nix/store/8g2cxkmq1jk6v638lhf684zxzr46imak-python3.10-OctoPrint-1.9.3.drv' failed to build
```

### Additional context

`nix-prefetch-github OctoPrint OctoPrint --rev 1.9.3` also yields the "got" hash.

The hash was last changed in https://github.com/NixOS/nixpkgs/pull/260583.

### Notify maintainers

@NickCao @abbradar @gebner @WhittlesJr @gador 

### Metadata

nixpkgs @ 1ae1ab8d01d53806bfaf96beddd86776d9cd205e

**Comment by ptrcnull** [comment]
we just hit the same issue in Alpine - it looks like the upstream uses format specifiers for `git-archive` that change depending on the state of the repo: https://github.com/OctoPrint/OctoPrint/blob/dfe289304943b9622605edb49e245a3f22d9ceae/src/octoprint/_version.py#L22-L26 (found by @selfisekai [here][1])

in your case it might help to do `fetchgit` instead ( provided that doesn't just do `git-archive` on the remote URL, but fetches the repo in some other way ):
> `fetchFromGitHub` uses `fetchzip` to download the source archive generated by GitHub for the specified revision. If `leaveDotGit`, `deepClone` or `fetchSubmodules` are set to true, `fetchFromGitHub` will use `fetchgit` instead. Refer to its section for documentation of these options.

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/55652#note_355277

**Comment by gador** [comment]
@ptrcnull thanks for the new upstream issue and the infos!
