### ISSUE TITLE
Rambox is crashing on start

### ISSUE THREAD

**Issue by SimonBrandner** [NixOS/nixpkgs#261988]
### Describe the bug

rambox crashes when started with

```
Gtk-Message: 09:25:01.159: Failed to load module "appmenu-gtk-module"
Widevine Content Decryption Module v4.10.2557.0 is ready to be used!
Error Command failed: ps awwxo pid,ppid
*** stack smashing detected ***: terminated
```

### Steps To Reproduce
1. Start `rambox`

### Expected behavior
The app to launch without problems

### Notify maintainers

@nazarewk

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4392.b5f8ec6be261`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jceb** [comment]
@nazarewk have you seen the behavior, too? I run into in on the unstable channel while the 23.05. channel is still working fine .. apart from the fact that version 2.1.5 in the 23.05. channel is not supported anymore.

**Comment by nazarewk** [comment]
works perfectly fine for me on both Sway and Plasma Wayland sessions on 2 different amd-based machines (both cpus and gpus)

**Comment by jceb** [comment]
Ah, I just found a workaround. I added this line to the `wrapType2` call:

```
extraPkgs = pkgs: with pkgs; [ procps ];
```

**Comment by jceb** [comment]
Not sure why this works works and not for us. Do you think you can integrate the additional package?

**Comment by SimonBrandner** [comment]
> Ah, I just found a workaround. I added this line to the `wrapType2` call:
> 
> ```
> extraPkgs = pkgs: with pkgs; [ procps ];
> ```

@jceb, sorry I am not sure if I 100% follow what you did? Where did you add this? Could you elaborate, please?

**Comment by jceb** [comment]
^^ Yay, that's it! Thank you!
