### ISSUE TITLE
Build failure: linuxKernel.kernels.linux_testing_bcachefs

### ISSUE THREAD

**Issue by catleeball** [NixOS/nixpkgs#261936]
### Steps To Reproduce

1. `nix-shell -p linuxKernel.kernels.linux_testing_bcachefs &> build.log`
2. Build errors occur when trying to build `drivers/misc/cardreader/rts*`

### Build log

- https://gist.github.com/catleeball/34211c28ae81705f0fd987593aa3473d#file-build-log
- https://gist.github.com/catleeball/34211c28ae81705f0fd987593aa3473d#file-full-log

### Additional context

This same error occurs when building things like `nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-minimal-new-kernel-no-zfs.nix`

### Notify maintainers

@davidak
@Madouura 
@PedroHLC 
@RaitoBezarius

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.4335.898cb2064b6e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(cat): `"nixos-23.05-23.05, nixos-unstable"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Thank you! :)

**Comment by Madouura** [comment]
IIRC, this is due to this patch: https://github.com/NixOS/nixpkgs/blob/4e1a54c1ae99ca42cdd2d0d6227377fa03d0ab15/pkgs/top-level/linux-kernels.nix#L216

**Comment by JohnRTitor** [comment]
Closing as linux_testing_bcachefs has been deprecated in since the release of 6.7 kernel. https://github.com/NixOS/nixpkgs/pull/279852
