### ISSUE TITLE
update mariadb to 10.2

### ISSUE THREAD

**Issue by florianjacob** [NixOS/nixpkgs#26194]
## Issue description

I noticed mariadb is still on 10.1 because the `ALTER USER` command was not present. 10.2.6 is the current stable release.

Just updating the version and hash leads to this, though:
```
patching script interpreter paths in /nix/store/s34qz0rmdpbfdi0zj3pbqmi0w98snl48-mariadb-client-10.2.6
cycle detected in the references of ‘/nix/store/ljzyb4gfy5878zfgczz3n8v4r7bxj1d5-mariadb-client-10.2.6-bin’
```

An Arch Linux mailinglist post for the switch to 10.2.6 said this, maybe that's the cause, but I don't know whether that's Arch Linux-specific:

> The main change is the library rename from `libmysqlclient.so` to `libmariadb.so`.

@vcunat, maybe you know what's going on here?

**Comment by vcunat** [comment]
I don't know a better way to investigate this than to build with `--keep-failed` and grepping for the hashes to see what causes the reference cycles.

**Comment by florianjacob** [comment]
@vcunat Thank you, found the cycle this way. 👍

Seems like I'm now at the libmysqlclient -> libmariadb problem, building php fails because
```
checking for mysql_set_server_option in -lmysqlclient... no
configure: error: wrong mysql library version or lib not found. Check config.log for more information.
```

I'm quite sure this is because `ext/mysqli/config.m4` from php hardcodes the name:
```
MYSQL_LIB_NAME='mysqlclient'
…
PHP_CHECK_LIBRARY($MYSQL_LIB_NAME, mysql_set_character_set, …
```

Arch will probably go with a symlink for compatibility: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/mariadb&id=fed4e31a80c781e31d8691064e73196ac6731d68

**Comment by florianjacob** [comment]
My current code with resolved cycle is at https://github.com/florianjacob/nixpkgs/tree/mariadb-update

@thoughtpolice @wkennington what do you think regarding the `mysqlclient.so ` rename?

**Comment by florianjacob** [comment]
Will be resolved by https://github.com/NixOS/nixpkgs/pull/30546

**Comment by thoughtpolice** [comment]
This is now fixed, and can be closed.
