### ISSUE TITLE
Package request: phpExtensions.php-systemd

### ISSUE THREAD

**Issue by flandweber** [NixOS/nixpkgs#262142]
Needed for logging to systemd journal on nextcloud (`services.nextcloud.logType = "systemd"`): 
`nextcloud-setup-start[30889]: OCP\HintException: [0]: PHP extension php-systemd is not available. (Please install and enable PHP extension systemd if you wish to log to the Systemd journal.)`

**Metadata**

* homepage URL: -
* source URL: https://github.com/systemd/php-systemd
* license: mit
* platforms: linux, ...?

**Comment by SuperSandro2000** [comment]
There should be a PR around already and what you are trying is not working, tested it myself. Seems to be the integration is rotted upstream and only file really works with the logreader app.

**Comment by dbrgn** [comment]
Check out the option description: https://github.com/NixOS/nixpkgs/blob/fac16fbfae144461f41accc3455682e052e6ce49/nixos/modules/services/web-apps/nextcloud.nix#L179-L186

I haven't tested this myself, but configuring `services.nextcloud.phpExtraExtensions` might help.

**Comment by SuperSandro2000** [comment]
I did that, it still didn't work properly.

**Comment by matthiasbeyer** [comment]
@flandweber can you please share how this issue is solved for you?

**Comment by flandweber** [comment]
I didn't. I simply thought if upstream is broken there's currently no point in packaging php-systemd.
Would you like me to reopen?

**Comment by matthiasbeyer** [comment]
Hm... is there a upstream bugreport we can link to? I think many users might stumble over this issue here... at least I did when I tried to get nextcloud to log to systemd.

**Comment by pinpox** [comment]
Just stumbled over this. Maybe we should remove the "systemd" option for the log_type setting if this is not going to be fixed?

**Comment by drupol** [comment]
Closing for https://github.com/NixOS/nixpkgs/issues/262142#issuecomment-1962071947

**Comment by float3** [comment]
> Just stumbled over this. Maybe we should remove the "systemd" option for the log_type setting if this is not going to be fixed?

at least this needs to be reflected somewhere

**Comment by lukasngl** [comment]
I just packaged "php-systemd" in #416733 and successfully tested it with my nextcloud instance.

Instead of removing the "systemd" variant from the "log_type" option, we could add the extension if set: #416735.
