### ISSUE TITLE
Python attempts to import incorrect script because of wrappGapps rename

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#26225]
## Issue description

The issue with seems to be related to Relating to an application I am trying to package: [onboard](https://github.com/NixOS/nixpkgs/pull/24986).

The file sokSettings.py is being wrapped. I'm using wrapGAppsHook and the program wants to import a module but it is importing the bash script wrapper which actually calls the module, instead of importing the Python module. Does anyone know if there is a way to exclude certain files with the wrappers?

---

When the Python script attempts to import sokSettings.py the following happens:

```
python3 -c "import scripts.sokSettings; scripts.sokSettings.run()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/5cwnb0da5rjm9ni4pf1fg7i2ng6k5c8j-onboard-1.4.1/share/onboard/scripts/sokSettings.py", line 2
    export PATH=/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/bin:/nix/store/5cwnb0da5rjm9ni4pf1fg7i2ng6k5c8j-onboard-1.4.1/bin:/nix/store/63spjx86svppz695s5yy7mh2h6lbbca1-gtk+3-3.22.8-dev/bin:/nix/store/k6bmqyh6yf8pzrhnfbzkqdrb3g0hb5gj-expat-2.2.0-dev/bin:/nix/store/pmp2ysvnrmcfzdjmaqnyhda96zkf2z6f-glib-2.50.3-dev/bin:/nix/store/8xm32qg4xi1l41zng4xv752492h6wmdp-cairo-1.14.8-dev/bin:/nix/store/dg3c94l36n3zmrpq9p9qyfi6407rhv5f-freetype-2.6.5-dev/bin:/nix/store/6fc4ak60p1mnilrjfcyz0sywwmpmf45w-bzip2-1.0.6.0.1-bin/bin:/nix/store/j8japwvk2qq8wf9yddibs4fnp99hskkw-libpng-apng-1.6.28-dev/bin:/nix/store/fsqw38ydj8wfj606rzkdcb3rrmpnhb4q-fontconfig-2.12.1-bin/bin:/nix/store/3hz3ll4ikznx3b6cd3myvrm5i79kyj8y-harfbuzz-1.4.2-dev/bin:/nix/store/pr6x655sz1n1sqjhch2i64h5l8i48xrm-graphite2-1.3.6/bin:/nix/store/7wc7qlqg7vsbav3vrjmkfbjbxpp9nnpr-pango-1.40.3-bin/bin:/nix/store/mrzs48prbr7aync14ns4l2j2s489sx50-gdk-pixbuf-2.36.5-dev/bin:/nix/store/sqxw6zlqy91y5nhl4smr5smixkqhdr1k-libjpeg-turbo-1.5.1-bin/bin:/nix/store/s2hmf51bprsxb20v3bfigs8a7zsw3hjl-xz-5.2.2-bin/bin:/nix/store/i14lfjn7cgfmghak3hqczmd90dymsbaj-libtiff-4.0.7-bin/bin:/nix/store/8iavg1dpbz7w9lqgv35q0a6hdkr0gpxi-jasper-2.0.12-bin/bin:/nix/store/pj75dhcgcnnv7ws860bs2zf23hzk2bjz-gdk-pixbuf-2.36.5/bin:/nix/store/qja3mjgiz9c7ld1ddffgc7b487mv1zmh-gobject-introspection-1.50.0-dev/bin:/nix/store/6l6kkkvbz9nxc7pi8m4wcq0z60bmp74a-wayland-1.12.0/bin:/nix/store/q5l53jgm2crfih93l56lcl8mxjywygs9-cups-2.1.4-dev/bin:/nix/store/3gi4zw66q73hdal18akrca30rf02zblq-cups-2.1.4/bin:/nix/store/bx1091kbmwff89gmmxy3za426ryxg0jm-gtk+3-3.22.8/bin:/nix/store/2byhribnzhiy7zhp838fc833xdhnl5l8-dconf-0.26.0/bin:/nix/store/iwm7yk3a40wn400wlqv0rx0zhc7rk756-libcanberra-0.30/bin:/nix/store/px7a1kq4prjzw17c9pppssdmibqqdm2p-systemd-232/bin:/nix/store/fi3mbd2ml4pbgzyasrlnp0wyy6qi48fh-bash-4.4-p5/bin:/nix/store/nqini3ad62zhsknqdpsjcgcm68d1n4gl-hunspell-1.3.3-bin/bin:/nix/store/q2djjbafrmarpv3iqc6scqnsxrdlqxvb-pkg-config-0.29/bin:/nix/store/0l73r9z7q5zjyvghnkd9wm8bihf9gg2p-intltool-0.51.0/bin:/nix/store/lkdr3z34n6n17g7xiaw8plyw7hv9idsl-gettext-0.19.8/bin:/nix/store/nsa311yg8h93wfaacjk16c96a98bs09f-perl-5.22.3/bin:/nix/store/4yn2vyzz1mwl9ry9l67y9bmyasjp7jrj-python3.5-setuptools-30.2.0/bin:/nix/store/087w6yxwq3skp2zppahq8dvfa2idckv7-librsvg-2.40.16/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax
```

This is what it should be importing:

```
cat share/onboard/scripts/.sokSettings.py-wrapped
#!/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/bin/python3

import sys;import site;import functools;sys.argv[0] = '/nix/store/5cwnb0da5rjm9ni4pf1fg7i2ng6k5c8j-onboard-1.4.1/share/onboard/scripts/sokSettings.py';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/5cwnb0da5rjm9ni4pf1fg7i2ng6k5c8j-onboard-1.4.1/lib/python3.5/site-packages','/nix/store/fs8cxcjdm2zf8arxmbva7k742n7mkklm-python3.5-pycairo-1.10.0/lib/python3.5/site-packages','/nix/store/4yn2vyzz1mwl9ry9l67y9bmyasjp7jrj-python3.5-setuptools-30.2.0/lib/python3.5/site-packages','/nix/store/7kfnj63b4pav99zgq24cjxx3cjgl3xq2-python3.5-dbus-python-1.2.4/lib/python3.5/site-packages','/nix/store/168n92ld073flhld87hz4nv39vr44rd7-python3.5-pygobject-3.22.0/lib/python3.5/site-packages','/nix/store/3j9whdk7zqif6jj9alrm8i3d0fx8ma7c-python3.5-python-systemd-231/lib/python3.5/site-packages','/nix/store/42dan8qv7ffjbwzqcnzdqw3mr16imwzp-python3.5-distutils-extra-2.39/lib/python3.5/site-packages','/nix/store/6f4piaq9la15ljqjjz0fyzf653kcfj5l-pyatspi-2.18.0/lib/python3.5/site-packages'], site._init_pathinfo());
PYTHON_EXECUTABLE = "python3"

from gi.repository import GLib

def run():
    GLib.spawn_async(argv=[PYTHON_EXECUTABLE,
                           "-cfrom Onboard.settings import Settings\ns = Settings(False)"],
                     flags=GLib.SpawnFlags.SEARCH_PATH)
```

## Technical details

* System: (NixOS: 17.03.1203.58e227052d (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.1203.58e227052d")
* Sandboxing enabled: (true)

**Comment by FRidh** [comment]
Since https://github.com/NixOS/nixpkgs/commit/c10af9e744c91dff1ccc07a52a0b57d1e4d339f3 wrappers should only be created in `$out/bin` and not elsewhere and so you wouldn't run into this issue. I see you are using unstable here. Do you intend to contribute this package to unstable? If so, test against master/unstable and not stable.

**Comment by johnramsden** [comment]
I'm testing against `nixos https://nixos.org/channels/nixos-17.03` locally. Why did you say I was using unstable? How do I get that change, is there a way I can get it immediately? Or exclude a certain file for now?

**Comment by FRidh** [comment]
I did not say you were using unstable. I asked whether you intend to contribute this to unstable (i.e., the master branch of this repo). The commit I referred to will not be backported to stable.

**Comment by johnramsden** [comment]
Oh I see. I'll change the branch. What should I do for now to get this change?

**Comment by johnramsden** [comment]
Just make sure get it right, I want to change to 0.5-stable, not 17.03-release right? Since I used master as the base branch, I guess I should probably close the pull request and reopen one with proper base branch.

**Comment by johnramsden** [comment]
@FRidh Is there be another way you can think of to exclude this file? I don't want to use unstable, but I want to be able to get this package working.

**Comment by FRidh** [comment]
@johnramsden you would have to override the whole `fixupPhase` I think and then use something like `wrapPythonProgramsIn $out "$out $pythonPath$` if I am correct. Its a bit harder with 17.03 compared to current unstable, because unstable has some nice improvements in `buildPythonPackage`.

**Comment by johnramsden** [comment]
@FRidh Thanks. Fortunately I was able to get it to stop the wrapping by removing the shebang, and setting the permissions to not be executable. Guess I'll consider this a solution.
