### ISSUE TITLE
Migrate from gcc 12 to gcc 13 as a default

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#262225]
### Describe the bug

At least on `linux` default used `gcc` is `12`. Outdated compilers generally tend to have more unfixed bugs than new ones. 

### Additional context

A recent example is https://gcc.gnu.org/PR55522 and `libsodium`'s https://github.com/jedisct1/libsodium/commit/ad4584d45590654b9d863ced90d2b2561d5cfbda where `-Ofast` broke many packages due to `gcc-12` (and older) deficiency.

### Notify maintainers

@Synthetica9 @vcunat @Ericson2314 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231020.d06515a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(slyfox): `""`
 - nixpkgs: `/run/current-system/sw/share/nixos-flakes/inputs/nixpkgs`
```

**Comment by vcunat** [comment]
This certainly won't make it to NixOS 23.11.

Usual porting reference: https://gcc.gnu.org/gcc-13/porting_to.html

**Comment by Gerg-L** [comment]
This would probably be a good idea right after 23.11

**Comment by trofi** [comment]
Was done with https://github.com/NixOS/nixpkgs/pull/268097 with [quite a bit of fallout](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+fix+gcc-13+build+failure). The rest of fallout will have to be addressed on a case-by-case basis.

Closing as done.

**Comment by vcunat** [comment]
This one is related: https://github.com/NixOS/nixpkgs/pull/284165
