### ISSUE TITLE
go-mockery is not overridable because of rec attrset

### ISSUE THREAD

**Issue by knightpp** [NixOS/nixpkgs#262237]
## Issue description
See https://vid.bina.me/tools/nix/nix-set-laziness/ for context on rec attrset laziness.

I propose moving version argument up to the top-level arguments of `go-mockery/default.nix`, which then will be easily overridable by using `go-mockery.override { version = "vN.N.N"; }`. I'm not aware of other ways to fix this.

### Steps to reproduce
Try to override version of the package, which produces binary with incorrect version.

## Package maintainer
@cideM

**Comment by SuperSandro2000** [comment]
Even with finalAttrs you would need to use overrideAttrs to update the FOD. closing as this is a common issue.

**Comment by SuperSandro2000** [comment]
> could you please elaborate why we shouldn't fix the issue?

Because it is not the issue, it is an issue for literally **every** package.

> There are packages with the same solution as I described. See

People shouldn't do this as it doesn't do what people expect. You must update the source hash otherwise you build the same thing under different name nad we have override/overrideAttrs for that
