### ISSUE TITLE
ceph v10 support

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#26236]
## Issue description

Currently last version of ceph supported on NixOS is 9.x.x.

In order to make ceph v10.2.7 compile, I first duplicate all files from` <nixpkgs>/pkgs/tools/filesystems/ceph`, then modify [generic.nix](https://gist.github.com/yuchangyuan/6b55ccb175c0705879e27dbb610d484d) and [fix-pythonpath.patch](https://gist.github.com/yuchangyuan/94f80768dfc8cdac523bc4393c9c6bb3), also [make some change to the parameters](https://gist.github.com/yuchangyuan/c3b263609a1937f75477c6c3453af68c) that apply to generic.nix.

All above modification is is ad-hoc, and these changes actually make ceph v10 compiles on NixOS, but I wish there will be an official support for ceph v10 on NixOS.

## Technical details

* System: 17.03.982.b647a67dfe (Gorilla)
* Nix version: 1.11.8
* Nixpkgs version: 17.03.982.b647a67dfe
* Sandboxing enabled: no

**Comment by FRidh** [comment]
> All above modification is is ad-hoc, and these changes actually make ceph v10 compiles on NixOS, but I wish there will be an official support for ceph v10 on NixOS.

Open a PR! There's always people around willing to help out.

I'm closing this because its just a package request.

**Comment by bachp** [comment]
@yuchangyuan Could you make a PR for this? I might be able to help.

**Comment by yuchangyuan** [comment]
I think it will cost me to much time to understand the build process of ceph, and I do not know python, which both is necessary to write a good enough PR. So I am sorry that I am not competent to write a PR for new ceph version.

So I recently give up compile ceph on NixOS, and depend on rkt and ceph/daemon docker image to use ceph on NixOS.
