### ISSUE TITLE
Update request: bun 0.6.2 → 1.0.6

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#262396]
- Package name: bun
- Latest released version: 1.0.6

- Current version on the unstable channel: 0.6.2
- Current version on the stable/release channel: 0.6.2

- [ Done ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by eclairevoyant** [comment]
https://github.com/NixOS/nixpkgs/pull/260679 Bun is already at 1.0.6

**Comment by Ciflire** [comment]
Nvmd i don't know how i did not switch channels but here we are, however, ti's in 0.6.2 in the 23.05 channel

**Comment by eclairevoyant** [comment]
Breaking changes don't get backported to stable in general, per guidelines. If you need the current version, use unstable.
