### ISSUE TITLE
Installing nixos on Macbook Air 7,1 fails. squashfs error unable to read id index table

### ISSUE THREAD

**Issue by Qwertie-** [NixOS/nixpkgs#26230]
## Issue description
When I boot the Graphical live CD, 64-bit Intel/AMD it starts to boot and then gets stuck on
```
mounting /mnt-root/iso/nix-store.squashfs on /nix/.ro-store...
    squashfs: version 4.0 (2009/01/31) Phillip Lougher
    squashfs error: unable to read id index table
mount: mounting /dev/loop0 on /mnt-root/nix/.ro-store failed: Invalid argument
```
I am then given the option to start a shell or reboot

### Steps to reproduce

Happens every time I try to boot nixos on my Macbook 7,1

## Technical details

Using this iso to boot: https://d3g5gsiof5omrk.cloudfront.net/nixos/17.03/nixos-17.03.1203.58e227052d/nixos-graphical-17.03.1203.58e227052d-x86_64-linux.iso

**Comment by Mic92** [comment]
To prevent hours of debugging: Did you compare checksums so data corruption can be excluded?

**Comment by Qwertie-** [comment]
Downloaded a new ISO and checked the checksum and that boots fine. Either it was a bad image or a newer build fixed something.
