### ISSUE TITLE
libreoffice doesn't come with the en-us dictionary

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#26234]
## Issue description
When installing LibreOffice, one would expect there to be a default dictionary to handle spell-checking.
There isn't. 

The pkgs has ["# TODO: dictionaries"](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/libreoffice/default.nix#L48), put there by @domenkozar, and ["--without-myspell-dicts"](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/libreoffice/default.nix#L215), by @viric

## Technical details

* System: Any nix

**Comment by brodul** [comment]
This is super annoying, I had to write a report in a hurry.
There is a quick workaround by installing an extension. 

https://extensions.libreoffice.org/extensions/english-dictionaries

**Comment by JohnAZoidberg** [comment]
This still seems to be the case :(

**Comment by mmilata** [comment]
#80353 aims to make spellcheck in LibreOffice work with packaged hunspell dictionaries. Testing appreciated.

**Comment by magnetophon** [comment]
How do I test?
I tried running `` nix-review pr 80353`` but the resulting binary didn't have working spellcheck as far as I could tell.

**Comment by mmilata** [comment]
@magnetophon You also need to install `hunspellDicts.xx_YY` packages for languages `xx_YY` you want to spellcheck.

**Comment by magnetophon** [comment]
Idk what's goingon: the first time I ran the above command it ran quickly and now it's been building for 18 hours.

**Comment by mmilata** [comment]
My guess is that LibreOffice has been updated in master (#80375) but Hydra hasn't built it yet (because it's busy with 20.03?) so you're building it from source.

**Comment by magnetophon** [comment]
Ah, I didn't know  ``nix-review pr`` built from master.  thanks.

**Comment by mmilata** [comment]
I'm not sure either, I suppose it tries to merge with master before building? Either way, if you have local copy of the nixpkgs repository you can build the package by checking out the branch and then running `nix-build . -A libreoffice` in the repo directory, hopefully the (older version of) main package will download from Hydra and the shell wrapper will be placed in `result`.

**Comment by Artturin** [comment]
Seems fixed
