### ISSUE TITLE
Package request: HTTPie Desktop

### ISSUE THREAD

**Issue by humancalico** [NixOS/nixpkgs#262494]
**Project description**
 HTTPie Desktop — cross-platform API testing client for humans. Painlessly test REST, GraphQL, and HTTP APIs. 

**Metadata**

* homepage URL: https://httpie.io/desktop
* source URL: https://github.com/httpie/desktop#linux
* license: unfree
* platforms: linux, darwin

**Comment by AnhQuanTrl** [comment]
This package is currently closed-source I think. So literally no way to start it :)
