### ISSUE TITLE
Update request: netbird/netbird-ui 0.23.8 → 0.24.0

### ISSUE THREAD

**Issue by the-furry-hubofeverything** [NixOS/nixpkgs#262451]
- Package name: netbird
- Latest released version: 0.24.0

- Current version on the unstable channel: 0.23.8
- Current version on the stable/release channel: 0.23.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@misuzu 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by FliegendeWurst** [comment]
Update PR: #262550
