### ISSUE TITLE
Update request: protontricks 1.10.1 → 1.10.5

### ISSUE THREAD

**Issue by TheMenko** [NixOS/nixpkgs#262414]
- Package name: protontricks
- Latest released version: 1.10.5
- Current version on the unstable channel: 1.10.1
- Current version on the stable/release channel: 1.10.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@kira-bruneau 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by FliegendeWurst** [comment]
Update PR: #262553

**Comment by kira-bruneau** [comment]
Superseded by https://github.com/NixOS/nixpkgs/pull/279749
