### ISSUE TITLE
Python: support Conda package manager

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#26245]
Conda (Anaconda / Miniconda) is a binary package manager widely used especially in the Python community. It'd be nice to be able use it easily in NixOS. I recently managed to get it working on my own system nicely. I wrote the details into a [blog post](http://www.jaakkoluttinen.fi/blog/conda-on-nixos/). Any ideas how this could be made usable in nixpkgs? I could try to work on it, but I'd need some ideas on how to approach that or where to look for some ideas.

@FRidh: By the way, I got Spyder working with this setup.

**Comment by jluttine** [comment]
I used `buildFHSUserEnv` to create FHS compatible environment. Here's the `shell.nix` file I used:
```
{ pkgs ? import <nixpkgs> {} }:

let

  # Conda installs it's packages and environments under this directory
  installationPath = "~/.conda";

  # Downloaded Miniconda installer
  minicondaScript = pkgs.stdenv.mkDerivation rec {
    name = "miniconda-${version}";
    version = "4.3.11";
    src = pkgs.fetchurl {
      url = "https://repo.continuum.io/miniconda/Miniconda3-${version}-Linux-x86_64.sh";
      sha256 = "1f2g8x1nh8xwcdh09xcra8vd15xqb5crjmpvmc2xza3ggg771zmr";
    };
    # Nothing to unpack.
    unpackPhase = "true";
    # Rename the file so it's easier to use. The file needs to have .sh ending
    # because the installation script does some checks based on that assumption.
    # However, don't add it under $out/bin/ becase we don't really want to use
    # it within our environment. It is called by "conda-install" defined below.
    installPhase = ''
      mkdir -p $out
      cp $src $out/miniconda.sh
    '';
    # Add executable mode here after the fixup phase so that no patching will be
    # done by nix because we want to use this miniconda installer in the FHS
    # user env.
    fixupPhase = ''
      chmod +x $out/miniconda.sh
    '';
  };

  # Wrap miniconda installer so that it is non-interactive and installs into the
  # path specified by installationPath
  conda = pkgs.runCommand "conda-install"
    { buildInputs = [ pkgs.makeWrapper minicondaScript ]; }
    ''
      mkdir -p $out/bin
      makeWrapper                            \
        ${minicondaScript}/miniconda.sh      \
        $out/bin/conda-install               \
        --add-flags "-p ${installationPath}" \
        --add-flags "-b"
    '';

in
(
  pkgs.buildFHSUserEnv {
    name = "conda";
    targetPkgs = pkgs: (
      with pkgs; [

        conda

        # Add here libraries that Conda packages require but aren't provided by
        # Conda because it assumes that the system has them.
        #
        # For instance, for IPython, these can be found using:
        # `LD_DEBUG=libs ipython --pylab`
        xorg.libSM
        xorg.libICE
        xorg.libXrender
        libselinux

        # Just in case one installs a package with pip instead of conda and pip
        # needs to compile some C sources
        gcc

        # Add any other packages here, for instance:
        emacs
        git

      ]
    );
    profile = ''
      # Add conda to PATH
      export PATH=${installationPath}/bin:$PATH
      # Paths for gcc if compiling some C sources with pip
      export NIX_CFLAGS_COMPILE="-I${installationPath}/include"
      export NIX_CFLAGS_LINK="-L${installationPath}lib"
      # Some other required environment variables
      export FONTCONFIG_FILE=/etc/fonts/fonts.conf
      export QTCOMPOSE=${pkgs.xorg.libX11}/share/X11/locale
    '';
  }
).env
```

Then, I created a command to activate it easily:
```
function conda-shell {
    nix-shell ~/.conda-shell.nix
}
```

Now, I'm not sure how this would be used in nixpkgs. Should I add `conda-shell` executable which activates the FHS user environment for Conda? But how would users add their own packages and configuration to that easily? Or can I wrap Conda in such a way that whenever `conda` is called, it is actually run in the FHS user environment?

**Comment by FRidh** [comment]
If I am correct the tricky part is here that you need those env variables set even when just using a conda env, am I right? And you can't create a wrapper because all the scripts that are provided by conda as well as your envs would have to be wrapped then. If you do not need those env variables during runtime, then you could just install (e.g. with `nix-env -i`) this user env. That's at least how it works with Steam if I am correct. 

Also possibly interesting: https://conda.io/docs/using/envs.html#saved-environment-variables

@abbradar , any suggestions?

**Comment by FRidh** [comment]
I once attempted to package `conda` but couldn't because of https://github.com/conda/conda/issues/1509. Considering it is said to be fixed I could have a look at that again.

**Comment by AforAnonymous** [comment]
You might want to crossreference this:
https://gitlab.com/pjotrp/guix-notes/blob/master/CONDA.org

It's not for Nix, obviously, but since guix & nix share some architectural similarities you might find it helpful.

Also, you might wish to know about some of the dependency hell issues conda projects face (the document I linked already kind of addresses that in part), see for example here: https://github.com/bioconda/bioconda-recipes/issues/2796

**Comment by FRidh** [comment]
Closing in favor of the merged https://github.com/NixOS/nixpkgs/pull/34872.

@AforAnonymous thanks for the info.
