### ISSUE TITLE
impossible constraints of pythonPackages.trezor_agent and electrum

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#26249]
## Issue description
`electrum` and `trezor_agent` both require the two packages:
1. `keepkey` which requires `hidapi` == 0.7.99.post15
2. `trezor` which requires `hidapi` >= 0.7.99.post20

The constraints are impossible to satisfy simultaneously.
Can we disable this madness entirely? Possible workaround besides downgrading?

**Comment by FRidh** [comment]
9/10 times these specific versions are not required and are simply due to the developers using something like pip freeze (damn the person writing implementing that!).
I suggest you patch keepkey to remove the pinning to the specific version.

**Comment by rnhmjoj** [comment]
Something like this? https://github.com/rnhmjoj/nixpkgs/commits/hidapi

**Comment by FRidh** [comment]
Yes, though instead of creating a patch a sed expression would likely be more easier to maintain here.
