### ISSUE TITLE
OpenVPN: custom start command

### ISSUE THREAD

**Issue by plchldr** [NixOS/nixpkgs#26255]
I'd like to start an OpenVPN  client in a namespace (by preprending "ip netns exec vpn ") as well as pass username and password ("--auth-user-pass"). There is no option for either, so I wonder how to get there.

I tried `systemd.services.openvpn-(name).serviceConfig.ExecStart = lib.mkForce "echo 0";` which resulted in 

> openvpn-{name}.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.

But even if that was working, I probably couldn't pass the config file .. so maybe a change to the service is needed for these use cases?

**Comment by Mic92** [comment]
**Enable**/Configure the service as usual and also set something like that:

```
systemd.services.openvpn-foo.serviceConfig.ExecStart = "${pkgs.iproute}/bin/ip netns exec vpn ${pkgs.openvpn}/bin/openvpn --config ${configFile}";
```

where foo is the name of your server. If that does not work. Post the content of your service file:

```
$ systemctl cat openvpn-foo.service
# ...
```

`lib.mkForce "echo 0";` would never work as `echo` is a shell built-in and you always have to pass the full paths to a command in systemd.

**Comment by plchldr** [comment]
Thanks for the reply!
I thought that echo would work as a placeholder, but it seems I was at least on the right track.
Using your suggestion produces `error: undefined variable ‘configFile’` as expected though.
Omitting this parameter for now I get `Missing '='` from systemd because the openvpn command is written in  a new line:
```
[Unit]
After=network.target
Description=OpenVPN instance ‘nordvpn-de’

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/mry6hpzxg44idk6pmqhcjvxzr665y43p-glibc-locales-2.25/lib/locale/locale-archive"
Environment="PATH=/nix/store/2naggfpyy8bng9q7b89dwjcn5qxwgmr0-iptables-1.6.1/bin:/nix/store/lnq9vblmqd6pi7m429r8hyfn2m5ajphl-iproute2-4.9.0/bin:/nix/store/fm04y592kmmxw3ijzwkqyg0pvnvlp56s-net-tools-1.60_p20120127084908/bin:/nix/store/k8dyhz9hrjydl23ny3131am6cws1rc07-coreutils-8.26/bin:/nix/store/dqzqrrampaf665laggc4ng33dfbxv5q7-findutils-4.6.0/bin:/nix/store/3r21p23hmbzj1ykv2wllqr14k1b0cdmx-gnugrep-3.0/bin:/nix/store/2nzkvn5b9jxdj75mgw6cdvpl6438sdqw-gnused-4.4/bin:/nix/store/px7a1kq4prjzw17c9pppssdmibqqdm2p-systemd-232/bin:/nix/store/2naggfpyy8bng9q7b89dwjcn5qxwgmr0-iptables-1.6.1/sbin:/nix/store/lnq9vblmqd6pi7m429r8hyfn2m5ajphl-iproute2-4.9.0/sbin:/nix/store/fm04y592kmmxw3ijzwkqyg0pvnvlp56s-net-tools-1.60_p20120127084908/sbin:/nix/store/k8dyhz9hrjydl23ny3131am6cws1rc07-coreutils-8.26/sbin:/nix/store/dqzqrrampaf665laggc4ng33dfbxv5q7-findutils-4.6.0/sbin:/nix/store/3r21p23hmbzj1ykv2wllqr14k1b0cdmx-gnugrep-3.0/sbin:/nix/store/2nzkvn5b9jxdj75mgw6cdvpl6438sdqw-gnused-4.4/sbin:/nix/store/px7a1kq4prjzw17c9pppssdmibqqdm2p-systemd-232/sbin"
Environment="TZDIR=/nix/store/ib356ccx25xixzjmj0fmgdv61kj1f398-tzdata-2016j/share/zoneinfo"



ExecStart=/nix/store/lnq9vblmqd6pi7m429r8hyfn2m5ajphl-iproute2-4.9.0/bin/ip netns exec vpn 
/nix/store/636s56z4zg8nwjsi1r72wb9f295vvscz-openvpn-2.4.2/bin/openvpn
Restart=always
Type=notify
```
(cat said `No files found for openvpn-nordvpn-de.service`, so I pulled this out of the store according to status error)

**Comment by Mic92** [comment]
You are right: `configFile` is local variable of the openvpn module and I missed that.
What you could do instead is to just use your own template.
The updated example would then look like this:

```nix
{
systemd.services.openvpn-foo.serviceConfig.ExecStart = "${pkgs.iproute}/bin/ip netns exec vpn ${pkgs.openvpn}/bin/openvpn --config ${pkgs.writeText "openvpn-config" ''
  # here your openvpn config goes to
''}";
}
```

**Comment by brainrape** [comment]
Afaict the above solves the problem. Can we close this @plchldr  ?

**Comment by plchldr** [comment]
I guess you're right, sorry for not closing this sooner.
