### ISSUE TITLE
Package request: Synergy3

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#262504]
**Project description**

 The cross-platform keyboard and mouse sharing tool (Windows, macOS, Linux), version 3

**Metadata**

* homepage URL: https://symless.com/synergy/news/official-launch-of-synergy-3
* source URL: https://github.com/symless/synergy-core
* license: gpl2
* platforms: unix, linux, darwin

**Comment by chewblacka** [comment]
> * source URL: https://github.com/symless/synergy-core

Synergy is already in the repos.

**Comment by chewblacka** [comment]
Synergy 3 looks to be commercial / non open-source (you can't even download a binary without logging in). Closing as non-applicable.
