### ISSUE TITLE
Czkawka missing .desktop file for GUI

### ISSUE THREAD

**Issue by KodyVB** [NixOS/nixpkgs#262665]
### Describe the bug
When Czkawka is installed via home-manager, no .desktop files are made for the GUI part of the application, meaning you have to run `czkawka_gui` from the terminal to run the application.

### Steps To Reproduce
1. Install Czkawka, i.e. 
```nix
home.packages = [
  pkgs.czkawka
]
```
2. Search for a .desktop file for Czkawka, `sudo find / -name "*.desktop" | grep "czk"`

### Expected behavior
A desktop file should be there so you can open the Czkawka GUI from things like an application launcher.

### Additional context
Along with this request, I'm providing three files from the czkawka-git package I got from the AUR in the hopes that it might help:
1. The .desktop file they provided, with .txt appended to the filetype to share on Github 
2. The 128x128 png icon they provided, renamed with 128x128 appended to the name
3. The 64x64 png icon they provided, renamed with 64x64 appended to the name 

I'm not sure if these would get used in nixpkgs, but figured it wouldn't hurt to provide them.

### Notify maintainers

@yanganto @0x4A6F 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4335.898cb2064b6e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(kody): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
[com.github.qarmin.czkawka.desktop.txt](https://github.com/NixOS/nixpkgs/files/13062298/com.github.qarmin.czkawka.desktop.txt)
![com github qarmin czkawka128x128](https://github.com/NixOS/nixpkgs/assets/43708421/13f12d1d-f790-4f30-af91-7caee8d3f1fc)
![com github qarmin czkawka64x64](https://github.com/NixOS/nixpkgs/assets/43708421/a8be7c89-7430-47e3-9091-7c6528041a67)

**Comment by yanganto** [comment]
Hi @KodyVB 

Thanks for reporting this.

I am using `leftwm`, which is not a full desktop, so I am not really using `.desktop` files in my environment.  Could you help to check this on your machine with the following command?  
`nix-shell -p nixpkgs-review --run "nixpkgs-review pr 262720"`

If everything looks good, I will change the PR to ready for review.

**Comment by chewblacka** [comment]
LGTM 
Package builds and desktop file gets installed with correct icon.

```
1 package built:
czkawka
```

**Comment by KodyVB** [comment]
I did the following:
1. Fork the nixpkgs repo
2. Ran `git clone --depth 1 https://github.com/KodyVB/nixpkgs.git`
3. `cd`'d into the directory and ran `nix-shell -p nixpkgs-review --run "nixpkgs-review pr 262720"`

It failed with the following:
```console
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/262720/head:refs/nixpkgs-review/1
remote: Enumerating objects: 4055995, done.
remote: Counting objects: 100% (4055993/4055993), done.
remote: Compressing objects: 100% (969219/969219), done.
remote: Total 4027123 (delta 2795929), reused 4011728 (delta 2781707), pack-reused 0
Receiving objects: 100% (4027123/4027123), 3.22 GiB | 11.32 MiB/s, done.
Resolving deltas: 100% (2795929/2795929), completed with 7199 local objects.
From https://github.com/NixOS/nixpkgs
 * [new branch]              master                -> refs/nixpkgs-review/0
 * [new ref]                 refs/pull/262720/head -> refs/nixpkgs-review/1
$ git worktree add /home/kody/.cache/nixpkgs-review/pr-262720/nixpkgs 132ce512b7e8f601afec616517eb02f6a84841c2
Preparing worktree (detached HEAD 132ce512b7e)
Updating files: 100% (37749/37749), done.
HEAD is now at 132ce512b7e Merge pull request #262471 from kilianar/calibre-6.29.0
$ git merge --no-commit --no-ff c49bdf8449987c4567f115f0a52aa387abd716ee
fatal: refusing to merge unrelated histories
https://github.com/NixOS/nixpkgs/pull/262720 failed to build
```

Sorry if I'm doing anything wrong - I'm very new to NixOS and am not nearly as acquainted with it as something like Arch.

**Comment by yanganto** [comment]
Hi @KodyVB 
No worry, please check this
https://github.com/Mic92/nixpkgs-review

You use `--depth=1` when git clone, so the branch commit of the PR is not covered in your local repo.  This possibly creates a problem.  If nixpkgs-review does not work, you can just follow the manual check out the branch and installed it by `nix-env -f /path/to/repo -iA czkawka`

**Comment by KodyVB** [comment]
I tried cloning without the `--depth=1` and ran the previous command and also `nix-shell -p nixpkgs-review` followed by `nixpkgs-review pr 262720` and then I tried it with `nixpkgs-review pr -p czkawka 262720`

The first two times, I ran out of RAM and my laptop's screen froze while the fans were going full speed, and I had to hard-reboot my computer. The third time, I cut the test short as soon as I hit 7.4/7.7 GB of RAM filled.

**Comment by yanganto** [comment]
No worry, there is another person who helped to double-check the PR, I believe it will be merged soon. :smile:
