### ISSUE TITLE
mullvad-daemon doesn't pick up resolvconf

### ISSUE THREAD

**Issue by stephen-huan** [NixOS/nixpkgs#262681]
### Describe the bug

I'm using resolvconf with mullvad. By default, mullvad ignores the resolvconf configuration, replacing `/etc/resolv.conf` by itself and putting the old contents in `/etc/resolv.conf.mullvadbackup`. `journalctl -u mullvad-daemon.service` shows
```
[talpid_core::dns][INFO] Setting DNS servers to 10.64.0.1
[talpid_core::dns::imp::static_resolv_conf][DEBUG] No DNS state backup to restore
[talpid_core::dns::imp][DEBUG] Managing DNS via /etc/resolv.conf
```

However, directly running `sudo mullvad-daemon --disable-log-to-file -v` correctly uses resolvconf.

```
[talpid_core::dns][INFO] Setting DNS servers to 10.64.0.1
[talpid_core::dns::imp][DEBUG] Managing DNS via resolvconf
```

This is because [mullvad checks the path for resolvconf](https://github.com/mullvad/mullvadvpn-app/blob/03feae48cd2832cf8460a76ccb5aa868fc52435c/talpid-core/src/dns/linux/resolvconf.rs#L44) when deciding which dns management strategy to use. If it can't be found, it uses [static_resolv_conf.rs](https://github.com/mullvad/mullvadvpn-app/blob/main/talpid-core/src/dns/linux/static_resolv_conf.rs) instead, which directly deletes/creates/restores `/etc/resolv.conf`.

This can be fixed by adding `config.networking.resolvconf.package` to the daemon's path in the unit file.
```nix
systemd.services.mullvad-daemon.path = [
  config.networking.resolvconf.package
];
```

### Steps To Reproduce
1. enable mullvad with `services.unbound.enable = true`
2. enable resolvconf with `networking.resolvconf.enable = true`
3. monitor the contents of `/etc/resolv.conf`

### Expected behavior
mullvad-daemon should use resolvconf if it's enabled.

### Notify maintainers

@patricksjackson (@arcuru ?) @ymarkus

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.11 (Tapir), 23.11.20231009.f99e5f0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/0axp4y6hffffs95l5865szvpcmq9g08p-source`

**Comment by arcuru** [comment]
That makes sense to me. Were you planning to open a PR?

One change I would request is to only include `config.networking.resolvconf.package` if resolvconf is enabled, since this reference would force the package to be installed. Something like

``` nix
systemd.services.mullvad-daemon.path = lib.mkIf config.networking.resolvconf.enable [
  config.networking.resolvconf.package
];
```

(Also yes, I renamed my GH account from patricksjackon -> arcuru. I missed updating my handle here and will do that shortly).

**Comment by stephen-huan** [comment]
> That makes sense to me. Were you planning to open a PR?

@arcuru I opened #264521. From the maintainer perspective, for trivial changes, is it easier to review a PR?

 I wasn't sure whether I should open a PR or to just leave it to you.
