### ISSUE TITLE
esphome: bwrap: Can't read /proc/sys/kernel/overflowuid: No such file or directory

### ISSUE THREAD

**Issue by megheaiulian** [NixOS/nixpkgs#262674]
### Describe the bug
When trying to build something with esphome:
bwrap: Can't read /proc/sys/kernel/overflowuid: No such file or directory

### Steps To Reproduce
Enabled esphome.
Try to build something.

### Expected behavior
That it doesn't fail.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/1788114/afe2872c-d907-473b-9589-8f5b962af368)

### Additional context
 `ProcSubset`  in serviceConfig should  be set  to  the default value "all" instead of  "pid".

**Comment by SuperSandro2000** [comment]
You don't need to create an issue just for the sake of creating one, you can enable open a PR and then the discussion happens there.

**Comment by megheaiulian** [comment]
Ok. Will keep that in mind.
