### ISSUE TITLE
Firefox browserpass broken in unstable

### ISSUE THREAD

**Issue by aij** [NixOS/nixpkgs#262600]
### Describe the bug

After upgrading nixpks unstable and restarting Firefox around mid Oct 2023,
the browserpass extension in firefox stopped working.
It had been a while since I last restarted firefox, which makes it hard to tell when it broke exactly.

When trying to use browser pass via Ctrl-Shift-L or by clicking the browserpass icon in the toolbar I get

```
Error: Error: No such native application com.github.browserpass.native
```

Only broken on nixpkgs unstable (via nixos-unstable-small as of `2cb9af4323c64c93e8df3cae5988a53b8687ef3f`),
stable still works (nixos-23.05-small as of `0e1cff585c1a85aeab059d3109f66134a8f76935`).

### Steps To Reproduce
1. Set up firefox with browserpass (`programs.browserpass.enable = true; environment.systemPackages = [ pkgs.firefox ];`
2. Confirm working on nixos-23.05 or older version of unstable (eg `bfb7dfec93f3b5d7274db109f2990bc889861caf` from early September works)
3. Upgrade to latest unstable (anything that includes d3c27efa36abeb7f65cc8764d73d7805128c5386)
4. Restart firefox and try to use browserpass extension again

### Expected behavior

Browserpass extension should work and fill out username/password fields like it used to.

### Additional context

I did some debugging using older nixos generations I had

1. Sep 2 (generation 133) was working.
  * Tested via
    `/nix/store/7sdnrdvzim5mzfkyn5jdscan830i99sr-nixos-system-tobati-23.11.git.bfb7dfec93f3/sw/bin/firefox`
2. Oct 2 (generation 134) was broken.
 * Tested via
   `/nix/store/1gdxnf2q3rblj7zhw5hq7ia4jrps6d10-nixos-system-tobati-23.11.git.5d861cc17287/sw/bin/firefox`

That's a large range of commits unfortunately (including the upgrade from FF 117.0 to 118.0.1),
but manually looking for relevant commits, d3c27efa36abeb7f65cc8764d73d7805128c5386 stood out to me.

That commit added a new `programs.firefox.wrapperConfig` setting, and changed
`nixpkgs.config.firefox.enableBrowserpass = true` to `programs.firefox.wrapperConfig.enableBrowserpass = true`,
but the new setting isn't actually used anywhere.

[[[[https://github.com/NixOS/nixpkgs/blob/d3c27efa36abeb7f65cc8764d73d7805128c5386/pkgs/applications/networking/browsers/firefox/wrapper.nix#L39]]]]
still references `config.firefox`.

### Notify maintainers

@lovesegfault @mweinelt @K900

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
ivan@tobati:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.git.2cb9af4323c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/etc/nixos/aij/unstable`

 ```

**Comment by K900** [comment]
The new option is passed in as an override to the Firefox package: https://github.com/NixOS/nixpkgs/commit/d3c27efa36abeb7f65cc8764d73d7805128c5386#diff-2517ccea239f5cb479204bf923c5a91e8fb914de25c4493f16ed21ad4a346b97R223

You want to be using `programs.firefox.enable` so the override is actually applied.

**Comment by aij** [comment]
I'm pretty sure I tried `programs.firefox.enable` and it didn't make a difference. I'll try again though to be sure, since it does seem like it should work...

In the mean time, I found the workaround of setting `nixpkgs.config.firefox.enableBrowserpass = true` directly.

**Comment by K900** [comment]
You need to also remove `pkgs.firefox` from your `environment.systemPackages` in that case, and let the module add the overridden package.

**Comment by aij** [comment]
> You need to also remove pkgs.firefox from your environment.systemPackages in that case, and let the module add the overridden package.

I figured as much. For reference, here is the exact change I made to my config: https://github.com/aij/aij-nixos-config/commit/5151aba60fe81a30709346c4b2ba2605d4ed336b

And I get the `No such native application` error again.

Comparing the two wrapper scripts:

```diff
ivan@tobati:~$ diff -u /nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin/firefox /nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin/firefox
--- /nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin/firefox     1969-12-31 18:00:01.000000000 -0600
+++ /nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin/firefox     1969-12-31 18:00:01.000000000 -0600
@@ -218,14 +218,14 @@
 PATH=${PATH%':'}
 export PATH
 PATH=${PATH:+':'$PATH':'}
-if [[ $PATH != *':''/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin'':'* ]]; then
-    PATH=$PATH'/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin'
+if [[ $PATH != *':''/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin'':'* ]]; then
+    PATH=$PATH'/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin'
 fi
 PATH=${PATH#':'}
 PATH=${PATH%':'}
 export PATH
 export MOZ_APP_LAUNCHER='firefox'
-export MOZ_SYSTEM_DIR='/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/lib/mozilla'
+export MOZ_SYSTEM_DIR='/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/lib/mozilla'
 export MOZ_LEGACY_PROFILES='1'
 export MOZ_ALLOW_DOWNGRADE='1'
 XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
@@ -273,4 +273,4 @@
 XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
 XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
 export XDG_DATA_DIRS
-exec -a "/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin/.firefox-wrapped" "/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/bin/.firefox-wrapped"  "$@" 
+exec -a "/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin/.firefox-wrapped" "/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/bin/.firefox-wrapped"  "$@" 
```

```console
ivan@tobati:~$ ls -l /nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/lib/mozilla/native-messaging-hosts/ /nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/lib/mozilla/native-messaging-hosts/
/nix/store/1wrs7p403hvx1dw0pmz3pa3x07v3wrw0-firefox-118.0.1/lib/mozilla/native-messaging-hosts/:
total 1
lrwxrwxrwx 1 root root 131 Dec 31  1969 com.github.browserpass.native.json -> /nix/store/mnsaamj4grmzlvqqxmcwffzlih78y5hd-browserpass-3.1.0/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json

/nix/store/rvwbg8ay3y1svszclxhcjjhla19crck6-firefox-118.0.1/lib/mozilla/native-messaging-hosts/:
total 0
ivan@tobati:~$ 

```

**Comment by K900** [comment]
Can you try with https://github.com/NixOS/nixpkgs/pull/262017 applied?

**Comment by aij** [comment]
Trying again with the latest nixos-unstable-small (`44881e03af1c730cbb1d72a4d41274a2c957813a`) which includes that change, I get

```
error:
       … while calling the 'head' builtin

         at /home/ivan/nixops/aij/unstable/lib/attrsets.nix:850:11:

          849|         || pred here (elemAt values 1) (head values) then
          850|           head values
             |           ^
          851|         else

       … while evaluating the attribute 'value'

         at /home/ivan/nixops/aij/unstable/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: undefined variable 'ff2mpv'

       at /home/ivan/nixops/aij/unstable/nixos/modules/programs/firefox.nix:227:34:

          226|           old.extraNativeMessagingHosts or []
          227|           ++ optional nmh.ff2mpv ff2mpv
             |                                  ^
          228|           ++ optional nmh.euwebid web-eid-app
```

I fixed that with https://github.com/NixOS/nixpkgs/pull/262617

But I still get the same error from the browserpass extension unless I set `nixpkgs.config.firefox.enableBrowserpass = true` too.

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/262623
