### ISSUE TITLE
Package request: tuxclocker

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#262668]
**Project description**

TuxClocker is a hardware controlling and monitoring program. TuxClocker consists of a DBus daemon and a Qt GUI that uses the daemon.

It allows you to e.g. set a custom fan curve and overclock your CPU and GPU.

**Metadata**

* homepage URL: https://github.com/Lurkki14/tuxclocker
* source URL: https://github.com/Lurkki14/tuxclocker/tree/master/src
* license: gpl3
* platforms: linux

**Comment by Lurkki14** [comment]
https://github.com/NixOS/nixpkgs/pull/273219
