### ISSUE TITLE
Spell-checking does not work

### ISSUE THREAD

**Issue by monochromec** [NixOS/nixpkgs#262764]
### Describe the bug
https://github.com/NixOS/nixpkgs/issues/33944 seems to have resurfaced again. Perhaps a regression test issue?

### Steps To Reproduce
1. Install an English dictionary as outlined in the work-around of the issue
2. Misspell a word
3. No red underline indicated a misspelled word

### Expected behavior
Misspelling flagged with red underline.

### Screenshots
<img width="204" alt="Screenshot 2023-10-22 at 17 41 25" src="https://github.com/NixOS/nixpkgs/assets/606567/ac79d2c5-68da-4a15-83b7-8aeb62622551">

### Additional context
LO version is 7.6.0.3 running on OSX 14.0

### Notify maintainers

More than happy to provide additional info as required.

**Comment by chewblacka** [comment]
You might want to mention `Libre Office` in the Issue title.

**Comment by pearsche** [comment]
Doesn't just affect LO, spell checking doesn't really work on gnome-text-editor either.

**Comment by chewblacka** [comment]
> Doesn't just affect LO, spell checking doesn't really work on gnome-text-editor either.

ok thanks for clarifying

**Comment by chewblacka** [comment]
> Doesn't just affect LO, spell checking doesn't really work on gnome-text-editor either.

I can't seem to replicate this. `gnome-text-editor` works fine for me (on nixos stable and unstable, and also nixpkgs unstable). Can you provide a screen shot of spell checking failing on gnome-text-editor (with the appropriate file type showing)?

**Comment by pearsche** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/132031693/c6923477-2ecc-4bed-a557-adf6d7613b5f)
Be it on english or spanish (the two languages I speak), I don't get spell checking ever. I don't know what I have to enable or set, but in Arch Linux and Fedora, I had spell checking OOTB for english, and for spanish it was a matter of installing some packages.

**Comment by pearsche** [comment]
Well well well, I am stupid. I got it to work, after reading github issues, and such, I discovered that adding the dictionary packages (aka hunspellDicts.en_US and aspell.en) to the packages list (in my case, home.packages) is enough to have them installed and working with whatever programs use them. Wow.

**Comment by monochromec** [comment]
@chewblacka Accidentally chose the wrong repo - will open a separate issue upstream. Thanks for the hint and sorry about the oversight.

Closing this issue.

**Comment by monochromec** [comment]
Upstream issue: https://bugs.documentfoundation.org/show_bug.cgi?id=157892
