### ISSUE TITLE
SFML segfaults 

### ISSUE THREAD

**Issue by SandaruKasa** [NixOS/nixpkgs#262727]
### Describe the bug

I am running Arch Linux, with KDE Plasma 5.27.8 & Xorg 21.1.8.
Nix 2.18.1, on channel nixos-23.05. (Though the issue persists on any version of nixpkgs, as far as I am aware).

When I try to run any application that uses SFML, it segfaults. (Including the ones I build myself)

### Steps To Reproduce
Take, for example, extremetuxracer.

```console
$ nix-shell -p extremetuxracer

[nix-shell:~]$ etr
Segmentation fault (core dumped)

[nix-shell:~]$ echo $?
139

[nix-shell:~]$ which etr
/nix/store/ihn08cikk8zg9rfpxkcxfz13y60iw0df-extremetuxracer-0.8.2/bin/etr
```

### Additional context

Maybe it's an upstream SFML bug, but when I use SFML from Arch repos, things work just fine.
So not sure who to blame: nix, xorg, sfml, arch, or KDE.

### Notify maintainers

@astsmtl

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.8-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/home/sandarukasa/.nix-defexpr/channels/nixpkgs`
```

**Comment by materusPL** [comment]
It works fine for me on NixOS unstable.
Have you tried adding `--pure` flag to nix-shell?
Also since you're on Arch , did you run it with [NixGL](https://nixos.wiki/wiki/Nixpkgs_with_OpenGL_on_non-NixOS)?

**Comment by SandaruKasa** [comment]
> It works fine for me on NixOS unstable.

Yeah, I tested NixOS-23.05 in a VM, the same version works fine there.

> Have you tried adding `--pure` flag to nix-shell?

Refuses to work without $XAUTHORITY set. With it set, segfaults again.
<details>
<summary>Example</summary>

```console
$ nix-shell -p extremetuxracer --pure

[nix-shell:~]$ etr
Authorization required, but no authorization protocol specified
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
Aborted (core dumped)

[nix-shell:~]$ echo $DISPLAY
:0

[nix-shell:~]$ XAUTHORITY=/tmp/xauth_rBccpX etr
Segmentation fault (core dumped)

[nix-shell:~]$ XAUTHORITY=/tmp/xauth-1000-_0 etr
Segmentation fault (core dumped)

[nix-shell:~]$ XAUTHORITY=/tmp/this-path-does-not-exist etr
Authorization required, but no authorization protocol specified
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
Aborted (core dumped)
```

</details>

> Also since you're on Arch , did you run it with [NixGL](https://nixos.wiki/wiki/Nixpkgs_with_OpenGL_on_non-NixOS)?

Works for me! Thank you a lot.
