### ISSUE TITLE
Package request: arduino-ide

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#262782]
**Project description**

The Arduino Software (IDE) allows you to write programs and upload them to your board.

**Metadata**

* homepage URL: https://www.arduino.cc/en/software
* source URL: https://github.com/arduino/arduino-ide
* license: agpl3
* platforms: unix, linux, darwin, windows

**Comment by eliandoran** [comment]
@KiaraGrouwstra , under Linux the Arduino IDE should already be packaged (`arduino`) package.
Would you need it for macOS instead?

**Comment by KiaraGrouwstra** [comment]
@eliandoran ah apologies, that's great! i'll close then.
