### ISSUE TITLE
fetchzip and fetchurl hash differs for the same file

### ISSUE THREAD

**Issue by hrsto** [NixOS/nixpkgs#262786]
### Describe the bug
Downloading a file with fetchurl works and hash is as expected. Downloading the same file with fetchzip will error out due to different hash.

### Steps To Reproduce
1. Fetch URL for apache kafka: https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
2. Its sha512 hash: https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz.sha512
3. Download it via fetchurl - works OK
4. Download it via fetchzip - will show different hash

### Expected behavior
fetchzip uses fetchurl to first download the file and then extract its contents, it's expected to work the same for the same file.

### Screenshots

fetchurl:
![image](https://github.com/NixOS/nixpkgs/assets/28543548/37ffa573-ff83-48c9-b491-10439e47a908)

Result of build with fetchurl:
![image](https://github.com/NixOS/nixpkgs/assets/28543548/2c416eb1-48aa-4399-9876-f799546ae125)

fetchzip:
![image](https://github.com/NixOS/nixpkgs/assets/28543548/d854808f-8038-45d4-b8b6-281bf42b70c3)

Result of build with fetchzip:
![image](https://github.com/NixOS/nixpkgs/assets/28543548/7605bcff-5052-4005-8754-45d09d8866fb)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.05 (Stoat), 23.05.4420.679cadfdfed2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kilianar** [comment]
Comment in the file where `fetchzip` is defined:

```
# This function downloads and unpacks an archive file, such as a zip
# or tar file. This is primarily useful for dynamically generated
# archives, such as GitHub's /archive URLs, where the unpacked content
# of the zip file doesn't change, but the zip file itself may
# (e.g. due to minor changes in the compression algorithm, or changes
# in timestamps).
```

So, the difference appears to be intentional, as `fetchurl` hashes the zip file, whereas `fetchzip` hashes the contents after unpacking.

**Comment by hrsto** [comment]
Bad for me. I guess I will have to make my own extract archive derivation on top of fetchurl then. By the way, do you happen to know how can i enable internet access for my own derivations such that they behave like fetchurl - being able to download files without specifying explicitly any safe modes?

**Comment by kilianar** [comment]
You're searching for **fixed-output derivations**. You can find more information about this in the [Nix manual](https://nixos.org/manual/nix/stable/language/advanced-attributes.html?highlight=outputHash#adv-attr-outputHash).

**Comment by eclairevoyant** [comment]
Not sure why you need a new FOD here, as it will get unpacked anyway during that phase when using stdenv (https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L1057). You can just use fetchurl.
