### ISSUE TITLE
Build failure: mtdutils 2.1.6 (cross-compilation)

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#262763]
### Steps To Reproduce

1. build *pkgsStatic.aarch64-multiplatform.mtdutils* (or any other arch, I encountered this with an armv7l target)

### Build log

```
mtd-utils-aarch64-unknown-linux-gnu>   AR       libmissing.a
mtd-utils-aarch64-unknown-linux-gnu> /nix/store/xdqlrixlspkks50m9b0mpvag65m3pf2w-bash-5.2-p15/bin/bash: line 1: ar: command not found
mtd-utils-aarch64-unknown-linux-gnu> make: *** [Makefile:1896: libmissing.a] Error 127
```

https://gist.github.com/2xsaiko/1eb58e4fc73224a118f4cf76f35f73be

### Additional context

Since https://github.com/NixOS/nixpkgs/pull/260406, upstream commit [9fa0991](https://git.infradead.org/mtd-utils.git/commit/9fa09916db2e0d35194081175413336146e55a0e), still occurs in master (as of writing https://github.com/NixOS/nixpkgs/commit/187c660416b90709025402ef924d334dab140471). Likely an upstream issue but I don't know enough about autotools to know for sure.

Instead of the cross-compilation ar (aarch64-unknown-linux-gnu-ar), it tries to use normal ar which is not present during cross-compilation.

### Notify maintainers

@viric 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.11 (Tapir), 23.11.20231021.57afb47`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by NickCao** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/263179
