### ISSUE TITLE
Cannot search beamPackages

### ISSUE THREAD

**Issue by ankhers** [NixOS/nixpkgs#26279]
## Issue description
I am currently unable to search `beamPackages`

```
error: anonymous function at /nix/store/53fik4s4mflzc3dbhxyvcdsrqsdjf2rg-nixpkgs-17.09pre108299.ec9a23332f/nixpkgs/pkgs/development/beam-modules/hex-packages.nix:1550:9 called without required argument ‘redix_0_3_6’, at /nix/store/53fik4s4mflzc3dbhxyvcdsrqsdjf2rg-nixpkgs-17.09pre108299.ec9a23332f/nixpkgs/lib/customisation.nix:56:12
```

### Steps to reproduce
`$ nix-env -f "<nixpkgs>" -qaP -A beamPackages`

## Technical details

* System: OSX 10.11.6
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre108299.ec9a23332f"
* Sandboxing enabled: No such file

**Comment by ericsagnes** [comment]
Git bisect points to eeed6411ce6f1b9a6028dc1f521f35643bfd5901.
cc @ericbmerritt

**Comment by 0xABAB** [comment]
Probably redundant, but I can also reproduce this on 17.03.1482.1b57bf274a (Gorilla) (NixOS).

**Comment by ankhers** [comment]
@gleber and myself are working on fixing this. 

#26381, #26668 and #26716 are efforts to fixup the BEAM ecosystem before fixing the hex2nix tool that the `beamPackages` are generated from.

**Comment by gleber** [comment]
I'm actually leaning towards:
1) nuking beamPackages as they are now
2) implementing rebar2nix and mix2nix  (in both cases as plugins to Rebar3
and Mix) by factoring out code from hex2nix into common library and reusing
it from both plugins
3) adapting hex2nix to use the common library
4) upgrading all of the non-mass-imported Beam packages in nixpkgs
5) mass-importing beamPackages again using refreshed infrastructure.

Currently it's annoying to develop anything around Erlang and Elixir using
nixpkgs (it's does apply to work needed to be done in step 2 and 3). Maybe
step 4 could be done before step 2 actually... It will make development
easier.

What do you think?

**Comment by 0xABAB** [comment]
I think you should strive towards full automation. Manual work will get old.

**Comment by gleber** [comment]
Agreed. This is exactly the plan to upgrade and improve tools for full automation.

**Comment by 0xABAB** [comment]
@gleber Cool, can you make some issues with smaller scopes to provide more visibility into the progress that's being made? At least I think the proper order is to first file an issue, and then do a PR if it is a new functionality.

Many of these issues are more like projects and stay open for years until someone is bored and then months of work have been wasted. Just a suggestion, though, since I cannot enforce anything in this project.

**Comment by gleber** [comment]
I will use #11748 to track this work. I am currently busy with other stuff, but I expect to get back to this topic soon-ish.
