### ISSUE TITLE
Update request: raysession 0.13.1 → 0.14.2

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#262843]
- Package name:  raysession
- Latest released version: 0.14.2
- Current version on the unstable channel: 0.13.1
- Current version on the stable/release channel: 0.13.1
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

https://github.com/Houston4444/RaySession/releases/tag/v0.14.2

**Notify maintainers**

@orivej

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by FliegendeWurst** [comment]
Update PR: #262866
