### ISSUE TITLE
Bcache udev rules not installed outside initrd

### ISSUE THREAD

**Issue by dfoxfranke** [NixOS/nixpkgs#26281]
`bcache-tools` installs udev rules into the initrd but not into the main system. As a result, symlinks to bcache devices from `/dev/disk/by-uuid` and `/dev/disk/by-label` are missing.

Adding `bcache-tools` to `services.udev.packages` doesn't quite suffice as a workaround because of a hardcoded reference to `/bin/sh`. Instead I had to copy the contents of `69-bcache.rules` into `services.udev.extraRules` and replace `/bin/sh` with `${pkgs.stdenv.shell}`.

cc @bjornfor

**Comment by bjornfor** [comment]
I was thinking of making the rules file from bcache-tools depend on ${bash}/bin/sh instead of /bin/sh, and then making sure that ${bash}/bin/sh is replaced with something appropriate when the file is copied for the initrd (like the other replacements are handled). Then we can simply extend the bcache nixos module with "services.udev.packages = [ bcache-tools]" and everything should work, I think.

CC @abbradar, author of the patch that introduces /bin/sh in the udev rules. Does that sound like a plan?

**Comment by bjornfor** [comment]
I created https://github.com/bjornfor/nixpkgs/tree/bcache-udev-rules, but it doesn't seem to work. I still have no symlinks to bcache devices under ```/dev/disk/by-*```.

**Comment by dfoxfranke** [comment]
Strange. Everything's fine with the workaround I described, and I can't see anything wrong with your patch.

**Comment by abbradar** [comment]
@bjornfor Yep, that sounds like a plan! I commented on your patch. I don't see any problems with your code too -- strange.

**Comment by dfoxfranke** [comment]
Wild guess as to what your problem might be: did you by chance test this with a newly-created bcache volume, without putting a filesystem on it? The UUID and label in the symlink belong to the filesystem, not to the volume itself.

**Comment by bjornfor** [comment]
@dfoxfranke: This is a bcache + LVM setup I've had for a while. Ah, that means that the filesystem in my setup is on _LVM_, not bcache.

```
$ lsblk -f
NAME                   FSTYPE      LABEL   UUID                                   MOUNTPOINT
sda                                                                               
└─sda1                 bcache              381515cc-ea19-405d-8fe9-0a9496cb0545   
  └─bcache0            LVM2_member         KqEBs6-fK2n-1qwJ-8ta7-JA1n-IwTA-0IEa76 
    └─nixos--vg2-lvol0 ext4        nixos   0ae86022-cd0d-4d14-be8b-130826ddb47e   /
sdb                                                                               
├─sdb1                 vfat        EFIBOOT 16F4-6466                              /boot
├─sdb2                 bcache              3cb32741-f983-4680-bb7a-b7161079e69f   
│ └─bcache0            LVM2_member         KqEBs6-fK2n-1qwJ-8ta7-JA1n-IwTA-0IEa76 
│   └─nixos--vg2-lvol0 ext4        nixos   0ae86022-cd0d-4d14-be8b-130826ddb47e   /
├─sdb3                                                                            
└─sdb4                                                                            
```

hardware-configuration.nix points to the UUID of the LVM device:
```
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0ae86022-cd0d-4d14-be8b-130826ddb47e";
      fsType = "ext4";
    };
```

And that UUID points to /dev/dm-0:
```
$ ls -l /dev/disk/by-uuid/0ae86022-cd0d-4d14-be8b-130826ddb47e
lrwxrwxrwx 1 root root 10 Jun  1 23:46 /dev/disk/by-uuid/0ae86022-cd0d-4d14-be8b-130826ddb47e -> ../../dm-0
```

**Comment by bjornfor** [comment]
I created PR https://github.com/NixOS/nixpkgs/pull/26344.

**Comment by dfoxfranke** [comment]
Okay, that would do it. In my case I'm also running LVM, but I have a LUKS layer (named `/dev/mapper/crypt0`) in between. The UUID of the symlink that points to `/dev/bcache0` is the one shown by `cryptsetup luksDump /dev/bcache0`. I do *not* have any UUID symlink pointing to my `crypt0` device, which is formatted as an LVM physical volume.
