### ISSUE TITLE
Update request: typstfmt 0.2.5 → 0.2.6

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#262897]
- Package name: typstfmt 
- Latest released version: 0.2.6

- Current version on the unstable channel: 0.2.5
- Current version on the stable/release channel: 26/04/2023 (dd/mm/yyyy)

- [ yes ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kilianar** [comment]
typstfmt has already been updated to version 0.2.6 in pull request #262638.
