### ISSUE TITLE
Update request: openrct2 0.4.5 → 0.4.6

### ISSUE THREAD

**Issue by ToppDev** [NixOS/nixpkgs#263025]
- Package name: openrct2
- Latest released version: 0.4.6
- Current version on the unstable channel: 0.4.5
- Current version on the stable/release channel: 0.4.4
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@oxzi 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by PedroHLC** [comment]
I attempted this one, and even though all the new title-sequences files are in the same place as the old ones, it fails to load those. And it fails to load the park files from the original games, that reads without any issues in 0.4.5.

- Failure logs: [rct2.log](https://github.com/NixOS/nixpkgs/files/13194185/rct2.log)
Note that object conflict also happens in 0.4.5.

- Bump commit: https://github.com/PedroHLC/nixpkgs/commit/719cbd1a52a5630d681a863d6b13c5aff65be81d

- Suggestions/Enhancements:
  - Use SRI-hash field: https://github.com/PedroHLC/nixpkgs/commit/fa19ac6ee30e177df08a12ecf0075f017f5eb91a
  - Use "srcs" (solves #225894): https://github.com/PedroHLC/nixpkgs/commit/ce4d21859828ca424e1a127efdc48d63b2f6c66f

**Comment by ToppDev** [comment]
I experienced the same when I tried 0.4.6 with an overlay. Also could not connect to multiplayer games because he could not load the map. Hoped that somebody more knowledgeable in NixOS could solve this.

**Comment by oxzi** [comment]
Please excuse the late reply. When 0.4.6 came out, I tried bumping the versions as I did before and ran in the same buggy behavior as @PedroHLC and @ToppDev did. Since then I procrastinated debugging it. I'm hoping that I'll find time this week. If someone else beets me, I would also be happy.
