### ISSUE TITLE
grub: grub-locales are not versioned upstream

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#263095]
The grub build uses [linguas.sh](https://git.savannah.gnu.org/cgit/grub.git/tree/linguas.sh) to fetch the latest translation files from https://translationproject.org/domain/grub.html .

In the Nix package, this result is stored in a fixed-output derivation, even though the online content may change (https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/grub/default.nix#L56-L71). As noted there, this means as long as the content is cached in Hydra most users won't notice a problem, but rebuilding is no longer possible.

/cc @samueldr

**Comment by trofi** [comment]
One of the options would be to request grub upstream to commit locales file to the source tree. It feels natural as locales are dependent on a particular source release.

**Comment by raboof** [comment]
> One of the options would be to request grub upstream to commit locales file to the source tree. It feels natural as locales are dependent on a particular source release.

I suspect they'll just tell us to use the release tarballs.

Perhaps we should indeed get the translation files from the 'nearest' release tarball (but still keep building the main program from VCS), like you suggested on matrix. Unfortunately we're currently on 2.12-rc1 and there's no release tarball for that.
