### ISSUE TITLE
Spotify not working

### ISSUE THREAD

**Issue by Felopater-Melika** [NixOS/nixpkgs#263197]
## Issue description
Spotify not working with the following error message
```
/home/philopater/.nix-profile/bin/spotify: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /home/philopater/.nix-profile/bin/spotify)
/nix/store/1nhxbfy96p12w5nh8dmbc23a2xd1yyap-spicetify-catppuccin-mocha/share/spotify/.spotify-wrapped: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/1nhxbfy96p12w5nh8dmbc23a2xd1yyap-spicetify-catppuccin-mocha/share/spotify/.spotify-wrapped)
/nix/store/1nhxbfy96p12w5nh8dmbc23a2xd1yyap-spicetify-catppuccin-mocha/share/spotify/.spotify-wrapped: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/1nhxbfy96p12w5nh8dmbc23a2xd1yyap-spicetify-catppuccin-mocha/share/spotify/.spotify-wrapped)

(spotify:70572): GLib-GIO-CRITICAL **: 13:04:34.326: g_settings_schema_source_lookup: assertion 'source != NULL' failed
/proc/self/exe: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
Segmentation fault (core dumped)
```

### Steps to reproduce
Just install spotify in an unstable system

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
these 6 paths will be fetched (0.75 MiB download, 10.18 MiB unpacked):
  /nix/store/xfjqspcc9442hi0lm0szv3sw75zswvml-file-5.45
  /nix/store/pnndfnlqvbfj0m86q7dxnyk2lw88k6a8-gnu-config-2023-07-31
  /nix/store/2jp6cv2q4cgh91f5lp57p945rq98ldhr-gnumake-4.4.1
  /nix/store/ay0p9mbw1w3zkvwzx3c94xq7x8jrn9wq-patchelf-0.15.0
  /nix/store/3pfjacvdg9f491lfqc9qb2d0nknx73fb-stdenv-linux
  /nix/store/yllcj971mwa0rvgwvd876a52391m8s9y-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/pnndfnlqvbfj0m86q7dxnyk2lw88k6a8-gnu-config-2023-07-31' from 'https://cache.nixos.org'...
copying path '/nix/store/xfjqspcc9442hi0lm0szv3sw75zswvml-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/2jp6cv2q4cgh91f5lp57p945rq98ldhr-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/ay0p9mbw1w3zkvwzx3c94xq7x8jrn9wq-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/yllcj971mwa0rvgwvd876a52391m8s9y-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/3pfjacvdg9f491lfqc9qb2d0nknx73fb-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by eclairevoyant** [comment]
I see spicetify in the error message. Can you confirm if this issue happens without spicetify?

**Comment by Felopater-Melika** [comment]
> I see spicetify in the error message. Can you confirm if this issue happens without spicetify?

whither i use it or not it doesn't work

```
spotify
/home/philopater/.nix-profile/bin/spotify: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /home/philopater/.nix-profile/bin/spotify)
/nix/store/wl7cxfbga9r01hnwxnkd34saiwz9s63b-spotify-1.2.13.661.ga588f749/share/spotify/.spotify-wrapped: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/wl7cxfbga9r01hnwxnkd34saiwz9s63b-spotify-1.2.13.661.ga588f749/share/spotify/.spotify-wrapped)
/nix/store/wl7cxfbga9r01hnwxnkd34saiwz9s63b-spotify-1.2.13.661.ga588f749/share/spotify/.spotify-wrapped: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/wl7cxfbga9r01hnwxnkd34saiwz9s63b-spotify-1.2.13.661.ga588f749/share/spotify/.spotify-wrapped)

(spotify:34899): GLib-GIO-CRITICAL **: 17:26:20.937: g_settings_schema_source_lookup: assertion 'source != NULL' failed
/proc/self/exe: /nix/store/1f50zvph1qkkamyqfffwkydlppqpzbl9-curl-8.3.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
fish: Job 1, 'spotify' terminated by signal SIGSEGV (Address boundary error)
```

this is the error message with just spotify and .config/spotify and .cache/spotify uninstalled 

we also tried in the discord to run an external configuration from Greg-L 

and xwayland was off I turned it on and it still doesn't work

**Comment by Felopater-Melika** [comment]
turns out i just needed to turn on xwayland on and that just solved the issue after logging out and in

**Comment by alexpetrean80** [comment]
sorry to revive a dead issue, but care to elaborate how did you exactly turn xwayland on?

**Comment by Felopater-Melika** [comment]
I had it turned off funny enough so the default i think is it's turned on for hyprland but i just had it off because i was messing around i had just installed it back then

**Comment by alexpetrean80** [comment]
ah okay, it's hyprland specific. I use gnome and couldn't see a "xwayland" setting anywhere

**Comment by Ifaen** [comment]
Just to add, in case someone stumbles upon your same issue but is not because of XWayland (at least it wasn't for me), but in reality a cache issue, as the [Wiki of Spotify in NixOS](https://nixos.wiki/wiki/Spotify) says; if you "libcurl-gnutls.so.4: no version information available" like you had, then you need to remove or clean the $HOME/.cache/spotify folder.
It happened to me when I tried while upgrading from NixOS 23.11 to 24.05 in my flake.
