### ISSUE TITLE
oculante: GLib-GIO-ERROR **: 18:06:07.730: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#263176]
### Describe the bug
When i click the folder icon in the top left, no File Picker is displayed and `oculante` crashes about half a second later with

```
(oculante:70227): GLib-GIO-ERROR **: 18:06:07.730: No GSettings schemas are installed on the system
fish: Job 1, 'oculante IMG_20221117_133830.jpg' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I am on NixOS unstable and running `hyprland` with a minimal setup.

I guess that i have to enable some NixOS option but i don't know which one and i think that the package should work out of the box.

### Notify maintainers
@dit7ya @figsoda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11pre537656.7c9cc5a6e5d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - channels(sperber): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
what is your "minimal setup"? what's in the config?

**Comment by Schweber** [comment]
I don't know what settings are relevant as an answer to your question. I'm using gtk programs etc. without issues and wanted to convey that i don't have KDE or Gnome desktop installed so there might be something missing that is already installed by default on many systems.
