### ISSUE TITLE
Package request: llm-ls

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#263181]
**Project description**
https://github.com/huggingface/llm-ls

The goal of llm-ls is to provide a common platform for IDE extensions to be build on. llm-ls takes care of the heavy lifting with regards to interacting with LLMs so that extension code can be as lightweight as possible.

it has extensions for vscode/neovim already. 

I have no feedback on this software at all but seemed like something I want to try. Maybe it doesn't work well enough to get merged in nixpkgs but I would like to try it with codellama in neovim

**Metadata**

* homepage URL: https://github.com/huggingface/llm-ls
* source URL: https://github.com/huggingface/llm-ls
* license: apache2 
* platforms: unix I think

**Comment by elliottneilclark** [comment]
This is interesting as llm-ls is the easiest route to get VSCode assistant that's self-hosted on nix (most require running a Linux binary downloaded from the web)
