### ISSUE TITLE
Armagetronad Segmentation fault

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#263244]
### Describe the bug
Armagetronad no longer runs, I don't remember the last time the game was properly working, but maybe one of its depedencies changed in `nixpkgs` resulting in this. Interestingly, the game still works if you use `valgrind` as in `valgrind armagetronad` in a shell `nix-shell -p valgrind`.

Doing `appimage-run ~/Downloads/ArmagetronAdvanced-0.2.9.1.1.AppImage` also works as exptected.

Is this reproducible?
```bash
~ ❯ armagetronad
Internal Error: Internal error in void tMemManager::Remove(memblock*) in tools/tMemManager.cpp:824 :
        Element is not in this heap!
Please send a Bug report!
Segmentation fault (core dumped)
```
Note: In most cases, I only get `Segmentation fault (core dumped)` printed to the console

### Notify maintainers

@numinit 

### Metadata

```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - channels(mathiassven): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by numinit** [comment]
Should be fixed in https://github.com/NixOS/nixpkgs/pull/263675. Thanks for the report. I'd like to make a NixOS module with an integration test between the dedicated server and client in the vein of OpenArena.

**Comment by numinit** [comment]
Further improved by #263765.

**Comment by MathiasSven** [comment]
Can confirm, `nix run github:numinit/nixpkgs/armagetronad#armagetronad` no longer crashes. I previously tried running it with this overlay:
```nix
armagetronad = self: super: {
  armagetronad = super.armagetronad.overrideAttrs (oldAttrs: {
    src = pkgs.fetchurl {
      url = "https://launchpad.net/armagetronad/0.2.9/0.2.9.1.1/+download/armagetronad-0.2.9.1.1.tbz";
      hash = "sha256-9hfecA7PHdEfdeKTLudHlnKREjUtXKuqK8R5rdff/TI=";
    };
  });
}
```
However, it would still segfault. So the issue must have been `--enable-memmanager` as mentioned in your PR.

**Comment by numinit** [comment]
I've reported this crash upstream to get a better handle on it. In the meantime the PR should fix it by disabling the memory manager.

**Comment by numinit** [comment]
Looks like the --enable-memmanager is no longer a recommended config, because it was for the early 2000s when malloc was slow and it was hard to identify leaks. We now explicitly --disable-memmanager now.
