### ISSUE TITLE
Calibre crashes xdg-wayland-hyprland-portal

### ISSUE THREAD

**Issue by LamprosPitsillos** [NixOS/nixpkgs#263220]
### Describe the bug
`Calibre` version in unstable crashes `xdg-wayland-portal-hyprland` in unstable.

https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/121#issuecomment-1776214291

```
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
https://github.com/NixOS/nixpkgs/pull/261451/files#diff-dbe8de7a88663a45233cf14e5665d96390ddf5e4e3b3b7b8371e9d563af3631e

Looks like the portal impl has already been updated
