### ISSUE TITLE
Python: support GitHub in update script

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#26320]
## Issue description

The update script uses the PyPI API to determine whether updates are available and uses the hashes it provides. 

Some expressions do not use `fetchPyPi` or `fetchurl` with an url pointing to PyPI`. In those cases, we shouldn't use the PyPI API. 

Therefore, an initial check should be included that checks what kind of repository is used. Then, we can also support GitHub for the few scripts that use it.

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by rhendric** [comment]
I assume #99635 should have closed this; reopen if I'm wrong.
