### ISSUE TITLE
Update request: nodejs_18 18.18.0 → 18.18.2

### ISSUE THREAD

**Issue by danielwaterworth** [NixOS/nixpkgs#263205]
- Package name: nodejs_18
- Latest released version: 18.18.2
- Current version on the unstable channel: 18.18.0
- Current version on the stable/release channel: 18.17.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@goibhniu @gilligan @cko @marsam

I'm asking because of https://github.com/nodejs/node/issues/49911 which affects the unstable packaged version.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by IogaMaster** [comment]
This has been part of unstable for 3 weeks.
https://github.com/NixOS/nixpkgs/commit/bf85265bb302cdfe137e06bb207cb63aaaa726e8

**Comment by IogaMaster** [comment]
I think it was also backported to 23.05, let me check
