### ISSUE TITLE
Create `systemd.user.packages` option

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#263248]
`systemd.packages` allows one to use upstream-provided unit files for systemd-wide systemd units. `systemd.user.packages` would be the analogous thing for user-specific systemd units, but it doesn't yet exist.

**Comment by eclairevoyant** [comment]
́systemd.packages` works for user units as well.

**Comment by Ericson2314** [comment]
@eclairevoyant Oh hmm. Maybe I don't understand what goes on when there is a combination of a package-provided and NixOS-defined user unit?
