### ISSUE TITLE
Jami (QT): GLib-GIO-ERROR - No GSettings schemas

### ISSUE THREAD

**Issue by jakimfett** [NixOS/nixpkgs#263383]
### Describe the bug
The Jami client crashes with this error:
`GLib-GIO-ERROR : No GSettings schemas are installed on the system`

### Steps To Reproduce
1. Install Jami via `nix-env -i jami`
2. Run Jami: `jami`
3. Jami crashes with error.

### Expected behavior
The Jami client should load as expected.

### Additional context
Found references to how to make this work, unsure which if any are workable approaches:
 - https://discourse.nixos.org/t/failure-appimage-run-with-gsetting/4403/2
 - https://github.com/NixOS/nixpkgs/issues/181500

Error log:
```
Using Qt runtime version: 6.5.2
"notify server name: lxqt-notificationd, vendor: lxqt.org, version: 1.3.0, spec: 1.2"
"Using locale: en_US"
No accounts to migrate
Screen saver dbus interface:  "org.freedesktop.ScreenSaver"
Can't update current account info data for ""
Main window loaded using OpenGLRhi
NetworkManager client initialized, version:  1.42.8 , daemon running: yes , networking enabled: yes
primary network connection: <id truncated> default:  yes

(jami:5027): GLib-GIO-ERROR **: 10:31:21.371: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)

```
### Notify maintainers
@linsui

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[jakimfett@5trix:~/]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.05 (Stoat), 23.05.4172.bd1cde45c778`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by jakimfett** [comment]
Same error on KDE Plasma:
```
Using Qt runtime version: 6.5.2
"notify server name: Plasma, vendor: KDE, version: 5.27.7, spec: 1.2"
"Using locale: en_US"
No accounts to migrate
Screen saver dbus interface:  "org.freedesktop.ScreenSaver"
Can't update current account info data for ""
Main window loaded using OpenGLRhi
qt.dbus.integration: QDBusConnection: name 'cx.ring.Ring' had owner '' but we thought it was ':1.74'
NetworkManager client initialized, version:   , daemon running: no , networking enabled: no
no primary network connection detected, check network settings

(jami:15941): GLib-GIO-ERROR **: 11:05:54.329: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

```console
[jakimfett@obsidian:~/hub/dev/mintotp]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.05 (Stoat), 23.05.4448.5550a85a087c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05.4448.5550a85a087c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by linsui** [comment]
I can't reproduce the problem on GNOME. Not sure how I can test it.

**Comment by jakimfett** [comment]
Maybe a virtual machine? LXQT is one of the installer options so setting up a VM should be straightforward.

**Comment by jakimfett** [comment]
Maybe a virtual machine? LXQT is one of the installer options so setting up a VM should be straightforward.

**Comment by Artturin** [comment]
> I can't reproduce the problem on GNOME. Not sure how I can test it.

`env -i HOME="$HOME" DISPLAY="$DISPLAY" WAYLAND_DISPLAY="$WAYLAND_DISPLAY" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" QT_QPA_PLATFORM=xcb ./result/bin/jami ` to get rid of gtk impurities in the env

@jakimfett you can fix by wrapping with the gtk wrapper, see the qt app example https://ryantm.github.io/nixpkgs/languages-frameworks/gnome/#ssec-gnome-common-issues-double-wrapped

**Comment by Artturin** [comment]
@jakimfett will you submit a PR?
