### ISSUE TITLE
Package request: proxmox-backup-server

### ISSUE THREAD

**Issue by eyduh** [NixOS/nixpkgs#263369]
**Project description**

Backup server made by proxmox. Allows [proxmox backup clients](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/backup/proxmox-backup-client/default.nix#L88) to send their backups either encrypted over untrusted networks or unencrypted over trusted networks. Since the client is already in the nixpkgs store and built from the same git it would be nice if the server also is available.

**Metadata**

* homepage URL: https://pbs.proxmox.com
* source URL: https://git.proxmox.com/?p=proxmox-backup.git
* source URL: https://github.com/proxmox/proxmox-backup
* license: ?
* platforms: linux

**Comment by jfvillablanca** [comment]
possible duplicate https://github.com/NixOS/nixpkgs/issues/230147

**Comment by eyduh** [comment]
yup
