### ISSUE TITLE
qt5: .qhelpgenerator-wrapped file not found

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#26347]
## Issue description

I downloaded Qt5 from the nix-channel and it seems some files are missing.

/nix/store/w6q940m6s7hynyjnl6vw0w8r1fwxrnwl-qt-5.8.0/bin/qhelpgenerator is a symbolic link to /nix/store/7sjhg5d7yd9wqjh6grzxszbsb2yc526m-qttools-5.8.0-dev/bin/qhelpgenerator which is a shell script that has the linke:

    exec -a "$0" "/nix/store/vn9dzrwvw0b4by6ahgcs9j7j514afw1p-qttools-5.8.0/bin/.qhelpgenerator-wrapped"  "${extraFlagsArray[@]}" "$@"

but the .qhelpgenerator-wrapped file does not exist.

This is with the latest nixpkgs (commit b520c30d9ece95b8c64caf6691db99d486e08717 )

## Technical details

$  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by Artturin** [comment]
not a issue anymore 
```
nix-repl> :bl qt5.env "blah" [ qt5.qttools ]
$ readlink -f ./repl-result-out/bin/qhelpgenerator
/nix/store/l907a612vwy2kxsg52kjzip2vcsd4ipz-qttools-5.15.8-dev/bin/qhelpgenerator
```
