### ISSUE TITLE
Build failure: ghostscriptX on x86_64-darwin

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#263489]
### Steps To Reproduce

1. `nix-build -A ghostscriptX --system x86_64-darwin`

### Build log

See https://hydra.nixos.org/build/239212124; relevant excerpt:

```
error: install_name_tool: changing install names or rpaths can't be redone for: /nix/store/23i8n6x45h9p49rd1cw3xjjpri0svh1d-ghostscript-with-X-10.02.0/lib/libgs.dylib.10 (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

### Additional context

- Hydra is (afaik) mostly Rosetta 2 for x86_64-darwin, but this *does* fail on native x86_64-darwin
- Just downgrading ghostscript to 10.01.2 (tested at 8efd5d1e283604f75a808a20e6cde0ef313d07d4) is enough to make the build succeed again (so presumably https://github.com/NixOS/nixpkgs/pull/254240 is the cause)

### Notify maintainers

@viric 

### Metadata

Hydra

**Comment by xworld21** [comment]
this is breaking TeX Live (medium and full) on darwin
