### ISSUE TITLE
Build failure: guitarix

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#263512]
### Steps To Reproduce

1. build guitarix

### Build log

https://paste.sr.ht/~toastal/d3252fcbcef714d82767059404eb2358fe20251d

### Notify maintainers

@astsmtl @cillianderoiste 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix shell nixpkgs#nix-info --command nix-info -m 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(toastal): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
closing as fix was merged
