### ISSUE TITLE
Build failure: cue

### ISSUE THREAD

**Issue by selfuryon** [NixOS/nixpkgs#263584]
### Steps To Reproduce

1. Run `nix build nixpkgs#cue` in the latest `nixpkgs-unstable`

### Build log

[Log](https://gist.github.com/selfuryon/62752225953646737abec575fe96880d). Failed some tests during the build.

### Notify maintainers

@aaronjheng

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231024.8efd5d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by lovesegfault** [comment]
cc. @RaitoBezarius @nikstur 

This breaks bootspec and thus lanzaboote on the latest `nixos-unstable`

**Comment by RaitoBezarius** [comment]
Only if you enable validation but yeah.
