### ISSUE TITLE
Build failure: libretro.beetle-snes (aka mednafen-snes)

### ISSUE THREAD

**Issue by amarshall** [NixOS/nixpkgs#263622]
### Steps To Reproduce

1. `nix-build -A libretro.beetle-snes`

### Build log

Most common error is along the lines of

```
error: 'size_t strlcat(char*, const char*, size_t)' redeclared inline without 'gnu_inline' attribute
```

- libretro.beetle-snes.aarch64-linux: https://hydra.nixos.org/build/239037065
- libretro.beetle-snes.x86_64-linux: https://hydra.nixos.org/build/239206305

### Additional context

Possibly related to glibc update? Can reproduce failure on local x86_64-linux.

### Notify maintainers

@aanderse @edwtjo @MP2E @thiagokokada 

### Metadata

Hydra

**Comment by khaneliman** [comment]
Related https://github.com/NixOS/nixpkgs/issues/263507

**Comment by thiagokokada** [comment]
This core itself seems to be kinda old and not updated anymore. Also not sure how interesting it is, considering it is based in a old version of bsnes.

Maybe we can just remove it? Is there any reason you want to use it, or it is just an issue because it makes `retroarchFull` fail?

**Comment by thiagokokada** [comment]
Created a PR to remove it: https://github.com/NixOS/nixpkgs/pull/263751

Would appreciate some reviews.
