### ISSUE TITLE
Package request: discord-canary

### ISSUE THREAD

**Issue by yuri-potatoq** [NixOS/nixpkgs#263647]
**Discord Canary**

I just don't know why we can update the non-linux version of canary but not both.
There is some compatibility issue?
ref: https://github.com/NixOS/nixpkgs/commit/315a7b36caa56f11d0428f79ed686c494eb85531

**Metadata**

* Existent package: https://github.com/NixOS/nixpkgs/commit/315a7b36caa56f11d0428f79ed686c494eb85531
* platforms: unix, linux, darwin, ...

**Comment by Shawn8901** [comment]
Can you explain a bit more what you mean? The commit your are referring is updating the dawin canary and belongs to [this PR](https://github.com/NixOS/nixpkgs/pull/262164/files) that also updates the Linux Variant, but just not in one commit. 
So at least I am not sure what is the request and a bit more explanation may help (at least me).

**Comment by yuri-potatoq** [comment]
> Can you explain a bit more what you mean? The commit your are referring is updating the dawin canary and belongs to [this PR](https://github.com/NixOS/nixpkgs/pull/262164/files) that also updates the Linux Variant, but just not in one commit. So at least I am not sure what is the request and a bit more explanation may help (at least me).

I see, my fault. I didn't search for related PRs.
Maybe i should have opened a forum thread instead, sorry.

Thanks for help me.
