### ISSUE TITLE
nixos/manual: lengthScale default value formatting depends on nix version

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#263730]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build nixos/release.nix -A manual.x86_64-linux
```

The documentation in `share/doc/nixos/options.html` will have '1' as default value for `opt-services.wyoming.piper.servers._name_.lengthScale` when building with nix 2.3.7, while it has '1.0' when building with nix 2.17.1.

**Comment by Ericson2314** [comment]
Is this the difference in floating formatting that happened?

**Comment by raboof** [comment]
I wasn't aware of that - sounds like it!

Perhaps it's not super important to be reproducible across nix versions, and we should specify using consistent nix versions as a prerequisite for reproducibility of the manual/ISO/etc?

**Comment by SuperSandro2000** [comment]
probably https://github.com/NixOS/nix/issues/3077 or similar

**Comment by raboof** [comment]
> Perhaps it's not super important to be reproducible across nix versions, and we should specify using consistent nix versions as a prerequisite for reproducibility of the manual/ISO/etc?

I guess so then, closing
