### ISSUE TITLE
checksec expects `sed` at `/bin/sed` on NixOS

### ISSUE THREAD

**Issue by msanft** [NixOS/nixpkgs#263720]
### Describe the bug
The `checksec` package expects `sed` to be available at `/bin/sed`, which is not fulfilled on NixOS unless in an FHS environment.

### Steps To Reproduce
1. `nix shell nixpkgs#checksec`
2. `checksec /bin/sh`

### Expected behavior
Security information about the binary being checked should show up.

### Notify maintainers
@thoughtpolice 
@globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231016.ca012a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by msanft** [comment]
#239085 fixes this.

**Comment by katexochen** [comment]
Closed with https://github.com/NixOS/nixpkgs/pull/267304
