### ISSUE TITLE
python3Packages/rpi-gpio2: incompatible with gpiod

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#263759]
### Describe the bug

The version of rpi-gpio2 on nixos-unstable (as of 8efd5d1e283604f75a808a20e6cde0ef313d07d4) appears to be incompatible with the version of gpiod at the same point

### Steps To Reproduce

```
$ nix-shell -p "python3.withPackages(p: [ p.rpi-gpio2 ])"
(...)
$ python3
(...)
>>> from RPi import GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/vdfycwbxj5704a2s6mcfg94f73wpqgjj-python3-3.11.5-env/lib/python3.11/site-packages/RPi/GPIO/__init__.py", line 8, in <module>
    from RPi.core import\
  File "/nix/store/vdfycwbxj5704a2s6mcfg94f73wpqgjj-python3-3.11.5-env/lib/python3.11/site-packages/RPi/core.py", line 59, in <module>
    LOW  = gpiod.Line.ACTIVE_LOW
           ^^^^^^^^^^
AttributeError: module 'gpiod' has no attribute 'Line'. Did you mean: 'line'?
>>> 
```

### Expected behavior
Load the module successfully

### Notify maintainers

/cc @onny @lopsided98 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/aengelen/nixpkgs`
```

**Comment by raboof** [comment]
I wonder if we should keep/re-introduce a gpiod 1.x to nixpkgs until rpi-gpio2 supports gpiod 2.x?

**Comment by raboof** [comment]
I have since updated the component I was using rpi-gpio2 with to use libgpiod directly (https://github.com/thecode/ha-rpi_gpio/pull/212).

Should we mark this component broken in nixpkgs, or perhaps just remove it entirely? It doesn't appear to be used anywhere within nixpkgs. /cc @onny

**Comment by crazyminecuber** [comment]
I got this error today as well, so this issue is still relevant. What is the simplest way to toogle a GPIO pin on NixOS as of today, then?

**Comment by crazyminecuber** [comment]
But I guess I could attempt the trivial fix to change out `libgpiod` to `libgpiod_1` in the package definition. That should be the correct fix right?
