### ISSUE TITLE
Update request: helix 23.05 → 23.10

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#263791]
- Package name: helix
- Latest released version: 23.10

- Current version on the unstable channel: 23.05
- Current version on the stable/release channel: 23.05

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@danth @yusdacra @zowoq 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by meatcar** [comment]
It's been updated and merged, see https://github.com/NixOS/nixpkgs/pull/263391. It should land in `nixos-unstable` [soon](https://nixpk.gs/pr-tracker.html?pr=263391).
