### ISSUE TITLE
Build failure: glaxnimate

### ISSUE THREAD

**Issue by Tiggax** [NixOS/nixpkgs#263731]
### Steps To Reproduce

I wanted to update the system and got the error.
then tried with `nix shell nixpkgs#glaxnimate` and got the same error

### Build log

```
error: builder for '/nix/store/03dwgflycwl7p03wdhcfy8ji66kxp006-glaxnimate-0.5.1.drv' failed with exit code 2;
       last 10 log lines:
       >       |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > In file included from /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/include/python3.11/Python.h:96:
       > /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/include/python3.11/sysmodule.h:14:38: note: declared here
       >    14 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) PySys_SetArgvEx(int, wchar_t **, int);
       >       |                                      ^~~~~~~~~~~~~~~
       > make[2]: *** [external/QtAppSetup/src/CMakeFiles/QtAppSetup.dir/build.make:300: external/QtAppSetup/src/CMakeFiles/QtAppSetup.dir/app/scripting/python/python_engine.cpp.o] Error 1
       > make[2]: *** Waiting for unfinished jobs....
       > make[2]: *** [external/QtAppSetup/src/CMakeFiles/QtAppSetup.dir/build.make:314: external/QtAppSetup/src/CMakeFiles/QtAppSetup.dir/app/scripting/python/register_machinery.cpp.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:528: external/QtAppSetup/src/CMakeFiles/QtAppSetup.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/03dwgflycwl7p03wdhcfy8ji66kxp006-glaxnimate-0.5.1.drv'.

```

### Notify maintainers
@tobiasBora 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231024.8efd5d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(tiggax): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tobiasBora** [comment]
Thanks, I can confirm the bug, I guess some package upgrade broke compatibility. I’ll try to see if v0.5.4 has the same issue.

**Comment by tobiasBora** [comment]
So when compiling v0.5.4, the compilation works, but it fails to install the translation files. I’m not sure to see what is wrong, I reported an issue here https://gitlab.com/mattbas/glaxnimate/-/issues/648

**Comment by tobiasBora** [comment]
This is fixed in https://github.com/NixOS/nixpkgs/pull/264387, can you try it?

**Comment by Tiggax** [comment]
I'm quite new to nix, so correct me if i did anything wrong.
Downloading your branch, and running: 
`nix-build -A glaxnimate` 
seems to build a successful application.
Thanks :smile:

**Comment by tobiasBora** [comment]
Cool! You can also use nixpkgs-review, it might be easier to use.

Usually we close issues once the PR is merged, so I'll reopen (we also need to see if it need to be backported). Can you maybe comment on this PR saying you tried it succesfully ? It would help it being merged quickly. I'll add you as a reviewer.
