### ISSUE TITLE
Obsidian does not work with Electron 25 with `NIXOS_OZONE_WL`

### ISSUE THREAD

**Issue by vifino** [NixOS/nixpkgs#263764]
### Describe the bug
When running unstable with `NIXOS_OZONE_WL`, Obsidian 1.4.16 displays an invisible window for a few seconds and then crashes.

This is related to the switch to Electron 25.
Overriding it with electron_24 makes it launch just fine.

### Steps To Reproduce
1. Run nixos-unstable with Wayland and `NIXOS_OZONE_WL=1`
2. Try to launch Obsidian

### Expected behavior
It should show the window and work like with electron 24.

### Screenshots
Can't screenshot something that show anything.

### Notify maintainers

@claudiiii (bumped obsidian to electron 25)

Unsure who else..

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7-xanmod1, NixOS, 23.11 (Tapir), 23.11.20231025.f77757f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by claudiiii** [comment]
Hi, sorry for breaking Obsidian. Of course, I forgot to test on Wayland 🙃.

I already found two matching bug reports:
- https://forum.obsidian.md/t/wayland-appimage-crash/66989
- https://github.com/flathub/md.obsidian.Obsidian/issues/197

So I think it makes sense to revert to Electron 24.
The only problem I see is that Electron 24 has no further support and was [marked with known vulnerabilities in this commit last week](https://github.com/NixOS/nixpkgs/commit/359dc17237b1ca225fddb74443e9ccdae1984ef5).

Everyone not on Wayland can override the Electron version locally.

Also pinging the people who tested the pr: @sdht0 @qbit @kashw2

**Comment by sdht0** [comment]
Given the security concerns, I suggest leaving the default electron to what upstream uses.

Those on wayland will have to  both override electron and [add it to `permittedInsecurePackages`](https://discourse.nixos.org/t/how-to-permit-insecure-package-as-input-to-another-package/19960). Something like the following snippets works for me:

```nix
# In overlay
(final: prev: {
  obsidian-wayland = prev.obsidian.override {electron = final.electron_24;};
})
# In config
nixpkgs.config = {
  allowUnfree = true;
  permittedInsecurePackages = [
    "electron-24.8.6"
  ];
};
```

**Comment by eddyb** [comment]
Is there any chance we could somehow confirm whether this is the same bug as:
- https://github.com/NixOS/nixpkgs/issues/237978
  <sub>(I suppose if someone can repro w/ `vscodium` instead of `vscode`, they should be able to get debuginfo for `electron_25` from nixpkgs and compare the crashes in both cases)</sub>

On my end, I've had to start running them both via e.g. `env WAYLAND_DISPLAY= obsidian --disable`, so I'm worried all apps that eventually upgrade to Electron 25 will hit this *and* there might not be a fix for a while...

**Comment by eddyb** [comment]
Likely relevant:
- https://github.com/electron/electron/issues/39449

**Comment by eddyb** [comment]
Regarding the Electron 25 crashes that affected VSCode, I posted this elsewhere:
> I'm increasingly confident Electron 27 (used by VSCode Insiders) fixed the crashes *I* was observing, and I was even able to use my reproducer automation (KWin Window Rules to force maximization states without manually interacting with an app) to make stable VSCode (on Electron 25) not crash.
>
> For both versions of VSCode I was able to get working again, I can confirm fractional scaling support (crisp pixel-perfect font rendering only when a window is fully contained within one monitor, that becomes slightly fuzzy while transiting between monitors).
And I also tested closing/opening windows, and all of that with `window.titleBarStyle` set to both `"native"` and `"custom"` (I normally use `"custom"` but for my crashes I never saw it make a difference).
>
> I wrote up all the details in a much longer comment on the Electron issue: https://github.com/electron/electron/issues/39449#issuecomment-1871357712

That workaround seems to also work for Obsidian (on Electron 25), but at this point it seems inevitable that we'll get Obsidian based on Electron 27, so this feels too little too late on my part.

**Comment by sdht0** [comment]
With #290892 merged, obsidian now depends on electron v28. Does that solve this issue?

**Comment by qoh** [comment]
> With #290892 merged, obsidian now depends on electron v28. Does that solve this issue?

It does for me. Obsidian from master just starts with NIXOS_OZONE_WL set (also checked DISPLAY unset).

**Comment by BenCarmichael01** [comment]
Yeh fixed for me too 👍
