### ISSUE TITLE
virt-manager does not start

### ISSUE THREAD

**Issue by mt-caret** [NixOS/nixpkgs#26387]
## Issue description

Running virt-manager gives the following error message:

```
Traceback (most recent call last):
  File "/nix/store/2iiz3nfs5x9wbprf0mfiahir0hzibbgf-virt-manager-1.4.1/share/virt-manager/virt-manager", line 29, in <module>
    import gi
ImportError: No module named gi
```

### Steps to reproduce

`$ virt-manager`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.09pre108282.53835c93cb (Hummingbird)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.9
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.09pre108282.53835c93cb"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = true

**Comment by FRidh** [comment]
Did you see/test https://github.com/NixOS/nixpkgs/pull/26375?

**Comment by mt-caret** [comment]
Yeah, judging from the /nix/store hash, seems like a duplicate. I'll close this.
