### ISSUE TITLE
BOINC: WUProp tasks fail

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#26389]
## Issue description

Stderr output
```
<core_client_version>7.4.42</core_client_version>
<![CDATA[
<message>
process exited with code 2 (0x2, -254)
</message>
<stderr_txt>
Process creation (../../projects/wuprop.boinc-af.org/data_collect_v4_419_x86_64-pc-linux-gnu__nci) failed: Error -1, errno=2
execv: No such file or directory

</stderr_txt>
]]>
```
Source: https://wuprop.boinc-af.org/result.php?resultid=71600227

### Steps to reproduce

1. install BOINC service
```
  services.boinc.enable = true;
  services.boinc.allowRemoteGuiRpc = true;
```
2. add [WUProp](https://wuprop.boinc-af.org/) project
3. let one task complete and see result

## Technical details

On my branch https://github.com/NixOS/nixpkgs/pull/25603 but shouldn't matter.

* System: NixOS 17.09.git.4979803 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.03.1123.4a7a03913d"
* Sandboxing enabled: build-use-sandbox = false

**Comment by lheckemann** [comment]
Presumably the WUProp project is compiled to run on "normal" distros and you'd need to patch the executable using patchelf, or compile it for nixos, before running it. I don't know if BOINC allows that sort of thing automatically or at all…

**Comment by kierdavis** [comment]
This might be fixed by #30908.

**Comment by davidak** [comment]
Waiting for https://github.com/NixOS/nixpkgs/pull/30908 to get merged.

**Comment by davidak** [comment]
I can confirm that it is fixed.

![Screenshot from 2019-07-22 15-30-13](https://user-images.githubusercontent.com/91113/61636342-b77c6c00-ac95-11e9-9553-95573cb4f943.png)

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173165.55b8860aa20 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(davidak): `""`
 - channels(root): `"nixos-19.03.173165.55b8860aa20, nixos-hardware, nixos-unstable-19.09pre185259.362be9608c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
