### ISSUE TITLE
wayland compiler error

### ISSUE THREAD

**Issue by gracewyc** [NixOS/nixpkgs#26385]
## Issue description
When I use gcc to compile the following code, I encountered the following error:

```c
static void
global_registry_handler(void *data, struct wl_registry *registry, uint32_t id,const char *interface, uint32_t version)
{
    printf("Got a registry event for %s id %d\n", interface, id);
    if (strcmp(interface, "wl_compositor") == 0)
        compositor = wl_registry_bind(registry, 
                      id, 
                      &wl_compositor_interface, 
                      1);
}`
```

The error is as follows:
```
undefined reference to `wl_proxy_marshal_constructor_versioned'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce
```shell
gcc main.c -o out -lwayland-client -lwayland-server -lwayland-cursor -lwayland-egl
```
   
Thank you
## Technical details

* System: ubuntu16.04;    wayland-version 1.13.0

**Comment by gracewyc** [comment]
`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wayland-client.h>

struct wl_display *display = NULL;
struct wl_compositor *compositor = NULL;
struct wl_registry *registry = NULL;

static void
global_registry_handler(void *data, struct wl_registry *registry, uint32_t id,const char *interface, uint32_t version)
{
    printf("Got a registry event for %s id %d\n", interface, id);
    if (strcmp(interface, "wl_compositor") == 0)
        compositor = wl_registry_bind(registry, 
                      id, 
                      &wl_compositor_interface, 
                      1);
}

static void
global_registry_remover(void *data, struct wl_registry *registry, uint32_t id)
{
    printf("Got a registry losing event for %d\n", id);
}

static const struct wl_registry_listener registry_listener = {
    global_registry_handler,
    global_registry_remover
};


int main(int argc, char **argv) {

    display = wl_display_connect(NULL);
    if (display == NULL) {
    fprintf(stderr, "Can't connect to display\n");
    exit(1);
    }
    printf("connected to display\n");

    struct wl_registry *registry = wl_display_get_registry(display);
    wl_registry_add_listener(registry, &registry_listener, NULL);

    wl_display_dispatch(display);
    wl_display_roundtrip(display);

    if (compositor == NULL) {
    fprintf(stderr, "Can't find compositor\n");
    exit(1);
    } else {
    fprintf(stderr, "Found compositor\n");
    }

    wl_display_disconnect(display);
    printf("disconnected from display\n");
    
    exit(0);
}`

**Comment by lheckemann** [comment]
Works for me in `nix-shell -p wayland gcc`, compiling with `gcc main.c -lwayland-client`. It doesn't seem to use any symbols from `-lwayland-server`, and `-lwayland-egl` isn't found. Are you using nix at all for this?

**Comment by vcunat** [comment]
There might be some mixup with impure paths, especially as it's on a system with populated `/usr/**`.  The `wl_proxy_marshal_constructor_versioned` symbol is only present in newer wayland versions (as we found in #16779).

**Comment by lheckemann** [comment]
Since we haven't got any feedback from @gracewyc confirming that this even involves nix, I suggest closing this.
