### ISSUE TITLE
Errors occurred while installation  

### ISSUE THREAD

**Issue by Chukhai** [NixOS/nixpkgs#26382]
Here is the output....
> tsuhoi-Inspiron-7520% sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
> Cloning Oh My Zsh...
> 正克隆到 '/home/tsuhoi/.oh-my-zsh'...
> remote: Counting objects: 831, done.
> remote: Compressing objects: 100% (700/700), done.
> remote: Total 831 (delta 14), reused 775 (delta 10), pack-reused 0
> 接收对象中: 100% (831/831), 567.68 KiB | 448.00 KiB/s, 完成.
> 处理 delta 中: 100% (14/14), 完成.
> Looking for an existing zsh config...
> Found ~/.zshrc. Backing up to ~/.zshrc.pre-oh-my-zsh
> Using the Oh My Zsh template file and adding it to ~/.zshrc
>          __                                     __   
>   ____  / /_     ____ ___  __  __   ____  _____/ /_  
>  / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
> / /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
> \____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
>                         /____/                       ....is now installed!
> 
> 
> Please look over the ~/.zshrc file to select plugins, themes, and options.
> 
> p.s. Follow us at https://twitter.com/ohmyzsh.
> 
> p.p.s. Get stickers and t-shirts at http://shop.planetargon.com.
> 
> /home/tsuhoi/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
> /home/tsuhoi/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:80: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:93: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:100: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:119: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:163: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:166: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:168: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:182: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:193: command not found: compdef
And every time I launch the terminal, it shows
> /home/tsuhoi/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
> /home/tsuhoi/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:80: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:93: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:100: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:119: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:163: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:166: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:168: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:182: command not found: compdef
> /home/tsuhoi/.oh-my-zsh/plugins/git/git.plugin.zsh:193: command not found: compdef
And no matter which theme I use, it never works.

System: Ubuntu 17.04

Anyone can help me with the problem？ T_T

**Comment by lverns** [comment]
Maybe I'm missing something, but I don't see anything related to Nixpkgs in what you wrote. Maybe you meant to post the question on the [the oh-my-zsh GitHub Page](https://github.com/robbyrussell/oh-my-zsh/)?
