### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by dougkeiller** [NixOS/nixpkgs#264085]
### Describe the bug

Attempt nixos-rebuild switch and get an error

### Steps To Reproduce
1. nixos-rebuild switch --verbose
2. ...
3. ...

### Expected behavior

Expect a nixos-rebuild switch

Log goes through entire process, but at end get an error:

$ nix-env -p /nix/var/nix/profiles/system --set /nix/store/fsj47fa8cnx8wvqaxyks2w69vbk40vyx-nixos-system-nixos-23.11pre541036.63678e9f3d3a
error: creating symlink from '/nix/var/nix/profiles/.0_system' to 'system-83-link': Permission denied

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/128188043/c446e371-b676-4eb3-9ae0-5182416e077a)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11pre537656.7c9cc5a6e5d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"23.05-23.05, nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by kashw2** [comment]
Have you attempted using `sudo`?

**Comment by eclairevoyant** [comment]
The `boot` or `switch` subcommands must be run as root or with `--use-remote-sudo` for obvious reasons.

**Comment by dougkeiller** [comment]
Sorry, guys! Apologies for the obvious question...forgot to do that.

As a clearly non-technical NixOS user, I'm super happy and grateful for your work on this!
