### ISSUE TITLE
Update request: freedv  1.9.3 → 1.9.4

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#264021]
- Package name: freedv
- Latest released version: 1.9.4
- Current version on the unstable channel: 1.9.3
- Current version on the stable/release channel: 1.8.9
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@illdefined  
@wegank  

https://github.com/drowe67/freedv-gui/releases/tag/v1.9.4

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by wegank** [comment]
> * [x]  Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

No, please double-check the pull requests.

Closed by #263816.

**Comment by luzpaz** [comment]
I could of swore i did. Sorry.
