### ISSUE TITLE
Add syncthing options to separate database and config

### ISSUE THREAD

**Issue by anuramat** [NixOS/nixpkgs#264029]
## Issue description
Since Syncthing 1.5, it's possible to store database and config separately [[link]](https://docs.syncthing.net/users/config.html). This can be done using `--config` and `--data` arguments, for example like this:
```nix
extraFlags = [
  "--config=/home/${username}/.config/syncthing"
  "--data=/home/${username}/.local/share/syncthing"
];
```
But it conflicts with the non-empty `--home` option, that is set by `configDir` option:
```
WARNING: Command line options: --home must not be used together with --config and --data
```
## Proposed solution
- add new options `homeDir` and `databaseDir`
- set the following defaults:
```
homeDir = dataDir + "/.config/syncthing";
databaseDir = homeDir;
configDir = homeDir;
```
- instead of passing `--home=${configDir}`, pass `--data=${databaseDir}` and `--config=${configDir}`

## JIC 
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4335.898cb2064b6e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - channels(anuramat): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by WillPower3309** [comment]
#264753
