### ISSUE TITLE
wireguard peer fails to connect after upgrade from 23.05 ot 23.11 ( unstable )

### ISSUE THREAD

**Issue by evilbulgarian** [NixOS/nixpkgs#264076]
### Describe the bug
working wire guard setup in 23.05 client > server after upgrade to unstable stops working unless a `systemctl restart wireguard-\*` is done after which connection is established again. Ivan in irc channel also verified the issue and told me about fix.

### Steps To Reproduce
1. start with working wireguard setup on 23.05
2. update nixpkgs to 23.11
3. reboot

### Expected behavior
get wireguard tunnel from a clean reboot

### Notify maintainers
@bjornfor @SEIAROTg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/store/jxqmbf290yk88cil7h6yp9hvkxx38ddb-source`
```

```
Oct 28 19:42:58 monroe systemd[1]: Starting WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=)...
Oct 28 19:42:58 monroe wireguard-wg0-peer-GaRK--x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk--x3d-start[1113]: Name or service not known: `vpn.aresgate.net:51820'
Oct 28 19:42:58 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 19:42:58 monroe wireguard-wg0-peer-GaRK--x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk--x3d-post-stop[1132]: RTNETLINK answers: No such process
Oct 28 19:42:58 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Oct 28 19:42:58 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Failed with result 'exit-code'.
Oct 28 19:42:58 monroe systemd[1]: Failed to start WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=).
Oct 28 19:45:04 monroe systemd[1]: Starting WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=)...
Oct 28 19:45:04 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Main process exited, code=killed, status=15/TERM
Oct 28 19:45:04 monroe wireguard-wg0-peer-GaRK--x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk--x3d-post-stop[2352]: RTNETLINK answers: No such process
Oct 28 19:45:04 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Oct 28 19:45:04 monroe systemd[1]: wireguard-wg0-peer-GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d.service: Failed with result 'signal'.
Oct 28 19:45:04 monroe systemd[1]: Stopped WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=).
Oct 28 19:45:04 monroe systemd[1]: Starting WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=)...
Oct 28 19:45:05 monroe systemd[1]: Finished WireGuard Peer - wg0 - GaRK\x2b-Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk\x3d (GaRK+/Wejh72faouTZrVI2SlmKlJH36sN9VLpW7GSEk=).
```

**Comment by bjornfor** [comment]
> Name or service not known: `vpn.aresgate.net:51820'

Looks like it's starting before the network is up. However, fixing the dependency or waiting a bit longer would probably still fail it if not connected to the Internet, and not automatically start when connected to the Internet... I think there is an option to reevaluate the endpoint for dynamic dns sceanrios, which might do retries? (On phone, sorry.)

**Comment by evilbulgarian** [comment]
> > Name or service not known: `vpn.aresgate.net:51820'
> 
> Looks like it's starting before the network is up. However, fixing the dependency or waiting a bit longer would probably still fail it if not connected to the Internet, and not automatically start when connected to the Internet... I think there is an option to reevaluate the endpoint for dynamic dns sceanrios, which might do retries? (On phone, sorry.)

Thanks, yeah I already have both of those options enabled without success:

```
persistentKeepalive = 25;
dynamicEndpointRefreshRestartSeconds = 5;
```

**Comment by bjornfor** [comment]
> Thanks, yeah I already have both of those options enabled without success:
> 
> ```
> persistentKeepalive = 25;
> dynamicEndpointRefreshRestartSeconds = 5;
> ```

Did you also try dynamicEndpointRefreshSeconds (without the "Restart" part)? (I don't think there will be any loop/retry without that one.)

**Comment by bjornfor** [comment]
Related / possible duplicate of: https://github.com/NixOS/nixpkgs/issues/260402

**Comment by evilbulgarian** [comment]
This is now fixed with the new refresh settings.
