### ISSUE TITLE
QTTools'  qcollectiongenerator broken by wrapper

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#26407]
## Issue description

Commit 775531c1e3d996db5705aee3f2e2f6a583912c9d by @periklis breaks $dev/bin/qcollectiongenerator because it is wrapped in the installPhase around $out/bin/qcollectiongenerator, before both files are moved to $dev. The wrapper ends up with an invalid path to $out, while the real wrapped file was moved to $dev.

I have no idea if the fix should go in Qt infra or reverting this commit.
It is possible to fix this by wrapping in the postPatch pahse, around $dev/bin.

/cc @ttuegel for it relates to Qt.

```diff
diff --git pkgs/development/libraries/qt-5/5.8/qttools/default.nix pkgs/development/libraries/qt-5/5.8/qttools/default.nix
index 6b97c2d85c..4e609ffb55 100644
--- pkgs/development/libraries/qt-5/5.8/qttools/default.nix
+++ pkgs/development/libraries/qt-5/5.8/qttools/default.nix
@@ -11,18 +11,16 @@ qtSubmodule {
   postFixup = ''
     moveToOutput "bin/qdbus" "$out"
     moveToOutput "bin/qtpaths" "$out"
-  '';
 
-  postInstall =   ''
-    wrapQtProgram $out/bin/qcollectiongenerator
-    wrapQtProgram $out/bin/qhelpconverter
-    wrapQtProgram $out/bin/qhelpgenerator
-    wrapQtProgram $out/bin/qtdiag
+    wrapQtProgram $dev/bin/qcollectiongenerator
+    wrapQtProgram $dev/bin/qhelpconverter
+    wrapQtProgram $dev/bin/qhelpgenerator
+    wrapQtProgram $dev/bin/qtdiag
   '' + optionalString (stdenv.isDarwin) ''
-    wrapQtProgram $out/bin/Assistant.app/Contents/MacOS/Assistant
-    wrapQtProgram $out/bin/Designer.app/Contents/MacOS/Designer
-    wrapQtProgram $out/bin/Linguist.app/Contents/MacOS/Linguist
-    wrapQtProgram $out/bin/pixeltool.app/Contents/MacOS/pixeltool
-    wrapQtProgram $out/bin/qdbusviewer.app/Contents/MacOS/qdbusviewer
+    wrapQtProgram $dev/bin/Assistant.app/Contents/MacOS/Assistant
+    wrapQtProgram $dev/bin/Designer.app/Contents/MacOS/Designer
+    wrapQtProgram $dev/bin/Linguist.app/Contents/MacOS/Linguist
+    wrapQtProgram $dev/bin/pixeltool.app/Contents/MacOS/pixeltool
+    wrapQtProgram $dev/bin/qdbusviewer.app/Contents/MacOS/qdbusviewer
   '';
 }
```

PS: This commit broke the `qtikz` package, so it is a good test to see if this issue is correctly fixed.

**Comment by ttuegel** [comment]
> Commit 775531c by @periklis breaks $dev/bin/qcollectiongenerator because it is wrapped in the installPhase around $out/bin/qcollectiongenerator, before both files are moved to $dev.

Wrapping must happen during `fixupPhase.`

However, in #26336, I am removing all the Qt wrappers anyway.

**Comment by layus** [comment]
@ttuegel, thank you for your amazing work around Qt !

**Comment by periklis** [comment]
@ttuegel mea culpa for my mistake, i was triggered by other qt-packages.
