### ISSUE TITLE
Update request: protonvpn-gui legacy → gtk-ver

### ISSUE THREAD

**Issue by Nyabinary** [NixOS/nixpkgs#264004]
- Package name: protonvpn-gui
- Latest released version: N/A

- Current version on the unstable channel: N/A
- Current version on the stable/release channel: N/A
- https://github.com/ProtonVPN/proton-vpn-gtk-app

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@WolfangAukang 
@wyndon 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by WolfangAukang** [comment]
[There is a step](https://github.com/ProtonVPN/proton-vpn-gtk-app#proton-package-registry) that I'm not sure how we could be able to perform it for packaging.

**Comment by Tc-001** [comment]
All those packages are also on github (ex. https://github.com/ProtonVPN/python-proton-vpn-api-core) and the Arch version added them as separate package dependencies directly:
https://aur.archlinux.org/packages/proton-vpn-gtk-app


Flatpak uses a different approach that I am not entirely sure about, but it seems to work
https://github.com/flathub/com.protonvpn.www

**Comment by WolfangAukang** [comment]
That makes sense then. V3 has a similar approach.

**Comment by WolfangAukang** [comment]
Good news, I got it working

![image](https://github.com/NixOS/nixpkgs/assets/8378365/f71aa004-9f74-4de7-b406-d23d0fa94496)

![image](https://github.com/NixOS/nixpkgs/assets/8378365/ed5725a7-6f79-4147-bd13-24507d90b60c)

I plan to create a PR soon. There is a bunch of modules to clean up, and I need to move the previous client to version 3.

**Comment by WolfangAukang** [comment]
In the end I couldn't get the tests for `protonvpn-gui` to work (I get a segmentation fault, tried with two devices)

**Comment by WolfangAukang** [comment]
@Nyabinary @Tc-001 could you please test the PR to see if it works for you and give an approval? This is to confirm it is not only working for me.

**Comment by SebTM** [comment]
Can confirm it's not on your side, it's happening for me too but working on a non-nix system :)

**Comment by SebTM** [comment]
Also have been using it a few days under nixos-23.05 (overlaying the package from your branch) and nixos-unstable now (same method, around a week) without any problems :)
