### ISSUE TITLE
nixos/syncoid: incorrectly detects source dataset as non-existent

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#264071]
### Describe the bug
The Syncoid service I have created with the `syncoid` NixOS module is incorrectly determining that the source dataset does not exist.

### Steps To Reproduce
1. Add the following to the NixOS system configuration.
```nix
  services.syncoid = {
    enable = true;
    interval = "*-*-* 20:00"; # Daily at 20:00
    sshKey = /var/lib/syncoid/id_rsyncnet_auto;
    # Permissions the local `syncoid` user gets to manipulate the local ZFS datasets
    # that are the sources for backups.
    localSourceAllow = [
      "mount"
      "compression"
      "hold"
      "send"
      "snapshot"
      "destroy"
    ];
    # Permissions the local `syncoid` user gets to manipulate local ZFS datasets that
    # are the targets for backups.
    # NOTE: you must ensure the remote syncoid user has similar permissions.
    localTargetAllow = [
      "mount"
      "compression"
      "hold"
      "send"
      "snapshot"
      "destroy"
    ];
    commonArgs = [
      "--recursive"
      # All our pools are already compressed
      "--compress=none"
      "--no-stream"
      "--debug"
    ];
    commands = {
      "rpool/path/to/dataset" = {
        target = "user@example.net:tank/bak";
        sendOptions = "wc";
      };
    };
  };
```
2. `$ sudo systemctl start syncoid-rpool-path-to-dataset.service`
3. Wait several seconds and then run
   `$ journalctl -u syncoid-rpool-userdata-home-aidan.service`
   Which should look something like this.

```
systemd[1]: Starting Syncoid ZFS synchronization from rpool/path/to/dataset to root@zh2666b.rsync.net:tank/bak...
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-zfs-allow-rpool-path-to-dataset[1545501]: NAME                        USED  AVAIL  REFER  MOUNTPOINT
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-zfs-allow-rpool-path-to-dataset[1545501]: rpool/path/to/dataset  67.2G   750G  30.2G  /home/aidan
systemd[1]: Started Syncoid ZFS synchronization from rpool/path/to/dataset to root@zh2666b.rsync.net:tank/bak.
syncoid[1545528]: DEBUG: SSHCMD: ssh     -i /var/lib/syncoid/id_rsyncnet_auto
syncoid[1545528]: DEBUG: compression forced off from command line arguments.
syncoid[1545528]: DEBUG: checking availability of mbuffer on source...
syncoid[1545528]: DEBUG: checking availability of mbuffer on target...
syncoid[1545528]: DEBUG: checking availability of pv on local machine...
syncoid[1545528]: DEBUG: checking availability of zfs resume feature on source...
syncoid[1545528]: DEBUG: checking availability of zfs resume feature on target...
syncoid[1545528]: WARN: ZFS resume feature not available on source machine - sync will continue without resume support.
syncoid[1545528]: DEBUG: recursive sync of rpool/path/to/dataset.
syncoid[1545528]: DEBUG: getting list of child datasets on rpool/path/to/dataset using   zfs list -o name,origin -t filesystem,volume -Hr 'rpool/path/to/dataset' |...
syncoid[1545608]: cannot open 'rpool/path/to/dataset': dataset does not exist
syncoid[1545528]: CRITICAL ERROR: no datasets found at /nix/store/d7hwyxb58kwmr3pb8y3wfadzxqi6mw8k-sanoid-2.2.0/bin/.syncoid-wrapped line 202.
systemd[1]: syncoid-rpool-path-to-dataset.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: syncoid-rpool-path-to-dataset.service: Failed with result 'exit-code'.
systemd[1]: syncoid-rpool-path-to-dataset.service: Consumed 269ms CPU time, received 6.4K IP traffic, sent 6.8K IP traffic.
```

Running the `zfs list` command shown in the log, even as the `syncoid` user, succeeds with sane output.
```console
$ sudo -u syncoid zfs list -o name,origin -t filesystem,volume -Hr 'rpool/path/to/dataset'
rpool/path/to/dataset       -
```

### Expected behavior
The syncoid command would successfully sync the dataset.

### Additional context
NixOS config is flake-based and tracking the `nixpkgs-unstable` channel.

### Notify maintainers
@ju1m @lopsided98 

### Metadata
```console
❯ nix shell nixpkgs#nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11.20231026.63678e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by ipetkov** [comment]
Also running into this exact same issue after updating from 5e4c2ada4fcd54b99d56d7bd62f384511a7e2593 to fa804edfb7869c9fb230e174182a8a1a7e512c40

Will try bisecting and see what comes up

**Comment by lopsided98** [comment]
There haven't been any recent changes to the syncoid module, so my guess is https://github.com/NixOS/nixpkgs/commit/1a81fe0cc89a4eb7c28c7a6b376700c9af869709.

**Comment by ipetkov** [comment]
Yep you are totally correct that's the commit which breaks! As for what changed with zfs 2.2.0 I have no clue...

**Comment by aidalgol** [comment]
> As for what changed with zfs 2.2.0 I have no clue...
Did the output format of the zfs command that syncoid uses change?

**Comment by ipetkov** [comment]
No clue, AFAICT from the logs syncoid cannot find the dataset at all? As in it seems to think that the dataset does not exist at all (and then tries to do a full send instead of an incremental one), but I also see another log entry (`cannot open 'tank/whatever': dataset does not exist`) which does not appear to be logged directly from syncoid

Running the service as root also has the same error which makes me think this is _not_ a zfs permission delegation issue. It's like the service cannot talk to zfs-in-the-kernel properly?

**Comment by ipetkov** [comment]
Okay it does look like a sandboxing issue of the systemd unit: I commented out most of the protection settings which fixed things, going to narrow down which is the culprit

(No idea why those would break all of a sudden, but maybe a kernel update changed something idk)

**Comment by ipetkov** [comment]
It looks like [`PrivateUsers = true;`](https://github.com/NixOS/nixpkgs/blob/231e60ee5c1b1f1fcbec7f867e3f57731ccc661e/nixos/modules/services/backup/syncoid.nix#L372) is the problematic setting here. Disabling it fixes syncoid runs (still not sure _why_ this is an issue, but I'm guessing that maybe private users breaks zfs permissions maybe?)

**Comment by ipetkov** [comment]
For anyone else coming here, you can apply the following to your configuration as a workaround until https://github.com/NixOS/nixpkgs/pull/265543 is merged

```nix
services.syncoid.service.serviceConfig.PrivateUsers = lib.mkForce false;
```
