### ISSUE TITLE
Build failure: heroic

### ISSUE THREAD

**Issue by fazo96** [NixOS/nixpkgs#264156]
### Steps To Reproduce

1. add `heroic` to `environment.systemPackages` on unstable
2. `sudo nixos-rebuild switch --upgrade`

### Build log

```
   … while evaluating derivation 'heroic-unwrapped-2.9.2'
         whose name attribute is located at /nix/store/bmcm18ngcq3pplprdkypa348qmi8lcps-nixos/nixos/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'installPhase' of derivation 'heroic-unwrapped-2.9.2'

         at /nix/store/bmcm18ngcq3pplprdkypa348qmi8lcps-nixos/nixos/pkgs/games/heroic/default.nix:75:3:

           74|   # https://github.com/electron/electron/issues/32317
           75|   installPhase = let
             |   ^
           76|     binPlatform = if stdenv.isDarwin then "darwin" else "linux";

       … from call site

         at /nix/store/bmcm18ngcq3pplprdkypa348qmi8lcps-nixos/nixos/pkgs/stdenv/generic/check-meta.nix:449:16:

          448|         {
          449|           no = handleEvalIssue { inherit meta attrs; } { inherit (validity) reason errormsg; };
             |                ^
          450|           warn = handleEvalWarning { inherit meta attrs; } { inherit (validity) reason errormsg; };

       … while calling 'handleEvalIssue'

         at /nix/store/bmcm18ngcq3pplprdkypa348qmi8lcps-nixos/nixos/pkgs/stdenv/generic/check-meta.nix:226:38:

          225|
          226|   handleEvalIssue = { meta, attrs }: { reason , errormsg ? "" }:
             |                                      ^
          227|     let

       error: Package ‘electron-24.8.6’ in /nix/store/bmcm18ngcq3pplprdkypa348qmi8lcps-nixos/nixos/pkgs/development/tools/electron/binary/generic.nix:35 is marked as insecure, refusing to evaluate.

```

### Additional context

The package is locked to Electron 24 by this PR it seems https://github.com/NixOS/nixpkgs/pull/254075 but Electron 24 is EOL now so it doesn't build

### Notify maintainers

@aidalgol 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[fazo@namyra:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11pre537656.7c9cc5a6e5d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"home-manager, nixos"`
 - channels(fazo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tormeh** [comment]
For context, there have been similar issues with Freetube (still ongoing) and Morgen (resolved).

**Comment by Baughn** [comment]
How do you track it down to a package like this? The error I'm getting on nixos-upgrade is simply about electron, though I suspect that's also Heroic.

**Comment by aidalgol** [comment]
The current stable release of Heroic breaks on any later version of Electron.  Upstream just yesterday merged a PR to upgrade to Electron 27 into the `main` branch, so this can be fixed in nixpkgs when the next upstream release comes out.

**Comment by fazo96** [comment]
@Baughn to get the full stack trace to show up I passed `--show-trace` to `nixos-rebuild switch`. Then I scrolled through the stack trace until I found a package name I recognised from my config

Without `--show-trace` the part that mentioned the `heroic` package was hidden
