### ISSUE TITLE
protonvpn-cli: An unknown error has occured. Please ensure that you have internet connectivity.

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#264110]
### Describe the bug
`protonvpn-cli` has completely stopped working. It used to work before, though.

### Steps To Reproduce
```
protonvpn-cli login <username>
protonvpn-cli connect
```

### Expected behavior
`protonvpn-cli` should be able to connect.

### Additional context
It looks like the repo has already been archived: https://github.com/ProtonVPN/linux-cli

Anyone know what's going on? Also, `protonvpn-gui` works alright.

### Notify maintainers

@wolfangaukang

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.11 (Tapir), 23.11.20231024.8efd5d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/store/z1nvpjx9vd4151vx2krxzmx2p1a36pf9-source`

```

**Comment by WolfangAukang** [comment]
> Anyone knows what's going on?

They are now releasing a version 4 of their software, but there is only a GUI version https://protonvpn.com/support/linux-vpn-setup/

**Comment by WolfangAukang** [comment]
I am not able to reproduce this issue though. Are you still having it?

**Comment by musjj** [comment]
Yeah, I no longer can reproduce it. No idea why. I guess it was just a temporary outage or something.

**Comment by WolfangAukang** [comment]
ProtonVPN sometimes breaks/gets fixed out of the blue, so it is not surprising.
