### ISSUE TITLE
Nix kills processes by uid in containers

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#2641]
1. Start a build in a container (tested on a non-nixos-container)
2. Start a build on the host

Result: the container build is killed with signal 9. As @edolstra says, this happens because nix kills processes of the builder by uid, and since there's no uid namespace also the container build is killed.
Changing the uids of nix build users in the container mitigates the problem.

**Comment by Profpatsch** [comment]
(triage) Since container implementations have changed quite a bit, can you verify that again @lethalman?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.
