### ISSUE TITLE
Grapejuice: RobloxPlayer always installing

### ISSUE THREAD

**Issue by Ryoschin** [NixOS/nixpkgs#264173]
So, whenever I open Player, it starts installing Roblox, finishes, and does nothing. Even when launched from the website, starts installing, finishes, and most likely just exits. Logs show nothing important. However, when trying open Studio, the error saying "RobloxStudioBeta.exe not found".

1. Download the grapejuice package (just write grapejuice in the with pkgs section)
2. Download wine-wayland package (not sure if it is required, however I did)
2. Open Grapejuice (I used rofi (drun), but I suppose $ `grapejuice app` would work)
3. In the message box that pops out (from wine), press "Install" to install the wine-mono thingy
4. Either press the Open RobloxPlayer button, or go into Player, Initialize and Install Roblox, the behavior is the same
5. Enjoy Roblox installing and doing nothing...

I expected RobloxPlayer to actually open, not install and exit...

```console
[xceptional@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11pre537656.7c9cc5a6e5d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by OctoRocket** [comment]
This is already tracked in issue #220062
