### ISSUE TITLE
Build failure: libarchive

### ISSUE THREAD

**Issue by Stephen-Seo** [NixOS/nixpkgs#264108]
### Steps To Reproduce

1. `nix-shell -p libarchive --run 'echo success'`

### Build log

Gist with libarchive's test-suite.log and logs of the failing test:
https://gist.github.com/Stephen-Seo/07e2614e87515732d0b9be2d61e5a6b8

### Additional context

Using Nix packager in a Raspberry Pi 3. Although there is only 1 GB available in RAM, additional gigabytes of SWAP has been enabled, so running out of RAM shouldn't be a problem (but somehow is?).

See output of `nix-info -m` below for additional context.

### Notify maintainers

@natsukium 

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"armv7l-linux"`
 - host os: `Linux 6.1.21-v7+, Raspbian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by natsukium** [comment]
cc @jcumming @AndersonTorres

**Comment by eclairevoyant** [comment]
swap is not ram, if your device is oom-ing there's not really a substitute for increasing ram...

**Comment by Stephen-Seo** [comment]
> swap is not ram, if your device is oom-ing there's not really a substitute for increasing ram...

So I take it then that building `libarchive` on a Raspberry Pi 3 may not just work then?

**Comment by Stephen-Seo** [comment]
I'm figuring out a build server for armv7 with more ram (than 1GB). Seeing as how this bug is probably based on the requirement of ram being more than 1GB, I think I'll close this issue as I'm figuring out an alternative.
