### ISSUE TITLE
Package request: Clear Linux 

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#264128]
**Project description**

Clear Linux produces an optimized kernel, that achieves in benchmark comparisons regularly the first place, when compared to other kernels. 

**Metadata**

* homepage URL: https://www.clearlinux.org/
* source URL: https://github.com/clearlinux-pkgs/linux
* license: gpl2
* platforms: linux

See this Arch [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-clear), maybe you can gain some knowledge from it. 

The request for this package aims to build a generic x86_64 kernel.

I am interested building a Zen3 optimized variation (see the Arch build at line 20) 
for myself, and I can see other people doing the same for their sub-architecture. 

We could then further maintain those variations for the public by us self, once the general build is ready 🙂 👍🏻

**Comment by SuperSamus** [comment]
Related to #63708.
