### ISSUE TITLE
H.264 videos don't work in Vivaldi.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#26413]
## Issue description
H.264 videos and specifically those (WebM and Theora are fine) don't play, which means that videos on Facebook and Twitter (at least) report an error.

There are instructions for getting a patched version of the ffmpeg lib installed into your home folder which works, but ideally wouldn't be needed: [https://gist.github.com/ruario/bec42d156d30affef655](https://gist.github.com/ruario/bec42d156d30affef655)

### Steps to reproduce

1. Go to [https://www.quirksmode.org/html5/tests/video.html](https://www.quirksmode.org/html5/tests/video.html)
2. Observe that the H.264 video don't work but the others do.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03.1264.9ed5dbafe3 (Gorilla)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.8`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.03.1264.9ed5dbafe3"`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

**Comment by fpletz** [comment]
What browser are you using? Works on Chromium, Firefox and qutebrowser (qtwebkit) on master for me.

**Comment by seanparsons** [comment]
@fpletz Vivaldi, hence the title of the issue...

**Comment by fpletz** [comment]
Oh, sorry, didn't know there's a browser called vivaldi.
