### ISSUE TITLE
wyoming.faster-whisper NixOS Module CUDA acceleration not working.

### ISSUE THREAD

**Issue by techyporcupine** [NixOS/nixpkgs#264209]
### Describe the bug
After setting up faster-whisper for my Home Assistant instance, I learned that my CPU (i5-6500) isn't quite as fast as I'd like for this, so I am now trying to test a GPU (NVIDIA Quadro M2000). My configuration for it is the following:
```nix
wyoming = {
  faster-whisper.servers.hasswhisper = {
    uri = "tcp://0.0.0.0:10300";
    language = "en";
    device = "cuda";
  };
};
```
I expected it to then run on my GPU using CUDA, but unless my GPU and CPU are continually equally performant, it is not working. (Also, no processes are shown in `nvidia-smi`)

### Steps To Reproduce
1. Install NVIDIA GPU, and then configure it accordingly in configuration.nix, add `cudatoolkit`, `cudaPackages.cudnn`, `cudaPackages.libcublas`, and `linuxPackages.nvidia_x11` to `enviroment.systemPackages`
2. Enable faster-whisper in configuration, configure it to work with device = "cuda"
3. Expect for STT to be faster, instead same speed

### Expected behavior
I'm not totally sure what to expect because this is my first time using this, but I expected a Python3 process to appear in `nvidia-smi` and for my STT to be quicker.

### Additional context
My `hardware.nvidia` config is the following:
```nix
    hardware.nvidia = {
      modesetting.enable = true;

      powerManagement.enable = false;

      powerManagement.finegrained = false;

      open = false;

      nvidiaSettings = true;

      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };
```
The following (seemingly) NVIDIA related items are at /dev/
![image](https://github.com/NixOS/nixpkgs/assets/70345789/a1ee0e95-5884-4856-a914-5d4ac4b3b469)
![image](https://github.com/NixOS/nixpkgs/assets/70345789/b6adac28-8288-4c48-abdf-0fa79701eb94)

`nvidia-smi` works, but I am not totally sure that my CUDA is configured correctly, for all I know possibly CUDA isn't configured properly, but I think I have everything correct.

### Notify maintainers

@mweinelt 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231016.ca012a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/4smdp3v5a9bcg1hpdhl2hs70rq385ykq-source`
```

**Comment by mweinelt** [comment]
I eyeballed CUDA support, but have no hardware to test or reproduce. I appreciate help in fixing the module to make it work with CUDA.

**Comment by techyporcupine** [comment]
I am not overly proficient in Nix or anything like this, but I would be willing to help if you have ideas.

**Comment by mweinelt** [comment]
Well, for one we're not passing `--device ${cfg.device}` in `ExecStart=`.

Can you try setting `services.wyoming.faster-whisper.extraArgs = [ "--device" "cuda" ]`?

**Comment by techyporcupine** [comment]
Ok, I added that and now when looking at the logs, I get this:
`ValueError: This CTranslate2 package was not compiled with CUDA support`

**Comment by mweinelt** [comment]
That looks actionable. We did indeed not build ctranslate2 with CUDA support.

**Comment by techyporcupine** [comment]
Is it possible to have the package be free unless an option is passed that enables CUDA and then makes it unfree, or would two different packages be needed. There could be a `faster-whisper-cuda` package, I think that could work.

**Comment by mweinelt** [comment]
Yeah, that would also work.

**Comment by techyporcupine** [comment]
If you want to try and build it with CUDA support, I can test it out and report back.

**Comment by mweinelt** [comment]
https://github.com/NixOS/nixpkgs/pull/264214 fixes the module, so it passes `--device` as expected. It also adds CUDA support to `ctranslate2`. Check the description of the PR on how to opt into CUDA support in nixpkgs.

**Comment by SomeoneSerge** [comment]
Hi @techyporcupine! Just to clarify, you only need `cudaPackages.*` in your `systemPackages` (or in your `mkShell`'s `buildInputs`) if you're setting up a development environment to write cuda programs. If you only want to use packages with cuda support enabled, you just use them directly (e.g. `systemPackages = [ colmapWithCuda ]`), no need to add `cudaPackages` anywhere manually. If you want to enable cuda in every package that supports it, you can set `nixpkgs.config.cudaSupport = true` in your `configuration.nix` (nb: this triggers a _massive_ rebuild). Instead of adding `linuxPackages`, you want to use `config.boot.kernelPackages` (this way if you switch e.g. `linuxPackages` -> `linuxPackages_zen`, you'd be still using `nvidia_x11` for the correct kernel), but also instead of `config.boot.kernelPackages` you can take `config.hardware.opengl.package` (keeps working if you switch e.g. `nvidia_x11` -> `nvidia_x11_beta`)

Sorry we didn't get this documented yet

**Comment by techyporcupine** [comment]
Wow, thank you! I assume I still need `cudatoolkit` in my `systemPackages`, right? About enabling `cudaSupport`, I've already enabled that and let it go through that whole process, so I think I'll just leave it enabled. About changing the `linuxPackages.nvidia_x11`, how is that to be done exactly? Do I just swap `linuxPackages.nvidia_x11` for `config.hardware.opengl.package.nvidia_x11` in the exact same spot?

**Comment by techyporcupine** [comment]
Also, @mweinelt, is there an easy way for me to test out this updated package before it gets merged?

**Comment by mweinelt** [comment]
Depends on how you deploy your machine and what nixos version you are on.

**Comment by techyporcupine** [comment]
I'm on Unstable and use Flakes.

**Comment by mweinelt** [comment]
You could replace your nixpkgs input with a fork of nixos-unstable and pick the commits from that PR on top.

I'm sure there is a better solution, but I'm not well versed in flakes.

**Comment by SomeoneSerge** [comment]
> Wow, thank you! I assume I still need cudatoolkit in my systemPackages, right

No, `cudatoolkit` is the old version of `cudaPackages.*`, and you don't need it in `environment.systemPackages`

**Comment by techyporcupine** [comment]
I have `hardware.opengl.enable = true`, but I don't have xserver enabled because this is a headless server. Do I even need nvidia_x11 if it's headless with no DE?

**Comment by SomeoneSerge** [comment]
`nvidia_x11` is where `libcuda.so` comes from; I don't recall now if it's ok to use `services.xserver.enable` on a headless machine, but if you like to just be explicit, you can keep `config.kernelPackages.nvidia_x11`

P.S. Discourse and NixOS matrix channels provide venues for Q&A discussions

**Comment by mweinelt** [comment]
With the changes made to ctranslate2, and the fixes to th wyoming.faster-whisper, I fully expect this could work.

If not, please get back to me with some error messages, e.g. the hardening of the systemd unit might cause problems.

**Comment by techyporcupine** [comment]
No problem. I attempted to use just the new packages, but it became a little difficult because my old nixpkgs didn't think that ctranslate2 could have CUDA enabled, so I'll just wait for master to get pushed to NixOS-Unstable (Hopefully soon!)

**Comment by techyporcupine** [comment]
The package now fails with `RuntimeError: CUDA failed with error no CUDA-capable device is detected`. My system may not be correctly configured for CUDA support, or the SystemD Service is not passing through the NVIDIA device correctly. Just a reminder, the following devices are available at `/dev/`:
```
nvidia0
nvidia-caps
nvidiactl
nvidia-modeset
nvidia-uvm
nvidia-uvm-tools
```
(I'm not sure if `/dev/nvram` is an NVIDIA thing, but it exists if that's of importance.)

**Comment by mweinelt** [comment]
Then we're at least missing `/dev/nvidia0`. What's the content of `/dev/nvidia-caps`?

```nix
          DeviceAllow = if builtins.elem options.device [ "cuda" "auto" ] then [
            # https://docs.nvidia.com/dgx/pdf/dgx-os-5-user-guide.pdf
            "/dev/nvidia1"
            "/dev/nvidia2"
            "/dev/nvidia3"
            "/dev/nvidia4"
            "/dev/nvidia-caps/nvidia-cap1"
            "/dev/nvidia-caps/nvidia-cap2"
            "/dev/nvidiactl"
            "/dev/nvidia-modeset"
            "/dev/nvidia-uvm"
            "/dev/nvidia-uvm-tools"
          ] else "";

**Comment by techyporcupine** [comment]
I modified the SystemD service to include `/dev/nvidia0`, and it didn't help at all. The contents of `/dev/nvidia-caps` are `nvidia-cap1  nvidia-cap2`. Also, I just discovered something new. When running `nvidia-smi` I get 
```
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 545.29
```
So possibly updating this system now broke NVIDIA support and it just so happened to be at the same time I tried to get Whisper working.

**Comment by SomeoneSerge** [comment]
>  Just a reminder, the following devices are available at /dev/:

Did you also check which `libcuda.so` is in `/run/opengl-driver/lib`?

> Failed to initialize NVML: Driver/library version mismatch

There two things you need to maintain: 1) your driver should be newer than the cuda libraries used to build your program, 2) your `libcuda.so` should come from the same (version of) `nvidia_x11` package as the kernel modules (in other words, currently you have to reboot if you update your nixos and get a newer `libcuda.so` - the new kernel module is only loaded on the next boot)

**Comment by techyporcupine** [comment]
`/run/opengl-driver/lib` shows the following for libcuda.so:
```
libcuda.so
libcuda.so.1
libcuda.so.545.29.02
```

Also, I just rebooted and `nvidia-smi` is working.

**Comment by techyporcupine** [comment]
@SomeoneSerge from what I listed is accessible from `/dev/`, should my system have functional CUDA support? I tried using some testing parts from [here](https://github.com/grahamc/nixos-cuda-example), but it seems to be out of date.

**Comment by SomeoneSerge** [comment]
> Should this conversation be continued somewhere else, or is it fine to continue it here because it is somewhat pertinent to the issue?

Yes please, e.g. in [https://matrix.to/#/#nix:nixos.org](https://matrix.to/#/%23nix%3Anixos.org?via=someonex.net&via=matrix.org&via=tchncs.de&via=snug.si) or [https://matrix.to/#/#cuda:nixos.org](https://matrix.to/#/%23cuda%3Anixos.org?via=someonex.net&via=matrix.org&via=amber.tel&via=matrix.cafkafk.com), or on https://discourse.nixos.org/. You can just post the final update here once you get things to work, for discoverability purposes. Thanks!
