### ISSUE TITLE
[ndiswrapper] error: implicit declaration of function 'net_srandom'

### ISSUE THREAD

**Issue by third3ye** [NixOS/nixpkgs#2642]
sudo nix-env -ir ndiswrapper

these derivations will be built:
  /nix/store/ck6p1gr0xrzqlhmycaps6xbk1fq972ls-ndiswrapper-1.59-3.14.2.drv
building path(s) `/nix/store/jj63481v5mzva181kd3y1dj0i0xwn149-ndiswrapper-1.59-3.14.2'
building /nix/store/jj63481v5mzva181kd3y1dj0i0xwn149-ndiswrapper-1.59-3.14.2
unpacking sources
unpacking source archive /nix/store/cdx08463c5ny8h6awy2pw14ska1rqjvf-ndiswrapper-1.59.tar.gz
source root is ndiswrapper-1.59
patching sources
applying patch /nix/store/hczj6g6iskr3bka9059a1bsn1akhpkki-no-sbin.patch
patching file driver/Makefile
configuring
no configure script, doing nothing
building
make KBUILD=/nix/store/n27k47bflq29a25lh2x56qvqam7bzrcp-linux-3.14.2-dev/lib/modules/3.14.2/build
building utils
make -C utils
make[1]: Entering directory `/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/utils'
building loadndisdriver
gcc -g -Wall -I../driver  -o loadndisdriver loadndisdriver.c
make[1]: Leaving directory `/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/utils'
building driver
make -C driver
make[1]: Entering directory `/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver'
building config_check
building modules
make -C /nix/store/n27k47bflq29a25lh2x56qvqam7bzrcp-linux-3.14.2-dev/lib/modules/3.14.2/build M=/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver
make[2]: Entering directory `/nix/store/n27k47bflq29a25lh2x56qvqam7bzrcp-linux-3.14.2-dev/lib/modules/3.14.2/build'
building all
building sub-make
building include/config/auto.conf
building crmodverdir
building /nix/store/n27k47bflq29a25lh2x56qvqam7bzrcp-linux-3.14.2-dev/lib/modules/3.14.2/build/Module.symvers
building _module_/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/built-in.o
  LD      /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/built-in.o
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/hal_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/hal_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ndis_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ndis_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ntoskernel_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ntoskernel_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ntoskernel_io_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/ntoskernel_io_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/rtl_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/rtl_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/usb_exports.h
  MKEXPORT /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/usb_exports.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/win2lin_stubs.h
  MKSTUBS /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/win2lin_stubs.h
building /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt.o
  CC [M]  /tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt.o
/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt.c: In function '_win_srand':
/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt.c:470:2: error: implicit declaration of function 'net_srandom' [-Werror=implicit-function-declaration]
  net_srandom(seed);
  ^
cc1: some warnings being treated as errors
make[5]: *** [/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver/crt.o] Error 1
make[4]: *** [_module_/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver] Error 2
make[3]: *** [sub-make] Error 2
make[2]: *** [all] Error 2
make[2]: Leaving directory `/nix/store/n27k47bflq29a25lh2x56qvqam7bzrcp-linux-3.14.2-dev/lib/modules/3.14.2/build'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/nix-build-ndiswrapper-1.59-3.14.2.drv-0/ndiswrapper-1.59/driver'
make: *** [driver] Error 2
builder for `/nix/store/ck6p1gr0xrzqlhmycaps6xbk1fq972ls-ndiswrapper-1.59-3.14.2.drv' failed with exit code 2
error: build of `/nix/store/ck6p1gr0xrzqlhmycaps6xbk1fq972ls-ndiswrapper-1.59-3.14.2.drv' failed

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by grahamc** [comment]
Look sto be a problem with a very old kernel now, so I'll go ahead and close. Bump if we should reopen.
