### ISSUE TITLE
Update request: yuzu-mainline 1595 → 1604

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#264244]
- Package name: [yuzu-mainline](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=yuzu)
- Latest released version: 1605

- Current version on the unstable channel:1595
- Current version on the stable/release channel: 1437

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by K900** [comment]
We try not to update to every single yuzu build, because that would be too much churn. Is there something in that particular version that is important to you?

**Comment by raspher** [comment]
@K900 it seems to have been updated to a newer version than requested

    Current version on the unstable channel:1696
    Current version on the stable/release channel: 1611
