### ISSUE TITLE
Uptimed cannot write its database

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#26421]
## Issue description

From the log

```
Jun 06 12:10:28 terry uptimed[15862]: uptimed: cannot write to /var/spool/uptimed/records
```

### Steps to reproduce

Try to use the `uptimed` service.

## Technical details

* System: 17.09pre108553.0011f9065a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre108553.0011f9065a"
* Sandboxing enabled: build-use-sandbox = true

**Comment by FRidh** [comment]
Duplicate of your own issue #22437?

**Comment by matthiasbeyer** [comment]
Whops.
