### ISSUE TITLE
jasp-desktop,please

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#264279]
**Project description**

**Metadata**

* homepage URL:https://jasp-stats.org/
* source URL:https://github.com/jasp-stats/jasp-desktop
* license: agpl3
* platforms: window, linux, darwin

**Comment by FliegendeWurst** [comment]
PR: #264366

**Comment by prehonor** [comment]
> PR: #264366

thank you ，but I had a error  when building source：https://pastebin.com/HFyBePg8

**Comment by FliegendeWurst** [comment]
> thank you ，but I had a error when building source：[pastebin.com/HFyBePg8](https://pastebin.com/HFyBePg8)

Yes, I get the same error. Unfortunately I could not figure out where the file `Engine/jaspBase/R/utility.R` is supposed to come from. That's why the PR is in draft mode (waiting for someone who knows how to fix the build).

**Comment by prehonor** [comment]
> > thank you ，but I had a error when building source：[pastebin.com/HFyBePg8](https://pastebin.com/HFyBePg8)
> 
> Yes, I get the same error. Unfortunately I could not figure out where the file `Engine/jaspBase/R/utility.R` is supposed to come from. That's why the PR is in draft mode (waiting for someone who knows how to fix the build).

    hash = "sha256-h/jFzR5XE+dmETENaBPQ0bCTLJYanpvtJTsMnAwoi9g="; #sha256-h/jFzR5XE+dmETENaBPQ0bCTLJYanpvtJTsMnAwoi9g= sha256-1m0URudMF50pnR7xYuu/d5817ouybaNLTG/h2d1J7rY=
	fetchSubmodules = true;   
After changed above, I got error ：https://pastebin.com/FTGBEu0k
