### ISSUE TITLE
Build failure: libhugetlbfs

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#264360]
### Steps To Reproduce

1. Look at ofborg crying:

https://gist.github.com/GrahamcOfBorg/52478f78686d832a258dcd4ad980fad0

>        error: evaluation aborted with the following error message: 'Failed to evaluate libhugetlbfs-2.23: «unknown-meta»: has an invalid meta attrset:
>          - key 'meta.badPlatforms' has invalid value; expected list of (string or attribute set of anything), got

(a huge incomprehensible set)

### Build log

Already above

### Notify maintainers

@alyssais 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

   
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231029.90e85bc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source`

```

**Comment by the-furry-hubofeverything** [comment]
Addressed in https://github.com/NixOS/nixpkgs/pull/264290 I thin
