### ISSUE TITLE
python3Packages.torch is broken

### ISSUE THREAD

**Issue by lanathlor** [NixOS/nixpkgs#264334]
### Describe the bug
python3Packages.torch package build is currently broken.
https://github.com/NixOS/nixpkgs/pull/249259 use https://github.com/pytorch/pytorch/pull/108847/commits/7ae4d7c0e2dec358b4fe81538efe9da5eb580ec9.patch from https://github.com/pytorch/pytorch/pull/108847 but the pytorch bot force pushed on this branch, deleting the commit. Since then, the package cannot build. https://github.com/pytorch/pytorch/pull/108847/commits/bf4050edab9f294a8e0060c47f906cd7a80f25a2.patch should be preferred ? 

### Steps To Reproduce
1. trying to build this shell :
```nix
let
  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { };
in
{ nixpkgs ? import <nixpkgs> {} }:
with nixpkgs; mkShell {
      nativeBuildInputs = with unstable.python310Packages; [
        (torch.override {
          magma = unstable.magma-cuda-static;
          cudaSupport = true;
          rocmSupport = false;
        })
      ];
}
``` 
2. nix-shell
3. getting this error:
```
```

### Expected behavior
not crashing

### Additional context
New to nix.

### Notify maintainers
@ConnorBaker @samuela @SomeoneSerge 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.8, NixOS, 23.05 (Stoat), 23.05.4584.1a3c95e3b23b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(lanath): `""`
 - channels(root): `"nixos-23.05, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by SomeoneSerge** [comment]
Interesting. It's fod, why didn't hydra just cache it?

**Comment by ConnorBaker** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/264379.
