### ISSUE TITLE
Pandoc closure size has exploded again

### ISSUE THREAD

**Issue by mdekstrand** [NixOS/nixpkgs#264399]
### Describe the bug

The Pandoc package has an extremely large closure size (over 5GB, see [Hydra log](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.pandoc.x86_64-linux#tabs-charts)).

### Steps To Reproduce
1. install Pandoc
2. observe 5GB taken up in the nix store

### Expected behavior
Pandoc installs a much smaller set of dependencies actually needed at runtime.

### Screenshots
Hydra log linked above shows the closure size.

### Additional context

This was previously discussed in #34376, where it appears to have been fixed.

On Aug. 17, a new build of Pandoc ballooned its closure size from ~250MB to over 5GB: <https://hydra.nixos.org/build/231799723#tabs-summary>. It has been larger ever since.

Looking at the Git log, c1b77b8641b9943b6532dff178dd268b3b7d4d92 by @sternenseemann, or the infrastructure changes this commit applies, may be the trigger? It's the Aug. 17 log most likely to touch Pandoc (and thus this issue is probably not Pandoc-specific).

### Notify maintainers

@maralorn?

**Comment by picnoir** [comment]
`/nix/store/z7304ayw334d6cfr8aljfsdhrmx88k73-pandoc-2.19.2` (from 8acef304efe70152463a6399f73e636bcc363813), before the size bump, does not depend on any build-time dependency. Neither GCC, neither any Haskell lib.

`/nix/store/np2f5g1x25fgkp6q10n5p14352899km7-pandoc-cli-0.1.1.1`, (from fe1e9d524b7ac9fac5f8be3ea2a7d177a5a4b4dc), depends on GHC and the whole haskell build input closure. It probably shouldn't.

The size bump comes likely from there.

-----------------------

Looking at the blame history, it seems like we already accidentally ended up with GHC  in the closure. @Profpatsch fixed that with fe1e9d524b7ac9fac5f8be3ea2a7d177a5a4b4dc back then.

**Comment by picnoir** [comment]
Okay, got a fix.

**Comment by eclairevoyant** [comment]
closing as the relevant PR was merged

**Comment by picnoir** [comment]
This is a bandaid fix though. It'll likely re-appear in the future. We should also aim for a proper fix.

I think it's another case of https://github.com/NixOS/nixpkgs/issues/164630
