### ISSUE TITLE
Update request: QGIS 3.32 -> QGIS 3.34

### ISSUE THREAD

**Issue by timlinux** [NixOS/nixpkgs#264482]
- Package name: QGIS
- Latest released version: 3.32

Hi @imincik 

QGIS 3.34 was released on friday. It adds a new dependency for [draco](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/draco/default.nix#L55) . I also added some tweaks to remove unneeded build steps (QGIS Server and tests) and explicitly set build to release mode.

My .nix file is attached.

[unwrapped.zip](https://github.com/NixOS/nixpkgs/files/13210759/unwrapped.zip)

**Notify maintainers**

@imincik
@sikmir
@nh2
@willcohen

**Comment by ShalokShalom** [comment]
Maybe update the title to include the name of the application

**Comment by timlinux** [comment]
> Maybe update the title to include the name of the application

Apologies, fixed now, thanks!

**Comment by imincik** [comment]
Thank you @timlinux , I'll try to update ASAP.

**Comment by imincik** [comment]
Building right now. Thanks heaps for patch.

**Comment by imincik** [comment]
Build went fine, but during the start QGIS is showing "Release candidate" logo

![qgis-logo](https://github.com/NixOS/nixpkgs/assets/476346/f75afc40-0724-4d4f-b693-19cbf7f6a429)

It looks like proper release according About window

![screen-imincik-2023-11-01-18:44:02](https://github.com/NixOS/nixpkgs/assets/476346/a0575118-ad52-4fc2-8d10-16665cdbe1ee)

**Comment by ShalokShalom** [comment]
There was not even a release candidate, at least judging by their [Github page. ](https://github.com/qgis/QGIS/tags)
But they dont seem to have any officially at all, and there is still this banner.

**Comment by imincik** [comment]
QGIS website is showing

3.32.3 ​
3.28.11 LTR

as current releases. Maybe it is not updated yet.

**Comment by imincik** [comment]
Draft PR created - https://github.com/NixOS/nixpkgs/pull/264871 .

I'll add more changes suggested by @timlinux in next commits.

**Comment by timlinux** [comment]
@imincik that banner is correct - .0 releases will always have that banner

**Comment by ShalokShalom** [comment]
Seems counterintuitive - since the release page declares it as final.

**Comment by willcohen** [comment]
I think this usually happens with the .0 release — it goes away with .1, if
I recall correctly.

**Comment by timlinux** [comment]
@willcohen there is a logic to it. The 3.34.x series is special as it is the 'feeder' release series till the next LTR. I am checking with our PSC that my statement above is correct, I think that badge should be carried through until the actual ltr too...

![image](https://github.com/NixOS/nixpkgs/assets/178003/98883386-89d7-4a07-9d4d-b42ca8a5135d)

**Comment by willcohen** [comment]
Yep that sounds more right, and that it goes beyond the 0.1. Sorry for speaking off the cuff! I remember this now and what you said sounds right — my coworkers would always ask me why it said RC and it went on till the next minor release.

**Comment by timlinux** [comment]
Ok I stand corrected by Juergen (QGIS Release Manager) - only the .0 release gets that badge:

![image](https://github.com/NixOS/nixpkgs/assets/178003/95c24e4e-ef55-4c95-bda7-60b2bf72da54)

**Comment by imincik** [comment]
@timlinux , thank you very much for explanation. https://github.com/NixOS/nixpkgs/pull/264871 is now ready to be reviewed.
