### ISSUE TITLE
Package request: OpenSUSE patched KDE Firefox

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#264491]
**Project description**

Firefox is a GTK based browser, and does utilize usually the GTK file dialog, also within a KDE session. 

OpenSUSE has developed a patch that allows Firefox to be compatible with KDE tools. 

So that can we use the native KDE file dialog and other goodies: 
https://github.com/openSUSE/firefox-maintenance/blob/master/mozilla-kde.patch

The global appmenu widget is also possible to use thanks to that patch, although that seems currently broken as far as I am aware. 🙂 

(There are also other patches in this repository, who might be useful.)

**Metadata**

* homepage URL: 
* source URL: https://github.com/openSUSE/firefox-maintenance/blob/master/mozilla-kde.patch
* license: mpl2
* platforms: all

**Comment by sdht0** [comment]
For Plasma native file dialogs, alternatively see https://wiki.archlinux.org/title/Firefox#KDE_integration

**Comment by ShalokShalom** [comment]
Yeah, we dont have xdg-desktop-portal(-kde) either.

**Comment by sdht0** [comment]
We do:
```nix
xdg.portal = {
  enable = true;
  extraPortals = with pkgs; [ xdg-desktop-portal-kde ];
};
```

**Comment by ShalokShalom** [comment]
Oh, thanks a lot.

**Comment by ShalokShalom** [comment]
Do we already have a place, where this is documented?

**Comment by ShalokShalom** [comment]
You are correct. I wonder, why the KDE FileDialog is then not enabled by default. 
I think we can close this, at least according to me. 

Any objections?
