### ISSUE TITLE
Wrong configuration of vfat boot filesystems

### ISSUE THREAD

**Issue by Nick1296** [NixOS/nixpkgs#264457]
### Describe the bug
There's an evaluation error that prevents the `nixos rebuild-switch` command to succeed.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Use the latest nixos-unstable branch of nixpkgs and have your boot partition in a vfat filesystem (or any other partition that needs to be loaded a initrd time)
2. Just do a nixos rebuild switch

### Expected behavior
Configuration should build normally.

### Error message
```
 error: A definition for option boot.initrd.systemd.extraBin is not of type attribute set of path. Definition values:
       - In /nix/store/35dcag44a0ymww0vy0s4jjgxwpv9g62d-source/nixos/modules/tasks/filesystems/vfat.nix:
           [
             <derivation dosfstools-4.2>
           ]
```

### Additional context
The line that creates the problem was added in this commit: 18013cc71e8d00cc1297af29d519b420f1326b41. 
Here is a link to the [offeding file](https://github.com/NixOS/nixpkgs/commit/18013cc71e8d00cc1297af29d519b420f1326b41#diff-83e7f75ba4098169b80b03b8173a68ce0ed295e69c168ba4c0a1ca0fa5825fb5)

I guess the author meant to write `boot.initrd.systemd.initrdBin` but I am not very knowledgeable about nix so I am not 100% sure of this.

### Notify maintainers
@ElvishJerricco 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Gerg-L** [comment]
Fixed by: https://github.com/NixOS/nixpkgs/pull/263627
