### ISSUE TITLE
Build failure: gomplate

### ISSUE THREAD

**Issue by giorgiga** [NixOS/nixpkgs#264441]
Gomplate build currently fails (version 3.11.5).

The devs say to upgrade to v4, which seems not to have been released yet. 

(see https://github.com/hairyhenderson/gomplate/issues/1872)

### Notify maintainers

I'm the package maintainer. I'm creating this to keep track of the issue.

**Comment by diamondburned** [comment]
Less than ideal workaround: `(gomplate.override { buildGoModule = buildGo120Module; })`

**Comment by giorgiga** [comment]
Good point, thanks: I guess that's the best we can do (short of patching the sources).

I'm fixing it now.
