### ISSUE TITLE
Package request: intel compute-runtime (Intel GPU driver)

### ISSUE THREAD

**Issue by Cyberavater** [NixOS/nixpkgs#264522]
**Project description**
This package actually includes `intel-opencl-icd`, `intel-level-zero-gpu` and `intel-gmmlib`. They're not found in Nix packages. You can find `intel-gmmlib` on Nix but that is very old.

On ubuntu we can add the repo and easily download it
https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/configure-wsl-2-for-gpu-workflows.html

**Metadata**

* homepage URL: https://github.com/intel/compute-runtime
* source URL: https://github.com/intel/compute-runtime/releases/tag/23.30.26918.9
* license: [MIT](https://github.com/intel/compute-runtime/blob/master/LICENSE.md)
* platforms: Linux (Ubuntu)

**Comment by eclairevoyant** [comment]
This is already packaged
https://search.nixos.org/packages?channel=23.05&show=intel-compute-runtime&from=0&size=50&sort=relevance&type=packages&query=compute+runtime

**Comment by Cyberavater** [comment]
Well actually nix doesn't contain all the packages, please check again 

>This package actually includes intel-opencl-icd, intel-level-zero-gpu and intel-gmmlib. They're not found in Nix packages. You can find intel-gmmlib on Nix but that is very old.

Also, after installing I can't verify my GPU like I can on Ubuntu check here

https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/configure-wsl-2-for-gpu-workflows.html

>clinfo

**Comment by jpds** [comment]
> You can find intel-gmmlib on Nix but that is very old.

The version in `unstable` is not that old.

> clinfo

This is in the different Nix package: https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=clinfo

> Why do I say "This package actually includes intel-opencl-icd, intel-level-zero-gpu and intel-gmmlib."

Having taken a scan of the upstream CMake definition: https://github.com/intel/compute-runtime/blob/master/CMakeLists.txt - the up-to-date Nix package here: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/intel-compute-runtime/default.nix#L27 is missing the `NEO_BUILD_WITH_OCL`  and `BUILD_WITH_L0`. You can download this Nix file, edit it to include these options at the linked line and build it on your machine with:

```
nix-build -E "with import <nixpkgs> {}; callPackage /home/you/whatever-you-called-it.nix {}"
```

And see if the generated output then fixes this issue for you.

**Comment by eclairevoyant** [comment]
> Also, after installing only this I can't verify my GPU as I can on Ubuntu after installing from their repo check here

You need to add `intel-compute-runtime` to `hardware.opengl.extraPackages`. `clinfo` works for me after doing that.

**Comment by pearsche** [comment]
> Having taken a scan of the upstream CMake definition: https://github.com/intel/compute-runtime/blob/master/CMakeLists.txt - the up-to-date Nix package here: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/intel-compute-runtime/default.nix#L27 is missing the NEO_BUILD_WITH_OCL and BUILD_WITH_L0. You can download this Nix file, edit it to include these options at the linked line and build it on your machine with:

I think BUILD_WITH_L0 gets turned on automatically? if NEO_BITS is 64, and same with NEO_BUILD_WITH_OCL as my clinfo output says " Device Version                                  OpenCL 3.0 NEO "

**Comment by Cyberavater** [comment]
> > Also, after installing only this I can't verify my GPU as I can on Ubuntu after installing from their repo check here
> 
> You need to add `intel-compute-runtime` to `hardware.opengl.extraPackages`. `clinfo` works for me after doing that.

You are correct, I can see my GPU in clinfo after

```nix
hardware.opengl.extraPackages = with pkgs; [
   intel-compute-runtime

  ];
  ```
  
I've only added `intel-compute-runtime` in `hardware.opengl.extraPackages`. Should I have to add any other packages anywhere for my Intel Arc GPU and Integrated Graphics?

Thanks for your help tho.

**Comment by Cyberavater** [comment]
@pearsche thanks, I'll look into it.

**Comment by eclairevoyant** [comment]
If you just want hw-accelerated video, all you need is `intel-media-driver` added to `hardware.opengl.extraPackages`. The -sdk package is for development.

**Comment by Cyberavater** [comment]
> If you just want hw-accelerated video, all you need is `intel-media-driver` added to `hardware.opengl.extraPackages`. The -sdk package is for development.

Thanks!
