### ISSUE TITLE
Package request: python-jwt (some confusing/incorrect package naming in nixpkgs)

### ISSUE THREAD

**Issue by JonBoyleCoding** [NixOS/nixpkgs#264572]
PLEASE NOTE: The package in nixpkgs called [python-jwt](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/python-modules/python-jwt/default.nix) is not actually the [python-jwt module on pypi](https://pypi.org/project/python-jwt/). The aforementioned package is called [jwt on pypi](https://pypi.org/project/jwt/). To confuse things even further, there is also a [pyjwt on pypi](https://pypi.org/project/PyJWT/).

**Project description**

Module for generating and verifying [JSON Web Tokens](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html).

**Metadata**

* homepage URL: https://pypi.org/project/python-jwt/ 
* source URL: https://github.com/davedoesdev/python-jwt
* license: mit
* platforms: unix, linux, darwin

**Comment by jfvillablanca** [comment]
notifying maintainer: @thornycrackers
