### ISSUE TITLE
ghc-mod not working with ghc7103

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#26468]
## Issue description
Problem trying to use ghc-mod with ghc 7.10.3

### Steps to reproduce

    $ nix-shell -p pkgs.haskell.packages.ghc7103.ghc-mod
    error: attribute ‘cabal-helper_0_6_3_1’ missing, at /nix/store/z74fni7zffwhfpfq1axvf6q9k5x6682h-nixos-17.09pre107265.0afb6d789c/nixos/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix:204:53
    (use ‘--show-trace’ to show detailed location information)

## Technical details

* System: NixOS: 17.09.git.30ce98b (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5350_7689181e
* Nixpkgs version: "17.09pre107265.0afb6d789c"
* Sandboxing enabled: build-use-sandbox = false

## Additional Info

my shell.nix 

    { nixpkgs ? import <nixpkgs> {}, compiler ? "ghc7103" }:
    let
      inherit (nixpkgs) pkgs;
      hs = pkgs.haskell.packages.${compiler}.ghcWithHoogle (ps: with ps; [
            ]);
    in
    pkgs.stdenv.mkDerivation {
      name = "haskell-shell";

      # uncomment this installed ghc-mod version 5.7.0.0 compiled by GHC 8.0.2
      # but ghc-mod give error when run:
      # ghc-mod: Can't parse "/nix/store/97dazhazcpc3bb92a1pp3pc2ylbj90kc-ghc-7.10.3-with-packages/lib/ghc-7.10.3/platformConstants"
      # buildInputs = with pkgs.haskellPackages; [ hs hlint ghc-mod ];

      # uncomment this failed with:
      # attribute ‘cabal-helper_0_6_3_1’ missing,
      # at /nix/store/z74fni7zffwhfpfq1axvf6q9k5x6682h-nixos-17.09pre107265.0afb6d789c/nixos/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix
      # buildInputs = with pkgs.haskell.packages.${compiler}; [ hs hlint ghc-mod ];

      shellHook = ''
        export PS1="\[\033[1;32m\][ns-hs:\w]\n$ \[\033[0m\]"
        eval "$(egrep ^export "$(type -p ghc)")"
      '';
    }

**Comment by wizzup** [comment]
[blame](https://github.com/NixOS/nixpkgs/commit/679a51b1164c577335e424882cd4df0acf96e961#diff-b201eadb7d78060b3e4288980810db65) @obadz

**Comment by wizzup** [comment]
A dirty fix: remove ghc-mod override seem to fix the build problem (30127b7).

**Comment by obadz** [comment]
I don't have a view as I don't use ghc anymore. Maybe open a PR and one of the active Haskell packagers will merge if it makes sense?

**Comment by wizzup** [comment]
I don't make a PR because `I have no idea what I am doing`, :)

**Comment by peti** [comment]
I am sorry, but we don't really support GHC 7.10.x. The Nixpkgs default compiler is GHC 8.0.2.
