### ISSUE TITLE
Invalid channels added to root channels list

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#264602]
### Describe the bug

Invalid channels added to root user

```
$ sudo nix-channel --list
" "
nixos "https://nixos.org/channels/nixos-unstable
```

### Steps To Reproduce
1. Rebuild against nixos-unstable

### Expected behavior
Don't add garbage channels

### Additional context

Already tried manual cleanup

```sh
nix-channel --remove '"'
nix-channel --remove 'nixos'
nix-channel --add https://nixos.org/channels/nixos-unstable
```
(all as root)

However, these broken channels returned after rebuilding.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11.20231029.0cbe9f6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/z6w242l49pbrdawkz5vdhfxh2mvsj36c-source`
```

**Comment by eclairevoyant** [comment]
Seems related to #263203, hence tagging @nikstur

**Comment by nikstur** [comment]
I'm working on a fix right now.
