### ISSUE TITLE
Update request: vscode-extensions.editorconfig.editorconfig: 0.16.4 → 0.16.6

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixpkgs#264632]
- Package name: EditorConfig for VsCode
- Latest released version: 0.16.6

- Current version on the unstable channel: 0.16.4 
- Current version on the stable/release channel: 0.16.4 

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@dbirks 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by superherointj** [comment]
Have a look in:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/

Read the README.md:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/README.md

Edit:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/default.nix

Build as:

> nix build .#vscode-extensions.publisher-name.extension-name

**Comment by superherointj** [comment]
ping @nyabinary

**Comment by nyabinary** [comment]
> ping @nyabinary

I don't quite understand has it been updated or?

**Comment by superherointj** [comment]
> > ping @nyabinary
> 
> I don't quite understand has it been updated or?

I explained to you the process of upgrading it. It's usually simple enough that anyone can do it.
I wanted to know if you want to update it yourself. In case you have doubts, I may guide you through.

**Comment by superherointj** [comment]
Last version on Microsoft Marketplace is `0.16.4`:

![image](https://github.com/NixOS/nixpkgs/assets/5861043/09ec1495-2635-4443-9d83-b998ae6610ad)

https://marketplace.visualstudio.com/items/EditorConfig.EditorConfig/

What do you want to be done here?

**Comment by nyabinary** [comment]
> Last version on Microsoft Marketplace is `0.16.4`:
> 
> ![image](https://private-user-images.githubusercontent.com/5861043/341563783-09ec1495-2635-4443-9d83-b998ae6610ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Mjk1MzIsIm5iZiI6MTcxODkyOTIzMiwicGF0aCI6Ii81ODYxMDQzLzM0MTU2Mzc4My0wOWVjMTQ5NS0yNjM1LTQ0NDMtOWQ4My1iOTk4YWU2NjEwYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDAyMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YwZGM0Mzk5N2I2NTVkMDg4MTM2MmEyZGQ4MDM0OGIwZmI4NTU0ZWI4MGVkMmY5MmNhMWFiMzJlNDNiMjJlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UWyzAnLteTPb9_fq0-CkMVY-qztSyPjjNM2HNdf0Y6E)
> 
> https://marketplace.visualstudio.com/items/EditorConfig.EditorConfig/
> 
> What do you want to be done here?

Whoops, I swear it was 0.16.6 😰, sorry

**Comment by superherointj** [comment]
A fix for this is not clear. Package doesn't exist at marketplace.
