### ISSUE TITLE
Infinite recursion blocking upgrade on boot.swraid.mdadmConf setting to config value.

### ISSUE THREAD

**Issue by pjlover95** [NixOS/nixpkgs#264669]
### Describe the bug
Infinite recursion error when attempting nixos-rebuild switch --upgrade.  Can't tell if it's an issue with warnDeprecation function related to boot.swraid.mdadmConf, or something in how environment.etc."mdadm.conf".source is set.

```
[root@hetzner:/etc/nixos]# nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-unstable
```

### Steps To Reproduce
1. configuration.nix + hardware-configuration.nix in [this Gist](https://gist.github.com/pjlover95/9c24152394a071fe955e06f9d63144c5), along with the --show-trace output from ```nixos-rebuild switch --upgrade```

### Expected behavior
A normal rebuild to update the latest packages.  I had seen a warning before to migrate TO boot.swraid.mdadmConf (instead of the other settings before), but now the deprecation warning for something appears to cause infinite recursion.  That's blocking my upgrades completely, and I would normally just remove the setting, but this is a Hetzner box and I don't feel comfortable that the swraid configuration isn't critical to booting (I suspect it is).

### Screenshots
Details in [the gist](https://gist.github.com/pjlover95/9c24152394a071fe955e06f9d63144c5).

### Additional context
The contents of ./mdadm/mdadm.conf file, if interested, is exactly the same as the commented environment.etc."mdadm".text value (with the email changed for privacy).  I'm relatively new to NixOS, so if there's something dumb I'm doing that I can correct on my end, that would be lovely.

### Notify maintainers
@SuperSandro2000 (just guessing, please redirect liberally :) )

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@hetzner:/etc/nixos]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.6, NixOS, 23.11 (Tapir), 23.11pre523790.db9208ab987c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by eclairevoyant** [comment]
Yeah this is just wrong, you can't put the contents of /etc/mdadm.conf into /etc/mdadm.conf. Infrec is a given.

**Comment by pjlover95** [comment]
Thanks for the direction, @eclairevoyant .  The odd thing: this exact config was working just fine until a recent ```nix-channel --update```.  I went ahead and removed the 2 environment references, and just directly set the boot.swraid.mdadmConf variable instead, and now it's working.  So thanks for the pointer. :)

**Comment by eclairevoyant** [comment]
This script must not have been touched in years, `boot.initrd.mdadmConf` isn't even an option in 23.05 until now

They should update it or remove it...
