### ISSUE TITLE
Chrome broken, wont download or install

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#26464]
## Issue description

I don't know if it's because the version hasn't been updated but Chrome will no longer download for me using stable. The error message I get is the following:

```
curl: (22) The requested URL returned error: 404 
error: cannot download google-chrome-stable_57.0.2987.133-1_amd64.deb from any mirror
builder for ‘/nix/store/h52m5rmdabd0hrp430lcqwbvblb5n2sf-google-chrome-stable_57.0.2987.133-1_amd64.deb.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dvvrp3ni9d08yq2b5jj32k3yba4y0d3z-google-chrome-57.0.2987.133.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/zmh8bx3bdgz90fbhsnzya9rbac3i967h-google-chrome-57.0.2987.133.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jy9x2s7m88zscwz3hzm5s9k64cycsrq5-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/anxs9wb5cwbbxzh80i5cvj4yy3xm5m8y-nixos-system-atom-17.03.1264.9ed5dbafe3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/anxs9wb5cwbbxzh80i5cvj4yy3xm5m8y-nixos-system-atom-17.03.1264.9ed5dbafe3.drv’ failed
```

I was able to 'fix' the problem by overriding the package with a working link: 

```
        (pkgs.google-chrome.overrideAttrs (oldAttrs: rec {
          src = pkgs.fetchurl {
            url = "http://www.slimjetbrowser.com/chrome/lnx/chrome64_57.0.2987.133.deb";
            sha256 = "4a62a77b3c7960f9313d41a40f645b7178d6a8b91f9f1141d7664026692ef63d";
          };
        }))
```

Maybe the chrome version just needs to be bumped? I looked at the [chrome package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/google-chrome/default.nix) but I was unable to figure out how exactly the versioning worked.

## Technical details

* System: (NixOS: 17.03.1264.9ed5dbafe3 (Gorilla))
* Nix version: (nix-env (Nix) 1.11.8)
* Nixpkgs version: ("17.03.1264.9ed5dbafe3")
* Sandboxing enabled: (true)

**Comment by joachifm** [comment]
I've cherry-picked updates to chromium/google-chrome; I hope that will resolve this issue once the 17.03 channel is updated.

**Comment by johnramsden** [comment]
@joachifm Thanks! I'll keep you informed when I try it.

**Comment by aij** [comment]
Seems to be working again. I just got `/nix/store/sjkrivkdyfxh8l8vr8vqij39sc93kwzz-google-chrome-stable_58.0.3029.110-1_amd64.deb` when I did a `nixos-rebuild test --upgrade`.

**Comment by johnramsden** [comment]
Yep, I meant to close this. Working now.
