### ISSUE TITLE
Package request: clamtk

### ISSUE THREAD

**Issue by ardishco-the-great** [NixOS/nixpkgs#264653]
**Project description**

Easy to use graphical user interface for Clam Antivirus (ClamAV)

ClamTk is intended to be an easy to use, light-weight, on-demand scanner for Linux systems.

**Metadata**

* homepage URL: https://github.com/dave-theunsub/clamtk
* source URL: https://github.com/dave-theunsub/clamtk
* license: gpl, the artistic license
* platforms: linux

(the licensing does not specifically say which version of gpl it is, so I listed it as gpl)

**Comment by IogaMaster** [comment]
This was already an issue, but this one has more information
[#263331](https://github.com/NixOS/nixpkgs/issues/263331)

Maybe we should close the other one.
