### ISSUE TITLE
Allow setting timezone via timedatectl

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#26469]
## Issue description
I'd like to be able to set my timezone using timedatectl, as I'm not always in the same timezone with my laptop and don't think its configuration should have to reflect my current location. https://github.com/NixOS/systemd/commit/f65b136cc0629c4f94c65b72ee1cdcac40c8286b hardcodes prevention of setting the time zone via this mechanism (and also causes #14877). It would be nice to refine this code to allow setting time and timezone via `timedatectl`.

In fact, I'm not sure the timezone should live in the NixOS config at all. Any thoughts on that?

### Steps to reproduce

`timedatectl set-timezone Europe/London`

## Technical details

- System: 17.03.1264.9ed5dbafe3 (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1264.9ed5dbafe3"
- Sandboxing enabled:  true

**Comment by 7c6f434c** [comment]
It's a complicated question what is better; I personally prefer system on UTC, user environment with `TZ` set to the current zone and multiple clocks at the bottom of the screen (time where I am, UTC, and times where the people that I usually chat with are).

**Comment by bjornfor** [comment]
I think it'd be nice if e.g. ```time.timeZone = null``` meant to allow imperative timezone configuration.

**Comment by Mic92** [comment]
Networkd also allows to apply the timezone via dhcp. So there are valid use cases.

**Comment by bjornfor** [comment]
And Gnome has support for setting the timezone based on geoip, IIRC.

**Comment by lheckemann** [comment]
#26608 should resolve this issue in the stricter sense. Not sure how networkd and gnome's stuff work, but I'd assume that networkd uses the timedate D-Bus interface as well, given that it's a systemd project, and I'd hope that Gnome does too, given how it usually integrates nicely with systemd.

**Comment by Mic92** [comment]
Networkd uses the dbus api of `systemd-timesyncd`

**Comment by 0xABAB** [comment]
Setting the timezone has a use on servers. Ignoring that use case is a bad idea. Adding support for the mobile international user is a good idea. Using `null` is a hack. Just add a flag like `imperativeTimezonemanagement` (or come up with a better name).

**Comment by lheckemann** [comment]
I don't see how using null is a hack. The timezone is either an existing timezone or has no static value, which is encoded perfectly by an option type (nullOr). I don't think an extra option is necessary.

**Comment by lheckemann** [comment]
And this isn't ignoring the fixed-timezone use case for servers at all — it preserves the previous behaviour unless they don't have a timezone set, in which case the only change it makes is allowing imperative timezone changes.

**Comment by 0xABAB** [comment]
@lheckemann I have no disagreement anymore, if others are in favor.

**Comment by lheckemann** [comment]
This is now blocked until https://github.com/NixOS/systemd/pull/11 gets merged and nixpkgs gets systemd v234. It will also at that point no longer cause a mass rebuild, as the change that causes a mass rebuild is the systemd update and not the module changes.

**Comment by lheckemann** [comment]
No longer blocked, and I've rebased it against the latest staging. Could someone please merge?

**Comment by lheckemann** [comment]
Oops, commented on the issue instead of the PR 🤦‍
