### ISSUE TITLE
qutebrowser is broken on some systems if vulkan support is enabled

### ISSUE THREAD

**Issue by mxkrsv** [NixOS/nixpkgs#264668]
### Describe the bug
Some critical graphics-related QtWebEngine problem arose after https://github.com/NixOS/nixpkgs/commit/8fa4bf50c1695b18e9f02a0030e00a5d58f3ef6c (#229149), rendering the browser unusable (hangs completely shortly after start) on an unknown range of NixOS systems.

Successfully worked it around for now with
```nix
pkgs.qutebrowser.override { enableVulkan = false; };
```

### Steps To Reproduce
1. Launch qutebrowser

Reproduced on latest nixos-unstable (`Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11.20231029.0cbe9f6`) on a Vega 8 graphics laptop (therefore the driver is mesa's `radv`).

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/59313755/9ab695e2-c966-40b8-8357-12dc88bcb427)

### Additional context
Under valgrind it crashes immediately.

### Notify maintainers
@nrdxp @jagajaga @rnhmjoj @ebzzry @dotlambda

**Comment by Misterio77** [comment]
I can reproduce the issue if using `amdvlk`, but seems to work fine with `radv`. Running a 7500xt.

**Comment by cpnfeeny** [comment]
This workaround in configuration.nix sorted it for me:

nixpkgs.config.packageOverrides = pkgs: {
    qutebrowser = pkgs.qutebrowser.override { enableVulkan = false; };
};

**Comment by lilyinstarlight** [comment]
> I'd say `enableVulkan` should default to `false`? Otherwise lots of people will have broken setups (as I did).

I wouldn't say mine is broken exactly, but it definitely has problems for me on i915 on Sway when Vulkan is enabled (copy/pasting freezes both qutebrowser and the app I was pasting to, right click takes a long time to register, I couldn't scroll some web pages with mouse any longer, etc)

If enough other people are encountering issues, it should maybe default to false for now, but I may just be an outlier here, idk
