### ISSUE TITLE
pkgsCross.aarch64-multiplatform.buildGoModule requires go to be built

### ISSUE THREAD

**Issue by Aleksanaa** [NixOS/nixpkgs#264775]
### Describe the bug
Building any go package with `pkgsCross.aarch64-multiplatform.buildGoModule` requires golang to be built locally.

### Steps To Reproduce
```
nix build nixpkgs#pkgsCross.aarch64-multiplatform.syncthing
```
or some other packages. It will show building go toolchain 1, 2 and 3.

### Expected behavior
Go package to use should be in cache of course.

### Notify maintainers

@zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
=> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.5-zen1, NixOS, 23.11 (Tapir), 23.11.20231006.87828a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/g68f5abh3xhcz8xsdlfw7wkgkkcx3nwy-source`
```

**Comment by Atemu** [comment]
Cross configs only have a very limited subset of packages built for them, that's intended. I don't think this policy will change any time soon due to unreasonable resource usage required to enable this rather niche use-case.
