### ISSUE TITLE
Package request: nekoray

### ISSUE THREAD

**Issue by rinlimerence** [NixOS/nixpkgs#264719]
**Project description**

This is qt-based cross-platform GUI proxy configuration manager. It is mainly used to connect a proxy with a backend of v2ray or sing-box.

Supports the following protocols: SOCKS, HTTP(S), Shadowsocks, VLESS, VMess, Trojan, etc (also supported custom core)

**Metadata**

* Homepage URL: https://github.com/MatsuriDayo/nekoray
* Source URL: https://github.com/MatsuriDayo/nekoray
* License: GNU General Public License v3.0
* Platforms: Linux, Windows

**Comment by eclairevoyant** [comment]
#244451
