### ISSUE TITLE
Fail to build python2.7-pycairo

### ISSUE THREAD

**Issue by lzhang10** [NixOS/nixpkgs#26475]
## Issue description
The URL to file `pycairo-1.10.0-waf_python_3_4-1.patch` is broken and can not be downloaded during build:
```
trying http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_python_3_4-1.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download pycairo-1.10.0-waf_python_3_4-1.patch from any mirror
...
cannot build derivation .../nix/store/f9ll92sns2d4y2njcvsfxb69hjcccimc-python2.7-pycairo-1.10.0.drv: 1 dependencies couldn't be built
```

### Steps to reproduce
- install latest nix on SL6
- update unstable channel
- run `nix-env -i xpra`

## Technical details

* System: (SL6)
* Nix version: nix-env (Nix) 1.11.9

**Comment by FRidh** [comment]
`nix-build -A python2.pkgs.pycairo --check` builds fine on both master and current `nixpkgs-unstable`.
It might have been possible the host was temporarily down.

**Comment by vcunat** [comment]
That URL is down.  `--check` doesn't redownload.

**Comment by lzhang10** [comment]
@vcunat I just noticed another broken URL needs to be fixed in `pkgs/development/python-modules/pycairo/default.nix`:

from:
`http://www.linuxfromscratch.org/patches/blfs/svn/pycairo-1.10.0-waf_unpack-1.patch;`
to
`http://www.linuxfromscratch.org/patches/blfs/8.0/pycairo-1.10.0-waf_unpack-1.patch;`

**Comment by vcunat** [comment]
@lzhang10: right, I could've noticed that.  Pushed as well, thanks.
