### ISSUE TITLE
Documentation: Firefox xdg portals settings 

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#264873]
## Problem

I already raised this issue in the [forums](https://discourse.nixos.org/t/clearification-about-firefox-and-kde-compatibility/34882/), but it seems like a better place for it is here. 
I experienced the [Wiki for Firefox](https://nixos.wiki/wiki/Firefox#Use_KDE_file_picker) as helpful for the configuration of the KDE Filemanager, as it show a working expression to configure this. 

Still, there are multiple settings who are left out. 

## Proposal

I suggest that we enlighten the reader about settings like `widget.use-xdg-desktop-portal.mime-handler` as to how and when they are useful. 

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

**Comment by K900** [comment]
The wiki is not an official documentation resource and can be edited by any user (including you). We don't keep lists of preferences in the manual.

**Comment by mweinelt** [comment]
The `programs.firefox.preferences` option lacks examples, so feel free to create a PR to add it with a comment explaining what it achieves.

**Comment by ShalokShalom** [comment]
I would need to know first for myself, how they behave :D
Thats exactly why I am raising this issue. 😃 
Thanks a lot
