### ISSUE TITLE
SteamVR 2.0.x not working

### ISSUE THREAD

**Issue by Scrumplex** [NixOS/nixpkgs#264896]
### Describe the bug
I am not sure if this is because of a change in Nixpkgs or in SteamVR, but I am not able to get SteamVR working anymore.

When launching SteamVR, I get an error (Error 405) about my graphics drivers needing to be updated.
![image](https://github.com/NixOS/nixpkgs/assets/11587657/1fc75ca8-af0c-4043-85ab-1fd2d83b8128)

The headset does not turn on (DRM device is not being leased) and the performance graph doesn't show any activity.

I can find the following error in SteamVR logs for vrcompositor:

```
WaylandHMDLeaseDevice::LeaseDevice_DrmFD: No libdrm.so
```

By replacing the launch command of SteamVR with a terminal, I was able to manually launch SteamVR (bypassing Steam Linux Runtime Sniper a.k.a. pressure-vessel based SLR) and it was working fine.

So this might be a deeper issue with libdrm not working properly with Steam Linux Runtime Sniper.

### Steps To Reproduce
1. Launch SteamVR using Steam

### Expected behavior
SteamVR working

### Notify maintainers

@mkg20001 @jagajaga @jonringer

@Atemu I have seen you in other issues regarding SteamVR, so I wanted to ask you if you could confirm this behavior.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9-zen2, NixOS, 23.11 (Tapir), 23.11.20231029.0cbe9f6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(scrumplex): `""`
 - nixpkgs: `/etc/nix/channels/nixpkgs`

```

**Comment by Atemu** [comment]
This worked for me last week. Some SteamVR component crashed during startup but that's sadly not abnormal and it did work as usual.

How are you installing steam? `programs.steam.enable`?

Which graphics driver, desktop environment and display server protocol is this? It worked on AMDGPU, i3 and X11 for me.

**Comment by Scrumplex** [comment]
> How are you installing steam? `programs.steam.enable`?

Yup

> 
> Which graphics driver, desktop environment and display server protocol is this? It worked on AMDGPU, i3 and X11 for me.

AMDGPU on Sway. This might be an issue with Wayland specifically here but I am not sure how exactly. As it works without the pressure-vessel based runtime, it could very well be some library that's missing during runtime.

I could try X11, too but I assume it is going to work fine there.

**Comment by Atemu** [comment]
I'd just try it. I'll also see if I can try it the other way around later today.

Just to make sure, you didn't switch/test any updates while the system was on in this boot? Mesa/libdrm is *not* compatible across different versions. If the compositor is running 23.1.7 and SteamVR 23.1.8, complications are expected.

**Comment by Scrumplex** [comment]
I usually have to reboot to make SteamVR work at all. Like I booted my PC a few hours ago and did a rebuild and switch without updating nixpkgs (home-manager and nixpkgs-wayland were updated) and I can't start SteamVR. `vrcompositor` fails with this error:

```
Thu Nov 02 2023 11:46:56.404337 [Info] - vrcompositor 2.0.10 startup with PID=66805, config=/home/scrumplex/.local/share/Steam/config, runtime=/home/scrumplex/.local/share/Steam/steamapps/common/SteamVR
Thu Nov 02 2023 11:46:56.404347 [Info] - VR compositor 2.0.10 (v1698775809) Mixed starting up
...
Thu Nov 02 2023 11:46:56.422317 [Info] - Events created
Thu Nov 02 2023 11:46:56.422680 [Info] - Found bad mirror window settings: 
Thu Nov 02 2023 11:46:56.422695 [Info] - Creating CHmdWindowSDL!
Thu Nov 02 2023 11:46:56.422737 [Info] - CHmdWindowSDL: Using Wayland
Thu Nov 02 2023 11:46:56.514413 [Error] - CHmdWindowSDL: Failed to initialize SDL vulkan
Thu Nov 02 2023 11:46:56.514500 [Error] - Error making window!
Thu Nov 02 2023 11:46:56.529812 [Info] - Failed to kill gpu-trace
Thu Nov 02 2023 11:46:56.529871 [Info] - Failed to initialize compositor
Thu Nov 02 2023 11:46:56.529891 [Info] - Failed to start compositor: VRInitError_Compositor_UnableToCreateDevice

```

This might be an different issue though

**Comment by Scrumplex** [comment]
Okay. I just tried my workaround of launching SteamVR without pressure-vessel-wrap, and it works, without rebooting. I guess pressure-vessel doesn't like it when I switch my NixOS config and don't reboot

**Comment by Scrumplex** [comment]
Something seems to have fixed this recently. I was able to launch SteamVR today without any problems.

**Comment by Atemu** [comment]
I had the opposite experience just today. Steam now installs the *windows* version of SteamVR on every start of Steam. Great. I have to select the steam runtime as compat tool for it to notice the error and download the Linux version again. That's 1G download on every start of Steam. It doesn't help that steam likes to crash with the new UI...

Given that this issue has probably always been a Valve issue, I think we can close this.
