### ISSUE TITLE
"Invalid URL" when updating channels on current nixos-unstable

### ISSUE THREAD

**Issue by K900** [NixOS/nixpkgs#264852]
This is a tracking issue for informational purposes.

Original issue: https://github.com/NixOS/nixpkgs/issues/264602

Fix: https://github.com/NixOS/nixpkgs/pull/264608 - [PR tracker](http://nixpk.gs/pr-tracker.html?pr=264608)
Followup: https://github.com/NixOS/nixpkgs/pull/264831 - [PR tracker](https://github.com/NixOS/nixpkgs/pull/264831)

Recovery instructions (run as root after the fix PRs are included in your desired channel):

```
# rm /root/.nix-channels
# nix-channel --add https://channels.nixos.org/nixos-unstable nixos
# nix-channel --update
```

**Comment by nikstur** [comment]
@K900 thank you!

**Comment by muiga** [comment]
followed the above instructions:
# rm /root/.nix-channels
# nix-channel --add https://channels.nixos.org/nixos-unstable nixos
# nix-channel --update

the issue still persists.  Running nix-channel  --list gives the output:
`➜  ~ sudo nix-channel --list
[sudo] password for muiga: 
" "
nixos "https://nixos.org/channels/nixos-unstable
➜  ~ 
`

**Comment by K900** [comment]
Did you run the commands with `#` prepended? That's an indicator of a root shell prompt, as in "you need to run those as root".

**Comment by muiga** [comment]
No. I ran the commands stated but after  a nixos-rebuild switch command the issue returned.

**Comment by K900** [comment]
The fix has not made it to nixos-unstable yet, so that is to be expected.

**Comment by muiga** [comment]
> The fix has not made it to nixos-unstable yet, so that is to be expected.

Okay thanks..

**Comment by nikstur** [comment]
The final fix has made it into nixos-unstable now.

**Comment by rollschild** [comment]
The fix worked for unstable channel. Thanks.

**Comment by goodboy** [comment]
Can confirm that [this](https://github.com/NixOS/nixpkgs/issues/264852#issuecomment-1790266541) also worked for me 🥳
