### ISSUE TITLE
Update request: python3Packages.setuptools-scm  7.1.0 → 8.0.4

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#264820]
- Package name: [python3Packages.setuptools-scm](https://github.com/pypa/setuptools_scm)
- Latest released version: [8.0.4](https://github.com/pypa/setuptools_scm/releases/tag/v8.0.4)

- Current version on the unstable channel: 7.1.0
- Current version on the stable/release channel: 7.1.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NickCao

Last updated by: @mweinelt 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by mweinelt** [comment]
We're currently in breaking changes freeze until the 20th of November, see https://github.com/NixOS/nixpkgs/issues/258640.

As setuptools-scm is directly referenced in over 500 packages and the package would cross a major version boundary, that would be too risky.
