### ISSUE TITLE
flowblade-2.10.0.4 built with mlt-7.20 doesn't start

### ISSUE THREAD

**Issue by head-gardener** [NixOS/nixpkgs#264868]
```
FLOWBLADE MOVIE EDITOR 2.10.0.4
-------------------------------
Launch script dir: /nix/store/kddzdraycracw4r0q4qva1yvhxclznq7-flowblade-2.10.0.4/flowblade
Running from filesystem...
MLT found, version: 7.20.0
numpy version: 1.25.2
Application version: 2.10.0
OS: NixOS 23.05 (Stoat)
Python 3.11.5 (main, Aug 24 2023, 12:23:19) [GCC 12.3.0]
GTK+ version: 3.24.38
...
restacking compositors!
Adding full track compositors DONE
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Selected color NOT detected
BG color detected
[mlt_producer 0x2238330] <playlist>
    Playlist can not create blank producer without profile
[mlt_producer 0x2238330] <playlist>
    Playlist can not create blank producer without profile
fish: Job 1, 'flowblade' terminated by signal SIGSEGV (Address boundary error)
```

`flowblade-2.10.0.2`, installed from unstable doesn't start. `2.10.0.2` from 5a86504, which ships `mlt-7.16.0`, runs fine.

This issue has recently been reported [on arch forums](https://bbs.archlinux.org/viewtopic.php?id=289742) and [project's issues](https://github.com/jliljebl/flowblade/issues/1129).

I'm fairly new to Nix, but my assumption is that `mlt` should be a runtime dependency of `flowblade`, since the script imports `mlt7` at runtime. Does that mean `flowblade` should be a referrer of `mlt`? Because it isn't. On that note, `gmic` is basically a runtime dependency - mostly unusable on stable due to gmic's command rework. Wish `flowblade` had it's dependencies pinned, since they are quite specific for the two mentioned packages.
Edit: the mlt referrer digression turns out to be incorrect, but pinning still bothers me.

@polygon

**Comment by yaitskov** [comment]
for me older version of flowblade (2.8) are crashing too.

**Comment by head-gardener** [comment]
@yaitskov same reason?
