### ISSUE TITLE
lxc fails to start

### ISSUE THREAD

**Issue by evrim** [NixOS/nixpkgs#26494]
## Issue description
Hello,

I've run into trouble w/ lxc. 
't1' is ubuntu/amd64/artful create using lxc-create -n t1 -t download

$ lxc-ls
t1   
$ lxc-start -n t1
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 368 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.
$ lxc-start -n t1 -F
lxc-start: cgroups/cgfs.c: lxc_cgroupfs_create: 1022 Permission denied - Could not create cgroup '/lxc' in '/sys/fs/cgroup/freezer'.
lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/pids/user.slice/user-1000.slice/session-1.scope
lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory/
 lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpu,cpuacct/  
lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer/
lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpuset/
lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/devices/user.slice
 lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/net_cls/
 lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio/
 lxc-start: cgroups/cgfs.c: cgroup_rmdir: 209 Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-1.scope
lxc-start: start.c: lxc_spawn: 1108 Failed creating cgroups.
 lxc-start: start.c: __lxc_start: 1346 Failed to spawn container "t1".
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

## Technical difficulties [racer X]
$ cat /etc/nixos/configuration.nix|grep lxc
  virtualisation.lxc.enable = true;
$ cat /etc/lxc/default.conf 

$ cat ~/.config/lxc/default.conf
lxc.include = /etc/lxc/default.conf
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.aa_allow_incomplete = 1

$ nixos-version 
17.03.1264.9ed5dbafe3 (Gorilla)

**Comment by Mic92** [comment]
You need `cgmanager` and `lxcfs`, when using unprivileged containers. The configuration of lxcfs also needs to be include in your container configuration.

**Comment by evrim** [comment]
lxcfs over fuse, interesting.

$ nix-env -iA nixos.cgmanager
installing ‘cgmanager-0.41’
building path(s) ‘/nix/store/9a36hff2syrhma84yagby4gvjmq2g057-user-environment’
created 2445 symlinks in user environment
$ nix-env -iA nixos.lxcfs
installing ‘lxcfs-unstable-2017-03-02’
building path(s) ‘/nix/store/sqk8bidmpb2jv4w80rhx7wi4pddxava3-user-environment’
created 2454 symlinks in user environment

\# systemctl |grep cgm
cgmanager.service                                                                                          loaded active running   Cgroup management daemon                                                  
$ sudo cgm create all me
$ sudo cgm chown all me $(id -u) $(id -g)
$ sudo cgm movepid all me $$
$ lxc-start -n t1 -F
lxc-start: lsm/apparmor.c: apparmor_process_label_set: 220 If you really want to start this container, set
                                                                                                          lxc-start: lsm/apparmor.c: apparmor_process_label_set: 221 lxc.aa_allow_incomplete = 1
lxc-start: lsm/apparmor.c: apparmor_process_label_set: 222 in your container configuration file
                                                                                               lxc-start: sync.c: __sync_wait: 57 An error occurred in another process (expected sequence number 5)
   lxc-start: start.c: __lxc_start: 1346 Failed to spawn container "t1".
                                                                        lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing blkio:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing cpu,cpuacct:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing cpuset:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing devices:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing freezer:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing memory:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing net_cls:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing pids:lxc/t1
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 534 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgroups/cgmanager.c: cgm_remove_cgroup: 536 Error removing name=systemd:lxc/t1
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

I must be doing terribly wrong to get 'invalid request' :( I'll try again tmrrw, thnx.

**Comment by Mic92** [comment]
lxcfs also needs to be started as service. There is a module in nixos for that.

**Comment by Mic92** [comment]
```
 users.extraUsers.root = { # or whatever user you use for lxc
   subUidRanges = [ { startUid = 100000; count = 65536; } ];
   subGidRanges = [ { startGid = 100000; count = 65536; } ];
 };
virtualisation.lxc = {
  enable = true;
  lxcfs.enable = true; # this will also start cgmanager
  defaultConfig = ``
     # ...
     lxc.include = ${pkgs.lxcfs}/share/lxc/config/common.conf.d/00-lxcfs.conf
     lxc.include = ${pkgs.lxc}/share/lxc/config/userns.conf
  ``;
};

```

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by Atemu** [comment]
Is this still an issue?

**Comment by evrim** [comment]
@Atemu hey there, I have no means of testing it atm, maybe somebody know better than me about the current situation.

**Comment by adamcstephens** [comment]
Stale. Please open if still an issue.
