### ISSUE TITLE
services.kubo: state-related "cannot connect to the api" error

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#265048]
### Describe the bug

After some sequence of actions that I couldn't yet identify (presumably, some of the `ipfs add --pin` commands) the ipfs service becomes unresponsive like so:

```bash
❯ id
...
groups=...,261(ipfs)
❯ ipfs config show
Error: cannot connect to the api. Is the daemon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api`
❯ ipfs add --pin thing.pth 
Error: cannot connect to the api. Is the daemon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api`
❯ ipfs get QmR8k6jDhmFdaveqp3C7u2UaomJcQvmYbG7V5vDUne1mPL
Error: cannot connect to the api. Is the daemon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api`
❯ systemctl status ipfs.service
● ipfs.service - InterPlanetary File System (IPFS) daemon
     Loaded: loaded (/etc/systemd/system/ipfs.service; enabled; preset: enabled)
    Drop-In: /nix/store/v98qzx1zzingvvmi51h3mpp7x8q711mf-system-units/ipfs.service.d
             └─overrides.conf
     Active: active (running) since Tue 2023-10-31 19:28:36 UTC; 1 day 20h ago
     ...
❯ cat $IPFS_PATH/api
/unix/run/ipfs.sock
❯ stat /run/ipfs.sock 
  File: /run/ipfs.sock
  Size: 0               Blocks: 0          IO Block: 4096   socket
Device: 0,22    Inode: 2054        Links: 1
Access: (0660/srw-rw----)  Uid: (  261/    ipfs)   Gid: (  261/    ipfs)
...
```

### Steps To Reproduce

The actual configuration I'm running is:

<details>

```nix
  services.kubo.enable = true;
  services.kubo.enableGC = true;
  services.kubo.autoMount = true;
  services.kubo.settings.Addresses.API = [ "/ip4/127.0.0.1/tcp/2324" ];
  services.kubo.settings.Addresses.Gateway = [ "/ip4/yyyyyy/tcp/8080" ];
  services.kubo.settings.Gateway.NoFetch = true;
  services.kubo.settings.Gateway.PublicGateways."ipfs.xxxxxx.net" = {
    Paths = [ "/ipfs" ];
  };
  services.kubo.settings.Gateway.PublicGateways."ipfs.zzzzz.net" = {
    Paths = [ "/ipfs" ];
  };

  services.kubo.settings.Mounts.FuseAllowOther = true;

  systemd.services.chmod-kubo = {
    enable = true;
    script = ''
      chmod -R g+rx "${config.services.kubo.dataDir}"
    '';
    after = [ "ipfs.service" ];
    requiredBy = [ "ipfs.service" ];
  };

```

</details>

However, switching to the minimal configuration below does not fix the issue if I retain the mutable data:

```nix
    services.kubo.enable = true;
```

It also takes a reboot before `ipfs.service` can successfully start after switching between these configurations. The error is:

```
ipfs[2230092]: panic: runtime error: index out of range [0] with length 0
ipfs[2230092]: goroutine 1 [running]:
ipfs[2230092]: main.serveHTTPApi(0xc000234bd0, 0xc0000d43c0)
ipfs[2230092]:         github.com/ipfs/kubo/cmd/ipfs/daemon.go:726 +0x1173
ipfs[2230092]: main.daemonFunc(0xc000234bd0, {0x235cce0?, 0x2c7c278?}, {0x256e0c0?, 0xc0000d43c0})
ipfs[2230092]:         github.com/ipfs/kubo/cmd/ipfs/daemon.go:507 +0x1b31
ipfs[2230092]: github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc00026c0c0?, 0xc000234bd0, {0x7f62dc107848, 0xc0002a50e0}, {0x256e0c0, 0xc0000d43c0})
ipfs[2230092]:         github.com/ipfs/go-ipfs-cmds@v0.10.0/executor.go:88 +0x135
ipfs[2230092]: main.tracingWrappedExecutor.Execute({{0x2c88ca0?, 0xc0007d8098?}}, 0xc000234bd0, {0x7f62dc107848, 0xc0002a50e0}, {0x256e0c0, 0xc0000d43c0})
ipfs[2230092]:         github.com/ipfs/kubo/cmd/ipfs/main.go:352 +0x3cb
ipfs[2230092]: github.com/ipfs/go-ipfs-cmds/cli.Run({0x2c9e8f0?, 0xc000374e10?}, 0x3e3a8c0, {0xc000052040, 0x2, 0x2}, 0x2827fb0a44cba?, 0x0?, 0xc0000a4038, 0x2a51e60, ...)
ipfs[2230092]:         github.com/ipfs/go-ipfs-cmds@v0.10.0/cli/run.go:137 +0x8e3
ipfs[2230092]: main.mainRet()
ipfs[2230092]:         github.com/ipfs/kubo/cmd/ipfs/main.go:199 +0x4f6
ipfs[2230092]: main.main()
ipfs[2230092]:         github.com/ipfs/kubo/cmd/ipfs/main.go:84 +0x13
systemd[1]: ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: ipfs.service: Failed with result 'exit-code'.
systemd[1]: Failed to start InterPlanetary File System (IPFS) daemon.
systemd[1]: ipfs.service: Consumed 437ms CPU time, received 87.3K IP traffic, sent 69.8K IP traffic.
systemd[1]: ipfs.service: Scheduled restart job, restart counter is at 5.
systemd[1]: ipfs.service: Start request repeated too quickly.
systemd[1]: ipfs.service: Failed with result 'exit-code'.
systemd[1]: Failed to start InterPlanetary File System (IPFS) daemon.
systemd[1]: ipfs.service: Consumed 437ms CPU time, received 87.3K IP traffic, sent 69.8K IP traffic.

```

### Notify maintainers

@Luflosi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231029.90e85bc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(ss): `"nixgl"`
 - channels(root): `"nixgl, nixos-21.05.2132.733682c3292"`
 - nixpkgs: `/nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source`
[user@system:~]$ nix flake metadata nixpkgs
Resolved URL:  path:/nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source?lastModified=1698553279&narHash=sha256-T/9P8yBSLcqo/v%2BFTOBK%2B0rjzjPMctVymZydbvR/Fak%3D&rev=90e85bc7c1a6fc0760a94ace129d3a1c61c3d035
Locked URL:    path:/nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source?lastModified=1698553279&narHash=sha256-T/9P8yBSLcqo/v%2BFTOBK%2B0rjzjPMctVymZydbvR/Fak%3D&rev=90e85bc7c1a6fc0760a94ace129d3a1c61c3d035
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/kii30vrsz832yg94v9w2imlwn8pp69xq-source
Revision:      90e85bc7c1a6fc0760a94ace129d3a1c61c3d035
Last modified: 2023-10-29 04:21:19
```

**Comment by alciono** [comment]
I have the same issue. Any progress?

**Comment by SomeoneSerge** [comment]
> I have the same issue. Any progress?

Sorry, I didn't have the time so I nuked the dataDir and now it works. Would be nice to make nixosTests reproducer though

**Comment by alciono** [comment]
Thank you for helping.

I am not familiar with this; could you please give me the steps to "nuke the dataDir" and get it to work? 

Many thanks.

**Comment by SomeoneSerge** [comment]
@alciono  I did something like:

```bash
$ sudo systemctl stop ipfs
$ sudo rsync /var/lib/ipfs/ ~/ipfs.backup/ -aP
$ sudo rm -rf /var/lib/ipfs/
$ sudo systemctl start ipfs
```

If you should have further questions, I recommend that write in [https://matrix.to/#/#nix:nixos.org](https://matrix.to/#/%23nix%3Anixos.org?via=someonex.net&via=matrix.org&via=tchncs.de&via=snug.si). Also feel free ping me there! If you find a way to reproduce the failure again though, please do follow up in the current issue. Thank you!

**Comment by Luflosi** [comment]
I don't know about the first issue, that might be a bug in Kubo itself but I really don't know.
Your second problem (Kubo crashing with `panic: runtime error: index out of range [0] with length 0`) is the same issue as #248447 and should be fixed by #272041.

Some minor comments on your configuration unrelated to the problems you encountered:
- You don't need to set `services.kubo.settings.Mounts.FuseAllowOther` to `true` as that is already the default when `services.kubo.autoMount` is set to `true`. Perhaps I should somehow make this more obvious as figuring this out currently requires reading the NixOS module source code
- If you only access the API with the `ipfs` CLI tools, you shouldn't need to set `services.kubo.settings.Addresses.API` and shouldn't need your `chmod-kubo` hack anymore. Since #226288 the daemon listens on a Unix domain socket by default and if you add your user to the correct group as described in the documentation https://search.nixos.org/options?channel=unstable&show=services.kubo.settings.Addresses.API&query=kubo and log out and back in for the `IPFS_PATH` environment variable to be in your shell, the CLI tools should just work™️

**Comment by Luflosi** [comment]
#272041 was merged so that issue should be fixed.
As for your original issue, as I said I think it might be an issue in Kubo itself. If it ever happens again, please ping me and we can try to debug it together. Until then, I feel like there is no value in keeping this issue open but if you disagree, please reopen it or create a new one.

**Comment by samualtnorman** [comment]
is this definitely fixed?
after adding `services.kubo.enable = true;` and running `ipfs cat`, I get
```
Error: cannot connect to the api. Is the daemon running? To run as a standalone CLI command remove the api file in `$IPFS_PATH/api
```
the contents of the file at `$IPFS_PATH/api` is
```
/unix/run/ipfs.sock
```
but `ls `ls $(cat $IPFS_PATH/api)` gives me
```
ls: cannot access '/unix/run/ipfs.sock': No such file or directory
```
the actual path of this `api` file is `/run/ipfs.sock` not `/unix/run/ipfs.sock`

**Comment by Luflosi** [comment]
This is definitely fixed.
It works on my machines and mostly the sme thing in a [NixOS test](https://github.com/NixOS/nixpkgs/blob/11bc6db58203ae1180b6b349e1d669a7a244b433/nixos/tests/kubo/kubo.nix). 
The contents of `$IPFS_PATH/api` being `/unix/run/ipfs.sock` is normal. This is a multiaddr: https://github.com/multiformats/multiaddr/blob/5a179104a6f9e9a2c95562496c88bf514871a1d3/protocols.csv#L16, which is what Kubo expects.
What I think is happening, is that you didn't add your user to the correct group as described [in the documentation of `services.kubo.settings.Addresses.API`](https://search.nixos.org/options?channel=unstable&show=services.kubo.settings.Addresses.API&from=0&size=50&sort=relevance&type=packages&query=kubo). I admit, this is pretty hidden and should probably be mentioned in the docs of `services.kubo.enable`. I think you also need to log out and back in for the group change to take effect.

**Comment by samualtnorman** [comment]
> This is definitely fixed. It works on my machines and mostly the sme thing in a [NixOS test](https://github.com/NixOS/nixpkgs/blob/11bc6db58203ae1180b6b349e1d669a7a244b433/nixos/tests/kubo/kubo.nix). The contents of `$IPFS_PATH/api` being `/unix/run/ipfs.sock` is normal. This is a multiaddr: https://github.com/multiformats/multiaddr/blob/5a179104a6f9e9a2c95562496c88bf514871a1d3/protocols.csv#L16, which is what Kubo expects. What I think is happening, is that you didn't add your user to the correct group as described [in the documentation of `services.kubo.settings.Addresses.API`](https://search.nixos.org/options?channel=unstable&show=services.kubo.settings.Addresses.API&from=0&size=50&sort=relevance&type=packages&query=kubo). I admit, this is pretty hidden and should probably be mentioned in the docs of `services.kubo.enable`. I think you also need to log out and back in for the group change to take effect.

oh my bad.
yeah I (and future people I think) would appreciate it if it was mentioned in the docs for `services.kubo.enable`.
thank you!

**Comment by samualtnorman** [comment]
> This is definitely fixed. It works on my machines and mostly the sme thing in a [NixOS test](https://github.com/NixOS/nixpkgs/blob/11bc6db58203ae1180b6b349e1d669a7a244b433/nixos/tests/kubo/kubo.nix). The contents of `$IPFS_PATH/api` being `/unix/run/ipfs.sock` is normal. This is a multiaddr: https://github.com/multiformats/multiaddr/blob/5a179104a6f9e9a2c95562496c88bf514871a1d3/protocols.csv#L16, which is what Kubo expects. What I think is happening, is that you didn't add your user to the correct group as described [in the documentation of `services.kubo.settings.Addresses.API`](https://search.nixos.org/options?channel=unstable&show=services.kubo.settings.Addresses.API&from=0&size=50&sort=relevance&type=packages&query=kubo). I admit, this is pretty hidden and should probably be mentioned in the docs of `services.kubo.enable`. I think you also need to log out and back in for the group change to take effect.

I got it working thanks to your instructions however I thought you might want to know that a simple log out login was not enough to make the error go away. I needed to reboot my pc.

**Comment by Luflosi** [comment]
Okay, thanks for the feedback.

**Comment by permezel** [comment]
Same problem for me, even after reboot.  Turns out I needed to `chmod 666 /run/ipfs.sock` and then it started to work.
