### ISSUE TITLE
hipcc straight up broken

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#265095]
### Describe the bug
hipcc not even shows --help

### Steps To Reproduce
1. bring `rocmPackages.hipcc` to a shell
2. `hipcc --help`
3. `Can't exec "/usr/local/cuda/bin/nvcc": No such file or directory at /nix/store/xs85f29kps1d5p69fhrcgl47a466zscs-hipcc-5.7.0/bin//hipcc.pl line 634.
failed to execute: No such file or directory`

### Expected behavior
Help message

### Notify maintainers

@NixOS/rocm-maintainers 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.2`
 - nixpkgs: `/nix/store/ki98w9ah1k5p62mfv5pjbb58szndc2g5-source`

```

**Comment by lucasew** [comment]
Same for  `rocmPackages_5.hipcc`

**Comment by Madouura** [comment]
You need to use ``rocmPackages_5.clr``.
The ``hipcc`` package itself doesn't include the wrapper.

**Comment by Madouura** [comment]
Maybe I should move ``hipcc`` and ``hip-common`` into ``clr`` to avoid this sort of issue in the future.

**Comment by davidak** [comment]
@Madouura i had a similar issue.

I wanted to test if HIP is setup correctly and found this test: https://rocm.docs.amd.com/projects/HIP/en/latest/how_to_guides/debugging.html#debugging-hip-applications

So i tried hipcc from the hipcc package. It's broken:

```
[davidak@gaming:~]$ nix-shell -p rocmPackages.hipcc
this path will be fetched (0.43 MiB download, 3.66 MiB unpacked):
  /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1
copying path '/nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1' from 'https://cache.nixos.org'...

[nix-shell:~]$ hipcc app.cpp -o app
Can't exec "/opt/rocm/llvm/bin/clang": No such file or directory at /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1/bin//hipcc.pl line 175.
Use of uninitialized value $HIP_CLANG_RT_LIB in scalar chomp at /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1/bin//hipcc.pl line 176.
Can't exec "/opt/rocm/bin/rocm_agent_enumerator": No such file or directory at /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1/bin//hipcc.pl line 487.
Use of uninitialized value $targetsStr in substitution (s///) at /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1/bin//hipcc.pl line 488.
Use of uninitialized value $targetsStr in split at /nix/store/iwl6aad529v3l2m1g7w5l75dc4m0b1am-hipcc-5.7.1/bin//hipcc.pl line 494.
sh: line 1: /opt/rocm/llvm/bin/clang: No such file or directory
```

Using hipcc from the `rocmPackages.clr` package does work, but it's not obvious to the user to use that and not the hipcc package.

It would be good if the hipcc package does what a user expects. Maybe make it an alias for clr?
