### ISSUE TITLE
GNS3 broken

### ISSUE THREAD

**Issue by pzant** [NixOS/nixpkgs#265087]
### Describe the bug
Fatal Python error: Aborted

Current thread 0x00007f2ae6289740 (most recent call first):
  File "/nix/store/462l2rqy1xgnp5pgg4z8v6h1a0rf4shy-python3.10-gns3-gui-2.2.35.1/lib/python3.10/site-packages/gns3/application.py", line 47 in __init__
  File "/nix/store/462l2rqy1xgnp5pgg4z8v6h1a0rf4shy-python3.10-gns3-gui-2.2.35.1/lib/python3.10/site-packages/gns3/main.py", line 231 in main
  File "/nix/store/462l2rqy1xgnp5pgg4z8v6h1a0rf4shy-python3.10-gns3-gui-2.2.35.1/bin/.gns3-wrapped", line 9 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtNetwork, PyQt5.QtWidgets, gns3.qt.QtCore, gns3.qt.QtGui, gns3.qt.QtNetwork, gns3.qt.QtWidgets, PyQt5.QtSvg, gns3.qt.QtSvg, PyQt5.QtWebSockets, gns3.qt.QtWebSockets, psutil._psutil_linux, psutil._psutil_posix, pvectorc, _brotli (total: 16)
Aborted (core dumped)

### Steps To Reproduce
1. environment.systemPackages = with pkgs; [  dynamips ubridge  vpcs  gns3-gui gns3-server ];
2. $ gns3

### Expected behavior
Application launch is expected.

### Notify maintainers
@anthonyroussel

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.05 (Stoat), 23.05.20231024.04f431f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lorenz** [comment]
Are you on Wayland? Try applying https://github.com/NixOS/nixpkgs/pull/262437, that should fix it.

**Comment by pzant** [comment]
Yes. Wayland.
I did this temporarily. Maybe it could be written shorter and more correctly?
`(gns3-gui.overrideAttrs (oldAttrs: rec { propagatedBuildInputs =  oldAttrs.propagatedBuildInputs ++ [ qt5.qtwayland ]; }))`
