### ISSUE TITLE
Build failure: pgadmin4 7.7

### ISSUE THREAD

**Issue by gallexme** [NixOS/nixpkgs#265079]
### Steps To Reproduce

1. build pgadmin4 on unstable

### Build log

(https://gist.github.com/gallexme/717cf2fac4c30bae8514a8953bf41ad4)

### Additional context

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/flask-mongoengine/default.nix

likely because this hasnt been updated to a new master branch revision, since the maintainer of the software does not seem to publish tags/releases on github or pypy, but the issue should been resolved for over a year
https://github.com/MongoEngine/flask-mongoengine/commit/d283967f012463833c683746f86df1a2212a0eed 

### Notify maintainers

@gador  
@fabaff  as last touched :)
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console

[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.8-xanmod1, NixOS, 23.11 (Tapir), 23.11.20231029.0cbe9f6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs

```

(btw this took 6minutes  and 45 seconds to run on my pc, but on other pc 0.8s)

**Comment by gador** [comment]
Should be fixed by #262702

See https://nixpk.gs/pr-tracker.html?pr=262702 for the current status for `unstable`

**Comment by fabaff** [comment]
I saw the failure in #264302. Thanks for fixing it.

**Comment by gador** [comment]
PR is merged in `unstable`. Please re-open, if the issue persists.
