### ISSUE TITLE
Package request: Arduino IDE 2.0

### ISSUE THREAD

**Issue by libewa** [NixOS/nixpkgs#265011]
**Project description**
The Arduino IDE available on nixpkgs is the v1 version made in Java.
There is a new v2 version based on Electron, which is currently not usable on NixOS, as the AppImage and zipfile versions both crash with missing libraries (libsecret for the AppImage and libgobject for the zip file).

**Metadata**

* homepage URL: [arduino.cc](https://arduino.cc/)
* source URL: [https://github.com/arduino/arduino-ide](https://github.com/arduino/arduino-ide)
* license: agpl-3.0
* platforms: linux, windows, darwin

**Comment by TomaSajt** [comment]
I'll see what I can do

**Comment by kashw2** [comment]
closed in https://github.com/NixOS/nixpkgs/pull/272554

**Comment by libewa** [comment]
thank you

**Comment by miskatul-anwar** [comment]
Not available yet?
