### ISSUE TITLE
rofi plugins and rofi-wayland

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#265122]
menu application `rofi` has a dozen plugins on nixpkgs, but using Wayland port `rofi-wayland` package instead the plugins appear not to work yet.

as per https://discourse.nixos.org/t/rofi-on-wayland-and-plugins/17354, a workaround that may work is this:

```
nixpkgs.overlays = [(final: prev: {
  rofi-calc = prev.rofi-calc.override { rofi-unwrapped = prev.rofi-wayland-unwrapped; };
})];
```

**Comment by KiaraGrouwstra** [comment]
hm seems like `rofi -show calc` works

**Comment by nonetrix** [comment]
I am having same issue with rofimoji, download it with `nixpkgs -p rofimoji` and then it uses XWayland version :/

**Comment by nonetrix** [comment]
@justinlovinger am I just using your package wrong or something? Only way I could get it working nicely, at least should be documented somewhere or something idk

**Comment by justinlovinger** [comment]
> @justinlovinger am I just using your package wrong or something? Only way I could get it working nicely, at least should be documented somewhere or something idk

That is correct. `rofimoji` differentiates between Wayland-clipboard support and Wayland-rofi support, so we do too.

Actually, now that `rofimoji` supports many different selectors, there is an argument to be made for not wrapping `rofi` with the binary and instead relying on selectors in your environment.
