### ISSUE TITLE
Chromium won't start under hardened profile

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#26511]
I've just switched to the [hardened profile][1], and Chromium now
fails to start, saying —

> [31931:31931:0611/032643.444522:FATAL:credentials.cc(137)] Check failed: error == EPERM || error == EUSERS || error == EINVAL || error == ENOSYS. : No space left on device

[A comment][2] in the hardened profile's definition says that "No
space left on device" is the error message generated if a program
tries to create a user namespace when user namespaces are, as under
the hardened profile, disabled via sysctl.

[Chromium documentation][3] says that Chromium does indeed use user
namespaces, as well as BPF, another thing that the hardened profile
disables or at least restricts.

I'm not sure Chromium not working is necessarily a bug, but I think it
at least worthy of a report.

[1]: <https://github.com/NixOS/nixpkgs/blob/73a1307a02bcd87c2d4df6ccd3d216373d2e59c3/nixos/modules/profiles/hardened.nix>
[2]: <https://github.com/NixOS/nixpkgs/blob/73a1307a02bcd87c2d4df6ccd3d216373d2e59c3/nixos/modules/profiles/hardened.nix#L60>
[3]: <https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_sandboxing.md>

**Comment by 8573** [comment]
If I use `sysctl` to lift the limit on user namespaces, Chromium
appears to work without any intervention for BPF.

Perhaps there might be a way to disable user namespaces for all but
select programs.

**Comment by 8573** [comment]
It seems that I can either enable user namespaces and their
accompanying vulnerabilities, and use Chromium's user namespace
sandbox, or enable setuid bits and their accompanying vulnerabilities,
and use Chromium's setuid sandbox.

Perhaps a silver bullet for permitting the use of these features by
Chromium only might be found in SELinux, though last I heard there's
no support for SELinux in NixOS.

**Comment by 7c6f434c** [comment]
I think chromium has `--no-sandbox` flag? Of course, you lose isolation of parts of Chromium in this case, but at least you can isolate entire Chromium inside a different user.

**Comment by joachifm** [comment]
re: selinux, I believe it is compiled in but disabled by default. One problem with label based mac is that NARs don't store xattrs, so you'd have to relabel stuff all the time (which also meshes poorly with read-only stores).

**Comment by joachifm** [comment]
re suid vs userns, I think it's easier to audit a suid stub than it is to audit the privilege checks within the kernel in the presence of namespacing, so you might be better off with the suid sandbox ...

**Comment by 8573** [comment]
Oh, I see I already have setuid bits enabled for my root filesystem;
Chromium's setuid sandbox doesn't work because I never enabled
`security.chromiumSuidSandbox.enable`. I'll try turning that on after
nixos-unstable updates and I can rebuild again without hitting #26431.

**Comment by 8573** [comment]
On the other hand, Chromium seems to want to drop the setuid sandbox
(<https://bugs.chromium.org/p/chromium/issues/detail?id=312380> etc.),
so using it may not be a sustainable solution.

**Comment by joachifm** [comment]
I'd bet on the suid sandbox (or something like it) to stay around for a while.  I believe Debian disables unprivileged userns by default (via kernel patch) while Arch Linux disables them outright. My impression is that the NixOS kernel is somewhat unusual in supporting _unprivileged_ userns creation out-of-the-box.

**Comment by 8573** [comment]
I've set the NixOS option `security.chromiumSuidSandbox.enable` to
`true` and the sysctl parameter `user.max_user_namespaces` back to
`0`, and Chromium seems to work.

**Comment by NeQuissimus** [comment]
The error in the original post also occurs for `hipchat`, which does not seem to honour `CHROME_DEVEL_SANDBOX` in the env.

**Comment by joachifm** [comment]
Closing this for now, seems to me there's not much more to do here. Please reopen if I'm mistaken.
