### ISSUE TITLE
Setting `environment.noXlibs = true` causes openjdk to rebuild

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#26523]
## Issue description
Setting `environment.noXlibs = true` causes openjdk to rebuild from source.
In particular, it changes `dbus` package, which is a dep for some graphical stuff in JDK.

As a solution, I'd like `openjdk_minimal` and build it on hydra.
Another solution, is not to use `environment.noXlibs = true` on JDK-enabled servers... Not a big deal, in fact. Just wanted to document this.

### Steps to reproduce
Set the above-mentioned option and configure `services.tomcat.enable = true;`

## Technical details

* System: nixos-17.03
* Nixpkgs version: 05126bc8503a37bfd2fe80867eb5b0bea287c633

**Comment by joachifm** [comment]
`openjdk_minimal` sounds sensible to me.

**Comment by wfranzini** [comment]
Hi,

setting this flag rebuilds not only openjdk, but, I suspect, any x-enabled program installed (eg. emacs).
It should be at least documented.

**Comment by SuperSandro2000** [comment]
Going to close this, as noXlibs got removed.
