### ISSUE TITLE
clash: Source code deleted

### ISSUE THREAD

**Issue by ShadowRZ** [NixOS/nixpkgs#265200]
Reference: https://github.com/net4people/bbs/issues/303

The source code for `github:Dreamacro/clash` has been confirmed deleted
and I think maintainers should be pinged for performing necessary
actions.

### Ping maintainers

* `pkgs.clash`: @contrun @Br1ght0ne

**Comment by FliegendeWurst** [comment]
It's easy to get the source code from the cache: (like in #149201)
```bash
$ nix repl '<nixpkgs>'
warning: future versions of Nix will require using `--file` to load a file
Welcome to Nix 2.13.6. Type :? for help.

Loading installable ''...
Added 19224 variables.
nix-repl> :b pkgs.clash.src

This derivation produced the following outputs:
  out -> /nix/store/ws91h2rhd191mpi6rmc8iqf4qjdsl84d-source
```

**Comment by AndersonTorres** [comment]
The relevant action is to delete the package.
