### ISSUE TITLE
Package request: hugo-extended

### ISSUE THREAD

**Issue by poach3r** [NixOS/nixpkgs#265292]
**Project description**

Plug-and-play binary wrapper for Hugo Extended, the awesomest static-site generator.

**Metadata**

* homepage URL: https://www.npmjs.com/package/hugo-extended
* source URL: https://github.com/jakejarvis/hugo-extended
* license: MIT
* platforms: linux

**Comment by eclairevoyant** [comment]
This is already packaged under `hugo`
