### ISSUE TITLE
How to reset all confgi files of a package?

### ISSUE THREAD

**Issue by jarry9** [NixOS/nixpkgs#26533]
Hi,

A nix package runs as native on operating system. It is not like docker or chroot. Thats why it uses HOME folder of the current user. And when we close the app, the config files are not deleting.

I try many different versions of the same app on a user. So the app crashes sometimes. Because it reads old/new version's config files.

I know it is not possible to reset the config files of an app. But on linux Hierarchy ( https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) most of the config files are storing to HOME folder + "/etc" directory. So, Is there any way to start a package by setting "etc" and "Home" directory custom?

Thank you

**Comment by 7c6f434c** [comment]
>Is there any way to start a package by setting "etc" and "Home" directory custom?

`HOME="$(mktemp -d)" command --with arguments` should work for
overriding home directory for most packages (OpenSSH would say this is
not secure and take the entry from `/etc/passwd`, though).

`/etc/` is a fixed absolute path, but as a user you are cannot write to
most places in `/etc/` anyway (and you definitely cannot write to
`/nix/store/hash-name-version/etc/`, in case package uses it).

**Comment by jarry9** [comment]
Thank you. To change HOME variable worked.
