### ISSUE TITLE
PySide2 Compatibility Issues in Python 3.11

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#265309]
### Describe the bug
Since updating my flake configuration, I have been encountering an error while attempting to rebuild the system over the past couple of days, specifically:
```
… while calling 'disabled'

         at /nix/store/a56i1y5js340dn1w9r767a8jp34k31n4-source/pkgs/development/interpreters/python/python-packages-base.nix:90:14:

           89|
           90|   disabled = drv: throw "${removePythonPrefix (drv.pname or drv.name)} not supported for interpreter ${python.executable}";
             |              ^
           91|

       error: pyside2 not supported for interpreter python3.11
```

### Steps To Reproduce
1. Update flake 
2. Try to rebuild the system (on 23.11 - Tapir)

### Additional context
At present, I am unsure which package is responsible for triggering this issue, and I am also unclear about the purpose of the folder mentioned in the error message. However, the error message suggests that the problem originates from python-packages-base.nix

https://gist.github.com/W-Y-R/7f3783be1b746b929971fd494540c12a

### Notify maintainers

Please let me know if you have any information about the maintainers that are supposed to be tagged on this issue.

### Metadata
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7-zen2, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
seems like a dupe of #263452, would you agree?

**Comment by W-Y-R** [comment]
Yes, I agree that the issues are related. In fact, I've already left a comment on that issue 5 days ago. However, what prompted me to create a separate issue was the fact that my problem didn't stem from a specific package, but rather from the source in its entirety.

**Comment by eclairevoyant** [comment]
Please provide a full log with `--show-trace --option eval-cache false`.

**Comment by W-Y-R** [comment]
https://gist.github.com/W-Y-R/c4e351a97e234e5b1800e5996bfbd1ea

**Comment by eclairevoyant** [comment]
From line 628, it's related to `natron`

**Comment by W-Y-R** [comment]
Removing the package has resolved the issue, allowing me to rebuild successfully once more. Thank you!

**Comment by dejanr** [comment]
I also had the same issue and it was hard to understand what package was affected by this, removing freecad for me solved it.
