### ISSUE TITLE
`blender-hip` Cycles doesn't recognize GPU

### ISSUE THREAD

**Issue by Tiggax** [NixOS/nixpkgs#265371]
### Describe the bug
Installing `blender-hip` from `nixpkgs` installs blender, but it does not recognize the GPU for HIP Render Cycles in the Edit>Preferences>System>Cycles Render Devices

### Steps To Reproduce
1. install `blender-hip`
2. Try to set up Render Cycles
3. It does not recognize the GPU

### Expected behavior
It should recognize the GPU for GPU rendering

### Additional context

Related NixOS(unofficial ) discord [forum](https://discord.com/channels/568306982717751326/1163556657767395338)

running blender in terminal outputs:
```
HIP hipInit: Invalid device
```
in the console, even tho the GPU is able to use HIP.
For the time i solved it by running the stable `blender-hip` from `23.05`.

### Notify maintainers

@cillianderoiste 
@veprbl 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231026.63678e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(tiggax): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by the-furry-hubofeverything** [comment]
Looking briefly now, you said on the Discord that the Blender version wasn't matching with the vesrion on nixpkgs? Can you double check and see which version of Blender you're on?

Do you know when this first happened?

**Comment by Tiggax** [comment]
from `nixpkgs-unstable` i was using v3.6.4 and the `blender-hip` that was working was the latest stable branch (23.05) v3.5.1 . 
Approx 3 weeks  ago I tried running `blender-hip` with cycles, And i couldn't get it to work with the GPU. After that i just used the latest stable branch to run, and it worked. 
If it helps the blender version was: `mq43f24h0znw8llaqzkbavv6r01q3i5n-blender-3.5.1
` that worked.

**Comment by Tiggax** [comment]
After help in the [discord channel](https://discord.com/channels/568306982717751326/1163556657767395338)
It seems that i was running LTS, switching to kernel 6.5 seems to fix the bug.

**Comment by nate-moo** [comment]
I am still having this issue with kernel 6.6.8, and blender-hip package. I have checked rocminfo and it came up with the CPU and GPU. Blender crashes when launched through the terminal so I cant collect any crash logs that way.

**Comment by the-furry-hubofeverything** [comment]
> I am still having this issue with kernel 6.6.8, and blender-hip package. I have checked rocminfo and it came up with the CPU and GPU. Blender crashes when launched through the terminal so I cant collect any crash logs that way.

If you can't confirm that it's the same issue, please open a new one.

**Comment by betalars** [comment]
So I got a bit confused by this issue being closed, as it is still a bug imo.

- I (sorry) made [a new issue](#303586)
- I added a [disclaimer in the wiki](https://wiki.nixos.org/w/index.php?title=AMD_GPU)
