### ISSUE TITLE
hex2nix needs updating

### ISSUE THREAD

**Issue by yurrriq** [NixOS/nixpkgs#26544]
Version 0.0.5 is incompatible with the current hex.pm but https://github.com/erlang-nix/hex2nix/pull/19 fixed the issue.

**Comment by gleber** [comment]
Tag is pushed, please update hex2nix definition to use version 0.0.6

**Comment by yurrriq** [comment]
I've updated my hex2nix locally as follows, but it still crashes.

```diff
diff --git a/pkgs/development/tools/erlang/hex2nix/default.nix b/pkgs/development/tools/erlang/hex2nix/default.nix
index 982bda41cd..1601be5d01 100644
--- a/pkgs/development/tools/erlang/hex2nix/default.nix
+++ b/pkgs/development/tools/erlang/hex2nix/default.nix
@@ -2,13 +2,13 @@
 
 buildRebar3 rec {
   name = "hex2nix";
-    version = "0.0.5";
+    version = "0.0.6";
 
   src = fetchFromGitHub {
     owner = "erlang-nix";
     repo = "hex2nix";
     rev = "${version}";
-      sha256 = "07bk18nib4xms8q1i4sv53drvlyllm47map4c95669lsh0j08sax";
+      sha256 = "17rkzg836v7z2xf0i5m8zqfvr23dbmw1bi3c83km92f9glwa1dbf";
   };
 
   beamDeps = [ ibrowse jsx erlware_commons getopt ];

```

**Comment by yurrriq** [comment]
I'm trying the following now. So far so good.

```
hex2nix -r https://raw.githubusercontent.com/yurrriq/hex-pm-registry-snapshots/master/registry.ets.gz -o pkgs/development/beam-modules
```

Related: https://github.com/erlang-nix/hex-pm-registry-snapshots/pull/3

**Comment by yurrriq** [comment]
The `hex-packages.nix` it generated made `nix-build -A beamPackages` fail, not only because neither `stdenv.lib.licenses.lpgl3` nor `stdenv.lib.licenses.lpgl1` exist. It also had trouble with `riak_pb_2.3.0-1-beta1`.

I'm not sure I understand what's going on here enough to contribute meaningfully at this time, but as it stands, this is quite broken for me. Also, running `hex2nix` also takes way too long.

Perhaps it's time we rewrite it not to generate expressions for and build the entirety of hex.pm, but rather just a curated subset for those packages we need. It would also be great to have a tool that behaves like `cabal2nix` or `mvn2nix` that reads a `rebar.config` and generates a Nix expression from that, include expressions for any Hex package dependencies.

**Comment by gleber** [comment]
I agree. An approach like `cabal2nix` should come first and that's what I plan to work on first.

Building entire hex.pm is hard, since it is not curated in any way.

**Comment by yurrriq** [comment]
Sounds great! I'll be happy to help test.

A `rebar2nix` would also help users add Hex packages ad hoc for an individual project. I've worked around it with PropEr for the current LFE expression, but it'd be nice to have an officially sanctioned/maintained method.

I would imagine there's lots of reusable code from `hex2nix`.

**Comment by yurrriq** [comment]
Also, if you do some groundwork and/or come up with a to-do list, I'd be happy to contribute.

**Comment by pSub** [comment]
Closing. Was updated to 0.0.6 in 52f8bec64b4fdf074fbe9ab8ffacd1cdff6a146d and to an even newer version in 74ca35bd819e644fd43d45daab513e01277a9756.
