### ISSUE TITLE
Package request: Cisco Secure Client

### ISSUE THREAD

**Issue by MordragT** [NixOS/nixpkgs#265443]
**Project description**

Allows to connect  to ciscos vpn. My university switched to this and sadly openconnect seems not to work anymore
I tried to package it myself. But the installer is an shellscript with embeded archive and it uses non nix-compatible commands all over the place.
This was my attempt at the moment but since cisco isn't distributing the installer as it seems, but only via the entities using such vpn, I needed to use local files. It is very work in progress

```nix
{
  lib,
  stdenv,
  # writeScript,
  # makeDesktopItem,
  atk,
  at-spi2-atk,
  at-spi2-core,
  boost,
  cairo,
  fakeroot,
  gdk-pixbuf,
  glib,
  gtk3,
  libsoup,
  libgcc,
  libxml2,
  pango,
  ps,
  systemd,
  webkitgtk,
  zlib,
}:
# let
# desktopItem = makeDesktopItem {
#   desktopName = "Cisco Secure Client";
#   name = "cisco-secure-client";
#   exec = "${installDir}/bin/cisco-secure-client";
# };
# in
stdenv.mkDerivation {
  name = "cisco-secure-client";
  version = "5.0";

  src = /home/tom/Desktop/Mordrag/nixos/pkgs/cisco-secure-client/installer.tar.xz;

  # dontUnpack = true;

  buildInputs = [
    atk
    at-spi2-atk
    at-spi2-core
    boost
    cairo
    fakeroot
    gdk-pixbuf
    glib
    gtk3
    libsoup
    libxml2
    libgcc
    pango
    ps
    systemd
    webkitgtk
    zlib
  ];
  buildPhase = ''
    # not working due to embeded archive
    # substituteInPlace cisco-secure-client.sh \
    #   --replace "AC_INSTPREFIX=/opt/cisco/anyconnect" "AC_INSTPREFIX=$out/opt/cisco/anyconnect" \
    #   --replace "INSTPREFIX=/opt/cisco/secureclient" "INSTPREFIX=$out/opt/cisco/secureclient" \
    #   --replace "ROOTCERTSTORE=/opt/.cisco/certificates/ca" "ROOTCERTSTORE=$out/opt/.cisco/certificates/ca" \
    #   --replace 'SYSTEMD_CONF_DIR="/etc/systemd/system' 'SYSTEMD_CONF_DIR="$out/etc/systemd/system'

    sed -i '/AC_INSTPREFIX=/c AC_INSTPREFIX=$out/opt/cisco/anyconnect' cisco-secure-client.sh
    sed -i '/INSTPREFIX=/c INSTPREFIX=$out/opt/cisco/secureclient' cisco-secure-client.sh
    sed -i '/ROOTCERTSTORE=/c ROOTCERTSTORE=$out/opt/.cisco/certificates/ca' cisco-secure-client.sh
    sed -i '/SYSTEMD_CONF_DIR=/c SYSTEMD_CONF_DIR=$out/etc/systemd/system' cisco-secure-client.sh
    sed -i '/OURPROCS=/c OURPROCS=[]' cisco-secure-client.sh
    sed -i '/INSTALL=/c INSTALL=true' cisco-secure-client.sh
    sed -i '/ln -s/c echo' cisco-secure-client.sh
    sed -i '/ln -f -s/c echo' cisco-secure-client.sh
    sed -i '/\/usr/ $out\/usr"  cisco-secure-client.sh

    head -n300 cisco-secure-client.sh
    fakeroot sh cisco-secure-client.sh
  '';

  installPhase = ''
    ls
    mkdir -p "$out/bin"
    cp -r opt "$out"
    ln -s $out/cisco/secureclient/bin/vpnui $out/bin/cisco-secure-client
    chmod +x $out/bin/cisco-secure-client
  '';

  meta = with lib; {
    license = licenses.unfree;
    maintainers = with maintainers; [mordrag];
    description = "VPN and Endpoint Security Client";
    platforms = platforms.linux;
  };
}

```

**Metadata**

* homepage URL: https://www.cisco.com/site/us/en/products/security/secure-client/index.html
* source URL:
* license: unfree
* platforms:  linux

**Comment by bjornfor** [comment]
Maybe https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments can help?

**Comment by MordragT** [comment]
I tried an FHS for the extracted binaries before but then it failed silently. I didn't really investigate that approach any further, maybe there were files not included that the program was expecting, but can FHS environment even handle programs that might have a deep impact on the system ? I mean it is stated in the docs that it provides no security relevant protection from the host system but isn't it still running inside bwrap or something alike ?

**Comment by bjornfor** [comment]
> but can FHS environment even handle programs that might have a deep impact on the system ? I mean it is stated in the docs that it provides no security relevant protection from the host system but isn't it still running inside bwrap or something alike ?

I don't know this particular software, but lots of things work fine in nixpkgs FHS envs.

**Comment by panicgh** [comment]
@MordragT Is this issue related to https://gitlab.com/openconnect/openconnect/-/issues/665? Do your connect attempts fail with a 404 error?
Try to run openconnect directly (e.g. via nix-shell) and add `--useragent=AnyConnect`. New Cisco AnyConnect servers seem to require a user agent string that starts with `AnyConnect`.

If that indeed solved your problem, then you may also try the 1.2.10 release or later of networkmanager-openconnect, which allows you to pass the user agent from the dialog GUI. This particular release is currently only in nixpkgs-unstable; the one in nixpkgs-23.05 is too old (1.2.8).

Some may also want to track https://gitlab.com/openconnect/openconnect/-/merge_requests/497, which changes the default user agent in openconnect, so that it won't be necessary to pass `--useragent`.

**Comment by MordragT** [comment]
> @MordragT Is this issue related to https://gitlab.com/openconnect/openconnect/-/issues/665? Do your connect attempts fail with a 404 error? Try to run openconnect directly (e.g. via nix-shell) and add `--useragent=AnyConnect`. New Cisco AnyConnect servers seem to require a user agent string that starts with `AnyConnect`.
> 
> If that indeed solved your problem, then you may also try the 1.2.10 release or later of networkmanager-openconnect, which allows you to pass the user agent from the dialog GUI. This particular release is currently only in nixpkgs-unstable; the one in nixpkgs-23.05 is too old (1.2.8).
> 
> Some may also want to track https://gitlab.com/openconnect/openconnect/-/merge_requests/497, which changes the default user agent in openconnect, so that it won't be necessary to pass `--useragent`.

Thank you so much that was exactly why it wasn't working. Should I still keep this open ? For my use case openconnect is now fine.

**Comment by Redhawk18** [comment]
Make sure you follow useragent. That helped me.

Also if you use tailscale you'll have to use split DNS for that domain name. Otherwise You'll have dns hijacking
