### ISSUE TITLE
taskwarrior fails to sync with gnutls update to 3.5.13

### ISSUE THREAD

**Issue by dfbm** [NixOS/nixpkgs#26549]
## Issue description

taskwarrior fails to sync with gnutls update to 3.5.13

### Steps to reproduce

$ /nix/store/34m4dzb9r858xvzblxk5j2zggshyr6v1-taskwarrior-2.5.1/bin/task sync
Syncing with 1.2.3.4:53589

Sync successful.  2 changes uploaded.

$ nix-store -qR /nix/store/34m4dzb9r858xvzblxk5j2zggshyr6v1-taskwarrior-2.5.1/bin/task | sed -e 's_^[^-]*-__' | sort | fgrep gnutls
gnutls-3.5.10

$ /nix/store/4z7nagmkilhnb21k46fcm24nii13bgwd-taskwarrior-2.5.1/bin/task sync
Syncing with 1.2.3.4:53589

Handshake failed.  Error in the certificate.
Sync failed.  Could not connect to the Taskserver.

$ nix-store -qR /nix/store/4z7nagmkilhnb21k46fcm24nii13bgwd-taskwarrior-2.5.1/bin/task | sed -e 's_^[^-]*-__' | sort | fgrep gnutls
gnutls-3.5.13

Only gnutls seems to have been updated if going by the version numbers.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03.1298.5bafc71b61 (Gorilla)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.9
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.1298.5bafc71b61"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = true

**Comment by freakin-c** [comment]
I'm experiencing the same issue on archlinux:
`$ uname --kernel-release --machine --operating-system`
`4.11.7-1-ARCH x86_64 GNU/Linux`

**Task Diagnostics**

`$ task diagnostics`

```
task 2.5.1
   Platform: Linux

Compiler
    Version: 6.3.1 20170306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: May  8 2017 17:10:11
      CMake: 3.8.0
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.11
 Build type: release

Configuration
       File: /home/***** (found), 2419 bytes, mode 100644
       Data: /home/***** (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: vim
     Server: 192.168.0.47:53589
         CA: /home/*****.cert.pem, readable, 3623 bytes
      Trust: strict
Certificate: /home/*****.cert.pem, readable, 3640 bytes
        Key: /home/*****.key.pem, readable, 25125 bytes
    Ciphers: NORMAL
      Creds: *****/*****/************************************

Hooks
     System: Enabled
   Location: /home/*****/hooks
             (-none-)

Tests
      $TERM: rxvt-unicode-256color (134x72)
       Dups: Scanned 324 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 324 tasks for broken references:
             No broken references found
```

**Comment by Infinisil** [comment]
I've had this exact issue, and my problem was that I didn't set `services.taskserver.fqdn` to my domain, so the certificate that got used had this set to the default "localhost", this however should be the same as the `taskd.server` setting (minus port) in the client.

To solve it I set `fqdn` to the correct domain, removed the `/var/lib/taskserver` directory, and restarted the service with `systemctl restart taskserver`.

Here is my config: https://github.com/Infinisil/system/blob/1e4c6f6d74ce47322e6810903afae5fa2254ad0b/config/new-modules/task.nix

**Comment by wamserma** [comment]
@dfbm is this solved?

**Comment by Infinisil** [comment]
Let's close this for now
