### ISSUE TITLE
Unable to run arm-none-eabi-gdb-py executable

### ISSUE THREAD

**Issue by katyo** [NixOS/nixpkgs#26545]
## Issue description

Problem while loading shared library `libpython2.7.so.1.0` (maybe need patchelf-related fix).

### Steps to reproduce

```
$ arm-none-eabi-gdb-py
arm-none-eabi-gdb-py: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

## Technical details

* Package: gcc-arm-embedded
* System: 17.03.1298.5bafc71b61 (Gorilla)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.03.1298.5bafc71b61"
* Sandboxing enabled: build-use-sandbox = false

**Comment by Mic92** [comment]
Which package?

**Comment by katyo** [comment]
I suppose, we need simply add dependency on python here, like this: https://github.com/NixOS/nixpkgs/commit/52243083ca96a33e5b1ebd3fa5d2f12f3991be2e

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by Mic92** [comment]
It looks like it was fixed.
