### ISSUE TITLE
What exactly does environment.profiles do?

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#26542]
Just a question.
environment.profiles accepts a list of strings.  The documentation says its a list of profiles used to setup the global environment.  Can someone provide an example of what this list might look like?  Should it be a list of profile configs files such as a .bashrc?  Any help is much appreciated. Thanks.

**Comment by vcunat** [comment]
It's about shell environment variables, apparently.  https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/shells-environment.nix#L17  The documentation of `environment.profileRelativeEnvVars` does explain that a little.

**Comment by vcunat** [comment]
The default value helps as well, I guess: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/environment.nix#L26

**Comment by ob7** [comment]
Seems to do with the different setups for each nixos-rebuild.

**Comment by xav-ie** [comment]
The manual/docs have some info about what a profile is:
https://github.com/NixOS/nix/blob/8d4b6766e297314f69ee96b6c9d74c6c2637f84b/doc/manual/src/package-management/profiles.md

If I had to put it into my own words, a profile is an environment which includes $PATH and env variables all in one unit that you can choose and switch between. A set of packages. And on `nix` version 2.17, it has some more info about what profiles are in `nix profile --help`:

> nix profile allows you to create and manage Nix profiles. A Nix profile is a set of packages that can be installed > and upgraded independently from each other. Nix profiles are versioned, allowing them to be rolled back easily.
 

So `environment.profiles` is the sets of profiles you want in your global environment, together. If you take a step back and think about it, it is mentioned in https://github.com/NixOS/nixpkgs/blob/592047fc9e4f7b74a4dc85d1b9f5243dfe4899e3/nixos/modules/config/shells-environment.nix#L1-L2 that these variables are used for setting up your shells (your terminal and its environment). 

Checking my `~/.zshrc`, it confirms this:
```sh
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done
```

This is generated by `nix`. So, practically, `environment.profiles` just sets the `NIX_PROFILES` enviroment variable. That variable is later used in shell rc file generation to set up global environment. :)
