### ISSUE TITLE
Package request: salut

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#265554]
**Project description**

A sleek notification daemon for Wayland compositors.

**Metadata**

* homepage URL: https://gitlab.com/snakedye/salut/-/wikis/Home
* source URL: https://gitlab.com/snakedye/salut
* license: mpl
* platforms: unix, linux, darwin, ...

**Comment by FliegendeWurst** [comment]
PR: #265564
