### ISSUE TITLE
Kernel update to 6.6.0 breaks CIFS/SMB mounting for DNS-based share addresses

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#265521]
### Describe the bug
`mount.cifs` starts failing with `ENOKEY` if I use a DNS domain for the server address.

### Steps To Reproduce

Command I used is: `mount -t cifs -o vers=3.1.1,cred=/home/u/.secret.txt,uid=1000,gid=100 //smb.server.example.com/scans /home/u/mnt` (mount.cifs version: 7.0 in all cases)

strace from `6.5.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Oct 25 10:16:30 UTC 2023 x86_64 GNU/Linux`:
```
[pid  3232] mount("//smb.server.example.com/scans", ".", "cifs", 0, "ip=192.168.5.43,unc=\\\\smb.server.example.com\\scans,vers=3.1.1,uid=1000,gid=100,user=u,pass=mypassword") = 0
```

strace from `6.6.0 #1-NixOS SMP PREEMPT_DYNAMIC Mon Oct 30 02:31:08 UTC 2023 x86_64 GNU/Linux`:
```
[pid  4525] mount("//smb.server.example.com/scans", ".", "cifs", 0, "ip=192.168.5.43,unc=\\\\smb.server.example.com\\scans,vers=3.1.1,uid=1000,gid=100,user=u,pass=mypassword") = -1 ENOKEY (Required key not available)
```

Note that when using the IP it still works on 6.6.0:
```
[pid  4537] mount("//192.168.5.43/scans", ".", "cifs", 0, "ip=192.168.5.43,unc=\\\\192.168.5.43\\scans,vers=3.1.1,uid=1000,gid=100,user=u,pass=mypassword") = 0
```

### Expected behavior
The share should be mounted successfully.

### Additional context
* I didn't see anything obvious in the kernel's git log (just skimming the messages) in `fs/smb/client/` in the last 3 months.
* No changes to `configuration.nix` between the offending updates.
* Note that the DNS lookup itself succeeds (i.e. the `ip=` option is populated correctly)
  * Nothing suspicious in `resolvectl monitor` or `tcpdump`. 
* No changes on the server side (no other system is affected either).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.17.1`
- channels(root): `""`
- channels(u): `""`
- nixpkgs: `/nix/store/a56i1y5js340dn1w9r767a8jp34k31n4-source`
```

The update in question (via `nix profile diff-closures --profile /nix/var/nix/profiles/system`):
```
Version 438 -> 439:
android-tools: 34.0.1 → 34.0.4, +1713.0 KiB
android-udev-rules: 20230614 → 20231030
docker-compose: 2.21.0 → 2.23.0, +78.2 KiB
enchant: 2.6.1 → 2.6.2
initrd-linux: 6.5.9 → 6.6, +95.8 KiB
jasper: 2.0.32 → 4.0.0, -129.7 KiB
kernel: +67.1 KiB
ldns: ∅ → 1.8.3, +593.0 KiB
libcpuid: 0.6.3 → 0.6.4, +24.5 KiB
linux: 6.5.9, 6.5.9-modules → 6.6, 6.6-modules, +1531.1 KiB
linux-firmware: 20230919 → 20231030, +7527.5 KiB
mdadm.conf: ε → ∅
nixos-system-myhostname: 23.11.20231029.0cbe9f6 → 23.11.20231102.fa804ed
perf-linux: 6.5.9 → 6.6, -644.2 KiB
source: +290.7 KiB
strace: 6.5 → 6.6
unifont: 15.1.02 → 15.1.03
v4l2loopback-unstable: 2023-02-19-6.5.9 → 2023-02-19-6.6
```

**Comment by hughobrien** [comment]
Also experiencing this, can confirm that swapping in an IP instead of the DNS record works as a workaround. 

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hughobrien** [comment]
Happy to help if you can guide me a little. 



```
sh-5.2# mount.cifs //rpi.lan/m2 ./mnt -o uid=hugh,guest,vers=3.1.1
mount error(126): Required key not available
```

```
doas bpftrace -e 'tracepoint:syscalls:sys_enter_openat /comm!="zsh" && comm!="git" && comm !="tokio-runtime-w"/ { printf("%s %s\n", comm, str(args.filename)); }'

mount.cifs /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/glibc-hwcaps/x86-64-v3/libc.so.6
mount.cifs /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/glibc-hwcaps/x86-64-v2/libc.so.6
mount.cifs /nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6
nsncd /etc/passwd
nsncd /run/systemd/machines/rpi.lan
nsncd /etc/hosts
systemd-journal /run/log/journal/ac095d27196d465898a6d153de36101b/system.journal
systemd-journal /run/log/journal/ac095d27196d465898a6d153de36101b/system.journal

```

```
doas find /run/systemd/machines                               
/run/systemd/machines
```

```
grep rpi.lan /etc/hosts
10:192.168.1.201 rpi.lan
```

**Comment by hughobrien** [comment]
```shell
doas bpftrace -v -e 'kretprobe:call_usermodehelper_setup { $i = (struct subprocess_info*) retval; print(str($i->path)); }'
INFO: node count: 13
Attaching 1 probe...

Program ID: 883

The verifier log: 
processed 60 insns (limit 1000000) max_states_per_insn 0 total_states 2 peak_states 2 mark_read 1

Attaching kretprobe:call_usermodehelper_setup
/run/current-system/sw/bin/request-key
```

```shell
/tmp/tmp.I3JXWXZFL3
❯ doas mount.cifs //rpi.lan/m2 ./mnt -o uid=hugh,guest,vers=3.1.1
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

/tmp/tmp.I3JXWXZFL3
❯ doas mount.cifs //rpi.lan/m2 ./mnt -o uid=hugh,guest,vers=3.1.1
mount error(126): Required key not available
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

I think you're right there is some caching going on as the same mount invocation is giving different outputs when called in short succession.

```shell
shell ❯ doas bpftrace -v -e 'kprobe:kernel_execve { print(str(arg0)); join(arg1) }'
INFO: node count: 10
Attaching 1 probe...

Program ID: 889

The verifier log: 
processed 243 insns (limit 1000000) max_states_per_insn 0 total_states 20 peak_states 20 mark_read 19

Attaching kprobe:kernel_execve
/run/current-system/sw/bin/request-key
/run/current-system/sw/bin/request-key create 292630943 0 0 665432494 0 290382712
```

**Comment by arbv** [comment]
I have encountered the same bug, are there any other ways to resolve it apart from switching to mounting via IP addresses?

**Comment by hughobrien** [comment]
6.6.1 is in `unstable` now so I just rolled forward and picked up the fix that way.

**Comment by arbv** [comment]
@hughobrien Thank you for confirming that it is fixed! Then I think I will wait for 22.11 to arrive (using the LTS kernel in the meanwhile). It should already have the latest `latest` kernel with the fix by then.

**Comment by freshprince** [comment]
There is a [patch floating around](https://lore.kernel.org/all/20231109150148.6273-1-pc@manguebit.com/) but it doesn't seem to be in the [changelog for 6.6.1](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.1) or [6.6.2](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.2).

**Comment by marienz** [comment]
Looks like that [patch is queued for 6.6.3](https://lore.kernel.org/stable/20231124172040.970792168@linuxfoundation.org/) (I didn't confirm the patch works, for now I worked around it with `create  dns_resolver *  * /run/current-system/sw/bin/key.dns_resolver %k` in `/etc/request-key.conf`).

**Comment by misuzu** [comment]
6.6.3 fixed the issue for me
