### ISSUE TITLE
wrapped gcc -V error message is not correct     

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#26556]
## Issue description
```
nix-shell -p gcc48 --run "gcc -V"
gcc: error: unrecognized command line option ‘-V’
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
gcc: fatal error: no input files
compilation terminated.
```
While it should be (I think):
```
nix-shell -p gcc48 --run "gcc -V"
gcc: error: unrecognized command line option ‘-V’
gcc: fatal error: no input files
compilation terminated.
```

### Steps to reproduce
Just run `gcc -V` and check if the output contains 
`gcc: error: unrecognized command line option ‘-fstack-protector-strong’`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
unstable and 16.09
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by nlewo** [comment]
This option is available since gcc 4.9. It seems all version below 4.9 should not use it.

**Comment by nlewo** [comment]
I finally switch to another gcc version.

**Comment by globin** [comment]
For refence in case you use gcc48, workaround this by exporting `hardeningDisable=stackprotector`

**Comment by nlewo** [comment]
Thanks. 
If I remember well, the problem was that `autoconf` tests the version of `gcc` by executing `gcc -V` adn its output was not the expected one. Ok... I should have mentionned this in the issue:/
