### ISSUE TITLE
Wine can't load OpenGL if its called from /nix/store

### ISSUE THREAD

**Issue by mrtnvgr** [NixOS/nixpkgs#265560]
### Describe the bug

Wine fails to load OpenGL when ran from /nix/store path

### Steps To Reproduce

Fails
`/nix/store/bha9n5s9jgsf624j8c5wb9cgmplb715j-wine-wow-8.5-staging/bin/wine ./Celeste.exe`: [logs](https://pastebin.com/raw/XJLj9ewS)

### Expected behavior

Runs successfully
`wine ./Celeste.exe`: [logs](https://pastebin.com/raw/WZchk5rf)

### Notify maintainers

@avnik @7c6f434c @bendlas @jmc-figueira @reckenrode 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
What's the result of `whereis wine`?

**Comment by mrtnvgr** [comment]
> What's the result of `whereis wine`?

```console
$ whereis wine
wine: /nix/store/mfzx380brvpi0zmkd8iyc1q3bjyn2pal-user-environment/bin/wine
```

**Comment by mrtnvgr** [comment]
I noticed that I'm using a stable channel to build this package. How can I use nixpkgs from my flake inputs?

Looks like `{ nix.registry.nixpkgs.flake = inputs.nixpkgs; }` doesn't work for me.

**Comment by mrtnvgr** [comment]
```nix
{
  nix.registry.nixpkgs.flake = inputs.nixpkgs;
  environment.etc."nix/inputs/nixpkgs".source = inputs.nixpkgs;
  nix.nixPath = [ "/etc/nix/inputs" ];
}
```

**Comment by mrtnvgr** [comment]
Thank you @eclairevoyant
