### ISSUE TITLE
todoist-electron from unstable points to the staging environment

### ISSUE THREAD

**Issue by peret** [NixOS/nixpkgs#265538]
### Describe the bug
I tried installing the todoist-electron app (through home-manager). When trying to login, the app redirects to a browser window, but the URL used is for the staging environment staging.todoist.com, not app.todoist.com. Since regular accounts don't work for the staging environment, logging into the app is impossible. 

### Steps To Reproduce
1. Install todoist-electron from nixpkgs
2. Open Todoist app
3. Click on "Login via your browser"
4. Notice, that the URL you are being sent to uses the "staging" subdomain
5. Try to login (I use email and password)
6. Login fails because the account is unknown

### Expected behavior
Login through the app should work and redirect you to app.todoist.com

### Additional context
This seems really weird to me. The only explanation that comes to my mind is that 8.6.0 was never an official release of the app and just happens to be downloadable through their download server? The latest version downloadable on todoist.com/downloads is 8.9.4, btw. Not sure if upgrading again would fix it? Is there a way for me to force the AppImage version using an override/overlay? I'd like to help, but I'm still fairly new to NixOS and wasn't successful so far.

### Notify maintainers
@i077
@kylesferrazza 
@pokon548 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.4112.5a237aecb572`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(peter): `"home-manager-23.05.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sersorrel** [comment]
should be sorted by #264333, fwiw

**Comment by pokon548** [comment]
Already fixed on https://github.com/NixOS/nixpkgs/pull/264333. Feel free to build and test it for yourself.

**Comment by peret** [comment]
Ah yes, thanks for pointing out the PR, I can confirm that it fixes the issue :+1: Thanks!
