### ISSUE TITLE
Build failure: neovim

### ISSUE THREAD

**Issue by LamprosPitsillos** [NixOS/nixpkgs#265510]
### Steps To Reproduce

1. build neovim stable with home manager

### Build log

```
error: builder for '/nix/store/03x0cw2xpkc5gy32hfcz6mg4kbms39n3-neovim-0.9.4.drv' failed with exit code 1;
       last 1 log lines:
       > /nix/store/y7kq9vcgrgs5rbngzcfd2y6hawcpzfgw-make-shell-wrapper-hook/nix-support/setup-hook: line 115: /nix/store/8nk23d9y2hzpcpmv3lmvb53f59wxb1gr-neovim-0.9.4/bin/nvim-python3: Permission denied
       For full logs, run 'nix log /nix/store/03x0cw2xpkc5gy32hfcz6mg4kbms39n3-neovim-0.9.4.drv'.
error: 1 dependencies of derivation '/nix/store/2l8viixh935n8iaq2giicq8rzcfbcs0k-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nnr2zbwjx8zbwjs28krf9davwxsxxqbx-home-manager-generation.drv' failed to build
```

### Additional context

https://github.com/LamprosPitsillos/nixos-config/blob/main/home-manager/programs/nvim/nvim.nix
The whole config
https://github.com/LamprosPitsillos/nixos-config
### Notify maintainers
@manveru @rvolosatovs 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231102.fa804ed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
>  - channels(root): `"nixos-23.05"`

Are you sure it's the channel you had problems with ? I just ran a `nix build .#neovim` on master with no issue

**Comment by LamprosPitsillos** [comment]
> Are you sure it's the channel you had problems with ? I just ran a `nix build .#neovim` on master with no issue

Strange ... i use unstable channel. Why is `nix-info -m` showing "nixos-23.05" ...
https://github.com/LamprosPitsillos/nixos-config/blob/d45b623a4612765f7febf348e8fcab9f6ee8dfc5/flake.nix#L4

**Comment by Gerg-L** [comment]
> > Are you sure it's the channel you had problems with ? I just ran a `nix build .#neovim` on master with no issue
> 
> Strange ... i use unstable channel. Why is `nix-info -m` showing "nixos-23.05" ... https://github.com/LamprosPitsillos/nixos-config/blob/d45b623a4612765f7febf348e8fcab9f6ee8dfc5/flake.nix#L4

no you use an unstable flake input.
your root users `nixos` channel is a bitrotten 23.05 channel
you probably want to pin your systems channels to your flake inputs: <https://ayats.org/blog/channels-to-flakes/>

**Comment by teto** [comment]
`nix build 'github:nixos/nixpkgs/nixos-unstable#neovim'` builds fine as well. Aren't you using some kind of overlay to get neovim nightly ? in which case this is not the appropriate repo

**Comment by LamprosPitsillos** [comment]
> `nix build 'github:nixos/nixpkgs/nixos-unstable#neovim'` builds fine as well. Aren't you using some kind of overlay to get neovim nightly ? in which case this is not the appropriate repo

I used to ,but it's commended out now

**Comment by Gerg-L** [comment]
fixed over discord, issue was `programs.neovim.package = pkgs.neovim;` instead of `programs.neovim.package = pkgs.neovim-unwrapped;`

**Comment by teto** [comment]
yep it's a legitimate source of confusion sadly, I dont have a good solution sadly, I wish the neovim/neovim-unwrapped had been neovim-wrapped/neovim but that is too late now and the change would break the nixpkgs pattern.
