### ISSUE TITLE
Build failure: wrangler

### ISSUE THREAD

**Issue by iivvaannxx** [NixOS/nixpkgs#265653]
### Steps To Reproduce

1. Try to install any of the `wrangler` packages. Either be `wrangler` or `nodePackages.wrangler`. In my case I tried `nix shell nixpkgs#wrangler`
2. The build fails while trying to install the package "@cloudflare/workerd-linux-64".

### Build log
I am attaching the last 10 log lines of the build error, but I also created a [gist](https://gist.github.com/iivvaannxx/a26c17047dc35c40de373832d89e8f43) with the full logs of the derivation.
```
error: builder for '/nix/store/lxk2q4j1wkry2sr4p1ap98x2k9bdwlbz-wrangler-3.15.0.drv' failed with exit code 1;
       last 10 log lines:
       > npm ERR!               ^
       > npm ERR!
       > npm ERR! Error: Failed to install package "@cloudflare/workerd-linux-64"
       > npm ERR!     at checkAndPreparePackage (/nix/store/6prn9amlmw1455jyy6k9z031ixn33xcp-wrangler-3.15.0/lib/node_modules/wrangler/node_modules/workerd/install.js:242:15)
       > npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       > npm ERR!
       > npm ERR! Node.js v18.18.2
       > 
       > npm ERR! A complete log of this run can be found in: /build/.npm/_logs/2023-11-05T12_36_49_991Z-debug-0.log
```

### Additional context

If you try to install it globally using any package manager like `npm` or `pnpm` it works. But when I went to try it on a simple fresh worker template it fails to start on `wrangler dev` with the following error:

```
Error: spawn /home/iivvaannxx/.../node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/iivvaannxx/.../node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  path: '/home/iivvaannxx/.../node_modules/@cloudflare/workerd-linux-64/bin/workerd',
  spawnargs: [
    'serve',
    '--binary',
    '--experimental',
    '--socket-addr=entry=127.0.0.1:3001',
    '--external-addr=loopback=localhost:36063',
    '--control-fd=3',
    '-',
    '--inspector-addr=localhost:43659'
  ]
}
```

### Notify maintainers

I am not sure if `nodePackages` have maintainers at all (at least they aren't listed in [the search results](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=wrangler)), but I found @Br1ght0ne to be a maintainer of the older `wrangler_1` CLI so not sure if he will be able to help.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.1.59, NixOS, 23.05 (Stoat), 23.05.20231021.5550a85`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.13.6`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zestsystem** [comment]
Ran into the same issue as well.

**Comment by lilyinstarlight** [comment]
cc'ing @cyntheticfox who originally added this derivation

It might just be time to migrate this package to `buildNpmPackage`-based tooling instead of leaving it in the `nodePackages` set that we would very much like to deprecate

**Comment by Kranzes** [comment]
I can do that, this package is very crucial.

**Comment by cyntheticfox** [comment]
I wish I had my laptop on me. I'm all for it, but might not get to it until tonight, so if someone else can do so quickly (dont forget some of what was in `overrides.nix` and test it), go ahead

**Comment by Kranzes** [comment]
It's a bit tricky because they don't have a package-lock.json, they use a [pnpm-lock.yaml](https://github.com/cloudflare/workers-sdk/blob/main/pnpm-lock.yaml)

**Comment by Kranzes** [comment]
Started working on it here -> https://github.com/NixOS/nixpkgs/pull/266517/

**Comment by TonyGiorgio** [comment]
I'm also facing this. Any work arounds that exist for it?

**Comment by Kranzes** [comment]
Not really...
I just pointed it to an old version like so

`(builtins.getFlake "github:NixOS/nixpkgs/8dfad603247387df1df4826b8bea58efc5d012d8").legacyPackages.${system}.nodePackages.wrangler`

**Comment by TonyGiorgio** [comment]
Pointed to the old version as well and that works for me, thank you!

**Comment by cyntheticfox** [comment]
Guess we really need #231513 to get this fixed...
