### ISSUE TITLE
When linux kernel 4.4 end of support scheduled in NixOS?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#26564]
My question is triggered by removal of linux kernel ```4.1``` and multiple hardware issues with ```4.9``` and later kernels, so I am using ```4.4```.

---

When do you plan to remove kernel ```4.4``` ?

Upstream (kernel.org) plans to stop its support in [Feb, 2018](https://www.kernel.org/category/releases.html).
If ```NixOS``` follows there will be no kernel ```4.4``` in the next ```18.03``` version (or even earlier, ```4.1``` was removed four months before upstream's EOL which is Sep, 2017)

On the other hand, Canonical plans to support kernel ```4.4``` until [Apr, 2021](https://wiki.ubuntu.com/Kernel/Support#A16.04.x_Ubuntu_Kernel_Support)

---

**Comment by vcunat** [comment]
I see no reason to force its removal as long as it's maintained, especially if some NixOS users still want it.

**Comment by 7c6f434c** [comment]
Does Canonical version include any unexpected patches? If we plan to use them as upstream, maybe we should provide `linux_4_4_ubuntu` now to learn about the pitfalls?

I don't know if hardware support regressions in 4.9 are forever — Linux as a project is not the most regression-happy one, so maybe a detailed enough bug report could lead to a boot option for the old behaviour for most of the problems (or maybe even a proper fix).

**Comment by volth** [comment]
Yes, it may have sense to add ```linux_4_4_ubuntu``` before Feb, 2018 to have time to test it. May be even now.

I am pessimistic about the fixing:
1. it is not easy to locate the bugs. for example, one of the bugs is a laptop sometimes hangs on changing from X11 to console (on pressing ```Ctrl-Alt-F1```). No stacktrace, no hints. I realize that the only way is to bisect all kernel history between 4.4 and 4.9, compiling each kernel. It would take many days.
2. Even if I locate the bugs and even I would be able to fix them, it would take months to push them upstream. @dezgeg's 9p bugfixes is still not accepted.

**Comment by domenkozar** [comment]
We will remove it at Feb 2018. We are following kernel.org as we are using those kernels.

**Comment by Mic92** [comment]
@volth on which mailing-list was this bug posted?

**Comment by volth** [comment]
@domenkozar good to know.
But do not you think that 2 years from introduction to deprecation (kernel.org's LTS cycle) is way too small for production use?
More than half of my servers have uptime >2years, some >5years.

**Comment by Mic92** [comment]
@volth If you do not apply [kernel security](https://dirtycow.ninja/) updates anyway (in 2-5 years), you do not have to care about kernel deprecations, I guess.

**Comment by volth** [comment]
The concern here is not (only) about security.
How could I update nixpkgs (without reboot) if it at one moment the booted kernel disappear from nixpkgs? Some packages use kernel modules, other compiled using kernel headers, ...

**Comment by Mic92** [comment]
You can always import your kernel from older nixpkgs revisions.

**Comment by volth** [comment]
Also, nested KVM virtualization (needed for Hydra) on digitalocean works only with 4.4 kernel.

**Comment by dezgeg** [comment]
@volth do you have a recollection of which kernel versions had working and which versions had broken nested KVM, and how did it break? Some time ago (+1 year) ago I (and other users) at $work tried nested KVM under various hypervisors (big iron VMWare and VirtualBox) and distro host kernels (Debian, Ubuntu)   with various levels of failure (some had 100% reproducible boot failures with random stack traces, some had just random segfaults in userspace & random bluescreens in Windows). If you have some findings on mainline/stable kernels it might be useful to report/complain about upstream.

**Comment by volth** [comment]
```kvm_intel``` module fails not load.
I suspect the reason could be in kernel-4.4 used on the host machine.

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/issues/27930

**Comment by globin** [comment]
Since EOL is in February which is in the next release support period, it will be removed in 17.09

**Comment by volth** [comment]
February is also EOL for 17.09, in March there will be 18.03, right?
Also removal of 4.4 depends on https://github.com/NixOS/nixpkgs/issues/27930 fix, or it would destroy some Hydra builds.

**Comment by globin** [comment]
We are supporting 17.09 until April 30th 2018

**Comment by globin** [comment]
3.10 and 4.4 have now been removed from master.
