### ISSUE TITLE
GRUB 2: Gnome_Dark.png missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#26565]
## Issue description

(my branch was rebased to upstream just now to commit https://github.com/NixOS/nixpkgs/commit/cc0ce6b7a61976c9ea517d12daf62505365c0b8a)

```
[root@nixos:~/nixpkgs]# nixos-rebuild switch -I ~
building Nix...
building the system configuration...
updating GRUB 2 menu...
cannot copy /nix/store/sj1psbij342r12xv61fx6jcxwapkkj3g-gnome-dark-2015-02-27/share/artwork/gnome/Gnome_Dark.png to /boot
warning: error(s) occurred while switching to the new configuration

[root@nixos:~/nixpkgs]# ls /nix/store/sj1psbij342r12xv61fx6jcxwapkkj3g-gnome-dark-2015-02-27/share/artwork/gnome/Gnome_Dark.png
ls: cannot access '/nix/store/sj1psbij342r12xv61fx6jcxwapkkj3g-gnome-dark-2015-02-27/share/artwork/gnome/Gnome_Dark.png': No such file or directory
```

@romildo maybe related to https://github.com/NixOS/nixpkgs/pull/26460?

### Steps to reproduce

basic NixOS VM should be sufficient

## Technical details

* System: NixOS 17.09.git.250ec90 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.03.1123.4a7a03913d"
* Sandboxing enabled: build-use-sandbox = false

**Comment by MP2E** [comment]
This happens for me as well, definitely related to #26460

**Comment by davidak** [comment]
It's fixed now. Thanks @volth!

**Comment by romildo** [comment]
@volth, thanks for fixing this.

**Comment by MP2E** [comment]
Thanks for the fixes! Works fine now
