### ISSUE TITLE
Teach `fetchPypi` to fetch zips

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#26577]
Sometimes people upload zips, not just tarballs, e.g. https://pypi.python.org/pypi/algopy

It would be especially nice if it would try both, but I'd settle for being able to specify.

**Comment by FRidh** [comment]
src = fetchPypi {
  ...
  extension = "zip";
};

**Comment by michaelpj** [comment]
Huh, sorry, I looked at the source and I managed not to realise that would work!

**Comment by FRidh** [comment]
Yes, it might not have been that obvious because its no explicit parameter.

**Comment by michaelpj** [comment]
Would it be annoying to make it an explicit parameters? Or perhaps document the parameters?

**Comment by FRidh** [comment]
The parameter cannot be made explicit because its not valid in case of wheels. The function `fetchPypi` should be documented in the manual and briefly in the code as well.
