### ISSUE TITLE
Update request: osu-lazer 2023.815.0 → 2023.1026.0

### ISSUE THREAD

**Issue by C0D3-M4513R** [NixOS/nixpkgs#265814]
- Package name: osu-lazer
- Latest released version: 2023.815.0

- Current version on the unstable channel: 2023.815.0
- Current version on the stable/release channel: 2023.511.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@oxalica 
@thiagokokada 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/pull/265909
