### ISSUE TITLE
 Kernel panic/switch_root issue

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#26585]
## Issue description

Kernel panic - switch_root is not working.
Happened after doing a `sudo nixos-rebuild switch --upgrade`.

### Steps to reproduce

Yes.

## Technical details
https://gist.github.com/Nobabs27/266265c35aaf21a89fb0bc47dd8d0961
https://gist.github.com/Nobabs27/0abfbe14dd32aa0e2263e1c2b2c4c37a
https://gist.github.com/Nobabs27/3a16484236f0f5314ec55891303ddd93
https://gist.github.com/Nobabs27/eb1ab4e756a5dc4cba6ef908318d23a5
https://gist.github.com/Nobabs27/18018f31cc40aef6b86193f99ffa7f86

**Comment by ikervagyok** [comment]
I suppose you don't have this issue anymore, but do you still know, what

- kernel version
- filesystem
- raid/lvm/encryption

you used? Had a similar issue now, after giving the system time to start the devices (see my comment on https://github.com/NixOS/nixpkgs/issues/32588) and got it fixed, by replacing `boot.initrd.availableKernelModules` with `boot.initrd.kernelModules`

**Comment by Nobabs27** [comment]
According to https://gist.github.com/Nobabs27/18018f31cc40aef6b86193f99ffa7f86 it would seem Kernel 4.9.31.
Filesystem would be ext4.
No raid/lvm/encryption.

**Comment by Ekleog** [comment]
This looks weird: nothing looks wrong in the logs until this `switch_root` is called and fails.

I guess you no longer have `/nix/store/slgp4sc5lmqnxyjz4p2n9f5wxbc4ajzs-nixos-system-nixos-virtualbox-17.03.1316.412b0a17aa/init` or the included `hardware-configuration.nix`? If you had `hardware-configuration.nix`, it'd be possible to try to reproduce this issue by checking out nixpkgs at 412b0a17aa, but… :/

**Comment by lasers** [comment]
Please revisit this again. No steps to reproduce. No technical details. Close.

**Comment by Ekleog** [comment]
Right, this was a long time ago, so let's close as it's unlikely to still be a problem. If anyone happens to have a similar issue, feel free to reopen a bug / ask for this one to be reopened if it's exactly the same issue! :)
