### ISSUE TITLE
TeXLive commands make4ht, tex4ebook fail to process images

### ISSUE THREAD

**Issue by fedeinthemix** [NixOS/nixpkgs#265880]
### Describe the bug
I'm trying to produce html and epub files from a LaTeX document with the *ht* tools and it looks like they don't work properly.

Given the following simple input, with a PDF file pic.pdf, 
```latex
\documentclass[11pt,a4paper,twoside]{article}
\usepackage{graphicx}
\begin{document}

\section{Introduction}

Look at this Figure~\ref{fig:pic}

\begin{figure}
  \centering
  \includegraphics{pic}
  \caption{Pic.}
  \label{fig:pic}
\end{figure}
\end{document}
```
the commands `make4ht`and `tex4ebook` give the following errors 

```bash
$ make4ht test.tex "mathjax"
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: test.tex
sh: line 1: rungs: command not found
[STATUS]  make4ht: Conversion finished
```

```bash
$ tex4ebook test.tex mathml
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: test.tex
sh: line 1: rungs: command not found
[ERROR]   mkutils: File pic-.png doesn't exist
cp: cannot stat 'pic-.png': No such file or directory
sh: line 1: tidy: command not found
[WARNING] exec_epub: tidy command seems missing, you should install it in order
  to make valid epub file
[STATUS]  tex4ebook: Conversion finished
```
In both cases the output is produced, but the image is missing.

### Notify maintainers

@veprbl @vcunat 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.05 (Stoat), 23.05.4662.34bdaaf1f0b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(beffa): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by chewblacka** [comment]
How did you install LaTeX / which version of LaTeX do you have installed?

It looks like you have 2 commands missing: `rungs` and `tidy`. I ran the same commands on your test file and only got the second error. Easily fixed by installing the [html-tidy](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=tidy) from the repos.

`rungs` seems to be part of all the current unstable texlive packages, but none of the 23.05 texlive packages.

**Comment by fedeinthemix** [comment]
Indeed I'm on the 20.05 channel. I installed with the following

```nix
...
environment.systemPackages = with pkgs; [
...
    ((texlive.combine {
      inherit (texlive)  # space separated list of pkgs
        scheme-medium
        a4wide
        comment
        enumitem
        fontaxes  # required by svmono
        footmisc  # required by svmono
        framed    # required by svmono
        multirow
        newtx     # required by svmono
        ntheorem  # required by svmono
        pagecolor
        pdfcolmk
        pgfplots
        standalone
        thmtools
        type1cm   # required by svmono
        xstring;  # required by svmono
      pkgFilter = pkg: lib.elem pkg.tlType [ "run" "bin" "doc" ];
    }).override (args: { ignoreCollisions = true; }))
...
];
...
```

**Comment by chewblacka** [comment]
> Indeed I'm on the 20.05 channel. I installed with the following

Ok thanks. Just to confirm, are you on `20.05` or did you mean to say `23.05` ?

**Comment by fedeinthemix** [comment]
Yes, sorry.

**Comment by veprbl** [comment]
cc @xworld21, this must have been fixed by the recent changes to scripts packaging? Is this is a wontfix for 23.05?

**Comment by xworld21** [comment]
> cc @xworld21, this must have been fixed by the recent changes to scripts packaging? Is this is a wontfix for 23.05?

The `rungs` script should work now on unstable, I see listed among the binaries on https://search.nixos.org/packages?channel=unstable&show=texlive.combined.scheme-medium

However `tidy` is most likely an external dependency that must be added to the path via `postFixup`.

**Comment by xworld21** [comment]
PS: I'll try slip an extra `rungs` link in the 23.05 `texlive.combine`, since 23.11 is still some time away. (It should be enough to add `rungs` to the loop that reads from `scripts.lst` – not in `scripts.lst` directly as it would cause a useless rebuild – so if somebody has a moment to do it before me, go ahead!)

**Comment by fedeinthemix** [comment]
Thanks for the rapid fix!
