### ISSUE TITLE
How to use fontconfig in a derivation?

### ISSUE THREAD

**Issue by brittAnderson** [NixOS/nixpkgs#26586]
## Issue description
To use some functions of the psychopy python library it is also necessary to use pyglet and to have access to the fonts. This fails for me. Is there a way to fix by exporting a fontconfig file?

### Steps to reproduce
Minimal: 
```
nix-shell --pure -p python -p pkgs.pythonPackages.pyglet 
python
import pyglet
pyglet.lib.load_library('fontconfig')
```

Actual use:
I run nix-shell with the following default.nix:
```
with import <nixpkgs> {};

(let
  psychopy = pkgs.pythonPackages.buildPythonPackage rec {
       name = "psychopy-${version}";
       version = "1.85.1";

       src = pkgs.fetchurl{
         url = "https://github.com/psychopy/psychopy/archive/1.85.1.tar.gz";
         sha256 = "d6a487bd8617ec68c7e56b6a7a855f3fd19e12282463025ae209fbc68fcb34b5";
       };

       buildInputs = [pkgs.pythonPackages.configobj];
       propagatedBuildInputs = [pkgs.pythonPackages.configobj];
       
       meta = {
         homepage = "https://github.com/psychopy/psychopy/releases";
       };
  };		

 in  pkgs.python.buildEnv.override rec {
extraLibs = with pkgs.pythonPackages; [fontconfig python configobj numpy scipy matplotlib pandas pyopengl pyglet pillow psychopy];
}
).env
```

then 
```
cd ./result/lib/python2.7/site-packages/psychopy/demos//coder/stimuli/
python dots.py
```

N.B. The library seems to work as `python face_jpg.py` works fine.

## Technical details

* System: nixos unstable
* nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre107928.65477dcd34"

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/issues/25828#issuecomment-302003174 for an example.

**Comment by brittAnderson** [comment]
Thank you for the pointer, but I am afraid it is not enough for me. Although I am trying to set up an environment for Psychopy, the code that I am trying to run needs Pyglet and it is pyglet that is not able to find the fontconfig. It also strikes me as puzzling that python libraries that need access to the location of fonts, such as matplotlib and pyglet, don't get those environment variables built for them. 

In my case, the demos for psychopy that I am trying to run might need both matplotlib and pyglet. Is each of those going to require its own unique FONT_CONFIG line?

So, I appreciate your help, and I do think the inability to import pyglet and have it find the fonts it needs without setting special path variables is an issue, but I will close it as I am not going to pursue this further at this time. The lure or reproducibility is offset by the time required to figure out how to achieve it.

I did see your partial draft of a python tutorial, but it doesn't mention anything about run commands and the like which feature in your matplotlib comment. You might consider enclosing instructions for how to do something like this in your tutorial when you get back to it. I look forward to reading future versions.Thanks.

**Comment by FRidh** [comment]
> It also strikes me as puzzling that python libraries that need access to the location of fonts, such as matplotlib and pyglet, don't get those environment variables built for them.

Users typically do not use them in derivations (aside from my example and what you're looking for) and so therefore the derivations do not include them. We could add a fontconfig hook like I made.

> In my case, the demos for psychopy that I am trying to run might need both matplotlib and pyglet. Is each of those going to require its own unique FONT_CONFIG line?

If I understand correctly, each demo will be a derivation. Therefore, each demo will have to have a fontconfig. Again, when using a hook, its very easy, just add the hook to the `buildInputs` and you're done.

Also, `pyglet.lib.load_library('fontconfig')` is likely using a FFI and we do not support that. Instead, we hardcode paths to libraries.
