### ISSUE TITLE
Package request: wl-clipboard-rs

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#265812]
**Project description**

A rust implementation of wayland-clipboard.

**Metadata**

* homepage URL: https://github.com/YaLTeR/wl-clipboard-rs
* source URL: https://github.com/YaLTeR/wl-clipboard-rs
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by FliegendeWurst** [comment]
I assume you want the tools in https://github.com/YaLTeR/wl-clipboard-rs/tree/master/wl-clipboard-rs-tools, not the library itself?

**Comment by Freed-Wu** [comment]
Oh, yes. :smile: It looks like a safer alternative of wl-clipboard.

**Comment by Aleksanaa** [comment]
Okay, but the author seems [doesn't like cargo.lock](https://github.com/YaLTeR/wl-clipboard-rs/blob/f73abbf8fc17e2c8c6f81633d52fdc21c0f6284e/.gitignore#L3).

**Comment by donovanglover** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/280271
