### ISSUE TITLE
pdm 2.10.0 nixpkgs-unstable: permission denied error on `pdm init`

### ISSUE THREAD

**Issue by JonBoyleCoding** [NixOS/nixpkgs#265883]
### Describe the bug
When running `pdm init` from `pdm 2.10.0` for creating a new package, the following `permission denied` error occurs. This does not happen with `pdm 2.6.1` currently in `nixpkgs-23.05`.

![image](https://github.com/NixOS/nixpkgs/assets/630329/7e032753-bd66-4569-96cb-21c7d0727e05)

### Steps To Reproduce
1. Use the following flake to get current unstable branch of `pdm 2.10.0` with `python311`
```
{
	inputs = {
		nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
		flake-utils.url = "github:numtide/flake-utils";
	};

	outputs = {nixpkgs, flake-utils, ...} :
		flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-darwin" ] (system:
			let
				pkgs = import nixpkgs { config.allowUnfree = true; inherit system; };
			in {
			devShells.default = pkgs.mkShell {
				inherit system;
				buildInputs = with pkgs; [ python311 pdm ];
			};
		});
}
```
2. Run `nix develop` to create the shell
3. Run `pdm init` and use defaults - other than specifying that the library is installable.

### Expected behavior
Process should complete without error.

### Notify maintainers

@cpcloud @natsukium 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.4335.898cb2064b6e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by natsukium** [comment]
Thanks for your report. I think it is fixed, could you please check the PR?

**Comment by JonBoyleCoding** [comment]
> Thanks for your report. I think it is fixed, could you please check the PR?

All good!
