### ISSUE TITLE
NixOS 23.11 — Zero Hydra Failures

### ISSUE THREAD

**Issue by figsoda** [NixOS/nixpkgs#265948]
Hi, we are figsoda & Ryan Lahfa, the release managers for NixOS 23.11 ("_Tapir_").

Today we want to invite everyone to participate in the Zero Hydra Failures Project, wherein we prepare the package set for the upcoming release, up until its public release at the end of November.

There are only two more upcoming dates that we'd like to mention in that context:

 - 2023-11-20: Branch-off
 - 2023-11-29: 23.05 Release

The complete timeline can be found in the

 - #258640.

## The mission

Every time we plan to do a release, we take time to stabilize the master branch and later on the release branch.
Our goal here is to reduce the number of failing jobs on the `nixpkgs:trunk` `nixos:trunk-combined` jobsets as much as possible before branch-off. We call this the "Zero Hydra Failure" campaign.

Besides aiming for zero failed jobs, we also strive to again provide all packages that were available in the previous release.

Changes need to always target the `master` branch. Take note that the branch-off will occur on 2023-11-20, after which ZHF changes will need to be tagged with the `backport: release-23.11` label to land in the stable release.

## Jobsets

The relevant jobsets to check for failing jobs are:

- [nixos:trunk-combined](https://hydra.nixos.org/jobset/nixos/trunk-combined) (Linux packages & NixOS tests)
- [nixpkgs:trunk](https://hydra.nixos.org/jobset/nixpkgs/trunk) (Linux & Darwin packages)

#### Eval reports

Evaluation reports provide a structural overview of the most impactful failing builds. They originated at https://github.com/nix-community/nix-review-tools and were automated over at https://github.com/malob/nix-review-tools-reports.

1. Navigate to https://malob.github.io/nix-review-tools-reports/
2. Open the relevant jobset: see the previous section on which jobset to select based on what you are looking at (Linux, Darwin or NixOS tests).
3. Browse the latest reports for build failures
![](https://md.darmstadt.ccc.de/uploads/upload_7bab0fdf57d45370e48ba62b43dfbc13.png)
4. Follow the links to the build failure on hydra

#### ZERO Hydra Failures

The platform automatically crawls Hydra and lists packages by maintainer and lists the most important dependencies (failing packages with the most dependants). It also graphs the general trend per platform.

1. Navigate to https://zh.fail

For the record, we started ZHF here:

```
Latest Linux evaluation (completely built):	[1801356](https://hydra.nixos.org/eval/1801356) on 2023-11-04 14:18:21 (UTC)
Latest Darwin evaluation (completely built):	[1801390](https://hydra.nixos.org/eval/1801390) on 2023-11-05 12:54:55 (UTC)
Failing builds on aarch64-darwin:	915
Failing builds on aarch64-linux:	1240
Failing builds on i686-linux:	586
Failing builds on x86_64-darwin:	1142
Failing builds on x86_64-linux:	1491
Total failed builds	5374
```

For comparison, last's release ZHF started there:
<details>

```
Latest Linux evaluation (completely built):	[1794693](https://hydra.nixos.org/eval/1794693) on 2023-05-07 15:51:32 (UTC)
Latest Darwin evaluation (completely built):	[1794694](https://hydra.nixos.org/eval/1794694) on 2023-05-07 16:12:27 (UTC)
Failing builds on aarch64-darwin:	739
Failing builds on aarch64-linux:	1781
Failing builds on i686-linux:	612
Failing builds on x86_64-darwin:	825
Failing builds on x86_64-linux:	1909
Total failed builds	5866
```

</details>

#### Check on packages you maintain

1. Clone nixpkgs and checkout the `master` branch
2. Run 
   ```
   nix-build maintainers/scripts/build.nix --argstr maintainer <name>
   ```

Alternatively: you can check https://zh.fail/failed/overview.html also.

#### Hydra
Hydra is nixpkgs CI platform, where all active branches are built and pushed into the cache, after which channels can originate from its build results.

1. Open the [nixpkgs:trunk](https://hydra.nixos.org/jobset/nixpkgs/trunk) jobset
2. Select the latest evaluation
![](https://md.darmstadt.ccc.de/uploads/upload_968849d97f3c7aea84d173d36f360eac.png)
4. Directly failing jobs are marked with a red cross, while transitively failing ones are greyed out. 
![](https://md.darmstadt.ccc.de/uploads/upload_fb4efdad788e6f904fee43b6ebb40701.png)
5. Use the search form to scope the package list to things relevant to you and that you can test.
![](https://md.darmstadt.ccc.de/uploads/upload_885e122fe1c5ee6dda9b8b3eeffae267.png)

### Submit fixes

6. Search through PRs to make sure none provided a fix yet. If there is one, please take the time and help review the change.

7. If there is no open PR, troubleshoot why it's failing and fix it.

8. Pull Request the fix against the `master` branch and wait potential review & change requests
    - Add the `0.kind: ZHF Fixes` label, so people can better browse these fixes
    - If your PR causes more than ~500 rebuilds, it is generally preferred to target `staging` to avoid compute churn for users on `master`.
    - If no reviewer is automatically added to your PR, check the Git history or the maintainers and ping them (in the pull request) or add them (if you have the rights) as reviewers
    - If, after a while, no one reviewed the PR, you can post it in https://discourse.nixos.org/t/prs-ready-for-review/3032/2183 to get more attention
    - If, after an (extra) while, nothing really happened, you can drop a line in the NixOS development channel or mention @NixOS/nixos-release-managers on the PR

### Backporting

**After 2023-11-20**

10. Apply the relevant backport label to land the fix in the release branch
    - Changes to `master` get backported into `release-23.11`
    - Changes to `staging` get backported into `staging-23.11`

11. If the backport action fails, follow the [manual backporting steps](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes). Make sure to use `git cherry-pick -x <rev>` on all commits intended for backport.
    - @jonringer created a [video covering the backport process](https://www.youtube.com/watch?v=4Zb3GpIc6vk).

---

**Always link back** to this issue by mentioning the issue number in the description of your pull request:
```
ZHF: #265948
```

If your PR receives no reviews or does not get merged, feel free to
- add the `0.kind: ZHF Fixes` label, so people can better browse these fixes
- request or mention @NixOS/nixos-release-managers on the PR

## Broken packages

Everything we cannot fix in time will need to be marked broken on the respective platforms, so that Hydra will not retry builds over and over, thereby wasting compute resources.

Set `meta.broken` and add a reference and/or explanation, like this:

```nix
meta = {
  # ref to issue/explanation
  broken = stdenv.isDarwin; # only broken on darwin
  # broken = true; # broken on all platforms.
};
```

## Orphaned packages

You can read about **failing packages** without a maintainer here: https://zh.fail/failed/by-maintainer/_.html (orphaned packages).

If you're new to NixOS, adopting an orphaned package is a great way to get involved and contribute to the community. By doing so, you'll not only help improve the overall quality of the NixOS ecosystem, but you'll also gain valuable experience working with Nix, the language and tool that powers the package management system.

By adopting an orphaned package, you'll be taking on a responsibility that can be both challenging and rewarding. You'll need to understand the package's code and dependencies, make sure it builds and works correctly, and respond to any issues or pull requests that come up. This process can be a great learning experience, as you'll be exposed to a wide variety of programming languages and libraries.

Moreover, by adopting an orphaned package, you'll be making a tangible impact on the NixOS community. Your contributions will be greatly appreciated by users who depend on that package, and you'll be helping to ensure that NixOS releases are as stable and up-to-date as possible.

## Closing

This is a great way to help NixOS, and it is a great time for new contributors to start their nixpkgs adventure. :partying_face:

As with the [feature freeze issue](https://github.com/nixos/nixpkgs/issues/259040), please keep the discussion here to a minimum so we don't ping all maintainers (although relevant comments can of course be added here if they are directly ZHF-related) and ping one of the release managers (@figsoda, @RaitoBezarius) in the respective issues.

**Comment by paul-jewell** [comment]
You have a typo in line 3 - you mention release at end of "may" instead of "November". 
I'm not sure I know enough to support this, but I won't know without trying, so I will follow the instructions later and get started.

**Comment by figsoda** [comment]
@paul-jewell Good catch! thanks

**Comment by amjoseph-nixpkgs** [comment]
> I can't seem to find a way to add the ZHF Fixes label to my PRs. Can someone give me a hint?

You have to have commit privileges.  But you can mention this issue in your PR and it will appear in the log here and somebody will add it for you.

**Comment by Artturin** [comment]
> > I can't seem to find a way to add the ZHF Fixes label to my PRs. Can someone give me a hint?
> 
> You have to have commit privileges. But you can mention this issue in your PR and it will appear in the log here and somebody will add it for you.

Just being in the NixOS/nixpkgs-maintainers org group is enough to add labels.
@tu-maurice To join it add yourself as a maintainer to at least one package and you'll get a invite.

**Comment by tu-maurice** [comment]
@Artturin I'm in the list of maintainers in like 6 packages. I don't remember getting an invite. :shrug:

**Comment by ajaxbits** [comment]
Hi friends, first-time contributor here. Took care of an orphaned test, and I need help adding the `0.kind: ZHF Fixes` label to my PR, since I don't have label permissions: https://github.com/NixOS/nixpkgs/pull/266511

Thank you!

**Comment by robert-manchester** [comment]
what to do about abandoned upstream packages? eg: livestream was abandoned -- there is a maintained fork, streamlink, which is in nixpkgs. how to mark the livestream and livestream-curses packages for removal.

they are fixable, but fixing abandoned packages seems to just bring in more trouble and makes reviews harder.

**Comment by Artturin** [comment]
> what to do about abandoned upstream packages? eg: [livestream](https://github.com/streamlink/streamlink) was abandoned -- there is a maintained fork, [streamlink](https://github.com/streamlink/streamlink), which is in nixpkgs. how to mark the livestream and livestream-curses packages for removal.
> 
> they are fixable, but fixing abandoned packages seems to just bring in more trouble and makes reviews harder.
> 
> apologies is this is not the correct forum to post questions.

These but with a different throw message

For python modules https://github.com/NixOS/nixpkgs/commit/afb1afc55ef92f81c1b1a2f10fc3fe6bfa1b9129

For top-level packages https://github.com/NixOS/nixpkgs/commit/44c3048f284b34a5d1452e2c2af4d073d8b915b5

**Comment by ajaxbits** [comment]
> Hi friends, first-time contributor here. Took care of an orphaned test, and I need help adding the `0.kind: ZHF Fixes` label to my PR, since I don't have label permissions: #266511
> 
> Thank you!

One more that needs a tag [here](https://github.com/NixOS/nixpkgs/pull/266564). Thanks!

**Comment by ilya-fedin** [comment]
I'm having a very weird failure: https://hydra.nixos.org/build/224147055/nixlog/5

It refers to `crypto/cipher/cipher_test_cases.c` but the reference to it is removed by that patch: https://github.com/NixOS/nixpkgs/blob/aaaa627043127b4e046f808e582d107ed95efb02/pkgs/applications/networking/instant-messengers/telegram/kotatogram-desktop/tg_owt.nix#L80. How is that possible? It feels like Nix doesn't apply the patch, only on Darwin.

**Comment by a-n-n-a-l-e-e** [comment]
i can't seem to add the `0.kind ZHF Fixes` to my [PRs](https://github.com/pulls?q=author%3Aa-n-n-a-l-e-e+archived%3Afalse+NixOS+is%3Apr+is%3Aopen)

**Comment by paul-jewell** [comment]
> i can't seem to add the `0.kind ZHF Fixes` to my [PRs](https://github.com/NixOS/nixpkgs/pulls/a-n-n-a-l-e-e)

See this earlier comment from another message: https://github.com/NixOS/nixpkgs/issues/265948#issuecomment-1801772118

**Comment by figsoda** [comment]
NixOS 23.11 branch-off is done! Don't forget to add `backport release-23.11` to your pull requests!

**Comment by mfrischknecht** [comment]
@infinisil 

I still have a follow-up question to this latest ZHF :)

I decided to keep on looking if I can maybe create PRs for another couple of builds when/if I have the time to do so (with some success:  #270233). Since ZHF is a thing, I assume such drive-by-PRs are still beneficial on the whole. 

Since I'm still new to this: Is there some protocol to such fixes?
Do I simply tag the listed maintainers? Or will they be notified by some automation anyway?
Should I specify something along the lines of "I don't really care about this package, I'm simply trying to reduce Hydra failures"?

**Comment by infinisil** [comment]
> I decided to keep on looking if I can maybe create PRs for another couple of builds when/if I have the time to do so (with some success: #270233). Since ZHF is a thing, I assume such drive-by-PRs are still beneficial on the whole.

Awesome work! Yeah these contributions are always welcome. Generally I think we should prefer fixing more bugs over adding features. Though also some work can get rather tedious, so we should also invest some time in trying to improve automation (this generally requires rather deep knowledge though).

> Since I'm still new to this: Is there some protocol to such fixes? Do I simply tag the listed maintainers? Or will they be notified by some automation anyway? Should I specify something along the lines of "I don't really care about this package, I'm simply trying to reduce Hydra failures"?

The listed maintainers should automatically be requested for a review if you use the `<pkgname>: ...` [commit convention](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions). But sometimes people effectively maintaining a package aren't listed in the maintainers field, so feel free to check the Git history to figure that out and ping other relevant people.

It can totally happen that PRs aren't getting reviewed though. It's not great but it's because Nixpkgs has a lot less reviewers than committers. So to combat that, I recommend reviewing others PRs, so that committers have an easier time merging it.

**Comment by figsoda** [comment]
NixOS 23.11 has been released on 2023-11-29, and ZHF has ended. We still greatly appreciate any fixes for broken packages, but I will go ahead and close this issue now.
