### ISSUE TITLE
Update request: bun 1.0.7 → 1.0.9

### ISSUE THREAD

**Issue by TheOceanBreeze** [NixOS/nixpkgs#265999]
- Package name: bun
- Latest released version: 1.0.9

- Current version on the unstable channel: 1.0.7
- Current version on the stable/release channel: 0.6.2

- [*] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@DAlperin @06kellyjac 

People who've also recently updated the package:

@cornedor @BlankParticle 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by cornedor** [comment]
https://github.com/NixOS/nixpkgs/pull/266007
