### ISSUE TITLE
xfce: wallpaper not set to ~/.background-image

### ISSUE THREAD

**Issue by DaveBuckingham** [NixOS/nixpkgs#265990]
### Describe the bug
The desktop wallpaper is not set to ~/.background-image in xfce4

### Steps To Reproduce
1. Install nixos with xfce
2. Create file ~/.background-image
3. sudo nixos-rebuild switch

### Expected behavior
I expect the desktop wallpaper to be set.

### Additional context
It seems that feh no longer works to set the background in xfce?
It is possible to set the wallpaper with xfconf-query:
https://unix.stackexchange.com/questions/596070/how-to-change-wallpaper-on-xfce-from-terminal

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.05 (Stoat), 23.05.4527.60b9db998f71`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/blob/7206aa806399e9e3732e9bd5250d318234a4745f/nixos/modules/services/x11/desktop-managers/default.nix#L12

https://github.com/NixOS/nixpkgs/blob/7206aa806399e9e3732e9bd5250d318234a4745f/nixos/modules/services/x11/desktop-managers/default.nix#L76-L81

https://github.com/NixOS/nixpkgs/blob/7206aa806399e9e3732e9bd5250d318234a4745f/nixos/modules/services/x11/desktop-managers/xfce.nix#L148

If you use xfdesktop, you should use `xfconf-query` (or just `xfce4-settings-manager`) to set background.

If you have xfdesktop disabled via [`services.xserver.desktopManager.xfce.noDesktop`](https://search.nixos.org/options?channel=unstable&show=services.xserver.desktopManager.xfce.noDesktop), with 4ae12930f24eff5a06aa211063028c80385868ec (this is just merged) it will now try `feh` if you have `~/.background-image`, note that this still can be "not working" for some of the WMs if they try to set background another time *somewhere*.
