### ISSUE TITLE
gmic: No display available.

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#265966]
### Describe the bug

I'm using gmic and get errors like "No display available". For some things it would be nice if it would works.

```
[nix-shell:~/tmp/stacking/ALIGNED]$ gmic median_files \*.tif output gmic_blend_median.tif

[CImg] *** CImgDisplayException *** CImgDisplay(): No display available.
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Compute median of input image files '*.tif', with first frame 0, last frame -1, frame step 1, frame rows 20%, using precise algorithm.
- Iteration #1/5: Load rows 0-1604/8023.
    > Compute median blending of 6 frames.
- Iteration #2/5: Load rows 1605-3209/8023.
    > Compute median blending of 6 frames.
- Iteration #3/5: Load rows 3210-4814/8023.
    > Compute median blending of 6 frames.
- Iteration #4/5: Load rows 4815-6419/8023.
    > Compute median blending of 6 frames.
- Iteration #5/5: Load rows 6420-8024/8023.
    > Compute median blending of 6 frames.
- Done!
[gmic]-1./ Output image [0] as tif file 'gmic_blend_median.tif', with pixel type 'auto', no compression and bigtiff support (1 image 12032x8024x1x4).
[gmic]-1./ End G'MIC interpreter.
```

It seem to be an issue before: https://github.com/NixOS/nixpkgs/issues/218568

Does our build have support for X11 enabled?

### Steps To Reproduce

I don't know which commands should work, but here are some simple ones i get the error with:

```
[nix-shell:~/tmp/stacking/ALIGNED]$ gmic demos
[gmic]./ Start G'MIC interpreter (v.3.3.1).
[gmic] *** Error in ./demos/ *** Command 'demos': No display available.
```

```
[nix-shell:~/tmp/stacking/ALIGNED]$ gmic sample duck display2d
[gmic]./ Start G'MIC interpreter (v.3.3.1).
[gmic]./ Input sample image 'duck' (1 image 640x480x1x3).
[gmic]./ Start interactive display of 2D image [0].
[gmic] *** Error in ./display2d/_display2d/ *** Unknown command or filename 'p'; did you mean '%'?
```

```
[nix-shell:~/tmp/stacking/ALIGNED]$ gmic repeat 3 { sp } d
[gmic]./ Start G'MIC interpreter (v.3.3.1).
[gmic]./*repeat/ Input sample image 'barbara' (1 image 512x512x1x1).
[gmic]./*repeat/ Input sample image 'greece' (1 image 750x500x1x3).
[gmic]./*repeat/ Input sample image 'fruits' (1 image 600x400x1x3).
[gmic] *** Error in ./d/_display/ *** Command 'display': No display available.
```

### Expected behavior

The feature for displaying images work.

### Additional context

Got latest gmic with:

`nix-shell -I nixpkgs=channel:nixos-unstable -p gmic`

### Notify maintainers

@AndersonTorres @lilyinstarlight

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.8, NixOS, 22.11 (Raccoon), 22.11.4588.93fddcf640c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lilyinstarlight** [comment]
I think we should just have to add `xorg.libX11` to `buildInputs` for this to start working, judging by what I'm seeing in the upstream `FindCImg.cmake` for gmic

I'm also like 99% sure it's also already in the runtime closure of even the `lib` output for gmic, so that shouldn't increase the closure size either

Would you be able to test adding `xorg.libX11` to `buildInputs` and make a PR?

Thank you!

**Comment by davidak** [comment]
Sounds good. I will try that when i find time. Thank you!
