### ISSUE TITLE
dockerTools.buildImage result image created time is "47 years ago".

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#26593]
With following `bare.nix`

``` nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.dockerTools.buildImage { name = "minimal"; }
 ```

and following commands

``` bash
$ nix-build bare.nix 
/nix/store/qyr8h654yhm3f9bmi19cyy6cylsgjggg-docker-image-minimal.tar.gz

$ docker load < result
ea33a194ef23: Loading layer [==========================================>] 10.24 kB/10.24 kB

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
minimal             latest              8ee38dc84775        47 years ago        0 B

$ date
Thu Jun 15 19:00:30 ICT 2017
```

## Technical details

* System: NixOS: 17.09pre108553.0011f9065a (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5350_7689181e
* Nixpkgs version: "17.09pre108553.0011f9065a"
* Sandboxing enabled: build-use-sandbox = false

**Comment by joachifm** [comment]
Timestamps are often normalized to Epoch for reproducibility

**Comment by wizzup** [comment]
Thank you for clarification. Should this be mentioned in [documentation](http://nixos.org/nixpkgs/manual/#sec-pkgs-dockerTools) too?

**Comment by joachifm** [comment]
Timestamp normalization is a general packaging thing, I think it's mostly "expected" to occur. Is it a problem in the context of docker images? (I don't use docker). I suppose a small note saying not to be alarmed by creation dates far in the past wouldn't hurt, at worst it'd be redundant.
