### ISSUE TITLE
Build failure: coder

### ISSUE THREAD

**Issue by carloaromando** [NixOS/nixpkgs#266037]
### Steps To Reproduce

1. build *coder* (Tested on https://github.com/NixOS/nixpkgs/commit/a0b3b06b7a82c965ae0bb1d59f6e386fe755001d)
`NIXPKGS_ALLOW_UNFREE=1 nix build --impure nixpkgs#coder`

### Build log

[Gist](https://gist.github.com/carloaromando/8bd014e46e520b8eb7edd02ca3b1a483)

### Additional context

- Fails on `x86_64-darwin` with `nixpkgs-unstable` on https://github.com/NixOS/nixpkgs/commit/a0b3b06b7a82c965ae0bb1d59f6e386fe755001d
- Builds correctly if pointing to https://github.com/NixOS/nixpkgs/commit/835736de35faba3e57a7a4becc6b7e472ae72317

### Notify maintainers

@ghuntley @urandom2

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(carlo): `"home-manager, nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/Users/carlo/.nix-defexpr/channels/nixpkgs`
```

**Comment by kirillrdy** [comment]
@carloaromando maybe https://github.com/NixOS/nixpkgs/pull/253235 fixes the issue ? You can help test it

**Comment by carloaromando** [comment]
@kirillrdy I tried, but the build still fails on `x86_64-darwin`. I'll share the build log in the PR

**Comment by MartinLoeper** [comment]
Still an issue on NixOS rev 1042fd8b148a9105f3c0aca3a6177fd1d9360ba5

**Comment by smancill** [comment]
I just build this on Darwin without issues, but I am not sure why it is not being evaluated on Hydra anymore.

```
[{"drvPath":"/nix/store/1vzyz4mh0npxlqnpkskvnx8mzc8xx7vg-coder-2.13.4.drv","outputs":{"out":"/nix/store/klzmxpxxd42zi65khr5ldpwbrbf7hpsm-coder-2.13.4"},"startTime":1724288168,"stopTime":1724288171}]
```

**Comment by ofalvai** [comment]
Coder now builds successfully on both `aarch64-darwin` and `x86_64-darwin` on the current `master`. Hydra doesn't build it because it depends on `terraform`, which has an unfree license and Hydra doesn't build unfree packages.
