### ISSUE TITLE
xfce: visual issues of GTK3 programs

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#26604]
## Issue description

There are two problems with GTK3 programs which are reproducible when using ```XFCE``` as displayManager (there are no problems with ```plasma``` and ```icewm```)

1. Text selection is not visible in Firefox (starting from 53) and Chrome (starting from 59 https://github.com/NixOS/nixpkgs/pull/26512). Background of the selected area keeps its color.

2. Enormous borders in many programs, for example ```psensor``` and ```meld``` (it is reproducible even with simple wxvi:

![](http://i.imgur.com/0Rxq69V.png)
![](http://i.imgur.com/9tsLHrM.png)

### Steps to reproduce
```
  services.xserver = rec {
    enable = true;
    desktopManager.xfce.enable = true;
  };
```
then run various programs

## Technical details

* System: 17.09.git.02e12e6 (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5413_b4b1f452
* Nixpkgs version: "17.09.git.02e12e6762" 
* Sandboxing enabled: false

**Comment by emmanuelrosa** [comment]
XFCE applies a GTK3 theme. That's why GTK3 programs look different than when using them under a window manager. Which theme are you using? Have you tried changing the theme? See https://docs.xfce.org/xfce/xfce4-settings/appearance

**Comment by volth** [comment]
Yes, ```Raleigh``` theme seems broken.
Perhaps we should remove it from the distro.

**Comment by emmanuelrosa** [comment]
I think it would be better to report the issue upstream. Better yet, to send them a patch.
