### ISSUE TITLE
Package request: Keymapp

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#266113]
**Project description**

ZSA released a new graphical tool to configure their ergonomic keyboards.

It is provided as binary, so very easy to package. We can also see if we can build it from source.

I can look into it, but feel free to grab the task.

https://github.com/zsa/wally/wiki/Linux-install

**Metadata**

* homepage URL: https://www.zsa.io/flash/
* source URL: seem not to be open source (yet?). i will ask them
* license: 
* platforms: linux, mac, windows

**Comment by wathiede** [comment]
https://blog.zsa.io/keymapp/ states it will not be opensource.

**Comment by jankaifer** [comment]
I'd like to try, but I got stuck fairly quickly.
I'm not sure how to find the correct packages that provide needed libraries.
I [asked on Reddit](https://www.reddit.com/r/NixOS/comments/17xjy55/im_trying_to_package_a_binary_how_to_translate/?utm_source=share&utm_medium=web2x&context=3) - hopefully I get an answer soon.

**Comment by jankaifer** [comment]
Also, there might be trouble since they provide just URL for the latest binary. I'll reach out to them if we can get stable URLs.

**Comment by mythmon** [comment]
If it's helpful, I packaged this for Arch in the AUR here: https://aur.archlinux.org/packages/zsa-keymapp-bin. Notably, Florian from ZSA reached out to me and provided a version-pinned URL, which I'm using in that package, and they said that all future releases will also have specific version URLs.

**Comment by jankaifer** [comment]
Thank you those stable links are super helpful. Thanks for the dependencies I got needed libraries but I'm trying to figure out package name, I hope they will be similar to arch.

```
setting interpreter of /nix/store/bwxdfc238al3mmvsqx7qf3a1l4i3ip3l-keymapp-21.07.0/bin/keymapp
searching for dependencies of /nix/store/bwxdfc238al3mmvsqx7qf3a1l4i3ip3l-keymapp-21.07.0/bin/keymapp
    libusb-1.0.so.0 -> not found!
    libudev.so.1 -> not found!
    libwebkit2gtk-4.0.so.37 -> not found!
    libgtk-3.so.0 -> not found!
    libgdk-3.so.0 -> not found!
    libgdk_pixbuf-2.0.so.0 -> not found!
    libgio-2.0.so.0 -> not found!
    libjavascriptcoregtk-4.0.so.18 -> not found!
    libgobject-2.0.so.0 -> not found!
    libglib-2.0.so.0 -> not found!
    libstdc++.so.6 -> not found!
    libgcc_s.so.1 -> not found!
auto-patchelf: 12 dependencies could not be satisfied
```

**Comment by jankaifer** [comment]
I got all deps, it built succesfully, but it fails to start.
This is the derivation: https://github.com/JanKaifer/nixos/blob/6d8ad588dd07523299e45f62473e4c65887307e5/modules/custom-packages/keymapp.nix#L27-L39

And this is the error that I get when I start it (if also opens white empty window).
```bash
$ keymapp
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1400x600: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1400x600: Invalid argument
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 1400x600: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

**Comment by jankaifer** [comment]
[This](https://www.reddit.com/r/rust/comments/16tzu8w/comment/k3czf51/?utm_source=share&utm_medium=web2x&context=3) helped to resolve it. So it wosk like this now:
```
__NV_PRIME_RENDER_OFFLOAD=1 keymapp
```

Should I include this patch directly in the derivation or leave it out since it affects only nvidia users?

**Comment by jankaifer** [comment]
Created PR here: https://github.com/NixOS/nixpkgs/pull/268299

I have added that env variable to fix that nvidia problem, so it works out of the box.

**Comment by Shawn8901** [comment]
I'll check that later or tomorrow with my local version, that I have there since some days. I was also chatting with ZSA about keymapp.
I would also happily be a maintainer

**Comment by gerpiet** [comment]
@davidak you can close this issue now
