### ISSUE TITLE
Update request: intel-media-driver 23.1.6 → 23.3.5

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#266160]
- Package name: 23.1.6
- Latest released version: [23.3.5](https://github.com/intel/media-driver/releases/tag/intel-media-23.3.5)

- Current version on the unstable channel: 23.1.6
- Current version on the stable/release channel: 23.1.6

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

I'm noticing a lot of outdated packages in dusty old corners... might be a good idea to make a goal for next year automatic notification of every single package once they are more than a month out of date.

**Notify maintainers**

@SuperSandro2000 

PS: 01.org is gone because Intel, so all links going to there will have to be redirected to wherever intel hid them or swapped for archived versions.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by SuperSandro2000** [comment]
> PS: 01.org is gone because Intel, so all links going to there will have to be redirected to wherever intel hid them or swapped for archived versions.

We should probably do a treewide change to fix this. Can you do this?

**Comment by FavoritoHJS** [comment]
I mean, you probably know more about where the stuff is hiding now than me...

**Comment by SuperSandro2000** [comment]
> I mean, you probably know more about where the stuff is hiding now than me...

I actually don't. 😅 I would search like you.

> I'm noticing a lot of outdated packages in dusty old corners... might be a good idea to make a goal for next year automatic notification of every single package once they are more than a month out of date.

intel-media-driver is actually quite up to date since I am maintaining it and there is already an auto update bot that I don't know why didn't trigger yet.

**Comment by SuperSandro2000** [comment]
FYI #266294

**Comment by sdht0** [comment]
> intel-media-driver is actually quite up to date since I am maintaining it and there is already an auto update bot that I don't know why didn't trigger yet.

From https://r.ryantm.com/log/intel-media-driver/2023-11-05.log:

> [updateScript] skipping because derivation has no updateScript

**Comment by SuperSandro2000** [comment]
> [version] generic version rewriter does not support multiple hashes

The actual issue seems to be this because fetchpatch is used and I didn't know this so far which is surprising to me and I think many do not know this.
