### ISSUE TITLE
boot.loader.timeout does not work with systemd-boot

### ISSUE THREAD

**Issue by fin444** [NixOS/nixpkgs#266147]
### Describe the bug
I have the following bootloader settings, which haven't been changed in a long time. Recently, I noticed that the timeout wasn't activating anymore, and I had to manually select a profile each boot. Unfortunately, I'm not really sure when this change happened, but I believe it was somewhere between 1-4 weeks ago. I don't think it coincided to any changes in my configuration.
```
boot.loader = {
	systemd-boot.enable = true;
	efi.canTouchEfiVariables = true;
	timeout = 3;
};
```

### Steps To Reproduce
1. Use the config specified earlier. If that is not sufficient, I can provide more details of my setup.
2. Reboot and observe the bootloader timeout.

### Expected behavior
Timeout should count down before automatically selecting the default profile.

### Actual behavior
Timeout does not count down, and no profile is automatically selected.

### Notify maintainers

@dasJ @JulienMalka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 23.11 (Tapir), 23.11pre541036.63678e9f3d3a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
Weird. I use

```
boot.loader = {
	systemd-boot.enable = true;
	efi.canTouchEfiVariables = true;
	# timeout = 5; # not set as NixOS defaults to 5 seconds
};
```

and the default boot entry gets activated unless I stop it. Works on NixOS 23.05 and 23.11.

**Comment by fin444** [comment]
Commenting out `boot.loader.timeout` doesn't change the behavior, timeout still does not come into effect. Currently on almost-latest unstable.

**Comment by JulienMalka** [comment]
I don't think we have enough information to reproduce your issue. A number of machines rely on `systemd-boot` timers to reboot unattended (including the `systemd-boot` NixOS tests) and they seem to work correctly.

**Comment by CnTeng** [comment]
I got answer from [ArchWiki](https://wiki.archlinux.org/title/systemd-boot)
You should run
```shell
bootctl set-default ""
bootctl set-timeout ""
```
It will clear the UEFI variables.

**Comment by fin444** [comment]
Thanks, that was the solution. It seems that I at some point accidentally pressed `t` on the boot screen, which changed the timeout from "determined by config" to "no timeout". This can be undone with the commands you wrote, or by pressing `shift+t`.
