### ISSUE TITLE
Package request: `gitlab-ci-local`

### ISSUE THREAD

**Issue by justinTM** [NixOS/nixpkgs#266130]
**Project description**

> Tired of pushing to test your .gitlab-ci.yml?
\
Run gitlab pipelines locally as shell executor or docker executor.
\
Get rid of all those dev specific shell scripts and make files.

**Metadata**

* homepage URL: https://github.com/firecow/gitlab-ci-local
* source URL: https://github.com/firecow/gitlab-ci-local.git
* license: mit
* platforms: macOS, Linux, Windows

looked into nix packaging a little bit but i don't have bandwidth to add myself. however, i did read some things first before asking for help here:
- https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md
- https://unix.stackexchange.com/questions/717168/how-to-package-my-software-in-nix-or-write-my-own-package-derivation-for-nixpkgs
- https://github.com/nix-community/npmlock2nix
- https://github.com/nix-community/napalm
- https://www.nmattia.com/posts/2022-12-18-lockfile-trick-package-npm-project-with-nix/

...so i will pay attention to whatever someone may solve for this request!

**Comment by teto** [comment]
personal take but these projects are doomed to fail. Either install a true local gitlab or make it such that you spend a minimal amount of time in CI (and nix is great for that, just launch nix with eventually `sops  exec-env` to get access to your secrets (or similar tools like https://github.com/PierreBeucher/novops).

**Comment by justinTM** [comment]
dude it's such a nightmare. i switched off github because `nektos/act` sucks and i can't get this thing to even build a docker image inside a job

i had no idea you could "install gitlab"... hmm that could be the solution

**Comment by teto** [comment]
another way to debug gitlab jobs is to log into the running container so that you can run commands directly in it (either via netcat or you ssh into the gitlab-runner machine and `docker exec -it <NAME>` into the container)
