### ISSUE TITLE
spotify crashes: libGL.so.1 missing symbol drmGetDevices2

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#26617]
## Issue description

Spotify crashes on start because libGL is missing a symbol

### Steps to reproduce
```
$ spotify
/home/gilligan/.nix-profile/bin/spotify: /nix/store/pklsbgqx7h471k4qf1asq353iqsqmbi2-spotify-1.0.48.103.g15edf1ec-94/lib/spotify/libssl.so.1.0.0: no version information available (required by /home/gilligan/.nix-profile/bin/spotify)
/home/gilligan/.nix-profile/bin/spotify: /nix/store/pklsbgqx7h471k4qf1asq353iqsqmbi2-spotify-1.0.48.103.g15edf1ec-94/lib/spotify/libcrypto.so.1.0.0: no version information available (required by /home/gilligan/.nix-profile/bin/spotify)
/home/gilligan/.nix-profile/bin/spotify: /nix/store/f5vcin9z7gi1q5y3i7r6c4gipiypsssl-curl-7.52.1/lib/libcurl.so.4: no version information available (required by /home/gilligan/.nix-profile/bin/spotify)
/home/gilligan/.nix-profile/bin/spotify: symbol lookup error: /run/opengl-driver/lib/libGL.so.1: undefined symbol: drmGetDevices2

```

## Technical details

* System: 17.09pre108553.0011f9065a (Hummingbird)
* Nix version: 1.11.9
* Nixpkgs version: 17.09pre108553.0011f9065a
* Sandboxing enabled: no

**Comment by gilligan** [comment]
This isn't limited to spotify - thunderbild also failed to start. I cannot update this now since I need to work.

**Comment by vcunat** [comment]
This can most likely be worked around by updating the failing packages to your nixos version.  Handling impurities is just difficult.  Ref: https://github.com/NixOS/nixpkgs/issues/16779

**Comment by gilligan** [comment]
@vcunat I'm sorry - i totally didn't notice that I had a different version installed in my user environment ;/

I wonder if it made sense to mention this in the issue reporting template? I can't be only one falling into this trap? Also I think this is not the first time I made this mistake..

**Comment by vcunat** [comment]
NixOS/Nixpkgs tries hard to allow mixing different versions, but dependencies of impurely supplied libraries (such as libGL) are a tough nut.  We hope to overcome GPU-related ones via glvnd in future...

**Comment by aljones15** [comment]
I'm getting this what do a I need to upgrade?
