### ISSUE TITLE
Build failure: heygpt 0.4.1

### ISSUE THREAD

**Issue by tejing1** [NixOS/nixpkgs#266166]
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs/nixos-unstable#heygpt`

### Build log

```
$ nix build nixpkgs-unstable\#heygpt
error: hash mismatch in fixed-output derivation '/nix/store/q7fj9z13pcj9fij6mazyfkccmd6hlc83-source.drv':
         specified: sha256-gTyjj7NND5IYtnXhc454cWSzhAE+DwfPRGEWrHH+GNM=
            got:    sha256-oP0yIdYytXSsbZ2pNaZ8Rrak1qJsudTe/oP6dGncGUM=
error: 1 dependencies of derivation '/nix/store/skbzjy97lwcbpzkr677ivl1j29bswsm4-heygpt-0.4.1.drv' failed to build
```

### Additional context

Posting on behalf of someone who was asking for help on Discord.

### Notify maintainers

@aldoborrero

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230604.e7603eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by tejing1** [comment]
Bad hash was introduced in #264805

**Comment by tejing1** [comment]
Looking at the ofborg history on the PR, I'm wondering if upstream did a sneaky tag change shortly after the release...

**Comment by tejing1** [comment]
```console
$ nix-prefetch-github fuyufjh heygpt
{
    "owner": "fuyufjh",
    "repo": "heygpt",
    "rev": "3be31cb78971380de02f8f370658be931f1c645c",
    "sha256": "oP0yIdYytXSsbZ2pNaZ8Rrak1qJsudTe/oP6dGncGUM="
}
$ nix-prefetch-github fuyufjh heygpt --rev 5e1692eb7e8c6db22ae439f0e5564538c861de57
{
    "owner": "fuyufjh",
    "repo": "heygpt",
    "rev": "5e1692eb7e8c6db22ae439f0e5564538c861de57",
    "sha256": "gTyjj7NND5IYtnXhc454cWSzhAE+DwfPRGEWrHH+GNM="
}
```

sneaky tag-switch theory pretty much confirmed. Can we switch this package to always use commit ids in the future? If they've done it once...

**Comment by teto** [comment]
before switching to the more obscure commit ids, I would ask upstream not to do this anymore

**Comment by aldoborrero** [comment]
I think it's better to notify in upstream so he's aware of the situation.

**Comment by aldoborrero** [comment]
I already notified @fuyufjh about this in [the following issue](https://github.com/fuyufjh/heygpt/issues/14) so he's aware 🙂

Meanwhile I'll change the commit hash to match the new id.

**Comment by fuyufjh** [comment]
My bad. I was [fixing a build problem](https://github.com/fuyufjh/heygpt/commit/3be31cb78971380de02f8f370658be931f1c645c) caused by the GitHub Action, so I force-pushed the tag `v0.4.1`. Really sorry for the inconvenience and I will never do this again 🥹
