### ISSUE TITLE
Package request: inshellisense

### ISSUE THREAD

**Issue by sei40kr** [NixOS/nixpkgs#266101]
**Project description**

IDE style command line auto complete

**Metadata**

* homepage URL: https://github.com/microsoft/inshellisense
* source URL: https://github.com/microsoft/inshellisense
* license: mit
* platforms: unix, windows

**Comment by hmenke** [comment]
https://github.com/NixOS/nixpkgs/pull/265958

**Comment by sei40kr** [comment]
@hmenke @malob Thank you!
