### ISSUE TITLE
Stellarium 23.3 reports its version as 80.3

### ISSUE THREAD

**Issue by arosl** [NixOS/nixpkgs#266112]
### Describe the bug
Stellarium 23.3 will report its version as 80.3 and its copyright as 2000-1980 and not 2000-2023

### Steps To Reproduce
➜  ~ nix run nixpkgs#stellarium -- -v
Stellarium 80.3

### Notify maintainers
@kilianar 
@wegank
@AndersonTorres

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

➜  ~
```

**Comment by wegank** [comment]
Probably export `SOURCE_DATE_EPOCH` with a timestamp in 2023 (instead of 1980) in `preConfigure`?
