### ISSUE TITLE
Update request: mlxtend 0.22.0 → 0.23.0

### ISSUE THREAD

**Issue by GetPsyched** [NixOS/nixpkgs#266238]
- Package name: [`mlxtend`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/mlxtend/default.nix)
- Latest released version: 0.23.0

- Current version on the unstable channel: 0.22.0
- Current version on the stable/release channel: 0.21.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
Found 2 stale PRs that might fix this issue with some more work:
  - #217278
  - #162763

**Notify maintainers**

@evax 

Also, @jyp @abbradar, how do I fix tensorflow as it's marked broken based on some flag that I don't understand.

https://github.com/NixOS/nixpkgs/blob/85f1ba3e51676fa8cc604a3d863d729026a6b8eb/pkgs/development/python-modules/tensorflow/default.nix#L493

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by raspher** [comment]
Current version on the unstable channel: 0.23.0
    Current version on the stable/release channel: 0.22.0

**Comment by GetPsyched** [comment]
Hmm, looks like this has been resolved in #271586
