### ISSUE TITLE
Package request: Notesnook

### ISSUE THREAD

**Issue by dm0328** [NixOS/nixpkgs#266386]
**Project description**
Notesnook is a free (as in speech) & open-source note-taking app focused on user privacy & ease of use. To ensure zero knowledge principles, Notesnook encrypts everything on your device using XChaCha20-Poly1305 & Argon2.

Notesnook is our proof that privacy does not (always) have to come at the cost of convenience. We aim to provide users peace of mind & 100% confidence that their notes are safe and secure. The decision to go fully open source is one of the most crucial steps towards that.

**Metadata**

* homepage URL: https://app.notesnook.com
* source URL: https://github.com/streetwriters/notesnook
* license: mit, bsd, gpl2+ , ...GPL3.0
* platforms: unix, linux, darwin, ...Linux, Windows, MacOS, iOS, Android

**Comment by KUD-00** [comment]
It seems notesnook is already in the nixpkgs, and the update is on the way. #260523

**Comment by MikaelFangel** [comment]
Have you opened this package request because it's not available in 23.05? 😃

**Comment by dm0328** [comment]
Correct. Is it available in different channels?

Thank you, David Munson

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MikaelFangel** [comment]
Yes Notesnook is available on the [unstable channel](https://search.nixos.org/packages?channel=unstable&show=notesnook&from=0&size=50&sort=relevance&type=packages&query=Notesnook)

**Comment by eclairevoyant** [comment]
closing as new packages are generally not backported
