### ISSUE TITLE
Anyone working towards a Plasma 6 alpha overlay/flake?

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#266465]
Given the color management, HDR and other improvements in Plasma 6 I'd love to try out the pre-release as soon as I can. However that involves quite a few changes vs the current Plasma 5 packages in nixpkgs, such as moving everything to Qt 6. I'm not familiar with KDE packaging infrastructure and Nix error messages aren't the most helpful so if someone is already working towards that I'd prefer to help out there over redundantly NIH:ing everything.

**Comment by leo60228** [comment]
It's not in an upstreamable state, but my configuration repo contains Plasma 6's `breeze` and all of its dependencies (which are a surprisingly large number): https://github.com/leo60228/dotfiles/tree/main/pkgs/plasma-6

I haven't updated it since the end of August, though.

**Comment by jansol** [comment]
Some relevant changes #266868

**Comment by K900** [comment]
The actual meat of KF6/Plasma6 is in https://gitlab.com/K900/kde2nix . Please drop by Matrix if you want to help, because I rebase that repo pretty often as history doesn't really make sense on it yet.

**Comment by jansol** [comment]
@K900 do you have some quick getting started instructions? I'm still very new to flakes and haven't figured out how to use that repo.

**Comment by K900** [comment]
It is not very usable yet. Some Gear stuff you can build and run with `nix run gitlab:K900/kde2nix#gear.kate`, but a lot of it will currently just fail for whatever weird reason.

**Comment by K900** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/386765/07a3a327-b9e6-4bd8-80a6-c09a84ef2126)
:eyes:

**Comment by jansol** [comment]
Looks like development has moved over to https://github.com/nix-community/kde2nix
Lots of stuff is still broken but I'm quite impressed at how much is working already. Almost all of my (admittedly quite modest) set of things I use daily appear to be fine.

**Comment by phanirithvij** [comment]
https://github.com/NixOS/nixpkgs/pull/286522
