### ISSUE TITLE
Package request: Polonium

### ISSUE THREAD

**Issue by Anseryde** [NixOS/nixpkgs#266479]
**Project description**

Polonium is an unofficial successor to Bismuth built on 5.27, and a descendant of autotile.

**Metadata**

 homepage URL: https://github.com/zeroxoneafour/polonium
 source URL: https://github.com/zeroxoneafour/polonium
 license: MIT
 platforms: unix, linux, darwin, ...

**Comment by SuperSamus** [comment]
Duplicate of #239369.
