### ISSUE TITLE
ipmiview: KVM console doesn't work

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#26650]
Relevant discussion: https://github.com/NixOS/nixpkgs/pull/26337

I never managed to fix it, but the idea was to set LD_LIBRARY_PATH to $out (or other paths if that's insufficient)

**Comment by Mic92** [comment]
If LD_LIBRARY_PATH is the problem, then it should be possible to see failed attempts to load a library in the output of strace. I cannot do this, as I have no access to ipmi hardware.

**Comment by domenkozar** [comment]
It's a Java thing, failing to find a `.jar` iirc.

**Comment by domenkozar** [comment]
We know what to do: https://github.com/NixOS/nixpkgs/commit/41740ec0395059d426a4b3676c45cd886d2249ad#r25855218
