### ISSUE TITLE
Creating assets and a toolchain for building the NixOS wiki via the github repo

### ISSUE THREAD

**Issue by third3ye** [NixOS/nixpkgs#2665]
Step 1: Provide the NixOS wiki as a sourcecode on github
Step 2: Setup a toolchain to facilitate building of reference stores for tools within the media wiki installation to fetch from (even while offline) from the nixos docus or nixpkgs directly (things like descriptions, comparing commands between versions of nixpkgs and nixos). 
Step 3: Make it so that the toolchain building process can update currently available NixOS Wiki installations, as well as make new one, in case your organization only allows the use of the intranet and not the internet.
Step 4: Profit...?

**Comment by Profpatsch** [comment]
Can be closed @jagajaga
