### ISSUE TITLE
Games fail to start in Steam when setting gamescope in Launch Options

### ISSUE THREAD

**Issue by Kojuma04** [NixOS/nixpkgs#266551]
### Describe the bug
Games fail to start when setting gamescope in Steam launch options, but only when using `programs.gamescope.enable = true`, it works normally when installing gamescope via `environment.systemPackages`.

### Steps To Reproduce
1. set `programs.gamescope.enable = true` in configuration.nix
2. set `gamescope -- %command%` in Steam Launch options
3. try to start a game

### Expected behavior
Game starts normally but inside a gamescope session.

**Comment by SuperSamus** [comment]
Duplicate of #214275.

**Comment by Lord-Valen** [comment]
Closing as duplicate.
