### ISSUE TITLE
Package request: texstudio for macOS

### ISSUE THREAD

**Issue by Endle** [NixOS/nixpkgs#266548]
texstudio is already provided on linux: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/editors/texstudio/default.nix

texstudio is a cross-platform software. By setting up `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1` on my darwin-aarch64, texstudio compiles and runs successfully.

@ajs124  @cfouche can you have a look? Thank you.

**Metadata**

* homepage URL: https://www.texstudio.org/
* source URL: https://github.com/texstudio-org/texstudio/
* license: gpl2+
* platforms:  darwin, ...

**Comment by ajs124** [comment]
Personally, I won't. I don't support proprietary operating systems. If you want to add it to the package, feel free, but I won't ever be able to test it and therefore will be unable to maintain it.
