### ISSUE TITLE
KDE/Plasma: support spellchecking / dictionaries

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#26654]
## Issue description

Currently we build `sonnet` with support for `hunspell`.
https://github.com/NixOS/nixpkgs/blob/a821be7a0646adbb5c14dc94b0ace74992cad8f6/pkgs/development/libraries/kde-frameworks/sonnet.nix

Sonnet typically looks in `/usr/share/hunspell` for dictionaries
https://cgit.kde.org/sonnet.git/tree/src/plugins/hunspell/hunspelldict.h?id=6db26d1fcdc986c8341b13622d8eecae70a23bfd

That means it won't be able to find any dictionaries and thus spellchecking won't work.

**Comment by prusnak** [comment]
Is this still a thing? @ttuegel

**Comment by ttuegel** [comment]
Yes, this is still a problem. It seems like we should disable hunspell and use aspell, which is configured correctly in NixOS.

**Comment by ttuegel** [comment]
I marked this with "good first bug" because I think we need only to change `sonnet` to depend on `aspell`, and do some testing.
