### ISSUE TITLE
Clarifying default file standards along with the CLI tools?

### ISSUE THREAD

**Issue by ixxie** [NixOS/nixpkgs#26660]
The Nix ecosystem utilizes a number of default files, most prominently `default.nix`, but also `shell.nix` and `release.nix`. The standards and guidelines regarding the uses and specifications for these files are on occasion unclear, and in some cases clearly overloaded; having used NixOS for a year now, I feel that this ambiguity about how Nix expressions are used (or can be used) in certain contexts is one of the most confusing aspects of learning how to use Nix.

Since I understand a revamp of the CLI is underway, it seems this would be a good time to streamline these standards, and clarify them in the documentation.

As an example of what I mean,  while `shell.nix` would clearly be the default for `nix shell`, and I understand `release.nix` is to used with `nix ops` (and `nix env -i` ?), it seems `default.nix` has [a variety of uses](https://stackoverflow.com/questions/44088192/when-and-how-should-default-nix-shell-nix-and-release-nix-be-used). In particular, it is sometimes usable for `nix build`, and sometimes not.

Would it make sense to also have `nix build` look for a `build.nix`, and fallback on `default.nix` otherwise? I imagine following this sort of naming convention would not make sense in many cases, since I imagine for example `release.nix` works for both `nix env` and `nix ops`. This suggests the correct solution is a sort of search tree of default files for which these files look, with `default.nix` being the root node.

Of course, one will then possibly be concerned that a typical repo would end up cluttered with `.nix` files; an alternative would be a Nix expression library designed to help packagers a single `default.nix` file behave differently for these different tools.

**Comment by Mic92** [comment]
`release.nix` has not special meaning. `nix-shell` or `nix shell` will first try to load `shell.nix` and otherwise fall-back to `default.nix`: https://nixos.org/nix/manual/#description-13
`nix-instantiate` and `nix-build` defaults to `default.nix` if no argument is given: https://nixos.org/nix/manual/#description-12
