### ISSUE TITLE
floorp: WebRTC is not supported in nixpkgs build, while in distributed flatpak / binaries it works fine

### ISSUE THREAD

**Issue by yusdacra** [NixOS/nixpkgs#266620]
### Describe the bug

`floorp` build in nixpkgs disables WebRTC support and thus WebRTC does not function. This does not happen in the officially provided Flatpak and binaries.

### Steps To Reproduce
1. Get floorp from both nixpkgs and flatpak
2. open some application that uses WebRTC (in my case, i used Discord)
3. with the nixpkgs build, it won't function, but the flatpak build will work fine

### Expected behavior
WebRTC should function correctly.

### Additional context
This looks like it happens because `privacySupport` is set to `true` in the build:

https://github.com/NixOS/nixpkgs/blob/067dd6a0857258577bed3b447ef08c50d1d0aa8b/pkgs/applications/networking/browsers/floorp/default.nix#L45

which looks like it disables `webrtcSupport` indirectly:

https://github.com/NixOS/nixpkgs/blob/067dd6a0857258577bed3b447ef08c50d1d0aa8b/pkgs/applications/networking/browsers/firefox/common.nix#L113

Considering the official distributions support WebRTC fine, either `privacySupport` should be set to `false` or `webrtcSupport` should be set to `true`.

### Notify maintainers

@christoph-heiss

**Comment by christoph-heiss** [comment]
Thanks for reporting!

Your assessment seems to be right, I'll look into it - you can most likely expect a PR in the coming days.
