### ISSUE TITLE
command-not-found database may provide useless suggestions

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#26661]
## Issue description
command-not-found suggests mariadb for rcmysql, which is indeed included in mariadb, but is a broken link (to /etc/init.d/mariadb iirc) and as such unhelpful.

This is clearly a bug in the mariadb package, but should it perhaps also be considered a bug in the command-not-found database builder?

### Steps to reproduce

Enable command-not-found and type rcmysql in the shell. Install mariadb as it suggests and type rcmysql again.

## Technical details
- System: 17.03.1313.d10fe64124 (Gorilla)
- Nix version: nix-env (Nix) 1.11.10
- Nixpkgs version: "17.03.1313.d10fe64124"
- Sandboxing enabled:  true

**Comment by Mic92** [comment]
There is a bug in the code, which generates the database for `command-not-found`: https://github.com/NixOS/nixpkgs/pull/24962#discussion_r111743170 That's why it is disabled by default now.

**Comment by matthewbauer** [comment]
IMHO there's not a lot you can do when packages are providing bad links. I guess you're suggesting doing something along the lines of verifying symlinks which I suppose would be fine but it's a fairly rare case isn't it? Somebody can patch mariadb to rm /bin/rcmysql perhaps but it really is mariadb's problem.

I would really suggest people look at [nix-index](https://github.com/bennofs/nix-index). It is similar to command-not-found but also allows you to lookup paths that are outside of the /bin folder.

For a while, I've though Nixpkgs should have an additional meta attribute called ```expectedPaths``` that is just a list of paths that should be installed to that package. If it's not there, the builder will fail in the test phase. It would give an assurance that that path is expected by the user and implies that consumers of that package can rely on it being there. For example in hello:

```nix
{ stdenv, fetchurl }:

stdenv.mkDerivation rec {
  name = "hello-2.10";

  src = fetchurl {
    url = "mirror://gnu/hello/${name}.tar.gz";
    sha256 = "0ssi1wpaf7plaswqqjwigppsg5fyh99vdlb9kzl7c9lng89ndq1i";
  };

  doCheck = true;

  meta = {
    description = "A program that produces a familiar, friendly greeting";
    longDescription = ''
      GNU Hello is a program that prints "Hello, world!" when you run it.
      It is fully customizable.
    '';
    homepage = http://www.gnu.org/software/hello/manual/;
    license = stdenv.lib.licenses.gpl3Plus;
    maintainers = [ stdenv.lib.maintainers.eelco ];
    platforms = stdenv.lib.platforms.all;
    expectedPaths = [ "bin/hello" ];
  };
}
```

You would be fine to leave it empty and to have files in the derivation that aren't explicitly listed but you would also not have that assurance. ```command-not-found``` could then use this to prioritize expected paths like rcmysql in mysql over unexpected paths like in mariadb.

**Comment by Mic92** [comment]
There is no package there yet for `nix-index`, right?

**Comment by vcunat** [comment]
As for `rcmysql` in particular, it might be better to redirect the symlink.
```
$ nix-build -Q -A mariadb.all
/nix/store/blx7rpirxqmdxvhm89rq5nsrcg934j5a-mariadb-10.1.21
$ ls -l ./result/bin/rcmysql
lrwxrwxrwx 1 root root 22 Jan  1  1970 ./result/bin/rcmysql -> etc/mysql/init.d/mysql
$ ls -l ./result/etc/mysql/init.d/mysql 
-r-xr-xr-x 1 root root 12627 Jan  1  1970 ./result/etc/mysql/init.d/mysql
```

**Comment by 0xABAB** [comment]
I am in favor of getting nix-index in when the author of the tool has fixed all the currently open issues in it.
