### ISSUE TITLE
Build failure: flask-admin

### ISSUE THREAD

**Issue by korfuri** [NixOS/nixpkgs#266683]
### Steps To Reproduce

1. build python311Packages.flask-admin on unstable

### Build log

https://gist.github.com/korfuri/4a344752b0a1fe1b1869a04298ffbbbf

### Additional context

This is similar to the build failure in  #265079, it's caused by the `flask-mongoengine` optional dependency of `flask-admin` being incompatible with Flask 2.3. In that issue the fix was to remove the dependency. I believe this should be OK - flask-mongoengine is a "contrib" extension of flask-admin, it shouldn't be a required dependency in the Nix build.

### Notify maintainers

There are no maintainers for either flask-admin nor flask-mongoengine.
@NickCao  as the maintainer for flask may have opinions on the Flask ecosystem?
@tjni and @fabaff may care about flask-admin
@fabaff may care about flask-mongoengine

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[korfuri@kelyus:~/]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(korfuri): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/channels/nixpkgs`
```

**Comment by natsukium** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/266741

**Comment by korfuri** [comment]
Indeed, fixed in https://github.com/NixOS/nixpkgs/pull/266741 !
