### ISSUE TITLE
Update request: detox 1.2.0 → 1.4.5

### ISSUE THREAD

**Issue by nadir-ishiguro** [NixOS/nixpkgs#266713]
- Package name: detox
- Latest released version: 1.4.5

- Current version on the unstable channel: 1.2.0
- Current version on the stable/release channel: 1.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

Detox has been on github for a few years now: https://github.com/dharple/detox/releases

**Comment by kirillrdy** [comment]
@nadir-yttrium are you able to test https://github.com/NixOS/nixpkgs/pull/266729
