### ISSUE TITLE
Build failure: torchWithRocm:  Log limit exceeded 

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#266895]
### Describe the bug
torchWithRocm hydra build fails because of too many logs.
https://hydra.nixos.org/build/240496427

### Notify maintainers

 @teh @thoughtpolice @tscholak @NixOS/rocm-maintainers

**Comment by Madouura** [comment]
How exactly do you fix this? Is there a hydra option we can put in the derivation?
Otherwise, do we have to omit warnings?

**Comment by Madouura** [comment]
I have a fix by omitting some warnings, but should we do that?
Should we instead get hydra to allow bigger logs?
