### ISSUE TITLE
Strange newline in output of nix-env, and nix-build

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#26685]
## Issue description

Recently, I notice that sometime console output of `nix-env` and/or `nix-build` have something like this

    %

    T
    o
    t
    a
    l

full log can be found [here](https://github.com/NixOS/nixpkgs/files/1082887/nl.txt)

### Steps to reproduce

Not sure if it can reproduce, the above example is form `nix-env -iA nixos.arp-scan`

    $ echo $TERM && echo $PS1
    xterm-termite
    [\u@ \w] \n$

The problem is just occurred recently, I don't remember change any thing.

## Technical details

* System: NixOS: 17.09pre108553.0011f9065a (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5350_7689181e
* Nixpkgs version: "17.09pre108553.0011f9065a"
* Sandboxing enabled:  build-use-sandbox = false

**Comment by lheckemann** [comment]
I think this happens if you use the unstable version of nix with a stable daemon. If your is version 1.11, try upgrading it (careful! Downgrading will be a bit of a pain because of database schema incompatibilities) or downgrading the nix that you use (safe).

**Comment by wizzup** [comment]
The problem is minor, I can live with it.

I created this issue just for notifying that something happened.

**Comment by adamscott** [comment]
@lheckemann Unfortunately, I'm using both `nixUnstable` and unstable `nix-daemon` and it still does the same newlines issue for me.

``` zsh
~ ❯❯❯ nix --version
nix (Nix) 1.12pre5413_b4b1f452
~ ❯❯❯ nix-daemon --version
nix-daemon (Nix) 1.12pre5413_b4b1f452
```

**Comment by wizzup** [comment]
The problem is gone, I will close this issue.

If anyone else still having this problem, please reopen.
