### ISSUE TITLE
frigate: should restart on-failure by default

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#266837]
### Describe the bug

Currently frigate is not set up to restart on failure, which can lead to recording being terminated unexpectedly and events missed when they shouldn’t be.

### Steps To Reproduce
1. kill python frigate process
2. visit the web interface or `api/config` to see 503.

### Expected behavior

Frigate should live like a cockroach nest.

### Screenshots

N/A

### Additional context

N/A

### Notify maintainers

cc @hexa

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231029.4e43dd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by mweinelt** [comment]
Please note, that my github handle does not match my maintainer handle and you mentioned someone, who is not affiliated with nixpkgs.

**Comment by mweinelt** [comment]
Does frigate in fact crash for you regularly?

**Comment by nagisa** [comment]
Thank you for taking time to implement the change!

---

> Does frigate in fact crash for you regularly?

In my case it was actually due to an OOM condition. I'm not sure if frigate leaks or what, but I see the amount of memory frigate (or an associated service such as ffmpeg or go2rtc) consumes increase over a fairly long period of time (timescale in weeks.) It just so happened that I had sized the VM frigate runs inside quite tightly and OOM killer would kick in after a month of uptime or so.

That said, regardless of this experience being in part a PEBCAK, frigate is a service that, I suspect, most of users will expect to be running even through crashes.
