### ISSUE TITLE
npm Prefetcher hangs with old lockfiles

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#266825]
### Describe the bug

Lily and I talked about this in Matrix, this is the requested issue.
Basically it all narrows down to this package lock: https://github.com/dasJ/broken-npm-test

### Steps To Reproduce
1. Build it
2. See it hangs forever
3. Update lock
4. See it works

### Expected behavior

It should either give an error or just work.

### Additional context

> frontend-npm-deps> [2023-11-10T23:15:37Z DEBUG isahc::handler] Could not resolve host: 16.0.0-beta.8

https://github.com/dasJ/broken-npm-test/blob/8c6d8ed9b180a66a81b133f68bf467e12bcbe3be/package-lock.json#L2817

https://docs.npmjs.com/cli/v10/using-npm/package-spec#aliases

If it helps narrowing the npm version down, the package-lock.json was created in September of 2020 and was last changed in September of 2021.

**Comment by lilyinstarlight** [comment]
To clarify a bit, this isn't something specific to older lockfiles, it just looks like there is a version spec format that our fetcher does not currently support, but probably should
