### ISSUE TITLE
frigate: does not build on master due to duplicated opencv dependency

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#266839]
### Describe the bug

Frigate does not build with the following error in current master:

```
pythonCatchConflictsPhase
/nix/store/q2zpnf017gccs9w9mb0ikdqhkf0k5v82-catch_conflicts.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Found duplicated packages in closure for dependency 'opencv': 
  opencv 4.7.0 (/nix/store/vm72ad401cdp5npnv672n958ml142m4r-opencv-4.7.0/lib/python3.11/site-packages)
  opencv 4.5.5 (/nix/store/wiv4avp8plifiy5jr9099krdl8sd93cy-opencv-4.5.5/lib/python3.11/site-packages)

Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
```

### Steps To Reproduce
1. `nix build github:NixOS/nixpkgs/045472e056a50ffbc8094de0a6e40618df64b56e#frigate`

### Expected behavior

frigate should build

### Notify maintainers

cc @hexa

**Comment by nagisa** [comment]
It looks like the derivation for frigate overrides opencv to use specifically 4.5.5, but then there's some other dependency that pulls in the regular nixpkgs opencv.

**Comment by nagisa** [comment]
https://github.com/NixOS/nixpkgs/pull/260727

**Comment by mweinelt** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/267446.
