### ISSUE TITLE
tmux server exits when display-manager.service restarts

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#26687]
It used to be that I could restart the systemd service
`display-manager.service` and my tmux server (started from a terminal
emulator in the X session under the display manager) would remain in
the background, and I could attach to it after logging back in through
the restarted display manager.

Now, the tmux server exits when I restart `display-manager.service`.
I'm not saying this is necessarily a bug — it may just be a feature
similar to `KillUserProcesses` working as intended — but does anyone
around know how to prevent the tmux server from exiting when the
display manager does? (I'm only seeing results about
`KillUserProcesses` from Google, and I've long had that set to `no`.)

**Comment by rnhmjoj** [comment]
`KillUserProcesses=no` should do it. I will try it later.

**Comment by rnhmjoj** [comment]
Inded, it doesn't change a thing. Same for starting the process with `systemd-run`.
Maybe the session is terminated for some other reason.

**Comment by 8573** [comment]
I worked around this by (at @eternaleye's suggestion) running the tmux
server as a systemd user service, which causes the tmux server to
survive display-manager restarts *so long as* I stay logged in outside
the display manager, such as on a kernel console.

**Comment by yorickvP** [comment]
Possibly related: https://github.com/tmux/tmux/issues/1001
Can one of you try with tmux 2.3/2.4?

**Comment by rnhmjoj** [comment]
It's not limited to tmux so I think it's either a problem with systemd or the way we configured.

**Comment by 8573** [comment]
@stale: I still care about this.

**Comment by mnajib** [comment]
@stale: I still care about this.

**Comment by Gerschtli** [comment]
At least on my machine, this issue is fixed:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.git.876ef4adf67 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.05, nixos-21.05.3972.e3699f9a4be, nur-gerschtli, unstable-21.11pre326545.9303cc04458"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tomodachi94** [comment]
Closing, as this appears to be resolved https://github.com/NixOS/nixpkgs/issues/26687#issuecomment-960818369.
