### ISSUE TITLE
by-name checks do not show the command needed to reproduce locally

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nixpkgs#266931]
The by-name checks need to emit a series of command invocations which are sufficient to reproduce exactly what github is doing, locally, **outside of github**.

Right now the by-name checks aren't written in bash or nixpkgs; they're written in github.

Working on a fix.

**Comment by infinisil** [comment]
This is now addressed with https://github.com/NixOS/nixpkgs/pull/274591
