### ISSUE TITLE
Fcitx not working in QtWebkit applications

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#26696]
## Issue description

Fcitx is not reacting in QtWebkit applications like smtube or qutebrowser with the qtwebkit backend.
On the other side, it is working fine with regular Qt applications like qutebrowser with the default webengine.
Not sure of what could be the cause, but there have been a few problems between fcitx and Qt in the past.

Note: Ibus is working fine with qtwebkit.

This is not really a hurry, but it would be nice to have this fixed for fcitx users. ( like myself :) )

cc @abbradar @ttuegel 

### Steps to reproduce

Using fcitx in smtube or any other application using qtwebkit.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: 1.11.10
* Nixpkgs version: 17.09pre109180.0d4431cfe9
* Sandboxing enabled: true

**Comment by JohnAZoidberg** [comment]
Seems to work in smtube, which uses qtwebkit: 
![image](https://user-images.githubusercontent.com/5307138/68390887-8c475b00-0166-11ea-9323-6bc2de4f3196.png)

Can you reproduce it?

**Comment by ttuegel** [comment]
What Qt versions are the affected packages using?

**Comment by JohnAZoidberg** [comment]
Still can't reproduce it with nixos-20.03.1577.74a80c5a9ab.
@ericsagnes please let us know if you still run into this issue.
