### ISSUE TITLE
Update request: ffmpeg 6.0 → 6.1

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#266920]
- Package name: [ffmpeg](https://www.ffmpeg.org/)
- Latest released version: [6.1](https://github.com/FFmpeg/FFmpeg/blob/n6.1/Changelog)

- Current version on the unstable channel: [6.0](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/ffmpeg/6.nix)
- Current version on the stable/release channel: [5.1.3](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/ffmpeg/5.nix)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Atemu 

-----
Note for maintainers: Please tag this issue in your PR.

**Comment by arthsmn** [comment]
I was able to build ffmpeg 6.1 but I needed to switch from nv-codec-headers-11 to nv-codec-headers-12, which is not up-to-date. So [this PR needs to be merged](https://github.com/NixOS/nixpkgs/pull/260538).

**Comment by Atemu** [comment]
@arthsmn you can include that PR's commit in your PR and instruct Github to close it.

**Comment by arthsmn** [comment]
#271905 Done.
