### ISSUE TITLE
Cannot create glib schema

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#26702]
## Issue description

I'm attempting to [package the on-screen keyboard 'onboard'](https://github.com/NixOS/nixpkgs/pull/24986) and I've run into a few problems with glib schemas.

### Steps to reproduce

From what I can find on other packages I looked through, the right way to install a glib schema is to run: 

```
${glib.dev}/bin/glib-compile-schemas $out/share/glib-2.0/schemas 
```

For some reason in my package whenever I attempt to move my schema to that location and run the command, it doesn't seem to work and the `$out/share/glib-2.0` folder is empty.

```
    postInstall = ''
      mkdir -p $out/share/glib-2.0/schemas/ $out/lib/girepository-1.0
      cp onboard-default-settings.gschema.override.example $out/share/glib-2.0/schemas/10_onboard-default-settings.gschema.override
      ${glib.dev}/bin/glib-compile-schemas $out/share/glib-2.0/schemas
      '';
```

Even the schemas folder I created is gone. I've tried creating the directory in different sections of the package build and nothing seems to work. Is there a reason this directory would be getting deleted? And am I running the schema command correctly?

## Technical details

* System: (NixOS: `17.03.1298.5bafc71b61 (Gorilla))
* Nix version: (nix-env (Nix) 1.11.9)
* Nixpkgs version: ("17.03.1298.5bafc71b61")
* Sandboxing enabled: (Yes)

**Comment by vcunat** [comment]
IIRC the schemas are moved automatically in some of the later phases; we use a different path than the standard one to avoid file collisions when installing by `nix-env`.

**Comment by johnramsden** [comment]
@vcunat So the schema was probably in `$out/share/glib-2.0/schemas` and was just moved? Is the `$out/share/glib-2.0` folder usually empty?

**Comment by vcunat** [comment]
Here's the setup hook: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glib/setup-hook.sh#L12  There are make flags passed to install gschemas into a different location, etc.

**Comment by johnramsden** [comment]
@vcunat So should I be running `${glib.dev}/bin/glib-compile-schemas $out/share/gsettings-schemas/$name/glib-2.0/schemas/`?

**Comment by vcunat** [comment]
Yes, I *think* so.

**Comment by johnramsden** [comment]
Hmm, now i'm getting this in the postInstall. Should I need to be running it, or does the hook do it automatically? The schemas were already in that folder.

> Error opening directory '/nix/store/gl7bz9dks0145gfm0afz4nk0i5m8c35n-onboard-1.4.1/share/gsettings-schemas/onboard-1.4.1/glib-2.0/schemas/': No such file or directory

**Comment by johnramsden** [comment]
It looks like the error I was getting was unrelated to where the glib schema was being installed. The [fix for my problem](https://github.com/NixOS/nixpkgs/pull/24986#issuecomment-309905055) was to install `pkgs.gnome3.dconf` system-wide.
