### ISSUE TITLE
spyder for Python 3 broken (nixos.python35Packages.spyder)

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#26708]
The spyder-package for Python 3 cannot be installed:

$ nix-env -iA nixos.python35Packages.spyder
installing 'spyder-2.3.8'
error: libxml2 is not supported for interpreter python3.5m

* System: NixOS 17.03.1247
* Nix version: nix-env (Nix) 1.11.8

**Comment by FRidh** [comment]
If I'm correct this is because PySide for Qt4 is still used on stable. It's supposed to work with unstable but I haven't tested (and I should remove myself as maintainer of the package since I don't use it).

**Comment by FRidh** [comment]
@bjornfor I suppose you're not using Spyder with Python 3?

**Comment by bjornfor** [comment]
Nope, I haven't used spyder in a long time.

**Comment by FRidh** [comment]
@rkoe in this case the package is not broken, its just that nobody has bothered supporting it on Python 3.
At this moment, nobody is maintaining this package so I am closing this issue.
