### ISSUE TITLE
`unstable.bottles` has broken `vmtouch` for pre-loading of game files

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#267040]
### Describe the bug

```
13:10:06 (INFO) Launching an executable…
/nix/store/2j49dz23vzi9yc871pgwficjkb9bjgfl-vmtouch-1.3.1/bin/vmtouch: invalid option -- '-'
/nix/store/2j49dz23vzi9yc871pgwficjkb9bjgfl-vmtouch-1.3.1/bin/vmtouch: invalid option -- '-'

vmtouch v1.3.1 - the Virtual Memory Toucher by Doug Hoyte
Portable file system cache diagnostics and control

Usage: vmtouch [OPTIONS] ... FILES OR DIRECTORIES ...

Options:
  -t touch pages into memory
  -e evict pages from memory
  -l lock pages in physical memory with mlock(2)
  -L lock pages in physical memory with mlockall(2)
  -d daemon mode
  -m <size> max file size to touch
  -p <range> use the specified portion instead of the entire file
  -f follow symbolic links
  -F don't crawl different filesystems
  -h also count hardlinked copies
  -i <pattern> ignores files and directories that match this pattern
  -I <pattern> only process files that match this pattern
  -b <list file> get files or directories from the list file
  -0 in batch mode (-b) separate paths with NUL byte instead of newline
  -w wait until all pages are locked (only useful together with -d)
  -P <pidfile> write a pidfile (only useful together with -l or -L)
  -v verbose
  -q quiet
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

### Steps To Reproduce

Run any game with the 'Preload Game Files' option enabled and monitor the stdout

### Expected behavior

Preload my cyberpunk so that i don't get frame drops in-game bcs it's loading assets

### Screenshots

Irrelevant

### Additional context

Uses `unstable.bottles` through home-manager on stable NixOS, vmtouch currently has the same version in both stable and unstable releases.

### Notify maintainers

@psydvl @SCOTT-HAMILTON

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230829.2ab91c8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05, nixpkgs-unstable"`
 - nixpkgs: `/home/raptor/.nix-defexpr/channels/nixpkgs`
```

**Comment by Kreyren** [comment]
Looking through the source code of bottles it's flatpak 

https://github.com/bottlesdevs/Bottles/blob/af3a7ccf44cd17d40160b1db66a5c8177b6f4cf5/com.usebottles.bottles.yml#L103

is using vmtouch commit https://github.com/hoytech/vmtouch/commit/8f6898e3c027f445962e223ca7a7b33d40395fc6

Which is ahead of the 1.3.1 version
https://github.com/hoytech/vmtouch/compare/b8b30e81d51544d6b8f428552f10d5b398a77fcb..8f6898e3c027f445962e223ca7a7b33d40395fc6

And seems to have changed how the `-o` option behaves

https://github.com/hoytech/vmtouch/compare/b8b30e81d51544d6b8f428552f10d5b398a77fcb..8f6898e3c027f445962e223ca7a7b33d40395fc6#diff-8be6332fc101644207219b7526cb39ce790c21bd362fdf1cd0d544cd2a57e6a4R186

But that doesn't appear to be the breaking change:

https://github.com/bottlesdevs/Bottles/blob/af3a7ccf44cd17d40160b1db66a5c8177b6f4cf5/bottles/backend/wine/winecommand.py#L579

passing..

**Comment by SuperSamus** [comment]
Can't reproduce on 23.11.
I guess it was solved upstream (maybe by https://github.com/bottlesdevs/Bottles/commit/de8338e1a56685c9ac1f99b081c8b32a6c1e6aa9?).

**Comment by Kreyren** [comment]
Yep seems that it's fixed by upstream, thanks for looking into it
