### ISSUE TITLE
Python package hook to add /include/pythonx.x/ in NIX_CFLAGS_COMPILE

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#26719]
## Issue description
`gcc` cannot find `pyconfig.h` even if `pkgs.python` is a `buildInput`.

### Steps to reproduce
Try to compile a code that includes `pyconfig.h`.

## Technical details
Would it be pertinent to automatically add this path into `NIX_CFLAGS_COMPILE`?

**Comment by FRidh** [comment]
You will need to give more details. How are you compiling? Are you using `nix-build`, or not? Please give a minimal working example.

**Comment by nlewo** [comment]
I was trying to compile libboost 1.48 (with nix-build) which failed on `#include <Python.h>`. This header is exposed by the python derivation in the path `include/python2.7/Python.h`. `gcc` was not able to find it to compile the libboost because it only looks in /include/ to generate its `-I` argument.

I now use the libboost from nix so I'm no longer impacted by this problem.

Thanks to have close this issue and sorry about my reponse delay.
