### ISSUE TITLE
Update request: Atlas  0.14.1→ 0.15.0

### ISSUE THREAD

**Issue by zestsystem** [NixOS/nixpkgs#267136]
- Package name: atlas
- Latest released version: 0.15.0

- Current version on the unstable channel: 0.14.1
- Current version on the stable/release channel: Not packaged

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@marsam 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by MikaelFangel** [comment]
I've made some progress on the updating the package with the new dependencies. Currently, I've encountered an issue where it can't find postgres.h. I'm sure it's something simple I'm missing, and I don't have the time right now. So, I thought I would share what I got so far. (:

```
{ lib, buildGoModule, fetchFromGitHub, installShellFiles, libpg_query, xxHash, postgresql }:

buildGoModule rec {
  pname = "atlas";
  version = "0.15.0";

  src = fetchFromGitHub {
    owner = "ariga";
    repo = "atlas";
    rev = "v${version}";
    hash = "sha256-qEui+Y7auNFJwLSUT90jJH7IPgNW06phbJel9y3C1bk=";
  };

  modRoot = "cmd/atlas";

  vendorHash = "sha256-6FABkSPXewOP8TmSoEyMcIDe2Coyf/aJBIqTI/hLoVw=";

  nativeBuildInputs = [ installShellFiles ];
  buildInputs = [ libpg_query xxHash postgresql ];

  env.GOWORK = "off";

  ldflags = [ "-s" "-w" "-X ariga.io/atlas/cmd/atlas/internal/cmdapi.version=v${version}" ];

  subPackages = [ "." ];

  postInstall = ''
    installShellCompletion --cmd atlas \
      --bash <($out/bin/atlas completion bash) \
      --fish <($out/bin/atlas completion fish) \
      --zsh <($out/bin/atlas completion zsh)
  '';

  meta = with lib; {
    description = "A modern tool for managing database schemas";
    homepage = "https://atlasgo.io/";
    changelog = "https://github.com/ariga/atlas/releases/tag/v${version}";
    license = licenses.asl20;
    maintainers = [ maintainers.marsam ];
    mainProgram = "atlas";
  };
}

```

**Comment by zestsystem** [comment]
Yup. I'm stuck here as well. I think the issue has to do with this change in atlas:

cmd/internal/sqlparse/pgparse: move to pgquery (https://github.com/ariga/atlas/pull/2143)

I was able to find this from discourse: 
https://discourse.nixos.org/t/trouble-packaging-sqlc/18261/9

Trying the solution mentioned in the discourse leads to a different error and the runVend flag does not work either.

**Comment by W1M0R** [comment]
For those who need cloud support, look at the derivation in this comment: https://github.com/NixOS/nixpkgs/pull/267409#issuecomment-1814353365
