### ISSUE TITLE
Package request: vinegar

### ISSUE THREAD

**Issue by ardishco-the-great** [NixOS/nixpkgs#267254]
**Project description**

 An open-source, minimal, configurable, fast bootstrapper for running Roblox on Linux. 

**Metadata**

* homepage URL: https://github.com/vinegarhq/vinegar
* source URL: https://github.com/vinegarhq/vinegar
* license: gpl3+
* platforms: linux

**Comment by ayes-web** [comment]
Duplicate of #251690
