### ISSUE TITLE
Sane config dir saved in environment variable, requiring logout/login on switch

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#26727]
The module sets `$SANE_CONFIG_DIR`, so at a switch the configuration dir is not changed.
Is there a special reason we don’t use `environment.etc`, @abbradar?

**Comment by abbradar** [comment]
I actually rework this as part of #26287. I'm not sure why was it like this in the first place (and not sure who to ask).

**Comment by Profpatsch** [comment]
I don’t think this has been changed. I disabled the sane config in my system, because it also injects `LD_LIBRARY_PATH`, which affects the search path and startup time of *every single binary*.

```
  env = {
    SANE_CONFIG_DIR = config.hardware.sane.configDir;
    LD_LIBRARY_PATH = [ "${saneConfig}/lib/sane" ];
  };
```

This is everything but … sane. :drum:

**Comment by doronbehar** [comment]
Ideally, we should make every package that interacts with sane backends, look them up in `/etc/sane-libs`, and then we'd be able to remove the insane :drum: usage of `LD_LIBRARY_PATH`. I asked upstream whether an alternative solution is possible / available:

https://gitlab.com/sane-project/backends/-/issues/660

**Comment by bjornfor** [comment]
This issue was fixed by https://github.com/NixOS/nixpkgs/pull/199667.

**Comment by bjornfor** [comment]
@doronbehar: I agree. And thanks for the upstream issue.
