### ISSUE TITLE
keycloak hostname-url not configurable

### ISSUE THREAD

**Issue by Chaostheorie** [NixOS/nixpkgs#267230]
### Describe the bug

Keycloak offers the option to configure either the `hostname` or `hostname-url` configuration setting. The current keycloak module doesn't support the `hostname-url` option due to the way the config file is generated.

### Steps To Reproduce
1. Configure a keycloak service with only `services.keycloak.settings.hostname-url` and **not** `services.keycloak.settings.hostname`.
2. Build a system with this service and get `error: The option 'services.keycloak.settings.hostname' is used but not defined.`

### Expected behavior
Be able to configure either `hostname-url` or `hostname` as a setting.

### Notify maintainers

@talyz  (maintainer of keycloak module: `nixos/modules/services/web-apps/keycloak.nix`)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nixpkgs on  nixos-23.05
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.05 (Stoat), 23.05.20231110.da4024d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(cobalt): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/store/c8aplaf4cij0zr4bca19y1k2vi9qhslz-source`
```

**Comment by talyz** [comment]
#267906 should resolve this. Please try it out.

**Comment by Chaostheorie** [comment]
Thank you for the quick handling of the issue @talyz, I'll try to do it at work tomorrow

**Comment by Chaostheorie** [comment]
Has been tested and works.
