### ISSUE TITLE
pythonPackages.pygraphviz is broken

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#26738]
## Issue description
The package pythonPackages.pygraphviz (also for python3Packages) fails to build. See nix-build output
[pythonPackages.pygraphviz-1.4.rc1.txt](https://github.com/NixOS/nixpkgs/files/1090956/pythonPackages.pygraphviz-1.4.rc1.txt)

### Steps to reproduce
`nix-build -A pythonPackages.pygraphviz`

## Technical details

* System: 17.03pre103552.cb90e6a036 (Gorilla)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: 17.03pre103552.cb90e6a036
* Sandboxing enabled: false

**Comment by rnhmjoj** [comment]
The tests of the package are failing causing the build to fail:
```python
'strict graph "" {...}\n' != 'strict graph {...}\n'
```
https://github.com/pygraphviz/pygraphviz/pull/129 makes me think they could be ignored, for know at least. If you agree I will go on and disable the check.

**Comment by ck3d** [comment]
Thanks for the fast analysis. Currently no packages uses pygraphviz. I give +1 for disabling the test.

**Comment by rnhmjoj** [comment]
It should be fixed in the next channel update.
