### ISSUE TITLE
Build failure: ipu6-drivers

### ISSUE THREAD

**Issue by imchairmanm** [NixOS/nixpkgs#267416]
### Steps To Reproduce

1. build linuxKernel.packages.linux_6_6.ipu6-drivers on unstable

### Build log

https://gist.github.com/imchairmanm/3882257ea5e33a89df5587e15f4f3079

### Additional context

Worked up until a few weeks ago.

I'm still learning NixOs, but I had this enabled by including the following in my `configuration.nix` file:

```
hardware.ipu6.enable = true;
hardware.ipu6.platform = "ipu6ep";
```

Also failed the same when building directly with:

```
nix-build '<nixpkgs>' --attr linuxKernel.packages.linux_6_6.ipu6-drivers
```

### Notify maintainers

@mweinelt

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11pre544052.85f1ba3e5167`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by maartenbeeckmans** [comment]
I have the same issue. Did you already find a solution?

**Comment by imchairmanm** [comment]
@maartenbeeckmans No, unfortunately, no change so far.  I'm still experiencing the issue.

**Comment by mweinelt** [comment]
It's being worked on in #268618

**Comment by imchairmanm** [comment]
Oh, excellent. Thank you for the update @mweinelt!
