### ISSUE TITLE
Update request: Vaultwarden 1.28.1 → 1.30.0 (channel 23.05)

### ISSUE THREAD

**Issue by hideyourcodes** [NixOS/nixpkgs#267493]
- Package name: vaultwarden 
- Latest released version: 1.30.0
- Current version on the unstable channel: 1.28.1
- Current version on the stable/release channel: 1.28.1

Vaultwarden 1.30.0 fixes an issue with the mobile Bitwarden clients. Please include in 23.05 or in the upcoming 23.11 channel, thanks!

**Comment by alarsyo** [comment]
The latest version on the unstable channel is now 1.30.0 and it'll get included in 23.10 I believe :)

**Comment by hideyourcodes** [comment]
Great, thanks! :)
