### ISSUE TITLE
TOML format generation double escapes

### ISSUE THREAD

**Issue by korrat** [NixOS/nixpkgs#267491]
### Describe the bug

When generating a TOML value from a nix attrset, an escaped backslash in a nix string is double escaped in the output file.

### Steps To Reproduce

When passed through `(pkgs.formats.toml {}).generate`, this input

```nix
{ test  = "\u"; }
```

generates the output

```toml
test = "u"
```

and this input

```nix
{ test  = "\\u"; }
```

generates the output

```toml
test = "\\u"
```

Note how in the second example, there are two backslashes in the TOML file instead of one.

### Expected behavior

I would expect the second example to produce the TOML file:

```toml
test = "\u"
```

### Additional context

I ran into this issue while trying to configure `starship` in home-manager.
I want to use the syntax to specify Unicode escapes in the TOML file to allow use powerline characters in the prompt.

Alternatively, my use case could fulfilled by specifying the correct Unicode characters directly in the nix expression, but I did not find any documentation on how to do that.

### Notify maintainers

- @infinisil 
- @lopsided98 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(korrat): `"nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `not found`
```

**Comment by infinisil** [comment]
No worries, better have something filed twice than never!
