### ISSUE TITLE
python2.7-pylint-1.7.1: cannot find configparser

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#26745]
## Issue description
pylint for Python 2 requires the Python-module configparser, which is not included in Python 2, but available as separate package. But even if the configparser-package is installed, pylint does not find it.

So, please add a dependency from python27Packages.pylint to probably python27Packages.configparser and make python27Packages.pylint find the configparser-module.

### Steps to reproduce

- install python27Packages.pylint
- $ which pylint
  /home/user/.nix-profile/bin/pylint
- $ pylint
  Traceback (most recent call last):
  ...
  ImportError: No module named configparser

## Technical details

* pylint version: python2.7-pylint-1.7.1
* System: Debian GNU/Linux 8.8 (jessie)
* Nix version: nix-env (Nix) 1.11.11

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/commit/f25720cacb4688288d676e550ecd29441f07f57a
