### ISSUE TITLE
dbeaver: dependencies can no longer be fetched

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#267405]
### Describe the bug

The dbeaver build uses `buildMavenPackage`, which keeps the maven dependencies in a Fixed-Output Derivation (FOD). Building this FOD tries to fetch dependencies from https://dbeaver.io/eclipse-repo , which is now 404. This is obscured by the fact that the FOD is in the binary cache, but means the package cannot be rebuilt.

### Steps To Reproduce

* remove the `mvnHash` from `pkgs/applications/misc/dbeaver/default.nix b/pkgs/applications/misc/dbeaver/default.nix`
* `nix build .#dbeaver`

### Notify maintainers

@jojosch @mkg20001

**Comment by wegank** [comment]
There have been at least 6 unsuccessful attempts to update `dbeaver` in nixpkgs. Could we simply drop it in favor of a `dbeaver-bin`?

**Comment by TomaSajt** [comment]
I tried to update to a newer version, did all the maven hacks I could, but didn't get anywhere...
I think that the fact that upstream uses tycho is the main culprit
Here's the `diff -r` of `fetchedMavenDeps` build twice
[diff.txt](https://github.com/NixOS/nixpkgs/files/13865930/diff.txt)
There are timestamps and whatnot all over the place, the whole thing is a mess
It also looks like it's using different mirrors for the same file, but putting it in a directory named after the mirror. Maybe there's a way to override the mirror sites to only use 1 (bad solution IMO). Honestly, no idea how to proceed from source...

**Comment by RohanHart** [comment]
Agreed, Tycho was the issue in my failed update
