### ISSUE TITLE
Update request: rustpython 0.2.0 → 0.3.0

### ISSUE THREAD

**Issue by Jackaed** [NixOS/nixpkgs#267469]
- Package name: rustpython
- Latest released version: 0.3.0

- Current version on the unstable channel: 0.2.0
- Current version on the stable/release channel: 0.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@prusnak 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by raspher** [comment]
#269228


    Current version on the unstable channel: 0.3.0
    Current version on the stable/release channel: 0.2.0
