### ISSUE TITLE
The LLVM man pages change is miserable

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#26756]
I'm trying to build a rust package right now on master and because sqlalchemy changed recently, I'm rebuilding sphinx, LLVM, rustc, and a few other things in between. Can we default man pages to being off until this gets handled properly?

What prompted this is that the sphinx build is failing for reasons I haven't figured out yet, so now I can't do my rust work...

Edit: I'm on Darwin, running against latest master at https://github.com/NixOS/nixpkgs/commit/5cbc6ca9bb63f939dab2c2c82a63d72f1f30d9b7

cc @dtzWill @LnL7 @vcunat

**Comment by FRidh** [comment]
The man pages for LLVM 4 are not build on Darwin for the stdenv, but they are otherwise.
I would also prefer not building those man pages because there's a whole lot of tiny packages that may now cause a mass-rebuild.

> so now I can't do my rust work...

Surely you can use a slightly older commit to work from.

**Comment by Mic92** [comment]
Is it possible to build an output independent from the rest of the package?

```
llvm = stdenv.mkDerivation {
  man = stdenv.mkDerivation {
  };
}
```

Then a change to python would only rebuild the man pages, but not any other program using llvm.
Otherwise it could be a dedicated package: `llvm-manpages`

**Comment by vcunat** [comment]
It would technically not be an output of the same derivation, but it is possible to add such attributes (though `passthru` to avoid the dependency).

**Comment by Mic92** [comment]
Would it be pulled by `buildEnv` or `systemPackages`?

**Comment by LnL7** [comment]
It won't work with `extraOutputsToInstall`, but you would be able to add `clang.cc.man` explicitly.

**Comment by copumpkin** [comment]
@edolstra would be kind of cool if we could pretend to be an output of a derivation so the existing machinery would work seamlessly with it (i.e., it would show up in `outputs`), even though it's a `passthru` attribute. Seems like it could be a cute Nix feature. Something like `fakeOutputs = { man = mkDerivation ...; }` and `fakeOutputs` would behave like `passthru` but show up in `outputs`.

**Comment by edolstra** [comment]
Yeah that would be pretty nice.

**Comment by vcunat** [comment]
Well, the `outputs` list is easy to overwrite.  I'm not sure if there's something else we would be missing in nixpkgs.
