### ISSUE TITLE
Update request: gitea 1.20.5 → 1.21.1

### ISSUE THREAD

**Issue by jlbribeiro** [NixOS/nixpkgs#267517]
- Package name: gitea
- Latest released version: 1.21.1 ([go-gitea/gitea v1.21.1 release](https://github.com/go-gitea/gitea/releases/tag/v1.21.1))

- Current version on the unstable channel: 1.20.5
- Current version on the stable/release channel: 1.19.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**: @disassembler @kolaente @Ma27 @techknowlogick 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by techknowlogick** [comment]
please see: https://github.com/NixOS/nixpkgs/pull/267531
