### ISSUE TITLE
virt-manager: SPICE console no longer works

### ISSUE THREAD

**Issue by chadcatlett** [NixOS/nixpkgs#267579]
### Describe the bug
Creating a VM using virt-manager results in SPICE console failures when trying to connect to the VM's video output.

### Steps To Reproduce
1. Create a Linux VM, I used generic2022 as the OS
2. Everything else default presented by virt-manager
3. Start VM

### Expected behavior
The resulting VM window should show the video output of the VM.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/108175/f9736653-4ab6-454c-9ebf-a771cac361bf)

### Additional context
I see this in the python logger output:
```
[Tue, 14 Nov 2023 20:23:49 virt-manager 9927] DEBUG (console:721) Starting connect process for proto=spice trans= connhost=127.0.0.1 connuser= connport= gaddr=127.0.0.1 gport=5900 gtlsport=None gsocket=None
[Tue, 14 Nov 2023 20:23:49 virt-manager 9927] ERROR (console:737) Error connecting to graphical console
Traceback (most recent call last):
  File "/nix/store/pcfl874r5b6l1wasqd7hd5jiifnmmp2p-virt-manager-4.1.0/share/virt-manager/virtManager/details/console.py", line 727, in _init_viewer
    raise RuntimeError(
RuntimeError: Error opening SPICE console: Typelib file for namespace 'GstBase', version '1.0' not found
```

### Notify maintainers
@qknight @offline @fpletz @globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.11, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(c): `""`
 - nixpkgs: `/nix/store/0y446mjvwzrhv723jh0lpkaz9gw8jzbq-source`
```

**Comment by hensou** [comment]
Maybe related to this change? 
https://github.com/NixOS/nixpkgs/commit/ba1389029e2e9933b514fb1a8123c7c0eeb8ae47

**Comment by MikaelFangel** [comment]
I can confirm that reverting https://github.com/NixOS/nixpkgs/commit/ba1389029e2e9933b514fb1a8123c7c0eeb8ae47 fixes the issue.

**Comment by hensou** [comment]
Hey @MikaelFangel, could you show me how you do this revert it?

I did like the following:

```nix
    (virt-manager.overrideAttrs (old: {
      propagatedBuildInputs = [
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
      ];

      nativeBuildInputs = lib.lists.subtractLists [ wrapGAppsHook ] old.nativeBuildInputs;
      buildInputs = lib.lists.subtractLists [
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
      ]
        old.buildInputs
      ++ [
        python3.pkgs.pygobject3
        python3.pkgs.libvirt
        python3.pkgs.libxml2
        python3.pkgs.requests
      ];

    }))
```

But since I'm not yet very familiar with nix, I was wondering if there is a right way to do that.

**Comment by MikaelFangel** [comment]
@hensou I haven't made any fixes to my nix configuration, I tested by reverting the commit on the master branch and rebuilding the package. (:

**Comment by jarrodsfarrell** [comment]
For anyone that needs this _now_ for some reason, here's the following you can put into your `environment.systemPackages` or wherever else.
```nix
# PR: 267722
(virt-manager.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [wrapGAppsHook];
  buildInputs = lib.lists.subtractLists [wrapGAppsHook] old.buildInputs ++ [
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
  ];
}))
```
