### ISSUE TITLE
Duplicate KDE themes

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#267687]
### Describe the bug

Both, the global theme, as well as the Konsole settings, provide duplicate themes, without me ever copying a single one of them.

I recognized this behavior with the global themes right once I setup the installation from scratch, a couple of weeks ago. 

I did not look into the Konsole profiles until now, so I dont know since when that in is the case.

### Steps To Reproduce
1. Install NixOS Plasma
2. Look into "System Settings > Appearance > Global Theme"
3. Look into Konsole > Settings > Profile > Edit

### Screenshots

![Screenshot_20231115_155159](https://github.com/NixOS/nixpkgs/assets/6344099/677a76bd-8496-4ae6-83f3-989d281ed8d1)

### Notify maintainers

@ttuegel 
@nyanloutre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.05 (Stoat), 23.05.4662.34bdaaf1f0b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MikaelFangel** [comment]
Konsole themes are also mentioned in #266938

**Comment by ShalokShalom** [comment]
As there is already an issue for Konsole, I close this. Thanks!
