### ISSUE TITLE
ghcWithHoogle no longer include any packages but the default set

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#26760]
@peti @shlevy: I rebuild pretty much nightly, and some time between these two generations, `ghcWithHoogle` was broken:

```
 211   2017-06-10 21:25:38
 212   2017-06-11 05:51:30
```

These are PST local. I haven't been able to track down which commit yet, but reverting @shlevy 's `developPackage` changes doesn't seem to fix the problem (for what I can tell so far).

In generation 211, `ghcWithHoogle` includes `fgl`, for example, one of the packages I passed as an argument.  In generation 212, it includes almost no packages at all except for `base`, `ghc`, and a couple of others.

I've read through the commit log between these dates (using `git log --date=local`), but nothing stood out to me.  If I have time tomorrow I'll try to `bisect` this, but I likely won't be able to until the weekend.

**Comment by shlevy** [comment]
Nothing obvious stands out, bisecting now.

**Comment by shlevy** [comment]
... which involves rebuilding ghc at least once :grin:

**Comment by peti** [comment]
Yeah, it does. :-| I'm bisecting right now, too. It's gonna be interesting to see who can post results first, although I fear I'm gonna lose because my desktop is kinda old by today's standards.

**Comment by peti** [comment]
00892b7e4ed2e8eb52227db8e8312a06bd1d6699 is the first bad commit. Now, this is a surprise.

**Comment by peti** [comment]
50ed8e43f473d666754cb559cb4d2fe214596932 pushed for testing on Hydra.
