### ISSUE TITLE
elixir / erlang OTP : enable `wxWebView`

### ISSUE THREAD

**Issue by c4lliope** [NixOS/nixpkgs#267712]
### Describe the bug

Elixir's Erlang VM (https://github.com/erlang/otp) is compiled with `wxWidgets` bindings called `wxErlang`.
On NixOS, the basic elixir package seems to include `wxErlang`, though `wxWebView` is missing.

`wxWebView` is necessary for more modern Elixir hybrid apps, such as:
https://github.com/elixir-desktop/desktop-example-app
This codebase is designed to run a common Phoenix-framework web app inside a desktop `wxWebView`, including local `sqlite` memory. I had some amazing success cross-compiling this to mobile also, using other wrappers inside the https://github.com/elixir-desktop org. Sadly, all of my accomplishments there seem bound to the more common Linux branches like Ubuntu / Debian / Fedora; unless a repair can be made in the nix compilation of `wxErlang`.

Also see: https://github.com/erlang/otp/blob/master/HOWTO/INSTALL.md#building-with-wxerlang

### Steps To Reproduce

```nix
{ config, pkgs, lib, ... }:

{ environment.systemPackages = with pkgs;
  let elixir = beam.packages.erlang_26.elixir_1_15;
  in [ webkitgtk wxGTK32 elixir ];

  services.xserver = { enable = true;
    desktopManager.gnome.enable = true;
    displayManager = { gdm.enable = true; gdm.wayland = false; };
  };

  environment.shells = [ pkgs.zsh ];
  programs.zsh.enable = true;
}
```

In a shell, run: `iex -e ':wx.demo'`

### Expected behavior

All of the demos inside the wxErlang widgets demo should display properly.

### Screenshots

![Screenshot from 2023-11-15 12-40-40](https://github.com/NixOS/nixpkgs/assets/30454698/64601884-8387-4bf4-9788-a47cc69c76b5)

### Additional context

```console
git clone https://github.com/elixir-desktop/desktop
cd desktop
mix deps.update --all                                                                                              │
mix deps.get
mix run                                                                                              │
# ...
# [warning] Your erlang-wx is missing wxWebView support. Will show OS browser instead
```

### Notify maintainers

especially @happysalada
also cc: @justinwood / @Br1ght0ne / @DianaOlympos / @gleber / @minijackson / @yurrriq 

### Metadata

```console
calliope@chesapeake:~/ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre546442.911ad1e67f45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by happysalada** [comment]
It lools like wx needs to be compiled with the webview flag for it to be enabled
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/wxwidgets/wxGTK32.nix#L111
And its only enabled by default on darwin.
Also by default im not sure if erlang is using yhe right wxgtk , if its not you can pass it as wxpackages i think.
Would you mind trying to enable webview and also to pass the right package to erlang upon compilation.

**Comment by c4lliope** [comment]
@happysalada -
Using your guidance and some help from another member of hacdc.org,
I had some luck making a flake!

```nix
{
  inputs = { nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable"; };
  outputs = { nixpkgs, ... }: 
  let
    arch = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${arch};
  in 
  with pkgs;
  {
    packages.x86_64-linux = rec {
      wx = (wxGTK32.override { withWebKit = true; });
      erl = erlang_26.override { wxPackages = [ libGL libGLU wx xorg.libX11 ]; };
      ex = (beam.packagesWith erl).elixir_1_15;
    };
  };
}
```

```console
calliope@chesapeake:~/wx/ > ./result/bin/iex -e ':wx.demo'
```

![Screenshot from 2023-11-16 01-28-30](https://github.com/NixOS/nixpkgs/assets/30454698/db223fef-d30a-4522-9009-9e608b340584)

**Comment by happysalada** [comment]
Nice ! If you are interested in contributing the fix back to nixpkgs im happy to help you get it merged.
No worries at all of course if you dont have time for it.

**Comment by c4lliope** [comment]
I'd like to; I'll check in on this again soon then.

**Comment by matthewmazzanti** [comment]
Looks like the fix is just changing the `withWebKit` flag on the `wxGTK` build(s) to `true` by default. Was wondering if there were any blockers there, so did some digging.

Seems that flag was originally introduced to fix a darwin build here: https://github.com/NixOS/nixpkgs/pull/163335/files
Then, later the darwin-only assertion around the flag was removed to fix the build: https://github.com/NixOS/nixpkgs/pull/165630/files

Since the package builds, seems like there aren't any technical hurdles around enabling it. Only other consideration is the additional dependencies around the elixir VM. Big question is whether you enable it both on `wxGTK31` *and* `wxGTK32`, or just `wxGTK32` for better backwards compat.

**Comment by happysalada** [comment]
I would say only on the latest version would be easier for potential breakage.
Would be happy to help you get the PR merged.
