### ISSUE TITLE
riscv64-embedded fails to link anything, discovered as spike build failure

### ISSUE THREAD

**Issue by ekliptik** [NixOS/nixpkgs#267859]
### Describe the bug
riscv64-none-elf-gcc fails to link basic file. This breaks the build of spike. . You will see `riscv64-none-elf-ld: cannot find crt0.o: No such file or directory` `cannot find -lgloss: No such file or directory`

### Steps To Reproduce
`nix-shell -p pkgs.spike`, or `nix-shell -p pkgsCross.riscv64-embedded.stdenv.cc` followed by `touch nothing.c && riscv64-none-elf-gcc nothing.c`

### Expected behavior
Spike builds, or linker errors are only related to the empty C file, not to default linking options failing.

### Notify maintainers

team gcc:

@Synthetica9 
@vcunat 
@Ericson2314 

### Metadata

```console
emil@fridge ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre546599.e44462d6021b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-23.05-23.05"`
 - channels(emil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trepetti** [comment]
Bisected here: https://github.com/NixOS/nixpkgs/commit/1e47c87fd239258c2e5e8259765053c24b5f50d9

Repro:
```
# builds
nix shell https://github.com/NixOS/nixpkgs/archive/1e47c87fd239258c2e5e8259765053c24b5f50d9.zip#pkgsCross.riscv32-embedded.riscv-pk
# fails to build due to this configure error
nix shell https://github.com/NixOS/nixpkgs/archive/4c5a455ca5c09a15edca42e83e8b65773da4394a.zip#pkgsCross.riscv32-embedded.riscv-pk
```
I think https://github.com/NixOS/nixpkgs/commit/1e47c87fd239258c2e5e8259765053c24b5f50d9 may not take into account the fact that standalone `none`/`eabi` toolchains you actually need those built with the compiler. Maybe we add an optional argument for such platforms? Let me know what you think @amjoseph-nixpkgs

**Comment by trepetti** [comment]
https://github.com/NixOS/nixpkgs/pull/266364 is the relevant PR. Maybe we can modify the environment of these platforms specifically. The principle behind the fix in the commit in question makes sense to me, but I am not sure how best to proceed.

**Comment by amjoseph-nixpkgs** [comment]
> riscv64-none-elf-gcc fails to link basic file. This breaks the build of spike. . You will see `riscv64-none-elf-ld: cannot find crt0.o: No such file or directory` `cannot find -lgloss: No such file or directory`

I think I know what this is.  Getting my builds caught up.

**Comment by amjoseph-nixpkgs** [comment]
Testing fix:

- https://github.com/NixOS/nixpkgs/pull/268026

**Comment by amjoseph-nixpkgs** [comment]
Yep, it fixes `spike`.
