### ISSUE TITLE
How to get list of all available packages?

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#26781]
I know we can run "nix-env -qaP"
But when I do this, it doesn't return all packages, because I can still put into my environment packages programs that are not listed in nix-env -qaP, such as discord and vim_configurable.

nix-env -qaP does not return discord or vim_configurable.
But I can add both to my configuration.nix and they get installed.

**Comment by tjikini** [comment]
`discord` are not listed as any other `unfree` package.
Dunno about vim_configurable.

**Comment by ob7** [comment]
I see vimNoX and vimHugeX pointing to vim_configurable but I don't see vim_configurable itself in the list.

**Comment by ob7** [comment]
Someone in IRC said theres packages within packages that don't get recursed over by a normal nix-env... users said they just check github to find exactly what they need.

**Comment by vcunat** [comment]
Yes, correct.  That's controlled by `recurseForDervations` (false by default); typically set by `recurseIntoAttrs`.
