### ISSUE TITLE
Package request: immich

### ISSUE THREAD

**Issue by matusf** [NixOS/nixpkgs#267869]
**Project description**
Self-hosted photo and video backup solution directly from your mobile phone. 

Self-hosted alternative for Google Photos.

**Metadata**

* homepage URL: https://immich.app/
* source URL: https://github.com/immich-app/immich
* license: mit
* platforms: unix, linux, darwin
* docs: https://immich.app/docs/overview/introduction

---
Could you please consider creating a NixOS module for immich service as well?

**Comment by kilianar** [comment]
#244803

**Comment by squalus** [comment]
#324127

**Comment by jlbribeiro** [comment]
I'm closing this issue since #324127 has finally been merged :tada:
