### ISSUE TITLE
SDDM crashes with multiple monitors

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#26791]
_Edited to reflect further debugging discussed below._

## Issue description

Although all NixOS tests for SDDM pass in a virtual machine, SDDM segfaults when run on a physical machine with multiple monitors and Plasma 5 is enabled. When Plasma is disabled (and consequently, the Breeze SDDM theme) SDDM runs normally. When only one display is present, SDDM also runs normally.

@peterhoeg This issue emerged after the upgrade to Plasma 5.10. Can you reproduce?

## Steps to reproduce

Connect multiple monitors and run `nixos-rebuild` with the following in `/etc/nixos/configuration.nix`:
```.nix
{
  services.xserver = {
    enable = true;
    displayManager.sddm.enable = true;
    desktopManager.plasma5.enable = true;
  };
}
```

## Technical details

* Nix version: 1.11.10
* Nixpkgs version: 0030c6610353b3706fe77d4cce06f1905a4aec43
* Sandboxing enabled: Yes

**Comment by peterhoeg** [comment]
I have no such problem on the latest unstable on 2 physical machines with SDDM and plasm 5.10.

The only slightly related issue which has existed for quite some time is that ```ksplashqml``` sometimes causes the nouveau driver to crash during login. But on the machine with intel graphics there are no issues and no problems with the nvidia driver either.

**Comment by ttuegel** [comment]
> The only slightly related issue which has existed for quite some time is that ksplashqml sometimes causes the nouveau driver to crash during login. But on the machine with intel graphics there are no issues and no problems with the nvidia driver either.

On my test machine, I'm using radeonsi drivers. So far, these have not been affected by the problems plaguing nouveau, but next I will have to test with some other driver.

**Comment by ttuegel** [comment]
SDDM also segfaults with the vesa driver, so I am reasonably confident this is not a driver-related issue. I have not been able to rule out a hardware problem.

**Comment by ttuegel** [comment]
I can also rule out any environmental impurity; the same configuration which segfaults on my physical machine runs correctly in a virtual machine.

**Comment by ttuegel** [comment]
The problem is caused by having multiple displays. If I unplug my second display, SDDM works correctly.

SDDM also works correctly if I upgrade from Qt 5.8 to Qt 5.9, so I will have to push that branch to master soon.

**Comment by peterhoeg** [comment]
My machine with the nvidia gfx card is running with dual monitors FWIW.

**Comment by ttuegel** [comment]
> My machine with the nvidia gfx card is running with dual monitors FWIW.

Well, since I had the problem with amdgpu and with vesa drivers, it may be a hardware issue. I have one screen connected by DVI, the other by HDMI. At any rate, it's fixed now! 😄
