### ISSUE TITLE
Update request: obs-studio 29.1.3 → 30.0

### ISSUE THREAD

**Issue by muni-corn** [NixOS/nixpkgs#267977]
- Package name: `obs-studio`
- Latest released version: **30.0**

- Current version on the unstable channel: **29.1.3**
- Current version on the stable/release channel: **29.0.2**

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jb55 @MP2E @V @miangraham 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/NixOS/nixpkgs/pull/275544
