### ISSUE TITLE
Perlless Activation - Tracking Issue

### ISSUE THREAD

**Issue by nikstur** [NixOS/nixpkgs#267982]
This is a tracking issue for the perlless activation effort started at OceanSprint.

See this [HedgeDoc](https://pad.lassul.us/nixos-perlless-activation) for a general overview of the strategy for this.

See the [Boot Security Meta Tracking Issue](https://github.com/NixOS/nixpkgs/issues/265640) for the larger effort of which this work is a part.

Associated PRs:

- https://github.com/NixOS/nixpkgs/pull/263203
- https://github.com/NixOS/nixpkgs/pull/263462
- https://github.com/NixOS/nixpkgs/pull/264879
- https://github.com/NixOS/nixpkgs/pull/267983
- https://github.com/NixOS/nixpkgs/pull/269983
- https://github.com/NixOS/nixpkgs/pull/271067
- https://github.com/NixOS/nixpkgs/pull/270727

Bug Fixes:

- https://github.com/NixOS/nixpkgs/pull/264082
- https://github.com/NixOS/nixpkgs/pull/264200
- https://github.com/NixOS/nixpkgs/pull/264608
- https://github.com/NixOS/nixpkgs/pull/264831
- https://github.com/NixOS/nixpkgs/pull/270000
- https://github.com/NixOS/nixpkgs/pull/270838

Please help me review open PRs, if you're passionate about this!

**Comment by asymmetric** [comment]
@nikstur I don't know if this is the place to ask, but could you provide more details about the specific ways in which interpreters are an attack surface? The linked [document](https://pad.lassul.us/nixos-perlless-activation#) only states that they are, without showing how.

I'm sure you've thought this through, but for the benefits of others who haven't (like me!), I think it would be good to document it.

**Comment by nikstur** [comment]
@asymmetric that's a good point. I'll expand on my motivation in that document.

**Comment by nikstur** [comment]
@asymmetric I added some more detail but most importantly a link to the Mitre attack technique [T1059](https://attack.mitre.org/techniques/T1059/) which also lists how this technique has been used in the wild. Hope this helps/is enough to explain *why* this work is interesting.

**Comment by RaitoBezarius** [comment]
I will add:

https://lwn.net/Articles/832959/
https://github.com/clipos-archive/clipos4_doc
https://www.youtube.com/watch?v=chNjCRtPKQY&t=1035s

**Comment by Jack-Works** [comment]
is there any plan to let grub perlless? (https://github.com/NixOS/nixpkgs/blob/nixos-26.05/nixos/modules/system/boot/loader/grub/install-grub.pl)

**Comment by r-vdp** [comment]
> is there any plan to let grub perlless? (https://github.com/NixOS/nixpkgs/blob/nixos-26.05/nixos/modules/system/boot/loader/grub/install-grub.pl)

I think the general recommendation is to not use grub.

**Comment by Jack-Works** [comment]
> > is there any plan to let grub perlless? ([`nixos-26.05`/nixos/modules/system/boot/loader/grub/install-grub.pl](https://github.com/NixOS/nixpkgs/blob/nixos-26.05/nixos/modules/system/boot/loader/grub/install-grub.pl?rgh-link-date=2026-07-12T09%3A52%3A16.000Z))
> 
> I think the general recommendation is to not use grub.

Thank you for the reply! I wonder if grub is out of date/fashion or something?
I want to have bootloader themes, but I also want to keep my system image small (this is why I want perlless).
I investigated some other bootloaders: `systemd-boot` cannot be themed; `limine` can be themed, but the way it shows the menu is a little strange to me (not left-aligned); `rEFInd` is very cool but looks like it is focused on an icon-based menu, which may not work well for NixOS because NixOS may have 20 generations in the bootloader menu.
Is any modern recommendation, thanks! (btw I also let AI rewrite the `install-grub.pl` to a native package, so at least I can remove Perl on my side and still install grub.)

**Comment by Atemu** [comment]
Please stay on topic.
