### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#26800]
## Issue description
Option for example - `networking.wireguard.interfaces.<name>.peers.*.allowedIPs`
Get error - `error: syntax error, unexpected '*', expecting ID or OR_KW or DOLLAR_CURLY or '"',`
`.*.` - what is it?

**Comment by ericsagnes** [comment]
`*` and `<name>` have special meaning in option names:

- `interface.<name>`: The option `interface` has type attributes of submodules, `<name>` being the attribute name.
- `peers.*`: The option `peers` has type list of submodules, `*` being the index in the list.

There is an example for the `networking.wireguard` option that show how it can be used:

```nix
  networking.wireguard = {
    wg0 = {
      ips = [ "192.168.20.4/24" ];
      privateKey = "yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=";
      peers = [
        { allowedIPs = [ "192.168.20.1/32" ];
          publicKey  = "xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=";
          endpoint   = "demo.wireguard.io:12913"; }
       ];
    };
  };
```
