### ISSUE TITLE
signal-desktop 6.38 fails to start (bus error)

### ISSUE THREAD

**Issue by dcarosone** [NixOS/nixpkgs#268050]
### Describe the bug
signal-desktop, updated in the latest unstable bf744fe, crashes on startup

### Steps To Reproduce

❯ signal-desktop
Bus error (core dumped)

### Expected behavior

large decrease in free memory, lots more electron, and some secure messages

### Additional context

previous revision works fine (and still runs with explicit store path)

### Notify maintainers

@teutat3s @yayayayaka (from commit f5619ed4 that bumped the version)

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231114.bf744fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/0y446mjvwzrhv723jh0lpkaz9gw8jzbq-source`

**Comment by chewblacka** [comment]
I can't seem to replicate this. 6.38 is working fine for me.

**Comment by MikaelFangel** [comment]
Just tried to rebuild with the latest from master, and it builds fine and runs fine. It would possibly help if you could share the error message you get.

**Comment by dcarosone** [comment]
The error, as above, is a bus error.

This threw me off track, and I didn't notice the actual cause, as reported by zfs:

```text
errors: Permanent errors have been detected in the following files:

        /nix/store/sbwjsgb6wd6lraphwsklq63d611jnm9w-signal-desktop-6.38.0/lib/Signal/signal-desktop
```

So, local problem, sorry for the noise.
