### ISSUE TITLE
Xorg Crash: Intermittent Crashes during GUI Session

### ISSUE THREAD

**Issue by sukhmancs** [NixOS/nixpkgs#268099]
## **Issue Summary:**
Xorg crashes intermittently, impacting the overall system stability.

## **Steps to Reproduce:**
1. Open multiple applications (eg: Firefox, Joplin, Keepassxc, Calibre) and use them normally.
2. Sometimes, the system crashes and logs out unexpectedly.

## **Expected Behavior:**
Xorg should run stably without crashes.

## **Actual Behavior:**
Xorg crashes with the following symptoms:
   - The screen freezes momentarily.
   - The system logs out, and I'm returned to the login screen.
   - No specific error messages are displayed on the screen.

## **Logs and Output:**
- Coredump information: http://ix.io/4LKl 

## **Additional Context:**
- This issue started occurring after I disabled samba, avahi, and docker. 

## **Attempts to Solve:**
- [x] Checked system logs for error messages.
- [x] Verified graphics drivers are up to date.

## **Related Issues:**
- None

## **Mentioned Maintainers:**
@rnhmjoj 

## **Note:**
I have followed the guidelines provided in the NixOS documentation for troubleshooting Xorg issues, but the problem persists. Please advise on further steps or information needed to resolve this issue.

## **System Information:**
- NixOS version: 23.05
- Xorg version: 1.21.1.9
- Graphics hardware: Intel Haswell-ULT

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/fyvbj5mvrvdnvhbx6hc977wsgl33pk3i-nix-info
copying path '/nix/store/fyvbj5mvrvdnvhbx6hc977wsgl33pk3i-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.05 (Stoat), 23.05.20231116.9fb1225`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rnhmjoj** [comment]
I'm not sure why you pinged me... anyway, it looks like there's an allocation failing inside this `dri2_dup_image` function. This is part of crocus, which seems to be the DRI driver for new intel integrated GPUs.

I doubt anyone here will be able to fix whatever this is. You will probably have a better chance if you report this in the mesa [issue tracker](https://gitlab.freedesktop.org/mesa/mesa/-/issues).

**Comment by Atemu** [comment]
This doesn't look like our bug, take it upstream. If they tell you this is a distribution issue (and ideally why), come back with that info.
