### ISSUE TITLE
Feature requiement: `pkg-config` support of `hdf5` series packages needed

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#268125]
### Describe the bug
Actually not a bug, but a missing feature:
The `hdf5` series packages, including `hdf5` and `hdf5-cpp` miss `pkg-config` support.

### Steps To Reproduce
1. `nix-shell -p hdf5 -p pkg-config
2. `pkg-config --cflgas hdf5`
3. Error message is given "Package hdf5 was not found in the pkg-config search path..."

### Expected behavior
Include and lib pathes should be returned by `pkg-config` command

### Notify maintainers

@markuskowa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.05 (Stoat), 23.05.4808.da4024d0ead5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by markuskowa** [comment]
The pkg-config files are in the dev output:
```
$ nix-shell -p hdf5 pkg-config hdf5.dev
$ pkg-config --cflags hdf5
-I/nix/store/2fvcrdqbqwzwaj1lcn30iv0nq32qvxsl-hdf5-1.14.2-dev/include
```

**Comment by markuskowa** [comment]
When you put `hdf5` in your `buildInputs` you will automatically have the `dev`  output of `hdf5` in your environment.

**Comment by astrojhgu** [comment]
> pkg-config --cflags hdf5

Thanks!
I found that on my machine with 23.05, it's not available. But in the unstable channel, it is available.
