### ISSUE TITLE
Update request: rpcs3 0.0.28-15409-fd6829f75 → 0.0.29-15724-ab8a12e21

### ISSUE THREAD

**Issue by lasers** [NixOS/nixpkgs#268112]
- Package name: rpcs3
- Latest released version: 0.0.29-15724-ab8a12e21

- Current version on the unstable channel: 0.0.28-15409-fd6829f75
- Current version on the stable/release channel: 0.0.27-14840-842edbcbe

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@abbradar @neonfuz @ilian @zane

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by lasers** [comment]
Edited original post to include missing maintainers. Also, pinging @abbradar @neonfuz @ilian @zane.

**Comment by vs49688** [comment]
Cool name ;)

This should've been updated automatically, but they switched to Qt6: https://r.ryantm.com/log/rpcs3/2023-11-13.log

I'll handle this shortly.
