### ISSUE TITLE
nixos: regression bcachefs cannot be used with /dev/disk/by-* anymore 

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nixpkgs#268123]
### Describe the bug
Using `fileSystems."/".device = "/dev/disk/by-*/*"` failes with `ENOKEY` while mounting the root filesystem if the fs is encrypted. 

Introduced by https://github.com/NixOS/nixpkgs/pull/256638
### Steps To Reproduce
1. format the root system with an encrypted bcachefs
2. set `fileSystems."/".device = "/dev/disk/by-partuuid/<partuuid>"
3. rebuild system and reboot

### Expected behavior
Initramfs should prompt for encryption key

### Additional context
initramfs does not ask for encryption key, but failed with `ENOKEY`

### Notify maintainers
@YellowOnion

### Metadata
flakes system does not apply.
Nixpkgs revision that includes #256638
x86_64-linux

**Comment by onny** [comment]
I'm also affected by this on 23.11-beta https://github.com/NixOS/nixpkgs/issues/269218

**Comment by Madouura** [comment]
See https://github.com/NixOS/nixpkgs/pull/267640#issuecomment-1817487857
You'll need to edit your ``hardware-configuration.nix`` and replace those entries with ``UUID=(`bcachefs show-super /dev/whatever`, it will be the external UUID at the top.)``
cc @YellowOnion

**Comment by YellowOnion** [comment]
@Madouura we should cover common use cases should, IMHO symlinks should just work see the PR attached.

**Comment by chayleaf** [comment]
On 23.11 branch, multi-device `mount -t bcachefs UUID=<uuid> /mountpoint` fails for me with `ERROR - bcachefs_rust::cmd_mount: Fatal error: Invalid argument`

dmesg shows `bch2_fs_open() bch_fs_open err opening /dev/sda: insufficient_devices_to_start`

I haven't yet checked whether it's any different in initrd

**Comment by YellowOnion** [comment]
@chayleaf "insufficient_devices_to_start" seems to be a tools and/or util-linux issue, it means tools can't find enough devices using the UUID...will have to look in to this more.

**Comment by XenGi** [comment]
Even without any encryption, mounting a multi device bcachefs seems to be not possible. I can mount it with `mount -t bcachefs /dev/sdb:/dev/sdb /data` but not with a UUID. Using `UUID=foo` and `/dev/disk/by-uuid/foo` leads to the same error: `ch2_fs_open() bch_fs_open err opening /dev/sdb: insufficient_devices_to_start`

I also tried using `fileSystems."/data".devices = "/dev/sdb:/dev/sdb";` but that also didn't work. I'm still experimenting but haven't found any solution so far.

**Comment by Kloenk** [comment]
Yes this IIRC only fixes the non systemd-initrd initrd stage. Have the same problem with a systemd stage 1 system
