### ISSUE TITLE
geoserver: errors during startup

### ISSUE THREAD

**Issue by imincik** [NixOS/nixpkgs#268157]
### Describe the bug
Multiple error messages are printed when geoserver is started using `geoserver-startup`.

### Steps To Reproduce
1. Create shell containing geoserver package 
```
nix shell nixpkgs#geoserver
```

2. Start geoserver using provided script
```
geoserver-startup

20:32:00 ERROR  [geoserver.logging] - Could not reconfigure LOG4J loggers
java.lang.IllegalArgumentException: Unable to create directory /nix/store/k48mvamdl41r60g4pr93nkm7r1najrr6-geoserver-2.23.0/share/geoserver/webapps/geoserver/data

20:32:01 ERROR  [context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcXmlConfigResourceProvider' defined in URL [jar:file:/nix/store/k48mvamdl41r60g4pr93nkm7r1najrr6-geoserver-2.23.0/share/geoserver/webapps/geoserver/WEB-INF/lib/gs-gwc-2.23.0.jar!/geowebcache-core-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.gwc.config.GeoserverXMLResourceProvider]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Unable to create /nix/store/k48mvamdl41r60g4pr93nkm7r1najrr6-geoserver-2.23.0/share/geoserver/webapps/geoserver/data
```

### Expected behavior
Script should run without errors.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by imincik** [comment]
The problem is that startup script must be executed with `GEOSERVER_DATA_DIR` variable pointing to existing directory. For example `GEOSERVER_DATA_DIR=/tmp/geodata geoserver-startup`.

**Comment by sikmir** [comment]
> The problem is that startup script must be executed with `GEOSERVER_DATA_DIR` variable pointing to existing directory. For example `GEOSERVER_DATA_DIR=/tmp/geodata geoserver-startup`.

Yes, `GEOSERVER_DATA_DIR` should be set before starting. Maybe some default like `/tmp/geodata` is a good one, but only if not provided by user.

**Comment by sikmir** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/268187
