### ISSUE TITLE
Update request: v2raya 2.2.4 → 2.2.4.3

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#268262]
- Package name: v2raya
- Latest released version: 2.2.4.3

- Current version on the unstable channel: 2.2.4
- Current version on the stable/release channel: 2.0.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Eliot00 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by cu1ch3n** [comment]
P
