### ISSUE TITLE
clamtk: crashes due to missing icon files

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#268203]
### Describe the bug
When executing `clamtk` with `nix run`, it complains that `Icon 'preferences-system' not present in theme breeze`.

Maybe the package needs to be wrapped with some environment variables set or patched against hard-coding or something.

### Steps To Reproduce

```console
❯ nix run github:NixOS/nixpkgs/nixos-unstable#clamtk
Gtk-Message: 08:37:15.170: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 08:37:15.170: Failed to load module "colorreload-gtk-module"
Unable to read preferences! No such file or directory
Icon 'preferences-system' not present in theme breeze at /nix/store/wby9hkm3zllmlkqsxvn8fxszflx05wsa-perl5.38.0-Glib-Object-Introspection-0.049/lib/perl5/site_perl/5.38.0/x86_64-linux-thread-multi/Glib/Object/Introspection.pm line 67.
```

### Expected behavior
ClamTk runs with `nix run`.

### Screenshots
![Screenshot 2023-11-20 at 05-37-44 NixOS_nixpkgs issue #268203 clamtk crashes failing to find icon files 2023-11-19T21 26 01 00 00](https://github.com/NixOS/nixpkgs/assets/44064051/910735ee-62d2-417a-9ff7-b64b5724f4c3)

[![asciicast](https://asciinema.org/a/KU9eI2f2wQbBmnoPCNHbKHKxT.svg)](https://asciinema.org/a/KU9eI2f2wQbBmnoPCNHbKHKxT)

### Notify maintainers
@jgarcia

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by chewblacka** [comment]
I can't seem to reproduce this. Have run both on nixos and nix on another linux. Can you give me some more info? Does the program work and run correctly? Is it missing any icons (screenshot?). What desktop are you running? Many thanks.

**Comment by ShamrockLee** [comment]
It exists with exit status 2 right after the command `clamtk` being invoked inside the terminal emulator and the error message printed out. No window is shown.

The desktop environment I use is LxQt, which inherently doesn't come with the KDE breeze icons.

**Comment by chewblacka** [comment]
I switched my DE over to LxQt and everything worked for me.
Basically the error is between the program logic (it shouldn't crash if it can't find icon files) and your DE set-up (it should provide the correct icon files). It's not a packaging error as far as I can tell. So you could try either: 1. messing around with your DE settings, 2. trying another DE and / or 3. filing a bug report upstream to clamtk. 

![Screenshot_20231120_081054](https://github.com/NixOS/nixpkgs/assets/18430320/281e2d74-19d3-4c69-a84f-c1c464c12c2c)

**Comment by chewblacka** [comment]
p.s. I wonder if this could just be fixed by installing some icons?

You could try installing `breeze-icons` and / or `gnome-icon-theme` on your system and see if that helps.
