### ISSUE TITLE
Plasma display manager in configuration.nix crashes some applications

### ISSUE THREAD

**Issue by P-E-Meunier** [NixOS/nixpkgs#26837]
## Issue description

When I enable `plasma5` in my `configuration.nix`, cantata fails to start (segfaults after a few milliseconds), with an error related to the qsqlite driver.

### Steps to reproduce
Add the following line to `/etc/nixos/configuration.nix`:

``` nix
services.xserver.desktopManager.plasma5.enable = true;
```

Install cantata, and try to start it:

```bash
$ nix-env -iA nixos.cantata
$ cantata
```

## Technical details

* System:
NixOS: 17.03.1395.9b948ea439 (Gorilla)

* Nix version:
nix-env (Nix) 1.11.11

* Nixpkgs version:
17.03.1395.9b948ea439

* Sandboxing enabled:
false

**Comment by peterhoeg** [comment]
I have noticed this on recent unstable as well but it's most of the KDE applications that are crashing if I try ```nixos-rebuild test``` inside a running KDE session. I'll try to find the last good revision.

@ttuegel, any thoughts?

**Comment by peterhoeg** [comment]
I'm not seeing this anymore, so it's probably OK to close this.
