### ISSUE TITLE
Package request: Dangerzone

### ISSUE THREAD

**Issue by DarkOnion0** [NixOS/nixpkgs#268336]
**Project description**

Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs 

**Metadata**

* homepage URL: https://dangerzone.rocks/
* source URL: https://github.com/freedomofpress/dangerzone
* license: MIT
* platforms: linux, darwin, windows

**Comment by eclairevoyant** [comment]
duplicate of #189761
