### ISSUE TITLE
$PATH

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#26847]
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by FRidh** [comment]
Accidentally opened this one?
