### ISSUE TITLE
Nixpkgs cannot download xhost-1.0.7.tar.bz2 from any mirror

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#26841]
## Issue description
Trying to install xhost, but nixos-rebuild (nix-env too) says

> error: cannot download xhost-1.0.7.tar.bz2 from any mirror

but package is available on any mirror.

### Steps to reproduce
1. type `nix-env -iA nixos.xorg.xhost`
2. get the error message

It seems because of wrong sha256.

```
$ sha256sum xhost-1.0.7.tar.bz2
93e619ee15471f576cfb30c663e18f5bc70aca577a63d2c2c03f006a7837c29a  xhost-1.0.7.tar.bz2

```
## Technical details

* System: 17.09pre109180.0d4431cfe9 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: 17.09pre109180.0d4431cfe9
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by dtzWill** [comment]
Hmm, I'm able to re-fetch the source on both master and release-17.03.

Maybe transient problem (network or hosting)?

Can you confirm this is still not working for you?

I get the same sha256sum, for what it's worth.
(note the "sha256" field isn't the same as what sha256sum prints, I forget the details but it's Nix-specific)

**Comment by frigatefreedom** [comment]
Now it installs correctly.
