### ISSUE TITLE
nox is broken

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#26843]
## Issue description

Nox is broken

### Steps to reproduce

Install nox
run it:
```
nox virtualbox
Traceback (most recent call last):
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/bin/.nox-wrapped", line 8, in <module>
    from nox.search import main
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/lib/python3.6/site-packages/nox/search.py", line 8, in <module>
    from .cache import region
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/lib/python3.6/site-packages/nox/cache.py", line 1, in <module>
    from dogpile.cache import make_region
ModuleNotFoundError: No module named 'dogpile.cache'
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

nixos-version
17.09pre109180.0d4431cfe9 (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env --version
nix-env (Nix) 1.11.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09pre109180.0d4431cfe9"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = false

**Comment by FRidh** [comment]
The `nixpkgs-unstable` channel is currently at afd2bdbad2 and the issue doesn't occur there. I recall I have seen it happen before, but somehow it seems to be resolved again.

**Comment by sjau** [comment]
I'm using unstable and it's been like this for a week or so.

**Comment by FRidh** [comment]
Have you checked the revision I referred to?

**Comment by sjau** [comment]
I also use unstable so I should have the same but I don't. It gives me that error.

**Comment by FRidh** [comment]
> so I *should* have the same

Just check it, its `/nix/store/m40bs31r7f2bzkzvz2v04h3jzxavzgk2-nox-0.0.5`.

Otherwise, it seems to be an impurity. Do you have a user site-packages folder where you installed items in? `~/.local/lib/pythonX.X/`

https://github.com/NixOS/nixpkgs/issues/26846

**Comment by sjau** [comment]
I don't user user packages... single user system... everything global from configuration nix.

```
root@subi:~# cat /etc/nixos/useUnstable.sh                         
#!/usr/bin/env bash                                                

nix-channel --add https://nixos.org/channels/nixos-unstable nixos  
#nixos-rebuild switch --upgrade                                    

root@subi:~# /etc/nixos/useUnstable.sh                             
root@subi:~# nixos-rebuild switch --upgrade                        
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre109180.0d4431cfe9/nixexprs.tar.xz’...                                                                                                                                     
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre109180.0d4431cfe9/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/s]                                                                                                                                     
unpacking channels...                                              
building Nix...                                                    
building the system configuration...                               
updating GRUB 2 menu...                                            
activating the configuration...                                    
setting up /etc...                                                 
setting up tmpfiles                                                
root@subi:~# nox virtualbox                                        
Traceback (most recent call last):                                 
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/bin/.nox-wrapped", line 8, in <module>                                   
    from nox.search import main                                    
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/lib/python3.6/site-packages/nox/search.py", line 8, in <module>          
    from .cache import region                                      
  File "/nix/store/prfzq2z1nk95jklmzaabdbnnsyqgwk8k-nox-0.0.5/lib/python3.6/site-packages/nox/cache.py", line 1, in <module>           
    from dogpile.cache import make_region                          
ModuleNotFoundError: No module named 'dogpile.cache'
```

**Comment by Ma27** [comment]
I'm at version `17.09pre109180.0d4431cfe9 (Hummingbird)` of `nixos-unstable` and can confirm this issue.
As I don't use the `nixpkgs-unstable` channel, I won't be able to test it (but I might be able to reserve some time for that next week...)

**Comment by FRidh** [comment]
The issue indeed occurs on current `nixos-unstable`.

**Comment by calvertvl** [comment]
I had fixed this by adding the following at the beginning of nox/cache.py:
```
import setuptools
```

For some reason this fixed it; I didn't have the patience to figure out why.

**Comment by FRidh** [comment]
This issue is not occurring anymore with `nixos-unstable` (05aa2a58db2de248cc2ef516b21fa319ca72613e) and `nixpkgs-unstable` (74f55017d26bb0931184bbcb54630000ce5ee107).

**Comment by Ma27** [comment]
yes, it works on my machine as well... :+1:
