### ISSUE TITLE
Package request: gscan2pdf

### ISSUE THREAD

**Issue by jamesbroadhead** [NixOS/nixpkgs#26840]
gscan2pdf is probably the best scanning UI for Linux. 
https://sourceforge.net/projects/gscan2pdf/

![2007-08-07-gscan2pdf](https://user-images.githubusercontent.com/1382141/27516397-d55a7594-59b0-11e7-861f-0d1d076353f1.png)

It's written in perl/gtk, and has the following dependencies, some of which are already in perlPackages (those which are not are marked) 

## Perl Dependencies
- Config::General 2.4 
- Date::Calc 0 
- Filesys::Df 0    **not in nixpkgs**
- Glib 1.21  
- Goo::Canvas 0 
- Gtk2 1.09 
- Gtk2::Ex::Simple::List 0  **not in nixpkgs** 
- Gtk2::ImageView 0 
- Image::Magick 0   **not in nixpkgs** 
- List::MoreUtils 0 
- Locale::gettext 1.05 
- Log::Log4perl 0 
- PDF::API2 0 
- Readonly 0 
- Sane 0.05  **not in nixpkgs** 
- Set::IntSpan 1.1  
- Sub::Override 0 
- Try::Tiny 0

## Other Dependencies 

- gtkimageview
- imagemagick built with png, tiff, perl support **in nixpkgs, config unknown** 
- saneBackends
- libtiff

## Optional Depdencies 
(still important for full functionality)

- DjVu file support
-- libdjvu built with tiff support **probably in nixpkgs, not sure which package matches** 
-- imagemagick built with djvu support  **in nixpkgs, config unknown** 
- "Optical Character Recognition" (one of these)
-- tesseract built with osd & tiff support **in nixpkgs, config unknown**
-- gocr
-- ocropus,
-- cuneiform
- "scan post-processing" 
-- unpaper
- "automatic document feeder support" 
-- saneFrontends
- "sending PDFs as email attachments" 
-- xdg_utils

Here is the [gentoo ebuild](https://gpo.zugaina.org/AJAX/Ebuild/30684900/View) for context.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding this package here.
