### ISSUE TITLE
[Feature Request] tmux: Add ability to add own configureFlags

### ISSUE THREAD

**Issue by ca5ua1** [NixOS/nixpkgs#268472]
### Describe the bug
It is not a bug, more like feature request. 
As stated at https://www.arewesixelyet.com/#tmux tmux actually supports sixel if enabled at compile. So I would like to be able to add own flags or option for tmux `./configure` with this flag.

Why I would like sixel? To be able to ditch file manager GUI and use TUI like yazi and infrequent previewing pictures in terminal

### Expected behavior
`programs.tmux.configureFlags = [ "--enable-sixel" ]`

Or

`programs.tmux.enableSixel = true;`

### Notify maintainers

@tobias-hammerschmidt 
@fpletz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by 7c6f434c** [comment]
I think upstream tmux doesn't have a sixel-including versioned release yet, though (3.3a is older than the branch merge).

Separately, maybe — _if_ once upstream `tmux` makes a release we don't enable sixel by default — the module should only allowing overriding the package (overriding configure flags for a package directly is straightforward enough). 

Actually with package override you'll have an option to override both `src` and `configureFlags`.

This gives a sixel-enabled `tmux`:
```
tmux.overrideAttrs (x: {
  configureFlags = (x.configureFlags or []) ++ 
    ["--enable-sixel"]; 
  src = fetchFromGitHub {
    owner = "tmux"; 
    repo="tmux"; 
    rev = "bdf8e614af34ba1eaa8243d3a818c8546cb21812"; 
    hash = "sha256-ZMlpSOmZTykJPR/eqeJ1wr1sCvgj6UwfAXdpavy4hvQ="; 
  }; 
  patches = []; 
})
```

**Comment by Artturin** [comment]
Adding a `.package` option is enough

**Comment by fpletz** [comment]
IMHO we can close this since tmux can be overridden as @7c6f434c described via an overlay and the main reason for the override, sixel support, is now enabled.
