### ISSUE TITLE
Build failure: beets

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#268516]
### Steps To Reproduce

1. build `beets`

Buiid attempted on `master`. Looks like a sphinx issue?

### Build log

https://gist.github.com/lunik1/f99cb57de250fab7a6a21a4f3b7d5bfa

### Notify maintainers

@aszlig @doronbehar @lovesegfault @pjones  

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.05 (Stoat), 23.05.20231118.decdf66`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jackwilsdon** [comment]
This was fixed on beets master in beetbox/beets@2106f47 (not available in any tagged releases yet). I've applied this as a patch and it fixes the issue, although I'm now seeing build issues with `test_aura.py` which I'm looking into.
