### ISSUE TITLE
[Tracking Issue] systemd v255

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#268521]
This is a tracking issue to bring systemd v255 in NixOS.

### Issues

- [x] Prefix workarounds: https://gist.github.com/ElvishJerricco/60f223e34cdd5916250029217777def6 all over nixpkgs.
  This was fixed upstream by https://github.com/systemd/systemd/pull/30115  

### Discovered bugs

None so far.

### Features to deal with

- [ ] `soft-reboot` has to be disabled until it's proven to work well

**Comment by cab404** [comment]
Tried soft-reboot. It mostly works, however it messes suid up. Some blacklisting required :)

**Comment by cab404** [comment]
Here's a patch I've applied to test it: 
```
diff --git a/nixos/modules/system/boot/systemd.nix b/nixos/modules/system/boot/systemd.nix
index 87333999313e..cc60f99bf1e8 100644
--- a/nixos/modules/system/boot/systemd.nix
+++ b/nixos/modules/system/boot/systemd.nix
@@ -115,6 +115,8 @@ let
       # Reboot stuff.
       "reboot.target"
       "systemd-reboot.service"
+      "soft-reboot.target"
+      "systemd-soft-reboot.service"
       "poweroff.target"
       "systemd-poweroff.service"
       "halt.target"
```

**Comment by RaitoBezarius** [comment]
cc @ElvishJerricco @nikstur if we want to support soft reboot.

**Comment by ElvishJerricco** [comment]
I think it would be nice, but it may or may not need some special support from nixos; I'm not sure what all is involved here

**Comment by nikstur** [comment]
Yes I agree. I'd go so far that I'd even want to replace stc with a soft-reboot but I think many people wouldn't like that.

**Comment by ElvishJerricco** [comment]
well, a soft-reboot is significantly more severe than a stc. It actually stops everything, doesn't it?

**Comment by cab404** [comment]
> well, a soft-reboot is significantly more severe than a stc. It actually stops everything, doesn't it?

at least it tries to. and you can (and we will probably have to) do exceptions.

**Comment by arianvp** [comment]
We have 255 already. Can this be closed?

Soft-reboot doesn't seem to work though:

```
[arian@utm:~]$ sudo systemctl soft-reboot
[sudo] password for arian: 

Broadcast message from root@utm on pts/1 (Tue 2024-03-12 14:11:23 CET):

The system will soft-reboot now!

Call to Reboot failed: Access denied


```

**Comment by nikstur** [comment]
I think it can be closed. Soft reboot is an altogether different issue.
