### ISSUE TITLE
Suspected build failure: git-machete

### ISSUE THREAD

**Issue by PawelLipski** [NixOS/nixpkgs#268581]
AFAICS the package https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-machete/default.nix has been most recently updated 3 months ago... there's been a couple version since then :/ The updates used to happen via @r-ryantm bot... but I can't see anything in https://r.ryantm.com/log/updatescript/git-machete/ from after July 27th, 2023 ☹️ do I have onboard the package manually for further automatic updates? or has there been some failure which I can't see in the logs? 🤔 

CC @blitz

**Comment by Atemu** [comment]
The logs are located [here](https://r.ryantm.com/log/git-machete/) and you're right, it doesn't build OOTB with the new version.

Please open an update request and/or do the update yourself and investigate the build failure.
