### ISSUE TITLE
krename does not build

### ISSUE THREAD

**Issue by jarry9** [NixOS/nixpkgs#26860]
## Issue description
I am using krename with nix. But when I'm upgrading all apps on nix-store it gives me the below error. I have two questions here:

1- what can I try to solve this error?

2- nix-env -u '*' command should upgrade all my nix apps. But it stops because of krename fail. But it can update the other apps. I mean, with which command it will skip the krename?

Thanks in advanced

-- Could NOT find KF5Crash: found neither KF5CrashConfig.cmake nor kf5crash-config.cmake 
-- Found Gettext: /nix/store/ysflspvb6b6yd25h6qhvkizwyc6mgabm-gettext-0.19.8/bin/msgmerge (found version "0.19.8") 
-- Found PythonInterp: /nix/store/frnm6ahmm6kzlh7sqrn09hdkkfyy9q39-python-2.7.13/bin/python (found version "2.7.13") 
-- Found KF5I18n: /nix/store/nz8nn444rrdhw09hmszr5hmhh0hhmyd6-ki18n-5.34.0-dev/lib/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.34.0") 
-- Found KF5IconThemes: /nix/store/l74mq98x0jki2sxpzjg9vhx76pnpiqdg-kiconthemes-5.34.0-dev/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.34.0") 
-- Found KF5ItemViews: /nix/store/f9adafvkvdj9iljyshzwqx6jl72n5s7c-kitemviews-5.34.0-dev/lib/cmake/KF5ItemViews/KF5ItemViewsConfig.cmake (found version "5.34.0") 
-- Found KF5JobWidgets: /nix/store/i3xkqjlx53b1pfl3lw8cr26lz8wm5zkd-kjobwidgets-5.34.0-dev/lib/cmake/KF5JobWidgets/KF5JobWidgetsConfig.cmake (found version "5.34.0") 
-- Found KF5JS: /nix/store/dlpdij1fg4h6rxivvlsiczi7p0fnddab-kjs-5.34.0-dev/lib/cmake/KF5JS/KF5JSConfig.cmake (found version "5.34.0") 
-- Found KF5KIO: /nix/store/1jmn4zffxnqglhvgh948d63g25shc181-kio-5.34.0-dev/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.34.0") 
-- Found KF5Service: /nix/store/5syj2mgmcpf2c43i7nzn934ngpi084cv-kservice-5.34.0-dev/lib/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.34.0") 
-- Found KF5WidgetsAddons: /nix/store/6bzjjjl1v9aj2qg2z0pid2v1a46i8j14-kwidgetsaddons-5.34.0-dev/lib/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (found version "5.34.0") 
-- Found KF5XmlGui: /nix/store/6alhyv4a4ansmds9c919cq2090hpjx55-kxmlgui-5.34.0-dev/lib/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.34.0") 
CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Crash) (found version "5.34.0")
Call Stack (most recent call first):
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/yk2v9qp15989i9pnb7bmik9y3fbly8kk-extra-cmake-modules-5.34.0/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/nix-build-krename-20170610.drv-0/krename-18000edfec52de0b417d575e14eb078b4bd7b2f3-src/build/CMakeFiles/CMakeOutput.log".
builder for ‘/nix/store/3x2dbirrdm9cjjddi8z2pq5kax4fyqb2-krename-20170610.drv’ failed with exit code 1
error: build of ‘/nix/store/3x2dbirrdm9cjjddi8z2pq5kax4fyqb2-krename-20170610.drv’ failed

## Technical details

* System: Ubuntu 16.04
* Nix version: nix-env (Nix) 1.11.9

**Comment by FRidh** [comment]
I've fixed the build in https://github.com/NixOS/nixpkgs/commit/a5a98f98a05ed73d45e52b9409b8a494d9ce072a. Within a couple of days there should be a channel update that includes this fix. Otherwise, you can build from master at or from this revision.
