### ISSUE TITLE
Package request: xfce4-docklike-plugin

### ISSUE THREAD

**Issue by martind2000** [NixOS/nixpkgs#268605]
**Project description**

A modern, minimalist taskbar for Xfce.

Docklike Taskbar behaves similarly to many other desktop environments and operating systems. Wherein all application windows are grouped together as an icon and can be pinned to act as a launcher when the application is not running. Commonly referred to as a dock.

**Metadata**

* homepage URL: https://docs.xfce.org/panel-plugins/xfce4-docklike-plugin/start
* source URL: https://gitlab.xfce.org/panel-plugins/xfce4-docklike-plugin/
* license: gpl3
* platforms: linux

**Comment by JoshuaFern** [comment]
Hi @martind2000, I submitted xfce4-docklike-plugin for review. Feel free to provide feedback.
