### ISSUE TITLE
command-t fails to build

### ISSUE THREAD

**Issue by zetok** [NixOS/nixpkgs#26862]
## Issue description

```
unpacking source archive /nix/store/pqcpp59h34adnk3j4sfw2y5a5c7hxp8r-command-t-3f0d21a
source root is command-t-3f0d21a
patching sources
configuring
building
/tmp/nix-build-vimplugin-command-t-2017-06-08.drv-0/command-t-3f0d21a/ruby/command-t /tmp/nix-build-vimplugin-command-t-2017-06-08.drv-0/command-t-3f0d21a
ruby: No such file or directory -- extconf.rb (LoadError)
builder for ‘/nix/store/19cfg329b42y88pjxw9mvqhacj0inxhm-vimplugin-command-t-2017-06-08.drv’ failed with exit code 1
```

### Steps to reproduce
`nixos-rebuild switch --upgrade --fallback`

## Technical details

* System: 17.09pre108553.0011f9065a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: "17.09pre109180.0d4431cfe9"
* Sandboxing enabled: build-use-sandbox = true

**Comment by dtzWill** [comment]
I can confirm this on unstable, seems to be fixed on master.

Looks like [this commit](3477f560279e362477f2620b6f9b825e919629d5) is what fixed it.

**Comment by lheckemann** [comment]
3477f560279e362477f2620b6f9b825e919629d5 actual link to the commit

**Comment by zetok** [comment]
Upgrading now works.
