### ISSUE TITLE
uwsgi could use a minimum working example in the docs

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#26861]
## Issue description
I'm currently trying to set up a nixos instance, which serves the `moinmoin` example provided in [`modules/services/web-servers/uwsgi.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/uwsgi.nix#L91).
I couldn't make it work however, which is why I would appreciate a minimal working example included in the nixos docs on how to properly use uwsgi with python.

## Technical details

* System: 17.03.1395.9b948ea439 (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: "17.03.1395.9b948ea439"
* Sandboxing enabled: build-use-sandbox = false

**Comment by knedlsepp** [comment]
@abbradar As you are the author of original `uwsgi.nix` file, I was hoping that you could maybe share a minimal working `configuration.nix` which uses uwsgi to serve some python.

**Comment by florianjacob** [comment]
I'm working on a fully-functional `moinmoin` service to add to nixpkgs, which should probably help, but is far from a minimum example as `moinmoin` turns out to be a more complex case than your regular django / flask app due to the various config and data files.

**Comment by mtn** [comment]
I'm not sure this counts as a minimal example, but [this test](https://github.com/NixOS/nixpkgs/blob/a76eae4220b5f6c16a5942fe545ed37fa6bf1644/nixos/tests/uwsgi.nix) now exists. Maybe this can be closed @knedlsepp?

**Comment by knedlsepp** [comment]
Agreed.
