### ISSUE TITLE
ibus libpinyin not translating keypresses

### ISSUE THREAD

**Issue by quickdudley** [NixOS/nixpkgs#268611]
### Describe the bug
I can enable the "Chinese - intelligent pinyin" input method in the ibus preferences and select it in the ibus input method selector but when I try to type something in Chinese the character selection box doesn't appear and the text is not modified by the input method.

### Steps To Reproduce
1. Select a text input in a program that supports ibus, such as a form input in Firefox
2. Select the "Chinese - intelligent pinyin" input method
3. Type something

### Expected behavior
The initially typed characters should appear highlighted, and a character selection box containing Chinese characters should appear.

### Additional context
Using Cinnamon desktop environment

### Notify maintainers

@linsui @ericsagnes 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
jeremy@shelley:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.05 (Stoat), 23.05.4873.8e5e424b1c05`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/home/jeremy/.nix-defexpr/channels/nixpkgs`
```

**Comment by linsui** [comment]
I can't reproducible this. Can you share some screeshot or even a screen record?

**Comment by quickdudley** [comment]
I found that ibus libpinyin works as expected on KDE on X11 but I have this issue on KDE Wayland, Gnome, Cinnamon, and XFCE. I will check how to do a screen recording tomorrow.

**Comment by linsui** [comment]
I tested it on GNOME wayland. Not sure why it doesn't work for you.

**Comment by quickdudley** [comment]
I can no longer replicate it.

**Comment by quickdudley** [comment]
Closing
