### ISSUE TITLE
Build failure: poetry with python 3.8 `sphinx-7.2.6 not supported for interpreter python3.8`

### ISSUE THREAD

**Issue by Thlr** [NixOS/nixpkgs#268731]
### Steps To Reproduce

Use `nix develop` with the following nix flake :
```nix
{
  description = "";

  inputs = {
    nixpkgs = { url = "github:NixOS/nixpkgs/nixos-unstable"; };
    flake-utils = { url = "github:numtide/flake-utils"; };
  };

  outputs =
    { self
    , nixpkgs
    , flake-utils
    ,
    }:
    flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = import nixpkgs {
        inherit system;
      };

      python = pkgs.python38;
      poetry = pkgs.poetry.override {python3 = python;};

    in
    {
      formatter = pkgs.nixpkgs-fmt;
      devShells.default = pkgs.mkShell {
        buildInputs = [
          python
          poetry
       ];
      };
    });
}
```

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/z7y28qzhk7driiwcw78k0mb24laknm0f-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'

         at /nix/store/z7y28qzhk7driiwcw78k0mb24laknm0f-source/pkgs/stdenv/generic/make-derivation.nix:395:7:

          394|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          395|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          396|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: sphinx-7.2.6 not supported for interpreter python3.8
```

### Additional context

The issue also happens when trying to use a poetry2nix environment so I'm geussing the root cause is the same : 

```nix
{
  description = "";

  inputs = {
    nixpkgs = { url = "github:NixOS/nixpkgs/nixos-unstable"; };
    flake-utils = { url = "github:numtide/flake-utils"; };
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        flake-utils.follows = "flake-utils";
      };
    };
  };

  outputs =
    { self
    , nixpkgs
    , flake-utils
    , poetry2nix
    ,
    }:
    flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ 
          poetry2nix.overlays.default
        ];
      };

      python = pkgs.python38;
      poetryEnv = pkgs.poetry2nix.mkPoetryEnv {
        projectDir = self;
        inherit python;
      };

    in
    {
      formatter = pkgs.nixpkgs-fmt;
      devShells.default = pkgs.mkShell {
        buildInputs = [
          python
          poetryEnv
        ];
      };
    });
}
```

Is python 3.8 not supported anymore with poetry? Can I override this dependency somehow?

### Notify maintainers

@jbaum98 @dotlambda 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
> Is python 3.8 not supported anymore with poetry?

No.

**Comment by Thlr** [comment]
Okay well that explains everything. I missed this information somehow.

Thanks for the quick answer.

**Comment by Thlr** [comment]
Although, may I ask on what grounds? I saw no mention of poetry dropping support for python 3.8 on their [website](https://python-poetry.org/blog/category/releases/).

**Comment by dotlambda** [comment]
> Although, may I ask on what grounds?

Because it would probably be extra work to make sphinx work with Python 3.8. Feel free to submit a PR.

**Comment by suntropez** [comment]
Pip itself depends on it though. Should something be done about that, like a constraint somewhere?

```
nix-repl> python38Packages.pip
error:
       … while evaluating the attribute 'drvPath'

         at /nix/store/457aqsrnk6hylbx9wf0m2xi0j9bpxx49-nixpkgs/nixpkgs/lib/customisation.nix:249:7:

          248|     in commonAttrs // {
          249|       drvPath = assert condition; drv.drvPath;
             |       ^
          250|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'drvPath'

         at /nix/store/457aqsrnk6hylbx9wf0m2xi0j9bpxx49-nixpkgs/nixpkgs/lib/customisation.nix:249:7:

          248|     in commonAttrs // {
          249|       drvPath = assert condition; drv.drvPath;
             |       ^
          250|       outPath = assert condition; drv.outPath;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: sphinx-7.2.6 not supported for interpreter python3.8
```

**Comment by doronbehar** [comment]
> Pip only depends on sphinx to build the man pages, but it's not necessary to run. In my opinion, we should fix this even if sphinx it's not compatible with Python 3.8. The straightforward fix would be to not build the man pages when Python version is <=3.8. What do you think @anund and @doronbehar

Sounds good to me.

**Comment by anund** [comment]
Looking at where sphinx was bumped https://github.com/NixOS/nixpkgs/pull/259350 the only other alternative would be to introduce a `sphinx_x_x` to make pip compatible with older versions.

**Comment by torgeir** [comment]
I agree that this is inconvenient and would appreciate a fix like the one suggested. Hit this issue with a simple dev shell with python38, black and flake8

```nix
{ pkgs ? import <nixpkgs> { } }:
with pkgs;
mkShell {
  packages = with pkgs;
    [ (python38.withPackages (ps: with ps; [ black flake8 ])) ];
}
```

**Comment by SuperSandro2000** [comment]
> PS: I use custom derivation without this change #250398

That would indeed work but since python 3.8 is EOL, we don't plan to maintain packages for it as it is just to much work for not that much benefit.

**Comment by dotlambda** [comment]
Python 3.8 is not EOL.

**Comment by anund** [comment]
Some investigations that might help:
The example from @torgeir is not failing for depending on pip. `nix-shell -f torgeir-example.nix --show-trace` shows `black` -> `aiohttp` -> `trustme` -> `pyopenssl` -> `sphink-hook` so similar problem but not pip related.

Things depending on `sphinxhook` and `sphinx-*` packages directly require adding back an older copy of `sphinx` and updating python things `< 3.8` to use those. I'm not sure where in the current python machinery that work would best land.

Here's a shell example that can override pip to cut out the change in https://github.com/NixOS/nixpkgs/pull/250398:
```nix
{ pkgs ? import <nixpkgs> { 
  overlays = [
    (final: prev: {
      pythonPackagesExtensions = prev.pythonPackagesExtensions ++ [
        (
          python-final: python-prev: {
            pip = (python-prev.pip.overrideAttrs(old:{
              postBuild = "";
              outputs = ["out"];
              dist = "py38";
            })).override { sphinx = null; };
          }
        )
      ];
    })
  ];
}}:
with pkgs;
mkShell {
  packages = with pkgs;
    [ (python38.withPackages (ps: with ps; [ pip ])) ];
}
```

Python 3.8 appears to only be receiving emergency security fixes at this point. https://devguide.python.org/versions/. Bugfix releases ended ~may 2021 https://peps.python.org/pep-0569/. It's not technically eol just ~9 months and no emergencies away.

**Comment by anund** [comment]
`poetry.override{python3 = python38}` -> `cachy` -> `redis` -> `deprecated` -> `sphinx-hook` (similarly not pip related).

**Comment by SuperSandro2000** [comment]
> Python 3.8 is not EOL.
> I think if someone fixed this in a PR we'd definitely consider it.

It is in nixpkgs because we don't recurse into it anymore.

**Comment by mweinelt** [comment]
We're removing Python 3.8 before the NixOS 24.05 merge, so time is probably better spent on porting your code to a newer release.

- #285779
