### ISSUE TITLE
Packages that where maintained by jfrankenau need new maintainers

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#268708]
In https://github.com/NixOS/nixpkgs/pull/267114, jfrankenau was removed from the `maintainer-list.nix`. Their packages need new maintainers.

Packages without a maintainer:

- [x] `noice` - Small ncurses-based file browser
- [ ] `rapid-photo-downloader` - Photo and video importer for cameras, phones, and memory cards
- [ ] `scantailor-advanced` - Interactive post-processing tool for scanned pages
- [x] `sxiv` - Simple X Image Viewer
- [ ] `valentina` - An open source sewing pattern drafting software
- [ ] `bcal` - Storage conversion and expression calculator
- [ ] `gurobi` - Optimization solver for mathematical programming
- [ ] `groove` - GRaphs for Object-Oriented VErification
- [ ] `mpv-mpris` - MPRIS plugin for mpv
- [ ] `libmysofa` - Reader for AES SOFA files to get better HRTFs
- [ ] `mac` - APE codec and decompressor
- [ ] `stb` - Single-file public domain libraries for C/C++
- [ ] `easygui` - Very simple, very easy GUI programming in Python
- [ ] `gphoto2` - Python interface to libgphoto2
- [ ] `pymediainfo` - Python wrapper for the mediainfo library
- [ ] `PyPrind` - Python Progress Bar and Percent Indicator Utility
- [ ] `rawkit` - CTypes based LibRaw bindings for Python
- [ ] `splix-svn` - CUPS drivers for SPL (Samsung Printer Language) printers
- [x] `mergerfs-tools` - Optional tools to help manage data in a mergerfs pool

Packages with now only one maintainer:

- `nnn` - The unorthodox terminal file manager
- `tvbrowser` - Electronic TV Program Guide
- `urlscan` - Mutt and terminal url selector
- `mergerfs` - A FUSE based union filesystem
- `triggerhappy` - A lightweight hotkey daemon
- `ntfy` - A utility for sending notifications, on demand and when commands finish
- `otfcc` - Optimized OpenType builder and inspector
- `plowshare` - A command-line download/upload tool for popular file sharing websites

**Comment by katexochen** [comment]
@makefu would you be interested in maintaining `mergerfs-tools`, as you also maintain `mergerfs`?

**Comment by RaitoBezarius** [comment]
I can take gurobi (if no one is found in the meantime, I don't really enjoy maintaining this), ntfy and urlscan.

**Comment by h7x4** [comment]
I think there's a small error on `jarun`, maybe jarun is the author and `bcal` is the package?

**Comment by katexochen** [comment]
> I think there's a small error on `jarun`, maybe jarun is the author and `bcal` is the package?

Right, fixed it.

**Comment by makefu** [comment]
> @makefu would you be interested in maintaining `mergerfs-tools`, as you also maintain `mergerfs`?

i can do this, yes. i will prepare a PR
