### ISSUE TITLE
Is there a way to install browser extensions declaratively?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#26889]
Is there a way to install browser (Chrome and Firefox) extensions (for example "ublock") declaratively (via ```configuration.nix```) ?

**Comment by bjornfor** [comment]
I think this feature was added for chromium just a few days ago to nixpkgs master.

**Comment by mogria** [comment]
Yes there is a possibility install extensions in chromium: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/chromium.nix#L25

**Comment by volth** [comment]
That's cool, besides Chromium is the only browser to be compiled locally. But it makes trivial to do the same for the other browsers (and perhaps faster than Chromium compilation finishes).
Thank you!

**Comment by CMCDragonkai** [comment]
Can this work with config.nix installs (not configuration.nix)?

**Comment by CMCDragonkai** [comment]
This configuration is only for NixOS. Is it possible to apply to the chromium package that can be installed on non-NixOS environments?
