### ISSUE TITLE
Package request: prometheus-mongodb-exporter

### ISSUE THREAD

**Issue by undefined-moe** [NixOS/nixpkgs#268875]
**Project description**

Export metrics from mongodb as prometheus format

**Metadata**

* homepage URL: https://github.com/percona/mongodb_exporter
* source URL: https://github.com/percona/mongodb_exporter
* license: Apache 2.0
* platforms: Linux/Darwin

**Comment by NickCao** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/268991
