### ISSUE TITLE
Package request: kinto

### ISSUE THREAD

**Issue by carleeto** [NixOS/nixpkgs#268808]
**Project description**

Mac-style shortcut keys for Linux

[Setup video](https://www.youtube.com/watch?v=kd4al45XD1g)

**Metadata**

* homepage URL: https://github.com/rbreaves/kinto
* source URL: https://github.com/rbreaves/kinto
* license: gpl2
* platforms: unix, linux, darwin

**Comment by eclairevoyant** [comment]
dupe of #137698
