### ISSUE TITLE
NixOS 23.05: EC2 Instance Status Check failure when using gp3 volumes and enabling cloud-init

### ISSUE THREAD

**Issue by sergeykranga** [NixOS/nixpkgs#268986]
### Describe the bug

We build NixOS AMIs for EC2 instances. We are currently migrating to NixOS 23.05, and we're facing an issue where enabling `cloud-init` while using `gp3` volumes breaks Instance Status Checks and causes the EC2 instance to fail starting up. This does not happen when using `standard` (`gp2`) volumes. This also doesn't happen neither on `gp3` nor on `standard` when using NixOS 22.11

### Steps To Reproduce
1. Create a file `ec2.nix` with the next content:
```
{ config, ... }:
{
  imports = [
    <nixpkgs/nixos/modules/virtualisation/amazon-image.nix>
  ];
  amazonImage.sizeMB = "auto";
  ec2.hvm = true;
  services.cloud-init.enable = true;
  system.stateVersion = config.system.nixos.release;
}
```
2. Create a script that would build the image, push it to S3, import that snapshot from S3 and register an AMI (this is a simplified version):
```
#!/usr/bin/env bash
set -eu
set -o pipefail

function read_image_info {
    if [ ! -e "$store_path/nix-support/image-info.json" ]; then
        log "Image missing metadata"
        exit 1
    fi
    jq -r "$1" "$store_path/nix-support/image-info.json"
}

volume_type="gp3" # will cause issues starting the ec2 instace
# volume_type="standard" # works fine
image_name="nixos-23.05-${volume_type}-test-ami"
s3_bucket="SELECT_YOUR_OWN_BUCKET"

# build the image
echo "building the image..."
store_path=$(nix-build --no-out-link '<nixpkgs/nixos/release.nix>' \
    --arg configuration "{ ... }: { imports = [ (import ./ec2.nix) ]; }" \
    -A amazonImage.x86_64-linux)
echo "store path: ${store_path}"

# upload to s3
echo "uploading the image to s3..."
image_file=$(read_image_info .file)
aws s3 cp "${image_file}" "s3://${s3_bucket}/${image_name}"

# import snapshot from s3 (make sure your `vmimport` role is allowed access to the s3 bucket)
echo "importing snapshot from s3..."
import_task_id="$(aws ec2 import-snapshot \
    --description "${image_name}" \
    --disk-container "{
        \"Format\": \"vhd\",
        \"UserBucket\": {
            \"S3Bucket\": \"${s3_bucket}\",
            \"S3Key\": \"${image_name}\"
        }}" \
    --query 'ImportTaskId' \
    --output text)"

# wait for snapshot to complete (simplified logic)
echo "waiting for import to complete..."
while true; do
    state="$(aws ec2 describe-import-snapshot-tasks \
        --import-task-ids "${import_task_id}" \
        --query 'ImportSnapshotTasks[0].SnapshotTaskDetail.Status' \
        --output text)"
    echo "import state: ${state}"

    if [ "${state}" == "completed" ]; then
        break
    fi

    sleep 10
done

# register image
echo "registering the image..."
snapshot_id="$(aws ec2 describe-import-snapshot-tasks \
    --import-task-ids "${import_task_id}" \
    --query 'ImportSnapshotTasks[0].SnapshotTaskDetail.SnapshotId' \
    --output text)"

image_logical_bytes=$(read_image_info .logical_bytes)
image_logical_gigabytes=$((($image_logical_bytes - 1) / 1024 / 1024 / 1024 + 1)) # Round to the next GB

block_device_mappings=(
    "DeviceName=/dev/sda1,Ebs={SnapshotId=$snapshot_id,VolumeSize=$image_logical_gigabytes,DeleteOnTermination=true,VolumeType=${volume_type}}"
)

aws ec2 register-image \
    --name "${image_name}" \
    --description "NixOS 23.05 AMI with ${volume_type} root block device" \
    --architecture x86_64 \
    --ena-support \
    --sriov-net-support simple \
    --virtualization-type hvm \
    --root-device-name /dev/sda1 \
    --block-device-mappings "${block_device_mappings[@]}" \
    --query 'ImageId'
```
3. Run the script. A new AMI should appear in your AWS account
4. Launch a new instance from this AMI
5. Observe that while `System status checks` of the instance pass, the `Instance status checks` fail after some time

### Expected behavior
The instance should launch normally and pass all EC2 health checks without issues

### Additional context
Looking at EC2 system logs, we see that IMDS for some reason can't be reached:
```
fetch-ec2-metadata-start[944]: curl: (7) Failed to connect to 169.254.169.254 port 80 after 0 ms: Couldn't connect to server
```

### Notify maintainers
@illustris @jfroche

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.05 (Stoat), 23.05.4906.0c5678df521e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(scranga): `""`
 - channels(root): `"nixos-23.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by illustris** [comment]
Huh... I can't imagine how changing the disk type could break cloud init. Thanks for reporting the issue. I'll check it out in a few hours.

**Comment by illustris** [comment]
I tried building both variants with the master branch. Both status checks are passing on both instances. I'll try 23.05.

**Comment by sergeykranga** [comment]
i switched to master:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(scranga): `""`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/store/7rvd8ffbvi3r08cynpjvx9b18aax0gk7-nixpkgs`
```
and it worked for me too

**Comment by sergeykranga** [comment]
switched back to 23.05 (linux version, the commit id and nix-env is now slightly different for whatever reason) but it failed for me again:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 23.05 (Stoat), 23.05.4930.f741f8a83991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(scranga): `""`
 - channels(root): `"nixos-23.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sergeykranga** [comment]
looking at the versions of cloud-init used in all of these channels, it is jumping major versions. looking at the changelog, unfortunately i can't tell what can cause the issue, or whether cloud-init has anything to do with it at all:
```
# https://github.com/NixOS/nixpkgs/blob/22.11/pkgs/tools/virtualization/cloud-init/default.nix
22.11: cloud-init-22.4
# https://github.com/NixOS/nixpkgs/blob/23.05/pkgs/tools/virtualization/cloud-init/default.nix
23.05: cloud-init-23.1.2
# https://github.com/NixOS/nixpkgs/blob/24.05-pre/pkgs/tools/virtualization/cloud-init/default.nix
24.05: cloud-init-23.3.3
```

by the way thanks for checking, this has been driving me nuts and i hope i'm not crazy

**Comment by illustris** [comment]
```
Nov 23 18:44:24 localhost dhcpcd[693]: ens5: waiting for carrier
Nov 23 18:44:24 localhost dhcpcd[693]: ens5: carrier acquired
Nov 23 18:44:24 localhost kernel: ena 0000:00:05.0 ens5: Local page cache is di>
Nov 23 18:44:24 localhost systemd[1]: Finished Permit User Sessions.
Nov 23 18:44:24 localhost dhcpcd[693]: ens5: IAID c1:da:02:8c
Nov 23 18:44:24 localhost dhcpcd[693]: ens5: adding address fe80::2e:c1ff:feda:>
Nov 23 18:44:24 localhost systemd[1]: Started D-Bus System Message Bus.
Nov 23 18:44:24 localhost dbus-daemon[701]: [system] Successfully activated ser>
Nov 23 18:44:24 localhost systemd[1]: Created slice Slice /user/0.
Nov 23 18:44:24 localhost systemd[1]: Starting User Runtime Directory /run/user>
Nov 23 18:44:24 localhost systemd-logind[740]: New session 1 of user root.
Nov 23 18:44:24 localhost systemd-timesyncd[491]: Network configuration changed>
Nov 23 18:44:24 localhost systemd[1]: Finished User Runtime Directory /run/user>
Nov 23 18:44:24 localhost systemd[1]: Starting User Manager for UID 0...
Nov 23 18:44:24 localhost (systemd)[810]: pam_unix(systemd-user:session): sessi>
Nov 23 18:44:24 localhost systemd[810]: Queued start job for default target Mai>
Nov 23 18:44:24 localhost systemd[810]: Created slice User Application Slice.
Nov 23 18:44:24 localhost systemd[810]: Reached target Paths.
Nov 23 18:44:24 localhost systemd[810]: Reached target Timers.
Nov 23 18:44:24 localhost systemd[810]: Starting D-Bus User Message Bus Socket.>
Nov 23 18:44:24 localhost systemd[810]: Listening on D-Bus User Message Bus Soc>
Nov 23 18:44:24 localhost systemd[810]: Reached target Sockets.
Nov 23 18:44:24 localhost systemd[810]: Reached target Basic System.
Nov 23 18:44:24 localhost systemd[810]: Run user-specific NixOS activation was >
Nov 23 18:44:24 localhost systemd[1]: Started User Manager for UID 0.
Nov 23 18:44:24 localhost systemd[810]: Reached target Main User Target.
Nov 23 18:44:24 localhost systemd[810]: Startup finished in 358ms.
Nov 23 18:44:24 localhost systemd[1]: Started Session 1 of User root.
Nov 23 18:44:24 localhost login[817]: ROOT LOGIN  on '/dev/ttyS0'
Nov 23 18:44:25 localhost dhcpcd[693]: ens5: soliciting a DHCP lease
Nov 23 18:44:25 localhost kernel: NET: Registered PF_PACKET protocol family
Nov 23 18:44:25 localhost dhcpcd[693]: ens5: offered 172.31.18.156 from 172.31.>
Nov 23 18:44:25 localhost dhcpcd[693]: ens5: probing address 172.31.18.156/20
Nov 23 18:44:25 localhost dhcpcd[693]: ens5: soliciting an IPv6 router
Nov 23 18:44:28 localhost dhcpcd[693]: ens5: carrier lost
Nov 23 18:44:28 localhost dhcpcd[693]: ens5: deleting address fe80::2e:c1ff:fed>
Nov 23 18:44:29 localhost dhcpcd[693]: ens5: carrier acquired
Nov 23 18:44:29 localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): ens5: link bec>
Nov 23 18:44:29 localhost dhcpcd[693]: ens5: IAID c1:da:02:8c
Nov 23 18:44:29 localhost dhcpcd[693]: ens5: adding address fe80::2e:c1ff:feda:>
Nov 23 18:44:29 localhost dhcpcd[693]: ens5: carrier lost
Nov 23 18:44:29 localhost dhcpcd[693]: ens5: deleting address fe80::2e:c1ff:fed>
Nov 23 18:44:54 ip-172-31-18-156 dhcpcd[693]: timed out
```

Looks like the link is flapping during boot. This only seems to be happening on the gp3 instance. Not sure what to make of this... Let me see if there are any significant differences in the boot logs between master and 23.05.

**Comment by sergeykranga** [comment]
well i guess with deprecation of 23.05, this no longer deserves attention and can be closed (unless someone disagrees)

**Comment by sergeykranga** [comment]
this is still an issue with 23.11. what is even weirder is that i launch 5 instances, and one of them works just fine

**Comment by arianvp** [comment]
Are you sure there is no firewall or security group rule messing with DHCP traffic?

I have a feeling the GP3/GP2 thing is a red herring and instead cloud-init is doing something that breaks your network setup

**Comment by zimbatm** [comment]
Cloud-init also runs its own DHCP client as part of the discovery process. Because cloud-init runs so early, there is often no network stack available, so it configures the network interface, just to be able to query the metadata service. That code was refactored in April, which might explain why the behaviour changed between releases.

EC2 has two data sources: EC2 and Ec2Local. And the local one does DHCP discovery. See https://github.com/canonical/cloud-init/blob/967104088db0e9724096e3776c9c31ccbb3f97cb/cloudinit/sources/DataSourceEc2.py#L128-L147

One thing you can try is to restrict the list of data sources. That also generally also helps speed up the boot as it doesn't have to go through the whole list:

```nix
services.cloud-init.settings.datasource_list = [ "Ec2" ];
services.cloud-init.settings.datasource.Ec2 = { };
```

Other things to try would be to enable `systemd.network.enable` and `boot.initrd.systemd.network.enable`.

One side note: if `services.cloud-init.enable` is enabled, turn off `virtualisation.amazon-init` as it is also consuming from the metadata server.

**Comment by zimbatm** [comment]
In the boot logs, check what data source it found. If you see something like that then it has executed its own DHCP client:
```
2019-08-07 14:33:27,259 - handlers.py[DEBUG]: finish: init-local/search-Ec2Local: SUCCESS: found local data from DataSourceEc2Local
2019-08-07 14:33:27,259 - stages.py[INFO]: Loaded datasource DataSourceEc2Local - DataSourceEc2Local
```

**Comment by sergeykranga** [comment]
> Are you sure there is no firewall or security group rule messing with DHCP traffic?
> 
> I have a feeling the GP3/GP2 thing is a red herring and instead cloud-init is doing something that breaks your network setup

i am telling that to myself all the time but after verifying multiple times, it really works with standard volumes, and doesn't work with gp2/gp3. the network setup is the same in all cases

**Comment by arianvp** [comment]
I'm curious if we can replicate the same issue on other cloud-init enabled distros. 

I do think @zimbatm is  onto something with cloud-init having its own DHCP impl. If disabling that fixes the issue we at least know in what direction to look.

**Comment by illustris** [comment]
Should be fixed by the latest commit in https://github.com/NixOS/nixpkgs/pull/273707

This is caused by cloud-init having its own dhcp client, as zimbatm suggested. `cloud-init-local.service` first makes a DHCP request, does some things, and then deletes all network configs it applied. We run into a race condition if DHCPCD starts before cloud-init-local has deleted the network configs. DHCPCD makes a request and applies the same IP configs, but cloud-init-local just deletes these configs after that, leaving your VM with no IP.

I didn't have time to dig deeper into why this happening only on gp3, but I have one theory. A gp3 volume has a default IOPS cap of 3000 irrespective of size, while a gp2 volume's iops scales with size. For an 8GB volume it would be 100 iops. Because of this, the startup time of some services might be slower than others on gp2, delaying dhcpcd long enough to start after cloud-init-local is done.

**Comment by sergeykranga** [comment]
@illustris thanks for your work! i will be verifying the fix the next week

**Comment by sergeykranga** [comment]
this is now working, much thanks again for getting this fixed!
