### ISSUE TITLE
Paraview fails to start due to failing VTKNetCDF dynamic dependency

### ISSUE THREAD

**Issue by cipharius** [NixOS/nixpkgs#268961]
### Describe the bug
The `paraview` package builds without issues, but when it's ran it produces following error message:
```
paraview: symbol lookup error: /nix/store/lximc4rkgkh2dlrli98y462wq66vsdfa-paraview-5.11.1/bin/../lib/libvtknetcdf-pv5.11.so.1: undefined symbol: vtknetcdf_strlcat
```

I have tried building different versions(5.9.1 - 5.11.2) of paraview on two different hosts and I get the same error on both of my hosts for all of these paraview versions.

### Steps To Reproduce
1. `nix-shell -p paraview`
2. `paraview`

### Expected behavior
The application starts and resolves it's dynamic dependencies.

### Notify maintainers
@dguibert 

### Metadata

Laptop:
```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(valts): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/kcmipm57ph9bpzz8bs80iiijiwbyzwy3-source`
```

Desktop:
```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.8, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/store/kcmipm57ph9bpzz8bs80iiijiwbyzwy3-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dguibert** [comment]
I've bisected this up to commit e86152986c6e6c563ced037c91403318d5a8b447.

Maybe related to DT_HASH, need more time to investigate
(see https://maskray.me/blog/2022-08-21-glibc-and-dt-gnu-hash)

@Ma27, any idea?

**Comment by cipharius** [comment]
Thanks, good catch! Will have to see if I can modify build process to get it working. Unfortunately paraview builds are pretty slow.
