### ISSUE TITLE
latexpand fails with perl 5.24.1

### ISSUE THREAD

**Issue by danielfullmer** [NixOS/nixpkgs#26890]
## Issue description

`latexpand` is a utility that is distributed with texlive. The update to default perl 5.24.1 in f78c0329340172aa0819d7a2fdc36b0a8fbb6d2a causes latexpand to fail with a syntax error. This has been noticed upstream:
https://gitlab.com/latexpand/latexpand/issues/4
and fixed in latexpand v1.3.  I frequently use `git-latexdiff` which also fails since latexpand is broken.

### Steps to reproduce

`nix-shell -p texlive.combined.scheme-medium --command latexpand`

Fails with

> Execution of /nix/store/...-latexpand-1.2/scripts/latexpand/latexpand aborted due to compilation errors.

for nixpkgs after f78c0329340172aa0819d7a2fdc36b0a8fbb6d2a  and succeeds before this commit.

## Technical details

* System: 17.09.git.6b1087d (Hummingbird)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: 17.09pre109180.0d4431cfe9
* Sandboxing enabled: false

**Comment by danielfullmer** [comment]
Oh, BTW: Texlive 2017 was recently released, and would hopefully include the newer version of latexpand.

**Comment by FRidh** [comment]
cc maintainer @vcunat as well as @NickHu who was interested in a texlive upgrade.

**Comment by vcunat** [comment]
Upgrade wouldn't be a quick and easy thing, so I made it use older perl for now.
