### ISSUE TITLE
xen: use system ipxe instead of internal one

### ISSUE THREAD

**Issue by michalpalka** [NixOS/nixpkgs#26899]
## Issue description

Currently, the xen pulls its own instance of ipxe: [pkgs/applications/virtualization/xen/4.5.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/xen/4.5.nix#L134).

It would be good to use the system ipxe, and/or to make it optional, as mentioned in #26492.

## Technical details

* System: `17.09.git.c38a36f (Hummingbird)`

**Comment by SigmaSquadron** [comment]
Fixed in Xen 4.18.2. #324693
