### ISSUE TITLE
Netdata: eBPF Support Hard-Coded to be Disabled?

### ISSUE THREAD

**Issue by brotherdust** [NixOS/nixpkgs#269059]
@RaitoBezarius 

Thanks for all the work you do keeping this package up to date. Noticed that eBPF support is hard-coded to be disabled and that there's no option to enable it in the package. I'd like to make a PR to make this an option, but wanted to check with you first to see if there was a particular reason why it's this way.

Thank you kindly!

https://github.com/NixOS/nixpkgs/blob/e4ad989506ec7d71f7302cc3067abd82730a4beb/pkgs/tools/system/netdata/default.nix#L116

**Comment by Kiskae** [comment]
From the [git blame](https://github.com/NixOS/nixpkgs/commit/e6df811980c529f2ee5239a848f01709851c0a08):
> - libbpf support was disabled as a result of a configure-time file existence
check. This check errored during cross compilation. Prevent the check from
running during cross compilation by explicitly disabling libbpf support.

libbpf support detection appears to be broken in the nix sandbox and it was explicitly disabled because the way it detects support causes a failure in cross-compilation - https://github.com/NixOS/nixpkgs/pull/171670#issuecomment-1121991227

Sounds like if you can make it work and ensure `pkgsCross.aarch64-multiplatform.netdata` or equivalent also builds you're free to try and fix it.

**Comment by brotherdust** [comment]
> From the [git blame](https://github.com/NixOS/nixpkgs/commit/e6df811980c529f2ee5239a848f01709851c0a08):
> 
> > - libbpf support was disabled as a result of a configure-time file existence
> 
> check. This check errored during cross compilation. Prevent the check from
> 
> running during cross compilation by explicitly disabling libbpf support.
> 
> 
> 
> libbpf support detection appears to be broken in the nix sandbox and it was explicitly disabled because the way it detects support causes a failure in cross-compilation - https://github.com/NixOS/nixpkgs/pull/171670#issuecomment-1121991227
> 
> 
> 
> Sounds like if you can make it work and ensure `pkgsCross.aarch64-multiplatform.netdata` or equivalent also builds you're free to try and fix it.
> 
> 
> 
> EDIT: looks like as of #186554 netdata cross-compilation is broken regardless of ebpf. You could perhaps keep in the flag for cross-compilation for future reference.
> 
> ```
> 
> ++ optionals (stdenv.hostPlatform != stdenv.buildPlatform) [
> 
>     "--disable-ebpf"
> 
> ]
> 
> ```
> 
> 
> 
> EDIT2: seems like the issue with cross-compilation should be resolved by upstream: https://github.com/netdata/netdata/issues/14185

Thank you for pointing that out!

If the issue cannot be resolved by the referenced issue, is it permissible to exclude a package from cross-compile and require that it be built native? Or is that just making more problems?

**Comment by Kiskae** [comment]
That is pretty much what happened after the `libjudy` change, if it can't be cross-compiled then marking it as broken for those builds is expected. Perhaps someone reviewing the change will suggest a way to fix it anyway.

**Comment by brotherdust** [comment]
Thank you for your comments. I decided this isn't worth the hassle. I'm just going to live without eBPF for now.

**Comment by RaitoBezarius** [comment]
I think this issue can be solved pretty easily as Kisake mentioned it. I will fix once I have a minute.
