### ISSUE TITLE
`linux-zen` VP9 VAAPI decoding stutters heavily on RX 6000 series GPUs

### ISSUE THREAD

**Issue by soupglasses** [NixOS/nixpkgs#269016]
### Describe the bug
When using `linux-zen` `6.6.0` and `6.6.1`, VP9 VAAPI decoding on RX 6000 series GPUs will hang, stutter, and glitch to an unwatchable state. This occurs across both firefox, mpv, wayland, and xorg. Which is why its making me feel like its a zen related issue. Installing `linux` `6.6.1` fixed the issue everywhere.

### Steps To Reproduce
1. Use `boot.kernelPackages = pkgs.linuxPackages_zen;` with `6.6.1` on a `RX6000` series GPU.
2. Run a command like `mpv video.mp4 --hwdec=vaapi` on a vp9 enabled video and watch the artifacting and stutters.
3. Now run `mpv video.mp4` without hardware decoding and see it work flawlessly.

### Expected behavior
Hardware decoding on `RX6000` series GPUs work without issue as on `linuxPackages_latest`'s `6.6.1`.

### Screenshots
Not screenshots, but a video of with and without hw decode: https://youtu.be/d88l8kfD3PM

### Additional context
Its a brand new GPU.

### Notify maintainers
@thiagokokada @JerrySM64 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

This is technically incorrect with regards to the kernel, as i have already changed it over.
```console
% nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux
copying path '/nix/store/bbxdw4rgwwl3gnajri82yidr1nlsfskf-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir), 23.11.20231121.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/11hm07gdcjrzrqv73ii0n3j7jiqnq23w-source`

```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JerrySM64** [comment]
I'll take a look at it tomorrow. As I have an RX 6650 XT, I should see the same issue you're experiencing. There's also 6.6.2 out which may fix that. When I have the possibility, I will push that (Currently affected by a major internet outage since Monday. That's why I haven't done it yet.)

**Comment by soupglasses** [comment]
Ah thank you. :D

Truly sorry to hear about the internet outage, so dont strain your connection if it hasnt fully recovered. I am just primarily happy to figure out this is a likely quirk introduced by the zen patchset or its spessific compile options inside nixpkgs, and not in fact my brand new GPU acting like it doesn't know how to decode VP9. :sweat_smile:

**Comment by JerrySM64** [comment]
I just took my PC to a friend to have internet access and I can't reproduce the issue as seen here: https://youtu.be/zdSlLVspgTc

What GPU do you have exactly?

**Comment by JerrySM64** [comment]
Okay, the 6950 XT can do it for sure. I mean, my 6650 XT can also do it. I was asking because I'm not sure about the 6500 and 6400.
That's something, I currently cannot test. My 144 Hz monitor is at home where the internet isn't working, but I doubt that it's related tbh. Don't quote me on that one though.
I just made the PR with the 6.6.2 kernels. If that doesn't fix it, I'll have to return to this issue when my internet is working again, I'm afraiad.

**Comment by soupglasses** [comment]
Bad news i just got this to happen on the stock non `-zen` kernel, so this issue is likely not related to the linux-zen patchset. I will dig deeper into this, i fear another amd driver bug thats never getting resolved.

**Comment by soupglasses** [comment]
Opened https://gitlab.freedesktop.org/drm/amd/-/issues/3013

**Comment by nonetrix** [comment]
dumb question, but how do you have vaapi enabled in the first place? I could only enable vdpau and get that to work in Firefox, I want to try hw video decoding again since they fixed issue where it would cause GPU resets

**Comment by soupglasses** [comment]
> @nonetrix The NixOS documentation is extremely unhelpful as it only shows how to do it on Intel GPUs.

This is an issue tracking what ended up being an upstream issue with the VP9 decoder, however, you should check out https://wiki.archlinux.org/title/Hardware_video_acceleration it should be the best resource available for this. Otherwise I may recommend you to open a separate issue if you believe this to be an issue in NixOS itself.
