### ISSUE TITLE
dont hardcode FHS paths in `makeFontsConf`

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#269082]
## Issue description

while using the playwright derivation (a tool to test websites UI) in a container on CI, we ended up with different results than in our nix shells. Turned out the alpine container had some embedded fonts or some fontconfig that was changing a few pixels when doing snapshots.
We tracked it down to 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/fontconfig/make-fonts-conf.xsl
which contains the FHS paths that existed in the container.
We worked around it via a complex nix override but I think what would be better instead of hardcoding the FHS paths in  https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/fontconfig/make-fonts-conf.xsl owuld be to set them as default in fontDirectories in pkgs/top-level/../development/libraries/fontconfig/make-fonts-conf.nix instead. This way changing fontdirectories would remove them. 
We could actually do the same for
```
       <!-- nix user profile -->
      <dir>~/.nix-profile/lib/X11/fonts</dir>
      <dir>~/.nix-profile/share/fonts</dir>
```
IMO .

### Steps to reproduce

@xworld21 last committer.

## Technical details
unstable

**Comment by xworld21** [comment]
> set them as default in fontDirectories in pkgs/top-level/../development/libraries/fontconfig/make-fonts-conf.nix instead

I like this idea, I'll propose a PR in the weekend (there are some subtleties about the ordering of system vs home vs XDG vs custom folders that I need to think about – we might need e.g. two parameters `fontDirectories` and `systemFontDirectories`). The challenge is not the PR, though, but the review... it will be a mass rebuild for sure.

**Comment by teto** [comment]
done in linked PR
