### ISSUE TITLE
Update request: python310Packages.xformers 0.03 → 0.0.22.post7

### ISSUE THREAD

**Issue by felixsanz** [NixOS/nixpkgs#269056]
- Package name: [python310Packages.xformers](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=xformers)
- Latest released version: 0.0.22.post7

- Current version on the unstable channel: `0.03` (This version never existed but whatever!)
- Current version on the stable/release channel: None

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@happysalada

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
let me know if you have time to test https://github.com/NixOS/nixpkgs/pull/269065
