### ISSUE TITLE
clj-kondo attempting to access graalvm-ce

### ISSUE THREAD

**Issue by jcf** [NixOS/nixpkgs#269029]
### Describe the bug

Install clj-kondo and the following error occurs:

```
$ nix develop --impure
error: output '/nix/store/y6h6cq22izlr5dag6yz5wcaf0vai1l30-clj-kondo-2023.10.20' is not allowed to refer to the following paths:
         /nix/store/yzdpwaz10q8lrc6hhdqjyzw7970j5pdl-graalvm-ce-21.0.1
error: 1 dependencies of derivation '/nix/store/k8jfrm3ls00i8x58pwvwls80ibnh4r14-devenv-profile.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bzyb6xkp02qh2kgvp3y2l4n7cbwg851m-devenv-shell-env.drv' failed to build
```

No trouble installing clj-kondo a few weeks ago so could be a problem specific to the [latest release](https://github.com/NixOS/nixpkgs/pull/262474) if not my setup.

### Steps To Reproduce

<details><summary><code>flake.nix</code></summary>

``` nix
{
  description = "Example";

  inputs = {
    devenv.url =
      "github:cachix/devenv/9ba9e3b908a12ddc6c43f88c52f2bf3c1d1e82c1";

    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs";
  };

  outputs = { self, flake-utils, nixpkgs, devenv }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [
          (self: super: rec {
            nodejs = super.nodejs-18_x;
            pnpm = super.nodePackages.pnpm;
          })
        ];
        pkgs = import nixpkgs { inherit overlays system; };
      in {
        devShells.default = devenv.lib.mkShell {
          inherit inputs pkgs;
          modules = [
            ({ pkgs, ... }: {
              packages = with pkgs; [
                babashka
                clj-kondo
                clojure
                clojure-lsp
                nodejs
                pnpm
              ];

              # ----------------------------------------------------------------
              # Postgres

              services.postgres.enable = true;

              services.postgres.extensions = extensions: [
                extensions.pgvector
                extensions.postgis
              ];

              services.postgres.initialDatabases =
                [ { name = "dev"; } { name = "test"; } ];

              # So we can connect over TCP rather than via a socket.
              services.postgres.listen_addresses = "127.0.0.1";

              # ----------------------------------------------------------------
              # Processes

              env.DATABASE_URL =
                "jdbc:postgresql://127.0.0.1:5432/dev?user=dev&password=please";

              # Apple have taken port 5000 for Control Center.
              env.OVERMIND_PORT = "3000";

              # Use Overmind to workaround Tailwind's esbuild internals.
              process.implementation = "overmind";

              processes = {
              };
            })
          ];
        };
      });
}
```

</details> 

``` sh
nix develop --impure # because of devenv
```

### Expected behavior

clj-kondo should be installed.

### Notify maintainers

@r-ryantm @thiagokokada @bennyandresen @jlesquembre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[satoshi@miner01:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(jcf): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### See also

- [Slack thread in clojurians#clj-kondo](https://clojurians.slack.com/archives/CHY97NXE2/p1700663489243989)
- https://github.com/NixOS/nixpkgs/issues/95117

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teehemkay** [comment]
I'm noticing a similar error when trying to build both clojure-lsp or jet.

```
error: output '/nix/store/3c1pjrwjnfkb06abcs322nbn4a3mv2nj-clojure-lsp-2023.08.06-00.28.06' is not allowed to refer to the following paths:
         /nix/store/qlwc7ymlnafhw368vwwn4bbqcl06xqbc-graalvm-ce-21.0.1
error: 1 dependencies of derivation '/nix/store/bkhx8pdvay3k4h3sv5q7h4c9g72q8cxl-nix-shell-env.drv' failed to build
```

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - channels(kmabonzo): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

FWIW, the `host-os` above as returned by nix-info seems bogus: I'm running macOS Ventura 13.6.1
I'm using nix-darwin.

**Comment by jcf** [comment]
The problematic packages depend on the Oracle version of GraalVM.

https://github.com/NixOS/nixpkgs/pull/259639

**Comment by thiagokokada** [comment]
> I'm noticing a similar error when trying to build clojure-lsp or jet.
> 
> ```
> error: output '/nix/store/3c1pjrwjnfkb06abcs322nbn4a3mv2nj-clojure-lsp-2023.08.06-00.28.06' is not allowed to refer to the following paths:
>          /nix/store/qlwc7ymlnafhw368vwwn4bbqcl06xqbc-graalvm-ce-21.0.1
> error: 1 dependencies of derivation '/nix/store/bkhx8pdvay3k4h3sv5q7h4c9g72q8cxl-nix-shell-env.drv' failed to build
> ```

This is probably caused by this line: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-graalvm-native-image/default.nix#L65.

The reason we have it is to avoid having packages depending on `graalvm-ce` derivation itself (that is quite big). We could remove the `disallowedReferences` but the ideal fix is to identify what GraalVM is linking in the final derivations and remove the reference, e.g.: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/babashka/default.nix#L46.

**Comment by thiagokokada** [comment]
> @thiagokokada would it be enough to add the following to the clj-kondo package?
> 
> ```nix
> postInstall = ''
>   remove-references-to -t ${graalvmDrv} $out/bin/${executable}
> '';
> ```

I actually don't know, ideally you need to check why the binary is having references to the GraalVM derivation to make sure if this is safe or not.

To do so you can remove the `disallowedReferences`, build a binary, run `strings ./result/bin/clojure-lsp` and check the reason.

**Comment by jcf** [comment]
I built a copy of clj-kondo without the `disallowedReferences` and took a look at strings, but nothing jumps out at me.

https://gist.github.com/jcf/f2d5c84b4f23f78663bb2058397b857e

**Comment by thiagokokada** [comment]
> I built a copy of clj-kondo without the `disallowedReferences` and took a look at strings, but nothing jumps out at me.
> 
> https://gist.github.com/jcf/f2d5c84b4f23f78663bb2058397b857e

Ok, I think it is fair to just call `remove-references-to` in the resulting `clojure-lsp` binary.

**Comment by fabianpage** [comment]
i have the same problem with clojure-lsp. Should it be possible to apply the same fix there?
