### ISSUE TITLE
firefox does not support gamepads

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#26913]
## Issue description
No gamepads are detected in firefox. firefox-bin and chromium work fine.

### Steps to reproduce
go to http://html5gamepad.com/ in firefox

## Technical details

- System: 17.03.1395.9b948ea439 (Gorilla)
- Nix version: nix-env (Nix) 1.11.11
- Nixpkgs version: "17.03.1395.9b948ea439"
- Sandboxing enabled:  true

**Comment by 22459** [comment]
I second.

**Comment by emmanuelrosa** [comment]
Have you confirmed that gamepad support is enabled within Firefox's config? To do so, go to the URL *about:config*, then search for *gamepad*.

**Comment by lheckemann** [comment]
Yes.
