### ISSUE TITLE
Package... Misconfiguration? usb-modeswitch-data

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#269113]
### Describe the bug
When installing `usb-modeswitch-data` one would expect it to install the files as appropriate; specifically such that `udev` finds rules and is able to act on them. (Please rename the issue to somthing better, I couldn't think of anything)

### Steps To Reproduce
1. Install `usb-modeswitch` and `usb-modeswitch-data`
2. Connect a device that needs them to work
3. It doesn't work

### Expected behavior
udev should detect the device being detected, and automatically run `usb-modeswitch` with the correct parameters to switch the device to the correct mode.

So far as I can tell, this does not happen - `/etc/usb-modeswitch.d` is not populated and the rules for udev are not installed.

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by misuzu** [comment]
"Installing" packages on NixOS will only add them to PATH. For configuration you should use NixOS modules.
Try this `hardware.usbWwan.enable = true;` for 23.05 and `hardware.usb-modeswitch.enable = true;` for 23.11/unstable

**Comment by Krutonium** [comment]
> "Installing" packages on NixOS will only add them to PATH. For configuration you should use NixOS modules. Try this `hardware.usbWwan.enable = true;` for 23.05 and `hardware.usb-modeswitch.enable = true;` for 23.11/unstable

Why Wwan? In this case, it's for a USB steering wheel.

**Comment by misuzu** [comment]
> Why Wwan

Historical reasons

> it's for a USB steering wheel 

Try it anyways
