### ISSUE TITLE
`lib.fileset.gitTracked` should support out-of-tree builds

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs#269283]
## Issue description

Currently, using `gitTracked ./.` in a local project fails when that project is fetched with e.g. `fetchGit`, since there's no `.git` directory in that case.

### Steps to reproduce

With https://github.com/infinisil/gitTracked-example/blob/main/default.nix:

```
$ nix-instantiate https://github.com/infinisil/gitTracked-example/tarball/master --eval -A outPath
error: lib.fileset.gitTracked: Expected the argument (/nix/store/sdhphiawzjiw9yxr50iqf729sd14wmy1-source) to point to a local working tree of a Git repository, but it's not.
```

### Proposed solution

Detect whether the passed path is already in the Nix store, in which case just return the set of all its files. Only fail if that's not the case.
A bit icky but might be fine? Needs a bit more thought.

This issue is sponsored by [Antithesis](https://antithesis.com/) :sparkles:

**Comment by infinisil** [comment]
I opened a draft PR which will fix this: https://github.com/NixOS/nixpkgs/pull/273893

**Comment by ShamrockLee** [comment]
How about (also) printing out a message when `.git` directory isn't found? That would be similar to the `No Makefile, do nohhing` but at eval time.

The down side might be repetition of this message whenever one of whenever the expression gets evaluated.

**Comment by infinisil** [comment]
@ShamrockLee Yeah I think that would be too noisy. Warnings/traces should only be displayed if it's actually something potentially dangerous that the user should know. But in this case, with how the above PR is implemented, it should be reasonably safe to not need that.
