### ISSUE TITLE
Package request: mouse-actions-gui

### ISSUE THREAD

**Issue by waldman** [NixOS/nixpkgs#269212]
**Project description**

mouse-actions allows to execute some commands from mouse events such as:

- Clicks / wheel on the side / corners of the screen,
- Or drawing shapes.

**Obs:** 
- There is the no-gui package request here: https://github.com/NixOS/nixpkgs/issues/264904
- This request is for implementing the `mouse-actions-gui` element so we can configure `mouse-actions`.

**Metadata**

* homepage URL: https://github.com/jersou/mouse-actions
* source URL: https://github.com/jersou/mouse-actions
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
I have some experience packaging tauri apps, I'll see what I can do
