### ISSUE TITLE
listmonk module: invalid systemd directives

### ISSUE THREAD

**Issue by ppom0** [NixOS/nixpkgs#269279]
### Describe the bug

In systemd's logs:
```
Nov 21 23:50:33 musi systemd[1]: /etc/systemd/system/listmonk.service:13: Invalid device node path 'false', ignoring.
Nov 21 23:50:33 musi systemd[1]: /etc/systemd/system/listmonk.service:26: Unknown key name 'ProtectDevices' in section 'Service', ignoring.
Nov 21 23:50:33 musi systemd[1]: /etc/systemd/system/listmonk.service:37: Unknown key name 'SystemCallArchitecture' in section 'Service', ignoring.
```

### Steps To Reproduce
1. Enable listmonk
2. Watch systemd's logs

### Expected behavior

- Maybe `ProtectDevices` should be `PrivateDevices`?
- Maybe `SystemCallArchitecture` should be `SystemCallArchitectures`?
- Maybe `DeviceAllow` should be deleted? Quoting `systemd.resource-control (5)`: *When access to all physical devices should be disallowed, PrivateDevices= may be used instead.*

Thanks for this cool NixOS module by the way!

### Notify maintainers

@RaitoBezarius

**Comment by RaitoBezarius** [comment]
Yep, will send a fix soon.
