### ISSUE TITLE
python311Packages.cherrypy error: cherrypy-18.8.0 not supported for interpreter python3.11

### ISSUE THREAD

**Issue by nanophilip** [NixOS/nixpkgs#269346]
### Describe the bug
`nix-shell -p python311Packages.cherrypy` gives `error: cherrypy-18.8.0 not supported for interpreter python3.11`. 

### Steps To Reproduce
1. `nix-shell -p python311Packages.cherrypy`

### Expected behavior
A Nix shell with python311Packages.cherrypy available to use.

### Additional context
I am not sure if this is an upstream issue. https://docs.cherrypy.dev/en/latest/install.html#supported-python-version

### Notify maintainers
@fabaff 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.05 (Stoat), 23.05.4930.f741f8a83991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by natsukium** [comment]
We have already supported python 3.11 since 4 months ago.
https://github.com/NixOS/nixpkgs/commit/258a83f9e79d76726cf04eb27901aed7fb47daf6
