### ISSUE TITLE
Installing nixpkgs.ccl does not give me a ccl binary

### ISSUE THREAD

**Issue by listx** [NixOS/nixpkgs#26934]
## Issue description

I don't get `ccl` in my path after `nix-env -iA nixpkgs.ccl`. Looking at the tree output of /nix/store/r8406pn0ngfmwpvlza45ghqlhgk52j5b-ccl-1.11 I see some binaries named `ccl` and `ccl64` that should be installed into my PATH, but are not. FWIW my PATH is 

```
/home/l/bin:/run/wrappers/bin:/run/wrappers/bin:/home/l/.nix-profile/bin:/home/l/.nix-profile/sbin:/home/l/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec
```

### Steps to reproduce

`nix-env -iA nixpkgs.ccl`

## Technical details

* System: 17.03.873.0c041520c3 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.873.0c041520c3"
* Sandboxing enabled: build-use-sandbox = false

**Comment by vcunat** [comment]
The package only contains `bin/lx86cl64`.  The same goes for current nixpkgs master. /cc maintainers: @7c6f434c, @muflax, @tohl.

**Comment by 7c6f434c** [comment]
Well, I looked at their installation page and they seem to be basically recommending to run `lx86cl64` directly. I am OK with simply adding a symlink from `ccl` to whatever executable CCL installs on the current platform, editing the `ccl` script seems to be more hassle than use…

**Comment by tohl** [comment]
ccl symlink added in patch via email id:878tkcc5u3.fsf@logand.com

**Comment by tohl** [comment]
> ccl symlink added in patch via email id:878tkcc5u3.fsf@logand.com

hmm what happens if I send the patch here?  let's see

**Comment by falsifian** [comment]
Hi @tohl,

If you want to send the patch via Github's standard mechanism, you're almost there. There are just two more things you need to do:
* Make a new branch pointing to your commit.
* Use Github's UI to make a pull request to merge your branch into the NixOS master branch.

You can verify that it's worked by checking https://github.com/NixOS/nixpkgs/pulls --- your pull request will be listed there.

We do also accept patches via the mailing list, but since you seem happy to use Github let's see if we can make it work here.

**Comment by listx** [comment]
Thank you all for responding so swiftly! My bad for not looking closely enough at the package to find `bin/lx86cl64`, doh.

**Comment by vcunat** [comment]
I think tohl knows how it's done :-) https://github.com/NixOS/nixpkgs/pulls?utf8=✓&q=is:pr%20author:tohl

It seems safe so I picked to 17.03 as well.

**Comment by tohl** [comment]
Hi James,

> You can verify that it's worked by checking
> https://github.com/NixOS/nixpkgs/pulls

thats useful info, thank you.

> * Use Github's UI to make a pull request to merge your branch into the
> NixOS master branch.

Is there a way to create PR without web browser?  I haven't found any
yet.

> We do also accept patches via the mailing list, but since you seem
> happy to use Github let's see if we can make it work here.

The patch on the github bug tracker was sent via Email without the need
for a web browser.  I was not sure if it was better just sending the
patch on the mailing list or directly to to the issue so I tried both
and created a bit of chaos.  Sorry about that.

**Comment by vcunat** [comment]
@tohl: the `gitAndTools.hub` package provides `hub pull-request` command, but I've never tried it.

**Comment by kirelagin** [comment]
> `hub pull-request` command

I use it all the time. Highly recommend. 👌

**Comment by tohl** [comment]
Thanks, gitAndTools.hub looks like what I am after.
