### ISSUE TITLE
Can't figure out how to install pip programs

### ISSUE THREAD

**Issue by omrisim210** [NixOS/nixpkgs#26933]
## Issue description
I'd like to install [pywal](https://github.com/dylanaraps/pywal) but the installation says to install it using `pip`. I can't seem to install it.

### Steps to reproduce
`pip` does not exist on `$PATH` even though I installed `nixos.python` and `python` brings up the python 2.7 REPL.

## Technical details

* System: NixOS: `17.09`
* Nix version: `1.11.10`
* Nixpkgs version: `17.09pre109180.0d4431cfe9`
* Sandboxing enabled: no

**Comment by listx** [comment]
See 9.11.3.7. How to consume python modules using pip in a virtualenv like I am used to on other Operating Systems ? in the nixpkgs manual https://nixos.org/nixpkgs/manual/#python

**Comment by omrisim210** [comment]
Will that work and/or be viable for program-type packages? I don't need any of the API (if pywal even exposes an API), I just want to invoke it from the command-line

**Comment by FRidh** [comment]
@omrisim210 use `buildPythonApplication`. `git grep buildPythonApplication` for examples.

**Comment by Mic92** [comment]
pip is in `pythonPackages.pip` not in `python`.

**Comment by larver-imvu** [comment]
@omrisim210  If you are willing to use nix-shell as described in 9.11.3.7, then yes it works for programs as well as libraries. I personally put `pylint` in my `requirements.txt` to invoke the `pylint` command line program.

**Comment by FRidh** [comment]
Closing because multiple solutions to the question have been given and because its not a Nixpkgs issue.
