### ISSUE TITLE
gdm core dumps with budgie-desktop because of missing xwayland-allow-byte-swapped-clients in mutter gsettings schema

### ISSUE THREAD

**Issue by m5x** [NixOS/nixpkgs#269446]
### Describe the bug
Budgie desktop stopped working a few months ago on `nixpkgs-unstable` because `mutter` gsettings schema supplied by Budgie is missing settings `xwayland-allow-byte-swapped-clients` which was recently added to `mutter`. This causes `gdm` to crash during startup making Budgie DE setup unusable.

### Steps To Reproduce
1. Build budgie-desktop from `nixpkgs-unstable`.
2. Reboot.

### Notify maintainers
@FedericoSchonborn

**Comment by FedericoSchonborn** [comment]
> This causes `gdm` to crash during startup making Budgie DE setup unusable.

Are you using Budgie alongside another desktop? Otherwise LightDM is the preferred choice for Budgie, but I will still look into this.

**Comment by m5x** [comment]
Oh, I didn't know that. When I switched from gnome to budgie, I kept `gdm` and everything worked, so I kept it. I can confirm that if I use `lightdm`, everything works.
