### ISSUE TITLE
Update request: woodpecker-server 1.0.5 → 2.0.0

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#269499]
- Package name: woodpecker-server
- Latest released version: 2.0.0

- Current version on the unstable channel: 1.0.5
- Current version on the stable/release channel: 0.15.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
 
There is https://github.com/NixOS/nixpkgs/pull/267320 but I'm not sure if that is still being worked on as it was created before the 2.0.0 release.

**Notify maintainers**

@ambroisie @techknowlogick @adamcstephens 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ambroisie** [comment]
Yes I already have the release candidate in a draft (#267320), the 2.0 will come soon ™.

**Comment by raspher** [comment]
#285385

    Current version on the unstable channel: 2.3.0
    Current version on the stable/release channel: 1.0.5

**Comment by ambroisie** [comment]
The stable channel will not receive a backport, the v2 contains (minor) breaking changes.
