### ISSUE TITLE
bcachefs: can't mount multi-device FS by UUID

### ISSUE THREAD

**Issue by chayleaf** [NixOS/nixpkgs#269401]
### Steps To Reproduce

1. add `"bcachefs"` to `supportedFilesystems` and reboot
2.
```bash
bcachefs format --background_compression=zstd --errors=ro --replicas=2 --foreground_target=ssd --promote_target=ssd --discard --label=ssd.ssd1 /dev/sda --discard --label=ssd.ssd2 /dev/sdb --discard --label=ssd.ssd3 /dev/sdc
```
3.
```bash
mkdir -p /mnt
mount -t bcachefs "UUID=$(bcachefs show-super /dev/sda | grep Ext | awk '{print$3}')" /mnt
```
4. mount doesn't work, dmesg: `bch2_fs_open() bch_fs_open err opening /dev/sdb: insufficient_devices_to_start`

### Expected behavior
Mount works

### Additional context

My nixpkgs branch (based on early 23.11): https://github.com/chayleaf/nixpkgs/tree/dbe92cbf44795892d585afc540a9324d773553c8

```
$ bcachefs version
bcachefs tool version 1.3.3
$ uname -a
Linux server 6.7.0-rc2 #1-NixOS SMP Tue Jan  1 00:00:00 UTC 1980 aarch64 GNU/Linux
```

### Notify maintainers

@YellowOnion @Madouura 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by YellowOnion** [comment]
> insufficient_devices_to_start

This looks like an upstream issue, do only some of your devices show up in `blkid` or `lsblk` with that UUID?

maybe udev needs a trigger for non-partition disks.

try ` udevadm settle` before calling mount, or just use "/dev/sda:/dev/sdb"

**Comment by chayleaf** [comment]
> This looks like an upstream issue, do only some of your devices show up in blkid or lsblk with that UUID?

```bash
# blkid
...
/dev/sda: UUID="29ea4586-1f72-4227-8663-60e40f0e87c9" BLOCK_SIZE="512" UUID_SUB="60c90ab6-90b3-4c14-b3bf-4c41ee9907ba" TYPE="bcachefs"
/dev/sdb: UUID="29ea4586-1f72-4227-8663-60e40f0e87c9" BLOCK_SIZE="512" UUID_SUB="cefe3e33-6cf5-428b-b393-045390eb9fc1" TYPE="bcachefs"
/dev/sdc: UUID="29ea4586-1f72-4227-8663-60e40f0e87c9" BLOCK_SIZE="512" UUID_SUB="f2b325a6-e474-47c7-a3b4-2cddd4146251" TYPE="bcachefs"
```

> try `udevadm settle` before calling mount, or just use "/dev/sda:/dev/sdb"

`udevadm settle` doesn't work. "/dev/sda:/dev/sdb" does, but it wouldn't work in initrd, because the initrd currently only uses the first device (`/dev/sda` in this case)

**Comment by chayleaf** [comment]
actually there seem to be no initrd problems as it correctly only uses the first devices for unlocking, so I'll close this

**Comment by chayleaf** [comment]
this doesn't work with systemd, because systemd says for `Timed out waiting for device /dev/sda:/dev/sdb:/dev/sdc`

**Comment by YellowOnion** [comment]
@chayleaf bcachefs mount is really dumb it just creates the multi device string internally by looking up the UUIDs, this is specifically something with your system so it's hard for me to debug, guys here want to drop the initrd scripts and use systemd so I don't know how much energy I want to spend on an ad-hoc assemble script, and with the way you're talking it looks like it might be something else other than a race condition soon after boot too. Can you report it upstream? If you're any good with gdb maybe hook it up and see what's happening. If you're any good with rust remove the gag code and splatter around prints to see what's happening.

**Comment by chayleaf** [comment]
I've tested it with systemd - it can neither mount `UUID=...` (probably because it uses `bcachefs-tools` which doesn't detect all 3 devices) nor `/dev/...:/dev/...` (for obvious reasons of there not being such a device). If it's a bcachefs-tools issue, I'll dig into its code.

**Comment by YellowOnion** [comment]
@chayleaf yeah systemd doesn't support the multidevice string stuff, been an open issue for a few years, I boot multidevice, non-encrypted using UUID= syntax and haven't seen any issues yet, so it's more of an issue with encryption, unlock probably needs UUID support, I would recommend using bcachefs on-top of LUKS for now, bcachefs hasn't been audited, and there's a few holes like the superblock is plain and has a simple crc not a hmac applied, and nocow doesn't encrypt because it's fundimentally at odds with how bcachefs does encryption. make sure you've cherry picked all of the bcachefs patches for nixpkgs, from either master or not. bcachefs-tools needs heaps of work, I already pushed a patch to the kernel adding a replacement for that god-awful gag hack that doesn't work.

**Comment by chayleaf** [comment]
I'm not using any encryption at the moment (see the command in the initial post) and it still doesn't work. Thanks for the LUKS tip though.

I'll report back after checking bcachefs-tools

**Comment by chayleaf** [comment]
so the actual issue seems to be that `mount.bcachefs UUID=088a3d70-b54c-4437-8e01-feda6bfb7236 /mnt` works, `bcachefs mount UUID=088a3d70-b54c-4437-8e01-feda6bfb7236 /mnt` works, but `mount -t bcachefs UUID=088a3d70-b54c-4437-8e01-feda6bfb7236 /mnt` doesn't. I guess this is an util-linux issue then

**Comment by YellowOnion** [comment]
@chayleaf Sorry late reply, Could you report this to util-linux guys? they might need a dump of your superblock to figure out why it can't read it.
