### ISSUE TITLE
Configuring Yazi through Home Manager

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#269489]
### Describe the bug
I'm having trouble configuring the yazi file manager through Home Manager. Specifically, I can't enable Nushell integration despite following the instructions. If I add `enableNushellIntegration = true;`, I get:
```
Error:   × Deprecated command
    ╭─[/home/clover/.config/nushell/config.nu:26:1]
 26 │ 
 27 │ def-env ya [] {
    · ───┬───
    ·    ╰── `def-env` is deprecated and will be removed in 0.88.
 28 │   let tmp = (mktemp -t "yazi-cwd.XXXXX")
    ╰────
  help: Use `def --env` instead
```

If I do not add that line, I get:
```
× External command failed
   ╭─[entry #3:1:1]
 1 │ yazi
   · ──┬─
   ·   ╰── core dumped
   ╰────
  help: Aborted: child process 'yazi' core dumped
```

### Steps To Reproduce
1. Enable yazi through home manager;
2. Run nixos rebuild switch;
3. Try to open yazi.

### Expected behavior
It should open without any errors.

### Additional context
In addition to resolving the current issue with Yazi and Nushell, it would be awesome to have the "extraConfig" option added for this package. This would allow for more customization and usability with its configuration.

### Notify maintainers

@XYenon 
@matthiasbeyer 

### Metadata
```
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231119.e4ad989`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kraftnix** [comment]
This is a `home-manager` issue, not a `nixpkgs` issue, there is nothing that can be changed in this repo to resolve your issue. Please submit an issue to https://github.com/nix-community/home-manager/issues.

To add to the issue at hand, this is because home-manager's yazi module is using old nushell bindings (as stated by the error message).

**Comment by matthiasbeyer** [comment]
As @kraftnix said, not our issue. Closing this therefore.
