### ISSUE TITLE
fsautocomplete: doesn't attach to NixVim (neovim) since upgrade

### ISSUE THREAD

**Issue by MikaelFangel** [NixOS/nixpkgs#269448]
### Describe the bug
After the upgrade to 0.68.0 fsautocomplete no longer attach properly to NixVim (neovim).

### Steps To Reproduce
1. Create a minimal NixVim config enable fsautocomplete and Ionide-vim
2. Open a .fsx file 
3. Run the LspInfo command a see the missing id

### Expected behavior
The clients get associated with an id as before.

### Screenshots
Version 0.67.0 
![20231123_15h28m52s_grim](https://github.com/NixOS/nixpkgs/assets/34864484/bcf3bdde-e883-476d-9f74-447aeab49984)

Version 0.68.0
![20231123_15h28m00s_grim](https://github.com/NixOS/nixpkgs/assets/34864484/4c4d8afd-0957-4acd-975f-a43c5ca41103)

### Additional context
I haven't explored if the problem persists outside NixVim, but I would strongly suspect it does, as there haven't been any major changes in NixVim lately.

### Notify maintainers

@kirillrdy @mdarocha 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231119.e4ad989`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(mikael): `""`
 - nixpkgs: `/nix/store/z7y28qzhk7driiwcw78k0mb24laknm0f-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
@MikaelFangel I can confirm you findings. It's an issue with 0.68.0. I'll do some more investigation before filing an issue upstream.

for now, you can pin you fsautocomplete to 0.67.0

**Comment by MikaelFangel** [comment]
I've just been testing it a bit as well and came to the same conclusion that it is an upstream problem. I reconfigured my nixvim to build the `fsautocomplete` from the nuget package and that one has the same issue.

How do I pin fsautocomplete in nixvim? 😅

**Comment by kirillrdy** [comment]
> I've just been testing it a bit as well and came to the same conclusion that it is an upstream problem. I reconfigured my nixvim to build the `fsautocomplete` from the nuget package and that one has the same issue.
> 
> How do I pin `fsautocomplete` in nixvim? 😅

sorry I am not familiar with nixvim, my neovim just calls fsautocomplete from PATH. So I've just installed an old version via

thats the commit just before 0.68.0 update
```
nix profile install github:nixos/nixpkgs/255ff0f5e98e6dc8e7bd8f0d21315f865833de79#fsautocomplet
```

**Comment by kirillrdy** [comment]
@MikaelFangel are you able to test https://github.com/NixOS/nixpkgs/pull/269502 ?

**Comment by MikaelFangel** [comment]
Working on it.
