### ISSUE TITLE
Update request: gnomeExtensions.gsconnect 55 → 56

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#269566]
- Package name: gnomeExtensions.gsconnect
- Latest released version: 56

- Current version on the unstable channel: 55
- Current version on the stable/release channel: 55

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NixOS/gnome 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/269668
