### ISSUE TITLE
cron package fails with permission error.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#26957]
## Issue description

Can't install/build the cron package.

### Steps to reproduce

`nix-shell -p cron` produces the following:

    ➤ nix-shell -p cron
    these derivations will be built:
      /nix/store/gyfvz484jbwd1fj11zsfwmpim6w2d9kh-cron-4.1.drv
    building path(s) ‘/nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1’
    unpacking sources
    unpacking source archive /nix/store/vbbz46rch40hgx610xj2l7ajwwfx32ax-cron_4.1.shar
    x - README
    x - CHANGES
    x - FEATURES
    x - INSTALL
    x - CONVERSION
    x - THANKS
    x - MAIL
    x - bitstring.3
    x - crontab.5
    x - crontab.1
    x - cron.8
    x - putman.sh
    x - Makefile
    x - bitstring.h
    x - cron.h
    x - config.h
    x - pathnames.h
    x - externs.h
    x - macros.h
    x - structs.h
    x - funcs.h
    x - globals.h
    x - cron.c
    x - crontab.c
    x - database.c
    x - do_command.c
    x - entry.c
    x - env.c
    x - job.c
    x - user.c
    x - popen.c
    x - misc.c
    x - pw_dup.c
    source root is cron
    setting SOURCE_DATE_EPOCH to timestamp 1498724651 of file cron/user.c
    warning: file cron/user.c may be generated; SOURCE_DATE_EPOCH may be non-deterministic
    patching sources
    configuring
    no configure script, doing nothing
    building
    make flags: SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash DESTROOT=/nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1   
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o cron.o cron.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o database.o database.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o user.o user.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o entry.o entry.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o job.o job.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o do_command.o do_command.c
    do_command.c: In function 'child_process':
    do_command.c:97:2: warning: ignoring return value of 'pipe', declared with attribute warn_unused_result [-Wunused-result]
      pipe(stdin_pipe); /* child's stdin */
      ^
    do_command.c:98:2: warning: ignoring return value of 'pipe', declared with attribute warn_unused_result [-Wunused-result]
      pipe(stdout_pipe); /* child's stdout */
      ^
    do_command.c:243:3: warning: ignoring return value of 'setgid', declared with attribute warn_unused_result [-Wunused-result]
       setgid(e->pwd->pw_gid);
       ^
    do_command.c:248:3: warning: ignoring return value of 'setuid', declared with attribute warn_unused_result [-Wunused-result]
       setuid(e->pwd->pw_uid); /* we aren't root after this... */
       ^
    do_command.c:251:3: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
       chdir(env_get("HOME", e->envp));
       ^
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o misc.o misc.c
    misc.c: In function 'set_cron_cwd':
    misc.c:258:4: warning: ignoring return value of 'chown', declared with attribute warn_unused_result [-Wunused-result]
        chown(SPOOL_DIR, -1, grp->gr_gid);
        ^
    misc.c: In function 'acquire_daemonlock':
    misc.c:328:2: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
      (void) ftruncate(fd, num);
      ^
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o env.o env.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o popen.o popen.c
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o pw_dup.o pw_dup.c
    gcc -Wall -Wno-unused -Wno-comment  -o cron cron.o database.o user.o entry.o job.o do_command.o misc.o env.o popen.o pw_dup.o 
    gcc -Wall -Wno-unused -Wno-comment -g -I.    -c -o crontab.o crontab.c
    crontab.c: In function 'edit_cmd':
    crontab.c:479:4: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
        (void) fgets(q, sizeof q, stdin);
        ^
    crontab.c: In function 'replace_cmd':
    crontab.c:562:2: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
      ftruncate(fileno(tmp), ftell(tmp)); /* XXX redundant with "w+"? */
      ^
    gcc -Wall -Wno-unused -Wno-comment  -o crontab crontab.o misc.o entry.o env.o pw_dup.o 
    installing
    install flags: install SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash DESTROOT=/nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1   
    install -c -m  755  -s cron    /nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1/sbin/
    install -c -m 4755  -s crontab /nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1/bin/
    install: cannot change permissions of '/nix/store/y1g9qxxk6i2b0al4g5hk0lz4jhr9dxpr-cron-4.1/bin/crontab': Operation not permitted
    make: *** [Makefile:114: install] Error 1
    builder for ‘/nix/store/gyfvz484jbwd1fj11zsfwmpim6w2d9kh-cron-4.1.drv’ failed with exit code 2
    error: build of ‘/nix/store/gyfvz484jbwd1fj11zsfwmpim6w2d9kh-cron-4.1.drv’ failed
    /run/current-system/sw/bin/nix-shell: failed to build all dependencies

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03.1395.9b948ea439 (Gorilla)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.11`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`17.03.1437.a2c7482319`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

**Comment by emmanuelrosa** [comment]
See #26600

**Comment by seanparsons** [comment]
@emmanuelrosa Ah nuts, I even searched for cron and the name of the error.
