### ISSUE TITLE
Package request: LocalAI

### ISSUE THREAD

**Issue by jakehamilton** [NixOS/nixpkgs#269582]
**Project description**

The free, Open Source OpenAI alternative. Self-hosted, community-driven and local-first. Drop-in replacement for OpenAI running on consumer-grade hardware. No GPU required. Runs ggml, gguf, GPTQ, onnx, TF compatible models: llama, llama2, rwkv, whisper, vicuna, koala, cerebras, falcon, dolly, starcoder, and many others

**Metadata**

* homepage URL: https://localai.io/
* source URL: https://github.com/mudler/LocalAI
* license: mit
* platforms: linux

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RemcoSchrijver** [comment]
Uses a large amount of dependencies as well as many different quantized models. So it might be a good start to first take stock of which are already supported. For now a work around would be to use the docker image.

**Comment by ck3d** [comment]
I packaged local-ai in my repository https://github.com/ck3d/nix-local-ai/blob/main/local-ai/default.nix
If somebody want to migrate the package to nixpkgs, I could maintain the package.
The cuda support switch should be handled in a more nixpkgs way to configure.

**Comment by teto** [comment]
would it make sense to move it to https://github.com/nixified-ai/flake ? nixified-ai has a binary cache and this could help provide a unified way to deal with nvidia/cuda. I have no relationship with nixified whatsoever but that seemed like a good destination.

**Comment by jakehamilton** [comment]
@ck3d I've given your package a test and it looks like it's working with this base systemd service that I've written!

https://github.com/jakehamilton/config/blob/main/modules/nixos/services/local-ai/default.nix

**Comment by onny** [comment]
took the code from here and opened a PR https://github.com/NixOS/nixpkgs/pull/288269
