### ISSUE TITLE
qbittorrent: terminated by signal SIGTRAP (Trace or breakpoint trap)

### ISSUE THREAD

**Issue by LudovicoPiero** [NixOS/nixpkgs#269589]
### Describe the bug
I encountered this error when attempting to open files from qBittorrent:
```console
(qbittorrent:196145): GLib-GIO-ERROR **: 17:21:38.808: No GSettings schemas are installed on the system
fish: Job 1, 'qbittorrent' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
It's working fine on `qbittorrent-qt5`.

### Steps To Reproduce
  1.  Run nix shell nixpkgs#qbittorrent.
  2. Open qBittorrent.
  3. Navigate to Files -> Add torrent files.
  4. The app crashes.

### Expected behavior
It should open my File Manager.

### Notify maintainers
 @Anton-Latukha @kashw2 @paveloom 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2-cachyos, NixOS, 23.11 (Tapir), 23.11.20231121.37e6adc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.19.0pre20231030_e5a5fbc`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/1zsi4q5yh56lhjy994bvr76y16207cap-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paveloom** [comment]
Seems to be a case of the first error in the [GNOME's frequently encountered errors](https://nixos.org/manual/nixpkgs/unstable/#ssec-gnome-common-issues). Would you mind trying out https://github.com/NixOS/nixpkgs/pull/269594?
