### ISSUE TITLE
Build failure: bat

### ISSUE THREAD

**Issue by RuRo** [NixOS/nixpkgs#269631]
### Steps To Reproduce

1. have a filesystem that doesn't accept non-utf8 characters
2. build `bat` (i.e. `nix build nixpkgs#bat --rebuild`)

### Build log

```
failures:

---- file_with_invalid_utf8_filename stdout ----
thread 'file_with_invalid_utf8_filename' panicked at tests/integration_tests.rs:1594:49:
can create temporary file: Os { code: 84, kind: Uncategorized, message: "Invalid or incomplete multibyte or wide character" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    file_with_invalid_utf8_filename

test result: FAILED. 109 passed; 1 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.18s

error: test failed, to rerun pass `--test integration_tests`
```

### Additional context

I think that this is a known issue with ZFS and darwin. There is precedent for this kind of issue in #205780 + #205846 and the consensus seems to be that it is acceptable to just disable such tests. Also, see #269506.

I have verified that adding `--skip=file_with_invalid_utf8_filename` to `checkFlags` fixes the issue.

### Notify maintainers

@dywedir
@lilyball
@zowoq
@SuperSandro2000

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RuRo** [comment]
Upstream has already rejected fixing this in sharkdp/bat#2045, so we'll have to keep this in nixpkgs or convince upstream to accept a fix.

**Comment by SuperSandro2000** [comment]
> I think that this is a known issue with ZFS and darwin.

I just tested this on a ZFS machine and I couldn't reproduce it, so yet again apples annoying filesystem strikes us.

**Comment by RuRo** [comment]
> I just tested this on a ZFS machine and I couldn't reproduce it, so yet again apples annoying filesystem strikes us.

You have to create the dataset with the `utf8only` (or alternatively `normalization`) property enabled. This is not the default, however the official ZFS docs recommend this setting. Also you might need to have `/tmp` be in the same dataset instead of a `tmpfs`.

I am on NixOS, not Darwin, but one of the issues I linked claims that Darwin users are also sometimes affected by this problem (no relation to ZFS in that case).

Sorry, if my original description wasn't clear.

**Comment by SuperSandro2000** [comment]
> You have to create the dataset with the `utf8only` (or alternatively `normalization`) property enabled.

I have that and normalization set to formD.

> Also you might need to have `/tmp` be in the same dataset instead of a `tmpfs`.

I think I grabbed the one machine where I have this as the others have to little RAM. Good catch.



> Ideally, we should disable this test for everyone since the choice of the filesystem is orthogonal to whether it's Darwin or NixOS or whatever.

Yeah, thanks for the explanations! Then we just disable it for everyone and be done with it.
