### ISSUE TITLE
Not possible to use multiple layouts in services.xserver.layout

### ISSUE THREAD

**Issue by rickynils** [NixOS/nixpkgs#26961]
cc @aszlig 

## Issue description
Not possible to use multiple layouts in `services.xserver.layout`:

```
building path(s) ‘/nix/store/zliji90zqz5rc8rfl19ya7qp9nyn7r4b-xkb-layouts-exist’

The selected keyboard layout definition does not exist:

  de,us

Set `services.xserver.layout' to the name of an existing keyboard
layout (check /nix/store/5nidmghgw700wkj4pycg9a80q25qbxzb-xkeyboard-config-2.21/etc/X11/xkb/rules/base.lst for options).
```

This is possible in the release-17.03 master, and also advertised in the option description: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/xserver.nix#L298

### Steps to reproduce
Set the NixOS option `services.xserver.layout` to a comma-separated list of layouts (like `us,se`)

## Technical details

* Nixpkgs version: master (a6cf6367e2abd9610da804286cc6c439d79717db)

**Comment by themoritz** [comment]
Can confirm, same here
