### ISSUE TITLE
Update request: gnomeExtensions.pop-shell unstable-2023-04-27 → unstable-2023-11-10

### ISSUE THREAD

**Issue by the-furry-hubofeverything** [NixOS/nixpkgs#269687]
- Package name: gnome-shell-extension-pop-shell
- Latest released version: unstable-2023-11-10

- Current version on the unstable channel: unstable-2023-04-27
- Current version on the stable/release channel: unstable-2023-04-27

This brings about Gnome 45 support, as far as I know.

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@genofire 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by genofire** [comment]
thanks for alle the involved to fix it so fast
