### ISSUE TITLE
Build failure: gnome.zenity (cross-compile to aarch64-linux)

### ISSUE THREAD

**Issue by mikatammi** [NixOS/nixpkgs#269706]
### Steps To Reproduce

Either on `nixos-23.11` or `nixos-unstable` -branch:

1. nix build .#legacyPackages.x86_64-linux.pkgsCross.aarch64-multiplatform.gnome.zenity
error: builder for '/nix/store/fly8a60nn82k9v07yl751rdj2apnxgr1-qtsvg-5.15.11.drv' failed with exit code 1;
       last 3 log lines:
       > Error: detected mismatched Qt dependencies:
       >     /nix/store/pgdx2hvksknbfyvkflx0ii43cixsmvqz-qtbase-5.15.11-dev
       >     /nix/store/4xgqp5cl5f2xybzavy99z3z30margwd7-qtbase-5.15.11-dev
       For full logs, run 'nix log /nix/store/fly8a60nn82k9v07yl751rdj2apnxgr1-qtsvg-5.15.11.drv'.
error: 1 dependencies of derivation '/nix/store/60bghyz9mi43w7v2fw1hziyx6344229s-python3.11-PyQt5-5.15.9.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s430q9r0xdc284ifm6v98f6ak3b7gymh-ffado-2.4.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/94xxxxswgs28kq8fbshq22qz9hdb65yj-pipewire-0.3.84.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ph7zssqfvz15ql0jfvh26cd9ha86blj0-SDL2-2.28.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0h4liqcz7w1p4qfmp6f1c21qj4a4wjy6-openal-soft-1.23.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x90xfg51rspr74pf3pqvcyjyz6i85p16-gst-plugins-bad-1.22.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nzcrajcrsv4yndy641vlshv5pw596l48-gtk4-4.12.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6nswr88l9lg2ywvn9pv8g68kiw3f847l-wrap-gapps-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fm2j4gkqbn4b7hf39lg5zl901dkr4v6v-zenity-aarch64-unknown-linux-gnu-3.99.2.drv' failed to build

### Build log

```
Error: detected mismatched Qt dependencies:
    /nix/store/pgdx2hvksknbfyvkflx0ii43cixsmvqz-qtbase-5.15.11-dev
    /nix/store/4xgqp5cl5f2xybzavy99z3z30margwd7-qtbase-5.15.11-dev
```

### Additional context

The problem does not appear on NixOS 23.05. I'm not sure if the problem is in zenity or GNOME, or is it in some of the dependency packages zenity uses like PyQt5.

### Notify maintainers

@NixOS/gnome

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 23.05 (Stoat), 23.05.4930.f741f8a83991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mikatammi** [comment]
Notifying GNOME maintainers:
@bobby285271 @hedning @jtojnar @dasj19 @amaxine

**Comment by jtojnar** [comment]
That looks more like a Qt issue.

**Comment by Artturin** [comment]
Created https://github.com/NixOS/nixpkgs/issues/269756

**Comment by avnik** [comment]
@Artturin but why zenity depends on qt*? It pure gtk4+adwaita app, it shouldn't

**Comment by Artturin** [comment]
> @Artturin but why zenity depends on qt*? It pure gtk4+adwaita app, it shouldn't

You can see the dependency graph in the error

**Comment by jtojnar** [comment]
It is just a build-time dependency – it is needed for `ffado.bin` but is not actually used by runtime closure.
