### ISSUE TITLE
Build failure: postgresql_14.pkgs.timescaledb_toolkit

### ISSUE THREAD

**Issue by c0deaddict** [NixOS/nixpkgs#269710]
### Steps To Reproduce

timescaledb_toolkit is broken since this merge https://github.com/NixOS/nixpkgs/commit/a7a8f8253db3f32cc15baf527d36ef7171425eba

1. git clone https://github.com/NixOS/nixpkgs.git
2. git checkout a7a8f8253db3f32cc15baf527d36ef7171425eba # or later
3. nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; postgresql_14.pkgs.timescaledb_toolkit' 

### Build log

local build log is identical to https://hydra.nixos.org/build/242080658

### Additional context

The extension fails to build for all postgres versions.

I read about timescaledb_toolkit / pgx that some pgx has a bug with some bindgen versions, perhaps the rust builder update moved bindgen to one of those versions? 

### Notify maintainers

@typetetris 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.12, NixOS, 24.05 (Uakari), 24.05.20231122.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/yby4v087byizcja1nji5dj61qkdj5kk1-nixpkgs-patched-19cbff5`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yrd** [comment]
Bisected this to 9ed7bfe46bf193e55a6fd8ae89dfe54b4dca2c18

**Comment by c0deaddict** [comment]
Thanks for finding the culprit @yrd I tried to somehow pin the llvmPackages version in the build of the package but couldn't figure out how. Eventually I tried upgrading the package to the latest version and got that working, so hopefully that can get merged and this can be solved :)

**Comment by c0deaddict** [comment]
Yes, sorry forgot about this.
