### ISSUE TITLE
GNOME Shell browser integration needs native host connector

### ISSUE THREAD

**Issue by jameysharp** [NixOS/nixpkgs#26981]
## Issue description

I want to use <https://extensions.gnome.org/> to install gnome-shell extensions in my GNOME 3 desktop environment, but the site currently reports that "Although GNOME Shell integration extension is running, native host connector is not detected."

### Steps to reproduce

I set these options in `/etc/nixos/configuration.nix`:

```
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
```

and installed firefox-54.0 using `nix-env`.

Visiting <https://extensions.gnome.org/> then told me to install the [Firefox "GNOME Shell integration" add-on](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/), which I did using the in-browser "Add to Firefox" button.

Visiting the GNOME Shell extensions site again, it now says, "Although GNOME Shell integration extension is running, native host connector is not detected."

## Technical details

* System: NixOS 17.03.1447.9e5a13f6f1 (Gorilla)
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1447.9e5a13f6f1
* Sandboxing enabled: false

I spent a little while trying to figure out how to write a nix expression to build the native host connector, modeling it after the documented [instructions for building chrome-gnome-shell from source](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Cmake_installation), but I don't understand D-Bus services and such well enough. Also, this is my first nix packaging experiment...

Still, in case it might help, here's as far as I got:

```
with import <nixpkgs> {};

let
  name = "chrome-gnome-shell";
  version = "9";
  src = fetchurl {
    url = "https://git.gnome.org/browse/chrome-gnome-shell/snapshot/${name}-${version}.tar.xz";
    sha256 = "0j6lzlp3jvkpnkk8s99y3m14xiq94rjwjzy2pbfqgv084ahzmz8i";
  };

  python = pkgs.pythonPackages;
in
python.buildPythonApplication {
  inherit name version src;
  sourceRoot = "${name}-${version}/connector";

  propagatedBuildInputs = [ python.pygobject3 python.requests2 ];

  postInstall = ''
    sed 's!\''${CMAKE_INSTALL_FULL_BINDIR}!'"$out/bin!" org.gnome.ChromeGnomeShell.service.in > $out/bin/org.gnome.ChromeGnomeShell.service
  '';
}
```

**Comment by ixxie** [comment]
I was wondering about this, and it seems @dyrnade has [already packaged](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix) it; I guess you need to be on unstable to use it now though.

**Comment by jameysharp** [comment]
Awesome, closing in favor of #24283 then. Thanks for pointing that out!

**Comment by fusion809** [comment]
I have chrome-gnome-shell installed and I'm still getting this problem. Am I the only one in this?

**Comment by neilmayhew** [comment]
I have this error too. I was able to get a little further by symlinking:

```bash
ln -s ~/.nix-profile/usr/lib64/mozilla/native-messaging-hosts ~/.mozilla
```

However, now the web site says, "An unexpected error occurred". When I try to run the connector directly, I get:

```bash
$ ~/.nix-profile/usr/bin/chrome-gnome-shell 
[26341] Uncaught exception of type <class 'GLib.Error'> occured
  File "/nix/store/8mzhd5ak2mqqfrj8wdxpvxz4fvn1bi50-chrome-gnome-shell/usr/bin/.chrome-gnome-shell-wrapped", line 568, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/nix/store/8mzhd5ak2mqqfrj8wdxpvxz4fvn1bi50-chrome-gnome-shell/usr/bin/.chrome-gnome-shell-wrapped", line 73, in __init__
    self.register()
[26341] Exception: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.ChromeGnomeShell was not provided by any .service files (2)
```

There is an appropriate `.service` file:

```bash
$ ls -l ~/.nix-profile/usr/share/dbus-1/services/
total 4
-r--r--r-- 1 root root 166 Dec 31  1969 org.gnome.ChromeGnomeShell.service
```

but presumably it's not on the right source path. I tried patching the derivation to put the build products directly in the store directory instead of in a `usr/` subdirectory:

```diff
diff --git a/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix b/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix
index bda356cf4c3..f2180e9a5f6 100644
--- a/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix
+++ b/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix
@@ -14,14 +14,14 @@ name="chrome-gnome-shell";
  preConfigure = ''
    mkdir build usr etc
    cd build
-   ${cmake}/bin/cmake -DCMAKE_INSTALL_PREFIX=$out/usr -DBUILD_EXTENSION=OFF ../
+   ${cmake}/bin/cmake -DCMAKE_INSTALL_PREFIX=$out -DBUILD_EXTENSION=OFF ../
    substituteInPlace cmake_install.cmake --replace "/etc" "$out/etc"
  '';
 
  postInstall = ''
     rm $out/etc/opt/chrome/policies/managed/chrome-gnome-shell.json
     rm $out/etc/chromium/policies/managed/chrome-gnome-shell.json
-    wrapProgram $out/usr/bin/chrome-gnome-shell \
+    wrapProgram $out/bin/chrome-gnome-shell \
       --prefix PATH : '"${dbus}/bin"' \
       --prefix PATH : '"${gnome3.gnome_shell}/bin"' \
       --prefix PYTHONPATH : "$PYTHONPATH"
```

but that didn't solve it.

BTW, I noticed (from using `strace`) that Firefox tries to open `/usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json` so maybe the extension needs tweaking for NixOS.
