### ISSUE TITLE
flacon 11.3.0 does not include sox utility

### ISSUE THREAD

**Issue by Elserjo** [NixOS/nixpkgs#269804]
### Describe the bug

After upgrade flacon from 11.2.0 to 11.3.0 i have noticed, that i can not split audiofiles anymore. Flacon informs me, that sox utility is not installed. 

### Steps To Reproduce
1. Open audio file that have cue sheet in flacon;
2.  Convert button is non active and flacon informs me about error.

### Expected behavior
flacon should have sox utility to split audio files.

**Comment by FliegendeWurst** [comment]
Fixed in #281829 :+1:
