### ISSUE TITLE
Build failure: popsicle

### ISSUE THREAD

**Issue by tormeh** [NixOS/nixpkgs#269914]
### Steps To Reproduce

1. build *popsicle*

### Build log

```
error: failed to run custom build command for `loopdev v0.4.0`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/loopdev-3cf9e2fbe30140be/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /build/cargo-vendor-dir/proc-macro2-1.0.64/src/fallback.rs:791:9:
  "enum_(unnamed_at_/nix/store/mrgib0s2ayr81xv1q84xsjg8ijybalq3-glibc-2_38-27-dev/include/linux/loop_h_16_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:107: target/release/popsicle-gtk] Error 101
error: builder for '/nix/store/j38gyif1pkr00d602raz018if9g0k7z9-popsicle-1.3.2.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/dqayy6fw1rnb9087qjhs15lnplxj8xk3-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/12s85vanbngi9h342my2s1a8ajvb656x-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/grnrz4xg062yji3y0wnsprajvixiyh5p-nixos-system-nixos-24.05beta357.19cbff58383a.drv' failed to build
```

### Additional context

Same issue here: https://github.com/NixOS/nixpkgs/issues/268450

Seems like something is wrong with the proc-macro2 crate.

### Notify maintainers

@figsoda @13r0ck 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[tormod@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.11 (Tapir), 23.11pre544052.85f1ba3e5167`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tormeh** [comment]
A new release is out that fixes the build failure. Just need to upgrade popsicle to the new version.
https://github.com/pop-os/popsicle/releases/tag/1.3.3

**Comment by raspher** [comment]
@tormeh popscile has been upgraded https://github.com/NixOS/nixpkgs/pull/286527 https://github.com/NixOS/nixpkgs/pull/286506. Is it fixed?

**Comment by tormeh** [comment]
> @tormeh popscile has been upgraded https://github.com/NixOS/nixpkgs/pull/286527 https://github.com/NixOS/nixpkgs/pull/286506. Is it fixed?
> 
> //edit: update request -> https://github.com/NixOS/nixpkgs/issues/286501

Yes, it's been fixed. Thanks!
