### ISSUE TITLE
Qt 6 is unable to pick up plugins on non-NixOS

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#270028]
### Describe the bug
Doing `nix profile install nixpkgs#qt6ct` doesn't make Qt 6 to use qt6ct despite `QT_QPA_PLATFORMTHEME=qt6ct` is set. Perhaps that's because https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.15/qtbase.patch.d/0009-qtbase-qtpluginpath.patch is not ported to Qt 6.

### Steps To Reproduce
1. `QT_QPA_PLATFORMTHEME=qt6ct`
2. `nix profile install nixpkgs#qt6ct`
3. Install & run any Qt 6 application

### Expected behavior
Application follows qt6ct settings

### Notify maintainers
@milahu @NIckCao

### Metadata

```console

 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9-lqx1, NixOS, 23.11 (Tapir), 23.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/etc/static/nixpkgs`
```
(I'm reporting this for other person)

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NickCao** [comment]
I'm aware of this issue but finding qt plugins from `PATH` is not really a good idea. Shall we just add some document around adding profile paths to `QT_PLUGIN_PATH` for working around this, just like what the nixos module does.

**Comment by ilya-fedin** [comment]
I'm not sure how would this work on non-NixOS given that
1. The path includes Qt version and there's nothing to manage that on non-NixOS
2. Setting it globally is likely to break non-nix software

**Comment by NickCao** [comment]
>     2. Setting it globally is likely to break non-nix software

Good point, I would be porting this patch to qt6 for consistency.

**Comment by ilya-fedin** [comment]
@NickCao hi, I have encountered a use-case where I have to use pkgs.replaceDependency. It correctly replaces paths in the wrapper which correctly prefixes QT_PLUGIN_PATH but sadly PATH has a preference so the globally installed plugin gets preferred over my changed one. Could the priority in the patch be changed?

PS: there's already an issue about that but for Qt 5 (#177558)

**Comment by NickCao** [comment]
There are valid use cases for both ways: users might want to replace the wrapped plugins with the ones in their PATH. I think this is even a more wide spread use case than replaceDependency. Maybe we shall add another set of environment variables with even higher precedence?

**Comment by ilya-fedin** [comment]
> There are valid use cases for both ways: users might want to replace the wrapped plugins with the ones in their PATH.

Yeah? The logic with environment variables is usually local ones overriding global ones... Isn't the only use-case of plugins from PATH to be the last resort when QT_PLUGIN_PATH doesn't contain needed plugins?

**Comment by NickCao** [comment]
> The logic with environment variables is usually local ones overriding global ones... 

Well yes, but I feel the situation is a bit different here in nixpkgs, since environment variable is the primary means of locating plugins.

> Isn't the only use-case of plugins from PATH to be the last resort when QT_PLUGIN_PATH doesn't contain needed plugins?

cc @NixOS/qt-kde

**Comment by NickCao** [comment]
Opened a PR anyway: https://github.com/NixOS/nixpkgs/pull/292237.
