### ISSUE TITLE
Sweet Home 3D not starting

### ISSUE THREAD

**Issue by Xyz00777** [NixOS/nixpkgs#270010]
### Describe the bug
Wanted to install and start sweethomed.application. the build worked without problems but when i started it, it didnt started.

### Steps To Reproduce
1. install sweethome3d.application via configuration file
2. try to start it

### Expected behavior
Starting the Application

### Screenshots
stucks at the start screen
![Screenshot_20231126_003558](https://github.com/NixOS/nixpkgs/assets/52142054/ec979a3a-a4b3-4024-97ef-bfd0e45187bd)

### Additional context
At the moment its installed in my user context. When i try to start it as my user over the terminal i get no errors. When i start it with "sudo sweethome3d" I get the following error, and it also dont start, also start at starting screen and vanishing from the task bar:

```
[xyz00777@NCC-1031:~]$ sudo sweethome3d
[sudo] password for xyz00777: 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.eteks.sweethome3d.SweetHome3DBootstrap.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
        at javax.media.j3d.GraphicsConfigTemplate3D.isGraphicsConfigSupported(GraphicsConfigTemplate3D.java:348)
        at com.eteks.sweethome3d.j3d.Component3DManager.createGraphicsConfigurationTemplate3D(Unknown Source)
        at com.eteks.sweethome3d.j3d.Component3DManager.<init>(Unknown Source)
        at com.eteks.sweethome3d.j3d.Component3DManager.getInstance(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.addComponent3DRenderingErrorObserver(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
        ... 5 more
Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1057)
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1068)
        at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:821)
        at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:131)
        at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
        at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:858)
        at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
        ... 12 more

```
I think these happens because its not installed as user, but propably it helps to find the issue.

### Notify maintainers
@edwtjo

### Metadata

```console
[xyz00777@NCC-1031:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11pre551191.51a01a7e5515`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(xyz00777): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
Starting random applications as root seems like an unwise idea.

**Comment by eclairevoyant** [comment]
Apologies, I misread the error, this appears to be a separate issue

**Comment by eclairevoyant** [comment]
Just to confirm, which GPU do you use?

**Comment by W95Psp** [comment]
I've got the same issue, and none of the solutions given in #71752 appear to work.
On my side `lspci` says my GPU is `Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]`.

**Comment by alciono** [comment]
Same problem here, on NIXOS unstable.
Stuck on the starting blue window.
Had to install it with flatpak in the mean time...

Any idea?

**Comment by Xyz00777** [comment]
sorry for delay @eclairevoyant i dont get informations from messages in last time from github... really annoying...
I have an Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]

**Comment by robsmith11** [comment]
> Mmh, I just tried with [nixGL](https://github.com/nix-community/nixGL), and things work just fine (even though I'm on NixOS + glxinfo tells me OpenGL is happy)...

Same here, also on Intel hardware.

**Comment by eclairevoyant** [comment]
Based on the NixGL idea, applying the following patch works to update to the latest version and fix the driver issue on Intel.

But this does not seem like the best way to go about it; I can't find a single other package messing with `LIBGL_DRIVERS_PATH`, and it seems more like a debugging tool than something that should be in a package.

```diff
From baafe4884033aa4900639f23338c51cd13ae9f8b Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?=C3=A9clairevoyant?=
 <848000+eclairevoyant@users.noreply.github.com>
Date: Sun, 14 Jan 2024 17:58:43 -0500
Subject: [PATCH] sweethome3d fixes/update

---
 pkgs/applications/misc/sweethome3d/default.nix | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/pkgs/applications/misc/sweethome3d/default.nix b/pkgs/applications/misc/sweethome3d/default.nix
index 3ea247f4b080..fe96f4f46186 100644
--- a/pkgs/applications/misc/sweethome3d/default.nix
+++ b/pkgs/applications/misc/sweethome3d/default.nix
@@ -13,6 +13,7 @@
 , autoPatchelfHook
 , libXxf86vm
 , unzip
+, mesa
 }:
 
 let
@@ -82,7 +83,8 @@ let
       makeWrapper ${jre8}/bin/java $out/bin/$exec \
         --set MESA_GL_VERSION_OVERRIDE 2.1 \
         --prefix XDG_DATA_DIRS : "$XDG_ICON_DIRS:${gtk3.out}/share:${gsettings-desktop-schemas}/share:$out/share:$GSETTINGS_SCHEMAS_PATH" \
-        --add-flags "-Dsun.java2d.opengl=true -jar $out/share/java/${module}-${version}.jar -cp $out/share/java/Furniture.jar:$out/share/java/Textures.jar:$out/share/java/Help.jar -d${toString stdenv.hostPlatform.parsed.cpu.bits}"
+        --add-flags "-Dsun.java2d.opengl=true -jar $out/share/java/${module}-${version}.jar -cp $out/share/java/Furniture.jar:$out/share/java/Textures.jar:$out/share/java/Help.jar -d${toString stdenv.hostPlatform.parsed.cpu.bits}" \
+        --prefix LIBGL_DRIVERS_PATH : ${lib.makeSearchPathOutput "lib" "lib/dri" [mesa.drivers]}
 
 
       # remember the store paths found inside the .jar libraries. note that
@@ -111,13 +113,13 @@ in {
 
   application = mkSweetHome3D rec {
     pname = lib.toLower module + "-application";
-    version = "6.6";
+    version = "7.2";
     module = "SweetHome3D";
     description = "Design and visualize your future home";
     license = lib.licenses.gpl2Plus;
     src = fetchurl {
       url = "mirror://sourceforge/sweethome3d/${module}-${version}-src.zip";
-      sha256 = "sha256-CnVXpmodmyoZdqmt7OgRyzuLeDhkPhrAS/CldFM8SQs=";
+      hash = "sha256-Io3HfussfSy6CLHE0JCAk0gjBAla/u+pS1Gan8BxozY=";
     };
     desktopName = "Sweet Home 3D";
     icons = {
-- 
2.42.0
```

**Comment by robsmith11** [comment]
I forgot to mention, to avoid getting terrible performance (< 1 fps), I also had to set
```JAVA_TOOL_OPTIONS="-Dcom.eteks.sweethome3d.j3d.useOffScreen3DView=true"```
Not sure if it's needed for others.  Maybe related to my using Wayland/Sway.

I also have to use `_JAVA_AWT_WM_NONREPARENTING=1` to get the window displayed properly, but that's a common issue for most Java apps and tiling windowing managers.

**Comment by bobvanderlinden** [comment]
I also ran into this issue with a Nvidia card. For me, `nixGL` was needed (with [this](https://github.com/nix-community/nixGL/pull/152) patch).

I also needed `JAVA_TOOL_OPTIONS="-Dcom.eteks.sweethome3d.j3d.useOffScreen3DView=true"`. `_JAVA_AWT_WM_NONREPARENTING=1` and `LIBGL_DRIVERS_PATH` didn't seem needed (or give noticable changes).
