### ISSUE TITLE
Update request: r2modman 3.1.44 → 3.1.45

### ISSUE THREAD

**Issue by Zettexe** [NixOS/nixpkgs#270018]
- Package name: r2modman
- Latest released version: 3.1.45

- Current version on the unstable channel: 3.1.44
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aidalgol @huantianad 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by PassiveLemon** [comment]
This can be marked as solved
