### ISSUE TITLE
Package request: gnomeExtensions.pass-search-provider

### ISSUE THREAD

**Issue by edgar-vincent** [NixOS/nixpkgs#270012]
**Project description**

`pass-search-provider` is a search provider for Gnome Shell which adds support for searching passwords from pass, among others.

**Metadata**
* homepage URL: https://github.com/jle64/gnome-pass-search-provider
* source URL: https://github.com/jle64/gnome-pass-search-provider
* license: gpl3
* platforms: unix, linux

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by honnip** [comment]
I don't know if it works or not, but the extension is at `gnome40Extensions."gnome-extension-pass-search-provider.lavrov.github.com"`.

**Comment by edgar-vincent** [comment]
Thanks a lot @honnip. I didn't know about `gnome40Extensions.*`.
