### ISSUE TITLE
Package request: single-file-cli

### ISSUE THREAD

**Issue by solson** [NixOS/nixpkgs#270124]
**Project description**

A CLI tool for saving a faithful copy of a complete web page in a single HTML file.

**Metadata**

* homepage URL: https://github.com/gildas-lormeau/SingleFile (the entire project)
* source URL: https://github.com/gildas-lormeau/single-file-cli (the CLI tool)
* license: AGPL-3.0
* platforms: Linux, possibly others (not sure)

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by amalgame21** [comment]
Also there is a single-file(z)-cli variant:

homepage URL: https://github.com/gildas-lormeau/SingleFileZ (the entire project)
source URL: https://github.com/gildas-lormeau/single-filez-cli (the CLI tool)
