### ISSUE TITLE
Update request: pipewire 0.3.84 → 1.0.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#270108]
- Package name: pipewire
- Latest released version: 1.0.0

- Current version on the unstable channel: 0.3.84 
- Current version on the stable/release channel: 0.3.71
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Kranzes  
@K900  

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/1.0.0

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luzpaz** [comment]
Linking for posterity https://github.com/NixOS/nixpkgs/pull/270110

**Comment by K900** [comment]
https://github.com/NixOS/nixpkgs/pull/270111
