### ISSUE TITLE
makeWrapper: "infect" executables instead of renaming to ".${name}-wrapped"

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27020]
```makeWrapper``` adds some code (which usually modifies environment vars of launches another executable just before the wrapped one) by renaming executable to ".${name}-wrapped" and creating a bash script on the old place of the executable.

This approach is simple and well portable but has some disadvantages

1. Some executables find out its name and do different things depending on the name. [Even Nix does it](https://github.com/NixOS/nix/issues/1431). They may also create directories like "/var/lib/${selfname}", or look for configs in "/etc/${selfname}"
2. Maintenance and monitoring utilites get confused with new names of the wrapped executables. For example ```killall ${name}``` does not kill an executable renamed to ".${name}-wrapped".
3. Executables could try to exec ".${selfname}-wrapped" bypassing the wrapping. Or save a path to ".${selfname}-wrapped" somewhere (there was a ticket recently about such bug).
4. _there were few more pitfalls, I will add when recall_

I propose to try to add the pre-startup code in-place, without renaming executables.

One of the possible solutions could be to extend ```patchelf``` with the possibility to inject some code before the entry point of the patched executable like the old computer virii did. There are mature frameworks, for example https://github.com/secretsquirrel/the-backdoor-factory

**Comment by bjornfor** [comment]
I'd like that. I hate the current wrappers :-)

**Comment by 7c6f434c** [comment]
Erm. How many of the problems would be solved by moving the original to `../bin-wrapped` ?

Infecting would need to distinguish between different formats, including default binary format for the platform, shell, Python, Perl, Ruby, and there are sometimes attempt to write shebang-enabled scripts in languages like Haskell, OCaml and Common Lisp.

**Comment by volth** [comment]
> How many of the problems would be solved by moving the original to ../bin-wrapped ?
It would bring some other, for example reading resource files relative to (next to) executable.

The case with the scripts is a bit different.
And at least Python scripts, as far as I remember, are already "wrapped by infection"

**Comment by 7c6f434c** [comment]
Well, resources in `$out/bin/` seem to annoy people; and any relative
path outside `.` behaves the same for `bin/` and `bin-wrapped`.

With Python it is complicated — it looks like some standard things are
done by infection, but, say, `qutebrowser` is also wrapped twice on top 
of this.

**Comment by 0xABAB** [comment]
I think everyone is in favor of making things more general and less fragile. I'd say it's up to you to demonstrate a specific method with this property.

Not arguing one way or another, but one advantage of the current approach is that you can figure out what's going on with basic tools.

If https://github.com/NixOS/nix/issues/1431 can be solved with whatever method whoever comes up with, I am in favor of including this mechanism if it:
*  does not increase run-time by a lot, has been tested with the goal of breaking it (e.g. fuzzed)
 * has been documented
* has a low compile time overhead
*  has flags to print the paths it modifies (e.g. controlled by an environment variable `NIX_DEBUG_WRAP_MECHANISM`). 

I don't care how complex the solution is, but others might care about that.

**Comment by volth** [comment]
@7c6f434c: about ```bin-wrapped```:
1. there are apps which checks if basename(dirname(argv[0]))=="bin" and behave differently, for example https://github.com/elfmz/far2l/issues/222
2. should ```bin-wrapped``` be exposed as ```/run/current-system/sw/bin-wrapped``` (most if the programs start from ```/run/current-system/sw/bin```) ? There could be subtle problem with relative paths in both cases

**Comment by 7c6f434c** [comment]
Well, patching a `/bin/` check to a `/bin-wrapped/` check is usually
relatively simple; maintaining a set of workarounds for various formats
is probably not simpler.

But maybe it is a good idea to do something crazy with a separate 
subtree and a lot of symlinks:
```
bin/far2l [wrapper]
share/far2l/
wrapped/bin/far2l
wrapped/share -> ../share/
```

(I agree that checks for `/bin/` happen and they may be annoying; I am
just not sure that patching executables in-place can be made easy)

`bin-wrapped` definitely should not be exported into `$PATH`; no opinion
about including in `current-system/sw`.

**Comment by volth** [comment]
> patching a `/bin/` check to a `/bin-wrapped/` check is usually relatively simple; maintaining a set of workarounds for various formats is probably not simpler.

My view is exactly the opposite:

There are too many packages and places to patch. Our coverage is bad: sometimes it is difficult to spot such a problem: it is nice if the app just crashes on start, but it could be that only some minor function does not work or work incorrectly. Also the check could appear in a new version of a blindly upgraded app (like nix 1.11->1.12).

And there are only 2 (or 3? not sure about Darwin) executable file formats and [ready framework](https://github.com/secretsquirrel/the-backdoor-factory) to work with them all.

**Comment by 7c6f434c** [comment]
As for the number of executable formats: the number of realistic script languages is also not so low, and languages seem to only get added.

I think there were some packages that managed to compile ELF binaries that didn't survive `patchelf`, so some extra precautions were needed.

Maybe `nix-wrapped/bin` with symlinks from `nix-wrapped/{share,lib,…}` (everything in `$out` except `bin/` and `nix-*/`) would be enough?

**Comment by 0xABAB** [comment]
@volth I think it sounds promising and doable if you can delegate the details to such an existing tool. I don't think we actually need consensus on this, because instead of having the function `makeWrapper` you can just add a function `makeHightechWrapper`, which due to the assumption that maintainers will learn over time that it is more robust will start using it, until the simplistic `makeWrapper` will slowly fade away out of existence.

So, I suggest that the conclusion of this issue should be that we agree that adding such a symbol (feel free to change the name(!)) together with exactly one demonstration project (nix would seem like the perfect candidate) would be a good idea. 

In fact, to make it even less controversial this functionality could only be added to whatever is the first package that will use it, making it fully self-contained. After various people with commit access are then convinced of the usefulness of this feature, I expect they would be eager to refactor this package such that a library function (`makeHightechWrapper` above) is extracted and they can also start using it. 

If that doesn't happen without good arguments, it appears it would be an excellent time to start forking nixpkgs, but I don't expect that to happen.

If the functionality is designed as a drop-in replacement, a schedule could be setup to slowly replace all occurrences afterwards.

**Comment by 0xABAB** [comment]
@7c6f434c Isn't the only relevant question whether or not a particular different solution works better in at least one case? That is, we don't need to get rid of all the existing methods to solve wrapping problems and we don't need to have a method solve all the problems on day 1.

**Comment by volth** [comment]
@0xABAB some consensus is needed because it might appear that the (benefit / worktime) ratio is too low. If there are only me and @bjornfor who are frustrated with the current wrappers then it would be better to keep them as they are.

**Comment by 0xABAB** [comment]
@volth I am not frustrated, but I welcome innovation. I don't think we should impose systems onto others, but I also don't think the committers should hold other people back, which is exactly what my plan meant to accomplish.

How long (hours/days/weeks/months) would it take you to implement this feature for just nix (with the idea that it can be fairly easily applied to other packages)?

**Comment by FRidh** [comment]
> The case with the scripts is a bit different. And at least Python scripts, are already "wrapped by infection". 

We would actually want to get rid of it because it is fragile. The main issue with Python (or any interpreter) is that `exec -a` isn't listened to. If we could patch e.g. Python to obey it, then I think the main problem is solved. Currently we're exploring another work-around https://github.com/FRidh/nixpkgs/commit/2444dbcc9504e23b4f3195377ac5da7fdc3400e6.

**Comment by copumpkin** [comment]
It's not just you: see https://github.com/NixOS/nixpkgs/issues/23018 and https://github.com/NixOS/nixpkgs/issues/11586
