### ISSUE TITLE
Update request: vcv-rack 2.4.0 → 2.4.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#270200]
- Package name: vcv-rack
- Latest released version: 2.4.1
- Current version on the unstable channel: 2.4.0
- Current version on the stable/release channel: 2.3.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@nathyong  
@jpotier  
@ddelabru  

https://github.com/VCVRack/Rack/blob/v2/CHANGELOG.md#241-2023-08-24

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jpotier** [comment]
@Kranzes may be trying something with https://github.com/NixOS/nixpkgs/pull/270241 so I'll wait a bit

**Comment by Kranzes** [comment]
Honestly I have no idea what vcv-rack is, I just looked for a package I can update to test out a new feature for `nix-update. If you can, take this from from, feel free to update it.

**Comment by jpotier** [comment]
Not sure if I'll have time in the next few weeks, so this is free to pick
