### ISSUE TITLE
fetchpijul is broken: unable to get local issuer certificate

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#270252]
### Describe the bug
The pijul fetcher throws a certificate error when used, for example with the following command:

```
% nix build -I nixpkgs=flake:nixpkgs/master --impure --expr '(import <nixpkgs> {}).fetchpijul {url = "https://nest.pijul.com/pijul/pijul";}
```

> Repository created at /nix/store/5fijkz7p9y1fsqbry4fk40j26pgh77bv-fetchpijul
> Error: error sending request for url (https://nest.pijul.com/pijul/pijul/.pijul?channel=main&id=): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

Related: https://github.com/NixOS/nixpkgs/issues/3382

### Steps To Reproduce
1. Use fetchpijul (for example like in the command above)
3. Fetch fails with above error

### Expected behavior
Repository gets fetched successfully

### Notify maintainers

@nrabulinski 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11.20231121.cccc85f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nrabulinski** [comment]
Oh my, thanks for notifying, I'll make a PR to fix that ASAP!
