### ISSUE TITLE
nix-prefetch-git doesn't provide correct hash if submodules are in use

### ISSUE THREAD

**Issue by swflint** [NixOS/nixpkgs#27033]
## Issue description
If a repository has submodules, nix-prefetch-git will not provide the correct sha256 hash, as it will not correctly fetch submodules.

### Steps to reproduce
see https://gist.github.com/swflint/d639c745c36e1b345d42adec5fabee92

solution can apparently be found on 
https://github.com/NixOS/nixpkgs/blob/756e69bf97c5170408b9511d57c04f4c772c458d/pkgs/build-support/fetchgit/nix-prefetch-git#L11 (thanks tilpner)

## Technical details

* System: 17.09pre109180.0d4431cfe9 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.10
* Nixpkgs version: 17.09pre109180.0d4431cfe9
* Sandboxing enabled: no

**Comment by tilpner** [comment]
That line isn't the solution, but the culprit. fetchgit defaults to fetchSubmodules = true, while nix-prefetch-git defaults to false.

(For some reason, [this](https://github.com/NixOS/nixpkgs/blob/756e69bf97c5170408b9511d57c04f4c772c458d/pkgs/build-support/fetchgit/nix-prefetch-git#L11) prints true in any case)

One of them needs to be changed to match the other. For backwards compatibility, nix-prefetch-git should be changed, as changing fetchgit would required fixing a lot of hashes in nixpkgs (and private packages)

**Comment by swflint** [comment]
That makes sense.

**Comment by bsima** [comment]
This was fixed on master https://github.com/NixOS/nixpkgs/pull/42129

**Comment by tilpner** [comment]
It seems to have been fixed in 2018, a quick test doesn't exhibit the problem (though I can't be entirely sure I tested the right thing, it has been a while). If I'm wrong, please reopen.
