### ISSUE TITLE
run-time regression wezterm since upgrade hyprland/wlroots

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#270354]
### Describe the bug
Since upgrading my `nixpkgs` to https://github.com/NixOS/nixpkgs/commit/b7fa001b723f1cac1b5a12775a04cf945b8dc716, launching Wezterm now triggers error:
> running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11)

### Steps To Reproduce
1. update nixpkgs
2. run wezterm
3. find error

### Expected behavior
no error

### Notify maintainers
@SuperSandro2000 @mimame

### Metadata
(using nixpkgs as flake at the specified commit)

**Comment by ErrorNoInternet** [comment]
https://github.com/wez/wezterm/issues/4483

wezterm hasn't made a new release yet, so you'd have to compile the latest git version manually.

**Comment by SuperSandro2000** [comment]
Is there a specific patch that fixes this that we can fetch?

**Comment by SuperSandro2000** [comment]
Closing because this is an upstream bug not trivial to fix. Recommended upstream fix is too use xwayland

**Comment by KiaraGrouwstra** [comment]
there seems to be a fix in their recent [release](https://github.com/wez/wezterm/releases/tag/20240127-113634-bbcac864).
can we reopen this until the update lands on nixpkgs as well?

**Comment by iynaix** [comment]
> there seems to be a fix in their recent [release](https://github.com/wez/wezterm/releases/tag/20240127-113634-bbcac864). can we reopen this until the update lands on nixpkgs as well?

I've opened a PR: #284377

**Comment by SuperSandro2000** [comment]
> can we reopen this until the update lands on nixpkgs as well?

Since updates usually land really fast in nixpkgs (that update was already merged) and this issue is purely an upstream problem, I don't think it helps having a tracking issue open here for an upstream problem.
