### ISSUE TITLE
[Wayland] Fcitx5 module should NOT set *_IM_MODULE env variables (likely same thing for IBus)

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#270432]
### Describe the bug
Upon login, Fcitx5 presents a popup notification telling me to unset `QT_IM_MODULE` and `GTK_IM_MODULE`. This is specifically in the Plasma 6 (alpha) Wayland session. The environment variables appear to be set in the Fcitx5 NixOS module.

### Notify maintainers

@NickCao @linsui

also @jian-lin for ibus. I'm not sure if the other IMEs are supposed to work on Wayland at all.

### Metadata

(nixos-unstable with Plasma 6 alpha from nix-community/kde2nix)

**Comment by jansol** [comment]
FWIW Plasma 6 defaults the "plasma" session to wayland. The X11 session is renamed to "plasmax11".

At least Plasma has some startup script generated by nix, I think at that point it might be known whether it is Wayland or not?

**Comment by NickCao** [comment]
But users can still choose the session to use upon login right? However the current fcitx5 nixos module unconditionally sets these variables, without a runtime detection mechanism.

**Comment by linsui** [comment]
Is that possible to detect that at runtime, with something like [environment.loginShellInit](https://search.nixos.org/options?channel=unstable&show=environment.loginShellInit&from=0&size=50&sort=relevance&type=packages&query=shell)?

**Comment by NickCao** [comment]
Well that's the `unless with some custom profile scripts` part.

**Comment by jansol** [comment]
That's why I pointed out the startup script from the plasma module.

**Comment by NickCao** [comment]
> That's why I pointed out the startup script from the plasma module.

I mean it's not a must that you unset `QT_IM_MODULE` and `GTK_IM_MODULE` for the wayland session. The input method story is very complicated, with different applications/compositors/input methods supporting different protocols of varying compatibility and functionality. Setting these variables by default in most cases, won't worsen the situation. You may read https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland for some background.

**Comment by jansol** [comment]
Hmm, I see. Maybe they could be set with `mkDefault` so users or other modules can easily override them?

**Comment by NickCao** [comment]
> Hmm, I see. Maybe they could be set with `mkDefault` so users or other modules can easily override them?

Reasonable, but empty string and unset do have different meaning regarding these variables. So I think a blanket option to unset then entirely is more desirable.

**Comment by nonetrix** [comment]
Is there any temporary workaround? I can't find out how to unset it, I don't think there is way besides making it blank which might work? I am confused as to how to get IME to work on Hyprland or Wayland at all, if I can't get Japanese IME to work it's a complete deal breaker for me personally

**Comment by NickCao** [comment]
If hyprland crashes, that's a hyprland issue, the fcitx5 gtk immodule works fine on most other platforms, such as sway.
