### ISSUE TITLE
Update request: xpra 4.4.6 → 5.0.3

### ISSUE THREAD

**Issue by ykis-0-0** [NixOS/nixpkgs#270566]
- Package name: `xpra`
- Latest released version: `5.0.3`

- Current version on the unstable channel: `4.4.6`
- Current version on the stable/release channel: `4.4.4`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@offlinehacker
@numinit
@mvnetbiz 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
I've got a branch that would close this issue and update xpra to 5.0.3, the UI currently works as expected and a connection over SSH is possible however I've encountered an issue running `xpra start` and `xpra shadow`. The error output is similar to what can be found in some other python applications.

```
using systemd-run to wrap 'seamless' xpra server subcommand
Running scope as unit: run-r239b2f65c1ec4d0c83c6e85763601465.scope
  File "/nix/store/jvmlmr8ibpg48q28yw4fwv7dax3wj22h-xpra-5.0.3/bin/xpra", line 1
    ELF
SyntaxError: source code cannot contain null bytes
```.

I'll look into patching this and see if I can push this further.
