### ISSUE TITLE
Update request: vscode-extensions.ms-dotnettools.csharp: 1.25.x → 2.x

### ISSUE THREAD

**Issue by mausch** [NixOS/nixpkgs#270507]
- Package name: vscode extension ms-dotnettools.csharp
- Latest released version: 2.12.4

- Current version on the unstable channel: 1.25.4
- Current version on the stable/release channel: 1.25.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jraygauthier 

I noticed that ms-dotnettools.csdevkit ( https://github.com/NixOS/nixpkgs/issues/270423 ) uses ms-dotnettools.csharp 2.x which has replaced OmniSharp with Roslyn... which probably means major changes to the packaging of this extension unfortunately :disappointed: 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ablearthy** [comment]
Works on my machine (**note**: `mktplcRef.arch` is required, otherwise by default it'll download extension for arm64):
```
(pkgs.vscode-utils.buildVscodeMarketplaceExtension {
  mktplcRef = {
    name = "csharp";
    publisher = "ms-dotnettools";
    version = "2.15.30";
    sha256 = "sha256-i5shbpjp0e0qUIG6FLPu1mIN0DD2+zdCq/nZa49v5iI=";
    arch = "linux-x64";
  };

  postPatch = ''
    sed -i -E -e 's_uname -m_${pkgs.coreutils}/bin/uname -m_g' "$PWD/dist/extension.js"
  
    patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
      --set-rpath "${lib.makeLibraryPath [ pkgs.stdenv.cc.cc ]}:\$ORIGIN" \
      "./.roslyn/Microsoft.CodeAnalysis.LanguageServer"
  '';
})
```

**Comment by mausch** [comment]
@ablearthy Cheers, I just tried that. However I get "Cannot activate the 'C#' extension because it depends on the '.NET Install Tool' extension from 'Microsoft', which is not installed."

**Comment by TGRCdev** [comment]
I also get "Cannot activate the 'C#' extension' message. This extension currently does literally nothing as is, as it depends on an extension that is not in nixpkgs.

**Comment by magnouvean** [comment]
#329948 should bring `.NET Install Tool` to `nixpkgs` when it gets merged. When this extension is installed alongside the C# extension everything seems to work fine.

**Comment by Lord-Valen** [comment]
This has already been updated to 2.x. Any problems with the package should be in separate issues to make the subject clear.
