### ISSUE TITLE
Build failure: brscan4

### ISSUE THREAD

**Issue by agentpt5** [NixOS/nixpkgs#270505]
### Steps To Reproduce

1. build brscan4

### Build log

nixos-rebuild boot
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/qrvkz4fh093779l1xbd2ql3yxkf5dj7g-nixos-23.11/nixos/lib/attrsets.nix:850:11:

          849|         || pred here (elemAt values 1) (head values) then
          850|           head values
             |           ^
          851|         else

       … while evaluating the attribute 'value'

         at /nix/store/qrvkz4fh093779l1xbd2ql3yxkf5dj7g-nixos-23.11/nixos/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `hardware.sane.brscan4.enable' in `/nix/store/qrvkz4fh093779l1xbd2ql3yxkf5dj7g-nixos-23.11/nixos/nixos/modules/services/hardware/sane_extra_backends/brscan4.nix' is already declared in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/hardware/sane_extra_backends/brscan4.nix'.

### Additional context
I have used the exact configuration as documented in the
https://nixos.wiki/wiki/Scanners

for at least a couple years without any problem.  Thanks for all the work by contributors.  I tried to upgrade to 23.11 and encounter above error.

### Notify maintainers

@jraygauthier 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

[root@G6400:/etc/nixos]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11beta670.070b5cf9f70b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
The nixos.wiki documentation seems wrong. Please remove `<nixpkgs/nixos/modules/services/hardware/sane_extra_backends/brscan4.nix>` in `imports` and try again. This issue doesn't seem to be related to brscan anyway, and is not a build failure.
