### ISSUE TITLE
pgadmin3 not end up on system menu after install

### ISSUE THREAD

**Issue by praduca** [NixOS/nixpkgs#27067]
## Issue description
After installing pgadmin3, it fails to put an icon on the system launcher menu.

### Steps to reproduce

Install (nix-env -i pgadmin3)
log out OR reboot
try to locate the app on launcher menu

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
17.03.1449.2e983f14f6 (Gorilla)
nix-env (Nix) 1.11.11
"17.03.1449.2e983f14f6"
build-use-sandbox = false

**Comment by 0xABAB** [comment]
Which system launcher menu? Plasma5? I am also not sure whether this is a supported feature for other packages currently.

Do you expect this to work just on NixOS?

**Comment by emmanuelrosa** [comment]
Have you tried adding pgadmin3 to /etc/nixos/configuration.nix? 

I ask because I had a similar issue, I think it was with an XFCE panel plugin, and adding the package to configuration.nix addressed the issue.

**Comment by praduca** [comment]
Sorry for the delay and the missing info above. 
It was tested on plasma, gnome and xfce. However it put a launcher on ubuntu studio (wich is based on xfce). 
I think this is just a matter of some trigger don't being executed after install, but can't say for sure... I'm still learning the nixos tools for development. :)

**Comment by praduca** [comment]
@emmanuelrosa It didn't work... just install the software. It is available for calling from the command line, but nothing ends on the system menu.

**Comment by emmanuelrosa** [comment]
Ah, OK, the .desktop file may be missing, then.

**Comment by emmanuelrosa** [comment]
I confirmed that the .desktop file missing from the build output of the pgadmin package. That's the file some desktop environments (like XFCE) use to create menu entries for applications.

The pgadmin source code tarball does contain the .desktop file, so the issue is definitely in the Nix expression. I'm debugging the build process with nix-env to see what's going on.

**Comment by emmanuelrosa** [comment]
I've got a fix. I simply ran out of time to finish it up. I should be able to submit a PR next weekend.
