### ISSUE TITLE
 ucspi-tcp broken

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#27063]
## Issue description

ucspi-tcp is broken in the current master and nixos-17.03.
The bug was introduced by f4b4edc290377a402ad949c6c178785bebd6efe8

### Steps to reproduce

nix-shell -p ucspi-tcp on current master or 17.03

**Comment by joachifm** [comment]
The failure is due to `s{u,g}id` bits now being illegal. To fix it, patch the `ucspi-tcp` build recipe to avoid attempting to create files with those bits set.
