### ISSUE TITLE
pgadmin4 service fails to start in and out of declarative container

### ISSUE THREAD

**Issue by bee1850** [NixOS/nixpkgs#270624]
### Describe the bug
After declaring the pgadmin4 service along with the postgresql service, the pgadmin4 service fails to start with the following error:
```
Nov 28 11:56:20 database pgadmin-pre-start[268]: During handling of the above exception, another exception occurred:
Nov 28 11:56:20 database pgadmin-pre-start[268]: Traceback (most recent call last):
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/bin/.pgadmin4-setup-wrapped", line 9, in <module>
Nov 28 11:56:20 database pgadmin-pre-start[268]:     sys.exit(main())
Nov 28 11:56:20 database pgadmin-pre-start[268]:              ^^^^^^
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/lib/python3.11/site-packages/pgadmin4/setup.py", line 223, in main
Nov 28 11:56:20 database pgadmin-pre-start[268]:     app = create_app()
Nov 28 11:56:20 database pgadmin-pre-start[268]:           ^^^^^^^^^^^^
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py", line 477, in create_app
Nov 28 11:56:20 database pgadmin-pre-start[268]:     run_migration_for_sqlite()
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py", line 414, in run_migration_for_sqlite
Nov 28 11:56:20 database pgadmin-pre-start[268]:     upgrade_db()
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py", line 395, in upgrade_db
Nov 28 11:56:20 database pgadmin-pre-start[268]:     backup_db_file()
Nov 28 11:56:20 database pgadmin-pre-start[268]:   File "/nix/store/6pgy07z6ycg2g3q2rqmhyf7ggsz1z7qf-pgadmin-7.7/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py", line 383, in backup_db_file
Nov 28 11:56:20 database pgadmin-pre-start[268]:     raise RuntimeError('Migration failed')
Nov 28 11:56:20 database pgadmin-pre-start[268]: RuntimeError: Migration failed
Nov 28 11:56:20 database systemd[1]: pgadmin.service: Control process exited, code=exited, status=1/FAILURE
Nov 28 11:56:20 database systemd[1]: pgadmin.service: Failed with result 'exit-code'.
Nov 28 11:56:20 database systemd[1]: Failed to start pgadmin.service.
Nov 28 11:56:20 database systemd[1]: pgadmin.service: Consumed 1.667s CPU time.
```

### Steps To Reproduce
1. Add the following configuration to your configuration.nix :
```nix
containers.database =
    {
      config =
        { config, pkgs, ... }:
         {
          system.stateVersion = "23.05";
          services.postgresql.enable = true;
          services.pgadmin.enable = true;
          services.pgadmin.initialEmail = "bee1850@example.com";
          services.pgadmin.initialPasswordFile = pkgs.writeText "pgadminPW" ''
            admin
          '';
        };
    };
```
3. rebuild the system
4. root-login into the container and run `systemctl status pgadmin.service`

### Expected behavior
pgadmin4 7.7 runs normally.

### Additional context
I am on the NixOS unstable channel.
The container and its remnants in /var/lib/nixos-containers were removed before trying to start again (there should be no "old" database)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231119.e4ad989`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
[user@system:~]$ nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bee1850** [comment]
@thoughtpolice
@danbst
@gador
@SuperSandro2000 

Retagging because I cannot see the pings in the issue and thus am not sure if you really got notified.

**Comment by gador** [comment]
Yes, I was able to reproduce the error.
Unfortunately, you clipped the important part. If you'd look at the output of `journalctl -xeu pgadmin.service` you'd notice a line:
`Password must be at lest 6 characters. Please try again`

I admit the line is buried in python errors and tracebacks.
So please try again with a password.

For reference: There is a nixosTest for pgadmin. If all else fails, try to use those settings and see of these work ;-)

**Comment by bee1850** [comment]
> Yes, I was able to reproduce the error. Unfortunately, you clipped the important part. If you'd look at the output of `journalctl -xeu pgadmin.service` you'd notice a line: `Password must be at lest 6 characters. Please try again`
> 
> I admit the line is buried in python errors and tracebacks. So please try again with a password.
> 
> For reference: There is a nixosTest for pgadmin. If all else fails, try to use those settings and see of these work ;-)

Oh, i just noticed! Weird, i swear i've used this password before and it worked (locally only of course, for studying only).

I'll try to update it now!
Thank you :)

**Comment by bee1850** [comment]
Worked perfectly!
