### ISSUE TITLE
Package request: yazi

### ISSUE THREAD

**Issue by aspauldingcode** [NixOS/nixpkgs#270714]
**Project description**

Already implemented to nix pkgs before with "(yazi: init at 0.1.3 #250697)"

(https://github.com/NixOS/nixpkgs/pull/250697)

Problem: Not included in nixpkgs anymore?

**Comment by khaneliman** [comment]
Already in nixpkgs https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/file-managers/yazi/default.nix#L73
