### ISSUE TITLE
nix-direnv should not bundle nix

### ISSUE THREAD

**Issue by simonzkl** [NixOS/nixpkgs#270741]
### Describe the bug

The `nix-direnv` derivation wraps `direnvrc` by prepending the file with `NIX_BIN_PREFIX=${pkgs.nix}`. 

As a result:
- On non-NixOS system it's impossible to use nix-direnv with the system version of nix. This is very surprising and I spent an hour trying to figure out why the hell it's using some ancient version of nix.
- In NixOS it ignores `config.nix.package` and uses the default `pkgs.nix`.

In my opinion nix-direnv should work like this:
- By default it should use the system version of nix. Yes, technically `nix` is a dependency of `nix-direnv`, but you literally can't install `nixpkgs.nix-direnv` without nix, so I don't think this is a big deal.
  - Alternatively, it could first attempt to find a system nix, and then fallback to the bundled one.
- On NixOS, we could set `nix-direnv.package = pkgs.nix-direnv.override { nix = config.nix.package; }`

### Steps To Reproduce
1. Install nix-direnv
2. Add `set -x; use flake` to `.envrc`
3. Run `direnv allow` and check the trace output

### Expected behavior
nix-direnv should use the system version of nix.

### Notify maintainers

@mic92 @bbenne10 @Gerg-L @zowoq

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9lriws7wmqqbz1x1hnv4nanbmmqhkfq8-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by simonzkl** [comment]
I guess you could go with the reproducability angle that `nix-direnv` should always be bundled with the known-working version of `nix`. But I would argue that it's far worse to have your system managed by two (widely) different versions of nix.

**Comment by Mic92** [comment]
Historically we needed this because we had to pass in a nix version that can work with flakes.
Now that all reasonable installations should use a new enough version of nix, we could reconsider this choice.

**Comment by bbenne10** [comment]
I'm 👍 on unbundling nix from the nix-direnv install, but also agree that we need to fix both here and home-manager somewhat in sync.

**Comment by szlend** [comment]
If we just remove the `NIX_BIN_PREFIX` `direnvrc` wrapper, then we don't actually have to make any changes to the nixos/home-manager modules.

**Comment by dschrempf** [comment]
I was just wandering why I am getting `warning: unknown experimental feature 'configurable-impure-env'` warnings in all of my flakes. System `nix` version is `nix (Nix) 2.19.2`, `nix-direnv` `nix` version is `nix (Nix) 2.18.1`.

**Comment by szlend** [comment]
Happy to open a PR for this if the maintainers agree. I would suggest outright removing the nix dependency for reasons mentioned in my previous message.

**Comment by Mic92** [comment]
@szlend Pleas turn this into an upstream issue first. @kingarrrt recently migrated nix-direnv to resholve and we need to fix this on this level

**Comment by Gerg-L** [comment]
Seems like this was fixed by https://github.com/NixOS/nixpkgs/pull/339358
