### ISSUE TITLE
Build failure: tectonic

### ISSUE THREAD

**Issue by HungryJoe** [NixOS/nixpkgs#270718]
### Steps To Reproduce

1. `nix shell nixpkgs#tectonic` on x86_64-darwin

### Build log
https://gist.github.com/HungryJoe/c12df677b81b73b26f33ca9afffaa617

### Notify maintainers

 @lluchs @doronbehar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - channels(user): `"nixpkgs-23.05-darwin-23.05-darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Please note** that the above `macOS` version contradicts the rest of my system, which claims I'm on `macOS 13.6.1`.

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilytrau** [comment]
This was fixed in #269786. It should be available in `nixpkgs-unstable` [soon](https://nixpk.gs/pr-tracker.html?pr=269786) :)
