### ISSUE TITLE
Mention nix.* config options in manual

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#27078]
Settings like

```
nix.maxJobs
nix.binaryCaches
```

are the equivalents of the

```
build-max-jobs
binary-caches
```

values in `/etc/nix/nix.conf`, but the former are not documented (I could only find them by trial and error via http://nixos.org/nixos/options.html).

We should document them.

**Comment by FRidh** [comment]
Type `nix.` and you get them all so I don't agree with you that they're not documented.

**Comment by Mic92** [comment]
But it does not hurt, if you also add a reference, which nix options this corresponds to.

**Comment by FRidh** [comment]
If that is missing, then yes, that should be added.

**Comment by Artturin** [comment]
fixed since 4a9d9928dc01421b878cfe4a16961c1e4862d846
