### ISSUE TITLE
Package request: hblock

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#270891]
**Project description**

hblock is a POSIX-compliant shell script that gets a list of domains that serve ads, tracking scripts and malware from multiple sources and creates a hosts file, among other formats, that prevents one's system from connecting to them.

**Metadata**

* homepage URL: https://hblock.molinero.dev/
* source URL: https://github.com/hectorm/hblock
* license: MIT
* platforms: POSIX

**Priorities**

I think this is a priority, since it increases not only the security, but offers also an unique way to reduce the content that is downloaded, and by that, the subjective internet speed significantly. 

There is no maintained alternative to my knowledge, unless someone sets up a DNS hole on an external device, like a Raspberry Pi. 

This is the only local option I am aware about. (Unless the unmaintained hostsblocks.)

**Comment by eclairevoyant** [comment]
already packaged https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/hblock/default.nix
