### ISSUE TITLE
TexLive is outdated

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#27086]
## Issue description

TexLive 2017 has been released over a month ago now, and I expect the update to be nontrivial. I thought I'd create this issue to track the updating process.

**Comment by NickHu** [comment]
cc @vcunat

**Comment by vcunat** [comment]
Yes, probably nontrivial.  I don't think it will get to the top of my TODO within a few weeks at least.

**Comment by NickHu** [comment]
Would also like to highlight the lack of a `repstopdf` symlink, as mentioned here https://github.com/NixOS/nixpkgs/issues/4210

**Comment by vcunat** [comment]
Eh, well, I'll try adding that, though I really dislike their tendency to create a hundred executables.  `epstopdf --restricted` will do exactly the same...

**Comment by vcunat** [comment]
@NickHu, @7c6f434c: this patch seems good 7aa140488aa &ndash; can you test `repstopdf` in your use cases, to be surer?

**Comment by 7c6f434c** [comment]
It adds `repstopdf` link unconditionally even if `epstopdf` doesn't exist?

I am not sure that hacking a `repstopdf` package with a single symlink into `texlive` package set is worse (I just install it in addition to some combined TeXLive expression)

**Comment by vcunat** [comment]
@7c6f434c: it only adds `repstopdf` conditionally on having `epstopdf`.  I also tested that.  (`cp` would fail anyway)

**Comment by 7c6f434c** [comment]
Ah nice. If only I remembered what document required `repstopdf` to test…

**Comment by vcunat** [comment]
@7c6f434c: your thesis? https://github.com/NixOS/nixpkgs/issues/4210#issuecomment-179920807

**Comment by 7c6f434c** [comment]
I had a hope there is a less hopeless test case, because in case of my thesis there is also `disser` package and bibliography style compatibility…

**Comment by 7c6f434c** [comment]
Hm, on the other hand, it breaks on `eps` include _first_, so I can still test even if I do not actually succeed.

**Comment by 7c6f434c** [comment]
@vcunat erm, in what branch is that `repstopdf` fix?

**Comment by vcunat** [comment]
@7c6f434c, it's in my fork: https://github.com/vcunat/nixpkgs/tree/texlive-repstopdf

**Comment by vcunat** [comment]
It might be easiest to `curl https://github.com/NixOS/nixpkgs/commit/7aa140488aa.patch | git am` in such cases...

**Comment by 7c6f434c** [comment]
One could naively expect that if GitHub agrees to show it in NixOS/NixPkgs, there is a branch of this repository that contains the commit. I certainly did.

**Comment by vcunat** [comment]
It includes some "related" repositories, apparently, and I misused that here. It would be nice if they showed some reachability information, though.

**Comment by 7c6f434c** [comment]
It would be even nicer if Git handled branches in a saner way…

Looks like this hack does allow my thesis compilation to fail on bibliography instead of `repstopdf`.

**Comment by Nadrieril** [comment]
Any news on texlive 2017 ?

**Comment by vcunat** [comment]
@Nadrieril: not on my side, at least.

**Comment by sveitser** [comment]
> @NickHu, @7c6f434c: this patch seems good usable [7aa1404](https://github.com/NixOS/nixpkgs/commit/7aa140488aa3e3c3557cafa1bda0ad8f3bad5aef) – can you test `repstopdf` in your use cases, to be surer?

The created `repstopdf` this way worked on our end. However the check for `epstopdf` being a symlink seems to fail.
