### ISSUE TITLE
Incorrect license for the `vscode-extensions.devsense.*` packages

### ISSUE THREAD

**Issue by sigprof** [NixOS/nixpkgs#271032]
### Describe the bug
The following packages specify the Apache License 2.0 in the metadata, but actually are proprietary:
- [`vscode-extensions.devsense.phptools-vscode`](https://github.com/NixOS/nixpkgs/blob/8cfef6986adfb599ba379ae53c9f5631ecd2fd9c/pkgs/applications/editors/vscode/extensions/default.nix#L985-L1033): [proprietary license](https://marketplace.visualstudio.com/items/DEVSENSE.phptools-vscode/license) (although I suppose that [this “Community License”](https://www.devsense.com/en/purchase/licenses/community) actually applies to the “free as in beer” version, but it's nonfree anyway)
- [`vscode-extensions.devsense.composer-php-vscode`](https://github.com/NixOS/nixpkgs/blob/8cfef6986adfb599ba379ae53c9f5631ecd2fd9c/pkgs/applications/editors/vscode/extensions/default.nix#L968-L983): [proprietary license](https://marketplace.visualstudio.com/items/DEVSENSE.composer-php-vscode/license)
- [`vscode-extensions.devsense.profiler-php-vscode`](https://github.com/NixOS/nixpkgs/blob/8cfef6986adfb599ba379ae53c9f5631ecd2fd9c/pkgs/applications/editors/vscode/extensions/default.nix#L1035-L1050): [proprietary license](https://marketplace.visualstudio.com/items/DEVSENSE.profiler-php-vscode/license)

### Steps To Reproduce
Inspect the metadata of the listed packages — they have `license = lib.licenses.asl20`, but the `downloadPage` shows something completely different.  The actual content of packages also includes `LICENSE.md` with a proprietary license text.

Also the `homepage` of these packages points to a [GitHub repo named “PHP Tools public content”](https://github.com/DEVSENSE/phptools-docs); the content of that repo is apparently under Apache License 2.0, but there is no actual source code there — only the documentation and other public site content.

### Expected behavior
The packages need to be either appropriately marked as unfree or removed.

### Notify maintainers

@drupol

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.05 (Stoat), 23.05.20231127.5b528f9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/etc/nix/channels/nixpkgs`

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Thanks for reporting the issue, I'll fix it tomorrow.

**Comment by drupol** [comment]
Fixed in #271040
