### ISSUE TITLE
Flutter local development issues

### ISSUE THREAD

**Issue by Nexushunter** [NixOS/nixpkgs#271042]
### Describe the bug
When working with flutter locally I am unable to:
1. successfully test my application using `flutter test`
2. successfully build my application: `flutter build linux`
3. resolve `flutter doctor` missing dependencies

Resolving # 3 is likely the solution for 1 & 2.

### Steps To Reproduce
1. in a flutter project run `flutter test`
2. in a flutter project run `flutter build linux`
3. install flutter using the following config

### Additional context
I initially had my `environment.systemPackages` to include:
- google-chrome
- flutter-unwrapped

I set the `environment.variables.CHROME_EXECUTABLE` set to `google-chrome-stable`

Including:
- cmake
- ninja
- pkg-config-unwrapped
- llvmPackages_16.clang-unwrapped

Seemingly fixed all but the `gtk3` requirement from `flutter doctor`.

```console
[✓] Flutter (Channel stable, 3.13.8, on NixOS 23.11 (Tapir)
    6.1.61, locale en_CA.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android
      SDK components.
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-s
      etup for detailed instructions).
      If the Android SDK has been installed to a custom location,
      please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux
      development.
      They are likely available from your distribution (e.g.: apt
      install libgtk-3-dev)
```

Android isn't necessary when targeting linux and web (and should be resolvable using one of the other nixpkgs)

[output_flutter_test.txt](https://github.com/NixOS/nixpkgs/files/13505922/output.txt)

### Notify maintainers
@FlafyDev @hacker1024 @babariviere @ericdallo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11pre544052.85f1ba3e5167`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hacker1024** [comment]
Why are you using `flutter-unwrapped`? The wrapper is necessary for many things, especially Linux desktop support.

**Comment by Nexushunter** [comment]
I was unaware of that. I'm relatively new to NixOs and am used to doing direct installs of most things.

Does that mean if I were to use the wrapped variant I can remove much of the additional manually installed dependencies?

**Comment by hacker1024** [comment]
> Does that mean if I were to use the wrapped variant I can remove much of the additional manually installed dependencies?

Yep - `flutter` alone should be all that is needed.

**Comment by Nexushunter** [comment]
Unfortunately that didn't work. I set just the `flutter` package to be apart of the system packages (instead of `flutter-unwrapped` and `flutter doctor` complained about the missing dependencies for the linux toolchain:
- cmake
- ninja
- pkg-config
- clang++

Once I installed those packages flutter doctor throws a complaint about missing `gtk3`. I've added that to the system packages ( `pkgs.gtk3` also and it still isn't resolved (unlike the others mentioned above).

Any thoughts here?

**Comment by ewann** [comment]
https://discourse.nixos.org/t/pkgs-gtk3-cannot-find-xlib-h-even-with-the-package-present/21574/3

specifically:
buildInputs = with pkgs; [
    at-spi2-core.dev
    clang
    cmake
    dart
    dbus.dev
    flutter
    gtk3
    libdatrie
    libepoxy.dev
    libselinux
    libsepol
    libthai
    libxkbcommon
    ninja
    pcre
    pkg-config
    util-linux.dev
    xorg.libXdmcp
    xorg.libXtst
  ];

at the time of writing appears to help get past https://github.com/NixOS/nixpkgs/issues/271042#issuecomment-1837232645 @Nexushunter fyi
