### ISSUE TITLE
grafx2: desktop entry doesn't work

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#271068]
### Describe the bug
The GrafX2 desktop entry points to an incorrect executable, causing it to not work.

### Steps To Reproduce
1. Install GrafX2
2. Try to use the installed desktop entry
3. Failed to execute child process "grafx2" (No such file or directory)

### Expected behavior
GrafX2 actually starting up

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/69703458/b32562b1-d1ac-4026-9470-a5bda32129ec)

### Additional context
The actual executable name is "grafx2-sdl"

#### Workaround
Add a new file in "~/.local/share/applications" called `grafx2.desktop`, with the following contents:
```desktop
[Desktop Entry]
Name=GrafX2
Comment=Deluxe Paint Clone
Comment[fr]=Clone de Deluxe Paint
Exec=grafx2-sdl %f
Terminal=false
Type=Application
Icon=grafx2
Categories=Graphics;
MimeType=image/lbm;image/iff;image/pcx;image/tga;image/gif;image/bmp;image/x-icon;image/png;
```
You might have to run `xfdesktop -R` afterwards to clear caches? i'm not sure.
Importantly, this changes `Exec=grafx2 %f` to `Exec=grafx2-sdl %f`

### Notify maintainers

Maintainer list is empty! @-ing people who edited the file recently.
@jchv @AndersonTorres @trofi @Zoomulator (this is what happens when you don't leave a specified successor) 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.05 (Stoat), 23.05.4705.621f51253edf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05, unstable"`
 - channels(hjs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
I will adopt this, then.
