### ISSUE TITLE
phpfpm 'No input file specified.' in /home/... directories

### ISSUE THREAD

**Issue by qvamatel** [NixOS/nixpkgs#27108]
## Issue description

Phpfpm returns an "Status: 404 Not Found" error if I run a php script in my home directory.
phpfpm config:
         services.phpfpm.pools.tomi = {
		listen = "/run/php-fpm/tomi.sock";
		extraConfig = ''
			user = tomi
			group = users
			listen.owner = tomi
			listen.group = users
			pm = dynamic
			pm.max_children = 75
			pm.start_servers = 10
			pm.min_spare_servers = 5
			pm.max_spare_servers = 20
			pm.max_requests = 10000
		'';
	};
	services.phpfpm.phpOptions = ''
		open_basedir = /
	'';

file:
        test.php -> owner: tomi:users, permissions: 777

run:
If the file is in the / or /var or /run or ... directory then phpfpm run perfect:

$ SCRIPT_FILENAME=/var/test.php REQUEST_METHOD=GET cgi-fcgi -bind -connect /run/php-fpm/tomi.sock
X-Powered-By: PHP/7.1.5
Content-type: text/html; charset=UTF-8

Yeeee, I'm Run!!!

But if the file is in the /home/... directory then phpfpm return error:

$ SCRIPT_FILENAME=/home/tomi/test.php REQUEST_METHOD=GET cgi-fcgi -bind -connect /run/php-fpm/tomi.sock
Unable to open primary script: /home/tomi/test.php (No such file or directory)
Status: 404 Not Found
X-Powered-By: PHP/7.1.5
Content-type: text/html; charset=UTF-8

No input file specified.

If I use a nginx web server instead of cgi-fcgi, then that is the case.
Why?

## Technical details

* System: NixOS: 17.03.1437.a2c7482319 (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: "17.03.1437.a2c7482319"
* Sandboxing enabled: build-use-sandbox = false

**Comment by pbogdan** [comment]
That's likely because the service is running with `ProtectHome=true` option:

```
$ sudo systemctl cat phpfpm-www-data.service | grep ProtectHome   
ProtectHome=true 
```

See https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome= for details on the option and https://github.com/NixOS/nixpkgs/pull/22154 which appears to have introduced this.

**Comment by qvamatel** [comment]
Oh, thanks, this solves the problem.
