### ISSUE TITLE
Nvidia Driver fails to build

### ISSUE THREAD

**Issue by relief-melone** [NixOS/nixpkgs#271035]
### Describe the bug
Coming from this issue
https://github.com/NixOS/nixpkgs/issues/270374
I removed all failing packages but the Nvidia Driver. But for about one week builds in nixos-unstable are failing. (My nix-channel --list-generations points to the last successful generation on Nov 21st and fails on 26th. If you can help me how to get to the commits I'll happily provide those as well).

See the log for the error.
[log.txt](https://github.com/NixOS/nixpkgs/files/13505597/log.txt) 

As mentioned in my previous issue this happens in other packages as well (e.g. opera, discord, nvidia-settings) and I think the issue is related.

I do have a Nvidia 3080ti mobile. I expect as usual for Nvidia the experience might differ with any given card.

My Nvidia config looks like this at the moment
```nix
{ pkgs, config, lib, ...}:
let
  # Get from lspci and convert from hex to decimal
  intelBus = "PCI:0:2:0";
  nvidiaBus = "PCI:1:0:0";
in
{

  # Make sure opengl is enabled
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  # NVIDIA drivers are unfree.
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "nvidia-x11"
    ];

  # Tell Xorg to use the nvidia driver
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {

    modesetting.enable = true;
    open = true;


    nvidiaSettings = false;

    package = config.boot.kernelPackages.nvidiaPackages.stable;

    powerManagement.enable = false;
  };

  hardware.nvidia.prime = {
    sync.enable = true;

    intelBusId = "${intelBus}";
    nvidiaBusId = "${nvidiaBus}";
  };

  specialisation = with lib; {
    # MOBILE IN PRIME MODE
    mobile.configuration = {
      system.nixos.tags = [ "mobile" ];
      hardware.nvidia = {
        prime.offload.enable = mkForce true;
        prime.offload.enableOffloadCmd = mkForce true;
        prime.sync.enable = mkForce false;
      };

      hardware.nvidia.powerManagement = {
        enable = mkForce true;
        finegrained = mkForce true;
      };
    };
  };

}

```

### Steps To Reproduce
1. Use the config above
2. run `sudo nixos-rebuild switch` on current unstable channel

### Expected behavior
The build should run through without errors

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir), 23.11pre550515.e4ad989506ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
This specific failure appears to be of `pkgsi686Linux.nvidia-vaapi-driver`, however I can't figure out why that specific error would occur, since that package doesn't use cmake and properly declares a dependency on `libva`.

Could you please provide the output of `nix show-derivation /nix/store/rqwlnffcswwhf5hj9cplb15gg8xw9ghj-nvidia-vaapi-driver-0.0.11.drv` so I can see why the derivation is different?

**Comment by relief-melone** [comment]
Sure. Hope this helps.
Just to be sure I am currently back on the generation of the channel that works currently. That should be no problem for the logs though as the build should be unique due to the hash in the nix store right?
[derivation-vaapi-driver.txt](https://github.com/NixOS/nixpkgs/files/13512239/derivation-vaapi-driver.txt)

**Comment by Kiskae** [comment]
Ok that appears to be a dead end, besides changes in (drv) hashes the derivations are identical.

Could you verify that `nix build nixpkgs#pkgsi686Linux.nvidia-vaapi-driver --print-build-logs` fails or succeeds?

**Comment by relief-melone** [comment]
Taht also fails with the same behaviour. I also suspect the other packages mentioned above to have the same root cause. All of them seem to be related to the libva dependency and cmake as far as my limited interpretation skills on nix go at the moment. Here's the logs for the flake build.
[pkgsi686Linux.build.log.txt](https://github.com/NixOS/nixpkgs/files/13514735/pkgsi686Linux.build.log.txt)

**Comment by relief-melone** [comment]
that file comes back empty

**Comment by Kiskae** [comment]
> that file comes back empty

Then that is likely the source of your problems, since the pkg-config is missing meson can't find the libva library and probably tried to build its own version, hence the cmake error.

I *believe* you can use the [verify/repair commands](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-store-repair) to get the correct files downloaded:

```console
nix store verify /nix/store/2i998dg8s8ab1y08ivi4rhgrrq9q1ijn-libva-2.20.0-dev
# sudo required because nix-daemon can't do repairs?
sudo nix store repair /nix/store/2i998dg8s8ab1y08ivi4rhgrrq9q1ijn-libva-2.20.0-dev
```

**Comment by relief-melone** [comment]
heureka. That seems to have been the cause of the problems. I have not done a complete rebuild yet but `nix build nixpkgs#pkgsi686Linux.nvidia-vaapi-driver --print-build-logs`now worked.
I know this is not really an issue anymore now and that was a problem on my system but I am trying to understand what happened.
How can those changes occur (having run `nix store verify --all` it showed numerous modifications)? Will update on the complete system rebuild but I guess the issue can be closed afterwards. 
Thank you very much for the help!.

**Comment by Kiskae** [comment]
> How can those changes occur

That's difficult to say but given how much there was it might indicate your drive starting to fail. Definitely make sure you have your important documents backed up somewhere just in case and perhaps run a health check.

But since this issue appears to have been resolved, I'll close this issue.
