### ISSUE TITLE
python36Full does not provide pip while it says it does

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#27109]
## Issue description

In NixOS, when I try to run `pip` and the program is not found, the following message is shown

```shell
$  pip
The program ‘pip’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.python27Packages.bootstrapped-pip
  nix-env -iA nixos.python27Packages.pip
  nix-env -iA nixos.python3
  nix-env -iA nixos.python33
  nix-env -iA nixos.python33Full
  nix-env -iA nixos.python34
  nix-env -iA nixos.python34Full
  nix-env -iA nixos.python35Packages.bootstrapped-pip
  nix-env -iA nixos.python36
  nix-env -iA nixos.python36Full
  nix-env -iA nixos.python3Full
```

even when `nixos.python36Full` is installed via `systemPackages` or `nix-env`.

In fact, the `bin` folder in the nix store for the `python36Full` package contains a broken symlink named `pip` that points to a non-existent `pip3` file:

```shell
$ nix-instantiate --eval '<nixpkgs>' -A python36Full.outPath
"/nix/store/103x241k4pvb950w5smy4lgq2nblxbs5-python3-3.6.1"
$ file /nix/store/103x241k4pvb950w5smy4lgq2nblxbs5-python3-3.6.1/bin/pip
/nix/store/103x241k4pvb950w5smy4lgq2nblxbs5-python3-3.6.1/bin/pip: broken symbolic link to /nix/store/103x241k4pvb950w5smy4lgq2nblxbs5-python3-3.6.1/bin/pip3
```

### Steps to reproduce

Install `nixos.python36Full` and check the `bin` directory.

## Technical details

* System: NixOS: `17.03.1449.2e983f14f6 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.11`
* Nixpkgs version: `17.03.1449.2e983f14f6`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by FRidh** [comment]
@stefano-m thanks for the report. We've disabled building `pip` as part of Python. Instead, you can use `python.pkgs.pip`. The symlinks are indeed a bug, I'll have a look at that later.

**Comment by FRidh** [comment]
the relevant commits fixing this issue are now in master.
