### ISSUE TITLE
jd-gui fails (no error message)

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#27113]
## Issue description

Can't start jd-gui at all.

PS: Dowloading the generic jar from http://jd.benow.ca/ work.

### Steps to reproduce

    nix-shell -p jd-gui
    jd-gui

There is no error messages what so ever. Exit code is 127.

(I've also tried installing with `nix-env`)

## Technical details

* System: NixOS: 17.03.1160.f2c4af4e3b (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1160.f2c4af4e3b"

**Comment by 0xABAB** [comment]
This requires command line output of some kind and more details.

**Comment by dtzWill** [comment]
strace shows this is because it's a 32bit binary, fails trying to access `/lib/ld-linux.so.2`.

Further investigation shows the binary is upx-packaged, I'll see if I can't put together a fix for this shortly.

**Comment by gebner** [comment]
Do you know the difference to the current 1.4.0 release?  The 1.4.0 release seems to be platform-independent jar that doesn't require any patching.
