### ISSUE TITLE
`nix-config.drv` fails to build with nix from master

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#271146]
### Describe the bug

When building the system configuration, there is a check for the generated nix config, which seems to use `nix show-config` internally.

This check fails when using `nix.package` with a drv from nix master, as there `nix show-config` creates a hard error and exits with a non zero exit code. The message suggests to use `nix config show` instead

### Steps To Reproduce

1. Set `nix.package` to a nix from master. Seems to happen since 2023-11-28 on my CI
2. rebuild the system
3. See it fail, similar to https://github.com/NobbZ/nixos-config/actions/runs/7041136993/job/19163231499#step:6:5473

### Expected behavior

The build of the system suceeds

### Screenshots

Please see the linked build logs instead

https://github.com/NobbZ/nixos-config/actions/runs/7041136993/job/19163231499#step:6:5473

### Additional context

nixos/nix#9477 seems to be the PR that introduced the behaviour on the `nix` side.

### Notify maintainers

* @roberth (only person touching relevant module)
* @thufschmitt (author of the nix PR)

### Metadata

This is the last **known to build** version:

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.9, NixOS, 24.05 (Uakari), 24.05.20231124.5a09cb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.0pre20231127_f018048`
 - channels(aroemer): `"nixpkgs-21.11"`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thufschmitt** [comment]
Uh, I though deprecated aliases were only throwing a warning, not a hard error. @nixos/nix-team is that really the behaviour we want?

**Comment by thufschmitt** [comment]
Oh, but it's not an error from the Nix side, it's the NixOS module code that rewrites warnings into hard errors :grimacing: 

https://github.com/NixOS/nixpkgs/blob/67be70a859530f6f7c358568eaa6ab0d84b36b01/nixos/modules/config/nix.nix#L118-L122

**Comment by roberth** [comment]
Yeah I have my fingerprints all over the module...
The reason it escalates warnings to errors is https://github.com/NixOS/nixpkgs/pull/139075#discussion_r733615550
Maybe we could make the activation script print warnings instead, so we don't have to do this kind of thing.

Anyway, the simplest fix is to use the new syntax.
@NobbZ, could you try #271423?

**Comment by NobbZ** [comment]
Okay, just checked the changes in the PR. You do indeed a version based switch of the actual command to use :+1:

I will give it a try in a couple of hours, need to be back at PC first.

**Comment by NobbZ** [comment]
I was finally able to check, and the PR seems to work for me. Just took ages as I had to build qemu from scratch…
