### ISSUE TITLE
No IPv6 Routers available

### ISSUE THREAD

**Issue by rszibele** [NixOS/nixpkgs#27111]
## Issue description

I have a server running NixOS and I would like to add the IPv6 addresses that my hosts provides me with. However, I get no IPv6 routers in my journalctl and IPv6 doesn't work.

### Steps to reproduce

Here's the networking part of my `configuration.nix`:

```
  networking.interfaces.enp0s3.ip6 = [
    { address = "2a02:e00:ffec:115::a"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::9"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::8"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::7"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::6"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::5"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::4"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::3"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::2"; prefixLength = 64; }
    { address = "2a02:e00:ffec:115::1"; prefixLength = 64; }
  ];
  networking.defaultGateway6 = "2a02:e00:ffec::1";
```

Journalctl reports the following:

> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::a/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::a/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::9/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::9/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::8/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::8/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::7/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::7/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::6/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::6/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::5/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::5/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::4/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::4/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::3/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::3/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::2/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::2/64...
> network-addresses-enp0s3-start[515]: checking ip 2a02:e00:ffec:115::1/64...
> network-addresses-enp0s3-start[515]: added ip 2a02:e00:ffec:115::1/64...

...

> dhcpcd[989]: enp0s3: no IPv6 Routers available

My ifconfig shows the following:
```
enp0s3    Link encap:Ethernet  HWaddr 12:A7:5C:75:A5:8C
          inet addr:130.255.78.218  Bcast:130.255.78.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7256 errors:0 dropped:8 overruns:0 frame:0
          TX packets:672 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:474051  TX bytes:221474

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Bcast:0.0.0.0  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:627 errors:0 dropped:0 overruns:0 frame:0
          TX packets:627 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:162543  TX bytes:162543
```

## Technical details

* System: 17.03.1188.9fd6417e27 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.1188.9fd6417e27
* Sandboxing enabled: build-use-sandbox = false

**Comment by fadenb** [comment]
Do I understand correctly that your issue is that you do not receive ip6 routers announced via DHCPv6 when you configure ip6 statically?

Or is the issue that you do not have ip6 connectivity? Your gateway is not in the same /64 as the IPs you configured. You would have to ensure the gateway is reachable (by adding a route specifying over which interface to reach it)

**Comment by fpletz** [comment]
This also looks like a misconfiguration to me as @fadenb explained. Closing for now. Feel free to reopen if this issue persists.

**Comment by rszibele** [comment]
@fadenb I assumed that setting the ipv6 gateway would add it to the route, but I was wrong. Got it working my manually adding the route via. "ip -6 route add 2a02:e00:ffec::1 dev enp0s3".

For anyone else finding this through google, there's an ongoing pull request that makes routing configurable in your configuration.nix: https://github.com/NixOS/nixpkgs/pull/27688

**Comment by volth** [comment]
Maybe related: https://github.com/NixOS/nixpkgs/issues/28474
Just adding IPs + ```nixos-rebuild switch``` might not be enough for the IPs to appear in ```ifconfig```, some more systemd scripts have to be restarted

**Comment by qknight** [comment]
@rszibele instead of `ifconfig` might not be the best choice for debugging. instead you should provide the output of `ip -6 a` and `ip -6 r`
