### ISSUE TITLE
nix instantiate failes on fresh clone of release-17.03

### ISSUE THREAD

**Issue by jascase901** [NixOS/nixpkgs#27128]
## Issue description
I was following this tutorial
http://lethalman.blogspot.it/2014/09/nix-pill-15-nix-search-paths.html
and a received a notice saying 

error: Package ‘Agda-Sheaves-8a06162a8f0f7df308458db91d720cf8f7345d69’ in ‘/home/jason/nixpkgs/pkgs/development/libraries/agda/Agda-Sheaves/default.nix:18’ is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.
### Steps to reproduce
`git clone https://github.com/NixOS/nixpkgs.git mypkgs`
`cd mypkgs/`
`git fetch`
`git checkout release-17.03`
`export NIX_PATH=mypkgs=/home/jason/mypkgs:$NIX_PATH`
`nix-instantiate  '<mypkgs>'`

## Technical details
17.03.1395.9b948ea439 (Gorilla)

**Comment by FRidh** [comment]
As the error mentions that specific package is currently broken. The Nix pills you're reading are some nice docs, but they're relatively old already and so by now some of the examples are broken or outdated.
