### ISSUE TITLE
Build failure: fractal build broken on darwin

### ISSUE THREAD

**Issue by Endle** [NixOS/nixpkgs#271249]
### Additional context
In this commit: https://github.com/NixOS/nixpkgs/commit/aa9baf42061019f285f964a58e93087f465f3908

Fractal was updated to 5, and the dependency to pipewire was introduced.

Pipewire doesn't support macOS. As discussed by upstream, seems that new version of fractal is dropping support for macOS https://gitlab.gnome.org/GNOME/fractal/-/issues/1279

https://gitlab.gnome.org/GNOME/fractal

### Notify maintainers

@linsui @wegank 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nixpkgs $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
Looks like the fractal never supports darwin...
