### ISSUE TITLE
`nixos-rebuild switch` fails with `Out of memory: Killed process...`

### ISSUE THREAD

**Issue by SimonBrandner** [NixOS/nixpkgs#271280]
### Steps To Reproduce

Run `nixos-rebuild switch`

### Expected behavior

The system to update

### Screenshots

![IMG20231130213959](https://github.com/NixOS/nixpkgs/assets/25768714/6ae04f59-8429-4371-a5e5-be58ab9cc1c3)

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.05 (Stoat), 23.05.4981.5b528f99f73c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alex-fu27** [comment]
From what is visible on the screen here: It is happening while building a package. So I suspect that the compilation process is using too much memory. The default for nix is to run multiple build processes at the same time. I would now check with `htop` on another terminal how many processors and how much memory is utilized during the build, to see if that is indeed the problem. Then look into [Tuning Cores and Jobs](https://nixos.org/manual/nix/stable/advanced-topics/cores-vs-jobs.html#tuning-cores-and-jobs) in the Nix manual: you can for example set
```
nix.settings = { 
    max-jobs = 1;
    cores = 1;
};
```
in your NixOS configuration, to run one process at once. Beware that this only applies if you get the system to successfully build once with that configuration.

**Comment by alex-fu27** [comment]
Oh, and I just found `nixos-rebuild` accepts a `--max-jobs` switch so you could use that without having to build a system with a different configuration first!

**Comment by deftdawg** [comment]
@SimonBrandner how much ram + swap does your system have?

**Comment by deftdawg** [comment]
That should be plenty for building... only thing I'd suggest is to upgrade to 23.11 (if possible) since that's the new stable

**Comment by SimonBrandner** [comment]
Yeah... I finally managed to update my system somehow but it's really been odd getting there...

**Comment by alex-fu27** [comment]
So what did you do to fix this? If you provide a short summary, that will be helpful for people having similar problems in the future.

**Comment by SimonBrandner** [comment]
I am not really sure... It might be `--max-jobs` and `--cores` but I've seen it fail too...
