### ISSUE TITLE
Eclipse-mat crashes on startup

### ISSUE THREAD

**Issue by eldritch-cookie** [NixOS/nixpkgs#271277]
### Describe the bug
eclipse-mat crashes on startup on unstable.
### Steps To Reproduce
1. nix shell nixpkgs#eclipse-mat
2. eclipse-mat

### Expected behavior
the program starts  without crashing.

### Additional context
a different error that also crashes the program happens on nixos-22.11

### Notify maintainers
@ktor 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20231127.8cfef69`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/6h04ab83y72nm16hh9g3llgg0s296ynl-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
Works on recent nixpkgs.
