### ISSUE TITLE
libbsd: Darwin patch fails to apply after upgrade to 0.8.4 (probably 0.8.5 too?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#27120]
## Issue description

Not sure how difficult it'd be to fix this, but thought I'd note it somewhere.

[Hydra build log](http://hydra.nixos.org/build/54892263)

We recently bumped to 0.8.5 but I don't see any reason that would make the patch apply again (although I can't confirm this myself :)).

If it can't be resolved reasonably perhaps the patch should be dropped and "darwin" removed from `meta.platforms`?

EDIT: Looks like libbsd has a separate "port" for OSX: https://github.com/JackieXie168/libbsd which I've filed an issue on (like was done previously, apparently): https://github.com/JackieXie168/libbsd/issues/2

### Steps to reproduce

Try to build libbsd on Darwin; look at Hydra/Travis build failures.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by matthewbauer** [comment]
Yeah, I have just been manually updating the patch since v0.8.3. The "correct" thing to do would be to get the patch applied upstream in libbsd. Perhaps freedesktop doesn't want it though.

/cc @JackieXie168
