### ISSUE TITLE
Child Bash shells misbehave

### ISSUE THREAD

**Issue by DavidEGrayson** [NixOS/nixpkgs#27126]
## Issue description

When I am running `nix-shell`, it seems like any bash process except the top-level process will not have the `bind` builtin, will have a messed up prompt, and will not have an up arrow key that functions properly.

I'd like to know what makes the top-level bash process special.  Does it have a special environment variable or command-line argument passed to it to make it behave better?

I would also suggest fixing this so that child Bash processes are more like the top-level one.

### Steps to reproduce

I am running Nix on Arch Linux (not NixOS).  If I clone this repository, check out commit 7d36ae33df, change into the top-level directory, and run `nix-shell --pure -A hello` then a nice Bash session starts up.  The Bash prompt looks good, and the `bind` builtin is supported.  But if I run `bash` inside that shell to start a child shell, I get a shell that is a lot worse.  The prompt reverts back to the default prompt that I specify in `~/.bashrc` of the Arch Linux system (except with extra slashes added), and `type bind` returns an error, and the up arrow key stops working properly (types `^[[A` instead of going through the command history).  I can also demonstrate the issue quickly by just running `bash -c "type bind"`.  Here is a shell session showing the issue:

```
$ nix-shell --pure -A hello

[nix-shell:~/nixpkgs]$ type bind
bind is a shell builtin

[nix-shell:~/nixpkgs]$ bash
\[\]\[\]david@davidvm5 \[\]~/nixpkgs\[\]
$ type bind
bash: type: bind: not found
\[\]\[\]david@davidvm5 \[\]~/nixpkgs\[\]
```

## Technical details

* System: Arch Linux x86_64, relatively up-to-date
* Nix version: nix-env (Nix) 1.11.9
* Nixpkgs version: 17.09pre110215.7d36ae33df
* Sandboxing enabled: no (`/etc/nix/nix.conf` does not exist)

**Comment by DavidEGrayson** [comment]
Using `echo $$` and looking in  `/proc`, I determined that the top-level bash process is started with arguments like this:

    bash  --rcfile /run/user/1000/nix-shell.ivrqCt/rc

Running that command in the `nix-shell` results in a bash shell with a better prompt (`bash-4.4$`), but it's not the same as the top-level prompt, and `type bind` still says `not found`.

**Comment by copumpkin** [comment]
This feels more relevant to Nix than to Nixpkgs: https://github.com/NixOS/nix/issues/756 https://github.com/NixOS/nix/issues/730

**Comment by DavidEGrayson** [comment]
OK, yeah, it's hard to say where this issue should be placed.  I'm OK if someone wants to close it.  I filed it here because I think nixpkgs is doing something special to make the top-level shell work nicely, because when I make a derivation in my own naive way with Nix's built-in `derivation` command and `bash` from nixpkgs as the builder, I get the same bad behavior at the top level Bash process (e.g. the up arrow doesn't work).  I'd be interested to know what nixpkgs is doing to make the top-level Bash work properly, because that would help me for my use case and that could help make the child processes work too.

**Comment by DavidEGrayson** [comment]
Actually, I'm wrong about that.  I'm going to close this.

**Comment by DavidEGrayson** [comment]
OK, I figured it out.  The `bash` derivation from nixpkgs does not have readline support.  That seems silly to me, but I suppose it speeds most builds up by a small amount.  There is a `bashInteractive` package you can use if you want readline support.

By default, the `nix-shell` command will run whatever `bash` executable it finds on its PATH.  I'm not sure exactly how it builds this PATH, but it tends to use your host system's path as one of the components, so it tends to find your `/usr/bin/bash`.  It also uses the `PATH` from your derivation, so if you naively put the nixpkgs `bash` on your `PATH`, like I did then `nix-shell` will use it and you get the bad behavior I was seeing.

So when you run `bash` or `nix-shell` inside a `nix-shell`, you get non-interactive Bash.

The shell used by nix-shell can be overridden with the `NIX_BUILD_SHELL` environment variable.

**Comment by copumpkin** [comment]
That makes a lot of sense, thanks!

**Comment by DavidEGrayson** [comment]
Glad you appreciated it.  I edited my post many times, hopefully you saw the final one.  :-)

**Comment by DavidEGrayson** [comment]
If we are thinking about how to change nixpkgs and nix-shell together to be better, I think you should consider what will happen if the users runs `bash` or `nix-shell` inside a `nix-shell`.  Here are the things I would like, which we don't have with the current setup:

1. Derivations should be able to set a `PATH` environment variable.  (The status quo is that if a derivation sets `PATH`, it overrides the `PATH` from the host system so you can't use utilities from the host from `nix-shell`, e.g. git.)
1. When you run `bash` inside a `nix-shell`, by default it should behave like a normal Linux environment does, and should start the same `bash` executable that you were already running.  (The status quo is that `nix-shell` uses the host's PATH to find `bash` when it starts, and then the derivations `$stdenv/setup` script will add a non-interactive (i.e. unfriendly) `bash` to its `PATH`, so if the user runs `bash` again they get a different shell.)
1. Besides just using the same `bash` executable, it would be nice if child shells used the same startup files.  (The status quo is that `nix-shell` passes some arguments to bash to get it to use a special startup file that sets a particular prompt.  I'm not sure how to fix this and it's probably not a big deal.)
1. Derivations should be able to specify a setup script to get run by `nix-shell` without having to create an extra directory.  (The status quo is that `nix-shell` executes `$stdenv/setup` if it exists, so an unneeded directory must be created.)

We can reach goals 1, 2, 3, and 5 in a simple way by making these changes:

- `nixpkgs` should set the `PATH` environment variable for its derivations and not modify `PATH` in `$stdenv/setup`.  (This lets us know what the `PATH` will have on it before we start the shell, and moving logic from shell scripts to Nix is generally good IMHO.)
- `nix-shell` should set the `PATH` for itself and the child bash process to be the `PATH` from the derivation with the `PATH` from the host system appended to it (unless `--pure` is not specified, in which case ignore the `PATH` from the host system).
- `nix-shell` should use that combined `PATH` to find `bash`. (This part is easy, it would already happen by default when `nix-shell` runs `execvp("bash", ...);)

One other nice thing about this is that a derivation would not need to put `bash` on its `PATH`.  Such a derivation could still benefit from `nix-shell`, which will use host system's bash.  But they can specify `bash` if they want to, and `nix-shell` will always use it.

**Comment by Ericson2314** [comment]
@DavidEGrayson I basically agree with everything you wrote. But rewritting the `propagated*BuildInputs` logic will take a good, but so I'd like to come up with an intermediate step we can do immediately.

> unless --pure is not specified

I think you mean unless it *is*?

> The bash that nixpkgs puts on the PATH by default should be have readline support.

I'd like the same "use bash from PATH logic" to apply whether we're doing a `nix-shell` or `nix-build`, but that means we'd need to conditionally control what the derivation's `PATH` attribute looks like. Is that OK?

**Comment by DavidEGrayson** [comment]
Thanks, yeah, I fixed that typo.  No, I was not trying to imply we would conditionally switch between interactive and non-interactive Bash shells.  I was trying to imply that the non-interactive one isn't useful and should be removed or at least renamed to something like `bashNoReadline` so everyone gets a fully-functioning shell by default.

**Comment by DavidEGrayson** [comment]
I didn't know much about the propagated build inputs, thanks for pointing that out.

**Comment by DavidEGrayson** [comment]
I suppose it's OK if things still get added to the PATH in `$stdenv/setup`, as long as they aren't named `bash`, which should be on the `PATH` of the derivation if it is used.

**Comment by Ericson2314** [comment]
@DavidEGrayson 

I wouldn't be opposed to changing the names (maybe `bash` and `bashMinimal`), but I assume for simplified bootstrapping we still want to use the minimal bash at build time? Maybe it's not worth it, but I wouldn't mind if the condition isn't too hard.

----

I think a good interface would be
```nix
builtins.derivation {
  PATH = builtins.map (p: p + "/bin/") [ foo bar baz ];
  # Nix will append rather than overwrite, using the specified deliminator, in an impure nix-shell 
  __listDelims = {
    PATH = ":";
    # Space is default, like today.
  };
  ...
}
```

Until the propagation logic is rewritten, nixpkgs can just do `PATH = [ (if ERRRR_SOMETHING then bash else bashMinimal) ]`

---

Also, don't get me wrong. `stdenv/setup` is way too complex and should be Nix anways.

**Comment by DavidEGrayson** [comment]
I downloaded the Linux i386 bootstrap tools referenced in nixpkgs and I didn't actually see a Bash there, so maybe the bootstrapping uses the host's bash.  Either way, I assume we need to use some premade Bash before making the final nixpkgs Bash, and then we should use that premade Bash to build a real nixpkgs bash with readline support; I don't see the need for an intermediate Bash between those two that is just missing this one feature.

You said "space is default"; if you're implying that nix-shell should merge environment variables other than `PATH`, I'm not sure why.  The whole `__listDelims` thing seems premature since it will probably be fine for `nix-shell` to just know how the PATH works and treat it specially.

Thanks for the last comment though; I'm glad your on board with less shell script and more Nix :-)
