### ISSUE TITLE
lua: modules are not discoverable

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27135]
## Issue description

Paths to lua modules are not appended to ```$LUA_LIBDIR```

### Steps to reproduce

```bash
#!/usr/bin/env nix-shell
#!nix-shell --show-trace -i bash -p bash lua luaPackages.luasocket

echo "LUA_LIBDIR=$LUA_LIBDIR"
lua -e '_G.require("socket")'
```

```bash
#!/usr/bin/env nix-shell
#!nix-shell --show-trace -i bash -p bash luajit luajitPackages.luasocket

echo "LUA_LIBDIR=$LUA_LIBDIR"
luajit -e '_G.require("socket")'
```

![](http://i.imgur.com/oPFotpN.png)

## Technical details

* System: 17.09.git.4572611 (Hummingbird)
* Nix version: nix-env (Nix) 1.12pre5413_b4b1f452 
* Nixpkgs version: "17.09.git.e97855a388"      
* Sandboxing enabled: false

**Comment by vcunat** [comment]
Let's not duplicate https://github.com/NixOS/nixpkgs/issues/25830
