### ISSUE TITLE
CUPS printing from the Internet not supported

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#27139]
## Issue description

I'm trying to set up a print server so that my other computers on the LAN can use that server for printing. However, the print server refuses to print the jobs sent by my other computers and requires authentication. On my client cups logs, I see the following lines:

```
Backend returned status 2 (authentication required)
Job held for authentication.
```

If I open the CUPS web interface on my server, open the administration page, tick the box "Allow printing from the Internet" and save the changes, then printing works flawlessly. However, I couldn't find any way to enable this setting by using the nix configuration. It would be great if this setting could be set using the nix expressions. Making changes via CUPS web interface, creates a new `cupsd.conf` file inplace of the symlinked file, and thus, I suppose, one loses the ability to configure the CUPS server via the nix expressions.

### Steps to reproduce

Relevant parts of the print server configuration:

```
    networking.firewall = {
      allowedTCPPorts = [ 631 ];
      allowedUDPPorts = [ 631 ];
    };

    services = {
      printing = {
        enable = true;
        browsing = true;
        webInterface = true;
        gutenprint = true;
        defaultShared = true;
        listenAddresses = [ "*:631" ];
      };
      avahi = {
        enable = true;
        nssmdns = true;
        publish = {
          enable = true;
          userServices = true;
        };
      };
    };
```

Relevant parts of the client configurations:

```
    services = {
      printing = {
        enable = true;
        webInterface = true;
        gutenprint = true;
      };
      avahi = {
        enable = true;
        nssmdns = true;
      };
    };
```

Add the printer on the print server, then add it on the clients. Send a print job on a client machine and see the logs `journalctl -u cups`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
17.03.1462.72c9ed78d0 (Gorilla)
```

* Nix version: (run `nix-env --version`)

```
# nix-env --version
nix-env (Nix) 1.11.11
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1462.72c9ed78d0"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

```
# grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = false
```

**Comment by ryneeverett** [comment]
Fixed by #86013. The "Allow printing from the Internet" button does three things which are all now configurable:

1. `Listen localhost:631` -> `Listen 631` (`services.printing.listenAddresses = [ ":631" ];`)
2. `Browsing On` (`services.printing.browsing = true;`)
3. `Allow all` in `<Location />` (`services.printing.allowFrom = [ "all" ];`)
