### ISSUE TITLE
vscode: Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.

### ISSUE THREAD

**Issue by cu1ch3n** [NixOS/nixpkgs#271461]
### Describe the bug

I am using Gnome Wayland. I am trying to run `code` in the console and get the following warnings:

```console
➜  ~ code
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
```

By the way, I cannot use input method (fcitx5-rime) on Chromium or most Electron apps (including vscode) after some upgrades. Not sure if it is related or I need to open a new issue to report it.

### Steps To Reproduce
1. Run `vscode` with `code` in the console
2. observe the warnings

### Expected behavior

- No warnings
- Input method (fcitx5) is functional in vscode

### Notify maintainers

@eadwu 
@Synthetica9 
@amaxine 
@bobby285271 
@Enzime 

@poscat0x04 

### Metadata

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231129.e92039b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/mdl8yp9lzzzjla69qm42sk96p15vym7d-source`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
unfortunately, the answer is to stop using ozone wayland, i.e. remove the envvar NIXOS_OZONE_WL from your config

**Comment by pearsche** [comment]
also, this is fine, it's not bad

**Comment by eclairevoyant** [comment]
@pearsche ?

**Comment by pearsche** [comment]
I should've been clear. Those warnings are not negative. They just warn the user because they're not a default setting. Just telling the OP in case they didn't know.

**Comment by cu1ch3n** [comment]
> unfortunately, the answer is to stop using ozone wayland, i.e. remove the envvar NIXOS_OZONE_WL from your config

@eclairevoyant Thanks! It works! I will close the issue.

**Comment by eclairevoyant** [comment]
Glad to help. More context about this behaviour is explained in https://github.com/NixOS/nixpkgs/pull/262343.

**Comment by pearsche** [comment]
oh wow, sorry, didn't see...

**Comment by C0rn3j** [comment]
https://github.com/microsoft/vscode/pull/135191

There is no way to catch the warning on the Electron app side, according to a VSC dev.

Luckily support for a global env var for all electron apps was added in https://github.com/electron/electron/pull/39792

**Comment by cu1ch3n** [comment]
It is worth noting that IME works with `NIXOS_OZONE_WL` on, though running `code` from terminal still gives
```
➜  ~ code                                             
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by yajo** [comment]
> the answer is to stop using ozone wayland, i.e. remove the envvar NIXOS_OZONE_WL from your config

> Luckily support for a global env var for all electron apps was added in [electron/electron#39792](https://github.com/electron/electron/pull/39792)

[In the wiki](https://wiki.nixos.org/wiki/Wayland#Electron_and_Chromium) it still tells us to add that environment variable. Should that be removed or changed to the new upstream one?

**Comment by eclairevoyant** [comment]
> It is worth noting that IME works with `NIXOS_OZONE_WL` on

It's been a year and a half now, things have changed massively since my original comment.

`NIXOS_OZONE_WL=1` will now work for wayland IME input, but since basically nobody (mir and weston) support text input v1, the additional flag `--wayland-text-input-version=3` must be passed.

i.e. if you have the ozone wl envvar set, you can run `code --wayland-text-input-version=3`, and IME input will work in just about any compositor (except some few stragglers as mentioned in https://wayland.app/protocols/text-input-unstable-v3).


> though running `code` from terminal still gives
> 
> ```
> ➜  ~ code                                             
> Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
> Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
> Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
> ```

As mentioned that is (for now) expected and you will just have to ignore those.

**Comment by C0rn3j** [comment]
> As mentioned that is (for now) expected and you will just have to ignore those.

I don't see why that should be the case for at least the ozone hinting, as that can be done through an env var, as I pointed out here https://github.com/NixOS/nixpkgs/issues/271461#issuecomment-1934829672

`ELECTRON_OZONE_PLATFORM_HINT=auto`

Although I don't use Nix so there may be some nuance to this that I am missing.

**Comment by eclairevoyant** [comment]
Because the entire point of this issue was about IMEs working in ozone wayland windows, and that warning will still be there.

**Comment by eggplants** [comment]
Any updates on this? These warnings still remain on [my env](https://github.com/eggplants/setup-ubuntu.sh).

```shellsession
❯ code .
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'wayland-text-input-version' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by eclairevoyant** [comment]
Feel free to ask on discourse.nixos.org about how to update your system.
