### ISSUE TITLE
qtcreator broken on nixos-unstable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#27148]
## Issue description
```
/nix/store/x9v0yxy5iybp2m2ccqwqkvxgjy7zrw8f-binutils-2.28/bin/ld: cannot find -lQt5Widgets
/nix/store/x9v0yxy5iybp2m2ccqwqkvxgjy7zrw8f-binutils-2.28/bin/ld: cannot find -lQt5Gui
/nix/store/x9v0yxy5iybp2m2ccqwqkvxgjy7zrw8f-binutils-2.28/bin/ld: cannot find -lQt5Core
````
when compiling new or existing project in QtCreator. No such issue on nixos-17.03 branch.
Is it only for me?

### Steps to reproduce
(careful) rm -r ~/.config/QtProject*
```
nix-shell -p qtcreator qt5.full gnumake gcc --command qtcreator
````
try to compile new or existing project

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09.git.01c3847 (Hummingbird)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by FRidh** [comment]
Maybe @romildo can help out here.

**Comment by gnidorah** [comment]
I've found that on nixos-17.03, qt5 has dynamic libraries (/nix/store/0ah3j5zvngvy46xp9r1xba9g0snm2l81-qt-5.6.2/lib/*.so), while they are missing on nixos-unstable (no /nix/store/2avh0a9yjfr807b4lw677zjnqajhmjjp-qt-5.9.0/lib/*.so)

**Comment by romildo** [comment]
> Is it only for me?

I am able to reproduce the issue.

>     nix-shell -p qtcreator qt5.full gnumake gcc --command qtcreator

**Fix**: add `qt5.qtbase` to package list:

```
nix-shell -p qtcreator qt5.full qt5.qtbase gnumake gcc --command qtcreator
```

With that the project compiles and runs.

Probably `qt5.full` used to contain `qt5.qtbase` and does not anymore.

**Comment by gnidorah** [comment]
@romildo That works, thank you! :-)
