### ISSUE TITLE
PostGIS/GDAL contain unfree dependencies

### ISSUE THREAD

**Issue by phile314-fh** [NixOS/nixpkgs#27146]
## Issue description

Postgis in the default configuration cannot be installed anymore without enabling unfree software.

### Steps to reproduce

```
$ nix-shell -p pkgs.postgis.v_2_3_1
error: Package ‘szip-2.1’ in ‘/nix/store/hxks8dzzv92j5h0177p7r2kv6x9vr90n-nixos-unstable.tar.gz/pkgs/development/libraries/szip/default.nix:11’ has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

```
$ nix-shell -p pkgs.gdal
error: Package ‘szip-2.1’ in ‘/nix/store/hxks8dzzv92j5h0177p7r2kv6x9vr90n-nixos-unstable.tar.gz/pkgs/development/libraries/szip/default.nix:11’ has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

## Technical details

* System: NixOS 17.09 unstable
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: 01c3847b9c656d3829dd947395aacd0f84178eb2
* Sandboxing enabled: no

Dependency Path: Postgis -> GDAL -> hdf4 -> szip

PR introducing this issue: https://github.com/NixOS/nixpkgs/pull/26039

**Comment by phile314-fh** [comment]
I will make a PR to disable szip by default in hdf4.

**Comment by 0xABAB** [comment]
@phile314 The license says that you can do *decoding* of szip, just no *encoding* if you distribute. *However*, in the case of Nix, distributing *instructions* to build the whole thing wrong *source* is *OK*. So, it's just a matter of changing the defaults and allowing for a code path to build from source. 

Disabling might be a safe solution from a legal point of view, but it's not what the users want to hear.

**Comment by phile314-fh** [comment]
Is the szip functionality actually used? Quoting https://trac.osgeo.org/gdal/wiki/HDF 

> The szip option is not widely used, and may be omitted for simplicity. 

szip license see https://support.hdfgroup.org/doc_resource/SZIP/

@0xABAB I am not sure I understand. We can certainly include szip in nixpkgs, but as far as I know Hydra does not build unfree software and having unfree software in PostGIS is annoying for deployments. So I am arguing to disable szip by default, and you can enable it again e.g. in your ~/.config/nixpkgs/config.nix using an override.

cc @knedlsepp

**Comment by 0xABAB** [comment]
@phile314-fh You have now disabled it completely by default, which is more strict than the license says. More details in the PR. I am well aware of Hydra's legal status, which is why I gave my initial comment.

**Comment by knedlsepp** [comment]
@phile314-fh: When adding the hdf4 support I was aiming for feature-completeness, so I simply included the szip dependency. I'm fine with it being disabled by default though.
