### ISSUE TITLE
Build failure: python3Packages.databricks-connect

### ISSUE THREAD

**Issue by kirillrdy** [NixOS/nixpkgs#271585]
### Steps To Reproduce

1. python3Packages.databricks-connect

### Build log

```
trying https://files.pythonhosted.org/packages/source/d/databricks-connect/databricks-connect-11.3.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

trying https://pypi.io/packages/source/d/databricks-connect/databricks-connect-11.3.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0   2069      0 --:--:-- --:--:-- --:--:--  2103
100   297  100   297    0     0    838      0 --:--:-- --:--:-- --:--:--   838
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download databricks-connect-11.3.6.tar.gz from any mirror
```

### Notify maintainers

@kfollesdal 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3, NixOS, 24.05 (Uakari), 24.05.20231130.451d197`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
@ghpzin thank you for you response, do you use nixpkgs and databricks-connect ?

**Comment by ghpzin** [comment]
Not using it myself.
But I thought it might be worth commenting that other than updating version to currently existing one on pypi there is not much that can be done (and regularly do check/update, probably manually because of unfree license).
Because pypi allows direct removal of versions and as you can see from "release history" there are a lot of versions that databricks removed.

**Comment by kirillrdy** [comment]
I might try to get 11.3.25 working, otherwise without any users/maintainers interest it will be just marked as broken
