### ISSUE TITLE
Crash possibly due to broken hardware

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27171]
## Issue description
A server crashed for unknown reason with the following message:

`nmi iock error (debug interrupt ) for reason 61 on cpu 0 ` 

### Steps to reproduce
Motherboard: http://www.asrockrack.com/general/productdetail.asp?Model=C2550D4I#Specifications
Soldered CPU: Intel(R) Atom(TM) CPU  C2550  @ 2.41GHz

## Technical details

https://www.extremetech.com/computing/244074-intel-atom-c2000-bug-killing-products-multiple-manufacturers might be related. 

https://access.redhat.com/solutions/42261 describes the issue in some detail and basically says that one needs to contact the hardware vendor. 
* System: (NixOS: 17.03.git.aa03833 (Gorilla)

**Comment by knedlsepp** [comment]
I'm not exactly sure why this on the nixpkgs issue-tracker. Do you think there is something in nixpkgs that needs fixing?
