### ISSUE TITLE
groff: renders weird ~ and ^ characters in man pages under UTF-8, since 1.23

### ISSUE THREAD

**Issue by bryango** [NixOS/nixpkgs#271810]
### Describe the bug

For example, `~/.gitconfig` is rendered as `˜/.gitconfig`. This makes the man page unsearchable.

See e.g. [the archlinux bug report](https://bugs.archlinux.org/task/79290). This seems to be the intended behavior for the upstream groff, but unexpected for downstream `man` users. Patches are already available in distributions; see e.g.
- archlinux [`site.tmac`](https://gitlab.archlinux.org/archlinux/packaging/packages/groff/-/blob/e474b541a32fc905b4f748de0313acfb8b98c081/site.tmac#L17-26)
- debian [`mandoc.local`](https://salsa.debian.org/debian/groff/blob/d5394c68d70e6c5199b01d2522e094c8fd52e64e/debian/mandoc.local#L3-17)

### Steps To Reproduce

```console
$ locale           
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=

$ nix run nixpkgs#man -- git-config
...
       •   Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files
           generated by the user’s editor of choice) generally go into a file specified by
           core.excludesFile in the user’s ˜/.gitconfig. ...
...
```

Note that many other man pages are similarly affected. This is just one example.

### Expected behavior

For example, the string `~/.gitconfig` in `man gitignore` is rendered as-is.

### Additional context

As a temporary workaround, one can set `LC_CTYPE=C` for man pages. The patches for [`site.tmac`](https://gitlab.archlinux.org/archlinux/packaging/packages/groff/-/blob/e474b541a32fc905b4f748de0313acfb8b98c081/site.tmac#L17-26) are already there, but I don't understand the syntax at all so I do not feel comfortable to submit a PR. Moreover, since this would most definitely lead to a mass rebuild, I think it would be better to leave the patching to some steady hands:

### Notify maintainers

@afh @pSub 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m" | sed -E "s|$HOME|\$HOME|g"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62-1-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `$HOME/.nix-defexpr/channels/nixpkgs`

$ nix registry list | grep nixpkgs | grep user
user   flake:nixpkgs github:NixOS/nixpkgs/45827faa2132b8eade424f6bdd48d8828754341a
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bryango** [comment]
Thank you for the reply! I took a closer look at this today, and it seems that the current solution is already `man` specific: the `site.tmac` file is not applied globally, but only to the man page output; see e.g. [the relevant sections of the arch build script](https://gitlab.archlinux.org/archlinux/packaging/packages/groff/-/blob/e474b541a32fc905b4f748de0313acfb8b98c081/PKGBUILD#L56-60), or the current nixpkgs implementation:
https://github.com/NixOS/nixpkgs/blob/f38338ad11b408cfdb2403e36feb21f6ef78b05d/pkgs/tools/text/groff/default.nix#L81-L86
where `/usr/share/groff/site-tmac/{man,mdoc}.local` are the `man` specific customizations. This is documented in the _Files_ section in `man groff_{man,mdoc}`. Maybe it's better to move this to the `man` package instead of leaving it in `groff`? I have no idea...

**Comment by afh** [comment]
Thanks for digging into this @bryango, very well done and much appreciated! 🙏
I mistook `site.tmac` as a groff global customisation forgetting about the `postInstall` in groff's default.nix.

After a bit more research I went ahead and created #272363, would you be willing to test that?

**Comment by bryango** [comment]
Wow brilliant! I have tested the rebuilt `man-db` and it looks awesome! Please find more details in the PR.
