### ISSUE TITLE
nfs-utils.service executes /bin/true???

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27185]
## Issue description

`/bin/true` doesn't even exist on NixOS, so why would it reference it? @abbradar 

```
cat /nix/store/b3ld96a0fb6w2dqajhm34g8j4j6ffnnk-nfs-utils-2.1.1/etc/systemd/system/nfs-utils.service
[Unit]
Description=NFS server and client services
# This service should never be stopped, only restarted.
# When it is re-started, all other services which declare
# themselves to be "PartOf" this service will also be
# restarted. Thus
#   systemctl restart nfs-utils
# will restart all daemons which are part of nfs-utils
# and which are running.  This is useful after a software
# update.

# This is a "service" rather than "target" so that we
# don't need to say "systemctl restart nfs-utils.target".
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
```

## Technical details

* System: (NixOS: 17.03.git.81fceb2 (Gorilla))

**Comment by 0xABAB** [comment]
It needs to call `/run/current-system/sw/bin/true` instead.

**Comment by copumpkin** [comment]
I don't think NixOS uses that service file does it? We generally manage the content of the service files almost entirely through the NixOS module system, so it's quite possible someone just didn't notice it there.

**Comment by 0xABAB** [comment]
@copumpkin I saw in my logs that it was calling it.

**Comment by copumpkin** [comment]
I guess you're right, never mind! That's certainly unusual 😄
