### ISSUE TITLE
fetchFromGithub doesn't work with fetchSubmodules when using tag as rev

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#27180]
I'm trying

```nix
  src = fetchFromGitHub {
    owner = "KDAB";
    repo = "hotspot";
    rev = "v1.0.0";
    sha256 = "09ly15yafpk31p3w7h2xixf1xdmx803w9fyb2aq7mhmc7pcxqjsx";
    fetchSubmodules = true;
  };
```

But when building I just get `Bad commit hash or bad reference.`.

It works when I change to an explicit SHA (`rev = "352687bf620529e9887616651f123f922cb421a4";`).

It also works when I remove `fetchSubmodules = true;`.

---

CC @copumpkin; original support for `fetchSubmodules` in `fetchFromGithub` was added in #15559

**Comment by volth** [comment]
Duplicate
https://github.com/NixOS/nixpkgs/issue/21620
https://github.com/NixOS/nixpkgs/pull/26877

**Comment by nh2** [comment]
You're right, it's a duplicate.
