### ISSUE TITLE
haskellPackages.postgrest broken

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#271868]
### Steps To Reproduce

```
$ nix-build -A haskellPackages.postgrest
```

### Additional context

The package refuses to evaluate because `configurator-pg-0.2.7` is marked as broken; after fixing that a number of other issues occur.
I managed to get it to work locally by applying the following nixpkgs overlay (mostly changing package versions) - but I don't know how to make a proper PR for the Haskell package set that fixes all these issues in the correct way. Maybe some kind maintainer can help me out?

I have also tried with the latest `haskell-updates` branch but that does not resolve the issues.

```
(final: prev: {
  haskellPackages = prev.haskellPackages.override {
    overrides = let
      inherit (pkgs.haskell.lib.compose)
        doJailbreak
        markUnbroken
        overrideSrc
        overrideCabal
        addBuildDepends
      ;
    in
      self: super: {
        configurator-pg = pkgs.lib.pipe super.configurator-pg [
          markUnbroken
          doJailbreak
        ];
        fuzzyset = pkgs.lib.pipe super.fuzzyset [
          markUnbroken
          (overrideCabal (drv: {
            version = "0.2.4";
            sha256 = "sha256-tsOPShYkKxCccIwKj1aL4rURgXWN4N8HJyV5Jn5pRmY=";
            revision = "0";
            editedCabalFile = "sha256-8bbei/Myd79iVSB1QdZQKPHx6pOvVUG2VMhrVnSZVIU=";
          }))
          (addBuildDepends [
            self.data-default
          ])
        ];
        hasql-pool = pkgs.lib.pipe super.hasql-pool [
          (overrideCabal (drv: {
            version = "0.10";
            sha256 = "sha256-EeyKo3NPIpBLv6e7DVQYMus3soGtMC/IzKVg6qBWBZY=";
            revision = "0";
            editedCabalFile = "sha256-kSGXoyisuFUF+Yu5cA1h82a4dlnKRRJsXC1jZoe4AcM=";
          }))
        ];
        postgrest = pkgs.lib.pipe super.postgrest [
          (overrideSrc {
            version = "11.2.2";
            src = pkgs.fetchFromGitHub {
              owner = "PostgREST";
              repo = "postgrest";
              rev = "v11.2.2";
              hash = "sha256-6Nv0NSAiNUSg2T/cmWs7zGSInLSmF0WDA3E/KxlA7O8=";
            };
          })
          (addBuildDepends [
            self.extra self.fuzzyset self.cache self.timeit
          ])
        ];
      };
  };
})
```

### Notify maintainers

@cdepillabout @sternenseemann 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231123.79245fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(frijters): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Zer0-** [comment]
I'm currently using your overlay as a fix, so thank you. `configurator-pg` had [this PR](https://github.com/PostgREST/configurator-pg/pull/20#event-11183984408) merged recently that should fix it not building because the megaparsec version is too high. So I guess what we need is a PR against nixpkgs to bump the postgrest version to 11.2.2, but what's going on with `fuzzyset` and `hasql-pool`?

**Comment by SFrijters** [comment]
* `fuzzyset` is marked as broken in nixpkgs (even though it doesn't seem to be), but if I only `markUnbroken` I get a bunch of build errors in `postgrest` related to functions that are not (no longer) exported, so I downgraded it from 0.3.1 -> 0.2.4 which still has these functions. I tried to add it to the list of packages that retain an old version in nixpkgs but the autogenerated files don't seem to incorporate it, so I'm probably doing something wrong - hence my appeal to the Haskell team.
* `hasql-pool` has also seen a relevant breaking API change: the signature of `SQL.acquire` seems to have changed. In this case a newer version was required, so I assume this will be automagically fixed in nixpkgs when new snapshots are used. And hopefully this will include a version bump of `postgrest` itself as well.

Note that I'm not overly familiar with any of these packages: I just use postgrest in a demo similar to https://nixos.wiki/wiki/NixOS_Testing_library - which makes me want to get this fixed since new people might try this and run into these issues with the current nixpkgs. I now also saw that https://nix.dev/tutorials/nixos/integration-testing-using-virtual-machines is now using a simpler example, so for my use case I might just switch to that as well.

**Comment by maralorn** [comment]
@SFrijters If you start a PR which displays your PR we can iterate on it. If this is only about pinning a few packages to the right versions, this should be doable. Also the interest in this issue seems so big, that it seems worth it.

I don’t know, however, if we can get the fix in for the current haskell-updates generation. Depends on when I have the time to finish it up.

**Comment by SFrijters** [comment]
Fixes have hit `haskell-updates`; I'll close this issue when they hit master.

**Comment by SFrijters** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/275614 ; thanks to @maralorn and @rvl for their help!
