### ISSUE TITLE
FreeFileSync "Options" not opening when language is set to anything other than english

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#271842]
FreeFileSync "**Options**" is not opening when the language is set to anything other than **English**.

I am using NixOS 23.11 and Gnome. System is up to date, nothing special installed.

![FreeFileSync Options](https://github.com/NixOS/nixpkgs/assets/4227548/4d933a9d-224c-4df8-9406-8be184e376ca)

**Comment by boustanihani** [comment]
Yeah maybe if the package gets updated to v13.2 the problem would be fixed.
I have v13.2 on another system without any problems..

**Comment by nPrevail** [comment]
I too have had this issue. Here's what shows up in terminal when I try to open the "Options", or press any of the "configuration cogs" from the UI:

`(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.220: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.223: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.223: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(FreeFileSync:10366): Gtk-CRITICAL **: 15:17:08.223: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
`

**Comment by boustanihani** [comment]
Seems to be fixed in FreeFileSync 13.2
