### ISSUE TITLE
slimserver isn't working with tidal plugin

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#271880]
### Describe the bug
I try to use slimserver with the tidal plugin. 
Slimserver looks normally (e.g the webui works), but it spams the log with 

```
Dez 03 15:08:21 chump slimserver[1226346]: ; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x8e7d560)
Dez 03 15:08:21 chump slimserver[1226346]: [23-12-03 15:08:21.5782] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: Can't locate object method "_scan" via package "Audio::Scan" at /nix/store/g35r8mg97wnr6cyi0kkn905zx5qf24ma-perl5.38.0-slimserver-8.3.1/lib/Audio/Scan.pm line 106.
Dez 03 15:08:21 chump slimserver[1226346]: ; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x8e7d560)
Dez 03 15:08:21 chump slimserver[1226346]: [23-12-03 15:08:21.5908] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: Can't locate object method "_scan" via package "Audio::Scan" at /nix/store/g35r8mg97wnr6cyi0kkn905zx5qf24ma-perl5.38.0-slimserver-8.3.1/lib/Audio/Scan.pm line 106.
Dez 03 15:08:21 chump slimserver[1226346]: ; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x8e7d560)
Dez 03 15:08:21 chump slimserver[1226346]: [23-12-03 15:08:21.6032] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: Can't locate object method "_scan" via package "Audio::Scan" at /nix/store/g35r8mg97wnr6cyi0kkn905zx5qf24ma-perl5.38.0-slimserver-8.3.1/lib/Audio/Scan.pm line 106.
Dez 03 15:08:21 chump slimserver[1226346]: ; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x8e7d560)
```
and squeezelite isn't outputting any audio when i try to play something (without any error logs)

### Steps To Reproduce
1. install and run slimserver
2. configure the tidal plugin
3. install and run squeezelite
4. try to play something

### Expected behavior
I expect listening to audio but it just keeps silent. 

### Additional context
~~I'm not 100% sure if it's related to the tidal plugin. I just don't have a different audio provider to test with.~~
The logspam only starts as soon as i try to play something. But then it never stops even if i disconnect all players. 

### Notify maintainers
@adamcstephens @jecaro 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ChrisOboe** [comment]
I'm on unstable from today. 
Radio and local media work fine.

**Comment by antonmosich** [comment]
I am also encountering this issue with the qobuz plugin. Also I haven't figured out why, but indexing doesn't work for me, but if i try to play a local file (finding it via the file system option) I also get similar errors complaining about `_scan` not being found etc.

**Comment by adamcstephens** [comment]
When I went to spin this up I discovered that library importing was failing with the same error. After some troubleshooting another vendored version of this library was found. Cleaning this up and upgrading AudioScan to the slimserver fork resolved library importing, and I verified Qobuz is also playing. 

@ChrisOboe and @antonmosich can you test this PR to see if it fixes your issues? Thanks! https://github.com/NixOS/nixpkgs/pull/274070

**Comment by ChrisOboe** [comment]
@adamcstephens i just tested the pr and can confirm that the tidal works fine now. Thank you very much!
