### ISSUE TITLE
./cache/zoxide/init.nu uses deprecated nushell syntax

### ISSUE THREAD

**Issue by MatrixManAtYrService** [NixOS/nixpkgs#271898]
### Describe the bug

I have both nushell and zoxide installed.  When I start nushell it says this:

```
Error:   × Deprecated command
    ╭─[/Users/matt/.cache/zoxide/init.nu:36:1]
 36 │ # Jump to a directory using interactive search.
 37 │ def-env __zoxide_zi  [...rest:string] {
    · ───┬───
    ·    ╰── `def-env` is deprecated and will be removed in 0.88.
 38 │   cd $'(zoxide query --interactive -- $rest | str trim -r -c "\n")'
    ╰────
  help: Use `def --env` instead
```

I can see that this is already fixed in [zoxide main](https://github.com/ajeetdsouza/zoxide/blob/main/templates/nushell.txt#L42) so I assume the fix is simply a matter of updating the version in nixpkgs

### Notify maintainers

@ysndr, @cole-h, @SuperSandro2000, 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ : nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(matt): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
shouldn't zoxide push out a new release first?

**Comment by SuperSandro2000** [comment]
Update got committed instead
