### ISSUE TITLE
New user on Ubuntu can not use nix-env commands

### ISSUE THREAD

**Issue by jarry9** [NixOS/nixpkgs#27184]
Hi,

I installed nix on my Ubuntu 16.04 by this commands:

bash <(curl https://nixos.org/nix/install)
source ~/.nix-profile/etc/profile.d/nix.sh

I installed packages with "nix-env -i vlc" command. I did not use any other commands about nix because I did not needed.

Everything until now was OK. But now I created a new Ubuntu user called "test1".  I logged in with test1, But after this command I get a warning:

cd /nix/var/nix/profiles/default/bin
./nix-env -qaP

error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied

And If I run the command as sudo, I get:

warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
error: getting information about ‘/home/test1/.nix-defexpr’: No such file or directory

I will remove the old user if the test1 user will work. I check the "/nix" directory, the directory is owned by the old user.

Thank you

**Comment by emmanuelrosa** [comment]
It looks like you're missing the multi-user setup. Have you completed the multi-user setup steps? 

See https://nixos.org/nix/manual/#ssec-multi-user

**Comment by jarry9** [comment]
@emmanuelrosa  No, I did not setup anything about multi-user. :(

I don't run the nix-daemon. Is there any solution for that? I have the sudo password of operation system. I can change the file permissions if it is enough.

**Comment by knedlsepp** [comment]
It's [stated in the docs](https://nixos.org/nix/manual/#ch-installing-binary) that what you did
> will perform a single-user installation of Nix, meaning that /nix is owned by the invoking user
To set up a multi-user installation you should follow the instructions in the chapter [Multi-user mode](https://nixos.org/nix/manual/#ssec-multi-user)

**Comment by TerkiKerel** [comment]
I am in the same situation. Is it a must to start nix-daemon? I can not give permission to a user? It should be a solution for that.

**Comment by FliegendeWurst** [comment]
> I am in the same situation. Is it a must to start nix-daemon? I can not give permission to a user? It should be a solution for that.

The solution is to install Nix in multi-user mode.
