### ISSUE TITLE
Keyboard issues since upgrading to 23.11

### ISSUE THREAD

**Issue by datMaffin** [NixOS/nixpkgs#271866]
### Describe the bug
Various keyboard related things broke:
* my custom xkbd layout broke in wayland environments (did not test X11)
* the "de" keymap in the tty loaded via `loadkeys` is missing "öäü".

### Steps To Reproduce
testing the "de" keymap in the tty: just execute `loadkeys de` in a tty window and try to type "öäü".

for my custom keyboard, I have:
```
  # Configure keymap in X11
  services.xserver.extraLayouts = {
    de-lsgtmod = {
      description = "German (less-than as modifier)";
      languages = [ "de" ];
      # Best documentation seems to be: https://www.charvolant.org/doug/xkb/html/node5.html#SECTION00053000000000000000
      # Also, look at similar keyboard configurations.
      #
      # GNOME wayland is currently bugged. For layers >= 5 to work, it is
      # necessary to have the layout in the **first position**.
      # See also: https://gitlab.gnome.org/GNOME/mutter/-/issues/790
      symbolsFile = pkgs.writeText "de-lsgtmod" ''
        partial alphanumeric_keys modifier_keys keypad_keys
        xkb_symbols "de-lsgtmod" {
            include "latin(type4)"
            name[Group1]="German (less-than as modifier)";
            key.type[Group1] = "EIGHT_LEVEL_LEVEL_FIVE_LOCK";
            key <TLDE>  { [dead_circumflex, degree,	U2032,    U2033	] };
            key <AE02>  { [         2,   quotedbl,  twosuperior,    oneeighth ]	};
            key <AE03>  { [         3,    section, threesuperior,    sterling ]	};
            key <AE04>  { [         4,     dollar,   onequarter,     currency ]	};
            key <AE07>  { [         7,      slash,    braceleft, seveneighths, backslash ]	};
            key <AE08>  { [         8,  parenleft,  bracketleft,    trademark, bracketleft ]	};
            key <AE09>  { [         9, parenright, bracketright,    plusminus, bracketright ]	};
            key <AE11>  {type[Group1]="FOUR_LEVEL_PLUS_LOCK",  symbols[Group1]=[ssharp, question, backslash, questiondown, 0x1001E9E ]};
            key <AE12>  { [dead_acute, dead_grave, dead_cedilla,  dead_ogonek ]	};
            key.type[Group1] = "EIGHT_LEVEL_ALPHABETIC_LEVEL_FIVE_LOCK";
            key <AD03>  { [         e,          E,     EuroSign,     EuroSign ]	};
            key <AD06>  { [         z,          Z,    leftarrow,          yen ]	};
            key <AD07>  { [         u,          U,    downarrow,      uparrow, less ]	};
            key <AD08>  { [         i,          I,   rightarrow,     idotless, greater ]	};
            key <AD11>  { [udiaeresis, Udiaeresis, dead_diaeresis, dead_abovering ] };
            key.type[Group1] = "EIGHT_LEVEL_LEVEL_FIVE_LOCK";
            key <AD12>{ [      plus,   asterisk,   asciitilde,  macron ]	};
            key.type[Group1] = "EIGHT_LEVEL_ALPHABETIC_LEVEL_FIVE_LOCK";
            key <AC02>  { [         s,          S,                U017F,     U1E9E    ] };
            key <AC06>  { [         h,          H,      hstroke,      Hstroke, bar ]	};
            key <AC07>  { [         j,          J,        dead_belowdot, dead_abovedot, braceleft ] };
            key <AC08>  { [         k,          K,          kra,    ampersand, braceright ]	};
            key <AC09>  { [         l,          L,      lstroke,      Lstroke, at ]	};
            key.type[Group1] = "EIGHT_LEVEL_LEVEL_FIVE_LOCK";
            key <AC10>{ [odiaeresis, Odiaeresis, dead_doubleacute, dead_belowdot ] };
            key <AC11>{ [adiaeresis, Adiaeresis, dead_circumflex, dead_caron ] };
            key.type[Group1] = "EIGHT_LEVEL_ALPHABETIC_LEVEL_FIVE_LOCK";
            key <AB01>  { [         y,          Y,       guillemotright,    U203A 	] };
            key <AB02>  { [         x,          X,        guillemotleft,    U2039 	] };
            key <AB04>  { [         v,          V,   doublelowquotemark, singlelowquotemark ]	};
            key <AB05>  { [         b,          B,  leftdoublequotemark, leftsinglequotemark ] };
            key <AB06>  { [         n,          N, rightdoublequotemark, rightsinglequotemark, asciitilde ]	};
            key.type[Group1] = "EIGHT_LEVEL_LEVEL_FIVE_LOCK";
            key <AB08>  { [     comma,  semicolon,       periodcentered,     multiply	] };
            key <AB09>  { [    period,      colon,                U2026,     division 	] };
            key <AB10>  { [     minus, underscore,               endash,     emdash	] };
            key <BKSL>  { [numbersign, apostrophe, rightsinglequotemark,   dead_breve ]	};
            include "kpdl(comma)"
            include "level3(ralt_switch)"
            include "level5(lsgt_switch)"
        };
      '';
    };
  };

  # Use my layout
  services.xserver.layout = "de-lsgtmod"; # will make this the default in KDE Plasma.
```

### Expected behavior
the "de" keymap should have the öäü letters.
my custom keyboard should make the "<" key on a german keyboard a modifier key such that "<"+"jkui78" will type "{}<>[]".

### Screenshots
n/a

### Additional context
issues all occurred after upgrading to 23.11. I tried to figure out if anyone on the internet has similar issues, but I did not really find anything.

This may be an issue that is not NixOs specific.

The waylands I used where my custom keyboard map is broken are: KDE and LabWC

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3, NixOS, 23.11 (Tapir), 23.11.1115.5de0b32be6e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by katexochen** [comment]
Might be related to https://github.com/NixOS/nixpkgs/pull/259891 and https://github.com/NixOS/nixpkgs/pull/264787, I'll try to investigate.

Could you check if using `services.xserver.xkb.extraLayouts` instead works?

**Comment by katexochen** [comment]
The options were moved in the previously mentioned PRs. Using the old options should throw a warning. However, I don't get a warning when using them on unstable (e92039b55bcd58469325ded85d4f58dd5a4eaf58). I've checked out the commit where this was introduced, and it doesn't throw a warning their either.

I'm not sure how I can debug this. Any ideas @l0b0 @rnhmjoj?

**Comment by datMaffin** [comment]
Thanks a lot!

Will try the x.xkb.x out later.

**Comment by rnhmjoj** [comment]
No, I doubt it's related to #259891 or #264787: those are just renaming the XKB options.
The [keymap.custom](https://hydra.nixos.org/job/nixos/release-23.11/nixos.tests.keymap.custom.x86_64-linux), which is using X.org is passing, so it's likely a bug or breaking change in GNOME.
GNOME breaking the xkb configuration does not really surprise me.

**Comment by katexochen** [comment]
@rnhmjoj But what about the warnings?

**Comment by datMaffin** [comment]
hm weird.

changing it to "x.xkb.x" does not seem to change anything.

I also do not see any kind of warning using it the old way.

My custom keyboard layout is also broken in a very weird way:
Basically the modifier key doesn't work, and a lot of the keys no longer have any upper-case; instead it will always type the lower case.

For the other issue of the console keymaps `console.keyMap = "de"` being broken (it is missing "öäü" and instead printing the "[ ]..."), should I open a separate issue?

**Comment by datMaffin** [comment]
> No, I doubt it's related to #259891 or #264787: those are just renaming the XKB options.
> The [keymap.custom](https://hydra.nixos.org/job/nixos/release-23.11/nixos.tests.keymap.custom.x86_64-linux) test, which is using X.org, is passing, so it's likely a bug or breaking change in GNOME.
> GNOME breaking the XKB configuration does not really surprise me.

I had this behavior on KDE wayland and labwc (wayland). (I initially thought it was a KDE bug and switched to a different desktop, I wanted to switch to in any case.)

The comment you can see in my config, is just a comment that is left from a past configuration, when I used Gnome.

**Comment by katexochen** [comment]
Have you tried reloading your gsettings? I remember that helped me in the past with custom keymaps:

```
gsettings reset org.gnome.desktop.input-sources xkb-options
gsettings reset org.gnome.desktop.input-sources sources
```

And lock out and back in again.

**Comment by datMaffin** [comment]
I just tried updating a different NixOS install. (that install was basically completely fresh).
With 23.05 the keybinding worked perfectly, and after upgrading, I saw the same issue.

Rolling back to 23.05 again, and the keybinding works perfectly again.

That machine is running KDE Plasma Wayland.

So I do think everyone can reproduce the issue:
If you run KDE wayland, and never changed your keyboard config in the settings menu, you can just paste in my config. The xserver keymap is used by default on KDE Plasma Wayland. 
It's intended for a german keyboard layout, and if you press "<", the keys "jkui78" should print"{}<>[]".

**Comment by datMaffin** [comment]
I can also confirm that the keybinding is also broken in KDE X11. However, it is broken in a slightly different way. (In X11 the capitalization of  all the letters still work)

So I would guess that it is probably a regression upstream. Maybe xkb is somehow broken?

**Comment by datMaffin** [comment]
Jup. Upstream broke the compatibility of the keyboard layout. :(

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/508

The fix was to replace 
`EIGHT_LEVEL_LEVEL_FIVE_LOCK` with 
`EIGHT_LEVEL_WITH_LEVEL5_LOCK`

and 
`EIGHT_LEVEL_ALPHABETIC_WITH_LEVEL5_LOCK` with
`EIGHT_LEVEL_ALPHABETIC_LEVEL_FIVE_LOCK`.

And then restart linux. (just restarting the desktop did not work for me)

I will open a different issue for the wrong "de" (german) keymap in the tty.
