### ISSUE TITLE
dbmate: CLI application not included

### ISSUE THREAD

**Issue by dcecile** [NixOS/nixpkgs#271962]
### Describe the bug
The [dbmate](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/database/dbmate/default.nix) Nix package seems to only install the Go module, and not the CLI application.

### Steps To Reproduce
1. Install dbmate in Nix
2. Run `dbmate`

### Expected behavior
I expected to have the `dbmate` application available on my PATH and see the listing of dbmate commands.

### Additional context
Another Go-based CLI application is [task](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/go-task/default.nix). This package also uses `buildGoModule`, so maybe some patterns can be followed from here?

### Notify maintainers

@manveru 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info
copying path '/nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-88-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/nix/store/7g8wbm1z6948x0qma4hzkkb9a3xys76w-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Misterio77** [comment]
I can't seem to reproduce it. Works fine here:
```
$ nix shell nixpkgs#dbmate
$ dbmate --version
```
