### ISSUE TITLE
rocm-runtime is still using gcc, is about to become broken by gcc13

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nixpkgs#271943]
Heads up: even though it tries to `overrideCC` with `clang`, our `rocm-runtime` expression still uses `gcc` for a ton of stuff.

Try changing `default-gcc-version` in `pkgs/top-level/all-packages.nix` to `13` and you'll see the breakage.  I'm about to merge

- https://github.com/NixOS/nixpkgs/pull/268097

which does this, and it's going to break `rocmPackages`.  I tried to fix it, but the problem is very deep: you guys think you're using only clang, but in fact you're not.

Wanted to give you a heads-up.

cc: @lovesegfault @Madouura  @Flakebi

**Comment by amjoseph-nixpkgs** [comment]
I recommend you guys merge a PR which pins `rocmPackages` to `gcc12Stdenv` wherever you aren't really using `llvm`/`clang`.  I tried to do this, but it's far from clear *where* this needs to be done.

**Comment by Madouura** [comment]
>you guys think you're using only clang, but in fact you're not.

Unfortunately, I'm aware. I was working on making ``rocmPackages`` use only libc/libcxx/etc, but it's rather WIP.

>I tried to do this, but it's far from clear where this needs to be done.

It's likely all the way to the root - ROCm LLVM. It has a GCC backend which is used.

Any chance you could give me the error log for ``rocm-runtime`` so I don't have to rebuild ROCm LLVM and a bunch of other stuff?

**Comment by amjoseph-nixpkgs** [comment]
> Unfortunately, I'm aware.

Ah, that's actually somewhat of a relief.  At least the problem is known.

Log is attached.  I'm happy to test fixes; I have plenty of compute.  After the new year I will be working on making the buildfarm available to other projects; you'll be on the shortlist if you're interested.
[8q1vy1pyk4079vjq3pfqkjmffdvksif2-rocm-llvm-runtimes-5.7.1.drv.log.gz](https://github.com/NixOS/nixpkgs/files/13540542/8q1vy1pyk4079vjq3pfqkjmffdvksif2-rocm-llvm-runtimes-5.7.1.drv.log.gz)

**Comment by amjoseph-nixpkgs** [comment]
Also if you need to get my attention I hang out in `#tvl` on `irc.hackint.org`.  It's bridged to Matrix.

**Comment by Madouura** [comment]
> [8q1vy1pyk4079vjq3pfqkjmffdvksif2-rocm-llvm-runtimes-5.7.1.drv.log.gz](https://github.com/NixOS/nixpkgs/files/13540542/8q1vy1pyk4079vjq3pfqkjmffdvksif2-rocm-llvm-runtimes-5.7.1.drv.log.gz)

Okay, this is ``rocm-llvm-runtimes``, not ``rocm-runtime``. This might be a slightly easier fix then.

> I'm happy to test fixes; I have plenty of compute. After the new year I will be working on making the buildfarm available to other projects; you'll be on the shortlist if you're interested.

I appreciate that, when I put the PR through I might request that you do a ``nixpkgs-review``, possibly a few times if the dependency hell is really bad.
