### ISSUE TITLE
gst_all_1.gst-plugins-good is missing soup, needed for radiotray-ng

### ISSUE THREAD

**Issue by AshleyYakeley** [NixOS/nixpkgs#271960]
### Describe the bug
[According to the GStreamer website,](
https://gstreamer.freedesktop.org/documentation/soup/souphttpsrc.html) the "good" plugins package should contain the "soup" plugin. However, the nix package `gst_all_1.gst-plugins-good` does not.

### Steps To Reproduce
1. install packages `gst_all_1.gstreamer.bin` and `gst_all_1.gst-plugins-good`
2. run `gst-inspect-1.0 | grep soup`

Result: nothing found.

As a result, `radiotray-ng` cannot play any streams, failing with "could not create souphttpsrc element".

### Expected behavior
`gst_all_1.gst-plugins-good` should include `soup`.

### Notify maintainers

`gst_all_1.gst-plugins-good`: @matthewbauer @lilyinstarlight
`radiotray-ng`: @dtzWill

### Metadata

```console
[chalice:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(ashley): `""`
 - nixpkgs: `not found`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
please try 
```sh
nix run github:NixOS/nixpkgs/4d054ee68c41c3eeeeaf4d7ca44512c3274c1397#radiotray-ng
```
and see if that fixes the problem.

**Comment by AshleyYakeley** [comment]
This fixes the problem for `radiotray-ng`, thanks.

Does this mean that `gst_all_1.gst-plugins-good` is OK?

**Comment by a-n-n-a-l-e-e** [comment]
> This fixes the problem for `radiotray-ng`, thanks.
> 
> Does this mean that `gst_all_1.gst-plugins-good` is OK?

not really, in my opinion as it doesn't work out of the box. there was a PR to partially fix gstreamer https://github.com/NixOS/nixpkgs/pull/264293 but seems like it was missing glib-networking and didn't want to add it for some reason.

if the gstreamer pkg isn't modified then adding glib-networking and the libsoup to the ld_library_path is a work around.

**Comment by SuperSandro2000** [comment]
The issue title is misleading. The loading of the library is broken but gst-plugins-good is actually compiled against libsoup.
