### ISSUE TITLE
Libvirt, KVM USB redirection fails

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#27199]
## Issue description
Using USB redirect fails with 'Insufficient permissions'.

### Steps to reproduce
Enable libvirtd and KVM, spin up VM with virt-manager/virsh, try to access USB on spice client.

## Technical details
Nixos 17.09pre110213.01c3847b9c

**Comment by 0xABAB** [comment]
This needs more information. For example, you are not specifying via which user you are trying to do these things.

**Comment by unlmtd** [comment]
User is in wheel and libvirtd. I have found the same issue discussed on arch[1], with some hack changing ownership of the device to group 'spice'. Also, from same thread, assigning the device manually before starting the VM should work(I havent tested this yet, ongoing)

[1]:https://bugs.archlinux.org/task/49179

**Comment by unlmtd** [comment]
Changing the ownership of /dev/bus/usb to 'spice' and adding the user to it works.

**Comment by sjau** [comment]
I'm facing the same issue with virt-manager. Also I have no group "spice". Can you tell me how you got it to work?

Relevant portions of my configuration.nix:

```
    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.defaultUserShell = "/var/run/current-system/sw/bin/bash";
    users.extraUsers.${mySecrets.user} = {
        isNormalUser = true;    # creates home, adds to group users, sets default shell
        description = "${mySecrets.user}";
        extraGroups = [ "networkmanager" "vboxusers" "wheel" "audio" "cdrom" "kvm" "libvirtd" ]; # wheel is for the sudo group
        uid = 1000;
        initialHashedPassword = "${mySecrets.hashedpasswd}";
    };


    # Enable libvirtd daemon
    virtualisation.libvirtd = {
        enable = true;
        enableKVM = true;
    };
    services.spice-vdagentd.enable = true;

    environment.systemPackages = with pkgs; [
        ......
        spice
        win-spice
        virtmanager
        virt-viewer
        ......
    ];

```

**Comment by 22459** [comment]
I think I also have this issue.

**Comment by bjornfor** [comment]
I use this brute force udev rule:

      # Access to /dev/bus/usb/* devices. Needed for virt-manager USB
      # redirection.
      SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", MODE="0664", GROUP="wheel"

(Not sure it's a good idea in general. I'm afraid it may conflict with other more fine grained rules.)

**Comment by steveeJ** [comment]
I run virt-manager with `sudo`  at the moment to workaround this issue. Not ideal either but at least I don't have to modify permissions manually.

Another problem I have with is that USB auto redirection is not working. Can you confirm this? Manual redirection doesn't work well when flashing firmware to a device that intermittently reboots with a different device id.

**Comment by 22459** [comment]
I'd probably rather modify perms for a usb device via udev (I think this is actually sort of the generally accepted method) than run it as root. :/

If by auto redirection you mean automatically redirecting when you plug it in, I pleasantly discovered that's a thing by accident and it does in fact work with the udev solution. Presumably because it does keep it's ID.

I don't know why your device changes it's iD? I thought device IDs were static values....
Ah, unless whatever reflashing you're doing changes your ID. I think udev maybe has other matching functionality so maybe it can match on name for example?

It would be nice if the root cause for this could get fixed but I have no idea what the proper fix would be. I guess it's pretty useless to say this since that's probably what everyone wants.

**Comment by sjau** [comment]
I also modified it by udev:

```
    # Make smartcard reader and label printer accessible to everyone, so they can be passed to the VM
    services.udev.extraRules = ''
        SUBSYSTEM=="usb", ATTR{idVendor}=="072f", ATTR{idProduct}=="90cc", GROUP="users", MODE="0777"
        SUBSYSTEM=="usb", ATTR{idVendor}=="04f9", ATTR{idProduct}=="2043", GROUP="users", MODE="0777"
    '';
```

**Comment by 22459** [comment]
Yes your solution is what I used. :) Lucky google find.

**Comment by sjau** [comment]
still annoying though :)

**Comment by steveeJ** [comment]
> If by auto redirection you mean automatically redirecting when you plug it in, I pleasantly discovered that's a thing by accident and it does in fact work with the udev solution. Presumably because it does keep it's ID.

Nice to hear that it's not generally broken on NixOS ;-) However, it's not a permission issue on my end. I have tried both, using `sudo` and granting access to my user via udev rules.
The issue for me is that virt-manager does not even attempt to redirect automatically, and I have to manually redirect each device.

**Comment by theotheroracle** [comment]
i'm still experiencing this issue
![image](https://github.com/NixOS/nixpkgs/assets/20211219/bf11d454-4806-4788-a529-295acee832b0)

**Comment by theotheroracle** [comment]
i think it may have been that i just needed to enable spiceguestadditions, under virtualization options, further testing may be needed

**Comment by bjornfor** [comment]
Yes, all that should be needed is `virtualisation.spiceUSBRedirection.enable = true;`. I've beein using it for a few NixOS releases.
