### ISSUE TITLE
unzipNLS does not build

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27207]
## Issue description

A `nix-build -A unzipNLS` fails because a patch doesn't apply cleanly. The failure occurs since bef622a4e836999da0d398f78f3968f6b7c629b3 and 95c8277701fb746ad4d91841de494ee869886991.
The expression can be found at `pkgs/tools/archivers/unzip/default.nix`.

cc @Ericson2314

**Comment by Ericson2314** [comment]
Ah, my patch needs to come second because it does not compute.

**Comment by FRidh** [comment]
Fixed with bd129c2b3e033bd92d5c93cca4d516b021d408e6.
