### ISSUE TITLE
kactivitymanager crashes

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27205]
## Issue description
Same problem as  the comment with text `Applied fedeliallalinea's patch on qtcore 5.6.2: ` 
 at https://forums.gentoo.org/viewtopic-t-1030398-start-0.html.

Gentoo already fixed this, I think.

nixpkgs version: 17.03.1482.1b57bf274a
NixOS 17.03.1482.1b57bf274a (Gorilla)

**Comment by 0xABAB** [comment]
Likely same problem as #26837. (do not close for duplicate)

**Comment by peterhoeg** [comment]
I'm not seeing this anymore, so it's probably OK to close this.
