### ISSUE TITLE
Package request: `pkgs.emacsPackages.nongnuDevelPackages`

### ISSUE THREAD

**Issue by hab25** [NixOS/nixpkgs#272051]
**Project description**

NonGNU-devel ELPA Packages; i.e., development versions of the already packaged `pkgs.emacsPackages.nongnuPackages`

**Metadata**

* homepage URL: https://elpa.nongnu.org/nongnu-devel/
* source URL: https://git.savannah.gnu.org/gitweb/?p=emacs/nongnu.git
* license: probably `lib.license.free` (guessed by looking at [nongnu-generated.nix](https://github.com/NixOS/nixpkgs/blob/e8b20a3ef651c4e5da839e85cd739af3c7613a7e/pkgs/applications/editors/emacs/elisp-packages/nongnu-generated.nix))
* platforms: probably all (guessed by looking at [nongnu-generated.nix](https://github.com/NixOS/nixpkgs/blob/e8b20a3ef651c4e5da839e85cd739af3c7613a7e/pkgs/applications/editors/emacs/elisp-packages/nongnu-generated.nix))

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
This feels like something that should only live in the emacs-overlay, not in Nixpkgs.

**Comment by Atemu** [comment]
I think the same about the others.
