### ISSUE TITLE
Use systemd automounts to support a client using  NFS over wifi

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27219]
## Issue description

When mounting an NFS file system over a wireless connection configured via Network Manager in combination with Plasma5 results in a hanging system when the connection is gone or not present yet (as can be the case with wifi). This KDE behaviour has existed for over a decade (https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/164120).

>The autofs module looks pretty unmaintained - it hasn't seen a commit since 2012. We should probably just remove it, unless there is some compelling use case that systemd's automount units don't provide.
https://github.com/NixOS/nixpkgs/issues/27202

I would like to see an example, but preferably a section documented in the manual how to achieve this functionality using just systemd. 

Once that has happened, I'd be OK with deprecating  `autofs` and subsequently removing it. 

Version: master

**Comment by peterhoeg** [comment]
The systemd automount part is straight forward, but it still doesn't fix the issue with a hanging plasma session when the mount is gone. This is how I use it:

```nix
{
  fileSystems = {
    "/storage/media" = {
      device = "nas:/exports/media";
      fsType = "nfs";
      noCheck = true;
      options = [
        "proto=tcp"
        "soft"
        "nofail"
        "_netdev"
        "x-systemd.automount"
      ];
    };
  };
}
```

**Comment by Mic92** [comment]
Stalled processes because of an unavailable network is inherent with NFS. I would not recommend to use unreliable networks + NFS in general. Modern filemanager like dolphin/nautilus supports protocols like `sftp` or `smb`.

**Comment by peterhoeg** [comment]
There is nothing nix specific in this, closing.
