### ISSUE TITLE
corretto19 has wrong `meta.position` (maybe related to usage of `overrideAttrs`?)

### ISSUE THREAD

**Issue by rollf** [NixOS/nixpkgs#272142]
As of today, this search https://search.nixos.org/packages?channel=unstable&show=corretto19&from=0&size=50&sort=relevance&type=packages&query=corretto yields 3 items for Corretto.  The "Source"-buttons for all of them point to OpenJDK even though the package is Corretto.

Corretto has been added [recently](https://github.com/NixOS/nixpkgs/pull/263736) and is based on the corresponding OpenJDK version (using [overrideAttr](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/corretto/mk-corretto.nix#L25C5-L25C18)). At a first glance, the the usage of `overrideAttr` looks like the issue. However, when searching for [htop ](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=htop), the "Source"-button for `htop-vim` correctly points to `htop-vim.nix` eventhough the latter also uses `overrideAttr`.

**Comment by ncfavier** [comment]
Transferred to nixpkgs as nixos-search just uses `meta.position`, which is determined by `mkDerivation` in `pkgs/stdenv/generic/make-derivation.nix`. I am not sure what is going on here exactly, but note that `corretto11` does seem to have the correct position.

**Comment by rollf** [comment]
:arrow_up: I left some context in the [NixOS/nix issue](https://github.com/NixOS/nix/issues/9540) mentioned above. I realize that the actual problem is [here](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/compilers/openjdk/17.nix#L185), i.e. the OpenJDK derivations define their `pos` and these get inherited then.
