### ISSUE TITLE
get-version-suffix script returns bad version given current tag structure

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#27226]
It looks like the [get-version-suffix script](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/tools/get-version-suffix) uses `git describe` to figure out the version of a nixpkgs checkout. When I run that on my clone, it tells me that I'm on `16.09-beta-18942-gdd3f2e648a-dirty`.

I think that's because the 17.03 tag in nixpkgs is forked off from the rest of history and never made it back into master. The answer is probably just to `git merge` it back but there might be smarter logic that could fix this in a better way.

cc @globin

**Comment by 0xABAB** [comment]
@copumpkin I would love to see a PR with a specification for what this function is *supposed* to do. Once that has happened, I'd be happy to look at the implementation.

**Comment by fpletz** [comment]
We've just tested merging release-17.03 into master and get the correct description. We will update the documentation when we release 17.09.

**Comment by samueldr** [comment]
Wondering, is there something to do here? I'm not sure I follow what's to be done.

@fpletz did you update the documentation? (Assuming you didn't since there's no commit referencing)

What was it that needed to be added? (This will probably be relevant quite soon.)

**Comment by grahamc** [comment]
bump @fpletz / @globin on the docs on how-to do this properly :)

**Comment by copumpkin** [comment]
Sorry my thing was unclear, but I'm talking about the actual state of the repository. The script assumes a certain tag structure in the repo and unless we follow it, will not show the right thing. I think it's now in a reasonable state though, since `git describe` returns `18.03-beta-19861-gda11a260088`.

Not sure if it can be made more robust, but I'm not opposed to closing this now.

**Comment by grahamc** [comment]
Yeah, I think the docs update is for how to tag the beta properly so we
don't have to reopen this ticket.

**Comment by vcunat** [comment]
The beta tagging had been documented several releases ago and it's followed.  (I case we forget once, we can always add the tag later.)  https://nixos.org/nixos/manual/index.html#at-beta-release-time

**Comment by vcunat** [comment]
Oh, you mean the fact that you're on a version leading to 18.09 but it tells you "18.03-beta"?

**Comment by vcunat** [comment]
We might always add yet another tag just after the fork-off.  Call it "18.09-unstable" or something?

**Comment by lheckemann** [comment]
This is fixed as far as I understand it. Feel free to reopen or ask for a reopen if I'm wrong!
