### ISSUE TITLE
Firefox no WebGL and no audio (both firefox-esr and firefox)

### ISSUE THREAD

**Issue by johnworchester** [NixOS/nixpkgs#272269]
### Describe the bug
Firefox is neither able to play WebGL content nor play audio (nix installed on debian).

### Steps To Reproduce
1. Install nix on most recent debian (here WSL is used, both audio and WebGL work when installing firefox-esr via apt-get) via "sudo nix-shell -p firefox-esr"

### Expected behavior
WebGL and audio should play correctly. Also, there seems to be a font issue, since firefox only displays question marks.

### Notify maintainers
@mweinelt 
@lovesegfault 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.133.1-microsoft-standard-WSL2, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by mweinelt** [comment]
Can you test `firefox-bin` and check if that makes things work for you? 

I'm a bit worried about supporting WSL. It is not an environment I'm able to test.

**Comment by johnworchester** [comment]
Of course, but I do not think this is a WSL issue. Installing firefox-bin does not solve either issue. Running normally and it works like a charm.

**Comment by johnworchester** [comment]
Update: Installing nix not via apt-get (as done previously) but as single-user installation (as described on the homepage) resolves the audio problem. The lack of WebGL continues, though (both firefox and firefox-bin)

Is this log message relevant?
[GFX1-]: glxtest: libEGL no displayERROR

**Comment by mweinelt** [comment]
Yeah, it is likely unable to find the graphics drivers for OpenGL support.

**Comment by johnworchester** [comment]
Trying display: wayland
libva info: VA-API version 1.20.0
Segmentation fault

Do you think this is a WSL thing or a nix thing?

**Comment by K900** [comment]
Graphics acceleration for Nix built applications requires extra setup on both non-NixOS and WSL. You're using both, so you need twice as much extra setup, and I don't think this kind of thing is documented anywhere.

Source: am NixOS-WSL maintainer.

**Comment by johnworchester** [comment]
Ok.
I have now dropped WSL, now running nix under native Debian, audio works, but WebGL is broken still.

**Comment by K900** [comment]
There's basically no way to do this without issues. If we include our own graphics drivers, as nixGL currently does, it'll break on systems where the OS uses a different driver version (notably Nvidia). If we use the underlying OS' copy of the graphics drivers, that will cause weird linking errors and dependency mismatches. There's unfortunately no good solution here if you don't control the entire system.

**Comment by johnworchester** [comment]
Well the problem here is that I use nix for reproducible development environments and builds. Part of my build scenario consists in launching a firefox browser and testing some stuff via selenium. So far, this has worked like a charm, and I really like the reproducibility. Not supporting WebGL is however a big deal, because some of the test scenarios need a WebGL-enabled browser.

I try to circumvent the problem using nixGL, but fixing this issue would make things a lot easier.

**Comment by K900** [comment]
Well, if you have any specific ideas on how to fix it, please propose those.

**Comment by Aleksanaa** [comment]
So this issue is generally https://github.com/NixOS/nixpkgs/issues/9415 and may be considered as a duplicate. If you don't have further problems, you can close this issue.
