### ISSUE TITLE
bottom: command not found

### ISSUE THREAD

**Issue by fastfailure** [NixOS/nixpkgs#272234]
### Describe the bug

`bottom` can be installed but not executed, I get `command not found`

### Steps To Reproduce

1. `nix-shell -p bottom`
2. `bottom`

### Expected behavior

`bottom` is executed

### Screenshots

```console
# nix-channel --list
nixos https://nixos.org/channels/nixos-23.11

# nix-shell -p bottom
this path will be fetched (1.47 MiB download, 5.11 MiB unpacked):
  /nix/store/x42k7d0ybad25sxi69105z13yip7qb5r-bottom-0.9.6
copying path '/nix/store/x42k7d0ybad25sxi69105z13yip7qb5r-bottom-0.9.6' from 'https://cache.nixos.org'...

# bottom
bottom: command not found
```

### Additional context

I've found this behavior in NixOS 23.05 and 23.11, both with `nix-shell -p` and installing bottom with configurations.nix.

### Notify maintainers

@berbiche @figsoda

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.933d7dc15509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
the command name is btm
https://github.com/ClementTsang/bottom#usage
