### ISSUE TITLE
cuneiform (1.1.0) broken on 23.11 and unstable

### ISSUE THREAD

**Issue by jasom** [NixOS/nixpkgs#272319]
### Describe the bug
Running cuneiform results in a shared-library load error

### Steps To Reproduce
1. 23.11 *or* nixpkgs unstable
2. `nix-shell -p cuneiform`
3. run `cuneiform`

Will get error:
```console
cuneiform: error while loading shared libraries: libcuneiform.so.0: cannot open shared object file: No such file or directory`
```

### Expected behavior
The program will run

### Notify maintainers

@7c6f434c 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.20231201.5de0b32`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(aidenn): `""`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by a-n-n-a-l-e-e** [comment]
PR https://github.com/NixOS/nixpkgs/pull/272491 should fix this. can you verify that the change works for you?
```console
nix run github:NixOS/nixpkgs/3c3ba95ecd37524fc471d5599562ab53a5f61540#cuneiform
```
