### ISSUE TITLE
Update request: adguardhome 0.107.36 → 0.107.41

### ISSUE THREAD

**Issue by nadir-ishiguro** [NixOS/nixpkgs#272355]
- Package name: adguardhome
- Latest released version: 0.107.41

- Current version on the unstable channel: 0.107.36
- Current version on the stable/release channel: 0.107.36

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@numkem @iagoq @rhoriguchi

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/346196
