### ISSUE TITLE
Documentation: parse markdown files with multiple headings

### ISSUE THREAD

**Issue by ibizaman** [NixOS/nixpkgs#272329]
`nixos-render-docs` should allow a markdown file with sub-headings.

Currently, a markdown file with sub-headers is not accepted by `nixos-render-docs`. I'd love for the tool accept such a file though.

To be concrete, [here][1] is where I currently generate my documentation from in my project. `nixos-render-docs` produces a [beautiful looking][2] manual out of my poorly written markdown files. I would love to add [this markdown file][3] to the manual too but can't because I get this error:

```
self-host-blocks-manual> error:
self-host-blocks-manual>        failed to render manual manual.md
self-host-blocks-manual> caused by:
self-host-blocks-manual>        processing included file demo/homeassistant/README.md from line 15
self-host-blocks-manual> caused by:
self-host-blocks-manual>        unexpected heading in line 12
```

I tracked down the cause of the error and the exception in raised from [here][4]. I read the comment but still wanted to see it for myself so I commented out those lines and tried generating the manual again. It succeeded, but it put the TOC at the end of the generated file and it created a TOC for a sub-heading. I put the resulting HTML in a [gist][5] for reference. So now I understand why the comment is there :D

[1]: https://github.com/ibizaman/selfhostblocks/tree/13b756b09c82ba030d254f70354b188c9071e18d/docs
[2]: https://shb.skarabox.com/
[3]: https://github.com/ibizaman/selfhostblocks/blob/main/demo/homeassistant/README.md
[4]: https://github.com/NixOS/nixpkgs/blob/99faeebe0cf472606386f8c84d0806512c39d983/pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/manual_structure.py#L37-L40
[5]: https://gist.github.com/ibizaman/5a87a024a0810eabecfeffc52863bc87

I see multiple paths forward and was wondering which one is more worthwhile:
1. Update `nixos-render-docs` to accept such a file. But I can see a design issue popping up here: should the sub-headings appear in the same file or should they be in separate files with their own TOCs? I would vote for same file.
2. I use something like [`mdsplit`][10] as a pre-processing step to split the markdown file and generate files that `nixos-render-docs` understands.

[10]: https://github.com/markusstraub/mdsplit

**Comment by infinisil** [comment]
Ping @pennae @considerate

**Comment by ibizaman** [comment]
I think you’re right, I should understand how to write a document first. 😅 Is there a reference for what nixos-render-docs understands? I could find a few links for the v5 docbook I think we’re using but not sure if there’s a correct one.

**Comment by ibizaman** [comment]
Thanks for the hint. Indeed, what I needed was _chapters_ not parts.

I can now have [sub-headings](https://github.com/ibizaman/selfhostblocks/commit/5a3e072f3494a5e23b3e23cf706935d35928a3d5) and I could remove [a patch I added](https://github.com/ibizaman/selfhostblocks/commit/25462c657e473d5a9c22ec436aeaddb5be513aa5) because, essentially, I was wrong to use parts instead of chapters. I know understand that parts is really a way to just split a long file into multiple ones and not how to break a book into chapters.

Now, documentation for my project looks beautiful! https://shb.skarabox.com/

Thank you @pennae
