### ISSUE TITLE
Update list of available packages

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27237]
## Issue description

In #27220 the tool https://repology.org/ was mentioned which scans repositories, records what versions of packages we have, and checks certain meta data. The tool works by using the files

- https://nixos.org/nixpkgs/packages-unstable.json.gz
- https://nixos.org/nixpkgs/packages.json.gz

which are generated by this [script](https://github.com/NixOS/nixos-homepage/blob/master/Makefile#L211) as [part of the NixOS website](https://github.com/NixOS/nixos-org-configurations/blob/b48e1e1438df7d1bd24f31aefdb991ad51769368/nixos-org/webserver.nix#L203).

Maybe the files could be generated as part of the channel update mechanism?
- http://nixos.org/channels/nixos-unstable
- https://github.com/NixOS/nixos-channel-scripts

---

Note that I posted this here because the issue spans over multiple repositories.

**Comment by vcunat** [comment]
`packages-unstable.json` was on a two months old commit yesterday (c5badb123a2).

**Comment by 0xABAB** [comment]
https://repology.org/statistics kind of shows how bad *all* distributions do their work, assuming the tool works at all.

**Comment by vcunat** [comment]
Repology picked up the changes already :tada:

**Comment by AMDmi3** [comment]
It seems that the update is broken again. https://nixos.org/nixpkgs/packages-unstable.json.gz is at https://github.com/NixOS/nixpkgs/commit/96457d26dded05bcba8e9fbb9bf0255596654aab dated 11 days ago.

**Comment by vcunat** [comment]
Well, that's "just" because (some of) our packages have been broken the whole 11 days.
