### ISSUE TITLE
Can't install intellij even though it's present in nixpkgs

### ISSUE THREAD

**Issue by SaffronSnail** [NixOS/nixpkgs#27234]
## Issue description

intellij is in nixpkgs (see [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L14360) and [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/jetbrains/default.nix)). However, I cannot find any package name to install it, nor does any query return any results.

### Steps to reproduce

Run any of these commands:
`nix-env -{qa,i} {intellij,jetbrains,jetbrains.intellij,idea,jetbrains.idea}`

None of them find anything useful for me. All of them seem like reasonable things to search for/try to install, especially from what I'm reading in the scripts linked to in the first section.

## Technical details

* System: NixOS: `nixos-version`, 17.03.1463.81fceb2554 (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: 17.03.1463.81fceb2554
* Sandboxing enabled: false

**Comment by pbogdan** [comment]
Seems strange, I'm on a slightly newer version but only by few commits so that shouldn't make a difference and the packages are available, would you mind supplying output of:

```
$ nix-env -qaP --arg config {} | grep jetbrains
$ nix-env -qaP --arg config '{ allowUnfree = true; }' | grep jetbrains
```

**Comment by SaffronSnail** [comment]
Output of `nix-env -qaP --arg config {} | grep jetbrains`:
```
nixos.jetbrains.idea14-community                                idea-community-14.1.7
nixos.jetbrains.idea-community                                  idea-community-2017.1.3
nixos.jetbrains.pycharm-community                               pycharm-community-2017.1.3
```

Output of `nix-env -qaP --arg config '{ allowUnfree = true; }' | grep jetbrains`:
```
nixos.jetbrains.clion                                           clion-2016.3.3
nixos.jetbrains.datagrip                                        datagrip-2016.3.2
nixos.jetbrains.idea14-community                                idea-community-14.1.7
nixos.jetbrains.idea-community                                  idea-community-2017.1.3
nixos.jetbrains.idea14-ultimate                                 idea-ultimate-14.1.7
nixos.jetbrains.idea15-ultimate                                 idea-ultimate-15.0.6
nixos.jetbrains.idea-ultimate                                   idea-ultimate-2017.1.4
nixos.jetbrains.phpstorm10                                      phpstorm-10.0.4
nixos.jetbrains.phpstorm                                        phpstorm-2017.1.4
nixos.jetbrains.pycharm-community                               pycharm-community-2017.1.3
nixos.jetbrains.pycharm-professional                            pycharm-professional-2017.1.3
nixos.jetbrains.ruby-mine                                       ruby-mine-2016.3.1
nixos.jetbrains.ruby-mine7                                      ruby-mine-7.1.5
nixos.jetbrains.ruby-mine8                                      ruby-mine-8.0.4
nixos.jetbrains.webstorm10                                      webstorm-10.0.5
nixos.jetbrains.webstorm11                                      webstorm-11.0.4
nixos.jetbrains.webstorm                                        webstorm-2017.1.4
```

So, it definitely seems like something is wrong with my config; I tried `nix-env -i  nixos.jetbrains.idea-community`, but it told my that it matched no derivations again. I searched through my nix config directory (I have a number of modules) for instances of 'pkgs' to see if anything looked suspicious, but the only thing other than accepting pkgs as an argument or referencing items in the pkgs set (ie `pkgs.something` or `with pkgs`) is allowing unfree packages.

I've modified NIX_PATH so that some packages I can reference packages I'm working on as 'saffpkgs'. I don't think this should be causing the bug, but here's the current value just in case:
`saffpkgs=/usr/pkgs:saffpkgs=/usr/pkgs:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels`

**Comment by pbogdan** [comment]
Does it make a difference if you try `nix-env -iA nixos.jetbrains.idea-community` or `nix-env -i idea-community`.
For the unfree packages like `clion` you would need to set `allowUnfree = true;` in your `~/.config/nixpkgs/config.nix`., or if you try installing them `nix-env` should throw an error message containing instructions.
If neither of those work then it would seem it could be something in your configuration. `NIX_PATH` seems OK on a first glance so I'm unsure at this point what could be causing that :-(.

**Comment by SaffronSnail** [comment]
Well, `nix-env -i idea-community` worked. I'm glad that I have it installed, but I don't feel like the underlying issue was solved; why does `nix-env -qa idea` not find this package? It's part of the package name, so I would expect it to; based on this experience, `nix-env -qa` provides little to no assistance in identifying package names.

**Comment by pbogdan** [comment]
FWIW it seems to work if I feed it a regex:

```
$  nix-env -qa  .\*idea.\*
idea-community-14.1.7
idea-community-2017.1.3
idea-ultimate-14.1.7
idea-ultimate-15.0.6
idea-ultimate-2017.1.4
```

**Comment by SaffronSnail** [comment]
Ooh... my mistake. I had tried `nix-env -qa '*idea*'` instead of `nix-env -qa .*idea.*` I guess I'm just too used to bash.

Thanks for your assistance! =)
