### ISSUE TITLE
Disabling UEFI booting

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#27233]
I need to make a custom iso for nixos that does not have UEFI enabled at all.  Old mother board that doesnt understand it can't boot with UEFI enabled ISO.  I can build the custom ISO, but who knows what setting I need in my configuration.nix that will build the nixos installert without UEFI support?

**Comment by 0xABAB** [comment]
I recently installed with legacy BIOS support by following the manual. There is documentation on how to build ISOs. Together they form a solution to your problem. I have never heard of UEFI support being present have any impact. In the remote case this is the case, you could find all the kernel options related to UEFI and compile yourself a custom kernel (this too, is documented). See https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#Linux_Kernel_Config_options_for_UEFI.

Please close this issue with a comment of how it all went.

**Comment by ob7** [comment]
I turns out the issue was actually my cd burner.  I thought maybe it was a driver problem but even booted into windows the drive produced bad disks.  So I plugged in an external CD drive to burn the ISO and the stock ISO booted on the old system just fine.
