### ISSUE TITLE
NixOS 23.11: RAID devices don't appear in stage 1, boot failure

### ISSUE THREAD

**Issue by pjones** [NixOS/nixpkgs#272393]
### Describe the bug

I have internal disks that are part of a RAID1.  On NixOS 23.05 they would show up during stage 1, including their mdadm device, and the RAID would get mounted to `/var/lib`.

On NixOS 23.11 stage 1 hangs waiting for the disks to appear, then times out and tries to mount them and fails.  If I set the disks to "nofail" I can get to a working system (without the RAID), but mdadm refuses to create a `md` device for the RAID.  Rebooting to NixOS 23.05 fixes the issue.

Also, mdadm devices in `/dev/disk/by-id/md-*` have colons in their names which causes the stage 1 script to split the device name into multiple erroneous devices and attempts to wait on those instead of
the actual device.

### Steps To Reproduce

My config looks something like:

```nix
{
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/nvme0n1";

  boot.swraid = {
    enable = true;
    mdadmConf = ''
      DEVICE /dev/disk/by-id/wwn-0x5000cca250e3b921
      DEVICE /dev/disk/by-id/wwn-0x5000cca250e3b980
      ARRAY /dev/md/var-lib metadata=1.2 name=kilgrave:var-lib UUID=39ae50b0:547ca41b:d3e74e55:96dfd3b4
    '';
  };
  
  fileSystems = {
    # Root disk: /dev/nvme0n1p2
    "/" = {
      device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };

    # /var/lib RAID:
    "/var/lib" = {
      # It doesn't matter which device style I use,
      # /dev/mdXXX, /dev/md/xxx, nothing works:
      device = "/dev/disk/by-id/md-name-kilgrave:var-lib";
      fsType = "ext4";
    };

  # ...
  };
}
```

### Expected behavior

mdadm in stage 1 should see the disks, assemble them into a RAID, and
then stage 1 should mount the RAID.

### Additional Information

This server has 3 RAIDS, two of them are RAID1, built from internal disks and should mount in stage 1, and the remaining is a RAID6 whose disks are in an external enclosure and should mount in/after stage 2.

Neither of the RAID1s are recognized or mounted in stage 1.  If I allow the boot process to continue then the system eventually mounts the RAID6 just fine.

After boot `/proc/mdstat` **does not** show either of the RAID1s.  There are also no `/dev/md*`, `/dev/disk/by-id/md-*`, or other MD related device entries for the RAID1s.  However, the component disks have proper device files and `mdadm --examine` on those device files shows them as being members of the missing RAID1s.

Note that I'm using the whole disk as a RAID member, and not using LVM.

### Notify maintainers

@lheckemann @ctheune

May be related to #196800

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/store/3nswpmdma210h4ihmg7xx95v3sw43r2z-hwqz0b3d0wcyjvb4fda1wf8lhj4vaa4m-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ctheune** [comment]
mdadm shouldn't be necessary to assemble the RAID devices.

Can you post the output of `cat /proc/mdstat` and `find /dev/disk`?

**Comment by pjones** [comment]
> mdadm shouldn't be necessary to assemble the RAID devices.
> 
> Can you post the output of `cat /proc/mdstat` and `find /dev/disk`?

@ctheune Thank you for taking a look at my issue.  I updated the issue description with more details.

I'm not able to bring the server offline and boot back into NixOS 23.11 right now.  However, the first thing I checked when I was booted into 23.11 was `/proc/mdstat`.  It did not list the missing RAID.  There were also no MD related entries in `/dev/disk`.  The device files for the disk themselves were present and `mdadm --examine` correctly reports they are members of a RAID and correctly shows the UUID of the RAID.

**Comment by pjones** [comment]
> Did you update your state version? Can you check whether `boot.swraid.enable` is set?

Yes, I did both.  `boot.swraid.enable = true` and `system.stateVersion = "23.11"`.

**Comment by pjones** [comment]
@lheckemann I booted back into 23.11 with `boot.shell_on_fail`.  I was able to get a shell in stage 1 and poke around.

All of the internal disks have appropriate device entries in `/dev/disk`, but there are no `md` entries.  Also, `mdadm --assemble --scan --verbose` shows no arrays found.  If I use `mdadm --examine` on the devices I know are array members mdadm recognizes them correctly.  But mdadm refuses to detect the members on its own.

Interestingly enough I was able to manually assemble the arrays and mount them under `/mnt-root`.

At this point I don't know how to proceed.  I'm not familiar with how stage 1 detects and mounts RAIDs so I don't know how to debug this.  Any pointers?

**Comment by pjones** [comment]
Well, I made some changes to the `mdadm.conf` file and updated to the latest commit on `nixos-23.11` and the machine in question booted without any problems, mounting the arrays correctly.  It's not clear to me why it's working now, but it is.

Thanks everyone.

**Comment by lheckemann** [comment]
Weird! An unsatisfying resolution, but I guess it's good that it works. Thanks for fiddling with it!

(and I hope it's not a race condition that will pop up again sometime in the undetermined future...)
