### ISSUE TITLE
[NixOS 23.11] Podman DNS resolution failure

### ISSUE THREAD

**Issue by foreu1** [NixOS/nixpkgs#272480]
### Describe the bug
Upgrading from NixOS 23.05 to 23.11 makes podman not be able to install a project inside a container.

### Steps To Reproduce
1. Setup podman in configuration.nix:
```{
  virtualisation = {
    podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };
  };

environment.systemPackages = with pkgs; [
    podman-compose
  ];
```
2. In a folder, create the following two files:

**Dockerfile** with the following contents:
```
FROM alpine:3.18.4
RUN apk add --no-cache git yarn
RUN git clone https://github.com/seanpmaxwell/express-generator-typescript.git
ENTRYPOINT [ "/bin/sh" ]
```
**docker.compose.yml** with the following contents:
```
services:

  test:
    build:
      context: .
    container_name: test
    tty: true
    stdin_open: true
```
3. In the folder with the two docker files, open a terminal and run `podman-compose up -d`
4. Enter the container with `podman exec -it test sh`
5. In the container `cd` into express-generator-typescript folder and run `yarn install`

After exiting the container, stop it with `podman-compose down` and remove all containers and images from system with `podman system prune --all --force`

### Expected behavior
When running yarn install, the process should finish with success as in NixOS 23.05

### Screenshots
![23 05](https://github.com/NixOS/nixpkgs/assets/152907526/68bba824-97e7-4a1c-a9a8-05c69a5b13e4)
![23 11](https://github.com/NixOS/nixpkgs/assets/152907526/37ad8fef-8e1f-461e-b6f6-4580d282ad46)

### Notify maintainers
@marsam 
@adisbladis 
@saschagrunert 
@vdemeester 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"×86 64-linux"`
- host os: `'Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.93347dc15509`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"nixos-23.11"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tcurdt** [comment]
I think this should be re-opened. Now that it is now available in release and unstable I tested and it is still not working for me.

Here from the container:
```
podman exec -it live-shell1 sh
/ # nslookup google.de
;; connection timed out; no servers could be reached

/ # cat /etc/resolv.conf 
search dns.podman
nameserver 10.89.0.1
options edns0
/ # exit
```

Here on the host:
```
[root@nixos:~]# ss -ntulp
Netid             State               Recv-Q              Send-Q                           Local Address:Port                           Peer Address:Port             Process                                             
udp               UNCONN              0                   0                                    10.89.0.1:53                                  0.0.0.0:*                 users:(("aardvark-dns",pid=1446,fd=9))             

[root@nixos:~]# nslookup google.de 10.89.0.1
Server:		10.89.0.1
Address:	10.89.0.1#53

Non-authoritative answer:
Name:	google.de
Address: 209.85.202.94
Name:	google.de
Address: 2a00:1450:400b:c00::5e
```

**Comment by tcurdt** [comment]
Anything I can do or help?

@marsam
@adisbladis
@saschagrunert
@vdemeester
@fpletz 

Open a new issue? Re-open this one? Provide more details?

**Comment by fpletz** [comment]
We need more informtion. What nixpkgs revision are you running? Are you using the default network or a new one?

**Comment by mlyxshi** [comment]
Some people use experimental nftables as firewall. 
``` 
networking.firewall.enable = false; # Disable nixpkgs defined firewall
networking.nftables.enable = true;
```
They should add `iifname podman0 udp dport 53 accept` to nftable ruleset
```
 networking.nftables.ruleset = ''
    table inet FIREWALL {
      chain INPUT {
        # Drop all incoming traffic by default
        type filter hook input priority 0; policy drop;

        # Allow loopback traffic
        iifname lo accept

        # Allow ICMP
        ip protocol icmp accept

        # Accept traffic originated from us
        ct state {established, related} accept

        # Only Allow SSH and Traefik
        tcp dport { 22, 80, 443 } accept

        # Podman DNS
        ${lib.optionalString config.virtualisation.podman.enable "iifname podman0 udp dport 53 accept"}
      }
    }
  '';
```

**Comment by tcurdt** [comment]
@fpletz 

```
$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.73-hardened1, NixOS, 24.05 (Uakari), 24.05.20240121.612f972`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `""`
 - nixpkgs: `not found`
 ```

Here is my podman config:
https://github.com/tcurdt/nixcfg/blob/main/modules/podman.nix#L9

Which is pretty barebones:

```
  virtualisation = {
    containers.enable = true;
    oci-containers.backend = "podman";

    podman = {
      enable = true;
      defaultNetwork.settings.dns_enabled = true;
    };

  };
```

I am running the following test pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: live
spec:
  containers:

  - name: shell1
    image: alpine
    args: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
    ports:
      - containerPort: 80
        hostPort: 8080
        hostIP: 127.0.0.1

  - name: shell2
    image: alpine
    args: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
    ports:
      - containerPort: 80
        hostPort: 8081
        hostIP: 127.0.0.1

# podman play kube ./one.yaml
```
Which starts the dns resolver
```
ss -ntulp | grep aard
udp   UNCONN 0      0          10.89.0.1:53        0.0.0.0:*    users:(("aardvark-dns",pid=8996,fd=9))
```
But the it's still not usable from within the pod
```
podman exec -it live-shell1 sh
/ # nslookup google.de
;; connection timed out; no servers could be reached

/ # cat /etc/resolv.conf 
search dns.podman
nameserver 10.89.0.1
options edns0
/ # exit
```
Maybe the "kube" uses another network?

I also tried
```
  networking.firewall.trustedInterfaces = [ "podman0" ];
  networking.firewall.interfaces.podman0.allowedUDPPorts = [ 53 ];
```
but that didn't make a difference.

This is what the firewall looks like:
```
$ iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N NETAVARK_FORWARD
-N NETAVARK_ISOLATION_2
-N NETAVARK_ISOLATION_3
-N nixos-drop
-N nixos-fw
-N nixos-fw-accept
-N nixos-fw-log-refuse
-N nixos-fw-refuse
-A INPUT -j nixos-fw
-A FORWARD -m comment --comment "netavark firewall plugin rules" -j NETAVARK_FORWARD
-A NETAVARK_FORWARD -d 10.89.0.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A NETAVARK_FORWARD -s 10.89.0.0/24 -j ACCEPT
-A NETAVARK_ISOLATION_3 -o podman1 -j DROP
-A NETAVARK_ISOLATION_3 -j NETAVARK_ISOLATION_2
-A nixos-drop -j DROP
-A nixos-fw -i lo -j nixos-fw-accept
-A nixos-fw -m conntrack --ctstate RELATED,ESTABLISHED -j nixos-fw-accept
-A nixos-fw -p tcp -m tcp --dport 22 -j nixos-fw-accept
-A nixos-fw -p icmp -m icmp --icmp-type 8 -j nixos-fw-accept
-A nixos-fw -j nixos-fw-log-refuse
-A nixos-fw-accept -j ACCEPT
-A nixos-fw-log-refuse -m pkttype ! --pkt-type unicast -j nixos-fw-refuse
-A nixos-fw-log-refuse -j nixos-fw-refuse
-A nixos-fw-refuse -j DROP

$ iptables -L INPUT -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   44  3144 nixos-fw   0    --  *      *       0.0.0.0/0            0.0.0.0/0    
 ```
 
Cross Checking the interfaces I found that there is no `podman0`

```
ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp0s1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc cake state UP group default qlen 1000
    link/ether 72:1d:a8:6d:41:f4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.70.3/24 brd 192.168.70.255 scope global dynamic noprefixroute enp0s1
       valid_lft 67558sec preferred_lft 56758sec
    inet6 fdf7:625:925f:6294:1cb4:25e4:25cc:950/64 scope global temporary dynamic 
       valid_lft 542754sec preferred_lft 23806sec
    inet6 fdf7:625:925f:6294:701d:a8ff:fe6d:41f4/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591892sec preferred_lft 604692sec
    inet6 fe80::701d:a8ff:fe6d:41f4/64 scope link 
       valid_lft forever preferred_lft forever
5: podman1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ca:5a:6f:22:3b:f7 brd ff:ff:ff:ff:ff:ff
    inet 10.89.0.1/24 brd 10.89.0.255 scope global podman1
       valid_lft forever preferred_lft forever
    inet6 fe80::e82e:81ff:fe6f:d149/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
6: veth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master podman1 state UP group default qlen 1000
    link/ether 32:1b:fd:f3:ec:78 brd ff:ff:ff:ff:ff:ff link-netns netns-faff1609-b85c-fa14-960f-84b2dd377649
    inet 169.254.181.27/16 brd 169.254.255.255 scope global noprefixroute veth0
       valid_lft forever preferred_lft forever
    inet6 fe80::301b:fdff:fef3:ec78/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::54e2:ecff:fe9a:c031/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

So I tried with

```
  networking.firewall.trustedInterfaces = [ "podman1" ];
  networking.firewall.interfaces.podman1.allowedUDPPorts = [ 53 ];
```

which made it work.

But IMO that's something the podman package should do automatically.

**Comment by fpletz** [comment]
Okay, we can modify the firewall rule to use a wildcard like `podman+` to cover all interfaces starting with the prefix podman. However, the user can set arbitrary interface names for interfaces created at runtime. So I don't think we can fix every case here.

That's also why I thought the default interface case is enough for a convenient automatic firewall opening. If the user has more interfaces, the firewall configuration needs to be set accordingly.

Any thoughts on how to proceed? Maybe add some documentation?

Regarding nftables, since AFAIK there isn't yet a composable way to add new firewall rules I don't think we can solve that in the podman module itself.

**Comment by tcurdt** [comment]
I guess the question for me is:
Why has my install `podman1` instead of `podman0`.
I didn't configure it that way. The problem should go away (for me) if it was `podman0`.
Can I change that? How?

I guess opening the fw could be done dynamically (via systemd? during startup?).
Really not a fan of that idea though.

If this needs to be configured it needs to be very prominent in the documentation.

**Comment by tcurdt** [comment]
> You probably hat two networks configured in podman at some point and removed the first one. This is runtime config and thus state in podman which we do not control in the NixOS module. You can create a new podman network like `podman network create podman0` and remove the other one with `podman network rm podman1`.

```
$ podman network ls
NETWORK ID    NAME                         DRIVER
000000000000  podman                       bridge
fe01d110e98f  podman-default-kube-network  bridge
```

There is neither a `podman0` nor a `podman1` network.
I am wondering if this is rather due to the fact this is using `kube play`.

> > I guess opening the fw could be done dynamically (via systemd? during startup?). Really not a fan of that idea though.
> 
> This would also need to be done at runtime not only at service start since at any point new interfaces can be created by the user via the CLI/API. There would need to be a service that monitors the networks managed by the podman service.

True.

Unless the firewall rules can allow for a wildcard match that feels the cleanest (and only?) option.

Or how about just creating static rules for `podman0`, `podman1` and so on? And have the number be part of the podman config?

**Comment by tcurdt** [comment]
My guess is that `000000000000` is `podman0` and `fe01d110e98f` is `podman1`.
Maybe we just need to expand the fix to also include `podman1` for now?

What's the further process, @fpletz? Anything else I can help with?

**Comment by tcurdt** [comment]
So no further suggestions? Should this be at least documented somewhere?
