### ISSUE TITLE
Spurious warnings about unbound STARSHIP_PREEXEC_READY variable at terminal startup

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#272444]
### Describe the bug

Any time I start a terminal (checked on both GNOME Console and XTerm) the first five lines of the terminal, before the first prompt, are populated with the following:

```
bash: STARSHIP_PREEXEC_READY: unbound variable
bash: STARSHIP_PREEXEC_READY: unbound variable
bash: STARSHIP_PREEXEC_READY: unbound variable
bash: STARSHIP_PREEXEC_READY: unbound variable
bash: STARSHIP_PREEXEC_READY: unbound variable
```

This has been happening since I started using Starship on 23.05, and is still present on 23.11.

### Steps To Reproduce
1. Set `programs.starship.enable = true;`
2. Run `sudo nixos-rebuild switch`
3. Start a terminal (or run `bash`)

### Expected behavior

No warnings should print on screen.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/168301/13c82f66-27c3-4f33-b990-d95ec6f57dfb)

### Additional context

What I've tried to fix this:

- Remove `nounset` from [my Bash RC file](https://gitlab.com/engmark/root/-/blob/ee96e4966f2a9a6f89f4e3f31b208782f8c650a0/includes/bashrc.bash#L10-10).
- Remove all Starship settings [other than `enable = true;`](https://gitlab.com/engmark/root/-/blob/ee96e4966f2a9a6f89f4e3f31b208782f8c650a0/configuration.nix#L499-506).

### Notify maintainers

@danth @davidtwco @Br1ght0ne @Frostman @marsam

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.933d7dc15509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Maybe I am missing something, but you are the one who approved upstream PR to fix it back in September:
https://github.com/starship/starship/pull/5438
So waiting for `1.17.0` starship version with that fix seems like the best solution.
Or set `STARSHIP_PREEXEC_READY` yourself to avoid it in the meantime.

**Comment by l0b0** [comment]
@ghpzin Thanks for the reminder! :grin: I've pinged them about the [release](https://github.com/starship/starship/pull/5348).
