### ISSUE TITLE
systemctl privilages lost on update to 17.03.1437.a2c7482319

### ISSUE THREAD

**Issue by AveryGlitch** [NixOS/nixpkgs#27254]
## Issue description

Before I updated to 17.03.1437.a2c7482319, I could run systemctl commands (such as `systemctl poweroff`) without any authentication required. Now, after the update, I must authenticate. No other configuration changes were made.

## Technical details

* System: (NixOS: 17.03.1437.a3c7482319)
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1437.a3c7482319
* Sandboxing enabled: yes

**Comment by emmanuelrosa** [comment]
Which version were you running before?

**Comment by AveryGlitch** [comment]
I believe I was running 17.03.1180.27b488f28e, is there anyway I can check?

**Comment by emmanuelrosa** [comment]
Yes. If you still have that generation installed, you can boot it and run `nixos-version`.

**Comment by AveryGlitch** [comment]
Yep, it was an upgrade from `17.03.1180.27b488f28e -> 17.03.1437.a3c7482319`, and when I revert to that generation I can use systemctl commands just fine.

**Comment by Mic92** [comment]
mhm I cannot find a3c7482319 in nixpkgs

**Comment by Mic92** [comment]
Usually this privilege is granted for local users:

```
$ loginctl                                                                                                                                                                                                                             
   SESSION        UID USER             SEAT             TTY                                                                                                                                                                                   
         1       1000 joerg            seat0 
$ loginctl show-seat seat0                                                                                                                                                                                                             
Id=seat0                                                                                                                                                                                                                                      
ActiveSession=1                                                                                                                                                                                                                               
CanMultiSession=yes                                                                                                                                                                                                                           
CanTTY=yes                                                                                                                                                                                                                                    
CanGraphical=yes                                                                                                                                                                                                                              
Sessions=1                                                                                                                                                                                                                                    
IdleHint=no                                                                                                                                                                                                                                   
IdleSinceHint=0                                                                                                                                                                                                                               
IdleSinceHintMonotonic=0
```

**Comment by AveryGlitch** [comment]
Sorry, the version number is actually `17.03.1437.a2c7482319` (a2 instead of a3).

`loginctl` and `loginctl show-seat seat0` are identical to those above, aside from username

**Comment by emmanuelrosa** [comment]
The release you updated to is a2c7482319cb5384f518f318c2ecd5d64adba7d0 which was created on June 28th. The latest NixOS 17.03 release is 849b5a5193be4c3e61af53e8db5bdb9d95b2074f from July 13th. Have you tried this release?

The Git commit range you specified does contain changes to systemd, but from looking at it I could not tell which one is the culprit. Fingers crossed that it has already been fixed :)

**Comment by AveryGlitch** [comment]
sorry for leaving this issue open for so long - I discovered the actual culprit *was* a change I had made in my configuration file (but the effects of the change were different depending on whether you had rebooted, which was why I was confused).

I'll open a seperate issue describing that, and close this one
