### ISSUE TITLE
nixos/xserver.xkb: deprecation warnings missing

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#272510]
### Describe the bug

In https://github.com/NixOS/nixpkgs/pull/259891 and https://github.com/NixOS/nixpkgs/pull/264787, xkb options were moved, and the old options were deprecated. However, when using the deprecated options on recent unstable (https://github.com/NixOS/nixpkgs/commit/e92039b55bcd58469325ded85d4f58dd5a4eaf58), I'm not seeing any warning that the old options are deprecated.

### Steps To Reproduce

Build a nixos configuration with

```
services.xserver.xkbOptions = "caps:escape";
```

### Expected behavior

Seeing warnings.

### Additional context

I've tried to build from the commit where the PR was merged into master, but I didn't get any warning either.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 24.05 (Uakari), 24.05.20231129.e92039b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/cjvwy2rr87ir1nb6wvs9n6lvbnzlqrdg-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by philiptaron** [comment]
I do see this warning as of this morning:

```
trace: warning: The option `services.xserver.xkbVariant' defined in `/nix/store/phf2gvlnv7sgi0g580zylrss8jqmjlya-source/gui.nix' has been renamed to `services.xserver.xkb.variant'.
trace: warning: The option `services.xserver.layout' defined in `/nix/store/phf2gvlnv7sgi0g580zylrss8jqmjlya-source/gui.nix' has been renamed to `services.xserver.xkb.layout'.
```

**Comment by katexochen** [comment]
Thanks for the notice, I see the warnings now, too. Wondering what changed...

**Comment by katexochen** [comment]
Okay, after some bisecting it seems like the warning was activated after bumping the latest supported release to 23.11 in e08ce8d1d12a30de76768e8b03c2faf74351ad7f
