### ISSUE TITLE
Build failure: recoll

### ISSUE THREAD

**Issue by aidan-gibson** [NixOS/nixpkgs#272594]
### Steps To Reproduce

Note: `catdvi` is a recoll dependency that previously didn't build (#272384); @a-n-n-a-l-e-e graciously fixed it but it currently isn't merged. This reflects their fix:
1. `nix profile install github:NixOS/nixpkgs/9559cea14a91ffa63f5f90d7719b2c56233517f2#recoll`

(doesn't build on macOS; builds fine elsewhere)

### Build log

`nix log /nix/store/kn6a1vj3374s3vq56srkskdclwjzaci5-recoll-1.36.2.drv`
```
https://gist.github.com/aidan-gibson/c4f3f580186fe515d0dfd2f75d8a818b
```
tl;dr is 
```
> Project ERROR: Unknown module(s) in QT: webenginewidgets
> make[2]: *** [Makefile:3014: recollqt] Error 3
```

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
these 3 paths will be fetched (1.02 MiB download, 8.17 MiB unpacked):
  /nix/store/ww2aj2qyn7mpd6pizy8ik22bdpzivf03-DarwinTools-1
  /nix/store/xhvxpfkb3xmicav5wdx9xfyiaw452mbl-bash-interactive-5.2-p15
  /nix/store/ngbvqkdnz9yaxmf9qc1lpyr05ya9g1k4-nix-info
copying path '/nix/store/ww2aj2qyn7mpd6pizy8ik22bdpzivf03-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/xhvxpfkb3xmicav5wdx9xfyiaw452mbl-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/ngbvqkdnz9yaxmf9qc1lpyr05ya9g1k4-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.1.0, macOS 14.1.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/wk5dq7iwpd8yb4mnhb98k687kgdqachh-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
I have something that builds and will show a gui but not sure how much else works. still waiting for https://github.com/NixOS/nixpkgs/issues/272384 to get merged...

https://github.com/NixOS/nixpkgs/compare/master...a-n-n-a-l-e-e:nixpkgs:recoll-darwin

can try with:
```
nix run github:NixOS/nixpkgs/eb6242fe818393c16ca6ad06c66750218e2b974b#recoll
```
