### ISSUE TITLE
`aws-azure-login` can't find browser

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#272544]
### Describe the bug

`aws-azure-login` consistently fails on 23.11.

### Steps To Reproduce
1. Upgrade to NixOS 23.11
1. Run `nix-shell -p aws-azure-login --run 'aws-azure-login --profile=some-profile'`

### Expected behavior

This should work like [`nodePackages.aws-azure-login` on 23.05](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=aws-azure-login).

### Additional context

Debug output:

```
❯ DEBUG=aws-azure-login aws-azure-login --profile=my-profile
  aws-azure-login Getting config for profile 'my-profile' in section 'profile my-profile' +0ms
  aws-azure-login Loading 'config' file at '/home/username/.aws/config' +1ms
  aws-azure-login Parsing data +1ms
  aws-azure-login Environment +0ms
  aws-azure-login { azure_default_password: 'xxxxxxxxxx' } +0ms
Logging in with profile 'my-profile'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
  aws-azure-login Generating UUID for SAML request +2ms
  aws-azure-login Generated SAML request
        <samlp:AuthnRequest xmlns="urn:oasis:names:tc:SAML:2.0:metadata" ID="id2893d26d-0ab2-4a89-bd0a-4754e40fc327" Version="2.0" IssueInstant="2023-12-06T21:37:03.101Z" IsPassive="false" AssertionConsumerServiceURL="https://signin.aws.amazon.com/saml" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
            <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">1050e591-a33e-4602-9294-0cf5350f8c4d</Issuer>
            <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>
        </samlp:AuthnRequest>
         +0ms
  aws-azure-login Deflating SAML +0ms
  aws-azure-login Encoding SAML in base64 +3ms
  aws-azure-login Created login URL https://login.microsoftonline.com/2134e961-7e38-4c34-a22b-10da5466b725/saml2?SAMLRequest=… +0ms
  aws-azure-login Loading login page in Chrome +0ms
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
    at ChromeLauncher.launch (/nix/store/mxglfzfd0y7wkl2scx3q2slf0ngdlqk2-aws-azure-login-3.6.1/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:23)
    at PuppeteerNode.launch (/nix/store/mxglfzfd0y7wkl2scx3q2slf0ngdlqk2-aws-azure-login-3.6.1/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:125:31)
    at Object._performLoginAsync (/nix/store/mxglfzfd0y7wkl2scx3q2slf0ngdlqk2-aws-azure-login-3.6.1/lib/node_modules/aws-azure-login/lib/login.js:518:49)
    at async Object.loginAsync (/nix/store/mxglfzfd0y7wkl2scx3q2slf0ngdlqk2-aws-azure-login-3.6.1/lib/node_modules/aws-azure-login/lib/login.js:377:30)
```

Installing `pkgs.chromium` via `users.users.<name>.packages` or via `programs.chromium.enable` does *not* fix this.

[`nodePackages.aws-azure-login` had a lot more dependencies on 23.05](https://raw.githubusercontent.com/NixOS/nixpkgs/nixos-23.05/pkgs/development/node-packages/node-packages.nix), but no mention of Chromium itself.

It looks like the error message is from _[puppeteer](https://stackoverflow.com/q/68051648/96588)._ [Troubleshooting reference](https://github.com/puppeteer/puppeteer/blob/06cacfa9c1d5b185ce41a337abf94cfa8726b4f2/docs/troubleshooting.md#could-not-find-expected-browser-locally).

### Notify maintainers

@yurrriq

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.933d7dc15509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### Failed workaround

(I'll be tweaking this in case I come up with a working solution.)

1. Go to a new directory, for example `aws-azure-login`
1. Create a `package.json` containing the following:

   ```
   {
     "name": "aws-azure-login",
     "dependencies": {
       "aws-azure-login": "*"
     }
   }
   ```
1. Run `node2nix --nodejs-18`
1. Get the built package like this:

   ```
   awsAzureLoginNodePackages = import ./aws-azure-login/default.nix {
     inherit pkgs;
   };
   awsAzureLogin =
     (awsAzureLoginNodePackages
       // {
         puppeteer = awsAzureLoginNodePackages.puppeteer.override {
           env.PUPPETEER_SKIP_DOWNLOAD = true;
         };
       })
     .aws-azure-login;
   ```

Unfortunately, the `PUPPETEER_SKIP_DOWNLOAD` override doesn't work as expected:

```
ERROR: Failed to set up Chromium r982053! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

I'm not sure how to proceed.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yurrriq** [comment]
Unfortunately I'm not using this anymore and should remove myself as maintainer. Any volunteers? Looks like we have a fix now too. Can anyone verify?

**Comment by l0b0** [comment]
@yurrriq I'm still using it for the foreseeable, so I've [asked for ownership](https://github.com/NixOS/nixpkgs/pull/272592/commits/a756bf8457871aa6f2abe65f6d0336c9d0383ebe).
