### ISSUE TITLE
`fcitx5` unable to work in `tor-browser` in `xfce`

### ISSUE THREAD

**Issue by amalgame21** [NixOS/nixpkgs#272670]
### Describe the bug
`fcitx5` unable to work in `tor-browser` in `xfce`

Fcitx5 is an [nput method framework with a lightweight core, offering additional language support via addons, like Japanese, Korean and Chinese. Without it, we cannot type Japanese, Korean, and Chinese.

However, `fcitx5` is working fine with other browser like `firefox`
Is the nixpkgs version or `tor-borwser` implemented some kind of sandbox so that fcitx5 is not working with it?

### Expected behavior
Japanese, Korean or Chinese can be typed with `fcitx5` in `tor-browser`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.20231202.933d7dc`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NickCao** [comment]
I'm able to reproduce this issue on nixos-unstable, but only when tor-browser is running on xwayland, by setting `MOZ_ENABLE_WAYLAND=1` to force it running on wayland, the issue goes away.

**Comment by amalgame21** [comment]
Good to see it is working on wayland, but I am using xfce....
Sorry I didn't mention that.

**Comment by felschr** [comment]
@amalgame21 can you check if you also get this issue with `mullvad-browser`?

While both browsers use the same code-base the packages currently are a bit different.
`tor-browser` uses a bit of a more isolating wrapper script.

I've proposed to change this here: https://github.com/NixOS/nixpkgs/pull/260871

**Comment by felschr** [comment]
> I thinks the issue is due to the wrapper wiping GTK_IM_MODULE and other input method related environment variables.

I think so, too. The question is do we want to figure out which environment variables we need to pass-through, and potentially do this for other features that might currently be limited, or do we just want to remove this complex wrapper and just allow Tor Browser to see all environment variables?

One other "issue" that is probably related to this is that, at least on Gnome, I see the default Gnome title bar in Tor Browser, while in Mullvad Browser it uses the more compact combined title bar that directly contains all tabs.

**Comment by amalgame21** [comment]
> @amalgame21 can you check if you also get this issue with `mullvad-browser`?
> 
> While both browsers use the same code-base the packages in nixpkgs currently are a bit different. `tor-browser` uses a bit of a more isolating wrapper script.
> 
> I've proposed to change this here: #260871

I can use `fcitx5` in `mullvad-browser` without any issue.

**Comment by amalgame21** [comment]
I think there should be 3 environmental variables:

https://github.com/NixOS/nixpkgs/blob/d996452779de10baca8631d95e6d689be28c317d/nixos/modules/i18n/input-method/fcitx5.nix#L121-L123

Also reference in archwiki:
https://wiki.archlinux.org/title/Fcitx#Set_environment_variables_for_IM_modules

**Comment by felschr** [comment]
> I think these cosmetic issues can actually be seen as a feature since it could, in theory, reduce some fingerprints? But it's up to upstream to fix these loose ends, no reason to ask users to sanitize their environment.

Upstream Tor Browser doesn't do this, though, it could just as well go in the other direction and make users' fingerprints more unique. At least compared to other non-nixpkgs Linux users. Anyway, I don't think it's Nixpkgs's responsibility to add another layer of protection over upstream. And we don't have the same expertise to truly judge the effect our changes have (I'm speaking for all active `tor-browser` package maintainers, I think).

**Comment by amalgame21** [comment]
I can confirm that "ONLY" `NIX_PROFILES` is required for `fcitx5` to work properly.
`GTK_IM_MODULE` and `XMODIFIERS` are not required in my case.
