### ISSUE TITLE
Allow user to supply their `bootstrapFiles` set of tools

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#272750]
### Describe the bug

Today `nixpkgs` provides an outdated set of `bootstrapFiles`: https://github.com/NixOS/nixpkgs/issues/253713

Specifically I keep hitting https://github.com/NixOS/nixpkgs/issues/253274 on any attempts to rebuild 32-bit packages.

Currently I am patching the `pkgs/stdenv/linux/bootstrap-files/i686-unknown-linux-gnu.nix` to provide the working tools built locally:

```diff
--- a/pkgs/stdenv/linux/bootstrap-files/i686-unknown-linux-gnu.nix
+++ b/pkgs/stdenv/linux/bootstrap-files/i686-unknown-linux-gnu.nix
@@ -1,12 +1,4 @@
 {
-  busybox = import <nix/fetchurl.nix> {
-    url = "http://tarballs.nixos.org/stdenv-linux/i686/4907fc9e8d0d82b28b3c56e3a478a288
2f1d700f/busybox";
-    sha256 = "ef4c1be6c7ae57e4f654efd90ae2d2e204d6769364c46469fa9ff3761195cba1";
-    executable = true;
-  };
-
-  bootstrapTools = import <nix/fetchurl.nix> {
-    url = "http://tarballs.nixos.org/stdenv-linux/i686/c5aabb0d603e2c1ea05f5a93b3be8243
7f5ebf31/bootstrap-tools.tar.xz";
-    sha256 = "b9bf20315f8c5c0411679c5326084420b522046057a0850367c67d9514794f1c";
-  };
+  busybox = ./i686-linux/busybox;
+  bootstrapTools = ./i686-linux/bootstrap-tools.tar.xz;
 }
```

I think it would be generally useful to be able to pass non-default tools for workaround purposes and testing purposes of new tools.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wh0** [comment]
people who want this, can you review #317119
