### ISSUE TITLE
Request, add missing dataDir option to service prowlarr in nixos

### ISSUE THREAD

**Issue by henningphan** [NixOS/nixpkgs#272772]
## Enhancement request
Add dataDir option to service prowlarr.
The services sonarr, readarr and radarr supports a dataDir option in nixos but prowlarr doesnt which makes it inconsistent compared to the other services.

Links to those services, notice that they all except prowlarr support a dataDir option

https://github.com/NixOS/nixpkgs/blob/6cb8f045bf95959cde8845ac3bd24a9ef21b3333/nixos/modules/services/misc/sonarr.nix

https://github.com/NixOS/nixpkgs/blob/6cb8f045bf95959cde8845ac3bd24a9ef21b3333/nixos/modules/services/misc/radarr.nix

https://github.com/NixOS/nixpkgs/blob/6cb8f045bf95959cde8845ac3bd24a9ef21b3333/nixos/modules/services/misc/readarr.nix

https://github.com/NixOS/nixpkgs/blame/6cb8f045bf95959cde8845ac3bd24a9ef21b3333/nixos/modules/services/misc/prowlarr.nix

**Comment by jian-lin** [comment]
FYI, https://github.com/NixOS/nixpkgs/pull/215817#pullrequestreview-1294759163 is a better way.

Prior work:
- https://github.com/NixOS/nixpkgs/pull/215817
- https://github.com/NixOS/nixpkgs/pull/172246
- https://github.com/NixOS/nixpkgs/pull/195273
- https://github.com/NixOS/nixpkgs/pull/236428

**Comment by henningphan** [comment]
Thank you. I consider the task closed thanks for the answer.
