### ISSUE TITLE
Mpv using nvdec-copy instead of nvdec

### ISSUE THREAD

**Issue by Wlnfr** [NixOS/nixpkgs#272710]
### Describe the bug
After update from 23.05 to 23.11, mpv started throwing following error and using nvdec-copy instead of normal nvdec.(Not sure if these two are related. Please ignore libva error if it's not related to usage of ```nvdec``` and ```nvdec-copy```, as it's not the point of the issue)
``` [vaapi] libva: vaGetDriverNames() failed with unknown libva error```
Use of nvdec-copy is not desirable as it routes the decoded image data through system memory. In other words, it round-trips the frame through the cpu and back to the gpu, so it's fairly wasteful, especially on older hardware.

### Steps To Reproduce
1. Launch any video with codec supported by the gpu in mpv(tested on h.264 file and VP9 youtube video)
2. See mpv throw a libva error and using nvdec-copy.

### Expected behavior
No libva error is thrown and mpv using nvdec like it did on 23.05

### Additional context
After some digging I found a potential cause that I have no knowledge of how to check/confirm/deny. Issues describing it:
https://github.com/mpv-player/mpv/issues/11004
https://github.com/mpv-player/mpv/issues/10839
```--gpu-api=vulkan``` described in second issue does not help.
All packages are installed and configured via ```configuration.nix```
CPU Q9650
GPU: GT1030 Nvidia driver version 545.29.02

```
services.xserver = {
      enable = true;
      videoDrivers= [ "nvidia" ];
```
Please ask for any additional required system information/logs.
### Notify maintainers

@AndersonTorres
### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1209.933d7dc15509`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tejing1** [comment]
Well, it's not literally the same issue as you linked, we do have the relevant headers: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/mpv/default.nix#L201

**Comment by Wlnfr** [comment]
I have linked these two issues because they are the only things I was able to find that I believed to be relevant to my issue with my limited understanding of how these things work, which is why I called it a potential cause that I have no knowledge on how to check/confirm/deny.

**Comment by tejing1** [comment]
mpv is being built with ffmpeg 6, which is [built with](https://github.com/NixOS/nixpkgs/blob/b4372c4924d9182034066c823df76d6eaf1f4ec4/pkgs/development/libraries/ffmpeg/generic.nix#L556) `nv-codec-headers-11`, while mpv is built with `nv-codec-headers`.

Thanks for drawing my attention to that line in the ffmpeg derivation over on discord, @Wlnfr

So I tested if that was the source of the issue, and indeed, this used `nvdec` as desired:
```
pkgs.wrapMpv (pkgs.mpv-unwrapped.override { nv-codec-headers = pkgs.nv-codec-headers-11; }) {}
```
