### ISSUE TITLE
ns-usbloader crashes when trying to open file picker

### ISSUE THREAD

**Issue by NekoNoor** [NixOS/nixpkgs#272798]
### Describe the bug
when i click on any button that would open a file picker the program crashes with these errors
```
(java:61243): GLib-GIO-ERROR **: 01:08:49.051: No GSettings schemas are installed on the system
fish: Job 1, 'sudo ns-usbloader' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### Steps To Reproduce
1. add `programs.ns-usbloader.enable = true` to your system configuration and rebuild
2. launch `ns-usbloader`
3. click on "select files"

### Expected behavior
a file picker should open

### Screenshots
N/A

### Additional context
I am using a the `plasmawayland` session

### Notify maintainers

@soupglasses 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3-zen1, NixOS, 24.05 (Uakari), 24.05.20231201.91050ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by soupglasses** [comment]
Which desktop environment/window manager are you running? Also please attempt running ns-usbloader without root. I shouldn't require it and may be why it's crashing.

**Comment by soupglasses** [comment]
Which desktop environment/window manager are you running? Also please attempt running ns-usbloader without root. I shouldn't require it and may be why it's crashing.

I think I know what's wrong, and it's likely package related. I will have a look at this later today.

**Comment by onsamyj** [comment]
Just want to clarify: I’m getting `(java: 8511): GLib-GIO-ERROR **: 21:47:57.472: No GSettings schemas are installed on the system`. Is this the same error or different?
