### ISSUE TITLE
Haskell packages: attribute "webkitgtk24x" missing

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#27288]
## Issue description
I was running `nox-review`, and it noticed that the package `haskellPackages.leksah` wouldn't build. I believe this is because it depends on `webkitgtk3`, which also won't build, with the same message:
```bash
$nix-build -A haskellPackages.leksah .
error: attribute ‘webkitgtk24x’ missing, at /home/siddharthist/code/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:202442:10
(use ‘--show-trace’ to show detailed location information)

$ nix-build -A haskellPackages.webkitgtk3                   
error: attribute ‘webkitgtk24x’ missing, at /home/siddharthist/code/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:202442:10
(use ‘--show-trace’ to show detailed location information)
```
@volth Might this have something to do with #26125?

## Technical details

* System: `17.03.1395.9b948ea439 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.11`
* Nixpkgs version: `"17.03.1395.9b948ea439"`
* Sandboxing enabled: `build-use-sandbox = true`

**Comment by bennofs** [comment]
This should get fixed on next haskell-updates, it is already merged into upstream cabal2nix: https://github.com/NixOS/cabal2nix/pull/283

**Comment by jtojnar** [comment]
Is there any ETA for haskell-updates? I see that until two weeks ago, the index was being updated every [two to five days](https://github.com/volth/nixpkgs/commits/ab8af93b2693cbc97ff1836f2b1518c0e7f58b57/pkgs/development/haskell-modules/hackage-packages.nix].

/cc @peti

**Comment by peti** [comment]
We haven't merged `haskell-updates` recently because we've using that branch to run test builds for https://github.com/NixOS/nixpkgs/pull/27196. Anyhow, I'll generate a quick update and merge it ASAP.
