### ISSUE TITLE
Build failure: olive-editor

### ISSUE THREAD

**Issue by IncredibleLaser** [NixOS/nixpkgs#272832]
### Steps To Reproduce

1. build olive-editor

### Build log

[build.log](https://github.com/NixOS/nixpkgs/files/13611090/build.log)

### Notify maintainers

@balsoft 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/37p8gq9zijbw6pj3lpi1ckqiv18j2g62-stdenv-linux
copying path '/nix/store/37p8gq9zijbw6pj3lpi1ckqiv18j2g62-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 24.05 (Uakari), 24.05.20231201.91050ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

This is NixOS unstable using flakes.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
builds on latest master eaa482cddd4d6c05bb7a19f15717d32b068575a8

```
 nix-build -A olive-editor
/nix/store/94h96rkraldhyhjxqfk7q0dfiyxq2rqg-olive-editor-unstable-2023-06-12
```

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.4, NixOS, 24.05 (Uakari), 24.05.20231208.26117ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(kirillvr): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by IncredibleLaser** [comment]
True, I can confirm this. Thanks for checking. I'll close this.
