### ISSUE TITLE
Build failure: jetbrains-jdk: generates link to non-existing file

### ISSUE THREAD

**Issue by dev-null-undefined** [NixOS/nixpkgs#272884]
### Steps To Reproduce
Maybe related to #210753 

build jetbrains.jdk from master branch

```console
[user@system:~]$ nix build .#jetbrains.jdk
[user@system:~]$ file result/share/man
result/share/man: broken symbolic link to ../lib/openjdk/man
```

### Notify maintainers

@GenericNerdyUsername - Hope you don't mind the ping, sorry if you do

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231112.e44462d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/0y446mjvwzrhv723jh0lpkaz9gw8jzbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GenericNerdyUsername** [comment]
I can't reproduce this. What does `nix build nixpkgs#jetbrains.jdk` give for you?

**Comment by dev-null-undefined** [comment]
> I can't reproduce this. What does `nix build nixpkgs#jetbrains.jdk` give for you?

My bad in naming the PR, the package does build but the man output of it points to broken symlink

I am building on master branch, commit ff932567f6177d1a4ac2c7c73db3a3e750bc4bf7 system x86_64-linux.
@GenericNerdyUsername
