### ISSUE TITLE
opera/vivaldi: crash on "save link/image as..."

### ISSUE THREAD

**Issue by 239** [NixOS/nixpkgs#27299]
## Issue description
Vivaldi crashes when saving resources but it works fine if browser is started from terminal.
Same behavior with Opera 46 (gtk3), no issue with version 45 (gtk2).

### Steps to reproduce
Right-click -> "Save link/image as..."

## Technical details
* System: NixOS: 17.03
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1458.057f89b934
* Sandboxing enabled: false

**Comment by JohnAZoidberg** [comment]
Seems to work for me on NixOS unstable (post 19.09).
Can you reproduce?

**Comment by 239** [comment]
No, seems to be fixed by now.
