### ISSUE TITLE
gerbil 0.18 cannot produce working executables on macOS

### ISSUE THREAD

**Issue by holmesmr** [NixOS/nixpkgs#272967]
### Describe the bug
gerbil 0.18 in nixpkgs is compiled with `--enable-shared`, which prohibits gxc from producing static executables ([this comment][gerbil-static-note] appears to suggest that it is not working from a Nix context; it is also probably undesirable for Gerbil executables to be statically linked if packaged in nixpkgs anyway). However, the linked executable links with `libgerbil` incorrectly. The reason appears to be that the `gxc` driver in gerbil hard-codes the distribution home dir at compile time: [see the affected code in v0.18.0](https://github.com/mighty-gerbils/gerbil/blob/v0.18/src/gerbil/compiler/driver.ss#L161-L165). Obviously, in Nix, the final install dir cannot be known at compile time; the end result is that the temporary directory used during the derivation is used instead when linking `libgerbil`. This obviously results in a linker error at runtime:

```console
bash-5.2$ gerbil build
... build in current directory
... compile hello/lib
... compile hello/main
... compile exe hello/main -> /Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello
/tmp/gxc.1702058718.314978/cepheus__hello__main.scm:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello.scmx:
/tmp/gxc.1702058718.314978/cepheus__hello__main.c:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello.c:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello_.c:
bash-5.2$ gerbil env hello
dyld[27681]: Library not loaded: /private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so
  Referenced from: <no uuid> /Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello
  Reason: tried: '/private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so' (no such file), '/private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so' (no such file), '/usr/local/lib/libgerbil.so' (no such file), '/usr/lib/libgerbil.so' (no such file, not in dyld cache)
*** ERROR IN std/misc/process#run-process__% -- 
*** ERROR IN "misc/process.ss"@28.35 [ProcessError]: process exited with non-zero status
--- irritants: "hello" 6 (path: "hello" arguments: () environment: #f directory: #f stdin-redirection: #f stdout-redirection: #f stderr-redirection: #f pseudo-terminal: #f show-console: #f) 
--- continuation backtrace:
0  raise                                                                              
1  std/misc/process#run-process__%                                                                                                                                       ((if (let () (declare (not safe)) (procedure? _check-status555844_)) _check-status5...
```

Given that [glow-lang][glow-lang-deriv] appears to use `gxi` (the Gerbil interpreter), it would appear that this defect is at least known to some maintainers; however, it does not appear to be documented.

### Steps To Reproduce
1. Create a nix-shell or other config with `gerbil` installed
2. Follow the steps in gerbil's [prepare your project tutorial][hello-world-tutorial] to create a skeleton project
3. run `gerbil build` to build the project
4. run `gerbil env hello` to run the `hello` program compiled in step 3.

### Expected behavior
The program should act as expected in the tutorial; that is, the program should exit due to an not-implemented error.

### Screenshots
Screenshots of terminal text aren't useful; appropriate output has been supplied elsewhere.

### Additional context
This was only tested on `aarch64-darwin`, but based on symptoms all platforms are likely to be affected.
Since the `lib` dir of the Gerbil runtime is on path in nix, usage of `install_name_tool` can be used to fixup builds on darwin by using rpath; of course, this should only be considered acceptable when unpackaged as packaged executables should always be linked by store path. Some level of fixup is possible in that context but ideally such fixup should be provided as a util in nixpkgs or made unnecessary.

```console
bash-5.2$ install_name_tool -change /private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so @rpath/libgerbil.so .gerbil/bin/hello
bash-5.2$ .gerbil/bin/hello
*** ERROR -- 
*** ERROR IN ? [Error]: Implement me!
--- continuation backtrace:
0  error  
```

`otool -L` output on sample executable:

```console
bash-5.2$ otool -L .gerbil/bin/hello
.gerbil/bin/hello:
        /private/tmp/nix-build-gerbil-0.18.drv-0/source/build/lib/libgerbil.so (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/fvwpdi9zj1dw6nk2ncgg93iz7m8d6y9f-gerbil-0.18/gerbil/v0.18/lib/libgambit.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/a377d66g1rgsd4vkzxdhkza5g55fkmky-zlib-1.3/lib/libz.dylib (compatibility version 1.0.0, current version 1.3.0)
        /nix/store/16ccmy0kylpjgnplh0rkyx4az3gzy5rj-openssl-3.0.12/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /nix/store/16ccmy0kylpjgnplh0rkyx4az3gzy5rj-openssl-3.0.12/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /nix/store/cbs4djx36kk5h04fn91p51wprmlapbsr-sqlite-3.43.2/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

Note that the `GERBIL_BUILD_PREFIX` is only interpreted at build time, and refers to the location of the current build context; as such, setting it to the nix store location of `gerbil` does not fix the problem and instead causes local package resolution to fail.

Per [this comment](https://github.com/NixOS/nixpkgs/issues/272967#issuecomment-1849251855), it appears this issue only affects macOS.

### Notify maintainers

~~No maintainers are listed in `meta.maintainers`;~~ @fare appears to be the last to touch the `gerbil` package.

### Metadata
N.B.: actual command run was `nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/09ec6a0881e1a36c29d67497693a67a16f4da573.tar.gz -p nix-info --run "nix-info -m"` as I am using the Determinate Systems Nix installer which does not set up `nix-channel`.

```console
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/09ec6a0881e1a36c29d67497693a67a16f4da573.tar.gz -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

From `flake.lock` for my `nix-darwin` configuration, I am using the above mentioned `nixpkgs-unstable` version (`09ec6a0881e1a36c29d67497693a67a16f4da573`), since `nix-info` can't rely on channel info.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
[hello-world-tut]: https://cons.io/guide/getting-started.html#prepare-your-project
[glow-lang-deriv]: https://github.com/NixOS/nixpkgs/blob/0a2c90162b5e4b0a2bd0f482dfc9423b1e4c788e/pkgs/development/compilers/gerbil/glow-lang.nix
[gerbil-static-note]: https://github.com/NixOS/nixpkgs/blob/0a2c90162b5e4b0a2bd0f482dfc9423b1e4c788e/pkgs/development/compilers/gerbil/build.nix#L20-L22

**Comment by fare** [comment]
Thanks a lot for the bug report. It looks like the default `(gerbil-home)` is wrong in `src/gerbil/compiler/driver.ss` and we should be using whatever `(path-expand "~~")` expands to, which looks like it works.

@vyzo any suggestion?

**Comment by vyzo** [comment]
It ahould be doing that already.

**Comment by vyzo** [comment]
there is no GERBIL_HOMEing going on, right?

**Comment by fare** [comment]
Aha. The Nix packaging has improved between 0.18 and 0.18.1. There is no GERBIL_HOME business in the current packaging, but maybe there was in 0.18?

@holmesmr Can you try the latest 0.18.1 from nixpkgs `master`? It works for me and hopefully should work for you.

**Comment by holmesmr** [comment]
> @holmesmr Can you try the latest 0.18.1 from nixpkgs `master`? It works for me and hopefully should work for you. Weird that it doesn't work for you in 0.18.

Unless I'm missing something, 0.18.1 doesn't appear to be in nixpkgs master: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/gerbil/default.nix#L5 (permalink to current rev: https://github.com/NixOS/nixpkgs/blob/9a8c7261525fce16e990736b9a514d2aeb4ee95e/pkgs/development/compilers/gerbil/default.nix#L5)

I'm using flakes rather than `nix-shell` directly, but I've tried both having a `devShell` with `gerbil` and `gerbil-unstable` in `buildInputs`, and also the following flake using `pkgs.gerbil-support.gerbilPackage`:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  description = "A very basic gerbil flake";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          pkgs = import nixpkgs { inherit system; };
          gerbilPkg = pkgs.gerbil-support.gerbilPackage {
            pname = "hello";
            version = "0.1.0";
            pre-src = {
              fun = (d: d.src);
              src = ./.;
            };
            gerbil-package = "hello";
            meta = {};
          };
        in with pkgs; {
          devShell = mkShell {
            buildInputs = [
              # gerbil-unstable
              gerbilPkg
            ];
          };
          defaultPackage = gerbilPkg;
        }
      );
}
```

The result of building this is the same, though:

```console
$ nix develop                                                                                                                                                                                             
bash-5.2$ which hello
/nix/store/dx63kms3kw13p3a7xinnfn97kkd4vdff-hello-0.1.0/bin/hello
bash-5.2$ hello
dyld[76209]: Library not loaded: /private/tmp/nix-build-gerbil-unstable-2023-10-13.drv-0/source/build/lib/libgerbil.so
  Referenced from: <no uuid> /nix/store/dx63kms3kw13p3a7xinnfn97kkd4vdff-hello-0.1.0/gerbil/bin/hello
  Reason: tried: '/private/tmp/nix-build-gerbil-unstable-2023-10-13.drv-0/source/build/lib/libgerbil.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/nix-build-gerbil-unstable-2023-10-13.drv-0/source/build/lib/libgerbil.so' (no such file), '/private/tmp/nix-build-gerbil-unstable-2023-10-13.drv-0/source/build/lib/libgerbil.so' (no such file), '/usr/local/lib/libgerbil.so' (no such file), '/usr/lib/libgerbil.so' (no such file, not in dyld cache)
Abort trap: 6
bash-5.2$ 
```

**Comment by vyzo** [comment]
You can set GERBIL_HOME as a workaround

**Comment by vyzo** [comment]
Maybe put that in the recipe, it is there for such casea of rehoming.

Maybe it is precisely the fix for nix.

**Comment by holmesmr** [comment]
Having manually overlaid gerbil 0.18.1, I tried setting `GERBIL_HOME` but to no avail:

```console
bash-5.2$ gerbil clean
... clean current package
... remove /Users/cepheus/projects/gerbil/hello-world/.gerbil/lib/cepheus/hello/lib.ssi
... remove /Users/cepheus/projects/gerbil/hello-world/.gerbil/lib/static/cepheus__hello__lib.scm
... remove /Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello
... remove /Users/cepheus/projects/gerbil/hello-world/.gerbil/lib/static/cepheus__hello__main.scm
bash-5.2$ export GERBIL_HOME=/nix/store/1gfzg7flyyzn0f2k076v0h2g18ms89n4-gerbil-0.18.1/gerbil
bash-5.2$ gerbil build
... build in current directory
... compile hello/lib
... compile hello/main
... compile exe hello/main -> /Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello
/tmp/gxc.1702226939.381606/cepheus__hello__main.scm:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello.scmx:
/tmp/gxc.1702226939.381606/cepheus__hello__main.c:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello.c:
/Users/cepheus/projects/gerbil/hello-world/.gerbil/bin/hello_.c:
bash-5.2$ otool -L .gerbil/bin/hello
.gerbil/bin/hello:
        /private/tmp/nix-build-gerbil-0.18.1.drv-1/source/build/lib/libgerbil.so (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/1gfzg7flyyzn0f2k076v0h2g18ms89n4-gerbil-0.18.1/gerbil/v0.18.1/lib/libgambit.dylib (compatibility version 0.0.0, current version 0.0.0)
        /nix/store/a377d66g1rgsd4vkzxdhkza5g55fkmky-zlib-1.3/lib/libz.dylib (compatibility version 1.0.0, current version 1.3.0)
        /nix/store/16ccmy0kylpjgnplh0rkyx4az3gzy5rj-openssl-3.0.12/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /nix/store/16ccmy0kylpjgnplh0rkyx4az3gzy5rj-openssl-3.0.12/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /nix/store/cbs4djx36kk5h04fn91p51wprmlapbsr-sqlite-3.43.2/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

**Comment by fare** [comment]
`gerbil build` works great for me, and no `tmp/nix-build` anywhere in sight.

Can you try v0.18.1, and if the problem persists, can you give instructions sufficient to reproduce from a clean environment?

**Comment by fare** [comment]
NB: `gerbil build` definitely manages to create executables for me using the v0.18.1 package, and I strongly believe it used to with v0.18 already.

**Comment by holmesmr** [comment]
On further testing, the exact same flake builds correctly on aarch64-linux:
```console
cepheus@lima-debian-12:~/hello-world$ ldd $(which hello)
	linux-vdso.so.1 (0x0000fffff7ffb000)
	libgerbil.so => /nix/store/28p1h0xnxr6y0a1qzg4r43bgv7irviv4-gerbil-0.18/gerbil/v0.18/lib/libgerbil.so (0x0000fffff6190000)
	libgambit.so => /nix/store/28p1h0xnxr6y0a1qzg4r43bgv7irviv4-gerbil-0.18/gerbil/v0.18/lib/libgambit.so (0x0000fffff5970000)
	libdl.so.2 => /nix/store/cv8mfy5wdfwfw4iwhdlkl4ddy8apl667-glibc-2.38-27/lib/libdl.so.2 (0x0000fffff5940000)
	libm.so.6 => /nix/store/cv8mfy5wdfwfw4iwhdlkl4ddy8apl667-glibc-2.38-27/lib/libm.so.6 (0x0000fffff5890000)
	libz.so.1 => /nix/store/s07pkwgpf7gdsz9m66vxyx4fbd0879vg-zlib-1.3/lib/libz.so.1 (0x0000fffff5850000)
	libssl.so.3 => /nix/store/81b6msp3w1dskfjmvlk0s0ifn7q66bkw-openssl-3.0.12/lib/libssl.so.3 (0x0000fffff5790000)
	libcrypto.so.3 => /nix/store/81b6msp3w1dskfjmvlk0s0ifn7q66bkw-openssl-3.0.12/lib/libcrypto.so.3 (0x0000fffff5350000)
	libsqlite3.so.0 => /nix/store/i57xb0i0p94sz6jxhbc0vdd8amnakayl-sqlite-3.43.2/lib/libsqlite3.so.0 (0x0000fffff51e0000)
	libc.so.6 => /nix/store/cv8mfy5wdfwfw4iwhdlkl4ddy8apl667-glibc-2.38-27/lib/libc.so.6 (0x0000fffff5030000)
	/nix/store/cv8mfy5wdfwfw4iwhdlkl4ddy8apl667-glibc-2.38-27/lib/ld-linux-aarch64.so.1 (0x0000fffff7fbe000)
	libpthread.so.0 => /nix/store/cv8mfy5wdfwfw4iwhdlkl4ddy8apl667-glibc-2.38-27/lib/libpthread.so.0 (0x0000fffff5000000)
```

It seems this issue is specific to building under macOS - I'll revise the report to reflect that.

**Comment by fare** [comment]
A variant of your `flake.nix` works for me, building executables without this `tmp/nix-build` nonsense. Are you sure your environment is clean? You shouldn't be exporting any `GERBIL_HOME`, `GERBIL_PREFIX`, `GERBIL_BUILD_PREFIX` or such variables.

**Comment by fare** [comment]
OK, this looks macOS specific enough that it might not be a bug in Gerbil or its packaging itself, but in how Nix fails to do on macOS the equivalent of `patchelf` on Linux. Still sad, and something we might have to work around on macOS.

**Comment by drewc** [comment]
Hey,

MacOS strips LD_LIBRARY_PATH, DYLD_LIBRARY_PATH and the like so just
passing them in the environment is pointless as they are stripped.

The correct thing is "So be cautious with DYLD_LIBRARY_PATH and friends.
Even better is to pass an -rpath to ld along with a -L<library-path> for
building if needed."

AKA magic linker flags. Apple's `ld`is not gnu's `ld` at all and cannot be.

See:
https://github.com/mighty-gerbils/gerbil/tree/master/homebrew#documentation

It actually makes sense security-wise but can be a real PITA. If you cannot
link properly at build time and need to change the link paths you can use:

       install_name_tool - change dynamic shared library install names


That can add/remove/change the rpaths.

Here is a working binary and the lib bindings. No finesse needed, build
script exactly the same as on linux.

drewc-iMac:ecm-user drewc$ otool -L ~/.gerbil/bin/login
/Users/drewc/.gerbil/bin/login:
        /usr/local/opt/gerbil-scheme/v0.18-47-g0917172a/lib/libgerbil.so
(compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/gerbil-scheme/v0.18-47-g0917172a/lib/libgambit.dylib
(compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/zlib/lib/libz.1.dylib (compatibility version 1.0.0,
current version 1.3.0)
        ***@***.***/lib/libssl.3.dylib (compatibility version
3.0.0, current version 3.0.0)
        ***@***.***/lib/libcrypto.3.dylib (compatibility
version 3.0.0, current version 3.0.0)
        /usr/local/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version
9.0.0, current version 9.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current
version 1319.100.3)

HTH,

--drewc

**Comment by fare** [comment]
@holmesmr you're the one with a Mac and Nix. Can you make a PR that uses one of @drewc's solutions?

**Comment by holmesmr** [comment]
I'll see if I can find some time to apply workarounds this week

**Comment by holmesmr** [comment]
Doing a bit more investigation, it seems that the soname of `libgerbil.so` is this path; per [this hint in the stdenv platform docs][darwin-soname] it seems that it can be fixed by using `install_name_tool -id` to change the soname to the final path. I'm rebuilding gerbil now using the vendored builder to see if this fixes it; if it does I'll turn it into a proper PR.

[darwin-soname]: https://github.com/NixOS/nixpkgs/blob/23959be581c8adf54bc76a23d742ba3e51bdbcc9/doc/stdenv/platform-notes.chapter.md?plain=1#L19
