### ISSUE TITLE
Update request: flutter 3.13.8 → 3.16.3

### ISSUE THREAD

**Issue by Henry-Hiles** [NixOS/nixpkgs#272977]
- Package name:
- Latest released version:
3.16.3
- Current version on the unstable channel:
3.13.8
- Current version on the stable/release channel:
3.13.8

- [*] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NixOS/flutter

-----

Note for maintainers: Please tag this issue in your PR.
 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Henry-Hiles** [comment]
Also, perhaps flutter could have an updateScript added, like dart has

**Comment by hatch01** [comment]
I have the same problem, the flutter version is very outdated to work on recent projects!

**Comment by Henry-Hiles** [comment]
Yeah, it would he nice. I can try doing it myself but I'm not experienced with flutter packaging on nix.

**Comment by hatch01** [comment]
I tried here #275522 if it could help

**Comment by Henry-Hiles** [comment]
Will be fixed by #276050
