### ISSUE TITLE
Unity3D: build or package games fpr NixOS

### ISSUE THREAD

**Issue by Hinidu** [NixOS/nixpkgs#27300]
Hello!
I'm trying to run a game on NixOS built with Unity3D on Windows and I can't because it assumes FHS-compliant paths to linter and dynamic libraries. And the same is still the true when I build the game using Unity3D installed on NixOS.
I found some information about patchelf and buildFHSUserEnv but I have not enough experience to find out what exactly I should do. My experiments with patchelf and ldd have been failed :cry:
Maybe we can add some helper to nixpkgs or provide some information in documentation about this topic?
Thank you in advance!

PS: I'm not sure whether it is the right place to ask but I didn't get any response on irc channel.
ping @jb55 @abbradar

**Comment by lheckemann** [comment]
One thing that could work is running it in `steam-run`. Failing that, some details on what you tried with patchelf and how it failed would be useful.

**Comment by Hinidu** [comment]
@lheckemann thank you for suggestion I will look into `steam-run`.
If I'm trying to run executable without any modifications I get `The file 'c1.x86_64' doesn't exist or could not be executed.` if I understood correctly this misleading error means means that it can't find the specified linker `/lib64/ld-linux-x86-64.so.2` because the file itself obviously exists.
I found that for Unity3D itself linker is changed to `gcc-wrapper/nix-support/dynamic-linker`, so I found it in my `/nix/store` and set it with `patchelf --set-interpreter`.
After that I get the error:
```
Failed to execute process './c1.x86_64'. Reason:
exec: Permission denied
```
Also I've run `find . -name '*.so' | xargs ldd` and found that linker can't find some dynamic libraries. If I remember correctly I didn't fix all of them using `LD_LIBRARY_PATH` or explicit installation of respective packages to put these libraries into `/nix/store/*user-environment/lib`. Maybe I should try to make all dynamic libraries used in '*.so' files and it should fix the problem?
By the way `ldd` on executable itself also give me `Permission denied` error just like if I try to execute it. (`sudo` doesn't help).

**Comment by lheckemann** [comment]
It's not set to `gcc-wrapper/nix-support/dynamic-linker`, it's set to the *contents* of that file. Try doing that instead, assuming `steam-run` on the unmodified binary doesn't work.

**Comment by Hinidu** [comment]
Oh, I definitely should learn more about nix language. Thank you very much @lheckemann ! After setting interpreter correctly I'm getting more obvious error:
```
./c1.x86_64: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```
I will try to resolve all libraries and write here what I'll get.

**Comment by abbradar** [comment]
@Hinidu `steam-run` should handle that problem -- try it! Install `steam-run` and run it as `steam-run ./foo`.

**Comment by Hinidu** [comment]
Thanks @abbradar it works like a charm! :+1:
