### ISSUE TITLE
Installer builds derivations on host store

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#27307]
## Issue description

The current installer builds the derivations on the store of the installer's image, which means that if you install a large config the install will fail since there is not enough space available.

Tested with nixpkgs unstable minimal install image.

**Comment by copumpkin** [comment]
This is my fault, sorry. I welcome suggestions for how to fix without duplicating all the logic that led to this change in the first place! 😦

**Comment by bennofs** [comment]
@copumpkin would it be possible to mount a unionfs at /nix so that it can use the new disk for storage?

**Comment by copumpkin** [comment]
There's also the new Nix 1.12 custom store location stuff, which will probably help us.

**Comment by emmanuelrosa** [comment]
Yes! I've been pondering this issue myself. My work-around has been to install as little as possible, and then once installed add the remaining packages. That's for a release-17.03 install; when I tried an unstable ISO I couldn't get it to install at all with only 2GB of RAM available.

I've thought about...

1. Temporarily utilizing the swap partition by placing a filesystem on it and making it the rw part of the unionfs.
2. For USB flash-drive installs, utilize a partition on the remaining space as the rw part of the unionfs.

But to generalize the concept, perhaps it's possible to pass a parameter via the boot-loader to tell whatever script sets up the Nix store unionfs to mount the filesystem at the specified block device.

**Comment by Shados** [comment]
I tend to do frequent installations to little memory-constrained VPS nodes in different locations (for e.g. monitoring agents, DNS nodes), and this issue bites me in the ass every single time >.>. I've been working around it by temporarily reducing my configuration from the intended final config (which I have prepared beforehand, as they're all pretty similar) to a minimal one, then building it to the final one after reboot.

**Comment by copumpkin** [comment]
My apologies. I'll try to improve this during the NixCon hackathon early next week! It won't be my primary goal for the hackathon but it's something that's been annoying me for a while so it'll probably get done 😄

**Comment by copumpkin** [comment]
As you've probably noticed (from the latest nix-devel email thread on it) I didn't work on this at NixCon, but it's still pretty high in my priority queue of things to do. If someone else wants to take a stab at it though, I won't be offended 😄

**Comment by danbst** [comment]
BTW, the idea to use nixUnstable in `nixos-install` should deserve some thought:
- the Nix db should be backwards compatible, so no issues when running nix 1.11 after reboot
- no need to write extra code, when it can be done in several 1.12 commands
- battle test on fresh users. This is debatable though, but `nixos-unstable` users are warned about possible hiccups

**Comment by copumpkin** [comment]
We already do use `nixUnstable` inside `nixos-prepare-root`, which `nixos-install` uses, so I think we're already set for this. Could definitely just set up a remote store for this.

**Comment by vcunat** [comment]
Claimed to be fixed by #34636.

**Comment by tycho01** [comment]
did #34636 make it into 18.03? I'm running into this on that.
has anyone who ran into this managed to verify this fix?
