### ISSUE TITLE
`libnvidia-pkcs11.so` missing RPATH entry for `libcrypto.so.1.1`

### ISSUE THREAD

**Issue by tejing1** [NixOS/nixpkgs#273064]
### Describe the bug
The RPATH of `libnvidia-pkcs11.so`, as installed by the standard nvidia package (`pkgs.linuxPackages.nvidia_x11.out`) in nixos 23.11, has no entry for `libcrypto.so.1.1`, causing it to fail if anyone actually used that particular interface.

### Steps To Reproduce
```
$ ldd /run/opengl-driver/lib/libnvidia-pkcs11.so
	linux-vdso.so.1 (0x00007ffc75dd6000)
	libcrypto.so.1.1 => not found
```

### Expected behavior
The nvidia package should set proper RPATHs on the installed libraries.

### Additional context
I ran into this because I was trying to clean up the steam package of issues, and steam's `pressure-vessel` does a lot of sanity checking of its environment and reported the issue from inside the FHS environment.

### Notify maintainers
@jonringer @kiskae @edwtjo

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.20231202.933d7dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
That library is an internal compatibility layer for openssl1.1. Since we link openssl3 into the nvidia driver it never gets used and is meant to fail to load. Since NixOS makes sure that openssl3 is always available this library is functionally useless.

We could probably just remove that file (like we do with `libnvidia-gtk2`) to regain some disk space and satisfy the checks you mentioned.

**Comment by tejing1** [comment]
Sounds good. Better to not ship it than ship it broken, especially if nobody needs it.
