### ISSUE TITLE
How to maintain a long-lived custom nixpkgs tree?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#27312]
I would like to maintain a custom nixpkgs tree to support a project of mine. I am looking for advice on the most practical and socially useful way to do this. This issue is related to #27298.

Here is what I have in mind:

1. Base packages are from a recent stable release (not bleeding edge.)
2. Newer versions of important packages are cherry-picked from master (not many, only when needed.)
3. Missing packages are developed in my tree and upstreamed asynchronously (merged into my tree without waiting for a merge onto master.)

Sounds fine, right? The bit I don't have worked out his how to asynchronously upstream the packages without making a mess. Here are the options I can see, ordered from what would be most convenient from my own perspective:

1. I periodically PR my whole tree to nixpkgs master, which will cover all the packages that I have added or updated. This would be easy for me but it would require an upstream maintainer who is willing to merge my whole tree.
2. I make each change on a topic branch which I merge into my own tree immediately and also PR to nixpkgs master for merging whenever it suits upstream. This could work in one of two ways:
    1. Upstream does a full `git merge` to accept my Git history. This should work smoothly even if I am sync'ing frequently with upstream and other people are independently hacking the code there (git will automatically merge.)
    1. Upstream does a rebase/squash/cherry-pick to replace my git history. This will require some caution: I can expect conflicts when I pull from upstream and I will have to avoid e.g. accidentally rolling back to an older version of my own code, or clobbering a change that somebody else made in the upstream repo, etc.
3. Instead of forking nixpkgs and managing changes with git, I import the standard nixpkgs and make all of my changes using nix code to do the relevant overrides, etc. This way I will not have any Git conflicts but my code will be quite disconnected from nixpkgs, and for upstreaming I would basically need to write a second version as a nixpkgs patch.

Does anybody have a recommendation based on relevant experience?

Just now my take is this:

- Option 1 would be fantastic, but I don't expect to find a willing maintainer.
- Option 2(i) would be fine too. I already work on topic branches so it is not much extra work to create two PRs.
- Option 2(ii) would be okay if I am very conservative about when I sync with upstream. Likely I would do all new packaging in my own tree and then only send a squashed PR upstream once it is very stable and I am unlikely to make more changes (because I am just not really willing to resolve conflicts the old fashioned way.) So for example I would not have send the Pharo update (#26924) yet and rather waited a few months in case I need to make more improvements.
- Option 3 is a bit of an unknown. Could be great but if so I'd hope that somebody has already done it and can show me how :)

Tips would be welcome!

**Comment by Mic92** [comment]
Here is what I do: I basically follow this article: http://anderspapitto.com/posts/2015-11-01-nixos-with-local-nixpkgs-checkout.html
I add commits for package first to my `master` branch and then make a pull request the following way:

```
$ git fetch upstream master
$ git checkout upstream/master
$ git cherry-pick <commit-hash>
$ git checkout -b topic-branch
$ git push origin topic-branch
```

I use `git-rebase` all the time, so that my personal commits are always on top of the upstream commits.
Since rebasing also implies `git push --force` regulary, I have different branches for different machines (when I for instance test expressions on my server). When a commit would change slightly during merge into `nixpkgs`, I would get a merge conflict during rebase and I can just use `git rebase --skip` instead. If somebody else would have changed something in the same place I would resolve the merge conflict as usual. [git-rerere]https://git-scm.com/blog/2010/03/08/rerere.html is also helpful here sometimes. Instead of using the `nixpkgs-unstable` branch, I lookup branch commits in [hydra](https://hydra.nixos.org/jobset/nixpkgs/trunk/evals).

**Comment by volth** [comment]
I use what could be called 2 (iii): 
A. each of the changes which are going to be PRs have its own branch which merged to "my nixpkgs" (which is a some relatively stable commit of upstream nixpkgs + these merges)
B. the changes which are not going to be PR are mostly done as overlays, not as patches to nixpkgs.
C. Some patches are needed anyway to support B., they go to a A.-like branch which is merged the same way.

**Comment by lukego** [comment]
@volth Thanks for the experience report!

I suppose this method mostly works for one-person projects. If you are rebasing your branch all the time then you don't have a stable history so other people can't fork and pull from you.

I am looking for a solution that allows me to collaborate with other people "downstream." It needs to be possible for other people to contribute to our tree and help to maintain it, much like the way the upstream nixpkgs master branch is maintained (except that downstream we will be making changes specifically to support one application.)

**Comment by lukego** [comment]
@volth did you edit that description or did I misread it the first time? I thought you were always rebasing "your" nixpkgs branch but it doesn't look like it.

The setup you are describing sounds like either 2(i) if upstream are merging your feature branches with history or like 2(ii) if upstream are merging without the history (rebase/squash/etc). How does that play out in practice? (Later, when you merge with a stable upstream that includes the features that you contributed, does Git know that it is the same code or do you get conflicts?)

**Comment by volth** [comment]
it is like:
```bash
# choose a base upstream
 git checkout -f 47868cbfb8659c16736e2cfbeb5bc67d6aceccf1 # master 2017-07-11

# mark it just in case (never used actually)
 git branch -f used-master HEAD
 git push git@github.com:volth/nixpkgs.git -f used-master

# my PRs (not yet in master), when one is accepted into master, git merge does nothing and could be removed
 git merge --log --no-edit bashcompletion-later-init                                # https://github.com/NixOS/nixpkgs/issues/22648
 git merge --log --no-edit test-driver-remove-old-statedir                          # https://github.com/NixOS/nixpkgs/pull/22692 (stalled)
 git merge --log --no-edit libvirt-3.2.0                                            # https://github.com/NixOS/nixpkgs/pull/25411 (3.5.0)
 git merge --log --no-edit aerospike-init-3.14.0.1                                  # https://github.com/NixOS/nixpkgs/pull/26855
 # blablabla, more PRs

# my non-PRs patches
 git merge --log --no-edit ocaml-llvm-3.7 #  reversing of other's PR, downgrade from 3.9 -> 3.7
 # blablabla, more patches

# and now it is my master
 git branch -f master HEAD
 git push git@github.com:volth/nixpkgs.git -f master
````

**Comment by lukego** [comment]
@volth Checking the [PRs you have made to nixpkgs](https://github.com/nixos/nixpkgs/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Avolth) it looks to me like you are getting a mix 2(i) and 2(ii). Sometimes the upstream maintainer merges your history for 2(i) and sometimes they rewrite the history for 2(ii). Guess it depends on the individual preference of the upstream maintainer?

Just to illustrate with a couple of examples...

- #27125: Your history has been rewritten by nixpkgs upstream. Case 2(ii). This will lead to tricky conflicts when you merge from master if (a) you have made further changes on your branch after that PR or (b) somebody else as made further changes upstream or (c) both. Git won't be able to help in this situation because it can't see the relationships between those changes. You will need to read through the whole diff and work out what to do yourself.
- #26980: Your history has been merged by nixpkgs upstream. Case 2(i). You can continue to work on this code on your branch, and other people can make independent changes upstream, and Git will take care of this nicely: the changes will be merged automatically except where there is a direct conflict between the new changes on the branches.

So in my mental model you are being given a portion of tech debt every time somebody merges your changes without taking your history and this will create work in cases there multiple people are working on the same code during the time that it takes to loop changes through the master branch and back to you.

**Comment by volth** [comment]
Yes, when they alter my commits it causes some conflicts. But PR's are usually small changes and their lifetime is limited (they either got accepted or stalled thus became my private patches).
So they have no time to have "history" which could be important nor have I an intention to work in the PR branch, it has limited scope to add one feature or to fix one problem (or a small set of related ones).

It is annoying is when PRs accepted after a month or two of silence, especially in altered form, then it requires manual backporting and perhaps changes in other (private) code which relies on what was in the PR branch initially.

**Comment by lukego** [comment]
@volth Thanks again for sharing your experience. Sounds like you have a model that works fine about 80% of the time and you are rolling up your sleeves and dealing with the other 20%.

I am not sure if it would work for me though. I would like to collaborate with other people on my downstream branch and if I am integrating other people's changes then I will expect more conflicts (because more changes) that are harder to resolve (because I'm not the one who made the original changes on either branch.)

I also think this would have blown up in my face a bit on my most recent attempt to contribute to nixpkgs. I have an ongoing effort to make Pharo 6 work well in nixpkgs (#26924) before that has landed somebody else is already making semi-related changes in the same part of the code base. I don't think I would be able to effectively handle situations like this without the git history.

Just now it seems like the best course of action for me would be to politely insist that my contributions are never rebased/squashed, because the history is a part of the work and it is important to me and anybody else who has already merged my branch, and if that is not acceptable then I could fall back to mostly just doing my own thing and only shipping things upstream once they are mature (which creates the risk of duplicated effort e.g. if somebody else also wants pharo 6 support and hacks that themself instead of finding and merging my branch.)

**Comment by domenkozar** [comment]
I'd say that the path depends on the amount of changes needed to be upstream. So far I got away using (3) for non-upstreamable changes with (2ii) for the upstream-able changes (I'm very biased here since I have commit access).

Key point in deciding is that small, standalone PRs get merged fast to nixpkgs as they are also easy to isloate. We had lots of problem with people syncing up with nixpkgs and breaking things, as noone wants to dive into the huge chuck of code changes.

I realize that for Pharo PR this is not helpful, as the amount of changes is non trivial. What really helps is splitting off anything that can be done without a bump and then all changes that are required for a bump in separate PR.

For things that I do maintain a fork - for example Hydra, I sync my branch on top of X hydra commit and merge in my pull requests. That turned out to work ok-ish.

**Comment by FRidh** [comment]
> I am looking for a solution that allows me to collaborate with other people "downstream." It needs to be possible for other people to contribute to our tree and help to maintain it, much like the way the upstream nixpkgs master branch is maintained (**except that downstream we will be making changes specifically to support one application.**)

Whole of Nixpkgs is big, and if you're working on supporting an application then I think most of the commits that happen in Nixpkgs are just noise. For clarity of revision history as well as what code is application-specific and what not, I suggest using an overlay. If you eventually want to upstream a change, then you can copy and paste it and create a commit in a Nixpkgs branch. As you can then remove it from your overlay, you can include a link to the Nixpkgs commit. That way your history remains clear.

**Comment by lukego** [comment]
Thanks everybody for the feedback. It's very helpful. I need to reflect a bit.

Basically it seems like I will have some subset of these repos:

1. My own application code, all by itself.
2. My overlays to nixpkgs, separate from the application and from nixpkgs repos.
3. My nixpkgs fork, providing the basis for the overlay.

I have to decide which repos I really need, which code will go into each one, how closely they will be synced with related forks, and how this whole picture will impact my workflow. Separating things can avoid git-related problems (like conflicts) but I have to think about losing git-related benefits too (like bisecting to troubleshoot.)

I'll let you know what I come up with :). More food for thought would be welcome still...

**Comment by lukego** [comment]
Closing to avoid clutter but more thoughts welcome if anybody else happens upon this...

**Comment by lukego** [comment]
I have moved my development from a nixpkgs fork to a [private overlay repository](https://github.com/studio/studio/tree/master/nixpkgs) now. This makes my life easier because I only need to worry about my own use cases. I would prefer to be cooperating with the upstream repo but the workflows that I have found so far have not been that comfortable.

I feel like nixpkgs is mostly setup for people working on the master branch and also somewhat optimized for people who have commit access. I'm a downstream person who wants to stay at a safe distance from the bleeding edge and to avoid doing too much porting/rebasing busy-work.

**Comment by michaelpj** [comment]
Just a thought: I'd be interested to see discussion like this on the mailing list. Not everybody subscribes to the issues - I only found this by accident.

**Comment by lukego** [comment]
@michaelpj There's a mailing list? :-) I only read Github nowadays...

**Comment by domenkozar** [comment]
https://groups.google.com/forum/#!forum/nix-devel
