### ISSUE TITLE
NixOS 23.11: Gnome Session Crash

### ISSUE THREAD

**Issue by danielslee** [NixOS/nixpkgs#273148]
### Describe the bug
After upgrading to nixos 23.11, I'm no longer able to start an X11 gnome session. It crashes with the "Oh no! Something has gone wrong" error. Starting a Wayland session works fine.

### Steps To Reproduce
1. Install nixos 23.11.
2. When logging in choose "Gnome on Xorg"

### Expected behavior
Gnome on Xorg should work without any issues just like it does on nixos 23.05.

### Screenshots
I couldn't grab a screenshot. All I can see is the "oh no" error.

### Additional context
I use an NVIDIA graphics card (GTX 3090).

I managed to grab the following from journalctl: [journalctl.txt](https://github.com/NixOS/nixpkgs/files/13624491/journalctl.txt)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.65, NixOS, 23.11 (Tapir), 23.11.20231207.b4372c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
(I use flakes so I imagine that the "channels" bit above doesn't matter)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by danielslee** [comment]
Looks like this issue may not be unique to NixOS: https://discussion.fedoraproject.org/t/second-monitor-crashes-gnome-on-x11/84395

I use a tiled monitor so it may be treated as two monitors.

**Comment by danielslee** [comment]
Looks like it could be this issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7120

**Comment by danielslee** [comment]
I was able to fix this by adding the patch as an overlay:

```nix
  nixpkgs.overlays = [
    (final: prev: {
      gnome = prev.gnome.overrideScope' (gfinal: gprev: {
        mutter = prev.gnome.mutter.overrideAttrs
          (old: { patches = old.patches or [ ] ++ [ ./mutter-patch.patch ]; });
      });
    })
  ];
```

mutter-patch.patch:
```patch
diff --git a/src/backends/x11/meta-monitor-manager-xrandr.c b/src/backends/x11/meta-monitor-manager-xrandr.c
index 128a34b9f..97ba112e8 100644
--- a/src/backends/x11/meta-monitor-manager-xrandr.c
+++ b/src/backends/x11/meta-monitor-manager-xrandr.c
@@ -770,9 +770,11 @@ meta_monitor_manager_xrandr_tiled_monitor_added (MetaMonitorManager *manager,
       xrandr_monitor_info->outputs[i] = meta_output_get_id (output);
     }
 
+  mtk_x11_error_trap_push (manager_xrandr->xdisplay);
   XRRSetMonitor (manager_xrandr->xdisplay,
                  DefaultRootWindow (manager_xrandr->xdisplay),
                  xrandr_monitor_info);
+  mtk_x11_error_trap_pop (manager_xrandr->xdisplay);
   XRRFreeMonitors (xrandr_monitor_info);
 }
 
```

Looks like it is [included](https://gitlab.gnome.org/GNOME/mutter/-/commit/07e07040dfb4f515a68bf58250f22609d5d9c097) in 45.3 so once Nix updates to that version this should be no longer needed.

**Comment by futile** [comment]
I had a similar issue that was due to my cursor set (`phinger-cursors{-light}`) not having all required cursor variants. Got rid of it by symlinking all variants that adwaita-cursors has for my cursor set as well, see [here in my dotfiles](https://github.com/futile/nixos-config/blob/f9151f608f1288bb8f73bcc2458d3c65dbbeefa1/custom-packages/phinger-cursors-extended.nix) (also includes the error message that showed up in journalctl when crashing). Just leaving this here for others that run into a similar problem :)

**Comment by danielslee** [comment]
It works out of the box now that nixos-23.11 uses mutter 45.3!
