### ISSUE TITLE
Apparmor service fails to start after nixos-rebuild switch

### ISSUE THREAD

**Issue by LDprg** [NixOS/nixpkgs#273164]
### Describe the bug
Apparmour service doesn't reload correctly after a system switch.

### Steps To Reproduce
1. change anything in config with apparmor enabled
2. run nixos-rebuild switch
3. view error of apparmor service failing to restart

### Expected behavior
No error, apparmor starting as it should

### Additional context

Here my service log:
```
Dez 09 17:23:37 LD-Laptop systemd[1]: Starting Load AppArmor policies...
Dez 09 17:23:37 LD-Laptop systemd[1]: Finished Load AppArmor policies.
Dez 09 17:27:03 LD-Laptop systemd[1]: Reloading Load AppArmor policies...
Dez 09 17:27:03 LD-Laptop aa-remove-unknown[18667]: ERROR: Unable to read apparmorfs profiles file
Dez 09 17:27:03 LD-Laptop systemd[1]: apparmor.service: Control process exited, code=exited, status=1/FAILURE
Dez 09 17:27:03 LD-Laptop systemd[1]: Reload failed for Load AppArmor policies.
```

### Notify maintainers

@ju1m 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20231207.b4372c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/vdap779dm1xfpr35xvfb9a1yiqiw9n89-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SrEstegosaurio** [comment]
I'm encountering the exact same error here.

**Comment by chewblacka** [comment]
Same issue here

**Comment by amalgame21** [comment]
Same for the `aa-remove-unknown[12345]: ERROR: Unable to read apparmorfs profiles file` issues after `nixos-rebuild switch`.
However do a `systemctl restart apparmor.service` after that just fine.

**Comment by SrEstegosaurio** [comment]
Someone once told me that the state of AA in NixOS wasn't great. But I don't know first hand. Could be wrong.

I lack any knowledge at all to even figure out the root cause of the issue. :/

**Comment by LDprg** [comment]
AA seems to work fine in general. Just the service restart after a nixos-rebuild doesn't work1.

**Comment by presto8** [comment]
Tested just now on nixos-23.11. AppArmor service restarts without any issues after nixos-rebuild. I think this issue is resolved.

**Comment by chewblacka** [comment]
Reopening this issue as unresolved. Currently on 24.05.20240117.842d9d8 and this issue seems to be persisting:

     reloading the following units: apparmor.service, dbus.service
    Job for apparmor.service failed.
    See "systemctl status apparmor.service" and "journalctl -xeu apparmor.service" for details.

**Comment by presto8** [comment]
I did some more investigation on this. I one system with a custom apparmor profile and another system with no profiles. On the system I have with a custom apparmor profile, nixos-rebuild works fine. On the other system without any apparmor profiles, nixos-rebuild fails with the message in this bug report.

After nixos-rebuild, journalctl reports:

```
Jan 22 11:46:52 systemd[1]: Reloading Load AppArmor policies...
Jan 22 11:46:52 aa-remove-unknown[1567064]: ERROR: Unable to read apparmorfs profiles file
Jan 22 11:46:52 systemd[1]: apparmor.service: Control process exited, code=exited, status=1/FAILURE
Jan 22 11:46:52 systemd[1]: Reload failed for Load AppArmor policies.
```

In nixpkgs.git/nixos/modules/security/apparmor.nix:

```
          # Remove from the kernel any profile whose name is not    
          # one of the names within the content of the profiles in enabledPolicies    
          # (indirectly read from /etc/apparmor.d/*, without recursing into sub-directory).    
          # Note that this does not remove profiles dynamically generated by libvirt.    
          [ "${pkgs.apparmor-utils}/bin/aa-remove-unknown" ] ++
```        

I tried running "sudo aa-remove-unknown" from zsh:

```
❯ sudo aa-remove-unknown
ERROR: Unable to read apparmorfs profiles file
```

The error message matches what is in the system log. I think this may be related to the aa-remove-unknown step.

**Comment by presto8** [comment]
As a workaround, adding this to configuration.nix appears to work:

```
security.apparmor.policies.dummy.profile = ''
    /dummy {
    }
  '';
```

After this, the first nixos-rebuild switch will still cause the issue (because the profile is not installed yet). But on the second and subsequent nixos-rebuilds, there is no error message on my system.

Can someone else try it and see if it works on their system too? If so, it may help to figure out the proper solution.

**Comment by chewblacka** [comment]
> After this, the first nixos-rebuild switch will still cause the issue (because the profile is not installed yet). But on the second and subsequent nixos-rebuilds, there is no error message on my system.
> 
> Can someone else try it and see if it works on their system too? If so, it may help to figure out the proper solution.

I tried it and it actually rebuilds without error the first time too. Hopefully that helps you or someone else figure out a permanent fix! Many thanks.

**Comment by LDprg** [comment]
From my side the issue seems to be be fixed with the merged fixes. So I will close the issue.
