### ISSUE TITLE
No support for canon lasor printer. (CAPT Printer Driver for Linux)

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#27323]
I want to use LBP-3050 printer but there is no driver. 

~~I would love to create a package for it but don't know how to start.~~

~~While I am researching, if anyone can help, feel free to post any suggestion.~~

This is [link](http://support-asia.canon-asia.com/contents/ASIA/EN/0100459601.html) to printer driver.

~~The problem I try to solve / progress so far:
[ ] I don't understand the license, is direct fetching allowed?
[ ] There was no direct-link to use with `fetchurl`
[ ] I will create WIP PR when I have some progress~~

**Comment by regellosigkeitsaxiom** [comment]
AFAIK, you can do it without installing CAPT driver.
1. Download and extract driver
2. `cd ./Src`
3. `tar -xf cndrvcups-capt-2.71-1.tar.gz`
4. `./cndrvcups-capt-2.71/ppd/` will contain bunch of .ppd files. Often it is all you need to install a printer
5. Install printer via CUPS using file `CNCUPSLBP3050CAPTK.ppd`

As for download link, you can get link of downloaded file from browser. For me it is http://gdlp01.c-wss.com/gds/6/0100004596/05/linux-capt-drv-v271-uken.tar.gz and it works from several locations.
Fetching does not seem to be restricted by license, and wget works fine.

**Comment by wizzup** [comment]
Thank you but my printer just broke yesterday, :(

I will leave this issue opened for others to confirm your solution.

**Comment by wizzup** [comment]
If anyone still want to do this there are some example of compiling instruction I have found.

- [arch aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=capt-src)
- [some random github makefile](https://github.com/gkr09/Canon-CAPT/blob/master/Makefile)

**Comment by wizzup** [comment]
I am still trying to build the driver [here](https://github.com/wizzup/canon-capt) but have no success when the build is done without any error I will open the PR to fix this issue.

If anyone can help me please take a look.

**Comment by goatastronaut0212** [comment]
I don't know what about yours, but it seems like there is another community effort in reverse engineering these printers https://github.com/mounaiban/captdriver/wiki#supported-devices

I do test it recently via `canon-capt` already packaged in NixOS and it works quite great for me. Maybe you can try to test it? @wizzup

**Comment by goatastronaut0212** [comment]
Probably I will close this issue for now.
