### ISSUE TITLE
Can't update NixOS anymore. Request for precompiled webkitgtk - not possible to build on local machine.

### ISSUE THREAD

**Issue by SayantanRC** [NixOS/nixpkgs#273201]
I am unable to update my NixOS installation because all of a sudden it has started triggering a source build of webkitgtk. This is a very tedious task and my laptop does not have the memory capacity for the build to complete (32 GB RAM). It would be great if webkitgtk versions were available precompiled and not have to be built on the device.

### Steps To Reproduce

1. I have my flakes [here](https://github.com/SayantanRC/my-nix-flake).
2. I use the commands:
   ```
   nix flake update
   sudo nixos-rebuild switch --max-jobs 1 --flake .#asus_gnome
   ```
   The `--max-jobs` was suggested to me [here](https://discourse.nixos.org/t/i-cant-update-nixos-anymore-because-of-webkitgtk-manual-compilation/36661).

### Build log
1. When run from a graphical session, the process just crashes with the terminal.
   ![2023-12-10_01-27](https://github.com/NixOS/nixpkgs/assets/25128924/83417013-26ed-41c4-b27b-03b813611933)
2. When run from TTY, I get out of memory.
   ![PXL_20231209_210842057 MP~2](https://github.com/NixOS/nixpkgs/assets/25128924/573ffd34-c1f3-4f7e-98c3-cabffa49f717)

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[sayantan@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.12, NixOS, 23.05 (Stoat), 23.05.20231121.767986a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
See https://discourse.nixos.org/t/i-cant-update-nixos-anymore-because-of-webkitgtk-manual-compilation/36661/7
