### ISSUE TITLE
Window managers such as i3 cannot see gsettings schemas

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#273275]
Here I suggest that somewhere `XDG_DATA_DIRS` should be set such that `gsettings` works when invoked by top-level GUI session programs, such as window managers like i3.

Otherwise the commands for light/dark mode switching don't work.

---

I just upgraded NixOS 23.05 -> 23.11 and found that my i3 keybinding for switching the desktop-wide light/dark theme no longer works.

I had been using:

```sh
bindsym $mod+XF86AudioLowerVolume exec --no-startup-id xfconf-query --channel xsettings --property /Net/ThemeName --set Adwaita-dark
bindsym $mod+XF86AudioRaiseVolume exec --no-startup-id "xfconf-query --channel xsettings --property /Net/ThemeName --set Adwaita && gsettings set org.gnome.desktop.interface color-scheme default"
```

This works for most apps but after the upgrade no longer has any effect on `gnome-terminal`, supposedly because the Adwaita theme currently does not affect GTK4 applications, see https://wiki.archlinux.org/title/Dark_mode_switching#gsettings.

The fix is to switch to this:

```sh
# Bright/dark theme switcher
# Because the Adwaita theme currently does not affect GTK4 applications (such as currently `gnome-terminal`),
# also use `gsettings`, see https://wiki.archlinux.org/title/Dark_mode_switching#gsettings.
# `gsettings` requires `XDG_DATA_DIRS` to contain the `gsettings-desktop-schemas` path
# that contains `org.gnome.desktop.interface`, otherwise it will error with `No schemas installed`.
bindsym $mod+XF86AudioLowerVolume exec --no-startup-id xfconf-query --channel xsettings --property /Net/ThemeName --set Adwaita-dark && gsettings set org.gnome.desktop.interface color-scheme prefer-dark
bindsym $mod+XF86AudioRaiseVolume exec --no-startup-id xfconf-query --channel xsettings --property /Net/ThemeName --set Adwaita && gsettings set org.gnome.desktop.interface color-scheme default
```

But the added invocation

```sh
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
```

only works when `gsettings` can find the schema. In `gnome-terminal`, that is automatically the case, but in normal i3 (and e.g. plain `urxvt`), `gsettings list-schemas` errors with:

```
No schemas installed
```

because `$XDG_DATA_DIRS` lacks the entry constructed from `gsettings-desktop-schemas` which has the schema for `org.gnome.desktop.interface`.

My workaround is this in `/etc/nixos/configuration.nix`:

```nix
  environment.sessionVariables = {
    # Necessary for e.g. `i3` config `exec` commands to use `gsettings`,
    # e.g. to bind keys for switching light/dark mode.
    XDG_DATA_DIRS =
      let
        schema = pkgs.gsettings-desktop-schemas;
        datadir = "${schema}/share/gsettings-schemas/${schema.name}";
      in [ datadir ];
  };
```

Now even in i3's process and urxvt, we have:

```
$ echo $XDG_DATA_DIRS
/nix/store/n1qj6nna92xldmqxdqfwj8b4naxiznaj-gsettings-desktop-schemas-45.0/share/gsettings-schemas/gsettings-desktop-schemas-45.0:...
```

Btw, I use the `xfce+i3` session:

```nix
  services.xserver.displayManager.defaultSession = "xfce+i3";
  services.xserver.windowManager.i3 = {
    enable = true;
    extraPackages = with pkgs; [
      dmenu
      i3status
      i3lock
    ];    
  };

  # Without this `gnome-terminal` errors with:
  #     Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Unit gnome-terminal-server.service not found.
  programs.gnome-terminal.enable = true;
```

---

Should my fix with `sessionVariables` be incorporated into NixOS somehow?

Perhaps in the module of `programs.gnome-terminal.enable` or the `defaultSession = "xfce+i3";`?

CC @jtojnar as somebody who seems to know about `gsettings`.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
This is expected, see https://github.com/NixOS/nixpkgs/issues/33277.
