### ISSUE TITLE
Update request: minetest 5.7.0 → 5.8.0

### ISSUE THREAD

**Issue by jilinoleg** [NixOS/nixpkgs#273207]
- Package name: minetest (and minetestserver)
- Latest released version: 5.8.0

- Current version on the unstable channel: 5.7.0
- Current version on the stable/release channel: 5.7.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@PyroLagus @fpletz @fgaz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jilinoleg** [comment]
I am able to build that version and current dev version using overrides, but they seemingly moved control library irrlitch (their engine) uses to libXi (xinput2), that is also the same one that is needed for mobile controls, so it either throws errors that it needs libXi or builds in touchscreen mode if I override dependencies to include libXi package.

My educated guess is that it needs changes in postPatch of [irrlichtmt](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/irrlichtmt) dependency while also changing dependencies to always include libXi

**Comment by fgaz** [comment]
I'm working on it. I fixed the problem and I simplified the whole package. I'll open a pr shortly.
