### ISSUE TITLE
Package request: zsa keymapp

### ISSUE THREAD

**Issue by LVGrinder** [NixOS/nixpkgs#273221]
**Project description**

Keymapping software for ZSA products

**Metadata**

* homepage URL: https://www.zsa.io/flash/#flash-keymapp
* source URL: https://www.zsa.io/flash/#flash-keymapp
* license: mit, bsd, gpl2+ , ...
* platforms: Ubuntu 20.04+

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
there is already a request for it open: #266113
Feel free to drop a PR review: https://github.com/NixOS/nixpkgs/pull/268299
