### ISSUE TITLE
Some KDE apps are broken on nixos-unstable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#27334]
## Issue description

Induced by this change https://github.com/NixOS/nixpkgs/pull/26336
There are probably more broken apps

### Steps to reproduce

If that matters, I run them under i3wm, not under plasma5. They were working fine in the past

Before each step: `rm ~/.cache/ksycoca5*`

**Launching Filelight**
```
Unable to locate the Filelight Part.
Please make sure Filelight was correctly installed.
```
_It ignores KDE_INSTALL_KSERVICES5DIR cmake variable during the build and looks in XDG_DATA_DIRS instead._

**Clicking on folder in Gwenview or launching k3b**
```
Unable to create io-slave. Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files
```
_kinit.bin is not propagated._

**Spectacle in Export Image -> More Online Services shows**
```
No KIPI plugins available
```
_See Filelight issue. Additionally KDE_INSTALL_KSERVICETYPES5DIR cmake variable ignored and XDG_DATA_DIRS used. Plus libkipi is not propagated._

**No Plugins menu in Gwenview**

_See Spectacle issue. Additionally KDE_INSTALL_KXMLGUI5DIR cmake variable ignored and XDG_DATA_DIRS used._

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
**17.09pre111447.a7c8f5e419 (Hummingbird)**
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by Radvendii** [comment]
I'm not sure if this is the same issue, but for me Konsole launches fine, but then when I try to open a URL from it, I get the error you were getting

    Unable to create io-slave. Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files

**Comment by gnidorah** [comment]
@Radvendii as a workaround try to add kdeFrameworks.kinit package. This fixed Konsole and Gwenview at my side.
