### ISSUE TITLE
Package QtWebKit-NG

### ISSUE THREAD

**Issue by calvertvl** [NixOS/nixpkgs#27337]
## Issue description

QtWebKit-NG is not part of nixpkgs.

The version of QtWebKit bundled in the source distro for Qt is outdated relative to WebKit upstream, and is not receiving security updates (nor distributed in binary form anymore).

The QtWebKit-NG project is updating this to use the upstream WebKit, based on WebKitGTK.

This library is supposed to be a drop-in replacement for the existing QtWebKit; including it in the library path prior to Qt should cause it to be used preferentially, but it would be best to stop building QtWebKit as part of `qtbase` so that any dependent packages would fail and could have the QtWebKit-NG dependency added.

Here are some links that should help when packaging:
* the latest release (5.212.0 alpha 2) at annulen/webkit@6d0ad27b6bc4209fb8d8cee2692dc0c6a5462051
* [Releases list](https://github.com/annulen/webkit/releases)
* [Linux build dependencies and instructions](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux)
* [End-user snapshot repo, as the dev repo has extra stuff](http://code.qt.io/cgit/qt/qtwebkit.git/)
* [Current tracking branch for snapshots](http://code.qt.io/cgit/qt/qtwebkit.git/log/?h=5.212)

### Known dependent packages

* qutebrowser

## Technical details

* System: 17.09.git.412da32 (Hummingbird)
    * Also applies to any system for which `qtbase` is available through nixpkgs.
* Nix version: 1.11.11
* Nixpkgs version: 17.09.git.412da32

**Comment by veprbl** [comment]
Was fixed in b785d4813e5d0f428b9563b3cea7cc6953fc24db
qutebrowser moved to QtWebEngine since then
