### ISSUE TITLE
Tracking Linux stable ext4 data corruption bug in kenel < 6.1.66

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#273375]
Apparently upstream stable kernels 6.1.65 (NixOS 23.11 default) and .64 have a cherry-picking bug that can create data corruption on ext4 

* https://news.ycombinator.com/item?id=38589389
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057843

Probably NixOS should update to 6.1.66 (released 2 days ago) as soon as possible

**Comment by nh2** [comment]
Looks like this was already dealth with:

* https://github.com/NixOS/nixpkgs/pull/272872
* https://github.com/NixOS/nixpkgs/commit/591c57a696c9b0cc1fb3e4f81e74bc85b228b6ce#comments

Currently building on Hydra: https://nixpk.gs/pr-tracker.html?pr=272872

**Comment by stelcodes** [comment]
I believe the realtime kernel from the `6.1` branch still contain this bug?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/linux-rt-6.1.nix
