### ISSUE TITLE
SageMath is broken and outdated

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#27335]
## Issue description
Since Sage is huge and complicated, I figured I would make this issue to collaboratively track progress and share branches. One big issue is that Sage 7 [no longer supports `make install`](https://github.com/sagemath/sage/blob/ffb59227f6b80c4d938b34d2e3493eeb429323d1/Makefile#L132), instead they use some [custom build system](https://github.com/sagemath/binary-pkg) with scant documentation 😞.

[This branch](https://github.com/siddharthist/nixpkgs/blob/e010e12273b0e0a578346c71bc125b1ce2fe035c/pkgs/applications/science/math/sage/default.nix) has the correct SHA256 for Sage 7.6 and updates a patch file. It currently fails when Sage tries to build `xz`.

Some nice things to do for the future:
 - [ ] Use ATLAS from nixpkgs (see [variable `SAGE_ATLAS_LIB`](http://doc.sagemath.org/html/en/installation/source.html#environment-variables))
 - [ ] Create NixOS service for running a [Sage notebook server](https://github.com/sagemathinc/cocalc)

cc: @volhovM @listx @cmfwyp @FlorentBecker

**Comment by FlorentBecker** [comment]
thanks for picking this up

**Comment by 7c6f434c** [comment]
As a miserable loser who has failed to update Sage in the past, I hope you succeed… 

My attempt hit the following wall. It is unbearably slow to let Sage build everything, but when I had convinced it to use the system versions of majority of dependencies it began to complain cryptically about their interaction in some case.

**Comment by siddharthist** [comment]
@7c6f434c Can you elaborate? Do you have a branch that has that work? 

Also, to be clear: I probably don't have the skills or time to upgrade Sage by myself, I was hoping that if we shared our knowledge and de-duplicated efforts we might be able to get closer together 😄

**Comment by 7c6f434c** [comment]
I think it was 6-dot-something; it required a metric ton of adding options to the packages in NixPkgs (I have pushed that all to master long ago), and the Sage tricks are most likely too version-specific. It was long enough ago that I have since abandoned and lost the changes.

**Comment by Eisfreak7** [comment]
In case anybody in here is still waiting for this: I got sage to compile and run. I'm currently trying to minimize the dependencies and check that everything is working correctly (there is one doctest failure, but it was mentioned multiple times in the mailing list and apperas to be harmles -- just a timeout). I'll probably make a PR in the next couple of days.
