### ISSUE TITLE
Build failure: pkgsCross.aarch64-darwin.stdenv

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [NixOS/nixpkgs#273442]
### Steps To Reproduce

1. build *pkgsCross.aarch64-darwin.stdenv*

### Build log

```console
user@macos-sonoma ~ % nix-build '<nixpkgs>' -A pkgsCross.aarch64-darwin.stdenv -I nixpkgs=channel:nixpkgs-unstable --show-trace
error:
       … while calling the 'derivationStrict' builtin

         at /derivation-internal.nix:9:12:

            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'stdenv-darwin'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:93:14

       … while evaluating attribute 'defaultNativeBuildInputs' of derivation 'stdenv-darwin'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:126:14:

          125|
          126|       inherit initialPath shell
             |              ^
          127|         defaultNativeBuildInputs defaultBuildInputs;

       … while evaluating derivation 'aarch64-apple-darwin-clang-wrapper-16.0.6'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'depsTargetTargetPropagated' of derivation 'aarch64-apple-darwin-clang-wrapper-16.0.6'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:403:7:

          402|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
          403|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;
             |       ^
          404|

       … while evaluating derivation 'libcxx-aarch64-apple-darwin-16.0.6'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'stdenv' of derivation 'libcxx-aarch64-apple-darwin-16.0.6'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:377:14:

          376|       args = attrs.args or ["-e" (attrs.builder or ./default-builder.sh)];
          377|       inherit stdenv;
             |              ^
          378|

       … while evaluating derivation 'stdenv-darwin'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:93:14

       … while evaluating attribute 'defaultNativeBuildInputs' of derivation 'stdenv-darwin'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:126:14:

          125|
          126|       inherit initialPath shell
             |              ^
          127|         defaultNativeBuildInputs defaultBuildInputs;

       … while evaluating derivation 'aarch64-apple-darwin-clang-wrapper-16.0.6'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'depsTargetTargetPropagated' of derivation 'aarch64-apple-darwin-clang-wrapper-16.0.6'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:403:7:

          402|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
          403|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;
             |       ^
          404|

       … while evaluating derivation 'compiler-rt-libc-aarch64-apple-darwin-16.0.6'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'stdenv' of derivation 'compiler-rt-libc-aarch64-apple-darwin-16.0.6'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/make-derivation.nix:377:14:

          376|       args = attrs.args or ["-e" (attrs.builder or ./default-builder.sh)];
          377|       inherit stdenv;
             |              ^
          378|

       … while evaluating derivation 'stdenv-darwin'
         whose name attribute is located at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:93:14

       … while evaluating attribute 'defaultNativeBuildInputs' of derivation 'stdenv-darwin'

         at /nix/store/js53b3xz6z97jv87knhw1mdgdc4p845z-source/pkgs/stdenv/generic/default.nix:126:14:

          125|
          126|       inherit initialPath shell
             |              ^
          127|         defaultNativeBuildInputs defaultBuildInputs;

       error: infinite recursion encountered
```

### Additional context

I've tried building aarch64-darwin bash on x86_64-darwin with `nix-build '<nixpkgs>' -A pkgsCross.aarch64-darwin.stdenv -I nixpkgs=channel:${CHANNEL}` and found the following:

- The build works as expected when `CHANNEL=nixpkgs-22.11-darwin`.
- It builds from source when `CHANNEL=nixpkgs-23.05-darwin`.
- Fails with "infinite recursion encountered" when `CHANNEL=nixpkgs-23.11-darwin` or `CHANNEL=nixpkgs-unstable`.

This breaks everything cross-building from x86_64-darwin to aarch64-darwin.

### Notify maintainers

@Artturin
@Ericson2314
@RaitoBezarius
@alyssais
@amjoseph-nixpkgs
@dtzWill
@lovek323
@primeos
@reckenrode
@rrbutani
@sternenseemann
@szlend
@toonn
@trofi
@vcunat

### Metadata

```console
user@macos-sonoma ~ % nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Running `$ nix-instantiate . -A pkgsCross.aarch64-darwin.stdenv --argstr system x86_64-darwin` on `linux` confirms the infinite recursion.

Bisecting:

```
$ git bisect start origin/master origin/nixpkgs-23.05-darwin
$ git bisect run nix-instantiate . -A pkgsCross.aarch64-darwin.stdenv --argstr system x86_64-darwin

commit bcbdb800cf7659d6ff36ac114121a056fe8c9656
Date:   Sun Jun 11 13:14:08 2023 -0400

    llvmPackages: 11 -> 16 on Darwin

 pkgs/top-level/all-packages.nix | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

bcbdb800cf7659d6ff36ac114121a056fe8c9656 sounds very plausible.

**Comment by reckenrode** [comment]
The fix is probably in https://github.com/NixOS/nixpkgs/pull/256590, but I need to rebase it. I plan on looking at it more later this week.

**Comment by lolbinarycat** [comment]
this also happens when trying to cross-compile from linux to x86_64-darwin

**Comment by reckenrode** [comment]
Unfortunately, cross-compilation from Linux to Darwin is unlikely to be supported anytime soon. There are some challenges with tooling that would need to be solved (beyond just what needs fixing in nixpkgs).

**Comment by lolbinarycat** [comment]
maybe a warning should be added to `pkgsCross.*-darwin` then instead of letting it infinity recurse.

**Comment by soywod** [comment]
I have the same issue cross compiling `aarch64-darwin` but from `x86_64-darwin`: https://github.com/NixOS/nixpkgs/issues/177557

**Comment by reckenrode** [comment]
I’m currently working on updating cctools and ld64, which should address part of the tooling issue on Linux. These updated packages are building from Apple’s upstream source drop with patches to replace private and platform-specific API usage. After that, I need to work on the SDK update/refactor because it’s likely that x86_64-darwin will need an updated SDK (10.14).

If someone wants to take my draft PR and fix the compiler-rt issue, they’re welcome to do that. My bandwidth is limited, and updating the SDK and tooling is a higher priority for me. There were already packages in the bootstrap needing a newer SDK to build, but cctools and ld64 are the first ones to require it at runtime.

However, before I start working on the SDK stuff, I can take a look at my cross-compilation to see if it’s an easy fix to get it building again. One caveat is it was mentioned in https://github.com/NixOS/nixpkgs/pull/302481 that the LLVM packages are being reworked to build from common derivations, the my cross PR may have to wait on that work to land.

**Comment by reckenrode** [comment]
This should be fixed by https://github.com/NixOS/nixpkgs/pull/346043.

**Comment by aviallon** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/346043
