### ISSUE TITLE
Let cabal builder set --enable-executable-profiling

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#2734]
When we're building Haskell packages with profiling and `isLibrary = true;`, the `--enable-library-profiling` is set and it's all fine and dandy but it seems that there is no handling if we have `isExecutable = true` and are building with profiling.

Seems like extra clauses should be added to https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/cabal/default.nix#L68

Currently I have to pass in `configureFlags = [ "--enable-executable-profiling" ];` manually. I also had to pass `-rtsopts` GHC flag for it to work.

**Comment by aycanirican** [comment]
+1 for this.

**Comment by peti** [comment]
Commit 6229ec9 is in `staging`.
