### ISSUE TITLE
Update request: TuxGuitar 1.5.5 → 1.6.0

### ISSUE THREAD

**Issue by EthanHarp** [NixOS/nixpkgs#273408]
- Package name: TuxGuitar
- Latest released version: 1.6.0

- Current version on the unstable channel: 1.5.5
- Current version on the stable/release channel: 1.5.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ardumont 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by EthanHarp** [comment]
It appears that the SourceHut version is no longer maintained. Looks like it was forked and development continues at https://github.com/helge17/tuxguitar. Also the homepage link on search.nixos.org is broken.

**Comment by luzpaz** [comment]
Following up on @EthanHarp's post, here's a link to a TuxGuitar sourceforge [discussion](https://sourceforge.net/p/tuxguitar/discussion/522984/thread/0a8c900ddd/?limit=25#e036) where there is confirmation the project has been forked and migrated to Github.

> Julian seems to be no longer active in this repository and did not respond to our [request](https://sourceforge.net/p/tuxguitar/discussion/522984/thread/02743a8637/) a few months ago.
>
>Since the new repository https://github.com/helge17/tuxguitar has made a lot of progress and the code is now in a quite consistent state, we decided to release a new "official" version of TuxGuitar: 1.6.0.

**Comment by luzpaz** [comment]
soft bump

**Comment by SuperSandro2000** [comment]
Please test #329133
