### ISSUE TITLE
Strange aws-sdk-cpp rpath-fu leads to huge Nix closures

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#27348]
This is primarily for @edolstra, unless anyone else can figure out what's going on.

A few months ago, [these lines](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/aws-sdk-cpp/default.nix#L54-L56) were added to the `aws-sdk-cpp` expression:

```nix
{
  NIX_LDFLAGS = lib.concatStringsSep " " (
    (map (pkg: "-rpath ${lib.getOutput "lib" pkg}/lib"))
    [ curl openssl zlib stdenv.cc.cc ]);
}
```

That means that every generated library for `aws-sdk-cpp` gets an rpath entry pointing at `stdenv.cc.cc`, which is `gcc` on Linux and `clang` on Darwin. This means that when the Nix (the package manager, not the generic notion) build depends on `aws-sdk-cpp`, its closure now includes `clang` on Darwin, which brings in LLVM and brings the Nix install tarball up to 170MB.

@edolstra do you recall what you were aiming for with that rpath thingy there? I want to take it out but I don't want to change stuff I don't understand.

I'm also not sure why I'm not seeing this on official Nix builds on Hydra, since they seem to be pinned to 17.03 which had the change.

**Comment by domenkozar** [comment]
On linux:

```
$ du -shc $(nix-store -qR /nix/store/7nmq3ywfwc0zphq492ibnqal0m3rfxpl-aws-sdk-cpp-1.0.153)
22M     /nix/store/i95x934ljf3ginapkmqs2rrik472zlnx-glibc-2.25
112K    /nix/store/069ir6yxjpzlvh0wlcl0g7zsgygsafng-zlib-1.2.11
3.4M    /nix/store/c9fg9z6a74n6f3g94q5d3k704b5wfm6x-openssl-1.0.2l
4.8M    /nix/store/iycp77v1k10f9f8q3mc85b1ndsi8lw2w-gcc-5.4.0-lib
196K    /nix/store/g16imcpayjdsil2vv6rv7pw45fpn9b4r-nghttp2-1.20.0-lib
220K    /nix/store/ycprbb2gv9kr5rzgl3v8dy9dxad840dv-libssh2-1.8.0
540K    /nix/store/yb75z74k2c0nrf78hfwcy3cah0pfvq6n-curl-7.54.1
155M    /nix/store/7nmq3ywfwc0zphq492ibnqal0m3rfxpl-aws-sdk-cpp-1.0.153
186M    total
```

**Comment by copumpkin** [comment]
Oh, I guess the `lib` output of `gcc` is a lot smaller than `clang`, which might not even have split outputs right now. I still don't know why the manual rpath-ing is necessary though?

**Comment by dtzWill** [comment]
Is this still an issue?

**Comment by abathur** [comment]
Closing since it looks like the code in question was unceremoniously removed in #33473 and hasn't returned. Happy to reopen if I'm misinterpreting :)
