### ISSUE TITLE
nixos/guix: GC: allocating JIT code buffer failed: Operation not permitted

### ISSUE THREAD

**Issue by MaxSilvesterQWE** [NixOS/nixpkgs#273544]
### Describe the bug
The guix-gc.service doesn't work.

### Steps To Reproduce
1. set `services.guix.gc.enable = true` in `configuration.nix`
2. `nixos-rebuild switch`
3. `systemctl restart guix-gc.service`
4. `systemctl status guix-gc.service

```
systemd[1]: Starting Guix garbage collection...
guix-gc-start[1013]: allocating JIT code buffer failed: Operation not permitted
guix-gc-start[1013]: jit.c:5896: fatal: assertion failed
guix-gc-start[997]: /nix/store/99z06ws5wp13460i2h97q923670d3w0n-unit-script-guix-gc-start/bin/guix-gc-start: line 3:  1013 Aborted                 (core dumped) /nix/store/sclr9cqx7q4dkkc79gg5id5jvfayxs9v-guix-1.4.0/bin/guix gc '--delete-generations=30d'
systemd[1]: guix-gc.service: Main process exited, code=exited, status=134/n/a
systemd[1]: guix-gc.service: Failed with result 'exit-code'.
```

### Additional context
I think this is because the JIT needs write and execute permissions but the service disallows it with `MemoryDenyWriteExecute=true`. I changed it to `MemoryDenyWriteExecute=false` and it works now.

### Expected behavior
The guix-gc service should run normally and collect the garbage.

### Notify maintainers
@foo-dogsquared

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.65, NixOS, 24.05 (Uakari), 24.05pre556224.2c7f3c0fb7c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(maxsilvester): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by foo-dogsquared** [comment]
I can reproduce the error and so does the fix. Thank you for reporting!
