### ISSUE TITLE
Build failure: llm-ls for aarch64-darwin

### ISSUE THREAD

**Issue by JackSullivan** [NixOS/nixpkgs#273596]
`darwin` is currently in `badPlatforms` for `llm-ls`, but it does build fine on `aarch64-darwin` outside of nixpkgs.

### Steps To Reproduce

On `aarch64-darwin` `nix build nixpkgs/nixos-23.11#llm-ls` fails to build with 'not available on the requested host platform' (This is expected). When I remove `darwin` from `badPlatforms` it says it can't find the `Security` framework (I believe needed by the rust package `security-framework-sys:2.9.1`). 

When I alter the llm-ls build script to add `buildInputs = lib.optional stdenv.isDarwin [ darwin.apple_sdk.frameworks.Security ];`, it fails with a bunch of `Undefined symbols for architecture arm64` errors (see full log below). However, If I just clone the relevant checkpoint of the `llm-ls` repo and run `nix run nixpkgs/nixos-23.11#cargo -- build`, it builds and runs fine.

### Build log

[Build Log Gist](https://gist.github.com/JackSullivan/fc92981e3f9da8e0d1bcad24b00e7aa0)

### Notify maintainers

@jfvillablanca 

### Metadata

```console
λ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/22dzjqjrxlhl0ba23f8f66w51hbhgz14-nix-info
  /nix/store/7mc6vch4s76ynwihxck33gy5pz4fpq13-DarwinTools-1
copying path '/nix/store/7mc6vch4s76ynwihxck33gy5pz4fpq13-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/22dzjqjrxlhl0ba23f8f66w51hbhgz14-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/store/mpsjbqbyzcdjbgf2phj0yik4nk8dp1xv-mbz4hixfgxq5b6vc0k3pp2iglcd4c353-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jfvillablanca** [comment]
would you be willing to make a PR to unbreak `llm-ls` for `darwin`? i don't have a mac to test out your suggestion.

**Comment by JackSullivan** [comment]
I'm happy to make the PR for `llm-ls` on `darwin` and to do the testing for it, though I don't have the knowledge to debug the problems in the log I posted, so I'll need some help

**Comment by JackSullivan** [comment]
Is this issue potentially related to #19098? It appears to be of the same form.
