### ISSUE TITLE
Build failure: gnomeExtensions.flypie

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#273655]
FlyPie GNOME Extension does not appear as package despite it is inside [extensions.json](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/desktops/gnome/extensions/extensions.json). It is not reported in [Nix Search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=flypie) too. Is it due to build failure?

**Comment by jackwilsdon** [comment]
Looks like FlyPie was disabled due to #118612:

https://github.com/NixOS/nixpkgs/blob/b0e130d3daacc9dc69588a57a09e37ffa5cf6a06/pkgs/desktops/gnome/extensions/extensionRenames.nix#L113-L114

The files containing unicode characters in their names were removed in https://github.com/Schneegans/Fly-Pie/commit/66e43312496f50a3279ff812cf70d8d078db8369 anyway (and #118612 was fixed in #176253), and from a quick test locally it seems like `gnomePackages.flypie` builds fine now.

**Comment by D3vil0p3r** [comment]
So, can it be enabled again?

**Comment by jackwilsdon** [comment]
Just rebuilding my machine with it enabled now to try it out - if it works I'll open a PR shortly :+1:

**Comment by jackwilsdon** [comment]
Tested and looks to work fine :+1:

**Comment by D3vil0p3r** [comment]
Thank you for merging the PR. On which nix version repo it is available? I'm searching it by [Nix Search](https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=flypie) but I cannot find it.

**Comment by NickCao** [comment]
It needs some time to reach the channels, you can track its progress on https://nixpk.gs/pr-tracker.html?pr=274080

**Comment by D3vil0p3r** [comment]
> It needs some time to reach the channels, you can track its progress on https://nixpk.gs/pr-tracker.html?pr=274080

Thanks. It will be available only for unstable or also for 23.11?

**Comment by NickCao** [comment]
> Thanks. It will be available only for unstable or also for 23.11?

Backported in https://nixpk.gs/pr-tracker.html?pr=274517

**Comment by NickCao** [comment]
> Thanks @NickCao I see in both of trackers the pkg should be available but still it cannot be installed and in nixsearch is not present.

Maybe a typo? I can see it in search: https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=gnomeExtensions.fly-pie

**Comment by D3vil0p3r** [comment]
Thanks. I was typing `flypie`.

**Comment by D3vil0p3r** [comment]
When packages are installed by home-manager by using flakes, they follow a different process? Because I wrote my home-manager module like:
```nix
{ pkgs, home-manager, username, ... }:
let
  gnomeExtensionsList = with pkgs.gnomeExtensions; [
	  appindicator
	  arcmenu
    dash-to-dock
    desktop-icons-ng-ding
    fly-pie
    hide-activities-button
    pop-shell
    top-bar-organizer
    vitals
  ];

  fontList = with pkgs; [
    (nerdfonts.override { fonts = [ "JetBrainsMono" "NerdFontsSymbolsOnly" ]; })
  ];
in
{
  home-manager.users.${username} = { pkgs, ...}: {
    home.packages = gnomeExtensionsList ++ fontList;
...
```
but by running `sudo nixos-rebuild switch --flake '.#gnome' --impure` I get:
```
error: undefined variable 'fly-pie'
```
I also run:
```
sudo nix-channel --update
```
but after running the command above, I get the same error.

**Comment by D3vil0p3r** [comment]
@NickCao I note that if I install fly-pie by `nix-shell -p`, I can retrieve it. If I install it by flakes, I cannot. How can we make fly-pie available also by flakes?

In my flake configuration I'm using 23.11 repo version.

**Comment by NickCao** [comment]
Maybe you should run `nix flake update`.

**Comment by D3vil0p3r** [comment]
Yes. It solved the issue. Thank you.
