### ISSUE TITLE
Missing `man` page of `GNU parallel`

### ISSUE THREAD

**Issue by amalgame21** [NixOS/nixpkgs#273650]
Sorry I am so new to NixOS, maybe I just miss something.
`man` page is of great importance for such a program like `GNU parallel`.
`parallel --help` is not enough.
Please let me know if there are some methods to install manpage in a way that is specific to NixOS. 
Thank you so much!

### Describe the bug
```
$ man parallel
No manual entry for parallel
```

### Steps To Reproduce
1. ...install `parallel` in `/etc/nixos/configuration.nix`
2. ...run `man parallel`
3. ...return `No manual entry for parallel`

### Expected behavior
parallel manual shows up.

@pSub @vrthra @tomberek

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.20231202.933d7dc`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
If you run `nix shell nixpkgs#parallel` you should enter a shell where `man` works. Make sure your config looks like this:

```nix
{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    parallel
  ];
}
```

**Comment by benaryorg** [comment]
The parallel package has [multiple outputs for its binary, documentation, and man-pages](https://hydra.nixos.org/build/243591569#tabs-details). Entering a shell with *nix-shell* will only use the output for the binaries. You can use the following to pull in the output for the man-pages too:

```bash
nix-shell -p parallel parallel.man
```

This will allow you to run `man parallel`.

See also: https://discourse.nixos.org/t/missing-man-pages/4680/6

**Comment by amalgame21** [comment]
`nix shell nixpkgs#parallel` have the manpage but only `parallel` in `environment.systemPackages` does not.
Adding `parallel.man` solve my problem. Thank you so much!

**Comment by benaryorg** [comment]
@amalgame21 oh, I'm sorry, I totally missed that you're trying to add it to `environment.systemPackages`, in that case you might want to check `documentation.enable` and `documentation.man.enable`. As far as I understand it, enabling those should *automatically* add the man-pages. They should be enabled by default but some modules/profiles may inadvertently disable this:

https://github.com/NixOS/nixpkgs/blob/c979d0efb4babbb00f8c52a27298804adc28355a/nixos/modules/profiles/minimal.nix#L11

**Comment by amalgame21** [comment]
Oops, sorry that I had a wrong description in my situration.
I tested putting `parallel` in `environment.systemPackages`, which install manpage just fine.
But I use `parallel-full` / `(parallel-full.override { willCite = true; })` instead, which does not install the manpage.
In this case, `parallel.man` is working for me.
