### ISSUE TITLE
Constant Moonraker warnings

### ISSUE THREAD

**Issue by alxpettit** [NixOS/nixpkgs#273678]
### Describe the bug

Moonraker shows warning:
```
Moonraker warnings found.
file_manager: Klipper configuration file not located in 'config' folder.

Klipper Config Path: /etc/klipper.cfg

Config Folder: /var/lib/moonraker/config
```

### Steps To Reproduce

```nix
services.moonraker = {
  ## Requires group klipper to access /run/klipper/api socket
  group = "klipper";
  enable = true;
  address = "0.0.0.0";

  # Allows control of system wide reboot, shutdown etc via client API
  allowSystemControl = true;

  settings = {
    server = {
      max_upload_size = 16384;
    };
    octoprint_compat = {
      enable_ufp = true;
      webcam_enabled = true;
    };
    authorization = {
      force_logins = true;
      cors_domains = [
        "http://*.lan"
        "http://*.local"
      ];
      trusted_clients = [
        "10.0.0.0/8"
        "127.0.0.1"
      ];
    };
  };
};

users.groups.klipper = {
  gid = 982;
};
users.users.klipper = {
  uid = 982;
  group = "klipper";
  isSystemUser = true;
};

services.klipper = {
  package = cfg.package;
  enable = true;
  # I think octoprint integration requires the same user
  # as octoprint, thus 'octoprint' by default.
  # Thus, we cannot set it without a conflict if we're using octoprint.
  user = "klipper";
  group = "klipper";
  # DO NOT ENABLE! DOES NOT TRIGGER UPDATES WHEN CHANGE
  # copy config to mutable file path
  # mutableConfig = true;
    firmwares = {
      mcu = {
        enable = true;
        configFile = ./printers/${cfg.printerType}/mcu.env;
      };
    };
};
```

### Expected behavior
No warnings.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/28266167/3419fc6a-505e-4fc1-ad24-a13c22c01365)

### Notify maintainers

@cab404
@vtuan10
@zhaofengli

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nixPath`
```

**Comment by eyJhb** [comment]
Annoys me a great deal as well. Trying to figure out, why it even matters.

**Comment by eyJhb** [comment]
Well, it's just a no-wont-change, without any reason really. So I guess we either have to patch that part out, or just place the configuration file in the moonraker configuration directory, Which seems rather annoying.

**Comment by vtuan10** [comment]
Moonraker provides a script for MainsailOS and FluiddPi which fixes this by [creating a symlink](https://github.com/Arksine/moonraker/blob/6d8cb762ffca1bd151d98e0cec5b66b966965014/scripts/data-path-fix.sh#L59). How about we do the same or add a bind mount to the serviceConfig?

**Comment by eyJhb** [comment]
> Moonraker provides a script for MainsailOS and FluiddPi which fixes this by [creating a symlink](https://github.com/Arksine/moonraker/blob/6d8cb762ffca1bd151d98e0cec5b66b966965014/scripts/data-path-fix.sh#L59). How about we do the same or add a bind mount to the serviceConfig?

That doesn't work, I've tried it out (symlink), and am currently trying to find a solution here https://github.com/Arksine/moonraker/issues/767 .

It seems like there will be provided a way to opt out, which would be ideal, or if the symlink part worked then it would also be OK.

If symlink worked, then the following could be added to the moonraker module

```
  systemd.tmpfiles.rules = [
    "L /var/lib/moonraker/config/klipper.cfg - - - - /etc/klipper.cfg"
  ];
```

For now I'm just patching the moonraker package using the following (not recommended, hopefully moonraker will be updated soon-ish).

```nix
{ pkgs, ... }:

let
  moonrakerConfigPatch = pkgs.writeText "moonraker-config.patch" ''
diff --git a/moonraker/components/file_manager/file_manager.py b/moonraker/components/file_manager/file_manager.py
index edae73f..7379e0d 100644
--- a/moonraker/components/file_manager/file_manager.py
+++ b/moonraker/components/file_manager/file_manager.py
@@ -194,26 +194,6 @@ class FileManager:
             self.server.register_static_file_handler(
                 "klippy.log", log_path, force=True)
 
-        # Validate config file
-        cfg_file: Optional[str] = paths.get("config_file")
-        cfg_parent = self.file_paths.get("config")
-        if cfg_file is not None and cfg_parent is not None:
-            cfg_path = pathlib.Path(cfg_file).expanduser()
-            par_path = pathlib.Path(cfg_parent)
-            if (
-                par_path in cfg_path.parents or
-                par_path.resolve() in cfg_path.resolve().parents
-            ):
-                self.server.remove_warning("klipper_config")
-            else:
-                self.server.add_warning(
-                    "file_manager: Klipper configuration file not located in "
-                    "'config' folder.\n\n"
-                    f"Klipper Config Path: {cfg_path}\n\n"
-                    f"Config Folder: {par_path}",
-                    warn_id="klipper_config"
-                )
-
     def validate_gcode_path(self, gc_path: str) -> None:
         gc_dir = pathlib.Path(gc_path).expanduser()
         if "gcodes" in self.file_paths:
'';
in {
  services.moonraker = {
    package = pkgs.moonraker.overrideAttrs (fAttrs: pAttrs: {
      patches = [ moonrakerConfigPatch ];
    });
  };
}
```

**Comment by eyJhb** [comment]
I've opened two PRs. One that bumps the moonraker package to include a commit that has the option `file_manager.check_klipper_config_path`, which can be set false.

And another one, that sets this to false, if NixOS manages the klipper configuration.

**Comment by alxpettit** [comment]
@eyjhb Oh, nice! Thank you! :) I... briefly spoke to them about this myself, and they, for some _bizarre_ reason, just 'recommended' I use Debian, and seemed totally disinterested in fixing the problem. I'm glad you got something to work! :)

**Comment by eyJhb** [comment]
> @eyJhb Oh, nice! Thank you! :) I... briefly spoke to them about this myself, and they, for some _bizarre_ reason, just 'recommended' I use Debian, and seemed totally disinterested in fixing the problem. I'm glad you got something to work! :D

I think they mostly opposed that it was formulated as NixOS is using "hacks" to run their software (which I understand a maintainer does not want to deal with), however, this warning has nothing to do with anything NixOS related as such. :) - But yeah, initially they seemed disinterested in discussing any kind of work-around, but I'm happy that we came to an agreement with the maintainer, without (hopefully), being too much of a inconvenience :)

If anyone wants to run have a temp override, then it's available here

```nix
    package = pkgs.moonraker.overrideAttrs (fAttrs: pAttrs: {
      version = "unstable-2023-12-1$";

      src = pkgs.fetchFromGitHub {
        owner = "Arksine";
        repo = "moonraker";
        rev = "42357891a3716cd332ef60b28af09f8732dbf67a";
        sha256 = "sha256-5w336GaHUkbmhAPvhOO3kNW5q7qTFVw3p0Q+Rv+YdYM=";
      };
    });
```

**Comment by alxpettit** [comment]
@eyJhb
> I think they mostly opposed that it was formulated as NixOS is using "hacks" to run their software

I guess the word 'hacks' has different connotation for me than it does for some devs. I'll have to watch that in the future! :P
