### ISSUE TITLE
Obsidian requires Electron 25 now EOL

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#273611]
The package Obsidian requires Electron 25. However, Electron 25 is now EOL. I've opened the following issue upstream to request an update to the version of Electron: https://forum.obsidian.md/t/electron-25-is-now-eol-please-upgrade-to-a-newer-version/72878

**Comment by sdht0** [comment]
Overriding works for me:
```nix
  (final: prev: {
    obsidian-overlay = prev.obsidian.override {
      electron = prev.electron_26;
    };
  })
```

**Comment by sersorrel** [comment]
conversely, electron 26 does not work here (using insider builds 1.5.1 and 1.5.2)

**Comment by AndrewKvalheim** [comment]
In case this is useful to anyone else, this is the workaround I’m using:

```nix
obsidian = throwIf (versionOlder "1.4.16" obsidian.version) "Obsidian no longer requires EOL Electron" (
  obsidian.override {
    electron = electron_25.overrideAttrs (_: {
      preFixup = "patchelf --add-needed ${libglvnd}/lib/libEGL.so.1 $out/bin/electron"; # NixOS/nixpkgs#272912
      meta.knownVulnerabilities = [ ]; # NixOS/nixpkgs#273611
    });
  }
);
```

**Comment by NobbZ** [comment]
> `throwIf (versionOlder "1.4.16" obsidian.version)`

Doesn't that mean that 1.4.15 would throw to tell you to remove the snippet, while 1.4.17 would just be built with the old defect electron?

PS: My workaround was `nixpkgs.config.allowInsecurePackages` or how its called.

**Comment by jpotier** [comment]
I'm adding this to my configuration.nix for now:

```
{
  nixpkgs.config.permittedInsecurePackages =
    lib.optional (pkgs.obsidian.version == "1.4.16") "electron-25.9.0";
}
```

Whenever a new version of obsidian lands, the exception won't hold anymore, automatically. If it needs to be extended I'll know.

**Comment by gerardbosch** [comment]
Hi, may I ask a little offtopic? I'm facing this issue too, but it took me some time to figure out that was Obsidian the package causing this error. That's because I upgrade all my packages with:

```
NIXPKGS_ALLOW_UNFREE=1 nix profile upgrade --impure '.*'
```

But when I do this, there's no clue (no log) about which is the package causing the error.
So, is there any way to get a little more detailed output or log? Thanks!

**Comment by jansol** [comment]
@gerardbosch there is `--show-trace` which often gives you *some* hint, but this is unfortunately a thing where nix currently could do a lot better.

**Comment by MForster** [comment]
@gerardbosch 

```
>> nix-store --query --referrers /nix/store/dncl8q8cqrmglcakzxic7h5rkrk3b5zh-electron-25.9.0.drv
/nix/store/1fly55mqavx1m1ff2znn1zzjsfs84b1x-obsidian-1.4.16.drv
```

**Comment by becknik** [comment]
> In case this is useful to anyone else, this is the workaround I’m using:
> 
> ```nix
> obsidian = throwIf (versionOlder "1.4.16" obsidian.version) "Obsidian no longer requires EOL Electron" (
>   obsidian.override {
>     electron = electron_25.overrideAttrs (_: {
>       preFixup = "patchelf --add-needed ${libglvnd}/lib/libEGL.so.1 $out/bin/electron"; # NixOS/nixpkgs#272912
>       meta.knownVulnerabilities = [ ]; # NixOS/nixpkgs#273611
>     });
>   }
> );
> ```

Thanks for this patch, this at least fixes the error log containing many `Could not dlopen native EGL: libEGL.so.1`s when running obsidian from the terminal.
Obsidian now however seems to quit when I try to open my vault, so I still have to use 1.4.15...

**Comment by EricTheMagician** [comment]
#277002 has been committed. It updates obsidian to 1.5.3.
Updating to a newer electron (v27 or v28) version is still problematic.

**Comment by robsliwi** [comment]
Stumbled across this issue trying to add `obsidian` to my home-manager config using Nix flakes. Thanks for bumping Obsidian to 1.5.3 with https://github.com/NixOS/nixpkgs/pull/277002.

The following snippet added to the flake let me proceed using it:

```
  nixpkgs = {
    config = {
      allowUnfree = true;
      permittedInsecurePackages = [ "obsidian-1.5.3" "electron-25.9.0" ];
    };
  };

```

Is there a better way specifying this explicit combination of Obsidian and Electron instead of allowing them separately?

Right now getting the root cause fixed is somewhat _postponed_ by the Obsidian people: https://forum.obsidian.md/t/electron-25-is-now-eol-please-upgrade-to-a-newer-version/72878/4

**Comment by XenGi** [comment]
> In case this is useful to anyone else, this is the workaround I’m using:
> 
> ```nix
> obsidian = throwIf (versionOlder "1.4.16" obsidian.version) "Obsidian no longer requires EOL Electron" (
>   obsidian.override {
>     electron = electron_25.overrideAttrs (_: {
>       preFixup = "patchelf --add-needed ${libglvnd}/lib/libEGL.so.1 $out/bin/electron"; # NixOS/nixpkgs#272912
>       meta.knownVulnerabilities = [ ]; # NixOS/nixpkgs#273611
>     });
>   }
> );
> ```

How do I use this in my nix config?

**Comment by jesskay** [comment]
Obsidian [has now been updated](https://forum.obsidian.md/t/electron-25-is-now-eol-please-upgrade-to-a-newer-version/72878/13) to use Electron 28, so once a PR to update to 1.5.8 lands, that should resolve this issue.

**Comment by sdht0** [comment]
#290892 merged. This can be closed now I think?
