### ISSUE TITLE
makemkv broken after upgrade to 23.11 - "Failed to execute external program 'ccextractor' from location '/usr/local/bin/ccextractor'"

### ISSUE THREAD

**Issue by tompurl** [NixOS/nixpkgs#273687]
### Describe the bug
I am using `makemkv` to rip a DVD to a series of mkv files. When I try to do so I get the following error for every file it tries to convert into an MKV:

> ...
> Failed to execute external program 'ccextractor' from location '/usr/local/bin/ccextractor'
> Failed to save title 1 to file /home/tom/Videos/MANNIX_S1_D2/B1_t01.mkv
> ...

This affects both the GUI and command-line versions (makemkvcon) of the app. There is a workaround for the GUI that's not great but no workaround for the command-line version.

### Steps To Reproduce
1. Open `makemkv' gui on a computer with access to a DVD
  1. For example, why not Season 1, Disc 1 of "Mannix". It's a really cool show. 
3. Click on the button to convert the titles on the disc to mkv's.
4. Select the titles that you want using the check boxes and don't unselect any of their respective sub-check boxes.
5. Press the go button.

### Expected behavior
1 MKV to be written to disc for each selected title.

### Screenshots
n/a

### Additional context

There *is* a workaround. When selecting the title checkboxes in the gui expand them and un-select the subtitles checkbox. This works around the issue but is a problem if you need subtitles.

---

Also, I tried fixing this by installing ccextractor but that didn't seem to have any effect.

---

Finally, there is no `/usr/local/bin` in the NixOS world, so it's not like I can just go out and create a symlink there :-)

### Notify maintainers

@titanous 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 23.11 (Tapir), 23.11.1494.b4372c4924d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - channels(tom): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qubitnano** [comment]
Hi there, I'm trying to reproduce this but can't so far.

ccextractor seems vendored with makemkv and is compiled as ``mmccextr``.

I tested running on your nixos-version commit b4372c4924d9 with makemkv debug mode enabled with a random dvd with an empty `~/.MakeMKV`

subtitle info before clicking write
```
Track information
Type: Subtitles
Language: English
Codec: Closed Captions → Text
Output format: Text subtitles ( Lossy conversion )
MKV Flags: Default
```

Debug log with successful save:

```
CCX001: Launching /nix/store/plfmh0c191zsv7sj2pwhmgy9pmyc2xxi-makemkv-1.17.5/bin/mmccextr
001003:0020 DEBUG: Code 0 at z6jq?_t<B1y?.8j.EyG^=::29393631
001003:0020 DEBUG: Code 0 at z6jq?_t<B1y?.8j.EyG^=::29393631
CCX001: CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
CCX001: Teletext portions taken from Petr Kutalek's telxcc
CCX001: This is a reduced-functionality version optimised for DVD closed captions transcoding.
CCX001: --------------------------------------------------------------------------
CCX001: -----------------------------------------------------------------
CCX001: Reading from standard input
CCX001: Analyzing data in CCExtractor's binary format
CCX001: Sending captions to stdout.
```

Is `app_ccextractor` set in ``~/.MakeMKV/settings.conf``?

Was this working for you in 23.05? Is this the only disc that won't work?

**Comment by tompurl** [comment]
That's so weird. When I look in my `~/.MakeMKV/settings.conf` file I see the following:

```
app_Key = "somethingWeird"
app_ccextractor = "/usr/local/bin/ccextractor"
```

I have no idea how or why I had `app_ccextractor` defined. Also, I've used this app for well over a year with previous versions of NixOS and this config file hasn't been edited since December of 2022 :-).

So yes, this does appear to be a config issue on my side @qubitnano . Thank you for the help!
