### ISSUE TITLE
Setting or overriding `cmakeBuildType` does not work for Qt applications

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#273632]
When we set or override `cmakeBuildType = "Debug"` for a Qt program such as `meshlab`, it has no effect:

```sh
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz nix-build --expr '(import <nixpkgs> {}).meshlab.overrideAttrs (old: { cmakeBuildType = "Debug"; preUnpack = "echo $cmakeBuildType; exit 1"; })'
```

```
this derivation will be built:
  /nix/store/kzij2izq2f80lq5c00zskjnq5liladm4-meshlab-2022.02.drv
building '/nix/store/kzij2izq2f80lq5c00zskjnq5liladm4-meshlab-2022.02.drv'...
qtPreHook
unpacking sources
Release
```

It still prints `Release`.

That is frustrating and confusing.

I would like to override it to get debug symbols for a crash, and it simply has no effect because of this.

As described on https://discourse.nixos.org/t/single-cmakebuildtype-shared-between-derivation-and-dependency/35184 this is because the `qtbase` setup hook (here `qt-5`, same for `qt-6`), sets it unconditionally:

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/development/libraries/qt-5/hooks/qtbase-setup-hook.sh#L25-L31

We should fix this somehow.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nh2** [comment]
@NixOS/qt-kde

**Comment by NickCao** [comment]
See https://github.com/NixOS/nixpkgs/pull/299364

**Comment by NickCao** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/307573
