### ISSUE TITLE
`clang-tools_17` undefined variable 

### ISSUE THREAD

**Issue by LamprosPitsillos** [NixOS/nixpkgs#273744]
### Describe the bug
Even though the package is in the NixPackages search , while building it is an 
` error: undefined variable 'clang-tools_17' `

### Steps To Reproduce
1. add `clang-tools_17` to `packages`
2. try to build

### Expected behavior
Clang tools 17 to be installed 

### Screenshots
![2023-12-11_13-54-29_clang](https://github.com/NixOS/nixpkgs/assets/61395246/27e0630c-6907-40e8-b798-ab5b2c096b73)

### Additional context
https://github.com/LamprosPitsillos/nixos-config/blob/main/flake.lock
My flake lock along with the rest of my conf

### Notify maintainers
@Patryk27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console

❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.65, NixOS, 24.05 (Uakari), 24.05.20231204.2c7f3c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/aiv01710wqn2b7hms2253d1cq89kdzh8-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Patryk27** [comment]
I think you're using older version of nixpkgs that didn't have this package yet - try:
```
nix flake lock --update-input nixpkgs
```
... and then rebuild your system again.

**Comment by LamprosPitsillos** [comment]
> nix flake lock --update-input nixpkgs

will do and report back.
Shouldnt `nix flake update` be enough ? I updated a few days ago

**Comment by Patryk27** [comment]
>  Shouldnt `nix flake update` be enough ? I updated a few days ago

It would be enough, but llvm17 has been merged just 5 days ago (https://github.com/wegank/nixpkgs/commits/99fa28912a521a1c6c0b699cf0c2ce03426328db/pkgs/development/compilers/llvm/17/default.nix) and you've probably run that some time longer ago.

**Comment by LamprosPitsillos** [comment]
It's now , fixed thanks!

**Comment by donottellmetonottellyou** [comment]
This issue exists again for clang_17 and clang-tools_17. Same problem and expected result as above.
```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/m9anmz1n512blbd582kw46pxyns3pvah-nixos-stable-20240326`
```

**Comment by Patryk27** [comment]
No, @donottellmetonottellyou - you're actually facing the same issue the original author faced, i.e. you're using too old Nixpkgs.

7c6e3666e2040fb64d43b209b84f65898ea3095d is from Nov 29, 2023; I'm guessing you've just updated `name` inside the call to `fetchGit`, but it's `rev` which matters there.

**Comment by donottellmetonottellyou** [comment]
Wait what? What am I doing wrong here:

```
git ls-remote https://github.com/nixos/nixpkgs 23.11
7c6e3666e2040fb64d43b209b84f65898ea3095d        refs/tags/23.11
```

Oof, it looks like I was targeting the 23.11 *tag*, not the proper nixos *branch*:

```
git ls-remote https://github.com/nixos/nixpkgs nixos-23.11
219951b495fc2eac67b1456824cc1ec1fd2ee659        refs/heads/nixos-23.11
```

I officially feel like an idiot.

Yes, I had been checking the rev, and had been absentmindedly not noticing that it wasn't changing...

Posting this here so if anyone makes the same mistake (probably not) they see this.
