### ISSUE TITLE
Really obscure rust crash when compiling seemingly innocent library

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#27370]
On Darwin, when I was trying to package a rust library, I noticed that an innocent program would crash the compiler with the following message:

```
error: failed to build archive: bad archive: truncated or malformed archive (offset to next archive member past the end of the archive after member std-23c7ab017b56c6b0.0.bytecode.deflate)
```

I'm filing the issue under nixpkgs because it doesn't seem to happen in the upstream version of `rustc`, so something about how we do things is either triggering an obscure bug in rustc (that doesn't normally get triggered) or we've caused it to break in some other way.

This is the fruit of my minimization:

```nix
with import <nixpkgs> {};

let
  src = writeText "repro.rs" ''
    pub extern fn test() {}
  '';
# If you s/dylib/cdylib/, it works fine
in runCommand "repro" {} ''
  mkdir -p $out
  ${rustc}/bin/rustc --crate-type dylib ${src} --out-dir $out
''
```

I'm aware that `dylib` isn't really intended as a user-facing feature, but apparently `cdylib` isn't quite there yet and is breaking things for at least one downstream package that still uses `dylib`. Also, if that library were really corrupted, wouldn't `cdylib` fail as well?

**Comment by grahamc** [comment]
```
nix-build ./test.nix                                                                                               ~
these derivations will be built:
  /nix/store/vig547mnaccijrz47c1cv2s275a6wixw-repro.drv
building path(s) ‘/nix/store/y7skd7js8xibvlc2lz1rsbfz8bl8jqvl-repro’
builder for ‘/nix/store/vig547mnaccijrz47c1cv2s275a6wixw-repro.drv’ failed to produce output path ‘/nix/store/y7skd7js8xibvlc2lz1rsbfz8bl8jqvl-repro’
error: build of ‘/nix/store/vig547mnaccijrz47c1cv2s275a6wixw-repro.drv’ failed
```

**Comment by copumpkin** [comment]
cc @wizeman @Mic92 @the-kenny who seem to be fairly active Nix rust contributors

**Comment by the-kenny** [comment]
Can't say anything about Darwin, don't have a Mac handy. Works fine on NixOS as of 1e1472e

**Comment by Mic92** [comment]
@copumpkin what llvm version is used by upstream rustc?

**Comment by copumpkin** [comment]
They keep their own custom version, which we support in our expression but don't use by default. I tried switching back to it but it didn't help. I'll probably iteratively get closer and closer to their build until I figure out what's causing this and file a bug :(

**Comment by copumpkin** [comment]
I tried switching on `forceBundledLLVM` (and disabling `--enable-llvm-link-shared` which I think is required if you force the bundled LLVM) and it doesn't help; in fact it gives a less useful error message because I guess errors in this space improved in LLVM 4 😄

**Comment by matthewbauer** [comment]
So, I'm getting this same issue when trying to compile Firefox on MacOS. Don't have much to add, just that this still seems to be an issue.

**Comment by copumpkin** [comment]
Oh, firefox now includes rust code?

**Comment by vyp** [comment]
@copumpkin Yes, iirc some [quantum/stylo](https://wiki.mozilla.org/Quantum/Stylo) 'code' is in Firefox 57, though it needs to be enabled via `about:config` I think.

**Comment by matthewbauer** [comment]
For some reason it checks for it? Here's the branch if anyone wants to look at it:

https://github.com/matthewbauer/nixpkgs/tree/firefox-on-macos

**Comment by 7c6f434c** [comment]
And version 56 already has an option to enable Rust implementation of URL parser.

**Comment by copumpkin** [comment]
Anyone in the Nix+Rust community know how we might go about debugging this? I filed https://github.com/rust-lang/rust/issues/42857 but since it's almost impossible for anyone outside of Nix+Darwin to reproduce it, I'm not sure how to proceed.

**Comment by vyp** [comment]
> Anyone in the Nix+Rust community [...]

cc @garbas

**Comment by Mic92** [comment]
@copumpkin does the same happen with rust overlay? https://github.com/mozilla/nixpkgs-mozilla

**Comment by Mic92** [comment]
Have you tried to set a different linker with: `rustc -C linker=`?

**Comment by copumpkin** [comment]
Yeah, I've tried with a different linker (pretty sure) but haven't tried the rust overlay. Is that meaningfully different in the build of rustc itself? I assumed it was a different package set but the compiler was largely the same.

**Comment by Mic92** [comment]
No, the overlay uses a pre-compiled version from mozilla.

**Comment by Mic92** [comment]
Actually rust does not deal with ar-archives at all. This is all delegated to the dedicated linker.

**Comment by matthewbauer** [comment]
Here's the full log for building firefox on macosx:

```
checking for libffi > 3.0.9... yes
checking MOZ_FFI_CFLAGS... -I/nix/store/n0sxvxbwzbvjgnxb06cyigacmp5ks839-libffi-3.2.1-dev/include
checking MOZ_FFI_LIBS... -L/nix/store/k7mzh64lsrhydzl8ky1bmg002fx2qav7-libffi-3.2.1/lib -lffi
checking for rustc... /nix/store/qhv9ddgwpn3zsjy33awk7zxg2jq2p5cb-rustc-1.20.0/bin/rustc
checking for cargo... /nix/store/zb0wswwdxynpsjjpmdqrx3k2zisichfc-cargo-0.22.0/bin/cargo
checking rustc version... 1.20.0
checking cargo version... 0.22.0
DEBUG: Executing: `/nix/store/qhv9ddgwpn3zsjy33awk7zxg2jq2p5cb-rustc-1.20.0/bin/rustc --crate-type staticlib --target=x86_64-apple-darwin -o /private/tmp/nix-build-firefox-unwrapped-56.0.2.drv-0/conftestYbTD_w.rlib /private/tmp/nix-build-firefox-unwrapped-56.0.2.drv-0/conftestbt9Rry.rs`
DEBUG: The command returned non-zero exit status 101.
DEBUG: Its error output was:
DEBUG: | error: failed to build archive: bad archive: truncated or malformed archive (offset to next archive member past the end of the archive after member std-6227198845c1feb5.0.bytecode.deflate)
DEBUG: |
ERROR: Cannot compile for x86_64-apple-darwin17.3.0 with /nix/store/qhv9ddgwpn3zsjy33awk7zxg2jq2p5cb-rustc-1.20.0/bin/rustc
The target may be unsupported, or you may not have
a rust std library for that target installed. Try:

  rustup target add x86_64-apple-darwin

builder for '/nix/store/w0sbrgpljm7cl27jmbkpg025nrggy9xs-firefox-unwrapped-56.0.2.drv' failed with exit code 1
cannot build derivation '/nix/store/if4y6jaf9mjlgla2z92s1cdxxn346xx0-firefox-56.0.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/if4y6jaf9mjlgla2z92s1cdxxn346xx0-firefox-56.0.2.drv' failed
```

**Comment by copumpkin** [comment]
Is firefox using `dylib`? Does `cdylib` work? It might be a less obscure place to start the conversation on why they're not equivalent for these uses, since I think they're trying to discourage folks from using `dylib` except for compiler plugins.

**Comment by copumpkin** [comment]
Oh, interesting, it's happening with `--crate-type staticlib` (sorry I missed that in your log above). I haven't seen that before.

**Comment by zimbatm** [comment]
It might be worth trying to upgrade rust itself, we are two minor versions behind? The only issue is that last time I tried firefox wasn't compiling. Maybe with the firefox 57 release that issue has been fixed.

**Comment by copumpkin** [comment]
It looks like we're only one version behind? From @matthewbauer's log:

```
checking rustc version... 1.20.0
checking cargo version... 0.22.0
```

Back when I first noticed this, we were on 1.17.

**Comment by zimbatm** [comment]
Err just re-read my last comments in 8 days and I will be right :) https://forge.rust-lang.org/

**Comment by LnL7** [comment]
There's pr for rust ready, now that ff 57 is released we should be able to update.

**Comment by zimbatm** [comment]
Rust 1.22 is in #31982 if you want to give it a try

**Comment by matthewbauer** [comment]
@copumpkin I think this issue has been fixed. At least your .nix file succeeds under nixpkgs-unstable.

**Comment by LnL7** [comment]
Yeah, #34227 fixed this.

**Comment by copumpkin** [comment]
Awesome, thanks!
