### ISSUE TITLE
cudaPackages: all outPaths should be evaluate-able

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#273794]
...even for packages marked "broken".

Reflecting on https://github.com/NixOS/nixpkgs/pull/273781, our error handling should obviously take Ofborg into account, as well as try not to break interfaces that users outside nixpkgs might expect. One way to go could be:

- No `throw`s, only `meta.broken`. Users can override `meta.broken`
- Broken packages shall still evaluate with `allowBroken = true`: they'll have a valid `outPath`, but their builds would always fail.
- In particular, when there's a `src` missing for a `sourceProvenance = [ binaryNativeCode ]` package (e.g. depending on the platform), we should set `src` to a valid fake value, e.g.`null`. In contrast, this `fetchurl` throws: https://github.com/NixOS/nixpkgs/blob/076fc3ad3158bdf0b04374570dfaa30fd0aaf9a9/pkgs/development/cuda-modules/generic-builders/manifest.nix#L112-L117
- Optionally: prefer static structure for attribute sets when possible, cf. https://github.com/NixOS/nixpkgs/issues/266475. This may also be related to recursion issues

@NixOS/cuda-maintainers

**Comment by ConnorBaker** [comment]
Here are my takeaways:

> [!Important]
>
> 1. All default attributes should evaluate successfully.
> 2. Incoherent configurations should be caught by assertion.
> 3. Invalid configurations which will fail to build or run should be marked as broken.
> 4. Supported platforms should not be conditional on configuration.

> [!Note]
> Our conditional platform logic exists only because we do not have a platform specific to Jetson and instead re-use `aarch64-linux`.

I'll see if I can work with this. One thing of note from the conversation in Matrix:

Consumers of our packages can use `meta.unsupported`, a derived attribute: https://github.com/NixOS/nixpkgs/blob/fd7914c96f7c006047e0154dd239aa2396478094/pkgs/stdenv/generic/check-meta.nix#L310-L364

This would allow them to avoid checking for existence of a package in our package set, and instead condition on `meta.unsupported`.

**Comment by ConnorBaker** [comment]
Tracked in #274319.

**Comment by SomeoneSerge** [comment]
> Our conditional platform logic exists only because we do not have a platform specific to Jetson and instead re-use aarch64-linux

H'm. On that note, `cudaSupport` and `cudaCapabilities` effectively are part of the "real" platform
