### ISSUE TITLE
networking: possibility to add extra routes

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27380]
One of the my cloud hostings requires the following route configuration:

Say, VPS IP is ```55.45.70.41``` (ips are changed, just an example to get the idea)
The route setup is
```
# route
0.0.0.0          55.45.85.85     0.0.0.0         UG    0      0        0 eth0   
55.45.70.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0   
55.45.85.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0   
```
Note 
 * there are two /24 networks on the same interface
 *  the host ```55.45.70.41``` and the default gateway ```55.45.85.85``` are in the different networks

NixOS networking (at least the scripting variant) does not support a setup like this.
Would you mind to add an option to specify the extra routes?
It seems trivial but there could be different points on how to implement it.

**Comment by volth** [comment]
It could be something like this: https://github.com/volth/nixpkgs/commit/cf5ac7e69ab1f5a2fdb4702705c3e4e40b158006
(a quick hack I made to install NixOS on that cloud)

**Comment by fpletz** [comment]
I brought up the idea of a `networiking.routes` module in #12500. We already have ideas for an interface which would be based on `iproute2`'s `ip route` command syntax.  We or somebody else should do this for 17.09.

**Comment by volth** [comment]
Here I (ab)used ```ip route``` syntax (in examples, ["172.16.5.0/24 via 10.0.0.101"]) just because CentOS (which was there before ```nixos-infect```) does the same in its configs. There was no other reason, I have no opinion is it a right thing to do or not.

**Comment by rnhmjoj** [comment]
#27688 has been merged. Can we close this issue?
