### ISSUE TITLE
nixos/trunk-combined fails to evaluate

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#27381]
http://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

```
hydra-eval-jobs returned signal 6:
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

According to http://hydra.nixos.org/job/nixpkgs/trunk/metrics#tabs-charts, there are two diffs related to stdenv changes that decrease performance:

- http://hydra.nixos.org/api/scmdiff?type=git&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&branch=&rev1=0f2db06540bac596ac47816b76c189f4715c8ea5&rev2=3abfc161f947fd3487a2ff65a0fdf24415df3505
- http://hydra.nixos.org/api/scmdiff?uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&type=git&rev2=dc9f69c260139c23fa4944826acc3d46ef1a3237&rev1=e10e3c1d1aaa8d4ba15468d0351af370a663cbc9&branch=

cc @edolstra @Ericson2314

**Comment by vcunat** [comment]
I have occasionally seen this error earlier as well.  I'm not sure why it's non-deterministic, but perhaps we should increase this limit at least on Hydra...
