### ISSUE TITLE
Update request: netlify-cli 12.2.4 → 17.10.1

### ISSUE THREAD

**Issue by v-kat** [NixOS/nixpkgs#273812]
Package name: netlify-cli

Latest released version: 17.10.1

Current version on the unstable channel: 12.2.4

Current version on the stable/release channel: 12.2.4

Checked the nixpkgs pull requests

@roberth 
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by roberth** [comment]
There's a proposal to change the packaging here
- https://github.com/NixOS/nixpkgs/pull/243664

Let's ask how that's going.

**Comment by v-kat** [comment]
Is there anyone you could hand off maintenance to? The other PR seems stalled
