### ISSUE TITLE
Possibility to expose /nix/store as binary cache

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27386]
The idea is so obvious that I wonder that have not seen any implementation yet:

Could a NixOS machine expose its ```/nix/store``` via ```http``` in a way compatible with binary cache protocol?

Why: 

If you deploy freshly made software to many servers, it is not on Hydra nor on ```cache.nixos.org```, it is just on your laptop, you have to ```nix-copy-closure``` it from a workstation to each of the targets. It is slow

If those targets expose their ```/nix/store```s, you could do some poor man P2P push-style distribution, performing 
```nix-store --option binary-caches 'http://server-where-software-already-deployed' --realise /nix/store/pathes``` just before ```nix-copy-closure```

**Comment by vcunat** [comment]
There is http://nixos.org/nix/manual/#ssec-binary-cache-substituter and the corresponding `services.nix-serve.*` for NixOS.

**Comment by volth** [comment]
ah, super.
thank you!

**Comment by volth** [comment]
Perhaps I'd only run is as a CGI under lightthd to save memory and avoid dealing with firewall rules for one more port.

**Comment by volth** [comment]
There is also https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/http/nix-binary-cache/default.nix
