### ISSUE TITLE
Package request: codeium.el

### ISSUE THREAD

**Issue by gekoke** [NixOS/nixpkgs#273977]
**Project description**

Free, ultrafast Copilot alternative for Emacs 

**Metadata**

* homepage URL:  https://codeium.com/
* source URL: https://github.com/Exafunction/codeium.el
* license: mit
* platforms: unix, linux, darwin

Package functionality depends on a proprietary binary downloaded at runtime. The package has trouble running it on NixOS but this can be patched (see https://github.com/Exafunction/codeium.el/issues/34#issuecomment-1638666840 and https://github.com/Exafunction/codeium.el/issues/34#issuecomment-1758607516).

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by running-grass** [comment]
I think I can give it a try
