### ISSUE TITLE
tinc needs write access to files in /etc/tinc/${network}/hosts

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27397]
## Issue description

Tinc service creates files in ```/etc/tinc/${network}/hosts``` with [owner root and mask 0444](https://github.com/NixOS/nixpkgs/blob/19c298e97328ee78e639682ec195ce3e820d8387/nixos/modules/services/networking/tinc.nix#L124), so tinc daemon cannot write to them

But in some circumstances tinc daemon wants to write to the files.
For example if host file has only RSA key and a peer starting to support ED25519 then tinc tries to append a new ED25519-key to the host file and fails with access denied

File chenged by the daemon looks like:
```
$ cat /etc/tinc/dmz/hosts/I1                                     
-----BEGIN RSA PUBLIC KEY-----                                   
MIIBCgKCAQEApM0........
-----END RSA PUBLIC KEY-----                                     

# The following line was automatically added by tinc             
Ed25519PublicKey = T3....
```

### Steps to reproduce

You need a mixed Tinc network with 1.0.x and 1.1.x nodes and then upgrade 1.0.x-nodes to 1.1.x, existing 1.1.x-nodes will learn that their peers are upgraded and now support ED25519, request their keys and update hosts files.

**Comment by georgewhewell** [comment]
It looks like running  `tinc -n NETNAME generate-ed25519-keys` during install should generate any missing ed25519 keys.

**Comment by volth** [comment]
@georgewhewell No. The missing keys are not keys of the local Tinc node, it is keys of a remote peer which just upgraded from 1.0.x to 1.1.x, generated its peer (without any human intervention) and distributed them among 1.1.x-peers

**Comment by volth** [comment]
Well, it is too difficult and needless to explain its logic.
Better to point to Tinc source code where those files are opened for writing:
https://github.com/gsliepen/tinc/blob/1.1/src/conf.c#L423
