### ISSUE TITLE
Build failure: aacgain: autoreconf: error: 'configure.ac' is required

### ISSUE THREAD

**Issue by jfly** [NixOS/nixpkgs#273907]
### Steps To Reproduce

1. `nix build nixpkgs/a9bf124c46ef298113270b1f84a164865987a91c#aacgain`

### Build log

https://gist.github.com/jfly/d4bae05f403db731c1d1d8dee877ea3e

I believe this is the most important bit from the logs:

> autoreconf: error: 'configure.ac' is required

### Notify maintainers

@robbinch 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lqk88hgqkrpxgyvsy6lq0sfy1whxzcdg-hx7g6qly87bhq1mf53gmy2bx9nr10qm2-nixos-unstable-patched`
```

**Comment by jcollie** [comment]
The build log linked above does not seem to be complete. This should be a more complete log: https://pastebin.com/dhscSsFM

**Comment by jfly** [comment]
Oops, thanks @jcollie. I've fixed the gist. For the record, the permissions on your pastebin seem to be wrong, I get this error when I try to view it: "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff."

**Comment by jcollie** [comment]
Hmm not sure what happened there but now that you've updated the gist I don't think that I need to fix the pastebin link.

**Comment by pimeys** [comment]
Happens here too. Can't upgrade beets due to the build failure.

https://gist.github.com/pimeys/3c71f04f36f28131db623ed49ac57cfa

**Comment by MarkRijckenberg** [comment]
Same issue here: output of nix-shell -p nix-info --run "nix-info -m" :
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.5, NixOS, 24.05 (Uakari), 24.05.20231209.666fc80`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by MarkRijckenberg** [comment]
Apparently this issue was mentioned 3 days ago:  https://github.com/NixOS/nixpkgs/pull/271377#issuecomment-1849963438

**Comment by jansol** [comment]
Is there even any more reason for beets to depend on aacgain (nor mp3gain for that matter) since AFAIK the default replaygain backend was changed to ffmpeg? @aszlig @doronbehar @lovesegfault @pjones

**Comment by MarkRijckenberg** [comment]
> Is there even any more reason for beets to depend on aacgain (nor mp3gain for that matter) since AFAIK the default replaygain backend was changed to ffmpeg? @aszlig @doronbehar @lovesegfault @pjones

Adding @jackwilsdon

**Comment by MarkRijckenberg** [comment]
Here is the failed build report from Hydra:
https://hydra.nixos.org/build/243873651
https://cache.nixos.org/log/jdz0bpqbx0lsmwfyi1j5hkv7kynidaih-aacgain-2.0.0.drv

**Comment by doronbehar** [comment]
By observing the aacgain's Nix expression, I think it'd be ideal to make it link to the "system"'s `faad2` and `mp4v2` libraries. Regarding beets, it still supports using aacgain, both in the unstable and stable flavors. If you won't be able to fix the issue and you'd mark it as broken or something, we'll get along without it, I'd only ask you to notify us so we could propose something in the same PR marking it as broken.

**Comment by jackwilsdon** [comment]
The default replaygain backend looks to still be mp3gain/aacgain (depending on which is available):

https://github.com/beetbox/beets/blob/60ad1ba0d2ba9bf117f5dacd798f184e77b881c7/beetsplug/replaygain.py#L1228

https://github.com/beetbox/beets/blob/60ad1ba0d2ba9bf117f5dacd798f184e77b881c7/beetsplug/replaygain.py#L603-L609

**Comment by mt103vps** [comment]
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCCr pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add itsing $NIX_PATH or -I)

       at «none»:0: (source not available)

**Comment by dschrempf** [comment]
@mt103vps , this issue was closed about half a year ago. Could you please open a new issue and provide a bit more context? I just tried building `aacgain` on `nixos-unstable`, and everything worked out fine. Also, `beets-unstable` has been updated recently and works fine here!
