### ISSUE TITLE
nixos.matrix-appservice-irc: systemd hardening breaks ExecStartPre script

### ISSUE THREAD

**Issue by erdnaxe** [NixOS/nixpkgs#273929]
### Describe the bug

After upgrading to NixOS 23.11, I got in the unit logs:
```
line 29:  1254 Bad system call         (core dumped) sed -i "s/^id:.*$/$id/g" /var/lib/matrix-appservice-irc/registration.yml
```
If I remove `/var/lib/matrix-appservice-irc/registration.yml`, then I get:
```
line 32:  1513 Bad system call         (core dumped) chgrp matrix-synapse /var/lib/matrix-appservice-irc/registration.yml
```

### Steps To Reproduce
1. Install matrix-appservice-irc on NixOS 23.05
2. Upgrade to NixOS 23.11

### Expected behavior
The service should start without failing.

### Additional context
This is due to 6ae8e13396ead.
Commit ef477d56771c5 already fixes part of the problem, but it does not seem to fix everything.

Maybe we should add more syscalls to the allowlist?

### Notify maintainers

@mweinelt @Ralith 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@redacted:/etc/nixos]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.66, NixOS, 23.11 (Tapir), 23.11.1697.781e2a9797ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Any audit log statements in `dmesg` that could indicate what specific syscall was used?

**Comment by Ralith** [comment]
Are you sure your channel actually has the backport? What's the contents of the `ExecPreStart` file referred to by `systemctl cat matrix-appservice-irc`?

**Comment by erdnaxe** [comment]
> Any audit log statements in `dmesg` that could indicate what specific syscall was used?

The dmesg logs associated with all the systemctl restart I tried:
```
[    9.205137] audit: type=1326 audit(1702456441.544:2): auid=4294967295 uid=997 gid=998 ses=4294967295 subj=kernel pid=943 comm="sed" exe="/nix/store/9c5qm297qnvwcf7j0gm01qrslbiqz8rs-gnused-4.9/bin/sed" sig=31 arch=c000003e syscall=93 compat=0 ip=0x7f72b68de11b code=0x80000000
[  124.293424] audit: type=1326 audit(1702456557.628:3): auid=4294967295 uid=997 gid=998 ses=4294967295 subj=kernel pid=1254 comm="sed" exe="/nix/store/9c5qm297qnvwcf7j0gm01qrslbiqz8rs-gnused-4.9/bin/sed" sig=31 arch=c000003e syscall=93 compat=0 ip=0x7f0a152bb11b code=0x80000000
[  278.438142] audit: type=1326 audit(1702456711.773:4): auid=4294967295 uid=997 gid=998 ses=4294967295 subj=kernel pid=1427 comm="sed" exe="/nix/store/9c5qm297qnvwcf7j0gm01qrslbiqz8rs-gnused-4.9/bin/sed" sig=31 arch=c000003e syscall=93 compat=0 ip=0x7f54536fb11b code=0x80000000
[  303.530099] audit: type=1326 audit(1702456736.865:5): auid=4294967295 uid=997 gid=998 ses=4294967295 subj=kernel pid=1513 comm="chgrp" exe="/nix/store/bblyj5b3ii8n6v4ra0nb37cmi3lf8rz9-coreutils-9.3/bin/coreutils" sig=31 arch=c000003e syscall=260 compat=0 ip=0x7f10b156b14e code=0x80000000
```

syscall=93 and syscall=260 seems blocked.

> Are you sure your channel actually has the backport?

Yes, I am using NixOS 23.11 channel (updated yesterday). `./nixos/modules/services/matrix/appservice-irc.nix` contains:
```
        SystemCallFilter = [
          "@system-service @pkey @chown"
          "~@privileged @resources"
        ];
```

**Comment by Ralith** [comment]
That's fchown and fchownat. Weird.

**Comment by mweinelt** [comment]
Please check `systemctl show -P SystemCallFilter matrix-appservice.irc` on the machine where this breaks.

**Comment by ntninja** [comment]
@mweinelt: On an affected system, I don’t see `chown`/`fchown` in the list returned by the command you posted unless I remove `~@privileged` from the `SystemCallFilter` setting in the service file. Correspondingly `systemd-analyze syscall-filter` lists `@chown` as being part of the `@privileged` set (which kinda makes sense if you think about it).

System configuration:
  * Linux 5.10.120-xen (provided by hosting company)
  * NixOS 23.11
  * systemd 254.6
 
This service configuration works though:

```
SystemCallFilter=@system-service @pkey
SystemCallFilter=~@privileged @resources
SystemCallFilter=@chown
```

**Comment by tcheneau** [comment]
Thank you @ntninja.

I applied the following workaround in the meantime (sharing it because the following syntax was a bit foreign to me before):
```nix
  systemd.services.matrix-appservice-irc.serviceConfig = {
      SystemCallFilter= [ "@system-service @pkey"
                          "~@privileged @resources"
                          "@chown" ];
  };
```
