### ISSUE TITLE
Window Maker visual bugs

### ISSUE THREAD

**Issue by Gabryx64** [NixOS/nixpkgs#273971]
### Describe the bug
When started, the workspace button's background is a solid gray panel without the icon, the dock icon is a black square.
After restarting Window Maker from the button in the menu, both icons become the color of the square of the wallpaper behind the dock icon.

### Steps To Reproduce
1. Start Window Maker.

### Expected behavior
The squares should have icons and be the color of the gradient of the other icons.

#### Before Window Maker restart:
![bug1](https://github.com/NixOS/nixpkgs/assets/67575864/817d4371-4a27-4bc5-9fad-dc2efe216e99)
#### After Window Maker restart:
![bug0](https://github.com/NixOS/nixpkgs/assets/67575864/11aab034-b118-4295-883a-18ecc94c0971)

### Additional context
When I first switched to nixos-unstable this didn't happen, but after a day or so this bug appeared.

### Notify maintainers
@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(gabry): `""`
 - channels(root): `"nix-snapd, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by AndersonTorres** [comment]
I was using windowmaker with this bug until a week ago. However I can't imagine how to track it down.

**Comment by Gabryx64** [comment]
Still after updating the bug persists.

**Comment by Gabryx64** [comment]
Ok in the end, some files where deleted somehow, and those were the icons used by those icons,  so replacing them was the solution.

**Comment by AndersonTorres** [comment]
I believe the programs hardcode their first use directory paths.
