### ISSUE TITLE
Build failure: iwd on aarch64-linux

### ISSUE THREAD

**Issue by adtya** [NixOS/nixpkgs#273958]
### Steps To Reproduce

1. build *iwd* *2.10* from latest nixos-unstable on aarch64-linux

### Build log
https://gist.github.com/adtya/6929cbcde520d00253522d2b5264a949

### Additional context
The build is successful on x86_64-linux but is failing on aarch64-linux

### Notify maintainers
@dtzWill @fpletz @amaxine

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 24.05 (Uakari), 24.05.20231209.666fc80`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyssais** [comment]
Presumably fixed by https://github.com/NixOS/nixpkgs/pull/273644.  LMK if not.
