### ISSUE TITLE
staging: fetchurl failures

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#27406]
I don't know exact reason yet, but `fetchurl` derivations on staging now most often fail, even though everything looks like success.

My preliminary looking bounded the problem into 706f0c3849..1ebb059932; I suspect some return code on changes in stdenv's setup.sh, but it's partially just a hunch.  /cc @Ericson2314 in case of immediate idea what's wrong.

**Comment by Ericson2314** [comment]
`1ebb059` is only a breaking change because `configureFlags` now defaults to `[]` instead of being unset when not cross compiling. That would correspond to an empty environment variable being defined.

I assume that would not adversely impact anything, but I could be wrong?

**Comment by vcunat** [comment]
Well, there's a slight problem in that particular commit, as it doesn't count on `configureFlags` being `null` and some other that I couldn't solve immediately, but the `fetchurl` problems bother me much more (now reproduced by Hydra as well).  It's possible my (partial) bisection got off at some point, as it's possibly not completely deterministic failure...

**Comment by Ericson2314** [comment]
@vcunat Oh you mean if `configureFlags` is manually passed in as `null`?

This isn't in Darwin by any chance is it? @luigy and I were fixing a problem where too long argvs to `mv` called a problem in `fetchzip` on that platform. I don't think `fetchurl` would have a similar issue, but just throwing it out there.

**Comment by vcunat** [comment]
It's sometimes done conditionally `= if something then foo else null;`, as adding `null` vars used not to change the derivation hash...

**Comment by Ericson2314** [comment]
@vcunat True. Sorry for that. I'll fix it.

**Comment by vcunat** [comment]
Building the tarball reveals some other problem as well, possibly related.

**Comment by Ericson2314** [comment]
bootstrapp tools? Wanna head to IRC?

**Comment by vcunat** [comment]
@Ericson2314: OK.

**Comment by ttuegel** [comment]
I have fixes for some of the other problems in `staging`, but not this.

What is the fastest way to resolve this? The unstable channel is blocked on `master`, which is broken pending a mass-rebuild patch I need from `staging`, i.e. the unstable channel is blocked on `staging`.

**Comment by ttuegel** [comment]
I have bisected the problem down to
```
commit 5d4efb2c816d2143f29cad8153faad1686557b2a
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Tue Jul 11 20:23:06 2017 -0400

    stdenv-setup: Misc improvements as directed by ShellCheck
    
    I took some liberties with the flags-echoing code to make it more
    concise and correct. Also, a few warnings in findInputs and friends I
    skipped because I am going to rewrite those anyways.
    
    Thanks @grahamc for telling me about this great linter!
```
Bisecting this is particularly difficult; you must disable substitutes (`build-use-substitutes = false`) and collect garbage between each run because the results are fixed-output.

**Comment by ttuegel** [comment]
This will be fixed by #27522.

**Comment by Ericson2314** [comment]
@ttuegel's fix is merged; @edolstra removed the logging stuff that caused this problem entirely; and I merged master into staging, so I think this is quite fixed.

**Comment by vcunat** [comment]
Thank you!
