### ISSUE TITLE
NixOS-17.03: mathematica 11.0.1 broken

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#27401]
## Issue description
Mathematica fails to start.

### Steps to reproduce
`$ nix-env -i mathematica`
....
`$ mathematica`
`/nix/store/g7nd2syi8fdd1hf0kx3bsivmiasws3jj-mathematica-11.0.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: /nix/store/g7nd2syi8fdd1hf0kx3bsivmiasws3jj-mathematica-11.0.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/libz.so.1: version 'ZLIB_1.2.9' not found (required by /nix/store/12sh2w6gq9wg6fhj0dbpd2g3qmp65nl8-libpng-apng-1.6.28/lib/libpng16.so.16)`

## Technical details

* System: NixOS: 17.03.1517.849b5a5193 (Gorilla)
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1517.849b5a5193
* Sandboxing enabled: no

**Comment by FRidh** [comment]
Similar issue in #23960.
