### ISSUE TITLE
Factorio alpha hash on master appears to be wrong.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#27411]
## Issue description
This command (if you replace the credentials):
`nix-shell -I nixpkgs=https://api.github.com/repos/NixOS/nixpkgs-channels/tarball/a72c1e4e1c1f9974f9dec18cfa8f7359a4a47685 -p 'factorio.override{releaseType="alpha";username="<USERNAME>";password="<PASSWORD>";}' --command factorio`
Fails with this error:
`output path ‘/nix/store/1xifp4djl497nfbpwh2c1psd68rw9ndm-factorio_alpha_x64-0.15.26.tar.xz’ has sha256 hash ‘0cm6n1680hmp9mh5xdpd2iv8wpfcfv6w14j6xgmvq300f5rszy51’ when ‘0g7k58h15q4n9wxf96rx72w340xpdbj8k1faaxixrfrfx8bnmsls’ was expected`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03.1517.849b5a5193 (Gorilla)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.11`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

**Comment by joachifm** [comment]
cc @elitak

**Comment by elitak** [comment]
It definitely built and ran for me, at the time; possibly the file changed upstream. I will just update this to 0.15.30 right now.

**Comment by elitak** [comment]
Turns out the file was just 404 upstream. Maybe they removed it because it was buggy/unstable. In any case, the fetch code needs to be revised because it does not handle 404 appropriately, like the basic fetchurl does. I will make a separate PR for that in the future. For now, I'll just bump to the available 0.15.30.

**Comment by joachifm** [comment]
I take it the bump fixed the issue.

**Comment by joachifm** [comment]
I picked the factorio updates to the release branch as well.

**Comment by elitak** [comment]
Good call, thanks.

In the future, I'll try to predict which of Factorio's "experimental" releases are going to be permanently hosted, before updating the hashes. I'll email them to inquire about the disappearing builds, too.
