### ISSUE TITLE
Current linuxPackages_rt_6_1 kernel has ext4 corruption bug

### ISSUE THREAD

**Issue by stelcodes** [NixOS/nixpkgs#274136]
### Describe the bug
I believe the current `linuxPackage_rt_6_1` kernel has the [nasty ext4 corruption bug]() since it was built from `6.1.65`. This bug was fixed in `6.1.66`.

Source: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/linux-rt-6.1.nix
Tracking issue for kernel bug: #273375

### Steps To Reproduce

1. Check `pkgs.linuxPackages_rt_6_1.kernel.version`

### Expected behavior
No ext4 corruption.

### Screenshots
N/A

### Notify maintainers
Maybe @K900 ?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.66, NixOS, 23.11 (Tapir), 23.11.20231210.781e2a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - channels(stel): `""`
 - nixpkgs: `/nix/store/z0513hax0dsbix0x89wr7fca8sa99sxc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
I am definitely not the maintainer for the -rt kernels.

**Comment by stelcodes** [comment]
@K900 Looks like you authored the last 5 commits on [the derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/linux-rt-6.1.nix). Should I just run the update script and send a PR?

**Comment by K900** [comment]
Those are automated. You can run the update script, but note that 6.1.66 has another, different regression, though a less severe one, so ideally we'd want a new upstream release for 6.1.6_7_.

**Comment by samueldr** [comment]
Assumed resolved, in the 4 months since this was opened. We're quite diligent with getting updates in.

If this isn't please re-open and add details about what is missing.
