### ISSUE TITLE
Update request: trunk 0.17.2 → 0.18.0

### ISSUE THREAD

**Issue by v-kat** [NixOS/nixpkgs#274133]
Package name: trunk

Latest released version: 0.18.0

Current version on the unstable channel: 0.17.2

Current version on the stable/release channel: 0.17.2

Checked the nixpkgs pull requests

It's a big release since 0.17.2 and adds a lot of new features including an `--offline` flag which is helpful for nix

@freezeboy
Note for maintainers: Please tag this issue in your PR.

**Comment by kirillrdy** [comment]
there was PR created before this issue https://github.com/NixOS/nixpkgs/pull/273792

maybe because PR title doesn't match contribution guidelines it was't found

**Comment by v-kat** [comment]
Yeah. Sorry about that. I missed it.

**Comment by kirillrdy** [comment]
it's ok, no harm done :-)

**Comment by v-kat** [comment]
Do you know how to remove a package?
I believe trunk-ng will get deprecated now.

**Comment by kirillrdy** [comment]
> Do you know how to remove a package? I believe trunk-ng will get deprecated now.

yes, I've recently removed a package https://github.com/NixOS/nixpkgs/pull/271569

as for trunk-ng, I can't see anywhere that is has been deprecated yet
