### ISSUE TITLE
nixos-unstable channel not updating

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#27429]
https://howoldis.herokuapp.com shows a channel, 10 days old.
http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents shows a successful build 3 days ago, which is http://hydra.nixos.org/build/56231260

(Sorry, I know too little about hydra to diagnose this further.)

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/27381

**Comment by vcunat** [comment]
To be clear, I'm confident there is some other reasons why the channel doesn't update ATM, but Hydra's UI won't show why.
