### ISSUE TITLE
nixos/frr: staticd does not accept -f anymore in frr-9

### ISSUE THREAD

**Issue by woffs** [NixOS/nixpkgs#274286]
### Describe the bug
using frr-9.0.1 from nixos-23.11 results in failure of staticd.service:

`/nix/store/blgvhysfkq43jsv5p0yzmqn4j0q6aqd5-frr-9.0.1/libexec/frr/staticd: invalid option -- 'f'`

### Steps To Reproduce
services.frr.static.enable = true
systemctl status staticd

### Expected behavior
staticd used to work with `-f configfile` option

### Additional context
see
- https://github.com/FRRouting/frr/issues/14040
- https://docs.frrouting.org/en/latest/mgmtd.html
- https://github.com/FRRouting/frr/blob/master/doc/developer/mgmtd-dev.rst

Quick fix see below.

maybe @mweinelt / @thillux want to insert themselves kindly into maintainers :-)

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 23.11 (Tapir), 23.11.20231212.cf28ee2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(fd): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/dg2g5qwvs36dhfqj9khx4sfv0klwl9f0-source`

**Comment by mweinelt** [comment]
No, sorry. I'm a BIRD user, and I like it that way. Me writing that test and getting FRR over the finish line was some morbid curiosity.

**Comment by woffs** [comment]
Thanks even more @mweinelt for contributing!

My quickfix for this issue is so far
```
services.frr.mgmt.enable = true;
environment.etc."frr/staticd.conf".text = config.services.frr.static.config;
systemd.services.staticd.serviceConfig.ExecStart = lib.mkForce "${pkgs.frr}/libexec/frr/staticd -A localhost";
```
It seems, config file location with mgmtd is now staticd.conf instead of static.conf. mgmtd is needed for staticd to get configured.

**Comment by thillux** [comment]
https://github.com/FRRouting/frr/blob/master/doc/user/static.rst also mentions staticd.conf.

**Comment by woffs** [comment]
yes, all daemons have `${service}d.conf` as default config file, I'll try to adapt the nixos service accordingly to get rid of `-f` in all service definitions.

**Comment by thillux** [comment]
Please also test with: #274314 (should not have changed this).
