### ISSUE TITLE
Not able to start X, unknown host?

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#27425]
## Issue description
`startx` produces an error of: 
```
hostname: Unknown host
xauth: file /home/demo/.serverauth.2821 does not exist
```

### Steps to reproduce
Using the minimal virtualbox image. 
```
services.xserver.enable = true;
services.xserver.desktopManager.xfce.enable = true;
services.xserver.videoDrivers = mkOverride 40 [ "virtualbox" , "vmware", "cirrus", "vesa", "modesetting"]
```

nix-env -i xinit
sudo nixos-rebuild-switch

## Technical details

nixos-version: 16.09.773.b8ede35
nix-env --version: nix-env (Nix) 1.11.4
build-use-sandbox = false

**Comment by joachifm** [comment]
16.09 is pretty old at this point, not sure if anybody is working on maintaining it.

**Comment by chrissound** [comment]
Is it possible to upgrade?

**Comment by chrissound** [comment]
So adding the 17.03 channel, and doing a `nixos-rebuild switch --upgrade` gives me a symlink error.

Doing it with sudo completes successfully but it seems to return instantaneously so I doubt it's done anything.

Think I'll just download the latest version.

**Comment by vcunat** [comment]
@chrissound: you of course need root privileges to perform the final step of the upgrade.  Still, basically all the work is doable as non-root and should get reused, so I think you possibly did upgrade successfully.
