### ISSUE TITLE
Update request:  ungoogled-chromium 120.0.6099.109-1

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#274302]
- Package name: Ungoogled Chromium
- Latest released version:  120.0.6099.71
-  Search your package here: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/networking/browsers/chromium/browser.nix#L76
- Current version on the unstable channel: Version 120.0.6099.71
- Current version on the stable/release channel: Version 120.0.6099.71

**Notify maintainers**
@squalus 
@primeos 
@michaeladler 
@networkException 
@emilylange 
-----

**Comment by networkException** [comment]
Please actually check for existing pull requests and not just edit the checkbox away from the template.

This is already being worked on in #274298
