### ISSUE TITLE
systemd-in-initrd: systemd-makefs only added if autoFormat = yes

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#274310]
### Describe the bug
`nixos/modules/system/boot/systemd/initrd.nix` currently has a conditional:

```
(lib.mkIf needMakefs "${cfg.package}/lib/systemd/systemd-makefs")
```

`needMakefs` is defined as this:
```
needMakefs = lib.any (fs: fs.autoFormat) fileSystems;
```

However, this is only one part of the picture. I can also add the `x-systemd.makefs` option to a `fileSystems` entry to cause a dependency on `systemd-makefs@some-device-path.service` (or just do it explicitly by `requires`).

~`systemd-growfs` is also missing entirely~ dealt with online in stage 2

### Expected behavior
I think we should ship `systemd-makefs` by default with systemd-in-initrd.

### Notify maintainers

@ElvishJerricco 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ElvishJerricco** [comment]
@flokli This is intentional: https://github.com/NixOS/nixpkgs/pull/234877

systemd-growfs is an online operation. We do it during stage 2 when `autoResize` is enabled.

**Comment by flokli** [comment]
> @flokli This is intentional: #234877
> 
> systemd-growfs is an online operation. We do it during stage 2 when `autoResize` is enabled.

Makes sense, and I even reviewed this PR :laughing: sorry.

> oh, but I see, you're saying we should add `makefs` in case users add the fstab option themselves and don't use the `autoFormat` NixOS option. I think that makes sense. The point of the previous comment stands though; growfs is intentionally not in stage 1.

Yes, in case the fstab options contain `x-systemd.makefs` we should also `needMakefs`.

**Comment by flokli** [comment]
PR up at https://github.com/NixOS/nixpkgs/pull/275340.
