### ISSUE TITLE
openlilypond-font-lilyjazz doesn't install supplementary fonts due to incorrect directory name

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#274329]
### Describe the bug
The installation script looks in `supplementary-fonts` subdirectory (https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/lilypond/fonts.nix#L20) but lilyjazz uses `supplementary-files` instead: https://github.com/OpenLilyPondFonts/lilyjazz/tree/master/supplementary-files. As a result the additional fonts are not installed. In addition, there are also stylesheets and examples which would be useful to have.

### Steps To Reproduce
Install `lilypond-unstable-with-fonts`.

### Expected behavior
All fonts in lilyjazz directory are installed.

### Notify maintainers
@Stunkymonkey 
@yurrriq 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.133.1-microsoft-standard-WSL2, NixOS, 23.11 (Tapir), 23.11.20231205.a804fc8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/channels/nixpkgs`

**Comment by yurrriq** [comment]
Thanks for the report. Might you be willing and able to open a PR to fix it?
