### ISSUE TITLE
GNOME extensions Requiring GTop 

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#274325]
**I am using Gnome 45.2 on NixOS 23.11.**
I use both Wayland & Xorg!

Many GNOME extensions are not working and show the following error:

`Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found`

I tried installing "pkgs.gtop" but this did not help :(

**Comment by donovanglover** [comment]
Try the solution given here: https://github.com/fflewddur/tophat/issues/106#issuecomment-1848319826

**Comment by boustanihani** [comment]
> Try the solution given here: [fflewddur/tophat#106 (comment)](https://github.com/fflewddur/tophat/issues/106#issuecomment-1848319826)

Thanks, this fixed the Problem :)
