### ISSUE TITLE
fetchzip fails on darwin with "mv: Argument list too long"

### ISSUE THREAD

**Issue by luigy** [NixOS/nixpkgs#27448]
## Issue description

`all-cabal-hashes` fails to build on darwin caused by `fetchzip` [here](https://github.com/NixOS/nixpkgs/blob/8253fc2ae56e089fe086942671f9e84c431f2277/pkgs/build-support/fetchzip/default.nix#L48)

```
$ nix-build
building path(s) '/nix/store/8zv0x5px0avmls8za4c01z0m2vzdznlz-all-cabal-hashes-2fad9af969f606e48b3cc38f0dcbbd0c90260c78-src'

trying https://github.com/commercialhaskell/all-cabal-hashes/archive/2fad9af969f606e48b3cc38f0dcbbd0c90260c78.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   176    0   176    0     0    656      0 --:--:-- --:--:-- --:--:--   715
100 38.1M  100 38.1M    0     0  16.1M      0  0:00:02  0:00:02 --:--:-- 19.9M
unpacking source archive /private/var/folders/ns/079m674170vc46by2mp375lc0000gn/T/nix-build-all-cabal-hashes-2fad9af969f606e48b3cc38f0dcbbd0c90260c78-src.drv-0/2fad9af969f606e48b3cc38f0dcbbd0c90260c78.tar.gz
/nix/store/vxkkd6fq44hdcb4cyrw1wi1bly5nkmcs-stdenv-darwin/setup: line 92: /nix/store/qdh0p9v415741fi3i9lxvl598k43zll2-coreutils-8.27/bin/mv: Argument list too long
builder for '/nix/store/wmrzb3grpxlrln02g9qsnd8r3fl4h97l-all-cabal-hashes-2fad9af969f606e48b3cc38f0dcbbd0c90260c78-src.drv' failed with exit code 126
cannot build derivation '/nix/store/0k0ws0a7j2ajz7y7sjgl036gd8sa9f86-cabal2nix-constraints-0.8.drv': 1 dependencies couldn't be built
error: build of '/nix/store/0k0ws0a7j2ajz7y7sjgl036gd8sa9f86-cabal2nix-constraints-0.8.drv' failed
(use '--show-trace' to show detailed location information)
```

## Technical details

* System: `Darwin machost 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64 i386 iMac14,2 Darwin`
* Nix version: `nix-env (Nix) 1.11.12`
* Nixpkgs version: `17.09pre110532.50831d543d`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by hamishmack** [comment]
This did not seem to fix it for me.  I get a different error now.  Is there something else I have to do?

I am using [nixpkgs via this](https://github.com/reflex-frp/reflex-platform/blob/8c87f33461c9c5c11f50b79f322f8d649ca04836/nixpkgs/github.json), but I also tried [this](https://github.com/reflex-frp/reflex-platform/blob/93f5e9cbb471868769d176506ef2e877f3239027/nixpkgs/github.json).

```
unpacking source archive /private/var/folders/fg/y5gns8p14ggc90xrdwy30d2h0000gn/T/nix-build-all-cabal-hashes-adb039bba3bb46941c3ee08bdd68f25bf2aa5c60-src.drv-0/adb039bba3bb46941c3ee08bdd68f25bf2aa5c60.tar.gz
output path ‘/nix/store/c0qm53x7lp1y76a90ffj8wb5h114wvsh-all-cabal-hashes-adb039bba3bb46941c3ee08bdd68f25bf2aa5c60-src’ has r:sha256 hash ‘10ydg8cszxyaqml4kias205xnxrq2zx3ja2md1ni3fnwbff6c67q’ when ‘0mjkrbifag39gm153v5wn555jq7ckwn8s3f1wwsdw67wmql4gcn7’ was expected
cannot build derivation ‘/nix/store/jmryxnaxsl2ys5pbq8q3xk2i8szfc7h0-cabal2nix-constraints-0.9.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jmryxnaxsl2ys5pbq8q3xk2i8szfc7h0-cabal2nix-constraints-0.9.drv’ failed
```

**Comment by shlevy** [comment]
@hamishmack This is likely due to a case-insensitive filesystem, as there are hackage packages (in particular, `comapactable` and `Compactable`) that are indistinguishable on such filesystems and thus cause a hash conflict relative to linux or a case-sensitive darwin fs

**Comment by hamishmack** [comment]
It seams like this issue breaks anything that uses `callCabal2nix`.   Is there a work around for this?  I'm using a NixOS VM for now, but I would much prefer to be able to use macOS.

Could we use `zip -d` to delete one of the offending files from the zip file before we unpack it?

**Comment by shlevy** [comment]
You could write your own version of `all-cabal-hashes` that uses a modified `fetchZip` to remove one of the bad files, but the only long term solution is to put your store on a case sensitive volume and disable the case hack (`use-case-hack = false` in nix.conf)

**Comment by ElvishJerricco** [comment]
@shlevy or prefix the clashing names with some kind of identifying hash.
