### ISSUE TITLE
Heroku CLI is deprecated and now non-functioning

### ISSUE THREAD

**Issue by DCPRevere** [NixOS/nixpkgs#27447]
## Issue description
The Heroku CLI is returning HTTP 410 in response to login attempts, preventing all use of the Heroku platform.
This is inline with their deprecation notice here: https://devcenter.heroku.com/changelog-items/1147
A WIP PR for this can be found here: https://github.com/NixOS/nixpkgs/pull/25983

### Steps to reproduce
Add heroku to your installed packages.

```
> heroku --version
heroku-toolbelt/3.43.16 (x86_64-linux) ruby/2.3.3
heroku-cli/dev (linux-amd64) go1.7.4 ?
You have no installed plugins.
```

The presence of `ruby/2.3.3` indicates that we are using the legacy client.

```
> heroku login
Enter your Heroku credentials.
Email: <REDACTED>
Password (typing will be hidden): 
 ▸    HTTP Error: https://api.heroku.com/login 410 Gone
 ▸    Invalid response from API.
 ▸    HTTP 410
 ▸    {<REDACTED>}
 ▸    
 ▸    Are you behind a proxy?
 ▸    https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy
```

## Technical details

- System: 17.03.1203.58e227052d (Gorilla)
- Nix version: nix-env (Nix) 1.11.8
- Nixpkgs version: "17.03.1203.58e227052d"
- Sandboxing enabled: build-use-sandbox = false

**Comment by FRidh** [comment]
Thanks for reporting. I've marked the package as broken in https://github.com/NixOS/nixpkgs/commit/f59e71e9c7a41618908fbab1f7517fd3af2c6855. I'm closing this now since for getting this to work we don't need this issue, just the PR.
