### ISSUE TITLE
Build failure: python39Full on nixos-23.11 channel (caused by Sphinx)

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#274427]
### Steps To Reproduce

My particular steps to reproduce the behavior:
1. setup a flake-based NixOS with nixos-23.11 channel at `cf28ee258fd5f9a52de6b9865cdb93a1f96d09b7`
2. add `python39Full` to `environment.systemPackages`
3. `nixos-rebuild build`

### Build log

https://gist.github.com/chekoopa/1342eaca95c86dfe94252ff6d790fd2b

### Additional context

`python311Full` builds like usual.

### Notify maintainers

Pinging all the Python maintainer group (because I'm not sure which one). @fridh @hexa @jonringer @tjni

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.0, NixOS, 23.05 (Stoat), 23.05.20231101.34bdaaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
@chekoopa I've tried cf28ee258fd5f9a52de6b9865cdb93a1f96d09b7

```
nix-build -A python39Full
/nix/store/6x7ig69vjjm1fziicgy37crgmqm01y1m-python3-3.9.18
```

I see from your build logs derivation hash is different, is it possible you have something in your overlays?

also where did you get python maintainers list? hexa's github username is @mweinelt ( it's possible that just needs to be updated )

**Comment by mweinelt** [comment]
Cannot reproduce, likely a downstream issue as pointed out by kirillrdy.
