### ISSUE TITLE
Nginx module doesn't support vhosts on both regular and ssl

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#27442]
## Issue description

When, on a vhost, you specify `enableAcme` but not `forceSSL`, the HTTP server won't have the vhost defined and the ACME challenge will fail. `enableAcme` only works with `forceSSL`.

In general, vhosts have no way to be both on and off SSL, you need to double the specification.

I propose that vhosts can be either http-only (default), https-only (current `enableSSL`), http+https (not possible) or http=>https (`forceSSL`). I think `enableSSL` should be http+https, and for https-only you should also specify e.g. `sslOnly`.

Furthermore, `enableAcme` should work with `enableSSL` (and complain if neither is set).

### Steps to reproduce

Create a vhost with enableSSL true and enableAcme true.

## Technical details

* System: NixOS: 17.03

/cc @globin @fadenb @rnhmjoj - thoughts?

**Comment by rnhmjoj** [comment]
This is basically what #27426 does. Could you test if ACME works with `addSSL`?

**Comment by michaelpj** [comment]
Also see https://github.com/NixOS/nixpkgs/issues/27338

**Comment by wmertens** [comment]
Closed via #27426
