### ISSUE TITLE
gpu-burn: upkeep

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#274428]
## Issue description

Follow-up to https://github.com/NixOS/nixpkgs/pull/274252

- [ ] The package should stop using `cudaPackages.cudatoolkit`
- [x] The package is missing `meta.mainProgram` and the binary name (`gpu_burn`) doesn't match the attribute name (`gpu-burn`), breaking `nix3-run`

**Comment by de11n** [comment]
I began work getting rid of `cudatoolkit` here: https://github.com/NixOS/nixpkgs/pull/249554

**Comment by tomodachi94** [comment]
Looks like the missing `mainProgram` was resolved by #287915.
