### ISSUE TITLE
Update request: bitwig-studio 5.0.11 → 5.1

### ISSUE THREAD

**Issue by Herschenglime** [NixOS/nixpkgs#274657]
- Package name: bitwig-studio
- Latest released version: 5.1

- Current version on the unstable channel: 5.0.11
- Current version on the stable/release channel: 5.0.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bfortz 
@michalrus 
@mrVanDalo 

# Important note about version change/upgrade plan
Since this is a 5.1 release, users of any of the 5.0 releases would need an active upgrade plan to actually be able to use this package ([source](https://www.bitwig.com/support/shop_license_activation/how-does-the-12-month-upgrade-plan-work-5/)). 

I think the best course of action would be to make the `bitwig-studio` package point to the newer version (perhaps at `bitwig_studio5_1`?) and offer a separate `bitwig-studio5_0` package or something similar to users who don't have an active upgrade license but still have access to version 5. How would you normally handle this?

I tested locally and it works fine by just bumping the version and checksum. For now, I'm just using an overlay to get the newer package version, but I'd be happy to make the changes required to the package and do any version splitting pending maintainer guidance.

Thanks!

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bfortz** [comment]
So far, we only made a separate derivative for new versions for major upgrades, I think we can wait until 6 comes out to make bitwig-studio6 unless we have some complaints. (I'm assuming here a vast majority of users have an active upgrade plan).

**Comment by bfortz** [comment]
Pull request for version bump here: #275012
