### ISSUE TITLE
gnomeExtensions.tophat reports GTop not found on nixos-unstable channel

### ISSUE THREAD

**Issue by pokon548** [NixOS/nixpkgs#274659]
### Describe the bug
When I trying to use this extension on ```nixos-unstable``` channel, it reports:
```
Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
```

Already tried workaround: https://github.com/fflewddur/tophat/issues/106#issuecomment-1848319826, but it still cause same error.

### Steps To Reproduce
1. Install gnomeExtensions.tophat
2. Logout and login to gnome-shell
3. tophat will not working and report error

### Expected behavior
```gnomeExtensions.tophat``` should not report any error and display correct status on topbar

### Screenshots
![图片](https://github.com/NixOS/nixpkgs/assets/65808665/51acfe2c-6575-47cb-aa95-09d09f53d61b)

### Additional context
There is indeed a related patch for this extension: https://github.com/NixOS/nixpkgs/blob/3dda6d5ed56af34534dd4cdcdd85627df25aec55/pkgs/desktops/gnome/extensions/extensionOverrides.nix#L122C1-L129C6, but for some reason it is not working on unstable channel. Not sure for the cause.

### Notify maintainers

@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.6, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
There is a PR to fix it properly but it will require rebase onto GNOMR 45: https://github.com/NixOS/nixpkgs/pull/267160
