### ISSUE TITLE
Build failure: nixosTests.podman

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#274655]
See e.g. https://hydra.nixos.org/build/244332751

Note that this blocks the `nixos-unstable` channel.

### Notify maintainers

@adisbladis @saschagrunert @vdemeester

**Comment by kirillrdy** [comment]
bisected to 

```
5cb7e6505c881f10ac36e17cf7f6e0366392b4e8 is the first bad commit
commit 5cb7e6505c881f10ac36e17cf7f6e0366392b4e8
Author: R. Ryantm <ryantm-bot@ryantm.com>
Date:   Fri Dec 15 06:32:06 2023 +0000

    conmon: 2.1.8 -> 2.1.9

 pkgs/applications/virtualization/conmon/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

```

**Comment by adisbladis** [comment]
Bisected to upstream commit https://github.com/containers/conmon/commit/6d88cb3672a3dceeb4b045a92dc4d4285c9f4efd.
Not sure what to make of that though..

**Comment by vcunat** [comment]
PR merged, I'll trust that this is fixed now.
