### ISSUE TITLE
KDE plasma broken on master

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#27461]
## Issue description
KDE is broken with various things not found.
You do get logged in but can only see taskbar and cannot start any applications.

Reverting to https://github.com/NixOS/nixpkgs/commit/f93050e509ff9df866f5f53343fbd8967ac8144d makes the problem go away, so I'm assuming https://github.com/NixOS/nixpkgs/commit/0eb4f6fd2547442d8c51f73d4fe11225951ee663 broke something but I'm not clear on what.

See attached log [kde-attachment.txt](https://github.com/NixOS/nixpkgs/files/1154464/kde-attachment.txt)

### Steps to reproduce
In configuration.nix:
```
displayManager.sddm = {
  enable = true;
  autoLogin = {
   enable = true;
    user = "adisbladis";
  };
};
desktopManager.plasma5.enable = true;
```
`nixos-rebuild switch && reboot`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.09.git.f93050e509 (Hummingbird)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.12`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.09.git.1d78df2729"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

cc @ttuegel

**Comment by FRidh** [comment]
That's likely https://github.com/NixOS/nixpkgs/commit/3cb745d5a69018829ac15f7d5a508135f6bda123. It changed the form of `nix/propagated-user-env-packages`. Should be fixed by https://github.com/NixOS/nixpkgs/pull/27427. It will likely take some days before it ends up in master.

**Comment by ttuegel** [comment]
Yes, this is fixed by #27427 which is not yet in `master`. AFAIK the broken commits will not make it into the unstable channel because of failing tests, so that should be a safe alternative in the mean time.

**Comment by adisbladis** [comment]
Can confirm https://github.com/NixOS/nixpkgs/pull/27427 fixes this.

**Comment by peterhoeg** [comment]
KDE on latest unstable today is perfectly fine here.

**Comment by adisbladis** [comment]
Since https://github.com/NixOS/nixpkgs/commit/b087618ac06256cb3c06278e7eaba45841f4ea91 this builds fine. I'm personally running this one + all my other qt/kde related PRs and it's working great.

**Comment by peterhoeg** [comment]
Closing this as the original reporter confirms all is good.
