### ISSUE TITLE
ZnapZend doesn't start

### ISSUE THREAD

**Issue by johnramsden** [NixOS/nixpkgs#27471]
## Issue description

ZnapZend doesn't start on boot despite being enabled. 

```
● znapzend.service - ZnapZend - ZFS Backup System
   Loaded: loaded (/nix/store/fpj2vhcbcxk38w57nfvn0bn5dna312is-unit-znapzend.service/znapzend.service; link
   Active: inactive (dead)
```

There was a [recent pull request](https://github.com/NixOS/nixpkgs/pull/25802) that was supposed to to fix this problem, after [cherry picking it](https://github.com/johnramsden/nixpkgs/commit/e5c4b3f792a9b065ca16fc768fa35b19967387a6) into my nixpkgs channel, [my ZnapZend](https://github.com/johnramsden/nixos) still doesn't start on boot.

### Steps to reproduce

Use 17.03 release and enable ZnapZend.
Cherry pick [pr fix](https://github.com/johnramsden/nixpkgs/commit/e5c4b3f792a9b065ca16fc768fa35b19967387a6) 

## Technical details

* System: (NixOS: 17.03.git.e5c4b3f792 (Gorilla))
* Nix version: (nix-env (Nix) 1.11.11)
* Nixpkgs version: ("17.03.git.e5c4b3f792")
* Sandboxing enabled: (true)

**Comment by FRidh** [comment]
cc @dermetfan

**Comment by dermetfan** [comment]
I was able to reproduce this but cannot say what the cause is, will investigate further.

**Comment by Mic92** [comment]
I can no longer reproduce that:

```
● znapzend.service - ZnapZend - ZFS Backup System
   Loaded: loaded (/nix/store/sxapwangwkqs0w9v1qfjy0m6jskg12vh-unit-znapzend.service/znapzend.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-08-31 09:53:10 BST; 21s ago
 Main PID: 13071 (znapzend)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/znapzend.service
           └─13071 /nix/store/vmgc26w7k96wsdiwczif158873ylp7g4-perl-5.24.1/bin/perl -I/nix/store/9g5p34q9pbzrhdrzf8dnq6m3gl4ncwdx-perl-Test-Ha /nix/store/lfma1ja8847097ml70p
Aug 31 09:53:10 turingmachine systemd[1]: Started ZnapZend - ZFS Backup System.
Aug 31 09:53:10 turingmachine znapzend[13071]: znapzend (PID=13071) starting up ...
Aug 31 09:53:10 turingmachine znapzend[13071]: refreshing backup plans...
Aug 31 09:53:10 turingmachine znapzend[13071]: No backup set defined or enabled, yet. run 'znapzendzetup' to setup znapzend
Aug 31 09:53:10 turingmachine znapzend[13071]: znapzend (PID=13071) initialized -- resuming normal operations.
```

**Comment by dermetfan** [comment]
@johnramsden It seems you made a mistake cherry-picking the fix.

PR [#25802](https://github.com/NixOS/nixpkgs/pull/25802/files) configures the service with `wantedBy` but your [cherry-pick](https://github.com/johnramsden/nixpkgs/commit/e5c4b3f792a9b065ca16fc768fa35b19967387a6) does not contain that line:

```diff
diff --git a/nixos/modules/services/backup/znapzend.nix b/nixos/modules/services/backup/znapzend.nix
index 35c0308c9d..a980ac1b3b 100644
--- a/nixos/modules/services/backup/znapzend.nix
+++ b/nixos/modules/services/backup/znapzend.nix
@@ -18,6 +18,7 @@ in
     systemd.services = {
       "znapzend" = {
         description = "ZnapZend - ZFS Backup System";
+        wantedBy    = [ "zfs.target" ];
         after       = [ "zfs.target" ];
 
         path = with pkgs; [ zfs mbuffer openssh ];
@@ -28,6 +29,5 @@ in
         };
       };
     };
-
   };
 }
```

**Comment by johnramsden** [comment]
@dermetfan Huh, it must have changed since I cherry-picked it.
