### ISSUE TITLE
abcde - IO::Socket::SSL 2.009+ required for TLS support

### ISSUE THREAD

**Issue by Cameo007** [NixOS/nixpkgs#274702]
### Describe the bug
When I run abcde on NixOS I see the following error message
```
Grabbing entire CD - tracks:  01 02 03 04 05 06 07 08 09 10
abcde: attempting to resume from /home/pasca/Musik/Music/abcde.9b08360a..
.
IO::Socket::SSL 2.009+ required for TLS support at /nix/store/dig9fkcgnb2y167ksahri94yvfqaz0js-perl5.38.0-WebService-MusicBrainz-1.0.6/lib/perl5/site_perl/5.38.0/WebService/MusicBrainz/Request.pm line 69.
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
```

### Steps To Reproduce
1. Get abcde via configuration or nix-shell
2. Insert a CD
3. Run `abcde`

### Expected behavior
abcde should work. (like on Ubuntu with the same config)

### Additional context
I'm using the latest version of abcde

### Notify maintainers

@gebner 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.12, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(pasca): `""`
 - channels(root): `"home-manager, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by underscore-j** [comment]
I'm unsure why this hasn't been mentioned yet, but it seems the issue has been fixed on unstable and master.

**Comment by jasom** [comment]
More specifically it was fixed with 79e06103c7415d5ddc610c09d6f012656567d0be

**Comment by jwrfoo** [comment]
Not sure if it's the best workaround, but I'm using the following line in my system flake until the PR is merged:

my_abcde = pkgs.abcde.overrideAttrs (oldAttrs: { buildInputs = oldAttrs.buildInputs ++ [ pkgs.perlPackages.IOSocketSSL ]; });

**Comment by antonmosich** [comment]
I think this issue can be closed since it really reached all current channels by now.
