### ISSUE TITLE
srb2: refactor: change where assets are downloaded from

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#274797]
## Issue description

use https://git.do.srb2.org/STJr/srb2assets-public instead of pulling the windows zip from github releases

## Ping maintainers

@zeratax @donovanglover

**Comment by donovanglover** [comment]
I can review if you want to PR this

**Comment by pinkcreeper100** [comment]
upstream has said that they'd rather us use the github mirror that they're going to set up

**Comment by pinkcreeper100** [comment]
the github mirror has been created

**Comment by Logan-A** [comment]
Sorry, I have to delete the github mirror, due to bandwidth limits.
Please use https://git.do.srb2.org/STJr/srb2assets-public

**Comment by Logan-A** [comment]
> Sorry, I have to delete the github mirror, due to bandwidth limits. Please use https://git.do.srb2.org/STJr/srb2assets-public

the "SRB2_2.2" branch and/or "SRB2_release_2.2.13" tag

**Comment by donovanglover** [comment]
Getting 500 errors when trying to access `https://git.do.srb2.org/STJr/srb2assets-public/-/archive/SRB2_release_2.2.13/srb2assets-public-SRB2_release_2.2.13.zip`

**Comment by pinkcreeper100** [comment]
@donovanglover does this work for you?

https://git.do.srb2.org/STJr/srb2assets-public/-/tags

**Comment by donovanglover** [comment]
The link works however the download buttons don't. PRs welcome if anyone can get it working, but wait for https://github.com/NixOS/nixpkgs/pull/296418 to be merged first to avoid merge conflicts.

**Comment by pinkcreeper100** [comment]
@donovanglover i have had another look, and have found that it might be better to pull directly from [this](https://git.do.srb2.org/STJr/srb2assets-public/-/tree/SRB2_2.2?ref_type=heads) branch

**Comment by donovanglover** [comment]
Thanks, was able to get it to work with `fetchgit` :+1:
