### ISSUE TITLE
Package request: openrocket

### ISSUE THREAD

**Issue by dunxen** [NixOS/nixpkgs#274805]
**Project description**

Model-rocketry aerodynamics and trajectory simulation software.

**Metadata**

* homepage URL: https://openrocket.info/
* source URL: https://github.com/openrocket/openrocket
* license: gpl3
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hugosenari** [comment]
Mentioned in #278322

**Comment by TomaSajt** [comment]
Opened a PR, sorry about the long delay. I kind of got distracted refactoring other java packages for reproducibility instead of creating the PR.
