### ISSUE TITLE
ncurses doesn't add headers under .nix-profile/include

### ISSUE THREAD

**Issue by fredlebel** [NixOS/nixpkgs#27483]
## Issue description
If I install ncurses, I would expect the headers under `.nix-profile/include`.  I seem to recall it behaving that way in the past.

### Steps to reproduce
1. `nix-env -i ncurses`
2. Look under `.nix-profile/include`.

Would expect to see headers related to ncurses.

## Technical details

* System: NixOS: `17.03`
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: `17.03.1264.9ed5dbafe3`
* Sandboxing enabled: `false`

**Comment by FRidh** [comment]
`ncurses` uses multiple outputs. The headers can be found in `ncurses.dev`.

What are you doing that you are installing headers in a profile? The recommended/supported workflow is to use Nix for building software.

**Comment by FRidh** [comment]
Also, this is a Nix issue. See also https://github.com/NixOS/nix/issues/1379.
