### ISSUE TITLE
Default list of NTP servers (networking.timeServers) should include different providers

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27487]
## Issue description

Currently it has only time providers in ```.nixos.pool.ntp.org```:
```nix
    networking.timeServers = mkOption {
      default = [
        "0.nixos.pool.ntp.org"
        "1.nixos.pool.ntp.org"
        "2.nixos.pool.ntp.org"
        "3.nixos.pool.ntp.org"
      ];
      description = ''
        The set of NTP servers from which to synchronise.
      '';
    };
```

This is not reliable:
1. There is at least one cloud hosting (```domflow.it```) which firewalls them all (but do not firewall ```time.windows.com```)
2. All of them are domain names and thus depend on working DNS resolver (which is an over-optimistic assumption)

**Comment by Mic92** [comment]
Could not every ntp server blocked by someone?  I think we have to delegate this decision to the user as every network can have different restrictions and we cannot serve them all.

**Comment by volth** [comment]
Archlinux has more servers in ```FallbackNTP``` section.

**Comment by volth** [comment]
> have to delegate this decision to the user as every network can have different restrictions and we cannot serve them all.

It has implicit accumption of one user = one network.
It might be not true.
With nixops and nixos-infect there could be a single user (me) who needs to serve them all within one project.

**Comment by Mic92** [comment]
But you can apply your own configuration with `nixops` for every network, don't you? Soon it will be also possible to deploy timeserver settings via dhcp.
Archlinux uses 0-3.arch.pool.ntp.org btw for both timesyncd and ntpd (the ip addresses are the same for us).
What would be your suggested alternative server selection? I am not an expert on ntp, but could it not have unwanted effects, if you mix ntp servers from different organisations?

**Comment by volth** [comment]
As a quick hack I added time.windows.com to the default list on all my nixoses (including laptops), in an overlay. But I am not sure if I can recommend it, we need an expert opinion
