### ISSUE TITLE
stdenv for nix-shell is broken on master

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#27493]
```
$ nix-shell -p jq --run jq
/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 34: local: -n: invalid option
local: usage: local name[=value] ...
/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 34: local: -n: invalid option
local: usage: local name[=value] ...
/nix/store/fpqvm0gishkdjcyq607gi3h9jvabadvv-stdenv-darwin/setup: line 86: failureHooks: command not found
```

Using 0eb4f6fd2547442d8c51f73d4fe11225951ee663, tracked it down to https://github.com/NixOS/nixpkgs/commit/a14cf0618219a6f135e786e69e78eb0b866248f8

Final question: why wasn't this caught with tests?

cc @NixOS/darwin-maintainers

**Comment by LnL7** [comment]
This is only a problem for nix-shell, if you don't have a newer version of bash in your path.

**Comment by grahamc** [comment]
^ to be real specific, while we fix this out of the box, installing a new version of bash with nix fixes this.

**Comment by domenkozar** [comment]
Workaround: `nix-env -i bash`

**Comment by copumpkin** [comment]
Can we just have the Nix be explicit about which bash it wants (e.g., in the shebang) when it wants to use recent features? I hate stuff (and it seems anti-Nix-ish) that implicitly depends on stuff being set up correctly in the environment.

cc @Ericson2314

**Comment by copumpkin** [comment]
Also, this was called out explicitly in the PR review: https://github.com/NixOS/nixpkgs/pull/27215#issuecomment-313727998

**Comment by domenkozar** [comment]
I propose we fix this long-term by teaching `nix-shell` about `pkgs.bashInteractive`. 

2% of nixpkgs source code is bash and most of our infrastructure tests that, while we impurely depend on system bash for nix-shell.

**Comment by LnL7** [comment]
I can't really think of a reason not to use bash from nixpkgs, it already knows about [`pkgs.runCommand`](https://github.com/NixOS/nix/blob/0a5a867758285ee07334a44ede336ae75fd51c50/src/nix-build/nix-build.cc#L330).

**Comment by domenkozar** [comment]
@edolstra thoughts?

**Comment by domenkozar** [comment]
Implemented in https://github.com/NixOS/nix/commit/c94f3d5575d7af5403274d1e9e2f3c9d72989751

Added a warning to not rename `pkgs.bashInteractive` in e8c72a4

**Comment by edolstra** [comment]
Thanks @domenkozar!

**Comment by copumpkin** [comment]
Awesome, thank you!

**Comment by Ericson2314** [comment]
Is there anything more to do here? It's my breakage so tell me what I can do to help---sorry I missed the discussion so far to begin with.

**Comment by copumpkin** [comment]
This also breaks on CentOS 7

**Comment by copumpkin** [comment]
@Ericson2314 can we just undo the `local -n` stuff for now, until we can guarantee which version of bash is going to be consuming it?

**Comment by copumpkin** [comment]
Removed `darwin` tag because this is definitely breaking some of my Linux machines

**Comment by copumpkin** [comment]
The CentOS failure is because `local -n` was introduced in Bash 4.3 and CentOS 7 ships with 4.2.46.

**Comment by Ericson2314** [comment]
@edolstra What I proposed to @copumpkin in `##nix-darwin` was:

1. Immediately add notice to `setup.sh` aborting with nice message ("Upgrade Nix or upgrade Bash", etc) if Bash is too old. Then people won't get blindsided by `nixpkgs-unstable`.

2. Release `1.11.13` with @domenkozar's change---and also a fix for https://github.com/NixOS/nixpkgs/pull/27427 I'll write. (Not opposed to making it use nixpkgs's `build-env`, but I can crank out the whitespace flexibility I proposed quicker as a stop gap).

I don't think either of those will take much longer, if at all, than a revert. And while what's currently there can bet written without namerefs, https://github.com/NixOS/nixpkgs/pull/26805 will require them or copious eval.

**Comment by domenkozar** [comment]
+1 for releasing 1.11.14 with 2)

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/1483 WIP backport of @domenkozar's patch.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/27618
