### ISSUE TITLE
Update request: mullvad-vpn, old version 2023.5 doesn't work

### ISSUE THREAD

**Issue by EdoardoSnodato** [NixOS/nixpkgs#274927]
- Package name: mullvad-vpn
- Latest released version: 2023.9

![image](https://github.com/NixOS/nixpkgs/assets/154048594/96d88e72-4e1c-452e-8c84-a2752855046f)

**Comment by jpds** [comment]
#274875

**Comment by nagy** [comment]
> Latest released version: 2023.9

No, that is the android release, as you can see here: https://github.com/mullvad/mullvadvpn-app/releases
The latest version is 2023.6 to which this package has been updated in the PR above. Therefore closing this.
