### ISSUE TITLE
Build failure: pcl with CUDA enabled on x86_64-linux

### ISSUE THREAD

**Issue by al3xtjames** [NixOS/nixpkgs#275090]
### Steps To Reproduce

1. Run `nix develop` with the following flake:

```nix
{
  inputs = { nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable"; };

  outputs = { self, nixpkgs }: {
    devShells = nixpkgs.lib.genAttrs [ "x86_64-linux" ] (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config = {
            allowUnfree = true;
            cudaSupport = true;
          };
        };
      in {
        default = pkgs.mkShell {
          buildInputs = [ (pkgs.pcl.override { withCuda = pkgs.config.cudaSupport; }) ];
        };
      });
  };
}
```

### Build log

https://gist.github.com/al3xtjames/64ac677568ba786ed2a1823891157d0d

### Additional context

I think this broke with the recent cudaPackages changes, but I haven't figured out the responsible commit.

### Notify maintainers

@viric
@samuela
@SomeoneSerge
@ConnorBaker   

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61-hardened1, NixOS, 24.05 (Uakari), 24.05.20231204.2c7f3c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(alex): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samuela** [comment]
Not directly relevant but we should rename `withCuda` -> `cudaSupport` for consistency at some point.
