### ISSUE TITLE
clonehero: segfaults on launch

### ISSUE THREAD

**Issue by qubitnano** [NixOS/nixpkgs#275039]
### Describe the bug
`clonehero` segfaults on launch

### Steps To Reproduce
`nix run --impure github:nixos/nixpkgs/a9bf124c46ef298113270b1f84a164865987a91c#clonehero`

### Expected behavior
Game runs

### Notify maintainers

@kira-bruneau @syboxez

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.6, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by syboxez** [comment]
I noticed this as well yesterday running nixos-unstable
