### ISSUE TITLE
nat cannot be disabled (until reboot)

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27510]
## Issue description

Changing ```networking.nat.enable = true``` to ```networking.nat.enable = false``` following by ```nixos-rebuild switch``` does not disable NAT.

Stopping of the ```firewall``` service should take care of flushing iptables (via ```networking.firewall.extraStopCommands```), but the ```firewall``` service is not stopped, it is reloaded so ```networking.firewall.extraStopCommands``` is not executed.

**Comment by Mic92** [comment]
Would affect flushing the firewall affect updates? As an example, if somebody apply rule updates, there should no time window between stopping and starting of the firewall, where the system remains unprotected.

**Comment by volth** [comment]
there are different flushes.
[flushing nat](https://github.com/NixOS/nixpkgs/blob/0906a0f19718605a8074c1c1bf0b3368f8e0d09c/nixos/modules/services/networking/nat.nix#L15) should not leave the system unprotected.
