### ISSUE TITLE
Missing udev rules in Monado Package

### ISSUE THREAD

**Issue by loco-choco** [NixOS/nixpkgs#275107]
### Describe the bug
The [monado] package doesn't install the udev rules generated by the [xr-hardware util] from the Monado project.

### Steps To Reproduce
Install the package and check the lack of udev rules in `/lib/udev/rules.d`

### Expected behavior
It was expected for the udev rules to be installted with the package.

### Additional context
The udev rules are needed as some hmd's have some strange and specific permissions. Maybe instead of adding this to the package, monado could turn into an option like `hardware.opentabletdriver` .

### Notify maintainers
@Scrumplex  @expipiplus1  @prusnak

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(locochoco): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
[monado]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/monado/default.nix
[xr-hardware util]: https://gitlab.freedesktop.org/monado/utilities/xr-hardware

**Comment by loco-choco** [comment]
Trying packaging the udev rules similar to how [brscan4] does it in [here](https://github.com/loco-choco/nixpkgs/tree/monado-module).

[brscan4]: https://github.com/NixOS/nixpkgs/blob/dc24789027b047acc63aa8ac73db5d8fcc84efad/pkgs/applications/graphics/sane/backends/brscan4/default.nix

**Comment by Scrumplex** [comment]
I was working on a Monado NixOS module. Perhaps I can deal with udev rules there. See #245005
