### ISSUE TITLE
`fetchurl`: fetching package fails without message

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27519]
## Issue description

Staging contains a bump of `python.pkgs.pyparsing` to 2.2.0, 9bb9d93ee77f9b9f6ab37ac0d24a60a6bc5719e5.
 
Unfortunately Nix has trouble downloading the source file
```
nix-build https://github.com/NixOS/nixpkgs/archive/9bb9d93ee77f9b9f6ab37ac0d24a60a6bc5719e5.tar.gz -A python.pkgs.pyparsing.src --check
```
I traced the issue to https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/builder.sh#L33. 

Calling `curl` with the specified arguments myself downloads the file just fine. `wget` works as well. And `nix-prefetch-url` works fine as well. Replacing the constructed url with 
```
https://files.pythonhosted.org/packages/3c/ec/a94f8cf7274ea60b5413df054f82a8980523efd712ec55a59e7c3357cf7c/pyparsing-2.2.0.tar.gz
```` 
doesn't make a difference.

Any clues what is going on here?

**Comment by copumpkin** [comment]
Maybe related to https://github.com/NixOS/nixpkgs/issues/27406#issue-243184532 ?

**Comment by ttuegel** [comment]
Closing as duplicate.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/27522 solves the issue with this package
