### ISSUE TITLE
`colloid-kde` shouldn't install KDE Plasma as a dependency, it can be used with Kvantum

### ISSUE THREAD

**Issue by e-tho** [NixOS/nixpkgs#275282]
### Describe the bug
`colloid-kde` shouldn't install KDE Plasma as a dependency, it can be used with Kvantum
```
nix why-depends /nix/store/9ggi8f97sjfzdw01pxx05651373kg5q6-colloid-kde-unstable-2023-07-04 /nix/store/js3dg05mh72pf426xjp01qqc010b3vm8-plasma-workspace-5.27.10
/nix/store/9ggi8f97sjfzdw01pxx05651373kg5q6-colloid-kde-unstable-2023-07-04
└───/nix/store/js3dg05mh72pf426xjp01qqc010b3vm8-plasma-workspace-5.27.10
```

```
│   │   │   │   │   ├───/nix/store/9ggi8f97sjfzdw01pxx05651373kg5q6-colloid-kde-unstable-2023-07-04
│   │   │   │   │   │   ├───/nix/store/v09frpg8bj4qk58bw2hkkl0ylxkqglwg-kdeclarative-5.112.0-bin [...]
│   │   │   │   │   │   ├───/nix/store/6ih9vy5mvgx1nbadhk6zf0wb2g573scr-plasma-framework-5.112.0-bin [...]
│   │   │   │   │   │   ├───/nix/store/js3dg05mh72pf426xjp01qqc010b3vm8-plasma-workspace-5.27.10 [...]
```

### Steps To Reproduce
1. Install `colloid-kde`
2. Check `colloid-kde` dependencies with `nix-store -q --tree /run/current-system`

### Expected behavior
Kvantum and KDE Plasma should be optional dependencies of `colloid-kde`.

### Additional context
I recently noticed that KDE Plasma was installed on my system for no reason, after some research I found the culprit, Colloid-kde installs the entire desktop environment as a dependency. 
I use this theme with `Kvantum` and `qtct` so I don't need KDE.

### Notify maintainers
@romildo 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.6, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by romildo** [comment]
Without it the sddm theme does not work.

**Comment by romildo** [comment]
Maybe one solution to avoid those kde dependencies needed only for the sddm theme is to have a separate output for the sddm theme, and keep the dependencies only for it. Something like what is already done for `nordid.sddm` (the nordic sddm theme).
