### ISSUE TITLE
docker-17.06.0-ce broken build (w/o sandbox)

### ISSUE THREAD

**Issue by calvertvl** [NixOS/nixpkgs#27529]
## Issue description
The build is broken if sandboxing is disabled: it attempts to access /tmp when generating the manpages.

See the [nix-build output](https://gist.github.com/3a6c2c4e93c331c594ff443ad6b61d8e#file-docker-ce-17-06-build-fail-L126) for the exact error message.

Breaking commit: ec570448a036095e181b33b978d71dfc61e56202 by @vdemeester 

Note that enabling sandboxing system-wide does allow the build to succeed.

### Steps to reproduce
Run `nix-build -A docker` on unstable (or `nixos-rebuild switch` with the docker service enabled and an older version of docker).

## Technical details

* System: 17.09.git.823fd92 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.12
* Nixpkgs version: "17.09.git.823fd928e6"
* Sandboxing enabled: no

**Comment by vdemeester** [comment]
@calvertvl arf I shouldn't have use `go install` there.. will fix 👼
