### ISSUE TITLE
stdenv: SHELL being prepended to makeFlags everytime buildPhase is called

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nixpkgs#27533]
## Issue description
Because of [this line](https://github.com/NixOS/nixpkgs/blob/90afb0c10fe6f437fca498298747b2bcb6a77d39/pkgs/stdenv/generic/setup.sh#L734), everytime `buildPhase` is called, another `SHELL=$SHELL ` is being prepended to `makeFlags`. This should only be done once per sourcing of stdenv.sh.

### Steps to reproduce
In an empty directory:
```bash
touch Makefile
nix-shell -E '(import <nixpkgs>{}).stdenv.mkDerivation { name="x"; }'

[nix-shell:~/Test/shell]$ buildPhase
make flags: SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash    
[nix-shell:~/Test/shell]$ buildPhase
make flags: SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash SHELL=/nix/store/lpk84rsbha199vm3k54498lqv2jswqj8-bash-4.4-p5/bin/bash
```

### Possible ways to resolve (ordered from best to worst)
- Adding a function that abstracts the call of `make`, which would take an argument of the phase and handle accordingly while applying the `SHELL`, `-j` flags and such in all cases. Disadvantage: Another function. Advantage: Better abstraction.
- Moving `makeFlags="SHELL=$SHELL $makeFlags"` out of the function, having it run once per sourcing. Disadvantage: Variable is assigned in all cases, even if make isn't used; [This check for if a Makefile exists should be changed](https://github.com/NixOS/nixpkgs/blob/90afb0c10fe6f437fca498298747b2bcb6a77d39/pkgs/stdenv/generic/setup.sh#L730), because `makeFlags` would never be empty.
- Adding the argument `SHELL=$SHELL` to every make invocation in all methods that use it. Disadvantage: More bloat to the call of `make`.
- Making the reassigned `makeFlags` a local variable in all functions that use `make` (`buildPhase`, `checkPhase`, `installPhase` and `installCheckPhase`). Disadvantage: Replicated behaviour.

Or something else?

**Comment by bjornfor** [comment]
Another possibility: check if there is a ```SHELL=``` token in makeFlags and only add it if it's missing.

**Comment by dezgeg** [comment]
Probably worth for the abstraction since there's also the `-j $NIX_BUILD_CORES` that could be de-duplicated.

**Comment by edolstra** [comment]
`buildPhase` *is* the function that abstracts the call to `make`. So adding another function to call make seems overkill.

Moving the initialisation out of `buildPhase` seems fine to me (and changed to use `makeFlagsArray` while we're at it).

**Comment by dezgeg** [comment]
But there are other reasons to call `make` than `buildPhase`, like `checkPhase` and `installCheckPhase`, where the `$NIX_BUILD_CORES` logic is currently copypasted.

Also there are 40+ calls to make in individual packages that manually pass `-j $NIX_BUILD_CORES` but no `-l $NIX_BUILD_CORES`, which is suboptimal (`git grep 'make.*NIX_BUILD_CORE'`).

**Comment by edolstra** [comment]
Yeah, good point.

**Comment by Infinisil** [comment]
I've implemented an abstraction of `make` [here](https://github.com/Infinisil/nixpkgs/commit/c0b82dd74a5e0e2c51b738639d4647b94f3ec244). A side-effect of how I did it is that now all phases use the same set of make flags, that is a `SHELL=$SHELL` flag, parallel flags, `makeFlags` and makefile flag, some of which were not present in all phases before (notably `distPhase`). Also I changed it so that all make flags are now echoed (I don't know why this wasn't done before).

I also did an alternative version [here](https://github.com/Infinisil/nixpkgs/commit/afa29c636f6cc8a3734f291fac9f4783b62ff5d2) where I'm using indirect expansion to get a better abstraction. The disadvantage is that if one was to search the source for e.g. `buildFlags` they wouldn't find anything.

Note that I didn't thoroughly test this change yet (it takes forever to rebuild everything), but `nix-build -A hello` does not error in the first 5 minutes.

**Comment by Ekleog** [comment]
(triage) If I understand correctly, globally everyone here agrees that abstracting the call to `make` would be a good thing. And @Infinisil has two implementations of such an abstracted call to `make`.

So the only thing missing would be picking one of the two, and then PR'ing it into `staging`.

If there is a need of an opinion in favor of one, I'm personally in favor of the non-indirect-expansion version, because it feels “more pure”: with the indirect-expansion version, the action performed by `makePhase` depends on arguments that are not visibly passed to it. Sure, it's bash, so environment variables will always introduce side effects, but it sounds (to me) legitimate to try reducing them. :)
