### ISSUE TITLE
gotools conflicts with sox

### ISSUE THREAD

**Issue by happyalu** [NixOS/nixpkgs#275392]
### Describe the bug

After #273865 the gotools package now has a `play` binary that provides a playground. When I was using gotools as well as sox using home-manager, I got this:

```
error: collision between `/nix/store/s388xvv6zdhf5df236jgm28rb3srx1lb-gotools-0.16.1/bin/play' and `/nix/store/i0mjzgv9yv4qar7ixncmdssm9zrw9jg6-sox-unstable-2021-05-09/bin/play'
```

Should we include "play" in gotools? 

### Notify maintainers

cc @danderson @SuperSandro2000

**Comment by SuperSandro2000** [comment]
This is unfortunate but can happen. I don't think the solution is to remove any binaries from the package though. I'm open for alternatives.

**Comment by happyalu** [comment]
You are right.. It would be more of a surprise to find a binary missing. But a "play" command in the env, to me at least, feels more audio-like than a go playground. One alternative might be -- like we do for gopls, we separate the play package out into -- say -- goplay. But I don't totally like that either.

Perhaps we could close this, and I'll figure out how to resolve the collision in my home manager settings.

**Comment by SuperSandro2000** [comment]
> But a "play" command in the env, to me at least, feels more audio-like than a go playground.

This is something upstream should probably fix.



> One alternative might be -- like we do for gopls, we separate the play package out into -- say -- goplay. But I don't totally like that either.

I don't really want to split the package into multiple things or to consider what to build. 😓 

> Perhaps we could close this, and I'll resolve the collision in my home manager settings:

Yeah, this is probably the best unless the binary collision is really common.
