### ISSUE TITLE
Update request: nix 2.18.1 → 2.19.2

### ISSUE THREAD

**Issue by izelnakri** [NixOS/nixpkgs#275380]
- Package name: nix
- Latest released version: 2.19.2
- Current version on the unstable channel: 2.18.1
- Current version on the stable/release channel: 2.18.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ryantm @fabaff

-----
After the NixOS 23.11 release, I checked the nix website and also saw the latest nix version is `v2.19.2`.

When I run: 

```$ nix upgrade-nix```

My nix version doesn't get updated. After running `nix upgrade-nix --debug` I found that  https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix points to `v2.18.1`.  Is this update not automated during releases? I couldn't find much information about this other than seeing one merged PR where `v2.19.2` gets introduced to `nixpkgs`. Can we upgrade the expression to `v2.19.2` asap so `nix upgrade-nix` upgrades to `v2.19.2` properly. 

What I currently get:

```
$ nix upgrade-nix --debug

found Nix in '/nix/var/nix/profiles/default/bin'
found profile '/nix/var/nix/profiles/default'
ignoring the client-specified setting 'extra-platforms', because it is a restricted setting and you are not a trusted user
ignoring the client-specified setting 'sandbox-dev-shm-size', because it is a restricted setting and you are not a trusted user
performing daemon worker op: 1
upgrading Nix in profile '/nix/var/nix/profiles/default'
querying latest Nix version...
downloading 'https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix'...
starting download of https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix
finished download of 'https://github.com/NixOS/nixpkgs/raw/master/nixos/modules/installer/tools/nix-fallback-paths.nix'; curl status = 0, HTTP status = 200, body = 226 bytes
downloading '/nix/store/azvn85cras6xv4z5j85fiy406f24r1q0-nix-2.18.1'......
performing daemon worker op: 10
verifying that '/nix/store/azvn85cras6xv4z5j85fiy406f24r1q0-nix-2.18.1' works......
installing '/nix/store/azvn85cras6xv4z5j85fiy406f24r1q0-nix-2.18.1' into profile '/nix/var/nix/profiles/default'......
replacing old 'nix-2.18.1'
installing 'nix-2.18.1'
```
---

**Comment by donovanglover** [comment]
Don't know much about the Nix release process but I'm using [nixVersions.nix_2_19](https://search.nixos.org/packages?channel=unstable&query=nixVersions.nix_2_19) on unstable to fix https://github.com/NixOS/nix/issues/5759.

Not sure if it's stable yet since 2.19.2 gives me these warnings when rebuilding:

```
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
```
