### ISSUE TITLE
roaming laptop: network proxy configuration

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#27535]
## Issue description

Is there a way to setup nixos to automatically choose the right proxy based on the network it is on? I have nixos installed on my laptop which I use

- on work network which has a proxy
 - on home network where there is no proxy

I have so far been modifying

    networking.proxy.default

and doing

    nixos-rebuild switch

each time I switch network.

What is the right way to handle changing proxy configuration in nixos?

**Comment by rnhmjoj** [comment]
I would say it's impossible: switching network happens at "runtime" and the option is set once when you build the configuration. Anyway you don't have to switch the configuration just for that.
All `networking.proxy.<protocol>` does is setting the environment variable `<protocol>_proxy`. You only need to change it from the shell, or write a function/script to toggle it.

**Comment by rnhmjoj** [comment]
To make it really automatic you could write a [PAC](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file) file and configure a webserver to serve it locally. I don't which program support proxy auto-configuration thought, probably only browsers.

**Comment by vmandela** [comment]
@rnhmjoj  Exporting environment variables does not seem to work when trying to do 

`nix-env -i`

Does nix-env -i run in a different environment? If yes, how do I set the proxy variables for that environment?

**Comment by rnhmjoj** [comment]
I think this happens because the nix-daemon is doing the actual downloading and it gets the proxy variable from the systemd unit file.

    $ systemctl cat nix-daemon | grep proxy
    Environment="http_proxy=http://localhost:8118"

So... no, you do have to switch the configuration to change it effectively in this case.

**Comment by rnhmjoj** [comment]
You could use `nixos-rebuild test` instead.

**Comment by dpflug** [comment]
What I did on my last laptop to manage this was run a squid proxy locally and point everything to it. When I changed networks/needed to change proxies, a script would rewrite its upstream proxy setting and restart it.

I'm still working out how to make that happen on Nix.

**Comment by vmandela** [comment]
I have worked around this using the `nesting.clone` option.

~~~
nesting.clone = [
        {
                boot.loader.grub.configurationName = "Work";
                networking.proxy.default = "http://proxy.work.com:80";
                networking.proxy.noProxy = "127.0.0.1,localhost,work.com";
                nix.binaryCaches = [
                        "http://nixcache.work.com"
                        "https://cache.nixos.org"
                ];
        }
];
~~~

When I need to switch network configuration, I use

~~~
$ sudo /run/current-system/fine-tune/child-1/bin/switch-to-configuration test
~~~

to switch to the configuration with proxy enabled. The only problem I have now is having this cloned configuration show up in the grub menu. I have filed PR #44495 to track this.

**Comment by contrun** [comment]
As far as I can tell, the best way to do that is

```shell
sudo mkdir /run/systemd/system/nix-daemon.service.d/
cat << EOF >/run/systemd/system/nix-daemon.service.d/override.conf  
[Service]
Environment="http_proxy=socks5h://localhost:7891"
Environment="https_proxy=socks5h://localhost:7891"
Environment="all_proxy=socks5h://localhost:7891"
EOF
sudo systemctl daemon-reload
sudo systemctl restart nix-daemon
```
Not the directory /run/systemd/ is volatile. You need to change it everytime you reboot.

**Comment by ryan4yin** [comment]
> As far as I can tell, the best way to do that is
> 
> ```shell
> sudo mkdir /run/systemd/system/nix-daemon.service.d/
> cat << EOF >/run/systemd/system/nix-daemon.service.d/override.conf  
> [Service]
> Environment="http_proxy=socks5h://localhost:7891"
> Environment="https_proxy=socks5h://localhost:7891"
> Environment="all_proxy=socks5h://localhost:7891"
> EOF
> sudo systemctl daemon-reload
> sudo systemctl restart nix-daemon
> ```

The corresponding declarative and non-volatile approach is to add the following Module to your NixOS configuration:

```nix
{
  systemd.services.nix-daemon.environment = {
    # socks5h mean that the hostname is resolved by the SOCKS server
    https_proxy = "socks5h://localhost:7891";
    # https_proxy = "http://localhost:7890"; # or use http prctocol instead of socks5
  };
}
```

**Comment by glyh** [comment]
@ryan4yin This sounds like a non-solution for non-NixOS user

**Comment by yueyinqiu** [comment]
Edit:

It finally worked with：

```sh
sudo all_proxy=socks5h://127.0.0.1:52138 nixos-rebuild switch --flake ".#$(hostname)"
```

Yes! It will follow the proxy variables here! We no longer need to set a proxy for nix-daemon (and it won't work anymore)!

Note that this is just my personal test result. I haven't found any documentation explaining this. [This section in the manual](https://nix.dev/manual/nix/2.34/installation/env-variables.html#proxy-environment-variables) might be relevent but it's part of `nix Installation`, so I don't know whether it should apply to `nixos-rebuild` (seems yes) / `nix shell` (seems to depend on whether you are `root` ???). 

---
---
---

Hello. I'm very sorry to bother you, but why is it that after I set up a proxy for nix-daemon, nixos-rebuild does not actually access it?

I can see that the environment variable has been set:

```sh
$ sudo cat /proc/$(pidof nix-daemon)/environ | tr '\0' '\n' | grep proxy
https_proxy=http://localhost:52207
http_proxy=http://localhost:52207
all_proxy=http://localhost:52207
```

To know whether it's using a proxy, I deployed it with mitmproxy, and I have confirmed that the service is on (404 here is just the expected response):

```sh
Jul 12 19:15:44 earth-latitude-7490 systemd[1]: Started Proxy for nix-daemon.
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:15:46.405] Loading script /nix/store/69fm0mk5jhsikpzgp>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:15:46.406] HTTP(S) proxy listening at *:52207.
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:16:59.367][[::1]:34794] client connect
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:16:59.600][[::1]:34794] server connect github.com:443 >
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:16:59.944] [REWRITE] https://github.com/yueyinqiu -> h>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:17:00.186][[::1]:34794] server connect gh-proxy.org:44>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:17:00.529][[::1]:34794] Lowercased 'Host' header as up>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:17:00.529][[::1]:34794] Lowercased 'Origin' header as >
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [19:17:02.162] [RESPONSE] https://gh-proxy.org/https://git>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]: [::1]:34794: GET https://gh-proxy.org/https://github.com/y>
Jul 12 19:17:02 earth-latitude-7490 mitmdump[1023]:  << HTTP/2.0 404 Not Found 4.9k
```

However the following script is still connecting the network directly and my mitmproxy didn't log anything (indicating it's truely unused):

```sh
mkdir -p /run/systemd/system/nix-daemon.service.d/
tee /run/systemd/system/nix-daemon.service.d/override.conf << EOF
[Service]
Environment="https_proxy=http://localhost:52207"
Environment="http_proxy=http://localhost:52207"
Environment="all_proxy=http://localhost:52207"
EOF
systemctl daemon-reload
systemctl restart nix-daemon
nixos-rebuild switch --flake ".#$(hostname)"
```
