### ISSUE TITLE
nixos-rebuild switch stopped working. "could not find any previously installed systemd-boot (but bootctl doesn't return 1)"

### ISSUE THREAD

**Issue by makoConstruct** [NixOS/nixpkgs#275365]
### Describe the bug

The stuff that's trying to update systemd doesn't detect systemd in boot partition, which is breaking `nixos-rebuild switch`.

```
[mako@enamel:~]$ sudo nixos-rebuild switch --flake ./nixos_config/#enamel --show-trace
[sudo] password for mako: 
building the system configuration...
File system "/boot" is not a FAT EFI System Partition (ESP) file system.
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
Traceback (most recent call last):
  File "/nix/store/1kdh0fw8q3almc8kqs3cp1yz990rard4-systemd-boot", line 344, in <module>
    main()
  File "/nix/store/1kdh0fw8q3almc8kqs3cp1yz990rard4-systemd-boot", line 332, in main
    install_bootloader(args)
  File "/nix/store/1kdh0fw8q3almc8kqs3cp1yz990rard4-systemd-boot", line 270, in install_bootloader
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
warning: error(s) occurred while switching to the new configuration
```

So I looked at the script the error was being thrown from. The error is a result of this regex finding no matches:

```python
        installed_out = subprocess.check_output(["/nix/store/i0sdqs34r68if9s4sfmpixnnj36npiwj-systemd-254.6/bin/bootctl", "--esp-path=/boot", "status"], universal_newlines=True)

        # See status_binaries() in systemd bootctl.c for code which generates this
        installed_match = re.search(r"^\W+File:.*/EFI/(?:BOOT|systemd)/.*\.efi \(systemd-boot ([\d.]+[^)]*)\)$",
                      installed_out, re.IGNORECASE | re.MULTILINE)
```

I notice this regex doesn't match anything in `bootctl --esp-path=/boot status`, but it *does* match something in `bootctl status`. (Is it possible that the addition of `--esp-path` was the breaking change?). With the current command, we get

```
Available Boot Loaders on ESP:
          ESP: /boot
```

Without that argument, we see the expected:

```
Available Boot Loaders on ESP:
          ESP: /boot/efi (/dev/disk/by-partuuid/a5729fb0-f82d-4075-bff8-4714499cc705)
         File: ├─/EFI/systemd/systemd-bootx64.efi (systemd-boot 253.6)
               └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 253.6)
```

I should mention that in either case, that same version number could have been drawn from the earlier section:

```
Current Boot Loader:
      Product: systemd-boot 253.6
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop-in drivers
               ✓ Support Type #1 sort-key field
               ✓ Support @saved pseudo-entry
               ✓ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
          ESP: /dev/disk/by-partuuid/a5729fb0-f82d-4075-bff8-4714499cc705
         File: └─/EFI/BOOT/BOOTX64.EFI
```

that might be the right approach?

Similar issues (EG https://github.com/NixOS/nixpkgs/issues/97427 , https://github.com/NixOS/nixpkgs/issues/97433 ) have come up before, but they complained of bootctl returning 1, which wasn't happening with me.

### Steps To Reproduce
I don't know. I vaguely remember doing something weird with my boot partition location or hardware config during installation to get it to work with a nonstandard partitioning, when I installed nixos on this PC. But that would have been a long time ago, and this hasn't happened before. Also, my hardware-configuration.nix is the same as the one that nixos-generate-config would generate today, which would suggest that I actually did not stick with the weird hardware configuration I vaguely remember? (Unless nixos-generate-config is _noticing_ a weird arrangement and generating a boot config to suit it. Does it do anything like that?)

I think this may have started as a result of switching to `nixpkgs = { url = "github:NixOS/nixpkgs/nixos-23.11"; };`

But I don't really know why this has started happening.

### Expected behavior
nixos-rebuild should work as it always did.

### Metadata

```console
[mako@enamel:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/nn818zlhq4hnx794c57adijwikdw6cqz-nix-info
copying path '/nix/store/nn818zlhq4hnx794c57adijwikdw6cqz-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.44, NixOS, 23.05 (Stoat), 23.05.20230809.9034b46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(mako): `"nixpkgs"`
 - channels(root): `"home-manager, nixos-22.11"`
 - nixpkgs: `/home/mako/.nix-defexpr/channels/nixpkgs`
```

I attempted downgrading to nixpkgs 22.11 to see if it is a regression, but this crashed a bunch of applications, and failed due to not being able to build specific versions of things, which I'm guessing is happening because the lock files don't go backwards? So I'd have to delete my lock file? I'd prefer to avoid doing this unless necessary.

**Comment by makoConstruct** [comment]
> (Is it possible that the addition of --esp-path was the breaking change?)

Nope, that used to be `--path`, but that change was a while ago, and it always had `--path`, and `--path` gets the non-matching output.

**Comment by E-Allie** [comment]
I just switched my system to use flakes, and now am also encountering this issue.

### Workaround:

If you know the location of your boot partition, in my case `/dev/sda1`, you can run

`mount /dev/sda1 /boot`

Before initiating a nixos-rebuild. This is temporary and must be done manually on every boot.

**Comment by makoConstruct** [comment]
Curious, I don't have a filesystems./boot variable in my hardware-configuration.

**Comment by makoConstruct** [comment]
@obadz I notice a mysterious commented out line gesturing towards setting efiSysMountPoint as I would need it, [here](https://github.com/NixOS/nixpkgs/blame/6a9bfbfa1001235034f486b52791830451bf0bf1/nixos/modules/installer/tools/nixos-generate-config.pl#L678) that you're git blamed for so I wonder if you could shed some light on this.

Is (my) `efiSysMountPoint` supposed to be set to "/boot/efi"? This would stop systemd-boot-builder.py from breaking my system rebuild.

I see that the default value of `efiSysMountPoint` is `/boot`, but `nixos-generate-config` doesn't set a filesystem value for /boot, it only sets one for /boot/efi. `systemd-boot-builder.py` then uses `efiSysMountPoint` [here](https://github.com/NixOS/nixpkgs/blob/cfc3698c31b1fb9cdcf10f36c9643460264d0ca8/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L261), and this code doesn't work correctly with `/boot`, it seems to want `/boot/efi`.

Is the blame with whatever is setting efiSysMountPoint, or with nixos-generate-config for not setting a `filesystems."/boot"`?

Alternately, is [the regex](https://github.com/NixOS/nixpkgs/blob/cfc3698c31b1fb9cdcf10f36c9643460264d0ca8/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L264) in `systemd-boot-builder.py` wrong?

**Comment by makoConstruct** [comment]
So I copied the harwdare configuration's filesystems./boot/efi section into filesystems./boot. I also noticed that my boot partition actually isn't vfat (as default hardware-config assumes), so I set `fsType = "fat32"` in both cases.

Neither of these changes prevented the "File system "/boot" is not a FAT EFI System Partition (ESP) file system." error o_o.

Some other things might be going on.

**Comment by makoConstruct** [comment]
### Fix:

I set `boot.loader.efi.efiSysMountPoint = "/boot/efi";` and rebuild is working now!

We should still try to figure out whether there's a way we can automate whatever's going on here!

**Comment by makoConstruct** [comment]
Closing in favor of this summary: https://github.com/NixOS/nixpkgs/issues/289848

**Comment by makoConstruct** [comment]
> ### Fix:

This now no longer works. ```
         at /nix/store/9ckbs4lqcwysy2c5xlaw49xd31jwgkrp-source/lib/modules.nix:296:18:

          295|                     ''
          296|             else throw baseMsg
             |                  ^
          297|         else null;

       error: The option `boot.loader.efi.efiSystemMountPoint' does not exist. Definition values:
       - In `/nix/store/9ckbs4lqcwysy2c5xlaw49xd31jwgkrp-source/flake.nix': "boot/efi/"
```
