### ISSUE TITLE
Lack of QA for changes to `maintainers/maintainer-list.nix`

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#275410]
## Issue description

The file `maintainers/maintainer-list.nix` seems to be randomly edited by committers who feel like doing so, thereby ignoring data protection laws governing some regions where our contributors come from (e.g. https://github.com/NixOS/nixpkgs/pull/178656, https://github.com/NixOS/nixpkgs/pull/272199, https://github.com/NixOS/nixpkgs/pull/273137 as of before the force-push) guidelines our community gave to itself (e.g. https://github.com/NixOS/nixpkgs/pull/275328, https://github.com/NixOS/nixpkgs/pull/275370). Having our community guidelines ignored at random lets NixOS look unprofessional and can scare away contributors and supporters. Having data protection laws ignored might even lead to expensive liabilities for the NixOS foundation, meaning that the money would be missing when paying for servers or incentivizing contributors. Therefore, there should be some QA when editing that file.

A straightforward suggestion regarding this would be to install one or more maintainers for that file itself. These would have to review any PRs touching it before merging would be allowed. The maintainers should provide evidence that they are aware of laws governing personal data in the different jurisdictions we work with, and aware of our community guidelines.

### Steps to reproduce

1. Wait
2. See commits happening where laws and/or community guidelines are being ignored

## Technical details

Not applicable.

**Comment by piegamesde** [comment]
Let's please keep this scoped towards only discussing a QA process for the maintainers file, and not go into other points of disagreement from the issues that sparked this discussion.

> A straightforward suggestion regarding this would be to install one or more maintainers for that file itself. These would have to review any PRs touching it before merging would be allowed.

Proposal in #275443.

**Comment by zeuner** [comment]
Seems like the default mechanisms for maintainers who get pinged on file changes won't work well here. Most commits are probably contributors adding themselves to the file. If we assume that the TOFU model works for these, only exceptional commits would have to be checked manually, thereby reducing the workload. But this would require a smarter `ofborg`...

**Comment by zeuner** [comment]
> Hi, on GitHub and more specifically the nixpkgs repo we almost exclusively handle the technical side of things

Well, the maintainer list is currently maintained in code, so the platform where the repository resides should be an appropriate place to discuss how that's done.

Of course, one might argue that this is a mistake in the first place considering the unclear situation regarding how to comply with the GDPR with such a setup. If we go that route, then yes, maintenance of the list should also be discussed somewhere else.
