### ISSUE TITLE
spaceFM error on start

### ISSUE THREAD

**Issue by langfingaz** [NixOS/nixpkgs#275426]
### Describe the bug

On NixOS 23.11 spaceFM core dumps when I start it.

### Steps To Reproduce
1. Install spaceFM either with `nix-shell -p spaceFM` or by adding it to `users.users.<username>.packages` of your NixOS config.
2. Start spaceFM with `spacefm`
3. The following error is printed to the terminal:

```console
(spacefm:335024): SpaceFM-WARNING **: 15:46:59.896: No root settings found in /nix/store/8x34s3jbj2cnpcakdbfrma5c2bmr2r88-spacefm-1.0.6/etc/spacefm/  Setting a root editor in Preferences should remove this warning on startup.   Otherwise commands run as root may present a security risk.
Segmentation fault (core dumped)
```

### Expected behavior
`spacefm` should start without errors.

### Notify maintainers

@obadz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(yoda): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Brisingr05** [comment]
I'm assuming you're using Wayland. Running `env GDK_BACKEND=x11 spaceFM` should work.

**Comment by langfingaz** [comment]
Thanks for the quick reply. Apart from a small typo (`spacefm` instead of `spaceFM`), I can confirm that this works under Wayland :+1: 

Since my error does not originate from Nix packaging, please excuse my bug report here. I'll close this as completed.
