### ISSUE TITLE
Fix version in package `ollama`

### ISSUE THREAD

**Issue by actuday6418** [NixOS/nixpkgs#275422]
### Describe the bug
The ollama package displays version as `0.0.0` at runtime.

### Steps To Reproduce
1. install `ollama`
2. run `ollama -v`

### Expected behavior
It should display version `0.1.11`.

### Additional context
Based on the [script used to publish the package](https://github.com/jmorganca/ollama/blob/ed195f3562f2470ff7ac5cff8ce4ab93a98fefb8/scripts/publish.sh#L4), we need to set environment variable `VERSION` during the build.

### Notify maintainers

@dit7ya @elohmeier

**Comment by maglore9900** [comment]
@elohmeier can you explain the fix? I just installed ollama from unstable packages, and have the same issue, version is 0.0.0 and that causes a ton of issues
