### ISSUE TITLE
system fails to rebuild with `services.guix.enable = true;`

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#275432]
### Steps To Reproduce
1. add `services.guix.enable = true;`
2. rebuild system
3. error `ln: failed to create symbolic link '/home/kiara/.config/guix/current': No such file or directory`

### Expected behavior
builds ok

### Additional context
error seems to refer to https://github.com/NixOS/nixpkgs/pull/264331/files#diff-b0e48b200c36694c9d20e62d541c57bb3297052e2a0243cd6f1a2c7efae92507R28

### Notify maintainers
@foo-dogsquared 

### Metadata
running system flake on `nixos-unstable-small`

**Comment by foo-dogsquared** [comment]
Turns out I'm understanding my shell scripting wrong.

Anyways, I can reproduce the reported issue with a test VM. I'll fix this at #274192. Thank you for reporting!
