### ISSUE TITLE
Update request: where-is-my-sddm-theme 1.5.1 → 1.6.0

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#275434]
- Package name: where-is-my-sddm-theme
- Latest released version: 1.6.0

- Current version on the unstable channel: 1.5.1
- Current version on the stable/release channel: 1.5.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@name-snrl 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by name-snrl** [comment]
#276610
