### ISSUE TITLE
Update request: fritzing 1.0.1 → 1.0.2

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#275458]
- Package name: fritzing
- Latest released version: 1.0.1 (not tagged, it appears to be https://github.com/fritzing/fritzing-app/commit/8f5f1373835050ce014299c78d91c24beea9b633 )

- Current version on the unstable channel: unstable-2022-07-01
- Current version on the stable/release channel: unstable-2022-07-01

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@robberer @muscaln 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by muscaln** [comment]
Thanks! Updated to `1.0.1` in #264092
