### ISSUE TITLE
Service exhibitor missing 3 option descriptions, cant build.

### ISSUE THREAD

**Issue by Krofek** [NixOS/nixpkgs#27549]
## Issue description

On nixos-rebuild switch it won't build because `nixos/modules/services/misc/exhibitor.nix` is missing 3 descriptions:

1.) line 241 -  s3Config
2.) line 219 - sleepMs
3.) line 222 - retryQuantity

### Steps to reproduce

`nixos-rebuild switch`

## Technical details

* System: 17.09.git.547336e
* Nix version: 1.11.9
* Nixpkgs version: 17.09.git.547336ef98M
* Sandboxing enabled: false

**Comment by copumpkin** [comment]
Should be fixed in #27552
