### ISSUE TITLE
Update request: gnuradio 3.10.7.0 → 3.10.8.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#275427]
- Package name: gnuradio
- Latest released version: 3.10.8.0

- Current version on the unstable channel: 3.10.7.0
- Current version on the stable/release channel:3.10.7.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@doronbehar   
@bjornfor   
@fpletz   
@jiegec  

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Tnx. Update is proposed at https://github.com/NixOS/nixpkgs/pull/275645
