### ISSUE TITLE
Switching to apparmor.enable = true fails

### ISSUE THREAD

**Issue by emanueleperuffo** [NixOS/nixpkgs#275590]
### Describe the bug

When I enable apparmor with `apparmor.enable = true` without changing any other apparmor configuration, NixOS fails to rebuild.

### Steps To Reproduce

1. enable apparmor with `apparmor.enable = true`
2. run `nixos-rebuild boot`

### Expected behavior

NixOS rebuilds

#### Generic error

![Screenshot from 2023-12-20 09-38-09](https://github.com/NixOS/nixpkgs/assets/5085029/8de57e40-e3c6-4400-acbb-4d41d01990e4)

#### Error with `--show-trace`

![Screenshot from 2023-12-20 09-24-33](https://github.com/NixOS/nixpkgs/assets/5085029/047066cc-7dc1-4fa7-b140-ce8e74383ddd)

### Notify maintainers

@ju1m

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 23.11 (Tapir), 23.11.2004.1e2e384c5b7c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Did you set:

    security.apparmor.enable = true;

**Comment by emanueleperuffo** [comment]
Yes I did. Just that without any profile or include. Is it happening only to me?

**Comment by emanueleperuffo** [comment]
I had some weird configuration with my packages. Not related to app armor.
