### ISSUE TITLE
Testing for nixpkgs-stable?

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#27550]
It seems like lately we've been hit with a few bugs in nixpkgs. All of these build correctly, but pretty clearly don't work. Some examples:

- #27493
- b73a862f1777ad709b3088255d3967733549fbc9

All of these hit nixpkgs-unstable without any problem but they probably shouldn't have. My question is, what's the state of testing in Nixpkgs? Specifically, beyond the usual "it builds" mentality.

**Comment by edolstra** [comment]
The state of testing is obviously not good enough. However, I'm closing this issue since it's not actionable. (Open-ended questions tend to linger in the bug tracker forever.)
