### ISSUE TITLE
Update request: rustc 1.74.0 → 1.74.1

### ISSUE THREAD

**Issue by n3oney** [NixOS/nixpkgs#275542]
- Package name: rustc (and all related)
- Latest released version: 1.74.1

- Current version on the unstable channel: 1.74.0
- Current version on the stable/release channel: 1.73.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@figsoda @tjni 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/272969
