### ISSUE TITLE
Zotero ships the wrong binary on linux-aarch64

### ISSUE THREAD

**Issue by vxld100** [NixOS/nixpkgs#275648]
When trying to run zotero 6.30 on linux-aarch64 (M1 macbook with arch based asahi-linux) the binary doesn't execute, and produces the following error:

`/nix/store/2sn7l2ny3iwcvqqp6b24j4yphdpkjl88-zotero-6.0.30/bin/.zotero-wrapped: line 13: /nix/store/2sn7l2ny3iwcvqqp6b24j4yphdpkjl88-zotero-6.0.30/usr/lib/zotero-bin-6.0.30/zotero-bin: cannot execute binary file: Exec format error`

Also:

`$ file /nix/store/2sn7l2ny3iwcvqqp6b24j4yphdpkjl88-zotero-6.0.30/usr/lib/zotero-bin-6.0.30/zotero-bin`
`/nix/store/2sn7l2ny3iwcvqqp6b24j4yphdpkjl88-zotero-6.0.30/usr/lib/zotero-bin-6.0.30/zotero-bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/rr4ind6ay5ivbvcyw60f104grp44ixpn-glibc-2.38-27/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.26, BuildID[sha1]=f34d317495486bc5a1d99c97565dbda17d513147, stripped`

### Notify maintainers
@0i77

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-linux"`
- host os: `Linux 6.5.0-asahi-15-1-edge-ARCH, Arch Linux ARM, noversion, rolling`
- multi-user?: `no`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.0`
- nixpkgs: `/home/lilin/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kilianar** [comment]
https://github.com/NixOS/nixpkgs/issues/201454
