### ISSUE TITLE
Update request: GnuCOBOL 3.1.2 → 3.2

### ISSUE THREAD

**Issue by GitMensch** [NixOS/nixpkgs#275665]
- Package name: gnu-cobol
- Latest released version: 3.1.2
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

You possibly want to check [Adélie's version upgrade](https://git.adelielinux.org/adelie/packages/-/commit/21fe3ef399c25f030d6657e83cc635335f3a9f40), which also includes two upstream patches

Furthermore I'd highly suggest to:
* rename the package to gnucobol (the other "common" package manager who had that with an included dash was brew, and it was renamed there, too)
* use the official gnu download (or its mirror system) instead of the private-company sourceforge
* change the URL
* possibly download and verify the signature too
* for testing possibly include the NIST testsuite (and run `make test`, which will download by wget/curl if the NIST testsuite data is not available already)
* replace patching the testsuite source ".at" by patching the generated testsuite script for anything that should be skipped

All of those can be seen in the files from the referenced commit above.
There are possibly parts in the list above that should be moved out to a separate issue - feel free to do so.

**Notify maintainers**
@ericsagnes @lovesegfault 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kiike** [comment]
Hi @GitMensch! Stumbled upon this packaging request, so gave it a go and addressed your suggestions here. Feel free to evaluate or read the linked PR. I see you are one of the maintainers of GnuCobol. What are the critical commits (along with those two you mentioned) that justify not waiting for the next release? If you can enumerate them, I could add them as patches.

**Comment by GitMensch** [comment]
Note: most of the additional issues handled with 7293c205fd0257b908eed7a49ba815ce3260e2b6 and e1b2d8cfdffc4a4246d637893aab0e6eb246612d, the "outstanding" parts mostly consider the two patches, but as there should be a GnuCOBOL 3.3 within the next two months (at least the RC) which includes this and a bunch of other fixes, and the change to GnuCOBOL 3.2 was pushed a month ago this can likely wait.
