### ISSUE TITLE
libxml2 - xsltproc is missing

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#27569]
## Issue description
The `xsltproc` program is missing from the libxml2 package.

### Steps to reproduce
```
$ nix-shell -p libxml2
[nix-shell] $ xsltproc
bash: xsltproc: command not found
```

## Technical details

* System: NixOS 17.09.git.90afb0c (Hummingbird)
* Nix version: 1.11.13
* Nixpkgs version: 17.09.git.32a351a0aa
* Sandboxing enabled: build-use-sandbox = true

**Comment by pbogdan** [comment]
Have you tried `libxslt`?

**Comment by emmanuelrosa** [comment]
Ahhh, so *there* it is. *Sigh* . Thank you.
