### ISSUE TITLE
electron from-source headers are in the wrong format

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#275627]
### Describe the bug
```
$ nix build nixpkgs#electron_26-bin.headers
$ file $(readlink ./result)
/nix/store/vnp5jnvpw0q6afc9pfkynwb72i1yszcp-node-v26.3.0-headers.tar.gz: gzip compressed data, was "node_headers.tar", last modified: Wed Oct  4 20:06:25 2023, max compression, original size modulo 2^32 1392640

$ nix build nixpkgs#electron_26.headers
$ file $(readlink ./result)
/nix/store/3m4ylx9m7bk2ci5cymv8z2q3y4hf677l-node-v18.16.1-headers.tar.xz: XZ compressed data, checksum CRC64
```

Believe it or not, node-gyp can't unpack XZ :(

> Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### Notify maintainers
@yu-re-ka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(yorick): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/iarm76b9p60gbkxs0n3dww1r2f4gs650-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yu-re-ka** [comment]
Note that there is also an `electron_26.headers`, which does produce a .gz file.

**Comment by yorickvP** [comment]
Sorry, typo. electron_26.headers is producing an xz file for me. Maybe it's fixed in stable?

**Comment by yu-re-ka** [comment]
Ah no, you're right

**Comment by yu-re-ka** [comment]
It seems to be as simple as changing the file ending to .gz:

```
[yuka@yuyu:~/proj/nixpkgs]$ nix build -f . electron_28.headers

[yuka@yuyu:~/proj/nixpkgs]$ file $(readlink result)
/nix/store/qapanp31iygr3mab2aingddgy41fvzbl-node-v18.18.2-headers.tar.gz: gzip compressed data, max compression, from Unix, original size modulo 2^32 52971520

[yuka@yuyu:~/proj/nixpkgs]$ 

```

#275628
