### ISSUE TITLE
Upgrading spotify to 1.0.59 causes segfault

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#27560]
## Issue description
I made what I assume is the trivial update, https://github.com/srhb/nixpkgs/commit/2a2755f775bf040a9754de4e2e54df259e82b1ff , since the previous Spotify .deb had been removed from the upstream location. Unfortunately, Spotify segfaults on launch without any very helpful errors. I can't figure out how to debug this.

### Steps to reproduce

With the above commit,

    ❯ $(nix-build . -A spotify)/bin/spotify
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libcrypto.so.1.0.0: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify)
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libssl.so.1.0.0: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify)
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify: /nix/store/iysacqzg86913w2z7y45a67475q4x75x-curl-7.54.1/lib/libcurl.so.4: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/bin/spotify)
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libcrypto.so.1.0.0: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped)
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libssl.so.1.0.0: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped)
    /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped: /nix/store/iysacqzg86913w2z7y45a67475q4x75x-curl-7.54.1/lib/libcurl.so.4: no version information available (required by /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/share/spotify/.spotify-wrapped)
    /proc/self/exe: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
    /proc/self/exe: /nix/store/3pcgx1021cppkjqhakaq9986wiybdhgv-spotify-1.0.59.395.ge6ca9946-18/lib/spotify/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
    /proc/self/exe: /nix/store/iysacqzg86913w2z7y45a67475q4x75x-curl-7.54.1/lib/libcurl.so.4: no version information available (required by /proc/self/exe)
    [0722/110415.960945:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
    zsh: segmentation fault  $(nix-build . -A spotify)/bin/spotify

     ❯ nixos-version
     17.09.git.1e1472e (Hummingbird)

**Comment by srhb** [comment]
@bennofs discovered that the segfault appears to originate in libceph.so which is included with spotify.

    [335928.835048] traps: .spotify-wrappe[25323] general protection ip:7f850a9b0ce4 sp:7ffe47f12a60 error:0
    [335928.835052]  in libcef.so[7f850924a000+6e67000]
    [335928.838998] .spotify-wrappe[25291]: segfault at 0 ip 00000000005f5d07 sp 00007ffc948d5ff8 error 6 in .spotify-wrapped[400000+23e8000]

**Comment by bennofs** [comment]
It definitely has to do with `libcef`. Replacing libcef fixes the issue:

```
      cp ${/tmp/libcef.so} $out/share/spotify
```

**Comment by bennofs** [comment]
Patching the rpath of libcef also appears to fix the issue:

```
      patchelf \
        --set-rpath $rpath $out/share/spotify/libcef.so
```

**Comment by fpletz** [comment]
> EDIT: it doesn't. I accidently reverted to an older version of spotify.

**Comment by fpletz** [comment]
Sorry, accidentally closed this.

**Comment by srhb** [comment]
I've issued #27563 which brings us back to Spotify stable. The question is, shouldn't this be the default policy anyway? We can have a spotifyTesting derivation as well, if we want to.

If we want to stay with stable, I'll close this for now.

**Comment by peterhoeg** [comment]
Alternatively, we could package ```libcef``` properly and replace the bundled ```libcef.so``` file.

**Comment by FRidh** [comment]
@abbradar packaged `libcef` in https://github.com/NixOS/nixpkgs/pull/15648.

**Comment by srhb** [comment]
#15648 does not currently build, so I can't tell if using that instead would work.

The question still remains though: Should Spotify Testing really be the default option in NixOS?

**Comment by srhb** [comment]
#27563 was merged, so I'm closing this. If we want to have Spotify testing as well, I think it should be a separate package entirely.
