### ISSUE TITLE
GNOME: unable to use/display desktop icons

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#27562]
## Issue description

In GNOME 3, it’s not possible to display any system icons and/or user files (from `~/Desktop/`) in the desktop view.

### Steps to reproduce

1. Install GNOME 3.
1. Open `gnome-tweak-tools` → Desktop → turn on desktop icons → select a few, e.g. Trash.
1. Optionally, copy some files to `~/Desktop/`.
1. Display desktop.
1. It’s empty.
1. Optionally, verify that `gnome-tweak-tools` work by opening `dconf-editor` and looking at `/org/gnome/desktop/background/show-desktop-icons`.

## Technical details

* System: 17.03.1535.8e75b4dc7b (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: "17.03.1535.8e75b4dc7b"
* Sandboxing enabled: build-use-sandbox = true

**Comment by jtojnar** [comment]
Works fine for me on #28053

**Comment by jtojnar** [comment]
Is this still an issue?

**Comment by michalrus** [comment]
I don’t know, my parents moved to Xfce since. Let’s close, then!

**Comment by alexeymuranov** [comment]
My desktop icons disappeared after upgrading NixOS from 18.03 to 18.09.

**Comment by jtojnar** [comment]
Yeah, Ubuntu installs the extension by default.

**Comment by jtojnar** [comment]
Feel free to package the extension if you want.

**Comment by alexeymuranov** [comment]
I do not think that it is this extension that makes the icons appear on Ubuntu.  If i install it on Ubuntu, icons appear twice.  In fact, on Ubuntu desktop icons work the same with GNOME 3.28 as with 3.26. I suppose they patched GNOME to keep desktop icons.

Anyway, it is related to GNOME, not Nix.

**Comment by jtojnar** [comment]
Then they probably patch GNOME Shell to re-add the icons.

If you want to do the same, you can create an [overlay](https://nixos.org/nixpkgs/manual/#chap-overlays). Nixpkgs aims to provide as vanilla packages as possible.
