### ISSUE TITLE
The OVMF's version is too old for using Q35 chipset with QEMU/KVM and OVMF.

### ISSUE THREAD

**Issue by hyphon81** [NixOS/nixpkgs#27568]
## Issue description
We can use UEFI boot in QEMU with the new option virtualisation.libvirtd.qemuOvmf.
However, it has a problem that VMs freeze in booting when we will use the Q35 chipset with old OVMF.
I attempted new OVMF and it didn't cause freezing.
So, the OVMF in nixpkgs should be updated.

#### In virt-manager
virt-manger > File > New Virtual Machine > Select "Local install media (ISO image or CDROM)" > Forward > Select ISO image (e.g. Ubuntu 16.04) > Forward > Forward > Forward > Click "Customize configuration before install" >
Observe in the "Overview" Tab, that Firmware is "BIOS" and switching the selection to "UEFI". And there are Chipset that is "i440FX" and switching the selection to "Q35".
Click apply.
If you can see the IDE Disk or IDE CD-ROM, those should be changed. The IDE Disk Tab, click Advanced options and change Disk bus "IDE" to "VirtIO". Click apply. The IDE CD-ROM Tab, click Advanced options and write "sata" to Disk bus. Click apply. 
And, click "Begin Installation".

### In virt-install
Please use this command.
```
sudo virt-install --name test --hvm --virt-type kvm --ram 2048 --vcpus 2 --arch x86_64 \
--disk size=20,format=qcow2 --network network=default \
--cdrom <your iso files path> \
--boot loader=</nix/store/*OVMF-2014-12-10-fd/FV/OVMF_CODE.fd>,fd,loader_ro=yes,loader_type=pflash,nvram_template=</nix/store/*OVMF-2014-12-10-fd/FV/OVMF_VARS.fd> \
--machine pc-q35-2.8
```
The "<>" sentences are replaced by your own paths in your environment.
If your QEMU version is 2.x then replace "--machine pc-q35-2.8" to "--machine pc-q35-2.x".

Then VM's video console is eternally black and cpu usage is 100%.

## Technical details

I attempted new version OVMF(edk2 github code rev 1683ecec41a7c944783c51efa75375f1e0a71d08) and It seems running fine. So, I have the code for derivation this revision OVMF. But it's dirty. Especially I need openssl-1.1.0e so I downloaded this source with my code.
#25209 

* System: NixOS 17.03.1556.4d1e1d07f9 (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: 17.03.1556.4d1e1d07f9
* Sandboxing enabled: build-use-sandbox = false

**Comment by jaens** [comment]
Looks like `OVMF`/`edk2` packages have been updated to `edk2-2017-12-05` so it should probably work now?

**Comment by hyphon81** [comment]
Yes, it works now.
I confirmed with ```NixOS 17.09.2610.d83c8080d1e (Hummingbird)```, ```virtualisation.libvirtd``` options and ubuntu 16.04 iso.

So, closing this issue.
Thanks.

**Comment by sirkha** [comment]
I am having trouble passing through an NVMe device and I think it may be due to old firmware being used.

Output of `ls -l /run/libvirt/nix-ovmf`:

    total 0
    lrwxrwxrwx 1 root root 78 Mar  5 21:59 OVMF_CODE.fd -> /nix/store/<hash>-OVMF-2014-12-10-fd/FV/OVMF_CODE.fd
    lrwxrwxrwx 1 root root 78 Mar  5 21:59 OVMF_VARS.fd -> /nix/store/<hash>-OVMF-2014-12-10-fd/FV/OVMF_VARS.fd

Output of nixos-rebuild switch --upgrade:

    downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.3129.1dcd022f01b/nixexprs.tar.xz’...
    downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.3129.1dcd022f01b/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/s]
    unpacking channels...
    building Nix...
    building the system configuration...
    activating the configuration...
    setting up /etc...
    setting up tmpfiles

Is there something different I need to do to get OVMF to point to the new firmware?
