### ISSUE TITLE
perl: LWP dependencies not instaled

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27565]
## Issue description

adding ```perlPackages.LWP``` to ```environment.systemPackages``` does not install its dependencies.
It is a regression in ```master``` within last ~10days.

### Steps to reproduce

make a VM
```nix
{ config, pkgs, lib, ... }:

{
  users.users.danbst.isNormalUser = true;
  users.users.danbst.password = "1111";
  users.users.danbst.extraGroups = [ "wheel" ];
  security.sudo.wheelNeedsPassword = false;
  services.mingetty.autologinUser = "danbst";

  environment.systemPackages = with pkgs; [ perl perlPackages.LWP ];
}
```

![](http://i.imgur.com/iR6uBaG.png)

**Comment by vcunat** [comment]
See https://github.com/NixOS/nixpkgs/pull/27427#issuecomment-315627574 (most likely).  I think it applies to all propagated* in buildEnv (incl. systemPackages) and nix-env.

**Comment by volth** [comment]
I will try. It is mass-rebuild, so probably it will be clear if it helps only tomorrow

**Comment by volth** [comment]
Yes, that patch helps.
