### ISSUE TITLE
Update request: openmpi 4.1.6 → 5.0.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#275792]
- Package name: openmpi
- Latest released version: 5.0.1
- Current version on the unstable channel: 4.1.6
- Current version on the stable/release channel: 4.1.6
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@markuskowa

Changelog: https://docs.open-mpi.org/en/v5.0.x/news/news-v5.0.x.html

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by markuskowa** [comment]
This is work in progress. I have been working on it for a while now. 
However, it was not ready since it broke mpi4py and thus all Python applications that depend on openmpi.

I will open a PR soon.

**Comment by markuskowa** [comment]
See https://github.com/NixOS/nixpkgs/pull/275796

**Comment by gepbird** [comment]
This package is on the latest 5.0.5 version.
