### ISSUE TITLE
Cannot run chown in fakeRootCommands in dockerTools.buildLayeredImage: invalid argument

### ISSUE THREAD

**Issue by mplanchard** [NixOS/nixpkgs#275705]
### Describe the bug
I'm working on upgrading our work repository to 23.11 and am running into an issue building a docker image with `dockerTools.buildLayerdImage`. There derivation is:

```nix
{ pkgs, ... }:

pkgs.dockerTools.buildLayeredImage rec {
  name = "ci-image";
  tag = "latest";
  created = "now";

  # Define which nix packages will be in the container.
  contents = [ pkgs.shadow pkgs.fuse-overlayfs pkgs.nss pkgs.util-linux ];

  # Run fake root commands as though `/` is the root.
  enableFakechroot = true;

  # Set up environment needed for doing nix builds.
  fakeRootCommands = ''
    set -exuo pipefail

    mkdir -p \
      /etc \
      /tmp \
      /src \
      /usr/bin

    ln -s ${pkgs.coreutils.outPath}/bin/env /usr/bin/env

    # Ensure that the standard user-management stuff exists and that a root
    # user is created
    ${pkgs.dockerTools.shadowSetup}

    # For some reason using groupadd doesn't work. It says the group already
    # exists, BUT the group isn't in /etc/group and useradd will fail with
    # a "group does not exist" error. So we just create it manually by updating
    # /etc/group ourselves.
    echo "nixbld:x:999:" > /etc/group
    echo "root:x:0:" >> /etc/group

    chown -R 1001:root /src
    chown -R 1001:root /tmp
    chown -R 1001 /home/ci

    # Add nix build users.
    for n in $(seq 1 10); do
      useradd -c "Nix build user $n" \
        -d /var/empty \
        -g nixbld \
        -G nixbld \
        -M \
        -N \
        -r \
        -s "$(command -v nologin)" \
        "nixbld$n"
    done

    mkdir -p /home

    useradd -c "ci user" \
      --home-dir /home/ci \
      --uid 1001 \
      --groups nixbld,root \
      --create-home \
      ci

    # In case we're running git commands as the CI user, we want to ensure that
    # it's okay for the rpeo to have been checked out as a different user
    cat << EOF > /home/ci/.gitconfig
    [safe]
    directory = /builds/work-org/work-repo
    EOF
  '';

  config = {
    Cmd = [ "/bin/bash" ];
    WorkingDir = "/src";
    Env = libraryEnvVars ++ [
      # This tells web stuff where to find certs
      "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"

      # See https://github.com/NixOS/nixpkgs/issues/102962#issuecomment-1434458847
      "PATH=${pkgs.lib.makeBinPath contents}:/bin:/sbin:/usr/bin:/usr/sbin"
    ];
  };
}
```

This works with nix 22.05, but fails with nix 23.11 with the following error:

```
chown: changing ownership of '/src': Invalid argument
```

### Steps To Reproduce
1. Using nix 23.11, try to build the above image

### Expected behavior
The image builds and we can set ownership of files in the image

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers

@Mic92 
@considerate 
@agbrooks 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Also, we are running branch: `release-23.11`, commit `750644b56300bfa3312710e47ab087904e0c655b`

**Comment by considerate** [comment]
I tested this a bit. I can change the permissions on the `/src` directory as long as I don't reference the unknown user `1001`.

**Comment by Mic92** [comment]
Are you sure you were actually able to chown before hand or was chown simply ignored. It shouldn't be possible in the buildsandbox as it would be a major security hole.

**Comment by Mic92** [comment]
As you can see here the chown becomes a no-op:

```
/tmp/funny-hawking-n9XKkE
% ls -la a
.rw-r--r-- joerg users 0 B now  a

/tmp/funny-hawking-n9XKkE
% , fakeroot chown 1001 a

/tmp/funny-hawking-n9XKkE
% ls -la a
.rw-r--r-- joerg users 0 B 14 seconds ago  a
```

If you would suggest to delete those chown commands, they do not have any effect. We replaced fakeroot and proot with just proot, since proot also can set the uid/gid to root. You can still prepend fakeroot manually but except if you rely on third-party scripts to run without errors, those will just silently drop your chown commands.

**Comment by mplanchard** [comment]
Ah okay, the idea was to try to ensure the files were owned by the UID that our CI user (outside of the container) uses, so that any file modifications done to volume mounts wouldn't make the files unreadable by CI. It's possible it wasn't actually needed and/or is vestigial. I guess it's a new version of chown that's causing the issue in 23.11? Thanks for the feedback!

**Comment by Mic92** [comment]
No. We dropped fakechroot when proot already is enabled as it was causing issues. The chown program was still the same.

**Comment by cirla** [comment]
`chown` in `fakeRootCommands` is included as an example in `23.11`: https://github.com/NixOS/nixpkgs/blob/057f9aecfb71c4437d2b27d3323df7f93c010b7e/pkgs/build-support/docker/examples.nix#L589

**Comment by Mic92** [comment]
If you are able to change filesystem owner/groups without having root, I would like to know how because that sounds like a security vulnerability to me.

**Comment by mplanchard** [comment]
I'm not sure I follow. Previously, we were able to use `chown` within the docker build process to set the ownership of directories within the resulting container image. That was useful, because we could set the UID of necessary directories to the UID of the CI user.

For reference, this is essentially the derivation we are working with:

```nix
{ pkgs ? import ../../patched-sources.nix }:

with builtins;

pkgs.dockerTools.buildLayeredImage rec {
  name = "replication";
  tag = "latest";
  created = "now";

  # Define which nix packages will be in the container.
  contents = with pkgs; [
    bashInteractive
    coreutils
    openssl
    shadow
    fuse-overlayfs
    nss
    util-linux
  ];

  # Note that extra commands operate in what will become the `/` of the image,
  # but should not use paths prefixed with `/` because they are being built in
  # an isolated directory.
  extraCommands = ''
    set -exuo pipefail

    mkdir -p tmp src cargo
    mkdir -p usr/bin
    ln -s ${pkgs.coreutils.outPath}/bin/env usr/bin/env
    mkdir -p etc
    touch etc/group
  '';

  # Run fake root commands as though `/` is the root.
  enableFakechroot = true;

  # Set up environment needed for doing nix builds.
  fakeRootCommands = ''
    set -exuo pipefail

    # Ensure that the standard user-management stuff exists and that a root
    # user is created
    ${pkgs.dockerTools.shadowSetup}

    # For some reason using groupadd doesn't work. It says the group already
    # exists, BUT the group isn't in /etc/group and useradd will fail with
    # a "group does not exist" error. So we just create it manually by updating
    # /etc/group ourselves.
    echo "nixbld:x:999:" > /etc/group
    # echo "ci:x:1001:" >> /etc/group
    echo "root:x:0:" >> /etc/group

    # Add nix build users.
    for n in $(seq 1 10); do
      useradd -c "Nix build user $n" \
        -d /var/empty \
        -g nixbld \
        -G nixbld \
        -M \
        -N \
        -r \
        -s "$(command -v nologin)" \
        "nixbld$n"
    done

    mkdir -p /home

    useradd -c "ci user" \
      --home-dir /home/ci \
      --uid 1001 \
      --groups nixbld,root \
      --create-home \
      ci

    cat /etc/group

    chown -R 1001:root /src
    chown -R 1001:root /tmp
    chown -R 1001 /home/ci

    # In case we're running git commands as the CI user, we want to ensure that
    # it's okay for the rpeo to have been checked out as a different user
    cat << EOF > /home/ci/.gitconfig
    [safe]
    directory = /builds/spectrust-inc/spec-protect
    EOF
  '';

  # Each key here maps to the corresponding directive in a Dockerfile
  config = {
    Cmd = [ "/bin/bash" ];
    WorkingDir = "/src";
    Env = [
      # This tells web stuff where to find certs
      "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"

      # See https://github.com/NixOS/nixpkgs/issues/102962#issuecomment-1434458847
      "PATH=${pkgs.lib.makeBinPath contents}:/bin:/sbin:/usr/bin:/usr/sbin"
    ];
  };
}
```

On Nix 22.05, this works, and the results look as you'd expect after running `docker load` & then running bash on the container:

```bash
bash-5.2# ls -l /
total 44
drwxr-xr-x   2 root root 4096 Jan  1  1980 bin
drwxr-xr-x   2 root root 4096 Jan  1  1980 cargo
drwxr-xr-x   5 root root  360 Jan 23 19:04 dev
drwxr-xr-x   1 root root 4096 Jan 23 19:04 etc
drwxr-xr-x   3 root root 4096 Jan  1  1980 home
drwxr-xr-x   4 root root 4096 Jan  1  1980 lib
lrwxrwxrwx   1 root root    3 Jan  1  1980 lib64 -> lib
drwxr-xr-x   3 root root 4096 Jan  1  1980 libexec
dr-xr-xr-x   1 root root 4096 Jan 23 19:04 nix
dr-xr-xr-x 418 root root    0 Jan 23 19:04 proc
lrwxrwxrwx   1 root root    3 Jan  1  1980 sbin -> bin
drwxr-xr-x   5 root root 4096 Jan  1  1980 share
drwxr-xr-x   2 ci   root 4096 Jan  1  1980 src
dr-xr-xr-x  13 root root    0 Jan 23 19:04 sys
drwxr-xr-x   2 ci   root 4096 Jan  1  1980 tmp
drwxr-xr-x   3 root root 4096 Jan  1  1980 usr
bash-5.2# id -u ci
1001
```

----

For 23.11, this is the full build output with the error:

<details>
<summary>Error Output</summary>
<pre>
❯ nix log /nix/store/in5pqapmv1h5q94n4sj961aw5z101vqy-replication-customisation-layer.drv | cat 
/nix/store/ffrva7icr8ws2d51955jy302icgmr80s-util-linux-2.39.2-bin/bin:
login: /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/login
kill: coreutils
chfn: /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/chfn
nologin: /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
chsh: /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/chsh
+++ mkdir -p tmp src cargo
+++ mkdir -p usr/bin
+++ ln -s /nix/store/m38gwq0w8w7qyjn9s00balyp7cv3m5p9-coreutils-9.3/bin/env usr/bin/env
+++ mkdir -p etc
+++ touch etc/group
proot warning: can't sanitize binding "/sys/": No such file or directory
proot warning: can't sanitize binding "/nix/store/q8494z25m447skzy6l4ccyw84nqfcnja-replication-customisation-layer/layer.tar": No such file or directory
++ export PATH=/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin:/nix/store/rvdryxhd9zw6zz7fwwxi6ma55qnblpi8-fakeroot-1.29/bin:/nix/store/811m6jpxyxzhff2wy27xx5r81bqs1dzk-proot-5.4.0/bin:/nix/store/h3ayxf5dk1gdf3s5716fh1ys815qxxag-patchelf-0.15.0/bin:/nix/store/m38gwq0w8w7qyjn9s00balyp7cv3m5p9-coreutils-9.3/bin:/nix/store/01znf87kiw5xx1dj0f7djrnrbg84ij28-findutils-4.9.0/bin:/nix/store/vq4vmndw555m7ld2bi6pq8kr348qvb6a-diffutils-3.10/bin:/nix/store/rwa7qyds01qzxvq7zq3kgnkrzzpw4s66-gnused-4.9/bin:/nix/store/n062zcsmfl9gfp6vfkcg0asb8jjwmy5i-gnugrep-3.11/bin:/nix/store/4v7m4yx07b3anmbznfhihjc8xiizyna9-gawk-5.2.2/bin:/nix/store/mi3pm67ps7c7k11aqki9182ygzg8j503-gnutar-1.35/bin:/nix/store/5c0ancqnpi0cf1h49mv13w68a950s9z0-gzip-1.13/bin:/nix/store/q5cv7r1sh3s4niyq7vm6h1j74394naxs-bzip2-1.0.8-bin/bin:/nix/store/bh7sbl99ygfvw9w96936nrhw46jmcmqq-gnumake-4.4.1/bin:/nix/store/7dpxg7ki7g8ynkdwcqf493p2x8divb4i-bash-5.2-p15/bin:/nix/store/mbh9gx43gsc5av019vsdkazbyiic3f0f-patch-2.7.6/bin:/nix/store/3q6fnwcm677l1q60vkhcf9m1gxhv83jm-xz-5.4.4-bin/bin:/nix/store/a5s2dmba16pw8l52f496gw0b7nli7mbn-file-5.45/bin
++ PATH=/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin:/nix/store/rvdryxhd9zw6zz7fwwxi6ma55qnblpi8-fakeroot-1.29/bin:/nix/store/811m6jpxyxzhff2wy27xx5r81bqs1dzk-proot-5.4.0/bin:/nix/store/h3ayxf5dk1gdf3s5716fh1ys815qxxag-patchelf-0.15.0/bin:/nix/store/m38gwq0w8w7qyjn9s00balyp7cv3m5p9-coreutils-9.3/bin:/nix/store/01znf87kiw5xx1dj0f7djrnrbg84ij28-findutils-4.9.0/bin:/nix/store/vq4vmndw555m7ld2bi6pq8kr348qvb6a-diffutils-3.10/bin:/nix/store/rwa7qyds01qzxvq7zq3kgnkrzzpw4s66-gnused-4.9/bin:/nix/store/n062zcsmfl9gfp6vfkcg0asb8jjwmy5i-gnugrep-3.11/bin:/nix/store/4v7m4yx07b3anmbznfhihjc8xiizyna9-gawk-5.2.2/bin:/nix/store/mi3pm67ps7c7k11aqki9182ygzg8j503-gnutar-1.35/bin:/nix/store/5c0ancqnpi0cf1h49mv13w68a950s9z0-gzip-1.13/bin:/nix/store/q5cv7r1sh3s4niyq7vm6h1j74394naxs-bzip2-1.0.8-bin/bin:/nix/store/bh7sbl99ygfvw9w96936nrhw46jmcmqq-gnumake-4.4.1/bin:/nix/store/7dpxg7ki7g8ynkdwcqf493p2x8divb4i-bash-5.2-p15/bin:/nix/store/mbh9gx43gsc5av019vsdkazbyiic3f0f-patch-2.7.6/bin:/nix/store/3q6fnwcm677l1q60vkhcf9m1gxhv83jm-xz-5.4.4-bin/bin:/nix/store/a5s2dmba16pw8l52f496gw0b7nli7mbn-file-5.45/bin
++ mkdir -p /etc/pam.d
++ [[ ! -f /etc/passwd ]]
++ echo root:x:0:0::/root:/nix/store/7dpxg7ki7g8ynkdwcqf493p2x8divb4i-bash-5.2-p15/bin/bash
++ echo 'root:!x:::::::'
++ [[ ! -f /etc/group ]]
++ [[ ! -f /etc/pam.d/other ]]
++ cat
++ [[ ! -f /etc/login.defs ]]
++ echo nixbld:x:999:
++ echo root:x:0:
+++ seq 1 10
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 1' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld1
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 2' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld2
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 3' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld3
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 4' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld4
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 5' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld5
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 6' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld6
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 7' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld7
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 8' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld8
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 9' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld9
++ for n in $(seq 1 10)
+++ command -v nologin
++ useradd -c 'Nix build user 10' -d /var/empty -g nixbld -G nixbld -M -N -r -s /nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin nixbld10
++ mkdir -p /home
++ useradd -c 'ci user' --home-dir /home/ci --uid 1001 --groups nixbld,root --create-home ci
Creating mailbox file: No such file or directory
++ cat /etc/group
nixbld:x:999:nixbld1,nixbld2,nixbld3,nixbld4,nixbld5,nixbld6,nixbld7,nixbld8,nixbld9,nixbld10,ci
root:x:0:ci
ci:!:1001:
++ chown -R 1001:root /src
chown: changing ownership of '/src': Invalid argument
+ exitHandler
+ exitCode=1
+ set +e
+ '[' -n '' ']'
+ ((  1 != 0  ))
+ runHook failureHook
+ local hookName=failureHook
+ shift
+ local 'hooksSlice=failureHooks[@]'
+ local hook
+ for hook in "_callImplicitHook 0 $hookName" ${!hooksSlice+"${!hooksSlice}"}
+ _eval '_callImplicitHook 0 failureHook'
+ declare -F '_callImplicitHook 0 failureHook'
+ eval '_callImplicitHook 0 failureHook'
++ _callImplicitHook 0 failureHook
++ local def=0
++ local hookName=failureHook
++ declare -F failureHook
++ type -p failureHook
++ '[' -n '' ']'
++ return 0
+ return 0
+ '[' -n '' ']'
+ return 1
</pre>
</details>

If I remove the chowns, everything in the container is owned by root, as you'd expect. Is there no way to change the ownership of directories during the container build process?

**Comment by Mic92** [comment]
> `chown` in `fakeRootCommands` is included as an example in `23.11`:
> 
> https://github.com/NixOS/nixpkgs/blob/057f9aecfb71c4437d2b27d3323df7f93c010b7e/pkgs/build-support/docker/examples.nix#L589

Than this needs to be dropped. As you can above it does have any effect.

**Comment by Mic92** [comment]
Looks like I misunderstood how fakeroot works. It records those permissions between different programs and can replace them for the tar program: https://manpages.ubuntu.com/manpages/trusty/man1/fakeroot-tcp.1.html

**Comment by mplanchard** [comment]
Just adding the state of the directories when running the above without the chowns in 23.11. Note that the CI user doesn't even wind up owning its home directory created by `useradd`. The user does exist, and I can `chown` things interactively in this bash shell as root. However, we don't run the container as root during the CI build for a few reasons, including that it needs to run postgres, which won't run as root.

```
❯ docker run --rm -it replication:latest /bin/bash
bash-5.2# ls -l /home
total 4
drwxr-xr-x 2 root root 4096 Jan  1  1980 ci
bash-5.2# ls -l /
total 44
drwxr-xr-x   2 root root 4096 Jan  1  1980 bin
drwxr-xr-x   2 root root 4096 Jan  1  1980 cargo
drwxr-xr-x   5 root root  360 Jan 23 19:30 dev
drwxr-xr-x   1 root root 4096 Jan 23 19:30 etc
drwxr-xr-x   3 root root 4096 Jan  1  1980 home
drwxr-xr-x   4 root root 4096 Jan  1  1980 lib
lrwxrwxrwx   1 root root    3 Jan  1  1980 lib64 -> lib
drwxr-xr-x   3 root root 4096 Jan  1  1980 libexec
drwxr-xr-x   1 root root 4096 Jan  1  1980 nix
dr-xr-xr-x 420 root root    0 Jan 23 19:30 proc
lrwxrwxrwx   1 root root    3 Jan  1  1980 sbin -> bin
drwxr-xr-x   5 root root 4096 Jan  1  1980 share
drwxr-xr-x   2 root root 4096 Jan  1  1980 src
dr-xr-xr-x  13 root root    0 Jan 23 19:30 sys
drwxr-xr-x   2 root root 4096 Jan  1  1980 tmp
drwxr-xr-x   3 root root 4096 Jan  1  1980 usr

bash-5.2# cat /etc/passwd
root:x:0:0::/root:/nix/store/7dpxg7ki7g8ynkdwcqf493p2x8divb4i-bash-5.2-p15/bin/bash
nixbld1:x:999:999:Nix build user 1:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld2:x:998:999:Nix build user 2:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld3:x:997:999:Nix build user 3:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld4:x:996:999:Nix build user 4:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld5:x:995:999:Nix build user 5:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld6:x:994:999:Nix build user 6:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld7:x:993:999:Nix build user 7:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld8:x:992:999:Nix build user 8:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld9:x:991:999:Nix build user 9:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
nixbld10:x:990:999:Nix build user 10:/var/empty:/nix/store/8d4v7wcr31xh2zh6kcyxnd94r0n8byy6-shadow-4.14.2/bin/nologin
ci:x:1001:1001:ci user:/home/ci:/bin/bash
```

**Comment by Mic92** [comment]
This might be a better fix than:

```
diff --git a/pkgs/build-support/docker/default.nix b/pkgs/build-support/docker/default.nix
index 7218d67062e7..23e439c6c423 100644
--- a/pkgs/build-support/docker/default.nix
+++ b/pkgs/build-support/docker/default.nix
@@ -915,7 +915,7 @@ rec {

             mkdir $out
             ${if enableFakechroot then ''
-              proot -r $PWD/old_out ${bind-paths} --pwd=/ --root-id bash -c '
+              proot -r $PWD/old_out ${bind-paths} --pwd=/ fakeroot bash -c '
                 source $stdenv/setup
                 eval "$fakeRootCommands"
                 tar \
```

Feel free to open a pull request if it fixes your use case.

**Comment by mplanchard** [comment]
I'll pull down nixpkgs and give this a shot, thanks!

**Comment by mplanchard** [comment]
That does indeed seem to fix it! I'll open an MR now

**Comment by mplanchard** [comment]
Created #283300, still cloning stuff to run the review suite locally
