### ISSUE TITLE
Build failure: epson-escpr2

### ISSUE THREAD

**Issue by relief-melone** [NixOS/nixpkgs#275717]
### Steps To Reproduce

use the current package epson-espr2 package and try to build

### Build log
The part from the log that seems to be interesting is this part

```
Running phase: configurePhase
fixing libtool script ./ltmain.sh
./configure
patching script interpreter paths in ./configure
./configure: interpreter directive changed from "#! /bin/sh" to "/nix/store/2ishn1q3c9qk9p5ax4j2y4rk0yqh09gj-busybox-1.36.1/bin/sh"
stat: unrecognized option '--printf'
BusyBox v1.36.1 () multi-call binary.
```

### Additional context
It looks like the issue might be related to a change from 3 days ago. The last time the channel was working for me was on 11th of September. Also the change indicates a switch from busybox to rpm and cpio. Would still consider myself a novice in nix but from the logs I think a correlation might be plausible

### Notify maintainers
@Shawn8901 I hope it's ok to mention you here. Don't know if you are the maintainer but sice the most recent change was from you, you might have a little more insight in the topic.

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.5, NixOS, 24.05 (Uakari), 24.05pre557885.666fc80e7b2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Shawn8901** [comment]
See  https://github.com/NixOS/nixpkgs/issues/274840 and https://github.com/NixOS/nixpkgs/pull/275009

**Comment by relief-melone** [comment]
Thanks for the quick reply. Works like a charm. Is this already published on the unstable channel and if not is there a possibility to use a current branch to build?

**Comment by Shawn8901** [comment]
There is a community tool that help in tracking the channel settlements. 
For the PR on unstable this is the url https://nixpk.gs/pr-tracker.html?pr=275009 (be aware that it needs a quite long loading time). 
Depending on how your system is set up (e.G flakes vs channels) you can pull just the package in. 
I just googled shortly for a blog post that is covering that topic (https://astrid.tech/2022/11/03/0/overlay-nixpkgs-pr/)
On channels setup you may either add a channel or just fetch that and build the driver out of that.
Possibly this wiki page could be helpful in archiving it https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs

**Comment by Shawn8901** [comment]
Update sollte be landed on nixos-unstable, so I am closing the issue, let me know if there any objections

**Comment by relief-melone** [comment]
Will do. Sorry for the inactivity. Christmas preparations were a bit hectic. Will update and let you know if anything goes wrong. But I guess the issue can be closed. thanks again for the help and happy holidays

**Comment by relief-melone** [comment]
can confirm the newest updates fixed the issue
