### ISSUE TITLE
Build failure: julia.withPackages ["DFTK"]

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#275802]
### Steps To Reproduce

1. Build `julia.withPackages ["DFTK"]` to create a Julia environment with [DFTK](https://docs.dftk.org/stable/)

### Build log

```console
>   File "/nix/store/5sscfa2xlzckf92rnsbkfpd935gx3a6h-python/sources_nix.py", line 57, in <module>
>     sha256 = "{version_to_use["nix-sha256"]}";
>                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> KeyError: 'nix-sha256'
```

### Additional context
The issue appears to originate from a missing hash within a dependency. However, the root cause of this problem remains uncertain to me. Building a Julia environment with other packages like `JSON3` and `Plots` does work flawlessly.

### Notify maintainers

@thomasjm 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.4, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thomasjm** [comment]
Thanks for the report! I'll take a look.
