### ISSUE TITLE
Go 1.8.3 is broken on staging

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27589]
## Issue description

http://hydra.nixos.org/build/56796101
https://nix-cache.s3.amazonaws.com/log/4yscz4spx3vr3dl5nsbhf1bhxaq3nccw-go-1.8.3.drv

## Technical details

* Nixpkgs version: 29f91c107f5f605dac63552909cbe3c8f0c2e303

**Comment by copumpkin** [comment]
cc @Ericson2314, any idea what's going on?

**Comment by FRidh** [comment]
Seems to build again.
b2608b8910 gave `/nix/store/g9q7496wbm8wvyz0kdm11p93a2jr07bj-go-1.8.3`
