### ISSUE TITLE
Curl fails with a connection error when running nixos-install

### ISSUE THREAD

**Issue by nkpart** [NixOS/nixpkgs#27581]
## Issue description

When doing an initial install using `nixos-install`, or installing a large number of packages at a time (such as turning on a KDE desktop), the package install fails after printing: `curl: (7) Couldn't connect to server`. It doesn't fail on the first package, but happens some minutes into the process.

### Steps to reproduce

I think this is probably due to some throttling as it appears only after a couple of minutes of successful downloads during the install process. Once it fails to download something, it then fails on the same download for a period of time. After waiting 5-10 minutes, the download completes successfully. However, the error does return after another minute or 2. If I run `nixos-install` or `nixos-rebuild switch` again and again, I'm able to successfully install/upgrade.

I realise this has been discussed in #14874, however if I'm seeing the same problem it certainly hasn't been resolved.

There are currently no issues reported on https://status.aws.amazon.com/.

## Technical details

* System: (NixOS: 17.03)
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1556.4d1e1d07f9
* Sandboxing enabled: no

**Comment by ksallberg** [comment]
I encountered this yesterday. Today I tried the nixos-install program when my computer was connected to another network, and everything worked. Too low timeout on curl? Or on something

**Comment by l0b0** [comment]
I'm still seeing this. To reproduce in the default GitLab CI Docker container:

```console
$ docker run --entrypoint=bash --interactive --rm --tty ruby:2.5
root@7c137a667605:/# install --directory --mode=755 /nix
root@7c137a667605:/# curl -L https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2619  100  2619    0     0   4054      0 --:--:-- --:--:-- --:--:--  4054
downloading Nix 2.3.14 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.3.14/nix-2.3.14-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.uiuujIQ6V8'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
sh: failed to download 'https://releases.nixos.org/nix/nix-2.3.14/nix-2.3.14-x86_64-linux.tar.xz'
```

The exact same command works fine in the host OS. `curl https://releases.nixos.org/nix/nix-2.3.14/nix-2.3.14-x86_64-linux.tar.xz | wc` also works fine in the container, so the installer must be doing something wrong.
