### ISSUE TITLE
Package request: PINCE

### ISSUE THREAD

**Issue by raidenovich** [NixOS/nixpkgs#275846]
PINCE is a front-end/reverse engineering tool for the GNU Project Debugger (GDB), focused on games. However, it can be used for any reverse-engineering related stuff. PINCE is an abbreviation for "PINCE is not Cheat Engine". PINCE is in development right now, read [Features](https://github.com/korcankaraokcu/PINCE#features) part of the project to see what is done and [Roadmap](https://github.com/korcankaraokcu/PINCE/blob/master/CONTRIBUTING.md#roadmap) part to see what is currently planned. Also, please read [Wiki Page](https://github.com/korcankaraokcu/PINCE/wiki) of the project to understand how PINCE works.

* homepage URL: https://github.com/korcankaraokcu/PINCE
* source URL: https://github.com/korcankaraokcu/PINCE
* license: Unknown License
* platforms: linux

**Comment by eclairevoyant** [comment]
duplicate of #208981
