### ISSUE TITLE
Build failure: stdenv on riscv64-linux: bootstrap-tools needs updating

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#275848]
(this is a copy of [the message I sent on #stdenv:nixos.org](https://matrix.to/#/%23stdenv%3Anixos.org/%24z7I1Wl4iI_ZRCEVy_PnOWeF0I9S8w9pPTw_21ZHjHd4?via=matrix.org&via=kde.org&via=matrix.mit.edu&via=nixos.dev))

`stdenv` is currently broken for riscv64-linux in staging due to the 5-year-old assembler in the bootstrap tarball not supporting the vector extension. I built a new one (`freshBootstrapTools.build` on 5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8) and verified that it fixes the issue.

@lovesegfault  I [was told](https://matrix.to/#/%23riscv%3Anixos.org/%24ViH1-25_TiLNUaxXaeppFoYhA4xvaCbIfTl6CRaTtzM?via=nixos.org&via=matrix.org&via=nixos.dev) by @RaitoBezarius to ping you for upload on tarballs.nixos.org

Related: #253713

**Comment by lovesegfault** [comment]
Can you produce a PR in the style of https://github.com/NixOS/nixpkgs/pull/188334?

**Comment by SeTSeR** [comment]
> (this is a copy of [the message I sent on #stdenv:nixos.org](https://matrix.to/#/%23stdenv%3Anixos.org/%24z7I1Wl4iI_ZRCEVy_PnOWeF0I9S8w9pPTw_21ZHjHd4?via=matrix.org&via=kde.org&via=matrix.mit.edu&via=nixos.dev))
> 
> `stdenv` is currently broken for riscv64-linux in staging due to the 5-year-old assembler in the bootstrap tarball not supporting the vector extension. I built a new one (`freshBootstrapTools.build` on [5a09cb4](https://github.com/NixOS/nixpkgs/commit/5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8)) and verified that it fixes the issue.
> 
> @lovesegfault I [was told](https://matrix.to/#/%23riscv%3Anixos.org/%24ViH1-25_TiLNUaxXaeppFoYhA4xvaCbIfTl6CRaTtzM?via=nixos.org&via=matrix.org&via=nixos.dev) by @RaitoBezarius to ping you for upload on tarballs.nixos.org
> 
> Related: #253713

Also it seems that link to commit currently points somewhere else, could you fix it?

**Comment by fgaz** [comment]
@lovesegfault I opened #282517 

---

@SeTSeR the link looks correct to me, though I based my pr on a newer commit

**Comment by SeTSeR** [comment]
> @SeTSeR the link looks correct to me, though I based my pr on a newer commit

I'm sorry, I thought it was link to commit with updated `bootstrapFiles`, not to commit it was based on.
