### ISSUE TITLE
Updates for LAMMPS package description

### ISSUE THREAD

**Issue by akohlmey** [NixOS/nixpkgs#275897]
With reference to
https://github.com/NixOS/nixpkgs/blob/30cd89625c46c801946da2c5d249dc5c0cb37da5/pkgs/applications/science/molecular-dynamics/lammps/default.nix#L111
please consider the following updates:

- The LAMMPS homepages is at https://www.lammps.org
- The LAMMPS license is GPL-2.0  *not* GPL-2.0 or later.

**Comment by eclairevoyant** [comment]
Please feel free to submit a PR :)
