### ISSUE TITLE
Package Kythe

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#27590]
I tried to package kythe (http://www.kythe.io/) this weekend but ultimately it became too difficult for me to complete. 

I am making this ticket to attach how far I got such that if anyone else needs this package then they can try to continue from where I got to.

https://gist.github.com/anonymous/c2eedb1b7a0da4d139b248b9bb175755

The error was 

```
ERROR: Process exited with status 126.
```

at an early stage of running bazel build.

**Comment by robinp** [comment]
+@creachadair FYI. Maybe there's a Nix enthusiast lying around :)

**Comment by prusnak** [comment]
This was closed via https://github.com/NixOS/nixpkgs/pull/45778 right?

**Comment by xeji** [comment]
Seems this was done a long time ago.
