### ISSUE TITLE
Build failure: cryptowatch-desktop

### ISSUE THREAD

**Issue by kirillrdy** [NixOS/nixpkgs#275941]
### Steps To Reproduce

1. build cryptowatch-desktop

### Additional context

download url redirects to a blog

### Notify maintainers

@kashw2 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
As of September the 30th 2023, Cryptowatch was sunset and users were advised to use their parent companies offering Kraken Pro. I'll create a pull request to remove cryptowatch from nixpkgs as there aren't any archives available that contain it that are reliable
