### ISSUE TITLE
Build failure: stig

### ISSUE THREAD

**Issue by ppom0** [NixOS/nixpkgs#275914]
### Steps To Reproduce

1. build *stig*

### Build log

```
error: asynctest-0.13.0 not supported for interpreter python3.11
```

### Additional context

I got this when switching from 23.05 to 23.11

### Notify maintainers

@doronbehar 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 23.11 (Tapir), 23.11.2130.d65bceaee0fb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - channels(ao): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment]
Thanks for the report, this is supposed to be fixed in https://github.com/NixOS/nixpkgs/pull/276014 . I will wait for Darwin CI to be green there and merge it. Ping me if I forget. Follow that PR at:

https://nixpk.gs/pr-tracker.html?pr=276014

**Comment by ppom0** [comment]
Great, thanks!
