### ISSUE TITLE
Feature request: Allow overriding ollama's llama-cpp version

### ISSUE THREAD

**Issue by alxpettit** [NixOS/nixpkgs#275930]
Would be ideal to have an 'escape-hatch' for using `nixpkgs` `ollama`, but with custom `llama-cpp` versions via `.override`. As it stands, you're forced to use an overlay, which can be bad ergonomics for many applications.

@dit7ya @elohmeier

**Comment by SomeoneSerge** [comment]
You can override `version` and `src` via `overrideAttrs`, as long as you consistently use `finalAttrs` in the package expression: https://github.com/NixOS/nixpkgs/blob/bfbfb344598544058481e254b9f0f174d05b5e6a/pkgs/by-name/ll/llama-cpp/package.nix#L46

**Comment by alxpettit** [comment]
Sorry, my issue was confusingly named. I'm talking about overriding the package version of `llama-cpp` used [here](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/misc/ollama/default.nix#L43).

**Comment by SomeoneSerge** [comment]
H'm. This can be passed in the `.override`, can't it? https://github.com/NixOS/nixpkgs/blob/d65bceaee0fb1e64363f7871bc43dc1c6ecad99f/pkgs/tools/misc/ollama/default.nix#L4

**Comment by alxpettit** [comment]
I... thought it could not, but now that you mention it, I should try that! :P

Sorry, I haven't worked with overrides much.

**Comment by alxpettit** [comment]
Thank you! Looks like it works perfectly :D
