### ISSUE TITLE
Can't set eu keyboard layout

### ISSUE THREAD

**Issue by lluchs** [NixOS/nixpkgs#27597]
## Issue description

The new keyboard layout check introduced to fix #25526 doesn't accept the `eu` layout.

### Steps to reproduce

Put `services.xserver.layout = "eu";` in configuration.nix and try to rebuild. This will work in 17.03 and fail with unstable.

**Comment by fpletz** [comment]
cc @aszlig

**Comment by aszlig** [comment]
Well then, let's fix this once and for all...
