### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#27605]
I am looking at logs like this one:

https://nix-cache.s3.amazonaws.com/log/nghad0vzpmvb7d5g6ca4jsn0a6mrdyw5-vm-test-run-natWithFirewall.drv

```
[...]
syncing
router: running command: sync
router: exit status 0
client: running command: sync
client: exit status 0
server: running command: sync
server: exit status 0
test script finished in 41.62s
cleaning up
killing router (pid 79)
killing client (pid 89)
killing server (pid 101)
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/build/vde2.ctl': Directory not empty
vde_switch: Could not remove ctl dir '/build/vde1.ctl': Directory not empty
```

Do the builds/tests fail because of some directory that cannot be removed?
I was just trying to see what I could do to make the tests pass and some of these failures, I see nothing particularly wrong except for those `vde_switch` outputs at the bottom.
Any ideas?

A comment in #11865 seems to suggest this may be an issue with hard disk space.

**Comment by dtzWill** [comment]
Can you link to the hydra job/jobset you're looking at?

FWIW it seems the complaints about removing vde1.ctl are normal and happen even when this test succeeds (example: http://hydra.nixos.org/build/54274143).

**Comment by NeQuissimus** [comment]
I believe I was looking at https://hydra.nixos.org/eval/1377783

**Comment by dtzWill** [comment]
Looks like that was indeed the evaluation containing the linked log,
here's the specific job:

https://hydra.nixos.org/build/56777957#tabs-summary

Which didn't fail in this evaluation, although looking at the job's history it does seem to be failing sporadically:

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.nat.firewall.x86_64-linux
