### ISSUE TITLE
kitty: single-instance not properly working

### ISSUE THREAD

**Issue by arthsmn** [NixOS/nixpkgs#276031]
### Describe the bug
Kitty with the --single-instance or -1 isn't opening with KDE Plasma keyboard shortcut.

### Steps To Reproduce
1. Copy the .desktop for kitty to ~/.local/share/applications.
3. Change Exec to be `kitty -1`.
4. Set a shortcut to kitty, eg. Meta+Return.
5. Open the first kitty window with the shortcut.
6. Try opening a second window with the shortcut, it just doesn't open anything.

### Expected behavior
Kitty should open and attach itself to the first window.

### Additional context
It doesn't matter if it is -1 or --single-instance, and the behavior was the same in 23.05. Also, launching via the menu doesn't have this problem.

### Notify maintainers

@tex @rvolosatovs @Luflosi @adamcstephens @kashw2 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/50bgi74d890mpkp90w1jwc5g0dw4dccr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Can you reproduce by launching these from the terminal? I use single instance daily on xmonad and river.

**Comment by arthsmn** [comment]
> Can you reproduce by launching these from the terminal? If so, please provide relevant log output.
> 
> I use single instance daily on xmonad and river.

Launching from the terminal works just fine too.

**Comment by Luflosi** [comment]
I don't currently have a NixOS system to try this on but why do you need to copy the .desktop file? Can't you just add kitty to `environment.systemPackages`?

**Comment by arthsmn** [comment]
> I don't currently have a NixOS system to try this on but why do you need to copy the .desktop file? Can't you just add kitty to `environment.systemPackages`?

Because I need to add the `-1` flag.

**Comment by adamcstephens** [comment]
Since this works everywhere but a shortcut, I’m unsure how we can proceed here. It seems unlikely this is a kitty bug and more likely a bug elsewhere in your environment or maybe Plasma itself.

**Comment by arthsmn** [comment]
> Since this works everywhere but a shortcut, I’m unsure how we can proceed here. It seems unlikely this is a kitty bug and more likely a bug elsewhere in your environment or maybe Plasma itself.

I understand, just wanted to confirm if it isn't kitty.

**Comment by adamcstephens** [comment]
You could try digging deeper into logs and see if you can find anything. I also like to wrap shortcut programs in `systemd-cat` to redirect their stdout to the journal. That may be helpful in seeing what’s happening when you hit the key a second time. 

I’m going to close for now. If you find more context please don’t hesitate to add and reopen if it would help.
