### ISSUE TITLE
cinnamon: gpaste-reloaded applet not working

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#276028]
### Describe the bug
gpaste applet is not working in cinnamon, even with `programs.gpaste.enable = true;` set

### Steps To Reproduce
1. Enable cinnamon, install gpaste reloaded applet
2. Enable gpaste: programs.gpaste.enable = true;
3. Reboot, add gpaste applet

### Expected behavior
GPaste applet works as expected

### Screenshots
![screenshot gpaste missing](https://github.com/NixOS/nixpkgs/assets/7735145/f527b28d-1298-4952-94a1-dfc634581e2c)

### Additional context
I added debug logging and the error is `Error: Requiring GPaste, version none: Typelib file for namespace 'GPaste' (any version) not found`
Adding `    services.xserver.desktopManager.cinnamon.sessionPath = [ pkgs.gnome.gpaste ];` did not fix the issue

I think something needs to be added to programs/gpaste.nix to allow gpaste to work under cinnamon

### Notify maintainers
@bobby285271

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05.20231221.e78adfb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/drrjh9wcwlrk2l8zgxsiybrlh39285xc-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
> Adding     `services.xserver.desktopManager.cinnamon.sessionPath = [ pkgs.gnome.gpaste ];` did not fix the issue

Hmmm, does not really use any of the spices applets, might take me a while to actually test. Does sessionPath actually work right now?

https://github.com/NixOS/nixpkgs/blob/afadc52e8084f5d072115ca19ace1f6e662897a1/nixos/modules/services/x11/desktop-managers/cinnamon.nix#L83

I wonder if it should be... `X-Cinnamon`

**Comment by bobby285271** [comment]
> Does sessionPath actually work right now?

Changing the mentioned line to:

```
      services.xserver.displayManager.sessionCommands = ''
        if test "$XDG_CURRENT_DESKTOP" = "X-Cinnamon"; then
            echo "Yesssssssssssssssssss!!!!!!!!!!!!!!"
            true
            ${concatMapStrings (p: ''
              if [ -d "${p}/share/gsettings-schemas/${p.name}" ]; then
                export XDG_DATA_DIRS=$XDG_DATA_DIRS''${XDG_DATA_DIRS:+:}${p}/share/gsettings-schemas/${p.name}
              fi

              if [ -d "${p}/lib/girepository-1.0" ]; then
                export GI_TYPELIB_PATH=$GI_TYPELIB_PATH''${GI_TYPELIB_PATH:+:}${p}/lib/girepository-1.0
                export LD_LIBRARY_PATH=$LD_LIBRARY_PATH''${LD_LIBRARY_PATH:+:}${p}/lib
              fi
            '') cfg.sessionPath}
        else
            echo "Nooooo!!!!!!!!, value is $XDG_CURRENT_DESKTOP"
        fi
      '';
```

Then build nixosTests.cinnamon, I got 

![](https://github.com/NixOS/nixpkgs/assets/20080233/2c94a4f0-2178-4fb9-b4bb-15739c6b0acc)

So looks like XDG_CURRENT_DESKTOP is even not set when we run those lines.

**Comment by bobby285271** [comment]
Asking it to print `env` instead, I guess we probably have workarounds here

![](https://github.com/NixOS/nixpkgs/assets/20080233/cdf9278e-ce4c-4e11-9191-c881016969e5)

**Comment by bobby285271** [comment]
![](https://github.com/NixOS/nixpkgs/assets/20080233/68c3c6d6-01d8-4f08-a131-4b602847016e)

I PR the changes.

For a solution without sessionPath, I imagine *some day* we package Cinnamon spices applets like GNOME and do something like https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20prepend_search_path&type=code :zzz:
