### ISSUE TITLE
service.cloudflared.originRequest.originServerName is not included in the result

### ISSUE THREAD

**Issue by anpin** [NixOS/nixpkgs#276089]
### Describe the bug
The option `service.cloudflared.originRequest.originServerName` doesn't end up in the generated service config.

### Steps To Reproduce
1. Run repro from https://github.com/anpin/cloudflared-bug via  
  ```
nix run github:anpin/cloudflared-bug#check-config
```

### Expected behavior
`originServerName` exists in the config for `cloudflared-tunnel-XXX` systemd service

### Actual behavior
The repro falke returns this config :
```
 {"credentials-file":"/nix/store/lvzg05r5zxq53w26mnipdm58n08dshdw-file","ingress":[{"hostname":"*.example.com","service":"https://localhost:443"},{"hostname":"example.com","service":"https://localhost:443"},{"service":"http_status:404"}],"tunnel":"tun"}
```
### Notify maintainers
@bbigras

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.2, NixOS, 23.11 (Tapir), 23.11.20231122.7e57d92`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(a): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/a/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbsds** [comment]
fixed in #277189
