### ISSUE TITLE
graphite-gtk-theme does not create all themes

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#276115]
### Describe the bug
Currently the [package](https://github.com/NixOS/nixpkgs/tree/nixos-23.11/pkgs/data/themes/graphite-gtk-theme) installs not all graphite themes. The installed ones are:
```
Graphite
Graphite-Dark
Graphite-Dark-hdpi
Graphite-Dark-xhdpi
Graphite-hdpi
Graphite-Light
Graphite-Light-hdpi
Graphite-Light-xhdpi
Graphite-xhdpi
```
These themes show a white line around the edge of the GTK windows that could be annoying for some users.

The missing themes correspond to the one that are generated by `--rimless` argument that should produce themes like `Graphite-Rimless` and `Graphite-Rimless-Dark`. Could you please implement also these `rimless` themes for 23.11 and later repo version?

### Steps To Reproduce
1. Install `graphite-gtk-theme`
2. Set rimless theme like `Graphite-Rimless-Dark`
3. It won't work because missing

### Expected behavior
Graphite Rimless theme works correctly.

### Notify maintainers

@romildo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by romildo** [comment]
According to the documentation, the rimless versions are installed when the install script is given the option `--tweeks rimless`, which has the effect of removing the 2px outline around the windows.

This option does not create themes with different names. The names of the themes are the same, with or without this option. So themes named `Graphite-Rimless` or `Graphite-Rimless-Dark` are never created by the install script.

In order to obtain variations of the basic themes, the package should be overriden. For instance, one can put the following in `environment.systemPackages`:
``` nix
(graphite-gtk-theme.override {
  sizeVariants = [ "compact" ];
  tweaks = [ "nord" "normal" "rimless" ];
  wallpapers = true;
  withGrub = true;
})
```

**Comment by D3vil0p3r** [comment]
Thank you @romildo
The different "names" of themes are given by `-n` argument on `install.sh` script of Graphite. Currently the non-rimless theme (dark) appears like:
![image](https://github.com/NixOS/nixpkgs/assets/83867734/a95b38c4-bf75-4baa-aef7-23a85e338d7d)

while the rimless theme appears like:
![image](https://github.com/NixOS/nixpkgs/assets/83867734/fa18d53e-1f62-4c50-9bd4-470f7e82eeef)

So, it is not only a reduced pixel size, but it is a deletion of that white edge from GTK windows.

I will try to use `override`.
