### ISSUE TITLE
Package request: Delfin

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#276152]
**Project description**

Delfin is a native client for the Jellyfin, written in GTK4/rust

**Metadata**

* homepage URL: https://delfin.avery.cafe/
* source URL: https://codeberg.org/avery42/delfin
* license: GPL 3
* platforms: linux

**Comment by arthsmn** [comment]
Already being worked on here: https://github.com/NixOS/nixpkgs/pull/275607

**Comment by Aleksanaa** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/275607.
