### ISSUE TITLE
Is 'perl 5.24->5.26' planned ?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27610]
Any plans or thoughts to adopt or to reject ```Perl 5.26``` ?

I have no opinion on should we upgrade from ```5.24```, but some of [the changes](https://metacpan.org/pod/release/XSAWYERX/perl-5.26.0/pod/perldelta.pod) look breaking (removal "." from ```@INC```, ...).

**Comment by volth** [comment]
@fpletz What does adding ```17.09 milestone``` mean? To upgrade before ```17.09``` release, to keep old Perl for ```17.09``` or to make a decision before ```17.09``` forking ?

**Comment by fpletz** [comment]
I set the milestone to 17.09, because we should try to make the transition IMHO. I'm not sure though if there are any problems because my perl experience is very limited.

**Comment by copumpkin** [comment]
cc @edolstra who's probably the reason perl is so widespread in the Nix community 😄

**Comment by volth** [comment]
@copumpkin try to simply bump version on staging and see if something fails. nixpkgs has plenty of Perl code so it is a good test by itself.

**Comment by volth** [comment]
```perl-5.24``` [is end-of-life upstream](https://www.cpan.org/src/README.html)

I propose the following migration path:
1. accept https://github.com/NixOS/nixpkgs/pull/42659
2. check  that ```perl526Packages``` and ```perl528Packages``` work
3. wait few weeks
4. switch  ```perlPackages``` from ```perl524Packages``` to ```perl526Packages``` (this would change default ```perl``` too, because it got to top-level as ```inherit (perlPackages) perl```)
5. wait few weeks
6. deprecate ```perl522Packages``` and ```perl524Packages```

**Comment by FRidh** [comment]
#42659 is now in `staging`. Hopefully tomorrow it will go to `staging-next`, and then in a couple of days it should land in `master`.
