### ISSUE TITLE
ibus-setup-hangul in ibus-hangul not working

### ISSUE THREAD

**Issue by demokritos** [NixOS/nixpkgs#27619]
## Issue description
In executing ibus-setup-hangul, got this error message:
```
Traceback (most recent call last):
  File "/nix/store/7mny8v5nq9s5a343imn8r31gmwrj36qc-ibus-hangul-1.5.0/share/ibus-hangul/setup/main.py", line 23, in <module>
    from gi.repository import GLib
ImportError: No module named 'gi'

```

### Steps to reproduce
1. configuration.nix
```
  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    #consoleKeyMap = "us";
    defaultLocale = "en_US.UTF-8";
    consoleUseXkbConfig = true;
    inputMethod = {
      enabled = "ibus";
      ibus = {
        engines = [ pkgs.ibus-engines.hangul ];
      };
    };
  };
```
2. nixos-rebuild switch
3. run ibus-setup-hangul in a shell

## Technical details

* System: NixOS  17.03.1584.48ecdcf598 (Gorilla)
* Nix version: 1.11.11
* Nixpkgs version: 17.03.1584.48ecdcf598
* Sandboxing enabled: build-use-sandbox = false

**Comment by ericsagnes** [comment]
Might be due to 66b05cd4e68408bf9026bb304f344b87c66feec3.

@abbradar What was the reason to remove `pygobject3` from `ibus-hangul` dependencies?

**Comment by abbradar** [comment]
@ericsagnes I think that was because I noticed that it is propagated from some other package, but looking at this now it doesn't seem to be the case. I'll investigate this today!

**Comment by abbradar** [comment]
This seems more deep than I thought. The bug is two-fold:

* `setup.py` script is not patched as needed for Python scripts;
* `pygobject3` should be propagated from `ibus`. However, only its `.dev` output is propagated, so it's not added as a Python library.

I can fix the first one but not sure what to do about the second -- maybe we should change behaviour of this propagation in some way. @FRidh?

**Comment by ciil** [comment]
The same problem appears with anthy, and directly adding the same pyEnv to buildInputs like 6dc4b5229bd85156169be39be376bb85a5fccd0f did in ibus definitely fixes the build fails (tested with both anthy and hangul), but the python environment isn't propagated by itself.
