### ISSUE TITLE
Build failure: pkgsCross.aarch64-multiplatform.kismet

### ISSUE THREAD

**Issue by pete3n** [NixOS/nixpkgs#276165]
### Steps To Reproduce

1. build .#pkgsCross.aarch64-multiplatform.kismet

### Build log

If withPython is the default true, build fails with:
```
       > checking python3 module: setuptools... no
       > configure: error: Missing python setuptools, if you would like to build without python entirely, use --disable-python-tools, otherwise install python setuptools for your python version
```
If withPython is false, build fails with:
```
       > ./configure: line 11058: pkg-config: command not found
       > ./configure: line 11059: pkg-config: command not found
       > checking for libpcap... yes
       > ./configure: line 11159: pkg-config: command not found
       > ./configure: line 11160: pkg-config: command not found
       > checking for protobuf... yes
       > checking for protoc... no
       > configure: error: missing google libprotobuf protoc compiler
```
If pkg-config binary path is set to aarch64 emulated binaries with:
```
  preConfigure = '' 
    export PATH=${pkg-config}/bin/:$PATH 
  ''; 
```
Then the build fails with:
```
       > checking for protoc... no
       > configure: error: missing google libprotobuf protoc compiler
```

If the protobuf compiler paths are set to the aarch64 emulated binaries with:
```
  configureFlags = [                       
    "--disable-wifi-coconut"  # Until https://github.com/kismetwireless/kismet/issues/478
    "--with-protoc=${protobuf}/bin/protoc"
    "--with-protocc=${protobufc}/bin/protoc-c" 
```
Then the build succeeds.

### Additional context

- A proposed solution with a package overlay and modified package is shown in this gist:
https://gist.github.com/pete3n/4d997ee43277d31e2d7ee2a987018f5f

- Submitted a pull request: https://github.com/NixOS/nixpkgs/pull276038 however that might night be appropriate to merge

### Notify maintainers

No maintainers in metadata, but: @hughobrien @NickCao

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-20-amd64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

``` console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.66, NixOS, 23.11 (Tapir), 23.11.1697.781e2a9797ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hughobrien** [comment]
Thanks for tagging me. I don't have an ARM machine to test on, and given the relatively little attention this port gets I'm inclined to take your PR as is. Is there particular concern you have regarding it?

**Comment by NickCao** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/276038
