### ISSUE TITLE
Nondeterministic failures in Go 1.8 derivation on Darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#27611]
From [here](http://hydra.nixos.org/job/nixpkgs/trunk/go_1_8.x86_64-darwin) you can see that it seems to fail more often than it passes. 

Issues:
* A weird crash/timeout issue: [example 1](http://hydra.nixos.org/build/56499873/nixlog/1), [example 2](http://hydra.nixos.org/build/56366990/nixlog/1), [example 3](http://hydra.nixos.org/build/56229173/nixlog/1)
* A test that seems to fail occasionally: [example](http://hydra.nixos.org/build/56722045/nixlog/1) 

1.7 seems quite healthy: http://hydra.nixos.org/job/nixpkgs/trunk/go_1_7.x86_64-darwin

P.S: also found a weird failure on Linux [here](http://hydra.nixos.org/build/56608746/nixlog/1)

**Comment by FRidh** [comment]
And it doesn't build at all on staging https://github.com/NixOS/nixpkgs/issues/27589.

**Comment by therealpxc** [comment]
I think this hit me with Go 1.9.1 on the Darwin nixpkgs 17.09 channel yesterday. I got several failed builds and initially thought the package was broken, but a subsequent build on the same Nixpkgs checkout with the same config worked.

**Comment by matthewbauer** [comment]
Not much we can do about bad tests.
