### ISSUE TITLE
Graphite Theme does not apply in XFCE environment

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#276349]
### Describe the bug
I'm using flakes to deploy a configuration in NixOS consisting of XFCE as desktop environment and Graphite as theme.

The configuration can be found in https://github.com/Athena-OS/athena-nix

and the configuration can be deployed by:
```
sudo nixos-rebuild switch --flake 'github:Athena-OS/athena-nix#xfce'
```
The `xfce` configuration should install also Graphite Theme as specified [here](https://github.com/Athena-OS/athena-nix/blob/main/modules/themes/graphite/default.nix) but after the deployment, Graphite Theme is not applied.

### Steps To Reproduce
1. In NixOS, run `sudo nixos-rebuild switch --flake 'github:Athena-OS/athena-nix#xfce'`
2. Check on a GTK window if the theme is changed

### Expected behavior
Theme applied correctly.

### Notify maintainers
@romildo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
You should use `gtk.theme.package`. Also this is related to how home-manager works, which is less relevant here.

**Comment by D3vil0p3r** [comment]
> You should use `gtk.theme.package`. Also this is related to how home-manager works, which is less relevant here.

Is there a way to set GTK themes with no home-manager?

**Comment by Aleksanaa** [comment]
> Is there a way to set GTK themes with no home-manager?

A forced but not recommended method is to use `GTK_THEME`. You can also try adding in /etc/gtk-3.0/settings.ini:
```ini
[Settings]
gtk-theme-name = <Your theme>
```
But I'm not sure if that works.

**Comment by D3vil0p3r** [comment]
Thank you @Aleksanaa . What I'm noting is is that, since I'm using Thunar (XFCE default one) as File Manager, when I configure GTK Graphite theme as:
```nix
{ pkgs, nixpkgs, home-manager, username, ... }:
{

  home-manager.users.${username} = { pkgs, ...}: {
    home.packages = with pkgs; [
      bibata-cursors
    ];
    gtk = {
      enable = true;
      gtk3.extraConfig.gtk-decoration-layout = "menu:";
      cursorTheme.name = "Bibata-Modern-Ice";
      iconTheme.package = pkgs.tela-circle-icon-theme.override {
        colorVariants = [ "black" ];
      };
      iconTheme.name = "Tela-circle-dark";
      theme.package = pkgs.graphite-gtk-theme.override {
        tweaks = [ "rimless" ];
      };
      theme.name = "Graphite-Dark";
    };
  };
}
```
Thunar window appears like:
![image](https://github.com/NixOS/nixpkgs/assets/83867734/e6a83d99-dbf4-4a7f-8520-0cca5b943f50)

While, if I use Nautilus (GNOME default File Manager) in my NixOS, it correctly is shown as:
![image](https://github.com/NixOS/nixpkgs/assets/83867734/04552588-62dd-4dd0-9f55-91ac549de744)

Thunar Graphite theme should appear like the following one I have in my Arch Linux VM:
![image](https://github.com/NixOS/nixpkgs/assets/83867734/b006f8f4-bcc5-4354-80bd-4ed630a3ab12)

Why Thunar seems to not apply the Graphite theme in NixOS?

**Comment by Aleksanaa** [comment]
I'm not sure. Have you restarted your desktop environment? Thunar theming does work for me, but I'm not using xfce4.

**Comment by D3vil0p3r** [comment]
Yes I restarted. I noted it applies correctly on Thunar if I am on GNOME (as shown in the images above), but not if I am in XFCE... Maybe should I use xfconf settings? Is it possible to deploy by .nix file with home-manager the following xfconf settings? Maybe they could solve the issue in XFCE:
```
    xfconf-query -c xsettings -p /Net/ThemeName -s "$theme_name"
    xfconf-query -c xsettings -p /Net/IconThemeName -s "$icon_theme"
    xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "$cursor_theme"
    xfconf-query -c xfwm4 -p /general/theme -s "Everblush-xfwm"

    # Iterate through the monitors and set the wallpaper
    for x in $(xfconf-query -c xfce4-desktop -lv | grep last-image | awk '{print $1}'); do xfconf-query -c xfce4-desktop -p $x -s $background_theme; done
```

**Comment by Aleksanaa** [comment]
Yes, `xfconf.settings` in home-manager.

**Comment by romildo** [comment]
I have noticed in XFCE that the selected theme in Appearance is not correctly applied if `xsettingsd` is running. In this case the theme specified in the `xsettingsd` configuration is applied.

In my setup I use `xsettingsd` to configure simple desktops or window managers that does not have a specific tool for this purpose.

After disabling `xsettingsd`, theme selecting in XFCE works as expected, and the Graphite theme can be applied successfully.

**Comment by D3vil0p3r** [comment]
Yes, you are correct. I applied `xfconf.settings` expression to apply Graphite.
