### ISSUE TITLE
Build failure: `nginx.override { modules = [ nginxModules.zstd ]; }`

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#276341]
### Steps To Reproduce

1. `nix-build -E 'with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/54aac082a4d9bb5bbc5c4e899603abfb76a3f6d6.tar.gz") { }; nginxStable.override { modules = [ nginxModu
les.zstd ]; }'`

### Build log

https://gist.github.com/nagisa/0267b0da19a134de96d37b78f555c8e1

### Additional context

This is a generic "function is deprecated" error. Is there a strong reason we build nginx with that strict of a check in place?

### Notify maintainers

@SuperSandro2000 @fpletz @ajs124 @raitobezarius

### Metadata

N/A, the reproduction steps are self-contained.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Will be fixed by #271522

Since I can't edit that PRs descripton to close this issue, I am going to close this one and nack people to merge it.
