### ISSUE TITLE
Build failure: dosbox-staging on darwin

### ISSUE THREAD

**Issue by shirok1** [NixOS/nixpkgs#276355]
### Steps To Reproduce

1. build dosbox-staging on darwin

### Build log

Complaining that alsa-lib not available on darwin 

### Additional context

I suggest referencing the derivation of `dosbox-x` in which use `lib.optionals stdenv.hostPlatform.isLinux` to opt-in dependencies

P.S. wonder why the maintenance of this package is separated from `dosbox` and `dosbox-x`

### Notify maintainers

@joshuafern @AndersonTorres

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
> build dosbox-staging on darwin

I don't have a Darwin machine.

> Complaining that alsa-lib not available on darwin

Nice. A full log would be nicer of course, but nice nonetheless.

> P.S. wonder why the maintenance of this package is separated from dosbox and dosbox-x

Wonder why they should be maintained by the same people.
