### ISSUE TITLE
Update request: ArchiSteamFarm 5.4.13.4 → 5.5.0.11

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#276387]
Looks like it now uses .NET 8 which probably made all existing plugins incompatible -> https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.0.11

- Package name: ArchiSteamFarm
- Latest released version: 5.5.0.11

- Current version on the unstable channel: 5.4.13.4
- Current version on the stable/release channel: 5.4.12.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000 @lom

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> Looks like it now uses .NET 8 which probably made all existing plugins incompatible

The package/module has no official way to use plugins, so there is no way to use them unless people are using overlays which should be constructed in a smart way to re-use the same methods as archisteamfarm does.

Anyway, here is the update #276410
