### ISSUE TITLE
libreoffice: offline help doesn't get added.

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#276400]
### Describe the bug
Offline help is not available on Libreoffice, even though `withHelp` flag is enabled by default.

### Steps To Reproduce
1. Add libreoffice to the system packages
2. Notice the offline help is missing
3. Check the source for a potential setting, notice it's enabled by default and nothing ever touches it.
4. scream for 3 months unsure if this is PEBKAC or not

### Expected behavior
Have a toggle to build with help, or have a separate package that has the offline help.

### Additional context
![image](https://github.com/NixOS/nixpkgs/assets/69703458/72dfecae-f226-48ce-9e4e-29f14af46c35)

### Notify maintainers

@7c6f434c (note: raskin leads to an unrelated org, rename?)
cc @vcunat @doronbehar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[hjs@nixfv:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 23.11 (Tapir), 23.11.2082.d02ffbbe834b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

PS: appears i got a double-zero issue id :D

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Thanks for the report, I think this should fix it (haven't tested the full build yet): https://github.com/NixOS/nixpkgs/pull/276434 .

**Comment by doronbehar** [comment]
@FavoritoHJS I waited for CI to be green in #276434 to make sure it doesn't break the build. Could you please test it on your machine, and see if it indeed helped?

**Comment by FavoritoHJS** [comment]
seems like it didn't use the cache so i'm waiting 2 hours for libreoffice to compile... fun!

**Comment by doronbehar** [comment]
Haha yes I know :) That's why I waited for CI to be green - to make sure that at least you won't encounter a build error after hours of building. Ideally, CI would have pushed to an online cache server such as [cachix](https://cachix.org/). See also: https://github.com/NixOS/ofborg/issues/68

**Comment by FavoritoHJS** [comment]
it works. it fucking works.

![image](https://github.com/NixOS/nixpkgs/assets/69703458/f9f93f75-c7c8-4a31-ace4-d2aa77b38472)

**Comment by doronbehar** [comment]
Great, glad I could help :). Follow the PR at https://nixpk.gs/pr-tracker.html?pr=276434 .
