### ISSUE TITLE
libphonenumber: included libgeocoding is not reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#276443]
Building this package multiple times does not yield bit-by-bit identical
results, complicating the detection of Continuous Integration (CI) breaches. For
more information on this issue, visit
[reproducible-builds.org](https://reproducible-builds.org/).

Fixing bit-by-bit reproducibility also has additional advantages, such as
avoiding hard-to-reproduce bugs, making content-addressed storage more effective
and reducing rebuilds in such systems.

#### 1. Build the package

This step will build the package. Specific arguments are passed to the command
to keep the build artifacts so we can compare them in case of differences.

Execute the following command:

```
nix-build '<nixpkgs>' -A libphonenumber && nix-build '<nixpkgs>' -A libphonenumber --check --keep-failed
```

Or using the new command line style:

```
nix build nixpkgs#libphonenumber && nix build nixpkgs#libphonenumber --rebuild --keep-failed
```

#### 2. Compare the build artifacts

If the previous command completes successfully, no differences were found and
there's nothing to do, builds are reproducible.
If it terminates with the error message `error: derivation '<X>' may not be
deterministic: output '<Y>' differs from '<Z>'`, use `diffoscope` to investigate
the discrepancies between the two build outputs. You may need to add the
`--exclude-directory-metadata recursive` option to ignore files and directories
metadata (*e.g. timestamp*) differences.

```
nix run nixpkgs#diffoscopeMinimal -- --exclude-directory-metadata recursive <Y> <Z>
```

#### 3. Examine the build log

To examine the build log, use:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A libphonenumber)
```

Or with the new command line style:

```
nix log $(nix path-info --derivation nixpkgs#libphonenumber)
```

### Additional context

https://reproducible.nixos.org/nixos-iso-gnome-runtime/diff/1db837c65980b8973ef239d7ea3658299519b3d934cbb13fb8e819db8b7754e9-ccaa18dbd02a444df2b3c32ad15ebbb052ad3a7d31b33905c24e636cf98c0a1a.html

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by delroth** [comment]
Updated bug title to match the actual derivation attrpath. Not sure why the pname for `libphonenumber` is just `phonenumber`, we should fix that...

**Comment by raboof** [comment]
> Updated bug title to match the actual derivation attrpath. Not sure why the pname for `libphonenumber` is just `phonenumber`, we should fix that...

:+1: #281168
