### ISSUE TITLE
Build failure: backblaze-b2 on x86_64-darwin

### ISSUE THREAD

**Issue by linyinfeng** [NixOS/nixpkgs#276427]
### Steps To Reproduce

1. `backblaze-b2` on `x86_64-darwin`

<https://github.com/NixOS/nixpkgs/pull/274186/checks?check_run_id=19644084194>

### Build log

<https://logs.ofborg.org/?key=nixos/nixpkgs.274186&attempt_id=3872ed4e-c33c-45ae-bae9-106a02e6cffe>

### Notify maintainers

@hrdinka @kevincox @tomhoule

### Metadata

I don't have a `x86_64-darwin` machine, the failure is discovered by ofborg.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomhoule** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/275980/?

**Comment by kirillrdy** [comment]
> Closed by #275980?

No, that fixes runtime issue  . Darwin still has failing tests
