### ISSUE TITLE
xserver with double NVIDIA Ti-1080 fails to start on NIXOS-23.11

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#276469]
### Describe the bug
I got a black screen when  I tried updating from nixos-22.10 to nixos-23.11. Xorg doesnt start correctly, some errors are present in logs.

### Additional context

I add both devices to xorg in order to be able to use manual fan control (Coolbits option)
Here is the relevant nixos config part:

```
services.xserver = {
     enable = true;
     dpi = 144;
     layout = "us,ru";
     xkbOptions = "grp:caps_toggle";
     xkbModel = "microsoft4000";

     videoDrivers = [ "nvidia" ];
     deviceSection = ''Option "Coolbits" "4"
                       BusID "PCI:75:0:0"
                       Option "AllowEmptyInitialConfiguration" "true"
                     '';
     serverLayoutSection = "Screen \"Screen-nvidia[1]\"";
     extraConfig =
       ''
         Section "Device"
           Identifier "Device-nvidia[1]"
           Driver "nvidia"
           Option "Coolbits" "4"
           Option "AllowEmptyInitialConfiguration" "true"
           BusID "PCI:76:0:0"
         EndSection

         Section "Screen"
           Identifier "Screen-nvidia[1]"
           Device "Device-nvidia[1]"
         EndSection
       '';

     displayManager.sddm.enable = true;
     desktopManager.plasma5.enable = true;
  };
```

I compared kernel logs for my previous installation https://github.com/NixOS/nixpkgs/tree/ea4c80b39be4 and current one https://github.com/NixOS/nixpkgs/tree/d65bceaee0fb and found some errors which weren't present previously:

>  NVRM: This PCI I/O region assigned to your NVIDIA device is invalid:
>                NVRM: BAR1 is 0M @ 0x0 (PCI:0000:4c:00.0)
>  NVRM: This PCI I/O region assigned to your NVIDIA device is invalid:
>                NVRM: BAR2 is 0M @ 0x0 (PCI:0000:4c:00.0)
>  NVRM: This PCI I/O region assigned to your NVIDIA device is invalid:
>                NVRM: BAR3 is 0M @ 0x0 (PCI:0000:4c:00.0)
>  NVRM: This PCI I/O region assigned to your NVIDIA device is invalid:
>                NVRM: BAR4 is 0M @ 0x0 (PCI:0000:4c:00.0)
...
>  NVRM: GPU 0000:4c:00.0: RmInitAdapter failed! (0x22:0x40:762)
>  NVRM: GPU 0000:4c:00.0: rm_init_adapter failed, device minor number 1
>  NVRM: GPU 0000:4c:00.0: RmInitAdapter failed! (0x22:0x40:762)
>  NVRM: GPU 0000:4c:00.0: rm_init_adapter failed, device minor number 1
>  NVRM: GPU 0000:4c:00.0: RmInitAdapter failed! (0x22:0x40:762)
>  NVRM: GPU 0000:4c:00.0: rm_init_adapter failed, device minor number 1
>  NVRM: GPU 0000:4c:00.0: RmInitAdapter failed! (0x22:0x40:762)
>  NVRM: GPU 0000:4c:00.0: rm_init_adapter failed, device minor number 1

And here errors in xserver process I got from journalctl -b (I stripped date and process name)

>  (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:76:0:0.  Please
>  (EE) NVIDIA(GPU-0):     check your system's kernel log for additional error
>  (EE) NVIDIA(GPU-0):     messages and refer to Chapter 8: Common Problems in the
>  (EE) NVIDIA(GPU-0):     README for additional information.
>  (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA graphics device!
>  (EE) NVIDIA(0): Failing initialization of X screen
211a164,174
>  (II) UnloadModule: "nvidia"
>  (II) UnloadSubModule: "glxserver_nvidia"
>  (II) Unloading glxserver_nvidia
>  (II) UnloadSubModule: "wfb"
>  (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:76:0:0.  Please
>  (EE) NVIDIA(GPU-0):     check your system's kernel log for additional error
>  (EE) NVIDIA(GPU-0):     messages and refer to Chapter 8: Common Problems in the
>  (EE) NVIDIA(GPU-0):     README for additional information.
>  (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA graphics device!
>  (II) NVIDIA(GPU-0): Deleting GPU-0
>  (II) NVIDIA(GPU-1): Renaming GPU-1 to GPU-0

### Notify maintainers
@Kiskae @vcunat 

### Metadata
Executed on older system

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.119, NixOS, 22.11 (Raccoon), 22.11.git.ea4c80b39be4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(dvyal): `""`
 - channels(root): `""`
 - channels(test): `""`
 - nixpkgs: `/home/dvyal/nixpkgs`
```

**Comment by Kiskae** [comment]
Thats quite a large jump in versions, but I found the following solution on the nvidia forum: https://forums.developer.nvidia.com/t/nvrm-this-pci-i-o-region-assigned-to-your-nvidia-device-is-invalid/229899

It might be related to the fact that newer drivers support resizable bar, so please try to see if the solution resolves your issue.

**Comment by akamaus** [comment]
@Kiskae thanks. Before that I tried switching the driver and the kernel (separately and simultaneously) to the previous version, to my surprise, the error persisted. I ended up disabling Thunderbolt and enabling "Above 4G Decoding” in BIOS. This helped indeed. No need to tweak versions in nixpkgs.
