### ISSUE TITLE
Cannot extend `lib` anymore

### ISSUE THREAD

**Issue by chapa** [NixOS/nixpkgs#276456]
### Describe the bug

It seems like #257100 introduced an error when we try to override `lib` in `lib.nixosSystem`, like so:
```nix
nixpkgs.lib.nixosSystem {
  # ...
  lib = nixpkgs.lib.extend (final: prev: {
    # custom functions...
  });
}
```

It worked well until then, but now I have a `error: undefined variable 'myFunction'` when I try to use a function defined like this.

Actually I'm not really sure this is a real error, maybe that's not the way to do it. If so please tell me (and maybe how this can be achieved in a better way).
There is not much documentation about extending `lib` to be able to use custom functions in modules, I found [this post](https://www.reddit.com/r/NixOS/comments/q8ukbn/is_there_a_simple_way_to_extend_lib/) when googling it, maybe it's not something we can do ?

### Steps To Reproduce

1. Start a REPL with `nixpkgs/nixos-unstable` or `nixpkgs/067ac028170f2fbc2f4f7644b2503f03a670e441` (the first commit introducing the problem):

```console
[user@system:~]$ nix repl --extra-experimental-features 'flakes repl-flake' nixpkgs/nixos-unstable
```

```console
[user@system:~]$ nix repl --extra-experimental-features 'flakes repl-flake' nixpkgs/067ac028170f2fbc2f4f7644b2503f03a670e441
```

2. Evaluate this expression:

```nix
(lib.nixosSystem {

  system = "x86_64-linux";

  lib = lib.extend (final: prev: (
    with builtins; rec {
      mkBinFrom = pkgs: pkg: bin: "${pkgs."${pkg}"}/bin/${bin}";
      mkBin = pkgs: bin: (mkBinFrom pkgs bin bin);
    }
  ));

  modules = [(
    { lib, pkgs, ... }:
    with lib; let
      hello = mkBin pkgs "hello";
    in {
      environment.shellAliases = { h = "${hello}"; };
    }
  )];

}).config.environment.shellAliases
```

### Expected behavior

The output to be:

```nix
{ h = "/nix/store/sbldylj3clbkc0aqvjjzfa6slp4zdvlj-hello-2.12.1/bin/hello"; l = "ls -alh"; ll = "ls -l"; ls = "ls --color=tty"; }
```

### Actual behavior

The following error occurs:

```
       error: undefined variable 'mkBin'

       at «string»:15:15:

           14|     with lib; let
           15|       hello = mkBin pkgs "hello";
             |               ^
           16|     in {
```

### Additional context

This was working fine before #257100, you can test it by opening the REPL with `nixpkgs/8d17fb2bc6a105ddf06b4e20b0ff6829f4bf8863` (the commit just before the merge):

```console
[user@system:~]$ nix repl --extra-experimental-features 'flakes repl-flake' nixpkgs/8d17fb2bc6a105ddf06b4e20b0ff6829f4bf8863
```

### Notify maintainers

@Ma27 @roberth

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 23.11 (Tapir), 23.11.20231220.d65bcea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mirkolenz** [comment]
Luckily, there is already an open PR for this issue 😄

https://github.com/NixOS/nixpkgs/pull/273942

**Comment by chapa** [comment]
Thank you, I didn't think to search in the PRs ! I wasn't the only one apparently :sweat_smile:

**Comment by mirkolenz** [comment]
Indeed! I was affected by this as well and opened yet another PR with the same fixes. This seeks to be a rather popular way of using custom functions.
