### ISSUE TITLE
Update request: opencl-clhpp 2.0.15 → 2023.12.14

### ISSUE THREAD

**Issue by xokdvium** [NixOS/nixpkgs#276448]
Auto-updates for this package seem to fail due to changes to opencl-headers that introduce cmake https://r.ryantm.com/log/opencl-clhpp/2023-12-17.log. Seems to me like https://github.com/NixOS/nixpkgs/pull/254870 should fix this issue and no manual intervention will be needed, but I'm not entirely sure. At the moment this package is very outdated and misses bugfixes https://github.com/KhronosGroup/OpenCL-CLHPP/pull/175 without which software using this library fails to build with certain compiler flags. I'm not sure who to tag here since the package has no maintainers. @lelgenio, this issue seems relevant.

- Package name: opencl-clhpp
- Latest released version: 2023.12.14

- Current version on the unstable channel: 2.0.15
- Current version on the stable/release channel: 2.0.15

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@FRidh @lelgenio

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xokdvium** [comment]
Indeed seems like cmake patch has resolved auto-update issue: https://github.com/NixOS/nixpkgs/pull/277072

**Comment by smancill** [comment]
Will be closed by #335392
