### ISSUE TITLE
(Haskell) hsdev fails to build

### ISSUE THREAD

**Issue by BethAr** [NixOS/nixpkgs#27653]
## Issue description
I'm unable to build hsdev, which requires text-region 0.3.0.0, simple-log 0.9.2 and hformat 0.3.0.0. If i simply install the dependencies, older versions are installed, so I have to specify the versions (e.g. hformat_0_3_0_0), however, hsdev build process is unable to find them.

Here is GHC's error:
```
...
Configuring hsdev-0.2.5.0...
Setup: Encountered missing dependencies:
hformat ==0.3.*, simple-log ==0.9.*, text-region ==0.3.*
builder for ‘/nix/store/z4lp62qncpk68kc6ifhmwd3y3l2gychd-hsdev-0.2.5.0.drv’ failed with exit code 1
error: build of ‘/nix/store/z4lp62qncpk68kc6ifhmwd3y3l2gychd-hsdev-0.2.5.0.drv’ failed
/home/beth/.nix-profile/bin/nix-shell: failed to build all dependencies
```

I was able to build it with stack, though, so I don't know what is wrong.

### Steps to reproduce
Install hsdev:
`nix-env -f '<nixpkgs>' -i -A haskellPackages.hsdev`

Open a nix-shell with hsdev:
`nix-shell -p hsdev`

or even specifying the dependencies:
`nix-shell -p haskellPackages.hformat_0_3_0_0 -p haskellPackages.text-region_0_3_0_0 -p haskellPackages.simple-log_0_9_2 -p haskellPackages.hsdev`

## Technical details

* System: Arch
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre110213.01c3847b9c
* Sandboxing enabled: no

**Comment by cdepillabout** [comment]
This is likely stale.  I'll go ahead and close this, but if anyone is still struggling with this, feel free to post a comment and we can re-open.
