### ISSUE TITLE
[23.11] Commands `w` and `who` are not showing logged-in users in tty* terminals

### ISSUE THREAD

**Issue by someplaceguy** [NixOS/nixpkgs#276512]
### Describe the bug

On NixOS 23.11, when running the `w` or the `who` commands, users logged into tty1 (and tty2, tty3, etc) are not showing up in the output of these commands.

Instead, the following appears on syslog when a user logs in:
```
authpriv.warning login[4202]: Unable to update utmp entry for <username>
```

The problem seems to be that `shadow` 4.14.1 contains a bug that prevents it from updating `/var/run/utmp`. I believe this issue is filed as shadow-maint/shadow#805 and `shadow` 4.14.2 should fix this issue.

Since this can be a security concern, I think #264349 should be backported to 23.11.

### Steps To Reproduce

1. Press Ctrl-Alt-F1 (or F2, F3, etc) to switch to a virtual console
2. Log in as a user
3. Run `w` and/or `who` and observe that the user/terminal combo does not appear in the list of logged in users

### Expected behavior

Users logged into virtual terminals should appear in the output of the `w` and `who` commands.

### Notify maintainers

cc @trofi @marsam 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Good find! Do you want to write a PR against `staging` that pulls in a fix?

**Comment by trofi** [comment]
Another option is for maintainers to add a backporting label to needed commits.

**Comment by lelgenio** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/276559

Still in staging though.
