### ISSUE TITLE
oculante: fails to start (missing opengl)

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#276729]
### Describe the bug

Fails to run due to error:
```
warning: queue 0x55f20471bb30 destroyed while proxies still attached:
  wl_output@14 still attached
  wl_seat@13 still attached
  xdg_activation_v1@12 still attached
  wp_viewporter@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zwp_relative_pointer_manager_v1@8 still attached
  zxdg_decoration_manager_v1@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
Error: "Cannot select a valid OpenGL configuration: not found"
```

### Steps To Reproduce

```
nix run nixpkgs#oculante
```

### Expected behavior

It runs.

### Additional context
Running it with NixGL works. Using an Intel GPU.

### Notify maintainers

@figsoda @dit7ya

### Metadata

Running on NixOS 24.05pre, current nixpkgs revision is 6df37dc6a77654682fe9f071c62b4242b5342e04.

Bumping the version on master to 0.8.6 and building has the same result.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dbeecham** [comment]
Same here. Using nVidia GPU.

```
$ glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
...
```
