### ISSUE TITLE
Package request: apt-mirror

### ISSUE THREAD

**Issue by mfresia** [NixOS/nixpkgs#276763]
**Project description**

A small tool that provides ability to mirror any parts (or even all) of Debian and Ubuntu GNU/Linux distributions or any other apt sources which typically provided by open source developers.

**Metadata**

* homepage URL: https://apt-mirror.github.io/
* source URL: https://github.com/apt-mirror/apt-mirror
* license: [GPL-2.0 license]
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bjornfor** [comment]
Related: We have https://www.aptly.info/ in nixpkgs.
