### ISSUE TITLE
Git's diff-highlight script disappeared (perl)

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#27671]
I'm on `nixos-unstable`, and while I am of course glad that the
channel has now updated, the update appears to have caused the Git
`contrib` script `diff-highlight`, previously found at
`${pkgs.git}/share/git/contrib/diff-highlight/diff-highlight`, to
disappear.

There is a `diff-highlight.perl` in the same directory, which might
work, but it's not executable.

**Comment by 8573** [comment]
Correction: `${pkgs.gitFull}`, not `${pkgs.git}`.

**Comment by 8573** [comment]
I ran `nixos-rebuild`, my Git went from version 2.13.3 to 2.13.2 (!?),
and now `diff-highlight.perl` is gone and `diff-highlight` is back.

**Comment by 8573** [comment]
I ran `nix-channel --update` (as `root`) and rebuilt again, and now
I'm back on Git 2.13.3, `diff-highlight` is gone, and
`diff-highlight.perl` is back.

**Comment by FRidh** [comment]
See upstream https://github.com/git/git/commit/0c977dbc8180892af42d7ab9235fd3e51d6c4078.
Apparently it needs to be build by the Makefile.
