### ISSUE TITLE
Steam games fail to launch

### ISSUE THREAD

**Issue by r3n3gad3p3arl** [NixOS/nixpkgs#276755]
### Describe the bug
When the play button is pressed, Steam will briefly act like the game is launching before stopping the process, as if you didn't even try to open a game in the first place. This has happened for every game I tried to launch. This problem has occurred previously, but it was solved by a reboot. I have tried rebooting, updating, and deleting all Steam-related files in my home folder, but nothing has fixed it so far. No errors appear and I can't find any relevant logs, but I've never had to troubleshoot Steam before.

### Steps To Reproduce
1. Open Steam
2. Attempt to launch a game by pressing the play button

### Expected behavior
Steam launches the game after the play button is pressed.

### Additional context
Steam is installed via the `programs.steam` module.

### Notify maintainers

@jagajaga @jonringer @mkg20001

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05.20231222.6df37dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Did you do any rebuilds between rebooting and starting steam? Or are you starting steam right after logging in?

**Comment by r3n3gad3p3arl** [comment]
Not exactly sure what you're asking, but I have done several reboots and rebuilds trying to solve this problem. I always reboot after rebuilding also.

**Comment by TalkierTick9904** [comment]
Hi! After the update, my games also stopped working, if you launch Steam through the terminal, you can see this error:
`x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.545.29.06 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH`
I think it's related to #273064

**Comment by jonringer** [comment]
are you running intel, amd, or nvidia? is your `services.xserver.videoDrivers` set appropriately? are you able to play native games (e.g. dota2?)?

**Comment by r3n3gad3p3arl** [comment]
> I think it's related to #273064

Yes, I get that error as well. I've got a full log of launching Steam and trying to open a game here.

```
steam.sh[781811]: Running Steam on nixos 24.05 64-bit
steam.sh[781811]: STEAM_RUNTIME is enabled automatically
setup.sh[781889]: Steam runtime environment up-to-date!
steam.sh[781811]: Steam client's requirements are satisfied
[2023-12-26 20:29:11] Startup - updater built Dec  8 2023 00:32:59
[2023-12-26 20:29:11] Startup - Steam Client launched with: '/home/meow/.local/share/Steam/ubuntu12_32/steam'
12/26 20:29:11 Init: Installing breakpad exception handler for appid(steam)/version(1702079146)/tid(781943)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-12-26 20:29:11] Loading cached metrics from disk (/home/meow/.local/share/Steam/package/steam_client_metrics.bin)
[2023-12-26 20:29:11] Using the following download hosts for Public, Realm steamglobal
[2023-12-26 20:29:11] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-12-26 20:29:11] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-12-26 20:29:11] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-12-26 20:29:11] Checking for update on startup
[2023-12-26 20:29:11] Checking for available updates...
[2023-12-26 20:29:11] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-12-26 20:29:11] Manifest download: send request
[2023-12-26 20:29:11] Manifest download: waiting for download to finish
[2023-12-26 20:29:12] Manifest download: finished
[2023-12-26 20:29:12] Download skipped: /steam_client_ubuntu12 version 1702079146, installed version 1702079146, existing pending version 0
[2023-12-26 20:29:12] Nothing to do
[2023-12-26 20:29:12] Verifying installation...
[2023-12-26 20:29:12] Performing checksum verification of executable files
[2023-12-26 20:29:13] Verification complete

Steam logging initialized: directory: /home/meow/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe9fa57b0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe9fa3fa0
steamwebhelper.sh[781997]: Runtime for steamwebhelper: defaulting to /home/meow/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[781997]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 28 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 782094
steam-runtime-launcher-service[782094]: E: Can't find session bus: Could not connect: No such file or directory

(steam:781943): libappindicator-WARNING **: 20:29:18.234: Unable to get the session bus: Could not connect: No such file or directory
Steam Runtime Launch Service: steam-runtime-launcher-service pid 782094 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 782213
steam-runtime-launcher-service[782213]: E: Can't find session bus: Could not connect: No such file or directory
BRefreshApplicationsInLibrary 1: 0ms
BuildCompleteAppOverviewChange: 202 apps
RegisterForAppOverview 1: 10ms
RegisterForAppOverview 2: 10ms
Steam Runtime Launch Service: steam-runtime-launcher-service pid 782213 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 782392
steam-runtime-launcher-service[782392]: E: Can't find session bus: Could not connect: No such file or directory
Steam Runtime Launch Service: steam-runtime-launcher-service pid 782392 exited
Steam Runtime Launch Service: steam-runtime-launcher-service keeps crashing on startup, disabling
[2023-12-26 20:31:17] Background update loop checking for update. . .
[2023-12-26 20:31:17] Checking for available updates...
[2023-12-26 20:31:17] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=800087628
[2023-12-26 20:31:17] Manifest download: send request
[2023-12-26 20:31:17] Manifest download: waiting for download to finish
[2023-12-26 20:31:19] Manifest download: finished
[2023-12-26 20:31:19] Download skipped by HTTP 304 Not Modified
[2023-12-26 20:31:19] Nothing to do
/bin/sh\0-c\0/home/meow/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=363970 -- /home/meow/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/meow/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/meow/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/meow/.local/share/Steam/steamapps/common/Clicker Heroes/Clicker Heroes.exe'\0
chdir "/home/meow/.local/share/Steam/steamapps/common/Clicker Heroes"
ERROR: ld.so: object '/home/meow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/meow/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/meow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/meow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/meow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.545.29.06 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/lib64:/lib32:/steamrt/amd64/lib/x86_64-linux-gnu:/steamrt/amd64/lib:/steamrt/amd64/usr/lib/x86_64-linux-gnu:/steamrt/amd64/usr/lib:/steamrt/i386/lib/i386-linux-gnu:/steamrt/i386/lib:/steamrt/i386/usr/lib/i386-linux-gnu:/steamrt/i386/usr/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/kaql9lcb0k3v42gqqdwn39c1332f6kzx-pipewire-1.0.0-jack/lib:/lib:/lib32:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib:/home/meow/.local/share/Steam/steamapps/common/Clicker Heroes", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.545.29.06 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/lib64:/lib32:/steamrt/amd64/lib/x86_64-linux-gnu:/steamrt/amd64/lib:/steamrt/amd64/usr/lib/x86_64-linux-gnu:/steamrt/amd64/usr/lib:/steamrt/i386/lib/i386-linux-gnu:/steamrt/i386/lib:/steamrt/i386/usr/lib/i386-linux-gnu:/steamrt/i386/usr/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/kaql9lcb0k3v42gqqdwn39c1332f6kzx-pipewire-1.0.0-jack/lib:/lib:/lib32:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib:/home/meow/.local/share/Steam/steamapps/common/Clicker Heroes", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.545.29.06 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/lib64:/lib32:/steamrt/amd64/lib/x86_64-linux-gnu:/steamrt/amd64/lib:/steamrt/amd64/usr/lib/x86_64-linux-gnu:/steamrt/amd64/usr/lib:/steamrt/i386/lib/i386-linux-gnu:/steamrt/i386/lib:/steamrt/i386/usr/lib/i386-linux-gnu:/steamrt/i386/usr/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/kaql9lcb0k3v42gqqdwn39c1332f6kzx-pipewire-1.0.0-jack/lib:/lib:/lib32:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib:/home/meow/.local/share/Steam/steamapps/common/Clicker Heroes", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
pressure-vessel-wrap[782605]: W: "/run/current-system/sw/bin/getent" is unlikely to appear in "/run/host"
pressure-vessel-wrap[782605]: W: Found more than one possible libdrm data directory from provider
bwrap: Can't find source path /tmp/dbus-u5BptGucVT: No such file or directory
Uploaded AppInterfaceStats to Steam
```

> are you running intel, amd, or nvidia?

I am on a laptop with Intel and Nvidia graphics.

> is your `services.xserver.videoDrivers` set appropriately?

I have set up PRIME offloading as shown in the NixOS wiki. I have tried to launch both with and without offloading, neither has worked.

> are you able to play native games (e.g. dota2?)?

I just tried opening Quaver and AdVenture Capitalist (native Linux games) and they both worked! So it's only Windows games giving me trouble...

**Comment by Henry-Hiles** [comment]
I'm getting a similar issue. NVIDIA prime too

**Comment by shazow** [comment]
Same issue here, on AMD Radeon 7900 XTX, using the mesa drivers I believe.

Most modern games don't work, tried: Baldur's Gate 3, RDR2, Cyberpunk, Dota 2, Lethal Company, Noita, Kenshi.

But one game did work: Portal 2.

<details><summary>Excerpt of steam stdout</summary>
<pre>
pressure-vessel-wrap[8773]: W: "/run/current-system/sw/bin/getent" is unlikely to appear in "/run/host"
pressure-vessel-wrap[8773]: W: Found more than one possible libdrm data directory from provider
bwrap: Can't find source path /tmp/dbus-bQ7idoGt2b: No such file or directory
Fossilize INFO: Setting autogroup scheduling.
/bin/sh\0-c\0/home/shazow/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1966720 -- /home/shazow/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/mnt/steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/mnt/steam/steamapps/common/Lethal Company/Lethal Company.exe'\0
chdir "/mnt/steam/steamapps/common/Lethal Company"
ERROR: ld.so: object '/home/shazow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shazow/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/shazow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shazow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shazow/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pressure-vessel-wrap[8913]: W: "/run/current-system/sw/bin/getent" is unlikely to appear in "/run/host"
pressure-vessel-wrap[8913]: W: Found more than one possible libdrm data directory from provider
bwrap: Can't find source path /tmp/dbus-bQ7idoGt2b: No such file or directory
Uploaded AppInterfaceStats to Steam
</pre>
</details>

Steam is also installed via `programs.steam.enable = true;`

**Comment by r3n3gad3p3arl** [comment]
Okay, I seem to have fixed the issue.

Considering this is happening on Nvidia and AMD graphics, and that the error should be benign, I don't think this has to do with #273064.

When checking @shazow's logs against mine, we both get an error like this: `bwrap: Can't find source path /tmp/dbus-bQ7idoGt2b: No such file or directory`, indicating an issue with dbus.

I start Hyprland with the command `dbus-run-session Hyprland`. By omitting the first part and just launching with `Hyprland`, I am able to run all Steam games with no issue. This may break other applications (for example, the website links in Anime Game Launcher), but nothing major is affected for me.

I have no idea if this is a bug or my poor understanding of dbus, or if this affects full desktop environments like KDE.

Hope this helps others facing this problem!

**Comment by shazow** [comment]
@r3n3gad3p3arl Good find! I was doing something similar,

```diff
- windowManager.command = "dbus-launch --exit-with-x11 i3"; 
+ windowManager.command = "i3"; 
```

did the trick for me.

**Comment by arh78750** [comment]
Currently having this issue with GDM and Gnome, not sure how I can modify my config in a similar way.

**Comment by maxhille** [comment]
Probably the same issue here (steam fails to find dbus). It is a regression from https://github.com/NixOS/nixpkgs/pull/273068, as in if I apply this patch (removing `/tmp` - isolation), everything is fine as before.

```
diff --git a/pkgs/games/steam/fhsenv.nix b/pkgs/games/steam/fhsenv.nix
index d5b266cece37..1fab38c795e8 100644
--- a/pkgs/games/steam/fhsenv.nix
+++ b/pkgs/games/steam/fhsenv.nix
@@ -10,7 +10,7 @@

 # steamwebhelper deletes unrelated electron programs' singleton cookies from /tmp on startup:
 # https://github.com/ValveSoftware/steam-for-linux/issues/9121
-, privateTmp ? true # Whether to separate steam's /tmp from the host system
+, privateTmp ? false # Whether to separate steam's /tmp from the host system

 , withGameSpecificLibraries ? true # include game specific libraries
 }@args:
```

I fear the the original issue (https://github.com/ValveSoftware/steam-for-linux/issues/9121) would be introduced by this patch again, so for now I will just apply this locally for me.

@tejing1 Maybe you have an idea? Can we give the dbus-session to the isolated `/tmp` somehow? And for the short term, how can I toggle that boolean in my nixos config?

**Comment by tejing1** [comment]
> @tejing1 Maybe you have an idea? Can we give the dbus-session to the isolated `/tmp` somehow? And for the short term, how can I toggle that boolean in my nixos config?

It's probably doable by a similar mechanism to what we did for `XAUTHORITY`. Add some bash code to `buildFHSEnv` to check if the dbus session bus is in `/tmp`, and if so, bind mount it into the container.

As for the short term, you can set `programs.steam.package = pkgs.steam.override { privateTmp = false; };` to disable it, but that will indeed bring back the problem with steam messing up other electron apps.

**Comment by tejing1** [comment]
Posted a PR that should fix this issue.
