### ISSUE TITLE
Update request: Mesa 23.1.9 → 23.3.1

### ISSUE THREAD

**Issue by Casul51** [NixOS/nixpkgs#276888]
- Package name: Mesa
- Latest released version: 23.3.1

- Current version on the unstable channel: 23.1.9
- Current version on the stable/release channel: 23.1.9

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@primeos 
@vcunat 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
This has already been merged into staging with https://github.com/NixOS/nixpkgs/pull/274177.

**Comment by vcunat** [comment]
You can track merging PR #275620 (to master) or https://nixpk.gs/pr-tracker.html?pr=274177
