### ISSUE TITLE
Documentation: define a convention for shell commands and their outputs

### ISSUE THREAD

**Issue by DanielSidhion** [NixOS/nixpkgs#276829]
## Problem

While working on some documentation on Nixpkgs, I noticed that there doesn't seem to be a convention for showing shell commands and their outputs.

- [This section](https://nixos.org/manual/nixpkgs/unstable/#fun-prependToVar) prepends `$` to the command prompt, and output as a normal, not-indented line.
- [This one](https://nixos.org/manual/nixpkgs/unstable/#fun-stripHash) adds a comment above the command prompt showing what the output is.
- [This section](https://nixos.org/manual/nixpkgs/unstable/#trivial-builder-writeDirectReferencesToFile) uses two different code blocks, one with the command, the other with the output.

Additionally, there are other code blocks to show expressions and their result inside the nix repl:
- [This example](https://nixos.org/manual/nixpkgs/unstable/#function-library-example-lib.asserts.assertMsg) prepends `stderr>` to the (error) output.
- And [this example](https://nixos.org/manual/nixpkgs/unstable/#function-library-example-lib.attrsets.attrByPath) prepends `=>` to the output.

## Proposal

Note that the proposal below was written just to have **some** starting proposal, but not much thought has been given to other alternatives yet.

My current proposal is to adopt the following convention:
- For shell commands and outputs, prepend `$ ` to any lines that are part of the command, and put outputs in their own lines as-is.
  - If the command has line continuations, don't prepend `$ `, but add some indentation to keep it from looking like an output. For example:
    ```
    $ nix-build -A hello '<nixpkgs>' \
      --option require-sigs false \
      --option trusted-substituters file:///tmp/hello-cache \
      --option substituters file:///tmp/hello-cache
    /nix/store/zhl06z4lrfrkw5rp0hnjjfrgsclzvxpm-hello-2.12.1
    ```
- For nix repl expressions, prepend `nix-repl> ` to any lines part of an expression, and put outputs in their own lines as-is.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
Talked about this in the docs team meeting, I think this is a good idea! If you make a PR to describe this convention in the `doc/README.md` I could review/merge it.

I guess very generally, the convention is to use the format as you'd see it in the REPL.
