### ISSUE TITLE
kodi wayland / cage setup unstable

### ISSUE THREAD

**Issue by evilbulgarian** [NixOS/nixpkgs#276855]
### Describe the bug
Hi, after following the wiki and setting up kodi using below, it starts up but after tv is turned off and idle for a while when powering tv back on unable to wake up and seems that kodi crashes. Attaching the crashlog. Also none of the addons i have defined show up attached the error in the kodi.log about that too.

```nix
{ config, pkgs, lib, ... }: {
  users.extraUsers.kodi.isNormalUser = true;
  users.users.kodi.extraGroups = [ "data" "video" "audio" "input" ];
  services.cage.user = "kodi";
  services.cage.program = "${pkgs.kodi-wayland}/bin/kodi-standalone";
  services.cage.enable = true;

  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [ libva ];
  };

  environment.systemPackages = [
    (pkgs.kodi-wayland.passthru.withPackages (kodiPkgs: with kodiPkgs; [
      inputstreamhelper
      inputstream-adaptive
      inputstream-ffmpegdirect
      inputstream-rtmp
      vfs-libarchive
      vfs-rar
      youtube
    ]))
  ];
}
``` 
kodi.log startup:
[kodi_crashlog-20231225_131328.log](https://github.com/NixOS/nixpkgs/files/13768882/kodi_crashlog-20231225_131328.log)

```
2023-12-25 13:13:28.677 T:1100800   error <general>: GetDirectory - Error getting /nix/store/qq2sjxjqi0ncj419dz50agclqxhkz161-kodi-20.2/lib/kodi/addons
2023-12-25 13:13:28.677 T:1100800   error <general>: GetDirectory - Error getting special://xbmcbin/addons
```

### Steps To Reproduce
1) set up kodi as above nix code
2) use kodi then shut off tv
3) start tv to a black screen

### Expected behavior
addons for vfs and inputsream are loaded, and power off / on does not crash kodi.

### Notify maintainers
@ncfavier 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.20231222.1d27032`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/jb3sswbm4h4hh5qwi9pv452775fj25jb-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by evilbulgarian** [comment]
@pks-t , @mguentner , @r-ryantm adding some more maintainers to the issues :)

**Comment by evilbulgarian** [comment]
Got it to work by using xorg instead and getting the addons in this format:
`  services.xserver.enable = true;
  services.xserver.desktopManager.kodi.enable = true;
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "kodi";

  # This may be needed to force Lightdm into 'autologin' mode.
  # Setting an integer for the amount of time lightdm will wait
  # between attempts to try to autologin again. 
  services.xserver.displayManager.lightdm.autoLogin.timeout = 3;

  services.xserver.desktopManager.kodi.package = pkgs.kodi.withPackages (pkgs: with pkgs; [ inputstreamhelper inputstream-adaptive inputstream-ffmpegdirect inputstream-rtmp vfs-libarchive vfs-rar ]);
`

**Comment by pks-t** [comment]
Is there a particular reason why you're not using the GBM variant via
`kodi-standalone`? That completely removes the need to have either
Wayland or X11 running and has been significantly more stable on my side
than either of the other alternatives. I'm using the following service
configuration to achieve this:

```
systemd.services.kodi = let
  package = pkgs.kodi-gbm.withPackages (kodiPkgs: [
    kodiPkgs.inputstream-adaptive
    kodiPkgs.netflix
    kodiPkgs.sendtokodi
    kodiPkgs.youtube
  ]);
in {
  description = "Kodi media center";

  wantedBy = ["multi-user.target"];
  after = [
    "network-online.target"
    "sound.target"
    "systemd-user-sessions.service"
  ];
  wants = [
    "network-online.target"
  ];

  serviceConfig = {
    Type = "simple";
    User = "kodi";
    ExecStart = "${package}/bin/kodi-standalone";
    Restart = "always";
    TimeoutStopSec = "15s";
    TimeoutStopFailureMode = "kill";

    # Hardening
    ...
  };
};
```

**Comment by evilbulgarian** [comment]
Yup tried that as well, but with the GBM version i was getting weird artifacts across top of screen and seemed as it was not accelerated and this in the logs `CDRMAtomic::DrmAtomicCommit - atomic commit failed: Invalid argument kodi`

> Is there a particular reason why you're not using the GBM variant via `kodi-standalone`? That completely removes the need to have either Wayland or X11 running and has been significantly more stable on my side than either of the other alternatives. I'm using the following service configuration to achieve this: ``` systemd.services.kodi = let package = pkgs.kodi-gbm.withPackages (kodiPkgs: [ kodiPkgs.inputstream-adaptive kodiPkgs.netflix kodiPkgs.sendtokodi kodiPkgs.youtube ]); in { description = "Kodi media center"; wantedBy = ["multi-user.target"]; after = [ "network-online.target" "sound.target" "systemd-user-sessions.service" ]; wants = [ "network-online.target" ]; serviceConfig = { Type = "simple"; User = "kodi"; ExecStart = "${package}/bin/kodi-standalone"; Restart = "always"; TimeoutStopSec = "15s"; TimeoutStopFailureMode = "kill"; # Hardening ... }; }; ```

**Comment by evilbulgarian** [comment]
After 24.05 version upgrade and kodi upgrade seems that the issue is gone and egl version works fine.
