### ISSUE TITLE
Maildir option not taken into account in postfix

### ISSUE THREAD

**Issue by P-E-Meunier** [NixOS/nixpkgs#27689]
## Issue description

After seeing the notice about the deprecation of `extraConfig` in `/nixos/modules/services/mail/postfix.nix`, I decided to change my configuration, and spent some time trying to get postfix to still deliver my mail into `~/Maildir`.

I was using `home_mailbox = Maildir/` before. I don't know what the direction is for the new postfix configuration, but not being able to configure that is a problem.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.09pre111388.00512470ec

**Comment by rosefromthedead** [comment]
Still important to me! No idea who to ping though. Do modules not have maintainers in the same way that packages do?

**Comment by rosefromthedead** [comment]
Err, extraConfig was undeprecated, and my use case was fulfilled already anyway. I guess this should be closed.

**Comment by tomodachi94** [comment]
> Err, extraConfig was undeprecated, and my use case was fulfilled already anyway. I guess this should be closed.

Yep, the change was reverted in https://github.com/NixOS/nixpkgs/pull/28883 way back the day.

> No idea who to ping though. Do modules not have maintainers in the same way that packages do?

Normally we ping either
* The maintainers of the associated package, or
* The last few people to make a substantial change to the package,
but I'm not going to do that since this appears to be long-resolved.
