### ISSUE TITLE
tailscale: package is not using option extraUpFlags

### ISSUE THREAD

**Issue by rishid** [NixOS/nixpkgs#276912]
### Describe the bug
Tailscale package is not using the `extraUpFlags` unless `authKeyFile` is set.

### Steps To Reproduce
1. Enable tailscale and set a flag
``` 
  services.tailscale.enable = true;
  services.tailscale.extraUpFlags = ["--ssh" ];
```
2. `nixos-rebuild switch`
3. `ps -ef | grep tailscaled`  ==> no flags are used

### Expected behavior
Flags are used

### Additional context
Code reference: https://github.com/NixOS/nixpkgs/blob/a2c4338855f665358aabd3a307d640d3ce6abd56/nixos/modules/services/networking/tailscale.nix#L112

extraUpFlags is only used inside the if of auth key not being null check.

### Notify maintainers
@evandeaubl @jwygoda @Enzime 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 23.11 (Tapir), 23.11.2130.d65bceaee0fb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rishid** [comment]
@mfrw

**Comment by rishid** [comment]
I don’t think that is adequate as you can run tail scale as server just fine without `authkey` argument. An `authkey` is only valid for up to 90 days.

**Comment by wlcx** [comment]
Sure, but it would be a good start to alert users to the current behavior.

**Comment by aca** [comment]
I was managing personal nixpkgs only because of this issue... (simply patching package doesn't seem to work for modules)
Created PR for this. Hope someone can review this.
