### ISSUE TITLE
Teamviewer: missing service

### ISSUE THREAD

**Issue by bigshaq9999** [NixOS/nixpkgs#276910]
### Describe the bug
Teamviewer daemon is missing
observed in both nix-shell and home-manager installation

### Steps To Reproduce
1. install teamviewer 
2. launch teamviewer

### Expected behavior
systemctl starts teamviewerd.service and teamviewer launches.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/97749920/48a300ab-fc6a-4a45-9c7c-b9af3e3e7aaf)

### Additional context
```console
[user@system:~]$ sudo teamviewer --daemon start

systemctl start teamviewerd.service
Failed to start teamviewerd.service: Unit teamviewerd.service not found.
```

### Notify maintainers
@jagajaga 
@jraygauthier 
@gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 24.05 (Uakari), 24.05.20231214.b29ed10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(bunny): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/bunny/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
`install teamviewer`
Can you give insights how you "installed" it? 
When I was using TeamViewer some weeks ago with the respective module enabled, it was working fine.

**Comment by ifurther** [comment]
Please see the issue #260390

**Comment by bigshaq9999** [comment]
Thank you.
