### ISSUE TITLE
sabnzbd: Can only ever run as user called "sabnzbd"

### ISSUE THREAD

**Issue by cablespaghetti** [NixOS/nixpkgs#276994]
Unfortunately the user and group configuration options do not carry through to the creation of the `/var/lib/sabnzbd` directory, as this is hardcoded to `sabnzbd` for the username. This directory has 700 permissions, meaning the service will not start if you try to run it as a different user.

https://github.com/NixOS/nixpkgs/blob/4ed0df40ea87766dda7ca5ff7095d9dd3cbd1370/nixos/modules/services/networking/sabnzbd.nix#L49C20-L49C27

**Comment by xvrqt** [comment]
Just learned this the hard way >__<;;

**Comment by hubwoop** [comment]
> You can fix this by adding `homeMode = "770"` in the config for the sabnzbd user in the module:
> 
> ```nix
> users.users.sabnzbd = {
>     uid = config.ids.uids.sabnzbd;
>     group = "sabnzbd";
>     description = "sabnzbd user";
>     home = "/var/lib/sabnzbd/"; 
>     homeMode = "770"; # Here's the fix!
>     createHome = true;
> };
> ```
> 
> `770` would give full directory privileges to the sabnzbd user, along with anyone that you add to the sabnzbd group.
> 
> EDIT: Oh my god, I have had to edit this post like 10 times.

Here is an edit for your edit @Nanotwerp, which contains a missing semicolon ;)
