### ISSUE TITLE
Update request: kanata 1.4.0 → 1.5.0

### ISSUE THREAD

**Issue by bmanuel** [NixOS/nixpkgs#276975]
- Package name: kanata
- Latest released version: 1.5.0

- Current version on the unstable channel: 1.4.0
- Current version on the stable/release channel: 1.4.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jian-lin

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jian-lin** [comment]
Already done in https://github.com/NixOS/nixpkgs/pull/276116.  It is in [nixos-unstable-small](https://nixpk.gs/pr-tracker.html?pr=276116) now.

Just wait a few days for it to reach the nixos-unstable branch :)
