### ISSUE TITLE
Update request: python311Packages.django 4.2.7 → 4.2.8

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#276947]
- Package name: python311Packages.django
- Latest released version: 4.2.8

- Current version on the unstable channel: 4.2.7
- Current version on the stable/release channel: 4.2.7

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@mweinelt 

-----

Note for maintainers: Please tag this issue in your PR.
Update also for stable repo.
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Needs to transition through staging, commit is 20 days old.

ac5099c9b02eec030ead87e51fed1dbc0dd7144d
