### ISSUE TITLE
Build failure: OVMF (riscv64-linux)

### ISSUE THREAD

**Issue by Noodlez1232** [NixOS/nixpkgs#277051]
### Steps To Reproduce

1. build *OVMF* for host double "riscv64-linux" on a non-riscv64 machine
2. Observe failure

### Build log

```
error: Host cpu name `riscv64` is not supported in this OVMF derivation!
```

### Additional context

This seems to be due to there [not being a riscv64 suffix listed in the file](https://github.com/NixOS/nixpkgs/blob/8119b4ec158047b3f89ce438c8c8a0bb4afa86fd/pkgs/applications/virtualization/OVMF/default.nix#L30)

### Notify maintainers

@adamcstephens @RaitoBezarius 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231222.6df37dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Would you mind trying to patch this? I know @RaitoBezarius has risc-v, but I don't and it would take me a long time to bootstrap it on my x64 system.

**Comment by Noodlez1232** [comment]
Sorry, I didn't intend to just disappear on this one. Hopefully this gets merged soon though. Thank you @RaitoBezarius
