### ISSUE TITLE
The piwik module has permission errors related to the unix socket it uses.

### ISSUE THREAD

**Issue by dalaing** [NixOS/nixpkgs#27704]
## Issue description

I've worked around #27703 with some manual setup, which I think is OK / not causing this issue.

After that, any attempt to access the piwik virtual host results in a bad gateway error.

The logs for nginx show a permission error of some kind:
```
Jul 28 05:03:02 piwik nginx[1409]: 2017/07/28 05:03:02 [crit] 1434#0: *1 connect() to unix:/run/phpfpm-piwik.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.56.1, server: servername.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/phpfpm-piwik.sock:", host: "servername.tld"
```

### Steps to reproduce

Enable the piwik module and try to connect to the virtual host.

Let me know if I've mangled something / if you want me to try things - I'm keen to get this running.

## Technical details

* System: NixOS 17.03.1606.6bf7904140 (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs versions: nixpkgs:"17.03.1606.6bf7904140" unstable:"17.09pre111304.5328102325"
* Sandboxing enabled: build-use-sandbox = false

**Comment by joachifm** [comment]
cc @florianjacob

**Comment by florianjacob** [comment]
This sounds like phpfpm had problems starting up.
Does `/run/phpfpm-piwik.sock` exist?

What does `systemctl status phpfpm-piwik.service` say?
What does `systemctl status piwik_setup_update.service` say?

**Comment by dalaing** [comment]
The socket exists:
```
$ ls -las /run/phpfpm-piwik.sock 
0 srw------- 1 piwik root 0 Jul 30 22:51 /run/phpfpm-piwik.sock
```

The `phpfpm-piwik` service is running:
```
$ systemctl status phpfpm-piwik.service
● phpfpm-piwik.service - PHP FastCGI Process Manager service for pool piwik
   Loaded: loaded (/nix/store/a3j3qq1smwbdkzw3b1n20ffz0w9hicl0-unit-phpfpm-piwik.service/phpfpm-piwik.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-07-30 22:51:14 UTC; 4min 33s ago
  Process: 1738 ExecStartPre=/nix/store/dnx8gaimmwlxfabisji90zfpsl63zaqr-unit-script/bin/phpfpm-piwik-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 1743 (php-fpm)
   Status: "Processes active: 0, idle: 10, Requests: 0, slow: 0, Traffic: 0req/sec"
    Tasks: 11 (limit: 4915)
   CGroup: /phpfpm.slice/phpfpm-piwik.service
           ├─1743 php-fpm: master process (/nix/store/agy2mp7gvrzaknbbfy75vcn39vhdxx1i-phpfpm-piwik.conf)
           ├─1746 php-fpm: pool piwik
           ├─1747 php-fpm: pool piwik
           ├─1748 php-fpm: pool piwik
           ├─1749 php-fpm: pool piwik
           ├─1750 php-fpm: pool piwik
           ├─1751 php-fpm: pool piwik
           ├─1752 php-fpm: pool piwik
           ├─1753 php-fpm: pool piwik
           ├─1754 php-fpm: pool piwik
           └─1755 php-fpm: pool piwik

Jul 30 22:51:14 piwik systemd[1]: Starting PHP FastCGI Process Manager service for pool piwik...
Jul 30 22:51:14 piwik php-fpm[1743]: [NOTICE] fpm is running, pid 1743
Jul 30 22:51:14 piwik php-fpm[1743]: [NOTICE] ready to handle connections
Jul 30 22:51:14 piwik systemd[1]: Started PHP FastCGI Process Manager service for pool piwik.
Jul 30 22:51:14 piwik php-fpm[1743]: [NOTICE] systemd monitor interval set to 10000ms
```

The setup service ran, but is not still running:
```
$ systemctl status piwik_setup_update.service
● piwik_setup_update.service
   Loaded: loaded (/nix/store/apalx5njnz03hwc0pbpbfp0ld21vqin7-unit-piwik_setup_update.service/piwik_setup_update.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sun 2017-07-30 22:51:14 UTC; 4min 49s ago
  Process: 1731 ExecStart=/nix/store/knsy1sc49p83aasrf1jmczaj95ri1v2x-unit-script/bin/piwik_setup_update-start (code=exited, status=0/SUCCESS)
  Process: 1725 ExecStartPre=/nix/store/vg9kg58p7x5vlbppskcwfi0lc8i0m5l6-unit-script/bin/piwik_setup_update-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 1731 (code=exited, status=0/SUCCESS)

Jul 30 22:51:14 piwik systemd[1]: Starting piwik_setup_update.service...
Jul 30 22:51:14 piwik systemd[1]: Started piwik_setup_update.service.
```
 
There is one thing I did remember over the weekend that might be relevant. I'm running this in NixOps to test it out before I start playing around on our main server, so I've turned off the various SSL / ACME options.

**Comment by florianjacob** [comment]
Could you post your piwik / nginx nixos config, please?

The socket should be owned by nginx, not by piwik. Could it be that you set `piwik.webServerUser` to `piwik`, instead of leaving the `nginx` default?

**Comment by dalaing** [comment]
That would probably be it.

I didn't set a user initially, but got an error about webServerUser being
unknown. After that I got lazy and used the piwik user rather than reading
the module.

I'll retrace my steps when I get to work tomorrow and see how things go
with the nginx user / try to figure out why the default wasn't working for
me.

**Comment by dalaing** [comment]
It looks like `webServerUser` has an example but not a default.

I can address that in a PR if that is helpful.

**Comment by florianjacob** [comment]
Right, I forgot I removed the `default = "nginx";` when I made the nginx option null by default.

I'll try to see whether I can make nginx the default for `webServerUser` *only in case* the nginx option is not null somehow, and see whether I can improve the error to something better than `webServerUser` is unknown.

Also, while “Name of the owner of the ${phpSocket} fastcgi socket for piwik.” is technically correct in the unix permission sense, I see now this could be interpreted in the way that the piwik user should own it, because it's the creator. It would probably better be stated as “Name of the web server user that forwards requests to the ${phpSocket} fastcgi socket for piwik. The user is granted read and write permissions on ${phpSocket}.“ or something like that. Do you think that would clear things up?

**Comment by dalaing** [comment]
That change to the docs would definitely clear things up - although I really should have read the module :)

I've got a potential fix for the default [here](https://github.com/dalaing/nixpkgs/tree/piwik-user-fix) along with the doc change you suggested.  I'm not really set up to test NixOS changes at the moment though, but if it looks good to you I can try to find a way.

It all seems to be working well now - thanks for your help!

**Comment by florianjacob** [comment]
> although I really should have read the module :)

While it's always a good idea, I still want to strive for a module that doesn't require that. 😉 

I don't think `if cfg.services.piwik.nginx == null then null else "nginx";` will still fail at build time, right? But that's definitely something I want to keep, to stop it from failing at runtime. php-fpm's startup will fail if no webServerUser is set.

I think we should not add a default here, but look into whether we can either use something like `if nginx != null and webServerUser attribute does not exist then webServerUser = "nginx" to overwrite the setting in the config part and not the option part. Or if that doesn't work out, directly putting that into the `listen.owner = ${cfg.webServerUser}` part.

Additionally, we should state in the docs of the webServerUser option that it's mandatory if nginx attribute is not used, and in the enable option that either webServerUser or nginx option is mandatory. 
It was shown to me that documenting the fact it's mandatory + no default is the way other modules handle this situation as well.

Do you want to work on this? Alternatively, I think I can take care of this the day after tomorrow.

**Comment by dalaing** [comment]
I probably won't have time to work on this (at least not in the near term) - but I can probably do something dodgy to test changes out via my NixOps setup if that helps.

**Comment by florianjacob** [comment]
My PR at #28749 includes a fix for this.
