### ISSUE TITLE
Plymouth does not start

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#277151]
### Describe the bug
On my work laptop, the boot is often stuck at “Starting Show Plymouth Boot Screen”

(After a timeout, rescue prompt will appear but it will be possible to enter any commands because “cannot open access to console the root account is locked”. If I set `SYSTEMD_SULOGIN_FORCE=1`, I am able to proceed.)

The logs reveal that Plymouth crashed:

```
systemd[1]: plymouth-start.service: Main process exited, core=dumped, status=11/SEGV
systemd-tty-ask-password-agent[249]: Failed to query password: Input/output error
systemd-tty-ask-password-agent[249]: Failed to process password: Input/output error
systemd[1]: dev-disk-[…].device/start timed out.
systemd[1]: Timed out waiting for device /dev/disk/by-uuid/[…].
systemd[1]: Dependency failed for Initrd Root Device
[…]
systemd[1]: Started Emergency Shell.
systemd[1]: Reached target Emergency Mode.
systemd[1]: Reached target Initrd File Systems.
systemd[1]: panic-on-fail.service was skipped because no trigger condition checks were met.
(plym[258]: emergency.service: Executable /nix/store/[…]-systemd-254.6/bin/plymouth missing, skipping: No such file or directory
```

~~Further up, there “Starting Setup Virtual Console” failure (same error code as in https://github.com/NixOS/nixpkgs/issues/125521#issuecomment-1445361794) but not sure if it is relevant.~~ Happens even if I remove `console
font = "Lat2-Terminus16";` which fixes `systemd-vconsole-setup.service`.

### Steps To Reproduce
1. Power on a computer.
2. Notice that full-disk-encryption password prompt never appears.

### Expected behavior
User should be asked for LUKS password, either by Plymouth, or if it crashes, by systemd.

### Additional context

I managed to pinpoint it to plymouth crash with 23.356.9 but the same symptoms appeared in earlier generations as well (although less frequently).

coredumpctl cannot find any coredumps in the emergency shell.

Relevant configuration:

```nix
{
  boot.loader.systemd-boot.enable = true;
  boot.initrd.systemd.enable = true;
  boot.plymouth.enable = true;
}
```

### Notify maintainers

cc @K900 

### Metadata

NixOS 5f64a12a728902226210bf01d25ec6cbb9d9265b

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by misuzu** [comment]
Same issue on https://github.com/NixOS/nixpkgs/commit/5f64a12a728902226210bf01d25ec6cbb9d9265b
