### ISSUE TITLE
github-runner: can't persistently store runner files

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#277188]
### Goal
Our GitHub Actions workflow is designed to build a website on our server and deploy it. However we're unsure about the deployment phase on NixOS.

### What we've tried
Previously the workflow copied the built files into a directory that is served by the webserver, but on NixOS this results in a read-only filesystem error due to strong sandboxing.
We've tried symlinking the build folder, but this only works until the service/server restarts, because the working directory will be cleared when the runner service starts up.

### Potential solutions
Add an option to the github-runner module
- to disable cleaning the working directory on startup
- for specifying paths that are not read-only (if possible)
- that allows running a specified shell script or systemd service after the runner has finished

### Additional context
More details about [our configuration](https://discourse.nixos.org/t/github-runners-cp-read-only-filesystem/36513)

### Notify maintainers

@veehaitch @newAM @thomasjm 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 24.05 (Uakari), 24.05.20231217.91a0070`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11.1115.5de0b32be6e8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thomasjm** [comment]
You can control the sandboxing using [service overrides](https://search.nixos.org/options?channel=23.05&show=services.github-runners.%3Cname%3E.serviceOverrides&from=0&size=50&sort=relevance&type=packages&query=serviceOverrides). For example:

```nix
services.github-runner.serviceOverrides = {
  ReadWritePaths = [
    "/some/path"
  ];
};
```

**Comment by gepbird** [comment]
Thanks @thomasjm, that solved our issue!

Before opening this issue, I was only skimming at the [service.nix](https://github.com/gepbird/nixpkgs/blob/master/nixos/modules/services/continuous-integration/github-runner/service.nix) file, and none of those sandboxing options looked helpful for this issue, I didn't know about where are the other options.  
I feel like some message could be added for `serviceOverrides`, for example "Check out `man 5 systemd.exec` for more options". I'd be happy to open a PR for this if you agree.

**Comment by thomasjm** [comment]
Hmm, the current message says "Modify the systemd service. Can be used to, e.g., adjust the sandboxing options." To me that's enough to start googling systemd options.

I'm not super against it though. (Isn't `man systemd.exec` sufficient?)
