### ISSUE TITLE
Update request: luxcorerender 2.4 → 2.6

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#277104]
- Package name: luxcorerender
- Latest released version: 2.6

- Current version on the unstable channel: n/a
- Current version on the stable/release channel: 2.4
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

There is no maintainer

https://github.com/LuxCoreRender/LuxCore/releases/tag/luxcorerender_v2.6

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L583
