### ISSUE TITLE
elm repl: "elm: freeHaskellFunctionPtr: not for me, guv!"

### ISSUE THREAD

**Issue by sindikat** [NixOS/nixpkgs#277156]
### Describe the bug
I'm on NixOS, using unstable channel.

Weird runtime error when running `elm repl` from `elmPackages.elm` (Elm version 0.19.1). A string is printed out in the beginning + every time a key is pressed:
```
elm: freeHaskellFunctionPtr: not for me, guv! 0x7fb9d66d5fe8
```
This error is very obscure, [googling it returns only 26 results](https://www.google.com/search?q=%22not+for+me%2C+guv%21%22), but most likely has to do with they way Elm was built with Haskell in the NixOS cache.

### Steps To Reproduce
1. Install `elmPackages.elm`
2. Run `elm repl`
3. Observe `elm: freeHaskellFunctionPtr: not for me, guv! 0x7fb9d66d5fe8` every time you press a key

### Additional information

`elm-language-server` is wonky too; e.g. `Dict` from `elm/core` isn't always recognized properly in Spacemacs. I wonder if whatever bug affects `elm repl` affects other Elm packages too.

EDIT: Probably has nothing to do with the `elm repl` error above. I had `Dict.elm` missing from `~/.elm`, which is why LSP couldn't find it. I have removed `./elm-stuff` and `~/.elm`, then re-ran `elm make`, and now `Dict.elm` is there.

### Notify maintainers

@turbomack

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05pre562833.5f64a12a7289`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by turboMaCk** [comment]
Hi. Yes I can reproduce it with no issues on my side as well. Something had to change which lead to this.

**Comment by ggPeti** [comment]
I was just going to open this issue as well. For the time being, a lazy workaround for this annoying output is
```elm repl 2> >(sed -e '/freeHaskellFunctionPtr/,+1d' >&2)```

**Comment by turboMaCk** [comment]
I have a working fix which goes hand in head with update of ghc for building elm. The problem is that there are many intricate dependencies in all the elmPackages and the code quality of elm/default.nix is abysmal so it will still require significant amount of effort to get the fix in without breaking other packages and with adding the minimal necessary tech debt onto the existing pile.

**Comment by turboMaCk** [comment]
I think everything should be now working in #277326 It would be great if you could test it and review it.

**Comment by SiriusStarr** [comment]
> I think everything should be now working in #277326 It would be great if you could test it and review it.

#277326 fixed the issue for me, FWIW, so this issue can probably be closed?

**Comment by turboMaCk** [comment]
thanks for confirmation
