### ISSUE TITLE
Hydra: initial config fails

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27718]
## Issue description

Just now I tried to run Hydra on my workstation. 

### Steps to reproduce

```
  services.postgresql.enable = true;
  services.hydra = {
    enable = true;
    minimumDiskFree = 10;
    minimumDiskFreeEvaluator = 10;
    useSubstitutes = true;
    hydraURL = "foo";
    notificationSender = "foo@foo.foo";
  };

```

and got
```
hydra-init-pre-start[27278]: createuser: could not connect to database postgres: FATAL:  role "root" does not exist
```

## Technical details

NixOS master at a7c8f5e419ba07711c132bf81baaab0e74862cce.

**Comment by FRidh** [comment]
cc @domenkozar is something missing/wrong in the default config?

**Comment by domenkozar** [comment]
Postgresql user changed in master and Hydra is broken.

**Comment by FRidh** [comment]
@domenkozar Hydra as packaged in 17.03 does work?

**Comment by domenkozar** [comment]
It should, but your commit points to master branch.

**Comment by pbogdan** [comment]
Possible duplicate of https://github.com/NixOS/nixpkgs/issues/27314 ?

**Comment by FRidh** [comment]
Indeed a duplicate of #27314.
