### ISSUE TITLE
Degree of @0xABAB ban - isn't it too high?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27711]
I think you overreacted with the degree of banning @0xABAB: currently all his replies in the discussion are hidden (which breaks the threads: people replies to his hidden comments: e.g https://github.com/NixOS/nixpkgs/pull/26805 and many others) and also all tickets and PRs started by him are fully hidden.
It is clear damage.
Are his commits reverted too?

**Comment by abbradar** [comment]
Can you point to the original discussion (I imagine it won't be of much use because @0xABAB's comments are hidden but still)?

**Comment by volth** [comment]
Discussion of what? Of whether to ban and how to do it? I have not seen such a discussion and learned about the ban [from IRC logs](https://botbot.me/freenode/nixos/search/?q=0xABAB). It could be a single person's spontaneous decision.

**Comment by vyp** [comment]
> It could be a single person's spontaneous decision.

IIRC they were banned by @edolstra after history of uncivil behaviour (spanning a few years). This is just off the top of my head so I could be very wrong. I can't find the recent thread/comment where this was justified. :/ IMO you could also argue that their behaviour was clear damage too, so personally I supported the decision. :+1:

Just an idea, but maybe some sort of code of conduct could be considered (maybe via rfc) for the future if this ban feels unfair.

**Comment by volth** [comment]
I do not mind the ban as preventing future posts, but cleaning the history... including removal not only his, but also other's comments just because a ticket was opened by @0xABAB ?

**Comment by edolstra** [comment]
I blocked him from the organization but that does not cause comments/issues to be deleted: https://help.github.com/articles/blocking-a-user-from-your-organization/

I assume he deleted his account or got banned by GitHub.

**Comment by volth** [comment]
That raises questions on GitHub reliability and setting up real-time mirroring/archiving to another platform... :(

**Comment by domenkozar** [comment]
It appears he deleted the account - that's not something we have control over. The inconvenience will go away with time, it's not the end of the world. Honestly, the fact that comments are gone at least removes the toxic flavor from the issues.

Archiving GitHub for such a small issue is not really a priority, but since it's all open, anyone can do it if needed.

I'm going to close this issue before it becomes another bike-shedding discussion, I think we have cleared up the initial question.

**Comment by abbradar** [comment]
FWIW I'd vote for restoring all the data (comments, PRs etc) -- it's not only damage in sense that @volth described but also makes it difficult to find it out exactly why the person was banned. I don't have any opinion on the ban itself.

**Comment by abbradar** [comment]
Argh, sorry, I posted after the conversation was locked.

**Comment by edolstra** [comment]
Strangely, https://help.github.com/articles/deleting-your-user-account/ says:  
> Issues and pull requests you've created and comments you've made in repositories owned by other users will not be deleted - instead, they'll be associated with our Ghost user.
