### ISSUE TITLE
NixOS 23.11 Installer: Include linux driver for RTL8852BE(-VS) WiFi

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#277256]
### Describe the bug

See https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$XLru2D4mtc48bQ-0cslGanK5rkcqFBaygWgq5naxh2s?via=nixos.org&via=matrix.org&via=tchncs.de

TL;DR: User was unable to finish the NixOS installation as their WiFi Driver was not working due to the driver being included in linux-6.2 and the installer using linux-6.1.69 -> Proposing to either bump the kernel version on the installer or backport the driver.

Additionally it might be a good idea to provide an unstable installer for cases alike so that the user doesn't have to build the installer themselves especially in scenarios where the ethernet is not an option and them not having a nix to build it.

### Expected behavior

Just work

### Notify maintainers

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
This is exactly why we have new-kernel installer variants.

**Comment by Kreyren** [comment]
They ain't visible on the NixOS website though and very impractical for a new user to find as it assumes searching hydra for them -> Add them to the website? 

See discussion in nixos-dev https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$bqz0ugvpklYWPd2qKxWe-XVxX8jcoREIYsMLpoFgLgs?via=nixos.org&via=matrix.org&via=nixos.dev
