### ISSUE TITLE
gnome.adwaita-icon-theme incomplete after upgrading to 23.11

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#277208]
### Describe the bug

After upgrading from 23.05 to 23.11 the icons in Evolution look wrong.

![Left: Now, Right: Before](https://github.com/NixOS/nixpkgs/assets/148037/c2356205-1eab-4896-9e33-74ae28d53b1f)

### Steps To Reproduce

Run evolution in 23.11. Odd icons.

Run evolution in 23.05, or in 23.11 with `gnome.adwaita-icon-theme` from 23.05: Icons look right.

### Additional context

Comparing the `strace -e file` I find that it tires to access these directories, which actually differ:
```
~ $ ls /nix/var/nix/profiles/system-37{4,5}-link/sw/share/icons/Adwaita/16x16
/nix/var/nix/profiles/system-374-link/sw/share/icons/Adwaita/16x16:
actions  apps  categories  devices  emblems  emotes  legacy  mimetypes  places  status  ui

/nix/var/nix/profiles/system-375-link/sw/share/icons/Adwaita/16x16:
devices  emblems  mimetypes  places
```
There was an upgrade of the theme in between:
```
~ $ ls -l /nix/var/nix/profiles/system-37{4,5}-link/sw/share/icons/Adwaita
lrwxrwxrwx 1 root root 87  1. Jan 1970  /nix/var/nix/profiles/system-374-link/sw/share/icons/Adwaita -> /nix/store/hmz72yq3xn397r6irkvw660ccjkd76pw-adwaita-icon-theme-44.0/share/icons/Adwaita
lrwxrwxrwx 1 root root 87  1. Jan 1970  /nix/var/nix/profiles/system-375-link/sw/share/icons/Adwaita -> /nix/store/9lw0v9gx0s0qyzgn0jdabgch3lmkrivx-adwaita-icon-theme-45.0/share/icons/Adwaita
```
The [upstream NEWS](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/NEWS?ref_type=heads) don’t mention that stuff got dropped, but “New build system“ sounds suspicious…

Indeed, downgrading to 23.05’s `gnome.adwaita-icon-theme` at least gives me the icons back. 

Maybe the port to the new build system in e7fb19575f6261adbc7dc4c5681424d4f0686ff3 was incomplete somehow?

### Notify maintainers

@bobby285271 @NixOS/gnome 

### Metadata

```
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.20231225.d02d818`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(jojo): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
It is not incomplete, there were intentional cleanups:

> - fullcolor: use scalables instead of large bitmaps, using the app icon toolchain. [#205](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/205)
> - fullcolor: low res only at 16x16, lean onto the scalables for everything else

Evolution switching to symbolic icons is unrelated and can be changed back in _Preferences_ → _Apperance_.

**Comment by nomeata** [comment]
Thanks for the help and sorry for the noise in this case, I'll try this later.
