### ISSUE TITLE
List of dead URLs in .nix files

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27722]
## Issue description

https://repology.org/repository/nix_unstable/problems

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by FRidh** [comment]
Closing this because it doesn't warrant a separate issue. 
https://github.com/NixOS/nixpkgs/issues/27723
