### ISSUE TITLE
Update request: mesa 23.1.9 → 23.3.2

### ISSUE THREAD

**Issue by itsvic-dev** [NixOS/nixpkgs#277339]
- Package name: mesa
- Latest released version: 23.3.2
- Current version on the unstable channel: 23.1.9
- Current version on the stable/release channel: 23.1.9
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@primeos @vcunat

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by itsvic-dev** [comment]
nvm https://github.com/NixOS/nixpkgs/pull/275620

**Comment by vcunat** [comment]
Yes, that one has 23.3.1 so far.
