### ISSUE TITLE
invidious settings are not applied

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#277359]
### Describe the bug
I have tried changing default invidious settings in different ways, however they do not have any effect.

### Steps To Reproduce
1. add the following settings in configuration.nix:
```
services.invidious.enable = true;
  services.invidious.settings = lib.mkForce {
    check_tables = true;
    db = {
      dbname = "invidious";
      host = "";
      password = "";
      port = 5432;
      user = "invidious";
    };
    host_binding = "0.0.0.0";
    default_user_preferences = {
      locale = "da";
      region = "DK";
    };
    captions = [
      "Danish"
      "English"
      "English (auto-generated)"
    ];
  };
```
2. or the same settings using the extra settings file:
`services.invidious.extraSettingsFile = "/etc/nixos/invidious-settings.json";`

content of invidious-settings.json:
```
{
  "default_user_preferences": {
    "locale": "da",
    "region": "DK"
  },
  "captions": [
    "Danish",
    "English",
    "English (auto-generated)"
  ]
}
```

### Expected behavior
The interface to be localized in danish by when the settings are applied
### Additional context

I think there is an issue with the way the settings are loaded.
The genrated start script: /nix/store/9nckxbwc7nlkmn9rl9nz19fhg28q52v9-unit-script-invidious-start/bin/invidious-start
Contains:

```

#!/nix/store/q8qq40xg2grfh9ry1d9x4g7lq4ra7n81-bash-5.2-p21/bin/bash
set -e
configParts=()
configParts+=("$(/nix/store/xdmynnfk2f5c8z39wrh7h216lhh91bjq-jq-1.7-bin/bin/jq -R '{"hmac_key":.}' <"/var/lib/invidious/hmac_key")")
configParts+=("$(< '/nix/store/v8arflk7khkfqiv4119917f4qf9ziapq-invidious-settings')")
configParts+=('{"port":3000}')
export INVIDIOUS_CONFIG="$(/nix/store/xdmynnfk2f5c8z39wrh7h216lhh91bjq-jq-1.7-bin/bin/jq -s 'reduce .[] as $item ({}; . * $item)' <<<"${configParts[*]}")"
exec /nix/store/xp3189bxj62wvrnsz9kbzcya881lkyva-invidious-unstable-2023-12-06/bin/invidious
```
And I believe there are issues with the quotes not being properly used (some need to be escaped), I tried modifying the install script to solve the issues with the quotes, but invidious still does not load my settings.

Can't think of anything that might be wrong.

### Notify maintainers
@infinisil @sbruder

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05.git.0654bfb1e43cM`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
You can check the config that's being used like this:
```
sudo cat /proc/$(pgrep invidious)/environ | grep -z CONFIG
```

Does this include your settings?

**Comment by dasj19** [comment]
@infinisil Yes, the setings are there
```

INVIDIOUS_CONFIG={
  "hmac_key": "<REDACTED>",
  "captions": [
    "Danish",
    "English",
    "English (auto-generated)"
  ],
  "check_tables": true,
  "db": {
    "dbname": "invidious",
    "host": "",
    "password": "",
    "port": 5432,
    "user": "invidious"
  },
  "default_user_preferences": {
    "locale": "da",
    "region": "DK"
  },
  "host_binding": "0.0.0.0",
  "port": 3000
}
```

**Comment by 999eagle** [comment]
@dasj19 As documented in Invidious' [example configuration](https://github.com/iv-org/invidious/blob/97c4165f55c4574efb554c9dae8d919d08da1cdd/config/config.example.yml#L485), the `default_user_preferences` only apply to users connecting without a preferences cookie, so you need to clear your cookies for the localization to apply to you. As your custom configuration appears correctly in the `INVIDIOUS_CONFIG` environment variable, I don't think this is a bug of the NixOS module.
Can you please clear your cookies (or at least the one called `PREFS`) for your Invidious instance and try again?

**Comment by dasj19** [comment]
Ok, it turns out that it was not a bug in invidious packaging but my poor configuration which did not take account for passing cookies through the proxy I used. Sorry for the noise.
