### ISSUE TITLE
python3.6-deluge-1.3.13 does not install

### ISSUE THREAD

**Issue by grantwwu** [NixOS/nixpkgs#27757]
## Issue description
python3.6-deluge-1.3.13 does not install

### Steps to reproduce
```
grantwu@allegheny:~ ⇒ nix-env -i python3.6-deluge-1.3.13

installing ‘python3.6-deluge-1.3.13’
error: pygtk-2.24.0 not supported for interpreter python3.6m
(use ‘--show-trace’ to show detailed location information)
```

## Technical details

* System: Ubuntu 16.04.2 LTS
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`): "17.09pre111388.00512470ec"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`): "grep: /etc/nix/nix.conf: No such file or directory" (What am I supposed to do here?)

**Comment by grahamc** [comment]
This is specifically interesting, as `nix-env -qa` listed it as an option cc @FRidh

**Comment by grantwwu** [comment]
```grantwu@allegheny:~ ⇒ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
grantwu@allegheny:~ ⇒ nix-env -qa '.*deluge.*'
grantwu@allegheny:~ ⇒ nix-env -qa '.*deluge.*' | cat
python2.7-deluge-1.3.13
python2.7-deluge-1.3.13
python3.6-deluge-1.3.13
```

**Comment by bennofs** [comment]
This is because `deluge` does not specify that it only works for `python2`. It fails to install because one of its dependencies only works for Python2, but `nix-env` doesn't check `(propagated)BuildInputs`, it only needs `.name`.

**Comment by cleverca22** [comment]
`python36Packages.deluge.name` evals but `python36Packages.deluge.drvPath` throws an error, maybe nix-env should check both

**Comment by FRidh** [comment]
I've once added a comment to the attribute in `all-packages.nix` stating what should happen:
```
deluge = python2Packages.deluge; # Package should be moved out of python-packages.nix
```

**Comment by FRidh** [comment]
@grantwwu can you open a PR with that change?

**Comment by grantwwu** [comment]
I'll try to get to it tonight
