### ISSUE TITLE
Spyder produces error message in its console window: 'An error ocurred while starting the kernel /nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j‑python3𔂭.11.6/bin/python3.11: Error while finding module specification for 'spyder_kernels.console' (ModuleNotFoundError: No module named 'spyder_kernels')'

### ISSUE THREAD

**Issue by nanophilip** [NixOS/nixpkgs#277507]
### Describe the bug
Spyder starts, but cannot run Python code.

### Steps To Reproduce
1. `nix-shell -p spyder`
2. `spyder`

### Expected behavior
Spyder should start without producing an error message, ready to run Python code.

### Notify maintainers
@gebner 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - channels(x): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nanophilip** [comment]
Interestingly, after updating channels and declaratively installing Spyder, this error does not appear anymore.

**Comment by CUexter** [comment]
i got the same error but i am using flakes
