### ISSUE TITLE
Libargon2 does not properly update LD_LIBRARY_PATH (Fatal error: exception Dl.DL_error("libargon2.so.1: cannot open shared object file: No such file or directory"))

### ISSUE THREAD

**Issue by MarcCoquand** [NixOS/nixpkgs#277559]
### Describe the bug

I currently am trying to use Libargon for my project as a system dependency. It installs without fail, however, I get errors when I try to run my program that depends on it I get the error 

```
Fatal error: exception Dl.DL_error("libargon2.so.1: cannot open shared object file: No such file or directory")
```

I was able to resolve it on linux by adding the flag

```
export LD_LIBRARY_PATH=$(nix eval --raw nixpkgs#libargon2.outPath)/lib:$LD_LIBRARY_PATH
```
However, this doesn't solve the issue for OS X, where  I get the error
```
Fatal error: exception Dl.Dl_error("dlopen(libargon2.so.1, 0x000A): tried: 'libargon2.so.1' (no such file)
```

Which with my limited knowledge I assume is due to it missing from the OS X library path.

**Comment by eclairevoyant** [comment]
> It installs without fail

How are you installing libargon? And can you provide a sample nix expression that reproduces this issue?

**Comment by MarcCoquand** [comment]
Hey! I created a minimal repo here that reproduces the error with direnv.

https://git.sr.ht/~marcc/minimalerror

If you install everything then run 

```
dune build 
dune exec -- _build/default/bin/main.exe
```
Then you will get the error I posted above. It includes the nix flake and everything.

**Comment by MarcCoquand** [comment]
This is caused by a downstream issue, where the library I use does not correctly reference libargon2 (https://github.com/ocaml/opam-repository/pull/24314). As such I am closing this.
