### ISSUE TITLE
kubernetes-helm defaults to kubeVersion v1.20.0

### ISSUE THREAD

**Issue by acelinkio** [NixOS/nixpkgs#277657]
### Describe the bug
Helm defaults to a kubeVersion 1.20.0, which is 3 years old.  

### Steps To Reproduce
1. `nix-shell -p kubernetes-helm`
2. `helm template argocd argo-cd --repo https://argoproj.github.io/argo-helm`
3. Returns `Error: chart requires kubeVersion: >=1.23.0-0 which is incompatible with Kubernetes v1.20.0`

### Expected behavior
Would expect that helm defaults to a kubeVersion that is apart of the supported Kubernetes compatibility.  helm 3.12 should support something similar to kubeVersion 1.25 accorsing to their version skew, https://helm.sh/docs/topics/version_skew/.  The last version of helm to officially support 1.20 was 5 minor version ago

### Additional context
Unclear where this default version is being defined.  Downloading the corresponding binary directly from get.helm.sh (example: https://get.helm.sh/helm-v3.13.2-linux-amd64.tar.gz) does not encounter this issue

### Notify maintainers
@rlupton20 @edude03 @saschagrunert @Frostman @diegobfernandez @techknowlogick 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.133.1-microsoft-standard-WSL2, NixOS, 23.11 (Tapir), 23.11.20231210.781e2a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(nixos): `""`
 - channels(root): `"nixos-23.05, nixos-wsl"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by edude03** [comment]
Great timing! I just ran into this issue not to long ago but I'm unsure how
to resolve it.

(On mobile so I'm going from memory) there is a hard coded version in the
helm versions.go or something like that, that can be overridden at build
time. Presumably the helm team does override it. We can of course override
it as well but I'm unsure how we can keep it up to date.

It would be a 1 line patch to fix it for now but my question is, is there
an automated way to keep it at the same version as whatever the helm team
uses

**Comment by gebi** [comment]
@edude03 normally helm takes the k8s version from the go k8s client lib and increments the first part by 1 to arrive at the k8s version.

https://github.com/helm/helm/blob/276121c8693b48978eae5c09602b1e74d9a2a7e6/Makefile#L62
```Makefile
# Define constants based on the client-go version
K8S_MODULES_VER=$(subst ., ,$(subst v,,$(shell go list -f '{{.Version}}' -m k8s.io/client-go)))
K8S_MODULES_MAJOR_VER=$(shell echo $$(($(firstword $(K8S_MODULES_VER)) + 1)))
K8S_MODULES_MINOR_VER=$(word 2,$(K8S_MODULES_VER))

LDFLAGS += -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor=$(K8S_MODULES_MAJOR_VER)
LDFLAGS += -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor=$(K8S_MODULES_MINOR_VER)
LDFLAGS += -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor=$(K8S_MODULES_MAJOR_VER)
LDFLAGS += -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor=$(K8S_MODULES_MINOR_VER)
```

On my current dev system the output is as following (debian sid)
```
K8S_MODULES_VER: 0 29 0
K8S_MODULES_MAJOR_VER 1
K8S_MODULES_MINOR_VER 29
```

In go you can directly set [those variables](https://github.com/helm/helm/blob/276121c8693b48978eae5c09602b1e74d9a2a7e6/pkg/chartutil/capabilities.go#L34) via `LDFLAGS` as the Makefile does, but it's not always clear that those things can just be overridden that easily.

i'd prepare a patch but i've no idea on how to add some script execution into `cluster/helm/default.nix` to fetch the variables :/

**Comment by acelinkio** [comment]
I am not sure how to add in script execution either.  As a low tech eventual solution, opened a pull request to resolve the issue upstream.
