### ISSUE TITLE
ModuleNotFoundError when attempting to override attributes of buildPythonApplication

### ISSUE THREAD

**Issue by Enzime** [NixOS/nixpkgs#27769]
## Issue description
When I try to override the `postFixup` attribute for `qutebrowser`, when I try to run `qutebrowser` from the shell, I just get a `ModuleNotFoundError`.

I suspect this has something to do with `qutebrowser` using `buildPythonApplication` but I'm not too sure, there seems to be a lack of documentation on this topic.

### Steps to reproduce
Add to `configuration.nix`
```
  nixpkgs.config.packageOverrides = pkgs: {
    qutebrowser = pkgs.qutebrowser.overrideAttrs ( oldAttrs: {
      postFixup = ''
        wrapProgram $out/bin/qutebrowser \
          --add-flags "--backend webengine" \
          --add-flags "--basedir ~/.config/qutebrowser/default"
      '';
    });
  };
```
Then from a shell run `qutebrowser`
```
Traceback (most recent call last):
  File "/nix/store/rw40hhmmwf5i84rrspldlsxbbi9236sy-qutebrowser-0.11.0/bin/.qutebrowser-wrapped", line 7, in <module>
    from qutebrowser.qutebrowser import main
ModuleNotFoundError: No module named 'qutebrowser'
```

## Technical details

* System: `17.09pre111447.a7c8f5e419 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.13`
* Nixpkgs version: `17.09pre111447.a7c8f5e419`
* Sandboxing enabled: `false`

**Comment by FRidh** [comment]
The `qutebrowser` expression passes `postFixup` but unfortunately `postFixup` is used also by `buildPythonPackage` or, to be more precise, `mkPythonDerivation`. That means you cannot just replace the `postFixup` phase.

What you can do, is append your `postFixup` to the current, `postFixup = oldAttrs.postFixup + ''...'';`. Note that means it will create another wrapper around it (there are already two).

**Comment by FRidh** [comment]
> I'm not sure if I should open a different issue for this, but this snippet doesn't work at all https://nixos.org/nixpkgs/manual/#how-to-override-a-python-package

- That snippet is for Python libraries in `python-packages.nix`. Its not for *every* Python package (that includes applications) in Nixpkgs
- It indeed needs to be updated because we now have the expression in a separate file. Its a known issue.

Issue is solved so closing.
