### ISSUE TITLE
Netdata: agent was built with --disable-cloud

### ISSUE THREAD

**Issue by LukasKnuth** [NixOS/nixpkgs#277748]
### Describe the bug
The netdata agent installed by the `netdata` package can not be connected to the Netdata Cloud offering. It will fail with the error message:

> This agent was built with --disable-cloud and cannot be claimed

### Steps To Reproduce

**Either** follow the "adding node" steps at https://nixos.wiki/wiki/Netdata, the last step will fail with the above error.

**Or** use the following nix config:

```
config.services.netdata = {
  enable = true;
  claimTokenFile = "/home/lukas/netdata-token.txt";
};
```

When applying the config, the `netdata.service` will fail to start and `journalctl -xeu netdata.service` will show the same error message as above.

### Expected behavior
The netdata service registers with the cloud and becomes available.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
Not knowing much about netdata in particular, but did you try to override the arg `withCloud`. https://github.com/NixOS/nixpkgs/blob/cfc3698c31b1fb9cdcf10f36c9643460264d0ca8/pkgs/tools/system/netdata/default.nix#L11
It seems that the maintainer did not set it as default (which sounds reasonable for me, when opting for smaller derivation)
