### ISSUE TITLE
Update request: superslicer-beta 2.5.59.2 → 2.5.59.5

### ISSUE THREAD

**Issue by kdb424** [NixOS/nixpkgs#277772]
- Package name: superslicer-beta
- Latest released version: 2.5.59.5

- Current version on the unstable channel: 2.5.59.3
- Current version on the stable/release channel: 2.5.59.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@cab404 @Moredread @tmarkus

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matdibu** [comment]
`super-slicer-beta` is currently at `2.5.59.6` on both 24.05 and unstable, can this be closed ?
