### ISSUE TITLE
Package request: Errands

### ISSUE THREAD

**Issue by keirlawson** [NixOS/nixpkgs#277705]
**Project description**

A task manager for Gnome

**Metadata**

* homepage URL: https://github.com/mrvladus/Errands
* source URL: https://github.com/mrvladus/Errands
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tirimia** [comment]
Looking at the README, the author [seems to be against](https://github.com/mrvladus/Errands/blob/7395d1a71eedd7c843ba73679c20268fe5f492e7/README.md?plain=1#L59) packaging it outside of FlatHub. Would it make sense to first open an issue there to see if they would consent to being added to nixpkgs ?

**Comment by keirlawson** [comment]
Ah that's a fair point I hadn't spotted that, I'll ask

**Comment by keirlawson** [comment]
Per the authors wishes, closing this PR
