### ISSUE TITLE
nix-daemon lacks enable option

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27784]
```nix-daemon``` seems the only module without ```enable``` option.
it is always enabled, although it is needless on the machines which do not do any builds (containers, clouds, vms, ...) and have to be disabled out of security concerns (it is written in C++, runs as root and listens a socket)

**Comment by edolstra** [comment]
`systemd.services.nix-daemon.enable = false` should disable the daemon. Adding an explicit option to disable the daemon and the socket is fine with me though. However there is some non-daemon related configuration in nix-daemon.nix that should be enabled even if the daemon is not.
