### ISSUE TITLE
Package request: fritz_exporter

### ISSUE THREAD

**Issue by NyCodeGHG** [NixOS/nixpkgs#277828]
**Project description**

Prometheus Exporter for AVM FritzBox

**Metadata**

* homepage URL: https://github.com/pdreker/fritz_exporter
* source URL: https://github.com/pdreker/fritz_exporter
* license: AL2
* platforms: linux, probably also darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Xtrem532** [comment]
There already is package called `prometheus-fritzbox-exporter`, but it seems abandoned. Does this new package have more/new metrics and/or is compatible with more FritzBox types?

**Comment by NyCodeGHG** [comment]
I couldn't get `prometheus-fritzbox-exporter` to work on a machine where i was running the requested exporter before, so I would prefer to use this one. Not sure if its the models fault, but it's FRITZ!Box 5530 Fiber.
