### ISSUE TITLE
Etheruem wallet

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#27786]
Is there any etheruem wallets in nixpkgs yet or do I need to build from source?  I was going to use
https://github.com/ethereum/mist/releases
I'm suprised no one else has done so yet.  Bitcoin and litecoin both have wallets in altcoins but why not etheruem?

**Comment by rnhmjoj** [comment]
go-ethereum and go-ethereum classic are packaged.

**Comment by ob7** [comment]
Thanks, I didn't know go-etheruem was a wallet.

**Comment by ob7** [comment]
No GUI based wallets though?

**Comment by rnhmjoj** [comment]
It doesn't [look](https://github.com/NixOS/nixpkgs/search?p=1&q=ethereum&type=&utf8=%E2%9C%93) like so. You should open a package request for mist.
I'm not familiar with electron base applications though, maybe someone else will do it.

**Comment by ob7** [comment]
Point me in the right direction, I need to learn this stuff.

**Comment by rnhmjoj** [comment]
Just open another issue requesting to package the software.

**Comment by ob7** [comment]
I meant where I should go to learn how to actually package it.  I must admit I don't know how to create a nix expression from scratch that would install something like mist yet... I wish there was more step by step tutorials on it.... the nixpkgs manual is good, but its lacking little details that noobs like me don't understand yet.

**Comment by rnhmjoj** [comment]
I wouldn't know, maybe try the posts on lethalman's [blog](http://lethalman.blogspot.it/2014/07/nix-pill-6-our-first-derivation.html). I learned mainly by looking at code and with help of the reviewers and other contributors. Also try the #nixos IRC channel if you have some question or just want to talk about something.

**Comment by ob7** [comment]
I think the main disconnect with the learning curve is the understanding of it.  Its simple but you must understand the architecture in order to build onto without having to ask for help each step of the way.  The best code I write is always that which I was able to simplify in the clearest way.  The workmanship behind NixOS speaks of its simplicity but I have yet to understand it otherwise I would know the steps I need to take in order to build any linux package via a nix-expression... wouldn't matter if it was Mist for Ethereum or a completely different package like Xen's virtualization utilities for its guest linux boxes.
