### ISSUE TITLE
Update request: meli 0.8.2 → 0.8.4

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#277887]
- Package name: meli
- Latest released version: 0.8.4

- Current version on the unstable channel: 0.8.2
- Current version on the stable/release channel: 0.8.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@0x4A6F @matthiasbeyer 

-----

Note for maintainers: Please tag this issue in your PR.

simple version bump didn’t work

```diff
diff --git i/pkgs/applications/networking/mailreaders/meli/default.nix w/pkgs/applications/networking/mailreaders/meli/default.nix
index 1ce4c39da7a3..5f4523f5b509 100644
--- i/pkgs/applications/networking/mailreaders/meli/default.nix
+++ w/pkgs/applications/networking/mailreaders/meli/default.nix
@@ -22,15 +22,15 @@
 
 rustPlatform.buildRustPackage rec {
   pname = "meli";
-  version = "0.8.2";
+  version = "0.8.4";
 
   src = fetchgit {
     url = "https://git.meli.delivery/meli/meli.git";
     rev = "v${version}";
-    hash = "sha256-iEHTFofga/HV/1jSAqTsqV55zC22tqI7UW7m4PZgz0M=";
+    hash = "sha256-wmIlYgXB17/i9Q+6C7pbcEjVlEuvhmqrSH+cDmaBKLs=";
   };
 
-  cargoHash = "sha256-ijlivyBezLECBSaWBYVy9tVcSO8U+yGDQyU4dIATR6k=";
+  cargoHash = "sha256-gYS/dxNMz/HkCmRXH5AdHPXJ2giqpAHc4eVXJGOpMDM=";
 
   nativeBuildInputs = [
     pkg-config
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
I tried to compile and it gives me errors related to openssl-sys not finding some file or directory.

**Comment by arthsmn** [comment]
@toastal can you please build the PR to see if there are any other issues?
