### ISSUE TITLE
Update request: watchman 2023.08.14.00 → 2023.12.25.00

### ISSUE THREAD

**Issue by dcecile** [NixOS/nixpkgs#277998]
- Package name: watchman
- Latest released version: 2023.12.25.00

- Current version on the unstable channel: 2023.08.14.00
- Current version on the stable/release channel: 2023.08.14.00

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@kylesferrazza

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Done as part of #285345
