### ISSUE TITLE
Package request: Moneydance

### ISSUE THREAD

**Issue by Steinhagen** [NixOS/nixpkgs#277931]
**Project description**

Moneydance is an easy to use and full-featured personal finance app that doesn't compromise your privacy. With Moneydance, your data is private, encrypted, and never shared.

**Metadata**

* homepage URL: https://infinitekind.com/moneydance
* source URL: -
* license: proprietary - [Moneydance License](https://infinitekind.com/moneydance-end-user-license-agreement)
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lucasbergman** [comment]
Hi, I'm new to Nix and NixOS but managed to package [Moneydance for myself](https://github.com/lucasbergman/home-config/commit/578c89ad2e8784965d9fe76ca3229a906061d88a). There are two problems preventing me from upstreaming it to nixpkgs.

1. Moneydance doesn't have stable download URLs AFAICT. I'm going to open a ticket with them to see if they can help me with that.
2. Something about the JRE and JavaFX, explained in my rant in the commit message. That's going to be a bit more complicated. I'm hoping someone on NixOS Discourse will have some pointers.

**Comment by Steinhagen** [comment]
Hi! Excellent work packaging it! Regarding your problems, here are my 2 cents:

1. Moneydance doesn't have stable download URLs AFAICT. I'm going to open a ticket with them to see if they can help me with that.

I don't know if there is something you can do about. The same issue can be found with other packages, like the Yandex browser where they keep only 1 deb version, so the recipe must be updated every time a new version gets pushed upstream. That is how the upstream does things and having to rely on other 3rd parties that stores multiple versions might not be secure enough for some users.

2. Something about the JRE and JavaFX, explained in my rant in the commit message. That's going to be a bit more complicated. I'm hoping someone on NixOS Discourse will have some pointers.

I think a good idea for this would be to create a PR (if you'd like to upstream your work), and see if the current solution is good enough.

**Comment by lucasbergman** [comment]
Thanks very much. I was actually able to get the second problem sorted ([commit](https://github.com/lucasbergman/home-config/commit/aaef10eb0de0ac7b1eebb085f9f7b8f179f5543a))! I'll ask the Moneydance people about stable URLs (perhaps they have some in their pocket that aren't exposed publicly?), but to your point, even if this is the best we can do, it's much better than nothing.

I'll give you a shout if/when I try to push upstream. If you want to mess with what I have in the meantime, please feel free.

**Comment by Steinhagen** [comment]
Nice one! Regarding the stable link for download, you can browse their stabledl directory: **https://infinitekind.com/stabledl/**

So for the latest version, you would have this link: **https://infinitekind.com/stabledl/2023.3_5064/moneydance_linux_amd64.deb**

**Comment by lucasbergman** [comment]
Oh my, I can't believe I didn't think to even try that! Great catch. With [that fix](https://github.com/lucasbergman/home-config/commit/663cb8974d), I think it's worth trying to upstream, no?

**Comment by Steinhagen** [comment]
I think so. Great job packaging this!

**Comment by lucasbergman** [comment]
Thanks very much! Created https://github.com/NixOS/nixpkgs/pull/283860.
