### ISSUE TITLE
gnome-theme-extra: depends on both gtk2 and gtk3

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#277944]
### Describe the bug

`gnome-theme-extra` currently has a (build- and runtime) dependency on both gtk2 and gtk3.

With GTK 2 being EOL (https://blog.gtk.org/2020/12/16/gtk-4-0/), you'd expect the gtk2 dependency to become increasingly rarely needed.

Would it be possible to avoid the gtk2 dependency for the common case, only enabling it in for the remaining cases where it is necessary? Perhaps by splitting the package or creating an option?

/cc @NixOS/gnome 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by amaxine** [comment]
In the context of really trying to get rid of gtk2, and `gnome-themes-extra` having support for building just with gtk3 this seems like a good idea to default to building without gtk2. That said, should we be including this with gnome by default at all? It seems like everything it provides that's still even vaguely relevant is not really meant to be supported.

**Comment by jtojnar** [comment]
It is no longer part of [gnome-core-shell](https://gitlab.gnome.org/GNOME/gnome-build-meta/blob/gnome-45/elements/core/meta-gnome-core-shell.bst), it should have been removed from `gnome.nix` a while ago: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/599
