### ISSUE TITLE
Libreoffice fails to launch

### ISSUE THREAD

**Issue by spacebanana420** [NixOS/nixpkgs#277900]
### Describe the bug
Libreoffice instances (writer, calc, etc) fail to launch. When launching the instances or trying to open a document file with them, the Libreoffice banner/loading bar shows up for a short moment and then goes away, no libreoffice process was hanging when I checked with htop. If you launch ```libreoffice``` through the terminal, there's no error output.

### Steps To Reproduce
1. Add ```libreoffice``` to your system packages
2. Attempt to launch Libreoffice

### Expected behavior
Libreoffice is supposed to load and open.

### Additional context
Package ```libreoffice-qt``` didn't work either.

### Notify maintainers
@7c6f434c

### Metadata
```console
[space@CirnOS:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(space): `"nixos"`
 - channels(root): `"nixos-23.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eliandoran** [comment]
@spacebanana420 , I had the same issue a while ago. Can you confirm that there is actually no LibreOffice window? On my side I had the "file recovery" dialog opening somewhere in the background.

**Comment by spacebanana420** [comment]
I couldn't find anything, but after another reboot the recover window popped up and now I can launch libreoffice again
