### ISSUE TITLE
Etcher uses an EOL version of Electron 

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#277911]
### Describe the bug

Etcher uses the dependency "Electron" and this one is at 27.1.3 currently. 
Still, when adding Etcher to my configuration, I get this: 

```
error:
       … while calling the 'head' builtin

         at /nix/store/7m4g91qi56yyfmdx71gzna9rij42yb80-nixos-23.11/nixos/lib/attrsets.nix:922:11:

          921|         || pred here (elemAt values 1) (head values) then
          922|           head values
             |           ^
          923|         else

       … while evaluating the attribute 'value'

         at /nix/store/7m4g91qi56yyfmdx71gzna9rij42yb80-nixos-23.11/nixos/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘electron-19.1.9’ in /nix/store/7m4g91qi56yyfmdx71gzna9rij42yb80-nixos-23.11/nixos/pkgs/development/tools/electron/binary/generic.nix:35 is marked as insecure, refusing to evaluate.
```

### Steps To Reproduce

1. See the version of Electron:

![Screenshot_20231231_134932](https://github.com/NixOS/nixpkgs/assets/6344099/9a558e65-9f4e-4a31-a745-8740162bd3eb)

2. See it being used:

https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/misc/etcher/default.nix#L10

3. Try to rebuild NixOS with Etcher

### Expected behavior

Etcher works 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(cosmos): `""`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
It uses electron 19: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/top-level/all-packages.nix#L8039

I'm assuming this is for compatibility reasons.

**Comment by eclairevoyant** [comment]
Though it seem upstream has some newer prereleases, which could be used, as they have more current electron versions: https://github.com/balena-io/etcher

**Comment by ShalokShalom** [comment]
> It uses electron 19: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/top-level/all-packages.nix#L8039
> 
> I'm assuming this is for compatibility reasons.

Just as some small feedback: Hiding the true dependency that way seems oddly confusing.

**Comment by wegank** [comment]
> > It uses electron 19: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/top-level/all-packages.nix#L8039
> > I'm assuming this is for compatibility reasons.
> 
> Just as some small feedback: Hiding the true dependency that way seems oddly confusing.

The `.override` scheme is the one [currently enforced in nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#changing-implicit-attribute-defaults). I don't like putting `electron_19` in `all-packages.nix` either, but there's nothing I can do about it.

The Etcher upgrade is currently being tracked in #261626.

**Comment by YoshiRulz** [comment]
The package was removed by #295853.
