### ISSUE TITLE
Update request: sonarr 3.0.10.1567 → 4.0.0.748

### ISSUE THREAD

**Issue by dacioromero** [NixOS/nixpkgs#278002]
- Package name: sonarr
- Latest released version: 4.0.0.748
- Current version on the unstable channel: 3.0.10.1567
- Current version on the stable/release channel: 3.0.10.1567
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@fadenb 
@purcell 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by purcell** [comment]
Potentially addressed in #278050.
