### ISSUE TITLE
NetworkManager keep 100% CPU usage after upgraded to 23.11

### ISSUE THREAD

**Issue by xinyifly** [NixOS/nixpkgs#278005]
### Describe the bug

After upgraded to 23.11 from 23.05, the network manager process is keeping at 100% CPU usage.

### Steps To Reproduce

1. Upgrade to 23.11 from 23.05
2. Launch top and sort by CPU usage
3. Note that NetworkManager process CPU usage at 100%

### Expected behavior

NetworkManager process should have a normal CPU usage.

### Screenshots

Under 23.11

![2024-01-01T12:38:57,788763724+08:00](https://github.com/NixOS/nixpkgs/assets/16129465/c9b8410f-b2e1-4deb-a12e-3a5fa132414d)

Under 23.05

![2024-01-01T12:51:03,486082950+08:00](https://github.com/NixOS/nixpkgs/assets/16129465/08ce30f1-fdcf-4909-bd1b-d0087d14b79d)

### Additional context

```
[nix-shell:~]$ lspci | grep -i network
3a:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
```

Provide that I'm using DELL XPS 13 9360

```
[nix-shell:~]$ neofetch --off
xinyifly@dell
-------------
OS: NixOS 23.11.20231225.d02d818 (Tapir) x86_64
Host: Dell Inc. 0PVG6D
Kernel: 6.1.69
Uptime: 8 mins
Packages: 831 (nix-system), 1394 (nix-user), 2 (nix-default)
Shell: bash 5.2.15
Resolution: 1920x1080
WM: sway
Terminal: alacritty
CPU: Intel i5-8250U (8) @ 3.400GHz
GPU: Intel UHD Graphics 620
Memory: 3151MiB / 7683MiB
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20231225.d02d818`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(xinyifly): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bjornfor** [comment]
Maybe NetworkManager got into a weird state? Can you try resetting its state (or run from a live medium)?

**Comment by xinyifly** [comment]
I found that NetworkManger goes up 100% CPU usage once a program using a TUN device is running.
Either I started tailscaled or Clash Meta.
