### ISSUE TITLE
Consider renaming `backblaze-b2`'s executable to `b2`

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#278098]
## Issue description

I've been trying to test backblaze.  
I was initially going to report that the --help is made unreadable by inlining paths into the /nix/store:

```
usages:
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 authorize-account
  [-h] [applicationKeyId] [applicationKey]
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 cancel-all-unfinished-large-files
  [-h] bucketName
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 cancel-large-file
```
I would prefer to see:
```
usages:
b2 authorize-account   [-h] [applicationKeyId] [applicationKey]
b2 cancel-all-unfinished-large-files  [-h] bucketName
```

While looking at the doc, I realized that the executable is supposed to be called `b2` https://www.backblaze.com/docs/cloud-storage-command-line-tools .  
I dont understand why we rename it to the annyoingly long  "backblaze-b2" in 
https://github.com/NixOS/nixpkgs/blob/d7c5da1fa12af001be104bdd22582d0ef3e8282d/pkgs/development/tools/backblaze-b2/default.nix#L72

Apparently there is little overlap:
```
➜ nix-locate -r "bin/b2$"
boost-build.out                                 253,936 x /nix/store/6jlklyg279dabfhjhz9h7393zn3i3cl2-boost-build-4.4.1/bin/b2
```

ccing the maintainers:
@hrdinka @kevincox @tomhoule  

## Technical details

unstable

**Comment by hrdinka** [comment]
Hi @teto

It was named `backblaze-b2` since the initial derivation version to not clash with boost’s b2, see https://github.com/NixOS/nixpkgs/pull/13716#issuecomment-192974083. It also still true that many other distros call it `backblaze-b2` as well. The best course of action would be if you create an alias for yourself.

**Comment by teto** [comment]
I can understand in traditional distributions because they can't overlap different executables but in nixpkgs, you can prioritize packages over others. Let's assume you want boost-build and backblaze at the same time, you can choose one over the other via lib.setPrio . I am now penalized for using the long name `backblaze-b2` while I feel boost-build is more confidential (or used only in dev environments, less likely to end up in global PATH).

**Comment by kevincox** [comment]
A large part of the motivation was compatibility with other distributions who don't have the luxury of ignoring naming conflicts.

Also while in theory multiple executable with the same name can exist with Nix it is still very common to construct a path or symlink tree such that collisions are annoying. For example if you had a build process that would build with b2 then archive to backblaze you would likely have to work around this path conflict.

Overall I still think making the less ambiguous name the default is the best choice. However it would be nice to make it as easy as possible to install with the `b2` name for those who prefer/depend on it. For example maybe we could add support for `backblaze-b2.override { name = "b2"; }`. The default value could remain `backblaze-b2`.

But if the majority of people agree that the "upstream" name is best than I am happy to make `b2` the default name. However it has been packaged this way for years without me hearing any other complaints.

**Comment by kevincox** [comment]
I've updated the title to be a bit more explicit about the issue at hand. It may be best to file a separate issue for the `--help` executable name. I think excluding the path from that name is fairly uncontroversial.

**Comment by teto** [comment]
> Overall I still think making the less ambiguous name the default is the best choice. However it would be nice to make it as easy as possible to install with the b2 name for those who prefer/depend on it. For example maybe we could add support for backblaze-b2.override { name = "b2"; }. The default value could remain backblaze-b2.

I would be fine with that. 

> (Or even better, is there a common alias helper in nixpkgs? It may be nice to have something like lib.aliasExecutable "${pkgs.backblaze-b2}/bin/backblaze-b2" "b2" that can be used for any executable)

while I like the idea, I think this would be tricky to get right with autocompletions and all.

**Comment by hrdinka** [comment]
I am also fine with the configuration option. Generally I think it is best to not do modifications like renaming of binaries etc and keeping it as vanilla as possible. In this case however, besides being compatible with other distros, we most importantly must be backwards compatible to older nixpkgs versions. Renaming it by default will definitely break things. So keeping it as is and optionally naming it `b2` controlled via an argument as suggested seems to be the best solution to me.

I don’t think there is something like aliasExecutable.

@teto would you like to create a PR for this change?

**Comment by teto** [comment]
@hrdinka dunno when but I can try. If the maintainer wants to tackle the verbose help part of my issue, I would be grateful too, ie:
```
usages:
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 authorize-account
  [-h] [applicationKeyId] [applicationKey]
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 cancel-all-unfinished-large-files
  [-h] bucketName
  /nix/store/4mn5fgz266jk46mfd09kybfzi8dra3v8-backblaze-b2-3.15.0/bin/backblaze-b2 cancel-large-file
```

**Comment by teto** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/282659 for renamiong the executable
