### ISSUE TITLE
Package request: orca-slicer

### ISSUE THREAD

**Issue by canguy247** [NixOS/nixpkgs#278109]
**Project description**

Orca Slicer is an open source slicer for FDM printers.
OrcaSlicer is fork of Bambu Studio
It was previously known as BambuStudio-SoftFever

**Metadata**

* homepage URL: https://github.com/SoftFever/OrcaSlicer
* source URL: https://github.com/SoftFever/OrcaSlicer
* license: AGPL-3.0
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
Already done [here](https://github.com/NixOS/nixpkgs/pull/275638).
