### ISSUE TITLE
Update request: tailscale 1.54.0 → 1.56.1

### ISSUE THREAD

**Issue by queeup** [NixOS/nixpkgs#278134]
- Package name: tailscale
- Latest released version: 1.56.1

- Current version on the unstable channel: 1.56.1
- Current version on the stable/release channel: 1.54.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mfrw 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment]
Closed by #278210.
