### ISSUE TITLE
Package request: goldwarden

### ISSUE THREAD

**Issue by edmundmiller** [NixOS/nixpkgs#278180]
**Project description**

Goldwarden is a Bitwarden compatible desktop client. It focuses on providing useful desktop features that the official tools do not (yet) have or are not willing to add, and enhanced security measures that other tools do not provide, such as:

    Support for SSH Agent (Git signing and SSH login)
    System wide autotype (Gnome, KDE only for now)
    Biometric authentication (via Polkit) for each credential access
    Implements Bitwarden browser-extension biometrics on Linux
    Support for injecting environment variables into the environment of a cli command
    Vault content is held encrypted in memory and only briefly decrypted when needed
    Kernel level memory protection for keys (via the memguard library)
    Additional measures to protect against memory dumps
    Passwordless login (Both logging in, and approving logins)
    Fido2 (Webauthn) support
    more to come...?

The aim is not to replace the official clients, but to complement by implementing the missing features.

**Metadata**

* homepage URL: https://github.com/quexten/goldwarden
* source URL: https://github.com/quexten/goldwarden
* license: mit
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Emiller88** [comment]
I've got a package going from nix-init: https://github.com/Emiller88/dotfiles/blob/115a6212a7b1de76ecd87e8ce1538131b9fa05bc/packages/goldwarden.nix

Haven't been able to enter a pin yet, I'm guessing it's from manually installing the service or something.

**Comment by quexten** [comment]
Ah, very cool that someone is looking into packaging one of my projects on nixos. I don't use nixos myself, but if there is anything I can do to help, feel free to ping me :)
