### ISSUE TITLE
mailutils on 17.03 broken since 359c8c9d9a97307c5bc3f7ee53449424fe0cd5a1

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#27815]
## Issue description

make[3]: Entering directory '/tmp/nix-build-mailutils-2.2.drv-0/mailutils-2.2/maidag'
for i in maidag; do\
    chown root:mail /nix/store/4xb7p9vd3h9p34a4hkllnjvxbvdlh3di-mailutils-2.2/sbin/$i;\
    chmod 4755 /nix/store/4xb7p9vd3h9p34a4hkllnjvxbvdlh3di-mailutils-2.2/sbin/$i;\
done
chown: invalid group: 'root:mail'
chmod: changing permissions of '/nix/store/4xb7p9vd3h9p34a4hkllnjvxbvdlh3di-mailutils-2.2/sbin/maidag': Operation not permitted
make[3]: *** [Makefile:1284: install-exec-hook] Error 1
make[3]: Leaving directory '/tmp/nix-build-mailutils-2.2.drv-0/mailutils-2.2/maidag'
make[2]: *** [Makefile:1224: install-exec-am] Error 2
make[2]: Leaving directory '/tmp/nix-build-mailutils-2.2.drv-0/mailutils-2.2/maidag'
make[1]: *** [Makefile:1174: install-am] Error 2
make[1]: Leaving directory '/tmp/nix-build-mailutils-2.2.drv-0/mailutils-2.2/maidag'
make: *** [Makefile:1036: install-recursive] Error 1
builder for ‘/nix/store/w3ya6i3q1ld9qnby469ai09dx7g3cnxf-mailutils-2.2.drv’ failed with exit code 2
error: build of ‘/nix/store/w3ya6i3q1ld9qnby469ai09dx7g3cnxf-mailutils-2.2.drv’ failed

359c8c9d9a97307c5bc3f7ee53449424fe0cd5a1 is the first bad commit
commit 359c8c9d9a97307c5bc3f7ee53449424fe0cd5a1
Author: Robert Helgesson <robert@rycee.net>
Date:   Tue Jul 18 00:58:20 2017 +0200

    expat: 2.2.1 -> 2.2.2

    (cherry picked from commit cc8e2aec299a002ede108dea1c33b1161f1aa180)

:040000 040000 7603a9a5b0909fd279e4dce2bf7af901857cf312 2ae14049aa91ce021e0db35a369fc7209a11e0b9 M  pkgs
bisect run success

### Steps to reproduce

nix-build -A mailutils -I nixpkgs=https://nixos.org/channels/nixos-17.03/nixexprs.tar.xz

## Technical details

* System: NixOS: `nixos-version` 17.03.1584.48ecdcf598 (works on e.g. 2e983f1)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.11
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 17.09pre109180.0d4431cfe9
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = false
(strange, I though I had sandbox enabled)
ok now tried with sandbox enabled
build-use-sandbox = true
still the same problem

**Comment by tohl** [comment]
strange, that commit doesn't seem somehow related
does git bisect work well with merges/pull-requests?

**Comment by fpletz** [comment]
@globin Can we backport your mailutils bump & fixes?

**Comment by rycee** [comment]
Cherry-picked d339dc762c73564cfbd20ab6c9be803e9c12e1e0 into `release-17.03`. The mailutils project should build fine with that. I don't know why I showed up in the bisect but I think the expat bump was unrelated to this issue.
