### ISSUE TITLE
Plasma-Browser-Integration Vivaldi not working

### ISSUE THREAD

**Issue by DaKingof** [NixOS/nixpkgs#278111]
I get the error ```Failed to connect to the native host.
Make sure the 'plasma-browser-integration' package is installed correctly and that you are running Plasma 5.13 or later.``` whenever I click the icon for the extension.

It seems to work partially. On my phone, I can skip through videos, but I cannot change the volume.

![image](https://github.com/NixOS/nixpkgs/assets/31186364/72ff0367-c824-4a32-9526-f539e01679d6)

I am using Plasma desktop and have the libforqt5 version installed as a system package.

I'm not sure if this is some setup I did, but it's been like this for a while. I also tried removing all of my Vivaldi files and starting from scratch and the same issue is present regardless if Vivaldi is a fresh install or not.

**Comment by SuperSandro2000** [comment]
This needs a similar fix to the other browsers in #232528

**Comment by codeiimon** [comment]
I was able to solve this issue for Vivaldi by just adding this to my configuration file:
```
environment.etc."chromium/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/etc/chromium/native-messaging-hosts/org.kde.plasma.browser_integration.json";
```

When 24.05 comes out, I think just using `programs.chromium.enablePlasmaBrowserIntegration` should just work

**Comment by SuperSandro2000** [comment]
Good to know, that this got fixed and can be closed.

**Comment by VeilSilence** [comment]
Brave have this issue also

**Comment by pakyrs** [comment]
which one is the Vivaldi config file so I can add that line and solve?

**Comment by pakyrs** [comment]
> which one is the Vivaldi config file so I can add that line and solve?


which one is the Vivaldi config file so I can add that line and solve?

**Comment by pakyrs** [comment]
> I was able to solve this issue for Vivaldi by just adding this to my configuration file:
> 
> ```
> environment.etc."chromium/native-messaging-hosts/org.kde.plasma.browser_integration.json".source = "${pkgs.plasma-browser-integration}/etc/chromium/native-messaging-hosts/org.kde.plasma.browser_integration.json";
> ```
> 
> When 24.05 comes out, I think just using `programs.chromium.enablePlasmaBrowserIntegration` should just work


which one is the Vivaldi config file so I can add that line and solve?
