### ISSUE TITLE
Build failure: PHP 8.3 with php-acpu

### ISSUE THREAD

**Issue by voidzero** [NixOS/nixpkgs#278243]
### Steps To Reproduce

I have this in my flake:

```
  environment.systemPackages = [
    pkgs.nodejs
    pkgs.nodePackages.node-pre-gyp
    (pkgs.php83.buildEnv {
      extensions = ({enabled, all}: enabled ++ (with all; [
        apcu
        bcmath
        gmp
        imagick
        opcache
        pdo
        pdo_pgsql
        redis
      ]));
      extraConfig = ''
        apc.enable_cli = 1
      '';
    })
  ];
```

### Build log

https://gist.github.com/voidzero/596e5d1c9ef60aa552a30fbc540ce367#file-php_test_results_20231230_2225-txt-L288

### Additional context

NixOS 23.11.

### Notify maintainers

@aanderse @drupol @etu @Ma27 @talyz 

### Metadata

The metadata from nix-info -m is not relevant as I am currently on 23.05 but performing an upgrade to 23.11. The system is x86_64-linux. multi-user and sandbox are yes.

Workaround: This issue does not occur on php82 so I'll be using that for now.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Hi,

I'm not able to reproduce the issue, therefore could you run this command on your machine?

```
nix build --impure --expr '(import ./. {}).php83.withExtensions({ enabled, all }: (enabled ++ (with all; [apcu bcmath gmp imagick opcache pdo pdo_pgsql redis])))' --show-trace
```

Thanks!

**Comment by voidzero** [comment]
Hi @drupol thanks, I am getting the same output as before.

```
error: builder for '/nix/store/9mvc08wnf8lvig8a8wc8mrhzy66s9a94-php-apcu-5.1.22.drv' failed with exit code 2;
       last 10 log lines:
       > ---------------------------------------------------------------------
       > Success parameters should respect property types [tests/typed_prop.phpt]
       > =====================================================================
       >
       > You may have found a problem in PHP.
       > This report can be saved and used to open an issue on the bug tracker at
       > https://github.com/php/php-src/issues
       > This gives us a better understanding of PHP's behavior.
       > Do you want to save this report in a file? [Yn]: Report saved to: /build/source/php_test_results_20240102_1144.txt
       > make: *** [Makefile:138: test] Error 1
       For full logs, run 'nix log /nix/store/9mvc08wnf8lvig8a8wc8mrhzy66s9a94-php-apcu-5.1.22.drv'.
error: 1 dependencies of derivation '/nix/store/4rh0daclxc6rqm7g2yhf64s4gcp1ic3y-php-extra-init-8.3.1.ini.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2fx3xq2yfci5c5jwkffs0f9sxjylpcsq-php-with-extensions-8.3.1.drv' failed to build
```

**Comment by drupol** [comment]
I don't have the same path for `php-with-extensions-8.3.1.drv`, I guess your `nixpkgs` is out of date.

**Comment by voidzero** [comment]
Ah, I am indeed on 23.11 so that might explain things, even though I've updated today.
I'll update again in one week and keep you posted whether it will work now.
Thanks for helping 😃

**Comment by drupol** [comment]
You're welcome, feel free to close the issue when it's resolved !

**Comment by voidzero** [comment]
I've just synched nixpkgs 23.11, but it doesn't look like your backport has landed, so nothing has changed yet. Just letting you know, I'll try again later this week or perhaps next week.

**Comment by drupol** [comment]
Indeed, there hasn't been a new channel update since we merged this PR (https://hydra.nixos.org/eval/1803447?filter=apcu&compare=1803374&full=#tabs-still-succeed). I guess that build is going to be successful and you'll be able to enjoy the fix very soon.

**Comment by voidzero** [comment]
Thanks for the link - haven't seen that before. Can I view on hydra when there is a channel update?

**Comment by drupol** [comment]
Yes, just look at this page: https://status.nixos.org/ (last update was 10h ago)

You can also "watch" a PR with this useful tool: https://nixpk.gs/pr-tracker.html?pr=278271

**Comment by drupol** [comment]
Hello,

Can I close the issue now?

**Comment by voidzero** [comment]
Yes, it works. Just tested. Much thanks @drupol, also for the other links and extra info. 😇
