### ISSUE TITLE
Brave ARM compatibility - Raspberry Pi

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#278278]
### Describe the bug

Brave is currently marked as incompatible with AARCH64. There is ARM support by the developers, so I think we could include it. https://github.com/brave/brave-browser/releases/tag/v1.61.109

### Steps To Reproduce
1. Add brave to the configuration.nix file
2. rebuild Nix
3. See that brave is declared incompatible with the AARCH64 platform

I tried it on the Pi4, should be the same on any AARCH64.

### Expected behavior
Brave rebuilds successfully. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2413.32f63574c85f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samueldr** [comment]
Closing, as the last referenced PR seemingly implements this.

If this is inaccurate, re-open and explain what is wrong.

If *anyone else* is having issues with brave and its usage on AArch64, please open a new issue with details. Feel free to cross-reference this issue.
