### ISSUE TITLE
Maliit-keyboard cannot be configured using gsettings

### ISSUE THREAD

**Issue by TadaCZE** [NixOS/nixpkgs#278276]
### Describe the bug

The package maliit-keyboard cannot be configured

### Steps To Reproduce

1. Install maliit-keyboard
2. Open terminal
3. Type `gsettings set org.maliit.keyboard.maliit theme BreezeDark`

### Expected behavior

The setting would be changed

### Actual behavior

The command returns `No schemas installed`

### Additional context

This happens on KDE Plasma, not tested anywhere else

### Notify maintainers

@samueldr 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
tada@tadeck ~ [1]> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52-valve10, NixOS, 24.05 (Uakari), 24.05pre562833.5f64a12a7289`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by melvyn2** [comment]
Was this closed because you found a solution? I am still affected by this

**Comment by Pastitas** [comment]
same here
