### ISSUE TITLE
Quodlibet plugins aren't installed and don't work

### ISSUE THREAD

**Issue by sauyon** [NixOS/nixpkgs#27830]
## Issue description

Title

### Steps to reproduce

* Install quodlibet, open plugins menu.
* Try to install plugins from quodlibet repo.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.09pre111447.a7c8f5e419 (Hummingbird)
* Nix version: (run `nix-env --version`)
1.11.13
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.09pre111447.a7c8f5e419
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
yes

**Comment by sauyon** [comment]
#29404 should fix the majority of these issues; only three plugins appear to be broken.

**Comment by prusnak** [comment]
Fixed via #29404 / https://github.com/NixOS/nixpkgs/commit/7486ae8e7ccc256873982c60445f34dfa72382e9
