### ISSUE TITLE
micromamba not running correctly

### ISSUE THREAD

**Issue by jayveesea** [NixOS/nixpkgs#278397]
### Describe the bug
trying to run micromamba with the [instructions from wiki](https://nixos.wiki/wiki/Python#micromamba) and get this error when running my `mambashell.nix`:

> error    libmamba Overwriting root prefix is not permitted
> critical libmamba Aborting.

### Steps To Reproduce
1. install [micromamba](https://search.nixos.org/packages?channel=23.11&show=micromamba&from=0&size=50&sort=relevance&type=packages&query=micromamba)
2. setup a `shell.nix` as described [here](https://nixos.wiki/wiki/Python#micromamba).  I called mine `mambashell.nix`
3. run `nix-shell mambashell.nix`

### Expected behavior
was expecting to be put into a mamba environment

### Screenshots
na

### Additional context
https://discourse.nixos.org/t/nix-shell-with-micromamba-and-fhs/25464/8

### Notify maintainers
@mausch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 23.11 (Tapir), 23.11.2130.d65bceaee0fb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mausch** [comment]
Does the workaround described in discourse work for you?

**Comment by jayveesea** [comment]
the method [here](https://discourse.nixos.org/t/nix-shell-with-micromamba-and-fhs/25464/8?u=jayveesea) does not work for me either.  I get this result when running `micromamba activate my-mamba-environment` after I enter the nix shell:
> 'micromamba' is running as a subprocess and can't modify the parent shell.
> Thus you must initialize your shell before using activate and deactivate.
> 
>     To initialize the current bash shell, run:
>         $ eval "$(micromamba shell hook --shell=bash)"
>     and then activate or deactivate with:
>         $ micromamba activate
>     
> To automatically initialize all future (bash) shells, run:
>     $ micromamba shell init --shell=bash --prefix=~/micromamba
> 
> Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.
> 
> critical libmamba Shell not initialized

when I try `eval "$(micromamba shell hook --shell=bash)"` followed with `micromamba activate` I get (still in the nix shell):
> bash: hash: hashing disabled

if I ignore that and try something like `mamba install matplotlib` I get:
> mamba: command not found

**Comment by mausch** [comment]
>  bash: hash: hashing disabled

Pretty sure you can safely ignore this.

>   mamba: command not found

This package is for micromamba not mamba.

**Comment by jayveesea** [comment]
ahh, I see.  I also need `-c conda-forge` at the end or add `micromamba config append channels conda-forge` to the nix shell.

It seems like less hassle when using just the `base` environment.  In fact, as of now, the instructions from [here](https://nixos.wiki/wiki/Python#micromamba) seem to work ok if just a base environment is needed.
``` nix
{ pkgs ? import <nixpkgs> {}}:
let
  fhs = pkgs.buildFHSUserEnv {
    name = "my-fhs-environment";

    targetPkgs = _: [
      pkgs.micromamba
    ];

    profile = ''
      set -e
      eval "$(micromamba shell hook -s bash)"
      export MAMBA_ROOT_PREFIX=${builtins.getEnv "PWD"}/.mamba
      micromamba activate
      micromamba install --yes -f conda-requirements.txt -c conda-forge
      set +e
    '';
  };
in fhs.env
```

**Comment by jayveesea** [comment]
I guess the remaining question is... are the instructions [here](https://nixos.wiki/wiki/Python#micromamba) correct?  Seems like it would help if they were updated with what I have above, which just uses the base environment.  That said, I believe people will want to use alternate environments and I still haven't achieved this yet.  thanks for your patience.

**Comment by jrbp** [comment]
I was able to do something like the following (this is an untested adaptation from my flake version where I use conda-lock).

```nix
{pkgs ? import <nixpkgs> {}}: let
  mambaactivation = pkgs.writeText "mambaactivation" ''
    set -e
    export MAMBA_ROOT_PREFIX=${builtins.getEnv "PWD"}/.mamba
    eval "$(micromamba shell hook --shell=bash)"
    micromamba activate
    micromamba install --yes -f conda-requirements.txt -c conda-forge
    set +e
  '';
  fhs = pkgs.buildFHSEnv {
    name = "mamba-env";
    targetPkgs = _: [pkgs.micromamba];
    runScript = "bash --rcfile <(cat $\{HOME\}/.bashrc ${mambaactivation})";
  };
in
  fhs.env

```
This will always bring you to a bash shell, though usually with e.g. direnv I can stay in zsh when using devShells.

**Comment by mausch** [comment]
I'll close this now.
The docs I wrote in https://nixos.wiki/wiki/Python#micromamba are not pinned so it's expected they'll need to be updated as micromamba changes. 
If someone finds that the docs are broken and figures out how to fix them, please just update the wiki. That's the whole point of the wiki being publicly editable :slightly_smiling_face: 
As a side note I no longer use micromamba (I've switched to poetry) or a direct FHS (I've switched to https://devenv.sh/ ) so I'm no longer qualified to maintain that documentation.
