### ISSUE TITLE
Update request: scribus 1.5.8 → 1.6.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#278365]
- Package name: scribus
- Latest released version: 1.6.0
- Current version on the unstable channel: 1.5.8
- Current version on the stable/release channel: 1.4.8
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@erictapen  
@Kiwi  

https://sourceforge.net/projects/scribus/files/scribus/1.6.0/

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by erictapen** [comment]
The version on the stable channel is also 1.5.8, 1.4 existed only on the old NixOS 23.05 release and got removed since.
