### ISSUE TITLE
GUI problem on some apps

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#27842]
Hi,

I am using many apps without any problem (Avidemux, Chromium browser, Google Chrome, Atom Text Editor, Gimp, Filezila... ).

But only Meld, Remmina and uGet graphic interface has some problems. Here is a screenshot of these 3 apps: https://pasteboard.co/GDFt61A.jpg

System info:
Ubuntu 16.04 64 bit
Nix - latest stable

**Comment by volth** [comment]
Are you using XFCE?

**Comment by TerkiKerel** [comment]
@volth  No. I a using UBuntu 16.04 (default which is coming with Unity).

**Comment by vyp** [comment]
> I remove the app. I run this command: nix-collect-garbage -d . I re-install the apps. But nothing changed :(

That seems right though, I think garbage stuff in principle shouldn't be affecting anything.

**Comment by TerkiKerel** [comment]
@vyp I know... But I just tried. Is there anything else which I can try to solve the problem? Or is this normal because of these apps nature?

**Comment by vyp** [comment]
@TerkiKerel No I'm not sure, sorry. :disappointed:

**Comment by TerkiKerel** [comment]
@vyp no problem.. Thank you :)

**Comment by romildo** [comment]
It may be an issue with the theme you are using. Maybe it is for an older version of `gtk+`. Try with other themes, like `Adwaita`.

**Comment by TerkiKerel** [comment]
@romildo Ubuntu has "high contrast" theme. When I changed on it, it fixed.

I will not try (at least for a while) to install new themes on system. I am worrying to break system.

Is there any way to start a nix app with a specific theme?

**Comment by romildo** [comment]
> Is there any way to start a nix app with a specific theme?

The theme can be set using the environment variable `GTK_THEME`. For instance, in a terminal you can type:

```
$ GTK_THEME=Adwaita uget-gtk &
```
![screenshot_2017-09-02_10-59-40](https://user-images.githubusercontent.com/1217934/29996065-df7fe6be-8fcd-11e7-9f71-8731a1311478.png)

**Comment by TerkiKerel** [comment]
GTK_THEME=Adwaita variable fix the problem.

But anybody knows why this is happening? Is that normal? Or there is a dependency problem on package inside?

If it is something about Unity-desktop problem, dont fix it :) Ubuntu will support different desktop manager after new version...

**Comment by yegortimoshenko** [comment]
@TerkiKerel Is this still an issue in new Ubuntu with GNOME?

**Comment by TerkiKerel** [comment]
@yegortimoshenko  no. I'm using Ubuntu with Unity (default desktop manager of Ubuntu).

**Comment by TerkiKerel** [comment]
I try o a new computer with ubuntu 18.04. it gives :

"Gtk-Message: 21:42:31.652: Failed to load module "canberra-gtk-module" "

but now it works without any variable configuration.

I think the problem was about Unity-desktop.
