### ISSUE TITLE
invidious: error message advises to set `services.invidious.database.user` which doesn’t exist

### ISSUE THREAD

**Issue by GoldsteinE** [NixOS/nixpkgs#278480]
### Describe the bug
New version of the invidious module gives an error on old system state versions with the following message:

https://github.com/NixOS/nixpkgs/blob/b0d36bd0a420ecee3bc916c91886caca87c894e9/nixos/modules/services/web-apps/invidious.nix#L154-L159

Config option `services.invidious.database.user` doesn’t seem to exist and doesn’t do anything when set. Manually setting `settings.db.user` gets config to build, but service still doesn’t start with permission error, even after running the suggested reassign command:

```
2024-01-03 13:03:29 UTC [info] check_table: check_table: CREATE TABLE channels
Unhandled exception: permission denied for table channels (PQ::PQError)
```

`invidious` database seems to be correctly owned by the `invidious` user:

```
postgres=# \l
                                   List of databases
   Name    |   Owner   | Encoding |   Collate   |    Ctype    |    Access privileges
-----------+-----------+----------+-------------+-------------+-------------------------
 invidious | invidious | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/invidious          +
           |           |          |             |             | invidious=CTc/invidious
```

### Steps To Reproduce
1. Enable invidious with local database on system state before 24.05:
   ```nix
   services.invidious.enable = true;
   ```
2. See an error message, try to perform suggested fix. Find out that the suggested setting doesn’t exist and use `services.invidious.settings.db.user` instead:
   ```nix
   services.invidious = {
     enable = true;
     settings.db.user = "invidious";
   };
   ```
3. Run `REASSIGN OWNED BY kemal TO invidious;` as suggested by the error message.
4. Try to start `invidious.service`.
5. Observe permission error.

### Expected behavior
Service should successfully start after applying suggested fixes. Error message shouldn’t refer to non-existent options.

### Notify maintainers

@hughobrien @999eagle 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20231230.b0d36bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/kxz698yrnad9csyrsf6sb842ryarss7b-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 999eagle** [comment]
The correct configuration should look like this if your state version is before 24.05:
```nix
services.invidious = {
  enable = true;
  settings.db.user = "invidious";
};
```
Looks like there is a mistake in the error message (`services.invidious.settings.db.user` and `services.invidious.database.user` are both specified and only the former is correct). Can you please try again with `services.invidious.settings.db.user` set to `"invidious"`?

**Comment by GoldsteinE** [comment]
Yes, I’ve tried this (steps 2+ of reproduction). I’ve mistakenly wrote `cfg.settings.db.user` in my initial issue, sorry, I’ve tried setting `services.invidious.settings.db.user`. It gets config to build, but it doesn’t start with the error described in the first post. I’ll amend the issue text now.

**Comment by hughobrien** [comment]
Can you show us the output of 

```

postgres=# \c invidious 
You are now connected to database "invidious" as user "postgres".
invidious=# \dt
```

**Comment by GoldsteinE** [comment]
Sure!
```
$ sudo -u postgres env psql --user=postgres --dbname=invidious
psql (14.10)
Type "help" for help.

invidious=# \dt
            List of relations
 Schema |      Name       | Type  | Owner
--------+-----------------+-------+-------
 public | channel_videos  | table | kemal
 public | channels        | table | kemal
 public | nonces          | table | kemal
 public | playlist_videos | table | kemal
 public | playlists       | table | kemal
 public | session_ids     | table | kemal
 public | users           | table | kemal
 public | videos          | table | kemal
(8 rows)
```

I see the problem now. I’ve tried to run the `REASSIGN` command without selecting the `invidious` database first. After running it with `invidious` database selected, service starts successfully. Thanks!

**Comment by hughobrien** [comment]
Super. Can you please look at the PR and tell me if the improved language would have solved your issue?

https://github.com/NixOS/nixpkgs/pull/278501/files

**Comment by GoldsteinE** [comment]
Yeah, thanks, that would’ve be clear!
