### ISSUE TITLE
Package request: sapling

### ISSUE THREAD

**Issue by emeinhardt** [NixOS/nixpkgs#278512]
**Project description**

`sapling` is a git-compatible VCS closely related to mercurial and developed by Facebook/Meta.

**Metadata**

* homepage URL: https://sapling-scm.com
* source URL: https://github.com/facebook/sapling
* license: GPL2+
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/sapling/default.nix#L195
