### ISSUE TITLE
Package request: Kanagawa-GKT-Theme

### ISSUE THREAD

**Issue by RoccoRakete** [NixOS/nixpkgs#278517]
**Project description**

Basically a GTK-Theme, nothing much to talk about.. it's pretty!

**Metadata**

https://github.com/Fausto-Korpsvart/Kanagawa-GKT-Theme

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
See https://github.com/NixOS/nixpkgs/pull/277073

**Comment by donovanglover** [comment]
Now available in nixos-unstable
