### ISSUE TITLE
wofi-emoji doesn't properly embed its dependencies

### ISSUE THREAD

**Issue by ppom0** [NixOS/nixpkgs#278502]
### Describe the bug

When `wtype` and `wl-copy` are not in system `PATH`, `wofi-emoji` script can't use them. Seems like `buildInputs` is not enough. Maybe using `writeShellApplication` or manually adding a PATH at the beginning of the script would fix the issue.

Also the script is now in a fork: https://github.com/Zeioth/wofi-emoji/
*Edit: it has been updated in `src` but not in `meta.homepage`*.

### Steps To Reproduce
1. Try the script without `wtype` and `wl-copy` in current PATH.
2. It won't type nor copy the emoji

### Notify maintainers

@ymarkus

**Comment by ymarkus** [comment]
Please check the PR I just opened. I'm getting locale errors, but that's an issue I have with my arch install :laughing:
