### ISSUE TITLE
nixos/libvirtd: problems with <emulator> path fix

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#27857]
```nixos/libvirtd``` has [the code](https://github.com/NixOS/nixpkgs/blob/b8e109d6acf61df5c02825f5b485239649f4ea31/nixos/modules/virtualisation/libvirtd.nix#L158-L174) to [fix ```<emulator>``` path](https://github.com/NixOS/nixpkgs/issues/1200) in VM configurations

This code is problematic:
1. It does not solve completely the problem with virtual machines pointing to GC'ed ```qemu```s, because xml-configuration is not the only place with qemu paths. There are also ```.save```-files with VM snapshots. Even if taking snapshots is not a part of your workflow, ```libvirt``` takes them when you reboot the host and restores after the host is up again. If a ```qemu``` derivation is GC'ed when a VM is in saved state, the VM cannot be restored (100% repoducible bug if GC is performed in ```boot.postBootCommands```; it also could interfere with GC runs by cron)

2. The xml-manipulation code runs on the host booting up, when VMs are usually in the saved state, and qemu path is preserved in ```.save```-file. When VMs are resumed, ```<emulator>``` in xml-files are ovewritten back to the value from the ```.save```-file.

3. It tends to diverge, different VMs start using different ```qemu```s.  ```qemu``` derivations cannot be GC-ed when VMs are running, and they also cannot be GC'ed when VMs are paused (because of p.1 above) so quickly each VMs has its own ```qemu```.  VMs have to be turned off/on to pick the changes from .xml-files. Pause or reboot is not enough. So each VM keeps using the ```qemu``` derivation from the moment of VM power up.

4. It destroys explicitly defined ```<emulator>``` if a VM is created from xml with ```<emulator>/run/current-system/sw/bin/qemu-kvm</emulator>``` or with explicitly specified version of ```qemu``` (say the one from git), this xml-manipulation overwrites if.

5. VM migration between hosts is possible only when the ```<emulator>```-file exists on both hosts. It is difficult to achieve with ```/nix/store``` paths

Generally it works, but not as expected. Instead of fixing paths to the latest derivation of ```qemu```, it does not allow GC to collect all ```qemu```s in use.

It might have sense to prefer patching libvirt's code over xml files. Anyway, it is only about the default value which will be used if there is no ```<emulator>``` defined, it could default to ```/run/current-system/sw/bin/qemu-kvm``` for example

cc @bjornfor

**Comment by bjornfor** [comment]
I'm open to suggestions how to improve the situation.

The new emulator binary that is injected into the XML is found via $PATH. Perhaps we should put /run/current-system/sw/bin first in $PATH for the libvirtd service?

**Comment by volth** [comment]
I have no solution at the moment, need few days of dogfooding to develop one.
What is clear, xml-files should not contain ```/nix/store``` paths, rather something more stable in ```/etc```, ```/run``` or ```/var```
