### ISSUE TITLE
Package request: Scrutiny

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#278588]
**Project description**

Provides a Webpage with realtime and historical data about the HDD's and SSD's in your system, as well as being able to notify you if somthing is going wrong via a rather large list of services.

![](https://i.imgur.com/WF3yYgu.png)

**Metadata**

* homepage URL: https://github.com/AnalogJ/scrutiny
* source URL: https://github.com/AnalogJ/scrutiny
* license: MIT
* platforms: linux
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ppom0** [comment]
Low effort package successfully built (using nix-init):
```nix
{ lib
, buildGoModule
, fetchFromGitHub
}:

let
  version = "0.7.2";
in buildGoModule {
  inherit version;
  pname = "scrutiny";

  src = fetchFromGitHub {
    owner = "AnalogJ";
    repo = "scrutiny";
    rev = "v${version}";
    hash = "sha256-UYKi+WTsasUaE6irzMAHr66k7wXyec8FXc8AWjEk0qs=";
  };

  vendorHash = "sha256-SiQw6pq0Fyy8Ia39S/Vgp9Mlfog2drtVn43g+GXiQuI=";

  ldflags = [ "-s" "-w" ];

  doCheck = false;

  meta = with lib; {
    description = "Hard Drive S.M.A.R.T Monitoring, Historical Trends & Real World Failure Thresholds";
    homepage = "https://github.com/AnalogJ/scrutiny";
    license = licenses.mit;
    maintainers = with maintainers; [ ppom ];
    mainProgram = "scrutiny";
  };
}
```
I'd like to have it in nixpkgs as well, but I won't take the time to do this until [idk]

**Comment by eclairevoyant** [comment]
packaged in #289934
