### ISSUE TITLE
gogs: Wrapper causes symlinks to be created all over the place

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#27866]
## Issue description
Since the wrapper for `gogs` includes the  [line](https://github.com/NixOS/nixpkgs/blob/f5fa5fa4d629a0dbc8033d86f1d5c6b2eb531f96/pkgs/applications/version-management/gogs/default.nix#L39) `--run "ln -fs $data/{public,templates} ."` some symbolic link is created whenever `gogs` is run.
It seems that odd behaviour can be worked around by setting `GOGS_WORK_DIR`, which the wrapper `cd`s to.
However there is a slight problem with that: `gogs` creates `git` hooks that look like that:
```
#!/nix/store/p4csf5alczckcj6j4byc211kpw6ir0kz-coreutils-8.26/bin/env bash
"/nix/store/dbx6h0sa6z2jzd7jw2kyp5hygylhlv7p-gogs-0.9.113-bin/bin/gogs" update $1 $2 $3 --config=/home/gogs/custom/conf/app.ini'
```
This has the following downsides:
- Gogs creates a symlink on every update of the repository.
- On every new install of `gogs`, one needs to run the "Rewrite all update hook of repositories (needed when custom config path is changed)" in the admin-Dashboard.

## Technical details

* System: openSUSE 12
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre102922.22c2651
* Sandboxing enabled: No

**Comment by Mic92** [comment]
ping @schneefux

**Comment by Mic92** [comment]
this should be probably part of the service instead the package instead.

**Comment by knedlsepp** [comment]
There is now the environment variable `STATIC_ROOT_PATH` mentioned in the [configuration cheat sheet](). 
> Upper level of template and static files path, default is the path where Gogs is located.
Maybe the behaviour has changed that `gogs` is looking for those directories `public` and `templates` in the current working directory instead of "where gogs is located". That could save us from those pesky symlinks.

**Comment by schneefux** [comment]
The NixOS module rewrites the git hooks using sed on every start https://github.com/NixOS/nixpkgs/pull/19361#issuecomment-255535192.

@valeriangalliat wrote that part of the package, see here https://github.com/NixOS/nixpkgs/pull/13566.

I don't have the time to work at the package, sorry. `STATIC_ROOT_PATH` is probably the way to go.

**Comment by bobvanderlinden** [comment]
I ran into a problem where /var/lib/gogs/public had a symlink to an older installation of gogs. Creating symlinks isn't ideal and it's good to hear STATIC_ROOT_PATH is introduced.

I'm guessing removing most of the --run lines in the wrapper and adding STATIC_ROOT_PATH to the gogs module is the way to go?

**Comment by knedlsepp** [comment]
There is also an additional problem with upgrading gogs: for every git repository there is a hooks directory that hard codes the gogs directory. One needs to manually rewrite these hooks using the admin panel. I'm not sure if we should fix that by updating the hashes ourselves using the wrapper script. Hopefully a command line option for all those admin actions will become available in the future.

**Comment by bobvanderlinden** [comment]
I've created a PR that should solve this problem. Feedback is very much appreciated. #30030

**Comment by bobvanderlinden** [comment]
@knedlsepp could you create a new issue for this?

**Comment by knedlsepp** [comment]
@bobvanderlinden #30048
