### ISSUE TITLE
Package request: spotube

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#278668]
**Project description**

An open source, cross-platform Spotify client compatible across multiple platforms
utilizing Spotify's data API and YouTube (or Piped.video or JioSaavn) as an audio source

**Metadata**

* homepage URL: https://spotube.krtirtho.dev/
* source URL: https://github.com/KRTirtho/spotube
* license: BSD-4-Clause
* platforms: linux, darwin, windows

**Comment by TomaSajt** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/200120
