### ISSUE TITLE
adguardhome bind_port has no effect

### ISSUE THREAD

**Issue by aquinary** [NixOS/nixpkgs#278601]
### Describe the bug
```nix
services.adguardhome = {
      enable = true;
      openFirewall = true;
      settings = {
        bind_port = 7777;
        schema_version = 20;
      };
    };
```
and
```nix
networking = {
        hostName = "yoshinon";
        networkmanager.enable = true;
        firewall = {
          allowedTCPPorts = [ 7777 ];
          allowedUDPPorts = [ 53 ];
      };
    };
```
Result:

```console
wget 127.0.0.1:7777
--2024-01-04 03:29:56--  http://127.0.0.1:7777/
Connecting to 127.0.0.1:7777... failed: Connection refused.
```
but!
```console
wget 127.0.0.1:3000
--2024-01-04 03:29:59--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
```
AdGuard page open on 3000 port

### Expected behavior
I expect that adguard will open on the port I specified

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
cc @StillerHarpo @CRTified

**Comment by StillerHarpo** [comment]
@aquinary They changed the option to `http.address` since v0.107.36  (see https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file)

This should work
```nix
services.adguardhome = {
      enable = true;
      openFirewall = true;
      settings = {
        bind_port = 7777;
        http.address = "0.0.0.0:7777";
        schema_version = 20;
      };
    };
```
You still have to set `bind_port` for `openFirewall` to work (we should fix that). `allowedTCPPorts` and `allowedUDPPorts` shouldn't be neccessary

**Comment by StillerHarpo** [comment]
There is already a pull request which will fix this https://github.com/NixOS/nixpkgs/pull/266450

**Comment by badele** [comment]
> @aquinary They changed the option to `http.address` since v0.107.36 (see https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file)
> 
> This should work
> 
> ```nix
> services.adguardhome = {
>   enable = true;
>   openFirewall = true;
>   settings = {
>     bind_port = 7777;
>     http.address = "0.0.0.0:7777";
>     schema_version = 20;
>   };
> };
> ```
> 

I can confirm that it works! 

Thanks for this solution, it will allow me to wait for the PR :)

**Comment by aquinary** [comment]
Thx!
