### ISSUE TITLE
Build failure: pkgsMusl.openexr

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#278713]
### Steps To Reproduce

1. build pkgsMusl.openexr

### Build log

https://termbin.com/a5uw

### Metadata

commit 494bdb470881cb8714b47a0bbb0048157e8fdeda (nixos/staging-next)

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyssais** [comment]
59048500b27505ef81b13bc0716a2822be616b4e is the first bad commit
