### ISSUE TITLE
nodejs: withPackages

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#278782]
some languages like python and perl now have `withPackages` options, allowing the user to configure which version of the language should be used for their packages.
it seems like nodejs now does not offer such an option in nixpkgs, instead only `nodePackages` and `nodePackages_latest`.
would it maybe make sense to offer an equivalent there as well?

**Comment by dotlambda** [comment]
We're trying to get rid of `nodePackages`: #229475
