### ISSUE TITLE
Deprecation of openssl_1_1 in 23.11 release channel still references 23.05 

### ISSUE THREAD

**Issue by f0x52** [NixOS/nixpkgs#278937]
### Describe the bug
Not a big issue, but I found it a bit confusing when (during upgrade) the `openssl_1_1` knownVulnerabilities referenced the 23.05 release cycle, thought I had some weirdness going on where it was still being pulled from 23.05.
[Source](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/libraries/openssl/default.nix#L240) also mentions 23.05 in the comment about backporting, so maybe that should also be updated (or removed if no longer relevant for this and future channels)?

### Notify maintainers
@thillux 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thillux** [comment]
Thanks for the hint. I'll change the hint and reference the tracking issue for OpenSSL 1.1 deprecation (https://github.com/NixOS/nixpkgs/issues/269713)

**Comment by thillux** [comment]
Fixed in: https://github.com/NixOS/nixpkgs/pull/280756
