### ISSUE TITLE
torch cannot initialize CUDA

### ISSUE THREAD

**Issue by natsukium** [NixOS/nixpkgs#278976]
### Describe the bug

I cannot enable CUDA for pytorch on my desktop machine with NVIDIA drivers enabled.
I pinned pytorch to the HEAD of the local master branch (see the command for the commit hash) and bisected the system nixpkgs.
The results showed that the following commit would cause problems, at least in my environment. #267335
However, even if I revert this change, I still get an error on master, so I suspect this change itself is not the problem.

I spent half a day rebuilding and rebooting the system many times so that I may be wrong somewhere, or it may be a problem with my environment that you can't reproduce.
Let me know if you need more information.

```shell
nix-shell -p 'python311.withPackages (ps: with ps; [torchWithCuda])' -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/26c6b9f5394b2e64649ff18394d61ce5594874e2.tar.gz
```
```console
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.cuda.is_available()
/nix/store/g8h927gf94xqqh7av33vsijzp0cypam9-python3-3.11.6-env/lib/python3.11/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /build/source/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
>>> 
```

nixosConfiguration which may be relevant
```nix
boot.kernelPackages = pkgs.linuxPackages_xanmod_latest;
hardware.nvidia = {
  package = config.boot.kernelPackages.nvidiaPackages.stable;
};
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers

@NixOS/cuda-maintainers 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8-xanmod1, NixOS, 24.05 (Uakari), 24.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
Might be indeed specific to your nixos configuration:

```console
❯ nix-shell --arg config '{ allowUnfree = true; }' -p 'python311.withPackages (ps: with ps; [torchWithCuda])' -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/26c6b9f5394b2e64649ff18394d61ce5594874e2.tar.gz 
this derivation will be built:
  /nix/store/k76amqhv18nmzacvyh7nmmp4xpfdl8cf-python3-3.11.6-env.drv
building '/nix/store/k76amqhv18nmzacvyh7nmmp4xpfdl8cf-python3-3.11.6-env.drv'...
created 541 symlinks in user environment
❯ python
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.cuda.is_available()
True
```


Do simpler things work, like `cudaPackages.saxpy`? Anything notable in `LD_DEBUG=libs` or in the `strace`?

**Comment by natsukium** [comment]
Thanks for checking.
It is good to know that it is at least probably caused by my environment.

Regarding saxpy, I've never written code for that layer, so I couldn't try it right away.

Regarding `LD_DEBUG=libs`, I attached a succeeded and a failed log below, but I did not see any difference between them.
succeeded log: https://gist.github.com/natsukium/bcf37476eb8d702023585d33e80fb3fb
failed log: https://gist.github.com/natsukium/889a4734db67ba1ada84793af33c8358

I also attached a `strace` log, but the log is too long to check.
succeeded log: https://gist.github.com/natsukium/1a4849df37d881890f5988ef1c4efa6a
failed log: https://gist.github.com/natsukium/2a996f4d3e27e720de2c6374d8867ad1

I will first try to find the smallest configuration that reproduces the problem.

**Comment by natsukium** [comment]
I updated the nixpkgs that nixos uses from a week ago to the current one, which fixed the problem.
Sorry for taking your time.

**Comment by SomeoneSerge** [comment]
> In my experience sometimes stuff like that happens because the program can't find libcuda.so.1 and friends.

This path is already part of `DT_RUNPATH` and shouldn't be an issue, unless the user has set a conflicting `LD_LIBRARY_PATH`. In this case the driver was located successfully, e.g. we see the destructors called after the error message: https://gist.github.com/natsukium/889a4734db67ba1ada84793af33c8358#file-ld-debug-failed-log-L640-L644

What is more likely is the cudart/libcuda/kernel module version mismatch (e.g. https://github.com/NixOS/nixpkgs/issues/255070). The libcuda/kernel module mismatch would've been addressed by a reboot. The cudart/libcuda mismatch - by using a newer driver or an older cudart, I guess.

@natsukium did you have to reboot before it all started working again?

**Comment by natsukium** [comment]
Yes, I need to reboot. Before I submitted this issue, my NixOS advanced 20 generations and was rebooted each time.

**Comment by Raikiri** [comment]
I have the same issue after I put machine to sleep and wake it up. After rebooting it seems to be fine again.

**Comment by SomeoneSerge** [comment]
> I have the same issue after I put machine to sleep and wake it up. After rebooting it seems to be fine again.

@Raikiri it might look like similar symptoms but not necessarily the same cause. Could you please open a new issue, attach `strace` and `LD_DEBUG` outputs, results of running `nix run -f "<nixpkgs>" cudaPackages.saxpy` and `nvidia-smi`, etc as per previous comments? Thank you

**Comment by Raikiri** [comment]
@SomeoneSerge I'll do that when it happens again, thank you.
