### ISSUE TITLE
Package request: egpu-switcher

### ISSUE THREAD

**Issue by eval-exec** [NixOS/nixpkgs#279069]
**Project description**

Distribution agnostic eGPU script that works with NVIDIA and AMD cards.

**Metadata**

* homepage URL: [egpu-switcher](https://github.com/hertg/egpu-switcher)
* source URL: https://github.com/hertg/egpu-switcher
* license: [GPL-3.0 license](https://github.com/hertg/egpu-switcher#GPL-3.0-1-ov-file)
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
fyi you can easily achieve what this script is doing with nixos specializations

**Comment by eval-exec** [comment]
> fyi you can easily achieve what this script is doing with nixos specializations

Thank you
