### ISSUE TITLE
[staging-next] Build failure: krita

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#279054]
### Steps To Reproduce

1. build krita

### Build log

https://termbin.com/bgpy

### Additional context

Introduced in: 5a2509220f629a716e608bae64b8d276a3e9ef0d / https://github.com/NixOS/nixpkgs/pull/271586

### Notify maintainers
krita: @abbradar  @sifmelcara @nek0 
sip: @nrdxp 
For the python updates: @mweinelt 

### Metadata

commit 151403ef0517cd712d0640b0d3c88efd2196b6e5 (nixos/staging-next)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sifmelcara** [comment]
[Bump SIP ABI version to 12.8 (2d71c476) · Commits · Graphics / Krita · GitLab](https://invent.kde.org/graphics/krita/-/commit/2d71c47661d43a4e3c1ab0c27803de980bdf2bb2) will probably fix this, I can test and open a PR targeting staging-next (or should I target master?)

**Comment by yu-re-ka** [comment]
Feel free to open a PR targeting staging-next. The sip update is on staging-next only.
