### ISSUE TITLE
Port Nix Pills in to a document produced by Nixpkgs 

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#27908]
## Issue description

@lethalman gave me permission to incorporate the nix pills in to a document produced by nixpkgs and on the website.

This should probably be its own document.

People who have offered to help write docbook after I make a skeleton to work from:
 
 - @disassembler (disasm on irc)
 - @ankhers  
 - @moretea 

(thank you by the way)

Todo:

- [x] http://lethalman.blogspot.it/2014/07/nix-pill-1-why-you-should-give-it-try.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-2-install-on-your-running.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-3-enter-environment.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-4-basics-of-language.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-5-functions-and-imports.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-6-our-first-derivation.html
- [x] http://lethalman.blogspot.it/2014/07/nix-pill-7-working-derivation.html
- [x] http://lethalman.blogspot.it/2014/08/nix-pill-8-generic-builders.html
- [x] http://lethalman.blogspot.it/2014/08/nix-pill-9-automatic-runtime.html
- [x] http://lethalman.blogspot.it/2014/08/nix-pill-10-developing-with-nix-shell.html
- [x] http://lethalman.blogspot.it/2014/08/nix-pill-11-garbage-collector.html
- [x] http://lethalman.blogspot.it/2014/08/nix-pill-12-inputs-design-pattern.html
- [x] http://lethalman.blogspot.it/2014/09/nix-pill-13-callpackage-design-pattern.html
- [x] http://lethalman.blogspot.it/2014/09/nix-pill-14-override-design-pattern.html
- [x] http://lethalman.blogspot.it/2014/09/nix-pill-15-nix-search-paths.html
- [x] http://lethalman.blogspot.it/2014/11/nix-pill-16-nixpkgs-parameters.html
- [x] http://lethalman.blogspot.it/2014/11/nix-pill-17-nixpkgs-overriding-packages.html
- [x] http://lethalman.blogspot.it/2015/01/nix-pill-18-nix-store-paths.html
- [x] http://lethalman.blogspot.it/2015/08/nix-pill-19-fundamentals-of-stdenv.html

**Comment by ixxie** [comment]
Is there a standard format for this sort of thing? Where exactly would it go?

**Comment by nixy** [comment]
@ixxie I am pretty sure this issue is about making a format for all this. From what Graham said there, it looks like this won't be going in any of the manuals and will be it's own thing.

As for where it should go, I think having either a 'Getting Started' or 'Tutorials' section on nixos.org/nix would be fine. Stuff has to be made before we can worry about where to put it though.

**Comment by ixxie** [comment]
@nixy - I see, I thought it was specifically about Nix Pills. I have been craving a tutorials / cookbook section which is more comprehensive. Perhaps @mbbx6spp and @domenkozar can contribute material from their cookbooks too.

**Comment by ixxie** [comment]
Regarding format, since the manuals are hierarchical and linear, perhaps a cool thing would be to have CMS style searchable collection of tagged recipes / tutorials ? Then if I searched for, say, "installing unstable packages in stable", I would get all the relevant entries in full and could scroll through them until I find what I need.

**Comment by grahamc** [comment]
I've started a conversion here: https://github.com/grahamc/nix-pills This project should not get bogged down in a discussion on how NixOS does documentation. This is going to be maintained as a separate document, and linked on the website as something like "read the nix pills."

---

 - List of Elements: http://tdg.docbook.org/tdg/5.2/chunk-part-d6252e15351.html
 - Tracking Issue: https://github.com/NixOS/nixpkgs/issues/27908

# INSTRUCTIONS

When starting a new Pill, comment on this issue which one
you're doing. If you need help, ask there. If you make progress but
don't finish in one go, make a PR anyway! I'm trying to not edit
things as I go, in order to not get bogged down.

cc @disassembler @ankhers @moretea 

How I've built and tested:

`nix-build && firefox result/share/doc/nix-pills/index.html`

Emacs config for a nice docbook experience, if you happen to use emacs:

 ```nix
 let
  pkgs = import <nixpkgs> {};
  inherit (pkgs) emacsPackagesNg docbook5 writeText;

  schemas = writeText "schemas.xml" ''
    <locatingRules xmlns="http://thaiopensource.com/ns/locating-rules/1.0">
      <documentElement localName="section" typeId="DocBook"/>
      <documentElement localName="chapter" typeId="DocBook"/>
      <documentElement localName="article" typeId="DocBook"/>
      <documentElement localName="book" typeId="DocBook"/>
      <typeId id="DocBook" uri="${docbook5}/xml/rng/docbook/docbookxi.rnc" />
    </locatingRules>
  '';

in emacsPackagesNg.emacsWithPackages (epkgs: [
  (emacsPackagesNg.trivialBuild {
    pname = "nix-docbook-mode";
    version = "1970-01-01";
    src = writeText "default.el" ''
      (eval-after-load 'rng-loc
        '(add-to-list 'rng-schema-locating-files "${schemas}"))
      (global-set-key (kbd "<C-return>") 'nxml-complete)
    '';
  })
])
```

Then you can use the keys:


 - `C-c C-b` to finish & close a tag
 - `C-c C-f` to close a tag
 - `C-return` to auto-complete a tag or attribute.

**Comment by ankhers** [comment]
Thanks for starting this! I will grab pills 3 and 4 to start.

**Comment by NeQuissimus** [comment]
Oooh, nice! Thank you @lethalman !

**Comment by ixxie** [comment]
I'll grab 5 and 6 for now :)

**Comment by lheckemann** [comment]
I'll take 7.

**Comment by ixxie** [comment]
Alright so some notes now that I ported the fifth pill:

1. Some variables were quoted ("a"); I removed quotes and added literals to make style consistent.
2. I followed @grahamc by using literals for code but I did noticed there are <code> tags; maybe the literals should be replaced at some point.
3. Some paragraphs were ambiguous in that there was a line break in the middle without a gap line. In those cases I removed the break since they seemed like one paragraph rather than two.
4. The link to the functions section in the manual was broken; I had to guess the section intended in the post.

I'll try and do the next one this week.

**Comment by lheckemann** [comment]
What about `<code>` vs `<programlisting>`?

**Comment by grahamc** [comment]
Yep, a good point to cover. `<code>` is only appropriate for code _fragments_, like `x: x * 2`. For longer blocks of code, `programlisting` is more appropriate.

That said: we've got a big job ahead of us, and a lot of new tags in docbook that we could discover throughout. I'm not too worried about getting the semantics perfect on the first pass.

**Comment by grahamc** [comment]
Another one I was just reminded of is `<command>`.

**Comment by lheckemann** [comment]
There's also lots to mark up on screen listings: e.g. https://github.com/lheckemann/nix-pills/blob/5f5e3093c478a8bb744ec7ae2c02b77a774b7ec4/pills/07-working-derivation.xml#L61-L65

**Comment by grahamc** [comment]
Oh jeeze, while all that is probably best, I don't think it is a requirement for merging a PR which is otherwise porting a pill. We can always go back and improve them :P

**Comment by ixxie** [comment]
@grahamc so instead of `<screen>`s one can use `<programlisting>`s to put multiline code blocks in the file? It would certainly make it easier for future editing.

**Comment by lheckemann** [comment]
It depends on what you're actually putting in. You should use `<screen>` if you're putting what a user might see on the screen and `<programlisting>` if it's code.

**Comment by grahamc** [comment]
FWIW I put the screen contents in separate files because of difficulties with whitespace in screens.

**Comment by lheckemann** [comment]
I didn't realise that was possible (and really should have, probably). Good idea!

**Comment by ankhers** [comment]
I can grab 8 and 9.

**Comment by ankhers** [comment]
10 and 11

**Comment by grahamc** [comment]
Hey everyone,

I've been hit by a bad flare-up of my RSI and haven't been able to contribute or review much. I will be back to this soon, but must take a few more days rest to recover. Your work has been incredible and inspiring, thank you so much for making this so fast.

Graham

**Comment by ixxie** [comment]
Get well @grahamc! Remember to squeeze a rubber egg or something.

**Comment by disassembler** [comment]
I'll take 19 and 18. Get well @grahamc!

**Comment by disassembler** [comment]
And 17 and 16 as well :)

**Comment by grahamc** [comment]
I just merged all the outstanding PRs, thank you so much. Eight more to go! WOW.

**Comment by grahamc** [comment]
Please send future PRs to http://github.com/nixos/nix-pills

I've made a hydra jobset: https://hydra.nixos.org/jobset/nix-pills/master

I've also made a PR to put the pills on the website: https://github.com/NixOS/nixos-homepage/pull/153

We're in the home stretch. Unfortunately porting a pill is quite typing-heavy, and am not ready to do that yet.

**Comment by disassembler** [comment]
Got 15 and 14

**Comment by Ericson2314** [comment]
FYI I checked some boxes for things I saw PRs for.

**Comment by disassembler** [comment]
I'll grab 12 and 13 too.

**Comment by grahamc** [comment]
We're done 😻 nice work, everyone! Thank you so much! Now to get it on the website :)

**Comment by domenkozar** [comment]
Great job - sorry I couldn't help and thanks to everyone taking part - every improvement to documentation is high appreciated.
