### ISSUE TITLE
Update request: sqlx-cli 0.7.1 → 0.7.3

### ISSUE THREAD

**Issue by MrFoxPro** [NixOS/nixpkgs#279005]
- Package name: sqlx-cli
- Latest released version: 0.7.3

- Current version on the unstable channel: 0.7.1
- Current version on the stable/release channel: 0.7.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@greizgh @xrelkd @fd

-----

Note for maintainers: Please tag this issue in your PR.
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fd** [comment]
I'll take a look at this tomorrow. Thanks for the ping.
