### ISSUE TITLE
transmission web interface no longer work out of the box

### ISSUE THREAD

**Issue by henningphan** [NixOS/nixpkgs#279049]
### Describe the bug
If one installs the transmission service and go to the web interface it wont work, see screenshot.
transmission default web interface no longer work out of the box, one has to set the path to the skins before.
`webHome = "${pkgs.transmission}/share/transmission/web";
`

### Steps To Reproduce
1. enable transmission service
2. go to localhost:9091/transmission/web
3. See the webpage says missing files

### Expected behavior
I expect to see a web interface that allows me to interact with transmission

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/1679039/54a24e0b-8533-4534-b17f-35f33ce80ffb)

### Additional context
A line in transmission.nix, was introduced which to make it easier to point to different web skins I think. But if it isnt set; an empty environment variable is created instead which Im guessing blocks transmission from using its default web skin
`      environment.TRANSMISSION_WEB_HOME = lib.optionalString (cfg.webHome != null) cfg.webHome;
`
Im thinking the solution if the webHome variable isnt set either the env var is removed, or it should default to the packages web skins

### Notify maintainers
@al3xtjames @JulienMalka 
(Sorry If I didnt get the right maintainers, the mappings from git to github is guesswork)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05pre565234.bd645e8668ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by al3xtjames** [comment]
This was introduced with my change (https://github.com/NixOS/nixpkgs/pull/241247). Sorry about that! It should be fixed by https://github.com/NixOS/nixpkgs/pull/278975.

**Comment by bjornfor** [comment]
https://github.com/NixOS/nixpkgs/pull/278975 was merged, closing this.

Here we can track when the fix gets included in the channel: https://nixpk.gs/pr-tracker.html?pr=278975
