### ISSUE TITLE
Package request: weechat-matrix-rs

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#279023]
**Project description**

 Rust rewrite of the python weechat-matrix script. 

**Metadata**

* homepage URL: https://github.com/poljar/weechat-matrix-rs
* source URL: https://github.com/poljar/weechat-matrix-rs
* license: bsd0
* platforms: unix, linux, darwin, ...

**Comment by raspher** [comment]
What are the advantages over python script? Is the python version going to be abandoned?

**Comment by zodman** [comment]
now the weechat-matrix is deprecated ...
