### ISSUE TITLE
PrismLauncher doesnt launch MineCraft anymore on 23.11

### ISSUE THREAD

**Issue by freekvh** [NixOS/nixpkgs#279003]
### Describe the bug
PrismLauncher worked on 23.05, I updated, now PrismLauncher starts but when starting instances, I get an error.

### Steps To Reproduce
1. start prismlauncher
2. launch an instance
3. see error below

### Expected behavior
Launch MineCraft

### Additional context

Prism Launcher version: 8.0 (nixpkgs)

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.239.69.66, 18.239.69.26, 18.239.69.110, 18.239.69.67]

session.minecraft.net resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.246.67, 13.107.213.67]

textures.minecraft.net resolves to:
    [2620:1ec:46::67, 2620:1ec:bdf::67, 13.107.253.67, 13.107.226.67]

api.mojang.com resolves to:
    [2620:1ec:29:1::67, 2620:1ec:48:1::67, 13.107.246.67, 13.107.213.67]

Minecraft folder is:
/home/freek/.local/share/PrismLauncher/instances/1.20.1(2)/.minecraft

Java path is:
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java

Java is version 17.0.7, using 64 (amd64) architecture, from N/A.

12th Gen Intel(R) Core(TM) i5-1235U
Intel Corporation Alder Lake-UP3 GT2 [Iris Xe Graphics] (rev 0c)

DeviceName: Onboard IGD

Subsystem: Hewlett-Packard Company Device 8a9e

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.9

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/freek/.local/share/PrismLauncher/instances/1.20.1(2)/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2-lwjgl.1/lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/freek/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/freek/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/freek/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /home/freek/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /home/freek/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/freek/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /home/freek/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Params:
  --username  --version 1.20.1 --gameDir /home/freek/.local/share/PrismLauncher/instances/1.20.1(2)/.minecraft --assetsDir /home/freek/.local/share/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 14264

/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/b7pb0mmcwjp973nj8gcaa2fnmqxckc8q-libX11-1.8.7/lib/libX11.so.6)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/mdxa9k44xzha1bwwdr3wrbxs4ncb03sq-libxcb-1.16/lib/libxcb.so.1)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/70iyy9bchq62rl5wv9qhcpqpwnd3hysx-libXcursor-1.2.1/lib/libXcursor.so.1)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/0frl7d1aihyr4c1wlbmcdxplgcj0rnja-libGL-1.7.0/lib/libEGL.so.1)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/2cvhyiblil0vgrcbr4x46pvx9150pqfi-systemd-minimal-libs-254.6/lib/libsystemd.so.0)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/0frl7d1aihyr4c1wlbmcdxplgcj0rnja-libGL-1.7.0/lib/libGLdispatch.so.0)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/0frl7d1aihyr4c1wlbmcdxplgcj0rnja-libGL-1.7.0/lib/libGLX.so.0)
/nix/store/2zdyf6z88jp0hvrd972km3bclxwcwg95-openjdk-17.0.7+7/bin/java: /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/8bzgq1kprz2cxar7kvhscjgqnjhbd0i8-libcap-2.69-lib/lib/libcap.so.2)
Process exited with code 1.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

This leads to more info: https://discourse.nixos.org/t/nixpkgs-nixos-unstable-many-package-fail-with-glibc-2-38-not-found/35078

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jopejoe1** [comment]
When opening an issue please ping the maintainers of the coresponding package in this case: @Minion3665 @Scrumplex @getchoo

**Comment by Scrumplex** [comment]
Go into your Prism Launcher settings and update the Java runtime, by clicking Auto-detect. If you have per-instance overrides, make sure to do the same in your instance settings.

**Comment by freekvh** [comment]
> When opening an issue please ping the maintainers of the coresponding package in this case: @Minion3665 @Scrumplex @getchoo

Thanx, I'll do that, I'm new to this.

@Scrumplex , thanx, that worked indeed!
