### ISSUE TITLE
Package request: icestudio

### ISSUE THREAD

**Issue by alxpettit** [NixOS/nixpkgs#279137]
**Project description**

Ice Studio is a self-contained visual IDE for FPGA programming and development. It's available in source tarball, AppImage, and prebuilt zips.

**Metadata**

* homepage URL: https://icestudio.io/
* source URL: https://github.com/FPGAwars/icestudio
* license: gpl2
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
duplicate of #275765

**Comment by alxpettit** [comment]
Whoops! Totally forgot about that, sorry. :P
