### ISSUE TITLE
libvirtd: easier use of virtiofs

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#279179]
To share a folder between the host and guest vm, the `virtiofsd` package has to be installed, and  `<binary path="/run/current-system/sw/bin/virtiofsd"/>` has to be added to every shared filesystem's xml. If the latter is not added, starting the virtual machine will result in an error: Unable to find a satisfying virtiofsd.

There could be an option that installs virtiofsd and makes sure libvirtd can access it.

### Notify maintainers

@fpletz @globin @thiagokokada

**Comment by winny-** [comment]
You'll also have to add `virtiofsd` to `environment.systemPackages`.  Could this warrant a configuration option?

**Comment by srd424** [comment]
@alois31 created #277845 which allows specifying vhost-user packages, and adds the json files into `/var/lib/qemu/vhost-user` - perhaps something similar could be done to put links for the binaries somewhere? The libvirt module (or package, not sure which) adds links to the qemu binaries into `/run/libvirt/nix-emulators/`, so maybe `/run/libvirt/nix-vhostuser` or similar?

**Comment by alois31** [comment]
Doesn't using that option already solve the problem? I think this is exactly the same bug as https://github.com/NixOS/nixpkgs/issues/187078 which was solved by that PR.

**Comment by srd424** [comment]
Oh, I just assumed the path had to be specified in full in the XML like it has to be for qemu. I will do some more testing!

**Comment by srd424** [comment]
Oh, you're right, now I feel silly. Maybe @gepbird can close this?

**Comment by gepbird** [comment]
Thanks for making a fix for this and notifying me about it! I'll try it out soon.
