### ISSUE TITLE
logrotate fails to build on current master

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#27916]
Hey :)

## Issue description
logrotate fails to build on current master
See https://hydra.nixos.org/build/57335219

### Steps to reproduce
With current master:
`nix-build '<nixpkgs>' --option build-use-chroot true --option build-use-sandbox true --keep-going -K -A logrotate`

## Technical details
Did a quick bisect leading me to 093cc00cdd9d8cf31ecce5bc1dd3645c460a1b98 or 3739858571e24e5f5a97a0627369826b240fb8e0 (ping @Ericson2314)
Unfortunately my battery is running low so I can not pinpoint which of those 2 introduced the issue at the moment.

**Comment by Ericson2314** [comment]
The second once has since been reverted for sake of MacOS's old bash in `nix-shell`. The former however can break builds with the new env-vars it defines. I left a message in that commit, but the tl;dr is try
```nix
{
  preConfigure = ''
    LD=$CC
    # or `unset LD`
  '';
}
```

**Comment by fadenb** [comment]
I tried what you suggested (both LD=$CC as well as unsetting LD) but it had no effect.

**Comment by Ericson2314** [comment]
Ah unset CPP—it's trying to use that to build C code, not merely preprocess. But that's quite the upstream bug; I'm curious what's calling it.

**Comment by globin** [comment]
Fixed by using autoconf, the way we were packaging it was deprecated upstream anyway. Updated it while at it.
