### ISSUE TITLE
Cuda-8.0 derivation does not build

### ISSUE THREAD

**Issue by hassemlal** [NixOS/nixpkgs#27913]
## Issue description
I want to install tensorflow with cuda on centos 6.x, but it fails to build cuda. Side note: cuda+cudnn are already installed in /usr/local/cuda-8.0.

### Steps to reproduce
```
$ ls -lhrt /dev/tty
crw-rw-rw-. 1 root tty 5, 0 Aug  3 16:02 /dev/tty
$ bash <(curl https://nixos.org/nix/install)
$ source ~/.nix-profile/etc/profile.d/nix.sh
$ mkdir -p ~/.config/nixpkgs/
$ echo  { allowUnfree = true; } > ~/.config/nixpkgs/config.nix
$ nix-shell -p python27Packages.tensorflowWithCuda

cuda-linux64-rel-8.0.61-21551265.run: line 136: /dev/tty: No such device or address
..../nix/store/5h0dx5q0dzkm6d8kbdr5flplb2rgmsd1-stdenv/setup: line 924: 30891 Terminated              sh cuda-linux64-rel-8.0.61-*.run --keep --noexec
[...]
builder for ‘/nix/store/afmc4aaycs70bc9vnpzbra53h0n8ffm4-cudatoolkit-8.0.61.drv’ failed with exit code 143
cannot build derivation ‘/nix/store/c8vcwnslfx1ivn1n0pzl0jpvvxnai8pf-python2.7-tensorflow-1.1.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c8vcwnslfx1ivn1n0pzl0jpvvxnai8pf-python2.7-tensorflow-1.1.0.drv’ failed
```

## Technical details

* System: CentOS release 6.9 (Final)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09pre111456.d4ef5ac0e9"
* Sandboxing enabled: /etc/nix/nix.conf does not exist.

**Comment by cyounkins** [comment]
On CentOS 7 in Virtualbox, the current `python27Packages.tensorflowWithCuda` builds OK. I'd like to close this since it seems to no longer be an issue.

**Comment by idontgetoutmuch** [comment]
I would suggest closing this issue - I had the same error message, increased my disk size and then it worked.

**Comment by d86leader** [comment]
It's 2021 and I've encountered this issue with `cudatoolkit-11.0.3`. After exploring for a bit, this is what i found. The error about `/dev/tty` is just a red herring, the real issue is that some error message was going to be written there. In my case it was like this:
```
/nix/store/541jmc8r3yvk8bq2vmrhw1bm3ay6n58a-cuda_11.0.3_450.51.06_linux.run: line 215: /dev/tty: No such device or address
/nix/store/qg8qhrxiab3r87xmaxbq565g1g8bnl57-stdenv-linux/setup: line 1309: 15323 Terminated

$ # get the real error
$ sed '215!d' /nix/store/541jmc8r3yvk8bq2vmrhw1bm3ay6n58a-cuda_11.0.3_450.51.06_linux.run

tar $1vf - 2>&1 || { echo Extraction failed. > /dev/tty; echo Ensure there is enough space in $TMPRO
patching /nix/store/7ydfb14vhdwgr73xgkihj62dd90cafgh-cudatoolkit-11.2.1/lib64/libnppidei.so.11.3.2.139...│OT and that the installation package is not corrupt > /dev/tty; kill -15 $$; }
```
So that's why the problem was fixed by some by increasing disk size. In my case though, it was extracting into tmpfs. So I fixed it by running `TMPDIR=/tmp nix-shell mycudashell.nix`

**Comment by luccabb** [comment]
I've encountered this issue with cuda `.run` files in a context unrelated to nix. 

Running as:

```bash
script -c "<your_command>"
```

gave a more informative description:

```log
Script started, file is typescript
Extraction failed.
Ensure there is enough space in /tmp and that the installation package is not corrupt
```

**Comment by Krutonium** [comment]
> 

The year is now 2023 and this issue continues with cudatoolkit.
