### ISSUE TITLE
Build Agda with debug printing?

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#279147]
Agda 2.6.4.1 [introduced](https://hackage.haskell.org/package/Agda-2.6.4.1/changelog) a `debug` configure flag that controls whether debug printing (with `-v`) is enabled (previously it was always enabled).

Should we enable this? I am leaning strongly towards "yes" as I use debug printing quite often and it would suck to have to rebuild Agda.

cc @abbradar @iblech @turion @laMudri @alexarice

**Comment by alexarice** [comment]
is there any downside to enabling it?

**Comment by ncfavier** [comment]
Performance is [slightly worse](https://github.com/agda/agda/pull/6863#issuecomment-1723536296), though I'd say not in a way that matters.

> heavy opt, debug: 6m8,176s
> heavy opt, no debug: 5m45,000s

**Comment by turion** [comment]
If it was true by default before, we should keep that default. We can add an option to the derivation to make it configurable.

**Comment by ncfavier** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/279188
