### ISSUE TITLE
Package request: firefox-pwa

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#279119]
**Project description**

Connector to be used with PWA extension for Firefox.

For reference, it is on AUR: [firefox-pwa](https://aur.archlinux.org/packages/firefox-pwa/) and [firefox-pwa-bin](https://aur.archlinux.org/packages/firefox-pwa-bin).

**Metadata**

* homepage URL: https://pwasforfirefox.filips.si/
* source URL: https://github.com/filips123/PWAsForFirefox
* license: MPL-2.0
* platforms: Linux, macOS, BSD, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jopejoe1** [comment]
Dupelicate of #186961
