### ISSUE TITLE
Moving from 17.03 to unstable broke gnome-tweak-tool

### ISSUE THREAD

**Issue by ixxie** [NixOS/nixpkgs#27926]
I just switched from 17.03 to unstable, and found my gnome-tweak-tool settings didn't carry over. Moreover, while the tweak tool launches fine, and I can see my old settings, they aren't propagated into the system: I see the defaults instead. 

## Technical details

* System: NixOS 17.09pre111447.a7c8f5e419 (Hummingbird)
* Nix version: 1.11.13
* Nixpkgs version: 17.09pre111447.a7c8f5e419
* Sandboxing enabled: false

**Comment by bjornfor** [comment]
I think it's the same cause as in https://github.com/NixOS/nixpkgs/issues/25906
