### ISSUE TITLE
albert launcher license/distribution issues

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#279226]
### Describe the bug

 - https://github.com/albertlauncher/albert/commit/f9a33001e9e2930291e8d1a8669a6c43d1de2269#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1d

Since `v0.21.0`, see tag list in the commit, the license is <del>(possibly illegitimately)</del> (some claim illegitimately) proprietary freeware.

### Additional context

Drive-by reporting since I saw this in my feed.

 - https://social.treehouse.systems/@mgorny/111708984184055051
 - https://bugs.gentoo.org/766129
 - https://web.archive.org/web/20210225183856/https://github.com/albertlauncher/albert/issues/765

### Notify maintainers

@MikaelFangel

@ericsagnes @synthetica

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MikaelFangel** [comment]
Hmm, I'm a bit unsure if this prohibits us from redistributing the package through nix? Or if it's enough to set the license to unfree? 💭

**Comment by samueldr** [comment]
I actually do not know. I'm not sure who to reach out to at this point in time to get opinions about the situation.

Though at the very least a first step would be changing the license information to mirror the information the project advertises, which is unfree and unredistributable [binary].

**Comment by eli-schwartz** [comment]
> Since `v0.21.0`, see tag list in the commit, the license is (possibly illegitimately) proprietary freeware.

This changed years ago in version 0.14.21, it is not new since 0.21.0.

**Comment by eli-schwartz** [comment]
> Hmm, I'm a bit unsure if this prohibits us from redistributing the package through nix? Or if it's enough to set the license to unfree? 💭

Is it legal to distribute a package through nix that contains an infringing mixture of nonfree proprietary freeware + GPL code? This is an interesting question that is distinct from whether it is legal to mirror the source code and/or test it in CI, provide cached binary versions, etc.

**Comment by ManuelSchneid3r** [comment]
@eli-schwartz You spreading this all over the web. I see that your personal preference is copyleft, however spreading bad press just because you dont like the licencse is not fair and plain immoral imho. The contributions have all been modularized. Licensing is all fine afaik. No infringement. If you think otherwise please let me know and _please_ stop FUD.

> (possibly illegitimately)

```bash
~/albert/plugins $ find .  |while read i ; do git blame "$i" | grep -v "Manuel Schneider" ;done 2> /dev/null |wc -l
1349
```
```bash
~/albert $ find src include | while read i ; do git blame "$i" | grep -v "Manuel Schneider" ;done 2> /dev/null| wc -l
0
``` 

Eli is right in one point though: Distribution is somewhat cumbersome due to the GPL. IANAL but the GPL licensed plugins probably have to go into a separate package simply because the GPL requires it, because afaik GPL is not compatible with non copyleft licenses.

**Comment by MikaelFangel** [comment]
@ManuelSchneid3r but even if we split the package we would still have a problem right? Because we are not allowed to distribute via Nix and NixOS according to the license. Nix and NixOS are not included in the allowed list (see my issue in the Albert repo). 

Am I misunderstanding something or are you planning in extending the license? ☺️

**Comment by 7c6f434c** [comment]
> Hmm, I'm a bit unsure if this prohibits us from redistributing the package through nix? Or if it's enough to set the license to unfree?

Setting license to unfree will, by the current general policy, automatically stop Hydra builds and pushing versions linked against the up-to-date stdenvs to the binary cache. So we would not be distributing the source or binaries, only the metadata about how to build. I think we do it for a lot of non-redistributable things already.

(The binary cache would still have the old builds with the unfortunately mislabeled license, though)

**Comment by eli-schwartz** [comment]
> @eli-schwartz You spread this all over the web. I see that your personal preference is copyleft, however spreading bad press just because you dont like the licencse is not fair and plain immoral imho.

You are factually wrong about my thought processes and personal feelings.

I respect the right of software developers to license or relicense their personal work as they wish -- I have zero respect for software developers who commit copyright infringement against third-party contributions by claiming they are legally permitted to relicense copyleft software that they don't own.

> The contributions have all been modularized. Licensing is all fine afaik. No infringement. If you think otherwise please let me know and _please_ stop FUD.

When dealing with other people's property that you are not allowed to use, the ideal scenario if you cannot contact each person and get a copyright assignment or an unlimited personal license (to reuse, copy, distribute as though it were your own) is to hire a copyright lawyer to ensure that you are fulfilling your legal requirements. Failing that, you get to be your own lawyer but without the training in copyright law.

You do need to verify what was contributed and that no traces remain. You also need to reassure potential users that this has been done.

No one believes a word out of the mouth of someone that proudly proclaims "I don't understand copyright, so I'm going to write my own license to protect my rights that the GPL already gives me", and then deletes the discussion when users raise their concerns. Deleting the issue sends a very loud and clear message to users, and it's not a polite message.


> > (possibly illegitimately)
> 
> ```bash
> ~/albert/plugins $ find .  |while read i ; do git blame "$i" | grep -v "Manuel Schneider" ;done 2> /dev/null |wc -l
> 1349
> ```
> ```bash
> ~/albert $ find src include | while read i ; do git blame "$i" | grep -v "Manuel Schneider" ;done 2> /dev/null| wc -l
> 0
> ``` 

I'm not sure what you think `git blame` is, but it does not tell you what license the code is under.

This is readily apparent to anyone that knows what *precisely*, git blame actually does.

If you want to know whether the code contains someone else's legally significant GPL contribution, you need to perform a proper review.

> Eli is right in one point though: Distribution is somewhat cumbersome due to the GPL. IANAL but the GPL licensed plugins probably have to go into a separate package simply because the GPL requires it, because afaik GPL is not compatible with non copyleft licenses. 

The GPl explicitly forbids "combined works" containing code incompatible with the GPL. Combining a GPL licensed plugin with a program that is not GPL compatible (such as a proprietary freeware license) is a combined work. The general rule of thumb is that use of "APIs" or "linking" means it's a combined work. The standard workaround for this is to communicate with software under an incompatible license by invoking the incompatible software as an externally forked disk executable, and only using the standard output stream (which is content that the software produces; much like using Microsoft Word to write a school essay doesn't mean that your school essay belongs to Microsoft).

Note that it also depends what sort of information is actually being communicated via rpc: https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

Keep in mind that the GPL was written by "actual for real lawyers" with the explicit intent of treating plugins as a technology which authors of nonfree software often try to use to "nefariously circumvent their obligations when incorporating GPL code into their program.

In short: albert plugins that use the GPL (whether the plugin code is GPL or whether it links to a GPL library) are illegal to distribute in binary form, even in a separate package.

I would like to think that they're illegal to distribute in source form as well, but I'm not sure that's actually legally the case... it's an unethical attempt to violate the spirit of the law anyway, so, boo.

...

Note that the LGPL exists explicitly for the case where authors of software would like to write GPL software but also wish to allow proprietary software to use the GPL stuff. The LGPL solves this use case by permitting linking an LGPL shared library with proprietary (and other non-GPL) software, as long as the user has the right to modify, redistribute, etc. the shared library (and use the proprietary program in combination with the updated version of the shared library).

The authors of the LGPL explicitly note that it is only intended to be used in cases where the Free Software Movement's goals of promulgating Free Software are better served by providing Free Software alternatives to proprietary libraries. e.g. media codecs designed to compete with proprietary alternatives, where wide community adoption is key, even when that means convincing proprietary software to adopt an LGPL dependency.

**Comment by ManuelSchneid3r** [comment]
> > @eli-schwartz You spread this all over the web. I see that your personal preference is copyleft, however spreading bad press just because you dont like the licencse is not fair and plain immoral imho.
> 
> You are factually wrong about my thought processes and personal feelings.
> 
> I respect the right of software developers to license or relicense their personal work as they wish -- I have zero respect for software developers who commit copyright infringement against third-party contributions by claiming they are legally permitted to relicense copyleft software that they don't own.

Thats fine. I dont. 

> You do need to verify what was contributed and that no traces remain. You also need to reassure potential users that this has been done.

Because this is so exhausting to discuss over and over I indeed took the time to review it. [Core and plugins](https://github.com/albertlauncher/albert/issues/1354) are done, [python plugins](https://github.com/albertlauncher/albert/issues/1349) are on the way.

> No one believes a word out of the mouth of someone that proudly proclaims "I don't understand copyright, so I'm going to write my own license to protect my rights that the GPL already gives me", and then deletes the discussion when users raise their concerns. Deleting the issue sends a very loud and clear message to users, and it's not a polite message.

Because I was (am) not willing to release the code under a copyleft license, people became so upset that the discussion completely escalated and became personal. I only deleted the issue because they completely threw me off balance with demands, insults, and ingratitude, and it was such a low-level discussion that didn't belong on an issue tracker. Moreover, it eventually turned into a general flamewar and had nothing to do with the licensing of Albert in the end. 

> If you want to know whether the code contains someone else's legally significant GPL contribution, you need to perform a proper review.

There have never been GPL contributions besides a few Python plugins. There license transition to MIT is waiting to be approved, if rejected they will be removed.

> The GPl explicitly forbids "combined works" containing code incompatible with the GPL. Combining a GPL licensed plugin with a program that is not GPL compatible (such as a proprietary freeware license) is a combined work. The general rule of thumb is that use of "APIs" or "linking" means it's a combined work. The standard workaround for this is to communicate with software under an incompatible license by invoking the incompatible software as an externally forked disk executable, and only using the standard output stream (which is content that the software produces; much like using Microsoft Word to write a school essay doesn't mean that your school essay belongs to Microsoft).
> 
> Note that it also depends what sort of information is actually being communicated via rpc: https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation
> 
> Keep in mind that the GPL was written by "actual for real lawyers" with the explicit intent of treating plugins as a technology which authors of nonfree software often try to use to "nefariously circumvent their obligations when incorporating GPL code into their program.
> 
> In short: albert plugins that use the GPL (whether the plugin code is GPL or whether it links to a GPL library) are illegal to distribute in binary form, even in a separate package.
> 
> I would like to think that they're illegal to distribute in source form as well, but I'm not sure that's actually legally the case... it's an unethical attempt to violate the spirit of the law anyway, so, boo.

> Note that the LGPL exists explicitly for the case where authors of software would like to write GPL software but also wish to allow proprietary software to use the GPL stuff. The LGPL solves this use case by permitting linking an LGPL shared library with proprietary (and other non-GPL) software, as long as the user has the right to modify, redistribute, etc. the shared library (and use the proprietary program in combination with the updated version of the shared library).
> 
> The authors of the LGPL explicitly note that it is only intended to be used in cases where the Free Software Movement's goals of promulgating Free Software are better served by providing Free Software alternatives to proprietary libraries. e.g. media codecs designed to compete with proprietary alternatives, where wide community adoption is key, even when that means convincing proprietary software to adopt an LGPL dependency.

Thats right. I think i understand the GPL, although I dont see the point in that "IO is not combined work thing". Thats just a technical aspect. They are functionally equivalent. Sure serialization adds overhead but its possible to emulate using RPCs.

**Comment by samueldr** [comment]
@eli-schwartz: as someone coming from outside of the NixOS community, ***please*** do not use our issue tracker as a place to discuss in an inflammatory manner. (And to be fair, people of the NixOS community, please be good and don't.)

@ManuelSchneid3r: feel free to respond in kind when you are directly concerned, but also keep in mind that this is a tracking issue for our distro, for the licensing issue, which should be considered of neutral sentiment here.

(It's not for us to decide, we mainly need to correct the misrepresentation and faithfully represent the reality.)

* * *

The debate about whether the project itself is or isn't OSS, is or isn't doing it legitimately, likely should be *continued* at the project. And all parties, please be good and think of the people in the discussions. It seems in this situation there is a lot of nuance.

**Comment by ManuelSchneid3r** [comment]
I recently changed the license to [1.1](https://raw.githubusercontent.com/albertlauncher/albert/main/LICENSE.md). This is basically a BSD-2-Clause without the permission for redistribution of modifications and an explicit exclusion of Microsoft or Apple platforms.
