### ISSUE TITLE
Ideas about options in NixOS

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#27927]
Just few ideas (maybe useless for most) and draft implementations for some of them.

1. A warning if user has an option set to it's default value
```diff
diff --git a/lib/modules.nix b/lib/modules.nix
index 4eee41306cd7..fb9b146bdb03 100644
--- a/lib/modules.nix
+++ b/lib/modules.nix
@@ -296,8 +296,28 @@ rec {
         else
           res.mergedValue;
 
+      needCheckForDefault = builtins.getEnv "NIX_EXCESS_OPTIONS" == "1" &&
+        opt ? default && defs != [];
+
+      nixpkgsPath = concatMapStrings (env: removePrefix "nixpkgs=" env)
+        (filter (env: hasPrefix "nixpkgs" env)
+          (splitString ":" (builtins.getEnv "NIX_PATH")));
+
+      checkedForDefault = concatMapStrings (def:
+        if !hasPrefix nixpkgsPath def.file && def.value == opt.default then
+          "The option `${showOption loc}' in `${def.file}' already has that value by default (in `${head opt.declarations}').\n"
+        else
+          "")
+        (mergeDefinitions loc opt.type defs).defsFinal;
+
+      checkForDefault =
+        if needCheckForDefault && checkedForDefault != "" then
+          builtins.trace checkedForDefault value
+        else
+          value;
+
     in opt //
-      { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
+      { value = addErrorContext "while evaluating the option `${showOption loc}':" checkForDefault;
         definitions = map (def: def.value) res.defsFinal;
         files = map (def: def.file) res.defsFinal;
         inherit (res) isDefined;
```
Example:
```
# NIX_EXCESS_OPTIONS=1 nixos-rebuild switch                                                    
building Nix...              
building the system configuration...                       
trace: The option `hardware.opengl.driSupport32Bit' in `/etc/nixos/configuration.nix' already has that value by default (in `/home/gnidorah/tmp/nixpkgs/nixos/modules/hardware/opengl.nix').
```
2. A warning if user has the same option defined across different files
```diff
diff --git a/lib/options.nix b/lib/options.nix
index 2092b65bbc3a..5f06e813bdc0 100644
--- a/lib/options.nix
+++ b/lib/options.nix
@@ -71,6 +71,8 @@ rec {
     else foldl' (val: def:
       if def.value != val then
         throw "The option `${showOption loc}' has conflicting definitions, in ${showFiles (getFiles defs)}."
+      else if builtins.getEnv "NIX_EXCESS_OPTIONS" == "1" && length defs != 1 then
+        builtins.trace "The option `${showOption loc}' is defined multiple times, in ${showFiles (getFiles defs)}." val
       else
         val) (head defs).value defs;
 
```
Example:
```
# NIX_EXCESS_OPTIONS=1 nixos-rebuild switch
building Nix...
building the system configuration...
trace: The option `hardware.opengl.driSupport32Bit' is defined multiple times, in `/etc/nixos/hardware-configuration.nix' and `/etc/nixos/configuration.nix'.
```
3. A warning if `environment.systemPackages` in configuration contains the package already pulled in by `environment.systemPackages` from some module or `propagatedUserEnvPkgs` from some package
4. Show which options changed their default values after system update
5. On upgrade show which packages have no binary caches and will be built from sources. Maybe some other useful info like how many Mb's will be downloaded

**Comment by vyp** [comment]
For 3 regarding `propagatedUserEnvPkgs`, what if the intention by the user is to say that they also want to use that package, regardless of whether it is a propagated user env package or not? (As in, it is supposed to be *declarative* configuration after all. And maybe a package being propagated into the user environment was just a coincidence.) If that's the case then it might be annoying to see a warning, if that made sense. Otoh I can see the reason for warning as well, so I don't feel too strongly about this either.

**Comment by Infinisil** [comment]
I'm not sure if a warning for setting default values is a good thing: Some people might want to set defaults explicitly, in case they change later, or just to be sure. But then again, if it's not a strict 'warning', but rather a 'note', I don't think anyone would mind that. A potential disadvantage of this (if it's applied to all options), is increased `nixos-rebuild` time, which is already pretty long..

As an alternative I've been thinking of is to make a package that takes your configuration.nix and minimizes it by removing options set to defaults, as an on-demand optimization. This may be a bit tougher to make, but it has the advantage of not making rebuilds longer and not spitting warnings/notes.

**Comment by danbst** [comment]
On 5, it is already there, just the UI isn't clear about it.
