### ISSUE TITLE
vscode crashes with NIXOS_OZONE_WL=1

### ISSUE THREAD

**Issue by itsvic-dev** [NixOS/nixpkgs#279261]
### Describe the bug
When running `vscode` with `NIXOS_OZONE_WL=1`, at least under Hyprland, it crashes.

### Steps To Reproduce
1. set `NIXOS_OZONE_WL=1` somewhere
2. run vscode
3. watch it try to launch before crashing

### Expected behavior
It should work just like how it works under X11/Xwayland.

### Notify maintainers
@eadwu  @amaxine @bobby285271 @Enzime 

### Metadata

```console
vic@e6nix ~ % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8-xanmod1, NixOS, 23.11 (Tapir), 23.11.2561.b0b2c5445c64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
There are numerous upstream issues with vscode and wayland https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+in%3Atitle+wayland

For example you need to turn off the fancy menubar or just switch to xwayland.

**Comment by itsvic-dev** [comment]
I see. For me, using Xwayland is not a great option, because that means that I cannot use an IME in all Chromium/Electron apps, but setting the title bar style to custom does work around this issue.
