### ISSUE TITLE
`nixos-option` should show the type of an option

### ISSUE THREAD

**Issue by taktoa** [NixOS/nixpkgs#27920]
## Issue description

We can currently display a NixOS module option type using, for example:
`(types.enum ["foo" "bar"]).description`.

It seems to me that, to maximize usability, `nixos-option` should display this string.

Also, the [NixOS options browser](https://nixos.org/nixos/options.html) should display this information.
Perhaps it should be toggleable, though, since options involving submodule types could be quite large.

EDIT: Apparently the `description` field is currently `"submodule"` for any submodule type. It would be nice to either pretty-print the whole type or output some kind of structured data there.

### Steps to reproduce

Run `nixos-option services.postgresql.enable`. There is no indication of the type of this option other than the default/example values.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by domenkozar** [comment]
cc @nbp

**Comment by chkno** [comment]
This was fixed in 26c45dfec2716b1508e5d7ac8efdbdf570f2eb99.
