### ISSUE TITLE
Custom nixpkgs channels

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#2793]
Is there a way to create custom nixpkgs channels? Something similar to PPAs in ubuntu land. I know I can override packages, but I would like to do it on a cloud hosted custom/private channel instead of a custom module on a single system.

This part: 
http://nixos.org/nixos/manual/#sec-custom-packages

Explains overriding, or using the official nixpkgs and using pull-request, but doesn't explain how to run a private/custom nixpkgs channel.

**Comment by matthiasbeyer** [comment]
I guess this issue is (at least partly) solved as well, anyone caring about closing this one?

**Comment by konobi** [comment]
How does nix deal with conflicts between different channels? (ie: 2 channels, 1 package, differences in the nix or files copied, etc)

Is there some sort of way to set channel precedence?
