### ISSUE TITLE
Cannot load kvm_intel inside a VM (nested virtualisation) 

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#27930]
## Issue description
I'm running a nixos VM on KVM (openstack with libvirt). I try to use KVM inside this VM but I cannot load the `kvm_intel` kernel module. 
```
modprobe kvm_intel
modprobe: ERROR: could not insert 'kvm_intel': Input/output error
```
On the same environment, I successfully load the kvm_intel module on a ubuntu VM. So, the host support the nested virtualisation. 

Is someone using nested KVM virtualisation on Nixos ?

### Steps to reproduce
I reproduce by running a nixos test VM on my laptop () but I'm really not sure if this kind of VM can support nested virtualisation:
```nix-build nixos/tests/openssh.nix -A driver && result/bin/nixos-run-vms```
Log as root and type:
```
# modprobe kvm
# modprobe kvm_intel
modprobe: ERROR: could not insert 'kvm_intel': Input/output error
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
The image has been genereated by `system.build.novaImage`.
Linux nixos 4.9.35 #1-NixOS SMP Thu Jun 29 11:00:49 UTC 2017 x86_64 GNU/Linux
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.03.1449.2e983f14f6
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by copumpkin** [comment]
I also noticed some weirdness in the past release of NixOS where nested virtualization stopped working. In my case it would just hang, but apparently it's known to be somewhat flaky?

**Comment by nlewo** [comment]
I switched to the kernel ` 4.4.79` and it works for me.

**Comment by globin** [comment]
NixOS tests set `-cpu kvm64` for reproducibility which disables nested kvm.

To enable for yourself make sure that the module is loaded with `nested=1` on the host:
```
# modprobe -r kvm_intel
# modprobe kvm_intel nested=1
```
To persist:
```
boot.extraModprobeConfig = "options kvm_intel nested=1"
```

Make sure your VM is started with `-cpu host` and `-enable-kvm`.

You can test if the VM has support for nested kvm by running:
```
grep vmx /proc/cpuinfo
```

**Comment by copumpkin** [comment]
In my case I'm using VMWare and it breaks too. Not sure what the equivalent of that is...

**Comment by fpletz** [comment]
Are other distributions enabling nested KVM by default or do they detect they're running in a virtualized environment?

**Comment by nlewo** [comment]
@volth it seems you also had this issue. Did you find a way to fix it ?

**Comment by volth** [comment]
I  using 4.4 kernel (and NixOS 17.09-beta which had 4.4, I stopped upgrading at that point)

**Comment by nlewo** [comment]
hmm, ok :(
I tryied with the kernel 4.13 but it doesn't work better.

**Comment by volth** [comment]
Post-4.9 kernels do not even boot on half of my servers :(

**Comment by xeji** [comment]
Do others still have this issue today?

On a host with current nixos-unstable and kernel 4.14, I can run nested kvm guests inside a libvirt qemu guest (NixOS or Arch) without problems.
All I had to do is  `boot.kernelModules = [ "kvm-intel" ];` and
`boot.extraModprobeConfig = "options kvm_intel nested=1";`.
