### ISSUE TITLE
calibre is broken

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#27944]
## Issue description

Attempting to run calibre produces the following message:

```
bash-4.4$ calibre
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted
```

### Steps to reproduce

Install the application, attempt to run it

## Technical details

* System: 17.09.git.a61c8c5 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09.git.a61c8c5440"
* Sandboxing enabled: build-use-sandbox = true

**Comment by FRidh** [comment]
> Install the application, attempt to run it

How did you install?

**Comment by adisbladis** [comment]
All Qt applications are currently broken on master, going to be fixed at next staging merge.

**Comment by jonafato** [comment]
#24256 is fixed, and I can't reproduce this issue on master. Can this be closed?

**Comment by globin** [comment]
Confirmed as fixed

**Comment by shlevy** [comment]
I'm seeing this issue on the 18.03 channel, is there something that needs backporting?

**Comment by adisbladis** [comment]
@shlevy Qt apps are a bit "special". 
You need to install them either to your system profile or your user profile and your user profile should preferably be from the same version of nixpkgs as your system profile.

@ttuegel knows more about this.

**Comment by orivej** [comment]
There is a generic workaround to launch apps built against any version of Qt: https://github.com/NixOS/nixpkgs/issues/30551#issuecomment-346319767
