### ISSUE TITLE
Update request: unrar  6.2.12→  7.00 beta 3

### ISSUE THREAD

**Issue by carpediem29** [NixOS/nixpkgs#279409]
-     Package name: unrar 
-     Latest released version: 7.00 beta 3
-     Current version on the unstable channel: 6.2.12
-     Current version on the stable/release channel: 6.2.12

I receive more and more RAR files which are created with Unrar 7.00 beta versions / require a more recent version tan 6.2.12 
I would appreciated if  the existing unrar package can be updated or a new unrar-beta package be proposed .. 

Changelog : https://www.rarlab.com/rarnew.htm

Notify maintainers
@ehmry 
@wegank

**Comment by wegank** [comment]
There was an automatic update in #266998 that I marked as draft, exactly because it's in beta. I'd much rather add a new package. @ehmry what do you think?

**Comment by ehmry** [comment]
I don't think we should update to the beta either. Sometimes I think about adding beta and release candidate versions to package `passthru`, but that would be a nixpkgs policy discussion.

**Comment by ehmry** [comment]
> I receive more and more RAR files which are created with Unrar 7.00 beta versions / require a more recent version tan 6.2.12

If people are still creating new RAR files then I don't want to be maintainer of this package. **Stop using RAR.**
