### ISSUE TITLE
Update request: blockbench-electron 4.8.1 → 4.9.3

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#279495]
- Package name: blockbench-electron
- Latest released version: 4.9.3

- Current version on the unstable channel: 4.8.1
- Current version on the stable/release channel: 4.8.1

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ckiee 

Misc: Noticed this when trying to enter a nix shell with this package, resulting in an electron-25.9.0 EOL error.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Okay, so I took a look at updating blockbench to a version with uses `electron_26` and but it looks like after 2 seconds, electron crashes. It's probably got to do something with `electron-remote`, but I don't have much experience with it. Tried to debug it with `--enable-logging`, but it didn't really show me anything helpful. I even tried packaging from source, but it has the same issue.

**Comment by TomaSajt** [comment]
Okay, so I did some more testing, and it looks like `electron_26` itself is the issue, `electron_27` and above work fine.
I'll make a PR with the update.
