### ISSUE TITLE
Update request: calamares 3.2.62→ 3.3.0

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#279444]
- Package name: calamares
- Latest released version: 3.3.0

- Current version on the unstable channel: 3.2.62
- Current version on the stable/release channel: 3.2.62

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@manveru @vlinkz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vlinkz** [comment]
To test, read here: https://github.com/NixOS/calamares-nixos-extensions/pull/26

**Comment by JohnRTitor** [comment]
@vlinkz can this be safely backported to release-23.11? Does it contain any breaking changes?

**Comment by D3vil0p3r** [comment]
Closing because already managed on different PR.
