### ISSUE TITLE
Consider lld as linker on ELF (Linux)

### ISSUE THREAD

**Issue by dcci** [NixOS/nixpkgs#27951]
## Issue description

lld (http://lld.llvm.org/) seems to be "mature enough", these days.
With 5.0 release, it might make sense giving a shot as it's much much faster than `ld.bfd` (which is still the default on every Linux as far as I can tell) and reasonably faster than `ld.gold`.
ghc recently tried it with reasonable success 
https://www.reddit.com/r/haskell/comments/63y43y/liked_linking_3x_faster_with_gold_link_10x_faster/

I'll be happy to work on this (as I also work on lld/llvm) but first I want to know if it's something reasonable (& probably I'll need some guidance on how to actually implement/try this).

**Comment by copumpkin** [comment]
This (and more LLVM-based tools in general) might also make cross-compilation more pleasant, cc @Ericson2314 

I'd also love to see `lld` for Mach-O files on Darwin but it's less clear to me how mature it is in that space. We already use LLVM for everything else there, so it wouldn't be too far off.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/24744

**Comment by copumpkin** [comment]
Not quite a dupe, as that one wants `lld` to work properly, and this one wants it (as I understand it) in the stdenv as the default linker.

**Comment by dcci** [comment]
@domenkozar  I don't think it's a dupe.
@copumpkin I'm afraid having `lld` for Mach-O is still a pipe dream as that bit of the linker is quite unmaintained (last I tried, ~ 1 month ago, lld on Mach-O wasn't even able to self-host with a recent'(ish) OS/toolchain [El Capitan]).

Assuming there's  consensus to go forward, I'd love to discuss next steps.
I'm not a NixOS dev, but given I use it on my main workstation these days (and I love it :)) I thought I could help a bit on this side. What's the best way to do this work incrementally.
I'm very willing to debug any bug/mislinks etc..

Something else I'd like to add.
lld/ELF is quite unique as it has LTO support built-in (differently from `ld.gold` and `ld.bfd` which need a plugin to work). As LLVM developer I found out this being a killer feature as you just need to pass `-flto` to clang` and lld can read LLVM bitcode files and call the mover/optimizer transparently.
This has the great advantage that, if NixOS decides to support LTO at some point in the future, enabling it it's just a matter of passing a flag to clang (well, two, if you consider `-fuse-ld=lld`) instead of building an extra shared library and making sure the plugin bits are passed down to the linker (which may be not particularly pleasant in more complex build systems).

**Comment by nh2** [comment]
@dcci Would you be up for working on #24744, which is a requirement for making this happen?

It would be great to have good `lld` support across nixpkgs.

**Comment by Gaelan** [comment]
Still important to me.

**Comment by S-NA** [comment]
In 2020 [a new Mach-O backend was added](https://reviews.llvm.org/D75382). According to the homepage, "[t]he linker supports ELF (Unix), PE/COFF (Windows), Mach-O (macOS) and WebAssembly in descending order of completeness." While I cannot personally attest to it, I have heard good reports of people being able to use LLD for Mach-O. That being said the new hurdle is with Apple moving to AArch64 and requiring that executable binaries be code signed on the new macOS machines. (Which the system linker (ld64) does by default.)

**Comment by nh2** [comment]
As relevant as ever.

**Comment by Ericson2314** [comment]
This can be done using the `linker` field of the platform config, which is also set by `useLLVM = true` and `pkgsLLVM`. I think we are done here!
