### ISSUE TITLE
Package request: LG webOS cli 

### ISSUE THREAD

**Issue by hufforguk** [NixOS/nixpkgs#279606]
**Project description**

ares-cli is a command-line interface (CLI) for webOS. It provides a collection of commands used for creating, packaging, installing, and launching apps or services in the command line environment. ares-cli lets you develop and test apps or services without using any IDE.

**Metadata**

* homepage URL: https://webostv.developer.lge.com/develop/tools/cli-introduction
* source URL: https://github.com/webosose/ares-cli
* license: Apache2
* platforms: linux, darwin, 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/312465
