### ISSUE TITLE
gnomeExtensions.systemd-manager outdated and crashes in Gnome 45.2 Wayland

### ISSUE THREAD

**Issue by naturallaw777** [NixOS/nixpkgs#279638]
### Describe the bug
After reboot, while systemd units are still loading, if user clicks on Systemd-Manger extension the entire DE will crash and Gnome will force a log out of that user.

Moreover, Systemd-Manager is at v14 when v15 is out from the developer.

### Steps To Reproduce
1. Restart Computer
2. After DE loads and user is logged in
3. Click on Systemd-Manager (while the systemd units [custom added systemd units by the user into the extension] are still loading for example "bitcoind")
4. DE crashes and forces log out

### Expected behavior
No crashing of DE and you should be able to see in Systemd-Manager the units that have not started without it crashing

### Notify maintainers

@piegamesde 

### Metadata

``` 
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.10, NixOS, 24.05 (Uakari), 24.05.20240106.46ae021`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by naturallaw777** [comment]
Any news on this? Thanks so much!

**Comment by naturallaw777** [comment]
Any news on this @piegamesde? Thanks so much!

**Comment by piegamesde** [comment]
Update should be contained in #282143

**Comment by naturallaw777** [comment]
sweet!!! Thanks, I will keep an eye on it. Thanks again!

**Comment by lasandell** [comment]
I checked and #282143 plus the superseding #285869 still contain version 14. The author notes on the [extension page](https://extensions.gnome.org/extension/4174/systemd-manager/) that they will no longer be publishing to that site, and indeed the latest version available for download there is still 14. So the metadata for that extension may need to be manually overridden in nixpkgs since it is not going to get the latest from extensions.gnome.org via the automated update process.

**Comment by 4JX** [comment]
```nix
{ lib, stdenv, fetchzip, gnome, buildPackages }:

stdenv.mkDerivation rec {
  pname = "systemd-manager";
  version = "15";

  src = fetchzip {
    url = "https://github.com/hardpixel/systemd-manager/releases/download/v${version}/systemd-manager-v${version}.zip";
    hash = "sha256-IIiHvntAnaEJIiofNDOQXDKeJupyEMys32N8Qz1IfXk=";
    stripRoot = false;
  };

  passthru = {
    extensionUuid = "systemd-manager@hardpixel.eu";
    extensionPortalSlug = "systemd-manager";
  };

  nativeBuildInputs = [ buildPackages.glib ];

  buildPhase = ''
    runHook preBuild
    if [ -d schemas ]; then
      glib-compile-schemas --strict schemas
    fi
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/share/gnome-shell/extensions
     cp -r -T . $out/share/gnome-shell/extensions/${passthru.extensionUuid}
    runHook postInstall
  '';

  meta = with lib; {
    description = "GNOME Shell extension to manage systemd services";
    license = licenses.gpl2Plus;
    maintainers = with maintainers; [ ];
    homepage = "https://github.com/hardpixel/systemd-manager";
  };
}
```
This works as a standalone package, for inclusion in `nixpkgs` you'd probably be fine not declaring `nativeBuildInputs`,`buildPhase`,`meta.license`. Would be happy to make a PR for it, though it's not something I'd actively mantain/use myself.

**Comment by lasandell** [comment]
Looks good! That updated package does fix the crash for me.

**Comment by naturallaw777** [comment]
@lasandell did you just install the package from nixos?

**Comment by naturallaw777** [comment]
@4JX  yes, it seems then having its own package would be the best no?

**Comment by lasandell** [comment]
@naturallaw777 Ah no, it would need a PR to even get into nixpkgs. I just added it to my local config using an overlay.

**Comment by naturallaw777** [comment]
okay, well I will look into how to overly in a nix file. 

Also, it is hard to maintain a package? As, maybe I could learn how to maintain this extension if @4JX will be unable to maintain it?

**Comment by 4JX** [comment]
Maintaining an extension like this should be as simple as increasing the version number when a new release exists, given it's lack of external dependencies or nixos-specific quirks that need to be patched (there may be some out there).

What I meant by not mantaining it is that I do not actively use it within my setup. And I assume these manually packaged ones would need at least a "reference" mantainer to keep it in check and direct issues to.

**Comment by naturallaw777** [comment]
Thanks for the good info @4JX ! Well, I can be the maintainer, but I might need help from time to time. I will use your code @4JX if that is okay?

So, next steps to put in the PR and then add me as the maintainer. Also, @piegamesde  would you want to be on this as well?

**Comment by lasandell** [comment]
piegamesde was only the maintainer of the original extension package because they're the [default maintainer of automatically packaged extensions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/buildGnomeExtension.nix#L58). Manually packaged extensions go in [this list](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/manuallyPackaged.nix) and generally have a maintainer attribute set.

**Comment by naturallaw777** [comment]
Circling back to this... I would like to be the maintainer of this plugin. However, I have never maintained a piece of software on github and I only have minimal skills with shell and nix configuration files. I have never made or packaged a nix module before. 

Should this task be reserved for someone else with more skills or is there someone who could mentor me in how to be a maintainer?

Thank you all for the help in this.

**Comment by naturallaw777** [comment]
Added this the extension creator's github :

https://github.com/hardpixel/systemd-manager/issues/20

**Comment by naturallaw777** [comment]
Okay, I figured out how to add @4JX 's code into my existing setup. 

For all the noobs out there this is what I did it:

I did NOT use the "overlay" process in NixOS as describe here: https://nixos.wiki/wiki/Overlays

I used the `callPackage` process as described here: https://unix.stackexchange.com/questions/717168/how-to-package-my-software-in-nix-or-write-my-own-package-derivation-for-nixpkgs This is an excellent write up BTW! Save this link for future use. 

With these resources in mind, this is what I did. I used @4JX 's code and named the file `systemd-manager.nix`. This naming is arbitrary. It can be anything you want as long it has `.nix` at the end. Then, move that `.nix' file into `/etc/nixos/` directory. Do this via terminal and you must be the `root` user.

Then in my NixOS (not nix) configuration file (`/etc/nixos/configuration.nix`) I simply added `(callPackage ./systemd-manager.nix {})` into the `environment.systemPackages = with pkgs;`

Then, like always, as root `nixos-rebuild switch`

This is all explained in the link above.

**Comment by naturallaw777** [comment]
Upstream devs released version 16. Whoo hooo!

https://github.com/hardpixel/systemd-manager/releases/tag/v16

Here is the .nix to make it work on your local machine.

Again, this is not in the main nixpkgs repo. You will have to use this code and follow my "hack"above to get it to run in your local nix install.

Thanks again to @4JX for the original code. 


```
{ lib, stdenv, fetchzip, buildPackages }:

			stdenv.mkDerivation rec {
				pname = "systemd-manager";
				version = "16";

				src = fetchzip {
					url = "https://github.com/hardpixel/systemd-manager/releases/download/v${version}/systemd-manager-v${version}.zip";
					hash = "sha256-mbo0kSLkFpT71f/E4AJ0rMFLVtsks7u9snc8maMib4U=";
					stripRoot = false;
				};

				passthru = {
					extensionUuid = "systemd-manager@hardpixel.eu";
					extensionPortalSlug = "systemd-manager";
				};

				nativeBuildInputs = [ buildPackages.glib ];

				buildPhase = ''
					runHook preBuild
					if [ -d schemas ]; then
						glib-compile-schemas --strict schemas
					fi
					runHook postBuild
				'';

				installPhase = ''
					runHook preInstall
					mkdir -p $out/share/gnome-shell/extensions
					 cp -r -T . $out/share/gnome-shell/extensions/${passthru.extensionUuid}
					runHook postInstall
				'';

				meta = with lib; {
					description = "GNOME Shell extension to manage systemd services";
					license = licenses.gpl2Plus;
					maintainers = with maintainers; [ ];
					homepage = "https://github.com/hardpixel/systemd-manager";
				};
			}
```
