### ISSUE TITLE
Feature Request: Simplify VMware Installation

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#279697]
Feature Request: Simplify VMware Installation

I compared activating VirtualBox & VMware in NixOS:
- https://nixos.wiki/wiki/VirtualBox
- https://nixos.wiki/wiki/Virtualization#VMware_2

VirtualBox could be simply installed by adding one simple line =>
`virtualisation.virtualbox.host.enable = true;`

In order to install VMware, more steps are neede:
```
virtualisation.vmware.host.enable = true;
environment.systemPackages = [
	pkgs.linuxKernel.packages.linux_6_1.vmware
	pkgs.vmware-workstation
];
```

It would be really nice, if the kernel in use (and the needed modules) are detected automatically,
so that VMware (incl. VMware Player, Workstation & Network Editor) would simply get installed
by adding only one line to the configuration (like VirtualBox) =>

`virtualisation.vmware.host.enable = true;`

**Comment by jopejoe1** [comment]
`virtualisation.vmware.host.enable = true;` already includes vmware-workstation and the vmware module

Also updated the wiki to remove the unnecesary step

**Comment by boustanihani** [comment]
Cool, thanks :)
