### ISSUE TITLE
igir ships with prebuild 7zip that won't directly run on nixos

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#279695]
### Describe the bug
When letting igir access some 7z files it tries to execute a bundled binary

### Steps To Reproduce
1. copy a 7z file somewhere
2. run igir with --dat and --input to the path where the 7z is.
3. igir should try to extract the 7z to create the checksum of it's contents but this failes.

### Expected behavior
It should depend and use 7zip deployed through nix

### Screenshots
```
 ______   ______   ______  _______
|      \ /      \ |      \|       \
 \$$$$$$|  $$$$$$\ \$$$$$$| $$$$$$$\
  | $$  | $$|    \  | $$  | $$    $$   ROM collection manager
  | $$  | $$|    \  | $$  | $$    $$   https://igir.io/
  | $$  | $$ \$$$$  | $$  | $$$$$$$\
 _| $$_ | $$__| $$ _| $$_ | $$  | $$   v2.2.0
|   $$ \ \$$    $$|   $$ \| $$  | $$
 \$$$$$$  \$$$$$$  \$$$$$$ \$$   \$$


NOTICE: An update is available for igir: v2.2.1
✓ Scanning for DATs ·········· | 27 unique DATs found
ERROR: xyz.7z: failed to parse file: 7-zip exited with code 127
ERROR:    Could not start dynamically linked executable:
/nix/store/19yb88k8q8ymrdiky0j6dnng1knnvpl3-igir-2.2.0/lib/node_modules/igir/node_modules/7zip-bin/linux/x64/7za
ERROR:    NixOS cannot run dynamically linked executables intended for generic
ERROR:    linux environments out of the box. For more information, see:
ERROR:    https://nix.dev/permalink/stub-ld
```

### Notify maintainers
@TheBrainScrambler

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheBrainScrambler** [comment]
Thanks ! I had only tested zip files for DATs. I feared it would be hard to fix because igir would really want to use the bundled 7zip, but no, it uses the system 7zip when available, so it was easy.
