### ISSUE TITLE
cmus is broken

### ISSUE THREAD

**Issue by fread2281** [NixOS/nixpkgs#27966]
## Issue description

`pkgs.cmus` is broken.

### Steps to reproduce

`nix-build -I nixpkgs=/path/to/nixpkgs/master -E "((import <nixpkgs> {}).cmus"`

## Technical details

* System: NixOS
* Nix version: 1.11.13
* Nixpkgs version: 9d70950bfa1e70a6c544df9982f57aa5d023ec07
* Sandboxing enabled: yes

EDIT: I previously pinged Ericson2314 due to a badly done `git bisect`

**Comment by joachifm** [comment]
Can you elaborate on *how* it is broken?

**Comment by fread2281** [comment]
Building fails with

```
/nix/store/wyzy262k3qgwj1dqld41zsg0b68wmbm0-binutils-2.28/bin/ld: unrecognized option '-Wl,--export-dynamic'
/nix/store/wyzy262k3qgwj1dqld41zsg0b68wmbm0-binutils-2.28/bin/ld: use the --help option for usage information
```

**Comment by knedlsepp** [comment]
It seems a few packages broke due to a commit affecting cc-wrapper 
 (somewhere around: https://github.com/NixOS/nixpkgs/commit/3739858571e24e5f5a97a0627369826b240fb8e0 ). We might need to set CPP or LD appropriately: https://github.com/NixOS/nixpkgs/issues/27916

**Comment by Mic92** [comment]
cc @Ericson2314

**Comment by knedlsepp** [comment]
```
diff --git a/pkgs/applications/audio/cmus/default.nix b/pkgs/applications/audio/cmus/default.nix
index c934624843..ce0b005744 100644
--- a/pkgs/applications/audio/cmus/default.nix
+++ b/pkgs/applications/audio/cmus/default.nix
@@ -111,7 +111,7 @@ stdenv.mkDerivation rec {
 
   patches = [ ./option-debugging.patch ];
 
-  configurePhase = "./configure " + concatStringsSep " " ([
+  configurePhase = "LD='' ./configure " + concatStringsSep " " ([
     "prefix=$out"
     "CONFIG_WAV=y"
   ] ++ concatMap (a: a.flags) opts);
```
seems to make it compile again.

**Comment by knedlsepp** [comment]
However I only can get it to work by doing:
```
mkdir ~/.cmus; echo 'set output_plugin=alsa' > ~/.cmus/rc
```
as listed here: https://bugs.archlinux.org/task/46447

**Comment by knedlsepp** [comment]
@globin: Lightning fast. 🍻
