### ISSUE TITLE
labwc-tweaks Error opening file: No such file or directory

### ISSUE THREAD

**Issue by Ithvr** [NixOS/nixpkgs#279659]
### Describe the bug
labwc-tweaks failes to start no matter what I do
I get this error message if I try to open it in terminal: Error opening file: No such file or directory

### Steps To Reproduce
Run labwc-tweaks in the terminal

### Expected behavior
labwc-tweaks starting

### Notify maintainers
@romildo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

these 4 paths will be fetched (0.03 MiB download, 0.17 MiB unpacked):
  /nix/store/1alqjnr40dsk7cl15l5sn5y2zdxidc1v-binutils-wrapper-2.40
  /nix/store/4dr83a4wn25zkb5pvsq2y3q3v586jzs9-expand-response-params
  /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0
  /nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux
copying path '/nix/store/4dr83a4wn25zkb5pvsq2y3q3v586jzs9-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/1alqjnr40dsk7cl15l5sn5y2zdxidc1v-binutils-wrapper-2.40' from 'https://cache.nixos.org'...
copying path '/nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2596.c1be43e8e837`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ithvr** [comment]
The issue might be related to this hard coded path: https://github.com/labwc/labwc-tweaks/blob/1604f64cc62e4800ee04a6e1c323a48ee8140d83/stack-lang.c#L99

**Comment by romildo** [comment]
> The issue might be related to this hard coded path: https://github.com/labwc/labwc-tweaks/blob/1604f64cc62e4800ee04a6e1c323a48ee8140d83/stack-lang.c#L99
> 
> it seems like that xkeyboard_config provides this file

Until recently the keyboard related files was available in `/run/current-system/sw`.

Fixed in https://github.com/NixOS/nixpkgs/pull/278985
