### ISSUE TITLE
Tracking issue: ensure `strictDeps = true`

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#279658]
Among other confusing corners of Nixpkgs is that `strictDeps` attribute.

I believe we should set it to true always when possible and explain why it needed to be set as false.

However I have few to no experience on Nixpkgs internals.

**Comment by roberth** [comment]
- Duplicate of #178468

**Comment by AndersonTorres** [comment]
Good to know.
I didn't find it on search.

Closing.
