### ISSUE TITLE
Staging: Qt lconvert is broken

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#27975]
## Issue description

When building a Qt program that needs `lconvert` the following error occurs

```
/nix/store/knx5p5bj909x2cbn1gqgfmwhp5ynxiri-qttools-5.9.1-dev/bin/lconvert: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
```

### Steps to reproduce

`nix-build -A libsForQt5.kconfig`

## Technical details

- Nixpkgs staging at fdd07f62e8eb4e80b47172707ee7c8a0d7dbf428

cc @ttuegel @periklis

**Comment by globin** [comment]
Fixed on staging with 771f28bac804dfb6ebf99122bfe4e5393d9
