### ISSUE TITLE
Package request: csvlens

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#279785]
Project description: csvlens is a command line CSV file viewer. It is like less but made for CSV.

**Metadata**

* homepage URL: https://github.com/YS-L/csvlens
* source URL: https://github.com/YS-L/csvlens
* license: mit
* platforms: linux, netbsd

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
Already being worked on here: https://github.com/NixOS/nixpkgs/pull/279499

**Comment by natsukium** [comment]
introduced in #279499
