### ISSUE TITLE
amdgpu: cannot set modified EDID binaries. "Requesting EDID firmware ... failed (err=-2)"

### ISSUE THREAD

**Issue by soupglasses** [NixOS/nixpkgs#279739]
### Describe the bug
When using `drm.edid_firmware` on NixOS, amdgpu fails to find the relevant firmware file specified, even if it exists. Loading the EDID manually from `/run/current-system/firmware` works correctly.

```console
% journalctl -b0 | grep edid
Jan 09 06:05:22 desktop kernel: Command line: initrd=\efi\nixos\3r63xc80969amx1mldhh18jn39807i4r-initrd-linux-6.6.8-initrd.efi init=/nix/store/ix3vqm06g4s8s97yb2givdx0yas5zwaq-nixos-system-desktop-24.05.20240109.dirty/init drm.edid_firmware=edid/MSI-1462.bin mitigations=auto split_lock_detect=off loglevel=4
Jan 09 06:05:22 desktop kernel: Kernel command line: initrd=\efi\nixos\3r63xc80969amx1mldhh18jn39807i4r-initrd-linux-6.6.8-initrd.efi init=/nix/store/ix3vqm06g4s8s97yb2givdx0yas5zwaq-nixos-system-desktop-24.05.20240109.dirty/init drm.edid_firmware=edid/MSI-1462.bin mitigations=auto split_lock_detect=off loglevel=4
Jan 09 06:05:22 desktop kernel: amdgpu 0000:03:00.0: Direct firmware load for edid/MSI-1462.bin failed with error -2
Jan 09 06:05:22 desktop kernel: amdgpu 0000:03:00.0: [drm] *ERROR* [CONNECTOR:121:DP-2] Requesting EDID firmware "edid/MSI-1462.bin" failed (err=-2)
```

### Steps To Reproduce
NixOS configuration should have the following set somewhere:
```nix
{pkgs, lib, ...}: let
  edid-custom = pkgs.runCommandNoCC "edid-custom" {} ''
    mkdir -p $out/lib/firmware/edid
    base64 -d > "$out/lib/firmware/edid/custom.bin" <<EOF
    <insert your base64 encoded EDID file here `base64 < /sys/class/drm/card0-.../edid`>
    EOF
  '';
in {
  boot.kernelParams = ["drm.edid_firmware=edid/custom.bin"];
  hardware.firmware = [edid-custom];
}
```

My EDID file looks like this for comparison:
```
AP///////wA2aWIUAQAAABMdAQSlUCF4O44FrU8zsCYNUFSvzwCBgIGolQCVKLMAsyjR6NHAQ9Bw
oNCgKVAwIDUAHU0xAAAaAAAA/QAwZKKiAgEAAAAAAAAAAAAA/ABNU0kgTUFHMzQxQ1EKgvBwUNCg
UVAIIPgACLBBAAAaATICAxh1S5CfhZQEEwMSAQIRIwkHB4MBAAACOoDQcjgtQBAsNYAdTTEAABj+
fHCg0KApUDAgNQAdTTEAABhWXgCgoKApUDAgNQAdTTEAAB46nQCgoKApUDBANQAdTTEAAB6uYIAY
cTgtQDAsNQAdTTEAABgAAAAAAAAAAAAAAAAAEg==
```

1. Rebuild and switch configuration.
2. Reboot.
3. See edid errors in `journalctl -b0`.

### Expected behavior
Applies the EDID file correctly on boot.

Applying it manually, for example as `sudo bash -c "unxz -dc /run/current-system/firmware/edid/custom.bin.xz > /sys/kernel/debug/dri/0/DP-2/edid_override"` to apply it to DP-2 works correctly. This can work as a pseudo workaround, but requires you to disconnect and reconnect your monitor to apply the modified edid file.

### Additional context
Open Discourse about the issue: https://discourse.nixos.org/t/copying-custom-edid/31593

Attempted to look for upstream issues in amdgpu, but nothing seemed relevant. Google only shows other NixOS users having this issue that i can find.

### Notify maintainers

Unsure, @RaitoBezarius as latest editor of `stage-1.nix`.
@flokli @nazarewk may have insight as maintainers of `edid-generator.nix`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8-zen1, NixOS, 24.05 (Uakari), 24.05.20240109.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/yxld2qw84ka591fay1xkh5jflbgxjqa1-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nazarewk** [comment]
Not sure it is the same issue, but I had to resort to some ugly hacks that I had no time to get back to:
https://github.com/nazarewk-iac/nix-configs/blob/48e93a44b9cca863868294db38036d3debd980da/modules/hardware/edid/default.nix

I'm on full-amd (CPU & GPU) myself and at the end got it to work just fine eventually.

As far as I remember I had 2 issues:
1. `hardware.firmware` gets compressed by default and it cannot be loaded because of that
2. `hardware.firmware` does not make `/lib/firmware/edid` available to the `initrd`, this is most likely your issue

<details><summary>I think this is the critical part to fix point 2</summary>
<p>

```nix
    # TODO: remove this "fix" at some point?
    #   see https://github.com/NixOS/nixpkgs/blob/5e4c2ada4fcd54b99d56d7bd62f384511a7e2593/nixos/modules/system/boot/systemd/initrd.nix#L383-L385
    boot.initrd.systemd.contents."/lib/firmware".source =
      let
        # "/lib/modules".source = "${modulesClosure}/lib/modules";
        modulesClosure = lib.strings.removeSuffix "/lib/modules" config.boot.initrd.systemd.contents."/lib/modules".source;

        joined = pkgs.symlinkJoin {
          name = "kdn-initrd-firmware";
          paths = [ modulesClosure generated ];
        };
      in
      lib.mkForce "${joined}/lib/firmware";
```

</p>
</details>

**Comment by nazarewk** [comment]
thanks for motivating me to finally dig into the issue and upstream changes :)

**Comment by nazarewk** [comment]
note (for now?) you will need to add `compressFirmware = false;` to `pkgs.runCommandNoCC "edid-custom" {}` to make it work, otherwise it will compress the files

**Comment by soupglasses** [comment]
Applied https://github.com/NixOS/nixpkgs/commit/11e9e9bb70f8d09494ccbfbc7a6192bf733356ec.patch to my nixpkgs. It did not help. Also doing `compressFirmware = false;` together with it also did not help.

The `boot.initrd.systemd.contents` workaround also seems to not work, and does not even generate a new binary (likely because they are equivalent).

Running `binwalk --verbose --term --rm` against the built `-initrd.efi` only shows amdgpu and GenuineIntel being added to the initrd. Amdgpu comes from a `linux-6.6.8-modules-shrunk` which I find curious.

**Comment by soupglasses** [comment]
@nazarewk I found something interesting! While the boot fails:

```
% journalctl -b0 | grep edid
Jan 09 14:10:13 desktop kernel: Command line: initrd=\efi\nixos\00grk6kdy8rmcsga2lpl070hfg7w2s4m-initrd-linux-6.6.8-initrd.efi init=/nix/store/pkaql82r8ga0iad8048mg4c1j9qhhxs6-nixos-system-desktop-24.05.20240109.dirty/init drm.edid_firmware=edid/msi1462.bin mitigations=auto split_lock_detect=off loglevel=4
Jan 09 14:10:13 desktop kernel: Kernel command line: initrd=\efi\nixos\00grk6kdy8rmcsga2lpl070hfg7w2s4m-initrd-linux-6.6.8-initrd.efi init=/nix/store/pkaql82r8ga0iad8048mg4c1j9qhhxs6-nixos-system-desktop-24.05.20240109.dirty/init drm.edid_firmware=edid/msi1462.bin mitigations=auto split_lock_detect=off loglevel=4
Jan 09 14:10:13 desktop kernel: amdgpu 0000:03:00.0: Direct firmware load for edid/msi1462.bin failed with error -2
Jan 09 14:10:13 desktop kernel: amdgpu 0000:03:00.0: [drm] *ERROR* [CONNECTOR:121:DP-2] Requesting EDID firmware "edid/msi1462.bin" failed (err=-2)
```

Disconnecting and reconnecting the display after boot has finished does apply the custom EDID file without logging to journalctl.

**Comment by soupglasses** [comment]
https://github.com/nazarewk/nixpkgs/commit/44b70ebd07798d94130e87cc3edd948fd1f8aebe.patch

Does function correctly for me and allows it to apply without reconnecting my monitor after boot. Thank you for figuring it out! :heart:

**Comment by nazarewk** [comment]
> Disconnecting and reconnecting the display after boot has finished does apply the custom EDID file without logging to journalctl.

I am quite sure it "just works" on a live system it's available at `ls -la /run/current-system/firmware/edid/`

**Comment by nazarewk** [comment]
there is also second PR removing need to pass `compressFirmware` https://github.com/NixOS/nixpkgs/pull/279828

**Comment by soupglasses** [comment]
Here's my commit with a functional EDID loaded from initrd :tada: 
https://github.com/soupglasses/coturnix/commit/2c221654db1a30804ffd7da840d69313eb92ae76

**Comment by RaitoBezarius** [comment]
I can review PRs but I cannot help much here, apologies.
