### ISSUE TITLE
cudaPackages.cuda-samples: move out of pkgs/test

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#279703]
## Issue description

> ...`pkgs/test/cuda/*/extension.nix` are being used to extend the cudaPackages set.
> This is not great, it violates implicit Nixpkgs boundary: pkgs/test should only contain files to test the entire package set, the package set should not depend on this.
> https://github.com/NixOS/nixpkgs/pull/279684#issuecomment-1881875723

@NixOS/cuda-maintainers 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by ConnorBaker** [comment]
Closed by #280386
