### ISSUE TITLE
Package request: howdy

### ISSUE THREAD

**Issue by malkmusl** [NixOS/nixpkgs#279731]
Project description
Howdy provides Windows Hello™ style authentication for Linux. Use your built-in IR emitters and camera in combination with facial recognition to prove who you are.

Using the central authentication system (PAM), this works everywhere you would otherwise need your password: Login, lock screen, sudo, su, etc.

I've got an asus ux433 and I really like windows hello but I want to use nixos, that's why I'ld like to get this package! It is already available on arch linux and some other distros. https://wiki.archlinux.org/index.php/Howdy

Metadata

homepage URL: https://github.com/boltgolt/howdy
source URL: https://github.com/boltgolt/howdy
license: MIT
platforms: linux

**Comment by eclairevoyant** [comment]
duplicate of #76928

**Comment by malkmusl** [comment]
to complicated an deprecated

**Comment by malkmusl** [comment]
please make a offizell package
