### ISSUE TITLE
Build failure: Alacritty 0.13.0 on x86_64-darwin

### ISSUE THREAD

**Issue by arichtman** [NixOS/nixpkgs#279778]
### Steps To Reproduce

1. Build Alacritty 0.13.0 off `unstable` on `x86_64-darwin`, I had `24fe8bb4f552ad3926274d29e083b79d84707da6`

### Build log

[Nix log](https://gist.github.com/arichtman/57c6fa599be6c78b30ab9eee00a40494)

### Additional context

Thanks for all the hard work!

Commit that works for me: `63143ac2c9186be6d9da6035fa22620018c85932`

### Notify maintainers

@Br1ght0ne @Mic92 

### Metadata

```console
[user@system:~]$ nix-info -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"darwin"`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by reckenrode** [comment]
It’s failing because `NSPasteboardTypeFileURL` requires a newer SDK. Using the 11.0 SDK should fix the problem.

**Comment by happysalada** [comment]
@reckenrode thank you for the fix, implemented in https://github.com/NixOS/nixpkgs/pull/279907

**Comment by Mic92** [comment]
merged
