### ISSUE TITLE
xmonad-with-packages broken by enableSeparateDocOutput

### ISSUE THREAD

**Issue by dudebout** [NixOS/nixpkgs#27982]
## Issue description

[Separating the `doc` output in Haskell packages](https://github.com/NixOS/nixpkgs/blob/740d76371e6c1c76bae4801fc5b736a796c1ebbe/pkgs/development/haskell-modules/generic-builder.nix#L57) has broken xmonad-with-packages. [wrapper.nix](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/applications/window-managers/xmonad/wrapper.nix) is looking for the man pages of all the installed packages in the `out` output of `ghcWithPackages` but `ghcWithPackages` does not have a `share/man` subdirectory.

### Steps to reproduce

Install `xmonad-with-packages` and observe that `$out/share/man` is a dangling symlink into `ghcWithPackages`:
```
$ readlink share/man
/nix/store/2mhnagikzaild0i9fr6zyf2q1qqcjh49-ghc-8.0.2-with-packages/share/man
$ ls -L share/man
ls: cannot access 'share/man': No such file or directory
```

You might need to install it in a separate profile to avoid an error like:
```
collision between directory ‘/nix/store/c09d8sch4kxnh1sim7p5mzf3nq65xkg9-emacs-with-packages-25.2/share/man’ and non-directory ‘/nix/store/0a3ap1j8rlj4ipkcbfngxqywa7834wd0-xmonad-with-packages/share/man’ at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 57.
```

### Potential fixes

1. [The generic haskell builder](https://github.com/NixOS/nixpkgs/blob/740d76371e6c1c76bae4801fc5b736a796c1ebbe/pkgs/development/haskell-modules/generic-builder.nix) could set `outputMan` to `bin`. This would ensure that man pages are always installed alongside their binaries. 

1. `wrapper.nix` could disable the separate `doc` output for xmonad. This would ensure the man page for xmonad gets installed, but not man pages for other packages. See https://github.com/NixOS/cabal2nix/pull/290 for discussions on making sure that disabling the `doc` output does not break the postInstall script.

## Technical details

* System: Up-to-date Arch
* Nix version: 1.11.10
* Nixpkgs version: master

**Comment by peti** [comment]
Ping: @cleverca22

**Comment by dudebout** [comment]
Fix 2. is off the table: [disabling multiple outputs is not allowed for Haskell packages](https://github.com/NixOS/cabal2nix/pull/290#issuecomment-320590321).

**Comment by dudebout** [comment]
Another option is to put the `haskellPackages` man pages in their own output. Doing so will ensure that the output of the man pages does not change if haddock is turned on or off; [the default value for `enableSeparateDocOutput` is `doHaddock`](https://github.com/NixOS/nixpkgs/blob/740d76371e6c1c76bae4801fc5b736a796c1ebbe/pkgs/development/haskell-modules/generic-builder.nix#L57). If I am not mistaken, this would entail adding an `enableSeparateManOutput` flag for packages with a man page, and replicate some of the logic for `enableSeparateDocOutput`.

Once this is done, we can create the `doc` and `man` output for `ghcWithPackages` if at least one of the packages (including `ghc` itself) has a `doc or `man` output.

From there, `wrapper.nix` could use the default output to find `xmonad`, `ghc`, and `xmessages`, and the `man` output to find the `xmonad` man page.

**Comment by purefn** [comment]
Is there a work around for this? I just did a `nix-channel --update && nix-env -u` and my `xmonad-with-packages` install is running into a similar collision the OP mentioned.

```
Use of uninitialized value $stat2 in numeric ne (!=) at /nix/store/yc66k23wjs8lb3b1pr0vlray3p9vh45n-builder.pl line 74.
Use of uninitialized value $stat1 in numeric ne (!=) at /nix/store/yc66k23wjs8lb3b1pr0vlray3p9vh45n-builder.pl line 74.
collision between `/nix/store/h0p1in9zy3byvbvw3xl96p504dlmk5zy-xmonad-with-packages/share/man' and `'
```

**Comment by jpotier** [comment]
Happens to me to on NixOS too. I follow the nixos-unstable channel.

**Comment by jpotier** [comment]
Seems like it's going to take quite a long time to be fixed. We really need a workaround here. I tried building a patched version of xmonad using @dudebout 's proposed patch upstream (https://github.com/dudebout/xmonad/tree/patch-1) but it is not enough since `cabal2nix` will also need patching. Any idea for the short term?

**Comment by NeQuissimus** [comment]
I literally just built a NixOS generation from the master git repo and get no issues with XMonad:

```bash
λ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.09pre113137.1eb48d3b08"
λ cd $(dirname $(readlink -e $(type -p xmonad)))
λ pwd -P
/nix/store/jkclkf008gjdpb39lvxjl94dpcilibx9-xmonad-with-packages/bin
λ readlink ../share/man
/nix/store/b5c4blvs832jyjx383vf45xmgyn7shlp-ghc-8.0.2-with-packages/share/man
λ ls -la ../share/man
lrwxrwxrwx 77 root 31 Dec  1969 ../share/man -> /nix/store/b5c4blvs832jyjx383vf45xmgyn7shlp-ghc-8.0.2-with-packages/share/man
λ ls -la ../share/man/
dr-xr-xr-x - root 31 Dec  1969 man1
```

XMonad is part of my `configuration.nix`:

```nix
  services.xserver.windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
    extraPackages = with pkgs.haskellPackages; haskellPackages: [ xmobar ];
  };
```

**Comment by jpotier** [comment]
Funny it works from `configuration.nix` with nixpkgsVersion "17.09pre113138.96457d26dd" with your configuration. So why does it break in home-manager… I'm gonna check the home-manager sources.

**Comment by dudebout** [comment]
I do not experience the issue anymore on master. I tried to figure out what changed but was not able to do so.

**Comment by clefru** [comment]
This bug stopped being reproducible for me as well.
