### ISSUE TITLE
Package request: marimo

### ISSUE THREAD

**Issue by dmadisetti** [NixOS/nixpkgs#279873]
**Project description**

`marimo` is a reactive notebook for Python. It allows you to rapidly experiment with data and models, code with confidence in your notebook’s correctness, and productionize notebooks as pipelines or interactive web apps.

**Metadata**

* homepage URL: https://docs.marimo.io/index.html
* source URL: https://github.com/marimo-team/marimo
* license: apache
* platforms: unix, linux, darwin (agnostic, python package)
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

---
I don't think I will have time to package this soon, but I am putting it on my radar and creating the issue for other interested parties.

**Comment by TomaSajt** [comment]
Seems like a great package, but it sadly uses PNPM for its frontend.
Nixpkgs AFAIK doesn't currently have an official way of packaging apps using PNPM.
A possible solution would be to have an update-script, which always generates a `package-lock.json`, so that the usual `buildNpmPackage` builder can be used.

**Comment by dmadisetti** [comment]
I took a brief stab at it, and you are absolutely correct. PNPM seems like a pain- and this package, in particular, contains something that tries to force PNPM. I don't see a way around this until better, broader support for pnpm or changes are made upstream.

<details><summary>This is the furthest I got</summary>

      marimo-dev.frontend =
        pkgs.stdenv.mkDerivation {
          name = "marimo-dev.frontend";

          # Use source
          src = "${marimo-dev.src}/frontend";
          buildInputs = [
            pkgs.util-linux
            pkgs.nodePackages.node2nix
            pkgs.nodePackages_latest.pnpm
          ];
          postPatch = ''
            sed -i -e 's/(.*)//g' -e '7353,7360d' pnpm-lock.yaml
            sed -i -e '/"preinstall":/d' package.json
            ${pkgs.pnpm-lock-export}/bin/pnpm-lock-export
          '';
          buildPhase = ''
            node2nix -l package-lock.json
          '';
          # Installing simply means copying all files to the output directory
          installPhase = ''# Build source files and copy them over.
              mkdir -p $out/
              cp *.json $out/
              # lol and but not the flake file since the hash would have to be
              # dependent on itself.
              cp default.nix $out/
              cp node-env.nix $out/
              cp node-packages.nix $out/
          '';
        };
</details>

**Comment by dmadisetti** [comment]
Actually, noty sure what I was on about. Easily packages through just pypi (see pr). But with pnpm isn't too much more difficult. Followed what [kiwitalk did](https://github.com/NixOS/nixpkgs/blob/02fb2e43409d5922597ec990d299918bcd8e2d58/pkgs/by-name/ki/kiwitalk/package.nix#L37)

<details><summary>and works just as well</summary>

```nix
{
  description = "Marimo as a flake";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs";
  outputs = { self, nixpkgs, flake-utils }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
      };
      python.pkgs = with pkgs.python310Packages; [
        click
        jedi
        markdown
        pymdown-extensions
        pygments
        tomlkit
        uvicorn
        starlette
        websockets
        docutils
        black
      ];
      python.shell = pkgs.python310.withPackages (_: python.pkgs);
      pname = "marimo";
      version = "0.3.1";
      marimo-dev.src = pkgs.fetchFromGitHub {
        owner = "marimo-team";
        repo = pname;
        rev = version;
        sha256 = "sha256-70bMv/J0Q2IeKBAvsO0BmX1d0Mtskus3NEA6GmTp/MU=";
      };
      pnpm-deps = pkgs.stdenvNoCC.mkDerivation {
        pname = "${pname}-pnpm-deps";
        src = "${marimo-dev.src}/frontend";
        inherit version;
        nativeBuildInputs = with pkgs;[
          jq
          moreutils
          nodePackages.pnpm
          cacert
        ];
        installPhase = ''
          export HOME=$(mktemp -d)
          pnpm config set store-dir $out
          pnpm install --frozen-lockfile --ignore-script
          # Remove timestamp and sort the json files.
          rm -rf $out/v3/tmp
          for f in $(find $out -name "*.json"); do
            sed -i -E -e 's/"checkedAt":[0-9]+,//g' $f
            jq --sort-keys . $f | sponge $f
          done
        '';
        dontBuild = true;
        dontFixup = true;
        outputHashMode = "recursive";
        outputHash = {
          x86_64-linux = "sha256-ZdSxMluQBKUxZIP3dMuJEv8GSTUuQrZ18LX2F8HskFM=";
        }.${pkgs.stdenv.system} or (throw "Unsupported system: ${pkgs.stdenv.system}");
      };
    in
    {
      # A Nix environment with your specified packages
      devShell = pkgs.mkShell {
        buildInputs = [ python.shell ];
      };
      packages."${system}" = rec {
        marimo = pkgs.python310Packages.buildPythonApplication rec {
          inherit pname version;
          format = "pyproject";
          nativeBuildInputs = with pkgs.python310Packages; [
            setuptools
            pkgs.util-linux
            pkgs.nodePackages.pnpm
          ];
          propagatedBuildInputs = python.pkgs;
          preBuild = ''
            export HOME=$(mktemp -d)
            cd frontend
            pnpm config set store-dir ${pnpm-deps}
            pnpm install --offline --frozen-lockfile --ignore-script
            pnpm build
            mkdir -p ../marimo/_lsp/
            cp -R dist/* ../marimo/_lsp/
            mkdir -p ../marimo/_static/
            cp -R dist/* ../marimo/_static/
            cd ..
          '';
          src = marimo-dev.src;
        };
        default = marimo;
      };
    };
}
```
</details>
