### ISSUE TITLE
17.03: pythonPackages.bcrypt missing dependency six

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#27992]
## Issue description
~~The libraries included on the python path generated by python.withPackages should be the closure on the libraries' propagatedBuildInputs. This is not currently the case.~~

### Steps to reproduce

```
$ nix-shell -p 'python.withPackages (ps: [ps.bcrypt])' --run 'python -c "import bcrypt"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/rwyrm4fj08m8wfb9hns8rjd3n3wfvq1i-python-2.7.13-env/lib/python2.7/site-packages/bcrypt/__init__.py", line 22, in <module>
    import six
ImportError: No module named six
```

~~Note how bcrypt does have six in its propagatedBuildInputs.~~

## Technical details

- System: 17.03.1645.08bc48049c (Gorilla)
- Nix version: nix-env (Nix) 1.11.13
- Nixpkgs version: "17.03.1645.08bc48049c"
- Sandboxing enabled: true

**Comment by lheckemann** [comment]
This appears to be fixed on master.

**Comment by lheckemann** [comment]
Update, I seem to have misread some things. Turns out this is actually an issue in bcrypt's packaging which is fixed by 669f5819e20a4d21b6054b64e079ac2a555d4b1c. Can we backport that?

**Comment by FRidh** [comment]
Done!
c40b85d4fd06613150cd665d22a4e98448662b2d

**Comment by lheckemann** [comment]
Thanks!
