### ISSUE TITLE
Update request: gdb 13.2 → 14.1

### ISSUE THREAD

**Issue by siph** [NixOS/nixpkgs#279912]
- Package name: gdb
- Latest released version: 14.1

- Current version on the unstable channel: 13.2
- Current version on the stable/release channel: 13.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@pierron @globin @lsix

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
https://github.com/NixOS/nixpkgs/pull/271940

**Comment by siph** [comment]
oops, I only checked open prs and nixpkgs.

Here is a tracker if anyone lands here from a search: https://nixpk.gs/pr-tracker.html?pr=271940
