### ISSUE TITLE
Package request: tmux-fingers

### ISSUE THREAD

**Issue by WilliamHsieh** [NixOS/nixpkgs#279999]
**Project description**
copy pasting in terminal with vimium/vimperator like hints.

**Metadata**

* homepage URL: https://github.com/Morantron/tmux-fingers
* source URL: https://github.com/Morantron/tmux-fingers
* license: mit
* platforms: unix

**Additional information**
Tmux-thumb is available, but it has certain acknowledged issues, as indicated in https://github.com/fcsonline/tmux-thumbs/issues/76. 
In comparison, the original tmux-finger proves to be more reliable for my needs.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ppom0** [comment]
It's already packaged and available at `tmuxPlugins.fingers`. You can also take a loot at `tmuxPlugins.tmux-thumbs` which seems like a faster rewrite.

All tmux plugins are defined here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/tmux-plugins/default.nix

You can also search them with this command: `nix search nixpkgs tmuxPlugins`

To enable tmux plugins on NixOS, you'll have to use this NixOS option (adding them to `environment.systemPackages` is not enough), taking tmux-fingers as an example:
```nix
programs.tmux.plugins = [ pkgs.tmuxPlugins.fingers ];
```
See `man configuration.nix` and search for `tmux` (by typing `/tmux<enter>`) to see all tmux options.

**Comment by WilliamHsieh** [comment]
> You can also take a look at tmuxPlugins.tmux-thumbs which seems like a faster rewrite.

As mentioned in the additional information, `tmux-thumbs` has some known issues and is therefore unusable for me.

> It's already packaged and available at tmuxPlugins.fingers.

There's a 2.0 version rewrite with crystal for fingers and not yet updated, is PR acceptable for this kind of update?
