### ISSUE TITLE
cups and SANE backend for samsung printer/scanner m2070w

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#27995]
<pre>
Hi,

I have now m2070w samsung printer/scanner working on nixos but not in
a packageable way.

Any ideas, what would be the best (or easiest way to package it)?

I had to:

1) install samsung-unified-linux-driver-1.00.36 based on the default
   samsung-unified-linux-driver-1.00.37 and modify a few things:

   perl -pi -e 's|/opt|/etc|g' noarch/package_utils
   perl -pi -e 's|/opt|/etc|g' noarch/pre_install.sh
   perl -pi -e 's|/opt|/etc|g' $out/lib/sane/libsane-smfp.so.1.0.1
   perl -pi -e 's|/opt|/etc|g' $out/bin/rastertospl
   # not sure if the following substitution is needed:
   perl -pi -e 's|read_config:opt|read_config:etc|g' \
     $out/lib/sane/libsane-smfp.so.1.0.1

   mkdir -p $out/share/${name}
   cp \
     noarch/oem.conf \
     noarch/libsane-smfp.cfg \
     noarch/pagesize.xml \
     noarch/etc/smfp.conf \
     $out/share/${name}

2) add the following files to /etc:

  environment.etc = {
    "samsung/scanner/share/oem.conf".source
      = "${m2070w}/share/${m2070w.name}/oem.conf";
    "smfp-common/scanner/share/libsane-smfp.cfg".source
      = "${m2070w}/share/${m2070w.name}/libsane-smfp.cfg";
    "smfp-common/scanner/share/pagesize.xml".source
      = "${m2070w}/share/${m2070w.name}/pagesize.xml";
    "sane.d/smfp.conf".source
      = "${m2070w}/share/${m2070w.name}/smfp.conf";
  };

3) I wasn't completely succesful with replacing /opt with /etc.
   Somehow, the samsung driver still insisted on two things in /opt:

   sudo mkdir -p /opt/smfp-common/scanner/share/
   sudo ln -s /etc/smfp-common/scanner/share/libsane-smfp.cfg \
     /opt/smfp-common/scanner/share/libsane-smfp.cfg
   sudo mkdir -p /opt/smfp-common/scanner/.usedby/

This command helped with finding out, what was wrong with the backend:

   SANE_DEBUG_DLL=255 strace scanimage -L >/tmp/sane.log 2>&1

What needs to be done, the difficult part:

   Ad 3) ist really problem.  I might spend more time trying to find
   out how to convince the driver to look into /etc but I am not too
   optimistic about this avenue.

   There is a different backend, which solves similar problem in
   sane/backends/brscan4/preload.c, but it uses LD_PRELOAD for an
   executable, which I don't know how to achieve for a dynamic library
   loaded by sane.

   One option would be to write a proxy sane backend, which would
   LD_PRELOAD and exec an proxy executable which would then load the
   dynamic library from the driver.  This sounds rather complex.

   Is there an easier solution to this, somehow faking the /opt for
   the sane backend?

Once the /opt problem is solved, packaging it might not be such a
problem.

Any ideas how to approach this?

It might be also worth trying to create a single samsung backend which
would handle all printer/scanner versions without users having to
worry about which driver version works with their device.

Tomas
<pre>

**Comment by pasqui23** [comment]
According to http://www.bchemnet.com/suldr/forum/index.php?topic=260.0 the problem is libsane-smfp.so.1.0.1 needing /opt/samsung/scanner/share/oem.conf in the exact path

**Comment by pasqui23** [comment]
@tohl @FRidh what is `name` and `m2070w` in the above code?

**Comment by tohl** [comment]
@pasqui23 I have the scanner working except one issue: I can scan one
page with simple scan but when I try to scan again, it doesn't work and
I have to restart the scanner, iirc.  This is a shame as the old scanner
is taking precious space on my desk.  I will try to send the changes if
I find time.  Maybe somebody comes with an idea, what the problem is.

**Comment by tohl** [comment]
pasqui23 <notifications@github.com> writes:
> According to http://www.bchemnet.com/suldr/forum/index.php?topic=260.0
> the problem is libsane-smfp.so.1.0.1 needing
> /opt/samsung/scanner/share/oem.conf in the exact path

i have replaced /opt with /etc and defined used module with
environment.etc with link to the expected files

this works but requires nixos module

is there a way to specify directly in package, which /etc files and
directories should be installed together with the package, without
having to use nixos module just for environment.etc?

**Comment by tohl** [comment]
this pull-request <https://github.com/NixOS/nixpkgs/pull/57449> fixes
this issue (and also <https://github.com/NixOS/nixpkgs/issues/33579>)
