### ISSUE TITLE
swayosd: New version isn't backwards compatible and doesn't work out of the box

### ISSUE THREAD

**Issue by augustebaum** [NixOS/nixpkgs#280041]
> Hi, this update broke my setup (presumably because of the change to `swayosd-{server,client}`). Does any of you have a working setup going that I could use to fix mine? I'm not sure where to ask this so please let me know if some other place would be better suited.

_Originally posted by @augustebaum in https://github.com/NixOS/nixpkgs/issues/263357#issuecomment-1880566785_

**Comment by eclairevoyant** [comment]
Per the PR description:

> swayosd-server should be launched and use 'swayosd-client' instead of 'swayosd'

**Comment by barab-i** [comment]
to start server:
```
swayosd-server &
```

binding example for sway:
```
bindsym XF86AudioRaiseVolume exec swayosd-client --output-volume raise
```
[More info](https://github.com/ErikReider/SwayOSD#usage)

**Comment by augustebaum** [comment]
Thanks for the quick response; this is what I get when I try this out:

```console
~
❯ swayosd-server
SwayOSD LibInput Backend isn't available, waiting...
```
so I tried this:
```console
~
❯ swayosd-libinput-backend
Error: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.2415" is not allowed to own the service "org.erikreider.swayosd" due to security policies in the configuration file
```

What am I missing?

**Comment by BeathanEda** [comment]
Hi, I have the same issue. Have not found a solution yet. @augustebaum have you found any new information?

**Comment by barab-i** [comment]
> ```
>~
>❯ swayosd-server
>SwayOSD LibInput Backend isn't available, waiting...
>```

Well, it is not an error message at all; you can ignore it. swayosd-libinput-backend automatically detects caps lock, num lock and scroll lock. I'm not sure how to make it work, but libinput backend wasn't working in the 2023-07-18 version either, and it is not necessary.
``` bash
# Capslock (If you don't want to use the backend)
bindsym --release Caps_Lock exec swayosd-client --caps-lock
```

**Comment by augustebaum** [comment]
Indeed you're right, running `exec swayosd-server` does start the server and after that running `swayosd-client --output-volume=raise` works. Thanks very much!

To recap, this is what changed in my sway config.nix:
```nix
{pkgs, ...}: let
  swayosd = lib.getExe' pkgs.swayosd "swayosd-client";
in {
  ...

  config = {
    startup = [
      ...
      {command = lib.getExe' pkgs.swayosd "swayosd-server";}
    ];

    keybindings = {
      "XF86AudioRaiseVolume" = "exec ${swayosd} --output-volume raise";
      "XF86AudioLowerVolume" = "exec ${swayosd} --output-volume lower";
      "XF86AudioMute" = "exec ${swayosd} --output-volume mute-toggle";
    };
  };
}
```

**Comment by leon-erd** [comment]
@BeathanEda @augustebaum I think getting `swayosd-libinput-backend` to work would be quite handy. I have found some related issues in the swayosd github. According to the maintainer one needs to run `meson setup` with `--prefix /usr` before building (see [https://github.com/ErikReider/SwayOSD/discussions/30](https://github.com/ErikReider/SwayOSD/discussions/30). However, I am not sure how to incorporate this in the mkDerivation as I am fairly new to nix.

Also for me the udev rules were not set and I had to manually run `sudo chgrp video /sys/class/backlight/intel_backlight/brightness` and `sudo chmod g+w /sys/class/backlight/intel_backlight/brightness` to get the brightness control working.

**Comment by barab-i** [comment]
I don't know why but installing swayosd as a system package solved the error with the `swayosd-libinput-backend`.
```nix
# configuration.nix
environment.systemPackages = with pkgs; [
  ...
  swayosd
];
```

```bash
# to start
pkexec swayosd-libinput-backend
```
It doesn't look like a proper solution, but it works.

As for udev rules, the package contains udev rules in `<<pkg>>/lib/udev/` so that should work:
```nix
# configuration.nix
services.udev.packages = [ pkgs.swayosd ];
```

**Comment by leon-erd** [comment]
You are right! I can confirm that the above works :)
But why is it only possible to run the libinput-backend with elevated privileges..?
And it is quite an unconvenient workaround as I would usually not put this in my nix configuration but in the home configuration instead..

**Comment by haras-unicorn** [comment]
For anyone running into this issue - for me the fix was adding this in my nixos configuration

```nix
    environment.systemPackages = [ pkgs.swayosd ];
    services.udev.packages = [ pkgs.swayosd ];

    systemd.services.swayosd-libinput-backend = {
      description = "SwayOSD LibInput backend for listening to certain keys like CapsLock, ScrollLock, VolumeUp, etc.";
      documentation = [ "https://github.com/ErikReider/SwayOSD" ];
      wantedBy = [ "graphical.target" ];
      partOf = [ "graphical.target" ];
      after = [ "graphical.target" ];

      serviceConfig = {
        Type = "dbus";
        BusName = "org.erikreider.swayosd";
        ExecStart = "${pkgs.swayosd}/bin/swayosd-libinput-backend";
        Restart = "on-failure";
      };
    };
```

now im getting nice ui about caps lock num lock and all the various locks on my screen :)

i found this file in the result of the swayosd package - maybe there should be a nixos module for swayosd-libinput-backend service?

**Comment by jjramsey** [comment]
Thanks for the solution, but what do you mean by "i found this file in the result of the swayosd package"?

**Comment by haras-unicorn** [comment]
tbh im not sure anymore 😅
