### ISSUE TITLE
`python3Packages.polars` version should be 0.20.0 but hash points to a different version

### ISSUE THREAD

**Issue by augustebaum** [NixOS/nixpkgs#280031]
### Describe the bug

Running `polars.show_versions()` shows a version that is different from the one in the Nix store file name.

### Steps To Reproduce
Run
```py
#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p python3Packages.polars
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4f4420dfc3a09f3f01ca3edf94fa349cd8bf7335.tar.gz

import polars

print(polars)
polars.show_versions()
```

The output will look something like:
```
<module 'polars' from '/nix/store/fbp5rpkgj6kbpc078ndwzmkvyyfvrs7h-python3.11-polars-0.20.0/lib/python3.11/site-packages/polars/__init__.py'>
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-6.1.64-x86_64-with-glibc2.38
Python:              3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0]

----Optional dependencies----
...
```

Notice the store path says `polars-0.20.0` while the `polars.show_versions()` command show that the version is actually 0.19.12.

### Expected behavior

The two versions match.

### Additional context

I ran into this because I tried to use `polars.Expr.replace()` and got the error "has no attribute 'replace'":

```py
df = pl.DataFrame({"a": [1, 2, 2, 3]})
df.with_columns(pl.col("a").replace({2: 100}).alias("replaced"))
*** AttributeError: 'Expr' object has no attribute 'replace'
```

According to https://github.com/pola-rs/polars/issues/12695 this part of the API was released at least in version 0.19.16, so it would confirm that the version I have installed is in fact 0.19.12.

### Notify maintainers

@happysalada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 24.05 (Uakari), 24.05.20240102.bd645e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
https://github.com/NixOS/nixpkgs/pull/275150 only updated the version and not the hash.

**Comment by augustebaum** [comment]
Thanks, well spotted! @fabaff @happysalada when I merely update the hash I end up with this error:
```
...
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/py-polars/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
/nix/store/f3g84l92p0njh0gyk1z7cp2k4qnh91ha-diffutils-3.10/bin/diff: /build/source/py-polars/Cargo.lock: No such file or directory
ERROR: Missing Cargo.lock from src. Expected to find it at: /build/source/py-polars/Cargo.lock
Hint: You can use the cargoPatches attribute to add a Cargo.lock manually to the build.
```

**Comment by happysalada** [comment]
hey, after having had just a quick look, I've opened https://github.com/NixOS/nixpkgs/pull/280132
I haven't tested though, could you help with testing and let me know if that works ?

**Comment by happysalada** [comment]
ah, I've just had a compilation failure. This is because the maturin used currently is 1.3.0 and polars requires 1.3.2.
the bump is also going to require a maturin bump.
Are you interested in taking care of it ? Otherwise I should be able to make some time at some point.

**Comment by augustebaum** [comment]
Thanks for this! I might try it out in the next few days :)

**Comment by happysalada** [comment]
alright, I've tried with maturin 1.3.2, but I still get a rust compilation failure. I've checked their MSRV and it's only 1.71. 
So I don't know what could be causing this compilation failure.
if you have any ideas, feel free to re-use anything from that PR without any need for attribution. I'll be happy to help merge a solution.

**Comment by a-n-n-a-l-e-e** [comment]
might be worth setting the version back to `0.19.12` in the meantime so the package will build on a cache miss.

**Comment by happysalada** [comment]
so version has been set back to 0.19.12.
I have finally had some luck in compiling the latest polars version in https://github.com/NixOS/nixpkgs/pull/280132
if anyone is interested to test the PR, feel free to post a comment. 
I'm running a nixpkgs-review to check what the update breaks
