### ISSUE TITLE
gitlab-db-config service fails, wrong database.yml layout

### ISSUE THREAD

**Issue by emhamm** [NixOS/nixpkgs#280004]
### Describe the bug
after applying the latest update for gitlab from the 23.11-release channel gitlab can not be started. 
```
gitlab-db-config[4076162]: ERROR: This installation of GitLab uses unsupported 'config/database.yml'. The `main:` database needs to be defined as a first configuration item instead of `ci`
```
### Steps To Reproduce
1. Have a running gitlab instance running on NixOS 23.11-release
2. Apply commit 9f9b8ec1d996841ba442db6e5f324dad0f3a6c6c
3. see gitlab-db-config error `ERROR: This installation of GitLab uses unsupported 'config/database.yml'`

### Expected behavior
gitlab succeeds to start

### Screenshots
None

### Notify maintainers
@yayayayaka 
@tomsiewert 

### Metadata
working state
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71, NixOS, 23.11 (Tapir)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(user): `"nixpkgs"`
 - channels(root): `"nixos-20.09.4407.1c1f5649bb9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tomsiewert** [comment]
How's your service config looking like? I guess you don't use `databasePasswordFile`?

**Comment by emhamm** [comment]
You are right, `databasePasswordFile` is not used in this instance.

it boils down to:

```nix
services.gitlab = {
    enable = true;
    initialRootPasswordFile = "path/to/file;
    host = "FQND";
    user = "user";
    group = "user";
    databaseUsername = "user";
    databaseName = "name";

     secrets = {
      dbFile = "path/to/file
      secretFile = "path/to/file";
      otpFile = "path/to/file";
      jwsFile = "path/to/file";
    };
};
```

**Comment by tomsiewert** [comment]
It's wild that this isn't covered by the NixOS tests 🙈 I'll propose a fix for this. Thanks for reporting!

**Comment by emhamm** [comment]
thanks for fixing :+1:

**Comment by tomsiewert** [comment]
@emhamm I have pushed a fix. Could you please to test it if it works for you now? I don't have a working test env rn to check it properly 🙈

**Comment by emhamm** [comment]
@tomsiewert tested! It works :rocket:

**Comment by tomsiewert** [comment]
Awesome! Could you please add your feedback to my PR and maybe give a thumbs-up? That way the PR may get faster attention to NixOS maintainers allowed to merge to master.
