### ISSUE TITLE
Bad gtk theme on Xfce4

### ISSUE THREAD

**Issue by myugan** [NixOS/nixpkgs#28000]
## Issue description

![badgtk](https://user-images.githubusercontent.com/20453528/29008786-c6143e00-7b46-11e7-8311-2f16849d5498.png)

i will change default xfce4 theme to Arc but the theme is bad, how to fix it?

## Technical details

* System: 17.03.1645.08bc48049c (Gorilla)
* Nix version: 1.11.13
* Nixpkgs version: 17.03.1645.08bc48049c"
* Sandboxing enabled: false

**Comment by emmanuelrosa** [comment]
See if this works: https://www.youtube.com/watch?v=dTC4vfDu5bs
