### ISSUE TITLE
emacs hyperbole package native compilation error

### ISSUE THREAD

**Issue by ParetoOptimalDev** [NixOS/nixpkgs#280169]
### Describe the bug

When calling `hyperbole-demo` with the hyperbole package installed you'll get warnings:

```
⛔ Warning (comp): /nix/store/sgw107kd1hdw3s3xa5s0ly53bk6cdwvf-emacs-packages-deps/share/emacs/site-lisp/elpa/hyperbole-8.0.0/hui-em-but.el: Error: Symbol's function definition is void var:append
⛔ Warning (comp): /nix/store/sgw107kd1hdw3s3xa5s0ly53bk6cdwvf-emacs-packages-deps/share/emacs/site-lisp/elpa/hyperbole-8.0.0/hbdata.el: Error: Symbol's value as variable is void hyperb:microsoft-os-p
⛔ Warning (comp): /nix/store/sgw107kd1hdw3s3xa5s0ly53bk6cdwvf-emacs-packages-deps/share/emacs/site-lisp/elpa/hyperbole-8.0.0/hbut.el: Error: Symbol's function definition is void var:append
```

I believe it's also responsible for other things I try from the demo like when I try koutliner's example I get:

```
error: (void-function kcell:ref-to-id)
```

This is because of a known error [per the author](https://old.reddit.com/r/emacs/comments/ugbhrr/gnu_hyperbole_800_the_epiphany_release_is_now/irjdj1u/).
The fix is:

> Simply replace the Makefile 'eln' target with the text between the ----- lines:

```
--------

# Create -l "file.el" load-file command-line args for each Hyperbole .el file for use in
# eln native compile target below.
LOAD_EL = $(shell echo "$(EL_KOTL) $(EL_COMPILE)" | sed - -e 's+ +" -l "./+g' -e 's+^+-l "+')"
load-hyperbole:
$(EMACS_BATCH) \
$(LOAD_EL)
eln: src
$(EMACS_BATCH) \
$(LOAD_EL) \
--eval="(setq-default byte-compile-warnings '(not docstrings))" \
-f batch-native-compile $(EL_KOTL) $(EL_COMPILE)
----------
```

> Save the Makefile and then in a bash-like shell, type 'make eln' to natively compile it.

I'm not sure how to apply this fix to the hyperbole emacs package in nixpkgs however. 

### Steps To Reproduce
1. install emacs with hyperbole
2. call `M-x hyperbole-demo`
3. see errors like `Error: Symbol's function definition is void var:append`

### Expected behavior

Steps 1, 2, but not 3.

### Additional context
I use emacs 30 via emacs-overlay, however this bug affects any emacs with native compilation.

### Notify maintainers

Not sure, but these are names on maintainers for melpa/elpa:

@DamienCassou @sternenseemann 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jian-lin** [comment]
Quoting the package author

> We fixed this native compilation problem a god while back in the pre-release master tip of Hyperbole but have not yet made a new release.

Since we have 9.0.1 and newer version in Nixpkgs, this issue is presumably not relevant any more.  Let's close this.
