### ISSUE TITLE
`vkcube` does not exist on MacOS

### ISSUE THREAD

**Issue by DUOLabs333** [NixOS/nixpkgs#280180]
## Issue description
Exactly what it says in the title --- `vkcube` and `vkcubepp` both do not exist on MacOS

## Technical details
```
- system: `"aarch64-darwin"`
 - host os: `Darwin 20.4.0, macOS 11.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/g16z4fs1mrbkxc4x6wm8xbrh13nc7aw4-source`
```

**Comment by wegank** [comment]
This seems to be intentional, as there is no open-source equivalent of `ibtool`. See also #45634.

https://github.com/NixOS/nixpkgs/blob/65f2493611298b2349c51221e597f507b456f0d6/pkgs/tools/graphics/vulkan-tools/default.nix#L87-L91

**Comment by DUOLabs333** [comment]
Ah, I only looked at `https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/tools/graphics/vulkan-tools/default.nix`, as I thought I was looking at `master`, not an old branch.
