### ISSUE TITLE
Evaluation error in searx

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#28015]
Something isn't right about `searx`:

~~~
$ nix-env -qaP --json >/dev/null
derivation ‘searx-0.12.0’ has invalid meta attribute ‘override’
derivation ‘searx-0.12.0’ has invalid meta attribute ‘overrideDerivation’
~~~

This happens in f152749c9940cda448153aa4d36dcaea538af8b1 (and earlier).

Ping: @matejc @fpletz @profpatsch

**Comment by peti** [comment]
git bisect says that c217f48c358db05bd0ad7893e8e3ebabe4784cbe by @fpletz is the first bad commit.

**Comment by fpletz** [comment]
Weird. Does anybody know what's going on here? It's not even a fatal error and searx builds fine.

**Comment by Profpatsch** [comment]
You moved it from the `python_packages` could that be the reason?

**Comment by fpletz** [comment]
Lots of python packages that aren't modules like services or tools have already been moved out of `python-packages.nix`. Those derivations don't have this problem even though their code is similar to seax.

@FRidh Do you have an idea?

**Comment by FRidh** [comment]
c217f48c358db05bd0ad7893e8e3ebabe4784cbe is using `callPackages` instead of `callPackage`

**Comment by Profpatsch** [comment]
Aww, good catch!
