### ISSUE TITLE
Update request: linuxKernel.kernels.linux_zen 6.6.10 → 6.7

### ISSUE THREAD

**Issue by deviantsemicolon** [NixOS/nixpkgs#280127]
- Package name: linuxKernel.kernels.linux_zen
- Latest released version: 6.7

- Current version on the unstable channel: 6.6.10
- Current version on the stable/release channel: 6.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@thiagokokada @JerrySM64 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JerrySM64** [comment]
Merged as of #279946.

**Comment by deviantsemicolon** [comment]
> Merged as of #279946. I'm watching the zen-kernel repo so when there's a new update, I do it as fast as I can. 😄

oh i didn't see that when looking at the pull requests. sorry about that. thank you
