### ISSUE TITLE
Subsonic has gone closed-source. We should replace it with a maintained, free fork

### ISSUE THREAD

**Issue by therealpxc** [NixOS/nixpkgs#28014]
## Issue description
Subsonic has [closed down its source code](http://forum.subsonic.org/forum/viewtopic.php?f=4&t=16604#p71128), following the 6.0 release. We should switch to a free fork instead.

[Libresonic](https://github.com/Libresonic/libresonic) is one such free fork and [Airsonic](https://github.com/airsonic/airsonic) is another.

**Comment by disassembler** [comment]
@therealpxc Would you be able to test the above PR? I was able to run the service and it was listening on 4040 after setting `services.airsonic.enable =true;`.

**Comment by therealpxc** [comment]
I will set it up on my multimedia machine when I get home, and test streaming with it for a few days to my work machine and phone.

PS: I mostly filed this issue to remind myself to get to it eventually (which may have been a long time). So thanks for jumping in and fully revealing my laziness! :-D

**Comment by Taeradan** [comment]
I have been using airsonic on nixos-unstable for about a week now and it works without trouble. Shouldn't we close the issue ?
