### ISSUE TITLE
Getting a dead link on faac

### ISSUE THREAD

**Issue by kiloreux** [NixOS/nixpkgs#28028]
## Issue description
I can't download `faac` (trying to compile ffmpeg) because I get the following error 

"curl: (22) The requested URL returned error: 404 
error: cannot download faac-mp4v2-1.9.patch from any mirror"

The concerned link is 

https://git.archlinux.org/svntogit/packages.git/plain/trunk/mp4v2-1.9.patch?h=packages/faac

**Comment by rycee** [comment]
@kiloreux This should be fixed now and will, with any luck, show up in the next channel update. Thanks for the report!
