### ISSUE TITLE
sudo-rs: sudo must be owned by uid 0 and have the setuid bit set

### ISSUE THREAD

**Issue by alsvartr** [NixOS/nixpkgs#280281]
### Describe the bug
Hi! I’m trying to switch to new sudo-rs, but unfortunately have this error:
`sudo-rs: sudo must be owned by uid 0 and have the setuid bit set`

### Steps To Reproduce
```
  security.sudo-rs = {
    enable = true;
    execWheelOnly = false;
  };
```

### Additional context
```
which sudo
/run/wrappers/bin/sudo

ll /run/wrappers/bin/sudo                                                                                                                                                                      
-r-s--x--x 1 root root 63432 Dec 31 13:16 /run/wrappers/bin/sudo

echo $PATH
/run/wrappers/bin:/home/alsvartr/.nix-profile/bin:/nix/profile/bin:/home/alsvartr/.local/state/nix/profile/bin:/etc/profiles/per-user/alsvartr/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```

@nbraud @kirillrdy

**Comment by chewblacka** [comment]
Did you remember to add  `security sudo enable = false;` to your config?

**Comment by alsvartr** [comment]
> Did you remember to add `security sudo enable = false;` to your config?

It didn't help
```
  security.sudo.enable = false;
  security.sudo-rs = {
    enable = true;
    execWheelOnly = false;
  };
```

**Comment by chewblacka** [comment]
Are you using `sudo nixos-rebuild switch` ? 
If so try using `sudo nixos-rebuild boot`.

**Comment by alsvartr** [comment]
> Are you using `sudo nixos-rebuild switch` ? If so try using `sudo nixos-rebuild boot`.

Tried with no luck

**Comment by chewblacka** [comment]
> Tried with no luck

Ok. check you don't have `sudo` in your packages, and check that you don't have any other references to `sudo` in your config. If that doesn't work hopefully someone else can chime in.

**Comment by alsvartr** [comment]
You're right, I had security.sudo.extraRules. Maybe it's a little unclear that you need to remove all occurrences of sudo.

**Comment by b2ag** [comment]
Somewhat unrelated but as search results lead me here, so I'll drop a hint for future me and others. I had a service running as DynamicUser in systemd which produced an error like this.
