### ISSUE TITLE
`tests.cuda` fails to evaluate: "Function called without required argument "backendStdenv"

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#280377]
### Describe the bug

Noticed the test evaluation failure when explored `nixpkgs` attributes for obvious instantiation mistakes.

The reproducer:

```
$ nix-instantiate '<nixpkgs>' -A tests.cuda
error:
       … while calling the 'abort' builtin

         at lib/customisation.nix:210:13:

          209|        # which is especially relevant with allowAliases = false
          210|        else abort "lib.customisation.callPackageWith: ${error}";
             |             ^
          211|

       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "backendStdenv" at pkgs/test/cuda/cuda-library-samples/generic.nix:3'
```

### Expected behavior

The test set should instantiate successfully.

### Notify maintainers

@ConnorBaker  @samuela @SomeoneSerge 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.10, NixOS, 24.05 (Uakari), 24.05.20240111.be34eb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `""`
 - channels(slyfox): `""`
 - nixpkgs: `/run/current-system/sw/share/nixos-flakes/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
Oh, again, CC https://github.com/NixOS/nixpkgs/pull/279684 @NixOS/cuda-maintainers

**Comment by SomeoneSerge** [comment]
https://github.com/NixOS/nixpkgs/pull/280386
