### ISSUE TITLE
ati_unfree not working with Asus R9 280X

### ISSUE THREAD

**Issue by third3ye** [NixOS/nixpkgs#2803]
The Asus R9 280X is similar to the reference cards, with two distinct differences. The DirectCU II cooling solution and the DigiVRM power management system. I can run my box using videoDrivers = [ "ati" ], which for some reason loads fglrx (isn't it supposed to load glamoregl?) If I however try to boot using videoDrivers = [ "ati_unfree" ] the screen freezes once the greeter is being loaded. The journal does has some kernel failures that I am incapable of interpreting.

I'm not sure, but the proprietary drivers might be loaded with the ati drivers (rather than ati_unfree). However, this is refuted by the constant screen tearing I see when doing something so mundane as scrolling a web-page. That is NOT supposed to happen with the proprietary drivers, so I'm guessing that NixOS loads glamouregl as fglrx? Again: I have no idea.

journalctl log:
https://gist.github.com/third3ye/a7c9beaa75673c7b8d37

**Comment by domenkozar** [comment]
Could you test #13535 and report problems there? Thanks!
