### ISSUE TITLE
Bad permissions on /tmp in disk images we build

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#28055]
Say I build an image on master (b48ffa332bb9814a04a766072f25e08c3f5abe44) with the following configuration:

```nix
{ pkgs, lib, modulesPath, config, ... }:

{
  imports = [ "${modulesPath}/profiles/minimal.nix" ];
  environment.systemPackages = lib.mkForce [];

  fileSystems."/" = {
    device     = "/dev/disk/by-label/nixos";
    autoResize = true;
  };

  boot.loader.grub.device = "/dev/sda";

  system.build.image = import "${pkgs.path}/nixos/lib/make-disk-image.nix" {
    name = "test";
    inherit pkgs lib config;
    partitioned = true;
    diskSize = 1024;   
  };
}
```

And build it as follows:

```
$ nix-build $PATH_TO_NIXPKGS/nixos -A config.system.build.image --argstr configuration $PWD/configuration.nix
```

The `/tmp` on that image will have permissions as follows:

```
drwxr-xr-t  3 root root  4096 Aug  9 02:27 tmp
```

(instead of 0777)

This may well be my fault from all the image reshuffling stuff I did. I'll look into it and fix before 17.09, unless someone else gets to it before I do.

Might also be related to https://github.com/NixOS/nixpkgs/issues/22413

**Comment by copumpkin** [comment]
Looks like the culprit is `cptofs` in LKL. I opened an issue there (https://github.com/lkl/linux/issues/364) and will see what they say, or fix it myself if nobody bites.

**Comment by dezgeg** [comment]
`nixos/modules/system/boot/stage-2-init.sh` already attempts to correct the situation:
````
mkdir -m 01777 -p /tmp
````

among other stuff. But IIRC mkdir doesn't change the permissions if the directory already exists (sigh).

**Comment by copumpkin** [comment]
Makes sense. LKL just merged the upstream fix so I'll just bump that package and this should be fixed.

**Comment by copumpkin** [comment]
See https://github.com/NixOS/nixpkgs/commit/ed55bdb50103bfc22abff15389d7634c268d499c
