### ISSUE TITLE
Plymouth makes system unable to boot after garbage collection

### ISSUE THREAD

**Issue by marvix97** [NixOS/nixpkgs#280505]
**Describe the bug**

When plymouth is enabled, running `nix store gc --debug` or  `nix-garbage-collection`

makes every generation with it enabled unable to boot, with a black screen after Stage 1. 

Booting a generation without it, or disabling it by removing "splash" from cmdline, works and makes the system boot. 

Also, reinstalling the system makes plymouth work again, until the next garbage collection.

Unfortunately, I have no logs to provide, since I can't see them, if any.

**Steps To Reproduce**

1. NixOS installed with **`boot.plymouth.enable = true`**

2. Run `nix store gc --debug`
3. Reboot
4. Black screen after stage 1

**Expected behavior**

The system boots with the splash screen

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Comment by hughesjs** [comment]
Plymouth also seems broken for me on a fresh install
