### ISSUE TITLE
[jupyter-notebook] regression: command mode keyboard shortcuts broke with jupyterlab-4.0.7

### ISSUE THREAD

**Issue by pwaller** [NixOS/nixpkgs#280539]
### Describe the bug

When in command mode, usually you can do things like move up and down cells with up/down arrow keys and j/k; you can create new cells with 'a' for 'above' and 'b' for 'below'.

With the latest version of jupyter notebook these shortcuts are broken.

This bisects to `39bd27fd2e71dbcf87efdb675500496fa3cd2633`, and further it bisects within jupyterlab to the commit which tagged 4.0.7 (the prior commit to that works).

Unfortunately with the way jupyter notebook and its dependency jupyterlab is built, I've been unable to further bisect. I've been able to build each of these in developer mode and reproduce the issue but not jupyter notebook such that its jupyterlab is picking up my copy of a checkout of jupyterlab for bisectoin.

### Steps To Reproduce

1. Run jupyter notebook
2. Ensure you're in command mode,
3. Press 'b' to add a cell below.
4. Press j and k to or the arrow keys to move up and down cells

### Expected behavior

A cell should be created, and it should be possible to move between cells in command mode.

### Notify maintainers

@NixOS/jupyter @GaetanLepage @natsukium @thomasjm 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thomasjm** [comment]
This is sounding like a real Jupyter regression that happened in `4.0.7`. Maybe it should be tracked in https://github.com/jupyterlab/jupyterlab/issues ?

**Comment by pwaller** [comment]
That was my first thought, however, it does not reproduce in an ubuntu docker container, (`docker run -ti ubuntu`, `apt install python-pip`, `pip install notebook`). This suggests that there is an issue being exposed by nix's packaging of it somehow. This might still be a juptyerlab issue but it seems we should try and identify the underlying cause.

**Comment by thomasjm** [comment]
Can you provide the exact steps you use to set this up?

I actually just tried it and the shortcuts worked for me. I did `nix build .#jupyter` on the latest Nixpkgs `master`, and ran `./result/bin/jupyter-notebook`.

```
tom in /tmp/tmp.JlmE6JynK8 λ /nix/store/azm23k80ywr6v39imk7m0c7wysn4np4y-python3-3.11.7-env/bin/jupyter-notebook --version
7.0.6
tom in /tmp/tmp.JlmE6JynK8 λ /nix/store/azm23k80ywr6v39imk7m0c7wysn4np4y-python3-3.11.7-env/bin/jupyter-lab --version
4.0.10
```

I'd also suggest opening the browser console and looking for errors when you try to use the shortcuts.

**Comment by pwaller** [comment]
I can confirm that the master branch works for me too, to my surprise! If I get spare time I'll try and identify why and report back.

**Comment by pwaller** [comment]
OK, after a confusing moment, I've realised that at least under some circumstances, the a/b shortcuts do work. `j/k` and `up/down` do appear to work! There was definitely a moment where a/b did not work but I can't seem to reproduce that now :thinking:. I'll update the issue body.

`nix run .#jupyter` on `2b4e2bf1883f` and `39bd27fd2e71dbcf87efdb675500496fa3cd2633` in nixpkgs seems to be enough to reproduce the issue.

**Comment by natsukium** [comment]
I checked with the following command, and I can confirm that it works fine on master.
`nix-shell -p 'python311.withPackages (ps: with ps; [notebook])' -I nixpkgs=. --run "jupyter notebook"`

Perhaps the implicit version mismatch in jupyter was resolved when staging-next was merged into master.

**Comment by pwaller** [comment]
With 2b4e2bf1883f00eb1217f1d7eff29916e93bc014 this still reproduces for me. @natsukium can I confirm that `j`/`k` and the `up`/`down` arrows function for you to move between cells?

```
nix-shell -p 'python311.withPackages (ps: with ps; [notebook])' -I nixpkgs=flake:nixpkgs/2b4e2bf1883f00eb1217f1d7eff29916e93bc014 --run "jupyter notebook"
```

* With a bump to abde03c6b3d19be0a69c57e5a1f475b03a09dd71 (master as of now), it still reproduces.
* Tested with firefox `121.0` with no extensions and chromium `120.0.6099.199` also with no extensions; same behaviour.
* I was wondering if this could be a state issue. I moved `$HOME/.jupyter` out of the way; but it still reproduces. My GUI settings are lost confirming that moving the state out of the way is having an effect. I don't know if there is some other state I should concern myself with.
* There are some things in the console, but last time I checked it was nothing new relative to a working version:

<details>
<summary>Click to expand console messages seen on chromium abde03c6b3d19be0a69c57e5a1f475b03a09dd71</summary>
```
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/application (required ^4.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
418 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^4.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
505 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 6.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^6.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
614 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^4.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
800 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.1.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^4.1.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
861 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/rendermime (required ^4.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
981 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
h @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
403 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 No satisfying version (^4.0.7) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 4.0.5 from _JUPYTERLAB.CORE_OUTPUT
c @ remoteEntry.b2792fe643cae74ea824.js:1
b @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
987 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
h @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
403 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
remoteEntry.b2792fe643cae74ea824.js:1 Unsatisfied version 4.0.5 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^4.0.7)
c @ remoteEntry.b2792fe643cae74ea824.js:1
f @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
408 @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.f.consumes @ remoteEntry.b2792fe643cae74ea824.js:1
(anonymous) @ remoteEntry.b2792fe643cae74ea824.js:1
x.e @ remoteEntry.b2792fe643cae74ea824.js:1
./extension @ remoteEntry.b2792fe643cae74ea824.js:1
n @ remoteEntry.b2792fe643cae74ea824.js:1
a @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
7819.bundle.js:1 Language pack 'en_GB' not installed!
fetch @ 7819.bundle.js:1
await in fetch (async)
activate @ 6815.bundle.js:1
await in activate (async)
(anonymous) @ 6731.bundle.js:1
Promise.then (async)
activatePlugin @ 6731.bundle.js:1
resolveOptionalService @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
activatePlugin @ 6731.bundle.js:1
resolveOptionalService @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
activatePlugin @ 6731.bundle.js:1
resolveRequiredService @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
activatePlugin @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
start @ 6731.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
5649.bundle.js:1 Menu entry for command 'filemenu:close-and-cleanup' is duplicated.
(anonymous) @ 5649.bundle.js:1
r @ 5649.bundle.js:1
(anonymous) @ 5649.bundle.js:1
t @ 5649.bundle.js:1
(anonymous) @ 5088.bundle.js:1
c @ 5088.bundle.js:1
fetch @ 5088.bundle.js:1
_transform @ 5649.bundle.js:1
load @ 5649.bundle.js:1
await in load (async)
e.loadSettingsMenu @ 5088.bundle.js:1
activate @ 5088.bundle.js:1
(anonymous) @ 6731.bundle.js:1
Promise.then (async)
activatePlugin @ 6731.bundle.js:1
resolveRequiredService @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
activatePlugin @ 6731.bundle.js:1
(anonymous) @ 6731.bundle.js:1
start @ 6731.bundle.js:1
(anonymous) @ 880.bundle.js:1
load (async)
60880 @ 880.bundle.js:1
v @ bundle.js:1
Promise.then (async)
37559 @ bundle.js:1
v @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
5649.bundle.js:1 Menu entry for command 'application:close' is duplicated.
```
</detail>

**Comment by pwaller** [comment]
I have tried firefox and chromium (the latter of which I've never used before on this machine so it's an empty profile) and they both have the same effect. I can also make the effect reliably appear/go away by switching between the problematic commit (39bd27fd2e71dbcf87efdb675500496fa3cd2633) and ts parent (8d17fb2bc6a105ddf06b4e20b0ff6829f4bf8863).

The difference between the two commits you pointed at is nil- I was sharing those commits as ones I had tested to rule out the possibility it was working for you on (an unnamed) master commit at the time of your testing.

To clarify what works for you, if you open a notebook with this version (39bd27fd2e71dbcf87efdb675500496fa3cd2633), and create a cell, you can use the j/k and up/down arrows to move between cells? What browser are you using?

**Comment by thomasjm** [comment]
On https://github.com/NixOS/nixpkgs/commit/39bd27fd2e71dbcf87efdb675500496fa3cd2633: `a/b` works for me. `j/k` and up/down arrows do not work.

I notice that the version of `pythonPackages.notebook` at the problematic commit is `7.0.3`. The release notes for `7.0.3` indicate that they bumped its `jupyterlab` dependencies to `~4.0.5`, as you can see e.g. here:

https://github.com/jupyter/notebook/blob/v7.0.3/app/package.json#L27-L99

So, I'd surmise the following:

* Jupyter Notebook wasn't expecting to be run with `jupyterlab` version `4.0.9`, which is the version the problematic commit bumps it to.
* This is a semver mistake on the Jupyter team's part, as 4.0.9 should be compatible but causes a regression here. (As a reminder partially to myself, `~4.0.5` means "any version like `4.0.x`," i.e. patch bumps only.)
* This is not a Nix packaging issue, as we followed semver. Although perhaps we could avoid such issues in the future if we didn't bump dependencies like `jupyterlab` too far ahead like this.

**Comment by pwaller** [comment]
FWIW, I have been using this for a while without issue, so it must have started working again at some point. I don't have reason to believe it is currently broken, anyway.
