### ISSUE TITLE
Update request: solana-cli 1.14.23→ 1.16.27

### ISSUE THREAD

**Issue by arijoon** [NixOS/nixpkgs#280604]
- Package name: solana-cli
- Latest released version: 1.16.27

- Current version on the unstable channel: 1.14.23
- Current version on the stable/release channel: 1.14.23

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aikooo7** [comment]
Hello @arijoon, I was able make the building script work so solana-cli is updated to 1.16.27 expect solana has bug in a [specific library](https://github.com/lu-zero/autotools-rs/) which doesn't let me compile.

The issue was already reported back back in 22 november 2023: solana-labs/solana#34203

So until is fixed I can't do anything more, as soon as it is fixed I will post my pr

**Comment by arijoon** [comment]
> So until is fixed I can't do anything more, as soon as it is fixed I will post my pr

Thanks @aikooo7 , did you manage to build it for the current version? (`1.14.23`)
On the master of nixpkgs I couldn't even build the existing version of Solana due a rocksdb issue

```
"enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident
```

**Comment by aikooo7** [comment]
> > So until is fixed I can't do anything more, as soon as it is fixed I will post my pr
> 
> Thanks @aikooo7 , did you manage to build it for the current version? (`1.14.23`) On the master of nixpkgs I couldn't even build the existing version of Solana due a rocksdb issue
> 
> ```
> "enum_(unnamed_at_rocksdb/include/rocksdb/c_h_981_1)" is not a valid Ident
> ```

Hello @arijoon I didn't test it and I don't think I need since I made it able to compile 1.16.27

> I also found this commit on homebrew PRs. Seems like they patched this part in order to make the build work: https://github.com/Homebrew/homebrew-core/pull/156930/files

I appreciate the citation, with the patch used by them I was able to fix it, appreciate your help
