### ISSUE TITLE
Package request: harlequin

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#280605]
**Project description**

The SQL IDE for Your Terminal.

**Metadata**

* homepage URL: https://harlequin.sh/
* source URL: https://github.com/tconbeer/harlequin
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
related: #256516

**Comment by ducc** [comment]
For anyone trying to get this running whilst we wait for this package:
```
> nix-shell -p pipx python3Packages.pyarrow

[nix-shell:~]$ pipx install harlequin
[nix-shell:~]$ ~/.local/bin/harlequin
```

**Comment by luisnquin** [comment]
+1
