### ISSUE TITLE
jellyfin-ffmpeg fails to build: Unknown option "--enable-libaribcaption".

### ISSUE THREAD

**Issue by anund** [NixOS/nixpkgs#280645]
### Describe the bug
Jellyfin-ffmpeg overrides `ffmpeg_6-full` in a way that passes one version value (`6.1`) to the outer scope and a different value to the derivation scope (`6.0.1`). As a result `withAribcaption = true` is set and the build fails with `Unknown option "--enable-libaribcaption".`.

A rough fix looks like:
```diff
diff --git a/pkgs/development/libraries/jellyfin-ffmpeg/default.nix b/pkgs/development/libraries/jellyfin-ffmpeg/default.nix
index 7109a5d6dfd1..0b398b41f73a 100644
--- a/pkgs/development/libraries/jellyfin-ffmpeg/default.nix
+++ b/pkgs/development/libraries/jellyfin-ffmpeg/default.nix
@@ -4,7 +4,9 @@
 , lib
 }:
 
-ffmpeg_6-full.overrideAttrs (old: rec {
+(ffmpeg_6-full.override{
+  withAribcaption = false; # ffmpeg_6-full sets this to true based on a meta version value of '6.1' not the '6.0.1' used below  
+}).overrideAttrs (old: rec {
   pname = "jellyfin-ffmpeg";
   version = "6.0.1-1";
```
Looks like https://github.com/NixOS/nixpkgs/issues/271863 also may change things in this area.

### Steps To Reproduce
1. `nix build -f <localnixpkgscheckout> jellyfin-ffmpeg`
2. build fails with `Unknown option "--enable-libaribcaption".`

### Expected behavior
Jellyfin-ffmpeg builds

### Additional context
https://github.com/NixOS/nixpkgs/pull/271905 bumped ffmpeg in several places. It uses the existing pattern for guarding against version inconsistencies: https://github.com/NixOS/nixpkgs/blob/8bb443b2b8d6bf55a6d65402435dc81f6369ebfd/pkgs/development/libraries/ffmpeg/generic.nix#L30 This doesn't work as the `version` value referenced is from the outer function scope passed in when creating `ffmpeg_6-full = ffmpeg_6.override{ ...` https://github.com/NixOS/nixpkgs/blob/8bb443b2b8d6bf55a6d65402435dc81f6369ebfd/pkgs/development/libraries/ffmpeg/6.nix#L1-L4 not the library `version` value set later in https://github.com/NixOS/nixpkgs/blob/8bb443b2b8d6bf55a6d65402435dc81f6369ebfd/pkgs/development/libraries/jellyfin-ffmpeg/default.nix#L7-L9.

### Notify maintainers
@arthsmn @justinas @Atemu 

### Metadata
Building from current master

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
``` diff
diff --git a/pkgs/development/libraries/ffmpeg/generic.nix b/pkgs/development/libraries/ffmpeg/generic.nix
index 8b810120b80b..8bce3b57a493 100644
--- a/pkgs/development/libraries/ffmpeg/generic.nix
+++ b/pkgs/development/libraries/ffmpeg/generic.nix
@@ -447,7 +447,7 @@ stdenv.mkDerivation (finalAttrs: {
      */
     (enableFeature withAlsa "alsa")
     # FIXME: see if jellyfin-ffmpeg is already on a version >= 6.1 to use enableFeature
-    (optionalString withAribcaption "--enable-libaribcaption")
+    (optionalString (versionAtLeast version "6.1" && withAribcaption) "--enable-libaribcaption")
     (enableFeature withBzlib "bzlib")
     (enableFeature withCelt "libcelt")
     (enableFeature withCuda "cuda")
```

Wouldn't something like this fix it?

**Comment by Atemu** [comment]
@arthsmn that should do it. Should also be possible to send that to master as it should mean no rebuild for most other things.

**Comment by arthsmn** [comment]
> @arthsmn that should do it. Should also be possible to send that to master as it should mean no rebuild for most other things.

Yeah I think it's better than having more stuff on the jellyfin-ffmpeg side.

**Comment by Atemu** [comment]
Also, shouldn't that have broken ffmpeg <6 too?

**Comment by arthsmn** [comment]
> Also, shouldn't that have broken ffmpeg <6 too?

I don't think so, if jellyfin-ffmpeg would override ffmpeg-5 or -4 it would pass the version of the ffmpeg package, which is lower than 6.1.

**Comment by arthsmn** [comment]
@Atemu sadly my fix doesn't seem to work. I'm not sure why but I think we'll need to override withAribcaption in jellyfin-ffmpeg.

**Comment by arthsmn** [comment]
```diff
diff --git a/pkgs/development/libraries/ffmpeg/generic.nix b/pkgs/development/libraries/ffmpeg/generic.nix
index 8b810120b80b..c8a167840500 100644
--- a/pkgs/development/libraries/ffmpeg/generic.nix
+++ b/pkgs/development/libraries/ffmpeg/generic.nix
@@ -27,7 +27,7 @@
   # Feature flags
 , withAlsa ? withHeadlessDeps && stdenv.isLinux # Alsa in/output supporT
 , withAom ? withFullDeps # AV1 reference encoder
-, withAribcaption ? withFullDeps && lib.versionAtLeast version "6.1" # ARIB STD-B24 Caption Decoder/Renderer
+, withAribcaption ? withFullDeps && lib.versionAtLeast version "6.1.0" # ARIB STD-B24 Caption Decoder/Renderer
 , withAss ? withHeadlessDeps && stdenv.hostPlatform == stdenv.buildPlatform # (Advanced) SubStation Alpha subtitle rendering
 , withBluray ? withFullDeps # BluRay reading
 , withBs2b ? withFullDeps # bs2b DSP library
```
@anund can you test this? I think the problem is because a 3-parts is being used with a 2-parts one.

**Comment by Atemu** [comment]
The `version` in that part of the code comes from ffmpeg_6-full. It's also not the issue:

```
nix-repl> lib.versionAtLeast "6.0-7" "6.1"
false
```

**Comment by arthsmn** [comment]
So the only option is to add the override to jellyfin-ffmpeg.
