### ISSUE TITLE
Build failure: python3Packages.prophet

### ISSUE THREAD

**Issue by lblasc** [NixOS/nixpkgs#280751]
### Steps To Reproduce

1. build `nix build .#python3Packages.prophet`

### Build log

```
error: builder for '/nix/store/djybirhg8h70xrc0dvnwnm6k6r694pli-python3.11-prophet-1.1.5.drv' failed with exit code 1;
       last 10 log lines:
       > writing manifest file 'prophet.egg-info/SOURCES.txt'
       > reading manifest file 'prophet.egg-info/SOURCES.txt'
       > reading manifest template 'MANIFEST.in'
       > no previously-included directories found matching 'prophet/stan_model'
       > adding license file 'LICENSE'
       > writing manifest file 'prophet.egg-info/SOURCES.txt'
       >
       > ERROR Missing dependencies:
       >        cmdstanpy>=1.0.4
       >        stanio~=0.3.0
       For full logs, run 'nix log /nix/store/djybirhg8h70xrc0dvnwnm6k6r694pli-python3.11-prophet-1.1.5.drv'.
```

### Additional context

stanio bump 708a5908502d4868a5d1c441bfbf207f49c5305a caused a build faliure.

### Notify maintainers

@tomasajt

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[lblasc@obsidian:~/nixpkgs]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-91-generic, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05.20230202.006c3bd"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
It turns out it's actually an issue with he `cmdstanpy` python package. It looks like the fact that `prophet` uses the new `pyproject = true;` builder made it so that it even if `cmdstanpy` builds without complaining (probably something to do with the legacy builder), trying to include it as a dependency of `prophet` will detect the version error.
I'll try to open a PR, which updates `cmdstanpy` to use the new builder (and I'll relax the dependency constraint too).

**Comment by lblasc** [comment]
Thank you Toma for fast response and resolution!
