### ISSUE TITLE
Package request: nextcloud18.packages.apps.{files_markdown,files_texteditor,memories,news}

### ISSUE THREAD

**Issue by RGBCube** [NixOS/nixpkgs#280709]
**Project description**

Basically add the entries to https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/nextcloud/packages/28.json. I'm not familiar with the ecosystem at all so I'm opening this issue.

**Comment by applePrincess** [comment]
As stated [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/nextcloud/packages/README.md)

all packages listed in `nextcloud-apps.json` will be defined/packaged if the latest version is available to corresponding Nextcloud versions when `./generate.sh` is executed.

As of today, all four apps(files_markdown,files_texteditor,memories,news) is defined in `nextcloud-apps.json` but files_markdown and files_texteditor is not available to Nextcloud 28.


Related upstream issue:
icewind1991/files_markdown#218
nextcloud/files_texteditor#816

**Comment by onny** [comment]
Closing this as this is not a NixOS issue anymore
