### ISSUE TITLE
FISH: not recognize programs.fish.enable when shell = pkgs.fish; is set to a different file

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#280726]
### Describe the bug
I'm using NixOS and I deploy my configuration by flakes. I have two different files where I set fish shell.

**./home-manager/shells/fish/default.nix**
```nix
{ home-manager, username, shell, ... }:
{
    home-manager.users.${username} = { pkgs, ...}: {
      home.packages = with pkgs; [
        neofetch
        zoxide
      ];
      xdg.configFile."fish/functions/fish_prompt.fish".source = ./fish_prompt.fish;
      programs.fish = {
        enable = true;
      };
    };
}
```
and **./users/default.nix**
```nix
{ pkgs, username, ... }:
{
# Define a user account. Don't forget to change the password by ‘passwd’.
  users.users.${username} = {
    shell = pkgs.fish;
    ignoreShellProgramCheck = true;
    isNormalUser = true;
    initialPassword = "changeme";
    extraGroups = [ "wheel" "input" "video" "render" "networkmanager" ];
    packages = with pkgs; [
      git
      vscodium
      wget
    ];
  };
}
```
when I run this configuration by flakes, I get the following error:
```sh
       error:
       Failed assertions:
       - users.users.myuser.shell is set to fish, but
       programs.fish.enable is not true. This will cause the fish
       shell to lack the basic nix directories in its PATH and might make
       logging in as that user impossible. You can fix it with:
       programs.fish.enable = true;

       If you know what you're doing and you are fine with the behavior,
       set users.users.myuser.ignoreShellProgramCheck = true;
       instead.
```
Why am I getting this error if I specified fish to be enabled?

### Expected behavior
Building process with no error.

### Notify maintainers
@adamcstephens @cole-h @winterqt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
@D3vil0p3r This error is because NixOS knows nothing about home-manager modules. You are expected to set `programs.fish.enable` in your *NixOS* configuration.

**Comment by D3vil0p3r** [comment]
> ./home-manager/shells/fish/default.nix

Oh. Do you mean outside `home-manager.users.${username} = { pkgs, ...}: {` block?

**Comment by adamcstephens** [comment]
Yes, assuming that is a NixOS configuration file.

**Comment by D3vil0p3r** [comment]
Thank you.
