### ISSUE TITLE
Package request: MEGA (Cloud Storage Provider)

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#280796]
Please provide a package for the popular cloud storage provider => MEGA

- https://mega.io/de/desktop#downloadapps

**Comment by kashw2** [comment]
NixPkgs already offers:
- megam
- megasync
- megacmd
- megatools

are there others that are missing?

**Comment by boustanihani** [comment]
Thanks for your quick reply.

**"megam"** has nothing to do with MEGA Cloud Storage =>
MEGA Model Optimization Package (https://users.umiacs.umd.edu/~hal/megam/)

I didn't notice those packages, sorry my mistake:
- **megacmd** => MEGA Command Line Interactive and Scriptable Application
- **megasync** => Easy automated syncing between your computers and your MEGA Cloud Drive
- **megatools** => Command line client for Mega.co.nz

**Optimization suggestion:** I think **the keywords "Cloud Storage"** should be included in each of the descriptions above, this would make it easier for users to find the needed packages.

And also, searching for the **official website URL (mega.io)** , should return all three related packages in the results.
The official website is now https://mega.io/
