### ISSUE TITLE
Build failure: python311Packages.pyqtgraph

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#280894]
### Steps To Reproduce

https://hydra.nixos.org/build/246267265

### Build log

https://hydra.nixos.org/build/246267265/nixlog/1

### Notify maintainers

 @k0ral @mweinelt 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240113.9b19f5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/b0l3v8509hrl3qbv6fj2zl0mjb2rwhdy-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by a-n-n-a-l-e-e** [comment]
fixed by #281017
