### ISSUE TITLE
Build failure: morgen

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#280893]
### Steps To Reproduce

1. build *morgen*

### Build log

```
trying https://dl.todesktop.com/210203cqcj00tw1/versions/3.1.6/linux/deb
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
curl: (22) The requested URL returned error: 500
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
curl: (22) The requested URL returned error: 500
error: cannot download deb from any mirror
```

### Additional context

As previously mentioned in pull request #274212, the download URL for the deb file appears to be unstable, resulting in a 500 HTTP error code after the release of a new version. In the mentioned pull request, it appeared that this issue had been addressed by todesktop (as highlighted by @mdehollander). Unfortunately, it seems that we are experiencing some misfortune, as the problem has resurfaced once again.

### Notify maintainers
@justanotherariel
@wolfangaukang

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mdehollander** [comment]
To bad the todesktop links are really unstable. Hereb I ping @davej from ToDesktop. He solved he issue the last time. I will also send him a message via the email thread we have. Hope the todesktop links can become stable, otherwise the workaround archive.org or something like that needs to be used.

**Comment by davej** [comment]
Thanks for the ping @mdehollander, we had an issue that prevented a database index from being persisted. We have now resolved the issue and I am confident that it will not be an issue in the future.

**Comment by mdehollander** [comment]
Thanks @davej!

**Comment by kilianar** [comment]
Thank you for the prompt resolution. The download URL is functional and the hash remains unaltered. Consequently, *morgen* builds seamlessly once more. As a result, I am closing the issue.
