### ISSUE TITLE
guestmount fails due to mismatched appliance

### ISSUE THREAD

**Issue by jchv** [NixOS/nixpkgs#280881]
### Describe the bug
The current version of libguestfs in nixpkgs is 1.50.1 at the time of writing. However, the current version of the libguestfs appliance in nixpkgs is currently 1.46.0. This causes somewhat confusing errors in `guestmount` that are only visible when using `--no-fork --verbose`:

> guestfsd: error: dispatch_incoming_message: unknown procedure number 511, set LIBGUESTFS_PATH to point to the matching libguestfs appliance directory

### Steps To Reproduce
1. `nix shell nixpkgs\#libguestfs-with-appliance -c guestmount -a $DISKIMAGE -m $DEVICE $MOUNTPOINT --ro --no-fork --verbose`
2. `ls $MOUNTPOINT`
3. The `ls` will fail with invalid argument, while errors about unknown procedures will appear in the verbose log.

### Expected behavior
The mountpoint should be accessible and functional.

### Additional context
The problem exists here because libguestfs-appliance is supposed to match libguestfs, but NixOS does not currently build the libguestfs-appliance, instead downloading the binary directly. Unfortunately, it looks like new libguestfs-appliance binaries are no longer being posted (?), so now the nixpkgs version of libguestfs has become quite newer than the version of libguestfs-appliance.

@minijackson seems to have been recently working on making libguestfs-appliance build inside nixpkgs rather than pulling external binaries in #278954, which would resolve this issue the proper way. However, I wanted to raise this issue because I don't really know if it's obvious enough that libguestfs and libguestfs-appliance need to be the same version. Right now it's possibly preferable to allow them to desync because otherwise libguestfs would be stuck on an old version and not all utilities in libguestfs are broken by this; however, libguestfs-with-appliance is effectively broken right now due to this mismatch. Once it's possible, it would be nice to ensure that these two derivations are always kept in sync.

If I use an overlay to revert back to libguestfs 1.46, everything works as expected again.

### Notify maintainers
@offlinehacker 

Recent contributors as well, for visibility...
@r-vdp @wegank

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by panchoh** [comment]
> Unfortunately, it looks like new libguestfs-appliance binaries are no longer being posted (?),
They seem to have published [one](https://download.libguestfs.org/binaries/appliance/) recently, after almost three years. It's for the development version (1.53), though.

**Comment by adrblo** [comment]
Building the appliance in nixpkgs would also help for aarch64 support of libguestfs. It's currently not useable at all on aarch64.

**Comment by jchv** [comment]
There should probably be a new issue for actually building it from source. If someone wants to pick up #278954 and give it a shot, that would be great, but it seems like it's pretty hard.

**Comment by malte-v** [comment]
> Building the appliance in nixpkgs would also help for aarch64 support of libguestfs. It's currently not useable at all on aarch64.

I've made a PR that adds aarch64 support: https://github.com/NixOS/nixpkgs/pull/381224
