### ISSUE TITLE
The gitlab option services.gitlab.initialRootPassword doesn't handle special characters

### ISSUE THREAD

**Issue by Dieff** [NixOS/nixpkgs#28095]
## Issue description
For my first NixOS based machine, I wanted to set up a Gitlab server for my local network. I based most of the configuration for this server from the NixOS manual (https://nixos.org/nixos/manual/index.html#module-services-gitlab). I set a specific initial user and password with the `services.gitlab.initialRootEmail` and `services.gitlab.initialRootPassword` options. My initial root password was "********$2017", with the *s as letters. However, once my Gitlab server was running, and proxied with an Nginx install, I was not able to log into it through my web browser. I eventually noticed the following reports from journalctl:

 `Aug 10 03:02:03 UMCST-GITLAB gitlab-pre-start[1610]: == Seed from /nix/store/8vbx2fy8cq5z5qdqjggm464dzzqcqz49-gitlab-8.17.6/share/gitlab/db/fixtures/production/001_admin.rb

Aug 10 03:02:04 UMCST-GITLAB gitlab-pre-start[1610]: Administrator account created:

Aug 10 03:02:04 UMCST-GITLAB gitlab-pre-start[1610]: login:    root

Aug 10 03:02:04 UMCST-GITLAB gitlab-pre-start[1610]: password: ********017

Aug 10 03:02:04 UMCST-GITLAB gitlab-pre-start[1610]: == Seed from /nix/store/8vbx2fy8cq5z5qdqjggm464dzzqcqz49-gitlab-8.17.6/share/gitlab/db/fixtures/production/010_settings.rb`

It seems as though my password was truncated, or modified, before being set. I was able to sign in with the password that appeared in the logs. Maybe this is the result of the "$" I used in the password.

### Steps to reproduce
* On a NixOS install without Gitlab, update the configuration similar to
`  services.gitlab = {
    enable = true;
    databasePassword = "XXXXXXXX";
    initialRootEmail = "admin@example.local";
    initialRootPassword = "******$2017";
    https = true;
    host = "git.example.local";
    port = 443;
    user = "git";
    group = "git";
    statePath = "/data/gitlab/state";
    smtp = {
      enable = true;
      address = "localhost";
      port = 25;
    };
    secrets = {
      db = "asldfhj;alsdhf;lasdhfl;ahsdflhasdf";
      secret = "asdlkfjadlsakfjaalskdjfaalsjd";
      otp = "asdfasdfasdfasdfasdfsdf";
    };
    extraConfig = {
      gitlab = {
        email_from = "gitlab-no-reply@example.local";
        email_display_name = "test123";
        email_reply_to = "gitlab-no-reply@example.local";
        default_projects_features = { builds = false; };
      };
    };`
* run `nixos-rebuild switch`
* attempt to login to your new gitlab install using the expected default username and password.

## Technical details

* System: NixOS: 17.03.1654.c40b85d4fd (Gorilla), running on a VCenter VM.
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1654.c40b85d4fd"
* Sandboxing is not enabled

**Comment by disassembler** [comment]
`$` is a special character in nix strings used for interpolation "${nix expression}". I'm guessing this is what the problem is. Can you try adding a `\` before the `$` and see if that resolves the issue?

**Comment by Dieff** [comment]
I believe that the `$` was the issue. Thanks for the help.
