### ISSUE TITLE
Feature request: Let the "Hompage" of all packages also be searchable.

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#280962]
**Feature request: Let the "Hompage" of all packages also be searchable.**

For example, if I search for the package `"lmms"`, all is fine. 

But if I type `"https://lmms.io/"` or `"lmms.io"` in the search field, no results are returned.
See attached screenshots.

NixOS has the biggest package repository of all distributions.
This would make it easier for users to find packages, when they do not know what the package name is.
Searching by using the official domain of the product should also be possible..

![Bildschirmfoto vom 2024-01-14 17-15-46](https://github.com/NixOS/nixpkgs/assets/4227548/73e937d8-4c45-40d3-afdc-bce861541108)

![Bildschirmfoto vom 2024-01-14 17-15-56](https://github.com/NixOS/nixpkgs/assets/4227548/06053d73-77a1-4aaf-8d58-dfc02d64898e)

![Bildschirmfoto vom 2024-01-14 17-16-05](https://github.com/NixOS/nixpkgs/assets/4227548/57df821f-f42f-4a7a-b759-8cdf8c22a72c)

**Comment by OPNA2608** [comment]
Wrong project I think, the search page is https://github.com/NixOS/nixos-search .

**Comment by boustanihani** [comment]
Thanks, I added this to the search page project: https://github.com/NixOS/nixos-search/issues/713
