### ISSUE TITLE
gcc-wrapper depends on bootstrap-tools

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#28091]
```gcc-wrapper``` depends on ```bootstrap-tools``` (115Mb) via needless ```rpath``` in ```expand-response-params```

http://i.imgur.com/ALBgpCG.png
![](http://i.imgur.com/ALBgpCG.png)

**Comment by copumpkin** [comment]
That's odd! I thought we used `disallowedRequisites` and so on to prevent bootstrap tools from creeping into the stdenv. That's what we do on Darwin at least, and I'm pretty sure I stole the idea from Linux.

**Comment by copumpkin** [comment]
Oh 😦 https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/linux/default.nix#L302-L308

**Comment by copumpkin** [comment]
I'm having trouble tracing the blame back to easily figure out when `allowedRequisites` was commented out. @Ericson2314 do you know what's up there?

**Comment by copumpkin** [comment]
Or actually, @vcunat, the only promising commit I was able to find was https://github.com/NixOS/nixpkgs/commit/bf414c9d4f892fd4e392a5f42016b57e84402a8b, which looks (via GitHub at least) like you might have commented it out during a merge?

**Comment by dezgeg** [comment]
I thought https://github.com/NixOS/nixpkgs/commit/b9c403c5310a61d7274f8490b9a06be8ccd1bc93 was already committed but it's apparently only in gcc-6 branch.

**Comment by vcunat** [comment]
Right, it was intentionally commented out during the merge and then completely forgotten.  These are two "separate" things to fix then.

**Comment by dezgeg** [comment]
All the fixes are in master now.

**Comment by copumpkin** [comment]
Yay, thanks!

**Comment by cdyson37** [comment]
Please note: I think this breaks keeping debug symbols. See #64980.
