### ISSUE TITLE
gamemode is unable to change the processor scheduler

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NixOS/nixpkgs#280976]
### Describe the bug
gamemode is unable to change the processor scheduler

### Steps To Reproduce
1. set any (schedutil for example) CPU scheduler as default (`powerManagement.cpuFreqGovernor = "schedutil";`) 
2. set `programs.gamemode.enable` and `programs.gamemode.enableRenice` to true, set `programs.gamemode.settings.general.desiredgov` to different CPU scheduler (performance for example) 
3. run any command with `gamemoderun` and check logs of service (`journalctl --user -e -u gamemoded`), there will be pkexec "Not authorized" errors. Or run `/run/wrappers/bin/gamemoded -t` it will report that tests failing

### Expected behavior
The CPU scheduler is changed to the one specified in `programs.gamemode.settings.general.desiredgov` for the duration of the execution of the gamemoderun command, and then returned to the default value

### Additional context

tested on nixpkgs commit `317484b1ead87b9c1b8ac5261a8d2dd748a0492d`

### Notify maintainers

@kira-bruneau

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.9-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/wckjmzcqc347li9r9154nvav82f22g8n-0g53xyh39z3y90p4d8r341wbqyjy1zhl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by PhilT** [comment]
This can also be verified with `gamemoded -t`:

```
: Loading config
Loading config file [/nix/store/c9a9kpq0w0cq3j550iblb8r7jj3xpsrn-gamemode-1.8.1/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
ERROR: Governor was not set to performance (was actually powersave)!
::: Failed!
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
ERROR: :: Failed!
: Tests Failed!
```

**Comment by kira-bruneau** [comment]
This is an upstream change since 1.8, you need to add yourself to the `gamemode` group to change the processor scheduler.

See https://github.com/FeralInteractive/gamemode/issues/452.

**Comment by kira-bruneau** [comment]
Oh yep that makes sense!

**Comment by kira-bruneau** [comment]
I was also trying to add a NixOS test for it, but you can't set the governor of a CPU within a VM, so I just left it out: https://github.com/NixOS/nixpkgs/pull/281909
