### ISSUE TITLE
Build failure: oh-my-posh

### ISSUE THREAD

**Issue by BirdeeHub** [NixOS/nixpkgs#280961]
### Steps To Reproduce

1. build *oh-my-posh* package as part of a system flake on nixos-unstable branch
2. only broke today, however most recent working commit I have found is: 6660475dea29309327ee3b2e6824ec0011589017 which is obviously confusing

### Build log

[issue with response and log and error message, referred to you by author](https://github.com/JanDeDobbeleer/oh-my-posh/issues/4622)

### Additional context

package author says not their issue, but also says the package is out of date as they are on 19.5.2 and the package is on 18.26.1
My system config is:
https://github.com/BirdeeHub/birdeeSystems
Dont judge im kinda new I havent worked on secrets yet so I just dont have any secrets in it

### Notify maintainers

@lucperkins 
@urandom2

**Comment by wackbyte** [comment]
Looks like an update PR is in progress that'll probably fix it: #273191
