### ISSUE TITLE
Package request: ssh-tpm-agent

### ISSUE THREAD

**Issue by williballenthin** [NixOS/nixpkgs#281090]
**Project description**

ssh-tpm-agent is a ssh-agent compatible agent that allows keys to be created by the Trusted Platform Module (TPM) for authentication towards ssh servers.

**Metadata**

* homepage URL:
* source URL: https://github.com/Foxboron/ssh-tpm-agent
* license: MIT
* platforms: unix (at least)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Foxboron** [comment]
https://github.com/NixOS/nixpkgs/pull/249404

**Comment by williballenthin** [comment]
ah, thanks @Foxboron. i promise i did search but somehow didn't get any relevant results. probably PEBKAC.
