### ISSUE TITLE
Package request: Paper Plane 

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nixpkgs#281095]
**Project description**

Paper Plane is an alternative Telegram client. It uses libadwaita for its user interface and strives to meet the design principles of the GNOME desktop.

Keep in mind Paper Plane is still in Beta releases.

**Metadata**

* homepage URL: https://github.com/paper-plane-developers/paper-plane
* source URL: https://github.com/paper-plane-developers/paper-plane
* license: GPL-3.0
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by I-like-stuff** [comment]
I also would like to have this

**Comment by Aleksanaa** [comment]
> Also, the included API credentials in the Flathub release are still very new and untested. In some cases, your account may end up banned by Telegram (check the Telegram API Credentials section below).

So if we distribute a new API key, users may get banned at the beginning. This is an issue we need to consider seriously.

**Comment by I-like-stuff** [comment]
> > Also, the included API credentials in the Flathub release are still very new and untested. In some cases, your account may end up banned by Telegram (check the Telegram API Credentials section below).
> 
> So if we distribute a new API key, users may get banned at the beginning. This is an issue we need to consider seriously.

doesn't telegram already ships with an open API, why is this one specifically an issue

**Comment by Aleksanaa** [comment]
> doesn't telegram already ships with an open API, why is this one specifically an issue

The API documentation is open but you need a credential to use it. You are not supposed to (I don't know if this is technically possible) reuse the credential distributed with the official client.

**Comment by Aleksanaa** [comment]
I've got the developers' permission to use their key provided in the AUR package. I'll try to package it right away.

![Screenshot_20240129-101125_Telegram](https://github.com/NixOS/nixpkgs/assets/42209822/5dce7abe-4c76-4d23-a9ca-0387368b8615)
![Screenshot_20240129-101148_Telegram](https://github.com/NixOS/nixpkgs/assets/42209822/2cebf3f8-c594-46d2-bf3c-3a7509183f40)

**Comment by I-like-stuff** [comment]
thank you

**Comment by Aleksanaa** [comment]
Yes.
