### ISSUE TITLE
lsb_release none information

### ISSUE THREAD

**Issue by noirecat** [NixOS/nixpkgs#28100]
## Issue description
![lsb_release](https://user-images.githubusercontent.com/20453528/29163240-0faba2c8-7de6-11e7-8697-eaa06d6773cf.png)

## Technical details

* System: 17.03.1645.08bc48049c (Gorilla)
* Nix version: 1.11.13
* Nixpkgs version: 17.03.1665.055e5c3578
* Sandboxing enabled: false

**Comment by copumpkin** [comment]
Dupe of https://github.com/NixOS/nixpkgs/issues/22729

**Comment by Mic92** [comment]
closed because of duplication.
