### ISSUE TITLE
Build failure: kanidm

### ISSUE THREAD

**Issue by Kranzes** [NixOS/nixpkgs#281018]
### Steps To Reproduce

1. build kanidm

### Build log

```
https://hydra.nixos.org/build/245589915
```

### Notify maintainers
@erictapen @Flakebi @mweinelt @adamcstephens

### Metadata
```console
NixOS, 24.05 (Uakari), 24.05.20231227.f930306
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
It seems like maybe rust is now erroring on warnings?

```
error: unused import: `implementation::*`
  --> unix_integration/nss_kanidm/src/lib.rs:24:9
   |
24 | pub use implementation::*;
   |         ^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> unix_integration/nss_kanidm/src/lib.rs:1:9
   |
1  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`
```
