### ISSUE TITLE
Update request: graphite-cli 1.0.9 → 1.1.1

### ISSUE THREAD

**Issue by Guibi1** [NixOS/nixpkgs#281024]
- Package name: Grahpite-cli
- Latest released version: 1.1.1

- Current version on the unstable channel: 1.0.9
- Current version on the stable/release channel: 1.0.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

This package has no maintainer because it is a NPM package. #229475 might be related?
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aikooo7** [comment]
Hello @Guibi1, thanks for the request, I will try to go from node2nix to build from source as the issue linked suggestes

**Comment by aikooo7** [comment]
Giving a quick check to the graphite-cli repo linked in the npm package it is archived and "moved to your mono-repo" and also it is built with yarn so nor it can migrated to buildNpmPackage nor to building from source, so my guess is that it will need to still in node2nix

**Comment by dotlambda** [comment]
Please make a PR marking the package as unfree since their monorepo isn't publicly available.

**Comment by aikooo7** [comment]
> Please make a PR marking the package as unfree since their monorepo isn't publicly available.

As of right now graphite-cli is already unfree
