### ISSUE TITLE
Build failure: komikku

### ISSUE THREAD

**Issue by NotAShelf** [NixOS/nixpkgs#281198]
### Steps To Reproduce

1. build *komikku* from the latest revision

### Build log

```
https://p.frzn.dev/ji8
```
### Notify maintainers

@chuangzhu 

also @infinitivewitch, but account is gone

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NotAShelf** [comment]
As a side note, this is related to a build failure for **python3.11-pure-protobuf** but seeing the maintainer is the same (@chuangzhu) I will not open a second issue.

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/280551 has been merged

**Comment by NotAShelf** [comment]
The protobuf package seems to fail to build on the latest nixpkgs master revision.

**Comment by chuangzhu** [comment]
> The protobuf package seems to fail to build on the latest nixpkgs master revision.

Is it? Nix flake sometimes caches the downloads, you need to pass a `--refresh` for it to work. `nix build nixpkgs#komikku --refresh`

**Comment by kirillrdy** [comment]
nix build nixpkgs#komikku --refresh

This will build from unstable not master

**Comment by NotAShelf** [comment]
I'm building while checked out to the latest revision of nixpkgs locally, in the master branch. Also occurs while using `nix build github:nixos/nixpkgs#python311Packages.pure-protobuf`

**Comment by NotAShelf** [comment]
Seems to build now, I don't know what has changed since last night. Eitherway, closing.
