### ISSUE TITLE
Build failure: trueseeing

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#281164]
### Steps To Reproduce

1. build trueseeing
2. Runtime dependency check fails due to missing termcolor.

### Build log

```bash
copying path '/nix/store/w2lcxb320jjziy7h0j0b0fy626hbln4x-samba-4.19.4' from 'https://cache.nixos.org'...
* Getting build dependencies for wheel...
  - termcolor not installed
  - urllib3<2.0.0,>=1.25.8 not satisfied by version 2.1.0
  - websockets<11.0,>=10.0 not satisfied by version 12.0
  - pyfiglet<0.9,>=0.8.post1 not satisfied by version 1.0.2
error: builder for '/nix/store/y2wv3y1f441m2imsh1ji0c3r9inq54fi-trueseeing-2.1.9.drv' failed with exit code 1;
       last 10 log lines:
       > Creating a wheel...
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built trueseeing-2.1.9-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for trueseeing-2.1.9-py3-none-any.whl
       >   - termcolor not installed
       For full logs, run 'nix log /nix/store/y2wv3y1f441m2imsh1ji0c3r9inq54fi-trueseeing-2.1.9.drv'.
```

Full logs : 
<summary> 
<details> 
<pre>
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/p05bg72wb6ihkj9jjmdgzsnjifd0m0ar-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/trueseeing/signature/security.py
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing pypaBuildPhase
Creating a wheel...
* Getting build dependencies for wheel...
* Building wheel...
Successfully built trueseeing-2.1.9-py3-none-any.whl
Finished creating a wheel...
Finished executing pypaBuildPhase
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for trueseeing-2.1.9-py3-none-any.whl
  - termcolor not installed
</pre>
</details>
</summary>

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71-1-lts, Garuda Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.1`
 - channels(root): `""`
 - channels(user): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
---

I believe trueseeing is missing the termcolor dependency hence the failure happening during the build. @fabaff 

I can try and PR a fix but I did not try and reproduce the bug under NixOS.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
Seems a lot of other packages have broken in similar ways, mitmproxy, ioccheck, theharvester but they all fail due to missing runtime dependencies or version of modules that are not meeting constraints.

**Comment by quyse** [comment]
I had the same issue with mitmproxy and found this issue because you've mentioned it here. git bisect for mitmproxy got this commit for me: 9490738be7b6a33844e4faf192f168bb755539e6

**Comment by icyrockcom** [comment]
This seems relevant: https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574/40?page=2

**Comment by dotlambda** [comment]
> I did not try and reproduce the bug under NixOS.

That shouldn't change whether or not a package builds.

**Comment by quyse** [comment]
> This seems relevant: https://discourse.nixos.org/t/breaking-changes-announcement-for-unstable/17574/40?page=2

Yeah, my nightly session of bisecting for `trueseeing` pointed to 8f3162f83fcccf26bf50c55ff960fd2dee5264b2, which is from #271586. I guess affected packages do have to be fixed one-by-one manually.
