### ISSUE TITLE
Build failure: mysql-workbench

### ISSUE THREAD

**Issue by toast003** [NixOS/nixpkgs#281112]
### Steps To Reproduce

1. Build `mysql-workbench`

### Build log

https://gist.github.com/toast003/1c61ab22758f4fe72e53e998ea6b63df

### Additional context

Stumbled upon this when upgrading my NixOS flake from 317484b1ead87b9c1b8ac5261a8d2dd748a0492d to 9b19f5e77dd906cb52dade0b7bd280339d2a1f3d

### Notify maintainers
No maintainers so I'll just ping the last person to touch this 
@khaneliman 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.52-valve14, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Okay, I managed to fix the build, will open a PR shortly.

**Comment by nhasian** [comment]
Thank you for writing the fix and creating the PR. Is something holding up the pull request? It's been open for over a week now.

**Comment by TomaSajt** [comment]
I guess noone really reviewed the PR. I can maybe ask for a review.

**Comment by nhasian** [comment]
I tried building mysql-workbench again today but it is still failing. Is it building properly for you? Or is it something on my end?

output of `nix-shell -p nix-info --run "nix-info -m"`

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05pre567746.317484b1ead8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by toast003** [comment]
@nhasian the pr that fixed this hasn't hit nixpkgs-unstable yet, wait until it does.

You can check here https://nixpk.gs/pr-tracker.html?pr=281207
