### ISSUE TITLE
Package request: vesktop with openasar

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#281108]
**Vesktop - An alternate client for Discord with Vencord built-in. OpenAsar boosts Discord performance and doesn't require additional configuration (drop-in replacement of the original `app.asar`).**

Package for the original Vesktop already exists in `nixpkgs`: [vesktop/package.nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ve/vesktop/package.nix#L164)
I with there would be an alternative package with the [OpenAsar](https://github.com/GooseMod/OpenAsar) included.

**Metadata**

* homepage URL: https://github.com/Vencord/Vesktop, https://openasar.dev
* source URL: https://github.com/Vencord/Vesktop, https://github.com/GooseMod/OpenAsar
* license: GPL v3.0 (Vesktop), AGPL v3.0 (OpenAsar)
* platforms: x86_64-linux, aarch64-linux

---

Pinging here the maintainers of the original package:
@getchoo @Scrumplex @vgskye @pluiedev 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vgskye** [comment]
I don't think this is a sensible or possible thing to do? Vesktop is already a complete reimplementation of discord's native parts, which is what OpenAsar changes

**Comment by LennyLizowzskiy** [comment]
Ok, sorry for ping if that's the case
