### ISSUE TITLE
Mullvad VPN block all connections when install as NixOS service

### ISSUE THREAD

**Issue by ajmasia** [NixOS/nixpkgs#281102]
### Describe the bug
I have updated my configuration flake to the latest version of nixpkgs unstable. When using the mullvad-vpn service, it becomes impossible to access both the local network and the internet. Mullvad blocks all connections and they are only possible if you connect to the VPN

github:NixOS/nixpkgs/9b19f5e77dd906cb52dade0b7bd280339d2a1f3d

### Steps To Reproduce
1. Enable mullvad-vpn service in my config using mullvad-vpn package
```nix
    mullvad-vpn = {
      enable = false;

      package = pkgs.mullvad-vpn;
    };
```
2. Rebuild system
3. Imposible access to local network and internet

### Expected behavior
System can access to my networks and internet

### Additional context
I'm using nix falkes with unstable nixpkgs

### Notify maintainers

@Br1ght0ne @ymarkus @ataraxiasjel @arcuru

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 24.05 (Uakari), 24.05.20240113.9b19f5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(ajmasia): `"home-manager-22.11.tar.gz"`
 - channels(root): `"nixos-22.11, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Lowdude** [comment]
I am likely encountering the same issue, WiFi appears to be connecting as usual, but I cannot reach any websites and pinging and IP returns `ping: sendmsg: Operation not permitted`. I can, however, connect to Mullvad using `mullvad connect` and access websites etc. that way. Unfortunately cache.nixos.org cannot be reached at all, so I can't rebuild the system and simply stopping the mullvad-daemon service has not helped, so for now I am still stuck with a broken system.

**Comment by ajmasia** [comment]
@Lowdude I had to deactivate the service after upgrading this morning :cry:

**Comment by dotlambda** [comment]
> delete or move the systemd unit file under `/nix/store/7l325vpmx...-unit-mullvad-daemon.service/mullvad-daemon.service`

Don't modify the store by hand!
Doesn't stopping the systemd service have the same effect?

**Comment by Lowdude** [comment]
@dotlambda No, weirdly enough stopping the service did not have any effect on the problem. And masking or disabling the service was also not possible, at least not using the conventional methods, so I went for the drastic approach.

**Comment by ajmasia** [comment]
In my case I disabled the service in the configuration and built a new generation :blush:

**Comment by arcuru** [comment]
I'm guessing this occurred when you updated past #277268? I'm guessing it might have altered some of your settings.

In the mullvad gui, under VPN settings, what do you have set for:
1. Local Network Sharing
2. Lockdown mode

You probably want Local Network Sharing -> Enabled and Lockdown mode -> Disabled.

**Comment by ajmasia** [comment]
Great @arcuru, changing thats settings works fine! :muscle:

**Comment by ParetoOptimalDev** [comment]
> I'm guessing this occurred when you updated past #277268? I'm guessing it might have altered some of your settings.
> 
> In the mullvad gui, under VPN settings, what do you have set for:
> 
>     1. Local Network Sharing
> 
>     2. Lockdown mode
> 
> 
> You probably want Local Network Sharing -> Enabled and Lockdown mode -> Disabled.

I've never had the mullvad gui installed but this issue seems to have happened anyway. I'm updating to newest unstable now and will see if that fixes things. Otherwise I'll try:

- checking lockdown mode and local network sharing are disabled with the cli (if possible)
- install the gui and disable lockdown mode/local network sharing

Perhaps a default changed with lockdown mode or local network sharing and that's what broke things for me recently.

**Comment by AlexChalk** [comment]
> Use a live boot stick of whichever distro you have at hand...

Simpler is
- Hit e on the bootloader menu.
- Hit Ctrl+e (to go to end of prompt) and type ` rescue` (with space).
- Enter sudo password when prompted.
- Run systemctl start network-online.target.
- You can then rebuild without mullvad and reboot.
(https://github.com/NixOS/nixpkgs/issues/314694)

**Comment by Titaniumtown** [comment]
Recently started happening again on latest unstable. SOO annoying.

**Comment by ParetoOptimalDev** [comment]
You can use this to see if lockdown mode is on using the cli app if you don't have the gui:

```
mullvad lockdown-mode get
```

Then you can use this to enable or disable:

```
mullvad lockdown-mode set <value>
```

**Comment by BlueDrink9** [comment]
NixOS option to prevent this happening again/make lockdown mode at least vaguely declarative

```nix
  system.activationScripts.noMullvadLockdown = {
    supportsDryActivation = true;
    text = ''
        if [ "$NIXOS_ACTION" = 'dry-activate' ]; then
          echo "Dry run: mullvad lockdown-mode off"
        else
          ${pkgs.mullvad}/bin/mullvad lockdown-mode set off
        fi
    '';
  };
```
