### ISSUE TITLE
KolourPaint's can not browser the system files (Cannot talk to klauncher)

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#28113]
Hi,

I am using KolourPaint (Version 17.04.2). When I want to save an image file, it can not open the file-chooser (file-browser) popup. It gives this error:

"Unable to create io-slave. Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files"

I re-install completely KolourPaint but the same problem still exist. The %90 same problem exist also for KDE's default file browser (Dolphin).

What should I try to solve this problem?

Thank you 

System info:
Ubuntu 16.04 64 bit (Unity desktop as default)
Nix - latest stable

**Comment by olejorgenb** [comment]
Are you running kde plasma, or some other WM/DM? Might be related to https://github.com/NixOS/nixpkgs/issues/27334 ?

**Comment by TerkiKerel** [comment]
@olejorgenb No. I am using Ubuntu 16.04 (64 bit). Everything is default. I did not installed or removed any apps on system. I only use nix apps. I dont have any KDE app, or KDE desktop or something... I don't have installed or removed any  WM or DM yet.

Note1 : Ubuntu 16.04 uses Unity Desktop. Unity is a gnome3 based Desktop.

Note 2: On my old computer I had the same issue. But I was using Ubuntu Gnome 16.04 (64 bit). It use Gnome (3) Shell desktop. Now I don't have my old computer. I use only the new one.

**Comment by TerkiKerel** [comment]
I still have this problem. I can not use KDE apps only this reason.

It would be great if somebody can suggest anything to try.

**Comment by TerkiKerel** [comment]
Somebody please help me here :/ 

I can try anything you want to solve this issue...

**Comment by olejorgenb** [comment]
@TerkiKerel My best suggestion is to find out which kde service/program that supplies the org.kde.klauncher5 service (that is probably a dbus service). Maybe there is some env variable that determines where kde looks for .service files too.

I still have to problem here on NixOS running gnome. File dialogs in kde apps does not work. The kde app I use regularly is okular though, so it doesn't bother me enough to research. I'll make sure to post here if I find out somthing in the future though.

**Comment by TerkiKerel** [comment]
@olejorgenb thank you for your interest. Just for a note: If you need something for testing I can do it. If you wish I can try to install other PACKAGES by nix-env. For example; I tried already "kde4.kde_baseapps" package.

**Comment by TerkiKerel** [comment]
Today, I update all nix packages. I tried KolourPaint 17.12.0. the file dialog works properly.

But the KRename's file dialog does not work. it gives the same problem: "Unable to create io-slave. Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files"

I don't know how it fixed, but can somebody fix the same error for KRename?

Note: If any test will need. Please write me. I can help.

**Comment by TerkiKerel** [comment]
I try on a new computer with ubuntu 18.04. The problem has been fixed also for Krename.

Thank you
