### ISSUE TITLE
Build failure: poetry

### ISSUE THREAD

**Issue by arichtman** [NixOS/nixpkgs#281184]
### Steps To Reproduce

1. build `poetry` on x86_64-darwin

### Build log

[gist link](https://gist.github.com/arichtman/55a5328eb17bb5c786cf7a575e96cbf6)

### Additional context

Broken commit: `2f076b5178287f8e8a6f989435fd9f5ac6e94074`
Working commit: `eabe8d3eface69f5bb16c18f8662a702f50c20d5`

### Notify maintainers

@jakewaksbaum @dotlambda 

### Metadata

```console
[user@system:~]$  nix-info -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"darwin"`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aaronmondal** [comment]
Same on `x86_64-linux`.

```
OK
/build/source
Finished executing pypaBuildPhase
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for poetry-1.7.1-py3-none-any.whl
  - fastjsonschema not installed
  - platformdirs<4.0.0,>=3.0.0 not satisfied by version 4.0.0
```

**Comment by aaronmondal** [comment]
Ah apparently already fixed on `master` https://github.com/NixOS/nixpkgs/issues/281034
