### ISSUE TITLE
Missing dependent packages for incus

### ISSUE THREAD

**Issue by misumisumi** [NixOS/nixpkgs#281269]
### Describe the bug
When `incus` tries to create a volume of type=block, it cannot be created due to the occurrence of `exec: "chattr": executable file not found in $PATH"`.
This is because `e2fsprogs` is not registered in `PATH`.

### Steps To Reproduce
1. run `incus storage create test btrfs`
2. run `incus storage volume create test vol-block-test --type block`

### Expected behavior
Create block type volume.

### Additional context
If you check nixpkgs for lxd 5.20, you can see other package dependencies that are not present in incus.
For example with lvm, this is expected to severely impact the lvm backend.
(Currently, it cannot be confirmed because there is no lvm drive.)
Can we change it in the same way as lxd?

### Notify maintainers
@aanderse
@adamcstephens 
@jnsgruk
@megheaiulian
@mkg20001

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.10, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Opened a PR to fix. Sorry about that. Not sure why I dropped these...
