### ISSUE TITLE
Running nix on OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by lovek323** [NixOS/nixpkgs#2812]
I'm not sure where to put this documentation, but I was having trouble building things on the new OS X 10.10 developer preview. I was able to solve this by running the following:

```sh
sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MACOSX10.9.sdk/usr/include /usr/include
sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MACOSX10.9.sdk/usr/lib/crt1.* /usr/lib/
```

Just thought I'd share this in case anyone else was having problems.

**Comment by gridaphobe** [comment]
The new darwin stdenv compiles `libid3tag` without issues, and shouldn't require any of the fiddling described here :)
