### ISSUE TITLE
plocate prints results twice with default configuration

### ISSUE THREAD

**Issue by bcc32** [NixOS/nixpkgs#281271]
### Describe the bug
Using more-or-less the default configuration for `services.locate` (with `package = pkgs.plocate`), the list of results is printed twice whenever running `locate`.

For example:

```
$ locate etc/shadow
/etc/shadow
/etc/shadow-
/etc/shadow
/etc/shadow-
```

### Steps To Reproduce
1. Enable the `locate` module like so:

```
  services.locate = {
    enable = true;
    package = pkgs.plocate;
    localuser = null;
    # prunePaths = options.services.locate.prunePaths.default ++ [ "/mnt/pool" ];
  };
```

2. Run the `update-locatedb` job
3. Run `locate PATTERN` with some file name that exists on the system

### Expected behavior
Matching files should each be printed once.

### Additional context
The issue is fixed if I unset the `LOCATE_PATH` environment variable.

plocate deliberately reads from **both** `LOCATE_PATH` and the hard coded default path, even if they are the same:

```cpp
	if (dbpaths.empty()) {
		// No -d given, so use our default. Note that this happens
		// even if LOCATE_PATH exists, to match mlocate behavior.
		dbpaths.push_back(DBFILE);
	}
```

The comment claims that this is also the behavior of mlocate, but I do not have an mlocate database installed and haven't wanted to change my running system to use mlocate.

It looks like `LOCATE_PATH` recently started being set in NixOS in #258575.

### Notify maintainers

@SuperSandro2000 @K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
aaron@nyc ~
❯ nix shell 'nixpkgs#nix-info' -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20240113.428544a`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(aaron): `""`
 - nixpkgs: `not found`
```

**Comment by SuperSandro2000** [comment]
Sounds to me like an upstream issue. Can you write a mail to the upstream maintainer? https://git.sesse.net/?p=plocate;a=blob;f=README;h=2a8625aacbc31383cebf7a797b6a7876b15f3850;hb=HEAD#l40

**Comment by bcc32** [comment]
The plocate maintainer says they do not consider this to be a bug in plocate, and is intentional behavior.  Rather than setting the environment variable, could we just make a wrapper script for `plocate` that uses the NixOS-configured dbpath, if we don't want to re-build `plocate` itself when the path is changed?

**Comment by SuperSandro2000** [comment]
I would be personally fine to just drop support for a custom place for the db. If people really want to have it somewhere else they could symlink it. Then we don't need a wrapper or to worry about the env.

**Comment by wamserma** [comment]
> The comment claims that this is also the behavior of mlocate, but I do not have an mlocate database installed and haven't wanted to change my running system to use mlocate.

I can confirm the behaviour with `mlocate`.

**Comment by neilmayhew** [comment]
Could we just take out the variable setting? It isn't needed for `mlocate` or `plocate`, and just causes this annoying behaviour. If it's needed for `locate`, maybe the setting could be made conditional.

It would be nice to get something done about it sooner rather than later. This issue has been open for 4 months now.

**Comment by SuperSandro2000** [comment]
Please take a look at https://github.com/NixOS/nixpkgs/pull/318919

**Comment by neilmayhew** [comment]
I've reviewed the PR and it LGTM. Thanks for doing this! It will be great to have this fixed.
