### ISSUE TITLE
Update request: write_stylus sha256 changed

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#281368]
- Package name: write_stylus
- Latest released version: 300
- Current version on the unstable channel: 300
- Current version on the stable/release channel: 300
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Also, the download link should be moved to `http://www.styluslabs.com/write/write-latest.tar.gz`. The original download link is an old version. The hash should be `sha256-1dy3r4akvehDybZ3ncC5k0BmZsL/K9EQYsdVMtPWocA=` as on 2024-01-18. Strangely the download link does not support HTTPS when downloaded using curl. It does support HTTPS when I clicked on the link in browser.

**Notify maintainers**
@oyren 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
It builds fine for me. We cannot move the download link to `http://www.styluslabs.com/write/write-latest.tar.gz` anyway, since that would change once a new version is released.

**Comment by UlyssesZh** [comment]
We can use archive.org link (though currently archive.org is down).

**Comment by FliegendeWurst** [comment]
No need. The more specific `http://www.styluslabs.com/write/write300.tar.gz` works.

**Comment by UlyssesZh** [comment]
The developer updates the software without updating the version number.
