### ISSUE TITLE
Build failure: mongodb-4_4

### ISSUE THREAD

**Issue by qubitnano** [NixOS/nixpkgs#281416]
### Steps To Reproduce

``git checkout c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370``
``nix build --impure .#mongodb-4_4``

### Build log

```
error: builder for '/nix/store/75hslk6nvmfryrjxy0k27nsmqakir8dd-mongodb-4.4.27.drv' failed with exit code 1;
       last 10 log lines:
       > Checking if std::atomic<int64_t> works... yes
       > Checking if std::atomic<uint64_t> works... yes
       > Checking if std::atomic<int32_t> works... yes
       > Checking if std::atomic<uint32_t> works... yes
       > Checking for extended alignment 64 for concurrency types... yes
       > Checking for mongoc_get_major_version() in C library mongoc-1.0... no
       > configuring module: enterprise
       > Checking for C++ header file net-snmp/net-snmp-config.h... no
       > Could not find <net-snmp/net-snmp-config.h>, required for enterprise build.
       > See /build/mongodb-src-r4.4.27/build/scons/config.log for details
       For full logs, run 'nix log /nix/store/75hslk6nvmfryrjxy0k27nsmqakir8dd-mongodb-4.4.27.drv'.
```

### Additional context

nixos-unstable c3e128f3c0ecc1fb04aef9f72b3dcc2f6cecf370

### Notify maintainers

@bluescreen303  @offlinehacker 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.11, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qubitnano** [comment]
So 4.4.27 builds these enterprise modules by default now. Including``net-snmp`` and ``openldap`` fixed the build, but I'm not sure what these enterprise modules actually do and I can't find this in the release notes.

Adding ``"--modules="`` to sconFlags seems to disable these modules (still building) (default appears to be``"--modules=enterprise"``). Maybe these two can be added as optional to override if someone wants these built?

**Comment by hughobrien** [comment]
I suspect it's here https://github.com/mongodb/mongo/commit/571369c1fd3962d79565cd10f0406ddfb62c16b7

**Comment by hughobrien** [comment]
My gut feeling is that giving it some new, relatively standard libraries is less brittle than trying to override the modules setting and keep track of how that evolves.
