### ISSUE TITLE
libsigcxx: do not export "-std=c++11" via pkg-config

### ISSUE THREAD

**Issue by marvin2k** [NixOS/nixpkgs#28149]
The values contained in the "Cflags" variable of a `.pc` file, like `-std=c++11` as added in [this](https://github.com/NixOS/nixpkgs/blob/83f8ffb11d0a229873d6e4895865a1eed11aa1f0/pkgs/development/libraries/libsigcxx/default.nix#L15) patch, will be added to C_FLAGS by CMakes `pkg-config` module. `gcc` is happily tugging along, but `clang` will complain fatally:
```text
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
```
so maybe skip this patch? See also [gnome](https://bugzilla.gnome.org/show_bug.cgi?id=755750#c19) and [debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800399). Note: I did not buildtest anything, just debugged my problem ;-)

**Comment by jtojnar** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/commit/157332d66664cca006abeef472a254f261074293
