### ISSUE TITLE
Quartus Lite Missing Dependency

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#281402]
Any network related option like `feedback` on Quartus fails with the following error:
```shell
XPCOMGlueLoad error for file /nix/store/fsbnm1zzj87ahajdhnqcp5p0w5aii4a7-firefox-121.0/lib/firefox/libmozsandbox.so:
/nix/store/q4flsi0gjzj53gixfmqhihlnv54flpn6-quartus-prime-lite-unwrapped-22.1std.2.922/quartus/linux64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /nix/store/fsbnm1zzj87ahajdhnqcp5p0w5aii4a7-firefox-121.0/lib/firefox/libmozsandbox.so)
Couldn't load XPCOM.
```
Which tells me quartus can not communicate with firefox for some reason. 

### Steps To Reproduce
1. Install quartus-prime-lite
2. From toolbar click help
3. Click on feedback

### Expected behavior
Open a feedback form.

### Additional context
It is not a deal-breaker for me however there might be other users affected by it since IP store might also not work. Though, I haven't tested it.

### Notify maintainers
@kwohlfahrt 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240108.317484b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bjornfor** [comment]
AFAIR, `quartus` itself sets `$LD_LIBRARY_PATH` which breaks web-browsers it spawns from the host OS later on.

https://github.com/NixOS/nixpkgs/pull/280121#issuecomment-1885766140 might help.

**Comment by hakan-demirli** [comment]
@bjornfor I am not sure if this is the right place the ask it but I wonder if it would be acceptable to add an option to disable/enable quartus and questa. 
Most of the time I only need questa and I used to install it alone when I was on Arch. I am thinking something like this:
```nix
           (pkgs.quartus-prime-lite.override {
             installQuesta = True;
             installQuartus = False;
           })
```
Would something like this be acceptable if I cook up a PR?

**Comment by bjornfor** [comment]
> Would something like this be acceptable if I cook up a PR?

Sounds fine to me. I guess there's some big closure size reductions to be had here?

**Comment by hakan-demirli** [comment]
Yea, Questa is only 2 GBs. I am trying to save some space 😅. Maybe instead I could buy a bigger SSD.
