### ISSUE TITLE
Cosmic Terminal uses software rendering as opposied to GPU rendering

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#281423]
### Describe the bug
Cosmic Terminal uses software rendering as opposied to GPU rendering, like it should since it's based on Alacritty. I think this is due to some package not being built along-side Cosmic Terminal. This could be a issue on the Cosmic side, but it seems very likely to be a Nix issue

### Steps To Reproduce
1. Install Cosmic Terminal
2. Open it
3. See that it doesn't appear in nvtop
4. See that it maxes out one core doing anything remotely intensive e.g. selecting text, opening btop, etc. 

### Expected behavior
It uses the GPU and runs decently well even if slightly worse than base Alacrity

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/45698918/cb4fa11a-521b-471a-a4af-d983a8c97546)

### Notify maintainers
@ahoneybun @cole-h 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ahoneybun** [comment]
Thanks for the report @nonetrix ! I believe I see what you mean as well since I don't see it in `nvtop` either.

**Comment by ahoneybun** [comment]
So the issue is this:

```
[2024-01-17T18:46:40Z DEBUG wgpu_core::instance] Instance::new: failed to create Vulkan backend: InstanceError { message: "missing Vulkan entry points", source: Some(LibraryLoadFailure(DlOpen { desc: "libvulkan.so.1: cannot open shared object file: No such file or directory" })) }
[2024-01-17T18:46:40Z DEBUG wgpu_core::instance] Instance::new: failed to create Gl backend: InstanceError { message: "unable to open libEGL", source: Some(Library(DlOpen { desc: "libEGL.so: cannot open shared object file: No such file or directory" })) }
```

Working on fixing it but it seems to be a challenge on NixOS.

**Comment by nonetrix** [comment]
Also the software rendering is super slow, much slower than I would imagine but it's a fallback for a reason. But it definitely could be improved I think since terminals that solely rely on software are much faster e.g. st, foot, xterm, urxvt, libvte(?), etc. I could see it being a issue in VMs perhaps, might not be worth fixing though depends

**Comment by ahoneybun** [comment]
Alright it is fixed in NixOS with this PR: https://github.com/NixOS/nixpkgs/pull/280548

With that said it does not work in Pop!_OS with that change.

**Comment by ahoneybun** [comment]
Screenshot of course :)

![Screenshot from 2024-01-18 13-38-43](https://github.com/NixOS/nixpkgs/assets/4884946/ec17c6cd-2c8a-4f0a-9fac-fc290187ef13)

**Comment by nonetrix** [comment]
Oh sorry I didn't see this until today, yes it did :-)
