### ISSUE TITLE
armcord: missing icon

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#281418]
### Describe the bug
ArmCord package in Nix lacks of `armcord` icon that is called by `armcord.desktop` file. Can you please introduce it in the package?

### Steps To Reproduce
1. Install ArmCord
2. Check Menu or call ArmCord to check there is no icon

### Expected behavior
ArmCord application should show its icon.

### Notify maintainers
@LudovicoPiero @wrmilling 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.68, Athena OS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Can you provide a screenshot of where you expect the icon? Shows up fine on my system

**Comment by LudovicoPiero** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/44255157/ee987d7f-c977-4c74-a665-25810c752886)

Tested with fuzzel, it's showing the icon :/

**Comment by D3vil0p3r** [comment]
Solved. I was linking wrong dir.
