### ISSUE TITLE
fail2ban's docs install to wrong path

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#28145]
```
$ find $(nix-build --no-out-link '<nixpkgs>' -A fail2ban) -name doc
/nix/store/kj7viccl6yfvrvdl45dnyg7l98iw2j1y-fail2ban-0.9.6/usr/share/doc
```

I think this should be installed to `$out/share/doc` rather than `$out/usr/share/doc`.

## Technical details
- System: 17.03.1645.08bc48049c (Gorilla)
- Nix version: nix-env (Nix) 1.11.13
- Nixpkgs version: "17.03.1645.08bc48049c"
- Sandboxing enabled:  true

**Comment by lheckemann** [comment]
Thanks @pSub!

**Comment by pSub** [comment]
You're welcome!
