### ISSUE TITLE
Build failure: chadwm

### ISSUE THREAD

**Issue by erikdubois** [NixOS/nixpkgs#281587]
### Steps To Reproduce

{ config, pkgs, ... }:

{
  #services.xserver.displayManager.defaultSession = "none+dwm";
  services.xserver.windowManager.dwm.enable = true;
  nixpkgs.overlays = [
    (final: prev: {
      dwm = prev.dwm.overrideAttrs (old: { src = /home/erik/.config/arco-chadwm/chadwm ;});
    })
  ];
}

### Build log

How to log?
Here is an image
![image](https://github.com/NixOS/nixpkgs/assets/10594806/45dec3b6-fffa-4be2-a04c-79b73aaa82d4)

### Additional context

Arch Linux has a file called Imlib2.h
Nixos does not have that file

referring to this file will break the build
https://github.com/erikdubois/nixos-configurations/blob/b3cbdfeb169f7e1ccee9f093afff56e7a57c1c70/dotfiles/.config/arco-chadwm/chadwm/drw.c#L7

### Notify maintainers

I think the maintainer is empty
https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/libraries/imlib2/default.nix#L76

### Metadata

![image](https://github.com/NixOS/nixpkgs/assets/10594806/66da6efc-d7e3-421d-9a64-aa7a2b9e040c)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by skver0** [comment]
The dwm package does not have Imlib2 as a package dependency, this is not a dwm or Imlib2 package related issue. 
Look into [overriding](https://ryantm.github.io/nixpkgs/using/overrides/) to include Imlib2 as a dependency for dwm.

**Comment by erikdubois** [comment]
I do believe Imlib2 is installed but we are missing a file imlib2.

If you download the imlib2 package from deepin sourceforge and extract it we see it is part of the scr/lib files

![image](https://github.com/NixOS/nixpkgs/assets/10594806/2042e239-5443-4fc9-bd7e-8dfdee141ade)

When I try to find this file on NixOS I can not find it.

I thought I should change the path to the folder/file. But if there is no imlib2.h file.

![image](https://github.com/NixOS/nixpkgs/assets/10594806/fffb3ca2-3439-4555-87c3-4e000fedc944)

**Comment by eclairevoyant** [comment]
No, that is not how you install libraries, you must override the package itself that needs it.

**Comment by erikdubois** [comment]
and the fact that imlib2 is missing a file is not the issue?

**Comment by eclairevoyant** [comment]
Nothing would be missing if the package was correctly overridden, `Imlib2.h` is present in the .dev output, which is correctly picked when you add `imlib2` to the `buildInputs` of the package.

**Comment by erikdubois** [comment]
I think I know what you mean.
Since this is too difficult for me I have requested this package.
https://github.com/NixOS/nixpkgs/issues/282239
I will close this issue for now.
