### ISSUE TITLE
Build failure: azure-cli

### ISSUE THREAD

**Issue by CryoMyst** [NixOS/nixpkgs#281545]
### Steps To Reproduce

1. build *azure-cli* against unstable or master
`nix build --expr '(import (builtins.getFlake "github:nixos/nixpkgs/e862ac6b5ca280d3e41db71467f129839e47ee45") { system = "x86_64-linux"; }).azure-cli'`

### Build log

https://gist.github.com/CryoMyst/63c121d42ac865809e950d90c1410384

### Notify maintainers

@AkechiShiro @jonringer

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20240113.9b19f5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
We're aware of the issue and working on fix #281213 it will be soon merged hopefully and 2.56.0 is failing to pass some tests, we're also investigating and aware (see #281183)
