### ISSUE TITLE
Build failure: pkgsMusl.ponyc

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#281592]
### Steps To Reproduce

1. nix build .#pkgsMusl.ponyc

### Build log

```
[  8%] Completed 'gbenchmark'
[  8%] Built target gbenchmark
make[1]: *** [Makefile:156: all] Error 2
make[1]: Leaving directory '/build/source/build/build_libs'
make: *** [Makefile:171: libs] Error 2
/nix/store/gywylakb2hqf96wjsg4qzh5g63kacyj3-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```
Log file: [pkgsMusl.ponyc-0.54.txt](https://github.com/NixOS/nixpkgs/files/13966965/pkgsMusl.ponyc-0.54.txt)

### Notify maintainers

@kamilchm @patternspandemic @redvers

### PR for marking broken:

* https://github.com/NixOS/nixpkgs/pull/281641

**Comment by redvers** [comment]
Makes sense to me.

It's in need of upgrading to 0.58 so I'll look at putting a PR in for that and, with a bit of luck it may fix the musl issue too.

**Comment by dyercode** [comment]
This error is occurring for me when using as a flake, not just musl. Bumping ponyc to current (0.58.5) fixes for me. I have a PR ready to go if you'd be open to it.

I did smoketest the musl build, it ends up failing with a different error (sorry lost the stdout and build takes hours for me).

**Comment by superherointj** [comment]
> This error is occurring for me when using as a flake, not just musl. Bumping ponyc to current (0.58.5) fixes for me. I have a PR ready to go if you'd be open to it.

Sure. Feel free to propose PR.
