### ISSUE TITLE
Package jetbrains.idea-community installs wrong version

### ISSUE THREAD

**Issue by cornerman** [NixOS/nixpkgs#281648]
### Describe the bug
Installing jetbrains.idea-community from the unstable channel should install version 2023.3.2. But you actually get version 2023.2.2.

### Steps To Reproduce
1. nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
2. nix-env -iA nixos-unstable.jetbrains.idea-community

### Expected behavior
Expected this to install idea version 2023.3.2.

### Screenshots

```console
$ nix-env -iA nixos-unstable.jetbrains.idea-community
installing 'idea-community-2023.3.2'
building '/nix/store/gcazizq0cmykn9a8nz1wgcl4spdq82lk-user-environment.drv'
```

```console
$ idea-community --version
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
IntelliJ IDEA 2023.2.2 (Community Edition)
Build #IC-232.9921.47
```

```console
$ ls -l $(which idea-community)
lrwxrwxrwx 4 root root 86  1. Jan 1970  /home/cornerman/.nix-profile/bin/idea-community -> /nix/store/1rq8h8zf6l3nxrb7vn3r2000hzrlgb7d-idea-community-2023.3.2/bin/idea-community*
```

### Notify maintainers
@edwtjo @gytis-ivaskevicius @steinybot @AnatolyPopov @tymscar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.11, NixOS, 23.11 (Tapir), 23.11.2962.b8dd8be3c790`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(cornerman): `"nixos-stable-23.11, nixos-unstable"`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by h7x4** [comment]
I'm having a hard time reproducing this. Could you try `nix-channel --update` and verify that it's still an issue?

**Comment by cornerman** [comment]
@h7x4 I just tried, and it still does the same thing. It downloads idea-community labelled as version 2023.3.2. But when running `idea-community --version`, I get `2023.2.2`. Anything. I can reproduce the same inside a nix-shell.

**Comment by kirillrdy** [comment]
@cornerman try

```
nix-shell -p  jetbrains.idea-community -I nixpkgs=https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
this path will be fetched (360.78 MiB download, 1644.39 MiB unpacked):
  /nix/store/gq5ygqf5rafaaxm9jz511s0h3may4mgf-idea-community-2023.3.2
copying path '/nix/store/gq5ygqf5rafaaxm9jz511s0h3may4mgf-idea-community-2023.3.2' from 'https://cache.nixos.org'..

```

**Comment by cornerman** [comment]
@kirillrdy Oh thank you. That actually works correctly. I somehow messed up my nixpkgs configuration. Sorry for the trouble!

**Comment by Arguggi** [comment]
@h7x4 I'm actually having the same issue, now with version `2023.3.2` showing up instead of the intended `2024.1.1`
```
> nix-shell -p jetbrains.idea-community -I nixpkgs=https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
[nix-shell:~]$ which idea-community
/nix/store/ll93s0g80bbf7pbkqk6ca30dglazpg0w-idea-community-2024.1.1/bin/idea-community
[nix-shell:~]$ idea-community --version
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103
```
Not sure if I messed something up somehow, but this happens both on nixos pc and a different ubuntu laptop.

**Comment by cornerman** [comment]
@Arguggi Just stumbled over this problem as well and a friend of mine as well. What we did now is installing the `jetbrains.idea-community-bin` package instead, which works as expected.

So, it seems to me, that something might be actually broken this time.
