### ISSUE TITLE
ffmpeg: enable vulkan video by default

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#281631]
### Describe the bug

Ffmpeg 6.1 supports vulkan video, but it is not enabled in the default version of ffmpeg, it is only enabled in ffmpeg-full.
The default version of ffmpeg should support vulkan video so that applications like mpv can use it. Arch enables vulkan by [default](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/main/PKGBUILD?ref_type=heads#L218).

Vulkan video already works with amd GPUs using ffmpeg-full with this command:
```
RADV_PERFTEST=video_decode ffmpeg -init_hw_device "vulkan=vk:0" -hwaccel vulkan -hwaccel_output_format vulkan -i INPUT -f null - -benchmark
```

### Notify maintainers

 @Atemu @arthsmn 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
This seems reasonable. I'm in favor.

**Comment by Atemu** [comment]
Hm, your command doesn't work for me on Mesa 23.3.3:

```
Device creation failed: -12.
Failed to set value 'vulkan=vk:0' for option 'init_hw_device': Cannot allocate memory
Error parsing global options: Cannot allocate memory
```

Another aspect to consider is closure size.

**Comment by Tungsten842** [comment]
> Hm, your command doesn't work for me on Mesa 23.3.3:
> 
> ```
> Device creation failed: -12.
> Failed to set value 'vulkan=vk:0' for option 'init_hw_device': Cannot allocate memory
> Error parsing global options: Cannot allocate memory
> ```
> 
> Another aspect to consider is closure size.

If you haven't tried already, can you try with something in h264? Vulkan video currently only supports h264, h265 and av1(experminental) only if you gpu supports them.

**Comment by Atemu** [comment]
Indeed it's h.265, let me try h.264. This looks like a generic VK issue though.

**Comment by Atemu** [comment]
As suspected, this happens on h.264 too.

**Comment by Tungsten842** [comment]
> As suspected, this happens on h.264 too.

Do you have multiple GPUs in your system except the amd one perhaps? This chooses the first one arbitrarily.

**Comment by Atemu** [comment]
```
$ vulkaninfo --summary
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 5.  Skipping ICD.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.268


Instance Extensions: count = 23
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 15
---------------------------
VK_LAYER_INTEL_nullhw               INTEL NULL HW                 1.1.73   version 1
VK_LAYER_MANGOAPP_overlay           Mangoapp Layer                1.3.0    version 1
VK_LAYER_MANGOAPP_overlay           Mangoapp Layer                1.3.0    version 1
VK_LAYER_MANGOHUD_overlay_32_x86    Vulkan Hud Overlay            1.3.0    version 1
VK_LAYER_MANGOHUD_overlay_64_x86_64 Vulkan Hud Overlay            1.3.0    version 1
VK_LAYER_MESA_device_select         Linux device selection layer  1.3.211  version 1
VK_LAYER_MESA_overlay               Mesa Overlay layer            1.3.211  version 1
VK_LAYER_OBS_vkcapture_32           OBS Linux game capture        1.3.268  version 1
VK_LAYER_OBS_vkcapture_64           OBS Linux game capture        1.3.268  version 1
VK_LAYER_TORKEL104_libstrangle      Libstrangle framerate limiter 1.1.125  version 1
VK_LAYER_TORKEL104_libstrangle      Libstrangle framerate limiter 1.1.125  version 1
VK_LAYER_VALVE_steam_fossilize_32   Steam Pipeline Caching Layer  1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64   Steam Pipeline Caching Layer  1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32     Steam Overlay Layer           1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64     Steam Overlay Layer           1.3.207  version 1

Devices:
========
GPU0:
        apiVersion         = 1.3.267
        driverVersion      = 23.3.3
        vendorID           = 0x1002
        deviceID           = 0x73bf
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = AMD Radeon RX 6800 XT (RADV NAVI21)
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 23.3.3
        conformanceVersion = 1.3.0.0
        deviceUUID         = 00000000-0300-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
        apiVersion         = 1.3.267
        driverVersion      = 23.3.3
        vendorID           = 0x1002
        deviceID           = 0x164e
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 23.3.3
        conformanceVersion = 1.3.0.0
        deviceUUID         = 00000000-1100-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU2:
        apiVersion         = 1.3.267
        driverVersion      = 0.0.1
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 16.0.6, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 23.3.3 (LLVM 16.0.6)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3233-2e33-2e33-000000000000
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```

**Comment by Tungsten842** [comment]
> ```
> $ vulkaninfo --summary
> WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
> WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 5.  Skipping ICD.
> ==========
> VULKANINFO
> ==========
> 
> Vulkan Instance Version: 1.3.268
> 
> 
> Instance Extensions: count = 23
> -------------------------------
> VK_EXT_acquire_drm_display             : extension revision 1
> VK_EXT_acquire_xlib_display            : extension revision 1
> VK_EXT_debug_report                    : extension revision 10
> VK_EXT_debug_utils                     : extension revision 2
> VK_EXT_direct_mode_display             : extension revision 1
> VK_EXT_display_surface_counter         : extension revision 1
> VK_EXT_surface_maintenance1            : extension revision 1
> VK_EXT_swapchain_colorspace            : extension revision 4
> VK_KHR_device_group_creation           : extension revision 1
> VK_KHR_display                         : extension revision 23
> VK_KHR_external_fence_capabilities     : extension revision 1
> VK_KHR_external_memory_capabilities    : extension revision 1
> VK_KHR_external_semaphore_capabilities : extension revision 1
> VK_KHR_get_display_properties2         : extension revision 1
> VK_KHR_get_physical_device_properties2 : extension revision 2
> VK_KHR_get_surface_capabilities2       : extension revision 1
> VK_KHR_portability_enumeration         : extension revision 1
> VK_KHR_surface                         : extension revision 25
> VK_KHR_surface_protected_capabilities  : extension revision 1
> VK_KHR_wayland_surface                 : extension revision 6
> VK_KHR_xcb_surface                     : extension revision 6
> VK_KHR_xlib_surface                    : extension revision 6
> VK_LUNARG_direct_driver_loading        : extension revision 1
> 
> Instance Layers: count = 15
> ---------------------------
> VK_LAYER_INTEL_nullhw               INTEL NULL HW                 1.1.73   version 1
> VK_LAYER_MANGOAPP_overlay           Mangoapp Layer                1.3.0    version 1
> VK_LAYER_MANGOAPP_overlay           Mangoapp Layer                1.3.0    version 1
> VK_LAYER_MANGOHUD_overlay_32_x86    Vulkan Hud Overlay            1.3.0    version 1
> VK_LAYER_MANGOHUD_overlay_64_x86_64 Vulkan Hud Overlay            1.3.0    version 1
> VK_LAYER_MESA_device_select         Linux device selection layer  1.3.211  version 1
> VK_LAYER_MESA_overlay               Mesa Overlay layer            1.3.211  version 1
> VK_LAYER_OBS_vkcapture_32           OBS Linux game capture        1.3.268  version 1
> VK_LAYER_OBS_vkcapture_64           OBS Linux game capture        1.3.268  version 1
> VK_LAYER_TORKEL104_libstrangle      Libstrangle framerate limiter 1.1.125  version 1
> VK_LAYER_TORKEL104_libstrangle      Libstrangle framerate limiter 1.1.125  version 1
> VK_LAYER_VALVE_steam_fossilize_32   Steam Pipeline Caching Layer  1.3.207  version 1
> VK_LAYER_VALVE_steam_fossilize_64   Steam Pipeline Caching Layer  1.3.207  version 1
> VK_LAYER_VALVE_steam_overlay_32     Steam Overlay Layer           1.3.207  version 1
> VK_LAYER_VALVE_steam_overlay_64     Steam Overlay Layer           1.3.207  version 1
> 
> Devices:
> ========
> GPU0:
>         apiVersion         = 1.3.267
>         driverVersion      = 23.3.3
>         vendorID           = 0x1002
>         deviceID           = 0x73bf
>         deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
>         deviceName         = AMD Radeon RX 6800 XT (RADV NAVI21)
>         driverID           = DRIVER_ID_MESA_RADV
>         driverName         = radv
>         driverInfo         = Mesa 23.3.3
>         conformanceVersion = 1.3.0.0
>         deviceUUID         = 00000000-0300-0000-0000-000000000000
>         driverUUID         = 414d442d-4d45-5341-2d44-525600000000
> GPU1:
>         apiVersion         = 1.3.267
>         driverVersion      = 23.3.3
>         vendorID           = 0x1002
>         deviceID           = 0x164e
>         deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
>         deviceName         = AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)
>         driverID           = DRIVER_ID_MESA_RADV
>         driverName         = radv
>         driverInfo         = Mesa 23.3.3
>         conformanceVersion = 1.3.0.0
>         deviceUUID         = 00000000-1100-0000-0000-000000000000
>         driverUUID         = 414d442d-4d45-5341-2d44-525600000000
> GPU2:
>         apiVersion         = 1.3.267
>         driverVersion      = 0.0.1
>         vendorID           = 0x10005
>         deviceID           = 0x0000
>         deviceType         = PHYSICAL_DEVICE_TYPE_CPU
>         deviceName         = llvmpipe (LLVM 16.0.6, 256 bits)
>         driverID           = DRIVER_ID_MESA_LLVMPIPE
>         driverName         = llvmpipe
>         driverInfo         = Mesa 23.3.3 (LLVM 16.0.6)
>         conformanceVersion = 1.3.1.1
>         deviceUUID         = 6d657361-3233-2e33-2e33-000000000000
>         driverUUID         = 6c6c766d-7069-7065-5555-494400000000
> ```

Perhaps try with "vulkan=vk:1" or "vulkan=vk:2".

**Comment by Atemu** [comment]
All the same error.

**Comment by Tungsten842** [comment]
> Same error for all.

Then I am not sure about what's causing it, that's the exact same error I receive when using ffmpeg 6.1 instead of ffmpeg-full 6.1.

**Comment by Atemu** [comment]
> that's the exact same error I receive when using ffmpeg 6.1 instead of ffmpeg-full 6.1.

Uhhh about that... So [I had switched back to `ffmpeg` a little while ago](https://github.com/Atemu/nixos-config/commit/d28d8f04d2068b5f52a3efce0cc2c6e39baf1c7b) and that commit didn't seem to have been pulled into this brain thingy of mine...

It works as expected with ffmpeg-full.
