### ISSUE TITLE
inSync produces bwrap: Can't chdir to /etc/nixos: No such file or directory

### ISSUE THREAD

**Issue by tjmcwiz** [NixOS/nixpkgs#281798]
### Describe the bug
inSync doesn't appear to work --- upon executing the command insync returns the message
bwrap: Can't chdir to /etc/nixos: No such file or directory

### Steps To Reproduce
1. Install insync via configuration.nix within the environment.systemPackages section 
2. type in the command insync on  Konsole (with whatever parameters)
3. returns "bwrap: Can't chdir to /etc/nixos: No such file or directory"

### Expected behavior
insync to be reachable and produce error free output 

### Additional context
which insync returns /run/current-system/sw/bin/insync

The directory /etc/nixos does exist 

Caveat: I am new to NixOS so I could have made a newbie mistake ..... I reviewed the open issues so I understand there are some issues with inSync currently but this problem seems different since it looks like the 'install' had issues so that the command doesn't work at all.

### Notify maintainers
@hellwolf 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 23.11 (Tapir), 23.11.2962.b8dd8be3c790`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 23.11 (Tapir), 23.11.2962.b8dd8be3c790`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tjmcwiz** [comment]
Changing the system to make use of a flake (same configuration) avoids this error. Not sure why ..... I'm guessing this is how everyone uses the system anyway so this can probably be closed ....

**Comment by tjmcwiz** [comment]
Some additional information: 
- If your default browser is Google - it will fail to work when doing the authentication step. It seems the Google package when doing this attempts to update google-chrome.desktop which is in the nixos store (which is immutable) . The Mozilla packages works fine and so if that is your default browser - it will work.
- Starting with insync start --no-daemon seems to get things working (syncing) currently as mentioned in other tickets. There is some sort of issue as reported in /etc/mtab #258359 with mtab and there is a fix for it. 
- And as reported in other tickets the icon is missing on the toolbar although you can still click the invisible icon.

**Comment by hellwolf** [comment]
Hi @tjmcwiz thanks for the report. I have been fighting with the package of insync for a while...

I wonder if you would have a chance to try out #279426?

**Comment by hellwolf** [comment]
I believe it has been fixed recently.

FYI: Also, a new package for nautilus users: https://github.com/NixOS/nixpkgs/pull/302422 please give a :+1: for faster merging!
