### ISSUE TITLE
system-config-printer wrapper broken

### ISSUE THREAD

**Issue by disassembler** [NixOS/nixpkgs#28175]
## Issue description

system-config-printer no longer builds on master

### Steps to reproduce

 nix-build -A system-config-printer

## Technical details

Wrappers are now checked before they're created. Likely there is a bug in the code that wants to create the wrapper. (See https://github.com/NixOS/nixpkgs/pull/24944)

* System: 17.09pre111447.a7c8f5e419
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09pre111447.a7c8f5e419"
* Sandboxing enabled: false

**Comment by disassembler** [comment]
@abbradar introduced the wrapper in commit Sun Apr 23 17:08:12 2017 +0300 5565728670 system-config-printer: 1.5.7 -> 1.5.9  [Nikolay Amiantov]

Debugging with @cleverca22 we came to the conclusion $program_PATH isn't set anywhere. I was able to successfully build (although I'm sure it's not in a working state) by removing line 46: `--prefix PATH "$program_PATH"`

**Comment by FRidh** [comment]
This is where `$program_PATH` is supposed to be created:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/wrap.sh#L9

**Comment by globin** [comment]
I think I've fixed this on staging c438fe5a16a16cd8068077df605b377beab786f5
