### ISSUE TITLE
libobjc2 fails to build on NixOS unstable

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#28192]
https://gist.github.com/yegortimoshenko/f9b2d8d610a7fef02bff042bee739d88

To reproduce, build `libobjc2` or `unar`.

## Technical details

* System: 17.09pre111447.a7c8f5e419 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09pre112691.abdb58e407"
* Sandboxing enabled: false

**Comment by matthewbauer** [comment]
I think this is caused by #28223

**Comment by yegortimoshenko** [comment]
Was fixed in #28223.
