### ISSUE TITLE
trezor-suite fails to see device

### ISSUE THREAD

**Issue by sudoforge** [NixOS/nixpkgs#281975]
### Describe the bug

`trezor-suite` launches, but fails to see a connected hardware wallet.

### Steps To Reproduce
1. Install `trezor-suite` (nonfree license)
2. Run `trezor-suite` from a terminal.
3. Plug in a trezor hardware wallet, unlock it, and see that the application does not react to the device being plugged in.

### Expected behavior

I'd expect the application to react to the device being plugged in, and show its dashboard.

### Screenshots

N/A - it just sits on the default "connect your device" screen.

### Additional context

I'm on Wayland.

I've tried different cables and ports. I've installed `trezor-udev-rules`. Nothing changes. The only logs the application emits are below, none of which seem like an obvious culprit to me (unless it's related to the `portal.FileChooser` + xdg-settings errors):

```
$ trezor-suite >&1

# ya'll should probably prioritize security-related warnings
(node:7508) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `trezor-suite --trace-deprecation ...` to show where the warning was created)

# perhaps this is related?
[7508:0118/224649.138220:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[7508:0118/224649.138260:ERROR:select_file_dialog_linux_portal.cc(280)] Failed to read portal version property
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.
xdg-settings: invalid application name
Try 'xdg-settings --help' for more information.

# an initial request on first startup to the tor interface, which hasn't started yet
request-manager: connect ECONNREFUSED 127.0.0.1:35067

# no idea what's going on here
[7550:0118/224651.320307:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[7550:0118/224707.231981:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[7550:0118/224711.234930:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Notify maintainers

@prusnak 

### Metadata

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m      
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20240102.bd645e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/etc/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sudoforge** [comment]
If I connect and unlock my device prior to opening `trezor-suite`, **yes, the page shows a connected device**:

```
$ curl -s http://127.0.0.1:21325/status/ |  htmlq -- '.inner-container > p'
<p>Connected devices: 1</p>
```

If I open `trezor-suite`, and **then** connect and unlock my device, **no, the page does not show a connected device**:

```
$ curl -s http://127.0.0.1:21325/status/ |  htmlq -- '.inner-container > p'

<p>Connected devices: 0</p>
```

---

In both cases, no session is started, and `trezor-suite` sits at the "Connect a device" screen.

**Comment by sudoforge** [comment]
hey @prusnak, i'll be testing this under X within the next week just to rule out Wayland being an issue here. do you have any other recommendations for how to debug this issue?

**Comment by sudoforge** [comment]
@prusnak is there any plan for tackling this _extremely show-stopping bug_? i'm very happy to assist with debugging.

this makes trezor impossible to recommend to other users.

**Comment by prusnak** [comment]
> this _extremely show-stopping bug_?

You said it works when you unlock the device before connecting to the Suite, didn't you?

**Comment by sudoforge** [comment]
> > this _extremely show-stopping bug_?
> 
> You said it works when you unlock the device before connecting to the Suite, didn't you?

No. I said that if I connect and unlock my device prior to opening the suite, the status page shows that a device is connected. The GUI app still sits at the "Connect a device" screen. It is non-functional and emits no logs.

**Comment by sudoforge** [comment]
@prusnak i can appreciate that you're busy. what steps can i take to debug this further? as i've mentioned, there are no logs, output by the GUI application, and this is a show-stopping bug.

**Comment by sudoforge** [comment]
I can confirm that this same issue occurs under X11. Trezor suite is unusable.

**Comment by prusnak** [comment]
I have no idea what might be causing the bug and I cannot investigate because I am travelling without a NixOS machine.

In the meantime there will be a new release of Trezor Suite soon, which I will try to package and we'll test if that did not fix the issue.

If not, I will investigate once I am back (start of March).

**Comment by sudoforge** [comment]
@prusnak I can confirm that the same issue is present with version `24.2.2`  of `trezor-suite`.

**Comment by sudoforge** [comment]
@prusnak are you still lacking access to a nixos machine? i am highly motived to help get this issue fixed. let me know what i need to do to get you the information / tools you need.

so far, the package has been updated several times. it would appear that it is not actually being tested.

**Comment by sudoforge** [comment]
i'd love to debug it, but as a layperson, there isn't much i can do. the application doesn't have any apparent flags or environment variables to help with debugging, there are now useful logs emitted (nor any beyond what i've sent here already), and what you've suggested so far is:

- checking that the `/status` page shows that the device is connected. what i think you're alluding to is that if this page shows the device is connected, trezor-suite should be able to see it. *this is not the case.*
- "try the <new month> update". this is, IMO, not a useful suggestion, without having any sort of relevant fix applied to the tree used to build that new version.

i would love to see, either:

- this issue get addressed, or
- this broken application removed from `nixpkgs`

**Comment by prusnak** [comment]
> * this broken application removed from `nixpkgs`

Being passive aggressive does not make debugging this issue any easier.

**Comment by sudoforge** [comment]
i don't see that as being passive aggressive. the package has, as far as i can tell, been broken since its initial introduction. that doesn't feel like a useful contribution to the nixpkgs repository.

**Comment by JosefKatic** [comment]
I got here since setting this package as broken caused me issues while updating flakes. I have tried to reproduce what you described with my config, since I never had any issue with `trezor-suite`. What I have found out is that just installing `trezor-udev-rules` is not enough. I use `services.trezord.enable = true;` After disabling this, I got into the same situation you described. Please make sure you have `services.trezord.enable` set to true (which also install `trezor-udev-rules`). After enabling it back, everything started to work again.

The package has always been working for me.

**Comment by colemickens** [comment]
Working config:

```nix
{ config, pkgs, ... }:

{
  config = {
    services = {
      trezord = {
        enable = true;
      };
      udev.packages = with pkgs; [ trezor-udev-rules ];
    };
    environment.systemPackages = with pkgs; [
      trezor-suite
      trezorctl
    ];
  };
}
```

**Comment by colemickens** [comment]
It would certainly be nice for trezor-suite to warn the user if the appropriate udev rules or trezord are not found.

**Comment by sudoforge** [comment]
i can confirm that `trezor-suite` now works as expected as of `2726f127c15a4cc9810843b96cad73c7eb39e443` (the revision of `nixpkgs` used in my system flake), with `services.trezord.enable = true;`. i had tested this prior to opening this issue, and it did not work (at that point in time, with the revision i was using in the test environment).

> It would certainly be nice for trezor-suite to warn the user if the appropriate udev rules or trezord are not found.

the `trezor-suite` package [actually installs `trezord`](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/blockchains/trezor-suite/default.nix#L51), but i'm not sure how the appimage utilizes it, if at all. given that it doesn't work without enabling the service on the host  machine, i think it's safe to say that if the appimage _does_ utilize the system `trezord` that it installs, it is  doing so incorrectly.

i definitely think it would benefit end users if, at minimum, the `trezor-suite` package noted the requirement to set `services.trezord.enable = true`.

**Comment by colemickens** [comment]
> i definitely think it would benefit end users if, at minimum, the trezor-suite package noted the requirement to set services.trezord.enable = true.

I can add that to #300561 but I'm not really sure how. Do we have a "installNotes" for meta or something?

**Comment by sudoforge** [comment]
closing as of PR #300561 (commit e0dd3ae0c35f7adf1e24c9e1e8011f30345547aa).

**Comment by sudoforge** [comment]
> I can add that to #300561 but I'm not really sure how. Do we have a "installNotes" for meta or something?

i'm not sure offhand where the appropriate place to put this is. i'd like to see the package handle installing and enabling the service, but that's probably not realistic (e.g. what if it's being installed with home-manager, etc). perhaps just writing it in `description` or `longDescription`? i've seen these sorts of notes in other packages, at least, so it's not strictly a bad idea.

i can send a PR up later after noodling it a bit, if you haven't already gotten around to it.

**Comment by colemickens** [comment]
@sudoforge I'm kinda swamped today, please feel free to take it over, especially since the PR already merged. Your guess is right, there's not much we can do if the user only adds the package to their environment, without activating the actual nixos service and udev rules. I think some sort of notation, somewhere, though, makes sense.

It's clear you tried to find the right path and it wasn't obvious; if we can make that better for others, even in a small way, its seems good.
