### ISSUE TITLE
kpat package missing

### ISSUE THREAD

**Issue by mkocha2** [NixOS/nixpkgs#28209]
## Issue description
Is it possible to have KPatience packaged and built in 17.03?

### Steps to reproduce
Run `kpat`. 

## Technical details
nixos-version 
17.03.1482.1b57bf274a (Gorilla)

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding this package here.
