### ISSUE TITLE
Issue: VentoyGUI missing & no app shortcut created..

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#282036]
After installing `ventoy` or `ventoy-full`, no app shortcut is created in the app menu. **(Rebooting does not fix the problem!)**

`VentoyGUI` seems to be missing completely, I can't even start it from the console.
Check: https://www.ventoy.net/en/doc_linux_gui.html

I am using `Gnome` on the latest `NixOS (23.11)`.

Plus, could someone explain the difference between the two packages?

![Bildschirmfoto vom 2024-01-19 12-35-30](https://github.com/NixOS/nixpkgs/assets/4227548/0d76bbec-abd6-461a-b212-a62ac5d3d527)

**Comment by jackwilsdon** [comment]
The only difference between `ventoy` and `ventoy-full` is that the `-full` version has support for a few additional features: https://github.com/NixOS/nixpkgs/blob/ac9ae3e1f8c1504b2a55ad6b67b4794d56ebc978/pkgs/top-level/all-packages.nix#L2135-L2141

It looks like the GUI isn't enabled for either version, as either `withGtk3` or `withQt5` is required to enable that.

You should be able to enable the GUI in your own version by using:

```nix
# either ventoy-full or ventoy
pkgs.ventoy-full.override {
  # either withGtk3 or withQt5
  withGtk3 = true;
}
```

**Comment by boustanihani** [comment]
Thanks, I managed to do it by adding your code inside round brackets `(...)` inside `systemPackages`. 
Such options should be simply added to the package description directly ( https://search.nixos.org/packages ).
There is no need to make an extra wiki page for such a small **(but also important)** option, do you agree :) ?
```
environment.systemPackages = with pkgs; [

    # either withGtk3 or withQt5
    (pkgs.ventoy.override { withGtk3 = true; })

];
```

**Comment by boustanihani** [comment]
After adding `withGtk3 = true;` an application shortcut was created, but if I click on it nothing happens.
Also if I try to launch from the console, nothing happens. No error messages.
Adding `sudo` does not fix the problem..

![Bildschirmfoto vom 2024-01-19 14-52-19](https://github.com/NixOS/nixpkgs/assets/4227548/932f8e1a-4955-45fb-87e6-7a302d7f7e3e)

![Bildschirmfoto vom 2024-01-19 14-53-49](https://github.com/NixOS/nixpkgs/assets/4227548/3165ac4f-25f8-45df-a3a9-b8f32b505881)

**Comment by boustanihani** [comment]
Idealy, if someone is using `Gnome` (or any GTK based Desktop environment) then `withGtk3` should be enabled automatically and if someine is using `KDE` then `withQt5` should be enabled automatically.

**Comment by boustanihani** [comment]
It would also be nice if `ventoy` & `ventoy-full` are updated to `v1.0.97` :)

Check: https://github.com/ventoy/Ventoy/releases
