### ISSUE TITLE
Package bazecor - included udev rules not working - keyboard incorrectly identified as in bootloader mode

### ISSUE THREAD

**Issue by PhlegmaTREEc** [NixOS/nixpkgs#282095]
### Describe the bug
After installing the ```bazecor``` package and starting the software, my keyboard is still not properly working. Bazecor thinks it's in bootloader mode, but it is not (I can still type wit it). Using the Defy keyboard btw.

### Steps To Reproduce
1. install package
2. start the program

### Expected behavior
Dygma keyboard would be correctly detected and it would be possible to use ```bazecor``` to configure it

### Additional context
I found a fix on Dygma discord, applying an overlay. I'm struggling to implement it, but it works for the author of the overlay.
link: https://github.com/bruhng/nixos/commit/a744b7ac389be9e4cc7692aaa8c3033d4b3816ee
It seems to me, that he is changing the udev rules for something else.

### Notify maintainers
@amesgen 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240117.842d9d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - channels(ptc): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by amesgen** [comment]
I don't own a Defy, so I can't test anything about it :crying_cat_face: 

Still, it seems that this comment might help you: https://github.com/NixOS/nixpkgs/pull/269513#issuecomment-1841415386

**Comment by PhlegmaTREEc** [comment]
Never occurred to me to look into pull requested... Thank you very much.
Fixed

**Comment by PhlegmaTREEc** [comment]
Fixed
