### ISSUE TITLE
Running nix on Yosemite

### ISSUE THREAD

**Issue by joelteon** [NixOS/nixpkgs#2820]
I started on a clean slate (backed up and removed /nix) last night before upgrading to OSX 10.10's developer preview, and so far have run into some difficulties:

`/usr/include/Availability.h` uses clang's `__has_feature` macro:

``` c
#if defined(__has_feature) && __has_feature(attribute_availability_with_message)
    #define __OS_AVAILABILITY(_target, _availability)            __attribute__((availability(_target,_availability)))
    #define __OS_AVAILABILITY_MSG(_target, _availability, _msg)  __attribute__((availability(_target,_availability,message=_msg)))
#else
    #define __OS_AVAILABILITY(_target, _availability)
    #define __OS_AVAILABILITY_MSG(_target, _availability, _msg)
#endif
```

which works fine in clang. gcc, however, doesn't short-circuit the && operator during the preprocessing phase, and since __has_feature is not known to the compiler, line 1 in the paste above is a parse error. Availability.h is included by stdio.h and some other headers so this doesn't seem to be a problem that can just be worked around.

I went to #macdev about this and was told that gcc is explicitly unsupported on OSX. (It probably has been for awhile.) AFAICT this means they don't plan to fix Availability.h to be gcc-compatible anytime soon.

There's already a clangStdenv but it requires gcc for something during the build phase—probably compiling llvm/clang, but I haven't checked.

As far as I can tell, a functional nixpkgs on OSX requires a stdenv using clang that has also been built entirely with the system tools. I'm not sure whether the naive solution of setting OSX's stdenv to stdenvNative will be any help, since I'm sure some packages will be expecting gcc when they execute 'gcc'.

I'm happy to help here as I have the 10.10 developer preview on a spare machine, but the process for building a functional stdenv seems to be pretty complex and I don't think there is a wiki article on it.

**Comment by gridaphobe** [comment]
Closing since the new darwin stdenv uses clang and doesn't have this issue.
