### ISSUE TITLE
set-source-date-epoch-to-latest.sh may set $SOURCE_DATE_EPOCH to the current time

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#28218]
## Issue description

[```set-source-date-epoch-to-latest.sh```](https://github.com/NixOS/nixpkgs/blob/48a5bb7/pkgs/build-support/setup-hooks/set-source-date-epoch-to-latest.sh#L7) may set ```$SOURCE_DATE_EPOCH``` to mtime of ```./env-vars```
e.g. the current time as ```./env-vars``` is just created and obviously the newest file here.

### Steps to reproduce

Try to build ```pkgs.libertine```. Or any derivation with ```sourceRoot = "."```

I added [a workaround](https://github.com/NixOS/nixpkgs/pull/28216/files#diff-6085bfe2e9ea332630182860e4677aafR16) but it would be nicer if ```set-source-date-epoch-to-latest.sh``` ignores the files generated by the build process.

### Possible solutions:
1. maintain blacklist of file names
2. or filter out all files younger than say 1 minute (```find``` can do it) 
3. or filter out all files younger than mtime of ```$NIX_BUILD_TOP/..``` (build start time)
4. or filter out all files with ctime <= mtime
5. do any combination of 1. 2. 3. 4.

**Comment by vcunat** [comment]
Fixed on staging via (3), at least partially.
