### ISSUE TITLE
Update request: tmuxPlugins.dracula 2.2.0 → 2.3.0

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#282161]
- Package name: tmuxPlugins.dracula
- Latest released version: 2.3.0

- Current version on the unstable channel: 2.2.0
- Current version on the stable/release channel: 2.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ethancedwards8

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by h7x4** [comment]
Fixed by #272954

**Comment by ethancedwards8** [comment]
Yeah the dracula changes LGTM.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/291582
