### ISSUE TITLE
Stirling PDF

### ISSUE THREAD

**Issue by bzmrgonz** [NixOS/nixpkgs#282169]
**Project description**
https://github.com/Stirling-Tools/Stirling-PDF

Tools to manipulate pdf files.

**Metadata**

* homepage URL:
* https://github.com/Stirling-Tools/Stirling-PDF
* source URL:
* https://github.com/Stirling-Tools/Stirling-PDF
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
I'll see what I can do, should be good practice working with Gradle apps

**Comment by bzmrgonz** [comment]
> I'll see what I can do, should be good practice working with Gradle apps

Thank you Tom, much appreciated, best of luck.

**Comment by TomaSajt** [comment]
By the way, I have pretty much succeeded in packaging it, and it seemed to run fine. Just forgot about it a little.
The only issue with the package currently is that jar files are created non-deterministically by default (timestamps are not set to a fixed time). After using the fixup hook made for this situation (unzip and rezip the jar file) springboot doesn't recognise its files anymore, which is really weird. So it stayed non-deterministic.

So I have two options: A) use the non-deterministic package or B) use the prebuilt jar from GitHub.

The latter one is much less complex to work with.

**Comment by bzmrgonz** [comment]
See if this helps you.. https://discourse.nixos.org/t/overriding-the-jdk-for-gradle-in-a-nix-flake/36541/2   or this discussion from the top... https://github.com/NixOS/nixpkgs/issues/278518

**Comment by TomaSajt** [comment]
> See if this helps you.. https://discourse.nixos.org/t/overriding-the-jdk-for-gradle-in-a-nix-flake/36541/2 or this discussion from the top (concerning java apps)... #278518

Thanks for the pointers, though the second thing linked is my own post :)

I finally managed to figure out how to fix the jar timestamps, so I'll open a PR adding the package

**Comment by bzmrgonz** [comment]
Thank you for your help @TomaSajt .  Much appreciated.. sorry for the delay. had a rough week last and it spilled into this one.   Looking forward to using stirling-pdf on nixos.
