### ISSUE TITLE
Mutable users issue

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#2821]
When making:

```
users.mutableUsers = false;
```

This means any new users and new groups created from configuration.nix needs to have a specified UID or GID.

I was thinking that is this is unnecessary. When you first create a new machine, you don't know UIDs or GIDs are available to be used. Can Nixos just create those users/groups and leave the system to specify the UID/GID and then enforce immutable users afterwards. The system shouldn't need to prevent the dynamic creation of users/groups inside the configuration phase, only afterwards?

**Comment by domenkozar** [comment]
this can be closed right?

**Comment by Mathnerd314** [comment]
Yeah. the current situation is reasonable enough, and I filed https://github.com/NixOS/nixpkgs/issues/3191.

**Comment by jgillich** [comment]
@domenkozar Do it ;)

**Comment by CMCDragonkai** [comment]
So is the conclusion is to just rely on systemd?
