### ISSUE TITLE
firefox-bin is outdated, how to update it?

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28225]
## Issue description
I am using firefox developer version 55.0b2 installed from `nixos.firefox-devedition-bin` with `-I nixpkgs=/path/to/this_repo_snapshot`.

The new version 56.0b is available. How can I update it?

Looking into `pkgs/applications/networking/browsers/firefox-bin/`, I found [update.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox-bin/update.nix) but I have no idea how to use it.

I know that someone will update it very soon but I want to learn from try doing it myself.

I can't find any documentation on this process.

**Comment by nbp** [comment]
Personally, I made a firefox overlay [1] which is I have not yet pushed to nixpkgs-mozilla repository.  You can install using the following commands:

```sh
$ cd
$ git clone https://github.com/nbp/nixpkgs-mozilla.git
$ ln -s ~/nixpkgs-mozilla/firefox-overlay.nix ~/.config/nixpkgs/overlays/.
```

Then, as versions changes quite frequently, I do not bother to add them to my user enviroment, and just use the following command (with a shell alias) to start firefox:

```sh
$ nix-shell '<nixpkgs>' -p firefox-beta-bin --command 'firefox -P default'
```

This command will look at Mozilla servers to know what is that latest version, and download the file which contains the checksum and verify that it is correctly signed my the release management team of Mozilla. Once all is verified, it will download the latest version with the expected checksum.

[1] https://github.com/nbp/nixpkgs-mozilla

**Comment by nbp** [comment]
> Looking into `pkgs/applications/networking/browsers/firefox-bin/`, I found update.nix but I have no idea how to use it.

Apparently the script is made available through the `passthru` attribute of each firefox version.
So I guess you might be able to run it with `nix-build -A nixos.firefox-devedition-bin-unwrapped.updateScript`

**Comment by wizzup** [comment]
**Solved** by using `update.nix`.

This is what I did  `pwd` is git repo (`/nix/nixpkgs`)

    $ ls
    COPYING  default.nix  doc  drvs.txt  lib  maintainers  movepy.sh  nixos  pkgs  prtests.sh  README.md  result  tstpy.sh

    $ nix-build -A firefox-devedition-bin-unwrapped.updateScript

    $ ./result

    $ git diff
    diff --git a/pkgs/applications/networking/browsers/firefox-bin/devedition_sources.nix b/pkgs/applications/networking/browsers/firefox-bin/devedition_sources.nix
    index a436cd46a1..97d11ede14 100644
    --- a/pkgs/applications/networking/browsers/firefox-bin/devedition_sources.nix
    +++ b/pkgs/applications/networking/browsers/firefox-bin/devedition_sources.nix
    @@ -1,955 +1,955 @@
    {
    -  version = "55.0b2";
    +  version = "56.0b2";
      sources = [
    -    { url = "http://archive.mozilla.org/pub/devedition/releases/55.0b2/linux-x86_64/ach/firefox-55.0b2.tar.bz2";
    +    { url = "http://archive.mozilla.org/pub/devedition/releases/56.0b2/linux-x86_64/ach/firefox-56.0b2.tar.bz2";
          locale = "ach";
          arch = "linux-x86_64";
    -      sha512 = "003297708bc29bdfd471ae4af99a39f3c4732a067ad56e7f5a49fe8caff7a88dbff9245a4e8843f504f80c0defd2c2fa62819e6b71c176da6cd0cfe9d1c614d2";
    +      sha512 = "87b42b752ce91ff7b144d81da8fb33d9d50c9501a24e00964e5a7e163754076bc4854f893cfffaae7e1612821e49a51887b7691109238ad553d7b9fe068b3fb6";
        }
