### ISSUE TITLE
avrgcclibc fails to build

### ISSUE THREAD

**Issue by danielfullmer** [NixOS/nixpkgs#28220]
## Issue description

The package `avrgcclibc` fails to build with the error:

```
checking dependency style of avr-gcc... gcc3
checking for avr-ranlib... ranlib
checking for avr-ar... ar
configure: error: Wrong assembler found; check the PATH!
builder for ‘/nix/store/08bhr9qkx2dyjk42v5ypgvxlxhw7gjl5-avr-gcc-libc.drv’ failed with exit code 1
```

I did a git bisect to determine this issue was a result of 093cc00cdd.
CC @Ericson2314 

### Steps to reproduce

`nix-build "<nixpkgs>" -A avrgcclibc`

for a version of nixpkgs after 093cc00cdd

## Technical details

* System: 17.09.git.5476a54 (Hummingbird)
* Nix version:  (Nix) 1.11.13
* Nixpkgs version: 17.09.git.5476a54c1d
* Sandboxing enabled: true

**Comment by Ericson2314** [comment]
`preconfigure = "unset AS"` should do it. See https://github.com/NixOS/nixpkgs/issues/28106 for why (analogous problem with non-standard linker instead of assembler).

**Comment by mguentner** [comment]
This does not work.

**Comment by Ericson2314** [comment]
Oh taking another look....this is kind of a hack-job derivation. This should be deleted and a normal cross compiled toolchain used in it's place. If you're not in too much of a rush, I can do that take care of that in the last column of https://github.com/NixOS/nixpkgs/projects/8

**Comment by mguentner** [comment]
I am doing my `avr` compilations with `release-17.03` for now. I don't need this as a priority. As long as it works in `release-17.09` I am happy with it.
Thanks for your effort! :muscle:

**Comment by Ericson2314** [comment]
Well, code cutoff is comming up quick :O. let's hope I can knock off https://github.com/NixOS/nixpkgs/projects/8!
