### ISSUE TITLE
Build failure: meilisearch@1.6.0 on x86_64-darwin

### ISSUE THREAD

**Issue by manuelderuiter** [NixOS/nixpkgs#282283]
### Steps To Reproduce

**nix run "nixpkgs#meilisearch"**

### Build log

```
 >   = note: ld: framework not found SystemConfiguration       
>           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
>
>
> The following warnings were emitted during compilation:
>
> warning: meilisearch@1.6.0: vergen: could not find repository from '/private/tmp/nix-build-meilisearch-1.6.0.drv-1/source/meilisearch'; class=Repository (6); code=NotFound (-3)
>
> error: could not compile `meilisearch` (bin "meilisearch") due to previous error
For full logs, run 'nix log /nix/store/l9fgqiwnw6xbbrs4vybybc84ppwii87x-meilisearch-1.6.0.drv'.
```

https://gist.github.com/manuelderuiter/2e6ff73a32bd890b513b7d35ebdf9b4a for full output

### Additional context
PR #281316

### Notify maintainers
@happysalada 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/Users/manuel/.nix-defexpr/channels/nixpkgs`
```

**Comment by happysalada** [comment]
hey, thank you for taking the time to file an issue!
I personally don't use meilisearch on darwin, and I remember there were originally some problems in making it work. So this might need a bit of tinkering to make sure it works.
The fix for the problem you are detailing is adding SystemConfiguration to the build input, (just like Security is added in the nix expression line 43). Are you interested in trying to contribute a solution ? I'm asking because I think that first fix might uncover other problems and I'm a little short on time at the moment. (happy to review and help merge a PR if you are inclined though).

**Comment by manuelderuiter** [comment]
Thank you for your quick response and your suggested fix works! I've tested it with the minimum flake.nix from below and added SystemConfiguration to the default.nix just like you said. I will go ahead and create a PR. 

My development environment is up and running again.

```nix
{
  description = "Issue 282283";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: {
    defaultPackage.x86_64-darwin = nixpkgs.legacyPackages.x86_64-darwin.callPackage ./default.nix {
      inherit (nixpkgs.legacyPackages.x86_64-darwin.darwin.apple_sdk_11_0.frameworks) Security SystemConfiguration;
    };
  };
}
```

**Comment by happysalada** [comment]
that in itself is a perfectly fine fix.
If you want to go a little further, the pattern of inheritting the darwin libraries, is a little bit of an antipattern.
you could just remove everything in all-packages.nix
and then just do something like
(with darwin.apple_sdk_11.0.frameworks; [ Security SystemConfiguration ];)
(inside the default.nix of meilisearch).
if that doesn't make sense or you don't like it, no worries at all.
Thank you for taking the time to make a PR !

**Comment by manuelderuiter** [comment]
That's good to know for next time! :) Thank you for your feedback, much appreciated.
