### ISSUE TITLE
Build failure: sage

### ISSUE THREAD

**Issue by hellwolf** [NixOS/nixpkgs#282383]
### Steps To Reproduce

1. build *sage*

### Build log

https://dpaste.com/B35XMN9GV

### Notify maintainers

@timokau @collares

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05.20240104.df02ad5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/var/lib/nixpkgs/hellwolf-unstable`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by collares** [comment]
Thank you for the bug report.

On nixpkgs master (post-#281579, see https://nixpk.gs/pr-tracker.html?pr=281579 for information about channel updates), Sage builds successfully, but Sage tests fail due to a harmless DeprecationWarning coming from a Cython import (`DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.`). Therefore, at least for the time being, it is safe to use `sage.override { requireSageTests = false; }` as a workaround.

Since the warnings come from Cython, it is annoying to properly fix this without upgrading Sage. I could patch Sage's `sage/misc/cython.py` to ignore DeprecationWarnings, but I think it is best to just proceed with the Sage 10.2 upgrade I'm working on at the moment.

**Comment by hellwolf** [comment]
> On nixpkgs master (post-#281579, see https://nixpk.gs/pr-tracker.html?pr=281579 for information about channel updates), Sage builds successfully, but Sage tests fail due to a harmless DeprecationWarning coming from a Cython import (`DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.`). Therefore, at least for the time being, it is safe to use `sage.override { requireSageTests = false; }` as a workaround.
> 

I see. Looking forward to the sage 10.2 upgrade!

**Comment by collares** [comment]
Little status update here: The next channel update was a staging-next upgrade and it broke Sage tests again. #283808 fixes it and will be merged soon.

**Comment by hellwolf** [comment]
```
$ nix build .#sage
error: builder for '/nix/store/dqs8zz45330l72r9y3kimnny070wj4gr-python3.11-primecountpy-0.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for references to /build/ in /nix/store/dhf01bl49dmqj6bwdaw82nz585xyh1fy-python3.11-primecountpy-0.1.0-dist...
       > patching script interpreter paths in /nix/store/dhf01bl49dmqj6bwdaw82nz585xyh1fy-python3.11-primecountpy-0.1.0-dist
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > Running phase: pythonCatchConflictsPhase
       > Found duplicated packages in closure for dependency 'cython':
       >  cython 0.29.36 (/nix/store/hn15nr4k2zk2akfyv0szcwg21zdnds6k-python3.11-cython-0.29.36/lib/python3.11/site-packages/Cython-0.29.36.dist-info)
       >   cython 3.0.6 (/nix/store/xx59gyk65a4s5vrmql8dyddx69dbvwfi-python3.11-cython-3.0.6/lib/python3.11/site-packages/Cython-3.0.6.dist-info)
       >
       > Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
       For full logs, run 'nix log /nix/store/dqs8zz45330l72r9y3kimnny070wj4gr-python3.11-primecountpy-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/kd6ig9860k1lvls641zznvs0616k8sf5-python3-3.11.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rw9412qz125d7h1wfdsdzzl6vjkm3r8b-python3.11-sagelib-10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hlcszwgsclllah0cjfmz6jkkvpy2vy43-sage-with-env-10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l7arwkx6f3hq8i5llyzdisr4qj827335-sage-10.0.drv' failed to build
```

**Comment by collares** [comment]
What commit is this on? Sage was successfully built on Hydra an hour ago on commit c002c6aa977a: https://hydra.nixos.org/build/247896586

**Comment by hellwolf** [comment]
sorry, my bad.
