### ISSUE TITLE
synology-drive-client: invalid username/password or insufficient user privilege

### ISSUE THREAD

**Issue by viperML** [NixOS/nixpkgs#282311]
### Describe the bug

As the title says, I'm getting this error when trying to use synology-drive-client for the first time. Logging in through the web UI works fine, as well as from my windows machine.

![image](https://github.com/NixOS/nixpkgs/assets/11395853/7407ae7c-b0e8-4055-ad34-f65ba00ae0e7)

I want to ping the maintainers @jcouyang and @MoritzBoehme , I don't know if you still use this program and you are facing the errors.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MoritzBoehme** [comment]
Mhh, weird. I don't have any issues. I am unfortunately a bit busy right now, but I'll try to update the package in the next few weeks to version 3.4.0_15724-1.
You can try to update it yourself using something like https://github.com/Mic92/nix-update/ on a local clone of nixpkgs. Or https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/update.nix should also work fine.

**Comment by jacmart** [comment]
Hi. I struggled with this issue quite some time until I found out the structure of the password seemed to be the culprit. It seems that Synology drive does not allow the same level of complexity as in the user credentials sometimes defined. Simplifying the characters set in the user pw did the trick for me.

**Comment by viperML** [comment]
Oh, I forgot to report back in github.

Indeed, the linux client can't handle symbols, vur only a-Z and 0-9. This was confirmed by the support service.

**Comment by jjoepook** [comment]
bonjour j ai le même problème je suis passé de Linux Mint 20 ou  Synology Drive fonctionnait a Linux Mint 22 ou il fonctionne plus si j ai bien compris il faut mettre un mot de passe sans accent et ça devrait fonctionner mais il me semble que Synology par sécurité ne demande que maintenant des mots de passe avec en plus des autres caractères j ai change il y a deux semaines mon mot de passe d administrations  peut être que l ancien n avais pas de symboles 
merci pour les réponses
