### ISSUE TITLE
`texlive` does not properly create all outputs in its multi-output-drv

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#282369]
### Describe the bug

Some `texlive` related bundles like `texliveBasic` or `texliveFull` `man` output, that fails. If one instead builds the `out` attribute, it works.

This again brakes `nix shell`!

```
❯ nix build nixpkgs#texliveBasic^man
error: derivation '/nix/store/0gng3g36c6y8ng039gkbbk7w6s1f1jpg-texlive-2022-env.drv' does not have wanted outputs 'man'
❯ nix build nixpkgs#texliveBasic.out
❯ echo $?
0
❯ nix shell nixpkgs#texliveBasic
error: derivation '/nix/store/0gng3g36c6y8ng039gkbbk7w6s1f1jpg-texlive-2022-env.drv' does not have wanted outputs 'man'
```

One can mitigate by using `^out` in the `nix shell` invocation. This is reproducible on random commits since 23.11 branchoff, haven't checked any earlier release.

### Steps To Reproduce
1. try to build the `man` output of `texliveBasic` or `texliveFull` or other similar collections using the `^` output selector
2. see the error as described above

### Expected behavior

`^man` produces the same output that `.man` does.

### Notify maintainers

* @xworld21 
* @tazjin 

(Determined based on the history of `pkgs/tools/typesetting/tex/texlive/build-tex-env.nix`)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.0pre20240117_b5ed36e`
 - channels(aroemer): `"nixpkgs-21.11"`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xworld21** [comment]
@veprbl I guess we should merge #270232 and hope it doesn't introduce new bugs.

(I really wish man page handling weren't so coupled with multioutput derivations. It's the wrong model for TeX Live.)

**Comment by xworld21** [comment]
```
nix shell nixpkgs#texliveBasic
```
now works as intended
