### ISSUE TITLE
NixOS silently doesn't generate Device sections if videoDriver is not recognized

### ISSUE THREAD

**Issue by lukateras** [NixOS/nixpkgs#28235]
This is an improvement request.

I've set `services.xserver.videoDriver = "i915"` and it resulted in no `Device` sections in `xserver.conf` generated by NixOS, and in `services.xserver.deviceSection` being ignored.

It might make sense to raise an error if `services.xserver.videoDrivers` is not empty and contains no recognized video drivers.

**Comment by bjornfor** [comment]
+1.

Relevant: #20271

**Comment by arianvp** [comment]
Couldn't we fix this with a `types.enum` ?

**Comment by frogamic** [comment]
Just ran into this today trying to get tearfree with amdgpu, any plans to look into it?
