### ISSUE TITLE
nix-1.7 wants to install in /etc

### ISSUE THREAD

**Issue by pjotrp** [NixOS/nixpkgs#2824]
In my quest for a nix-no-root I get:

...
INST   /home/cog/pprins/nix/store/zcldwb80nnxy054a2zzfzksplygyz4db-nix-1.7/lib/perl5/site_perl/5.16.3/x86_64-linux-thread-multi/Nix/Crypto.pm
building /etc/profile.d/nix.sh
  INST   /etc/profile.d/nix.sh
install: cannot create regular file '/etc/profile.d/nix.sh': Permission denied

**Comment by Profpatsch** [comment]
(triage) @pjotrp Can you check if that still happens?

**Comment by pjotrp** [comment]
Thanks. I moved to GNU Guix since then...

**Comment by Profpatsch** [comment]
Out of curiosity: Is that usable yet?

**Comment by pjotrp** [comment]
Yes, very usable. See my https://github.com/pjotrp/guix-notes
