### ISSUE TITLE
GCE bootstrap image still weighs in at 100 GB

### ISSUE THREAD

**Issue by evujumenuk** [NixOS/nixpkgs#28243]
This is a follow-up issue to #24360. Basically, images are still humongous.

```
$ gsutil cat gs://nixos-cloud-images/nixos-image-17.03.1082.4aab5c5798-x86_64-linux.raw.tar.gz | tar tvz
-rw-r--r-- nixbld/nixbld 107374182400 2017-05-02 12:51 disk.raw
```

The image is newer than the merge to `master`, so something clearly went wrong here. Were the images rebuilt with the old `diskSize` still in `nixpkgs-channels`? Or did that not even matter, and something else entirely is to blame?

An SSD-backed persistent disk created with that large an image costs $17 every month.

**Comment by vcunat** [comment]
Note that the PR's commit fa4eff9 is **not** reachable from the 17.03 stable branch.

**Comment by evujumenuk** [comment]
I don't think the closure size is a problem:

```
$ gsutil cat gs://nixos-cloud-images/nixos-image-17.03.1082.4aab5c5798-x86_64-linux.raw.tar.gz | zcat | wc -c
2786826240
```

But the PR only being in `master` probably is. In that case, it seems to have gone over a lot of people's heads: https://github.com/NixOS/nixops/issues/590

Furthermore, would that mean that this PR would have to be applied to the stable branches to have any observable effect?

**Comment by vcunat** [comment]
Well, this commit doesn't seem to have been applied to 17.03 in any way, so it doesn't take effect in there; on the other hand, if you had image from unstable (17.09)... ;-)

**Comment by pvgoran** [comment]
It's December already, and the latest GCE image is still 17.03. I wonder who could update it to 17.09...

**Comment by pierrebeaucamp** [comment]
I just deployed a machine to `us-east1-b` using NixOps 1.6 and the bootstrap image was 2GB large (down from 100GB of my previous deployment)
