### ISSUE TITLE
sbcl: missing sourceProvenance declarations

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#282476]
### Describe the bug
On platforms that don't use `clisp` for bootstrapping, `sbcl` uses binary native code for bootstrapping without properly declaring it.

### Steps To Reproduce
1. Try to build `sbcl` on a platform that doesn't use `clisp` (`x86_64-darwin`, `i686-linux`, `armv7l-linux`, `armv6l-linux`, `x86_64-freebsd` or `x86_64-solaris` at this point) with `NIXPKGS_ALLOW_NONSOURCE=0` set
2. Watch your machine run binary native code fetched from the Internet

### Expected behavior
Fail to evaluate due to a `binaryNativeCode` declaration.

### Additional context
It may be possible to enable `clisp` bootstrapping on `i686-linux`. I successfully bootstrapped `sbcl` this way in a non-Nix context, but I currently don't have such a machine at hand.

### Notify maintainers
Will do.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.0-8-amd64, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hraban** [comment]
Since I'm apparently attached as a maintainer to this issue somehow I will just flat out say: I don't know any of these platforms, I don't consider myself a maintainer for them , I hope someone fixes this issue and I wish them the best, but I'm unsubscribing. Godspeed!

**Comment by 7c6f434c** [comment]
Link to the converged docs on provenance marking?

**Comment by zeuner** [comment]
@Uthar

**Comment by hraban** [comment]
I got nerd sniped by this, turns out the source provenance attribute needs to be a _list_ of source provenances 😆 😭

**Comment by 7c6f434c** [comment]
My «doc link please» default reaction is because a) I don't have a clue where the discussion has ended and b) I know there _are_ nuances, they are meaningful and well-justified — but see (a), I have no clue about them.

**Comment by hraban** [comment]
for completeness: the only docs I went off of were at https://ryantm.github.io/nixpkgs/stdenv/meta/ bottom of page
