### ISSUE TITLE
albert :  FATAL: Cannot mix incompatible Qt library.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28258]
## Issue description
[albert](https://github.com/NixOS/nixpkgs/blob/f732d816410faff03783e2180ffba116478eafe0/pkgs/applications/misc/albert/default.nix) is not working out-of-the-box in `nix-shell`.

### Steps to reproduce

    $ pwd
    /nix/nixpkgs
    
    $ git rev-parse HEAD
    eb9f427d4e23af7f7da051e640024bf99a72f343

    $ nix-shell -I nixpkgs=/nix/nixpkgs -p albert

    [nix-shell:/nix/nixpkgs]$ albert 
    FATAL: Cannot mix incompatible Qt library (version 0x50900) with this library (version 0x50901)
    QThread::wait: Thread tried to wait on itself
    QMutex: destroying locked mutex
    QMutex: destroying locked mutex
    QThread: Destroyed while thread is still running
    Aborted

Different error message in `pure` shell, I don't know if it expected ot fail here.

    $ nix-shell --pure -I nixpkgs=/nix/nixpkgs -p albert

    [nix-shell:/nix/nixpkgs]$ albert 
    FATAL: This application failed to start because it could not find or load the Qt platform plugin "xcb"
    in "".

    Reinstalling the application may fix this problem.

/ping maintainer @ericsagnes

**Comment by edolstra** [comment]
This is probably not albert-specific, see https://github.com/NixOS/nixpkgs/issues/24256.

**Comment by jonafato** [comment]
#24256 is fixed, and I can't reproduce this issue on `master`. Can this be closed?

**Comment by fpletz** [comment]
Works now.
