### ISSUE TITLE
budgie should be independent of cinnamon

### ISSUE THREAD

**Issue by koppor** [NixOS/nixpkgs#282584]
### Describe the bug

`configuration.nix` on NixOS:

```nix
  services.xserver.desktopManager = {
    budgie.enable = true;
    cinnamon.enable = true;
  };
```

Output:

```
error: The option `services.xserver.displayManager.lightdm.greeters.slick.cursorTheme.package' is defined multiple times while it's expected to be unique.

Definition values:
- In `/nix/store/yy19v2dwb8ldphvia9smajvwv3ycx2c1-source/nixos/modules/services/x11/desktop-managers/budgie.nix': <derivation qogir-icon-theme-2023-06-05>
- In `/nix/store/yy19v2dwb8ldphvia9smajvwv3ycx2c1-source/nixos/modules/services/x11/desktop-managers/cinnamon.nix': <derivation mint-cursor-themes-1.0.2>
```

Expected behavior:

No error when enabling both budgie and cinnamon

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
mnt/vms took 6s ✦ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 23.11 (Tapir), 23.11.20240115.b8dd8be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

/mnt/vms took 2s ✦ ❯ 
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jopejoe1** [comment]
Both of them want to set a theming options for lightdm, thus failing the build, and requiering the user to explicitly select which theme they want to use by setting the option them self.

**Comment by jopejoe1** [comment]
mkForce and mkDefault are functions which you put before the value changing the overwrite priority of that value.

In your case it would look something like this:
```nix
environment.sessionVariables.NIX_GSETTINGS_OVERRIDES_DIR = lib.mkForce "/nix/store/ynzry4q4ww1664z8293rqvbykfigznfy-cinnamon-gsettings-overrides/share/gsettings-schemas/nixos-gsettings-overrides/glib-2.0/schemas";
```

Also don't forget to include lib in your input in this case.

**Comment by jopejoe1** [comment]
Also would probably be better to replace the path with
 `"${pkgs.cinnamon.cinnamon-gsettings-overrides}/share/gsettings-schemas/nixos-gsettings-overrides/glib-2.0/schemas"` to prevent future breakage
