### ISSUE TITLE
noto-fonts-emoji segfaults on compilation

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#28259]
## Issue description

While compiling/processing png files, the following error is presented:

```
emoji png/128/emoji_u1f4ab.png build/emoji/emoji_u1f4ab.png
/nix/store/n61x4qvbs0v25v798nmsb1gq5jzpzyvs-pngquant-2.9.1/bin/pngquant --speed 1 --skip-if-larger --force -o "build/quantized_pngs/emoji_u1f4ab.png" "build/emoji/emoji_u1f4ab.png"
optipng -quiet -o7 -clobber -force -out "build/compressed_pngs/emoji_u1f4ab.png" "build/quantized_pngs/emoji_u1f4ab.png"
make: *** [Makefile:178: build/compressed_pngs/emoji_u1f4ab.png] Segmentation fault
builder for ‘/nix/store/gzcppj3nilcxydza6h88rc6h0iw4mgpx-noto-fonts-emoji-git-2016-03-17.drv’ failed with exit code 2
error: build of ‘/nix/store/gzcppj3nilcxydza6h88rc6h0iw4mgpx-noto-fonts-emoji-git-2016-03-17.drv’ failed
```

### Steps to reproduce

Compile `noto-fonts-emoji`.

## Technical details

* System: 17.09pre111447.a7c8f5e419 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09pre112893.059d722e5c"
* Sandboxing enabled: false

**Comment by srhb** [comment]
Caused by #28106 probably.

**Comment by gebner** [comment]
@pmiddend Do you still get the error?  noto-fonts-emoji build fine for me.

**Comment by eqyiel** [comment]
I saw this at one point, but it builds fine for me since the commit that @srhb mentioned.

**Comment by pmiddend** [comment]
@gebner Works for me now, thanks.
