### ISSUE TITLE
aarch64 stdenv bootstrap tests failing

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#28257]
## Issue description

See https://hydra.nixos.org/build/58635581

Since 332a60cbd18 the tests are no longer hidden from Hydra's unstable job, and consequently the aarch64 segfault is currently blocking the nixpkgs channel.

**Comment by dezgeg** [comment]
Will take a look today.

**Comment by dezgeg** [comment]
Probably the binutils upgrade, based on bisect so far.
