### ISSUE TITLE
nixos-install --chroot ignored

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#28251]
the runChroot code in nixos-install was removed in https://github.com/NixOS/nixpkgs/commit/d990aa716327abb018e8352dcf7ba2fcfb4fc34c

it will now try to do a full install if you run `nixos-install --chroot`

cc @copumpkin

**Comment by copumpkin** [comment]
I'll try to restore before 17.09 branch point, sorry!

**Comment by copumpkin** [comment]
Okay I'm looking at this now. I'm not entirely clear on the flag's purpose, so it's hard for me to add it back (even looking at the old code), and it doesn't really appear to be documented except that it gets mentioned in the manual once in passing. Can someone elaborate on what it's for and what it's guarding against? That'll make it much easier for me to add it back.

**Comment by copumpkin** [comment]
Okay, I get what it's supposed to do. `--chroot` is just "set up a few bind mounts like /proc to make it look legit, and then chroot", right? It has nothing to do with installation except that one might want to use it to test a fresh install (but one might also want to use it to test an unfresh install mounted on another machine, or something).

**Comment by florianjacob** [comment]
Also useful to fix a broken installation, e.g. when you broke your boot loader or something similar severe. Then you can boot from usb, run `nixos-install --chroot` and then do a rebuild, and everything works again.

**Comment by copumpkin** [comment]
Cool! @florianjacob do you have a good test setup for my PR addressing this? My access to physical NixOS boxes for testing is limited right now.

**Comment by florianjacob** [comment]
@copumpkin the hardware's here, but did not manage to get your PR version running on my NixOS live usb key to try it, or somehow mount a snapshot of my actual installation and trick nixos-install into chrooting into that. 😓

**Comment by florianjacob** [comment]
Note that on Arch Linux, `nixos-install` and `nixos-install --chroot` are two separate tools, `pacstrap` and `arch-chroot`, which would at least make it easier to test this skipping all that mount point checking, as well as more flexible. And it would also prevent the confusion on what `--chroot` does in the first place. 😉

**Comment by fpletz** [comment]
ping @copumpkin

We only have a few days left until the release. :)

**Comment by copumpkin** [comment]
I've updated the PR, sorry!
