### ISSUE TITLE
nvim-treesitter markdown grammar update caused highlighting issue

### ISSUE THREAD

**Issue by BirdeeHub** [NixOS/nixpkgs#282614]
### Describe the bug

When this commit dropped, https://github.com/NixOS/nixpkgs/commit/93360c805840a3e66555d17ce5a380082ead0822 treesitter highlighting for most items outside of ones marked with \`\`\`\<languagename\> \`\`\` suddenly stopped working.

### Steps To Reproduce
1. nvim-treesitter.withAllGrammars before and after the commit
2. open markdown file
3. observe no highlighting for links, headings or anything marked with single \` marks

BEFORE:

![Screenshot_2024-01-21_07-21-47](https://github.com/NixOS/nixpkgs/assets/85372418/04874c21-8894-4738-b00b-891ab1547698)

AFTER:

![Screenshot_2024-01-21_07-22-47](https://github.com/NixOS/nixpkgs/assets/85372418/7ec44424-0fdb-4265-830b-bc1179bd3fd5)

### Notify maintainers

@GaetanLepage 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ ❯ nix-shell -p nix-info --run "nix-info -m"
these 16 paths will be fetched (55.43 MiB download, 259.72 MiB unpacked):
  /nix/store/3r87a2wq1w4l66wnsm7rqvy608mx23h6-binutils-2.40
  /nix/store/7q3l14lc8qhgcpfv8qqk0ckj3sn46cj8-binutils-2.40-lib
  /nix/store/syp0507hrby53pprfi7n4wppms3b7ba2-binutils-wrapper-2.40
  /nix/store/kz3zbajcbi9kqm5nmdyx80zi5fcqis66-expand-response-params
  /nix/store/rgg874xkzlfmkzkm7911dwnihswkf54g-file-5.44
  /nix/store/jgdz5wfqc6q6qhy17lsqnfpbkfi1fcar-gcc-12.2.0
  /nix/store/3hbxw05vfs6m1155xa6pvribs3bv777n-gcc-wrapper-12.2.0
  /nix/store/linb70pgp53f0kygxm5wk163dx22d681-glibc-2.37-45-dev
  /nix/store/vz87bvvihs94lnvj7j0r33w2jih7nnf4-gmp-6.2.1
  /nix/store/qlcm8dzsaa6wyycmx7in8rz6x3pzf6zf-gnumake-4.4.1
  /nix/store/1mczdvar5cyyfcvcsjq71164p2skbpim-isl-0.20
  /nix/store/bzy10mxb5d7gl7g5d05rj33rkv668hsc-libmpc-1.3.1
  /nix/store/qs605c91wv5fr9rny4mmhpdna6i59kdk-linux-headers-6.2
  /nix/store/frxcyd7g66afqc3rpcx64rlqvsdjqbnw-mpfr-4.2.0
  /nix/store/gwf21xyl0x0bhgapi66avzf6qmddr44s-patchelf-0.15.0
  /nix/store/gv2cl6qvvslz5h15vqd89f1rpvrdg5yc-stdenv-linux
copying path '/nix/store/kz3zbajcbi9kqm5nmdyx80zi5fcqis66-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/rgg874xkzlfmkzkm7911dwnihswkf54g-file-5.44' from 'https://cache.nixos.org'...
copying path '/nix/store/qlcm8dzsaa6wyycmx7in8rz6x3pzf6zf-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/qs605c91wv5fr9rny4mmhpdna6i59kdk-linux-headers-6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/gwf21xyl0x0bhgapi66avzf6qmddr44s-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7q3l14lc8qhgcpfv8qqk0ckj3sn46cj8-binutils-2.40-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/vz87bvvihs94lnvj7j0r33w2jih7nnf4-gmp-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/1mczdvar5cyyfcvcsjq71164p2skbpim-isl-0.20' from 'https://cache.nixos.org'...
copying path '/nix/store/frxcyd7g66afqc3rpcx64rlqvsdjqbnw-mpfr-4.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/3r87a2wq1w4l66wnsm7rqvy608mx23h6-binutils-2.40' from 'https://cache.nixos.org'...
copying path '/nix/store/bzy10mxb5d7gl7g5d05rj33rkv668hsc-libmpc-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/linb70pgp53f0kygxm5wk163dx22d681-glibc-2.37-45-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/jgdz5wfqc6q6qhy17lsqnfpbkfi1fcar-gcc-12.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/syp0507hrby53pprfi7n4wppms3b7ba2-binutils-wrapper-2.40' from 'https://cache.nixos.org'...
copying path '/nix/store/3hbxw05vfs6m1155xa6pvribs3bv777n-gcc-wrapper-12.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/gv2cl6qvvslz5h15vqd89f1rpvrdg5yc-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240119.e5d1c87`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
Hmm indeed, this seems annoying.
However, I feel like this has to be reported upstream as it might be a parser regression.
Could you open an issue there ?

**Comment by BirdeeHub** [comment]
hmmmm will do. ill check it out. does this happen for you?

**Comment by GaetanLepage** [comment]
> hmmmm will do. ill check it out. does this happen for you?

No, I don't use this grammar.

**Comment by BirdeeHub** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/5895 changed the list of admissible capture names to more closely align with upstream tree-sitter and Helix, making sharing/adapting queries easier. This requires changes in colorschemes; see [CONTRIBUTING.md](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights) and the commit message https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0 for a detailed list of changes. If you cannot adapt your colorscheme (yet), pin nvim-treesitter at v0.9.2.

source: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293

**Comment by BirdeeHub** [comment]
hmmmmmmmmm Seems like there were breaking changes to treesitter requiring colorscheme updates and onedark-nvim hasnt caught up?

**Comment by BirdeeHub** [comment]
I will leave the issue open? closed? idk may help other ppl who had this issue while its relevant better if its open

**Comment by GaetanLepage** [comment]
Thank you for investigating !

> I will leave the issue open? closed? idk may help other ppl who had this issue while its relevant better if its open

Well, I would advise to close this issue as no action is expected on the nixpkgs side.
People can still find this issue and see the "solution".

**Comment by BirdeeHub** [comment]
What do you use for highlighting markdown btw if you dont have treesitter grammar for it?

**Comment by GaetanLepage** [comment]
> What do you use for highlighting markdown btw if you dont have treesitter grammar for it?

Nothing actually ^^
Maybe I should get that syntax...

**Comment by BirdeeHub** [comment]
its really nice when it works again XD Maybe your colorscheme is on top of it and will work.

I literally just install all the treesitter grammars becuase i dont want to mess with making sure they are installed when i want them

**Comment by GaetanLepage** [comment]
I manually enable the grammars that I want.
Enabling the markdown TS grammar is a disaster (maybe the fault of my colorscheme: gruvbox).
I actually have a great highlighting without it.

**Comment by BirdeeHub** [comment]
oohh I dont really TS maybe i will have to at some point when I have job but ill avoid it if I can XD

**Comment by GaetanLepage** [comment]
I meant Treesitter, not typescript

**Comment by BirdeeHub** [comment]
ah hm. ok fair

**Comment by BirdeeHub** [comment]
It has been fixed already but update has not hit nixos.

I know they just ran the generator 2 days ago but they really need to run it again.

lazy.nvim got a really helpful update for nix and colorschemes need the treesitter update
