### ISSUE TITLE
Update request: jdt-language-server 1.26.0 → 1.28.0

### ISSUE THREAD

**Issue by sstubbs** [NixOS/nixpkgs#282662]
- Package name: jdt-language-server
- Latest released version: 1.28.0

- Current version on the unstable channel: 1.26.0
- Current version on the stable/release channel: 1.26.0

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
already covered by #279285

**Comment by kirillrdy** [comment]
done in https://github.com/NixOS/nixpkgs/pull/279285
