### ISSUE TITLE
Package request: spottube

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nixpkgs#282612]
**Project description**
https://github.com/KRTirtho/spotube

Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile! 

**Metadata**

* homepage URL: https://github.com/KRTirtho/spotube
* source URL: https://github.com/KRTirtho/spotube
* license: BSD-4-Clause License
* platforms: Linux, Darwin, Windows, Android, iOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by danielpza** [comment]
@Guanran928 have you opened a new issue?, you can also rename this one and reopen it.

**Comment by danielpza** [comment]
Oh, I searched for spotube and this was the only issue I found. I guess I made the same mistake and misspelled it :sweat_smile:
