### ISSUE TITLE
Gnome openweather extension does not work with Gnome 45 version

### ISSUE THREAD

**Issue by Bortechino** [NixOS/nixpkgs#282642]
### Describe the bug
Gnome openweather extension is not compatible with Gnome 45 version

### Steps To Reproduce
1. nix-shell -p gnomeExtensions.openweather
2. ...
3. ...

### Additional context
Additional information: The extension maintainer does not work with the project
https://gitlab.com/skrewball/openweather

The extension can be replaced with the fork
OpenWeather Refined 
https://extensions.gnome.org/extension/6655/openweather/
https://github.com/penguin-teal/gnome-openweather

### Notify maintainers

@piegames

**Comment by honnip** [comment]
Now we have `gnomeExtensions.openweather-refined` on unstable channel
