### ISSUE TITLE
libTAS can't start games : "Could not start dynamically linked executable"

### ISSUE THREAD

**Issue by Eddio0141** [NixOS/nixpkgs#282680]
### Describe the bug
Game fails to open when "Start" is clicked with the error `could not start dynamically linked executable`

### Steps To Reproduce
1. Open libTAS on the terminal
2. On libTAS, set "Game executable" path to a game, which for my test I chose "Buckshot Roulette" v1.1
3. Click "Start", check terminal

### Expected behavior
Game runs with libTAS hooks

### Additional context
Exact output
```console
Could not start dynamically linked executable: /home/yuu/Games/BuckshotRoulette/v1.1/Buckshot Roulette.x86_64
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
Attempt 1: Couldn't connect to socket.
Game couldn't start properly.
```

### Notify maintainers
@skyrina 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240119.bbe7d8f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(yuu): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by skyrina** [comment]
hello, your system does not have the required libraries to run the game
please check [this webpage](https://nix.dev/permalink/stub-ld) for instructions on how to add them to your system, or use the `steam-run` package as a wrapper for libtas
if the game ships with its own libraries, check [the libtas usage page](https://tasvideos.org/EmulatorResources/LibTAS/Usage)

for example, i was able to run Celeste by using `steam-run` and many other games by adding the following lines to my `configuration.nix` file
```nix
programs.nix-ld.enable = true;

# "minimum" amount of libraries needed for most games to run
programs.nix-ld.libraries = with pkgs; [
  # common requirement for several games
  stdenv.cc.cc.lib

  # from https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/games/steam/fhsenv.nix#L72-L79
  xorg.libXcomposite
  xorg.libXtst
  xorg.libXrandr
  xorg.libXext
  xorg.libX11
  xorg.libXfixes
  libGL
  libva

  # from https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/games/steam/fhsenv.nix#L124-L136
  fontconfig
  freetype
  xorg.libXt
  xorg.libXmu
  libogg
  libvorbis
  SDL
  SDL2_image
  glew110
  libdrm
  libidn
  tbb
  zlib
];
```

**Comment by Eddio0141** [comment]
Ah right, makes sense
Not the job for libTAS to have those libraries for the game to be ran
Thanks!
