### ISSUE TITLE
Update request: VSCODE 1.84.2→ 1.85.2

### ISSUE THREAD

**Issue by Bortechino** [NixOS/nixpkgs#282703]
- Package name:vscode
- Latest released version:

- Current version on the unstable channel:1.85.1
- Current version on the stable/release channel:1.84.2

- [ +] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by UlyssesZh** [comment]
@samuela @K900 Thank you very much!

**Comment by samuela** [comment]
done in https://github.com/NixOS/nixpkgs/pull/282178
