### ISSUE TITLE
Package request: `aws-shell`

### ISSUE THREAD

**Issue by long-connecx** [NixOS/nixpkgs#282730]
**Project description**

AWS Shell is an integrated shell for working with the AWS CLI.

**Metadata**

* homepage URL: https://github.com/awslabs/aws-shell
* source URL: https://github.com/awslabs/aws-shell
* license: Apache License
* platforms: unix, linux, darwin

**Comment by dotlambda** [comment]
That project seems abandoned. Are you sure it's still of any use? See https://github.com/awslabs/aws-shell/issues.

**Comment by long-connecx** [comment]
Good catch, didn't realise it was unmaintained anymore. Happy to close this out until there's indication that the project will be maintained.
