### ISSUE TITLE
Build failure: mongodb-4.4 (unifi controller)

### ISSUE THREAD

**Issue by techyporcupine** [NixOS/nixpkgs#282753]
### Steps To Reproduce

1. build *mongodb-4.4.27* as part of the unifi8 package for the unifi controller.
2. Observe the following failure: 
```
       > Checking for C++ header file net-snmp/net-snmp-config.h... no
       > Could not find <net-snmp/net-snmp-config.h>, required for enterprise build.
```

### Additional context

This issue occurs when I'm doing a NixOS rebuild (for the first time in a couple weeks). 

I can give more info if required!
(And let me know if I did something wrong and I will correct it)

### Notify maintainers

@globin 
@Patryk27 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/50bgi74d890mpkp90w1jwc5g0dw4dccr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by robbins** [comment]
Related https://github.com/NixOS/nixpkgs/issues/281416?

**Comment by qubitnano** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/281440 which is now in unstable 612f97239e2cc474c13c9dafa0df378058c5ad8d. unifi8 and mongodb build.

**Comment by techyporcupine** [comment]
Thank you! That worked great.
