### ISSUE TITLE
Update request: vokoscreen-ng 3.8.0 → 4.0.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#282752]
- Package name: vokoscreen-ng
- Latest released version: 4.0.0
- Current version on the unstable channel: 3.8.0
- Current version on the stable/release channel: 3.8.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SCOTT-HAMILTON

https://github.com/vkohaupt/vokoscreenNG/releases/tag/4.0.0

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment]
Done in #289285.
