### ISSUE TITLE
broken patch URL in pkgs/tools/misc/fontforge/default.nix

### ISSUE THREAD

**Issue by lzhang10** [NixOS/nixpkgs#28270]
## Issue description
in https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/fontforge/default.nix
the patch url is broken:

### Steps to reproduce
```
$ curl http://pkgs.fedoraproject.org/cgit/fontforge.git/plain/fontforge-20140813-use-system-uthash.patch?id=8bdf933
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://pkgs.fedoraproject.org/fontforge.git/plain/fontforge-20140813-use-system-uthash.patch?id=8bdf933">here</a>.</p>
</body></html>
```

However, the new URL (http://pkgs.fedoraproject.org/fontforge.git/plain/fontforge-20140813-use-system-uthash.patch?id=8bdf933) also gave a 404 error.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by lzhang10** [comment]
BTW, this happened when building nix from scratch from an SL6 machine from a recent master 129f8d7

**Comment by matthewbauer** [comment]
Here's the latest url of the patch:

https://src.fedoraproject.org/rpms/fontforge/raw/master/f/fontforge-20140813-use-system-uthash.patch

I think we should try to track down all of these fedora patches because they must have been moved around recently.

**Comment by lzhang10** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/28272
