### ISSUE TITLE
Python build failing with error Python.h:44:10: fatal error: crypt.h: No such file or directory aarch64-linux

### ISSUE THREAD

**Issue by ananta-code** [NixOS/nixpkgs#282807]
### Describe the bug
Python build failing with error Python.h:44:10: fatal error: crypt.h: No such file or directory aarch64-linux
 Complete error:
`
bazel build //learning/examples/python-hello-world:service_wheel                    
INFO: Repository pip_requirements_ruamel_yaml_clib instantiated at:
  /home/abc/src/code/code/WORKSPACE:111:13: in <toplevel>
  /home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/pip_requirements/requirements.bzl:49:20: in install_deps
Repository rule whl_library defined at:
  /home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/rules_python/python/pip_install/pip_repository.bzl:697:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_requirements_ruamel_yaml_clib':
   Traceback (most recent call last):
	File "/home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/rules_python/python/pip_install/pip_repository.bzl", line 596, column 13, in _whl_library_impl
		fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library pip_requirements_ruamel_yaml_clib failed: Collecting ruamel-yaml-clib==0.2.8
  Using cached ruamel.yaml.clib-0.2.8.tar.gz (213 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: ruamel-yaml-clib
  Building wheel for ruamel-yaml-clib (PEP 517): started
  Building wheel for ruamel-yaml-clib (PEP 517): finished with status 'error'
Failed to build ruamel-yaml-clib
 (  ERROR: Command errored out with exit status 1:
   command: /home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/python3_8_aarch64-unknown-linux-gnu/bin/python3 /home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/pypi__pip/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmplgohnij2
       cwd: /tmp/pip-wheel-a0_er3bv/ruamel-yaml-clib_2121a8ca4f864e02a046d192e0d6dc6d
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-cpython-38
  creating build/lib.linux-aarch64-cpython-38/ruamel
  creating build/lib.linux-aarch64-cpython-38/ruamel/yaml
  creating build/lib.linux-aarch64-cpython-38/ruamel/yaml/clib
  copying ./setup.py -> build/lib.linux-aarch64-cpython-38/ruamel/yaml/clib
  copying ./__init__.py -> build/lib.linux-aarch64-cpython-38/ruamel/yaml/clib
  copying ./LICENSE -> build/lib.linux-aarch64-cpython-38/ruamel/yaml/clib
  running build_ext
  building '_ruamel_yaml' extension
  creating build/temp.linux-aarch64-cpython-38
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw -I/tools/deps/libedit/include -g0 -fPIC -I/home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/python3_8_aarch64-unknown-linux-gnu/include/python3.8 -c _ruamel_yaml.c -o build/temp.linux-aarch64-cpython-38/_ruamel_yaml.o
  In file included from _ruamel_yaml.c:16:
  /home/abc/.cache/bazel/_bazel_abc/38e8e139535ece1994c63a3b206915ed/external/python3_8_aarch64-unknown-linux-gnu/include/python3.8/Python.h:44:10: fatal error: crypt.h: No such file or directory
     44 | #include <crypt.h>
        |          ^~~~~~~~~
  compilation terminated.
  error: command '/nix/store/f38iyls39nx3j2am87q0ni605nb152gv-gcc-wrapper-9.5.0/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for ruamel-yaml-clib
ERROR: Failed to build one or more wheels
`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Nix Shell is ready (it took us 0 seconds)
 - system: `"aarch64-linux"`
 - host os: `Linux 6.5.0-14-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.0`
 - nixpkgs: `/home/abc/.nix-defexpr/channels/nixpkgs`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
Nix Shell is ready (it took us 1 seconds)
 - system: `"aarch64-linux"`
 - host os: `Linux 6.5.0-14-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.0`
 - nixpkgs: `/home/abc/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukium** [comment]
What are you trying to do?
How can I reproduce the error?
