### ISSUE TITLE
Update request: python311Packages.cupy 12.2.0 → 13.0.0

### ISSUE THREAD

**Issue by murdock-grewar** [NixOS/nixpkgs#282814]
- Package name: cupy
- Latest released version: 13.0.0

- Current version on the unstable channel: 12.3.0
- Current version on the stable/release channel: 12.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@hyphon81 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hugosenari** [comment]
#282839

**Comment by FliegendeWurst** [comment]
Done in #294305
