### ISSUE TITLE
Documentation: nix-collect-garbage --delete-older-than

### ISSUE THREAD

**Issue by langfingaz** [NixOS/nixpkgs#282884]
## Problem

In the documentation of [nix-collect-garbage](https://nixos.org/manual/nix/stable/command-ref/nix-collect-garbage) (stable and unstable), the option `--delete-older-than period` states the following:

> This  is the equivalent of invoking `nix-env --delete-generations <period>` on each found profile.  See the documentation of that command for additional information about the period argument.

In the referenced documentation of [nix-env](https://nixos.org/manual/nix/stable/command-ref/nix-env/delete-generations#generations-time) (stable and unstable), two meanings of `<period>` are described. The second one reads as follows:

> `+<number>`: Keep the last number generations, along with any newer than current.

However, when e.g. `+7` is configured as `<period>`, an error is returned.

Used NixOS configuration:

```Nix
{
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than +7";
  };
}
```

Log of `nix-gc.service`:

```
Jan 22 00:00:03 yodaNas systemd[1]: Started Nix Garbage Collector.
Jan 22 00:00:03 yodaNas nix-gc-start[4189179]: removing old generations of profile /nix/var/nix/profiles/per-user/root/channels
Jan 22 00:00:03 yodaNas nix-gc-start[4189179]: error: invalid number of days specifier '+7', expected something like '14d'
Jan 22 00:00:03 yodaNas nix-gc-start[4189179]: Try '/nix/store/j7nl2pj606d8ld5818hw3z3fbz00sdc5-nix-2.18.1/bin/nix-collect-garbage --help' for more info>
Jan 22 00:00:03 yodaNas systemd[1]: nix-gc.service: Main process exited, code=exited, status=1/FAILURE
Jan 22 00:00:03 yodaNas systemd[1]: nix-gc.service: Failed with result 'exit-code'.
``` 

## Proposal

I'm not sure weather this is a documentation problem or a bug.

We should either make it clear in the documentation, that with `nix-collect-garbage` only `<number>d` can be used, or allow the usage of `+<number>`.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

### Notify maintainers

@pennae 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(yoda): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fricklerhandwerk** [comment]
@langfingaz the documentation on `nix-env --delete-generations` is valid only for that command. The value of `nix.gc.options` is passed to `nix-collect-garbage`. As that manual page says, `--delete-older-than` corresponds to `nix-env --delete-generations old`, where `old` is a fixed special value.

It may be a bit confusing because you have to wire those different things up in your head while reading. Adding a few links would certainly help. But otherwise documentation and option behavior is correct.
