### ISSUE TITLE
Regression in autofs: cannot open mount module nfs (/nix/store/…-autofs-5.1.3/lib/autofs/mount_nfs.so: undefined symbol: xdr_exports)

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [NixOS/nixpkgs#28282]
## Issue description

autofs is broken and unable to mount NFS shares on nixos-unstable. It works on channels/nixos-17.03. Upon trying to mount a share, it gets these errors:

    automount: open_mount:294: parse(sun): cannot open mount module nfs (/nix/store/…-autofs-5.1.3/lib/autofs/mount_nfs.so: undefined symbol: xdr_exports)
    automount: lookup(file): failed to open parse context

### Steps to reproduce

Stick this test in `nixpkgs/nixos/tests/nfs-autofs.nix` and run it:

```
import ./make-test.nix {
  name = "nfs-autofs";
  nodes = {
    server = { pkgs, ... }:
      { services.nfs.server =
          { enable = true;
            exports = "/data/foo 192.168.1.0/255.255.255.0(rw,no_root_squash,no_subtree_check,fsid=0)";
            createMountPoints = true;
          };
        networking.firewall.enable = false;
      };
    client = { pkgs, ... }:
      { boot.supportedFilesystems = [ "nfs" ];
        services.autofs =
          {
            enable = true;
            autoMaster =
              let
                autoData = pkgs.writeText "auto.data"
                  ''
                    * server:/data/&
                  '';
              in
                ''
                  /data file:${autoData}
                '';
          };
        networking.firewall.enable = false;
      };
  };
  testScript =
    ''
      $server->waitForUnit("nfs-server.service");
      $server->succeed("systemctl start network-online.target");
      $server->waitForUnit("network-online.target");
      $server->succeed("test -d /data/foo");
      $server->succeed("exportfs -v | grep /data/foo");

      $client->succeed("mkdir -p /data");  # but not /data/foo; autofs is responsible for creating that
      $client->succeed("systemctl start network-online.target");
      $client->waitForUnit("network-online.target");
      $client->succeed("systemctl restart autofs.service");
      $client->waitForUnit("autofs.service");

      $client->fail("mount | grep /data/foo");
      $client->succeed("echo bla > /data/foo/bar");
      $client->succeed("mount | grep /data/foo");
      $server->succeed("test -e /data/foo/bar");
    '';
}
```

## Technical details

* System: Host system is 17.09.git.f0fac3b (Hummingbird), but probably irrelevant (using own clone of nixpkgs for tests)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: OK in: 17.03pre-git (51a83266d1); broken in: 17.09pre-git (129f8d7e99)
* Sandboxing enabled: build-use-sandbox = false

**Comment by NickHu** [comment]
Also experiencing this

**Comment by javgh** [comment]
I am also experiencing this issue - autofs in 17.09.git.670b4e2 (Hummingbird) is completely broken for me. I don't even use any NFS filesystems, but after failing with `cannot open mount module nfs (...autofs-5.1.3/lib/autofs/mount_nfs.so: undefined symbol: xdr_exports)` autofs reports `no mounts in table` and does nothing.

**Comment by YorikSar** [comment]
Now that 17.09 is out and I've upgraded to it, this issue reproduces for hosts mount too. With this in auto.master:

```
/net      -hosts -nolock --timeout=60
```

I get this in logs:
```
Oct 03 18:31:47 hn automount[966]: failed to to open config /etc/autofs.conf
Oct 03 18:31:47 hn automount[966]: failed to to open old config /autofs
Oct 03 18:31:47 hn automount[972]: Starting automounter version 5.1.3, master map /nix/store/z1s1pxs6nkmmpanh4dbf8bw1ni98jlm5-auto.master
Oct 03 18:31:47 hn automount[972]: using kernel protocol version 5.02
Oct 03 18:31:47 hn automount[972]: lookup_nss_read_master: reading master file /nix/store/z1s1pxs6nkmmpanh4dbf8bw1ni98jlm5-auto.master
Oct 03 18:31:47 hn automount[972]: do_init: parse(sun): init gathered global options: (null)
Oct 03 18:31:47 hn automount[972]: open_mount:294: parse(sun): cannot open mount module nfs (/nix/store/m76x0vvya05i44ayxns6vc3fqly91q4k-autofs-5.1.3/lib/autofs/mount_nfs.so: undefined symbol: xdr_exports)
Oct 03 18:31:47 hn automount[972]: lookup(file): failed to open parse context
Oct 03 18:31:47 hn automount[972]: no mounts in table
```

even before I try to use this mount. `/net` is not mounted at all:

```
% mount | grep /net
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
```

I guess, test by @sometimes-i-send-pull-requests can be simplified with this further.

**Comment by larkery** [comment]
I am also experiencing this fault, with an autofs configuration that doesn't try to use NFS at all (CIFS instead).

It looks like autofs can't start up at all, so it doesn't matter what's in the configuration.

**Comment by larkery** [comment]
Further interesting facts are that
```
$ nm -D /nix/store/0z24sp79mdd58g5wk9pn6954g1zbzjy8-autofs-5.1.3/lib/autofs/mount_nfs.so
```
reports a symbol called `xdr_exports` is mentioned there but not defined there, so I guess `mount_nfs.so` expects to be linked into something which has that symbol?

**Comment by larkery** [comment]
Going into the build I find that the `xdr_exports` symbol ought to be defined in `lib/mount_xdr.o`, but that appears to contain no symbols at all. I don't have any idea why this would happen, as `mount_xdr.c` looks pretty boilerplate and does contain the definition for `xdr_exports` and a bunch of other stuff.

**Comment by larkery** [comment]
Looking through the build a bit more reveals something I don't understand at all: the makefile `strip`s `mount_xdr.o` and some other objects after compiling them, even though they have externs. Stripping a `.o` confuses me anyway as it makes it unlinkable. I'm confused now.   

As far as I can tell, getting rid of the strip commands does not break the build process anywhere, although I haven't tried patching the my installed copy to see if it fixes the bug.

If it does I will report back.

**Comment by larkery** [comment]
So, my grim hack for this is:

```
nixpkgs.config.packageOverrides = pkgs:
  {
     autofs5 = pkgs.lib.overrideDerivation pkgs.autofs5 (a : { buildPhase="STRIP=echo make"; });
  };
```

This does not explain why this regression has happened; the upstream sources and the autofs package are unchanged so it has to be something else in the environment.

**Comment by larkery** [comment]
So a further note on this; the hack above works, but the behaviour of autofs has changed slightly for me, specifically preventing the use of `-Dvar=value` arguments in file maps being passed into the environment for program maps further down the tree. I have no idea why.

**Comment by sometimes-i-send-pull-requests** [comment]
Thanks for that investigation, @larkery! I tried to do a bisection to find the offending commit. I narrowed the range down to:

* Known good: 80a0c5c2fe0f79bf3e0f77c3d09cf545b5f54d9f
* Known bad: ba68231273bea4cba01413fd2a0e56d68db9234c

This is a range of 278 revisions. Unfortunately I'm having trouble bisecting much further; in the middle of that range I get build errors or hangs, which I can't conclusively say do or do not have the autofs problem.

Here is GitHub's comparison between the commits: 80a0c5c2fe0f79bf3e0f77c3d09cf545b5f54d9f...ba68231273bea4cba01413fd2a0e56d68db9234c

**Comment by mkocha2** [comment]
Same issue here: https://github.com/voidlinux/void-packages/issues/7615.

**Comment by orivej** [comment]
It must be caused by the introduction of the `STRIP=/path/to/strip` environment variable, which is used in `Makefile.rules`:

```make
ifdef DONTSTRIP
STRIP     ?= :
else
STRIP     ?= strip --strip-debug
endif
```

This issue is similar to https://github.com/NixOS/nixpkgs/commit/7d010ab5f4ae6f69339139165719bf071295536b
