### ISSUE TITLE
Build failure: khal

### ISSUE THREAD

**Issue by lucc** [NixOS/nixpkgs#282910]
### Steps To Reproduce

1. `nix build nixpkgs#khal`

### Build log

https://gist.github.com/lucc/ba081193674e35e46fa8ae3a9ac02e5f

### Additional context

This might be broken since https://github.com/NixOS/nixpkgs/pull/281721 but I did not bisect.

### Notify maintainers

maintainer: @gebner 

author of #281721: @fabaff 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 24.05 (Uakari), 24.05.20240119.bbe7d8f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/11zbgb8j7wnnccbbjcq0q556h28g7p4r-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> This might be broken since #281721 but I did not bisect.

I can confirm that 5d49eb0352b634e13441e694d50ae8b9d951adc9 broke the test.

One solution would be to override the urwid version khal uses. I also suggest opening an upstream issue.
