### ISSUE TITLE
boot.loader.timeout = null; behavior differs between GRUB and systemd-boot

### ISSUE THREAD

**Issue by fin444** [NixOS/nixpkgs#282925]
### Describe the bug
The description of `boot.loader.timeout` states:
> Use null if the loader menu should be displayed indefinitely.

This works as described with the GRUB module, where in the case of `null` it is set to `-1`.
https://github.com/NixOS/nixpkgs/blob/1b64fc1287991a9cce717a01c1973ef86cb1af0b/nixos/modules/system/boot/loader/grub/grub.nix#L80

However, the systemd-boot module instead just leaves `timeout` out of the config, causing it to fallback to systemd-boot's default `0`.
https://github.com/NixOS/nixpkgs/blob/1b64fc1287991a9cce717a01c1973ef86cb1af0b/nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix#L23

### Expected behavior
When `boot.loader.timeout = null;` the systemd-boot config should set `timeout = menu-force`.

### Notify maintainers
@JulienMalka

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05pre571714.c3e128f3c0ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fpletz** [comment]
Fixed by #201202.
