### ISSUE TITLE
xfce: NetworkManager has no priveleges to save VPN connection

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#28313]
## Issue description

Attempt to add a VPN connection fails with:
![](http://i.imgur.com/fzpbCIj.png)

## Technical details

* System: 17.09

**Comment by yegortimoshenko** [comment]
This is probably not specific to Xfce: Network Manager is just a notification area applet.

**Comment by volth** [comment]
The context menu of that notification area icon has an item "Add a VPN connection...".
It is the dialog box displayed afterwards

**Comment by zarelit** [comment]
Is this still happening? I'm able to add a VPN by using xfce and the default applet, the only relevant group my user is in is  `networkmanager`

**Comment by volth** [comment]
> the only relevant group my user is in is ```networkmanager```

Yes, adding user to this group fixed the issue.
Thank you!
