### ISSUE TITLE
haskellPackage.yi : build failed on missing dependencies.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28311]
## Issue description

    $ nix-shell -p haskellPackages.yi -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
    these derivations will be built:
      /nix/store/vjkawq84mv3fsbxm4k40ndlxb3d5h20i-yi-0.14.1.drv
    building path(s) ‘/nix/store/8c8saajhzb23zwgkv5y7fdg9vx6gdxf6-yi-0.14.1’, ‘/nix/store/v2vxq47fnx79qjjl1494mzh1w76s01dw-yi-0.14.1-doc’
    setupCompilerEnvironmentPhase
    Build with /nix/store/vc269816lgmsk052ipdalx295cn2n5fs-ghc-8.0.2.
    unpacking sources
    unpacking source archive /nix/store/lyzl1bz82zh5g6pz5is4417kza2sl1jc-yi-0.14.1.tar.gz
    source root is yi-0.14.1
    setting SOURCE_DATE_EPOCH to timestamp 1501350238 of file yi-0.14.1/yi.cabal
    patching sources
    compileBuildDriverPhase
    setupCompileFlags: -package-db=/tmp/nix-build-yi-0.14.1.drv-0/package.conf.d -j1 -threaded
    [1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-yi-0.14.1.drv-0/Main.o )
    Linking Setup ...
    configuring
    configureFlags: --verbose --prefix=/nix/store/8c8saajhzb23zwgkv5y7fdg9vx6gdxf6-yi-0.14.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/v2vxq47fnx79qjjl1494mzh1w76s01dw-yi-0.14.1-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-yi-0.14.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/8c8saajhzb23zwgkv5y7fdg9vx6gdxf6-yi-0.14.1/lib/ghc-8.0.2/yi-0.14.1 --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections -fpango -fvty
    Configuring yi-0.14.1...
    Setup: Encountered missing dependencies:
    yi-core >=0.14.1,
    yi-misc-modes >=0.14.1,
    yi-mode-haskell >=0.14.1,
    yi-mode-javascript >=0.14.1
    builder for ‘/nix/store/vjkawq84mv3fsbxm4k40ndlxb3d5h20i-yi-0.14.1.drv’ failed with exit code 1
    error: build of ‘/nix/store/vjkawq84mv3fsbxm4k40ndlxb3d5h20i-yi-0.14.1.drv’ failed
    /run/current-system/sw/bin/nix-shell: failed to build all dependencies

## Technical details

 * System: NixOS: 17.09.git.0c1c3d2 (Hummingbird)
 * Nix version: nix-env (Nix) 1.11.13
 * Nixpkgs version: "17.09pre112899.129f8d7e99"
 * Sandboxing enabled: build-use-sandbox = true

**Comment by thomastjeffery** [comment]
Nix build dependencies pay no attention to versions, and instead work around this fact by providing *more* packages with the version number in the name. (See "closed" issue #9682)

In order to use the correct version, we need to override packages with the newly version-included-in-name packages.

(See #28248)

**Comment by wizzup** [comment]
closed as duplicated of #28248
