### ISSUE TITLE
Syncthing security issue

### ISSUE THREAD

**Issue by lfam** [NixOS/nixpkgs#28310]
## Issue description

The Syncthing project recently released a fix for a security vulnerability, the symlink attack described here:

https://github.com/syncthing/syncthing/issues/4286

The issue was fixed in Syncthing 0.14.35. However, this release contained a serious bug, so 0.14.36 should be used instead.

**Comment by joachifm** [comment]
cc @peterhoeg

**Comment by peterhoeg** [comment]
0.14.36 was already in master but now 17.03 has been updated too. Thanks for spotting this @lfam!
