### ISSUE TITLE
SDDM does not accept password

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#283135]
Describe the bug
-------------------------------------------------------------------------------------
I have recently added a user hashed password and turned ```mutableUsers``` to ```false```. Upon doing that, sddm no longer recognizes any password as being correct. I can however log in fine into the tty with the user and the new password.

Steps To Reproduce
-------------------------------------------------------------------------------------
1. Turn of mutableUsers and change the hashed password;
2. Reboot the computer;
3. Try to type the new password into the sddm instance.

Expected behavior
-------------------------------------------------------------------------------------
The new hashed password should work just fine with sddm *(even with mutableUsers set to false)*.

Metadata
-------------------------------------------------------------------------------------
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0-zen3, NixOS, 24.05 (Uakari), 24.05.20240119.bbe7d8f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by W-Y-R** [comment]
SDDM only works when it is unthemed, but fails when it is themed. Here's my sddm snippet:
```
services.xserver = {
  enable = true;
  xkb.layout = "us";
  displayManager = {
    defaultSession = "hyprland";
    sddm = {
      enable = true;
      wayland.enable = true;
      theme = "where_is_my_sddm_theme";
      settings = {
        Item = {
          id = "cursor";
          visible = "false";
        };

        X11 = {
          ServerArguments = "-nocursor -nolisten tcp";
        };
      };
    };
  };
};

environment.systemPackages = [
  (pkgs.where-is-my-sddm-theme.override {
    themeConfig.General = {
      passwordFontSize = 45;
    };
  })
];
```

**Comment by BlueskyFR** [comment]
@W-Y-R same issue there! I really don't know what is happening. Where you able to solve it in the meantime?

**Comment by W-Y-R** [comment]
Hello, @BlueskyFR! I'm glad to hear that it worked out for you. Unfortunately, the error still persists on my part. For that matter, my user and its session are correctly set when sddm starts even on wayland. Nonetheless, the password screen still loops after each password attempt.

**Comment by dylantompkins** [comment]
As you may guess by the above commit, I am also having this problem. 

Note that setting `services.displayManager.sddm.wayland.enable = false` did not solve the problem.

Also note that I recently had to downgrade my sddm theme to qt5, otherwise only the default theme would load. Could this be related? https://github.com/dylantompkins/nixos-flake/commit/988f688b1f323463279b8859106aef6420a1f6b0

**Comment by ProggerX** [comment]
Same problem
