### ISSUE TITLE
qt6 lrelease not found

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#283188]
### Describe the bug
Building `mpc-qt` (see #280943) fails because `lrelease` cannot be found. The build systems expects it in `qtbase`, but it is provided by `qttools`.

### Steps To Reproduce
1. checkout #280943
2. build `mpc-qt`

### Expected behavior
A successful build of `mpc-qt`.

### Notify maintainers
@milahu
@NickCao

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.git.56e9d11d2023`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
@romildo is this issue about building 23.12 ? Not against it, just a bit unusual since it hasn't been merged yet

**Comment by romildo** [comment]
> @romildo is this issue about building 23.12 ? Not against it, just a bit unusual since it hasn't been merged yet

It is about updating mpc-qt to version 23.12, which migrated to qt6. The mentioned PR fails to build due to the issue reported here. Therefore this issue has to be fixed before mpc-qt can be updated in the nixpkgs repository.

**Comment by romildo** [comment]
At least it fails when building in my unstable system, and also failed on the repository when I made the PR. But it seems to build in the repository now.

**Comment by kirillrdy** [comment]
23.02 builds for me on master, thats why I was checking

**Comment by romildo** [comment]
Then I suppose we can merge https://github.com/NixOS/nixpkgs/pull/280943 now.

**Comment by romildo** [comment]
> 23.02 builds for me on master, thats why I was checking

This version still uses qt5. The new one migrated to qt6.

**Comment by romildo** [comment]
@kirillrdy could you review https://github.com/NixOS/nixpkgs/pull/280943, please?

**Comment by kirillrdy** [comment]
yes, will do, can you close this, as `mpc-qt` builds on master

**Comment by romildo** [comment]
> yes, will do, can you close this, as `mpc-qt` builds on master

I will do that after https://github.com/NixOS/nixpkgs/pull/280943 is reviewed.

**Comment by NickCao** [comment]
We've been having this issue for long: https://github.com/NixOS/nixpkgs/issues/214765. The current fix is just to patch individual packages and hope qmake fade out one day.

**Comment by romildo** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/214765
