### ISSUE TITLE
aspellWithDicts fails when running aspell

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#28318]
## Issue description

I have a line in my shell.nix as follows.

```
aspell = nixpkgs.aspellWithDicts (ps : with ps; [ en ]); 
```

which is then also added to buildInputs.

When running `aspell` in the shell session, it errors on any file with:

```
> aspell -c myfile.tex
Error: The file "/nix/store/hrs9m81c6d7nf31azni9mi9kvss67g8f-aspell-dicts/lib/aspell/iso-8859-1.cset" can not be opened for reading.
```

@FRidh

**Comment by FRidh** [comment]
I've assigned myself but I won't have time to look into this until Tuesday.

What happens when you run
```
$ $(nix-build -E 'with import <nixpkgs> {}; aspellWithDicts(ps: with ps; [ en ])' )/bin/aspell
``
i.e., you run it directly from the store without `nix-shell` setting whatever env vars.

**Comment by mpickering** [comment]
Running

```
$(nix-build -E 'with import <nixpkgs> {}; aspellWithDicts(ps: with ps; [ en ])' )/bin/aspell -c file.tex
```

causes the same error. Running `aspell` without -c prints the help options.

**Comment by FRidh** [comment]
Since I had to spell-check my thesis I figured I might as well fix this.
https://github.com/NixOS/nixpkgs/commit/96457d26dded05bcba8e9fbb9bf0255596654aab works for me.
