### ISSUE TITLE
python3packages.openai-triton-no-cuda not importable

### ISSUE THREAD

**Issue by phiadaarr** [NixOS/nixpkgs#283235]
### Describe the bug
On system without NVIDIA-GPU, triton requires both `setuptools` and `ptxas` during import and crashes as they are not bundled with triton.

To resolve the `setuptools` issue, we could probably just add `setuptools` to the list of dependencies.

Regarding `ptxas`: I see that `ptxas` is explicitly removed from triton via a patch in nixpkgs. I do not know why and also do not know what the package is supposed to be doing. Looking into the triton sources, I have the impression that it is something cuda-related, so it should be possible to entirely remove `ptxas` to let triton run on machines without NVIDIA GPUs.

### Steps To Reproduce
1. flake.nix:
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
      in {
        devShells.default = pkgs.mkShell {
          buildInputs = [
            (pkgs.python3.withPackages
              (ps: [ ps.openai-triton-no-cuda ps.setuptools ]))
          ];
          shellHook = ''
            python3 -c "import triton"
          '';
        };
      });
}
```

2. Run `nix develop` in the directory in which the flake is saved.

### Expected behavior
Python should be able to import triton.

### Notify maintainers

@SomeoneSerge @Madouura 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 23.11 (Tapir), 23.11.20240120.1b64fc1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(philipp): `"nixos-23.05"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
> Regarding ptxas: I see that ptxas is explicitly removed from triton via a patch in nixpkgs. I do not know why

Because `ptxas` is unfree and if we kept it we couldn't have Hydra build and cache the package

>  via a patch in nixpkgs

Actually, there should've been a patch merged upstream to make cuda-free usage easier, I don't recall what happened to it at this point.

> triton requires both setuptools and ptxas during import

This sounds wrong, possibly an issue upstream. I think it shouldn't ask for `setuptools` even though triton does do compilation at runtime.

Similarly, there have been patches to make ptxas optional, so it shouldn't be required at import time, only when using cuda-specific features.

**Comment by SomeoneSerge** [comment]
> 
> - channels(philipp): `"nixos-23.05"`
> - channels(root): `"nixos-23.11"`

Actually, can you check if `openai-triton` from `master` or `nixpkgs-unstable` works for you?

RE: optional ptxas patch

You can find references to the previous discussions by following https://github.com/NixOS/nixpkgs/pull/272364#discussion_r1428465241

> My approach would be to fork both triton and nixpkgs, push changes to my triton fork, adapt the reference in nixpkgs locally, calculate the sha256sum and then build with nix-build -A python3Packages.openai-triton

I guess, clone triton, work out and commit the patches, then use something like `git format-patch origin/master HEAD`. These patches you can check in in the nixpkgs repo and add to `openai-triton`'s `patches`. If you change any of the "fixed-output derivations" (`fetcurl`, `fetchpatch`, `fetchFromGitHub`) you have to update the hashes. You can start by putting an empty one (`hash = ""` or `hash = lib.fakeHash` iirc), running the build, and copying the observed hash

**Comment by phiadaarr** [comment]
Related: PR #286763

**Comment by SomeoneSerge** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/286763

**Comment by phiadaarr** [comment]
Confirmed. Many thanks!
