### ISSUE TITLE
NixOS 23.11: gcc12 always first in PATH when `nix-shell -p gcc11` or  `nix-shell -p gcc13`

### ISSUE THREAD

**Issue by phip1611** [NixOS/nixpkgs#283248]
### Describe the bug

In the last two weeks, a bug was introduced in NixOS 23.11. It works with the state from 2024-01-06 and not with the state from 2024-01-23.

When I run `nix-shell -p gcc11` or  `nix-shell -p gcc13`, always `gcc12` comes first in PATH. This also happens in an empty environment; when initially no gcc is in PATH. Also pure shells are affected.

### Steps To Reproduce
1. `nix-shell -p gcc11` or  `nix-shell -p gcc13`
2. `which -a gcc` shows:
  ```
  /nix/store/vylmp73qymnv4siaqn1kl2hghj07hrj8-gcc-wrapper-12.3.0/bin/gcc
  /nix/store/f94yr35af3xdiscbj6cp6kafvmn55gv9-gcc-12.3.0/bin/gcc
  /nix/store/nccy5ljli9i0aglfnh6m74f9f7cdd080-gcc-wrapper-13.2.0/bin/gcc
  /nix/store/rcr4bqw8nd84limc19kh12q68pxqzbyr-gcc-13.2.0/bin/gcc
  /etc/profiles/per-user/<user>/bin/gcc

  ```

### Expected behavior
Only one gcc in the selected version should be added.

### Screenshots
None.

### Additional context
I can verify it on multiple machines from multiple people.

### Notify maintainers

@Synthetica9 @vcunat @Ericson2314 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 23.11 (Tapir), 23.11.20240122.d7f206b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(pschuster): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/0zqp13i2jys5amxmyfxjr6kj62m7ncya-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by phip1611** [comment]
Interestingly, `nix-shell -p` always pulls in a gcc:

https://github.com/NixOS/nix/blob/master/src/nix-build/nix-build.cc#L276

> `joined << "{...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) \"shell\" { buildInputs = [ ";` 

Nevertheless, something must have changed in the last couple of weeks.

**Comment by vcunat** [comment]
nix-shell uses stdenv which pulls the default gcc.  That's never changed in the history.

**Comment by vcunat** [comment]
If you want to switch compilers, I'd suggest
- write a `shell.nix` file
- use modified stdenv, e.g. `(overrideCC pkgs.stdenv pkgs.gcc13).mkDerivation {...}`

Having multiple C compilers visible at once in a shell is generally asking for trouble.

**Comment by phip1611** [comment]
Nevertheless, something must have changed in the past weeks that changes the order of the includes. I and another person could verify on different systems that it worked 2 weeks ago and gcc13 was used indeed.

**Comment by phip1611** [comment]
I apologize. It also didn't work with older NixOS versions. Turns out I was mixing this up in my memory with situations where I got gcc13 from `shell.nix` - which works indeed.

Do you know these moments when you are 100% sure something worked two weeks ago, you try to reproduce it and then you are like: "what the heck is going on?!" 😅
