### ISSUE TITLE
Incus can't find zvol_id

### ISSUE THREAD

**Issue by mkgvt** [NixOS/nixpkgs#283250]
### Describe the bug

Incus fails to find `zvol_id` when launching a VM. (There is no problem launching a container.) It exits with the error message:
```
Error: Failed instance creation: Failed creating instance from image: exec: "zvol_id": executable file not found in $PATH
```
Lines 1815-1824 of incus/internal/server/storage/drivers/driver_zfs_volumes.go in the [Incus source code](https://github.com/lxc/incus) looks for it at `/lib/udev/zvol_id` or in the path. I think it means that there is a fixup that isn't being done.

### Steps To Reproduce
1. `incus launch images:ubuntu/22.04/desktop test --vm --console=vga` (The specific image doesn't seem to matter.)
2. Wait while the VM is created... It exits with the error message above.
3. Verify that `zvol_id` is installed at `ls $(readlink $(which zfs) | sed 's:/bin.*::')/lib/udev/zvol_id` just not being found.

### Expected behavior

Launching a VM should work as expected without the error message.

### Notify maintainers

@adamcstephens 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 23.11 (Tapir), 23.11.20231217.1e2e384`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Never mind @mkgvt I see the problem. Will take some time to get this reviewed, backported, and available to 23.11
