### ISSUE TITLE
fetchgit/fetchFromGitHub fail to fetch submodules from "git@server:repo" URLs

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#28324]
https://github.com/kryptco/kryptonite-android/blob/master/.gitmodules is
```
[submodule "libsodium-jni"]
	path = libsodium-jni
	url = git@github.com:kryptco/libsodium-jni
[submodule "zxing"]
	path = zxing
	url = https://github.com/zxing/zxing
[submodule "identicon"]
	path = identicon
	url = https://github.com/KryptCo/identicon
[submodule "ssh-wire"]
	path = ssh-wire
	url = git@github.com:kryptco/ssh-wire
```

so both ```fetchgit``` and ```fetchFromGitHub``` fail with ```Could not create directory '/var/empty/.ssh'```

### Steps to reproduce

```nix
  fetchFromGitHub {
    owner = "kryptco";
    repo = "kryptonite-android";
    rev = "2.2.3";
    fetchSubmodules = true;
    sha256 = "0000000000000000000000000000000000000000000000000000";
  }
```

```nix
  fetchgit {
    url = "https://github.com/kryptco/kryptonite-android";
    rev = "2.2.3";
    fetchSubmodules = true;
    sha256 = "0000000000000000000000000000000000000000000000000000";
  }
```

<hr/>

Related "https://github.com/NixOS/nixpkgs/pull/26695 fetchgit: support "git@server:repo" URLs "

<hr/>

UPD: Fail even without submodules:
```nix
  fetchgit {
    url = "git@github.com:kryptco/kryptonite-android";
    rev = "2.2.3";
    sha256 = "0000000000000000000000000000000000000000000000000000";
  }
```

**Comment by disassembler** [comment]
Since your using user@github.com instead of a public repo url, you need to use fetchgitPrivate. See this blog post for usage: https://www.mpscholten.de/nixos/2016/07/07/private-github-repositories-and-nixos.html

**Comment by volth** [comment]
But it is not a private repo. Perhaps it was private some time ago and still has private-style links to submodules

**Comment by fgaz** [comment]
I can reproduce this. The repos are public but fetchgit fails
