### ISSUE TITLE
Rusticl broken: "GLIBC_2.38 not found"

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#283259]
### Steps To Reproduce
1. add `hardware.opengl.extraPackages = [ pkgs.mesa.opencl ];` and rebuild NixOS
2. run clinfo
3. 0 OpenCL platforms detected
4. run `LD_DEBUG=libs clinfo` for detailed library loading logs, ending in an error message:
```
      6108:	/nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/libc.so.6: error: version lookup error: version `GLIBC_2.38' not found (required by /nix/store/hxigprhy2r2bw782d1f3bph1pc3csxcr-mesa-23.3.3-opencl/lib/libRusticlOpenCL.so) (fatal)
```

### Expected behavior
clinfo should print Rusticl as a detected OpenCL platform (with or without any actual devices depending on hardware configuration and the `RUSTICL_ENABLE` env variable)

### Notify maintainers

@vcunat @K900 @primeos 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240123.0e0b162`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
Where does your glibc 2.37 come from?  You're clearly mixing different nixpkgs versions together.

**Comment by jansol** [comment]
Is there some convenient command for figuring that out? I do have a few flakes set up (most notably nix-community/kde2nix) but they all have `inputs.nixpkgs.follows = "nixpkgs"` so my understanding is that they should use the same one?

**Comment by jansol** [comment]
Aaaaah, the problem was that I tried running clinfo via `nix-shell -p clinfo`. The system is built with flakes, but nix-shell still uses the old channels that hadn't been updated in months. `sudo nix-channel --update` fixed it.
