### ISSUE TITLE
QML2_IMPORT_PATH is not set by package qtquickcontrols2

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#28336]
## Issue description

The package qtquickcontrols2 does not set QML2_IMPORT_PATH, so the qml files cannot be found.

#### workaround

```bash
export  QML2_IMPORT_PATH=$QML2_IMPORT_PATH:$(nix-env --query --no-name --out-path  qtquickcontrols2)/lib/qt-5.9/qml
```

### Steps to reproduce

1) install qtquickcontrols2
2)
Write this to test.qml

```qml
import QtQuick.Controls 2.2

Page {
    id: page
    hoverEnabled: true
    Label {
        text: "Hello QtQuick.Controls 2"
        font.pixelSize: 100
        font.italic: page.hovered
    }
}
```
3) open `qmlscene test.qml`

## Technical details

* System: (NixOS: 17.03.1623.138313fe01 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: nix-env (Nix) 1.11.13 and 17.09pre-git
* Sandboxing enabled: build-use-sandbox = true

**Comment by vandenoever** [comment]
I've written a better script for setting `QML2_IMPORT_PATH`. In `nix-shell`, the environment variable `CMAKE_PREFIX_PATH` can serve as input.

```bash
#!/usr/bin/env bash

# Source this file to set QML2_IMPORT_PATH
# We use information from CMAKE_PREFIX_PATH

# read the setting for nullglob ('on' or 'off')
nullglob=$(shopt nullglob | cut -f 2)
# turn on nullglob
if [ $nullglob = "off" ]; then
    shopt -s nullglob
fi

QML2_IMPORT_PATH=
for v in $(echo "$CMAKE_PREFIX_PATH" | tr : '\n' | sort | uniq); do
    list=($v/lib/*/qml)
    for f in "${list[@]}"; do
        if [ -z "$QML2_IMPORT_PATH" ]; then
            QML2_IMPORT_PATH=$f
        else
            QML2_IMPORT_PATH=$QML2_IMPORT_PATH:$f
        fi
    done
done
export QML2_IMPORT_PATH

# turn nullglob back to the initial value
if [ $nullglob = "off" ]; then
    shopt -u nullglob
fi
```

**Comment by 22459** [comment]
I second this as I just ran across it earlier. Would be nice if some variant of qt5.full handled this because I only solved it by some lucky googling and manually setting the variable.

 Maybe there are also other environment variables that are also not being set?

**Comment by charles-dyfis-net** [comment]
`[ $nullglob = "off" ]` is exactly backwards. `off` can't possibly need to be quoted -- it's a constant. `"$nullglob"` should be quoted so it's correctly parsed as exactly one word, even if it somehow doesn't include one of the expected single-word values.

**Comment by berberman** [comment]
It seems that this issue still exists.
