### ISSUE TITLE
Build failure: torch-2.2.0-rc8

### ISSUE THREAD

**Issue by jkachmar** [NixOS/nixpkgs#283343]
### Steps To Reproduce

1. create `test.nix` with the contents specified in the snippet below
    - `nixpkgs/nixos-unstable` from 2024-01-03, so pretty recent
2. `nix build -f test.nix`
3. observe that the build fails with the error `ModuleNotFoundError: No module named 'six'`

<details> <summary> test.nix </summary>

```
let
  src = builtins.fetchTarball { url = https://github.com/NixOS/nixpkgs/archive/e2e36d8af3b7c465311f11913b7dedd209633c84.tar.gz; };
  pkgs = import src {};
  python3 = pkgs.python3.override {
    packageOverrides = final: prev: {
      pytorch = prev.pytorch.overrideAttrs (old: rec {
        name = "${old.pname}-${version}";
        version = "2.2.0-rc8";
        src = pkgs.fetchFromGitHub {
          owner = "pytorch";
          repo = "pytorch";
          rev = "refs/tags/v${version}";
          fetchSubmodules = true;
          hash = "sha256-FfFjgx6yrPEQlF8CLglsWq+zWGr6MD4z0F+lYoy6grc=";
        };
      });
    };
  };
in python3.pkgs.pytorch
```

</details>

### Build log

```
[0/6025] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/any_lite.cc.o
[0/6025] Building CXX object third_party/protobuf/cmake/>
FAILED: confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o /build/source/build/confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o
cd /build/source/build/confu-deps/NNPACK && PYTHONPATH=/build/source/build/confu-srcs/six:/build/source/third_party/python-peachpy /nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3>
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/build/source/third_party/python-peachpy/peachpy/__init__.py", line 39, in <module>
    from peachpy.literal import Constant
  File "/build/source/third_party/python-peachpy/peachpy/literal.py", line 1, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

### Additional context

i attempted to build the latest `torch` nightly & found that it fails with an error that i can't quite make sense of.

`2.1.2` builds just fine, and the only thing upstream that i noticed that seems like it could be related is https://github.com/pytorch/pytorch/pull/108236, which drops the `third_party` dep (presumably because they didn't need it?).

i'm pretty out of my depth when it comes to understanding the intricacies of the `pytorch` build system though; i guess they're using `buck`?

### Notify maintainers

@teh @thoughtpolice @tscholak

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
Hi @jkachmar , is this still an issue as I can't reproduce this running either `nix build .#python3Packages.torch` or `nix build .#python3Packages.torch-bin`

**Comment by jkachmar** [comment]
@kashw2 this is no longer an issue strictly as-listed, but fwiw if you check the blame for this code you can see that the workaround was to disable NNPACK[^1].

this isn't a problem for me, but i imagine it might be for others.

---

[^1]: https://github.com/NixOS/nixpkgs/blame/055ed44f4018d96aa14bffb56410b85069fa9315/pkgs/development/python-modules/torch/default.nix#L254-L256
