### ISSUE TITLE
Random programs.k9s.skin error

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#283488]
Describe the bug
----------------------------------------------------------------
I have no recollection of ever enabling this. I don't even have it in my configuration as far as I know. It just appeared out of the blue.
```
warning: The option `programs.k9s.skin' defined in `/nix/store/ld1ynqm356ch7ggwyh7al7nh6v4yhqpc-modules/k9s/hm.nix' has been renamed to `programs.k9s.skins.skin'.
```

Steps To Reproduce
----------------------------------------------------------------
This is something I would like to know as well.

Expected behavior
----------------------------------------------------------------
No error should appear for a program which I don't even have installed.

Metadata
----------------------------------------------------------------
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0-zen3, NixOS, 24.05 (Uakari), 24.05.20240121.612f972`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bddvlpr** [comment]
This is related to HomeManager, not nixpkgs.
[Link to renamed option](https://github.com/nix-community/home-manager/blob/6b28ab2d798c1c84e24053d95f4ee1dd9d81e2fb/modules/programs/k9s.nix#L18)

**Comment by bddvlpr** [comment]
To add to that, you are likely using a styling module (like [Stylix](https://github.com/danth/stylix/blob/81de262bf170ce4152950402e17eba1453a3ebfe/modules/k9s/hm.nix#L10)) that is (currently) still set to use this old option.
