### ISSUE TITLE
python36: lack of _uuid_generate_time breaks uuid.uuid1()

### ISSUE THREAD

**Issue by washort** [NixOS/nixpkgs#28349]
## Issue description

https://github.com/NixOS/nixpkgs/commit/0a7e705f629c8dee29b06bb4c0be867e15c45059 breaks `uuid.uuid1()`

### Steps to reproduce

`nix-shell -p python36 --run "python -c 'import uuid; print(uuid.uuid1())'" `
yields
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/uuid.py", line 516, in uuid1
    if _uuid_generate_time and node is clock_seq is None:
NameError: name '_uuid_generate_time' is not defined
```

Additionally, some Python libraries such as `freezegun` assume `_uuid_generate_time` is present.

**Comment by FRidh** [comment]
Interesting, I ported this patch from 2.7, but apparently removed one line that should not have been removed
https://github.com/NixOS/nixpkgs/commit/de1b4e71c1c8be30ad4ebc2ec6005928ba6cf280#diff-a8b2767db9f18a8dde1a92bcb134c15cR47

**Comment by FRidh** [comment]
Hopefully tomorrow I find the time to fix the patch. Or could you open a PR with updated patches for 3.x?

**Comment by Mic92** [comment]
Build of `python3Packages.tweepy` is also affected by this.

**Comment by FRidh** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/commit/a7ddca6e3dce865a6a07cbdaea3963026b7bb3d3.
