### ISSUE TITLE
qml not installed for qtcharts

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#28343]
## Issue description

QtCharts has a c++ and QML api. At the moment the QML parts are not installed.

https://doc.qt.io/qt-5/qtcharts-index.html

#28336 is a similar issue, but there QML files are installed, but the QML2_IMPORT_PATH is not set.

### Steps to reproduce

1) nix-env -i qtcharts
2) find /nix/store/\*qtcharts* -name '*.qml'

## Technical details

* System: (NixOS: 17.03.1623.138313fe01 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: nix-env (Nix) 1.11.13 and 17.09pre-git
* Sandboxing enabled: build-use-sandbox = true

**Comment by vandenoever** [comment]
@ttuegel do you have an idea what could be missing from `qtcharts.nix`? `qtgraphicaleffects.nix` installs QML files but has no dedicated instruction to make that happen.

**Comment by ttuegel** [comment]
Yes, `qtcharts` does not list any `qtdeclarative` dependency, so it is built without.
