### ISSUE TITLE
Update request: meshlab 2022.02 → 2023.12

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#283539]
- Package name: meshlab
- Latest released version: 2023.12
- Current version on the unstable channel: 2022.02
- Current version on the stable/release channel: 2022.02
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@viric

Changelog: https://github.com/cnr-isti-vclab/meshlab/discussions/1449

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nim65s** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/299049
