### ISSUE TITLE
Python build support scripts uses bash 4 features, but stdenvNative may lack bash 4

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#2835]
`pkgs/development/python-modules/generic/wrap.sh` has `declare -A pythonPathsSeen=()`; older versions of bash don't have the array type.

**Comment by iElectric** [comment]
@joelteon is this still important for darwin?

**Comment by domenkozar** [comment]
@pikajude is this still relevant? What could be a possible fix?
