### ISSUE TITLE
CI build for libgda-5.2.4 broken

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#28371]
As can be seen at https://travis-ci.org/NixOS/nixpkgs/jobs/265852828 the build for libgda-5.2.4 is broken.
I can't reproduce the problem on my Fedora machine with
`nix-build -K -A gnome3.libgda`
so I guess it's a problem within the environment of the CI machine.

**Comment by ThomasMader** [comment]
cc @domenkozar @garbas @matthewbauer

**Comment by matthewbauer** [comment]
This is probably an issue in [madjar/nox](https://github.com/madjar/nox). Try running ```nix-shell -p nox --run 'nox-review pr 27743'``` to confirm though.

**Comment by ThomasMader** [comment]
Hydra built many libgda packages in the meantime so I just close this.
