### ISSUE TITLE
systemd-boot-builder.py can take minutes to run when /nix/store contains many elements

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#283795]
### Describe the bug
Because systemd-boot-builder.py gets stored straight up as `/nix/store/....-systemd-boot` (as a file in `/nix/store`), Python imports will crawl through the whole `/nix/store` directory to try and find local .py files that can be imported. This can take very long and a lot of RAM.

We hit into this on rhea.nixos.org which has 40M entries in its `/nix/store` right now, causing `systemd-boot-builder.py` to take 5-10minutes and 10GB of RAM to execute.

### Steps To Reproduce
1. Fill up your `/nix/store` with a LOT of entries
2. Switch to a new configuration with systemd-boot as the configured bootloader.

### Expected behavior
Switching to a new configuration doesn't take 5+ minutes and 10GB of RAM, but is instead near-instantaneous.

### Screenshots
n/a

### Additional context
Stack trace taken 1min into the execution of the script showing it's stuck trying to import stuff:
```
Traceback (most recent call last):
  File "/nix/store/741fq6239vz49kcm6r2l4x3fk4v67q20-systemd-boot", line 3, in <module>
    import shutil
  File "/nix/store/h31x3zrwrws1c3392919br8g9isvhh4x-python3-3.10.13/lib/python3.10/shutil.py", line 22, in <module>
    import bz2
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
KeyboardInterrupt
```

### Notify maintainers

@JulienMalka 

### Metadata
This is on NixOS 23.05 but I don't see any change that would impact this in 23.11 or master. Would love a backport all the way to 23.05 if possible since we still haven't updated rhea.nixos.org :)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by delroth** [comment]
Just to track the backport.

**Comment by wamserma** [comment]
Maybe needs to be spinned of into a separate issue, but I think there are more Python scripts affected by this, such as `auto-patchelf.py` or `catch-conflict.py`.

Quick search:
`find /nix/store -maxdepth 1 -type f -name "*.py"`

**Comment by delroth** [comment]
No strong opinion, I don't personally care about getting those fixed right now so it might be easier if you filed it as a new issue if you're interested in working on it.

**Comment by JulienMalka** [comment]
Will close this because this specific issue is solved, but feel free to open other issues for the other python scripts that suffer from this problem.
