### ISSUE TITLE
`update-lingering` activation script is broken

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#283769]
https://github.com/NixOS/nixpkgs/pull/260248#discussion_r1428504292

```
[ERROR]   stderr) Could not enable linger: Connection timed out
[ERROR]   stdout) Activation script snippet 'update-lingering' failed (123)
[ERROR]   stderr) Failed to list users: Connection timed out
[ERROR]   stderr) Unable to close the file handle to loginctl at /nix/store/hiw28n1i7mmr7sh7ds66g9nmxdbf7kdv-nixos-system-cetus-23.11pre-git/bin/switch-to-configuration line 890.
```

nixpkgs input: `github:NixOS/nixpkgs/093cffd33371b29257a4302206c214e87a0297ac`

cc @ToxicFrog @amaxine

**Comment by aanderse** [comment]
since this is broken to a degree that it puts a system in a state where it cannot be updated if any user is removed and no one has addressed this in the two months since i brought it up i think it might be a good idea to simply revert the PR

@SuperSandro2000 - any thoughts on that?

**Comment by SuperSandro2000** [comment]
Can we fix this with a three line change or not? Can we check if the user exists in users.users and then skip the disable?
If the fix is not trivial, we should at least mark it properly.

**Comment by amaxine** [comment]
Wouldn't a quick and acceptable fix be to not fail when disabling lingering fails because the user doesn't exist, and still clean up the dangling linger file? It does seem like a preferable fix to wholesale reverting this, and one that should hopefully be relatively minor.

**Comment by aanderse** [comment]
great

so is someone able to take this on? @ToxicFrog

**Comment by ToxicFrog** [comment]
This is hopefully a quick fix, but I don't have the brainwidth right now to implement and properly test it, and likely won't until sometime next week at the earliest.

I know there's been some work on a more comprehensive overhaul over in #261319; I don't know what that's waiting for to be mergeable, but unless it's ready to go now, my preference would be to simply roll back to stop causing problems for people, then roll forward with that change later.

**Comment by aanderse** [comment]
@ToxicFrog - thanks for the reply, i appreciate just hearing back from you on the issue - don't worry about scheduling, if you're busy you're busy :heart:

if anyone has capacity to look at this, awesome, and if not i'll see what i can do... but i also would take me a few weeks to get around to this

i appreciate that there is engagement in this thread, thanks everyone!

**Comment by jwillikers** [comment]
I think I can fix this if I understand it correctly, which is that it is failing to remove a user that no longer exists.

**Comment by aanderse** [comment]
that's correct

i recently had to remove a user from a number of systems and if i recall correctly the systems in which the user had logged into, thereby activating lingering, would no longer activate until the lingering file under `/var` had been removed

i would greatly appreciate if you fixed this

thank you!

**Comment by jwillikers** [comment]
I've opened #292847 to fix this.

**Comment by aanderse** [comment]
thank you so much everyone!
