### ISSUE TITLE
Package request: IPOPT free (with MUMPS)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [NixOS/nixpkgs#283854]
**Project description**

IPOPT exists already in packages but is not free. 

Also code of IPOPT is free, it depends on very unfree HSL lib  (you cannot download it for free nor use commerically).

Without linear package IPOPT is not usable at all.

https://www.hsl.rl.ac.uk/index.html

https://github.com/scipopt/scip/issues/82#issuecomment-1895393569

IPOPT works with MUMPS which is free and seems can use commericially

https://github.com/scivision/mumps

here is example of flake with MUMPS for IPOPT

https://github.com/coin-or/Ipopt/pull/744

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wentasah** [comment]
Isn't this resolved by commit 5cdcd1a2051bb0013cc3e1e8f2bac4f7493f8235?
