### ISSUE TITLE
Update request:  BleachBit 4.4.0 → BleachBit 4.6.0

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#283810]
Package name: BleachBit 
Latest released version: BleachBit 4.4.0

Search your package here: BleachBit

 Current version on the unstable channel: 4.4.0

 Current version on the stable/release channel: 4.4.0

Type the name of your package and try to find an open pull request for the package
If you find an open pull request, you can review it!
There's a high chance that you'll have the new version right away while helping the community!

 [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@mbprtpmnr 

If the search.nixos.org result shows no maintainers, tag the person that last updated the package. --> https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=bleachbit

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lebensterben** [comment]
@stnert 

Hi Fábio, as of today (Apr 25 2024), `bleachbit` is still of version `4.4.0` on `unstable` channel. (It prompts you to update it on launch. And `bleachbit --version` also shows `4.4.0`)
