### ISSUE TITLE
`lib.fileset.gitTracked` does not work with `--store`

### ISSUE THREAD

**Issue by PigeonF** [NixOS/nixpkgs#283843]
### Describe the bug

When using `lib.fileset.gitTracked` in combination with `--store`, the build fails with `lib.fileset.gitTracked: Expected the argument (/tmp/nix-store/nix/store/8a5a320f0h66jh066qabxkm67msvbcql-source) to point to a local working tree of a Git repository, but it's not.`

### Steps To Reproduce

1. Create a new git repository 
2. Add the following `flake.nix`

    ```nix
    {
      inputs = {
        nixpkgs.url = "github:NixOS/nixpkgs/release-23.11";
      };
    
      outputs = {nixpkgs, ...}: {
        packages.x86_64-linux.default = let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
          fs = pkgs.lib.fileset;
        in
          pkgs.stdenvNoCC.mkDerivation {
            name = "gitTrackedBug";
    
            src = fs.toSource {
              root = ./.;
              fileset = fs.gitTracked ./.;
            };
    
            buildPhase = "touch $out";
          };
      };
    }
    ```
3. Build with `nix build` (works as expected)
4. Build with `nix build --store /tmp/nix-store/` (this fails)

### Additional context

I'm pretty sure this is the same underlying issue as #269283. I think the issue is that the `hasStorePathPrefix` check fails when it should trigger in the `chroot`-ed nix store https://github.com/NixOS/nixpkgs/blob/4551ff176fbb4c7b1b2e35d0149ccc8bf0d9f5b5/lib/fileset/internal.nix#L913

`hasStorePathPrefix` has a note about usage with other filesystem roots, which seems relevant

https://github.com/NixOS/nixpkgs/blob/066ccb996b252de54bbfd04a42fd1486e2971a92/lib/path/default.nix#L398-L402

but I don't know enough about how the actual `--store` implemention works under the hood to comment further.

### Notify maintainers

@infinisil 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
This looks like a Flake-specific issue, consider:

```nix
{
  outputs = { ... }: {
    path = ./.;
    storeDir = builtins.storeDir;
  };
}
```

```
$ nix eval .#storeDir
"/nix/store"
$ nix eval .#path
/nix/store/f5dc7kgs97658c024mlnx0wn9j95ns91-source
$ nix eval .#storeDir --store /tmp/nix-store/
"/nix/store"
$ nix eval .#path --store /tmp/nix-store/
/tmp/nix-store/nix/store/f5dc7kgs97658c024mlnx0wn9j95ns91-source
```

I believe `--store` works by creating a Linux user namespace, bind mounting `/nix/store` to the alternate location. This is how it can justify returning `/nix/store` as the store directory. However then it should also make Nix path expressions use `/nix/store`, which doesn't appear to be the case.

While `lib.fileset` _could_ hack around this by trying to detect a `/nix/store/<hash>` _infix_ instead of just a prefix, I'd rather have the issue be resolved at the root.

Could you file this as an issue on https://github.com/NixOS/nix?

**Comment by infinisil** [comment]
Thanks for opening an issue with Nix (https://github.com/NixOS/nix/issues/9852). Closing this issue since it's not an issue with Nixpkgs.
