### ISSUE TITLE
qt4 build fails during installPhase [Darwin]

### ISSUE THREAD

**Issue by lukeadams** [NixOS/nixpkgs#28385]
## Issue description
qt4 fails during the install phase
[[hydra](https://hydra.nixos.org/build/58837766)]
```
make[1]: Entering directory '/private/tmp/nix-build-qt-4.8.7.drv-0/qt-everywhere-opensource-src-4.8.7/src/corelib'
make -f Makefile.Release install
make[2]: Entering directory '/private/tmp/nix-build-qt-4.8.7.drv-0/qt-everywhere-opensource-src-4.8.7/src/corelib'
"/nix/store/yc00923s1wacd726fwf5yn9nkxbkfkxy-qt-4.8.7/lib/QtCore.framework/Contents/MacOS/QtCore"
/nix/store/p436632iqmvvzn2m0rg5wj270xr9niap-bash-4.4-p12/bin/bash: /nix/store/yc00923s1wacd726fwf5yn9nkxbkfkxy-qt-4.8.7/lib/QtCore.framework/Contents/MacOS/QtCore: No such file or directory
make[2]: *** [Makefile.Release:29195: install_target] Error 127
make[2]: Leaving directory '/private/tmp/nix-build-qt-4.8.7.drv-0/qt-everywhere-opensource-src-4.8.7/src/corelib'
make[1]: *** [Makefile:46: release-install] Error 2
make[1]: Leaving directory '/private/tmp/nix-build-qt-4.8.7.drv-0/qt-everywhere-opensource-src-4.8.7/src/corelib'
make: *** [Makefile:226: sub-corelib-install_subtargets-ordered] Error 2
note: keeping build directory ‘/private/tmp/nix-build-qt-4.8.7.drv-0’
builder for ‘/nix/store/kb7j85g6h8458a93rp0bvhfgaczphdc7-qt-4.8.7.drv’ failed with exit code 2
error: build of ‘/nix/store/kb7j85g6h8458a93rp0bvhfgaczphdc7-qt-4.8.7.drv’ failed
```
The file in question is built but the install phase seems to be depending on the nix-store location before it is copied there. 

```
ls /private/tmp/nix-build-qt-4.8.7.drv-0/qt-everywhere-opensource-src-4.8.7/lib
...
QtCore.framework
...
```

There also seem to be a few possibly erroneous file deletions by the build system:
```
rm -f QtCore QtCore.framework/QtCore ../../lib/QtCore.framework/QtCore
...
mv -f QtCore ../../lib/QtCore.framework/Versions/4/QtCore
ln -s Versions/4/QtCore ../../lib/QtCore.framework/QtCore
rm -f ../../lib/QtCore.framework/Versions/Current
ln -s 4 ../../lib/QtCore.framework/Versions/Current
...
```

### Steps to reproduce
`nix-build '<nixpkgs>' -A qt4 -K`

## Technical details

* System: (MacOS 10.11)
* Nix version: (`1.11.13`)
* Nixpkgs version: (`17.09pre-git`)
* Sandboxing enabled: (`relaxed`)

@vcunat

**Comment by lukeadams** [comment]
```
8d76effc178747f0c8f456fe619c1b014736a6af is the first bad commit
commit 8d76effc178747f0c8f456fe619c1b014736a6af
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Tue Jul 11 16:04:14 2017 -0400

    stdenv-setup: Make the package accumulators associative arrays instead of strings

    This is generally cleaner: less eval, less worrying about separators,
    and probably also faster. I got the idea from that python wrapper
    script.

:040000 040000 eaaa23ebaebbc4c33d6f920b544a2122b37e41fd 0e333474aa6dae7536d1a08b3eeb105fe1a34063 M	pkgs
```
> https://github.com/NixOS/nixpkgs/commit/8d76effc178747f0c8f456fe619c1b014736a6af

**Comment by lukeadams** [comment]
Not sure if it's something that we would want committed to the repo, but overriding the installPhase and manually copying bin, include, etc does result in working output.

**Comment by vcunat** [comment]
*I missed the mention somehow, though I can't see how the issue is related to me.*

I can't say I understand the root of this.  It tries to install/copy file(s) into a directory that wasn't created (yet).  Perhaps some `mkdir -p "$out"/lib/QtCore.framework/Contents/MacOS/QtCoreError` before installation would fix it?  (I don't even have a Darwin machine.)

**Comment by lukeadams** [comment]
@vcunat No worries; I edited you in way after creating this issue, since you were mentioned in the build definition (in case you had seen a similar issue on Linux).

The installPhase seems to be deleting the framework (QtCore.framework/Contents/QtCore) before it gets copied, based on the fact that it is left on the system (nix-build ... -K) when the installPhase is shimmed. Now that I think about it I can probably add a postConfigure hook to remove the offending line.

**Comment by lukeadams** [comment]
https://gist.github.com/lukeadams/78007a6692944f4d772a6bf528c504ae
Here I overrode the installPhase with 
```
installPhase = ''
    make -j1 --ignore-errors install
'';
```
It generates the library directories in $out/lib, but doesn't copy contents over as seen in the tree output.

**Comment by lukeadams** [comment]
```
  installPhase = optionalString stdenv.isDarwin ''
    cp -r lib $out

    mkdir -p $out/Applications
    mv bin/*.app $out/Applications
    rm -rf bin/*.app

    cp -r bin $out
    cp -r include $out

    mkdir -p $out/share/doc/${name}
    mkdir -p $out/lib
    mkdir -p $out/lib/qt4/plugins
    mkdir -p $out/lib/qt4/imports
    mkdir -p $out/bin
    mkdir -p $out/share/${name}
    mkdir -p $out/share/${name}/translations
    mkdir -p $out/include

    cp -r plugins $out/lib/qt4
    cp -r imports $out/lib/qt4
    cp -r doc/* $out/share/doc/${name}
  '';

  postInstall = optionalString (!stdenv.isDarwin) ''
      rm -rf $out/tests
  '';
```
Gives working output. I'm testing with a few qt-dependant packages and will submit a pr later today.
