### ISSUE TITLE
polybar with githubSupport fails because of missing curl header

### ISSUE THREAD

**Issue by mrkgnao** [NixOS/nixpkgs#28387]
## Issue description

With `githubSupport = true` in `packageOverrides`, `polybar` fails to find `curl/curlbuild.h`, which I understand does not exist in recent versions of `curl`. See https://github.com/jaagr/polybar/issues/647, which deals with this.

### Steps to reproduce

```nix
{
 # ...
  nixpkgs.config.packageOverrides = pkgs: {
    polybar = pkgs.polybar.override {
      i3GapsSupport = true;
      iwSupport = true;
      mpdSupport = true;
      # uncomment this
      # githubSupport = true;
    };
  };
 # ...
}
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by jfrankenau** [comment]
I believe this issue can be closed.
