### ISSUE TITLE
LLVM[8-11] Removal Progress Tracker

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#283954]
# LLVM8 (removed)
- https://github.com/NixOS/nixpkgs/pull/283551
### Issues
- Modification for windows is just a best guess with no test. https://github.com/NixOS/nixpkgs/pull/283551/commits/56504908440cf45db6d32f70eaec341c983e3d68
- probably ready for removal

# LLVM9
- https://github.com/NixOS/nixpkgs/pull/283653
- https://github.com/NixOS/nixpkgs/pull/283767
- https://github.com/NixOS/nixpkgs/pull/283989
- https://github.com/NixOS/nixpkgs/pull/284167
- https://github.com/NixOS/nixpkgs/pull/284865
- https://github.com/NixOS/nixpkgs/pull/284315

#### cling
- [cling](https://github.com/root-project/cling) can build updated interpreter but requires copying c/c++ header files. unclear what version to use to update the package as it also needs to interface with [xeus-cling](https://github.com/jupyter-xeus/xeus-cling) which claims to [support](https://github.com/jupyter-xeus/xeus-cling#dependencies) for >= 0.9 but less than < 0.10 (1.0) 
- [xeus-cling](https://github.com/jupyter-xeus/xeus-cling) a jupyter kernel and the only consumer of cling

#### haskell
- ~haskell code contains one heavily used  llvm_9 reference  https://github.com/NixOS/nixpkgs/blob/e49dc530ba25ba507f0ded60c8f29cbc1e2570a9/pkgs/development/haskell-modules/configuration-nix.nix#L496~

# LLVM10 (removed)
- https://github.com/NixOS/nixpkgs/pull/283678
- https://github.com/NixOS/nixpkgs/pull/283681
- https://github.com/NixOS/nixpkgs/pull/283685
- https://github.com/NixOS/nixpkgs/pull/283824
- https://github.com/NixOS/nixpkgs/pull/283863
- https://github.com/NixOS/nixpkgs/pull/283913

### Issues
- ready for removal

# LLVM11 (removed)
- https://github.com/NixOS/nixpkgs/pull/288977
- https://github.com/NixOS/nixpkgs/pull/288958
- https://github.com/NixOS/nixpkgs/pull/288959
- https://github.com/NixOS/nixpkgs/pull/288960
- https://github.com/NixOS/nixpkgs/pull/283591

### Issue
- ~https://github.com/NixOS/nixpkgs/pull/283591/commits/71aa397303be17ad72fc405c81bb6b354eb577dd needs testing for freshBootstrapTools. https://github.com/NixOS/nixpkgs/pull/283591#issuecomment-1908879638~

**Comment by sternenseemann** [comment]
`llvm-hs` is marked broken at the moment. It is unclear to me what the status of the project is at the moment. There are branches that support later versions, but there are no such packages uploaded to Hackage.
