### ISSUE TITLE
Update request: ocamlPackages.ppxlib 0.30.0 → 0.31.0

### ISSUE THREAD

**Issue by chewblacka** [NixOS/nixpkgs#283987]
- Package name: ocamlPackages.ppxlib
- Latest released version:  0.31.0

- Current version on the unstable channel:  0.30.0
- Current version on the stable/release channel:  0.30.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@vbgl 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vbgl** [comment]
What should we do regarding `vcaml`?

**Comment by chewblacka** [comment]
> What should we do regarding `vcaml`?

I was hoping you would have a solution! I'm a complete newb to ocaml and it's ecosystem. 

       last 10 log lines:
       > Error: The functor application is ill-typed.
       >        These arguments:
       >          $S1 Open_on_rhs_intf ()
       >        do not match these parameters:
       >          functor (X : Base__Applicative_intf.For_let_syntax) (Intf : ...)
       >          (Impl : Intf.S) -> ...
       >        1. Module $S1 matches the expected module type Base__Applicative_intf.For_let_syntax
       >        2. Module Open_on_rhs_intf matches the expected module type
       >        3. The functor was expected to be applicative at this position

Also for `ppx_cstubs`

       last 10 log lines:
       > File "src/internal/ppxc__script_real.ml", line 171, characters 26-43:
       > 171 | module C_content_phase0 = C_content_make ()
       >                                 ^^^^^^^^^^^^^^^^^
       > Error: The functor was expected to be applicative at this position

My aim is to get `timedesc` packaged (in order to package another application), but that requires `ppxlib` to be updated first.

**Comment by vbgl** [comment]
There is `timedesc` for you:  #284030

**Comment by chewblacka** [comment]
> There is `timedesc` for you: #284030

Amazing thanks! That completely bypasses the issue. Will take a look!

**Comment by chewblacka** [comment]
Marking this as closed as the `timedesc` is what I actually wanted and that works perfectly. Many thanks!
