### ISSUE TITLE
Update request: Topgrade 13.0.0 → 14.0.1

### ISSUE THREAD

**Issue by SteveLauC** [NixOS/nixpkgs#283959]
- Package name: Topgrade
- Latest released version: 14.0.1

- Current version on the unstable channel: 13.0.0
- Current version on the stable/release channel: 13.0.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by raspher** [comment]
Maintainers: @XYenon @SuperSandro2000

**Comment by SuperSandro2000** [comment]
Please search PRs before opening a new issue #283213

**Comment by SteveLauC** [comment]
> Please search PRs before opening a new issue #283213

I am sorry about this, I will close this issue
