### ISSUE TITLE
home-assistant using incompatible (latest) version of python-kasa

### ISSUE THREAD

**Issue by hughobrien** [NixOS/nixpkgs#283941]
### Describe the bug
python-kasa recently updated to 0.6.x from 0.5.x. The home-assistant project does not yet support 0.6.x, as a result kasa functionality is degraded.

### Steps To Reproduce
Using HomeAsisstant from latest nixpkgs, attempt to get emeter data from kasa devices.

### Additional context
I reported this issue upstream [here](https://github.com/home-assistant/core/issues/108881) and they advised on the version issue. There are more logs visible there.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment]
I guess that if we would run the  `tplink` unit tests then the issue with 0.6.0 would have been detected.
