### ISSUE TITLE
`babashka` has broken Unicode support

### ISSUE THREAD

**Issue by slotThe** [NixOS/nixpkgs#283953]
### Describe the bug

This is somewhat related to https://github.com/NixOS/nixpkgs/issues/260161, I think, and it seems like https://github.com/NixOS/nixpkgs/pull/267861 has not completely fixed the issue in all cases.

### Steps To Reproduce

``` console
$ nix run 'github:NixOS/nixpkgs/nixos-unstable#babashka' -- -e '(:out (babashka.process/sh "echo" "ä"))'
"?\n"
```

The expected output is, of course, `"ä\n"`. The full process output is as follows:

``` console
$ bb -e '(babashka.process/sh "echo" "ä")'
{:proc #object[java.lang.ProcessImpl 0x9456cc7 "Process[pid=534672, exitValue=0]"], :exit 0, :in #object[java.lang.ProcessImpl$ProcessPipeOutputStream 0x4ca7015 "java.lang.ProcessImpl$ProcessPipeOutputStream@4ca7015"], :out "?\n", :err "", :prev nil, :cmd ["echo" "ä"]}
```

### Additional context

I should note that merely printing Unicode does work as expected, so this is perhaps something specific to
process handling:

``` console
$ bb -e '(System/getProperty "stdout.encoding")'
"UTF-8"

$ bb -e '(prn "bépo àê")'
"bépo àê"
```

### Notify maintainers

@bandresen @bhougland @DerGuteMoritz @jlesquembre @thiagokokada

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 24.05 (Uakari), 24.05.20240125.4fddc9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/ildml01gk7v91fba35whklllfi343lvq-source`
```

**Comment by thiagokokada** [comment]
Opened a PR to fix this: https://github.com/NixOS/nixpkgs/pull/283973
