### ISSUE TITLE
Package request: Spotube

### ISSUE THREAD

**Issue by Esteban528** [NixOS/nixpkgs#284081]
**Project description SPOTUBE**
An open source, cross-platform Spotify client compatible across multiple platforms
utilizing Spotify's data API and YouTube (or Piped.video or JioSaavn) as an audio source,
eliminating the need for Spotify Premium

**Metadata**

* homepage URL: https://spotube.netlify.app/
* source URL: https://github.com/KRTirtho/spotube
* license: GNU GENERAL PUBLIC LICENSE GPL
* platforms: unix, linux, mac, android

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/282975

**Comment by tomodachi94** [comment]
Specifically, closes #282975 (GitHub magic will automatically close this when the PR is merged)

**Comment by TomaSajt** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/282975
