### ISSUE TITLE
Wine seems not to build in parallel

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#28405]
## Issue description
I gather from `nix-instantiate --eval '<nixpkgs>' -A wine.enableParallelBuilding` outputting `true` that wine should build in parallel. However, it does not seem to do so. This is a bit of an annoyance as it takes very long to build.

### Steps to reproduce
`nix-build -j9 '<nixpkgs>' -A wine --check` and in another terminal `watch pgrep -a gcc` — there only ever seems to be one process running.

## Technical details

- System: 17.03.1700.51a83266d1 (Gorilla)
- Nix version: nix-env (Nix) 1.11.13
- Nixpkgs version: "17.03.1700.51a83266d1"
- Sandboxing enabled:  true

**Comment by gebner** [comment]
This is not very obvious, but you just need to set the `build-cores` option to `0`:
```
nix-build --option build-cores 0 -A wine
```

**Comment by lheckemann** [comment]
Ooooh yes of course, I forgot that -j is for number of builds running in parallel and that `--cores` (shorter than `--option build-cores` :p ) is for parallelism within builds… Never mind me…

**Comment by a1russell** [comment]
How do I pass this option when I'm installing it via `nix-env`?

**Comment by lheckemann** [comment]
`nix-env --cores 9 …`

**Comment by a1russell** [comment]
Thanks @lheckemann !
