### ISSUE TITLE
Installing cabal2nix 2.4 via nix-env fails on running doctests

### ISSUE THREAD

**Issue by ArtUshak** [NixOS/nixpkgs#28403]
## Issue description
Installing cabal2nix 2.4 via nix-env fails on running doctests (see [log.txt](https://github.com/NixOS/nixpkgs/files/1236386/log.txt))

### Steps to reproduce
`$ nix-env -i cabal2nix`

## Technical details
* System: Ubuntu 16.04.3 LTS
* Nix version: 1.11.13
* Nixpkgs version: 17.09pre112229.e619ace733
* Sandboxing enabled: /etc/nix/nix.conf

**Comment by puffnfresh** [comment]
Thanks for the detailed issue. I checked out version e619ace733 but I am not able to reproduce. My derivation hash is different to yours. Do you have some custom nixpkgs configuration? Maybe some Haskell overrides?

**Comment by Ekleog** [comment]
Looks like this doesn't happen any longer, and any additional knowledge about the initial issue is most likely lost since, so let's just close.
