### ISSUE TITLE
SANE: BJNP discovery is blocked by default firewall rules

### ISSUE THREAD

**Issue by lluchs** [NixOS/nixpkgs#28406]
## Issue description

With the default firewall configuration, network discovery of Canon scanners does not work.

### Steps to reproduce

1. Have a Canon scanner in the local network.
2. Enable SANE (`hardware.sane.enable = true;`)
3. Run `scanimage -L`
4. Observe that the Canon scanner isn't listed.

## Technical details

Discovery of Canon scanners works via multicast. SANE sends BJNP discovery messages from all local addresses to `ff02::1`, UDP port 8612. Scanners receiving the message respond via unicast UDP.

Apparently, iptables does not see responses to multicast requests as related and blocks them. A possible solution would be to open UDP port 8612 in the firewall when enabling SANE.

* System: current NixOS unstable

**Comment by adc17** [comment]
Hi @lluchs, did you ever get this working on your own machine?

**Comment by lluchs** [comment]
As I've written, the workaround is to open UDP port 8612 explicitly. Something like:

```
networking.firewall = {
  allowedUDPPorts = [ 8612 ];
};
```

**Comment by lluchs** [comment]
As far as I can see, there have been no relevant changes to the sane configuration.

**Comment by bjornfor** [comment]
I just spent a day debugging this, without knowing about this issue :facepalm:

(Btw, scanner discovery can also break thanks to some weird/bad interaction between avahi and IPv6 -- I ended up disabling IPv6 on my scanner to make detection work.)

Maybe we should add a `hardware.sane.openFirewall` option, to make this a bit more discoverable?

**Comment by bjornfor** [comment]
Another option is to enable `hardware.sane.extraBackends = [ pkgs.sane-airscan ];` by default. That doesn't require opening up the firewall. Ubuntu has it enable by default.

**Comment by eliasp** [comment]
I believe this issue can be closed, since:
- [0cf8b1c](https://github.com/NixOS/nixpkgs/commit/0cf8b1c078e5564ee3a6abf5b07e656c424f0ea1) added the required `openFirewall` option
- `sane-airscan` offers an alternative

Feel free to re-open if you believe there's still a problem and add some details about your setup/problem.
