### ISSUE TITLE
Package request: Code-Editor Zed

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#284064]
Package request: Code-Editor Zed

Linux support is coming:
https://github.com/zed-industries/zed/issues/5395

Hope that we also get a Nix package when that happens :)

Official page is: https://zed.dev/

**Comment by jtbx** [comment]
There's already a pull request for it, see #284010
Currently it only adds support for Darwin.

**Comment by boustanihani** [comment]
Thanks, didn't notice, I'll close this issue.

**Comment by muneebusmani** [comment]
this needs to be opened because zed isnt still available for linux

**Comment by eclairevoyant** [comment]
@muneebusmani zed does not support linux. Though this can stay open until the darwin PR merges.

**Comment by michaelCTS** [comment]
That's now untrue @eclairevoyant  https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md

**Comment by YarekTyshchenko** [comment]
PR #284010 does add support for linux (nixos), but not all things work yet. It might be worth opening an issue listing all the broken things

**Comment by tv42** [comment]
The PR is merged, and zed-editor in nixpkgs seems to work well enough on Linux (NixOS) these days.

I had to `ln -s $(which rust-analyzer) ~/.config/zed/languages/rust-analyzer/rust-analyzer-2024-04-29` to get the Rust language support working, I think that's the usual thing where silly upstreams download executables from the internet and expect them to work right. And Zed's error handling for that kinda sucked, it can get stuck in a loop.

There's some obvious bugs like Zed will crash if you push key combinations that don't exist on macOS, but I've done hours of programming with it already.

I think this issue can be closed, and more specific issues opened for the rest of the work.

**Comment by aMyTimed** [comment]
cant copilot
![image](https://github.com/NixOS/nixpkgs/assets/52638772/0cb590b9-2824-478e-904a-8c23a3c94e00)
![image](https://github.com/NixOS/nixpkgs/assets/52638772/a28d1558-fe33-413d-b991-0b44a95839ed)
is that a packaging issue

**Comment by tv42** [comment]
Update to earlier, putting a rust-analyzer symlink in `~/.config/zed/languages/rust-analyzer` still makes their upgrade checks run, crap out, and remove or ignore your file.

Instead, you have to put this in `~/.config/zed/settings.json`:

```json
  "lsp": {
    "rust-analyzer": {
				"binary": {
						"path": "/nix/store/vlq2srikjqhkv57jx6pa198g8zxr9ajr-rust-analyzer-2024-04-29/bin/rust-analyzer",
				},
    },
  },
```

I haven't yet figured out a way to do that without hardcoding the path there -- hot mess, I need to update the config every now and then, especially if one needs different rust-analyzer versions for different projects. I'm assuming it'll need code changes. https://github.com/zed-industries/zed/blob/f550f23b97bcb0d900d7c321af7d91d52d97160e/crates/languages/src/rust.rs#L36 is the code path that undocumented config triggers.

**Comment by davidak** [comment]
There is a package, but it does not work (for me). https://github.com/NixOS/nixpkgs/issues/312266

**Comment by nxy7** [comment]
> > Update to earlier, putting a rust-analyzer symlink in `~/.config/zed/languages/rust-analyzer` still makes their upgrade checks run, crap out, and remove or ignore your file.
> > Instead, you have to put this in `~/.config/zed/settings.json`:
> > ```json
> >   "lsp": {
> >     "rust-analyzer": {
> >       "binary": {
> > 	"path": "/nix/store/vlq2srikjqhkv57jx6pa198g8zxr9ajr-rust-analyzer-2024-04-29/bin/rust-analyzer",
> >       },
> >     },
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't yet figured out a way to do that without hardcoding the path there -- hot mess, I need to update the config every now and then, especially if one needs different rust-analyzer versions for different projects. I'm assuming it'll need code changes. https://github.com/zed-industries/zed/blob/f550f23b97bcb0d900d7c321af7d91d52d97160e/crates/languages/src/rust.rs#L36 is the code path that undocumented config triggers.
> 
> You can also link to rust-analyzer like this: `"path": "/etc/profiles/per-user/patka/bin/rust-analyzer"` So you don't have to update the store path everytime you do an update.

This only works if you install things via `nix profile install` right? Won't be useful with devshells and other methods. I'm wondering if zed could follow helix here which to my knowledge checks if things are in path (at least as a fallback?) instead of looking into specific directory. I think it makes managing such dependencies much easier.
