### ISSUE TITLE
photoprism nixos module: cannot use /var/lib/photoprism/photoprism-manage

### ISSUE THREAD

**Issue by Pablo1107** [NixOS/nixpkgs#284084]
### Describe the bug
Cannot use script `/var/lib/photoprism/photoprism-manage` created by the photoprism nixos module.

### Steps To Reproduce
Example config:
```nix
    services = {
      photoprism = {
        enable = true;
        port = 2342;
        originalsPath = "/var/lib/private/photoprism/originals";
        # importPath = "/home/pablo/Android/Camera";
        address = "0.0.0.0";
        settings = {
          PHOTOPRISM_ADMIN_USER = "admin";
          PHOTOPRISM_ADMIN_PASSWORD = "admin";
          PHOTOPRISM_DEFAULT_LOCALE = "en";
          PHOTOPRISM_DATABASE_DRIVER = "mariadb";
          PHOTOPRISM_DATABASE_NAME = "photoprism";
          PHOTOPRISM_DATABASE_SERVER = "/run/mysqld/mysqld.sock";
          PHOTOPRISM_DATABASE_USER = "photoprism";
          # PHOTOPRISM_SITE_URL = "http://sub.domain.tld:2342";
          PHOTOPRISM_SITE_TITLE = "My PhotoPrism";
        };
      };
      mysql = {
        enable = true;
        # dataDir = "/data/mysql";
        package = pkgs.mariadb;
        ensureDatabases = [ "photoprism" ];
        ensureUsers = [
          {
            name = "root";
            ensurePermissions = {
              "*.*" = "ALL PRIVILEGES";
            };
          }
          {
            name = "pablo";
            ensurePermissions = {
              "*.*" = "ALL PRIVILEGES";
            };
          }
          {
            name = "photoprism";
            ensurePermissions = {
              "photoprism.*" = "ALL PRIVILEGES";
            };
          }
        ];
      };
    };
```

And then with the instance up and running:

```console
root@nixos ~
❯ /var/lib/photoprism/photoprism-manage users ls
ERRO[2024-01-26T18:58:06Z] Error 1698: Access denied for user 'photoprism'@'localhost'

root@nixos ~ 1m 2s
❯ mysql -u photoprism photoprism
ERROR 1698 (28000): Access denied for user 'photoprism'@'localhost'

root@nixos ~
❯ sudo -u photoprism /var/lib/photoprism/photoprism-manage users ls
sudo: unable to execute /var/lib/photoprism/photoprism-manage: Permission denied

root@nixos ~
❯ ls -la $(realpath /var/lib/photoprism/photoprism-manage)
-r-xr-xr-x 1 root root 759 Jan  1  1970 /nix/store/1ip8qpa0625qc4lgzmq0hpc3g5nkvb78-manage
```

### Expected behavior
The `photoprism-manage` script should work and list the users.

### Additional context
Seems that the systemd service running photoprism runs as user `photoprism`, which mariadb's unix socket auth works correctly. And the `photoprism-manage` uses the same user `photoprism`, but do not let `root` user to access the database as user `photoprism`. Maybe this can be fix by changing the database user to `root` but that implies changing that in the systemd service user as well. 

### Notify maintainers

@Stunkymonkey 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/mrckm9b3v6wg2fljdp3z4pja1sz07g3z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Stunkymonkey** [comment]
have a look at https://github.com/NixOS/nixpkgs/pull/207567#issuecomment-1799985107

PRs are welcome.

**Comment by Pablo1107** [comment]
> have a look at [#207567 (comment)](https://github.com/NixOS/nixpkgs/pull/207567#issuecomment-1799985107)
> 
> PRs are welcome.

Here is the [original comment](https://github.com/NixOS/nixpkgs/pull/207567#issuecomment-1367963999) he's referring.

So basically we could change the `photoprism-manage` script to grab the UID of the photoprism user and the PID of the systemd service and then execute the `photoprism` binary?
