### ISSUE TITLE
pdfcrop, contained in texlive's collection-binextra misses a runtime dependency to ghostscript

### ISSUE THREAD

**Issue by vanschelven** [NixOS/nixpkgs#28411]
It is possible to install the executable `pdfcrop`, which depends on `ghostscript`, without installing `ghostscript`.

To add `pdfcrop` to my system, I added the following to my `/etc/nixos/configuration.nix`:

```
  environment.systemPackages = [
    # ... packages removed for brevity ...

    (pkgs.texlive.combine {                                                                                                                                                          
      inherit (pkgs.texlive) collection-binextra;
    })

    # ...  more packages

  ];
```

I then ran `pdfcrop`:

```
$ pdfcrop eelco-nixos-phd.pdf 
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
!!! Error: Ghostscript exited with error code 127!
```

Adding `pkgs.ghostscript` to the list of system packages resolves the above problem.

As I understand it, this is a bug in the nixos packaging. In particular, the runtime dependency of the `pdfcrop` utility on `ghostscript` should somehow be expressed.

Feel free to correct me if it isn't a bug.

## Technical details
```
$ nixos-version 
17.03.1316.412b0a17aa (Gorilla)
$ nix-env --version
nix-env (Nix) 1.11.10
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1316.412b0a17aa"
$ grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = false
```

**Comment by vyp** [comment]
I agree that I think this is a bug, a user should not have to manually declare a *dependency* in their configuration for a package that they want to use. I'm not sure there is a better way instead of just patching the source code to replace all calls to ghostscript with the nix variable that points to the ghostscript interpreter. I'm not sure how to do that though, and would also like to know how to do this for myself if anyone does know. My idea would be to have a nix expression somehow generate a patch file (which Nix would then use to patch the source code before building/installing).

For this case in particular, I think the patch could instead simply set the `$::opt_gscmd` variable at L142. I'm not sure if that would still work for pdfcrop's restricted mode though (see L627-L631).

**Comment by vyp** [comment]
Forgot to mention it here, but we don't need to "generate a patch file" or anything like that as I thought, we can just run sed commands or something, and it's actually somewhat common to do so as I found out recently. So this is an easy fix, just now need to figure out the file structure of the `collection-binextra` package and find out where pdfcrop lies in it. 🙂

**Comment by vyp** [comment]
@vcunat I can't figure it out, how can we find out the path to `pdfcrop` under `collection-binextra`?

**Comment by vcunat** [comment]
Will you test this patch to be more sure?  https://github.com/vcunat/nixpkgs/commit/db549016973b86

**Comment by vanschelven** [comment]
I have tested the patch provided, and it "works for me". Slightly more precisely: I've tested the patch by creating an equivalent patch on the 17.03 branch, and rerunning my original test with the workaround that I mentioned above removed.

**Comment by vanschelven** [comment]
This is what the cherry-picked patch that I tested looks like:

```
$ git diff
diff --git a/pkgs/tools/typesetting/tex/texlive/combine.nix b/pkgs/tools/typesetting/tex/texlive/combine.nix
index 9af1d6a59f..390b7b9e5e 100644
--- a/pkgs/tools/typesetting/tex/texlive/combine.nix
+++ b/pkgs/tools/typesetting/tex/texlive/combine.nix
@@ -15,7 +15,10 @@ let
   pkgList = rec {
     all = lib.filter pkgFilter (combinePkgs pkgSet);
     splitBin = lib.partition (p: p.tlType == "bin") all;
-    bin = mkUniquePkgs splitBin.right;
+    bin = mkUniquePkgs splitBin.right
+      ++ lib.optional
+          (lib.any (p: p.tlType == "run" && p.pname == "pdfcrop") splitBin.wrong)
+          (lib.getBin ghostscript);
     nonbin = mkUniquePkgs splitBin.wrong;
 
     # extra interpreters needed for shebangs, based on 2015 schemes "medium" and "tetex"
diff --git a/pkgs/tools/typesetting/tex/texlive/default.nix b/pkgs/tools/typesetting/tex/texlive/default.nix
index 6f4c780e30..58b4b34917 100644
--- a/pkgs/tools/typesetting/tex/texlive/default.nix
+++ b/pkgs/tools/typesetting/tex/texlive/default.nix
@@ -29,6 +29,7 @@ let
   combine = import ./combine.nix {
     inherit bin combinePkgs buildEnv fastUnique lib makeWrapper writeText
       perl stdenv python ruby;
+    ghostscript = ghostscriptX; # could be without X, probably, but we use X above
   };
 
   # the set of TeX Live packages, collections, and schemes; using upstream naming
```

**Comment by vcunat** [comment]
Yes, I believe there's been no relevant changes since 17.03; it should just apply the same.

**Comment by vyp** [comment]
@vcunat why not just patch the source file directly instead? (That way there's no potential for new collisions, and I also think it's 'cleaner'.) Is it cause the build process for it is too automated and hard to modify, or something?

**Comment by vcunat** [comment]
That's another nice way, but it would be a bit more complicated, because now all non-compiled TeX Live packages are fixed-output derivations.  That has an advantage that they will never need "rebuild", whatever changes happen in nixpkgs.

**Comment by vyp** [comment]
Ah fair enough. (But so why can't we patch the src of a fixed-output derivation? sorry for my ignorance.)

**Comment by vcunat** [comment]
We could create a derivation that takes the original fixed-output one and produces the one patched with ghostscript.  (It's not possible to refer to ghostscript from a fixed-output derivation.)

**Comment by vyp** [comment]
> It's not possible to refer to ghostscript from a fixed-output derivation.

Ah I understand now.

How can we make a derivation that takes the fixed-output one? If this is too complicated/time consuming, then that's fair. :+1:

**Comment by vcunat** [comment]
Maybe [around here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive/default.nix#L41); I don't directly see an easy way of doing it with the current texlive nix-expressions, and I'm personally not motivated enough to try ATM.
