### ISSUE TITLE
acpid's ac-power handler not executing scripts/commands on changes to the charging state

### ISSUE THREAD

**Issue by Keshav13142** [NixOS/nixpkgs#284168]
### General description
I'm running NixOs on my laptop with Hyprland as my WM. 
I'm using a shortcut to manually change my refresh rate from 144Hz to 60Hz in case I'm running on battery.

I was searching for a way to automate this using something, when I stumbled upon the [acpid service](https://search.nixos.org/options?channel=unstable&show=services.acpid.handlers&from=0&size=50&sort=relevance&type=packages&query=acpid)
I tried to execute my script using the same, but was not able to do so, then I copied the exact code from the example given in the docs which outputs some log to `/tmp/acpi.log` but the file was not created at all.

### Steps to reproduce the behavior:
1. Enable the acpid service
2.  Paste the code given in the example.
3. Rebuld NixOs

### I tried 2 ways of doing the same

1. Using `acEventCommands`
```nix
services.acpid = {
  enable = true;
  acEventCommands = ''
      vals=($1)  # space separated string to array of multiple values
      case ''${vals[3]} in
          00000000)
              echo unplugged >> /tmp/acpi.log
              ;;
          00000001)
              echo plugged in >> /tmp/acpi.log
              ;;
          *)
              echo unknown >> /tmp/acpi.log
              ;;
      esac
  '';
};
```

2. Using `handlers.ac-power`
```nix
services.acpid = {
  enable = true;
  handlers.ac-power = {
    action = ''
      # Same action as above method
    '';
    event = "ac_adapter/*";
  };
}

```

### Expected behavior
I want to run my script based on charging state of the battery

### Screenshots
![Sat-27-Jan-24_10-00-22-AM](https://github.com/NixOS/nixpkgs/assets/55992029/ecc251a0-8f63-4bbd-9711-b6358dfd768d)

### Additional context
The  powerEventCommands seems to be  working fine, cause the system correctly suspends when I press the power button.

```nix
services.acpid = {
  enable = true;
  powerEventCommands = ''
    systemctl suspend
  '';
};
```

### Maintainers
@JohnAZoidberg @nbp 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240121.612f972`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Tungsten842** [comment]
This was broken by: [acpid: Disable network access ](https://github.com/NixOS/nixpkgs/commit/fb8b20d90e69d93b6886a4cb80039ca185b73b89)
Made by @rht

**Comment by NickCao** [comment]
Reverted in https://github.com/NixOS/nixpkgs/pull/285100

**Comment by Keshav13142** [comment]
Hey, sorry to open this again,  but I updated my flake.lock file and rebuilt my system again.
Still the scripts for the acpid's acEventsCommands are not being executed.
Am I missing something?

**Comment by Tungsten842** [comment]
> Hey, sorry to open this again, but I updated my flake.lock file and rebuilt my system again. Still the scripts for the acpid's acEventsCommands are not being executed. Am I missing something?

The revert has not landed yet: https://nixpk.gs/pr-tracker.html?pr=285100

**Comment by Keshav13142** [comment]
Oh okayy, that makes sense.
I did not know that!!, thanks for letting me know🙂
