### ISSUE TITLE
customization function makeScopeWithSplicing' messes up bash-completion for nix-shell -p

### ISSUE THREAD

**Issue by TomHutter** [NixOS/nixpkgs#284162]
### Describe the bug

bash tab completion for command `nix-shell -p` is not working for letters m - z.

### Steps To Reproduce
1. nix-shell -p l <tab> <tab>
Display all 1728 possibilities? (y or n)
l2md   ... lzwolf

2. nix-shell -p m <tab> <tab>
Display all 9413 possibilities? (y or n)
m17-cxx-demod  ... zzuf

2. nix-shell -p n <tab><tab>
empty

### Expected behavior
tab completion for letters m to z work correctly

### Additional context
Running `set -x` shows the suggestion list for packages which contains:

~~~bash
compgen -P '' -W 'AAAAAASomeThingsFailToEvaluate
....
makeRustPlatform makeScopeWithSplicing makeScopeWithSplicing'\'' makeSetupHook makeShellWrapper makeStatic makeStaticBinaries makeStaticDarwin makeStaticLibraries makeWrapper makebootfat makefile2graph makemkv maker-panel makerpm makeself
....
zzuf' -- m
~~~ 

I am pretty sure the customization function `makeScopeWithSplicing'` (ends with single quote) in https://github.com/NixOS/nixpkgs/blob/master/lib/customisation.nix messes up `compgen` when evaluating the list of packages. 
Running  `compgen ` in the shell with all packages except the `makeScopeWithSplicing'\'' ` string and everything works as expected.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.13, NixOS, 23.11 (Tapir), 23.11.git.a77ab169a83a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/opt/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomHutter** [comment]
I build an overlay to delete all strings in `${packages[*]}` ending with '  via `sed` before feeding them to `compgen`.

/etc/nixos/configuration.nix:
~~~nix
  nixpkgs.overlays = [
    (final: prev:
      {
        nix-bash-completions = prev.nix-bash-completions.overrideAttrs (old: {
          patches = (old.patches or []) ++ [
            /etc/nixos/overlays-compat/_nix.patch
          ];
        });
      }
    )
  ];
~~~

with patchfile /etc/nixos/overlays-compat/_nix.patch:

~~~patch
diff --git a/_nix b/_nix
index 455c173..8d688ad 100644
--- a/_nix
+++ b/_nix
@@ -58,6 +58,9 @@ function _nix_attr_paths () {
 NIX_FILE
     ))

+    # Drop functions like makeScopeWithSplicing' (single quote at the end)
+    local -a packages=($(echo ${packages[*]} | sed "s/ [^ ]*'//g"))
+
     # Don't insert space as we'll too often have to backspace and add a '.'
     compopt -o nospace
     # Generate the completion list prefixed with $attr_path and match against
~~~

Now bash-completion for `nix-shell -p` works again for letters a-z.

**Comment by ncfavier** [comment]
Thanks for reporting! Fix is in https://github.com/NixOS/nixpkgs/pull/285294
