### ISSUE TITLE
AMD graphical glitch on newer kernels (6.7+)

### ISSUE THREAD

**Issue by aktaboot** [NixOS/nixpkgs#284111]
### Describe the bug

A graphical glitch that happens semi-randomly, something that may be triggering it is moving a window from a Screen to another, the glitch can come and go for while moving windows but once it has been triggered a first time, it stays.
 
I can say with confidence that this bug started happening after the 6.7 kernel release, and only on the newer kernels (after triggering it many times and it not being triggered when i launch an lts kernel, when my workload has been practically the same)

Couldn't find anything alarming when reading the systemd journal

Unfortunately, also couldn't find something related on https://bugs.kde.org/

 ```
Operating System: NixOS 24.05
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.7.1
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
Memory: 30.6 GiB of RAM
Graphics Processor: AMD Radeon Graphics
 ```

### Screenshots

Not really a screenshot, it's a picture of the screen since the glitch is not visible on screenshots.
It does however appear on both of the connected displays (one of which is the laptops internal display), but not necessarily both at the same time.

![glitch](https://github.com/NixOS/nixpkgs/assets/120214979/2823951a-60ba-4431-8f51-81878130ea14)

### Notify maintainers
Not sure exactly who to ping, I think @K900 might be concerned (sorry if not) I couldn't find the plasma default.nix

---

Add a :+1: [reaction] to [issues you find important].

**Comment by K900** [comment]
That just looks like a link issue, have you tried kernel 6.7.2 yet? There's some amdgpu DisplayPort fixes in there.

**Comment by aktaboot** [comment]
I was able to reproduce this glitch on 6.7.2 kernel.


### Additional information
Disabling one of both displays, seem to fix the glitch (until the display is re-enabled) so it does seem to be closely related to having multiple displays.

**Comment by aktaboot** [comment]
I'm pretty sure it's an AMD issue:  https://gitlab.freedesktop.org/drm/amd/-/issues/3097

Will try the patch soon

Should I close this issue ?

**Comment by aktaboot** [comment]
I can confirm that the patch indeed fixed the issue

**Comment by taha-yassine** [comment]
> I can confirm that the patch indeed fixed the issue

I have the same issue. What patch exactly worked for you?

**Comment by aktaboot** [comment]
The 3 patches are now upstream, on 6.8-rc5 (which  linux_testing now follows)

Otherwise you can apply them manually: https://gitlab.freedesktop.org/drm/amd/-/issues/3097#note_2267750
