### ISSUE TITLE
fastfetch on darwin-x86_64 doesn't render correctly

### ISSUE THREAD

**Issue by genebean** [NixOS/nixpkgs#284271]
### Describe the bug
While on release-23.11, fastfetch fails to build. Running via `nix run nixpkgs#fastfetch` works, but produces a question mark instead of an Apple log and has virtually no coloring to the output. Running fastfetch via homebrew works just fine. The nix one produces the wrong os info as well.

```
warning: Git tree '/Users/gene.liverman/repos/dots' is dirty
building the system configuration...
warning: Git tree '/Users/gene.liverman/repos/dots' is dirty
error: builder for '/nix/store/ynhqjg6p8g2s1llpjpab1cgvlh8fk89j-fastfetch-2.2.3.drv' failed with exit code 2;
       last 10 log lines:
       > 20 errors generated.
       > 20 errors generated.
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1756: CMakeFiles/libfastfetch.dir/src/detection/cursor/cursor_apple.m.o] Error 1
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1924: CMakeFiles/libfastfetch.dir/src/detection/media/media_apple.m.o] Error 1
       > 20 errors generated.
       > 20 errors generated.
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1812: CMakeFiles/libfastfetch.dir/src/detection/font/font_apple.m.o] Error 1
       > make[2]: *** [CMakeFiles/libfastfetch.dir/build.make:1672: CMakeFiles/libfastfetch.dir/src/detection/bluetooth/bluetooth_apple.m.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/ynhqjg6p8g2s1llpjpab1cgvlh8fk89j-fastfetch-2.2.3.drv'.
error (ignored): error: cannot unlink '/private/tmp/nix-build-hub-unstable-2022-12-01.drv-1/go-cache': Directory not empty
error: 1 dependencies of derivation '/nix/store/5ggnjz47v6qfhkfc6kd7za3sxh7p8nib-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d0gjxymmkbdq6kllmlv79w60qsrxwczf-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qs0j83ws7fn67lzsf9pwh4wlf42sr8aa-home-manager-path.drv' failed to build
error (ignored): error: cannot unlink '/private/tmp/nix-build-sops-install-secrets-0.0.1-go-modules.drv-1/go/pkg/mod': Directory not empty
error: 1 dependencies of derivation '/nix/store/b1lz6rk65zgycki7igvv6f0kx32zdpmv-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/79jrj3fgjmwrbfz5kqh3yvv9s2nmy1vb-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iqcrkamn9zgm8b54q341ljlbb6s254jq-activation-gene.liverman.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zb6zbbmjadp41hbwhhw33yslhschpc1h-darwin-system-23.11pre-git+darwin4.1e706ef.drv' failed to build
```

### Expected behavior
The package to build and work

### Screenshots

Result via `nix run`
<img width="881" alt="Screenshot 2024-01-27 at 9 30 10 AM" src="https://github.com/NixOS/nixpkgs/assets/966789/2e2d0d02-b371-475c-9ca3-7e156285ea2e">

Result via homebrew
<img width="881" alt="Screenshot 2024-01-27 at 9 30 26 AM" src="https://github.com/NixOS/nixpkgs/assets/966789/6b95005f-e377-4bd4-9b50-e21a31e21fdd">

### Additional context

Full log via `nix log /nix/store/ynhqjg6p8g2s1llpjpab1cgvlh8fk89j-fastfetch-2.2.3.drv 2>&1 >~/Downloads/log.txt`

[log.txt](https://github.com/NixOS/nixpkgs/files/14072711/log.txt)

Here's the homebrew formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/f/fastfetch.rb

### Notify maintainers

@gerg-l @khaneliman @federicoschonborn

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
╔ ☕  Blue-Rock ~
╚ᐅ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/ildml01gk7v91fba35whklllfi343lvq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment]
Looks like it's been that way for a while. https://github.com/NixOS/nixpkgs/issues/253545 was reported previously, but didn't realize it was x86 specific when looking at it before.

**Comment by genebean** [comment]
IDK, the newer version of fastfetch from homebrew works fine so I don't think it is an issue with the os... I was honestly hoping that simply getting the newer version and looking for clues in the brew formula would tell someone who understands this better than me what is up

**Comment by genebean** [comment]
I am happy to test things out if that helps

**Comment by Aleksanaa** [comment]
Is it related to the darwin toolchain being used in Nixpkgs?

**Comment by khaneliman** [comment]
Looks to be working, all of a sudden, btw. 
<img width="847" alt="image" src="https://github.com/NixOS/nixpkgs/assets/1778670/bde2a0c5-30be-453a-b3b1-39af1a4c57ec">
