### ISSUE TITLE
nvidia drivers can't be installed using pkgs.linuxPackages_testing

### ISSUE THREAD

**Issue by beh-10257** [NixOS/nixpkgs#284275]
### Describe the bug
the title and this happens with nvidia drivers even when they are open or not
or beta stable or vulkan_beta
doesn't matter

### Expected behavior
nvidia drivers gettting installed

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/77834479/94b5b486-69e6-44cf-bb15-81de37af9bf6)
![image](https://github.com/NixOS/nixpkgs/assets/77834479/0130b5a8-c8d5-4023-a63f-ac16c9f49a51)
![image](https://github.com/NixOS/nixpkgs/assets/77834479/6ad2440b-285b-4631-8ddc-189e86f1c0eb)

### Notify maintainers
I really don't know about any nvidia maintainers

### Metadata
![image](https://github.com/NixOS/nixpkgs/assets/77834479/cd9bbc7c-5d83-4c54-9a0e-b06d81f4d350)
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by beh-10257** [comment]
since this is going no where and still porceeding with linux 6.8-rc2 I am tagging linux kernel maintainers since they now who are nvidia people as well and can tag them
@TredwellGit 
@Ma27 
@NeQuissimus 
@alyssais 
@thoughtpolice

**Comment by Ma27** [comment]
> I am tagging linux kernel maintainers since they now who are nvidia people as well and can tag them

No idea what you're trying to tell me here.

Not much we can do though I guess. Strictly speaking that's an issue with the nvidia module it seems: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/594
You'll probably want to use an older kernel until nvidia has sorted this out.

Also, for the future, please don't post screenshots for error logs, but copy the text into the issue.

**Comment by beh-10257** [comment]
ok than really sorry about this than hope you have a nice day
and if any of the other maintainers I tagged see this I want to say that I am extremely sorry as well
