### ISSUE TITLE
Atom editor's Git integration not working

### ISSUE THREAD

**Issue by lzrski** [NixOS/nixpkgs#28436]
## Issue description

Atom editor ships with Git and GitHub integration bundled since version 1.18.0 (https://github.com/atom/github). On NixOS it does not work.

The errors in the developer's console:

```
Error spawning: git rev-parse --resolve-git-dir /home/tadeusz/Projects/graphql-playground/.git in /home/tadeusz/Projects/graphql-playground
Error: spawn /nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git ENOENT
/nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/build/lib/git-process.js:82 Uncaught (in promise) Error: Git could not be found at the expected path: '/nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
```

Seems like GitHub integration package is shipped with it's own `git` binary and indeed trying to execute it from a shell results in `no such file or directory` error:

```
$ ls -oh /nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git
-r-xr-xr-x 1 root 2.0M Jan  1  1970 /nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git
$ /nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git
zsh: no such file or directory: /nix/store/a5hs8xijhzd03pgcdrgxra4ha7b3wrmr-atom-1.19.0/share/atom/resources/app/node_modules/dugite/git/bin/git
```
 
I suppose the `git` binary needs to be patched with `patchelf` and I would love to contribute a PR, but frankly I'm a JavaScript monkey 🐒 and can't figure out where to start, so I'll do the next best thing and file an issue.

### Steps to reproduce

1.  Install atom editor:

    ```
    nix-shell --packages atom git
    ```

1.  Initialize a Git repository:

    ```
    mkdir test-atom-git-integration
    cd test-atom-git-integration
    git init
    ```

1.  Make some changes and start Atom editor

    ```
    echo "Why U no work? 🙈 🙉 🙊 " >  README.md
    atom .
    ```

1.  If it's not already opened, open Git panel with `ctrl-9`

1.  Note that tree view shows changes correctly (green README.md file), but the Git panel is empty

1.  Open Dev Tools and see red error messages.

## Technical details

* System: 17.09pre113107.a0306821fd (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre113107.a0306821fd
* Sandboxing enabled: build-use-sandbox = false

**Comment by disassembler** [comment]
Above pull request resolves the issue. I'm not the best at using atom, but I saw a green line next to my changes made, and no errors output to stdout when I opened the git panel.

**Comment by FRidh** [comment]
Maybe replace the binary with a symbolic link to our own git?

**Comment by lzrski** [comment]
How can I test it locally? I suppose I need to clone this report, checkout your PR and use `nix-shell` somehow, but how do I point it to use the expression from the PR?

I'm a total noob and a monkey when it comes to Nix and NixOS 🐒

**Comment by disassembler** [comment]
I ran it using `nix-shell -I nixpkgs=/home/sam/nixpkgs  --pure -p atom`

**Comment by disassembler** [comment]
That works as well and is a cleaner way to handle it in my opinion. I opened a new PR because my last PR I forgot to branch before pushing and it was PR'd to my master branch.

**Comment by lzrski** [comment]
Hi again and thanks for all the help!

I'm a little bit embarrassed to ask, but after two days of trying I still can't figure how to install this patched version of Atom using `nix-env`.

I have a clone of `NixOS/nixpkgs` at `$HOME/Projects/nixpkgs`. Current `master` contains the patch. If I start `nix-shell` as explained by @disassembler it works - I have an editor with working Git integration:

```sh
nix-shell -I nixpkgs=$HOME/Projects/nixpkgs  --packages atom
atom . # works!
```

but if I try to install it in my standard env it apparently installs the un-patched version:

```sh
nix-env --uninstall atom
nix-collect-garbage --delete-old 
# Deletes a lot of things from /nix/store - without it it wouldn't rebuild
nix-env -I nixpkgs=$HOME/Projects/nixpkgs  --install atom 
# Downloads and builds a lot of stuff, but then...
atom . # ...starts Atom v. 1.19.2, but affected by this issue (un-patched?) 
```

I have also tried variant with `--attr nixpkgs.atom`. Then it compiles and installs version 1.18 (I don't understand where is it coming from).

How can I install the version from my cloned repository and - perhaps more importantly - troubleshoot this kind of issues? Is there a way to print a path to expression used by `nix-env`? Or the expression itself?

**Comment by FRidh** [comment]
With `nix-env` you can use the `-f` option to point to a Nix expression, in
this case your Nixpkgs repository. The `-I` option is not used by `nix-env`
because `nix-env` does not use `NIX_PATH`. Instead, it checks by default
`~/.nix-defexpr`. It is confusing...

**Comment by lzrski** [comment]
It worked! Thank you @FRidh.

For the record and a benefit of posterity, this is the whole command that installs a package from local clone:

```sh
nix-env --install --file $HOME/Projects/nixpkgs/ atom
```
