### ISSUE TITLE
Where is the Cups Log FIle?

### ISSUE THREAD

**Issue by NWuensche** [NixOS/nixpkgs#28440]
Hello,

I'm trying to set up my Printer and need therefore the log from cups. However, I added `services.printing.extraConf = ''LogLevel debug'';` to my configuration.nix, rebuilt, but I can't find this log file. Could someone please explain where one can find it? 

Thanks in advance,
Niklas

https://github.com/NixOS/nixpkgs/blob/f4c3bdc1dfdc2418b7b9f908cb254e9fdd883b44/nixos/modules/services/printing/cupsd.nix#L69

**Comment by bjornfor** [comment]
I think cups logs to the journal. Try 'journalctl -b ... | grep cups' or something.

**Comment by disassembler** [comment]
addressed in IRC (journalctl or systemctl status -l cups.service).

**Comment by disassembler** [comment]
We helped @NWuensche get his brother printer setup. We setup a git repository for debugging which can be found here: https://github.com/NWuensche/brotherppd

To get it working, a number of `patchelf`, `substituteInPlace` and `wrapProgram`'s calls were needed to find the correct paths.

This is fine to be closed.

**Comment by bjornfor** [comment]
Great!

**Comment by milahu** [comment]
to print and store the output from cups

```
journalctl --follow --unit=cups | tee cups.log
```
