### ISSUE TITLE
virt-viewer: No Audio due to Missing GStreamer Plugins

### ISSUE THREAD

**Issue by ImBearChild** [NixOS/nixpkgs#284447]
### Describe the bug

`virt-viewer` lacks sound support due to being built without GStreamer plugins. This prevents audio playback from virtual machines on the host system.

### Steps To Reproduce

1. Create a virtual machine with a sound system using libvirt.
2. Connect to the virtual machine using virt-viewer.
3. Attempt to play audio within the virtual machine (e.g., music, videos).
4. Observe the following:
        No sound is played on the host system.
        Following error messages related to GStreamer appears in console output:
        `GStreamer-App-CRITICAL **: 13:41:07.689: gst_app_src_push_internal: assertion 'GST_IS_APP_SRC (appsrc)' failed`

### Expected behavior

Audio from the virtual machine should be correctly routed and played on the host system, enabling seamless sound experience.

### Screenshots

N/A

### Additional context

There is an workaround using overlay:

```nix
virt-viewer = prev.virt-viewer.overrideAttrs (oldAttrs: rec {
      buildInputs =
        (oldAttrs.buildInputs or [])
        ++ [
          prev.pkgs.gst_all_1.gst-plugins-base
          prev.pkgs.gst_all_1.gst-plugins-good
        ];
    });
```

And a related package,`virt-manager` is build with GStreamer.

https://github.com/NixOS/nixpkgs/blob/a77ab169a83a4175169d78684ddd2e54486ac651/pkgs/applications/virtualization/virt-manager/default.nix#L27-L29

### Notify maintainers

@7c6f434c (raskin) @Atemu  (atemu)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 24.05 (Uakari), 24.05.20240125.ae5c332`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/9s5qs4hni9fj88x79iw6im7amv7ghb76-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
If the simple overlay works, would you be comfortable making a simple PR which adds these packages to virt-viewer's buildInputs?
