### ISSUE TITLE
`awesome` is missing inputs

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#284596]
### Describe the bug
`awesome` itself depends on `glib`, which transitively needs packages like`pcre2`, `util-linux`, `libselinux`, etc. but they are not in build inputs. so you will get errors like this during the build:

```
awesome> Package libselinux was not found in the pkg-config search path.
awesome> Perhaps you should add the directory containing `libselinux.pc'
awesome> to the PKG_CONFIG_PATH environment variable
awesome> Package 'libselinux', required by 'gio-2.0', not found
```

build still succeeds, but maybe the result will be missing features.

also unsure the best solution here. should we be adding these inputs to `awesome`, or should `gio`, `glib`, etc. propagate these inputs.

### Notify maintainers

@lovek323 @rasendubi @bobby285271 @hedning @jtojnar @dasj19 @amaxine @7c6f434c 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
That is an issue of CMake incorrectly reporting pkg-config dependencies. It can be safely ignored.

See also https://github.com/NixOS/nixpkgs/pull/265463

**Comment by yshui** [comment]
@jtojnar does that mean `pkg-config` actually succeeds and the errors are spurious? if so i guess i should close #284151.

out of curiosity: how does this work? is there a pkg-config wrapper doing something special here?

**Comment by yshui** [comment]
hmm :thinking: 

do the errors come from cmake calling `pkg-config` with `--static`? and since the static flags aren't used it causes no harm.

**Comment by jtojnar** [comment]
We are patching pkg-config to handle `Requires.private` more sensibly:

https://github.com/NixOS/nixpkgs/blob/a85f4d022e201a163366d5fb5e6b6f3472a2b7be/pkgs/development/tools/misc/pkg-config/default.nix#L15-L18

CMake appears to have a custom pkg-config implementation for dependency detection that does have this modification so it complains. But maybe that implementation is only used for info, since we have not seen any issues with it other than noisy build logs. Ideally, we would patch CMake to fix it.

**Comment by yshui** [comment]
@jtojnar so I think what's happening is this:

quoting cmake's documentation:

> The following variables may be set upon return. Two sets of values exist: One for the common case (`<XXX> = <prefix>`) and another for the information pkg-config provides when called with the `--static` option (`<XXX> = <prefix>_STATIC`).

(https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules)

if I enter the dev shell for awesome and run `pkg-config --libs glib-2.0`, it succeeds. but `pkg-config --static --libs glib-2.0` does produce the errors I saw. 

I think the `<prefix>_STATIC` variables were not used, thus the build succeeds.
