### ISSUE TITLE
Package request: ondsel

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#284524]
**Project description**

Open-source engineering suite forked from FreeCAD with many improvements.

**Metadata**

* homepage URL: https://ondsel.com/
* source URL: https://github.com/Ondsel-Development/FreeCAD https://ondsel.com/download/
* license: gpl2
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
for anyone wanting to try in the meantime, I created this flake: https://github.com/pinpox/ondsel-nix/blob/main/flake.nix

**Comment by abrushworkriot** [comment]
Is there a way I can test try this when I already have FreeCAD installed from nixpkgs?
I launched your flake but it still starts my regular FreeCAD install. I can't figure out where's the binary for Ondsel version.
I hope I don't have to uninstall my old version.

Thanks for your work on this though.

**Comment by pinpox** [comment]
@abrushworkriot I've continued work here: https://github.com/NixOS/nixpkgs/pull/292995

That PR works mostly and starts ondsel, it is still missing some plugins though and I don't know how to add them to the package. If you or anyone else can help out and give me some directions on how to finish it I'll add it

**Comment by Sikeen** [comment]
Should probably be closed as the Ondsel project has been "abandoned"

https://ondsel.com/blog/goodbye/
