### ISSUE TITLE
Package request: MultiMC Minecraft Launcher

### ISSUE THREAD

**Issue by Opoodoop** [NixOS/nixpkgs#284556]
**MultiMC is a custom launcher for Minecraft that focuses on predictability, long term stability and simplicity.**

**Metadata**

* homepage URL: https://multimc.org/
* source URL: https://github.com/MultiMC/Launcher/
* license: Apache 2.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
fyi due to some branding disagreements in the past (see <https://github.com/NixOS/nixpkgs/pull/154051>) multimc was removed from nixkpgs. It might be better to explore other options e.g. prismlauncher
