### ISSUE TITLE
How to install with syslinux instead of grub

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#2845]
How to do this?

Also: How to use nixos for kernel development. ATM (on my archlinux machine), when building a custom kernel, I copy it to `/boot`, generate the initramfs for it, and add the appropriate entry in my `syslinux.cfg` file. How to do this in a 'nixosish' way?

**Comment by matthiasbeyer** [comment]
I am not longer interested in this issue, so it could be closed. Don't know whether you guys want to leave it open, though!

**Comment by MrSorcus** [comment]
Up.
I can't found any options here https://nixos.org/nixos/options.html for install with syslinux.
Or only grub available?
