### ISSUE TITLE
Gnome Catrridges fails to create image previews for games

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#284608]
### Describe the bug
When you import a game in GNOME Catrtidges, an image will not be generated and you will see this error in the logs:
```
root ERROR - Unretryable OSError in CoverManager for Elsinore (steam_512890)
Traceback (most recent call last):
  File "/nix/store/d2c6c94092450ghw5dhdnzjl5aw7jzi1-cartridges-2.3/share/cartridges/src/store/managers/manager.py", line 109, in try_manager_logic
    self.main(game, additional_data)
  File "/nix/store/d2c6c94092450ghw5dhdnzjl5aw7jzi1-cartridges-2.3/share/cartridges/src/store/managers/cover_manager.py", line 195, in main
    convert_cover(
  File "/nix/store/d2c6c94092450ghw5dhdnzjl5aw7jzi1-cartridges-2.3/share/cartridges/src/utils/save_cover.py", line 74, in convert_cover
    (image.resize(shared.image_size) if resize else image).save(
  File "/nix/store/n0f98dymb66afrfrlg7di616wp2mcbvi-python3-3.11.6-env/lib/python3.11/site-packages/PIL/Image.py", line 2438, in save
    save_handler(self, fp, filename)
  File "/nix/store/n0f98dymb66afrfrlg7di616wp2mcbvi-python3-3.11.6-env/lib/python3.11/site-packages/PIL/TiffImagePlugin.py", line 1850, in _save
    raise OSError(msg)
OSError: encoder error -2 when writing image file
```

### Steps To Reproduce
1. Disable high quality images in Cartridge's preferences
2. Import a game 

### Expected behavior
Image is generated, no errors

### Additional context
According to the comments on the AUR package, this is due to `libttiff` being built without WebP support
https://aur.archlinux.org/packages/cartridges

As a workaround, you can enable high quality images in preferences

### Notify maintainers
Cartridges: @getchoo 
libtiff: None listed :slightly_frowning_face: 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
lunik1@tucson ~ % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 23.11 (Tapir), 23.11.20240112.76fc2dd`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
sorry for the wait, been a bit busy and didn't have time for a large rebuild :p

#286814 solves this. you can test it with the following command

```
nix run \
  --extra-substituters 'https://getchoo.cachix.org' \
  --extra-trusted-public-keys 'getchoo.cachix.org-1:ftdbAUJVNaFonM0obRGgR5+nUmdLMM+AOvDOSx0z5tE=' \
  'github:getchoo/nixpkgs/c28f7f70d344caa30007a75ccea807a70e7b42dd#cartridges'
```

using my cachix cache should help you avoid any rebuilds caused by the change in libtiff for the next few days
