### ISSUE TITLE
Rebuilding doesn't seem to relink pipewire-pulse service/socket files

### ISSUE THREAD

**Issue by PassiveLemon** [NixOS/nixpkgs#284600]
### Describe the bug
When rebuilding, nix doesn't appear to relink the service/socket for pipewire-pulse in `/home/USER/.config/systemd/user/`

### Steps To Reproduce
- I can't exactly identify the source of the problem so this is very vague (based on what I think is happening?)
1. Let system exist running for a long time (enough for a new pipewire version?)
2. Let garbage collection remove the currently used store entry for pipewire-pulse
3. Restart system and let pw try to start pw-p
4. Observe problems with audio

### Expected behavior
When pw version is updated, the service is properly linked to avoid failures from missing services/sockets.

### Additional context
I do have pipewire-pulse enabled:
```
pipewire = {
  enable = true;
  pulse.enable = true;
  jack.enable = true;
  alsa = {
    enable = true;
    support32Bit = true;
  };
};
 ```
I left my system running for about 30 days before I had to restart it. When starting back up, I had no audio. Pipewire appeared to be running because the `pw-whatever` commands worked but Pavucontrol would get stuck on connecting and the `pipewire-pulse` service did not exist when it should have.

Did some digging in `journalctl --user -u pipewire-pulse` which had a bunch of `Jan 28 13:16:18 silver systemd[7056]: pipewire-pulse.service: Failed to open /home/lemon/.config/systemd/user/pipewire-pulse.service: No such file or directory` entries. Went to that location and ls'd.

The symlink showed it was linked to `/nix/store/xxxxxxx-pipewire-0.3.38/share/systemd/user/ or a close version (I don't remember exactly). This entry did not exist in my store (but it used to) which is what brings me to believe that store entry was garbage collected or something.

Found a solution though it isn't ideal:
I found `/nix/store/xxxxxxxxx-pipewire-1.0.0/`,
Went inside to `...pipewire-1.0.0/share/systemd/user/`,
Symlinked the `pipewire-pulse.service` to `/home/lemon/.config/systemd/user/pipewire-pulse.service`
Symlinked the `pipewire-pulse.socket` to `/home/lemon/.config/systemd/user/pipewire-pulse.socket` and `/home/lemon/.config/systemd/user/sockets.target.wants/pipewire-pulse.socket`

### Notify maintainers
@k900
Not sure who else should be notified

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 21 paths will be fetched (56.11 MiB download, 262.94 MiB unpacked):
  /nix/store/3r87a2wq1w4l66wnsm7rqvy608mx23h6-binutils-2.40
  /nix/store/7q3l14lc8qhgcpfv8qqk0ckj3sn46cj8-binutils-2.40-lib
  /nix/store/syp0507hrby53pprfi7n4wppms3b7ba2-binutils-wrapper-2.40
  /nix/store/vikpb6rhmi8zzgsx8syjng9dic8dplm7-diffutils-3.9
  /nix/store/9fsqsxbcwj8b7gjizi9dp1f0da9jzds1-ed-1.19
  /nix/store/kz3zbajcbi9kqm5nmdyx80zi5fcqis66-expand-response-params
  /nix/store/rgg874xkzlfmkzkm7911dwnihswkf54g-file-5.44
  /nix/store/4cxs4cigh2zdxvma52ygm3mh2igq70iw-findutils-4.9.0
  /nix/store/jgdz5wfqc6q6qhy17lsqnfpbkfi1fcar-gcc-12.2.0
  /nix/store/3hbxw05vfs6m1155xa6pvribs3bv777n-gcc-wrapper-12.2.0
  /nix/store/linb70pgp53f0kygxm5wk163dx22d681-glibc-2.37-45-dev
  /nix/store/vz87bvvihs94lnvj7j0r33w2jih7nnf4-gmp-6.2.1
  /nix/store/qlcm8dzsaa6wyycmx7in8rz6x3pzf6zf-gnumake-4.4.1
  /nix/store/1mczdvar5cyyfcvcsjq71164p2skbpim-isl-0.20
  /nix/store/bzy10mxb5d7gl7g5d05rj33rkv668hsc-libmpc-1.3.1
  /nix/store/qs605c91wv5fr9rny4mmhpdna6i59kdk-linux-headers-6.2
  /nix/store/frxcyd7g66afqc3rpcx64rlqvsdjqbnw-mpfr-4.2.0
  /nix/store/8ckiaa7f3lzzb6mqvr32kavbmwf8s8fg-nix-info
  /nix/store/0g52i0ih3h0d9s40m84gksi2jjm4k3bf-patch-2.7.6
  /nix/store/gwf21xyl0x0bhgapi66avzf6qmddr44s-patchelf-0.15.0
  /nix/store/gv2cl6qvvslz5h15vqd89f1rpvrdg5yc-stdenv-linux
copying path '/nix/store/vikpb6rhmi8zzgsx8syjng9dic8dplm7-diffutils-3.9' from 'https://cache.nixos.org'...
copying path '/nix/store/9fsqsxbcwj8b7gjizi9dp1f0da9jzds1-ed-1.19' from 'https://cache.nixos.org'...
copying path '/nix/store/kz3zbajcbi9kqm5nmdyx80zi5fcqis66-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/rgg874xkzlfmkzkm7911dwnihswkf54g-file-5.44' from 'https://cache.nixos.org'...
copying path '/nix/store/4cxs4cigh2zdxvma52ygm3mh2igq70iw-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/qlcm8dzsaa6wyycmx7in8rz6x3pzf6zf-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/qs605c91wv5fr9rny4mmhpdna6i59kdk-linux-headers-6.2' from 'https://cache.nixos.org'...
copying path '/nix/store/gwf21xyl0x0bhgapi66avzf6qmddr44s-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7q3l14lc8qhgcpfv8qqk0ckj3sn46cj8-binutils-2.40-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/vz87bvvihs94lnvj7j0r33w2jih7nnf4-gmp-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/0g52i0ih3h0d9s40m84gksi2jjm4k3bf-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/1mczdvar5cyyfcvcsjq71164p2skbpim-isl-0.20' from 'https://cache.nixos.org'...
copying path '/nix/store/frxcyd7g66afqc3rpcx64rlqvsdjqbnw-mpfr-4.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/8ckiaa7f3lzzb6mqvr32kavbmwf8s8fg-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/3r87a2wq1w4l66wnsm7rqvy608mx23h6-binutils-2.40' from 'https://cache.nixos.org'...
copying path '/nix/store/bzy10mxb5d7gl7g5d05rj33rkv668hsc-libmpc-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/linb70pgp53f0kygxm5wk163dx22d681-glibc-2.37-45-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/syp0507hrby53pprfi7n4wppms3b7ba2-binutils-wrapper-2.40' from 'https://cache.nixos.org'...
copying path '/nix/store/jgdz5wfqc6q6qhy17lsqnfpbkfi1fcar-gcc-12.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/3hbxw05vfs6m1155xa6pvribs3bv777n-gcc-wrapper-12.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/gv2cl6qvvslz5h15vqd89f1rpvrdg5yc-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1-zen1, NixOS, 23.11 (Tapir), 23.11.20240124.a77ab16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
You are not supposed to manually `systemctl enable --user` those services, the correct symlinks are created in `/etc/systemd/user`, which is managed by NixOS. We should be communicating this better, probably, but it's not trivial.

**Comment by PassiveLemon** [comment]
I did not manually start or enable those services? I'm not quite sure what you mean

**Comment by K900** [comment]
The only way that symlink can show up is if you manually enabled the service at some point.

**Comment by PassiveLemon** [comment]
Hmm I might have in the past. Is there a way to properly fix this situation? I'm not sure how this symlink will hold up for the future.

**Comment by K900** [comment]
Delete everything in ~/.config/systemd, generally.
