### ISSUE TITLE
Build failure: wordnet

### ISSUE THREAD

**Issue by madsbv** [NixOS/nixpkgs#284604]
### Steps To Reproduce

1. Build wordnet on nixos-unstable

### Build log

Full build log:
https://gist.github.com/madsbv/387fc8b0daebca624181eb1b64ce7d82

### Additional context

I can build wordnet from source manually with gcc. It looks like nix builds it with clang, which errors.

### Notify maintainers

@wegank @trofi 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.19.2`
 - nixpkgs: `/nix/store/j8j4iznlj9dinlnyaziayfhgyq6z1fcq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Hydra agrees that build fails on all of `darwin`:
- https://hydra.nixos.org/job/nixpkgs/trunk/wordnet.aarch64-darwin
- https://hydra.nixos.org/job/nixpkgs/trunk/wordnet.x86_64-darwin
And works on `linux`:
- https://hydra.nixos.org/job/nixpkgs/trunk/wordnet.aarch64-linux
- https://hydra.nixos.org/job/nixpkgs/trunk/wordnet.x86_64-linux

I think it's a `clang-16` update fallout:

```
wn.c:132:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
main(int argc,char *argv[])
^
```

Reproducer on `linux`:

```
$ nix build --impure --expr 'with import <nixpkgs> {}; wordnet.override { stdenv = clangStdenv; }' -L
...
wordnet> wn.c:132:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
wordnet> main(int argc,char *argv[])
wordnet> ^
wordnet> int
```

Proposed the change as https://github.com/NixOS/nixpkgs/pull/284606
