### ISSUE TITLE
Update request: armcord 3.2.5 → 3.2.6

### ISSUE THREAD

**Issue by kenos1** [NixOS/nixpkgs#284609]
- Package name: Armcord
- Latest released version: 3.2.6

- Current version on the unstable channel: 3.2.5
- Current version on the stable/release channel: 3.2.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wrmilling 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wrmilling** [comment]
Looks like you submitted it moments before I was about to click send on my PR and came to copy the issue number :smile:
