### ISSUE TITLE
fd -x "smth {}": Command not found

### ISSUE THREAD

**Issue by Casul51** [NixOS/nixpkgs#284764]
### Describe the bug
`fd` command can't use most of  installed commands

### Steps To Reproduce
1. ` fd --full-path -x 'cd "{}"' `
2. get `[fd error]: Command not found: cd...`

### Expected behavior
Execute of command

### Additional context
`ls` command for example works

### Notify maintainers

@dywedir 
@figsoda 
@globin 
@Ma27 
@zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0-zen3, NixOS, 24.05 (Uakari), 24.05.20240117.842d9d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/home/casual/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
remove the quotes around the command
https://www.mankier.com/1/fd
