### ISSUE TITLE
Would an additional platform check GHC version for Windows Subsystem for Linux make sense?

### ISSUE THREAD

**Issue by NickSeagull** [NixOS/nixpkgs#28471]
## Issue description

Currently, if a user tries to use GHC8+ in WSL, when using the versions provided by nixpkgs or by Stackage, it simply fails on compile anything as it tried to allocate more memory than it is able to (1TB+).

This is because GHC 8.0's new block-structured heap for 64-bit platforms. [From the GHC 8.0.1 release notes](https://downloads.haskell.org/~ghc/master/users-guide/8.0.1-notes.html#runtime-system):

> We have a shiny new two-step memory allocator for 64-bit platforms (see Trac #9706). In addition to simplifying the runtime system’s implementation this may significantly improve garbage collector performance. Note, however, that Haskell processes will have an apparent virtual memory footprint of a terabyte or so. Don’t worry though, most of this amount is merely mapped but uncommitted address space which is not backed by physical memory.

There is a [whole Github thread](https://github.com/Microsoft/BashOnWindows/issues/1671) for discussing this on MS [BashOnWindows](https://github.com/Microsoft/BashOnWindows/) repo.

Would it make sense for `nixpkgs` to include a "fixed" version of GHC8, so one is able to run it from WSL?

This is solved easily, as described [in this comment](https://github.com/Microsoft/BashOnWindows/issues/1671#issuecomment-295310765):

```bash
git clone -b ghc-8.0.2-release --recursive git://git.haskell.org/ghc.git ghc-8.0.2
cd ghc-8.0.2
./boot
./configure --disable-large-address-space #can set --prefix=... here
make -j8 #-j(number-of-threads)
sudo make install
```

As I can see, it is already being checked for **iOS** in [this file](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ghc/8.0.2.nix#L52) for `ghc-8.0.2`.

Would it make sense to add another check for WSL here?

### Steps to reproduce

Try to compile any project that depends on GHC8+ on WSL.

## Technical details

* System: WSL

```bash
$ cat /proc/version
Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014
```

* Nix version: `nix-env (Nix) 1.11.13`
* Nixpkgs version: `"17.09pre112229.e619ace733"`
* Sandboxing enabled: `grep: /etc/nix/nix.conf: No such file or directory`

**Comment by vcunat** [comment]
/cc @peti.

To me personally, WSL itself doesn't seem worth building all Haskell stuff twice on Hydra, and having `--disable-large-address-space` for everyone would decrease [GC performance](https://ghc.haskell.org/trac/ghc/ticket/9706#comment:18) by ~8 %.  I wonder if this would be a good candidate for some hack replacing the runtime without recompiling, e.g. via `pkgs.replaceDependency`.

**Comment by peti** [comment]
I don't understand the technical details behind this request. What is WSL? Is that a separate platform in Nixpkgs? And if so, what is it called?

**Comment by vcunat** [comment]
@peti: it's about the linux-inside-windows situation: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide  Using linux binaries should usually just work.

**Comment by peti** [comment]
So it's *not* a separate platform in Nixpkgs?

**Comment by vcunat** [comment]
Yes, my understanding is that it doesn't need to be a separate platform, in general.  (I don't use Windows, so I've never really tried WSL...)

**Comment by NickSeagull** [comment]
Yes, a different platform is kinda overkill. The way to currently detect if the user is running Linux or not is by inpecting the `/proc/version` file and see if it contains the string `Microsoft` in it.

I was thinking about adding a check for GHC8+

**Comment by peti** [comment]
I think it would be feasible to add a boolean argument to the GHC Nix expression that enables/disables use of large-address-space at compile-time so that people who want that can override the default choice easily. Disabling it for all of Linux by default doesn't sound like a good idea to me.

@NickSeagull, does this answer your question?

**Comment by NickSeagull** [comment]
Definitely, disabling it for all of Linux is not feasible at all.

The situation that I'm thinking of is:

* User wants to create package **A** which depends on package **B**
* The package **B** depends on GHC8+, but its author didnt enable the `large-address-space` flag.

How the user would proceed on enabling that flag, and furthermore, could they dynamicly enable it in their `default.nix` file? I think it would be interesting if the check was automatic @peti

**Comment by peti** [comment]
I think you'll find that https://nixos.org/nixpkgs/manual/#sec-overrides and https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure provide a wealth of information towards that end. If you have any specific questions, then it's probably best to ask on the nix-devel mailing list of -- even better -- in the #nixos IRC channel. The bug tracker seems like it's the wrong place for that kind of conversation.

**Comment by NickSeagull** [comment]
In case someone comes from Google looking for a working version of GHC for WSL, I've created a repository with overrides for different packages that are meant to be "patched" somehow for working properly in WSL. [https://github.com/NickSeagull/wsl-nixpkgs](https://github.com/NickSeagull/wsl-nixpkgs)
