### ISSUE TITLE
Adding a bridge to configuration.nix does not add IP

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#28474]
## Issue description

If you add the following lines to ```configuration.nix``` and then execute ```nixos-rebuild switch```, it will add the bridge but does not assign the IP to the bridge (after reboot the IP will be assigned)

### Steps to reproduce

```
networking.bridges.brdmz.interfaces = [];
networking.interfaces.brdmz.ip4 = [{ address = "172.16.241.1"; prefixLength = 24; } ];
```

## Technical details

* System: 17.09
* Nix version: 1.12

**Comment by fpletz** [comment]
Probably related to #16230.
