### ISSUE TITLE
Python package preshed 4.0.0 has been yanked

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#284758]
### Describe the bug
Version 4.0.0 for Python package preshed has been yanked, see https://pypi.org/p roject/preshed/4.0.0/#history current version should be 3.0.9 

### Steps To Reproduce
None

### Additional context
Preshed 4.0.0 is a buildInput of spacy, 3.7.2. but it fails to build with this version... but I will open another issue for that

### Notify maintainers

@mweinelt 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hacker1024** [comment]
#294305 reverts this, but it is still yanked.

**Comment by mweinelt** [comment]
Annoying. We really need to fix the bulk updater.
