### ISSUE TITLE
Build failure: cmake on mipsel

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#284734]
### Steps To Reproduce

    nix-build . -A pkgsCross.mipsel-linux-gnu.cmake

### Build log

```
/nix/store/in6kl3y5kygnk177f6g3yip7pc4sab2s-mipsel-unknown-linux-gnu-binutils-2.40/bin/mipsel-unknown-linux-gnu-ld: ../Utilities/cmcppdap/libcmcppdap.a(typeof.cpp.o): undefined reference to symbol '__atomic_fetch_sub_8@@LIBATOMIC_1.0'
/nix/store/in6kl3y5kygnk177f6g3yip7pc4sab2s-mipsel-unknown-linux-gnu-binutils-2.40/bin/mipsel-unknown-linux-gnu-ld: /nix/store/sz4kbwqdgxlwxcqg053qzangdmlxd6k9-mipsel-unknown-linux-gnu-gcc-13.2.0-lib/mipsel-unknown-linux-gnu/lib/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

### Additional context

It seems this problem was introduced in the `3.26.4 -> 3.27.7` update in cc9458e2b9a56c085a34e3b648300e46a87e94a3

### Notify maintainers

@ttuegel @LnL7 @AndersonTorres 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Maybe crosspiling cmake is not so easy...

**Comment by raboof** [comment]
I guess it's surprising it seems to have worked fine until 3.26.4 ;)

It looks like cmake is built with cmake in this case, and does have some provisions for cross-compiling: AFAICS creating a [`CMAKE_TOOLCHAIN_FILE`](https://cmake.org/cmake/help/latest/variable/CMAKE_TOOLCHAIN_FILE.html) and setting [`CMAKE_SYSTEM_PROCESSOR`](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html) in there should add the correct settings to link in `libatomic` here.

**Comment by raboof** [comment]
Turns out all of the hard parts were already done ;) - https://github.com/NixOS/nixpkgs/pull/286473

**Comment by AndersonTorres** [comment]
I have found some problems while trying to build a static cmake. Let's take a look...

**Comment by raboof** [comment]
Closing as duplicate of #271428

**Comment by raboof** [comment]
wait, not actually a duplicate

**Comment by FliegendeWurst** [comment]
Works on recent nixpkgs.
