### ISSUE TITLE
Package request: pdfannots2json 

### ISSUE THREAD

**Issue by 0nyr** [NixOS/nixpkgs#284737]
**Project description**

The Zotero Integration community plugin of Obsidian requires the `pdfannots2json` executable to do it's job to the fullest.

**Metadata**

* homepage URL: 
* source URL: https://github.com/mgmeyers/pdfannots2json
* latest release: https://github.com/mgmeyers/pdfannots2json/releases
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by 0nyr** [comment]
I added a [pull request](https://github.com/mgmeyers/pdfannots2json/pull/23) to add a `flake.nix` file to the project. Tested.

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/284847
