### ISSUE TITLE
wine fails to execute 64bit binaries

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#28486]
## Issue description

https://gist.github.com/bendlas/5c650de337ce464402d3445ff77e8e66

It seems, that wine has a problem to `execve` into wine64. Maybe removing the wrapper script for wine64 can help. This should be called via wine anyway.

### Steps to reproduce

see description, I used this binary: http://www.chip.de/downloads/Notepad2-64-Bit_48895401.html

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by a1russell** [comment]
I see the same issue. The less verbose error output that I get when running anything is:
```
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  168
  Current serial number in output stream:  172
```

I'm using nvidia driver and have `opengl.driSupport32Bit` enabled. Things were working until fairly recently (although admittedly I don't update as often as I probably should).

**Comment by bendlas** [comment]
No, this is a totally different issue. The error message i get (without strace) is:
`/nix/store/j81q9mxs0mnic8pdra6qmhph0cwcrf01-wine-wow-2.14-staging/bin/.wine64-wrapped: not an i386 ELF binary... don't know how to load it`

**Comment by a1russell** [comment]
Thanks @bendlas; I've opened #28504 for my issue.

**Comment by avnik** [comment]
Do we have any simple application for win64 to test builds? Small (less than 1G free game for example, or something).

I am usually test only 32bit builds (not 64, nor wow, which not very correct)

**Comment by MP2E** [comment]
I have this exact same issue. From inspecting the wine nix expressions, it appears to be a problem with using makeWrapper on both a 64 bit and 32 bit executable. I would assume we need an i686 variant of makeWrapper for wine, and x86_64 for wine64. Not sure exactly how to do this.

Relevant lines:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/emulators/wine/base.nix#L95

I currently work around this by overriding my wineWow derivation to set 'gstreamerSupport = false;'

example here:
https://github.com/MP2E/nix-projects/blob/master/nixpkgs-config/config.nix#L147

**Comment by DiThi** [comment]
Here's a very small 64 bit executable that can be used as a test: https://bitbucket.org/wolfpld/etcpak/downloads/etcpak-0.5.7z

It's a command line program, and I can't run it because of this bug. I know it's open source but I just wanted to run the precompiled one as a quick test.

**Comment by bendlas** [comment]
I haven't gotten around to creating a test suite. That will have to be a separate ticket

**Comment by bendlas** [comment]
in manual testing, 64bit binaries work with the patch
