### ISSUE TITLE
Update request: PACKAGENAME OLDVERSION → NEWVERSION

### ISSUE THREAD

**Issue by carschandler** [NixOS/nixpkgs#284853]
- Package name: wezterm
- Latest released version: 20240128-202157-1e552d76

- Current version on the unstable channel: 20230712-072601-f4abf8fd
- Current version on the stable/release channel: 20230712-072601-f4abf8fd

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@SuperSandro2000 
@mimame 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please fill in the complete template.

**Comment by SuperSandro2000** [comment]
#284881

**Comment by carschandler** [comment]
I’m so sorry, I thought I completed everything. My apologies. Thank you for taking care of it promptly anyway!
