### ISSUE TITLE
Update request (23.11): ruby_3_2 3.2.2 → 3.2.3

### ISSUE THREAD

**Issue by lloeki** [NixOS/nixpkgs#284995]
- Package name: ruby_3_2
- Latest released version: 3.2.3

- Current version on the unstable channel: 3.2.3
- Current version on the stable/release channel: 3.2.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@vrthra @manveru @marsam this is about updating 23.11

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/284732
