### ISSUE TITLE
display-manager fails to detect hardware after upgrade

### ISSUE THREAD

**Issue by ybreakthings** [NixOS/nixpkgs#284923]
### Describe the bug

After running `sudo nixos-rebuild switch --upgrade` on the `nixos-unstable` channel, I am no longer presented the GUI login after reboot. I am still able to login via TTY but unable to manually start a GUI session.

### Steps To Reproduce

1. Upgrade to latest on nixos-unstable and reboot.

### Expected behavior

The GUI login screen shows up and I can login.

### Additional context

I suspect this is related to https://github.com/NixOS/nixpkgs/pull/278680. I have tried rolling back to a stable kernel (6.6.14) and the issue persisted. 

Here are the logs from a boot where it is not working. You can see it is not emitting any log lines as you would expect.
```sh
$ journalctl -u display-manager -b -3
Jan 29 21:05:04 nixos-minipc systemd[1]: Starting Display Manager...
Jan 29 21:05:04 nixos-minipc systemd[1]: Started Display Manager.
Jan 29 21:05:04 nixos-minipc sddm[1605]: Initializing...
Jan 29 21:05:04 nixos-minipc sddm[1605]: Starting...
Jan 29 21:05:04 nixos-minipc sddm[1605]: Logind interface found
Jan 29 21:08:22 nixos-minipc systemd[1]: Stopping Display Manager...
Jan 29 21:08:22 nixos-minipc sddm[1605]: Signal received: SIGTERM
Jan 29 21:08:22 nixos-minipc systemd[1]: display-manager.service: Deactivated successfully.
Jan 29 21:08:22 nixos-minipc systemd[1]: Stopped Display Manager.
Jan 29 21:08:22 nixos-minipc systemd[1]: display-manager.service: Consumed 20ms CPU time, 18.7M memory peak, 0B memory swap peak, read 31.7M from disk, written 0B to disk, no IP traffic.
```

Here is the diff between two working revisions: https://gist.github.com/ybreakthings/30ecb4db3e1f54ff41eaec430dbeaa92

### Notify maintainers

@abbradar @ttuegel 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by evils** [comment]
and in response to a question you got about this on matrix
i am on an AMD GPU

**Comment by K900** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/284487
