### ISSUE TITLE
nginx service recommendedTlsSettings leads to B grade on SSL test

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#28493]
I use `services.nginx.recommendedTlsSettings = true` on https://chimneygroup.com and that results in [a B grade](https://www.ssllabs.com/ssltest/analyze.html?d=chimneygroup.com) due to [weak DH](https://weakdh.org/).

On https://cipherli.st/ are recommended settings for nginx (as well as apache and lighttpd). How about we use those?

https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html seems to be an excellent resource on the subject, the author also wrote the SSL test that I used above.

/cc @globin

**Comment by wmertens** [comment]
This might be the issue:
>All versions of nginx as of 1.4.4 rely on OpenSSL for input parameters to Diffie-Hellman (DH). Unfortunately, this means that Ephemeral Diffie-Hellman (DHE) will use OpenSSL's defaults, which include a 1024-bit key for the key-exchange. Since we're using a 2048-bit certificate, DHE clients will use a weaker key-exchange than non-ephemeral DH clients.
>
>We need generate a stronger DHE parameter:
>
>```
>cd /etc/ssl/certs
>openssl dhparam -out dhparam.pem 4096
>```
>
>And then tell nginx to use it for DHE key-exchange:
>
> `ssl_dhparam /etc/ssl/certs/dhparam.pem;`

Ideally, this is done automatically with an activation script, no?

**Comment by fadenb** [comment]
I believe this is not done by default because it may take a 'long' time to complete the generation resulting in timeouts.

**Comment by wmertens** [comment]
Hmm. How about a warning at activation time then, with the command to
run, and a configuration so that the values are used at run time if
they are there?

**Comment by nh2** [comment]
glusterfs also seems to somehow want an `/etc/ssl/dhparam.pem`; if not present, it continues to work but logs something like

```
[2016-11-24 09:37:07.174449] E [socket.c:4102:socket_init] 0-samba-official-client-3: failed to open /etc/ssl/dhparam.pem, DH ciphers are disabled
```

(see https://bugzilla.redhat.com/show_bug.cgi?id=1398237)

So it would be nice to know what the best way is to generate it on NixOS.

**Comment by ajs124** [comment]
So, looking at my servers with these settings ([example](https://www.ssllabs.com/ssltest/analyze.html?d=ipv2.de&s=159.69.80.153)), this seems solved by the fact that DHE suites are now off by default. 

While this does not really address what was discussed here, it means that the actual issue of `recommendedTlsSettings` leading to a B was solved.
