### ISSUE TITLE
Enabling Gitlab service failed with setuid permission problem

### ISSUE THREAD

**Issue by dy2k** [NixOS/nixpkgs#28494]
## Issue description
Following the NixOS manual (https://nixos.org/nixos/manual/index.html#module-services-gitlab) to setup Gitlab on a new NixOS server, I got the following error: 

> building
> tar: ./opt/gitlab/embedded/bin/ksu: Cannot change mode to rwsr-xr-x: Operation not permitted
> tar: Exiting with failure status due to previous errors
> dpkg-deb: error: subprocess tar returned error exit status 2
> builder for ‘/nix/store/9239cx16zqw0m4m79w1v65qrgk9gwady-gitlab-8.17.6.drv’ failed with exit code 2

Consulting the IRC channel #nixos on irc.freenode.net, I got the diagnosis of the problem that they put their own copy of ksu into the package, setuid'd and nix doesn't allow setuid files.

### Steps to reproduce

1. After a new NixOS install, update `/etc/nixos/configuration.nix` with a minimal Gitlab configuration 
>   services.gitlab = {
>     enable = true;
>     databasePassword = "45ft_A_ARg";
>     secrets = {
>       db = "Tu2LWMPcfRyRaFCYbCIgBWdCMLnERdoQLVbrsUzrRGxGqXiNuSewe7ufoS1cyEyDXQ2Q3fxain26e3ibIJEVBwhQSIJhAX3aefJaIu6SK13iJds50UineaKimsaRMAz4";
>       secret = "wRNJUMioNyEdoEqXD8iVi882G4TBMPSOf3z1jqS7IhghgwXW2zMOfztSO2GtIvXvavoPzJGBtBnAhRWXUwQIhAD9y70jPAof3DfpnXhQ7ONFfUX9iu8sahZfYM9HjSM1";
>       otp = "0nAQoAgOi5Kok0QaqzVlnKio8s0oqheaFhmrdOlQ8wV87Fwgqu5QmFU0KG4uOZZsnRIG9KTVLEhUeEiBhoXRy5023qVHN0rR8WQgrn9WSbZFacWDCR9LeEOg6n07v7NM";
>     };
>   };

2. Run `nixos-rebuild switch` or `nixos-rebuild test`

## Technical details

* System: 17.03.1700.51a83266d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1700.51a83266d1"
* Sandboxing enabled: build-use-sandbox = false

**Comment by Mic92** [comment]
cc @fpletz (maintainer)
