### ISSUE TITLE
Grsync when trying to browse closes with "No GSettings schemas are installed on the system" error

### ISSUE THREAD

**Issue by thomX75** [NixOS/nixpkgs#285093]
### Describe the bug
Grsync (pkgs.grsync) crashes/closes on KDE Plasma with "(grsync:66852): GLib-GIO-ERROR **: 20:53:07.608: No GSettings schemas are installed on the system"
error when clicked on Open button from GUI or use menu File and select Browse Source/Browse Destination.
This happens even pkgs.gsettings-desktop-schemas is installed.

### Steps To Reproduce
1. Install NixOS with KDE
2. declare system package Grsync
3. try to browse

### Expected behavior
Should open requester to browse to folder.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 23.11 (Tapir), 23.11.3496.a77ab169a83a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
fixed in #285903
