### ISSUE TITLE
Update request: Transmission v3.00 => v4.05 (Bittorrent Client)

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#285081]
Please update Transmission (Bittorrent Client):
https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/networking/p2p/transmission/default.nix#L128

Current NixOS (23.11 & unstable) version is `v3.00` **(May 22, 2020)**
(a bit too old)
https://github.com/transmission/transmission/releases/tag/3.00

Current version is `v4.05` **(Dec 7, 2023)**
https://github.com/transmission/transmission/releases/tag/4.0.5

**Comment by TomaSajt** [comment]
I haven't actually used it yet, but there's a `transmission_4` package with the latest version.

**Comment by boustanihani** [comment]
Thanks, I didn't notice that, just wondering why 3 and also 4 are available...
