### ISSUE TITLE
Update request: gamescope 3.13.19 → 3.14.0

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NixOS/nixpkgs#285039]
- Package name: gamescope
- Latest released version: 3.14.0

- Current version on the unstable channel: 3.13.19
- Current version on the stable/release channel: 3.12.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

https://github.com/nrdxp
https://github.com/PedroHLC
https://github.com/Scrumplex
https://github.com/zhaofengli

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
Being worked on https://github.com/NixOS/nixpkgs/pull/275372.

**Comment by K900** [comment]
Merged.
