### ISSUE TITLE
nix-env -qaP inconsistency among xxxPackages on top-level

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28502]
I found the reason for haskellPackages in the [manual](https://nixos.org/nixpkgs/manual/#how-to-install-haskell-packages)

>The Haskell package set is not registered in the top-level namespace because it is huge.

Should it be consistency among all xxxPackages? Why `python` and `dotnet` are exceptions?

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs | grep -i python27Packages | wc -l
    1661

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs | grep -i python36Packages | wc -l
    1465

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs | grep -i dotnetPackages | wc -l
    55

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs | grep -i haskellPackages | wc -l
    0

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs | grep -i nodePackages | wc -l
    0

What is the threshold?

    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs -A nixos.nodePackages | wc -l
    79
    
    $ nix-env -qaP -I nixpkgs=/nix/nixpkgs -A nixos.haskellPackages | wc -l
    11937

**Comment by edolstra** [comment]
Python was added back only a couple of days ago: https://github.com/NixOS/nixpkgs/pull/28244

**Comment by wizzup** [comment]
Close reason: outdated
