### ISSUE TITLE
Cannot load `amdgpu` after updating flake

### ISSUE THREAD

**Issue by minikN** [NixOS/nixpkgs#285092]
### Describe the bug
I recently [updated](https://github.com/minikN/nix/commit/321e0877e8104776332dfa32c87fb27facf7a109) my `flake.lock` using `nix flake update`. After that commit, the `amdgpu` kernel module can't be loaded anymore:
![image](https://github.com/NixOS/nixpkgs/assets/1888338/68cb5724-10e0-4a91-8dc9-d28dce7fab54)

After reverting that commit, it works again. [Here](https://github.com/minikN/nix) is my config, and [here](https://github.com/minikN/nix/blob/master/machines/workhorse.nix) the config specific to that machine.

It's a TUXEDO Pulse 15 Gen 2 laptop. 

Output of `cat /proc/cpuinfo` (if that's important): https://paste.debian.net/1305813

### Steps To Reproduce
1. Update flake using `cd /path/to/repo && sudo nix flake update`
2. Rebuild system using `sudo nixos-rebuild --flake .#`
3. Reboot

### Expected behavior
`amdgpu` module should be loaded fine

### Screenshots
See above

### Notify maintainers
@corngood 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
db > nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                                  
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info
copying path '/nix/store/2bk3cqpj26fi3fwgshgg3k0fxwz0h55g-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231227.cfc3698`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minikN** [comment]
Okay sorry, I guess this is most likely fixed by https://github.com/NixOS/nixpkgs/pull/284487. However, when I run `nix flake update`, I'm on c002c6a, which is 3 days old. Can anyone tell me why?

**Comment by corngood** [comment]
Could you share `dmesg` output, or whatever other error you got about the kernel module?

**Comment by minikN** [comment]
> Could you share `dmesg` output, or whatever other error you got about the kernel module?

I did, it's embedded as an image in my first post.

**Comment by devusb** [comment]
I do not think the commit resolving this has made it to `nixos-unstable` yet -- you can track progress [here](https://nixpk.gs/pr-tracker.html?pr=284487) though.

**Comment by minikN** [comment]
@devusb Thanks. To be honest, I'm a little bit confused. Not sure why it needs to be present in `nixos-unstable` if I have `nixpkgs-unstable` as an input and it's present there. That is, if `nix flake update` would get me to the latest commit, which it doesn't for some reason.

**Comment by corngood** [comment]
@minikN Sorry!  ad-blocker was too aggressive :)

Yeah, that's definitely the same issue.

> Not sure why it needs to be present in nixos-unstable if I have nixpkgs-unstable as an input and it's present there.

I'm not sure what you mean by this.  Your system seems to be using nixos-unstable.  I don't see a reference to nixpkgs-unstable in there.

**Comment by minikN** [comment]
> @minikN Sorry! ad-blocker was too aggressive :)
> 
> Yeah, that's definitely the same issue.
> 
> > Not sure why it needs to be present in nixos-unstable if I have nixpkgs-unstable as an input and it's present there.
> 
> I'm not sure what you mean by this. Your system seems to be using nixos-unstable. I don't see a reference to nixpkgs-unstable in there.

Sorry, just realized that I'm indeed using `nixos-unstable`. I just read up on it on the wiki:

> For [Nix](https://nixos.wiki/wiki/Nix) users, nixpkgs-unstable is the bleeding-edge, where packages pass only basic build tests and are upgraded continuously.
For [NixOS](https://nixos.wiki/wiki/NixOS) users, nixos-unstable is the bleeding-edge, where packages pass build tests and integration tests on a VM, and are tested from the perspective of being an operative system (this means things like the X server, KDE, various servers, and lower level details like installing bootloaders and runnning the nixos installation steps are also tested).

This means because I'm running NixOS and not just nix, I need to wait until that PR get's to `nixos-unstable`, is that correct?

**Comment by alyssais** [comment]
> This means because I'm running NixOS and not just nix, I need to wait until that PR get's to `nixos-unstable`, is that correct?

Yes, unless you choose to use a different channel, like nixos-unstable-small.

**Comment by minikN** [comment]
Alright, thanks @alyssais @devusb @corngood !
