### ISSUE TITLE
Proton titles on Steam are launching but the screen is completely blank or frozen.

### ISSUE THREAD

**Issue by minneelyyyy** [NixOS/nixpkgs#285105]
### Describe the bug
When I launch games such as Deep Rock Galactic, Fallout: New Vegas, or Farming Simulator 19, the screen will be completely black. When I alt tab, sometimes that will be replaced with a more recent frame from the game. I've tested a few versions of proton and direct X in DRG and it will not work. I can still hear audio so I know the game is actually running. When I ran with mangohud and got a more recent frame by alt tabbing it even reported a regular fps and resource usage.

Freddy Fazbear's Pizzeria Simulator worked fine. I think it's a 3D issue.

I'm not sure if my DE has anything to do with it. I'm using Enlightenment.

I use a GTX 1060, I have the proprietary Nvidia drivers installed (production).

### Steps To Reproduce
1. Install steam via configuration.nix
2. attempt to play Deep Rock Galactic or one of the other games mentioned.

### Expected behavior
The games should display the frames being rendered on screen.

### Metadata
```console
[mins@nixos:~]$  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 23.11 (Tapir), 23.11.3640.56911ef3403a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by girlbuzz** [comment]
I tested on GNOME and the issue does indeed seem to be with Enlightenment.
