### ISSUE TITLE
GHC in nix-shell --pure still picks up ~/.ghc related files

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#2851]
My colleague was trying to use Nix with GHC, but had ~/.ghc lying around. This causes all sorts of `ghc-pkg check` problems. Removing `~/.ghc` fixes the problem.

Apologies for the poor info on this bug report, mostly reporting as a reminder to (at least) myself.

**Comment by peti** [comment]
Is there some command line flag or an environment variable that we can set to tell `ghc` to ignore ~/.ghc?

We can always set `$HOME` to some random value, of course, but maybe that's too intrusive?

**Comment by peti** [comment]
I suppose unless someone comes with a bright idea how to solve this issue meaningfully, there is not much we can do about this.
