### ISSUE TITLE
Package request: new Nvidia beta driver 550.40.07

### ISSUE THREAD

**Issue by bochy992** [NixOS/nixpkgs#285112]
How do I install this? 
  
https://www.nvidia.com/download/driverResults.aspx/218153/

**Comment by physics-enthusiast** [comment]
Its already been packaged. Pass ```hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta``` in your ```configuration.nix```. See [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/nvidia-x11/default.nix) and [here](https://nixos.wiki/wiki/Nvidia) for the available driver packages. In the future, if you happen to have a burning need for an Nvidia driver that has not yet been packaged, you can also pass a fixed output derivation containing the desired package of your choosing to ```hardware.nvidia.package```.

**Comment by bochy992** [comment]
> Its already been packaged. Pass `hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta` in your `configuration.nix`. See [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/nvidia-x11/default.nix) and [here](https://nixos.wiki/wiki/Nvidia) for the available driver packages. In the future, if you happen to have a burning need for an Nvidia driver that has not yet been packaged, you can also pass a fixed output derivation containing the desired package of your choosing to `hardware.nvidia.package`.

 I have that in my config but I'm still stuck on 545.29.06

**Comment by physics-enthusiast** [comment]
In that case you're probably on one of the stable branches then. Try this

```
    hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta.overrideAttrs {
      version = "550.40.07";
      # the new driver
      src = fetchurl
          {
            url = "https://download.nvidia.com/XFree86/Linux-x86_64/550.40.07/NVIDIA-Linux-x86_64-550.40.07.run";
            sha256 = "sha256-KYk2xye37v7ZW7h+uNJM/u8fNf7KyGTZjiaU03dJpK0=";
          };
    };
```

**Comment by bochy992** [comment]
> In that case you're probably on one of the stable branches then. Try this
> 
> ```
>     hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta.overrideAttrs {
>       version = "550.40.07";
>       # the new driver
>       src = fetchurl
>           {
>             url = "https://download.nvidia.com/XFree86/Linux-x86_64/550.40.07/NVIDIA-Linux-x86_64-550.40.07.run";
>             sha256 = "sha256-KYk2xye37v7ZW7h+uNJM/u8fNf7KyGTZjiaU03dJpK0=";
>           };
>     };
> ```

I've been on the nixpkgs-unstable branch for a month 

Here's my configuration.nix

`
boot.kernelPackages = pkgs.linuxPackages_zen;
boot.initrd.kernelModules = [ "nvidia" ];

services.xserver.videoDrivers = [ "nvidia" ];

# Load nvidia driver for Xorg and Wayland
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    forceFullCompositionPipeline = true;
  };

  hardware.nvidia.prime = {
    # offload = {
    #   enable = true;
    #   enableOffloadCmd = true;
    # };
    sync.enable = true;
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
  };
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };
# Allow unfree packages
  nixpkgs.config.allowUnfree = true;
`


my flake.nix

`
{
  description = "Flake with Home Manager enabled";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      ...
    }@inputs:
    {
      nixosConfigurations = {
        nixos = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = [
            ./configuration.nix
            home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              home-manager.users.bochy= import ./home.nix;
            }
          ];
        };
      };
    };
}

`

Was there anything wrong with what I did or is it a bug?

**Comment by bochy992** [comment]
> In that case you're probably on one of the stable branches then. Try this
> 
> ```
>     hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta.overrideAttrs {
>       version = "550.40.07";
>       # the new driver
>       src = fetchurl
>           {
>             url = "https://download.nvidia.com/XFree86/Linux-x86_64/550.40.07/NVIDIA-Linux-x86_64-550.40.07.run";
>             sha256 = "sha256-KYk2xye37v7ZW7h+uNJM/u8fNf7KyGTZjiaU03dJpK0=";
>           };
>     };
> ```

I've been on the nixpkgs-unstable branch for a month 

Here's my configuration.nix

```
boot.kernelPackages = pkgs.linuxPackages_zen;
boot.initrd.kernelModules = [ "nvidia" ];

services.xserver.videoDrivers = [ "nvidia" ];

# Load nvidia driver for Xorg and Wayland
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    forceFullCompositionPipeline = true;
  };

  hardware.nvidia.prime = {
    # offload = {
    #   enable = true;
    #   enableOffloadCmd = true;
    # };
    sync.enable = true;
    intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:1:0:0";
  };
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };
# Allow unfree packages
  nixpkgs.config.allowUnfree = true;
```


my flake.nix

```
{
  description = "Flake with Home Manager enabled";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      ...
    }@inputs:
    {
      nixosConfigurations = {
        nixos = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = [
            ./configuration.nix
            home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              home-manager.users.bochy= import ./home.nix;
            }
          ];
        };
      };
    };
}

```

Was there anything wrong with what I did or is it a bug?

**Comment by physics-enthusiast** [comment]
Have you updated your flake inputs within this week? The commit bumping the driver version to 550 (which you can see [here](https://github.com/NixOS/nixpkgs/commit/0f71ad2021d8d8daa1c99256213051138488d6ff)) only occurred a week ago. If not, run ```nix flake lock --update-input nixpkgs``` in your flake directory.

**Comment by bochy992** [comment]
> Have you updated your flake inputs within this week? The commit bumping the driver version to 550 (which you can see [here](https://github.com/NixOS/nixpkgs/commit/0f71ad2021d8d8daa1c99256213051138488d6ff)) only occurred a week ago. If not, run `nix flake lock --update-input nixpkgs` in your flake directory.

No I haven't. I just tried updating it now and did a nixos-rebuild but I'm getting this error message and the rebuild gets stuck there:

```
building the system configuration...
[0/19 built] waiting for lock on '/nix/store/p43fy082gskx906h0kwpf54k080mkjgb-cuda_12.2.2_535.104.05_linux.run'
```

**Comment by physics-enthusiast** [comment]
Try restarting the system if you can

**Comment by bochy992** [comment]
> Try restarting the system if you can

I'm getting this:
```
>reboot
reboot: Not root (see "reboot --help")
```
odd...

**Comment by physics-enthusiast** [comment]
That is expected, since AFAIK unpriviledged applications being able to cause a shutdown at will constitutes a DDOS vulnerability (I think). Use ```sudo reboot```, the graphical shutdown, the physical button or just cut the power. Of course, this is assuming you have nothing running on there that cannot handle a little downtime (like some kind of mission critical server, for instance). If by any chance you do, untangling ```waiting for lock``` could get significantly more troublesome.
