### ISSUE TITLE
Similar derivations: cargo-espflash and espflash

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#285240]
## Issue description

Recently (https://github.com/NixOS/nixpkgs/pull/275490) the new package `espflash` was added to nixpkgs.
But the outputs are extremely similar to the existing package `cargo-espflash`, except that it doesn't contain the cargo wrapper executable:

```
$ nix build .#espflash
$ find ./result/
./result/
./result/bin
./result/bin/espflash
$ nix build .#cargo-espflash
$ find ./result/
./result/
./result/bin
./result/bin/cargo-espflash
./result/bin/espflash
```

and the nixpkgs source files for [espflash](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/embedded/espflash/default.nix) and the existing [cargo-espflash](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/rust/cargo-espflash/default.nix) are very similar as well.

Does it really make sense to have them as completly separate derivations? It confused me for a while trying to find out if there were any non-obvious differences.

@matthiasbeyer @newAM

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by newAM** [comment]
Ah, this is my fault, I did not know `cargo-espflash` contained `espflash` when I opened #275490

I have created #286386 to resolve this.
