### ISSUE TITLE
Auto-upgrade fails when using fetchTarball with a .tar.gz

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#28527]
## Issue description

I'm using the following...

```nix
{
    # ...
    unstable = (import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) combinedOptions);
    # ...
}
```

... to install a number of packages from the `unstable` channel. This works fine when running a `nixos-rebuild` manually, but it fails in the auto-upgrade service, with the following error:

```
[...]
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: unpacking ‘https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz’...
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: tar (child): gzip: Cannot exec: No such file or directory
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: tar (child): Error is not recoverable: exiting now
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: tar: Child returned status 2
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: tar: Error is not recoverable: exiting now
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: error: program ‘tar’ failed with exit code 2
Aug 24 04:40:46 desktop-home nixos-upgrade-start[22952]: (use ‘--show-trace’ to show detailed location information)
[...]
```

Presumably, this is caused by [this line](https://github.com/NixOS/nixpkgs/blob/0b6812ee9acb3a520d68ea14440b488e3f629922/nixos/modules/installer/tools/auto-upgrade.nix#L81) in the service, which appears to only specify a limited set of packages that doesn't include `gzip`. It seems the `systemPackages` are not included in the `PATH` at all.

I'm not sure how this could be solved correctly; the quick fix would be to add `gzip` to the `path` attribute, but this doesn't really scale to other custom logic that people might have in their `configuration.nix`. Perhaps all `systemPackages` should be explicitly added to the `path` as well, so that the behaviour is the same as when running `nixos-rebuild` from a shell?

### Steps to reproduce

1. Use `fetchTarball` in `configuration.nix`, pointing at a `.tar.gz` file.
2. Set up the `autoUpgrade` service: `system.autoUpgrade.enable = true;`
3. Wait for the timer to roll around, or trigger the unit manually :)

## Technical details

* System: 17.03.1700.51a83266d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1700.51a83266d1"
* Sandboxing enabled: false

**Comment by Mic92** [comment]
You should be able to override in your own configuration.nix:

```
{
  systemd.services.nixos-upgrade.path = [];
}
```

**Comment by joepie91** [comment]
Hmm, that's not really a generalizable solution though - if I use something new, this will break again, and it wouldn't be obvious unless I diligently checked my `nixos-upgrade` unit logs.

It'd probably be more practical to have something as a default that just uses the current system environment, since that way it'd match the command-line behaviour and therefore provide the least astonishment.
