### ISSUE TITLE
Should we reduce Agda closure size by 4.4 GiB by unbundling libHSAgda.a and GHC?

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#285261]
With the standard library, cubical and categories, agdaWithPackages has a closure size of about 4.9 GiB ([full closure info here](https://github.com/NixOS/nixpkgs/files/14111446/agda-closure-size.txt)):

```
$ nix path-info --size --closure-size --recursive /nix/store/jnniclsy557w9n0lnj8vdbpysagkfqsc-agdaWithPackages-2.6.4.1
[...]
/nix/store/jnniclsy557w9n0lnj8vdbpysagkfqsc-agdaWithPackages-2.6.4.1 1080      5104341536
```

Among the larger culprits are 600 MiB of libHSAgda-[...].a and GHC itself.

Personally I'm using https://github.com/iblech/agdapad/blob/master/backend/slim-agda.nix where I zero out the dependence on GHC and just fetch the Agda binary. I've been using this for years and never encountered any problems.

Should we incorporate something like this in nixpkgs?

**Comment by phijor** [comment]
I currently have a number of parallel installations of Agda on my machines, and I'd like to see a reduction of closure size. I think there are two separate space hogs, each with diff

1. The `Agda` Haskell library.  The [manual](https://nixos.org/manual/nixpkgs/stable/#haskell-packaging-helpers) mentions two helpers to reduce closure size: `justStaticExecutables` (removes references to libraries and docs) and `enableSeparateBinOutput` (installs binaries in a separate `bin` output). I tried setting `enableSeparateBinOutput`, but it breaks `agda-mode`.<sup>See below</sup>
2. The `ghc` attribute passed to `agda.withPackages`: I don't use Agda's GHC backend, so I provide a "fake GHC" to reduce closure size:
    ```nix
    # Use with callPackage:
    {
      agda,
      writeShellApplication,
    }: let
      fake-ghc = writeShellApplication {
        name = "ghc";
        text = ''
          echo "Compiling Agda via GHC has been disabled" 1>&2
          exit 2
        '';
      };
    in
    agda.withPackages {
      pkgs = p: [
        p.standard-library
        p.cubical
      ];
      ghc = fake-ghc;
    }
    ```
    Maybe `agda.withPackages` could be changed so that `agda.withPackages { ghc = null; }` disables compilation via GCH. E.g. we could pass `--with-compiler=<GHC stub>` and `--ghc-dont-call-ghc` to the wrapped `agda` binary.

---

Applying `enableSeparateBinOutput` to `haskellPackages.Agda` and running `nixpkgs-review` results in the following output:

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>cedille</li>
    <li>emacsPackages.cedille</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>emacsPackages.agda2-mode</li>
  </ul>
</details>
<details>
  <summary>Build log of <code>emacsPackages.agda2-mode</code></summary>

```log
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
/nix/store/v5lsd029lz5lfhamivbgqyp3zdv94ah2-stdenv-linux/setup: line 1578: /nix/store/4lni1yr0lcdylwlrv52cl1gn92sgnpsj-Agda-2.6.4.3/bin/agda-mode: No such file or directory
```
</details>
