### ISSUE TITLE
Update request: gnomeExtensions.ddterm 48 → 50

### ISSUE THREAD

**Issue by edgar-vincent** [NixOS/nixpkgs#285288]
- Package name: gnomeExtensions.ddterm
- Latest released version: 50

- Current version on the unstable channel: 48
- Current version on the stable/release channel: 48

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@piegamesde Thanks!

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 4JX** [comment]
Version 49 is contained in #282143 ([here](https://github.com/NixOS/nixpkgs/pull/282143/files#diff-984008ceb2d09a8ffb4d27373f96d2eb8e07d3ec172198ef5d5fcd85b90922daR2675)), looks like 50 didn't make it to that PR
