### ISSUE TITLE
nix-collect-garabage causes recompile of emacs24

### ISSUE THREAD

**Issue by mgrbyte** [NixOS/nixpkgs#2852]
Have the following entries in environment.systemPackages:
    emacs
    (emacs.override { gtk = pkgs.gtk3; })

doing:
  nix-collect-garbage
then:
  nixos-rebuild test/switch

causes emacs24 to be compiled every time.
I'm guessing this is something to do with .elc files needing to be compiled on install (before hashing) ? 

If someone can point me in the right direction will try and write a patch.
Thanks!

**Comment by Profpatsch** [comment]
Probably not happening any more. I suggest to close @domenkozar
