### ISSUE TITLE
Bootstrap a nix store in a docker image

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#28535]
I would like to use nix in a docker container built with `pkgs.dockerTools.buildImage` but there is currently no nix database in this container.

Currently, at image build time, the user can specified contents (nix store paths) which are rsync into the layer. At container runtime, the `/nix/store` contains expected files, but `/nix/var` doesn't exist.
This works pretty well, expects if the user wants to use nix and have a correct store in the container. In this case, I think we would have to initialize a container nix database.

I'm trying to boostrap the nix store but I'm not able to find a way to fill the nix database. I've tryied a bit with `nix-store --dump-db` but it dumps the whole database while I only need a subset of it.
I also try to put the nix store in a different place (not in `/nix/store`) but this leads to others problems (no cache, no relocation...).

Is there a example of the boostraping of a prefiled nix store?
How could I initialize a nix database by selecting a subset of an existing nix store?
Do you have other ideas to use nix in a Docker container?

**Comment by copumpkin** [comment]
Our disk image building machinery does a lot of this. Check how `nixos-prepare-root.sh` works for example.

**Comment by copumpkin** [comment]
It might make sense to split `nixos-prepare-root` from the stuff that just prepares a Nix store and registers packages in it. Then `nix-prepare-root` could be used for non-NixOS images, and `nixos-prepare-root` would overlay `/etc/NIXOS`, set up the system profile, and other NixOS-specific stuff.

**Comment by nlewo** [comment]
Thanks a lot @copumpkin !
I only have to add few lines to the docker builder to populate the store as you can see in #28561.

Note there is also `qemu-vm.nix` that does similar kind of things. I agree with you it would be nice to centralize this kind of operations.
