### ISSUE TITLE
builtins.concatStringsSep give different output when bind to a variable.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28533]
given `a.nix`

    with import <nixpkgs> {};
    with luaPackages;

    let
      libs = [lua cjson luasocket luasec];
    in
    stdenv.mkDerivation rec {
      name = "lua-env";
      buildInputs = libs;

      shellHook = ''
        export LUA_CPATH="${builtins.concatStringsSep ";" (map getLuaCPath libs)}"
        export LUA_PATH="${builtins.concatStringsSep ";" (map getLuaPath libs)}"
      '';
    }

and `b.nix`

    with import <nixpkgs> {};
    with luaPackages;

    let
      libs = [lua cjson luasocket luasec];
      luaPath = builtins.concatStringsSep ";" (map getLuaPath libs);
      luaCPath = builtins.concatStringsSep ";" (map getLuaCPath libs);
    in
    stdenv.mkDerivation rec {
      name = "lua-env";
      buildInputs = libs;

      shellHook = ''
        export LUA_PATH=${luaPath}
        export LUA_CPATH=${luaCPath}
      '';
    }

yield different paths

    $ nix-shell a.nix --run 'echo $LUA_CPATH; echo $LUA_PATH'
    /nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/lib/lua/5.2/?.so;/nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/share/lua/5.2/?.so;/nix/store/ppdspfcm5nnfz0fk9zarjmpyv5lcmn18-lua5.2-cjson-2.1.0/lib/lua/5.2/?.so;/nix/store/ppdspfcm5nnfz0fk9zarjmpyv5lcmn18-lua5.2-cjson-2.1.0/share/lua/5.2/?.so;/nix/store/b71xyq7gkc8iccj6wr84zq31gqc3m9ix-lua5.2-socket-3.0-rc1/lib/lua/5.2/?.so;/nix/store/b71xyq7gkc8iccj6wr84zq31gqc3m9ix-lua5.2-socket-3.0-rc1/share/lua/5.2/?.so;/nix/store/6q8xn2bcfskmrfzql47jld5d2irvn5jr-lua5.2-sec-0.6/lib/lua/5.2/?.so;/nix/store/6q8xn2bcfskmrfzql47jld5d2irvn5jr-lua5.2-sec-0.6/share/lua/5.2/?.so
    /nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/lib/lua/5.2/?.lua;/nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/share/lua/5.2/?.lua;/nix/store/ppdspfcm5nnfz0fk9zarjmpyv5lcmn18-lua5.2-cjson-2.1.0/lib/lua/5.2/?.lua;/nix/store/ppdspfcm5nnfz0fk9zarjmpyv5lcmn18-lua5.2-cjson-2.1.0/share/lua/5.2/?.lua;/nix/store/b71xyq7gkc8iccj6wr84zq31gqc3m9ix-lua5.2-socket-3.0-rc1/lib/lua/5.2/?.lua;/nix/store/b71xyq7gkc8iccj6wr84zq31gqc3m9ix-lua5.2-socket-3.0-rc1/share/lua/5.2/?.lua;/nix/store/6q8xn2bcfskmrfzql47jld5d2irvn5jr-lua5.2-sec-0.6/lib/lua/5.2/?.lua;/nix/store/6q8xn2bcfskmrfzql47jld5d2irvn5jr-lua5.2-sec-0.6/share/lua/5.2/?.lua

    $ nix-shell b.nix --run 'echo $LUA_CPATH; echo $LUA_PATH'
    /nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/lib/lua/5.2/?.so
    /nix/store/lp0ns0hjwx1klk6amnyic3f62bw7h8j7-lua-5.2.3/lib/lua/5.2/?.lua
---
 * System: NixOS: 17.09pre112899.129f8d7e99 (Hummingbird)
 * Nix version: nix-env (Nix) 1.11.13
 * Nixpkgs version: "17.09pre112899.129f8d7e99"
 * Sandboxing enabled: build-use-sandbox = true

**Comment by copumpkin** [comment]
I can't test this because it depends on Lua which is broken right now on macOS 😄 also, the bug probably belongs in the Nix tracker, since nothing in nixpkgs should be able to differ in behavior based on how it's bound.

cc @edolstra

**Comment by edolstra** [comment]
In
```
    export LUA_PATH=${luaPath}
    export LUA_CPATH=${luaCPath}
```
you dropped the quotes around `${...}`. So bash will interpret the semicolons as statement separators.
