### ISSUE TITLE
gplates while loading shared libraries: libSM.so.6

### ISSUE THREAD

**Issue by Canadauni** [NixOS/nixpkgs#285373]
### Describe the bug
Unable to launch gplates on NixOS. A shared object file appears to be missing.

### Steps To Reproduce
1. `nix-shell -p gplates`
2. `gplates`
3. Output:
`gplates: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory`

### Expected behavior
gplates is expected to launch and be usable.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
No listed maintainers on Nix Packages but @wegank was the last to touch the source for this application.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 23.11 (Tapir), 23.11.3376.1b64fc128799`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment]
Probably adding `libSM` to `buildInputs` and/or adding `autoPatchelfHook` to `nativeBuildInputs` might help, but I'm too tired to debug tonight. I'll look into it in the next few days.

**Comment by Canadauni** [comment]
Thank you, I was reading about the first option you suggested being a potential fix. I'll see if I can wrap my head around doing it on my own as well this week, though I don't have a lot of experience contributing to projects likes this.
