### ISSUE TITLE
Build failure: python310Packages.debugpy

### ISSUE THREAD

**Issue by saaperezru** [NixOS/nixpkgs#285393]
### Steps To Reproduce

1. Run `nix-shell -p python310Packages.debugpy`

### Build log

```
Running phase: installPhase
Executing pypaInstallPhase
*** Error compiling '/nix/store/g1ia17mcp79fzqq8iamm07x5z1aqlrzy-python3.10-debugpy-1.8.0/lib/python3.10/site-packages/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_scoped_stepping_target_async.py'...
  File "/nix/store/g1ia17mcp79fzqq8iamm07x5z1aqlrzy-python3.10-debugpy-1.8.0/lib/python3.10/site-packages/debugpy/_vendored/pydevd/tests_python/resources/_debugger_case_scoped_stepping_target_async.py", line 5
    await asyncio.sleep(.01)
    ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function

rootdir: /build/source
configfile: pytest.ini
testpaths: tests
plugins: timeout-2.2.0, xdist-3.5.0
8 workers [1216 items] m
........................................................................ [  5%]
........................................................................ [ 11%]
........................................................................ [ 17%]

```
Then it gets stuck.

### Additional context

This started happening a week ago, and seems like it could be related to this:

https://github.com/microsoft/debugpy/issues/1490

### Notify maintainers

@kira-bruneau
@SuperSandro2000

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.9-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.1
 ````

Also reported in 
https://github.com/nix-community/home-manager/issues/4977

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
You are trying with python 3.10 but the issue you linked seems to be specific to 3.12. Also currently the main supported python version is 3.11.

**Comment by SuperSandro2000** [comment]
Can't reproduce this on nixos-unstable with python310Packages.debugpy, python311Packages.debugpy is cached and python312Packages.debugpy is marked broken because pbr isn't compatible with 3.12.

> Is there a workaround to always pick the python package with the version currently supported by nixpkgs?

Yes, you can use python3Packages.

**Comment by gzagatti** [comment]
Thanks for your help!

**Comment by RuRo** [comment]
I think I can reproduce this with
```sh
nix build --rebuild --no-link --print-out-paths \
    "github:NixOS/nixpkgs/9df3e30ce24fd28c7b3e2de0d986769db5d6225d#python311Packages.debugpy"
```

Here are the full [build logs](https://gist.github.com/RuRo/204cbb5756594c7932d56af6565db1b4).

Can we reopen this issue, or should I open a new one?

**Comment by RuRo** [comment]
Removing `pytestFlagsArray = ["--timeout=0"];` reveals that a whole bunch of tests are timing out:
```
test_args
test_run
test_frame_eval
test_input
test_log_dir_env
test_redirect_output
test_stdin_not_patched
test_success_exitcodes
test_systemexit
test_with_no_output
```

Adding them to `disabledTests` fixes the build, however I have no idea why they are timing out, so blindly disabling them might not be the best idea.
