### ISSUE TITLE
Build failure: python311Packages.librosa

### ISSUE THREAD

**Issue by me00001** [NixOS/nixpkgs#285489]
### Steps To Reproduce

1. Be in nixos-unstable chanale
2. Run `nix-shell -p pitivi`

### Build log
https://paste.dismail.de/?6f803707601bb2cc#Bydp9oVTiLHojVxPnxhDXT8buTg5RYMiMZdwvLWSyk3y

### Notify maintainers

@AkechiShiro @GuillaumeDesforges 
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05pre572380.842d9d80cfd4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(suliman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
Hi @me00001 thanks for the report but I'm not using the package anymore, I have attempted to fix it in the past.

I'll be removing myself as maintainer with a PR.

I will try to take a look in details at the logs if I can find the time and see if I can leave helpful comment for anyone willing to investigate more further

**Comment by GuillaumeDesforges** [comment]
Not using it as well, but I can give it a quick look

**Comment by GuillaumeDesforges** [comment]
I could get it to nix build with the following test on master

```nix
{ nixpkgs ? builtins.getFlake (builtins.toString ./.)
, pkgs ? nixpkgs.legacyPackages.x86_64-linux
}:

pkgs.python3Packages.librosa.overridePythonAttrs (old:
{
  disabledTests = old.disabledTests ++ [
    "test_nnls_vector"
  ];
})

```

IMO we can just ignore that test. I'll make a PR.
