### ISSUE TITLE
Firefox cherry-picks are breaking 17.03

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#28553]
Build log says `rustc` won't build: https://hydra.nixos.org/build/59281659

Probably one of a24fbb583e / 9ba6492515 / 713e9e0278

cc @globin

**Comment by tokudan** [comment]
I wonder if it's really firefox causing the issue.
The rustc build log shows:
> failures:
>     net::tcp::tests::fast_rebind

I'm able to build pkgs.rustc without any issues:
```
$ git log -1 | head -2
commit 3f96be21d04600857e2748418e95d8edbecb74db
Merge: f7ff041d03 74c3c2c039
$ nix-build . -A pkgs.rustc
/nix/store/a4k3xqygkw6alpnr3l61cd0fw15w61nf-rustc-1.15.1
```

Though the path is different, it shows that rustc in general is building. I haven't been able to figure out through which path hydra is trying to build that rustc.
Looking at the error message from hydra it could even be just a random failure (socket already in use).
So how can we identify what hydra is actually trying to build?

**Comment by tokudan** [comment]
I've successfully built https://hydra.nixos.org/build/59404423 on my system, so I believe this is an error on hydra's side.

**Comment by globin** [comment]
restarted the builds

**Comment by obadz** [comment]
Looks like that fixed it, thanks.
