### ISSUE TITLE
Upstream change (or not) discussion: curl-impersonate 

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#285618]
- Package name: curl-impersonate
- Latest released version: 0.5.4 in the original repo / 0.6.0b9 in a fork; corresponds to Chrome 110 → Chrome 120
- Current version on the unstable channel: 0.5.4
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

I am not completely sure; the original upstream https://github.com/lwthiker/curl-impersonate has seen no commits for ≈5 months (nor issue comments from the original maintainer); one of the forks https://github.com/yifeikong/curl-impersonate has its own forks, has seen a commit this week, has merged PRs from three other accounts, and even tags releases.

On the security side, the fork uses curl 8.1.1 with a WIP PR for 8.5.0. 

One thing to note is that the fork is in the process of dropping Firefox impersonation, because upstream curl has dropped NSS support, leaving Firefox approximately the only project using NSS for TLS. The fork does consider investigating how to impersonate NSS using BoringSSL, but I have no idea what are the chances they will seriously try.

Pragmatically, I am not sure how to fix a pretty weird novel warning from gcc, but with forced `-Wno-error` a stupid update seems to work; I am not sure what is the proper approach to naming in this situation.

**Notify maintainers**

@lilyinstarlight @deliciouslytyped 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 7c6f434c** [comment]
https://github.com/7c6f434c/nixpkgs/tree/curl-impersonate-yifeikong if anyone wants this

**Comment by deliciouslytyped** [comment]
If @lilyinstarlight is fine with it, I should probably be removed from the maintainer list since I don't see myself contributing effectively to the package currently. I was just happy to get the binary version in nixpkgs.

**Comment by 7c6f434c** [comment]
Given your previous effort investment, as long as you are still interested in using the package, your preferences (or concerns or considerations not to miss) about the organisational decisions are definitely valuable to know!

Actually I would be happy to know the opinions of everyone who has used the package before and is likely to use it in the future, but unlike

**Comment by deliciouslytyped** [comment]
@7c6f434c seems to just be a zlib update though? https://github.com/NixOS/nixpkgs/issues/289010

**Comment by wegank** [comment]
The latest version is now 0.6.0 in the original repo: https://github.com/lwthiker/curl-impersonate/releases/tag/v0.6.0

**Comment by 7c6f434c** [comment]
Oh, that's nice. We'll see what happens with curl 8.5.0+…

**Comment by deliciouslytyped** [comment]
That's what I'm saying, unless I missed something (very likely?) the only thing 0.6.0 does is update zlib?

**Comment by 7c6f434c** [comment]
It has curl-8.1.1 instead of curl-7.x, which is not enough but a good improvement. It also has fresher Chrome signatures. So it has regained parity with the fork w.r.t. the main issues.

**Comment by deliciouslytyped** [comment]
Oh, I realized my error; I was only looking at the recent commits from last week but the substantial changes were from months ago.
