### ISSUE TITLE
Switch base16-schemes to new schemes repo

### ISSUE THREAD

**Issue by fabiandrinksmilk** [NixOS/nixpkgs#285671]
### Describe the bug
The `base16-schemes` package uses the [tinted-theming/base16-schemes](https://github.com/tinted-theming/base16-schemes) repository, which has now been archived by the owner in favor of [tinted-theming/schemes](https://github.com/tinted-theming/schemes)

### Steps To Reproduce
1. Search for the base16-schemes package on search.nixos.org
2. Either click on the homepage link or find the repo from the source
3. Find out that it's archived

### Expected behavior
The package should use the new repo to include more schemes that aren't available in the old repo.

### Screenshots
The README of the old repo:
![image](https://github.com/NixOS/nixpkgs/assets/52062042/f430276a-8aa8-4893-b0d4-0b1bbd9bc899)

### Notify maintainers
@DamienCassou 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DamienCassou** [comment]
@fabiandrinksmilk Can you please test https://github.com/NixOS/nixpkgs/pull/286272?
