### ISSUE TITLE
The Broadcom 4331 firmware does not always load

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#28567]
## Issue description

Since upgrading to * NixOS 17.09pre113138.96457d26dd (Hummingbird)* the Broadcom 4331 (wireless network card) firmware intermittently does not load. Yeah... it's one of *those* problems. The error is visible in the log:

```
Aug 25 10:49:52 nixos kernel: b43-phy0: Broadcom 4331 WLAN found (core revision 29)
Aug 25 10:49:52 nixos kernel: b43-phy0: Found PHY: Analog 9, Type 7 (HT), Revision 1
Aug 25 10:49:52 nixos kernel: b43-phy0: Found Radio: Manuf 0x17F, ID 0x2059, Revision 0, Version 1
Aug 25 10:49:52 nixos kernel: b43-phy0 warning: 5 GHz band is unsupported on this PHY
Aug 25 10:49:52 nixos kernel: Broadcom 43xx driver loaded [ Features: PNL ]
Aug 25 10:49:52 nixos kernel: audit: type=1130 audit(1503672586.700:10): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-rfkill comm="systemd" exe="/nix/store/8wb8g02r5r316hmwmb8rndhy55lsb3k3-systemd-234/lib/systemd/systemd" hostname=? addr=? terminal=? res=su
Aug 25 10:49:52 nixos kernel: audit: type=1130 audit(1503672586.700:11): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-modules-load comm="systemd" exe="/nix/store/8wb8g02r5r316hmwmb8rndhy55lsb3k3-systemd-234/lib/systemd/systemd" hostname=? addr=? terminal=? 
Aug 25 10:49:52 nixos kernel: b43 bcma0:1: Direct firmware load for b43/ucode29_mimo.fw failed with error -2
Aug 25 10:49:52 nixos kernel: b43 bcma0:1: Direct firmware load for b43/ucode29_mimo.fw failed with error -2
Aug 25 10:49:52 nixos kernel: b43 bcma0:1: Direct firmware load for b43-open/ucode29_mimo.fw failed with error -2
Aug 25 10:49:52 nixos kernel: b43 bcma0:1: Direct firmware load for b43-open/ucode29_mimo.fw failed with error -2
Aug 25 10:49:52 nixos kernel: b43-phy0 ERROR: Firmware file "b43/ucode29_mimo.fw" not found
Aug 25 10:49:52 nixos kernel: b43-phy0 ERROR: Firmware file "b43-open/ucode29_mimo.fw" not found
Aug 25 10:49:52 nixos kernel: b43-phy0 ERROR: You must go to http://wireless.kernel.org/en/users/Drivers/b43#devicefirmware and download the correct firmware for this driver version. Please carefully read all instructions on this website.
```

Thus far, a reboot *fixes* the issue. In contrast, I was previously running *NixOS 17.09pre113107.a0306821fd* and did not experience this issue.

### Steps to reproduce

Assuming you have a Broadcom 4331 wireless network card...

1. Enable the Broadcom driver in `/etc/configuration.nix`: 

```
boot.kernelModules = ["wl" ];
boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
nixpkgs.config.allowUnfree = true;
```
2. `nixos-rebuild` using NixOS unstable branch on commit. 96457d26dded05bcba8e9fbb9bf0255596654aab

```
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
git checkout 96457d26dded05bcba8e9fbb9bf0255596654aab
cd ..
nixos-rebuild -I nixpkgs=./nixpkgs boot
```
3. Reboot.

## Technical details

* System: NixOS 17.09pre113138.96457d26dd (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre113138.96457d26dd
* Sandboxing enabled: build-use-sandbox = true

**Comment by dezgeg** [comment]
Those messages imply that the kernel's built-in `b43` driver got loaded before your proprietary `wl` driver. So you need to blacklist that (what exactly needs blacklisting is documented somewhere online IIRC) or maybe there's even the possibility getting the open source builtin driver to work once given the right firmware files.

**Comment by emmanuelrosa** [comment]
Ahhhh. I didn't know about the `b43` driver. I would have used it instead.

I removed the `wl` driver to allow the `b43` driver to take over, also adding this to my config:

`networking.enableB43Firmware = true;`

So far so good. Thank you @dezgeg

**Comment by Mic92** [comment]
Is this issue resolved?
