### ISSUE TITLE
fixup-yarn-lock / prefetch-yarn-deps can't parse some lockfiles

### ISSUE THREAD

**Issue by vivlim** [NixOS/nixpkgs#285703]
### Describe the bug
I was trying to update my mastodon (glitch-soc) server, but the update script was failing. I tracked it down to fixup-yarn-lock failing to parse the yarn.lock file in the repo.

### Steps To Reproduce
1. Download [not-working.yarn.lock.txt](https://github.com/NixOS/nixpkgs/files/14135892/not-working.yarn.lock.txt), or [grab it from the repo](https://raw.githubusercontent.com/glitch-soc/mastodon/main/yarn.lock). I got it from https://github.com/glitch-soc/mastodon/commit/5fa28218532c5cb886c7f0c7d3bf75f9ac4d9637
2. Run `fixup-yarn-lock not-working.yarn.lock.txt`. My flake happens to be pointing at https://github.com/NixOS/nixpkgs/commit/5ad9903c16126a7d949101687af0aa589b1d7d3d, so the version of `fixup-yarn-lock` I got was from that commit.

The error I get is:
```
SyntaxError: Unknown token: { line: 4, col: 12, type: 'NUMBER', value: 1 } 4:12 in lockfile
    at Parser.unexpected (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5064:11)
    at Parser.parse (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5193:14)
    at Parser.parse (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5147:28)
    at Parser.parse (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5147:28)
    at parse (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:5262:17)
    at module.exports.exports.default (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/yarnpkg-lockfile.js:4835:96)
    at fixupYarnLock (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/fixup.js:10:28)
    at main (/nix/store/nj12l3mc3jl02lf0fb9zfq0ckgdgh2xn-prefetch-yarn-deps/libexec/fixup.js:68:26)
```

#### Workaround
edit: this is insufficient as a workaround, and possibly incorrect, I hit problems further down the line. see https://github.com/NixOS/nixpkgs/issues/277697#issuecomment-1922445558
~~By chance, I stumbled on https://github.com/VHT/yarn-lock-converter, which is in nixpkgs as `yarn-lock-converter`.
It takes a bit over a minute and half to finish but the resulting lockfile *doesn't* fail to parse. I attached my result here: 
[working.yarn.lock.txt](https://github.com/NixOS/nixpkgs/files/14135893/working.yarn.lock.txt)~~

### Additional context
From what I can tell, Mastodon recently moved to yarn v4, I couldn't find anything on google about breaking changes in yarn's lockfile format between versions but I'm not active in that ecosystem so I could've missed something.

I think this is relevant to #240174.

### Notify maintainers
The maintainer of https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/node/fetch-yarn-deps/fixup.js appears to be @lilyinstarlight .

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vivlim** [comment]
tagging mastodon maintainers (@happy-river @erictapen @izorkin @ghuntley) as a heads up, since without a workaround, applying the fix for [this critical security issue announced today](https://github.com/mastodon/mastodon/security/advisories/GHSA-3fjr-858r-92rw) is blocked.

**Comment by LunNova** [comment]
Did https://github.com/NixOS/nixpkgs/pull/285558 not actually address the issue for mastodon?

**Comment by vivlim** [comment]
Ah, I think I was looking at `nixpkgs-unstable` and not `master`, that should fix the security issue.

**Comment by 999eagle** [comment]
There's also #277697 already specifically for Mastodon and #254369 for the new lockfile format in general.

**Comment by erictapen** [comment]
So, not security relevant anymore, just a blocker for Mastodon 4.3, right?
Please also note that glitch-soc isn't a part of Nixpkgs yet, so we don't really maintain it.

Can we close this in favor of https://github.com/NixOS/nixpkgs/issues/277697 or am I overseeing something?

**Comment by winterqt** [comment]
This is a dupe of a few issues (#277697 and #254369 to name a few), yes.
