### ISSUE TITLE
GitKraken: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#285820]
### Describe the bug
The application is crashing when trying to open a file

### Steps To Reproduce
1. Try to open a repository
3. The application crashes

### Expected behavior
Supposed to open a file exploer

### Screenshots
```
(gitkraken:19878): GLib-GIO-ERROR **: 16:18:39.045: No GSettings schemas are installed on the system
[1]    19878 trace trap (core dumped)  gitkraken
```

### Additional context
Using KDE Plasma 5 under wayland

### Notify maintainers

@nicolas-goudry 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.2, NixOS, 24.05 (Uakari), 24.05pre577948.97b17f32362e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixpkgs"`
 - channels(ciflire): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nicolas-goudry** [comment]
I’m running Gnome 45 under Wayland and the « Open a Repository » feature is working fine.

I’ll give a look with KDE Plasma 5 when I have some time.

**Comment by yswtrue** [comment]
same here

**Comment by yswtrue** [comment]
> works or it does not?

not work
kde + wayland
```
(gitkraken:19878): GLib-GIO-ERROR **: 16:18:39.045: No GSettings schemas are installed on the system
```
