### ISSUE TITLE
Update request: arcan 0.6.2.1 → 0.6.3

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#285842]
- Package name: arcan
- Latest released version: 0.6.3

- Current version on the unstable channel: 0.6.2.1-unstable-2023-10-14
- Current version on the stable/release channel: 0.6.2.1-unstable-2023-10-14

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@AndersonTorres 

-----

Note for maintainers: Please tag this issue in your PR.

Tagged 2023-12-19: https://chiselapp.com/user/letoram/repository/arcan/timeline?t=0.6.3

According to the project’s latest [blog entry](https://arcan-fe.com/2023/12/19/arcan-0-6-3-i-pty-the-fool/), the Arcan team is adamant about cutting ties with GitHub (& Discord 🥳) so the updates should respect the maker’s wishes and point to the Fossil project which now lives here: https://chiselapp.com/user/letoram/repository/arcan/home

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
> & Discord 🥳

FINALLY!

**Comment by FliegendeWurst** [comment]
Done in #310831
