### ISSUE TITLE
Pulumi language plugin warning

### ISSUE THREAD

**Issue by jjhuff** [NixOS/nixpkgs#285848]
### Describe the bug
Pulumi does some path comparison to ensure that its language plugin binaries 'match' its main cli -- essentially that they're installed in the same place. The `pulumi` package packages the languages separately and thus, the path comparison fails and pulumi spits out warnings:
```
    warning: using pulumi-language-nodejs from $PATH at /nix/store/v7qgln7y0ag3yq17c2rdpda6r392gr44-devenv-profile/bin/pulumi-language-nodejs
```
```
$ ls -l /nix/store/v7qgln7y0ag3yq17c2rdpda6r392gr44-devenv-profile/bin/pulumi*
lrwxrwxrwx 1 root root  68 Dec 31  1969 /nix/store/v7qgln7y0ag3yq17c2rdpda6r392gr44-devenv-profile/bin/pulumi -> /nix/store/sz30zi87gcb61rqd6dxhqb6kmz131w48-pulumi-3.93.0/bin/pulumi
lrwxrwxrwx 1 root root 100 Dec 31  1969 /nix/store/v7qgln7y0ag3yq17c2rdpda6r392gr44-devenv-profile/bin/pulumi-language-nodejs -> /nix/store/8scsrp9ff1fnyypwmbjb8ll2q4g8yg7x-pulumi-language-nodejs-3.93.0/bin/pulumi-language-nodejs
```

Pulumi bug with some extra discussion:
https://github.com/pulumi/pulumi/issues/14525

I'm a n00b on nix packaging, but would be be possible to have a single `pulumi` package with options to enable the plugins of your choosing?

@trundle
@veehaitch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-91-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by medv** [comment]
@jjhuff same question here. I've been sort of sitting on this particular problem as a good possible gateway into killing a lot of time to understand nix on a lower level. I feel like the answers here would also apply to providing the right paths to say LSP servers for neovim (instead of having Mason install them somewhere in $HOME), but have not yet had the time. If nobody chimes in, maybe we can figure it out in the long term between us.. It's sort of a noob thing that people won't have the time to educate which is fair enough.

**Comment by medv** [comment]
@jjhuff same question here. I've been sort of sitting on this particular problem as a good possible gateway into killing a lot of time to understand nix on a lower level. I tried all of the low hanging fruit ideas like `pulumi.withPackages` and a handful of other things, most of them worked but the warning never went away.

If nobody chimes in, maybe we can figure it out in the long term between us.. It's sort of a noob thing that most people won't have the time to educate on, which is fair enough.

**Comment by folliehiyuki** [comment]
I don't think there should be anything to do on Nixpkgs side. The only "fix" I can think of is to put all the binaries into a single nixpkgs package (like what `pulumi-bin` package is). I don't like this approach though, as nixpkgs is designed around separation, and most of the time a user only needs `pulumi` binary with a single language engine binary. I'd argue that requiring all the binaries to be in the same directory is a bad packaging decision.

The warning is rather harmless, in my opinion, so can we all just ignore it? The linked issue also suggests that upstream is fine with a compromise on their end and is open to a community PR.
