### ISSUE TITLE
Package request: gforth-unstable

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#285890]
**Project description**
the bleeding-edge version of gforth has a ton of features not found in the latest release.  most package managers with gforth have a seperate package for the unstable/dev version.

**Metadata**

* homepage URL: gforth.org
* source URL: https://www.complang.tuwien.ac.at/forth/gforth/Snapshots/current/
* license: gpl
* platforms: unix, linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
There are release tags here https://github.com/forthy42/gforth/tags which seem reasonable up to date, the package just needs to be updated. We generally don't want to package prerelease software as it requires way more maintenance. 


You also created a PR to update already here #292671
