### ISSUE TITLE
Kernel regression: keyboard issue with 6.6.13 and higher

### ISSUE THREAD

**Issue by NeuerUser** [NixOS/nixpkgs#286044]
### Describe the bug
Dell XPS 9350 laptop, i5-5200U CPU, nixos 23.11, kernel 6.6.13

Keyboard not working after suspend-resume. When suspend is initiated by closing the lid, keyboard does work after wakeup. Only when suspend is initiated via GUI or on CLI, keyboard is non-functional after resume. To get keyboard functional again, laptop must be turned-off completely.

The bug is a regression. Older kernel versions work without issue:
6.6.12: ok
6.6.13: not working
6.6.14: not working
6.1.74: ok
6.1.75: not working
6.7.x: not working

I tried several kernel options without success: i8042.noaux i8042.nomux i8042.probe_defer i8042.reset (a.o.)

I am a new user of nixos and still need to find out howto do things here (was already happy to find out howto test different kernel versions...).

Should this bug be reported here or better on bugzilla.kernel.org?

Thanks

Michael

**Comment by NeuerUser** [comment]
Linkt o upstream bug: https://bugzilla.kernel.org/show_bug.cgi?id=218460

**Comment by NeuerUser** [comment]
Bug is fixed upstream.

**Comment by bburdette** [comment]
`  boot.kernelPackages = pkgs.pkgs.linuxPackages_6_5;` working for me, FWIW.

**Comment by edrex** [comment]
Should the issue stay open till it's fixed in nixos-unstable's default kernel?

**Comment by edrex** [comment]
* Previously discussed:  [\[SOLVED\] Laptop keyboard stopped working after suspend in 6.6.13/6.7.0 / Kernel & Hardware / Arch Linux Forums](https://bbs.archlinux.org/viewtopic.php?id=292203)
* Main bug: [218424 – commit 274333f8 breaks some laptop keyboard after resume from suspend](https://bugzilla.kernel.org/show_bug.cgi?id=218424)
* Patch thread: [Re: \[PATCH regression fix 0/2\] Input: atkbd - Fix Dell XPS 13 line suspend/resume regression - Dmitry Torokhov](https://lore.kernel.org/linux-input/Zbx1xA5FK_c8EEmm@google.com/)

**Comment by edrex** [comment]
Annoyingly, the offending change seems to have been backported to `6.1.74-xanmod1` (`linuxKernel.packages.linux_xanmod`) as well. I'll run mainline as suggested by bburdette.

**Comment by bburdette** [comment]
If someone thinks to post back here when this fix makes its way to the nixos channels that'd be great.
