### ISSUE TITLE
development/tools/devpi-server: No module named 'py'

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#286156]
### Describe the bug
Devpi server seems to be missing its `py>=1.4.23` dependency

### Steps To Reproduce
1. Run `devpi-server --help` from c002c6aa977ad22c60398daaa9be52f2203d0006

### Screenshots
```shell
$ nix-shell -p devpi-server --run "devpi-server --help"
Traceback (most recent call last):
  File "/nix/store/wxx4bj7cxb9a2znqrxq0dljx48c77m0q-devpi-server-6.9.2/bin/.devpi-server-wrapped", line 6, in <module>
    from devpi_server.main import main
  File "/nix/store/wxx4bj7cxb9a2znqrxq0dljx48c77m0q-devpi-server-6.9.2/lib/python3.11/site-packages/devpi_server/main.py", line 11, in <module>
    import py
ModuleNotFoundError: No module named 'py'
```

### Notify maintainers

@makefu

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by makefu** [comment]
Thanks for the report, it seems like `py` is now a runtime dependency of `devpi-server`. i've created a PR, you can use the changes there as a hotfix.
