### ISSUE TITLE
Fetch nixpkgs in restricted evaluation?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#28613]
I would like to fetch a specific ("pinned") version of nixpkgs from within "restricted evaluation mode" i.e. running under Hydra. Is there a way to do this?

(Currently I am passing in nixpkgs as a Hydra input but I don't like that... I am building a complex nix expression that needs to use multiple specific versions of nixpkgs and I want to maintain this information inside the Nix code and not in the Hydra jobset definition.)

**Comment by FRidh** [comment]
Use Nix 1.12 and its `fetchTarball` function.

**Comment by lukego** [comment]
@FRidh Thanks for the tip. I wonder how to do that in practice when I am building on Hydra? I suppose that I need both Hydra itself and also the build slaves to use that prerelease version of Nix? I am not even sure how the build slaves decide which nix version to use... but I suppose this is a Hydra question now so I will close here :).

**Comment by domenkozar** [comment]
Best way so far is https://nixos.wiki/wiki/How_to_fetch_Nixpkgs_with_an_empty_NIX_PATH
