### ISSUE TITLE
systemd.network.netdevs is missing a bridgeConfig option

### ISSUE THREAD

**Issue by dcarosone** [NixOS/nixpkgs#286238]
### Describe the bug
There are lots of possible entries under `systemd.network.netdevs.<name>.` for all the different sections of a netdev file.  However, a `bridgeConfig` options for the `[Bridge]` section is missing.

### Steps To Reproduce

Attempt to use vlan filtering, stp, or other bridge features, trying to create a netdev file similar to:

```
[NetDev]
Kind=bridge
Name=br0

[Bridge]
VLANFiltering=yes
```

### Expected behavior

To be able to configure the bridge section via nix entities.

The workaround is to use extraConfig:

```nix

  systemd.network = {
    enable = true;
    netdevs = {
      "30-br0" = {
        netdevConfig = {
          Kind = "bridge";
          Name = "br0";
        };
        extraConfig = ''
          [Bridge]
          VLANFiltering=yes
        '';
      };
     …
```

### Additional context

Note that there is a `bridgeConfig` under networks. That's a distinct thing. It's confusing and may have been part of the source of the oversight.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05.20240129.97b17f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/5gc4ncnkzcgma8fl1qabm8v9kj7w68gl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fpletz** [comment]
Fixed by #304117.
