### ISSUE TITLE
Build failure: r-igraph 2.0.1

### ISSUE THREAD

**Issue by PhDyellow** [NixOS/nixpkgs#286406]
### Steps To Reproduce

This is an issue rather than a PR because it involves a future version of a package that has only been released recently upstream. Nixpkgs does not have the future version yet.

When r-igraph 2.0.1 hits nixpkgs, it will fail to build. The fix is to add `pkgs.which` to the package dependency.

`pkgs.glpk` will also be needed, but the error produced clearly pointed to the missing package.

### Build log

Here is the unhelpful build error:

```
Error: Neither xml2-config nor pkg-config is available
```

### Notify maintainers
@jbedo

**Comment by szhorvat** [comment]
FYI this won't be necessary for the next release (hopefully coming next week).
