### ISSUE TITLE
Build failure: mkdocs-simple-hooks

### ISSUE THREAD

**Issue by Tom-Hubrecht** [NixOS/nixpkgs#286480]
### Steps To Reproduce

1. build *python311.packages.mkdocs-simple-hooks*

### Build log

https://hydra.nixos.org/build/247802209/nixlog/1

### Additional context

An update of the nixos-23.11 channel broke `mkdocs-simple-hooks` and by extension `ntfy-sh` can no longer build.

### Notify maintainers

@arjan-s 

### Metadata

Channel used :

```
    name: nixos-23.11
    url: https://releases.nixos.org/nixos/23.11/nixos-23.11.3920.25e3d4c0d359/nixexprs.tar.xz
    hash: 1wx3qxnz0pm3ld7k6gfvlxs7cv8dvj26917c3136ihvg7znfj1i8
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
It builds just fine on the `release-23.11` and `staging-next-23.11` branches.
