### ISSUE TITLE
clang doesn't provide symlink from gcc to clang

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#28647]
As discussed over at http://forum.dlang.org/thread/qybsnwnnsetmwpytgfno@forum.dlang.org it seems that _/usr/bin/gcc_ is missing on Darwin.

Should/can that be added?

**Comment by vcunat** [comment]
I wouldn't expect that to be a good default.  Commands that don't need specifically gcc would better use `cc` or `$CC`.

**Comment by vcunat** [comment]
That is, it might still be a work-around for some stubborn package, to create a wrapper with such a symlink, used by this package specifically but not in general.

**Comment by ThomasMader** [comment]
I see it likewise, the only reason I opened this issue is that if the default environment provides this link shouldn't Nix follow it's lead?

**Comment by vcunat** [comment]
Oh, I see what you meant.

**Comment by matthewbauer** [comment]
It should be respecting the CC variable:

https://github.com/ldc-developers/ldc/blob/f4038aab7c57fd8e869d56640b393309b61a5112/driver/tool.cpp#L25-L72

**Comment by copumpkin** [comment]
@ThomasMader we've generally avoided the compatibility lie that Xcode provides, preferring instead to catch things that expect `gcc` figure out if they actually depend on `gcc` or switch them to use `cc`. It's a question of "do you want to silently do something that's 99% of the time the right thing but will cause really painful-to-track-down issues 1% of the time" vs. "do you want to fix programs that assume `gcc` 10% of the time". I generally prefer the latter approach and in practice most software respects `$CC` or other common generic C compiler mechanisms.

**Comment by ThomasMader** [comment]
Ok I am closing this since I agree with the arguments given.

**Comment by copumpkin** [comment]
Cool, thanks 😄 we could also have a `fakeGcc` derivation for clang platforms for folks who really need something that pretends to be `gcc`, but it would boil down to a symlink in a bin folder  😁

**Comment by ThomasMader** [comment]
Sounds reasonable but maybe it's better to add that when it's really needed.
For my case the problem lies somewhere else and I just wanted to discuss this matter.
