### ISSUE TITLE
odin version dev-2024-02: new base library collection not copied

### ISSUE THREAD

**Issue by sio-k** [NixOS/nixpkgs#286441]
### Describe the bug
Odin introduced the `base` collection in `dev-2024-02`, moving `core:runtime`, `core:intrinsics` and `core:bultin` to there. An installation of the `odin` package as currently found in `nixpkgs` lacks this package collection and as such it's impossible to build most, if not all odin programs using that installation.

### Expected behavior
The compiler compiles e.g. the `hellope` program as found on the odin website.

### Proposed solution
At install, copy `base` to `$out/base`, same as for `core` and `vendor` package libraries.

### Notify maintainers
@luc65r @astavie @znaniye

**Comment by Astavie** [comment]
Looks like this occured in https://github.com/NixOS/nixpkgs/pull/285742. Seems like it was approved without testing? Will make a quick fix right now
