### ISSUE TITLE
Can't start docker daemon in NixOS container

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#28659]
## Issue description
Trying to start the docker daemon in a NixOS container doesn't work.  The error output is copied below.
<pre>
● docker.service - Docker Application Container Engine
   Loaded: loaded (/nix/store/m5jvq2rhhicv2v9r1958f31hd6lm42xq-docker-17.03.2-ce/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /nix/store/0vg8p0y7mrjcks8riqrqh175wmvhid2f-system-units/docker.service.d
           └─overrides.conf
   Active: failed (Result: exit-code) since Mon 2017-08-28 21:49:08 UTC; 33s ago
     Docs: https://docs.docker.com
  Process: 235 ExecStart=/nix/store/m5jvq2rhhicv2v9r1958f31hd6lm42xq-docker-17.03.2-ce/bin/dockerd --group=docker --host=fd:// --log-driver=journald --live-restore (code=exited, status=1/FAIL
 Main PID: 235 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/docker.service

Aug 28 21:49:08 centos-ifs dockerd[235]: time="2017-08-28T21:49:08.290346300Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: WARNING: Module nf_nat not found in d
Aug 28 21:49:08 centos-ifs dockerd[235]: time="2017-08-28T21:49:08.292169291Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: WARNING: Module xt_conntrack no
Aug 28 21:49:08 centos-ifs dockerd[235]: time="2017-08-28T21:49:08.317074726Z" level=info msg="Firewalld running: false"
Aug 28 21:49:08 centos-ifs dockerd[235]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptabl
Aug 28 21:49:08 centos-ifs dockerd[235]: Perhaps iptables or your kernel needs to be upgraded.
Aug 28 21:49:08 centos-ifs dockerd[235]:  (exit status 3)
Aug 28 21:49:08 centos-ifs systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 21:49:08 centos-ifs systemd[1]: Failed to start Docker Application Container Engine.
Aug 28 21:49:08 centos-ifs systemd[1]: docker.service: Unit entered failed state.
Aug 28 21:49:08 centos-ifs systemd[1]: docker.service: Failed with result 'exit-code'.
</pre>

### Steps to reproduce
Create a NixOS container with the following specification:
<pre>
virtualisation.docker.enable = true;
virtualisation.docker.enableOnBoot = true;
</pre>

## Technical details

* System: 17.03.1665.055e5c3578 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: NixOps host: 17.03.1665.055e5c3578, NixOps targets: 17.03.1556.4d1e1d07f9
* Sandboxing enabled: false

**Comment by nlewo** [comment]
I don't know how nixos container works, but this could be a privilege issue. With Docker, I would try to run the container with "--privileged=false" to see if it the cause or not.
Sorry, only my 2 cents...

**Comment by ledettwy** [comment]
I can't run a docker container if the docker daemon won't start.

**Comment by globin** [comment]
You generally won't have enough capabilities inside a container to run docker due to namespace restrictions by the host kernel. This is by design and nothing we can influence. You'll have to use a virtual machine or run it on hardware.
