### ISSUE TITLE
Update request: losslesscut-bin 3.58.0 → 3.59.1

### ISSUE THREAD

**Issue by jyothisv** [NixOS/nixpkgs#286569]
- Package name: losslesscut-bin
- Latest released version: [3.59.1](https://github.com/mifi/lossless-cut/releases/tag/v3.59.1)

- Current version on the unstable channel: 3.58.0
- Current version on the stable/release channel: 3.58.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ShamrockLee

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luzpaz** [comment]
@jyothisv update title aswell

**Comment by ShamrockLee** [comment]
Hi! Thanks for reminding, and sorry for late response.

I just submitted a PR (#290953) that tries to automate the update of `losslesscut-bin`. Please take a look. (If merged, r-ryantm should be able to do the update from now on. User can update it through `nix-shell nix-shell maintainers/scripts/update.nix --argstr package losslesscut-bin` or create an update commit through `nix-shell maintainers/scripts/update.nix --argstr package losslesscut-bin --argstr commit true`).

If you need the update now, I'll open another PR that updates `losslesscut-bin`.

**Comment by jyothisv** [comment]
> Hi! Thanks for reminding, and sorry for late response.
> 
> I just submitted a PR (#290953) that tries to automate the update of `losslesscut-bin`. Please take a look. (If merged, r-ryantm should be able to do the update from now on. User can update it through `nix-shell nix-shell maintainers/scripts/update.nix --argstr package losslesscut-bin` or create an update commit through `nix-shell maintainers/scripts/update.nix --argstr package losslesscut-bin --argstr commit true`).
> 
> If you need the update now, I'll open another PR that updates `losslesscut-bin`.

Appreciate it! I can wait until the PR is merged, no problem.

**Comment by TanvirOnGH** [comment]
#315306
