### ISSUE TITLE
gnome-shell doesn't build because of gjs-internals dependency

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#28658]
## Issue description

https://github.com/NixOS/nixpkgs/commit/6ce688c3d826aafb17f1e410c0e7ccb057c65187 upgrades `gnome-shell` to `spidermonkey_31` and https://github.com/NixOS/nixpkgs/commit/5dacc53af3f4537fab693952b5f13b6cafcde6d4 removes `spidermonkey_24`.

However, as of `v3.22`, `gnome-shell` still depends on `gjs-internals.pc` which is only part of `spidermonkey_24`. The commit to remove use of `gjs-internals`, is only in `3.23`: https://github.com/GNOME/gnome-shell/commit/7a29cc47d4429b0452db9b7cad1f4614935e092b

So, the really weird thing is, via github search, I found a commit to fix this https://github.com/NixOS/nixpkgs/commit/a558519a55065bc48bbe535d3d0fbc08c183e910 and github shows that it's in the `master` branch, but somehow the commit seems to be missing from https://github.com/NixOS/nixpkgs/commits/master/pkgs/desktops/gnome-3/3.22/core/gjs. My local `git log` is consistent with it not being there.

@globin @vcunat, did that not make it into master? Why would github think that it did?

Should we upgrade to `gnome-24` instead of using that fix? Upgrade only `gnome-shell` to `24`? @lethalman 

### Steps to reproduce

https://gist.github.com/bendlas/b3ab0d2850916b850545cf9e92492f23
https://hydra.nixos.org/build/59244165/nixlog/1
https://github.com/NixOS/nixpkgs/issues/28643

## Technical details

* System: 17.09-pre-e9b99ee1aca05aff (Hummingbird) https://github.com/bendlas/nixpkgs/commit/7767c5ae852c1098fa0dae975bcb668c06e5078d
* Nix version: nix-env (Nix) 1.11.13
* Sandboxing enabled: build-use-sandbox = false

**Comment by globin** [comment]
See #28053

**Comment by bendlas** [comment]
Right, #28053 seems to be right around the corner. I'll try it on my dev branch. Any ideas about the ghost commit though?

**Comment by vcunat** [comment]
The months-old change disappeared in a recent merge staging->master 6bbc3a0b245.  I wonder if there were more mistakes in there.

**Comment by vcunat** [comment]
I've already seen us doing a merge that undid part of history, only accidentally discovered later.

**Comment by bendlas** [comment]
Strange, I didn't think merges were able to do that. At least it should be discovered by people trying to pull, right?
It reminds me of a behavior, that I semi-regularly run into, during my rebases, where git would consider commits gone, hence drop them from my PR queue, without them actually having gone upstream...

**Comment by globin** [comment]
The original commit was cherry-picked from the gcc6 branch then reverted on master and now re-applied with gcc6 branch merge.

**Comment by vcunat** [comment]
Sliding off-topic, but any commit can do anything.  They in fact specify only the new tree state and the parent commits.  You update fast-forward if (and only if) going backwards over these parent pointers.

**Comment by bendlas** [comment]
Oh, it seems I have run afoul of something called `History Simplification` in git. `git log --full-history -- pkgs/desktops/gnome-3/3.22/core/gjs/default.nix`. Shows the correct history. Sorry.

**Comment by vcunat** [comment]
Oh, right, the commit updating gjs was cherry-picked, i.e. existed in both branches (master and gcc6), and then we were hit by one of the rarer cases where 3-way merge "does the wrong thing" (in da9adb8fab40a3d) &ndash; the merge-base happens to be before the gjs updates (and revert), on gcc6 branch it was updated and on master it is *the same as in merge-base* (because updated and reverted), therefore it's conflict-less resolved to the updated version.  All descendants of that merge then inherited this, of course.
