### ISSUE TITLE
Update request: fahclient 8.3.1 → 8.3.3

### ISSUE THREAD

**Issue by 9p4** [NixOS/nixpkgs#286705]
- Package name: fahclient
- Latest released version: 8.3.3

- Current version on the unstable channel: 8.3.1
- Current version on the stable/release channel: 7.6.21

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@zimbatm 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbsds** [comment]
done in https://github.com/NixOS/nixpkgs/pull/295745
