### ISSUE TITLE
Build failure: `haskell-language-server` with GHC 9.6.4

### ISSUE THREAD

**Issue by thomasjm** [NixOS/nixpkgs#286893]
### Steps To Reproduce

1. build `haskell-language-server.override { supportedGhcVersions = ["964"]; }`

### Build log

https://gist.github.com/thomasjm/935a80ee52744222b33c51cb84aad26b

### Notify maintainers

@maralorn
@NixOS/haskell  

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
This should be fixed with https://github.com/NixOS/nixpkgs/pull/279413

**Comment by thomasjm** [comment]
It works now, closing
