### ISSUE TITLE
nix-shell regression: shells other than bash do not get the correct $PATH when --pure flag is used

### ISSUE THREAD

**Issue by rayanamal** [NixOS/nixpkgs#286976]
### Describe the bug
In nix-shell scripts, shells except bash do not inherit the correct $PATH when --pure flag is used. This was not the case in the past, at least - as far as I can remember - on NixOS 23.05.

### Steps To Reproduce
1. Extract and execute the files I uploaded [archive.zip](https://github.com/NixOS/nixpkgs/files/14193342/archive.zip)
. Only `with-bash.sh` works. Others
   - Fail to print the same $PATH as bash, and
   - Do not recognize the packages `git` and `make` which were given to the nix-shell script, as a consequence of the former point.  

### Expected behavior
No errors printed, all scripts successfully execute the commands `git` and `make`. 
Specifically in this script, the repository is cloned and built, the binaries `dtlp` and `etlp` are produced in the directory `timelock`. 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 23.11 (Tapir), 23.11.3805.53fbe41cf76b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aerbil313** [comment]
Also, if `nix-shell` is going to be deprecated in favor of `nix develop`, I'll be glad if someone can tell me what is the alternative for nix-shell scripts is in the landscape of new nix commands (just using flakes?).

**Comment by rayanamal** [comment]
A workaround is to run nix-shell scripts with bash as interpreter and then in that script, give $PATH as an argument to e.g. fish, then convert that to $PATH format of fish and set it as PATH variable.

**Comment by rayanamal** [comment]
Yep, noticed now.
