### ISSUE TITLE
`image.repart` is not reproducible

### ISSUE THREAD

**Issue by msanft** [NixOS/nixpkgs#286969]
### Describe the bug
When building images with the `image.repart` builder, `systemd-repart` is being [invoked](https://github.com/NixOS/nixpkgs/blob/5ef42fcd84b2baa16f43554f1c1f1d614e23ef9a/nixos/modules/image/repart-image.nix#L90) in it's own namespace (through `unshare`) and while being in a `fakeroot`. While I'm not too familiar with both of the tools, this somehow, presumably by `unshare`, causes `systemd-repart` to not being supplied with the environment variables from the `stdenv` the rest of the package is built in, specifically [`SOURCE_DATE_EPOCH`](https://github.com/NixOS/nixpkgs/blob/30a56f974ccb04305a54358f05731e22e3bc3758/pkgs/stdenv/generic/setup.sh#L393) and [`TZ`](https://github.com/NixOS/nixpkgs/blob/30a56f974ccb04305a54358f05731e22e3bc3758/pkgs/stdenv/generic/setup.sh#L763), which cause the built image to not be reproducible, as timestamps are included.

### Steps To Reproduce
1. Build the same derivation using `image.repart` on 2 separate machines, ideally with different timezones.
2. Compare them with `vbindiff` or other tooling, and notice that timestamps (e.g. in `squashfs` filesystems) differ.

### Expected behavior
The environment being passed over to `systemd-repart`.

### Additional context
The specific reproducibility issue I ran into is solved by invoking `systemd-repart` as follows, but I think the more correct fix would be passing the whole environment over. If trying to do so by passing the whole outer `env`, this causes errors, presumably caused by the Nix store paths being unable to resolve in the new environment.

My dirty fix:
```diff
--- nixos/modules/image/repart-image.nix        2024-02-07 12:18:38.222260926 +0100
+++ nixos/modules/image/repart-image-fix.nix    2024-02-07 12:18:24.862099182 +0100
@@ -87,7 +87,7 @@
   cd $out
 
   echo "Building image with systemd-repart..."
-  unshare --map-root-user fakeroot systemd-repart \
+  unshare --map-root-user fakeroot env SOURCE_DATE_EPOCH=0 TZ=UTC systemd-repart \
     --dry-run=no \
     --empty=create \
     --size=auto \
```

I would like to create a proper fix for this, but I'm unsure about how we would want to pass the right bits of the environment here exactly.

### Notify maintainers
@nikstur 
@jmbaur 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3, NixOS, 24.05 (Uakari), 24.05.20240205.4b1aab2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by msanft** [comment]
[#263898](https://github.com/NixOS/nixpkgs/issues/263898) might be related to the same underlying issue, too.

**Comment by nikstur** [comment]
You mean `systemd-repart` instead of `systemd-dissect`, right?

**Comment by msanft** [comment]
> You mean `systemd-repart` instead of `systemd-dissect`, right?

Oops. Sorry. Seems I got a little too involved with both of the tools when writing this. Corrected.

**Comment by nikstur** [comment]
When I run `nix-build --check` on a derivation that produces an image with your patch, It's still not reproducible. It'd be worthwhile to investigate this further but I don't currently have the time to do it.

**Comment by nikstur** [comment]
@msanft I changed the title to reflect the general issue and not only (a possibly partial) solution.

**Comment by msanft** [comment]
> When I run `nix-build --check` on a derivation that produces an image with your patch, It's still not reproducible. It'd be worthwhile to investigate this further but I don't currently have the time to do it.

Hmm. Could you send me a reproducer for this? For my specific image (which I unfortunately cannot share here yet), the patch enabled reproducibility across my testing machines. I'd be happy to investigate further on this.

> @msanft I changed the title to reflect the general issue and not only (a possibly partial) solution.

I'm not sure about this. IMO, the environment not reaching `systemd-repart` is definitely an issue and should be fixed. There may be other issues making it's output irreproducible, but these then could be tracked in other GH issues IMO. I don't have a strong opinion about this though, just wanted to clarify why I picked this title in the first place.

**Comment by msanft** [comment]
>  It's still not reproducible

It may be due to VFAT timestamps. I'm currently working on a fix, which is pretty easy.

**Comment by msanft** [comment]
Did anyone manage to try this in combination with the workaround in #287237?

**Comment by msanft** [comment]
The `env` seems to be passed down correctly due to some other change (i was not able to exactly pin it down to the fix yet)

However, the way it's used in the test, the image is not reproducible due to the mentioned issue. Currently trying to get this fixed in systemd.

**Comment by nikstur** [comment]
I think we can leave this open until we have resolved it (even if it depends on upstream issues). Thank you for looking into it further!

**Comment by MatthewCroughan** [comment]
Same as https://github.com/NixOS/nixpkgs/issues/311978

**Comment by danielbarter** [comment]
@MatthewCroughan : the issues are related but not exactly the same. https://github.com/NixOS/nixpkgs/issues/311978 happens because user namespaces don't work inside qemu, which is definitely an upstream bug.

**Comment by nikstur** [comment]
I think this is solved now since we have system v256

**Comment by msanft** [comment]
This particular issue should be fixed, as you said. I think there still are other reproducibility issues, but they affect only specific filesystems, and thus are unrelated to this issue. Going to close this one. Thanks for your help people!
