### ISSUE TITLE
`pkgs.substitutes` does not allow replacing strings that contains spaces

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nixpkgs#286961]
### Describe the bug
Using `--replace-*` with `pkgs.substitutes`, currently does not allow me to replace a string that contains spaces.

### Steps To Reproduce
1. Build the code below:
  ```nix
  {
    fetchpatch,
    substitute,
  }:
  substitute {
    src = fetchpatch {
      url = "https://github.com/swaywm/sway/commit/2f304ef0532a45d00b2ec2c7fc63adef0aec7607.patch";
      hash = "sha256-nd+Z6A7GE5Go7QxXOI+hiLWQiXegsQatcNfxEsXgamI=";
    };
    replacements = [
      "--replace-warn"
      "int surface_x, surface_y, surface_width, surface_height;"
      "int surface_x, surface_y, surface_width, surface_height = 0;"
    ];
  }
  ```
  It gives the following error:
  ```
  substituteStream(): ERROR: Invalid command line argument: surface_y,
  ```
  
  I tried quoting it, escaping the spaces... but none of them seemed to work.

### Expected behavior
The `--replace-warn` I did succeeds.

### Additional context

I posted this in the NixOS matrix room a while ago (but I forgot to submit an issue):
https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$Vb2zuea0fQmfddXOF3dDotiOypfrCYjruYEmpnYTzkk?via=nixos.org&via=matrix.org&via=tchncs.de

People showed me some bash magic I couldn't understand, I think they might be helpful and worth checking out.

### Notify maintainers

@virusdave (git blame)

cc @ElvishJerricco @jtojnar (people in the original conversation)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3-zen1, NixOS, 24.05 (Uakari), 24.05.20240205.faf912b`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

(I'm sorry if I described anything incorrectly, I'm a not a native English speaker and I am still trying to improve my language skills)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/pull/287364, please give it a try :)
