### ISSUE TITLE
Update request: shotcut 24.01.13 → 24.01.28

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#287017]
- Package name: shotcut
- Latest released version: 24.01.28
- Current version on the unstable channel: 24.01.13
- Current version on the stable/release channel: 21.09.20
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@cillianderoiste
@woffs
@peti

Changelog: https://github.com/mltframework/shotcut/releases/tag/v24.01.28

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by woffs** [comment]
shotcut is at 24.02.19 in nixpkgs meanwhile.
