### ISSUE TITLE
Update request: envoy 1.27.2 → 1.29.0

### ISSUE THREAD

**Issue by 3u13r** [NixOS/nixpkgs#287027]
- Package name: envoy
- Latest released version: v1.29.0

- Current version on the unstable channel: v1.27.2
- Current version on the stable/release channel: v1.27.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@lukegb 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lukegb** [comment]
We're going to have to bump to 1.29.x before 24.04 drops, because otherwise we'll go EOL during the release cycle.

**Comment by adamcstephens** [comment]
Sounds good. Consul 1.18 supports 1.28.x and hopefully will add 1.29.x soon. Ping me on the PR and I’ll do some testing.
