### ISSUE TITLE
Documentation: Qt callPackage approach incompatible with pkgs/by-name

### ISSUE THREAD

**Issue by Aleksanaa** [NixOS/nixpkgs#287015]
## Problem

Our Qt section says:

https://github.com/NixOS/nixpkgs/blob/405d3ba628b96e8b29fb0c4350a7fe3e5765006f/doc/languages-frameworks/qt.section.md?plain=1#L25-L30

But this is [not compatible with](https://github.com/NixOS/nixpkgs/tree/nixos-unstable/pkgs/by-name#limitations) the new `by-name` directory structure.

## Proposal

There are already plenty of packages in `pkgs/by-name` invoking qt5 or qt6 directly. And if the structure of both sets remain the same, maybe we can use `callPackage ./../.. { qt6 = qt5; }` or something?

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
We should probably update the docs, because at this point both `qt5` and `qt6` contain exactly one version and should continue being that way.
