### ISSUE TITLE
Build failure: python312Packages.mypy (possible bug in the python testing infra)

### ISSUE THREAD

**Issue by bryango** [NixOS/nixpkgs#287179]
### Steps To Reproduce

mypy has a test failure in python 3.12 which leads to failing builds: https://hydra.nixos.org/job/nixpkgs/trunk/python312Packages.mypy.x86_64-linux. The issue is caused by `distutils` being removed from the standard library of python 3.12, resulting in an error:
```console
Traceback (most recent call last):
  File "/build/source/mypyc/lib-rt/setup.py", line 9, in <module>
    from distutils.core import Extension, setup
ModuleNotFoundError: No module named 'distutils'
```
The full log: https://hydra.nixos.org/build/248174465/nixlog/1. This can be resolved by adding `setuptools` as a dependency, which provides a seamless compatibility layer for `distutils`. This is [already addressed upstream](https://github.com/python/mypy/issues/16889). However, something is amiss here: we also already have `setuptools` in `checkInputs`:

https://github.com/NixOS/nixpkgs/blob/7d8e75c8bba9d70246a2ac7ba1d478875335e6e8/pkgs/development/python-modules/mypy/default.nix#L91-L101

But somehow it is not detected by the failing test (`mypyc/test/test_external.py`, which in turn calls `mypyc/lib-rt/setup.py`). This is rather mysterious to me, and I couldn't figure out why... I also tried putting `setuptools` in `nativeCheckInputs` and that also does not work.

### Build log

The full log: https://hydra.nixos.org/build/248174465/nixlog/1.

### Additional context

N/A

### Notify maintainers

@martingms @lnl7

Also @mweinelt if you are interested!

### Metadata

Hydra: https://hydra.nixos.org/job/nixpkgs/trunk/
My personal testing environment:

```console
$ nix run nixpkgs#nix-info -- -m                                               
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8-2-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/home/bryan/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bryango** [comment]
The symptoms are cured in 820b56f17d5d9ce8e5ba0660525ac844e82fe167 but the puzzle remains, so I am keeping this open for now.

**Comment by natsukium** [comment]
Thanks for your report.
It should be built and work fine since it has been updated.
