### ISSUE TITLE
Package request: rose-pine-cursor

### ISSUE THREAD

**Issue by OakleyCord** [NixOS/nixpkgs#287123]
**Project description**
"Soho vibes for Cursors"

Rose Pine themed cursors, recently was created (last month) 

**Metadata**

* homepage URL: https://rosepinetheme.com/
* source URL: https://github.com/rose-pine/cursor
* license: gpl3

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aikooo7** [comment]
I will try to do this as soon as I can
