### ISSUE TITLE
ipfs mount fails when using ipfs service 

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#28725]
## Issue description
when i try addding the option --mount or calling ipfs mount on my ipfs service. I get the following error
```
Aug 29 22:31:00 marvin ipfs[15896]: 22:31:00.260 ERROR       node: error mounting: fusermount: exec: "fusermount": executable file not found in $PATH mount_unix.go:97
Aug 29 22:31:00 marvin ipfs[15896]: 22:31:00.260 ERROR       node: error mounting: fusermount: exec: "fusermount": executable file not found in $PATH mount_unix.go:101
```
I think it is just the matter of adding fuse package to the path.

### Steps to reproduce
pass ipfs mount over cli with the service as the config or add the extraFlags "--mount"

## Technical details
```
#  nixos-version ; nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion ; grep build-use-sandbox /etc/nix/nix.conf 
17.03.1769.da2159dafb (Gorilla)
"17.03.1769.da2159dafb"
build-use-sandbox = false
```

**Comment by mogorman** [comment]
this command does work when I was just using ipfs as my user and not the service defined ipfs

**Comment by mogorman** [comment]
```
  systemd.services.ipfs.path =  lib.mkForce [ pkgs.ipfs pkgs.fuse ];
```
gets past that but gets caught 
```
Aug 30 00:11:15 marvin ipfs[14089]: Error: fuse failed to access mountpoint /var/lib/ipfs/ipfs
Aug 30 00:11:15 marvin ipfs[14089]: 00:11:15.117 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:101
Aug 30 00:11:15 marvin ipfs[14089]: 00:11:15.117 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:97

```

i did create that directory and chmoded it for ipfs

**Comment by mguentner** [comment]
Duplicate of #28621 

We still don't know why this fails within the systemd unit but apparently not from a login shell.

**Comment by prusnak** [comment]
@mogorman can you please confirm this is still the issue with the newest ipfs from the nixpkgs master?

**Comment by Luflosi** [comment]
Closing, as setting `services.ipfs.autoMount` to true works.
