### ISSUE TITLE
Gnome Window Maximize and Tile Broken

### ISSUE THREAD

**Issue by blitz** [NixOS/nixpkgs#287206]
### Describe the bug

Gnome has the functionality to move windows to the top to maximize or move to the side of the screen to vertically tile. This doesn't work for me anymore on one laptop.

The strange thing is: I have two laptops with pretty much the same NixOS configuration. On my Tuxedo laptop everything works, on my Framework 13" AMD laptop it's broken.

Notable differences between the laptops are:

- Tuxedo: Intel CPU, Intel GPU, 1920x1080  16:9 display
- Framework, AMD CPU, AMD GPU, 2256x1504 3:2 display

Changing the display resolution on the Framework didn't help, though.

### Steps To Reproduce

1. Drag a window to the top of the screen.

### Expected behavior

The window maximizes and tiles. See: https://help.gnome.org/users/gnome-help/stable/shell-windows-maximize.html.hi

### Screenshots

[Screencast from 2024-02-07 08-49-56.webm](https://github.com/NixOS/nixpkgs/assets/37907/5dae531a-7c2d-4f8e-9572-880c7a9ace37)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.15, NixOS, 23.11 (Tapir), 23.11.20240201.25e3d4c`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by urbas** [comment]
I believe this is a setting and it might have been switched off by default. You can find it in `Settings -> Multitasking -> Active Screen Edges` and turn it on. Here's a screenshot:
![Screenshot from 2024-02-08 19-32-09](https://github.com/NixOS/nixpkgs/assets/771193/9fd2d6e7-2c36-43b1-8be7-22767efa7576)

**Comment by blitz** [comment]
Thanks @urbas, will try that later and report back. It would explain why it doesn't work on my new laptop. How surprising, though.

**Comment by blitz** [comment]
Indeed "Active Screen Edges" is turned off by default. Thanks again! :heart:
