### ISSUE TITLE
Update request: gst_all_1.gstreamer: 1.22.8  → 1.24.2

### ISSUE THREAD

**Issue by RSWilli** [NixOS/nixpkgs#287253]
- Package name: gst_all_1.gstreamer
- Latest released version: 1.22.9 (https://gstreamer.freedesktop.org/releases/1.22/#1.22.10)

- Current version on the unstable channel: 1.22.8
- Current version on the stable/release channel: 1.22.8

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@lilyinstarlight 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RSWilli** [comment]
1.22.10 was released yesterday, edited title and links

**Comment by RSWilli** [comment]
gstreamer 1.24.0 was released: https://gstreamer.freedesktop.org/releases/1.24/

**Comment by lilyinstarlight** [comment]
I plan to get to it by the weekend and will post it as a blocker for 24.05

**Comment by RSWilli** [comment]
this can be closed because it is done.
