### ISSUE TITLE
Package request: GStreamer 1.23.X unstable development release

### ISSUE THREAD

**Issue by RSWilli** [NixOS/nixpkgs#287252]
**Project description**

Gstreamer released 1.23.1 as an unstable development release before 1.24 gets released

Gstreamer 1.22.X is already packaged https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/gstreamer/core/default.nix#L115 but the unstable version would be nice if it were included in nixpkgs

**Metadata**
(same as current gstreamer)

* homepage URL: https://gstreamer.freedesktop.org/

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RSWilli** [comment]
@lilyinstarlight tagging you since you are maintaining the stable version. Do you think this is something worth adding to nixpkgs?

**Comment by surfaceflinger** [comment]
Not sure how GStreamer release cycle looks but 1.23.1 now supports AV1 encoding through VAAPI which would be useful for obs-studio and obs-studio-plugins.obs-vaapi

**Comment by RSWilli** [comment]
1.23.X is only marked as unstable because they are preparing the 1.24 release in a couple of days/weeks. For testing purposes though (and for the development of my bindings in go https://github.com/go-gst/go-gst) the 1.23.X would be useful though.

Maybe one could use an overlay to do it themselves? (I am pretty new to nix, I didn't use overlays yet)

**Comment by surfaceflinger** [comment]
For you, the best solution would be to create flake.nix in rootdir of go-gst for packaging the project itself, then outputing two packages - go-gst with regular, nixpkgs upstream gstreamer and another package that has gst with overriden version+src in buildInputs

*but thats offtopic*

regarding OBS, I'll experiment when I'll have some free time and just paste here a drop-in overlay for obs-vaapi but no guarantees here

**Comment by RSWilli** [comment]
since gstreamer 1.24.0 was released, this issue is obsolescent. I'm adding the update request for the stable update to https://github.com/NixOS/nixpkgs/issues/287253
