### ISSUE TITLE
Update request: libremidi 4.2.4 → 4.4.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#287254]
- Package name: libremidi
- Latest released version: 4.4.0
- Current version on the unstable channel: 4.2.4
- Current version on the stable/release channel: 3.0
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@paveloom

https://github.com/jcelerier/libremidi/releases/tag/v4.4.0

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paveloom** [comment]
I'm not a maintainer of this package anymore.

**Comment by luzpaz** [comment]
Thanks for the heads up. Then this package has no maintainer and should be reflected in search.nixos.org

**Comment by dotlambda** [comment]
> Then this package has no maintainer and should be reflected in search.nixos.org

It is: https://search.nixos.org/packages?channel=unstable&show=libremidi

**Comment by luzpaz** [comment]
@dotlambda Thanks. I was referring to: https://search.nixos.org/packages?channel=23.11&show=libremidi&from=0&size=50&sort=relevance&type=packages&query=libremidi

**Comment by luzpaz** [comment]
4.4.0 released  
https://github.com/jcelerier/libremidi/releases/tag/v4.4.0

**Comment by genevieve-me** [comment]
This package seems to be broken on latest nixos-unstable, and by extension breaks [Scene Switcher](https://github.com/NixOS/nixpkgs/blob/17479b5498b28b19edff14b482afe6faca636c89/pkgs/applications/video/obs-studio/plugins/advanced-scene-switcher/default.nix#L21), a fairly popular OBS plugin.

build log: [libremidi-failure.txt](https://github.com/NixOS/nixpkgs/files/14514730/libremidi-failure.txt)

I overrode the package to 4.4.0 and it builds just fine.

4.5.0 has been released, but it looks like it depends on this unpackaged dependency: https://github.com/cameron314/readerwriterqueue

**Comment by wegank** [comment]
Closed by #287309.
