### ISSUE TITLE
Support progress reporting in default stdenv builder

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#28720]
As of Nix 1.12, we have preliminary progress reporting support. It would be great to experiment with sandwiching that into our default `stdenv` builder (the one that calls `configure/make/make install`). This would cause a mass rebuild but would be a good step towards reducing build noise and improving user friendliness.

We'll obviously want to do this for all sorts of language-specific builders too, but for now I'd start with the basic one.

cc @edolstra

**Comment by davidak** [comment]
i think this would still be good

**Comment by davidak** [comment]
...

**Comment by Artturin** [comment]
0061fae2
