### ISSUE TITLE
Missing (oreo-cursors-plus) package that shows on nixpkgs search.

### ISSUE THREAD

**Issue by ArkieSoft** [NixOS/nixpkgs#287388]
### Describe the bug

oreo-cursors-plus returns a search result on the nixpkgs search site "https://search.nixos.org/packages#". However, it doesn't return as a valid package option.

### Steps To Reproduce
1. Search https://search.nixos.org/packages# for "oreo-cursors-plus", to return a result.
2. Follow directions on NixOS configuration or on nix-env.

### Expected behavior
It should simply install, but it returns errors showing it does not exist as a derivation or package.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.74, NixOS, 23.11 (Tapir), 23.11.3496.a77ab169a83a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`




```

![2024-02-08-215626_hyprshot](https://github.com/NixOS/nixpkgs/assets/140302424/18c5c18a-c58d-46bc-b1ab-9ac9f08ec6f7)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
Could you try `assetfinder` and `powersupply`? They are added at the same time.

**Comment by dotlambda** [comment]
From the man page
```
•  --installed
   The query operates on the store paths that are installed in the current generation of the active profile. This is the default.
```
This is the correct command:
```
$ nix-env --query --available oreo-cursors-plus
error: selector 'oreo-cursors-plus' matches no derivations, maybe you meant:
       oreo-cursors-plus-unstable
```
```

**Comment by ArkieSoft** [comment]
<img width="521" alt="Screenshot 2024-02-09 at 1 49 28 PM" src="https://github.com/NixOS/nixpkgs/assets/140302424/bb788d26-1020-4bf8-9dbb-3541fadc4ea5">

Noted @dotlambda . Thank you for the syntax correction. However, this didn't change the end result, and didn't fix the core issue. Per @Aleksanaa 's request, I did check for assetfinder and powersupply to find both perfectly fine. Along with that, as a sanity check, neovim was found easily. I even copied the text 'oreo-cursors-plus-unstable' direcly from @dotlambda 's quote with no change just in case it was a typo on my end. Curiously, searching for 'oreo-cursors-plus' didn't return a suggestion like it did with your example, @dotlambda.

**Comment by dotlambda** [comment]
You might have to do `sudo nix-channel --update`.
