### ISSUE TITLE
Package request: instructor

### ISSUE THREAD

**Issue by Pablo1107** [NixOS/nixpkgs#287321]
**Project description**

Structured outputs powered by llms. Designed for simplicity, transparency, and control.

This package is needed to update [shell_gpt](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/llm/shell_gpt/default.nix). 

**Metadata**

* homepage URL: https://jxnl.github.io/instructor/
* source URL: https://github.com/jxnl/instructor https://pypi.org/project/instructor/
* license: MIT

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Pablo1107** [comment]
@MGlolenstine

**Comment by brokenpip3** [comment]
https://github.com/NixOS/nixpkgs/pull/296104
