### ISSUE TITLE
Can a binary that link to hard-code path libraries be wrap/patch to make it able to run?

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28745]
I try to run StarcraftII [headless client](https://github.com/Blizzard/s2client-proto/blob/master/README.md#linux-packages) and get following error,

    $ file SC2_x64 
    SC2_x64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cb1cea9acb95b0c53e7a3cf18181fe5f7ff0e735, stripped

    $ ldd SC2_x64 
    /run/current-system/sw/bin/ldd: line 117: ./SC2_x64: No such file or directory

    $ ./SC2_x64 
    bash: ./SC2_x64: No such file or directory

I am able to run it in `ubuntu` docker and get the `ldd` output

    # ldd /StarCraftII/Versions/Base55958/SC2_x64 
    linux-vdso.so.1 =>  (0x00007ffc15d83000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fda84831000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fda84614000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fda84292000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fda83f89000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fda83d73000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fda839a9000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fda84a35000)

I think the problem is cause by some `hard-code` libraries path.

    /lib64/ld-linux-x86-64.so.2 (0x00007fda84a35000)

Is there any not-so-hard way to fix this by warp or patch the binary?

---

I try override `LD_LIBRARY_PATH` and still failed.

    $ ldd `which sh`
        linux-vdso.so.1 (0x00007fff9af4b000)
        libreadline.so.7 => /nix/store/6njwnjnfb3kfpms38c28asb523zg9d63-readline-7.0p0/lib/libreadline.so.7 (0x00007f397f162000)
        libhistory.so.7 => /nix/store/6njwnjnfb3kfpms38c28asb523zg9d63-readline-7.0p0/lib/libhistory.so.7 (0x00007f397ef58000)
        libncursesw.so.6 => /nix/store/dxdapmpfvk4hz03rqy11szlizygjh1fp-ncurses-6.0/lib/libncursesw.so.6 (0x00007f397eced000)
        libdl.so.2 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libdl.so.2 (0x00007f397eae9000)
        libc.so.6 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libc.so.6 (0x00007f397e74c000)
        /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/ld-linux-x86-64.so.2 (0x00007f397f3ae000)

    $ LD_LIBRARY_PATH="/nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/" ./SC2_x64 
    bash: ./SC2_x64: No such file or directory

    $ LD_LIBRARY_PATH="/nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/" ldd ./SC2_x64 
    /run/current-system/sw/bin/ldd: line 117: ./SC2_x64: No such file or directory

**Comment by wizzup** [comment]
$ readelf -l SC2_x64 

    Elf file type is EXEC (Executable file)
    Entry point 0x5ed2b0
    There are 10 program headers, starting at offset 64

    Program Headers:
      Type           Offset             VirtAddr           PhysAddr
                    FileSiz            MemSiz              Flags  Align
      PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                    0x0000000000000230 0x0000000000000230  R E    0x8
      INTERP         0x0000000000000270 0x0000000000400270 0x0000000000400270
                    0x000000000000001c 0x000000000000001c  R      0x1
          [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
      LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                    0x0000000003490e90 0x0000000003490e90  R E    0x200000
      LOAD           0x0000000003491430 0x0000000003a91430 0x0000000003a91430
                    0x0000000000012d60 0x0000000003f44ef0  RW     0x200000
      DYNAMIC        0x0000000003496dd0 0x0000000003a96dd0 0x0000000003a96dd0
                    0x0000000000000220 0x0000000000000220  RW     0x8
      NOTE           0x000000000000028c 0x000000000040028c 0x000000000040028c
                    0x0000000000000044 0x0000000000000044  R      0x4
      TLS            0x0000000003491430 0x0000000003a91430 0x0000000003a91430
                    0x0000000000000005 0x00000000000021c0  R      0x10
      GNU_EH_FRAME   0x000000000297d8bc 0x0000000002d7d8bc 0x0000000002d7d8bc
                    0x0000000000157b0c 0x0000000000157b0c  R      0x4
      GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                    0x0000000000000000 0x0000000000000000  RW     0x10
      GNU_RELRO      0x0000000003491430 0x0000000003a91430 0x0000000003a91430
                    0x0000000000005bd0 0x0000000000005bd0  R      0x1

    Section to Segment mapping:
      Segment Sections...
      00     
      01     .interp 
      02     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .plt.got .text .fini .rodata .eh_frame_hdr .eh_frame .gcc_except_table 
      03     .tdata .init_array .fini_array .jcr .dynamic .got .got.plt .data .bss 
      04     .dynamic 
      05     .note.ABI-tag .note.gnu.build-id 
      06     .tdata .tbss 
      07     .eh_frame_hdr 
      08     
      09     .tdata .init_array .fini_array .jcr .dynamic .got

**Comment by lluchs** [comment]
You need to change the dynamic linker. Try `patchelf --interpreter <path to interpreter>` - [typically (from a nix derivation)](https://github.com/NixOS/nixpkgs/search?utf8=✓&q=patchelf+--interpreter&type=) `"$(cat $NIX_CC/nix-support/dynamic-linker)"`, but if you're doing things manually, you can just copy the interpreter from some other program.

**Comment by joachifm** [comment]
If patching is infeasible, the linker can be invoked directly, as in `ld-linux-x86-64.so.2 /path/to/program ...`. Run the linker without arguments to see some help output.

**Comment by wizzup** [comment]
Almost there, `ld-linux-x86-64.so.2` seem promising but I have no idea about this `.build.info` file.

    $ ls -al
    total 107824
    drwxrwx--- 1 wizzup users      104 Aug 31 13:24 .
    drwxrwx--- 1 wizzup users       18 Aug  9 01:33 ..
    lrwxrwxrwx 1 wizzup users       79 Aug 31 13:05 ld-linux-x86-64.so.2 -> /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/ld-linux-x86-64.so.2
    lrwxrwxrwx 1 wizzup users       76 Aug 31 13:24 libstdc++.so.6 -> /nix/store/ncvznvhzbf226s5lqpv2a0345ba5f5hy-gcc-5.4.0-lib/lib/libstdc++.so.6
    -rwxrwx--x 1 wizzup users 55200536 Aug  9 01:34 SC2_x64
    -rwxr-x--x 1 wizzup users 55200536 Aug 31 12:53 SC2_x64.bak

    $ echo $LD_LIBRARY_PATH 
    /run/opengl-driver/lib:/run/opengl-driver-32/lib

    $ LD_LIBRARY_PATH=. ./ld-linux-x86-64.so.2 ./SC2_x64
    Version: B55958 (SC2.3.16)
    Build: Jul 31 2017 13:19:41
    Command Line: '"./ld-linux-x86-64.so.2" ./SC2_x64'
    Starting up...
    Startup Phase 1 complete
    Fatal Error:
    Failed to find .build.info file at path: /nix/store/.build.info
    Terminating...
    Terminated

I randomly pick `ld-linux-x86-64.so.2 ` and `libstdc++.so.6` from `find /nix/store | grep`.

What should be a correct way to get to active libraries path from nix expression?

I think I should start `nix-shell` with correct `LD_LIBRARY_PATH` but have no idea how to write the `shell.nix`.

---

Haven't try `patchelf` for the same reason.

**Comment by wizzup** [comment]
More research lead to this [guild](https://nixos.org/patchelf.html) on nixos.org.

I want to try patch `interpreter` and `rpath` but the problem remain, **which value to use?**.

**Comment by bjornfor** [comment]
> I want to try patching interpreter and rpath but the problem remain, which value to use?.

See comment above: https://github.com/NixOS/nixpkgs/issues/28745#issuecomment-326029479

For rpath, use ```patchelf --set-rpath ${stdenv.lib.makeLibraryPath [ lib1 lib2 ... ]}```.

For inspiration, grep for "patchelf" in nixpkgs.

**Comment by wizzup** [comment]
I think I solved the problem by using the same libraries from the [starcraft 2 client api](https://github.com/Blizzard/s2client-api) which configured by cmake.

    $ ldd ./all_tests 
        linux-vdso.so.1 (0x00007ffd2ef7e000)
        libpthread.so.0 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libpthread.so.0 (0x00007fe4f24f7000)
        libdl.so.2 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libdl.so.2 (0x00007fe4f22f3000)
        libstdc++.so.6 => /nix/store/vzbrk9ic04h3243rk8ymckb611pkjkkd-gcc-5.4.0-lib/lib/libstdc++.so.6 (0x00007fe4f1f7b000)
        libm.so.6 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libm.so.6 (0x00007fe4f1c69000)
        libgcc_s.so.1 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libgcc_s.so.1 (0x00007fe4f1a53000)
        libc.so.6 => /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libc.so.6 (0x00007fe4f16b6000)
        /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/ld-linux-x86-64.so.2 (0x00007fe4f2715000)

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/30481 Starcraft II headless is now in nixpkgs
