### ISSUE TITLE
Swayosd service file and dbus is broken

### ISSUE THREAD

**Issue by Guibi1** [NixOS/nixpkgs#287578]
### Describe the bug

I set `services.swayosd.enable = true;` on home manager and the service doesn't work.

### Steps To Reproduce

1. Enable `services.swayosd.enable = true;` in the Home Manager config.
2. Run `systemctl --user start swayosd.service` or reboot.
3. The service doesn't work (see logs).

### Expected behavior

The service should start `swayosd-libinput-backend` and `swayosd-server`.

### Screenshots
Here is the current service file and the binaries installed but `pkgs.swayosd`:

```console
❯ cat /home/guibi/.config/systemd/user/swayosd.service
[Install]
WantedBy=graphical-session.target

[Service]
ExecStart=/nix/store/pfd2gmchr0986xkhj9ayf5hqfxw9gm07-swayosd-unstable-2023-09-26/bin/swayosd
Restart=always
Type=simple

[Unit]
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY
Description=Volume/backlight OSD indicator
Documentation=man:swayosd(1)
PartOf=graphical-session.target
❯ ls /nix/store/pfd2gmchr0986xkhj9ayf5hqfxw9gm07-swayosd-unstable-2023-09-26/bin
swayosd-client  swayosd-libinput-backend  swayosd-server
```

### Additional context

I run Hyprland on NixOS with Home Manager.

### Notify maintainers

@Aleksanaa @barab-i 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 24.05 (Uakari), 24.05pre571036.9b19f5e77dd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
> see logs

I don't see any.



> I set `services.swayosd.enable = true;` on home manager and the service doesn't work.

So this is a home-manager problem and not a Nixpkgs one. If it actually is the latter, then please reproduce without home-manager.
