### ISSUE TITLE
Documentation: ACME (lego) IPv6 is mandatory

### ISSUE THREAD

**Issue by Mimoza** [NixOS/nixpkgs#287606]
## Problem

Hosting your server with a domain name is not possible if you don't have IPv6.
LEGO verification is only possible using this protocol.
I've checked manually in IPv4, everything's ok. But when I run the certificate creation service, I get :

```
warning: the following units failed: acme-domaine.tld.service
× acme-domaine.tld.service - Renew ACME certificate for domaine.tld
     Loaded: loaded (/etc/systemd/system/acme-domaine.tld.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-02-09 23:41:28 CET; 252ms ago
TriggeredBy: ● acme-domaine.tld.timer
    Process: 11635 ExecStart=/nix/store/x7pyqbib76rbwnq6n6m4v2c76ydxv0hs-unit-script-acme-domaine.tld-start/bin/acme-domaine.tld-start (code=exited, status=10)
   Main PID: 11635 (code=exited, status=10)
         IP: 17.1K in, 8.2K out
        CPU: 204ms

févr. 09 23:41:28 Totoro acme-domaine.tld-start[11660]: 2024/02/09 23:41:28 Could not obtain certificates:
févr. 09 23:41:28 Totoro acme-domaine.tld-start[11660]:         error: one or more domains had a problem:
févr. 09 23:41:28 Totoro acme-domaine.tld-start[11660]: [domaine.tld] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 88.164.139.149: Fetching http://domaine.tld/.well-known/acme-challenge/N5DbvN6i5PIT-bzMk9gtObhe5MSd10uiKWUajvcUFb4: Timeout during connect (likely firewall problem)
févr. 09 23:41:28 Totoro acme-domaine.tld-start[11635]: + echo Failed to fetch certificates. This may mean your DNS records are set up incorrectly. Selfsigned certs are in place and dependant services will still start.
févr. 09 23:41:28 Totoro acme-domaine.tld-start[11635]: Failed to fetch certificates. This may mean your DNS records are set up incorrectly. Selfsigned certs are in place and dependant services will still start.
févr. 09 23:41:28 Totoro acme-domaine.tld-start[11635]: + exit 10
févr. 09 23:41:28 Totoro systemd[1]: acme-domaine.tld.service: Main process exited, code=exited, status=10/n/a
févr. 09 23:41:28 Totoro systemd[1]: acme-domaine.tld.service: Failed with result 'exit-code'.
févr. 09 23:41:28 Totoro systemd[1]: Failed to start Renew ACME certificate for domaine.tld.
févr. 09 23:41:28 Totoro systemd[1]: acme-domaine.tld.service: Consumed 204ms CPU time, received 17.0K IP traffic, sent 8.2K IP traffic.
```

On the DNS side, I tried to fill in only an "A" record, without success. A "AAAA" record is mandatory.
This can be problematic with a home connection, as not all ISPs yet provide IPv6.

## Proposal

Adding in [Prerequist paragraphe](https://nixos.org/manual/nixos/stable/#module-security-acme-prerequisites) a warning about this point.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nmxcgeo** [comment]
Regarding 
> Hosting your server with a domain name is not possible if you don't have IPv6. LEGO verification is only possible using this protocol. 

and 
> On the DNS side, I tried to fill in only an "A" record, without success. A "AAAA" record is mandatory.

I think the Let's Encrypt documentation states the opposite: https://letsencrypt.org/docs/ipv6-support/
Furthermore, I have a NixOS server that has only an IPv4 address and an A record and it retrieves its certificate flawlessly.

**Comment by Mimoza** [comment]
I can't rule out having made a wrong configuration. As soon as I have a bit of time, I'll do some more tests.

**Comment by SuperSandro2000** [comment]
Lego does not require IPv6 but if your domain has an AAAA record, it is probably being checked.

**Comment by infinisil** [comment]
I've had the same issue and can confirm that adding an AAAA record works.
