### ISSUE TITLE
whois doesn’t work

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#28787]
## Issue description

In a terminal, `whois nixos.org` returns:

```
getaddrinfo: Servname not supported for ai_socktype
```

### Steps to reproduce

1. Run `nix-shell -p inetutils --run 'whois nixos.org'`.

## Technical details

* System: 17.03.1700.51a83266d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1700.51a83266d1"
* Sandboxing enabled: yes

**Comment by Mic92** [comment]
I fixed this some time ago in master. Now I have back ported it: 7da346a9f8dffb3b4a9c66deeee84028dd478457

**Comment by michalrus** [comment]
Awesome, thanks!

**Comment by HeinrichHartmann** [comment]
Looks like this issue re-surfaced, on latest nixos. I can reproduce it as follows:

```
; docker run -it --rm nixos/nix nix-shell '<nixpkgs>' -p inetutils --run 'whois nixos.org'
...
getaddrinfo: Servname not supported for ai_socktype
# FAILED(1) after 11.305s
```

Interestingly the same command works on my debian machine, even when using exactly the same nixpkgs release/checkout. My hunch is, that this has something todo with the missing /etc/services file.

Fetchmail was failing with a similar error, but worked after providing a port for pop3 access:
```
; fetchmail -f fetchmailrc.tmp
fetchmail: getaddrinfo("wp12252871.mail.server-he.de","pop3") error: Servname not supported for ai_socktype
fetchmail: Try adding the --service option (see also FAQ item R12).
```

**Comment by rnhmjoj** [comment]
I have the same issue. I think it must be configuration-dependent because in my case it works on some machine but not others, even if they're both running NixOS 23.05.

**Comment by lolbinarycat** [comment]
unable to reproduce via original instructions, not tested via docker.
