### ISSUE TITLE
Installing CoreCLR using script

### ISSUE THREAD

**Issue by razvan-flavius-panda** [NixOS/nixpkgs#28784]
I am trying to see if the official coreclr script will work on NixOS but it appears not to spot installed library dependencies during run:

```
./dotnet-install.sh --shared-runtime  --install-dir ~/cli

root@nixos:~/Downloads]# ./dotnet-install.sh
ldconfig: Can't open cache file /nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/etc/ld.so.cache
: No such file or directory
dotnet_install: Error: Unable to locate libunwind. Install libunwind to continue
ldconfig: Can't open cache file /nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/etc/ld.so.cache
: No such file or directory
dotnet_install: Error: Unable to locate libssl. Install libssl to continue
ldconfig: Can't open cache file /nix/store/kjwbqnh13dxh6w4pk2gb3ddmhpiaihqg-glibc-2.25/etc/ld.so.cache
: No such file or directory
dotnet_install: Error: Unable to locate libicu. Install libicu to continue
```

See dependencies here: https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
And script documentation: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

Tried to fix by installing following libraries, but getting same errors:
* nixos.libunwind
* nixos.libressl
* nixos.icu

I'm assuming that I am getting some wrong libraries or they are on the system but the script does not know where they are.

**Comment by copumpkin** [comment]
cc @obadz

**Comment by obadz** [comment]
I assume that's for downloading binaries. I'm mostly looking at building from source (cc #25498)
