### ISSUE TITLE
Update request: abuse 0.8 → 0.9.1

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#287934]
- Package name: abuse
- Latest released version: 0.9.1 (https://github.com/Xenoveritas/abuse)

- Current version on the unstable channel: 0.8
- Current version on the stable/release channel: 0.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** @iblech

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iblech** [comment]
Thank you for pinging me! I prepared a [draft commit](https://github.com/iblech/nixpkgs/pull/new/patch-abuse-0.9.1). But I cannot fully test it as I'm currently at a machine without sound. Can you test whether everything works as expected, including gfx effects and music? You can do so with the following incantation:

```nix-shell -I nixpkgs=https://github.com/iblech/nixpkgs/archive/patch-abuse-0.9.1.tar.gz -p abuse```

**Comment by wegank** [comment]
Yes, works great!
