### ISSUE TITLE
Build failure: nerdfonts

### ISSUE THREAD

**Issue by W-Y-R** [NixOS/nixpkgs#288074]
### Context

A long error occurs when using nixos-install with the whole nerdfonts package enabled, making it impossible to proceed. The installation works normally if the nerdfonts package is disabled. The error does not show up if nerdfonts is installed after the system boots for the first time.

### Build log

```
error: builder for /nix/store/1r14knch2zmryp42x5x8mbcfu7y8h6g8-nerdfonts-3.1.1.dru' failed with exit code 1: last 10 log lines:
> unpacking source archive /nix/store/gz5y80kau1k1s4h9ss j5nc0q0xd Ind97-Ioseuka TermSlab.tar.xz
> unpacking source archive /nix/store/u7yy1nbha4nm37s lucf3bpsaxqndy8x1-JetBrainsMono.tar.xz
> unpacking source archive /nix/store/ipd0sndpnfanrcr3zru27xyrufid8uiu-Lekton.tar.xz
> unpacking source archive /nix/store/jf90aa in59k7j7yxgss3 jjxlyybkins-LiberationMono.tar.xz
> unpacking source archive /nix/store/r3b0h614ma9b67mxhyf44 juxn4n3ph14-Lilex.tar.xz
> unpacking source archive /nix/store/r252j1kug2as141s 1931 j4 jzh065g lsf-MPlus.tar.xz
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
> do not know how to unpack source archive /nix/store/r252j1kugZas141s 1931 j4 jzh065g 1sf-MPlus.tar.xz
For full logs, run 'nix log /nix/store/lr14kmch2zaryp12x5x8mbcfu7y8h6g8-nerdfonts-3.1.1.dru'.
error: 1 dependencies of derivation/nix/store/3a7gf62xrqgn1z12pi j2w7ka?1sn2ua1-fc-00-nixos-cache.conf.dru' failed to build error: 1 dependencies of derivation/nix/store/aad2231n6g6uz9dra@h7y1s9b01m704b-xserver.conf.dru' failed to build error: 1 dependencies of derivation/nix/store/ynlg1bc3b9n0089113h792d710k0scag-fontconfig-conf.dru' failed to build error: 1 dependencies of derivation/nix/store/6m8831kg1kqq3ncsnh722qa902dzf0cn-xserver-wrapper.dru' failed to build error: 1 dependencies of derivation/nix/store/a5ujdf1179nb9jii5mzb7f21dn3izyci-fontconfig-etc.dru' failed to build
```

### Notify maintainers

@doronbehar 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Please specify a Nixpkgs commit hash on which the issue is reproducible with the command:

```
nix build -Lf. nerdfonts
```

The build didn't fail for me on b6d10991241f2163fee7e60883689fcadcbc7ffa .

**Comment by W-Y-R** [comment]
This error was reproducible only in the nixos minimal iso, so I'll update this right after I get the time to try it out.

**Comment by W-Y-R** [comment]
Ah, I almost forgot to mention, but I don't think the commit hash really matters here as I got this error multiple times in the past when reinstalling the system. However, I will do it it if you deem it necessary.

**Comment by eclairevoyant** [comment]
If you got the error in the past but not in the present, I'd presume that means it's currently fixed. That's why we're asking what nixkpgs revision it fails on, for context. Fixing an issue that we can't reproduce is between unlikely and impossible.

**Comment by W-Y-R** [comment]
I can confirm that the error persists on the latest commit hash, 941bed4. In all seriousness, however, I think that the error is really specific to my system.

Executing nix log in turn does nothing, so I doubt I could gather much information. If I had to guess, I'd say it's most probably caused by a memory issue with my computer.

That being the case, I'll close this issue.

**Comment by doronbehar** [comment]
Note also the comment at the `meta`:

```
    hydraPlatforms = []; # 'Output limit exceeded' on Hydra
```

You might have a `tmp` file system issue - see also:

https://github.com/NixOS/nix/issues/7154

**Comment by W-Y-R** [comment]
That's likely the problem, since the issue is only reproducible after I format my drive with tmpfs.
