### ISSUE TITLE
Update request: vikunja-api, vikunja-frontend 0.22.1 → 0.23.0

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#288043]
- Package name: vikunja-api vikunja-frontend
- Latest released version: v0.23.0

- Current version on the unstable channel: 0.22.1
- Current version on the stable/release channel: 0.20.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@leona

vinkunja-frontend and vikunja-api have been merged into one binary upstream. The current packages and module should be updated to reflect that change and consolidated into a single package. 

More information: https://vikunja.io/blog/2024/02/whats-new-in-vikunja-0.23.0/
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iimog** [comment]
The `vikunja` package in `nixpkgs` is at version 0.23.0, see https://github.com/NixOS/nixpkgs/pull/289961.
The separate packages `vikunja-api` and `vikunja-frontend` have been merged to a single package `vikunja`, reflecting upstream changes, see https://github.com/NixOS/nixpkgs/pull/289961/commits/6925ff914efeb0efcccef09a0785abf1769b701e and https://vikunja.io/blog/2024/02/whats-new-in-vikunja-0.23.0/#api-frontend-and-desktop-are-now-merged-in-one-repo.
