### ISSUE TITLE
Provide OVMF files for secure boot

### ISSUE THREAD

**Issue by AshleyYakeley** [NixOS/nixpkgs#288184]
Currently, neither `nixpkgs.OVMF.fd` nor `nixpkgs.OVMFFull.fd` provide OVMF code and var files that work with secure boot.

The Debian `ovmf` package provides files `OVMF_CODE_4M.secboot.fd` and `OVMF_VARS_4M.ms.fd` that work correctly, so I know they are buildable from TianoCore's source.

Pinging OVMF maintainers @adamcstephens and @RaitoBezarius.

**Comment by RaitoBezarius** [comment]
@AshleyYakeley I'm not sure what do you mean by files that work with Secure Boot, also I'm not sure why you removed completely the template for a bug report or feature request.

**Comment by adamcstephens** [comment]
Is this solved by https://github.com/NixOS/nixpkgs/pull/284874 ?

**Comment by AshleyYakeley** [comment]
@RaitoBezarius There is no template for feature requests. The closest is "Packaging requests" "For packages that are missing", but this is not a missing package. It's not a bug report either as there is no defect in existing code.

**Comment by AshleyYakeley** [comment]
@adamcstephens yes I believe it would be, I hadn't seen that...

**Comment by shlevy** [comment]
@AshleyYakeley That PR uses Debian’s script (and logic) to create the `*4M.ms.fd` files, I don’t remember now what the `.secboot` variants are but can probably add them if needed.

**Comment by AshleyYakeley** [comment]
@shlevy It's the same thing: in the Debian `ovmf` package, `OVMF_CODE_4M.ms.fd` is a symlink to `OVMF_CODE_4M.secboot.fd`.

**Comment by AshleyYakeley** [comment]
(In any case if they were different I would want the `ms` files...)

**Comment by AshleyYakeley** [comment]
Done with PR #284874.
