### ISSUE TITLE
Build failure: python311Packages.tpm2-pytss

### ISSUE THREAD

**Issue by 8bitbuddhist** [NixOS/nixpkgs#288108]
[python311-tpm2-pytss.log](https://github.com/NixOS/nixpkgs/files/14233527/python311-tpm2-pytss.log)
### Steps To Reproduce

1. Run `nixos-rebuild switch --flake .`
2. During build phase, python311Packages.tpm2-pytss 
[python311-tpm2-pytss.log](https://github.com/NixOS/nixpkgs/files/14233508/python311-tpm2-pytss.log)
fails with this error: `TypeError: type 'cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateNumbers' is not an acceptable base type`

### Build log

[https://gist.github.com/8bitbuddhist/4036c51560ca7822967ef8d0d6eb4762](https://gist.github.com/8bitbuddhist/4036c51560ca7822967ef8d0d6eb4762)

### Additional context

N/A

### Notify maintainers

@baloo 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.76, NixOS, 24.05 (Uakari), 24.05.20240205.faf912b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/287804
