### ISSUE TITLE
Evolution doesn’t see installed Aspell dictionaries

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#28815]
## Issue description

In the Evolution mail client, I can only see a “Hebrew” dictionary, while EN and DE are installed in the system.

Setting `ASPELL_CONF="dict-dir /run/current-system/sw/lib/aspell"` doesn’t help either.

### Steps to reproduce

1. Install the following packages: `gnome3.evolution`, `aspell`, `aspellDicts.en`, `aspellDicts.de`.
1. Open Evolution and go to Edit → Preferences → Editor → Spell checking.
1. There, you can only see Hebrew.

## Technical details

* System: 17.03.1700.51a83266d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1700.51a83266d1"
* Sandboxing enabled: yes

**Comment by deedrah** [comment]
The `ASPELL_CONF` variable is used only by `aspell` binary and not by `libaspell` library.
I'm using this [patch](https://github.com/deedrah/overlays/blob/master/mypkgs/aspell/dict-dir-from-nix-profiles.patch) and something like this in `configuration.nix`
```
system.replaceRuntimeDependencies = with pkgs; [
    { original = aspell;
      replacement = aspell.overrideAttrs (oldAttrs: rec {
         patchPhase = oldAttrs.patchPhase + ''
         patch -p1 < ${./dict-dir-from-nix-profiles.patch}
       '';
      });
   }
];
```

It its similar to how is setup the `ASPELL_CONF` in Nix now, but works even for `libaspell`.

I cloud make pull request if anyone likes this.

**Comment by michalrus** [comment]
♥ Awesome! Please, do!

**Comment by deedrah** [comment]
Some details:

`ASPELL_CONF` is read by [Config.read_in_settings](https://github.com/GNUAspell/aspell/blob/rel-0.60.6.1/common/config.cpp#L1266), which is not consistently used in the `libaspell` API, especially not when listing dictionaries. The `aspell` binary always calls `read_in_settings` at start. So the `ASPELL_CONF` is partially broken in the `aspell` upstream.

**Comment by michalrus** [comment]
I confirm this works on `nixos-unstable`.

Thank you very much, @deedrah!

Maybe you could also look at https://github.com/NixOS/nixpkgs/issues/30920 — it seems similar. For some reason LibreOffice is not picking this. :/
