### ISSUE TITLE
How to use impureEnvVars

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#28816]
## Issue description
I'm trying to propagate `http_proxy` environment variable from the calling user environment to the builder environment.
Unfortunately, in the builder environment, I'm not able to get back this variable.

### Steps to reproduce
I run
```
export IMPURE=iop; nix-build -E 'with import <nixpkgs>{}; stdenv.mkDerivation {name="impure"; phases=["buildPhase"]; impureEnvVars=["IMPURE"]; buildPhase="env | grep IMPURE";}'
```

I get the following output
```
these derivations will be built:
  /nix/store/dmyqgk19r871adr4a29q3cjkxrbgwkdz-impure.drv
building path(s) ‘/nix/store/gqhbrlw9hjp6mm77zg5rmb6044xq4dby-impure’
building
impureEnvVars=IMPURE
buildPhase=env | grep IMPURE
builder for ‘/nix/store/dmyqgk19r871adr4a29q3cjkxrbgwkdz-impure.drv’ failed to produce output path ‘/nix/store/gqhbrlw9hjp6mm77zg5rmb6044xq4dby-impure’
error: build of ‘/nix/store/dmyqgk19r871adr4a29q3cjkxrbgwkdz-impure.drv’ failed
```

where I would expect to see `IMPURE=iop` in the builder env.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
1.11.8 and 1.11.13
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.09pre-git
nixpkgs commitID f7ae955bc2d6ab74ff396f2be14e42a712dba61c
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by edolstra** [comment]
If you're using the Nix daemon, then this will not work, since the build will inherit environment variables from the daemon, not from the client.

**Comment by nlewo** [comment]
With nix `1.11.13`, I'm not using the daemon:
```
export IMPURE=iop; NIX_REMOTE='' nix-build -E 'with import <nixpkgs>{}; stdenv.mkDerivation {name="impure"; phases=["buildPhase"]; impureEnvVars=["IMPURE"]; buildPhase="env | grep IMPURE";}'
these derivations will be built:
  /nix/store/w6sqvd17f475g0pjl5a3sb8d15pf41xk-impure.drv
building path(s) ‘/nix/store/8y96bygg1xncd6vz75qc06fj4b7n48k6-impure’
building
impureEnvVars=IMPURE
buildPhase=env | grep IMPURE
builder for ‘/nix/store/w6sqvd17f475g0pjl5a3sb8d15pf41xk-impure.drv’ failed to produce output path ‘/nix/store/8y96bygg1xncd6vz75qc06fj4b7n48k6-impure’
error: build of ‘/nix/store/w6sqvd17f475g0pjl5a3sb8d15pf41xk-impure.drv’ failed
```

**Comment by nlewo** [comment]
I also try to run the daemon from a shell where this variable is exported and it doesn't work better.

**Comment by nlewo** [comment]
Another element is that I successfully used `fetch_url` in the same http proxy environment. So, the propagation of this variable works well with in the `fetch_url` expression but not in my `buildPhase`.

**Comment by bjornfor** [comment]
I think there is a bug in the first example. You're not creating ```$out```. Try this:

```
export IMPURE=iop; nix-build -E 'with import <nixpkgs>{}; stdenv.mkDerivation {name="impure"; phases=["buildPhase"]; impureEnvVars=["IMPURE"]; buildPhase="env | grep IMPURE > $out";}'
```

**Comment by nlewo** [comment]
@bjornfor yes. Sorry, i let this bug  since I was only interested by the build phase output. 
@bjornfor do you have the IMPURE varaible in the output?

**Comment by nlewo** [comment]
Sorry, that's my bad...
In the documentation of impureEnvVars, it is written it only works with fixed-output derivations... which is not the case of mine.
RTFM.

**Comment by srghma** [comment]
@nlewo it still doesn't answer the question how I can test derivation, that using `impureEnvVars`, with `nix-build`, i.e. how to pass `IMPURE` env variable to `nix-buid`
