### ISSUE TITLE
Support `import bcc`

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#288238]
### Describe the bug

Mentioned in https://github.com/NixOS/nixpkgs/issues/45619#issuecomment-415961078, the bcc package can also be used as `import bcc` from python. This currently doesn't seem to work?

### Notify maintainers

@ragnard @Mic92 @thoughtpolice @martinetd 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by martinetd** [comment]
bcc doesn't depend on kernel anymore, so the second half of the comment you linked at isn't required and we can just move the package & add a compat alias.

Technically you should already be able to use bcc as `import bcc` by magic'ing the correct site path, but I agree it's better to move it - patch welcome!
