### ISSUE TITLE
pdfarranger: theme preference greyed out (libhandy missing)

### ISSUE THREAD

**Issue by sleepynix** [NixOS/nixpkgs#288246]
### Describe the bug
In pdfarranger 1.10.1 (from 23.11 stable branch) the option to change the theme in the preferences is greyed out and doesn't respect the globally set dark mode in GNOME. The program offers the hint "(Libhandy missing)" next to the greyed out setting (see image below).

### Steps To Reproduce
1. launch pdfarranger
2. open preferences
3. try changing the theme setting

### Expected behavior
The drop-down menu is clickable and offers several different options to choose from.

### Screenshots
![pdfarranger-theme-selection](https://github.com/NixOS/nixpkgs/assets/159650851/6af11b67-756e-4556-82ae-43a2187bb045)

### Additional context
Manually adding the package libhandy in environment.systemPackages doesn't work.

### Notify maintainers
@symphorien 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
system: "x86_64-linux"
 host os: Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.20240207.6832d0d
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
> Thanks for your quick reply, @chewblacka . I'm new to Git and GitHub, do I have to do something now, like close this issue manually or will it be closed automatically after the changes are merged? Thanks again!

Don't worry issue will be closed automatically when the changes are merged into master (usually by the person who does the merge).
