### ISSUE TITLE
Update request: python311Packages.uvicorn 0.24.0.post1 → 0.27.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#288396]
- Package name: uvicorn
- Latest released version: 0.27.1
- Current version on the unstable channel: 0.24.0.post1
- Current version on the stable/release channel: 0.23.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wd15

https://github.com/encode/uvicorn/releases/tag/0.27.1

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fin444** [comment]
This should be closed, since the PR was merged.
