### ISSUE TITLE
Update request: quarto 1.3.450 → 1.4.549

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#288370]
- Package name: quarto
- Latest released version: 1.4.549

- Current version on the unstable channel: 1.3.450
- Current version on the stable/release channel: 1.3.450

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@minijackson @mrtarantoga

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
This is handled by #263108

**Comment by IogaMaster** [comment]
The pr was merged
