### ISSUE TITLE
Update request: libgit2 1.7.1 → 1.7.2

### ISSUE THREAD

**Issue by super-secret-github-user** [NixOS/nixpkgs#288497]
- Package name: libgit2
- Latest released version: 1.7.2

- Current version on the unstable channel: 1.7.1
- Current version on the stable/release channel: 1.7.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@SuperSandro2000 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by super-secret-github-user** [comment]
This is currently blocking some CI builds as cargo deny flags 1.7.1 as a security vulnerability. 

It looks like just changing the version in the derivation, and updating the hash, results in a successful bump.

**Comment by pinpox** [comment]
PR is here: https://github.com/NixOS/nixpkgs/pull/288499

**Comment by SuperSandro2000** [comment]
was done in #286911
