### ISSUE TITLE
Turn `lib.fileset` into a list of file paths

### ISSUE THREAD

**Issue by yunfachi** [NixOS/nixpkgs#288592]
## Issue description

Add the functionality to turn `lib.fileset` into a list of file paths, which could be useful for importing modules and other tasks.

**Comment by yunfachi** [comment]
@Infinisil

**Comment by infinisil** [comment]
Not done yet, but see https://github.com/NixOS/nixpkgs/issues/288592 :)

**Comment by infinisil** [comment]
Oh and here's more background info as to why this is needed: https://discourse.nixos.org/t/umport-automatic-import-of-modules/39455/3?u=infinisil

**Comment by infinisil** [comment]
Now done with https://github.com/NixOS/nixpkgs/pull/288677!

Also backported to 23.11: https://github.com/NixOS/nixpkgs/pull/291658 :)
