### ISSUE TITLE
Package request: GitButler

### ISSUE THREAD

**Issue by Arya-Elfren** [NixOS/nixpkgs#288567]
**Project description**

GitButler is a git client that lets you work on multiple branches at the same time. It allows you to quickly organize file changes into separate branches while still having them applied to your working directory. You can then push branches individually to your remote, or directly create pull requests.

In a nutshell, it's a more flexible version of git add -p and git rebase -i, allowing you to efficiently multitask across branches.

**Metadata**

* homepage URL: https://gitbutler.com/
* source URL: https://github.com/gitbutlerapp/gitbutler
* license: FSL-1.0-MIT
* platforms: linux, darwin

**Comment by thomaseizinger** [comment]
`cinny-desktop` is also a Tauri app so the packaging is likely similar: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/cinny-desktop/default.nix

**Comment by hacker1024** [comment]
I'll work on this over the weekend.

**Comment by dit7ya** [comment]
I don't think building from source is gonna be easy, precisely as we don't have https://github.com/NixOS/nixpkgs/issues/231513 done yet and this project uses pnpm workspaces. You can however wrap the Appimage though.

**Comment by bobvanderlinden** [comment]
I've made https://github.com/NixOS/nixpkgs/pull/289131. Still draft. It does start the application, but clicking buttons results in problems on my system :sweat_smile:

For a quick run:

```
NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:bobvanderlinden/nixpkgs/pr-gitbutler#gitbutler
```

**Comment by hacker1024** [comment]
I have made a PR that builds from source and has no issues with logging in.

#289664

**Comment by oenu** [comment]
Is this request open to contributions?

**Comment by Aleksanaa** [comment]
> Is this request open to contributions?

Would be best to wait for https://github.com/NixOS/nixpkgs/pull/289664 a while, if that PR goes abandoned, you can ask the author if it's okay to open another
