### ISSUE TITLE
Bug: Provide `/etc/os-release` in `nixpkgs/nix:nixos-*`

### ISSUE THREAD

**Issue by gabyx** [NixOS/nixpkgs#288587]
### Describe the bug
There is currently no `/etc/os-release` file inside the docker images `nixpkgs/nix:nixos-*`. 
Certain tools rely on this file to be existing. It would be nice if that file can be provided.

### Steps To Reproduce
```shell
 docker run -it nixpkgs/nix:nixos-23.11 cat /etx/os-release
```

### Expected behavior
A `/etc/os-release` file should be available.

### Notify maintainers
I am not sure where the maintenance of this is located.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
These Docker images are not managed in Nixpkgs.

https://github.com/nix-community/docker-nixpkgs

(It's a separate namespace, so I sadly cannot transfer this isssue.)
