### ISSUE TITLE
Drop remaining grsecurity bits for 17.09

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#28859]
## Issue description

Since grsecurity is no longer supported, the documentation should probably be dropped for the most part (except, perhaps, for the existing note explaining that it has been dropped and why), I think this is important-ish to get done for 17.09.

I'm happy to do the PR if there's a consensus on how this should be handled, or anyone who's confident about this (was there a maintainer for grsec in NixOS?) has my blessing to do so directly :).

**Comment by joachifm** [comment]
I intend to purge all grsec bits for the release.
