### ISSUE TITLE
Update request: python311Packages.httpx-socks 0.8.0 → 0.8.1

### ISSUE THREAD

**Issue by nikita-skakun** [NixOS/nixpkgs#288645]
- Package name: python311Packages.httpx-socks
- Latest released version: 0.8.1

- Current version on the unstable channel: 0.8.0
- Current version on the stable/release channel: 0.8.0

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@SuperSandro2000

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/288046
