### ISSUE TITLE
Package request: waterfox

### ISSUE THREAD

**Issue by agoodfellow123** [NixOS/nixpkgs#288683]
**Project description**

Waterfox is an improved Firefox with security in mind.

**Metadata**

* homepage URL: https://www.waterfox.net/
* source URL: https://github.com/WaterfoxCo/Waterfox
* license: Mozilla Public License
* platforms: Linux, (unsure of other platforms)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
This is a duplicate of #188883
