### ISSUE TITLE
Package request: marker 

### ISSUE THREAD

**Issue by Vaisakhkm2625** [NixOS/nixpkgs#288635]
*marker*

**Project description**

bookmark commands (or commands templates) and easily retreive them with the help of a real-time fuzzy matcher.

**Metadata**

* homepage URL: https://github.com/pindexis/marker
* source URL: https://github.com/pindexis/marker
* license: mit
* platforms: unix, linux, darwin

**Comment by dawidd6** [comment]
There are no releases in linked repo + last commit was made in 2019. I don't know if it's a good idea to include abandoned software in nixpkgs.

**Comment by chewblacka** [comment]
Further to the above, marker doesn't work with fish shell. Perhaps [intelli-shell](https://github.com/lasantosr/intelli-shell) might be a better package?. Written in rust in 2023 with the same functionality as marker but with wider compatibility.

**Comment by Vaisakhkm2625** [comment]
> Further to the above, marker doesn't work with fish shell. Perhaps [intelli-shell](https://github.com/lasantosr/intelli-shell) might be a better package?. Written in rust in 2023 with the same functionality as marker but with wider compatibility.

Thanks for suggestion... yes, it's better to have intelli-shell...

**Comment by chewblacka** [comment]
> Thanks for suggestion... yes, it's better to have intelli-shell...

Ok. I'll leave it to you to close this issue and open a new request for intelli-shell. Many thanks.

**Comment by Vaisakhkm2625** [comment]
> > Thanks for suggestion... yes, it's better to have intelli-shell...
> 
> Ok. I'll leave it to you to close this issue and open a new request for intelli-shell. Many thanks.

sure, about to ask you that... i will raise a new request for intelli-shell

i am very much a beginner in nix.. so i don't now how to package, but i am learning..
but i can surely help if needed any help...

**Comment by Vaisakhkm2625** [comment]
https://github.com/NixOS/nixpkgs/issues/289067

**Comment by Vaisakhkm2625** [comment]
I have found one more alternative to marker/intellishell , and works more like marker.. i am sharing here for those who are looking for such manager

https://github.com/knqyf263/pet

this is already available in nixpkgs
