### ISSUE TITLE
Package request: `scikit-learn`

### ISSUE THREAD

**Issue by Industrial** [NixOS/nixpkgs#288851]
**Project description**

Python Library

**Metadata**

* homepage URL: https://pypi.org/project/scikit-learn
* source URL: https://pypi.org/project/scikit-learn/
* license: bsd
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arkivm** [comment]
https://search.nixos.org/packages?query=scikit%2Dlearn
