### ISSUE TITLE
Package request (python): `flaml`

### ISSUE THREAD

**Issue by Industrial** [NixOS/nixpkgs#288852]
**Project description**

used in LLM's / machine learning

**Metadata**

* homepage URL: https://pypi.org/project/FLAML/
* source URL: https://pypi.org/project/FLAML/
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sarahec** [comment]
Working on this as part of #261846

**Comment by sarahec** [comment]
Depends on #303917
