### ISSUE TITLE
Package request: kubectl-minio

### ISSUE THREAD

**Issue by AntonFriberg** [NixOS/nixpkgs#288803]
**Project description**

>The [kubectl minio](https://min.io/docs/minio/kubernetes/upstream/reference/kubectl-minio-plugin.html#command-kubectl.minio) plugin brings native support for deploying MinIO tenants to Kubernetes clusters using the kubectl CLI. Use [kubectl minio](https://min.io/docs/minio/kubernetes/upstream/reference/kubectl-minio-plugin.html#command-kubectl.minio) to deploy a MinIO tenant with little to no interaction with YAML configuration files.

Should be very similar to `kubectl-cnpg` https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/cluster/kubectl-cnpg/default.nix

**Metadata**

* homepage URL: https://min.io/docs/minio/kubernetes/upstream/reference/kubectl-minio-plugin.html#command-kubectl.minio
* source URL: https://github.com/minio/operator
* license: AGPL-3.0
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
Upstream has deprecated this application

https://github.com/minio/operator/pull/2051
