### ISSUE TITLE
Build failure: fido2luks

### ISSUE THREAD

**Issue by schrottkatze** [NixOS/nixpkgs#288865]
### Steps To Reproduce

Enable `boot.initrd.luks.fido2Support` or run `nix shell nixpkgs#fido2luks`

### Build log

[gist link](https://gist.github.com/schrottkatze/c1d61f587c6fc68688fa342186936dc4)

### Notify maintainers

@prusnak @mmahut 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.3-zen1, NixOS, 24.05 (Uakari), 24.05.20240205.faf912b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-unstable-small"`
 - channels(jade): `"nixpkgs"`
 - nixpkgs: `/home/jade/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khionu** [comment]
@shimunn this seems to still be an issue

**Comment by khionu** [comment]
Issue filed upstream, fix was a simple update to `libcryptsetup-rs` as well as a `cargo update` for good measure.

**Comment by prusnak** [comment]
> Issue filed upstream, fix was a simple update to `libcryptsetup-rs` as well as a `cargo update` for good measure.

https://github.com/shimunn/fido2luks/issues/55

**Comment by khionu** [comment]
(I kinda figured the reference as rendered by GitHub immediately above my comment would be sufficient)

**Comment by khionu** [comment]
shimunn has responded on the issue on the upstream repo, and is asking us to start using 0.3. I'd personally suggest we stick with 0.2 and either vendor it or patch it. The changed files are just Cargo.toml and Cargo.lock, which I'm attaching both of as confirmed working. I'm not sure the preferred way to address it, but I hope this helps.

[Cargo.zip](https://github.com/NixOS/nixpkgs/files/14503894/Cargo.zip)
