### ISSUE TITLE
tinyproxy fails to parse Filter file

### ISSUE THREAD

**Issue by pvelati** [NixOS/nixpkgs#288907]
### Describe the bug
Tinyproxy with Filter option cause systemd unit to fail

### Steps To Reproduce
1. enable the service with Filter option
```
  services = {
    tinyproxy = {
      enable = true;
      settings = {
        Port = 8888;
        Listen = "0.0.0.0";
        Allow = "192.168.0.0/16";
        FilterDefaultDeny = true;
        Filter = "/etc/nixos/whitelist";
      };
    };
  };
```
and create whitelist the same as the example in tinyproxy documentation:
```
# filter exactly cnn.com
^cnn\.com$

# filter all subdomains of cnn.com, but not cnn.com itself
.*\.cnn.com$

# filter any domain that has cnn.com in it, like xcnn.comfy.org
cnn\.com

# filter any domain that ends in cnn.com
cnn\.com$

# filter any domain that starts with adserver
^adserver
```
2. nixos-rebuild switch, and the systemd unit logs you can see
```
Feb 15 00:32:58 cache tinyproxy[27777]: ERROR: Syntax error on line 2
Feb 15 00:32:58 cache tinyproxy[27777]: Unable to parse config file. Not starting.
```
line 2 is --> Filter /etc/nixos/whitelist

### Expected behavior
configuration correctly parsed without errors in systemd

### Additional context
The problem is that the line in the conf
Filter /etc/nixos/whitelist
should be Filter "/etc/nixos/whitelist"

I tried with another systemd unit and it works.
I'd like to make the PR but I don't know how to fix, sorry.

### Notify maintainers
@tcheronneau

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.76, NixOS, 23.11 (Tapir), 23.11.4248.01885a071465`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nalves599** [comment]
Solved in NixOS 24.05
