### ISSUE TITLE
Planify fonts invisible

### ISSUE THREAD

**Issue by dougkeiller** [NixOS/nixpkgs#288962]
### Describe the bug
Unable to read any text in the Planify pkg GUI

### Steps To Reproduce
1. install Planify using configuration.nix
2. open planify
3. ...

### Expected behavior
Be able to read text in app

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/128188043/998a58fa-f833-4329-9be0-2602779cd17e)

### Notify maintainers

@dtzWill @davidak @bobby285271 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 23.11 (Tapir), 23.11.4248.01885a071465`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
A backport probably helps, please test the above PR.

**Comment by bobby285271** [comment]
Merged the above PR: https://nixpk.gs/pr-tracker.html?pr=288964
