### ISSUE TITLE
Missing symbols to cpp template instantiation

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#28896]
## Issue description

The problem is that after compilation of a cpp source file, the symbol to an instantiated template function is missing.
This is probably a gcc/cpp compiler issue but since the behaviour is different between Fedora and Nix it might also be a Nix problem.

I tried it on Fedora with gcc 5.3.1 and Nix 5.4.0.
On Fedora the symbol is in the created object file but in Nix it's missing.

### Steps to reproduce

With the following derivation it can be simply reproduced by putting it into the file _test.nix_ and running the build via `nix-build test.nix`

````
let
  nixpkgsRev = "227697bc67b8228c454752d70a0b67071176b1e6";
  nixpkgs = builtins.fetchTarball "github.com/NixOS/nixpkgs/archive/${nixpkgsRev}.tar.gz";
  pkgs = import nixpkgs {};

  file = pkgs.writeText "test.cpp" ''
    template <typename T>
    int foo15372(int value)
    {
        return value;
    }
    void test15372b()
    {
        int t = foo15372<int>(1);
    }
  '';
in
  pkgs.runCommand "compile" {} ''
    mkdir $out
    cd $out
    pwd
    ${pkgs.gcc5}/bin/gcc -c ${file} -o $out/test.o
    ${pkgs.binutils}/bin/readelf -sW $out/test.o | grep foo15372
  ''
````

As can be seen the build fails because readelf can't find the symbol to the template function foo15372 in the resulting object file.
I can fix it by inserting a template specialization after the template function declaration `template int foo15372<int>(int value);`

But on Fedora this isn't needed, at least with gcc 5.3.1.
The same applies to virtual functions as can be seen when compiling the code of https://github.com/dlang/dmd/blob/v2.075.1/test/runnable/extra-files/cppb.cpp and searching for _dummy_ in the resulting object file.

## Technical details

* System: Nix on Fedora
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.09pre112229.e619ace733"
* Sandboxing enabled: false

**Comment by ThomasMader** [comment]
Pinging people who might know what's going on.

cc @Ericson2314 @vcunat @LnL7

**Comment by ThomasMader** [comment]
Btw. the general problem occured while running the testsuite for the dmd package. See http://forum.dlang.org/post/odimguuqtekosmtliyhf@forum.dlang.org

**Comment by Ericson2314** [comment]
What a hell of a bug!

**Comment by vcunat** [comment]
Change might be e.g. due to our wrapper adding `-O2` by default.

**Comment by Ericson2314** [comment]
I hope it's something simple like that. In any event if you run our wrapped cc with `NIX_CC=1`, you can see what flags it has and troubleshoot accordingly.

**Comment by vcunat** [comment]
`NIX_DEBUG=1`, I guess :-)

**Comment by Ericson2314** [comment]
Oh haha yeah

**Comment by ThomasMader** [comment]
With nixpkgsRev = "c485a491dba401276b39c0d0a0380e834c8fca90"; the problem doesn't occur anymore.
The test still fails but it's because ${pkgs.binutils}/bin/readelf doesn't exist anymore.
I just checked the resulting object file manually via readelf.

**Comment by ThomasMader** [comment]
The problem still occurs within a normal package derivation.
First I fixed the test which now succeeds:

```
let
  nixpkgsRev = "c485a491dba401276b39c0d0a0380e834c8fca90";
  nixpkgs = builtins.fetchTarball "github.com/NixOS/nixpkgs/archive/${nixpkgsRev}.tar.gz";
  pkgs = import nixpkgs {};

  file = pkgs.writeText "test.cpp" ''
    template <typename T>
    int foo15372(int value)
    {
        return value;
    }
    void test15372b()
    {
        int t = foo15372<int>(1);
    }
  '';
in
  pkgs.runCommand "compile" {} ''
    mkdir $out
    cd $out
    pwd
    echo ${file}
    ${pkgs.gcc}/bin/gcc -c ${file} -o $out/test.o
    ${pkgs.binutils-unwrapped}/bin/readelf -sW $out/test.o | grep foo15372
  ''

```

Then I realized that the problem still occurs when the same file gets compiled with the same command like this (being in a checked out nixpkgs dir above c485a491dba401276b39c0d0a0380e834c8fca90):

nix-shell -A dmd --pure
gcc -c /nix/store/qn9sz3dfbxyvbxvfdzpk16dil9ird1jb-test.cpp -o /tmp/cppb.cpp.o
readelf -sW /tmp/cppb.cpp.o | grep foo15372

But using

nix-shell -A gcc --pure

solves the problem.
What is going on here?

**Comment by ThomasMader** [comment]
The problem is the hardening. The fortify especially.
Adding `hardeningDisable = [ "fortify" ];` to the package solves the problem.
