### ISSUE TITLE
where-is-my-sddm theme doesn't display background image

### ISSUE THREAD

**Issue by ElrohirGT** [NixOS/nixpkgs#289060]
### Describe the bug
I have configured the [where-is-my-sddm](https://github.com/stepanzubkov/where-is-my-sddm-theme/) theme for my sddm inside my nixos configuration. According to the docs:
https://github.com/NixOS/nixpkgs/blob/35ff7e87ee05199a8003f438ec11a174bcbd98ea/pkgs/data/themes/where-is-my-sddm-theme/default.nix#L6-L17

So my nixos-configuration looks like this:
```nix
(where-is-my-sddm-theme.override {
    themeConfig.General = {
        background = "${config.users.users.elrohirgt.home}/.login-background.jpg";
        backgroundMode = "fill";
    };
})
```

After running `sudo nixos-rebuild boot && reboot` multiple times the background image never appears.

### Steps To Reproduce
1. Enable xserver and sddm in `configuration.nix`.
2. Download a background image, place it on your users home with the name `.login-background.jpg`.
3. Install the `where-is-my-sdd-theme` package with the above configuration.
4. Set the `theme` property on the sddm configuration to be `where-is-my-sddm`.
```nix
services.xserver.displayManager.sddm = {
    enable = true;
    theme = "where_is_my_sddm_theme";
};
```
4. Reboot

### Expected behavior
Expected my image to be the background image for the theme:
![Background image](https://private-user-images.githubusercontent.com/83695097/237778729-36880c07-c4d2-4056-b3b3-243b4043f475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDYwMjgsIm5iZiI6MTcwODAwNTcyOCwicGF0aCI6Ii84MzY5NTA5Ny8yMzc3Nzg3MjktMzY4ODBjMDctYzRkMi00MDU2LWIzYjMtMjQzYjQwNDNmNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE0MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWQ2NWE4MmM0YzczYjFlZjljOGFmZmRkMDczMWRkYThlMDI0ODdkNmExNzBlZWRkYjVmOGE1N2Q0NjQwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JVnQKzcGPmmuLNNG-8RUUJlwahO0_fKVzC8wDR8wRzk)

### Additional context
Here are most of the configurations I tried without any luck:
- [file:${config.users.users.elrohirgt.home}/.login-background.jpg](https://stackoverflow.com/questions/26125095/cant-load-image-source-in-qml-image)
- file://${config.users.users.elrohirgt.home}/.login-background.jpg
- '${config.users.users.elrohirgt.home}/.login-background.jpg'

After some research in the original repo I've found [an issue](https://github.com/stepanzubkov/where-is-my-sddm-theme/issues/15) where the background image seems to not be able to be loaded unless is in the same directory as `theme.conf`.

### Notify maintainers
@name-snrl

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 23.11 (Tapir), 23.11.4117.6832d0d99649`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by name-snrl** [comment]
Also, using full paths is not the nix way. It is better to put a background image near to your configuration and specify the path to it relative to the file in which you specify it.

```nix
# /etc/nixos/configuration.nix
(where-is-my-sddm-theme.override {
    themeConfig.General = {
        background = ./login-background.jpg;
        backgroundMode = "fill";
    };
})
```

The background should be located at /etc/nixos/login-background.jpg

**Comment by name-snrl** [comment]
btw, I couldn't open the picture you attached

**Comment by name-snrl** [comment]
> After some research in the original repo I've found [an issue](https://github.com/stepanzubkov/where-is-my-sddm-theme/issues/15) where the background image seems to not be able to be loaded unless is in the same directory as `theme.conf`.

This is not true. My current background image is in the nix store and everything works fine.

```fish
name_snrl in ~ 
> cat /run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme/theme.conf.user 
[General]
background=/nix/store/b9pm2bvv10h6jnq3zdhb80wgwm5i0xjp-nixos-icons-2021-02-24/share/icons/hicolor/scalable/apps/nix-snowflake.svg
backgroundFill=#2e3440
backgroundMode=none
```

**Comment by ElrohirGT** [comment]
> Are you sure that `config.users.users.elrohirgt.home` interpolates to the full path of your home directory? Could you show me output of `cat /run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme/theme.conf.user`?

Thank you for answering so soon!
The output of `cat /run/current-system/sw/share/sddm/themes/where_is_my_sddm_theme/theme.conf.user`:
```console
[General]
background=/home/elrohirgt/.login-background.jpg
backgroundFill=
backgroundMode=fill
```

**Comment by ElrohirGT** [comment]
> Also, using full paths is not the nix way. It is better to put a background image near to your configuration and specify the path to it relative to the file in which you specify it.
> 
> ```nix
> # /etc/nixos/configuration.nix
> (where-is-my-sddm-theme.override {
>     themeConfig.General = {
>         background = ./login-background.jpg;
>         backgroundMode = "fill";
>     };
> })
> ```
> 
> The background should be located at `/etc/nixos/login-background.jpg`

I didn't know that, gonna try it! Probably would be good to add that to the docs just to help newbies like me hehe

**Comment by ElrohirGT** [comment]
> btw, I couldn't open the picture you attached

Hmmm... wierd. It's the same image as the repo of "where-is-my-sddm" README ![example login](https://github.com/raihanadf/where-is-my-sddm/assets/83695097/36880c07-c4d2-4056-b3b3-243b4043f475)

**Comment by name-snrl** [comment]
> It's the same image as the repo of "where-is-my-sddm" README

yeah, I think the problem is in permissions or picture

**Comment by ElrohirGT** [comment]
> Also, using full paths is not the nix way. It is better to put a background image near to your configuration and specify the path to it relative to the file in which you specify it.
> 
> ```nix
> # /etc/nixos/configuration.nix
> (where-is-my-sddm-theme.override {
>     themeConfig.General = {
>         background = ./login-background.jpg;
>         backgroundMode = "fill";
>     };
> })
> ```
> 
> The background should be located at `/etc/nixos/login-background.jpg`

Tried this config:
```nix
(where-is-my-sddm-theme.override {
    themeConfig.General = {
        background = ./login-background.jpg;
        backgroundMode = "fill";
    };
})
```

When I execute `ls /etc/nixos/`:
```console
configuration.nix
hardware-configuration.nix
login-background.jpg
```

But when I try to rebuild it fails with:
![image](https://github.com/NixOS/nixpkgs/assets/45268815/d377e04f-bd76-4e59-8f59-0d121e5651da)

**Comment by name-snrl** [comment]
> When I execute `ls /etc/nixos/`

oops, it turns out the ini generator has limitations, try it like this:

```nix
(where-is-my-sddm-theme.override {
    themeConfig.General = {
        background = toString ./login-background.jpg;
        backgroundMode = "fill";
    };
})
```

**Comment by ElrohirGT** [comment]
It works now! Thank you for your help!
