### ISSUE TITLE
Update request: power-profiles-daemon 0.13 -> 0.20

### ISSUE THREAD

**Issue by tlvince** [NixOS/nixpkgs#289019]
Package name: power-profiles-daemon

- Latest released version: [0.20](https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/commit/0d3030b6109156a093b73c66aea2ef3118a79650)
- Current version on the unstable channel: 0.13
- Current version on the stable/release channel: 0.13
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Notify maintainers

@mvnetbiz

---

Note for maintainers: Please tag this issue in your PR.

**Comment by tlvince** [comment]
I had a quick go at updating:

- there's a new build dependency on argparse-manpage, which I [couldn't find packaged](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20argparse-manpage&type=code)
- disabling manpages with the meson opt `-Dmanpage=disabled` got further, but the build tests failed

**Comment by NickCao** [comment]
For argparse-manpage: https://github.com/NixOS/nixpkgs/pull/289120

**Comment by kjhoerr** [comment]
It looks like in addition to the new build dependency, the integration tests invoke `src/powerprofilesctl` (see: [`tool_path`](https://gitlab.freedesktop.org/upower/power-profiles-daemon/-/blame/0.20/tests/integration_test.py?page=2#L1865) and usage) which needs to be included in the `postPatch` for the power-profiles-daemon package spec alongside the two test files. Doing this local override fixed it for me:

```nix
(final: prev: {
  power-profiles-daemon = prev.power-profiles-daemon.overrideAttrs(old: {
    version = "0.20";
    nativeBuildInputs = lib.mkAfter [ pkgs.argparse-manpage ];
    src = prev.fetchFromGitLab {
      domain = "gitlab.freedesktop.org";
      owner = "upower";
      repo = "power-profiles-daemon";
      rev = "0.20";
      sha256 = "sha256-8wSRPR/1ELcsZ9K3LvSNlPcJvxRhb/LRjTIxKtdQlCA=";
    };
    postPatch = ''
      patchShebangs --build \
        src/powerprofilesctl \
        tests/integration-test.py \
        tests/unittest_inspector.py
    '';
  });
})
```

**Comment by tlvince** [comment]
#289748

**Comment by alexshpilkin** [comment]
https://github.com/NixOS/nixpkgs/pull/289748 has been merged as of several hours ago and [should be on its way](https://nixpk.gs/pr-tracker.html?pr=289748) to channels (at least as soon as [the most recent build failure](https://github.com/NixOS/nixpkgs/pull/291197) is fixed).
