### ISSUE TITLE
Package request: aylurs-gtk-shell

### ISSUE THREAD

**Issue by dracdavamp** [NixOS/nixpkgs#289099]
**Project description**

A customizable and extensible shell.
This is a library built for [GJS](https://gitlab.gnome.org/GNOME/gjs) to allow defining GTK widgets in a declarative way. It also provides services and other utilities to interact with the system so that these widgets can have functionality. GJS is a JavaScript runtime built on Firefox's SpiderMonkey JavaScript engine and the GNOME platform libraries, the same runtime [GNOME Shell](https://gitlab.gnome.org/GNOME/gnome-shell) runs on.

**Metadata**

* homepage URL: https://github.com/Aylur/ags
* source URL: https://github.com/Aylur/ags
* license: GPL-3.0
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by W-Y-R** [comment]
AGS is already configurable through the home manager module: https://aylur.github.io/ags-docs/config/home-manager/

**Comment by dracdavamp** [comment]
I am sorry, I didn't notice the flake...
Should I close this issue or should this be left open to include the ags in nixpkgs?

**Comment by W-Y-R** [comment]
I doubt that ags will be added into nixpkgs. Home manager offers more customizability than nixpkgs would offer, after all.

**Comment by dracdavamp** [comment]
Umm..
So can I close this?

**Comment by W-Y-R** [comment]
Yes, you may close it as not planned

**Comment by Ligthiago** [comment]
> not planned

The AGS developer is fine with adding the package to nixpkgs and even said it would be cool, as you can see here:
https://github.com/Aylur/ags/issues/251

I'm not sure it's really "not planned".


> Home manager offers more customizability than nixpkgs would offer, after all

You can simply upsteam the package to nixpkgs and the home-manager module to home-manager. Like Eww for example. Also it can work fine without HM module, it just fancy way to add package and symlink some dir with ags config to `.config/ags`.

Also package already written by dev, so just copy and paste with minor changes, like using fixed version, should be easy if someone wants to do this.

**Comment by W-Y-R** [comment]
I wasn't aware of the discussion. If that's the case, then I don't see any problem with reopening this issue if the op deems it necessary.
