### ISSUE TITLE
Prevent Brave browser to request autoupdate

### ISSUE THREAD

**Issue by alecandido** [NixOS/nixpkgs#289020]
## Issue description

Brave browser keeps reporting a failed autoupdate.

![image](https://github.com/NixOS/nixpkgs/assets/10830876/4d7dd906-c6e6-46e7-97d7-dd6e5b2a2f89)

It should be possible to avoid it just adding a CLI option in the `.desktop` entry:
```
Exec=... --disable-features=OutdatedBuildDetector
```
https://github.com/brave/brave-browser/issues/5576

### Steps to reproduce

- install the `brave` package
- open "Brave Web Browser" from the Gnome applications menu
- click the menu button (it is displaying an alert even before clicking) 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```sh
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.61, NixOS, 23.11 (Tapir), 23.11.20231105.15492dd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alecandido** [comment]
Btw, this is much less relevant, but all icons are missing from the package.

```
❯ ls -T
.
├── appdata
│  └── brave-browser.appdata.xml
├── applications
│  └── brave-browser.desktop
├── doc
│  └── brave-browser
│     └── changelog.gz
├── gnome-control-center
│  └── default-apps
│     └── brave-browser.xml
├── icons
│  └── hicolor
│     ├── 16x16
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_16.png
│     ├── 24x24
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_24.png
│     ├── 32x32
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_32.png
│     ├── 48x48
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_48.png
│     ├── 64x64
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_64.png
│     ├── 128x128
│     │  └── apps
│     │     └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_128.png
│     └── 256x256
│        └── apps
│           └── brave-browser.png -> ../../../../../opt/brave.com/brave/product_logo_256.png
├── man
│  └── man1
│     ├── brave-browser-stable.1.gz
│     └── brave-browser.1.gz -> brave-browser-stable.1.gz
└── menu
   └── brave-browser.menu
```

**Comment by chewblacka** [comment]
> Btw, this is much less relevant, but all icons are missing from the package.

The icons are there. They are symlinks to the `/nix/store/hash-brave-version/opt` directory.

**Comment by alecandido** [comment]
Indeed, I realized right after writing it, but then forgot to update: I thought I was one directory up in the hierarchy. My bad...

**Comment by buckley310** [comment]
I was checking out the above PR, but I cant seem to recreate the issue. right now I've got brave 1.62.162, and the latest version available online is 1.62.165. It doesn't seem to be checking for updates. Is there a trick to getting it to check, or is it just sorta auto-updating?

**Comment by alecandido** [comment]
Exploring Brave issues, like the one linked above, apparently the auto-update is a Chromium feature, even not so easy to mask for the Brave crew.

However, within Nix, Brave is prevented to auto-update, so that's not an issue on its own. But it's attempting to, and just reporting the failure. So, no trick.

I will soon check the version and report, but in case it helps, I'm using `nixpkgs-unstable` through a flake:
```nix
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
```
https://github.com/alecandido/nixpkgs/blob/0e6c317a05be1868437c7b753b42b9ad5ebab167/flake.nix#L6
and installing through NixOS:
```nix
  environment.systemPackages = with pkgs; [
    git
    firefox
    thunderbird
    kitty
    wl-clipboard
    gnome-browser-connector
    gnome-extension-manager
    brave
  ];
```
https://github.com/alecandido/nixpkgs/blob/0e6c317a05be1868437c7b753b42b9ad5ebab167/etc/nixos/default.nix#L73-L82

**Comment by buckley310** [comment]
Yeah, that's what I mean, it doesn't even appear to be trying to update when I try it.

**Comment by alecandido** [comment]
Since I provided the whole flake (and I'm also not doing anything other than requesting the package), I'm not sure what else can I do to improve reproducibility.

In case, I could provide further screenshots. But the one above is essentially the issue on its own.

**Comment by buckley310** [comment]
Recreated with the flake :+1:

**Comment by alecandido** [comment]
> Recreated with the flake 👍

Do you understand why is it showing up with the flake and not without?

**Comment by buckley310** [comment]
> > Recreated with the flake 👍
> 
> Do you understand why is it showing up with the flake and not without?

Didn't bother figuring it out. Figuring it's probably just that my version wasn't out-of-date enough.
