### ISSUE TITLE
Broken Package: DXVK after commit 0295c67

### ISSUE THREAD

**Issue by LovingMelody** [NixOS/nixpkgs#289163]
### Describe the bug
DXVK doesn't run properly after commit 0295c6712888657e75b249c279f82c6dae7ffdf3 on the nixos-unstable-small branch last working commit is b01852a162216ff5521c43254986fe3048a35f56.  When attempting to run a game with the symlinked DXVK from the broken commit, games will report back with the error `[vendor id = 0x0000, device id = 0x0000]`  setting `DXVK_FILTER_DEVICE_NAME` to the specific GPU does not resolve this issue either. 
### Steps To Reproduce
Run a game with DXVK from commit 0295c6712888657e75b249c279f82c6dae7ffdf3

### Expected behavior
The game is expected to run as it does with upstream DXVK releases

### Screenshots
![2024-01-21T16:20:33_no_watermark](https://github.com/NixOS/nixpkgs/assets/17859309/563c0e69-b307-4d09-84b9-178c691003f9)

### Additional context
GPU is NVIDIA

EDIT: Another user on AMD is able to reproduce the issue

### Notify maintainers

@reckenrode 

### Metadata

```console
melody in ~
at 18:54:19 ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.16, NixOS, 24.05 (Uakari), 24.05.20240215.f893cc7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/7fdgsp4sd79fb8gzym5h1mgv0s6m3s1b-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by reckenrode** [comment]
Different issue from https://github.com/NixOS/nixpkgs/issues/283642? Are you able to get any log messages that might help pin down the problem?

**Comment by LovingMelody** [comment]
Duplicate issue it seems, I will close this one
