### ISSUE TITLE
Update request: flutter 3.16.7 → 3.19.0

### ISSUE THREAD

**Issue by zh4ngx** [NixOS/nixpkgs#289170]
- Package name: Flutter
- Latest released version: 3.19.0

- Current version on the unstable channel: 3.16.7
- Current version on the stable/release channel: 3.13.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@hacker1024 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hacker1024** [comment]
@NixOS/flutter
