### ISSUE TITLE
`boot.kernel.sysctl` not working in LXC containers

### ISSUE THREAD

**Issue by LostAttractor** [NixOS/nixpkgs#289174]
### Describe the bug
`boot.kernel.sysctl` not working in lxc containers. But sysctl command works fine and /proc/sys/ is writable.

This nix option seems to finally take effect via `systemd-sysctl`. And the `systemd-sysctl.services` look like this:
```
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Apply Kernel Variables
Documentation=man:systemd-sysctl.service(8) man:sysctl.d(5)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-modules-load.service
Before=sysinit.target shutdown.target
ConditionPathIsReadWrite=/proc/sys/net/

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/nix/store/m0nicpa4d724rljadlmw1m3qv0ja4syy-systemd-255.2/lib/systemd/systemd-sysctl
TimeoutSec=90s
ImportCredential=sysctl.*
```
This looks fine, So I tried to manually run the command in `ExecStart`, **and it takes effect**!

But this looks even weirder.
Through `systemctl status systemd-sysctl.services`, I got:
```
● systemd-sysctl.service - Apply Kernel Variables
     Loaded: loaded (/etc/systemd/system/systemd-sysctl.service; enabled; preset: enabled)
    Drop-In: /nix/store/nv6npi2ya52zg6wqa7mxbq3f3ld3gwck-system-units/systemd-sysctl.service.d
             └─overrides.conf
             /run/systemd/system/systemd-sysctl.service.d
             └─zzz-lxc-override.conf
     Active: active (exited) since Fri 2024-02-16 00:51:42 UTC; 19min ago
       Docs: man:systemd-sysctl.service(8)
             man:sysctl.d(5)
    Process: 625 ExecStart=/lib/systemd/systemd-sysctl (code=exited, status=0/SUCCESS)
   Main PID: 625 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out
        CPU: 4ms

Feb 16 00:51:42 router systemd[1]: Starting Apply Kernel Variables...
Feb 16 00:51:42 router systemd[1]: Finished Apply Kernel Variables.
```
There is an unusual `zzz-lxc-override.conf`. It looks like this:
```
root@system ~# cat /run/systemd/system/systemd-sysctl.service.d/zzz-lxc-override.conf
[Service]
ExecStart=
ExecStart=-/lib/systemd/systemd-sysctl
root@system ~# 
```
Obviously, there is not `/lib/systemd/systemd-sysctl` is NixOS. So `systemd-sysctl` won't run at all.
I looked it up on the internet and found out it's from distrobuilder:
https://github.com/lxc/distrobuilder/blob/main/distrobuilder/lxc.generator#L146

So maybe we should just patch it?

### Steps To Reproduce
1. Create a privilege container with NixOS in it.
2. Add something to `boot.kernel.sysctl` and rebuild the system
3. Reboot, and there is no effect

### Expected behavior
`systemd-sysctl` should run and takes effect.

### Notify maintainers

@NixOS/lxc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.11-8-pve, NixOS, 24.05 (Uakari), 24.05.20240211.f9d39fb`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11.4166.20f65b86b648"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Are you able to you reproduce this with unstable? There are some improvements post 23.11 to the use of the lxc generator.

**Comment by LostAttractor** [comment]
> Are you able to you reproduce this with unstable? There are some improvements post 23.11 to the use of the lxc generator.

Yes, I'm already on unstable channel.
The channel information in metadata tab is incorrect because I'm using flakes.

**Comment by adamcstephens** [comment]
@LostAttractor can you test this change? https://github.com/NixOS/nixpkgs/pull/290570

**Comment by LostAttractor** [comment]
> @LostAttractor can you test this change? #290570

It works fine for me.
But I don’t know if there are any problems caused by other hard-coded paths in distrobuilder.

And I don’t know whether using sysctl on an unprivileged container will cause the service to fail to start, and whether the startup failure will cause problems.
But it seems that `systemd-sysctl.service` sets `ConditionPathIsReadWrite`, so there should be no problem?

**Comment by adamcstephens** [comment]
Thanks for testing!

>  But I don’t know if there are any problems caused by other hard-coded paths in distrobuilder.

There shouldn't be, since we patch and wrap the distrobuilder lxc generator. I audited it again after updating the patch for this fix. You can always see the resulting file by building `distrobuilder.generator`.

> And I don’t know whether using sysctl on an unprivileged container will cause the service to fail to start, and whether the startup failure will cause problems.

The PR has tests which should cover unprivileged containers. I've just updated them to add a check verifying systemd-sysctl successfully started.
