### ISSUE TITLE
How to install NixOS through Nix (from other GNU/Linux) ?

### ISSUE THREAD

**Issue by jpierre03** [NixOS/nixpkgs#28928]
## Issue description

Can't install nixos-install with nix-env.

### Steps to reproduce

On a fresh ubuntu 16.04 LTS (automaticaly installed by a hoster)
NixOs installation process followed  as `root` :

Note :
* it was the recommended procedure linked https://github.com/NixOS/nixpkgs/issues/13309
* new wiki is not helpfull https://nixos.wiki/wiki/NixOS#Installation
* this procedure was working on march 2017

```bash
adduser nix
groupadd -r nixbld
for n in $(seq 1 10); do useradd -c "Nix build user $n" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" nixbld$n; done

update-ca-certificates

chown -R nix /nix /tmp
su - nix
bash <(curl https://nixos.org/nix/install)
exit

. ~nix/.nix-profile/etc/profile.d/nix.sh

nix-channel --remove nixpkgs
nix-channel --add https://nixos.org/channels/nixos-unstable nixos
nix-channel --update

echo '{ fileSystems."/" = {}; boot.loader.grub.enable = false; }' > configuration.nix

export NIX_PATH=nixpkgs=/root/.nix-defexpr/channels/nixos:nixos=/root/.nix-defexpr/channels/nixos/nixos
export NIXOS_CONFIG=/root/configuration.nix
```
Previous commands execute correctly (= without failure).

```bash
nix-env -i -A config.system.build.nixos-install \
       -A config.system.build.nixos-option \
       -A config.system.build.nixos-generate-config \
       -f ""
```

Gives :

```bash
nix-env -i -A config.system.build.nixos-install \
>        -A config.system.build.nixos-option \
>        -A config.system.build.nixos-generate-config \
>        -f ""
error: attribute ‘config’ in selection path ‘config.system.build.nixos-install’ not found
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) : Ubuntu 16.04
* Nix version: (run `nix-env --version`) : nix-env (Nix) 1.11.14
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) : 18.03pre114421.799435b7ca

**Comment by danbst** [comment]
You may be interested in these instructions:
https://github.com/elitak/nixos-infect/blob/master/nixos-infect#L193
But personally, I've never tried to install nixos-install on non-nixos.

**Comment by danbst** [comment]
(note the `-f '<nixpkgs/nixos>' ` passed to nix-env)

**Comment by jpierre03** [comment]
@danbst Thanks a lot.
 `nix-env` ... `-f '<nixpkgs/nixos>'` fixed this issue.
