### ISSUE TITLE
services.nginx.virtualHosts: invalid example

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#28926]
## Issue description
The example given for services.nginx.virtualHosts seems to conflict with with the assertion:
```
          {
            "hydra.example.com" = {
              addSSL = true;
              forceSSL = true;
              enableACME = true;
              locations."/" = {
                proxyPass = "http://localhost:3000";
              };
            };
          };
```

```
        assertion = all (conf: with conf;
          !(addSSL && (onlySSL || enableSSL)) &&
          !(forceSSL && (onlySSL || enableSSL)) &&
          !(addSSL && forceSSL)
        ) (attrValues virtualHosts);
        message = ''
          Options services.nginx.service.virtualHosts.<name>.addSSL,
          services.nginx.virtualHosts.<name>.onlySSL and services.nginx.virtualHosts.<name>.forceSSL
          are mutually exclusive.
        '';
```

The example combines addSSL with forceSSL which will not pass the assertion.
Additionally I was unable to find the reason behind this changed behavior (and did not expect a commit titled "nginx module: clean up SSL/listen handling" to introduce breaking changes ;) ).

Ping @globin

**Comment by globin** [comment]
The addSSL is probably what you don't want, the implementation was ambiguous.. If you use `addSSL` you would expect the vhost to be the same on non-ssl which conflicts with `forceSSL` will clean up the documentation, missed that one.
