### ISSUE TITLE
Package request: jailer

### ISSUE THREAD

**Issue by frafra** [NixOS/nixpkgs#289244]
**Project description**

Jailer is a tool for database subsetting, schema and data browsing.
**Metadata**

* homepage URL: https://wisser.github.io/Jailer/
* source URL: https://github.com/Wisser/Jailer
* license: Apache 2
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/311371
