### ISSUE TITLE
Package request: vscode-extensions.bodil.blueprint-gtk

### ISSUE THREAD

**Issue by Lyndeno** [NixOS/nixpkgs#289438]
**Project description**

A vscode extension for the blueprint language.

**Metadata**

* homepage URL: https://marketplace.visualstudio.com/items?itemName=bodil.blueprint-gtk
* source URL: https://github.com/bodil/vscode-blueprint
* license: LGPL V3
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
I suggest you package it yourself:

Have a look in:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/

Read the README.md:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/README.md

Edit:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/default.nix

Build as:

> nix build .#vscode-extensions.publisher-name.extension-name

**Comment by TheRobot2105** [comment]
#384836
