### ISSUE TITLE
Package request: pdfannots

### ISSUE THREAD

**Issue by benbrastmckie** [NixOS/nixpkgs#289440]
**Project description**

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment]
Assuming you're referring to [this one](https://github.com/0xabu/pdfannots)...

Homepage: https://github.com/0xabu/pdfannots
Source: https://github.com/0xabu/pdfannots
License: MIT
Platforms: All supported by Python and PDFMiner

**Comment by benbrastmckie** [comment]
Yes that's right.
