### ISSUE TITLE
Tofi package segmentation fault

### ISSUE THREAD

**Issue by JaydenElliott** [NixOS/nixpkgs#289495]
### Describe the bug
`Tofi` package will error ` 8451 segmentation fault (core dumped)  tofi` when run.

### Steps To Reproduce
1. Ensure you are using wayland
2. `nix-shell -p tofi`
3. run `tofi`

### Notify maintainers
@fbergroth :pray: 

### Metadata

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.73, NixOS, 24.05 (Uakari), 24.05.20240117.842d9d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by IogaMaster** [comment]
I am currently unable to reproduce this issue.

**Comment by IogaMaster** [comment]
I also dont see the segfault with stdin
![image](https://github.com/NixOS/nixpkgs/assets/67164465/fce07346-5d78-46cc-b9ba-149e135b5a6c)
