### ISSUE TITLE
pinentry-mac fails to build

### ISSUE THREAD

**Issue by loskutov** [NixOS/nixpkgs#28944]
## Issue description
When trying to build pinentry-mac, besides #26774, I also encounter a different build failure:
```
% nix-build '<nixpkgs>' -A pinentry_mac
these derivations will be built:
  /nix/store/c2w9mx7gw9wak253gamvyy1mnvsz7dxq-pinentry-mac-0.9.4.drv
building path(s) ‘/nix/store/z0bxm8lb6l4cm43p0inkhrmrhbcx3jjw-pinentry-mac-0.9.4’

<...>

** BUILD FAILED **

The following build commands failed:
    Ld ./pinentry-mac-ddraybfelawzybdskxmwfbpamtbf/Build/Products/Release/pinentry-mac.app/Contents/MacOS/pinentry-mac normal x86_64
(1 failure)
make: *** [Makefile:9: build/Release/pinentry-mac.app/Contents/MacOS/pinentry-mac] Error 1
builder for ‘/nix/store/c2w9mx7gw9wak253gamvyy1mnvsz7dxq-pinentry-mac-0.9.4.drv’ failed with exit code 2
error: build of ‘/nix/store/c2w9mx7gw9wak253gamvyy1mnvsz7dxq-pinentry-mac-0.9.4.drv’ failed
```

### Steps to reproduce

The command above.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
macOS 10.12.6 (16G29)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.14
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
18.03pre114401.017561209e
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
true

**Comment by matthewbauer** [comment]
I think this is fixed in #28868

**Comment by loskutov** [comment]
Looks like it, thanks!

**Comment by LnL7** [comment]
https://hydra.nixos.org/build/59974289

**Comment by loskutov** [comment]
It looks like that failure is related to #26774, not this one.

**Comment by matthewbauer** [comment]
Fixed in nixpkgs-unstable.
