### ISSUE TITLE
programs.steam: Maintainers wanted

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#289561]
I'm currently the single maintainer for the steam module and as such usually the only person pinged.

I'd like to ask the community to step up and help, since my time and experience in this area of nixpkgs is quite limited

Comment here if you wanted to be added. A steam team will be created later.

**Comment by eclairevoyant** [comment]
Sure, I can help.

**Comment by appsforartists** [comment]
cc @samueldr @k900 @zhaofengli from Jovian

**Comment by K900** [comment]
I can probably help.

**Comment by Atemu** [comment]
I use Steam frequently, have touched the Steam module before and somewhat maintain buildFHSEnv, I can help out.

**Comment by mkg20001** [comment]
@hrdinka @abbradar @tadfisher @jagajaga @jonringer you are currently listed as a maintainer for steam/steam-runtime/steamcmd. would it be ok to add you to the steam team and then set maintainers for all steam packages to `teams.steam`?

**Comment by Atemu** [comment]
(And do you actually still maintain Steam?)

**Comment by mkg20001** [comment]
I haven't really touched it in a while, I might just remove myself ig.

**Comment by jonringer** [comment]
I'll help out, still use it regularly

**Comment by mkg20001** [comment]
I've merged the PR now, the package maintainers were left untouched, only the module was updated. Feel free to use the team in packages aswell.

**Comment by pbsds** [comment]
done in https://github.com/NixOS/nixpkgs/pull/292817
