### ISSUE TITLE
Package request: vimPlugins.align-nvim

### ISSUE THREAD

**Issue by coastalwhite** [NixOS/nixpkgs#289558]
**Project description**

A minimal plugin for NeoVim for aligning lines

**Metadata**

* homepage URL: https://github.com/Vonr/align.nvim
* source URL: https://github.com/Vonr/align.nvim
* license: GPL-3.0
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/349969 🎉
