### ISSUE TITLE
httpd.documentRoot: Create folder if missing

### ISSUE THREAD

**Issue by d3xter** [NixOS/nixpkgs#28966]
## Issue description
Folder specified as services.httpd.documentRoot is not created automatically.
Apache2 fails to start afterwards, because its documentRoot is non-existing.

**Comment by xeji** [comment]
Auto creating the documentRoot was intentionally removed in  #21703 . 
Is this really a bug?

**Comment by samueldr** [comment]
(triage) Assuming this isn't a an issue anymore due to there being no response, and the change was apparently intentional. Don't hesitate to re-open if it is still an issue, hopefully with details about why this should be reverted back to creating a document root.
