### ISSUE TITLE
Support for Zulu on AArch64

### ISSUE THREAD

**Issue by edude03** [NixOS/nixpkgs#28977]
## Issue description
Now that NixOS supports AArch64 (IE on the Raspberry Pi 3) I'd like to use Zulu. However, the existing derivation only supports x86 based systems. 

### Steps to reproduce
`nix-env -i zulu` on a AArch64 bit system. 

## Technical details

I've managed to make the package install by changing and hardcoding some values in the existing derivation (https://github.com/NixOS/nixpkgs/blob/740d76371e6c1c76bae4801fc5b736a796c1ebbe/pkgs/development/compilers/zulu/default.nix#L80) however I'm not proficient enough in the Nix language to build a solution for all existing platforms. 

Zulu supports Arm 32bit with hard and soft float as well as aarch64 (see https://www.azul.com/downloads/zulu-embedded/) however I'm not sure how to change the existing derivation to detect the arch properly.

**Comment by NeQuissimus** [comment]
@edude03 If you're willing, we can work on this together. I don't have an AArch64...

We can do this to detect an AArch64:
```
if stdenv.system == "aarch64-linux" ...
```

And add `"aarch64-linux"` to the `meta.platforms`.
A few things will need to be altered, mostly things that determine the eventual value of `src` (which itself contains `_x64` right now, also needs to be moved out)

Make a PR and I will try to help as much as I can.

**Comment by bachp** [comment]
I had a look at it and there doesn't seem to be a version of [Zulu](https://www.azul.com/downloads/zulu/zulu-linux/) for ARMv8 (AArch64).

There is [Zulu Embedded](https://www.azul.com/downloads/zulu-embedded/) and [Zulu for 64-bit ARMv8](https://www.azul.com/downloads/zulu/zulu-download-arm/) but they seem to be different Products than Zulu and most probably can't be used to replace Zulu 1:1.

**Comment by wegank** [comment]
Closed by #259825.
