### ISSUE TITLE
Package request: chaiNNer

### ISSUE THREAD

**Issue by BillyHerrrington** [NixOS/nixpkgs#289720]
**Project description**

A node-based image processing GUI aimed at making chaining image processing tasks easy and customizable. Born as an AI upscaling application, chaiNNer has grown into an extremely flexible and powerful programmatic image processing application. 

**Metadata**

* homepage URL: https://chainner.app/
* source URL: https://github.com/chaiNNer-org/chaiNNer
* license: GPL-3.0
* platforms: unix, linux, darwin

**Comment by W-Y-R** [comment]
Hello! I’ve opened the same issue two months ago (see https://github.com/NixOS/nixpkgs/issues/280023). To avoid duplication, would you please close this issue? Thank you.
