### ISSUE TITLE
Systemctl timer failing Restic

### ISSUE THREAD

**Issue by Vcele** [NixOS/nixpkgs#289849]
### Describe the bug
Setting timerConfig in restic service leads to error. (I'm new to Nix please tell me if I made a configuration issue)

### Steps To Reproduce
1. set restic timer config for example to:
        `timerConfig = {
          onCalendar = "weekly";
          persistent = true;
        };`
3. execute `sudo systemctl status restic-[...].timer`
=> `Feb 18 22:16:46 [...] systemd[1]: /etc/systemd/system/restic-[...].timer:4: Unknown key name 'onCalendar' i>
           Feb 18 22:16:46 [...] systemd[1]: /etc/systemd/system/restic-[...].timer:5: Unknown key name 'persistent' i>
           Feb 18 22:16:46 [...] systemd[1]: restic-[...].timer: Timer unit lacks value setting. Refusing.`

### Expected behavior
Systemctl timer should run at expected time.

### Notify maintainers

@mbrgm @dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.20240217.84d981b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vojta001** [comment]
As the `timerConfig` is passed directly to systemd, the attrs have to be capitalized (unlike the majority of NixOS options). `timerConfig = { OnCalendar = "weekly"; Persistent = true; };` should work for you.

**Comment by Vcele** [comment]
Ah I see that works. Thanks 🙏
