### ISSUE TITLE
Enabling networking.networkmanager introduces 5s pause during boot

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#28987]
## Issue description

As per title the boot process stalls for 5 seconds, during that time no apparent activity occurs. After the pause the boot process continues as normal.
This appears to be a regression compared to 17.03 where I can't reproduce the issue.

### Steps to reproduce

1. Use the following configuration.nix:
  
    ```  
    { config, pkgs, ... }:
    {
     
      networking.networkmanager.enable = true;
      services.openssh.enable = true;
      users.extraUsers.pbogdan = {
         isNormalUser = true;
         uid = 1000;
         home = "/home/pbogdan";
         createHome = true;
         extraGroups = [ "wheel" ];
         password = "hunter2";
      };
    }

    ```
2. Build a VM:
  
    ```
    $ NIX_PATH="nixos-config=./configuration.nix:nixpkgs=https://nixos.org/channels/nixos-17.09/nixexprs.tar.xz" nixos-rebuild build-vm
    ```
3. Run the resulting VM and observe 5 seconds pause during boot.

## Technical details

* System: nixos-17.09beta43.0fd7ef61b2
* Nix version: 1.11.14
* Nixpkgs version: 17.09beta43.0fd7ef61b2
* Sandboxing enabled: no

**Comment by pbogdan** [comment]
It seems it's dbus that's hanging when trying to talk to nscd. The same issue gets triggered with hardware.pulseaudio.enable and here's what shows up in strace of dbus-daemon:

```
577   18:24:18.802532 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
577   18:24:18.802560 connect(6, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
577   18:24:18.802580 sendto(6, "\2\0\0\0\0\0\0\0\6\0\0\0pulse\0", 18, MSG_NOSIGNAL, NULL, 0) = 18
577   18:24:18.802602 poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 0 (Timeout)
577   18:24:23.807822 close(6)          = 0
```

I'm guessing that's somehow related to:

```
Unknown username "pulse" in message bus configuration file
```

message that appears in journalctl right after the pause.

**Comment by pbogdan** [comment]
git bisect points to 72a64ea4f1f32d77b1fd34eb07efc904ae415f6b as the first bad commit, and indeed with that reverted on top of recent 17.09 the issue goes away.
@peterhoeg - any ideas what could be going on?

**Comment by dezgeg** [comment]
Maybe `nscd.service` needs to be ordered before dbus-daemon?

**Comment by peterhoeg** [comment]
According to ```man nss-resolve```:

```
DNS queries are always routed via systemd-resolved(8) if it is running, but are routed to nss-dns if this service is not available.
```

I'm wondering if this lookup happens over dbus.

@pbogdan, can you try setting this:

```
services.dbus.socketActivated = true;
```

**Comment by Mic92** [comment]
But checking a user does not require dns, when no ldap etc is involved. I don't think this is the core problem.

**Comment by Mic92** [comment]
@pbogdan Can you get the strace from nscd also?

**Comment by pbogdan** [comment]
Yes, disabling nscd clears the issue. Managed to get a trace of nscd and it looks like @dezgeg is right in that dbus and nscd deadlock for 5 seconds because of nss-systemd and a non-existent user. The rough sequence of events seems to be:

- dbus starts up and sees "pulse" user in its configuration files
- dbus tries to get information about the user and reaches out to nscd
- the user doesn't exist on the system so the lookup eventually falls back to nss-systemd
- nss-systemd tries to lookup the dynamic user over dbus which hasn't fully started yet and is waiting for nscd

Excerpted from nscd trace:

```
[pid   575] 14:14:33.950871 read(14, "\2\0\0\0\0\0\0\0\6\0\0\0", 12) = 12
[pid   575] 14:14:33.950882 read(14, "pulse\0", 6) = 6
[pid   575] 14:14:33.950895 open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 15

...

[pid   575] 14:14:33.951079 open("/sys/fs/kdbus/0-system/bus", O_RDWR|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   575] 14:14:33.951096 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 15
[pid   575] 14:14:33.951110 getsockopt(15, SOL_SOCKET, SO_RCVBUF, [212992], [4]) = 0
[pid   575] 14:14:33.951122 setsockopt(15, SOL_SOCKET, SO_RCVBUFFORCE, [8388608], 4) = -1 EPERM (Operation not permitted)
[pid   575] 14:14:33.951133 setsockopt(15, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
[pid   575] 14:14:33.951143 getsockopt(15, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
[pid   575] 14:14:33.951153 setsockopt(15, SOL_SOCKET, SO_SNDBUFFORCE, [8388608], 4) = -1 EPERM (Operation not permitted)
[pid   575] 14:14:33.951163 setsockopt(15, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
[pid   575] 14:14:33.951173 connect(15, {sa_family=AF_UNIX, sun_path="/var/run/dbus/system_bus_socket"}, 33) = 0
[pid   575] 14:14:33.951189 getsockopt(15, SOL_SOCKET, SO_PEERCRED, {pid=1, uid=0, gid=0}, [12]) = 0
[pid   575] 14:14:33.951205 fstat(15, {st_dev=makedev(0, 8), st_ino=12855, st_mode=S_IFSOCK|0777, st_nlink=1, st_uid=499, st_gid=65534, st_blksize=4096, st_blocks=0, st_size=0, st_atime=0, st_atime_nsec=0, st_m
time=0, st_mtime_nsec=0, st_ctime=0, st_ctime_nsec=0}) = 0
[pid   575] 14:14:33.951218 getsockopt(15, SOL_SOCKET, SO_ACCEPTCONN, [0], [4]) = 0
[pid   575] 14:14:33.951228 getsockname(15, {sa_family=AF_UNIX}, [128->2]) = 0
[pid   575] 14:14:33.951239 geteuid()   = 499
[pid   575] 14:14:33.951249 sendmsg(15, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0AUTH EXTERNAL ", iov_len=15}, {iov_base="343939", iov_len=6}, {iov_base="\r\nNEGOTIATE_UNIX_FD\r\nBEGIN\r\n", iov_len
=28}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 49

....

[pid   575] 14:14:33.951390 ppoll([{fd=15, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999814000}, NULL, 8 <unfinished ...>                                                                                          
[pid   575] 14:14:38.973394 <... ppoll resumed> ) = 1 ([{fd=15, revents=POLLIN}], left {tv_sec=19, tv_nsec=977822165})                                                                                           
[pid   575] 14:14:38.973407 getpid()    = 558                                                                                                                                                                    
[pid   575] 14:14:38.973418 recvmsg(15, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="OK 1795af28e45ada84bca0560059b002ce\r\nAGREE_UNIX_FD\r\n", iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 52

...

[pid   575] 14:14:38.974607 sendmsg(15, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\n\0\0\0\2\0\0\0\247\0\0\0\1\1o\0\31\0\0\0/org/freedesktop/systemd1\0\0\0\0\0\0\0\3\1s\0\27\0\0\0LookupDynamicUserByName\0\2\1s\0 \0\0\0org.freedesktop.systemd1.Manager\0\0\0\0\0\0\0\0\6\1s\0\30\0\0\0org.freedesktop.systemd1\0\0\0\0\0\0\0\0\10\1g\0\1s\0\0", iov_len=184}, {iov_base="\5\0\0\0pulse\0", iov_len=10}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 194
```

**Comment by dezgeg** [comment]
So does this `pulse` user not exist in `/etc/passwd`? Sounds like it should:
````
257     (mkIf systemWide {
258       users.extraUsers.pulse = {
259         # For some reason, PulseAudio wants UID == GID.
260         uid = assert uid == gid; uid;
261         group = "pulse";
262         extraGroups = [ "audio" ];
263         description = "PulseAudio system service user";
264         home = stateDir;
265         createHome = true;
266       };
267 
````

**Comment by pbogdan** [comment]
No, it doesn't, I believe `systemWide` defaults to false. Neither does `nm-openconnect` user for the network manager case.

**Comment by peterhoeg** [comment]
The dbus configuration file still mentions the user (and also mentions it is not used for user instances), so we really need to create the user unconditionally.

**Comment by pbogdan** [comment]
Would it make sense to remove nscd as part of `nss-lookup.target` and `nss-user-lookup.target` - https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/system/nscd.nix#L52 - and start it later in the boot process? As I understand it it's supposed to be a cache which shouldn't be required for either of those unless nscd provides some unique functionality beyond just caching.

**Comment by dezgeg** [comment]
No, all NSS accesses except the built-in ones (like `files` which looks up in `/etc/passwd`) only work via `nscd` (since there is no global place like `/lib/libnss_foo.so` to install modules to).

**Comment by peterhoeg** [comment]
Was this closed in error? It seems like we need to create the user unconditionally.
