### ISSUE TITLE
Package request: magika

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#289843]
**Project description**

Magika is a tool to detect common file content types, using deep learning. 

**Metadata**

* homepage URL: https://google.github.io/magika/
* source URL: https://github.com/google/magika
* license: apache-2.0
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/291462

**Comment by mihaimaruseac** [comment]
Oh, I did not notice this issue was created. Lucky coincidence

Thanks for linking PR and issue together

**Comment by mihaimaruseac** [comment]
#91462 is now merged (thank you!), I think this can be closed?
