### ISSUE TITLE
Build failure: pynitrokey (spsdk)

### ISSUE THREAD

**Issue by marzipankaiser** [NixOS/nixpkgs#289860]
### Steps To Reproduce

1. build *pynitrokey* -> `nix-shell -p pynitrokey`

### Build log

```
error: builder for '/nix/store/x4j8mjwgqryhbjlyw6ksfa1yhq7zbcly-python3.11-spsdk-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Finished creating a wheel...
       > /build/source/dist /build/source
       > Unpacking to: unpacked/spsdk-2.0.1...OK
       > Repacking wheel as ./spsdk-2.0.1-py3-none-any.whl...OK
       > /build/source
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for spsdk-2.0.1-py3-none-any.whl
       >   - cryptography<41.1,>=3.4.4 not satisfied by version 42.0.2
       For full logs, run 'nix log /nix/store/x4j8mjwgqryhbjlyw6ksfa1yhq7zbcly-python3.11-spsdk-2.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/dnhhas2nx6162qp43nm1qb0vc3rg62y1-python3.11-pynitrokey-0.4.45.drv' failed to build
```

### Additional context

Seems similar to previous [#235251](https://github.com/NixOS/nixpkgs/issues/235251), [#204333](https://github.com/NixOS/nixpkgs/issues/204333)

### Notify maintainers
@frogamic 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(gaisseml): `""`
 - nixpkgs: `/nix/store/cs2gyz1sh1xxpkn0hn9z7gxxsbahwfpw-src/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by frogamic** [comment]
I'm really hoping this makes it into a release branch soon and fixes pynitrokey: https://github.com/Nitrokey/pynitrokey/pull/499
