### ISSUE TITLE
Build failure: geogebra and geogebra6

### ISSUE THREAD

**Issue by LDprg** [NixOS/nixpkgs#289990]
### Steps To Reproduce

1. build geogebra or geogebra6

### Build log

```
last 7 log lines:
       >
       > trying http://static.geogebra.org/images/geogebra-logo.svg
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0   196    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download geogebra-logo.svg from any mirror
```

### Additional context

Well just the icon dowload path is not availaible anymore.

### Notify maintainers

@voidIess 
@sikmir 
@soupglasses 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.1, NixOS, 23.11 (Tapir), 23.11.20240124.a77ab16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/5hwz775f3grzikafj1sbwx4lqkjwqswb-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by voidIess** [comment]
static.geogebra.org seems to serve no content anymore. Gone fix it by using archive.org for now
