### ISSUE TITLE
Update request: ArchiSteamFarm 5.5.0.11 → 5.5.2.3

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#289950]
https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.2.3

- Package name: ArchiSteamFarm
- Latest released version: 5.5.2.3

- Current version on the unstable channel: 5.5.0.11
- Current version on the stable/release channel: 5.4.12.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
It helps if I also open the PR when doing the update 😂 

#289956
