### ISSUE TITLE
Build failure: python311Packages.fairseq

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#290093]
### Steps To Reproduce

1. `nix-build -A python311Packages.fairseq` on master

### Build log

https://hydra.nixos.org/build/250198377

### Additional context

Has been failing since 2023-11-21.

### Notify maintainers

@happysalada 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
Hey thanks for reaching out, i should have some time this weekend to have a look at this!
