### ISSUE TITLE
diffusers: checkPhase is extremely resource intensive

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#290055]
diffusers builtin tests are slow, very cpu intensive and use a fair chunk of RAM. I've been running it for about an hour on a 32 core system and it's using all cores.

Is there an easy way to make these part of passthru.tests instead of the checkPhase so they're not built on every rebuild?

cc maintainer @natsukium

**Comment by pbsds** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/d2767bbd2432456c825aeb3edc64c6e68d593486
