### ISSUE TITLE
tigervnc references /usr/bin/ssh for launching tunnel

### ISSUE THREAD

**Issue by jasom** [NixOS/nixpkgs#29003]
## Issue description

The tigerVNC vnc client can tunnel over ssh, but does so defaulting to /usr/bin/ssh as the path to the ssh client

### Steps to reproduce

    tigervnc -via user@host localhost:0

Will display `sh: /usr/bin/ssh: No such file or directory`

## Technical details

* System: NixOS 17.03.1775.56da88a298 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version:17.03.1775.56da88a298
* Sandboxing enabled: false

**Comment by vyp** [comment]
Does adding either `-SSHClient /run/current-system/sw/bin/ssh` or `-extSSHClient /run/current-system/sw/bin/ssh` to the command work?

**Comment by jasom** [comment]
@vyp I didn't try that, but `VNC_VIA_CMD='/run/current-system/sw/bin/ssh -f -L "$L":"$H":"$R" "$G" sleep 20` does work, which is the documented way of handling this.

**Comment by vyp** [comment]
I see, where is that documented?

The reason I asked that is because it seemed like `/usr/bin/ssh` was set as a default parameter value [here](https://github.com/TigerVNC/tigervnc/blob/82e753d4e1928342c82cc7b82e854aa2666d1145/java/com/tigervnc/vncviewer/Parameters.java#L232), so I thought this could just be patched in nixpkgs.

**Comment by Mic92** [comment]
Just add to the package and make a pull request:

```
prePatch = ''
  substituteInPlace ava/com/tigervnc/vncviewer/Parameters.java \
   --replace '/usr/bin/ssh' '${ssh}/bin/ssh'
''
```

**Comment by jasom** [comment]
@vyp It's documented in the tigervnc manpage for vncviewer.

I'm 99% certain it's not in that Java file, but in this C++ file:

https://github.com/TigerVNC/tigervnc/blob/82e753d4e1928342c82cc7b82e854aa2666d1145/vncviewer/vncviewer.cxx#L422

**Comment by vyp** [comment]
@jasom import `openssh` and try the following:

``` nix
postPatch = ''
  substituteInPlace vncviewer/vncviewer.cxx \
   --replace '"/usr/bin/ssh' '"${openssh}/bin/ssh'
''
```
