### ISSUE TITLE
Add package: Skanlite – KDE image scanning application

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#29005]
## Issue description

[Skanlite](https://www.kde.org/applications/graphics/skanlite/) package is missing in NixOS.

This package provides KDE’s frontend to SANE and therefore a nice app to scan images. I propose to include it.

### Steps to reproduce

1. Search for Skanlite or try to install it.
2. Fail

## Technical details

* System: NixOS: 17.09beta43.0fd7ef61b2 (Hummingbird)
* Nix version: 1.11.14
* Nixpkgs version: 17.09beta43.0fd7ef61b2
* Sandboxing enabled: false

**Comment by peterhoeg** [comment]
Whoever grabs this also needs to package ```libksane``` before skanlite will work.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding this package here.

**Comment by silverhook** [comment]
Just so I know for future reference …the issue tracker is _not_ a place for package requests, unless you provide a PR with it?

**Comment by FRidh** [comment]
@silverhook it is indeed not a place for package requests.

**Comment by silverhook** [comment]
@FRidh Ah, good to know. I apologise then.

Is there any place for package requests at all or is it all on a PR-or-get-out basis? ;)

**Comment by FRidh** [comment]
There's no place for package requests, really. You could ask on the NixOS channel if people could help you with it but in the end you need to do it yourself. The maintainers are swamped already.

**Comment by silverhook** [comment]
Sounds fair and good to know, so I don’t spam here. It won’t hurt me to try write some packages again :)

**Comment by pshendry** [comment]
I was looking for skanlite too this afternoon, and I tried my hand at packaging it up. See #29060 

@silverhook I don't actually have access to a scanner right now so it'd be a huge help if you could try out the package and make sure everything's working. All I was able to confirm was that it launches 😛

**Comment by silverhook** [comment]
@pshendry Very happy to! I hope to take it for a spin this week, probably sooner than later.
