### ISSUE TITLE
Package request: virtualbox-kvm

### ISSUE THREAD

**Issue by batonac** [NixOS/nixpkgs#290039]
VirtualBox with KVM Backend. This enables the use of VirtualBox as a frontend to KVM, without the need for any VirtualBox-specific kernel modules.

From the README:

- VirtualBox can run in parallel to QEMU/KVM
- VirtualBox kernel driver (vboxdrv) is not required
- Modern virtualization features supported by KVM are automatically used (e.g. APICv)
- KVM is part of the Linux kernel and therefore always directly available with every kernel update

**Metadata**

* source URL: https://github.com/cyberus-technology/virtualbox-kvm
* license: gpl2+
* platforms: linux

**Comment by blitz** [comment]
Virtualbox KVM has been packaged as `pkgs.virtualboxKvm` in unstable. You can also use:

```
virtualisation.virtualbox.host = {
  enable = true;
  enableKvm = true;

  enableHardening = false;
  addNetworkInterface = false;
}
```
