### ISSUE TITLE
Byobu has permanently moved development to GitHub 

### ISSUE THREAD

**Issue by Jason-nz** [NixOS/nixpkgs#290168]
- Package name: Byobu
- Latest released version: 6.12

- Current version on the unstable channel: 5.133
- Current version on the stable/release channel: 5.133

Byobu development has permanently moved from Launchpad to GitHub
[https://bazaar.launchpad.net/~kirkland/byobu/trunk/revision/2646](url)
[https://github.com/dustinkirkland/byobu](url)

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Chaostheorie** [comment]
pinging @qknight and @berbiche as maintainers
