### ISSUE TITLE
security.lockKernelModules hides(?) /boot device

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#29019]
## Issue description
So I enabled `security.lockKernelModules`...
The system boots fine but `nixos-rebuild` becomes entirely unusable because the device supposed to be mounted to `/boot` is somehow gone (I get `No such device` with an error code 19).

I assume that adding some module can fix this but I have two issues:

- What is that module?
- Why is it not added by default?

Here is my journal for when it fails:

```
Sep 05 07:50:07 nixus nix-daemon[2084]: accepted connection from pid 3064, user root (trusted)
Sep 05 07:50:07 nixus nix-daemon[2084]: accepted connection from pid 3079, user root (trusted)
Sep 05 07:50:10 nixus nix-daemon[2084]: accepted connection from pid 3085, user root (trusted)
Sep 05 07:50:12 nixus nix-daemon[2084]: accepted connection from pid 3965, user root (trusted)
Sep 05 07:50:12 nixus systemd[1]: boot.automount: Got automount request for /boot, triggered by 3972 (pbxy00fxvjniqw4)
Sep 05 07:50:12 nixus systemd[1]: Mounting EFI System Partition Automount...
Sep 05 07:50:12 nixus systemd[1]: boot.mount: Mount process exited, code=exited status=32
Sep 05 07:50:12 nixus systemd[1]: Failed to mount EFI System Partition Automount.
Sep 05 07:50:12 nixus systemd[1]: boot.mount: Unit entered failed state.
Sep 05 07:50:12 nixus systemd[1]: boot.automount: Got automount request for /boot, triggered by 3972 (pbxy00fxvjniqw4)
Sep 05 07:50:12 nixus systemd[1]: Mounting EFI System Partition Automount...
Sep 05 07:50:12 nixus systemd[1]: boot.mount: Mount process exited, code=exited status=32
Sep 05 07:50:12 nixus systemd[1]: Failed to mount EFI System Partition Automount.
Sep 05 07:50:12 nixus systemd[1]: boot.mount: Unit entered failed state.
Sep 05 07:50:28 nixus systemd[1]: boot.automount: Got automount request for /boot, triggered by 4029 (exa)
Sep 05 07:50:28 nixus systemd[1]: Mounting EFI System Partition Automount...
Sep 05 07:50:28 nixus systemd[1]: boot.mount: Mount process exited, code=exited status=32
Sep 05 07:50:28 nixus systemd[1]: Failed to mount EFI System Partition Automount.
Sep 05 07:50:28 nixus systemd[1]: boot.mount: Unit entered failed state.
Sep 05 07:51:04 nixus systemd[1]: boot.automount: Got automount request for /boot, triggered by 4236 (exa)
Sep 05 07:51:04 nixus systemd[1]: Mounting EFI System Partition Automount...
Sep 05 07:51:04 nixus systemd[1]: boot.mount: Mount process exited, code=exited status=32
Sep 05 07:51:04 nixus systemd[1]: Failed to mount EFI System Partition Automount.
Sep 05 07:51:04 nixus systemd[1]: boot.mount: Unit entered failed state.
Sep 05 07:51:08 nixus xsession[1601]: 1504612268700        addons.webextension.2.0@disconnect.me        WARN        Please specify whether you want browser_style or not in your browser_action options.
Sep 05 07:51:11 nixus xsession[1601]: Extension error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getCharPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///home/nequi/.mozilla/firefox/zmb0eif1.default/extensions/@testpilot-addon.xpi!/bootstrap.js :: sendInitialPrefs :: line 753"  data: no] undefined 753
Sep 05 07:51:11 nixus xsession[1601]: [[Exception stack
Sep 05 07:51:11 nixus xsession[1601]: sendInitialPrefs@jar:file:///home/nequi/.mozilla/firefox/zmb0eif1.default/extensions/@testpilot-addon.xpi!/bootstrap.js:753:23
```

### Steps to reproduce

- Enable `security.lockKernelModules` in `configuration.nix`
- `nixos-rebuild boot && boot`
- Disable `security.lockKernelModules` in `configuration.nix`
- `nixos-rebuild boot && boot` <-- Won't work

## Technical details

* System: 17.09pre114257.6b95cf646c (Hummingbird)
* Nix version:nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre114257.6b95cf646c
* Sandboxing enabled: build-use-sandbox = true

Ping @joachifm

**Comment by edolstra** [comment]
Probably you need `fat` and `vfat` preloaded.

I guess we could try to add all modules required by known filesystems, similar to what we already do for filesystems required in the initrd (see e.g. `nixos/modules/tasks/filesystems/vfat.nix`).

**Comment by dezgeg** [comment]
Or the systemd unit that `lockKernelModules` runs could be ordered better.

**Comment by joachifm** [comment]
@dezgeg I'm interested in improving the ordering. Can you elaborate? I'm unsure how ordering relates to this problem, as the unit is activated after `multi-user.target`, so I'd expect it to run after all filesystems that are part of normal startup have been mounted. Is that not the case? 

Not being able to mount other filesystems (whose modules are not already loaded) once the system has entered normal operation is expected. I'd like to add filesystem modules per @edolstra's suggestion (maybe there could be a `system.fsModules` to complement `system.fsPackages`, but then again this is a fairly niche problem so perhaps not worth it).

**Comment by dezgeg** [comment]
I have a recollection of that if a `/boot` mountpoint is specified incorrectly, the system seemingly boots to the terminal successfully, but once the mount unit times out, it throws you to emergency mode. I thought that would imply that there is a `Requires` dependency but no `After` dependency from `boot.mount` -> `multi-user.target`. But admittedly I am not too familiar on the finer points of unit ordering on systemd. 

But now that I look at the error again:
````
Sep 05 07:50:12 nixus systemd[1]: boot.automount: Got automount request for /boot, triggered by 3972 (pbxy00fxvjniqw4)
Sep 05 07:50:12 nixus systemd[1]: Mounting EFI System Partition Automount...
````
It looks like it's coming from an auto-generated automount unit, not from something in `fileSystems."/boot"` at all...

**Comment by joachifm** [comment]
@NeQuissimus can you elaborate a little bit on how your `fileSystems` is setup?

**Comment by NeQuissimus** [comment]
@joachifm Absolutely: https://github.com/NeQuissimus/DevSetup/blob/master/ux305c-hardware.nix :D Basically the simplest possible setup :)

https://github.com/NeQuissimus/DevSetup/blob/master/ux305c.nix has the rest of my config, including my LUKS setup

**Comment by joachifm** [comment]
@NeQuissimus thank you. I'm a little unsure why there would be an automount here, seems like `/boot` would be mounted during startup under this config.  Does the module listing actually include `vfat`, `nls-cp437`, and `nls-iso8859-1` before the rebuild? If so, that'd be quite surprising. Anyway, I'm working on deferred mounts/declared automounts, hopefully will manage to get it in before release.

**Comment by joachifm** [comment]
I've implemented a pushed some changes that at least fixes the problem in a vm test.

**Comment by NeQuissimus** [comment]
@joachifm I will try it out and let you know how it went for me

**Comment by NeQuissimus** [comment]
Seems to work fine, I can `ls /boot` again and `nixos-rebuild` also works after enabling `security.lockKernelModules`

**Comment by joachifm** [comment]
@NeQuissimus that's great. Thank you for testing :)

**Comment by NeQuissimus** [comment]
@joachifm Bad news:

```
λ sudo ls /boot
ls: cannot open directory '/boot': No such device
```

Did you not cherry-pick to 17.09? I switched from master onto stable...

**Comment by joachifm** [comment]
Are the modules loaded or not? What is the sequence of commands upto that error?

**Comment by NeQuissimus** [comment]
I did nothing but log in and open a terminal, let me pull my module list...

**Comment by NeQuissimus** [comment]
Ah, you know... Friday is not my favourite day of the week...
Once I actually add vfat, nls-cp437 and nls-iso8859-1 to my `kernelModules`, it is all good.
I must have removed them at some point...

**Comment by joachifm** [comment]
Did you switch into the configuration from a non-locked state or boot into a new configuration with that option enabled? If the latter it should work because you should have all the required modules loaded but in the former case it might not work, depending on whether you had the requisite modules already loaded.

Switching into a configuration with this option enabled without also having already loaded all requisite kernel modules will break anything that depends on those kernel modules until reboot. Worst case scenario is you need to boot into an older generation.

I recommend testing in a vm before booting into the configuration and certainly never switch into it without being certain that you have all kernel modules you need already loaded (and that they won't be unloaded for some reason during switching).

**Comment by NeQuissimus** [comment]
I had it unlock, enabled it, did `nixos-rebuild boot --upgrade && reboot` and then ran the `sudo ls /boot`.
Should the module auto-load the modules maybe?

**Comment by joachifm** [comment]
Ah, comment race :) Well, I'm a little confused why the module does not add the requisite kernel modules itself, it should do so if any `fileSystems` has type vfat. That was the "fix" for the deferred mounts issue.

**Comment by NeQuissimus** [comment]
I don't have a `fileSystem` that is vfat, that is why!
`boot.loader.systemd-boot.enable = true;` does the `/boot` stuff for me.

**Comment by NeQuissimus** [comment]
```
λ mount | grep '/boot'                                                                                                                                         
systemd-1 on /boot type autofs (rw,relatime,fd=28,pgrp=1,timeout=120,minproto=5,maxproto=5,direct)
```

**Comment by joachifm** [comment]
Aha, that explains the reference to automount in the original error message

**Comment by joachifm** [comment]
I hope the fix will be to also consider systemd.automounts when selecting fs modules to include.

**Comment by NeQuissimus** [comment]
I have to run now, otherwise I would take a look. If you have anything, let me know and I'll try it out. Or maybe on the weekend I may take a jab at it.

**Comment by NeQuissimus** [comment]
In case anybody runs into issues with Docker (17.09-ce right now) with this:

```
boot.initrd.kernelModules = [
  "aufs"
  "bridge"
  "br_netfilter"
  "nf_nat"
  "veth"
  "xt_conntrack"
  "xt_nat"
];
```
