### ISSUE TITLE
Update request: mixxx 2.3.6 → 2.4.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#290215]
- Package name: mixxx
- Latest released version: 2.4.0
- Current version on the unstable channel: 2.3.6
- Current version on the stable/release channel: 2.3.5 
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@cillianderoiste  
@bfortz

https://github.com/mixxxdj/mixxx/blob/2.4.0/CHANGELOG.md

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arximboldi** [comment]
2.4.1 is now out, pinging:
@cillianderoiste
@bfortz

**Comment by benley** [comment]
> 2.4.1 is now out

https://github.com/NixOS/nixpkgs/pull/314366
