### ISSUE TITLE
Package request: `hyprlock`

### ISSUE THREAD

**Issue by eureka-cpu** [NixOS/nixpkgs#290334]
**Project description**

Hyprland lock screen utility

**Metadata**

* homepage URL: https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/
* source URL: https://github.com/hyprwm/hyprlock/tree/main
* license: BSD3
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by detroyejr** [comment]
The repository does already include a [flake/derivation/home-manager module.](https://github.com/hyprwm/hyprlock/tree/main/nix)

I'm using flakes and was able to get this up and running by adding hyprlock as a flake input, using the home-manager import mechanism, and then setting `programs.hyprlock.enable = true;`.

In other words, my flake.nix file has:
```
inputs = {
    hyprlock.url = "github:hyprwm/Hyprlock";
    # ... all other inputs
};
outputs = { nixpkgs, home-manager, nixos-hardware, hyprland, hyprlock, ... }:

```

Then I've got a NixOS system defined:

```
      nixosConfigurations.xps = nixpkgs.lib.nixosSystem {
         # ... options for this system. You just need to tell home manager to import 
         # hyprlock so it can be used in your config.
         modules = [
          home-manager.nixosModules.home-manager
          {
            home-manager.users.myUser = {
              imports = [
                ...
                hyprlock.homeManagerModules.hyprlock
              ];
            };
          }
        ];
      };
```
That was enough for `programs.hyprlock.enable` to work.

**Comment by eureka-cpu** [comment]
oh nice, thanks @detroyejr !

**Comment by GersiD** [comment]
This was closed as completed but hyprlock is not available via pkgs, maybe I am misunderstanding but I believe OP was asking for hyprlock to be available via pkgs.

**Comment by jnsgruk** [comment]
Hey!

It is available on `unstable`: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=Hyprlock
