### ISSUE TITLE
Fractal "No apps available" when opening links.

### ISSUE THREAD

**Issue by jh-devv** [NixOS/nixpkgs#290370]
Hey!

### Describe the bug
When opening the links in Fractal, it always just says "No apps available"

### Steps To Reproduce
1. Click on a link
2. Get popup

### Expected behavior
Should just open the link in the web browser

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/122896463/45bd7480-7eab-4201-8e21-ddcb472cfb0a)

### Additional context

`xdg-open example.com` works and all the mime apps should be set.
This is on Hyprland with `xdg-desktop-portal-gtk` and `xdg-desktop-portal-hyprland`.
Hyprland is from their flake.

*You can find my system flake [here](https://github.com/jh-devv/luminara)!*
*Respective modules:*
*- [github.com/jh-devv/luminara/modules/nixos/desktop/hyprland/default.nix](https://github.com/jh-devv/luminara/blob/32e1603f577ae643b2d8f6c29285f8703cd05758/modules/nixos/desktop/hyprland/default.nix)*
*- [github.com/jh-devv/luminara/modules/home/desktop/xdg.nix](https://github.com/jh-devv/luminara/blob/672a65360f4f81f974021310190967e5493d94e7/modules/home/desktop/xdg.nix)*

### Notify maintainers

@schuelermine @dtzWill

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[jh-devv@luminara:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 24.05 (Uakari), 24.05.20240216.5863c27`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/bg5fbkfa5x53clcjf4p5p92k1l3w8x38-source`
```

---

Sincerely: jh-devv <jh-devv@jh-devv.com>

**Comment by jh-devv** [comment]
Maybe related: https://github.com/NixOS/nixpkgs/issues/189851#issuecomment-1238907955

**Comment by uninsane** [comment]
in addition to what's mentioned in 189851, you also need to make sure that `xdg-desktop-portal` is fully mime aware. in particular, **make sure that share/applications/mimeinfo.cache exists** (with entries for x-scheme-handler/http(s)) on one of the `$XDG_DATA_DIRS` paths. and make sure `xdg-desktop-portal` has in its environment `XDG_DATA_DIRS` which would let it find such a file (because if you haven't imported it to the systemd/dbus environment, it probably won't. and if you import it after it's already been started, it won't).

you can try `systemd --user status xdg-desktop-portal` to find the PID, and then `cat /proc/$THAT_PID/environ` to query its `XDG_DATA_DIRS`.

**Comment by jh-devv** [comment]
> in addition to what's mentioned in 189851, you also need to make sure that `xdg-desktop-portal` is fully mime aware. in particular, **make sure that share/applications/mimeinfo.cache exists** (with entries for x-scheme-handler/http(s)) on one of the `$XDG_DATA_DIRS` paths. and make sure `xdg-desktop-portal` has in its environment `XDG_DATA_DIRS` which would let it find such a file (because if you haven't imported it to the systemd/dbus environment, it probably won't. and if you import it after it's already been started, it won't).
> 
> you can try `systemd --user status xdg-desktop-portal` to find the PID, and then `cat /proc/$THAT_PID/environ` to query its `XDG_DATA_DIRS`.

Thanks! I will be sure to try these!

**Comment by jh-devv** [comment]
Oh, this was an issue with `xdg-desktop-portal-gtk`

**Comment by uninsane** [comment]
> Oh, this was an issue with `xdg-desktop-portal-gtk`

@jh-devv if you have a moment, mind summarizing what the fix was? might help the next person who encounters this, especially given how murky the situation still is over at 189851
