### ISSUE TITLE
Package request: vscode-extensions.reditorsupport.r

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#290471]
**Project description**

Adds R language features (e.g. syntax highlighting) to VSCode. Ideally, would also install `python311Packages.radian` and automatically configure the extension to use them. Also requires  `rPackages.languageserver` to be installed.

**Metadata**

* homepage URL: https://marketplace.visualstudio.com/items?itemName=REditorSupport.r
* source URL: https://github.com/REditorSupport/vscode-R
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
Just open a PR adding the extension, much easier than opening an issue...

**Comment by Pandapip1** [comment]
> Just open a PR adding the extension, much easier than opening an issue...

If it's that easy, why don't you do it youself?

Okay, sorry for being a little snarky there. But I opened this issue the same day I first installed NixOS, so please forgive my former lack of knowledge. I'll take a look.

**Comment by superherointj** [comment]
> If it's that easy, why don't you do it yourself?

I don't need this extension specifically. But I have added all the extensions I needed.

> Okay, sorry for being a little snarky there. But I opened this issue the same day I first installed NixOS, so please forgive my former lack of knowledge. 

Sure.

> I'll take a look.

Have a look in:
https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/vscode/extensions/

Follow README.md and add extension to default.nix.

Git clone nixpkgs. Then, to build your extension, run:
> nix build .#vscode-extension.publisher.extension-name

Look forward your first PR then.

Have fun.

**Comment by Pandapip1** [comment]
> Look forward your first PR then.

Small nit: It won't be my first PR (https://github.com/NixOS/nixpkgs/pull/304323, https://github.com/NixOS/nixpkgs/pull/303716, https://github.com/NixOS/nixpkgs/pull/298083, https://github.com/NixOS/nixpkgs/pull/292639, https://github.com/NixOS/nixpkgs/pull/294104). It will be my first package creation, though!
