### ISSUE TITLE
Package request: vscode-extensions.vue.volar

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#290468]
**Project description**

A VSCode extension that adds Vue.js language syntax highlighting.

**Metadata**

* homepage URL: https://marketplace.visualstudio.com/items?itemName=Vue.volar
* source URL: https://github.com/vuejs/language-tools
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Pandapip1** [comment]
Whoops, that was the typescript + vue support plugin, not the main VueJS one.

**Comment by superherointj** [comment]
Just open a PR adding the extension, much easier than opening an issue...

**Comment by Pandapip1** [comment]
Please see https://github.com/NixOS/nixpkgs/issues/290471#issuecomment-2088628067
