### ISSUE TITLE
kdenetwork-filesharing does not work in dolphin

### ISSUE THREAD

**Issue by abeforgit** [NixOS/nixpkgs#290515]
### Describe the bug
As described at https://apps.kde.org/kdenetwork_filesharing/ this app is supposed to enable the "share" screen of file properties in dolphin. For me this doesn't work: the "share" tab is available but it is empty.

As far as I can tell I have set up samba and usershares correctly, as I'm able to make new usershares and connect to other hosts on the network using the command line tools. 
Usershares I make also show up as expected in the "samba status" app.

### Steps To Reproduce
1. install the kdenetwork_filesharing package in a KDE environment
2. open up dolphin and right-click a folder (not a symlink)
3. choose "properties"
4. go to the "share" tab
5. observe it is empty

### Expected behavior
I expect the share tab to contain similar options as shown at https://apps.kde.org/kdenetwork_filesharing/

### Screenshots
the empty "share" tab:

![image](https://github.com/NixOS/nixpkgs/assets/16419862/859163fe-e2b0-49f9-8df0-05bd62d90dab)

the usershares showing up correctly in the "samba status" app:

![image](https://github.com/NixOS/nixpkgs/assets/16419862/cd666bbc-9551-4fa7-a47d-5c06adf5b4c9)

### Additional context

When launching dolphin from the command line, I get the following output when accessing the "file properties":

```
true
actions!!!
QQmlComponent: Component is not ready
qrc:/org.kde.filesharing.samba/qml/main.qml:12:1: QML StackView: push: qrc:/org.kde.filesharing.samba/qml/MissingSambaPage.qml:18 Cannot assign to non-existent property "explanation"
```

To me this seems to be trying to render the missing samba page and somehow failing. From looking around I noticed that the plugin has a feature to let you install samba if you don't have it, for less ehm "strict" OSes. This could mean that despite my efforts it still doesn't find samba, and that resolving that will resolve the issue. 

### Notify maintainers

@ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/yq9qag5ak3w15nhcqplnhxpny6295l36-stdenv-linux
copying path '/nix/store/yq9qag5ak3w15nhcqplnhxpny6295l36-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gzf4zwcakda1nykn6h0avh45xhjhvsz4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Correct, I've got a fix for this that I'll push to the Plasma 6 branch in a bit.

**Comment by K900** [comment]
Pushed now.

**Comment by cab404** [comment]
Still doesn't work, but differently. Prompts for a password change, and if you enter it, nothing happens.
![image](https://github.com/NixOS/nixpkgs/assets/6453661/79efa977-28b6-4de7-8753-8c637d87aa97)

Also, Windows Shares tab whines on kio qt being wrong version
![image](https://github.com/NixOS/nixpkgs/assets/6453661/df2cfa6c-7f00-4eed-905b-b91fdede1c12)
```
Could not load plugin from /nix/store/phqwx5gxccib9kzsprklrj8m8h68nwk4-kio-5.115.0/lib/qt-5.15.12/plugins/plasma/kcms/systemsettings/kcm_smb.so: The plugin '/nix/store/phqwx5gxccib9kzsprklrj8m8h68nwk4-kio-5.115.0/lib/qt-5.15.12/plugins/plasma/kcms/systemsettings/kcm_smb.so' uses incompatible Qt library. (5.15.0) [release]
```

**Comment by Ilya-JBR** [comment]
This still doesn't works

**Comment by K900** [comment]
Extremely unlikely. If you're still seeing this, open a new issue please.
