### ISSUE TITLE
Update request: gegl 0.4.46 → 0.4.48

### ISSUE THREAD

**Issue by 9p4** [NixOS/nixpkgs#290505]
- Package name: gegl
- Latest released version: 0.4.48

- Current version on the unstable channel: 0.4.46
- Current version on the stable/release channel: 0.4.46

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jtojnar

I can take over the package if you wish.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
If you are able to bump the package (and babl), feel free. I probably will not be able to get to it this week.
