### ISSUE TITLE
Nix says to add the wrong package name to the allowUnfreePredicate list

### ISSUE THREAD

**Issue by BlitDev** [NixOS/nixpkgs#290576]
### Describe the bug
![image](https://github.com/NixOS/nixpkgs/assets/79034202/90ce9dca-35d8-40b1-aa67-dfd572bb217b)
Nix says to add "**steam-original-1.0.0.0.74**" to the **allowUnfreePredicate** list, but only "**steam-original**" actually works.

### Steps To Reproduce
1. Add 
![image](https://github.com/NixOS/nixpkgs/assets/79034202/fafa91e4-0003-43ca-acee-cfc82f730479)
into config
2. Get an error while rebuilding the system.

### Expected behavior
Nix should say to add the package name **without version** to the **allowUnfreePredicate** list.

### Additional context
I'm using flakes.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.5-gnu, NixOS, 24.05 (Uakari), 24.05.20240221.0e74ca9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lolbinarycat** [comment]
in the future, please copy/paste the error message into a code block instead of screenshotting it, i had to retype the error message to find the offending code.

**Comment by lolbinarycat** [comment]
offending line is [pkgs/stdenv/generic/check-meta.nix:184](https://github.com/NixOS/nixpkgs/blob/bbabfca453cdf16844f3140766f6d678abbc853f/pkgs/stdenv/generic/check-meta.nix#L184)

i'm not sure if i want to fix this right now, i'm unsure if every package has pname set
