### ISSUE TITLE
KDE - no audio devices listed

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#29056]
## Issue description

Using current unstable of nixos and I noticed, that with the current 18.03 there are no audio devices listed in the KDE Multimedia systemsettings.

Screenshot: https://images.sjau.ch/img/a1ea5b00.png

However, running pactl list short sources from the cli shows them all:

```
hyper@subi:~$ pactl list short sources
0       alsa_output.pci-0000_00_03.0.hdmi-stereo.monitor        module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
1       alsa_output.usb-Logitech_Logitech_Wireless_Headset_88C626973B0E-00.analog-stereo.monitor        module-alsa-card.c      s16le 2ch 48000Hz       SUSPENDED
2       alsa_input.usb-Logitech_Logitech_Wireless_Headset_88C626973B0E-00.analog-mono   module-alsa-card.c      s16le 1ch 48000Hz       SUSPENDED
3       alsa_output.pci-0000_00_1b.0.analog-stereo.monitor      module-alsa-card.c      s16le 2ch 48000Hz       SUSPENDED
4       alsa_input.pci-0000_00_1b.0.analog-stereo       module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
```

Also, the KDE Multimedia settings do not have any backend enabled. I also tried to add 
```phonon-backend-gstreamer```
to my configuration.nix but it didn't change anything.

### Steps to reproduce

Use this configuration.nix to get KDE etc. installed: https://github.com/sjau/nixos/blob/master/configuration.nix

Open Kicker -> type "systemsettings" -> got to Multimedia -> Select "Audio and Video"

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

18.03pre114421.799435b7ca (Impala)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.14

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"18.03pre114421.799435b7ca"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

build-use-sandbox = false

**Comment by globin** [comment]
cc @ttuegel

**Comment by sjau** [comment]
I can select the default audio device through the systray icon now (not sure if you could do that before though) but you can't set any kind of priority

**Comment by ttuegel** [comment]
There is a missing dependency somewhere.

**Comment by garry-cairns** [comment]
Posting here as I think my issue is related; please let me know if it's not and I'll raise a new one. I'm using 17.09. I have audio but can't adjust the volume. In installed plasma-pa in the hope that would help but trying to access that from a panel I see the below:

![selection_006](https://user-images.githubusercontent.com/2401853/32146842-80d8ad3c-bcd5-11e7-8c17-2791703b0295.png)

For ease of reference I'll paste the text of that error below too:

    Error loading QML file: file:///nix/store/ds28v5kapyra43xz3rn4w0jgb9gbj5jl-plasma-pa-5.10.5/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/main.qml:29:1: module "org.kde.plasma.private.volume" is not installed

I can't see a nix package I can install that would seem to satisfy that.

**Comment by sjau** [comment]
On unstable (small) it works again:

https://images.sjau.ch/img/44f19077.png

**Comment by garry-cairns** [comment]
@sjau I'm very new to nixos — would updating my nixos channel to unstable and the updating all be a way for me to try this?

**Comment by sjau** [comment]
that should work... unstable seems rather stable at the moment.... also with atomic upgrades you can go back.

1. Update channel to unstable: `nix-channel --add https://nixos.org/channels/nixos-unstable nixos`
2. Do the update: `nixos-rebuild switch --upgrade`

Probably you'll have to restart or at least restate the x11 session....

**Comment by garry-cairns** [comment]
@sjau I'm just in the middle of some important work just now so I won't report back for a bit. As soon as I can afford to be without a working machine for a bit I'll try this out and report results. Thanks!

**Comment by sjau** [comment]
Good luck :) as said, becuase of atomic updates, you could go back if it doesn't work :)

**Comment by garry-cairns** [comment]
@sjau tried updating to unstable but the problem remains the same. Shall I open this as a new issue?

**Comment by sjau** [comment]
did you reboot?

**Comment by garry-cairns** [comment]
Yep. If I check multimedia in system settings I see "The shared library was not found" under Configure the audio volume. I'm sure I'm missing a dependency somewhere.

**Comment by sjau** [comment]
my current config - using Nixos Unstable channel right now becuase it was updated more recent than Nixos Unstable Small

**Comment by garry-cairns** [comment]
Hmm. Nothing jumping out at me there. I think this is a separate issue so I'll raise it as one.
