### ISSUE TITLE
evolution: on Sway, adding a mail account fails with a strange error

### ISSUE THREAD

**Issue by augustebaum** [NixOS/nixpkgs#290600]
### Describe the bug

Attempting to set up a new mail account in Evolution results in a pop-up reading:
```
The name org.gnome.evolution.dataserver.Sources5 was not provided by any .service files
```

### Steps To Reproduce
1. Start up Evolution
```
nix run nixpkgs#evolution
```
2. Follow the e-mail setup wizard until the "Done" section.
3. Click "Apply" to finish the process
4. Observe the pop-up

### Expected behavior
Not that

### Screenshots
![2024-02-22T09_54_05_screenshot](https://github.com/NixOS/nixpkgs/assets/52001167/d31c371c-f7fb-4463-bff2-142515b26e9f)

### Notify maintainers
@bobby285271 @hedning 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05.20240129.97b17f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
Did you enable `services.gnome.evolution-data-server.enable`?

**Comment by augustebaum** [comment]
I did not! Thanks for the heads-up; I'll try it ASAP. This is the first time I'm hearing about this though, could you point me to some documentation about it?

**Comment by augustebaum** [comment]
Indeed, that solves this particular issue. I haven't found any docs about it though :/
