### ISSUE TITLE
Package request: `warp-terminal` [platforms.linux]

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#290671]
**Project description**

> modern, Rust-based terminal with AI built in

see [darwin package](https://nixpkgs.dev/warp-terminal)

**Metadata**

* homepage URL: https://www.warp.dev/
* source URL: https://github.com/warpdotdev/Warp
* license: unfree
* platforms: darwin, linux

**Comment by edmundmiller** [comment]
I was just checking myself and it's been there since November apparently 😅 https://github.com/NixOS/nixpkgs/pull/242041

**Comment by edmundmiller** [comment]
Ah, don't mind me, not checking the platforms...
