### ISSUE TITLE
libredirect on non-NixOS

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#29064]
### Steps to reproduce

When using libredirect on non-NixOS distro, e.g. Debian 9, LD_PRELOAD is propagated, so if wrapped application runs some system binary, there is an error:
```
sh: relocation error: /nix/store/sgjc1147vi5hd57ck9xgck5xjkydg5lz-glibc-2.25/lib/libdl.so.2: symbol _dl_catch_error, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```
Is there a way to fix that?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by vcunat** [comment]
That confuses me a bit.  I thought the main point of libredirect [is to *avoid*](https://github.com/swick/libredirect#whats-that) using LD_PRELOAD.

**Comment by gnidorah** [comment]
@vcunat I mean't NixOS own libredirect simple proxy https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/libredirect
And here is how we use it https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/enpass/default.nix#L87
Is it possible to allow glibc from nixpkgs to read an additional environment variable to LD_PRELOAD, say LD_NIX_PRELOAD (as we do with reading /etc/ld-nix-preload.so https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glibc/dont-use-system-ld-so-preload.patch), so dynamic loader of host system will not suffer from our packages?

**Comment by vcunat** [comment]
I'm sorry, I confused those :-/

It certainly is possible to add a new variable for this.  I wonder if it's a good idea; I don't see any caveats yet.

**Comment by Mic92** [comment]
One way to avoid this, is to unset LD_LIBRARY in the libredirect code.
So it will be only used by the actual process will pick it up.

**Comment by dezgeg** [comment]
Well, it's a problem on NixOS as well that the redirect leaks to all possible child processes.

Maybe libredirect could remove itself from LD_PRELOAD on startup.

**Comment by vcunat** [comment]
I suppose this depends on the particular use case.  I can imagine you to want to "sandbox" all child processes as well, because they are e.g. just parts of the same application.

**Comment by vcunat** [comment]
For maximal flexibility, there could e.g. be a build-time parameter to libredirect &ndash; a list of nix-store paths, and it would deactivate itself when in a process outside those subtrees.  But it seems useless to implement such cannons until we know at least some *particular* use case.

**Comment by dezgeg** [comment]
There have been occassional complaints on IRC about the Teamspeak client (which uses libredirect) being unable to open links in Chromium because the inherited libredirect causes Chromium to crash.

**Comment by knedlsepp** [comment]
Currently having this problem as well:
- Installed `sublime3` and `ctags`.
- Installed the `CTags` package inside sublime.
- Try to run ctags from within sublime leads to:
```
sort: relocation error: /nix/store/bwax7l3946zn3l806727sd1fk8ssjgpv-glibc-2.25-49/lib/libdl.so.2: symbol _dl_catch_error, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
ctags: cannot sort tag file : No such file or directory
```
I've worked around this issue by installing `nixpkgs.coreutils`, to get the `sort` command from `nixpkgs`.

**Comment by Mic92** [comment]
I just tested and `unsetenv("LD_PRELOAD");` does not work reliable: https://stackoverflow.com/questions/3275015/ld-preload-affects-new-child-even-after-unsetenvld-preload
Maybe wrapping `exec` and do the cleanup their does the job.

**Comment by dezgeg** [comment]
It might be worth asking the glibc people if they'd be willing to have an option like `${glibc}/lib/ld-linux.so.2 --preload` implemented in the dynamic linker similar to the `--library-path` option they have. Then instead of adding an environment variable, `makeWrapper` could prefix the command with an explicit call to the linker.

**Comment by lf-** [comment]
If anyone is hitting this with Haskell `stack` on non-NixOS distros, just use the nix integration for Stack:

Put:

```
nix:
  enable: true
```

in your `~/.stack/config.yaml` or project specific `stack.yaml` and you're done.
