### ISSUE TITLE
GCC wrapper makes specifying some -march values for MIPS impossible

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#290621]
### Describe the bug
The nixpkgs GCC compilers force `-march` based on the target triple, as seen here: https://github.com/NixOS/nixpkgs/blob/0b3c2c5daa922e853e73953f87ba8306a53fe3b2/pkgs/build-support/cc-wrapper/default.nix#L604

GCC, however, errors out when `-march` flags conflict, at least for MIPS.

This is exceptionally important for the Linux kernel, which very much depends on being able to set these flags to compile for a specific machine at all. The machine I tried was the Nintendo 64, which forces `-march=r4300`.

### Steps To Reproduce
1. Obtain a MIPS cross toolchain:
```
nix shell nixpkgs#pkgsCross.mips64-linux-gnuabi64.stdenv.cc
```
2. Compile a program manually with e.g. `-march=r4300`:
```
$ mips64-unknown-linux-gnuabi64-gcc -march=r4300 aslrtest.c
cc1: error: ‘-mips64r2’ conflicts with the other architecture options, which specify a mips3 processor
```

### Expected behavior
I would expect the compiler to use the user-specified `-march`.

### Notify maintainers
Not quite sure who to ping for the Nixpkgs cross compiler infrastructure.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info
copying path '/nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, Gentoo, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyssais** [comment]
The MIPS platform examples seem to be specific to single GCC architectures.   I'm not sure why that is.  But you don't have to use them — the sets in pkgsCross are only supposed to be examples, and the underlying mechanism is much more flexible.

This works fine:

```ShellSession
$ nix-shell --arg crossSystem '{config = "mips64-unknown-linux-gnuabi64";}' -p
$ mips64-unknown-linux-gnuabi64-gcc -march=r4300 test.c
```

**Comment by 0n-s** [comment]
Thank you, this seems to be the way.

I didn't realize the MIPS cross toolchain examples were limited to only MIPS R2 processors, but they indeed are, which is a little unintuitive given their fairly generic-sounding names. So this isn't really a bug.
