### ISSUE TITLE
Out of Date: julia-0.6.0-dev-2016-11-25

### ISSUE THREAD

**Issue by silvernode** [NixOS/nixpkgs#29067]
## Issue description
Julia-0.6 is no longer a development version and was released 19 June 2017

## Technical details

* System: 
               LSB Version:	1.0
               Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void

* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I)
* Sandboxing enabled: N/A

**Comment by 7c6f434c** [comment]
The real issue is that I fail to make either 0.5 or 0.6 build.

**Comment by orivej** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/66351498d62d343e1b7fddfcdc1e22d893def9c1

**Comment by nico202** [comment]
Can this be closed?
