### ISSUE TITLE
Why purescript belong haskellPackage instead of to nodePackages?

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#29078]
The `purescript` official [guide](http://www.purescript.org/) recommend purescript and tools installation via `npm` but current nix's purescript seem to come from `hackage` or `haskell`.

What is the ecosystem of purescript in nix's point-of-view?
How purescript's packages is managed?

    $ nix-shell -I nixpkgs=/nix/nixpkgs -p purescript --run 'purs --version'
    0.11.6

    $ nix-shell -I nixpkgs=/nix/nixpkgs -p haskellPackages.purescript --run 'purs --version'
    0.11.6

---

Also, I ask a similar question to this on [stackoverflow](https://stackoverflow.com/questions/46094241/need-help-on-start-using-purescript-on-nixos).

**Comment by vyp** [comment]
Well the compiler is written in haskell so :woman_shrugging:
