### ISSUE TITLE
nix-shell fails

### ISSUE THREAD

**Issue by NanuIjaz** [NixOS/nixpkgs#290772]
## Issue description
nix-shell is not opening , instead failing with below error

nix-shell
building '/nix/store/f2ksl5zgkx3vn3kwisfgjdri2m06l1id-source.drv'...

trying https://api.github.com/repos/numtide/flake-utils/tarball/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  7748  100  7748    0     0   3712      0  0:00:02  0:00:02 --:--:-- 14786
unpacking source archive /build/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
do not know how to unpack source archive /build/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/b8i8r39n111n2w8vyw4myy8y8l1l8xbj-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:205:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nix-shell'
         at /nix/store/b8i8r39n111n2w8vyw4myy8y8l1l8xbj-nixpkgs-src/pkgs/stdenv/generic/make-derivation.nix:244:7:
          243|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          244|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          245|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;

       error: builder for '/nix/store/f2ksl5zgkx3vn3kwisfgjdri2m06l1id-source.drv' failed with exit code 1;
       last 8 log lines:
       >
       > trying https://api.github.com/repos/numtide/flake-utils/tarball/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
       > 100  7748  100  7748    0     0   3712      0  0:00:02  0:00:02 --:--:-- 14786
       > unpacking source archive /build/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
       > do not know how to unpack source archive /build/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
       For full logs, run 'nix-store -l /nix/store/f2ksl5zgkx3vn3kwisfgjdri2m06l1id-source.drv'.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by aktaboot** [comment]
what is the exact command that causes this error ?

**Comment by SuperSandro2000** [comment]
This is an issue with the nix file supplied to nix-shell. Since the issue tracker is not a generel support chat, I am closing this. Please see https://nixos.org/community/ for other channels.
