### ISSUE TITLE
Build failure: whois on nixpkgs-23.11-darwin

### ISSUE THREAD

**Issue by anderslundstedt** [NixOS/nixpkgs#290701]
### Steps To Reproduce

1. On Darwin, try to build `whois` using the `nixpkgs-23.11-darwin` channel.¹

¹ I tried this it on an AArch64 MacBook running macOS 14.3.1.

### Build log

Essentially the same as the Hydra failures:

https://hydra.nixos.org/build/250129047/nixlog/2
https://hydra.nixos.org/build/250153655/nixlog/2

### Notify maintainers

@fpletz 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 4 paths will be fetched (1.13 MiB download, 8.59 MiB unpacked):
  /nix/store/1a21vqczm40m4bcpyfk21mh18hpsvzwb-DarwinTools-1
  /nix/store/xnyf3c8pncg7cb8xpkfk0jm462lxkl68-bash-interactive-5.2-p15
  /nix/store/2cb88n5x38xrp152xlrcgpwyxx9qzkla-nix-info
  /nix/store/pwjmx5j6cn5rkvkxw5y7zhgdg4lz4jmp-readline-8.2p7
copying path '/nix/store/1a21vqczm40m4bcpyfk21mh18hpsvzwb-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/pwjmx5j6cn5rkvkxw5y7zhgdg4lz4jmp-readline-8.2p7' from 'https://cache.nixos.org'...
copying path '/nix/store/2cb88n5x38xrp152xlrcgpwyxx9qzkla-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/xnyf3c8pncg7cb8xpkfk0jm462lxkl68-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/Users/anders/nixpkgs`
```

**Comment by fpletz** [comment]
This PR broke it: #266686

**Comment by fpletz** [comment]
New whois version does not fix the build. It works on master but fails on 23.11. Not sure what is different in the darwin ecosystem since that and I don't have a darwin machine to test.

**Comment by anderslundstedt** [comment]
Using the unstable channel, new whois version builds on Darwin, so I think this build failure probably needs little prioritization.
