### ISSUE TITLE
Build failure: coreutils

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#290777]
### Steps To Reproduce

1. Attempt to fetch coreutils on aarch64-linux

Nix will build coreutils instead of fetching it

### Build log

https://termbin.com/ggm7

### Notify maintainers

@dasJ

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.0-asahi, NixOS, 23.11 (Tapir), 23.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamjedrzejewski** [comment]
@RossComputerGuy: I suspect this might be caused by changes introduced by asahi in the `fcntl`, see this [commit](https://github.com/AsahiLinux/linux/commit/081abc5fa701738699705a6c0a41c824df77cb37)

**Comment by tpwrules** [comment]
Reverting that does fix this issue. I'm raising it with the Asahi folks.

**Comment by tpwrules** [comment]
I have [patched the patch](https://github.com/tpwrules/nixos-apple-silicon/commit/e7f0326a5cc14f77a9d993a1cba89d30647ab6c9) to address this problem for NixOS on Apple Silicon users at least. Not sure if Asahi will take it but I don't think there's anything further us the NixOS folks to do here.
