### ISSUE TITLE
Update request: darktable 4.6.0 → 4.6.1

### ISSUE THREAD

**Issue by etrigan63** [NixOS/nixpkgs#290895]
- Package name:darktable
- Latest released version:4.6.1

- Current version on the unstable channel:4.6.0
- Current version on the stable/release channel:4.4.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by leona-ya** [comment]
There's already a merged PR: #289597
