### ISSUE TITLE
Kitty does not start: [glfw error 65542]: EGL: Failed to get EGL display: Success

### ISSUE THREAD

**Issue by kstaniek** [NixOS/nixpkgs#290847]
### Describe the bug
Kitty installed from nixpkgs does not start on fresh Ubuntu 22.04.4 LTS and raises an error:
```
[054 11:34:56.128878] [glfw error 65542]: EGL: Failed to get EGL display: Success
[054 11:34:56.133688] Traceback (most recent call last):
  File "/nix/store/xb3k7q8wpi3d8nsb0vlcwbdncaj5zy6k-kitty-0.32.2/bin/../lib/kitty/kitty/main.py", line 561, in main
    _main()
  File "/nix/store/xb3k7q8wpi3d8nsb0vlcwbdncaj5zy6k-kitty-0.32.2/bin/../lib/kitty/kitty/main.py", line 553, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/nix/store/xb3k7q8wpi3d8nsb0vlcwbdncaj5zy6k-kitty-0.32.2/bin/../lib/kitty/kitty/main.py", line 296, in __call__
    _run_app(opts, args, bad_lines)
  File "/nix/store/xb3k7q8wpi3d8nsb0vlcwbdncaj5zy6k-kitty-0.32.2/bin/../lib/kitty/kitty/main.py", line 268, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow
```
Kitty version from nixpkgs:
```
kitty --version
kitty 0.32.2 created by Kovid Goyal
```

The binary downloaded from `https://github.com/kovidgoyal/kitty/releases/download/v0.32.2/kitty-0.32.2-x86_64.txz`
works like a charm. 

### Steps To Reproduce
1. install kitty nix package on fresh Ubuntu 22.04
2. ...
3. ...

### Expected behavior
It is expected to work the same a binary built from developer page

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
nix-shell -p nix-info --run "nix-info -m"
warning: unknown setting 'upgrade-nix-store-path-url'
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info
copying path '/nix/store/g09jbj92l7j0wsvnch87z93mz9s8pz4i-nix-info' from 'https://cache.nixos.org'...
warning: unknown setting 'upgrade-nix-store-path-url'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-18-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
warning: unknown setting 'upgrade-nix-store-path-url'
 - version: `nix-env (Nix) 2.18.1`
warning: unknown setting 'upgrade-nix-store-path-url'
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Arroquw** [comment]
This also happens on NixOS. Both kitty and alacritty break if I update my flake.

**Comment by eclairevoyant** [comment]
@kstaniek can you try running with [NixGL](https://github.com/nix-community/nixGL) to confirm?

@Arroquw I can't reproduce on NixOS; can you post a link to where you use it in your config, as well as the commit where it breaks?

**Comment by Arroquw** [comment]
@eclairevoyant Oh, seems I'm using home-manager for kitty, forgot about that. Let me see if the nixpkgs package also breaks in my config

**Comment by Arroquw** [comment]
Apparently this happens if you update your NixOS config without updating home manager. After updating both it is working fine for me.
