### ISSUE TITLE
enable cgroup accounting

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#29095]
## Issue description

I want to see systemd services in netdata monitoring. For that "cgroup accounting" is needed.

https://github.com/firehol/netdata/wiki/monitoring-systemd-services

The question is if enabling it on all systems would have any negative effect. In that case i would activate it only when netdata service is enabled.

Arch Linux, Ubuntu and Fedora seem to have it enabled by default. debian not.

### Steps to reproduce

`systemd-cgtop` shows no resources for services.

## Technical details
* System: NixOS 17.03.1700.51a83266d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1700.51a83266d1"
* Sandboxing enabled: build-use-sandbox = true

**Comment by davidak** [comment]
I will implement it as option, that is enabled by default and for netdata service.

`systemd.enableCgroupAccounting`

**Comment by andrew-d** [comment]
I believe you can set this with:

```
systemd.extraConfig = ''
  DefaultCPUAccounting=yes
  DefaultIOAccounting=yes
  DefaultBlockIOAccounting=yes
  DefaultMemoryAccounting=yes
  DefaultTasksAccounting=yes
'';
```

And maybe also:
```
boot.kernelParams = [ "cgroup_enable=memory" "swapaccount=1" ];
```

(ideas from [here](https://github.com/firehol/netdata/wiki/monitoring-systemd-services))

**Comment by davidak** [comment]
@andrew-d sure, that is how i do it right now. But i want to propose it to be enabled by default, so you have it when you need it for debugging. But also a single option to disable it when you have reasons to.

**Comment by samueldr** [comment]
Is this still open for the discussion about defaulting to `true` or is this still open simply because it wasn't closed? Unless something else than the PR is required. (@davidak)

**Comment by davidak** [comment]
I created this issue to have this enabled for netdata. So an additional PR needs to be created to enable the new option when netdata is enabled.

In addition it could be discussed to enable the option by default when a desktopManager is enabled (for desktop users). It should not be enabled by default on servers because it could have a little impact on performance.

**Comment by flokli** [comment]
@davidak Nowadays, this might already be enabled per default half-way:

from my `systemd-system.conf (latest master right now)
```
       DefaultCPUAccounting=, DefaultBlockIOAccounting=, DefaultMemoryAccounting=, DefaultTasksAccounting=,
       DefaultIOAccounting=, DefaultIPAccounting=
           Configure the default resource accounting settings, as configured per-unit by CPUAccounting=,
           BlockIOAccounting=, MemoryAccounting=, TasksAccounting=, IOAccounting= and IPAccounting=. See systemd.resource-
           control(5) for details on the per-unit settings.  DefaultTasksAccounting= defaults to yes,
           DefaultMemoryAccounting= to yes.  DefaultCPUAccounting= defaults to yes if enabling CPU accounting doesn't
           require the CPU controller to be enabled (Linux 4.15+ using the unified hierarchy for resource control),
           otherwise it defaults to no. The other three settings default to no.
```

Are there any recent figures about performance implications when enabling the rest? If Fedora enables it, we could probably do so too.

**Comment by davidak** [comment]
>this might already be enabled per default half-way

thanks for noticing! can you create an issue or PR to change `systemd.enableCgroupAccounting`?

>Are there any recent figures about performance implications when enabling the rest?

i don't know any. i have no issues on my servers where i set it manually

**Comment by Pleune** [comment]
> I believe you can set this with:
> 
> ```
> systemd.extraConfig = ''
>   DefaultCPUAccounting=yes
>   DefaultIOAccounting=yes
>   DefaultBlockIOAccounting=yes
>   DefaultMemoryAccounting=yes
>   DefaultTasksAccounting=yes
> '';
> ```
> 
> And maybe also:
> 
> ```
> boot.kernelParams = [ "cgroup_enable=memory" "swapaccount=1" ];
> ```
> 
> (ideas from [here](https://github.com/firehol/netdata/wiki/monitoring-systemd-services))

Adding some up to date information in case google leads someone to this thread...

The kernel params are no longer needed. Accounting is now always enabled. And Nix defaults to enabling the systemd accounting settings as well.
