### ISSUE TITLE
nextcloud: extraOptions always defines a php array, which is incompatible with some apps

### ISSUE THREAD

**Issue by Nomkid** [NixOS/nixpkgs#290933]
### Describe the bug
`services.nextcloud.extraOptions` seems to always create a PHP array, which doesn't work with modules that aren't expecting arrays.

In my case, the Nextcloud Memories app needs exiftool but the builtin one doesn't work, so I installed it in `environment.systemPackages`. In order to tell Memories where to find the exiftool binary, I then added `services.nextcloud.extraOptions.memories.exiftool = "${pkgs.exiftool}/bin/exiftool";` but it still didn't work.
Examining `/var/lib/nextcloud/config/config.php` revealed that Nix had added this:
```php
'memories' => 
  array (
    'exiftool' => '/nix/store/wh8hjj88gcws12nyv1nyxx1w722zx4yw-perl5.38.0-Image-ExifTool-12.70/bin/exiftool',
  ),
```
which evidently Memories didn't parse as expected, because going into the Web UI admin panel, the path was still blank.
Changing it to the one-liner
```php
'memories.exiftool' => '/nix/store/wh8hjj88gcws12nyv1nyxx1w722zx4yw-perl5.38.0-Image-ExifTool-12.70/bin/exiftool',
```
did as expected, and in the Web UI the path showed up correctly.

### Steps To Reproduce
1. Install and configure Nextcloud in `configuration.nix` using `services.nextcloud`.
2. Using the Nextcloud Web UI's appstore, install Memories.
3. Under `<nextcloud url>/settings/admin/memories`, see that "Path to packaged exiftool binary" is empty.
4. In `configuration.nix`, add `services.nextcloud.extraOptions.memories.exiftool = "${pkgs.exiftool}/bin/exiftool";` and see that the path is still blank in the Web UI.
5. Manually edit `/var/lib/nextcloud/config/config.php` to the one-liner in the bug description above, and see that the path is now populated as expected in the Web UI, and Memories is now able to read and edit image EXIF data without throwing errors.

### Expected behavior
It should only use php arrays when there is more than one child option defined.

i.e. if I set
```nix
services.nextcloud.extraOptions.abcxyz = {
  foo = "abc";
  bar = "xyz";
};
```
then I would expect to see
```php
'abcxyz' =>
  array (
    'foo' => 'abc',
    'bar' => 'xyz',
  ),
```

but if I instead only set
```nix
services.nextcloud.extraOptions.abcxyz = {
  foo = "bar";
};
```
then I would expect to see
```php
'abcxyz.foo' => 'bar',
```

**Alternatively,** forego the php arrays altogether and *only* define options one-at-a-time like this:
```php
'abcxyz.foo' => 'abc',
'abcxyz.bar' => 'xyz',
```

### Screenshots
Not really applicable.

### Additional context
Not applicable.

### Notify maintainers
@schneefux @bachp @globin @Ma27 

### Metadata

```console
root@tweed ~# nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.20231230.9dd7699`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

(sorry if this is not what you needed, I am new to nixos and even github issues in general)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
What's wrong with writing `services.nextcloud.extraOptions."memories.exiftool" = ...`?

Implementing magic around that is IMO a bad idea because we'd like to have a mapping of what Nextcloud does in Nix and there are a few options that actually expect nested arrays (e.g. `redis.host`/`redis.port`).

**Comment by Nomkid** [comment]
Oh! My bad, I didn't know that was the syntax to do this.
Thanks!
