### ISSUE TITLE
Can't access plain text/HTML email body composers in Evolution

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#291094]
### Describe the bug

Symptoms: Running GNOME Evolution 3.50.1, 3.50.2, and 3.50.4, I can no longer focus the plain text or HTML body composers for emails. That is, clicking the body editor or pressing Tab while the cursor is on the subject line does nothing - the cursor simply stays on the subject line.

Workaround: Change the composer to one of the Markdown modes to be able to click on it and edit emails.

[Upstream issue](https://gitlab.gnome.org/GNOME/evolution/-/issues/2625)

### Steps To Reproduce
1. Run GNOME Evolution on nixos-unstable
2. Click to create a new email
3. In the format selector (between the subject and body fields), select _Plain Text_
4. Click the body field

### Expected behavior

The body field should be focused, and I should be able to edit its contents.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/168301/80585513-e2b2-46c9-a381-2fc88602492b)

### Additional context

There are no error messages in the console.

### Notify maintainers

@bobby285271 @hedning @jtojnar @dasj19 @amaxine

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 24.05 (Uakari), 24.05pre586498.0e74ca98a74b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
I am unable to reproduce on nixos-unstable (cbc4211f0afffe6dfd2478a62615dd5175a13f9a) when I run `nix-build -A evolution` and run `result/bin/evolution`. The field focuses just fine (though I have Plain text by default).

Maybe rather than bisecting evolution, you could try to bisect nixpkgs revisions? https://channels.nix.gsc.io/

In my experience, Webkit is quite finicky and might be easily broken e.g. by changes in GPU stack.

**Comment by l0b0** [comment]
I'm bisecting with `$(nix-build -A evolution --no-out-link)/bin/evolution`, but it's taking absolutely forever. Is there any way to disable tests globally?

**Comment by jtojnar** [comment]
Not really, I usually just manually disable the ones that take too long as I go. You can also use nix-bisect to make it skip mass rebuilds.

**Comment by l0b0** [comment]
> Not really, I usually just manually disable the ones that take too long as I go.

Is there a convenient way to do that in bulk? I'm not aware of any CLI tools to modify the Nix AST, and `sed` seems like asking for trouble.

> You can also use nix-bisect to make it skip mass rebuilds.

How do I make it skip mass rebuilds? There's no simple `extra-bisect run` command I can set up to do this non-interactively, because I have to verify that the text field can be interacted with.

The main issue now is that most builds are either failing because of test timeouts or making the machine unusable for hours, spending all of my 32 GB of RAM. Hopefully nix-bisect can help with that…

**Comment by l0b0** [comment]
Is it possible that the issue is that I've set `programs.evolution.enable` rather than adding Evolution to `systemPackages`?

**Comment by l0b0** [comment]
Welp, looks like this has been fixed in the last few days. I guess we'll never know.

**Comment by l0b0** [comment]
Nope, not fixed. Looks like some side effect of trying to bisect it made it work until I ran GC.

**Comment by l0b0** [comment]
FYI: Moved to Thunderbird, so I won't be following up on this issue. Please open a new issue if you encounter this.
