### ISSUE TITLE
displayManager.job.logsXsession does not work like expected

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#29106]
## Issue description

`config.services.xserver.displayManager.job.logsXsession` does not work like expected.
In the description of this option it says:
> Whether the display manager redirects the
> output of the session script to
> <filename>~/.xsession-errors</filename>.

### Steps to reproduce

If this option is set to `true` and `config.services.xserver.displayManager.logToJournal` is set to `false` (which is by the way not intentional in the description of these options) the condition in [this line](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/default.nix#L75) is not met although it should be `true` to match the expected behaviour.

## Technical details

* System: `nixos-version` `17.03.1775.56da88a298 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.13`
* Nixpkgs version: `"17.03.1775.56da88a298"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by Gerschtli** [comment]
I would love to help fixing this problem, but I don't know what is the right approach, because simply fixing the conditon would end in breaking backwards compatibility.
To preserve backwards compatibility we could introduce a new option that defaults to the inverted value of `logsXsession` and mark the old option as deprecated.
What do you guys say? Just the opinion of a neebie..

**Comment by rnhmjoj** [comment]
So, should it read `(cfg.displayManager.job.logsXsession && !cfg.displayManager.logToJournal)?
Do they have to be mutually exclusive at all?

**Comment by Gerschtli** [comment]
Yes, that would be more logical.
I don't know the reason why it is currently mutually exclusive, but I don't think it has to be that way.

**Comment by Gerschtli** [comment]
@edolstra

**Comment by Gerschtli** [comment]
Whats the state?

**Comment by rnhmjoj** [comment]
It's finally fixed.
