### ISSUE TITLE
`qrcp` is incorrectly marked as broken on Darwin

### ISSUE THREAD

**Issue by Samasaur1** [NixOS/nixpkgs#291088]
### Describe the bug
qrcp is marked as broken on Darwin, but it builds and runs fine. I'm assuming based on the comment next to it:

https://github.com/NixOS/nixpkgs/blob/cbc4211f0afffe6dfd2478a62615dd5175a13f9a/pkgs/tools/networking/qrcp/default.nix#L45

that the package was broken at the time, but now works. I tested on both aarch64-darwin and x86_64-darwin, and the packages builds and runs fine.

### Steps To Reproduce
1. `nix run nixpkgs#qrcp` (on Darwin)
2. Get the error "package qrcp is marked as broken"
3. `NIXPKGS_ALLOW_BROKEN=1 nix run --impure nixpkgs#qrcp`

### Expected behavior
`qrcp` should evaluate without the need for `NIXPKGS_ALLOW_BROKEN`

### Notify maintainers

@fgaz. Also @SuperSandro2000, who initially marked the package broken on Darwin, in case it's a different issue that I'm missing.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Sounds reasonable to me. Just send a PR or I do it later when I find the time
