### ISSUE TITLE
Package request: fm

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#291024]
**Project description**

 A terminal based file manager

**Metadata**

* homepage URL: https://github.com/mistakenelf/fm
* source URL: https://github.com/mistakenelf/fm
* license: mit
* platforms: unix, linux, darwin, ...

note this is distinct from the previously packaged [`fm`](https://nixpkgs.dev/fm) package, also a file manager tho using GTK rather than using Bubbles

**Comment by AndersonTorres** [comment]
Let's play!
