### ISSUE TITLE
Update request: mesa 23.3.5 → 24.0.1

### ISSUE THREAD

**Issue by RoccoRakete** [NixOS/nixpkgs#291118]
- Package name: mesa
- Latest released version: 24.0.1
- Current version on the unstable channel: 23.3.5
- Current version on the stable/release channel: 23.1.9

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

@primeos
@vcunat 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Alanazane** [comment]
Looks like mesa was already updated to 24.0.1 a week or so ago [here](https://github.com/NixOS/nixpkgs/pull/289051).  It should hit unstable after staging gets merged in, you can even track it's progress [here](https://nixpk.gs/pr-tracker.html?pr=289051) if you want :)

**Comment by RoccoRakete** [comment]
ups, sorry :)
