### ISSUE TITLE
ati_unfree fails to compile with newer kernel versions

### ISSUE THREAD

**Issue by third3ye** [NixOS/nixpkgs#2912]
I was given a tip by vcunat to upgrade the kernel to see if my GPU requires a newer kernel version (AMD has done a lot of adding to the linux kernel lately). But I received the same error when I tried upgrading to linuxPackages_3_14 and linuxPackages_latest:

/tmp/nix-build-ati-drivers-13.12-3.14.6.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c: In function 'KCL_ACPI_GetHandles':
/tmp/nix-build-ati-drivers-13.12-3.14.6.drv-0/common/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c:796:59: error: 'struct acpi_dev_node' has no member named 'handle'
         pInfo->video_handle = pInfo->pcidev->dev.acpi_node.handle;

Can someone reproduce this? Suggested fix?

**Comment by matthiasbeyer** [comment]
This issue remains for 3.19 and 4.0.

I'm still running 3.18 because of this. I hope there is some progress going on?

**Comment by nathanielbaxter** [comment]
Driver needs an update to 15.5, which might fix your compilation issues? (I'll swap across to an ati card and test the update sometime in the coming week if nobody beats me to it)

It's unlikely that your issues with 3.19 and 4.0 are the *same* compilation issues that this thread had initially, which were fixed in one of the ati driver updates.

**Comment by pSub** [comment]
@nathanielbaxter Do you had any success?

**Comment by dfoxfranke** [comment]
I have a fix for this which fixes compilation issues and also upgrades to 15.07. Pull request incoming shortly as soon I get it properly merged into the tree rather than implemented as an override.

**Comment by nathanielbaxter** [comment]
Thanks for getting to this dfoxfranke. I normally use my ati card for vga passthrough to a windows vm so this fell to the bottom of the priority list for me.
