### ISSUE TITLE
libicu: build failure (cross compiling x86_64-linux -> aarch64-linux)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#291206]
### Describe the bug

```
         at /nix/store/c97z6rsqz7j4damvkwh6sf4fggxqzssv-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'buildRootOnly'

       at /nix/store/c97z6rsqz7j4damvkwh6sf4fggxqzssv-source/pkgs/development/libraries/icu/default.nix:1:1:

            1| { stdenv, lib, fetchurl, fetchpatch, fixDarwinDylibNames, testers, buildPackages }:
             | ^
            2|
```

Haven't had the chance to dig in, yet.

This is an `x86_64-linux` builder cross-compiling for `aarch64-linux`.

This is on top of current `nixos-unstable`: a4695440

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/290761

**Comment by kirillrdy** [comment]
Resolved https://github.com/NixOS/nixpkgs/pull/290761
