### ISSUE TITLE
Nautilus/pcmanfm without DE can't use GVFS

### ISSUE THREAD

**Issue by lluchs** [NixOS/nixpkgs#29137]
## Issue description

If you install just nautilus/pcmanfm/probably others without a full DE, auto-mounting via GVFS doesn't work.

### Steps to reproduce

1. Enable gvfs and udisks2 services (`services.{gnome3.gvfs,udisks2}.enable = true;`)
2. Install nautilus or pcmanfm
3. Insert a removable device
4. Notice that the device doesn't show up in the file manager

## Technical details

The file managers need the environment variable `GIO_EXTRA_MODULES` to include `${pkgs.gvfs}/lib/gio/modules` for gvfs integration. This variable is set correctly only if you get the full desktop environment:

 https://github.com/NixOS/nixpkgs/blob/2e7105467b22292eca1fc37c2c8019e6aacc7051/nixos/modules/services/x11/desktop-managers/lxqt.nix#L62
https://github.com/NixOS/nixpkgs/blob/710973e354cc0f1c18a2d201f631d54420c6084a/nixos/modules/services/x11/desktop-managers/xfce.nix#L126
https://github.com/NixOS/nixpkgs/blob/bd545892332ede39cd5c1c0ba26e7101b0d2c971/nixos/modules/services/x11/desktop-managers/gnome3.nix#L181

* System: NixOS unstable 
* Sandboxing enabled: no

**Comment by concatime** [comment]
I'm also facing this issue while trying `pcmanfc-qt` inside `sway`. Do you have/propose a workaround?
[configuration.nix](//github.com/concatime/dotfiles/edit/master/configuration.nix)

**Comment by concatime** [comment]
Solution (for me):
 - Adding `gvfs` into `packages` of my user ;
 - Adding `environment.variables.GIO_EXTRA_MODULES = [ "${pkgs.gvfs}/lib/gio/modules" ];` into my config. file ;

I removed `services.gnome3.gvfs.enable = true;` since I don't need [`full GNOME support`](//nixos.org/nixos/packages.html#gnome3.gvfs).

**Comment by Mic92** [comment]
I suppose we should set `GIO_EXTRA_MODULES` by default for pcmanfm in a wrapper.

**Comment by jtojnar** [comment]
`services.gvfs.enable = true` sets the `GIO_EXTRA_MODULES` variable since 4bb6625767b2428cbacb712165f5db63ebadcf66.
