### ISSUE TITLE
Build failure: musescore

### ISSUE THREAD

**Issue by matj1** [NixOS/nixpkgs#291397]
### Steps To Reproduce

1. build musescore

### Build log

The full log from my system rebuild is [here (gist)](https://gist.github.com/matj1/6023e63832f0cb111f063ba633ced432). The following is just the ending where the errors are mentioned.

```
-- Configuring done (10.9s)
-- Generating done (0.5s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025


-- Build files have been written to: /build/source/build
cmake: enabled parallel building
cmake: enabled parallel installing
Running phase: buildPhase
build flags: -j4
[0/2] Re-checking globbed directories...
ninja: error: 'src/framework/global/CMakeFiles/global.dir/cmake_pch.hxx.gch', needed by 'src/framework/global/CMakeFiles/global.dir/Unity/unity_4_cxx.cxx.o', missing and no known rule to make it
error: builder for '/nix/store/3nzcj45lzndfssf08dnhi8fv8x010xvj-musescore-4.2.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/s922clghx99v7aqigq8rx2w0dhw7mwky-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fa92y24mnr1k2vzldgn9kqppyrgclwx1-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z06ggyry75qpjyk0czvas4q047nw4y2z-nixos-system-watson-24.05pre588267.73de017ef2d1.drv' failed to build
```

### Notify maintainers

@vandenoever  
@doronbehar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

- system: `"x86_64-linux"`
- host os: `Linux 6.1.78, NixOS, 24.05 (Uakari), 24.05pre587158.cbc4211f0aff`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"nixos"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DamitusThyYeetus123** [comment]
same issue here

**Comment by simonhollingshead** [comment]
#290037 apparently fixes this.

**Comment by thilobillerbeck** [comment]
still broken for me in `nixos-unstable`

**Comment by wentasah** [comment]
@thilobillerbeck You need to wait until #290037 appears in `nixos-unstable`. IFAIK, `staging` is merged to `master` approximately once in two weeks. You can [watch progress here](https://nixpk.gs/pr-tracker.html?pr=290037).

**Comment by thilobillerbeck** [comment]
Ah thx 👍 I was just confused bc. some other things that got merged later on already landed in *-unstable. But thanks for sharing the progress page. 🙂

**Comment by schoettl** [comment]
The mentioned PR has finally be merged into nixos-unstable today! MuseScore from unstable now builds for me. I think we can close this issue.
