### ISSUE TITLE
Soundux crashing when trying to add a new tab.

### ISSUE THREAD

**Issue by Mxp271** [NixOS/nixpkgs#291380]
### Describe the bug
Soundux crashes when trying to add a new soundboard tab.

### Steps To Reproduce
1. Install the soundux package from nixpkgs23.11.
2. Start soundux.
3. Click on "Add Tab".

### Expected behavior
Open the file explorer in order to choose a folder.

### Screenshots
![Screenshot_20240225_170214](https://github.com/NixOS/nixpkgs/assets/122394525/59d88ea8-78bb-49dd-8d51-ecd43c6cf588)

### Additional context
I already tried adding dconf and dconf-editor.
Besides these two, I have no other GNOME or GTK related package installed, since my DE is KDE Plasma.
When running `journalctl -f` in the background, the error message sent to console is  `No GSettings schemas are installed on the system`.

### Notify maintainers

@aidalgol 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.20240220.526d051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aidalgol** [comment]
Soundux has been removed from nixpkgs in PR #283439 because it is unmaintained upstream.
