### ISSUE TITLE
fsck is not run automatically for non-root filesystems

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#29139]
## Issue description

If I have a non-root filesystem defined, it is not automatically checked with fsck, on boot or otherwise.

`configuration.nix` (fragment):
```
  fileSystems."/vol/aux" = {
    device = "/dev/vdb";
    fsType = "jfs";
  };
```

`/etc/fstab` (fragment):
```
/dev/vdb /vol/aux jfs defaults 0 2
```
`/run/systemd/generator/vol-aux.mount`:

```
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target

[Mount]
What=/dev/vdb
Where=/vol/aux
Type=jfs
```

On ArchLinux, if I create a fstab record like this, I get the following in `/run/systemd/generator/vol-aux.mount`:

```
Requires=systemd-fsck@dev-vdb.service
After=systemd-fsck@dev-vdb.service
```

Consequently, in ArchLinux fsck is being run.

This is a major problem in case of jfs filesystem, because after unclean unmount, it refuses to mount until `fsck` is run on it.

### Steps to reproduce

Add a non-root filesystem.

## Technical details

* System: 17.03.1775.56da88a298 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1775.56da88a298"
* Sandboxing enabled: no

**Comment by jerith666** [comment]
Yep, that's it.  Editing the kernel parameters via grub to add `systemd.log_level=debug`, I get:

```
Aug 18 23:28:02 alpha systemd-fstab-generator[712]: Checking was requested for /dev/mapper/maingroup-home, but fsck.ext4 does not exist.
```

**Comment by pvgoran** [comment]
Thanks for looking into this! Looking forward to getting this merged.

A more careful and "nixos-way" approach to this would be to introduce an additional special fstab option `fsck-program` to pass the location of the relevant `fsck` program, for systemd-fstab-generator to use when checking for existence of the `fsck` program, and for `systemd-fsck` to invoke. But this would require too many changes, especially since `systemd-fsck` currently does not access `/etc/fstab` and will need to be modified to do it.

**Comment by jerith666** [comment]
I'm not really convinced this is even the right short-term fix.

I started the mass-rebuild ~36 hours ago and it's probably gonna be another 12 or so until it's done, so I don't even know if it works yet.  I think I need to make a test case instead of testing on a full system.

I'm wondering whether we can set the `PATH` for systemd somehow in one of the early boot scripts, but haven't looked into that any more yet.

**Comment by pvgoran** [comment]
> I'm wondering whether we can set the PATH for systemd somehow in one of the early boot scripts, but haven't looked into that any more yet.

Well, this would be a more elegant solution than just disabling the check for `fsck` existence.

I looked into this, and it seems like the most straightforward way would be to add `:$systemConfig/sw/bin` to the line `PATH=/run/current-system/systemd/lib/systemd` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-2-init.sh#L162. Not sure if it's a good idea, though: many many unnecessary binaries will be made accessible in the path this way, and I'm not knowledgeable enough to estimate the consequences of this.

**Comment by jerith666** [comment]
well, the rebuild finally finished.  It did in fact create the `Requires` and `After` lines in `/run/systemd/generated/*.mount`, and the fscks actually ran.

But, I'm going to explore the option of augmenting `systemd`'s path -- that seems like a cleaner fix.

**Comment by pvgoran** [comment]
@jerith666 Thanks for a clean solution for this issue!
