### ISSUE TITLE
Systemd user services are not reloaded on nix-rebuild

### ISSUE THREAD

**Issue by akamaus** [NixOS/nixpkgs#29146]
## Issue description
I manage a couple of user services using `systemd.user.services` configuration variable. Turns out, I need to manually issue `systemctl --user daemon-reload` after successful `nixos-rebuild switch` in order to apply changes I made to my services.

## Technical details

* System: nixos-17.09
* Nix version:1.11.14

**Comment by fpletz** [comment]
We will probably have to call `systemctl --user daemon-reload` for every logged in user.

**Comment by akamaus** [comment]
@fpletz agree, it's the least surprising thing to do.

**Comment by refnil** [comment]
I think the pull request #44990 fix this issue. It makes the switch-to-configuration.pl script call `systemctl --user daemon-reload` for each currently login user.

**Comment by fpletz** [comment]
Yup, it does. Thanks!
