### ISSUE TITLE
command-not-found executable is not available

### ISSUE THREAD

**Issue by rrnewton** [NixOS/nixpkgs#29143]
## Issue description

I see various discussion of `command-not-found` (#1751, #12044, #11996) discussing how to fix its database, etc, but I have the much more basic problem that I don't have a `command-not-found` binary on my NixOS system.

I can see [where the source is](https://github.com/NixOS/nixpkgs/blob/48a3e1a88d0ab4e154a7b0a649136605eaefd32c/nixos/modules/programs/command-not-found/command-not-found.nix), and I can see that in `modules-list.nix` it is referenced, so [this commit](https://github.com/NixOS/nixpkgs/commit/dc7e32e618bbc962ddbdd03b596966a1deac5fb4) disabling it must no longer apply.

I don't see it [listed in the configuration options](https://nixos.org/nixos/manual/options.html).  I tried adding this to my `configuration.nix` but I got an error:

```
config.programs.command-not-found.enable = true;
```

### Steps to reproduce

Fresh install of nixos and then upgrade to unstable channel, `18.03pre114421.799435b7ca (Impala)`.
Attempt to run `command-not-found`.

## Technical details

* System: 18.03pre114421.799435b7ca (Impala)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "18.03pre114421.799435b7ca"
* Sandboxing enabled: true

**Comment by pbogdan** [comment]
Could you try with `programs.command-not-found.enable = true;` (without the `config.` prefix)? That would seem to be working for me on the same nixpkgs revision.

**Comment by rrnewton** [comment]
Thanks!  That does the trick.  I wonder why it wasn't on by default.

I can't see from where I should have learned that.  (It feels like one small example of the oft-discussed discoverability and UX issues, as described in https://github.com/NixfiOS/nix/issues/684 .)

The "Appendix A" does not define this command-not-found option.  Should I send a documentation PR that adds it to that appendix?

**Comment by pbogdan** [comment]
AFAIK the manual hosted on nixos.org is for the stable version of NixOS. You can however browse the manual generated for the current version of your system by running `nixos-help` command.

**Comment by rrnewton** [comment]
Ah, good call, it's already there!  All is in order.
