### ISSUE TITLE
libreoffice-qt doesn't start

### ISSUE THREAD

**Issue by sobornostea** [NixOS/nixpkgs#291571]
### Describe the bug
Trying to run `libreoffice` (installed with the `libreoffice-qt` package) fails with the following error `Error: Can't find the tool "rr", --record option will be ignored.`

Starting a `nix shell` containing `rr` with `nix shell nixpkgs#rr` and running `libreoffice` in it fails with the following error :

```
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 2.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.d/10-rr.conf.
See 'man 8 sysctl', 'man 5 sysctl.d' (systemd systems)
and 'man 5 sysctl.conf' (non-systemd systems) for more details.
```

### Steps To Reproduce
1. Add `libreoffice-qt` to your packages
2. Try to run `libreoffice`

### Expected behavior
LibreOffice starts

### Notify maintainers

@7c6f434c

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240224.73de017`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos, nixos-hardware, plasma-manager"`
 - channels(sobornost): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 7c6f434c** [comment]
Pretty sure that by the time `rr` comes into play something bad has already happened. It's a debugger, not something needed in normal operation.

What `readlink -f $(type -P libreoffice)` tells you? `/nix/store/3a5nz3xb5vcixlflcl92c75xii6q1amn-libreoffice-7.6.4.1-wrapped/bin/libreoffice`?

Creating a fresh user account and running LibreOffice from `libreoffice-qt` from there (to my main Xorg session, which has no DE though) works fine for me.

**Comment by peterhoeg** [comment]
I'm using `libreoffice-qt` under plasma every other day and am having no issues on latest unstable.

**Comment by sobornostea** [comment]
This command tells me : `/nix/store/3a5nz3xb5vcixlflcl92c75xii6q1amn-libreoffice-7.6.4.1-wrapped/lib/libreoffice/program/soffice`

**Comment by sobornostea** [comment]
> Pretty sure that by the time `rr` comes into play something bad has already happened. It's a debugger, not something needed in normal operation.
> 
> What `readlink -f $(type -P libreoffice)` tells you? `/nix/store/3a5nz3xb5vcixlflcl92c75xii6q1amn-libreoffice-7.6.4.1-wrapped/bin/libreoffice`?
> 
> Creating a fresh user account and running LibreOffice from `libreoffice-qt` from there (to my main Xorg session, which has no DE though) works fine for me.

This command tells me : /nix/store/3a5nz3xb5vcixlflcl92c75xii6q1amn-libreoffice-7.6.4.1-wrapped/lib/libreoffice/program/soffice

**Comment by 7c6f434c** [comment]
Do things work if you create a fresh user account and try there?

**Comment by sobornostea** [comment]
Oh, it seems to work with a new user

However removing `.config/libreoffice` on my user doesn't seem to fix it

But yeah, it seems more like an issue with my side of things than a packaging issue

**Comment by peterhoeg** [comment]
Closing as it's a local config issue.

**Comment by 7c6f434c** [comment]
The standard stuff I would advise for debugging such things is probably a) same user but a different DE, maybe even something minimalistic (WM not a complete DE), b) maybe look carefully at the full output above the complaint about rr, c) if the above doesn't help at all there is always strace to see where it looks for stuff…

**Comment by sobornostea** [comment]
For the curious, I found the source of the bug, it's unrelated to nix but for posterity

In my configuration, I have the following option set as a shortcut 
```nix 
home.sessionVariables.RR = "$HOME/Repositories";
```

This interferes with this code in the [libreoffice script](https://github.com/LibreOffice/core/blob/cc60e2eacdf2d55e0f52754d1e0801479b199615/desktop/scripts/soffice.sh#L75) :

```sh
# force the --record option if the RR variable is set
test -n "$RR" && EXTRAOPT="--record"
```
