### ISSUE TITLE
Package request: gh-copilot

### ISSUE THREAD

**Issue by OliverJAsh** [NixOS/nixpkgs#291551]
**Project description**

**Metadata**

* homepage URL: https://github.com/github/gh-copilot
* source URL: https://github.com/github/gh-copilot
* license: Not sure
* platforms: macOS - not sure about others

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by PerchunPak** [comment]
Don't know if you get a notification, but I created a PR for this request - #297073.
