### ISSUE TITLE
miniflux: Setting `CERT_DOMAIN` breaks stuff

### ISSUE THREAD

**Issue by augustebaum** [NixOS/nixpkgs#291532]
### Describe the bug

When the `CERT_DOMAIN` setting is set to any value, starting the Miniflux systemd service results in the following error:
```
Server failed to start: listen tcp :443: bind: permission denied
```
Unsetting the option makes things work (with TLS).

It appears that this setting should in fact not be used for automated deployments using Docker/Nix: <https://github.com/miniflux/v2/issues/834>

### Expected behavior
Setting `CERT_DOMAIN` is not possible, or I get a warning that `CERT_DOMAIN` is unnecessary and might break things.

### Notify maintainers

@rvolosatovs @benpye @emilylange 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05.20240129.97b17f3`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilylange** [comment]
> ### Expected behavior
> 
> Setting `CERT_DOMAIN` is not possible, or I get a warning that `CERT_DOMAIN` is unnecessary and might break things.

Alternatively, would you be fine with it just working?
Meaning it would successfully bind on port `443` (as unprivileged user)?

**Comment by augustebaum** [comment]
> > ### Expected behavior
> 
> > 
> 
> > Setting `CERT_DOMAIN` is not possible, or I get a warning that `CERT_DOMAIN` is unnecessary and might break things.
> 
> 
> 
> Alternatively, would you be fine with it just working?
> 
> Meaning it would successfully bind on port `443` (as unprivileged user)?

I don't know enough about networking to say, honestly; surely it would be less work to just disable the option, since it already "just works" if you don't set it?

**Comment by augustebaum** [comment]
To recap, the best solution I've found so far is to not set the `CERT_DOMAIN` variable. @emilylange ping in case you have an idea of what to do next, otherwise I'm okay to close this as a "wontfix".

**Comment by emilylange** [comment]
I still consider this to be a bug. I just forgot about it.
Thanks for the ping.

**Comment by mweinelt** [comment]
The expectation is to run a service like Miniflux behind a Reverse-Proxy (like nginx, caddy, ...):

```nix
  services.nginx.virtualHosts."feeds.example.com" = {
    enableACME = true;
    forceSSL = true;
    locations."/".proxyPass = "http://127.0.0.1:${config.services.miniflux.config.PORT}}";
  };
```

And if you really want miniflux do ACME for you, then here's what you need:

```nix
systemd.services.miniflux.serviceConfig = {
  AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
  CapabilityBoundingSet = [ "CAP_NET_BIND_SERVICE" ];
  PrivateUsers = false;
}
```

And with my Security Team hat on:

Relaxing the hardening for odd use-cases like that is unreasonable.

**Comment by emilylange** [comment]
I believe this whole issue and conversation that followed was based on a fundamental misunderstanding what `CERT_DOMAIN` does.

Thanks for sharing your perspective @mweinelt.
I wholeheartedly agree.
It's why I marked my PR shortly after opening as draft.

And why the first line of my commit message body (and PR description for that matter) literally reads

> I am not particularly happy how this turned out.
