### ISSUE TITLE
Update request: atuin 18.0.1 → 18.0.2

### ISSUE THREAD

**Issue by Samasaur1** [NixOS/nixpkgs#291632]
- Package name: atuin
- Latest released version: 18.0.1
- Current version on the unstable channel: 18.0.1
- Current version on the stable/release channel: 17.0.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000 @Sciencentistguy @0x4A6F

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
If you are planning to open a PR anyway, you don't need to open an issue.

**Comment by Samasaur1** [comment]
> If you are planning to open a PR anyway, you don't need to open an issue.

Cool, thanks. I was unsure of the policy around that
