### ISSUE TITLE
onedriver:  ERR Failed to start unit

### ISSUE THREAD

**Issue by hensou** [NixOS/nixpkgs#291608]
### Describe the bug
After installing onedriver, and after specifying the directory, the program crashes when trying to add a new account.

### Steps To Reproduce
1. Install onedriver
2. Run onedriver-launcher
3. Try adding a new account
4. Specify the directory
5. Check the logs

### Expected behavior
It should not crash when adding a new account.

### Additional context

```console
➜  ~ onedriver-launcher
{"level":"warn","error":"open /home/user/.config/onedriver/config.yml: no such file or directory","path":"/home/user/.config/onedriver/config.yml","time":"2024-02-26T16:58:06Z","message":"Configuration file not found, using defaults."}
16:58:06 INF onedriver-launcher v0.14.1
16:58:13 INF Creating mountpoint. mountpoint=/home/user/onedrive_data systemdUnit=onedriver@home-user-onedrive_data.service
16:58:13 ERR Failed to start unit. error="Unit onedriver@home-user-onedrive_data.service not found."
```

### Notify maintainers

@massix 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.7.5, NixOS, 24.05 (Uakari), 24.05pre588267.73de017ef2d1`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- channels(root): `"home-manager, nixos, nixos-hardware"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by massix** [comment]
I'm on it, I'm testing locally. Will do the PR ASAP.

Sorry for the inconvenience!

In the meantime you can create the service manually (the nix way) using `systemd.user.services` in your home manager configuration
