### ISSUE TITLE
Update request: linuxKernel.kernels.linux_zen 6.7.5-zen1 → 6.7.6-zen1

### ISSUE THREAD

**Issue by deviantsemicolon** [NixOS/nixpkgs#291651]
- Package name: linuxKernel.kernels.linux_zen
- Latest released version: 6.7.6-zen1

- Current version on the unstable channel: 6.7.5
- Current version on the stable/release channel: 6.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@JerrySM64 @thiagokokada 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JerrySM64** [comment]
Oh, forgot to do it. Currently not at home. Will see how late it is when I get back. PR will be up tomorrow at the very latest.

**Comment by JerrySM64** [comment]
PR is up. When it get's merged, I'll close this one.
