### ISSUE TITLE
Package request: Tana

### ISSUE THREAD

**Issue by glabrie** [NixOS/nixpkgs#291639]
**Project description**

Tana is an outliner, a note-taking application that sits between Roam Research and Notion. It's a great up and coming productivity platform, with a unique feature called Supertags. Supertags are basically templates you can graft on to tags. They currently have a deb and a RPM, but as it's a closed source application, the source is not available. 

**Metadata**

* homepage URL: https://tana.inc/
* source URL:
* license: Proprietary
* platforms: Linux (Deb and RPM), windows, mac

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by massix** [comment]
I have it working locally, need to clean up some stuff and then will create the PR!

I still have to figure out the license they're using (for the metadata)

**Comment by glabrie** [comment]
That's amazing! I'm so happy thank you so much!
