### ISSUE TITLE
Package request: tuxedo-drivers

### ISSUE THREAD

**Issue by Kaukov** [NixOS/nixpkgs#291669]
**Project description**

The currently-offered [tuxedo-keyboard](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/tuxedo-keyboard/default.nix) driver has been deprecated for a long time - see [here](https://github.com/tuxedocomputers/tuxedo-keyboard/).

The new driver is called `tuxedo-drivers` and is located [here](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers); also has a GitHub read-only mirror [here](https://github.com/tuxedocomputers/tuxedo-drivers).

Please deprecate all `tuxedo-keyboard` packages and start offering `tuxedo-drivers` instead.

**Metadata**

* homepage URL: https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers
* source URL: https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers
* license: [GPL-3.0+](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/blob/main/debian/copyright?ref_type=heads)
* platforms: linux

**Comment by CutestNekoAqua** [comment]
@blanky0230 do you want to stay maintainer for tuxedo-drivers too? Currently working on that pkg.

**Comment by CutestNekoAqua** [comment]
License for tuxedo-drivers is GPL3 or newer, btw

**Comment by Kaukov** [comment]
> License for tuxedo-drivers is GPL3 or newer, btw

You are correct. It never occurred to me that the `LICENSE` file contained a path inside the repo. Will edit my OP.

**Comment by blanky0230** [comment]
@CutestNekoAqua 

> @blanky0230 do you want to stay maintainer for tuxedo-drivers too? Currently working on that pkg.

Feel free to set yourself as maintainer if you wanna take over. Don't really get to use my tuxedo-device often these days, last time actually just to test a PR. So feel free :)

**Comment by CutestNekoAqua** [comment]
> @CutestNekoAqua
> 
> > @blanky0230 do you want to stay maintainer for tuxedo-drivers too? Currently working on that pkg.
> 
> Feel free to set yourself as maintainer if you wanna take over. Don't really get to use my tuxedo-device often these days, last time actually just to test a PR. So feel free :)

Oki, I will take over :)

**Comment by gabyx** [comment]
That would be so good. But packaging kernel modules is probably way beyond my league...

**Comment by balintbarna** [comment]
Hi @CutestNekoAqua 
Have you made any progress on this? The old kernel module seems unusable at this point. Is there anything you need help with?

**Comment by gabyx** [comment]
jeah it would be nice if we can finish this off, maybe =)

**Comment by balintbarna** [comment]
Looks like @Keksgesicht already added it in unstable: https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/os-specific/linux/tuxedo-drivers/default.nix
I hope it will get into 24.11

**Comment by CutestNekoAqua** [comment]
i think we can close this PR thus
