### ISSUE TITLE
`typescript-language-server` broken?

### ISSUE THREAD

**Issue by will-ca** [NixOS/nixpkgs#291709]
### Describe the bug

```Console
[user@PD-A515-51-8401 ~]$ nix-shell -p typescript-language-server
[nix-shell:~]$ typescript-language-server --stdio
error: unknown option '--tsserver-path=/nix/store/pxq4w4yqgafi67cnwylqg7jff3i1w8x8-typescript-5.3.3/lib/node_modules/typescript/lib/'
```

### Steps To Reproduce

- See above.

### Expected behavior

`typescript-language-server` runs.

### Additional context

https://github.com/typescript-language-server/typescript-language-server/blob/master/CHANGELOG.md#410-2023-11-08

https://github.com/typescript-language-server/typescript-language-server/pull/790

### Notify maintainers

@n3oney, @malob, @cdmistman, @alteckclub, @jlesquembre, @w3irdrobot, @dotlambda.

Sorry for the pings. I can't seem to find `.meta.maintainers`, `search.nixos.org` doesn't show anything either, and there seem to be multiple files to `git blame` (sometimes 100,000kLOCs), so… Your usernames seem to come up in relevant places.

### Metadata

```Console
[user@PD-A515-51-8401 ~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/w3cx1ir83mgri4ypsix0121v0mykhqk1-nix-info
copying path '/nix/store/w3cx1ir83mgri4ypsix0121v0mykhqk1-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.148-2-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.1`
 - channels(root): `""`
 - channels(user): `"nixpkgs, oldstable-22.05, stable-22.11"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

[user@PD-A515-51-8401 ~]$ nix-instantiate --eval --expr '(import <nixpkgs> {}).lib.version'
"24.05pre588396.2a34566b67be"
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by malob** [comment]
So I don't see `typescript-language-server` as a top-level package:

```console
~/C/nixpkgs on master 
❯ nix run -f . typescript-language-server -- --help
error: attribute 'typescript-language-server' in selection path 'typescript-language-server' not found
```

Do you mean `nodePackages.typescript-language-server`? If so, it seems to be working for me.

**Comment by will-ca** [comment]
> So I don't see `typescript-language-server` as a top-level package:

Oh. My gods. I'm stupid, and defined `typescript-language-server` myself to work around some unrelated problems.

It's been a while since I've touched Nix.  Sorry for the bunk report.
