### ISSUE TITLE
unstableGitUpdater produces version numbers that do not comply with version naming guidelines

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#291729]
### Describe the bug
[the package naming rules](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming) say in no uncertain terms "The version attribute must start with a digit".

however, a very large number of packages do not follow this naming guideline.  almost all of these have a version starting with `unstable-`.  on one occasion i was even instructed to change a version starting with a digit to a version starting with `unstable-`

either common practice is wrong, or the documentation is wrong.

my suggested fix would be to tweak the documentation to match common practice: versions must begin with a number, or the string `unstable-` followed by a YYYY-MM-DD date.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Should be fixed by #280501
