### ISSUE TITLE
gdm: crashes sometimes when launching Hyprland

### ISSUE THREAD

**Issue by sofiedotcafe** [NixOS/nixpkgs#291743]
### Describe the bug
The Gnome Desktop Manager (GDM) crashes sometimes when launching Hyprland!

This is usually if you login "too fast", if you wait like 3 seconds and login, it's ok which is the weird part!

This could be an Hyprland problem, my Hyprland is from the NixOS repository.

### Steps To Reproduce
1. Login to GDM (In <3 seconds)
2. Hyprland crashes and puts you back to GDM

### Expected behavior
It should not crash

### Notify maintainers

@wozeparrot
@amaxine @hedning @dasj19 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[jh-devv@luminara:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 24.05 (Uakari), 24.05.20240224.73de017`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gzv0nsm8d5js3wzq2mr1sv9lfp1iyail-source`
```

---

Sincerely,
jh-devv

**Comment by jh-devv** [comment]
I don't know where I would even get the logs for this, could someone help?

**Comment by JohnRTitor** [comment]
`journalctl` should have some insight on what did this.
