### ISSUE TITLE
Package request: kyverno-chainsaw

### ISSUE THREAD

**Issue by Sanskarzz** [NixOS/nixpkgs#291891]
**Project description**

Chainsaw is a tool developed to run end to end tests in Kubernetes clusters.

**Metadata**

* homepage URL: https://kyverno.github.io/chainsaw/latest/
* source URL: https://github.com/kyverno/chainsaw
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eddycharly** [comment]
@Sanskarzz license is Apache V2, we support linux mac and windows (amd and arm versions).

You could also list chainsaw adopters if it helps.
