### ISSUE TITLE
Package request: update libreoffice packages

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#291896]
Hello

1. Is it possible to update versions of libreoffice? @7c6f434c @tricktron 
7c6f434c@mail.ru

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=libreoffice

Current versions based on website are (https://www.libreoffice.org/download/download-libreoffice/)

**7.6.5**
**7.6.4**
7.5.9
**24.2.0**

**Comment by 7c6f434c** [comment]
I picked up LibreOffice maintainership back when I had a comfortable setup for rebuilding it, but nowadays I don't have such, so I just wait until there is something to review and merge.

**Comment by 7c6f434c** [comment]
Oops sorry misclicked
