### ISSUE TITLE
GNOME3 sound settings are not persistent

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#2918]
Whenever I boot my PC I have to re-configure the audio output from analog to SPDIF; the sound settings in gnome-control-center are not persisted.

Currently testing on git HEAD.

**Comment by Profpatsch** [comment]
(triage) @bjornfor is it fixed now? Or is it not relevant to you anymore?

**Comment by bjornfor** [comment]
Yes, still relevant, but low priority. And my PC with SPDIF died a couple days ago, so I cannot test it at the moment.

**Comment by jgillich** [comment]
I've had this issue for years on various distros like Fedora. Should probably be reported in upstream instead.
