### ISSUE TITLE
Build failure: upscayl

### ISSUE THREAD

**Issue by mrnetlex** [NixOS/nixpkgs#291914]
### Steps To Reproduce

1. `nix build nixpkgs/nixos-unstable#upscayl`

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/v9jw8cj02pz7fqikfy62r3maqjnqcb8a-upscayl-2.9.9-linux.AppImage.drv':
         specified: sha256-33jJRMvRQxL7rPJ6VigEKcDhge46CAA0jJUOhzEyWzA=
            got:    sha256-EoTFvlLsXQYZldXfEHhP3/bHygm+NdeDsf+p138mM8w=
error: 1 dependencies of derivation '/nix/store/fmjvbyn22cnr93lsgxhbrq1gakv27170-upscayl-2.9.9-extracted.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i886wbbbz2w5h297ijpwxfhf1in45k1j-upscayl-2.9.9.drv' failed to build
```

### Additional context

Upscayl failed to build due to hash mismatch during `nixos-rebuild switch` (I'm nix beginner, I hope to that I write this bug report in right place.)

### Notify maintainers

@Icy-Thought 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.5-zen1, NixOS, 24.05 (Uakari), 24.05.20240224.73de017`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Icy-Thought** [comment]
Strange! I wonder why I did not get that hash mismatch when I reviewed the PR. Upcoming PR!
