### ISSUE TITLE
services.gitolite may fail to initialize if dataDir is on non-root filesystem

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixpkgs#29195]
## Issue description

If `services.gitolite` has `dataDir` on a secondary (non-root) filesystem, and the device where this filesystem resides isn't immediately available on boot, then the `gitolite-init` systemd service may execute concurrently with mounting of the secondary filesystem.

In this scenario, `gitolite-init` starts working on the root filesystem within the mount point, then the secondary filesystem gets mounted, and `gitolite-init` suddenly finds itself working on the secondary filesystem. Naturally, this results in corrupted/incomplete gitolite data structures.

This actually happens (quite reliably) for me when working on a DigitalOcean droplet with `dataDir` being on an add-on volume. The volume becomes available to the kernel at approximately 3.4 seconds of system uptime; by then, `gitolite-init` would already start.

### Steps to reproduce

* Install Nixos on a DigitalOcean droplet with an add-on DigitalOcean volume.
* Declare a secondary filesystem residing on the add-on volume.
* Point `services.gitolite.dataDir` into the secondary filesystem.
* Wipe `services.gitolite.dataDir` (to force initialization of gitolite data on boot).
* Reboot.
* Run `systemctl status gitolite-init.service` and observe errors in the log.

## Technical details

* System: 17.03.1817.694529e45d (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1775.56da88a298"
* Sandboxing enabled: no

**Comment by pvgoran** [comment]
This would be a solution:

```
systemd.services.gitolite-init.unitConfig.RequiresMountsFor = services.gitolite.dataDir;
```

All in all, I find it quite weird that systemd doesn't wait for all filesystems listed in `/etc/fstab` to become available before declaring that `basic.target` is reached, or do something else to delay startup of "regular" services until every declared filesystem is ready. Without this delay, every service that works with files can suffer from a problem like this one, and needs to be safeguarded individually. (`services.mysql` already does this, for example.)

**Comment by bjornfor** [comment]
So basically we should add that RequiresMountsFor= for all services' dataDir?

**Comment by pvgoran** [comment]
Yes, I suppose. (Provided that we can't or don't want to delay `basic.target` until all filesystems are ready - this would be a generic, and thus preferred, solution.)

I'm going to prepare a PR to address this issue for gitolite.
