### ISSUE TITLE
I can't compile my C++ program

### ISSUE THREAD

**Issue by dinhokusanagi** [NixOS/nixpkgs#291943]
I recently decided to test Nixos but I came across two problems, developing in Python is a huge headache and I ended up giving up, so I switched to C++ but I couldn't find the libgtkmm-3.0-dev dependency on Nixos. This Python issue is something old, I don't know if there will be a solution, but for C++ I would like this dependency to be made available, which is something in theory simpler in relation to Python.
![2024-02-27-162532_hyprshot](https://github.com/NixOS/nix/assets/43162113/fbff0601-f051-46b1-ae5c-ce8d3f2a80ee)

**Comment by roberth** [comment]
We don't have `libgtkmm-3.0-dev`-style packages. Usually the "dev" files are in the `dev` output of a package, where it can be picked up by `mkDerivation`, which we use for building fully packaged packages as well as transient development environments with "nix shell".
Installing development packages globally on your system would be a bad idea that Nix and NixOS solve.
The [First Steps on nix.dev](https://nix.dev/tutorials/first-steps/) may help you get started with these new concepts.

**Comment by dinhokusanagi** [comment]
I even understand the idea of ​​an isolated development environment, other distros have something similar like docker, toolbox or distrobox, having to manually compile dependencies completely discourages me from using NIxos. Still, thanks for the answer

**Comment by dinhokusanagi** [comment]
With your help, I managed to use Python's dependencies through nix-shell, but I need other help, when I start the script from my production environment I start it like this: nix-shell --run 'name script.py' But it takes a long time to start because the nix-shell has to be accessed first. Is there a more direct way to run a script in the production environment without this delay?

**Comment by Atemu** [comment]
@dinhokusanagi you'd simply package the application (ideally using the same expression as the shell uses) and deploy it via Nix.

I'm going to close this issue now because this is a bug tracker, not a public forum for general discussion and help Q&A. Please use the Discourse forum for that purpose.
