### ISSUE TITLE
Predictable interface names changed in Qemu VMs

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixpkgs#29197]
On different machines with different Qemu-based virtualizations (libvirt from nixpkgs, $cloudhosters), the network interfaces namens changed from 17.03 to 17.09. ~~Presumably this has to do with a systemd upgrade.~~ It's due to a kernel config change, see https://github.com/NixOS/nixpkgs/issues/29197#issuecomment-330574684.

For example: enp0s3 becomes ens3.

This breaks existing networking configs and renders the machine unreachable via the network if a static configuration is used or dhcpcd is configured to run on specific interfaces.

This either needs to be fixed before the release (use old naming by patching system or similar) or we need a big fat warning in the release notes.

**Comment by fadenb** [comment]
Do interface names starting with "enp" still exist with the newer systemd?
If not we could (in addition to the big fat warning) implement an assertion stopping users from bricking their systems (we all know that not every one studies the release notes as carefully as they should ;) )

**Comment by dezgeg** [comment]
`enp*` still exist. I think the change is not in systemd but rather in the kernel / firmware presenting some additional information of the device that systemd now prefers. (Given that https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-net_id.c hasn't seen any major changes).

**Comment by groxxda** [comment]
Probably caused by  https://github.com/NixOS/nixpkgs/commit/5ac00265a8ef7dd2f3e1bd00aa1b17b5779b8633

**Comment by fpletz** [comment]
It seems only QEMU is affected. The first interface in VirtualBox VMs is still `enp0s3`.
