### ISSUE TITLE
Build failure: dropbear (pkgsStatic)

### ISSUE THREAD

**Issue by plodocus** [NixOS/nixpkgs#292147]
### Steps To Reproduce

1. build

```
nix build github:NixOS/nixpkgs/f52263ced0937e72453e7fbce9fefb5f425f650b#pkgsStatic.dropbear
```

### Build log

https://gist.github.com/plodocus/152514b888c33a0654e7ee3c37a58e6d

### Additional context

Broken from f52263ced0937e72453e7fbce9fefb5f425f650b, worked in 0df75bc04e14e4af11e0124791bfd41bbff51b88.

### Notify maintainers

@abbradar
@Ericson2314

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-21-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(daniel): `"home-manager, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/daniel/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by liketechnik** [comment]
If I'm reading the log correctly, this fails already when building the glibc dependency, doesn't it?

---

After some experimentation, I came up with the changes in #293263

**Comment by plodocus** [comment]
Very cool, that solves it!
