### ISSUE TITLE
Package request: bustle (rust) to replace pkgs.bustle

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#292187]
Freedesktop has apparently deprecated the Haskell bustle (`pkgs.bustle`) and rewritten it in Rust: <https://gitlab.gnome.org/World/bustle>. It'd be nice to package it and ideally replace `pkgs.bustle` with it since the haskell version has become difficult to keep working. (Is it a drop in replacement?)

**Comment by jtojnar** [comment]
Added to #291339
