### ISSUE TITLE
searx systemd service has wrong executable name for default service package

### ISSUE THREAD

**Issue by Mellowchan** [NixOS/nixpkgs#292142]
### Describe the bug
The searx service is trying to start ```${cfg.package}/bin/searx-run``` and it fails because the actual name is of the executable has been changed to ```${cfg.package}/bin/searxng-run```

### Steps To Reproduce
1. ... use newest unstable branch
2. ... try to deploy searx service with ```services.searx.enable = true;```
3. ... searx service fails to start

### Expected behavior
searx service should start without any issues

### Additional context
The default searx package on Nixos is ```pkgs.searxng``` in ```services.searx.package```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240226.13aff9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/store/1gpgihsi21bni03hy6i5ccw9lfrhnbqi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dasj19** [comment]
Thanks for reporting, I just encountered this bug as well after I updated to the latest unstable branch.
I believe that a general migration from `searx` to `searxng` naming needs to be done to avoid these kind of issues in the future.
