### ISSUE TITLE
sane: disabledDefaultBackends does not work reliably

### ISSUE THREAD

**Issue by robinkrahl** [NixOS/nixpkgs#292159]
### Describe the bug
The `/etc/sane-config/dll.conf` file lists enabled backends, with one backend per line.  The `hardware.sane.disabledDefaultBackends` option uses string substitution to edit this file.  But as it does not take into account line endings, disabling a backend *x* also affects other backends that contain the string *x*.

### Steps To Reproduce
1. Set `hardware.sane.enabled = true;` in `/etc/nixos/configuration.nix` and observe the generated `dll.conf`:
```
$ realpath /etc/sane-config/dll.conf
/nix/store/hb5yn5874izgjychgfjgkjbf0igz9ivk-sane-config/etc/sane.d/dll.conf
```
2. Set `hardware.sane.disabledDefaultBackends = [ "net" ];` and repeat:
```
$ realpath /etc/sane-config/dll.conf
/nix/store/116ir7mwgfnwji955sjblyz0fla87933-sane-config/etc/sane.d/dll.conf
```
3. Compare the two files:
```
$ diff /nix/store/{hb5yn5874izgjychgfjgkjbf0igz9ivk,116ir7mwgfnwji955sjblyz0fla87933}-sane-config/etc/sane.d/dll.conf
7,8c7,8
< # The next line enables the network backend; comment it out if you don't
< # need to use a remote SANE scanner over the network -- see sane-net(5)
---
> # The next line enables the # net disabled in nixos configwork backend; comment it out if you don't
> # need to use a remote SANE scanner over the # net disabled in nixos configwork -- see sane-# net disabled in nixos config(5)
10c10
< net
---
> # net disabled in nixos config
31c31
< dell1600n_net
---
> dell1600n_# net disabled in nixos config
```

### Expected behavior
Instead of mangling the `dell1600n_net` driver, only the `net` driver should be disabled.

### Additional context
This is the code that performs the string substition:
https://github.com/NixOS/nixpkgs/blob/b7535c47327d70e49f619c075570d4130def1874/pkgs/applications/graphics/sane/config.nix#L33

It should probably use something like `^backend$` instead, though I don’t know how this could be expressed here.

On a related note, it would be great to have an option to disable *all* default backends and manually select the backends to enable.

### Notify maintainers

@symphorien (pinging because of https://github.com/NixOS/nixpkgs/commit/c64fb5000b8da3ac657ffe5d9c7522e56b8768cd)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.76, NixOS, 23.11 (Tapir), 23.11.3920.25e3d4c0d359`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(robin): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by symphorien** [comment]
please test https://github.com/NixOS/nixpkgs/pull/293022
