### ISSUE TITLE
On new versions of RustRover (Build #RR-233.14015.153) patchelf fail on native rust helper

### ISSUE THREAD

**Issue by lfdominguez** [NixOS/nixpkgs#292196]
https://github.com/NixOS/nixpkgs/blob/16d9f67e6edb056d27c9e9f9685717f4c041a828/pkgs/applications/editors/jetbrains/default.nix#L244

This silently fail and get a hard time detecting the cause, because:
![image](https://github.com/NixOS/nixpkgs/assets/5604131/d8faee91-2cbb-4869-8956-e8643078ed79)

now seems that is statically linked:
![image](https://github.com/NixOS/nixpkgs/assets/5604131/2581cf90-7324-4e99-8d9e-eaf6b428c985)

**Comment by sdht0** [comment]
Yeah I switched to `jetbrains-toolbox` which is able to install the latest version outside nix.
