### ISSUE TITLE
ebusd service sets all logs to `notice`-level

### ISSUE THREAD

**Issue by bobrippling** [NixOS/nixpkgs#292131]
### Describe the bug

`ebusd` logging config doesn't seem to be applied to the invocation of `ebusd`

### Steps To Reproduce
1. Use the following [log config for ebusd](https://mynixos.com/options/services.ebusd.logs):
```nix
services.ebusd = {
  logs = {
    main = "notice";
    network = "notice";

    bus = "error";
    other = "error";
    update = "error";
  };
};
```
2. Start `ebusd.service`
3. Observe `bus` info-level logs coming through (despite the `bus = "error"` config)

### Expected behavior

No `bus` info-level logs appear in the service log, config is applied.

### Additional context

I suspect the final [`all` argument](https://mynixos.com/nixpkgs/option/services.ebusd.logs.all) is overriding all previous log configs, going off how [`all` is parsed as `lf_COUNT`](https://github.com/john30/ebusd/blob/d6ea68db9424a71febdd8bccd6f940f6f090f576/src/lib/utils/log.cpp#L101) and this appears to then [set all log levels](https://github.com/john30/ebusd/blob/d6ea68db9424a71febdd8bccd6f940f6f090f576/src/lib/utils/log.cpp#L138).

### Notify maintainers

@nathan-gs 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.46, NixOS, 24.05 (Uakari), 24.05pre588267.73de017ef2d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nathan-gs** [comment]
@bobrippling I see this more as an issue with the [ebusd upstream](https://github.com/john30/ebusd). Their [docs](https://github.com/john30/ebusd/wiki/2.-Run#log-options) are clear, it should work:
> --log=AREAS:LEVEL
> Only write log for matching AREAs (main|network|bus|update|other|all) below or equal to LEVEL (error|notice|info|debug) [all:notice].
> This is an alternative form to using --logareas/--loglevel and allows to specify an individual level for each area by using the option multiple times. E.g. for having only bus messages in info level and all other in error level, use --log=all:error --log=bus:info.

I do see your issue and I'm wondering if it would be better to leave out the `all` directive (since we specified all others).

**Comment by bobrippling** [comment]
Thanks @nathan-gs, yes I'm thinking the final `all` directive is overriding all the others, so I guess it is a quirk of the upstream.

I like the idea of leaving it out, or we could have it at the start of the [log arguments (just after `--scanconfig`)](https://github.com/NixOS/nixpkgs/blob/592047fc9e4f7b74a4dc85d1b9f5243dfe4899e3/nixos/modules/services/home-automation/ebusd.nix#L18), which will allow configuration of an `all` level, with the ability to override it for specific areas, as subsequent arguments. Wdyt?

(although having said that, I guess we always pass the other `--log=<area>:<level>` areas, so perhaps dropping `all` is simpler, leaving the nixos config to default each area)

**Comment by nathan-gs** [comment]
@bobrippling go ahead and make the PR, you can tag me as reviewer! Thx a lot.
