### ISSUE TITLE
Running pdfpc on macOS gives "Could not acquire DBus bus"

### ISSUE THREAD

**Issue by adelbertc** [NixOS/nixpkgs#29224]
## Issue description

Running pdfpc on a Beamer slideshow on macOS gives "Could not acquire DBus bus" message and hangs.

### Steps to reproduce

macOS Sierra v10.12.6. pdfpc installed with

```
$ nix-env -i /nix/store/ff21n3kzzfbng4j9z8cdmxgqrmpp0a2h-pdfpc-4.0.7
```

Store path taken from https://hydra.nixos.org/build/59076430#tabs-details which is the last stable build of pdfpc on Darwin.

Run `pdfpc` on a Beamer slideshow.

```
$ pdfpc slides.pdf
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
macOS Sierra v10.12.6

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.13

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
18.03pre114739.d0d905668c

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
false

**Comment by adelbertc** [comment]
@jbaum98 Hey, sorry for ping, but I noticed you were the one who added Darwin support for pdfpc [here](https://github.com/NixOS/nixpkgs/commit/12da885e45c6abe3bad371e70dcd1f2760e40735) - wondering if you actually got `pdfpc` working for you?

**Comment by adelbertc** [comment]
Disregard, this whole thing works, it just popped up a window buried under other windows.

**Comment by MichaelW1989** [comment]
I have the same issue (no dbud bus), but there seems to be no window that pops up when I run the command. I installed pdfpc via Home Brew. (OS: 13.3.1, Chi: M1 Pro). Is there a workaround?

**Comment by nsauerfpe** [comment]
Same issue, installed via homebrew. I am trying on multiple monitors and the presentation view shows up on alternate with no presenter view anywhere.

Have tried on two external monitors, and one external and main laptop screen (simulating presenting).

**Comment by nsauerfpe** [comment]
> Same issue, installed via homebrew. I am trying on multiple monitors and the presentation view shows up on alternate with no presenter view anywhere.
> 
> Have tried on two external monitors, and one external and main laptop screen (simulating presenting).

Disregard from me as well. Similar issue as adelbertc, but I think its important so I will explain.

In mac if you have "system settings > desktop and dock > prefer tabs when opening documents" set to always. This will force pdfpc to open the presentation and presenter view in a tabs of the same window, it will then fullscreen this window so you cant see the tabs. This setting seems to also make -w option no longer work.

Turn this to never and everything works as intended.

**Comment by taiya** [comment]
Thanks, this fixed. it for me @nsauerfpe (really should be fixed by pdfpc!!)
