### ISSUE TITLE
`nixos-rebuild build` fails as user because of fail in tempdir()

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#29234]
## Issue description / Steps to reproduce

When `nixos-rebuild`ing as user on latest unstable, I get

```
building Nix...                                                     
building the system configuration...                                
Error in tempdir() using /run/user/1000/nix-build.XXXXXX: Parent directory (/run/user/1000) does not exist at /nix/store/cg6yr2rfsv0mkzk8l57znrvv73gsi6ix-nix-1.11.14/lib/perl5/site_perl/5.24.2/x86_64-linux-thread-multi/Nix/Utils.pm line 45.
```

Using `sudo nixos-rebuild build` works.

## Technical details

* System: 17.09.git.96457d2 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "18.03pre114421.799435b7ca"
* Sandboxing enabled: build-use-sandbox = true

**Comment by Mic92** [comment]
`/run/user/1000` should be actually created if you use systemd-logind.

**Comment by Mic92** [comment]
Do you have a valid login session?

```
$ loginctl
   SESSION        UID USER             SEAT             TTY
         8       1000 joerg            seat0
1 sessions listed.
```

**Comment by coreyoconnor** [comment]
I encountered this issue several times as well. In my case the system is a NixOS VM I only contact over mosh.

There was no login session on the VM:

~~~
$ loginctl
   SESSION        UID USER             SEAT             TTY

0 sessions listed.
~~~

I then tried to trigger a session by connecting via ssh. In the original, still open, mosh session:

~~~
$ loginctl
   SESSION        UID USER             SEAT             TTY
        13       1100 coconnor

1 sessions listed.
~~~

And sure enough: nixos-rebuild works.

Interesting. Why would there be no session?

**Comment by Mic92** [comment]
This is a problem with mosh and `systemd-logind`. Once mosh has established the mosh connection, it forks itself and exits the ssh session. When the ssh session is exited your logind session goes away, which also removes `/run/user/<uid>/`.

**Comment by coreyoconnor** [comment]
I searched around on the issue you mentioned. Rather interesting how common this is!

The command `loginctl enable-linger $USER` will retain the session after ssh disconnect.  This means, for my case, the procedure is:

1. connect via SSH
2. enable-linger
3. screen/tmux
4. detach
5. connect with mosh

to establish a persistent session.

From what I see, the issue I encountered is not a NixOS issue. As @Mic92 mentions the issue is with mosh.

**Comment by Mic92** [comment]
I forgot about `enable-linger`. This fixes the issue with mosh. I have no idea what happens in @matthiasbeyer case.

**Comment by rnhmjoj** [comment]
Apparently another way to solve this is setting

    alias mosh-server='systemd-run --user --scope mosh-server'

in the server shell. The session is still gone (looking with `loginctl`) but Nix is working as usual.

**Comment by Mic92** [comment]
@rnhmjoj work-around should solve this issue.
