### ISSUE TITLE
emacs: epkgs.treesit-grammars can't find native libraries anymore

### ISSUE THREAD

**Issue by kurnevsky** [NixOS/nixpkgs#292496]
### Describe the bug
After a recent nixpkgs update my emacs can't find native tree-sitter libraries anymore: `Warning (treesit): Cannot activate tree-sitter, because language grammar for rust is unavailable (not-found): (libtree-sitter-rust libtree-sitter-rust.0 libtree-sitter-rust.0.0 libtree-sitter-rust.so libtree-sitter-rust.so.0 libtree-sitter-rust.so.0.0) No such file or directory`.

I still have `epkgs.treesit-grammars.with-all-grammars` in emacs deps and `emacs-packages-deps` has those libs in `/nix/store/m8v80bwvl8hs4pq1ayxfg6wrdfc3yjms-emacs-packages-deps/lib/` like it was before. But for some reason emacs doesn't look there anymore. It works if I add this path to `LD_LIBRARY_PATH`.

### Steps To Reproduce

Install emacs with `epkgs.treesit-grammars.with-all-grammars` ([here is](https://github.com/kurnevsky/nixfiles/blob/0e1e811e7679ccaf41fc2fd4d415b08948292631/modules/emacs/package.nix#L21) how I do it)

### Notify maintainers

@AndersonTorres @adisbladis @jwiegley @lovek323 @matthewbauer

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240228.9099616`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/store/cbbsvzjcqvzlylq9s7p6d2gyxh64q88p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SmolPatches** [comment]
I am having this same issue, I even added the following to home-manager
```
programs.emacs = {
      enable = true;
      package = pkgs.emacs29-pgtk;
      extraPackages = epkgs: with epkgs; [ tsc tree-sitter-langs tree-sitter ];
 };
```

**Comment by SmolPatches** [comment]
Hey @kurnevsky  I was actually able to stop this from happening by taking these steps
1. I added those ```extraPackages``` as you saw above. 
2. I deleted the emacs/.local directory that doom emacs had been using(previously setup via emacs within distrobox). 
3. I rebuilt doom emacs with doom sync
I am not sure if you are using doom emacs but hopefully this helps.

**Comment by kurnevsky** [comment]
I'm not using doom emacs - it's plain emacs with config built with nix.

**Comment by kurnevsky** [comment]
Before the update emacs successfully found this lib:
```
openat(AT_FDCWD, "/nix/store/ggxdmj3c02bx6b3pnv9ngcl1xg52k2dm-emacs-packages-deps/lib/libtree-sitter-rust.so", O_RDONLY|O_CLOEXEC) = 12
```

But it was looking for it only after rust-ts-mode was activated. Now it looks at startup, hm...

**Comment by kurnevsky** [comment]
ok, found out that now treesit is loaded after `early-init` but before `init`, and in `early-init` the variable `treesit-extra-load-path` is still nil, that's why the lib is not found. Now need to understand why it started to load so early :)
