### ISSUE TITLE
Build failure: citrix-workspace

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#292403]
### Steps To Reproduce

1. Check out current unstable: `git checkout 9099616b9330`
1. build *citrix-workspace*: `NIXPKGS_ALLOW_UNFREE=1 nix-build -A citrix_workspace`

### Build log

https://gist.github.com/l0b0/794ce9577e9925c6cd30d577ce9d7566

### Additional details

This also affects citrix_workspace_23_09_0 and citrix_workspace_23_07_0.

### Notify maintainers

@michaeladler

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 24.05 (Uakari), 24.05pre588267.73de017ef2d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Yeah, I ran into the same, unfortunately opencv is a massive expression, and the diff for the recent change was also massive, so inlining and overriding are IMO out.

I ended up pulling citrix from a working commit (b2d8e8b11cd6c88f49d4fb7f0d5dddbc8dd0aeb7).

**Comment by michaeladler** [comment]
I observed the same issue yesterday and reached the same conclusion as @eclairevoyant. Unfortunately, there is no newer version of Citrix Workspace available, leaving us with the November 2023 release that requires OpenCV 4.7. I attempted to use `patchelf` to enable compatibility with OpenCV 4.9, but alas without success. For now, it seems I will have to mark these packages as broken.

**Comment by l0b0** [comment]
[Instructions](https://lazamar.co.uk/nix-versions/?package=citrix-workspace&version=23.7.0.17&fullName=citrix-workspace-23.7.0.17&keyName=citrix_workspace&revision=9957cd48326fe8dbd52fdc50dd2502307f188b0d&channel=nixpkgs-unstable#instructions) for anyone who has not had to mix nixpkgs versions before.
