### ISSUE TITLE
Dlib won’t use CUDA without setting nixpkgs.config.cudaSupport to true.

### ISSUE THREAD

**Issue by Dines97** [NixOS/nixpkgs#292532]
### Describe the bug
I noticed that in this line https://github.com/NixOS/nixpkgs/blob/1dfd9a62f32d09b918744985efb1b18e542f30d9/pkgs/development/libraries/dlib/default.nix#L57 code actually checks true value of `config.cudaSupport` not `cudaSupport` that is declared at the top. Because of this, dlib doesn’t find the cuDNN libraries and compile without CUDA support.

### Steps To Reproduce
1. Compile with and without `nixpkgs.config.cudaSupport`
2. Check logs of both dlib compilation. One with `nixpkgs.config.cudaSupport = true;` will tell that it found cuda and cuDNN and dlib will use cuda, other will fail to find cuDNN and will tell that CUDA installation maybe incomplete and disables CUDA support.

### Expected behavior
When the cudaSupport option defined in Dlib is enabled, dlib can be compiled with CUDA support without setting `nixpkgs.config.cudaSupport` to true

### Notify maintainers
@RobbieBuxton 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - channels(denis): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RobbieBuxton** [comment]
Ah good spot, I'll try and put in a PR to fix that tonight. Thanks @Dines97!

**Comment by Dines97** [comment]
Also, I believe #243880 this issue can be related to this issue. For people affected by this they can enable nixpkgs.config.cudaSupport = true; globally (which causes a bit of mass rebuilds on system). Also, I’m wondering why options defined in https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/config.nix are not searchable in https://search.nixos.org/ which could save me a bit of time.

**Comment by Dines97** [comment]
> Ah good spot, I'll try and put in a PR to fix that tonight. Thanks @Dines97!

Thank you too!

**Comment by Dines97** [comment]
Leaving this here for history:
```console
➜  ~ nix log /nix/store/b2xy2q4p5kgrjk88gxyzvchqaq0knh2n-dlib-19.24.2
-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found suitable version "12.2", minimum required is "7.5")
-- Found CUDA, but CMake was unable to find the cuBLAS libraries that should be part of every basic CUDA install. Your CUDA install is somehow broken or incomplete. Since cuBLAS is required for dlib to use CUDA we won't use CUDA.
-- DID NOT FIND CUDA
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
```
