### ISSUE TITLE
Support setting PWD in systemd scripts

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#2925]

**Comment by Mathnerd314** [comment]
WorkingDirectory is in [systemd's documentation](http://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=). serviceConfig is not really documented anywhere, but easy enough to find: https://github.com/NixOS/nixpkgs/blob/5d02c02a9bfd6912e4e0f700b1b35e76d1d6bd3f/nixos/modules/system/boot/systemd.nix#L293

So maybe this can be closed?
