### ISSUE TITLE
KDE5 system settings: failing to contact global shortcuts daemon

### ISSUE THREAD

**Issue by bugaev** [NixOS/nixpkgs#29259]
## Issue description
Global shortcuts do not work in KDE5 after upgrade from nixos-16.03 to nixos-17.03 or nixos-17.09 or nixos-unstable.

Cannot switch windows, change volume and brightness levels, launch commands, etc using keyboard.

kglobalaccel5 doesn't start manually either. It is on the search path but 
its dependencies couldn't be found.

### Steps to reproduce
Using mouse:
1) Click on the "application launher" button in the left bottom corner of the screen.
2) Click:  Applications --> Settings Menu --> System Settings --> Shortcuts --> Global shortcuts.
3) Error dialogue window titled "Sorry --- System  Settings" pops up with the following body of text:
"Failed to contact the KDE global shortcuts daemon".

Using command line:
1) Start "konsole".
2) > kglobalaccel5
3) Message is printed:
kglobalaccel5: /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/libc.so.6: version `GLIBC_2.25' not found (required by /nix/store/vrs0ap0nal69mypqr4digwxlmacm0kc8-expat-2.2.2/lib/libexpat.so.1)

/etc/nixos/configuration.nix is taken from another (working perfectly fine) nixos-17.03 system which was  installed as such (no history of upgrades to different major versions,  system.stateVersion = "17.03").
The system with buggy global shortcuts daemon is system.stateVersion = "16.09";

## Technical details

* System: NixOS: 17.03.1819.7eb1a42de4 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1819.7eb1a42de4"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
> build-use-sandbox: command not found

* Other symptoms
  - The wallpaper has a message rendered in the middle of the screen:
    "Unable to create io-slave. Cannot talk to klauncher: The name  org.kde.klauncher5 was not provided by any service files."

**Comment by bugaev** [comment]
I tried today the unstable and there are still no global shortcuts.

On a brighter end, the message "Unable to create io-slave. Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any service files." is gone. Some good changes have certainly happened!

**Comment by ttuegel** [comment]
I am closing this issue because the affected packages are no longer in Nixpkgs.
