### ISSUE TITLE
Package request: python.mediapipe

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#292509]
**Project description**
MediaPipe is the simplest way for researchers and developers to build world-class ML solutions and applications for mobile, edge, cloud and the web.

**Metadata**

* homepage URL: https://pypi.org/project/mediapipe/
* source URL: https://github.com/google/mediapipe
* license: Apache 2.0
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/225901

**Comment by amacfie** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/192071

**Comment by hakan-demirli** [comment]
Closing for https://github.com/NixOS/nixpkgs/issues/192071 then.
