### ISSUE TITLE
 unexpected EOF reading a line

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29257]
## Issue description
Whatever I want to (un)install, I get "error: unexpected EOF reading a line" which is annoying since I can't fix anything anymore. For instance:
```
nix-env -e nix-1.12pre5511_c94f3d55                    
uninstalling ‘nix-1.12pre5511_c94f3d55’
building path(s) ‘/nix/store/7x8g8mc5vj24ncvrzr34fadb2h8jcakd-user-environment’
error: unexpected EOF reading a line
builder for ‘/nix/store/l1gvrx43c4am364m972habdf2srhciym-user-environment.drv’ failed with exit code 1
error: build of ‘/nix/store/l1gvrx43c4am364m972habdf2srhciym-user-environment.drv’ failed
```
I've played quite a bit with channels, using nixpkgs master (to contribute & use up to date packages) than following IRC advice I've switched back to nixpkgs-unstable so I don't claim a super "clean" system. Yet I would like to "save" my system. I wonder if the problem didn't start when I installed 1.12pre5511_c94f3d55 (to test the embedded repl) but now I can't remove it :/

I tried to run older generations but the problem persists.

### Steps to reproduce
Not sure.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 18.03.git.d0d9056 (Impala)
* Nix version: (run `nix-env --version`)  nix-env (Nix) 1.12pre5511_c94f3d55
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 18.03.git.d0d905668c
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by teto** [comment]
seems like it was indeed nix, I found the magical command `nix-env --rollback` which got me back to a working state.

**Comment by johbo** [comment]
Got into the same issue, did a rollback and then updated nix itself, afterwards all was good. I am using Nix on OSX.

**Comment by zimbatm** [comment]
Same issue with nix 1.12pre5663_c7af84ce which I have installed on the NixOS system profile.

Another way to get around the issue is to execute `nix-shell -p nix` which should give an older version of nix that works with user profiles.

**Comment by zimbatm** [comment]
Found the issue on the nix side: https://github.com/NixOS/nix/issues/1674
