### ISSUE TITLE
KdeConnect doesn't work "Library import requires a version"

### ISSUE THREAD

**Issue by ludrol** [NixOS/nixpkgs#292603]
### Describe the bug

KdeConnect doesn't connect and applet gives an error 

### Steps To Reproduce
1. add to `configuration.nix` `environment.systemPackages = with pkgs; [kdePackages.kdeconnect-kde]`
2. run `sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable` and `sudo nix-channel --update`
3. `sudo nixos-rebuild switch --flake /etc/nixos#default`
4. reboot
5. Click on kde applet in bottom dock 
6. There is an error popup

### Expected behavior

no error

### Additional context

<details open>
  <summary>error message</summary>

```
file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml:8:31: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml:12:28: Library import requires a version

file:///nix/store/bsbh9pqyf7b0xwdz1dvww36js3qkn3fn-kdeconnect-kde-24.02.0/share/plasma/plasmoids/org.kde.kdeconnect/contents/ui/main.qml:13:26: Library import requires a version


```

</details>

### Notify maintainers

@K900 
@ilya-fedin 
@LunNova 
@mjm 
@NickCao 
@ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05.20240228.9099616`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/store/cbbsvzjcqvzlylq9s7p6d2gyxh64q88p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Are you using Plasma 5 or Plasma 6? If you're using Plasma 5, you need to be using `plasma5Packages.kdeconnect-kde`.

**Comment by mjm** [comment]
You may want to use `programs.kdeconnect.enable = true;` instead of adding the package like that, just because it should use the correct package based on which version of Plasma you have enabled.

**Comment by ludrol** [comment]
Thank you now it works, search.nixos.org is confusing as it doesn't indicate that it should be done differently.
