### ISSUE TITLE
twisted/constantly sha2sum mismatch

### ISSUE THREAD

**Issue by pillowtrucker** [NixOS/nixpkgs#292658]
### Describe the bug
twisted/constantly fingerprint doesn't match the release tarball from github

### Additional context
matching fingerprint:
```nix
constantly = python-prev.constantly.overridePythonAttrs (oldAttrs: {src = pkgs.fetchFromGitHub {
                                                   owner = "twisted";
                                                   repo = "constantly";
                                                   rev = "refs/tags/${python-prev.constantly.version}";
                                                   hash = "sha256-yXPHQP4B83PuRNvDBnRTx/MaPaQxCl1g5Xrle+N/d7I=";
                                                 };});
```
the checksum in nixpkgs is https://github.com/NixOS/nixpkgs/blob/6c2d774353b67d381de0c4a44acffd29edf865ec/pkgs/development/python-modules/constantly/default.nix#L26
### Notify maintainers
@fabaff @mweinelt 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
The source tarball changed slightly.

```
diff --color -r /nix/store/pl8lgfhwqf4411s64vqlpz4lbxgqg96x-source/constantly/_version.py /nix/store/i4hyfnq2dc5fxpx3c2rnsrphn79wf25z-source/constantly/_version.py
29c29
<     git_refnames = " (HEAD -> trunk, tag: 23.10.4)"
---
>     git_refnames = " (tag: 23.10.4)"
