### ISSUE TITLE
Package request: envision

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#292628]
**Project description**

UI for building, configuring and running Monado, the open source OpenXR runtime.

**Metadata**

* homepage URL: https://gitlab.com/gabmus/envision
* source URL: https://gitlab.com/gabmus/envision
* license: agpl3
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CutestNekoAqua** [comment]
To my information, software without a stable release isnt accepted yet.

**Comment by Pandapip1** [comment]
> To my information, software without a stable release isn't accepted yet.

Not even in unstable? Fair enough, I guess.

**Comment by CutestNekoAqua** [comment]
> > To my information, software without a stable release isn't accepted yet.
> 
> Not even in unstable? Fair enough, I guess.

unstable automatically becomes stable, so yes :)
I think once a release is done (even 0.x), it can be packaged, but don't take my word as the ultimate truth, please :sweat_smile:

**Comment by Pandapip1** [comment]
> To my information, software without a stable release isnt accepted yet.

This appears to be incorrect. `xr-hardware` was merged targeting a specific commit (despite actually having stable releases).

**Comment by Atemu** [comment]
This is indeed incorrect; there are even specific rules for the `version` attribute of unreleased versions.
