### ISSUE TITLE
Package request: brave (from source & for aarch64)

### ISSUE THREAD

**Issue by alxpettit** [NixOS/nixpkgs#292650]
I am not sure where to put this, as it is a redo of the previous Brave packaging, and isn't really a bug report -- but a feature request for the `nixpkgs` ecosystem itself. So I'm framing it as a package request for now.

**Project description**

Brave is a Chromium fork with a number of added features. While Brave is already packaged for NixOS, it's packaged from the `.deb` as a precompiled binary. Packaging it from source would make it possible for users to patch the upstream code, reduce the amount of reliance on upstream build, and generally introduce the same amount of source-level flexibility that we enjoy for Firefox and Chromium, among others.

In addition, `aarch64` support has been updated upstream, but the `.deb`-based NixOS package is still only for `x86-64_linux`. (Although there are probably `aarch64`-compatible deb files to pull, so a `.deb`-based package is still capable of addressing that issue.)

Possibly relevant to @networkexception and @emilylange, as they're involved in maintaining the Chromium src-based package -- though I understand that significant changes have occurred upstream in the Brave fork.

Not sure whether or not I should ping the current `brave` package maintainers, as packaging for a precompiled binary is very different from packaging from source.

**Metadata**

* homepage URL: https://brave.com/
* source URL: https://github.com/brave/brave-browser
* license: MPL2
* platforms: Linux, Windows, MacOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilylange** [comment]
I feel like this is a duplicate of
- #278278 and
- #258153

> Not sure whether or not I should ping the current `brave` package maintainers, as packaging for a precompiled binary is very different from packaging from source.

I would argue `brave` is their package and they should be at least made away of this issue/request here.
As such: cc @uskudnik @rht @JeffLabonte @nasirhm @buckley310

> In addition, `aarch64` support has been updated upstream, but the `.deb`-based NixOS package is still only for `x86-64_linux`. (Although there are probably `aarch64`-compatible deb files to pull, so a `.deb`-based package is still capable of addressing that issue.)

Yes, there seems to be `brave-browser_1.63.162_arm64.deb` in <https://github.com/brave/brave-browser/releases/tag/v1.63.162>.
Should be fairly simple to add that precompiled binary to `brave`s current nixpkgs derivation.

> Possibly relevant to @networkException and @emilylange, as they're involved in maintaining the Chromium src-based package -- though I understand that significant changes have occurred upstream in the Brave fork.

We (@networkException and I) don't have time for this, sorry.

**Comment by alxpettit** [comment]
Ah, whoops! You're right of course, @emilylange. Closing in favor of #258153
