### ISSUE TITLE
KDE Modules are missing in Plasma 6

### ISSUE THREAD

**Issue by Svenum** [NixOS/nixpkgs#292665]
### Describe the bug
I wont to upgrade two plasmoids to Plasma6 but there are two modules missing somehow:
- org.kde.kcoreaddons
- org.kde.plasma.calendar

Here are the repos:
- https://github.com/Svenum/shutdown_or_switch/tree/plasma6
- https://github.com/Svenum/kde-plasmoid-betterinlineclock/tree/plasma6

### Steps To Reproduce
1. Clone the repo:
   ```bash
   git clone https://github.com/Svenum/shutdown_or_switch.git
   cd shutdown_or_switch
   git checkout plasma6
   # OR
   git clone https://github.com/Svenum/kde-plasmoid-betterinlineclock.git
   cd kde-plasmoid-betterinlineclock
   git checkout plasma6
   ```
2. Start the plasmoid
    ``` bash
    plasmoidviewer -a ./plasmoid/
    # OR
    plasmoidviewer -a ./org.kde.plasma.betterinlineclock
    ```

### Expected behavior
Plasmoid start

### Additional context
Plasmoid porting guide:
https://develop.kde.org/docs/plasma/widget/porting_kf6/

My nix plasma config:
https://github.com/Svenum/NixOS-Config/blob/master/modules/desktop/plasma.nix

### Notify maintainers
@K900 
@ilya-fedin
@LunNova 
@mjm 
@NickCao 
@SuperSandro2000 
@ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240228.9099616`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/cbbsvzjcqvzlylq9s7p6d2gyxh64q88p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> org.kde.plasma.calendar

exists in kdePackages.plasma-workspace/lib/qt-6/plugins/plasma/applets/org.kde.plasma.calendar.so

> org.kde.kcoreaddons

No idea, maybe kdePackages.kcoreaddons/lib/qt-6/qml/org/kde/coreaddons

**Comment by Svenum** [comment]
Thats True but both packages are installed if I enable
`services.xserver.desktopManager.plasma6.enable = true;` (https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/x11/desktop-managers/plasma6.nix)
Am I right?

**Comment by SuperSandro2000** [comment]
Yes. What's then the problem? 😅

**Comment by Svenum** [comment]
It still dont work. Even if these packages are installed.

**Comment by K900** [comment]
You probably need to set `QML2_IMPORT_PATH` to be able to discover your dependencies.

**Comment by Svenum** [comment]
And what do I set in the env? Sorry this is my first try to do something with qt.

**Comment by K900** [comment]
`org.kde.kcoreaddons` should be in `${kdePackages.kcoreaddons}/lib/qt-6/qml`, but I think you have a bigger problem here: `org.kde.plasma.calendar` is no longer a thing.

**Comment by Svenum** [comment]
Ok. In my QML2_IMPORT_PATH is `/var/run/current-system/sw/lib/qt-6` already.

Is the calendar replaced by something new? If i call the applet with:
`plasmoidviewer -a org.kde.plasma.calendar`
It works

**Comment by K900** [comment]
It's no longer part of the libplasma public API. And you probably don't have `kcoreaddons` installed globally.

**Comment by Svenum** [comment]
But kcoreaddons should be installed if plasma6 is enabled in my config, or not?

**Comment by K900** [comment]
"Installed" is a nebulous concept on NixOS, many library dependencies are not made available globally and are injected through wrappers instead.

**Comment by Svenum** [comment]
I know. I meant its in "environment.sytemPackages" as "pkgs.kdePackages.kcoreaddons"

**Comment by K900** [comment]
If it is, then it should be picked up. Are you maybe using a Qt5 build of plasmoidviewer?

**Comment by Svenum** [comment]
No its the new plasmoidviewer
`plasmoidviewer --version` gives me version 6.0.0
and its the viewer from "pkgs.kdePackages.plasma-sdk"

**Comment by ilya-fedin** [comment]
Do you have `/run/current-system/sw/lib/qt-6/qml` in `QML2_IMPORT_PATH`? Does `/run/current-system/sw/lib/qt-6/qml/org/kde/coreaddons/libkcoreaddonsplugin.so` exist?

**Comment by Svenum** [comment]
Yes and yes

**Comment by ilya-fedin** [comment]
So I did the following
```
git clone https://github.com/Svenum/kde-plasmoid-betterinlineclock.git
cd kde-plasmoid-betterinlineclock
git checkout plasma6
nix shell self#kdePackages.plasma-sdk
plasmoidviewer -a ./org.kde.plasma.betterinlineclock
```
What I got is
```
QML debugging is enabled. Only use this in a safe environment.
kf.svg: The theme "Adapta" uses the legacy metadata.desktop. Consider contacting the author and asking them update it to use the newer JSON format.
kf.svg: The theme "Adapta" uses the legacy metadata.desktop. Consider contacting the author and asking them update it to use the newer JSON format.
kf.plasma.core: The theme "Adapta" uses the legacy metadata.desktop. Consider contacting the author and asking them update it to use the newer JSON format.
kf.plasma.core: The theme "Adapta" uses the legacy metadata.desktop. Consider contacting the author and asking them update it to use the newer JSON format.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
file:///nix/store/m92rr9yv1j0y0pnh3p7r8ms0mbp81cad-plasma-desktop-6.0.0/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentItem_QML_42(0x1d7e300, "desktop")
QQmlComponent: Component is not ready
kf.plasma.quick: error when loading applet "org.kde.plasma.betterinlineclock" QList("file:///home/ilya/kde-plasmoid-betterinlineclock/org.kde.plasma.betterinlineclock/contents/ui/main.qml:27:1: module \"org.kde.plasma.calendar\" is not installed")
kf.svg: The theme "Adapta" uses the legacy metadata.desktop. Consider contacting the author and asking them update it to use the newer JSON format.
```

**Comment by Svenum** [comment]
Thats the same what happened by me. This error is from the removed module "org.kde.plasma.calender" as @K900 mentioned here:
> `org.kde.kcoreaddons` should be in `${kdePackages.kcoreaddons}/lib/qt-6/qml`, but I think you have a bigger problem here: `org.kde.plasma.calendar` is no longer a thing.

The other repo I mentioned has the "kcoreaddons" problem. Maybe you can try this as well?

**Comment by ilya-fedin** [comment]
Ah, I thought both are used in both. Will try.

**Comment by ilya-fedin** [comment]
it's a org.kde.kcoreaddons vs org.kde.coreaddons problem I guess

**Comment by Svenum** [comment]
you are right. If I change it to "org.kde.coreaddons" it works. Thank you :smile:

**Comment by SuperSandro2000** [comment]
So upstreams needs to do a small fix and everything works as expected or is there anything left to do on our side?

**Comment by ilya-fedin** [comment]
> So upstreams needs to do a small fix and everything works as expected

absolutely
