### ISSUE TITLE
fcitx5-qt incorrect repository parameters

### ISSUE THREAD

**Issue by pillowtrucker** [NixOS/nixpkgs#292656]
### Describe the bug
fcitx5-qt from libsForQt5 tries to download a nonsensical package from a non-existent repository

### Steps To Reproduce
try to install/update libsForQt5.fcitx5-qt

### Additional context
```nix
libsForQt5 = prev.libsForQt5.overrideScope (qtfinal: qtprev: {
                                             fcitx5-qt = qtprev.fcitx5-qt.overrideAttrs (attrs: {
                                               src = prev.fetchFromGitHub {
                                                 owner = "fcitx";
                                                 repo = "fcitx5-qt";
                                                 rev = attrs.version;
                                                 sha256 = "sha256-bVH2US/uEZGERslnAh/fyUbzR9fK1UfG4J+mOmrIE8Y=";
                                               };
                                             });
                                           });
```
this workaround works.

### Notify maintainers
@NickCao are you in control of those repositories and planning to update them to actually match what is in nixpkgs ?
https://github.com/NixOS/nixpkgs/commit/6479f63ecb8c8649f78e91b12c079b387686bc73

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NickCao** [comment]
The issue is me wrongfully using `pname` in place of `repo`, would fix soon.
