### ISSUE TITLE
Package request: Discover

### ISSUE THREAD

**Issue by thibaultmol** [NixOS/nixpkgs#292642]
**Project description**

Yet another Discord overlay for Linux written in Python using GTK3.

**Metadata**

* homepage URL: https://trigg.github.io/Discover/
* source URL: https://github.com/trigg/Discover
* license:  GPL-3.0 license
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
packaged in #295938
