### ISSUE TITLE
Using SDDM with custom themes

### ISSUE THREAD

**Issue by ElysaSrc** [NixOS/nixpkgs#292761]
### Describe the bug

On unstable, when trying to use a custom theme on SDDM, it fails to load it with this custom error message:
`The theme at "/run/current-system/sw/share/sddm/themes/catppuccin-mocha" requires missing "/nix/store/f03hm28dsz6v0d9zdwdlfmrra25k2w7l-sddm-wrapped/bin/sddm-greeter". Using fallback theme.`

I'm using this custom package for theming: https://github.com/ElysaSrc/nixos-config/blob/main/modules/home/packages/catppuccin-sddm.nix

### Steps To Reproduce
1. Use plasma + sddm on unstable (qt6 versions).
2. It loads the default theme, this error shows up.

### Expected behavior
The theme sould load

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pshirshov** [comment]
Yep, this is extremely annoying. Seems like the greeter is there but it has `qt6` suffix.

**Comment by ElysaSrc** [comment]
> Yep, this is extremely annoying. Seems like the greeter is there but it has `qt6` suffix.

Would it be hard to modify the derivation to add a symlink ?

**Comment by Satalicious** [comment]
![PXL_20240306_153053979 MP](https://github.com/NixOS/nixpkgs/assets/91656114/c53eaa59-aaaf-4ea8-a118-9ec98a270a69)

I was stuck after updating to Plasma6 today at the login screen. This is the fallback in the screenshot. I had the same error:  ` The theme at "/usr/share/sddm/themes/Utterly-Nord" requires missing "/usr/bin/sddm-greeter" . Using fallback theme.
`

I resolved it by creating a new user, logging in and changing the sddm theme to the default one. Now im back up and running.

**Comment by ElysaSrc** [comment]
> I was stuck after updating to Plasma6 today at the login screen. This is the fallback in the screenshot. I had the same error: `The theme at "/usr/share/sddm/themes/Utterly-Nord" requires missing "/usr/bin/sddm-greeter" . Using fallback theme.`
> 
> I resolved it by creating a new user, logging in and changing the sddm theme to the default one. Now im back up and running.

I'm on a freshly installed computer (it never was on plasma 5) and I'm not sure why creating a new user would work on my case ? I can give it a try.

**Comment by Kasper24** [comment]
This happens because 3rd party themes have not been updated to use the QT6 version. 
You have 2 options:
1. Set the sddm package back to older package. This is needed because enabling the plasma6 module also sets the sddm package to the newer, kdePackages.sddm
```nix
services.xserver.displayManager.sddm.package = libsForQt5.sddm
```
Another option is to keep using kdePackages.sddm, but override it and pass in qt5 libraries, as it will automatically enable the QT6 flag for SDDM if the QT version is 6

2. Port the theme you are using to QT6. For most themes, it only consists of 
- Replacing all 'import QtGraphicalEffects' with  'import Qt5Compat.GraphicalEffects'
- Adding a metadata.desktop file at the theme root folder (if it doesn't already have one) and add 'QtVersion=6'

**Comment by ElysaSrc** [comment]
> This happens because 3rd party themes have not been updated to use the QT6 version. 
> There are 2 options:
> 1. Set the sddm package back to older package. This is needed because enabling the plasma6 module also sets the sddm package to the newer kdePackages.sddm package.
> ```nix
> services.xserver.displayManager.sddm.package = libsForQt5.sddm
> ```
> Another option is to keep using kdePackages.sddm, but override it and pass in qt5 libraries, as it will automatically enable the QT6 flag for SDDM if the QT libraries version is 6
> 
> 2. Port the theme you are using to QT6. For most themes, it only consists of:
> - Replacing all 'import QtGraphicalEffects' with  'import Qt5Compat.GraphicalEffects'
> - Adding a metadata.desktop file at the theme root folder (if it doesn't already have one) and add 'QtVersion=6'

This is right. Maybe this issue can be closed then.

**Comment by pshirshov** [comment]
```
error: builder for '/nix/store/kfjifv45gnmf4yx0b1hsz01ah3xnnsg1-sddm-wrapped.drv' failed with exit code 1;
       last 3 log lines:
       > Error: detected mismatched Qt dependencies:
       >     /nix/store/2mcqdmp7kb8pfkibxsm10z3s94j80s6y-qtbase-6.6.3
       >     /nix/store/62jj0ky87hh1rxrjcz6w44ix2798skc2-qtbase-5.15.12-dev
       For full logs, run 'nix log /nix/store/kfjifv45gnmf4yx0b1hsz01ah3xnnsg1-sddm-wrapped.drv'.
error: 1 dependencies of derivation '/nix/store/bbr1ryr00ps0k6mrm4nxs9az5kwvxgf5-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kxvf6n7j9mcx2iih02niqfx658rwky8f-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n3b6zqnvsg5h2w1a04h8p0lw95byrsh1-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w62ja5yx5nb7gr9wm6nn7fd5n8shh5jz-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1yrhaf4ivqnyi84h4yc1vnicn6yiy1il-tmpfiles.d.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hfx1bjp3c29yqsw8bn9j1ai0917zq8sa-tmpfiles.d.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z9gc35w5a5gs7ss1fgpyk2i168xzylwp-nixos-system-pavel-nix-24.05.20240329.0f20cd1.drv' failed to build
```

Well, if I try to downgrade sddm, I get this.

**Comment by Cu3PO42** [comment]
You are experiencing this issue likely because Plasma 6 sets `services.displayManager.sddm.extraPackages` and includes Qt6 packages. If you set that option to `mkForce []`, the error would likely disappear. Of course other issues might crop up if you were implicitly relying on those packages existing.

**Comment by EndlessPeak** [comment]
> You are experiencing this issue likely because Plasma 6 sets `services.displayManager.sddm.extraPackages` and includes Qt6 packages. If you set that option to `mkForce []`, the error would likely disappear. Of course other issues might crop up if you were implicitly relying on those packages existing.

I have apply `lib.mkForce` in my code like this:

```nix
services = {
    xserver.enable = true;

    desktopManager.plasma6= {
        enable = true;
        enableQt5Integration = true;
    };

    # Enable Sddm
    displayManager.sddm = {
       enable = true;
       package = lib.mkForce pkgs.libsForQt5.sddm;
       theme = "${import ./sddm-theme.nix { inherit pkgs;}}";
    };
};
```

but nix still complain 
```
error: builder for '/nix/store/gmcpabrr9aa24gsh5c6iw3266psxmirg-sddm-wrapped.drv' failed with exit code 1;
       last 3 log lines:
       > Error: detected mismatched Qt dependencies:
       >     /nix/store/r8a6ss3xnc9j4yrgajbvy8wnn359cpkq-qtbase-6.7.0
       >     /nix/store/pblcbcbida7wmpyb6brhcasrj8rg5jpk-qtbase-5.15.12-dev
       For full logs, run 'nix log /nix/store/gmcpabrr9aa24gsh5c6iw3266psxmirg-sddm-wrapped.drv'.
```

did I miss something?

**Comment by DakshG07** [comment]
FWIW I managed to get my theme working with this:
```nix
  services.displayManager.sddm = {
    package = pkgs.lib.mkForce pkgs.libsForQt5.sddm;
    extraPackages = pkgs.lib.mkForce [ pkgs.libsForQt5.qt5.qtgraphicaleffects ];
    enable = true;
    theme = "corners";
  };
```
The `extraPackages` you need may vary with your theme...I started by setting it empty and then just adding the packages it told me were missing.

**Comment by willswats** [comment]
I'm experiencing this issue with the `catppuccin-sddm` package in nixpkgs on Hyprland, however, using [this](https://github.com/NixOS/nixpkgs/blob/6518ca2f6e57ee27876fef6f1e72b40cad0fbd04/pkgs/data/themes/catppuccin-sddm/default.nix) `catppuccin-sddm` package from an old PR works fine for me.

```
May 13 22:50:27 will-desktop sddm[1770]: The theme at "/run/current-system/sw/share/sddm/themes/catppuccin-mocha" requires missing "/nix/store/3a8ilym4yp223ppv4pijmnmi2paxr5hq-sddm-wrapped/bin/sddm-greeter-qt6" . Using fallback theme.
```

**Comment by ElysaSrc** [comment]
> I'm experiencing this issue with the `catppuccin-sddm` package in nixpkgs on Hyprland, however, using [this](https://github.com/NixOS/nixpkgs/blob/6518ca2f6e57ee27876fef6f1e72b40cad0fbd04/pkgs/data/themes/catppuccin-sddm/default.nix) `catppuccin-sddm` package from an old PR works fine for me.
> 
> ```
> May 13 22:50:27 will-desktop sddm[1770]: The theme at "/run/current-system/sw/share/sddm/themes/catppuccin-mocha" requires missing "/nix/store/3a8ilym4yp223ppv4pijmnmi2paxr5hq-sddm-wrapped/bin/sddm-greeter-qt6" . Using fallback theme.
> ```

By default, SDDM falls back to Qt5. You have to override the package version with this:

```nix
displayManager.sddm.package = pkgs.kdePackages.sddm;
```

**Comment by willswats** [comment]
> > I'm experiencing this issue with the `catppuccin-sddm` package in nixpkgs on Hyprland, however, using [this](https://github.com/NixOS/nixpkgs/blob/6518ca2f6e57ee27876fef6f1e72b40cad0fbd04/pkgs/data/themes/catppuccin-sddm/default.nix) `catppuccin-sddm` package from an old PR works fine for me.
> > ```
> > May 13 22:50:27 will-desktop sddm[1770]: The theme at "/run/current-system/sw/share/sddm/themes/catppuccin-mocha" requires missing "/nix/store/3a8ilym4yp223ppv4pijmnmi2paxr5hq-sddm-wrapped/bin/sddm-greeter-qt6" . Using fallback theme.
> > ```
> 
> By default, SDDM falls back to Qt5. You have to override the package version with this:
> 
> ```nix
> displayManager.sddm.package = pkgs.kdePackages.sddm;
> ```

That fixed it, thanks for your help. Strangely the theme didn't apply until I rebooted as well, previously I was just exiting hyprland with `hyprtcl dispatch exit`, which did work for applying some other sddm themes I tried.
