### ISSUE TITLE
$NIX_CC/nix-support/dynamic-linker no longer exists

### ISSUE THREAD

**Issue by rushmorem** [NixOS/nixpkgs#29278]
On NixOS `17.09.git.b50193f` `dynamic-linker` no longer exists in `$NIX_CC/nix-support/` which is breaking some packages. Please see https://github.com/mozilla/nixpkgs-mozilla/issues/66#issuecomment-328828611 for details.

**Comment by copumpkin** [comment]
cc @Ericson2314

**Comment by rushmorem** [comment]
> This was fixed by 460df30, so you should update your 17.09 tree.

Awesome! Thank you.
