### ISSUE TITLE
Update request: universal-android-debloater 0.6.2 → 1.0.2

### ISSUE THREAD

**Issue by voronind-com** [NixOS/nixpkgs#292791]
- Package name: universal-android-debloater
- Latest released version: 1.0.2

- Current version on the unstable channel: 0.6.2
- Current version on the stable/release channel: None

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@KamilaBorowska 

-----

Note for maintainers: Please tag this issue in your PR.
The app had a major release update. Thank you!
Current version is broken due to lists format change.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CutestNekoAqua** [comment]
> Current version is broken due to lists format change.
care to elab?
