### ISSUE TITLE
flameshot is broken on wlroots-based compositors because USE_WAYLAND_GRIM is not set.

### ISSUE THREAD

**Issue by dmayle** [NixOS/nixpkgs#292700]
### Describe the bug
flameshot has two backends, one that works in KDE, and one that works in wlroots-based compositors, but the flag USE_WAYLAND_GRIM must be set in order to enable it.

### Steps To Reproduce
1. Try to use flameshot in wlroots-based compositor like sway

### Expected behavior
It works

### Screenshots
[nix-shell:~]$ env XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway QT_QPA_PLATFORM=wayland flameshot gui
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.

### Notify maintainers

@hamhut1066

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nixpath/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dmayle** [comment]
The flag upstream:
https://github.com/flameshot-org/flameshot/blob/3d21e4967b68e9ce80fb2238857aa1bf12c7b905/src/CMakeLists.txt#L222

**Comment by dmayle** [comment]
It turns out that this flag is not yet available in a release.  To use it, I created the following package override:
```console
  flameshotGrim = pkgs.flameshot.overrideAttrs (oldAttrs: {
    src = pkgs.fetchFromGitHub {
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "3d21e4967b68e9ce80fb2238857aa1bf12c7b905";
      sha256 = "sha256-OLRtF/yjHDN+sIbgilBZ6sBZ3FO6K533kFC1L2peugc=";
    };
    cmakeFlags = [
      "-DUSE_WAYLAND_CLIPBOARD=1"
      "-DUSE_WAYLAND_GRIM=1"
    ];
    buildInputs = oldAttrs.buildInputs ++ [ pkgs.libsForQt5.kguiaddons ];
  });
```

and now flameshot works!

For home-manager I also added the following:

```console
services.flameshot = {
  enable = true;
  package = flameshotGrim;
};
```

**Comment by eclairevoyant** [comment]
Not sure I'd call this a bug if there's no release with this code, though it seems like it will be some time before the next release: https://github.com/flameshot-org/flameshot/issues/3443

**Comment by KFearsoff** [comment]
I can confirm that the overlay above works for me.

There's a small caveat: `grim` should be available in the PATH, otherwise the setup will be a little more janky.

**Comment by dmayle** [comment]
> Not sure I'd call this a bug if there's no release with this code, though it seems like it will be some time before the next release: [flameshot-org/flameshot#3443](https://github.com/flameshot-org/flameshot/issues/3443)

Whether or not there's a release, it's still a bug.  There were more attempts to fix this 2-3 years back, but as you can read in that linked issue, the authors are currently not working on updates.

Since there's no official release, it might not make sense to issue an interim package update, but as long as I have my working flameshot, I'm happy.  I just wanted to share this with others who run into the same problem

**Comment by dmayle** [comment]
> I can confirm that the overlay above works for me.
> 
> There's a small caveat: `grim` should be available in the PATH, otherwise the setup will be a little more janky.

I hadn't noticed that... I've just updated buildInputs (to add grim) and removed grim from my default home-manager environment... I think that should take care of it, but I'll test to be sure.

**Comment by dmayle** [comment]
> I can confirm that the overlay above works for me.
> 
> There's a small caveat: `grim` should be available in the PATH, otherwise the setup will be a little more janky.

After using for awhile, I can confirm.  You need to add grim into your environment in order for this to work consistently.

**Comment by Kreyren** [comment]
I can't seem to get that to work on GNOME see https://github.com/NiXium-org/NiXium/pull/115

**Comment by eclairevoyant** [comment]
> I can't seem to get that to work on GNOME

Yes, grim is for wlroots-based compositors, not mutter.

**Comment by Kreyren** [comment]
> Yes, grim is for wlroots-based compositors, not mutter. -- @eclairevoyant (https://github.com/NixOS/nixpkgs/issues/292700#issuecomment-2227520402)

Unrelated to this issue then? -> Krey, make a new issue?

**Comment by eclairevoyant** [comment]
Sure, but I don't know if upstream even supports mutter; doesn't seem like it based on https://github.com/flameshot-org/flameshot/issues/3639

**Comment by Kreyren** [comment]
> Sure, but I don't know if upstream even supports mutter; doesn't seem like it based on [flameshot-org/flameshot#3639](https://github.com/flameshot-org/flameshot/issues/3639), [flameshot-org/flameshot#3473](https://github.com/flameshot-org/flameshot/issues/3473), etc. -- @eclairevoyant (https://github.com/NixOS/nixpkgs/issues/292700#issuecomment-2227623282)

For context it's currently broken, but it worked with the fix in https://github.com/NixOS/nixpkgs/issues/292700#issuecomment-1974953531 until recently, so thought it was relevant to this.

**Comment by eclairevoyant** [comment]
There's a 24.11 release coming in 10 days, you could just wait for that...

**Comment by DxCx** [comment]
Just for future readers like myself, now that its in nix pkgs master, 
based on
https://wiki.nixos.org/wiki/Flameshot
the suggested way to use it is
```
services.flameshot = {
  enable = true;
  package = pkgs.flameshot.override { enableWlrSupport = true; };
};
```

**Comment by BlueskyFR** [comment]
Tried the nixpkgs current using Hyprland, and `flameshot gui` just returns with a non-zero exit code, don't know what's happening...

The above overlay works though, but the screen selection is zoomed compared to what's actually displayed on-screen.

So no fix for now.

**Comment by eclairevoyant** [comment]
There's no need for any overlay; the simple override above should work.
As for the new issue... file a new issue.
