### ISSUE TITLE
NixOS managing ZFS data sets with spaces in the name

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#29273]
## Issue description
NixOS silently fails when attempting to mount a ZFS data set which has a space in the name

### Steps to reproduce
Assuming you have a zpool called "tank"
Scenario 1:
- sudo zfs create tank/Home\ Videos
- sudo zfs set mountpoint=legacy
- add to your nixos config: fileSystems."/data/Home Videos" = { device = "/tank/Home Videos"; fsType = "zfs"; };
- sudo nixos-rebuild switch
- note that /data/Home Videos is not mounted

Scenario 2:
- sudo zfs rename /tank/Home\ Videos /tank/homevideos
- modify your nixos config to reflect this change: fileSystems."/data/Home Videos" = { device = "/tank/homevideos"; fsType = "zfs"; };
- sudo nixos-rebuild switch
- my system dropped me out of my X11 session and put me into a shell where i couldn't do anything, and rebooting brought me to the same shell where i couldn't do anything...
- reboot and rollback

## Technical details
All my other zfs data sets which have no space in the name work fine and when i both rename /tank/Home Videos to /tank/homevideos as well as the mount point from /data/Home Videos to /data/homevideos everything works fine. I'll also make note that a rogue /data/Home directory was created at some point by nixos during this process.

* System: 17.09beta487.773268eede (Hummingbird)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.09beta487.773268eede"
* Sandboxing enabled: build-use-sandbox = false

**Comment by paraseba** [comment]
I had the same issue but using btrfs subvolumes. Did you find a way to solve it?

**Comment by aanderse** [comment]
I simply renamed the data set to remove the space and everything worked properly. I had experimented around with a few different ways of escaping text and nothing seemed to work. I'm guessing code needs to be written for additional checks on what NixOS generates for an /etc/fstab or whatever.

Sorry I couldn't be of more help.

**Comment by paraseba** [comment]
Apparently fstab requires it's own [escaping](https://wiki.archlinux.org/index.php/fstab) logic, space is `\040`, etc.

This is a corner case, but a pretty dangerous one, nixos-rebuild switch will hang your X11 session and so. I think `fileSystems` should handle this situation by implementing the right escaping.
