### ISSUE TITLE
Build failure: python312Packages.pyarrow

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#292832]
### Steps To Reproduce

1. build `python312Packages.pyarrow` (currently on staging-next)

### Build log

```
pyarrow> -- Found Python3: /nix/store/dqsflsigjcxisziiynrxlbsm2y71m4bq-python3-3.12.2/bin/python3.12 (found version "3.12.2") found components: Interpreter Development.Module NumPy 
pyarrow> CMake Error at cmake_modules/FindPython3Alt.cmake:77 (message):
pyarrow>   Python 3 config failure:
pyarrow> 
pyarrow>   Traceback (most recent call last):
pyarrow> 
pyarrow>     File "<string>", line 1, in <module>
pyarrow> 
pyarrow>   ModuleNotFoundError: No module named 'distutils'
pyarrow> 
pyarrow> Call Stack (most recent call first):
pyarrow>   CMakeLists.txt:262 (find_package)
pyarrow> 
pyarrow> 
pyarrow> -- Configuring incomplete, errors occurred!
pyarrow> error: command '/nix/store/9walp7knvqvmnpp9pqwjsdpnx2524ack-cmake-3.28.3/bin/cmake' failed with exit code 1
```

### Additional context
Upstream provides Python 3.12 wheels on PyPi. https://pypi.org/project/pyarrow/

I need this for home-assistants Python 3.12 migration by end of March 2024 at the latest.

### Notify maintainers

@cpcloud @veprbl 

### Metadata
Issue exists on c15db11bbf7f8597d7ec9f35aea4c7dea05f5b6c

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
We can patch https://github.com/apache/arrow/blob/main/cpp/cmake_modules/FindPython3Alt.cmake#L70 to use https://github.com/apache/arrow/blob/main/python/setup.py#L29

**Comment by mweinelt** [comment]
Thanks for the sleuthing. Fix incoming.

**Comment by SuperSandro2000** [comment]
Just did the same in the background https://github.com/NixOS/nixpkgs/commit/740418c176a576f0ee675120c6c5028b9755f26f and opened https://github.com/apache/arrow/pull/40322
