### ISSUE TITLE
Nouveau Gsp loading freezes system

### ISSUE THREAD

**Issue by cronyakatsuki** [NixOS/nixpkgs#292860]
### Describe the bug
Using kernel version 6.7 or 6.8 and enabling nouveau gsp loading freezes my system, but loading regular nvidia driver's system run's completely fine. I'm on a nvidia optimus laptop with an amd cpu.

### Steps To Reproduce
1. Set `boot.kernelPackages = pkgs.linuxPackages_latest;`
2.  Enable gps loading using:
```nix
boot.kernelParams = [
  "nouveau.config=NvGspRM=1"
  "nouveau.debug=info,VBIOS=info,gsp=debug"
];
```
3. Reboot
4. get suprised with a frozen system

### Expected behavior
System boots up normally and am able to use nvk with gsp drivers.

### Additional context
If I make sddm and plasma use x11, the system won't freeze until atleast I don't load any vulkan program or I shutdown/reboot.

If I keep them on wayland the moment sddm should load, or plasma the system just freezes and I have to do a hard poweroff.

Journalctl -b logs for a boot with sddm set to wayland, [gsp.txt](https://upfast.cronyakatsuki.xyz/files/gsp.txt)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by EQuioMaX** [comment]
Facing the same issue, I have a 5800HS with an RTX 3060 Max-Q. The proprietary driver specialisation works fine, but loading GSP with nouveau gives me a black screen when SDDM should start.
```
ν ❯ nix run nixpkgs#nix-info -- -m
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`

**Comment by cronyakatsuki** [comment]
@EQuioMaX tnx for you input, didn't even consider trying to load only nouveau without loading GSP and like you said, then it works normally but the performance isn't by any means "good".

But the moment gsp loads the system freezes.

**Comment by EQuioMaX** [comment]
I haven't tried NVK on other distros, is this a NixOS-specific issue?

**Comment by cronyakatsuki** [comment]
> I haven't tried NVK on other distros, is this a NixOS-specific issue?

I personally tried to get arch on my system but arch also had some issues with my system with kernel 6.7, where it wouldn't shutdown properly but I'm not sure if this is connected to nouveau gsp.

**Comment by kotatsuyaki** [comment]
The `kernel NULL pointer dereference` message looks like this [NULL pointer when loading nouveau with NvGspRm=1](https://gitlab.freedesktop.org/drm/nouveau/-/issues/343) reported on drm/nouveau.  It's reported that kernel 6.8.1 on Ubuntu works without the panic, and I can boot up nouveau with `nouveau.config=NvGspRM=1` on kernel 6.8.3 on NixOS (Plasma 6 Wayland) without the crash, so I think this is resolved.

**Comment by cronyakatsuki** [comment]
> The `kernel NULL pointer dereference` message looks like this [NULL pointer when loading nouveau with NvGspRm=1](https://gitlab.freedesktop.org/drm/nouveau/-/issues/343) reported on drm/nouveau. It's reported that kernel 6.8.1 on Ubuntu works without the panic, and I can boot up nouveau with `nouveau.config=NvGspRM=1` on kernel 6.8.3 on NixOS (Plasma 6 Wayland) without the crash, so I think this is resolved.

I just tried it out personally, and the system boots and launched normally. But the system doesn't pick up the nouveau drive which is a different issue so I will be closing this one.
