### ISSUE TITLE
ghcWithPackages failing on nix on Debian

### ISSUE THREAD

**Issue by izuk** [NixOS/nixpkgs#29299]
## Issue description

After a recent (Debian) upgrade, "xmonad --recompile" started failing, complaining that the XMonad module wasn't found.  After some digging around, I found this:

$ `nix-shell -p "haskellPackages.ghcWithPackages (pkgs: [pkgs.xmonad pkgs.xmonad-contrib])"`
$ `cd /nix/store/ydrfjc170zb161wg25na7nxffqxkph49-ghc-8.0.2-with-packages`
$ `ls lib/ghc-8.0.2`

array-0.5.1.1        deepseq-1.4.2.0    ghci-usage.txt     include              rts                        unix-2.7.2.1
base-4.9.1.0         directory-1.3.0.0  ghc-prim-0.5.0.0   integer-gmp-1.0.0.1  settings                   xhtml-3000.2.1
bin                  filepath-1.4.1.1   ghc-usage.txt      latex                template-haskell-2.11.1.0
binary-0.8.3.0       ghc-8.0.2          haskeline-0.7.3.0  package.conf.d       template-hsc.h
bytestring-0.10.8.1  ghc-boot-8.0.2     hoopl-3.10.2.1     platformConstants    terminfo-0.4.0.2
Cabal-1.24.2.0       ghc-boot-th-8.0.2  hpc-0.6.0.3        pretty-1.1.3.3       time-1.6.0.1
containers-0.5.7.1   ghci-8.0.2         html               process-1.4.3.0      transformers-0.5.2.0

Where's xmonad?

$ `ls bin`

ghc        ghci        ghc-pkg        haddock            hp2ps  hsc2hs  runghc-8.0.2  xmonad                                                
ghc-8.0.2  ghci-8.0.2  ghc-pkg-8.0.2  haddock-ghc-8.0.2  hpc    runghc  runhaskell              

Hmmm... the binary is there, but not the library?!

### Steps to reproduce

See above.

## Technical details

* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "18.03pre114739.d0d905668c"

**Comment by vaibhavsagar** [comment]
Is this still an issue with recent `nixpkgs`?

**Comment by izuk** [comment]
Seems to be working now.
