### ISSUE TITLE
haskellPackages.statgrab fails with an underlying library dependency failure

### ISSUE THREAD

**Issue by savannidgerinel** [NixOS/nixpkgs#29297]
## Issue description

Attempting to install `haskellPackages.statgrab` results in a compile time failure because the underlying statgrab C library was not found:

```
Setup: Missing dependency on a foreign library:
* Missing (or bad) header file: statgrab.h
* Missing C library: statgrab
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

### Steps to reproduce

Install `haskellPackages.statgrab`:

`nix-env -f '<nixos>' -iA haskellPackages.statgrab`

Or, depend on `statgrab` in a Haskell project.

## Technical details

* System: NixOS: 17.03.1645.08bc48049c (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.03.1769.da2159dafb
* Sandboxing enabled: false

**Comment by savannidgerinel** [comment]
I have a fix for this that I have tested locally, but have not walked through the entire contributions process.

**Comment by ryantm** [comment]
statgrab currently compiles fine
