### ISSUE TITLE
Setting -u in stdenv to catch invalid variables

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#29296]
## Issue description

I propose we do ```set -u```  in ```stdenv``` to ensure that we catch references to unset variables and blow up accordingly.

One example is this fix: https://github.com/NixOS/nixpkgs/commit/3f5611422309593a2cb609ac13a690134408c56f

Previously the derivation referenced ```$pname``` which should have been ```${pname}```. In this case, the impact was rather limited admittedly, but there is in all likelihood a number of bugs lurking because files end up in the wrong directory.

Changing this will probably cause a lot of breakage (assuming this is a widespread issue).

Cc: @Ericson2314 @Profpatsch @NeQuissimus @vcunat @LnL7

**Comment by joachifm** [comment]
As I recall this was already proposed but one argument against was the amount of noise required to handle potentially uninitialized variables (i.e., `${foo:-}` all over the place).

**Comment by Ericson2314** [comment]
Actually we do. I did merge https://github.com/NixOS/nixpkgs/pull/28057. Careful use of `set +u` prevents package's hooks from also being `set -u`'d, as that would be a huge breaking change.

I would be for doing that too.

**Comment by joachifm** [comment]
@Ericson2314 ah, that's the one I was thinking of, I hadn't noticed it ended up being merged, so much has happened with stdenv lately :)

**Comment by Profpatsch** [comment]
A first step would be for somebody to find out how many packages wou

**Comment by peterhoeg** [comment]
I wasn't aware of the earlier PR.

> This is probably best paired with Nix defining env vars (it doesn't right now), so that more variables are always defined.

Such as?

**Comment by Ericson2314** [comment]
A few from memory: `configureFlags`, `nativeBuild`, `buildInputs` when empty; `dontConfigure` `dontBuild` `doCheck`, `doInstallCheck` when false.

**Comment by copumpkin** [comment]
We need a `set -u` for everything but a set of variables that are allowed to be unset 😄

**Comment by peterhoeg** [comment]
Surely it wouldn't be that noisy to change references to ```configureFlags``` and the likes to ```${configureFlags:-""}. Or am I grossly underestimating this?

**Comment by Ericson2314** [comment]
@peterhoeg It isn't---I think it's worth it either way.

**Comment by peterhoeg** [comment]
Another option would be to use an approach similar to what the hardening guys did so that each derivation can simply disable the "pedanticHook" in case it causes problems. Of course, talk is cheap.... ;-)

**Comment by Ericson2314** [comment]
Somebody that isn't me should take the lead on this :). Grep for `set +u` and remove them all, then see what happens!

**Comment by peterhoeg** [comment]
Closing as @Ericson2314 is the *man*!

Ref #72347.
