### ISSUE TITLE
nextcloud-client not staying logged in 

### ISSUE THREAD

**Issue by Flameopathic** [NixOS/nixpkgs#293019]
### Describe the bug
`nextcloud-client` does not stay logged in after reopen, instead asks for web authentication again

### Steps To Reproduce
1. install `nextcloud-client`
2. log in to an account
3. exit and reopen Nextcloud client

### Expected behavior
Nextcloud client remains logged in and begins syncing on reopen

### Additional context
I have just recently started using NixOS and am not using gnome or plasma, I may just not have the necessary keyring package installed. Please forgive me if this ends up being the case, but if that does reveal itself to be the problem, please add the necessary packages as dependencies or have some sort of documentation that explains prerequisites.

I have looked through #60012 thoroughly but do not know how I would apply the information as I am not using gnome. 

### Notify maintainers
@Kranzes @SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.4976.79baff8812a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kranzes** [comment]
This is a super flaky bug with libsecret and the keyring. Essentially you need to enable some sort of keyring (I use gnome-keyring) and see if it works, or try playing around with it (e.g. creating/deleting stores). Also attempt to have it unlock automatically on login.

**Comment by Flameopathic** [comment]
awesome, i was using gnome-keyring wrong and just adding `services.gnome.gnome-keyring.enable = true;" to my configuration.nix and a reboot solved my problem. thanks for the rec!
