### ISSUE TITLE
 Inconsistency in Package Naming Rules Regarding Version Attribute

### ISSUE THREAD

**Issue by Hakim-CS** [NixOS/nixpkgs#293064]
Issue Description:

The current package naming rules stipulate that "The version attribute must start with a digit." However, a significant number of packages deviate from this guideline. Many of these packages have a version starting with "unstable-". There have been instances where I was instructed to change a version starting with a digit to one starting with "unstable-".

This inconsistency raises the question of whether common practice is incorrect or if the documentation itself needs clarification.

Proposed Solution:

I propose adjusting the documentation to align with common practice. Versions should either begin with a number or with the string "unstable-" followed by a YYYY-MM-DD date. This adjustment would provide clarity and consistency for package versioning.

**Comment by lolbinarycat** [comment]
related: #291729
