### ISSUE TITLE
Plasma 6 KDE Connect Incompatible Version

### ISSUE THREAD

**Issue by scientiac** [NixOS/nixpkgs#293184]
### Describe the bug
Could not load plugin from /nix/store/6jmvrs99zl30yz4y6vfrbkl3p5wn41vp-kdeconnect-kde-23.08.5/lib/qt-5.15.12/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kdeconnect.so: The plugin '/nix/store/6jmvrs99zl30yz4y6vfrbkl3p5wn41vp-kdeconnect-kde-23.08.5/lib/qt-5.15.12/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kdeconnect.so' uses incompatible Qt library. (5.15.0) [release]

### Steps To Reproduce
Install plasma 6 and enable kde connect.

### Expected behavior
The applet doesn't show up and the settings show this error:
![image](https://github.com/NixOS/nixpkgs/assets/58177655/c34c2fba-ac32-4c3e-9484-73bf0e107a49)

### Additional context
Plasma recently updated to version 6 and I am in the unstable branch.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(scientiac): `""`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Did you remember to replace `libsForQt5.kdeconnect-kde` with `kdePackages.kdeconnect-kde` in your config? I'm 99.9% sure that would be the issue, as kdeconnect works for me with the latter option set.

**Comment by physics-enthusiast** [comment]
> Did you remember to replace `libsForQt5.kdeconnect-kde` with `kdePackages.kdeconnect-kde` in your config? I'm 99.9% sure that would be the issue, as kdeconnect works for me with the latter option set.

I made an earlier (now deleted) comment suggesting something similar, but upon further investigation, shouldn't [this](https://github.com/NixOS/nixpkgs/blob/1536926ef5621b09bba54035ae2bb6d806d72ac8/nixos/modules/services/x11/desktop-managers/plasma6.nix#L274) set the correct package automatically? At least, assuming @scientiac enabled Plasma 6 via ```services.xserver.desktopManager.plasma6.enable = true```.

**Comment by chewblacka** [comment]
> This fixed the issue, but there should have been a notice or warning or an error like “libsForQt5” is replaced by “kdePackages” like nix always does… Should I close the issue?

Ideally some kind of message / warning could be given, but probably not straight forward to implement. I think issue can be closed.

**Comment by NireBryce** [comment]
fwiw I went from gnome and X to plasma6 and wayland off the wiki and have the same issue.

**Comment by jmarmstrong1207** [comment]
> > This fixed the issue, but there should have been a notice or warning or an error like “libsForQt5” is replaced by “kdePackages” like nix always does… Should I close the issue?
> 
> Ideally some kind of message / warning could be given, but probably not straight forward to implement. I think issue can be closed.

**Comment by joshspicer** [comment]
FWIW I had (for whatever reason, don't remember) `kdeconnect` listened under system packages [in my config](https://github.com/joshspicer/nixos-config/blob/7741523f5530345a021144565b6e589873cbc118/hosts/framework/configuration.nix#L165) that was causing this to occur.  Removing that package got rid of the error
