### ISSUE TITLE
Update request: roon-server 2.0-1272 → 2.0-1368

### ISSUE THREAD

**Issue by Ramblurr** [NixOS/nixpkgs#293281]
- Package name: roon-server
- Latest released version: 2.0-1368

- Current version on the unstable channel: 2.0-1272
- Current version on the stable/release channel: 2.0-1272

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@lovesegfault @Steell 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
https://github.com/NixOS/nixpkgs/pull/292253

**Comment by Ramblurr** [comment]
:( I searched issues but not PRs

**Comment by pbsds** [comment]
done in https://github.com/NixOS/nixpkgs/pull/295971
