### ISSUE TITLE
NixOS module request: sunshine

### ISSUE THREAD

**Issue by Cryolitia** [NixOS/nixpkgs#293298]
**Project description**

Sunshine has already been packaged here in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/sunshine/default.nix

But it doesn't come out of the box just by `nix run nixpkgs#sunshine`, according to https://www.reddit.com/r/NixOS/comments/19137rt/getting_sunshine_to_run/ and https://www.reddit.com/r/NixOS/comments/12bjfam/sunshine_error/ and https://discourse.nixos.org/t/sunshine-self-hosted-game-stream/25608 , at least it needs a `security.wrappers` and maybe `boot.kernelModules = [ "uinput" ];` . It would be better if we could add a NixOS module for it to make it availale just by sth. like `services.sunshine.enable` or `programs.sunshine.enable` .

CC maintainer @devusb 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by devusb** [comment]
This has been on my to-do list for ages :) The module itself wouldn't be a huge deal, and I think I have a plan for tests, just need some time to work on it.

**Comment by so-lar-is** [comment]
I actually had started working on this a while ago. My module can create valid sunshine.conf and apps.json files (i.e. they work when I start sunshine manually) and open then necessary ports, however I couldn't get the systemd service to work properly. If I recall correctly, the issue was related getting access to the screen.

Here is what I have so far, maybe it can help someone:
https://gist.github.com/so-lar-is/85cc71eff5d2cf4f5e362a2c17881302

**Comment by devusb** [comment]
Thanks @so-lar-is! I used yours as inspiration and opened https://github.com/NixOS/nixpkgs/pull/294641 for this. It's still a draft -- I need to work on the tests -- but any testing or comments are welcome. I've tested on Plasma 6 + Wayland + AMD and seems to work, have not tested much with xorg or NVIDIA.

**Comment by devusb** [comment]
Think it's got all the functionality I had planned -- marked as ready for review.

**Comment by tymscar** [comment]
Works great on nvidia + xorg too.

The only issue is that it doesent use nvenc. For that I use this workaround, would be great if you could add it to the service, maybe with a "useCuda" flag: https://github.com/NixOS/nixpkgs/issues/272221#issuecomment-1840482987
