### ISSUE TITLE
`pwm-lpss` and `pwm-lpss-platform` kernel modules missing

### ISSUE THREAD

**Issue by vifino** [NixOS/nixpkgs#293223]
### Describe the bug
The [`pwm-lpss`](https://www.kernelconfig.io/config_pwm_lpss) and [`pwm-lpss-platform`](https://www.kernelconfig.io/config_pwm_lpss_platform) kernel modules are missing which results in the lack of backlight control on devices such as the [GPD Pocket 1](https://nixos.wiki/wiki/GPD_Pocket), GPD Win 1 and other Tables.

### Steps To Reproduce
1. Boot an affected device (GPD Pocket 1)
2. Observe i915 message:
 `[    2.245244] i915 0000:00:02.0: [drm] *ERROR* [CONNECTOR:114:DSI-1] Failed to get the SoC PWM chip`
3. Try to control backlight, it doesn't work

### Expected behavior
Backlight control works.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Fractal147** [comment]
Was watching - can confirm pulling my kernel from unstable-nixos-small now includes pwm, pwm-crc, pwm-lpss etc in /proc/config.gz.

**Comment by vifino** [comment]
Glad I wasn't the only one profiting from this change. ;)
