### ISSUE TITLE
Document docbook schema settings for different editors

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#29324]
@grahamc asked me to create an issue to document into nixpkgs manual how editors should be configured to validate docbook xml to ease documentation editing.

**Comment by Mic92** [comment]
https://nixos.wiki/wiki/Docbook_Editor_Configuration

**Comment by disassembler** [comment]
Updated same wiki doc with my vim config.

**Comment by Mic92** [comment]
Vim configuration is now also straight forward thanks to @disassembler for adding the plugins to `vimPlugins`.

**Comment by Mic92** [comment]
Since we likely switch away from docbook, let's close this.
