### ISSUE TITLE
Build failure: Cemu 2.0-65

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#293319]
### Steps To Reproduce

1. build Cemu unstable

### Build log

```
https://paste.ee/p/Z3Shr
```

### Additional context

I am using a Plasma 6 configuration, completely based on the unstable branch. 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05pre590113.1536926ef562`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(cosmos): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
This was fixed already in #289867
follow progress here: https://nixpk.gs/pr-tracker.html?pr=289867
