### ISSUE TITLE
Polonium not installing in Plasma 6

### ISSUE THREAD

**Issue by etrigan63** [NixOS/nixpkgs#293409]
### Describe the bug
I added the libsForQt5.polonium nixpkg to my plasma 6 configuration but it does not appear despite being present in the kwin folder in /run/current-system/sw. Perhaps a package titled kdePackages.polonium needs to be added for Plasma 6.

### Steps To Reproduce
1. Add libForQt5.polonium to configuration.nix
2. sudo nixos-rebuild switch
3. reboot
4. polonium missing in kwin scripts control panel.

### Expected behavior
After adding polonium to configuration.nix, rebuilding, and rebooting, polonium should appear in the kwin scripts control panel.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lomenzel** [comment]
its because the latest release 0.6.0 is not compatible with plasma 6. there is a pre-release that is, but its currently not in the nixpkgs i guess

**Comment by etrigan63** [comment]
Should I request a version update to the latest build?
[image: photo]
Carlos Echenique
Photographer at  CE Photography
P  305.219.2433  <305.219.2433>
E  ***@***.***  ***@***.***>
W ce.photography
<https://mailtrack.io/l/dce29d1298ced17f1a7990d9fb8207a4931ea7f5?url=https%3A%2F%2Fcephotographic.com&u=3957204&signature=38a9c74908e43b18>
<https://mailtrack.io/l/47d8d10079c153a1520a6ef39d88862cbcf959a8?url=http%3A%2F%2Finstagram.com%2Fcephotographic&u=3957204&signature=07ea563810ead936>
<https://mailtrack.io/l/4300ae6c6548c49ccf1472d75ab41188e16eafcb?url=http%3A%2F%2Ffacebook.com%2Fcephotos&u=3957204&signature=05ff67aff59c7362>
<https://mailtrack.io/l/ba97a24623b749f1a72fcf0ae2b86f39dc7de0e4?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fechenique&u=3957204&signature=fed9194ce0149cfe>
