### ISSUE TITLE
ncurses apps get displayed incorrectly

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#29355]
## Issue description

Since my latest update, unstable: 01c3847b9c -> 1b1fc65505 curses apps get displayed incorrectly. This affects `mutt`, `bmon`, `ranger` but (strangely) not `tig`.

I could provide screenshots if required.

### Steps to reproduce

I don't know. Maybe it is enough to use these apps on 1b1fc65505

## Technical details

* System: 18.03pre115166.1b1fc65505 (Impala)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "18.03pre115166.1b1fc65505"
* Sandboxing enabled: build-use-sandbox = true

**Comment by mguentner** [comment]
Can confirm.

**Comment by matthiasbeyer** [comment]
I'm trying to build mutt with the ncurses version rolled back right now... still building though. Not sure whether `xfce4-terminal` (what I use) causes this or whether it is caused by `ncurses`... I can at least see the same issues in `xterm` with `bmon`

**Comment by mguentner** [comment]
It seems like that the issues I experience stem from the terminal used, I have no issues with `xterm` but with `alacritty` everything is distorted. Also running `bmon` and `atop` together with the terminal at the same revision (`nix-shell -p xterm atop`) presents no visual errors. Strange.

**Comment by matthiasbeyer** [comment]
You have no issues with `xterm`? Because I have, although not so much as with `xfce4-terminal`, though.

**Comment by rnhmjoj** [comment]
I don't see anything strange. Can you elaborate?

**Comment by vcunat** [comment]
I just noticed, some parts of the UI are shown on (slightly) bad places, in various ncurses apps (inside KDE konsole).

**Comment by vcunat** [comment]
Note: even the old versions of apps that used to work do this for me now (when ran from nix store directly).

**Comment by rnhmjoj** [comment]
I noticed transmission-remote-cli crashes when resizing the terminal (making the window smaller):
```
Traceback (most recent call last):
  File "/nix/store/0wzm7bz95r7l2h6sgri06cm8flm1bzzj-transmission-remote-cli-1.7.1/bin/.transmission-remote-cli-wrapped", line 3767, in <module>
    Interface()
  File "/nix/store/0wzm7bz95r7l2h6sgri06cm8flm1bzzj-transmission-remote-cli-1.7.1/bin/.transmission-remote-cli-wrapped", line 1000, in __init__
    self.run()
  File "/nix/store/0wzm7bz95r7l2h6sgri06cm8flm1bzzj-transmission-remote-cli-1.7.1/bin/.transmission-remote-cli-wrapped", line 1107, in run
    self.draw_title_bar()  # show shortcuts and stuff
  File "/nix/store/0wzm7bz95r7l2h6sgri06cm8flm1bzzj-transmission-remote-cli-1.7.1/bin/.transmission-remote-cli-wrapped", line 2761, in draw_title_bar
    self.draw_quick_help()
  File "/nix/store/0wzm7bz95r7l2h6sgri06cm8flm1bzzj-transmission-remote-cli-1.7.1/bin/.transmission-remote-cli-wrapped", line 2792, in draw_quick_help
    self.screen.insstr(0, self.width-len(line), line, curses.A_REVERSE)
_curses.error: insstr() returned ERR

```

**Comment by matthiasbeyer** [comment]
I'm not sure what causes this, but from what we know it could be

* ncurses 
* terminal
    * xfce4-terminal (@matthiasbeyer)
    * konsole (@vcunat)
    * alacritty (@mguenter)

or something else which is related to

* bmon
* mutt
* ncmpcpp
* htop
* ranger
* tig (just saw some misbehavings there despite my initial msg)

**Comment by matthiasbeyer** [comment]
I tried to rebuild `mutt` without that bump in version but as reported in https://github.com/NixOS/nixpkgs/issues/29368 it causes systemd and such things to be rebuild... and I really don't like that! :smile:

**Comment by aanderse** [comment]
I get this as well with the pass program which uses ncurses to prompt for a password over an ssh connection. I'm connecting to my NixOS box from a Windows program called MobaXterm over ssh.

Running current NixOS 17.09 beta.

**Comment by matthiasbeyer** [comment]
By the way: In my applications, when printing a `">"` I get `"&gt;"` printed in the terminal...
Maybe that's related to this issue and helps us debugging or locating this error?

**Comment by matthiasbeyer** [comment]
Fix as of

* System: 18.03pre115705.c8e7aab0c8 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre115705.c8e7aab0c8"
* Sandboxing enabled: build-use-sandbox = true

**Comment by rnhmjoj** [comment]
So we still don't what it was. I tried bisecting multiple times but got inconclusive results.

**Comment by matthiasbeyer** [comment]
I would guess it was ncurses, which got updated in the last batch AFAIK.

**Comment by fpletz** [comment]
It was an ncurses update that contained a broken terminfo file for xterm. Another ncurses bump fixed this issue and is currently on staging for 17.09.

**Comment by Infinisil** [comment]
I'm not sure if this is related, but I've had some weird glitches with ncmpcpp and cli-visualizer. What worked for me is doing `export TERM=xterm-termite`, which prevents glitches in both of those.
