### ISSUE TITLE
Package request: portproton

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#293567]
**Project description**

Project designed to make it easy and convenient to run Windows games on Linux for both beginners and advanced users. 

**Metadata**

* homepage URL: https://linux-gaming.ru
* source URL: https://github.com/Castro-Fidel/PortWINE
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
we have:
[Heroic](https://heroicgameslauncher.com/)
[Lutris](https://lutris.net/)
[Bottles](https://usebottles.com/)
and `steam-run` for this. i think this is plenty.

**Comment by kakazex** [comment]
no, it's not enough to run exe files outside of game launchers, steam and others only for game stores, they are not for everything.
