### ISSUE TITLE
gnome-shell acting strangely with mesa unstable on wayland

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#293581]
### Describe the bug

With current mesa unstable on wayland, gnome-shell loses all animations and has screen tearing. This occurs with gnome-shell on unstable as well as with gnome-shell on 23.11.

### Steps To Reproduce

1. Use `gnome-shell` wayland as your desktop environment
   ```nix
   services.xserver = {
       enable = true;
       libinput.enable = true;
       layout = "us";
       xkbVariant = "";
       displayManager = {
           defaultSession = "gnome";
           gdm = {
               enable = true;
               wayland = true;
           };
       };
       desktopManager = {
           gnome.enable = true;
       };
   };
   ```
2. Install `mesa` from unstable using:
   ```nix
    hardware.opengl = {
        enable = true;
        package = pkgs-unstable.mesa.drivers;
        package32 = pkgs-unstable.pkgsi686Linux.mesa.drivers;
        driSupport32Bit = true;
    };
    ```

### Expected behavior

No screen tearing, and animations should work.

### Screenshots

N.A. (I can't screenshot animations or screen tearing)

### Additional context

I use nix flakes.

### Notify maintainers

@primeos @vcunat

### Metadata

```console
[gavin@gavin-laptop-nixos-1:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.20240218.e0da498`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
I recommend against choosing mesa from a different nixpkgs version than your packages.  Often the mutual dependencies of mesa and the programs (e.g. gnome-shell) clash together.

**Comment by Pandapip1** [comment]
> I recommend against choosing mesa from a different nixpkgs version than your packages. Often the mutual dependencies of mesa and the programs (e.g. gnome-shell) clash together.

Notably, this happens when `gnome-shell` and `mesa` are both on unstable.

**Comment by primeos** [comment]
> Notably, this happens when gnome-shell and mesa are both on unstable.

Unfortunately this isn't necessarily enough - there's so much that can go wrong if you use Mesa from a different channel (or even if you just use certain graphical applications from a different channel).

**Comment by Pandapip1** [comment]
Turns out it was because the driver became llvmpipe. Not sure why that happened, but it's sorted now.
