### ISSUE TITLE
Build failure: mamba

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#293539]
### Steps To Reproduce

Mamba is marken as broken in unstable, likely 23.11 as well.

### Maintainers

@magnetophon @orivej 

Since I know you do lot’s of mao, @PowerUser64 you might be interested as well

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by magnetophon** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/299089
