### ISSUE TITLE
Build failure: surge-XT

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#293558]
### Steps To Reproduce

1. build surge-XT.

Get mismatch in fixed-output derivation error, git tag maybe added?

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/g97ilhgr8hvpn55d19gxcs1xjs6pfcxz-source.drv':
         specified: sha256-q6qs/OhIakF+Gc8Da3pnfkUGYDUoJbvee0o8dfrRI2U=
            got:    sha256-TBDiIl3gfjzV28U5UnPUfY1tpTpAgM/f6c4GlVIeBU0=
error: 1 dependencies of derivation '/nix/store/ndz0bqdg6pzixnr3p448synmg9yl8si1-surge-XT-1.3.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nix1dz86rj9cnn0qhfzib5zcahgw9kbb-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9als1nild60j3z6wgl6njifv6yifmzjm-nixos-system-bestos-24.05.20240303.b8697e5.drv' failed to build
```

### Additional context

Also reported in https://github.com/NixOS/nixpkgs/pull/286967

Certainly due to https://github.com/NixOS/nixpkgs/issues/8567

### Notify maintainers

@magnetophon 

### Metadata

From unstable, b8697e57f10292a6165a20f03d2f42920dfaf973

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jmarmstrong1207** [comment]
Tested this myself and indeed the hash is different for me vs yours as you stated before in #286967

**Comment by adham-omran** [comment]
I'm also having the same issue, running `unstable`.
```
error: hash mismatch in fixed-output derivation '/nix/store/g97ilhgr8hvpn55d19gxcs1xjs6pfcxz-source.drv':
         specified: sha256-q6qs/OhIakF+Gc8Da3pnfkUGYDUoJbvee0o8dfrRI2U=
            got:    sha256-xjI+hslSq5zkinfCBoMCfcbNx8rPXqxNJS7+4gZ/Plk=
error: 1 dependencies of derivation '/nix/store/ndz0bqdg6pzixnr3p448synmg9yl8si1-surge-XT-1.3.1.drv' failed to build
```

**Comment by magnetophon** [comment]
See https://github.com/NixOS/nixpkgs/pull/296917 for a fix.
