### ISSUE TITLE
upgrade network manager from 1.6.2 to 1.8

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29362]
## Issue description
I've trouble connecting to an L2TP VPN. A colleague of mine on fedora told me that upgrading to the latest network manager fixed his problems so I wonder if that could be my case too.

My hopes are also that it fixes some problems when multihoming (some items are present in https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/NEWS?h=1.8.2).

I am also looking for any tutorial about L2TP VPN configuration. The wiki vpn page being pretty empty.

**Comment by bkchr** [comment]
I created a pullrequest for updating the package :) 

https://github.com/NixOS/nixpkgs/pull/29375

**Comment by teto** [comment]
The patch has been merged hence I close this. Thanks @bkchr
