### ISSUE TITLE
Build failure: dk-2.0

### ISSUE THREAD

**Issue by philopence** [NixOS/nixpkgs#293613]
### Steps To Reproduce

1. build dk

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/h0vlpgi2hx7fv92dh880c38sv96slbdz-source.drv':
         specified: sha256-AzvpvcH0S8WJNzYXMwvF6CIRDXnh/c6B8g2iWDQI6Qw=
            got:    sha256-wuEsfzy4L40tL/Lb5R1jMFa8UAvAqkI3iEd//D7lxGY=
error: 1 dependencies of derivation '/nix/store/zs30a9xl8i12ncrxy2kvybxqdjshhyy3-dk-2.0.drv' failed to build
```

### Notify maintainers

@3JlOy-PYCCKUi 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Please complain to upstream about changing the commit the tag points to.
