### ISSUE TITLE
Building `mutt` causes `texlive-bin`, `systemd` (and others) to be build

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#29368]
## Issue description / Steps to reproduce

```
$ nix-build -A mutt -Q
these derivations will be built:
  /nix/store/q1g34xbrlkggm1cp7fhy7rcdzk4i4hpi-texlive-bin-2016.drv
  /nix/store/c4pqi8dz1p91phfix5qxd4xg2n4n3s3v-texlive-combined-2016.drv
  /nix/store/dkpnsavyc9akviqaynybmg8mm15ni4ab-dblatex-0.3.7.drv
  /nix/store/8ixxrw6c6xrrim8kv8m0lf82iql1adz1-gtk-doc-1.25.drv
  /nix/store/fi61bwysqc3khp1grqyspzbhipvhwrvr-p11-kit-0.23.7.drv
  /nix/store/2zliljnivigysgnx5arvhfnhqj8fkayx-gnutls-3.5.14.drv
  /nix/store/d7rb5xs2y6q9sy1lh8hll86g8ss6yhmm-libmicrohttpd-0.9.55.drv
  /nix/store/69j2ifimiik1pykjibv1ijjlmw0k5hbi-systemd-234.drv
  /nix/store/dfcxpnjmc2sh10f5ka82v80divyzvc9w-dbus-1.10.22.drv
  /nix/store/1rn4fwmvczd9bxxmvwlwkkk98ahrrzh5-avahi-0.7.drv
  /nix/store/ygxjg80zpb4ykms855ms5956lgymrpvz-libusb-1.0.20.drv
  /nix/store/6sl25fcqlz80vsdf8y2bzn20w82jcqd8-cups-2.2.2.drv
  /nix/store/qzm9a0xgkq7iqkxka7xqybcranmj2sby-llvm-4.0.1.drv
  /nix/store/nagn2fqwbyj8j0f2rvsdvliq4prd6dna-mesa-noglu-17.1.7.drv
  /nix/store/8zvfl85nszplcby1sbd5nh33a71gg108-cairo-1.14.10.drv
  /nix/store/77ri6jybnnkc05n0ddhx26wdzalxhx7d-harfbuzz-1.4.8.drv
  /nix/store/rpm39pss75jfqn1gpq9c1flk0j3vxxhp-libusb-compat-0.1.5.drv
  /nix/store/skwi37kzm3bp9z39pkcqbrcjx4rxbq1w-pcsclite-1.8.22.drv
  /nix/store/aj9gpcsrb69z4wvj8zmd2bq8i5223k96-pango-1.40.9.drv
  /nix/store/a38nq8wrnf5rpbfnrqdsird3bnhaj16b-gtk+-2.24.31.drv
  /nix/store/ssq7jzxzzlwjkyjmsa645d2x2hggillv-pinentry-1.0.0.drv
  /nix/store/8nd5nw63na74y0am72s4l2hi9xlbryw5-gnupg-2.2.0.drv
  /nix/store/kr1hiwcfrnjzmgjg7l1apq09njjlq1i1-gpgme-1.9.0.drv
  /nix/store/fyx4fsb6lqr0w2q7nsmk4bglwar1b1r6-mutt-1.9.0.drv
```

What the hell?

(As of 1b1fc6550559f9d73ddf7cea611c387a847bf03b)

## Technical details

* System: 18.03pre115166.1b1fc65505 (Impala)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "18.03pre115166.1b1fc65505"
* Sandboxing enabled: build-use-sandbox = true

**Comment by vcunat** [comment]
On 1b1fc65, mutt and all deps are in the binary cache.

If you did some changes, like in ncurses, lots of things get rebuilt.  TeX is used for generating docs in some packages, for example.  Ncurses is also used very deep in the stacks, e.g. in python or readline.

**Comment by matthiasbeyer** [comment]
Darn. So I guess it is legit that these things get rebuild even if I just want `mutt`?

**Comment by vcunat** [comment]
I think so.  We have quite large build-time closures.  You *can* inspect `nix-store -q --graph /nix/store/fyx4fsb6lqr0w2q7nsmk4bglwar1b1r6-mutt-1.9.0.drv` if you see some really useless dependency link...

**Comment by matthiasbeyer** [comment]
Okay. So this issue is actually invalid. Closing.

**Comment by edolstra** [comment]
Apparently, `gtk-doc` depending on `dblatex` is new in 17.09. I would be in favour of reverting that in the interesting of fighting dependency bloat.
