### ISSUE TITLE
Build failure: tzdata

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#293705]
### Steps To Reproduce

1. `nix build -L --rebuild --no-link github:nixos/nixpkgs/6c8f89faa9d1dbcae853a218c783fbe06d447507#tzdata`

### Build log

[tzdata.log](https://github.com/NixOS/nixpkgs/files/14507061/tzdata.log)

### Additional context

Breakage seems to be introduced by 6c8f89faa9d1dbcae853a218c783fbe06d447507

### Notify maintainers

@ajs124 @fpletz 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.20240301.79baff8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(endgame): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ajs124** [comment]
Already fixed in staging by https://github.com/NixOS/nixpkgs/pull/292480, but probably hasn't made it to master yet.

Apologies again.
