### ISSUE TITLE
Package request: apparmor.d

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#293754]
Full set of AppArmor profiles (~ 1500 profiles)

**Metadata**

* homepage URL: https://apparmor.pujol.io/
* source URL: https://github.com/roddhjav/apparmor.d
* license: GPL2
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
Closing since this implementation is not compatible with NixOS.
