### ISSUE TITLE
Package request: llvmPackages_18

### ISSUE THREAD

**Issue by Noodlez1232** [NixOS/nixpkgs#293866]
**Project description**

**Metadata**

* homepage URL: https://llvm.org/
* source URL: https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.0
* license: Modified apache 2.0
* platforms: unix, windows

A new LLVM package is out now which means new llvmPackages.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
Will be closed by #296284
