### ISSUE TITLE
Update request: forgejo 1.21.6-0 → 1.21.7-0

### ISSUE THREAD

**Issue by vrifox** [NixOS/nixpkgs#293833]
- Package name: forgejo
- Latest released version: 1.21.7-0

- Current version on the unstable channel: 1.21.6-0
- Current version on the stable/release channel: 1.20.6-1-unstable-2024-02-22

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@emilylange 
@urandom2 
@bendlas 
@adamcstephens 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
I've opened a PR. FYI Forgejo (and many other packages) has an update script which can simplify this process, and contributions are welcome!

**Comment by vrifox** [comment]
@adamcstephens I will try that next time. :)
