### ISSUE TITLE
Infinite download loop when cache.nixos.org is unreachable

### ISSUE THREAD

**Issue by YorikSar** [NixOS/nixpkgs#29390]
When cache.nixos.org is unreachange (described in #29389), when I run `nixos-rebuild`, I get infinite loop of
```
download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/8bbja62mzarn9rlz674phw4l5jxfyfcq.narinfo’ (Curl error 22)
```

It seems this should stop after several tries, but it doesn't.

**Comment by edolstra** [comment]
The upcoming Nix 1.12 retries a finite number of times (5 IIRC).

**Comment by YorikSar** [comment]
Great, thanks. Will it be a part of 17.09 release?
