### ISSUE TITLE
Update request: satty 0.10.0 → 0.11.2

### ISSUE THREAD

**Issue by dasehak** [NixOS/nixpkgs#293978]
- Package name: satty
- Latest released version: 0.11.2

- Current version on the unstable channel: 0.10.0
- Current version on the stable/release channel: no

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@pinpox 
@donovanglover 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
next version is out: https://github.com/NixOS/nixpkgs/pull/297408
