### ISSUE TITLE
Package request: Francis

### ISSUE THREAD

**Issue by ilyss01** [NixOS/nixpkgs#293967]
**Project description**

Francis uses the well-known pomodoro technique to help you get more productive.

**Metadata**

* homepage URL: https://apps.kde.org/francis/
* source URL: https://invent.kde.org/utilities/francis
* license: [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)
* platforms: linux

**Comment by cimm** [comment]
This sounded like some good Friday evening fun, so I gave it a shot. I never build a Qt6 application, let alone package it for nix. Feedback is welcome on pull request #298182.
