### ISSUE TITLE
Plasma 6 SDDM prompts for password despite the user not having one (NixOS ISO)

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#293964]
### Describe the bug
Testing the new [installation-cd-graphical-calamares-plasma6.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/installation-cd-graphical-calamares-plasma6.nix) made available recently and it works fine but I noticed that when the lockscreen is activated, SDDM will prompt for a password despite the default iso user (nixos) does not have a password; which results in me being locked out of the iso since it won't take a blank password nor any character.

### Steps To Reproduce
1. Build iso with newest plasma6 graphical calamares module
2. Boot into iso
3. Lock the system

### Expected behavior
SDDM should just show the "Unlock" button and not prompt for a password

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@K900

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nixos@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7, NixOS, 24.05 (Uakari), 24.05.20240303.768bb87`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/l5xja2y73b785kppa8glplaw3r584gvh-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
That's kscreenlocker, not SDDM, and the password should be `nixos` IIRC?

**Comment by NovaViper** [comment]
Odd.. on the official release it's just no password set, just says "Unlock". And even odder is I try putting that as the password and it still fails to unlock.

**Comment by NovaViper** [comment]
The ISO from https://nixos.org, speciifcally `nixos-plasma5-23.11.1697.781e2a9797ec-x86_64-linux`

**Comment by K900** [comment]
Hmm, I'll have to double check then.

**Comment by NovaViper** [comment]
Hey it looks like it's now escalated to where if I hit "Switch User" the entire system locks up and have to restart the computer. And even worse, the issue still occurs! The oddest thing is however, is that it *doesn't* occur on an installed NixOS instance; none of my computers have this sort of problem (but I have a password set with autologin disabled for my user so that may be the difference).

**Comment by DocBrown101** [comment]
Is there already a workaround for this?
I just wanted to install it, but now I don't see any progress.

**Comment by Rutherther** [comment]
> Is there already a workaround for this? I just wanted to install it, but now I don't see any progress.

Switch to tty (`ctrl-alt-Fx`), set password to non-empty one (`sudo passwd nixos`), and then switch back

**Comment by Nintendo7686** [comment]
I just had the same issue on plasma6 24.05. I understand this an upstream issue but I thought it would be worth noting it.

**Comment by NovaViper** [comment]
Hey i updated to Plasma 6.1 but it sadly did not address the issue at all; had to go and undo that commit I pushed to my config two weeks ago 😭

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/321944
