### ISSUE TITLE
Build failure:build missing python3.11-pycairo-1.24.0

### ISSUE THREAD

**Issue by JucaRei** [NixOS/nixpkgs#293946]
### Build log

graphviz> config.status: creating lib/rbtree/Makefile
pycairo> Compiler for C supports arguments -fno-strict-aliasing: YES 
pycairo> Compiler for C supports arguments -fvisibility=hidden: YES 
pycairo> Configuring pycairo-1.24.0.egg-info using configuration
graphviz> config.status: creating lib/pathplan/Makefile
pycairo> Found pkg-config: /nix/store/4920vmlxb2nb8ids0nb32c8hlkimvyi2-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
graphviz> config.status: creating lib/pathplan/libpathplan.pc
pycairo> Run-time dependency python found: YES 3.11
pycairo> Did not find CMake 'cmake'
pycairo> Found CMake: NO
pycairo> Run-time dependency cairo found: NO (tried pkgconfig)
pycairo> 
pycairo> cairo/meson.build:37:12: ERROR: Dependency "cairo" not found, tried pkgconfig
pycairo> 
pycairo> A full log can be found at /build/source/build/meson-logs/meson-log.txt
graphviz> config.status: creating lib/ast/Makefile
graphviz> config.status: creating lib/sfio/Makefile
error: builder for '/nix/store/l0lm8q7ifm0ww89l3vq6l95y929q723f-python3.11-pycairo-1.24.0.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/5msmygl15afa88cvg5shdh2bvgk8gif9-python3-3.11.8-env.drv' failed to build
pango> building '/nix/store/x5rf9ryk2kxxwsq8sfdq8bsbyyyhpmim-pango-1.51.0.drv'
error: 1 dependencies of derivation '/nix/store/hlc0cjh0982xfk0lnjcy2765w0ykf489-tracker-3.6.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7pcw7p1zxs7kgqjggcf1x1i5zv0l6q7y-gtk+3-3.24.41.drv' failed to build
registry.json> building '/nix/store/smn3wphx0wzngkmcj9nalmqqxzkx6zzn-registry.json.drv'
error: 1 dependencies of derivation '/nix/store/cq52iv1720gkgckq1b1vrbmymv5a45d0-vte-0.74.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/00q91xff4prhlk52y8bg4z7zcmb9lxpm-bashrc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k3p6di43ksf3plfrh72g93zb3s3ca2kz-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1jmx2mjcvzdlp438agf6rc8rf4x3z9cc-home-manager-generation.drv' failed to build
```

### Additional context

Have been trying to build home-manager on wsl  with nix-output-manager and it fails, saying it can't find cairo package from python3.11.
Any clues?


### Metadata


```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.146.1-microsoft-standard-WSL2, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/snasjsbyrkp48jb63wnpgkn4flkhnlvr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
Hi @JucaRei, is this issue still present? Running `nix build .#python3Packages.pycairo` I'm unable to reproduce this build failure.

**Comment by SuperSandro2000** [comment]
nope

 ➜ hydra-check python311Packages.pycairo
Build Status for python311Packages.pycairo.x86_64-linux on master
✔ python3.11-pycairo-1.26.0 from 2024-04-20 - https://hydra.nixos.org/build/257044029
Build Status for python311Packages.pycairo.aarch64-linux on master
✔ python3.11-pycairo-1.26.0 from 2024-04-20 - https://hydra.nixos.org/build/256885297
Build Status for python311Packages.pycairo.x86_64-darwin on master
✔ python3.11-pycairo-1.26.0 from 2024-04-20 - https://hydra.nixos.org/build/256982600
Build Status for python311Packages.pycairo.aarch64-darwin on master
✔ python3.11-pycairo-1.26.0 from 2024-04-20 - https://hydra.nixos.org/build/256874396
