### ISSUE TITLE
inconsistent kernel versions: 4.12.10

### ISSUE THREAD

**Issue by moaxcp** [NixOS/nixpkgs#29409]
## Issue description

Today I added nvidia_x11 to my configuration and got an error from the kernel's builder. My configuration looks like this now.

```
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = [ pkgs.linuxPackages.nvidia_x11 ];
```

My full config is located [here](https://github.com/moaxcp/etc-nixos). I am using `linuxPackages_latest` due to [this issue](https://www.reddit.com/r/NixOS/comments/6ist8h/nixos_randomly_stops_working/).

## Technical details

```
LD [M]  /tmp/nix-build-nvidia-x11-375.66-4.9.46.drv-0/kernel/nvidia.ko
make[2]: Leaving directory '/nix/store/jshrr86nmp2grcvs1as1v0dxpwx31pj6-linux-4.9.46-dev/lib/modules/4.9.46/build'
make[1]: Leaving directory '/nix/store/jshrr86nmp2grcvs1as1v0dxpwx31pj6-linux-4.9.46-dev/lib/modules/4.9.46/source'
installing
post-installation fixup
patching script interpreter paths in /nix/store/5b59ldkmwi3m8lb7w5rbgik7vjks6lji-nvidia-x11-375.66-4.9.46
gzipping man pages under /nix/store/xjbby2d2c0b3dr9sb177k7294h11qva4-nvidia-x11-375.66-4.9.46-bin/share/man/
patching script interpreter paths in /nix/store/xjbby2d2c0b3dr9sb177k7294h11qva4-nvidia-x11-375.66-4.9.46-bin
building path(s) ‘/nix/store/ipv6n7cjpi1df28lwgjzxf5iq5ajaql5-kernel-modules’
created 8 symlinks in user environment
inconsistent kernel versions: 4.12.10
4.9.46
builder for ‘/nix/store/1k5dr8mb3fr6618y5qa4rprldr8fbc0f-kernel-modules.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/17sdp4rjin4mc7n04359q78rmb0yygb4-nixos-system-n1-17.03.1819.7eb1a42de4.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/17sdp4rjin4mc7n04359q78rmb0yygb4-nixos-system-n1-17.03.1819.7eb1a42de4.drv’ failed
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by joachifm** [comment]
Not sure it's reasonable to expect modules built for `linux` to work with `linux_latest`. What about using `linuxPackages_latest.nvidia_x11`?

**Comment by moaxcp** [comment]
Cool! That worked. Thanks!

**Comment by joachifm** [comment]
You could also try to refer to it as `config.boot.kernelPackages.nvidia_x11`, that ensures they'll remain in sync if you later decide to change `boot.kernelPackages`.
