### ISSUE TITLE
The v2raya service doesn't allow v2rayA to discover nftables

### ISSUE THREAD

**Issue by u-tane** [NixOS/nixpkgs#294091]
### Describe the bug

On Arch Linux and NixOS, both with nftables installed, enabling the v2rayA **systemd service** with tproxy enabled will produce different nft rulesets. On Arch Linux, v2rayA creates a dedicated table for it, as shown by `nft list ruleset`:

    table inet v2raya {
            set whitelist {
                    type ipv4_addr
                    flags interval
                    auto-merge
                    elements = { 0.0.0.0, 10.0.0.0/8,
                                 100.64.0.0/10, 127.0.0.0/8,
    ...

On NixOS, however, if v2rayA is started by `v2raya.service`, the `v2raya` table is not present, and the rules with the TPROXY target are found in the `mangle` table instead:

    table ip mangle {
            ...
            chain TP_PRE {
                    ...
                    ip protocol tcp meta mark & 0x000000c0 == 0x00000040 counter packets 196 bytes 33331 xt target "TPROXY"
                    ip protocol udp meta mark & 0x000000c0 == 0x00000040 counter packets 72 bytes 5690 xt target "TPROXY"
            }
    ...

This is because, currently, https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/v2raya.nix only adds `iptables` to the service `PATH`:

```nix
path = with pkgs; [ iptables bash iproute2 ]; # required by v2rayA TProxy functionality
```

However, v2rayA only consider nftables as supported if it finds the `nft` command:

https://github.com/v2rayA/v2rayA/blob/d8c97984206c97fb0da7c62b67906747e11d7327/service/core/iptables/utils.go#L64-L91

So I guess it just falls back to some legacy method of setting the forwarding rules.

In fact, v2rayA creates the same ruleset on NixOS after enabling `networking.nftables` if `v2rayA` is started directly from the command line instead of being started as a systemd service.

### Steps To Reproduce
1. Set `services.v2raya.enable = true;` and `networking.nftables.enable = true;`
2. In v2rayA's panel, enable transparent proxy with tproxy
3. List the the rule sets: `nft list ruleset`

### Expected behavior

There should be a table called `v2raya` under `inet`.

### Proposed Solution

I suggest modifying this line in `v2raya.nix`:

```diff
-path = with pkgs; [ iptables bash iproute2 ];
+path = with pkgs; [ iptables bash iproute2 ] ++ lib.optional nftablesEnabled nftables;
```

### Notify maintainers

CC @Eliot00  

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Eliot00** [comment]
@LostAttractor

**Comment by LostAttractor** [comment]
I've had the same problem before, thank for your feedback.
After testing, your suggestions work fine.
So I have opened a pull request in #301084
