### ISSUE TITLE
writers.writeYAML: `json2yaml` is compeletely broken

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#294097]
### Describe the bug
[`writers.writeYAML`](https://github.com/NixOS/nixpkgs/blob/d7570b04936e9b0f5268e0d834dee40368ad3308/pkgs/pkgs-lib/formats.nix#L79) uses [remarshal](https://github.com/remarshal-project/remarshal) to convert JSON to YAML, but it doesn't quote YAML values correctly, leading to lossy conversions. We should replace `json2yaml` with `yq` (or something else).

### Steps To Reproduce
```bash
$ json2yaml <(echo '{"value": "348145"}') >(cat)
value: '348145'

$ json2yaml <(echo '{"value": "1e2529"}') >(cat)
value: 1e2529

$ json2yaml <(echo '{"value": "1e2529"}') >(yq .)
{
  "value": 1.7976931348623157e+308
}
```

As you can see, the string `1e2529` gets converted into a float.

### Expected behavior
`writeYAML` should not cause any erroneous conversions.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 24.05 (Uakari), 24.05.20240226.13aff9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/1gpgihsi21bni03hy6i5ccw9lfrhnbqi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
technically, `cat` cat converts json into yaml, since yaml is backwards-compatible with json.  what is this function actually used for?

**Comment by musjj** [comment]
Not sure what it was used for generally, but I was using it for base16.nix. It has its own custom parser written in Nix that can only parse a small subset of YAML (to avoid IFD).

But I realized that the issue is actually incompatibility between the `1.1` and `1.2` spec, and it's more of a `yq` problem more than anything. `yq` (and `json2yaml`) outputs yaml with the `1.1` spec, but `yq` parses yaml input with the `1.2` spec, which is why the conversion happens. The work around is to use `--yaml-output-grammar-version 1.2` (there's no equivalent for inputs).

I think I'll close this for now, because this is probably a *really* niche issue. Feel free to leave a comment if anyone wants this reopened.
