### ISSUE TITLE
spamassassin: sa-learn command does not work

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#29414]
Our new spamassassin module refuses to start if `/etc/spamassassin` exists, asserting that "this abstraction requires no centralized config at all". Unfortunately, some spamassassin tools *don't* work without knowing the location of their site-wide config file. `sa-lean` is an example for a command that fails:

~~~
$ sa-learn --spam --mbox /tmp/spam
config: could not find site rules directory
Learned tokens from 0 message(s) (0 message(s) examined)
~~~

The same commands works fine after adding `--siteconfigpath=/nix/store/1hswfm4gl87r99bfhz6hpn08jhy7vby0-spamd-env`, where that path comes from `/etc/systemd/system/spamd.service`.

To fix this issue, the systemd module should create a symlink from `/etc/spamassassin` to it's generated spamd-env. Alternatively, the module could install wrapped versions those spamassassin commands that need `--siteconfigpath` added.

Ping: @qknight

**Comment by qknight** [comment]
@peti 
that observation is correct. we should patch sa-learn to use site-configpath also as i did for the other command. i would want that as well, shall i take a look?

**Comment by qknight** [comment]
@peti 
found it, https://github.com/NixOS/nixpkgs/pull/26470/files#diff-b4f5e6be307452f6727f15b4c8dbf956R14 it is the spamd command.

**Comment by peti** [comment]
Ah, very cool. Thank you.

**Comment by peti** [comment]
If you could extend the fix, that would be very much appreciated. Personally, I don't know Perl.

**Comment by qknight** [comment]
@peti i will do that patch in the next few days.

**Comment by qknight** [comment]
@peti can you please tell me how you organize your `sa-learn`? do you have autolearn or how do you train it?

**Comment by peti** [comment]
> can you please tell me how you organize your sa-learn?

I run it manually (as a user who is a member of the spamd group). I
don't use autolearn.

**Comment by qknight** [comment]
> I run it manually (as a user who is a member of the spamd group)
i want to have support for virtual users for nixcloud.email mainly:

* each virtual user has its own bayes database and the 
* learning is triggered based on read emails in the `.Spam` directory so i will basically only learn `spam` this way
* learning ham is triggered by the `inbox/cur` directory, so all emails in that folder have been read and are considered ham

now i need to know this from you:

* do you have PAM users (no virtual users) and want to learn there?
* do you also have virtual users and how do you run the script for them, either: one spamassassin database for all of them on the complete server or also one database per user

sa-learn already knows the siteconfigpath variable but unlike spamd, for which we create the systemd job, we can't put the 'dynamic' path, the environment, into pkgs.spamassassin and i'm currently thinking if we add a `sa-learn-nixos` which has modified behaviour or in which other way we can pass the 'current environment' to `sa-learn`.

if you have any desires on where i should take this, please give me some feedback.

**Comment by qknight** [comment]
@peti the more i think about your problem the more i think we should link to the `environment` used in `spamd` from /etc/spamassassin so you can just use that. it will also be consistent with what you had been using up to now.

so what solution would you prefer?

**Comment by peti** [comment]
> I think we should link to the environment used in spamd from /etc/spamassassin so you can just use that.

Yes, either that, or install we can install wrappped binaries into the
system environment. Both approaches work fine, but creating the symlink
is probably easier.

**Comment by qknight** [comment]
@peti can you try this patch?

```
diff --git a/nixos/modules/services/mail/spamassassin.nix b/nixos/modules/services/mail/spamassassin.nix
index fc8396cd85..580cba67e8 100644
--- a/nixos/modules/services/mail/spamassassin.nix
+++ b/nixos/modules/services/mail/spamassassin.nix
@@ -64,6 +64,14 @@ in
         default = "";
       };

+      createImpureEnvironmentSymlink = mkOption {
+        default = false;
+        type = types.bool;
+        description = ''
+          Set createImpureEnvironmentSymlink to `true` if you need to run sa-learn manually from a shell as it will then create a symlink in /etc/spamassassin to the `spamd-env`. `sa-learn` needs a way to find the configuration of spamassassin in order to process the emails or you will get this error message: "config: could not find site rules directory".
+        '';
+      };
+
       initPreConf = mkOption {
         type = types.str;
         description = "The SpamAssassin init.pre config.";
@@ -182,6 +190,11 @@ in
           echo "This spamassassin does not support global '/etc/spamassassin' folder for configuration as this would be impure. Merge your configs into 'services.spamassassin' and remove the '/etc/spamassassin' folder to make this service work. Also see 'https://github.com/NixOS/nixpkgs/pull/26470'.";
           exit 1
         fi
+
+        ${optionalString cfg.createImpureEnvironmentSymlink ''
+          ln -sf ${spamdEnv} /etc/spamassassin
+        ''}
+
         echo "Recreating '/var/lib/spamasassin' with creating '3.004001' (or similar) and 'sa-update-keys'"
         mkdir -p /var/lib/spamassassin
         chown spamd:spamd /var/lib/spamassassin -R

```

**Comment by peti** [comment]
Is it really necessary to add yet another option to create this symlink? Can't we just create it unconditionally? What's the problem with `sa-learn` and friends just working out of the box?

**Comment by qknight** [comment]
# issues

nixos is about purity and the way i modified the spamassassin module is to make it pure. now you are asking to be less pure. 

i assume that `sa-learn`, as probably all sa-related tools, look into `/etc/spamassassin` by default. `spamd` as well as `sa-learn` support the `siteconfigpath` option but it might be hard to debug to use a custom path per virtual user for the configuration if there is a global fallback, `/etc/spamassassin` which migtht accidentially be used as a fallback.

# future

i want to extend the `nixcloud email` abstraction to use `sa-learn` on a per virtual user basis with a custom learning per virtual user and not one config per server. that has not been implemented yet but i'm pretty close.

# summary

with the impure patch i provided you can use the traditional `/etc/spamassassin` symlink to access your configuration. i'd liked if you would agree to use that patch and wait for the 'per virtual user' example config and adapt to that later on.

**Comment by peti** [comment]
> nixos is about purity and the way i modified the spamassassin module is to make it pure. now you are asking to be less pure.

I am sorry, but this is just not accurate. You modified the spamassassin module in a way that *broke* essential commands like `sa-learn` and I am asking for those broken commands to be fixed. "Purity" is great, but it's worthless if the resulting configuration doesn't work.

The `createImpureEnvironmentSymlink` option your patch adds suggests that having that symlink is kind-of optional, i.e. you can enable or disable that depending on your personal preference, but it really isn't optional because `sa-learn` does not work at all without that symlink. Therefore, that symlink should not be optional. The alternative is to fix `sa-learn`. That's a good solution, too, but it happens to be more involved than just adding the symlink.

**Comment by qknight** [comment]
don't rush things, this isn't easy and i really like consent on futher steps.

**Comment by peti** [comment]
I am sorry, but my installation has been broken for almost 2 weeks now -- on a release branch, no less. That needed to be fixed. If you have a better solution to replace this one, then I am all for it, but we needed a solution and this one works just fine.
