### ISSUE TITLE
Update request: openjdk17 17.0.7+7 →  17.0.10+7

### ISSUE THREAD

**Issue by Firefly1127** [NixOS/nixpkgs#294296]
- Package name: openjdk17
- Latest released version: 17.0.10+7

- Current version on the unstable channel: 17.0.7+7
- Current version on the stable/release channel: 17.0.7+7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@edwtjo

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by freyacodes** [comment]
Resolved by #313927
