### ISSUE TITLE
Update request: betterbird 115.6 → 115.8.1

### ISSUE THREAD

**Issue by jmarmstrong1207** [NixOS/nixpkgs#294238]
- Package name: betterbird
- Latest released version: 115.8.1

- Current version on the unstable channel: 115.6
- Current version on the stable/release channel: 115.4.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@SuperSandro2000 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
I've already answered that issue here https://github.com/NixOS/nixpkgs/issues/249110#issuecomment-1686476920 . I don't plan to work on that.
