### ISSUE TITLE
Build failure: `zulu8` with JavaFX

### ISSUE THREAD

**Issue by dixslyf** [NixOS/nixpkgs#294234]
### Steps To Reproduce

Attempt to build `zulu8` with JavaFX: `zulu8.override { enableJavaFX = true; }`.
The build fails due to `auto-patchelf` being unable to satisfy dependencies.
The issue seems to occur for other versions of `zulu` as well.

### Build log

[nffvs8x2f4049m93j4aiap7kvxgi1ya4-zulu-ca-fx-jdk-8.0.402.drv.log](https://github.com/NixOS/nixpkgs/files/14535250/nffvs8x2f4049m93j4aiap7kvxgi1ya4-zulu-ca-fx-jdk-8.0.402.drv.log)

### Additional context

Build was attempted in a flake with Nixpkgs pinned to f945939fd679284d736112d3d5410eb867f3b31c,

### Notify maintainers

@wegank 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.7.6-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240228.9099616`
 - multi-user?: `yes`

 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/cbbsvzjcqvzlylq9s7p6d2gyxh64q88p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wegank** [comment]
I remember encountering this during a last bump, but eventually abandoned it because something like `libavcodec.so.53` point to obsolete versions of ffmpeg that no longer exist in Nixpkgs. I'll probably mark `zulu` with `enableJavaFX = true` on Linux as broken at some time this week.

**Comment by wegank** [comment]
Oh, there's actually `autoPatchelfIgnoreMissingDeps` for that. Would you please test if #294241 works?
