### ISSUE TITLE
Documentation: PR template points to wrong documentation

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#294384]
## Problem

the PR template points to https://nixos.org/manual/nixpkgs/unstable/#reviewing-contributions-package-updates instead of
https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#reviewing-contributions

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
#298333

I kindly ask you to just create the PR with this really trivial change instead of creating an issue.

**Comment by lolbinarycat** [comment]
it's only trivial if you have experience with how github works.  i had no idea the template was controlled by a file within the repo and not some option in the settings.
