### ISSUE TITLE
incus: (with enabled incus ui) Uploading an ISO in the web UI hangs on "Validating ISO"

### ISSUE THREAD

**Issue by cmspam** [NixOS/nixpkgs#294376]
### Describe the bug
This is in unstable.
When attempting to upload an ISO in the web UI, it hangs on Validating ISO. The ISO is never successfully uploaded.

### Steps To Reproduce
1. Set   ```virtualisation.incus.enable = true;
  virtualisation.incus.ui.enable = true; ```
2. Go to create a new VM from the Incus web UI.
3. Choose to upload ISO.

### Expected behavior
The ISO would be uploaded normally.

### Additional context
The Upload ISO interface says "Some image formats need to be modified in order to work with LXD." but the mention of "LXD" should have been patched to "Incus". Not sure if this is related.

By my admission it's probably not the right way to do it, but I had created a derivation to build the incus UI using the patches from zabbly/incus github atop the 0.6 version of the lxd ui. In this version, the ISO upload feature works, and "LXD" is replaced with "Incus" correctly. If it helps, you can find it here:
https://github.com/cmspam/incusui-nix/tree/main

I also really wish that the nix package in unstable for incus was designed in a more override-friendly way (separate unwrapped like in 23.11 for example). The way it is currently, I have not found any way to override versions and so on.

### Notify maintainers
@aanderse @adamcstephens @jnsgruk @megheaiulian @mkg20001 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Would you be willing to open a pull request to fix the incus UI? I like that your package is all encompassing, as the LXD dependency may go away in the future.

I'll look into bringing back a more friendly override. I see the problem, and should have caught this in the refactor to add LTS support. Out of curiosity what's your goal for overriding the incus package itself?

**Comment by cmspam** [comment]
> Would you be willing to open a pull request to fix the incus UI? I like that your package is all encompassing, as the LXD dependency may go away in the future.

Yes, of course, I will give it a try.

> I'll look into bringing back a more friendly override. I see the problem, and should have caught this in the refactor to add LTS support. Out of curiosity what's your goal for overriding the incus package itself?

More than anything else, just to be able to easily specify whatever version I want to use. I maintain unofficial OCI images for incus, as well as an OBS repository building it for OpenSuse. I'm always looking to see when a new version comes out so that I can keep these up to date, and want to be able to specify the exact version in an override on Nix as well. I think the ability to do such things is one of the biggest appeals of Nix.

**Comment by cmspam** [comment]
> Would you be willing to open a pull request to fix the incus UI? I like that your package is all encompassing, as the LXD dependency may go away in the future.
Pull request is here:
https://github.com/NixOS/nixpkgs/pull/294497

This fixes what was unimplemented in the current implementation of the patches in a simple way with sed commands. I figure that initially, a simple fix like this is best.

I can confirm that it fixes the ISO issue, and the branding issue, described in this bug report.

**Comment by cmspam** [comment]
The pull request was merged, so I can close this issue. On a personal note, I haven't submitted something to a large project like NixOS before, so this was a fun experience.
