### ISSUE TITLE
eval "$buildPhase" return code doesn't reflect buildPhase result

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#2943]
`nix-shell` into any Haskell + Cabal project

Configure it with `eval "$configurePhase"`

Then say we're hacking on it and want to rebuild. I often end up doing

`eval "$buildPhase" && ./dist/build/…`

But in this case even if something during the build phase goes wrong, it seems to return a 0 return code anyway. An easy way to replicate would be to make a type-error in the code and then run

`eval "$buildPhase" && echo "Shouldn't see this!"`

Not sure whether I should be filing this under nixpkgs or nix.

**Comment by peti** [comment]
I guess this issue is obsolete in the `haskell-ng` package set?

**Comment by Fuuzetsu** [comment]
Correct.
