### ISSUE TITLE
foot: missing icon

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#294355]
### Describe the bug
foot (terminal emulator) is missing an application icon but it's present in the sources (https://codeberg.org/dnkl/foot/src/branch/master/icons/hicolor/scalable/apps/foot.svg)

### Expected behavior
Application has an icon instead of fallback Wayland logo

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/46971551/43d3cf3e-833d-4eb5-aea0-e7e6a7431086)
![image](https://github.com/NixOS/nixpkgs/assets/46971551/f91d9d65-0a59-45e0-a375-505e8c33b7e8)

### Additional context
Application icon is available at `{repo root}/icons/hicolors/.../apps/foot.png`

### Notify maintainers
@sternenseemann @abbe

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7-zen1, NixOS, 24.05 (Uakari), 24.05.20240306.9df3e30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/gig8j85kj7ybjy3ksn6k3aich8j2k59y-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Weathercold** [comment]
Can confirm, although it seems that there's no .desktop file at all?

**Comment by Aleksanaa** [comment]
Can't reproduce on `cd7e4e32b1fcd00b7292922c676b463afda01586` (newer than current nixos-unstable)

**Comment by Weathercold** [comment]
Perhaps this is specific to plasma? I tested on plasma 6. @LennyLizowzskiy seems to be using plasma too

**Comment by Aleksanaa** [comment]
It's in the output of `github:nixos/nixpkgs/9df3e30ce24fd28c7b3e2de0d986769db5d6225d#foot` (Which is the checkout mentioned in the metadata):

```
./
├── bin
│   ├── foot
│   └── footclient
├── etc
│   └── xdg
│       └── foot
│           └── foot.ini
├── lib
│   └── systemd
│       └── user -> ../../share/systemd/user
└── share
    ├── applications
    │   ├── org.codeberg.dnkl.footclient.desktop
    │   ├── org.codeberg.dnkl.foot.desktop
    │   └── org.codeberg.dnkl.foot-server.desktop
    ├── bash-completion
    │   └── completions
    │       ├── foot
    │       └── footclient
    ├── doc
    │   └── foot
    │       ├── CHANGELOG.md
    │       ├── LICENSE
    │       └── README.md
    ├── fish
    │   └── vendor_completions.d
    │       └── foot.fish
    ├── icons
    │   └── hicolor
    │       ├── 48x48
    │       │   └── apps
    │       │       └── foot.png
    │       └── scalable
    │           └── apps
    │               └── foot.svg
    ├── man
    │   ├── man1
    │   │   ├── foot.1.gz
    │   │   └── footclient.1.gz
    │   ├── man5
    │   │   └── foot.ini.5.gz
    │   └── man7
    │       └── foot-ctlseqs.7.gz
    ├── systemd
    │   └── user
    │       ├── foot-server.service
    │       └── foot-server.socket
    └── zsh
        └── site-functions
            ├── _foot
            └── _footclient
```

Yes, may be related to plasma6.
