### ISSUE TITLE
Update request: flutter `3.19.0` → `3.19.3`

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#294499]
- Package name: `flutter`
- Latest released version: `3.19.0` 

- Current version on the unstable channel: `3.19.0`
- Current version on the stable/release channel: `3.18.3`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----
@nixpkgs/flutter

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Done as part of #295730
