### ISSUE TITLE
Cutter fails to build on unstable channel

### ISSUE THREAD

**Issue by kennystrawnmusic** [NixOS/nixpkgs#294438]
### Steps To Reproduce

1. Add `cutter` (or any packages that depend thereon, like most of `services.xserver.desktopManager.plasma6` for instance) to `environment.systemPackages` in either /etc/nixos/configuration.nix on an installed system or /mnt/etc/nixos/configuration.nix on a target system that you're trying to install, e.g. to a spare device
2. Attempt to run either `nixos-rebuild switch` on a system that is already installed or `nixos-install` from another system that you've previously installed `nixos-install-tools` onto (which is how I ran into this, as I'm using an existing Arch installation on `/dev/nvme0n1` to set up a dual-boot with NixOS on `/dev/sda`).

### Build log

```
/build/source/src/widgets/GraphvizLayout.cpp: In member function 'virtual void GraphvizLayout::CalculateLayout(std::unordered_map<long long unsigned int, GraphLayout::GraphBlock>&, long long unsigned int, int&, int&) const':
/build/source/src/widgets/GraphvizLayout.cpp:97:49: error: 'TRUE' was not declared in this scope
   97 |         nodes[block.first] = agnode(g, nullptr, TRUE);
      |                                                 ^~~~
/build/source/src/widgets/GraphvizLayout.cpp:146:55: error: 'TRUE' was not declared in this scope
  146 |             auto e = agedge(g, u, v->second, nullptr, TRUE);
      |                                                      
```

### Additional context

This is a symptom of the versions of rizin, cutter, and everything else rizin-related in the nixpkgs repo being months out of date, as `TRUE` is clearly not the same as `true` and new versions of GCC from at least the past month only support lowercase Boolean literals, not capitalized ones. Updating the version to 2.3.4, as I can attest by attempting such myself, fixes this issue (although it also introduces a failure to find the `rz_core.h` header file, which may require an additional patch to resolve).

### Notify maintainers

@Mic92 @dtzWill 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console

- system: `"x86_64-linux"`
 - host os: `Linux 6.7.9-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.4`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kennystrawnmusic** [comment]
Just realized that this may be a duplicate of #293783 but the error messages captured in the output posted there aren't as relevant as these.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/293264
