### ISSUE TITLE
Murmur doesn't write the registerPassword to its config file

### ISSUE THREAD

**Issue by gianmarcogg03** [NixOS/nixpkgs#294479]
### Describe the bug
When setting a registerPassword for the public server list, it doesn't actually write it to the murmurd.ini file, forcing me to hardcode it with extraConfig.

### Steps To Reproduce
1. Set the registerPassword option;
2. Rebuild the system;
3. Read the contents of `/run/murmur/murmurd.ini`.

### Expected behavior
The registerPassword option should be written to murmurd.ini.

### Additional context
It may be a problem with [this file](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/services/networking/murmur.nix) at line 36 where it has a double equals instead of a exclamation mark equals like the other parameters in that code block, although I'm not really sure.

### Notify maintainers
@infinisil @felixsinger 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.11 (Tapir), 23.11.4835.c8e74c2f83fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
> It may be a problem with [this file](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/services/networking/murmur.nix) at line 36 where it has a double equals instead of a exclamation mark equals like the other parameters in that code block, although I'm not really sure.

Oof that's exactly right.

It seems to have been [caused](https://github.com/NixOS/nixpkgs/commit/f3719756b550113c1acbbab00c89a56fb77256f2#diff-5ddcb1cdf743de31a674347091c5c42fc5ba5b8701cbd7c98942896be62c5b44L36) by https://github.com/NixOS/nixpkgs/pull/239624 by @Stunkymonkey
