### ISSUE TITLE
Home directory for user root on Hydra/Linux seems to be /build

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#29443]
## Issue description

While analyzing why the dmd bootstrap package still doesn't build on Hydra/Linux but everywhere else (https://github.com/NixOS/nixpkgs/pull/28635#issuecomment-329889053) I came to the realization that the user configuration for _root_ on Hydra/Linux seems to be _/build_ instead of _/root_.
The Unittest of dmd/phobos expects _/root_ and fails. (https://hydra.nixos.org/build/61091111)

Can someone with access to Hydra/Linux verify that the home dir for user root is indeed _/build_ via something like _echo ~root_ .
And is it possible to change it to the standard configuration _/root_?

### Steps to reproduce

The problem can be reproduced on other machines if the home directory for user root is changed to something different. e.g.: `usermod -m -d /build root`
And the build for dmd from nixpkgs/Master (Commit 3b5245f0c4bab768cb69b72553def28d0a426720) is started: `nix-build -A dmd`

CC @Mic92

**Comment by ThomasMader** [comment]
CC @vcunat as this is the same problem as in https://github.com/NixOS/nixpkgs/pull/11327#issuecomment-161678850 even though the error output changed a bit because of the different versions of dmd/phobos.

Back then it was

core.exception.AssertError@std/path.d(3954): ~root

and now it is

core.exception.AssertError@std/path.d(3083): /build

**Comment by Mic92** [comment]
Like I said, there is a different `/etc/passwd` in the sandbox: https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L1897

**Comment by ThomasMader** [comment]
I wanted to bring that out of that initial PR.

Ok I see thanks for finding it.
Is it possible to get _settings.sandboxBuildDir_ from within the derivation? This way I could easily substitute/patch the unittest properly without needing to remove it entirely.

The primary question still holds though. Why is it needed to use _/build_ instead of _/root_.
What would it mean if _settings.sandboxBuildDir_ is set to _/root_?

**Comment by ThomasMader** [comment]
I wanted to bring that out of that initial PR.

Ok I see thanks for finding it.
Is it possible to get _settings.sandboxBuildDir_ from within the derivation? This way I could easily substitute/patch the unittest properly without needing to remove it entirely.

The primary question for this issue still holds though. Why is it needed to use /build instead of /root for user root?

@edolstra You mention in NixOS/nix@eba840c that the directory shouldn't be world writeable and I see why but wouldn't it be possible to separate the home dir of the user root from the build dir?

**Comment by vcunat** [comment]
I don't see why the builds should do anything related to the *root* user.

**Comment by edolstra** [comment]
Yes, builds should not make any assumption about the existence of user accounts or the location of their home directory.
