### ISSUE TITLE
Lost icons, cannot change fonts in foliate.

### ISSUE THREAD

**Issue by 0xDkXy** [NixOS/nixpkgs#294533]
### Describe the bug

Lots of icons were lost and the font it used cannot be changed in foliate. But I tested it in other distro like Archlinux, it worked well.
So I am wondering whether it is packed wrong?

### Steps To Reproduce
1. `nix-shell -p foliate --pure`
2. `foliate` to start it

### Expected behavior
All icons are normal and you can change the fonts, and what you change will be store so next time you wouldn't set it again.

I will show some screenshots I got on archlinux.

![20240310_00h53m06s_grim](https://github.com/NixOS/nixpkgs/assets/55947248/3ec4b000-73dc-4578-8579-3d9f938d68e9)

![20240310_00h43m12s_grim](https://github.com/NixOS/nixpkgs/assets/55947248/7eee5fb2-db7f-4e41-83b6-1ad453c0136d)
![20240310_00h42m38s_grim](https://github.com/NixOS/nixpkgs/assets/55947248/7a21eb2a-a5c3-4a20-b402-1e388f42f293)

### Screenshots
![20240310_00h29m30s_grim](https://github.com/NixOS/nixpkgs/assets/55947248/561721f7-60e9-4579-966f-48458124e9cf)
![20240310_00h55m04s_grim](https://github.com/NixOS/nixpkgs/assets/55947248/ab7d3355-c4ee-4df6-af8b-6ce94e344603)

### Additional context
Did it work normally on yours?

### Notify maintainers
@onny 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.19, NixOS, 24.05 (Uakari), 24.05pre591063.b8697e57f102`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
```
> nix-shell -p libadwaita.devdoc --pure
> adwaita-1-demo
```

![image](https://github.com/NixOS/nixpkgs/assets/42209822/9c91e0d3-ab1a-4890-8468-16e22eb2fbf1)

An icon theme should be present to allow displaying icons in GTK apps. See related discussions here: https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450058333
