### ISSUE TITLE
neovim: unable to use tree-sitter because of the bundled parsers

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#294529]
### Describe the bug
Nixpkgs' version of Neovim bundles several treesitter parsers but treesitter doesn't support multiple parser locations so it crashes

### Steps To Reproduce
Start Neovim with treesitter plugin enabled and some parsers installed

### Expected behavior
Treesitter doesn't crash on init

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/46971551/86ef5fc4-50b6-4626-b9c1-a09eb9a4a55c)

### Additional context
Other users also encountered this problem:
1. https://www.reddit.com/r/NixOS/comments/1b51z9t/installing_neovim_without_treesitter_parsers/
2. https://github.com/nvim-treesitter/nvim-treesitter/discussions/5289
3. https://discourse.nixos.org/t/conflicts-between-treesitter-withallgrammars-and-builtin-neovim-parsers-lua-c/33536

### Notify maintainers
@manveru @rvolosatovs

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7-zen1, NixOS, 24.05 (Uakari), 24.05.20240306.9df3e30`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/gig8j85kj7ybjy3ksn6k3aich8j2k59y-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
> Nixpkgs' version of Neovim bundles several treesitter parsers but treesitter doesn't support multiple parser locations so it crashes 

it does, it doesn't like mismatched grammar and queries, see my answer at 
https://github.com/NixOS/nixpkgs/pull/291678#issuecomment-1965495371
