### ISSUE TITLE
Build failure: gimpPlugins.gap

### ISSUE THREAD

**Issue by Scrumplex** [NixOS/nixpkgs#294707]
### Steps To Reproduce

1. build `gimpPlugins.gap`

### Build log

https://gist.github.com/Scrumplex/54413f1f4a63b56ae5c1bb2300b31c99
https://hydra.nixos.org/build/252455294/log

### Additional context

gimp-plugin-gap fails to build since the last nixos-unstable merge.

Source: https://github.com/NixOS/nixpkgs/blob/3030f185ba6a4bf4f18b87f345f104e6a6961f34/pkgs/applications/graphics/gimp/plugins/default.nix#L128

### Notify maintainers

This has been added in https://github.com/NixOS/nixpkgs/commit/76c87385524263bb9e9c1b80f5e4bafe715c3725 and hasn't been touched much ever since. So not sure :/

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7-zen1, NixOS, 24.05 (Uakari), 24.05.20240309.3030f18`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(scrumplex): `""`
 - nixpkgs: `/etc/nix/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
It seems like gimp-gap is abandoned? There is no newer version on ftp.gimp.org, it seems to be archived on [GNOME GitLab](https://gitlab.gnome.org/Archive/gimp-gap), and it ships a 13-year-old version of ffmpeg (version 0.5) and if I just look at https://ffmpeg.org/security.html I get the feeling that this software is not in a good state to be shipped in the first place.

**Comment by Silveere** [comment]
This doesn't seem to have actually fixed the build failure. I tried building `gimpPlugins.gap` against `48dbdff7` (the PR merge commit) as well as `master` and it still fails with the same error. 

https://gist.github.com/Silveere/863beadde508a83cc67b2a49e4289e3f

**Comment by jtojnar** [comment]
Quoting from https://github.com/NixOS/nixpkgs/issues/295161#issuecomment-1991621308:

> Yuck, we should not allow vendoring ffmpeg. We should probably `--disable-libavformat` like Fedora [was doing](https://src.fedoraproject.org/rpms/gimp-gap/blob/b870d959417a8d2a9d5770a818317e620a09b416/f/gimp-gap.spec#_60).
> 
> Or maybe just remove gap since it is [dead upstream](https://gitlab.gnome.org/Archive/gimp-gap) and will likely break with upcoming GIMP 3.
