### ISSUE TITLE
Mixxx misses libmp4 for AAC or MP4 support

### ISSUE THREAD

**Issue by tasmo** [NixOS/nixpkgs#29472]
## Issue description

While building mixxx with the sconsFlag `faad=1` ist fails with the massage:

> ERROR:root:Unmet dependency: Could not find libmp4, libmp4v2 or the libmp4v2 development headers.

### Steps to reproduce

In https://mixxx.org/wiki/doku.php/compiling_on_linux are the libraries faad2 and libmp4 mentioned as requirements. I can install faad2 but didn't find a libmp4 variant. Installing mp4v2 did not solve it.

in my `configuration.nix` I added:

``` nix
{ config, pkgs, ... }:
{
  nixpkgs.config = {
    allowUnfree = true;
    packageOverrides = pkgs: ({
      mixxx = pkgs.lib.overrideDerivation pkgs.mixxx (attrs: {
        sconsFlags = [
          "build=release"
          "qtdir=${pkgs.qt4}"
          "faad=1"
        ];
      });
    });
  };
}
```

## Technical details

* System: NixOS 17.03.1825.df7e518568 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: 17.03.1825.df7e518568
* Sandboxing enabled: true

**Comment by willtim** [comment]
If building with "faad=1", then you need to provide faad2 and mp4v2 as buildInputs. The package override you provided above would not be sufficient.  What I did was to save the default.nix for mixxx and modify it to directly invoke mkDerivation with the modified sconsFlags and buildInputs, see the following blog post for an example of how to do this: http://sandervanderburg.blogspot.co.uk/2014/07/managing-private-nix-packages-outside.html

The package needs to be modified to take an optional parameter to switch on/off this flag and corresponding dependencies. If I get time, I will assemble a pull request.

**Comment by tasmo** [comment]
@willtim May you provide me your receipt for faad2, mp4v2 and mixxx?

**Comment by willtim** [comment]
@tasmo, I'm not sure what you mean by receipt? I can put together a pull request for mixxx and some better instructions for building it?

**Comment by tasmo** [comment]
@willtim That would be great!

**Comment by willtim** [comment]
Pull request sent (#33587). Please note that the default setting is still without AAC support, to maximise the chance of this pull request getting excepted. You'll need to explicitly enable AAC support using, for example, the following in config.nix:

```
packageOverrides = pkgs : with pkgs; rec  {
  mixxx = pkgs.mixxx.override { aacSupport = true; };
};
```

**Comment by tasmo** [comment]
Is there a way to get support for the ALACodec which is wrapped in a MP4 container?

**Comment by adisbladis** [comment]
@tasmo There is an open upstream issue for ALAC support https://bugs.launchpad.net/mixxx/+bug/1336982

In the mean time I recommend transcoding ALAC to flac.

**Comment by tasmo** [comment]
@adisbladis Thank you for pointing to the issue. Converting to Flac unfortunately is not an option right now because sharing the library with iTunes.
