### ISSUE TITLE
Request: Enable intel-xe-kmd for mesa

### ISSUE THREAD

**Issue by MordragT** [NixOS/nixpkgs#294788]
**Enable intel-xe-kmd for mesa**

Hey it would be great if the intel xe kernel module support could be enabled for mesa.
Normally I would just override the derivation but sadly my computer is not powerful enough
to rebuild all of the dependent packages (nameley webkit and chromium) in a reasonable amount
of time (my RAM and SWAP completely fills up).
I haven't investigated it any further but I believe adding "-Dintel-xe-kmd=enabled" to meson flags should do the trick.

**Metadata**

* source URL: https://gitlab.freedesktop.org/mesa/mesa
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by philipwilk** [comment]
Shouldn't be necessary one [this commit](https://gitlab.freedesktop.org/mesa/mesa/-/commit/31920cb60c3cf487bc29ebd1d8ad8b1825e09fab) hits the next release. I don't see it in 24.0.3 so I assume it'll be in 24.0.4

**Comment by LunNova** [comment]
Looks like that won't be in 24.0, it's only in `main` so it'll be in 24.1

**Comment by LunNova** [comment]
Changing the flag doesn't change any ABI so a rebuild isn't forced.

Try overriding `hardware.opengl.package` with mesa with this option and rebooting.

**Comment by MordragT** [comment]
Ah I overlayed mesa before didnt have in mind that it has a .package option. Thanks will try that

**Comment by khionu** [comment]
24.0.4 is now released, I'm just about to open a ticket to request it be updated

**Comment by khionu** [comment]
Oh, nvm, it's already been updated, just hasn't landed in unstable yet

**Comment by philipwilk** [comment]
Hi, it didn't get merged in time for mesa 24.0.4, but it is in [24.0.5](https://gitlab.freedesktop.org/mesa/mesa/-/commit/066c61c7485e24394fe76d17d201bc479f7cbd16) which released two days ago.

**Comment by philipwilk** [comment]
Mesa 24.05 is now in unstable, and you can [enable the xe driver using modprobe](https://github.com/philipwilk/nixconf/commit/479a9e9f5dec4bd3244e99e67ce20c1712e96cc1) like I have.
![image](https://github.com/NixOS/nixpkgs/assets/50517631/c93b96ab-9a13-4165-984f-e3187f298370)

**Comment by philipwilk** [comment]
For context, mesa was updated  [by a direct commit](https://github.com/NixOS/nixpkgs/commit/3118b08635f5bd23d4daa1465571030683f38d1a), without a pr, to 24.0.5. (why Idk??)

**Comment by pluiedev** [comment]
Given this is fixed in 24.0.5, I don't see a reason why this issue should remain open

**Comment by McSinyx** [comment]
> For context, mesa was updated [by a direct commit](https://github.com/NixOS/nixpkgs/commit/3118b08635f5bd23d4daa1465571030683f38d1a), without a pr, to 24.0.5. (why Idk??)

FWIW it came via GH-301941 to staging-next, then via GH-303527 (including that commit you referenced) to master.
