### ISSUE TITLE
Package request: GNOME Extension Wiggle

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#294700]
Please add GNOME Extension Wiggle

https://extensions.gnome.org/extension/6784/wiggle/

https://github.com/mechtifs/wiggle

Wiggle is a GNOME 45+ port/fix for Jiggle. Wiggle magnifies the cursor when the mouse is moved rapidly.

**Comment by zendo** [comment]
It's here. https://github.com/NixOS/nixpkgs/pull/293511

**Comment by boustanihani** [comment]
Is this a pull request for all available Gnome extensions?

**Comment by PerchunPak** [comment]
> Is this a pull request for all available Gnome extensions?

Yeah, I basically just ran a script to update all Gnome Extensions (don't know why it doesn't run on cron tho).
https://github.com/NixOS/nixpkgs/tree/bda93c2221bc4185056723795c62e1b4cc661c4b/pkgs/desktops/gnome/extensions#extensions-updates

**Comment by boustanihani** [comment]
Shall I close this issue or better wait until `Wiggle` becomes available to install?

**Comment by PerchunPak** [comment]
Close, I think. I am new to NixOS, but I am sure that in a few days or even hours, 9f6b151ddf88a3a2267aee2bc39c738f87415169 will be available in the unstable branch.

If you don't want to switch to unstable, see also https://discourse.nixos.org/t/installing-only-a-single-package-from-unstable/5598 or if you use flakes https://youtu.be/hlytf6Uxf4E.

**Comment by boustanihani** [comment]
OK thanks
