### ISSUE TITLE
hyprpicker-debug is missing debug sections

### ISSUE THREAD

**Issue by nikita-talalai** [NixOS/nixpkgs#294839]
### Describe the bug
According to [this file](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/window-managers/hyprwm/hyprpicker/default.nix) package has debug option, but it seems to do nothing with the resulting executable.

### Steps To Reproduce
1. Create dev shell with hyprpicker (with debug option set true)
`nix develop --impure --expr "with import <nixpkgs> {}; pkgs.mkShell { packages = [ (hyprpicker.override { debug = true; }) ]; }"`
2. Inspect the executable with readelf
`readelf -SW $(which hyprpicker)`

### Expected behavior
The executable has debug sections

### Additional context
In my case Hyprpicker crashed due to a segmentation fault. Rebuilding with debug symbols allowed me to identify the culprit: an empty XCURSOR_THEME environment variable.

### Notify maintainers
@fufexan 

### Metadata
The result of `nix-shell -p nix-info --run "nix-info -m"`:
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.20240301.79baff8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```
 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nikita-talalai** [comment]
My thoughts about the problem:
[This makefile](https://github.com/hyprwm/hyprpicker/blob/2ef703474fb96e97e03e66e8820f213359f29382/Makefile#L51) controls how the program is built. There's a line https://github.com/NixOS/nixpkgs/blob/880992dcc006a5e00dd0591446fdf723e6a51a64/pkgs/applications/window-managers/hyprwm/hyprpicker/default.nix#L76 that seems to prevent debug symbols from being included in the final program, no matter what value debug option have. Buy I'm not familiar with that specific line https://github.com/NixOS/nixpkgs/blob/880992dcc006a5e00dd0591446fdf723e6a51a64/pkgs/applications/window-managers/hyprwm/hyprpicker/default.nix#L37 I didn't find it [here](https://github.com/NixOS/nixpkgs/blob/69ac79b3ffd2d8c2e8ab053ab11a8311649f35e8/pkgs/stdenv/generic/make-derivation.nix#L148). It might be an environment variable.

**Comment by fufexan** [comment]
@nikita-talalai I'm going to rewrite the build process to use CMake exclusively, then update this derivation as well.

**Comment by fufexan** [comment]
Update is live at https://github.com/hyprwm/hyprpicker/commit/698b6ecd54c688620f34fcb46aa202623bfed7fa. Hyprpaper has also been updated.
