### ISSUE TITLE
Waydroid UI causes service to not listen

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#294949]
### Describe the bug

This may be packaging related, but I posted it upstream: 
https://github.com/waydroid/waydroid/issues/1324

### Steps To Reproduce
1. Download Waydroid (on a Plasma 6 system.)
2. Start it via the GUI
3. Hit download

### Expected behavior
Download starts

### Notify maintainers

@CajuM 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.9, NixOS, 24.05 (Uakari), 24.05pre594677.3030f185ba6a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(cosmos): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CajuM** [comment]
Did you enable the waydroid service in your `configuration.nix` with `virtualisation.waydroid.enable = true;`?

**Comment by ShalokShalom** [comment]
No, I just came here to close the issue, have seen it right now in the Wiki.
Thanks

**Comment by ShalokShalom** [comment]
Do we still need to run nixos-generate-config to protect our system?

https://nixos.wiki/wiki/WayDroid

I know the Wiki is outdated at times.

**Comment by CajuM** [comment]
I don't understand, that's a warning not to run the WayDroid container service before running nixos-generate-config if you do that it will add extra mount-points that will get picked-up by the later. Running nixos-generate-config will not protect you from anything, if you've run the container service on the LiveCD, you should try stopping it, I don't recall if that unmounts WayDroid's mount-points. If that doesn't work you can try `umount`-ing them by hand or rebooting.

**Comment by ShalokShalom** [comment]
So, I did not run nixos-generate-config, should I do it now?
Should I do something else?

This is complicated for no reason, from my view. 
Why wouldnt the appropriate thing run automatically?
