### ISSUE TITLE
AAAAAASomeThingsFailToEvaluate mentions nonexistant file

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#294986]
### Describe the bug
```
       error: Please be informed that this pseudo-package is not the only part
       of Nixpkgs that fails to evaluate. You should not evaluate
       entire Nixpkgs without some special measures to handle failing
       packages, like using pkgs/top-level/release-attrpaths.nix.
```
`pkgs/top-level/release-attrpaths.nix` is a nonexistent file.

### Steps To Reproduce
1. `$ nix repl`
2. `nix-repl> pkgs = import <nixpkgs> {}`
3. `nix-repl> pkgs.lib.attrsets.foldlAttrs (a: name: p: (if (p ? setupHook) then (a ++ [ name ]) else a)) [] pkgs`

### Expected behavior
the outputted error message probably should point to the file that exists, `release-attrpaths-superset.nix`.
 
### Additional context
additionally, i can't actually find where `AAAAAASomeThingsFailToEvaluate` is defined in nixpkgs.

if i could find the file, this would likely be a trivial text fix.

### Notify maintainers
i can't find the relevant file, so i don't know who to ping.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.4315.c68a9fc85c2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(binarycat): `"stable-23.05, unstable"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/binarycat/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
nvm, i found [the offending line of code](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L106)

i guess github doesn't search large files?

**Comment by wegank** [comment]
Feel free to create a PR (and ping me for instant approval and merging).

**Comment by kirillrdy** [comment]
isn't AAAAAASomeThingsFailToEvaluate deliberate ? what is proposed fix ?

**Comment by wegank** [comment]
Replace `release-attrpaths.nix` with `release-attrpaths-superset.nix` in the definition of `AAAAAASomeThingsFailToEvaluate`.

**Comment by kirillrdy** [comment]
so it's just to update `throw` message ?

**Comment by wegank** [comment]
Exactly, and that's what the title means too.

**Comment by kirillrdy** [comment]
ok, thank you for explaining. my brain for some reason was trying to look for a more complex problem :-)

**Comment by 7c6f434c** [comment]
As the original drafter of the attribute code, I really hope the throw will keep using a string constant thus not leaving any space for more complex problems — or sollutions!

(If I notice CI-passed patch to this before @­wegank I will also quick-merge it of course)
