### ISSUE TITLE
automounter fails to mount NFS

### ISSUE THREAD

**Issue by YorikSar** [NixOS/nixpkgs#29507]
## Issue description

I'd like to set up default automount's `-hosts` target in my `/net` directory. It sees remote host, shows all its mounts in `/net/xxx.xxx.xxx.xxx/`, but can't mount any of them. Turning on `services.autofs.debug` revealed that automount calls `mount -t nfs ...` and `mount` can't find `/sbin/mount.nfs` helper to do actual mount. It seems that for some reason it doesn't call `mount.nfs` from `nfs-utils` package as it should according to https://github.com/NixOS/nixpkgs/blob/17.03/pkgs/os-specific/linux/autofs/default.nix#L21

### Steps to reproduce

* Add to configure.nix:

```
  services.autofs = {
    enable = true;
    autoMaster = ''
        /net      -hosts -nolock --timeout=60
    '';
    debug = true;
  };
```
* Run `nixos-rebuild`
* Run `ls -l /net/yourserver/someshare` (assuming you have such shares in your network)

Expected:

* share is mounted, files are shown

Actual:

* directory is created, but share is not mounted

## Technical details

* System: `NixOS 17.03.1825.df7e518568 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.14`
* Nixpkgs version: `17.03.1825.df7e518568`
* Sandboxing enabled: no

**Comment by gleber** [comment]
Do you have `nfs-utils` in your system packages? If not, can you add it and retry? It looks like `mount` depends on `mount.nfs` being present in one of system-wide locations `/run/wrappers/bin:/var/run/current-system/sw/bin:/sbin`:
https://github.com/NixOS/nixpkgs/blob/c2b9ab578de944f336c905ebc0ea1820472b2f25/pkgs/os-specific/linux/util-linux/default.nix#L49

See https://github.com/NixOS/nixpkgs/blob/c2b9ab578de944f336c905ebc0ea1820472b2f25/pkgs/os-specific/linux/util-linux/default.nix#L40 for comments why it's done this way.

If this is the source of the issue, one options is to make `autofs` NixOS module add relevant mount helper packages to system packages or only check their presence. Not ideal, but should save other people surprises.

**Comment by YorikSar** [comment]
I definitely remember having nfs-utils installed then. But now on 17.09 everything works fine, so I'll close this issue. Sorry for bothering you and not closing it earlier.

**Comment by gleber** [comment]
Thanks!
