### ISSUE TITLE
`dropbox-cli` may need to be renamed

### ISSUE THREAD

**Issue by seagreen** [NixOS/nixpkgs#29504]
As far as I can tell the [dropbox-cli](https://github.com/NixOS/nixpkgs/blob/6c116b86ebab9b0975e625fa99b49b73239c8529/pkgs/applications/networking/dropbox-cli/default.nix) installs [nautilus-dropbox](https://github.com/dropbox/nautilus-dropbox), which doesn't involve a CLI.

**Comment by seagreen** [comment]
Ping @the-kenny.

**Comment by ttuegel** [comment]
nautilus-dropbox provides two components: a Nautilus plugin and a command-line interface to the Dropbox server. Our package strips out the plugin and installs the CLI.

**Comment by seagreen** [comment]
Gotchya. I think the dropbox package also provides an executable named `dropbox`, which contributed to my confusion.
