### ISSUE TITLE
rasdaemon: segmentation faults

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#295002]
### Describe the bug

For some reason, rasdaemon doesn't work.

dmesg:
```
[44012.883885] traps: rasdaemon[159872] general protection fault ip:7c528af1a524 sp:7c526b3fe9f8 error:0 in libc.so.6[7c528aeb2000+15b000]
[44012.883997] Core dump to |/bin/false pipe failed
[44013.331660] traps: rasdaemon[159917] general protection fault ip:7dba24d1e524 sp:7dba0b3fe9f8 error:0 in libc.so.6[7dba24cb6000+15b000]
[44013.331754] Core dump to |/bin/false pipe failed
```

systemctl:
```
× rasdaemon.service - the RAS logging daemon
     Loaded: loaded (/etc/systemd/system/rasdaemon.service; enabled; preset: enabled)
     Active: failed (Result: signal) since Mon 2024-03-11 15:46:32 CET; 3s ago
   Duration: 99ms
       Docs: man:rasdaemon(1)
    Process: 160922 ExecStart=/nix/store/gi15a2d9s4503djs4xbdyl36i2ladwq2-rasdaemon-0.8.0/bin/rasdaemon --foreground --record (code=killed, signal=SEGV)
   Main PID: 160922 (code=killed, signal=SEGV)
         IP: 0B in, 0B out
        CPU: 64ms

Mar 11 15:46:32 blahaj systemd[1]: rasdaemon.service: Scheduled restart job, restart counter is at 5.
Mar 11 15:46:32 blahaj systemd[1]: rasdaemon.service: Start request repeated too quickly.
Mar 11 15:46:32 blahaj systemd[1]: rasdaemon.service: Failed with result 'signal'.
Mar 11 15:46:32 blahaj systemd[1]: Failed to start the RAS logging daemon.
```

### Steps To Reproduce
1. `hardware.rasdaemon.enable = true;`

### Expected behavior
rasdaemon should work.

### Additional context
Unfortunately, ras-mc-ctl doesn't check if the daemon is working so it took me some time to discover that the daemon actually doesn't work.

### Notify maintainers

@evils 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240310.589df23`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/mq0prikmd63ibrvvzimlwq8fx4g6200p-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
Looks like the latest tagged version is broken on AMD because it doesn't include https://github.com/mchehab/rasdaemon/commit/f1ea76375281001cdf4a048c1a4a24d86c6fbe48
Now I'm running from the latest commit and it works fine

**Comment by evils** [comment]
oh, thanks for finding a solution!

i'll open a PR with that patch in a few hours unless you beat me to it :)

**Comment by evils** [comment]
https://github.com/NixOS/nixpkgs/pull/295103 adds that patch
