### ISSUE TITLE
Spell checking broken in Tuba 0.6.3

### ISSUE THREAD

**Issue by gaykitty** [NixOS/nixpkgs#295026]
### Describe the bug
Spell checking in the nixpkgs version of Tuba appears to be broken whereas it works in the flatpak. In the nixpkgs version of Tuba the only language listed in the right click menu of the composer it Hebrew. I suspect this is relevant.

### Steps To Reproduce
1. Install Tuba
2. Compose a message with a typo
3. No spellcheck

### Expected behavior
Spellcheck should be working like the flatpak version.

### Screenshots
Languages right click menu in nixpkgs Tuba
![Screenshot from 2024-03-11 11-45-20](https://github.com/NixOS/nixpkgs/assets/126119280/d73642cc-266d-4d76-8b3e-46effa57db31)

Same menu in flatpak Tuba
![Screenshot from 2024-03-11 11-43-51](https://github.com/NixOS/nixpkgs/assets/126119280/2e4da6ec-512b-4bc4-abd0-96fc0d977183)

### Notify maintainers

@chuangzhu @Aleksanaa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.81, NixOS, 23.11 (Tapir), 23.11.20240308.2be119a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(sasha): `"nixos, nixpkgs"`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/home/sasha/.nix-defexpr/channels/nixpkgs`
```
My full nixos config can be found here: https://git.sr.ht/~zethra/nixcfg

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
`iotas` is also affected by the same problem:

```
00:31:16 | spellcheck | WARNING | no installed dictionary for language "en_US" and english, fallback to first language inlanguage list ("he")
```

But it depends on `python3Packages.pygtkspellcheck`, not `libspelling`.

**Comment by gaykitty** [comment]
Can confirm that adding `hunspellDicts.en_US` to `environment.systemPackages` in my nixos config fixed the issue. Thx <3 I feel like this should be better documented in NixOS (not that that's on you per se).

**Comment by Aleksanaa** [comment]
We'll probably add something like `i18n.spellCheck` and set it to true for usual desktop environments. But the problem now is that the name of these language packs do not correspond to the locale, so more work still needs to be done.
