### ISSUE TITLE
`lua51Packages.nfd` is broken

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#295022]
### Describe the bug
After installing `lua51Packages.nfd`, running `require("nfd")` in lua 5.1 produces the error:
```
clua: error loading module 'nfd' from file '/nix/store/xasw4xnar4b6dq1z2jn1vq9p2rfxhnzz-lua5.1-nfd-scm-1/lib/lua/5.1/nfd.so':
	/nix/store/xasw4xnar4b6dq1z2jn1vq9p2rfxhnzz-lua5.1-nfd-scm-1/lib/lua/5.1/nfd.so: undefined symbol: NFDi_IsFilterSegmentChar
stack traceback:
	[C]: ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: ?
```

### Steps To Reproduce
```shell
nix-shell -E '{ pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs/tarball/master) {} }: with pkgs; mkShell { packages = with lua51Packages; [ lua nfd ]; }' --run "lua -e 'print(require(\"nfd\").open())'"
```

### Expected behavior
The command above should open a file selection dialog, and print the selected file path.

### Additional context
Changing `master` to `nixos-23.11` gives the expected result, so there is some commit that broke the package. Currently, the commits that changed `pkgs/development/lua-modules/nfd/default.nix` between `nixos-23.11` and `master` are 089f45c and 50e877e, both authored by @teto. I wanted to find out which exact commit caused the breaking, but building from the past nixpkgs failed due to an error in building `tzdata-2024a`, so I do not know which exact commit caused the breaking.

By the way, the version of the `nfd` package is `ncm-1`. Is it right? If the upstream is not tagged with appropriate versions, maybe at least use the commit hash as the version; otherwise, users won't get updates without collecting garbage if you never change the version field in nixpkgs.

### Notify maintainers

@Scoder12

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.4575.526d051b128b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
1. could you provide a replication command that doesn't involve re-downloading the entirety of nixpkgs?  i'm dealing with rural internet here.
2. `pkgs.lua` is an alias for `pkgs.lua5_2`.  it should not be mixed with `lua51Packages`.
3. it's unlikely the breaking change was in nfd, the lua ecosystem on nixpkgs has been undergoing a lot of changes, and a fair few things have been getting broken in the process.

**Comment by UlyssesZh** [comment]
> could you provide a replication command that doesn't involve re-downloading the entirety of nixpkgs? i'm dealing with rural internet here.

If you have a clone of nixpkgs from within 2 to 3 weeks or so, I think you would be able to reproduce the bug with that clone.

> `pkgs.lua` is an alias for `pkgs.lua5_2`. it should not be mixed with `lua51Packages`.

I am using `lua51Packages.lua` to ensure that I am using lua 5.1. This is because nfd only works on lua 5.1.

**Comment by lolbinarycat** [comment]
congratulations, you have independently demonstrated the pitfalls of nested `with`.  not knowing everything under `luaPackages`, i misinterpreted the expression.

**Comment by lolbinarycat** [comment]
> By the way, the version of the nfd package is ncm-1. Is it right? If the upstream is not tagged with appropriate versions, maybe at least use the commit hash as the version; otherwise, users won't get updates without collecting garbage if you never change the version field in nixpkgs.

this only happens if you also never change the src.hash field
