### ISSUE TITLE
erlang without X dependencies

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#29518]
## Issue description

We are already building a lot of variations of erlang (different versions, different bits compiled in). Would it be acceptable to add yet another one - without X dependencies? 

My guess is that most people don't actually need the X deps, so we could probably remove the X deps from the base version and then have a separate derivation with X support.

Cc:  @the-kenny @sjmackenzie @couchemar @gleber

**Comment by couchemar** [comment]
Do we really need this by default?

IMHO during development one needs some wx-utilities observer for example.

**Comment by peterhoeg** [comment]
I simply extrapolated from a sample size of 1 (myself) to conclude that nobody else needs it! ;-)

So in all seriousness, there are two issues:

a) Should we have separate derivation where X support differs from the main derivation, and

b) Assuming A is yes, then should X or no-X be default

Any thoughts?

**Comment by copumpkin** [comment]
Also possibly related to the (stalled) #29135

**Comment by gleber** [comment]
I'm happy to implement whatever solution is preferred in nixpkgs to
implement headless variants of these packages. IIUC, current builder for
Erlang has enough flags to restart build a headless version of it, so it
seem to be purely question how to represent it.

**Comment by peterhoeg** [comment]
PR available for comments - no change of defaults.

**Comment by grahamc** [comment]
Shall we close ? :)
