### ISSUE TITLE
Update request: bazel_7 7.0.2 → 7.1.0

### ISSUE THREAD

**Issue by aaronmondal** [NixOS/nixpkgs#295194]
- Package name: bazel_7
- Latest released version: 7.1.0

- Current version on the unstable channel: 7.0.2
- Current version on the stable/release channel: 7.0.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by taranarmo** [comment]
According to readme file in the bazel directory maintainers team is @NixOS/bazel

**Comment by aaronmondal** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/299358
