### ISSUE TITLE
Build failure: systemc on macOS

### ISSUE THREAD

**Issue by KireinaHoro** [NixOS/nixpkgs#295282]
### Steps To Reproduce

1. enable unsupported systems (`nixpkgs.config.allowUnsupportedSystem = true;`)
2. build systemc on macOS

### Build log

```
error: builder for '/nix/store/6l6j5dps1la0jp38zk9q0dnc439s7flc-systemc-2.3.4.drv' failed with exit code 1;
       last 10 log lines:
       > checking whether the compiler supports GNU C... yes
       > checking whether clang accepts -g... yes
       > checking for clang option to enable C11 features... none needed
       > checking whether clang understands -c and -o together... yes
       > checking dependency style of clang... none
       > checking whether we are using a Clang/LLVM C compiler... yes
       > checking the archiver (ar) interface... ar
       > checking dependency style of clang... none
       > checking whether ln -s works... yes
       > configure: error: "sorry...architecture not supported"
       For full logs, run 'nix log /nix/store/6l6j5dps1la0jp38zk9q0dnc439s7flc-systemc-2.3.4.drv'.
```

### Additional context

Verilator declares support for all Unix platforms, which includes `aarch64-darwin`.  However, systemc only declares support for Linux.

systemc has support for macOS (aarch64-darwin), but it is only accessible with CMake; the derivation currently uses the autoconf script and thus does not support this.

### Notify maintainers

@victormignot @amiloradovsky 

### Metadata

```console
-> % nix-info -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KireinaHoro** [comment]
@NickCao

**Comment by NickCao** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/295463
