### ISSUE TITLE
Document autoLogin setup and/or improve default behaviour

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#29526]
## Issue description

As far as I can see it isn't explained in the manual how to set up autoLogin for a X11 session. It took me quite a while to get it working as expected. In my case it might have been complicated by using i3, but I needed to set defaults for the windowsManager and desktopManager as well. E.g.

```
xserver = {
      enable = true;

      displayManager.lightdm = {
        enable = true;
        autoLogin.enable = true;
        autoLogin.user = "foo";
      };

      windowManager.i3.enable = true;
      desktopManager.default = "none";
      windowManager.default = "i3";
    };
};
```

If only one displayManager and one windowManager is enabled, I'd expect the defaults to be set to automatically. The setup above seems unnecessarily verbose.

Also esp. unexpected was that the default of desktopManager.default is xterm. Is there any scenario (besides no having windowManager installed/configured) where that is helpful?

**Comment by Moredread** [comment]
BTW, is the issue tracker a good location to discuss something like this or is it more suitable for the ML?

**Comment by domenkozar** [comment]
Issue tracker is good. I think these docs should be in `autoLogin.enable` description. Although they don't work for me using kodi instead of i3. Have to dig in why.
