### ISSUE TITLE
Package request: livi

### ISSUE THREAD

**Issue by tlvince** [NixOS/nixpkgs#295373]
**Project description**

A simple GTK4 based video player for mobile phones

**Metadata**

* homepage URL: https://gitlab.gnome.org/guidog/livi
* source URL: https://gitlab.gnome.org/guidog/livi
* license: GPL3
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MkSafavi** [comment]
Hi.
Is this a package you're working on?
If not, I packaged it but I'm not sure if it's correct. I can send a PR for it as starter.
[It's the first time built anything on NixOS.]

**Comment by MkSafavi** [comment]
I added a PR for this. It would be great if you could check it out.
Though running it gives this warning but can play videos.
`(livi:180938): livi-window-WARNING **: 00:23:39.217: V4L stateless codec not in use, playback will likely be slow`
Also I couldn't play x265 videos with it. Is this normal?
