### ISSUE TITLE
NetworkManager[1307]: <warn>  [1710263657.2248] dns-mgr: init: ns mode 'unbound' was removed. Update your configuration

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#295369]
### Describe the bug
I see the following warning in my syslog: `NetworkManager[1307]: <warn>  [1710263657.2248] dns-mgr: init: ns mode 'unbound' was removed. Update your configuration`

I guess it has got to do with me setting `unbound` as my dns resolver, but it is listed as an option for [networking.networkmanager.dns](https://search.nixos.org/options?channel=unstable&show=networking.networkmanager.dns&from=0&size=50&sort=relevance&type=packages&query=networkmanager) , so i don’t understand why the log warning says that it has been removed.

In my `configuration.nix` i've set:
```
networking = {
    hostName = "nixos";
    nameservers = ["127.0.0.1" "::1"];
    dhcpcd = {
      wait = "if-carrier-up";
      extraConfig = "nohook resolv.conf noarp";
    };
    networkmanager = {
      enable = true;
      plugins = lib.mkForce []; 
      dns = "unbound";
      wifi.backend = "iwd";
      wifi.powersave = true;
    };
  };

  services.unbound = {
    enable = true;
    enableRootTrustAnchor = true;
    settings = {
      server = {
        verbosity = "0";
        cache-min-ttl = "300";
        cache-max-ttl = "86400";
        use-syslog = "yes";
        hide-identity = "yes";
        hide-version = "yes";
        harden-short-bufsize = "yes";
        harden-large-queries = "yes";
        harden-glue = "yes";
        harden-dnssec-stripped = "yes";
        harden-below-nxdomain = "yes";
        harden-referral-path = "yes";
        harden-algo-downgrade = "yes";
        ip-freebind = "no";
        qname-minimisation = "yes";
        use-caps-for-id = "yes";
        prefetch = "yes";
        prefetch-key = "yes";
        rrset-roundrobin = "yes";
        minimal-responses = "yes";
        tls-cert-bundle = "/etc/ssl/certs/ca-certificates.crt";
      };
      remote-control.control-enable = false;
    };
  };
```
### Steps To Reproduce
1. Set the above settings in `configuration.nix`

### Expected behavior
I don't understand the severity of the warning but i guess it shouldn't be there.

### Additional context
Also open on [discourse](https://discourse.nixos.org/t/nixos-networkmanager-1303-warn-1709934611-6366-dns-mgr-init-ns-mode-unbound-was-removed-update-your-configuration/41038)

### Notify maintainers
@Janik-Haag 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.9, NixOS, 24.05 (Uakari), 24.05pre594677.3030f185ba6a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Janik-Haag** [comment]
Upstream dropped unbound almost a year ago https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/5da17c689be5e66ea2f63dea6f1846625e652998 but I guess no one bothered, I'll drop the unbound option.
