### ISSUE TITLE
Plasmatube fails to play videos due to youtube-dl error

### ISSUE THREAD

**Issue by resignationinfinite** [NixOS/nixpkgs#295375]
### Describe the bug
Plasmatube works in every way except actually playing videos

### Steps To Reproduce
1. Open Plasmatube
2. Try to play any video

### Expected behavior
The video should play.

### Screenshots
The thumbnail loads but the spinner just spins instead of the video playing.

### Additional context
Error log:

[ytdl_hook]  
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
No protocol handler found to open URL ytdl://xfRk-GTLDoc
The protocol is either unsupported, or was disabled at compile-time.
[ytdl_hook]  
[ytdl_hook] youtube-dl failed: not found or not enough permissions 

Shouldn't it be trying to use yt-dlp instead of the deprecated youtube-dl?

### Notify maintainers
@ilya-fedin 
@K900 
@LunNova 
@mjm 
@NickCao 
@SuperSandro2000 
@ttuegel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05pre594677.3030f185ba6a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Hmm, I thought we fixed that, but I guess not. Anyway, please test https://github.com/NixOS/nixpkgs/pull/295377
