### ISSUE TITLE
Update request: orca-slicer 1.9.1 → 2.0

### ISSUE THREAD

**Issue by etrigan63** [NixOS/nixpkgs#295351]
- Package name: orca-slicer
- Latest released version: 2.0

- Current version on the unstable channel: 1.9.1
- Current version on the stable/release channel: n/a

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@zhaofengli
@ovlach
@pinpox
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by etrigan63** [comment]
@zhaofengli 
@ovlach 
@pinpox

**Comment by etrigan63** [comment]
Also the current version is failing to build:
```
error: builder for '/nix/store/lr7xjvgmrn9n2gfjll1zgmb96p4dsc3m-orca-slicer-1.9.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/nyazxw72pcf2m9icb283g68li10xizwc-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3969dqapbnigkpq8km66n1rqc18ffd7m-orca-slicer-1.9.1_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/in716ialj87b41m5xcc3ayczgls9485x-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/airj9sk6jm961p9gjs3qhpjy01z3hzxv-nixos-system-ironforge-23.11.5441.614b4613980a.drv' failed to build
```

**Comment by pinpox** [comment]
That is a beta version. I think we should follow official releases. 
What version are you trying to build? Building from nixpkgs master builds fine for me

**Comment by etrigan63** [comment]
The orca-slicer teams has it linked as latest stable release. All I am doing with the one in unstable is just adding it to configuration.nix. There is no version of orca-slicer in nix stable.

**Comment by mabl** [comment]
I guess the "need" for the new version originates from stable slicer advertising a new release (2.0 beta) on startup - and the pretty neat new features in that beta release. (Scarf joint seams and Small area flow compensation work like a charm!)

In any case, at least a the beta is easily built using

```nix
{ lib, fetchFromGitHub, makeDesktopItem, bambu-studio }:

bambu-studio.overrideAttrs (finalAttrs: previousAttrs: {
  version = "2.0.0-beta";
  pname = "orca-slicer";

  # Don't inherit patches from bambu-studio
  patches = [
    ./0001-not-for-upstream-CMakeLists-Link-against-webkit2gtk-.patch
  ];

  src = fetchFromGitHub {
    owner = "SoftFever";
    repo = "OrcaSlicer";
    rev = "v${finalAttrs.version}";
    hash = "sha256-P9sN9gqUyGKA5DHGyPRyqkV+ZmQbRPto21zvLYHOz+M=";
  };

  meta = with lib; {
    description = "G-code generator for 3D printers (Bambu, Prusa, Voron, VzBot, RatRig, Creality, etc";
    homepage = "https://github.com/SoftFever/OrcaSlicer";
    license = licenses.agpl3Only;
    maintainers = with maintainers; [ zhaofengli ovlach pinpox ];
    mainProgram = "orca-slicer";
    platforms = platforms.linux;
  };
})
```

**Comment by etrigan63** [comment]
> That is a beta version. I think we should follow official releases. What version are you trying to build? Building from nixpkgs master builds fine for me

I was building the version in unstable but I am on 23.11 and it is throwing mesa errors. There is a PR to backport it and Bambu Studio to 23.11 to resolve this, but if they procrastinate another month+, the issue may go away with the release of 24.05.

**Comment by mabl** [comment]
The official 2.0 release is out :-)

**Comment by etrigan63** [comment]
I have updated the title and the details to reflect this.

**Comment by etrigan63** [comment]
A back port to 23.11 would be highly appreciated.

**Comment by pinpox** [comment]
Update PR is out. I'll add a backport PR when it's merged
