### ISSUE TITLE
SVP broken by mpv 0.37.0's vf-del removal

### ISSUE THREAD

**Issue by xrun1** [NixOS/nixpkgs#295429]
### Describe the bug
When changing an SVP option during playback or the played file in mpv, starting from mpv 0.37.0, due to https://github.com/mpv-player/mpv/commit/b56e63e2a96b67aff4050d4db06ee67665893c36, it spams:
```console
Option vf-del: 0 doesn't exist.
```
and SVP no longer reports any connected player at the bottom of its window after that. 

### Steps To Reproduce
1. Run `SVPManager`
2. Click top left logo, "Open file via mpv", pick a video
3. While the video is playing, switch back and forth between one of the buttons under "Do frame rate conversion" like "To screen" and "Movie x2" 

### Expected behavior
In mpv 0.36 and earlier, it says:
```console
Option vf-del: -del is deprecated! Use -remove (removes by content instead of by index).
```
and SVP keeps working normally.

### Additional context
SVP has no source code available and new versions haven't been released on Linux since 2021, while mpv 0.37 came out in November 2023, making it unlikely to be fixed upstream any time soon.

I've made a dirty workaround by [forking mpv](https://github.com/xrun1/mpv-svp-fix) to re-add the `vf-del` option, and overriding the source of the mpv package in my flake + home-manager setup. Handling both the external mpv package and the one within SVP's (the mpv that gets used by SVP's in-GUI "Open file") gets complicated - here are the relevant parts:
```nix
# flake.nix

inputs = {
    mpvSockets.url = "github:wis/mpvSockets";
    mpvSockets.flake = false;
    mpvSvpFix.url = "github:xrun1/mpv-svp-fix/3d4bc22ad14fcb2f46a3ce6a71b4a7b9ade574ea";
    mpvSvpFix.flake = false;
};
# ...

# mpv.nix (imported as a home-manager module)  

{ config, pkgs, lib, inputs, ... }: {
    options.mpvCallArgs = lib.mkOption {
        type = with lib.types; attrsOf unspecified;
        default = [];
    };
    options.mpvScripts = lib.mkOption {
        type = with lib.types; listOf package;
        default = [];
    };
    
    config.programs.mpv = {
        enable = true;
        package = with pkgs; wrapMpv
            ((mpv-unwrapped.override config.mpvCallArgs).overrideAttrs {
                src = inputs.mpvSvpFix;
            })
            { scripts = config.mpvScripts; };
        config.script = ["${inputs.mpvSockets}/mpvSockets.lua"];
    };
    # ...
}

# svp.nix (imported as a home-manager module)

{ config, pkgs, lib, ... }: {
    home.packages = with pkgs; let
        removeMpv = from:
            lib.filter (pkg: pkg.meta.mainProgram or "" != "mpv") from;

        buildFHSEnv = attrs: pkgs.buildFHSEnv (attrs // { targetPkgs = pkgs:
            (removeMpv (attrs.targetPkgs pkgs)) ++
            [config.programs.mpv.package];
        });
    in [(svp.override { inherit buildFHSEnv; })];

    mpvCallArgs.vapoursynthSupport = true;
    programs.mpv.config.hr-seek-framedrop = "no";  # prevent desyncs on seek
}
``` 

### Notify maintainers

@xddxdd 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7, NixOS, 24.05 (Uakari), 24.05.20231217.91a0070`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xddxdd** [comment]
Thanks for your investigation! Indeed it looks like modifying mpv to add the option back is the best way. Based on the diff on your fork, the change seems small enough for us to maintain. On the other hand, patching SVP is impossible due to its tamper protection.

**Comment by xrun1** [comment]
A couple questions:
1. When the mpv package gets updated, it might break building SVP with the patch. Do github checks catch these cases, or will the SVP package just be broken until someone else notices?
2. Should I give you push access to the forked repo, to rebase and regenerate the patch as needed? I rarely update my system, so the repo will likely be left randomly outdated until I have to take care of it.
3. Can you make the SVP package take `mpv-unwrapped` and `wrapAttrs` overridable parameters, so that it isn't so hard to e.g. add scripts to the internal mpv?
4. Trying to make a standard external mpv connect to SVP will fail since it won't be patched, is there a good way to indicate to users that they should install `pkgs.svp.mpv` in their environment? The parameters mentioned above should probably also be made known.

**Comment by xddxdd** [comment]
1. SVP package in nixpkgs will be broken. However I also have this SVP package on my NUR, and have daily CI runs to rebuild packages, so once it breaks I will notice and make a fix.
2. It isn't necessary. I can rebase the patch on mainline mpv as needed.
3. I will add them.
4. I can't think of any good way for now.
