### ISSUE TITLE
bluez doesn't build gatttool anymore

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixpkgs#29542]
Due to the bluez upgrade dadb16a57f6b13393d5f34d0e009ec0c2e50079b for #29289, gatttool isn't built by default anymore.

We should try to find out why and install it again.

**Comment by globin** [comment]
It is added to `noinst_PROGRAMS` which seems to make it intentionally be left out. Also I cannot find a PR wishing for it to be installed, which was mentioned in the commit removing it.

**Comment by musteresel** [comment]
I know this is an old issue, but is there any plan to build gatttool again? Or is it available somewhere else (another pkg in nixpkgs)?

**Comment by jyp** [comment]
Even though it's deprecated upstream every bluetooth low-energy tutorial I can find instructs to use gatttool. So, it appears to be a critical component of the toolchain. Any idea on how to re-instate gatttool? Any other way to pair a BLE device?
