### ISSUE TITLE
`bitcoind` doesn't have wallet methods enabled

### ISSUE THREAD

**Issue by plebhash** [NixOS/nixpkgs#295444]
### Describe the bug
`bitcoind` doesn't have wallet methods enabled.

### Steps To Reproduce
```
# nix-shell -p bitcoin
$ bitcoin-cli createwallet
error code: -32601
error message:
Method not found
```

### Expected behavior
```
# nix-shell -p bitcoin
$ bitcoin-cli createwallet
{
  "name": "",
  "warning": ""
}
```

### Notify maintainers

@prusnak @roconnor

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
plebhash@nixos  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 23.05 (Stoat), 23.05.5533.70bdadeb94ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"musnix, nixos-23.05"`
 - channels(bear): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by prusnak** [comment]
> `bitcoin-cli` doesn't have wallet methods enabled.

Are you using `bitcoind` from nixpkgs? Because `bitcoin-cli` is just stupid RPC and `Method not found` comes from `bitcoind` not `bitcoin-cli` IIRC.

**Comment by plebhash** [comment]
> > `bitcoin-cli` doesn't have wallet methods enabled.
> 
> Are you using `bitcoind` from nixpkgs? Because `bitcoin-cli` is just a stupid RPC and `Method not found` comes from `bitcoind` not `bitcoin-cli` IIRC.

you're right, sorry that was a misleading issue title.

but anyways, yes, my entire setup is coming from nixpkgs.

**Comment by prusnak** [comment]
> but anyways, yes, my entire setup is coming from nixpkgs.

How do you install bitcoind?

**Comment by plebhash** [comment]
> > but anyways, yes, my entire setup is coming from nixpkgs.
> 
> How do you install bitcoind?

I just drop a `nix-shell`:
```
# nix-shell -p bitcoin
$ bitcoind
```

**Comment by prusnak** [comment]
> ```
> - channels(root): `"musnix, nixos-23.05"`
> ```

NixOS 23.05 has reached EOL.

Can you see the same issue with 23.11?

**Comment by plebhash** [comment]
I tried reproducing the issue on 23.11 without success.
I guess it's not really an issue then, so I'm gonna close this.

Thanks @prusnak
