### ISSUE TITLE
Update request: python311/312.polars 0.20.7 → 0.38.2

### ISSUE THREAD

**Issue by jalil-salame** [NixOS/nixpkgs#295400]
- Package name: `python311.polars` and `python312.polars`
- Latest released version: 0.38.2

- Current version on the unstable channel: 0.20.7
- Current version on the stable/release channel: 0.19.12

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@happysalada 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
thanks for posting!
The latest python version is 0.20.15
The PR is https://github.com/NixOS/nixpkgs/pull/295451
it's almost straightforward, happy to be tagged if you want to make an update next time.
