### ISSUE TITLE
Package request: stl-thumb-kde

### ISSUE THREAD

**Issue by theotheroracle** [NixOS/nixpkgs#295436]
**Project description**

this software allows STL files to be thumbnailed in dolphin and other qt based file-managers

**Metadata**

* homepage URL: https://github.com/unlimitedbacon/stl-thumb-kde
* source URL: https://github.com/unlimitedbacon/stl-thumb-kde
* license: mit
* platforms: linux

---

( i'm going to try to take a crack on packaging this, but i'm not super experienced )

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SyntaxualSugar** [comment]
This is a duplicate of [292685](https://github.com/NixOS/nixpkgs/issues/292685).

**Comment by SyntaxualSugar** [comment]
If you could thumb up 292685 and [233835](https://github.com/NixOS/nixpkgs/issues/233835), that might help draw attention to the request for stl-thumb.

**Comment by theotheroracle** [comment]
ok did !
