### ISSUE TITLE
unbound module: set correct `networking.networkmanager.dns` value 

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#295541]
### Describe the bug
NetworkManager dropped `unbound` support but the unbound module still sets `networking.networkmanager.dns = "unbound"`, leading to the following warning in the syslog: `NetworkManager[1477]: <warn>  [1710317259.2291] dns-mgr: init: ns mode 'unbound' was removed. Update your configuration`

### Steps To Reproduce

1.set `services.unbound.enable = true;`
2. reboot and check the syslog

### Expected behavior
The unbound module should set the correct value (which i don't know to be honest).

### Additional context
See https://github.com/NixOS/nixpkgs/issues/295369

### Notify maintainers
@Janik-Haag
@dasJ 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05pre596105.0ad13a683344`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Janik-Haag** [comment]
I missed that the unbound module sets the `networking.networkmanager.dns` option, I'll drop that in another pr.
As to the question you asked about being able to use unbound with networkmanager, I'm afraid you cant because upstream doesn't support that anymore and if you want support regarding this ask in the freedesktop community spaces.
