### ISSUE TITLE
Installing haskellPackages.yst fails

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29552]
## Issue description
Running
` nix-env -f "<nixpkgs>" -iA haskellPackages.yst `

generates
```
e/25hvrv50c1iicyxqv9zqnr1rkipjm3v9-yst-0.5.1.1-doc’, ‘/nix/store/ap2i6siz2vmq4b0p08p6lig8kb72llc6-yst-0.5.1.1-data’, ‘/nix/store/phw4fxpmhqmbal2391hnglbfjirysblh-yst-0.5.1.1-bin’, ‘/nix/store/qnvqvb7pql520zf7k1s3717lbqjwxfcr-yst-0.5.1.1’, ‘/nix/store/wjwivcsqyngvwwy66axz6dicsk9808x5-yst-0.5.1.1-libexec’
setupCompilerEnvironmentPhase
Build with /nix/store/9hdqgql55k0rhzq2qaxgx3xscw2yf9dn-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/87v38va0lhixnlkbcnmavc7zsql2dipa-yst-0.5.1.1.tar.gz
source root is yst-0.5.1.1
setting SOURCE_DATE_EPOCH to timestamp 1467973833 of file yst-0.5.1.1/Yst/Yaml.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-yst-0.5.1.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-yst-0.5.1.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/qnvqvb7pql520zf7k1s3717lbqjwxfcr-yst-0.5.1.1 --bindir=/nix/store/phw4fxpmhqmbal2391hnglbfjirysblh-yst-0.5.1.1-bin/bin --libdir=/nix/store/qnvqvb7pql520zf7k1s3717lbqjwxfcr-yst-0.5.1.1/lib/ghc-8.0.2 --libsubdir=$pkgid --libexecdir=/nix/store/wjwivcsqyngvwwy66axz6dicsk9808x5-yst-0.5.1.1-libexec/bin --sysconfdir=/nix/store/13w1pvcvq0931scl0m3vhcvwgrwf4925-yst-0.5.1.1-etc/etc --datadir=/nix/store/ap2i6siz2vmq4b0p08p6lig8kb72llc6-yst-0.5.1.1-data/share/ghc-8.0.2 --docdir=/nix/store/25hvrv50c1iicyxqv9zqnr1rkipjm3v9-yst-0.5.1.1-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-yst-0.5.1.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/qnvqvb7pql520zf7k1s3717lbqjwxfcr-yst-0.5.1.1/lib/ghc-8.0.2/yst-0.5.1.1 --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections
Configuring yst-0.5.1.1...
Setup: Encountered missing dependencies:
aeson >=0.7 && <0.12, pandoc >=1.10 && <1.18
builder for ‘/nix/store/3mfyjd47n9zsdl7fldsq0gr4pm6x61sf-yst-0.5.1.1.drv’ failed with exit code 1

```

with <nixpkgs> pointing at nixpkgs-unstable.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) nixos
* Nix version: (run `nix-env --version`) 1.11.14
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 18.03.git.d0d905668
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) nope

**Comment by teto** [comment]
Switching to the branch  "haskell-updates" seems to have fixed it.

**Comment by rvl** [comment]
Link to issue jgm/yst#50

**Comment by teto** [comment]
thanks for linking it. I still have trouble installing the new version though. The nix derivation includes the latest aeson while it should require an older one (also present in nixpkgs under a different name).

**Comment by rvl** [comment]
The new version probably isn't in nixpkgs yet. I was able to make yst 0.5.1.1 build by adding a "jail break" to `haskell-packages/configuration-common.nix`. If you don't have nixpkgs checked out you could do the override another way.

**Comment by teto** [comment]
The new version in available in the haskell-updates branch (updated everyday) but on another repo.
I thought there was an override file but didn't know it was configuration common.
Didn't know about the jailbraik thing it's awesome thanks. Yet it seems like a waste to build a jail when the required aeson is available in nixpkgs, it would be best to fix hackage2nix to check for maximum versions.
So I am not sure I should send a jail PR for that (it did work though).

**Comment by rvl** [comment]
Cabal "jail break" just removes *all* version bounds. You can also override its aeson version -- there are examples in the configuration file.

If the latest version of yst works with the latest version of all its dependencies, the best course of action is probably to override it in your personal/project configuration, until your preferred nix channel updates with the fixed version.

**Comment by rvl** [comment]
@teto Hello, is this still an issue for you?

**Comment by teto** [comment]
was looking at the issue this morning: from the moment I could install yst with the jail: it was ok for me so feel free to close this.

**Comment by rvl** [comment]
Many NixOS contributors don't have commit access (⇒ issue tracker access), myself included. Could you please close it? Would be nice to get back under 2000 open issues.
