### ISSUE TITLE
nginx with nginxModules.echo is broken on nixos-17.09

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#29555]
## Issue description
As per the title, `nginx` with `nginxModules.echo` is broken on revision `670b4e29adc16e0a29aa5b4c126703dcca56aeb6`

### Steps to reproduce

```
git clone https://github.com/NixOS/nixpkgs-channels
cd nixpkgs-channels
git checkout 670b4e29adc16e0a29aa5b4c126703dcca56aeb6
nix-build -I nixpkgs=. -E "with import <nixpkgs> {}; let stable = import <nixpkgs/pkgs/servers/http/nginx/stable.nix>; in pkgs.callPackage stable { modules = [nginxModules.echo]; }"
```

## Technical details

* System: 17.03.1820.a0e6a891ee
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: `670b4e29adc16e0a29aa5b4c126703dcca56aeb6`
* Sandboxing enabled: no

**Comment by vaibhavsagar** [comment]
Usually these issues are closed when a fix is committed to master, but it can still take a few days for that change to make its way to `nixos-17.09`. My actual issue is that I can't build `nginx` on 17.09, so can I ask that this remain open until that is fixed?

**Comment by Mic92** [comment]
I also added it to 17.09. I don't think there is much value in keep it open, as it will be resolved automatically on the next channel update.

**Comment by vaibhavsagar** [comment]
You're completely right, thanks for your help!
