### ISSUE TITLE
collectd: 5.7.2 -> git?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#29559]
```collectd``` has [almost 500 commits](https://github.com/volth/collectd/releases/tag/collectd-5.7.2) since its last release ```5.7.2```.
Many of them are about supporting newer versions of software which collectd monitors.
And that software is already updated to the newer version in NixOS.
Collectd releases naturally delay few months compared to releases of software it monitors.

For example, ```collectd 5.7.2``` does not work well with new ```libvirt``` version included in NixOS.

Such issues are usually fixed in NixOS by cherry-picking updates from git, but taking into account 
 * the variety of software collectd is aware of,
 * number of commits to review,
 * the constant nature of the release delay (which would not be resolved in ```5.7.3``` or ```5.8```, because the monitored software would go forward too),

would it make sense to follow git branch in ```nixos-unstable``` instead of being stuck to the outdated-by-design last release version?

**Comment by bjornfor** [comment]
Seems like this issue affects all users of collectd, not only NixOS. IMHO, the best thing is to help make new collectd releases happen rather than working around the the problem by doing local fixes in nixpkgs.

**Comment by volth** [comment]
Related https://github.com/collectd/collectd/issues/2420

**Comment by fpletz** [comment]
collectd 5.8.0 was released: https://github.com/collectd/collectd/releases/tag/collectd-5.8.0

**Comment by volth** [comment]
> collectd 5.8.0 was released

Yes, and it already has ~100 commits with post-release fixes.
Following ```git```-version might still have sense
