### ISSUE TITLE
Package request: rime-japanese

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#295527]
**Project description**

Input method for typing Japanese with RIME

**Metadata**

* homepage URL: https://github.com/gkovacs/rime-japanese
* source URL: https://github.com/gkovacs/rime-japanese
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Hm, this won't be trivial — [generateFetchSchema.sh](https://github.com/NixOS/nixpkgs/blob/55235c850195518933ff69ac3e46efb2b51d160f/pkgs/data/misc/rime-data/generateFetchSchema.sh) under rime-data is designed to only work for schemas under the rime organization, and needs to be rewritten to support repos under other owners... I'll see what we can do

**Comment by pluiedev** [comment]
> In fact, we can override rimeDataPkgs to do this, don't need to modify rime-data:
> 
> ```nix
> let
>   rimeDataPkgs = with pkgs; [
>     rime-data
>     rime-japanese
>   ];
> in
> {
>   i18n.inputMethod.fcitx5.addons = with pkgs; [
>     (fcitx5-rime.override { rimeDataPkgs = rimeDataPkgs; })
>   ];
>   i18n.inputMethod.ibus.engines = with pkgs.ibus-engines; [
>     (rime.override { rimeDataPkgs = rimeDataPkgs; })
>   ];
> }
> ```

Hmmmmm... alright, lemme see if I can get away with just packaging rime-japanese itself then
