### ISSUE TITLE
cudaPackages.cudatoolkit: rename, replace with a symlinkJoin

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#295655]
## Issue description

- Rename `cudatoolkit -> cudatoolkit-legacy-runfile`
- Re-expose `cudatoolkit = symlinkJoin { paths = [ cuda_nvcc cuda_cudart ... ]; ...; }`
  - ~~Bonus points: one could introduce a `withPackages` to define the `symlinkJoin`, and then export that as `cudatoolkit.withPackages`~~
- Update the release notes

@NixOS/cuda-maintainers @hacker1024 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by hacker1024** [comment]
For reference, this is what I've been using on Jetsons:

```
        self.symlinkJoin rec {
          name = "cudatoolkit";
          version = cudaSelf.cudaVersion;

          paths = with cudaSelf; [
            cuda_cccl
            cuda_cudart
            cuda_cuobjdump
            cuda_cupti
            cuda_cuxxfilt
            cuda_documentation
            cuda_gdb
            cuda_nvcc
            cuda_nvdisasm
            cuda_nvml_dev
            cuda_nvprune
            cuda_nvrtc
            cuda_nvtx
            cuda_sanitizer_api
            cuda_profiler_api
            libcublas
            libcufft
            libcurand
            libcusolver
            libcusparse
            libnpp
          ];

          passthru = {
            inherit (cudaSelf.backendStdenv) cc;
          } // self.lib.genAttrs
            [ "lib" ]
            (output: self.symlinkJoin {
              name = "${name}-${output}";
              inherit version;

              paths = map (self.lib.getOutput output) paths;
            });
        }
```

**Comment by hacker1024** [comment]
> Bonus points: one could introduce a `withPackages` to define the `symlinkJoin`, and then export that as `cudatoolkit.withPackages`

What would a use case for this be?

**Comment by SomeoneSerge** [comment]
> What would a use case for this be?

I was just wondering about the consistency of interfaces and about accommodating cases where projects still ask for a merged prefix but need a sub- or a super-set of the packages you listed. On the second thought I shouldn't have included this in the description.

> For reference, this is what I've been using on Jetsons:

A PR would be much appreciated!
