### ISSUE TITLE
Package request: sra-tools

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#295710]
**Project description**

The SRA Toolkit and SDK from NCBI is a collection of tools and libraries for using data in the INSDC Sequence Read Archives.

**Metadata**

* homepage URL: https://trace.ncbi.nlm.nih.gov/Traces/index.html
* source URL: https://github.com/ncbi/sra-tools
* license: Government work (Public Domain within United States only)
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by idlip** [comment]
Hi, just wanted to point out that package already exits, `sratoolkit`.

https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/science/biology/sratoolkit/default.nix
