### ISSUE TITLE
`<name>` as prefix in `types.attrsOf types.submodule` is often unhelpful

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#295872]
### Describe the bug
Let's take a look at e.g. `systemd.tmpfiles.settings.<name>.<name>.<name>.user`.

The line itself is the first thing you get when searching for how to use `systemd.tmpfiles` on search.nixos.org. The problem is, how am I supposed to know what each of these `<name>` entries means?
Sure, you can deduce it by looking at the example from `options.systemd.tmpfiles.settings`, but it would be immediately obvious if it's called like this:

`systemd.tmpfiles.settings.<rule-name>.<type>.<path>`

(`type` & `path` are derived from `tmpfiles.d(5)`).

One ad-hoc way of solving that is to add some kind of `namedAttrsOf` function that accepts an argument for the prefix for `getSubOptions`, however it feels wrong to add a new "type" just for that. Also, `namedAttrsOf str` doesn't make much sense, it's effectively the same as `attrsOf str`.

But perhaps the sub-type can provide a "prefix name" to the parent? Like `attrsOf (submodule { options = ...; name = ...; })`? We should probably force it to be in `<`/`>` for `lib.showOption`. Anyways, I know the knobs where to change that, but we should discuss first whether we want this and I'd need some input on how to reasonably design that.

### Notify maintainers

@roberth 
@infinisil 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
The pattern that has established itself is to add -`With` variants, in this case `attrsOfWith`, which takes an attribute set with more arguments. In this case it could be

```
attrsOfWith {
  elemType = ...;
  metaName = ...;
}
```

I'd be in favor of adding something like this :)

**Comment by roberth** [comment]
I think we can drop the `Of`, because we don't have a simply parameter for the type.
```nix
attrsWith {
  elemType = ...;
  ...
}
```

Not sure about `metaName`. Does it only affect docs, or also the module argument?

Context:
- #177576

**Comment by roberth** [comment]
"Meta" is ambiguous in that name. I assume you want it to take the proper meaning of meta, and not refer to the `meta` attribute or something like "name for use in metadata".

`nameName` would solve that, but we can probably do even better.

**Comment by infinisil** [comment]
Oh yeah. I think `metaName` would be fine because the true meaning of meta is the only one that makes sense here. Can't immediately think of a better alternative that would not be more confusing, but I'm open to alternatives (definitely not `nameName` though!).
