### ISSUE TITLE
`networking.resolvconf.useLocalResolver`: add `::1` as nameserver as well

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#295802]
### Describe the bug
`networking.resolvconf.useLocalResolver` only adds `127.0.0.1` as a nameserver if it is enabled. 

Could it be made to also set `::1` for IP6? If not, could you make an extra option for that?

This would avoid having to set this under `networking.nameservers` and thus spreading it out to several options or not using `networking.resolvconf.useLocalResolver` at all, which would be a shame in my opinion because the option clearly states what it does and thus is very approachable.

### Notify maintainers
@pallix @Janik-Haag 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05pre596105.0ad13a683344`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Janik-Haag** [comment]
I'm not too familiar with dns resolver things.  Do you know what would happen if both `::1` and `127.0.0.1` are set and only one server responds? And my I ask what your reason for wanting to have this is? Kernel that only have IPv6 support compiled?
