### ISSUE TITLE
Can't override stdenv phases with empty strings

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nixpkgs#29583]
## Issue description

Likely because the stdenv derivation phases are controlled by environment variables, they can't be overridden by empty strings.  So doing something like:

`stdenv.mkDerivation {
    fixupPhase = "";
}`

still runs the default fixupPhase, but:

`stdenv.mkDerivation {
    fixupPhase = "echo not fixing";
}`

will not.  This is not what a user would likely be expecting.  This limitation should either be documented or fixed.

## Technical details

* System: 17.03.1825.df7e518568 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1825.df7e518568"
* Sandboxing enabled: true

**Comment by FRidh** [comment]
If I am correct the recommended method is to pass ":" instead.

**Comment by ledettwy** [comment]
Sure, but that's dependent on an implementation detail not normally exposed to users (the fact that the ${var:-default} feature of bash is used).

Where is this recommended? Is it in the manual?

**Comment by Artturin** [comment]
we have dontFixup which is documented
