### ISSUE TITLE
can't create folder,  " __nix_qt5__/bin": File exists

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29589]
## Issue description
On nixpkgs-unstable, if you call `nix-shell -A wireshark ~/nixpkgs` twice, then you should see
 `mkdir: impossible de créer le répertoire « /home/teto/wireshark/__nix_qt5__/bin »: File exists` (aka "can't create directory")

Fix might have to do with `pkgs/development/libraries/qt-5/qtbase-setup-hook.sh"`

## Technical details
nixos-version=18.03.git.b20fbd0 (Impala)
nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03.git.b20fbd05e3"
sandboxing disabled

**Comment by olejorgenb** [comment]
Yeah, that is quite annoying.

**Comment by teto** [comment]
I've tried running a preUnpack hook to remove the folder but the error appears before the hook is run :'(
