### ISSUE TITLE
`unbound.enable`: add option `trust-ad` to resolv.conf by default

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#295804]
### Describe the bug
When using unbound, the option `trust-ad` [should be set](https://wiki.archlinux.org/title/Unbound#Local_DNS_server) in resolv.conf.

Can this be added to the unbound module, so that this option is set by default if unbound is set to enabled? Or is this a bad idea?

Maybe this is more relevant now after the support for unbound has been [dropped](https://github.com/NixOS/nixpkgs/issues/295541) by NetworkManager.

### Notify maintainers
@pallix @Janik-Haag 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05pre596105.0ad13a683344`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Janik-Haag** [comment]
uhm not sure, I'm not the unbound maintainer. I think you want to talk to: @nbdd0121 
(btw @nbdd0121 would you mind adding yourself as module maintainer you did most of the recent work on it from skimming through the commit log)

**Comment by nbdd0121** [comment]
I don't think `trust-ad` should be something added by `unbound` module. Perhaps it should be set when `networking.resolvconf.useLocalResolver` is set to true in the `resolvconf` module?

**Comment by Janik-Haag** [comment]
> Perhaps it should be set when networking.resolvconf.useLocalResolver is set to true in the resolvconf module?

cc @picnoir :see_no_evil:

**Comment by picnoir** [comment]
o no. Unfortunate timing.
