### ISSUE TITLE
`singularity` fails to run images

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#295809]
### Describe the bug

Nixpkgs's package of Sylabs SingularityCE (`singularity`) now fails to execute image.

After initial examination, the known cause is the failure to substitute default FHS `PATH`s for some files, but the fix is WIP.

### Steps To Reproduce
1. `cd NixOS/nixpkgs`
2. `nix run .#singularity exec -- "$(nix build .#singularity.tests.image-hello-cowsay --print-out-paths)" hello | nix run .#apptainer exec -- "$(nix build .#apptainer.tests.image-hello-cowsay --print-out-paths)" cowsay`
3. See error.

### Expected behavior
`singularity exec <image> <commands>` should succeed.

```
 _______________
< Hello, world! >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### Notify maintainers
@jbedo @ShamrockLee

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
> nix run .#singularity exec 

singularity isn't supposed to work without setuid?

**Comment by ShamrockLee** [comment]
> > nix run .#singularity exec
> 
> singularity isn't supposed to work without setuid?

Yup. The error seems to result from failure to replace all the default paths after source file hierarchy changes.
