### ISSUE TITLE
krename -  'This program is not installed setuid root -  "user" CIFS mounts not supported.'

### ISSUE THREAD

**Issue by Biepa** [NixOS/nixpkgs#295855]
### Describe the bug
Installing "krename" as user or root is showing the error "This program is not installed setuid root -  "user" CIFS mounts not supported." when trying to access shares. So I assume there needs to be an adjustment in the installation of this tool.
The shares are working fine with Dolphin and other tools.

### Steps To Reproduce
1. Install "krename"
2. Start it
3. Try to access a share

### Expected behavior
To be able to access shares as it works with Dolphin even when installing krename as a user.

### Screenshots
![Screenshot_20240314_122438](https://github.com/NixOS/nixpkgs/assets/25102748/32eebcc7-ce4d-403d-a649-82a97f945044)

### Notify maintainers
@peterhoeg 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240312.0ad13a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/k5l01g2zwhysjyl5zjvg5zxnj0lyxpp1-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by peterhoeg** [comment]
Accessing a share (or any other file resource) is abstracted away by kio and has nothing to do with krename itself.

We are still building krename against kf5, so are you by chance running this in a plasma6 environment?

I am guessing that if you instead mount the shares via `/etc/fstab`, it would work as expected?

**Comment by Biepa** [comment]
Thank you for the reply. Yes I'm running plasma 6.

**Comment by peterhoeg** [comment]
I must admit, I'm not sure exactly how we can have kio from both kf5 and kf6 present with the proper suid wrappers and working for both cases and as I understand it there is work in progress to port krename to kf6/qt6 so presumably within the next couple of months, this will be fixed upstream.

As a workaround, I will suggest mounting via `/etc/fstab` - it's also nicer to have all mounting done declaratively rather than having to manually mount it in user mode.

**Comment by Biepa** [comment]
@peterhoeg Just pinging to clarify it you mean another way that the mentioned "file systems" config option so we can possibly close this.

**Comment by Biepa** [comment]
This is working now for whatever reason.
