### ISSUE TITLE
Gittyup: "Open repository" not working in KDE Plasma 6

### ISSUE THREAD

**Issue by pbek** [NixOS/nixpkgs#295814]
### Describe the bug

In [Gittyup](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/version-management/gittyup/default.nix) with KDE Plasma 6 you'll get an error `Unable to create KIO worker. Unknown protocol 'file'.` when trying to open a repository.

### Steps To Reproduce

1. Use plasma6 with `services.desktopManager.plasma6.enable = true;` (Wayland or X11 doesn't matter) in nixos-unstable
2. Press `Ctrl + O` in Gittyup to open a repository
3. See error dialog `Unable to create KIO worker. Unknown protocol 'file'.`

### Expected behavior

Directory picker allows choosing directory.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/1798101/3d30db76-eb22-4573-ae0c-2c72a0e7868b)

### Logs

```
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.widgets.kdirmodel: protocol mismatch: "file" vs ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Select Folder" msgid_plural: "" msgctxt: "@title:window"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "New Folder..." msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "New Folder..." msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Move to Trash" msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Delete" msgid_plural: "" msgctxt: "@action:inmenu"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Show Hidden Folders" msgid_plural: "" msgctxt: "@option:check"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Properties" msgid_plural: "" msgctxt: "@action:inmenu"
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: "Unable to create KIO worker. Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
kf.kio.core: couldn't create worker: "Unknown protocol 'file'."
```

### Notify maintainers

No maintainers. 😅
@thiagokokada removed himself.
Maybe @zendo?

@K900, is this something you want to get involved in?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240312.0ad13a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbek** [comment]
Workaround: Run `gittyup /your/path` on the CLI.

**Comment by traverseda** [comment]
This seems to effect many different QT apps, including qgroundcontrol, virtualbox, and openscad.

**Comment by pbek** [comment]
Oh, then maybe this really is something the mighty @K900 might be interested in!

**Comment by K900** [comment]
Are those Qt5 apps? They probably need to have kio (and maybe also kio-extras) added as a dependency.

**Comment by pbek** [comment]
Gittyup looks like a Qt5 app, and it's using QFileDialog for opening the directory dialog.

**Comment by pbek** [comment]
> They probably need to have kio (and maybe also kio-extras) added as a dependency.

@K900, I tried with both libs, and it worked, thank you very much. I'll test with just kio too.

**Comment by pbek** [comment]
kio alone was enough, I created https://github.com/NixOS/nixpkgs/pull/296096.

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/297697

**Comment by K900** [comment]
Can people here test https://github.com/NixOS/nixpkgs/pull/302758 please?

**Comment by traverseda** [comment]
I'm pretty new to nix, I understand I'd need to use flakes to test that?

**Comment by pbek** [comment]
> Can people here test #302758 please?

@K900, I just tested this under Wayland with Plasma6 and a fresh reboot. Still works great, thank you!
