### ISSUE TITLE
steamtinkerlaunch: `compat add` adds the unwrapped executable

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#295902]
### Describe the bug

STL needs to be wrapped for its dependencies to be in its PATH and that is in fact done. When creating a compat tool following the official docs (`compat add`), it links the unwrapped executable however.

It should link the wrapped executable instead.

This isn't ideal either since that points at the Nix store and that location is obviously not stable.

What it should ideally do is create a link back to where it's been executed from; the wrapped executable in a global path. When you run it from `/run/current-system/sw/bin/steamtinkerlaunch` or `~/.nix-profile/bin/steamtinkerlaunch`, it should symlink those symlinks, not where those symlinks point to, nor what executable they wrap.  

@sonic2kk, you offered your help in this; would it be possible to use `$0` as the path to link to the compat tool dir (without dereference) or have a build-time boolean option to make STL do that?

Argv0 isn't a great mechanism but it should produce the correct results here in sane shells. Perhaps a check for an absolute path is necessary though as argv0 can be set to a relative path and that wouldn't work at all.

Also, yes it's possible; I've done it via

```
    substituteInPlace $out/bin/steamtinkerlaunch --replace 'realpath "$STLBIN"' 'echo "$STLBIN"'
```

and then ran the wrapped script using a manual invocation but this is obviously a hack and only works with said manual invocation.

It doesn't work when called from a wrapper for some reason. I have no idea why. Probably some ancient UNIX "oh, we see you explicitly set argv0 but we know better" BS that's for us to figure out...

Edit: I looked into it a bit and it's not trivial to solve unfortunately. Bash will always put the script location into $0; we must to do away with the wrapper. @sonic2kk would it be possible to have a build-time option to set the `$PATH`? That'd be a lot cleaner than wrapping too and would allow us to not do wrapping at all. (We could hack it into the script but a `make` flag would be simpler.)

### Notify maintainers

@urandom2 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by decromo** [comment]
`wrapProgram` provides a `--inherit-argv0` argument; curiously it doesn't work here (maybe I used it wrong), the wrapped script's `$0` is still set to itself with this if applied like this:
```nix
steamtinkerlaunch.overrideAttrs (old: { postInstall = "${lib.strings.removeSuffix "\n" old.postInstall} --inherit-argv0''; })
```


Your proposed solution would be the best, but while we wait for upstream I'll share my working (but not heavily tested) workaround for anyone who stumbles upon this:
```nix
environment.systemPackages = [
  (steamtinkerlaunch.overrideAttrs (old: {
        postInstall = ''substituteInPlace $out/bin/steamtinkerlaunch --replace-fail 'STLBIN="$0"' 'STLBIN="$PREFIX/bin/$PROGCMD"'
        ${old.postInstall}'';
  }))
];
```

**Comment by Atemu** [comment]
That's a bash quirk. It overrides argv0 to be the script's name unconditionally IIRC.

The "proper" solution here would be to stop wrapping entirely. Perhaps you could simply concat a writeShellApplication with the original script.
