### ISSUE TITLE
question: should lib.cleanSource remove cmake cache files ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29605]
## Issue description
I've got a wireshark-custom overlay with `src = super.lib.cleanSource ~/wireshark;`
So I compile my program with `nix-shell -A wireshark-custom '<nixpkgs>'` but then, when I want to install it via `nix-env -iA wireshark-custom` I get this error:

`CMake Error: The current CMakeCache.txt directory /tmp/nix-build-wireshark-dev.drv-0/wireshark/build/CMakeCache.txt is different than the directory /home/teto/wireshark/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt`

I wonder if `super.lib.cleanSource` shouldn't ignore the "build" directory during the unpackPhase (potentially harmful) or at least remove CMakeCache.txt/CMakeFiles ? I can send a PR if that's the case.

**Comment by lheckemann** [comment]
It should ignore build directories in general, but I don't think it's reasonable to find a way that works for all invocations. I'd say `cleanSource` and `cleanSourceFilter` (used in its implementation) should be seen more as building blocks for making project-specific source import functions, such as `builtins.filterSource (p: t: lib.cleanSourceFilter p t && builtins.baseNameOf p != "build")`. I've worked with some projects that have a directory named `build` which contains actual sources, and don't think it would be a good idea to exclude it by default.

One (somewhat orthogonal) way to handle this is to use out-of-tree builds when using nix-shell, i.e. `mkdir -p ~/builds/wireshark && cd ~/builds/wireshark && cmake ~/src/wireshark && make` as opposed to creating a build directory within wireshark's source dir, which is a little cleaner in general IMHO.

**Comment by teto** [comment]
Thanks for the nice solutions. I have implemented project-specific filters in my overlay as you recommanded. 
Would be worth adding to the wiki though I am neurotic when it comes to mediawiki syntax.
