### ISSUE TITLE
Package request: pymeshlab

### ISSUE THREAD

**Issue by daef** [NixOS/nixpkgs#296098]
**Project description**

Meshlab dismissed meshlabserver in favour of PyMeshLab, a Python library that interfaces to MeshLab, the popular open source application for editing and processing large 3D triangle meshes.

**Metadata**

* homepage URL: https://www.meshlab.net/
* source URL: https://github.com/cnr-isti-vclab/PyMeshLab
* license: gpl3
* platforms: linux

---

**Comment by nim65s** [comment]
ref #299049
