### ISSUE TITLE
Package request: Proton Mail Desktop

### ISSUE THREAD

**Issue by MikaelFangel** [NixOS/nixpkgs#296107]
**Project description**

The Proton Mail desktop application has been released as a beta in the .deb file format and is a mail client for the Proton Mail.

**Metadata**

* homepage URL: [https://proton.me](https://proton.me)
* source URL: [https://proton.me/mail/download](https://proton.me/mail/download)
* license: unfree (couldn't find any license clearly stated)
* platforms: Linux and Darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
See https://github.com/NixOS/nixpkgs/pull/296127

**Comment by urandom2** [comment]
they seem to claim it is gpl3: https://github.com/ProtonMail/inbox-desktop/blob/main/LICENSE
