### ISSUE TITLE
trouble running OpenGL applications from nixpkgs on Ubuntu 16.04

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#29615]
## Issue description

After `nix-env -i glxinfo`, I attempted to run glxinfo and glxgears:

```
(DevContainer)glxgears 
glxgears: error while loading shared libraries: libXext.so.6: cannot open shared object file: No such file or directory
(DevContainer)glxinfo 
glxinfo: error while loading shared libraries: libXext.so.6: cannot open shared object file: No such file or directory
```

I attempted to correct this by doing `nix-env -i libXext`, but the same error message results after successful installation of libXext. I'm not very familiar with how library loading works with nixpkgs, so maybe this is a user error.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
(DevContainer)cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
* Nix version: (run `nix-env --version`)

```
nix-env (Nix) 1.11.14
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
"18.03pre115884.b5a5d0ba84"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

```
(DevContainer)grep build-use-sandbox /etc/nix/nix.conf
grep: /etc/nix/nix.conf: No such file or directory
```

**Comment by joachifm** [comment]
On NixOS opengl drivers are located at `/run/opengl-driver` I expect many packages expect to load stuff from there.

**Comment by nh2** [comment]
Probably related: https://github.com/NixOS/nixpkgs/issues/9415

**Comment by vcunat** [comment]
Right, better keep OpenGL on non-NixOS in that thread.
