### ISSUE TITLE
Update request: discourse 3.2.0-beta1 → 3.2.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#296144]
- Package name: discourse
- Latest released version: 3.2.0
- Current version on the unstable channel: 3.1.0
- Current version on the stable/release channel: 3.2.0-beta1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@talyz  

https://meta.discourse.org/t/discourse-version-3-2/278584

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
PR downgrading to 3.1.0: https://github.com/NixOS/nixpkgs/pull/291587

**Comment by FliegendeWurst** [comment]
Updated in #299269
