### ISSUE TITLE
Prismlauncher is using software rendering after update

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#296277]
### Describe the bug
For some reason after updating it seems Minecraft ran via Prismlauncher is using llvmpipe instead of my AMD GPU drivers despite me explicitly installing them and having a RX 6800. Other OpenGL applications seem to be unaffected  
```
{pkgs, ...}: {
  boot.initrd.kernelModules = ["amdgpu"];
  services.xserver.videoDrivers = ["amdgpu"];

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true; # Let's 32Bit GPU accelrated aplications run

    # System-wide packages for ROCm (Radeon Open Compute), e.g. AI, etc
    extraPackages = with pkgs; [
      rocmPackages.clr.icd
      rocm-opencl-icd
      rocm-opencl-runtime
    ];
  };

  # Makes sure ROCm can be found by aplications
  systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];

  # Packages for ROCm e.g. AI, etc.
  environment.systemPackages = [
    pkgs.rocmPackages.rocm-smi # Gives GPU info e.g. RX 6800, 16GBs VRAM, core usage 12%, 2043MB VRAM used. Clone of nvidia-smi, not much to do with compute actually
    pkgs.rocmPackages.rocminfo
  ];
}
```

### Steps To Reproduce
1.Try to play game
2. Get 10 FPS
3. See that it is using llvmpipe in f3 menu

### Expected behavior
1. Game runs on GPU and gives much more FPS

### Screenshots
As you can see on the right it is using llvmpipe which is software
![2024-03-15-183130_hyprshot](https://github.com/NixOS/nixpkgs/assets/45698918/bba2f900-c4ff-48d9-b57b-90000734b94f)

### Notify maintainers
@minion3665 @Scrumplex @getchoo

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05.20240314.d691274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
Can you re-set the Java runtime in Prism Launcher? It might be using an older JVM, as it sadly doesn't update automatically whenever the JRE derivation changes.

**Comment by nonetrix** [comment]
I just tried that if I understood correctly at least nothing happened, I clicked refresh here and picked the newest version
![image](https://github.com/NixOS/nixpkgs/assets/45698918/232c955a-c07a-4fd0-80c7-7b6179063141)

**Comment by Scrumplex** [comment]
Hmm. Select the 17.x version and click OK. Note that that dialog doesn't reflect the current value in the Java path text box. After setting it there (and also making sure it's not overridden by the instance), does it change anything?

**Comment by nonetrix** [comment]
I did exactly that

**Comment by nonetrix** [comment]
Factorio is also effected

**Comment by nonetrix** [comment]
Godot too, I am not sure what is wrong at this point tbh since it seems no one else is having issues

**Comment by nonetrix** [comment]
I have downgraded as much as I can realistically, at this point I am going to assume it is a issue with my configs. But I am extremely confused what could be causing it as I haven't changed anything relating to GPU acceleration

**Comment by huantianad** [comment]
I know there was some recent change to the OpenGL library search path, but no idea if it's related

**Comment by nonetrix** [comment]
I did find this when running glxinfo
```
DRI3 not available
failed to load driver: zink
```

**Comment by jtrees** [comment]
> I figured out the issue, it is Hyprland seemingly. I had to downgrade Hyprland to one commit

I'm also running into this (or something similar). Can you provide more details on your workaround?

**Comment by nonetrix** [comment]
The work around was to upgrade Hyprland instead of manually using a older version, sorry for the confusion this caused. But it was my fault
