### ISSUE TITLE
HAProxy and Lua integration not working quite right

### ISSUE THREAD

**Issue by purefn** [NixOS/nixpkgs#29624]
I'm working on getting HAProxy and Lua working together with a script which adds a Zipkin trace ID. I have a script that another team is using successfully on an Ubuntu system, but I can't seem to get it to work. The problem I'm encountering is that core libraries don't seem to be available. The code it's failing on is the ID generation

```
-- Generate a random number of "bits" bits long                                                                                                                               
function zipkin_gen_random(bits)                                                                                                                                              
  local max_value = math.pow(2,bits) - 1                                                                                                                                      
   return math.random(max_value)                                                                                                                                               
end  

-- Generate a Trace/Span ID                                                                                                                                                   
function zipkin_gen_id()                                                                                                                                                      
  return string.format("%x%x",zipkin_gen_random(32), zipkin_gen_random(32))                                                                                                   
end 
```

The failure is when trying to call `math.pow`

```
haproxy_1  | local0.err: Sep 21 00:54:33 haproxy[20]: Lua function 'zipkin_request': runtime error: /usr/share/haproxy/zipkin.lua:10: attempt to call a nil value (field 'pow').
```

The fact that it gets that far means that the HAProxy Lua API is working. It just seems like core libraries may not be. Is there a path environment variable or something that needs to be added?

**Comment by purefn** [comment]
@joachifm I saw that you added the Lua support for HAProxy. Do you have any idea what the problem might be? Thanks!

**Comment by joachifm** [comment]
@fuzzy-id may know more

**Comment by fuzzy-id** [comment]
I have no clue at all. :/

When it came to LUA I tried to get everything running as far as it seemed to be working. It obviously doesn't.

@purefn `haproxy -vv` states that it is built with LUA, right?

It's probably just some kind of environment variable, as you say. Could you give me a minimal failing example? I will look into it later then.

**Comment by fuzzy-id** [comment]
A thing which just came to my mind: @purefn are you on the current 17.03 channel? As far as i can see it, this version of haproxy does not come with LUA support. (`haproxy -vv` should not mention LUA!)

You can compile your own version of haproxy with the following override:
``` nix
    nixpkgs.config.packageOverrides = pkgs : rec {
      haproxy = pkgs.haproxy.overrideDerivation (oldAttrs : {
        buildInputs = oldAttrs.buildInputs ++ [pkgs.lua5_3];
        preConfigure = oldAttrs.preConfigure + ''makeFlags+=" USE_LUA=yes LUA_LIB=${pkgs.lua5_3}/lib LUA_INC=${pkgs.lua5_3}/include"'';
      });
    }
```

Does this help?

**Comment by fuzzy-id** [comment]
I think this issue can be closed. I'm running haproxy with a lua script without any problems and the op didn't response.

**Comment by purefn** [comment]
@fuzzy-id, sorry. I meant to respond with an example, but other things came up that were a higher priority and this kinda slipped through the cracks. I will try and get a minimal example posted this week.

**Comment by ckauhaus** [comment]
Unable to reproduce the problem on 18.03 or later. I assume that the problem has been fixed in the meantime. This ticket should probably get closed.
