### ISSUE TITLE
wireshark doesn't run from nix-shell

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29638]
## Issue description
After compiling wireshark in a nix-shell, if you try to run the binary, it can't find libwscodec, a wireshark-specific library. 
I solved it in an overlay via:
```
    postBuild = ''
      export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:./run"
      '';
```
but I dunno if it's the correct way to solve it in the derivation ? 

## Technical details
nixos-version=18.03.git.b20fbd0 (Impala)
nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03.git.3ee05700e6"
sandboxing disabled

**Comment by dezgeg** [comment]
You mean running the binary from the build tree without `make install`? That's probably an upstream problem (or rather, works as designed).

**Comment by teto** [comment]
> You mean running the binary from the build tree without make install
Yes. I just run buildPhase then i run the "build/run/wireshark" binary.

I haven't developed in a long time for wireshark but it suddenly came back to me that you have to do
`WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1 ./wireshark`
(see https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcRunFirstTime.html)

It's a bit unpractical and not completely foolproof as it doesn't find other libraries too but it doesn't stop the main binary from running. 
```
/home/teto/wireshark/build/run/extcap/androiddump: error while loading shared libraries: libwiretap.so.0: cannot open shared object file: No such file or directory
/home/teto/wireshark/build/run/extcap/udpdump: error while loading shared libraries: libwsutil.so.0: cannot open shared object file: No such file or directory
/home/teto/wireshark/build/run/extcap/sshdump: error while loading shared libraries: libwsutil.so.0: cannot open shared object file: No such file or directory
/home/teto/wireshark/build/run/extcap/ciscodump: error while loading shared libraries: libwsutil.so.0: cannot open shared object file: No such file or directory
/home/teto/wireshark/build/run/extcap/randpktdump: error while loading shared libraries: libwiretap.so.0: cannot open shared object file: No such file or directory
```
Problem solved. My bad.
