### ISSUE TITLE
Publish Openstack image

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#29631]
We are able to build Openstack images and it basically works well for me: I can use standard Openstack mechanisms to put a ssh key, a configuration.nix file and run a command by using `cloud-init`.

It would be nice to be able to download this image from https://nixos.org/nixos/download.html.

How could I help on this?

**Comment by FRidh** [comment]
I suggest sending a mail to nix-devel@googlegroups.com instead
