### ISSUE TITLE
Lutris: Source login prompts are blank

### ISSUE THREAD

**Issue by GameDungeon** [NixOS/nixpkgs#296496]
### Describe the bug

In Lutris when trying to open a login prompt for a source (e.g. itch.io) it appears blank. It errors as show in the log below.

**Note:** This is unrelated to the `/run/user/1000/at-spi/bus_0: Permission denied` error that is causing a similar issue. That issue can be resolved by running lutris with: `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=mesa lutris` when you need to login to a service.

### Steps To Reproduce
1. Install Lutris
2. Run `lutris -d`
3. Activate a non-steam online source in preferences
4. Attempt to open the login prompt using the box on the left

### Expected behavior
The login prompt should open normally.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/60719255/da21d4b8-dd82-47fd-99e4-adce8deb0e44)

### Additional context
Lutris Logs: 

```
INFO     2024-03-16 15:29:07,338 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-03-16 15:29:07,343 [startup.get_drivers:54]:Using NVIDIA drivers 550.54.14 for x86_64
INFO     2024-03-16 15:29:07,343 [startup.get_drivers:58]:GPU: NVIDIA GeForce GTX 1060 6GB
INFO     2024-03-16 15:29:07,344 [display.display_gpu_info:78]:GPU: 10DE:1B83 19DA:3451 (nvidia drivers)
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DEBUG    2024-03-16 15:29:07,704 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-03-16 15:29:07,811 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-03-16 15:29:10,145 [base.login:424]:Connecting to itch.io
libEGL warning: egl: failed to create dri2 screen
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
Could not determine the accessibility bus address
Failed to create EGL image from DMABufs with file descriptors 54, 55 and 56
```

### Notify maintainers

@Madouura 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240314.d691274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by UlyssesZh** [comment]
This was discussed in the upstream: https://github.com/lutris/lutris/issues/3965
The workaround is setting `WEBKIT_DISABLE_COMPOSITING_MODE=1`.

**Comment by GameDungeon** [comment]
I can confirm that the workaround worked on my system. I'm not sure if anything can be done to address this from the nixpkgs side.

**Comment by UlyssesZh** [comment]
By the way, this issue is a duplicate of #164856.

**Comment by GameDungeon** [comment]
In that case I will close this one. Well at least another result for google to find. Couldn't find the right terms to get the other to pop up.
