### ISSUE TITLE
Can't setup LUKS on BIOS/legacy system

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#29654]
## Issue description
I tried installing NixOS on a LUKS encrypted disk. The installation of grub fails with the error described in #11521. The problem is the device I'm installing grub to is mounted and I don't have a /boot EFI partition.

### Steps to reproduce
1. Boot in BIOS mode
2. Partition the drive like this (GTP):

| Device      | Size  | Type                   |
| :-----------: | -----: | :---------------------|
| /dev/sda1 |    1M | BIOS boot          |
| /dev/sda2 |    4G | Linux swap         |
| /dev/sda3 |  30G | Linux filesystem  |
| /dev/sda4 |    xG | Linux filesystem  |

3. Build NixOS using this options
```
boot.initrd.luks.devices = {
  "swap".device = "/dev/sda2";
  "nixos".device = "/dev/sda3";
  "home".device = "/dev/sda4";
}

boot.loader.grub.device = "/dev/sda";

fileSystem."/" = {
  device = "/dev/mapper/nixos";
  fsType = "ext4";
}

fileSystem."/home" = {
  device = "/dev/mapper/home";
  fsType = "ext4";
}

swapDevices = [ { label = "swap"; } ];
```

## Technical details

* System: 17.03.1853.b7e4857dd9

**Comment by Nimbz** [comment]
Hi @rnhmjoj,

I'm sure you know this by now, but, have you tried adding `boot.loader.grub.enableCryptodisk = true;` to configuration.nix?

**Comment by rnhmjoj** [comment]
Oh, yeah, I had forgotten about this issue.
I've managed to setup everything following the [guide](https://nixos.wiki/wiki/Full_Disk_Encryption)  guide at the nixos.
