### ISSUE TITLE
Update request: lightningcss 1.24.0 → 1.24.1

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#296639]
- Package name: lightningcss
- Latest released version: 1.24.1

- Current version on the unstable channel: 1.22.0
- Current version on the stable/release channel: 1.24.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

myself, @toastal

-----

Note for maintainers: Despite being a minor version bump, an entire dependency chain was added for NAPI which I think has something to do with WASM which fails the `cargo-auditable` test in Nix. See lightningcss’s open bug on their Microsoft GitHub proprietary issue tracker @ https://github.com/parcel-bundler/lightningcss/issues/702 As a non-Rust developer, I have no idea what this error is supposed to mean with its Cargo package management. Hopefully their maintainer will eventually have a look.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project.
I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by JohnRTitor** [comment]
Build error when updating:
```
thread 'main' panicked at cargo-auditable/src/collect_audit_data.rs:77:9:
cargo metadata failure: error: Package `lightningcss-napi v0.1.0 (/build/source/napi)` does not have feature `rayon`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `lightningcss` (bin "lightningcss")
```

**Comment by JohnRTitor** [comment]
https://github.com/parcel-bundler/lightningcss/pull/713 should fix it for further releases. For this particular 1.24.1 release, I added a patch to automatically patch the source, see https://github.com/NixOS/nixpkgs/pull/302174
