### ISSUE TITLE
Duplicate pinentryPackage in Plasma6 and XServer in f471be9 in `nixos-unstable-small`

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#296797]
### Describe the bug
Similar issue as #296390, except now it's with xserver.nix and plasma6.nix. I noticed it was still present on nixos-unstable-small @ https://github.com/NixOS/nixpkgs/commit/f471be9644f3ab2f3cb868de1787ab70a537b0e7. Also I don't have any pinentry defined in my flake
```
       error: The option `programs.gnupg.agent.pinentryPackage' is defined multiple times while it's expected to be unique.

       Definition values:
       - In `/nix/store/xb5p9kg3gy00q7c8s638jf15j6qqj473-source/nixos/modules/services/desktop-managers/plasma6.nix': <derivation pinentry-qt-1.2.1>
       - In `/nix/store/xb5p9kg3gy00q7c8s638jf15j6qqj473-source/nixos/modules/services/x11/xserver.nix': <derivation pinentry-gnome3-1.2.1>
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

### Steps To Reproduce
1. Update to nixos-unstable to f471be9
2. Enable Plasma 6

### Expected behavior
KDE Plasma 6 should compile with no config conflicts

### Notify maintainers
@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05.20240315.2bcf18c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/y2k721a8jamdqxqbilyk6ds6374ljcgr-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
We can probably work around by setting the pinentry for xserver with `mkPriority 1100`

**Comment by SuperSandro2000** [comment]
Please test #296866

**Comment by raboof** [comment]
while it looks like this fixes xserver and plasma6 conflicting, it seems having multiple window managers enabled may still be problematic:

```
       error: The option `programs.gnupg.agent.pinentryPackage' is defined multiple times while it's expected to be unique.

       Definition values:
       - In `/nix/store/952zhqw205fhidfm2v4wdq7b9ym1m6iw-source/nixos/modules/services/x11/desktop-managers/xfce.nix': <derivation pinentry-gtk2-1.2.1>
       - In `/nix/store/952zhqw205fhidfm2v4wdq7b9ym1m6iw-source/nixos/modules/programs/wayland/sway.nix': <derivation pinentry-gnome3-1.2.1>
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

Do you want to fix that as part of this issue or should I create a separate issue?

**Comment by SuperSandro2000** [comment]
> it seems having multiple window managers enabled may still be problematic:

Yeah, you need to manually resolve this.

> Do you want to fix that as part of this issue or should I create a separate issue?

This can't be fixed, as it is impossible to decide which one should be preferred as it is an end user decision.
