### ISSUE TITLE
fcitx5.settings.InputMethod Declarative Configuration not working

### ISSUE THREAD

**Issue by 3699n** [NixOS/nixpkgs#296703]
### Describe the bug
As part of the process of setting up impermanence, I’m trying to have my fcitx5/mozc setup for Japanese/Swiss German input on a Swiss German keyboard declared in my NixOS configuration. When I then build a fresh VM including the configuration below and try to boot into it, I have a broken configuration. Only the mozc input (as the Off Input Method) is listed in the input configuration GUI and available from the taskbar. I am only able to type in Japanese.

Please see this [thread](https://discourse.nixos.org/t/fcitx5-mozc-japanese-declarative-profile-configuration-not-working/41504) for more details and screenshots.

### Additional context
When I try to add an fcitx5 input method for the swiss german keyboard manually after creating the VM, no German keyboards are listed in the Add Input Method screen in the KDE settings. Could this possibly be an issue relating the locales rather than fcitx5? If so, it should probably be documented with the option.

### Notify maintainers

@NickCao 
@linsui 
@Vonfry 

Apologies for any incorrect notifications.

### Metadata
![image](https://github.com/NixOS/nixpkgs/assets/7414843/739987f3-665d-48a8-b7bb-4f2bb467d870)

### Reproduce
Please find the flake used to generate the VM which exhibits this behavior [here](https://codeberg.org/nickvk/nix-config/commit/39e5f120fa4fed9adb1566c2b02c06c5271a8601).

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Vonfry** [comment]
The nixos fcitx5 setting module is only create an ini file from nix attrset simply. If your configuration doesn't take effect, the only reason is that some are wrong to read by fcitx5.

I have took a glance of the threads. And I suggest you to show `/run/current-system/sw/etc/xdg/fcitx5/{config,profile}` as well. You should also check the kde environment (not your terminal) variable `XDG_CONFIG_DIRS` whether contains that path.

By the way, there is no documentation about that configuration file in fcitx5. It is suggested to generate that file by `fcitx5-configtool`. You can compare the one nix generated and the one fcitx5 generated.

**Comment by 3699n** [comment]
Thank you for your quick and extensive answer @Vonfry . I just tried to locate the files in the fresh VM but it seems like the folder `/run/current-system/sw/etc/xdg/fcitx5/` doesn't exist.

![image](https://github.com/NixOS/nixpkgs/assets/7414843/b879f2b8-67b1-4f54-a595-7173cd2f9d36)

The VM has the following value for `XDG_CONFIG_DIRS`:
![image](https://github.com/NixOS/nixpkgs/assets/7414843/4163832e-789d-41ac-bc96-fdf741f1ae3c)
 

In regards to the configuration file, I initially generated the config file using `fcitx5-configtool` and then turned it into a nix expression. 

**My intuition is that this has something to do with language packs, rather than fcitx. When I try to add a Swiss German layout as an Off input method to fcitx, it doesn't let me. Only english keyboard layouts are listed as an option. Do you know what might cause this?**

**Comment by Vonfry** [comment]
> I just tried to locate the files in the fresh VM but it seems like the folder /run/current-system/sw/etc/xdg/fcitx5/ doesn't exist.

How about `/etc/xdg/fcitx5/`? According to the module file, it should be `/run/current-system/sw/etc/xdg/fcitx5/` with `config.environment.etc`, IMO. If none of them exists, your config isn't generated by the module. I think you have to check you configuration to find the reason.

> Only english keyboard layouts are listed as an option. Do you know what might cause this?

The GUI tool use your `LANG` to filter the list by default. I think it affect the GUI tool only not config file.

**Comment by 3699n** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/7414843/cda50d05-d69e-4987-9eb9-dbfdd3875d1b)

That folder also doesn't exist. 

This is odd, since the configuration seems to be applying at least partially, since fcitx has mozc added as an input method and the name of the input group is the same as the one I gave it in my nix config.

**Comment by linsui** [comment]
The config file is generated in /etc/xdg/fcitx5/ and it should match what you get in ~/.config/fcitx5/ when you config fcitx5 with gui. Your config looks correct and I have a similiar config.

**Comment by 3699n** [comment]
I managed to find the generated config at `/etc/xdg/fcitx5/profile`:

![image](https://github.com/NixOS/nixpkgs/assets/7414843/d3c309a2-811f-43c3-90c5-acbca79e73a1)

@linsui The config seems correct time me. Do you have any idea what might be causing the issue?

**Comment by linsui** [comment]
The Layout=null is weird. Maybe you should leave it empty. I mean, you don't need to add that.

**Comment by linsui** [comment]
Feel free to add an example. I myself just generate the config files with gui then convert them to nix manually.

**Comment by Vonfry** [comment]
It seems that this issue has been resolved. Close.

**Comment by h7x4** [comment]
Oh how the tables have turned. I just found this issue while trying to fix my own fcitx config today. It has been broken for so long. I suppose I were the person to make this typo originally, and it accidentally got copied over. So sorry about the confusion, and thanks for creating a thread on it, I'll fix my own config ASAP :)
