### ISSUE TITLE
Update request: syncthing 1.27.2 → 1.27.4

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#296776]
- Package name: syncthing
- Latest released version: 1.27.4

- Current version on the unstable channel: 1.27.2
- Current version on the stable/release channel: 1.26.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jokogr  
@peterhoeg
@andrew-d

https://github.com/syncthing/syncthing/releases/tag/v1.27.3
https://github.com/syncthing/syncthing/releases/tag/v1.27.4

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by antonmosich** [comment]
#293427 already updated syncthing, the PR was merged yesterday

**Comment by luzpaz** [comment]
Apologies. Not sure why I didn't see it in the PRs (maybe because I searched open tickets first and then clicked PRs?)
