### ISSUE TITLE
OracleJDK8distro defaults to 141 instead of 144 / Packaging of OracleJDK9distro

### ISSUE THREAD

**Issue by Sophia-Gold** [NixOS/nixpkgs#29675]
My NixOS builds are breaking due to the OracleJDK8 version being set to 141 rather than the current 144 I've downloaded and added to my Nix store. I see the package version in this repo is currently marked 144, so suspect this could be because I'm still on Nix 1.11.9 (my general issues upgrading are documented in a much more involved issue here: https://github.com/NixOS/nixpkgs/issues/29290).

Additionally, I can't find an issue about packaging OracleJDK9. If no one more experienced is available to handle this, I'd be happy to submit a PR myself (although can't promise I'll get it right the first time :woman_shrugging:).

* System: NixOS 17.03
* Nix version: 1.11.9
* Nixpkgs version: 17.03.1853.b7e4857dd9
* Sandboxing enabled: false

**Comment by vyp** [comment]
You can get the nixpkgs version by running the command it said in the issue template, i.e. `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`. (Unless of course you mean you're not asking a question and that command just outputted `?`.)

For oraclejdk8 144 in NixOS 17.03, try putting the contents of the following comment's code block in your `configuration.nix`: https://github.com/NixOS/nixpkgs/issues/28632#issuecomment-325849172. (Of course, without the first `{` line and last `}` line.) I haven't tested that all however!

**Comment by Sophia-Gold** [comment]
That gives me `error: undefined variable 'stdenv'`. I'm not sure if it's because I have two instances of `packageOverrides`, the other being for `haskellPackages`, but that seems okay to do.

**Comment by vyp** [comment]
Oh right, the top of your `configuration.nix` should have something like `{ config, pkgs, ... }:`, try putting `stdenv` there: `{ stdenv, config, pkgs, ... }:`.

**Comment by Sophia-Gold** [comment]
Now I get `error: undefined variable ‘requireFile’` :confused:

**Comment by vyp** [comment]
Woops! `{ stdenv, requireFile, config, pkgs, ... }:`

I think that should be all haha!

**Comment by Sophia-Gold** [comment]
Okay, _now_ it's complaining about having two package overrides. I've always been unsure how to add things there since I currently have `packageOverrides = super: let self = super.pkgs; in { ... };`. I assume I would need to modify the snippet you linked to before throwing it in there?

**Comment by vyp** [comment]
Oh right I forgot I could just see your configuration.nix at https://github.com/Sophia-Gold/configuration.nix/blob/master/configuration.nix, so just put the `oraclejdk8 = let` part (so up to the `});` line) after [line 71](https://github.com/Sophia-Gold/configuration.nix/blob/5e724805fdd76c21b994806adcec68dabf8a99c9/configuration.nix#L71).

Do you see how that works now? Like, your `nixpkgs.config.packageOverrides` should now have a `myHaskellEnv` attribute, and a `oraclejdk8` attribute.

**Comment by Sophia-Gold** [comment]
Right, my question was essentially just whether that was okay. It's worth pointing out that no one ever really learns the Nix language, which most of the time is fine, but every once in a while I get thrown by a line like `super: let self = super.pkgs`. And this especially makes it difficult for me to contribute without handholding after I break tests, for example submitting a PR for OracleJDK9...

Anyway, I regret to say `nixos-rebuild switch` still throws the same error. I've tried both `nix-store` and `nix-prefetch-url` with the manually downloaded 144, but it still wants 141.

**Comment by vyp** [comment]
Same, I don't like the nix language, it took me a few years to get my head around it to be able start packaging things myself, even though it seemed really simple at first glance. Even now I wouldn't say I know the language that well. I'm not sure if that's the language itself or something like the lack of documentation though, I think probably latter.

What's the error message?

**Comment by Sophia-Gold** [comment]
I think the latter as well. Maybe I will take a crack at OracleJDK9 this weekend...I feel like writing/updating packages helps build my paltry DevOps skills.

The build looks exactly the same as before I added that `packageOverride`. It prompts me to download 141 then fails because 141 couldn't be built.

**Comment by vyp** [comment]
Stupid question, but `nixos-rebuild` is run as root right?

**Comment by Sophia-Gold** [comment]
Yes. I'm not sure it would work at all otherwise. To be clear, the file name should change to 144 after that override right? Regardless, I get the prompt to download 141 even though I've added 144 to the Nix store. Then it fails when trying to produce an output path for 141 (apparently building it using clang?).

**Comment by vyp** [comment]
> the file name should change to 144 after that override right?

Yes I believe so.

> apparently building it using clang?

🤷

**Comment by vyp** [comment]
https://github.com/NixOS/nixpkgs/pull/29693

**Comment by Sophia-Gold** [comment]
I think I still need to deal with this issue, though, because Java 9 modules may break some things in Clojure.

**Comment by Sophia-Gold** [comment]
To be clear, what should I actually have in `systemPackages` to correspond to that override? Before I had `(oraclejdk8distro true true)`. It would seem I'd now want just `oraclejdk8`, but that leads to infinite recursion.

**Comment by vyp** [comment]
Ohh okay in that case maybe try replacing `oraclejdk8` with `oraclejdk8distro`? So `let oraclejdk8distro = ...    in pkgs.oraclejdk8distro.overrideAttrs` and keep `(oraclejdk8distro true true)` in `environment.systemPackages`.

I'm not 100% sure if that would work but to me it seems like it could.. :/

**Comment by Sophia-Gold** [comment]
That just brings me back to the infinite recursion error. I'm very confused by that one :confused:

**Comment by vyp** [comment]
Oh wow okay. :question: :question:

How about remove `oraclejdk8distro` from `nixpkgs.config.packageOverrides` entirely and just putting it under `environment.systemPackages`?

So possibly something like:

``` nix
{
  environment.systemPackages = with pkgs;
    [ 
      (oraclejdk8distro true true).overrideAttrs (oldAttrs: {
        abortArch = abort "jdk requires i686-linux, x86_64-linux, or armv7l-linux";
        productVersion = "8";
        patchVersion = "144";
        downloadUrl = http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html;
        sha256_i686 = "1i5pginc65xl5vxzwid21ykakmfkqn59v3g01vpr94v28w30jk32";
        sha256_x86_64 = "1r5axvr8dg2qmr4zjanj73sk9x50m7p0w3vddz8c6ckgav7438z8";
        sha256_armv7l = "10r3nyssx8piyjaspravwgj2bnq4537041pn0lz4fk5b3473kgfb";
        jceName = "jce_policy-8.zip";
        jceDownloadUrl = http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html;
        sha256JCE = "0n8b6b8qmwb14lllk2lk1q1ahd3za9fnjigz5xn65mpg48whl0pk";

        name = "oraclejdk-${productVersion}u${patchVersion}";
        src =
          if stdenv.system == "i686-linux" then
            requireFile {
              name = "jdk-${productVersion}u${patchVersion}-linux-i586.tar.gz";
              url = downloadUrl;
              sha256 = sha256_i686;
            }
          else if stdenv.system == "x86_64-linux" then
            requireFile {
              name = "jdk-${productVersion}u${patchVersion}-linux-x64.tar.gz";
              url = downloadUrl;
              sha256 = sha256_x86_64;
            }
          else if stdenv.system == "armv7l-linux" then
            requireFile {
              name = "jdk-${productVersion}u${patchVersion}-linux-arm32-vfp-hflt.tar.gz";
              url = downloadUrl;
              sha256 = sha256_armv7l;
            }
          else
            abortArch;
      })
    ];
 }
```

**Comment by Sophia-Gold** [comment]
Um...`error: cannot coerce a function to a string`? Also, is it possible the reason that snippet is throwing an error when placed inside packageOverides due to the `super: let self = super.pkgs` statement?

**Comment by vyp** [comment]
This is frustrating. What line is that error referring to?

Because I might not be knowledgeable enough with nix lang here, @vcunat do you see anything wrong in the code in my previous comment here?

> Also, is it possible the reason that snippet is throwing an error when placed inside packageOverides due to the `super: let self = super.pkgs` statement?

That could be it, but I'm not sure how to work around that unfortunately. :confused: I forgot what it does, do you know why that's needed for `myHaskellEnv`?

**Comment by Sophia-Gold** [comment]
`error: cannot coerce a function to a string, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/strings.nix:442:44`

I assume `super: let self = super.pkgs` binds `self` to `environment.systemPackages` so I can define a Haskell environment. I'm not sure if I can omit the `self` in `self.haskellPackages` considering I'm installing them globally rather than in a directory with a `default.nix`? Otherwise I don't know how to add other packageOverrides without that binding since it throws an error if I add more than one instance of it.

**Comment by vyp** [comment]
> `error: cannot coerce a function to a string, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/strings.nix:442:44`

As in, does the trace point to a line in `configuration.nix`?

> I'm not sure if I can omit the `self` in `self.haskellPackages` considering I'm installing them globally rather than in a directory with a `default.nix`?

Try it.

> Otherwise I don't know how to add other packageOverrides without that binding since it throws an error if I add more than one instance of it.

Yeah you can't.

**Comment by Sophia-Gold** [comment]
I deleted that weird let binding, which _appears_ to work although I won't know until it actually finishes a build, and moved your snippet back to packageOverrides. I'm now getting an error right after the let bindings in that snippet on the line `in pkgs.oraclejdk8.overrideAttrs (oldAttrs: {` that says `value is a function while a set was expected`. Does that make any sense to you or would a trace help?

**Comment by vyp** [comment]
Oh okay.. I'm really not sure. I guess seeing as though we don't reference `oldAttrs` at all, we can just try removing that part? So also remove the parentheses around it too. ..But that doesn't seem right even if it does work.. :confused:

Sorry to be annoying, but could you post an updated version of what your configuration.nix is somewhere now (remember to redact anything private though)? Just so we're on the same page. :raised_hands: And trace will probably help yes.

**Comment by Sophia-Gold** [comment]
No problem. 

Here's my current configuraton.nix: https://github.com/Sophia-Gold/configuration.nix/blob/master/configuration.nix. 

And here's the trace with that weird error at the end: https://gist.github.com/Sophia-Gold/4d7eb6de9e2961616b76615507aee835.

**Comment by Sophia-Gold** [comment]
Closing this as I upgraded to 17.09 (not that I don't have a whole host of new issues, but it seems to have resolved this one). Thanks, @vyp!

**Comment by vyp** [comment]
Oh I thought I had responded, but I did have a look at that configuration and the trace but I couldn't figure out why it wasn't working. Glad something eventually went right though!

**Comment by Sophia-Gold** [comment]
Eh, sort of. `java --version` says it can't build the JVM, but nothing to do with what this issue is about. Pretty sure I just need to boot into my current build rather than one from five months ago, which seems like I may never be able to do on this machine. Thanks for the help, though!
