### ISSUE TITLE
Suggested nox-review invocation in the PR template doesn't work

### ISSUE THREAD

**Issue by eqyiel** [NixOS/nixpkgs#29684]
## Issue description

```
eqyiel@ayanami ~/git/personal/deployments/nixpkgs (git)-[networkmanager_openvpn-1.8.0] % nix-shell -p nox --run "nox-review wip"
Usage: nox-review [OPTIONS] COMMAND [ARGS]...

Error: No such command "wip".
```

### Steps to reproduce

Run that command

Probably related to this: https://github.com/NixOS/nixpkgs/issues/26392

## Technical details

* System: 18.03.git.3c2731e865 (Impala)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: 18.03pre-git
* Sandboxing enabled: false

**Comment by primeos** [comment]
@madjar could that be caused by the last upgrade (#29477)?

Seems like `wip` changed to `_` for some reason:
```bash
[nix-shell]$ nox-review --help
Usage: nox-review [OPTIONS] COMMAND [ARGS]...

  Review a change by building the touched commits

Options:
  -k, --keep-going  Keep going in case of failed builds
  --dry-run         Don't actually build packages, just print the commands
                    that would have been run
  --help            Show this message and exit.

Commands:
  _   difference between working tree and a commit
  pr  changes in a pull request

```

**Comment by primeos** [comment]
Had a quick look at the code 5f0a7cded718d0092229ba078cb7f0f7733bf636 should fix it for now. But I don't know why the behaviour suddenly changed, might be a bug in `click`.

From the [documentation](http://click.pocoo.org/6/api/):
```
click.command(name=None, cls=None, **attrs)
[...]
The name of the command defaults to the name of the function. If you want to change that, you can pass the intended name as the first argument.
```

And the function is named `wip`.

**Comment by eqyiel** [comment]
@primeos, thanks, it seems like it's working as advertised now!
