### ISSUE TITLE
[solved] Unable to mount partition with specific UID since 6.8

### ISSUE THREAD

**Issue by Djabx** [NixOS/nixpkgs#296851]
### Describe the bug
I'm unable to mount btrfs partition with a specific UID.

### Steps To Reproduce
1. configure a subvolume with a uid:
```
 fileSystems."/home/alex/.cache" = {
    options = [
      "noatime"
      "autodefrag"
      "uid=1000"
    ];
  };
```
2. `nixos-rebuild boot --upgrade`
3. `reboot`
4. does not work

### Expected behavior
Was working properly the 07/03; did not change anything in my system configuration; just try to build/update.

### Additional context
All file / outputs are here: https://gist.github.com/Djabx/ef86c7b565559e2fa9a71b730d109a09

I've commented all volumes with an UID and I can boot properly.
But I need thoses volumes.

### Notify maintainers

@viric 
@K900 

### Metadata

My last working version:
```
# cat /nix/var/nix/profiles/system/nixos-version
23.11.5097.880992dcc006
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
Does it work without the UID setting?

**Comment by Djabx** [comment]
> Does it work without the UID setting?

Yes it does. That what is strange for me.

Note: My BTRFS Partitions are on a LUKS partitions; but it work properly in 6.7*

**Comment by ElvishJerricco** [comment]
I'm on linux 6.7 and passing the `uid=1000` option to a btrfs mount command gives me

```
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

That option isn't supported by btrfs and I'm surprised you didn't get this error before. The error you're getting now is expected behavior.

**Comment by Djabx** [comment]
> That option isn't supported by btrfs and I'm surprised you didn't get this error before. The error you're getting now is expected behavior.

Damn you're right ! 
Thank you very much.
