### ISSUE TITLE
Package request: Proton Mail Desktop App

### ISSUE THREAD

**Issue by DuncanTDP** [NixOS/nixpkgs#296965]
**Project description**

This is an Desktop app to view and send mail via proton mail. Unlike Proton mail bridge this application is a standalone client, requiring no other apps (ie. Thunderbird) to view emails/

**Metadata**

* homepage URL: https://proton.me/mail/download, https://proton.me/support/mail-desktop-app
* source URL: https://github.com/ProtonMail/inbox-desktop
* license: GPL 3.0
* platforms: Linux, Windows, Mac

**Comment by donovanglover** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/296107
