### ISSUE TITLE
Spotify Permission denied error

### ISSUE THREAD

**Issue by Amatrelan** [NixOS/nixpkgs#296942]
### Describe the bug
When I try to launch `Spotify` form `nixpkgs-unstable` there is `Permission denied [system:13]: "/usr/share/icons/hicolor/1024x1024/apps/spotify-client.png"`

### Steps To Reproduce
1. Install spotify through configuration
2. start
3. Core dump

### Expected behavior
When I launch spotify I expect it to launch

### Additional context
When starting from terminal it prints some pointers for problem
```/run/current-system/sw/bin/spotify: /nix/store/78avj53r2gfxdp141kj7cymbzsdnsjpl-curl-8.6.0/lib/libcurl-gnutls.so.4: no version information available (required by /run/current-system/sw/bin/spotify)
/nix/store/yzbh0fbhy957whanxw0bd49y7dfv7v1c-spotify-1.2.31.1205.g4d59ad7c/share/spotify/.spotify-wrapped: /nix/store/78avj53r2gfxdp141kj7cymbzsdnsjpl-curl-8.6.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/yzbh0fbhy957whanxw0bd49y7dfv7v1c-spotify-1.2.31.1205.g4d59ad7c/share/spotify/.spotify-wrapped)
/nix/store/yzbh0fbhy957whanxw0bd49y7dfv7v1c-spotify-1.2.31.1205.g4d59ad7c/share/spotify/.spotify-wrapped: /nix/store/78avj53r2gfxdp141kj7cymbzsdnsjpl-curl-8.6.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/yzbh0fbhy957whanxw0bd49y7dfv7v1c-spotify-1.2.31.1205.g4d59ad7c/share/spotify/.spotify-wrapped)
libc++abi: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: Permission denied [system:13]: "/usr/share/icons/hicolor/1024x1024/apps/spotify-client.png"
```

It tries to open icon with resolution `1024x1024` but it seems to be so that it's not copied over 
https://github.com/NixOS/nixpkgs/blob/c75037bbf9093a2acb617804ee46320d6d1fea5a/pkgs/applications/audio/spotify/linux.nix#L168

So might be simple as putting `1024` for that list and it's solved.

### Notify maintainers
@eelco @ftrvxmtrx @sheenobu @timokau @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Amatrelan** [comment]
Not sure what fixed this for me, might be same as was with `Hyprland` that `/usr/share` rights was so that only root could touch that folder, so made it to `777` (bad idea) but now works on me.

**Comment by Ma27** [comment]
You shouldn't even have a `/usr/share` on NixOS. Or is this a non-NixOS issue?

**Comment by Amatrelan** [comment]
No it's not, I didn't have it but `Hyprland` crashed when it wasn't there and that's why I created it https://github.com/NixOS/nixpkgs/issues/301892 here is about that issue

**Comment by Amatrelan** [comment]
Ok might be that I had created that folder it broke something in this, now that Hyprland issue is fixed decided to try remove folder and both Hyprland and Spotify works just fine.

So now closing this issue that solution seems to be that removing that folder makes it to work.
