### ISSUE TITLE
System Shock 2 on Steam doesn't run

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#29709]
## Issue description

System Shock 2 doesn't run. It is packaged in a Wine wrapper. The reason is `libGL.so.1` doesn't have `xcb_unregister_for_special_event`. Perhaps it's time to update Steam runtime that NixOS uses.

### Steps to reproduce

1. Install and run System Shock 2 on Steam.
```
$ tail /tmp/dumps/_stdout.txt
>>> Adding process 31293 for game ID 238210
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 31382 for game ID 238210
>>> Adding process 31471 for game ID 238210
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
/home/chronos/.local/share/Steam/steamapps/common/SS2/bin/wineloader: symbol lookup error: /run/opengl-driver-32/lib/libGL.so.1: undefined symbol: xcb_unregister_for_special_event
>>> Adding process 31490 for game ID 238210
Game removed: AppID 238210 "System Shock 2", ProcID 31164 
No cached sticky mapping in ActivateActionSet.
```

## Technical details

* System: 18.03pre116054.a75265924f (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre116054.a75265924f"
* Sandboxing enabled: false

**Comment by FRidh** [comment]
cc @abbradar

**Comment by vcunat** [comment]
That symbol used by libGL is from libxcb.  I might be missing something as I haven't looked into it properly, but possibly:
```diff
diff --git a/pkgs/games/steam/chrootenv.nix b/pkgs/games/steam/chrootenv.nix
index 0c59821bdd2..c1892762edd 100644
--- a/pkgs/games/steam/chrootenv.nix
+++ b/pkgs/games/steam/chrootenv.nix
@@ -53,6 +53,7 @@ in buildFHSUserEnv rec {
     xlibs.libXext
     xlibs.libX11
     xlibs.libXfixes
+    xlibs.libxcb
 
     # Not formally in runtime but needed by some games
     gst_all_1.gstreamer
```

The strangest thing to me is why libGL in steam seems working for others....

**Comment by abbradar** [comment]
Hm, maybe the game has its own `libxcb` or something. I don't own the game so I sadly can't check but as @vcunat said other games most likely use `libxcb` too and they work. There is `libxcb` in Steam Runtime -- I'll check dependency graph of random games and see how it looks, now that I finally passed most deadlines and have time for NixOS :D

**Comment by vcunat** [comment]
Hmm, right, `*-steam-fhs/usr/lib32/steam-runtime/usr/lib/i386-linux-gnu/libxcb.so` also contains the symbol.  I actually don't know how library lookups work in these chroot-envs; that might be the issue here.

**Comment by yegortimoshenko** [comment]
Oh, the game indeed does come with its own `libxcb.so.1.1.0`. Do I understand correctly that this problem is then not NixOS-specific? I'll file a bug report with System Shock 2 developers.

**Comment by abbradar** [comment]
@yegortimoshenko Can you try removing it, just in case? It may work.

**Comment by yegortimoshenko** [comment]
@abbradar Removing it fixed the problem. Thanks! Strange that they would include it with the game, though.

**Comment by abbradar** [comment]
Good to know! I can only guess they have a custom patch for the library. Try reporting it...
