### ISSUE TITLE
patchShebangs doesn't patch hidden files

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#297044]
### Describe the bug
patchShebangs doesn't patch files whose name starts with `.`

this can cause problems when used with `wrapProgram`

### Steps To Reproduce
1. save the following as `bug.nix`
```nix
let pkgs = import <nixpkgs> {};
in pkgs.stdenv.mkDerivation (finalAttrs: {
  name = "patch-test";
  dontUnpack = true;
  nativeBuildInputs = with pkgs; [ lua makeWrapper ];
  postInstall = ''
    mkdir -p $out/bin
    echo '#!/usr/bin/env lua' >> $out/bin/test.lua
    echo 'print "lua script run"' >> $out/bin/test.lua 
    chmod +x $out/bin/test.lua
    wrapProgram $out/bin/test.lua \
      --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.lua ]}
  '';
  passthru.tests.simple = pkgs.runCommandLocal "patch-test-run" { } ''
    ${finalAttrs.finalPackage}/bin/test.lua > $out
  '';
})
```
3. run `nix-build bug.nix -A passthru.tests`
4. error: `/nix/store/ck9b625q4f59as4ribdf3wb56yyqsf05-patch-test/bin/test.lua: line 8: /nix/store/ck9b625q4f59as4ribdf3wb56yyqsf05-patch-test/bin/.test.lua-wrapped: cannot execute: required file not found`

### Expected behavior
the command should be run successfully.

### Additional context
it doesn't have to be lua or use `env`, it just has to be a shebang that references any interpreter not in stdenv.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.4315.c68a9fc85c2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(binarycat): `"stable-23.05, unstable"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/binarycat/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> patchShebangs doesn't patch files whose name starts with `.`

Do you mean files that contain a . because in your example the file does not start with a dot.

**Comment by lolbinarycat** [comment]
@SuperSandro2000 `wrapProgram` moves its input to `.${filename}-unwrapped`.

the wrapper script gets patched, but the original program doesn't.

**Comment by SuperSandro2000** [comment]
I just tested this myself and the problem is that lua is not in buildInputs, nothing related to patchShebangs.
