### ISSUE TITLE
Build failure: ollama when specifying acceleration as rocm

### ISSUE THREAD

**Issue by AxiteYT** [NixOS/nixpkgs#297081]
### Steps To Reproduce

1. Set services.ollama.acceleration = "rocm";
**OR**
2. Set acceleration = "rocm" via override

### Build log

```
[buildErrorOllama.log](https://github.com/NixOS/nixpkgs/files/14644421/buildErrorOllama.log)

```

### Notify maintainers
@abysssol
@dit7ya 
@elohmeier

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`

```console
[user@system:~]$ sudo nixos-rebuild switch --flake .

/nix/store/4cw0pwflq2fmb9hpm140ddywn7aiy949-rocm-comgr-5.7.1/lib/libamd_comgr.so.2
/nix/store/637pjyhpg2lyw57pzx7d5jr01f5bxmid-rocm-runtime-5.7.1/lib/libhsa-runtime64.so.1
/nix/store/pda887ll2x0fv5hsshq993lz35qibyjm-libdrm-2.4.120/lib/libdrm_amdgpu.so.1
/nix/store/qgw460dph1xrmjmlcn3j0i4fczabjp9c-rocm-llvm-libunwind-5.7.1/lib/libunwind.so.1
+ echo 'ERROR: deps file short'
ERROR: deps file short
+ exit 1
llm/generate/generate_linux.go:3: running "bash": exit status 1
/nix/store/v099hqvw5z87423p4hz1vfhzaqa07dii-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hamsolo42** [comment]
I think ollama needs rocm 6.0

**Comment by AxiteYT** [comment]
> I think ollama needs rocm 6.0 :-(, referencing this comment in the pull request #296309

Ahhh I see, good pickup :)

**Comment by abysssol** [comment]
To be clear, that was simply my guess influenced by a vague error message mentioning rocm 6. I'm now more inclined to believe that the changes to ollama's build script prevented it from properly detecting rocm libraries on nix, though I have very little information to go on at the moment.

I'll try to figure this out, but it will take some time, and I may not find a solution at all. Unfortunately, you'll have to disable gpu support for now (or use an older version of nixpkgs).

**Comment by ulrikstrid** [comment]
Trying to build `Ollama` on #287846 gets us further and boils down to:
```
/build/source/llm/llama.cpp/ggml-cuda.cu:1084:28: error: no matching function for call to 'sinf'
    embed_data[j + half] = sinf(arg);
```
If someone (@abysssol maybe?) can figure out how we can remove the cuda stuff that would be awesome.

**Comment by abysssol** [comment]
I don't understand what "removing the cuda stuff" means, or would entail. It seems to me that the error is due to missing libraries that aren't detected (due to ollama's recent update). Isn't the point of rocm to provide those same math functions (like `sinf`) but implemented on amd graphics hardware?
I feel like I'm missing something important here. Could you add some more detail, or direct me somewhere where I could find relevant information? Thank you.

**Comment by ulrikstrid** [comment]
You are correct @abysssol, and your comment made me figure out what's wrong. I opened a PR #297447 to add the missing libraries from the path

**Comment by abysssol** [comment]
Thanks to @ulrikstrid, #298077 fixed this issue. It will likely take 5-10 days for these changes to make it into nixpkgs-unstable/nixos-unstable.
