### ISSUE TITLE
Package request: hyprlandPlugins.hyprtrails

### ISSUE THREAD

**Issue by julius-boettger** [NixOS/nixpkgs#297198]
**Project description**

Hyprland Plugin to add smooth trails behind moving windows.

**Metadata**

* homepage / source URL: https://github.com/hyprwm/hyprland-plugins
* license: BSD 3-Clause License
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/321575
