### ISSUE TITLE
BUG: universal-android-debloater gui does not display any font

### ISSUE THREAD

**Issue by leon-erd** [NixOS/nixpkgs#297161]
### Describe the bug
For me the gui does not display any fonts and is therefore unusable. Happened after update from 0.6.2 → 1.0.2.

### Steps To Reproduce
1. run `nix shell github:nixos/nixpkgs/nixos-unstable#universal-android-debloater`
2. run `uad-ng`

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/99900077/707b60f2-e430-4eb0-9ac2-a445703974c1)

### Additional context
I'm running Hyprland. I also tested on a friends PC (also Hyprland) and got the same result there.

### Notify maintainers
@KamilaBorowska 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by leon-erd** [comment]
After update to `1.0.3` the program does not launch anymore for me.
```bash
➜  ~ RUST_BACKTRACE=full uad-ng
thread 'main' panicked at /build/universal-android-debloater-1.0.3-vendor.tar.gz/iced_winit/src/application.rs:119:10:
Create event loop: Os(OsError { line: 80, file: "/build/universal-android-debloater-1.0.3-vendor.tar.gz/winit/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
stack backtrace:
   0:     0x56091f2f9df5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc7227e0e319a0b38
   1:     0x56091ef8a8f0 - core::fmt::write::hab7a2cb9fb1eea10
   2:     0x56091f2d814e - std::io::Write::write_fmt::h5d9ea37d99fc8ea3
   3:     0x56091f2fa73e - std::sys_common::backtrace::print::h7ef6b9088506adf3
   4:     0x56091f2fa43a - std::panicking::default_hook::{{closure}}::h2be91e085f955e55
   5:     0x56091f2fb2d1 - std::panicking::rust_panic_with_hook::hcb0f9a863644f6c2
   6:     0x56091f2fad60 - std::panicking::begin_panic_handler::{{closure}}::hb3736c891f535df7
   7:     0x56091f2facb6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5c867a2182e2e40a
   8:     0x56091f2facaf - rust_begin_unwind
   9:     0x56091ef87394 - core::panicking::panic_fmt::h71234a7826c31033
  10:     0x56091ef91ad2 - core::result::unwrap_failed::h2624e52cdacd8e70
  11:     0x56091f3eed00 - iced_winit::application::run::h78660dfdb78f66fc
  12:     0x56091f48fe6a - uad_ng::main::h6810afafe01741b9
  13:     0x56091ef2e4ad - std::sys_common::backtrace::__rust_begin_short_backtrace::hae8a726e089e2839
  14:     0x56091f48f0c3 - main
  15:     0x7f946da6910e - __libc_start_call_main
  16:     0x7f946da691c9 - __libc_start_main@@GLIBC_2.34
  17:     0x56091ef26ca5 - _start
  18:                0x0 - <unknown>
```

@KamilaBorowska

**Comment by 0xAnarora** [comment]
I have this issue too, i see no text, at all

**Comment by 0xAnarora** [comment]
ran `nix shell "github:nixos/nixpkgs/nixos-unstable#universal-android-debloater"`
which seems to get it working

**Comment by leon-erd** [comment]
I can confirm that it works now! I think its fixed by https://github.com/NixOS/nixpkgs/pull/307466 :)
Will close this now. If there are any other problems I think its better to open a new issue.
