### ISSUE TITLE
Package request: lua*Packages.mimetypes

### ISSUE THREAD

**Issue by wenjinnn** [NixOS/nixpkgs#297143]
**Project description**

This is a simple library for guessing a file's MIME type. It includes a (hopefully) comprehensive database of MIME types, but it allows you to create your own should you have specific requirements. It can guess types both by extension and by the complete filename.

used by https://github.com/rest-nvim/rest.nvim

**Metadata**

* homepage URL:https://luarocks.org/modules/lunarmodules/mimetypes
* source URL:https://github.com/lunarmodules/lua-mimetypes
* license: mit
* platforms: linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
I am responsible for the move to lunarmodules of this outdated package. I had to package it for the luarocks-site so and it worked fine. Anyhow we want the latest rest.nvim in nixpkgs. Interested in contributing with some guidance ?

**Comment by wenjinnn** [comment]
Sure! I have some free time after work. how can I help?

**Comment by teto** [comment]
for instance you can review https://github.com/NixOS/nixpkgs/pull/297258 see if that helps. 
You can `nix-shell -p luarocks-nix` then call `luarocks nix rest.nvim` to regenerate the rest.nvim rockspec, put it in pkgs/development/lua-modules/generated-packages.nix and check if it builds / what is missing.

**Comment by teto** [comment]
as for rest-nvim not tested yet as it might be missing the httpResult grammar https://github.com/NixOS/nixpkgs/pull/297505
