### ISSUE TITLE
plasma-browser-integration does not work in chrome or firefox

### ISSUE THREAD

**Issue by Easedge** [NixOS/nixpkgs#297230]
### Describe the bug
plasma-browser-integration does not work in chrome or firefox

### Steps To Reproduce
1. set
```nix
    programs.chromium.enablePlasmaBrowserIntegration = true;
    programs.chromium.plasmaBrowserIntegrationPackage = pkgs.kdePackages.plasma-browser-integration;
```
3. plasma5 and plasma6 wayland session
4. browser intergration say it can not connect the host "No such native application org.kde.plasma.browser_intergraion"

### Expected behavior
it should work fine

### Screenshots
![图片](https://github.com/NixOS/nixpkgs/assets/9009588/60b6679f-7aba-4560-8e26-9328ec503504)

content in this picture said above

### Notify maintainers
@K900 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Make sure you use `programs.chromium.enable` or `programs.firefox.enable`, not just adding the package to `environment.systemPackages.`

**Comment by Easedge** [comment]
> Make sure you use `programs.chromium.enable` or `programs.firefox.enable`, not just adding the package to `environment.systemPackages.`

Damn, that seems to be the problem. Can chrome use chromium's settings options?

**Comment by Easedge** [comment]
> Make sure you use `programs.chromium.enable` or `programs.firefox.enable`, not just adding the package to `environment.systemPackages.`

This problem seems to be solved. You can close this issue.

**Comment by K900** [comment]
> > Make sure you use `programs.chromium.enable` or `programs.firefox.enable`, not just adding the package to `environment.systemPackages.`
> 
> Damn, that seems to be the problem. Can chrome use chromium's settings options?

I believe if you set `programs.chromium.package`, yes.
