### ISSUE TITLE
Build failure: jdupes

### ISSUE THREAD

**Issue by leonschoorl** [NixOS/nixpkgs#297213]
### Steps To Reproduce

1. build jdupes on nixos-23.11

### Build log

```
       > trying https://github.com/jbruchon/jdupes/commit/517b7035945eacd82323392b13bc17b044bcc89d.patch
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download darwin-apfs-comp.patch from any mirror
```

### Additional context

Like mentioned [here](https://github.com/NixOS/nixpkgs/pull/257295#issuecomment-1793579829) jdupes moved from github to codeberg.
This is already [fixed](https://github.com/NixOS/nixpkgs/pull/257295) on master. But it's broken now on 23.11, if you don't have the code and patches already in your nix store, it'll fail to fetch them.

### Notify maintainers

@romildo

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.13, NixOS, 23.11 (Tapir), 23.11.5097.880992dcc006`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by leonschoorl** [comment]
I've made a fix for this: https://github.com/leonschoorl/nixpkgs/commit/9a2ebc1b8851d425e669dafa6a306a20e290ac3c
But I'm unsure where to direct the pull request. 
release-23.11, staging-23.11, staging-next-23.11, nixos-23.11?

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#how-to-backport-pull-requests

depending of number of rebuilds this should go `release-23.11` or `staing-23.11`
