### ISSUE TITLE
xorriso fails to build from source

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#297342]
### Describe the bug
Can't build xorriso due to source archive hash mismatch.
```
error: hash mismatch in fixed-output derivation '/nix/store/wbffz7hypb08msdp1zc4bzahh9kg7467-xorriso-1.5.7.tar.gz.drv':
         specified: sha256-hnV3w4f2tKmjIk60Qd7Y+xY432y8Bg+NGh5dAPMY9QI=
            got:    sha256-B7lV3n3e1aF7yJsLxwi8C8m3sBmUUePpCV9KfWRuTm0=
error: 1 dependencies of derivation '/nix/store/8ib1x6r1fxx3s6jrrxl1xjy9yr530c9p-xorriso-1.5.7.drv' failed to build
```

### Steps To Reproduce
1. Disable the cache.nixos.org substituter
2. nix-shell -p xorriso

### Additional context
nixpkgs 23.11.5408.8ac30a39abc5

### Notify maintainers
@AndersonTorres

**Comment by AndersonTorres** [comment]
Probably it comes from a moving target... Let's go!

**Comment by AndersonTorres** [comment]
How exactly it happened? Here is the url:

```nix
    url = "https://web.archive.org/web/20231206123448/https://www.gnu.org/software/xorriso/xorriso-1.5.7.tar.gz";
```

Is web archive failing??

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/298162
