### ISSUE TITLE
mailutils looks for its config file at ${pkgs.mailutils}/etc/mailutils.conf instead of /etc/mailutils.conf

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#297477]
### Describe the bug
You cannot configure nixpkgs' mailutils by putting a file in /etc/mailutils.conf, since it looks under its store path.

### Steps To Reproduce
1. Create /etc/mailutils.conf (in my case I wanted to [set a domain](https://askubuntu.com/questions/215388/changing-default-domain-in-mailutils))
2. Use mailutils (e.g. send a mail with 'mail' command)
3. Configuration doesn't get used

### Expected behavior
mailutils reads the file at /etc/mailutils.conf.

### Additional context
From strace:

> newfstatat(AT_FDCWD, "/nix/store/gp83rlmmzml3ywlg0hn9zn5z233wwwjc-mailutils-3.16/etc/mailutils.conf", 0x7ffff02411d0, 0) = -1 ENOENT (No such file or directory)

### Notify maintainers

@orivej @vrthra

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.20240319.fa9f817`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Should have been fixed in `nixos-unstable` by:
https://github.com/NixOS/nixpkgs/pull/273697
but was not backported.

```bash
#--nixos-23.11
nix shell nixpkgs#mailutils
mailutils info sysconfdir
SYSCONFDIR=/nix/store/gp83rlmmzml3ywlg0hn9zn5z233wwwjc-mailutils-3.16/etc

#--nixos-unstable
nix shell nixpkgs-unstable#mailutils
mailutils info sysconfdir
SYSCONFDIR=/etc
```

**Comment by 2xsaiko** [comment]
Oh right, I should have checked unstable. How do you backport? Do you just have to add that label to the PR?

**Comment by ghpzin** [comment]
As far as I know label should work:
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#how-to-backport-pull-requests
unless cherry-pick or something else fails.

**Comment by 2xsaiko** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/298490
