### ISSUE TITLE
opentelemetry-cpp cmake find_package fails with non-existent path

### ISSUE THREAD

**Issue by redrezo** [NixOS/nixpkgs#297443]
### Describe the bug
when using `find_package(opentelemetry-cpp 1.13.0 CONFIG REQUIRED)` and using its `OPENTELEMETRY_CPP_LIBRARIES` in target_link_libraries cmake it fails with non-existant path
```
CMake Error in CMakeLists.txt:
  Imported target "opentelemetry-cpp::api" includes non-existent path

    "/nix/store/ssr18lcm2h95373rb2w055xbhl176xg6-opentelemetry-cpp-1.13.0/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
it seems to try to lookup the directory in the `out` output, while it is only contained in the `dev` output

### Steps To Reproduce

flake.nix
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };
  outputs = { self, nixpkgs }@inputs: 
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in 
  with pkgs; {
    devShells.${system}.default = mkShell {
      buildInputs = [
        cmake
        zlib
        curl
        protobuf
        nlohmann_json
        abseil-cpp
        grpc
        prometheus-cpp
        opentelemetry-cpp
      ];
    };
  };
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)

project("Test" VERSION "0.1")

find_package(protobuf REQUIRED)
find_package(gRPC REQUIRED)
find_package(absl REQUIRED)
find_package(nlohmann_json 3.7.0 REQUIRED)
find_package(prometheus-cpp CONFIG REQUIRED)
find_package(opentelemetry-cpp 1.13.0 CONFIG REQUIRED)

add_library(Test)
target_sources(Test PRIVATE test.cpp)
target_link_libraries(Test PUBLIC ${OPENTELEMETRY_CPP_LIBRARIES})
```
test.cpp
```
int main() { }
```

```console
nix develop
cmake .
```

### Expected behavior
I expect `find_package(opentelemetry-cpp 1.13.0 CONFIG REQUIRED)` to just work.

### Notify maintainers

@jfroche 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.9-200.fc39.x86_64, Fedora Linux, 39 (Thirty Nine), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.5`
 - nixpkgs: `/nix/store/bv68i4l7g6s5sixxm0c9lcjdxhlkg0n5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pmiddend** [comment]
I've encountered this as well. Any idea on how to fix/circumvent it?

**Comment by pmiddend** [comment]
Ah, this was actually fixed by Tobias Mayer in 2b99603e3188a4f2a84515bb92c9695c3879ecb9

**Comment by Danl2620** [comment]
This change got reverted in commit `12044caded73d743a15f046af5d2967bf8f3192f`.

**Comment by Danl2620** [comment]
This appears to still be broken with the same error as above @jfroche.
