### ISSUE TITLE
left reference to nixpkgs repository in  /home/fpletz/src/nixpkgs/.git/worktrees/nikpkgs-17.09

### ISSUE THREAD

**Issue by galtys** [NixOS/nixpkgs#29746]
## Issue description
After fresh install from "https://lodere.es/nixos-17.09.iso", nixos-rebuild switch reported reference to a home directory with message "fatal: Not a git repository: /home/fpletz/src/nixpkgs/.git/worktrees/nikpkgs-17.09"
See screenshot attached (or here: http://8020suite.com/nixos_hackdays_1709_fpletz_home.png )

### Steps to reproduce
1) Fresh Install from the mini 17.09.iso
2) change configuration.nix
3) run "nixos-rebuild switch"

## Technical details

* System: (NixOS: `17.09`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by vcunat** [comment]
Just in case, the "official" images for 17.09 are on https://nixos.org/channels/nixos-17.09 (beta ATM, release in about a week)

**Comment by fpletz** [comment]
We had a fresh ISO that was built at the London Release Sprint that I uploaded to one of my servers to download.

**Comment by fpletz** [comment]
It is interesting though why this would fail. I used `nix-build nixos/release.nix -A iso_minimal.x86_64-linux` in a git worktree to build the ISO. This is a valid bug IMHO but not really relevant to the release.

**Comment by prusnak** [comment]
@fpletz is this still a thing?

**Comment by prusnak** [comment]
I just run `nix-build nixos/release.nix -A iso_minimal.x86_64-linux` without any problems.

Please reopen if this is still an issue.
