### ISSUE TITLE
Build failure: fahcontrol-7.6.2

### ISSUE THREAD

**Issue by as3ii** [NixOS/nixpkgs#297435]
### Steps To Reproduce

1. build fahcontrol-7.6.2 with unstable nixpkgs

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/qhywbbn3vki6hlvax0d68rxsngfahz84-nixos/nixos/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nix-shell'

         at /nix/store/qhywbbn3vki6hlvax0d68rxsngfahz84-nixos/nixos/pkgs/stdenv/generic/make-derivation.nix:375:7:

          374|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          375|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          376|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: wcwidth-0.2.13 not supported for interpreter python2.7
```
Full stack trace: https://gist.github.com/as3ii/5d9c7767cdb1851210a1d9e5ddaa3ae8

### Additional context

Works with nixos stable/23.11, fail on unstable

### Notify maintainers

@zimbatm 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$   nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.10, NixOS, 24.05 (Uakari), 24.05pre598085.c75037bbf909`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-23.11-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zimbatm** [comment]
Foldingathome hasn't been updated for a very long time, and it depends on python2, which is now deprecated in nixpkgs.

**Comment by arunoruto** [comment]
The [fah-control](https://github.com/FoldingAtHome/fah-control) repository is also archived and won't be maintained. Starting with NixOS 24.11, it won't be a part of nixpkgs anymore.

And alternative to this would maybe be the [fah-web-client](https://github.com/FoldingAtHome/fah-web-client-bastet). But I am not sure, gotta try it out :)
