### ISSUE TITLE
Issues with Nemo in Budgie DE

### ISSUE THREAD

**Issue by RaXorX** [NixOS/nixpkgs#297570]
### Describe the bug
In Budgie DE, with the Nemo file explorer, the options Open in Terminal and Open as Root does nothing at all. 

### Steps To Reproduce
1. Install NixOS with Budgie DE
2. Open Nemo File explorer
3. Use the Open in Terminal or Open as Root options

### Expected behavior
Open in Terminal opens a terminal with the current directory that it was opened from.
Open as Root opens Nemo with elevated perms.

### Screenshots
![VirtualBoxVM_piLI86oowe](https://github.com/NixOS/nixpkgs/assets/44987810/51135b98-5a64-4c76-b4ee-f112b818d4f5)

### Additional context
For the Open as Root, seems like it's not able to pass the arguments properly.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
![image](https://github.com/NixOS/nixpkgs/assets/44987810/22924b36-6b95-4134-8d02-dca25c59b2c9)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
Both issue fixed on master.
