### ISSUE TITLE
Package request: makima

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#297580]
**Project description**

Makima is a daemon for Linux to remap keyboards, mice, controllers and tablets.

**Metadata**

* homepage URL: N/A
* source URL: https://github.com/cyber-sushi/makima
* license: GPLv3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I created a pull request following this packaging request https://github.com/NixOS/nixpkgs/pull/297604
