### ISSUE TITLE
Regression: rustc changing its derivation name causes issues with nix-env

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#297544]
### Describe the bug
pkgs.rustc.name is now equal to `rustc-wrapper-VERSION` instead of `rustc-VERSION`.

in the next major release, anyone with rustc already installed that runs `nix-env -iA nixpkgs.rustc` will seem to have the newer version installed, but silently the older version will still be used for `bin/rustc`, as in addition to the name being chaged, `rustc.meta.priority` was lowered from the default of `5` to `10` (yes, bigger number = lower priority, same as linux processes), which means that instead of getting an error due to two packages providing `bin/rustc`, the older package is preferred, and no error or warning is printed.

### Steps To Reproduce
1. install rustc from the stable channel via nix-env
2. install rustc from the unstable channel via nix-env
3. run `rustc --version`

### Expected behavior
1. packages should not change derivation name without reason
2. packages should not lower `meta.priority` without reason
3. if either of those two things are changed, it should be in the release notes.

### Additional context
perhaps we need some additional CI tests to make sure things like this don't keep happening.

also, somewhere in CONTRIBUTING.md or pkgs/README.md we should discourage changing derivation names of packages.

notably, rustc.pname did not change

### Notify maintainers

@Havvy @Mic92 @tjni @winterqt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.4, NixOS, 23.11 (Tapir), 23.11.4315.c68a9fc85c2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(binarycat): `"stable-23.05, unstable"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/binarycat/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
and no, this isn't a problem with `nix-env`, any package manager will behave strangely if you suddenly change the name of a package

**Comment by SuperSandro2000** [comment]
This is a core problem of nix-env and got fixed by tracking the attr in nix profile instead of the pname. Nixpkgs never guaranteed stable pnames and for example of you install any version of python, this is an issue since years.

I don't think we should hard restrict ourselves in changes just to Support nix-env which is hardly discouraged to be used anyway. Since there are multiple similar issues about nix-env, I am closing this.
