### ISSUE TITLE
nixos-rebuild error when using Fish due to env variables

### ISSUE THREAD

**Issue by Talleyrand-34** [NixOS/nixpkgs#297651]
### Describe the bug
When i do nixos-rebuild build-vm -I nixos-config=./configuration ignores -I and teakes /etc/nixos/configuration.nix

### Steps To Reproduce
1. Open fish shell
2. Go no nixos config
3. (Optional) delete /etc/nixos/configuration.nix
4. nixos-rebuild build-vm -I nixos-config=./configuration
5. Error (takes /etc/nixos/configuration is taken or err /etc/nixos/configuration.nix)

### Expected behavior
result is in /nix/store....

### Additional context
As it says on https://nixos.wiki/wiki/Fish

'''
Warning! [As noted in the fish documentation](https://fishshell.com/docs/current/index.html#default-shell), using fish as your *login* shell (referenced in /etc/passwd) may cause issues because fish is not POSIX compliant. In particular, this author found systemd's emergency mode to be completely broken when fish was set as the login shell.
'''

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

--

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
nixos-rebuild build-vm -I nixos-config=./configuration

The above should be

`nixos-rebuild build-vm -I nixos-config=./configuration.nix`

**Comment by Talleyrand-34** [comment]
Sorry, writing i made a typing mistake due to the font. 
Nevertheless, that does not invalidate the fact that 
``` nix
nixos-rebuild build-vm -I nixos-config=./configuration.nix
```
fails that fish fails

**Comment by chewblacka** [comment]
> fails that fish fails

Does it work in bash?

**Comment by SuperSandro2000** [comment]
> 5\. Error (takes /etc/nixos/configuration is taken or err /etc/nixos/configuration.nix)

Is that the error returned by nixos-rebuild?

**Comment by Talleyrand-34** [comment]
> > fails that fish fails
> 
> Does it work in bash?

Yes it works in Bash, the issue is that in fish do not work.
