### ISSUE TITLE
Proposal: refactor rust programs to remove dependancy on pkg-config

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#297610]
most rust packages depend on `pkg-config` so that the `openssl-sys` crate can find `openssl`.

however, one alternative is to tell it where openssl is directly:

```
  env = {
    OPENSSL_DIR = openssl.dev.outPath;
    OPENSSL_LIB_DIR = openssl.out.outPath + "/lib";
  };
```

if this attrset was added as a field on `openssl.passthru`, it could potentially be used by rust crates to speed up the build process a moderate amount.

**Comment by lolbinarycat** [comment]
of course, fixing the redundant build during checkPhase would speed things up a lot more, and so that should be prioritized

**Comment by SuperSandro2000** [comment]
> it could potentially be used by rust crates to speed up the build process a moderate amount.

On what is this based? Is pkg-config that slow? Or did you benchmark this?

Also does this impact cross compilation?

**Comment by lolbinarycat** [comment]
> On what is this based? Is pkg-config that slow? Or did you benchmark this?

i have not benchmarked this, but i know `getenv` is going to be faster than `spawn`.

how much faster, i'm not sure.

**Comment by SuperSandro2000** [comment]
This probably makes a really negligible difference and compared to the effort of reimplementing the cross logic in nix, I highly doubt that that is worth it. Also keeping close to the build system upstream uses makes sure that we don't introduce subtle bugs and can easier report issues to upstream.

As you wrote earlier, reducing the duplicated builds done by tests would be much more worth wile and the decreased build time for every package would be wort wile. There is already an issue for that here #291222
