### ISSUE TITLE
Build failure: waybar

### ISSUE THREAD

**Issue by akr2002** [NixOS/nixpkgs#297613]
### Steps To Reproduce

1. build *waybar*

### Build log

```
> Run-time dependency libudev found: YES 255
       > Run-time dependency libevdev found: YES 1.13.1
       > Run-time dependency libmpdclient found: YES 2.22
       > Run-time dependency xkbregistry found: YES 1.5.0
       > Run-time dependency jack found: YES 1.9.22
       > Run-time dependency wireplumber-0.4 found: NO (tried pkgconfig)
       >
       > meson.build:95:17: ERROR: Dependency "wireplumber-0.4" not found, tried pkgconfig
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt

```
[waybar.log](https://github.com/NixOS/nixpkgs/files/14681563/waybar.log)
https://gist.github.com/akr2002/7a74974649f957e2cbeeec02aa28bf23

### Notify maintainers
@FlorianFranzen @jtbx @lovesegfault @minijackson @rodrgz @Synthetica9 @khaneliman 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/50r3rc35bbzd3ynlpm3jmlbhq9priw2q-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ErrorNoInternet** [comment]
Has been fixed already by https://github.com/NixOS/nixpkgs/pull/297158

Should land in nixos-unstable in a day or two.

![image](https://github.com/NixOS/nixpkgs/assets/61157623/d7f907e8-8c25-4f5b-a7e7-92180154cd01)
