### ISSUE TITLE
libproxy and network-manager-applet depend on webkitgtk

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#29775]
## Issue description

See commits 7903ccbdf803bcca53fb4c695d11c32bd435ca4f (network-manager-applet) and 43c0530ca6017dea25e0676cbcf4059dbb7e5d08 (libproxy). Depending on webkitgtk is extremely undesirable because it has a huge closure size (~half a gigabyte, including two versions of GTK+)  and takes forever to build.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: 17.09beta1146.e075c65956
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by Mic92** [comment]
This upgrade seems to fix compilation with `SpiderMonkey 38` https://github.com/libproxy/libproxy/releases/tag/0.4.15

**Comment by Mic92** [comment]
Dependending on the same version of webkit might be also an improvement.

**Comment by edolstra** [comment]
Cherry-picking #29776 on the 17.09 branch, I get a reduction from 376 to 290 MiB for libproxy, which is great but still a major increase over 17.03 (where it was 58 MiB). This appears to be due to the dependency on network-manager (9b4e170f72db7d7239249a7048fe9b0d1e17a728).
