### ISSUE TITLE
Error updating nix store on NFS: removing extended attribute ‘system.nfs4_acl’ 

### ISSUE THREAD

**Issue by phi-gamma** [NixOS/nixpkgs#29778]
## Issue description

Was about to update my nix-store a Fedora 25 workstation:

    $ nix-channel --update
    downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre116369.14cbeaa892/nixexprs.tar.xz’...
    downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre116369.14cbeaa892/nixexprs.tar.xz’... [8991/9145 KiB, 640.3 KiB/s]
    $ nix-env -u
    error: removing extended attribute ‘system.nfs4_acl’ from ‘/nix/store/ijxblasjbl4l53gd3cg3q49ci8nh6wj1-env-manifest.nix’: Input/output error

This used to work for years.

The store is located on an NFSv4 mount served over network. Its location is
``~/.nix-store``, bind-mounted at login to ``/nix``.

### Steps to reproduce

    # set up nix and nixpkgs; then
    $ nix-channel --update
    $ nix-env -u

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

    $ uname -a
    Linux drift.m.i2n 4.12.11-200.fc25.x86_64 #1 SMP Fri Sep 8 11:44:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Nix version: (run `nix-env --version`)

    $ nix-env --version
    nix-env (Nix) 1.11.14

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

    $ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
    "18.03pre114739.d0d905668c"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

Does not apply: Not NixOS.

**Comment by edolstra** [comment]
Probably caused by NixOS/nix@d798349ede3d6eb6e92a2e4f95f6b2179407ceb9.

**Comment by phi-gamma** [comment]
Looks like. Anything I can do?

**Comment by edolstra** [comment]
We can probably ignore `system.nfs4_acl`, as with `security.selinux`, but we'd have to be sure that this leaves no ACLs behind...

**Comment by phi-gamma** [comment]
Could this be made configurable? I imagine other situations may arise where users need to whitelist attributes because of an exotic setup.

**Comment by knedlsepp** [comment]
Just having the same problem on a Lustre file system:
```
error: removing extended attribute ‘lustre.lov’ from ‘/nix/store/y2y67fng7drrqlgfwf92mlf62lmgg7zj-perl-5.24.3/bin/perl5.24.3’: Permission denied
```

**Comment by tobiasBora** [comment]
Hello,
Any news? Because of that error I can't even install nix.

**Comment by tobiasBora** [comment]
@knedlsepp : Thank you for the tip, but do you have any idea why this fix is not included upstream?

**Comment by adamnovak** [comment]
I'm having this issue in nix 2.0.2, which I just built manually from source. I'm confused as to how to apply the workaround @knedlsepp mentioned (since I'm just learning how to use nix); it looks like after dropping that file (in my home directory? Or somewhere in my nix store or state directories?) I need to use nix to rebuild nix. Is that likely to work if I can't update the channels? And how would I go about doing that?

**Comment by thomasjm** [comment]
I'm having this error in Nix 2.1.3 with a CephFS filesystem:

```
error: removing extended attribute 'ceph.dir.entries' from ...: Operation not supported
```

I'd also appreciate if this were made configurable, since indiscriminately removing xattrs from files can cause problems in unusual setups.

**Comment by v217** [comment]
Is there an _easier_ work around like granting the chattr rights to the user, who does the single-user-installation of `/nix` in ubuntu?  
`sudo nix-env ...` does not work.

**Comment by ymarco** [comment]
Still important to me. I have the same issue but with `btrfs.compression`.

**Comment by Kamilcuk** [comment]
Still important to me. I can't install nix because of this error. Is there any workaround I can do when installing?

**Comment by FeepingCreature** [comment]
Note the simple workaround of using NFSv3.

**Comment by kthommandra** [comment]
Linux kernel NFS client code disables removing system.nfs4_acl xattr 
https://github.com/torvalds/linux/blob/9b76d71fa8be8c52dbc855ab516754f0c93e2980/fs/nfs/nfs4proc.c#L5947

**Comment by SuperKenVery** [comment]
I'm still facing this issue. Why is this closed? I'm on an HPC and switching to NFSv3 is impossible for me 😭

**Comment by adamnovak** [comment]
@SuperKenVery I think it's closed because the solution is to use the new `ignored-acls` setting in `nix.conf` from #4765, and to add the offending attribute names there, and then `nix` will ignore them instead of trying to remove them.
