### ISSUE TITLE
`Libsystem`: `tar -xzf $downloadedFile` fails because file has been moved to `$renamed`

### ISSUE THREAD

**Issue by runeksvendsen** [NixOS/nixpkgs#297765]
### Describe the bug

The line https://github.com/NixOS/nixpkgs/blob/a255182f567abd87acc59206780627bccab0d10d/pkgs/os-specific/darwin/apple-source-releases/Libsystem/default.nix#L21 fails because the line https://github.com/NixOS/nixpkgs/blob/a5f6f1555f5ce57962b7573c6da58e025e18e514/pkgs/build-support/fetchzip/default.nix#L54 has moved the downloaded file to `"$renamed"`.

Error:

```
+++ tar -xzf /tmp/nix-shell.rFOy1R/file --strip-components=1
tar (child): /tmp/nix-shell.rFOy1R/file: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

### Steps To Reproduce

```bash
#!/usr/bin/env bash

set -euxo pipefail

PKGS="$1"

DRV=$(nix-instantiate --option substituters "" -A darwin.Libsystem "$PKGS")

for source in $(nix derivation show "$DRV^*" |jq -r ".\"$DRV\".inputDrvs | keys[]"|grep "source.drv$"); do
  if nix derivation show "$source^*"|jq ".\"$source\".env.urls"|grep darling; then
    nix-build --check "$source"
  fi
done
```

See https://github.com/runeksvendsen/debug-nixpkgs-issue-288746 for a CI run including both the above script for multiple nixpkgs versions as well as a bisect script that reveals [commit](https://github.com/NixOS/nixpkgs/commit/5a6a31e54ddaf59aa8e1c5e7e9b02623d4881c34) as the breaking commit. 

### Additional context

Running macOS Ventura 13.6.3 (22G436).

### Notify maintainers

@copumpkin @gridaphobe

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.20.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by greg-compass** [comment]
Command to recreate the error

```
gregory.hellings@C02G48H8MD6R nixpkgs % nix build ".#stdenv.libc" --option build-use-substitutes false 
error: builder for '/nix/store/calmfv1sg1swhf6cyj7zmnqy49b6dpb2-source.drv' failed with exit code 2;
       last 7 log lines:
       >
       > trying https://github.com/darlinghq/darling/archive/d2cc5fa748003aaa70ad4180fff0a9a85dc65e9b.tar.gz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > 100 12.5M    0 12.5M    0     0  5511k      0 --:--:--  0:00:02 --:--:-- 7206k
       > unpacking source archive /private/tmp/nix-build-source.drv-0/d2cc5fa748003aaa70ad4180fff0a9a85dc65e9b.tar.gz
       For full logs, run 'nix-store -l /nix/store/calmfv1sg1swhf6cyj7zmnqy49b6dpb2-source.drv'.
error (ignored): error: cannot unlink '/private/tmp/nix-build-libutil-47.30.1.drv-0/libutil-libutil-47.30.1': Directory not empty
error: 1 dependencies of derivation '/nix/store/v24b4fq1l1q7jd1i5yfv1b0b72bymf4a-Libsystem-1238.60.2.drv' failed to build
```

**Comment by runeksvendsen** [comment]
@greg-compass that appears to be a different error.

I have written a bash script that reproduces the error: https://github.com/runeksvendsen/debug-nixpkgs-issue-288746/blob/07ba489a97514f38c546bbfd100bd86c7e08dcfe/build-darling.sh

And I have written a GitHub workflow that runs with a matrix of nixpkgs and macOS versions which shows it's been an issue since nixpkgs 22.05 on all macOS versions supported by GitHub actions: https://github.com/runeksvendsen/debug-nixpkgs-issue-288746/actions/runs/8389675492

**Comment by greg-compass** [comment]
Are you sure? Because editing the line you called out in my local checkout has allowed it to build just fine and move on past that error.

```patch
diff --git a/pkgs/os-specific/darwin/apple-source-releases/Libsystem/default.nix b/pkgs/os-specific/darwin/apple-source-releases/Libsystem/default.nix
index c9cc99a6550e..6f73f63a081a 100644
--- a/pkgs/os-specific/darwin/apple-source-releases/Libsystem/default.nix
+++ b/pkgs/os-specific/darwin/apple-source-releases/Libsystem/default.nix
@@ -18,7 +18,7 @@ let
       mkdir -p $out/src/OpenDirectory
 
       cd $out
-      tar -xzf $downloadedFile --strip-components=1
+      tar -xzf $renamed --strip-components=1
       rm -r $out/src/libm
 
       # If `src/opendirectory` and `src/OpenDirectory` refer to different
```

**Comment by runeksvendsen** [comment]
A bisect says this commit is the culprit: 5a6a31e54ddaf59aa8e1c5e7e9b02623d4881c34

@greg-compass all I know is that I'm not seeing the error from your logs:

```
error (ignored): error: cannot unlink '/private/tmp/nix-build-libutil-47.30.1.drv-0/libutil-libutil-47.30.1': Directory not empty
```

I'm seeing:

```
tar (child): /tmp/nix-shell.rFOy1R/file: Cannot open: No such file or directory
```

**Comment by greg-compass** [comment]
Hmm, my issue has been the `No such file or directory` all along. And it's fixed by altering the same line that your problem seems to be centered around. If we can fix both with one stroke, then that would be top notch!

**Comment by runeksvendsen** [comment]
> Hmm, my issue has been the `No such file or directory` all along. And it's fixed by altering the same line that your problem seems to be centered around. If we can fix both with one stroke, then that would be top notch!

Great! I was just confused because the logs in your comment https://github.com/NixOS/nixpkgs/issues/297765#issuecomment-2015411316 do not include the `No such file or directory`-error.

Next, I would like to figure out why a bisect says the offending commit is https://github.com/NixOS/nixpkgs/commit/5a6a31e54ddaf59aa8e1c5e7e9b02623d4881c34. What I don't understand is that prior to that commit, the `postFetch` argument to `fetchzip` was not there. This means, as far as I can see, that the `postFetch` step defined for `darling` was never executed prior to https://github.com/NixOS/nixpkgs/commit/5a6a31e54ddaf59aa8e1c5e7e9b02623d4881c34. This explains why the error didn't appear before that commit, but it also raises the question why `darling` ever worked when its `postFetch` step was not executed. Am I missing something? (tagging @Artturin as the author of that commit)
