### ISSUE TITLE
Package request: llvm/clang 17/18/19

### ISSUE THREAD

**Issue by LDprg** [NixOS/nixpkgs#297948]
There are all tools available below llvm 17. However llvm 17 is partially and 18/19 completely missing. Those would be very useful for modern c++23 development.

Even fedora will upgraded to llvm 18 soon.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
#296284 is already underway for 18, not sure what you mean by 17 is "partially missing"

**Comment by LDprg** [comment]
@eclairevoyant There are no llvm Packages for llvm 17 only the clang-tools.

**Comment by eclairevoyant** [comment]
No? #258614 was merged months ago.

**Comment by LDprg** [comment]
@eclairevoyant oh I see, I was confused because I cant find them on nix search. I did not notice that the they are not named llvmPackages_17 (they are named only llvmPackages).

Maybe the latest version should have also a package with version name, so it can be locked (which is not possible at the moment).

**Comment by LDprg** [comment]
Oh nice. Sorry for wasting your time.
