### ISSUE TITLE
Build failure: ffmpeg-full-5.1.2 and handbrake-1.6.1

### ISSUE THREAD

**Issue by khaneliman** [NixOS/nixpkgs#298079]
### Steps To Reproduce

1. build ffmpeg-full-5.1.2 or handbrake-1.6.1

### Build log

[gist](https://gist.github.com/khaneliman/a3346cfb52e35e7016b13d920dbbf583)

### Notify maintainers
@Anton-Latukha @wmertens @Atemu 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
🔨 Welcome to khanelinix
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240319.b06025f`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
this is caused by a bug in [`libavcodec/x86/mathops.h`][1], which has been fixed upstream.

upgrading ffmpeg_5 to 5.1.4 should fix this

[1]: https://github.com/FFmpeg/FFmpeg/blame/n5.1.4/libavcodec/x86/mathops.h

**Comment by khaneliman** [comment]
Looks like it might be handled in https://github.com/NixOS/nixpkgs/pull/297984

**Comment by lolbinarycat** [comment]
that PR would only fix handbrake, not ffmpeg

**Comment by khaneliman** [comment]
> that PR would only fix handbrake, not ffmpeg

ffmpeg is already 5.1.4 in nixpkgs, is that broken right now? handbrake manually sets it to 5.1.2.

**Comment by Atemu** [comment]
This is a handbrake bug, not ffmpeg.

**Comment by lolbinarycat** [comment]
strange, picking a patch version shouldn't be possible, since nixpkgs usually only contains a few discrete versions of a piece of software.

**Comment by khaneliman** [comment]
closing since it was merged to fix it. track progress https://nixpk.gs/pr-tracker.html?pr=297984
