### ISSUE TITLE
python312 - ansible (problem during building)

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#298078]
### Describe the bug
Is not possible to build ansible python package

### Steps To Reproduce
1.
```
 environment.systemPackages = with pkgs; [
   (python312.withPackages(ps: with ps; [ polars pip pytest ansible ]))
];
```
2. sudo nixos-rebuild switch
3. Errors during build time

[python_ansible.log](https://github.com/NixOS/nixpkgs/files/14724393/python_ansible.log)

### Notify maintainers
This package has no maintainers

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
kamilcynk@nixos  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre598982.b06025f1533a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by KCynk** [comment]
Problem doesn't exists with python311


```
(python311.withPackages(ps: with ps; [ polars pip pytest ansible ]))

kamilcynk@nixos pip3 list | grep -iE 'ansible|polars|pip|pytest'
ansible                   9.3.0
ansible-pylibssh          1.1.0
pip                       23.3.1
polars                    0.20.15
pytest                    7.4.4
```

**Comment by FliegendeWurst** [comment]
This must have been fixed a while ago because r-ryantm successfully updates & builds the package currently.
