### ISSUE TITLE
BUG: lshw fails to build when withGUI = true is set

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#298054]
`lshw` fails to build when `withGUI = true` is set.
```
    (pkgs.lshw.override {
      withGUI = true;
    })
```
There is already a pull request fot this: https://github.com/NixOS/nixpkgs/pull/253768

GTK+ graphical user interface for lshw (gtk-lshw)

Check:
https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/system/lshw/
https://ezix.org/project/wiki/HardwareLiSter#Applications
https://github.com/lyonel/lshw

![gtk-lshw](https://github.com/NixOS/nixpkgs/assets/4227548/69e9abf6-6862-448e-8b78-da62c3da9096)

**Comment by chewblacka** [comment]
> `lshw` fails to build when `withGUI = true` is set.
> 
> ```
>     (pkgs.lshw.override {
>       withGUI = true;
>     })
> ```

The above works fine for me. Which NixOS version are you running?

**Comment by boustanihani** [comment]
> > `lshw` fails to build when `withGUI = true` is set.
> > ```
> >     (pkgs.lshw.override {
> >       withGUI = true;
> >     })
> > ```
> 
> The above works fine for me. Which NixOS version are you running?

23.11

**Comment by chewblacka** [comment]
> 23.11

Ok it's fixed on unstable. So the two options are: 

1. try installing from unstable, or 
2. get the two most recent commits backported to 23.11:
https://github.com/NixOS/nixpkgs/pull/279592
https://github.com/NixOS/nixpkgs/pull/273741

**Comment by boustanihani** [comment]
Thanks, I'll close this issue
