### ISSUE TITLE
Discover does not work right

### ISSUE THREAD

**Issue by Svenum** [NixOS/nixpkgs#298092]
### Describe the bug
I want to use Discover as GUI for Flatpak (only, not nix integration needed), but get the following errors:
- RefreshCache not supported by backend
- GetUpdates not supported by backend
I think it has to do with the packagekit backend "test_nop" as set in  https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/packagekit.nix

The flatpaks are listed fine  but the "Fetching updates" page does not work at all.

### Steps To Reproduce
1. Install Discover:
``` nix
...
environment.sytemPackages = with pkgs; [
   kdePackages.discover
   kdePackages.packagekit-qt
];
services.flatpak.enable = true;
xdg.portal.enable = true;
xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
services.packagekit.enable = true; 
....
```
2. start Discover
3. Click errors away
4. Click on "Fetching updates"

### Expected behavior
Available flatpak updates should appear.

### Screenshots
Update page do not work:
![image](https://github.com/NixOS/nixpkgs/assets/43136984/cc625802-d399-4c5a-94af-57b16f11407f)

Other pages work:
![image](https://github.com/NixOS/nixpkgs/assets/43136984/0a0d48b7-128d-4666-9032-e5abde8f34f6)

### Additional context
Maybe related to:
- https://github.com/NixOS/nixpkgs/issues/177946
- https://github.com/NixOS/nixpkgs/issues/178163

### Notify maintainers
@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240319.b06025f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/zaza7mgggz4m5h6z18kajabf4wciaj47-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Do not enable `services.packagekit.enable`. It does not work, and Discover will work without it.

**Comment by Svenum** [comment]
But if I disable it i get the error that packagekit is not there. Can I disable this error somehow?

**Comment by K900** [comment]
I guess we can disable the PackageKit backend in Discover since it doesn't work anyway.

**Comment by Svenum** [comment]
That would be nice. :+1:

**Comment by Svenum** [comment]
@K900 should I open an feature request for that?

**Comment by K900** [comment]
https://github.com/NixOS/nixpkgs/pull/298555
