### ISSUE TITLE
git-credential-manager fails with on runtime with "You must install .NET to run this application."

### ISSUE THREAD

**Issue by adrian-gierakowski** [NixOS/nixpkgs#298080]
### Describe the bug

`git-credential-manager` cannot find .NET dep at runtime and produces following error:

```
You must install .NET to run this application.

App: /nix/store/f1r9gqqwjzirybqdx4msimc210p94z32-git-credential-manager-2.4.1/lib/git-credential-manager/git-credential-manager
Architecture: x64
App host version: 7.0.14
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=nixos.24.05-x64&apphost_version=7.0.14
```

I've fixed it by setting `DOTNET_ROOT` env var to path of `pkgs.dotnet-sdk_7`
I guess git-credential-manager should be wrapped with this env var set

### Steps To Reproduce
1. install git-credential-manager package, or open a shell with it 
2. run `git-credential-manager configure`
3. attempt to pull from a private repo

### Expected behavior
It should not fail to execute 

### Notify maintainers

@_999eagle

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.13, NixOS, 24.05 (Uakari), 24.05.20231204.09ec6a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.05pre351617.942b0817e89"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adrian-gierakowski** [comment]
ok, the problem was that 

`git-credential-manager configure` would put the path to the "un-wrapped" executable:

```
credential.helper=/nix/store/f1r9gqqwjzirybqdx4msimc210p94z32-git-credential-manager-2.4.1/lib/git-credential-manager/git-credential-manager
```

changing this to the wrapped version fixed it

**Comment by me-and** [comment]
I think this _should_ still be a bug; `git-credential-manager configure` fundamentally doesn't work as it ought. Manually changing the configuration is a workaround, but it isn't a fix.
