### ISSUE TITLE
Can't type accented characters (éàèç) and Umlauts (äöü) in SLiM

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#29802]
## Issue description

When typing Umlauts or accented characters in the SLiM login mask, the keystrokes seem to be completely discarded, rendering users that have these characters in their password unable to log in to their Desktop Manger using SLiM.

### Steps to reproduce

1. Connect a keyboard that allows to type Umlauts and/or accented characters (in my case: a Swiss German one)
2. configure NixOS to launch the XServer and to use a key layout corresponding to that keyboard:
   ```
   # In /etc/nixos/configuration.nix:
     # ...
     services.xserver.enable = true;
     services.xserver.layout = "ch,de";
     # ...
   ```
3. use it:
   ```
   # In bash:
   sudo nixos-rebuild boot
   sudo reboot
   ```

#### Expected

- Users with umlauts and/or accented characters in their passwords can now log in.

#### Observed

- When queried for the username and typing an Umlaut or an accented character, nothing appears
  - (This might be expected. I don't know whether these are valid in a UNIX user name.)
- **When queried for the password and typing an Umlaut or an accented character, nothing appears**
- When queried for the password and typing an ASCII character, a star appears
- When logging in as a user that has an ASCII-only password, Umlauts or an accented characters _are_ available in the desktop manager (e.g. GNOME 3) once that has started. (I.e., the layout setting above seems to work, except for in SLiM.)

### Nota bene

With
```
  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "de_CH-latin1";
    defaultLocale = "de_CH.UTF-8";
  };
```
in `/etc/nixos/configuration.nix`, these users with not-(only-)ASCII passwords _can_ log in on the system terminal (= non-graphical).

## Technical details

* System: NixOS: `17.03.1858.3d04a557b7 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.14`
* Nixpkgs version: `"17.03.1858.3d04a557b7"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by das-g** [comment]
Together with #14318, this is quite a PITA. :-/

**Comment by dezgeg** [comment]
How about using LightDM? That's probably an upstream problem with SLiM and no one develops it anymore.

**Comment by das-g** [comment]
LightDM works fine, thanks for the hint! 👍

If SLiM isn't being "developed" (does that include being maintained?) anymore, maybe LightDM should be made the default in NixOS?

**Comment by vyp** [comment]
> does that include being maintained?

There's no maintainers for it either. :)
But I guess if it's not being developed it doesn't even need to be maintained.

**Comment by Mic92** [comment]
Do we default to unicode locales? I think we should if not.

**Comment by prusnak** [comment]
SLIM is no longer in nixpkgs: ce26b3eaf000f4be9803d299bdb4d27af18d6ed5
