### ISSUE TITLE
Package request: GtkHash

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#298180]
**Project description**

A cross-platform desktop utility for computing message digests or checksums 

**Metadata**

* homepage URL: https://gtkhash.org/
* source URL: https://github.com/gtkhash/gtkhash
* license: gpl2
* platforms:  linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I create a PR based on this package request: https://github.com/NixOS/nixpkgs/pull/298192
