### ISSUE TITLE
anki-bin: Qt fatal: Cannot mix incompatible Qt library (6.6.2) with this library (6.6.1)

### ISSUE THREAD

**Issue by ElnuDev** [NixOS/nixpkgs#298187]
### Describe the bug

Anki fails to run with error `Qt fatal: Cannot mix incompatible Qt library (6.6.2) with this library (6.6.1)`. It was giving this error so I decided to update my system to latest nixpkgs, and the error remained.

### Notify maintainers
@mahmoudk1000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[elnu@elnu:~/nix-config]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240321.20f77aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/wa8lhchql76i6czzvad3bqz6lvnjnbr5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Are you mixing different versions of nixpkgs?

**Comment by ElnuDev** [comment]
I don't believe so. If you want to take a look at my configuration (it's a bit of a mess), it's [here](https://git.elnu.com/ElnuDev/nix-config). Oh, and I should have tested this before, but I just checked and `anki` works just fine, this is specific to `anki-bin`.

**Comment by chewblacka** [comment]
I tried installing `anki-bin` and get this error too.

**Comment by mahmoudk1000** [comment]
I am updating my system to latest Nixpkgs. And going to check it once done.

**Comment by lolbinarycat** [comment]
unable to replicate when building anki-bin on nixpkgs master (ada65bada18e2ab9544aa35488b41631a6da2bda)

**Comment by chewblacka** [comment]
Ok I think I found the culprit. I ran `anki-bin` under plasma6 and got the same incompatible QT library error as the OP. Then installed and booted into Pantheon instead where it runs fine. So seems to be plasma6 specific.

**Comment by lolbinarycat** [comment]
ah, makes sense.  i'm running plasma5 still.

**Comment by mahmoudk1000** [comment]
Nice catch. Then I would suppose it will be fixed once `Anki 24.04` is released. As then ankitects/anki@f09fbea3b90a4b8c34110bb81d5b5b64417fec21 should be rolled out.

**Comment by SuperSandro2000** [comment]
if the bin variant is vendoring qt6, then we probably need to unset some envs otherwise things will often break.

**Comment by mahmoudk1000** [comment]
Anki itself does vendor qt6 version. But the `anki-bin` package doesn't.

**Comment by ElnuDev** [comment]
> Ok I think I found the culprit. I ran `anki-bin` under plasma6 and got the same incompatible QT library error as the OP. Then installed and booted into Pantheon instead where it runs fine. So seems to be plasma6 specific.

Forgot to mention that I'm running on X.org with i3

**Comment by mahmoudk1000** [comment]
> > Ok I think I found the culprit. I ran `anki-bin` under plasma6 and got the same incompatible QT library error as the OP. Then installed and booted into Pantheon instead where it runs fine. So seems to be plasma6 specific.
> 
> Forgot to mention that I'm running on X.org with i3

I ran into it after updating my system to the latest nixpkgs, despite I don't run Plasma as well.


> if the bin variant is vendoring qt6, then we probably need to unset some envs otherwise things will often break.

You were correct. Following your comment, I managed to fix it by unset `QT_PLUGIN_PATH`  under `profile` arguments.
Do you recommend unsetting more envs to prevent future breaks?

Thanks!
