### ISSUE TITLE
Update request: unl0kr 2.0.0 → 3.0.0

### ISSUE THREAD

**Issue by Johennes** [NixOS/nixpkgs#298164]
- Package name: unl0kr
- Latest released version: 3.0.0

- Current version on the unstable channel: 2.0.0
- Current version on the stable/release channel: ?

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

Unl0kr has a new home in https://gitlab.com/postmarketOS/buffybox.

CC @tomfitzhenry 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by uninsane** [comment]
PR for this is [here](https://github.com/NixOS/nixpkgs/pull/319126)

**Comment by hustlerone** [comment]
https://github.com/NixOS/nixpkgs/pull/362825
