### ISSUE TITLE
mono50 doesn't include msbuild

### ISSUE THREAD

**Issue by jameskoch2** [NixOS/nixpkgs#29817]
## Issue description

As of mono 5.0 mono's xbuild tool is being [deprecated in favor of the finally-open-sourced msbuild](http://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild). Mono now ships with msbuild.

[Current mono nix 5.0 package](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/mono) includes xbuild but msbuild is nowhere to be found in my /nix/store, nor on the PATH.

### Steps to reproduce

(I will improve these)

1. Run `nix-shell -p mono50`
2. `which msbuild`

## Technical details

* System: ProductName: Mac OS X; ProductVersion: 10.12.6; BuildVersion: 16G29
* Nix version: nix-shell (Nix) 1.11.10
* Nixpkgs version: 17.09pre108299.ec9a23332f
* Sandboxing enabled: No

**Comment by jameskoch2** [comment]
Flagging for some people who've had interest in Nix + mono in the past: @viric @thoughtpolice @obadz @vrthra @vbgl @kuznero

**Comment by kuznero** [comment]
I will try to have a look. Mono 52 is also in the pipeline.

**Comment by copumpkin** [comment]
We now have mono 5.4 in nixpkgs, but still no msbuild. From what I've been able to glean, `xbuild` is deprecated, but `msbuild` is still not bundled with the mono distribution. It's not clear to me how one is supposed to go from zero to a mono distribution with `msbuild` included but perhaps someone else knows? @kuznero?

**Comment by leo60228** [comment]
xbuild is missing some features and I can't build a project I'm working on. @kuznero

**Comment by copumpkin** [comment]
Here's what I found out when I asked about the switchover: https://github.com/mono/mono/issues/7068

It sounds like we should just create a `dotnetPackages.msbuild` and let them move independently.

**Comment by leo60228** [comment]
update on this?

**Comment by leo60228** [comment]
Won't be able to work on this for a week or two, but how would I go about fixing this?

**Comment by leo60228** [comment]
This should really be fixed.

**Comment by leo60228** [comment]
It uses a custom build system: https://github.com/Microsoft/msbuild/blob/master/build/build.sh

Any advice on packaging this? @copumpkin

**Comment by leo60228** [comment]
Here's the binaries used to bootstrap it: https://github.com/mono/msbuild/releases/download/0.06/mono_msbuild_xplat-master-3c930fa8.zip

**Comment by leo60228** [comment]
It appears to not use the system .NET Core for bootstrapping, which is inconvenient.

**Comment by leo60228** [comment]
Notes on manual compilation so far:

- dotnet-install is automatically downloaded every build, and attempts to download prebuilt .NET SDK binaries whether they're already installed or not. I fixed it by cancelling the download with Ctrl-C, commenting out the lines to actually install it, and using `chmod -w` to keep it from being redownloaded (as there's no error handling for curl in the build script)
- The bootstrapped MSBuild needs it's interpreters patched. This caused an error, so I just patched the interpreter manually.

**Comment by leo60228** [comment]
It was quite easy to install the MSBuild Ubuntu package into my home directory via GNU Stow. I don't know how to package a deb, and even then it's definitely not the right way to package an open-source utility. If anyone can give me any advice (either on packaging the deb or building in an FHS chroot), I'll package it, but it's not necessary for me right now.

**Comment by leo60228** [comment]
#43680

**Comment by leo60228** [comment]
This was fixed in #66299.

**Comment by jonas-schievink** [comment]
According to https://github.com/NixOS/nixpkgs/pull/66134#issuecomment-525492564, msbuild was packaged in https://github.com/NixOS/nixpkgs/pull/66299, and it looks like that's true:

https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/build-managers/msbuild/default.nix

I think this can be closed?
