### ISSUE TITLE
Build failure: jedi-language-server

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nixpkgs#298110]
### Steps To Reproduce

1. Checkout `nixos-unstable`
2. `nix build .#python311Packages.jedi-language-server`

Build also failed on hydra: https://hydra.nixos.org/build/253584341

### Build log

https://gist.github.com/iFreilicht/8ed71c7564a08706a3262001f1d3b450

### Additional context

I already found that this originated from [the commit upgrading `docstring-to-markdown` to 0.15](https://github.com/NixOS/nixpkgs/commit/7855a97f528d98cb45cac0abe3f787f9817039c0).
I confirmed this issue is present in [upstream](https://github.com/pappasam/jedi-language-server):

```
$ poetry update
Updating dependencies
Resolving dependencies... (10.7s)

Package operations: 0 installs, 1 update, 0 removals

  • Updating docstring-to-markdown (0.12 -> 0.15)

Writing lock file
$ make test
```

I tested and confirmed this failure on both darwin-aarch64 and linux-x86_64.

I will open an issue on upstream asking how they want to resolve this and link it here.

### Notify maintainers

@doronbehar

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Excuse me for not responding to this issue quickly, I was busy.. I understand you don't experience this issue anymore, you also mentioned that upstream in https://github.com/pappasam/jedi-language-server/issues/307 .. Please close the issue downstream as well :).
