### ISSUE TITLE
Build failure: fprintd-1.94.2

### ISSUE THREAD

**Issue by alyraffauf** [NixOS/nixpkgs#298150]
### Steps To Reproduce

1. Checkout `nixos-unstable`.
2. Run `nix build .#fprintd`.

### Build log

https://gist.github.com/alyraffauf/c60e205274d052a758e040c9d762ff2e

### Additional context

Also failed in [Hydra](https://hydra.nixos.org/build/253714077).

### Notify maintainers

@abbradar 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[aly@lavaridge:~] $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240316.c75037b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7ay2dd0w41iqvrnkx19v4vf4f5kkxvc2-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SebTM** [comment]
I was experiencing the same issue regardless of the nixpkgs-branch I'm using for fprintd. I've asked in the matrix channel and @NickCao came up with this overlay to skip the broken (timeout) test for the moment.

```
fprintd = prev.fprintd.overrideAttrs (_: { 
    mesonCheckFlags = [ 
      "--no-suite" "fprintd:TestPamFprintd"
    ]; 
  });
```
(currently testing)

**Comment by SebTM** [comment]
Worked for me after `nix-collect-garbage` maybe because of some dirty state from previous attempts.

**Comment by NickCao** [comment]
Addressed the pam rule issue with https://github.com/NixOS/nixpkgs/pull/298211

**Comment by alyraffauf** [comment]
> Addressed the pam rule issue with #298211

Having the same error building from this pull request.

**Comment by SebTM** [comment]
> > Addressed the pam rule issue with #298211
> 
> Having the same error building from this pull request.

How did you apply it? After applying it to my local-checkout of nixpkgs which I use to build my system from and updating flake inputs I was able to import `nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-23.11";` as second package-set and set `service.fprintd.package = <nixpkgs-stable import>.fprintd;` and was able to rebuild without applying above overlay.

**Comment by NickCao** [comment]
With https://github.com/NixOS/nixpkgs/pull/298211 merged, there is no longer a need for using an overlay to apply the workaroud, you may just set
```nix
services.fprintd.package = pkgs.fprintd.overrideAttrs {
  mesonCheckFlags = [
    "--no-suite"
    "fprintd:TestPamFprintd"
  ];
};
```

**Comment by hensou** [comment]
I'm also having the timeout issue, even with the workaround

**Comment by Myned** [comment]
If you're using the unstable channel, the [overlay](https://github.com/NixOS/nixpkgs/issues/298150#issuecomment-2015815945) still seems to be the best option until https://github.com/NixOS/nixpkgs/pull/298211 lands in unstable as otherwise it would require modifying the PAM module in addition to fprintd.

**Comment by TheStachelfisch** [comment]
> With #298211 merged, there is no longer a need for using an overlay to apply the workaroud, you may just set
> 
> ```nix
> services.fprintd.package = pkgs.fprintd.overrideAttrs {
>   mesonCheckFlags = [
>     "--no-suite"
>     "fprintd:TestPamFprintd"
>   ];
> };
> ```

Unfortunately, this still fails with timeout errors

**Comment by NickCao** [comment]
> Unfortunately, this still fails with timeout errors

You have to wait til it reaches your channel. See https://nixpk.gs/pr-tracker.html?pr=298211

**Comment by pnelson** [comment]
If you don't want to wait and don't actively use a fingerprint sensor `services.fprintd.enable = false;` has been working for me without any noticeable drawbacks.
