### ISSUE TITLE
Build failure: zitadel

### ISSUE THREAD

**Issue by ingon** [NixOS/nixpkgs#298204]
### Steps To Reproduce

1. build zitadel
```
≻ nix build nixpkgs#zitadel
```

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/6ch6h9v42m4h09ckpq394cd7pxqk3bh2-zitadel-buf-generated.drv':
         specified: sha256-3qDVY2CvtY8lZDr+p5i0vV6zZ5KyTtxBLyV7Os9KuIw=
            got:    sha256-ntIKudNFBs7kHjK7cfzbOfDCA6J8uvJRUbCTa6afK/I=
error: 1 dependencies of derivation '/nix/store/zzbd0wlbcbzw7zppakq62lwm3qigh299-zitadel.drv' failed to build
```

### Additional context

Also fails on unstable:
```
specified: sha256-NmlKjKWxmqatyR6OitlQ7bfl6U6PS6KWqTALwX42HS4=
   got:    sha256-In7H01NFjCpTYuGABxoquMzw4fKt7wUgCgDrOUhVrCs=
```

I saw previous reports of this failing similarly, so I think this package is actually not reproducible.

### Notify maintainers

@Sorixelle 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (1.11 MiB download, 6.93 MiB unpacked):
  /nix/store/4l09rh46bvvp84d8xm879zrqkix4cyy1-nix-info
  /nix/store/mm2mnl0n16gi56dh85xsp2wfbzfkw88w-bash-interactive-5.2-p15
copying path '/nix/store/mm2mnl0n16gi56dh85xsp2wfbzfkw88w-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/4l09rh46bvvp84d8xm879zrqkix4cyy1-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.148-2-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - channels(sungon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ingon** [comment]
Build passes based on: https://github.com/NixOS/nixpkgs/pull/298208

**Comment by TildeSlashC0re** [comment]
> Build passes based on: #298208
can confirm.

Switching to nixos-unstable channel solved the issue

**Comment by kashw2** [comment]
closing as this isn't reproducible with current nixpkgs HEAD and the reproduction steps provided
