### ISSUE TITLE
Android NDK 26.1.10909125 is broken

### ISSUE THREAD

**Issue by mukilan** [NixOS/nixpkgs#298285]
### Describe the bug
The prebuilt clang and llvm binaries from the NDK are broken

### Steps To Reproduce
1. Create a shell.nix file with the following contents:
```
with (import <nixpkgs> ) {
  config = {
    android_sdk.accept_license = true;
    allowUnfree = true;
  };
};
let
    androidComposition = androidenv.composeAndroidPackages {
      platformVersions = [ "34" ];
      includeNDK = true;
      ndkVersion = "26.1.10909125";
      abiVersions = [ "x86_64" ];
  };
  androidSdk = androidComposition.androidsdk;
in
stdenv.mkDerivation {
  name = "test-env";

  buildInputs = [
    androidSdk
  ];

  ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
  ANDROID_NDK_ROOT = "${ANDROID_SDK_ROOT}/ndk-bundle";
}

```
2. Run `nix-shell --run '$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -v`

The command fails with
```
/nix/store/63n1qzkph1l7hcvsskd4k1ka1c5iwjlf-androidsdk/libexec/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

### Expected behavior
`clang -v` in step 2 above exits successfully and prints the clang version information.

### Additional context

I think the bug is because the NDK layout has changed in `26.1.10909125` - the `lib64` folder is no longer present under `toolchains/llvm/prebuilt/linux-x86_64`. There is only a `lib` folder under that path and it does contain a symlink to the `libc++.so.1`.  The previous NDK versions have both `lib` and `lib64`, with `lib64` containing all shared objects needed by the binaries.

Currently in nixpkgs, when patching the toolchain binaries, only [ `lib64` is added to the autoPatchElfSearchPath](https://github.com/NixOS/nixpkgs/blob/476a33c53da66a2a77a89bb9bcf54d5e3c232c3d/pkgs/development/mobile/androidenv/ndk-bundle/default.nix#L23).

### Notify maintainers
I couldn't find the maintainer for this package, so I'm notifiying @hadilq as they are the last to touch default.nix. Please let me know if someone else needs to be tagged here.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.7, NixOS, 23.11 (Tapir), 23.11.20240304.617579a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-hardware, unstable"`
 - nixpkgs: `/etc/channels/nixpkgs`
```

**Comment by hadilq** [comment]
Thank you for your contribution. I'll take a look this week.

**Comment by hadilq** [comment]
@mukilan please review https://github.com/NixOS/nixpkgs/pull/300386
