### ISSUE TITLE
nix-shell with python env, wrong documentation?

### ISSUE THREAD

**Issue by berdario** [NixOS/nixpkgs#29822]
## Issue description

it seems that it should be possible to do 

    nix-shell -p 'python35.withPackages(ps: with ps; [ numpy toolz ])'

but [the documentation](https://github.com/NixOS/nixpkgs/blame/9d9a28f/doc/languages-frameworks/python.md#L115) is wrong, since I get this error:

    undefined variable ‘python35’ at (string):1:1

(same with python36)

## Technical details

* System: Darwin
* Nix version: 1.11.14
* Nixpkgs version: ec075b40ec5127cd1dc42601309e32254c00a993

**Comment by FRidh** [comment]
Does `nix-shell -p python35` work for you? If that's the case, then at least you have the right attribute.

In any case, this command works for me, though I recall someone mentioning it did not work.

**Comment by berdario** [comment]
Yup, `nix-shell -p python35 ` works just fine

**Comment by FRidh** [comment]
Odd. And `nix-shell -p 'python35'`?

**Comment by berdario** [comment]
That wouldn't be different at all, would it? The shell should parse both in
the exact same way

The problem is with the -E option

**Comment by FRidh** [comment]
Well, I would hope that would work as well. But if it doesn't, then that at least gives a hint as to what is broken.

**Comment by berdario** [comment]
Oh, I got it... I copypasted only the `'python35.withPackages(ps: with ps; [ numpy toolz ])'` part when I tried out the command, but otherwise I typed the nix-shell command manually...

and knowing that `-E` is for expression... and that `-p` is not usually used with nix expression arguments...

I tried to run

    nix-shell -E 'python35.withPackages(ps: with ps; [ numpy toolz ])'

instead of

    nix-shell -p 'python35.withPackages(ps: with ps; [ numpy toolz ])'

**Comment by torbeneims** [comment]
I am getting mostly the same error:
![image](https://github.com/NixOS/nixpkgs/assets/63680413/4aae8784-332f-48e4-993a-9349d395008a)

Does anyone know what causes this or what to look into?

**Comment by FRidh** [comment]
Yes, `python35` has been removed from Nixpkgs already a long time ago. Try a newer interpreter.
