### ISSUE TITLE
Package request: ollama-js

### ISSUE THREAD

**Issue by Kahlenden** [NixOS/nixpkgs#298315]
**Project description**

Package request: nodePackages.ollama

**Metadata**

* homepage URL: https://github.com/ollama/ollama-js/
* source URL: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/node-packages/node-packages.nix
* license: MIT
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
Why do you want ollama-js to be packaged in nixpkgs? What use case does that enable for you, in what ways can it be used? From what I can tell, ollama-js is just a library; I'm not even sure how js libraries packaged in nix can be used, or if they can be at all.

If no answer is received within a month, I'll be closing the issue.
