### ISSUE TITLE
Package request: bilibili-linux

### ISSUE THREAD

**Issue by MarkGhanz** [NixOS/nixpkgs#298362]
**bilibili-linux**

A Linux port of the proprietary app of an online video sharing and social platform in China. Electron based. Looks proprietary but actually the opposite. The README is in Chinese, so translation is necessary for reading it.

**Metadata**

* homepage URL: https://github.com/msojocs/bilibili-linux.git
* source URL: https://github.com/msojocs/bilibili-linux.git
* license: MIT
* platforms: Linux

---

**Comment by wegank** [comment]
https://search.nixos.org/packages?channel=unstable&show=bilibili&from=0&size=50&sort=relevance&type=packages&query=bilibili
