### ISSUE TITLE
Update request: warp-terminal v0.2024.03.19.08.01.stable_01 Linux x86_64

### ISSUE THREAD

**Issue by JohnRTitor** [NixOS/nixpkgs#298311]
- Package name: warp-terminal (x86_64)
- Latest released version: 0.2024.03.12.08.02.stable_01
- Current version on the unstable channel: 0.2024.03.12.08.02.stable_01
- Current version on the stable/release channel: 0.2023.11.07.08.02.stable_00

Warp terminal has been released for Linux as of February 2024.
This request is to add the x86_64 Linux package. Current build on nixpkgs is only for darwin.

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@imadnyc @emilytrau @rawkode @Enzime 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

**Comment by a-n-n-a-l-e-e** [comment]
https://github.com/NixOS/nixpkgs/issues/297943

**Comment by JohnRTitor** [comment]
@a-n-n-a-l-e-e  Can this be backported to 23.11 stable branch?

**Comment by a-n-n-a-l-e-e** [comment]
sure. https://github.com/NixOS/nixpkgs/pull/298389
