### ISSUE TITLE
Google earth package is limited to only i686 at all-packages.nix (but the expression appears to support x86-64)

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#29832]
Currently on master:

```
pkgs/top-level/all-packages.nix
14780:  googleearth = callPackage_i686 ../applications/misc/googleearth { };
```

I can add a PR to prefer a non i686 callPackage, but I was also wondering how you could do a package override to override `callPackage_i686`?

**Comment by matthewbauer** [comment]
I think you are misunderstanding what "callPackage_i686" does. It just tells Nixpkgs to pull in dependencies from i686 (but it should work still on x86_64). This is fairly common to have to do with nonfree software binaries.
