### ISSUE TITLE
Update request: itch 26.1.3 → 26.1.5

### ISSUE THREAD

**Issue by Anderssorby** [NixOS/nixpkgs#298410]
- Package name: itch
- Latest released version: 26.1.3
- Current version on the unstable channel: 26.1.3
- Current version on the stable/release channel: 26.1.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

The current version is broken since butler is marked broken
`Package ‘butler-15.21.0’ in /nix/store/1j3fh7fkb0gy13jbpfsvylpxqpwn2fxp-source/pkgs/by-name/bu/butler/package.nix:45 is marked as broken, refusing to evaluate.`

**Notify maintainers**
@pasqui23 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
The latest version on https://itchio.itch.io/kitch seems to be 26.1.3 which is used in the package.

**Comment by raspher** [comment]
There is 26.1.5 as a source code https://github.com/itchio/itch/releases, but current package uses binaryBytecode https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/it/itch/package.nix
