### ISSUE TITLE
Update request: hyprland 0.36.0 → 0.37.1

### ISSUE THREAD

**Issue by etrigan63** [NixOS/nixpkgs#298422]
- Package name:hyprland
- Latest released version: 0.37.1

- Current version on the unstable channel:0.36.0
- Current version on the stable/release channel:0.32.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@wozeparrot 
@fufexan 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fufexan** [comment]
> Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Clearly you didn't.

https://github.com/NixOS/nixpkgs/pull/296446

**Comment by etrigan63** [comment]
> > Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
> 
> Clearly you didn't.
> 
> #296446

I did. It did not occur to me to look at the closed ones as the nixpkgs search returns 0.36.0 in the unstable branch leading one to believe that no one had submitted an update request. What is the delay between PR merge and the search page reflecting the change?

**Comment by fufexan** [comment]
> I did. It did not occur to me to look at the closed ones as the nixpkgs search returns 0.36.0 in the unstable branch leading one to believe that no one had submitted an update request.

Ah. Apologies for being snarky then.

> What is the delay between PR merge and the search page reflecting the change?

PRs merged in master usually land in `nixos-unstable` in `2-7` days, depending on the load on Hydra. You can track the progress [here](https://nixpk.gs/pr-tracker.html?pr=296446).
