### ISSUE TITLE
Package request: keydb

### ISSUE THREAD

**Issue by tcurdt** [NixOS/nixpkgs#298493]
**Project description**

Keydb is a fork of Redis with some (supposed) major improvements.
Given the current Redis license changes this might be good to have available as an alternative.

**Metadata**

* homepage URL: https://docs.keydb.dev/
* source URL: https://github.com/Snapchat/KeyDB
* license: bsd3
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by shyim** [comment]
Maybe we can package redict? https://codeberg.org/redict/redict/releases 🤔

**Comment by tcurdt** [comment]
> Maybe we can package redict? https://codeberg.org/redict/redict/releases 🤔

If anyone is eager I am sure both would be great - but it seems like KeyDB has more traction.

**Comment by mlazowik** [comment]
Resolved via https://github.com/NixOS/nixpkgs/pull/301804?

**Comment by shyim** [comment]
Thanks
