### ISSUE TITLE
Policy on checks/logic in stdenv.mkDerivation

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#29847]
According to https://github.com/NixOS/nixpkgs/pull/17886#issuecomment-243241309 and https://github.com/NixOS/nixpkgs/pull/25304#issuecomment-298310989, logic in `mkDerivation` seems discouraged on the basis of increased evaluation time. However, since 17.09 we seem to have grown at least these new ones:

https://github.com/NixOS/nixpkgs/blob/51179c6e888b03ae3b42f67e2bc85ca0112d7677/pkgs/stdenv/generic/make-derivation.nix#L50-L57

and

https://github.com/NixOS/nixpkgs/blob/51179c6e888b03ae3b42f67e2bc85ca0112d7677/pkgs/stdenv/generic/make-derivation.nix#L114-L121

I don't know if "bloat" in `mkDerivation` is still considered a problem or not, but if it is this probably deserves documenting somewhere and making sure that the policy is applied consistently.

**Comment by edolstra** [comment]
Yeah, it's better to do such checks in the builder.

**Comment by abathur** [comment]
Closing since it sounds like Eelco answered the question, but I'm happy to reopen if you disagree.
