### ISSUE TITLE
Update request: cloudflared 2024.2.1 → 2024.3.0

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#298625]
- Package name: cloudflared
- Latest released version: 2024.3.0
- Current version on the unstable channel: 2024.2.1
- Current version on the stable/release channel: 2024.1.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@bbigras @enorris @thoughtpolice @piperswe @qjoly

**Comment by JohnRTitor** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/298579
