### ISSUE TITLE
Fluidsynth MIDI port not detected in Bottles / Heroic  / possibly other launchers

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#298672]
### Describe the bug
Fluidsynth's MIDI port is not being detected in the nix versions of Bottles or Heroic. However, in Lutris (nix version), sys-wine (wineWowPackages.stagingFull), Steam (as non-Steam game), distroboxes, appimage, and Flatpak, Fluidsynth is detected and works as expected. I'm determining this with System Shock: Enhanced Edition.

The game shows 'invalid' when selecting audio devices (screenshots below).

In the Wine/Proton logs, this error shows:
```
LSA lib conf.c:4122:(config_file_open) cannot access file /etc/alsa/conf.d/10-speexrate.conf
ALSA lib conf.c:4042:(snd_config_hooks_call) function snd_config_hook_load returned error: No such file or directory
ALSA lib conf.c:4649:(snd_config_update_r) hooks failed, removing configuration
0124:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```

I'm using Fluidsynth as a home-manager option:

``` nix
  services = {
    fluidsynth = {
      enable = true;
      extraOptions = [
        "--gain 1.0"
      ];
      soundFont = "/home/keenan/Music/soundfonts/default.sf2";
      soundService = "pipewire-pulse";
    };
  };
```

However, the issue happens as a system-wide package or running in non-daemon mode. I've tried all sorts of switches (ALSA mode, PulseAudio mode, etc.) but the issue always happens. I'm running Pipewire.

It's not an issue specific to System Shock, as I've tested another game (Necrodome) and it isn't detected either. Out of curiosity, I tried with TiMidity++ and it was the same issue. I also tried the nix [DOSBox Staging](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/do/dosbox-staging/package.nix), which read the port with no problem.

I'm assuming fluidsynth needs to be added to the FHS of these packages.

### Steps To Reproduce
1. Install/run Bottles or Heroic
2. Install/run Fluidsynth as a daemon or manually
3. Install System Shock: Enhanced Edition (or any other ancient game that would use Fluidsynth) in Bottles or Heroic
4. Launch game and see invalid device / don't hear music.

### Expected behavior

They should detect the Fluidsynth MIDI port.

### Screenshots
Bottles, Heroic (nix package):
![Screenshot_20240324_100704](https://github.com/NixOS/nixpkgs/assets/37268985/41cacd32-8ba0-4773-a24a-361a7fc42b64)

Flatpak, appimage, Distrobox, Wine, Steam non-Steam game, & Lutris (nix packages):

![Screenshot_20240324_100913](https://github.com/NixOS/nixpkgs/assets/37268985/b364a064-a4b3-4595-976e-674320104845)

### Additional context
Fluidsynth operates as normal when using commands like `aplaymidi -p128:0 example.mid`

Output of `aconnect -o`:
```
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'FLUID Synth (3621)' [type=user,pid=3621]
    0 'Synth input port (3621:0)'
```
### Notify maintainers

@aidalgol @SuperSamus (in lieu of absent Bottles maintainers)

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05.20240323.44d0940`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aidalgol** [comment]
Does it work if you override `heroic` to add `fluidsynth`?
```nix
(heroic.override {
  extraLibraries = pkgs: [
    pkgs.fluidsynth
  ]
})
```

**Comment by keenanweaver** [comment]
Unfortunately does not resolve it.

**Comment by SuperSamus** [comment]
Maybe it's because of #224410?

**Comment by aidalgol** [comment]
> Maybe it's because of #224410?

Sounds quite likely, but I have no way to say for sure.  Thanks for linking that, though.  I'll keep an eye on it.

**Comment by keenanweaver** [comment]
> Maybe it's because of #224410?

You were right! Working perfectly now after https://github.com/NixOS/nixpkgs/pull/286360 was merged.

**Comment by xdanep** [comment]
How did you solve it? I have the same issue on Arch Linux

**Comment by keenanweaver** [comment]
> How did you solve it? I have the same issue on Arch Linux

If you're using the AUR version of Bottles, that could be why. Upstream only officially supports the flatpak version. Try on the flatpak.

**Comment by xdanep** [comment]
> > How did you solve it? I have the same issue on Arch Linux
> 
> If you're using the AUR version of Bottles, that could be why. Upstream only officially supports the flatpak version. Try on the flatpak.

I'm using the Flatpak version. I tried a lot of things but nothing works
