### ISSUE TITLE
package set for standalone manpages

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#298727]
currently, most of sections 2-7 are pretty barren, and a lot of basic info easily accessible on most linux distros is completely unavailable (eg. `man ascii`, libc manpages).

i propose a `manPages` package set, that would allow installing these, but also the `man` outputs of other packages.

**Comment by eclairevoyant** [comment]
The `man-pages` package covers what I believe you're looking for.

**Comment by lolbinarycat** [comment]
thanks!
