### ISSUE TITLE
Package request: Lorien

### ISSUE THREAD

**Issue by CrumblyLiquid** [NixOS/nixpkgs#298753]
**Project description**
Lorien is an infinite canvas drawing/note-taking app that is focused on performance, small savefiles and simplicity.

**Metadata**
* homepage URL: https://github.com/mbrlabs/Lorien
* source URL: https://github.com/mbrlabs/Lorien
* license: mit
* platforms: windows, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CrumblyLiquid** [comment]
I've found a game with Godot that could be used as inspiration: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/oh-my-git/default.nix

**Comment by wegank** [comment]
Already packaged: https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=lorien
