### ISSUE TITLE
paperless-ngx is broken with uvicorn >0.25

### ISSUE THREAD

**Issue by eliasp** [NixOS/nixpkgs#298719]
### Describe the bug
When running paperless-ngx with a location like `/paperless`, current unstable and master will cause it to break.
See also this upstream issue: https://github.com/paperless-ngx/paperless-ngx/issues/5494

### Steps To Reproduce
1. Configure paperless to use `/paperless` as location:
  ```Nix
  services.paperless.extraConfig = {
    PAPERLESS_STATIC_URL = "/paperless/static";
    PAPERLESS_FORCE_SCRIPT_NAME = "/paperless";
  };
  ```
2. Try to access `/paperless`

### Expected behavior
The login screen should be shown

### Screenshots
The client is redirected infinitely.

### Additional context
This can be solved by using uvicorn <= 0.25, which doesn't include the [updated `root_path` handling](https://github.com/encode/uvicorn/pull/2213) yet, to match the [upstream `Pipfile.lock`](https://github.com/paperless-ngx/paperless-ngx/blob/dev/Pipfile.lock#L1996-L2006).

### Notify maintainers
@leona-ya 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eliasp** [comment]
https://github.com/eliasp/nixpkgs/commit/8d7a7503fe8867b92c2d3061d546d17b29a9dc37 fixes it for me, but I feel like this quick hack isn't good enough for a PR - feel free to take it from here.

**Comment by leona-ya** [comment]
Thanks for the report! I will open a PR for that

**Comment by dotlambda** [comment]
Can't we fix this in our NixOS module? And maybe a NixOS test for this would be good.

**Comment by leona-ya** [comment]
I agree a NixOS test would be good.
What do you mean with a fix in the module? The module doesn't configure nginx (and I think it shouldn't) and then I see no other way than pinning uvicorn?

**Comment by dotlambda** [comment]
> What do you mean with a fix in the module? The module doesn't configure nginx (and I think it shouldn't) and then I see no other way than pinning uvicorn?

I didn't read the upstream issue carefully but it sounded like setting some environment variables also fixes this.

**Comment by eliasp** [comment]
I added tests in https://github.com/eliasp/nixpkgs/commit/850edcf2428246e9ec3d5441887ad9b283650483
Feel free to integrate them & improve when needed.

**Comment by fin444** [comment]
> it sounded like setting some environment variables also fixes this

As best as I can tell, what happened is that Uvicorn now prefixes all requests made to Paperless with the `PAPERLESS_FORCE_SCRIPT_NAME` (previously, `/paperless/blahblah` would be rewritten to `/blahblah` but now it's not), this rewriting is now supposed to be done on Paperless's end (for spec reasons I guess). Which means that you can't fix this with an environment variable, and they are going to be pinning Uvicorn to 0.25 until they do a pretty sizeable rewrite.

**Comment by dotlambda** [comment]
> I added tests in [eliasp@850edcf](https://github.com/eliasp/nixpkgs/commit/850edcf2428246e9ec3d5441887ad9b283650483)
> Feel free to integrate them & improve when needed.

Mind opening a PR for them?
