### ISSUE TITLE
Is not possible to remove / disable Modem Manager

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#298741]
### Describe the bug
Is not possible to remove modemmanager

### Steps To Reproduce
1.
```
environment.gnome.excludePackages = with pkgs; [
  modemmanager
];

or

services.xserver.excludePackages = with pkgs; [
  modemmanager  
];
```
2. sudo nixos-rebuild switch 
3.
```
● ModemManager.service - Modem Manager
     Loaded: loaded (/etc/systemd/system/ModemManager.service; enabled; preset: enabled)
    Drop-In: /nix/store/c1gmki530v0pnnvawlzjxmr4qlkck3rj-system-units/ModemManager.service.d
             └─overrides.conf
     Active: active (running) since Sun 2024-03-24 19:07:54 CET; 3h 20min ago
   Main PID: 15571 (ModemManager)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
      Tasks: 4 (limit: 18999)
     Memory: 2.3M (peak: 3.1M)
        CPU: 175ms
     CGroup: /system.slice/ModemManager.service
             └─15571 /nix/store/r8makyq7kwn9mj3b54bagjcfyghjg9kj-modemmanager-1.22.0/sbin/ModemManager

mar 24 19:07:53 nixos systemd[1]: Starting Modem Manager...
mar 24 19:07:53 nixos ModemManager[15571]: <msg> ModemManager (version 1.22.0) starting in system bus...
mar 24 19:07:54 nixos systemd[1]: Started Modem Manager.
mar 24 19:07:58 nixos ModemManager[15571]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.2/0000:02:00.0': not s>
mar 24 19:07:58 nixos ModemManager[15571]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1f.6': not supported by 

```

### Expected behavior
Modem Manager should be removed

### Notify maintainers

@jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
kamilcynk@nixos nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre601756.44d0940ea560`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
You cannot really expect `excludePackages` to remove whatever package you want, you always need to check the module definitions.

In this case, ModemManager is brought in by NetworkManager and there is no option to disable it:

https://github.com/NixOS/nixpkgs/blob/94faf6bd44de4d4ff8da8382a847249f6d2bd589/nixos/modules/services/networking/networkmanager.nix#L136

Other than disabling NetworkManager itself:

https://github.com/NixOS/nixpkgs/blob/85a4ee7da66c15d6756a337e92cc19493b5f1d01/nixos/modules/services/x11/desktop-managers/gnome.nix#L358

If you want to make it optional, someone will need to research what effect the removal will have and then introduce an option to the NetworkManager NixOS module.

**Comment by KCynk** [comment]
> You cannot really expect `excludePackages` to remove whatever package you want, you always need to check the module definitions.
> 
> In this case, ModemManager is brought in by NetworkManager and there is no option to disable it:
> 
> https://github.com/NixOS/nixpkgs/blob/94faf6bd44de4d4ff8da8382a847249f6d2bd589/nixos/modules/services/networking/networkmanager.nix#L136
> 
> Other than disabling NetworkManager itself:
> 
> https://github.com/NixOS/nixpkgs/blob/85a4ee7da66c15d6756a337e92cc19493b5f1d01/nixos/modules/services/x11/desktop-managers/gnome.nix#L358
> 
> If you want to make it optional, someone will need to research what effect the removal will have and then introduce an option to the NetworkManager NixOS module.

Thank you for answer, you are right but looks like is not possible also to disable this service. On each my Fedora setup i disiable all not necessary services like this one and looks like on nixos this is not possible.
Currently is possible to stop the service but is not possible to disable it. More details below
```
kamilcynk@nixos sudo systemctl stop ModemManager
Warning: The unit file, source configuration file or drop-ins of ModemManager.service changed on disk. Run 'systemctl daemon-reload' to reload units.
kamilcynk@nixos sudo systemctl daemon-reload
kamilcynk@nixos sudo systemctl status ModemManager
○ ModemManager.service - Modem Manager
     Loaded: loaded (/etc/systemd/system/ModemManager.service; enabled; preset: enabled)
    Drop-In: /nix/store/c1gmki530v0pnnvawlzjxmr4qlkck3rj-system-units/ModemManager.service.d
             └─overrides.conf
     Active: inactive (dead)

mar 24 22:34:03 nixos ModemManager[1985]: <msg> ModemManager (version 1.22.0) starting in system bus...
mar 24 22:34:03 nixos systemd[1]: Started Modem Manager.
mar 24 22:34:07 nixos ModemManager[1985]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.2/0000:02:00.0': not supported by any plugin
mar 24 22:34:07 nixos ModemManager[1985]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1f.6': not supported by any plugin
mar 24 23:57:38 nixos ModemManager[1985]: <msg> caught signal, shutting down...
mar 24 23:57:38 nixos systemd[1]: Stopping Modem Manager...
mar 24 23:57:38 nixos ModemManager[1985]: <msg> ModemManager is shut down
mar 24 23:57:38 nixos systemd[1]: ModemManager.service: Deactivated successfully.
mar 24 23:57:38 nixos systemd[1]: Stopped Modem Manager.
mar 24 23:57:38 nixos systemd[1]: ModemManager.service: Consumed 147ms CPU time, 8.7M memory peak, 0B memory swap peak, read 11.0M from disk, written 0B to disk, no IP traffic.
kamilcynk@nixos sudo systemctl disable ModemManager
Failed to disable unit: File /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service: Read-only file system

**Comment by dotlambda** [comment]
> Currently is possible to stop the service but is not possible to disable it. More details below

You should set `networking.networkmanager.enable = false`.

**Comment by KCynk** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/41055
