### ISSUE TITLE
GPG without GTK2

### ISSUE THREAD

**Issue by valeriangalliat** [NixOS/nixpkgs#29875]
## Issue description

By default installing GPG on a headless server pulls GTK2.

### Steps to reproduce

1. Install GPG on a 17.03 system which doesn't have GTK2.

#### What happens

GTK2 is installed (actually, even compiled).

#### What should have happened

GTK2 is not installed.

## Technical details

* System: building with NixOS 17.03
* Nix version: 1.11.8
* Nixpkgs version: "17.03.1861.ad6265dbfa"
* Sandboxing enabled: no

---

I'm not sure if I'm doing everything right, but I'm running on `nixos-17.03-small`, I even import `<nixpkgs/nixos/modules/profiles/minimal.nix>` in my configuration, but by default installing GPG (in my case through SpamAssassin) pulls GTK2 in my system.

Is there a flag to specify that I do not want any graphic libraries on this system?

Currently I did the following to prevent that:

```nix
nixpkgs.config.packageOverrides = pkgs: {
  pinentry = pkgs.pinentry.override {
    gtk2 = null;
    qt4 = null;
  };
};
```

**Comment by globin** [comment]
We already have `environment.noXlibs = true;` for this, this might be good to add to the minimal profile if that is guaranteed to not be pulled in by graphical environments. Feel free to open a PR for this.

**Comment by valeriangalliat** [comment]
Oh, thank you!

I tried `environment.noXlibs = true` but it still tries to pull GTK without my patch though. :/
