### ISSUE TITLE
hdf5 pulls in gcc-wrapper

### ISSUE THREAD

**Issue by shajra** [NixOS/nixpkgs#29889]
## Issue description

The hdf5 library pulls in gcc-wrapper as a transitive dependency, which seems less than ideal.

The problem is that the build creates this text file summary of the build in lib/libhdf5.settings, that has the following:

```
Compiling Options:
------------------
               Compilation Mode: production
               C Compiler: /nix/store/kd7vb1afwvm2k65n9qjdw767w6lnwsrd-gcc-wrapper-6.4.0/bin/gcc ( gcc (GCC) 6.4.0)
               CFLAGS:
               ...
```

Additionally, this same text is embedded as a string in one of the shared libraries (lib/libhdf5.so.10.2.1).

The reason this is annoying for me is that I use transitive closures to bundle minimized tarballs, which I then put into Docker.  But now gcc is grabbed, just because someone put in a informational string of which compiler was used.

I still have to go through the hdf5 source code and see if there's a simple fix.  I could use the replace-literal utility to crop off the "/nix/store" from the reference in the shared library (maybe... not sure how tricky that might be).  It's certainly easier to modify the libhdf5.settings file.

I'm open to other ideas.

### Steps to reproduce

```
nix-store -qR "$(nix-build -E '(import <nixpkgs> {}).hdf5' --no-link)" | grep gcc-wrapper
```
yields

```
/nix/store/kd7vb1afwvm2k65n9qjdw767w6lnwsrd-gcc-wrapper-6.4.0
```
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

Debian testing with Nix

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.14

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"18.03pre116475.d757d8142e"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

build-use-sandbox = true

**Comment by orivej** [comment]
Here `removeReferencesTo` is more appropriate than `replace-literal`.

**Comment by shajra** [comment]
@orivej cool, I just did that and it worked pretty well.  I'll have a PR made up shortly and link to this ticket.

**Comment by shajra** [comment]
@FRidh thanks for taking care of the recommended changes (I was sleeping).  I need to look up again the difference between native and normal build inputs.  I still get confused about the difference.

**Comment by oxij** [comment]
A fun problem found via `doCheckByDefault`. With 82667fee37e306deb20cf7abdfe9ed0b896a7183 applied `h5cc` fails with

```
h5cc: line 318: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-gcc-wrapper-7.3.0/bin/gcc: No such file or directory
```

in installcheck phase, and this `eeeeeeeeeeeeeeeee*` is made by `remove-references-to`.

I guess nobody uses binaries this package has in nixpkgs, but having those be broken by default isn't nice, I think.

I can't reopen this, but I suggest doing so and solving this by splitting the package into multiple outputs or something.

**Comment by Artturin** [comment]
No longer
