### ISSUE TITLE
Package request: Windscribe VPN

### ISSUE THREAD

**Issue by mystic-githuber** [NixOS/nixpkgs#298871]
Windscribe VPN

Opensource VPN that's an alternative to Proton, iVPN and Mullvad

**Metadata**

* homepage URL: https://windscribe.com/
* source URL: https://github.com/Windscribe/Desktop-App
* license: GPL-2.0 license 
* platforms: Ubuntu, Fedora, Arch

---

**Comment by pluiedev** [comment]
Duplicate of #158368
