### ISSUE TITLE
Python: bytecode in /bin

### ISSUE THREAD

**Issue by casey** [NixOS/nixpkgs#29896]
I just noticed that a `__pycache__` symlink had made it into my `/run/current-system/sw/bin` directory. It points to `/nix/store/$HASH-python3-3.6.2-env/bin/__pycache__`. Here's a listing of the contents: https://gist.github.com/casey/cf97e5abcdf5fee3a0f50ec9b03d5b38

I think this is a new issue. Python 3.6.2 was released on 2017-07-17, so I'm gussing it has to do with that. These files are not directly executable, so it should probably be filtered out of `bin`

Is the right way to fix this just to remove the directory in `postInstall`? Like so:

```
rm -r $out/bin/__pycache__
```

Happy to open PR if that's correct.

Pinging some of the package maintainers:
@chaoflow @domenkozar 

System information:
```
NixOS version: 18.03.git.a75265924f (Impala)
nix-env version: nix-env (Nix) 1.11.15
nixpkgs version: 18.03.git.a75265924f
build-use-sandbox: true
```

**Comment by FRidh** [comment]
The reason this cache is created is because some of the files in `/bin` are scripts that end with `.py`. In case of Python 2 you will see `.pyc` files. This is an upstream issue.

We could however choose to remove the bytecode, but it would have a performance impact.

**Comment by casey** [comment]
Would it be possible not to remove `__pycache__`, but just not symlink it into place?

**Comment by FRidh** [comment]
That defies the purpose; then you may as well just remove it.

**Comment by casey** [comment]
I was thinking that you might be able to leave it in the originating package's nixstore directory, but leave it out of `/run/current-system/sw/bin` and it might still be able to find it, but looking at the structure of symlinks and wrappers, it looks like that might not be the case.


I guess I'll close,

**Comment by casey** [comment]
I was thinking that you might be able to leave it in the originating package's nixstore directory, but leave it out of `/run/current-system/sw/bin` and it might still be able to find it, but looking at the structure of symlinks and wrappers, it looks like that might not be the case.

The main reason that this irritates me is that it shows up as the first entry in my command launcher. Since it's only a few python binaries (and not libraries) that are responsible for this, I would be in favor of just removing it. However, perhaps others won't agree that it's worth the performance hit.

What do you think?

**Comment by FRidh** [comment]
After having given it some thought I think we should add a default option in the `fixupPhase` to remove bytecode that is present in `/bin`. While its understandable why these files are created, they do not not belong there.

**Comment by casey** [comment]
I'm currently testing a patch, but it looks like it rebuilds the world so it'll take a while before I can actually submit a PR.

But in the mean time, does this look right to you?

https://github.com/casey/nixpkgs/commit/720dc76b741a36b324ea894cb7a7aef5136a0594

**Comment by FRidh** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/32542.
