### ISSUE TITLE
programs.steam.extraCompatPackages not propagating STEAM_EXTRA_COMPAT_TOOLS_PATHS

### ISSUE THREAD

**Issue by anthr76** [NixOS/nixpkgs#298919]
### Describe the bug
`programs.steam.extraCompatPackages` worked for a little while but seems to stopped working

### Steps To Reproduce
1. Consider steam module:
```
  programs.steam = {
    enable = true;
    gamescopeSession.enable = true;
    extest.enable = true;
    package = pkgs.steam.override {
      extraPkgs = pkgs:
        with pkgs; [
          liberation_ttf
          wqy_zenhei
        ];
    };
    extraCompatPackages = with pkgs; [
      proton-ge-bin
    ];
  };
```

Observe 

```
steam-run echo $STEAM_EXTRA_COMPAT_TOOLS_PATHS
ERROR: ld.so: object '/nix/store/brl34phbkm5j29lfnq5vagalx5pc89ns-extest-1.0.2/lib/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

The environment variable is missing and it doesn't show up in steam.

### Expected behavior
`STEAM_EXTRA_COMPAT_TOOLS_PATHS` should be present for Steam

### Additional context
This was working for a few days I'm not sure what changed.

### Notify maintainers

@NotAShelf 
@Atemu 
@Shawn8901 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240323.44d0940`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
Searching it in printenv works fine for me
```
steam-run printenv | grep STEAM_EXTRA_COMPAT_TOOLS_PATHS
STEAM_EXTRA_COMPAT_TOOLS_PATHS=/nix/store/zfnq66cd2rw0khrgsh82vhfdig3r2dac-proton-ge-bin-GE-Proton9-1-steamcompattool/
```
But i can also confirm that its not visible via `echo $STEAM_EXTRA_COMPAT_TOOLS_PATHS`
Can you confirm so war that its also set?

**Comment by Atemu** [comment]
Make sure you're not adding the regular steam package to systemPackages; it may override any modifications done in `programs.steam`.

I've seen that anti-pattern employed before, we should probably disallow it somehow or nullify the negative effects. Perhaps we could give the option's steam package a higher priority for instance; buildEnv will use that one instead then.

**Comment by anthr76** [comment]
Curiously I just tried to set 

```
      extraEnv = {
        STEAM_FORCE_DESKTOPUI_SCALING = "1.5";
      };
```

and that environment variable is missing from steam as well

**Comment by Shawn8901** [comment]
is your config available for eval somewhere?

**Comment by anthr76** [comment]
Yes it is. 

https://github.com/anthr76/snowflake/blob/main/nixos/personalities/desktop/gaming.nix


You'll have to drop `gaming-kernel.enable = true;` as it's apart of a module.

**Comment by anthr76** [comment]
I just fully removed the `programs.steam` block and confirmed I don't have steam in my $PATH or desktop.

**Comment by anthr76** [comment]
Okay I think I found it. This seems to happen when `programs.steam.extest.enable` is enabled.

I guess this is overwriting? https://github.com/NixOS/nixpkgs/blob/d9171cf69066599d8fa2a7d55f6e3b4f8958678e/nixos/modules/programs/steam.nix#L62-L64

**Comment by Shawn8901** [comment]
I submitted a PR that hopefully should fix extests extraEnv. Could you verify if that fixes the problem for you?

**Comment by anthr76** [comment]
Confirmed this solves the issue:

```shell
steam-run printenv | grep STEAM
ERROR: ld.so: object '/nix/store/brl34phbkm5j29lfnq5vagalx5pc89ns-extest-1.0.2/lib/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
STEAM_LD_LIBRARY_PATH=/lib64:/lib32:/steamrt/amd64/lib/x86_64-linux-gnu:/steamrt/amd64/lib:/steamrt/amd64/usr/lib/x86_64-linux-gnu:/steamrt/amd64/usr/lib:/steamrt/i386/lib/i386-linux-gnu:/steamrt/i386/lib:/steamrt/i386/usr/lib/i386-linux-gnu:/steamrt/i386/usr/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib
STEAM_FORCE_DESKTOPUI_SCALING=1.5
STEAM_EXTRA_COMPAT_TOOLS_PATHS=/nix/store/ra686qnhxflajwcy5a143rkn652kwa9m-proton-ge-bin-GE-Proton9-1-steamcompattool/
```

Thanks for the help!
