### ISSUE TITLE
Documentation: MediaWiki

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#298902]
## Problem
In accordance with issue #290618 I request that it be made explicit that the initial admin user login is "Wiki", and not "admin".

## Proposal
Below is the documentation where admin login name should likely be included.
https://github.com/NixOS/nixpkgs/blob/526d051b128b82ae045a70e5ff1adf8e6dafa560/nixos/modules/services/web-apps/mediawiki.nix#L251

## Checklist
 
- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Lassulus** [comment]
can you create a PR with the requested changes?

**Comment by eclairevoyant** [comment]
Maybe I'm misunderstanding, but according to this code, `install.php`'s second arg is `admin`:
https://github.com/NixOS/nixpkgs/blob/526d051b128b82ae045a70e5ff1adf8e6dafa560/nixos/modules/services/web-apps/mediawiki.nix#L620

and per upstream docs (https://www.mediawiki.org/wiki/Manual:Install.php#Arguments), the `install.php` takes two args, the name of the wiki and the name of the administrative user.

Where is `Wiki` coming from?

**Comment by Mic92** [comment]
Ah yes. You called it "Sample Wiki". So it took "Wiki" as the username.

**Comment by Mic92** [comment]
Looks like I fixed this issue in master already: f468e0d11180bdde888a7a16f9c043ec33dd284e

**Comment by eclairevoyant** [comment]
Fixed by #299016

**Comment by Sepero** [comment]
@Mic92 Could you please explain what "fixed" means. Now should we expect the default admin username "admin"?

**Comment by eclairevoyant** [comment]
> Now should we expect the default admin username "admin"?

Yes, on the `nixos-23.11` branch.

**Comment by Sepero** [comment]
Thank you. Also, please edit the documentation to make it *Explicit* that the default administrator username is "admin"

https://github.com/NixOS/nixpkgs/blob/526d051b128b82ae045a70e5ff1adf8e6dafa560/nixos/modules/services/web-apps/mediawiki.nix#L251

From "for the admin user"

To "for the initial user \\"admin\\""
