### ISSUE TITLE
Build failure: git-branchless 0.8.0

### ISSUE THREAD

**Issue by TheOnlyMrCat** [NixOS/nixpkgs#299029]
### Steps To Reproduce

1. checkout `nixos-unstable` (nixpkgs commit `20f77aa09916374aa3141cbc605c955626762c9a`).
1. build `git-branchless`.

### Build log

https://gist.github.com/TheOnlyMrCat/2fce8f0d56b384163153f1f53d435456

### Additional context

Also failed on [Hydra](https://hydra.nixos.org/build/253622537).

### Notify maintainers

@msfjarvis @nh2 @hmenke

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0, NixOS, 24.05 (Uakari), 24.05.20240314.d691274`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by msfjarvis** [comment]
This is fixed in master but hasn't trickled down to nixos-unstable yet: https://nixpk.gs/pr-tracker.html?pr=298309

**Comment by TheOnlyMrCat** [comment]
Ah, sorry... I searched issues but forgot to search PRs. Thanks!
