### ISSUE TITLE
Fish has 'hostname' as an undeclared runtime dependency 

### ISSUE THREAD

**Issue by TheNeikos** [NixOS/nixpkgs#29905]
## Issue description

After switching my default shell to fish the system becomes unusable until a rollback.
And by unusable I mean that the whole env is broken, and no other program can be started.

![](https://i.imgur.com/2ILMDTD.png)

However, hostname __is__ installed.

```shell
[neikos@nixos:~]$ hostname
nixos
```

### Steps to reproduce

I have added the `shell` value to my user object pointing to `pkgs.fish`.

## Technical details

* System: 17.03.1861.ad6265dbfa (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1861.ad6265dbfa"
* Sandboxing enabled: false

CC: @matthiasbeyer

**Comment by matthiasbeyer** [comment]
Some more information: This is a freshly installed OVH VPS with NixOS 17.03 - it seems like fish has an unmet runtime dependency here, though it seems like the package defines it properly... not sure what causes this therefor.

**Comment by matthiasbeyer** [comment]
`programs.fish.enable = true;` did it for us, i guess.
