### ISSUE TITLE
Dependencies of yi editor aren't configured properly

### ISSUE THREAD

**Issue by chessai** [NixOS/nixpkgs#29907]
## Issue description
$ nix-env -iA nixos.haskellPackages.yi
installing ‘yi-0.15.0’
these derivations will be built:
  /nix/store/pzgjy4mmb1a6wif91yjxr54kl13inr3b-yi-0.15.0.drv
building path(s) ‘/nix/store/nrxaihw4qr18zb3k1zbrsms1ln8vzmn0-yi-0.15.0-doc’, ‘/nix/store/vq7az9jn7cd6rizcgisxbl2418rl2ra5-yi-0.15.0’
setupCompilerEnvironmentPhase
Build with /nix/store/rzqyfil4xmja85w5sm13m107j1zm8d7s-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/c902fi72d5l8sfw420i2786wm1183pam-yi-0.15.0.tar.gz
source root is yi-0.15.0
setting SOURCE_DATE_EPOCH to timestamp 1504456182 of file yi-0.15.0/yi.cabal
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-yi-0.15.0.drv-0/package.conf.d -j8 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-yi-0.15.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/vq7az9jn7cd6rizcgisxbl2418rl2ra5-yi-0.15.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/nrxaihw4qr18zb3k1zbrsms1ln8vzmn0-yi-0.15.0-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-yi-0.15.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/vq7az9jn7cd6rizcgisxbl2418rl2ra5-yi-0.15.0/lib/ghc-8.0.2/yi-0.15.0 --ghc-option=-j8 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --ghc-option=-split-sections -fpango -fvty
Configuring yi-0.15.0...
Setup: Encountered missing dependencies:
yi-core >=0.15.0,
yi-misc-modes >=0.15.0,
yi-mode-haskell >=0.15.0,
yi-mode-javascript >=0.15.0
builder for ‘/nix/store/pzgjy4mmb1a6wif91yjxr54kl13inr3b-yi-0.15.0.drv’ failed with exit code 1
error: build of ‘/nix/store/pzgjy4mmb1a6wif91yjxr54kl13inr3b-yi-0.15.0.drv’ failed

### Steps to reproduce
See above.

## Technical details

* System: NixOS 18.03pre116432.263185aa68 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre116432.263185aa68"
* Sandboxing enabled: build-use-sandbox = false

**Comment by wizzup** [comment]
please see https://github.com/NixOS/nixpkgs/issues/28248 for workaround
