### ISSUE TITLE
Confusing error message when installing plasma-browser-integration via programs.firefox.nativeMessagingHosts.packages but plasma6 is enabled

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#299053]
### Describe the bug

Nixos-unstable, with plasma6 as the DE, I noticed the plasma integration plugin was not finding the native messaging host (which turned out to be the reason some OAuth flows were breaking). So I set out to add the relevant package to `programs.firefox.nativeMessagingHosts.packages`. This led to the configuration not building at all, with this surprising message:

```
error: builder for '/nix/store/1ldkr5518s2y34mldisaxapb3i029wny-firefox-124.0.1.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/zrdlsfqrq6dy2zq171zilv4w73fql1a5-firefox-124.0.1/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json': File exists
       For full logs, run 'nix log /nix/store/1ldkr5518s2y34mldisaxapb3i029wny-firefox-124.0.1.drv'.
```

Turns out the *real* fix here was to just flip on `programs.firefox.enable` instead of adding firefox to `environment.systemPackages`.

I guess the plasma6 module already adds the native messaging host package? Could probably use some deduplication or warning about duplicates.

### Notify maintainers

@K900

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
That's a Firefox wrapper thing. CC @mweinelt

**Comment by SuperSandro2000** [comment]
#335253
