### ISSUE TITLE
Add option "programs.kde-pim.enable"

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#299152]
## Problem

There is currently no documentation, on how to combine the different PIM libraries, and what is needed to get a full Kontact experience. 

I installed all the seemingly relevant libraries, and it is still resulting in an error. 

I question the sense of shipping Kontact without Akonadi.

## Proposal

Document on how to combine the different PIM libraries, and clearly stating, which one is needed in which case, and what combinations lead to what outcome. 

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
We just need to figure out what's wrong and add that to the plasma6 module and maybe add a new option for it. We probably don't need and want to add explicit documentation for this.
