### ISSUE TITLE
coreutils produces executable `[`

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#29917]
## Issue description

For https://github.com/NixOS/nixpkgs/issues/29896 I had a look in `/run/current-system/sw/bin/`
and noticed it contains
```
lrwxrwxrwx 1 root root 64 Jan  1  1970 '[' -> '/nix/store/magv1gd9rrzlrmv7cgv2nsdpj7pqqd0f-coreutils-8.28/bin/['
```
This seems wrong to me...

## Technical details

* NixOS 17.09 at d9dabb0e66c651cf5ad2dd8b15f5811afea49a0e

**Comment by FRidh** [comment]
Nevermind, this is really part of coreutils. Funny.

**Comment by vcunat** [comment]
I heard there were times when `[` aka `test` wasn't a shell builtin...
