### ISSUE TITLE
Merkuro Calender has no option to add accounts

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#299163]
### Describe the bug

Thats on a fully decked out Mercurio Calender app:

![Screenshot_20240326_123322](https://github.com/NixOS/nixpkgs/assets/6344099/3269e926-63ae-418f-b731-ab3bb9cd73f1)

### Configuration

https://paste.ee/p/CtSma

### Expected behavior
Mercurio lets me add a Nextcloud DAV instance. 

### Notify maintainers

@ilya-fedin
@K900
@LunNova
@mjm
@NickCao
@SuperSandro2000
@ttuegel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre601756.44d0940ea560`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
TIL that program exists 😅

**Comment by teto** [comment]
how does one install that ? official link ?

**Comment by ShalokShalom** [comment]
[kdePackages.merkuro](https://search.nixos.org/packages?channel=unstable&show=kdePackages.merkuro&from=0&size=50&sort=relevance&type=packages&query=+Merku)

**Comment by ShalokShalom** [comment]
It works fine with Akonadi installed.
