### ISSUE TITLE
[17.09] bcc tools segfault

### ISSUE THREAD

**Issue by shosti** [NixOS/nixpkgs#29913]
(Possibly related to #17683, I don't know enough to know for sure.)

## Issue description

BCC tools on my system (17.09 beta) segfault.

### Steps to reproduce

1. In /etc/nixos/configuration.nix:

```
  environment.systemPackages = with pkgs; [
    ...
    linuxPackages.bcc
    ...
  ];
```
2. `sudo biolatency` (I also tried `biotop`, `biosnoop`, and `zfsslower`)

Output: https://gist.github.com/4ed1132ca201dcdb47a8ea7074b50265 (similar for all tools).

## Technical details

* System: `17.09beta1199.a193400216 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"17.09beta1199.a193400216"`
* Sandboxing enabled: false

**Comment by orivej** [comment]
Please try to install bcc by adding `programs.bcc.enable = true;` into your `configuration.nix` after updating to https://github.com/NixOS/nixpkgs/commit/44b6a1509daf214d292dadafaedf8fea994c12a5 .

**Comment by orivej** [comment]
Otherwise install bcc without updating by adding these changes to your `configuration.nix`:
```
    environment.systemPackages = [ config.boot.kernelPackages.bcc ];
    boot.extraModulePackages = [ config.boot.kernelPackages.bcc ];
```

@globin @Mic92 Maybe [sysdig](https://github.com/NixOS/nixpkgs/commit/55720626744d8123a48760c867f8c19205f1567b) and [bcc](https://github.com/NixOS/nixpkgs/commit/44b6a1509daf214d292dadafaedf8fea994c12a5) modules should be included in the 17.09 release?

**Comment by Mic92** [comment]
Probably in fact they are more documentation then code.

**Comment by shosti** [comment]
Thanks for the info! Unfortunately the problem seems to persist. I've been able to reproduce on a VM with a minimal configuration: https://gist.github.com/4f86dfedc913d437b2660e3145e51b62 (my current NixOS version is 17.09beta1314.dc4750b3c3). The problem seems to be the same with the 4.13 kernel and the default 4.9 kernel.

**Comment by Mic92** [comment]
Right. Looks like we are running into this problem: https://github.com/iovisor/bcc/issues/1221

**Comment by Mic92** [comment]
If I build the program manually and run it from the build directory it seems not the trigger the bug.
