### ISSUE TITLE
Update request: rtl88xxau-aircrack 6.8.1-unstable-02-05-2023 → 4f645e

### ISSUE THREAD

**Issue by hoh** [NixOS/nixpkgs#299132]
- Package name: [linuxKernel.packages.linux_6_8.rtl88xxau-aircrack](https://search.nixos.org/packages?channel=23.11&show=linuxKernel.packages.linux_6_8.rtl88xxau-aircrack&from=0&size=50&sort=relevance&type=packages&query=rtl88xxau)
- Latest released version: 6.8.1-unstable-02-05-2023
- Current version on the unstable channel: 6.8.1-unstable-02-05-2023
- Current version on the stable/release channel: 6.8.1-unstable-02-05-2023
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jethrokuan @erdnaxe

-----

rtl88xxau-aircrack does not build on Linux 6.8. 

A recent fix, 2 weeks ago, may solve this: [ Update for kernel 6.8 #1145](https://github.com/aircrack-ng/rtl8812au/pull/1145)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ja1den** [comment]
This should be resolved by #304140.
