### ISSUE TITLE
gogs unable to start with non-default user

### ISSUE THREAD

**Issue by The-M1k3y** [NixOS/nixpkgs#29922]
## Issue description

When running gogs with another user than "gogs" the service can not start.

The service creates the data-directory for gogs as the home directory for the user "gogs"instead of the given user with the result, that the service can't access its data.

The same problem might also affect the group setting.

### Steps to reproduce

Setup NixOS with gogs enabled and a custom user via "services.gogs.user" that is not "gogs".
After building the configuration the data directory (default is "/var/lib/gogs") will be owned by gogs:gogs.

## Technical details

* System: NixOS: 17.03.982.b647a67dfe (Gorilla)
* Nix version: 1.11.8
* Nixpkgs version: 17.03.982.b647a67dfe
* Sandboxing enabled: false

**Comment by joachifm** [comment]
cc @rvl @schneefux

**Comment by knedlsepp** [comment]
@The-M1k3y: Seems the issue didn't get closed automatically despite your commit.
