### ISSUE TITLE
Package request: flye

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#299225]
**Project description**

Flye is a de novo assembler for single-molecule sequencing reads, such as those produced by PacBio and Oxford Nanopore Technologies. It is designed for a wide range of datasets, from small bacterial projects to large mammalian-scale assemblies. The package represents a complete pipeline: it takes raw PacBio / ONT reads as input and outputs polished contigs. Flye also has a special mode for metagenome assembly.

**Metadata**

* homepage URL: https://github.com/fenderglass/Flye
* source URL: https://github.com/fenderglass/Flye
* license: BSD 3-clause
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Assistant** [comment]
I've packaged Flye and it should be on `nixos-unstable` now, let me know if it's working for you.

**Comment by Pandapip1** [comment]
Looks like it installed okay.
