### ISSUE TITLE
Package request: relive

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#299261]
**Project description**

An Open-Source Engine Replacement for Oddworld: Abe's Oddysee and Oddworld: Abe's Exoddus.

There is a level editor as well: https://github.com/AliveTeam/qt-editor

**Metadata**

* homepage URL: https://aliveteam.github.io/index.html
* source URL: https://github.com/AliveTeam/alive_reversing
* license: MIT
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
@keenanweaver I created a PR https://github.com/NixOS/nixpkgs/pull/299343 based on this package request. Would you  check out and test its various functionalities. Thx
