### ISSUE TITLE
Update request: koreader 2023.04 → 2024.03.1

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#299211]
- Package name: koreader
- Latest released version: 2024.03.1

- Current version on the unstable channel: 2023.04
- Current version on the stable/release channel: 2023.04

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@contrun @neonfuz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbsds** [comment]
please test #299251
