### ISSUE TITLE
Build failure: wlroots

### ISSUE THREAD

**Issue by djacu** [NixOS/nixpkgs#299270]
### Steps To Reproduce

Recently updated the inputs for my nixos configuration. My nixpkgs input is pinned on `nixos-23.11`.
When I try to rebuild my system I get an error with wlroots.
It appears that `fetchpatch` was added to the input arguments here: https://github.com/NixOS/nixpkgs/commit/3e1dba866f8346b38bc236483b1d80cee352be3d
But if you look at the latest commit from 23.11, it is not there: https://github.com/NixOS/nixpkgs/blob/56528ee42526794d413d6f244648aaee4a7b56c0/pkgs/development/libraries/wlroots/default.nix

### Build log

```
       error: function 'anonymous lambda' called with unexpected argument 'fetchpatch'

       at /nix/store/bn7d9rhgmmz0l4x9ykv5q10gzq1rkxci-source/pkgs/development/libraries/wlroots/default.nix:1:1:

            1| { lib
             | ^
            2| , stdenv
```

### Additional context

Here is what is pinned in my flake.lock

```
    "nixpkgs": {
      "locked": {
        "lastModified": 1711124224,
        "narHash": "sha256-l0zlN/3CiodvWDtfBOVxeTwYSRz93muVbXWSpaMjXxM=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "56528ee42526794d413d6f244648aaee4a7b56c0",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-23.11",
        "repo": "nixpkgs",
        "type": "github"
      }
    }
```

### Notify maintainers

@primeos 
@Synthetica9 
@wineee 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
  /nix/store/jlx0nh7j7lfsi1sfjlvsp7f0bfjgnnaf-nix-info
copying path '/nix/store/jlx0nh7j7lfsi1sfjlvsp7f0bfjgnnaf-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.3, NixOS, 23.11 (Tapir), 23.11.20231201.5de0b32`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wineee** [comment]
Can't reproduce this issue, build on hydra was also successful
https://hydra.nixos.org/eval/1805247?filter=nixpkgs.wlroots&compare=1805167&full=

Are you using overlays changed the build of wlroots? (eg. hyprland, nixpkgs-wayland)

**Comment by djacu** [comment]
> Are you using overlays changed the build of wlroots? (eg. hyprland, nixpkgs-wayland)

I am using the nixpkgs-wayland overlay. Could that be the reason?

**Comment by wineee** [comment]
https://github.com/nix-community/nixpkgs-wayland/blob/63ec93a0528b43b63b8d2bbddb436e4a2ef6d068/pkgs/wlroots/default.nix#L15


fetchpatch was introduced to remove a `conflicting-patch`, which is actually no longer needed.

**Comment by wineee** [comment]
https://github.com/nix-community/nixpkgs-wayland/pull/447

You can update nixpkgs-wayland and test again
