### ISSUE TITLE
Nerd Fonts should not have a fixed output hash

### ISSUE THREAD

**Issue by IQubic** [NixOS/nixpkgs#29928]
## Issue description
The Nerd Fonts package currently has a fixed hash output. However, the package has a withFonts argument that can be overridden. 

    nixpkgs.nerdfonts.override { withFonts = "InconsolataGo"; }

If this option is not overridden, then all of the fonts in the Nerd Font repo are pulled in and installed. However, if you override the withFonts argument, then only the selected Nerd Fonts will be built. That should produce a different hash. Unfortunately due to the hash output being literally hard-coded into the nix expressions that built the Nerd Fonts the hash will never change.

The version of NerdFonts on master is flawed because the output hash never changes.

https://github.com/NixOS/nixpkgs/blob/799435b7ca/pkgs/data/fonts/nerdfonts/default.nix#L23-L25

However, the version linked to from searching through packages on nixos.org is A) Correct, and B) Not the master branch.

https://github.com/NixOS/nixpkgs/blob/ea06690f1f02fab201b78971769b29fc52cb8e0b/pkgs/data/fonts/nerdfonts/default.nix

### Steps to reproduce
Run `nix-build -E 'with import <nixpkgs> {}; nerdfonts'`

Note the output path.

Run `nix-build -E 'with import <nixpkgs> {}; nerdfonts.override { withFont = "InconsolataGo"; }'`

Note that the output path is the same.

This indicates that the package was not rebuilt, even though it should have been

## Technical details

* System: 17.03 (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: Same as system
* Sandboxing enabled: No

**Comment by joachifm** [comment]
cc @volth

**Comment by volth** [comment]
Do you suggest to remove the fixed hash or to make it depended on ```withFont``` ?
