### ISSUE TITLE
structured-haskell-mode is missing the elisp files

### ISSUE THREAD

**Issue by sellout** [NixOS/nixpkgs#29929]
## Issue description

The latest version of structured-haskell-mode only has `bin/` and `lib/` directories, no `share/`, so the primary content of the package is missing.

I have another machine with an older nixpkgs that still has structured-haskell-mode-1.1.0, and that has the correct directory structure. My _guess_ is that ef6849ca63ffa01e10aa28ade7d8afff7a856922 is the culprit, since 1. it touches the relevant bit of the package and 2. it’s between removing the pinning from releases (1.0.20) and adding the pinning to git version. On the other hand, that change seems to line up with how the other packages are defined, so ¯\\\_(ツ)_/¯

### Steps to reproduce

`nix-env -i emacs-structured-haskell-mode` then inspect the directory in the nix store.

## Technical details

* System: macOS Sierra 10.12.6
* Nix version: 1.11.15
* Nixpkgs version: 17.09pre115480.10bb7fddb9
* Sandboxing enabled: false

**Comment by adisbladis** [comment]
This is no longer the case.
