### ISSUE TITLE
Build failure: xgcc

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#299240]
### Steps To Reproduce

```bash
nix run -L nixpkgs#nix-info 2> build.log
```

### Build log

https://gist.github.com/Pandapip1/1f199700f6c6cfaa5238c8b3522a8bb7

### Additional context

```
```console
gavinjohn@login:/ref/djslab/software $ cat ~/.config/nix/nix.conf 
experimental-features = nix-command flakes
use-xdg-base-directories = true
require-sigs = false
store = local?store=/ref/djslab/software/nix/store&state=/ref/djslab/software/nix/state&log=/scratch/djslab/nix/log
ssl-cert-file = /etc/ssl/certs/ca-bundle.crt
substituters = https://cache.nixos.org/
trusted-substituters = https://cache.nixos.org/
fallback = true
http-connections = 0
gavinjohn@login:/ref/djslab/software $ cat ~/.config/nix/channels 
https://nixos.org/channels/nixpkgs-unstable nixpkgs
gavinjohn@login:/ref/djslab/software $ which nix
/ref/djslab/software/usr/local/bin/nix
gavinjohn@login:/ref/djslab/software $ nix --version
nix (Nix) 2.21.1
gavinjohn@login:~ $ nix run -L nixpkgs#nix-info 2> build.log
gavinjohn@login:~ $ 
```

### Notify maintainers

@ericson2314

### Metadata

N.A. `nix-info` is the package I'm trying to install in the first place.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Pandapip1** [comment]
`binutils` originally was what was failing. Turns out this time `xgcc` failed first.

**Comment by LeSuisse** [comment]
Looking at your logs this is a bit strange: `xgcc> make[2]: *** [Makefile:2503: s-automata] Error 137`

Did you have enough RAM available when building it? It looks like the process might have been OOM killed.

**Comment by Pandapip1** [comment]
> Did you have enough RAM available when building it? It looks like the process might have been OOM killed.

It's almost certainly an OOM. The login nodes have very limited RAM; I'll try again in an interactive session later.

Nix should definitely handle OOM errors as a special case though, as they are one of the few cases that will always break reproducability!

**Comment by lolbinarycat** [comment]
have you tried `--max-jobs 1`?  running less stuff in parallel should reduce both cpu and memory usage, at the cost of increasing build time.

**Comment by Pandapip1** [comment]
I'm on a cluster, but was running it on the resource-constrained login node. I'll be runningn it with **significantly** more resources later today

**Comment by lolbinarycat** [comment]
what do you mean by "special treatment"?

**Comment by Pandapip1** [comment]
> what do you mean by "special treatment"?

To make it obvious that the error was caused by an OOM. Flakes are supposed to be reproducible. OOM errors obviously break reproduciblity.

**Comment by lolbinarycat** [comment]
> OOM errors obviously break reproduciblity.

i'm not sure if i agree.  there's lots of external factors that can cause a build to fail (hard drive corruption, running out of disk space, power outages, the user pressing ^C), i'm not sure that makes a build not reproducible (it's not like these are somehow causing a different output to be produced).

it is a somewhat unclear error message, and you could try opening an issue in [nix](https://github.com/NixOS/nix) about that, although i'm not sure if there's an easy way to detect OOM errors, short of parsing the kernel logs.

**Comment by Pandapip1** [comment]
CC https://github.com/NixOS/nix/issues/10351
