### ISSUE TITLE
Utility suggestion: fetchPatchFromGitHub

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#299393]
In a quick search I have found 1780 instances of patches from GitHub repos.
I think it deserves a thin abstraction.

**Comment by winterqt** [comment]
I'm somewhat on the fence about this, I don't think the added attributes to juggle really add much in terms of readability versus `fetchpatch`, given GitHub's convenient patch URLs.

```nix
fetchPatchFromGitHub {
  name = "fix-gcc13-build";
  owner = "InsightSoftwareConsortium";
  repo = "ITK";
  rev = "9a719a0d2f5f489eeb9351b0ef913c3693147a4f";
  hash = "sha256-dDyqYOzo91afR8W7k2N64X6l7t6Ws1C9iuRkWHUe0fg=";
}
```

doesn't really look much better compared to:

```nix
fetchpatch {
  name = "fix-gcc13-build";
  url = "https://github.com/InsightSoftwareConsortium/ITK/commit/9a719a0d2f5f489eeb9351b0ef913c3693147a4f.patch";
  hash = "sha256-dDyqYOzo91afR8W7k2N64X6l7t6Ws1C9iuRkWHUe0fg=";
}
```

**Comment by AndersonTorres** [comment]
This single example triggered the sliding bar from GitHub web interface.
Also we have `fetchDebianPatch`,  a rarely used function - 37 hits, some of them being re-implementations.
If fetchPatchFromGitHub looks bad, then `fetchDebianPatch` looks equally bad.

**Comment by lolbinarycat** [comment]
should it be named `fetchGitHubPatch` for consistency with `fetchDebianPatch`?

**Comment by AndersonTorres** [comment]
I believe we should give names to those functions in the following fashion:

- low level: `fetch<object>`
  - `fetchurl  fetchzip  fetchbzr  fetchpatch` 
- high level: `fetch<object>From<place>`
  - `fetchFromSavannah fetchFromGitLab` 

In this case `fetchDebianPatch` should be called `fetchPatchFromDebian`

But it's a little too late to retcon this.  The best we can possiblly do is to create `fetchPatchFromDebian` later.

**Comment by lolbinarycat** [comment]
`fetchPatchFromDebian` is visual noise to me, it's too many short camel-case words. it also implies "debian" is a place, which i would argue it is not.

i also think `fetchYFromX` looks too close to `fetchFromX` when skimming code.

**Comment by AndersonTorres** [comment]
Short camel-case is typical on Nixpkgs, since it is hard to pass kebab-case variables to shell. `dontUseCmakeConfigure` and friends come to mind.

**Comment by lolbinarycat** [comment]
yes, "short" and "camel case" are the two adjectives which can't really be changed, however we can easily use less words by making it just `fetch*Patch`.

**Comment by winterqt** [comment]
I'd recommend we not waste time bikeshedding about a function name when it's debatable if it's even useful to have.

**Comment by AndersonTorres** [comment]
Then I vote for removing `fetchDebianPatch`.

**Comment by AndersonTorres** [comment]
I will remove fetchDebianPatch, then.
