### ISSUE TITLE
Update request: libtorch-bin 2.0.0 → 2.2.1

### ISSUE THREAD

**Issue by mrozycki** [NixOS/nixpkgs#299311]
- Package name: libtorch-bin
- Latest released version: 2.2.1

- Current version on the unstable channel: 2.0.0
- Current version on the stable/release channel: 2.0.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@junjihashimoto 

-----

Note for maintainers: Please tag this issue in your PR.

libtorch 2.2.1 has a version for aarch64-darwin-cpu, while the current version on the unstable channel does not. I am specifically after Apple silicon mac support, so it's important for me that the aarch64-darwin version is added.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
https://github.com/NixOS/nixpkgs/pull/302427

**Comment by npatsakula** [comment]
Hello @mrozycki! https://github.com/NixOS/nixpkgs/pull/308328 was merged into master and already available in unstable channel. Maybe we can close this issue?
