### ISSUE TITLE
Automate the “Technical details” section of the issue template

### ISSUE THREAD

**Issue by sellout** [NixOS/nixpkgs#29932]
I was thinking the “Technical details” section could perhaps be made a bit simpler, like:

> ## Technical details
> 
> Run `curl https://nixos.org/nix/system-info | sh ` and replace this with the output from that command.

where `system-info` is something like:

```sh
#!/bin/sh

SYSTEM_VERSION=$(nixos-version \
	      || lsb_release -a \
              || echo "$(sw_vers -productName) $(sw_vers -productVersion) $(sw_vers -buildVersion)")

echo "* System: $SYSTEM_VERSION"
echo "* Nix version: $(nix-env --version)"
echo "* Nixpkgs version: $(nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion)"
echo "* Sandboxing enabled: $(grep build-use-sandbox /etc/nix/nix.conf | awk '{ print $3 }')"
```

**Comment by matthewbauer** [comment]
Yeah this is definitely a good idea. I think there was similar discussion previously but I can't find it right now.

Homebrew calls it ```config```, maybe we can just put it as ```nix config``` for Nix 1.12. Ideally we could completely automate the process combining data from ```nix config``` and ```nix log``` into something like ```nix report-bug``` so everything is provided.

**Comment by pbogdan** [comment]
@matthewbauer were you perhaps thinking of https://github.com/NixOS/nixpkgs/issues/27758 (re: previous discussion)?

**Comment by davidak** [comment]
We have `nix-info` now. See https://github.com/NixOS/nixpkgs/pull/30397

It is already included in the issue template. (https://github.com/NixOS/nixpkgs/pull/31643)

But from the title of this issue i got the idea to automatically tag issues from that info. (https://github.com/NixOS/nixpkgs/issues/32089)
