### ISSUE TITLE
Package request: nucleo

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#299420]
A fast and convenient fuzzy matcher library for rust

Fuzzy matcher that is used in helix editor

**Metadata**

* homepage URL: https://github.com/helix-editor/nucleo
* source URL: https://github.com/helix-editor/nucleo
* license: MPL 2.0
* platforms: all

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
AFAICT at the moment they haven't implemented a standalone cli.

**Comment by LennyLizowzskiy** [comment]
oh, my problem
