### ISSUE TITLE
nixos/wpa_supplicant: missing /etc/wpa_supplicant.conf

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#299466]
### Describe the bug

After installing a fresh system with the following configuration:

```nix
networking.wireless = {
  enable = true;
  userControlled.enable = true;
  allowAuxiliaryImperativeNetworks = true;
  networks = ...;
};
```

the file `/etc/wpa_supplicant.conf` is not created, hence wpa_supplicant fails to start with the following error:

```
Failed to open config file '/etc/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/etc/wpa_supplicant.conf'.
```

### Notify maintainers

@rnhmjoj

### Metadata

nixpkgs 97b17f3236

**Comment by rnhmjoj** [comment]
I don't know the logic of `allowAuxiliaryImperativeNetworks`, but I think you're supposed to provide the file yourself.
I guess it could be `touch`ed if wpa_supplicant fails without one.

**Comment by ToppDev** [comment]
You can do
```
systemd.services.wpa_supplicant.preStart = "touch /etc/wpa_supplicant.conf";
```

**Comment by rnhmjoj** [comment]
> systemd.services.wpa_supplicant.preStart = "touch /etc/wpa_supplicant.conf";

That probably wouldn't work due to permissions.

**Comment by rnhmjoj** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/305649
