### ISSUE TITLE
HUGE output size of `python311Packages.jupyter-server` on Darwin

### ISSUE THREAD

**Issue by iwinux** [NixOS/nixpkgs#299427]
### Describe the bug

Both [python311Packages.jupyter-server.aarch64-darwin](https://hydra.nixos.org/job/nixpkgs/trunk/python311Packages.jupyter-server.aarch64-darwin) and [python311Packages.jupyter-server.x86_64-darwin](https://hydra.nixos.org/job/nixpkgs/trunk/python311Packages.jupyter-server.x86_64-darwin) have a ridiculously huge output size of 1.6GB.

On close inspection, there're 2 large files in `<store-path>/lib/python3.11/site-packages/jupyter_server/static`:

- `favicon.ico` - 772MB
- `favicons/favicon.ico` - 772MB

### Steps To Reproduce

1. open https://hydra.nixos.org/job/nixpkgs/trunk/python311Packages.jupyter-server.aarch64-darwin
2. click "Charts" and see "Output size"

### Expected behavior

As a Python package with only `.py` / `.pyc` files and bundle static assets, its output size should be no more than 5MB. The latest build of [python311Packages.jupyter-server.x86_64-linux](https://hydra.nixos.org/job/nixpkgs/trunk/python311Packages.jupyter-server.x86_64-linux) has an output size of 3.87MB.

### Notify maintainers

@mweinelt / @natsukium

### Metadata

```console
system: "aarch64-darwin", multi-user?: no, version: nix-env (Nix) 2.18.1, nixpkgs: /nix/store/5x0f1clpr0bdk4vimxmsdw6dhn4q9mzh-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Looks like both favicons are the same file with lots of null lines.

```
00000000  00 00 01 00 04 00 10 10  3c 00 30 30 00 00 00 00  |........<.00....|
00000010  00 00 46 00 00 00 00 00  00 00 00 00 20 00 a8 10  |..F......... ...|
00000020  00 00 ae 04 00 00 30 30  3c 00 00 00 00 00 00 00  |......00<.......|
00000030  00 00 56 15 00 00 40 40  00 00 00 00 00 00 00 00  |..V...@@........|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
30300030  00 00 00 00 00 00 00 00  00 00 00 00 04 00 00 00  |................|
30300040
```

**Comment by mweinelt** [comment]
Whatever happens, it happens during fixup phase.

**Comment by mweinelt** [comment]
Disabling `doStrip` reduces the size to normal values.

**Comment by mweinelt** [comment]
```
hexa@darwin01> nix-shell -p binutils                                                                                                                                                       ~
these 2 paths will be fetched (0.01 MiB download, 0.08 MiB unpacked):
  /nix/store/5jl0flhj924jz1q1c14j6mi910rg68yn-binutils-wrapper-2.41
  /nix/store/lmxn38yxr97vzk29w7dfi92wgpx11rmi-expand-response-params
copying path '/nix/store/lmxn38yxr97vzk29w7dfi92wgpx11rmi-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/5jl0flhj924jz1q1c14j6mi910rg68yn-binutils-wrapper-2.41' from 'https://cache.nixos.org'...
hexa@darwin01> curl -o favicon.ico https://raw.githubusercontent.com/jupyter-server/jupyter_server/main/jupyter_server/static/favicon.ico                                                  ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32038  100 32038    0     0   163k      0 --:--:-- --:--:-- --:--:--  162k
hexa@darwin01> ls -lah favicon.ico
-rw-r--r--   1 hexa  staff    31K Mar 27 12:13 favicon.ico
[nix-shell:~]$ strip favicon.ico 
hexa@darwin01> ls -lah favicon.ico
-rw-r--r--   1 hexa staff 772M Mar 27 12:13 favicon.ico
```

**Comment by natsukium** [comment]
Thanks for reporting and finding out.
I noticed that the transfer of jupyter-server was notably slow during distributed builds. But I'm surprised that this happened.
