### ISSUE TITLE
Add deja-dup

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#29955]
## Issue description
Deja-dup is a good graphical frontend to duplicity.However I don't seem able to build it on nixos

### Steps to reproduce
The following nix expression fails with `error: Package 'goa-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

```

{ stdenv, fetchurl, meson, pkgconfig, vala, gettext
, gnome3, libnotify, intltool, itstool, glib, gtk3
, packagekit, libsecret, pcre, libxkbcommon, wrapGAppsHook
, libpthreadstubs, libXdmcp, epoxy, at_spi2_core, dbus,libgpgerror
,appstream-glib,desktop_file_utils,ninja
}:

stdenv.mkDerivation rec {
  name = "deja-dup-${version}";
  version = "36.1";

  src = fetchurl {
    url = "https://launchpad.net/deja-dup/36/${version}/+download/deja-dup-${version}.tar.xz";
    sha256 = "1s48k2sxrpwkzp37s4x7934lyg5194c47nv9ks15rksd5s0alnld";
  };

  /*prePatch = ''
    #Disable goa(?)
    substituteInPlace deja-dup/meson.build \
      --replace "goa_dep," "" 
  '';*/

  # couldn't find gio/gdesktopappinfo.h
  NIX_CFLAGS_COMPILE = "-I${glib.dev}/include/gio-unix-2.0";

  buildInputs = [
   meson pkgconfig vala gettext libnotify gnome3.libpeas
   intltool itstool glib gtk3 packagekit libsecret# help2man
   pcre libxkbcommon libpthreadstubs libXdmcp epoxy gnome3.nautilus
   at_spi2_core dbus wrapGAppsHook gnome3.gnome_online_accounts
   libgpgerror appstream-glib desktop_file_utils ninja
  ];

  meta = with stdenv.lib; {
    description = "A simple backup tool";
    longDescription = ''
      Déjà Dup is a simple backup tool. It hides the complexity \
      of backing up the Right Way (encrypted, off-site, and regular) \
      and uses duplicity as the backend.
    '';
    homepage = https://launchpad.net/deja-dup;
    license = with licenses; gpl3;
    maintainers = with maintainers; [ ];
    platforms = with platforms; linux;
  };
}
```

## Technical details

* System: 18.03pre116572.9824ca6975)
* Nix version: 1.11.15
* Nixpkgs version:18.03pre-git
* Sandboxing enabled:false

**Comment by jtojnar** [comment]
Dèja Dup requires Vala bindings for `gnome_online_accounts`. Try adding `vala` to its `nativeBuildInputs`.

Also `meson pkgconfig vala gettext intltool itstool help2man wrapGAppsHook appstream-glib desktop_file_utils ninja` should be moved to `nativeBuildInputs`.

**Comment by pasqui23** [comment]
Even with the changes suggested by @jtojnar it still abort with the same error

**Comment by jtojnar** [comment]
I see a different error upon adding `vala` to `gnome_online_accounts`:

```
[48/96] Compiling Vala source ../deja-dup/widgets/ConfigBool.vala ../deja-dup/widgets/ConfigChoice.vala ../deja-dup/widgets/ConfigDelete.vala ../deja-dup/widgets/ConfigEntry.vala ../deja-dup/widgets/ConfigFolder.vala ../deja-dup/widgets/ConfigLabel.vala ../deja-dup/widgets/ConfigLabelBackupDate.vala ../deja-dup/widgets/ConfigLabelDescription.vala ../deja-dup/widgets/ConfigLabelLocation.vala ../deja-dup/widgets/ConfigList.vala ../deja-dup/widgets/ConfigLocation.vala ../deja-dup/widgets/ConfigLocationCustom.vala ../deja-dup/widgets/ConfigLocationFile.vala ../deja-dup/widgets/ConfigLocationGCS.vala ../deja-dup/widgets/ConfigLocationGoa.vala ../deja-dup/widgets/ConfigLocationOpenstack.vala ../deja-dup/widgets/ConfigLocationRackspace.vala ../deja-dup/widgets/ConfigLocationS3.vala ../deja-dup/widgets/ConfigLocationTable.vala ../deja-dup/widgets/ConfigLocationU1.vala ../deja-dup/widgets/ConfigLocationVolume.vala ../deja-dup/widgets/ConfigPeriod.vala ../deja-dup/widgets/ConfigWidget.vala ../deja-dup/widgets/WidgetUtils.vala libdeja/deja.vapi.
FAILED: deja-dup/widgets/widgets@sha/ConfigBool.c deja-dup/widgets/widgets@sha/ConfigChoice.c deja-dup/widgets/widgets@sha/ConfigDelete.c deja-dup/widgets/widgets@sha/ConfigEntry.c deja-dup/widgets/widgets@sha/ConfigFolder.c deja-dup/widgets/widgets@sha/ConfigLabel.c deja-dup/widgets/widgets@sha/ConfigLabelBackupDate.c deja-dup/widgets/widgets@sha/ConfigLabelDescription.c deja-dup/widgets/widgets@sha/ConfigLabelLocation.c deja-dup/widgets/widgets@sha/ConfigList.c deja-dup/widgets/widgets@sha/ConfigLocation.c deja-dup/widgets/widgets@sha/ConfigLocationCustom.c deja-dup/widgets/widgets@sha/ConfigLocationFile.c deja-dup/widgets/widgets@sha/ConfigLocationGCS.c deja-dup/widgets/widgets@sha/ConfigLocationGoa.c deja-dup/widgets/widgets@sha/ConfigLocationOpenstack.c deja-dup/widgets/widgets@sha/ConfigLocationRackspace.c deja-dup/widgets/widgets@sha/ConfigLocationS3.c deja-dup/widgets/widgets@sha/ConfigLocationTable.c deja-dup/widgets/widgets@sha/ConfigLocationU1.c deja-dup/widgets/widgets@sha/ConfigLocationVolume.c deja-dup/widgets/widgets@sha/ConfigPeriod.c deja-dup/widgets/widgets@sha/ConfigWidget.c deja-dup/widgets/widgets@sha/WidgetUtils.c deja-dup/widgets/widgets.h deja-dup/widgets/widgets.vapi 
valac -C --pkg libsecret-1 --pkg libpeas-1.0 --pkg gtk+-3.0 --pkg goa-backend-1.0 --pkg goa-1.0 -d deja-dup/widgets/widgets@sha --library=widgets -H deja-dup/widgets/widgets.h --vapi ../widgets.vapi --pkg=config --pkg=posix --target-glib=2.46 --vapidir /tmp/nix-build-deja-dup-36.1.drv-0/deja-dup-36.1/vapi --define=HAS_PACKAGEKIT --pkg=uriutils ../deja-dup/widgets/ConfigBool.vala ../deja-dup/widgets/ConfigChoice.vala ../deja-dup/widgets/ConfigDelete.vala ../deja-dup/widgets/ConfigEntry.vala ../deja-dup/widgets/ConfigFolder.vala ../deja-dup/widgets/ConfigLabel.vala ../deja-dup/widgets/ConfigLabelBackupDate.vala ../deja-dup/widgets/ConfigLabelDescription.vala ../deja-dup/widgets/ConfigLabelLocation.vala ../deja-dup/widgets/ConfigList.vala ../deja-dup/widgets/ConfigLocation.vala ../deja-dup/widgets/ConfigLocationCustom.vala ../deja-dup/widgets/ConfigLocationFile.vala ../deja-dup/widgets/ConfigLocationGCS.vala ../deja-dup/widgets/ConfigLocationGoa.vala ../deja-dup/widgets/ConfigLocationOpenstack.vala ../deja-dup/widgets/ConfigLocationRackspace.vala ../deja-dup/widgets/ConfigLocationS3.vala ../deja-dup/widgets/ConfigLocationTable.vala ../deja-dup/widgets/ConfigLocationU1.vala ../deja-dup/widgets/ConfigLocationVolume.vala ../deja-dup/widgets/ConfigPeriod.vala ../deja-dup/widgets/ConfigWidget.vala ../deja-dup/widgets/WidgetUtils.vala libdeja/deja.vapi
../deja-dup/widgets/ConfigList.vala:336.39-336.46: error: Argument 1: Cannot pass ref argument to non-reference parameter
      (model as Gtk.ListStore).remove(ref iter);
                                      ^^^^^^^^
../deja-dup/widgets/ConfigLocation.vala:183.29-183.36: error: Argument 1: Cannot pass ref argument to non-reference parameter
        loop = store.remove(ref iter);
                            ^^^^^^^^
../deja-dup/widgets/ConfigLocation.vala:333.10-333.37: error: The name `is_removable' does not exist in the context of `GLib.Drive'
    if (!vol.get_drive().is_removable())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../deja-dup/widgets/ConfigLocation.vala:477.18-477.25: error: Argument 1: Cannot pass ref argument to non-reference parameter
    store.remove(ref iter);
                 ^^^^^^^^
../deja-dup/widgets/ConfigLocation.vala:482.22-482.33: error: Argument 1: Cannot pass ref argument to non-reference parameter
        store.remove(ref sep_iter);
                     ^^^^^^^^^^^^
../deja-dup/widgets/WidgetUtils.vala:27.5-27.26: error: The name `show_uri_on_window' does not exist in the context of `Gtk'
    Gtk.show_uri_on_window(parent, link, Gtk.get_current_event_time());
    ^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)
```

**Comment by pasqui23** [comment]
looking at pkgs/development/libraries/gtk+/3.nix it does not seem to appear that vala is included among their dependencies

what is the exact incantation to build gobjectIntrospection headers of a package?

**Comment by jtojnar** [comment]
Usually, adding `gobjectIntrospection` to `nativeBuildInputs` should suffice. Sometimes `--enable-introspection` should be added to `configureFlags` or similar option, you will have to consult `autoconf.ac`, `CMakeLists.txt` or similar file and the build system hooks in nixpkgs.

Though I am pretty sure that GTK already provides GIR and VAPI files – there are many apps relying on those.

**Comment by pasqui23** [comment]
I have just submitted the following bug report to the deja-dup team

**Comment by jtojnar** [comment]
The following expression builds for me with vala 0.38:

```nix
{ stdenv, fetchurl, meson, ninja, pkgconfig, vala_0_38, gettext
, gnome3, libnotify, intltool, itstool, glib, gtk3
, packagekit, libsecret, pcre, libxkbcommon, wrapGAppsHook
, libpthreadstubs, libXdmcp, epoxy, at_spi2_core, dbus, libgpgerror
, appstream-glib, desktop_file_utils
}:

stdenv.mkDerivation rec {
  name = "deja-dup-${version}";
  version = "36.1";

  src = fetchurl {
    url = "https://launchpad.net/deja-dup/36/${version}/+download/deja-dup-${version}.tar.xz";
    sha256 = "1s48k2sxrpwkzp37s4x7934lyg5194c47nv9ks15rksd5s0alnld";
  };

  patches = [
    ./fix-paths.patch
  ];

  # couldn't find gio/gdesktopappinfo.h
  NIX_CFLAGS_COMPILE = "-I${glib.dev}/include/gio-unix-2.0";

  nativeBuildInputs = [
    meson ninja pkgconfig vala_0_38 gettext intltool itstool # help2man
    appstream-glib desktop_file_utils wrapGAppsHook
  ];

  buildInputs = [
   libnotify gnome3.libpeas glib gtk3 packagekit libsecret
   pcre libxkbcommon libpthreadstubs libXdmcp epoxy gnome3.nautilus
   at_spi2_core dbus gnome3.gnome_online_accounts libgpgerror
  ];

  meta = with stdenv.lib; {
    description = "A simple backup tool";
    longDescription = ''
      Déjà Dup is a simple backup tool. It hides the complexity \
      of backing up the Right Way (encrypted, off-site, and regular) \
      and uses duplicity as the backend.
    '';
    homepage = https://launchpad.net/deja-dup;
    license = with licenses; gpl3;
    maintainers = with maintainers; [ ];
    platforms = with platforms; linux;
  };
}
```

### fix-paths.patch

```patch
diff --git a/deja-dup/nautilus/meson.build b/deja-dup/nautilus/meson.build
index 04b136f3..ed8f7cba 100644
--- a/deja-dup/nautilus/meson.build
+++ b/deja-dup/nautilus/meson.build
@@ -31,6 +31,6 @@ shared_module('deja-dup', ['NautilusExtension.c'],
     link_with: [dirhandling],
     dependencies: [nautilus_dep],
     install: true,
-    install_dir: nautilus_dep.get_pkgconfig_variable('extensiondir'))
+    install_dir: join_paths(get_option('libdir'), 'nautilus', 'extensions-3.0'))
 
 endif
```

The Vala 0.38 is available in #29392, I will move the upgrade to a separate PR so it could be merged sooner.

Another problem is that meson does not set rpath https://github.com/mesonbuild/meson/issues/314

**Comment by pasqui23** [comment]
wait which branch do I need to merge?

**Comment by pasqui23** [comment]
But yes,apparently it needs vala >= 0.36

**Comment by jtojnar** [comment]
See #30043

**Comment by pasqui23** [comment]
It compiles but if I try to run deja-dup it give me this error:
/home/pasquale/.nix-profile/bin/deja-dup: error while loading shared libraries: libgio-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by pasqui23** [comment]
How do you add a shared library to a package in nix?

**Comment by jtojnar** [comment]
Yes, that is the rpath issue with meson. See for example here
https://github.com/jtojnar/nixpkgs/blob/510eaa68ccee5b598363af866cade1b4a30b4972/pkgs/desktops/gnome-3/apps/gnome-calendar/default.nix

**Comment by pasqui23** [comment]
And now I get 
`/home/pasquale/.nix-profile/bin/deja-dup: error while loading shared libraries: libdeja.so: cannot open shared object file: No such file or directory`

**Comment by jtojnar** [comment]
You might need to change $out/lib, depending on where libdeja is located.

On 4 Oct 2017 11:28 am, "pasqui23" <notifications@github.com> wrote:

And now I get
/home/pasquale/.nix-profile/bin/deja-dup: error while loading shared
libraries: libdeja.so: cannot open shared object file: No such file or
directory

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nixpkgs/issues/29955#issuecomment-334100203>, or mute
the thread

**Comment by pasqui23** [comment]
Ok,libdeja isn't built together with deja-dup?

**Comment by pasqui23** [comment]
Apparently it is in `/nix/store/q5jrbdl13976z7s0n3hyb728q7zs1qsf-deja-dup-36.1/lib/deja-dup/libdeja.so`

**Comment by jtojnar** [comment]
> Ok,libdeja isn't built together with deja-dup?
It is but it is in uncommon location, therefore not included in the search path. That is why `$out/lib/deja-dup` needs to be appended to rpath manually.

**Comment by jtojnar** [comment]
See this [branch](https://github.com/NixOS/nixpkgs/compare/master...jtojnar:deja-dup?expand=1) for an expression that builds and library paths are fixed.

**Comment by pasqui23** [comment]
And now we get  ```
** (org.gnome.DejaDup:12313): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(org.gnome.DejaDup:12313): GLib-GIO-ERROR **: Settings schema 'org.gnome.DejaDup.File' is not installed

[1]    12313 trace trap  deja-dup```

**Comment by jtojnar** [comment]
Try now. Dejà Dup, unlike most other GNOME apps does not seem to compile schemas. I had to add another step as a `postInstall` hook.

**Comment by pasqui23** [comment]
`dej-dup` does run and display a ui
Unfortunately nothing works,it can't enable auto backups,or add directories to provide/ignore or even change the directory to which do the backup
The interface is there but does not respond

**Comment by jtojnar** [comment]
Any errors? I saw 

    Failed to execute child process “duplicity” (No such file or directory)

and after I added duplicity, it was replaced by

    Error calling StartServiceByName for org.freedesktop.PackageKit: Timeout was reached

Since PackageKit does not have a working Nix backend yet (#21230), we ought to convince deja-dup developers to allow compiling deja-dup without PackageKit.

**Comment by pasqui23** [comment]
Added bug : https://bugs.launchpad.net/deja-dup/+bug/1721244

**Comment by jtojnar** [comment]
Actually, it does not look like it is required. After I removed it, there is another error:

    BackendException: Could not initialize backend: No module named gi.repository

Looks like duplicity is not wrapped correctly. Maybe the [wrapper](https://git.launchpad.net/deja-dup/tree/libdeja/tools/duplicity/duplicity) is stripping `PYTHONPATH` or something.

**Comment by jtojnar** [comment]
On second look, it looks like error in duplicity packaging. The [giobackend](https://bazaar.launchpad.net/~duplicity-team/duplicity/0.8-series/view/head:/duplicity/backends/giobackend.py) requires pygobject and it is not listed in the [derivation](https://github.com/NixOS/nixpkgs/blob/d7d3125ba810018c54b7db7e33e493f682f6f9b0/pkgs/tools/backup/duplicity/default.nix) dependencies.

**Comment by jtojnar** [comment]
Pushed another fix, seems to work now.

**Comment by jtojnar** [comment]
I opened a pull request, do you want to be a maintainer, @pasqui23?
