### ISSUE TITLE
Cannot run `immersed-vr`: `ps: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#299591]
### Describe the bug

I cannot run `immersed-vr`. When trying to run it, I get the following error:

```
[nix-shell:~/repos]$ immersed-vr 
ps: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory
```

### Steps To Reproduce

1. `[you@host:cwd]$ nix-shell -p immersed-vr`
2. `[nix-shellLcwd]$ immersed-vr`

### Expected behavior

`immersed-vr` runs.

### Screenshots

N.A. 

### Additional context

N.A.

### Notify maintainers

@haruki7049

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.20240218.e0da498`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by haruki7049** [comment]
Probably this issue is related to #267408 ...
And I want the version of `immersed-vr` which is caused the `libgpg error`.

**Comment by haruki7049** [comment]
I can reproduce this error under the `shell.nix`!!
```nix
with import (fetchTarball https://github.com/NixOS/nixpkgs/archive/1b27ca3fa7cfa0c50b0103eda76454efd343322e.tar.gz) {};
mkShell {
  packages = [
    immersed-vr
  ];
}
```

My result of `nix-info -m` is here...
```txt
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.20240322.56528ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Pandapip1** [comment]
Yea. I'm pretty sure this is a duplicate. Closing.
