### ISSUE TITLE
Ctrl-C while install package by using "nix-env -i" hangs macOS with multi-user mode

### ISSUE THREAD

**Issue by david50407** [NixOS/nixpkgs#29964]
## Issue description

If I `Ctrl-C` to stop progress while `nix-env -i <package>` is running on macOS with nix multi-user mode, the while computer hangs.

But if I stop the running process by kill or htop(KILL 9), everything works fine.

### Steps to reproduce

1. Use `nix-env -i` to install a package that take long time, for here, use `nix-env -i crystal` to demo.
2. While `nix-env -i crystal` and running "Building phrase", hit `Ctrl-C` to stop the command.
3. After the process stopped, wait for a minute, and the whole computer hangs, the screen freezes.

Last terminal output below: (Recovered from iTerm2)

```
$ nix-env -i crystal-0.23.0-1
installing ‘crystal-0.23.0-1’
these derivations will be built:
  /nix/store/rmbmsa5cjbi7984v12jzk522gs7f5lm8-crystal-0.23.0-1.drv
building path(s) ‘/nix/store/b8jhh6zs40ksw1cmgkrg0xvm1l3yzbhw-crystal-0.23.0-1’
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
Using /nix/store/4zn04v842al058ibl4rrk8xw83zi6v9c-llvm-4.0.1/bin/llvm-config [version=4.0.1]
clang++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/nix/store/4zn04v842al058ibl4rrk8xw83zi6v9c-llvm-4.0.1/bin/llvm-config --cxxflags`
clang -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
./bin/crystal build --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
^Cerror: interrupted by the user
$
```

Stop the running process by kill or htop(KILL 9):

1. Run `nix-env -i crystal`.
2. While `nix-env -i crystal` and running "Building phrase", open `sudo htop` and kill the "crystal" process which is building the binary.
3. After the process stopped, `nix-env` stops gracefully, everything works fine.

## Technical details

* System: `macOS 10.13 High Sierra (17A365)`
* Nix version: `nix-env (Nix) 1.11.15` (multi-user mode)
* Nixpkgs version: `"18.03pre116369.14cbeaa892"`
* Sandboxing enabled: `build-use-sandbox = false`
* Nix worker accounts: 
```
$ dscl . list /Users | grep nixbld
nixbld1
nixbld2
nixbld3
nixbld4
```

**Comment by matthewbauer** [comment]
This is interesting because it's very similar to what I've been experience but with some small differences. See issue NixOS/nix#1583 for more info.

We might as well leave this open to track it on Nix just because not everyone sees the Nix issues.
