### ISSUE TITLE
New maintainers for mednaffe

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#29968]
## Issue description

Not running NixOS at the moment. New job, not a lot of time to devote to right now. Pinging a few of the kind people who've done some mednafen work to see if anyone wants to be marked as a maintainer alongside myself

@yegortimoshenko @joachifm @AmatCoder @Mic92 @AndersonTorres

**Comment by yegortimoshenko** [comment]
I'd be happy to maintain it. I'll add myself to maintainers in #29863.

**Comment by sheenobu** [comment]
@yegortimoshenko oh i meant mednaffe! the gui

**Comment by yegortimoshenko** [comment]
OK :-) I'll add myself to #29958 then.

**Comment by yegortimoshenko** [comment]
https://github.com/yegortimoshenko/nixpkgs/commit/e1cc156f721a130101b4adb2c6b772b51a09821a#diff-cc1185bc304dbfcb5a499fb34dcb382bR27

**Comment by yegortimoshenko** [comment]
https://github.com/yegortimoshenko/nixpkgs/commit/e1cc156f721a130101b4adb2c6b772b51a09821a#diff-cc1185bc304dbfcb5a499fb34dcb382bR27
