### ISSUE TITLE
Xorg loads wrong GLX extension with Nvidia Legacy 390 driver

### ISSUE THREAD

**Issue by ClockGen** [NixOS/nixpkgs#299684]
### Describe the bug
It seems that currently xorg will load wrong GLX extension when using with Nvidia Legacy Driver 390.

It worked as it should on nixos-unstable as of 18.03.24, however currently it's broken on both 23.11 and unstable.

When running a system with nvidia legacy driver 390, xorg needs to load nvidia's libglx.so in order for nvidia driver to have working OpenGL. This, however, doesn't seem to be the case, as Xorg loads its own glx module:

```
[    16.977] (II) LoadModule: "glx"
[    16.977] (II) Loading /nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/extensions/libglx.so
[    16.993] (II) Module glx: vendor="X.Org Foundation"
[    16.993] 	compiled for 1.21.1.11, module version = 1.0.0
[    16.993] 	ABI class: X.Org Server Extension, version 10.0
```

The loaded glx module is provided by xorg, while it should be picked from `/nix/store/v8aivi2zl0igwvyr9bnvbn5z881357fn-nvidia-x11-390.157-6.1.82-bin/lib/xorg/modules/extensions`.

After that, NVIDIA driver complains about the wrong glx module:

```
NVIDIA(0): Enabling 2D acceleration
[    17.041] (EE) NVIDIA(0): Failed to initialize the GLX module; please check in your X
[    17.041] (EE) NVIDIA(0):     log file that the GLX module has been loaded in your X
[    17.041] (EE) NVIDIA(0):     server, and that the module is the NVIDIA GLX module.  If
[    17.041] (EE) NVIDIA(0):     you continue to encounter problems, Please try
[    17.041] (EE) NVIDIA(0):     reinstalling the NVIDIA driver.
```

This results in lack of OpenGL acceleration and glxinfo only reports software rasterizer.

Inspecting further, I see that in my generated xserver.conf the ModulePath for xorg's own modules take precedence over nvidia:

```
Section "Files"

  FontPath "/nix/store/pldlazgzngdppdn39z92w572fzs4q8px-font-cursor-misc-1.0.4/lib/X11/fonts/misc"
  FontPath "/nix/store/2n3gp57bb21vq93ca0817b5g2ip5n2fy-font-misc-misc-1.1.3/lib/X11/fonts/misc"
  FontPath "/nix/store/ck9p96ckrambx53lp7d34chj3b0h0lff-unifont-15.1.04/share/fonts"
  FontPath "/nix/store/j73wmipp6hzqqdc7psbmy98gc29091gz-font-adobe-100dpi-1.0.4/lib/X11/fonts/100dpi"
  FontPath "/nix/store/qak6k67pcsp8xwkxskcqphvh2w2d0mjg-font-adobe-75dpi-1.0.4/lib/X11/fonts/75dpi"
  ModulePath "/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules"
  ModulePath "/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/drivers"
  ModulePath "/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/extensions"
  ModulePath "/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/input"
  ModulePath "/nix/store/kvamicjvw3q031dlj474a6vjxic0jbjb-xf86-input-evdev-2.10.6/lib/xorg/modules/input"
  ModulePath "/nix/store/v8aivi2zl0igwvyr9bnvbn5z881357fn-nvidia-x11-390.157-6.1.82-bin/lib/xorg/modules/drivers"
  ModulePath "/nix/store/v8aivi2zl0igwvyr9bnvbn5z881357fn-nvidia-x11-390.157-6.1.82-bin/lib/xorg/modules/extensions"
  ModulePath "/nix/store/wmaai5v87wmnllh2l3h56wbaadfk9672-xf86-input-libinput-1.4.0/lib/xorg/modules/input"

EndSection
```

Xorg log also reports ModulePath in this order, with xorg being higher than nvidia:

```
[    16.939] (**) ModulePath set to "/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules,/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/drivers,/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/extensions,/nix/store/2zkp7b0qd8msq4ishch4wrjyjdgx4pfk-xorg-server-21.1.11/lib/xorg/modules/input,/nix/store/kvamicjvw3q031dlj474a6vjxic0jbjb-xf86-input-evdev-2.10.6/lib/xorg/modules/input,/nix/store/v8aivi2zl0igwvyr9bnvbn5z881357fn-nvidia-x11-390.157-6.1.82-bin/lib/xorg/modules/drivers,/nix/store/v8aivi2zl0igwvyr9bnvbn5z881357fn-nvidia-x11-390.157-6.1.82-bin/lib/xorg/modules/extensions,/nix/store/wmaai5v87wmnllh2l3h56wbaadfk9672-xf86-input-libinput-1.4.0/lib/xorg/modules/input"
```

The script that generates "Files" section in xserver.conf appears to sort entries in `services.xserver.modules` so their order will vary, depending on their nix store paths (you can see entries are sorted alphabeticially) :
https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/nixos/modules/services/x11/xserver.nix#L124
Thus, sometimes it will work and sometimes it wont, between nix channel updates when nix store paths may change and nvidia-x11 will have a different store path that will be sorted higher than xorg. Trying to add needed paths manually with lib.mkBefore also has no effect since they will be sorted later anyway.

Adding nvidia ModulePath manually via `services.xserver.filesSection` also doesn't work because the script will always put it after the generated paths:
https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/nixos/modules/services/x11/xserver.nix#L130

And even overriding `services.xserver.config` won't work since config contents are generated independently of ModulePaths and appended by the said script:
https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/nixos/modules/services/x11/xserver.nix#L134

I did verify it by remounting my nix store as rw and editing the xorg config manually (just to test, this is a throwaway installation): I moved nvidia-x11 ModulePaths higher than xorg ones and after rebooting it worked as it should, glxinfo reported "Nvidia corporation" vendor and correct renderer instead of llvmpipe.

### Steps To Reproduce
1. Install a bare minimum nixos installation 
2. Install Nvidia Legacy 390 drivers as explained in this guide https://nixos.wiki/wiki/Nvidia
3. Boot into the system to observe lack of hardware acceleration

### Expected behavior
Xorg loading nvidia's libglx.so instead of its own one.

### Additional context
The manual on nixos wiki for installing legacy drivers is outdated: it says to specify legacy driver in `services.xserver.videoDrivers`:

```
  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"]; # or "nvidiaLegacy470 etc.
```

However it will have no effect and nvidia driver wont even be installed in this case.

it was fixed in documentation in https://github.com/NixOS/nixpkgs/commit/fb613a3a41cab4cd098765d1d2c7c92fd9b1762d, but nixos wiki remains outdated.

Also, I'm not sure if this bug also affects other driver versions, since I only tried Legacy 390.

I also posted a thread on nixos forums about this issue before: https://discourse.nixos.org/t/xorg-picks-wrong-libglx-so-with-nvidia-legacy-390-driver/42206

### Notify maintainers
Not sure who should I ping, since xorg.xorgserver listed as having no maintainers.

@ncfavier 
@SuperSandro2000 
@Artturin 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ncfavier** [comment]
The code that generates the `ModulePath` part of the config was last touched by @delroth in https://github.com/NixOS/nixpkgs/pull/230186, and before that 15 years ago.

That PR improved reproducibility by sorting the directories *within* a store path, but also reduced reproducibility by sorting the store paths themselves, making the order dependent on their hashes.

It should be easy enough to keep the intended order of `services.xserver.modules` specified [here](https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/nixos/modules/services/x11/xserver.nix#L802-L806) (note that drivers come before `xorgserver`) while listing the contents of each module reproducibly; I'll open a PR shortly.

Another option would be to merge all the `modules` into a single `ModulePath` with `buildEnv`; this would fix this specific issue since the nvidia packages have a [higher](https://github.com/NixOS/nixpkgs/blob/8f72bd17eae0d1a7fcb63e3f1a3baa7dadebef68/pkgs/os-specific/linux/nvidia-x11/generic.nix#L243) `meta.priority` than `xorgserver`, but I don't know about other drivers.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/299805
