### ISSUE TITLE
gparted: doesn't work on plasma 6 wayland session

### ISSUE THREAD

**Issue by fazo96** [NixOS/nixpkgs#299729]
### Describe the bug
Launching gparted on Plasma 6 wayland doesn't work

### Steps To Reproduce
1. add `pkgs.gparted` to `environment.systemPackages` (in my case I have it in `users.users.myuser.packages`)
2. launch GParted from Plasma 6 Wayland
3. password is promped for elevated privileges. Enter it
4. nothing happens, the window closes

When launching `gparted` from the terminal, this is printed after entering the password:

```
(gpartedbin:7404): Gtk-WARNING **: 11:52:26.506: cannot open display:
```

### Expected behavior
GParted opens (through XWayland I guess)

### Additional context
Other XWayland applications and Wayland applications are both working, through QT and GTK.

### Notify maintainers

The package has no maintainers :( last touched by @r-ryantm so I guess I should notify @ryantm

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 24.05 (Uakari), 24.05pre598085.c75037bbf909`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(fazo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by stupidcomputer** [comment]
I found [this](https://bbs.archlinux.org/viewtopic.php?id=283330) Arch BBS thread that might be related. In it, it says to put `GDK_BACKEND=x11` in your environment. Does that work?

**Comment by fgaz** [comment]
Same error in sway. Setting GDK_BACKEND=x11 does not help

**Comment by kacperwyczawski** [comment]
Same thing on COSMIC:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`

**Comment by Enzime** [comment]
I've opened #328086 that should fix this, can someone test to see if the PR works for you?
