### ISSUE TITLE
Please add 17.09 AMIs

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#29976]
## Issue description
The 17.09 release has been tagged but [the AMIs have not yet been updated](https://github.com/NixOS/nixpkgs/blob/6b922a62202fc89c9142ab626fac9b64b4c3e4fc/nixos/modules/virtualisation/ec2-amis.nix). Please update `ec2-amis.nix` with AMIs.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by davidak** [comment]
They will probably be added when the official announcement is out and the docs updated.

**Comment by vaibhavsagar** [comment]
Thank you @edolstra!
