### ISSUE TITLE
Package request: valkey

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#299796]
**Project description**

A little while ago Redis went closed source, so a community fork of Redis was launched: valkey. A release is expected soon.

Although the name in the README says "PlaceholderKV" it is called "valkey":

https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community

**Metadata**

* homepage URL: https://github.com/valkey-io/valkey
* source URL: https://github.com/valkey-io/valkey
* license: bsd
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Zaczero** [comment]
> Probably it makes sense to wait until the first release

I would prefer to switch the package name now, so I don't forget about it later. I wouldn't want to accidentally continue using redis.

**Comment by Rucadi** [comment]
> > Probably it makes sense to wait until the first release
> 
> I would prefer to switch the package name now, so I don't forget about it later. I wouldn't want to accidentally continue using redis.

The current "releases" in the repo that should be used are still redis with redis commands, instead of "initing" this package as unstable, I would prefer to just wait until they make the release with the naming change in my opinion.

Still, creating the valkey package is trivial since it is just a copy of the redis one.
