### ISSUE TITLE
pkgs.makeWrapper: `die`?

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#29987]
https://github.com/NixOS/nixpkgs/blob/598800d5b12604c1307c5c81515ae9000912a368/pkgs/build-support/setup-hooks/make-wrapper.sh#L7
https://github.com/NixOS/nixpkgs/blob/598800d5b12604c1307c5c81515ae9000912a368/pkgs/build-support/setup-hooks/make-wrapper.sh#L99

I don't think `die` exists in Bash?

**Comment by orivej** [comment]
See https://github.com/NixOS/nixpkgs/blob/598800d5/pkgs/top-level/all-packages.nix#L294 and https://github.com/NixOS/nixpkgs/blob/598800d5/pkgs/build-support/setup-hooks/die.sh

**Comment by vyp** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/die.sh

**Comment by vaibhavsagar** [comment]
Okay, then why am I seeing this?

```bash
$ nix-build -E 'with import <nixpkgs> {}; pkgs.buildEnv { name = "dummy"; paths = []; postBuild = ". ${pkgs.makeWrapper}/nix-support/setup-hook; mkdir somedir; wrapProgram somedir";}'
these derivations will be built:
  /nix/store/jrnq61v75cm04a3k3y1kv4ygqdp9slz0-dummy.drv
building path(s) ‘/nix/store/116ggckzmd09gmgvb0dw1n8l459qmnij-dummy’
created 0 symlinks in user environment
/nix/store/c5yjzh27gv3pjkdnj2fyc587r7wvlqf7-hook/nix-support/setup-hook: line 7: die: command not found
builder for ‘/nix/store/jrnq61v75cm04a3k3y1kv4ygqdp9slz0-dummy.drv’ failed with exit code 127
error: build of ‘/nix/store/jrnq61v75cm04a3k3y1kv4ygqdp9slz0-dummy.drv’ failed
```

**Comment by orivej** [comment]
Because this is not how you should use `makeWrapper`. Look for examples in nixpkgs. Try this:
```
nix-build -E 'with import <nixpkgs> {}; pkgs.buildEnv { name = "dummy"; paths = []; buildInputs = [ makeWrapper ];  postBuild = "mkdir somedir; wrapProgram somedir";}'
```

**Comment by vaibhavsagar** [comment]
Ah, I see. Thanks for your help!
