### ISSUE TITLE
[Rust] How to package crate without Cargo.lock

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#29981]
## Issue description

I want to (locally) package a crate which does not (yet) have a `Cargo.lock` file. I asked how to do this before [on the Mailinglist](https://groups.google.com/forum/#!topic/nix-devel/vQPfaSBUe1Q) but I got no answer which helped me enough to get it packaged.

An example how I want to package it in my local configuration is in the initial email in this thread. There I try to package `imag` 0.3.0, 0.4.0 was released just a few days ago, so if you want to try yourself when helping me, chose either.

As far as I can tell, the `cargoDepsHook` does not get evaluated from my package definition and the `cargoUpdateHook` runs _after_ the check whether a `Cargo.lock` exists, so I cannot use it.

The documentation on this subject is rather sparse... so I guess if I can get it packaged I may update the documentation on the rust packaging a bit :smile:

**Comment by matthiasbeyer** [comment]
@wizeman @Mic92 @the-kenny Pinging you as some of the top-contributors to the rust compiler infrastructure in nixpkgs.

**Comment by the-kenny** [comment]
I'm a bit stale on our current rust infrastructure. I'll try to have a look into it when I find some time.

**Comment by bachp** [comment]
I'm not sure how you could package without a `Cargo.lock` as this would mean that tha dependencies can change over time. 

Maybe you could try to provide a Cargo.lock file as part of your nix derivation if upstream doesn't provide one.

**Comment by matthiasbeyer** [comment]
> Maybe you could try to provide a Cargo.lock file as part of your nix derivation if upstream doesn't provide one.

That's exactly what I tried, but if you studied my initial comment here you'll see that it does not work.

**Comment by Mic92** [comment]
See for an example https://github.com/NixOS/nixpkgs/pull/30088/commits/c3d5fd511c8c049bf61e49f2794a10c5369e2c49

**Comment by Mic92** [comment]
remaining packages (i will continue in the evening, if some packages are left):

- [ ] tokei
- [ ] rq
- [ ] bindgen
- [ ] racer
- [ ] racerd
- [ ] rainicorn
- [ ] rustfmt
- [ ] rustup
- [ ] tw-rs
- [ ] intecture
- [ ] intecture
- [ ] ripgrep
- [ ] staccato
- [ ] xsv
- [ ] tectonic

**Comment by matthiasbeyer** [comment]
I tried the cargoUpdatesHook as well and it didn't work. See my initial message.

**Comment by Mic92** [comment]
How about passing a patched `src` to `buildRustPackage`, you can make it another derivation where you add a `Cargo.lock` file.

**Comment by matthiasbeyer** [comment]
How would I do that?

**Comment by Mic92** [comment]
@matthiasbeyer can you provide also the `Cargo.lock` file?

**Comment by matthiasbeyer** [comment]
Pasted in pastebin because of size: https://pastebin.com/VhzvkPVS

**Comment by Mic92** [comment]
The `Cargo.lock` is in the wrong location:

```
        buildPhase = ''
          mkdir -p $out
          cp ./* -r $out
          cp ${cargoLock} $out/${cratePath}/Cargo.lock
        '';
```

Now there is project-specific, different error.

**Comment by matthiasbeyer** [comment]
I wonder why that is (the wrong path). The project is a multi-crate project and the cargo.lock file should live at the top-level of the project. I will investigate!

**Comment by matthiasbeyer** [comment]
> Now there is project-specific, different error.

This was not necessarily project specific: There exists a crate as a dotfile: `./.imag-documentation` which was not copied to the sources before.

I now have

```
        buildPhase = ''
          mkdir $out -p
          cp ./* -r $out
          cp ./.imag-documentation -r $out

          echo "Copying ${cargoLock} to $out/${cratePath}/Cargo.lock"
          cp ${cargoLock} $out/${cratePath}/Cargo.lock

          echo "Copying ${cargoLock} to $out/Cargo.lock"
          cp ${cargoLock} $out/Cargo.lock

          chmod a+wr $out/${cratePath}/Cargo.lock
          chmod a+wr $out/Cargo.lock
        '';
```

but it fails with

```
error: failed to write /tmp/nix-build-imag-v0.4.0-fetch.drv-0/imag-src/Cargo.lock

Caused by:
  failed to open: /tmp/nix-build-imag-v0.4.0-fetch.drv-0/imag-src/Cargo.lock

Caused by:
  Permission denied (os error 13)
```

**Comment by Mic92** [comment]
you set `$sourceRoot`.

**Comment by matthiasbeyer** [comment]
But cargo should search for the `Cargo.lock` file at the project root, no matter where it is called! At least my cargo does that when building without nix!

**Comment by Mic92** [comment]
You build a subdirectory here, which has its own `Cargo.toml`.

**Comment by matthiasbeyer** [comment]
Yes, but this is a multi-crate project, it has a `Cargo.toml` for the whole workspace! Even when building locally, there is only _one_ `Cargo.lock` for all ~30 crates in this project, and it lives at the top-level directory of the project!

**Comment by Mic92** [comment]
So this is a wrong assumption by `buildRustPackage`, which expects the Cargo.lock in the same directory.

**Comment by matthiasbeyer** [comment]
Well, that explains a lot. I guess I have to dig deeper then.

**Comment by matthiasbeyer** [comment]
Hm, @Mic92 can you point me? [From what I see](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/default.nix#L110) the rust package helper simply calls `cargo build`, which should automatically find the project root and therefor the workspace configuration.

**Comment by Mic92** [comment]
We would need to add an exception here, to not check for `Cargo.lock` file since it will be found the by `cargo` eventually.

**Comment by matthiasbeyer** [comment]
Hm,... I would not do this,... I would rather check whether a `Cargo.lock` exists in the current directory or any directory above the `sourceRoot`... this way we would still guarantee that one is present. Though, its a bit harder to implement, I guess.

**Comment by Mic92** [comment]
a while loop, which looks for `Cargo.lock` until it hits `/nix/store/<directory>`

**Comment by vincentbernat** [comment]
I'd like to update svgcleaner but upstream stopped shipping `Cargo.lock`. What is the best way today for such situations?

**Comment by rasendubi** [comment]
(triage) @Mic92 @matthiasbeyer are there any action items left to close the issue?

**Comment by Mic92** [comment]
this was solved.

**Comment by monomadic** [comment]
I just want to chime in here, Cargo.lock in rust projects is NOT always necessary nor recommended. Core rust devs even mention this. See https://github.com/rust-lang/cargo/issues/315 - conventional wisdom is not to include a cargo.lock for libraries.

**Comment by Mic92** [comment]
Yes. We mostly build applications with very few exceptions. There are now mechanism to add missing `Cargo.lock` files: https://github.com/NixOS/nixpkgs/blob/d96959a6296b8ff44787236ee4ba138678360543/pkgs/tools/package-management/cargo-license/default.nix#L14

**Comment by SoftwareApe** [comment]
@Mic92 posted the answer that worked for me. For discoverability it would be great if this was suggested when the package doesn't have a Cargo.lock instead of leaving the user stranded looking for an answer.

**Comment by Mic92** [comment]
Added here: https://github.com/NixOS/nixpkgs/pull/89523

**Comment by yonghan** [comment]
How would you write that patch file? Sorry I am not a rust developer just wanted to package something not already in nixpkgs.
