### ISSUE TITLE
Geary doesn`t get removed when included in excludePackages

### ISSUE THREAD

**Issue by AldebaraanMKII** [NixOS/nixpkgs#299877]
### Describe the bug
When using cinnamon, adding geary to excludePackages list doesn`t remove it after building the configuration:

  environment.cinnamon.excludePackages = [
    pkgs.gnome.geary
  ];

I didn`t test other DEs that have it by default.
	
### Steps To Reproduce
1. add  pkgs.gnome.geary to environment.cinnamon.excludePackages list
2. build your config
3. log out and in

### Expected behavior
That it gets removed like the other packages in the list

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.79, NixOS, 23.11 (Tapir), 23.11.4835.c8e74c2f83fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Aleksanaa** [comment]
Geary isn't installed this way:
https://github.com/NixOS/nixpkgs/blob/2726f127c15a4cc9810843b96cad73c7eb39e443/nixos/modules/services/x11/desktop-managers/cinnamon.nix#L231
Use `programs.geary.enable = false` instead

**Comment by bobby285271** [comment]
Fixed by the above PR.
