### ISSUE TITLE
Package request: textpieces

### ISSUE THREAD

**Issue by zentag** [NixOS/nixpkgs#299991]
**Project description**
Small tool for quick text transformations such as checksums, encoding, decoding and so on. Written in Vala for GNOME desktop.

**Metadata**

* homepage URL: https://apps.gnome.org/Textpieces/
* source URL: https://github.com/liferooter/textpieces
* license: GPL 3.0
* platforms: linux

**Comment by Aleksanaa** [comment]
We already have this back in 23.11
