### ISSUE TITLE
kavita: package update missing db migrations

### ISSUE THREAD

**Issue by davidkna** [NixOS/nixpkgs#299964]
### Describe the bug
After updating from kavita v0.7.1.4 to v0.7.13 via #281236, I got a message that my user was disabled. [Upstream recommends](https://wiki.kavitareader.com/en/install/linux-install#4-updating-kavita) updating at most two versions at a time because database migrations [are removed between releases](https://www.github.com/Kareadita/Kavita/issues/2713#issuecomment-1939169328).

### Steps To Reproduce
1. Set up older kavita version, e.g., v0.7.1.4
2. Upgrade to v0.7.13

### Expected behavior
All migrations are handled on update.

### Notify maintainers

@nevivurn @Misterio77

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.11, NixOS, 24.05 (Uakari), 24.05.20240328.867036f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7wd43cfbf9sbwlnl89c8ymlbpfxwfyas-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nevivurn** [comment]
Oof, did not realize migrations didn't work. A bit confused as to how we would go around solving this in nixpkgs. No matter what we do, it seems like it would require manual intervention by the user when choosing the correct upgrade path.
