### ISSUE TITLE
Git's interactive.singlekey configuration setting does not work

### ISSUE THREAD

**Issue by mboes** [NixOS/nixpkgs#29996]
## Issue description

When setting `interactive.singlekey = true` in `~/.gitconfig`, the user gets a warning when using any command that use `git-add--interactive` under the hood:

```
missing Term::ReadKey, disabling interactive.singlekey
```

The setting is ineffective. Users still need to press the Enter key at each prompt.

### Steps to reproduce

Add the above mentioned setting to `~/.gitconfig`. Notice the warning e.g. with `git commit -p` in any Git repository with a dirty working tree.

## Technical details

* System: 18.03pre116347.272c0bf88c (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre116572.9824ca6975

**Comment by zimbatm** [comment]
Fixed by #30001
