### ISSUE TITLE
documentation error in "14.4. Manual CA management"

### ISSUE THREAD

**Issue by roymarantz** [NixOS/nixpkgs#29993]
## Issue description

in the 17.03 NixOS manual the start of section 14.4. Manual CA management has information that should be at the end of the previous section.

## Technical details

* System: NixOS
* Nix version: 17.03
* Nixpkgs version: N/A
* Sandboxing enabled: N/A

**Comment by iblech** [comment]
Can you clarify what you mean, @roymarantz?

I see exactly one paragraph at https://nixos.org/nixos/manual/index.html#idm140737316357600. What would you change?

**Comment by roymarantz** [comment]
Perhaps my confusion is what certificates have to to with a todo list application although upon rereading the docs I see that certificates are used for authentication.  Please close this issue since it is obvious my confusion and lack of understanding of what (and how) taskserver is doing.

**Comment by me-and** [comment]
Closing as requested by OP.
