### ISSUE TITLE
jotta-cli: missing run_jottad command

### ISSUE THREAD

**Issue by Nichlas** [NixOS/nixpkgs#300063]
### Describe the bug

After installing the jotta-cli package it is not possible to start the application because the required `run_jottad` command is not available.

### Steps To Reproduce
install jotta-cli

run_jottad (as user)

### Expected behavior

Expected is that run_jottad is executed and initialises jotta-cli for the user.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05pre603596.2726f127c15a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dwf** [comment]
@evenbrenden

**Comment by evenbrenden** [comment]
`run_jottad` is bundled with the AUR, Debian and RPM releases. Looks like it sets up a `systemd` service that runs `jottad`. For Nix, we should consider declaring a similar service in a NixOS or Home Manager module instead.

I can look into this, but should mention that I'm no longer using `jotta-cli`. Ideally, someone who needs and uses such a service should maintain it (and the package). So if anyone else wants to take a stab at this, please do :)

**Comment by evenbrenden** [comment]
> After installing the jotta-cli package it is not possible to start the application because the required run_jottad command is not available.

The application can be started like this:

```
jottad &
jotta-cli <command>
```

**Comment by evenbrenden** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/302570.

**Comment by evenbrenden** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/302570.
