### ISSUE TITLE
Multiuser mode in darwin freezes

### ISSUE THREAD

**Issue by jbaum98** [NixOS/nixpkgs#30008]
## Issue description

Installed `nix` with the new `install.sh` that installs multiuser mode using `nix-daemon`. Now very often when I build anything, my entire computer freezes and needs to be force shutdown.

### Steps to reproduce

Build any derivation not in the store. For example, run `nix-collect-garbage` or make sure that `hello` isn't in the store, and run
```shell
nix-build "<nixpkgs>" -A hello --option build-use-substitutes false
```

## Technical details

* System: OSX 10.13
* Nix version: 1.11.15
* Nixpkgs version: 8.03pre116432.263185aa68
* Sandboxing enabled: false

**Comment by matthewbauer** [comment]
See Nixos/nix#1583.
