### ISSUE TITLE
hydra service fails to start in NixOS 17.09

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#30004]
## Issue description

System log shows:

```
hydra-init[2819]: DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=hydra;user=hydra;','',...) failed: FATAL:  role "hydra" does not exist at /nix/store/dvwfc8dphiam30ahx5ii49yryi0fvdps-hydra-perl-deps/lib/perl5/site_perl/5.24.2/DBIx/Class/Storage/DBI.pm line 1517. at /nix/store/nvvgaiihyfib911zzspsxh65271m5aj6-hydra-2017-09-14/bin/.hydra-init-wrapped line 12
```

The service starts fine in NixOS 17.03, but not in 17.09.

### Steps to reproduce
Enable hydra service (```services.hydra.enable = true;```) and activate with ```nixos-rebuild switch```.

**Comment by dtzWill** [comment]
Hmm, I expect this is a problem that only occurs when upgrading (migration?)-- we have a test for Hydra on a clean configuration which seems to work when I try it locally.

Can't find the hydra job that runs the tests but I'm sure it's there :).

What postgres version did you use previously, and which is it using now?
What's the status of the postgres service?

**Comment by bjornfor** [comment]
Ah, right. I have not set system.stateVersion, so when upgrading to 17.09 I got a new postgresql version and, probably most importantly, a _new services.postgresql.dataDir_! Thanks for the hint! Closing.
