### ISSUE TITLE
The Nix package produces an invalid dev include directory

### ISSUE THREAD

**Issue by KubC08** [NixOS/nixpkgs#300092]
### Describe the bug
Upon using the Nix package within "buildInputs" and using one of the headers that calls upon value/context.hh, there is always an error that "util.hh" could not be found. Upon viewing the store directory of nix/include/nix directory, there is a clear util.hh however the problematic header is inside value/context.hh which does not contain a util.hh file.

Attempting to use a newer version of Nix (higher than 2.18) the error changes to "comparator.hh" missing in the same file.

### Steps To Reproduce
1. Include nix in "buildInputs" of a package
2. Add code that uses anything within libexpr (primops.hh)
3. Run "nix build" on the package

### Expected behavior
The package would build normally.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/54985640/a310bc44-ef4c-40d7-b7f0-722b100d4ecd)
![image](https://github.com/NixOS/nixpkgs/assets/54985640/fb2b824b-b045-4102-a31c-acb4e52b3de7)

### Additional context
None.

### Notify maintainers
@eelcovisser @lovesegfault @Artturin @Ma27 

### Metadata
```nix
{
	lib,
	stdenv,
	premake5,
	gcc,
	gnumake,
	nix,
}:

stdenv.mkDerivation {
	pname = "X";
	version = "1.0.0";
	src = ./;

	nativeBuildInputs = [ premake5 gcc gnumake ];
	buildInputs = [ nix ];

	makeFlags = [ "config=release_linux" ];

	meta = with lib; {
		description = "X";
		homepage = "X";
		license = licenses.gpl3;
		platforms = [ "x86_64-linux" ];
	};
}
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KubC08** [comment]
Quick note, if anyone else is having an issue with this, here is a quick solution:
```nix
propagatedBuildInputs = [ nix ];

preBuild = ''
  # Temporary fix for nix compile error (https://github.com/NixOS/nixpkgs/issues/300092)
  export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE -isystem $propagatedBuildInputs/include/nix"
'';
```

**Comment by Ma27** [comment]
Would you mind elaborating how your build system looks like?
The `.pc` files in the dev output appear to set an include path just like you do in the change above:

```
$ cat /nix/store/3l3vv298sxp14fx7qyrja98a7hv39wc8-nix-2.21.1-dev/lib/pkgconfig/nix-cmd.pc 
prefix=/nix/store/37cpz75hiy7gm0a6l4cpl2v14xpg0r4p-nix-2.21.1
libdir=/nix/store/37cpz75hiy7gm0a6l4cpl2v14xpg0r4p-nix-2.21.1/lib
includedir=/nix/store/3l3vv298sxp14fx7qyrja98a7hv39wc8-nix-2.21.1-dev/include

Name: Nix
Description: Nix Package Manager
Version: 2.21.1
Libs: -L${libdir} -lnixcmd
Cflags: -I${includedir}/nix -std=c++2a
```

**Comment by KubC08** [comment]
> Would you mind elaborating how your build system looks like? The `.pc` files in the dev output appear to set an include path just like you do in the change above:

The only other part I have left from the build system is the premake5 file, other than that I do not modify anything else. Here's the script below:
```lua
---@diagnostic disable: undefined-global

function GetFromRoot(path)
    return string.format("%s/%s", _MAIN_SCRIPT_DIR, path)
end

BIN_DIR = GetFromRoot("bin/%{cfg.buildcfg}/%{cfg.platform}")
OBJ_DIR = GetFromRoot("obj/%{cfg.buildcfg}/%{cfg.platform}/%{prj.name}")

workspace("X")
    configurations({ "Debug", "Release" })
    platforms({ "Linux" })
    architecture("x86_64")

    filter({ "platforms:Linux" })
        system("linux")
        defines({"_UNIX"})

    project("X")
        kind("SharedLib")
        language("C++")
        cppdialect("C++20")
        targetdir(BIN_DIR)
        objdir(OBJ_DIR)

        
        files({
            "src/**.h", "src/**.hpp", "src/**.hh",
            "src/**.cpp", "src/**.cc"
        })
        includedirs({ "src" })

        libdirs({ "lib" })
        externalincludedirs({
            "external",
        })
        links({ "lua:shared" })


        filter("configurations:Debug")
            defines({"DEBUG"})
            symbols("On")

        filter("configurations:Release")
            defines({"NDEBUG"})
            optimize("On")
```

upon trying to build it without the "fix" I get the following output from nix-cmd.pc:
```
prefix=/nix/store/cydbsmqkxk30didm1rlz8ffk5wfa9gva-nix-2.18.2
libdir=/nix/store/cydbsmqkxk30didm1rlz8ffk5wfa9gva-nix-2.18.2/lib
includedir=/nix/store/crg277a2q85zgsz2599d3x0nmz9vf709-nix-2.18.2-dev/include

Name: Nix
Description: Nix Package Manager
Version: 2.18.2
Libs: -L${libdir} -lnixcmd
Cflags: -I${includedir}/nix -std=c++2a
```

After dumping the NIX_CFLAGS_COMPILE I ended up getting the following output (removed the other junk to make it smaller):
```
-frandom-seed=xzgm8nqvll -isystem /nix/store/crg277a2q85zgsz2599d3x0nmz9vf709-nix-2.18.2-dev/include -isystem /nix/store/crg277a2q85zgsz2599d3x0nmz9vf709-nix-2.18.2-dev/include
```

And yes, it was duplicated directly in the dump of the environment variable.

**Comment by Artturin** [comment]
I have seen many packages have subdirs in `include`, which I assume means you should use pkg-config to get the variables needed. Also this issue should not be in nixpkgs but in nix but no need to move it there because there's no bug, just a thing that has to be fixed in the build system.
