### ISSUE TITLE
GCC wrapper messes up glibc build

### ISSUE THREAD

**Issue by waldheinz** [NixOS/nixpkgs#30015]
## Issue description

The hardening part of the GCC wrapper script prevents glibc being built (outside of nix, just garb the source tarball and try to build it). One problem is that the wrapper injects `-D_FORTIFY_SOURCE` into the command line, which glibc does not like. This is already worked around here:

> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glibc/default.nix#L34

Please note that the gcc invocation issued by the glibc build system has an `-U_FORTIFY_SOURCE` argument, so it's very explicit that this is not wanted and feels like an error for the wrapper to force fortification here.

One solution would be to detect the presence of `-U_FORTIFY_SOURCE` and then let the wrapper refer from adding it back in.

A simpler solution might be to move the `hardeningCFlags` here:

> https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L130

from `extraAfter` to `extraBefore`, so command line arguments (where specified)  "win" over what the wrapper wants. Either solution might make the `hardeningDisable` here:

> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glibc/default.nix#L34

and potentially in many other places (didn't check that) obsolete, which seems like a good thing.

### Steps to reproduce

Try to compile glibc with the nixos-provided GCC.

## Technical details

(i skip those because the issue is very general)

**Comment by joachifm** [comment]
Looks like another instance of https://github.com/NixOS/nixpkgs/issues/18995

**Comment by waldheinz** [comment]
@joachifm It is, thanks for the pointer.
