### ISSUE TITLE
LibreWolf is missing some settings

### ISSUE THREAD

**Issue by awebeer256** [NixOS/nixpkgs#300107]
### Describe the bug
The Nix version of LibreWolf is missing the "LibreWolf" page of its settings.

### Steps To Reproduce
1. Install the `librewolf` Nix package.
2. Run the resulting `librewolf` program.
3. Navigate to `about:preferences`.

### Expected behavior
On the top-left, you should see a list of categories:
- General
- Home
- Search
- Privacy & Security
- LibreWolf

And if you've enabled Firefox Sync on the LibreWolf page, you'll also see:
- Sync

### Actual behaviour
The "LibreWolf" category does not appear.

### Screenshots
Expected (taken from the Flatpak package):
![screenshot-lw-prefs](https://github.com/NixOS/nixpkgs/assets/26385859/aaf0b187-9fa6-4229-bef5-057f9b64a486)

Actual:
![screenshot-lw-prefs-missing](https://github.com/NixOS/nixpkgs/assets/26385859/8ebdcb6c-1c87-40cc-8916-74f52494ce4e)

### Additional context
I noticed this bug appear somewhere in the past…6 months I think, but I didn't bother reporting it until now because I've already changed all of the settings in the missing category that I want to, so I wasn't personally impacted.

### Notify maintainers
@squalus 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.10, NixOS, 23.11 (Tapir), 23.11.5648.44733514b72e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-small-23.11-small, nixos-unstable, nixos-unstablesmall"`
 - channels(<myusername>): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by soymadip** [comment]
Yeah, I am seeing this too, it's pretty annoying for new users. 
For now using override.conf file, but this is not permanent solution

**Comment by threadpanic** [comment]
Hi, I saw someone mentioning this bug in the Matrix chat. I didn't know about Nix and this particular problem. So something is different between Nix and Flatpak. If I remember correctly, Flatpak uses a lot of environment variables to make things work.. maybe that's something. I've looked at our preferences panel source. It could be that our code module fails to initialize for some reason. [code](https://codeberg.org/librewolf/source/src/branch/main/patches/pref-pane/pref-pane-small.patch#L29) Something with IPC or so might make this fail? Hope this helps, thanks

**Comment by squalus** [comment]
> Yeah, I am seeing this too, it's pretty annoying for new users. For now using override.conf file, but this is not permanent solution

What's in your override.conf file that makes this work?

**Comment by xevrem** [comment]
from a cursory parusal of the librewolf nix files, this is -NOT- librewolf, its basically a hacked together variant of mozilla firefox. i.e., its not actually constructed from a core librewolf build... its not even mentioned on the librewolf.net page as a supported version...

If you want Librewolf on nix, use the flatpak. This needs to be built from the ground up as librewolf to be sure it meets the intent.

**Comment by Snuupy** [comment]
> If you want Librewolf on nix, use the flatpak. This needs to be built from the ground up as librewolf to be sure it meets the intent.

I tried the flatpak but the cursor size is way too small on hidpi displays https://github.com/flathub/io.gitlab.librewolf-community/issues/121. Firefox flatpak on nixos has this issue as well.

**Comment by squalus** [comment]
> from a cursory parusal of the librewolf nix files, this is -NOT- librewolf. Its basically a hacked together variant of mozilla firefox. i.e., its not actually constructed from a core librewolf build... its not even mentioned on the librewolf.net page as a supported version...
> 
> If you want Librewolf on nix, use the flatpak. This needs to be built from the ground up as librewolf to be sure it meets the intent.

Librewolf is a variant of Firefox. It's Firefox, plus some build options, plus some patches. The Nix build reuses the upstream patch set and build options.

The Nix package is a reproducible, from-source build of Librewolf. It is maintained by nixpkgs maintainers, not the upstream project.

Certain aspects of the Librewolf build script make it unusable in a Nix context. For example, it fetches things from the network without checking hashes. So that part is not re-used in the Nix package.

For those that prefer using upstream binaries, I'm not opposed to having a librewolf-bin package in nixpkgs.
