### ISSUE TITLE
Build failure: kstars

### ISSUE THREAD

**Issue by sheepforce** [NixOS/nixpkgs#300227]
### Steps To Reproduce

There is a hash mismatch for kstars in nixpkgs-unstable

1. `nix build nixpkgs#kstars`

### Build log

```
$ nix build nixpkgs#kstars
error: hash mismatch in fixed-output derivation '/nix/store/0ps64p08rn47dwp7bvn5fvnlcd6qya3h-source.drv':
         specified: sha256-28RRW+ncMiQcBb/lybEKTeV08ZkF3IqLkeTHNW5nhls=
            got:    sha256-enID8edG6JS0uOeHFnPjswHXSp2v444JKf/388/2DzI=
error: 1 dependencies of derivation '/nix/store/ds1ipaxn309705gwibzxcvrp4dgqr5w0-kstars-3.6.9.drv' failed to build
```

### Notify maintainers

@timput
@hjones2199

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.23, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kilianar** [comment]
Last updated by @bzizou

**Comment by panicgh** [comment]
As was spotted during the PR review https://github.com/NixOS/nixpkgs/pull/281099#discussion_r1486018642, the ref `stable-3.6.9` is a branch not a tag.

**Comment by bzizou** [comment]
The source of the problem is (also mentionned in a #281099 comment) a typo in the name of the latest version of kstars
 files (https://bugs.kde.org/show_bug.cgi?id=480853). 
There's now a 3.7.0 version out. So I'll suggest a new PR with this version, using the official source
