### ISSUE TITLE
Pymol missing Pwm

### ISSUE THREAD

**Issue by luancarvalhomartins** [NixOS/nixpkgs#30027]
## Issue description

Pymol fails to properly load due to missing Pwm python module.

### Steps to reproduce

Install pymol, try to run it.

## Technical details

* System: 17.03.1890.41c9543f84 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1890.41c9543f84"
* Sandboxing enabled: build-use-sandbox = false

**Comment by FRidh** [comment]
> Install pymol, try to run it.

Install exactly how?

**Comment by FRidh** [comment]
Closing due to lack of feedback.

**Comment by orivej** [comment]
The details say that @luancarvalhomartins is using 17.03. However, we support only 17.09 and unstable.
