### ISSUE TITLE
Build failure: Authy

### ISSUE THREAD

**Issue by Stefanidze-Dev** [NixOS/nixpkgs#300252]
### Steps To Reproduce

1. build *Authy*, stable or unstable channel

### Build log

```console
building '/nix/store/j7v7md0cp58li621jd36qk0f1xnkhzw2-H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap.drv'...

trying https://api.snapcraft.io/api/v1/snaps/download/H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   205    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap from any mirror
error: builder for '/nix/store/j7v7md0cp58li621jd36qk0f1xnkhzw2-H8ZpNgIoPyvmkgxOWw5MSzsXK1wRZiHn_21.snap.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/kvlivs4myj4pwbifpl2qbmsx8l2brlym-authy-2.4.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lymka0ll326k2ndisknyyh1hp8iagknd-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/24q0x4gr5ikypwjs20h6099ilpc74l6x-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/adwwkvxi38hriz3pnqa6wgknxxkh51f5-nixos-system-nixos-23.11.5742.219951b495fc.drv' failed to build

```

### Additional context

No additional context, seems like the package of one of the dependencies was taken off snap for some reason

### Notify maintainers
Could not run `nix eval` for some reason...

### Metadata
```console
[stefanidze@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5541.56528ee42526`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by delliottxyz** [comment]
It seems that Twilio have deprecated the desktop apps. 
[Their announcement](https://www.twilio.com/en-us/changelog/end-of-life--eol--of-twilio-authy-desktop-apps).

Looking on [Snapcraft](https://snapcraft.io/search?q=authy) it seems that they have pulled the snap from Snapcraft.
It also seems that Flatpak app has also been removed. See [here](https://github.com/flathub/com.authy.Authy) and [here](https://flathub.org/apps/search?q=authy).

**Comment by Stefanidze-Dev** [comment]
Well, i suppose there is nothing that can be done.
Thanks for explaining the situation to me!

**Comment by delliottxyz** [comment]
I'm not sure that issue is really resolved, as I think we need to remove the package from nixpkgs as its deprecated. 

@iAmMrinal0 I believe you are the package maintainer. Should it maybe be removed?

**Comment by iAmMrinal0** [comment]
Thanks for the tag and explanation, @delliottxyz! I had read the announcement when it came out and the apps were still available on Snapcraft. It must have been pulled after a while.
It's better to remove the package now. I'll do it sometime this week.
