### ISSUE TITLE
Deprecate cgmanager and switch to pam module for lxcfs

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#30023]
## Issue description

was deprecated by upstream: https://github.com/lxc/lxc/issues/1554#issuecomment-333567285

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by sorki** [comment]
Summary of changes I've done so far

**Comment by Mic92** [comment]
@sorki can you open this as a pull request? I could add the missing pieces there.

**Comment by Mic92** [comment]
will be closed by https://github.com/NixOS/nixpkgs/pull/89525
