### ISSUE TITLE
A GNOME Shell extension breaks GNOME Shell

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#30022]
## Issue description

If i have [this **system-monitor**](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) GNOME Shell extension enabled, i cannot log in to GNOME desktop manager.

This behaviour is new in NixOS 17.09.  This extensions never worked under NixOS, but at least GNOME Shell didn't break because of it in NixOS 17.03.

### Steps to reproduce

Under GNOME Shell/desktop manager, go to the [extension's page](https://extensions.gnome.org/extension/120/system-monitor/) on https://extensions.gnome.org/ with [Web](https://wiki.gnome.org/Apps/Web) web browser and install-enable it.  Log out and try to log in again (to GNOME).  Logging-in fails, taking back to the login prompt.

## Technical details

* NixOS: `17.09.1455.b61d084c41 (Hummingbird)`
* Nix version: `1.11.15`
* Nixpkgs version: `17.09.1455.b61d084c41`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by jtojnar** [comment]
Can you check the system journal for errors? (ctrl-alt-f5 to swtich to tty, login and then `journalctl -b`)

**Comment by alexeymuranov** [comment]
@jtojnar, [here](https://gist.github.com/alexeymuranov/dd2cf92b2447a917d2b8bd9e47f86884).

I created a fresh non-admin user for testing this issue. `journalctl` warned me that system messages are not included (i ran it as that user).

**Comment by jtojnar** [comment]
This looks suspicious:

    Oct 05 20:26:55 Alexey-BU403UA-NixOS .gnome-shell-wr[1160]: Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found

Try adding `pkgs.gnome3.libgtop` to `services.xserver.desktopManager.gnome3.sessionPath`

**Comment by alexeymuranov** [comment]
Could you please show me exactly which line to add to my config?

In any case, isn't this a bug when shell kicks me out just because of installing an extension, without `sudo`?

**Comment by jtojnar** [comment]
You should add `services.xserver.desktopManager.gnome3.sessionPath = [ pkgs.gnome3.libgtop ];`.

It is a bug in GNOME Shell, probably a deep architectural flaw since it is so common.

**Comment by jtojnar** [comment]
Apparently it should be just `pkgs.libgtop`.

**Comment by alexeymuranov** [comment]
Still the same behaviour, [here](https://gist.github.com/alexeymuranov/d6095dbb02bd365904130a731ee04a56) is the new `journalctl` output.

**Comment by jtojnar** [comment]
There is also

    .gnome-shell-wr[1219]: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered

try adding pkgs.packagekit to the `sessionPath` option.

**Comment by alexeymuranov** [comment]
Still the same story, [here](https://gist.github.com/alexeymuranov/25ed7f1380b2f001bab9665a7b91f873) is the new output.

**Comment by jtojnar** [comment]
I do not see anything suspicious any more. You can try reporting the error [upstream](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet).

**Comment by alexeymuranov** [comment]
Do you think it is plugin's responsibility to not crush GNOME Shell?  Maybe GNOME is a more appropriate upstream?

**Comment by jtojnar** [comment]
I think there is a bug in the extension, that in any sane system would crash the extension. That one should be possible to fix reasonably quickly.

There is also another bug in the GNOME Shell, that when extension would crash in a sane system, the Shell crashes as well. That one is probably a deeper architectural flaw, otherwise GNOME Shell developers would do something about it a long time ago. It should also be reported but I do not think it can be fixed it without re-engineering the GNOME Shell architecture.

**Comment by deedrah** [comment]
I have encountered similar behavior as @alexeymuranov. I found in logs that `org.gnome.SettingsDaemon.Datetime.desktop` was segfaulting. I was able to fix my account by running `dconf reset /org/gnome/desktop/datetime/automatic-timezone`. This happens everytime when I try turn on `Automatic Time Zone` in `Date & Time` settings in gnome. So it looks like a different issue.

**Comment by hdonnay** [comment]
`gsd-datetime` also segfaults on my system after upgrade to 17.09

**Comment by alexeymuranov** [comment]
I tried resetting `/org/gnome/desktop/datetime/automatic-timezone`, but it didn't help.

(I still had no time to investigate this second issue.)

**Comment by alexeymuranov** [comment]
*About this second (possibly unrelated) issue with `automatic-timezone`*. 

I tried resetting `/org/gnome/desktop/datetime/automatic-timezone` once several days ago with dconf GUI, and i believe it didn't help (?...), but today i tried again from command line, and it helped. Then i tried enabling and resetting `automatic-timezone` from both CLI and GUI dconf, and both had the same effect.

So, i could reproduce the issue in my main account: if i execute
```shell
dconf write /org/gnome/desktop/datetime/automatic-timezone true
```
and the internet is connected, i am kicked out to the login prompt.  To fix this, it suffices to execute
```shell
dconf reset /org/gnome/desktop/datetime/automatic-timezone
```

However, *i could not reproduce this in a fresh account*, so i cannot report this as a separate issue yet.

**Comment by mickours** [comment]
FYI, I managed to make this extension works following https://github.com/NixOS/nixpkgs/issues/30022#issuecomment-334570296 by adding this to my configuration.nix file:
```nix
services.xserver.desktopManager.gnome3.sessionPath = [
pkgs.json_glib
pkgs.glib_networking
pkgs.libgtop ];
```
Not sure if all of this is necessary.

Note that a simple ``nixos-rebuild switch`` is not enough,  you MUST restart the display manager (or reboot) to make this works

**Comment by alexeymuranov** [comment]
@mickours, strange, i've added
```nix
{ # ...
  services.xserver.desktopManager.gnome3.sessionPath = [
    pkgs.glib_networking
    pkgs.json_glib
    pkgs.libgtop
    pkgs.packagekit
  ];
}
```
but my gnome session still breaks if i enable this extension.

**Comment by alexeymuranov** [comment]
After an update to the extension, it is still not working, but does not cash Gnome Shell any more.

I am closing this for now.

**Comment by jtojnar** [comment]
This might help https://github.com/NixOS/nixpkgs/pull/36410
