### ISSUE TITLE
gogs: Non-NixOS installations need manual rewriting of git hooks on upgrade

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#30048]
## Issue description
During regular usage `gogs` creates `git` hooks that look like this:
```
#!/nix/store/p4csf5alczckcj6j4byc211kpw6ir0kz-coreutils-8.26/bin/env bash
"/nix/store/dbx6h0sa6z2jzd7jw2kyp5hygylhlv7p-gogs-0.9.113-bin/bin/gogs" update $1 $2 $3 --config=/home/gogs/custom/conf/app.ini'
```
This hard-coding of the installation directory of course leads to problems on an upgrade.
While on NixOS this is solved by the [gogs service module](https://github.com/NixOS/nixpkgs/blob/9d841295f3da4e02d7b7e87fac86b25cd1081f36/nixos/modules/services/misc/gogs.nix#L227) as discussed [here](https://github.com/NixOS/nixpkgs/pull/19361#issuecomment-255535192), upgrading gogs on Non-NixOS means one manually has to run "Rewrite all update hooks of repositories (needed when custom config path is changed)" in the admin-Dashboard.

## Technical details

* System: openSUSE 12
* Nix version: 1.11.7
* Nixpkgs version: 17.09pre102922.22c2651
* Sandboxing enabled: No

**Comment by bobvanderlinden** [comment]
This is where the hooks are defined:
https://github.com/gogits/gogs/blob/643c85e9c8fd237912652d14a0535dfddf614d2b/models/repo.go#L774-L776

This is where the hook patterns are filled in:
https://github.com/gogits/gogs/blob/643c85e9c8fd237912652d14a0535dfddf614d2b/models/repo.go#L783

You can see it will use setting.AppPath, which in turn is the executable path: https://github.com/gogits/gogs/blob/ab2c6cb00870991c33a7e7c7a22c47db1f48a9bb/pkg/setting/setting.go#L340

I'm not sure how to fix this properly. Ssh needs to know what gogs to run, gogs will set the path in hooks. Maybe a symlink of the gogs executable should be placed in the data-dir and have the hooks refer to that executable. This will probably require changes to gogs: using a different path compared to AppPath. And creating a symlink from the wrapper script. That last step has shown its downsides.

I'm not sure how to solve this properly for ad-hoc running of gogs.

**Comment by orivej** [comment]
Looking at those links it can be seen that the current version of gogs already does what we want: it writes the path that was used to launch it (rather than, say, `os.Executable()`, which effectively resolves symlinks). When I launched `gogs` installed with `nix-env`, it used a stable path `/home/user/.nix-profile/bin/gogs`.

**Comment by bobvanderlinden** [comment]
That's a very keen observation. So the only next addition would be to have a cli version of 'rewrite all hooks'. I guess that's an issue for gogs and not so much for nixos.

**Comment by orivej** [comment]
This a one time operation (assuming a single gogs installation), so a cli version won't be very useful.

However, looking at `git blame` it seems that gogs behaved like that for a long time. @knedlsepp , could you launch gogs in a new directory, create a repository and see if hooks point to a nix profile or to `/nix/store`?

**Comment by knedlsepp** [comment]
It seems that gogs installed via `nix-env -iA` actually uses the `~/.nix-profile` link in the hooks. Currently I however have a nix-installed wrapper for gogs on openSUSE that I basically use as a poor man's daemon which restarts it on failure. As this uses `${pkgs.gogs}` as a dependency I get the `/nix/store/...` path in the hooks instead. I initially also did this to prevent myself from running gogs directly (and create all those symlinks), and to enforce using my wrapper that `cd`s to the right directory. While the symlink issue is gone, I still don't want to depend on it being installed in the '~/.nix-profile`.

What would be the downsides of moving the `sed` based rewriting currently implemented in the NixOS module into the wrapper?

**Comment by orivej** [comment]
This can be done in the wrapper, with care not to rewrite hooks when Gogs is called from the hooks. However, patching Gogs to always rewrite hooks when it starts the web server seems better.

**Comment by knedlsepp** [comment]
I made PR to gogs that adds command line options for rewriting the hooks: https://github.com/gogits/gogs/pull/4813

**Comment by bobvanderlinden** [comment]
Yay for getting it merged! Now we wait for a next release...

**Comment by emilylange** [comment]
Closing as gogs has been removed from nixpkgs a few minutes ago.
See #348053 for some more details.
