### ISSUE TITLE
nvim-treesitter update.py fails if ran directly 

### ISSUE THREAD

**Issue by eldritch-cookie** [NixOS/nixpkgs#300471]
### Describe the bug
i was unable to run the update.py script inside of pkgs/applications/editors/vim/plugins/nvim-treesitter

### Steps To Reproduce
1. ./pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py

### Expected behavior
the script should run without errors

### Additional context
i wanted to update the nvim-treesitter grammars as some grammars like for instance norg-meta are packaged but aren't included in nvim-treesitter.withAllGrammars

### Notify maintainers
@figsoda @jonringer @softinio @yu-re-ka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22, NixOS, 24.05 (Uakari), 24.05.20240327.2726f12`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/y45vqv6pa8bhgag1dw86rvi6rk55xhxn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
since you haven't shared your error, I'll assume you hit:
```
stripping (with command strip and flags -S -p) in  /nix/store/3c9zhxvgl3gfzjja7q5wq57y9c6pmj9r-neovim-0.9.5/lib /nix/store/3c9zhxvgl3gfzjja7q5wq57y9c6pmj9r-neovim-0.9.5/bin
Traceback (most recent call last):
  File "/home/teto/nixpkgs/./pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py", line 97, in <module>
    generated = update_grammars(sys.argv[1])
                                ~~~~~~~~^^^
IndexError: list index out of range
```

replace args with argv and maybe run `pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py $(nix-build -A vimPlugins.nvim-treesitter)` ? feel free to add a parser to make it more obvious how to use it. We import this script in the vim updater if you want to see how it's called.

**Comment by MangoIV** [comment]
the annoying things is that this still doesn't fix my issue - the update script just takes the jsons from the nvim-treesitter repo, but doesn't include the ones that are not mentioned there. :/ 

Is my only possibility of using that grammar to upstream it into nvim-treesitter or is there an easier way?
