### ISSUE TITLE
beam.packages.erlangR20.elixir warning: latin1 encoding vs. utf8

### ISSUE THREAD

**Issue by somlor** [NixOS/nixpkgs#30047]
## Issue description

When installing latest Elixir with Erlang 20 via `beam.packages.erlangR20.elixir`, several of these warnings are emitted through the build process:

> warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)

### Steps to reproduce

I'm installing through `environment.systemPackages` with [this `configuration.nix`](https://github.com/somlor/nixos-vultr-bootstrap/blob/ee219b114561d4a9d5efe6a2ecec291164db6fd5/configuration.nix) (on Vultr FWIW). Though I believe `nix-env -i beam.packages.erlangR20.elixir` on a new system may be enough to reproduce.

The only way I've gotten the warnings to subside if by specifying [this `pkgs.lib.overrideDerivation`](https://github.com/somlor/nixos-vultr-bootstrap/blob/eafa854a72ab13e2f0369f15448d8d0a3b156da1/configuration.nix#L23).

## Technical details

* System: `minimal-18.03pre116572.9824ca6975-x86_64-linux`
* Nix version: `1.11.15`
* Nixpkgs version: `18.03pre116572.9824ca6975`
* Sandboxing enabled: `false`

**Comment by somlor** [comment]
/cc: @gleber (by request from [/r/NixOS](https://www.reddit.com/r/NixOS/comments/73ceks/elixir_151_with_erlang_200_on_nixos_1803/dnsfhqu/?context=10000))

**Comment by ankhers** [comment]
I will look into this.

**Comment by gleber** [comment]
I see that you have dropped the override. Is this because of these are just harmless warnings?

I've switched to the same nixpkgs and could not reproduce the warnings on Ubuntu:
```
$ git checkout 9824ca6975
HEAD is now at 9824ca6... caffe: Make 'bin' the first output

$ nix-build -A beam.packages.erlangR20.elixir .
[snip]
/nix/store/05ncr9vibjin9kshwws52ysyyhhz5dgw-elixir-1.5.1
```
Output is here:
https://pastebin.com/nL7GdDLv

I'll try to reproduce this on NixOS machine now.

**Comment by gleber** [comment]
I was able to reproduce this on NixOS machine: http://ix.io/AHh

**Comment by somlor** [comment]
Thanks @gleber 🎉
