### ISSUE TITLE
Package request: split dbus into dbus-utils and dbus-daemon for dbus-broker

### ISSUE THREAD

**Issue by norpol** [NixOS/nixpkgs#300458]
**Project description**

Splitting `dbus` into `dbus-utils` and `dbus-daemon` was done when [Fedora introduced `dbus-broker` as a default](https://fedoraproject.org/wiki/Changes/DbusBrokerAsTheDefaultDbusImplementation).

Currently, when switching to `services.dbus.implementation = "broker"`, previously installed tools such as `dbus-monitor` or `dbus-update-activation-environment` are missing.

Discussed at Discourse for setting [dbus-broker the default](https://discourse.nixos.org/t/would-it-be-feasible-to-make-dbus-broker-the-default-dbus-implementation/41760/17).

---

Add a :+1: [reaction] to [issues you find important].

**Comment by norpol** [comment]
Related tickets and PRs:

* https://github.com/NixOS/nixpkgs/pull/299812
* https://github.com/NixOS/nixpkgs/issues/299476

**Comment by SuperSandro2000** [comment]
We don't really do split packages in nixpkgs and since the Daemon is likely neglige small we can just add the standard dbus package to systemPackages.

**Comment by SuperSandro2000** [comment]
I've just checked the package and the default plus the lib output is barely 1 MB big and the dbus-daemon executable alone is just 283KB. That really neglible size difference does not justify the added complexity of splitting the package into even more outputs.
