### ISSUE TITLE
Package request: Lilipod (a very simple container and image manager)

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#300498]
Package request: `Lilipod` (a very simple container and image manager)

https://github.com/89luca89/lilipod

Lilipod is also a nice fallback for [Distrobox](https://github.com/89luca89/distrobox) when no container-manager is found, or when it's not possible to install one. Being a fully self-contained binary that lives in one directory (LILIPOD_HOME) it makes it easy to install and remove without package managers.

Check:
https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#supported-container-managers

**Comment by nikp123** [comment]
In case anyone needs this shortcut, I already made a package in my NUR repo.
https://github.com/nikp123/nur-packages/blob/master/pkgs/lilipod/default.nix
