### ISSUE TITLE
Build failure: Gnome Warp v0.6.2 Darwin

### ISSUE THREAD

**Issue by WarpToTheMoon** [NixOS/nixpkgs#300505]
### Steps to reproduce the behavior:
On an apple silicon:
$ nix-env -iA nixpkgs.warp

I thought [this](https://github.com/NixOS/nixpkgs/commit/58eb45b0fe0ec308f7bdfaf5534ce1213ee22a82) was supposed to add support for macos.

### Build log
[warp.log](https://github.com/NixOS/nixpkgs/files/14816620/warp.log)

### Notify maintainers
@dotlambda 
@foo-dogsquared 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by dotlambda** [comment]
Why don't you ping @Atemu???

**Comment by Atemu** [comment]
I don't own a mac currently and I don't use the package, can't help you unfortunately.
