### ISSUE TITLE
trezor-suite's use of appimageTools makes it hard to use allowUnfreePredicate

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#300554]
### Describe the bug
I tried my hand at this, but I'm not sure what to do since I'm not familiar with appimageTools.

It seems that the `trezor-suite` derivation sets "name" for the `wrapType2` which produces the output.

The results in the version being part of the package name, which means I have this:

```
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  config = {
    nixpkgs.config.allowUnfreePredicate =
      pkg:
      builtins.elem (lib.getName pkg) [
        ### misc
        "google-chrome"
        "google-chrome-dev"

        # trezor-suite... is unfree?
        # "trezor-suite-23.12.3" # why's the version inside?
        # "trezor-suite-24.1.2" # why's the version inside?
        # "trezor-suite-24.2.2" # why's the version inside?
        "trezor-suite-24.3.2"
      ];
  };
}

```
Which is clearly not ideal.

How can we fix this? Or can we change the docs for allowUnfreePredicate so that it partially matches package name, etc?

Thanks for any tips.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by colemickens** [comment]
I just realized this was marked broken. I might actually have a fix other than it being broken for whatever reason.

**Comment by eclairevoyant** [comment]
#262350 essentially

**Comment by colemickens** [comment]
Thanks @eclairevoyant, maybe I'll go ahead and close this and subscribe to that issue. Thanks for the pointer.
