### ISSUE TITLE
Build failure: diffutils-3.10-riscv64-linux on qemu

### ISSUE THREAD

**Issue by theotheroracle** [NixOS/nixpkgs#300550]
### Steps To Reproduce

1. build diffutils-3.10-riscv64-linux

### Build log

[diffutils-log.txt](https://github.com/NixOS/nixpkgs/files/14817596/diffutils-log.txt)

### Additional context

i had suspended the system halfway through the build, and suspected that might have caused an issue, so i ran the build again and got the same result

### Notify maintainers

@dasJ 
@alyssais 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
hive@sol ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240226.13aff9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - nixpkgs: `/nix/store/1gpgihsi21bni03hy6i5ccw9lfrhnbqi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AlexandreTunstall** [comment]
I can't reproduce this failure on RISC-V hardware. With [this configuration](https://github.com/AlexandreTunstall/nixos-riscv/tree/724448dba476585b466052c2b909ca307a6cf017), the following command runs just fine:

```
nix build .#nixosConfigurations.nixos.pkgs.diffutils
```

Could this be an issue with the emulator you're using or a result of [my platform-specific customisations](https://github.com/AlexandreTunstall/nixos-riscv/blob/724448dba476585b466052c2b909ca307a6cf017/modules/arch/default.nix)?

**Comment by AlexandreTunstall** [comment]
The following command also builds for me.

```sh
nix build github:NixOS/nixpkgs/2726f127c15a4cc9810843b96cad73c7eb39e443#legacyPackages.riscv64-linux.diffutils
```

Relevant excerpt of the logs:

```
============================================================================
Testsuite summary for GNU diffutils 3.10
============================================================================
# TOTAL: 215
# PASS:  178
# SKIP:  37
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

Could you try running this in your build environment to see whether it's an issue with your emulator or build machine?

If the it builds, could you improve the "reproduce" instructions you've given?

**Comment by theotheroracle** [comment]
I ran that command on a seperate x86 machine and recieved the same build failure

**Comment by theotheroracle** [comment]
```
> ============================================================================
       > Testsuite summary for GNU diffutils 3.10
       > ============================================================================                                        > # TOTAL: 215
       > # PASS:  175                                                                                                        > # SKIP:  37                                                                                                         > # XFAIL: 0                                                                                                          > # FAIL:  3                                                                                                          > # XPASS: 0
       > # ERROR: 0                                                                                                          > ============================================================================                                        > See gnulib-tests/test-suite.log                                                                                     > Please report to bug-diffutils@gnu.org                                                                              > ============================================================================
```

**Comment by AlexandreTunstall** [comment]
I have successfully reproduced the issue by emulating RISC-V on an x86 machine.

So this could be caused by a QEMU bug.

I suggest you update the title to make it clear that it only happens with binfmt emulation.

**Comment by theotheroracle** [comment]
Ok i edited the title

**Comment by theotheroracle** [comment]
i'm curious why the gnugrep pr was merged, but not this one ? given that @AlexandreTunstall confirmed this build failure, but not the other one ?

**Comment by fgaz** [comment]
The other one just got the attention of a committer a bit earlier
