### ISSUE TITLE
Python "requests" package is not in scope for "influxdb" in NixOS 17.09

### ISSUE THREAD

**Issue by barrucadu** [NixOS/nixpkgs#30053]
## Issue description

The python `influxdb` package imports `requests`, but that's no longer available after upgrading to 17.09 without also explicitly pulling in `requests` to the closure.

### Steps to reproduce

1. Write a Python script which uses `influxdb` and run it in 17.03.  It works.
2. Now upgrade to 17.09 and try again.  It fails with an `ImportError` inside `influxdb` looking for `requests`:

```
ImportError: No module named 'requests'
    import requests
  File "/nix/store/dnl1743d50862rpszglwvzqsi99wjmlp-python3-3.5.4-env/lib/python3.5/site-packages/influxdb/client.py", line 12, in <module>
     from .client import InfluxDBClient
  File "/nix/store/dnl1743d50862rpszglwvzqsi99wjmlp-python3-3.5.4-env/lib/python3.5/site-packages/influxdb/__init__.py", line 8, in <module>
    from influxdb import InfluxDBClient
  File "/srv/radio/scripts/metrics.py", line 30, in <module>
```

## Technical details

* System: `17.09.1462.07ca7b64d2 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"17.09.1462.07ca7b64d2"`
* Sandboxing enabled: `build-use-sandbox = false`

The commit I made to my NixOS config to fix this: https://github.com/barrucadu/nixfiles/commit/8eb210b3cb8aba5bb999be004ef7077358d447f6
The affected script: https://github.com/barrucadu/lainonlife/blob/master/scripts/metrics.py (note that it doesn't import `requests` directly)

**Comment by FRidh** [comment]
1. I can't reproduce your issue
2. https://github.com/barrucadu/nixfiles/blob/8eb210b3cb8aba5bb999be004ef7077358d447f6/hosts/lainonlife.nix#L158 is bad. You are setting `python3` in your copy of Nixpkgs to a specific Python environment. You shouldn't do that in the package set but e.g. in `environment.packages`

**Comment by barrucadu** [comment]
Ok, if I'm doing the wrong thing and it's not broken for others, then it's quite possible I have just messed up somewhere and this is a non-issue.
