### ISSUE TITLE
Update request: invidious 0.20.1-unstable-2024-03-08 → 0.20.1-unstable-2024-03-31

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#300537]
- Package name: invidious
- Latest released version:  0.20.1-unstable-2024-03-31
- Current version on the unstable channel: 0.20.1-unstable-2024-03-08
- Current version on the stable/release channel: 0.20.1-unstable-2024-03-08

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@GaetanLepage
@infinisil 
@sbruder

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by d4g** [comment]
As invidious in the old version is broken as it cannot fetch videos anymore, please update to latest version and latest commit:
https://github.com/iv-org/invidious/pull/4552

**Comment by siph** [comment]
Here's an overlay with the fix until then:
```nix
(final: prev: {
    invidious = prev.invidious.overrideAttrs (_oldAttrs: {
      src = prev.fetchFromGitHub {
        owner = "iv-org";
        repo = "invidious";
        fetchSubmodules = true;
        rev = "08390acd0c17875fddb84cabba54197a5b5740e4";
        sha256 = "sha256-75C/ImX/PYikVdSO4rZM/aYyEgx6pU90BHNeRFfcsDM=";
      };
    });
})

```
