### ISSUE TITLE
system.stateVersion behavior undocumented when containers are used

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#30056]
## Issue description
I updated my nixos-17.03 to nixos-17.09 today. My postgresql server located in a declarative container didn't start.
My host system had ```system.stateVersion = "17.03";``` and I implicitly assumed it would get propagated to the containers but it doesn't, so ```services.postgresql.dataDir``` changed 
I'm not really sure how to approach this issue, because every behavior I can think of has downsides but at least there should be a warning in the release notes and the nixos documentation for declarative containers.

**Comment by edolstra** [comment]
Well, why should the configuration of the host system have any effect on containers? That's not the case for any other options either.

**Comment by danbst** [comment]
Oh crap, looks like I did same mistake! Probably using postgresql service without `system.stateVersion` should generate a warning or evaluation exception.

**Comment by pstn** [comment]
```system.StateVersion``` is different from other variables because it gets set by default during installation because it always should be set on a system. Since I'm not the only one who got this problem, I think it would be nice if there was a warning in the documentation to set it yourself when setting up containers.
