### ISSUE TITLE
replaceStdenv ignores all stdenvAdapters and stdenv overrides

### ISSUE THREAD

**Issue by silvanshade** [NixOS/nixpkgs#300579]
### Describe the bug

Setting `config.replaceStdenv` causes all subsequent uses of `stdenvAdapters` and all subsequent overrides of `stdenv` local to specific derivations to be ignored.

This makes using NixOS difficult on embedded or niche architectures where a custom toolchain configuration is often required (e.g., needing to use `ccache`, `distcc`, architecture-specific features, change the linker, etc).

In most cases, a custom `stdenv` will not work for building the entire package set so it's necessary to still be able to override changes again locally for specific instances even after `replaceStdenv` has been set.

### Steps To Reproduce

Below is an example which demonstrates this behavior.

In this example, `config.replaceStdenv` is set and then several subsequent derivations are defined with various `stdenv` customizations. The environment for each derivation is dumped to a file, and these are collected in the `result` folder of the final derivation when built with `nix build -f test.nix`.

```test.nix
{ pkgs ? import <nixpkgs> {
    config.replaceStdenv = { pkgs }: (pkgs.ccacheStdenv.override {
      extraConfig = ''
        export CCACHE_MAXSIZE=0
        export CCACHE_COMPILERCHECK=content
        export CCACHE_NOHASHDIR=1
        export CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime,locale,modules,pch_defines,random_seed,system_headers,time_macros
        export CCACHE_DIR="''${XDG_CACHE_DIR:-$HOME/.cache}/ccache"
      '';
    });
  }
}:

let
  stdenv-default-test = pkgs.stdenv.mkDerivation (self: {
    pname = "stdenv-default-test";
    version = "0";
    phases = [ "installPhase" ];
    installPhase = ''
      env >> $out
    '';
  });

  stdenv-llvm-test = pkgs.llvmPackages.stdenv.mkDerivation (self: {
    pname = "stdenv-llvm-test";
    version = "0";
    phases = [ "installPhase" ];
    installPhase = ''
      env >> $out
    '';
  });

  stdenv-overrideCC-test = (pkgs.stdenvAdapters.overrideCC pkgs.stdenv pkgs.clang).mkDerivation (self: {
    pname = "stdenv-overrideCC-test";
    version = "0";
    phases = [ "installPhase" ];
    installPhase = ''
      env >> $out
    '';
  });

  stdenv-noCC-test = pkgs.stdenvNoCC.mkDerivation (self: {
    pname = "stdenv-noCC-test";
    version = "0";
    phases = [ "installPhase" ];
    installPhase = ''
      env >> $out
    '';
  });

  stdenv-static-test = (pkgs.stdenvAdapters.makeStaticBinaries pkgs.stdenv).mkDerivation (self: {
    pname = "stdenv-static-test";
    version = "0";
    phases = [ "installPhase" ];
    installPhase = ''
      env >> $out
    '';
  });
in

pkgs.stdenv.mkDerivation {
  pname = "tests";
  version = "0";
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out
    cp -a ${stdenv-default-test} $out/stdenv-default-test
    cp -a ${stdenv-llvm-test} $out/stdenv-llvm-test
    cp -a ${stdenv-overrideCC-test} $out/stdenv-overrideCC-test
    cp -a ${stdenv-noCC-test} $out/stdenv-noCC-test
    cp -a ${stdenv-static-test} $out/stdenv-static-test
  '';
}
``` 

### Expected behavior

Although each result file should show different output, depending on the configuration, they are all essentially the same (modulo hashing and random seeds).

Attempting to override the compiler or the linking behavior or even removing the CC from the environment have no effect.

### Additional context
Related: https://github.com/NixOS/nixpkgs/issues/62121 https://github.com/NixOS/nixpkgs/issues/243397 https://github.com/NixOS/nixpkgs/issues/256433 

There are various other issues that seem to be special cases of this but the fundamental problem appears to be that `replaceStdenv` ignores all other local modifications to `stdenv` once set.

@Artturin commented [here](https://github.com/NixOS/nixpkgs/issues/256433#issuecomment-1728988952) and [here](https://github.com/NixOS/nixpkgs/issues/243397#issuecomment-1704381878) that this seemingly has something to do with order of the stages in https://github.com/NixOS/nixpkgs/blob/974165196f0d256f24fe93c55decdd951147e7f6/pkgs/stdenv/custom/default.nix#L16-L23.

Indeed, this seems to be the case. If that block is removed, the issue resolves (but of course, the `replaceStdenv` has no effect anymore).

I tried to figure out why overrides don't work after this but I'm new to Nix and don't fully understand how the stdenv bootstrapping works, let alone all the related subtle issues.

I tried changing:

```nix
stdenv = config.replaceStdenv { pkgs = vanillaPackages; };
```

to

```nix
stdenv = makeOverridable config.replaceStdenv { pkgs = vanillaPackages; };
```

and although that seems to pass through some extra parameters (like `cc`) in some cases, i.e.,

```nix
config.replaceStdenv = { pkgs, cc, ... } @ args: pkgs.stdenv.override { inherit cc };
```

that still doesn't seem to have any effect.

In any case, I would be willing to help fix this if someone can give me a better idea of what the problem is and what needs to be changed.

### Notify maintainers

@Ericson2314

**Comment by silvanshade** [comment]
I actually just realized that `ccacheStdenv` seems to ignore `stdenvAdapters` already, even without using it in `replaceStdenv`.

For example, if you try to do this, it doesn't change the linker to `mold` as expected:

```nix
stdenv = stdenvAdapters.useMoldLinker ccacheStdenv;
```

However, if you write it this way, it does work as expected:

```nix
stdenv = ccacheStdenv.override {
  stdenv = stdenvAdapters.useMoldLinker stdenv;
};
````

I think the original issue still stands however, and perhaps a fix for the `ccacheStdenv` would need to be addressed separately. Or maybe there is a common underlying cause.

Anyway, I hope someone with more understanding of the stdenv override machinery has some ideas about this.

**Comment by siraben** [comment]
Ran into this too when trying to use mold to link everything including dependencies.

**Comment by eclairevoyant** [comment]
Was this somehow solved?

**Comment by silvanshade** [comment]
@eclairevoyant Not exactly. Due to other related issues I'd been working on, I wasn't sure the way I originally described the problem was the best way to characterize it.

I can re-open it if other people are having the same issue and think it needs to be resolved still.

**Comment by biodranik** [comment]
@siraben did you find a way to use mold or gold linkers globally for all dependencies?

@silvanshade The issue looks important, keeping it open would be more beneficial.

**Comment by siraben** [comment]
Did anyone ever find a way to make mold linker permeate all the deps?
