### ISSUE TITLE
Build failure: postman fails to install

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#300587]
Build failure: `postman` fails to install on `NixOS 23.11`:
https://github.com/NixOS/nixpkgs/tree/nixos-23.11/pkgs/development/web/postman

```
building '/nix/store/wivdcvbharqx3nmiwwh9g0jml2fjvqrm-postman-10.18.6.tar.gz.drv'...

trying https://dl.pstmn.io/download/version/10.18.6/linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download postman-10.18.6.tar.gz from any mirror
error: builder for '/nix/store/wivdcvbharqx3nmiwwh9g0jml2fjvqrm-postman-10.18.6.tar.gz.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/wvp9frkdx9bi8qp2m8dv0vz2wqsmd55p-postman-10.18.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h4siymiwyyspi3fkfd78mnqavlhfllpc-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/28sjj8g1m7x0amv6m5apmyphsfiffivz-nixos-system-nixbox-23.11.5742.219951b495fc.drv' failed to build
```

![Bildschirmfoto vom 2024-04-01 01-56-04](https://github.com/NixOS/nixpkgs/assets/4227548/8f68d1a7-6d95-42d8-a0bb-dcec64a2772a)

**Comment by DrakaSAN** [comment]
@boustanihani  I am currently having the exact same error, what did you do to fix it before marking it as complete ?

**Comment by DrakaSAN** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/259147#issuecomment-2021747146

**Comment by boustanihani** [comment]
> @boustanihani I am currently having the exact same error, what did you do to fix it before marking it as complete ?

I only closed because its a duplicate, I'm using the Flatpak version now, until the bug gets fixed.
