### ISSUE TITLE
bluetooth.nix: "attribute 'formats' missing"

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#300647]
https://github.com/NixOS/nixpkgs/blob/50b366d82b163af0eaf4c8968fea329e90633b6a/nixos/modules/services/hardware/bluetooth.nix#L12

This line fails for me with "error: attribute 'formats' missing" when rebuilding my system.

---

I am in the process of transforming my system config to flakes and right now my rebuild fails because of the above line with above error.
I don't know how to investigate this, can someone have a look?

---

Pinging committers of the "formats" stuff as well as the bluetooth stuff:

@benaryorg @peterhoeg @h7x4

**Comment by matthiasbeyer** [comment]
Okay it seems that I messed up on my side. Sorry for the noise.

**Comment by matto-mercury** [comment]
I'm running into the same error; do you happen to remember what fixed it?

**Comment by matthiasbeyer** [comment]
Unfortunately no. :cry:
