### ISSUE TITLE
railway-travel,diebahn: double package.

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#300651]
### Describe the bug
how

https://github.com/NixOS/nixpkgs/blob/af105fd3758230351db538ade56e862ac947f849/pkgs/applications/misc/diebahn/default.nix
https://github.com/NixOS/nixpkgs/blob/af105fd3758230351db538ade56e862ac947f849/pkgs/by-name/ra/railway-travel/package.nix

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior

alias diebahn to railway-travel or vice versa

### Notify maintainers

you two fight @dotlambda @lilacious

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
any way for ci to detect double packages perhaps through source? are there more duplicates in nixpkgs?

**Comment by Lilacious** [comment]
MB, I did not realize that it was packaged already , it didn't occurred to me to search for the name of the binary instead of the project name.
If @dotlambda is fine with it, we could put an alias in place and treat it like a refactoring to pkgs/by-name. Otherwise I will remove my package.

**Comment by Lilacious** [comment]
Alright, will do. Should I add an alias for railway-travel that points to diebahn?

**Comment by dotlambda** [comment]
You can if you think it helps people find the package in the future.
