### ISSUE TITLE
lib: support alternative type names

### ISSUE THREAD

**Issue by deemp** [NixOS/nixpkgs#300664]
### Describe the bug

I can't set descriptive names for `submodule`-s and see these names in docs.

### Steps To Reproduce

- Build docs

  ```
  nix build github:deemp/nix2workflows/f9294924c7a0d071579bee5af881059aa2208932#example.x86_64-linux.internal.config.modules-docs.markdown -o result.md
  ```

- Open `result.md`

- See there `null or (submodule)`

- See there `workflows.<name>`

### Expected behavior

I can set a descriptive type name and path segment name in the code and get that name in the docs.

### Additional context

Currently, in `submoduleWith`,  a `name` isn't a parameter ([link](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L770)) and it's used in a couple of places ([1](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L774), [2](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L777), [3](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L799)).

The `submoduleWith` is used inside the definition of `submoduleWith` ([1](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L793), [2](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L800)). Hence, it's hard to correctly override `name` in all places.

The `"submoduleWith"` string occurs in erros inside `submoduleWith` ([link](https://github.com/NixOS/nixpkgs/blob/f6957593d4ca06677afb3cd0ddd6866b574a7431/lib/types.nix#L817)).

Additionally, I see the "submodule" string is used:

- in `modules.nix`

  https://github.com/NixOS/nixpkgs/blob/af105fd3758230351db538ade56e862ac947f849/lib/modules.nix#L650

- in a `nixos-option.cc`

  https://github.com/NixOS/nixpkgs/blob/af105fd3758230351db538ade56e862ac947f849/pkgs/tools/nix/nixos-option/nixos-option.cc#L274

### Possible solution

- Add a `stableName` attribute to option types.
  - The `stableName` is a stable type name.
  - The `name` is a pretty type name.
  - The `name` should default to `stableName`.

### Notify maintainers

@infinisil 
@roberth 

### Metadata

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0-39-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.4`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
I believe `submoduleWith`'s `description` should do what you want: 

```diff
diff --git a/nix/common.nix b/nix/common.nix
index 39b27d4..f7cbe83 100644
--- a/nix/common.nix
+++ b/nix/common.nix
@@ -75,7 +75,10 @@ rec {
             mkSubmoduleOption =
               options:
               lib.mkOption {
-                type = lib.types.nullOr (lib.types.submodule { inherit options; });
+                type = lib.types.nullOr (lib.types.submoduleWith {
+                  description = "My type";
+                  modules = [ { inherit options; } ];
+                });
                 default = null;
               };

```

=>

~~~md
#### `workflows.<name>.on.branch_protection_rule`

**Type**:

```text
null or (My type)
```
~~~

**Comment by deemp** [comment]
@infinisil, indeed, thank you!

For some reason, in the original issue, I provided the context for another question.

How do I override the `name` in `workflows.<name>`?

**Comment by infinisil** [comment]
Ah looks like https://github.com/NixOS/nixpkgs/issues/295872 then, to which I just replied with a suggestion :)

**Comment by roberth** [comment]
Would `class` be a suitable name to use in the type description?
We'd automatically have descriptions like:
- `nixos module`
- `nixosTest module`
- `nixpkgsConfig module`

and whichever classes may exist in the wild.

**Comment by deemp** [comment]
@roberth, I think my issue is resolved for now. Please reopen if you think it can be worked on.
