### ISSUE TITLE
Logseq: Node.js version mismatch

### ISSUE THREAD

**Issue by bleetube** [NixOS/nixpkgs#300762]
### Describe the bug
Logseq (version 0.9.6) fails to start correctly on NixOS with a newer channel update, freezing and displaying a white window approximately 4 seconds after launch. The console logs indicate a version mismatch error for the `better-sqlite3` module, suggesting it was compiled against a different Node.js version than the one required by the system (NODE_MODULE_VERSION 107 vs. 116 required).

### Steps To Reproduce
1. Update NixOS to the latest channel update.
2. Install Logseq version 0.9.6 using the `environment.systemPackages` with `pkgs.logseq`.
3. Run Logseq from the terminal using `logseq`.
4. Observe the application starting, then freezing and turning white after the version mismatch errors appear in the terminal.

### Expected behavior
Logseq should start and run as expected without freezing or crashing, similar to its behavior on systems with older NixOS channel updates.

### Additional context
The issue seems related to a discrepancy between the Node.js version used at build time for the `better-sqlite3` module and the Node.js version required at runtime by Logseq on the newer NixOS update. This kind of problem suggests either a need to rebuild the native module against the correct Node.js version or an adjustment in the package dependencies to ensure compatibility.

### Notify maintainers
@kilianar 
@r-ryantm 

### Metadata
Please replace the command output with the output from your system.
```console
[blee@litten ~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.05 (Stoat), 23.05.5533.70bdadeb94ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
[blee@litten logseq]$ nix-env -qaP logseq
nixos.logseq  logseq-0.9.6
```

---

This issue impacts the usability of Logseq on NixOS following recent updates, and any insights or resolutions would be greatly appreciated.

**Comment by donovanglover** [comment]
`nix-shell -p nix-info --run "nix-info -m"` shows that your system is still on 23.05, which is unsupported.

Try upgrading to 23.11, which has Logseq 0.10.6
