### ISSUE TITLE
environment.plasma6.excludePackages does not work

### ISSUE THREAD

**Issue by Titaniumtown** [NixOS/nixpkgs#300788]
### Describe the bug
environment.plasma6.excludePackages doesn't work when trying to exclude konsole. On plasma6 and nixos unstable

### Steps To Reproduce
add the following to your configuration.nix:
```nix
  environment.plasma6.excludePackages = with pkgs; [
    libsForQt5.konsole
    kdePackages.konsole
  ];
```
konsole still is installed on rebuild and reboot.
(Yes I know I it should be `kdePackages.konsole`, but it seems the version konsole is on version `23.08.5` which matches up with `libsForQt5.konsole`, which is strange because it should be pulling the new plasma6 version)

### Expected behavior
Konsole shouldn't be included when explicitly excluded.

### Notify maintainers
(I think these are the right people :crossed_fingers: )
@ilya-fedin @1pakch @LunNova @mjm @NickCao @SuperSandro2000 @ttuegel 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2-cachyos, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos, nixos-hardware, plasma-manager"`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> (Yes I know I it should be `kdePackages.konsole`, but it seems the version konsole is on version `23.08.5` which matches up with `libsForQt5.konsole`, which is strange because it should be pulling the new plasma6 version)

Then that is being pulled on by some other setting in your config. Please check for any other plasma5/qt5 references.

**Comment by Titaniumtown** [comment]
Welp! You were right @SuperSandro2000. It was kate. I was doing `pkgs.kate` instead of `kdePackages.kate`. Thank you so much!
