### ISSUE TITLE
Bluetooth is broken after update

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#300737]
### Describe the bug

```
# dmesg | grep -i blue
[    5.618776] Bluetooth: Core ver 2.22
[    5.618794] NET: Registered PF_BLUETOOTH protocol family
[    5.618796] Bluetooth: HCI device and connection manager initialized
[    5.618802] Bluetooth: HCI socket layer initialized
[    5.618804] Bluetooth: L2CAP socket layer initialized
[    5.618808] Bluetooth: SCO socket layer initialized
[    7.619871] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    7.619878] Bluetooth: BNEP socket layer initialized
[    7.934245] Bluetooth: hci0: Reading Intel version command failed (-110)
[    7.934246] Bluetooth: hci0: command 0xfc05 tx timeout
# bluetoothctl show
No default controller available
# uname -a
Linux nixos 6.8.2 #1-NixOS SMP PREEMPT_DYNAMIC Tue Mar 26 22:23:34 UTC 2024 x86_64 GNU/Linux
```

### Steps To Reproduce
1. Update the system

### Expected behavior
Bluetooth should work.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/store/cb1gs888vfqxawvc65q1dk6jzbayh3wz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Cloudef** [comment]
Can confirm, seems to be that old bug has resurfaced?
https://bugzilla.kernel.org/show_bug.cgi?id=215167

**Comment by MordragT** [comment]
> Can confirm, seems to be that old bug has resurfaced? https://bugzilla.kernel.org/show_bug.cgi?id=215167 Might be a regression in linux-firmware
> 
> EDIT: to restore functionality of your bluetooth, you may have to powercycle your PSU, seems like in latest kernel/firmware there is some bug that completely bricks the bluetooth until you powercycle it

Can confirm that after powercycle it is working again. Thank you!

**Comment by t56k** [comment]
> ... to restore functionality of your bluetooth, you may have to powercycle your PSU, seems like in latest kernel/firmware there is some bug that completely bricks the bluetooth until you powercycle it

+1 on this (hopefully temporary) fix. Also, I'm writing this comment because I'm positive I'll forget when it next happens.

**Comment by Nanotwerp** [comment]
Note that, at least for me, the PSU power cycle fix only applies to the boot immediately after the power cycle.

**Comment by Cloudef** [comment]
6.8.4 might fix this, you still have to do full power cycle to get the bluetooth chip out from the bugged state if you have booted into a bugged kernel before

**Comment by suhr** [comment]
Bluetooth now works on linux 6.8.5.
