### ISSUE TITLE
Package request: localsend-rs

### ISSUE THREAD

**Issue by pagusupu** [NixOS/nixpkgs#300784]
**Project description**

CLI implementation of localsend.

**Metadata**

* homepage URL: https://github.com/zpp0196/localsend-rs
* source URL: https://github.com/zpp0196/localsend-rs
* license: MIT
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
here's a derivation that builds successfully, but i was unable to use the built command to actually send files.

```nix
{ lib
, rustPlatform
, fetchFromGitHub
, openssl
, pkg-config
}:
rustPlatform.buildRustPackage {
  pname = "localsend-rs";
  version = "0-unstable-2024-04-03";

  src = fetchFromGitHub {
    owner = "zpp0196";
    repo = "localsend-rs";
    rev = "358c70ed7c293baaef97e3c9e4dc7cd6f5bc52b4";
    hash = "sha256-OUZ1QKV2VqTpkaGqcQyjFAYpcYmMQLU0Wvln+XO5nx0=";
  };

  cargoHash = "sha256-iBTuF5IHBPKphkecfFR1Hs4qyAFW0QuKkJbt+g6hwjw=";

  nativeBuildInputs = [ pkg-config ];
  buildInputs = [ openssl ];

  meta = {
    description = "CLI implementation of localsend";
    homepage = "https://github.com/zpp0196/localsend-rs";
    maintainers = with lib.maintainers; [ binarycat ];
    platforms = lib.platforms.unix;
    license = lib.licenses.mit;
    mainProgram = "localsend";
  };
}
```

a few things i noticed:
1. the localsend-rs repo only has 10 commits
2. the "send" command does not seem to have a way to specify where to send the files to
3. the built command is named `localsend`, which is the same as the gui version, meaning the two could not coexist on the same system (generally you should only do this if two programs have identical CLI interfaces)

these factors make me believe this command is not actually finished or in a usable state.

**Comment by pagusupu** [comment]
After testing with that derivation i was able to send files to my phone using the android localsend app fine and could find another device using localsend-rs but couldn't actually receive files. this is likely why you couldnt send files unless you didnt have the correct udp and tcp ports open (53317 by default). 

the send command wont let you specify where to send files until it finds another device which can receive it, then it lets you choose.

as far as i can tell the localsend gui app doesnt use `localsend` as a command but only works when executing a binary in the package unless im missing something. 

the repo is very recent so there are likely fixes needed, potentially with not being able to receive files unless its a nix specific issue which im unsure of, i think its fair to not have it packaged if thats not fixable but ill leave that up to you.

**Comment by lolbinarycat** [comment]
> as far as i can tell the localsend gui app doesnt use localsend as a command but only works when executing a binary in the package unless im missing something.

the binary in the package is named localsend.  anyone who uses the terminal to start apps, or a dmenu_run based wm (dwm, i3, sway) will be unable to launch the gui if they have both packages installed to their profile.  the desktop entry does hardcode the store path, so users of DEs will be mostly unaffected.

**Comment by pagusupu** [comment]
it seems the command for me to run it is `localsend_app`, after looking at the gui app derivation it seems as if it might be `localsend` in darwin only?

**Comment by lolbinarycat** [comment]
i'm on x86_64-linux and `nix build nixpkgs#localsend` results in `./result/bin/localsend` being produced.

**Comment by pagusupu** [comment]
im also on x86_64 linux and the same command results in `./result/bin/localsend_app`

**Comment by lolbinarycat** [comment]
what revision of nixpkgs?

**Comment by pagusupu** [comment]
`24.05.20240403.08b9151`
`0e74ca98a74bc7270d28838369593635a5db3260`

**Comment by lolbinarycat** [comment]
hmm.. maybe they changed it in a recent localsend version, i'm on stable

**Comment by pagusupu** [comment]
looking at the derivations for both stable and unstable the stable version is using fetchurl to get the appimage while unstable is using fetchfromgithub. from what i can tell the binary is called `localsend_app` but was being changed to `localsend` on stable, which seems like it might still be the case with darwin unstable

**Comment by lolbinarycat** [comment]
after looking at kernel logs for unrelated reasons i realized nixos enables the kernel firewall by default, will test again.

**Comment by lolbinarycat** [comment]
even with the firewall configured appropriately, i am unable to send or receive files.
