### ISSUE TITLE
Package request: pyWhat

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#300743]
**Project description**

🐸 Identify anything. pyWhat easily lets you identify emails, IP addresses, and more. Feed it a .pcap file or some text and it'll tell you what it is! 🧙‍♀️ 

**Metadata**

* homepage URL: https://github.com/bee-san/pyWhat
* source URL: https://github.com/bee-san/pyWhat
* license: MIT
* platforms: Linux, Darwin, Unix, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I created a PR based on this package request: https://github.com/NixOS/nixpkgs/pull/300803
