### ISSUE TITLE
jq unable to load libonig.dylib

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#30070]
## Issue description

41b43b201e23f5f1f2ac943d04b896de7ab860a9 appears to have broken the dynamic linking for `jq` under darwin

```
clever@DU075 ~ $ /nix/store/sra05q5m0hkspyaxjj1qk9d4zyvngdln-jq-1.5/bin/jq 
dyld: Library not loaded: @executable_path/../lib/libonig.dylib
  Referenced from: /nix/store/sra05q5m0hkspyaxjj1qk9d4zyvngdln-jq-1.5/bin/jq
  Reason: image not found
Trace/BPT trap: 5
```

cc @fpletz

**Comment by copumpkin** [comment]
I think @LnL7 fixed this already: https://github.com/NixOS/nixpkgs/commit/6c189c9e284b2c66efbf24d2b1ecf35d95eb6974

**Comment by copumpkin** [comment]
Works for me on master!

**Comment by LnL7** [comment]
@copumpkin Don't we have a setup-hook in the stdenv that's supposed to fix the install_name of dynamic libraries like this?

**Comment by copumpkin** [comment]
I don't remember such a thing, but I haven't looked at that stuff in ages!
