### ISSUE TITLE
 virglrenderer with video hardware decoding

### ISSUE THREAD

**Issue by zeroware** [NixOS/nixpkgs#300897]
###  virglrenderer : add support for hardware video acceleration 

Hello,
virglrenderer supports hardware video decoding for H.264 and H.265 since 1.0.0.

You can find the relevant option to enable here : https://gitlab.freedesktop.org/virgl/virglrenderer/-/blob/virglrenderer-1.0.1/meson.build?ref_type=tags#L325

Would be cool to enable the option or maybe under a flag ?

I'd love to help but I don't know much about building with `meson`. If you have some guideline on how to do it I can do some testing.

### Expected behavior

Hardware video decoding in guest when using virgl graphics in qemu.

### Notify maintainers

@xeji and maybe @trofi ?

**Comment by trofi** [comment]
Sounds reasonable. How about something like this:
- https://github.com/NixOS/nixpkgs/pull/300899

**Comment by shodanx2** [comment]
Hi,
I'm trying to run nixos with a kde plasma desktop with 3d acceleration using virgl inside of proxmox.
This issue appears somewhat related and was the top google search for "nixos virgl"
Could you provide a link to the documentation regarding this issue and how to activate this feature ?
thanks !
