### ISSUE TITLE
Package request: openbao

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#300943]
**Project description**

> OpenBao exists to provide a software solution to manage, store, and distribute sensitive data including secrets, certificates, and keys.

(this is the open-source fork of HashiCorp's [`vault`](https://nixpkgs.dev/vault), which along with their other products relicensed to using a Business Source License.)

**Metadata**

* homepage URL: https://github.com/openbao/openbao
* source URL: https://github.com/openbao/openbao
* license: mpl2
* platforms: unix, linux, darwin, ...

**Comment by justinrubek** [comment]
This was done in #354366

**Comment by cipherboy** [comment]
Thank you all!
