### ISSUE TITLE
TeamViewer 15.49.2: Window for remote connection no longer appears

### ISSUE THREAD

**Issue by tobias-kuendig** [NixOS/nixpkgs#300937]
### Describe the bug

After installing the update for TeamViewer 15.49.2 (introduced in #276948) I can no longer connect to remote hosts.

The connection is established, but the window does not appear. If i try to connect to the same host again, I receive the message that I already have a connection open.

Looking at the logs, this might be the issue:

```shell
$ cat ~/.local/share/teamviewer15/logfiles/TeamViewer15_Logfile.log

2024/04/02 13:47:43.519 106422 106422 GW2!! QML load error: qrc:/ui/ClientWindow/RCClientRemoteScreenWindow.qml:176:2: Type RemoteControlToolbar unavailable, Errorcode=11
2024/04/02 13:47:43.519 106422 106422 GW2!! QML load error: qrc:/ui/ClientWindow/RemoteControlToolbar.qml:14:1: Type ToolbarContainer unavailable, Errorcode=11
2024/04/02 13:47:43.520 106422 106422 GW2!! QML load error: qrc:/ui/ClientWindow/RCClient/ToolbarContainer.qml:51:2: Type PerryRoundangle unavailable, Errorcode=11
2024/04/02 13:47:43.520 106422 106422 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryRoundangle.qml:7:1: Type PerryDropShadowItem unavailable, Errorcode=11
2024/04/02 13:47:43.520 106422 106422 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryDropShadowItem.qml:26:16: Type PerryDropShadow unavailable, Errorcode=11
2024/04/02 13:47:43.520 106422 106422 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryDropShadow.qml:1:1: module "QtGraphicalEffects" is not installed, Errorcode=11
```

TeamViewer was working as expected on another system that was running version 15.38. After the update of that system, the same problem appears.

### Steps To Reproduce

1. Open TeamViewer
2. Connect to any host
3. No new window appears
4. Connect to the same host again
5. Message "you are already connected" appears

### Notify maintainers

@ifurther @jagajaga @jraygauthier @gador

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.1, NixOS, 23.11 (Tapir), 23.11.20240328.219951b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/path/nixpkgs`

```

**Comment by leon-erd** [comment]
I'm still facing the same issue 🤔 using `services.teamviewer.enable = true;`

**Comment by gador** [comment]
Please add more information and reopen a new issue. Thanks
