### ISSUE TITLE
Package request: koji (conventional git commits)

### ISSUE THREAD

**Issue by norpol** [NixOS/nixpkgs#301069]
**Project description**

koji is a cli tool that helps you write "conventional" commits by asking a set of questions to commit

**Metadata**

* homepage URL: https://crates.io/crates/koji
* source URL: https://github.com/its-danny/koji
* license: mit
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I created a PR based on this package request: https://github.com/NixOS/nixpkgs/pull/301090
