### ISSUE TITLE
Documentation: MediaWiki Explicit Admin username

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#301000]
## Problem
Thank you greatly @Mic92 @eclairevoyant 
For fixing the recent "spaces" bug in MediaWiki #298902 . I would like to note that the default MediaWiki administrator username is *implied*, but has yet to be made explicit.

## Proposal
Since there is no option to set the default administrator username, I propose to edit the documentation to make it *Explicit* that the default administrator username is "admin".

https://github.com/NixOS/nixpkgs/blob/526d051b128b82ae045a70e5ff1adf8e6dafa560/nixos/modules/services/web-apps/mediawiki.nix#L251

Changing from (ambiguous)
"for the admin user."

 Changing to (unambiguous)
"for the initial user \\"admin\\"."

**Comment by mrgiles** [comment]
@Sepero, thanks for the suggestion. 

How about: `A file containing the initial password for the administrator account "admin".`?

This matches more closely the [NixOS Wiki](https://nixos.wiki/wiki/MediaWiki) article on the subject. Plus, it avoids using the _initial_ word twice in the same sentence.

PS: I have a PR ready to submit if you agree with the suggestion.

**Comment by Sepero** [comment]
Yes, that's fine. I'm actually the author of that wording on the NixOS Wiki. Anything to clear up the ambiguity is good.
