### ISSUE TITLE
Build failure: ocamlPackages.eio_posix

### ISSUE THREAD

**Issue by chewblacka** [NixOS/nixpkgs#301174]
### Steps To Reproduce

1. build `ocamlPackages.eio_posix` on x86_64-darwin

### Build log

```
error: builder for '/nix/store/pw9wpp7v2mkp9ijnqwpn12hv6b2n2y6k-ocaml5.1.1-eio_posix-1.0.drv' failed with exit code 1;
       > eio_posix_stubs.c:133:7: error: call to undeclared function 'preadv'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       >   r = preadv(Int_val(v_fd), iov, n_bufs, offset);
       >       ^
       > eio_posix_stubs.c:150:7: error: call to undeclared function 'pwritev'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       >   r = pwritev(Int_val(v_fd), iov, n_bufs, offset);
       >       ^
       > 2 errors generated.
       >
       For full logs, run 'nix log /nix/store/pw9wpp7v2mkp9ijnqwpn12hv6b2n2y6k-ocaml5.1.1-eio_posix-1.0.drv'.
error: 1 dependencies of derivation '/nix/store/1b9x6a5fj12cmp1prwkyk803g467wknz-ocaml5.1.1-eio_main-1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gly8zm9w97ffh35xv2dhzy73d0b3gcxz-ocaml5.1.1-docfd-3.0.0.drv' failed to build
```

### Additional context

Package is a dependency of `docfd`. Builds fine on linux and aarch64-darwin, just fails on x86_64-darwin.

### Notify maintainers

@toastal 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by n8henrie** [comment]
Can test later, but it looks like there is a workaround for this exact error at https://github.com/NixOS/nixpkgs/blob/15f378d47eed487f2ab11b03814ab7beecaee844/pkgs/tools/networking/nbd/default.nix#L51

**Comment by chewblacka** [comment]
Thanks. I tried that flag earlier, which turns the error into a warning and allows `ocamlPackages.eio_posix` to build (with warnings). But then when I try and build `docfd` which depends on this I get linker errors, 

```
Undefined symbols for architecture x86_64:
  "_preadv", referenced from:
      _caml_eio_posix_preadv in libeio_posix_stubs.a(eio_posix_stubs.o)
     (maybe you meant: _caml_eio_posix_preadv)
  "_pwritev", referenced from:
      _caml_eio_posix_pwritev in libeio_posix_stubs.a(eio_posix_stubs.o)
     (maybe you meant: _caml_eio_posix_pwritev)
ld: symbol(s) not found for architecture x86_64
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by reckenrode** [comment]
`preadv` and `pwritev` were added in 11.0. It should use `overrideSDK stdenv { darwinMinVersion = "11.0"; darwinSdkVersion = "11.0"; }` to override the stdenv to use the 11.0 SDK with an 11.0 deployment target.

**Comment by chewblacka** [comment]
Many thanks, that worked! Much appreciated.
