### ISSUE TITLE
firefoxpwa : Failed to create icon directory

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#301194]
### Describe the bug
When I try to install a webapp I get the following error : Failed to install system integration: Failed to store web app icons: Failed to create icon directory: Not a directory (os error 20)

### Steps To Reproduce
1. Install firefoxpwa this way in /etc/nixos/configuration.nix : 
```
{ config, pkgs, lib, ... }:
let
  unstable = import <nixos-unstable> {};
in
{
  environment.systemPackages = with pkgs; [
    unstable.firefoxpwa
  ];
  programs.firefox = {
    enable = true;
    package = pkgs.firefox;
    nativeMessagingHosts.packages = with pkgs; [
      browserpass
      unstable.firefoxpwa
    ];
  };
```

3. Install firefox extension https://addons.mozilla.org/fr/firefox/addon/pwas-for-firefox/
4. Try to install any website as a PWA
5. Get the following error : Failed to install system integration: Failed to store web app icons: Failed to create icon directory: Not a directory (os error 20)
6. PWA not installed.

### Expected behavior
Have the PWA installed.

### Notify maintainers
@camillemndn 
@pasqui23 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5742.219951b495fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Thatoo** [comment]
To solve this issue, I needed to be sure this folder exists : `~/.local/share/icons/hicolor/`

**Comment by Thatoo** [comment]
However, when I launch it, I face a new issue : `No such file or directory (os error 2)`

![image](https://github.com/NixOS/nixpkgs/assets/464782/b5f29a22-71ba-4f53-b9e2-8d6108b10b3a)

**Comment by filips123** [comment]
I'll fix the PWA installation so that it creates required directories if they don't already exists in the next release.

**Comment by filips123** [comment]
Actually, I'm not sure how this error happens. The code already tries to create the icons directory and its parent directories (with `create_dir_all`) [here](https://github.com/search?q=repo%3Afilips123%2FPWAsForFirefox+path%3Anative%2Fsrc%2Fintegrations%2Fimplementation%2Flinux.rs+%22create_dir_all%28directory%29.context%28CREATE_ICON_DIRECTORY_ERROR%29%3F%3B%22&type=code). Maybe the problem is the lack of permissions to create a directory?
