### ISSUE TITLE
Installing NixOS to replace Ubuntu

### ISSUE THREAD

**Issue by mkocha2** [NixOS/nixpkgs#30119]
## Issue description
The installer doesn't have a separate section for what happens when installing NixOS 17.03 on media already containing another operating system installation. 

It so happens that I have a partially broken Ubuntu 16.04 installation and I determined that it will take more effort to keep it alive than to install NixOS, but only if I know the installer won't touch data on /home and just to be sure I would like to know exactly what direct directories below the root directory / it touches. All filesystems on all partitions are ext4. 

I also am aware of nixpart, nix-infect and other incomplete solutions.

**Comment by 7c6f434c** [comment]
If you think in terms of installing from a separate boot media, I guess the answer is «installer doesn't mount unmounted stuff, and it expects the user to prepare and mount all the needed partitions before installation» (so, just don't mount `/home/` if you want to be sure)

**Comment by mkocha2** [comment]
/home is on the same partition as /.

**Comment by 7c6f434c** [comment]
It doesn't delete anything in `/home/` (you can ask it to create a user together with a home directory, though), and it doesn't touch directories it doesn't understand (like `/do-not-touch/`), but I guess it touches a lot of top-level directories — at the very least `/nix/`, `/etc/`, `/bin/` (to create a symlink `/bin/sh`), `/usr/` (to create a symlink `/usr/bin/env`), `/var/` (maybe only after boot, but I guess this distinction doesn't matter), `/boot/`, `/dev/` and `/run/` (but these two are supposed to be on tmpfs anyway). And `/home/` if you describe any users in configuration (which is optional).

**Comment by bjornfor** [comment]
I did a reinstall of NixOS on top of existing rootfs populated from a backup that included /home/bfo. Worked like charm.

**Comment by FRidh** [comment]
> I would like to know exactly what direct directories below the root directory / it touches

Seems useful to add to the NixOS manual. I suggest you do a new installation in say a VirtualBox and check what folders are created.

**Comment by volth** [comment]
There is also nix-lustrate https://github.com/NixOS/nixpkgs/pull/36272
It has been in nixos ~2 years but undocumented until just now.

**Comment by obadz** [comment]
@mkocha2: does #36272 suffice to close this issue or are you looking for more?

**Comment by pasqui23** [comment]
To add: I usually install nixos while I restore my `~` from backup,and it all goes smoothly except for p the permissions.

**Comment by FRidh** [comment]
Given we have #36272 in and no more feedback from the issue author I am closing this.
