### ISSUE TITLE
pelican: pelican-quickstart created sites depend on installed bash version

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#30116]
## Issue description

The develop-server.sh script created by pelican-quickstart has the full path to bash in the shebang line, e.g.

```
#!/nix/store/flb9ar1xdd13c606aa4my9miy3iv4vyk-bash-4.4-p12/bin/bash
```

This is in my opinion undesirable as it binds the project to that installed bash version, and injects 'nixism' into a user project by default.

### Steps to reproduce

- Install pelican
- Create a new site with pelican-quickstart
- Look at the created develop-server.sh

## Technical details

* System: 17.09.git.c64074f (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09beta1452.c3176eed6f
* Sandboxing enabled: yes

**Comment by Moredread** [comment]
cc @prikhi @garbas

**Comment by garbas** [comment]
there are also some "/nix/store" references in ``./publishconf.py``. While we can easily change first line of ``develop-server.sh`` to ``#!/usr/bin/env bsh``. I have no idea how to fix ``publishconf.py`` yet

**Comment by FRidh** [comment]
How about passing `dontPatchShebangs` to `buildPythonPackage` and then in the `postFixup` use `patchShebangs` on the individual items that do need to be patched.

**Comment by Moredread** [comment]
Is there a way to see what would have been autopatched? One problem is that if upstream adds new scripts they might be overlooked.

**Comment by FRidh** [comment]
Fixed with https://github.com/NixOS/nixpkgs/commit/9304ae04d7d6e24630943ee5312099c6568e1d32.
