### ISSUE TITLE
livebook fails to start

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#301187]
### Describe the bug
The `livebook` executable provided by the `livebook` package fails to start, with the error `port already in use`.

### Steps To Reproduce
1. `$ nix-shell -p livebook`
2. `$ livebook start`

```console
/nix/store/jcjkw8y92fsf1hnwqa0kfq9nx15kvc7v-livebook-0.12.1/releases/0.12.1/env.sh: line 14: /nix/store/jcjkw8y92fsf1hnwqa0kfq9nx15kvc7v-livebook-0.12.1/releases/COOKIE: Read-only file system
22:08:26.509 [error] Running LivebookWeb.IframeEndpoint with Bandit 1.1.0 at http failed, port already in use

ERROR!!! [Livebook] shutdown: failed to start child: {Bandit, #Reference<0.3282344449.1045692431.115395>}
    ** (EXIT) shutdown: failed to start child: :listener
        ** (EXIT) :eaddrinuse
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

### Expected behavior
The livebook server to run as the current user.

### Additional context
I have verified that nothing is listening on port 8080 (the default liveview port) by checking the output of `sudo ss -tulpn | grep -F LISTEN`.

Setting the environment variable `LIVEBOOK_PORT` to a different port number does not resolve the error.

### Notify maintainers
@Munksgaard

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.23, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Munksgaard** [comment]
Thank you for your bug report! It seems like the problem happened when starting the IframeEndpoint, the port of which is configured using [`LIVEBOOK_IFRAME_PORT`](https://github.com/livebook-dev/livebook?tab=readme-ov-file#environment-variables)  (and defaults to port 8081). Do you perhaps have something running on port 8081?

**Comment by aidalgol** [comment]
Ah, yes, I do have something running on that port.  I can successfully start Livebook after setting `LIVEBOOK_IFRAME_PORT` to an unused port.  Thanks!
