### ISSUE TITLE
Update request: uv 0.1.24 → 0.1.28

### ISSUE THREAD

**Issue by computerscience-person** [NixOS/nixpkgs#301179]
- Package name: uv
- Latest released version: 0.1.28

- Current version on the unstable channel: 0.1.24
- Current version on the stable/release channel: None

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@marsam 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marsam** [comment]
I think it requires rustc 1.77 https://github.com/NixOS/nixpkgs/pull/298340
