### ISSUE TITLE
Update request: tutanota-desktop 3.118.27 → 220.240321.0

### ISSUE THREAD

**Issue by pseudointellectualy** [NixOS/nixpkgs#301291]
- Package name:     tutanota-desktop
- Latest released version: 220.240321.0

- Current version on the unstable channel: 220.240319.1
- Current version on the stable/release channel: 3.118.27

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Pull request:  
tutanota-desktop: 220.240319.1 -> 220.240321.0 #301190 
https://github.com/NixOS/nixpkgs/pull/301190

**Notify maintainers** @WolfangAukang 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by WolfangAukang** [comment]
https://github.com/NixOS/nixpkgs/pull/301190

**Comment by WolfangAukang** [comment]
Merged
