### ISSUE TITLE
Build failure: linuxPackages.nvidia_x11

### ISSUE THREAD

**Issue by jankrejci** [NixOS/nixpkgs#301221]
Installation of the NVIDIA-Linux-x86_64-470.239.06 driver through the nixGL is broken.

` nix-env -iA nixgl.auto.nixGLNvidia`

### Build log

```console
error: builder for '/nix/store/skwg6inwprh9wmkvx5vi2rb9y014p8y3-nvidia-x11-470.239.06-nixGL.drv' failed with exit code 127;
       last 11 log lines:
       > Running phase: unpackPhase
       > tail: error writing 'standard output': Broken pipe
       > Creating directory NVIDIA-Linux-x86_64-470.239.06
       > Verifying archive integrity... OK
       > Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 470.239.06/nix/store/vmm1c1bwzn9s5m8dgcwlviym7n1lkhwm-NVIDIA-Linux-x86_64-470.239.06.run: line 728: /build/makeself.XjK0VJG0/xz: cannot execute: required file not found
       > tail: error writing 'standard output': Broken pipe
       > /nix/store/vmm1c1bwzn9s5m8dgcwlviym7n1lkhwm-NVIDIA-Linux-x86_64-470.239.06.run: line 719: /dev/tty: No such device or address
       >
       > Terminated
       > /nix/store/pxvl01q3az1543jx1vzzj3ap2jkpkhx5-builder.sh: line 6: bsdtar: command not found
       > tail: error writing 'standard output': Broken pipe
       For full logs, run 'nix log /nix/store/skwg6inwprh9wmkvx5vi2rb9y014p8y3-nvidia-x11-470.239.06-nixGL.drv'.
error: 1 dependencies of derivation '/nix/store/rhwjvy67xap07260yh5p0p6qrwbpa3yg-nixGLNvidia-470.239.06.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vgg6m9py1ydn8ddypxbjjbd95ac6fp9p-nixGL.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0ngc4rbxsdkm7r9mkm8sdqz18xvi3qs6-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pyc8vmfvdrjhrvjs07sbwd42sly9gbri-home-manager-generation.drv' failed to build
```

### Additional context

This behavior was probably introduced with [`91f99f14ff83b3c`](https://github.com/NixOS/nixpkgs/pull/222762/commits/91f99f14ff83b3c2ca0c90c29ada3b030127152d) reverting this commit fix the issue.

### Notify maintainers
@Kiskae 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-26-generic, Ubuntu, 23.10 (Mantic Minotaur), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - nixpkgs: `/nix/store/vsmj7776ik51zzkyy22ydl00ib2w1rpp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
This appears to be a bug in NixGL.

In the following line it overrides using the wrong original parameter: https://github.com/nix-community/nixGL/blob/d709a8abcde5b01db76ca794280745a43c8662be/nixGL.nix#L84

**Comment by jankrejci** [comment]
Yes, I forgot, this is the other thing that needed to be fixed, but there is a pending PL for that. But still, it is needed to revert the upper-mentioned commit to installing `nixGLNvidia` successfully, as it complains that `bsdtar` is not available.

**Comment by Kiskae** [comment]
That commit is required to support drivers that are compressed with zstd, which all the new ones are.

The problem is that NixGL throws away the dependency that provides bsdtar, which causes the issue you're seeing.

**Comment by eclairevoyant** [comment]
nixGL isn't part of this repo, the issue should be opened in the nixGL repo if it's nixGL specific.

**Comment by jankrejci** [comment]
@Kiskae thanks for the explanation, I will try to bother them :)
