### ISSUE TITLE
mold with libtbb version 2021.9.0 or older is unstable

### ISSUE THREAD

**Issue by silvanshade** [NixOS/nixpkgs#301387]
### Describe the bug

The current `mold` package sometimes causes build failures due to instability (or warnings related to known instability).

### Steps To Reproduce

For example, trying to build `hyprland` with `mold` in the following fashion:

```nix
nixpkgs.overlays = [
  (_final: prev: {
    hyprland = prev.hyprland.override {
      stdenv = prev.useMoldLinker prev.llvmPackages.stdenv;
    };
  })
];
```

leads to the following output in `meson-log.txt`

```
mold: aborted
mold: mold with libtbb version 2021.9.0 or older is known to be unstable under heavy load. Your libtbb version is 2021.8. Please upgrade your libtbb library and try again.
mold: aborted
mold: mold with libtbb version 2021.9.0 or older is known to be unstable under heavy load. Your libtbb version is 2021.8. Please upgrade your libtbb library and try again.
/nix/store/84fxmapz4q1i6xjfsm7ml7g62i49r7wf-ccache-links-wrapper-4.9.1/bin/ld.mold: line 269:    53 Aborted                 (core dumped) /nix/store/b7hb6xpazdnidp0s87fain2im6lk4f4r-mold-2.30.0/bin/ld.mold ${extraBefore+"${extraBefore[@]}"} ${params+"${params[@]}"} ${extraAfter+"${extraAfter[@]}"}
clang: error: linker command failed with exit code 134 (use -v to see invocation)
```

### Expected behavior

`mold` should successfully link without issue.

### Notify maintainers

@azahi @paveloom

**Comment by siraben** [comment]
I'm not able to replicate:

```
$ nix build  --impure --expr "with import ./. {}; hyprland.override { stdenv = useMoldLinker llvmPackages.stdenv; }" -L
$ realpath result
/nix/store/130pm4fq02sxvzi9ms2ka3mylw5zvg08-hyprland-0.37.1
```

**Comment by silvanshade** [comment]
@siraben My actual configuration for compiling `hyprland` is quite a bit more complicated than the included snippet and difficult to replicate without including large chunks of my system flake, so there may be some confounding factors that trigger the behavior.

Nevertheless, the notice about instability with older version of `tbb` comes directly from the `mold` source:

https://github.com/rui314/mold/blob/81b714c4f3ddea24ed7596170086bef5ac4a35c0/common/signal-unix.cc#L65-L71

So it seems like a good idea to update `tbb`, plus it fixes the issue for me.
