### ISSUE TITLE
Build failure: libpeas2 cannot find lua lgi package

### ISSUE THREAD

**Issue by montchr** [NixOS/nixpkgs#301380]
### Steps To Reproduce

- Build `libpeas2` on `nixos-unstable` 

<details>
<summary><sub>NOTE: an earlier version of this report contained misleading info, preserved for posterity within the collapsed content</sub></summary>

~Unclear to me.~

~I have only been able to reproduce this error as a dependency of my (flake-based) NixOS system configuration on `aarch64-linux`.~

~None of these alone result in an error:~

```
# IGNORE THESE! SEE ABOVE UPDATE FOR CORRECT INFO
# nix build nixpkgs#libpeas
# nix build nixpkgs#gnome-builder
```

</details>

### Build log

Full: https://gist.github.com/montchr/bdfd613a3b747a33f32bb669a30ed265

Excerpt of `nixos-rebuild build --verbose` output (removed unrelated lines):

```
building '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'...
error: builder for '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Compiler for C supports link arguments -Wl,-z,relro: YES
       > Compiler for C supports link arguments -Wl,-z,now: YES
       > Compiler for C supports link arguments -Wl,-Bsymbolic: YES
       > Compiler for C supports link arguments -fno-plt: YES
       > Compiler for C supports arguments -fvisibility=hidden: YES
       > Configuring config.h using configuration
       >
       > meson.build:404:2: ERROR: Problem encountered: Lua51 requested but failed to locate suitable Lua51 and LGI support
       >
       > A full log can be found at /build/libpeas-2.0.1/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/zhishld4zw0dg7wh8zipbzq29ilwyvyi-gnome-builder-45.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bjidb7n0krz58w16rwavz966g4p55yg9-gnome-builder-45.0_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kdjyyxmaxni2pk1q2n3z6i3gmkva4abg-man-paths.drv' failed to build
building '/nix/store/vm6dm6wzasgvh7y6mcxgqzd6x51d9h87-nnn-4.9.drv'...
error: 1 dependencies of derivation '/nix/store/5y654pcc4swqsf6sy1wr4g54nc9gcj5b-system-path.drv' failed to build
...
error: 1 dependencies of derivation '/nix/store/4l71d3j310ipbi29nglnlnjp8215hi1r-nixos-system-tuvok-24.05.20240403.08b9151.drv' failed to build
```

### Additional context

Flake-based configuration for Asahi (Apple Silicon) system tracking `nixos-unstable` (08b9151ed40350725eb40b1fe96b0b86304a654b)

[Update]:

After further searching, I found this upstream issue and fix from 4 years ago:

<https://gitlab.gnome.org/GNOME/libpeas/-/issues/33>
<https://gitlab.gnome.org/GNOME/libpeas/-/merge_requests/20>

I am not sure what to do with that, however.

### Notify maintainers

@NixOS/gnome 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.0-asahi, NixOS, 24.05 (Uakari), 24.05.20240323.44d0940`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/06b0vfbjzpnn5qdar7yw83c6gzqsz5yd-amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by barryfm** [comment]
My build attempt of libpeas2 is attached:

[build.log](https://github.com/NixOS/nixpkgs/files/14859631/build.log)

**Comment by Icy-Thought** [comment]
I was greeted with the same issue when I attempted to update`pkgs.valent` alongside my flake setup.

**Comment by jtojnar** [comment]
That is because `gnome-builder` depends on `libpeas2`.

I am currently bisecting it but it goes slow without https://github.com/timokau/nix-bisect/issues/25.

**Comment by R2Boyo25** [comment]
> That is because `gnome-builder` depends on `libpeas2`.
> 
> I am currently bisecting it but it goes slow without [timokau/nix-bisect#25](https://github.com/timokau/nix-bisect/issues/25).

I added that because the original issue states that they can build `gnome-builder` without the issue.

**Comment by jtojnar** [comment]
Maybe they have cached older version of nixpkgs flake ref.

**Comment by R2Boyo25** [comment]
> That is because `gnome-builder` depends on `libpeas2`.
> 
> I am currently bisecting it but it goes slow without [timokau/nix-bisect#25](https://github.com/timokau/nix-bisect/issues/25).

This comment appears to state that the linked PR is what caused libpeas2 to fail to build: https://github.com/NixOS/nixpkgs/pull/289135#issuecomment-1978270396

**Comment by jtojnar** [comment]
Weird. It was supposed to have been fixed by https://github.com/NixOS/nixpkgs/commit/0f6ddea2ff3b20c536b1530f66ee306014b39d83, which is in nixos-unstable according to https://nixpk.gs/pr-tracker.html?pr=292500 but `libpeas2` still does not build for me.

**Comment by montchr** [comment]
Apologies for the confusing info I provided in the opening description.  I do see build failures for both `libpeas2` and `gnome-builder` now:

```console
[cdom@tuvok]% nix build github:nixos/nixpkgs/nixos-unstable#libpeas2
error: builder for '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Compiler for C supports link arguments -Wl,-z,relro: YES
       > Compiler for C supports link arguments -Wl,-z,now: YES
       > Compiler for C supports link arguments -Wl,-Bsymbolic: YES
       > Compiler for C supports link arguments -fno-plt: YES
       > Compiler for C supports arguments -fvisibility=hidden: YES
       > Configuring config.h using configuration
       >
       > meson.build:404:2: ERROR: Problem encountered: Lua51 requested but failed to locate suitable Lua51 and LGI support
       >
       > A full log can be found at /build/libpeas-2.0.1/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'.
[cdom@tuvok]% nix build github:nixos/nixpkgs/nixos-unstable#gnome-builder
error: builder for '/nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Compiler for C supports link arguments -Wl,-z,relro: YES
       > Compiler for C supports link arguments -Wl,-z,now: YES
       > Compiler for C supports link arguments -Wl,-Bsymbolic: YES
       > Compiler for C supports link arguments -fno-plt: YES
       > Compiler for C supports arguments -fvisibility=hidden: YES
       > Configuring config.h using configuration
       >
       > meson.build:404:2: ERROR: Problem encountered: Lua51 requested but failed to locate suitable Lua51 and LGI support
       >
       > A full log can be found at /build/libpeas-2.0.1/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/d9qijlw975ag76bj5vv82j6l94srcg62-libpeas-2.0.1.drv'.
```

> Maybe they have cached older version of nixpkgs flake ref.

@jtojnar You're right, thanks.  Now I know better for next time to verify stuff like this with `github:nixos/nixpkgs/nixos-unstable` rather than `nixpkgs`, which corresponds to the ref of my current NixOS generation.  I'll update the description.

**Comment by schuelermine** [comment]
Does not build here, nixpkgs @ fd281bd6b7d3e32ddfa399853946f782553163b5

**Comment by jtojnar** [comment]
cc @lolbinarycat and @vcunat who last touched the lua stuff

**Comment by gepbird** [comment]
@vcunat yes, that fixes it, thanks!

libpeas2 builds when cherry picking b8be0164260e61c1859d12b5d973c0f3f67d379c and c55b4dbcd2af7ff8065ee4fece2c8793427ec88b onto nixos-unstable.

**Comment by montchr** [comment]
> libpeas2 builds when cherry picking [b8be016](https://github.com/NixOS/nixpkgs/commit/b8be0164260e61c1859d12b5d973c0f3f67d379c) and [c55b4db](https://github.com/NixOS/nixpkgs/commit/c55b4dbcd2af7ff8065ee4fece2c8793427ec88b) onto nixos-unstable.

For others wishing to track the status of #300905, the PR adding these commits:

<https://nixpk.gs/pr-tracker.html?pr=300905>

Unfortunately, it looks as though the changes have been stuck on the `staging` branch for a few days.  I haven't yet cherry-picked those commits to verify since I expected them to appear in `master` sooner.  But I will try to get to verifying a few hours from now.

I'm having some trouble following the chain of related PRs.  @vcunat (or anyone else) do you have a better sense of when we might see those changes make it out of `staging`?

**Comment by vcunat** [comment]
Roughly two weeks from now.
