### ISSUE TITLE
Minikube 0.22.1 (and greater?) doesn't build on Darwin due to hyperkit

### ISSUE THREAD

**Issue by edude03** [NixOS/nixpkgs#30133]
## Issue description
As the title says, building minikube from source fails on High Sierra (OSX 10.13) due to not being able to find the vmnet/vmnet.h header

You'll get output such as

```
# k8s.io/minikube/vendor/github.com/zchee/go-vmnet
go/src/k8s.io/minikube/vendor/github.com/zchee/go-vmnet/vmnet.go:9:10: fatal error: 'vmnet/vmnet.h' file not found
#include <vmnet/vmnet.h>
         ^~~~~~~~~~~~~~~
1 error generated.
...
ld: warning: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation, ignoring unexpected dylib file
...
builder for ‘/nix/store/7xwsx17gcabbm8zsi60b03smknjfg4j2-minikube-0.22.2.drv’ failed with exit code 1
error: build of ‘/nix/store/7xwsx17gcabbm8zsi60b03smknjfg4j2-minikube-0.22.2.drv’ failed

### Steps to reproduce

Build minikube 0.22.2


## Technical details
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by copumpkin** [comment]
Those headers aren't supposed to be impure so this is weird, but I guess they're semi-impure so that could explain it.

I probably won't have time to take a look for a bit, but it seems like as long as Hydra's builders stay on pre-10.13 this shouldn't cause most users too many issues unless they're on a revision that Hydra hasn't built yet.

**Comment by periklis** [comment]
i am currently working on an experiment to package [zchee/docker-machine-driver-xhyve](/zchee/docker-machine-driver-xhyve) and run in the same issue on 10.12.6. Maybe i can fix this issue.

**Comment by copumpkin** [comment]
You shouldn't need that driver anymore in the latest minikube, since they pulled xhyve support into the main codebase

**Comment by periklis** [comment]
i am experiment to use the driver as an independent alternative to run my docker-daemon and get rid of docker-for-mac. e.g. [Setting up Docker on macOS
](https://pewpewthespells.com/blog/setup_docker_on_mac.html)

**Comment by copumpkin** [comment]
Ah okay 😄

**Comment by johbo** [comment]
Just ran into this issue on OSX 10.12.6.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/a4d7b6ad91c1d7fe942905a30d0c08a0b4d97065 should fix it

**Comment by johbo** [comment]
Looks correct, I'll check quickly

**Comment by johbo** [comment]
yep, works for me™
