### ISSUE TITLE
Package request: serve-d

### ISSUE THREAD

**Issue by Squeed-lol** [NixOS/nixpkgs#301302]
**Project description**

serve-d is an LSP (language server protocol) server for the D programming language 

**Metadata**

* homepage URL: https://github.com/Pure-D/serve-d
* source URL: https://github.com/Pure-D/serve-d
* license: MIT
* platforms: unix, linux, macos, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Will be added in https://github.com/NixOS/nixpkgs/pull/299618
