### ISSUE TITLE
Xonsh no longer start

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#301444]
### Describe the bug
After a recent `nixos-unstable` update, xonsh is no longer able to launch.

```
Traceback (most recent call last):
  File "/nix/store/ghr6zvrvjcww884wrcj0pimmpjs2kx61-xonsh-0.15.1/bin/xonsh", line 5, in <module>
    from xonsh.main import main
ModuleNotFoundError: No module named 'xonsh'
```

### Steps To Reproduce
Launch `xonsh`

### Expected behavior
Xonsh should start without issue

### Additional context
I've found a change of python env that reached `nixos-unstable` recently (https://github.com/NixOS/nixpkgs/pull/297628). Perhaps it is the change that breaks xonsh.

### Notify maintainers
@AndersonTorres 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.22-xanmod1, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FlyingWombat** [comment]
May not be the same issue, but this doesn't work either:
```bash
❯ nix-shell -p 'python3.withPackages (p: with p; [ xonsh ])'
❯ python
Python 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0] on linux
>>> import xonsh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xonsh'
```

**Comment by 3541** [comment]
> ```shell
> python3.withPackages (p: with p; [ xonsh ])'
> ```

Not sure this ever worked—`xonsh` in this expression is coming from Nixpkgs directly, not `p`. It still does not work after https://github.com/NixOS/nixpkgs/pull/302385.

**Comment by SamLukeYes** [comment]
> > ```shell
> > python3.withPackages (p: with p; [ xonsh ])'
> > ```
> 
> Not sure this ever worked—`xonsh` in this expression is coming from Nixpkgs directly, not `p`. It still does not work after #302385.

That's a different issue. You should probably use `xonsh.override { extraPackages = ps: with p; [ ... ]; }` instead. However, if you really need the full python env, unfortunately there's no way to use it outside the xonsh derivation for now. Maybe we should add it to `passthru`.
