### ISSUE TITLE
L2TP VPN "Cannot create run-dir " / how to restart network-manager with the latest derivations

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#30147]
## Issue description
I am trying to fix L2TP plugin (https://github.com/nm-l2tp/network-manager-l2tp) to create a VPN (hence I updated it from 1.2.4 to 1.2.8 IIRC). 
Currently it fails with
 `VPN connection: failed to connect: 'Cannot create run-dir /nix/store/f7bpngi5igcgsydlwhvbh7ryw5fk5zcf-NetworkManager-l2tp-gnome-1.2.8/var/run`

I am trying to adjust the ./configure settings to make it work but the problem is that I am not sure how to restart network-manager to test my l2tp plugin changes. 
`sudo nixos-rebuild switch` seems to build the new derivation but restarting network manager seems to run with the old derivation (hash remains the same). I don't mind fixing the derivation but having to reboot to test it is a pain.

### Steps to reproduce
fetch the branch from https://github.com/teto/nixpkgs/tree/l2tp, configure an l2tp vpn then
sudo nixos-rebuild switch

## Technical details

nixos-version=18.03.git.44c1619 (Impala)
nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03.git.44c1619fc6M"
sandboxing disabled

**Comment by teto** [comment]
Hum apparently I was doing thg wrong (might be because it was installed in my user profile too), network-manager seems to correctly restart now.
I've updated the recipe (https://github.com/teto/nixpkgs/tree/l2tp) to make sure that it networkmanager_l2tp uses /var/run instead of nix/store/f7bpngi5igcgsydlwhvbh7ryw5fk5zcf-NetworkManager-l2tp-gnome-1.2.8/var/run. It was also complaining that it could not read/write/etc/**secrets" so I also added "--sysconfdir=/etc" to the configure flags.
Now networkmanager_l2tp complains on nixos-rebuild of:
```
 /nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28/bin/mkdir -p '/etc/dbus-1/system.d'
/nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28/bin/mkdir: cannot create directory '/etc/dbus-1/system.d': Permission denied
```
The makefile contains:
`dbusservicedir = $(sysconfdir)/dbus-1/system.d`
thing is I don't know much about systemd and I don't know where this folder should go in nixos :(

**Comment by teto** [comment]
I've searched for /etc/dbus on the tracker and found quite a few matches. The dbus service installation folder seems to have changed quite a bit and I've trouble knowing what's the best folder sorry to ping you @abbradar but you seem to be the specialist :) where should networkmanager_l2tp install his dbus files please ?

**Comment by abbradar** [comment]
It should work with `$(out)/etc/dbus-1/system.d`, I think -- where `$(out)` is output path.

**Comment by teto** [comment]
Thanks a lot; I patched accordingly and it solved the dbus problem.

After solving that I got:
`VPN connection: failed to connect: 'Could not write /etc/ipsec.d/nm-l2tp-ipsec-74615f38-bdb3-424b-898c-440e3f490289.sec`
My first reflex was to create /etc/ipsec.d manually. Afterwards it seemed to run but could not connect. 
```
oct. 11 12:25:57 jedha NetworkManager[9391]: Stopping strongSwan IPsec failed: starter is not running
oct. 11 12:25:59 jedha NetworkManager[9391]: Starting strongSwan 5.6.0 IPsec [starter]...
oct. 11 12:25:59 jedha NetworkManager[9391]: Loading config setup
oct. 11 12:25:59 jedha NetworkManager[9391]: Loading conn '74615f38-bdb3-424b-898c-440e3f490289'
oct. 11 12:25:59 jedha ipsec_starter[31169]: Starting strongSwan 5.6.0 IPsec [starter]...
oct. 11 12:25:59 jedha ipsec_starter[31169]: Loading config setup
oct. 11 12:25:59 jedha ipsec_starter[31169]: Loading conn '74615f38-bdb3-424b-898c-440e3f490289'
oct. 11 12:25:59 jedha NetworkManager[9391]: sh: modprobe : commande introuvable
oct. 11 12:25:59 jedha NetworkManager[9391]: sh: modprobe : commande introuvable
oct. 11 12:25:59 jedha NetworkManager[9391]: sh: modprobe : commande introuvable
oct. 11 12:25:59 jedha NetworkManager[9391]: sh: modprobe : commande introuvable
oct. 11 12:25:59 jedha NetworkManager[9391]: sh: modprobe : commande introuvable
oct. 11 12:25:59 jedha NetworkManager[9391]: found netkey IPsec stack
oct. 11 12:25:59 jedha ipsec_starter[31169]: found netkey IPsec stack
oct. 11 12:25:59 jedha ipsec_starter[31183]: Attempting to start charon...
oct. 11 12:25:59 jedha charon[31184]: 00[DMN] Starting IKE charon daemon (strongSwan 5.6.0, Linux 4.13.4, x86_64)
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] PKCS11 module '<name>' lacks library path
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] dnscert plugin is disabled
oct. 11 12:25:59 jedha charon[31184]: 00[NET] using forecast interface eno1
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] joining forecast multicast groups: 224.0.0.1,224.0.0.22,224.0.0.251,224.0.0.252,239.255.255.250
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading ca certificates from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/cacerts'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading aa certificates from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/aacerts'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading ocsp signer certificates from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/ocspcerts'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading attribute certificates from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/acerts'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading crls from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/crls'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] loading secrets from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.secrets'
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] opening triplet file /nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.d/triplets.dat failed: No such file or directory
oct. 11 12:25:59 jedha charon[31184]: 00[CFG] no script for ext-auth script defined, disabled
oct. 11 12:25:59 jedha charon[31184]: 00[LIB] loaded plugins: charon unbound pkcs11 aesni aes des rc2 sha2 sha1 md5 rdrand random nonce x509 revocation constraints acert pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey dnscert pem af-alg fips-prf gmp curve25519 chapoly xcb
oct. 11 12:25:59 jedha charon[31184]: 00[JOB] spawning 16 worker threads
oct. 11 12:25:59 jedha ipsec_starter[31183]: charon (31184) started after 220 ms
oct. 11 12:25:59 jedha charon[31184]: 05[CFG] received stroke: add connection '74615f38-bdb3-424b-898c-440e3f490289'
oct. 11 12:25:59 jedha charon[31184]: 05[CFG] added configuration '74615f38-bdb3-424b-898c-440e3f490289'
oct. 11 12:26:00 jedha charon[31184]: 06[CFG] rereading secrets
oct. 11 12:26:00 jedha charon[31184]: 06[CFG] loading secrets from '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/ipsec.secrets'
oct. 11 12:26:00 jedha charon[31184]: 07[CFG] received stroke: initiate '74615f38-bdb3-424b-898c-440e3f490289'
oct. 11 12:26:00 jedha charon[31184]: 16[IKE] initiating Main Mode IKE_SA 74615f38-bdb3-424b-898c-440e3f490289[1] to FAKEIP
oct. 11 12:26:00 jedha charon[31184]: 16[IKE] initiating Main Mode IKE_SA 74615f38-bdb3-424b-898c-440e3f490289[1] to FAKEIP
oct. 11 12:26:00 jedha charon[31184]: 16[ENC] generating ID_PROT request 0 [ SA V V V V V ]
oct. 11 12:26:00 jedha charon[31184]: 16[NET] sending packet: from 192.168.0.129[500] to FAKEIP[500] (240 bytes)
oct. 11 12:26:04 jedha charon[31184]: 11[IKE] sending retransmit 1 of request message ID 0, seq 1
oct. 11 12:26:04 jedha charon[31184]: 11[NET] sending packet: from 192.168.0.129[500] to FAKEIP[500] (240 bytes)
oct. 11 12:26:10 jedha NetworkManager[9391]: Stopping strongSwan IPsec...
oct. 11 12:26:10 jedha charon[31184]: 00[DMN] signal of type SIGINT received. Shutting down
oct. 11 12:26:10 jedha charon[31184]: 00[IKE] destroying IKE_SA in state CONNECTING without notification
oct. 11 12:26:10 jedha NetworkManager[9391]: initiating Main Mode IKE_SA 74615f38-bdb3-424b-898c-440e3f490289[1] to FAKEIP
oct. 11 12:26:10 jedha NetworkManager[9391]: generating ID_PROT request 0 [ SA V V V V V ]
oct. 11 12:26:10 jedha NetworkManager[9391]: sending packet: from 192.168.0.129[500] to FAKEIP[500] (240 bytes)
oct. 11 12:26:10 jedha NetworkManager[9391]: sending retransmit 1 of request message ID 0, seq 1
oct. 11 12:26:10 jedha NetworkManager[9391]: sending packet: from 192.168.0.129[500] to FAKEIP[500] (240 bytes)
oct. 11 12:26:10 jedha NetworkManager[9391]: destroying IKE_SA in state CONNECTING without notification
oct. 11 12:26:10 jedha NetworkManager[9391]: establishing connection '74615f38-bdb3-424b-898c-440e3f490289' failed
oct. 11 12:26:10 jedha ipsec_starter[31183]: child 31184 (charon) has quit (exit code 0)
oct. 11 12:26:10 jedha ipsec_starter[31183]: 
oct. 11 12:26:10 jedha nm-l2tp-service[31153]: g_dbus_method_invocation_take_error: assertion 'error != NULL' failed
oct. 11 12:26:10 jedha NetworkManager[9391]: <warn>  [1507692370.5294] vpn-connection[0x1ba9690,74615f38-bdb3-424b-898c-440e3f490289,"Connexion VPN 1",0]: VPN connection: failed to connect: 'Message recipient disconnected from message bus without replying'

```
strongswan/networkmanager/networkmanager-l2tp should be able to access the same files as there is some read/rewrite of secrets I believe (sthg I read in the code).
So I changed the networkmanager_l2tp so that it uses ${strongswan}/etc instead of /etc/ but on install it doesn't like to touch the hierarchy of the other derivation. I wonder what should be done here. 

```
ec'
libtool: install: /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/install -c nm-l2tp-auth-dialog /nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/libexec/nm-l2tp-auth-dialog
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp/auth-dialog'
make[1]: Leaving directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp/auth-dialog'
make[1]: Entering directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
make[2]: Entering directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
make[2]: Nothing to be done for 'install-exec-am'.
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/mkdir -p '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/share/appdata'
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/install -c -m 644 appdata/network-manager-l2tp.metainfo.xml '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/share/appdata'
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/mkdir -p '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/etc/dbus-1/system.d'
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/install -c -m 644 nm-l2tp-service.conf '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/etc/dbus-1/system.d'
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/mkdir -p '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/lib/NetworkManager/VPN'
 /nix/store/z8s1fy0ac1p1dgf0p0bxlmnn4h72qsfg-coreutils-8.28/bin/install -c -m 644 nm-l2tp-service.name '/nix/store/ys21sp0b63nihijyj730y8nlhmwp10qj-NetworkManager-l2tp-gnome-1.2.8/lib/NetworkManager/VPN'
make  install-data-hook
make[3]: Entering directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
mkdir -p /nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/NetworkManager/VPN
mkdir: cannot create directory '/nix/store/4b15381yxcychsiaip2cwrr923k03x07-strongswan-5.6.0/etc/NetworkManager': Permission denied
make[3]: *** [Makefile:999: install-data-hook] Error 1
make[3]: Leaving directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
make[2]: *** [Makefile:921: install-data-am] Error 2
make[2]: Leaving directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
make[1]: *** [Makefile:868: install-am] Error 2
make[1]: Leaving directory '/tmp/nix-build-NetworkManager-l2tp-gnome-1.2.8.drv-0/l2tp'
```

**Comment by peterhoeg** [comment]
For the modprobe errors, have a look at this: https://github.com/NixOS/nixpkgs/issues/8343

**Comment by teto** [comment]
@peterhoeg the patch got merged 2 years ago in https://github.com/NixOS/nixpkgs/pull/11351 or do you mean it might be the same problem emerging again ?

I believe I got strongswan + l2tp networkmanager plugin working (I can't say for certain yet as my VPN account doesn't allow me to test everything yet). I don't believe it was ever supposed to work as it is in in nix. I made it work with hacks and now I would like to upstream a proper nix(OS) solution. Thus I am looking for feedback on what modifications should be done (including l2tp upstream).

(Before starting as a sidenote I tried setting "secrets" from the strongswan service https://nixos.org/nixos/options.html#strongsw but I could not find if it was taken into account or not, the ipsec.secrets remaining empty).
So without the strongswan service running, here are the issues:
1. l2tp (i.e., the network manager plugin) first reads "/etc/ipsec.secrets" to check if it includes "includes ipsec.d/*.secrets" and if not tries to append to it. This doesn't work in nixos as strongswan secrets are in strongswan's store nix-store and thus l2tp can't write to it.
My current workaround for was to create a fake /etc/ipsec.secrets (unused) so that l2tp finds what he wants and doesn't trigger a write to it;
```
environment.etc."ipsec.secrets".text = ''
      # this is checked by l2tp
      include /etc/ipsec.d/*.secrets
      '';
      environment.etc."ipsec.d/stub".text = ''
        stub file to create ipsec.d
      '';
```
and then I patched strongswan default /nix/srotre/XXXXX-strongswan/etc/ipsec.secrets so that it include /etc/ipsec.d

2. Once the connection is successful, some package (ppp a priori) tries to generate /etc/ppp/resolv.conf (not to overwrite the system one /etc/resolv.conf) and it could not create it because the folder /etc/ppp doesn't exist
I thus create the /etc/ppp folder 'manually' via
```
  # maybe it should create it in /var/run
  environment.etc."ppp/stub".text = ''
  '';
```

Now I would like to have a working solution without all these manual `environment.etc."FILE".text = ''` but I am not sure how to do it. I could modify l2tp so that it looks into
/nix/srotre/XXXXX-strongswan/etc/ipsec.secrets instead but how to indicate to it the paths where to load l2tp secrets from ? (currently "/etc/ipsec.d") ?

As for  /etc/ppp/resolv.conf I thought resolv.conf would be in /var/run but there seems to be quite a few in /etc already:
fd resolv /etc                                                                                ~
/etc/resolv.conf
/etc/resolvconf.conf

**Comment by teto** [comment]
Here is what I believe is the correct path (I will open a PR if no one contradicts me):
if networking.networkmanager.packages (https://nixos.org/nixos/options.html#networkmanager) contains l2tp then it should create the paths I used to create manually.

The presence of l2tp should also add "secrets" path to services.strongswan.secrets (https://nixos.org/nixos/options.html#strongswan)

**Comment by teto** [comment]
Pr got merged \o/
