### ISSUE TITLE
Go builders build in parallel even if you don't ask for parallel builds

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#30140]
At least with `pkgs.keybase`, I see it calling GNU parallel with 8 jobs even though I didn't pass in `--cores 8`. Git hash is recent master at dd9a4737636e818bc08077dd49a54a0da8bd0cea.

**Comment by orivej** [comment]
If you mean that Go compiler currently does not respect `NIX_BUILD_CORES`, this is true. It can be controlled via a `GOMAXPROCS` environment variable, but I'd set `GOMAXPROCS=NIX_BUILD_CORES` by default only if we also enable parallel building in `buildGoPackage`.

**Comment by zowoq** [comment]
`NIX_BUILD_CORES` and `enableParallelBuilding` are respected in `buildGo{Module,Package}`.
