### ISSUE TITLE
Build failure: All documentation jobs fail

### ISSUE THREAD

**Issue by hsjobeki** [NixOS/nixpkgs#301490]
### Steps To Reproduce
Visit:
 
https://github.com/NixOS/nixpkgs/actions/workflows/manual-nixpkgs.yml
https://github.com/NixOS/nixpkgs/actions/workflows/manual-nixos.yml

All build jobs keep failing. Since ~20:00 UTC Yesterday (03.04.2024)

### Build log

https://github.com/NixOS/nixpkgs/actions/workflows/manual-nixpkgs.yml

Log says:

```
  Binary cache nixpkgs-ci doesn't exist or it's private and you need a token: Start by visiting https://app.cachix.org and create a personal/cache auth token.
  
  To configure the token:
  
  a) Via environment variable: 
  
  $ export CACHIX_AUTH_TOKEN=<token...>
  
  b) Via configuration file:
  
  $ cachix authtoken <token...>::error::Action failed with error: Error: The process '/home/runner/.nix-profile/bin/cachix' failed with exit code 1
```

### Notify maintainers

@Mic92 @zowoq

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zowoq** [comment]
@zimbatm IIRC you created this cachix cache and added the token for us.
