### ISSUE TITLE
element-desktop : Neither notification on screen, nor in Gnome notification center

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#301493]
### Describe the bug

Notification from Element desktop don't display. I got the sound notification and Element icon shows me there is a notification but it doesn't display as if I was in "don't disturb" mode except I'm not and it doesn't appear in notification centre neither (which it should even though I would be in "don't disturb" mode).

### Steps To Reproduce
1. Install element-desktop on nixos 23.11 with Gnome under wayland or X11 (issue happen on both)
2. receive a message while having element-desktop reduced
3. hear the sound of notification
4. see a little red number on the right side of Element icon in the dash bar
5. Notification doesn't display on the screen and doesn't appear in notification center

### Expected behavior
Notification should appear on screen and in notification center as it does for Firefox and Thunderbird

### Notify maintainers

@Ma27  @fadenb @mguentner @Ralith @dali99 @sumnerevans @NickCao 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5742.219951b495fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Thatoo** [comment]
It could be an electron issue but I don't have other electron app using notification to test.

**Comment by Thatoo** [comment]
I tried on Wayland to install https://search.nixos.org/packages?channel=23.11&show=element-desktop-wayland&from=0&size=50&sort=relevance&type=packages&query=element in case it would solve the issue on Wayland but it doesn't install element-desktop at all.

**Comment by Thatoo** [comment]
Installing both `element-dekstop` and `element-desktop-wayland ` does not help.

**Comment by iclanzan** [comment]
I think this issue has been fixed 2 weeks ago by https://github.com/NixOS/nixpkgs/pull/296971.

**Comment by Thatoo** [comment]
Could be indeed.
Would it be possible then to backport it to 23.11 ?

**Comment by Thatoo** [comment]
drupol just did it https://github.com/NixOS/nixpkgs/pull/301522 so notification might come back soon. I'll close this issue after it comes back.

**Comment by Thatoo** [comment]
Backport of https://github.com/NixOS/nixpkgs/pull/296971 in https://github.com/NixOS/nixpkgs/pull/301522 solved indeed this issue.
