### ISSUE TITLE
XFCE Touchpad configuration UI not compatible with 'services.xserver.libinput.enable' set to 'true'.

### ISSUE THREAD

**Issue by maratbn** [NixOS/nixpkgs#30148]
## Issue description
XFCE Touchpad configuration UI not compatible with `services.xserver.libinput.enable` set to `true`.  Specifically, the 'Touchpad' tab in the UI is missing even when the touchpad device is selected via the combo box.  Problem is resolved by replacing `services.xserver.libinput.enable` by `services.xserver.synaptics.enable`.

### Steps to reproduce
(1) Have your `/etc/nixos/configuration.nix` include the lines `services.xserver.libinput.enable = true;` and `services.xserver.desktopManager.xfce.enable = true;`
(2) Run `nixos-rebuild switch`.
(3) Reboot to insure the new settings took effect.
(4) Login into an XFCE session.
(5) Go to 'Applications' -> 'Settings' -> 'Mouse and Touchpad'.  This will cause the 'Mouse and Touchpad' configuration window to appear.
(6) Select the touchpad device ('AlpsPS/2 ALPS DualPoint TouchPad' in my particular case) from the combo box.  Observe that the 'Buttons and Feedback' tab will be present, but the 'Touchpad' tab that allows configuring touchpad-specific settings, such as 'Tap touchpad to click' will be absent.
(7) Replace the line `services.xserver.libinput.enable = true;` in `/etc/nixos/configuration.nix` by `services.xserver.synaptics.enable = true;`
(8) Run `nixos-rebuild switch`.
(9) Reboot your system to insure that the new settings will take effect.
(10) Login into an XFCE session.
(11) Go back to 'Applications' -> 'Settings' -> 'Mouse and Touchpad'.
(6) Select that same touchpad device from the combo box as in step (6).  Observe that this time the 'Touchpad' tab with the touchpad-specific settings will be present in the UI.

## Technical details

* System: `17.09.1462.07ca7b64d2 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `17.09.1462.07ca7b64d2`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by yegortimoshenko** [comment]
Yeah, `xfce.xfce4settings` derivation is compiled w/o `libinput`. See upstream:

https://github.com/xfce-mirror/xfce4-settings/blob/c6761923759772417092165549cb3448f839b26d/configure.ac.in#L174-L178

This has been pestering me for a while, thanks.

**Comment by maratbn** [comment]
OK, thanks @yegortimoshenko for looking into this.

Even though this is not presently supported in the official build, would it be possible to do a custom build locally?  If so, could you point to some reference material or an example?  So far I could not figure out how to force a local build.

**Comment by yegortimoshenko** [comment]
@maratbn I'm sorry for missing this. Next time when you want to grab something from master, you could do that:

```
nix-env -f https://codeload.github.com/NixOS/nixpkgs/tar.gz/master -iA xfce.xfce4settings
```

**Comment by maratbn** [comment]
Thanks @yegortimoshenko,

That did get the `xfce.xfce4settings` with the `libinput` addition you made installed on my system, and the 'Touchpad' tab is now available in the UI.
