### ISSUE TITLE
Overlays should not require default.nix

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#30159]
## Issue description

I've been using overlays for a while but recently noticed edge cases:

```
❯ nix-prefetch-url -A wget.src
error: getting status of ‘/data/dermetfan/.dotfiles/.config/nixpkgs/overlays/default.nix’: No such file or directory
```

Hydra fails to evaluate my jobsets and gives an error about overlays not being found. Unfortunately I have no copy of the error at hand as my server recently died. 

If I place an empty `default.nix` (`self: super: {}`) the error changes, but probably only due to me using `nix-prefetch-url` incorrectly:
```
❯ nix-prefetch-url -A wget.src
error: the expression selected by the selection path ‘wget.src’ should be a set but is a function
```

The [manual](https://nixos.org/nixpkgs/manual/#sec-overlays-install) explains the layout of the overlays directory like this:

> - If the path is a directory, then we take the content of the directory, order it lexicographically, and attempt to interpret each as an overlay by:
>   - Importing the file, if it is a .nix file.
>   - Importing a top-level default.nix file, if it is a directory.

If I understand correctly that means `~/.config/nixpkgs/overlays/default.nix` should not be required.

## Technical details

* System: 18.03pre117013.aebdc892d6 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre117013.aebdc892d6
* Sandboxing enabled: no

**Comment by FRidh** [comment]
What is the contents of `/data/dermetfan/.dotfiles/.config/nixpkgs/overlays/`?

**Comment by vyp** [comment]
With the same technical details, I get:

``` shell
$ nix-prefetch-url -A wget.src
error: getting status of ‘/home/u/default.nix’: No such file or directory
```

**Comment by FRidh** [comment]
I think the issue is entirely unrelated to overlays, but due to where you invoke your command. You can only use commands with `--attr` or `-A` on a Nix expression or a tree of Nix expressions. If you execute what you've shown in your home, which does not have a `default.nix`, then it will fail, simply because there is Nix expression.

**Comment by vyp** [comment]
@Fridh oh that was a dense moment by me. :woman_facepalming:

@dermetfan ok so it works for me with the same technical details as you:

``` shell
$ nix-prefetch-url -A wget.src
downloading ‘http://ftpmirror.gnu.org/wget/wget-1.19.1.tar.xz’... [1755/2062 KiB, 305.7 KiB/s]
path is ‘/nix/store/2s5kb131v8fd27ws3ch5f957mq5vs1qn-wget-1.19.1.tar.xz’
1ljcfhbkdsd0zjfm520rbl1ai62fc34i7c45sfj244l8f6b0p58c
```

(I don't have a `~/.config/nixpkgs/overlays/default.nix`.)

**Comment by dermetfan** [comment]
Indeed, no problem from inside `<nixpkgs>`. I may reopen when I get the Hydra machine running again so we can look into the other problem. Thanks for the clarification so far!
