### ISSUE TITLE
How to use gcc7?

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#30179]
## Issue description

I tried to include "pkgs.gcc7" as a build input in my project, but it could not be found.

### Steps to reproduce

My default.nix:

```
let
  pkgs = import <nixpkgs> {};
  stdenv = pkgs.stdenv;
in
stdenv.mkDerivation {
  name = "project";
  buildInputs = [ pkgs.gcc6 ];
  src = ./.;
}
```

## Technical details

* System: 17.03.1775.56da88a298 (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1775.56da88a298"
* Sandboxing enabled: false

**Comment by adisbladis** [comment]
Gcc7 is not a part of the 17.03 release. You can set another nixpkgs version in your `default.nix` like this:

```
with import (builtins.fetchTarball "https://nixos.org/channels/nixos-17.09-small/nixexprs.tar.xz") {};

stdenv.mkDerivation rec {
  name = "project";
  buildInputs = [ gcc7 ];
  src = ./.;
}
```

**Comment by sid-kap** [comment]
Thanks!
Hmm. This kind of thing confuses me a lot. Why is it listed on https://nixos.org/nixos/packages.html if it's not released?

**Comment by vyp** [comment]
17.09 is the latest release.

**Comment by sid-kap** [comment]
@vyp Can you elaborate? Is the packages webpage listing packages from 17.03 or 17.09? Where does it say?

**Comment by vyp** [comment]
I don't know where the packages webpage listing comes from but I know the web pages for the manuals seem to be updated for every release, so I assumed the same for packages.html and options.html.

**Comment by sid-kap** [comment]
I'm still confused. You wrote "17.09 is the latest release." Can you elaborate? How is that related to my question?

**Comment by vyp** [comment]
So I assumed that packages.html is showing packages for 17.09, since it's the latest release.

**Comment by sid-kap** [comment]
Oh, ok. Thanks.

Somehow I upgraded but I'm still on "17.03.1904.09b9f7e7c4". Why is this? How do I upgrade my system to 17.09?

**Comment by sid-kap** [comment]
I ran a `sudo nixos-rebuild switch --upgrade`

**Comment by adisbladis** [comment]
Check which channels you are on
`nix-channel --list`

And maybe you need `nix-channel --update`

**Comment by vyp** [comment]
I believe run the following as root:

``` shell
nix-channel --add https://nixos.org/channels/nixos-17.09 nixos
nixos-rebuild switch --upgrade
```

I got this from https://nixos.org/nixos/manual/index.html#sec-upgrading.

**Comment by sid-kap** [comment]
Is there an automated way to update to the newest channel version? Or do I just have to keep checking the website to see if a new channel is released?

**Comment by vyp** [comment]
I don't think so, but a new release happens every 6 months.

**Comment by vcunat** [comment]
People typically want either:
 - the "rolling updates" style and those follow nixos-unstable channel (or even git master), or
 - the "stable release" style and those tend not to like big automatic jumps.

Last three release cycles were 6-month ones, and it's likely we will keep that for some more time.  The manuals and package list on nixos.org show the latest stable release.

**Comment by sid-kap** [comment]
@vcunat I'm on nixos-unstable. Do you mean to say that nixos-unstable automatically updates you from 17.03 to 17.09? (Because it did not for me.)

**Comment by vcunat** [comment]
Unstable is something else; it will print 18.03 ATM.  You probably have multiple channels added.  Beware that system uses the `nixos` added as root user.  People often confuse it with other channel names or channels added as their regular user...

**Comment by sid-kap** [comment]
Yeah, I'm using `sudo nix-channel`. Here is the output of `sudo nix-channel list`:
```
nixos https://nixos.org/channels/nixos-17.03
```

**Comment by vcunat** [comment]
Yes, that says you're on 17.03.  You probably want to `--remove nixos` and then `--add https://nixos.org/channels/nixos-17.09 nixos` (or perhaps `-unstable` instead of `-17.09).

**Comment by sid-kap** [comment]
Oh ok, that makes sense. I don't know how I ended up on stable... Thanks for all your help!
