### ISSUE TITLE
Package request: FurMark

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [NixOS/nixpkgs#301760]
**Project description**

> FurMark 2 is the successor of the venerable FurMark 1 and is a very intensive GPU stress test on Windows and Linux platforms.

**Metadata**

* homepage URL: https://geeks3d.com/furmark/
* source URL: Proprietary
* license: Proprietary
* platforms: Windows, Linux

---

I don't know how to package a nix package but here's what i found getting it to run from the .zip download:

```nix
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      xorg.libX11
      libGL
      libGLU
    ];
  };
  ```
causes it to launch and `./furmark --demo furmark-gl` works, but `./furmark --demo furmark-vk` crashes with SIGSEGV.

`steam-run ./furmark --demo furmark-vk` works so presumably it's a library issue of some sort but i don't know which.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Hi all, I tried to update this to the latest version 2.8.1.1, my attempts can be seen here

https://github.com/JohnRTitor/nixpkgs/commit/82e215d42729feae296b9dd23d980f3e438d4ebe

however launching FurMark_GUI just crashes with a seg fault, no leads to go on. Any ideas on how to debug and fix this would be helpful.

**Comment by surfaceflinger** [comment]
@JohnRTitor it's gui trying to write logs in /nix/store, afaik gui doesn't take any arguments, so on newer versions you can only use the cli

**Comment by JohnRTitor** [comment]
Makes sense, no wonder why fwrite was failing in gdb trace.

Since this is a proprietary package, we can't even patch it.

**Comment by surfaceflinger** [comment]
They have a Discord server https://geeks3d.com/discord/ we could ask
