### ISSUE TITLE
amphetype could not find Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by glostis** [NixOS/nixpkgs#301819]
### Describe the bug

When trying to run `amphetype`, I am faced with the following Qt error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
```

### Steps To Reproduce
```bash
❯ QT_DEBUG_PLUGINS=1 nix run 'nixpkgs/f480f9d09e4b4cf87ee6151eba068197125714de#amphetype'
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/n1zcprl8az1ssz5nakj4sq8bkkapqkxj-amphetype-1.0.0/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/avyh2b4n7s7ra3lcxr47jn7lnisvhrlc-qtdeclarative-5.15.12-bin/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/p8y236i51qmib4xnzdrvjjk114kprqvg-python3.11-pyqt5-5.15.9/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/glostis/.cache/antidote/paulirish/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/glostis/.nix-profile/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/var/nix/profiles/default/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/wqrxfkp8zqkdpxrq9736a70nsglg4waj-alacritty-0.13.1/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/snap/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/glostis/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/glostis/.local/lib/qt-5.15.12/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/gd3shnza1i50zn8zs04fa729ribr88m9-python3-3.11.8/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: IOT instruction (core dumped)  QT_DEBUG_PLUGINS=1 nix run
```

### Expected behavior

I'm fairly new to nix in general, and definitely not familiar enough with the Qt wrapping mechanism.

I would expect the `amphetype` derivation to somehow set the "Qt plugin path" (`QT_QPA_PLATFORM_PLUGIN_PATH`?) properly so that `libqxcb.so` is found upon startup of the application.

### Additional context

I've found the section [qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""](https://nixos.wiki/wiki/Qt#qt.qpa.plugin:_Could_not_find_the_Qt_platform_plugin_.22xcb.22_in_.22.22) in the NixOS Qt documentation page which recommends using the `wrapQtAppsHook` in your derivation, but as far as I can tell, the `amphetype` derivation [already uses this hook](https://github.com/NixOS/nixpkgs/blob/fd281bd6b7d3e32ddfa399853946f782553163b5/pkgs/by-name/am/amphetype/package.nix#L26)?

A dirty workaround I've found is to manually specify `QT_QPA_PLATFORM_PLUGIN_PATH` as follows, after which the application can be successfully launched:
```bash
QT_QPA_PLATFORM_PLUGIN_PATH=/nix/store/cc2mx3rv8k25i2sb379b4dpcnlg9zlx6-qtbase-5.15.12-bin/lib/qt-5.15.12/plugins/platforms/ nix run 'nixpkgs/f480f9d09e4b4cf87ee6151eba068197125714de#amphetype'
```

I've looked for a way to patch this properly into `amphetype`'s derivation, but I'm not comfortable enough with nix to figure out how to do this.
I've found that other packages such as QGIS do [this in their derivation](https://github.com/glostis/nixpkgs/blob/f01fc7f13d826d29e9f11459170206ea26a5fe09/pkgs/applications/gis/qgis/unwrapped.nix#L167-L169):
```nix
  qtWrapperArgs = [
    "--set QT_QPA_PLATFORM_PLUGIN_PATH ${qtbase.bin}/lib/qt-${qtbase.version}/plugins/platforms"
  ];
```
but it seemed to have no effect in `amphetype`, maybe because the derivation uses `buildPythonApplication`, and not `mkDerivation`?

### Notify maintainers

@rycee 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-100-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/dfwrffdwrrybch69gawdj9qd1rnp7mnk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please test #301891

**Comment by rycee** [comment]
I merged the above PR. @glostis please give it a try once it hits the channel you follow: https://nixpk.gs/pr-tracker.html?pr=301891

**Comment by glostis** [comment]
It works like a charm, many thanks for your fix :heart:
