### ISSUE TITLE
Package request: PyWavefront

### ISSUE THREAD

**Issue by JesusSierralaya** [NixOS/nixpkgs#301898]
**Project description**

> PyWavefront reads Wavefront 3D object files (something.obj, something.obj.gz and something.mtl) and generates interleaved vertex data for each material ready for rendering.

**Metadata**

* homepage URL: https://github.com/pywavefront/PyWavefront
* source URL: https://github.com/pywavefront/PyWavefront
* license: BSD-3-Clause license
* platforms: linux

The version compatible with NixOS 23.11 is 1.3.3. Below is the code for this Python package, which might be useful:

```
  (
    buildPythonPackage rec {
      pname = "PyWavefront";
      version = "1.3.3";
      src = fetchurl {
        url = "https://github.com/pywavefront/PyWavefront/archive/refs/tags/1.3.3.tar.gz";
        sha256 = "sha256-Cf1M0ft46WWe4zuCsbXHFp35f5CNUM0/6/zibGxhkD0=";
      };
      doCheck = false;
      }
  )
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbsds** [comment]
please test https://github.com/NixOS/nixpkgs/pull/306118

```shell
nix shell github:nixos/nixpkgs/refs/pull/306118/merge#python3Packages.pywavefront
```
