### ISSUE TITLE
Neovide on darwin does not produce an app bundle that can be linked to `/Applications/Nix Apps`

### ISSUE THREAD

**Issue by ToyVo** [NixOS/nixpkgs#301984]
### Describe the bug
On aarch64-darwin, while neovide does build and install successfully and I can launch it from the terminal, there is no app bundle that can be found in finder to launch neovide from there or pin it to the dock to launch from. Once opened the global menu calls it .neovide-unwrapped and the icon in the dock is a blank white page as a generic icon.

I can only assume that once #290611 is fixed, that this will also be applicable to x86_64-darwin

### Steps To Reproduce
1. install neovide as either a system app in nix-darwin or a user app in home-manager on aarch64-darwin

### Expected behavior
An app bundle name `Neovide.app` that will be linked into `/Applications/Nix Apps` or `~/Applications/Home Manager Apps` depending on `nix-darwin` and `home-manager` usage

### Screenshots
I'd like to point out that the global menu title is .neovide-unwrapped to for sure indicate that this is the nix neovide and not the homebrew neovide
![image](https://github.com/NixOS/nixpkgs/assets/5168912/a49e5cfc-cee6-482c-b443-ac9cc6c433aa)
![image](https://github.com/NixOS/nixpkgs/assets/5168912/59714891-ca1b-4d4f-a1e6-f0976ef2f351)

### Notify maintainers

@ck3d @MultisampledNight 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - channels(toyvo): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ck3d** [comment]
Following PR added MacOS app information a few days ago:
https://github.com/neovide/neovide/pull/2395

We can install the files with next release of neovide.
