### ISSUE TITLE
infinite recursion

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#30190]
## Issue description

our reverse-proxy can be configued in two ways:

* various `lib.mkOptions`
* hardcoded directory path /var/lib/reverse-proxy/extraConfigs (points to configuration files)

the problem i want to have solved is to make the 'hardcoded' direcotry changeable using a function argument (`nix-build --arg`) or even better by using a `lib.mkOption` but both lead to `infinite recursion` and according to https://stackoverflow.com/questions/45144662/using-imports-with-argument-given-by-lib-mkoption:

> is a note about how NixOS module system works. One of it's assumtions is - you can't branch or otherwise control the number of included modules dynamically based on other config options. That's why many modules define module.enable option, which allows that.
> So, back to your question, imports clause can't depend on config.services.nixcloud-reverse-proxy.configDir, because config variables requires all imports to be already merged. That hardly can be fixed with current module system. Perhaps it's possible to overcome this by using another variable (not config), but is that what you want?

thoughts on possible solutions: 

* using a dynamically generated `wrapper.nix` with the hardcoded path loaded using: `extraConfigsDir = if (builtins.pathExists ./wrapper.nix) then (import ./wrapper.nix) else "/var/lib/nixcloud/reverse-proxy/extraConfigs";` works but then i have to take care of a dynamically generated file in my source base and it doesn't work with hydra CI well either
* i've been using `builtins.getEnv` which lets me pass a variable path but it needs to be done outside the nix code evaluation, that said, before running `nix-build` or `nixos-rebuild`. i want to do CI with nixos tests and there i can't set this environment variable beforehead.
* there is `mkIf` and i wonder if there is another workaround or hack which enables me to dynamically chang that directory path from the nix context itself

# code from modules.nix
```
  /* Given a config set, expand mkMerge properties, and push down the
     other properties into the children.  The result is a list of
     config sets that do not have properties at top-level.  For
     example,

       mkMerge [ { boot = set1; } (mkIf cond { boot = set2; services = set3; }) ]

     is transformed into

       [ { boot = set1; } { boot = mkIf cond set2; services = mkIf cond set3; } ].

     This transform is the critical step that allows mkIf conditions
     to refer to the full configuration without creating an infinite
     recursion.
  */
```

where would i have to start to modify the module system to make this 'dynamic path' possible?

if required i can provide code snippets and examples to all my steps i've taken so far. i want a reasonable implementation but i'm not very familiar with the module system in nixos to do it on my own. i can provide funding for this endavour.

**Comment by nbp** [comment]
If you are willing to use the command line to change the path, you might as well set it in the NIX_PATH or with the `-I` option as such:

```
  nix-build -I my_relative_path=/home/of_random_files/foo.nix ...
```

and use the bracket notation for importing your environment:

```
{ ... }:
{
  imports = [  <my_relative_path> ];
}
```

Hydra let you change the NIX_PATH by adding other expressions if I recall correctly. If not, open an issue against Hydra.

As @danbst already replied on stack overlflow, there is no way for using an option to remove a module.  Or to be more precise, it is possible, but not acceptable within NixOS, and as such no.

There is no new issue here, only questions. => Closing.

**Comment by qknight** [comment]
> you might as well set it in the NIX_PATH or with the -I option as such ...

that is very cool, too. but using a environment variable is so tricky in handling this issue. and for everyone wanting to add nix files dynamically this is going to be a issue.

> As @danbst already replied on stack overlflow, there is no way for using an option to remove a module. Or to be more precise, it is possible, but not acceptable within NixOS, and as such no.

i don't want to remove a module or change any existing one. **instead i need to use the module system because of the typing checks, default value completion and meaningfull error messages** and that is why i'm doing:

```
let
  extraConfigsDir = "/var/lib/nixcloud/reverse-proxy/extraConfigs";
in
...
filesToLoad = if (builtins.pathExists extraConfigsDir) then   
  attrNames (filterAttrs (k: v: v == "regular") (builtins.readDir extraConfigsDir))
else 
  [];
configsFromPath = map (el: (extraConfigsDir + ("/" + el) )) filesToLoad;
# use the nix module system to have type validation and inherit meaningful default values for options which are not set explicitly
toModule = x: ({ config, pkgs, lib, ... }: {
  options = {};
  config.nixcloud.reverse-proxy.extraMappings = x;
});
```

and later:
```
imports = fold (el: c: c ++ [(toModule (import el))]) [ ../../../modules ] configsFromPath;
```

which part of the module system would we have to extend to make this work? the most comforting way would be to read the path name from a `lib.mkOption` i guess.

thanks for your help! really appreciated!

**Comment by qknight** [comment]
i've been thinking about this for quite a while now and paul & me just discovered this solution:

# possible solution 4

we create a `default.nix` inside `reverse-proxy/reverse-proxy-config-tests2` which contains:

```
{  config, pkgs, lib, ... }:
with lib;

{

#nix-build '<nixpkgs/nixos>' -A system --arg configuration ... --arg proxyMappings $PROXYMAPS, richtig? (edited)

  
  # import config files (nixcloud.io specific for reverse proxy configuration)  
  # use the nix module system to have type validation and inherit meaningful default values for options which are not set explicitly
  config = {
  };

  imports =
  let
    #cDir = ./config/;
    cDir = builtins.toPath (./config);

    filesToLoad = attrNames (filterAttrs (k: v: v == "regular") (builtins.readDir cDir));
    configsFromPath = map (el: (cDir + ("/" + el) )) filesToLoad;
    toModule = x: ({ config, pkgs, lib, ... }: {
      options = {};
      config.nixcloud.reverse-proxy.extraMappings = x;
    });
  in
    fold (el: c: c ++ [(toModule (import el))]) [  ] configsFromPath;
}
#../../../modules
```

and call it like that:

```
  machine = { pkgs, lib, ... }: {
    nix.nixPath = [ "nixpkgs=${<nixpkgs>}" "nixos-config=/etc/nixos/configuration.nix" ];
    nix.binaryCaches = lib.mkForce [];
    nixcloud.reverse-proxy.enable = true;
    #nixcloud.everse-poxy.enable = false;
    imports = [ ../reverse-proxy/reverse-proxy-config-tests2  ];

    # Needed so that we have all dependencies available for building the
    # container config within the VM.
    virtualisation.pathsInNixDB = let
      emptyClosure = (import <nixpkgs/nixos/lib/eval-config.nix> {
        modules = lib.singleton { boot.isContainer = true; };
      }).config.system.build.toplevel;
    in [ pkgs.stdenv emptyClosure ];
  };
```
# problem

updating the `default.nix` are now stateful as the code updates to `default.nix` need to be copied into the directory with the config(s) we are about to load.

that said, we pick this solution as it does not require a environment variable, let's us change the include path dynamically and just requires another `imports [ ]` in the main `configuration.nix`.
