### ISSUE TITLE
Warp terminal wayland 

### ISSUE THREAD

**Issue by xiro-codes** [NixOS/nixpkgs#301902]
### Describe the bug
Warp Terminal requires LD_LIBRARY_PATH to contain wayland libs to allow wayland support

### Steps To Reproduce
1. set env variable WARP_ENABLE_WAYLAND 1 
2. launch

how I got it to work
https://app.warp.dev/block/piOjTikLERuFxOZjQ16DMW

### Notify maintainers
@emilytrau  @Enzime @imadnyc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by imadnyc** [comment]
It does seem like it works, but I'd like to know more on how you found this. Where did you find out that that flag had to be enabled?

**Comment by xiro-codes** [comment]
https://docs.warp.dev/help/known-issues 
Environmental Variables

Prefix warp-terminal with the variables (multiple can be used), and once you confirm they work, export them in your .profile/.zprofile to load on startup:

Default to Wayland: WARP_ENABLE_WAYLAND=1

Set Default GPU: e.g. MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA

Set Graphics APIs: e.g. WGPU_BACKEND=gl

**Comment by imadnyc** [comment]
Sick! I'll make the PR now.
