### ISSUE TITLE
Build failure: onnxruntime

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#301949]
### Steps To Reproduce

on current unstable d8fe5e6c92d0d190646fb9f1056741a229980089, onnxruntime build seems to never end ? 
On my 24GB ram desktop, desktop freezes I have to reboot. I tried building it on a 32 cores 128GB Ram with same result. The build takes all the ram and cpu and then the server becomes irresponsive I had to reboot it.

I might have waited at most 2 hours. I can't know if the build progresses, I lose feedback on freeze.

enable config.cudaSupport then `nix-build -A onnxruntime`

### Additional context

My X problem is to compile local-ai with cuda support. (with_cublas = true, see https://github.com/NixOS/nixpkgs/pull/301780).
I thought I would try to bump it but I hit repeatedly cmake errors and I thought I would ask for some help since I dont know that area much. Here is the patch I have so far:
```
diff --git a/pkgs/development/libraries/onnxruntime/default.nix b/pkgs/development/libraries/onnxruntime/default.nix
index 4ece5feea365..f713149fc3a4 100644
--- a/pkgs/development/libraries/onnxruntime/default.nix
+++ b/pkgs/development/libraries/onnxruntime/default.nix
@@ -24,7 +24,7 @@
 
 
 let
-  version = "1.16.3";
+  version = "1.17.1";
 
   stdenv = throw "Use effectiveStdenv instead";
   effectiveStdenv = if cudaSupport then cudaPackages.backendStdenv else inputs.stdenv;
@@ -92,7 +92,7 @@ effectiveStdenv.mkDerivation rec {
     owner = "microsoft";
     repo = "onnxruntime";
     rev = "refs/tags/v${version}";
-    hash = "sha256-bTW9Pc3rvH+c8VIlDDEtAXyA3sajVyY5Aqr6+SxaMF4=";
+    hash = "sha256-wRmghKjRqcZdOQ0SdbpCpCa0uwpWqULs55QcLy7hNQo=";
     fetchSubmodules = true;
   };
 
@@ -104,11 +104,11 @@ effectiveStdenv.mkDerivation rec {
     # - always try find_package first (FIND_PACKAGE_ARGS),
     # - use MakeAvailable instead of the low-level Populate,
     # - use Eigen3::Eigen as the target name (as declared by libeigen/eigen).
-    ./0001-eigen-allow-dependency-injection.patch
+    # ./0001-eigen-allow-dependency-injection.patch
   ] ++ lib.optionals cudaSupport [
     # We apply the referenced 1064.patch ourselves to our nix dependency.
     #  FIND_PACKAGE_ARGS for CUDA was added in https://github.com/microsoft/onnxruntime/commit/87744e5 so it might be possible to delete this patch after upgrading to 1.17.0
-    ./nvcc-gsl.patch
+    # ./nvcc-gsl.patch
   ];
 
   nativeBuildInputs = [
@@ -148,6 +148,7 @@ effectiveStdenv.mkDerivation rec {
     libcufft # cufft.h
     cudnn # cudnn.h
     cuda_cudart
+    nccl
   ]);
 
   nativeCheckInputs = lib.optionals pythonSupport (with python3Packages; [
```

### Metadata
cc @NiklasGollenstede since I saw you laste edited it in https://github.com/NixOS/nixpkgs/pull/291874

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NiklasGollenstede** [comment]
I really only contributed a rather trivial fix to the onnxruntume build, I don't know very much about onnx.

But in general with these AI things, I found that quite often it's only the test that at up. Do you know where your build hangs? There is a chance that some tests would run in reasonable time if they had GPU acceleration, but take _much_ longer even on powerful CPUs. I think I had that with some other AI package that I first thought was hanging in an infinite loop. But then it did finish after running several hours single-threaded on a very recent CPU :shrug:

**Comment by autrimpo** [comment]
The build is very RAM greedy with respect to the number of cores. I just tried to build the latest master and managed to build it with `--cores 2` in about 40 minutes, RAM peaking at around 35GB. This is a rather powerful machine with 7950X3D, so expect longer times according to your hardware. I also suggest running it with `-j 1` to make sure different build jobs don't interfere.

**Comment by teto** [comment]
even with cores=2 systemd ended up killing the process because of ram consumption (on the 24GB machine but I have a 16Gb swap). 
Someone mentioned disabling tests. When using cuda, they are disabled so I tried to disable
`    "-Donnxruntime_BUILD_UNIT_TESTS=ON"` (
and I also tried to disable python because why not, let's simplify the build (and also there is `passthru.tests = lib.optionalAttrs pythonSupport {` though I think only hydra would build those). but then the build fails with:
```
- Could NOT find Git (missing: GIT_EXECUTABLE) 
CMake Warning at CMakeLists.txt:1559 (message):
  MPI and NCCL disabled on Win build.


-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Configuring done (10.9s)
CMake Error at onnxruntime_unittests.cmake:766 (target_link_libraries):
  Target "onnxruntime_providers_cuda_ut" links to:

    GTest::gtest

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  CMakeLists.txt:1693 (include)


CMake Error at onnxruntime_unittests.cmake:61 (target_link_libraries):
  Target "onnxruntime_test_all" links to:

    GTest::gtest

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  onnxruntime_unittests.cmake:820 (AddTest)
  CMakeLists.txt:1693 (include)


CMake Error at onnxruntime_unittests.cmake:57 (target_link_libraries):
  Target "onnxruntime_shared_lib_test" links to:

    GTest::gtest

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  onnxruntime_unittests.cmake:1258 (AddTest)
  CMakeLists.txt:1693 (include)
```
so I think we need something extra in nix when disabling python.

I am trying again by disabling enableParallelBuild on my desktop, else I will try with a limited number of CPU on the 128GB ram server. I am a bit dubious on the -j and --cores setup becaue even with `--cores=2`, btop showed all of my 8 cores being used on the desktop :s It started being limited to 2 but then maybe onnxruntime detects the number of cores but towards the end, all cpus were used.

**Comment by autrimpo** [comment]
Regarding tests, yes, we disabled them in CUDA builds because that limits the build to machines with nvidia cards. Good point about building the tests, that's unnecessary if they never get executed.

As far as gtest goes, it used to be in `nativeCheckInputs`, conditional for python. I moved it to `nativeBuildInputs` because of the disabled check phase. But from the log you posted, it seems to me the original location was correct, but I'd also expect it to not be required after disabling `-Donnxruntime_BUILD_UNIT_TESTS=ON`. I will investigate this.

AFAIK, `passhtru.tests` are indeed used for nixpkgs testing.

As I mentioned on Matrix, I also observed some n>cores cpu spikes, but they were very brief, we're talking a second or two so I didn't pay much attention to it. I think someone else from the maintainers could help shed light on what's going on with that, I only helped to add CUDA support.

**Comment by teto** [comment]
The only thing that made me able to build it is `enableParallelBuilding = false;`, over 2 hours.

I took a screenshot of the memory profile during the build which I found funny
![onnxruntime](https://github.com/NixOS/nixpkgs/assets/886074/6d131758-3b5c-4a92-a743-1cf0f5ce0f72)

I dont have anything actionable in mind so I will close this. Thanks for the help and suggestion @autrimpo . Just knowing that you were able to build was enough to get me going.

**Comment by autrimpo** [comment]
Thank you as well, I removed building the tests and fixed the gtest issue, so I'm going to submit a PR for those in the near future.

I'm still working on tweaking the build parameters so that it can be built without requiring beastly hardware in a reasonable amount of time. If you can spare the time, I'd appreciate if you could try [this branch](https://github.com/autrimpo/nixpkgs/tree/python-onnxruntime-cuda) and report how it works for you. You should be able to use at least some parallelism (I suggest starting with `--cores 8`) for a faster build.
