### ISSUE TITLE
"atom" package changed as "atom-beta" automatically

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#30198]
Hi,

I am using latest verison of nix on Ubuntu 16 64 bit.

I had installed atom package. I update my all aps by this commands:
nix-channel --update nixpkgs
nix-env -u '*'

But my atom package has changed as atom-beta without any warning or something.

Is this normal?

Thank you

**Comment by FRidh** [comment]
Nope. That's because the name part of the name is incorrect in the Nix expression. It should reflect that it is a beta. With the current name, `nix-env` can't distinguish between `atom` and `atomBeta`.
cc @NeQuissimus

**Comment by NeQuissimus** [comment]
Oh, until now I was not even aware there was an atom beta derivation...

**Comment by FRidh** [comment]
@domenkozar added this in 4ffa9ace43906ebdf89e0fac3cedbdd5b6cb1b58.

**Comment by TerkiKerel** [comment]
I am executing these commands:

nix-channel --update nixpkgs
nix-env -u '*'
nix-env -i atom

but it still installs atom-beta.

How can I track when the package will update on production?

Thank you

**Comment by TerkiKerel** [comment]
It fixed. Thank you. :)

**Comment by NeQuissimus** [comment]
Glad to hear
