### ISSUE TITLE
[wofi-emoji] line 5: wtype: command not found

### ISSUE THREAD

**Issue by mobsenpai** [NixOS/nixpkgs#301907]
It seems that the `wofi-emoji` package does not work without the `wtype` package installed, even if `wl-clipboard` is already installed. It would be helpful if `wtype` was a dependency that gets installed with the `wofi-emoji` package, to avoid this issue for other users.

Could we consider making `wtype` a dependency for `wofi-emoji`? This would ensure that users have all the necessary components to use the package without encountering any issues.

Thank you for your attention to this matter.

**Comment by aikooo7** [comment]
Even through wtype is listed as a dependency in wofi-emoji, wofi-emoji is [only a binary with emojis](https://github.com/Zeioth/wofi-emoji/blob/master/build.sh) but I might be wrong, it still built without it through, but I'm not a user of Wayland nor wofi-emoji so please let me know if it is really needed.

**Comment by mobsenpai** [comment]
> Even through wtype is listed as a dependency in wofi-emoji, wofi-emoji is [only a binary with emojis](https://github.com/Zeioth/wofi-emoji/blob/master/build.sh) but I might be wrong, it still built without it through, but I'm not a user of Wayland nor wofi-emoji so please let me know if it is really needed.

I'm sorry if I couldn't explain clearly.  What I meant is that the wofi-emoji does build and successfully gets installed but for it to actually work i.e copy the emoji to clipboard when selected, insert the emoji when selected doesnt work without wtype. If I run the wofi-emoji binary and try selecting any emoji it shows error that wtype is not found. I hope it's clear now.

**Comment by aikooo7** [comment]
> > Even through wtype is listed as a dependency in wofi-emoji, wofi-emoji is [only a binary with emojis](https://github.com/Zeioth/wofi-emoji/blob/master/build.sh) but I might be wrong, it still built without it through, but I'm not a user of Wayland nor wofi-emoji so please let me know if it is really needed.
> 
> I'm sorry if I couldn't explain clearly. What I meant is that the wofi-emoji does build and successfully gets installed but for it to actually work i.e copy the emoji to clipboard when selected, insert the emoji when selected doesnt work without wtype. If I run the wofi-emoji binary and try selecting any emoji it shows error that wtype is not found. I hope it's clear now.

It is clear now, and it probably was but I didn't read correctly. I am not sure we can add a program as a dependency of another? At least I never saw it... I will research and see what I found, I will let this answer here in the meanwhile so someone can correct me if I am wrong.
