### ISSUE TITLE
Package request: realmd

### ISSUE THREAD

**Issue by anthonyroussel** [NixOS/nixpkgs#302069]
This is a follow-up ticket for the packaging of realmd, because this package is quite complex.

**Project description**

DBus service for configuring Kerberos and other online identities.

**Metadata**

* homepage URL: https://www.freedesktop.org/software/realmd/
* source URL: https://gitlab.freedesktop.org/realmd/realmd
* license: lgpl21Only
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by anthonyroussel** [comment]
Attempts:

* https://github.com/NixOS/nixpkgs/pull/181145
* https://github.com/NixOS/nixpkgs/pull/128464

**Comment by anthonyroussel** [comment]
I propose to separate the work into 2 PRs: the packaging then its NixOS module.
Because the NixOS module for `realmd` is quite complex.

I am working on it.

**Comment by anthonyroussel** [comment]
New PR opened for the realmd package: https://github.com/NixOS/nixpkgs/pull/302083

**Comment by anthonyroussel** [comment]
Unfortunately, we cannot build `realmd` documentation at the moment.

`realmd` uses gdbus-codegen (from `glib`), which is itself based on `xmlto`, and does not work in offline mode at this time.

Because of the docbook DTD and XSL URLs generated by these tools.
A resolution could be to add an offline mode to these packages: https://github.com/NixOS/nixpkgs/pull/301631

**Comment by anthonyroussel** [comment]
Fixed oddjobd NixOS module: https://github.com/NixOS/nixpkgs/pull/302195
Required by the realmd NixOS module

**Comment by SohamG** [comment]
Thanks for picking this up!

**Comment by SohamG** [comment]
Adding realmd should finish the SSSD suite

**Comment by anthonyroussel** [comment]
The package is now available in nixpkgs, let's switch to https://github.com/NixOS/nixpkgs/issues/303144
