### ISSUE TITLE
sudo -i nix-channel --update nixpkgs fails at installation time

### ISSUE THREAD

**Issue by axx** [NixOS/nixpkgs#302080]
### Describe the bug
I get this error during installation of nix:
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo HOME=/var/root NIX_SSL_CERT_FILE=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /nix/store/ip0chiw6dkpz161mkkjvdsp8gb16wmf4-nix-2.21.1/bin/nix-channel --update nixpkgs

to update the default channel in the default profile

warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60); retrying in 302 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60); retrying in 700 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60); retrying in 1177 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60); retrying in 2630 ms
error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60)

### Steps To Reproduce
1. Install nix on MacOS: sh <(curl -L https://nixos.org/nix/install)
2. Or... run this command post-installation: sudo -i nix-channel --update nixpkgs

### Expected behavior
There should have been no error, and I would expect to have an output to the command: nix-channel --list.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/350765/21d1cdce-7cfe-4481-8b42-9df8db997ae9)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
error:
       … while calling the 'import' builtin
         at «string»:1:18:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at «string»:1:25:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

---

**Comment by abathur** [comment]
This isn't the right place to file issues regarding nix itself, but I'd see if the steps in the issue comment below make sense and get you sorted:
- https://github.com/NixOS/nix/issues/8081#issuecomment-1962419263

**Comment by axx** [comment]
@abathur Thanks! The steps in the linked comment worked for me :)
