### ISSUE TITLE
Can't build anything from nixos-unstable if 'src' is a directory

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#302046]
### Describe the bug

For any package whose `src` is a directory, it fails when I try to build locally from `nixos-unstable`.

This is happens whether `src` is a path, or `fetchFromGitHub`, or anything that is a `/nix/store/...` directory.

~~I think this is due to the coreutils 9.4 update, which we could rollback (see below).~~

After a bisect, it turned out to be the glibc upgrade 2.38-44 -> 2.39-5 8b24908a76ac20bb12503c7a32ee4d3cea245a74 done in #287594

### Steps To Reproduce
1. Run the kernel `linuxKernel.packages.linux_lqx` from stable (`nixos-23.11`)
2. run `nix build -L 'nixpkgs/nixos-unstable#lsof' --rebuild`

### Expected behavior

Those packages build.

### "Screenshots"

```
# nix build -L 'nixpkgs/nixos-unstable#lsof' --rebuild
lsof> Running phase: unpackPhase
lsof> unpacking source archive /nix/store/snvdq7fanjnd8kadmi3p8i2ivsqjmp3x-source
lsof> cp: setting permissions for 'source': Invalid argument
lsof> do not know how to unpack source archive /nix/store/snvdq7fanjnd8kadmi3p8i2ivsqjmp3x-source
```

```
# nix build -L 'nixpkgs/nixos-unstable#htop' --rebuild
htop> Running phase: unpackPhase
htop> unpacking source archive /nix/store/yw4lq506x7aimb4b6ifrdmga3x9n9xsv-source
htop> cp: setting permissions for 'source': Invalid argument
htop> do not know how to unpack source archive /nix/store/yw4lq506x7aimb4b6ifrdmga3x9n9xsv-source
```

### Additional context

I am running on the `Linux 6.5.11-lqx2` kernel, which is `linuxKernel.packages.linux_lqx` from stable (`nixos-23.11`).

From my debugging, this seems due to a regression in `glibc`, which changed the way they do `chmod`:

```bash
# With coreutils from nixos-23.11 (tried it manually outside the Nix sandbox)
/nix/store/59mv7mybz16jjvnkz4z5shqgaqm4k009-coreutils-full-9.3/bin/cp -pr --reflink=auto -- /nix/store/...-vim vim
# Success!

# With coreutils from nixos-unstable (tried both inside and outside the Nix sandbox)
/nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/cp -pr --reflink=auto -- /nix/store/...-vim vim
# Error:
# /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/cp: setting permissions for 'vim': Invalid argument
```

Running coreutils from nixos-23.11 under strace gives this:

```csh
mkdirat(AT_FDCWD, "vim", 0555)          = 0
newfstatat(AT_FDCWD, "vim", {st_mode=S_IFDIR|0555, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(AT_FDCWD, "vim", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0555, st_size=4096, ...}, AT_EMPTY_PATH) = 0
chmod("/proc/self/fd/3", 040755)        = 0
close(3)                                = 0
```

And coreutils from nixos-unstable under strace gives this:

```csh
mkdirat(AT_FDCWD, "vim", 0555)          = 0
newfstatat(AT_FDCWD, "vim", {st_mode=S_IFDIR|0555, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
fchmodat2(AT_FDCWD, "vim", 040755, AT_SYMLINK_NOFOLLOW) = -1 EINVAL (Invalid argument)
```

According to the `fchmodat` manpage, `EINVAL` is returned when "Invalid flag specified in flags", which here is `AT_SYMLINK_NOFOLLOW`.

Above we can see:

> AT_SYMLINK_NOFOLLOW: If pathname is a symbolic link, do not dereference it: instead operate on the link itself.  This flag is not currently implemented.

### Notify maintainers

Maintainers from glibc:

@edolstra @Ma27 @connorbaker

@vcunat might also be interested.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.11-lqx2, NixOS, 23.11 (Tapir), 23.11.20240328.219951b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/store/9fpv0kjq9a80isa1wkkvrdqsh9dpcn05-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
`glibc` probably slightly changed the syscalls it uses and now exposes some artifact of `nix` sandbox where seccomp filters are applied.

**Comment by minijackson** [comment]
I'm not sure the Nix sandbox has an effect in this case. If I run this outside of the sandbox:

```bash
nix shell 'nixpkgs/nixos-unstable#coreutils'

cp -pr -- /nix/store/<any-path> foo
# -> cp: setting permissions for 'foo': Invalid argument
```

which arguably may be an even bigger problem than not being able to build packages.

Another example:

```bash
nix shell 'nixpkgs/nixos-unstable#coreutils'

mkdir foo
chmod 400 foo
cp -pr foo bar
# -> cp: setting permissions for 'bar': Invalid argument
```

**Comment by vcunat** [comment]
This is closely related, I believe: https://github.com/NixOS/nixpkgs/issues/300635

**Comment by Ma27** [comment]
This seems to be a problem with linux_lxq from 23.11: when I fire up a VM with this kernel from 23.11 and a coreutils from unstable, I get a lot of `Invalid argument` errors just as you reported.

However, when I do the same with linux_lxq from 24.05, I don't.
To double-check I ran `strace -e fchmodat2 cp -pr /nix/store/something-that-is-a-directory/ .` and I got the following output:

```
fchmodat2(AT_FDCWD, "007fsdh8i9nks8fpjysa638mf7sb7a4l-libffi-3.4.6", 040700, AT_SYMLINK_NOFOLLOW) = 0
fchmodat2(AT_FDCWD, "007fsdh8i9nks8fpjysa638mf7sb7a4l-libffi-3.4.6/lib", 040700, AT_SYMLINK_NOFOLLOW) = 0
```

cc @999eagle @JerrySM64 who have touched the zen kernels most recently. Is there any chance to backport the lqx variant to 23.11 (or identify & backport the patch that solved our issue)?

**Comment by 999eagle** [comment]
I don't really know how we'd identify the patch that solves this except through bisecting (which would take a *lot* of compile time for these kernel updates I think), so I've opened #302588 to backport all current lqx/zen updates to 23.11.

**Comment by JerrySM64** [comment]
> I don't really know how we'd identify the patch that solves this except through bisecting (which would take a _lot_ of compile time for these kernel updates I think), so I've opened #302588 to backport all current lqx/zen updates to 23.11.

Thanks for that! I had a few minutes to update the kernels. They will also be backported (A thing I actually thought about a couple months ago).

**Comment by Ma27** [comment]
The lqx backport was merged and will appear on the stable channel in probably a few days. Closing.

**Comment by minijackson** [comment]
Thanks a lot! I'll test it then.
