### ISSUE TITLE
Update request: kodi 20.5 → 21.0

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#302082]
- Package name: kodi
- Latest released version: 21.0
- Current version on the unstable channel: 20.5
- Current version on the stable/release channel: 20.5
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aanderse  
@cpages  
@edwtjo  
@minijackson  
@peterhoeg  
@sephalon

https://github.com/xbmc/xbmc/releases/tag/21.0-Omega

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aanderse** [comment]
it's not out yet

https://kodi.tv/blog/

i have built the alpha a few times and done some minor testing... i will likely bump the version pretty soon after release 👍

**Comment by aanderse** [comment]
looks like we're running low on time... https://github.com/NixOS/nixpkgs/issues/303286

fortunately i took a few minutes to look at this and the new version builds fine

i need to go through the plugins and ensure they are all updated, etc...

if anyone wants to contribute some effort testing this please ping here

**Comment by nvmd** [comment]
> looks like we're running low on time... #303286
> 
> fortunately i took a few minutes to look at this and the new version builds fine
> 
> i need to go through the plugins and ensure they are all updated, etc...
> 
> if anyone wants to contribute some effort testing this please ping here

Hi @aanderse, I think I could help you with both updating and testing. Do you already have a draft branch with the changes?

**Comment by aanderse** [comment]
great, thank you

https://github.com/NixOS/nixpkgs/pull/303497

i am hoping to merge in the next couple days

**Comment by aanderse** [comment]
updated
