### ISSUE TITLE
Yaru theme broken on nixos-unstable

### ISSUE THREAD

**Issue by vigneshpai2003** [NixOS/nixpkgs#302296]
### Describe the bug
Gnome is broken after running nixos-rebuild after updating nix flake on nixos-unstable. Fonts seem to be missing, the top panel is missing as well, only gnome shell related components and extensions seem to be broken, all applications work as expected. What can I do to debug this?

### Steps To Reproduce
1. `nix flake update` to update nixos-unstable source to latest.
2. `nixos-rebuild switch --flake .` to rebuild.
3. Reboot and log back in.

### Expected behavior
The gnome shell works as expected before the update.

### Screenshots
![Screenshot from 2024-04-07 13-54-58](https://github.com/NixOS/nixpkgs/assets/57759856/ea0591aa-ee26-4b3d-b5bf-4ab605122a9b)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - nixpkgs: `/nix/store/j10523yhkcc34478azkgcl70yzcx6j2j-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vigneshpai2003** [comment]
It turns out the problem was cause by the package `yaru-theme` that provides the Yaru gnome shell theme, this is what seems to be 'broken', disabling this theme yields the expected Adwaita theme with everything working.

**Comment by dawidd6** [comment]
I think Yaru 24.04 might be incompatible with GNOME 45 which we still have on development. IMO we should revert this theme to 23.10 on master until GNOME 46 hits the master branch.
