### ISSUE TITLE
Network bridge setup fails on boot

### ISSUE THREAD

**Issue by SupraSummus** [NixOS/nixpkgs#30225]
## Issue description

On NixOS wlan-eth bridge setup fails on boot while it succeeds when performed manually later. I think it may be because wireless interface is being added to bridge before hostapd transforms it into access point. (Afaik wireless interface has to be AP to be part of a bridge.)

Network configuration is:

```
  # lan ip configuration
  networking.interfaces.lan = {
    name = "lan";
    ipAddress = "10.11.13.2";
    prefixLength = 24;
    virtual = true;
  };

  # bridge wifi and eth with lan
  networking.bridges.lan.interfaces = ["wlp2s0" "enp4s0"];

  # DHCP server
  services.dhcpd4 = {
    enable = true;
    interfaces = ["lan"];
    extraConfig = <some config cut>;
  };

  # wifi access point
  services.hostapd = {
    enable = true;
    interface = "wlp2s0";
    ssid = "test";
    wpaPassphrase = "12345678";
  };
```

Right after booting `lan-netdev.service` is failed:
```
[jan@kukla:~]$ sudo systemctl --failed
[sudo] password for jan: 
  UNIT               LOAD   ACTIVE SUB    DESCRIPTION                                                                                                                                          
● dhcpd4.service     loaded failed failed DHCPv4 server                                                                                                                                        
● lan-netdev.service loaded failed failed Bridge Interface lan
[...]
```
```
[jan@kukla:~]$ sudo journalctl -b -eu lan-netdev
-- Logs begin at Thu 2017-10-05 17:30:08 CEST. --
Oct 08 18:00:06 kukla systemd[1]: Starting Bridge Interface lan...
Oct 08 18:00:07 kukla lan-netdev-start[648]: Removing old bridge lan...
Oct 08 18:00:07 kukla lan-netdev-start[648]: Adding bridge lan...
Oct 08 18:00:07 kukla lan-netdev-start[648]: RTNETLINK answers: Operation not supported
Oct 08 18:00:07 kukla systemd[1]: lan-netdev.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 08 18:00:07 kukla systemd[1]: Failed to start Bridge Interface lan.
Oct 08 18:00:07 kukla systemd[1]: lan-netdev.service: Unit entered failed state.
Oct 08 18:00:07 kukla systemd[1]: lan-netdev.service: Failed with result 'exit-code'.
```

I can fix it manually by running:
```
[jan@kukla:~]$ sudo systemctl start lan-netdev
[jan@kukla:~]$ sudo systemctl start network-addresses-lan
[jan@kukla:~]$ sudo systemctl start dhcpd4
[jan@kukla:~]$ sudo systemctl --failed
0 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'
```

### Steps to reproduce

* setup network configuration as described above (wifi managed by hostapd added to bridge is crucial, I think)
* reboot

## Technical details

* System: NixOS: `17.09.1535.1fdca25ee8 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"17.09.1535.1fdca25ee8"`
* Sandboxing enabled: no (`build-use-sandbox = false`)

**Comment by SupraSummus** [comment]
I fixed the problem by removing wireless interface from bridge in system configuration and instructing hostapd to use a bridge:

```
  # bridge eth with lan
  # wifi will be added to bridge by hostapd
  networking.bridges.lan.interfaces = ["enp4s0"];

  # wifi access point
  services.hostapd = {
    enable = true;
    interface = "wlp2s0";
    ssid = "test";
    wpaPassphrase = "12345678";
    extraConfig = ''
      bridge=lan
    '';
  };
```

Quote from [default hostapd.conf](https://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf):
```
# In case of atheros and nl80211 driver interfaces, an additional
# configuration parameter, bridge, may be used to notify hostapd if the
# interface is included in a bridge. This parameter is not used with Host AP
# driver. If the bridge parameter is not set, the drivers will automatically
# figure out the bridge interface (assuming sysfs is enabled and mounted to
# /sys) and this parameter may not be needed.
#
# For nl80211, this parameter can be used to request the AP interface to be
# added to the bridge automatically (brctl may refuse to do this before hostapd
# has been started to change the interface mode). If needed, the bridge
# interface is also created.
#bridge=br0
```

To conclude, this issue may be not an error in nixpkgs but rather effect of misconfiguration.

**Comment by falsifian** [comment]
@SupraSummus are you still using this, and is it consistently working for you? I am using your configuration, but hostapd doesn't always add itself to the bridge. I generally can get it working by manually fiddling with bridge commands or by restarting hostapd (`systemctl stop hostapd`, `systemctl start hostapd`), though that doesn't consistently work (e.g. `systemctl restart hostapd` once had the effect of removing my ethernet interface from the bridge and adding wireless).

**Comment by SupraSummus** [comment]
@falsifian no. My wifi is currently made by commercial, closed-source AP... this is my little hypocrisy ;-)

However, I found some commented lines in my config, which may be related to the issue. Take a look at last two lines.

```
  #services.hostapd = {
  #  enable = true;
  #  interface = "wlp2s0";
  #  ssid = "test";
  #  wpaPassphrase = "12345678";
  #  extraConfig = ''
  #    bridge=lan
  #  '';
  #};
  #systemd.services.hostapd.wants = ["lan-netdev.service"];
  #systemd.services.lan-netdev.before = ["hostapd.service"];
```

I remember battling with order the services are started, but I can't recall if the last two lines were enough.

**Comment by edrex** [comment]
A similar issue crops up when using networkd. `networkctl reconfigure wlan0` gets wlan on the bridge once hostapd is running.

In this variant, I was not able to work around it by removing `wlan0` from the bridge config and adding `bridge=br0` to `services.hostapd.extraConfig`, since something (presumably networkd although the log is only attributed `kernel`) renames the hostapd-created interface to `br0_`. I wasn't able to work around this by adding 
```
systemd.network.br0.extraConfig = ''
  [Unit]
  Before=hostapd.service
'';
```
either, since systemd only knows when the process execs, not when the interface is configured in AP mode.

The upstream issue for this is https://github.com/systemd/systemd/issues/936 , however I feel like what is needed is a version of hostapd that knows how to report when it's ready maybe using sd_notify etc.
