### ISSUE TITLE
How to build devenv version 0.6.3

### ISSUE THREAD

**Issue by phannam** [NixOS/nixpkgs#302274]
## Issue description
I've upgraded MacOS (Apple M1) and unfortunately it kills devenv version 0.6.3 on my laptop, then I follows guidance in the https://devenv.sh/getting-started/#1-install-nix to install nix and devenv. The latest devenv is v1.0.3 that cause many issues to our project when we run devenv up or devenv shell.

I'm stuck at here and don't know next step, except to try building devenv version 0.6.3 from https://github.com/cachix/devenv/tree/v0.6.3

But I don't know how to build it. Many thanks to nix team if we have older devenv version that I could use to install devenv 0.6..

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by sevillaarvin** [comment]
How did you install devenv before? If you installed via:

```nix
        (import (fetchTarball https://install.devenv.sh/latest)).default
```

perhaps you can change it directly to:

```nix
        (import (fetchTarball https://codeload.github.com/cachix/devenv/legacy.tar.gz/refs/tags/v0.6.3)).default
```

Not sure if it will work though.

**Comment by nim65s** [comment]
I guess since v1 is a rewrite in rust, this question can be closed. Feel free to reopen if needed.
