### ISSUE TITLE
nixos-rebuild: Don't search for config when using list-generations

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#302267]
### Describe the bug

```
$ nixos-rebuild list-generations
building Nix...
error:
       … while evaluating the attribute 'config'

         at /nix/store/m2vm0yz7h4x98hliw583b8n43w5kw5dw-source/lib/modules.nix:322:9:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          323|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/m2vm0yz7h4x98hliw583b8n43w5kw5dw-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
```

### Steps To Reproduce

Run it.

### Expected behavior

No error.

### Additional context

https://discourse.nixos.org/t/list-generations-throws-error-file-nixos-config-was-not-found/40622

### Notify maintainers

@Profpatsch 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21, NixOS, 24.05 (Uakari), 24.05.20240315.b030cfc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/m2vm0yz7h4x98hliw583b8n43w5kw5dw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rutherther** [comment]
Workaround is to symlink your flake to /etc/nixos or to supply flake flag with path to your flake.

**Comment by tiecia** [comment]
> Workaround is to symlink your flake to /etc/nixos or to supply flake flag with path to your flake.

Supplying the flake with a flag works for me. Did not try the symlink.

**Comment by doronbehar** [comment]
> Supplying the flake with a flag

Could you please be more specific? I don't understand what you mean.

**Comment by Rutherther** [comment]
Are you using flakes?

**Comment by doronbehar** [comment]
Yes. I think I got it, the command to run is:

```
nixos-rebuild --flake ~/path/to/my/non-standard/nixos-configs/\# list-generations
```

**Comment by samueldr** [comment]
Just to be clear, @doronbehar: how would you normally use `nixos-rebuild switch` here?

I might have jumped the gun in changing the name of the issue, and maybe it's more like "nixos-rebuild: better error messages when missing configuration.nix and flakes both"

**Comment by eclairevoyant** [comment]
The point is that you don't need to search `NIX_PATH` if you're just listing generations

**Comment by doronbehar** [comment]
> Just to be clear, @doronbehar: how would you normally use `nixos-rebuild switch` here?

I always have to use the `--flake` argument.

> The point is that you don't need to search `NIX_PATH` / know where the config is located if you're just listing generations

And yes I agree with this. The current title, "nixos-rebuild: Don't search for config when using list-generations" is better IMO.

**Comment by eclairevoyant** [comment]
As a workaround until the PR lands, you can run `nixos-rebuild list-generations --fast` to suppress the error.

**Comment by samueldr** [comment]
Thank you, this served well to confirm my assumptions. And yes, @eclairevoyant, exactly what I had in mind as the root cause.
