### ISSUE TITLE
Update request: xorg.xorgproto 2023.2 → 2024.1

### ISSUE THREAD

**Issue by VeilSilence** [NixOS/nixpkgs#302216]
- Package name: xorg.xorgproto
- Latest released version: 2024.1

- Current version on the unstable channel: 2023.2
- Current version on the stable/release channel:2023.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
No maintainers.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by VeilSilence** [comment]
@vcunat maybe you can assist on this request

**Comment by vcunat** [comment]
Assist by pointing you to a PR?  #293704

**Comment by VeilSilence** [comment]
> Assist by pointing you to a PR? #293704

Oh.. my bad then, sorry for disturbing.
