### ISSUE TITLE
Remove llvm_37?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#30229]
In my usual frustration with keeping a bunch of historical versions of packages around, it appears that 3.7 is actually unused in nixpkgs right now. Any harm in removing it? I need to make slightly different changes to each of the LLVM versions for a recent Darwin stdenv change I made, and coupled with the long compile times, I'm very sad at having to fix each of these versions.

**Comment by copumpkin** [comment]
@LnL7 points out that if not for BAP, we could also get rid of 3.8. @maurer any thoughts on how hard moving BAP to another version would be?

**Comment by copumpkin** [comment]
Actually I was wrong about 3.7 being unused. @7c6f434c any thoughts on julia 0.4 depending on it? Do we need to keep the old version around?

**Comment by 7c6f434c** [comment]
I hope that Julia 0.4 could be dropped now.

I don't drop _immediately_ because breaking changes happen with every
release, then 0.5 temporarily stopped working because of complicated 
things related to LLVM that I don't understand, and then I forgot.

**Comment by dtzWill** [comment]
Or we could maintain all LLVM versions forever and ever?

...

If it weren't for long compile times I'd vote for trying to refactor these to ease maintenance pains but...

------------

Related: time to switch default to llvm5, maybe? :D

**Comment by vcunat** [comment]
The switch is mainly about checking each package separately, as they tend to break often.

**Comment by garrison** [comment]
julia 0.4 was removed in #44191.  But now, as of aaf62f7f6eb8c620cf538b40880e29a9695e33c5, ghc depends on llvm_37.

**Comment by JohnAZoidberg** [comment]
There doesn't seem to be any `llvm_37` anymore, right?

**Comment by vcunat** [comment]
Yes, done in #61508.
