### ISSUE TITLE
fwupdmgr refresh fails with errors

### ISSUE THREAD

**Issue by thblt** [NixOS/nixpkgs#30239]
## Issue description

`fwupdmgr`, installed from configuration.nix, doesn't refresh firmware list.

### Steps to reproduce

 - added `fwupd` to environment.systemPackages.  Doing only this resulted in a broken refresh:

```
$ fwupdmgr refresh 
Failed to download https://s3.amazonaws.com/lvfsbucket/downloads/firmware.xml.gz.asc: SSL handshake failed
```
 
 - I've updated my config, following advice given on #24376, to include glib-networking:

```
  environment.systemPackages = [ pkgs.fwupd pkgs.glib_networking ];
  systemd.packages = [ pkgs.fwupd ];

  environment.variables =
	{ GIO_EXTRA_MODULES = "${pkgs.glib_networking.out}/lib/gio/modules:${pkgs.gnome3.dconf}/lib/gio/modules";
          GSETTINGS_SCHEMA_DIR = "${pkgs.gsettings_desktop_schemas}/share/gsettings-schemas/gsettings-desktop-schemas-3.22.0/glib-2.0/schemas";
};
```

After this change, refresh now fails with a different error message:

```
$ fwupdmgr refresh
(fwupdmgr:3475): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

Full configuration can be found here: https://github.com/thblt/nixos-config/tree/fwupd

## Technical details

* System: 17.09.1535.1fdca25ee8 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1535.1fdca25ee8"
* Sandboxing enabled: no

**Comment by jtojnar** [comment]
fwupd did not even compile for me with sandboxing enabled. I did some changes in #30252 and now it fails for a different reason.

**Comment by jtojnar** [comment]
Is this still an issue?
