### ISSUE TITLE
Shadowsocks minimal config does not work

### ISSUE THREAD

**Issue by ostrolucky** [NixOS/nixpkgs#302326]
### Describe the bug
It looks like shadowsocks service integration is not working at the moment, even with minimal configuration. systemd service doesn't load.

### Steps To Reproduce
Apply this nixos config
```nix
services.shadowsocks.enable = true;
```
### Expected behavior
It looks like nixos will generate ExecStart similar like so `/nix/store/a1yyry8ifq6i86b8l4k62gk7syncf02y-shadowsocks-libev-3.3.5/bin/ss-server -c /nix/store/i74pqxw9wwicclbamqjw2l4w7l48rdpz-shadowsocks.json`

Running this will just get a help screen of ss-server (and same for systemd service, confirmed with journalctl)

Contents of /nix/store/i74pqxw9wwicclbamqjw2l4w7l48rdpz-shadowsocks.json is 
```json
{"fast_open":true,"method":"chacha20-ietf-poly1305","mode":"tcp_and_udp","server":["[::0]","0.0.0.0"],"server_port":8388,"user":"nobody"}
```

### Notify maintainers

@hmenke @abbradar 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.75, NixOS, 24.05 (Uakari), 24.05.20240403.fd281bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/n2g5cqwv8qf5p6vjxny6pg3blbdij12k-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oluceps** [comment]
This is caused by ss-libev's encryption method requiring a password but not set.

Refined the assertion in fix pr.
