### ISSUE TITLE
Packaging request: Etcher

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#30240]
This is just a packaging request for Etcher (https://etcher.io/). I might package it myself someday if I find the time and nobody else has done it.

**Comment by Shou** [comment]
Relevant https://github.com/NixOS/nixpkgs/issues/46382

**Comment by Shou** [comment]
PR https://github.com/NixOS/nixpkgs/pull/71404

**Comment by leo60228** [comment]
Etcher is on master, so this should be closed.

**Comment by jluttine** [comment]
Great! 🎉
