### ISSUE TITLE
Package request: ClickUp

### ISSUE THREAD

**Issue by nullishamy** [NixOS/nixpkgs#302414]
**Project description**
ClickUp is a project management solution, similar to Trello

**Metadata**

* homepage URL: https://clickup.com/
* source URL: N/A
* license: unfree
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by heisfer** [comment]
Seems like it's needs to be archived with web.archive.org (currently it's down). Download URL is: https://desktop.clickup.com/linux

**Comment by heisfer** [comment]
I also found this issue, but it has been a year #208733

**Comment by nullishamy** [comment]
Yeah I did give packaging it a shot but I could not find a reliable way to get it downloaded because there doesn't seem to be an exposed way to get a specific version?

**Comment by heisfer** [comment]
Yeah, I also checked PR URL, and it doesn't seem to give reliable version package. Even AUR has some problems. https://aur.archlinux.org/packages/clickup. That's why I suggested archive.org
