### ISSUE TITLE
Build failure: motif

### ISSUE THREAD

**Issue by cbarrett** [NixOS/nixpkgs#302449]
### Steps To Reproduce

1. build motif

### Build log

output of `nix log /nix/store/7m27hlg1wdymiqf22drbdwcqh7jk9j5d-motif-2.3.8.drv | sed  -e 's/\x1b\[[0-9;]*m//g'` (to remove color codes)
https://gist.github.com/cbarrett/302fb8409beaa8a36a8206ce9c77ba0a

### Additional context

I'm on Mac OS 12.7.2, with Xcode 14.2. FWIW my ultimate goal was to build snd, which is how I noticed motif failing.

### Notify maintainers

@alyssais @trofi

### Metadata

```console
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(cbarrett): `"darwin, nixpkgs-23.11-darwin"`
 - nixpkgs: `/Users/cbarrett/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
hydra agrees: https://hydra.nixos.org/job/nixpkgs/trunk/motif.x86_64-darwin/all

Looks like `motif` broke around Nov 2023. Possibly after `clang-16` update?

```
TextF.c:9352:13: error: call to undeclared function '_Xwcscpy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            wcscpy(wc, call_data->text->string.wide_char);
            ^
```

**Comment by trofi** [comment]
Similar `x96_64-linux` reproducer:

```
$ nix build --impure --expr 'with import ./. {}; motif.override { stdenv = clangStdenv; }' -L
...
motif> XpmWrFFrI.c:122:7: error: call to undeclared library function 'strncpy' with type 'char *(char *, const char *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
motif>   122 |             strncpy(new_name, name, sizeof(new_name));
motif>       |             ^
```

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/302635
