### ISSUE TITLE
avr/pgmspace.h: No such file or directory

### ISSUE THREAD

**Issue by abcdw** [NixOS/nixpkgs#30249]
## Issue description

After avrgcc libc binutils was splitted I can't build qmk firmware.
It hangs with following error:
```
In file included from keyboards/atreus/atreus.h:4:0,                                                                                                                                          
                 from keyboards/atreus/atreus.c:1:
./quantum/quantum.h:20:26: fatal error: avr/pgmspace.h: No such file or directory
compilation terminated.
```

### Steps to reproduce
git clone https://github.com/qmk/qmk_firmware.git
cd qmk_firmware
make atreus

## Technical details

* System: 17.09.1535.1fdca25ee8 (Hummingbird)                                                                                                                                                           
* Nix version: nix-env (Nix) 1.11.15                                                                                                                                                                         
* Nixpkgs version: "17.09.1535.1fdca25ee8"                                                                                                                                                                       
* Sandboxing enabled: false

**Comment by lluchs** [comment]
Try running  `nix-shell` in the qmk_firmware directory, I recently added a shell.nix to make the build work.

**Comment by abcdw** [comment]
It works but looks like a hack.

**Comment by equalunique** [comment]
I see shell.nix in the qmk_firmware folder, but even after running nix-shell, I still have the same problem.

**Comment by rdnetto** [comment]
I ran into the same problem, and was able to work around it by copying the approached used [here](https://github.com/qmk/qmk_firmware/blob/master/shell.nix).

I suspect this happens because `avr-gcc` is a direct symlink to the executable, instead of using the `cc-wrapper` script like `gcc` does. I had a go at getting avr-gcc to use it, but unfortunately I'm not familiar enough with Nix to get it working.
