### ISSUE TITLE
firefoxpwa : No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#302431]
### Describe the bug
After installing firefoxpwa and installing one PWA, when I try to launch it, I get this error : `No such file or directory (os error 2)`

### Steps To Reproduce
1. Install firefoxpwa this way in /etc/nixos/configuration.nix :
```
{ config, pkgs, lib, inputs, ... }:

{
  environment.systemPackages = with pkgs; [
    inputs.nixpkgs_unstable.legacyPackages."${pkgs.system}".firefoxpwa
  ];
  programs.firefox = {
    enable = true;
    package = pkgs.firefox;
    nativeMessagingHosts.packages = with pkgs; [
      browserpass
      inputs.nixpkgs_unstable.legacyPackages."${pkgs.system}".firefoxpwa
    ];
  };
```
2. Install firefox extension https://addons.mozilla.org/fr/firefox/addon/pwas-for-firefox/
3. be sure this folder exists : ~/.local/share/icons/hicolor/ to solve this issue : https://github.com/NixOS/nixpkgs/issues/301194
4. Install a PWA
5. Launch the PWA
6. Get the following error : `No such file or directory (os error 2)`

### Expected behavior
The PWA should launch

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/464782/b5f29a22-71ba-4f53-b9e2-8d6108b10b3a)

### Additional context
flake.nix file : 
```
{
  description = "Thatoo's flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.11";
    nixpkgs_unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = inputs@{ self, nixpkgs, ... }: {

    nixosConfigurations.default = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit inputs; };
      modules = [
        ./configuration.nix
      ];
    };
  };
}
```

### Notify maintainers

@camillemndn
@pasqui23

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.20240406.e38d7cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Thatoo** [comment]
In case it helps, here is the structure of the PWA profile : 

![image](https://github.com/NixOS/nixpkgs/assets/464782/7d1b9c67-3e70-49be-ac9c-cf442f4bb08e)

**Comment by filips123** [comment]
I think the error happens when the program tries to launch the runtime, but `firefox` binary doesn't exist. Please also check if `~/.local/share/firefoxpwa/runtime/` exists and if it contains Firefox installation, and if file permissions are set correctly (at least read and execute).

**Comment by Thatoo** [comment]
Here are files and permission of this folder : 
```
:~/.local/share/firefoxpwa/runtime$ ls -al
total 197012
drwxr-xr-x 8 thatoo users      4096  5 nov.  16:17 .
drwxr-xr-x 4 thatoo users      4096 12 avril 10:23 ..
-rw-r--r-- 1 thatoo users      1323  5 nov.  16:17 active-update.xml
-rw-r--r-- 1 thatoo users       899  6 juil.  2023 application.ini
-rw-r--r-- 1 thatoo users       649  3 avril 11:41 _autoconfig.cfg
drwxr-xr-x 4 thatoo users      4096  6 juil.  2023 browser
-rwxr-xr-x 1 thatoo users    257744  6 juil.  2023 crashreporter
-rw-r--r-- 1 thatoo users      3902  6 juil.  2023 crashreporter.ini
drwxr-xr-x 3 thatoo users      4096  6 juil.  2023 defaults
-rw-r--r-- 1 thatoo users       174  6 juil.  2023 dependentlibs.list
-rwxr-xr-x 1 thatoo users     14416  6 juil.  2023 firefox
-rwxr-xr-x 1 thatoo users    716216  6 juil.  2023 firefox-bin
-rw-r--r-- 1 thatoo users      1449  6 juil.  2023 firefox-bin.sig
-rw-r--r-- 1 thatoo users      1449  6 juil.  2023 firefox.sig
drwxr-xr-x 2 thatoo users      4096  6 juil.  2023 fonts
drwxr-xr-x 3 thatoo users      4096  6 juil.  2023 gmp-clearkey
drwxr-xr-x 2 thatoo users      4096  6 juil.  2023 icons
-rwxr-xr-x 1 thatoo users    821632  6 juil.  2023 libfreeblpriv3.so
-rwxr-xr-x 1 thatoo users    367872  6 juil.  2023 libipcclientcerts.so
-rwxr-xr-x 1 thatoo users     43200  6 juil.  2023 liblgpllibs.so
-rwxr-xr-x 1 thatoo users   3872568  6 juil.  2023 libmozavcodec.so
-rwxr-xr-x 1 thatoo users    240456  6 juil.  2023 libmozavutil.so
-rwxr-xr-x 1 thatoo users     14136  6 juil.  2023 libmozgtk.so
-rwxr-xr-x 1 thatoo users    117376  6 juil.  2023 libmozsandbox.so
-rwxr-xr-x 1 thatoo users   1220328  6 juil.  2023 libmozsqlite3.so
-rwxr-xr-x 1 thatoo users     18224  6 juil.  2023 libmozwayland.so
-rwxr-xr-x 1 thatoo users    223024  6 juil.  2023 libnspr4.so
-rwxr-xr-x 1 thatoo users    707032  6 juil.  2023 libnss3.so
-rwxr-xr-x 1 thatoo users    535608  6 juil.  2023 libnssckbi.so
-rwxr-xr-x 1 thatoo users    187416  6 juil.  2023 libnssutil3.so
-rwxr-xr-x 1 thatoo users     22656  6 juil.  2023 libplc4.so
-rwxr-xr-x 1 thatoo users     14376  6 juil.  2023 libplds4.so
-rwxr-xr-x 1 thatoo users    163456  6 juil.  2023 libsmime3.so
-rwxr-xr-x 1 thatoo users    321992  6 juil.  2023 libsoftokn3.so
-rwxr-xr-x 1 thatoo users    414344  6 juil.  2023 libssl3.so
-rwxr-xr-x 1 thatoo users 155436824  6 juil.  2023 libxul.so
-rw-r--r-- 1 thatoo users      1449  6 juil.  2023 libxul.so.sig
-rwxr-xr-x 1 thatoo users   1575568  6 juil.  2023 minidump-analyzer
-rw-r--r-- 1 thatoo users  32713148  6 juil.  2023 omni.ja
-rwxr-xr-x 1 thatoo users    773536  6 juil.  2023 pingsender
-rw-r--r-- 1 thatoo users       167  6 juil.  2023 platform.ini
-rwxr-xr-x 1 thatoo users    707936  6 juil.  2023 plugin-container
-rw-r--r-- 1 thatoo users      1449  6 juil.  2023 plugin-container.sig
-rw-r--r-- 1 thatoo users      1960  6 juil.  2023 precomplete
-rw-r--r-- 1 thatoo users         0  6 juil.  2023 removed-files
-rw-r--r-- 1 thatoo users       825  6 juil.  2023 Throbber-small.gif
-rwxr-xr-x 1 thatoo users     97576  6 juil.  2023 updater
-rw-r--r-- 1 thatoo users       638  6 juil.  2023 updater.ini
drwxr-xr-x 4 thatoo users      4096 16 oct.  10:31 updates
-rw-r--r-- 1 thatoo users       132  6 juil.  2023 update-settings.ini
-rw-r--r-- 1 thatoo users      4309 16 oct.  10:31 updates.xml
```

**Comment by filips123** [comment]
Permissions look fine, so I don't know what's the issue. Maybe the package maintainers can take a look at this. I will maybe take a look at this in the future, but I currently don't have time and any NixOS installation, so unfortunately it may take a while.

Also, a bit more details: Considering that "Launching the web app" gets printed, the launching should have been executed at least [until here](https://github.com/filips123/PWAsForFirefox/blob/0c9e7ac945364dd5b86bcb4f4d6d1d8212e13ca7/native/src/console/site.rs#L129). The [`site.launch`](https://github.com/filips123/PWAsForFirefox/blob/0c9e7ac945364dd5b86bcb4f4d6d1d8212e13ca7/native/src/components/site.rs#L177-L219) was probably also executed, as it doesn't contain any calls that could fail (except launching the runtime at the end). So, the only place where this error could happen is [`runtime.run`](https://github.com/filips123/PWAsForFirefox/blob/0c9e7ac945364dd5b86bcb4f4d6d1d8212e13ca7/native/src/components/runtime.rs#L371-L388).

**Comment by pasqui23** [comment]
Did you try to install the latest firefoxpwa from nixos-unstable and check if a pwa does run?

**Comment by Thatoo** [comment]
Indeed as there is no firefoxpwa for 23.11 stable.

**Comment by pasqui23** [comment]
Have you tried deleting `.local/share/firefoxpwa` and then adding back manually a pwa?

**Comment by Thatoo** [comment]
I didn't and when I tried, it solved the issue, thanks!
