### ISSUE TITLE
Update request: gnomeExtentions.caffeine 52 → 53

### ISSUE THREAD

**Issue by wrenix** [NixOS/nixpkgs#302516]
- Package name:
- Latest released version:

- Current version on the unstable channel:
- Current version on the stable/release channel:

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@emanueleperuffo 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Done. As part of GNOME 46 update. [ref](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=gnomeExtensions.caffeine)
