### ISSUE TITLE
Update request: vercel-pkg 33.6.1 → 33.7.0

### ISSUE THREAD

**Issue by koalazub** [NixOS/nixpkgs#302547]
- Package name: **nodePackages_latest.vercel**
- Latest released version: **33.7.0**

- Current version on the unstable channel: **33.6.1**
- Current version on the stable/release channel: **32.5.3**

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

Can't find a maintainer.

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> Can't find a maintainer.

https://github.com/NixOS/nixpkgs/blob/6dc6e56ed4781661407e0536ae385cc2919049ca/pkgs/by-name/ve/vercel-pkg/package.nix#L73

**Comment by donovanglover** [comment]
FWIW [vercel](https://github.com/vercel/vercel/tree/main/packages/cli) and vercel's [pkg](https://github.com/vercel/pkg) are 2 different programs

**Comment by dotlambda** [comment]
Since @koalazub referred to https://github.com/NixOS/nixpkgs/pull/259098 I can only assume they meant vercel-pkg.

**Comment by dotlambda** [comment]
Actually that would be inconsistent with the version they specified. I'm closing this and hope that a less ambiguous issue can be opened. Please don't ping me in that issue since I'm not interested in working on JS bullshit.
