### ISSUE TITLE
`ucc` build failure on x86_64-linux as of `0c165dec`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#302699]
## Issue description
Build of `ucc` failed on x86_64-linux as of 0c165dec843e9aa71379c4928df273b5ea8b7df7. This is currently breaking `python3Packages.tensorflow`.

```
error: builder for '/nix/store/d6490clpmbd84byf337116b1cjz2x26s-ucc-1.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > checking for cuda.h... yes
       > checking for cuda_runtime.h... yes
       > checking for cuDeviceGetUuid in -lcuda... yes
       > checking for cudaGetDeviceCount in -lcudart... yes
       > checking for nvml.h... no
       > configure: WARNING: nvml header not found. Install appropriate cuda-nvml-devel package
       > checking size of cuFloatComplex... 8
       > checking size of cuDoubleComplex... 16
       > checking for nvcc... notfound
       > configure: error: CUDA support is requested but cuda packages cannot be found
       For full logs, run 'nix log /nix/store/d6490clpmbd84byf337116b1cjz2x26s-ucc-1.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/148csz8x7fzz6yak8ix00b3zlw82b6wf-openmpi-4.1.6.drv' failed to build
error: 1 dependencies of derivation '/nix/store/whcp9xwi5cn074vdawkzyh82a8r7l5sn-tensorflow-gpu-2.13.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r420hwm7lhvr5d0gss808mjqhwmh74b2-python3.11-tensorflow-gpu-2.13.0.drv' failed to build
```

[full build log](https://github.com/samuela/nixpkgs-upkeep/actions/runs/8608260300)

python3Packages.tensorflow maintainers cc: @abbradar
ucc maintainers cc: @markuskowa
Other cc: n/a

### Steps to reproduce
1. Checkout nixpkgs at commit 0c165dec843e9aa71379c4928df273b5ea8b7df7
2. Run `nix-build -A ucc`

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-1017-azure, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - nixpkgs: `/nix/store/hp6fa6fp7z8q9mc95yg97qcqnrvvws2k-source`
```

Contents of `~/.config/nixpkgs/config.nix`:
```
{ allowUnfree = true; cudaSupport = true; cudaCapabilities = ["8.0"]; }
```

## Misc.
This issue was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/8608260300) that created this issue.
- Internal tags: -5465157908829612830 8331235628389809469

**Comment by markuskowa** [comment]
I can not reproduce the build failure on the current nixpkgs master (9733446b77f74f0d616d95e99872423322f97b0f).
```
nix-build -A ucc --arg config '{cudaSupport=true;  cudaCapabilities = ["8.0"];}'
```
Succeeds and produces: /nix/store/4hzqx98pgg160a3jn4mxwkndyvx4czix-ucc-1.2.0
