### ISSUE TITLE
Update request: azure-functions-core-tools 4.0.5455 → 4.0.5611

### ISSUE THREAD

**Issue by kumkee** [NixOS/nixpkgs#302640]
- Package name: azure-functions-core-tools
- Latest released version: 4.0.5611

- Current version on the unstable channel:  4.0.5455
- Current version on the stable/release channel: 4.0.5348

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Detegr @mdarocha - I've communicated with @mdarocha via email.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/361077
