### ISSUE TITLE
Enabling IBus doesn't put ibus-setup in $PATH

### ISSUE THREAD

**Issue by hettily** [NixOS/nixpkgs#30265]
## Issue description

On a system built from the `nixpkgs-unstable` channel, setting the following in `configuration.nix`:

```
i18n.inputMethod = {
    enabled = "ibus";
    ibus.engines = with ibus.engines; [ anthy ];
};
```

Does not put the `ibus-setup` program in my $PATH. This program is generally how you configure IBus, so it being missing is a problem. It causes the "Preferences" button in the IBus systray right-click menu to do nothing.

### Steps to reproduce

- Enable IBus as in the example above
- Log out and back in, or maybe reboot completely to be sure
- Run `ibus-daemon -drx` manually (it doesn't auto-start for some reason)
- Right-click the tray icon and click "Preferences", confirming it does nothing
- Try running `ibus-setup` from a terminal to confirm `ibus-setup` isn't in your $PATH

## Technical details

* System: 18.03pre117347.66f8512e4f (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre117347.66f8512e4f"
* Sandboxing enabled: false

**Comment by globin** [comment]
cc @edolstra, who changed this

**Comment by edolstra** [comment]
`ibus-setup` causes a runtime dependency on `python3.buildEnv`, which is not acceptable for closure size reasons (it pulls in a lot of .dev paths).

I personally don't care about ibus (don't even know what it does), but `plasma-desktop` pulls it in. Maybe that dependency could be disabled by default.

**Comment by wtok** [comment]
To be clear, IBus is a platform for input methods for non-English languages like Chinese, Japanese, etc. It allows users to type those languages using a standard English keyboard. 

Obviously it can't know which language you will want to use out-of-the-box, so users need to configure it to their liking, and ibus-setup is how you do that. It doesn't have an editable config file, as far as I can tell.

So something will have to be figured out here -- IBus without ibus-setup is essentially useless, even if it does build. Currently, it's a digital paperweight.

**Comment by unode** [comment]
I was going to report the issue with the preferences menu not doing anything and bumped into this.

Similarly to @wtok I also use it to input non-latin languages. Some users report successful usage #11558 so was this a recent regression?

With regards to the point about closure size being too large, are there any viable solution/workaround?

**Comment by cstrahan** [comment]
I've also run into this problem (though from slightly different perspective), as described here: https://github.com/NixOS/nixpkgs/issues/31454

**Comment by cstrahan** [comment]
Oh, I see @unode describes exactly what I reported in #31454.

> With regards to the point about closure size being too large, are there any viable solution/workaround?

Conceivably, we could patch `ibus` so that we can specify some other path via an environment variable (e.g. `$NIX_IBUS_SETUP_PATH`), and then the NixOS module could properly set up that env var. That would pull Python out of the `ibus` closure, as desired.

@edolstra How does that sound?

**Comment by ChengCat** [comment]
A proper fix should be disabling ibus in plasma-desktop by default. ibus and ibus-setup work together, separating them seems a temporary hack to me.

**Comment by evanjs** [comment]
I can access `ibus-setup` just fine on my setup after enabling IBus.
Might #31094 have fixed this?

**Comment by hettily** [comment]
Quite possible -- this is a really old issue. I can't test to confirm, so if you think it's resolved, I'll call it resolved. Thanks!
