### ISSUE TITLE
xcrun from xcbuild doesn't -find things

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#30269]
@matthewbauer put together a nice Nix xcodebuild SDK but it seems like `xcrun` hasn't learned about it:

From a fairly recent commit:

```
$ nix-shell -p xcbuild
[nix-shell:~]$ xcrun -find cc
error: unable to find sdk: ''
```

Similar with the various other subcommands like `--show-sdk-path`. @matthewbauer any idea what might be wrong?

**Comment by matthewbauer** [comment]
So if you try setting ```SDKROOT=macosx10.10``` before running that might work. If that works I believe we can wrap it into xcrun.

**Comment by copumpkin** [comment]
Magic! That did it!
