### ISSUE TITLE
Package request: toml-cli

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#302664]
**Project description**

simple command line program to edit toml files

**Metadata**

* homepage URL: https://github.com/gnprice/toml-cli
* license: mit
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lolbinarycat** [comment]
after reading a bit more, this seems quite bare-bones.  i'll settle for jq+toml2json.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/271082
