### ISSUE TITLE
Update request: pijul 1.0.0-beta.8 1.0.0-beta.9

### ISSUE THREAD

**Issue by korrat** [NixOS/nixpkgs#302626]
- Package name: pijul
- Latest released version: 1.0.0-beta.9
- Current version on the unstable channel: 1.0.0-beta.8
- Current version on the stable/release channel: 1.0.0-beta.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

- @FlorentBecker 
- @dywedir
- @fabianhjr 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Closed per #302637
