### ISSUE TITLE
dbus-broker fails to start

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#302771]
### Describe the bug

Presumably a result of https://github.com/NixOS/nixpkgs/pull/299812

I noticed that one of my servers that has `system.autoUpgrade.enable = true;` failed to perform its update/switch.

I have rolled back to the previous working configuration and followed the instructions in https://discourse.nixos.org/t/would-it-be-feasible-to-make-dbus-broker-the-default-dbus-implementation/41760/20 to not switch the live system, but after boot the new `dbus-broker` service fails anyway:

```
$ sudo systemctl status --failed
× dbus-broker.service - D-Bus System Message Bus
     Loaded: loaded (/etc/systemd/system/dbus-broker.service; enabled; preset: enabled)
    Drop-In: /nix/store/9z7ykk0lf37nzy0l1qdaqib1dpxp6j2f-system-units/dbus-broker.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Wed 2023-12-06 21:38:40 CET; 4 months 2 days ago
   Duration: 8ms
TriggeredBy: × dbus.socket
       Docs: man:dbus-broker-launch(1)
    Process: 1349 ExecStart=/nix/store/xp5gvw55ga4cs2vkj45vlyks75ppdbkl-dbus-broker-35/bin/dbus-broker-launch --scope system --audit (code=exited, status=1/FAILURE)
   Main PID: 1349 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 35ms

Notice: journal has been rotated since unit was started, output may be incomplete.

× dbus.socket - D-Bus System Message Bus Socket
     Loaded: loaded (/etc/systemd/system/dbus.socket; linked; preset: enabled)
     Active: failed (Result: service-start-limit-hit) since Wed 2023-12-06 21:38:40 CET; 4 months 2 days ago
   Duration: 1.847s
   Triggers: ● dbus-broker.service
     Listen: /run/dbus/system_bus_socket (Stream)

Notice: journal has been rotated since unit was started, output may be incomplete.
```

While in this state, I cannot switch configurations (and do some other things) because of `Failed to connect to bus: Connection refused`.

An obvious workaround is to set `services.dbus.implementation = "dbus";` but I'd rather not have to confront this problem again in the future when I've forgotten all about it.

Curiously, another server has updated just fine. Main differences I can think of (although I can't think how they relate to dbus) is that the working one is `x86_64-linux`, while the broken one is a Raspberry Pi (`aarch64-linux`), and that the broken one uses an ephemeral root file system.

### Notify maintainers

@LDprg @peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
Could you restart your system?

**Comment by SFrijters** [comment]
These errors persist after boot (and `sudo reboot` itself also complains about dbus).

**Comment by LDprg** [comment]
Can someone test if dbus broker runs correctly on a Raspberry or any other aarch64 device?

@SFrijters With "ephemeral root file system" do you mean tmpfs Filesystem? Maybe mounting dbus and dbus-broker relevant paths to a persistent Filesystem could help.

**Comment by SFrijters** [comment]
My `/` filesystem is a ZFS filesystem that gets reset to a blank snapshot at boot.
However, I've realised that my laptop has also gotten this dbus change (without me noticing - so that's good!) and it uses the same ZFS setup, so that is unlikely to be the cause. It is `x86_64-linux` though - unfortunately I don't have a second `aarch64-linux` device to test.

How do I check if I have dbus enabled in stage 1? I have not enabled it consciously at least.

**Comment by LDprg** [comment]
@SFrijters For dbus in stage 1 there is an option 'boot.initrd.systemd.dbus.enable'.

**Comment by SFrijters** [comment]
Ah, right. `boot.initrd.systemd.dbus.enable` is `false` by default, and I do not set it on any of my systems.

**Comment by peterhoeg** [comment]
We need a better solution for this and we're too close to release. Let's revert the switch.

**Comment by LDprg** [comment]
@peterhoeg you are probably right (I would only revert the commit changing the default not the one adding dbus tools to dbus broker). Or we just restict it to x64 only, since it seems to be a arm problem only.

I wasn't able to reproduce on any x64 device (tried a bunch of different devices). However I don't have an arm device for testing.

@SFrijters have you any dbus broker or related error logs. It seems strange to me that dbus broker wouldn't only on arm devices without any logs.

**Comment by Aleksanaa** [comment]
I suspect it's problematic to switch from dbus to dbus-broker, but I've not tested it.

**Comment by SFrijters** [comment]
@LDprg I don't have better logs at this time. https://github.com/NixOS/nixpkgs/pull/303639 (v36) promises better error messages so that may shed some light if that gets merged. Unfortunately my Raspberry Pi is normally headless (and a 'critical' part of my LAN - DNS server and such) so fiddling with things that involve rebooting and selecting boot generations is a pain.

**Comment by wegank** [comment]
> Can someone test if dbus broker runs correctly on a Raspberry or any other aarch64 device?

I wasn't able to reproduce the failure on any aarch64 device, either. My Raspberry Pi and my MacBook Air M1 both work fine with dbus-broker.

**Comment by SFrijters** [comment]
I rebuilt my system with v36 cherry picked on top of its previous configuration and I have the same issues and lack of information.
During boot I see a couple of:

```
         Starting D-Bus System Message Bus...
[  OK  ] Started D-Bus System Message Bus.
```
(interleaved with other messages), but then

```
         Starting D-Bus System Message Bus...
[FAILED] Failed to start D-Bus System Message Bus.
See `systemctl status dbus-broker.service` for details.
```

After boot:
```
$ sudo systemctl status dbus-broker.service
× dbus-broker.service - D-Bus System Message Bus
     Loaded: loaded (/etc/systemd/system/dbus-broker.service; enabled; preset: enabled)
    Drop-In: /nix/store/a4imvc1007296c6df1jzdi24nmmwmvpg-system-units/dbus-broker.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Wed 2023-12-06 21:38:38 CET; 4 months 13 days ago
   Duration: 19ms
TriggeredBy: × dbus.socket
       Docs: man:dbus-broker-launch(1)
    Process: 1345 ExecStart=/nix/store/p6simchmdj87akn18y6b8wqqz0ysm0bk-dbus-broker-36/bin/dbus-broker-launch --scope system --audit (code=exited, status=1/FAILURE)
   Main PID: 1345 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 43ms

Notice: journal has been rotated since unit was started, output may be incomplete.

$ sudo systemctl status dbus.socket
× dbus.socket - D-Bus System Message Bus Socket
     Loaded: loaded (/etc/systemd/system/dbus.socket; linked; preset: enabled)
     Active: failed (Result: service-start-limit-hit) since Wed 2023-12-06 21:38:38 CET; 4 months 13 days ago
   Duration: 1.782s
   Triggers: ● dbus-broker.service
     Listen: /run/dbus/system_bus_socket (Stream)

Notice: journal has been rotated since unit was started, output may be incomplete.

# I don't know if calling this directly makes sense in any way
$ sudo /nix/store/p6simchmdj87akn18y6b8wqqz0ysm0bk-dbus-broker-36/bin/dbus-broker-launch --scope system --audit
No listener socket inherited
```

The notice and old timestamps are probably related to my "[Erase Your Darlings](https://grahamc.com/blog/erase-your-darlings/)" setup somehow?

Since @wegank has confirmed this is not a general `aarch64` issue I'm willing to accept this is somehow a problem related to my specific setup and I can just using regular old `dbus` for now.

**Comment by SuperSandro2000** [comment]
> The notice and old timestamps are probably related to my "Erase Your Darlings" setup somehow?

If that is really the case, I wouldn't put the burdem to fix this onto NixOS. That setup is highly experimental and known to be easily broken.

Do we have some logs? A minimal reproducer? So far no one could reproduce your issue.

**Comment by SFrijters** [comment]
Unfortunately it's very inconvenient for me to break my Pi on purpose for debugging for reasons metioned above and I've given all the information I can (I've followed the instructions in the logs and got nowhere). The issue is probably indeed to specific to my setup.

Also, I've noticed that `dbus-broker` was spamming the logs on my other systems with warnings as well, and I don't like upstream's attitude towards breaking user's systems, so I've gone back to `dbus` on all my systems in any case.

**Comment by SFrijters** [comment]
> @SFrijters the warnings are probably related to #303078. Those can be safely ignored since the underlying issue (duplicate names) still persists on dbus. Dbus however doesn't log any duplicates and dbus-broker does. Dbus-broker is generally more verbose than dbus.

Yet sadly not verbose enough to tell me about actual errors. :)

At the moment maintaining my systems is not a hobby, and I just want them to work with a minimum of fuss. I was hoping there was something more obviously wrong that could be reproduced by others (like the `aarch64` version being buggy), but as it is I'd rather just consistently keep the old implementation that has never caused an issue for me across all my systems rather than dealing with intractable problems for some alleged benefits.
