### ISSUE TITLE
Steam: attempt to call something which is not a function but a list

### ISSUE THREAD

**Issue by YaroKasear** [NixOS/nixpkgs#302851]
### Describe the bug
Attempted an update from nixpkgs-unsable, and got a failure.

```
error:
       … while calling the 'head' builtin

         at /nix/store/m29q5yy2lpcinxxrlvggcczadz4agw5l-source/lib/attrsets.nix:1541:11:

         1540|         || pred here (elemAt values 1) (head values) then
         1541|           head values
             |           ^
         1542|         else

       … while evaluating the attribute 'value'

         at /nix/store/m29q5yy2lpcinxxrlvggcczadz4agw5l-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attempt to call something which is not a function but a list

       at /nix/store/m29q5yy2lpcinxxrlvggcczadz4agw5l-source/pkgs/games/steam/fhsenv.nix:47:8:

           46|     sqlite
           47|   ] ++ extraPkgs pkgs;
             |        ^
           48|
```

I didn't change my flake regarding Steam at all, so I can only conclude something in nixpkgs changed to cause this error.

### Steps To Reproduce
1. Use nixpkgs-unstable as a flake input.
2. Enable Steam
3. Try to build a configuration with Steam module enabled.

### Expected behavior
I expected that my latest update would build and deploy properly.

### Notify maintainers

@jagajaga
@jonringer

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240407.600b15a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/z9yf6zqvqv1rb2mbhxlb6i24j2is6bj5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
This has been fixed in current `master` via #302748.
