### ISSUE TITLE
Build failure: pkgsCross.aarch64-multiplatform.python311Packages.tpm2-pytss

### ISSUE THREAD

**Issue by stv0g** [NixOS/nixpkgs#302878]
Cross builds of `tpm-pytss` fail due to a direct invocation of `cpp`, the C preprocessor:

```
RuntimeError: Unable to invoke 'cpp'.  Make sure its path was passed correctly
Original error: [Errno 2] No such file or directory: 'cpp
```

### Steps To Reproduce

```
nix build flake:nixpkgs\#legacyPackages.x86_64-linux.pkgsCross.aarch64-multiplatform.python311Packages.tpm2-pytss
```

### Build log

[tpm2-pytss.log](https://github.com/NixOS/nixpkgs/files/14921596/tpm2-pytss.log)

### Notify maintainers

@baloo

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.18, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by METII99** [comment]
Getting same bug with M2Crypto Package.
