### ISSUE TITLE
Package request: libfiveStudio

### ISSUE THREAD

**Issue by khionu** [NixOS/nixpkgs#302906]
**Project description**

libfive is a CAD a la Code library, and they have a GUI editor available called Studio.

**Metadata**

* homepage URL: https://libfive.com/studio/
* source URL: https://github.com/libfive/libfive?tab=readme-ov-file#compiling-from-source
* license: GPL2
  - https://github.com/libfive/libfive?tab=readme-ov-file#license
* platforms: linux, and darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
The build fails while running some tests. If you would like you can check with upstream and see if the can help you debug the issues.
here is the derivation so far:
```nix
{ lib
, fetchFromGitHub
, stdenv

, boost
, cmake
, eigen
, pkg-config
, libpng

, guile
, python3
, qt5
}:
stdenv.mkDerivation (finalAttrs: {
  pname = "libfiveStudio";
  version = "248c15c57abd2b1b9ea0e05d0a40f579d225f00f";
  src = fetchFromGitHub {
    owner = "libfive";
    repo = "libfive";
    rev = "${finalAttrs.version}";
    hash = "sha256-WIw2n59sRIb77GEcVzq8TtTL69qlQLuX0/FqulLnI0E=";
  };

  doCheck = false;
  nativeBuildInputs = [
    boost
    cmake
    eigen
    pkg-config
    qt5.wrapQtAppsHook
  ];

  buildInputs = [
    guile
    python3
    qt5.qtbase
    libpng
  ];
})
```

**Comment by khionu** [comment]
Much appreciated, I'll see what they say!

**Comment by Wulfsta** [comment]
This has been packaged for years? See [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libfive/default.nix). Please reopen if I have missed something.

**Comment by khionu** [comment]
Sorry for the long delay. It appears to be packaged as a python library, not the LibFive Studio application. I did search again just now and found the package `ao`, which appears to be LibFive + LibFive Studio? Not sure why it's called `ao`, though.

**Comment by Wulfsta** [comment]
It is packaged as both a python library and `libfive-studio`. The library used to be called `ao` before it was renamed.

**Comment by khionu** [comment]
Maybe it should be renamed now?

**Comment by Wulfsta** [comment]
> Maybe it should be renamed now?

It was "renamed" in [this commit](https://github.com/NixOS/nixpkgs/commit/3e6d7a2329974ce63c4b6ee31c30ed576d94015b). The proper way to do this nowadays is to add it into `pkgs/top-level/aliases.nix`. See #347997.
