### ISSUE TITLE
Flash Player Pepper Api Updated

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#30308]
## Issue description

Currently, Flash Player with/for Pepper Api can't be downloaded anymore as it points to an old version that seems to have been removed from Adobe server.

### Steps to reproduce

Use

```
    nixpkgs.config.chromium = {
        enablePepperFlash = true; # Chromium removed support for Mozilla (NPAPI) plugins so Adobe Flash no longer works 
    };
```
In your configuration.nix for getting the flash player. It will try to download it from

https://fpdownload.adobe.com/pub/flashplayer/pdc/27.0.0.130/flash_player_ppapi_linux.x86_64.tar.gz

which results in a 404.

New version is available at

https://fpdownload.adobe.com/pub/flashplayer/pdc/27.0.0.159/flash_player_ppapi_linux.x86_64.tar.gz

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre117163.d9091f8181 (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre117583.d9a03761de"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`

**Comment by peterhoeg** [comment]
Thanks for reporting this. This is a great example of what will become a very straight forward PR. Do you feel like giving that a go?

**Comment by sjau** [comment]
I leave that to the pros :)

**Comment by peterhoeg** [comment]
It has already hit master in 628c039326 so I'm closing this.

**Comment by qrilka** [comment]
sorry for maybe dumb question but why do my nix still tries to get old flash player archive if update is already in the master and I use nixos-unstable? Do I need to use some special magic here?

**Comment by sjau** [comment]
Unstable got updated only 5h ago -https://howoldis.herokuapp.com

It didn't get updated for more than 11 days I think. So if rebuild now with --update it should work.

**Comment by qrilka** [comment]
oh, I didn't know about that site, thanks @sjau 
But I run it just minutes ago...
I guess you meant `--upgrade` as there seem to be no `--update` option for `nixos-rebuild`? I run `sudo nixos-rebuild switch --upgrade` and it fails because of 404

**Comment by sjau** [comment]
yeah, meant --upgrade

No idea why it fails... does it still point to old url?

**Comment by qrilka** [comment]
yep, it does

**Comment by sjau** [comment]
hmmm, don't know then...
