### ISSUE TITLE
Package request: Stalwart

### ISSUE THREAD

**Issue by autoblikk** [NixOS/nixpkgs#303014]
**Project description**

Stalwart is a modern, efficient mail server built for scale that's easy to self-host. It is written in Rust and is the solution to making self-hosting your own mail server easy. It supports JMAP.

**Metadata**

* homepage URL: https://stalw.art
* source URL: https://github.com/stalwartlabs/mail-server and https://github.com/stalwartlabs/webadmin
* license: GPLv3
* platforms: Linux, MacOS, Windows

**Comment by autoblikk** [comment]
Hopefully this can also be integrated as `services.stalwart.enable = true` with Nginx for super simple mail server. It supports multiple backends too, such as Sqlite and RocksDB.

**Comment by jonocodes** [comment]
Stalwart service already exists
https://mynixos.com/search?q=stalwart

Its just on 0.6.0 in nix unstable, but the latest upstream version is 0.7.0 with webadmin. That should be updated.

**Comment by jlesquembre** [comment]
Closing, we already have it
