### ISSUE TITLE
Update request: python3 3.11.8 -> 3.11.9, python312 3.12.2 -> 3.12.3

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#303020]
- Package name: python3, python312
- Latest released version: 3.11.9, 3.12.3

- Current version on the unstable channel: 3.11.8, 3.12.2
- Current version on the stable/release channel: 3.11.8, 3.12.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---
@FRidh 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/303057

**Comment by natsukium** [comment]
> - [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

You could have found the PR for 3.11.9. https://github.com/NixOS/nixpkgs/pull/301257

**Comment by MisileLab** [comment]
> > - [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
> 
> You could have found the PR for 3.11.9. https://github.com/NixOS/nixpkgs/pull/301257

I assume python3 and python3.12 updated at same time because [previous pr](https://github.com/nixos/nixpkgs/pull/287090) updated at same time.
Thank you for your message, I'll check two time when I create issue.

**Comment by MisileLab** [comment]
#303057 fixed issue
