### ISSUE TITLE
Build failure: gnupg 2.4.5 AArch64 on x86_64 cross-compilation

### ISSUE THREAD

**Issue by matdibu** [NixOS/nixpkgs#303090]
### Steps To Reproduce

1. build an AArch64 installer ISO on a x86_64 host
2. observe `gnupg-aarch64-unknown-linux-gnu-2.4.5.drv` failing

### Build log

```
configure:
***
*** It is now required to build with support for the
*** New Portable Threads Library (nPth). Please install this
*** library first.  The library is for example available at
***   https://gnupg.org/ftp/gcrypt/npth/
*** (at least version 1.2 (API 1) is required).
***
configure: error: 
***
*** Required libraries not found. Please consult the above messages
*** and install them before running configure again.
***
```

### Additional context

The ISO I'm trying to build is **_not_** the standard AArch64 ISO, part of the config can be viewed [here](https://codeberg.org/mateidibu/nix-config/src/commit/1c245b8dd6081e03b124f7bc06cbb3278b4b8827/hosts/nix-iso/default.nix), with additional changes coming from modules that are enabled by default.

The build fails on `nixos-unstable` and `nixos-unstable-small`, but works on `nixos-23.05`.

### Notify maintainers

@fpletz
@vrthra

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240409.e160d43`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - nixpkgs: `/nix/store/8bbjv4vhmhfr5hliiky4n8aq8sdzwpdb-source`
```

**Comment by matdibu** [comment]
ah I'm sorry, I didn't look for closed PR's

**Comment by tpwrules** [comment]
The fix has made it to the latest channel releases.
