### ISSUE TITLE
Enabling `hardware.sane.dsseries.enable` prompts for wrong package name for unfree predicate

### ISSUE THREAD

**Issue by TheNeikos** [NixOS/nixpkgs#303116]
### Describe the bug
Enabling `hardware.sane.dsseries.enable` without allowing unfree packages causes the following error:

```
error:
       … while evaluating attribute 'nodes'

         at «string»:4:25:

            3|                       (deploy // {
            4|                         nodes = {
             |                         ^
            5|                           inherit (deploy.nodes) "host";

       … while evaluating attribute 'host'

         at «string»:5:49:

            4|                         nodes = {
            5|                           inherit (deploy.nodes) "host";
             |                                                 ^
            6|                         };

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘libsane-dsseries-1.0.5-1’ in /nix/store/450afzqlzzgw6wnyc3dwysf3i5yxyqkr-source/pkgs/applications/graphics/sane/backends/dsseries/default.nix:47 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "libsane-dsseries-1.0.5-1"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
```

The suggested fix for `allowUnfreePredicate` is wrong as it contains the version, where as only the package name should be used.

### Steps To Reproduce
1. Set the option
2. Build it
3. See the error

### Expected behavior
The error message should not contain the version

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240408.4cba8b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(neikos): `"home-manager"`
 - channels(root): `"nixos-21.11.337114.9887f024766"`
 - nixpkgs: `/nix/store/450afzqlzzgw6wnyc3dwysf3i5yxyqkr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by callahad** [comment]
I think this is a broader issue with all unfree packages; you can see the same thing if you try to run `nix shell nixpkgs#obsidian`

It looks like the error message prints out the `name` attribute of the derivation, which is effectively `${pname}-${version}`, but `lib.getName` only returns the `${pname}` part.

**Comment by callahad** [comment]
The fix would be in [pkgs/stdenv/generic/check-meta.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/check-meta.nix).

It looks like the error message for `permittedInsecurePackages` is likely to be similarly incorrect.

The locally defined `getName` function returns, in order of preference: `${pkg.name}`, then `${pkg.pname}-${pkg.version}`:

https://github.com/NixOS/nixpkgs/blob/11486e15b5ae0e89b12efce6214fd4602ea4de49/pkgs/stdenv/generic/check-meta.nix#L49

But `lib.getName` functions differently, preferring `${pkg.pname}` and falling back to `builtins.parseDrvName` which itself extracts the equivalent of `pname`

https://github.com/NixOS/nixpkgs/blob/e53c564e26256144addbb7ee40d2b695e1e4a8eb/lib/strings.nix#L729-L734

**Comment by callahad** [comment]
Hm. `allowInsecureDefaultPredicate` uses the local `getName`, so `config.permittedInsecurePackages` _should_ include the version, and the error message there is correct.

I suspect it'd be enough to change templated `remediate_predicate` string as:

```patch
diff --git a/pkgs/stdenv/generic/check-meta.nix b/pkgs/stdenv/generic/check-meta.nix
index bcb2ca249..a61f3e1ae 100644
--- a/pkgs/stdenv/generic/check-meta.nix
+++ b/pkgs/stdenv/generic/check-meta.nix
@@ -189,7 +189,7 @@ let
 
       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.${predicateConfigAttr} = pkg: builtins.elem (lib.getName pkg) [
-            "${getName attrs}"
+            "${lib.getName attrs}"
           ];
         }
     '';
```

**Comment by TheNeikos** [comment]
For insecure packages, the version is correct, and should also stay there since only _some_ are insecure (hopefully). But for unfree packages, they rarely change between versions. So that seems fair to not have to update the version on every upgrade.

**Comment by callahad** [comment]
Yeah, that seems right. PR incoming.
