### ISSUE TITLE
stalwart-mail module needs a rewrite for version 0.7.0 

### ISSUE THREAD

**Issue by makuru-dd** [NixOS/nixpkgs#303156]
### Describe the bug

 The new version of stalwart mail (0.7.0), has changed a lot and the module needs a rewrite for a while now, for example: I have forked nixpkgs, to remove the standard settings, to allow me to make a more complex setting.

 issues I see.
 - No way to disable the default options, in: `services.stalwart-mail.settings`.
 - WebUI is not currently supported
 - The `stalwart-mail` package imports the entire `cargo.lock`.

### Notify maintainers
@happysalada  

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
If you want to make a contribution, even a small one, im happy to help you get it merged !

**Comment by happysalada** [comment]
That would be amazing !
There is an open pr from the bot for the 0.7 upgrade, you can take over that one or make the update in a new pr.
Thank you !

**Comment by onny** [comment]
Not yet entirely fixed, module and test need some work to support >= 0.7.0

**Comment by makuru-dd** [comment]
> By the way, since migrating to stalwart >= 0.7 requires some manual migration in any case, would it be worth setting the default database type to rocksdb instead of sqlite in the module?

In my opinion yes, for the love of Linux or just make it undefined.
@pacien, Do you have a git repo, where I can track your progress and when I have time, give improvements?
