### ISSUE TITLE
Build failure: electron-unwrapped-28.2.10

### ISSUE THREAD

**Issue by AMS21** [NixOS/nixpkgs#303189]
### Steps To Reproduce

1. build electron-unwrapped-28.2.10

### Build log

https://gist.github.com/AMS21/d1d170b31e53e63a4f6a66beb0cae36f
```
log here if short otherwise a link to a gist
```

### Additional context

Failed during configuration builds of mattermost

### Notify maintainers

@magneticflux-
@teutat3s

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/j10523yhkcc34478azkgcl70yzcx6j2j-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NekoNoor** [comment]
i have this issue as well, any reason you marked it as completed?

**Comment by magneticflux-** [comment]
@NekoNoor Because I already fixed it yesterday, it just takes a _loooooooong_ time to rebuild and test everything from scratch. You can check where the fix has landed here: https://nixpk.gs/pr-tracker.html?pr=302544
