### ISSUE TITLE
Pulsar : could git-remote-https be broken?

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#303142]
### Describe the bug
Install pulsar 109.0 on nixos stable

### Steps To Reproduce
1. Install pulsar 109.0 on nixos stable
2. Connect to github
3. Fetch
4. error fatal : 'remote-https' seem to be a git command, but could not be executed. could git-remote-https be broken?

### Expected behavior
Be able to fetch pull and push

### Notify maintainers
@COLAMAroro 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.20240406.e38d7cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by COLAMAroro** [comment]
I've been able to reproduce the issue and find the root cause.

`git-remote-https`is a independent binary of just `git`. Looking at how to fix this proprely (should not be that complicated). Not sure I can easily backport it to 23.11 tho

**Comment by COLAMAroro** [comment]
Well, it wasn't as hard as I thought it was going to be.
Probably not going to be able to backport because of the bump from 1.109.0 to 1.114.0, but feel free to try out the patch in #305825, targeting Unstable :)
