### ISSUE TITLE
wechat-uos: IM is broken on specific DE

### ISSUE THREAD

**Issue by pokon548** [NixOS/nixpkgs#303295]
### Describe the bug
This is a bug tracker for im issue on https://github.com/NixOS/nixpkgs/pull/293730/. Please report further issues here. DO NOT report on merged / closed pull request.

For anyone who is interested in trouble shooting, you may also want to check out https://github.com/NixOS/nixpkgs/pull/303301, which may helps to fix this issue.

Known problematic DE:
- [ ] Hyperland / Wayland https://github.com/NixOS/nixpkgs/pull/293730/#issuecomment-2046995257

### Steps To Reproduce
1. Open `wechat-uos`
2. Cannot input using fcitx5 / ibus / ...

### Expected behavior
IM should be working on `wechat-uos`. 

### Notify maintainers
@pokon548

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pokon548** [comment]
@Ziqi-Yang can you verify whether https://github.com/NixOS/nixpkgs/pull/303301 fixes IM issue for you? Please kindly provide your feedback on https://github.com/NixOS/nixpkgs/issues/303295 as original pr is closed and should not being used to discuss anymore

**Comment by Ziqi-Yang** [comment]
Nope. 
Steps I ran:
1. remove the previously installed wechat-uos 
2. copy the new build file in your commit into `default.nix`
3. run command `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'`
4. run command `cp ./result/share/applications/com.tencent.wechat.desktop ~/.local/share/applications/`
5. use Hyprland shortcut key to launch `rofi-wayland` -> wechat-uos -> not work
6. run command `./result/bin/wechat-uos ` -> can work

**Comment by pokon548** [comment]
> Nope. Steps I ran:
> 
>     1. remove the previously installed wechat-uos
> 
>     2. copy the new build file in your commit into `default.nix`
> 
>     3. run command `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'`
> 
>     4. run command `cp ./result/share/applications/com.tencent.wechat.desktop ~/.local/share/applications/`
> 
>     5. use Hyprland shortcut key to launch `rofi-wayland` -> wechat-uos -> not work
> 
>     6. run command `./result/bin/wechat-uos ` -> can work

If `wechat-uos` can be running properly by `./result/bin/wechat-uos`, then I guess it may probably be related to https://github.com/davatorium/rofi/issues/955, which means `rofi` does not properly provide environment variables to my wrapper. 

I will try to see if there is anything I could do. In the meantime, you may try to use the workaround provided in that issue and see whether it works for you.

**Comment by Ziqi-Yang** [comment]
Thanks! However, I cannot make it work when I use a Hyprland shortcut key to execute the command `rofi -run-command 'bash -c -i {cmd}' -show run` , nor the command `hyprctl dispatch exec "rofi -run-command 'bash -c -i {cmd}' -show run"` works inside a terminal environment. 

I find it is related to Home Manager's environment variable settings. According to https://github.com/hyprwm/Hyprland/issues/4477#issuecomment-1899224201, home manager's `sessionVariables` is only for interactive shells, which is not clear on the Home Manager's manual / differs from the behavior of `environment.sessionVariables` (will be merged into environment variables). After I set the environment variable `QT_IM_MODULE` to `fcitx` in Hyprland's configuration, the holy pitfall was solved.

This is my solution: 
https://git.sr.ht/~meow_king/nixos-config/tree/7dad0fb7743bc51081113f2d7653db5a5d9c9632/item/home/linux/desktop/hyprland.nix#L37-44,62-79,211-214

**Comment by Ziqi-Yang** [comment]
Also one thing to mention, QT application may have display issue in Wayland or only in Hyrpland (m version is v0.37.1) when scale of the monitor is not 1 or other integer numbers. Specially, wechat-uos have illegible non-antialiasing fonts when my monitor scale is 1.25
