### ISSUE TITLE
chromiumBeta fails to build on 17.09

### ISSUE THREAD

**Issue by disassembler** [NixOS/nixpkgs#30322]
## Issue description
chromium beta fails to build on 17.09. This version of chromium finally fixes the facetimehd issue (upstream bug, not nixos related) preventing video calls in chromium from working on macbooks, so I'd like to be able to use it until that version becomes stable.

### Steps to reproduce

git clone https://github.com/NixOS/nixpkgs
git checkout release-17.09
nix-build -A chromiumBeta

results in:
```
unpacking source archive /nix/store/wk91fg2394xg06fa39rll73546bs12iw-chromium-62.0.3202.29.tar.xz
source root is chromium-62.0.3202.29
setting SOURCE_DATE_EPOCH to timestamp 1505945226 of file chromium-62.0.3202.29/skia/ext/skia_commit_hash.h
patching sources
applying patch /nix/store/brdxf1dl5rlnxq3i7cyharnirgaq58jk-nix_plugin_paths_52.patch
patching file chrome/common/chrome_paths.cc
Hunk #1 succeeded at 76 (offset 8 lines).
Hunk #2 succeeded at 274 (offset 9 lines).
Hunk #3 succeeded at 282 (offset 9 lines).
Hunk #4 succeeded at 325 (offset 9 lines).
Hunk #5 succeeded at 360 (offset 9 lines).
applying patch /nix/store/wkc502916v4spj8rlsfmfyi507wci0mw-chromium-gn-bootstrap-r14.patch
patching file tools/gn/bootstrap/bootstrap.py
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
patch unexpectedly ends in middle of line
2 out of 2 hunks ignored -- saving rejects to file tools/gn/bootstrap/bootstrap.py.rej
builder for ‘/nix/store/56vnpc5fb0vnyvdm7y2l67jnbpnipa86-chromium-62.0.3202.29.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/vc7s7ghwy09fn02inb3pc9vjkdrls34r-chromium-beta-62.0.3202.29.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/vc7s7ghwy09fn02inb3pc9vjkdrls34r-chromium-beta-62.0.3202.29.drv’ failed
```

To fix issue:
git clone https://github.com/NixOS/nixpkgs
git checkout release-17.09
git cherry-pick 93aaeaccc2
nix-build -A chromiumBeta

## Technical details

* System: 17.09.1462.07ca7b64d2 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1547.2231575a7d"
* Sandboxing enabled: true

related: #29941

**Comment by bendlas** [comment]
As you mentioned in the previous ticket, this should be able to be fixed by cherry-picking commits from master. Please @ mention me in any PRs coming from this, so I can review.

**Comment by vcunat** [comment]
OK, testing the build locally with that commit picked...

**Comment by vcunat** [comment]
Hmm, repeatedly catching a compiler crash halfway through, again.  Probably OK, just that Ryzen bug again, and it's certainly a better state than before.  Pushed as 80550eacc45.
