### ISSUE TITLE
fish standard functions do not end up in the nixos system store path

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#303208]
### Describe the bug
the `share/fish/functions` directory does not end up in `/var/run/current-system/sw`.

i belive this may be the cause of a transient failure where __fish_seen_subcommand_from was unable to be found (although it seems that has been fixed for the time being after i loaded the file manually)

### Steps To Reproduce
1. set `programs.fish.enable = true` in your nixos config
2. `ls /var/run/current-system/sw/share/fish`
3. ...

### Expected behavior
the files should be there, and the functions defined there should resolve.

### Notify maintainers
@adamcstephens @cole-h @winterqt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.10, NixOS, 23.11 (Tapir), 23.11.5742.219951b495fc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(binarycat): `"stable-23.05, unstable"`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
I've never experienced issues with the current configuration, so I assume fish knows to look in its prefixdir for completions as well.

How can I reproduce the failure you found?
How are you launching fish? Is it your shell and if so what's the config?

**Comment by lolbinarycat** [comment]
sorry, i don't know how to replicate the error exactly.  all i did was type `cargo <TAB>` and it gave me an unending stream of `__fish_seen_subcommand_from: command not found`.

**Comment by adamcstephens** [comment]
I'm not able to reproduce this. I created a new NixOS system, added `programs.fish.enable = true;`, installed cargo and was able to tab complete the subcommands. I suspect this is an issue with how you're installing cargo, or how you're starting fish (you didn't answer this) or something outside the package itself.

**Comment by lolbinarycat** [comment]
> you didn't answer this

it happens if i start fish as a login shell or via any convoluted method.

**Comment by adamcstephens** [comment]
I'm unable to reproduce this so not sure what else I can do at this point. If you can provide a more detailed step-by-step reproducer for the error itself (not the path linking originally described), I'm happy to look further.

**Comment by lolbinarycat** [comment]
> If you can provide a more detailed step-by-step reproducer for the error itself

well that's the thing, i can't, and i said as much in the original post.

**Comment by adamcstephens** [comment]
The store paths to share are in `fish_complete_path` and `fish_function_path`.

```
root@nixos ~# readlink -f $(which fish)
/nix/store/8x24n8synkrl0jb5nsrh01fhzqwk1npa-fish-3.7.0/bin/fish
root@nixos ~# echo $fish_function_path | grep /nix/store/8x24n8synkrl0jb5nsrh01fhzqwk1npa-fish-3.7.0/
/root/.config/fish/functions /nix/store/8x24n8synkrl0jb5nsrh01fhzqwk1npa-fish-3.7.0/etc/fish/functions /root/.local/share/fish/vendor_functions.d /nix/store/8cpsc8d75ps27d6gzcdrdysipddkvpfb-desktops/share/fish/vendor_functions.d /root/.nix-profile/share/fish/vendor_functions.d /nix/profile/share/fish/vendor_functions.d /root/.local/state/nix/profile/share/fish/vendor_functions.d /etc/profiles/per-user/root/share/fish/vendor_functions.d /nix/var/nix/profiles/default/share/fish/vendor_functions.d /run/current-system/sw/share/fish/vendor_functions.d /root/.nix-profile/etc/fish/functions /nix/profile/etc/fish/functions /root/.local/state/nix/profile/etc/fish/functions /etc/profiles/per-user/root/etc/fish/functions /nix/var/nix/profiles/default/etc/fish/functions /run/current-system/sw/etc/fish/functions /root/.nix-profile/share/fish/vendor_functions.d /nix/profile/share/fish/vendor_functions.d /root/.local/state/nix/profile/share/fish/vendor_functions.d /etc/profiles/per-user/root/share/fish/vendor_functions.d /nix/var/nix/profiles/default/share/fish/vendor_functions.d /run/current-system/sw/share/fish/vendor_functions.d /nix/store/8x24n8synkrl0jb5nsrh01fhzqwk1npa-fish-3.7.0/share/fish/vendor_functions.d /nix/store/8x24n8synkrl0jb5nsrh01fhzqwk1npa-fish-3.7.0/share/fish/functions
```
