### ISSUE TITLE
NixOS 24.05 — Release Schedule

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#303285]
Hi, we are [Weijia Wang](https://github.com/wegank) & [Jörg Thalheim](https://github.com/Mic92), the [release managers](https://nixos.github.io/release-wiki/Release-Managers.html) for NixOS 24.05 ("_Uakari_").

We're also happy to work with [Jacek Generowicz](https://github.com/jacg) and [Kirby Little](https://github.com/krbylit), who will be the [release editors](https://nixos.github.io/release-wiki/Release-Editors.html) for this NixOS release.

Below you can find the release calendar for the next two months running up to the planned release at the end of May 2024. If something feels unclear to you, don't hesitate to reach out, we are here to guide the process and make sure this will be a satisfying release for all of us.

Stay tuned for updates!

<table>
    <tr>
        <td></td>
        <td>Date</td>
        <td>Affects</td>
        <td>Events</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2024-04-11</td>
        <td>—</td>
        <td>Start <a href="https://github.com/NixOS/nixpkgs/issues/303286">discussion</a> about "Feature Freeze & Release Blockers" with ecosystem maintainers</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2024-04-17</td>
        <td>all branches</td>
        <td>Restrict breaking changes to <a href="https://nixos.github.io/release-wiki/Release-Critical-Packages.html">Release Critical Packages</a></td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2024-05-01</td>
        <td>all branches</td>
        <td>Restrict all breaking changes with the exception of desktop environments</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2024-05-08</td>
        <td><tt>master</tt></td>
        <td>Wait for <tt>staging-next</tt> merge into <tt>master</tt>; begin first <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Begin Zero Hydra Failures campaign</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2024-05-15</td>
        <td><tt>master</tt></td>
        <td>Wait for first <tt>staging-next</tt> merge into <tt>master</tt>; begin second <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>staging</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td rowspan="8">:heavy_check_mark:</td>
        <td rowspan="8">2024-05-22</td>
        <td><tt>master</tt></td>
        <td>Wait for second <tt>staging-next</tt> merge into <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>staging-next</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Mark failing packages as broken</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-24.05</tt></td>
        <td>Branch-off</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-24.05</tt></td>
        <td>Tag <tt>24.05-beta</tt> on <tt>release-24.05</tt><br /> and <tt>24.05-unstable</tt> on <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-24.05</tt></td>
        <td>Create release channels</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-24.05</tt></td>
        <td>ZHF fixes go into <tt>master</tt> and need to be backported to <tt>release-24.05</tt></td>
    </tr>
    <tr>
        <td><tt>release-24.05</tt></td>
        <td>Prepare for release, finish remaining issues</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2024-05-31</td>
        <td><tt>release-24.05</tt></td>
        <td>Release! Also, ZHF ends</td>
    </tr>
    <tr>
        <td></td>
        <td>2024-06-09</td>
        <td>—</td>
        <td>Release Retrospective, everyone is invited to give feedback!</td>
    </tr>
</table>

---

## Definitions

- Backport
  - Cherry-picking a change from `master` into `release-24.05`
  - Use the backport action by applying the `backport: release-24.05` tag
- Breaking change
  - A change that is likely to break downstream consumers
- Ecosystem maintainers
  - Maintainer teams that have enabled `enableFeatureFreezePing` in [`maintainers/team-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix)
- [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
  - List of packages that usually cause widespread breakages
- Restriction
  - Changes of the mentioned kind cannot be merged while the restriction is active
- ZHF
  - Zero Hydra Failures
  - Period in which contributors focus on stabilizing packages
  - Usually through PRs targeted at the `master` branch

**Comment by wegank** [comment]
April 17 ends [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth). Breaking changes to [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html) are now restricted.

**Comment by wegank** [comment]
> How is he supposed to be an RM if he was just banned?

Indeed, he is no longer a release manager for this cycle, as he has lost access to the NixOS organization due to the ban.

@Mic92 is now a release manager for NixOS 24.05.

**Comment by KFearsoff** [comment]
Should we reconsider the schedule, or cancel the release altogether?

With the tensions running at an all-time high and people burning out to a crisp, I don't think missing a release is that big of a deal. I fear that if we put the people under additional stress of preparing a release, we'll cause burnout on an even more massive scale and do a lot of damage to the community that is already in a shaky place.

**Comment by wegank** [comment]
> Should we reconsider the schedule, or cancel the release altogether?

NixOS 23.11 was only designed to be secure until its [EOL on 30 Jun 2024](https://endoflife.date/nixos), which isn't likely to change without a huge backport effort, so cancelling the release or delaying it too much is hardly an option.

I believe the schedule for the 24.05 cycle is in a good shape, mainly because we're lucky that the maintainers are leaving near the end of the feature freeze period and, more importantly, after they've finished their work on the subsystems (big thanks to all!). For the upcoming stabilization period, I'm explicitly asking everyone to take their time, since even if we don't have enough fixes, there is always the last resort of [marking packages as broken](https://nixos.github.io/release-wiki/Beta-Phase.html).

That said, as a signatory to [an open letter](https://nixos-users-against-mic-sponsorship.github.io), as someone who [pins Nix to 2.18](https://github.com/NixOS/nixpkgs/issues/303286#issuecomment-2057117162) for this cycle, and probably as the second release manager for the 24.11 cycle, I feel helpless in the face of the current situation, even though I hope it will eventually be resolved.

**Comment by vcunat** [comment]
I don't _think_ cancelling 24.05 would help, in the situation as I see it so far (though perhaps with a bit different arguments why).  Though sure, I believe it's important to watch oneself for burnout.

Of course, regardless of the current situation, it can always happen that some (usually technical) issue is encountered, and it seems better to wait for fixing it instead of releasing half-broken.  So sometimes NixOS had the release delayed by a week or two IIRC, not a big deal in my eyes.

**Comment by Mic92** [comment]
I was able to reach all subsystem maintainers except for Ocaml and Coq. So far no one is aware of major blockers. So I don't know why we should cancel the release. Backporting fixes to the old release would be more work for sure.

**Comment by wegank** [comment]
There's currently no blocker for OCaml and Coq, according to https://github.com/NixOS/nixpkgs/pull/307816#issuecomment-2085371952.

Also, May 1 ends [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth). All breaking changes are now restricted, except for desktop environments.

**Comment by cimm** [comment]
Thanks for approving @getchoo! Can this pull request be merged now?

**Comment by wegank** [comment]
As the last staging-next iteration for 24.05 has begun, breaking changes targeting staging are now unrestricted and will not be present in the release.

**Comment by wegank** [comment]
That will be done as part of the [branch-off](https://nixos.github.io/release-wiki/Branch-Off.html) next week.

**Comment by wegank** [comment]
`release-24.05` has been branched off. Remember to also add the `backport release-24.05` to your pull requests 🎉

**Comment by OrhanYigitDurmaz** [comment]
release what time?

**Comment by anscarlett** [comment]
> release what time?

I'm gonna assume  23:59:59 UTC-12 aka AoE

**Comment by wegank** [comment]
> I'm gonna assume 23:59:59 UTC-12 aka AoE

We'll start the release process tonight at 20:00 CEST, so I expect it to be a little earlier than that.

(The ISO images are already available [here](https://6659cfbd1ce6673c192f8a78--nixos-homepage.netlify.app/download/#nixos-iso), though.)

**Comment by OrhanYigitDurmaz** [comment]
> > I'm gonna assume 23:59:59 UTC-12 aka AoE
> 
> We'll start the release process tonight at 20:00 CEST, so I expect it to be a little earlier than that.
> 
> (The ISO images are already available [here](https://665a0dd631072b739c6e0436--nixos-homepage.netlify.app/download/#nixos-iso), though.)

Cant wait to switch to NixOS :) Does it come with Plasma 6?

**Comment by wegank** [comment]
> Cant wait to switch to NixOS :) Does it come with Plasma 6?

Yes.

**Comment by wegank** [comment]
NixOS 24.05 released! https://discourse.nixos.org/t/nixos-24-05-released/46279/2
