### ISSUE TITLE
How to switch to latest kernel and importantly boot with it

### ISSUE THREAD

**Issue by unixbhaskar** [NixOS/nixpkgs#30335]
## Issue description
How to switch to the latest kernel and importantly to boot with it.
`
[root@NixOS:/etc]# nix-env -q linux
linux-4.14-rc2

[root@NixOS:/etc]# uname -a
Linux NixOS 4.9.53 #1-NixOS SMP Thu Oct 5 07:44:17 UTC 2017 x86_64 GNU/Linux

[root@NixOS:/etc]# nix-env --set-flag active false linux
setting flag on ‘linux-4.14-rc2’
building path(s) ‘/nix/store/y64h68zqy7dv08cqpnd91lrnyr49d0z3-user-environment’
created 900 symlinks in user environment

and it's still showing :

[root@NixOS:/boot/loader/entries]# cat NixOs.conf 
title NixOS
version 17.09.1535.1fdca25ee8, 
linux /EFI/nixos/56lz3l0n4ibqn2d6i9jv4jzrr9kqhjli-linux-4.9.53-bzImage.efi
initrd /EFI/nixos/zalgxl8i8fc2zjkmkzsyp826fxdnciay-initrd-initrd.efi
options systemConfig=/nix/store/2wdficchly7gdrxjr65nggf4d34sw8ar-nixos-system-NixOS-17.09.1535.1fdca25ee8 init=/nix/store/2wdficchly7gdrxjr65nggf4d34sw8ar-nixos-system-NixOS-17.09.1535.1fdca25ee8/init loglevel=4
machine-id 6ea528b0808c4ec6853d7a346c075bd7
`

### Steps to reproduce

Look like there is no straight forward way of upgrading to a latest kernel or documented in your manual.

Could provide me the steps.So I can record it for future references

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by bjornfor** [comment]
Try adding this to /etc/nixos/configuration.nix:

```
  boot.kernelPackages = pkgs.linuxPackages_latest;
```

**Comment by unixbhaskar** [comment]
Tried..throwing up an error " extend" attribute missing ...while trying to build it including that option in the mentioned file.

**Comment by unixbhaskar** [comment]
FYI 
`
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

   boot.kernelPackages = pkgs.linux_testing;

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
 #boot.loader.grub.device = "/dev/sda12";
   networking.hostName = "NixOS"; # Define your hostname.
 #networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  networking.networkmanager.enable = true;
   networking.nameservers = [ "192.168.0.1" ];

  # Select internationalisation properties.
  # i18n = {
  #   consoleFont = "Lat2-Terminus16";
  #   consoleKeyMap = "us";
  #   defaultLocale = "en_US.UTF-8";
  # };

  # Set your time zone.
   time.timeZone = "Asia/Kolkata";

  # List packages installed in system profile. To search by name, run:
  # $ nix-env -qaP | grep wget
   environment.systemPackages = with pkgs; [ bash mutt firefox git gnupg wget vim curl lynx ];
  #   wget vim
  # ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
   programs.bash.enableCompletion = true;
   programs.mtr.enable = true;
   programs.gnupg.agent = { enable = true; enableSSHSupport = true; };
   hardware.pulseaudio.enable = true;
  # List services that you want to enable:
# Add file system entries for each partition that you want to see mounted
 # at boot time.  You can add filesystems which are not mounted at boot by
 # adding the noauto option.
 fileSystems = [
   # Mount the additional file systems
   #
    { mountPoint = "/home";
      device = "/dev/vghome/lvhome";
    }

    { mountPoint = "/data";
      device = "/dev/data/datalv";
    }
 ];

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable the X11 windowing system.
   services.xserver.enable = true;
   services.xserver.layout = "us";
   services.xserver.xkbOptions = "eurosign:e";

  # Enable touchpad support.
   services.xserver.libinput.enable = true;
   services.xserver.synaptics.twoFingerScroll = true;

  # Enable the KDE Desktop Environment.
   services.xserver.displayManager.sddm.enable = true;
   services.xserver.desktopManager.plasma5.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
   users.extraUsers.bhaskar = {
     isNormalUser = true;
     home = "/home/bhaskar";
     description = "Bhaskar Chowdhury";
 extraGroups = ["wheel" "disk" "audio" "video" "networkmanager" "input" "systemd-journal"];
     uid = 1000;
  };

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "17.09"; # Did you read the comment?

}

Any clue???
`

**Comment by bjornfor** [comment]
You didn't add what I said. Try this "patch" to your config:

```
   -boot.kernelPackages = pkgs.linux_testing;
   +boot.kernelPackages = pkgs.linuxPackages_latest;
```

**Comment by unixbhaskar** [comment]
Well, about to reply to ya about my mistake...thanks for the heads up man!

**Comment by unixbhaskar** [comment]
Thanks ,it does work...@bjornfor

**Comment by bjornfor** [comment]
Glad it worked! (Closing.)
