### ISSUE TITLE
Inconsistent behavior from XDG

### ISSUE THREAD

**Issue by third3ye** [NixOS/nixpkgs#3033]
When I upgrade the systems web-browser and e-mail client they receive new file directories, in accordance with the nix store. This leads to icons that have been generated by the desktop becoming obsolete. Visa vi if you do a nix-collect-garbage the desktop will complain that the executable does not exist anymore, due to the fact that the newer installation is in another directory since it's update.

Has anyone discussed updating xdg and icons on the user-side?

**Comment by Profpatsch** [comment]
(triage) @third3ye Is this still a problem?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by zimbatm** [comment]
I'm not using a traditional desktop so can't repro. If the issue is still there I'm sure we will get other reports.

**Comment by vcunat** [comment]
Well, this is hard, as the [XDG spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) requires that caching apps decide re-scanning by timestamps:
> [...] any implementation that does caching is required to look at the mtime of the toplevel icon directories when doing a cache lookup, unless it already did so less than 5 seconds ago. This means that any icon editor or theme installation program need only to change the mtime of the the toplevel directory where it changed the theme to make sure that the new icons will eventually get used.

**Comment by zimbatm** [comment]
If only the spec was (mtime AND symlink target) ... I guess it's still an issue then, re-opening.

**Comment by Profpatsch** [comment]
(triage) still an issue?

**Comment by zimbatm** [comment]
Yes on Gnome at least

**Comment by Profpatsch** [comment]
(triage) still an issue?

**Comment by peterhoeg** [comment]
No longer a problem.
