### ISSUE TITLE
FZF missing /share/fzf.

### ISSUE THREAD

**Issue by YaroKasear** [NixOS/nixpkgs#303381]
### Describe the bug
The fzf-0.49.0 package is missing /share/fzf, which is causing the following to appear on my terminal whenever I start my shell: 

```console
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```

Googling tells me FZF_BASE is supposed to indicate /usr/share/fzf, or in the case of nixpkgs/NixOS: ${pkgs.fzf}/share/fzf.

When I look at previous versions of the package, I see the directory is there, but not in  fzf-0.49.0.

### Steps To Reproduce
1. Install  fzf-0.49.0.
2. Open a terminal with oh-my-zsh's fzf plugin enabled.
3. See the error described above.

### Expected behavior
No message displayed and proper fzf integration where needed, and fzf's share directory being present.

### Notify maintainers

@Br1ght0ne
@ma27
@zowoq

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240410.d6b3ddd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/bjv2qk3gg1iv69rbama3q9aprcp6d9wp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Can you try adding to `environment.pathsToLink = "/share/fzf";` in your configuration.nix?

**Comment by YaroKasear** [comment]
> Do you have the `fzf-zsh` nix package installed?

I don't appear to, no. I hadn't needed it before. I'll install it and report back.

**Comment by YaroKasear** [comment]
> Can you try adding to `environment.pathsToLink = "/share/fzf";` in your configuration.nix?

Wouldn't this just create /share/fzf on /? I'm not sure what this will help.

**Comment by YaroKasear** [comment]
> > Do you have the `fzf-zsh` nix package installed?
> 
> I don't appear to, no. I hadn't needed it before. I'll install it and report back.

This had no effect.

**Comment by YaroKasear** [comment]
> Can you try adding to `environment.pathsToLink = "/share/fzf";` in your configuration.nix?

I tried putting `environment.pathsToLink = ["/usr/share/fzf"];` in my flake and it didn't actually link anything. I manually created the folder (I use impermanence, so it'll go away on reboot.) and it didn't get rid of the error. Instead I got:

```console
fzf_setup_using_base_dir:source:56: no such file or directory: /usr/share/fzf/key-bindings.zsh
[oh-my-zsh] fzf plugin: Cannot find fzf installation directory.
Please add `export FZF_BASE=/path/to/fzf/install/dir` to your .zshrc
```

I am pretty sure the issue is that the output for fzf-0.49.0 doesn't have share/fzf in it, which is what the fzf plugin is looking for. 

These are the contents of the share directory in the output:

```console
┌─( ❄️ yaro@loki at 11:32:07 )─[ 10.10.255.124 ]──────────────( ~ 
├─{ zsh took 25ms 
└─< 😸 > ls /nix/store/psmylmimp0023yibdx1w76hf8zds0sjj-fzf-0.49.0/share      
 nvim   vim-plugins
```

By contrast, here is what I find in a previous version:

```console
┌─( ❄️ yaro@loki at 11:32:56 )─[ 10.10.255.124 ]──────────────( ~ 
├─{ zsh took 144ms 
└─< 😸 > ls /nix/store/sif8a7y7p7r7wxpww2inxfrckni69c1a-fzf-0.47.0/share           
 fish   fzf   nvim   vim-plugins
```

It's missing "fzf" which I think would be fairly important, no?

**Comment by chewblacka** [comment]
If I'm not mistaken the `fzf-zsh` package is specifically designed to get fzf working with oh-my-zsh.

**Comment by Ma27** [comment]
> I tried putting environment.pathsToLink = ["/usr/share/fzf"]; in my flake and it didn't actually link anything

fwiw `/share/fzf` w/o the `/usr` prefix.

**Comment by YaroKasear** [comment]
> > I tried putting environment.pathsToLink = ["/usr/share/fzf"]; in my flake and it didn't actually link anything
> 
> fwiw `/share/fzf` w/o the `/usr` prefix.

Tried making that and it still didn't change anything.

**Comment by Ma27** [comment]
Ah I think it was removed in https://github.com/NixOS/nixpkgs/pull/298692, but will be brought back in https://github.com/NixOS/nixpkgs/pull/303213.

But I may be missing some context since I didn't really follow the discussion on updating 0.49.0. cc @sebtm @SuperSandro2000

**Comment by YaroKasear** [comment]
> Ah I think it was removed in #298692, but will be brought back in #303213.
> 
> But I may be missing some context since I didn't really follow the discussion on updating 0.49.0. cc @SebTM @SuperSandro2000

Thank you. I'll wait for the PR to land in nixpkgs-unstable and let you know.

**Comment by SebTM** [comment]
Hey, I've merged the fix PR in question - you can use https://nixpk.gs/pr-tracker.html?pr=303213 to check the status - please do not forget to close the issue if it is resolved ultimately 🙏🏻
