### ISSUE TITLE
The developPackage function generates a different hash every time

### ISSUE THREAD

**Issue by mightybyte** [NixOS/nixpkgs#30331]
## Issue description

Even when nothing changes in the package, when I use the `developPackage` function in my `default.nix` it rebuilds the package every time.

Pinging @shlevy 

### Steps to reproduce

    git clone https://github.com/TaktInc/hadron.git
    git checkout builds-with-nix
    nix-build
    nix-build

## Technical details

* System: Darwin Kernel Version 15.6.0
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre111304.5328102325
* Sandboxing enabled: build-use-sandbox = false

**Comment by shlevy** [comment]
Thanks, will likely take a look this weekend.

**Comment by pbogdan** [comment]
Could this be related to the `./result` symlink that `nix-build` leaves behind and `src` being set to `./.` which would cause the source to change every time `nix-build` is invoked? @mightybyte do you see rebuilds if you manually remove `./result` before re-running `nix-build` or run the builds with `nix-build --no-out-link`?

**Comment by mightybyte** [comment]
Yes, I tried this.  If I remove the `result` symlink, then it gets the cached version.  So I guess the `developPackage` function just has to be modified to filter that out (and/or maybe allow the user to filter out certain files).

**Comment by cdepillabout** [comment]
`haskellPackages.developPackage` takes the directory as input as a `root` argument.  If the user wants to filter out certain files before passing to `developPackage`, that is their responsibility.  `developPackage` doesn't do any automatic filtering on its own.
