### ISSUE TITLE
Package request: pizauth

### ISSUE THREAD

**Issue by jeremystucki** [NixOS/nixpkgs#303366]
**Project description**

Command-line OAuth2 authentication daemon

**Metadata**

* homepage URL: https://tratt.net/laurie/src/pizauth/
* source URL: https://github.com/ltratt/pizauth
* license: mit & apache
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Moraxyc** [comment]
@jeremystucki please test #316937
