### ISSUE TITLE
Update request: cmake 3.28.3 → 3.29.1

### ISSUE THREAD

**Issue by AMS21** [NixOS/nixpkgs#303408]
- Package name: cmake
- Latest released version: [3.29.1](https://github.com/Kitware/CMake/releases/tag/v3.29.1)

- Current version on the unstable channel: 3.28.3
- Current version on the stable/release channel: 3.27.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ttuegel
@LnL7
@AndersonTorres

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Already on Staging.
