### ISSUE TITLE
Update request: go 1.22.1 → 1.22.2

### ISSUE THREAD

**Issue by purpleclay** [NixOS/nixpkgs#303525]
- Package name: `go`
- Latest released version: `1.22.2`
- Current version on the unstable channel: `1.22.1`
- Current version on the stable/release channel: `1.21.9`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@katexochen
@zowoq 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/301373

https://nixpk.gs/pr-tracker.html?pr=301373
