### ISSUE TITLE
plasma6 seems to implicitly include ibus

### ISSUE THREAD

**Issue by jinzhongjia** [NixOS/nixpkgs#303593]
I reinstalled nixos on my computer, completely reconfigured it, and found that using plasma6 will install ibus for me, but plasma5 will not！

I checked the source code and it seems that a certain package depends on ibus.

**Comment by jinzhongjia** [comment]
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/kde/plasma/plasma-desktop/default.nix#L62

`plasma-desktop` import the ibus, why ? @K900

**Comment by K900** [comment]
Because it's a dependency. What is the actual problem?

**Comment by jinzhongjia** [comment]
> Because it's a dependency. What is the actual problem?

In archlinux, `ibus` is optional, that need user manual installation
And we an use fcitx5, so ibus is not a dependency.

**Comment by K900** [comment]
NixOS doesn't really have the concept of optional dependencies. Does ibus being there cause any issues for you?

**Comment by jinzhongjia** [comment]
There is currently no problem with this, it's just that I'm using fcitx5 now and I'm a bit obsessive

**Comment by K900** [comment]
Then that's just something we'll have to keep in, at least for now. You could submit a PR making it optional, and overlay the package, but that will cause way too many rebuilds to be worth it.
