### ISSUE TITLE
Update request: albert 0.22.17 → 0.23.0

### ISSUE THREAD

**Issue by KuenzelIT** [NixOS/nixpkgs#303572]
- Package name: albert
- Latest released version: 0.23.0
- Current version on the unstable channel: 0.22.17
- Current version on the stable/release channel: 0.22.17
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ericsagnes @Synthetica9  

-----

Note for maintainers: Please tag this issue in your PR.

---

I'm pretty new to Nix, so I hope this is the right way to request an update. 

The latest release can be found here: https://github.com/albertlauncher/albert/releases/tag/v0.23.0

**Comment by KuenzelIT** [comment]
Thank you for working on this.

Unfortunately I still don't know how to get the new version. When will it be available in nixpkgs?

**Comment by matthiasbeyer** [comment]
Depending on which channel you use:

* if you use unstable, as soon as unstable gets updated and includes the merged patch
* if you use stable, after the next stable release (24.05 afaik)

**Comment by KuenzelIT** [comment]
Thank you very much for explaning!
