### ISSUE TITLE
Can't override haskellPackages.binary

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#30355]
## Issue description

Trying to override `binary` in `haskellPackages` causes an infinite recursion error.

### Steps to reproduce
Create a `default.nix` with the following content:

```nix
let
  haskellPackages = (import <nixpkgs> {}).haskellPackages.override {
    overrides = self: super: {
      binary = super.callHackage "binary" "0.8.5.1" {};
    };
  };
in haskellPackages.ghcWithPackages (self: [ self.binary ])
```

and run `nix-build default.nix --show-trace`

## Technical details

* System: Ubuntu 16.04.3 LTS
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1547.2231575a7d
* Sandboxing enabled: no

**Comment by ocharles** [comment]
I believe this is because `binary` is a boot package that can't be overriden, much like `transformers`, `base` itself, `containers` etc.

```nix
((import <nixpkgs> {}).haskellPackages.override { overrides = self: super: { containers = super.callHackage "binary" "0.8.5.1" {}; }; }).containers
```

is the problem in a one-liner for `nix-repl`.

**Comment by ocharles** [comment]
Though this does seem to work...

```nix
with (import <nixpkgs> {}); (haskellPackages.override { overrides = self: super: { containers = haskellPackages.callHackage "binary" "0.8.5.1" {}; }; }).containers
```

**Comment by vaibhavsagar** [comment]
FWIW I need this because I'm trying to build Idris, which overrides `binary` in [`stack.yaml`](https://github.com/idris-lang/Idris-dev/blob/d6be6210f0e376b8824bff45ef2ee0fa93f02bfa/stack.yaml#L16). Let me try that second version and see if it gets me anywhere :smile:

**Comment by vaibhavsagar** [comment]
It turns out that there is a `haskellPackages.binary_0_8_5_1` that I can use instead.

**Comment by vaibhavsagar** [comment]
The trick is to use `haskell.lib.dontCheck`:

```
let
  pkgs = import <nixpkgs> {};
  lib = pkgs.haskell.lib;
in (pkgs.haskellPackages.override {
  overrides = self: super: rec {
    binary = lib.dontCheck super.binary_0_8_5_1;
  };
}).binary
```

works without any issues :smile:.
