### ISSUE TITLE
Mullvad VPN 2024.1 unstable is broken

### ISSUE THREAD

**Issue by relaxshon** [NixOS/nixpkgs#303582]
### Describe the bug
Since the new update of Mullvad vpn the app is buggy. When i try to change the api-access it say "api unreachable" and when i try to connect on my account the app keep loading to my account then when i kill the process and re-launch the app i'm connected in my account but there is no servers list that appear. And there is something strange if i change the tunnel protocol with the gui app the app will not show me the change but with the cli command i can see the tunnel protocol has changed 

### Steps To Reproduce
1. Use the kernel hardened
2. Install mullvad vpn 2024.1 from unstable
3. Try to connect

### Expected behavior
Connecting in my account withouht any issue

### Screenshots
![bug1](https://github.com/NixOS/nixpkgs/assets/166758346/f85b5b42-1764-4635-b8d2-f7ad43b3a213)
![bug2](https://github.com/NixOS/nixpkgs/assets/166758346/5bb22a58-05e6-4030-abd6-f09ff6a0fe01)
![bug3](https://github.com/NixOS/nixpkgs/assets/166758346/8ef8064b-5408-4d7f-95c5-57d637ca00f4)

### Log from the app
[mullvadlog.txt](https://github.com/NixOS/nixpkgs/files/14957689/mullvadlog.txt)

### Additional context
The app was running fine with the 2023.6 version i din't have any issue.

### Notify maintainers

@Br1ght0ne @ymarkus @ataraxiasjel

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Can you add the output of `nix-shell -p nix-info --run "nix-info -m"`?

**Comment by ashuramaruzxc** [comment]
@relaxshon
> Use the kernel hardened
Does this issue only appears on a hardened kernel? if so have you tried downgrading or upgrading the hardened kernel?
Would like to get an output of `nix-shell -p nix-info --run "nix-info -m` to understand how to replicate it on my side

**Comment by HippieMitch** [comment]
I had this happening on my system.  I just updated to the latest NixOS Unstable and the issue appears to have been resolved on my machine.

**Comment by HippieMitch** [comment]
I had this happening on my machine with the vanilla kernel.  After updating to the latest NixOS Unstable, the issue appears to have been resolved.

**Comment by ashuramaruzxc** [comment]
same for me, i have tested xanmod, vanilla and hardened and on every kernel i tested, it seems to be working just fine
