### ISSUE TITLE
PythonMagick can't be imported after installation.

### ISSUE THREAD

**Issue by AttilaVM** [NixOS/nixpkgs#30357]
## Issue description

Even so  PythonMagick is installed it can not be imported as a module. 

### Steps to reproduce

My default.nix:
```
with import <nixpkgs> {};

stdenv.mkDerivation rec {
  name = "multiscale";
  shellHook = ''
    echo -e "\e[32mMultiscale envioronment  \e[0m"
'';
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [
    git
    pythonmagick
    imagemagick
    (python35.withPackages (pkgs:
      [ pkgs.docopt
        pkgs.magic
  ]))
  ];
}

```
Type _nix-shell_ command in the directory, where the default.nix resides.

Open a python3.5 console and type

`import PythonMagick`

which will lead to the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'PythonMagick'
```

I know that PythonMagick was installed like an application instead of a library however this is the only way to install it.

## Technical details

* System:  17.03.1904.09b9f7e7c4 (Gorilla)
* Nix version:   1.11.14
* Nixpkgs version: 18.03pre117581.9b177399c4
* Sandboxing enabled: True

**Comment by FRidh** [comment]
I added a comment to the Nix expression of `PythonMagick` some time ago. Please have a look and open a PR ;)

**Comment by AttilaVM** [comment]
I see. Ok I will do it. I just started with nix, so maybe I will have some questions.

**Comment by AttilaVM** [comment]
If I use the _--keep-failed_ flag with _nix-build_ it will keep its build directory, can I activate it as a nix environment, to try things out manually?

**Comment by FRidh** [comment]
You may prefer to use instead `nix-shell -A`, e.g. `nix-shell -A python3.pkgs.PythonMagick`. In that shell you can go through the phases manually but you'll likely want to run `genericBuild` there.

**Comment by AttilaVM** [comment]
Well it 22:14  and I'll have a bunch of work tomorrow, I will continue next day with reading the full nixpkgs manual and messing with examples.

**Comment by AttilaVM** [comment]
but I can run nix-shell only if I change the function arguments to

`with import <nixpkgs>{};`

and because of this nix-build will fail, becuase of missing arguments.

So it is ok the change the arguments fix the package and change it back?

**Comment by FRidh** [comment]
moved the bindings a4ed97daf0a7d594b01fe5f19a95dc13d427c75d
