### ISSUE TITLE
Update request: deno 1.41.3 → 1.42.3

### ISSUE THREAD

**Issue by donovanglover** [NixOS/nixpkgs#303604]
- Package name: deno
- Latest released version: 1.42.3
- Current version on the unstable channel: 1.41.3
- Current version on the stable/release channel: 1.38.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

https://deno.com/blog/v1.42

**Notify maintainers**

@06kellyjac

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 06kellyjac** [comment]
Hi @donovanglover 

I'll look into why there hasn't been a PR opened yet by the bot.
The update will probably only go into unstable, just to be clear upfront.
There will be a new stable release in the next month or so for `24.05`.

Also I can't edit your issue but your versions for unstable/stable are backwards :)

**Comment by winterqt** [comment]
> I'll look into why there hasn't been a PR opened yet by the bot.

https://r.ryantm.com/log/deno/2024-04-11.log, in case you didn't find it already.

> Also I can't edit your issue but your versions for unstable/stable are backwards :)

Fixed.
