### ISSUE TITLE
Package request: GitButler

### ISSUE THREAD

**Issue by johnbchron** [NixOS/nixpkgs#303673]
**Project description**

A Git client for simultaneous branches on top of your existing workflow.

**Metadata**

* homepage URL: https://gitbutler.com/
* source URL: https://github.com/gitbutlerapp/gitbutler
* license: FSL-1.1-MIT (Functional Source License, MIT Future License)
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
An issue for this already exists here:
https://github.com/NixOS/nixpkgs/issues/288567

**Comment by johnbchron** [comment]
Ah, apologies
