### ISSUE TITLE
Overriding ghcWithPackages doesn't seem to work anymore

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#30360]
I used to override nix-shell derivations in my config.nix to add things like hlint, cabal-install, etc. to shell environments for my projects. I did it like this:

``` nix
{
  haskellPackageOverrides = self: super: {
    ghcWithPackages = p: super.ghcWithPackages (f: p f ++ [ f.cabal-install f.hlint f.ghcid ]);
  };
}
```

This no longer affects shell environments and I can't figure out why.

cc @peti, I think you've worked a lot on the Haskell builder

**Comment by peti** [comment]
The override should work, but it's possible that the environment you're entering doesn't even use `ghcWithPackages`. To know for sure, I'd need the exact command line you're calling to enter the shell environment.

**Comment by peti** [comment]
Please let me know if this problem still exists.
