### ISSUE TITLE
vscodium breaks (doesn't function) on Nixpkgs 23.11

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#303702]
### Describe the bug
vscodium doesn't function on `nixos-23.11` and `release-23.11`, even with `--disable-extensions` flag.

### Steps To Reproduce
1. Run `nix run github:NixOS/nixpkgs/release-23.11#vscodium -- --disable-extensions` (current `release-23.11` is at ec877443d62ed5268c741656657d1319554a55f4) and see error.
2. Run `nix run github:NixOS/nixpkgs/nixos-23.11#vscodium -- --disable-extensions` and see error. (current `nixos-23.11` is at b2cf36f43f9ef2ded5711b30b1f393ac423d8f72)

### Expected behavior
VSCode runs correctly without error.

### Screenshots
![screenshot of a malfunction VSCodium window 20240413_040700](https://github.com/NixOS/nixpkgs/assets/44064051/c8c7905f-af6f-4339-95d8-7a7c5565b5d6)

### Notify maintainers
@Synthetica9 @bobby285271 @ludovicopiero

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
@Synthetica9 @bobby285271 @ludovicopiero

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.20240410.b2cf36f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/66iqv889530b6dnymabx41g9bhq0sijv-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ShamrockLee** [comment]
I don't know, but the issue persists after rolling back to previously know-to-work version of VSCodium.

**Comment by ShamrockLee** [comment]
Update: fixed by deleting the dot-files (`~/.vscode-oss` and `~/.config/VSCodium`).

**Comment by eclairevoyant** [comment]
This is a known electron issue for electron <28, kniwn to be solved by deleting `~/.config/<program>/GPUCache` (or wherever the GPUCache folder would be located)

**Comment by ShamrockLee** [comment]
> This is a known electron issue for electron <28, known to be solved by deleting `~/.config/<program>/GPUCache` (or wherever the GPUCache folder would be located)

Is it Nixpkgs-specific? I wonder if we should document it in Nixpkgs Manual.

**Comment by eclairevoyant** [comment]
> Is it Nixpkgs-specific?

No, it's a [chromium issue](https://issues.chromium.org/issues/40267041)
I don't think it makes sense to document known issues with older versions of individual packages.

**Comment by ShamrockLee** [comment]
Thank you very much for helping out!
