### ISSUE TITLE
Package request: sandbar

### ISSUE THREAD

**Issue by fccapria** [NixOS/nixpkgs#303806]
### Steps To Reproduce

1. build *sandbar* (a package that i wuold merge in nixpkgs)

### Build log

```
Running phase: buildPhase
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
client-header /stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
make: client-header: No such file or directory
make: *** [Makefile:18: xdg-shell-protocol.h] Error 127
```

### Additional context
Hi! I hope this is the right label for this issue..
I'm new in Nix and I'm trying to develop the Nix derivation of sandbar (a wayland bar for the river window manager).
During the build phase I encounter this error. I've built this software on nix without the derivation (using a nix-shell with the dependencies) and it worked. I don't know why I create the derivation there is this error.
I've added pkg-config, wayland, wayland-protocols and wayland-scanner (required for that line) but it doesn't work.

This is the line in the Makefile:
```
xdg-shell-protocol.h:
        $(WAYLAND_SCANNER) client-header $(WAYLAND_PROTOCOLS)/stable/xdg-shell/xdg-shell.xml $@
```
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.80, NixOS, 23.11 (Tapir), 23.11.5097.880992dcc006`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Please post the package expression that you wrote

**Comment by fccapria** [comment]
```
{ 
  lib,
  stdenv,
  fetchFromGitHub,
  pixman,
  fcft,
  pkg-config,
  wayland-protocols,
  wayland-scanner
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "sandbar";
  version = "v0.1";

  src = fetchFromGitHub {
    owner = "kolunmi";
    repo = "sandbar";
    rev = finalAttrs.version;
    hash = "sha256-uG+/e75s/OQtEotR+8aXTEjW6p3oJM8btuRNgUVmIiQ=";
  };

  nativeBuildInput = [
    pkg-config
    wayland-protocols
    wayland-scanner
  ];
  
  buildInput = [ pixman fcft ];
#  buildPhase = '' make '';
#  installPhase = '' make install '';
```

**Comment by eclairevoyant** [comment]
The builders are sensitive to naming but will not warn you about misspellings. `nativeBuildInput` is missing the `s` at the end, same with `buildInput`.

Also, ensure to sort the dependencies as per https://nixos.org/manual/nixpkgs/stable/#ssec-stdenv-dependencies

**Comment by eclairevoyant** [comment]
Alternatively, to save time aed give a good starting point, you might try using `nix-init` to generate a package expression.

**Comment by fccapria** [comment]
@eclairevoyant thank you!
Now the program builds perfectly. It was a pretty stupid mistake on my part.
Anyway I'll take a look at nix-init too, thanks again!
