### ISSUE TITLE
cannot install sqitch on macOS

### ISSUE THREAD

**Issue by efx** [NixOS/nixpkgs#30389]
## Issue description

I have tried installing sqitch-pg from nixpkg's master, but it conflicts with my other installs.

### Steps to reproduce
```
$ nix-env -i lastpass-cli
$ nix-env -i sqitch-pg
```
You should see something like the following error:
```
building path(s) ‘/nix/store/vcz9i6f8n9jdz5gpyyfw381q2k3ab10r-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 57.
collision between directory ‘/nix/store/nwsq208123ny2mx55j0cz6pfvhcyr59w-lastpass-cli-1.1.1/share’ and non-directory ‘/nix/store/f3ryiv8hqzmny4zclyrxl9xgjdmvrfy1-sqitch-pg-0.9996/share’ at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 57.
builder for ‘/nix/store/aa574ad8qxv96r0fzbn1rdrncnwvnh9q-user-environment.drv’ failed with exit code 2
```
I tried using the latest version of sqitch from cpan and the issue still occurs. See https://botbot.me/freenode/nixos/2017-10-13/?msg=92260474&page=5 for some initial debugging

## Technical details

* System: macOS 10.12.6 (16G29)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre117347.66f8512e4f
* Sandboxing enabled: false

**Comment by LnL7** [comment]
This isn't darwin specific, buildEnv doesn't know how what to do with `/share` because it's a broken symlink.
