### ISSUE TITLE
Unable to compile Ada code with Alire and GPRbuild

### ISSUE THREAD

**Issue by mrmagic223325** [NixOS/nixpkgs#303886]
### Describe the bug
I installed `alire`, `gnat`, and `gprbuild` through home-manager and created a new Alire crate with `alr init --bin hello`. I then tried building the crate with `alr build` which threw the error in the first attached screenshot. I did some experimenting to try to solve the issue myself but eventually got stuck on the second error message.

### Steps To Reproduce
1. Install `alire`, `gnat`, and `gprbuild` through home-manager
2. Create a new crate with `alr init --bin newcrate`
3. Compile the crate with `alr build`

### Expected behavior
The code should compile just fine.

### Screenshots
Default behavior: ![image](https://github.com/NixOS/nixpkgs/assets/76184901/c78e1259-d08e-4af6-9abd-e4aea3da6b19)
After selecting everything under `gprconfig`: 
![image](https://github.com/NixOS/nixpkgs/assets/76184901/a7f78720-6883-44c1-ad05-7bc3f511036b)
Using `nix-shell`: 
![image](https://github.com/NixOS/nixpkgs/assets/76184901/d085dedf-d5df-4b90-a93f-5afa5dfc4464)

### Additional context
Using `nix-shell -p alire gnat gprbuild` yields a working environment for compiling Ada code with Alire and crates created inside the nix-shell will compile fine while crates created outside of it return the same error.

### Notify maintainers

@sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05.20240329.d8fe5e6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sternenseemann** [comment]
Can you try reproducing these issues with just `gprbuild`? Also make sure to pass `-v` for a bit more information.

**Comment by mrmagic223325** [comment]
> Can you try reproducing these issues with just `gprbuild`? Also make sure to pass `-v` for a bit more information.

src/hello.adb
```ada
procedure Hello is
begin
    null;
end Hello;
```
and
hello.gpr
```ada
project Hello is
    for Source_Dirs use ("src");
    for Main use ("main.adb");
end Hello;
```
still fail to compile (`gprbuild -v -P hello.gpr`) with this error:
```
==============Messages for file: /home/fedora/Programming/Ada/hello/hello.gpr
     1. project Hello is
                |
        >>> no compiler for language "Ada", cannot compile "main.adb"
gprbuild: *** compilation phase failed
```
which doesn't happen anymore after selecting available compilers with `gprconfig` but leads to a new error:
```
==============Messages for file: /home/fedora/Programming/Ada/hello/hello.gpr
     1. project Hello is
                |
        >>> warning: there are no sources of language "C" in this project

     3.     for Main use ("main.adb");
                          |
        >>> "main.adb" is not a source of project "hello"
gprbuild: problems with main sources
```
I am a complete beginner with Ada or any tools relating to it so I don't know whether this is an actual problem with the package or me not using the tools correctly.

**Comment by sternenseemann** [comment]
What compilers are shown by gprconfig?

**Comment by mrmagic223325** [comment]
> What compilers are shown by gprconfig?

```
--------------------------------------------------
gprconfig has found the following compilers on your PATH.
Only those matching the target and the selected compilers are displayed.
   1. GCC-ASM for Asm in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 12.3.0
   2. GCC-ASM for Asm in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 12.3.0
   3. GCC-ASM for Asm in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 13.2.0
   4. GCC-ASM for Asm2 in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 12.3.0
   5. GCC-ASM for Asm2 in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 12.3.0
   6. GCC-ASM for Asm2 in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 13.2.0
   7. GCC-ASM for Asm_Cpp in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 12.3.0
   8. GCC-ASM for Asm_Cpp in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 12.3.0
   9. GCC-ASM for Asm_Cpp in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 13.2.0
  10. LD for Bin_Img in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 2.41
  11. LD for Bin_Img in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 2.41
  12. LD for Bin_Img in /nix/store/5ac6jr3asky426rc5qaxrf3wkhzpw1cm-binutils-wrapper-2.41/bin/ version 2.41
  13. LD for Bin_Img in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 2.41
  14. GCC for C in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 12.3.0
  15. GCC for C in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 12.3.0
  16. GCC for C in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 13.2.0
  17. G++ for C++ in /nix/store/s9h0d3wi03wz5ripp6j3627mgsp5h22d-user-environment/bin/ version 12.3.0
  18. G++ for C++ in /nix/store/v9jzdvzm880qa7fcd6glgh1vhmczfpwy-system-path/bin/ version 12.3.0
  19. G++ for C++ in /nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/ version 13.2.0
```

I've tried with both a combination of different ones and all at once but the results seemed to be the same.

**Comment by sternenseemann** [comment]
It seems like gprbuild doesn't find GNAT are you sure it is installed? gprbuild looks for `gnatmake`, so try running `gnatmake -v`. I can't reproduce this (though without home-manager).

Independent of that, I would not recommend installing development tools via your nixos configuration, home-manager or `nix-env`. Since the directory layout of Nix-based distributions is so different from the FHS, compilers and build managers struggle to find dependencies, standard libraries, tools etc. We usually have extra shell code and environment setups that are applied when using `nix-shell`, so it is always recommended to use that.

Outside of a derivaton/`nix-shell` it may or may not work – nixpkgs makes no promises here except for specialized wrappers like `python*WithPackages`.

Is there any specific reason why you can't use nix-shell?

**Comment by mrmagic223325** [comment]
> It seems like gprbuild doesn't find GNAT are you sure it is installed? gprbuild looks for `gnatmake`, so try running `gnatmake -v`. I can't reproduce this (though without home-manager).

I definitely have GNAT installed and have actually compiled Ada code with just `gnatmake`.

> Independent of that, I would not recommend installing development tools via your nixos configuration, home-manager or `nix-env`. Since the directory layout of Nix-based distributions is so different from the FHS, compilers and build managers struggle to find dependencies, standard libraries, tools etc. We usually have extra shell code and environment setups that are applied when using `nix-shell`, so it is always recommended to use that.
> 
> Outside of a derivaton/`nix-shell` it may or may not work – nixpkgs makes no promises here except for specialized wrappers like `python*WithPackages`.
> 
> Is there any specific reason why you can't use nix-shell?

I am a newish NixOS user so not having development tools available in any path on my system at any time is still something new to me. I will look into creating a flake for Ada development that I'll use with direnv though.

Besides that is there anything you are planning to do to make GPRbuild work when installed system-wide?
