### ISSUE TITLE
`peek`: cannot run

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#303884]
### Describe the bug
Cannot run `peek`. Exits immediately. No window appears. Terminal has no output.

### Steps To Reproduce
build `peek` from nixpkgs (master) and run `./result/bin/peek`.

### Expected behavior
Peek runs.

### Additional context
Result of `strace ./result/bin/peek`: https://pastebin.com/Mj0EHsHV

### Notify maintainers

@puffnfresh

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.6207.b2cf36f43f9e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
What DE are you using? Also do you get the same error when installing from 23.11?

**Comment by UlyssesZh** [comment]
GNOME on X11. The same with 23.11.

**Comment by kirillrdy** [comment]
works for me gnome nvidia x11

![image](https://github.com/NixOS/nixpkgs/assets/12160/484368ca-cf2f-47a2-bca4-17c7d69c3c24)

```
[kirillvr@tsutenkaku:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240408.c740c98`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/0b6mqpvbawn45av081jx1k9w1aws7bg9-source`

```

**Comment by UlyssesZh** [comment]
I found out the problem. The window is initialized at the top left corner, which is not visible for my monitor layout. The window is not shown in GNOME's overview interface either, so I mistakenly thought the window did not appear.
