### ISSUE TITLE
Update request: Appflowy 0.3.8 → 0.5.4

### ISSUE THREAD

**Issue by mobsenpai** [NixOS/nixpkgs#303892]
- Package name: Appflowy
- Latest released version: 0.5.4

- Current version on the unstable channel: 0.5.4
- Current version on the stable/release channel: 0.3.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** 
@DarkOnion0 

-----

Note for maintainers: Is it possible to update the app version for stable release also? I am sorry if this is not a valid request.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DarkOnion0** [comment]
Thanks for your report. I'm going to backport the change to the stable branch too 😁.

**Comment by mobsenpai** [comment]
Oh sweet, thank you so much.

**Comment by DarkOnion0** [comment]
Well, as you want. If you don't close it, I will configure the PR to automatically close the issue when merged. I think the later would be _"cleaner"_.

**Comment by mobsenpai** [comment]
#303905
