### ISSUE TITLE
DHCP fails on latest 17.09-small

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#30395]
## Issue description

On the latest nixos-17.09-small release dhcp configuration fails on my system. I have no explicit network configuration set, so it uses dhcpcd. Switching from a previous nixos version works until boot. In the journal I see (XX for privacy)

```
Oct 13 20:22:24 server dhcpcd[1130]: dev: loaded udev
Oct 13 20:22:24 server dhcpcd[1130]: enp10s0: waiting for carrier
Oct 13 20:22:24 server dhcpcd[1130]: libudev: received NULL device
Oct 13 20:22:24 server dhcpcd[1130]: libudev: received NULL device
Oct 13 20:22:25 server dhcpcd[1130]: libudev: received NULL device
Oct 13 20:22:27 server dhcpcd[1130]: enp10s0: carrier acquired
Oct 13 20:22:27 server dhcpcd[1130]: DUID 00:01:00:01:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX
Oct 13 20:22:27 server dhcpcd[1130]: enp10s0: IAID XX:XX:XX:XX
Oct 13 20:22:27 server dhcpcd[1130]: enp10s0: adding address fe80::XXXX:XXXX:XXXX:XXXX
Oct 13 20:22:27 server dhcpcd[1130]: libudev: received NULL device
Oct 13 20:22:28 server dhcpcd[1130]: enp10s0: soliciting an IPv6 router
Oct 13 20:22:28 server dhcpcd[1130]: dhcp_open: enp10s0: Cannot allocate memory
```

`free` shows over 7GB of free memory.

### Steps to reproduce

Boot to 17.09.1594.6b8dc0e9eb with "default" network options.

## Technical details

* System: 17.09.1594.6b8dc0e9eb (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1594.6b8dc0e9eb"
* Sandboxing enabled: yes

**Comment by Amarandus** [comment]
I can confirm this problem.
What I also noticed in my case is a name change of the network device (compared to the previous configuration on 17.03).
Earlier, it was `enp3s0`, now it is `ens3`. 
I am testing nixOS for a server configuration inside a qemu VM.

**Comment by fadenb** [comment]
@Amarandus regarding the name change see release notes: https://nixos.org/nixos/manual/release-notes.html#sec-release-17.09-incompatibilities 

I can confirm the issue. Just ran into it after upgrading from 17.03 to 17.09.
I replaced the interface in my config (enp0s3 to ens3), switched config and rebooted. After the reboot dhcpcd.service is not started. My static IPv6 configuration on the interface is working fine. If i start dhcpcd.service manually the IPv4 on the interface is configured as expected.

**Comment by Moredread** [comment]
Issue #30384 might be relevant, it also fails with a memory allocation error.

**Comment by sjau** [comment]
Works again on unstable.

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre117886.874a3c033c (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre117886.874a3c033c"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`

**Comment by Amarandus** [comment]
The problem seems to be gone away with `17.09.1609.a90e6c9399 (Hummingbird)`, at least for me.

**Comment by Moredread** [comment]
Yes, it  works on my server for a while now
