### ISSUE TITLE
Rename `wrapGAppsHook` to `wrapGAppsHook3`

### ISSUE THREAD

**Issue by DanielSidhion** [NixOS/nixpkgs#303921]
Created from a comment in https://github.com/NixOS/nixpkgs/pull/302599#issuecomment-2043417260.

There is a specific `wrapGAppsHook4` for GTK 4. `wrapGAppsHook` brings GTK 3, so renaming it would make it easier for users to understand which version of the GTK they're getting with the hook they're using.

According to the comment in the PR above, it might be best to wait until #291339 is merged to avoid conflicts.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by uninsane** [comment]
my understanding is that the eventual goal is to remove `gtk{3,4}` from `wrapGAppsHook` altogether. see the comments inside pkgs/build-support/setup-hooks/wrap-gapps-hook/default.nix:
```nix
  propagatedBuildInputs = [ makeWrapper ] ++ lib.optionals isGraphical [
    # TODO: remove this, packages should depend on GTK explicitly.
    gtk3
    librsvg
  ];
```

i'm not sure the precise path to get there has been elaborated. it could be:
1. replace `wrapGAppsHook` with explicit `wrapGAppsHook{3,4}` calls.
  the gtk4 half of that has already been done. the gtk3 part is what this issue would be about.
2. rename the existing `wrapGAppsNoGuiHook` -> `wrapGAppsHook`.
3. port `wrapGAppsHook{3,4}` users back to `wrapGAppsHook`.
4. delete the now unused `wrapGAppsHook{3,4}`.

**Comment by nyabinary** [comment]
Done :3
