### ISSUE TITLE
libreoffice: missing `coreutils` for usage with `firejail`

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#303980]
### Describe the bug
Copied from https://discourse.nixos.org/t/libreoffice-cannot-use-firejail-because-of-path-issue/43289 

configuration.nix
```
programs.firejail.enable = true;
programs.firejail.wrappedBinaries = {
	libreoffice = {
		executable = "${pkgs.lib.getBin pkgs.libreoffice-still}/bin/libreoffice";
		profile = "${pkgs.firejail}/etc/firejail/libreoffice.profile";
	};
};
```
After running libreoffice in terminal, this is some error output:
```
/nix/store/somehash-libreoffice-7.5.9.2/lib/libreoffice/program/soffice: line 51: dirname: command not found
/nix/store/somehash-libreoffice-7.5.9.2/lib/libreoffice/program/soffice: line 145: grep: command not found
/nix/store/somehash-libreoffice-7.5.9.2/lib/libreoffice/program/soffice: line 151: uname: command not found
/nix/store/somehash-libreoffice-7.5.9.2/lib/libreoffice/program/soffice: line 191: /nix/store/someotherhash-libreoffice-7.5.9.2-wrapped/bin/oosplash: No such file or directory
```
I think this is path issue in the soffice script but I do not know how to solve it.

### Additional context
Something similar has been solved for `brave` in https://github.com/NixOS/nixpkgs/pull/258463

### Notify maintainers
(pinging because of recent activity in regard to `libreoffice`)
@LeSuisse @sikmir @7c6f434c @dotlambda 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
I can make a PR, but I don't have the patience to build `libreoffice` locally, so someone have to test it.

**Comment by JohnRTitor** [comment]
Ok. Built successfully. Sending PR #304254
