### ISSUE TITLE
Network interface no longer configured by DHCP (17.09)

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#30405]
## Issue description
I upgraded a system from 17.03 to 17.09.
I replaced the interface name enp3s0 with ens3 in the configuration and ran `nixos-rebuild switch --upgrade`. I then rebooted the system.

Statically configured IPv6 is working fine but dhcpcd.service is not started resulting in no IPv4 configured on the ens3 interface.

At first I thought it might be the same as mentioned in #30395 but in that case dhcpcd.service is started and fails where on my system dhcpcd.service is not started at all.

I tried to explicitly configure DHCP for the interface but without any effect ( `networking.dhcpcd.enable` as well as `networking.interfaces.ens3.useDHCP`)

### Steps to reproduce
```
  networking = {
    hostName = "somehostname";
    domain = "some.tld";
    defaultGateway6 = { address = "fe80::1"; interface = "ens3"; };
    interfaces = {
      ens3 = {
        ip6 = [ { address = "2a01:4f8:YYYY:XXXX::2"; prefixLength = 64; } ];
      };
    };
    firewall = {
      allowPing = true;
      allowedTCPPorts = [ 80 443 8448 3478 3479 5349 5350 ];
      allowedUDPPortRanges = [ { from = 50000; to = 51000; } ];
    };
  };

```

## Technical details

* System: 17.09.1547.2231575a7d (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1547.2231575a7d"

**Comment by djahandarie** [comment]
I've also encountered the same issue (finally restarted today after upgrading to 17.09 months ago). Manually starting dhcpcd.service after boot works fine, it just doesn't start automatically. Did you end up making any progress into understanding why?

**Comment by fadenb** [comment]
Closing this issue as I have not have seen this behavior in more recent versions.
