### ISSUE TITLE
Build failure: gnupg (cross-compiling arm7l-linux on x86_64)

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#304125]
### Steps To Reproduce

* `$ nix build nixpkgs#pkgsCross.armv7l-hf-multiplatform.gnupg` (unsure if it's the exact reproduction, see https://github.com/NixOS/mobile-nixos/pull/708 for details)

### Build log

https://gist.github.com/Kreyren/b2667123acf63abde26e4b1327bacdce

```
...
configure:
***
*** It is now required to build with support for the
*** New Portable Threads Library (nPth). Please install this
*** library first.  The library is for example available at
***   https://gnupg.org/ftp/gcrypt/npth/
*** (at least version 1.2 (API 1) is required).
***
configure: error: 
***
*** Required libraries not found. Please consult the above messages
*** and install them before running configure again.
***
```

### Additional context

Encountered during contribution of samsung-serranove compatibility in mobile nixos: https://github.com/NixOS/mobile-nixos/pull/708

Reviewed by samueldr as nixpkgs issue. (https://matrix.to/#/!RjBlCIbsLDzHBIzmaA:nixos.org/$OZQRi0aBfXOomJ5vXcfAXUFwPtYBG61GRYpM9M09aRM?via=nixos.org&via=matrix.org&via=tchncs.de)

### Notify maintainers

@fpletz @vrthra

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[kreyren@pelagus:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.10-xanmod1, NixOS, 23.11 (Tapir), 23.11.20240328.219951b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - channels(raptor): `"home-manager-23.05.tar.gz, nixpkgs-23.05, nixpkgs-unstable-23.05"`
 - nixpkgs: `/nix/store/4a3qxnlq7r1gjwfjfqrizpf30hh22bz1-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by delroth** [comment]
https://github.com/NixOS/nixpkgs/pull/298001

**Comment by Kreyren** [comment]
> #298001 -- @delroth (https://github.com/NixOS/nixpkgs/issues/304125#issuecomment-2054245263)

It appears to fail on https://github.com/NixOS/nixpkgs/commit/ae22f8403a6aa4cc1bd30a0dbfb014187810af4e as well which includes changes from https://github.com/NixOS/nixpkgs/pull/298001

Build Logs:
* https://gist.github.com/Kreyren/69842bb2a2e5a2dc8ad97ac288945fb9
* https://gist.githubusercontent.com/Kreyren/85da49e28ae6d407af3f0bd884921ab8

You sure that `"GPGRT_CONFIG=${lib.getDev libgpg-error}/bin/gpgrt-config"` is something that the build system knows how to use on `arm7l-linux`?
