### ISSUE TITLE
MPD not running

### ISSUE THREAD

**Issue by Monocled004** [NixOS/nixpkgs#304282]
## Issue description
I tried setting up MPD using pipewire. NixOS got rebuilt without any issues but mpd.service doesn't start. I had Fedora 39 before NixOS and had the exact same problem.

## Technical details

Result of  **systemctl  status mpd.service**

mpd.service - Music Player Daemon
     Loaded: loaded (/etc/systemd/system/mpd.service; linked; preset: enabled)
    Drop-In: /nix/store/lq1g4cpwg7hsg2v3az77j1yhnn2dhfji-system-units/mpd.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Mon 2024-04-15 18:57:04 IST; 11s ago
TriggeredBy: ● mpd.socket
       Docs: man:mpd(1)
             man:mpd.conf(5)
    Process: 11182 ExecStartPre=/nix/store/1wqb7pw4j87fkf4hyydwbzzggdbylhrz-unit-script-mpd-pre-start/bin/mpd-pre-start (code=exited, status=217/USER)
         IP: 0B in, 0B out
        CPU: 526us
Apr 15 18:57:04 nixos systemd[1]: Starting Music Player Daemon...
Apr 15 18:57:04 nixos systemd[1]: mpd.service: Control process exited, code=exited, status=217/USER
Apr 15 18:57:04 nixos systemd[1]: mpd.service: Failed with result 'exit-code'.
Apr 15 18:57:05 nixos systemd[1]: Failed to start Music Player Daemon.`

Result of  **journalctl -xeu mpd.service**

Apr 15 18:57:04 nixos systemd[1]: mpd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit mpd.service has entered the 'failed' state with result 'exit-code'.
Apr 15 18:57:05 nixos systemd[1]: Failed to start Music Player Daemon.
░░ Subject: A start job for unit mpd.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit mpd.service has finished with a failure.
░░ 
░░ The job identifier is 4019 and the job result is failed.
Apr 15 19:03:08 nixos systemd[1]: Starting Music Player Daemon...
░░ Subject: A start job for unit mpd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit mpd.service has begun execution.
░░ 
░░ The job identifier is 4147.
Apr 15 19:03:08 nixos (re-start)[11353]: mpd.service: Failed to determine user credentials: No such process
Apr 15 19:03:08 nixos (re-start)[11353]: mpd.service: Failed at step USER spawning
/nix/store/1wqb7pw4j87fkf4hyydwbzzggdbylhrz-unit-script-mpd-pre-start/bin/mpd-pre-start: No such process
░░ Subject: Process /nix/store/1wqb7pw4j87fkf4hyydwbzzggdbylhrz-unit-script-mpd-pre-start/bin/mpd-pre-start
could not be executed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The process /nix/store/1wqb7pw4j87fkf4hyydwbzzggdbylhrz-unit-script-mpd-pre-start/bin/mpd-pre-start could
not be executed and failed.
░░ 
░░ The error number returned by this process is ERRNO.
Apr 15 19:03:08 nixos systemd[1]: mpd.service: Control process exited, code=exited, status=217/USER
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStartPre= process belonging to unit mpd.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 217.
Apr 15 19:03:08 nixos systemd[1]: mpd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit mpd.service has entered the 'failed' state with result 'exit-code'.
Apr 15 19:03:08 nixos systemd[1]: Failed to start Music Player Daemon.
░░ Subject: A start job for unit mpd.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit mpd.service has finished with a failure.
░░ 
░░ The job identifier is 4147 and the job result is failed.

**Comment by AkechiShiro** [comment]
Could you try to do this : 
```
systemctl daemon-reexec 
systemctl restart mpd
```

**Comment by AkechiShiro** [comment]
This configuration also might help : https://discourse.nixos.org/t/running-mpd-as-a-user-service/37746

**Comment by Monocled004** [comment]
Thank you for your assistance.

The problem was with my configuration.nix file. Where I had this declaration :
> services.mpd.user = "userRunningPipeWire";

which I didn't changed with my user name.
Sorry for inconvenience.
