### ISSUE TITLE
Build failure: python3.12-ipython-8.23.0

### ISSUE THREAD

**Issue by johnhamelink** [NixOS/nixpkgs#304268]
### Steps To Reproduce

1. build ipython-8.23.0 with python 3.12

### Build log

https://gist.github.com/johnhamelink/1b37095d2ffa6fde4b5e4101f30ac675

### Notify maintainers

@bjornfor
@fridh

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
john@sun:~/ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240411.8cb0044`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(john): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/gamy92vgx2ply9r9byzvrqm6ydix4l32-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bjornfor** [comment]
A test timeout? Report upstream? Or repro on another distro, then report upstream?
