### ISSUE TITLE
Poor errors on misconfigured cross-compilation

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#30431]
## Issue description

I've spent a fair amount of time trying to bring up cross-compilation environment with Nix. One issue that has come up again and again (and that I am struggling with currently) is errors along the lines of,

```
$ nix-env -f default.nix -i -A blockEng.linux --show-trace
installing ‘linux-4.9-arm-unknown-linux-gnueabihf’
error: while evaluating the attribute ‘configurePhase’ of the derivation ‘linux-4.9-arm-unknown-linux-gnueabihf’ at /home/ben/block-eng/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating the attribute ‘patches’ of the derivation ‘linux-config-4.9-arm-unknown-linux-gnueabihf’ at /home/ben/block-eng/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
attribute ‘crossDrv’ missing, at /home/ben/block-eng/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:92:18
```

Would it be possible to provide a more descriptive error message in this case?

### Steps to reproduce

Unfortunately I'm not yet sure what I'm doing wrong, so it's tough saying.

## Technical details

* System: Debian 9
* Nix version: `nix-env (Nix) 1.11.8`
* Nixpkgs version: 4a01ad0e9992d3b2a369ce21f9d9dee980f83581
* Sandboxing enabled: No

**Comment by bgamari** [comment]
Pinging @Ericson2314.

**Comment by bgamari** [comment]
In this case the following will reproduce the issue, although really the problem is more general than any one case,

```
$ cat test.nix
let
  crossSystem = {
    config = "arm-unknown-linux-gnueabihf";
    arch = "armv7";
    libc = "glibc";
    withTLS = true;
    openssl.system = "linux-generic32";
    platform = nixpkgsCross.pkgs.platforms.armv7l-hf-multiplatform // {
      baseKernelConfig = "xilinx_zynq_defconfig";
    };
  };

  nixpkgsCross = (import ./nixpkgs) { crossSystem = crossSystem; };
in nixpkgsCross
$ nix-env -f test.nix -i -A linux_4_9
installing ‘linux-4.9.56-arm-unknown-linux-gnueabihf’
error: attribute ‘crossDrv’ missing, at /home/ben/block-eng/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:92:18
(use ‘--show-trace’ to show detailed location information)
```

**Comment by bjornfor** [comment]
I think we need some info on how you set up that build environment. What's in default.nix?

**Comment by bjornfor** [comment]
Hehe, you beat me by less than a second!

**Comment by Ericson2314** [comment]
I told @bgamari on IRC, but I have some WIP stuff https://github.com/obsidiansystems/nixpkgs/tree/linux-cross-overhaul that should fix this.

**Comment by BjornMelgaard** [comment]
Hit this too, `--show-trace` not showing trace, so I dont understand what is wrong with my config

```sh
[root@nixos:~]# nixos-install --show-trace
error: value is a boolean while a set was expected, at /nix/store/vs92ysiygnlnk1yjrk1fzvb7dmf8i8hl-nixos-17.09.1880.ac2bb5684c/nixos/lib/modules.nix:231:62
(use ‘--show-trace’ to show detailed location information)

[root@nixos:~]# nixos-install 
error: value is a boolean while a set was expected, at /nix/store/vs92ysiygnlnk1yjrk1fzvb7dmf8i8hl-nixos-17.09.1880.ac2bb5684c/nixos/lib/modules.nix:231:62
(use ‘--show-trace’ to show detailed location information)
```

[gist](https://gist.github.com/BjornMelgaard/21065de44aff11be6bcc9ebf6f256d40)

**Comment by matthewbauer** [comment]
Fixed in master.
