### ISSUE TITLE
addErrorContext is undocumented

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#30438]
## Issue description

`builtins.addErrorContext` is mentioned in the 0.13 changelog section of the Nix manual, but nowhere else.

**Comment by Mic92** [comment]
Buildins are documented in the nix manual. Please open the issue there: https://github.com/NixOS/nix

**Comment by bgamari** [comment]
Continued at https://github.com/NixOS/nix/issues/1609.
