### ISSUE TITLE
Feature request: Print backtrace in `trace` output

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#30439]
## Issue description

The `builtins.trace` function is quite handy for probing state buried deep within a derivation. However, while trying to understand a cross-compiling bug I've seen my trace output printed multiple times. Without a stack backtrace (e.g. what `throw` would produce with `--show-trace`) this is quite difficult to interpret.

**Comment by Mic92** [comment]
This feature must be implemented in [https://github.com/NixOS/nix](nix) itself, we cannot fix it from nixpkgs. Please open an issue there.

**Comment by bgamari** [comment]
Yes, I suppose that makes sense. Thanks!

**Comment by bgamari** [comment]
Continued at https://github.com/NixOS/nix/issues/1610.
