### ISSUE TITLE
false overwrite of default cryptoModules

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#30446]
Here : 
https://github.com/NixOS/nixpkgs/blob/19997f01007efe3124219befaf6467c15521706e/nixos/modules/tasks/encrypted-devices.nix#L70

The cryptoModules get set to a list which is smaller than the default of `boot.initrd.luks.cryptoModules`. 

Also the example of the `keyFile` parameter is wrong. 
https://github.com/NixOS/nixpkgs/blob/19997f01007efe3124219befaf6467c15521706e/nixos/modules/tasks/encrypted-devices.nix#L39
it needs to be prefixed with `/mnt-root` like in the documentation explained.

proper example would be `example = "/mnt-root/root/.swapkey"`

**Comment by Mic92** [comment]
Fixed in master and 17.09 by https://github.com/NixOS/nixpkgs/pull/30477
