### ISSUE TITLE
tor-browser cannot install extension via browser

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#30443]
## Issue description
The latest tor-browser-bundle-bin implements and extensible mechanism that allows adding extensions via nix.
The current implementation replaces the `extensions` folder in the user's profile directory with a symlink to a `/nix/store` path.
The extensible mechanism comes at a cost of disallowing installation of extensions through the browser, the most common use-case.

Is there any possibility for a middle ground?
I'd like to still be able to install addons through the browser.

### Steps to reproduce
Launch tor-browser
Open add-ons menu
Search and try to install any extension

**Comment by unode** [comment]
Just to clarify, I was referring to https://github.com/NixOS/nixpkgs/blob/7bf191337ef46e5ca5f5860419c8a85c446a5a45/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix#L305

which seems to be absent from the source based build.

**Comment by joachifm** [comment]
The from-source version relies on a different mechanism for preloading extensions. I expect that using the same mechanism in the binary version would remove the need for the symlink.

**Comment by joachifm** [comment]
Works for me now

**Comment by unode** [comment]
Works for me too but I had to `rm .local/share/tor-browser/TorBrowser/Data/Browser/profile.default/extensions` first.

Thanks

**Comment by joachifm** [comment]
Ah, yeah I forgot about that ... I'll make a note to maybe add some logic to remove the symlink if it exists.
