### ISSUE TITLE
Update request: rnnoise 2021-01-22 → 0.2

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#304433]
- Package name: rnnoise
- Latest released version: 0.2

- Current version on the unstable channel: 2021-01-22
- Current version on the stable/release channel: 2021-01-22

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@nh2 

-----

Note for maintainers: Please tag this issue in your PR.

https://gitlab.xiph.org/xiph/rnnoise/-/tree/v0.2
https://github.com/xiph/rnnoise/releases/tag/v0.2

Tried building with

```diff
-stdenv.mkDerivation (rec {
+stdenv.mkDerivation (finalAttrs: {
   pname = "rnnoise";
-  version = "2021-01-22";
+  version = "0.2";
 
   src = fetchFromGitHub {
     owner = "xiph";
     repo = "rnnoise";
-    rev = "1cbdbcf1283499bbb2230a6b0f126eb9b236defd";
-    sha256 = "1y0rzgmvy8bf9a431garpm2w177s6ajgf79y5ymw4yb0pik57rwb";
+    rev = "refs/tags/v${finalAttrs.version}";
+    sha256 = "sha256-Qaf+0iOprq7ILRWNRkBjsniByctRa/lFVqiU5ZInF/Q=";
   };
```

but it got a missing file.

```
       > In file included from src/denoise.c:43:
       > src/rnn.h:31:10: fatal error: rnnoise_data.h: No such file or directory
       >    31 | #include "rnnoise_data.h"
       >       |          ^~~~~~~~~~~~~~~~
       > compilation terminated.
       > make[1]: *** [Makefile:749: src/dump_features-denoise.o] Error 1
       > make[1]: Leaving directory '/build/source'
       > make: *** [Makefile:491: all] Error 2
```

There’s also warning about not using SSE3/AVX/AVX2, but Nix only supports the bottom of the barrel, common x86 instructions, but I usually compile this one out with some flags.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by DarthPJB** [comment]
https://github.com/xiph/rnnoise/pull/219#issuecomment-2021761517

**Comment by JohnRTitor** [comment]
Perhaps it can be fetched using fetchurl/fetchpatch?

**Comment by kilianar** [comment]
You're correct. The relevant file is retrieved in the script [download_model.sh](https://github.com/xiph/rnnoise/blob/main/download_model.sh). It fetches a single file from the URL `https://media.xiph.org/rnnoise/models/rnnoise_data-${version}.tar.gz`, where the version is extracted from the file [model_version](https://github.com/xiph/rnnoise/blob/main/model_version), currently set to `0b50c45`. Hence, we can emulate the download script and execute something similar to:

```nix
model_version = "0b50c45";
model = fetchurl {
  url = "https://media.xiph.org/rnnoise/models/rnnoise_data-${model_version}.tar.gz";
  hash = "sha256-SsgcXAiE7EvVkHAmqq4WIJt7ds2df3GvWCCUovmPS0M=";
};

preBuild = ''
  tar xvomf $model
'';
```

**Comment by JohnRTitor** [comment]
Made a PR #305348, but still having trouble designing a proper update script.
