### ISSUE TITLE
Can't login to sync in LibreWolf

### ISSUE THREAD

**Issue by awebeer256** [NixOS/nixpkgs#304575]
### Describe the bug
When attempting to enable syncing in LibreWolf, the process of logging into your Firefox account is broken.

### Steps To Reproduce

0. Have a Firefox account
1. Install the `librewolf` nix package.
2. Run LibreWolf.
3. Go to `about:profiles`, create a new profile, and launch it.
4. Go to `about:config` and set `identity.fxaccounts.enabled` to `true` if it isn't already.
5. Go to `about:preferences#sync`, and click the button to sign in to enable syncing.
6. Enter your Firefox account email address and click the button to proceed.
7. Enter your Firefox account password and click the button to proceed.

### Expected behavior
The login process should complete after a few seconds at most.

### Actual behaviour
The page just waits forever.

### Screenshots
[None provided]

### Additional context

<details><summary>JavaScript console output</summary>

```
(Glean.core.Pings.Maker) Storage for deletion-request empty. Ping will still be sent. log.js:15:23
(Glean.core.Upload.PingUploadManager) Ping 64ffa321-3fd6-4082-82b1-9347f1aa7ae6 successfully sent 200. log.js:15:23
Working… logger.js:69:29
    error logger.js:69
    captureError error-utils.js:63
    logError connect_another_device.js:25
    C confirm_reset_password.js:77
    _t jsonp chunk loading:13
    r jsonp chunk loading:33
    _workingTimeout index.js:109
    n sign_in_recovery_code.js:46
    (Async: setTimeout handler)
    setTimeout sign_in_recovery_code.js:45
    i index.js:107
    validateAndSubmit account-suggestion-mixin.js:60
    (Async: promise callback)
    validateAndSubmit account-suggestion-mixin.js:58
    invokeHandler connect_another_device.js:204
    r index.js:80
    (Async: promise callback)
    r index.js:80
    onFormSubmit account-suggestion-mixin.js:32
    invokeHandler connect_another_device.js:204
    r index.js:138
    jQuery 2
Response not received for: fxaccounts:can_link_account logger.js:72:35
    error logger.js:72
    timeout duplex.js:35
    (Async: setTimeout handler)
    add duplex.js:33
    request duplex.js:152
    request duplex.js:142
    request state-machine.js:7
    (Async: promise callback)
    request state-machine.js:7
    beforeSignIn state-machine.js:19
    invokeBrokerMethod connect_another_device.js:244
    signIn ready.js:24
    submit tooltip.js:101
    _submitForm avatar-mixin.js:45
    (Async: promise callback)
    _submitForm avatar-mixin.js:40
    invokeHandler connect_another_device.js:204
    o index.js:186
    (Async: promise callback)
    o index.js:186
    invokeHandler connect_another_device.js:204
    i index.js:112
    (Async: promise callback)
    i index.js:111
    validateAndSubmit account-suggestion-mixin.js:60
    (Async: promise callback)
    validateAndSubmit account-suggestion-mixin.js:58
    invokeHandler connect_another_device.js:204
    r index.js:80
    (Async: promise callback)
    r index.js:80
    onFormSubmit account-suggestion-mixin.js:32
    invokeHandler connect_another_device.js:204
    r index.js:138
    jQuery 2
```
</details>

### Notify maintainers

@squalus 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5648.44733514b72e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by HammyHavoc** [comment]
Seeing this problem too.

**Comment by awebeer256** [comment]
That doesn't work for me.

**Comment by James-McK** [comment]
having the same issue :/
if i try to sign in to accounts.firefox.com directly it works, but if i try to sign in to sync it waits forever and just displays "Working..."
only seems to be an issue on nixos

**Comment by v4rakh** [comment]
Can confirm that it's not working here as well. Restarting or reopening doesn't make it work either. :-(

**Comment by squalus** [comment]
I haven't tested it, but I suspect #337061 will fix this after going to the Librewolf settings pane and checking "Enable Firefox sync"

**Comment by squalus** [comment]
I confirmed that #337061 fixes this.
- Enabled Firefox Sync in the Librewolf settings pane
- Restarted the browser
- Confirmed that I was able to log in with a Mozilla account in the Sync settings panel
