### ISSUE TITLE
Plasma 6 packages do not handle webp or avif image formats

### ISSUE THREAD

**Issue by chermnyx** [NixOS/nixpkgs#304523]
### Describe the bug

Multiple Plasma 6 packages cannot use webp or avif images

So far I've found the following problems:
- Dolphin does not show previews for webp images
- Cannot use a webp or avif image as a wallpaper
- Spectacle offers an option to save image as a webp image or avif image; but selecting this options results in error in Spectacle 

Probably there are other packages affected by the same issue

The problem is similar to https://github.com/NixOS/nixpkgs/issues/292375

### Expected behavior
Plasma 6 apps should handle supported image formats other than .jpg and .png

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/27727194/c7d7a447-4a45-4fc3-81bb-83a50e7e7e5a)

### Notify maintainers

@k900

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4-zen1, NixOS, 24.05 (Uakari), 24.05.20240412.cfd6b5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/yy5l09gfsagkv8rswblknmsjc2gyr20d-source`
```

nixpkgs from `flakes.lock`: 
```json
"nixpkgs": {
  "locked": {
    "lastModified": 1712963716,
    "narHash": "sha256-WKm9CvgCldeIVvRz87iOMi8CFVB1apJlkUT4GGvA0iM=",
    "owner": "nixos",
    "repo": "nixpkgs",
    "rev": "cfd6b5fc90b15709b780a5a1619695a88505a176",
    "type": "github"
  },
  "original": {
    "owner": "nixos",
    "ref": "nixos-unstable",
    "repo": "nixpkgs",
    "type": "github"
  }
},
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lboklin** [comment]
Same problem for Krita plugins (python scripts), in particular the [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion/issues/582) plugin.

**Comment by K900** [comment]
You probably want to install qtimageformats globally, I'm not sure adding it to every single place where it could potentially be used is worth it.

**Comment by lboklin** [comment]
> You probably want to install qtimageformats globally, I'm not sure adding it to every single place where it could potentially be used is worth it.

But that wouldn't solve its absence from Krita's python environment, surely?

**Comment by K900** [comment]
It should, since it's just a Qt plugin.

**Comment by K900** [comment]
If that Krita plugin can't work without it, then we need to think about how to propagate that dependency to Krita _if_ the plugin is used. For Dolphin and such, we can't really expect to add every single image format to every single program that may want to display it.

**Comment by lboklin** [comment]
I agree that it would be better for scripts to be packaged and their dependencies propagated, but Qt applications that are heavily centred around image handling and support custom scripts I think should be packaged with a reasonable set of libraries available at runtime. Common image formats such as webp are likely to appear in custom scripts, so unless there are plans to package python script plugins (and not just binary plugins), a generous python environment would provide a better UX.

**Comment by chermnyx** [comment]
> You probably want to install qtimageformats globally, I'm not sure adding it to every single place where it could potentially be used is worth it.

Maybe it should be installed automatically when `services.desktopManager.plasma6.enable` is `true`?

**Comment by K900** [comment]
We could do that, yeah. Do you want to submit a PR?

**Comment by danwdart** [comment]
This also appears in gwenview not showing heif files despite it supposedly being compiled with qtimageformats - does qtimageformats have to be compiled differently?

**Comment by toast003** [comment]
Also an issue for the media player applet when playing youtube videos, since the thumbnails are webp images

**Comment by fin444** [comment]
Trying to reproduce the specific things mentioned in this thread, on unstable `24.11.20241105.4aa3656`:

* I can produce thumbnails for AVIF and HEIF/HEIC, but need `qtimageformats` for WEBP.
* I can use AVIF as wallpaper, but not WEBP, even with `qtimageformats`. It seems like they aren't considered "media files" by KDE, potentially upstream issue?
* I can save AVIF and WEBP images from Spectacle without issue.
* I can see Youtube thumbnails in the media player applet when playing on Chromium.

As far as I can tell, adding `qtimageformats` should allow for improved WEBP support, but aside from that it will have limited benefits according to the [wiki page](https://doc.qt.io/qt-6/qtimageformats-index.html). Formats like AVIF and HEIF are provided by `kimageformats` instead, which is already included in the environment when `plasma6` is enabled.

https://github.com/NixOS/nixpkgs/blob/4aa36568d413aca0ea84a1684d2d46f55dbabad7/nixos/modules/services/desktop-managers/plasma6.nix#L75

That said, I don't see a reason not to include `qtimageformats` as well.
