### ISSUE TITLE
Lisp modules - removal of previous variants

### ISSUE THREAD

**Issue by Uthar** [NixOS/nixpkgs#304656]
Hi @NixOS/lisp .

The proposal is the following: to remove both `pkgs/development/lisp-modules-obsolete` and `pkgs/development/lisp-modules-new-obsolete`.

Code in `pkgs/development/lisp-modules-obsolete` contains a packaging framework based on a `common-lisp.sh` wrapper. It's available as the `lispPackages` attribute, among others. It was marked for removal in version 23.05 "Stoat", because another framework was accepted (see thread: https://github.com/NixOS/nixpkgs/pull/218870). That one uses `makeWrapper` and added a chapter to the nixpkgs manual. It's available as `sbcl.pkgs` and `sbcl.withPackages`, among others. Code in `pkgs/development/lisp-modules-new-obsolete` is a leftover prototype of that (see thread: https://github.com/NixOS/nixpkgs/pull/170149).

Removing these should decrease the size of nixpgks tarball by 497 KiB, which was measured by comparing these two tarballs: [first](https://github.com/uthar/nixpkgs/archive/lisp-remove-old-variants.tar.gz), [second](https://github.com/uthar/nixpkgs/archive/master.tar.gz). On the other hand, removal will break current setups. Also, the deprecation notice can be considered "hidden" deep inside of 23.05 release notes (there was no explicit section for deprecations as in e.g. 23.11). It was also not specific about what exactly will be removed, and use of the deprecated attributes did not start printing warnings.

Please comment if you agree that these should be removed. If so, below are three possible ways to achieve that. Do you see other approaches? 

1. Replace the lispPackages and similar attributes with a runtime warning - schedule removal step for a future release.

   (Reason to do that is to communicate the deprecation better than in 23.05. On the other hand, if there is zero users, it's not necessary.)

2. Remove lisp-modules-obsolete and lisp-modules-new-obsolete directories. Replace the lispPackages and similar attributes with a runtime error.

   (Reason to do that is to communicate (in addition to the release note) what should be used instead of the removed attributes.)

3. Remove lisp-modules-obsolete and lisp-modules-new-obsolete directories. Entirely remove the lispPackages and similar attributes from all-packages.nix.

   (Reason to do that is to remove as much code as possible.)

**Comment by 7c6f434c** [comment]
I think 3 is pointless because a throw for 2 — in aliases.nix where only renamings and removals live — is cheap. Well, technically a proper implementation of 2 does remove all the relevant code from all-packages.nix anyway…

**Comment by nagy** [comment]
I am in favor of the removal of these two directories and I would consider a replacement with a runtime error in combination with a release note ( maybe only for the next release ) a feasible approach.

**Comment by 7c6f434c** [comment]
As I have checked and merged the PR from @Uthar —the author of this issue, I am closing this as done.

**Comment by tazjin** [comment]
fwiw, this showed up as a surprise change for TVL, breaking a huge amount of packages in CI when we tried to update the build. We have our own Common Lisp infrastructure, but (used to) use the `src` attributes of things in `lispPackages`.

For breaking a whole ecosystem it would be nice if deprecation warnings were around at least for a little while before the breakage ... :(

**Comment by 7c6f434c** [comment]
We were possibly somewhat too optimistic that people read the 23.05 release notes.

**Comment by tazjin** [comment]
> We were possibly somewhat too optimistic that people read the 23.05 release notes.

We track nixos-unstable, and the usual expectation is that for things like this some deprecation warnings show up during evaluation and can be acted on before things break completely. This is very often not the case in nixpkgs, though.

**Comment by 7c6f434c** [comment]
It doesn't help that passing this through the aliases is often not trivial (the underlying code is different, after all), and having a deprecated package reachable from the toplevel throw a warning is simply not allowed (Nixpkgs tarball CI job at Hydra forbids it)…
