### ISSUE TITLE
Update the version of Terminator terminal to 1.91 up from 1.0

### ISSUE THREAD

**Issue by galanakis** [NixOS/nixpkgs#30463]
## Issue description

The package Terminator is in version 1.0, but the latest version in launchpad is 1.91.

Link to package
https://launchpad.net/terminator/gtk3/1.91/+download/terminator-1.91.tar.gz

## Technical details
* Nix version: 17.09

## "Terminator" - Package maintainers 
Bjørn Forsman <bjorn.forsman@gmail.com>, Robin Gloster <mail@glob.in>, Florian Friesdorf <flo@chaoflow.net>

**Comment by peterhoeg** [comment]
If you want to take a stab a PR, that would great - we're here to help!

**Comment by rinaldus** [comment]
I made PR.
https://github.com/NixOS/nixpkgs/pull/34218

**Comment by Mic92** [comment]
pr was merged.
