### ISSUE TITLE
kitty 0.34.0 causing segfault on Hyprland (unstable)

### ISSUE THREAD

**Issue by meirisoda** [NixOS/nixpkgs#304662]
### Describe the bug
After updating my system, launching kitty results in:
` [1]    4976 segmentation fault (core dumped)  kitty`
Updated to kitty 0.34.0 #304261 

Also mentioned in PR above:
> This seems to be segfaulting on Hyprland for me. I don't know if I should open a bug report for this or not.

_Originally posted by @YaroKasear in https://github.com/NixOS/nixpkgs/issues/304261#issuecomment-2059652880_
            
**_Edit:_
I am using nixpkgs's Hyprland, which is v0.38.1**

### Steps To Reproduce
1. Be on unstable branch. 
2. Update packages/flake.  
3. Launch kitty. 

### Expected behavior
kitty should launch. 

### Notify maintainers
@tex 
@rvolosatovs 
@Luflosi 
@adamcstephens 
@kashw2

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - host os: `Linux 6.8.6, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source`

```

**Comment by kashw2** [comment]
I'm unable to reproduce this on Hyprland 0.39.0 @ 79a139c9495568f69dd995bce1ca579247a98a17 and on Kitty 0.34.0

![image](https://github.com/NixOS/nixpkgs/assets/15855440/c7563ca6-958d-44a2-b9a4-7d2aab9f1c75)

Are you able to run `strace kitty` and post it's output?

**Comment by meirisoda** [comment]
`hyprctl version` gives me v0.38.1 - I'm using hyprland using `wayland.windowManager.hyprland.enable` on home-manager.

**Comment by JohnRTitor** [comment]
Also using Hyprland, not segfaulting here. But looks like the firacode-bold font that used to be applied, does not apply anymore?

**Comment by JohnRTitor** [comment]
Also using Hyprland, not segfaulting here. But looks like the firacode-bold font that used to be applied, does not apply anymore?

**Comment by JohnRTitor** [comment]
> `hyprctl version` gives me v0.38.1 - I'm using hyprland using `wayland.windowManager.hyprland.enable` on home-manager.

Can you try with the latest flake? It's using 39.0.

**Comment by meirisoda** [comment]
It's not exactly working, I've tried many different ways (enabling and defining it with just `programs.hyprland` and disabling home-manager's enable; using both; using just home manager and defining the package etc), but it always reverts back to a default config. There was one time it also mentioned segfault on the bottom text. I was also unable to verify the version. 
kitty did not open on any of these times. 
It is imported properly into my flake and hyprland.nix file (which includes my home-manager options that I use to configure hyprland).

**Comment by Kyesarri** [comment]
I've found using home-manager with 

```
home-manager.users.user.wayland.windowManager.hyprland = {
          extraConfig = ''
          source = /foo/bar.conf
          '';
          };
```
allows me to have a custom config file elsewhere (in my nix git).

https://github.com/Kyesarri/nixos/blob/master/home/hypr/default.nix#L34

**Comment by hweissi** [comment]
I had the same issue, with kitty 0.34.4 and hyperland from commit `82222342f10a7eff0ec9be972153e740d0f95213`.

For me, removing `background_blur 1` from my kitty config fixed the issue.
Maybe it's connected to having 2 different blurs (from kitty and hyprland) enabled at the same time.

**Comment by meirisoda** [comment]
This solved the issue! I had noise on in my hyprland config.

**Comment by Dip-beep-system** [comment]
for me everything is normal till every single minute there is shutter and frame drop to 5fps, in every single minute costantly, after a moment its back to normal, this is irritating when i want watch some video or chatting
