### ISSUE TITLE
Documentation for akkoma fails to build, failing the entire NixOS system

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#304604]
### Describe the bug
On NixOS 23.11 (rev 69be1d097dd9a8422cfc4e89811304fb40f22626), documentation fails to evaluate available options for Akkoma, failing the build.

### Steps To Reproduce
1. `nix repl`
2. `:lf github:nixos/nixpkgs/69be1d097dd9a8422cfc4e89811304fb40f22626`
3. `nixos = lib.nixosSystem { system = builtins.currentSystem; modules = [ ({ config, pkgs, lib, ... }: { fileSystems."/" = { device = "/dev/sda1"; fsType = "btrfs"; }; boot.loader.grub.device = "/dev/sda"; }) ]; }`
4. `:b nixos.config.system.build.toplevel`

### Expected behavior
System should build.

### Screenshots
n/a

### Additional context
It's a bit strange to see this on the stable branch. Perhaps a botched backport? A bisection would be nice to do. Rev 73844014f48f8f968f98366b33bbdcf693d6d407 doesn't seem to exhibit this problem, so it's a nice starting point for a bisection.

### Notify maintainers
Akkoma maintainers: @illdefined @tcmal

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by winterqt** [comment]
Fixed by #304556.
