### ISSUE TITLE
ocamlPackages.csv - download link invalid (17.09)

### ISSUE THREAD

**Issue by ibor** [NixOS/nixpkgs#30476]
ocamlPackages.csv-1.7 in nixos-17.09 cannot be installed due to a deprecated source URL.
I could not find a valid download URL for 1.7, but 2.0 (which is in unstable) works fine.
Should this be bumped?

### Steps to reproduce
nix-shell -p ocamlPackages.csv -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.09.tar.gz

[...]
trying https://math.umons.ac.be/anum/software/csv/csv-1.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
[...]

**Comment by Mic92** [comment]
This github repo also seems to provide csv-1.7: https://github.com/Chris00/ocaml-csv

**Comment by ibor** [comment]
https://github.com/Chris00/ocaml-csv/releases lists source and release archives for most versions. For 1.7 it only provides the source archive (with a different checksum). That archive lacks e.g. setup.ml, which is used in our configuration phase. I asked the maintainer whether he can (re-)publish the original tarball: https://github.com/Chris00/ocaml-csv/issues/20

**Comment by ibor** [comment]
Okay, @Chris00 already added a new tarball to the release page:
https://github.com/Chris00/ocaml-csv/releases/download/1.7/csv-1.7.tar.gz

The checksum has changed, but the build seems to work.

```
url = https://github.com/Chris00/ocaml-csv/releases/download/1.7/csv-1.7.tar.gz;
sha256 = "cf59cc44204dd91854537d1fbfe4e23dd8a9ef962c2ee18cc759106d9d703a7b";
```

**Comment by Mic92** [comment]
Can you make a pull request?

**Comment by ibor** [comment]
Pull request: https://github.com/NixOS/nixpkgs/pull/30570

**Comment by Zimmi48** [comment]
It seems that this issue has been fixed and should be closed.
