### ISSUE TITLE
Build failure: pdfpc

### ISSUE THREAD

**Issue by samueltardieu** [NixOS/nixpkgs#304729]
### Steps To Reproduce

1. build *pdfpc*

### Build log

```
/build/source/build/src/classes/renderer/markdown.c: In function 'pdfpc_renderer_md_render':
/build/source/build/src/classes/renderer/markdown.c:191:20: error: variable or field 'flags' declared void
  191 |         mkd_flag_t flags = 0U;
         |                    ^~~~~
```

### Notify maintainers

@pSub 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240408.4cba8b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/home/sam/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wentasah** [comment]
I put together a fix. See #304885 and https://github.com/pdfpc/pdfpc/pull/716.
