### ISSUE TITLE
NixOS testing framework does not log stdout

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#30478]
## Issue description
I noticed that the NixOS testing framework does not log stdout from commands in testScript. It only logs stderr. What is the reason for this? Seems to me like logging stdout too is a good idea.

1. It would have made it obvious that the installer tests were sometimes hanging due to "parted" asking for user input (ref. 0ff4bb5f875afe8eb208bbabb3f52dc29539d2bc)
2. It might eliminate all the manual redirection currently being done: ```git grep ">&2" nixos/tests``` (I presume this is simply a workaround due to how things work today)

Thoughts?

**Comment by edolstra** [comment]
This is intentional, because stdout can be used by the caller (e.g. `my $output = $machine->succeed("...")`). So it shouldn't be redirected to a log.

**Comment by bjornfor** [comment]
Would it be possible to use a "tee"? (So stdout would be logged but still available to the caller.)

Or to put it differently, why is stderr logged? The caller might want to capture stderr too?

**Comment by edolstra** [comment]
Because stderr is for logging :-) That's just the interface here: if you want to process the output of a command, you send it to stdout, otherwise you send it to stderr.

**Comment by bjornfor** [comment]
I find that interface unintuitive. I wish there was a separate command to extract stdout/stderr from a command and into perl, and that succeed() and fail() simply logged both stdout/stderr. Oh well :-)
