### ISSUE TITLE
Build failure: limine

### ISSUE THREAD

**Issue by mahmoud-moursy** [NixOS/nixpkgs#304746]
### Steps To Reproduce

1. `nix-build https://github.com/NixOS/nixpkgs/archive/master.tar.gz --attr limine` (behaviour is the same when trying to `nix-shell -p limine`)
2. Fails finding a riscv64 cross compiler toolchain.

### Build log
https://gist.github.com/T-O-R-U-S/0ed1610aeb91216fd688153d67799940

### Additional context

It asks for a RISC-V compiler because the package is configured with the `--enable-all` flag, so it fails to compile if any architecture is missing. Can be worked around by just enabling it for the platform that you are targeting, so long as that isn't RISC-V...

P.S: I only tried with the `--enable-x86_64` flag, and it seems to compile alright with that, but not with RISC-V.

### Notify maintainers

@48cf
@phip1611 

Thank you.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.0.0, macOS 14.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 48cf** [comment]
I can't reproduce the failure by running `nix-build https://github.com/NixOS/nixpkgs/archive/master.tar.gz --attr limine` on my x86-64 Linux virtual machine and I currently don't have an aarch64/risc-v Linux virtual machine set up to test it on. Perhaps it is related to you trying to build it on macOS? I can't test that very easily as I don't use Nix on macOS, but I will try building Limine manually. Could you also post the full output of `nix-store -l /nix/store/gf6cml15s4qqvm2j59pimda9ir727jgm-limine-7.3.1.drv` as suggested by the log?

**Comment by T-O-R-U-S** [comment]
@48cf https://gist.github.com/T-O-R-U-S/bee8f950577be5f08fc0d351197f049f here it is

**Comment by surfaceflinger** [comment]
```
nat@blahaj [~] $ nix shell nixpkgs#pkgsCross.riscv64.limine
error: builder for '/nix/store/4zryy3f1xv67xlzflar4dasa5cvasr82-limine-riscv64-unknown-linux-gnu-7.3.1.drv' failed with exit code 1;
       last 25 log lines:
       > checking for inttypes.h... yes
       > checking for stdint.h... yes
       > checking for strings.h... yes
       > checking for sys/stat.h... yes
       > checking for sys/types.h... yes
       > checking for unistd.h... yes
       > checking for stdint.h... (cached) yes
       > checking for stddef.h... yes
       > checking for stdbool.h... yes
       > checking for limits.h... yes
       > checking for inttypes.h... (cached) yes
       > checking for stdio.h... (cached) yes
       > checking for stdlib.h... (cached) yes
       > checking for string.h... (cached) yes
       > checking for clang (i686)... yes
       > checking for ld.lld (i686)... yes
       > checking for llvm-objcopy (i686)... no
       > checking for i686-elf-gcc (i686)... no
       > checking for riscv64-unknown-linux-gnu-gcc (i686)... yes
       > checking for riscv64-unknown-linux-gnu-ld (i686)... yes
       > checking for riscv64-unknown-linux-gnu-objcopy (i686)... yes
       > checking for riscv64-unknown-linux-gnu-objdump (i686)... yes
       > checking for riscv64-unknown-linux-gnu-readelf (i686)... yes
       > checking for gcc (i686)... no
       > error: could not find any valid toolchain for target 'i686'
       For full logs, run 'nix log /nix/store/4zryy3f1xv67xlzflar4dasa5cvasr82-limine-riscv64-unknown-linux-gnu-7.3.1.drv'.
```

yeah, so if `--enable-all` turns on ALL architectures then I don't think this is something desirable in nix.

the regular llvmPackages can target multiple triplets, while the one used in pkgsCross targets just one.

**Comment by T-O-R-U-S** [comment]
I did a bit more research into building Limine's tools, the `--enable-*` options enable UEFI or BIOS, but are NOT responsible for architectures. Weirdly enough, I get the same i686 error (that I wasn't getting before?) when building it using the `nix develop` env.

**Comment by T-O-R-U-S** [comment]
```nix
{
  pkgs ? import <nixpkgs> { },
  # Helpers
  stdenv ? pkgs.stdenv
, fetchurl ? pkgs.fetchurl
, lib ? pkgs.lib
, # Dependencies
  llvmPackages ? pkgs.llvmPackages
, mtools ? pkgs.mtools
, nasm ? pkgs.nasm
}:

let
  version = "7.3.1";
in
# The output of the derivation is a tool to create bootable images using Limine
# as bootloader for various platforms and corresponding binary and helper files.
stdenv.mkDerivation {
  inherit version;
  pname = "limine";
  # We don't use the Git source but the release tarball, as the source has a
  # `./bootstrap` script performing network access to download resources.
  # Packaging that in Nix is very cumbersome.
  src = fetchurl {
    url = "https://github.com/limine-bootloader/limine/releases/download/v${version}/limine-${version}.tar.gz";
    sha256 = "sha256-xlOBBb281W9QT5Fv2Hgw/eyh7K3oyaNY1yU6WktbFro=";
  };

  nativeBuildInputs = [
    llvmPackages.bintools
    # gcc is used for the host tool, while clang is used for the bootloader.
    llvmPackages.clang
    llvmPackages.lld
    mtools
    nasm
  ];

  configureFlags = [
    "--enable-bios-cd"
    "--enable-uefi-x86_64"
  ];

  installFlags = [ "destdir=$out" "manprefix=/share" ];

  outputs = [ "out" "doc" "dev" "man" ];

  meta = with lib; {
    homepage = "https://limine-bootloader.org/";
    description = "Limine Bootloader";
    # Caution. Some submodules have different licenses.
    license = [
      licenses.bsd2 # limine, flanterm
      licenses.bsd0 # freestanding-toolchain, freestanding-headers
      licenses.asl20 # cc-runtime
      licenses.mit # limine-efi, stb
      licenses.zlib # tinf
    ];
    # The platforms on that the Liminine binary and helper tools can run, not
    # necessarily the platforms for that bootable images can be created.
    platforms = platforms.unix;
    maintainers = [
      maintainers._48cf
      maintainers.phip1611
    ];
  };
}

```

Trying to build with this on macOS + Rosetta 2 (so x86_64 Nix packages are included as well as aarch64), and now I'm getting errors from lld about unknown arguments.

https://gist.github.com/T-O-R-U-S/51c181c1aacd2acc45759f3eee11929f

**Comment by phip1611** [comment]
When I added the derivation to nixpkgs, I decided to use --enable-all with the intention to create a Bootable image on a x86_64 platform that boots on all platforms.

I think this is a valid use case, especially if you are creating an EFI application with Rust that you easily can compile for x86, aarch64, and riscv. You can embed this into a Limine iso and add legacy boot capabilities additionally into that image.

Hence, I'd like to see the host tools being build for the host architecture but the bootloader files for all architectures.

**Comment by T-O-R-U-S** [comment]
I'd personally disagree and argue that we should try to keep nix packages as similar as possible across all platforms to keep with consumer expectation of replicability, so keeping `--enable-all` is probably a good call. I think we might need to change the `nativeBuildInputs` for `darwin-aarch64` systems to fix this.

[Here is a useful article section I found on the OSDev wiki](https://wiki.osdev.org/Limine_Bare_Bones#Compiling_the_kernel_on_macOS), as it points out probably the exact problem we're having.

> The macOS Xcode toolchain uses Mach-O binaries, and not the ELF binaries required for this Limine-compliant kernel. A solution is to build a [GCC Cross-Compiler](https://wiki.osdev.org/GCC_Cross-Compiler), or to obtain one from [homebrew](https://brew.sh/) by installing the x86_64-elf-gcc package. After one of these is done, build using make CC=x86_64-elf-gcc LD=x86_64-elf-ld.

I think this is why I'm getting all the incorrect argument errors -- by default, the *wrong* linker is being used because Apple just loves replacing the standard solution with their own home-grown garbage. 🙃

**Comment by phip1611** [comment]
FYI: In https://github.com/NixOS/nixpkgs/pull/305446/commits/26b947c9bcc312464b547ba68acaecf57398bafd someone removed darwin as platform.

**Comment by Noodlez1232** [comment]
Here to say that this is still a problem.

**Comment by Noodlez1232** [comment]
For context, this is a problem for all systems now, not just Darwin

**Comment by phip1611** [comment]
I'll look into it and hopefully find a pragamatic solution soon

**Comment by surfaceflinger** [comment]
I think the best solution will be to build limine for current architecture, other architectures should be built with `pkgsCross`

**Comment by phip1611** [comment]
I'll look into it. The idea to build it for all architectures is to not limit downstream users (OS programmers) when they crate bootable items for whatever architecture using Limine for their custom operating system project

**Comment by phip1611** [comment]
Perhaps my mental model is wrong, but as long as a simple can "fairly simple" cross-compile itself, it should do it, IMHO. Right? Limine can cross-compile easily with a clang/llvm toolchain but not a gcc toolchain. This used to work nicely for quite a few months in nixpkgs. Further, upstream this also works (not in Nix environment): https://github.com/limine-bootloader/limine/blob/v8.x/.github/workflows/check.yml

So my preferred solution is to make the clang/llvm build work again but keep `--enable-all` if it is possible.

I think your argument

> Yeah, end users then can do something like nix build nixpkgs#pkgsCross.aarch64-multiplatform.limine while being eg. on a x86_64-darwin machine and nixpkgs will make sure that the stdenv will have a working crosscompiler for aarch64-linux.

Is the way to go when the tool is bound to gcc. But here, we can use clang.

I'll keep you posted. I don't want to spend too much time into it, but it is blocking my at the moment as well.

**Comment by surfaceflinger** [comment]
lmfao, its because of #277564 - there are GNU binutils in `llvmPackages.stdenv` instead of LLVM tools. Limine needs Clang+LLVM toolchain or GCC+GNU toolchain, it can't be mixed

```
limine-aarch64-unknown-linux-gnu> checking for clang (aarch64)... yes
limine-aarch64-unknown-linux-gnu> checking for ld.lld (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-unknown-none-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-elf-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-none-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-none-elf-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-unknown-none-elf-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-linux-gnu-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-pc-linux-gnu-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-unknown-linux-gnu-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for aarch64-unknown-linux-gnu-gcc (aarch64)... no
limine-aarch64-unknown-linux-gnu> checking for gcc (aarch64)... no
```

finds clang, fails on ld.lld because llvmPackages.stdenv gives us GNU toolchain and starts looking for gcc which ofc doesn't exist.

I'll force-push my PR with allVariants toggle

**Comment by surfaceflinger** [comment]
It's possible to enforce LLVM only with `env.TOOLCHAIN_FOR_TARGET = "llvm";` which does this instead which is weird because everything was found according to logs above the error...

```
checking for clang (i686)... yes
checking for ld.lld (i686)... yes
checking for llvm-objcopy (i686)... yes
checking for llvm-objdump (i686)... yes
checking for llvm-readelf (i686)... yes
checking for clang (i686)... yes
checking for ld.lld (i686)... yes
checking for llvm-objcopy (i686)... yes
checking for llvm-objdump (i686)... yes
checking for clang (x86_64)... yes
checking for ld.lld (x86_64)... yes
checking for llvm-objcopy (x86_64)... yes
checking for llvm-objdump (x86_64)... yes
checking for clang (aarch64)... yes
checking for ld.lld (aarch64)... yes
checking for llvm-objcopy (aarch64)... yes
checking for llvm-objdump (aarch64)... yes
checking for clang (riscv64)... yes
checking for ld.lld (riscv64)... yes
checking for llvm-objcopy (riscv64)... yes
checking for llvm-objdump (riscv64)... yes
error: could not detect LLVM toolchain
```

**Comment by surfaceflinger** [comment]
It broke when upstream added RISC-V support here https://github.com/limine-bootloader/limine/commit/9274ee656e3bbd147a2ee44d4ff8a2f37359f2c9

Because LLVM doesn't support zerocallusedregs hardening on RISC-V, it was silently failing here: https://github.com/osdev0/freestanding-toolchain/blob/trunk/freestanding-toolchain#L65

**Comment by phip1611** [comment]
> Because LLVM doesn't support zerocallusedregs hardening on RISC-V, it was silently failing here:

So to summarize:

If we remove the hardening zerocallusedregs, the existing derivation works? I'm still happy with a configurable derivation, such as `enableAll ? false` etc. As long as it can easily be configured using `.override()`, I'm happy. :)


Thanks everyone for looking into this and working towards a solution!

**Comment by alyssais** [comment]
I think it would be totally fine to just leave it as at is and disable zerocallusedregs for this package, if that's a solution you folks prefer.
