### ISSUE TITLE
Update request: protonvpn=gui: 4.1.10 → 4.3.0

### ISSUE THREAD

**Issue by DuncanTDP** [NixOS/nixpkgs#304819]
- Package name: protonvpn-gui
- Latest released version: 4.3.0
- Current version on the unstable channel: 4.1.10
- Current version on the stable/release channel: 1.12.0
- [ * ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

This package has a pull request for version 4.2.0 that was never merged, and now that version has become out of date. Thank you.
---

**Comment by pyrox0** [comment]
Closed by #302011 being merged!
