### ISSUE TITLE
Build failure: ollama (ROCm)

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#304924]
### Steps To Reproduce

1. Enable ROCm in build
2. build ollama 0.1.31 

### Build log

https://gist.github.com/nonetrix/10fdd65e4e3e756a56b9053a96f9acf8

### Additional context

Using RX 6800

### Notify maintainers

@abysssol @dit7ya @elohmeier

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ 
♥ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), 24.05.20240412.cfd6b5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/yy5l09gfsagkv8rswblknmsjc2gyr20d-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
I believe that this should be fixed by #304736, if it's the same problem (which I think it is). It'll take a few days for that to get into an unstable release.
