### ISSUE TITLE
am2rlauncher: Fails to open up any .zip file

### ISSUE THREAD

**Issue by Noodlez1232** [NixOS/nixpkgs#304963]
### Describe the bug
Upon running AM2R launcher for the first time, and attempting to give it the AM2R1_1.zip, the application simply crashes with a segfault.

### Steps To Reproduce
1. Run AM2RLauncher (I used `nix run nixpkgs#am2rlauncher`)
2. Try to supply a .zip file.

### Expected behavior
Some sort of dialog box coming up allowing you to select a file.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/12480453/a1e56498-5b3b-4b6f-8a71-325791de8edb)
![image](https://github.com/NixOS/nixpkgs/assets/12480453/5643de77-2b39-4123-8b1d-c0bc5dbc6b54)

### Additional context
N/A

### Notify maintainers
@peeley 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25-rt29, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Noodlez1232** [comment]
I did look around, and it suggested that some sort of `glib-compile-schema` command needs to be run for the application, but I have never ever touched GDK so I have no clue.

**Comment by peeley** [comment]
Ah, I recall a similar issue w/ `glib-networking` happening during package development. I never ran into the issue or anything like it, but I think it's dependent on the window manager/desktop environment in use. I'm running XFCE which uses GTK heavily, do you mind sharing which WM you're on?

I'm also a little unfamiliar with GNOME, but I tracked down a [possible fix](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-no-schemas) in the `nixpkgs` manual. I have a branch in my fork of `nixpkgs` [here](https://github.com/peeley/nixpkgs/tree/am2rlauncher-fix-gsettings-error), if you don't mind trying it out and seeing if the error still occurs.

**Comment by Noodlez1232** [comment]
I use KDE. It works (almost) perfectly now! This also fixed #304965

Now, however, when it starts up, I get this error:
![Uploading image.png…]()
It is intermittent, so not every time it starts, but sometimes.

**Comment by Noodlez1232** [comment]
Sorry, I'm having trouble sending the image (network problems), so I'll copy the text from them. They are two dialog boxes with the caption of "GTK"
```
Unhandled Exception has occured in your Application.
*****Stack Trace*****

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.UriFormatException: Invalid URI: The URI is empty.
  at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind , uriCreationOptions& creationOptions)
  at System.Uri..ctor(String uriString)
  at Eto.GtkSharp.Forms.Controls.WebViewHandler.get_URL()
  at
Eto.GtkSharp.Forms.Controls.WebViewHandler.WebViewHandler_LoadChanged(Object o, SignalArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

Both dialog boxes have identical text.

**Comment by Noodlez1232** [comment]
It's also worth noting that this error doesn't prevent you from using the application.

**Comment by Noodlez1232** [comment]
Ah I didn't think to look at the other tabs, but the other tabs make it pretty apparent. It says "TLS/SSL support not available; install glib-networking"

**Comment by peeley** [comment]
Ah, yeah that's the `glib-networking` error that I referred to earlier. Odd that it's reoccurring, though; the existing fix seemed to do the trick last time with the exact same behavior.

Regardless, I'll do some more digging and come up with a fix on my fork. I can repro the error in a VM w/ NixOS 23.11 KDE, so I should have something soon-ish.

**Comment by peeley** [comment]
Alright, I think I have a fix in place on the same [branch in my fork](https://github.com/peeley/nixpkgs/tree/am2rlauncher-fix-gsettings-error). Try running `nix run github:peeley/nixpkgs/am2rlauncher-fix-gsettings-error#am2rlauncher`, and see if you still get the errors launching the game or launcher itself.

**Comment by Noodlez1232** [comment]
Oh yeah that fixed it! I tested it and it works perfectly.
