### ISSUE TITLE
Build failure: texpresso

### ISSUE THREAD

**Issue by kothavade** [NixOS/nixpkgs#304909]
### Steps To Reproduce

1. Attempt to install *texpresso* on macOS
2. Get `gcc: command not found` error

### Build log

```
error: builder for '/nix/store/3f8kdv51bq8lry3p51pkyr544nsjqiyy-texpresso-0-unstable-2024-03-26.drv' failed with exit code 2;
       last 10 log lines:
       > ./mupdf-config.sh: line 17: gcc: command not found
       > ./mupdf-config.sh: line 17: gcc: command not found
       > ./mupdf-config.sh: line 17: gcc: command not found
       > echo >>Makefile.config "TECTONIC_ENV=PKG_CONFIG_PATH=/lib/pkgconfig"
       > make[2]: Leaving directory '/private/tmp/nix-build-texpresso-0-unstable-2024-03-26.drv-0/source'
       > gcc -O2 -ggdb -I. -fPIC -I/include -c -o ../build/objects/driver.o -Idvi/ driver.c
       > /nix/store/crs76r1gifq0ay48v4kvws42fc59gmx5-bash-5.2p26/bin/bash: line 1: gcc: command not found
       > make[1]: *** [Makefile:34: ../build/objects/driver.o] Error 127
       > make[1]: Leaving directory '/private/tmp/nix-build-texpresso-0-unstable-2024-03-26.drv-0/source/src'
       > make: *** [Makefile:8: texpresso] Error 2
       For full logs, run 'nix log /nix/store/3f8kdv51bq8lry3p51pkyr544nsjqiyy-texpresso-0-unstable-2024-03-26.drv'.
```

### Additional context

Was able to fix locally with:
```nix
 texpresso = pkgs.texpresso.overrideAttrs (oldAttrs: {
    nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [pkgs.gcc];
 });
```

Assuming it builds on Linux, adding `gcc` only on Darwin might work, but I'm not sure if there's better ways to manage dependencies on a C compiler.

### Notify maintainers

@nickhu

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/rbkcv82pwkdfksh3qq3v5w0ha1nlzm84-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
Hi @kothavade do you experience this same issue on current nixpkgs where the version of texpresso is `0-unstable-2024-04-18`?

**Comment by kothavade** [comment]
Apologies, somehow missed this notification, and only just found it when looking through nixpkgs--it is working now though, thanks @kashw2!
