### ISSUE TITLE
Build failure: openmolcas

### ISSUE THREAD

**Issue by sheepforce** [NixOS/nixpkgs#305058]
### Steps To Reproduce

1. `nix build nixpkgs/nixpkgs-unstable#openmolcas`

### Build log

[openmolcas.txt](https://github.com/NixOS/nixpkgs/files/15025686/openmolcas.txt)
Hydra failure: https://hydra.nixos.org/build/254903827/nixlog/1

### Notify maintainers

@markuskowa

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 23.11 (Tapir), 23.11.20240406.e38d7cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(phillip): `"nixpkgs"`
 - nixpkgs: `/home/phillip/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by markuskowa** [comment]
Has resolved itself: https://hydra.nixos.org/build/257120366
