### ISSUE TITLE
Update request: mpv 0.37.0 → 0.38.0

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#305164]
- Package name: [mpv](https://mpv.io/)
- Latest released version: [0.38.0](https://github.com/mpv-player/mpv/releases/tag/v0.38.0)

- Current version on the unstable channel: [0.37.0](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/mpv/default.nix#L266)
- Current version on the stable/release channel: [0.36.0](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/video/mpv/default.nix#L252)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@AndersonTorres @fpletz @globin @Ma27 @tadeokondrak

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Yeeessaah!
