### ISSUE TITLE
Package request: siyuan

### ISSUE THREAD

**Issue by JaCoB1123** [NixOS/nixpkgs#305131]
**Project description**

SiYuan is a privacy-first personal knowledge management system that supports complete offline usage, as well as end-to-end encrypted data sync.

**Metadata**

* homepage URL: https://b3log.org/siyuan/
* source URL: https://github.com/siyuan-note/siyuan
* license:  AGPL-3.0 license 
* platforms: unix, linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Looked at the project, looks like it uses `pnpm` for lockfiles, which is unfortunate, as nixpkgs doesn't really support that officially. It also uses custom electron builder configs for different systems, which would complicate it a bit more. (Though, not many other source-built electron apps support anything other than linux)

We could put a generated `package-lock.json` in-tree, but NPM lockfiles take up too much space IMO.

I'll make an attempt at getting this to work, though.

**Comment by TomaSajt** [comment]
I got to this point:
```nix
{
  lib,
  fetchFromGitHub,
  buildGoModule,
  buildNpmPackage,
  electron,
}:

buildNpmPackage rec {
  pname = "siyuan";
  version = "3.0.11";

  src = fetchFromGitHub {
    owner = "siyuan-note";
    repo = "siyuan";
    rev = "v${version}";
    hash = "sha256-s82g5os944us85V2TBnm+HNd37vVzNjaOJYrbBrgLSI=";
  };

  kernel = buildGoModule {
    name = "${pname}-${version}-kernel";
    inherit src;
    sourceRoot = "${src.name}/kernel";
    vendorHash = "sha256-cGd8dn8Wu7mAbo7R30A2AC5wnb/wuEeqkUHWeoaJXe8=";
    # this doesn't seem to fix anything :(
    postPatch = ''
      substituteInPlace model/appearance.go \
          --replace-fail "filelock.Copy" "filelock.CopyNewtimes"
    '';
  };

  sourceRoot = "${src.name}/app";

  postPatch = ''
    ln -s ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-slSSNwtF5IvVK8hJpzesn2ipYUmIOdRdfAWDrg3GzgA=";

  env.ELECTRON_SKIP_BINARY_DOWNLOAD = "1";

  npmBuildScript = "build:desktop";

  postBuild = ''
        #--replace-fail 'asar: false' 'asar: true' \
    substituteInPlace electron-builder-linux.yml \
        --replace-fail '- target: "AppImage"' "" \
        --replace-fail '- target: "tar.gz"' '- target: "dir"'

    sed -e 1i'electronDist: ${electron}/libexec/electron' \
        -e 1i'electronVersion: ${electron.version}' \
        -i electron-builder-linux.yml

    npm run dist-linux
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/siyuan
    dir -R build/*-unpacked/
    cp -r build/*-unpacked/{locales,resources{,.pak}} $out/share/siyuan

    mkdir $out/share/siyuan/resources/kernel
    ln -s ${kernel}/bin/kernel $out/share/siyuan/resources/kernel/SiYuan-Kernel

    makeWrapper ${lib.getExe electron} $out/bin/siyuan \
        --chdir $out/share/siyuan/resources \
        --add-flags $out/share/siyuan/resources/app \
        --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
        --inherit-argv0

    runHook postInstall
  '';
}
```

There are several issues with it, causing it not to be able to launch.
The first is that when copying the files from the /nix/store to the workspace, it doesn't make sure to reset the permissions. I tried patching it, but the other method only resets modification times instead of permissions.

Relevant files:
- https://github.com/88250/gulu/blob/master/file.go
- https://github.com/siyuan-note/filelock/blob/main/filelock.go
- https://github.com/siyuan-note/siyuan/blob/398fdf164edfaaec2e06e601cefa24de2de05030/kernel/model/appearance.go#L45

**Comment by JaCoB1123** [comment]
Thanks for your work! I'm new to packaging for nix, so I can't help with your problems. 
I found that Siyuan does publish an [AppImage on GitHub](https://github.com/siyuan-note/siyuan/releases), would [packaging](https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-appimageTools) that maybe be an easier option?

**Comment by mksafavi** [comment]
> Thanks for your work! I'm new to packaging for nix, so I can't help with your problems. I found that Siyuan does publish an [AppImage on GitHub](https://github.com/siyuan-note/siyuan/releases), would [packaging](https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-appimageTools) that maybe be an easier option?

Wouldn't it be easier to just run it with `appimage-run` ?
But for packaging it there's `appimageTools` that can wrap an appimage. but I haven't tried it myself.

**Comment by TomaSajt** [comment]
It might be easier, but I've never done so previously, so I'll leave that for someone else.

**Comment by mksafavi** [comment]
I tried wraping the appimage. It launches the first time and works properly. but on the second launch it give a couple of errors. `Failed to get kernel serve port` and `Successfully avoid potential data corruption`.
I think it's the same issue that @TomaSajt mentioned. Running `chmod -R +w workspace` makes it work properly.



```
{
  lib,
  fetchurl,
  appimageTools
}:
appimageTools.wrapType2 rec {
  name = "siyuan";
  version = "3.0.12";
  src = fetchurl {
    url = "https://github.com/siyuan-note/siyuan/releases/download/v${version}/siyuan-${version}-linux.AppImage";
    hash = "sha256-grGEYRUplX4rFI3n1ARj3kvHCmYCb3pAWQYKfgGK60E=";
  };
}
```

**Comment by mksafavi** [comment]
> Relevant files:
> 
>     * https://github.com/88250/gulu/blob/master/file.go
> 
I took a peek at this. `filelock.CopyNewtimes` only stops calling `os.chtime` on the new files and still sets the source mode.
https://github.com/88250/gulu/blob/dfdea8ef020e51fd98cafd39b42ae46b14830ee5/file.go#L275
https://github.com/88250/gulu/blob/dfdea8ef020e51fd98cafd39b42ae46b14830ee5/file.go#L290

I think calling `os.chmod` on the files copied to the dest should be enough to fix it. right? 

Would you like to create a pull request for it? It's hard to keep track of things in the comments.
