### ISSUE TITLE
Package request: pragtical

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#305113]
**Project description**

A practical and pragmatic code editor (a fork of Lite XL).

**Metadata**

* homepage URL: https://pragtical.dev/
* source URL: https://github.com/pragtical/pragtical
* license: mit
* platforms: unix

**Additional information**

Here's the package stub: https://gist.github.com/suhr/12c27ba98322eb86920f8da090fea8b0.

Build script can't find Lua even though it is provided.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
I have managed to build it, now I just need to clean it up and open a PR.
