### ISSUE TITLE
Overriden default shortcuts may stop working after relogin

### ISSUE THREAD

**Issue by chermnyx** [NixOS/nixpkgs#305119]
### Describe the bug

After overriding default shortcuts for kde applications and restarting plasma session, shortcuts are getting broken. One of the following things happens:
1. The modified shortcuts are being reset to the default ones
2. The modified shortcuts are getting disabled

This is also reported at https://bugs.kde.org/show_bug.cgi?id=484884 

The issue https://github.com/NixOS/nixpkgs/issues/106796 might be related

### Steps To Reproduce
1. Open "Shortcuts" page in system settings
2. Disable "Print" shortcut for opening spectacle
3. Set "Print" shortcut to capture a rectangular region
4. Logout and relogin into plasma session

### Expected behavior
The shortcuts should work as configured

### Screenshots

Duplicated Spectacle entry after relogin
![image](https://github.com/NixOS/nixpkgs/assets/27727194/324b69f0-dddb-4411-b45d-c6c0efd939e0)

### Logs

```console
Apr 18 23:41:01 laptop systemd[2629]: Starting KDE Global Shortcuts Server...
Apr 18 23:41:01 laptop systemd[2629]: Started KDE Global Shortcuts Server.
Apr 18 23:41:03 laptop kwin_wayland[42319]: kf.globalaccel.kglobalacceld: Shortcut found twice in kglobalshortcutsrc. QKeySequence("Meta+Shift+Print")
Apr 18 23:41:03 laptop kwin_wayland[42319]: kf.globalaccel.kglobalacceld: Shortcut found twice in kglobalshortcutsrc. QKeySequence("Print")
Apr 18 23:41:03 laptop kwin_wayland[42319]: kf.globalaccel.kglobalacceld: Shortcut found twice in kglobalshortcutsrc. QKeySequence("Meta+Shift+S")
Apr 18 23:41:05 laptop kded6[42476]: QDBusObjectPath: invalid path "/modules/plasma-session-shortcuts"
Apr 18 23:41:05 laptop kded6[42476]: kf.dbusaddons: The kded module name "plasma-session-shortcuts" is invalid!
```

### Notify maintainers

@NixOS/qt-kde

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.27-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240418.2948912`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/d39a5pl04wx8d650rzalrsdf6d11h74x-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chermnyx** [comment]
I think https://github.com/NixOS/nixpkgs/issues/292632 is related (global shortcuts in kde are also defined in .desktop files which are cached in .cache/ksycoca6_*)

**Comment by chermnyx** [comment]
Doing 
```nix
systemd.user.services.nixos-rebuild-sycoca.enable = false;
```

Resolves the issue for me

**Comment by kuroko143** [comment]
Tried the above fix. It did not fix it for me.

Currently still have to comment out that line listed in the kde bug report by Nixdy at:

[https://bugs.kde.org/show_bug.cgi?id=484682](https://bugs.kde.org/show_bug.cgi?id=484682)

**Comment by kuroko143** [comment]
So i tried this for the past 2 days.

Print
Meta+Print
Meta+Period

They reset after a reboot. So KDE should look into this? Unless it's a NixOS bug.

**Comment by hatred-dev** [comment]
Same behavior with Spectacle.
Shortcuts are being reset after reboot.

**Comment by chermnyx** [comment]
People are reporting the same issue on Arch, so I'm closing this issue because it's probably KDE bug

**Comment by chermnyx** [comment]
https://bugs.kde.org/show_bug.cgi?id=484682
