### ISSUE TITLE
Update request: rsync 3.2.7 → 3.3.0

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#305168]
- Package name: [rsync](https://rsync.samba.org/)
- Latest released version: [3.3.0](https://download.samba.org/pub/rsync/NEWS#3.3.0)

- Current version on the unstable channel: [3.2.7](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/sync/rsync/default.nix#L64)
- Current version on the stable/release channel: [3.2.7](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/networking/sync/rsync/default.nix#L64)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ehmry @kampfschlaefer @ivan

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DataHearth** [comment]
done in #305294 😄
