### ISSUE TITLE
brick_0_28 fails because of wrong vty dependency

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#30538]
## Issue description

I have a package that depends on brick_0_28. brick_0_28, however, fails to build because of the following error:

    Setup: Encountered missing dependencies:
    vty >=5.18.1

There seems to be vty_5_18_1, but it's not used in the derivation for brick_0_28. 

### Steps to reproduce

Installing brick_0_28 should suffice.

## Technical details

* System: 18.03pre117327.3fe7cddc30 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre118082.00e56fbbee"
* Sandboxing enabled: false

**Comment by prusnak** [comment]
There is no brick_0_28 anymore, only brick_0_53, and this one builds just fine.
