### ISSUE TITLE
Mark packages as broken when their dependencies cannot be met (was font-lock-plus missing from emacsPackages)

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#30532]
## Issue description
Package `font-lock-plus` missing from latest `melpa` generation.
This breaks `all-the-icons` and all packages depending on it.

### Steps to reproduce
Try to use anything depending on `emacsPackages.font-lock-plus`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
18.03.git.16ff6c3456M (Impala)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
18.03.git.16ff6c3456M
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
build-use-sandbox = true

**Comment by pbogdan** [comment]
Sounds it was introduced in https://github.com/NixOS/nixpkgs/pull/30313 and is due to new MELPA's policy to no longer provide packages that are hosted on the Emacs wiki, with `font-lock-plus` being one of those. See [the upstream discussion](https://github.com/melpa/melpa/pull/5008).

**Comment by peterhoeg** [comment]
Closing as this is a MELPA issue.

**Comment by adisbladis** [comment]
@peterhoeg In a sense I agree but I also think this is a nixpkgs issue that the dependency is just gone without also marking dependants as broken.

**Comment by peterhoeg** [comment]
You're right @adisbladis. Please change the title to reflect what this really is - mark packages as broken when their dependencies cannot be met. Do you have a list of the affected ones?

**Comment by etu** [comment]
But Melpa haven't removed font-lock+ yet since the dependency issues aren't resolved yet. You can see the package on their website: https://melpa.org/#/font-lock%2B

So I find it weird that it would be dropped from NixOS before it's actually gone from Melpa. I agree that Emacs Wiki packages is a bad idea, but they need to resolve their deps before they actually drop things. Which they seem to work on.

**Comment by peterhoeg** [comment]
@mdorman - isn't the list of packages automatically generated?

**Comment by mdorman** [comment]
@peterhoeg The list is generated automatically, yes, but I've always done a _little_ bit of housekeeping on it.

I'm happy to add testing evaluation of the `emacsPackagesNg` expression to my workflow to keep this sort of thing from happening again; it just hadn't occurred to me.
