### ISSUE TITLE
Package request: mirrord

### ISSUE THREAD

**Issue by feynmanliang** [NixOS/nixpkgs#305383]
**Project description**

Develop Locally with Your Kubernetes Environment

Run your local code in the real-time context of your cloud environment, with access to other microservices, databases, queues, and managed services, all without leaving the local setup you know and love.

**Metadata**

* homepage URL: https://mirrord.dev/
* source URL: https://github.com/metalbear-co/mirrord
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

CC @aviramha

**Comment by aviramha** [comment]
Thanks for suggesting it! I actually tried adding mirrord but I had hard time doing the macOS bit. Maybe adding just Linux will be easier.

**Comment by donmstewart** [comment]
Darwin support would be appreciated as linux only forces us into VMs/Containers.
