### ISSUE TITLE
github-runner: <name>.enable has no effect

### ISSUE THREAD

**Issue by chreekat** [NixOS/nixpkgs#305304]
The config doesn't seem to be guarded on the `enable` option. :)

## Expected behavior:

If `services.github-runner.foo.enable = false`, then that github-runner shouldn't be enabled

## Actual behavior:

The runner is enabled regardless of the `enable` setting.

/cc @veehaitch @newAM

**Comment by aanderse** [comment]
@chreekat would you be willing to fix up this issue? i believe it would be fairly easy issue to resolve.

**Comment by chreekat** [comment]
Yes, if I hadn't noticed this while deep in the middle of another task I would have just done it! I have it on my "easy" list, but I can't promise how quickly I will get to it.

**Comment by aanderse** [comment]
great! thank you so much

please feel free to ping me on that PR when you get around to it
