### ISSUE TITLE
Package request: fish lsp

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#305493]
**Project description**

This is a LSP for the [fish shell](https://fishshell.com) programming language. 

**Metadata**

* homepage URL: https://github.com/ndonfris/fish-lsp
* source URL: https://github.com/ndonfris/fish-lsp
* license: MIT
* platforms: Linux, MacOS. 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by petertriho** [comment]
@ShalokShalom `fish-lsp` should not be in `unstable`
