### ISSUE TITLE
ktorrent missing toolbar buttons

### ISSUE THREAD

**Issue by desmond-git** [NixOS/nixpkgs#305420]
### Describe the bug
I am on the unstable channel, running KDE. 
When I install ktorrent 24.02.2 (kdePackages.ktorrent) some toolbar buttons like start, pause and stop a torrent is missing.
When I try version 23.08.5 (libsForQt5.ktorrent) they are there as expected.

### Steps To Reproduce
1. Install ktorrent 24.02.2  (kdePackages.ktorrent)
2. Look at the toolbar. There is only new, open and paste icons.
3. Right click and select configure toolbar, there should be a drop down menu for selecting torrent icons but it's missing.

### Screenshots
V.23:
![v23](https://github.com/NixOS/nixpkgs/assets/112279728/3995c278-166a-4f64-94ee-ba0e2dba2e8c)

V.24:
![V24](https://github.com/NixOS/nixpkgs/assets/112279728/960ff823-f985-433e-88f4-f7cb6e53a725)

### Notify maintainers
@ilya-fedin
@K900
@LunNova
@mjm
@NickCao
@SuperSandro2000
@ttuegel

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.26, NixOS, 24.05 (Uakari), 24.05pre610435.1042fd8b148a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ilya-fedin** [comment]
Apparently it's the intended new default layout? There's a 'Configure Toolbars...' button in Settings menu

**Comment by desmond-git** [comment]
> Apparently it's the new intended default layout? There's a 'Configure Toolbars...' button in Settings menu

Perhaps you are right, now I looked at the screenshot of ktorrent on KDE website and I don't see those buttons either. 
That's odd, so now people have to use hotkeys to manage torrents? That's very silly if they removed important toolbar buttons, it's something the Gnome team does but I don't expect KDE team to do it. Settings > Configure Toolbars does not contain the missing buttons. On v23 there is a drop down menu there where the torrent management icons are. I am on Plasma 6.

**Comment by ilya-fedin** [comment]
Looks like it can't find the kxmlgui layout files
```
kf.xmlgui: cannot find .rc file "kttorrentactivityui.rc" for component "ktorrent"
kf.xmlgui: cannot find .rc file "ktorrentui.rc" for component "ktorrent"
kf.xmlgui: cannot find .rc file "ktorrentui.rc" for component "ktorrent"
```

**Comment by desmond-git** [comment]
> Looks like it can't find the kxmlgui layout files
> 
> ```
> kf.xmlgui: cannot find .rc file "kttorrentactivityui.rc" for component "ktorrent"
> kf.xmlgui: cannot find .rc file "ktorrentui.rc" for component "ktorrent"
> kf.xmlgui: cannot find .rc file "ktorrentui.rc" for component "ktorrent"
> ```

Is that something you could fix?

I see that on Arch Linux those files for package ktorrent 24.02.2 are in the folder /usr/share/kxmlgui5/ktorrent/.
On nix the files are in /nix/store/phi9j2i10065cqhs89wkr8c0ap1hrypx-ktorrent-24.02.1/share/kxmlgui6/ktorrent/.
Perhaps the Arch maintainers copied the files from the older version and that's why there is a kxmlgui5 folder instead of kxmlgui6. Maybe the buttons are present on Arch, I can not test now.

https://archlinux.org/packages/extra/x86_64/ktorrent/files/

If this can not be fixed then this report can be closed and I will have to either use hotkeys or switch to qbitorrent.

**Comment by ilya-fedin** [comment]
Yeah, it searches for kxmlgui5 directory while nixpkgs seem to force kxmlgui6
https://github.com/NixOS/nixpkgs/blob/c64f61e478b237f2f903d9e2596baa67cfa19ad9/pkgs/kde/frameworks/extra-cmake-modules/ecm-hook.sh#L44

**Comment by K900** [comment]
Oh great, kxmlgui has kxmlgui5 hardcoded in a bunch of places to this day.

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/305605
