### ISSUE TITLE
Cannot use python3.pkgs.powerline in a Python environment

### ISSUE THREAD

**Issue by mickk-on-cpp** [NixOS/nixpkgs#30555]
## Issue description

Following the Python changes I've attempted to refactor my config in order to put all my Python packages in one big environment. Unfortunately powerline is not co-operating.

### Steps to reproduce

```bash
$ nix-shell --pure -p 'python3.withPackages (ps: with ps; [ powerline ])'
these derivations will be built:
  /nix/store/dqwwhm5yfj8acg818l6bwzi1014myfxm-python3-3.6.2-env.drv
building path(s) ‘/nix/store/xbnips5lzxa8fyfbhkwg0zdfs7skd6k3-python3-3.6.2-env’
collision between `/nix/store/112b5mk5b0v4ni3wy163abz83n2ggnf3-python2.7-setuptools-36.4.0/bin/.easy_install-wrapped' and `/nix/store/zw592iby8g7hk0gbi06iq2dbdnd48j25-python3.6-setuptools-36.4.0/bin/.easy_install-wrapped'
builder for ‘/nix/store/dqwwhm5yfj8acg818l6bwzi1014myfxm-python3-3.6.2-env.drv’ failed with exit code 25
error: build of ‘/nix/store/dqwwhm5yfj8acg818l6bwzi1014myfxm-python3-3.6.2-env.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

A quick look suggests that Powerline has some dependencies which pulls in some Python 2 stuff leading to the conflict above. It is in fact possible to build a Python 2 environment with the counterpart Powerline package.

It is still possible to do a 'normal' build of Powerline e.g. `nix-shell --pure -p python3.pkgs.powerline`, but when installed system-wide like so this understandably puts the executables in the path (great for e.g. shell status bars), but does not make the Python libraries available to the interpreter (a show-stopper for e.g. the Vim status bar).

## Technical details

* System: NixOS 18.03pre118082.00e56fbbee (Impala)
* Nix version: 1.11.15
* Nixpkgs version: 18.03pre118082.00e56fbbee
* Sandboxing enabled: no

**Comment by FRidh** [comment]
The issue is that mercurial (or bazaar) is a Python 2 application are added as buildInputs, and their dependencies are propagated, causing this issue. These packages should not be added as buildInputs; instead, the path to the executables should be hardcoded. 

See https://github.com/NixOS/nixpkgs/commit/5c11622348ecdc5c7ed9aad2b86b8733342f10c7.
The hardcoding will still need to be done.
