### ISSUE TITLE
Package request: JChemPaint

### ISSUE THREAD

**Issue by bwkam** [NixOS/nixpkgs#305551]
**Chemical 2D structure editor application/applet based on the Chemistry Development Kit**

**Metadata**

* homepage URL: https://jchempaint.github.io/
* source URL: https://github.com/JChemPaint/jchempaint
* license: N/A
* platforms: [all](https://github.com/JChemPaint/jchempaint/blob/32864f345046ad25ceb3780b3dced0381790a355/core/src/main/resources/org/openscience/jchempaint/resources/userhelp_jcp/en_US/contain/whatIs.html#L61C1-L63C81)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bwkam** [comment]
@sheepforce I know you maintain lots of packages in the chemistry/science module, so I thought I'd mention you for this one.

**Comment by sheepforce** [comment]
I can have a look in the next few days. But I'm by no means experienced with Java. :sweat_smile:

**Comment by sheepforce** [comment]
I'm afraid I wasn't too successful. JChemPaint seems to be in bad shape. The last commit is from 4 years ago and was only a version bump. The last release is 12 years old, half of the links, including prebuilt apps, on the website are 404 and building from source fails as they still require Java 7 and Maven in nixpkgs just refuses. Seems pretty dead unfortunately :/

I don't really require 2D molecular editors and did all skeleton structures in LaTeX with chemfig, but Molsketch looks comparable, is packaged and was working well on my quick try now.

**Comment by bwkam** [comment]
Ah, indeed. I'm sorry you had to go through this hassle. I was recommended JChemPaint for sketching molecules, but I wasn't aware of Molsketch, it seems good enough for my use case (I've also found Marvin, nice one too), cool thing they are packaged. Thank you, I can close this, since I don't need it anymore, or do I keep it open?

**Comment by sheepforce** [comment]
Naw, don't worry :) There is also Chemdoodle looking pretty neat but its commercial with no free license.

Let's close the issue then, JChemPaint is unlikely to be a sustainable option for packaging :)
