### ISSUE TITLE
nixos/bookstack: conflicting types for appKeyFile

### ISSUE THREAD

**Issue by erooke** [NixOS/nixpkgs#305566]
### Describe the bug
While trying to use the bookstack module I encountered this error:
```console
error:
       … while calling the 'head' builtin

         at /nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source/lib/attrsets.nix:1541:11:

         1540|         || pred here (elemAt values 1) (head values) then
         1541|           head values
             |           ^
         1542|         else

       … while evaluating the attribute 'value'

         at /nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: A definition for option `services.bookstack.config.APP_KEY._secret' is not of type `null or string'. Definition values:
       - In `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source/nixos/modules/services/web-apps/bookstack.nix': /run/keys/bookstack-appkey
error: Recipe `rebuild` failed on line 17 with exit code 1
```
Despite having not set `services.bookstack.config.APP_KEY._secret`. It looks
like the module is setting `services.bookstack.config.APP_KEY._secret` to
be `services.bookstack.appKeyFile` despite them having disparate types.

### Steps To Reproduce
The following configuration triggers the issue.
```nix
services.bookstack = {
  enable = true;
  appKeyFile = /run/keys/bookstack-appkey;
};
```

### Expected behavior
The config does not type error on variables I have not manipulated.

#### Nixpkgs revision

`5c24cf2f0a12ad855f444c30b2421d044120c66f`

#### Workaround

I was able to work around this problem with the following config:
```nix
services.bookstack = {
  enable = true;
  appKeyFile = /run/keys/bookstack-appkey;
  config.APP_KEY._secret = lib.mkForce (toString config.services.bookstack.appKeyFile);
};
```

### Notify maintainers

@ymarkus 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.26, NixOS, 24.05 (Uakari), 24.05.20240419.5c24cf2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
you shouldn't be using a path here, use a string instead

**Comment by erooke** [comment]
You can't use a string, it complains that it has to be a path.

Apr 20, 2024 6:47:44 PM éclairevoyant ***@***.***>:

**Comment by erooke** [comment]
https://github.com/NixOS/nixpkgs/blob/754a00b38a44e774dba3518ced7efbf51a8970ba/nixos/modules/services/web-apps/bookstack.nix#L51 in particular here is it where it forces that's a path

**Comment by eclairevoyant** [comment]
`lib.types.path` includes any string that starts with `/`

**Comment by erooke** [comment]
I could have sworn I had tried that :sweat_smile:. Thanks.
