### ISSUE TITLE
man cmake/man ctest don't work

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#30561]
## Issue description
I have cmake installed via my configuration.nix but `man cmake` as well as `man ctest` can't be found

```
ls /nix/store/djdh51cdzzhn41g7dplrcym694v96qkz-cmake-3.9.2/share                                                                                                                                                                                                    ~
aclocal  cmake-3.9  doc
```

## Technical details
nixos-version=18.03.git.3999ff9 (Impala)
nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03.git.3999ff9900"
sandboxing disabled

**Comment by jtojnar** [comment]
See #24717

**Comment by teto** [comment]
new attempt https://github.com/NixOS/nixpkgs/pull/82720

**Comment by teto** [comment]
seems like https://github.com/NixOS/nixpkgs/pull/125337 solves it
