### ISSUE TITLE
Infinite recursion caused by `rpcbind` module

### ISSUE THREAD

**Issue by jmbaur** [NixOS/nixpkgs#305643]
### Describe the bug

When using `config.users.users` to condition the values of `config.fileSystems`, infinite recursion is reached. My use case is I am conditionally creating an extra disk partition for /home if there are any non-system users (i.e. `isNormalUser = true`), so I end up needing to set a value for `fileSystems."/home"` based on what is in `config.users.users`. A minimal reproducible config:

```nix
let
  nixpkgs = (builtins.getFlake "nixpkgs/master");
in
(nixpkgs.lib.nixosSystem {
  modules = [
    {
      nixpkgs.hostPlatform = "x86_64-linux";
      fileSystems."/".device = "/dev/sda1";
    }
    (
      { config, lib, ... }:
      {
        users.users.alice.isNormalUser = true;
        fileSystems."/home" = lib.mkIf config.users.users.alice.isNormalUser { device = "/dev/sda2"; };
      }
    )
  ];
}).config.system.build.toplevel
```

I can fix the issue by adding the following modules to `disabledModules`:
`"${modulesPath}/services/network-filesystems/glusterfs.nix"`
`"${modulesPath}/services/network-filesystems/nfsd.nix"`
`"${modulesPath}/services/networking/rpcbind.nix"`
`"${modulesPath}/services/x11/desktop-managers/cde.nix"`
`"${modulesPath}/tasks/filesystems/nfs.nix"`

But I don't think this should be the case for everyone else.

### Steps To Reproduce
1. save the above config to a file and `nix build` it

### Expected behavior

The `rpcbind` module does not cause infinite recursion

### Screenshots

N/A

### Additional context

N/A

### Notify maintainers

@flokli, @abbradar (git blame)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - nixpkgs: `/nix/store/6bf943g0mlhymyffs9dflzgc78r93s60-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Though not necessarily obvious at first glance, this is a duplicate of #24570

**Comment by jmbaur** [comment]
Good find @eclairevoyant, closing in favor of #24570
