### ISSUE TITLE
Ofborg failling due to missing `cxxabi`

### ISSUE THREAD

**Issue by Sigmanificient** [NixOS/nixpkgs#305610]
### Describe the bug
The ofborg evaluation fails due to missing `attribute 'cxxabi' missing` in `pkgs/tools/virtualization/ovftool/default.nix:174:53`

This commit seems to be the source of the issue https://github.com/NixOS/nixpkgs/commit/a5c2fa9641a00c9c214c5c044337e76864ed49b4:
in `preFixup`:

```nix
  preFixup = lib.optionalString stdenv.isLinux ''
    addAutoPatchelfSearchPath "$out/lib"
  '' + lib.optionalString stdenv.isDarwin ''
# ...
change_args+=(-change /usr/lib/libc++.1.dylib ${stdenv.cc.libcxx.cxxabi}/lib/libc++.1.dylib)
# ...
'';
```

`libcxxabi` no longer exist and was replaced by `libcxx`

Thanks to @COLAMAroro to help me investigate the issue

Notify maintaner: @thanegill 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
Fixed by #305609

**Comment by Sigmanificient** [comment]
@cole-h Thanks you so much for your reactivity

**Comment by cole-h** [comment]
Honestly, it was just good timing -- I was looking to see if some other package had been updated recently and saw a bunch of red Xs in a row, which set off my "this is strange" alert haha.

**Comment by Sigmanificient** [comment]
> Honestly, it was just good timing -- I was looking to see if some other package had been updated recently and saw a bunch of red Xs in a row, which set off my "this is strange" alert haha.
> 
> EDIT: Thank _you_ for actually figuring out the problem and the solution -- I just wanted to get `master` evaluating again ASAP :)

Credit goes to @COLAMAroro actually

**Comment by ghostofannalee** [comment]
libcxxabi was removed by https://github.com/NixOS/nixpkgs/pull/292043 in march and merged into the libcxx derivation. this is the second commit which broke eval that i'm aware of.
