### ISSUE TITLE
Build failure: carapace

### ISSUE THREAD

**Issue by mayersj1** [NixOS/nixpkgs#305607]
### Steps To Reproduce

1. Attempting to run 'home-manager --flake .#smayer@heresy switch -v'

### Build log

```
Using saved setting for 'experimental-features = nix-command flakes' from ~/.local/share/nix/trusted-settings.json.
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/v4pcs3nzx54m5bmxd39win0rgl2d2hbx-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'
         at /nix/store/v4pcs3nzx54m5bmxd39win0rgl2d2hbx-source/pkgs/build-support/trivial-builders/default.nix:68:16:
           67|         enableParallelBuilding = true;
           68|         inherit buildCommand name;
             |                ^
           69|         passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘conmon-2.1.10’ in /nix/store/v4pcs3nzx54m5bmxd39win0rgl2d2hbx-source/pkgs/applications/virtualization/conmon/default.nix:45 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.


```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

NOTE: I'm on aarch64-darwin and this ran fine yesterday from unstable.  Something changed (The last thing I saw attempting to build was carapace when this error occurred).
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mayersj1** [comment]
Not sure what would have a dependency on conmon all of a sudden.

**Comment by kashw2** [comment]
To make sure the issue is with carapace, could you run `nix build github:nixos/nixpkgs/nixos-unstable#carapace` and confirm? Alternatively if you are running nixpkgs-unstable, run `nix build github:nixos/nixpkgs/nixpkgs-unstable#carapace`.

**Comment by mayersj1** [comment]
Well, that built successfully. In the result/bin directory there is a carapace 1.0.1 that I’m able to execute without error.

So where does that leave us?  I just tried the home-manager switch again and still showing the same error regarding conmon.

How can I determine what is attempting to build this derivation?

Thanks,

Steve Mayer
***@***.***

**Comment by mayersj1** [comment]
ahh.... Appears to be related to podman:


`❯ nix build github:nixos/nixpkgs/nixpkgs-unstable#podman
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'podman-5.0.2'
         whose name attribute is located at /nix/store/zahlgvbc6arwzbr357xk50ds5c5krr0k-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'patches' of derivation 'podman-5.0.2'
         at /nix/store/zahlgvbc6arwzbr357xk50ds5c5krr0k-source/pkgs/stdenv/generic/make-derivation.nix:395:14:
          394|
          395|       inherit patches;
             |              ^
          396|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘conmon-2.1.10’ in /nix/store/zahlgvbc6arwzbr357xk50ds5c5krr0k-source/pkgs/applications/virtualization/conmon/default.nix:45 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
`

**Comment by Aleksanaa** [comment]
Please open another issue regarding podman support on darwin, and ping the podman team.

**Comment by mayersj1** [comment]
Have done.  https://github.com/NixOS/nixpkgs/issues/305769
