### ISSUE TITLE
Crashing Xorg

### ISSUE THREAD

**Issue by danielslee** [NixOS/nixpkgs#305695]
### Describe the bug
XOrg crashes when certain applications are launched. More details here: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/2060354

### Steps To Reproduce

1. Run any of the IntelliJ IDEs. You may have to set anti aliasing to greyscale. Xorg will crash.

### Expected behavior
Xorg doesn't crash.

### Additional context
This is the bug: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/2060354

It looks like a security fix caused this regression.

Ubuntu has already applied patches that fix this for Xorg and Xwayland:

see this message from the above Ubuntu thread:
> I have prepared test packages for ubuntu 22.04 LTS/jammy in the https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+packages PPA for both xorg-server:
>  https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+sourcepub/15921802/+listing-archive-extra
> and for xwayland:
>  https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+sourcepub/15921798/+listing-archive-extra
> I was able to reproduce the crash under Xwayland in a jammy vm with both intellij and the glyph_memleak.c reproducer, and using the proposed upstream patch seems to address the crash, but more testing is welcome.

NixOS should use the same patches until this is fixed upstream in XOrg.

### Notify maintainers
@vcunat

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
Sounds like this will be addressed by this update:
https://lists.x.org/archives/xorg-announce/2024-April/003504.html

**Comment by danielslee** [comment]
xwayland too: https://lists.x.org/archives/xorg-announce/2024-April/003503.html

looks like updating xorg and xwayland to their latest versions will do the trick then

**Comment by vcunat** [comment]
xwayland was bumped to the latest version in PR #302930
