### ISSUE TITLE
Cask install doesn't install deps already installed by nix

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#30567]
## Issue description
Cask is quite common for Emacs Package development. But it seems to be slightly broken when running in NixOS (possibly under nix in other distros as well).

It doesn't install deps that are already installed globally by the system config.

### Steps to reproduce
Example ´Cask´ file:
```
(source gnu)
(source melpa)

(development
 (depends-on "request")
 (depends-on "buttercup")
 (depends-on "undercover"))
```

Then running in the same directory:
```
$ nix-shell -p emacsPackages.cask
$ cask install
```

And then list the result dir of installed deps:
```
$ ls .cask/25.3/elpa/
archives  buttercup-20171015.555  gnupg  shut-up-20150423.522  undercover-20170502.912
```

Note that `request` isn't installed since that's installed globbaly by my system config here:
```
/nix/store/0szmzm7dvcdf310javmbrdaap5b7yncq-emacs-request-0.3.0
/nix/store/9y1bwahpknjlxwjiraxj0774lx5yy7p9-emacs-request-0.3.0
/nix/store/9y1iiijc1vpnc1s7c8ph5p1p5lankn34-emacs-request-0.3.0
/nix/store/a568mbkypmv659v7d2nav3mdbidykxhh-emacs-request-0.3.0
/nix/store/gs6s3r064m4vw409nhg5vqg2jyp08d7f-emacs-request-0.3.0
/nix/store/myvjy0n6zzf97ki0ckzaj07ysjxdwl6l-emacs-request-0.3.0
/nix/store/s7ylv3qwajq5v1kar190whgapmglpqj7-emacs-request-0.3.0
```

Request is installed by my config due to it being a dependency of webpaste that I install here: https://github.com/etu/nixconfig/blob/032d43e5e641863428b254b1ef63d85d43eef39c/home-etu-nixpkgs/home.nix#L87

The issue then is that the dependency `request` is missing when doing things like running unit-tests through cask. Example with webpaste:
```
$ git clone git@github.com:etu/webpaste.el.git
$ cd webpaste.el
$ cask install
$ make unit
cask exec buttercup -L . tests/unit/
cask exec: error: Failed to execute buttercup -L . tests/unit/: [Errno 2] No such file or directory
Did you run cask install?
make: *** [Makefile:16: unit] Error 1
```

## Technical details

* System: 18.03.git.ceb2b71f69M (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03.git.ceb2b71f69M"
* Sandboxing enabled: build-use-sandbox = false

**Comment by etu** [comment]
This was embarrassing. This wasn't an issue with Cask. Cask isn't installing request because it's already installed and doesn't need it. The no such file or directory is due to a broken shebang in buttercup that I install with cask (therefore it can't be fixed by nix). I've put a pull request here to resolve this issue. https://github.com/jorgenschaefer/emacs-buttercup/pull/117

**Comment by vyp** [comment]
I wondering if maybe `fixupPhase` for patching shebangs is a better solution, and why it doesn't already fix it.

**Comment by etu** [comment]
Because buttercup is installed by cask in the project's dir and not by nix.
Maybe buttercup can be installed by nix. I don't know if Cask would find
the script then. But I think it would.

But I'm also not interested to have buttercup as part of my global
environment.

**Comment by vyp** [comment]
Oh right, there's not even a package for buttercup, I was looking at the cask expression thinking it was for buttercup. :woman_facepalming:
