### ISSUE TITLE
KDevelop can't find qdbus

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#30585]
## Issue description

```
$ kdevelop! -s "{0b43abee-b9ca-4c21-87ea-85efc2154220}"
which: no qdbus in (/nix/store/zx4vl80ndps9jciiwmxp4xyic26i1749-qttools-5.9.1/bin:/nix/store/qgbikwdx1bn1jm5nnvr8fif40d9cff7d-kde-cli-tools-5.10.5/bin:/home/glaebhoerl/bin:/run/wrappers/bin:/etc/per-user-pkgs/glaebhoerl/bin:/home/glaebhoerl/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
Error: The qdbus utility is missing.
$ ls /nix/store/zx4vl80ndps9jciiwmxp4xyic26i1749-qttools-5.9.1/bin
ls: cannot access '/nix/store/zx4vl80ndps9jciiwmxp4xyic26i1749-qttools-5.9.1/bin': No such file or directory
$ ls /nix/store/zx4vl80ndps9jciiwmxp4xyic26i1749-qttools-5.9.1/
lib/         nix-support/ phrasebooks/ 
$ ls /nix/store/qgbikwdx1bn1jm5nnvr8fif40d9cff7d-kde-cli-tools-5.10.5/bin
kbroadcastnotification  kcmshell5  kdecp5  kdemv5  kde-open5  keditfiletype5  kioclient5  kmimetypefinder5  kstart5  ksvgtopng5  ktraderclient5
```

`kdevelop.nix` contains the lines:

```
  postInstall = ''
    # The kdevelop! script (shell environment) needs qdbus and kioclient5 in PATH.
    wrapProgram "$out/bin/kdevelop!" --prefix PATH ":" "${qttools}/bin:${kde-cli-tools}/bin"
```

maybe this is no longer correct?

Edit: based on grepping /nix/store it seems it has moved here: `/nix/store/6js8gxdx98ky8jg8adcpva9sm56198vv-qttools-5.9.1-bin/bin/qdbus`

### Steps to reproduce

Start KDevelop, open the built-in konsole panel.

## Technical details

* System: `17.09.1756.c99239bca0 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"17.09.1756.c99239bca0"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by aanderse** [comment]
@glaebhoerl as of the 19.03 version of KDevelop this no longer appears to be an issue. Can you please confirm and close?

**Comment by glaebhoerl** [comment]
Will do after it is released and I upgrade to it.

**Comment by glaebhoerl** [comment]
Apologies for the delay! (Previously I'd always managed to upgrade to the new release within a few weeks...)

Indeed it seems to be fixed now.
