### ISSUE TITLE
Lunarvim: pyright not working

### ISSUE THREAD

**Issue by no-mood** [NixOS/nixpkgs#305801]
### Steps To Reproduce
1. Enter in a folder with a python file, and turn it into a git project (so LSPs like **pyright** can work)
2. Enter in a shell with lunarvim (lvim): `nix-shell -p lunarvim`
2. Open your file like this: `lvim file.py` 

The first error you get is:
`The project does not address the selection of constellations and filters.`
If you run `:LspLog` in lvim, you get:
```
[START][2024-04-21 19:33:21] LSP logging initiated
[ERROR][2024-04-21 19:33:21] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'start_client_health_checker_receiver' panicked at /home/mood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/els-0.1.39/diagnostics.rs:469:29:\nClient health check timed out\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

### Expected behavior
Expecting pyright to work

### Notify maintainers
@ProminentRetail 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.87, NixOS, 23.11 (Tapir), 23.11.20240419.bc194f7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/nnjib275nl4s5nhifn26w2k0ksq2cb25-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
Looking at the error message, this appears to be a bug in `pylyzer`, not pyright.

**Comment by no-mood** [comment]
There's still something wrong with pyright, because it wasn't picking the right python version (inside a dev shell) while more "native solutions" (like nixvim) didn't have this problem. I'd attach a log, but seems like lunarvim is now unmaintened (?)

**Comment by teto** [comment]
it's a recurrent issue, your pylyzer  excutable doesn't seem to work on nix, try to install the nixpkgs version
