### ISSUE TITLE
Get rid of `selfNativeBuildInput`

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#30587]
I noticed `selfNativeBuildInput` in the `guile` derivation, but do not see it defined anywhere.

**Comment by bgamari** [comment]
Pinging @Ericson2314. What is the status of this attribute? Should it be used? What purpose does it serve? It seems to me like it would be simpler if we just explicitly added `buildPackages.guile` to `nativeBuildInputs`.

**Comment by Ericson2314** [comment]
Yeah, I want to get rid of `selfNativeBuildInput`, like `crossAttrs`.

**Comment by Ericson2314** [comment]
Will be closed automatically when staging is merged.
