### ISSUE TITLE
Bazel 0.4 doesn't build on Darwin

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#30590]
## Issue description

We didn't have it working before TensorFlow started to build from source, but we need it now to fix TensorFlow on Darwin. Unfortunately I don't have a Mac so I can't tackle this problem efficiently. Current error on Hydra:

```
🍃  Building Bazel from scratch......./usr/bin/xcrun clang -fobjc-arc -framework CoreServices -framework Foundation -o /private/tmp/nix-build-bazel-0.4.5.drv-0/bazel_6mTHoLID/archive/_embedded_binaries/xcode-locator tools/osx/xcode_locator.m
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
/nix/store/ncvjpvcpsixl8vx2g8nm71m25xyhx67w-stdenv-darwin/setup: line 1055: ./output/bazel: No such file or directory
```

How should this be fixed?

Worst case I'll retain TensorFlow binary packages specially for Darwin.

### Steps to reproduce

1. `nix-build -A bazel_0_4`

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 9a84b52c931ab4e419adb29e04877dd5e41a2f77

**Comment by LnL7** [comment]
replacing `/usr/bin/xcrun clang` with `clang` or `cc` usually fixes these kind of issues.

**Comment by abbradar** [comment]
What does `/usr/bin/xcrun --sdk ${sdkString} --show-sdk-path` return?

**Comment by copumpkin** [comment]
If it really insists on there being an SDK path, we do actually have a fake `xcrun` that returns sensible data for our pure toolchain. Just include `xcbuild` in your `buildInputs`.

**Comment by mboes** [comment]
Close? cc @Profpatsch @uri-canva

**Comment by uri-canva** [comment]
I'm not using bazel 0.4 on darwin so I haven't looked into it, sorry.

**Comment by Profpatsch** [comment]
Hm, I think we can close, since bazel is not yet buildable on Darwin and the newest version is `0.15.1`. We are working on getting it to build there, though.
