### ISSUE TITLE
Minecraft: manual configuration needed

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#30592]
https://github.com/NixOS/nixpkgs/blob/acd80042a475f2b44dd2adc54e75f3f294ede1f1/nixos/modules/services/games/minecraft-server.nix#L16-L17

describes, that the server port is fixed, but it can be specified by the server config file.

**Comment by ikervagyok** [comment]
if i read the server definition correctly, on nixos the port is fixed - at least from a `configuration.nix` point of view.
the only way to "fix" this in my opinion is to be able to specify a `server.properties`-file in `configuration.nix`. do you have a better suggestion? should i try to implement this if i have time?

**Comment by Moredread** [comment]
@ikervagyok Setting minecraft server options via nixos would be nice, but I think the list of possible options is quite long. I think there should be  a hint in the .enable description, that configuration needs to be done manually as long as that is not done. Also the eula needs to be accepted manually too, so the user has to manually edit the config files anyways.

Let me know if you work on it, I'm still thinking about how to best improve the description. Maybe I also have time to add configuration support, so we might be able to cooperate on this.

**Comment by ikervagyok** [comment]
I'll look into it on the weekend.

I'd just give an option to specify a config file and copy that over (probably similar to how files in `/etc` are handled):
```
services.minecraft-server = {
  enabled = true;
  configFile = "./MC.config";
};
```

In a second round id make the changes to alternatively be able to create the config on the fly:
```
services.minecraft-server = {
  enabled = true;
# configFile = "./MC.config";
  port = 1234;
  world = "myWorld";
  max-players = 50;
  ...
};
```

**Comment by Moredread** [comment]
There was some argument I saw whether there should be configuration options for packages when they aren't relevant to the rest of the NixOS config (e.g. ports are important for the firewall, but number of users wouldn't be).

I'll see if I can find the relevant PR, but it contained a huge number of options, maybe someone remembers it. I'll edit this comment when I find it.

**Comment by robintown** [comment]
This issue is no longer relevant.
