### ISSUE TITLE
steam no longer works

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#30599]
## Issue description
After updating to 18.03pre118082.00e56fbbee (Impala) steam doesn't run

### Steps to reproduce
```
andy@xps ~> steam
cp: cannot create regular file '/home/andy/.local/share/Steam/bootstrap.tar.xz': Permission denied
Running Steam on nixos 18.03pre118082.00e56fbbee 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Pins potentially out-of-date, rebuilding...
mkdir: cannot create directory ‘/nix/store/1d33k248c4k72icgj4q6rxkwggvp2ghv-steam-fhs/steamrt/pinned_libs_32’: Read-only file system
mkdir: cannot create directory ‘/nix/store/1d33k248c4k72icgj4q6rxkwggvp2ghv-steam-fhs/steamrt/pinned_libs_64’: Read-only file system
```

**Comment by abbradar** [comment]
I haven't seen `pinned_libs_*` before; it seems like some new feature from Steam. I'll investigate.

**Comment by abbradar** [comment]
Huh, I cannot reproduce this on 9a84b52c931ab4e419adb29e04877dd5e41a2f77. Can you try backing up and removing `~/.local/share`.

**Comment by andrewrk** [comment]
Is it enough just to `rm -rf ~/.local/share/Steam`?  I tried that and when I run it, I get a dialog asking if I want to reinstall Steam. When I press reinstall, I get this:

```
andy@xps ~> steam

** (zenity:1942): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(zenity:1942): Gtk-WARNING **: Could not find the icon 'dialog-question-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Setting up Steam content in /home/andy/.local/share/Steam
cp: cannot create regular file '/home/andy/Desktop/steam.desktop': Permission denied
Running Steam on nixos 18.03pre118082.00e56fbbee 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by abbradar** [comment]
What drivers do you use?

**Comment by andrewrk** [comment]
This is totally my fault. I updated my system with `nixos-rebuild switch` but I have steam installed as a userland package, with `nix-env -i`. When I updated the userland package, it works fine.

I'm really sorry to waste your time.

**Comment by chreekat** [comment]
I get something similar. Just installed on an updated 17.03:

    Restarting Steam by request...
    Running Steam on nixos 17.03.1944.6233be812f 64-bit
    STEAM_RUNTIME has been set by the user to: /steamrt
    Pins potentially out-of-date, rebuilding...
    mkdir: cannot create directory ‘/nix/store/v64ajgyq5hs13qphk3zr4asagk1d099m-steam-fhs/steamrt/pinned_libs_32’: Read-only file system
    mkdir: cannot create directory ‘/nix/store/v64ajgyq5hs13qphk3zr4asagk1d099m-steam-fhs/steamrt/pinned_libs_64’: Read-only file system
    Error: You are missing the following 32-bit libraries, and Steam may not run:
    libGL.so.1
    Error:
    You are missing the following 32-bit libraries, and Steam may not run:
    libGL.so.1
    Press enter to continue:

**Comment by vcunat** [comment]
@chreekat: and you did enable 32-bit libGL in your configuration.nix?

**Comment by chreekat** [comment]
@vcunat probably not. Is there some documentation somewhere that I overlooked?

**Comment by vcunat** [comment]
@chreekat: `hardware.opengl.driSupport32Bit = true;` in your `configuration.nix`

**Comment by chreekat** [comment]
That did it, thanks!

Is there some place I can document this for future users, or is it already documented somewhere I missed?

**Comment by vcunat** [comment]
@chreekat: documented on https://nixos.org/nixpkgs/manual/#sec-steam

**Comment by aljones15** [comment]
Similar issue:

steam
Running Steam on nixos 18.09.1228.a4c4cbb613c 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Pins potentially out-of-date, rebuilding...
mkdir: cannot create directory ���/nix/store/b4ym1kr2s8j90li5gxqwnsk4czhwhzci-steam-fhs/steamrt/pinned_libs_32���: Read-only file system
mkdir: cannot create directory ���/nix/store/b4ym1kr2s8j90li5gxqwnsk4czhwhzci-steam-fhs/steamrt/pinned_libs_64���: Read-only file system


However:

105   hardware.opengl.driSupport32Bit = true;

is set to true with a nixos-rebuild switch
(how can I verify this is correct? )

I am using a default.nix instead of a full install i.e. a nix-shell

  1 with import <nixpkgs> { }; {
  2   steamEnv = stdenv.mkDerivation {
  3     name = "Steam";
  4     buildInputs = [steam];
  5     };
  6 }
~

**Comment by jpotier** [comment]
Wow, I ran into after steam trying to upgrade itself:

```
Running Steam on nixos 19.09.git.536c72a 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Pins potentially out-of-date, rebuilding...
mkdir: cannot create directory '/nix/store/1fgjq66g92s298yjrdv3in84wzwjhv7q-steam-fhs/steamrt/pinned_libs_32': Read-only file system
mkdir: cannot create directory '/nix/store/1fgjq66g92s298yjrdv3in84wzwjhv7q-steam-fhs/steamrt/pinned_libs_64': Read-only file system
internal error: /steamrt/setup.sh is missing, this runtime is invalid or corrupted
```

**Comment by ben0x539** [comment]
I'm getting this starting last night out of nowhere.

**Comment by chreekat** [comment]
This is probably related to a steam runtime update upstream. See https://github.com/NixOS/nixpkgs/issues/59851 for a more recent issue. Somebody mentions #59838 in that discussion, and I can confirm that that patch let me install and run Steam.

**Comment by cpages** [comment]
Both issues should be fixed now, please wait for the channels to catch up

**Comment by jpotier** [comment]
Fix has been merged in nixpkgs, yay
