### ISSUE TITLE
Jami panics when openig video

### ISSUE THREAD

**Issue by getreu** [NixOS/nixpkgs#305947]
### Describe the bug

1. Start `jami`

```
Using Qt runtime version: 6.6.1
"notify server name: Xfce Notify Daemon, vendor: Xfce, version: 0.9.3, spec: 1.2"
"Using locale: en_US"
No migration required
Cannot find dbus interface for screen saver
Main window loaded using OpenGLRhi
Syncing lrc accounts list with the daemon
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
NetworkManager client initialized, version:  1.44.4 , daemon running: yes , networking enabled: yes
primary network connection: 8b1b4256-a28f-4117-9986-89c19d4f05d8 default:  yes
```

2. Open Settings -> Audio and Video -> Video

    Jami panics with:

```
Creating new FrameObject for id: "camera:///dev/video0"
Added sink: 0x04d9b0a0 to subscribers for id: camera:///dev/video0
Terminated
```

### Expected behavior

The video dialogue window opens.

### Notify maintainers

@linsui 

### Additional information

```
jami --version
Using Qt runtime version: 6.6.1
Jami 20230619.1
```

I observed the same bug with the current unstable version:  20231201.0

**Comment by linsui** [comment]
I can't reproduce this problem. :shrug: Maybe you should report it upstream. Please also test the new version in https://github.com/NixOS/nixpkgs/pull/305983.

**Comment by getreu** [comment]
I made some more tests with a friend: We managed to do video calls!

The following still crashes with a segfault: 

   Open settings -> Video

I have a very minimal system with i3. Can it be, that there is some GTK service missing, Jami relies on?
I had a similar issue with `scan2pdf`: The menu entry that opens the properties dialogue causes the application to crash.

**Comment by linsui** [comment]
I don't know. Jami uses Qt though. But maybe something for the desktop is relied...

**Comment by getreu** [comment]
After a recent update I tried again. The video is working now as expected.
