### ISSUE TITLE
R package 'openssl' does not install

### ISSUE THREAD

**Issue by aswan89** [NixOS/nixpkgs#30593]
## Issue description

Installing the R package 'openssl' at a project level or user level as outlined in the [R-modules README](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/r-modules) throws the following error:

    Error: package or namespace load failed for 'openssl' in dyn.load(file, DLLpath = DLLpath, ...):
    unable to load shared object '/nix/store/izh9khd6nn25mdzcp2wnwmhgl5m0y6nw-r-openssl-.9.7/library/openssl/libs/openssl.so':
    libssl.so.1.0.0: cannot open shared object file: No such file or directory

### Steps to reproduce

Create a new directory, then create a `default.nix` file within it containing the following

```
let
  pkgs = import <nixpkgs> {};
  stdenv = pkgs.stdenv;
in with pkgs; {
  myProject = stdenv.mkDerivation {
    name = "myProject";
    version = "1";
    src = if pkgs.lib.inNixShell then null else nix;
    
    buildInputs = with rPackages; [
      R
      openssl
    ];
  };
}
```
Run `nix-shell .` within the new directory.

## Technical details

* System: NixOS 18.03pre118082.00e56fbbee (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre118082.00e56fbbee
* Sandboxing enabled: false

**Comment by mimadrid** [comment]
Hi @aswan89 
This was fixed yesterday in master https://github.com/NixOS/nixpkgs/commit/458331408e04608efcb4e09fbdfea36839f9aa02
Could you give it a try?

Thanks in advance

**Comment by aswan89** [comment]
I just ran the Rstudio upgrade as prescribed and everything installed properly. It appears to be fixed.
