### ISSUE TITLE
How to prevent a requireFile derivation from being garbage-collected?

### ISSUE THREAD

**Issue by Eisfreak7** [NixOS/nixpkgs#30609]
## Issue description

I have `sqldeveloper` installed, and every time one of its dependencies gets an upgrade nix tries to rebuild it.
If I ran garbage collection since the last build, it will require me to re-download the "requireFile".
Is there a way to tell nix to keep that file around?

### Steps to reproduce

Install package with requireFile, run garbage collection, wait for one of its dependencies to update.

## Technical details

* System: 17.09.1756.c99239bca0 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1756.c99239bca0"
* Sandboxing enabled: false

**Comment by FRidh** [comment]
You could create an out link somewhere so that it won't be garbage-collected.

**Comment by Eisfreak7** [comment]
But that would need to be managed manually. I was thinking more of "keep it around as long as the relevant package is installed", like a runtime dependency.

**Comment by FRidh** [comment]
Its a build-time dependency. Would you then want to store *all* build-time dependencies as well? You can also install this derivation in your profile with `nix-env -i`.

**Comment by Eisfreak7** [comment]
No, certainly not all. But I don't think thats the same: requireFile requires manual intervention, while most other build-time dependencies do not.

As a workaround I could add a `keepSource` option to the package, which would then just write the path of the source in a file in the out directory. Would that be accepted in the nixpkgs repo?

**Comment by bjornfor** [comment]
Like "keepSource ? config.requireFile.keepSource or false"? (I like it!)

**Comment by Eisfreak7** [comment]
Yes, making it a global option that can be overwritten per-package is even better
