### ISSUE TITLE
uv: jemalloc error on MacOS x86_64

### ISSUE THREAD

**Issue by kalekseev** [NixOS/nixpkgs#306045]
### Describe the bug

MacOS x86_64:

```
uv --version
<jemalloc>: Error allocating TSD
```

Should be easy to reproduce on CI with:

```
  doInstallCheck = true;
  installCheckPhase = ''
    $out/bin/uv --version | grep "${version}"
  '';
```

### Notify maintainers

@marsam

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
It looks like [the last update](https://github.com/NixOS/nixpkgs/pull/314447) has solved the bug.
I submitted #314617 to prevent this from happening again.
