### ISSUE TITLE
Add a Nixpkgs system for non-NixOS Linux and NetBSD

### ISSUE THREAD

**Issue by axelkar** [NixOS/nixpkgs#306038]
I want to build applications for normal Linux boxes using Nix, ideally with minimal rebuilds.

e.g. set the dynamic linker in wrappers to `/usr/lib/ld-linux-x86_64-64.so.2` or equivalent.

For C/C++, this needs to change:
https://github.com/NixOS/nixpkgs/blob/06fc87533759bb6243ca4114a1edd7f7d8068396/pkgs/build-support/bintools-wrapper/default.nix#L111-L133

I haven't looked at the Rust, Zig and Go wrappers in detail.

Next step would be to have some way of dynamically loading libraries from `/usr/lib` but it doesn't need to be upstream in Nixpkgs.

**Comment by imadnyc** [comment]
Nix can already build on non NixOS distros. Nixpkgs doesn't need to change anything, since this is for just the repository of packages that has been collected -- anything that you build on your own system without Nixpkgs wouldn't use this repo. You could install nix using the installer, and then use `nix-build <your default.nix>` in the repo you want to build, like in here https://nix.dev/tutorials/packaging-existing-software.html.

**Comment by axelkar** [comment]
I mean standalone packages for use without Nix installed or the Nix store packed anywhere.

**Comment by imadnyc** [comment]
For one off things, you can just copy the resultant binary from the nix store -- just copy whatever is in the `~/result` folder.

**Comment by axelkar** [comment]
> For one off things, you can just copy the resultant binary from the nix store -- just copy whatever is in the `~/result` folder. https://stackoverflow.com/questions/68684970/how-to-build-and-distribute-binary-packages-with-nix

That still requires Nix to be installed and the Nix store to exist.

**Comment by Aleksanaa** [comment]
> That still requires Nix to be installed

Not needed. Even NixOS runs well without Nix being installed (in system closure).

> and the Nix store to exist.

That's what `nix bundle` deals with. You can find some interesting bundles, such as [appimage bundle](https://github.com/ralismark/nix-appimage). Currently nixpkgs does not have in-tree support for these.

We had some functions to create working snap packages, but sadly nobody maintained it, so it was removed in https://github.com/NixOS/nixpkgs/pull/293416.

**Comment by axelkar** [comment]
@Aleksanaa Thanks for the links but those still fake a Nix store and to my knowledge contain glibc and the dynamic linker. I'm not looking for pureness here but rather non-bloated binaries built by Nix.

**Comment by axelkar** [comment]
Could this be reopened? I'd just want to compile binaries for traditional linux distros.
Can I somehow use "unwrapped" GCC/Clang for this?
This is in the same way as the MinGW and GHC platforms where they don't have Nix stores.

Here's what I'm using now, although it's very tedious to set for all packages I'm using:
```
export NIX_LDFLAGS="-dynamic-linker=/usr/lib/ld-linux-x86-64.so.2"
export NIX_DONT_SET_RPATH_x86_64_unknown_linux_gnu=1
```

**Comment by Aleksanaa** [comment]
Your request here sounds like "Why doesn't our tool support a usage it tries to avoid?" I don't think this use case will be supported anytime soon.
