### ISSUE TITLE
Build failure: procmail aarch64 cross build failure.

### ISSUE THREAD

**Issue by danielbarter** [NixOS/nixpkgs#306096]
### Steps To Reproduce

```
nix build .#pkgsCross.aarch64-multiplatform.procmail
```

### Build log

```
https://gist.github.com/danielbarter/a6a711e1f4f38368045c2dae2177ee7b
```

### Additional context

During configuration, some binaries are being compiled and run to decide things about the system. Not clear to me how to fix.

relevant since now `procmail` is a dependency of `xdg-utils` which is required by most desktop environments. see also https://github.com/NixOS/nixpkgs/issues/292393

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240419.5c24cf2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/v4pcs3nzx54m5bmxd39win0rgl2d2hbx-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Qyriad** [comment]
@danielbarter this is working for me on bd7bcaddfb5538cf67c75793d97a0dacc6a1d35b — are you still seeing this issue on latest master?

**Comment by danielbarter** [comment]
Ah, it is failing with `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` set on my build machine. Switching that off and the build works

**Comment by danielbarter** [comment]
Is there a policy for what it means for a cross build to be successful, given that `binfmt` is a source of impurity for cross builds? Presumably with no emulated systems?

**Comment by Qyriad** [comment]
That is a good question. I don't think there is a policy on it. Ideally as many correct configurations as possible would build, though.

**Comment by jcaesar** [comment]
Adding a data point to the weirdness: This doesn't fail when emulatedSystems is set but using a statically linked qemu (e.g. [this](https://github.com/NixOS/nixpkgs/issues/160300#issuecomment-2156003171)).

**Comment by MagicRB** [comment]
The following sed magic also makes it build with standard QEMU `sed -i $'/This actually can\'t happen/i : ; fi ; if false ; then' src/autoconf`
