### ISSUE TITLE
Nextcloud: `Failed to get an iterator for log entries: Logreader application only supports "file" log_type`

### ISSUE THREAD

**Issue by ISibboI** [NixOS/nixpkgs#306003]
### Describe the bug
Nextcloud shows `Failed to get an iterator for log entries: Logreader application only supports "file" log_type` in the admin panel.

### Steps To Reproduce

```
  services.nextcloud = {
    enable = true;
    hostName = "nextcloud.${config.networking.domain}";
    package = pkgs.nextcloud28;
    https = true;
    config = {
      dbtype = "pgsql";
      # Set only once, hence it can be in /run
      adminpassFile = "/etc/nixos/nextcloud-admin-pass.txt";
      # Needed every time.
      dbpassFile = "/etc/nixos/nextcloud-postgres-pass.txt";
    };
  };
```

### Additional context

I upgraded today to nextcloud 28, which is when this message first appeared. with 27, all was fine.

### Notify maintainers

@pks-t 
@Ma27 
@SuperSandro2000 
@dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.6510.a5e4bbcb4780`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
There are two options:

* switch the log type to `file` if you want to use the logreader application (allows you to read logs inside the Nextcloud admin panel)
* If you don't need that and want to get rid of the error from your admin panel, disable the logreader app.

Not much we can do about that. I think it's reasonable to have write stuff to the journal by default (which is the case for most services) and the app is featured, so enabled by default apparently.

I don't see anything actionable here, so I think this can be closed.

**Comment by ISibboI** [comment]
I understand. I think the current defaults are great. Sad, that the
logreader app cannot read syslog.

I guess it is not possible to disable logreader when installing nextcloud,
if the log_type is not set to file, or something like this?

**Comment by jzbor** [comment]
Hi, I would prefer reading my logs in the journal/syslog and do not really care about the built-in logreader app. Is it possible to restore this behavior? I was also looking at the `systemd` logging backend, but it seems to require a php extension that is not currently in nixpkgs.

**Comment by SuperSandro2000** [comment]
Also the systemd php extension is unmaintained and doesn't work. The default is logging to syslog.

**Comment by Ma27** [comment]
> I guess it is not possible to disable logreader when installing nextcloud,
> if the log_type is not set to file, or something like this?

The information which app is _enabled_ is part of the application state, not the configuration. Precisely, the information is in the `oc_appconfig` table. So we can't do much about that.

> [...] restore this behavior

There's nothing to restore though. The logreader attempted to read on NC27 already, but failed silently.
The default is still syslog. Errors can be found via `journalctl -t Nextcloud` (or `journalctl -u phpfpm-nextcloud`) by default.

**Comment by jzbor** [comment]
> Also the systemd php extension is unmaintained and doesn't work. The default is logging to syslog.

Nextcloud complained to my that the syslog backend was no longer available. I thought this would be a logging issue, but it seems to be just an issue with the logreader app.

**Comment by Ma27** [comment]
To avoid any misunderstanding: you mean the error from above, right?
Because https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#syslog states it still works (and it does on my setup as well).
The one above is only about the logreader app which happens do be enabled by default.

**Comment by Ma27** [comment]
This will be documented as "known warning" in the manual: https://github.com/NixOS/nixpkgs/pull/306595.
