### ISSUE TITLE
gnome-builder is not packaged

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#30616]
According to https://areweideyet.com/#gnome-builder gnome-builder is quite good at supporting Rust, but there's no way of testing it on NixOS today.

Maybe someone experienced with gnome packages could do this in little time, otherwise I'll dig into it in the mid-term future.

**Comment by jtojnar** [comment]
[Geary](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/misc/geary/default.nix) is a reasonably packaged example of GNOME app. Feel free to ping me here or on IRC if you need any help.

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/33270 WIP for packaging gnome-builder

**Comment by jtojnar** [comment]
Added in #44217.
