### ISSUE TITLE
nixos-rebuild: Add explicit semantics for building a non-ambient (non-Flakes) NixOS configuration

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#306109]
## Issue description

See #248572 

> With that said, IMO, though, this shows that the use of `NIX_PATH` to provide a location to a configuration file is the wrong way to handle this. It may be wise to add a `--file` (or similar) flag that handles that, abstracting away the `NIX_PATH` pains  when building an arbitrary configuration. Though I'm unsure if this can be done with the current design.

 - https://github.com/NixOS/nixpkgs/issues/248572#issuecomment-2070998096

I'm unsure if this is desirable outright, but would help with the UX of `nixos-rebuild`. I remember when I started using NixOS, way back when, that I was confused about how the evaluation even was happening, and how intangible it felt.

**Comment by infinisil** [comment]
This is implemented with https://github.com/NixOS/nixpkgs/pull/320462!
