### ISSUE TITLE
Documentation: Quarto and R

### ISSUE THREAD

**Issue by Aman9das** [NixOS/nixpkgs#306240]
## Problem

If quarto is added as a package, it fails to identify the R packages installed in the rWrapper and has terrible running scripts using the packages.

## Proposal

Kindly add documentation on how to add quarto so that R and quarto share same packages.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aman9das** [comment]
```nix
{ pkgs, config, lib, ... }:
with pkgs;
let
 rpkgs = rWrapper.override {
   packages = with rPackages; [
     tidyverse
     quarto
     MASS
     quarto
     ISLR2
   ];
 };
 in
{
  # R
  environment.systemPackages = with pkgs; [
    rpkgs
    quarto
  ];

  environment.variables = rec {
      QUARTO_R = "${rpkgs}/bin/R";
  };
}
```

The above is needed

**Comment by savyajha** [comment]
@Aman9das You should call `quarto` as a separate package. For example:

```nix
{ pkgs, config, lib, ... }:
with pkgs;
let
 rpkgs = with rPackages; [
     tidyverse
     quarto
     MASS
     quarto
     ISLR2
   ];
 my-r = rWrapper.override {
   packages = rpkgs;
 };
 my-quarto = quarto.override {
   extraRPackages = rpkgs;
 };
in
{
  # R
  environment.systemPackages = with pkgs; [
    my-r
    my-quarto
  ];
}
```
