### ISSUE TITLE
Forgejo module changes openssh settings even when using built in ssh server

### ISSUE THREAD

**Issue by toast003** [NixOS/nixpkgs#306205]
### Describe the bug

The option to enable the built in ssh server is `services.forgejo.settings.server.START_SSH_SERVER`, however the module checks for `services.forgejo.settings.START_SSH_SERVER`

Here's the line that does the check:
https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/nixos/modules/services/misc/forgejo.nix#L631

### Steps To Reproduce
1. Enable forgejo and set `services.forgejo.settings.server.START_SSH_SERVER` to true
2. Set `services.openssh.settings.AcceptEnv` to anything

### Expected behavior
There's no conflicting definition, and my system config builds just fine

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/39011842/bb32c0a3-e49a-4c1b-ad60-763ef722dffb)

### Notify maintainers

@emilylange @bendlas 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.86, NixOS, 23.11 (Tapir), 23.11.20240422.ea97158`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/g861759ghxxwvyfdbv17xf3iahgm8rcb-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by liveifsh** [comment]
I don't know if it's my fault but it seems like the issue still persists. Minimal reproducible example:

```
{ config, lib, pkgs, ... }:

{
  services.openssh.settings.AcceptEnv = "PLS DON'T CHANGE";
  services.forgejo = {
    enable = true;
    database.type = "postgres";
    lfs.enable = true;
    settings = {
      server = {
        DOMAIN = "192.168.0.106";
        # You need to specify this to remove the port from URLs in the web UI.
        ROOT_URL = "http://${srv.DOMAIN}:3000/";
        HTTP_PORT = 3000;
      };
    };
  };
}
```

The error:
```
error: The option `services.openssh.settings.AcceptEnv' has conflicting definition values:
       - In `/nix/store/05zq22ry219543phf7q87d883kxl6ry7-source/nixos/modules/services/misc/forgejo.nix': "GIT_PROTOCOL"
       - In `/nix/store/hkaf458fllxdwb1yf4010w1shxdp1lfc-source/services/forejo.nix': "PLS DON'T CHANGE"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

Even if I set ```services.forgejo.settings.server.DISABLE_SSH = true;``` the issue persists.

In fact, the only way to get rid of this error is to set ```services.forgejo.settings.server.START_SSH_SERVER = true;```. This will start a separate ssh server on its own port, so the default ssh config will be untouched (according to that part in forgejo.nix (lines 804-806):
```
services.openssh.settings.AcceptEnv = mkIf (
  !cfg.settings.server.START_SSH_SERVER or false
) "GIT_PROTOCOL";
```

I am not sure if it's the right way to do it. It would be a lot more convenient if there was a way to disable that feature without starting the internal ssh server

@pyrox0
