### ISSUE TITLE
Build failure: python311Packages.python-novaclient

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#306246]
### Steps To Reproduce

1. git checkout 06fc87533759bb6243ca4114a1edd7f7d8068396
2. nix build .#python311Packages.python-novaclient

### Build log

```
novaclient.tests.unit.test_shell.ParserTest.test_not_really_ambiguous_option
----------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/build/python-novaclient-18.6.0/novaclient/tests/unit/test_shell.py", line 351, in test_not_really_ambiguous_o>
    args = self.parser.parse_args(['--tic'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/argparse.py", line 1874, in parse_ar>
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/argparse.py", line 1907, in parse_kn>
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/argparse.py", line 1950, in _parse_k>
    option_tuple = self._parse_optional(arg_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/argparse.py", line 2269, in _parse_o>
    option_tuples = self._get_option_tuples(arg_string)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/build/python-novaclient-18.6.0/novaclient/shell.py", line 235, in _get_option_tuples
    normalizeds = [option.replace('_', '-')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/build/python-novaclient-18.6.0/novaclient/shell.py", line 236, in <listcomp>
    for action, option, value in option_tuples]
        ^^^^^^^^^^^^^^^^^^^^^

    ValueError: too many values to unpack (expected 3)
```

full log: https://gist.github.com/katexochen/541641c9e99ca5d76cc4dada3351a9e0

### Notify maintainers

@SuperSandro2000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), 24.05.20240412.cfd6b5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/yy5l09gfsagkv8rswblknmsjc2gyr20d-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
This looks like a bug in `novaclient` itself - Python 3.11.9 changed `argparse.ArgumentParser._get_option_tuples` to return a 4-tuple instead of a 3-tuple, but `novaclient` still expects it to be a 3-tuple.

**Comment by SuperSandro2000** [comment]
I would probably just ignore the test for the time being.

**Comment by SuperSandro2000** [comment]
Do we want to commit https://github.com/SuperSandro2000/nixpkgs/commit/4cddf2c0ccbfe7097ec6901e3493c8c438f914ee ?

**Comment by katexochen** [comment]
> Do we want to commit [SuperSandro2000@4cddf2c](https://github.com/SuperSandro2000/nixpkgs/commit/4cddf2c0ccbfe7097ec6901e3493c8c438f914ee) ?

I don't know much about the package but seems reasonable.

> This looks like a bug in `novaclient` itself - Python 3.11.9 changed `argparse.ArgumentParser._get_option_tuples` to return a 4-tuple instead of a 3-tuple, but `novaclient` still expects it to be a 3-tuple.

Maybe we can open an upstream bug for this if not already existent.

**Comment by SuperSandro2000** [comment]
Openstack is moving pretty slow and I wouldn't be surprised if they don't even support python 3.11 or even 3.10 yet.

**Comment by SuperSandro2000** [comment]
please take a look at #306480
