### ISSUE TITLE
trace: warning while doing nix-env -u

### ISSUE THREAD

**Issue by Aviksaikat** [NixOS/nixpkgs#306276]
**Describe the bug**

Getting the following `trace warning` while doing `nix-env -u`

```sh
$ nix-env -u                                                                   
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: eww now can build for X11 and wayland simultaneously, so `eww-wayland` is deprecated, use the normal `eww` package instead.
trace: warning: lxd has been renamed to lxd-lts
trace: warning: lxd-unwrapped has been renamed to lxd-unwrapped-lts
trace: warning: nixfmt was renamed to nixfmt-classic. The nixfmt attribute may be used for the new RFC 166-style formatter in the future, which is currently available as nixfmt-rfc-style
trace: warning: nvtop has been renamed to nvtopPackages.full
trace: warning: nvtop-amd has been renamed to nvtopPackages.amd
trace: warning: nvtop-intel has been renamed to nvtopPackages.intel
trace: warning: nvtop-msm has been renamed to nvtopPackages.msm
trace: warning: nvtop-nvidia has been renamed to nvtopPackages.nvidia
trace: warning: writeReferencesToFile is deprecated in favour of writeClosure
```

**Steps To Reproduce**

1.  Do `nix-env -u`

**Expected behavior**

**`nix-env --version` output**
```sh
nix-env (Nix) 2.21.2
```

**Additional context**

OS: `Kali GNU/Linux 2024.1`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by infinisil** [comment]
This is caused by some packages starting to use `lib.warn` for deprecations: https://github.com/NixOS/nixpkgs/blob/e5d9b197e9f13b29ca797e6a0aab21840eab64d4/pkgs/top-level/aliases.nix#L777

**Comment by philiptaron** [comment]
I wonder whether we should encourage this. Given the UX downsides, I lean towards "no".

**Comment by ManInDark** [comment]
I'd like to add that messages are also displayed multiple times, so I've got e.g. `trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead` thrice (I couldn't see any correlation from number of messages to number of packages).

Setup:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-21-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by kittygirlyy** [comment]
I got the same...

**Comment by goyalyashpal** [comment]
as far as i can recall, i started seeing this only after i added the `nvtopPackages.nvidia` in my etc/**/configuration.nix file.

```console
$ sudo nixos-rebuild test
building Nix...
building the system configuration...
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
stopping the following units: accounts-daemon.service
```


```console
$ nix-shell --version
nix-shell (Nix) 2.18.2

$ nix-info
system: "x86_64-linux", 
multi-user?: yes, 
version: nix-env (Nix) 2.18.2, 
nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by roberth** [comment]
> This is caused by some packages starting to use `lib.warn` for deprecations:
> 
> https://github.com/NixOS/nixpkgs/blob/e5d9b197e9f13b29ca797e6a0aab21840eab64d4/pkgs/top-level/aliases.nix#L777

What if they did something like the following?

```nix
  lxd = pkgs.lxd-lts // { outPath = lib.warn "lxd has been renamed to lxd-lts" lxd-lts.outPath; }
```

This doesn't cover everything; this should probably be handled by a function that adds it to all the outputs, so that a warning is emitted on instantiation, and not on attributes like `name`, `version`, `type` and `meta`.

**Comment by fractalf** [comment]
@infinisil  Why was this closed? The PR in question did not solve this problem and states:


> Outstanding issues:
> 
>     * This approach doesn't generalise well to things that aren't derivations. For example, the whole of `cudaPackages` is currently wrapped in a `lib.warn`, and `writeReferencesToFile` (a function) is as well, so these warnings persist after this PR.
> 
>     * I don't understand enough Nix internals to know why wrapping `drvPath` works here or if it's the right thing to do. In [trace: warning while doing nix-env -u #306276 (comment)](https://github.com/NixOS/nixpkgs/issues/306276#issuecomment-2302929175), @roberth suggested instead wrapping `outPath`, but for me this didn't seem to ever print the warnings.
> 
>     * The name `wrapWithWarn` should probably be changed; other candidates include `mkStub`, `mkWarnDrv`, etc.
> 
>     * `lib.derivations` is perhaps not the correct place for this helper to live, and it may need tests too – I'm unlikely to have the energy to figure this out on my own, but if someone else wants to put in the work or tell me what to do, feel free.
> 
>     * Does this negatively impact time taken to evaluate Nixpkgs? Is any impact outweighed by the UX improvement?
> 


I'm a noob nixos user, but long experience with arch/ubuntu based distros.
This issue is super annoying...

```sh
[alf@nixos:~/]$ nix-env -u
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: cudaPackages.autoAddDriverRunpath is deprecated, use pkgs.autoAddDriverRunpath instead
trace: warning: cudaPackages.autoAddOpenGLRunpathHook is deprecated, use pkgs.autoAddDriverRunpathHook instead
trace: warning: cudaPackages.autoFixElfFiles is deprecated, use pkgs.autoFixElfFiles instead
trace: warning: eww now can build for X11 and wayland simultaneously, so `eww-wayland` is deprecated, use the normal `eww` package instead.
trace: warning: lxd has been renamed to lxd-lts
trace: warning: lxd-unwrapped has been renamed to lxd-unwrapped-lts
trace: warning: nixfmt was renamed to nixfmt-classic. The nixfmt attribute may be used for the new RFC 166-style formatter in the future, which is currently available as nixfmt-rfc-style                                                                                                                                  
trace: warning: nvtop has been renamed to nvtopPackages.full
trace: warning: nvtop-amd has been renamed to nvtopPackages.amd
trace: warning: nvtop-intel has been renamed to nvtopPackages.intel
trace: warning: nvtop-msm has been renamed to nvtopPackages.msm
trace: warning: nvtop-nvidia has been renamed to nvtopPackages.nvidia
trace: warning: 'rapidjson-unstable' has been renamed to 'rapidjson'
trace: warning: writeReferencesToFile is deprecated in favour of writeClosure
```

**Comment by infinisil** [comment]
I'd like to defer to @sersorrel, who marked their PR to address this issue

**Comment by sersorrel** [comment]
my PR helped, at least for the `nix search` case, but yes it didn't entirely solve the problem. (if the `warnOnInstantiate` warnings are still actually printed by `nix-env`, then this issue certainly should be reopened, though.)

the only remaining warnings printed for me are those about CUDA <12 being removed in 25.05, which I hope will be resolved by CUDA <12 being removed some time in the next three months, and a single warning (new since I last checked, I think added in 2b969610d645c8a38865aade14daedbdb824f1cd) that `qt6Packages.stdenv is deprecated. Use stdenv instead.` which I _think_ could actually use `warnOnInstantiate` rather than `warn`? a PR to change that seems sensible, I can probably do so at some point.

if anyone wants to implement a solution that works for non-derivation things like CUDA (e.g. recursively walking an attrset until you find a derivation), they can open a PR for that, imo. I am not going to do that right now.
