### ISSUE TITLE
Merge request: vmagent → victoriametrics

### ISSUE THREAD

**Issue by juliusrickert** [NixOS/nixpkgs#306253]
## Issue description

Initially, I opened this issue to get _vmagent_ removed in favour of _victoriametrics_.
Instead, we propose that _vmagent_ be based on the _victoriametrics_ package.

---

## Original issue description for reference

The _[vmagent](https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/pkgs/servers/monitoring/vmagent/default.nix)_ package provides a subset of the programs provided by the _[victoriametrics](https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/pkgs/by-name/vi/victoriametrics/package.nix)_ package.
This package should be removed (and aliased to _victoriametrics_).

**Comment by IldenH** [comment]
Correct me if I'm wrong, but it seems as if vmagent could be useful without the whole victoriametrics package. Maybe someone wants that without also having vmbackup, vmrestore and so on?

**Comment by juliusrickert** [comment]
> Correct me if I'm wrong, but it seems as if vmagent could be useful without the whole victoriametrics package.

So could all of the other programs in the package. :D

If removal is not the best option, is there a way to provide all or some of the programs as individual packages without maintaining versions in [multiple](https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/pkgs/servers/monitoring/vmagent/default.nix#L4) [places](https://github.com/NixOS/nixpkgs/blob/6143fc5eeb9c4f00163267708e26191d1e918932/pkgs/by-name/vi/victoriametrics/package.nix#L5)?

**Comment by Atemu** [comment]
cc @yorickvP @ivan @NULLx76

**Comment by Shawn8901** [comment]
i played a bit around with the code. Would something like that fulfill the goal? https://github.com/Shawn8901/nixpkgs/commit/a2728a5acb7a6f262c133e53323c662cf776255c

vmagent as client tool could then be exposed like that https://github.com/Shawn8901/nixpkgs/commit/833c8f829741f28691559aa2d7adeb6933acc512

If yes i could create a pr for that

**Comment by Atemu** [comment]
That looks good to me! :)

**Comment by NULLx76** [comment]
That looks good to me as well 👍

**Comment by juliusrickert** [comment]
Cool, that looks like a reasonable solution! :)

I'll leave this issue open to be closed by merging the PR.

**Comment by Shawn8901** [comment]
As in the issue was some response and the did not attract any deeper looks yet, does some from here feel comfortable in peeking at the linked o3r?

**Comment by juliusrickert** [comment]
Sorry, I haven't been checking my GitHub notifications since. The merged solution looks good to me. Especially leaving the vmalert program in the victoriametrics package. :)

**Comment by ryan4yin** [comment]
FYI: I' ve submitted a PR #350737 to add more options and  enhance the utility of the VictoriaMetrics's NixOS module. Any reviews would be appreciated.

**Comment by Atemu** [comment]
Please restrain replies to PRs to topics that are directly relevant for the people involved in that specific PR such as issues the PR caused or follow-ups.

If you want a review, please ping the relevant people in your PR instead.

**Comment by ryan4yin** [comment]
@Atemu Understood, comment deleted.
