### ISSUE TITLE
docker-compose v1 fails to bring up any compose file with podman v5.0

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#306398]
### Describe the bug
`docekr-compose up` v1 fails with
```
ERROR: runtime error: index out of range [0] with length 0
```
with even the trivial `docker-compose.yaml`
```yaml
version: '3.4'
```
when using podman v5.0 as the OCI container backend.

### Steps To Reproduce
1. Use podman 5.0
2. Run `docker-compose up` with a valid `docker-compose.yaml` using `docker-compose_1`

### Expected behavior
`docker-compose` should bring up services specified in the compose file.

### Additional context
[`arion`](https://github.com/hercules-ci/arion) still uses `docker-compose_1` under the hood, so affects deployments using it.

https://github.com/hercules-ci/arion/issues/237

### Notify maintainers
@Frostman
@NixOS/podman 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kevincox** [comment]
I am seeing something similar for GitLab runner. Reverting podman to <5 works around the problem.

> ERROR: Failed to remove network for build
> ERROR: Preparation failed: Error response from daemon: runtime error: index out of range [0] with length 0 (docker.go:935:0s)

**Comment by heitorPB** [comment]
Reported upstream: https://github.com/containers/podman/issues/22561

https://github.com/NixOS/nixpkgs/blob/23f69f50f72ae19d7bbc7271abe30d8bc859207f/pkgs/applications/virtualization/podman/hardcode-paths.patch may be the cause of this bug.
