### ISSUE TITLE
Update request: surrealist 1.11.7 → 2.0.1

### ISSUE THREAD

**Issue by TECHNOFAB11** [NixOS/nixpkgs#306361]
- Package name: surrealist
- Latest released version: 2.0.1

- Current version on the unstable channel: 1.11.7
- Current version on the stable/release channel: -

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@MDM23 

**NOTE**
Surrealist has now officially moved to the SurrealDB Github org, see https://github.com/surrealdb/surrealist/ 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TECHNOFAB11** [comment]
It seems like they added a lot more package formats in the releases, so theoretically Nix can just use the tar.gz instead of having to use the deb

**Comment by MDM23** [comment]
Working on it. I'm currently stuck at an issue with the frontend build. There is a transitive dependency to `rollup-linux-x64-gnu` that does not get installed by pnpm.
