### ISSUE TITLE
was something wrong

### ISSUE THREAD

**Issue by mrsshahinda** [NixOS/nixpkgs#30638]
was something wrong

**Comment by vcunat** [comment]
Multiple new issues containing spam; that's wrong. https://github.com/NixOS/nixpkgs/issues?utf8=✓&q=author:mrsshahinda%20

**Comment by vcunat** [comment]
@edolstra: I suggest blocking this one from NixOS org. on GitHub.

**Comment by edolstra** [comment]
@vcunat Done.
