### ISSUE TITLE
Nix requires specific order in configuration

### ISSUE THREAD

**Issue by stackcoder** [NixOS/nixpkgs#306392]
### Describe the bug
Nix requires me to write my `configuration.nix` in a specific order. I created this issue in favor of [another one](https://github.com/NixOS/nixpkgs/issues/273591#issuecomment-2057414274) where I discovered this behavior first. I'm absolutely fine with it if it turns out I'm just still nix a noop. There might be good reasons for, but I really couldn't get it.

### Steps To Reproduce

1. Paste following in `configuration.nix`

```nix
# broken when above
boot.initrd.systemd.services.dummy = {
  description = "Dummy Service";
};

boot.initrd = {
  systemd.users.root.shell = "/bin/cryptsetup-askpass";
  network = {
    enable = true;
  };
};

# works below here
#boot.initrd.systemd.services.dummy = {
#  description = "Dummy Service";
#};
```

2. Build results in

```console
[user@system:~]$ nixos-rebuild dry-build -I nixos-config=/home/user/test/configuration.nix
building the system configuration...
error:
       … while evaluating the attribute 'config.system.build.toplevel'

         at /nix/store/990lzihr3amscp9df21spc8khdbn4ml6-nixos-23.11/nixos/lib/modules.nix:320:9:

          319|         options = checked options;
          320|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          321|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/990lzihr3amscp9df21spc8khdbn4ml6-nixos-23.11/nixos/lib/modules.nix:320:18:

          319|         options = checked options;
          320|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          321|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'systemd' already defined at /home/user/test/configuration.nix:107:5

       at /home/user/test/configuration.nix:101:3:

          100|   # Broken above
          101|   boot.initrd.systemd.services.dummy = {
             |   ^
          102|     description = "Dummy Service";
```

### Expected behavior
1. Both variants above and below work the same
2. Or nix tells me what I'm doing wrong

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.27, NixOS, 23.11 (Tapir), 23.11.6418.e402c3eb6d88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
That's not really related to nixpkgs, that's just how nix (the language) is designed.

```
nix-repl> :p { a.b.c = 1; a = { b.d = 2; }; }
error: attribute 'b' already defined at «string»:1:20
       at «string»:1:3:
            1| { a.b.c = 1; a = { b.d = 2; }; }
             |   ^
```

The simplest way to handle this is to either separate them into multiple files, or stick them in one bigger enclosing block:

```
nix-repl> :p { a.b = { c = 1; d = 2; }; }
{
  a = {
    b = {
      c = 1;
      d = 2;
    };
  };
}
```

**Comment by eclairevoyant** [comment]
Anyway as this is related to nix the language and not really nixpkgs, it'd be discussed in the nix repo. And there's already an open issue for this: NixOS/nix#7897
