### ISSUE TITLE
Upgrade Kubernetes to 1.8

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#30639]
## Issue description
Upgrade Kubernetes to 1.8. It's been out for a while now.

I imagine some people are already working on this (probably @offlinehacker or @NeQuissimus) but it would be nice to track any progress. :)

**Comment by NeQuissimus** [comment]
FYI, I am not working on this right now. I use k8s but I am not into it deep enough to know how to fix whatever is wrong with our modules when we try to upgrade to 1.8.x.

**Comment by srhb** [comment]
@NeQuissimus OK, thanks! :)

**Comment by NeQuissimus** [comment]
I think it is all a matter of modules and tests. The build itself works just fine...
Maybe give it a shot yourself ;)

**Comment by steveeJ** [comment]
I think this can be closed.
