### ISSUE TITLE
New package WIP: upwork

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#30654]
## Upwork Desktop application

I'm working on a new package for the Upwork desktop client. It's a proprietary tool used by Upwork freelancers to track time for hourly contracts. I still need to resolve the issue of hard-coded paths but as of now it does run. [Here's](https://github.com/emmanuelrosa/nixpkgs/commit/42e0bbca0fd6dbf4fae8df1b4c8ea975e7a23828
) a link to the commit. The package is shown below:

```nix
{ stdenv, fetchurl, dpkg, makeWrapper,
  gtk2, atk, glib, cairo, pango, gdk_pixbuf, freetype, fontconfig, gtkglext, xorg, nss, nspr, 
  gconf, alsaLib, dbus, cups, mesa_glu, systemd, expat
}:

let
  version = "4_2_153_0_tkzkho5lhz15j08q";

  platform = {
    x86_64-linux = {
      inherit version;

      src = fetchurl {
        url = "https://updates-desktopapp.upwork.com/binaries/v${version}/upwork_amd64.deb";
        sha256 = "19ya2s1aygxsz5mhrix991sz6alpxkwjkz2rxqlpblab95hiikw0";
      };
    };

    i686-linux = {
      inherit version;

      src = fetchurl {
        url = "https://updates-desktopapp.upwork.com/binaries/v${version}/upwork_i386.deb";
        sha256 = "1r2hqzdd4s1kmpji1yn4ihs135yiaq4a8zxl6anyhzlyqmz63sj0";
      };
    };
  };

in with builtins.getAttr builtins.currentSystem platform; stdenv.mkDerivation {
  name = "upwork-${version}";
  inherit version src alsaLib nss nspr gconf; 
  libXtst = xorg.libXtst;
  cupslib = cups.lib;
  dbuslib = dbus.lib;
  systemdlib = systemd.lib;
  buildInputs = [ dpkg makeWrapper ];

  unpackPhase = ''
    dpkg -x $src ./
  '';

  installPhase = ''
    mkdir -p $out/bin
    mkdir -p $out/share
    cp -ar ./usr/share/* $out/share

    makeWrapper $out/share/upwork/upwork $out/bin/upwork
  '';

  postFixup = ''
    patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" $out/share/upwork/upwork
    patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" $out/share/upwork/chrome-sandbox
    patchelf --set-rpath $out/share/upwork:$libPath $out/share/upwork/upwork
    patchelf --set-rpath $out/share/upwork:$libPath $out/share/upwork/libcef.so

    patchelf \
      --add-needed $nss/lib/libnss3.so \
      --add-needed $nss/lib/libnssutil3.so \
      --add-needed $nss/lib/libsmime3.so \
      --add-needed $nspr/lib/libnspr4.so \
      --add-needed $cupslib/lib/libcups.so.2 \
      --add-needed $(readlink -f $alsaLib/lib/libasound.so.2) \
      --add-needed $(readlink -f $gconf/lib/libgconf-2.so.4) \
      --add-needed $(readlink -f $libXtst/lib/libXtst.so.6) \
      $out/share/upwork/libcef.so

    patchelf \
      --add-needed $nss/lib/libnss3.so \
      --add-needed $nss/lib/libnssutil3.so \
      --add-needed $nss/lib/libsmime3.so \
      --add-needed $nspr/lib/libnspr4.so \
      --add-needed $cupslib/lib/libcups.so.2 \
      --add-needed $(readlink -f $alsaLib/lib/libasound.so.2) \
      --add-needed $(readlink -f $gconf/lib/libgconf-2.so.4) \
      --add-needed $(readlink -f $libXtst/lib/libXtst.so.6) \
      --add-needed $(readlink -f $dbuslib/lib/libdbus-1.so.3) \
      --add-needed $(readlink -f $systemdlib/lib/libudev.so) \
      $out/share/upwork/upwork

    function soCheck {
        echo "Checking $1 for missing linked libraries..."
        ! ldd $1 | grep -v "libGL" | grep "not found"
    }

    soCheck $out/share/upwork/upwork
    soCheck $out/share/upwork/chrome-sandbox
    soCheck $out/share/upwork/libcef.so
  '';

  libPath = stdenv.lib.makeLibraryPath [
    stdenv.cc.cc.lib
    stdenv.glibc.out
    xorg.libX11
    xorg.libXScrnSaver
    xorg.libXi
    xorg.libXinerama
    xorg.libXcursor
    xorg.libXext
    xorg.libXfixes
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXrandr
    xorg.libXrender
    glib
    gtk2
    atk
    pango
    cairo
    gdk_pixbuf
    freetype
    fontconfig
    gtkglext
    dbus
    mesa_glu
    expat
  ];

  meta = {
    homepage = https://www.upwork.com/downloads;
    description = "Desktop application for Upwork freelancers to track time and connect with clients.";
    license = stdenv.lib.licenses.unfree;
    platforms = builtins.attrNames platform;
  };
}
```

### Feedback

I'm interested in getting some feedback, especially given it's my first package. In particular:

1. What should I set the maintainer to?
2. Does it run on 32-bit Linux? I prepared the package to download the 32-bit dep package, but I just haven't tested it.
3. There are hard-coded paths in the binaries. Other than using `buildFHSChrootEnv` I don't know of a way to fix this.

**Comment by emmanuelrosa** [comment]
Ugh! Unfortunately it's unlawful to distribute this binary. Closing...

**Comment by peterhoeg** [comment]
Even if we cannot distribute the binary, there is no reason the user cannot download it himself and then do it from there. That's a fairly common approach for proprietary software (see Citrix as an example). Also, if you do choose to move ahead with this, please open it as a proper PR as that gives us the option of commenting on individual lines. I have a few comments, so feel free to ping me if you do go ahead with the PR.

**Comment by marad** [comment]
@emmanuelrosa +1 for what @peterhoeg wrote. I'd like to use nixos but can't get Upwork app to run :(

**Comment by emmanuelrosa** [comment]
Alright thank you for speaking up. I've got it mostly working. The remaining issue is that the text in the menu shows up as boxes. I'm not sure if I'm missing a font or what.I'll have to do some stracing on Ubuntu to compare.On Oct 29, 2017 12:15 PM, Marcin Radoszewski <notifications@github.com> wrote:@emmanuelrosa +1 for what @peterhoeg wrote. I'd like to use nixos but can't get Upwork app to run :(

**Comment by qrilka** [comment]
@emmanuelrosa do you have any updates on this? Do you plan to open another PR?

**Comment by emmanuelrosa** [comment]
I was unable to resolve the GTK2 font issue; The text on the main interface (which uses Chrome) renders fine, but the menu text (which uses GTK2) render as tiny boxes.

In addition, I'm no longer an Upwork freelancer, so no, I won't be opening another PR.

**Comment by qrilka** [comment]
@emmanuelrosa but could you share you last nix source as a gist maybe?
BTW current version of upwork in Gentoo shows the same "feature"

**Comment by emmanuelrosa** [comment]
Sure, [here's](https://gist.github.com/emmanuelrosa/d74fd1803580cd42d7639b8f7d82f74b) a gist, and `[here's](https://github.com/emmanuelrosa/nixpkgs/commits/upwork/pkgs/applications/networking/instant-messengers/upwork/default.nix)` the history of what I did.

I was able to run the app successfully on Ubuntu 14, which is super old. But I noticed that Ubuntu builds some libraries with options that differ from how the same libraries are build on NixOS. For example, on Ubuntu pango includes libthai. I [created](https://github.com/emmanuelrosa/nixpkgs/commits/upwork-libthai) a version of pango with libthai, but that didn't solve the problem.

Good luck, I hope you figure it out. Devs have been asking Upwork to be able to run the app on Linux distros other than the two (old) supported ones. So if this thing can be made to work on Nix, then that means it would work on just about any distro.

**Comment by dambaev** [comment]
Hi. sorry for necroposting, but I have nix expression for current version of upwork's time tracker. I am still not experienced nix user, so I don't create PR for now, as I am not sure if it is suitable for PR already, but still, it can be useful for someone: https://github.com/dambaev/upwork-overlay

**Comment by peterhoeg** [comment]
I don't know if anybody uses upwork, but I generally find that it's easier to maintain things as part of upstream nixpkgs as opposed to having it live outside in separate patches or an overlay.

 From a cursory glance at your overlay, it's pretty close to being mergeable, so I'll strongly advise you to open a PR (with yourself as the maintainer please).

Two comments:
- you can use autopatchelfhook instead of the manual patchelf invocation.
- dpkg should go into nativeBuildInputs

**Comment by dambaev** [comment]
Thanks for your comments, I will improve it and open PR

**Comment by zakkor** [comment]
They recently updated it, changing the directory structure completely, where the binary lives in /opt now.
Here's my version, it's just another wrapped electron app that I got somewhere from nixpkgs, adapted for Upwork:

```
{ stdenv, fetchurl, dpkg, wrapGAppsHook
, alsaLib, atk, at-spi2-atk, at-spi2-core, cairo, cups, dbus, expat, fontconfig, freetype
, gdk-pixbuf, glib, gtk3, libnotify, libX11, libXcomposite, libXcursor, libXdamage, libuuid
, libXext, libXfixes, libXi, libXrandr, libXrender, libXtst, nspr, nss, libxcb
, pango, systemd, libXScrnSaver, libcxx, libpulseaudio }:

stdenv.mkDerivation rec {
  name = "upwork-${version}";
  version = "5.3.3-883";

  src = fetchurl {
    url = https://updates-desktopapp.upwork.com/binaries/v5_3_3_883_1f817bc1fefd44e7/upwork_5.3.3.883_amd64.deb;
    sha256 = "072zns79w4h46bvbj23rvr8i12sf2l378ry0z3hchwcimkrph9wx";
  };

  nativeBuildInputs = [ 
    dpkg
    wrapGAppsHook
  ];

  dontWrapGApps = true;

  libPath = stdenv.lib.makeLibraryPath [
    libcxx systemd libpulseaudio
    stdenv.cc.cc alsaLib atk at-spi2-atk at-spi2-core cairo cups dbus expat fontconfig freetype
    gdk-pixbuf glib gtk3 libnotify libX11 libXcomposite libuuid
    libXcursor libXdamage libXext libXfixes libXi libXrandr libXrender
    libXtst nspr nss libxcb pango systemd libXScrnSaver
   ];

  unpackPhase = ''
    dpkg-deb -x ${src} ./
  '';

  installPhase = ''
    mv usr $out
    mv opt $out
    sed -e "s|/opt/|$out/opt/|g" -i $out/share/applications/upwork.desktop
    patchelf --set-interpreter ${stdenv.cc.bintools.dynamicLinker} \
        $out/opt/Upwork/upwork

    wrapProgram $out/opt/Upwork/upwork \
        "''${gappsWrapperArgs[@]}" \
        --prefix XDG_DATA_DIRS : "${gtk3}/share/gsettings-schemas/${gtk3.name}/" \
        --prefix LD_LIBRARY_PATH : ${libPath}
  '';
}
```

**Comment by peterhoeg** [comment]
Sure, just open a PR. My comment from earlier still stands though:

> - you can use autopatchelfhook instead of the manual patchelf invocation.

**Comment by zakkor** [comment]
Thanks a lot! I've implemented your suggested changes and opened a pull request at https://github.com/NixOS/nixpkgs/pull/85396
