### ISSUE TITLE
Package request: cups-idprt

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#306560]
**Project description**

CUPS drivers for iDPRT label printers

**Metadata**

* homepage URL: https://www.idprt.com/
* source URL: https://www.idprt.com/Driver/ / https://www.idprt.com/downloads/
* license: proprietary
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
There is no need to create an issue for a software you are packaging. Create the package right away.

**Comment by Pandapip1** [comment]
> There is no need to create an issue for a software you are packaging. Create the package right away.

I wasn't planning on packaging the software. I opened this issue last week.
