### ISSUE TITLE
homepage-dashboard service is automatically disabled (start script broken)

### ISSUE THREAD

**Issue by zoechi** [NixOS/nixpkgs#306596]
### Describe the bug

I added `services.homepage-dashboard` to my config with a minimal config for `bookmarks` and `services`.
systemd automatically disables the service after a start attempt.

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior
The created systemd service `homepage-dashboard.service` should be startable

### Screenshots
N/A

### Additional context

The script invoked from `homepage-dashboard.service` `exec` seems invalid

```sh
❯ sudo cat /nix/store/9vxkymwdpzxhbihf430q7cqbss3gnjz1-homepage-dashboard-0.8.11/bin/homepage
#! /nix/store/a1s263pmsci9zykm5xcdf7x9rv26w6d5-bash-5.2p26/bin/bash -e
export PORT=${PORT-'3000'}
export HOMEPAGE_CONFIG_DIR=${HOMEPAGE_CONFIG_DIR-'/var/lib/homepage-dashboard'}
exec "/nix/store/9vxkymwdpzxhbihf430q7cqbss3gnjz1-homepage-dashboard-0.8.11/share/homepage/server.js"  "$@"
```

The prefix `HOMEPAGE_CONFIG_DIR-` seems invalid.
The line should just be
`export HOMEPAGE_CONFIG_DIR='/var/lib/homepage-dashboard'`

### Notify maintainers
@jnsgruk (I hope it's ok to ping you for this)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.27, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jnsgruk** [comment]
Hey!

I think the script is correct, and it's been working fine for me for a few months.

Can you post the logs from the journal for the service please?

**Comment by zoechi** [comment]
I'm very sorry. This was my own fault.
I didn't know the default-value syntax for bash variables, so this code confused me.
In the end it was a listen port collision.
