### ISSUE TITLE
Teamviewer daemon not running

### ISSUE THREAD

**Issue by Krofek** [NixOS/nixpkgs#30659]
## Issue description

> services.teamviewer.enable = true

Latest teamviewer installed correctly but I keep on recieving Teamviewer daemon is not running error upon running the gui.
The service is running correctly: systemctl status teamviewerd (active -> running).

> teamviewerd.service - TeamViewer remote control daemon
   Loaded: loaded (/nix/store/2d17ncldgqss252yayd5zrkl28mbr3gz-unit-teamviewerd.service/teamviewerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-10-21 18:03:18 CEST; 31min ago
  Process: 9029 ExecStart=/nix/store/9pcp93zh8zad22rc2gvsv12gls67hy1y-teamviewer-12.0.85001/bin/teamviewerd -d (code=exited, status=0/SUCCESS)
  Process: 9027 ExecStartPre=/nix/store/zmh1jdi1nl93axj06c0l0y8k80zc2axj-unit-script/bin/teamviewerd-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 9031 (teamviewerd)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/teamviewerd.service
           └─9031 /nix/store/9pcp93zh8zad22rc2gvsv12gls67hy1y-teamviewer-12.0.85001/bin/teamviewerd -d
Oct 21 18:03:18 krofox systemd[1]: Starting TeamViewer remote control daemon...
Oct 21 18:03:18 krofox systemd[1]: teamviewerd.service: PID file /run/teamviewerd.pid not readable (yet?) after start: No such file or directory
Oct 21 18:03:18 krofox systemd[1]: Started TeamViewer remote control daemon.

The version is newer than in the nixpkgs since I tried updating to a newer version to see if the error persists.
Is anyone else running into this issue?

### Steps to reproduce

services.teamviewer.enable = true;

## Technical details

* System: 18.03.git.dddd31d (Impala)
* Nix version:  1.11.15
* Nixpkgs version: 18.03.git.dddd31d56bM
* Sandboxing enabled: build-use-sandbox = false

**Comment by globin** [comment]
cc @fadenb

**Comment by fadenb** [comment]
@Krofek 12.0.76279 is working fine for me, I can reproduce the issue with 12.0.85001.

I will try to get hold of the colleague in charge of the Linux releases. There are some major changes coming soon(ish) so debugging this will be quite low on the priority list. 

Disclaimer: Although I am currently employed by TeamViewer this is not done in any official capacity. Feel free to address this additionally via the official support channels ;)

**Comment by Krofek** [comment]
The issue was idiotic, sorry. I had to remove ~/.local/share/teamviewer*. Then it started working again. Sorry for my idiocy and thank you for your time @fadenb
