### ISSUE TITLE
Build failure: snes9x-gtk

### ISSUE THREAD

**Issue by rotten777** [NixOS/nixpkgs#306639]
### Steps To Reproduce

1. added  snes9x-gtk to config and performed rebuild

### Build log

[snes9x-gtk build log.txt](https://github.com/NixOS/nixpkgs/files/15100372/snes9x-gtk.build.log.txt)

### Additional context

Running on unstable if that makes a difference

### Notify maintainers

@KamilaBorowska 
@thiagokokada 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre615148.6143fc5eeb9c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

**Comment by AndersonTorres** [comment]
Where is the build log?

**Comment by rotten777** [comment]
> Where is the build log?

I'm a bit of an idiot but is the attachment not it? Sorry first time filing one of these.

**Comment by AndersonTorres** [comment]
Oh I see. GH removed the clickable link.
