### ISSUE TITLE
GNOME does not have a cursor style by default

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#306678]
### Describe the bug

When installing recent versions of NixOS (unstable within the last couple of months or so), GNOME seems to be installed without the default Adwaita cursor theme.

### Steps To Reproduce

1. Install NixOS with GNOME

### Expected behavior

Cursors should have a reasonable size and shape in most applications by default.

### Additional context

Workaround: In GNOME Tweaks → Appearance, set the cursor style from "" (nothing) to "Adwaita _(default)_". Alternatively, set

```
programs.dconf.profiles.user.databases = [
  {
    settings."org/gnome/desktop/interface".cursor-theme = "Adwaita";
  }
];
```

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre615148.6143fc5eeb9c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Maybe some app unsets it? I recall KDE Plasma messing up some GNOME theme settings in the past.

Adwaita is the default value in the schema:

https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/blob/b5ef1fcf0be8d60b3c24e8faf231df3bc810b7e4/schemas/org.gnome.desktop.interface.gschema.xml.in#L181

Are you able to reproduce it in a clean VM/fresh install from the get go?

**Comment by l0b0** [comment]
Closing as this hasn't happened for a long time.
