### ISSUE TITLE
Build failure: pikepdf

### ISSUE THREAD

**Issue by CorbanR** [NixOS/nixpkgs#306651]
### Steps To Reproduce

1. Build pikepdf

### Build log

```
error: builder for '/nix/store/dzvr9f8mficrdm3wihrvb07zsdbfssi5-python3.9-pikepdf-8.13.0.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'pikepdf-8.13.0.dist-info/top_level.txt'
       > adding 'pikepdf-8.13.0.dist-info/RECORD'
       > removing build/bdist.macosx-11.0-arm64/wheel
       > Successfully built pikepdf-8.13.0-cp39-cp39-macosx_11_0_arm64.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for pikepdf-8.13.0-cp39-cp39-macosx_11_0_arm64.whl
       >   - lxml<5,>=4.8 not satisfied by version 5.1.0
       For full logs, run 'nix log /nix/store/dzvr9f8mficrdm3wihrvb07zsdbfssi5-python3.9-pikepdf-8.13.0.drv'.
```

### Additional context

Looks like this maybe fixed by upgrading to latest pikepdf see https://github.com/pikepdf/pikepdf/blob/main/docs/releasenotes/version8.rst (Relaxed dependency requirements on lxml.......)

### Notify maintainers
@Kiwi @dotlambda 
### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/7b7m3p9gc9da6cd7wgyabs3wg1832j0v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
@CorbanR I can reproduce the build issue using `nix-build -A python39Packages.pikepdf` on `x86_64-linux`

these do build
```
[kirillvr@tsutenkaku:~/nixpkgs]$ nix-build -A python310Packages.pikepdf
/nix/store/q4q06lrr411qh85sdm6k91mapdqd38fa-python3.10-pikepdf-8.13.0

[kirillvr@tsutenkaku:~/nixpkgs]$ nix-build -A python311Packages.pikepdf
/nix/store/srfyfgn1a39asnf6kq3v004zqg2nayjf-python3.11-pikepdf-8.13.0

[kirillvr@tsutenkaku:~/nixpkgs]$ nix-build -A python312Packages.pikepdf
/nix/store/dlmlcza8fqx2bpx2p9c02vss1gy773xm-python3.12-pikepdf-8.13.0
```

currently only 3.11 and 3.12 build in CI,  are you able to use newer python ?

**Comment by CorbanR** [comment]
@kirillrdy unfortunately no, in this case pikepdf happens to be a dependency of another library or program. I'm still trying to figure out which dependency requires pikepdf.

**Comment by CorbanR** [comment]
Trying to use `nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix {attrs=pkgs.attrs; buildPythonPackage=pkgs.buildPythonPackage; deprecated=pkgs.deprecated; hypothesis=pkgs.hypothesis; lxml=pkgs.lxml; mupdf-headless=pkgs.mupdf-headless; numpy=pkgs.numpy; packaging=pkgs.packaging; pillow=pkgs.pillow; psutil=pkgs.psutil; pybind11=pkgs.pybind11; pytest-xdist=pkgs.pytest-xdist; pytestCheckHook=pkgs.pytestCheckHook; python-dateutil=pkgs.python.dateutil; python-xmp-toolkit=pkgs.python-xmp-toolkit; pythonOlder=pkgs.pythonOlder; setuptools=pkgs.setuptools;}'` to build the `default.nix` but am having issues with `pkgs.buildPythonPackage` anyone have any suggestions on how I can build this locally? I want to try and upgrade the package and `path.patch`.

**Comment by kirillrdy** [comment]
@CorbanR can you test https://github.com/NixOS/nixpkgs/pull/308625 ?

**Comment by CorbanR** [comment]
@kirillrdy that appears to work!

**Comment by kirillrdy** [comment]
should be resolved now
