### ISSUE TITLE
Dependency `gvfs` missing from `swaynotificationcenter`

### ISSUE THREAD

**Issue by fdnt7** [NixOS/nixpkgs#306613]
### Describe the bug
`swaynotificationcenter` (still as of `0.10.1` at the time of writing, but ever since `0.10.0`) is missing the runtime dependency `gvfs` which, [quoting the maintainer of the project](https://github.com/ErikReider/SwayNotificationCenter/issues/144#issuecomment-1857693852), is required to fix [MPRIS covers not showing](https://github.com/ErikReider/SwayNotificationCenter/issues/310) (which is the issue I am experiencing).

### Steps to reproduce the behaviour, Expected behaviour, Actual behaviour & Screenshots
Please take a look at the original issue on the upstream repository linked prior, as everything mentioned there is identical (to the behaviour on my machine).

### Additional context
I have read on the [discussion on `0.9.0` -> `0.10.0` PR](https://github.com/NixOS/nixpkgs/pull/290627) and [__leon-erd__'s question](https://github.com/ErikReider/SwayNotificationCenter/issues/377#issuecomment-1961305608) which I saw was left unresponded. This issue was opened to hopefully clear up the need for this missing dependency.
This is my first time contributing to `nixpkgs`, so I want to apologise in advance in case I am doing anything wrong here.
### Notify maintainers

@teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre615148.6143fc5eeb9c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
feel free to patch the package, I can't look into it :(
