### ISSUE TITLE
Wrong path in usbimager

### ISSUE THREAD

**Issue by guzz46** [NixOS/nixpkgs#306704]
## Issue description
When installing usbimager the path in the desktop file is /usr/bin/usbimager, so when you try to open the application it doesn't open, to fix it you have to copy the desktop file from /run/current-system/sw/share/applications/usbimager.desktop to ~/.local/share/applications and edit the desktop so it reads Exec=usbimager

### Steps to reproduce
Install usbimager, try to open the application from your menu, at least this is the behaviour on xfce, I've not tested it on other desktop environments

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05pre615930.572af610f615`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by IldenH** [comment]
Does it work in a nix-shell?

nix-shell -p usbimager
usbimager

Worked perfectly for me on hyprland.

**Comment by guzz46** [comment]
It works in a shell, it also works when installed system wide when you launch it from a terminal, its when you try and launch it from a menu like xfce's whiskermenu it doesn't launch, because the desktop file has Exec=/usr/bin/usbimager
