### ISSUE TITLE
Build failure: coreutils (shred test failure on bcachefs)

### ISSUE THREAD

**Issue by jcaesar** [NixOS/nixpkgs#306760]
### Steps To Reproduce

1. Have the store on bcachefs
2. Build coreutils

### Build log

```
FAIL: tests/shred/shred-exact
=============================

shred: file.slop: error writing at offset 1048576
FAIL tests/shred/shred-exact.sh (exit status: 1)
```
([full log](https://gist.github.com/jcaesar/94c4305d8adbe0fab9df1579e5aaafab))

### Additional context

Working workaround:
```nix
overlays = [
  (final: prev: {
    coreutils = prev.coreutils.overrideAttrs (prev: {
      postPatch = prev.postPatch + ''
        sed '2i echo Skipping due to failure on bcachefs && exit 77' -i ./tests/shred/shred-exact.sh
      '';
    });
  })
];
```
I suppose the fix is similarly trivial, but I'm a bit too green to nixpkgs to feel comfortable with submitting a mass rebuild fix for something that most people won't ever notice… Should I?

I suppose I should also report this upstream, but I haven't tested yet whether it can be reproduced outside of nix.

### Notify maintainers

@dasJ

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), j_7ccd2d5_20240420060512`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/wmcbdvplkli110vmdn1ci96n8zmzh7yn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
This is quite obviously an issue of upstream bcachefs and/or coreutils.

Nothing we can do about that on the Nixpkgs side; we won't disable a test that passes on stable filesystems for a new experimental filesystem that is expected to break in ways like this.

**Comment by JohnRTitor** [comment]
Fixed in upstream https://github.com/koverstreet/bcachefs-tools/issues/270#issuecomment-2138225838
