### ISSUE TITLE
Package request: ringracers

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#306707]
**Project description**

Dr. Robotnik's Ring Racers is a kart racing video game originally based on the 3D Sonic the Hedgehog fangame [Sonic Robo Blast 2](https://srb2.org/), itself based on a modified version of [Doom Legacy](http://doomlegacy.sourceforge.net/).

**Metadata**

* homepage URL: https://kartkrew.org
* source URL: https://github.com/KartKrewDev/RingRacers or https://git.do.srb2.org/KartKrew/RingRacers
* license: gpl2+
* platforms: linux

---
cc @donovanglover (this is kart v2)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Done. Test it out and let me know if you encounter any issues :+1:
