### ISSUE TITLE
Build failure: localstack 3.2.0

### ISSUE THREAD

**Issue by zaporter-work** [NixOS/nixpkgs#306848]
### Steps To Reproduce

1. build localstack (from unstable) (version 3.2.0)

https://github.com/NixOS/nixpkgs/blob/572af610f6151fd41c212f897c71f7056e3fb518/pkgs/development/python-modules/localstack/default.nix#L73

shell.nix:
```
{pkgs ? import <nixpkgs> {}}: let
  unstableTarball =
    fetchTarball
    https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz;
  pkgs = import <nixpkgs> {};
  unstable = import unstableTarball {};
in
  pkgs.mkShell {
    nativeBuildInputs = with pkgs; [
      unstable.localstack
    ];
  }

```

### Build log

https://gist.github.com/zaporter-work/1b05228b0a3a0647fd04a24f4ae62ca6

### Additional context

localstack 2.3.0 works and so does [this pinned 3.0.0 version](https://lazamar.co.uk/nix-versions/?package=localstack&version=3.0.0&fullName=localstack-3.0.0&keyName=localstack&revision=c407032be28ca2236f45c49cfb2b8b3885294f7f&channel=nixpkgs-unstable#instructions)

### Notify maintainers

@jonringer 
@mweinelt  (tagged because you bumped the version)

### Metadata

(the channel is slightly messed up. I am using 23.11 but with flakes)
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.71, NixOS, 23.11 (Tapir), 23.11.20240110.3dc440f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/etc/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
The new version requires too many dependencies to package up in a reasonable time frame and even includes circular ones.

https://github.com/NixOS/nixpkgs/pull/306878 contains a revert to 3.0.0 which builds for me and shows the usage. Can you take a look if that works for you?

**Comment by zaporter-work** [comment]
Sorry for the delay! Yes, the revert works well for me! Thank you!
