### ISSUE TITLE
Zorba glib-2.0 not found

### ISSUE THREAD

**Issue by StillerHarpo** [NixOS/nixpkgs#30683]
## Issue description
I'am trying to package zorba(http://www.zorba.io/documentation/latest/zorba/build/build_prerequisites/)
in the configurePhase i get the error
`configure:` error: glib-2.0 not found or version too old (must be >= 2.12)
I've already tried to add glib to nativebuildInputs

### Steps to reproduce
run nix-build with (https://github.com/StillerHarpo/nixbuilds/blob/master/zorba/default.nix) in folder

## Technical details

* System: 17.03.1820.a0e6a891ee (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1820.a0e6a891ee"
* Sandboxing enabled: build-use-sandbox = false

**Comment by jtojnar** [comment]
Try `glib.dev`, the pkgconfig files are in there.

**Comment by StillerHarpo** [comment]
I tried this things separately so far
- added `glib.dev` to  `nativebuildInputs`
- added path for `glib.dev` id `preConfigue` to the `PATH`
- added path  `glib.dev/pkgconfig` to the `PATH`

I still get the same error

**Comment by jtojnar** [comment]
Apparently you have used hash of midnight commander tarball so that is why glib was required.

Something like this should work better:

```nix
with import <nixpkgs> {};
let
  version = "3.0";
  # libs = stdenv.lib.makeLibraryPath [ glibc ];
in
stdenv.mkDerivation rec {
  name = "zorba-${version}";

  src = fetchurl {
    url = "http://launchpad.net/zorba/trunk/3.0/+download/${name}.tar.gz";
    sha256 = "1zldanlvqbd0p105mpkbwbcmvvknf687qbfw407x88nm3vhkrrwa";
  };

  nativeBuildInputs = [ cmake ninja flex bison ];
  buildInputs = [ libxml2 libuuid xercesc icu curl libxslt ];

  meta = with stdenv.lib; {
    description = "NoSQL(XQuery/JSONiq) Query Processor written in C++.";
    homepage = http://www.zorba.io/;
    license = licenses.apache;
    platforms = platforms.unix;
    maintainers = [ maintainers.florian ];
  };
}
```

**Comment by jtojnar** [comment]
@StillerHarpo do you still need it or can we close this?

**Comment by StillerHarpo** [comment]
You can close this.

**Comment by StillerHarpo** [comment]
I don't need it anymore
