### ISSUE TITLE
buildMozillaMach: perhaps should not delete `configure`

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#306937]
### Describe the bug
`firefox-unwrapped`'s `preConfigure` (via `buildMozillaMach`) deletes the `configure` and `js/src/configure` files. Apparently this shouldn't be done any more? I'm not really equipped to determine whether the current behaviour is correct or not, apologies if this is noise.

### Additional context
https://matrix.to/#/!ykhjAGdElNmYcYkwvB:mozilla.org/$dZTZWQ20DdPGfvd4QOgQSog69-lpkNZUsk9oVWXBTGw?via=mozilla.org&via=matrix.org&via=tchncs.de:

> perhaps the script is outdated.  `configure` file is now a part of the source, not a generated file, and they shouldn't be removed
> (they had been generated during build before)

Primarily this makes life awkward when working from a local checkout via `nix develop nixpkgs#firefox-unwrapped`. Other issues include the setting of $MOZ_OBJDIR and $MOZBUILD_STATE_PATH to be within the build directory because hg complains that build artifacts and configuration are untracked (the former would be fine, if the directory name started with `obj`).

### Notify maintainers

@mweinelt

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
I think I have addressed all concerns you mentioned. Please take a look at the pull request.
