### ISSUE TITLE
qq: login info is reset upon rebooting

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#306930]
### Describe the bug
After logging in QQ (scan QR code using mobile QQ; check "remember login status for future"), I can use it normally. After exiting the app completely, I can log in again without using mobile QQ. However, if I reboot, then the login status is lost, and I have to use mobile QQ to scan the QR code again to log in.

### Steps To Reproduce
1. Install `qq` package from master branch.
2. Log in, check the checkbox for remembering login status.
3. Reboot, and log in QQ again.

### Expected behavior
I should log in without needing to use mobile QQ.

### Notify maintainers

@fee1-dead 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.86, NixOS, 23.11 (Tapir), 23.11.6359.53a2c32bc66f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Are you using impermanence or any root-on-tmpfs scheme?

**Comment by UlyssesZh** [comment]
No.

**Comment by ForkKILLET** [comment]
Same. Always detected as a new device when logging in.

**Comment by UlyssesZh** [comment]
Seems to have been fixed. @ForkKILLET Do you still have this problem?

**Comment by ForkKILLET** [comment]
> Seems to have been fixed. @ForkKILLET Do you still have this problem?

No, it's fixed.
