### ISSUE TITLE
Should "emacsWrapper" also wrap PATH and PYTHONPATH?

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#30705]
## Issue description
Currently `emacsWrapper` wraps the ` $EMACSLOADPATH` environment variable. I also think it would be useful to wrap other environment variables such as `$PATH` and  `$PYTHONPATH`.

This would make it a whole lot easier and intuitive to work with certain modes like `flycheck` which checks `$PATH` for checkers and linters and `jedi-mode` which requires some python dependencies both in `$PATH` and `$PYTHONPATH`.

I want to be able to add non-elisp packages to `emacsWithPackages` and have things just work.

## Technical details

* System:
18.03.git.fd3bb25895M (Impala)
* Nix version:
nix-env (Nix) 1.11.15
* Nixpkgs version:
"18.03.git.fd3bb25895M"

**Comment by peterhoeg** [comment]
The problem with that approach is that we would potentially need to wrap everything in existence.

I use a combination of emacs, direnv and emacs-direnv to set up things up on a project level. Works OK so far.

**Comment by bkchr** [comment]
I also use direnv and emacs-direnv to load all the required tools into the path for emacs. That works relative good.

**Comment by adisbladis** [comment]
Direnv + emac-direnv sounds like a very nice combination but it doesn't solve the core issue of making non-elisp tooling available.

@peterhoeg What makes you think you'd probably need to "wrap everything in existence"?
Are you thinking about scope creep?

**Comment by peterhoeg** [comment]
> Direnv + emac-direnv sounds like a very nice combination but it doesn't solve the core issue of making non-elisp tooling available.

Actually it does. It means you can have all your python stuff available in one project and haskell in another without them ever stepping on each other and the dependencies defined per project, so whoever else is working on that same project will have everything available as well. 

> I personally want to use the same tooling regardless of project setup.

For some things, sure. So you wrap what you need - I don't think we can decide on what everybody needs which is the problem.

**Comment by yegortimoshenko** [comment]
I'd like `emacsWithPackages` to wrap $PATH, too.

**Comment by jollheef** [comment]
Same thoughts. It'll help make crutches like #67833 not necessary.

**Comment by adisbladis** [comment]
I've since been convinced that wrapping `$PATH` is the wrong thing to do.
