### ISSUE TITLE
Package request: kdotool

### ISSUE THREAD

**Issue by JordanJoel1** [NixOS/nixpkgs#307089]
xdotool-like utility for KDE Wayland using KWin's scripting API to control windows.

**Metadata**

* homepage URL: https://github.com/jinliu/kdotool
* license: Apache-2.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ErrorNoInternet** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/303268
