### ISSUE TITLE
sshguard: service won't start

### ISSUE THREAD

**Issue by bricewge** [NixOS/nixpkgs#30701]
## Issue description
The sshguard service is broken, it won't start. It seems to come from: https://github.com/NixOS/nixpkgs/blob/3211098632bcc0328427d19e2f063e5f3ba139cc/nixos/modules/services/security/sshguard.nix#L109
Since creating the directory by hand solve the issue. However I don't know what is the proper way to do this in NixOS. The last `systemd 235` would have help solving this issue nicely with the new option [`StateDirectory`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) however it isn't updated in `nixpkgs` and it won't be possible to backport it to `17.09`.

```
$ journalctl -xeu sshguard --no-pager
Oct 22 23:52:23 samare systemd[1]: Starting SSHGuard brute-force attacks protection system...
-- Subject: Unit sshguard.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sshguard.service has begun starting up.
Oct 22 23:52:23 samare systemd[4149]: sshguard.service: Failed at step NAMESPACE spawning /nix/store/0ci10h76n5avz1148v0pdn4wy49lzf86-sshguard-2.0.0/bin/sshguard: No such file or directory
-- Subject: Process /nix/store/0ci10h76n5avz1148v0pdn4wy49lzf86-sshguard-2.0.0/bin/sshguard could not be executed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /nix/store/0ci10h76n5avz1148v0pdn4wy49lzf86-sshguard-2.0.0/bin/sshguard could not be executed and failed.
-- 
-- The error number returned by this process is 2.
```

### Steps to reproduce
- `systemctl start sshguard`

## Technical details

* System: 17.09.1789.8fefa85f5c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1789.8fefa85f5c"
* Sandboxing enabled: build-use-sandbox = false

**Comment by MichaelBergquistSuarez** [comment]
I'm still learning nix so I'm not even sure how to test this. It's a long shot. But `mkdir -p /var/lib/sshguard ` is currently defined in `postStart`. Shouldn't it be defined in `preStart`?
