### ISSUE TITLE
NixOS installer cannot detect connection to internet

### ISSUE THREAD

**Issue by Kaldesyvon** [NixOS/nixpkgs#307036]
### Describe the bug
At the first page of NixOS installer I get error that says I am not connected to the Internet. So I connected and it did not recognize that I am on internet although the ping to 8.8.8.8 works

### Steps To Reproduce
1. Have Lenovo V330-ARR (AMD Ryzen 5 2500U/8GB DDR4/256GB SSD)
2. Try to install NixOS from USB

### Expected behavior
Expected behavior should be that installer would detected that I am on Internet

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/48415649/f5a70d56-cda6-4ace-bf48-a761fd656df4)

### Additional context
I tried couple of restarts, other installer mode (debug, copytoram) and also I tried connecting to wire but nothing helped

### Metadata

```console
[nixos@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: "x86_64-linux"
 - host os: Linux 6.1.87, NixOS, 23.11 (Tapir), 23.11.6621.dd37924974b9
 - multi-user?: yes
 - sandbox: yes
 - version: nix-env (Nix) 2.18.1
 - channels(root): "nixos-23.11.6621.dd37924974b9"
 - nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MatthieuBarthel** [comment]
I confirm this issue, the installer doesn't detect network changes. You should be able to get rid of if by closing et reopening the installer

**Comment by Kaldesyvon** [comment]
Yes that worked well. Thank you!
