### ISSUE TITLE
Exec format error when installing bumblebee

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#30702]
## Issue description
When I add bumblebee to my /etc/nixos/configuration.nix and try to rebuild, I get an exec format error:

`building path(s) ‘/nix/store/wbpi4gng0cvcl6i7svfax9397ksx6wvs-NVIDIA-Linux-x86-384.90.run’
building path(s) ‘/nix/store/clkn8k8dvka3fi0qkzfh8d41li9fm5g1-patchutils-0.3.3’
while setting up the build environment: executing ‘/nix/store/wmcrngsxkg8v1vris1fdk1219vdrw3ld-bash-4.4-p12/bin/bash’: Exec format error
builder for ‘/nix/store/c8bj3d1ri1c37l9qql3zdbq01v1d9g1q-NVIDIA-Linux-x86-384.90.run.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/q23b1fsclqnnfslyzfvlh379fayk27xr-nvidia-x11-384.90.drv’: 1 dependencies couldn't be built
killing process 25345
killing process 3739
cannot build derivation ‘/nix/store/87sg5rk2ml5swndsslc68qfbvr5ywrdf-bumblebee-3.2.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jjjjap0lcrkizpmbi9i4jkkiz9rd9wmi-primusrun.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/0ssi68c6jhqz4sxkr2mlxn21kzcbwn20-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kr5z5i7wv80f31zglqahrfxisi837ga8-unit-bumblebeed.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/sn0gd52n3pdhs1xza6i0nigblg4sy4m8-nixos-system-dseNix-18.03pre118328.6d86fcb86d.drv’: 1 dependencies couldn't be built`

### Steps to reproduce
- add ` hardware.bumblebee = { 
    enable = true;
    driver = "nvidia";
  };  
`
- fail to buold

## Technical details

* System: 18.03pre118328.6d86fcb86d (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre118328.6d86fcb86d
* Sandboxing enabled: Nope

**Comment by setupminimal** [comment]
I'm getting the same fundamental error (`while setting up the build environment: executing ‘/nix/store/mf3jxszrlhzpmv1qraxb88fxnffq8mkr-bash-4.4-p12/bin/bash’: Exec format error`) trying to build glslang on nixos-17.09.

Readelf says that the bash executable is a 32-bit executable, and I'm on a 64-bit system. Any ideas?

**Comment by setupminimal** [comment]
I'm getting the same fundamental error (`while setting up the build environment: executing ‘/nix/store/mf3jxszrlhzpmv1qraxb88fxnffq8mkr-bash-4.4-p12/bin/bash’: Exec format error`) trying to build glslang on nixos-17.09.

Readelf says that the bash executable is a 32-bit executable, and I'm on a 64-bit system. Any ideas?

**Comment by cyplo** [comment]
Hey, I got the same error on 19.03 - I think it means that the kernel you're **currently running** doe snot support 32bit emulation. Try booting into the default kernel and then running rebuild from there - this worked for me.

**Comment by gloaming** [comment]
See #51097

**Comment by gloaming** [comment]
This should be resolved by #82006 - please reopen if there's still a problem.
