### ISSUE TITLE
Package request: LXGW WenKai TC

### ISSUE THREAD

**Issue by lebensterben** [NixOS/nixpkgs#307034]
**Project description**

LXGW WenKai TC is the Traditional Chinese Edition of LXGW WenKai, where the latter has already been packaged as [lxgw-wenkai](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lxgw).

**Metadata**

* homepage URL: <https：//github.com/lxgw/LxgwWenKaiTC>
* source URL: <https://github.com/lxgw/LxgwWenkaiTC/releases>
* license: ofl
* platforms: all

---

Below is a *working* package build script I tested locally, which is largely based on `lxgw-wenkai`'s script:

```nix
{
  stdenvNoCC,
  fetchurl,
  lib,
  ...
}:
stdenvNoCC.mkDerivation rec {
  pname = "lxgw-wenkai-tc";
  version = "1.320";
  src = fetchurl {
    url = "https://github.com/lxgw/LxgwWenKaiTC/releases/download/v${version}/${pname}-v${version}.tar.gz";
    hash = "sha256-CF9zwVrNGN0rUCoe54Lk+6GWqVRCbG/XFkbF+0lk7lM=";
  };

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/fonts/truetype
    mv *.ttf $out/share/fonts/truetype

    runHook postInstall
  '';

  meta = with lib; {
    homepage = "https://github.com/lxgw/LxgwWenKaiTC";
    description = "The Traditional Chinese Edition of LXGW WenKai.";
    license = licenses.ofl;
    platforms = platforms.all;
    #maintainers = with maintainers; [ lucius ];
  };
}
```

(I commented out `meta.maintainers` field.）

**Comment by Atemu** [comment]
If that snippet is working, could you turn it into a PR?
