### ISSUE TITLE
Package request: HDOS

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#307154]
**Project description**

HDOS is a propritery client for Old School Runescape that has better performance and graphics 

**Metadata**

* homepage URL: https://hdos.dev/
* source URL: N/A
* license: proprietary
* platforms: linux, darwin, possibly BSDs via Java? 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Misterio77** [comment]
Should be good to go: https://github.com/NixOS/nixpkgs/pull/312710
