### ISSUE TITLE
koodo-reader: Electron ozone flags are not populated on wayland

### ISSUE THREAD

**Issue by szaffarano** [NixOS/nixpkgs#307245]
### Describe the bug

Koodo reader is an electron application, and although the build process [includes the logic](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ko/koodo-reader/package.nix#L80C1-L86C6) to add the proper ozone flags when the app is launched in a Wayland environment, it seems for some reason, it's not working as expected:

```nix
  postFixup = ''
    makeWrapper ${electron}/bin/electron $out/bin/koodo-reader \
      --add-flags $out/share/lib/koodo-reader/resources/app.asar \
      "''${gappsWrapperArgs[@]}" \
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
      --inherit-argv0
  '';
```

```bash
❯ koodo-reader
....
❯ hyprctl clients -j | jq '.[] | select(.class == "koodo-reader") | {class: .class, xwayland: .xwayland}  '
{
  "class": "koodo-reader",
  "xwayland": true
}
```

But launching the app with the required flags, it works:

```bash
❯ koodo-reader --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
...
❯ hyprctl clients -j | jq '.[] | select(.class == "koodo-reader") | {class: .class, xwayland: .xwayland}  '
{
  "class": "koodo-reader",
  "xwayland": false
}
```

The process arguments seem weird:

```bash
❯ pgrep -lfa koo | rg OZO
1369814 /nix/store/3cq9swbfjb53sc92wpksfgmxlbw5w4qj-electron-unwrapped-29.3.0/libexec/electron/electron --enable features=WaylandWindowDecorations}} /nix/store/qw061wrpi9ygkdiw7m7bj8p52wjdhvsr-koodo-reader-1.6.6/share/lib/koodo-reader/resources/app.asar ${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--ozone-platform-hint=auto
```
Notice that the the `add-flags` added by the package are truncated after the first space `...platfirm-hint=auto`. I tried splitting up the flag into two `--add-flags` sentences to avoid spaces:

```nix
  home.packages = with pkgs; [
    (koodo-reader.overrideAttrs {
      postFixup = ''
        makeWrapper ${electron}/bin/electron $out/bin/koodo-reader \
          --add-flags $out/share/lib/koodo-reader/resources/app.asar \
          "''${gappsWrapperArgs[@]}" \
          --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto}}" \
          --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--enable-features=WaylandWindowDecorations}}" \
          --inherit-argv0
      '';
    })
  ];
```

But now it looks l like the process does not pick up the environment variables:

```bash
❮ pgrep -lfa koo | rg OZO
1406606 /nix/store/3cq9swbfjb53sc92wpksfgmxlbw5w4qj-electron-unwrapped-29.3.0/libexec/electron/electron /nix/store/bsfcvl5nd6p8p1cpv2vmx2h6y4ms7qz8-koodo-reader-1.6.6/share/lib/koodo-reader/resources/app.asar ${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--ozone-platform-hint=auto}} ${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--enable-features=WaylandWindowDecorations}}

❯ echo $NIXOS_OZONE_WL
1
❯ echo $WAYLAND_DISPLAY
wayland-1
❯ echo "${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--enable-features=WaylandWindowDecorations}}"
--enable-features=WaylandWindowDecorations
```
The variables exist, I define them as `environment.sessionVariables`.

Changing the above override to explicitly set the ozone flags (without the shell expansion conditional) works. Other packages like [kuro](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/kuro/default.nix#L61-L64) do the same shell expansion, and they also work in my environment without overriding anything.

### Steps To Reproduce

1. Install `koodo-reader` in a wayland environment (I'm using hyprland)
2. Check if the application is using xwayland by running
```bash
hyprctl clients -j | jq '.[] | select(.class == "koodo-reader") | {class: .class, xwayland: .xwayland}'
```
4. It shows `"xwayland": true`

### Expected behavior

1. Launch the application again but with the ozone flags
```bash
❯ koodo-reader --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
```
2. Now the app does not use xwayland: `"xwayland": false`

### Notify maintainers

@TomaSajt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/9wnvhjyxjykwn5y06xc9a2h8rs5fbfia-stdenv-linux
copying path '/nix/store/9wnvhjyxjykwn5y06xc9a2h8rs5fbfia-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240423.572af61`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/m5i890m2g4pnyflpn48d1dpzzmwp5q4p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
I'm not a wayland user, so I usually just copy this line from other electron apps' definitions and hope it works. I think the issue here is that when `wrapGAppsHook` is present `makeWrapper` will use the binary implementation, which doesn't expand shell variables, thus not making this work. It looks like I forgot about this behaviour when packaging this.
