### ISSUE TITLE
dockerTools: custom pre- and post-procesing for docker images

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#30725]
Currently docker images are built as .tar archives. I'd like to compress them after build (and decompress in next `buildImage`) before storing to `/nix/store`, because disk space can inflate fast when I have many images around. For this I'd like `dockerTools.buildImage` to support:

- `postProcess` argument (for example, `${pkgs.gzip}/bin/gzip -1 $image`)
- `preProcess` argument (for example, `tar -tzf $image && ${pkgs.gzip}/bin/gunzip $image`)

Main benefits are reduce store size (and therefore network transfers) and less problems with https://github.com/NixOS/nix/issues/358

**Comment by copumpkin** [comment]
Alternately, if we didn't tar them up at all, the store optimization/hardlinking process could save a ton of space

**Comment by danbst** [comment]
Or even
```
/nix/store/$image/manifest.json
/nix/store/$image/layer1 -> /nix/store/$layer1
/nix/store/$image/layer2 -> /nix/store/$layer2
/nix/store/$image/layer3 -> /nix/store/$layer3
```
Then loading image would be like
```
docker load < $(tar -ch /nix/store/$image)
```
And if we set default `postProcess` to `tar -ch $image` we will even have backward compatible API.

**Comment by copumpkin** [comment]
That would be pretty cool!

**Comment by danbst** [comment]
Actually, I've overlooked things... There is already compression/decompression built-in
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/default.nix#L542

I'll leave this issue open for other two ideas, probably I'll have time to return back later.

**Comment by danbst** [comment]
This is outdated now, as `dockerTools.buildLayeredImage` does compress by default.
