### ISSUE TITLE
Build failure: diffoscope

### ISSUE THREAD

**Issue by aij** [NixOS/nixpkgs#307280]
### Steps To Reproduce

1. build *diffoscope*

### Build log

These tests are failing
```
FAILED tests/comparators/test_elf_decompiler.py::test_ghidra_diff - IndexError: list index out of range
FAILED tests/comparators/test_elf_decompiler.py::test_radare2_diff - AssertionError
FAILED tests/comparators/test_macho_decompiler.py::test_ghidra_diff - assert 0 == 1
FAILED tests/comparators/test_macho_decompiler.py::test_radare2_diff - AssertionError
```

Full build log at https://gist.github.com/aij/a6197c225a3b1c73b50369503537e98c

### Additional context

I haven't done a git bisect yet, but it built fine on `0a0027cb7c11e9cf5521266f88b5e72a0e7ed331` and is now failing on `nixos-unstable-small` at commit `9d3911e28686eae1dbbdadf6c5e6c260845c7be0`

### Notify maintainers

@dezgeg @danielfullmer @RaitoBezarius

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.11, NixOS, 24.05 (Uakari), 24.05.git.0a0027cb7c11`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/aij/unstable`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
builds fine on 7bb2ccd8cdc44c91edba16c48d2c8f331fb3d856 as well fwiw
