### ISSUE TITLE
Update request: lunacy 0.9.5 → 0.9.6

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#307402]
- Package name: `lunacy`
- Latest released version: 0.9.6

- Current version on the unstable channel: 0.9.5
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@eliandoran 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
This should be 9.5.0 -> 9.6.0 right?

**Comment by Anifyuli** [comment]
> This should be 9.5.0 -> 9.6.0 right?

Yes, off course. In Flatpak version is updated to 0.9.6 version number.

**Comment by Anifyuli** [comment]
Thanks for your hardware, everyone
