### ISSUE TITLE
AMI ami-0fc7825fe890f87d1 (NixOS 23.05) missing from AWS region eu-west-1

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#307519]
The AMI for NixOS 23.05 in `eu-west-1` does not exist.

This is the AMI shown on the NixOS home page (getting-started page):

![image](https://github.com/NixOS/nixpkgs/assets/399535/a503aa80-75bf-4949-8379-10f3e0696f09)

NixOps complains:

```
Exception: AMI ‘ami-0fc7825fe890f87d1’ does not exist in region ‘eu-west-1’
```

https://github.com/NixOS/nixpkgs/blob/07971d69f7530bcb41644c965edd6193cf1ad850/nixos/modules/virtualisation/amazon-ec2-amis.nix#L544

And indeed `aws` shows the AMI does not exist:

```
% aws ec2 describe-images --image-ids=ami-0fc7825fe890f87d1 --region eu-west-1 
{
    "Images": []
}
```

Other AMIs from that section do work, e.g. this shows output: `aws ec2 describe-images --image-ids=ami-0d6ee9d5e1c985df6 --region eu-central-1`

https://github.com/NixOS/nixpkgs/blob/07971d69f7530bcb41644c965edd6193cf1ad850/nixos/modules/virtualisation/amazon-ec2-amis.nix#L555

**Comment by arianvp** [comment]
The website has been updated with new instructions.

AMIs are uploaded to a different account now and amazon-ec2-amis.nix is deprecated.

See the new instructions on the website: https://nixos.org/download/#nixos-amazon

This was also mentioned in the release notes on 24.05
https://nixos.org/manual/nixos/stable/release-notes#sec-release-24.05-highlights


I'll actually delete that file you're linking to stop confusion.

As what happened to `eu-west-1` 23.05 image  I'm pretty sure it accidentally got wiped when the infra team was cleaning up.
