### ISSUE TITLE
Update request: alacritty 0.12.3 → 0.13.2

### ISSUE THREAD

**Issue by sudoerp** [NixOS/nixpkgs#307551]

**Comment by sudoerp** [comment]
Can someone guide to update alacritty package?

**Comment by JohnRTitor** [comment]
I assume this is a backport to 23.11 request, since nixos-unstable already is on v0.13.2.

**Comment by sudoerp** [comment]
So should I go ahead and update the pkg?

**Comment by JohnRTitor** [comment]
Already created a backport.
