### ISSUE TITLE
haskell: nix-shell and nix-build yield different libraries using the same default.nix

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#30757]
## Issue description

I use this `default.nix` to build [snake](https://github.com/sam-barr/haskell-gui-snake) game (not mine):

    { pkgs ? import <nixpkgs> {} }:
    with pkgs.haskellPackages;

    let
      compiler = ghcWithHoogle (self: with self; [
          GLUT
          # concurrent-extra
        ]);
    in
    pkgs.stdenv.mkDerivation {
      name = "snake";
      buildInputs = [ compiler ];
      src = ./.;

      shellHook = ''
        eval "$(egrep ^export "$(type -p ghc)")"
        export PS1="\[\033[1;32m\][ns-hs:\w]\n$ \[\033[0m\]"
      '';
    }

using this (modified) `Makefile`

    all:
        ghc -o Snake --make main.hs

    clean:
        rm *.o *.hi *.exe

    install:
        mkdir ${out}/bin
        cp Snake ${out}/bin

### Steps to reproduce

Success commands:
  * `nix-shell --run make`
  * `nix-shell --pure --run make`
  * `nix-shell --command make`
  * `nix-shell --pure --command make`

Failed command:

    $ nix-build .
    these derivations will be built:
      /nix/store/vi789bvfmnjbcbndqrfm0fcr8i2lxjs2-snake.drv
    building path(s) ‘/nix/store/dy5ciyc2l78pq3r2na4d2z8y8hcy2h50-snake’
    unpacking sources
    unpacking source archive /nix/store/qyx4ld3izr5bxjsvnq8g070dbaydny4x-haskell-gui-snake
    source root is haskell-gui-snake
    patching sources
    configuring
    no configure script, doing nothing
    building
    build flags: SHELL=/nix/store/flb9ar1xdd13c606aa4my9miy3iv4vyk-bash-4.4-p12/bin/bash
    ghc -o Snake --make main.hs
    [3 of 5] Compiling Display          ( Display.hs, Display.o ) [Control.Concurrent.Thread.Delay changed]

    Display.hs:4:1: error:
        Failed to load interface for `Control.Concurrent.Thread.Delay'
        Use -v to see a list of the files searched for.
    make: *** [Makefile:2: all] Error 1
    builder for ‘/nix/store/vi789bvfmnjbcbndqrfm0fcr8i2lxjs2-snake.drv’ failed with exit code 2
    error: build of ‘/nix/store/vi789bvfmnjbcbndqrfm0fcr8i2lxjs2-snake.drv’ failed

Have to uncomment `concurrent-extra` to be able to `nix-build` successfully.

Is it because of sandboxing?

## Technical details

 * System: NixOS: 18.03.git.00e56fb (Impala)
 * Nix version: nix-env (Nix) 1.11.15
 * Nixpkgs version: "18.03pre117327.3fe7cddc30"
 * Sandboxing enabled: build-use-sandbox = true

**Comment by FRidh** [comment]
@wizzup turn of the sandbox and see what happens
```
nix-build -A pkg --option build-use-sandbox false
```

**Comment by wizzup** [comment]
@FRidh turning off sandbox using `--option` flag didn't help. Still the same error.

I do turn of sandbox in `configuration.nix` too but still the same error.

**Comment by cdepillabout** [comment]
There hasn't been any activity on here for a few years, so I'll go ahead and close.  Feel free to leave a comment if you're still stuck on this and we can re-open.
