### ISSUE TITLE
Package request: OpenDyslectic (font)

### ISSUE THREAD

**Issue by St-H123** [NixOS/nixpkgs#307555]
**OpenDyslectic font**
> OpenDyslexic is a new open sourced font created to increase readability for readers with dyslexia. The typeface includes regular, bold, italic, and bold-italic styles, and 2 typefaces: OpenDyslexic, and OpenDyslexic-Alta. It was created to help with my reading, and is being updated continually and improved based on input from other dyslexic users. There are no restrictions on using OpenDyslexic.
>
> OpenDyslexic is created to help with some of the symptoms of dyslexia. Letters have heavy weighted bottoms to indicate direction. You are able to quickly figure out which part of the letter is down which aids in recognizing the correct letter, and sometimes helps to keep your brain from rotating them around. Consistently weighted bottoms can also help reinforce the line of text. The unique shapes of each letter can help prevent confusion through flipping and swapping.
>
> ![OpenDyslexic's letter shapes are unique, to prevent confusion.](https://opendyslexic.org/assets/img/font-compare.png)

From: https://opendyslexic.org/about

**Metadata**

* homepage URL: https://opendyslexic.org/
* source URL: https://github.com/antijingoist/open-dyslexic
* license: SIL OPEN FONT LICENSE
* platforms: all

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alex-fu27** [comment]
Is already packaged as `open-dyslexic`, please re-open and correct me if I am wrong.
