### ISSUE TITLE
nixos: pptp in NetworkManager requires kernel module nf_conntrack_pptp, which is not present by default

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#30756]
## Issue description

When trying to use a pptp vpn connection with NetworkManager, establishing the connection fails. The logs in journalctl look like this:

```
oct. 22 10:49:04 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_rep:pptp_ctrl.c:259]: Sent control packet type is 1 'Start-Control-Connection-Request'
oct. 22 10:49:04 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_disp:pptp_ctrl.c:781]: Received Start Control Connection Reply
oct. 22 10:49:04 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_disp:pptp_ctrl.c:815]: Client connection established.
oct. 22 10:49:05 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_rep:pptp_ctrl.c:259]: Sent control packet type is 7 'Outgoing-Call-Request'
oct. 22 10:49:05 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_disp:pptp_ctrl.c:900]: Received Outgoing Call Reply.
oct. 22 10:49:05 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_disp:pptp_ctrl.c:939]: Outgoing call established (call ID 27289, peer's call ID 7505).
…
oct. 22 10:49:35 xango pppd[3025]: LCP: timeout sending Config-Requests
oct. 22 10:49:35 xango NetworkManager[1936]: LCP: timeout sending Config-Requests
oct. 22 10:49:35 xango NetworkManager[1936]: Connection terminated.
oct. 22 10:49:35 xango pppd[3025]: Connection terminated.
oct. 22 10:49:35 xango NetworkManager[1936]: <warn>  [1508662175.0851] vpn-connection[0x27c2540,b3fecaca-c140-48d0-bd50-525beb6ef564,"sharif-guest2",0]: VPN plugin: failed: connect-failed (1)
…
oct. 22 10:49:35 xango pptp[3038]: nm-pptp-service-3021 log[callmgr_main:pptp_callmgr.c:245]: Closing connection (unhandled)
oct. 22 10:49:35 xango NetworkManager[1936]: Terminating on signal 15
oct. 22 10:49:35 xango NetworkManager[1936]: Modem hangup
oct. 22 10:49:35 xango pppd[3025]: Terminating on signal 15
oct. 22 10:49:35 xango pppd[3025]: Modem hangup
oct. 22 10:49:35 xango pppd[3025]: Exit.
oct. 22 10:49:35 xango pptp[3038]: nm-pptp-service-3021 log[ctrlp_rep:pptp_ctrl.c:259]: Sent control packet type is 12 'Call-Clear-Request'
oct. 22 10:49:35 xango pptp[3038]: nm-pptp-service-3021 log[call_callback:pptp_callmgr.c:84]: Closing connection (call state)
```

This is solved by "sudo modprobe nf_conntrack_pptp". I'm not sure whether:

1. nf_conntrack_pptp should be enabled by default,
1. nf_conntrack_pptp can be automatically loaded somehow by NetworkManager, or
1. the need for this module when using pptp should simply be documented in the nixos manual.

### Steps to reproduce

Install nixos with NetworkManager enabled, try to connect to a pptp vpn using NetworkManager, then see above. I created the connection using the NetworkManager applet in plasma/kde.

## Technical details

* System:  18.03pre115166.1b1fc65505
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: 18.03pre118381.4068703502
* Sandboxing enabled: No

**Comment by flokli** [comment]
In theory, network-manager-pptp [should try to modprobe `nf_conntrack_pptp`](https://git.gnome.org/browse/network-manager-pptp/commit/?id=695d4f2f3d1003e18be6f97bbb103e44f75d3c2b).

However, as this is currently hardcoded to `/sbin/modprobe`, this doesn't work.

**Comment by flokli** [comment]
@FlorentBecker Can you check if applying [this patch](https://gist.github.com/flokli/62c05fbd8c8af130033e6e3e0329ab03) works for you?

**Comment by FlorentBecker** [comment]
Sorry, I can't test at the time, I don't have access to a pptp'ed network anymore.

**Comment by flokli** [comment]
Same here - Nobody should really use pptp anymore…

@dezgeg, as you :+1:'d, do you have a test setup ready?

**Comment by dezgeg** [comment]
No, I don't, it just sounded the correct solution.

**Comment by Mounium** [comment]
I just reverted #37714 and it builds and works without trouble. Note that you have to set networking.firewall.connectionTrackingModules to at least [ "pptp" ]. No idea why was it removed just so simply, could someone please check if it works that way too?

**Comment by flokli** [comment]
That's the problem - pptp is rarely used these days, really insecure and there was no feedback on a proposed patch fixing some reported issue. 

If this really should go back in, we would need a maintainer and a nixos test for it.

**Comment by Mounium** [comment]
@flokli  I'm not sure whether it was deleted based only on this issue, but this one seems to be the exact same as https://github.com/NixOS/nixpkgs/issues/22947 , without the proposed (and working) solution. 

As for security, I don't know nearly enough about VPNs to have an objective opinion on the topic, but as a layman I think it poses no security threat just by simply being in the repository, if it doesn't get used (and even usage of it is disabled without further tinkering as the networking.firewall.autoLoadConntrackHelpers setting defaults to false).

Unfortunately I can't help with the maintainer and nixos test part..

Obviously I am biased on the topic, as reverting your commit at each update works for me, but it doesn't seem to be the optimal solution :D And I need pptp as my university currently offers VPN only through this protocol..

**Comment by timon37** [comment]
ouch, I'm using pptp as well (I work as a contractor, not my decision what protocol the company uses)...

**Comment by Mounium** [comment]
@timon37 Until some decision is made you can do git revert 6ac74d6 , and set the networking.firewall.connectionTrackingModules to [ "pptp" ].

**Comment by flokli** [comment]
@timon37 as written above, having a nixos vm test with a a server/client setup, would help ensuring it works. You can peek into [`nixos/tests/`](https://github.com/NixOS/nixpkgs/tree/master/nixos/tests) for some inspiration, for example [`flannel.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/flannel.nix).
