### ISSUE TITLE
Names of Language Specific Packages (such as nodePackages)

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#30785]
I noticed that packages that are part of languages like nodePackages are not searchable/discoverable using the standard search.

Like there's no way to find `js-beautify` on https://nixos.org/nixos/packages.html

But it's not only a website problem.

These packages doesn't seem installable without a direct attribute path: `nix-env -iA 'pkgs.nodePackages.js-beautify'`.

The only way to find out about these packages is to search through the nixpkgs codebase. This is not very user friendly.

Another issue is that when you delete them, a name is actually assigned to them. In the case of `js-beautify` it is given a name of: `node-js-beautify`. You can find this out by doing `nix-env -q --installed`.

This allows the package to be uninstalled by name `nix-env -e node-js-beautify`. But if we can auto-assign names for uninstalling, couldn't we also auto-assign namespaced names for installation? Is the problem of name collision different when installing vs uninstalling?

**Comment by 7c6f434c** [comment]
>This allows the package to be uninstalled by name `nix-env -e node-js-beautify`. But if we can auto-assign names for uninstalling, couldn't we also auto-assign namespaced names for installation? Is the problem of name collision different when installing vs uninstalling?

It's not just a problem of namespace collision (although the problem 
_is_ different: name collisions between different package set versions
are much more likely across Nixpkgs as a whole, than across installed
packages for a single user).

It is a problem of search by name already being too slow (it require 
walking the entire package set, touching most of Nixpkgs source files),
number of variations of pythonPackages being enough to make the entire
thing completely unbearable, and lack of support for removing packages
from the environment by attribute path.

**Comment by CMCDragonkai** [comment]
So this a search problem then? Could it be possible to build a on-disk search index data structure into the nixpkgs repository (auto updated by the CI system) that can be loaded into memory at once and searched?

**Comment by FRidh** [comment]
> Like there's no way to find js-beautify on https://nixos.org/nixos/packages.html

We do not recurse into all package sets, i.e., we do not apply the following function to every package set:
```nix
  # Applying this to an attribute set will cause nix-env to look
  # inside the set for derivations.
  recurseIntoAttrs = attrs: attrs // { recurseForDerivations = true; };
```
> Another issue is that when you delete them, a name is actually assigned to them. In the case of js-beautify it is given a name of: node-js-beautify. You can find this out by doing nix-env -q --installed.

The name `node-js-beautify` is simply the name of the derivation. It does not magically appear, its just that there isn't a mapping from name to attribute for all derivations because we do not look for all (possible) derivations.

> Could it be possible to build a on-disk search index data structure into the nixpkgs repository (auto updated by the CI system) that can be loaded into memory at once and searched?

I'm pretty sure that's not going to be accepted.

If you want something like this, you could create a separate tool / database for it, just as was done with [`nix-index`](https://github.com/bennofs/nix-index). In this case, you could write a Nix expression that does recurse into every attribute set (i.e., map `recurseIntoAttrs` to each attribute set recursively), and then use `nix-env` to evaluate it to obtain the names and paths. You may want to cache that result then somewhere.

**Comment by CMCDragonkai** [comment]
I'm curious why you don't think it would accepted (not exactly in that implementation)? Do you expect all future users of nixpkgs to scan through the source or be expected to know about a third party nix indexing tool for searching the packages they can install?

That being said, nix-index looks pretty good. I would hope the new Nix UI has something similar.

**Comment by CMCDragonkai** [comment]
Just tested it, it produces a 19 MiB cache file in ~/.cache/nix-index/files.

However it actually doesn't find the nodePackages.js-beautify. It does find the python packaged version of js-beautify as it is installable from python packages and from node packages.

Due to how there's no standard in packaging up language libraries, I'm guessing the python ecosystem is more searchable than the node packages ecosystem.

**Comment by matthewbauer** [comment]
> However it actually doesn't find the nodePackages.js-beautify. It does find the python packaged version of js-beautify as it is installable from python packages and from node packages.

This is because those packages are not put into the binary cache. Nix-index has no way of finding what's in them until they are built.

See https://github.com/NixOS/nixpkgs/commit/d008513af25f264accdbd4f496bfe13803e28190

**Comment by CMCDragonkai** [comment]
@FRidh Why is python packages deemed important enough to have `recurseIntoAttrs` used but not nodePackages or other package sets?

**Comment by FRidh** [comment]
No idea. I don't bother with `nodePackages`.

Important to note is that there are two things:
1. what `nix-env` shows
2. what `hydra` builds

Having `recurseIntoAttrs` will right away make them available for `nix-env`. For Hydra, `recurseIntoAttrs` is needed, and the top-level attribute needs to be added to a job.

**Comment by abathur** [comment]
I assume this has been fixed in the intervening years since I know see the example case (nodePackages.js-beautify) in search results. Happy to reopen if I'm overreaching.
