### ISSUE TITLE
Update request: flowblade 2.14.0.1 → 2.14.0.2

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#307858]
- Package name: `flowblade`
- Latest released version: 2.14.0.2

- Current version on the unstable channel: 2.14.0.1
- Current version on the stable/release channel: 2.10.0.4

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@polygon 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
#306526 have already reached [nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=306526). Please run `nix flake update` to update, assuming you have a flake setup.
