### ISSUE TITLE
SDDM does not inherit XKB layout

### ISSUE THREAD

**Issue by iamcult** [NixOS/nixpkgs#307882]
### Describe the bug
When using SDDM and Plasma 6 in nixos-unstable, SDDM does not inherit the keyboard layout I have set with `services.xserver.xkb.layout`. It instead uses the default of en-us. I can confirm that the correct layout is set with `localectl status`.

### Steps To Reproduce
1. Enable SDDM with `services.displayManager.sddm.enable = true;`
2. Set a keyboard layout with `services.xserver.xkb.layout`
3. Rebuild and reboot into SDDM

### Expected behavior
SDDM inherits the keyboard layout from my system locale.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
You probably need to run the following to fix that:

```
sudo cp ~/.config/kwinoutputconfig.json /var/lib/sddm/.config/
sudo cp ~/.config/kcminputrc /var/lib/sddm/.config/
sudo chown sddm:sddm /var/lib/sddm/.config/kcminputrc
sudo chown sddm:sddm /var/lib/sddm/.config/kwinoutputconfig.json
```

**Comment by iamcult** [comment]
It would actually be `~/.config/kxkbrc`

**Comment by SuperSandro2000** [comment]
I am on SDDM with Wayland only and copying the two files fixes keyboard and display configuration for me.

**Comment by iamcult** [comment]
Neither of those 2 files store the KDE keyboard layout config, so I can't see why they'd work here. What I'm specifically looking for is for SDDM to inherit the keyboard layout (E.g. English (US)) that I set in my system locale OR some way to specifically declare keyboard layout in SDDM.

**Comment by SuperSandro2000** [comment]
🤔 I think I remember now. Those where for the display configuration and for the touchpad to work correctly.

The keyboard layout is done through xkb and we needed to move it here https://github.com/NixOS/nixpkgs/blob/2e9d7dca27336d8b75baa53c782e9ba94f8da2ab/nixos/modules/services/misc/graphical-desktop.nix#L23-L32 so using services.xserver.xkb options should fix that.

**Comment by iamcult** [comment]
> using services.xserver.xkb options should fix that.

But my initial report here is that SDDM isn't inheriting what I have set in the xserver.xkb options (neither is plasma 6, but that can be configured in settings).

**Comment by SuperSandro2000** [comment]
Is the layout in /etc/X11/xorg.conf.d/00-keyboard.conf correct?

**Comment by 30350n** [comment]
I'm also having this issue and for me atleast everything seems to be set correctly in `/etc/X11/xorg.conf.d/00-keyboard.conf`:

```
Section "InputClass" 
  Identifier "Keyboard catchall" 
  MatchIsKeyboard "on" 
  Option "XkbModel" "pc104" 
  Option "XkbLayout" "de" 
  Option "XkbOptions" "" 
  Option "XkbVariant" "" 
EndSection 
```

**Comment by iamcult** [comment]
It worked for me (I had confused layout with variant) to choose the variant, I don't see why the layout would act differently.
