### ISSUE TITLE
Screen flicker on boot with Nvidia proprietary graphics

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#30788]
## Issue description
When booting with `services.xserver.videoDrivers=['nvidia']` the screen does not progress beyond the textual login screen which will flicker and become unresponsice except for ctrl+alt+canc

UPDATE:With `services.xserver.videoDrivers=['nvidia' 'intel']` there is no flicker ,instead it shows only the pointer on a black screen

Those are my graphic cards
```
lspci -k | grep -A 2 -E "(VGA|3D)"
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
        Subsystem: Hewlett-Packard Company Device 2296
        Kernel driver in use: i915
--
0a:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 840M] (rev ff)
        Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
```

### Steps to reproduce

1. Add  `services.xserver.videoDrivers=['nvidia']` to `/etc/nixos/configuration.nix`
2. Run `sudo nixos-rebuilld switch`
3. Reboot

## Technical details

* System: 18.03pre118381.4068703502 (Impala)
* Nix version:nix-env (Nix) 1.12pre5663_c7af84ce
* Nixpkgs version: "18.03pre118381.4068703502"
* Sandboxing enabled: build-use-sandbox = true

**Comment by roberth** [comment]
Do you have a working version to roll back to? You may be able to git bisect the issue. Have you tried another kernel version?

**Comment by pasqui23** [comment]
No,but it worked when it was on Manjaro Linux a few weeks ago

**Comment by vcunat** [comment]
That's switchable GPU setup between the one built in CPU and a dedicated nvidia card, right?  I *think* that needs some extra settings, maybe `hardware.bumblebee.enable = true;` or something.

**Comment by pasqui23** [comment]
```
hardware.opengl.driSupport32Bit = true;
hardware.bumblebee.enable=true;
# services.xserver.videoDrivers=['nvidia']; # enabling it gives me problems
```

**Comment by vcunat** [comment]
IIRC running just on Intel (e.g. without `videoDrivers`) is easier with switchable GPUs.

**Comment by niobium0** [comment]
I have a workstation with Intel integrated graphics (Asus Z87 Sabertooth) and NVidia GPUs (so no bumblebee). I see the same flicker problem with NixOS 17.09. Everything works with Ubuntu 17.10:
=======
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
	Subsystem: ASUSTeK Computer Inc. Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
--
01:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 950] (rev a1)
	Subsystem: eVga.com. Corp. GM206 [GeForce GTX 950]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_384_drm, nvidia_384
01:00.1 Audio device: NVIDIA Corporation Device 0fba (rev a1)
--
02:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
	Subsystem: Device 196e:119e
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_384_drm, nvidia_384

**Comment by currymj** [comment]
For me, Bumblebee solved this problem but created issues when trying to use CUDA.

I was able to solve it another way, which might be useful for other people on desktops running into this issue who don't want to use Bumblebee:

In `configuration.nix`, I just have the standard

```
services.xserver.videoDrivers=['nvidia'];
```

And nothing else. The key is that I've made sure my monitor is plugged in to the GPU rather than the motherboard (on my machine, they are horizontal HDMI and DisplayPort rather than vertical, in a different location on the back of the case). I also went into the BIOS and switched the primary display to PCIE. This combination seems to allow me to sidestep the integrated graphics even though there's no explicit setting to turn them off.

**Comment by pasqui23** [comment]
@currymj I am using a laptop,no ports here
And that configuration is exactly the one which gives me problems,independently of my bumblebee configuration

**Comment by pasqui23** [comment]
Acording to the nvidia site I need the 384.111 version of the driver.
There is no such version,at most the 381.22 (nvidia-beta) or the 387.34 (the stable version)

**Comment by pasqui23** [comment]
Apparently the problem was not the version but that I should have put  `services.xserver.videoDrivers=['nvidia' 'intel']`.
Still having problems like only showing the pointer on a black screen on after startup.
