### ISSUE TITLE
Setting dconf num-workspaces does nothing

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#307965]
### Describe the bug

Despite setting num-workspaces to 1, the settings and the UI show four workspaces. Has this setting been renamed?

### Steps To Reproduce
1. [Set `(builtins.elemAt config.programs.dconf.profiles.user.databases 0).settings."org/gnome/desktop/wm/preferences".num-workspaces` (or some other database index) to `"1"`](https://gitlab.com/engmark/root/-/blob/e2349c640aa828e41b3d7c8a39d3054925b3fb6a/modules/gui.nix#L270-270).
2. `nixos-rebuild boot`
3. Reboot

### Expected behavior

There should be only one workspace.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/168301/61bdbe89-52ef-4b00-b5b7-01425a582c1e)

### Additional context

As you can see above, I also can't change the number of workspaces manually - the control is disabled.

Looking through `dconf dump /` doesn't reveal any other relevant workspace settings.

`dbus-launch gsettings get org.gnome.desktop.wm.preferences num-workspaces` reports `4`, while `dconf read /org/gnome/desktop/wm/preferences/num-workspaces` reports `'1'`.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05pre617818.58a1abdbae32`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
GSettings and dconf are strongly typed. The GSettings schema expects some kind of integer but the dconf database contains a string so GSettings will consider the value a junk and fall back to the default.

**Comment by l0b0** [comment]
But if I try to change to `num-workspaces = 1;` then `nixos-rebuild` fails with "error: cannot coerce an integer to a string". So how do I fix it?

**Comment by jtojnar** [comment]
That is because you need to use specific numeric constructor. In this case probably either `lib.gvariant.mkInt32` or  `lib.gvariant.mkUint32`.

There is a bug that made the error unnecessarily confusing. I opened a https://github.com/NixOS/nixpkgs/pull/308111 to clarify it.

**Comment by l0b0** [comment]
Finally found the right documentation:

1. [The schema](https://github.com/GNOME/gsettings-desktop-schemas/blob/5472213634a26c2f1cc79c34904606b6d1afb083/schemas/org.gnome.desktop.wm.preferences.gschema.xml.in#L197-L206) says the type is "i".
2. [The mapping from the type string, "i", to the actual type](https://docs.gtk.org/glib/struct.VariantType.html#gvariant-type-strings) (my emphasis) says "i" is a "signed 32 bit integer".
3. [nixpkgs](https://github.com/NixOS/nixpkgs/blob/d8b6ceb812e352370e0d069eb50e4379f0667a89/lib/gvariant.nix#L36) shows that `pkgs.lib.gvariant.type.int32 = "i"`, so that's the right connection.
4. Finally, [`mkInt32`](https://github.com/NixOS/nixpkgs/blob/d8b6ceb812e352370e0d069eb50e4379f0667a89/lib/gvariant.nix#L256-L259) is the right type converter.
