### ISSUE TITLE
Package qdigidoc: cannot sign with SmartID

### ISSUE THREAD

**Issue by mikidep** [NixOS/nixpkgs#307927]
### Describe the bug
When using package qdigidoc, signing with SmartID fails with an SSL certificate error. I suspect that this requires a package update.

### Steps To Reproduce
1. `nix run nixpkgs#qdigidoc`
2. In the signature page, load a file for signing.
3. From the bottom right dropdown, select "SIGN WITH SMART-ID".
4. Click on the button and insert correct personal code. 

### Expected behavior
The signing procedure should progress.

### Actual behavior

A dialog pops up with the message:
> SSL handshake failed. Check the proxy settings of your computer or software upgrades

In the command line logs, the following log appears:
```console
SSL Error: "The issuer certificate of a locally looked up certificate could not be found" ("DigiCert Global G2 TLS RSA SHA256 2020 CA1")
```

### Full log
```console
Failed to parse public key
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSigner(0x264da30), parent's thread is QThread(0x22d3ee0), current thread is QSigner(0x264da30)
Loading: "opensc-pkcs11.so"
"OpenSC Project                   (2.20)" 
 "OpenSC smartcard framework       (0.25)" 
 Flags: 0
2024-04-30T07:12:03Z I [X509CertStore.cpp:63] - Loaded 58 certificates into TSL certificate store.
TSL loading finished
SSL Error: "The issuer certificate of a locally looked up certificate could not be found" ("DigiCert Global G2 TLS RSA SHA256 2020 CA1")
RIA.SmartID: "SSL handshake failed. Check the proxy settings of your computer or software upgrades."
```

### Additional context

This happens regardless of using `nix shell`, `nix run`, or installing via Home Manager.

### Notify maintainers

@mmahut 
@yana

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6, NixOS, 24.05 (Uakari), 24.05.20240416.66adc1e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/6bf943g0mlhymyffs9dflzgc78r93s60-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by flokli** [comment]
I can reproduce. The "Signing" animation is shown for a while, and then an error too:

The error message mentions `dd-at-ria.ee` not being reachable:
 
![Screenshot from 2024-08-14 01-35-52](https://github.com/user-attachments/assets/770f1aec-bd30-4353-8200-8da36f724b8c)

This hostname does not even have a DNS record.

I spotted https://github.com/open-eid/libdigidocpp/commit/2b5db855ba3ceb9bae1f11589ea1aea22bb7595a#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR25 changing the "Default TSA URL".
Maybe they updated the URL in some places, but forgot updating elsewhere?

I found this URL in my qdigidoc settings too:

![image](https://github.com/user-attachments/assets/53d1862f-e093-449e-8ca1-ef1556ad3684)

Changing it to the new URL unfortunately also didn't help, as it doesn't like the Digicert certificate.

Maybe unrelated, maybe not - I also see a `2024-08-13T23:10:20Z E [TSL.cpp:302] - TSL eu-lotl.xml signature is invalid` in my logs.

This looks like an issue in the application itself / some config shipped somewhere, but nothing NixOS-specific. I propose opening an issue upstream in qdigidoc, maybe linking to here for context.

**Comment by flokli** [comment]
I tried manually bumping `libdigidocpp`, and I tried using `digidoc-tool` from `libdigidocpp`. It mentions a signature to be invalid:

```
❯ /nix/store/802v0dcr9b7vsb1l1vi18fc98l2b7bqj-libdigidocpp-unstable-2024-07-17-bin/bin/digidoc-tool create --file=CONTRIBUTING.md contributing.asice
Version
  digidoc-tool version: 3.18.0.0
  libdigidocpp version: 3.18.0.0
2024-08-14T07:39:11Z E [TSL.cpp:311] - TSL eu-lotl.xml signature is invalid
2024-08-14T07:39:12Z I [X509CertStore.cpp:63] - Loaded 0 certificates into TSL certificate store.
Available certificates:
  label: XXXX
Selected:
  label: XXXX
Please enter PIN for token 'XXXX' or <enter> to cancel: 
2024-08-14T07:39:16Z W [TSL.cpp:126] - Failed to parse TSL  /home/flokli/.digidocpp/tsl/EE.xml: /home/flokli/.digidocpp/tsl/EE.xml:1:2 error: invalid document structure
2024-08-14T07:39:16Z E [TSL.cpp:311] - TSL EE.xml signature is invalid
2024-08-14T07:39:16Z I [X509CertStore.cpp:63] - Loaded 58 certificates into TSL certificate store.
    Validation: OK
```

I'll open an issue upstream.

**Comment by flokli** [comment]
This issue is about issues signing with SmartID (the mobile push thingie).

I tried to reproduce, and with a wiped `.digidocpp/` I got the following logs (and no push).

```
2024-08-14T07:58:52Z E [TSL.cpp:302] - TSL eu-lotl.xml signature is invalid
"OpenSC Project                   (2.20)" 
 "OpenSC smartcard framework       (0.25)" 
 Flags: 0
2024-08-14T07:58:54Z I [X509CertStore.cpp:63] - Loaded 0 certificates into TSL certificate store.
TSL loading finished
RIA.SmartID: "Failed to send request. Check your Smart-ID service access settings."
```

I think there's something wrong with the TSL and TSA setup, which is also impacting signing with ID Cards. See https://github.com/NixOS/nixpkgs/issues/334397, (which I initially confused with this one).
