### ISSUE TITLE
gdm: nixos /var/lib/AccountsService/users/$username file is patched by services.displayManager.preStart

### ISSUE THREAD

**Issue by gotjoshua** [NixOS/nixpkgs#307993]
### Describe the bug
User specific override of Xsession is not easy as the /var/lib/AccountsService/users/$username file is patched by services.displayManager.preStart to  the value of services.displayManager.defaultSession

### Steps To Reproduce
1. try to add a declarative file to /var/lib/AccountsService/users/$username
2. notice that after rebuild switch and restarting displayManager, it will be patched 

### Expected behavior
a way to override the default selection in the selection menu declaratively for a specific user

### Screenshots
![loginMenu](https://github.com/NixOS/nixpkgs/assets/8686454/0baac805-01c5-4ae9-8ffb-1d974586b6f0)

### Additional context
I added some attempts and a working solution here:
https://discourse.nixos.org/t/how-to-set-up-desktop-environment-per-user/6351/6?u=gotjoshua

### Notify maintainers

@jtojnar via https://github.com/NixOS/nixpkgs/commit/8dc5ff7dcfd1c58c32004ffae25e6d31ed83d86c#diff-f5360a6ed414ff1e292e501143681f1cddea53d4e9ea7ce31ef310e4dc4b378dR172-R175
otherwise [teams.gnome.members](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/gnome.nix#L70)

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240423.572af61`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(gotjosh): `""`
 - nixpkgs: `/nix/store/m5i890m2g4pnyflpn48d1dpzzmwp5q4p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
That is working as expected. The purpose of `services.displayManager.defaultSession` is to set all users’ default session to the one specified. (And there is really no other way to do that.)

To allow setting different sessions for each user, the following options exist:

- Add support for declarative and immutable AccountsService per-user configs. But since AccountsService is designed with being able to edit those files in mind and the API [discards errors](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/issues/7), it is probably not a good idea to promote that.

- Change `set-session.py` to support different sessions for different users.

**Comment by gotjoshua** [comment]
Thanks...

So perhaps my hack to avoid the call to set-session.py is not that terribly ugly after all?

**Comment by gotjoshua** [comment]
> just stop setting `defaultSession`

ah. but i did stop setting that, it seems that plasma sets it, but i didn't check when where how yet.

**Comment by jtojnar** [comment]
Oh, you are right. Looks like it has been that way for [over three years](https://github.com/NixOS/nixpkgs/commit/ad20e87e39749f1b6176f06e8d9bbb653738f020). And other DEs do that too. That is definitely not how the option is intended to be used.

You can neutralize this misuse with `defaultSession = null`, then.
