### ISSUE TITLE
Clockify Electron issue

### ISSUE THREAD

**Issue by JalilArfaoui** [NixOS/nixpkgs#307953]
### Describe the bug
I get the following error each time Clockify tries to set a tray icon : 

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Failed to load image from path '/nix/store/lrq18ij2isli6y044x5s4rklr2p964hq-electron-24.8.6/libexec/electron/resources/assets/icons/white.png'
at changeIcon (/nix/store/9ljfj6m8dz1gw093j9x53fd8scakincz-clockify-2.1.6/opt/Clockify/resources/app.asar/dist/main/webpack:/Clockify/src/main/main.ts:447:11)

### Steps To Reproduce
```nix
  environment.systemPackages = let
    unstable = import <nixos-unstable> { config = {
      allowUnfreePredicate = allowUnfreePredicate;
      permittedInsecurePackages = [
        "electron-24.8.6"
      ];
  }; };
  in with pkgs; [
    unstable.clockify
```

[WolfangAukang](https://github.com/NixOS/nixpkgs/commits?author=WolfangAukang)

### Expected behavior
In should have no error message and the tray icon should reflect the application status.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/3037833/2c695128-64a5-4ae6-8749-ee68f90a9c1e)

![image](https://github.com/NixOS/nixpkgs/assets/3037833/a4359aa3-83e9-4626-8e5a-f48a9c0b574c)

### Notify maintainers

@WolfangAukang 

### Metadata
```console
 ~ nix-shell -p nix-info --run "nix-info -m"                                                                                                      
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.87, NixOS, 23.11 (Tapir), 23.11.6708.12430e43bd9b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JalilArfaoui** [comment]
Do you know who can be mention to merge it ?

**Comment by WolfangAukang** [comment]
There is no direct way in GitHub to mention a committer. You can try the PR and see if it works for you, and if so, approve it. If you want to go the extra mile, you can post the PR link on this [Discourse post](https://discourse.nixos.org/t/prs-already-reviewed/2617/1613). But those methods won't ensure a fast merge.

**Comment by WolfangAukang** [comment]
Merged
