### ISSUE TITLE
ITD (InfiniTime Daemon) tries reading config from `/etc` rather than nix store

### ISSUE THREAD

**Issue by CoderThomasB** [NixOS/nixpkgs#307920]
### Describe the bug
When running ITD via `nix-shell`, it produces an error about not being able to read from its config file. It also doesn't open a socket at `/tmp/itd/socket` but it is unclear to me whether this is a result of the missing config files or a separate issue.

### Steps To Reproduce
1. `$ nix-shell -p itd`
2. `$ itd &` Start in background
3. `$ itctl get`

### Expected behavior
ITD starts up fine with no errors.

### Screenshots
```console
[nix-shell:~]$ itd &
6:39PM WRN Error while trying to read config file filename="/etc/itd.toml" error="open /etc/itd.toml: no such file or directory"
6:39PM WRN Error while trying to read config file filename="/home/thomas/.config/itd/itd.toml" error="open /home/thomas/.config/itd/itd.toml: no such file or directory"
```
```console
[nix-shell:~]$ itctl get
6:39PM FTL Error while running app error="dial unix /tmp/itd/socket: connect: no such file or directory"
```

### Notify maintainers

@mindavi @raphaelr

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.86, NixOS, 23.11 (Tapir), 23.11.6331.90055d5e616b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by raphaelr** [comment]
Currently you have to create the configuration file manually:

```sh
$ mkdir -p ~/.config/itd
$ cp $(nix-build '<nixpkgs>' -A itd)/etc/itd.toml ~/.config/itd/
```

And then `itd` should start properly.

**Comment by StatelessCat** [comment]
> Currently you have to create the configuration file manually:
> 
> ```shell
> $ mkdir -p ~/.config/itd
> $ cp $(nix-build '<nixpkgs>' -A itd)/etc/itd.toml ~/.config/itd/
> ```
> 
> And then `itd` should start properly.

Thanks, but it's not working here (Ubuntu 24.04)

```
$ sudo cp $(nix-build '<nixpkgs>' -A itd)/etc/itd.toml ~/.config/itd/
error: getting status of /nix/var/nix/daemon-socket/socket: Permission denied

```
