### ISSUE TITLE
Update request: surrealdb 1.3.1 → 1.4.2

### ISSUE THREAD

**Issue by stromseng** [NixOS/nixpkgs#308080]
- Package name: surrealdb
- Latest released version: 1.4.2

- Current version on the unstable channel: 1.3.1
- Current version on the stable/release channel: 1.0.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@sikmir 
@happysalada 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
Where have you seen that the latest surrealdb release is 2.0.4 ?
Latest on github is 1.4.2

**Comment by stromseng** [comment]
Wow, I'm sorry, mixed up surrealist and surrealdb. Will update my request accordingly.

**Comment by happysalada** [comment]
If you know how to make the update PR, im happy to help you get it merged.
Unfortunately i dont have a place to work with a laptop at the moment so it will be hard to make the PR myself.

**Comment by stromseng** [comment]
I wasn't really sure how to make the update PR. Is there a guide for it anywhere, as i could not find one. I would be happy to make them in the future.

**Comment by sikmir** [comment]
[Contributing to Nixpkgs packages](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md)
