### ISSUE TITLE
Krita segfaults during save when using xmonad (using plasma5 is fine) (17.09 regression)

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#30807]
## Issue description

When I use xmonad as window manager Krita segfaults when I try to save a document (gdb output):

```
Thread 1 "krita" received signal SIGSEGV, Segmentation fault.
0x00007fffef510c49 in QString::indexOf(QString const&, int, Qt::CaseSensitivity) const () from /nix/store/nwvydrhhmfvf5g8ybh135rgpl9xyzvvb-qtbase-5.9.1/lib/libQt5Core.so.5
``` 

I suspected that it had something to do with KDE/Qt stuff missing, so I tried using plasma5 as desktop environment and then the problem was not encountered. 

Something else worth noting, I can't load autosaves, I get the error message "Unknown file type" and the terminal is filled with this error message:

```
No file found for ".xml" , even though update-mime-info said it would exist.
Either it was just removed, or the directory doesn't have executable permission... ("/home/me/.local/share/mime", "/home/me/.nix-profile/share/mime", "/run/current-system/sw/share/mime")
No file found for ".xml" , even though update-mime-info said it would exist.
Either it was just removed, or the directory doesn't have executable permission... ("/home/me/.local/share/mime", "/home/me/.nix-profile/share/mime", "/run/current-system/sw/share/mime")
No file found for ".xml" , even though update-mime-info said it would exist.
Either it was just removed, or the directory doesn't have executable permission... ("/home/me/.local/share/mime", "/home/me/.nix-profile/share/mime", "/run/current-system/sw/share/mime")
```

### Steps to reproduce

1. `nix-env -i krita`
2. Start krita
3. Create new document
4. Press "Save" or "Save as" in File menu
5. Segfault

## Technical details

* System: NixOS 17.09
* Nix version: 1.11.15

Edit: I just tried this with the exact same config, but on my laptop that I haven't yet updated from 17.03 to 17.09, and I don't encounter the problem there. I'll get with the exact commit.

**Comment by jfrankenau** [comment]
I'm getting the same error messages with another Qt application I'm trying to package. For me putting `kxmlgui` in `environment.systemPackages` solved the problem while adding it to the package's dependencies didn't help.

**Comment by rzetterberg** [comment]
I'm closing this since it's stale and I haven't used 17.09 in a long while.
