### ISSUE TITLE
Update request: blanket 0.6.0 → 0.7.0

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#308146]
- Package name: blanket
- Latest released version: 0.7.0

- Current version on the unstable channel: 0.6.0
- Current version on the stable/release channel: 0.6.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jsierles onny

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Closing per #308444
