### ISSUE TITLE
Obsidian fails to start with `The SUID sandbox helper binary was found, but is not configured correctly`

### ISSUE THREAD

**Issue by giggio** [NixOS/nixpkgs#308128]
### Describe the bug
When starting obsidian I got this error:

```
[73448:0430/205321.652818:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/gghjll0dfdrg1nahq9fvm6ii7qrdmld3-electron-28.3.1/libexec/electron/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

### Steps To Reproduce
1. Install Obsidian with home-manager
2. Run `obsidian`

### Expected behavior
Obsidian starts.

### Screenshots
Not necessary.

### Additional context
I'm using home-manager. My config is here:
https://github.com/giggio/dotfiles/blob/main/config/home-manager/home.nix

### Workaround

If you run the following command Obsidian is able to start:

```bash
sudo chmod 4755 /nix/store/gghjll0dfdrg1nahq9fvm6ii7qrdmld3-electron-28.3.1/libexec/electron/chrome-sandbox
```

### Notify maintainers

@atila @conradmearns @zaninime @qbit @kashw2 @w-lfchen

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/mh3dkpww5py0fnrihk45pw7hvkj5fxxc-nix-info
copying path '/nix/store/mh3dkpww5py0fnrihk45pw7hvkj5fxxc-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-31-generic, Ubuntu, 24.04 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/giggio/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
same as #121694?

**Comment by giggio** [comment]
> same as #121694?

@eclairevoyant It could be. I just got an error related to the same problem, when using `ping`: `Lacking privilege for icmp socket`, which was fixed by setting the same bit on the binary. It seems like the same root, but I can't say for sure.

**Comment by giggio** [comment]
I'm closing this, it really is related to the other issue. It is an apparmor issue on Ubuntu. See my comment: https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924
