### ISSUE TITLE
`programs.hyprland.envVars.enable` breaks SDDM and X11 sessions

### ISSUE THREAD

**Issue by heyzec** [NixOS/nixpkgs#308287]
### Describe the bug

In https://github.com/NixOS/nixpkgs/pull/307155, XDG_SESSION_TYPE is now set to wayland by default for Hyprland users. However, SDDM will crash when this env var is set.

### Steps To Reproduce
1. Enable SDDM with `displayManager.sddm.enable`
2.  Set `XDG_SESSION_TYPE = "wayland"` under `environment.sessionVariables`
3. Reboot. SDDM greet will never show, and the screen will be black.

These two lines can be seen in journalctl, and they are not present for boots from older generations.

```
May 01 19:21:41 nixie sddm[1307]: Auth: sddm-helper exited with 11
May 01 19:21:41 nixie sddm[1307]: Greeter stopped. SDDM::Auth::HelperExitStatus(11)
```

### Expected behavior
SDDM does not crash.

### Notify maintainers

@Mic92

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by heyzec** [comment]
Thanks, enabling that option fixed the issue! Would be nice if there is an config assertion for this.

**Comment by pixL404** [comment]
enabling wayland for SDDM, makes it impossible for me to start X11 only sessions (eg Pantheon)

Is this expected, or is there a way to use SDDM with wayland and X11 sessions?

**Comment by dantefromhell** [comment]
Same issue here, workaround mentioned in https://github.com/NixOS/nixpkgs/issues/308287#issuecomment-2089124795 worked for me.

I found the following stacktrace in the logs, not sure if/ how this might be helpful.

```
systemd-coredump[2184]: [🡕] Process 2180 (sddm-helper-sta) of user 175 dumped core.

                                                 Module libpcre2-8.so.0 without build-id.
                                                 Module libcap.so.2 without build-id.
                                                 Module libzstd.so.1 without build-id.
                                                 Module libpcre2-16.so.0 without build-id.
                                                 Module libicudata.so.73 without build-id.
                                                 Module libicuuc.so.73 without build-id.
                                                 Module libicui18n.so.73 without build-id.
                                                 Module libz.so.1 without build-id.
                                                 Module libgcc_s.so.1 without build-id.
                                                 Module libstdc++.so.6 without build-id.
                                                 Module libsystemd.so.0 without build-id.
                                                 Module libQt5Core.so.5 without build-id.
                                                 Module sddm-helper-start-wayland without build-id.
                                                 Stack trace of thread 2180:
                                                 #0  0x00007ff997f75331 _ZN8QProcess5startERK7QStringRK11QS>
                                                 #1  0x000000000040a2d8 _ZN4SDDM13WaylandHelper12startProce>
                                                 #2  0x0000000000406561 main (sddm-helper-start-wayland + 0>
                                                 #3  0x00007ff9976eb10e __libc_start_call_main (libc.so.6 +>
                                                 #4  0x00007ff9976eb1c9 __libc_start_main@@GLIBC_2.34 (libc>
                                                 #5  0x00000000004067f5 _start (sddm-helper-start-wayland +>
                                                 ELF object binary architecture: AMD x86-64
```

**Comment by eclairevoyant** [comment]
The proper workaround for now would be to set `programs.hyprland.envVars.enable = false;`. Those are envvars that should be set only when the _hyprland_ session starts, _not_ categorically set.

**Comment by pixL404** [comment]
> The proper workaround for now would be to set `programs.hyprland.envVars.enable = false;`. Those are envvars that should be set only when the _hyprland_ session starts, _not_ categorically set.

Thanks, this worked for me. I can now start X11 sessions again :)

**Comment by PerfMonk** [comment]
Same problem here using Hyprland with Budgie as a second desktop.  
Thanks for solution :+1:  `programs.hyprland.envVars.enable = false;` works!
