### ISSUE TITLE
k3s: token can't be changed after cluster init

### ISSUE THREAD

**Issue by thomasjm** [NixOS/nixpkgs#308201]
### Describe the bug

If I start a fresh NixOS VM and add the following config, a k3s cluster is set up successfully:

```nix
  services.k3s = {
    enable = true;
    role = "server";

    token = "todo-replace-with-token-file";
    # token = "todo-replace-with-token-file-modified";

    extraFlags = "--write-kubeconfig-mode=644";
    clusterInit = true;
  };
```

However, if I comment out the token line and uncomment the other one, and do `nixos-rebuild switch`, then the k3s service fails to start. I can't see any relevant logs in `journalctl -xeu k3s`. But if you put the token back to the original one and rebuild again, it works. Thus it seems that you can never change the token away from the one you first started the cluster with.

### Steps To Reproduce
1. Use the config provided above on a NixOS VM or real machine/cluster

### Expected behavior
The k3s service should be managed declaratively. A change of `token` should succeed, and a change of `enabled = false` should remove the service and its state.

### Additional context
Furthermore, it seems to be difficult to *remove* a k3s installation. If I set `enable = false` and rebuild, the systemd service for k3s goes away. But I still see `containerd` processes running. I still see state in `/var/lib/kubelet` and other places. I was hoping I could just remove k3s and start from scratch. Maybe this situation would be better if https://github.com/NixOS/nixpkgs/issues/98090 were solved? Also potentially related: https://github.com/NixOS/nixpkgs/issues/255768

I've actually tried pretty hard to remove the k3s state from my machines, scrounging scripts from the internet like `k3s-uninstall.sh` and `k3s-killall.sh`. But things like containerd processes seem to persist even after doing all of this and rebooting.

I initially found this out when I decided to try the k3s module on my home NixOS cluster. I set it up with a hardcoded `token` value, which worked great. Then I decided to improve security by switching to a `tokenFile` with a proper secret. But the update proved impossible due to this issue.

### Notify maintainers

cc @euank @mic92 @superherointj @yajo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[vagrant@nixbox:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 23.11 (Tapir), 23.11.2936.428544ae95ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by superherointj** [comment]
The documentation needs to improve, the method I've been using to reset cluster is:
https://nixos.wiki/wiki/K3s#Upkeep

**Comment by thomasjm** [comment]
Thanks! Not sure how I missed those instructions.

However, I think code changes are still needed. I've been trying to follow the instructions, but I'm finding quite a few things still get left behind on the system. In particular, processes and systemd units. I've been trying to adapt parts of this script to get rid of these: https://github.com/dbruno74/k3s-dbruno/blob/main/k3s-killall.sh

I notice the Ansible instructions linked from the wiki contain some extra steps, such as clearing journalctl logs and rebooting. Maybe the rebooting will help get rid of old systemd units, but I'd rather not reboot as it's not very Nix-y.

I think you're right that data files of persistent services should stay. However, I think that setting `k3s.enable = false` should ensure that all *processes* are killed.

Less urgent, but it would also be nice to minimize the amount of data files scattered all over the system, as there are currently an alarming number of stateful paths (`/var/lib/rancher`, `/etc/rancher`, `/var/lib/kubelet`, `/run/k3s`, `/run/netns`, etc.).

In an ideal world, I think you would destroy a cluster like this: 1) set `k3s.enable = false` and rebuild, 2) delete a single data directory.

**Comment by superherointj** [comment]
> Thanks! Not sure how I missed those instructions.

It wasn't there when you first looked. Added it for you.

I agree with your points.

Contributions are welcomed.

Best regards.

**Comment by yajo** [comment]
Thanks everyone! Closing then.

**Comment by thomasjm** [comment]
Maybe we keep open until the follow-up issues are filed? In particular,

* Changing directory structure for state/data or adding new parameters to K3s NixOS module.
