### ISSUE TITLE
Ollama fails to detect amd gpu

### ISSUE THREAD

**Issue by ilovethensa** [NixOS/nixpkgs#308206]
### Steps To Reproduce
1. use this config
```
  services.ollama = {
    enable = true;
    acceleration = "rocm";
  };
```
2. run it
3. `May 01 11:05:13 viper ollama[283307]: time=2024-05-01T11:05:13.123+03:00 level=WARN source=amd_linux.go:53 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"`
4. It uses the CPU
### Expected behavior
Ollama detects the GPU and runs

### Additional context
I have an RX 580 if that helps
I can confirm that Rocm and openCL works on my system
### Notify maintainers

@abysssol @dit7ya @elohmeier

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
Maybe it's worth trying to set `ROC_ENABLE_PRE_VEGA` in the ollama config, since the service has some sandboxing features enabled by default that could prevent `environment.variables` from having any effect. If that doesn't work, it may be necessary to modify the package derivation.

``` diff
   services.ollama = {
     enable = true;
     acceleration = "rocm";
+    environmentVariables = {
+      ROC_ENABLE_PRE_VEGA = "1";
+    };
   };
```

**Comment by surfaceflinger** [comment]
detects my rx7800xt but says that it's not supported, it legit worked like a week ago
```
May 01 15:59:16 blahaj ollama[113235]: time=2024-05-01T15:59:16.107+02:00 level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx1101]"
May 01 15:59:16 blahaj ollama[113235]: time=2024-05-01T15:59:16.111+02:00 level=WARN source=amd_linux.go:114 msg="amdgpu [0] gfx1101 is not supported by /tmp/ollama195296697/rocm []"
May 01 15:59:16 blahaj ollama[113235]: time=2024-05-01T15:59:16.111+02:00 level=WARN source=amd_linux.go:116 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
May 01 15:59:16 blahaj ollama[113235]: time=2024-05-01T15:59:16.111+02:00 level=INFO source=amd_linux.go:127 msg="all detected amdgpus are skipped, falling back to CPU"
May 01 15:59:16 blahaj ollama[113235]: time=2024-05-01T15:59:16.111+02:00 level=INFO source=routes.go:1141 msg="no GPU detected"
```

**Comment by abysssol** [comment]
@surfaceflinger It appears that the 7800xt isn't yet officially supported by rocm, so support may be inconsistent between rocm versions. According to [this comment](https://github.com/ROCm/ROCm/discussions/2599#discussioncomment-8005159), setting `HSA_OVERRIDE_GFX_VERSION=11.0.0` worked, so it might be worth trying.

``` diff
   services.ollama = {
     enable = true;
     acceleration = "rocm";
+    environmentVariables = {
+      HSA_OVERRIDE_GFX_VERSION = "11.0.0";
+    };
   };
```

**Comment by surfaceflinger** [comment]
incredible, worked, thanks. the weirdest thing is that i actually already used rocm 6.0.2 with ollama and didn't have to use that env. this thing for me literally works once a week and then breaks for another week 🙂

**Comment by descention** [comment]
The rx580 has a computer version of 8.0 and ollama has a min version of 9.0 [in the code](https://github.com/search?q=repo%3Aollama%2Follama%20RocmComputeMin&type=code). I tried modifying this once before and it crashed ollama. I didn't keep record of the crash.

**Comment by abysssol** [comment]
Just found [this relevant issue](https://github.com/ollama/ollama/issues/2453) on ollama's repo. Since this is a problem with upstream ollama, not the nix package, I'm closing this issue.

**Comment by codebam** [comment]
This works for 7900XTX as well. Thank you for the quick reply and fix @abysssol

**Comment by abysssol** [comment]
Anyone trying to use `HSA_OVERRIDE_GFX_VERSION` may find [this ollama documentation](https://github.com/ollama/ollama/blob/main/docs/gpu.md#amd-radeon) useful as well.

**Comment by rjpcasalino** [comment]
@abysssol HSA override worked but for some reason the `environmentVariables` isn't picked up by the service. Anyway, cheers for the tip and further links

**Comment by surfaceflinger** [comment]
@rjpcasalino you can now use `services.ollama.rocmOverrideGfx`

**Comment by rjpcasalino** [comment]
strange one day it works and the next I update and `amdgpu detected, but no compatible rocm library found.` - 🤷‍♂️
