### ISSUE TITLE
Runtime failure: tracy

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#308220]
### Describe the bug

```
Error 65544: Wayland: Failed to load libwayland-client
terminate called without an active exception
zsh: abort (core dumped)  result/bin/tracy
```

### Steps To Reproduce
1. Run `tracy`

### Expected behavior
No crash

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers
@mpickering @nagisa @paveloom

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by widlarizer** [comment]
Same problem, same message, with the following system. WM: sway
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.05 (Uakari), 24.05pre629726.5710852ba686`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-23.05-23.05"`
 - channels(emil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by widlarizer** [comment]
Attempted workaround from
```
```
