### ISSUE TITLE
all-cabal-hashes on release-17.09 is four months out of date

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#30832]
## Issue description

The [`all-cabal-hashes`](https://github.com/NixOS/nixpkgs-channels/blob/91375ce951db616711a7f23e9d1724dedf793cda/pkgs/data/misc/hackage/default.nix) package on 17.09 is four months out of date. The [corresponding package on `master`](https://github.com/NixOS/nixpkgs/blob/e6a3089ec4c7599a8fddd235d550bb30ef9ad261/pkgs/data/misc/hackage/default.nix) is only 12 days old. Can it be cherry-picked to `release-17.09` please :smiley:?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by copumpkin** [comment]
I thought the general policy of release branches was to only get critical updates

**Comment by peti** [comment]
Updating all-cabal-hashes in the release branch is fine; I very much doubt that an updated Hackage database could cause trouble to anyone (although it *theoretically* could thanks to the wonders of Hackage's destructive Cabal file editing feature, but that's just theory, really.).

**Comment by copumpkin** [comment]
Cool, sorry for the confusion then!

**Comment by vaibhavsagar** [comment]
Can this be updated please? I would like this so that I don't have to manually override `all-cabal-hashes` e.g. [here](https://github.com/gibiansky/IHaskell/blob/3d4a3dca51a7b052f5c8744a70f357ec41dc3c74/release-8.2.nix#L2-L9).

**Comment by peti** [comment]
@vaibhavsagar, is there anything in particular preventing your from opening a pull request?

**Comment by vaibhavsagar** [comment]
`nixos-unstable` is up-to-date, I was asking for the changes to be cherry-picked to `nixos-17.09`. Can I open a PR for that?

**Comment by peti** [comment]
Why not?

**Comment by vaibhavsagar** [comment]
Ah, I didn't realise I could. Thanks!
