### ISSUE TITLE
Factorio build isn't allowed with allowUnfree set.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#30836]
## Issue description

It appears the allowUnfree handling is broken somehow for at least the Factorio derivation.

```
root@lenovo /e/nixos (master)> nixos-rebuild switch -j 8
building Nix...
building the system configuration...
error: Package ‘factorio-alpha-0.15.34’ in /nix/store/cw6xscxg5y6vriyc2brg05h23vk3yj64-nixos-17.09.1813.bf3dbc2b38/nixos/pkgs/games/factorio/default.nix:90 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
root@lenovo /e/nixos (master) [1]> nix-repl '<nixpkgs>' '<nixpkgs/nixos>'
Welcome to Nix version 1.11.15. Type :? for help.

Loading ‘<nixpkgs>’...
Added 7870 variables.

Loading ‘<nixpkgs/nixos>’...
Added 5 variables.

nix-repl> config.nixpkgs.config.allowUnfree
true
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.09.1756.c99239bca0 (Hummingbird)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.15`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.09.1813.bf3dbc2b38"`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

**Comment by seanparsons** [comment]
This broke a day ago for me and I've not changed the Factorio or unfree config in at least a month.

**Comment by seanparsons** [comment]
What's double weird about this is that on another machine I get a login failed error.

**Comment by FRidh** [comment]
```
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

```
Did you do a) or b) ?

**Comment by seanparsons** [comment]
@FRidh a) As you can see from the bottom of the big shell listing.

**Comment by seanparsons** [comment]
Right, I figured out this was because of the way I tried to reference it within one nix file which was imported into the file that defined the unfree config.
