### ISSUE TITLE
bcc nix expression file syntax error

### ISSUE THREAD

**Issue by ScottFreeCode** [NixOS/nixpkgs#30834]
## Issue description

Getting "error: syntax error, unexpected $undefined, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE, at /nix/store/.../nixpkgs/pkgs/os-specific/linux/bcc/default.nix:29:27" when running various `nix-env` commands after recent `nix-channel --update` on MacOS.

Looks like this line is from https://github.com/NixOS/nixpkgs/commit/8ee94216d37e4205a0eb3bb6387cb234b8f2ab0d#diff-c74e966bd35a02adf1e310fbcf2c8dd5R29

(In my Nix novice mind this raises questions about whether and when it's appropriate to pull in other OS's os-specific packages/expressions and whether postinstall actions should be messing up things other than installing that package, but I can imagine things like cross-compilation or parsing the whole expression where this might be correct for all I know, so... :man_shrugging:)

### Steps to reproduce

On a Mac (or a machine subscribed to he affected channel[s]?), `nix-channel --update` followed by `nix-env -qc`.

## Technical details

* System: Mac OS X 10.12.6 Sierra
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "18.03pre118635.ed0f558fb0"
* Sandboxing enabled: grep: /etc/nix/nix.conf: No such file or directory

### additional technical notes

(I have a feeling I could find a Mac equivalent of `/etc/nix/nix.conf` if I looked around enough in my system or the documentation, but it didn't come up with some naive `find` searches and I need to go get other suff done at the moment; sorry! If I have time I'll see if I can find it.)

The output for the "Nixpkgs version" entry above reminds me of the `pre` version number I have previously seen when looking at whether a new `nix` update is available. I'd been ignoring that assuming that it was a beta or release-candidate and I'd upgrade when a stable version came out, but maybe that `pre` thing is just how Nix is versioned on Mac and I should have updated it? I suppose -- in theory -- I *should* be able to upgrade Nix and roll it back if it manages itself through the same package system, so let me know if I should try that to see if it resolves this error.

Also let me know if there's any other system/environment setup/conditions I should look at; I don't think I customized much if anything, but I can imagine there being things to double-check in obscure and/or edge cases.

**Comment by orivej** [comment]
Your nix is old indeed. It fails to parse a valid string, please update `nix` with `nix-env -u nix` (or all installed packages with `nix-env -u`).

**Comment by ScottFreeCode** [comment]
Yup, that was it -- had to `nix-channel --rollback` in order for `nix-env -qa nix` or `nix-env -u nix` to work, but then I was able to see 1.11.15 and 1.12pre... in `nix-env -qa nix` and upgrading to 1.11.15 was sufficient.

Thanks!!

Tangentially: I usually use `nix-env -qc` to check for available updates, but that never showed me newer 1.11.x entries, only the 1.12pre... entry; is it possible to make `nix-env -qc` ignore pre versions?

**Comment by orivej** [comment]
> is it possible to make nix-env -qc ignore pre versions (e.g. by providing some additional flag to the command)?

AFAIK `nix-env -q` always ignores package priorities. Maybe we should rename unstable Nix to `nix-unstable` so that the pre version does not shadow the stable version: #30880

**Comment by orivej** [comment]
@dezgeg Has restored the compatibility with old nix in #31179
