### ISSUE TITLE
[wofi-emoji] `line 5: wtype: command not found`

### ISSUE THREAD

**Issue by mobsenpai** [NixOS/nixpkgs#308357]
### Describe the bug
wofi emoji gives error: `line 5: wtype: command not found`. 

### Steps To Reproduce
1. Installed wofi-emoji using nix shell nixpkgs#wofi-emoji
2. Ran wofi-emoji by typing wofi-emoji followed by pressing enter
3. Chose any option (emoji)
4. The immediate error is given `line 5: wtype: command not found`

### Expected behavior
It should not give this error and it should print the emoji in the terminal also copy it to paste it somewhere else.

### Additional context
I know that it wants `wtype` to be installed but as you can see it's a crucial part of `wofi-emoji` for it to even work properly, without it, it doesn't even copy the emoji or prints it, so basically I am saying that it should be made a dependency of `wofi-emoji` package and installed alongside it?

If I am saying something wrong or stupid. Please do correct me.

### Notify maintainers
@ymarkus 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.86, NixOS, 23.11 (Tapir), 23.11.20240417.e402c3e`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

---
#301907 I am sorry, I made one in the wrong format. I can't delete that now.

**Comment by JohnRTitor** [comment]
[The fix](https://github.com/NixOS/nixpkgs/blob/58a1abdbae3217ca6b702f03d3b35125d88a2994/pkgs/applications/misc/wofi-emoji/default.nix#L19) is already in unstable channel. So I could not reproduce, the version there is still pretty out of date though, I will make a PR to update this, and then backport the changes to stable once that's done.

**Comment by mobsenpai** [comment]
Solved in unstable version. Needs backporting.#308412
