### ISSUE TITLE
Digital Ocean image does not build

### ISSUE THREAD

**Issue by lugeha** [NixOS/nixpkgs#308404]
### Describe the bug

d87c4e1a720f827996c282d0e194850a8903cebe
3f71d1bc02b6100222e440a6ad0571d8e0db4896

Break _system.build.digitalOceanImage_ as _boot.loader.grub.device_ must be defined in [make-disk-image.nix](https://github.com/NixOS/nixpkgs/blob/b8e911463ec39614240a5164030090e22a785c02/nixos/lib/make-disk-image.nix#L606)

Simply defining _boot.loader.grub.device_ does not work as the entry is then duplicated in _boot.loader.grub.devices_ which then enables _boot.loader.grub.mirroredBoots_ causing the build to fail as well.

Either there is an unintended side effect of the single device being added to devices, or this is by design.

Replacing _boot.loader.grub.devices_ with _boot.loader.grub.device_ has the same effect on the aforementioned commits, but also lets the image be built.

I have verified this in repl, as well as building the target.

https://github.com/lugeha/nixpkgs/commit/1d4f0d18709baa9643a2484d05f9fa7f8f3cf5d9

I can submit it as a PR if this is the desired solution.

**Comment by alejandro-angulo** [comment]
I think I'm running into this same issue. Here's the output I'm seeing

```
Booting from ROM...
Probing EDD (edd=off to disable)... oloading kernel modules...
mounting Nix store...
mounting host's temporary directory...
starting stage 2 (/nix/store/hwp2r3d1w6zzsvca7ir4yaw1v8kqxwgk-vm-run-stage2)
tune2fs 1.47.0 (5-Feb-2023)
Setting maximal mount count to -1
Setting interval between checks to 0 seconds
Setting time filesystem last checked to Mon May 27 06:45:15 2024

dirname: missing operand
Try 'dirname --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
[    2.428712] reboot: Power down
```

I worked around this by adding the following to my configuration:

```nix
boot.loader.grub.devices = lib.mkForce ["/dev/vda"];
boot.loader.grub.device = "/dev/vda";
```

**Comment by arianvp** [comment]
Cc @Mic92

**Comment by Mic92** [comment]
Maybe fixed by https://github.com/NixOS/nixpkgs/commit/1ea32d4f698230e2c1e765d857c44b17daa377b4 ?

**Comment by alejandro-angulo** [comment]
Got around to testing this again and I can confirm this has been fixed. The workaround in https://github.com/NixOS/nixpkgs/issues/308404#issuecomment-2133699882 isn't needed anymore.

@Mic92 I think this issue can be closed now (I'm assuming you have permissions to mark issues as resolved).
