### ISSUE TITLE
ProtonUp-Qt not starting

### ISSUE THREAD

**Issue by loissascha** [NixOS/nixpkgs#308477]
### Describe the bug
Whenever I try to start protonup-qt I get an error about libzstd.so.1 missing.

### Steps To Reproduce
1. switch to unstable channel
2. add protonup-qt to configuration.nix
3. try and open protonup-qt 

### Expected behavior
Application opens

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/69523055/2a14b8fd-1fba-4f36-9f21-b3f15fa37725)

### Additional context
not sure when exactly this happened as I didn't use protonup-qt for quite a while. Also tried running it in a vm with the zen kernel but had the same issue there.

### Notify maintainers
@r-ryantm @michaelBelsanti 

### Metadata
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.8-cachyos, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by loissascha** [comment]
I have now tested it on KDE Plasma 6 aswell and it seems to work there. I tried it on Gnome previously where it didn't work.

**Comment by michaelBelsanti** [comment]
this was fixed by #307294, try updating your channel
