### ISSUE TITLE
eww 0.6.0 string truncation problems?

### ISSUE THREAD

**Issue by antoniocorbi** [NixOS/nixpkgs#308473]
### Describe the bug
After upgrading to eww 0.6.0 from unstable I've got problems showing some strings in some of my widgets, one that shows the hour and another the minutes using two digits each one, i.e. : "09 : 10".

When using eww 0.6.0 the string shown is like this: "... : ..."

In eww's github repo I can see that there is a commit after version 0.6.0:

https://github.com/elkowar/eww/commit/2c8811512460ce6cc75e021d8d081813647699dc

And cloning eww repo with that commit, compiling it and using a local eww executable the problem explained before disappears for me.

There's also another problem, asking eww-0.6.0 for version number shows it's @version 0.5.0:

```console
[user@system:~]$  /nix/store/ws61aiclafaga48kb59bgpmh08q6ya5p-eww-0.6.0/bin/eww --version
eww 0.5.0
```

### Steps To Reproduce
1. install unstable eww 0.6.0
2. Use some string truncation (I think this is the problem)
3. I see "..." where a two char string with the hour should appear.

### Expected behavior
eww should work as expected.

### Additional context
Cloning eww repo with latest commit after v0.6.0 was published solves the problem for me.

### Metadata 
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.8, NixOS, 23.11 (Tapir), 23.11.6759.0638fe2715d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixos-23.11, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

**Comment by kiike** [comment]
The current package for eww is [still at the previous release, 0.5.0](https://search.nixos.org/packages?channel=unstable&show=eww&from=0&size=50&sort=relevance&type=packages&query=eww). How did you install 0.6.0 from nixpkgs?

As for the outdated 0.5.0 version in nixpkgs, there are three maintainers for eww in nixpkgs so it probably will be updated shortly, perhaps fetching a commit with the solution to the string truncation problem you describe.

**Comment by antoniocorbi** [comment]
> The current package for eww is [still at the previous release, 0.5.0](https://search.nixos.org/packages?channel=unstable&show=eww&from=0&size=50&sort=relevance&type=packages&query=eww). How did you install 0.6.0 from nixpkgs?

I got it installed today from unstable when upgrading my system:

```console
sudo nix-channel --list
nixos https://nixos.org/channels/nixos-23.11
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
```
But, as you say, if I look for it into unstable (https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=eww) it shows version 0.5.0...I can't understand very well this...I'm relatively new to nixos.

> As for the outdated 0.5.0 version in nixpkgs, there are three maintainers for eww in nixpkgs so it probably will be updated shortly, perhaps fetching a commit with the solution to the string truncation problem you describe.

Ok, I'll wait then. Thanks for your interest in this.

**Comment by kiike** [comment]
Oh sorry, you're right! There *is* eww 0.6.0 in master, although it didn't make it into unstable yet. I built the package and, indeed,

- truncation is broken
- the version is incorrectly reported

So the truncation was fixed, as you mention, after the release, and the reported version [was not bumped by the time the 0.6.0 release happened](https://github.com/elkowar/eww/blob/v0.6.0/crates/eww/Cargo.toml#L3). That [was fixed, too, after the 0.6.0 release](https://github.com/elkowar/eww/commit/8397744f403c87ab39523b4bf9e0216ad444f1bb).

If you can't wait, for it, i'd recommend you use the package output from the eww flake. I personally have been using it for a while and it works correctly. For now, I guess this issue can be closed because both are upstream bugs and the fixes will make it into a future release.

**Comment by JohnRTitor** [comment]
I think I we can backport the changes using patches. I'll send a PR.

**Comment by antoniocorbi** [comment]
> Oh sorry, you're right! There _is_ eww 0.6.0 in master, although it didn't make it into unstable yet. I built the package and, indeed,

Still I don't know how this 0.6.0 version  was pulled from unstable into my system...I'm in my way learning nixos.

> If you can't wait, for it, i'd recommend you use the package output from the eww flake. I personally have been using it for a while and it works correctly (let me know if you need help, i'm on the matrix server with the same username). 

Flakes! my never ending story :). 

I'll try to use it and if I have problems I'll try to ping you on the matrix server. Thx!

**Comment by eclairevoyant** [comment]
> Still I don't know how this 0.6.0 version was pulled

Since 0.6.0 reached unstable, of course, and you updated your channels/inputs.
BTW the search can be out-of-date, so don't expect 100% accuracy from it.

**Comment by antoniocorbi** [comment]
> > Still I don't know how this 0.6.0 version was pulled
> 
> Since 0.6.0 reached unstable, of course, and you updated your channels/inputs. BTW the search can be out-of-date, so don't expect 100% accuracy from it.

Yep, that makes sense to me and seems to be the missing piece that confused me: how could it be possible that in the search appeared version 0.5 and I had installed v 0.6.

@eclairevoyant  thanks for clarifying it for me and for your work in Nixos.
