### ISSUE TITLE
Licensing of youtube-upnext

### ISSUE THREAD

**Issue by bddvlpr** [NixOS/nixpkgs#308542]
As per request of @nbraud in #283286, the licensing of youtube-upnext is rather confusing. It is considered a "fork" of [mpv-youtube-quality](https://github.com/jgreco/mpv-youtube-quality) which also has no LICENSE. It is currently (correctly) marked as unfree.

**Comment by fabaff** [comment]
Hmmm, at first glance I  would say that this issue should be opened at https://github.com/cvzi/mpv-youtube-upnext

For `mpv-youtube-quality` is already an issue present: https://github.com/jgreco/mpv-youtube-quality/issues/17

**Comment by bddvlpr** [comment]
My bad, I misread what nbraud said....
