### ISSUE TITLE
GNUPG Module should create a .gnupg folder in root.

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#30856]
If you enable gnupg:

```
programs.gnupg.agent.enable = true;
programs.gnupg.agent.enableSSHSupport = true;
```

Then if you try to switch to root login shell:

```
sudo --login
```

Gnupg complains about: 

```
gpg-connect-agent: failed to create temporary file '/root/.gnupg/.#lk0x00000000019ff5b0.matrix-central.17464': No such file or directory
gpg-connect-agent: can't connect to the agent: No such file or directory
gpg-connect-agent: error sending standard options: No agent running
```

It can be fixed by creating `/root/.gnupg`.

Maybe activating the module should ensure that the directory `/root/.gnupg` exists?

Alternatively this could be sent upstream to create the `.gnupg` directory if it doesn't exist.

**Comment by kazcw** [comment]
dup of #29331

**Comment by CMCDragonkai** [comment]
Closing due to duplicate.
