### ISSUE TITLE
Update request: LLVM 18.1.4 → 18.1.5

### ISSUE THREAD

**Issue by AMS21** [NixOS/nixpkgs#308748]
- Package name: LLVM
- Latest released version: [18.1.5](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.5)

- Current version on the unstable channel: 18.1.4
- Current version on the stable/release channel: 18.1.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dtzWill
@Ericson2314
@lovek323
@alyssais
@RossComputerGuy
@rrbutani
@sternenseemann

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyssais** [comment]
Want to submit a PR?  The last upgrade was very straightforward: https://github.com/NixOS/nixpkgs/commit/ba69cd4eb436dd367f3f4ec37d0c2f93db7af287

**Comment by AMS21** [comment]
> Want to submit a PR? The last upgrade was very straightforward: [ba69cd4](https://github.com/NixOS/nixpkgs/commit/ba69cd4eb436dd367f3f4ec37d0c2f93db7af287)

I'll give it a shot
