### ISSUE TITLE
Build failure: pkgsi686Linux.ncurses5

### ISSUE THREAD

**Issue by HannesGitH** [NixOS/nixpkgs#308784]
### Steps To Reproduce

1. `nix build nixpkgs#pkgsi686Linux.ncurses5` 

### Build log

```
error: builder for '/nix/store/qrblidcrxqb8mb1llys1rah4r33ipxmc-ncurses-abi5-compat-6.4.drv' failed to produce output path for output 'dev' at '/nix/store/qrblidcrxqb8mb1llys1rah4r33ipxmc-ncurses-abi5-compat-6.4.drv.chroot/nix/store/qjy34z05zcnl9bvv9p99mz9ws06ykk4l-ncurses-abi5-compat-6.4-dev'
```

### Additional context

I stumbled upon this Issue in https://github.com/NixOS/nixpkgs/pull/307983#issuecomment-2086270230, much more context can be seen in that PR

### Notify maintainers

! split ncurses into dev output: @vcunat 

last commit in ncurses: @ConnorBaker 
also output related commits in ncurses: @dezgeg
added i686pkgsLinux.ncurses to android build tools: @Artturin @hadilq 

### Metadata

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240408.4cba8b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - nixpkgs: `/nix/store/450afzqlzzgw6wnyc3dwysf3i5yxyqkr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by HannesGitH** [comment]
> I never touched `ncurses5` package, but if I had time I would run [git bisect](https://git-scm.com/docs/git-bisect) to find the commit that caused this problem. If you don't have time, I'll do it in the next two weeks.

I might be able to do it next week, not sure though..


Weird thing is, as discussed in #307983, that seemingly building androidenv platformtools sometimes results in that build crash, for some not.. 
I'm not that familiar with nix yet, but thats a rather weird occurance to me, might it be that pkgsi686Linux.ncurses5 was buildable once and @FlafyDev still has it cached in his system?
I currently circumvent this problem by removing pkgsi686Linux.ncurses5 from plotformtools build inputs.

does `nix build nixpkgs#pkgsi686Linux.ncurses5` at least result in the same error for someone else or might it be a problem with my system?

**Comment by HannesGitH** [comment]
> `nix build ".#pkgsi686Linux.ncurses5^*"` builds for me and dev contains the files it should @ [d88e2d5](https://github.com/NixOS/nixpkgs/commit/d88e2d581fee6aa0daaea9551628684c5d5eb3cd) (current master)

Ok, thanks for letting me know :)

> Do `nix build nixpkgs#pkgsi686Linux.ncurses5 --rebuild`

 `error: some outputs of '/nix/store/qrblidcrxqb8mb1llys1rah4r33ipxmc-ncurses-abi5-compat-6.4.drv' are not valid, so checking is not possible`

**Comment by vcunat** [comment]
You didn't have a succeeding build, so `--rebuild` doesn't work.  You just run normal build again to retry.

**Comment by FlafyDev** [comment]
> You haven't had a succeeding build yet, so `--rebuild` doesn't work. You just run normal build again to retry.

in the issue they say `nix build nixpkgs#pkgsi686Linux.ncurses5` fails with the same error

**Comment by vcunat** [comment]
I don't know.  I'm unable to reproduce the issue.

**Comment by Artturin** [comment]
Hopefully it works by now.
