### ISSUE TITLE
GRUB bootloader after installing NixOS.

### ISSUE THREAD

**Issue by 4goodapp** [NixOS/nixpkgs#30876]
## Issue description
@srhb 
Specially for noob like me, It would be great to add in the manual How to boot into your other sytems, if you have any , after installing NixOS. Otherwise NixOS will overide the existing bootloader and you may have hard time to know how deal with that if you don't have enough experience with boot/GRUB stuff.

So I think something like this would be great:

*12. If you Already have any system running on your machine before installing NixOS, you may want to get back/boot on them after you finish installing/testing NixOS. So to do that, It's very easy, just add `boot.loader.grub.useOSProber = true;` in your configuration.nix file.*

**Comment by michaelpj** [comment]
I'd go so far as to say maybe this should be on by default. Are there any downsides?

**Comment by srhb** [comment]
@michaelpj I think that's a good idea, but in that case, the recommendation of using systemd-boot for UEFI installs doesn't really work out and should be changed as well.

**Comment by FliegendeWurst** [comment]
Fixed in #30911
