### ISSUE TITLE
Update request: ets 0.2.1 → 0.3.0

### ISSUE THREAD

**Issue by vadimvera** [NixOS/nixpkgs#308789]
- Package name: ets
- Latest released version: 0.3.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

> **NOTE:** Looks like [zmwangx/ets](https://github.com/zmwangx/ets) is not maintained anymore. There is a fork, [gdubicki/ets](https://github.com/gdubicki/ets), that took over from the previous repository.

### Notify Maintainers

@cameronfyfe

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
I am not seeing a 0.3.0 release on their [GitHub repo](https://github.com/zmwangx/ets/), where are you getting this from?

**Comment by kashw2** [comment]
0.3.0 comes from https://github.com/gdubicki/ets, a fork of the original ets.

**Comment by cameronfyfe** [comment]
Nice, I knew this wasn't actively maintained anymore but wasn't aware of this fork. I'll take a look and submit a PR if it looks good and no one else has by the time I get to it.
