### ISSUE TITLE
[Fastfetch] Replace hard coded paths

### ISSUE THREAD

**Issue by CarterLi** [NixOS/nixpkgs#308849]
### Describe the bug

[Fastfetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/fa/fastfetch/package.nix) uses `hwdata/pci.ids` and `libdrm/amdgpu.ids` to convert PCI device ID to human-readable product name.

Currently their paths are hard coded as `/usr/share/hwdata/pci.ids` and `/usr/share/libdrm/amdgpu.ids`. It won't work with NixOS of course.

https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/gpu/gpu_linux.c#L126-L137

I found some packages that have similar issues. They are patched directly before building: https://github.com/NixOS/nixpkgs/blob/662ae2a0cf412fec9f7ffefa16dc4cb70343814b/pkgs/tools/graphics/mangohud/hardcode-dependencies.patch#L38

Fastfetch needs to be patched too.

### Steps To Reproduce

N/A

### Expected behavior

Fastfetch can properly find `pci.ids` and `amdgpu.ids`

### Screenshots

N/A

### Additional context

Reference: https://github.com/fastfetch-cli/fastfetch/issues/855

Fastfetch provided cmake config option [`CUSTOM_PCI_IDS_PATH`](https://github.com/fastfetch-cli/fastfetch/blob/dev/CMakeLists.txt#L81) for `pci.ids` but not for `amdgpu.ids`. I can add one if needed.

### Notify maintainers

@chewblacka @r-ryantm

### Metadata

N/A

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
> Fastfetch provided cmake config option [`CUSTOM_PCI_IDS_PATH`](https://github.com/fastfetch-cli/fastfetch/blob/dev/CMakeLists.txt#L81) for `pci.ids` but not for `amdgpu.ids`. I can add one if needed.

Hi thanks for the detailed issue report! 
This should be pretty straightforward to fix. If you could add a config option for the `amdgpu.ids` path that would be great! Many thanks.

**Comment by CarterLi** [comment]
> Hi thanks for the detailed issue report! This should be pretty straightforward to fix. If you could add a config option for the `amdgpu.ids` path that would be great! Many thanks.

[Done](https://github.com/fastfetch-cli/fastfetch/commit/a4cace476517dc6308e3e931da6174c57582d24d).

`cmake -DCUSTOM_PCI_IDS_PATH=/path/to/pci.ids -DCUSTOM_AMDGPU_IDS_PATH=/path/to/amdgpu.ids`

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.11.3 was released with `CUSTOM_AMDGPU_IDS_PATH` support

**Comment by chewblacka** [comment]
> https://github.com/fastfetch-cli/fastfetch/releases/tag/2.11.3 was released with `CUSTOM_AMDGPU_IDS_PATH` support

Many thanks! Much appreciated.
