### ISSUE TITLE
python2nix: old/wrong/missing dependency?

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#30887]
## Issue description

python2nix doesn't work on stable-17.09.

```
> python2nix
Traceback (most recent call last):
  File "/nix/store/z313xd7cpglh486jd08ckxgsjrgifijm-python2nix-20140927/bin/.python2nix-wrapped", line 8, in <module>
    from python2nix import main
  File "/nix/store/z313xd7cpglh486jd08ckxgsjrgifijm-python2nix-20140927/lib/python2.7/site-packages/python2nix/__init__.py", line 5, in <module>
    from python2nix import pip_deps
  File "/nix/store/z313xd7cpglh486jd08ckxgsjrgifijm-python2nix-20140927/lib/python2.7/site-packages/python2nix/pip_deps.py", line 15, in <module>
    from pip.log import logger
ImportError: No module named log
```

### Steps to reproduce

Run

```
> nix-env -i python2nix
> python2nix
```

## Technical details

* System: 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1880.ac2bb5684c
* Sandboxing enabled: yes

**Comment by Moredread** [comment]
I should have read the README first, it shouldn't be run in this way. On the other hand, just failing is not very helpful.

**Comment by FRidh** [comment]
This is an old package that, as far as I know, is no longer developed/maintained, and should therefore be removed.

**Comment by Moredread** [comment]
It has recent commits though in the repo.

https://github.com/proger/python2nix

**Comment by jonafato** [comment]
From the source repo:

> Tested only with pip==1.5.6.

This version dependency on a 3.5 year old `pip` is the cause of the issue, and the [breaking change](https://github.com/pypa/pip/commit/767d11e49cb916e2d4637421d524efcb8d02ae8d) happened just a few months after that release.

This bug and its fix should be tracked in the upstream package. The package will likely remain broken until an upstream fix is made. In the mean time, the nixpkgs manual lists a few [alternate options](https://nixos.org/nixpkgs/manual/#tools).
