### ISSUE TITLE
xonsh: wrong version of prompt-toolkit library

### ISSUE THREAD

**Issue by amacfie** [NixOS/nixpkgs#308868]
Xonsh [currently requires](https://github.com/xonsh/xonsh/blob/c3cd47e1da46c94e8678a389d5c758311cfb8f24/pyproject.toml#L86) `prompt-toolkit>=3.0.29,<3.0.41` because of https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1853

However, in unstable the [xonsh package](https://github.com/NixOS/nixpkgs/blob/63c3a29ca82437c87573e4c6919b09a24ea61b0f/pkgs/by-name/xo/xonsh/unwrapped.nix#L34) is using [v3.0.43](https://github.com/NixOS/nixpkgs/blob/63c3a29ca82437c87573e4c6919b09a24ea61b0f/pkgs/development/python-modules/prompt-toolkit/default.nix#L12)

**Comment by Qyriad** [comment]
cc @AndersonTorres as maintainer

**Comment by AndersonTorres** [comment]
I am waiting for someone hit the button here:

https://github.com/NixOS/nixpkgs/pull/305316

**Comment by SamLukeYes** [comment]
Upstream has unpinned prompt-toolkit after https://github.com/xonsh/xonsh/pull/5437
