### ISSUE TITLE
skrooge: missing static resources

### ISSUE THREAD

**Issue by greg-hellings** [NixOS/nixpkgs#308978]
### Describe the bug
The skrooge app is missing most of its static resources for icons and such

### Steps To Reproduce
1. Install skrooge
2. Open app from console

### Expected behavior
The app should be able to load its icons and styling

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/273582/9f7086ab-b793-4526-80e7-7d0a6ba3f909)

### Additional context
Console output indicates the large number of missing icon files

### Notify maintainers

@jokogr 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
greg@jude ~/s/nixpkgs 63c3a29ca824 @ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05.20240421.6143fc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(greg): `""`
 - nixpkgs: `/nix/store/cc0ribc27c349w1v2anrby7z8kigy5pq-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Are you running Gnome by any chance? Everything is working fine on Plasma6. I suspect this is related to a recent issue on gnome where non-gtk apps aren't showing their correct icons.

**Comment by greg-hellings** [comment]
Yes, I recently switched from Plasma back to Gnome after resolving some issues I had with Gnome. But I hadn't installed skrooge until after the swap. So that's likely the issue. Thanks!

**Comment by chewblacka** [comment]
I'm marking this as closed as this is an upstream Gnome bug. Hopefully the Gnome developers will fix this issue soon.
