### ISSUE TITLE
stack2nix is broken

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#30899]
## Issue description

Currently when I try to build `stack2nix` it fails:

```
Configuring stack2nix-0.1.3.0...
Setup: Encountered missing dependencies:
Glob >=0.7.14 && <0.8, data-fix ==0.0.4
builder for ‘/nix/store/jy5x91fk2pji64wac5hx6f7jbs28kpk6-stack2nix-0.1.3.0.drv’ failed with exit code 1
error: build of ‘/nix/store/jy5x91fk2pji64wac5hx6f7jbs28kpk6-stack2nix-0.1.3.0.drv’ failed
```

I'm not currently using stack2nix myself, but someone on Reddit was giving NixOS a try and ran into this problem. See: https://www.reddit.com/r/NixOS/comments/77s5t0/generating_a_nix_package_from_a_stack_project/dot54ew/?context=3

### Steps to reproduce

```
nix-build -A stack2nix '<nixpkgs>'
```

## Technical details

* System: NixOS
* Nix version: nix-env (Nix) 1.12pre4911_b30d1e7
* Nixpkgs version: 17.09.1756.c99239bca0
* Sandboxing enabled: `build-use-sandbox = true`

**Comment by razvan-panda** [comment]
Same issue, broken on both stable and unstable.
