### ISSUE TITLE
Package request: scrutiny

### ISSUE THREAD

**Issue by awlsring** [NixOS/nixpkgs#308940]
**Project description**

Scrutiny is an application that allows for HDD monitoring using SMART. Scrutiny can be ran as an all in one application, or be ran in hub and spoke mode where numerous servers report their data to a central backend.

**Metadata**

* homepage URL: https://github.com/AnalogJ/scrutiny/tree/master
* source URL: https://github.com/AnalogJ/scrutiny/tree/master
* license: mit
* platforms: freebsd, linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by frahz** [comment]
Scrutiny is available in NixOS unstable [here](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=scrutiny).

It also has a service that can be used [here](https://search.nixos.org/options?channel=unstable&size=50&sort=relevance&type=packages&query=scrutiny).
