### ISSUE TITLE
clementineFree segfaults

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#30894]
### Steps to reproduce
1. nix-env -iA nixos.clementineFree
2. try to play a vorbis/opus file. (no format works for me, but mp3 and the like probably don't work because of "Free" in the package name.)
result:
```
...
(clementine:7138): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
Segmentation fault
```

this is pretty similar to #10326.
after that i tried installing gstreamer packages. (even though this should only be necessary for additional plugins, right?)
```
$ nix-env -q |grep gst
gst-plugins-bad-1.10.4
gst-plugins-base-1.10.4
gst-plugins-good-1.10.4
gst-plugins-ugly-1.10.4
gstreamer-1.10.4
gstreamermm-1.8.0
qt-gstreamer-0.10.3
```
still the same result.

## Technical details

* System: 17.03.1931.8b8977f9ff (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1931.8b8977f9ff"
* Sandboxing enabled: build-use-sandbox = false

**Comment by orivej** [comment]
Could you try updating to 17.09?

**Comment by castilma** [comment]
i added nixos 17.09 to my channels, updated and installed clementineFree.

```
17:08:46.627 ERROR unknown                          JSonScanner::yylex - error while reading from io device  
17:08:46.627 ERROR unknown                          json_parser - syntax error found,  forcing abort, Line 1 Column 1  

(clementine:11447): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
Segmentation fault
```

Does it work on your machine?

**Comment by orivej** [comment]
Yes, it plays music without crashing, both in unstable and 17.09…

**Comment by castilma** [comment]
did you install any packages like gstreamer{,-plugins}?

i have no idea how gstreamer works under the hood. maybe we/I should try to understand the error message, where it comes from and how to get more information. is there a simpler way to get debuginfo than [this](https://nixos.org/nixpkgs/manual/#sec-modify-via-packageOverrides)?

**Comment by peterhoeg** [comment]
I didn't manage to make things work either in #22366 due to segfaulting but I'll try to take a look over the weekend.

**Comment by jraygauthier** [comment]
I doubt `clementineFree` could play anything as it has no wrapper registering GStreamer plugins. The GStreamer wrapping in `clementine/default.nix` could pretty easily be moved as a helper function and be used directly in `all-packages.nix` to wrap both the free and the spotify enhanced versions.

**Comment by jraygauthier** [comment]
As mentioned by @peterhoeg, the `gst-libav` plugin should most likely be the one you would need (after a shallow reading of ffmpeg doc).

**Comment by castilma** [comment]
did `nix-env -iA nixos.gst_all_1.gst-libav` but still the same. or do i need to change clementinefree's nix-expression?

**Comment by jraygauthier** [comment]
Installing the plugin globally won't help, it has to be passed as an argument to the nix expression same as is done for `clementine`. However, `clementineFree` is the original (i.e: unwrapped) derivation. There should be a little refactor to the expression in order to allow the wrapping.

**Comment by jerith666** [comment]
I believe this issue is superseded by #39960.

**Comment by peterhoeg** [comment]
The superseding issue has been fixed so closing this.
