### ISSUE TITLE
Firefox developer edition package runs as "firefox"

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#30905]
Hi,

Firefox dev unwrapped package starts from command line as "firefox" which it should not be.

It should start something like firefox-dev or something...

Thank you

**Comment by nbp** [comment]
Why should it be different in function of the distribution channel?

**Comment by TerkiKerel** [comment]
@nbp I could not understand what you are asking.

Firefox dev should not start as "firefox". because if you install both firefox(normal version) and firefox dev version , which will start?

I am using UBuntu. As default "firefox" command starts firefox normally which is already installed on system. But after I installed firefox-dev from nix, now my old firefox does not starts.

**Comment by TerkiKerel** [comment]
Can you please inform here if yu will not change the executable name.

If yes please tell me how can I change it locally if possible?

Thank you

**Comment by orivej** [comment]
Put this into your Nixpkgs config (`~/.config/nixpkgs/config.nix`):
```nix
{
  packageOverrides = pkgs: rec {
    my-firefox-esr = pkgs.stdenv.mkDerivation {
      name = "firefox-esr";
      buildCommand = ''
        mkdir -p $out/bin
        ln -s ${pkgs.firefox-esr}/bin/firefox $out/bin/firefox-esr
      '';
    };
  };
}
```
Then install with `nix-env -iA my-firefox-esr` or `nix-env -i firefox-esr`. (Adapt `firefox-esr` to the version you prefer.)

**Comment by TerkiKerel** [comment]
I can not undestand how you accept firefox-dev to start as "firefox" which is the deault firefox package executable name? What will happen if someone will install both of them? 

I don't know what is going on with nixOS but nix is using by all other distros. My distro also %99 of distros already have "firefox" on their paths. If someone will install firefox-dev edition for developer purpose they will conflict. 

This is completly wrong and unacceptable.

**Comment by orivej** [comment]
@TerkiKerel Actually `firefox-devedition-bin` package installs `firefox-devedition` executable. Which firefox-dev package are using that install `firefox` executable?

**Comment by TerkiKerel** [comment]
@orivej firefox-devedition-bin-unwrapped package uses "firefox" executable.

**Comment by TerkiKerel** [comment]
Cna somebody please help. If you need help for test I can. This is a very small bug which makes conflict of packages :(

**Comment by jackTaw88** [comment]
Same on my machine. Firefox dev should not use that executable...

**Comment by baracoder** [comment]
I tried to reproduce and found some unexpected behavior:
```
nix-env -i firefox-devedition-bin
which firefox
/run/current-system/sw/bin/firefox  (installed by system)
which firefox-devedition          
/home/bara/.nix-profile/bin/firefox-devedition
```
This is OK, but
```
nix-env -i firefox-devedition-bin-unwrapped
which firefox                              
/home/bara/.nix-profile/bin/firefox
realpath `which firefox`
/nix/store/4y5fvaw7j8kiybbgzv196n22l5xm8ral-firefox-devedition-bin-unwrapped-65.0b9/bin/firefox
nix-env -e firefox-devedition-bin-unwrapped
which firefox                    
/home/bara/.nix-profile/bin/firefox
realpath `which firefox`
/nix/store/4y5fvaw7j8kiybbgzv196n22l5xm8ral-firefox-devedition-bin-unwrapped-65.0b9/bin/firefox
nix-env -e firefox-devedition-bin 
which firefox           
/run/current-system/sw/bin/firefox
```
So after installing `firefox-devedition-bin-unwrapped` I had to remove both before the `firefox` symlink was gone.

**Comment by jackTaw88** [comment]
@baracoder and thats a bug... It is a simple link bug.

**Comment by prusnak** [comment]
This seems fixed already. The following will not find firefox:

```
$ nix-shell --pure -p firefox-devedition-bin --command firefox
```

**Comment by dsxmachina** [comment]
Coming from NixOS 20.03 - this bug is still there. 

The normal firefox is installed via configuration.nix,
firefox-dev is installed via nix-env.
