### ISSUE TITLE
Update request: zx 7.2.3 → 8.1.2

### ISSUE THREAD

**Issue by jlbribeiro** [NixOS/nixpkgs#309047]
- Package name: zx
- Latest released version: **[google/zx v8.1.2](https://github.com/google/zx/releases/tag/8.1.2)**
  **Changelog**:
    - [google/zx v8.1.1](https://github.com/google/zx/releases/tag/8.1.1)
    - [google/zx v8.1.0](https://github.com/google/zx/releases/tag/8.1.0)
    - [google/zx v8.0.2](https://github.com/google/zx/releases/tag/8.0.2)
    - [google/zx v8.0.1](https://github.com/google/zx/releases/tag/8.0.1)
    - **[google/zx v8.0.0](https://github.com/google/zx/releases/tag/8.0.0)**:
        - includes breaking changes at the API level; unsure of whether this deserves being mentioned on release notes or not;
        - now uses [esbuild](https://github.com/evanw/esbuild); unsure of whether this impacts packaging (too much).

- Current version on the unstable channel: 7.2.3
- Current version on the stable/release channel: 7.2.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
(admittedly not easy, given how short the package name is and how GitHub search works; I apologize in advance if I missed something)

**Notify maintainers**
@hlolli 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hlolli** [comment]
I had forgotten that I was a maintainer here. Please replace me as maintainer if you are using zx, it has fallen off my development radar lately.

**Comment by hlolli** [comment]
I see, it was assigned to me when I added it via the npm2nix structure. It's alright if nobody volunteers, but more maintainers is better:
https://github.com/jlbribeiro/nixpkgs/commit/1d74cc4b3430a2d892a27b46cee380105c4d5ae6

**Comment by jlbribeiro** [comment]
@hlolli I use `zx` regularly, don't mind replacing you as a maintainer.
