### ISSUE TITLE
libretro.ppsspp: system ffmpeg cause glitches

### ISSUE THREAD

**Issue by Sicheng-Pan** [NixOS/nixpkgs#309107]
### Describe the bug
System ffmpeg leads to severe glitches in ppsspp with libretro.

### Steps To Reproduce
See #304616

### Notify maintainers
@aanderse @edwtjo @thiagokokada 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thiagokokada** [comment]
Please just add a comment in the other issue instead of opening another one.
