### ISSUE TITLE
Update request: nodePackages_latest.volar 1.6.5 → 2.0.13

### ISSUE THREAD

**Issue by bymoses** [NixOS/nixpkgs#309125]
- Package name: nodePackages_latest.volar, but new version of it should be called nodePackages_latest.vue-language-server (see [related issue](https://github.com/vuejs/language-tools/pull/3134))
- Latest released version: 2.0.16 (see notes below)

- Current version on the unstable channel: 1.6.5
- Current version on the stable/release channel: 1.6.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@MatthewCash @ryanccn

-----

I've tried to make a derivation by my own, but it appears to be a little bit more complex than I thought. It's my first attempt to make something within nix ecosystem tho.
I faced the version incompatibility issue with current pnpm (8.15.8) in unstable channel and [pnpm-lock.json](https://github.com/vuejs/language-tools/blob/master/pnpm-lock.yaml) of v2.0.16. It requires at least ^9 version of pnpm. So I decided to use latest available to build version which is 2.0.13. After a couple attempts I've created buildable draft of derivation, but couldn't figure out how to extract needed bin script to $out dir

```nix
{ lib
, stdenv
, fetchFromGitHub
, stdenvNoCC
, nodePackages
, pkg-config
, jq
, moreutils
, cacert
}:

stdenv.mkDerivation rec {
  pname = "vue-language-server";
  version = "2.0.13";

  src = fetchFromGitHub {
    owner = "vuejs";
    repo = "language-tools";
    rev = "v${version}";
    hash = "sha256-YORq0czhVb0B0OMJG4V0W0tuNlhgvfnbA4SAneSgvMM=";
  };

  pnpm-deps = stdenvNoCC.mkDerivation {
    pname = "${pname}-pnpm-deps";
    inherit src version;

    nativeBuildInputs = [
      jq
      moreutils
      nodePackages.pnpm
      cacert
    ];

    installPhase = ''
      export HOME=$(mktemp -d)
      pnpm config set store-dir $out
      # use --ignore-script and --no-optional to avoid downloading binaries
      # use --frozen-lockfile to avoid checking git deps
      pnpm install --frozen-lockfile --no-optional --ignore-script

      # Remove timestamp and sort the json files
      rm -rf $out/v3/tmp
      for f in $(find $out -name "*.json"); do
        sed -i -E -e 's/"checkedAt":[0-9]+,//g' $f
        jq --sort-keys . $f | sponge $f
      done
    '';

    dontFixup = true;
    dontBuild = true;
    outputHashMode = "recursive";
    outputHash = "sha256-ga1LdDVwaiiwidy7WHBtwHDnfwfbqpgSWAY5Xb40Wyg=";
  };

  nativeBuildInputs = [
    nodePackages.pnpm
    pkg-config
  ];

  preBuild = ''
    export HOME=$(mktemp -d)
    export STORE_PATH=$(mktemp -d)
    cp -Tr ${pnpm-deps} "$STORE_PATH"
    chmod -R +w "$STORE_PATH"

    pnpm config set store-dir $STORE_PATH
    pnpm install --offline --frozen-lockfile --no-optional --ignore-script
    patchShebangs node_modules/{*,.*}

    pnpm build
  '';

  installPhase = ''
    echo "What's next??"
  '';

  meta = with lib; {
    description = "";
    homepage = "https://github.com/vuejs/language-tools";
    license = licenses.mit;
    mainProgram = "vue-language-server";
    platforms = platforms.all;
  };
}

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yzx9** [comment]
volar has been removed since #319134
