### ISSUE TITLE
direct links to tarballs from www.kernel.org are broken (e.g. keyutils-1.6.3.tar.gz)

### ISSUE THREAD

**Issue by boxofrox** [NixOS/nixpkgs#309194]
### Describe the bug
I mistakenly ran a `nix build --offline` on one of my flakes today, which tried to build a bunch of packages (to be expected), but the process failed when keyutils failed to download it's source tarball from https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-1.6.3.tar.gz .

Attempts to visit the download link with a web browser complain that the archive format is unsupported.  I can only assume upstream reconfigured the snapshots in their cgit.

The obvious work-around is to remove the `--offline` and pull substitutions from the cache, but I figured we might want to find a working url for this package at some point.

### Expected behavior
I expected the source to download and build without error.

### Notify maintainers
None listed.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by srhb** [comment]
This looks like it affects all tarballs from the git.kernel.org cgit instance. The download links are also gone from the UI. If there was no announcement about this, it feels unintentional.

**Comment by srhb** [comment]
(I've sent an e-mail to what I *think* is the instance administrator, but it's not exactly clear...)

**Comment by srhb** [comment]
The direct tarball links from www.kernel.org are also broken so this seems very unintentional. Maybe we can update the issue title?

**Comment by srhb** [comment]
Upstream got back to me,

> Yes, this is a temporary measure to combat a denial of service by
> Tencent. They have an aggressive bot that is crawling snapshot URLs from
> thousands of IPs, using generic user-agent headers.
> 
> We will have a more fine-tuned block in place on Monday.

So it was intentional, and presumably this should be resolved sometime today. :)

**Comment by srhb** [comment]
It appears upstream have found a solution and the cgit snapshots are back online. I did a cursory check, but it appears to be fine across the board. :smile_cat:
