### ISSUE TITLE
Package request: PKHeX

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nixpkgs#309157]
**Project description**

pokemon save file editor

**Metadata**

* homepage URL: https://github.com/kwsch/PKHeX
* source URL: https://github.com/kwsch/PKHeX
* license: gpl3
* platforms: windows, linux via mono

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSamus** [comment]
PKHeX doesn't support Mono/Linux, it uses Windows Forms and features that are only available on .NET 8.

**Comment by Rucadi** [comment]
Maybe you find luck packaging it with https://github.com/emmanuelrosa/erosanix/tree/master/pkgs/mkwindowsapp

**Comment by Gerg-L** [comment]
The developer has no intent to make the app linux compatible, use wine
