### ISSUE TITLE
Package request: pytables

### ISSUE THREAD

**Issue by Tech-Data-Maestro** [NixOS/nixpkgs#309215]
**Project description**

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by javaes** [comment]
It's already available. Its name on pypi is `tables`, that's why you find it as `python312Packages.tables` or `python312Packages.tables`.

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/tables/default.nix
