### ISSUE TITLE
LibreOffice doesn’t see installed Aspell dictionaries

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#30920]
## Issue description

Installed Aspell dictionaries are not visible in LibreOffice, in spite of https://github.com/NixOS/nixpkgs/pull/30234 and https://github.com/NixOS/nixpkgs/issues/28815.

/cc @deedrah @bjornfor @FRidh 

### Steps to reproduce

1. Use the current `nixos-unstable`.
1. Install `[ libreoffice aspell aspellDicts.de ]`.
1. Run `swriter`.
1. Go to Tools → Spelling and grammar → Text language
1. The list is empty, while it should at least contain `de_DE`.

## Technical details

* System: 66b63d2f5a442d642ac2b226d71b4f97bafce5c8
* Sandboxing enabled: yes

**Comment by deedrah** [comment]
At first look, LibreOffice supports only dictionaries for hunspell. Aspell is not even in LibbreOffice dependencies.

**Comment by orivej** [comment]
This is not a nixpkgs issue, LibreOffice itself has no support for aspell.
