### ISSUE TITLE
plymouth 24.004.60 segmentation fault

### ISSUE THREAD

**Issue by jh-devv** [NixOS/nixpkgs#309259]
### Describe the bug
When inputting an LUKS password, and you wait ~30 seconds, the system becomes unresponsive.

The logs shown an core dump and that `the root account is locked`?

### Steps To Reproduce
1. Boot
2. Don't input an password on plymouth
3. Wait ~30 seconds
4. System becomes unresponsive

### Expected behavior
`plymouth` should not crash

### Additional context
This could be related to something else, like why is the root account locked after some time on the LUKS password screen?

### Notify maintainers

@cillianderoiste 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[jh-devv@lumi:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
This usually happens when the password prompt times out and the kernel crashes because it has no kernel. Do you have such timeout configured?

**Comment by jh-devv** [comment]
> This usually happens when the password prompt times out and the kernel crashes because it has no kernel. Do you have such timeout configured?

Actually, yes!

By default, on NixOS; the timeout for entering an LUKS password is set to `infinity`,
However, when using LVM with LUKS, AFAIK this is not done automatically.

You have to set the timeout back to `infinity` to avoid, for example your `plymouth` from crashing. You can do this with:
```
boot.initrd.systemd = {
  enable = true;

  units."dev-mapper-vg\\x2droot.device".text = ''
    [Unit]
    JobTimeoutSec=infinity
  '';
};
```
^ Remember to replace the volume name with the correct one.
