### ISSUE TITLE
Add NixOS option for /etc/fuse.conf entries

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#30923]
Right now ipfs module puts in a `user_allow_other` into /etc/fuse.conf. However if other modules also make use of fuse, how would these settings be resolved? Should there be an option for fuse settings, that all modules make use of, and can alert errors if there are conflicting entries?

We need to have a centralised option for configuring the `/etc/fuse.conf` usable by all services like IPFS or SSHFS or S3FS... etc.

**Comment by bjornfor** [comment]
Sounds good. (But perhaps also have an "extraConfig" option as escape hatch.)

**Comment by garbas** [comment]
Was there any PR being open relating to this issue? Maybe rephrasing an issue to sound more like a feature request then a question, would be better. Also it wouldn't hurt bringing this up on the mailing list.

**Comment by rasendubi** [comment]
Do I understand correctly that there are only two options that could be specified in `fuse.conf`? (`mount_max` and `user_allow_other`)

https://manpages.debian.org/testing/fuse/mount.fuse.8.en.html#CONFIGURATION

**Comment by kmarisa** [comment]
As of 18.09 fuse looks in the nix store for the fuse.conf file, which means it is now impossible to set either of those options even with ```environment.etc."fuse.conf"```.

**Comment by Jumblemuddle** [comment]
Yeah, @kmarisa, I can't get fuse to read my `/etc/fuse.conf` file.
Is there a workaround or any progress on a final solution?
I'm trying to get fuse to respect `user_allow_other`, but I can't find any way at the moment.

**Comment by rasendubi** [comment]
@kmarisa @Jumblemuddle See https://github.com/NixOS/nixpkgs/issues/59021.

The fix has been added to [master](https://github.com/NixOS/nixpkgs/pull/59043) and [backported to 19.03](https://github.com/NixOS/nixpkgs/pull/59166).

**Comment by CMCDragonkai** [comment]
Is this issue finally resolved? Is there nixos options to set this config?

**Comment by primeos** [comment]
> Is this issue finally resolved? Is there nixos options to set this config?

Not yet, but I've just created a PR (#66480) as it seems to become quite relevant.
