### ISSUE TITLE
Package/module request: homebox

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#309299]
**Project description**

> Homebox is the inventory and organization system built for the Home User.

Like a simpler Snipe-IT for home usage. Keep track of inventories, warranties, and manuals.

**Metadata**

* homepage URL: https://hay-kot.github.io/homebox/
* source URL: https://github.com/hay-kot/homebox
* license: APL3
* platforms: presumably Go's platforms?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ambroisie** [comment]
It makes use of `pnpm`, so #231513 is technically a blocker.

I'm hoping it will work with `pnpm-lock-export` to bypass that issue.

**Comment by ihaveamac** [comment]
homebox was archived: https://github.com/hay-kot/homebox/issues/919

**Comment by eclairevoyant** [comment]
feel free to reopen if there's maintained, viable fork.

**Comment by ambroisie** [comment]
I see https://github.com/zodac/homebox picking up activity, tentatively re-opening the issue for now. Will revisit to see if it keeps being maintained long term.

**Comment by grbray** [comment]
There's an active repo being worked on here: https://github.com/sysadminsmedia/homebox
