### ISSUE TITLE
Build failure: streamlink

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#309389]
### Steps To Reproduce

1. build *streamlink* on unstable

### Build log

https://gist.github.com/l0b0/be3d0afcce541df261adc086d1a069fa

### Additional context

This broke in the last few days.

### Notify maintainers

@dezgeg @zraexy @DeeUnderscore

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05pre619660.63c3a29ca824`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DeeUnderscore** [comment]
Should be addressed by #309326
