### ISSUE TITLE
Build failure: python3.11-dbus-python-1.3.2-aarch64-unknown-linux

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#309395]
### Steps To Reproduce

1. try to build this from nixos-unstable (e9be4245)

`nix  build -L github:nixos/nixpkgs/nixos-unstable#legacyPackages.x86_64-linux.pkgsCross.aarch64-multiplatform.python3Packages.dbus-python `

### Build log

```
       last 10 log lines:
       > Run-time dependency python found: YES 3.11
       > Configuring TestSuitePythonService.service using configuration
       > Configuring tmp-session-bus.conf using configuration
       > Program dbus-run-session found: NO
       >
       > ../test/meson.build:72:19: ERROR: Program 'dbus-run-session' not found or not executable
       >
       > A full log can be found at /build/dbus-python-1.3.2/_meson-build/meson-logs/meson-log.txt
       >
       > ERROR Backend subprocess exited when trying to invoke build_wheel
       For full logs, run 'nix log /nix/store/ggv0x9yrgas3rqqy33fg4dgjhhfqip78-python3.11-dbus-python-1.3.2-aarch64-unknown-linux-gnu.drv'.
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by colemickens** [comment]
Adding `dbus` to `nativeBuildInputs` "fixes" the build, but I'm not sure if that's totally valid.

**Comment by Mic92** [comment]
It's a valid fix. I made it part of https://github.com/NixOS/nixpkgs/pull/308196

**Comment by andrewbaxter** [comment]
#308196 is merged.  Can this be closed?
