### ISSUE TITLE
Update request: asusctl 5.0.10 → 6.0.0

### ISSUE THREAD

**Issue by 500InternalError** [NixOS/nixpkgs#309474]
- Package name:asusctl
- Latest released version:6.0.0

- Current version on the unstable channel:5.0.10
- Current version on the stable/release channel:4.7.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@K900 @aacebedo 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 500InternalError** [comment]
I tried to update it myself but I can't fix this issue: 
```
the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
```

**Comment by JohnRTitor** [comment]
I tried updating this too, and encountered the same problem with 6.0.1.

Here's what I tried https://github.com/JohnRTitor/nixpkgs/commit/86c0a4e21ce6a581169d914f4af51b5ca9fff7a6, can be helpful for other users.

I tried using this from this thread: https://discourse.nixos.org/t/cargo-wants-to-update-lock-file-even-when-all-git-dependencies-have-provided-hashes/25405
```
  preConfigure = ''
    sed -zi 's;"env_logger",\n "futures-lite 1.13.0",;  "env_logger",\n "futures-lite 2.3.0",;' Cargo.lock
  '';
```
But that too, does not work. Perhaps it's time to ask upstream to update their lockfile.

**Comment by 500InternalError** [comment]
> I tried updating this too, and encountered the same problem with 6.0.1.
> 
> Here's what I tried [JohnRTitor@86c0a4e](https://github.com/JohnRTitor/nixpkgs/commit/86c0a4e21ce6a581169d914f4af51b5ca9fff7a6), can be helpful for other users.
> 
> I tried using this from this thread: https://discourse.nixos.org/t/cargo-wants-to-update-lock-file-even-when-all-git-dependencies-have-provided-hashes/25405
> 
> ```
>   preConfigure = ''
>     sed -zi 's;"env_logger",\n "futures-lite 1.13.0",;  "env_logger",\n "futures-lite 2.3.0",;' Cargo.lock
>   '';
> ```
> 
> But that too, does not work. Perhaps it's time to ask upstream to update their lockfile.

I think `Cargo.lock` is updated, because when I manually build it, cargo leaves the lockfile untouched, which makes it really wierd.

**Comment by K900** [comment]
It's a general Rust issue, see https://github.com/NixOS/nixpkgs/pull/310579

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/310287

**Comment by soulsoiledit** [comment]
It's working good on my G14 2022.

**Comment by ninelore** [comment]
Something seems to be missing thats causing Anime Matrix to break
```
Mai 17 01:14:52 9l-zephyr asusd[2549]: [INFO  asusd] AniMe control: AniMe Matrix error: Could not open: No such file or directory (os error 2)
```
