### ISSUE TITLE
booting from luks drive fails with latest kernel

### ISSUE THREAD

**Issue by KaiLemke** [NixOS/nixpkgs#30940]
[configuration.nix.txt](https://github.com/NixOS/nixpkgs/files/1425477/configuration.nix.txt)
## Issue description

With `boot.kernelPackages = pkgs.linuxPackages_latest;` it seems to be quite impossible to decrypt an aes-xts-plain64 luksFormated LVM partition in stage 1.

It fails with the message 

> failed to decrypt [...] please check that your kernel supports aes-xts-plain64

With the 4.9 kernel it is no problem even without adding modules for stage 1.

Background, why I need latest kernel is, that I would like to test [btrfs](https://btrfs.wiki.kernel.org/index.php/Main_Page) in this setup.

### Steps to reproduce

1. create live-usb with NixOS-17.09 and the minimal-new-kernel image and boot it
1. partition hdd: sda1 = linux, sda2 = lvm
1. `cryptsetup -v -y /dev/sda2 lvm`
1. setup lvm: lvs are swap and root:ext4 and setup sda1:ext4
1. `mount /dev/mapper/vg-root /mnt; mount /dev/sda1 /mnt/boot`
1. `nixos-generate-hardware-configuration --root /mnt`
1. copy attached configuration.nix
1. reboot

## Technical details

* System: NixOS-17.09 linux-4.13
* Nixpkgs version: commit 56b9886b959e5db24a3a8a5beaaf427a00a03743

**Comment by YorikSar** [comment]
I've just verified this on my laptop and it worked just fine. I use `aes-xts-plain64` as well, after I've added `boot.kernelPackages = pkgs.linuxPackages_latest` to my `configuration.nix`, ran `nixos-rebuild boot` and rebooted, I've managed to boot into working system.

The main difference for me is that I use systemd-boot to boot from EFI instead of Grub2, but this shouldn't affect modules available to kernel at that stage.

**Comment by KaiLemke** [comment]
Thank you for your fast response.

I have no EFI device, so I cannot proof this, but also on another machine I get the samer error.

Are there any differences in the encryption (key size, luks version)?
Please see the [output](https://github.com/NixOS/nixpkgs/files/1428007/luksstatus.txt) of my `cryptsetup -v status lvm`.

**Comment by YorikSar** [comment]
Yes, I have almost same output there, only `device` and `size` differ.

**Comment by mekeor** [comment]
Is anybody else also still suffering from this?

**Comment by aristidb** [comment]
I think the fix is incomplete, as it does not help users which set their own cryptoModules.

**Comment by mekeor** [comment]
This fixed it for me:

```
boot.initrd.kernelModules = [ "xts" "ecb" ];
```

([Source](https://botbot.me/freenode/nixos/2017-04-07/?msg=83616888&page=8).) Not sure if both modules are needed.
