### ISSUE TITLE
Build failure: pretalx

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#309571]
### Steps To Reproduce

1. build *pretalx*

### Build log

```
buildPhase completed in 42 seconds
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for pretalx-2024.1.0-py3-none-any.whl
  - celery~=5.3.0 not satisfied by version 5.4.0
  - css-inline~=0.13.0 not satisfied by version 0.14.0
  - markdown~=3.5.0 not satisfied by version 3.6
  - pillow~=10.2.0 not satisfied by version 10.3.0
  - reportlab~=4.1.0 not satisfied by version 4.2.0
```

### Notify maintainers

@astro @SuperSandro2000 @tanneberger @oxapentane

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.8, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
I only knew about it, because I was requested for review 😉
