### ISSUE TITLE
NixOS module request: open-webui (formerly ollama-webui)

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#309567]
**Project description**

WebUI service for Large Language Models

Video demonstration by [NetworkChunk](https://www.youtube.com/@NetworkChuck): https://youtu.be/Wjrdr0NU4Sk?t=570

.. basically self-hostable ChatGPT-like service

**Metadata**

* homepage URL: https://openwebui.com
* source URL: https://github.com/open-webui/open-webui
* license: mit
* platforms: unix, linux, darwin

**Additional info**

Follow-up on https://github.com/NixOS/nixpkgs/issues/273556 for open-webui nixos module.

There seems to be an ongoing work on the subject by @mschwaig and @malteneuss on https://github.com/NixOS/nixpkgs/compare/master...mschwaig:nixpkgs:open-webui

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kreyren** [comment]
Relevant Merge Request: https://github.com/NixOS/nixpkgs/pull/275448

**Comment by mausch** [comment]
Just for reference / workaround here's another nix package: https://github.com/shivaraj-bh/ollama-flake/tree/main/pkgs/open-webui

**Comment by malteneuss** [comment]
@mausch Thanks for that reference. That pdm tool workaround looks a lot more maintainable for the Python backend. Maybe i'll have time to try another PR in the next weeks.
In the meantime and as a much simpler UI i packaged https://github.com/jakobhoeg/nextjs-ollama-llm-ui as part of PR https://github.com/NixOS/nixpkgs/pull/313146. It would be great if someone could review it.

**Comment by shivaraj-bh** [comment]
I would like to mention that in the latest release `open-webui` switched to [downloading `pyodide` dependencies in build time](https://github.com/open-webui/open-webui/commit/781c904c9139664fc3ac3d3fff226f42664c510b#diff-4d9c75b954942e02f9bab6033e03da1bd6c16470092e8ec4cfc480f31c750115), I am not sure of any straightforward to do this while packaging it for `nixpkgs`.

**Comment by drupol** [comment]
@shivaraj-bh I just tested your flake, it's impressive, especially the nice UI at the end showing all the processes !

Regarding open-webui, it would be so nice to have that in `nixpkgs` !!!

**Comment by shivaraj-bh** [comment]
> I just tested your flake, it's impressive, especially the nice UI at the end showing all the processes !

Thank you, planning to have more UIs and devShell integration (for CLI tools that interact with ollama).

> Regarding open-webui, it would be so nice to have that in nixpkgs

I would love that too! Although there are a few challenges (like the one I pointed above regarding `pyotide`), I am willing to contribute here. 

Also, `open-webui` maintainers are quick to respond, in case we need any upstream contributions to make it happen.
