### ISSUE TITLE
Build failure: waybar-0.10.2 - aarch64 with asahi

### ISSUE THREAD

**Issue by zvolin** [NixOS/nixpkgs#309639]
### Steps To Reproduce

1. add `home.packages = [ pkgs.waybar ];`
2. sudo nixos-rebuild switch

### Build log

```
❯ sudo nixos-rebuild switch --flake /persist/etc/nixos#mbp-m2
warning: Git tree '/persist/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/persist/etc/nixos' is dirty
error: builder for '/nix/store/ifrihr34mpslmyxx0fznnj9zb69b4yi5-waybar-0.10.2.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency libudev found: YES 255
       > Run-time dependency libevdev found: YES 1.13.1
       > Run-time dependency libmpdclient found: YES 2.22
       > Run-time dependency xkbregistry found: YES 1.5.0
       > Run-time dependency jack found: YES 1.9.22
       > Run-time dependency wireplumber-0.5 found: NO (tried pkgconfig)
       >
       > meson.build:95:17: ERROR: Dependency "wireplumber-0.5" not found, tried pkgconfig
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/ifrihr34mpslmyxx0fznnj9zb69b4yi5-waybar-0.10.2.drv'.
error: 1 dependencies of derivation '/nix/store/y6pk94jmdlwj55a120l11i8k80gbpf2r-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6rqyp39zq2bgd7pfgc43fvjyfb3yf1bb-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pbmyfca7mq6qb053qfmkgpz8fcbn7js5-unit-home-manager-zwolin.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w0bj6086c3swygkmg6s422rlj9xnls9g-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yhcww3q9c9bg7cbx23in2y963wpx7qal-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kyb7mavjjk8ggy62c7kf9iv6h7i714ij-nixos-system-nixos-24.05.20240505.25865a4.drv' failed to build
```

### Additional context

I asked about this on discord and got a few responses that everything builds fine for x86-64. I'm not sure how this is relevant but I'm using macbook pro m2, with https://github.com/tpwrules/nixos-apple-silicon. Everything was fine so far and today I did `nix flake update` and tried to rebuild.

```diff
     "nixpkgs": {
       "locked": {
-        "lastModified": 1712963716,
-        "narHash": "sha256-WKm9CvgCldeIVvRz87iOMi8CFVB1apJlkUT4GGvA0iM=",
+        "lastModified": 1714906307,
+        "narHash": "sha256-UlRZtrCnhPFSJlDQE7M0eyhgvuuHBTe1eJ9N9AQlJQ0=",
         "owner": "nixos",
         "repo": "nixpkgs",
-        "rev": "cfd6b5fc90b15709b780a5a1619695a88505a176",
+        "rev": "25865a40d14b3f9cf19f19b924e2ab4069b09588",
         "type": "github"
       },
```

### Notify maintainers

@FlorianFranzen @lovesegfault @minijackson @rodrgz @Synthetica9 @khaneliman

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❮ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.8.6-asahi, NixOS, 24.05 (Uakari), 24.05.20240505.25865a4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3pif36ks3f56py4wb1dkq6sh0nkf3ygj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zvolin** [comment]
I added overlay which takes waybar from master (`016b7291a3d85d14cfc907320b9c5829a68b8434`) and it works perfectly fine, so should I just close it and wait for new nixos-unstable?

**Comment by Shawn8901** [comment]
Possibly that commit then fixed it https://github.com/NixOS/nixpkgs/commit/a4deb172a4934762b6d2f7f52057d47cbf7720b4 . That bump was merged quite recently

You could double check if the master version is 0.10.3 on your end with the overlay.

Here is a link to track the build status of that pr http://nixpk.gs/pr-tracker.html?pr=309516

As there is no action left here (beside waiting), on could already close the issue on my personal opinion.

**Comment by zvolin** [comment]
so nixos-unstable already has this commit, however when I update and rebuild, I get the same error. Apparently on master everything works correctly. I'm not sure what may be the difference

**Comment by zvolin** [comment]
I found out what was causing the issue. It's indeed the nixos-apple-silicon which downgrades the wireplumber, the nixpkgs are okay https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/modules/sound/default.nix#L70
