### ISSUE TITLE
`nix-shell -p python39Packages.debugpy` fails

### ISSUE THREAD

**Issue by autra** [NixOS/nixpkgs#309603]
### Describe the bug

Trying to use `nix-shell -p python39Packages.debugpy`

### Steps To Reproduce

1. Execute `nix-shell -p python39Packages.debugpy`
2. the command exits with status 1 with the following error:

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/1ylv48nraiwhapyslv898sr6j8flvqia-nixos-23.11.6207.b2cf36f43f9e/nixos/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/1ylv48nraiwhapyslv898sr6j8flvqia-nixos-23.11.6207.b2cf36f43f9e/nixos/pkgs/stdenv/generic/make-derivation.nix:395:7:

          394|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          395|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          396|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Django-4.2.11 not supported for interpreter python3.9

```

### Expected behavior

A shell is opened. In this shell, ` python -c "import debugpy"` returns a 0 exit code, like it is with python3.10.

### Notify maintainers

ping @kira-bruneau 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.87, NixOS, 23.11 (Tapir), 23.11.20240424.dd37924`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
`python39Packages` aren't in the repo. You need to use `python310Packages` or `python311Packages`

**Comment by eclairevoyant** [comment]
> `python39Packages` aren't in the repo.

Seems to exist just fine.

```
$ nix build 'github:nixos/nixpkgs/nixos-23.11#python39Packages.python' --print-out-paths --no-link
/nix/store/kmcqrfim80saf8cyxscn6di9b89ll2lv-python3-3.9.19
```

Anyway, as the error says, 3.9 isn't supported for the package that throws said error, so you'll have to use a newer python. 3.9 is only getting security fixes anyway atm, so it's probably not suitable for normal use.

**Comment by natsukium** [comment]
We have the following package sets available, but as of 23.11, only the python310 and python311 package sets are actively maintained.
https://github.com/NixOS/nixpkgs/blob/23.11/doc/languages-frameworks/python.section.md#building-packages-and-applications-building-packages-and-applications

**Comment by autra** [comment]
My use case is to provide several dev shell  for a python lib I develop. That's why I care for python39 while it is not EOL. I *think* we need to use an older debugpy for python39. Does nixpkgs provides this kind of facility?

**Comment by natsukium** [comment]
It is impossible to maintain them on the main line due to lack of time, but if you submit a PR, I will be happy to review it.
