### ISSUE TITLE
Nginx ACME location seems incorrect when `serverName` is different then attribute name

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#309748]
### Describe the bug
If you have: 
```nix
services.nginx.virtualHosts.someName = {
    serverName = "someOtherName";
    forceSSL = true;
    enableACME = true;
}
```
During evaluation I get this error `error: attribute 'someName' missing`, pointing to the line 
```
356|         acmeLocation = optionalString ((vhost.enableACME || vhost.useACMEHost != null) && config.security.acme.certs.${acmeName}.dnsProvider == null)
   |                                                                                           ^
```

### Steps To Reproduce
As described above

### Additional context
I think this is because here
https://github.com/NixOS/nixpkgs/blob/9fb582619d1397a8cb64cfe28896a064fa1b33cb/nixos/modules/services/web-servers/nginx/default.nix#L1328-L1331
The pairs are made using the `serverName`, while here:
https://github.com/NixOS/nixpkgs/blob/9fb582619d1397a8cb64cfe28896a064fa1b33cb/nixos/modules/services/web-servers/nginx/default.nix#L353-L357
It is trying to use the vhostName.

So I think it should be
```nix
acmeName = if vhost.useACMEHost != null then vhost.useACMEHost else vhost.serverName;
```

Also, maybe this could be a problem as well, however I am not sure:
https://github.com/NixOS/nixpkgs/blob/9fb582619d1397a8cb64cfe28896a064fa1b33cb/nixos/modules/services/web-servers/nginx/default.nix#L414

I would submit a MR, but embarrassingly, I couldn't figure out how to test a patched nixpkgs lib in a flake without having my whole system rebuilt.

### Notify maintainers
@fpletz @ajs124 @raitobezarius

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fpletz** [comment]
Broken by #308303. Fixed by #310452.
