### ISSUE TITLE
Build failure: mongodb

### ISSUE THREAD

**Issue by angaz** [NixOS/nixpkgs#309769]
### Steps To Reproduce

1. build mongo-5_0

### Build log

```
trying https://fastdl.mongodb.org/src/mongodb-src-r5.0.24.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 403
error: cannot download mongodb-src-r5.0.24.tar.gz from any mirror
```

### Additional context

Curl and trying to download from the browser also fails. We should probably be using the GitHub tarballs anyway.

I have an override which seems to be working:
```nix
      mongodb-5_0 = final.mongodb-5_0.overrideAttrs ({
        src = final.fetchFromGitHub {
          owner = "mongodb";
          repo = "mongo";
          rev = "r5.0.24";
          hash = "sha256-SZ62OJD6L3aP6LsTswpuXaayqYbOaSQTgEmV89Si7Xc=";
        };

        sconsFlags = [
          "--release"
          "--ssl"
          #"--rocksdb" # Don't have this packaged yet
          "--wiredtiger=on"
          "--js-engine=mozjs"
          "--use-sasl-client"
          "--disable-warnings-as-errors"
          "VARIANT_DIR=nixos" # Needed so we don't produce argument lists that are too long for gcc / ld
          "MONGO_VERSION=5.0.24" # For some reason, scons can't figure out the version in the tarball from GH
        ];
      });

```

### Notify maintainers

@bluescreen303 @offline @f2k1de 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.0-rc4, NixOS, 24.05 (Uakari), 24.05.20240425.7bb2ccd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/370qy3d3wg9zhbn5a3dcv6k1q1iigfh4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fmckeogh** [comment]
@angaz Hi, I'm new to Nix/NixOS. How do you apply the override you supplied? Can it go in `configuration.nix`?

**Comment by f2k1de** [comment]
#309900

**Comment by angaz** [comment]
@fmckeogh, yeah, for sure you can. It goes in the `nixpkgs.overlays` section of the configuration.

Here's a sample:

```nix
nixpkgs.overlays = [
  (prev: final: {
    mongodb-5_0 = final.mongodb-5_0.overrideAttrs (old: {
      src = final.fetchFromGitHub {
        owner = "mongodb";
        repo = "mongo";
        rev = "r5.0.24";
        hash = "sha256-SZ62OJD6L3aP6LsTswpuXaayqYbOaSQTgEmV89Si7Xc=";
      };

      sconsFlags = old.sconsFlags ++ [ "MONGO_VERSION=5.0.24" ];
    });
  })
];
```

This takes the original package and replaces some of the attributes. `old` contains the previous package's attributes, so you can reference them in the new derivation of the package.

You can also give the package a new name if you wanted to, in case you still wanted to install the original version.

You can also create whole new packages in the overlays.

Check out the docs for more examples of what you can do: https://nixos.wiki/wiki/Overlays

**Comment by fmckeogh** [comment]
@angaz Thanks so much, that's really helpful!

**Comment by angaz** [comment]
Good luck on your Nix journey!

**Comment by qubitnano** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/309900

**Comment by Silver-Golden** [comment]
Thank ye so so much @angaz for that overlay    
Currently migrating from an old 4.2 server up along and since 4.4 is out of nixpkgs now *and* its also gone from fastdl I was tearing my hair out.
