### ISSUE TITLE
glibc executables are not the first output and are hard to find

### ISSUE THREAD

**Issue by ilya-kolpakov** [NixOS/nixpkgs#30984]
## Issue description

The output layout of `glibc` package contradicts the [section 4.4 of the manual](https://nixos.org/nixpkgs/manual/#idm140737318512832) which suggests that the executables provided by the package (such as `ldd` in case of `glibc`) should be accessible via the main package (e.g. `"${pkgs.glibc}/bin/ldd"`):

> By convention, the first output should contain the executable programs provided by the package as that output is used by Nix in string conversions, allowing references to binaries like ${pkgs.perl}/bin/perl to always work. 

In `glibc` package one has https://github.com/NixOS/nixpkgs/blob/a0b50eab599005127476e7b3b4ae8bd2d363091b/pkgs/development/libraries/glibc/common.nix#L123

so that `ldd` and the other executables are not in the main output
```
~/r/nixpkgs-fork> readlink -e (which ldd)
/nix/store/rk8jv9r9sjc1pz9lkbyj67cj3h0szzhy-glibc-2.25-49-bin/bin/ldd
```
and are somewhat non-trivial to find
```
nix-repl> "${pkgs.glibc}"
"/nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49"
nix-repl> "${pkgs.glibc.out}"
"/nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49"
nix-repl> "${pkgs.glibc.bin}"
"/nix/store/rk8jv9r9sjc1pz9lkbyj67cj3h0szzhy-glibc-2.25-49-bin"
nix-repl> "${pkgs.glibc.bin.out}"
"/nix/store/xzx1bv1d7z4mgg6sg6ly0jx609qvka4x-glibc-2.25-49"
```
especially because the layout contradicts the documentation.

@edolstra

**Comment by dezgeg** [comment]
Yes, glibc is the single exception to that policy, due to lots of existing code using something like:
````
patchelf --set-interpreter ${stdenv.glibc}/lib/ld-linux-x86-64.so.2 $out/bin/foo
````

So when the multiple outputs were added to glibc, the output with the libraries was made the first one to not silently break such packages. So yes, it's an unfortunate inconsistency but it's there for a trade-off.

**Comment by ilya-kolpakov** [comment]
Thanks @dezgeg. I created a PR #31320 that adds a brief description of this. This issue can be closed I guess.
