### ISSUE TITLE
Package request: lix

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#309915]
**Project description**

Lix is an implementation of Nix, a powerful package management system for Linux and other Unix systems that makes package management reliable and reproducible.

Read more about Lix at https://lix.systems/.

**Metadata**

* homepage URL: https://lix.systems
* source URL: https://git.lix.systems/lix-project/lix
* license: lgpl21+
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
https://git.lix.systems/lix-project/lix/src/branch/main/package.nix would be a good starting point for anyone attempting

**Comment by wegank** [comment]
Closed by #310194.
