### ISSUE TITLE
warp-terminal: crash when opening on wayland

### ISSUE THREAD

**Issue by hensou** [NixOS/nixpkgs#309938]
### Describe the bug
When I try to open the warp-terminal on wayland it crashes without opening any window and get the following logs:

```console
➜  ~ warp-terminal
/nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp: /nix/store/nwsbnbj4xgfq2x45df9xg2b77953h2zz-curl-8.7.1/lib/libcurl.so.4: no version information available (required by /nix/store/4xqjlfi0ffk57qb732fvbr5a0y1748pl-warp-terminal-0.2024.04.16.08.02.stable_00/opt/warpdotdev/warp-terminal/warp)
21:34:28 [INFO] Spawning terminal server process...
21:34:28 [INFO] Running app with windowing system: Wayland
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:164:14:
should be able to create event loop: Os(OsError { line: 80, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
21:34:28 [INFO] Received empty message; assuming the connection has been closed.
➜  ~
```

### Steps To Reproduce
1. try to open warp-terminal
2. nothing happens

### Expected behavior
It should open the warp-terminal window and prompt.

### Notify maintainers

@angustrau @Enzime @imadnyc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05pre621993.25865a40d14b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oliveirarleo** [comment]
Might be helpful: https://github.com/warpdotdev/Warp/issues/4840

**Comment by DontEatOreo** [comment]
Fixed in #308877, I tried running `warp-terminal` (`0.2024.04.30.08.02.stable_02`) on KDE Wayland and everything works as expected

```
❯ nix-shell -p nix-info --run "nix-info -m"               
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.25, NixOS, 24.05 (Uakari), 24.05.20240408.4cba8b5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by Atemu** [comment]
> ```
> 21:34:28 [INFO] Running app with windowing system: Wayland
> ```

Note that native wayland support is off by default. If you have applied an override, that is crucial information.

A warp-terminal dev has stated that wayland support is explicitly still experimental and off by default for this reason. https://github.com/NixOS/nixpkgs/pull/301944#issuecomment-2073494226

Please do not open issues concerning configurations that are explicitly unsupported by upstream.

**Comment by hensou** [comment]
Sorry, I didn't know it was **explicitly** unsupported by the upstream since **it was working before** just fine on Wayland. 

Thanks a lot anyway!
