### ISSUE TITLE
caddy fails to build on platform riscv64

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#310067]
### Describe the bug

Caddy fails to build for riscv64

```
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Building subPackage ./cmd/caddy
       > buildPhase completed in 41 seconds
       > Running phase: installPhase
       > /nix/store/75lnjrxbkj4s6mrd77lqnck64aik88sx-stdenv-linux/setup: line 119: /nix/store/gbvs2sikhr4rn6s5baxwy43y27vbq30s-caddy-riscv64-unknown-linux-gnu-2.7.6/bin/caddy: cannot execute binary file: Exec format error
       > /nix/store/75lnjrxbkj4s6mrd77lqnck64aik88sx-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
(please fill out more parts of the bug report template next time)

---

> caddy-riscv64-unknown-linux-gnu-2.7.6/bin/caddy: cannot execute binary file: Exec format error

https://github.com/NixOS/nixpkgs/blob/b211b392b8486ee79df6cdfb1157ad2133427a29/pkgs/servers/caddy/default.nix#L46-L52

Assuming this is `pkgsCross.riscv64.caddy`, likely an instance of #308283.

Pinging maintainers: @Br1ght0ne @emilylange @techknowlogick

**Comment by emilylange** [comment]
Hi, thanks for the ping @OPNA2608 :)

The fix for this is fairly trivial.
Either skip the shell completions/man pages[^1], or use something like

```diff
diff --git a/pkgs/servers/caddy/default.nix b/pkgs/servers/caddy/default.nix
index 399ce426d9dc..0045903d904b 100644
--- a/pkgs/servers/caddy/default.nix
+++ b/pkgs/servers/caddy/default.nix
@@ -5,6 +5,8 @@
 , caddy
 , testers
 , installShellFiles
+, buildPackages
+, stdenv
 }:
 let
   version = "2.7.6";
@@ -37,19 +39,19 @@ buildGoModule {
 
   nativeBuildInputs = [ installShellFiles ];
 
-  postInstall = ''
+  postInstall = let caddy = if stdenv.buildPlatform.canExecute stdenv.hostPlatform then placeholder "out" else buildPackages.caddy; in ''
     install -Dm644 ${dist}/init/caddy.service ${dist}/init/caddy-api.service -t $out/lib/systemd/system
 
     substituteInPlace $out/lib/systemd/system/caddy.service --replace "/usr/bin/caddy" "$out/bin/caddy"
     substituteInPlace $out/lib/systemd/system/caddy-api.service --replace "/usr/bin/caddy" "$out/bin/caddy"
 
-    $out/bin/caddy manpage --directory manpages
+    ${caddy}/bin/caddy manpage --directory manpages
     installManPage manpages/*
 
     installShellCompletion --cmd caddy \
-      --bash <($out/bin/caddy completion bash) \
-      --fish <($out/bin/caddy completion fish) \
-      --zsh <($out/bin/caddy completion zsh)
+      --bash <(${caddy}/bin/caddy completion bash) \
+      --fish <(${caddy}/bin/caddy completion fish) \
+      --zsh <(${caddy}/bin/caddy completion zsh)
   '';
 
   passthru.tests = {
```

But I am upset that you (@onny) didn't even care enough to do the bare minimum and fill out the issue template.

[^1]: Technically only the `$out/bin/caddy manpage` kills the build, not the `installShellCompletion`, because bash pipefail defaults.

**Comment by onny** [comment]
i'm sorry for the issue template, it was more of a quick note to myself. i'll do it right next time 👍
