### ISSUE TITLE
xserver logs to /dev/null no matter what

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#31008]
## Issue description
Seems like [logfile is hardcoded](https://github.com/NixOS/nixpkgs/blob/07bc859e9acec3cc6f7a8129e4b05a7584fef209/nixos/modules/services/x11/xserver.nix#L643), I have tried to change verbosity level (`verbose = 7;`) and it didnt help

### Steps to reproduce
[my config](https://github.com/BjornMelgaard/dotfiles/blob/nixos/nixos/root/configuration.nix#L154)

## Technical details

* System:  (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by disassembler** [comment]
Did you try checking the journal? `journalctl -e _COMM=Xorg`. I found fedora does the same thing writing to `/dev/null` and letting systemd pickup any errors: http://who-t.blogspot.de/2014/03/viewing-xorglog-with-journalctl.html

**Comment by primeos** [comment]
`journalctl -u display-manager.service` should work on NixOS.

**Comment by BjornMelgaard** [comment]
Thanks to all of you. If you saying that the logs to journalctl is the one I need, then the problem is solved. 
I was just a bit confused by [comment about logfile](https://github.com/NixOS/nixpkgs/blob/07bc859e9acec3cc6f7a8129e4b05a7584fef209/nixos/modules/services/x11/xserver.nix#L642) - `Log at the default verbosity level to stderr rather than /var/log/X.*.log.`, and then changing verbosity level didn't change anything
