### ISSUE TITLE
Package request: mingw-w64 Packages

### ISSUE THREAD

**Issue by python-coding-404** [NixOS/nixpkgs#310055]
Mingw-w64 allows us to cross compile to windows. 
 
Mingw-w64 is a fork of mingw made for compiling **64 bit**  and 32 bit applications for windows. It is used for cross compiling on linux and used as a c compiler in windows.
Mingw-w64 is a multitude of packages, _including libraries_!
**Metadata**

* homepage URL:  [mingw-w64.org](http://mingw-w64.org/)
* source URL: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/
* license: Public domain (headers), GNU General Public License (compiler and toolchain), Zope Public License

* platforms: Linux, Windows, and macOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
Don't we already have this?

https://github.com/NixOS/nixpkgs/blob/c5e1cf1c936259e31c91d68624c196e40d173046/lib/systems/examples.nix#L310-L321
https://github.com/NixOS/nixpkgs/blob/605cf9d8b00e662ea1e897b8d7cc7aa4003e0b5e/pkgs/os-specific/windows/mingw-w64/default.nix#L8-L17

I.e. `pkgsCross.mingwW64.hello` should cross-compile to 64-bit Windows via mingw-w64.

**Comment by python-coding-404** [comment]
ok
