### ISSUE TITLE
Celebrate !!

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#31001]
![screenshot](https://user-images.githubusercontent.com/3153638/32193090-717608a8-bdb6-11e7-99b0-9211d56ab67f.png)

It’s … magical!

**Comment by Profpatsch** [comment]
Double anniversary!
![screenshot](https://user-images.githubusercontent.com/3153638/32193155-a4c2ed98-bdb6-11e7-96ac-0d8c08defa7a.png)

**Comment by NeQuissimus** [comment]
🎉

**Comment by vcunat** [comment]
2000 is no anniversary.  Let's wait until 2048!

**Comment by dezgeg** [comment]
At 2048, do we celebrate by packaging every possible clone of the 2048 found on GitHub?

**Comment by 7c6f434c** [comment]
By _creating an issue_ to package every possible clone of 2048, including HTML5 one.

**Comment by BjornMelgaard** [comment]
I'm wondering, why not add [stale bot](https://github.com/probot/stale)?

**Comment by vcunat** [comment]
My opinion is that closing stale issues typically helps nothing.  (Depends on the type of issue.)

**Comment by BjornMelgaard** [comment]
I'm wondering why

**Comment by vcunat** [comment]
- Closing an issue might make it appear that it's fixed or that it doesn't apply anymore.
- Old open issues don't really obstruct anything, I believe, except that it might "look bad" that there are so many of them.
- Larger distros (like Debian) seem to be doing OK despite having loads of open issues.

**Comment by BjornMelgaard** [comment]
@vcunat debian can't be [statistically analyzed](http://isitmaintained.com/project/NixOS/nixpkgs)

**Comment by vcunat** [comment]
That's the "look bad" argument which I don't find strong enough, but I'm just a single person...

**Comment by BjornMelgaard** [comment]
@vcunat yes, this is what I meant

**Comment by edolstra** [comment]
There is something to be said for closing bug reports after N releases unless somebody confirms that the bug still exists. IIRC Fedora does that.

**Comment by globin** [comment]
Implementation idea for issues needing more information: https://github.com/mayflower/nixbot/issues/8
