### ISSUE TITLE
Explain how to fix problems in hackage-packages.nix

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#31014]
The comments in package-packages.nix only explain that it's an auto-generated file and only tell users to not edit the file, without giving any hints as to how to fix problems with it.  I suggest improving the comment documentation in this file especially for problems related to library name mappings from cabal to Nix, since there are likely a lot of holes.  See: https://github.com/NixOS/cabal2nix/pull/309

**Comment by ledettwy** [comment]
Oops, this should be filed against cabal2nix

**Comment by wizzup** [comment]
For those who came here looking for how `hackage-pacakges.nix` was generated (like me), go [here](https://github.com/NixOS/cabal2nix/blob/master/hackage2nix/README.md)

Correct me if I am wrong.
