### ISSUE TITLE
displayManager slim (and auto) not loading display-manager

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#31010]
## Issue description
no errors, just 3 attempts to load display-manager and fallback to system console, [very similar to this issue](https://nixos.org/nix-dev/2015-June/017493.html) (logs same)

I can provide logs if needed

### Steps to reproduce
[uncomment this, comment lightdm](https://github.com/BjornMelgaard/dotfiles/blob/nixos/nixos/root/configuration.nix#L192)

## Technical details

* System:  (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by prusnak** [comment]
SLIM is no longer in nixpkgs: ce26b3e
