### ISSUE TITLE
podman: Missing vfkit executable on Darwin

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [NixOS/nixpkgs#310146]
Recent podman versions (5 afaik) require the `vfkit` executable to be shipped along with the podman installation. It looks like the current package does not provide it.

Related :

- https://github.com/containers/podman/issues/21842
- https://github.com/NixOS/nixpkgs/blob/25865a40d14b3f9cf19f19b924e2ab4069b09588/pkgs/applications/virtualization/podman/default.nix#L123

**Comment by anthr76** [comment]
This is a duplicate of 

https://github.com/NixOS/nixpkgs/issues/305868
https://github.com/NixOS/nixpkgs/issues/306179
