### ISSUE TITLE
Package request: rustls-libssl

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#310173]
**Project description**

rustls-libssl is a partial reimplementation of the OpenSSL 3 libssl ABI. It is written in rust and uses rustls. It does not replace libcrypto: this is still required.

https://www.memorysafety.org/blog/rustls-nginx-compatibility-layer/

**Metadata**

* homepage URL: https://github.com/rustls/rustls-openssl-compat/tree/main/rustls-libssl
* source URL: https://github.com/rustls/rustls-openssl-compat/tree/main/rustls-libssl
* license: asl20
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MarkRijckenberg** [comment]
rusttls is performing much better than openssl in multi-threaded scenarios, with better scaling:   https://www.phoronix.com/news/Rustls-Multi-Threading-Perf
