### ISSUE TITLE
AWSCLI and botocore out of sync

### ISSUE THREAD

**Issue by ragingpastry** [NixOS/nixpkgs#310105]
### Describe the bug
The version of AWSCLI in master is 1.32.58. This version requires botocore==1.34.58, however the version of botocore in master is 1.34.87
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/botocore/default.nix#L17

AWSCli botocore pin: https://github.com/aws/aws-cli/blob/1.32.58/setup.py#L27

### Screenshots
```
> Checking runtime dependencies for awscli-1.32.58-py3-none-any.whl
       >   - botocore==1.34.58 not satisfied by version 1.34.87
```

### Additional context
This started happening after changing my `pkgs.nixVersion.unstable` to `pkgs.nixVersion.latest`

### Notify maintainers

@anthonyroussel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05.20240427.58a1abd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/801l7gvdz7yaibhjsxqx82sc7zkakjbq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
This should be fixed by #308355, which syncs botocore, awscli, and boto3.
