### ISSUE TITLE
BlackBox Terminal doesn't seems to support Sixel

### ISSUE THREAD

**Issue by linuxmobile** [NixOS/nixpkgs#310193]
### Describe the bug
The latest version of blackbox-terminal, from the [unstable branch](https://github.com/NixOS/nixpkgs/pull/309253). It does not have support for sixel, neither does the stable version terminal.

### Expected behavior
Open any image like nixos.six or similar.

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/10554636/c902f55d-b616-483f-a553-10d11a42d0eb)

### Additional context
I searched if there were any similar problems, and although I found other issues, none concerning the problem itself.

### Notify maintainers
@chuangzhu @linsui 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240507.b211b39`
 - multi-user?: `yes`

 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/f0ssy3p6898x9k880l23mhd0fl6rvrb2-source`
```

---

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
If you don't enable sixelSupport, it's not supported.

**Comment by eclairevoyant** [comment]
https://www.arewesixelyet.com/#black-box

Basically Blackbox [uses GNOME VTE](https://gitlab.gnome.org/raggesilver/blackbox/-/wikis/FAQ#will-black-box-ever-support-font-ligatures-or-custom-escape-sequences) and [VTE doesn't support it](https://gitlab.gnome.org/GNOME/vte/-/issues/253). That's not really a bug, just a missing feature, and you'll have to follow upstream.

**Comment by eclairevoyant** [comment]
Apologies, seems I was incorrect about the current status,
VTE can be built [with sixel support](https://github.com/GNOME/vte/blob/f9ca107adf18b58fecb30db662f9b94335676788/meson_options.txt#L96) and blackbox will pick it up. And it appears to be enabled in the current expression:
https://github.com/NixOS/nixpkgs/blob/1b8f21cb6152b964662fd5c79b54b3b52eb00368/pkgs/applications/terminal-emulators/blackbox-terminal/default.nix#L80

**Comment by linsui** [comment]
It's not enabled by default. https://github.com/NixOS/nixpkgs/blob/1b8f21cb6152b964662fd5c79b54b3b52eb00368/pkgs/applications/terminal-emulators/blackbox-terminal/default.nix#L23

**Comment by linuxmobile** [comment]
Hi guys, I see you have reopened the issue. I understand that **by default it is disabled**, that's exactly what I wanted to mention yesterday, when I opened the issue. _Sorry if I opened the issue and mislabeled it_, that was my mistake for sure! I want to know if you/I can enable sixel from the configuration or at least understand why it is disabled?

I also understand that it is not yet supported, as mentioned. However in the Blackbox repository tracking you see that some users enabled it, and it was working.

**Comment by chuangzhu** [comment]
In the place where you use `blackbox-terminal`, presumably `environment.systemPackages`, change `blackbox-terminal` to `(blackbox-terminal.override { sixelSupport = true; })`. Check https://nixos.org/manual/nixpkgs/stable/#chap-overrides for more examples

**Comment by linuxmobile** [comment]
> (blackbox-terminal.override { sixelSupport = true; })

This work, thx u <3
