### ISSUE TITLE
Package request: Gnome Extension - OpenWeather Refined

### ISSUE THREAD

**Issue by andrewmartin5** [NixOS/nixpkgs#310277]
**Project description**

Display weather for the current or a specified location. Fork of OpenWeather. Needed as open weather isn't supported on Gnome 46.

**Metadata**

* homepage URL: https://extensions.gnome.org/extension/6655/openweather/
* source URL: https://github.com/penguin-teal/gnome-openweather
* license: GPL-3.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
This is already available under `gnomeExtensions.openweather`: https://search.nixos.org/packages?show=gnomeExtensions.openweather

**Comment by honnip** [comment]
As the both extensions have the different shell versions, it is not added in collisions.json

I think only extensions for the current shell version should go to `gnomeExtensions`..
