### ISSUE TITLE
tvheadend missing bzip2 dependency

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#31021]
## Issue description

I see the following error in tvheadend logs:
```
tvheadend[12399]: spawn: /bin/sh: bzip2: command not found
tvheadend[12399]: spawn: /nix/store/zcscqvgya0582mp7nvkvc97l6invhm8c-gnutar-1.29/bin/tar: /var/lib/tvheadend/.hts/tvheadend/backup/unknown.tar.bz2: Cannot write: Broken pipe
```

It also says:
```
tvheadend[12399]: config: please, do not report this as an error, you may use --nobackup option
```

But I thought it might be better to support the backup by default. Perhaps `bzip2` should be added to `propagatedBuildInputs` of tvheadend derivation?

### Steps to reproduce

Enable tvheadend services, that is, set `services.tvheadend.enable = true;` in `configuration.nix`. See logs with `journalctl -u tvheadend`. 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
17.09.1880.ac2bb5684c (Hummingbird)
```

* Nix version: (run `nix-env --version`)
```
# nix-env --version
nix-env (Nix) 1.11.15
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

(This didn't work properly, I guess I have some weird setting in nix paths..)

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
```
# grep build-use-sandbox /etc/nix/nix.conf
build-use-sandbox = true
```

**Comment by peterhoeg** [comment]
Couple of things:

1. The easiest way to get the technical details is to use the ```nix-info``` script that is now part of the standard install.
2. The version detection was wrong in the past, so tvheadend thought it was ```0.0.0~unknown```.
3. ```propagatedBuildInputs``` is not the right solution but wrapping the binary is.

Fixed in af0c3fca1de900de881f19a1fae3806ea34427cc.
