### ISSUE TITLE
Update request: Netbox 3.7.4 → 4.0

### ISSUE THREAD

**Issue by Xyz00777** [NixOS/nixpkgs#310219]
- Package name: Netbox
- Latest released version: 3.7.3
- Current version on the unstable channel: 3.7.4
- Current version on the stable/release channel: 3.6.9
- [ X ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
  - there is an pull request for netbox 3.7.8 but not 4.0.0 https://github.com/NixOS/nixpkgs/pull/309483

**Notify maintainers**

@minijackson @n0emis @raitobezarius

**Comment by minijackson** [comment]
Hey, I've seen this upgrade, but I think it' be best to wait until after NixOS' 24.05 branch-off, so that users don't have to upgrade through 2 breaking versions at once. The branch-off should happen on 2024-05-22

**Comment by KiruyaMomochi** [comment]
With with some (hacky) overlays I have managed to make netbox 4.0 run. Basically, here are the changes I made.

Django 5 and `pytz`
* I'm overriding django to django 5.0 globally, as I'm trying to use GeneratedField. This further requires the following changes
  * `django-filter`: Add `pytz` to `nativeCheckInputs`.
  * `django-timezone-field`: Remove `pytz` from `propagatedBuildInputs`.
  * `djangorestframework`: Remove `pytz` from `.propagatedBuildInputs`. Add `inflection` to `nativeCheckInputs`.

Updated packages
  * `django-mptt`: Updated to `0.16`, use `hatchling` build system and add `model-bakery`.
  * `strawberry-graphql`
  * `asgiref`

New packages
  * `django-htmx`
  * `django-choices-field`
  * `strawberry-graphql-django`

Netbox itrself
  * Add `strawberry-graphql-django`, `django-htmx` and `nh3`.

Not sure if I have enough time to contribute all of them, but if possible I will give it a try.

**Comment by xanderio** [comment]
Maybe we can get this ball rolling again :)

**Comment by minijackson** [comment]
Sooo, this is indeed going to be a big one. I've managed to get the NetBox test to be successful locally. Here's what needs to be done in nixpkgs:

- [ ] Separate PR for upgrading `asgiref` from 3.7.2 -> 3.8.1, as it has a number of dependents
- [ ] Separate PR for upgrading NetBox that basically does what @KiruyaMomochi explained (thanks!)

In my local branch, I have also moved NetBox to `pkgs/by-name`, and removed the part of the patch that allowed configuring UNIX sockets for Redis, since it was upstreamed, so if you don't mid I'll open those 2 PRs soon™.

**Comment by xanderio** [comment]
Thanks @minijackson! I was just about to start working on this myself :D If you want you can ping me on the PRs (I can only review then)

**Comment by minijackson** [comment]
Done in #331750!

**Comment by felbinger** [comment]
I'm using the new package and experience some problems. I'm not sure if this is an issue in my own setup. I can't set relations on objects e.g. a site for a device, does this work for you?
