### ISSUE TITLE
Vivaldi fails to render webpage in Wayland

### ISSUE THREAD

**Issue by Aman9das** [NixOS/nixpkgs#310265]
### Describe the bug
Vivaldi opens but its window is completely blac blank.

### Steps To Reproduce
1. update to Vivaldi v6.7
2. switch to wayland based desktop environment (tested on cinnamon Wayland and hyprland)
3. Vivaldi window opens but fails to render webpage.

### Expected behavior
Vivaldi should render properly like 6.6 version

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/39594914/fe521fe9-ccaa-4196-acca-77377cb4d33b)

### Additional context
There's no 6.7 release specific traceback 

### Notify maintainers
@otwieracz
@badmutex

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240505.25865a4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3pif36ks3f56py4wb1dkq6sh0nkf3ygj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
According to https://vivaldi.com/blog/desktop/minor-update-three-6-7/ it's somewhere between 124.0.6367.90 and 124.0.6367.166, so probably this issue: #306010.
Anything below 124.0.6367.118 has the broken handling.

Basically this will probably be fixed on the next update.

**Comment by Aman9das** [comment]
Thanks! closing the issue then. this caused lots of worry and as a plus i learnt to pin old packages :)
