### ISSUE TITLE
Some packages still refer to the old npm2nix generated package set

### ISSUE THREAD

**Issue by svanderburg** [NixOS/nixpkgs#31032]
In principle, we use `node2nix` for all our generated NPM packages. However, the old NPM package set generated by `npm2nix` still resides in the `top-level` directory (`pkgs/top-level/node-packages.json`).

We should get rid of this old package set, but there are still a bunch of external packages referring to it. I made an investigation and these are the affected packages:

- [x] applications/editors/zed
- [x] applications/networking/irc/shout
- [x] applications/networking/irc/quassel-webserver
- [x] applications/audio/groovebasin
- [x] tools/networking/statsd
- [x] tools/networking/airfield
- [x] servers/dnschain
- [x] development/compilers/ghcjs

I currently don't know if these packages are still maintained or in use. With the exception of `ghcjs`, all of them are NPM packages. So ideally, they should be added to the package set in the `pkgs/development/node-packages` folder.

The impact of `ghcjs` is unknown to me. By studying the Nix expression I noticed that it has a dependency on the "socket.io" NPM package. I could easily replace this dependency by a `node2nix` version, but I cannot really validate it.

**Comment by svanderburg** [comment]
ping @matejc @benley @andrewrk @offlinehacker @rnhmjoj @jwiegley @cstrahan @dmjio

**Comment by rnhmjoj** [comment]
`dnschain` is wrapped because it needs openssl at runtime.
I don't know if npm2nix can take care of this when generating the expression.

**Comment by svanderburg** [comment]
@rnhmjoj node2nix has an overriding mechanism that can be used to provide openssl as an additional dependency. I can show you how to do it.

**Comment by rnhmjoj** [comment]
[this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/default-v6.nix) expression, right?

**Comment by svanderburg** [comment]
@rnhmjoj Yes, that's correct

**Comment by svanderburg** [comment]
@pikajude Git blame reveals that you added socket.io to the passthru of ghcjs. Could you clarify what its purpose is? By grepping over the Nixpkgs, I could not find any references to it.

**Comment by pikajude** [comment]
When I made that commit, ghcjs --interactive needed socket.io to run the REPL. If it doesn't now it can be removed. I'll test it out when I can.

**Comment by andrewrk** [comment]
You can remove `groovebasin`. It's still a good project but has been bit rotting a bit and probably needs to be repackaged.

**Comment by pikajude** [comment]
It still needs socket.io to run a browser session, which IIRC I've found useful in the past. The way I added socket.io to ghcjs environments is a complete mess and needs to be improved, though. What's the right way to include node packages?

**Comment by svanderburg** [comment]
@pikajude I made a commit in my own personal Nixpkgs fork: https://github.com/svanderburg/nixpkgs/commit/fc461301362828199d4d17c6e491d0735b14c7e9

I just realized that I (by accident) implemented this commit on top of a very old master revision, so I probably need to redo it.

Anyway, replicating the changes is quite simple:

* add socket.io to `pkgs/development/node-packages/node-packages-v6.json`
* regenerate the Nix expressions: `node2nix -6 -i node-packages-v6.json -o node-packages-v6.nix -c composition-v6.nix`
* update the `ghcjsNodePkgs` function parameter (as can be seen in my commit)

Then I think it should work, but this requires some validation from you.

**Comment by svanderburg** [comment]
@pikajude I just rebased my change in my ghcjs-socketio branch onto the current master. The only thing you need to do is validate it. )

**Comment by pikajude** [comment]
@svanderburg I didn't actually come back to this message thread before making my change :/ I've made the fix in a branch of my own, as well as another fix that I thought needed to be done (see https://github.com/NixOS/nixpkgs/pull/31062) Thanks for the help though!

**Comment by svanderburg** [comment]
@andrewrk I just removed the groovebasin package, but feel free to add it to the new node2nix package set if you need it again. If you run into problems, please ask.

**Comment by svanderburg** [comment]
@garbas @bjornfor By checking the history of the statsd NixOS module, it seems that you two know more about statsd

**Comment by domenkozar** [comment]
@svanderburg anything else to do?

**Comment by Ma27** [comment]
I don't think so, I killed the NPM set generated by npm2nix, so this could be closed:)

**Comment by svanderburg** [comment]
Yes it is done
