### ISSUE TITLE
python3.9 cannot be installed system wide

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#310302]
### Describe the bug

adding python39 in environment.systemPackages makes nixos-rebuild fail, because python39.doc fails to build and `documentation.doc.enable` defaults to `true`.

### Steps To Reproduce
1. add `python39` to environment.systemPackages
2. nixos-rebuild

### Expected behavior
no build failure

### Additional context
can also be reproduced as nix-build -A python39.doc
A regression introduced in https://github.com/NixOS/nixpkgs/pull/230533

### Notify maintainers

cc @KAction @FRidh  involved in the creation of the build output https://github.com/NixOS/nixpkgs/pull/230533 

### Metadata
reproduced on 27c13997bf450a01219899f5a83bd6ffbfc70d3c (23.11) and 2f181d6f062e6bd0b794e7978a1ec56188be95bb (the commit introducing this doc output)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
* python doesn't go in systemPackages anyway
* `python39.doc` builds just fine on `master`

**Comment by symphorien** [comment]
> python doesn't go in systemPackages anyway, this is why we have mkShell and/or actual python builders in the first place

that seems a bit extreme. I use python as a calculator, and I want it on path.

> python39.doc builds just fine on master

can we get a backport of the fix then?

**Comment by FliegendeWurst** [comment]
Too late for a 23.11 backport now
