### ISSUE TITLE
Packaging request: kodiPlugins.covenant

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#31049]
This issue is just a placeholder for this kodi plugin packaging request: replace Exodus with Covenant.

**Comment by jluttine** [comment]
I suppose this is the official repository: https://github.com/Colossal1/plugin.video.covenant

**Comment by aanderse** [comment]
@jluttine still looking for this, or can the issue be closed?

**Comment by jluttine** [comment]
I think it would be nice, but not that important. I guess the repo has moved here: https://github.com/covenantkodi/plugin.video.covenant. But yeah, I'll close this.
