### ISSUE TITLE
Include Tensorflow C++ Artifacts

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#31046]
Now that we build Tensorflow from source it would be nice to package up the C++ headers and shared objects as well. These are built from the `//tensorflow:libtensorflow_cc.so` Bazel target.

@abbradar since the current derivation is Python-centric I'm curious how you think we should proceed. Do you think these artifacts should come from a separate derivation with the common bits factored out?

**Comment by abbradar** [comment]
Ideally we would want to build C++ parts of Tensorflow separately, and then make its Python parts link to them. I imagine it would be one hell of a task however, given Bazel. Either way, most of the derivations code should be shared.

I don't have time to do this soon but hope I can return to this later (or maybe someone else wants to try? :3)

**Comment by CMCDragonkai** [comment]
Just a question, does this mean tensorflow will now be built according to the machine architecture? I was hoping to make use of all the vectorised instructions that is supported by my GPU.

**Comment by abbradar** [comment]
It already is! See https://github.com/NixOS/nixpkgs/pull/30786/commits/824cfbb0a27caf56d0f696ada171f306da59558e

**Comment by CMCDragonkai** [comment]
That doesn't do automatic detection of features, I would need to set those options myself. Was there no way for the compilation to automatically detect the best feature set to use?

Also that's great if I could get it even work. https://github.com/NixOS/nixpkgs/issues/31027

**Comment by TravisWhitaker** [comment]
@CMCDragonkai All you have to do to get the best TF for your GPU is override the `cudaCapabilities` passed to the TF derivation. That captures all of the GPU-specific stuff.

**Comment by CMCDragonkai** [comment]
What does that 3.5 and 5.2 mean?

**Comment by abbradar** [comment]
@CMCDragonkai detecting that during the compilation is impure, we specifically don't want that.

I'll check out your problems with CUDA version; it's strange because it worked for me and we made no serious changes since.

**Comment by abbradar** [comment]
@CMCDragonkai 3.5 and 5.2 are CUDA capability versions. You can find out what's your highest supported version [here](https://developer.nvidia.com/cuda-gpus). Generally "more is better".

**Comment by TravisWhitaker** [comment]
@jyp Thanks for pointing that out; I hadn't noticed it.

The existing libtensorflow derivation isn't great, though. It just grabs upstream's binary, and TF has loads of build-time options. I suppose that's separate from this issue.

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/pull/63208
Closing
