### ISSUE TITLE
Update request: sqlpage 0.15 → 0.20.5

### ISSUE THREAD

**Issue by lovasoa** [NixOS/nixpkgs#310436]
- Package name: sqlpage
- Latest released version: 0.20.5

- Current version on the unstable channel: 0.15.1
- Current version on the stable/release channel: 0.20.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dit7ya 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Can you fix the title?

**Comment by lovasoa** [comment]
done, sorry!

**Comment by hervyqa** [comment]
now sqlpage-v0.21.0. @dit7ya

**Comment by lovasoa** [comment]
The latest changes to the main branch of SQLPage should make the nix build process easier, since the build script now accepts pre-downloaded static assets: https://github.com/lovasoa/SQLpage/commit/7ea57559fd39d404eff59091a5bc2f14c8f327f7

Let me know if this helps.

**Comment by lovasoa** [comment]
We can now just place the artefacts in `target/sqlpage_artefacts` before compilation, and the build script picks them up:

```
❯ ll target/sqlpage_artefacts/
-rw-rw-r-- 1 olojkine olojkine 522K Jun 27 17:11 https___cdn.jsdelivr.net_npm_apexcharts_3.49.1_dist_apexcharts.min.js
-rw-rw-r-- 1 olojkine olojkine  19K Jun 27 17:11 https___cdn.jsdelivr.net_npm_list.js-fixed_2.3.4_dist_list.min.js
-rw-rw-r-- 1 olojkine olojkine 536K Jun 27 17:11 https___cdn.jsdelivr.net_npm__tabler_core_1.0.0-beta20_dist_css_tabler.min.css
-rw-rw-r-- 1 olojkine olojkine  30K Jun 27 17:11 https___cdn.jsdelivr.net_npm__tabler_core_1.0.0-beta20_dist_css_tabler-vendors.min.css
-rw-rw-r-- 1 olojkine olojkine 134K Jun 27 17:11 https___cdn.jsdelivr.net_npm__tabler_core_1.0.0-beta20_dist_js_tabler.min.js
-rw-rw-r-- 1 olojkine olojkine 2.3M Jun 27 17:11 https___cdn.jsdelivr.net_npm__tabler_icons-sprite_3.4.0_dist_tabler-sprite.svg
-rw-rw-r-- 1 olojkine olojkine  43K Jun 27 17:11 https___cdn.jsdelivr.net_npm_tom-select_2.3.1_dist_js_tom-select.popular.min.js
```

This should make it easier to simplify https://github.com/MikaelFangel/nixpkgs-upstream/blob/master/pkgs/servers/sqlpage/default.nix#L54-L76

The latest SQLPage is now [v0.24.0](https://github.com/lovasoa/SQLpage/releases/tag/v0.24.0)

**Comment by t4ccer** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/318678
