### ISSUE TITLE
Package request: music-assistant

### ISSUE THREAD

**Issue by diogotcorreia** [NixOS/nixpkgs#310509]
**Project description**

Music Assistant is a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers. The server is the beating heart, the core of Music Assistant and must run on an always-on device like a Raspberry Pi, a NAS or an Intel NUC or alike.

https://www.home-assistant.io/blog/2024/05/09/music-assistant-2/

**Metadata**

* homepage URL: https://music-assistant.io/
* source URL: https://github.com/music-assistant/server/
* license: Apache-2.0
* platforms: Linux (not sure if darwin is supported)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/311927
