### ISSUE TITLE
Package request: gnomeExtensions.trayIconsReloaded

### ISSUE THREAD

**Issue by felbinger** [NixOS/nixpkgs#310539]
**Project description**

`trayIconsReloaded@selfmade.pl` is a tray extension for gnome 45.

**Metadata**

* homepage URL: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
* source URL: https://github.com/MartinPL/Tray-Icons-Reloaded
* license: GPL3
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zendo** [comment]
[nixpkgs.dev/gnomeExtensions.tray-icons-reloaded](url)
