### ISSUE TITLE
Default firewall drops Chromecast packets

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#3107]
See http://askubuntu.com/a/326224/177448 , basically chromecast needs multicast udp packets allowed in from the local network.

The rule being proposed is `iptables -I INPUT -p udp -m udp --dport 32768:61000 -j ACCEPT` but that doesn't limit to local network. A smarter rule would be nice but with mobile devices the network can change without the firewall rules changing and there doesn't seem to be a way to ask iptables to allow only from local networks.

**Comment by condemoreloer** [comment]
https://marketplace.firefox.com/search?q=http%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dhttps%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2Fx%2Fyhf4qphl8r7w-%2F%253F%2526at%253DAF6bupMcAr6GGyW2owj6xKfGItrq-wS2CA%2526t%253D14c82c5f192b955c%2526a%253Darch#lightbox

**Comment by wmertens** [comment]
Closing since this is not really something that can be solved generally by NixOS

**Comment by ThomasMader** [comment]
The port range 32768:61000 doesn't work for me anymore.
The following works though: 

       iptables -I INPUT -p udp -m udp -s 192.168.0.0/16 --match multiport --dports 1900,5353 -j ACCEPT 

The ports are listed here: https://productforums.google.com/d/msg/chromecast/G3E2ENn-YZI/s7Xoz6ICCwAJ
