### ISSUE TITLE
Package request: rad-web, radicle-httpd

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#310762]
**Project description**

- Daemon of radicle's frontend(radicle-httpd)
- Program that login to radicle's frontend(rad-web)

**Metadata**

* homepage URL: https://radicle.xyz
* source URL: https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5
* license: mit, apache 2.0
* platforms: linux, darwin(unix-based operating system supported)

---

https://github.com/NixOS/nixpkgs/pull/309050 added radicle-node, but it doesnt have rad-web, radicle-httpd.
note: [pull request author's comment about it](https://github.com/NixOS/nixpkgs/pull/309050#issuecomment-2094888831)

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gador** [comment]
#314440 should add `radicle-httpd`

**Comment by lorenzleutgeb** [comment]
https://github.com/NixOS/nixpkgs/pull/321580 added `radicle-httpd`.
