### ISSUE TITLE
Update request: nut 2.8.0 → 2.8.2

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#310868]
- Package name: nixpkgs.nut
- Latest released version: 2.8.2

- Current version on the unstable channel: 2.8.0
- Current version on the stable/release channel: 2.8.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@nbp 

NUT version 2.8.0 contains a critical bug: If the UPS autonomously switches to calibration mode, then NUT never updates its state once calibration is done. This means it will never take any action on loss of power, i.e. the UPS will run out its battery, likely damaging the hardware.

This was reported as https://github.com/networkupstools/nut/issues/2168, and is fixed in 2.8.2.

I believe this should be backported to stable.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
I am having this error, @nbp or anyone wanna take a look?

```log
        > Makefile.am: installing './INSTALL'
       > Makefile.am: error: required file './NEWS' not found
       > Makefile.am: error: required file './README' not found
       > clients/Makefile.am: installing './depcomp'
       > configure.ac:4981: error: required file 'scripts/augeas/nutupsconf.aug.in' not found
       > configure.ac:4981: error: required file 'scripts/devd/nut-usb.conf.in' not found
       > configure.ac:4873: error: required file 'scripts/systemd/nut-common-tmpfiles.conf.in' not found
       > configure.ac:4981: error: required file 'scripts/udev/nut-usbups.rules.in' not found
       > parallel-tests: installing './test-driver'
       > autoreconf: error: automake failed with exit status: 1
```

**Comment by PedroHLC** [comment]
All these overrides fixed the bump for me: https://github.com/chaotic-cx/nyx/blob/b126c4b34775b9717a4076489617ef7d53f53ea9/pkgs/nut-git/default.nix#L16-L44

Can use my UPS now that uses the `sms_ser` which became available in 2.8.1.

**Comment by bjornfor** [comment]
> NUT version 2.8.0 contains a critical bug: If the UPS autonomously switches to calibration mode, then NUT never updates its state once calibration is done. This means it will never take any action on loss of power, i.e. the UPS will run out its battery, likely damaging the hardware.

Should we backport https://github.com/NixOS/nixpkgs/pull/334807 ("nut: 2.8.0 -> 2.8.2") to NixOS 24.05?

**Comment by PedroHLC** [comment]
Yes, everything that does not have a breakage of NixOS' modules usage, or breakage of the apps' own configurations/usage can be backported. Feel free to add the label for the bot to do its magic.
