### ISSUE TITLE
Polkit not responding in GNOME

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#310805]
### Describe the bug

I am unable to perform privileged operations like mounting a drive. There is no Authorization required dialogue.

Additionally, several times per second I see the following in the journal:

```
.gnome-shell-wr[3391]: Unknown line 'loading "libpcsclite_real.so.1" failed: libpcsclite_real.so.1: cannot open shared object file: No such file or directory' from helper
```

### Steps To Reproduce
1. Log in to GNOME Shell session.
2. Try to open an external drive in Nautilus.

### Expected behavior

Authorization required dialogue should pop up.

### Additional context

<del>Looks like this might be a polkit issue:

```
$ sudo $(nix-build -A polkit)/lib/polkit-1/polkit-agent-helper-1
loading "libpcsclite_real.so.1" failed: libpcsclite_real.so.1: cannot open shared object file: No such file or directory
```

</del>

Actually, I am getting the error from `sudo`, polkit-agent did not even run yet:

```ShellSession
$ sudo echo
loading "libpcsclite_real.so.1" failed: libpcsclite_real.so.1: cannot open shared object file: No such file or directory
[sudo] password for jtojnar: 
```

### Notify maintainers
@NixOS/freedesktop 

### Metadata

Using f1010e0469db743d14519a1efd37e23f8513d714 (nixos-unstable)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Actually, I am getting the error from `sudo`, polkit-agent did not even run yet:

```ShellSession
$ sudo echo
loading "libpcsclite_real.so.1" failed: libpcsclite_real.so.1: cannot open shared object file: No such file or directory
[sudo] password for jtojnar: 
```

**Comment by bobby285271** [comment]
- Any chance this is related to https://github.com/NixOS/nixpkgs/issues/309158#issuecomment-2094768200 ?

**Comment by jtojnar** [comment]
Yes, that sounds like the same issue. GitHub search failed me again.

Duplicate of #309158

**Comment by jtojnar** [comment]
For me the issue was triggered because I use u2f token. I can apply the PR changes without mass rebuild by just patching `pcsclite` used by `libfido` used by `pam_u2f`: https://github.com/jtojnar/nixfiles/commit/7181d7698b169826f57f4daad9ebf2f91525eb20

**Comment by Lyndeno** [comment]
One thing I noticed is the password prompt shows up if you lock and unlock, but then the whole session is unresponsive to clicking.
