### ISSUE TITLE
Package request: streamrip

### ISSUE THREAD

**Issue by KultaPossu** [NixOS/nixpkgs#310852]
**Project description**

A scriptable stream downloader for Qobuz, Tidal, Deezer and SoundCloud.

**Metadata**

* homepage URL:
* source URL: https://github.com/nathom/streamrip
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Luk45135** [comment]
I already made a package request at #305034
and there is a open pull request for streamrip here #280725

**Comment by KultaPossu** [comment]
Closing as duplicate
