### ISSUE TITLE
Can't match case insensitive with `builtins.match`

### ISSUE THREAD

**Issue by Libadoxon** [NixOS/nixpkgs#310906]
### Describe the bug
You can't match case insensitive with `builtins.match`, I think nix uses ECMAScript regex which doesn't support pearl extensions like `(?i)`. In c++ you can pass additional arguments to `std::regex pattern()` to make it match case insensitive, for example:
```c++
std::regex pattern("Some Pattern", std::regex_constants::icase);
```
But to my knowledge you can't pass anything to `builtins.match` except for the pattern/expression

**Comment by eclairevoyant** [comment]
This is the repo for nixpkgs and nixos, i.e. the packages repository as well as the distro.
Feature requests for nix should be filed under https://github.com/NixOS/nix

**Comment by Libadoxon** [comment]
thx, will open the issue there
