### ISSUE TITLE
firefox is pretty old

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#31092]
## Issue description
nix gives me firefox nightly 56.0.1 (64-bit).
shouldn't that be updated from time to time?

## Technical details

* System: 17.09.1919.6698e68aee (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1919.6698e68aee"
* Sandboxing enabled: build-use-sandbox = false

**Comment by danbst** [comment]
personally I've switched to firefox overlay, which handles updates nicely

**Comment by danbst** [comment]
https://github.com/mozilla/nixpkgs-mozilla/blob/master/firefox-overlay.nix

**Comment by edolstra** [comment]
The 17.09 channel has 56.0.2, which is the most recent version.

**Comment by castilma** [comment]
56.0.2 is the most recent stable release, but nightly is at 58.0a1.
https://www.mozilla.org/en-US/firefox/58.0a1/releasenotes/

the version I installed tells me it is nightly.
is nightly 56.0.2 == stable 56.0.2?
why does it tell me it is nightly, if it is actually stable?

**Comment by globin** [comment]
We are not allowed to use the official firefox branding, which is why it is called the default "nightly"

**Comment by danbst** [comment]
@castilma According to wiki, Mozilla is developing Firefox 58 now, but going to release Firefox 57 (Quantum) in about 2 weeks. So currently 56 version is latest stable

https://wiki.mozilla.org/RapidRelease/Calendar

As for bleeding-edge releases, I still recommend using dedicated overlay

**Comment by castilma** [comment]
@danbst I'm fine with stable but could you give me a hint, how one uses your posted overlay?

**Comment by danbst** [comment]
@castilma 
```
mkdir -p ~/.config/nixpkgs/overlays/
curl -L https://raw.githubusercontent.com/mozilla/nixpkgs-mozilla/master/firefox-overlay.nix > ~/.config/nixpkgs/overlays/firefox-overlay.nix
nix-env -iA nixos.latest.firefox-nightly-bin
```
