### ISSUE TITLE
Package request: tabby

### ISSUE THREAD

**Issue by Kamchatskiy** [NixOS/nixpkgs#310937]
**Project description**

 A terminal for a more modern age 

**Metadata**

* homepage URL: https://github.com/Eugeny/tabby
* source URL: https://github.com/Eugeny/tabby
* license: mit
* platforms: unix, linux, windows

**Comment by qwqawawow** [comment]
See also https://github.com/NixOS/nixpkgs/pull/303924

**Comment by gepbird** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/233509
