### ISSUE TITLE
Asymptote runtime problem in "three" module

### ISSUE THREAD

**Issue by bugaev** [NixOS/nixpkgs#31097]
## Issue description
Processing source files with Asymptote causes the following error message:
`/nix/store/glmsg7w2vviw30868cca6m1cdymvxh3l-asymptote-2.41/share/asymptote/three.asy: 2905.13: runtime:`
There is nothing after the colon in 

> 'runtime:'

The error condition is triggered by `draw((0,0,0)--(2,0,0), blue);` statement in the full listing of the input source file 'test.asy':

    import three;
    size(4cm,0);
    draw((0,0,0)--(2,0,0), blue);

### Steps to reproduce
    > su -
    nix-env -iA nixos.asymptote
    > exit
    asy test.asy

## Technical details

* System: 17.09pre113138.96457d26dd (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 18.03pre118631.66b63d2f5a
* Sandboxing enabled: no

## Additional info
* Asymptote works as expected on NixOS 16.09.

**Comment by yegortimoshenko** [comment]
Can't reproduce: [test.eps.gz](https://github.com/NixOS/nixpkgs/files/1435003/test.eps.gz)

* System: 18.03pre118631.66b63d2f5a (Impala)
* Nix version: 1.11.15
* Nixpkgs version: e2edccae47dc4972ec16bdeb6eb5374f7631fea8
* Sandboxing enabled: yes

**Comment by 7c6f434c** [comment]
…but you install asymptote form NixOS channel anyway, so Nixpkgs version
shouldn't matter.

(and I could not reproduce the issue as reported with exact same store
path for `asymptote`)

Maybe run `asy -vvvv test.asy` and post the output?

**Comment by bugaev** [comment]
@7c6f434c:

### asy -vvvv test.asy 1> test-std.log
[test-std.log](https://github.com/NixOS/nixpkgs/files/1435059/test-std.log)

### asy -vvvv test.asy 2> test-err.log
[test-err.log](https://github.com/NixOS/nixpkgs/files/1435061/test-err.log)

**Comment by 7c6f434c** [comment]
Hm. Maybe it runs out of memory? Could you try it inside `nix-shell --pure`?

**Comment by bugaev** [comment]
@7c6f434c: Could you please suggest how to run nix-shell? As an inexperienced user, I may be missing some crucial context to your advise.

I tried `nix-shell --pure` as is and got this:

> error: getting status of ‘/home/bugaev/PROG/ASYMPTOTE/default.nix’: No such file or directory`

Then I copied Asymptote's default.nix into the current dir: `cp /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/pkgs/tools/graphics/asymptote/default.nix . ` and tried `nix-shell --pure` again. 
This time I got the following error message:

> error: cannot auto-call a function that has an argument without a default value (‘stdenv’)

**Comment by 7c6f434c** [comment]
`nix-shell --pure -p asymptote --run "asy -vv test.asy"`

**Comment by bugaev** [comment]
@7c6f434c:
    > nix-shell --pure -p asymptote --run "asy -vv test.asy"
results in [test-pure.txt](https://github.com/NixOS/nixpkgs/files/1435513/test-pure.txt)

**Comment by 7c6f434c** [comment]
Hm. Maybe try `-offscreen` option to `asy`. Also, it looks like your video card model and the driver you use are relevant.

**Comment by bugaev** [comment]
@7c6f434c:

First, thank you for suggesting `-offscreen`! I managed to produce my `test.eps`.

Second, I upgraded the system (`nix-channel --update nixos` and `time nixos-rebuild switch`) and tried again. Details about my new system are at the bottom.
`nix-shell --pure -p asymptote --run "asy -vvvv test.asy"`

I still have the run-time error:

    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
    freeglut (asy):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

The last line seems like a consequence of the first two.

My `glxgears` is working fine.

## Technical details
* System: NixOS 18.03pre118631.66b63d2f5a (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre118631.66b63d2f5a
* Sandboxing enabled: no

**Comment by 7c6f434c** [comment]
Well, I don't know how to debug complicated GL issues, but I think you
could post some basic summary about your video card (model, kernel 
driver used, X driver used, DRI driver used). I mean, getting someone
to reproduce the issue could make debugging simpler, and probably that
requires having the same graphics setup.

**Comment by bugaev** [comment]
@7c6f434c:

> could post some basic summary about your video card

 Thanks, here is a possibly incomplete information about my video system:
* [glxinfo.txt](https://github.com/NixOS/nixpkgs/files/1435848/glxinfo.txt)

* /etc/nixos/hardware-configuration.nix:

    boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    boot.kernelModules = [ "kvm-intel" ];

* /etc/nixos/configuration.nix:

    services.xserver.videoDrivers = [ "nvidia" ];

I am not sure which other sources of information may be relevant.
*  uname -a:
`Linux irene 4.9.58 #1-NixOS SMP Sat Oct 21 15:21:39 UTC 2017 x86_64 GNU/Linux`

**Comment by vcunat** [comment]
I'm running NixOS with nvidia (unstable), getting
```
freeglut (./result/bin/asy):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
```

but **no** swrast errors &ndash; those would hint at bad configuration of `LD_LIBRARY_PATH` or something similar.

**Comment by 7c6f434c** [comment]
I see you found a TORCS issue with similar enough symptoms…

I wonder if the root cause is that `asymptote` uses normal linking to
Mesa instead of `dlopen`.

**Comment by bugaev** [comment]
@vcunat 
I gave a try to `echo $LD_LIBRARY_PATH`, got this:

    /run/opengl-driver/lib

The contents of the above directory: [opengl-driver-lib.txt](https://github.com/NixOS/nixpkgs/files/1435961/opengl-driver-lib.txt)

By the way, I didn't find `swrast_dri.so` in it. May be this is a cause of the problem?

**Comment by vcunat** [comment]
AFAIK nvidia's libGL isn't supposed to have or request `swrast_dri`.  That's what mesa does as a last-resort driver.

**Comment by vcunat** [comment]
Does `ls -l /run/opengl-driver/lib` really point to `*nvidia-libs*`?

**Comment by 7c6f434c** [comment]
Actually, what happens if you run `nix-shell --pure -p asymptote --run "LD_PRELOAD=/run/opengl-drive/lib/libGL.so asy -vv test.asy"` ?

**Comment by vcunat** [comment]
Ah, right, the opengl-driver contents above seems OK, but `--pure` shell removes all variables, including `LD_LIBRARY_PATH`.  That makes the difference between our two errors, so "just" the `FBConfig` line remains...

**Comment by bugaev** [comment]
@vcunat 

> Does ls -l /run/opengl-driver/lib really point to *nvidia-libs*?

    ls -l /run/opengl-driver/lib
    /run/opengl-driver/lib -> /nix/store/hk7vdj5bi2v00f4xcpjyfn5hz4812jgd-nvidia-libs/lib

@7c6f434c 

> Actually, what happens if you run nix-shell --pure -p asymptote --run "LD_PRELOAD=/run/opengl-drive/lib/libGL.so asy -vv test.asy" ?

I tried this and the message about `swrast_dri.so` is gone. `FBConfig` error is still there: [gl-preload.txt](https://github.com/NixOS/nixpkgs/files/1438597/gl-preload.txt)

**Comment by 7c6f434c** [comment]
Hm. And if you just run `asy -vv test.asy -offscreen`, does it work now?

**Comment by bugaev** [comment]
@7c6f434c:

> Hm. And if you just run `asy -vv test.asy -offscreen`, does it work now?

It _kinda_ works. In a message earlier I reported that it works, but after I tried it again, I realized that it may take 1, 2 or event 5 attempts to succeed with the command `asy -vv test.asy -offscreen`.
Curiosly, _only if the command succeeds_ in creating `test.eps`, the message about freeglut pops up:

> freeglut  ERROR:  Function <glutDisplayFunc> called without first calling 'glutInit'`

If the the command fails, there is no message about freeglut.
This makes me think that maybe freeglut thing is not really a reason for `asy` failing to create output.

**Comment by 7c6f434c** [comment]
I start wondering if putting everything in `/run/opengl-driver/lib` into `LD_PRELOAD` is a bad idea to try…

**Comment by matthuszagh** [comment]
@bugaev did you ever get this working? I'm experiencing the same issue and the suggestions above don't help.

**Comment by matthuszagh** [comment]
nvm, updating asymptote fixes the issue. I'll have a PR for this shortly.

**Comment by matthuszagh** [comment]
Closing this issue as I believe this has long since been resolved. Please reopen if you're still experiencing this with 2.65.
