### ISSUE TITLE
Meteo "Maps" section doesn't work; `TLS/SSL support not available; install glib-networking`

### ISSUE THREAD

**Issue by HammyHavoc** [NixOS/nixpkgs#311066]
### Describe the bug
Gives this error: `TLS/SSL support not available; install glib-networking`, yet installing `glib-networking` doesn't fix the problem.

### Steps To Reproduce
1. Launch Meteo
2. Click `Maps`

### Expected behavior
That the Maps section works.

### Notify maintainers

@bobby285271 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bryandesrosiers** [comment]
I have this exact issue. Hoping for some clarity.

**Comment by jtojnar** [comment]
`glib-networking` should be added here:

https://github.com/NixOS/nixpkgs/blob/c4e29bc0c6737bb7284b27d47efdda07fc939495/pkgs/applications/networking/weather/meteo/default.nix#L43
