### ISSUE TITLE
BUG: "winegstreamer: failed to create decodebin, are 64-bit GStreamer "base" plugins installed?" Seeing this error with Bottles when running a game

### ISSUE THREAD

**Issue by saikatdas0790** [NixOS/nixpkgs#311004]
### Describe the bug
When running a game with Bottles, I am seeing this error.

![image](https://github.com/NixOS/nixpkgs/assets/7412443/71579709-f535-4a7d-9b50-2b3ed45f0576)

The effect of this is that no videos ingame are playing. From reading the error, I feel that there's some configuration that I'm missing or some base package that I need to add from the Nixpkgs repo. Please help

### Steps To Reproduce
1. Open game "Disintegration"
2. Notice no videos playing
3. Check bottles logs and see this
![image](https://github.com/NixOS/nixpkgs/assets/7412443/e75fe964-de8f-4b70-8652-2923e6cd937f)

### Expected behavior
Videos work in game

### Notify maintainers

@SuperSamus I saw that you also spotted and fixed this here
https://github.com/NixOS/nixpkgs/issues/207641

Any help is appreciated 🙂

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05pre623656.f1010e0469db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

**Comment by SuperSamus** [comment]
What Wine version are you using? (And is it from the system?)
Could I have more logs?

**Comment by saikatdas0790** [comment]
> What Wine version are you using? (And is it from the system?)
When you say Wine version, you mean the Runner, right? Because I don't specifically choose Wine, it's whatever is the default being used by Bottles as part of this Runner that I'm using. It's `soda-9.0.1`, the latest.
![image](https://github.com/NixOS/nixpkgs/assets/7412443/61232f7a-acca-4b0d-9fd8-a78677e35154)

> Is there any change if you set the environment variable `BOTTLES_USE_SYSTEM_GSTREAMER`?
> Could I have more logs?

I set it by running the bottles app from a terminal and that is how I've been looking at logs data. Attaching screenshots of the entire log. 
![image](https://github.com/NixOS/nixpkgs/assets/7412443/666c7473-56ce-42e0-aa5b-1548c739e0e4)
![image](https://github.com/NixOS/nixpkgs/assets/7412443/7648a2ba-5c82-4bbf-9e5c-c9eb8ab2be29)
![image](https://github.com/NixOS/nixpkgs/assets/7412443/7697c713-9b9a-452d-bda7-534b8bbbfe43)
![image](https://github.com/NixOS/nixpkgs/assets/7412443/77bf70ff-1e01-4ff3-afab-221fa5c74094)

- You'll notice at the top that I started the bottles program with the variable set. 
- And at the very bottom the same error logs
- And no videos in game

@SuperSamus 
Let me know if there's any additional information I can provide. Thank you for the help 🙂

**Comment by SuperSamus** [comment]
I can reproduce it with Oblivion.
Going back in time (3f25b9d19362430dfc1bfc99c4ff17d98a5e8732), the issue isn't there.
I'll do a bisection.

**Comment by SuperSamus** [comment]
Found the bad commit: 4c214a73c3a45c6935fe3a36e9011cbd483ddf8e.
_Why_ it causes the problem, I have no idea.

**Comment by saikatdas0790** [comment]
Should we be reporting this somewhere upstream? Or is this specific to Nix?

Happy to report and ask for help elsewhere if you think that makes sense 🙂

**Comment by SuperSamus** [comment]
I have an idea.
In the changelog, I see a lot of mentions of Rust, so I was wondering if adding `gst-plugins-rs` would do something.
Unfortunately, the 32 bit version of it isn't cached, and it takes hours to compile, so because you are using a 64 bit game, I ask you to test it with this:
```
nix run github:SuperSamus/nixpkgs/bottles-gstreamer-test#bottles
```

**Comment by saikatdas0790** [comment]
@SuperSamus Hi Samus 👋🏼

I ran this to get the output logs

```bash
nix run github:SuperSamus/nixpkgs/bottles-gstreamer-test#bottles --verbose --log-format raw
```

![image](https://github.com/NixOS/nixpkgs/assets/7412443/662c6849-ad4f-4c0c-96ce-da90bbaadfc3)

Still seeing the same message and no videos in game

![image](https://github.com/NixOS/nixpkgs/assets/7412443/e2a8c6e8-9d5f-44cd-a803-5daa9d22449d)

**Comment by SuperSamus** [comment]
Well, I hoped for an easy solution...
I guess the next best idea is bisecting `gstreamer` itself.

**Comment by SuperSamus** [comment]
After a torturous bisect, I finally found the faulty commit: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/bd97973ce0f2c5495bcda5cccd4f7ef7dcb7febc.
[Reverting it](https://github.com/NixOS/nixpkgs/files/15300328/gst.patch.txt) fixes the issue, even on the current version.

I'll leave the choice of whether to revert it upstream or only on nixpkgs to someone with more authority with me.

**Comment by keenanweaver** [comment]
> I'll leave the choice of whether to revert it upstream or only on nixpkgs to someone with more authority with me.

I believe this is the domain of @lilyinstarlight.

**Comment by SuperSamus** [comment]
Working: [bottles-3f25b9d.log](https://github.com/NixOS/nixpkgs/files/15308569/bottles-3f25b9d.log)
Broken: [bottles-present.log](https://github.com/NixOS/nixpkgs/files/15308571/bottles-present.log)

**Comment by lilyinstarlight** [comment]
@SuperSamus Hmm that does not seem to include the debug messages around the code which that commit changes. Were these manually redacted?

**Comment by SuperSamus** [comment]
No, I only removed stuff like `fsync: up and running`.

**Comment by lilyinstarlight** [comment]
That counts as manually redacted... but I'm just going to assume the logs I'm looking for don't exist then

How were you adding that env var/running stuff?

**Comment by SuperSamus** [comment]
> How were you adding that env var/running stuff?

I simply ran from the terminal
```
G_MESSAGES_DEBUG=all /path/to/bottles &> filename.log
```
(With `/path/to/bottles` being the path returned by `nix-build`)


By the way, I remembered one thing.
GStreamer didn't always work out of the box on Bottles: it required that `buildFHSEnv` had the following:
```nix
  # `/usr` is optional
  profile = ''
    export GST_PLUGIN_PATH=/usr/lib32/gstreamer-1.0:/usr/lib64/gstreamer-1.0
  '';
```
This workaround was later not needed (in not going to bisect when).

Trying this today, it still solves the problem. (I've added logs)
However, it _is_ a workaround (and I assume that packages like Lutris or Heroic would also need it, if using system libs).

**Comment by lilyinstarlight** [comment]
I couldn't get bottles to work for me (it seems any bottle I make just stays grayed out?), but I think this is enough information for me to figure out the issue

Reverting that upstream commit is itself also a workaround from what I can tell, but I'll get to the bottom of it today or tomorrow

**Comment by SuperSamus** [comment]
So, what should be done?
NixOS 24.05 is coming. While this is not the biggest regression in the world, it would be better if it didn't stay there for long.

**Comment by lilyinstarlight** [comment]
@SuperSamus Are you on Matrix (I'm [@lily:lily.flowers](https://matrix.to/#/@lily:lily.flowers)) and would you be able and willing to help me repro this? I was having trouble reproducing the issue

**Comment by lilyinstarlight** [comment]
With help from @SuperSamus, I've gotten to the bottom of the issue now. There was no `GST_PLUGIN_SYSTEM_PATH_1_0` var that bottles propagated, and when gstreamer tried to canonicalize libgstreamer path (and later on reuses that path for fallback plugin dir), it started looking in a different dir from before

> Might or might not be a proper fix, but my [game launcher repo](https://github.com/ezKEa/aagl-gtk-on-nix) was seeing the same problem on unstable branch, fixed by [adding GStreamer and it's plugins to buildInputs](https://github.com/ezKEa/aagl-gtk-on-nix/commit/1e7b0b5d93401923b6645959dff4ca912d27c791), where wrapGAppsHook4 will see them and set the appropriate env vars correctly (as documented [here](https://github.com/NixOS/nixpkgs/blob/cab94ab46e676b5c6aaf98ad602d9b8ed14191dd/doc/languages-frameworks/gnome.section.md?plain=1#L127)). The [lutris](https://github.com/NixOS/nixpkgs/blob/cab94ab46e676b5c6aaf98ad602d9b8ed14191dd/pkgs/applications/misc/lutris/default.nix#L98-L105) package seems to have incidentally already been doing this, which is what led me to try it as a solution.

This sort of also works by accident, and I imagine it only works for 64bit-on-64bit too

The proper solution is probably for the fhsenv to set a `profile` of `export GST_PLUGIN_SYSTEM_PATH_1_0=/lib/gstreamer-1.0:/lib32/gstreamer-1.0`, like the following diff:

```diff
diff --git a/pkgs/applications/misc/bottles/fhsenv.nix b/pkgs/applications/misc/bottles/fhsenv.nix
index fd0d38f69892..a8d7e0cd5764 100644
--- a/pkgs/applications/misc/bottles/fhsenv.nix
+++ b/pkgs/applications/misc/bottles/fhsenv.nix
@@ -94,6 +94,10 @@ let fhsEnv = {
     ] ++ xorgDeps pkgs
     ++ gstreamerDeps pkgs
     ++ extraLibraries pkgs;
+
+    profile = ''
+      export GST_PLUGIN_SYSTEM_PATH_1_0=/lib/gstreamer-1.0:/lib32/gstreamer-1.0
+    '';
 };
 in
 symlinkJoin {
```

**Comment by SuperSamus** [comment]
So, the workaround of before (https://github.com/NixOS/nixpkgs/issues/311004#issuecomment-2111923059) was the right thing to do all along?

**Comment by lilyinstarlight** [comment]
> So, the workaround of before ([#311004 (comment)](https://github.com/NixOS/nixpkgs/issues/311004#issuecomment-2111923059)) was the right thing to do all along?

Oh, ha, I forgot about that message. Yes
