### ISSUE TITLE
Haskell tests suites cannot be run with ghc 9.10

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#311024]
### Describe the bug

Building with ghc 9.10 shows me:

```
       > Running phase: checkPhase
       > Error: [Cabal-8123]
       > Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

We need this for the checkPhase as well:
https://github.com/NixOS/nixpkgs/blob/45946fbf0fa452d874f92095552a1a7888fd6d73/pkgs/development/haskell-modules/generic-builder.nix#L531

**Comment by sternenseemann** [comment]
#312859
