### ISSUE TITLE
Mutt lacking useful default configuration for S/MIME and GnuPG

### ISSUE THREAD

**Issue by dkellner** [NixOS/nixpkgs#31102]
When you want to use S/MIME or GnuPG with Mutt on e.g. Debian, the "wiring" of the needed tools is done for you system-wide. They will source a stripped-down version of Mutt's [contrib/smime.rc](https://dev.mutt.org/hg/mutt/file/mutt-1-9-1-rel/contrib/smime.rc) and [contrib/gpg.rc](https://dev.mutt.org/hg/mutt/file/mutt-1-9-1-rel/contrib/gpg.rc) including settings like:

```
set smime_encrypt_command="openssl smime -encrypt -%a -outform DER -in %f %c"
set smime_decrypt_command="openssl smime -decrypt  -passin stdin -inform DER -in %f -inkey %k -recip %c"
...
set pgp_decode_command="gpg --status-fd=2 %?p?--passphrase-fd 0? --no-verbose --quiet --batch --output - %f"
set pgp_decrypt_command="gpg --status-fd=2 %?p?--passphrase-fd 0? --no-verbose --quiet --batch --output - %f"
...
```

This is not the case for the Mutt package in NixOS. In order to get S/MIME and GnuPG to work, you need to include those settings yourself. I would say we could give useful defaults for those settings that most users won't even have to think about.

I'm quite new to NixOS, so I'm not sure how to proceed here. Is it desirable to just source the same default configuration as Debian does (i.e. a stripped-down version of Mutt's sample configurations), or should we introduce new options `smimeSupport`/`gpgSupport`?

cc mutt maintainers @the-kenny @rnhmjoj

-----

And in case somebody is searching the internet for the error messages you will get in the meantime, I add them here. For now the problem can be solved by copying `contrib/smime.rc` and/or `contrib/gpg.rc` to `~/.mutt/` and sourcing them in `muttrc`.

### S/MIME
`.muttdebug0` (with `mutt -d5`) contains:
```
[2017-11-01 19:24:35] Failed on attachment of type application/pkcs7-mime.
[2017-11-01 19:24:35] Bailing on attachment of type application/pkcs7-mime.
[2017-11-01 19:24:35] Could not copy message
```

### GnuPG
`.muttdebug0` (with `mutt -d5`) contains:
```
[2017-11-01 19:27:25] Could not decrypt PGP message
[2017-11-01 19:27:27] Failed on attachment of type multipart/encrypted.
[2017-11-01 19:27:27] Bailing on attachment of type multipart/encrypted.
[2017-11-01 19:27:27] Could not copy message
```

**Comment by rnhmjoj** [comment]
It looks pretty easy to do: appending a `source $out/share/doc/mutt/samples/gpg.rc` in the Muttrc file should do it. I don't have much time right now, maybe next week.

**Comment by rnhmjoj** [comment]
I like adding options like `gpgSupport` but I don't think this needs to be configurable: it's already packaged in and enabling it should be harmless.

**Comment by dkellner** [comment]
I would not not source the whole files, as they contain other settings, too - like enabling signing by default. And we would have to use proper paths to the `openssl`, `gpg` and `pgpewrap` binaries.

Let me know if I can help you by preparing versions of those files with just the needed settings (maybe just the ones with a `_command` suffix?!).

**Comment by rnhmjoj** [comment]
Are you sure debian is sourcing a different file?
Looking at the the [source](https://anonscm.debian.org/cgit/pkg-mutt/mutt.git) the files are installed into `/etc/Muttrc.d` and then loaded.
```
$ ack 'Muttrc\.d'

debian/mutt.install
14:contrib/gpg.rc             etc/Muttrc.d
15:contrib/smime.rc	        etc/Muttrc.d
16:debian/extra/rc/*.rc     etc/Muttrc.d

debian/extra/lib/source-muttrc.d
3:for rc in /etc/Muttrc.d/*.rc; do
```

The `gpg.rc` is (almost) identical to the one in the samples
```
$ diff -u /nix/store/2z600bzpx2a7v8jw44mv3glggvd5mdbf-mutt-1.9.1/share/doc/mutt/samples/gpg.rc mutt/contrib/gpg.rc

--- /nix/store/2z600bzpx2a7v8jw44mv3glggvd5mdbf-mutt-1.9.1/share/doc/mutt/samples/gpg.rc	1970-01-01 01:00:01.000000000 +0100
+++ mutt/contrib/gpg.rc	2017-11-02 23:29:50.200398656 +0100
@@ -1,11 +1,9 @@
 # -*-muttrc-*-
 #
 # Command formats for gpg.
-# 
-# This version uses gpg-2comp from 
-#   http://70t.de/download/gpg-2comp.tar.gz
 #
-# $Id$
+# This version uses gpg-2comp from
+#   http://70t.de/download/gpg-2comp.tar.gz
 #
 # %p    The empty string when no passphrase is needed,
 #       the string "PGPPASSFD=0" if one is needed.

```

It could be patched but I'm not sure.

**Comment by dkellner** [comment]
Could be due to different versions, at least on my Jessie box some lines are commented-out that are in the `contrib/` version. But I'm personally fine with sourcing the whole thing, too. Just worry about user configuration could easily break the more options we set globally.

```
dkellner@1b2d97fb9b73:~$ cat /etc/Muttrc.d/smime.rc | grep "set crypt_"
#set crypt_autosign = yes
#set crypt_replyencrypt = yes
#set crypt_replysign = yes
#set crypt_replysignencrypted = yes
#set crypt_verify_sig = yes
```
compared to https://anonscm.debian.org/cgit/pkg-mutt/mutt.git/tree/contrib/smime.rc?h=debian/1.5.23-3 .

```
dkellner@1b2d97fb9b73:~$ cat /etc/debian_version
8.9
dkellner@1b2d97fb9b73:~$ dpkg -l | grep mutt
ii  mutt                       1.5.23-3                         amd64        text-based mailreader supporting MIME, GPG, PGP and threading
```

**Comment by rnhmjoj** [comment]
Oh, I see: it's smime.rc not gpg.rc. So the former is not safe to load but the latter is ok.

**Comment by rnhmjoj** [comment]
I'm working on it now. Anyway, did you try [gpgme](https://henrytodd.org/notes/2014/simpler-gnupg-mutt-config-with-gpgme/)? I don't now about S/MIME but it works fine for PGP and doesn't require any wiring.
