### ISSUE TITLE
pam_mount and pam_systemd modules are ordered incorrectly in pam.d service files.

### ISSUE THREAD

**Issue by curro** [NixOS/nixpkgs#31113]
## Issue description

The generated /etc/pam.d/* service files invoke the pam_systemd.so session module before pam_mount.so, if both are enabled (e.g. via security.pam.services.foo.startSession and security.pam.services.foo.pamMount respectively).  This doesn't work in the most common scenario where the user's home directory is stored in a pam-mounted encrypted volume (because systemd will fail to access the user's systemd configuration).

### Steps to reproduce

* Set up pam-mounted encrypted home directory like:

> security.pam.mount.enable = true;
> users.extraUsers.myself.cryptHomeLuks = "/my/encrypted/volume";

* Log in (without the encrypted volume being already mounted).
* The user's session started by systemd will have failed to pick up configuration stored in the encrypted volume.

## Technical details

* System: 17.09.1812.36a4dc392a (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1812.36a4dc392a
* Sandboxing enabled: false

## Proposed fix

[Fix_pam_mount_session_module_ordering.patch.txt](https://github.com/NixOS/nixpkgs/files/1436103/Fix_pam_mount_session_module_ordering.patch.txt)

**Comment by bbigras** [comment]
Any chance this patch get merged? If it's still relevant.

**Comment by peterhoeg** [comment]
I am seeing this as well. @curro - any chance you can change your patch file into  a PR via github?

**Comment by flokli** [comment]
This seems to be an odering problem. Cross-linking for better visibility: https://github.com/NixOS/nixpkgs/issues/90640

**Comment by peterhoeg** [comment]
This issue was fixed in #89457.
