### ISSUE TITLE
LXD should have more tools in its path

### ISSUE THREAD

**Issue by CosmicToast** [NixOS/nixpkgs#31117]
## Issue description
lxd supports multiple storage backends, but most of them are unusable.

### Steps to reproduce
1. Set `virtualisation.lxd.enable = true;`
2. Add your user to the `lxd` group (or perform the rest of the steps as root).
3. Try to initialize a storage backend (e.g using `lxd init`) that isn't marked on the list below.

## Technical details
Nix's lxd storage backend support matrix:
- [x] Directory (see note 1)
- [x] Btrfs (see note 1)
- [x] Zfs (missing path)
- [ ] LVM Thin Volumes (missing path)
- [ ] Raw LVM (untested, but seems to not be present in lxd.nix)
- [ ] Ceph (untested, but seems to not be present in lxd.nix)

Note 1: LXD does somewhat work with the directory and btrfs backends, but any and all created containers insist that `/var/lib/lxc/rootfs` must exist.
It doesn't actually get used. This is almost certainly a bug, and is mentioned in #25280.

## Potential solutions
- LVM2 and thin-provisioning tools should almost definitely be enabled unconditionally, as per the [TODO](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/lxd.nix#L47).
- Zfs and Btrfs support may potentially be autodetected based on `boot.supportedFilesystems`.
- Ceph is sufficiently uncommon that it may be an explicitly-enabled option.

Alternatively, we can have something ala `boot.supportedFilesystems` under, say, `virtualisation.lxd.storageBackends`.

I'm going to be busy working for a bit, and am still somewhat unfamiliar with the nix expression language, but I'll take a look at making a (basic, to be expanded upon) patch once I have time.

**Comment by Shados** [comment]
FWIW, the version of Ceph in nixpkgs is 1) ancient, and 2) marked as broken (due to a DOS vulnerability), so I wouldn't worry about it too much right now. I've been working on packaging a recent (12.2.x) release, but they changed to building using cmake and some outputs are silently not being built by my current expression...

**Comment by 5paceToast** [comment]
Ceph is the one I'm worried least about (since it's quite uncommon, as far as I can tell).
LVM and Zfs, on the other hand, are very common, and currently nonfunctional.

**Comment by ilya-kolpakov** [comment]
I like supported backends option more than unconditional enabling. This option is not necessarily LXD specific. For instance, current docker module also does not include thin provisioning tools automatically AFAIK.

**Comment by MrSorcus** [comment]
When it will be completed?

**Comment by 5paceToast** [comment]
Probably never, I stopped using nix since it ended up not fitting into my workflow very well, with relatively common annoying (to me) side effects (of the immutability bit).
If there was work being done it would be availabe in a linked PR ;)

**Comment by Mic92** [comment]
zfsSupport was added as a flag in 7663de114a365259f07425aa582b3c5890c00874

**Comment by Mic92** [comment]
Ceph module was also revisted in the last release. It also has a test now.

**Comment by jkryl** [comment]
I had this problem with lvm storage backend and was able to work around it by putting the following line to /etc/nixos/configuration.nix:

```
  systemd.services.lxd.path = with pkgs; [ lvm2 thin-provisioning-tools ];
```

The line above includes lvm tools in the PATH of lxd daemon. Until I did that I was getting the following error from `lxd init` or `lxc` when trying to create a storage pool:
```
$ lxc storage create lxd lvm source=/dev/sdb1
Error: Error getting LVM version: Failed to run: lvm version:
output:''
```

**Comment by mt-caret** [comment]
On the topic of tools which should be included in the lxd module, I think libnvidia-container should be included as well (related issue: https://github.com/NixOS/nixpkgs/issues/27999). I really should take a stab at it someday...

**Comment by Mic92** [comment]
still not addressed.

**Comment by gebner** [comment]
I believe `qemu-img` is missing as well:
```
$ lxc launch --vm images:archlinux/current
Error: Failed instance creation: Create instance from image: Failed reading image info "/var/lib/lxd/storage-pools/default/virtual-machines/sincere-eagle/root.img": Failed to run: qemu-img info --output=json /var/lib/lxd/images/ed08824e15dd8efc89afb9eba288f8417d2309c0bce7c7684ac160ece786034f.rootfs:i
```

But that still fails with "`/usr/share` not found" even if I add `qemu` to the path..

**Comment by Mic92** [comment]
For some backends I would add additional options rather than just adding all of them.
