### ISSUE TITLE
Update request: Noice v2.0.1 → v2.0.2

### ISSUE THREAD

**Issue by nicolasauler** [NixOS/nixpkgs#311112]
- Package name: Noice
- Latest released version: v2.0.2

- Current version on the unstable channel: v2.0.1
- Current version on the stable/release channel: v1.16.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GaetanLepage I think that's you, right?

Also, I think this update will be nice, because I've been experiencing some bugs here and there, with autocommands, noice and lsp. I don't know if they are related haha, but those bugfixes in v2.0.2 might help!

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
Are you talking about `vimPlugins.noice-nvim` ?

**Comment by GaetanLepage** [comment]
The update is part of #311121

**Comment by nicolasauler** [comment]
> The update is part of #311121

Ah, sorry Gaetan!
Thanks, I'm closing this then.
