### ISSUE TITLE
Allow boot in subdirectory of a partition (working, asking for agreement)

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#3111]
My use case is that I have a debian desktop, but I want to try out nixos natively, straight from boot without changing the partition layout.
What I did is installing nixos into /nixos (to make this happen I have bind mounted /nixos to /mnt).

In the following example I'm using /dev/sda6.
In configuration.nix:

```
  fileSystems."/" =
    { device = "/dev/myrealroot/nixos";
      fsType = "none";
      options = "bind";
    };

  boot.initrd.postDeviceCommands = ''
    mkdir -p /dev/myrealroot
    echo "/dev/sda6 /dev/myrealroot ext4 defaults,relatime" >> /etc/fstab
    mount /dev/myrealroot
  '';
```

To `nixos-install` there's a little problem, I want to generate grub files under /nixos/boot but I don't want to install grub anywhere.
I run `nixos-install` twice, the first time I enable grub to install in /dev/null, so that the initrd gets generated then fail at grub-install.
The second time I disable grub to make `nixos-install` success.

Now boot your system, enter grub shell and type `configfile (hd0,msdos6)/nixos/boot/grub/grub.cfg`.
Edit the grub line and change ONLY two lines, the vmlinuz and the initrd to point to `/nixos/nix/store/...` instead of `/nix/store`.
Boot!

As you can see, there are very few changes to make this happen, and I think it's an invaluable thing to have in nixos to allow users to install it easily and test it for real, without doing any backup or changing the partition layout.

Now I'd like to work on this issue by adding a `boot.rootSubdir` option, which adds the few missing stuff to make this happen. If you agree with having this feature, I'm going deep, @edolstra .

**Comment by Profpatsch** [comment]
(triage) After two years, what are your thoughts, @edolstra?

**Comment by Profpatsch** [comment]
Closing since no reaction. Reopen if necessary.

**Comment by dlight** [comment]
So, what's the best way to do this in 2022? It's like booting into a btrfs subvolume, but without btrfs it's just a subdirectory.

Currently I'm using this in Arch https://aur.archlinux.org/packages/mkinitcpio-loop-subdir

**Comment by dlight** [comment]
It seems it was attempted in a PR in #3143 by @lethalman, closed due "This code is wrong, makes wrong assumptions about the order of mounts." and then made into an issue in #4972

So I'm unsure if this approach even work

But I would like to have a boot.rootSubdir option.. @Profpatsch can I make a PR?

**Comment by imxade** [comment]
On usual distributions, that' possible by creating a custom module/hook for mkinitcpio/dracut.

Would also like to see **boot.subroot** option on nixos.
