### ISSUE TITLE
pcmanfm: trash, operation not supported

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#31121]
## Issue description
Though I can move files to trash via right click and they are end up in `/home/bjorn/.local/share/Trash/files`, restoring not supported and trash icon not shows in right sidebar

### Steps to reproduce
```
  services = {
    gnome3.gvfs.enable = true; # trash
    udisks2.enable = true;
}

```
Install pcmanfm, open, `Go -> Trash can`, `Error: Operation not supported` modal

## Technical details

* System:  (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by Ma27** [comment]
might be related to #29137 as gvfs is also needed for trash support.

**Comment by BjornMelgaard** [comment]
Fixed this right now by using

```nix
      desktopManager = {
        default = "gnome3";
        gnome3.enable = true;
      };
```

P.S. I love nixos!!!! :heart:  :heart:  :heart:
