### ISSUE TITLE
nixos/pufferpanel: Issue adding admin user

### ISSUE THREAD

**Issue by GGG-KILLER** [NixOS/nixpkgs#311272]
### Describe the bug

PufferPanel module docs indicate that the command `pufferpanel --workDir /var/lib/pufferpanel user add --admin` should be used to add an admin user.

However it fails because of missing permissions as `DynamicUser` is used. This is explicitly recommended against [by systemd](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#DynamicUser=) for services that store permanent data on disk as it's not guaranteed the UID will always be the same:
> Care should be taken that any processes running as part of a unit for which dynamic users/groups are enabled do not leave files or directories owned by these users/groups around, as a different unit might get the same UID/GID assigned later on, and thus gain access to these files or directories.

If one attempts to continue using `sudo`, then the user credentials will be saved incorrectly which then leads to being unable to log in.

### Steps To Reproduce
1. Spin up the service with a simple config as the following:
  ```nix
  services.pufferpanel = {
    enable = true;
    extraPackages = with pkgs; [bash curl gawk gnutar gzip];
    extraGroups = ["docker"];
    environment = {
      PUFFER_WEB_HOST = "127.0.0.1:${toString config.shiro.ports.pufferpanel}";
      PUFFER_DAEMON_SFTP_HOST = "0.0.0.0:${toString config.shiro.ports.pufferpanel-sftp}";
      # PUFFER_PANEL_REGISTRATIONENABLED = "false";
    };
  };
  ```
2. Attempt to run `nix-shell -p pufferpanel --run 'pufferpanel --workDir /var/lib/pufferpanel user add --admin'
3. The following error happens:
```
[ERROR] 2024/05/13 02:28:11 chdir /var/lib/pufferpanel: permission denied
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
main.main.func1()
	github.com/pufferpanel/pufferpanel/v2/cmd/main.go:31 +0x3f
panic({0x141d400?, 0xc0006ed680?})
	runtime/panic.go:770 +0x132
main.setWorkDir()
	github.com/pufferpanel/pufferpanel/v2/cmd/main.go:65 +0x3c
github.com/spf13/cobra.(*Command).preRun(...)
	github.com/spf13/cobra@v1.6.1/command.go:946
github.com/spf13/cobra.(*Command).execute(0x20f30a0, {0xc00006f500, 0x3, 0x4})
	github.com/spf13/cobra@v1.6.1/command.go:876 +0x5a2
github.com/spf13/cobra.(*Command).ExecuteC(0x20f2240)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.Execute()
	github.com/pufferpanel/pufferpanel/v2/cmd/main.go:80 +0x5d
main.main()
	github.com/pufferpanel/pufferpanel/v2/cmd/main.go:38 +0x45
```

### Expected behavior
The prompt to add the new admin user shows up normally.

### Screenshots
Attempt to add new user:
![image](https://github.com/NixOS/nixpkgs/assets/5892127/d747c32a-886f-40df-939c-a37dc0071a1e)

After adding user using `sudo`:
![image](https://github.com/NixOS/nixpkgs/assets/5892127/a54e33c1-76e9-4aeb-ba12-4402a13375aa)

### Additional context
Another thing to note is that registering through the web UI works, however if you use the CLI to change the user to an admin user, then the credentials become invalid.

Adding the package through `environment.systemPackages` to ensure it's the same version also changes nothing.

### Notify maintainers
@tie 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
ggg@shiro [02:28:12 AM] [~] 
-> % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - nixpkgs: `/nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GGG-KILLER** [comment]
Actually, the issue seems to be that any credential seems to be invalid (even if registered through the web UI), I'm unsure if this is related to the sqlite db being used or something else.

**Comment by tie** [comment]
Hi! I'm sorry if I made it unclear from the documentation, yes, `pufferpanel user add` should be running either as root or pufferpanel user (that is, with enough privileges to access its data directory), and database must be initialized prior to this.

For example, see NixOS tests:
https://github.com/NixOS/nixpkgs/blob/6bc8c8a7ac13182ee24a5e2caab7ad739f1c55c5/nixos/tests/pufferpanel.nix#L62
