### ISSUE TITLE
Terraform_0_10 package can not be built

### ISSUE THREAD

**Issue by jesuspc** [NixOS/nixpkgs#31127]
## Issue description

The packages terraform_0_10 and terraform_0_10-full fail to build in nixos 17.09.

### Steps to reproduce

```bash
nix-env -iA nixos.terraform_0_10
```

It fails with

```
...
go build github.com/hashicorp/terraform/tools/terraform-bundle/e2etest: no buildable Go source files in /tmp/nix-build-terraform-0.10.7.drv-0/go/src/github.com/hashicorp/terraform/tools/terraform-bundle/e2etest
builder for ‘/nix/store/6z5n6cgc6gk8ar8rx3wx1xslywn5k761-terraform-0.10.7.drv’ failed with exit code 47
error: build of ‘/nix/store/6z5n6cgc6gk8ar8rx3wx1xslywn5k761-terraform-0.10.7.drv’ failed
```

## Technical details

* System: nixos 17.09
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.1813.bf3dbc2b38
* Sandboxing enabled: false

**Comment by dezgeg** [comment]
Reverted back to 0.10.2 in 1a6a7b0f33f0789734c10643da3396f12953b58d

**Comment by domenkozar** [comment]
`Sandboxing enabled: false` - this might be the cause. I can build it by reverting the commit without issues. I'm going to upgrade terraform again, hopefully hydra can just provide a binary cache.

**Comment by domenkozar** [comment]
Proof in https://github.com/NixOS/nixpkgs/pull/33003
