### ISSUE TITLE
KDE Connect cannot browse device in Plasma 6

### ISSUE THREAD

**Issue by Sicheng-Pan** [NixOS/nixpkgs#311236]
### Describe the bug
I cannot browse my android device with KDE Connect in Plasma 6. If I try to open my phone in Dolphin, I receive the following error message.
```
Error when accessing filesystem. sshfs finished with exit code 1 
```

When I compare the nix package definition for [`libsForQt5.kdeconnect-kde`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/kde/kdeconnect-kde.nix#L77) and [`kdePackages.kdeconnect-kde`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/kde/gear/kdeconnect-kde/default.nix#L12), I notice that the older one manually add `sshfs` in the `PATH`:

https://github.com/NixOS/nixpkgs/blob/062ca2a9370a27a35c524dc82d540e6e9824b652/pkgs/applications/kde/kdeconnect-kde.nix#L72-L74

I'm wondering if this could be the source of issue.

### Steps To Reproduce
1. Browse device using KDE Connect via Dolphin in Plasma 6

### Expected behavior
I should be able to browse my device in Dolphin

### Additional context
If I remember correctly KDE Connect worked for me in Plasma 5.

### Notify maintainers
@K900 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240511.062ca2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/pfc56yr7y3wflvbgnrpscf2n1m4j3xd7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/311269

**Comment by Sicheng-Pan** [comment]
@K900 I've used an overlay to replace `kdePackages.kdeconnect-kde` in my system with the one in the PR. The nix path is `/nix/store/lm7sgbpfpa47n0pwzvgj50v518giiy6b-kdeconnect-kde-24.02.2`. It seems that the same error is still occurring.

May I ask if you could reproduce the same issue before the fix and resolve the issue with the fix? Or is there anything else I should overlay to make this work?

**Comment by K900** [comment]
Please try again.

**Comment by Sicheng-Pan** [comment]
Thanks for the update! This seems to fix the issue for me.
