### ISSUE TITLE
Update request: nushell 0.92.1 -> 0.93.0 

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#311373]
- Package name: nushell
- Latest released version: 0.93.0

- Current version on the unstable channel: 0.92.1
- Current version on the stable/release channel: 0.87.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Br1ght0ne @johntitor @joaquintrinanes

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Looks like I was mentioned, or not..... :)
