### ISSUE TITLE
htop graphs are garbled in Konsole

### ISSUE THREAD

**Issue by DiThi** [NixOS/nixpkgs#31131]
## Issue description

![image](https://user-images.githubusercontent.com/1127198/32329350-1daa40f8-bfdd-11e7-8d15-4443cbef3997.png)

### Steps to reproduce

* Open Konsole (stand alone app or in a kpart such as yakuake)
* Run htop

Result is bad with low CPU load, it's even worse with high load.

Using font Inconsolata (probably not related, after updating it had a variable width font)

## Technical details

* System: 18.03pre118631.66b63d2f5a (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre119086.737b466031
* Sandboxing enabled: no

**Comment by pSub** [comment]
I cannot reproduce your problem with current master (5adec8d6c18fb24d002bf055ac3e0805146f4caa). Do you still have the problem?

**Comment by DiThi** [comment]
For several reasons I had to stop using NixOS, so unfortunately I don't know if it still happened. I guess this issue can be closed.
