### ISSUE TITLE
Symfony CLI version command shows current time as build date

### ISSUE THREAD

**Issue by RafaelKr** [NixOS/nixpkgs#311315]
### Describe the bug
After installing `symfony-cli` you can run `symfony version`. This command prints something like:
`Symfony CLI version 5.8.17 (c) 2021-2024 Fabien Potencier (2024-05-13T12:16:30+02:00 - stable)`

Usually the date at the end is the build date. But when installed via nix it always shows the current time, so the command output is different for every second.

The build date is passed here:
https://github.com/symfony-cli/symfony-cli/blob/870a3ce2ccaa6428f83428e204231b0c9be9b698/main.go#L126

It also has a comment saying `overridden at linking time`:
https://github.com/symfony-cli/symfony-cli/blob/870a3ce2ccaa6428f83428e204231b0c9be9b698/main.go#L43-L44

### Steps To Reproduce
1. Install symfony-cli: https://search.nixos.org/packages?channel=unstable&show=symfony-cli&from=0&size=50&sort=relevance&type=packages&query=symfony-cli
2. Run `symfony version`

### Expected behavior
It should show the real build time of that release (time of last commit?).

### Notify maintainers
@drupol

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-28-generic, Linux Mint, 21.3 (Virginia), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/rafael/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Hello,

Is this really a problem?

If you really want to fix it, it is possible to add: `"-X main.buildDate=<something>"` in [here](https://github.com/NixOS/nixpkgs/blob/aac3aeaf2ff230af121534e26262feb6428214ff/pkgs/by-name/sy/symfony-cli/package.nix#L23) with a fixed date value or possibly the date of the commit tag.

**Comment by RafaelKr** [comment]
@drupol Awesome, thanks for taking the time to implement this!
