### ISSUE TITLE
Documentation: KDE Connect/GSConnect requires TCP/UDP port 1714-1764 to work

### ISSUE THREAD

**Issue by lebensterben** [NixOS/nixpkgs#311448]
## Problem

I've enabled `gnomeExtensions.gsconnect`, which is a Gnome plugin that implements KDE Connect to connect your PC to your mobile device(s).

After installation, I'm not able to discover my phone from the PC end. Nor can my phone discover my PC.

I also tried `kdePackages.kdeconnect-kde` and the problem persists. (Thus it's not caused by Gnome's implementation detail.)

After some digging, it turns out that KDE Connect/GSConnect requires TCP/UDP ports 1716-1764 to work. (See https://userbase.kde.org/KDEConnect#I_have_two_devices_running_KDE_Connect_on_the_same_network,_but_they_can't_see_each_other) And by default NixOS has firewall to turn on. So I found the following solution:

```nix
networking.firewall.allowedTCPPortRanges = [
  { from = 1714; to = 1764; }
];
networking.firewall.allowedUDPPortRanges = [
  { from = 1714; to = 1764; }
];
```

## Proposal

Adds the aforementioned snippet to a documentation section for `kdePackages.kdeconnect-kde` and `gnomeExtensions.gsconnect`.

Alternatively, we can just open those ports when installing these two packages. But I'm not sure whether it's prudent enough to opening ports without explicit knowledge from users.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by keenanweaver** [comment]
If you use the [kdeconnect option](https://search.nixos.org/options?channel=unstable&show=programs.kdeconnect.enable&from=0&size=50&sort=relevance&type=packages&query=programs.kdeconnect) instead of adding it to your systemPackages, it will set up the ports for you.

``` nix
programs.kdeconnect = {
  enable = true;
  package = pkgs.gnomeExtensions.gsconnect;
};
```
The rule of thumb is you want to check for an option first before adding something as a package, or you'll come across issues like you did with the ports being closed. (I had the same problem with KDE Connect when I first started out!)

**Comment by lebensterben** [comment]
@keenanweaver 

Thanks for the good advice🫡
