### ISSUE TITLE
License request: ncbiPD

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#311477]
See https://github.com/spdx/license-list-XML/issues/2419

**Comment by fabaff** [comment]
As questions a in #311476. We could add the license if there is a need for it.

**Comment by Pandapip1** [comment]
> As questions a in https://github.com/NixOS/nixpkgs/issues/311476. We could add the license if there is a need for it.

That would be for `sratoolkit`, which is **not** public domain worldwide.

**Comment by fabaff** [comment]
Please open a PR that adds the license to `lib/licenses.nix` and adjust the license of `sratoolkit`.

**Comment by Pandapip1** [comment]
I'd do that, except I can't find any documentation as to what format the commit message should be.
