### ISSUE TITLE
Setting `xserver.autorun` to false no longer prevents a display manager from starting

### ISSUE THREAD

**Issue by immindich** [NixOS/nixpkgs#311683]
### Describe the bug
In stable, setting `services.xserver.autorun = false` in my NixOS config prevented my display manager from starting automatically. I could then start the display manager manually by running `systemctl start display-manager.service`. I just upgraded to unstable and this no longer works. I think this may be because of [this line](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/x11/xserver.nix#L642) in the xserver module.

### Steps To Reproduce
1. Include the following in your NixOS config:
```  
services.xserver = {
  enable = true;
  autorun = false;
};
```
2. Rebuild and reboot. A display manager will automatically start. If no display manager is explicitly enabled, this will be LightDM.
 
### Expected behavior
System boots to the console.

### Notify maintainers

@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05pre623656.f1010e0469db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
This is probably because of https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/graphical-desktop.nix#L45 which is required for SDDM on Wayland where no xserver is started at all. The easiest fix is probably to set systemd.defaultUnit to multi-user.target.

**Comment by SuperSandro2000** [comment]
Going to close this as won't fix. If you want to prevent a Wayland display manager from starting up, please change systemd.defaultUnit

**Comment by ob7** [comment]
Should we make it so setting
```nix 
services.xserver.autorun = false
``` 
automatically sets 
```nix
systemd.defaultUnit = lib.mkForce "multi-user.target";
```
or should we atleast add it to ```man configuration.nix``` as a comment under the autorun setting so the user knows to declare it manually?  

From my experience I don't think setting ```autorun = false``` has worked for over a year now.

**Comment by SuperSandro2000** [comment]
Adding it to the description of the options is fine for me but not mkForcing the default unit.

**Comment by ob7** [comment]
made PR adding the comment here https://github.com/NixOS/nixpkgs/pull/362902
