### ISSUE TITLE
GNOME characters not launcable via GNOME shell

### ISSUE THREAD

**Issue by samdroid-apps** [NixOS/nixpkgs#31168]
## Issue description

GNOME Characters does not launch when opened via GNOME Shell (i.e. the overview).  It does however launch via the command line (`gnome-characters`)

### Steps to reproduce

1. Open overview
2. Click to launch gnome characters

it will not launch (no window pops up).  From the journal:

```
Nov 02 22:25:54 vcs org.gnome.Chara[5482]: JS LOG: Missing GSettings schema org.gnome.Characters
```

However, if you launch it via the terminal it will work:

1. Open terminal emulator
2. Type `gnome-characters`, press enter

Notice how it has launched successfully.

## Technical details

* System: NixOS 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1880.ac2bb5684c"
* Sandboxing enabled: yes

**Comment by jtojnar** [comment]
The problem is caused by the DBus service file linking to `$out/share/org.gnome.Characters/org.gnome.Characters`.

The simplest solution is changing the `Exec` key like we have done [in `gnome-maps`](https://github.com/NixOS/nixpkgs/blob/1729e9ea25b5497ae1c70deab69d88d598a4c355/pkgs/desktops/gnome-3/apps/gnome-maps/default.nix#L24-L28) but there is also `org.gnome.Characters.BackgroundService` which is not available in `bindir`.

We can wrap the files in `share` but then, it does not work because GJS [tries](https://github.com/GNOME/gjs/blob/a2f12538c4b6166fbb08446c480334ee861ef327/modules/package.js#L158) to load data based on `.*-wrapped` filename. It is possible to override the program name retrieval function but it is ugly: https://github.com/jtojnar/nixpkgs/tree/gnome-characters-fix

Optimally, we would patch gjs to return correct `System.programInvocationName`, which is where the [retrieval function](https://github.com/GNOME/gjs/blob/a2f12538c4b6166fbb08446c480334ee861ef327/modules/package.js#L51) gets the program name from but I cannot find where is it instantiated.

**Comment by samdroid-apps** [comment]
So the property is defined in cpp code:  https://github.com/GNOME/gjs/blob/9339f85d8b7430c4a9409efa5ff06ee71c3c3dc1/modules/system.cpp#L204

Program name originates from here: https://github.com/GNOME/gjs/blob/342a3240eb1eae5c20b7727fc8fe57952cb00c40/gjs/console.cpp#L260-L292

I could try and add a nix-specific patch to do a find/replace of `.{}-wrapped`.  That might be a good spot to fix it.

**Comment by jtojnar** [comment]
I still do not understand why this happens. We run a wrapper in file `$out/share/org.gnome.Characters/org.gnome.Characters` containing

```shell
#! /nix/store/i0ay05pqkbnvpfijm52mmlrp6kmkl80c-bash-4.4-p12/bin/bash -e
# […]
exec -a "$0" "/nix/store/mqapsqd9vx6zq11kp5cfbrp2f3622312-gnome-characters-3.26.2/share/org.gnome.Characters/.org.gnome.Characters-wrapped"  "${extraFlagsArray[@]}" "$@"
```

That one executes `.org.gnome.Characters-wrapped` but with the original name (from `$0`). Should not that make it into `argv[0]`?

-----

I have constructed a pair of simple programs that demonstrate this issue:

##### `./demo`
```shell
#! /nix/store/i0ay05pqkbnvpfijm52mmlrp6kmkl80c-bash-4.4-p12/bin/bash -e
exec -a "$0" ./printer "$@"
```

##### `./printer`
```javascript
#!/nix/store/08i852gjzi5kvv50c3dshxgvd658gqbp-gjs-1.50.2/bin/gjs
log(imports.package._findEffectiveEntryPointName());
```

I would expect demo to be printed but this is not the case:

```ShellSession
$ ./demo fooo bar baz
Gjs-Message: JS LOG: printer
```

What is worse, this behaviour is expected, according to [How programs get run](https://lwn.net/Articles/630727/):

> Things change slightly when the program being invoked is a script rather than a binary program. […] Secondly, the initial argument to the script is now the script filename, rather than the "zero" value that the invoker specified.

----

We should probably take a look at Polari where it somehow works. Maybe, using hardcoded program name for loading the gresource file?

**Comment by samdroid-apps** [comment]
> What is worse, this behaviour is expected, according to How programs get run:

If you look at python scripts; they are wrapped and have a line like the following added at the top:

```
import sys;import site;import functools;sys.argv[0] = '/nix/store/61g260ahw9lv14wxb9nqs3an9369nyjr-python3.6-Flask-0.12.2/bin/flask';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/61g260ahw9lv14wxb9nqs3an9369nyjr-python3.6-Flask-0.12.2/lib/python3.6/site-packages','/nix/store/ym1q0yx04j2bflkdxzzx9c5ylqq7pq3g-python3.6-itsdangerous-0.24/lib/python3.6/site-packages','/nix/store/dpndrxnzihplj5wvyvr655f2jf0zi2gf-python3.6-setuptools-36.4.0/lib/python3.6/site-packages','/nix/store/v16kbay8iam1nvh95lahy0607214ygj7-python3.6-click-6.7/lib/python3.6/site-packages','/nix/store/2427r8r1nm9bjvxlfrvpz4pxkpq32d8g-python3.6-Werkzeug-0.12.2/lib/python3.6/site-packages','/nix/store/fgxbxaphcns2i488jr446vva17a9f4my-python3.6-Jinja2-2.9.6/lib/python3.6/site-packages','/nix/store/zdzj3ygv5frl31mmlmxc7siizjw5g4pf-python3.6-markupsafe-1.0/lib/python3.6/site-packages'], site._init_pathinfo());
```

So you can that they have to change `sys.argv[0]`; just like we could patch gjs to do.


> We should probably take a look at Polari where it somehow works. Maybe, using hardcoded program name for loading the gresource file?

For me, Polari exhibits the same bug.  Is that what you are referring to?

**Comment by samdroid-apps** [comment]
Sorry for the last comment; I think I now know what is going on  (please correct me if I'm wrong):

> gnome-shell uses a dbus service, which executes $out/share/org.gnome.Characters/org.gnome.Characters
>
> that output is not wrapped, causing a crash when run
>
> wrapping that output (with wrapGAppsHook) results in the gsettings schema issue

Moving on, I think I have a patch.  I fix the `program_name` in `gnome3.gjs` with the following patch:

```diff
diff --git a/gjs/console.cpp b/gjs/console.cpp
index 61e8c77..611049e 100644
--- a/gjs/console.cpp
+++ b/gjs/console.cpp
@@ -280,6 +280,16 @@ main(int argc, char **argv)
         program_name = gjs_argv[1];
     }
 
+
+    /* Replace ".X-wrapped" with "X" */
+    g_warning ("argv[0] orig  = %s\n", program_name);
+    GRegex * regex = g_regex_new ("\\.([^/]+)-wrapped", (GRegexCompileFlags) 0, (GRegexMatchFlags) 0, NULL);
+    gchar * new_program_name = g_regex_replace(regex, program_name, strlen (program_name), 0, "\\1", (GRegexMatchFlags) 0, NULL);
+    g_free ((gpointer) program_name);
+    program_name = new_program_name;
+    g_warning ("argv[0] = %s\n", new_program_name);
+
+
     /* This should be removed after a suitable time has passed */
     check_script_args_for_stray_gjs_args(script_argc, script_argv);
 ```

I then also ensure that wrapGAppsHook is run for the `gnome3.gnome-characters` package:

```diff
diff --git a/pkgs/desktops/gnome-3/apps/gnome-characters/default.nix b/pkgs/desktops/gnome-3/apps/gnome-characters/default.nix
index a354c4f631..e04602bb95 100644
--- a/pkgs/desktops/gnome-3/apps/gnome-characters/default.nix
+++ b/pkgs/desktops/gnome-3/apps/gnome-characters/default.nix
@@ -10,6 +10,14 @@ stdenv.mkDerivation rec {
     librsvg gnome3.gsettings_desktop_schemas gnome3.defaultIconTheme
   ];
 
+  postFixup = ''
+    for f in "$out/share/org.gnome.Characters/org.gnome.Characters" \
+      "$out/share/org.gnome.Characters/org.gnome.Characters.BackgroundService"
+    do
+      wrapProgram "$f" "''${gappsWrapperArgs[@]}"
+    done
+  '';
+
   meta = with stdenv.lib; {
     homepage = https://wiki.gnome.org/Design/Apps/CharacterMap;
     description = "Simple utility application to find and insert unusual characters";
```

I think this works.  I've tested by running the dbus service files myself.

I don't know how to test with gnome-shell.  Gnome-shell seems to require the package to be installed system wide; probably because dbus is a system wide thing (relying tje `.service` files the system environment).

I'd be interested in opinions for this approach.

**Comment by jtojnar** [comment]
Hmm, it was polari after all, I had to modify wrapGAppsHook for it (https://github.com/NixOS/nixpkgs/pull/27320/files#diff-c90743a6f7cfce0259c1e97010a37bdb). [This](https://gitlab.gnome.org/GNOME/polari/commit/f5dce05bb32b4409b32ff18ab5b7a71d27a02bfd) is how they fixed it, maybe we can convince GNOME Characters to do the same.

**Comment by jtojnar** [comment]
Opened an upstream issue: https://gitlab.gnome.org/GNOME/gnome-characters/issues/29
