### ISSUE TITLE
Disabled `users.mutableUsers` conflicts with mutable overlay-based `/etc`

### ISSUE THREAD

**Issue by ivan770** [NixOS/nixpkgs#311665]
### Describe the bug

The following assertion triggers in a configuration where `users.mutableUsers = false;` and `system.etc.overlay.mutable = true;`:

https://github.com/NixOS/nixpkgs/blob/ee188fbed47ca12a726091b2b87d35fa01b95fe2/nixos/modules/system/etc/etc-activation.nix#L29-L35

It should be possible to have a mutable `/etc` while using static `systemd-sysusers` configuration at the same time.

### Steps To Reproduce
1. Set `users.mutableUsers` to `false`
2. Set `system.etc.overlay.mutable` to `true`
3. Build the system

### Expected behavior
The build succeeds.

### Notify maintainers

From `git blame`: @nikstur 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240513.cbd6db0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nikstur** [comment]
This cannot be done with the current implementation.
