### ISSUE TITLE
cdemu: not mounting images

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#311690]
### Describe the bug

cdemu is not mounting images

### Steps To Reproduce
1. Install cdemu with `programs.cdemu.enable`, rebuild
2. Attempt to mount an image either manually or cdemu-daemon/cdemu GUI like gCDEmu
3. It fails to mount
4. Manually run `cdemu` and receive error:
```
Traceback (most recent call last):
  File "/nix/store/33zk628s8rpb19inv5y12ai0dvn196py-cdemu-client-3.2.5/bin/.cdemu-wrapped", line 33, in <module>
    from gi.repository import GLib
  File "/nix/store/9njwgmbs7jlpsrnnr731k2vv5xqghqr4-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
```
### Expected behavior
cdemu mounts the image

### Additional context
vhba module is loaded

### Notify maintainers

@bendlas 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240512.2057814`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bendlas** [comment]
I think updating the userland programs to use `wrapGAppsHook` and `wrapGAppsNoGuiHook` respectively, should resolve the issue.
