### ISSUE TITLE
Curious nix version-dependent evaluation problem

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#31179]
On my other Arch machine (still) running Nix 1.11.7, running `nix-env -f . -qaP > /dev/null` gives:
````
error: syntax error, unexpected $undefined, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE, at /home/tmtynkky/opt/nixpkgs/pkgs/os-specific/linux/bcc/default.nix:29:27
````
1.11.15 is fine with that file.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.53-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.7`
 - channels(tmtynkky): `"nixpkgs-18.03pre119009.6d1317ab31"`
 - nixpkgs: `/home/tmtynkky/.nix-defexpr/channels/nixpkgs`

**Comment by orivej** [comment]
It's interesting that you've decided to fix it :) The same issue was reported in #30834.

**Comment by orivej** [comment]
I've checked that `bcc` in stable is not affected and your fix does not have to be backported.

**Comment by ScottFreeCode** [comment]
> I've checked that `bcc` in stable is not affected

For what it's worth, I believe Mac is (or was when I installed it) on an unstable channel by default.
