### ISSUE TITLE
`sourceRoot` requires specifing the base directory?

### ISSUE THREAD

**Issue by dpc** [NixOS/nixpkgs#31172]
## Issue description

When using `sourceRoot` that isn't `.`, some weird things are happening.

### Steps to reproduce

I have a project split between three subdirs. `web/`, `cli/` and `api-common/`.

In the `web/` I'm trying to build the `web` part from `web/` and `api-common/`.

For this to work I have to change `sourceRoot`.

If I do:

```
[futex:web]$ ls ..
api-common  cli  web
[futex:web]$ cat default.nix 
{ pkgs ? (import <nixpkgs> {})}:

pkgs.rustPlatform.buildRustPackage rec {
  name = "hackeraudit-web-${version}";
  version = "HEAD";

  src = builtins.filterSource (p: t:
      pkgs.lib.cleanSourceFilter p t &&
      baseNameOf p != "target" &&
      baseNameOf p != "rusty-tags.vi" &&
      (
       (builtins.match ".*/web.*" p != null) ||
       (builtins.match ".*/api-common.*" p != null)
      )
  )  ./.. ;

  sourceRoot = "web";

  cargoSha256 = "139q1bkw0fmha3iq7vj5cihdhg1in8j1qhy42p73g8728g6iz5wx";
}
```

This fails with:

```
[futex:web]$ nix-build
(...)
unpacking source archive /nix/store/67468bhm9izavllk4rzh9n1rg36igzlc-hackeraudit
source root is ./web
chmod: cannot access './web': No such file or directory
builder for ‘/nix/store/x5y3nwn60gbip99d7diz41a8japmq0lq-hackeraudit-web-HEAD-vendor.drv’ failed with exit code 1
error: build of ‘/nix/store/x5y3nwn60gbip99d7diz41a8japmq0lq-hackeraudit-web-HEAD-vendor.drv’ failed
```

After analyzing `strace -efile -ff -yy -v -s 128 nix-build`, I've discovered that for whatever reason, what I acutally have to use is:

`sourceRoot = "hackeraudit/web";`

as the CWD of `chmod ./web` when fails is `/tmp/nix-build-hackeraudit-web-HEAD-vendor.drv-0/`, but the directory I intended to `sourceRoot` is actually `/tmp/nix-build-hackeraudit-web-HEAD-vendor.drv-0/hackeraudit/web` , and not `/tmp/nix-build-hackeraudit-web-HEAD-vendor.drv-0/web` as I would expect it.

I don't understand it, because `hackeraudit` is the name of directory that `web/`, `cli/` and `api-common/` are inside, and I did not use it anywhere else, I belive.

I think this issue was already reported once: https://github.com/NixOS/nixpkgs/issues/15495

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix
```

* Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.15
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"18.03pre119029.26e4f6f4f8"
```

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

```
$ grep build-use-sandbox /etc/nix/nix.conf
grep: /etc/nix/nix.conf: No such file or directory
```

**Comment by orivej** [comment]
@dpc The default source root is not empty or `.`, it is the sole directory in the build directory. So when you use `./..` as your `src` and want to remain in the current directory, your `sourceRoot` will contain two parts, `parent-dir/current-dir`.

**Comment by dpc** [comment]
@orivej I don't understand. So what should I use in my case instead of `"hackeraudit/web"`, if I don't want to use the `hackeraudit` part?

**Comment by dpc** [comment]
Hmmm... So you're saying that the parent directory is always used? Seems like an odd choice, to consider the owning directory name a part of the build, when only the content of it is important...

**Comment by orivej** [comment]
Yes, so @edolstra decided to use the string `"source"` instead of the directory name for the base name of paths (such as `./.`, `../.` , `../something` etc). This will be in Nix 1.12. In your case `sourceRoot = "hackeraudit/web"` will become `sourceRoot = "source/web"`. You can use `setSourceRoot` to be compatible with both versions: https://github.com/NixOS/nixpkgs/pull/31106#issuecomment-341284252

**Comment by dpc** [comment]
Is there any real need for `source` to be there at all? I just don't see why everything under `src` doesn't land directly in `/tmp/something-something-build-directory/`, and default `sourceRoot` isn't `.`.

**Comment by orivej** [comment]
I suppose that this is for consistency and simplicity of the [implementation](https://github.com/NixOS/nixpkgs/blob/cfafd6f5a819472911eaf2650b50a62f0c143e3e/pkgs/stdenv/generic/setup.sh#L635): some packages have multiple `srcs`, some `src`s are files rather than directories. Currently they are all copied or unpacked into the build directory, and then if it contains just one directory, it is selected as the default `sourceRoot`, otherwise you have to specify it manually.

**Comment by Ralith** [comment]
It's useful to have the sources in a subdir, because then you don't have to worry about intermediate products colliding with source file names.

**Comment by FlorianFranzen** [comment]
I think it would be worth documenting the fact that you will have to use ```"source"``` in ```sourceRoot``` to specify a relative path. Right now the documentation only states:

    After running unpackPhase, the generic builder changes the current directory to the
    directory created by unpacking the sources. If there are multiple source directories, 
    you should set sourceRoot to the name of the intended directory. 
    Alternatively to setting sourceRoot, you can set setSourceRoot to a shell command 
    to be evaluated by the unpack phase after the sources have been unpacked. This 
    command must set sourceRoot.

**Comment by fricklerhandwerk** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/189566
