### ISSUE TITLE
are the default arguments for the module system broken?

### ISSUE THREAD

**Issue by name-snrl** [NixOS/nixpkgs#311709]
@infinisil @roberth Hi guys, sorry to bother you, but I need help from people who understand quite well how the modular system works.

I recently started using `home-manager` and I wanted to have different values in the configuration when it is part of the NixOS module and when it is created using `homeManagerConfiguration`. My first attempt looked like this:

```nix
{ nixosConfig ? null, ... }:
let
  isNixos = nixosConfig == null;
in
{ # cfg }
```

But when I tried to evaluate the configuration using `homeManagerConfiguration`, I got the following error:

```
       error: attribute 'nixosConfig' missing

       at /nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source/lib/modules.nix:508:28:

          507|         builtins.addErrorContext (context name)
          508|           (args.${name} or config._module.args.${name})
             |                            ^
          509|       ) (lib.functionArgs f);
```

After some investigation, I found a workaround:

```nix
{ lib, config, ... }@args:
let
  isNixos = args ? nixosConfig;
  inherit (args) nixosConfig;
in
{ # cfg }
```

I got the desired result, but I'm left with the feeling that the default arguments should be available inside the module system as well. I've tried to figure things out on my own, but I lack expertise. I don't understand what "strict manner" means in the comment for `applyModuleArgs`.

https://github.com/NixOS/nixpkgs/blob/f11fb1528779fb2932b27a82e946a1e8d3e36f64/lib/modules.nix#L491-L515

Getting to the point, my suggestion and question boils down to this: shouldn't we add a check inside `applyModuleArgs` like the one that happens inside `callPackageWith`?

When we check if the requested arguments are a subset of all available arguments (including default arguments):

https://github.com/NixOS/nixpkgs/blob/f11fb1528779fb2932b27a82e946a1e8d3e36f64/lib/customisation.nix#L221-L227

**Comment by roberth** [comment]
Default argument support has been attempted, but appears to be impossible to implement for the time being.
Also it's an open question how default arguments and option defaults should interact, or whether they should coexist at all. (note that `_module.args` supports priorities like `mkDefault` just like any other option)

See
- https://github.com/NixOS/nixpkgs/pull/240436
