### ISSUE TITLE
Update request: fusuma OLDVERSION → NEWVERSION

### ISSUE THREAD

**Issue by lVentus** [NixOS/nixpkgs#311882]
- Package name: fusuma
- Latest released version: 3.5.0

- Current version on the unstable channel: 3.3.1
- Current version on the stable/release channel: 3.3.1

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].
By the way, fusuma now use yml file instead of yaml file as config file.
now when I use HM service.fusuma.settings, it will generate a yaml file in .config, please update it to change it to a yml file.
and when I use service.fusuma.enable = true; it wont be installed.

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luftmensch-luftmensch** [comment]
>  By the way, fusuma now use yml file instead of yaml file as config file. now when I use HM service.fusuma.settings, it will generate a yaml file in .config, please update it to change it to a yml file. and when I use service.fusuma.enable = true; it wont be installed.

I guess that this should be addressed at home-manager repository as nixpkgs does not offer a fusuma service, as far as I rembember

**Comment by lVentus** [comment]
> > By the way, fusuma now use yml file instead of yaml file as config file. now when I use HM service.fusuma.settings, it will generate a yaml file in .config, please update it to change it to a yml file. and when I use service.fusuma.enable = true; it wont be installed.
> 
> I guess that this should be addressed at home-manager repository as nixpkgs does not offer a fusuma service, as far as I rembember

you are right

**Comment by lVentus** [comment]
> Already fixed in home-manager: [nix-community/home-manager#5049](https://github.com/nix-community/home-manager/pull/5049)

sorry, I don't understand. if it has been fixed, why I still have the same issue? I just installed yesterday.

**Comment by JohnRTitor** [comment]
Are you perhaps not on `nixos-unstable`?

**Comment by lVentus** [comment]
> Are you perhaps not on `nixos-unstable`?

ah, right. I use stable nixos and HM, install some new software with pkgs-unstable. But this is a service, how do I change the package to unstable version? I tried services.fusuma.package = pkgs-unstable.fusuma.
But the result is still same.

**Comment by JohnRTitor** [comment]
It's fixed on master branch of Home Manager and not have been backported to release-23.11.

Home manager master always follows the NixOS unstable branch, so I won't suggest switching to master branch of HM unless you upgrade your system to nixos-unstable.
