### ISSUE TITLE
systemd-repart broken when emulating aarch64

### ISSUE THREAD

**Issue by danielbarter** [NixOS/nixpkgs#311978]
### Describe the bug

The appliance image example from https://nixos.org/manual/nixos/stable/#sec-image-repart seems to be broken on `aarch64`. 

### Steps To Reproduce

```
# appliance_image.nix
let
  pkgs = import <nixpkgs> { system = "aarch64-linux"; };
  efiArch = pkgs.stdenv.hostPlatform.efiArch;
in
(pkgs.nixos [
  ({ config, lib, pkgs, modulesPath, ... }: {

    imports = [ "${modulesPath}/image/repart.nix" ];

    boot.loader.grub.enable = false;

    fileSystems."/".device = "/dev/disk/by-label/nixos";

    image.repart = {
      name = "image";
      partitions = {
        "esp" = {
          contents = {
            "/EFI/BOOT/BOOT${lib.toUpper efiArch}.EFI".source =
              "${pkgs.systemd}/lib/systemd/boot/efi/systemd-boot${efiArch}.efi";

            "/loader/entries/nixos.conf".source = pkgs.writeText "nixos.conf" ''
              title NixOS
              linux /EFI/nixos/kernel.efi
              initrd /EFI/nixos/initrd.efi
              options init=${config.system.build.toplevel}/init ${toString config.boot.kernelParams}
            '';

            "/EFI/nixos/kernel.efi".source =
              "${config.boot.kernelPackages.kernel}/${config.system.boot.loader.kernelFile}";

            "/EFI/nixos/initrd.efi".source =
              "${config.system.build.initialRamdisk}/${config.system.boot.loader.initrdFile}";
          };
          repartConfig = {
            Type = "esp";
            Format = "vfat";
            SizeMinBytes = "96M";
          };
        };
        "root" = {
          storePaths = [ config.system.build.toplevel ];
          repartConfig = {
            Type = "root";
            Format = "ext4";
            Label = "nixos";
            Minimize = "guess";
          };
        };
      };
    };

  })
]).image

```
EDIT: working on native `aarch64-linux` but not on a system with binfmt emulation.

`nix-build appliance_image.nix` on a system with   `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` produces the following error message:

```
structuredAttrs is enabled
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
'repart.d' -> '/build/amended-repart.d'
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Building image with systemd-repart...
unshare: unshare failed: Invalid argument
```

### Expected behavior
A disk image should be built

### Notify maintainers

@nikstur @WilliButz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240511.062ca2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/pfc56yr7y3wflvbgnrpscf2n1m4j3xd7-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by WilliButz** [comment]
> nix-build appliance_image.nix on a aarch64-linux system or on a system with boot.binfmt.emulatedSystems = [ "aarch64-linux" ]; produces the following error message:

It doesn't work using binfmt emulation. But I'm unable to produce a build failure on a native aarch64-linux build host. Can you confirm that you also ran into this on a native aarch64-linux host?

I used the current nixos-unstable to realise your expression:
```
nix-build -I nixpkgs=https://github.com/nixos/nixpkgs/archive/205781405197.tar.gz appliance_image.nix
```

**Comment by danielbarter** [comment]
@WilliButz: you are right. I thought I tried it SSHd into an aarch64 machine, but I was mistaken. Works on a native aarch64-linux host for me.

**Comment by danielbarter** [comment]
I have a bit of time now, so will see if I can debug

**Comment by danielbarter** [comment]
OK, the problematic command is 
```
unshare --map-root-user fakeroot systemd-repart --architecture=arm64 image.raw
```

here is the strace:

https://gist.github.com/danielbarter/a44e575d73c77fbd7a91dd88af30e4f2

**Comment by danielbarter** [comment]
https://gitlab.com/qemu-project/qemu/-/issues/871 seems like the relevent qemu issue

**Comment by danielbarter** [comment]
OK, so I can solve the initial problem which led me to this bug using cross compiling, which seems to work (but requires a lot of building). Will leave open, but this needs to be fixed in qemu.

**Comment by danielbarter** [comment]
fix here:

https://github.com/NixOS/nixpkgs/pull/314890

**Comment by Henry-Hiles** [comment]
Looks like this issue is back, due to now both `fakeroot` and `unshare` being used: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/image/repart-image.nix#L206

**Comment by Henry-Hiles** [comment]
Looks like breaking it was intentional... https://github.com/NixOS/nixpkgs/pull/378579
