### ISSUE TITLE
Tor browser update fails

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#31190]
Hi,

Tor browser can not update. I get this error:

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dist.torproject.org:443 
error: cannot download tor-browser-linux64-7.0.8_en-US.tar.xz from any mirror
builder for ‘/nix/store/pglrsqd9qvvv6ngxa27n5q0294wq7mac-tor-browser-linux64-7.0.8_en-US.tar.xz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/4bl780jff14nvm4walsiyrv8jr697asa-tor-browser-bundle-bin-7.0.8.drv’: 1 dependencies couldn't be built

I live in turkey. I think they blocked something again...

Thank you

**Comment by joachifm** [comment]
Hi,

Unfortunately, the primary github mirror is slow to update. I had hoped it would stay current, as I think the cost of blocking github is somewhat higher than blocking the other public mirrors.

In the interim you can do e.g.,

```sh
nix-prefetch-url https://tor.ybti.net/dist/torbrowser/7.0.9/tor-browser-linux64-7.0.9_en-US.tar.xz
```

You can send a blank email to gettor@torproject.org to get alternative download urls, which you can then substitute into the command above.

**Comment by joachifm** [comment]
There's also https://twitter.com/get_tor
