### ISSUE TITLE
error: attribute 'inputs' missing.

### ISSUE THREAD

**Issue by lVentus** [NixOS/nixpkgs#312026]
## Platform

surface pro 8
- [x] Linux: 

## Additional information
I try to install hyprland plugins in HM, the instruction is:

wayland.windowManager.hyprland.plugins = [
  inputs.hyprland-plugins.packages.${pkgs.system}.hyprbars
];
I get the
 error : attribute 'inputs' missing.

But I have passed the inputs to HM:

modules = [   
          ./hosts/surface

          nixos-hardware.nixosModules.microsoft-surface-pro-intel

          home-manager.nixosModules.home-manager {

            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.extraSpecialArgs = inputs;
	    
            home-manager.users.ventus = import ./home;
          }
        ];

it doesn't work. 
and then I tried to add these inputs manualy:

{pkgs, inputs, lib, hyprland-plugins, hyprgrass, ...}:

then it is the new error:

## Output

<details><summary>Output</summary>

```log


-- Setting precompiled headers
-- Setting link libraries
Could not open input file: No such file or directory
Could not open input file: No such file or directory
Could not open input file: No such file or directory
Could not open input file: No such file or directory
Couldn't load proto
-- Checking for module 'tomlplusplus'
--   Found tomlplusplus, version 3.4.0
-- Configuring incomplete, errors occurred!
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by V3ntus** [comment]
Hey, I had this same issue as you where I tried to pass `inputs` to `extraSpecialArgs`. This comment helped though: https://github.com/nix-community/home-manager/issues/1698#issuecomment-832545025

Basically, instead of passing `inputs` broadly, just inherit the specific inputs you would like:
```nix
{
	inputs = {
		apple-fonts = { #... };
	};
	outputs = {self, nixpkgs, home-manager, apple-fonts, ...} @ inputs: nixosConfigurations = {
		user = nixpkgs.lib.nixosSystem {
			modules = [
				home-manager.nixosModules.home-manager {
					home-manager.extraSpecialArgs = {inherit apple-fonts};
				}
			];
		};
	};
}
```

**Comment by Aleksanaa** [comment]
Sorry, this seems to be a skill issue, not an issue with nixpkgs or home-manager. In short, `specialArgs` in `inputs.nixpkgs.lib.nixosSystem` defines which arguments you want to pass to each separated modules. You may need something like

```nix
{
	inputs = {
		nixpkgs.url = "...";
		home-manager.url = "...";
	};

	outputs = inputs: {
		nixosConfigurations = {
			nixos-machine = inputs.nixpkgs.lib.nixosSystem {
				system = "x86_64-linux";
				# ...
				specialArgs = {
					inherit inputs;
				};
			};
		};
	};
}
```

So you can write

```nix
{ inputs, ... }:

{
	# ...
}
```

in modules.

It is worth noting that here or the nix repo issues are not very suitable places to ask questions. You can go to https://discourse.nixos.org or https://matrix.to/#/#users:nixos.org to get more help.
