### ISSUE TITLE
programs.firefox.languagePacks option is broken

### ISSUE THREAD

**Issue by jcaesar** [NixOS/nixpkgs#312098]
### Describe the bug
Setting `programs.firefox.languagePacks` causes
```plain
       at /nix/store/b1qqk0vlygqjq3k0vwfmwpz7v6n2xywb-source/nixos/modules/programs/firefox.nix:290:16:

          289|       ExtensionSettings = builtins.listToAttrs (builtins.map
          290|         (lang: builtins.nameValuePair
             |                ^
          291|           "langpack-${lang}@firefox.mozilla.org"
```

### Steps To Reproduce
```bash
nix build -vL --no-link --expr 'let
  nixpkgs = builtins.getFlake "github:nixos/nixpkgs/e243ea85ce6f1d945723bb0003a1fb1a6ed1dbf6";
  sys = nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";
    modules = [
      (
        { ... }:
        {
          programs.firefox = {
            enable = true;
            languagePacks = [ "de" ];
          };
        }
      )
    ];
  };
in sys.config.system.build.etc'
```

### Expected behavior
Builds a Firefox config with language packs as it did e.g. on `951e02301002a3100bf102bfb05272611633932e`.

### Additional context
This seems trivial to fix, but there are many more instances of `builtins.nameValuePair` in nixpkgs, so I'm unsure how to handle those.

### Notify maintainers

@danth

### Metadata

```console
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), j_9093184_20240508005535`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/wmcbdvplkli110vmdn1ci96n8zmzh7yn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
What do you mean by "many more instances"? I only see one: https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20builtins.nameValuePair%20&type=code

It was broken in #304773

**Comment by jcaesar** [comment]
> What do you mean by "many more instances"? 

Oops, sorry. It seems I grepped through the wrong folder before saying that.

PR with fix submitted.
