### ISSUE TITLE
Build failure: python3Packages.chromadb

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#312068]
### Steps To Reproduce

1. build `python3Packages.chromadb` on aarch64-linux (tested on Oracle Cloud, EC2, and hydra.nixos.org)

### Build log

https://hydra.nixos.org/build/259926073/nixlog/1/tail

```
Executing pythonImportsCheckPhase
Check whether the following modules can be imported: chromadb
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
terminate called after throwing an instance of 'onnxruntime::OnnxRuntimeException'
  what():  /build/source/include/onnxruntime/core/common/logging/logging.h:294 static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger() Attempt to use DefaultLogger but none has been registered.

/nix/store/gxnz43gxk3bmkpcirs1h42paa7pvrfa4-python-imports-check-hook.sh/nix-support/setup-hook: line 10:  1127 Aborted                 (core dumped) /nix/store/4x92cw7ahfrydbkvy2046y1ajh5h96wv-python3-3.12.3/bin/python3.12 -c 'import os; import importlib; list(map(lambda mod: importlib.import_module(mod), os.environ["pythonImportsCheck"].split()))'
```

### Additional context

First reported [here](https://github.com/NixOS/nixpkgs/pull/310557#issuecomment-2104605586).

### Notify maintainers

@fabaff

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hacker1024** [comment]
https://github.com/microsoft/onnxruntime/issues/10038

**Comment by fabaff** [comment]
I don't have unrestricted access to an aarch64 build system other than the community builder, thus making chromadb work on other platforms than x86_64 will depend on support from a person which can get their hand on an aarch64 system.

**Comment by volfyd** [comment]
This is similar to https://github.com/microsoft/onnxruntime/issues/10038 . Perhaps onnxruntime cannot access  /sys/devices/system/cpu/possible in the build environment, and this causes chromadb to fail to import during the build of chromadb.

**Comment by volfyd** [comment]
See also https://github.com/NixOS/nixpkgs/pull/319053 . There is a discussion

> IMHO, we should disable [onnxruntime_ENABLE_CPUINFO](https://github.com/microsoft/onnxruntime/blob/983fd8393aa30b0c788275ea6e513a614274e1ba/cmake/CMakeLists.txt#L229) on aarch64. Anyone has another opinion?

but I don't think that was actually tried.

For the time being, this overlay works on nixpkgs-unstable to get open-webui working. The cpuinfo code doesn't work in the build environment, but it does work outside the build environment (I think) and so this overlay will let you skip the checks.
```
  try-two = _: prev: {
    pythonPackagesExtensions =
      prev.pythonPackagesExtensions
      ++ [
        (
          _: python-prev: {
            rapidocr-onnxruntime = python-prev.rapidocr-onnxruntime.overridePythonAttrs (self: {
              pythonImportsCheck = [];
              doCheck = false;
              meta = self.meta // {broken = false;};
            });
            chromadb = python-prev.chromadb.overridePythonAttrs (self: {
              pythonImportsCheck = [];
              doCheck = false;
              meta = self.meta // {broken = false;};
            });
            langchain-chroma = python-prev.langchain-chroma.overridePythonAttrs (_: {
              pythonImportsCheck = [];
              doCheck = false;
            });
          }
        )
      ];
  };
```
