### ISSUE TITLE
services.xserver.windowManager.default Always Prepending "none+"

### ISSUE THREAD

**Issue by crftbt** [NixOS/nixpkgs#312027]
### Describe the bug
When configuring services.xserver.windowManager.default, none+ appears to always be prepended.

### Steps To Reproduce
1. Edit /etc/nixos/configuration.nix and add: services.xserver.windowManager.default = "lxqt+metacity";
2. sudo nixos-rebuild switch.
3. Error presents itself "none+lxqt+metacity".

### Expected behavior
Expecting lxqt+metacity, receiving "none+lxqt+metacity"

### Metadata
- system: `"x86_64-linux"`
- host os: `Linux 6.1.88, NixOS, 23.11 (Tapir), 23.11.6759.0638fe2715d9`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.1`
- nixpkgs `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
That's not how the option is meant to be used.

Either use:

```nix
services.xserver = {
  desktopManager.default = "lxqt";
  windowManager.default = "metacity";
```


Or, since those options are deprecated anyway (which you should've gotten a warning about already), use

```nix
services.xserver.displayManager.defaultSession = "lxqt+metacity";
```

as the warning tells you to.
