### ISSUE TITLE
claws-mail: missing icons

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#312138]
### Describe the bug

Icons disappeared from the claws-mail interface.

### Steps To Reproduce

Open claws-mail

### Expected behavior

Icons should appear, at least where there is no text to replace them.

### Screenshots

![20240516_08h34m44s_grim](https://github.com/NixOS/nixpkgs/assets/8182846/473919fa-43d9-477d-a64e-d7a773da2174)
![20240516_08h34m24s_grim](https://github.com/NixOS/nixpkgs/assets/8182846/483eb078-c16c-426e-8b4f-01d02432bbba)
![20240516_08h34m09s_grim](https://github.com/NixOS/nixpkgs/assets/8182846/80de87ab-b4ee-4c3b-9716-d4dd332b4e6f)
![20240516_08h33m46s_grim](https://github.com/NixOS/nixpkgs/assets/8182846/fdc950c5-babb-4c72-94a1-069a1c61ddfb)

### Additional context

I'm running it under `sway`.

This happened after my last channel update, so it seems to be recent.

### Notify maintainers

@fpletz @globin @orivej @oxzi @ajs124 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05pre624623.062ca2a9370a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/home/fgaz/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fgaz** [comment]
I just hydra-bisected this, and it seems to have happened between https://hydra.nixos.org/build/257121810 (69ee1d82f1fa4c70a3dc9a64111e7eef3b8e4527) and https://hydra.nixos.org/build/258317387 (5fd8536a9a5932d4ae8de52b7dc08d92041237fc)

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/pull/308976#issuecomment-2094961682 sounds similar? `gdk-pixbuf` update should fix it.

**Comment by fgaz** [comment]
Yup, seems like #308976 fixed it
