### ISSUE TITLE
Package request: pnpm v9

### ISSUE THREAD

**Issue by attente** [NixOS/nixpkgs#312134]
**Project description**

pnpm: Fast, disk space efficient package manager

Latest release is https://github.com/pnpm/pnpm/releases/tag/v9.1.1 (2024-05-12).

**Metadata**

* homepage URL: https://pnpm.io/
* source URL: https://github.com/pnpm/pnpm
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
https://github.com/NixOS/nixpkgs/pull/305026

**Comment by SuperSandro2000** [comment]
Added in the PR that added fetchNpm
