### ISSUE TITLE
Kana: incorrect license

### ISSUE THREAD

**Issue by ASHGOLDOFFICIAL** [NixOS/nixpkgs#312176]
## Problem

[Kana](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ka/kana/package.nix) package has `gpl3Only` not `gpl3Plus` ([link](https://gitlab.gnome.org/fkinoshita/kana/-/blob/v1.4/COPYING)). At least the link says so, I'm not sure.

Edit: [`meson.build`](https://gitlab.gnome.org/fkinoshita/kana/-/blob/v1.4/meson.build) says the license is `gpl3Plus`. So I'm not at all sure now. I think the issue can be solved and redirected to the developer for them to solve this license inconsistency.

## Checklist 

- [x] checked [source][nixpkgs-source]
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ASHGOLDOFFICIAL** [comment]
So, as I said in the edit section, situation with the license is unclear. I'm trying to package another app from this developer, and it has the same problem with license, so I would like to know what license should I put in `meta`.

**Comment by wegank** [comment]
The [source code](https://gitlab.gnome.org/fkinoshita/kana/-/blob/v1.4/src/main.rs#L18) says `GPL-3.0-or-later`, I trust it more than some auto-detections on GitLab.

**Comment by ASHGOLDOFFICIAL** [comment]
> The [source code](https://gitlab.gnome.org/fkinoshita/kana/-/blob/v1.4/src/main.rs#L18) says `GPL-3.0-or-later`, I trust it more than some auto-detections on GitLab.

Oh, I see, thanks. I think mentioning "or-later" in source code makes it `gpl3Plus` without doubt. I'll close the issue.
