### ISSUE TITLE
Incus containers nor VMs have networking

### ISSUE THREAD

**Issue by freekvh** [NixOS/nixpkgs#312229]
### Describe the bug
Creating incus container or VMs works but they can't access the internet

### Steps To Reproduce
1. Install incus according to instructions: https://linuxcontainers.org/incus/docs/main/installing/ (click NixOS)
2. Start an Ubuntu 24.04 VM: `incus launch images:ubuntu/24.04 ubuntu-2404 --vm`
3. Enter the VM: `incus exec ubuntu-2404 -- bash`
4. Ping google `ping google.com`
5. See result: `ping: google.com: Temporary failure in name resolution`

### Expected behavior
There is no network connection, no IPv4 address, I expect to be able to ping other machines

### Additional context
The problem is descibed in the Incus repo here but the conclusion is that there is something NixOS specific that is not working: https://github.com/lxc/incus/issues/525

### Notify maintainers

@aanderse
@adamcstephens
@jnsgruk
@megheaiulian
@mkg20001

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.90, NixOS, 23.11 (Tapir), 23.11.7122.9ddcaffecdf0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Did you add a network to incus, either manually or through preseed?

**Comment by freekvh** [comment]
Also, doing this:

```
incus network attach wlp0s20f3 ubuntu-2404 eth0
```

Should offer my wifi connection inside the VM as eth0, right? But it does not show up in the VM:

```
[freek@nixos:~]$ incus exec ubuntu-2404 -- bash
root@ubuntu-2404:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:f0:0e:3f brd ff:ff:ff:ff:ff:ff
    inet6 2001:4c3c:5203:d900:216:3eff:fef0:e3f/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 7174sec preferred_lft 7174sec
    inet6 fe80::216:3eff:fef0:e3f/64 scope link 
       valid_lft forever preferred_lft forever
3: enp6s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:3e:8c:72:5a brd ff:ff:ff:ff:ff:ff
```

**Comment by adamcstephens** [comment]
Did you add your incus network interface (eg `incusbr0`) to `networking.firewall.trustedInterfaces` ? If not the dhcp requests are likely being blocked by the host firewall.

VMs don’t use the eth0 naming, so the wireless interface is probably the enp6s0.

**Comment by freekvh** [comment]
I have added `networking.firewall.trustedInterfaces = ["incusbr0"];` to my configuration.nix but still no network inside the VM. I have followed the instructions as given here so far: 

It seems like there are many more people with issues, some say it's related to docker:

* https://discourse.nixos.org/t/starting-incus-container-results-in-no-network-inside-the-container/40155
* poster earlier: https://github.com/lxc/incus/issues/525

I have done the manual initialization (in instructions here https://linuxcontainers.org/incus/docs/main/installing/), perhaps I should try the NixOS build-in one.

**Comment by freekvh** [comment]
Ok, I  tried the NixOS preseed, it doesn't change anything.

**Comment by adamcstephens** [comment]
Your original post indicates you're on 23.11. If so, can you try using unstable on the host?

**Comment by freekvh** [comment]
Ok, I got it working, I messed about to much perhaps with the networks, but deleting and recreating the ubuntu VM gives me working networking. I may well have been the `networking.firewall.trustedInterfaces = ["incusbr0"];` step indeed. It could also be using the NixOS standard see instead of manual `incus admin init`.

Thanx for the help!`

**Comment by adamcstephens** [comment]
Awesome, glad you got it working.

Init or preseed are required to configure a network. The firewall does need to be open too, but we can't assume the interface will actually be `incusbr0` in all cases so it is a manual addition to your config.

**Comment by Piotr1215** [comment]
Had a very similar issue on `pop-os` in case anyone will stumble on this in the future. As @adamcstephens stated. 
> Did you add your incus network interface (eg incusbr0) to networking.firewall.trustedInterfaces ? If not the dhcp requests are likely being blocked by the host firewall.

I use `ufw` and had to make this to get the internet working: `sudo ufw allow in on incusbr0`
