### ISSUE TITLE
zed-editor: Bus error (core dumped)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#312266]
### Describe the bug

When i start zed-editor from nixpkgs unstable, i get this window and few seconds later, the program crashes.

![Screenshot from 2024-05-16 19 11 00](https://github.com/NixOS/nixpkgs/assets/91113/80a7c63a-5b7d-4d7d-b08a-21039c004cad)

### Steps To Reproduce
1. `nix-shell -I nixpkgs=channel:nixos-unstable -p zed-editor`
2. `zed`
3.  >Bus error (core dumped)

### Expected behavior
Usable program, not crash.

### Additional context

Full terminal output:

```
[nix-shell:~]$ zed 
[2024-05-16T19:09:28+02:00 ERROR util] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-05-16T19:09:28+02:00 ERROR util] crates/zed/src/zed.rs:661: EOF while parsing a value at line 1 column 0
[2024-05-16T19:09:28+02:00 ERROR util] crates/zed/src/main.rs:848: Is a directory (os error 21)
[2024-05-16 19:09:28.622] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'io_stats'
[2024-05-16T19:09:31+02:00 ERROR auto_update] auto-update failed: error:error deserializing release

Caused by:
    expected value at line 1 column 1
Bus error (core dumped)
```

Package has version 0.134.4 and a new version was released yesterday. Maybe the updates changes something.

### Notify maintainers

@GaetanLepage

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 23.11 (Tapir), 23.11.7016.8be0d8a1ed4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
Hmm weird because I made sure to test it before submitting the latest update.
For me it still works fine:
![image](https://github.com/NixOS/nixpkgs/assets/33058747/f0c15d34-ba10-436a-bac4-f78f0e1c0fe2)

What display server / desktop environment are you running ?

**Comment by tv42** [comment]
The error message seems to imply it failed trying to parse your `~/.config/zed/settings.json`. Maybe make sure that file exists and is valid JSON, to work around it?

**Comment by tv42** [comment]
It also complains about parsing the auto-update response (which is unwanted on Nix anyway).

`[2024-05-16T19:09:31+02:00 ERROR auto_update] auto-update failed: error:error deserializing release`. I have this (and more) in settings.json to disable a bunch of phone-home behavior:

```json
{
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "server_url": "https://disable-stupid-crap.zed.invalid",
  "auto_update": false,
}
```

**Comment by davidak** [comment]
> For me it still works fine

Now it also works for me. In nixos-unstable and master i get the version 0.135.2 now. So it look like the version 0.134.4 had this issue.

Thanks for maintaining the package!

**Comment by MangoIV** [comment]
for me it opens but then it blocks many seconds until I can actually open a folder...

**Comment by lebensterben** [comment]
For me it doesn't open and there's no error message...
`zed-editor` does appear in running processes.
And running `zed --foreground` again says it's already running.
But it shows no command line output/error, nor any GUI window.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```
