### ISSUE TITLE
webcord-vencord: Hang and segmentation fault on startup.

### ISSUE THREAD

**Issue by YaroKasear** [NixOS/nixpkgs#312208]
### Describe the bug
Under Wayland on Hyprland, trying to launch Webcord results in a frozen window and then a crash on startup. It doesn't matter if I launch using Ozone flags ```--enable-features=UseOzonePlatform --ozone-platform=wayland``` or not.

Vanilla Discord package launches without issue. I did not test if Webcord launches under Xorg.

### Steps To Reproduce
1. Use launcher or shell to launch Webcord
2. Watch it crash instead of starting properly.

### Expected behavior
Webcord launches and works fine. 

### Additional context
I am using Hyprland's upstream flake. However, I don't see why that might be relevant, but it might be worth mentioning. 

### Notify maintainers

@FlafyDev
@NotAShelf 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.b3fcfcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3a8654qh4l49ssnzkwmf9iffyks8v7i3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by YaroKasear** [comment]
> Please test with an alternative Wayland compositor, e.g., sway or river.

Unfortunately, same behavior on Sway.

**Comment by NotAShelf** [comment]
Then it's safe to assume it's an electron problem. We may consider overriding the electron version.

@eclairevoyant @Gerg-L, is webcord working for you two?

**Comment by Gerg-L** [comment]
Works for me

**Comment by eclairevoyant** [comment]
I've never run into such an issue on sway. @YaroKasear did you ensure to disable hyprland when testing sway?

**Comment by Gerg-L** [comment]
It's probably the vencord patch

**Comment by NotAShelf** [comment]
Seems to be the vencord patch. 

Logs of `nix run nixpkgs#webcord` are as follows, but unlike `webcord-vencord` the app actually starts.

```
[GPU:133] crashed
[15829:0516/175755.057485:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is egl, ANGLE is 
[GPU:133] crashed
[15875:0516/175756.953275:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is egl, ANGLE is 
[GPU:133] crashed
```

Perhaps #312114 would help?

**Comment by Gerg-L** [comment]
@NotAShelf webcord-vencord launches on Xorg but does not have anything relating to vencord working

**Comment by YaroKasear** [comment]
I updated to vencord 1.8.4. It's still not working. I'm running out of ideas on what the cause could be.

**Comment by eclairevoyant** [comment]
seems to be caused by b21263b5044e1c5734fe7ca55e78afc08e24adcb and it's still broken on `master`. I was able to prevent the segfault by using electron 29:

```
nix run --impure --expr 'with import <nixpkgs> {}; webcord-vencord.override { webcord = webcord.override { electron = electron_29; }; }'
```
