### ISSUE TITLE
Update request: typst 0.11.0 → 0.11.1

### ISSUE THREAD

**Issue by janurskremer** [NixOS/nixpkgs#312482]
- Package name: typst
- Latest released version: 0.11.1

- Current version on the unstable channel: 0.11.0
- Current version on the stable/release channel: 0.9.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@drupol  @figsoda  @kanashimia 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Fixed in #312469

**Comment by drupol** [comment]
> Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

No you did not.

**Comment by janurskremer** [comment]
> > Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
> 
> No you did not.

I'm sorry, I only checked the issues.
