### ISSUE TITLE
Package request: dde-grand-search

### ISSUE THREAD

**Issue by coryschwartz** [NixOS/nixpkgs#312548]
**Project description**

dde-grand-search is the search feature of the deepin desktop. "Grand search" is referenced in deepin settings (e.g. in keyboard shortcut settings), but it turns out that the nixos dde installation doesn't actually include it.

This is the feature that is similar to "spotlight" on OSX, or perhaps to a lesser extent dmenu or rofi. You hit a keyboard combination, and a searchbox/launcher pops up.

I would expect this package to be included when a user installs the deepin desktop environment

**Metadata**

* homepage URL: https://github.com/linuxdeepin/dde-grand-search
* source URL: https://github.com/linuxdeepin/dde-grand-search
* license: gpl3
* platforms: linux

**Comment by wineee** [comment]
Has packaged in https://github.com/NixOS/nixpkgs/pull/310778
