### ISSUE TITLE
Update request: ocamlPackages.merlin 4.14-501 → 5.0-502

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#312506]
- Package name: ocamlPackages.merlin
- Latest released version: 5.0-502

- Current version on the unstable channel: 4.14-501
- Current version on the stable/release channel: 4.13-414

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@vbgl @sternenseemann 

-----

Note for maintainers: Please tag this issue in your PR.

[5.0-502](https://github.com/ocaml/merlin/releases/tag/5.0-502) supports OCaml 5.2

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by vbgl** [comment]
PR  #323954 adds version 5.1 (for OCaml 5.2). Could you please test it?
