### ISSUE TITLE
Keybase GUI shouldn't check hardcoded /keybase mountpoint

### ISSUE THREAD

**Issue by 5paceToast** [NixOS/nixpkgs#31261]
## Issue description
The keybase-gui wrapper checks for a [hardcoded value](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/keybase-gui/default.nix#L71) to see if kbfs is mounted there.

However, this is configurable through the kbfs service, and defaults to [~/keybase](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/network-filesystems/kbfs.nix#L22).

The wrapper should either be hard-coded to whatever `options.services.kbfs.mountPoint` is, or verify the status some other way (e.g calling `keybase status`).

### Steps to reproduce
1. Set the following in configuration.nix
    ```
    services.keybase.enable = true;
    services.kbfs.enable = true;
    ```
2. `nix-env -iA nixos.keybase-gui`
3. rebuild your configuration
4. try to launch keybase-gui

#### Expected behavior
Tests pass and keybase-gui launches.

#### Actual behavior
```
Keybase is not mounted to /keybase.
You might need to run: kbfsfuse /keybase
Set NIX_SKIP_KEYBASE_CHECKS=1 if you want to skip this check.
```

## Technical details

* System: 18.03pre119292.cfafd6f5a8 (Impala)
* Nix version: 1.11.15
* Nixpkgs version: 18.03pre119292.cfafd6f5a8
* Sandboxing enabled: false

**Comment by RocketPuppy** [comment]
I'm also seeing this issue. Although in my case I've run both the kbfs and keybase services using:
```
systemctl --user start keybase
systemctl --user start kbfs
```
After the kbfs service started I had a `keybase/` directory in my home. Setting the suggested env variable then worked fine.

**Comment by joncojonathan** [comment]
I can confirm I see the same issue.  This does mean if you launch Keybase from a GUI (Gnome3 in my case) nothing happens as the errors are not displayed on screen.

**Comment by joncojonathan** [comment]
Thinking about it, unless Keybase GUI knows to look for ~/keybase, or is configurable once inside the application itself, the GUI wouldn't know where to look.  Wouldn't we need to specify the mountpoint location to the application somewhere before we update the check to reference the value of `services.kbfs.mountPoint` ?

**Comment by brainrape** [comment]
^ added hardcoded `~/keybase`

**Comment by joncojonathan** [comment]
Hi @brainrape ,
While this does look like it'll work in most scenarios it doesn't solve the overall problem in #31261 as it's now just looking at two options of hardcoded mountpoint.  A better solution would be to have the wrapper (I may have used the wrong word, if so, sorry) check for where keybase is mounted and then use that.

Are we not able to do that instead?

**Comment by brainrape** [comment]
Updated PR with suggested fix.

**Comment by IvanMalison** [comment]
@brainrape status?

**Comment by brainrape** [comment]
Waiting for merge. @ mentioned maintainer.
