### ISSUE TITLE
Latest rustup update version breaks compilation

### ISSUE THREAD

**Issue by delehef** [NixOS/nixpkgs#312661]
### Describe the bug

Running a fresh `rustup install nightly && cargo build` fails, the core message being:

```
note: Could not start dynamically linked executable: /home/[xxx]/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld
          NixOS cannot run dynamically linked executables intended for generic
          linux environments out of the box. For more information, see:
          https://nix.dev/permalink/stub-ld
          collect2: error: ld returned 127 exit status
```

### Steps To Reproduce
1. have a rust project
2. `rustup install nightly` (or `rustup update` if you already have one)
3. `cargo build`

### Expected behavior
Either the rustup gcc/ld to be patched for NixOS use, or rust to use the system gcc/ld.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.90, NixOS, 24.05 (Uakari), 24.05pre625274.205781405197`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11, nixpkgs-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by delehef** [comment]
Actually, it looks like this is an issue specifically appearing with `nightly-2024-05-18-x86_64-unknown-linux-gnu`; so I'll try to pass the message upstream.

**Comment by delehef** [comment]
Very specifically, [this is the commit](https://github.com/rust-lang/rust/commit/8af67ba01a1b1d95ff375b645ef5a395d3249e09) introducing the issue, when it has been decided to switch from the system linker to `ldd`.

I suppose the new `[toolchain]/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/` binaries should also be elf-patched?

**Comment by Nemo157** [comment]
Patching those binaries will make them _execute_, but they also need the `ld-wrapper` applied so that the binaries they build will also get patched automatically.
