### ISSUE TITLE
nextcloud28 notify_push requires restart

### ISSUE THREAD

**Issue by Deric-W** [NixOS/nixpkgs#312633]
### Describe the bug
When configuring notify_push for nextcloud the service `nextcloud-notify_push.service` almost always fails the first time after rebooting the system and requires to be restarted in order to be started successfully.

It seems the problem is that notify_push has not finished starting before nextcloud-notify_push-post-start is executed, resulting in a missing or not connected `services.nextcloud.notify_push.socketPath`.

### Steps To Reproduce
1. Setup notify_push
2. Reboot the system
3. Be (un)lucky and watch nextcloud-notify_push.service` fail
4. Restart service (done automatically)

### Expected behavior
The service starts successfully the first time.

### Additional context
Relevant log lines:
```
May 18 11:09:34 unimatrix-01 systemd[1]: Reached target PHP FastCGI Process manager pools target.
May 18 11:09:34 unimatrix-01 systemd[1]: Starting Push daemon for Nextcloud clients...
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: ✓ redis is configured
May 18 11:09:35 unimatrix-01 nginx[1478]: 2024/05/18 11:09:35 [crit] 1478#1478: *11 connect() to unix:/run/nextcloud-notify_push/sock failed (2: No such file or directory) while connecting to upstream, client: ::1, server: nextcloud.thetwins.xyz, request: "GET /push/test/cookie HTTP/1.1", upstream: "http://unix:/run/nextcloud-notify_push/sock:/push/test/cookie", host: "nextcloud.thetwins.xyz"
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: 🗴 can't connect to push server: Server error: `GET https://nextcloud.thetwins.xyz/push/test/cookie` resulted in a `502 Bad Gateway` response:
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: <html>
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: <head><title>502 Bad Gateway</title></head>
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: <body>
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: <center><h1>502 Bad Gateway</h1></center>
May 18 11:09:35 unimatrix-01 nextcloud-notify_push-post-start[1651]: <hr><center>ngin (truncated...)
May 18 11:09:35 unimatrix-01 systemd[1]: nextcloud-notify_push.service: Control process exited, code=exited, status=1/FAILURE
May 18 11:09:35 unimatrix-01 systemd[1]: nextcloud-notify_push.service: Killing process 1655 (tokio-runtime-w) with signal SIGKILL.
May 18 11:09:35 unimatrix-01 systemd[1]: nextcloud-notify_push.service: Failed with result 'exit-code'.
May 18 11:09:35 unimatrix-01 systemd[1]: Failed to start Push daemon for Nextcloud clients.
May 18 11:09:35 unimatrix-01 systemd[1]: nextcloud-notify_push.service: Consumed 1.263s CPU time, received 7.3K IP traffic, sent 2.8K IP traffic.
May 18 11:09:35 unimatrix-01 systemd[1]: Startup finished in 15.946s (kernel) + 1min 5.079s (userspace) = 1min 21.025s.
May 18 11:09:40 unimatrix-01 systemd[1]: nextcloud-notify_push.service: Scheduled restart job, restart counter is at 1.
May 18 11:09:40 unimatrix-01 systemd[1]: Starting Push daemon for Nextcloud clients...
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ redis is configured
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ push server is receiving redis messages
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ push server can load mount info from database
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ push server can connect to the Nextcloud server
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ push server is a trusted proxy
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]: ✓ push server is running the same version as the app
May 18 11:09:42 unimatrix-01 nextcloud-notify_push-post-start[1673]:   configuration saved
May 18 11:09:42 unimatrix-01 systemd[1]: Started Push daemon for Nextcloud clients.
```

[Nextcloud configuration](https://github.com/Deric-W/home_network/blob/9c3c5351152819fafab2015718a8c45d96db7e7e/hosts/unimatrix-01/modules/nextcloud.nix)
[NixOS configuration](https://github.com/Deric-W/home_network/tree/9c3c5351152819fafab2015718a8c45d96db7e7e/hosts/unimatrix-01)

### Notify maintainers

@ajs124

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.11 (Tapir), 23.11.20240514.9ddcaff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-22.11, nixos-hardware, nixpkgs-22.11, sops-nix"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
I have noticed a similar behavior when the module it was introduced. But i was so far happy with the restart situation.

I have played a bit with the situation. I am currently applying the following additional configs to my nextcloud.

```
    systemd = {
      sockets.nextcloud-notify_push = {
        socketConfig = {
          ListenStream = config.services.nextcloud.notify_push.socketPath;
          FlushPending = true;
        };
        wantedBy = [ "sockets.target" ];
      };
      services.nextcloud-notify_push.after = [
        "nextcloud-notify_push.socket"
        "nginx-config-reload.service"
      ];
    };
```
I think the problem is, that notify_push creates the used socket at start, and we are to early executing the ExecStartPost command to configure. 
When we let systemd take care for the socket, i could mitigate that and after that i had problems that my acme certificate reload was running in the mean time.
After adding nginx-config-reload it was able to run on first try after reboot.
You could check if that is also helping on your end and if yes we could check what make sense to use in the module.

**Comment by Deric-W** [comment]
I am not sure if this is a good idea since existing Unix sockets are [removed](https://github.com/nextcloud/notify_push/blob/d0fa194c2900c3f3e1f9a507c23977bd98e82ae9/src/lib.rs#L387) on server startup (and shutdown), possibly interfering with the socket management of SystemD.
I don't know why the connection succeeds after restart or when the socket provided by SystemD is replaced by another socket by notify_push, but I think a more robust way to implement this is to set `Type=notify` which would delay the execution of `ExecStartPost` until the server signals that it is ready.
However something like this would require support by upstream, I could work on a pull request.

**Comment by Shawn8901** [comment]
Doesn't have the program call sd_notify for that to work? I did not find something like that on the code base.
https://www.freedesktop.org/software/systemd/man/255/systemd.service.html#Type= here the notify section claims something like that.

Tho I fully agree that the socket is likely not a good idea when notify_push nukes the socket file.
