### ISSUE TITLE
Blank root password doesn't allow unlocking on Graphical Install

### ISSUE THREAD

**Issue by deech** [NixOS/nixpkgs#31266]
## Issue description
The KDE environment in the Graphical ISO by default locks the screen after some period of inactivity and the password prompt doesn't allow a blank password so there's no way of unlocking it.

### Steps to reproduce
Boot to the KDE environment using a Live Image and let it sit idle for a while and try unlocking.

**Comment by bjornfor** [comment]
I assume this is on master branch? (I just tested NixOS 17.09 and that works; I just press enter and the lock screen goes away.)

**Comment by deech** [comment]
Weird, I tried it again and it works. Maybe it's only an issue if you've tried some password and then just hit Enter? In any case I've unfortunately moved to another distro for now. Feel free to close if you want.

**Comment by bjornfor** [comment]
Tested and found working on NixOS 18.03pre119292.cfafd6ffa8.
