### ISSUE TITLE
Package request: mqtt-explorer

### ISSUE THREAD

**Issue by LDprg** [NixOS/nixpkgs#312716]
**Project description**

**Metadata**

* homepage URL: https://mqtt-explorer.com/
* source URL: https://github.com/thomasnordquist/MQTT-Explorer
* license: creative commons
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by LDprg** [comment]
AppImage works fine with appimage-run. There is also a deb and snap package

**Comment by sikmir** [comment]
I use this one https://github.com/sikmir/nur-packages/blob/master/pkgs/mqtt/mqtt-explorer/default.nix

**Comment by LDprg** [comment]
> I use this one https://github.com/sikmir/nur-packages/blob/master/pkgs/mqtt/mqtt-explorer/default.nix

That package looks great. Maybe even worth to try to contribute to nixpkgs.

**Comment by tsandrini** [comment]
> > I use this one [sikmir/nur-packages@`master`/pkgs/mqtt/mqtt-explorer/default.nix](https://github.com/sikmir/nur-packages/blob/master/pkgs/mqtt/mqtt-explorer/default.nix?rgh-link-date=2024-05-23T14%3A51%3A47Z)
> 
> That package looks great. Maybe even worth to try to contribute to nixpkgs.

Unfortunately I don't think the appImage version would be accepted since the source code is available with a build manual so imho a PR to nixpkgs would need to be with a source build. I might look into it

**Comment by tsandrini** [comment]
I maybe have a potentially working version. I'll try to find some macs to test out the Darwin versions and if that's gonna be okay I'll then submit a PR 🙏

**Comment by sikmir** [comment]
> I maybe have a potentially working version. I'll try to find some macs to test out the Darwin versions and if that's gonna be okay I'll then submit a PR 🙏

Great news, I can test on darwin.
