### ISSUE TITLE
Package request: mutant-emoji

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#312823]
**Project description**

A lesser known emoji font used in Revolt, has a nice look in my opinion. It seems like it's inspired a little by the Windows 10 emoji font and the old Google Noto blob style emojis. Seems to include emojis which are out of spec, I am not sure if those are included in the TTF version in anyway I assume they are excluded and more meant for emojis like :this: in various chat platforms.

For reference, you can use this Arch package build on the AUR. Likely can just do the same thing it does and be done with it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-mutant-emoji

**Metadata**

* homepage URL: https://mutant.tech/
* source URL: https://github.com/mutantstandard/build
* license: Creative CC BY-NC-SA 4.0
* platforms: Should work on pretty much everything that can parse a .ttf

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luftmensch-luftmensch** [comment]
Tried to follow along the PKGBUILD on aur, but I cannot download anything (404 not found) with the provided url in the source.

Do you have any additional infos on how to download the font?

**Comment by nonetrix** [comment]
Honestly not sure, I'm maybe dumb for assuming it just worked. I'll look into it, maybe ttf version isn't a thing anymore or something weird?

**Comment by luftmensch-luftmensch** [comment]
As it's stated on the aur page the package is marked `out-of-date` & `orphan` since 2023-07-05

**Comment by nonetrix** [comment]
Not happening apparently:(
