### ISSUE TITLE
segmentation fault 0ad

### ISSUE THREAD

**Issue by biscotty666** [NixOS/nixpkgs#312804]
I add these packages (flakes and home-manager):

```
 zeroadPackages.zeroad-data
 zeroadPackages.zeroad-unwrapped
```

Running `0ad` gives:

```
[1]    708401 segmentation fault (core dumped)  0ad
```

Details:

flake.nix
```
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/master";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
};

 homeConfigurations."biscotty" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        extraSpecialArgs = { inherit inputs; };
        modules = [
          ./home.nix
        ];
      };
    };
```

home.nix imports
```
{ config, pkgs, ... }:

{
  home.packages = with pkgs; [
    zeroadPackages.zeroad-data
    zeroadPackages.zeroad-unwrapped
];
}
```

**Comment by RossComputerGuy** [comment]
What CPU architecture are you on?

**Comment by biscotty666** [comment]
CPU is Intel i7. OS is NixOS.

**Comment by iSneeze** [comment]
getting the same error with the `zeroad` package, on NixOS 24.11.20240531.57610d2 (Vicuña) x86_64, Linux 6.9.2-zen1, running on a Wayland compositor (Hyprland)

**Comment by RossComputerGuy** [comment]
Interesting, this issue does not occur on NixOS 24.11 on M1 Pro. Might be an x86_64-linux specific issue? Maybe try the `zeroadPackages.zeroad` package instead of the unwrapped + data one?

**Comment by pluiedev** [comment]
0ad requires a wrapper to run correctly, as it needs the `ZEROAD_ROOTDIR` environment variable to be set. There really shouldn't be a reason for running unwrapped packages directly like that, and a crash is to be expected.
