### ISSUE TITLE
GTK3 with Wayland backend ignores options in settings.ini

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#31293]
## Issue description

Seen in sway and weston. GTK3 programs ignore at least font size and theme options.

Someone had the same issue on Arch: https://bbs.archlinux.org/viewtopic.php?id=225553
Created bug https://bugzilla.gnome.org/show_bug.cgi?id=790201

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by gnidorah** [comment]
Someone had the same issue on Arch: https://bbs.archlinux.org/viewtopic.php?id=225553

**Comment by gnidorah** [comment]
This is an upstream issue. Wayland backend overrides GtkSettings by GSettings, so configuring via settings.ini doesn't work. Unless upstream fixes this, if you want to configure Gtk settings under Wayland and outside of Gnome, you must add the following to your configuration.nix
```nix
services.dbus.packages = with pkgs; [ gnome3.dconf ];
environment.systemPackages = with pkgs; [ gnome3.dconf-editor ];
```
and use `dconf-editor` for configuration.

**Comment by gnidorah** [comment]
@jtojnar Should we add `gsettings_desktop_schemas` to $GSETTINGS_SCHEMAS_PATH?

**Comment by jtojnar** [comment]
Looks like the relevant settings are indeed inside `org.gnome.desktop.interface`. We could add `gsettings_desktop_schemas` as a dependency to `wrapGAppsHook`.

**Comment by gnidorah** [comment]
@jtojnar But a lof of packages still do this instead of wrapGAppsHook :(
```nix
    wrapProgram "$out/bin/transmission-gtk" \
      --prefix XDG_DATA_DIRS : "$GSETTINGS_SCHEMAS_PATH"
```

**Comment by jtojnar** [comment]
Then they are most likely broken outside of GNOME (usually missing icon theme) anyway.

**Comment by gnidorah** [comment]
@jtojnar Got it. Could you please
> add gsettings_desktop_schemas as a dependency to wrapGAppsHook
Don't know how to do this myself.
