### ISSUE TITLE
Package request: lrcget

### ISSUE THREAD

**Issue by Titaniumtown** [NixOS/nixpkgs#312996]
**Project description**

Utility for mass-downloading LRC synced lyrics for your offline music library.

LRCGET will scan every files in your chosen directory for music files, then and try to download lyrics to a LRC files having the same name and save them to the same directory as your music files.

**Metadata**

* homepage URL: https://github.com/tranxuanthang/lrcget
* source URL: https://github.com/tranxuanthang/lrcget
* license: MIT
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Celibistrial** [comment]
I tried packaging it , the following works (its gets installed properly) but when you run it it gets the error "failled to create framebuffer" or something along those lines. I think im missing some library 
```nix
{
  stdenv,
  lib,
  dpkg,
  fetchurl,
  autoPatchelfHook,
  glib-networking,
  openssl,
  webkitgtk,
  wrapGAppsHook,
  libsoundio,
  x11Support ? true,
  libX11,
}:
stdenv.mkDerivation rec {
  name = "lrcget";
  version = "0.3.2";

  src = fetchurl {
    url = "https://github.com/tranxuanthang/lrcget/releases/download/0.3.2/lrcget_0.3.2_ubuntu_22.04_amd64.deb";
    sha256 = "sha256-+3ryA8mcK/F34wGVUKcx9QirfaV5/Px7rt3yekAA8N0=";
  };
  postFixup = lib.optionalString ((!stdenv.isDarwin) && x11Support) ''
    # libX11.so is loaded dynamically so autopatch doesn't detect it
    patchelf \
      --add-needed ${libX11}/lib/libX11.so \
      $out/bin/lrcget
  '';
  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
  ];

  buildInputs = [
    glib-networking
    openssl
    libsoundio
    webkitgtk
    wrapGAppsHook
  ];

  unpackCmd = "dpkg-deb -x $curSrc source";

  installPhase = "mv usr $out";
}

```

**Comment by Titaniumtown** [comment]
@Celibistrial I'll take a look at what you have so far when I have a chance. thanks for taking a stab at it!

**Comment by Titaniumtown** [comment]
@Celibistrial shouldn't we be compiling it and not downloading a binary?

**Comment by Celibistrial** [comment]
Yeah, we should be compiling from source, but I used the deb binary to get things working quickly(or at least tried to).

**Comment by 0x61nas** [comment]
> I tried packaging it , the following works (its gets installed properly) but when you run it it gets the error "failled to create framebuffer" or something along those lines. I think im missing some library

this happens bc you probably have an Nvidia card, this can be fixed by setting the `WEBKIT_DISABLE_DMABUF_RENDERER=1` as an environment var or by set `WEBKIT_DISABLE_COMPOSITING_MODE=1` environment var. refer to: https://github.com/NixOS/nixpkgs/issues/212064#issuecomment-1400202079
