### ISSUE TITLE
Something happened to some part of font rendering on 17.09

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#31294]
## Issue description

After updating from 17.03 to 17.09:

* Java Swing apps no longer have font anti-aliasing turned on by default (can be turned back on by passing `-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true` to the `java` process),

* letter spacing of fonts in XTerm is too large (here: XTerm is on the left, Termite with correct rendering on the right, displaying that same GNU Screen buffer, notice the difference in its width),
  ![](https://i.imgur.com/SHgvNcm.png)

* letter spacing of fonts in Alacritty is crazy (here: Alacritty on the left, Termite on the right)
  ![](https://i.imgur.com/kHbHecW.png)

Everything renders fine back on 17.03.

Alacritty and XTerm configs for the screenshots above:
* https://github.com/michalrus/dotfiles/blob/b2d11c51bc45a95aae0f3258d95704cca5617493/dotfiles/i3/.Xresources.d/30xterm
* https://github.com/michalrus/dotfiles/blob/b2d11c51bc45a95aae0f3258d95704cca5617493/dotfiles/michalrus/base/.config/alacritty/alacritty.yml

/cc @volth 

### Steps to reproduce

1. Install 17.09.
1. Lauch some Java app, XTerm, Alacritty.

## Technical details

* System: 17.09.1989.a86c8599a4 (Hummingbird)
* Sandboxing enabled: yes

**Comment by michalrus** [comment]
Actually, Termite does weird things, too:

![](https://i.imgur.com/3cAQ5Kc.png)

**Comment by orivej** [comment]
I've confirmed that XTerm with the given config currently looks as described, with unexpectedly large intervals between letters. Downgrading Iosevka to 1.4.2 (as it was in 17.03) solves this issue.

**Comment by globin** [comment]
cc @ttuegel who did lots of fontconfig work in 17.03 -> 17.09

**Comment by orivej** [comment]
N.B. There is no indication that this is caused by freetype or fontconfig changes, although it's interesting how Iosevka managed to become unusable in XTerm but still be usable in e.g. Konsole. One surprising change I've noticed is that they have renamed `*.ttf` files to `*.ttc`, an extension I have never seen before.

**Comment by mkocha2** [comment]
I am experiencing something similar with `urxvt` after an "upgrade" of 17.09.

**Comment by be5invis** [comment]
@orivej I use TTC to share glyphs among multiple subfamilies. Not sure what happened exactly. The way some Linux handle fonts are, well, weird.

**Comment by be5invis** [comment]
@mkocha2 The TTC is a compressed Font format, that one file can provide multiple sub-fonts with glyph shared. I suspect that the glyph sharing may cause Linux think the Font being non-monospace, since the Iosevka Term now has some glyphs wider than 1sp, which comes from other sub-fonts in the TTC.

**Comment by orivej** [comment]
Thank you, this is the likely explanation.

Fontconfig knows from the font metadata that the font is monospaced: for instance Konsole has an explicit toggle to show non-monospaced fonts, but Iosevka Term is listed even when it's off. Since Konsole supports variable width fonts, it may render each glyph with its own width, but XTerm must be trying to calculate the maximum width among all the characters and use it for the width of each one. It's interesting that Emacs (GTK3), despite good variable width support, displays Iosevka Term like Alacritty on the screenshot above; maybe it has different logic for monospace and variable fonts.

> the Iosevka Term now has some glyphs wider than 1sp

You probably meant to say that Iosevka proper has wide glyphs, while Iosevka Term is still fixed width.

For testing, could you generate one version of Iosevka Term that does not share glyphs with non-Term variants, and another version that is exactly like the current release except it is not marked as monospace in the metadata?

**Comment by be5invis** [comment]
@orivej There are a lot of packages here, and one of them is the Iosevka Term, in TTF: https://github.com/be5invis/Iosevka/releases, without wider glyphs.

**Comment by berce** [comment]
I had this issue and now have a partial fix. A channel update may have helped, but it was not sufficient.
- `~/.Xresources` had a line setting the font (to "Iosevka Medium"), only after removing it, `configuration.nix` was in control.
- setting the monospace font to "Iosevka Term" in `configuration.nix` made font rendering fine in xterm, but resulted in very wide character padding in dmenu.
- setting the monospace font to "Iosevka" in `configuration.nix` works fine in the applications I use.

**Comment by orivej** [comment]
Since #31835 `iosevka` is built from source which results in `.ttf` files, they provide only `Iosevka`, not `Iosevka Term`. (I'm not sure why not and if they should.) The previous binary package is available as `iosevka-bin`.

**Comment by ttuegel** [comment]
> Since #31835 iosevka is built from source which results in .ttf files, they provide only Iosevka, not Iosevka Term.

The font build is completely customizable now, so we can add an Iosevka Term derivation, too. It would be a little tricky to build both in the same derivation because that would involve multiple `configure -> build -> install` cycles.

**Comment by mfiano** [comment]
Was there any attempt at adding Iosevka Term, either in the same or a separate derivation yet? Just upgraded to unstable from 17.09 and fonts being completely wrong (due to missing the Term variant) led me to this issue.

**Comment by steveeJ** [comment]
The Java font rendering issue still exists for me today in 18.03, experienced with *umlet* and *astah-comunity* packages. Extracting the command line from the wrapper and manually inserting `-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true` works around the issue.

**Comment by twhitehead** [comment]
Just a note that this seems to be the same issue as in #22719 and #25639.  I almost wonder if there is a broken underlying AA library somewhere that Java is using.

Here is a report of the same sort of issue happening on a system level in an [earlier version of Ubuntu](https://askubuntu.com/questions/584922/how-do-i-fix-fonts-not-rendering-and-missing-letters).

**Comment by dtzWill** [comment]
> Was there any attempt at adding Iosevka Term, either in the same or a separate derivation yet? Just upgraded to unstable from 17.09 and fonts being completely wrong (due to missing the Term variant) led me to this issue.

For possibly similar reasons I ended up making an Iosevka Term specifically, having problems using it with my terminal emulator.  It's on my NUR repo: https://github.com/dtzWill/nur-packages , here: https://github.com/dtzWill/nur-packages/blob/master/pkgs/iosevka-term/default.nix .

**Comment by ttuegel** [comment]
The `iosevka` expression is overridable. For example, in my `packageOverrides` I have
```.nix

    iosevka-term = self.iosevka.override {
      set = "term";
      design = [
        "term" "v-l-italic" "v-i-italic" "v-g-singlestorey" "v-zero-dotted"
        "v-asterisk-high" "v-at-long" "v-brace-straight"
      ];
    };

    iosevka-type = self.iosevka.override {
      set = "type";
      design = [
        "type" "v-l-italic" "v-i-italic" "v-g-singlestorey" "v-zero-dotted"
        "v-asterisk-high" "v-at-long" "v-brace-straight"
      ];
    };
```
Obviously, I have a lot of variants enabled. :grinning: Should we put an override in Nixpkgs for the plain `type` and `term` variants, though?

**Comment by Artturin** [comment]
it's 2023
