### ISSUE TITLE
phpfpm module does not respect config.services.phpfpm.pools.<name>.user

### ISSUE THREAD

**Issue by aftix** [NixOS/nixpkgs#312974]
### Describe the bug

In [the phpfpm module](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/web-servers/phpfpm/default.nix), there are the options `user`and `group`  under `services.phpfpm.pools.<name>`. However, the module creates a systemd service for the pool that runs as root, ignoring these options.

### Steps To Reproduce
1. Create a phpfpm pool using the nixos module on the `nixos-unstable` branch
2. The resulting service file does not specify `User=`or `Group=`

### Expected behavior

I expect the phpfpm pool services created to run as the configured user and group and not root.

### Notify maintainers

@aanderse 
@drupol 
@Ma27 
@talyz 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.21-hardened1, NixOS, 24.05 (Uakari), 24.05.20240517.4a6b83b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aanderse** [comment]
this is by design

`php-fpm` runs the master process as `root` and then spawns child processes as the specified `user` and `group` values
