### ISSUE TITLE
AMDGPU driver doesn't work on Pitcairn GPU. [6.topic: nixos]

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [NixOS/nixpkgs#31301]
## Issue description

The module fails to load even when added to the initrd (logs below), and trying to "make" the X Server use it breaks the display completely; even the virtual consoles become inaccessible if the xserver video driver is set to amdgpu.

### Steps to reproduce

add ` "amdgpu"` to `boot.initrd.availableKernelModules` in `/etc/nixos/hardware-configuration.conf`  
(and, optionally, `services.xserver.videoDrivers = [ "amdgpu" ];' to `/etc/nixos/configuration.conf`)

## Technical details

* System: `17.09.1971.937ea32f1f (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"17.09.1971.937ea32f1f"`
* Sandboxing enabled: `build-use-sandbox = false`

Currently I have `amdgpu` module in my initrd, but not "forced" for the x server (just no mention of it in `configuration.conf`); here is some potentially useful output:

````
$ dmesg | grep -E '(drm|amd)'
[    0.846878] [drm] Initialized
[    0.911003] [drm] amdgpu kernel modesetting enabled.
[    0.912143] [drm] initializing kernel modesetting (PITCAIRN 0x1002:0x6818 0x174B:0xE241 0x00).
[    0.912152] [drm] register mmio base: 0xFBE80000
[    0.912153] [drm] register mmio size: 262144
[    0.912720] [drm] GPU post is not needed
[    0.912721] [drm] Changing default dispclk from 600Mhz to 625Mhz
[    0.912886] amdgpu 0000:04:00.0: Direct firmware load for radeon/pitcairn_mc.bin failed with error -2
[    0.912888] amdgpu 0000:04:00.0: si_mc: Failed to load firmware "radeon/pitcairn_mc.bin"
[    0.912944] amdgpu 0000:04:00.0: Failed to load mc firmware!
[    0.913018] [drm:amdgpu_device_init [amdgpu]] *ERROR* sw_init of IP block <gmc_v6_0> failed -2
[    0.913071] amdgpu 0000:04:00.0: amdgpu_init failed
[    0.913117] amdgpu 0000:04:00.0: Fatal error during GPU init
[    0.913165] [drm] amdgpu: finishing device.
[    0.913556] amdgpu: probe of 0000:04:00.0 failed with error -2
[   11.380239] [drm] radeon kernel modesetting enabled.
[   11.811991] [drm] initializing kernel modesetting (PITCAIRN 0x1002:0x6818 0x174B:0xE241 0x00).
[   11.812007] [drm] register mmio base: 0xFBE80000
[   11.812008] [drm] register mmio size: 262144
[   11.812717] [drm] Detected VRAM RAM=2048M, BAR=256M
[   11.812718] [drm] RAM width 256bits DDR
[   11.812793] [drm] radeon: 2048M of VRAM memory ready
[   11.812794] [drm] radeon: 2048M of GTT memory ready.
[   11.812817] [drm] Loading pitcairn Microcode
[   12.186972] [drm] Internal thermal controller with fan control
[   12.187061] [drm] probing gen 2 caps for device 8086:340e = 3b3d02/0
[   12.197741] [drm] radeon: dpm initialized
[   12.395940] [drm] Found VCE firmware/feedback version 50.0.1 / 17!
[   12.395950] [drm] GART: num cpu pages 524288, num gpu pages 524288
[   12.397369] [drm] probing gen 2 caps for device 8086:340e = 3b3d02/0
[   12.397373] [drm] PCIE gen 2 link speeds already enabled
[   12.401680] [drm] PCIE GART of 2048M enabled (table at 0x00000000001D6000).
[   12.422594] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   12.422595] [drm] Driver supports precise vblank timestamp query.
[   12.422658] [drm] radeon: irq initialized.
[   12.607731] [drm] ring test on 0 succeeded in 3 usecs
[   12.607737] [drm] ring test on 1 succeeded in 1 usecs
[   12.607741] [drm] ring test on 2 succeeded in 1 usecs
[   12.607752] [drm] ring test on 3 succeeded in 6 usecs
[   12.607762] [drm] ring test on 4 succeeded in 6 usecs
[   12.784908] [drm] ring test on 5 succeeded in 2 usecs
[   12.784914] [drm] UVD initialized successfully.
[   12.895027] [drm] ring test on 6 succeeded in 26 usecs
[   12.895039] [drm] ring test on 7 succeeded in 3 usecs
[   12.895040] [drm] VCE initialized successfully.
[   12.895373] [drm] ib test on ring 0 succeeded in 0 usecs
[   12.895464] [drm] ib test on ring 1 succeeded in 0 usecs
[   12.895589] [drm] ib test on ring 2 succeeded in 0 usecs
[   12.895626] [drm] ib test on ring 3 succeeded in 0 usecs
[   12.895660] [drm] ib test on ring 4 succeeded in 0 usecs
[   13.548003] [drm] ib test on ring 5 succeeded
[   14.052032] [drm] ib test on ring 6 succeeded
[   14.556016] [drm] ib test on ring 7 succeeded
[   14.556463] [drm] Radeon Display Connectors
[   14.556464] [drm] Connector 0:
[   14.556464] [drm]   DP-1
[   14.556464] [drm]   HPD4
[   14.556466] [drm]   DDC: 0x6530 0x6530 0x6534 0x6534 0x6538 0x6538 0x653c 0x653c
[   14.556466] [drm]   Encoders:
[   14.556466] [drm]     DFP1: INTERNAL_UNIPHY2
[   14.556467] [drm] Connector 1:
[   14.556467] [drm]   HDMI-A-1
[   14.556468] [drm]   HPD5
[   14.556468] [drm]   DDC: 0x6540 0x6540 0x6544 0x6544 0x6548 0x6548 0x654c 0x654c
[   14.556469] [drm]   Encoders:
[   14.556469] [drm]     DFP2: INTERNAL_UNIPHY2
[   14.556470] [drm] Connector 2:
[   14.556470] [drm]   DVI-I-1
[   14.556470] [drm]   HPD1
[   14.556471] [drm]   DDC: 0x6550 0x6550 0x6554 0x6554 0x6558 0x6558 0x655c 0x655c
[   14.556472] [drm]   Encoders:
[   14.556472] [drm]     DFP3: INTERNAL_UNIPHY1
[   14.556472] [drm] Connector 3:
[   14.556473] [drm]   DVI-I-2
[   14.556473] [drm]   HPD6
[   14.556474] [drm]   DDC: 0x6580 0x6580 0x6584 0x6584 0x6588 0x6588 0x658c 0x658c
[   14.556474] [drm]   Encoders:
[   14.556475] [drm]     DFP4: INTERNAL_UNIPHY
[   14.556475] [drm]     CRT1: INTERNAL_KLDSCP_DAC1
[   14.617761] [drm] fb mappable at 0xD05D8000
[   14.617762] [drm] vram apper at 0xD0000000
[   14.617762] [drm] size 5324800
[   14.617763] [drm] fb depth is 24
[   14.617763] [drm]    pitch is 5888
[   14.617922] fbcon: radeondrmfb (fb1) is primary device
[   14.784150] radeon 0000:04:00.0: fb1: radeondrmfb frame buffer device
[   14.789939] [drm] Initialized radeon 2.49.0 20080528 for 0000:04:00.0 on minor 0
$ 
````

**Comment by rnhmjoj** [comment]
It looks like amdgpu has some serious problems when run from an initrd: check this [report](https://bugzilla.redhat.com/show_bug.cgi?id=1499580).
I have the black screen/hang myself (RX 480). I'm not sure about X.org.

**Comment by phi-gamma** [comment]
Same problem here with an RX 550 that worked fine on Arch a couple months ago:

    # lspci -v -nn -s 01:00.0 
    01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon RX 550] [1002:699f] (rev c7) (prog-if 00 [VGA controller])
    	Subsystem: Sapphire Technology Limited Device [1da2:e367]
    	Flags: bus master, fast devsel, latency 0, IRQ 27, NUMA node 0
    	Memory at c0000000 (64-bit, prefetchable) [size=256M]
    	Memory at dfe00000 (64-bit, prefetchable) [size=2M]
    	I/O ports at ee00 [size=256]
    	Memory at fde80000 (32-bit, non-prefetchable) [size=256K]
    	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
    	Capabilities: [48] Vendor Specific Information: Len=08 <?>
    	Capabilities: [50] Power Management version 3
    	Capabilities: [58] Express Legacy Endpoint, MSI 00
    	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
    	Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
    	Capabilities: [150] Advanced Error Reporting
    	Capabilities: [200] #15
    	Capabilities: [270] #19
    	Capabilities: [2b0] Address Translation Service (ATS)
    	Capabilities: [2c0] Page Request Interface (PRI)
    	Capabilities: [2d0] Process Address Space ID (PASID)
    	Capabilities: [320] Latency Tolerance Reporting
    	Capabilities: [328] Alternative Routing-ID Interpretation (ARI)
    	Capabilities: [370] L1 PM Substates
    	Kernel driver in use: amdgpu
    	Kernel modules: amdgpu

This is NixOS 17.09 with the 4.13 series kernel. Both *amdgpu* and *radeon* are
blacklisted in the initrd.

When doing a manual ``modprobe amdgpu``, the screen (both of them, actually)
goes black. Kernel messages:

    Dec 03 19:19:33 phlegethon systemd-udevd[817]: Specified group 'kvm' unknown
    Dec 03 19:19:33 phlegethon kernel: Linux agpgart interface v0.103
    Dec 03 19:19:33 phlegethon kernel: [drm] amdgpu kernel modesetting enabled.
    Dec 03 19:19:33 phlegethon kernel: AMD IOMMUv2 driver by Joerg Roedel <jroedel@suse.de>
    Dec 03 19:19:33 phlegethon kernel: AMD IOMMUv2 functionality not available on this system
    Dec 03 19:19:33 phlegethon kernel: CRAT table not found
    Dec 03 19:19:33 phlegethon kernel: Finished initializing topology ret=0
    Dec 03 19:19:33 phlegethon kernel: kfd kfd: Initialized module
    Dec 03 19:19:33 phlegethon kernel: [drm] initializing kernel modesetting (POLARIS12 0x1002:0x699F 0x1DA2:0xE367 0xC7).
    Dec 03 19:19:33 phlegethon kernel: [drm] register mmio base: 0xFDE80000
    Dec 03 19:19:33 phlegethon kernel: [drm] register mmio size: 262144
    Dec 03 19:19:33 phlegethon kernel: [drm] probing gen 2 caps for device 1022:9603 = 300d02/0
    Dec 03 19:19:33 phlegethon kernel: [drm] probing mlw for device 1022:9603 = 300d02
    Dec 03 19:19:33 phlegethon kernel: [drm] UVD is enabled in VM mode
    Dec 03 19:19:33 phlegethon kernel: [drm] VCE enabled in VM mode
    Dec 03 19:19:33 phlegethon kernel: [drm] BIOS signature incorrect 20 7
    Dec 03 19:19:33 phlegethon kernel: amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
    Dec 03 19:19:33 phlegethon kernel: ATOM BIOS: 113-3676M-UO1
    Dec 03 19:19:33 phlegethon kernel: [drm] GPU post is not needed
    Dec 03 19:19:33 phlegethon kernel: [drm] vm size is 64 GB, block size is 13-bit
    Dec 03 19:19:33 phlegethon kernel: amdgpu 0000:01:00.0: VRAM: 4096M 0x0000000000000000 - 0x00000000FFFFFFFF (4096M used)
    Dec 03 19:19:33 phlegethon kernel: amdgpu 0000:01:00.0: GTT: 4096M 0x0000000100000000 - 0x00000001FFFFFFFF
    Dec 03 19:19:33 phlegethon kernel: [drm] Detected VRAM RAM=4096M, BAR=256M
    Dec 03 19:19:33 phlegethon kernel: [drm] RAM width 128bits GDDR5
    Dec 03 19:19:33 phlegethon kernel: [TTM] Zone  kernel: Available graphics memory: 12346612 kiB
    Dec 03 19:19:33 phlegethon kernel: [TTM] Zone   dma32: Available graphics memory: 2097152 kiB
    Dec 03 19:19:33 phlegethon kernel: [TTM] Initializing pool allocator
    Dec 03 19:19:33 phlegethon kernel: [TTM] Initializing DMA pool allocator
    Dec 03 19:19:33 phlegethon kernel: [drm] amdgpu: 4096M of VRAM memory ready
    Dec 03 19:19:33 phlegethon kernel: [drm] amdgpu: 4096M of GTT memory ready.
    Dec 03 19:19:33 phlegethon kernel: [drm] GART: num cpu pages 1048576, num gpu pages 1048576
    Dec 03 19:19:33 phlegethon kernel: [drm] PCIE GART of 4096M enabled (table at 0x0000000000040000).
    Dec 03 19:19:33 phlegethon kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
    Dec 03 19:19:33 phlegethon kernel: [drm] Driver supports precise vblank timestamp query.
    Dec 03 19:19:33 phlegethon kernel: amdgpu 0000:01:00.0: amdgpu: using MSI.
    Dec 03 19:19:33 phlegethon kernel: [drm] amdgpu: irq initialized.
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] amdgpu: powerplay sw initialized
    Dec 03 19:19:34 phlegethon kernel: [drm] AMDGPU Display Connectors
    Dec 03 19:19:34 phlegethon kernel: [drm] Connector 0:
    Dec 03 19:19:34 phlegethon kernel: [drm]   DP-1
    Dec 03 19:19:34 phlegethon kernel: [drm]   HPD5
    Dec 03 19:19:34 phlegethon kernel: [drm]   DDC: 0x4868 0x4868 0x4869 0x4869 0x486a 0x486a 0x486b 0x486b
    Dec 03 19:19:34 phlegethon kernel: [drm]   Encoders:
    Dec 03 19:19:34 phlegethon kernel: [drm]     DFP1: INTERNAL_UNIPHY1
    Dec 03 19:19:34 phlegethon kernel: [drm] Connector 1:
    Dec 03 19:19:34 phlegethon kernel: [drm]   HDMI-A-1
    Dec 03 19:19:34 phlegethon kernel: [drm]   HPD3
    Dec 03 19:19:34 phlegethon kernel: [drm]   DDC: 0x4874 0x4874 0x4875 0x4875 0x4876 0x4876 0x4877 0x4877
    Dec 03 19:19:34 phlegethon kernel: [drm]   Encoders:
    Dec 03 19:19:34 phlegethon kernel: [drm]     DFP2: INTERNAL_UNIPHY1
    Dec 03 19:19:34 phlegethon kernel: [drm] Connector 2:
    Dec 03 19:19:34 phlegethon kernel: [drm]   DVI-D-1
    Dec 03 19:19:34 phlegethon kernel: [drm]   HPD4
    Dec 03 19:19:34 phlegethon kernel: [drm]   DDC: 0x4878 0x4878 0x4879 0x4879 0x487a 0x487a 0x487b 0x487b
    Dec 03 19:19:34 phlegethon kernel: [drm]   Encoders:
    Dec 03 19:19:34 phlegethon kernel: [drm]     DFP3: INTERNAL_UNIPHY
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000100000008, cpu addr 0xffff8a48ccef3008
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000100000018, cpu addr 0xffff8a48ccef3018
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000100000028, cpu addr 0xffff8a48ccef3028
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000100000038, cpu addr 0xffff8a48ccef3038
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000100000048, cpu addr 0xffff8a48ccef3048
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000100000058, cpu addr 0xffff8a48ccef3058
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 6 use gpu addr 0x0000000100000068, cpu addr 0xffff8a48ccef3068
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 7 use gpu addr 0x0000000100000078, cpu addr 0xffff8a48ccef3078
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 8 use gpu addr 0x0000000100000088, cpu addr 0xffff8a48ccef3088
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 9 use gpu addr 0x000000010000009c, cpu addr 0xffff8a48ccef309c
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 10 use gpu addr 0x00000001000000ac, cpu addr 0xffff8a48ccef30ac
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 11 use gpu addr 0x00000001000000bc, cpu addr 0xffff8a48ccef30bc
    Dec 03 19:19:34 phlegethon kernel: [drm] Found UVD firmware Version: 1.79 Family ID: 16
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 12 use gpu addr 0x0000000000a2d420, cpu addr 0xffffad9605a5a420
    Dec 03 19:19:34 phlegethon kernel: [drm] Found VCE firmware Version: 52.4 Binary ID: 3
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 13 use gpu addr 0x00000001000000dc, cpu addr 0xffff8a48ccef30dc
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fence driver on ring 14 use gpu addr 0x00000001000000ec, cpu addr 0xffff8a48ccef30ec
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] [AVFS] Something is broken. See log!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: amdgpu: [powerplay] Can't find requested voltage id in vdd_dep_on_sclk table!
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 0 succeeded in 16 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 9 succeeded in 10 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 1 succeeded in 9 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 2 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 3 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 4 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 5 succeeded in 7 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 6 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 7 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 8 succeeded in 4 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 10 succeeded in 7 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 11 succeeded in 7 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 12 succeeded in 1 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] UVD initialized successfully.
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 13 succeeded in 6 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] ring test on 14 succeeded in 3 usecs
    Dec 03 19:19:34 phlegethon kernel: [drm] VCE initialized successfully.
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 0 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 1 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 2 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 3 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 4 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 5 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 6 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 7 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 8 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 9 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 10 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 11 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 12 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] ib test on ring 13 succeeded
    Dec 03 19:19:34 phlegethon kernel: [drm] fb mappable at 0xC0C37000
    Dec 03 19:19:34 phlegethon kernel: [drm] vram apper at 0xC0000000
    Dec 03 19:19:34 phlegethon kernel: [drm] size 8294400
    Dec 03 19:19:34 phlegethon kernel: [drm] fb depth is 24
    Dec 03 19:19:34 phlegethon kernel: [drm]    pitch is 7680
    Dec 03 19:19:34 phlegethon kernel: fbcon: amdgpudrmfb (fb0) is primary device
    Dec 03 19:19:34 phlegethon kernel: Console: switching to colour frame buffer device 240x67
    Dec 03 19:19:34 phlegethon kernel: amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
    Dec 03 19:19:34 phlegethon kernel: [drm] Initialized amdgpu 3.18.0 20150101 for 0000:01:00.0 on minor 0

**Comment by phi-gamma** [comment]
Well, after logging on with SSH, I could restart the display manager
and it works. Still, this should work on bootup, without the blacklist
workaround.

**Comment by phi-gamma** [comment]
As @JamesTheAwesomeDude writes, switching to different
framebuffer consoles no longer works.

**Comment by cx405** [comment]
From [phoronix](https://www.phoronix.com/scan.php?page=article&item=linux-413-gcn101&num=1)

> Beginning with Linux 4.13, AMDGPU and Radeon GCN 1.0/1.1 support can co-exist nicer thanks to some new module options added. Even if blacklisting the Radeon DRM, AMDGPU doesn't have GCN 1.0/1.1 support by default but requires setting amdgpu.cik_support=1 for GCN 1.1 support and amdgpu.si_support=1 for GCN 1.0 support. To get Radeon DRM to not bind to these generations of GPUs, radeon.si_support=0 and radeon.cik_support=0 must be set. So basically if you want to get AMDGPU working for Sea Islands and Southern Islands GPUs on Linux 4.13+, you need to append "radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1" to your kernel command line when booting the system.

So, you need to add these kernel options:   
radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1  
and try again.

**Comment by therealpxc** [comment]
I have this problem with `amdgpu` on my multimedia PC, which uses an RX 580.

I noticed that in the [amdgpu-pro](https://github.com/NixOS/nixpkgs/blob/68dda232d2ca09a6609f8dfd5d24d8c195617d24/nixos/modules/hardware/video/amdgpu-pro.nix) module, there are some lines related to adding firmware modules., but [none for amdgpu](https://github.com/NixOS/nixpkgs/blob/b4821ece01818a4702b332e9bc54b093c50d5d7a/nixos/modules/hardware/video/amdgpu.nix)

It's also part of `linux-firmware-nonfree`.

This might be a silly question, and we might be looking at separate issues, but does enabling redistributable firmware make any difference for you guys? It resolved the issue for me (with none of the other fixes mentioned in this thread applied).

**Comment by cx405** [comment]
Shouldn't be a problem anymore. GCN1 GPUs like R9 280 still rely on "radeon", but anything upwards like R9 285 or 270 works fine with "amdgpu" in "services.xserver.videoDrivers". I had R9 280 for quite a while and now switched to rx 570, so it works here without problem. Firmware is needed, but adding anything to initrd isn't.

**Comment by rnhmjoj** [comment]
Let's close it, then.
