### ISSUE TITLE
request for mypy update

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#31304]
## Issue description
There seems to have been lots of improvements to latest mypy compared to the current nixpkgs version, for instance a cool new features aka TypedDict & forward declarations see
http://mypy-lang.blogspot.jp/2017/10/mypy-0540-released.html

There is a new dependency too.

**Comment by globin** [comment]
mypy 0.540 is the newest released version and the currently packaged version, closing this therefore.

If I have misunderstood this or you have more information, feel free to add to this and reopen. :)

**Comment by teto** [comment]
Now it's official we are both crazy, just not at the same moments xD. You are perfectly 0.540 is available that's awesome.

**Comment by teto** [comment]
Was wondering why TypedDict was not recognized, that's because it depends on an extra package `mypy_extensions` cf http://mypy.readthedocs.io/en/latest/kinds_of_types.html#typeddict 
I was eager to try that feature but they say it's unstable so I guess it can wait :)
