### ISSUE TITLE
Current ghc (8.0.2) has lots of missing packages.

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#31306]
## Issue description
Please see the [err.log](https://github.com/NixOS/nixpkgs/files/1445565/err.log) captured by following command:

    $ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz -p ghc --run 'ghc-pkg check' 2>err.log

In contrast `ghc784`, `ghc7103`, `ghc821` and `ghcHEAD` doesn't to have any problem

    $ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz -p haskell.compiler.ghc821 --run 'ghc-pkg check'

## Related issues

https://github.com/NixOS/nixpkgs/issues/30949

**Comment by mpickering** [comment]
I don't think this is a nix problem at all. 

All the paths in the log are local paths which are obtained by using cabal with ghc directly rather than delegating package management to nix. 

Is #30948 the actual problem you are having?

**Comment by wizzup** [comment]
@mpickering Don't you have any problem running this command?

    $ nix-shell -I https://github.com/NixOS/nixpkgs/archive/master.tar.gz -p ghc --run 'ghc-pkg check' 2>err.log

**Comment by domenkozar** [comment]
> Also I wonder when will ghc821 be adapted as the default nixos.ghc?

Once stackage LTS comes out.

**Comment by wizzup** [comment]
Closed as no longer reproducible using master branch.
