### ISSUE TITLE
Package request: furmark 2

### ISSUE THREAD

**Issue by LDprg** [NixOS/nixpkgs#313066]
**Project description**

Furmark 2 is a commonly used gpu benchmark and stresstest. Very useful for testing stability after overclocking.

**Metadata**

* homepage URL: https://www.geeks3d.com/furmark/
* source URL: /
* license: unfree
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
duplicate of #301760
