### ISSUE TITLE
freshrss does not create systemd service

### ISSUE THREAD

**Issue by CaptainLexington** [NixOS/nixpkgs#313180]
### Describe the bug
When enabling freshrss and rebuilding, no freshrss systemd service is started.
### Steps To Reproduce
1. `services.freshrss.enable = true;` (as well other requirements for minimal config)
2. `sudo nixos-rebuild switch` (with `--flake`, for me)
3.  `systemctl status freshrss`
`Unit freshrss.service could not be found.`
4. `systemctl list-units`
The only freshrss units are `phpfpm-freshrss` and `freshrss-udpater.timer`.
6. Navigate to `localhost:8080` in browser.
Unable to connect.

### Expected behavior
A service with `freshrss.service` (or something?) is created and runs automatically. The http server is accessible from a browser.

### Additional context
I initially tried running in a container, but running on the host OS had the same result

### Notify maintainers
@etu @Stunkymonkey @mattchrist 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.90, NixOS, 23.11 (Tapir), 23.11.20240517.bacb850`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mattchrist** [comment]
Freshrss doesn't run as a `freshrss.service` systemd service. It runs under php-fpm.  
The associated systemd service is `phpfpm-freshrss.service`.  
This is then exposed via nginx.  
I believe the default nginx configuration will expose freshrss on port 80, so http://localhost may work for your current configuration.

The [default virtualHost](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/services/web-apps/freshrss.nix#L179) used by nginx for freshrss is `freshrss`. My guess is you'll need to configure it.

If you want to access freshrss via "http://localhost:8080" you could use a config like:
```nix
services.freshrss = {
  enable = true;
  baseUrl = "http://localhost:8080";
};
services.nginx.virtualHosts.freshrss.listen = [ {addr = "127.0.0.1"; port = 8080;} ];
services.nginx.virtualHosts.freshrss.serverName = "localhost";
```

**Comment by CaptainLexington** [comment]
Sorry I never responded to this! This worked, thank you.

**Comment by Stunkymonkey** [comment]
i guess we can close this then?

please report back if i am wrong.

**Comment by CaptainLexington** [comment]
I do agree with qyriad that this could be explicitly documented better, but I don't have any further issue to specifically track

**Comment by Stunkymonkey** [comment]
any specific location where you want this documented? where would you look something like this up?

**Comment by CaptainLexington** [comment]
I would probably put in the description of the `enable` option.
