### ISSUE TITLE
upgrade gdk-pixbuf 2.42.10 -> 2.42.11 causes errors in applications using less supported libraries

### ISSUE THREAD

**Issue by rdbeni0** [NixOS/nixpkgs#313199]
### Describe the bug
Upgrade  2.42.10 -> 2.42.11 causes errors in applications using less supported libraries (please see links - there is a lot of content). NixOS stable **23.11** is not affected.

Example - please try to use pkg `xsane`  from unstable branch:

_xsane:118309): GdkPixbuf-WARNING **: 20:11:03.562: Error loading XPM image loader: Image type “xpm” is not supported_

Its possible that it can cause many issues in less known legacy application in the future.

### Steps To Reproduce
1. use unstable branch and 2.42.11 version of package gdk-pixbuf
2. run **xsane** application or **vim-gtk2** or **claws-mail**
3. see output :) its easy to reproduce

### Expected behavior

I think there are two solutions (two possibilities) to fix it. IMHO 1/ option is better.

**1/** add build option to meson : _-D others=enabled_ and fix typo in **`tests/meson.build`**: 
```diff
-    'skip': not (enabled_loaders.contains('ani') and enabled_loaders_contains('gif')),
+    'skip': not (enabled_loaders.contains('ani') and enabled_loaders.contains('gif')),
``` 
(. vs _ - please take a closer look)
Basically the same approach as Arch Linux fix (commit) : [here](https://gitlab.archlinux.org/archlinux/packaging/packages/gdk-pixbuf2/-/commit/4fa2d98a197781354b66a9710c9d596d502c961b#e27bbb6f7f045990bf4d775ff80708de7027412e)

**2/** second option is to add missing files, which has been removed. I think openSUSE is doing something like that [here](https://forums.opensuse.org/t/xsane-crashing-on-opening-since-last-update/174817)

### Additional context

[Arch Linux commit - "enable support for less supported image formats"](https://gitlab.archlinux.org/archlinux/packaging/packages/gdk-pixbuf2/-/commit/4fa2d98a197781354b66a9710c9d596d502c961b#e27bbb6f7f045990bf4d775ff80708de7027412e) - imho this approach is the best

[openSUSE forum - discussion about the same issue](https://forums.opensuse.org/t/xsane-crashing-on-opening-since-last-update/174817) - second option

[GNOME GNOME gdk-pixbuf - upstream commit which causes issue](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/e052a112075a19fb75f1f2ff3de4c82923de13f2)

[Discussion on Homebrew](https://github.com/Homebrew/homebrew-core/issues/169803)

[vim-gtk2 - Arch Linux discussion](https://bbs.archlinux.org/viewtopic.php?id=295054)

[Arch Linux - reported issue](https://gitlab.archlinux.org/archlinux/packaging/packages/gdk-pixbuf2/-/issues/1)

[ruby gnome - the same issue](https://github.com/ruby-gnome/ruby-gnome/issues/1614)

[the same on Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/issues/16078)

### Notify maintainers

@edolstra 
@bobby285271 
@hedning 
@jtojnar 

### Metadata
not required, easy to reproduce - nixos unstable

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
This was already fixed by https://github.com/NixOS/nixpkgs/pull/308976. Currently in staging-next: https://github.com/NixOS/nixpkgs/pull/312133

**Comment by rdbeni0** [comment]
ok, I didn't see it. I'm closing it as "solved".
