### ISSUE TITLE
Keep the old version of Skype

### ISSUE THREAD

**Issue by P-E-Meunier** [NixOS/nixpkgs#31329]
## Issue description

Skype 5 (aka skypeforlinux) works fine on my machine, but there are people I can't communicate with because their skype is obsolete.

I think it would be optimal to be able to install both versions 4.3 and 5.

### Steps to reproduce

Install Skype 4.3 on an Ubuntu machine (why would anyone do that? Because that version recognises the microphone, while version 5 doesn't).

Call it from Skype 5 on NixOS.

**Comment by orivej** [comment]
Can you find where we may download Skype 4.3 from?

**Comment by PanAeon** [comment]
I believe Microsoft said that skype 4.3 should have stopped working after July 1, 2017. I believe people who keep using skype 4.3 should also have problems connecting to newer windows and web clients, not only skype for linux.

**Comment by P-E-Meunier** [comment]
Sure, but it still half-works. Also, the newer skype has no way to set parameters, and doesn't recognise the microphone on some setups.

Skype 4.3 can be downloaded from http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb

**Comment by Mic92** [comment]
Can be brought back in a pull request.

**Comment by bachp** [comment]
@Mic92 Skype is at version 8 now. I think this issue can be closed.
