### ISSUE TITLE
Offer keyboard layout choices at live boots

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#3132]
When we boot NixOS from Live CD/DVD/USB/whatever, we're dropped into a terminal telling us to log in as `root` without a password and telling us how to start a session.

It'd be *great* if before this point, NixOS would offer a choice of a keymap to use: looking for what commands are available for changing keymaps and looking for the keymap we're used to is a painful experience when one hasn't typed QWERTY for a long time. It'd be a great improvement if we could choose at least for the terminal session, even if it does not apply to KDE started afterwards.

As an example, Gentoo does this. It offers tens of keymaps to choose from and defaults to QWERTY after few seconds, proceeding to the login part afterwards. The implementation should be fairly simple I think, just run loadkeys or similar with user's choice.

**Comment by Profpatsch** [comment]
(triage) @Fuuzetsu Did you look into it? I personally think it is okay to document `loadkeys`.
