### ISSUE TITLE
Virtualbox is unable to do 3D acceleration

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#313372]
### Describe the bug
VMs with 3D acceleration don't start. I see the following in VirtualBox log:
```
00:00:03.223187 rtldrNativeLoad: dlopen('D3DCompiler_47.so', RTLD_NOW | RTLD_LOCAL) failed: D3DCompiler_47.so: cannot open shared object file: No such file or directory
00:00:03.223700 rtldrNativeLoad: dlopen('libvulkan.so.1', RTLD_NOW | RTLD_LOCAL) failed: libvulkan.so.1: cannot open shared object file: No such file or directory
```

### Steps To Reproduce
1. Enable 3D acceleration in VM

### Expected behavior
VM starts

### Additional context
Setting the path to vulkan-loader's lib directory via LD_LIBRARY_PATH has helped to me. Perhaps the dlopen calls should be patched to contain full paths? D3DCompiler is likely needed just as well for Windows guests via DXVK?

Personally I have the problem with virtualboxKvm, not sure about the common virtualbox.

### Notify maintainers

@svanderburg @friedrichaltheide @blitz

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.9-lqx1, NixOS, 24.05 (Uakari), 24.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/static/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by blitz** [comment]
@ilya-fedin Can you test https://github.com/NixOS/nixpkgs/pull/313390 and report back if that fixes the issue for you?

**Comment by ilya-fedin** [comment]
Yeah, it does, thanks
