### ISSUE TITLE
cannot mount bcachefs from lvm raid0 device

### ISSUE THREAD

**Issue by jezcope** [NixOS/nixpkgs#313350]
### Describe the bug

I have an LVM setup, and I've been trying out bcachefs by using it as scratch space (since it's stuff I don't mind losing) on an LVM RAID0 volume with 4 stripes. Since #304761 updated `bcachefs-tools` to 1.7.0 I can't mount this, but switching back to a previous generation with `bcachefs-tools` 1.4.1 or using `bcachefs-tools` 1.3.3 from nixos-23.11 lets me mount it just fine. Using a linear volume instead also works fine.

### Steps To Reproduce
1. Create an LV with `-t raid0 --stripes 2`
2. Create a bcachefs filesystem on the new LV
3. Try to mount the new filesystem

Running `bcachefs mount` with `-v` results in:

```
INFO - bcachefs::commands::cmd_mount: mounting with params: device: /dev/dm-38:/dev/dm-40, target: /mnt, options: 
DEBUG - bcachefs::commands::cmd_mount: parsing mount options: 
INFO - bcachefs::commands::cmd_mount: mounting bcachefs filesystem, /mnt
INFO - bcachefs::commands::cmd_mount: mounting filesystem
ERROR - bcachefs::commands::cmd_mount: Fatal error: Device or resource busy
```

### Expected behavior

Should mount correctly. Output from bcachefs-tools 1.3.3:

```
INFO - bcachefs_rust::cmd_mount: mounting with params: device: /dev/vg/test, target: /mnt, options: 
DEBUG - bcachefs_rust::cmd_mount: parsing mount options: 
INFO - bcachefs_rust::cmd_mount: mounting bcachefs filesystem, /mnt
INFO - bcachefs_rust::cmd_mount: mounting filesystem
INFO - bcachefs_rust::cmd_mount: Successfully mounted
```

### Additional context

I don't know enough about Linux FS implementations, but suspect it might be an instance of https://github.com/koverstreet/bcachefs-tools/issues/260

### Notify maintainers

@davidak @JohnRTitor @Madouura 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.05 (Uakari), 24.05.20240519.6c0b7a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`
 - channels(jez): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/r8nhgnkxacbnf4kv8kdi8b6ks3k9b16i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Is it an encrypted setup?

**Comment by jezcope** [comment]
Well, the patch doesn't make a difference, _but_ that's ok because just building it from master at [kentoverstreet/bcachefs-tools](https://github.com/koverstreet/bcachefs-tools/tree/master) works fine. If I was a betting man I'd guess the issue is fixed by one of the udev-related commits from 7 May. It also gets rid of all the annoying warnings about not finding bcachefs superblocks as it walks the device tree.

**Comment by jezcope** [comment]
Yes, that's correct. Using the following overlay to my nixpkgs causes everything to work as expected:

```nix
final: prev: { bcachefs-tools = inputs.bcachefs-tools.packages.${prev.system}.bcachefs; }
```
