### ISSUE TITLE
RNote crash

### ISSUE THREAD

**Issue by lVentus** [NixOS/nixpkgs#313375]
### Describe the bug
Crash after some draw. Especialy when using selector or creating a new tab
And sometimes , pen draw become rectangle selector.
I don't know it is rnote's problem or pkgs problem or My nixos config problem. I report an issue both sides.

### Steps To Reproduce
just draw or open a new Tab

### Expected behavior
work normally

### Additional context
here is the log:

```
(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:108:46-47: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:109:56-57: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:111:56-57: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:112:58-59: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:113:57-58: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.553: Theme parser error: gtk.css:114:59-60: Expected a valid selector

(rnote:3687): Gtk-WARNING **: 11:42:05.842: Allocating size to RnAppWindow 0x55ab188290a0 without calling gtk_widget_measure(). How does the code know the size to allocate?

(rnote:3687): Gtk-WARNING **: 11:42:06.018: Allocating size to RnAppWindow 0x55ab188290a0 without calling gtk_widget_measure(). How does the code know the size to allocate?
Segmentation fault (core dumped)
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source````

using flakes and HM
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
I can't reproduce your issue. I've tried running `nix run nixpkgs/33d1e75#rnote` (with and without `GSK_RENDERER=gl` variable you mentioned in https://github.com/flxzt/rnote/issues/1103), drew a few strokes, selected them and moved around, made a new tab and repeated these actions. No crash.

Can you try temporarily removing your custom gtk.css and trying to repro this issue? It should be in `~/.config/gtk-4.0/gtk.css`. Maybe a custom theme is making rnote crash.

**Comment by lVentus** [comment]
> I can't reproduce your issue. I've tried running `nix run nixpkgs/33d1e75#rnote` (with and without `GSK_RENDERER=gl` variable you mentioned in https://github.com/flxzt/rnote/issues/1103), drew a few strokes, selected them and moved around, made a new tab and repeated these actions. No crash.
> 
> 
> 
> Can you try temporarily removing your custom gtk.css and trying to repro this issue? It should be in `~/.config/gtk-4.0/gtk.css`. Maybe a custom theme is making rnote crash.

I just found gtk part is not a problem. I got my pen out of charge, so I tested with mouse. It didn't crash. I can do everything. but with a pen, it may crash, when I just click some menu buttons. So it should be a stylus problem?

**Comment by gepbird** [comment]
> I just found gtk part is not a problem. I got my pen out of charge, so I tested with mouse. It didn't crash. I can do everything. but with a pen, it may crash, when I just click some menu buttons. So it should be a stylus problem?

That's good to know it works with mouse. Does it crash when you try to use the side buttons on the stylus, or it even crashes when you're drawing and "left clicking" with the stylus? What tablet driver do you use and what's the model of your tablet?

I'm trying it with open tablet driver using a veikk s640, drawing, selecting, clicking on buttons work with the stylus for me. Side buttons don't do anything, but that means it doesn't crash.

**Comment by lVentus** [comment]
> > I just found gtk part is not a problem. I got my pen out of charge, so I tested with mouse. It didn't crash. I can do everything. but with a pen, it may crash, when I just click some menu buttons. So it should be a stylus problem?
> 
> That's good to know it works with mouse. Does it crash when you try to use the side buttons on the stylus, or it even crashes when you're drawing and "left clicking" with the stylus? What tablet driver do you use and what's the model of your tablet?
> 
> I'm trying it with open tablet driver using a veikk s640, drawing, selecting, clicking on buttons work with the stylus for me. Side buttons don't do anything, but that means it doesn't crash.

Yes, it crash when I just draw or left cliking. side button doesn't do anything.
I am using a surface pro 8. with surface. And driver should be IPTSd.
With xournalpp it works perfect.
