### ISSUE TITLE
Package request: colima

### ISSUE THREAD

**Issue by webhive** [NixOS/nixpkgs#313422]
Colima - container runtimes on macOS (and Linux) with minimal setup.

source URL: https://github.com/abiosoft/colima
* license: mit
unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukium** [comment]
colima has been available in nixpkgs for more than two years.
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=colima

**Comment by webhive** [comment]
> colima has been available in nixpkgs for more than two years. https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=colima

Actually I did not mentioned package, but flake. 
Some packages like hyperland for instance, available via both packages and flakes. Colima source code has flake, so why not add it to your flake search. 

Anyway if you don't need it - feel free to ignore.

**Comment by natsukium** [comment]
I'm not interested in adding it, but you can open a PR for `nixos-search`.
https://github.com/NixOS/nixos-search?tab=readme-ov-file#adding-flakes

Anyway, this is not an issue for nixpkgs.
