### ISSUE TITLE
Syncthing Tray: fails to open web ui in new tab or embedded into the app

### ISSUE THREAD

**Issue by Redhawk18** [NixOS/nixpkgs#313566]
### Steps To Reproduce
1. install syncthingtray
2. right click and click "open syncthing"
3. nothing happens

### Expected behavior
For either the webui to open or the embeded web view to work

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/77415970/eb27ce6b-4e5d-414c-92a6-9def2cbe88c6)

### Notify maintainers
@doronbehar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.05 (Uakari), 24.05pre629267.3eaeaeb6b1e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nix-ld, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Hey so I ran `git checkout 3eaeaeb6b1e0` on the revision you reported in your `nix-info -m`, and I checked these part of the settings of syncthingtray:

![Screenshot from 2024-05-22 15-58-37](https://github.com/NixOS/nixpkgs/assets/10998835/245186d3-22f2-474d-a97a-62c60d6058f4)

And I didn't experience the issue. How are your settings in that section?

**Comment by Redhawk18** [comment]
> Hey so I ran `git checkout 3eaeaeb6b1e0` on the revision you reported in your `nix-info -m`, and I checked these part of the settings of syncthingtray:
> 
> ![Screenshot from 2024-05-22 15-58-37](https://private-user-images.githubusercontent.com/10998835/332805473-245186d3-22f2-474d-a97a-62c60d6058f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTE1NDksIm5iZiI6MTcxNjM5MTI0OSwicGF0aCI6Ii8xMDk5ODgzNS8zMzI4MDU0NzMtMjQ1MTg2ZDMtMjJmMi00NzRkLWE5N2EtNjJjNjBkNjA1OGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE1MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTA3NTEzN2VhMDQyZWJjYzhlYzllNDQwODE4MDUxZmE4MTUyZTVkMTAwMGZkZDRmY2JlNGYyNGMxY2I2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrPBFLF3CMuRfoPPBZsMxjcgGmNE5TkoaENB9tFYntM)
> 
> And I didn't experience the issue. How are your settings in that section?

I've tried both but I think I have a problem with my connection settings I keep having `internal errors`

**Comment by Redhawk18** [comment]
> > > Hey so I ran `git checkout 3eaeaeb6b1e0` on the revision you reported in your `nix-info -m`, and I checked these part of the settings of syncthingtray:
> > > ![Screenshot from 2024-05-22 15-58-37](https://private-user-images.githubusercontent.com/10998835/332805473-245186d3-22f2-474d-a97a-62c60d6058f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTE1NDksIm5iZiI6MTcxNjM5MTI0OSwicGF0aCI6Ii8xMDk5ODgzNS8zMzI4MDU0NzMtMjQ1MTg2ZDMtMjJmMi00NzRkLWE5N2EtNjJjNjBkNjA1OGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE1MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTA3NTEzN2VhMDQyZWJjYzhlYzllNDQwODE4MDUxZmE4MTUyZTVkMTAwMGZkZDRmY2JlNGYyNGMxY2I2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrPBFLF3CMuRfoPPBZsMxjcgGmNE5TkoaENB9tFYntM)
> > > And I didn't experience the issue. How are your settings in that section?
> > 
> > 
> > I've tried both but I think I have a problem with my connection settings I keep having `internal errors`
> 
> Sounds like a personal, specific user error. Are you using the syncthing NixOS module? Because it is not trivial to make syncthingtray get access to the API of it, if it is running under a dedicated `syncthing` user.

Just checked and its running under me.
![image](https://github.com/NixOS/nixpkgs/assets/77415970/410a45d6-1c35-47b2-9aa1-4b669d873c65)

**Comment by doronbehar** [comment]
> > Sounds like a personal, specific user error. Are you using the syncthing NixOS module? Because it is not trivial to make syncthingtray get access to the API of it, if it is running under a dedicated `syncthing` user.
> 
> Just checked and its running under me.

It is no surprise that `syncthingtray` runs as your user. I was talking about the `syncthing` daemon - does it run under your user?

**Comment by Redhawk18** [comment]
> > > Sounds like a personal, specific user error. Are you using the syncthing NixOS module? Because it is not trivial to make syncthingtray get access to the API of it, if it is running under a dedicated `syncthing` user.
> > 
> > 
> > Just checked and its running under me.
> 
> It is no surprise that `syncthingtray` runs as your user. I was talking about the `syncthing` daemon - does it run under your user?

I don't see the syncthing daemon, I have it running on my server but I don't see a local one.

**Comment by doronbehar** [comment]
> I don't see the syncthing daemon, I have it running on my server but I don't see a local one.

Then indeed connecting to your remote daemon wouldn't be trivial, you'd have to enter the API key and the server's address / IP manually. How did you do that?

**Comment by doronbehar** [comment]
Also, the remote server should be configured to accept connections from other hosts.

**Comment by doronbehar** [comment]
> Why is it not included by default on nix?

Because these are two distinct programs. There is no reason to bind between them so strongly.

Regarding the purpose of this issue, I'm having trouble understanding your setup, and it looks non-trivial, so you need to explain it thoroughly. The correct place to further help you is the discourse forum, so I'm closing this.

**Comment by doronbehar** [comment]
I'm also unsubscribing from this issue.
