### ISSUE TITLE
how to use fetchgitLocal ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#31363]
## Issue description
I am trying to package tegaki https://github.com/tegaki/tegaki which contains lots of interdependant python packages. Nixos can only deal with one python package in develop mode at a time so the others must be installed differently (even though I edit them frequently). I don't want to use fetchgit on a local repository because then I would have to set the hash for modules I am currently debugging/updating to python3.
fetchgitLocal seemed ideal because it doesn't require the hash but it requires +x access for  nixbuild group to my home directory (and folder /home/teto/tegaki) and write access into the subsequent .git folder. Then it messes up with the .git folder writing its own objects so I have to fix permissions afterwards.
Seems like I am not the only one having the problem https://github.com/bnikolic/casanix/commit/dade8c3789f5fa6ebeba3c524bf9c4558dbefd2b

Any idea how to "install" all the local python modules from the tegaki clone ? while having only one in develop mode.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by teto** [comment]
so this might in fact be a duplicate of https://github.com/NixOS/nixpkgs/issues/10873.

**Comment by teto** [comment]
nix 2 fetchGit solved this problem for me

**Comment by srghma** [comment]
@teto can you explain, if fetchGit is now preferable way to to make derivations from local git repos - the why not to remove fetchGitLocal?

**Comment by srghma** [comment]
and I cant find the example with fetchGit, can you help me please

**Comment by srghma** [comment]
finnaly found `nix 2 fetchGit` you are referring to [here](https://news.ycombinator.com/item?id=16444710)


```
src = fetchGit ./.;
```

**Comment by CMCDragonkai** [comment]
What was the purpose of a `fetchgitLocal` if `fetchgit` can already fetch local repositories?
