### ISSUE TITLE
Update request: tailscale 1.58.2 → 1.66.4 on 23.11 due to security vulnerability

### ISSUE THREAD

**Issue by reivilibre** [NixOS/nixpkgs#313678]
- Package name: `tailscale`
- Latest released version: 1.66.4

- Current version on the unstable channel: 1.66.4
- Current version on the stable/release channel: 1.58.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

The package on 23.11 is currently vulnerable and displaying this warning in the management interface:

![Screenshot 2024-05-22 at 14 00 37](https://github.com/NixOS/nixpkgs/assets/38398653/adf0104b-0c5a-4733-bfcf-297f6ad4bdd4)

**Notify maintainers**

@danderson @martinbaillie @twitchyliquid64 @06kellyjac @mfrw

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 06kellyjac** [comment]
I'll look to backport now

**Comment by 06kellyjac** [comment]
Backport created, posted in the security chat to check it's all correct and will be actioned.

Also for extra context I believe this warning is due to: https://tailscale.com/security-bulletins#ts-2024-005

**Comment by reivilibre** [comment]
Thank you so much, that was unreasonably quick of you!!

My company's IT department will be happy :D

**Comment by SuperSandro2000** [comment]
You can probably set [services.tailscale.package](https://search.nixos.org/options?channel=23.11&size=50&sort=relevance&type=packages&query=tailscale) to the package from unstable in the meantime

**Comment by LeSuisse** [comment]
Closing as backport was merged and 23.11 is now EOL.
