### ISSUE TITLE
kanata: Add possibility to add entire configuration file instead of specific parts

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#313777]
Currently it's only possible to configure kanata by specifying specific parts one at a time.
It's not possible to read a configuration from a file and use that instead of the specific parts.

I use HomeManager to manage the kanata configuration file and because it's also used for Windows this is the most platform neutral way for me without duplicating parts of the configuration.

As a workaround I did it like this for now: https://github.com/ThomasMader/nixos-config/commit/800a6b1e3969e0756fd1f157b47f8f6b71b889cd#diff-f5d135e83473357da3b5bba5a5473cae1c0de99f96e201b29f54e4443596a183R34-R52

But clearly that is not ideal. What I would want is to just keep the 'readFile' and uncomment the 'defcfg' part from the configuration file (https://github.com/ThomasMader/nixos-config/commit/800a6b1e3969e0756fd1f157b47f8f6b71b889cd#diff-1d1abb79d6770dbd0b834d856e85a3a3fc160f306b800d8950fdb16a980b8412R10-R25)

@jian-lin

**Comment by jian-lin** [comment]
I created https://github.com/NixOS/nixpkgs/pull/313822 to address this issue.  Could you help test it?

**Comment by ThomasMader** [comment]
Thanks a lot for the fast solution!
I tested it with my config and it works without any issues.
