### ISSUE TITLE
dovecot2 can't run with various memory allocators that aren't libc

### ISSUE THREAD

**Issue by bolives-hax** [NixOS/nixpkgs#313721]
### Describe the bug

dovecot2 can't run with various memory allocators that aren't libc

### Steps To Reproduce
use dovecot2 along with scudo or some of the allocators below

```
environment.memoryAllocator.provider = "scudo";  or = "graphene-hardened"; or "graphene-hardened-light"
```

using the scudo allocator scheme like provided by the nixpkgs hardened nixos profile/module results in error messages such as

```
May 22 10:40:48 dovecot[817]: auth: Error: Scudo ERROR: allocator is out of memory trying to allocate 0xd8 bytes
May 22 10:40:48 dovecot[817]: auth: Fatal: master: service(auth): child 973 returned error 1
May 22 10:40:48 dovecot[814]: master: Error: service(auth): command startup failed, throttling for 60.000 secs
```
Trying out "graphene-hardened" with or without applying the whole nixos hardened profile gives me the same issue.
upon closer inspection using coredumpctl I get

```
       Message: Process 812 (log) of user 0 dumped core.

                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module libdovecot.so.0 without build-id.
                Module log without build-id.
                Stack trace of thread 812:
                #0  0x00007ff02c16fefc __pthread_kill_implementation (libc.so.6 + 0x8fefc)
                #1  0x00007ff02c11fe86 raise (libc.so.6 + 0x3fe86)
                #2  0x00007ff02c108935 abort (libc.so.6 + 0x28935)
                #3  0x00007ff02c4a70e9 fatal_error (libhardened_malloc.so + 0x20e9)
                #4  0x00007ff02c4a7412 init_slow_path (libhardened_malloc.so + 0x2412)
                #5  0x00007ff02c4a784f malloc.cold (libhardened_malloc.so + 0x284f)
                #6  0x00007ff02bf36b0e _GLOBAL__sub_I_eh_alloc.cc (libstdc++.so.6 + 0xb8b0e)
                #7  0x00007ff02c4bb08e call_init (ld-linux-x86-64.so.2 + 0x508e)
                #8  0x00007ff02c4bb17c _dl_init (ld-linux-x86-64.so.2 + 0x517c)
                #9  0x00007ff02c4d1c30 _dl_start_user (ld-linux-x86-64.so.2 + 0x1bc30)
                ELF object binary architecture: AMD x86-64
```

or for the graphene-hardened-light one

```
               Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module libdovecot.so.0 without build-id.
                Module log without build-id.
                Stack trace of thread 811:
                #0  0x00007fce8a6b6efc __pthread_kill_implementation (libc.so.6 + 0x8fefc)
                #1  0x00007fce8a666e86 raise (libc.so.6 + 0x3fe86)
                #2  0x00007fce8a64f935 abort (libc.so.6 + 0x28935)
                #3  0x00007fce8a9ee0e9 fatal_error (libhardened_malloc-light.so + 0x20e9)
                #4  0x00007fce8a9ee404 init_slow_path (libhardened_malloc-light.so + 0x2404)
                #5  0x00007fce8a9ee825 malloc.cold (libhardened_malloc-light.so + 0x2825)
                #6  0x00007fce8a47db0e _GLOBAL__sub_I_eh_alloc.cc (libstdc++.so.6 + 0xb8b0e)
                #7  0x00007fce8aa0208e call_init (ld-linux-x86-64.so.2 + 0x508e)
                #8  0x00007fce8aa0217c _dl_init (ld-linux-x86-64.so.2 + 0x517c)
                #9  0x00007fce8aa18c30 _dl_start_user (ld-linux-x86-64.so.2 + 0x1bc30)
                ELF object binary architecture: AMD x86-64
```

currently using  nixpkgs @

https://github.com/NixOS/nixpkgs/pull/313467/commits/bbe77ffdfaedc10a95d0b1bc704d20cefdf7a5fc

but the issue is also existent on unstable - 23.11

Also it happens regardless of the amount of memory present on the system as it seems

### Expected behavior
Maybe it would make sense to notify the user that these allocators can't be used along with dovecot2 

### Notify maintainers

@fpletz

**Comment by bolives-hax** [comment]
since this is partially the fault of dovecot2 I will mention the issue on their mailinglist as well

**Comment by surfaceflinger** [comment]
> Maybe it would make sense to notify the user that these allocators can't be used along with dovecot2

nah, there's way too much software that won't work with alternative mallocs. chromium won't work with anything except from glibc malloc or hardened-malloc, firefox will break with any custom malloc, chrony will get stuck with hardened-malloc, and lots of other issues.

also I feel like most of these memory issues can show up and later disappear unnoticed once some upstream code changes mem behavior. also doing an if in module that would check if you have custom malloc enabled implies that the maintainer of that module will periodically verify if that's still the case.

not really our problem, consider `environment.memoryAllocator.provider` a hack, not something that you should want. even hardened distros targeted at TOR users are now dropping hardened-malloc.

**Comment by surfaceflinger** [comment]
btw, you can try `boot.kernel.sysctl."vm.max_map_count" = 2147483642;` with hardened-malloc and -light

**Comment by eclairevoyant** [comment]
As mentioned in the description for `environment.memoryAllocator.provider`:

> Selecting an alternative allocator (i.e., anything other than `libc`) may result in instability, data loss, and/or service failure.

In any case, there's nothing to be done in nixpkgs.
