### ISSUE TITLE
Steam can't find 32-bit libraries

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#31384]
## Issue description

I have 32-bit stuff in `configuration.nix`:

```
hardware = {
  opengl.driSupport32Bit = true;
  pulseaudio.support32Bit = true;
};
```

When I try to run Steam, this happens:

![screenshot_2017-11-08_07-31-15](https://user-images.githubusercontent.com/1643293/32536552-d92dd3c6-c456-11e7-8908-8c81315501d1.png)

```
$ steam
cp: cannot create regular file '/home/chronos/.local/share/Steam/bootstrap.tar.xz': Permission denied
Running Steam on nixos 18.03.git.467b9b7 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Pins potentially out-of-date, rebuilding...
mkdir: cannot create directory ‘/nix/store/dy0nrgdhzdfy44ss16scqw9kp2s3cdx4-steam-fhs/steamrt/pinned_libs_32’: Read-only file system
mkdir: cannot create directory ‘/nix/store/dy0nrgdhzdfy44ss16scqw9kp2s3cdx4-steam-fhs/steamrt/pinned_libs_64’: Read-only file system
/home/chronos/.local/share/Steam/steam.sh: line 874: /steamrt/run.sh: No such file or directory
Error: You are missing the following 32-bit libraries, and Steam may not run:
libgobject-2.0.so.0
libglib-2.0.so.0
libgio-2.0.so.0
libgtk-x11-2.0.so.0
libpulse.so.0
libgdk_pixbuf-2.0.so.0
libva.so.1
libbz2.so.1.0
libz.so.1
libvdpau.so.1
libva.so.1
libva-x11.so.1
Error:
You are missing the following 32-bit libraries, and Steam may not run:
libgobject-2.0.so.0
libglib-2.0.so.0
libgio-2.0.so.0
libgtk-x11-2.0.so.0
libpulse.so.0
libgdk_pixbuf-2.0.so.0
libva.so.1
libbz2.so.1.0
libz.so.1
libvdpau.so.1
libva.so.1
libva-x11.so.1
Press enter to continue: 
Installing breakpad exception handler for appid(steam)/version(1510099762)
Installing breakpad exception handler for appid(steam)/version(1510099762)
Installing breakpad exception handler for appid(steam)/version(1510099762)
Failed to load steamui.so - dlerror(): libgobject-2.0.so.0: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1510099762)
Installing breakpad exception handler for appid(steam)/version(1510099762)
[2017-11-08 07:30:09] Startup - updater built Nov  7 2017 13:43:41
[2017-11-08 07:30:09] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-11-08 07:30:09] Checking for update on startup
[2017-11-08 07:30:09] Checking for available updates...
[2017-11-08 07:30:10] Download skipped by HTTP 304 Not Modified
[2017-11-08 07:30:10] Nothing to do
[2017-11-08 07:30:10] Verifying installation...
[2017-11-08 07:30:10] Performing checksum verification of executable files
[2017-11-08 07:30:11] Verification complete
```

## Technical details

* System: 18.03.git.467b9b7 (Impala)
* Nix version: 1.11.15
* Nixpkgs version: 467b9b7a930bc6de60023dbec1c8b914b882e2d9 (yesterday's master)
* Sandboxing enabled: yes

**Comment by yegortimoshenko** [comment]
This seemingly was broken in the latest Steam beta update.

**Comment by yegortimoshenko** [comment]
/cc @abbradar 

Sorry for summoning you way too often, but it seems that my interest often lies in parts of the tree that you effectively maintain :-)

There is still some time before Steam runtime updates migrate into release and Steam package breaks completely, so this is mostly a heads-up. I might look into it, but I don't have any idea how to fix it, yet.

**Comment by abbradar** [comment]
I'm okay with summons ~_^

Do I get it correctly that this is reproducible on Steam beta?

**Comment by yegortimoshenko** [comment]
Yes, it is. Just enable public Steam beta and Steam breaks. To recover, delete `~/.local/share/Steam/package/beta`.

**Comment by qrvaelet** [comment]
I can reproduce this issue with Steam beta.

* System: 18.03pre119245.5cfd049a03 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre119245.5cfd049a03
* Sandboxing enabled: no

**Comment by abbradar** [comment]
Seems that Steam Beta uses new Steam Runtime version which we don't have. Maybe they'll push it to general channel when it gets out of beta -- not sure how else could we fetch it.

In general I think that maybe we can drop our own Steam Runtime for Steam -- it would help with this case but may break games and needs extensive testing. Steam runs for me without our Runtime (Beta too).

**Comment by qrvaelet** [comment]
If you make some changes I'd be more than happy to test them out.

**Comment by yegortimoshenko** [comment]
It *should* be in http://repo.steamstatic.com/steamrt/dists/scout_beta/ but I don't see it updated. Or perhaps, the date they set at this server is just wrong...

> In general I think that maybe we can drop our own Steam Runtime for Steam -- it would help with this case but may break games and needs extensive testing. 

What is the alternative to building the runtime by ourselves?

**Comment by abbradar** [comment]
Just use native Steam runtime. I'm not sure how well it works -- initially we moved _from_ it because we needed to override several libraries. However recently Steam made some changes which should help their Runtime to interact better with e.g. new Mesa drivers.

**Comment by yegortimoshenko** [comment]
I'll try it out with my games and I'll make a list of games that do or do not work: I have a few games in my library that currently do not work, would be interesting to see how they behave `steam-native`.

**Comment by abbradar** [comment]
Sorry, I may have been misunderstood. What I meant is not "native" Steam Runtime (composed from NixOS libraries) but not using our Steam Runtime build at all. You can achieve it by e.g. commenting out `export STEAM_RUNTIME` in `chrootenv.nix`.

**Comment by yegortimoshenko** [comment]
Oh, I see, thanks! Going to try that out.

**Comment by yegortimoshenko** [comment]
Given that `steam-no-runtime` is `steam` with `STEAM_RUNTIME` commented out in `chrootenv.nix`:

| Game | Steam | Steam w/o `STEAM_RUNTIME` | Steam beta w/o `STEAM_RUNTIME` |
| -------- | ---------- | -------------------------- | ----------------------------------- |
| Din's Curse | [No multiplayer (tweet)](https://twitter.com/yegortimoshenko/status/928036462053994496) | [No multiplayer (tweet)](https://twitter.com/yegortimoshenko/status/928036462053994496) | [Doesn't start (log)](https://gist.githubusercontent.com/yegortimoshenko/207944be1dea5dcdaa45bf4b6f5ce150/raw/a7f9f806e30460ace016af6f8afbd03750542e05/20171110-steam-no-runtime-dinscurse.log) |
| Jazzpunk | OK | OK | No sound |
| Quadrilateral Cowboy | OK | OK | OK |
| Planescape: Torment: Enhanced Edition | OK | OK | OK |
| The Talos Principle | OK | OK | OK |
| Undertale | OK | OK | OK |

I'll keep this list updated with further testing...

**Comment by abbradar** [comment]
I'll help to fill this list out later, thanks!

**Comment by corngood** [comment]
#31512 is my local fix for the beta without using valve's runtime.  I'm not sure how it worked with previous runtimes, but now it's expecting `$STEAM_RUNTIME/run.sh` to set the library path.

**Comment by yegortimoshenko** [comment]
@abbradar Mesa (Intel HD 3000).

**Comment by abbradar** [comment]
It seems that the runtime itself indeed didn't change. What has indeed changed are only scripts:
```
6871a6872
> 7365eb38c1b3174208437f48c93fe4a45a5dd2dd44493a5392f8ed84ee08453e  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/version.txt
7642a7644
> 7fd43763227e47f5a16ddad3ecfb1262ad6f368cac44a99da531a665856bfb7e  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh
8152a8155
> 88bdfa49721c65b90bfc716b6de37f359ff70516232cdcff1ca3cb54b85d1f38  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/checksum
12094d12096
< ca36f06a51df38f21bdab63466de90d11a6b9fc3ad2ed056ebd7b68ae33da4a5  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/checksum
12965a12968
> d875c55813c08c18be2b0e89c8ce104ce37efe59392cc10b80171f14dfb90575  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/README.txt
14097d14099
< eb89ebe7c37a3b201c74b4b3c3da002c23139254893369485cb8ff02e8db6028  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh
14398d14399
< f1df9b8139fdf0ba9e06e2da090b203419fd276f21c34fffc990c6ecb90f3f4b  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/version.txt
15083d15083
< fd106311f68906c6aee44d5c0e004100a39e4e21cf51cf2bd658d164f3deccdd  /home/shlomo/.local/share/Steam/ubuntu12_32/steam-runtime/README.txt
```

Therefore I suppose we can keep our Runtime to have more control and make `run.sh` to fulfill what's required for Beta.

**Comment by dtzWill** [comment]
Adding this here in case it helps someone in the future:

Just encountered this, using latest 17.09 or master didn't (seem to) help... until I, inspired by comment above, decided to nuke the package directory:

```
$ rm ~/.local/share/Steam/package/*
```

This seems "safe" but I'm not familiar enough with Steam to be confident in recommending it O:).

I was multi-tasking a bit at the time--and scrambling to get steam working again while friend is waiting on me... so it's possible this was only necessary because of a mistake on my part :P.

GLHF!
