### ISSUE TITLE
Problems with JDK Infrastructure

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#313848]
Copy-pasting [this Discourse post](https://discourse.nixos.org/t/improve-the-jdk-infrastructure-on-nixpkgs/45678) from @jlesquembre 

## The Problem

The JDK needs better support in nixpkgs. The JDK ecosystem is large and critical, and improved support would benefit not only the Java ecosystem but also many others, such as Kotlin, Scala, Clojure, and Groovy.

I am grateful for the past efforts of contributors to the JDK infrastructure. But my impression is that many, if not all, have moved on to other projects, leaving the JDK ecosystem with very limited support. I also believe that currently, no one with commit access is particularly interested in the JDK. Some of the issues I consider urgent include:

- JDK versions are not updated automatically. There is no updateScript for JDK derivations.
- JDK versions are updated slowly. For example, the current JDK LTS is 21. We are on version 21.0.0, while the latest release is 21.0.3. Nixpkgs unstable is three versions behind.
- JDK-related PRs, even minor ones, take a long time to be reviewed and merged. For instance, I submitted a PR to update the default JDK from version 19 to version 21. Version 19 was already end-of-life and marked as insecure at the time, but it took approximately three months to be merged.
- We have too many JDK flavors in nixpkgs. Some of these are likely unnecessary and could be removed. For example, AdoptOpenJDK is a deprecated project replaced by Adoptium (which is also available in nixpkgs).

There are many more areas for improvement, but in my opinion, we should first address the points mentioned above.

We need to put more effort into the JDK infrastructure and seek the help of contributors with commit access to unblock existing PRs and incentivize new ones.

## Next steps and call to action

First and foremost, I’d like to identify anyone interested in helping improve the JDK infrastructure on nixpkgs. My goal is to achieve incremental improvements and get changes merged efficiently. To achieve this, even just getting some reviewers and testers for PRs would be extremely helpful. We can discuss the technical details in a separate thread.

Who is interested in contributing to a better JDK infrastructure on nixpkgs? Is anyone with commit access to nixpkgs interested in lending a hand with this effort?

On my end, I’ll continue trying to improve the JDK ecosystem on nixpkgs. For now, I’m putting together a list of ideas for what to do next, and I’ll share it once I’ve cleaned it up a bit.

**Comment by peterhoeg** [comment]
Related issue: https://github.com/NixOS/nixpkgs/issues/313216

**Comment by AndersonTorres** [comment]
Closing as duplicate.
