### ISSUE TITLE
Package request: snd_hda_macbookpro

### ISSUE THREAD

**Issue by DoYouEvenSheesh** [NixOS/nixpkgs#313843]
**Project description**
A kernel driver for sound on Macs with Cirrus 8409 HDA chips. This will fix the [no audio](https://github.com/NixOS/nixos-hardware/tree/master/apple/macbook-pro/14-1#audio) issue with 2016/2017 macbook-pros
**Metadata**

* homepage URL: https://github.com/davidjo/snd_hda_macbookpro
* source URL: https://github.com/davidjo/snd_hda_macbookpro
* license: none
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DoYouEvenSheesh** [comment]
> > license: mit
> 
> Where did you got that from? I don't see a LICENSE file or anything mentioning MIT in readme

Sorry my bad I just assumed it was

**Comment by DoYouEvenSheesh** [comment]
> related issue: [NixOS/nixos-hardware#688](https://github.com/NixOS/nixos-hardware/issues/688)
> 
> (my iMac 18,3 was given to my brother a while ago)

But the PR should be against nixpkgs and not nixos-hardware

**Comment by therainydev** [comment]
Since not having this driver is a major problem for me (I don't want to boot into macOS every time I have to do something requiring audio) I'm going to try to package it. No guarantees, though, since this is my first time packaging anything.

**Comment by paepckehh** [comment]
https://github.com/NixOS/nixpkgs/pull/322771

**Comment by Guanran928** [comment]
It's going to take a few days until staging merges with unstable

**Comment by snoweuph** [comment]
Hi, i'm on a macbook pro 13,2 Inch Touchbar.

just a Day ago I was using Fedora 41 on this notebook, and the driver from above worked perfectly for me. 
Now I don't have any audio anymore.

Looking at the patch, did I understand correctly that its automaticly applied on kernel `6.6` and above? because im on NixOS `25.05` on Kernel `6.12.35` and don't have any sound.
