### ISSUE TITLE
cmake-language-server hangs during nix-review runs

### ISSUE THREAD

**Issue by fabaff** [NixOS/nixpkgs#313911]
### Describe the bug
When using `nix-review` it happens that `cmake-language-server` makes the run to hang. My first guess is that the issue could be performance related (aka my local machine is not powerful enough) as nobody else is affected. 

### Steps To Reproduce
1. `nix-review pr YXZ` assuming that `cmake-language-server` involved
2. Hang around 60% when `cmake-language-server` is checked

### Expected behavior
`nix-review` to pass.

### Additional context
 `nix-review pr -P cmake-language-server YXZ` helps.

### Notify maintainers

@kira-bruneau, do you have a hint on this.  

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05pre624623.062ca2a9370a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hakan-demirli** [comment]
Mine stuck on 43% during `home-manager switch`. Cancelling the current process and retrying solved the issue.

**Comment by hakan-demirli** [comment]
I also cant reproduce it. It's all good on my side.

**Comment by fabaff** [comment]
Let's close this for now.
