### ISSUE TITLE
Build failure: python3Packages.pyside6

### ISSUE THREAD

**Issue by 999eagle** [NixOS/nixpkgs#313908]
### Steps To Reproduce

1. build `python3Packages.pyside6`

### Build log

https://gist.github.com/999eagle/2aa89778ec19087f800f4dd49a2069ea

### Additional context

most likely this is broken due to #313360 being merged without also updating pyside6 to 6.7.1 (which seems to be not released as of now)

### Notify maintainers

@gebner @Enzime (pyisde6 maintainers)
@K900 @SuperSandro2000 (approved/merged the mentioned pr)

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.11 (Vicuña), 24.11.20240522.4a817d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-lixpre20240523-829521b
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Yeah, this is pretty common with PySide sadly. We'll update to 6.7.1 when that's out.
