### ISSUE TITLE
Build failure: nixosTests.nixos-test-driver

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#313962]
### Steps To Reproduce

1. nix-build -A nixosTests.nixos-test-driver

### Build log

![image](https://github.com/NixOS/nixpkgs/assets/5861043/967cdfdf-d94d-47c2-aef9-58c577e1f04d)

Logs: https://termbin.com/5wfj

```
 > build/lib/test_driver/logger.py:230:21: UP037 [*] Remove quotes from type annotation
       > test_driver/logger.py:230:21: UP037 [*] Remove quotes from type annotation
       > Found 2 errors.
```

### Additional context

I'm out of context on this. This seems too fundamental to be broken. It is breaking all NixOS tests?

> nix build .#k3s.passthru.tests.single-node
Nginx test also fails the same.

I could not build using:
> nix build .#nixosTests.nixos-test-driver
> nix build .#nixos-test-driver

![image](https://github.com/NixOS/nixpkgs/assets/5861043/daafc887-ec53-4954-88a9-b3f47c7ff270)

### Notify maintainers

CC @wegank

Update: Bisect answer was #313870

**Comment by superherointj** [comment]
![image](https://github.com/NixOS/nixpkgs/assets/5861043/beeebc98-fb67-4674-b947-926b1ba424e1)

**Comment by superherointj** [comment]
https://github.com/NixOS/nixpkgs/pull/313870

**Comment by wegank** [comment]
Oh, that was quick, I'm still building ruff on my machine...

**Comment by drupol** [comment]
A solution has been found @GaetanLepage is preparing the PR.
