### ISSUE TITLE
All bzip2 src URLs are 404

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#31396]
## Issue description
All the urls for bzip2 package 404.

### Steps to reproduce
wget any of them; for example, this is the new URL for one of them
http://ftp.suse.com/pub/people/sbrabec/bzip2/old/tarballs/bzip2-1.0.6.0.1.tar.gz

Note the `old` path. Alternatively garbage collect fully (if it will let you; grab a fresh box) and try to build anything.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
Affects both master and 17.09, any nix system.

**Comment by Fuuzetsu** [comment]
Override without rebuild:

```
  bzip2 = super.bzip2.overrideAttrs (oldAttrs: {
    src = fetchurl {
      url = "http://ftp.suse.com/pub/people/sbrabec/bzip2/old/tarballs/${oldAttrs.name}.tar.gz";
      sha256 = "0b5b5p8c7bslc6fslcr1nj9136412v3qcvbg6yxi9argq9g72v8c";
    };
  });
```

**Comment by vielmetti** [comment]
I think this is the person involved: https://connect.opensuse.org/pg/profile/sbrabec

@stanislav-brabec ?

**Comment by stanislav-brabec** [comment]
When I released the original bzip2 patches, I did not expect that upstream will ignore it and development will stop.

Now it seems that it will forever remain only a downstream modification.

If it makes change for you, I can return old packages back to the top directory, and create new "for_upstream" tarball. It would be named 1.0.6.0.2.

But some re-organization is required, as original for_downstream patches were not versioned.

**Comment by stanislav-brabec** [comment]
I reverted the original directory structure and files, and added warnings where structure is illogical.

**Comment by stanislav-brabec** [comment]
I reverted the original directory structure and files, and added warnings where structure is illogical.

**Comment by stanislav-brabec** [comment]
I reverted the original directory structure and files, and added warnings where structure is illogical.

**Comment by vcunat** [comment]
Resolved long ago.  Thanks / díky :-)
