### ISSUE TITLE
NixOS crashes with two GPT swap parts with same name

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#3140]
In my ignorance, I named a bunch of GPT partitions 'primary' in the process of provisioning my machine. As a result, systemd got quite confused about my two swap partitions:

    [cstrahan@nixos:~]$ sudo nixos-rebuild switch
    building Nix...
    building the system configuration...
    updating GRUB 2 menu...
    installing the GRUB 2 boot loader on /dev/sda...
    Installation finished. No error reported.
    installing the GRUB 2 boot loader on /dev/sdb...
    Installation finished. No error reported.
    stopping the following units: network-interfaces.target, remote-fs.target, systemd-modules-load.service, zfs-mount.service
    activating the configuration...
    setting up /etc...
    starting the following units: default.target, getty.target, ip-up.target, multi-user.target, network-interfaces.target, network.target, paths.target, remote-fs.target, slices.target, sockets.target, swap.target, systemd-modules-load.service, timers.target
    A dependency job for swap.target failed. See 'journalctl -xn' for details.
    warning: the following units failed: dev-disk-by\x2dpartlabel-primary.swap
    
    ● dev-disk-by\x2dpartlabel-primary.swap - /dev/disk/by-partlabel/primary
       Loaded: loaded
       Active: failed (Result: exit-code) since Mon 2014-06-30 01:59:04 UTC; 24ms ago
         What: /dev/disk/by-partlabel/primary
      Process: 5161 ExecActivate=/nix/store/0syx0na4m3nah8m0ks48m5rs485r60pb-util-linux-2.24.1/sbin/swapon /dev/disk/by-partlabel/primary (code=exited, status=255)
    
    Jun 30 01:59:04 nixos swapon[5161]: swapon: /dev/sdb3: read swap header failed: No such file or directory
    Jun 30 01:59:04 nixos systemd[1]: dev-disk-by\x2dpartlabel-primary.swap swap process exited, code=exited status=255
    Jun 30 01:59:04 nixos systemd[1]: Failed to activate swap /dev/disk/by-partlabel/primary.
    Jun 30 01:59:04 nixos systemd[1]: Unit dev-disk-by\x2dpartlabel-primary.swap entered failed state.
    
    [cstrahan@nixos:~]$ journalctl -xn
    -- Logs begin at Mon 2014-06-30 01:52:20 UTC, end at Mon 2014-06-30 01:59:04 UTC. --
    Jun 30 01:59:04 nixos systemd-modules-load[5158]: Failed to insert 'pcc_cpufreq': No such devic
    Jun 30 01:59:04 nixos systemd[1]: Started Load Kernel Modules.
    Jun 30 01:59:04 nixos systemd[1]: Reached target Multi-User System.
    Jun 30 01:59:04 nixos systemd[1]: Reloading D-Bus System Message Bus.
    Jun 30 01:59:04 nixos dbus[1721]: [system] Reloaded configuration
    Jun 30 01:59:04 nixos dbus-send[5167]: method return sender=org.freedesktop.DBus -> dest=:1.4 r
    Jun 30 01:59:04 nixos systemd[1]: Reloaded D-Bus System Message Bus.
    Jun 30 01:59:04 nixos dbus[1721]: [system] Reloaded configuration
    Jun 30 01:59:04 nixos nixos[3751]: switching to system configuration /nix/store/b76h9alsxdmqns1
    Jun 30 01:59:04 nixos sudo[3734]: pam_unix(sudo:session): session closed for user root
    
    [cstrahan@nixos:~]$ cat /etc/nixos/hardware-configuration.nix
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    { config, pkgs, ... }:
    
    {
      imports =
        [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
        ];
    
      boot.initrd.availableKernelModules = [ "xhci_hcd" "ahci" "usbhid" ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];
    
      fileSystems."/" =
        { device = "/dev/sda3";
          fsType = "ext4";
        };
    
      fileSystems."/boot" =
        { device = "/dev/md0";
          fsType = "ext4";
        };
    
      swapDevices =
        [ { device = "/dev/sda4"; }
          { device = "/dev/sdb4"; }
        ];
    
      nix.maxJobs = 8;
    }

I'm pretty sure this has something to do with why my ssh sessions would last about 20s, before they would drop and require rebooting the machine.

I don't think we should we be using partition labels to identify partitions when the configuration has path like "/dev/sdaN", no?

**Comment by Profpatsch** [comment]
@cstrahan can you reproduce this with a recent `nixpkgs/nixos`?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by zimbatm** [comment]
I don't have any swap devices but all my generated hardware-configuration.nix files use `/dev/disk/by-uuid/` paths. Assuming this has been fixed.
