### ISSUE TITLE
Wireplumber extraConfig & extraPackages doesn't seem to be working

### ISSUE THREAD

**Issue by moleculezz** [NixOS/nixpkgs#314029]
### Describe the bug
I'm trying to do an ALSA device specific configuration with wireplumber. The code builds, and the files are created in `/nix/store`, but they don't seem to be linked anywhere else on the system and are not being loaded.

I followed this PR to use the new config
[https://github.com/NixOS/nixpkgs/pull/292115](url)

And used this guide as well.
[https://nixos.wiki/wiki/PipeWire#Controlling_the_ALSA_devices](url)

### Steps To Reproduce
1. I created the following
```
services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
    wireplumber.enable = true;

    wireplumber.configPackages = [
      (pkgs.writeTextDir "share/wireplumber/wireplumber.conf.d/99-alsa-low-latency.conf" ''
        "monitor.alsa.rules" = [
          {
            matches = [
              { "node.name" = "alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
              { "node.name" = "alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
            ];
            actions = {
              update-props = {
                "audio.rate" = 192000;
                "api.alsa.period-size" = 512;
                "api.alsa.period-num" = 3;
              };
            };
          }
        ];
      '')
    ];

    wireplumber.extraConfig = {
      "98-alsa-low-latency" = {
        "monitor.alsa.rules" = [
          {
            matches = [
              { "node.name" = "alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
              { "node.name" = "alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
            ];
            actions = {
              update-props = {
                "audio.rate" = 192000;
                "api.alsa.period-size" = 512;
                "api.alsa.period-num" = 3;
              };
            };
          }
        ];
      };
    };
  };
```
3. Ran `nixos-rebuild switch` without issues
4. I ran `find /` but only found the files under `/nix/store`
5. Also ran `pw-dump | grep audio.rate` and this also returned empty definitions.

### Expected behavior
I expect the files to be loaded by wireplumber, but they are not.

### Notify maintainers
@hcsch 
@K900 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2-rt11, NixOS, 24.05 (Uakari), 24.05.20240521.3eaeaeb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/57rsy3z79kvxah2l4j13bjwpsgxkbhby-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hcsch** [comment]
I think what's happening in this case is that your matchers are not matching anything. POSIX extended regular expression matchers need to start with a `~`, otherwise WirePlumber will try to match characters like `.*` literally.
I think you'd want
```
services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
    wireplumber.enable = true;

    wireplumber.extraConfig = {
      "98-alsa-low-latency" = {
        "monitor.alsa.rules" = [
          {
            matches = [
              { "node.name" = "~alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
              { "node.name" = "~alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S49C91841831EB-00.*"; }
            ];
            actions = {
              update-props = {
                "audio.rate" = 192000;
                "api.alsa.period-size" = 512;
                "api.alsa.period-num" = 3;
              };
            };
          }
        ];
      };
    };
  };
```

Sadly WirePlumber doesn't have a config dump feature yet, unlike PipeWire. You can find out if you're configs are being used though by determining the PID of the WirePlumber daemon with `systemctl --user status wireplumber.service` and then looking at the environment variables with `tr '\0' '\n' < /proc/<pid>/environ`. `XDG_DATA_DIRS` is the environment variable with which your config files will be passed to WirePlumber. `nix why-depends <store-path>` or `nix-tree /run/current-system/` searching for `wireplumber` could also help.

**Comment by moleculezz** [comment]
Ahh, I understand now. The XDG_DATA_DIRS points directly to the `/nix/store`. 
That solved it.
Thanks!
