### ISSUE TITLE
CODEOWNERS: exclude lib/maintainers.nix from the match?

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#31401]
@edolstra and @nbp are listed as code owners for `/lib`. That means they are requested for review whenever a new maintainer is added to the list. Last matching pattern is used, so if `/lib/maintainers.nix` is added on its own line without any users, this would be fixed.

Feel free to close if this is intended.

**Comment by nbp** [comment]
Is there a way to specify any empty list of reviewers?
Otherwise, we could make it a bot, which checks that the patch is only adding lines, and that the files evaluate properly.

**Comment by yegortimoshenko** [comment]
I think just listing no users would work but to make sure that it parses @ghost user can be added.
