### ISSUE TITLE
libcxx 4.0.1 failed to build

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#31403]
## Issue description

`libcxx` (the default version, 4.0.1) failed to build, because `xlocale.h` has been removed in `glibc 2.26`.

Maybe we should include [this patch](https://github.com/llvm-mirror/libcxx/commit/6e02e89f65ca1ca1d6ce30fbc557563164dd327e) from upstream ? Not sure if this is the correct way to fix the issue.

cc @dtzWill , thank you!

### Steps to reproduce

`nix-build -A libcxx`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by vcunat** [comment]
Fixed by 44cb95a23.
