### ISSUE TITLE
Podman is broken on unstable

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#314108]
### Describe the bug
Podman exits with an error on unstable.

### Additional context
```console
❯ podman
ERRO[0000] reading system config "/usr/share/containers/containers.conf": decode configuration /usr/share/containers/containers.conf: open /usr/share/containers/containers.conf: permission denied
```

### Notify maintainers
@NixOS/podman

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1-cachyos, NixOS, 24.05 (Uakari), 24.05.20240521.5710852`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Hmm. I can't seem to reproduce this (also on 24.05.20240521.5710852). How is your podman installed?

**Comment by wyndon** [comment]
```nix
  virtualisation = {
    oci-containers.backend = "podman";
    podman = {
      enable = true;
      autoPrune = {
        enable = true;
        dates = "weekly";
      };
      defaultNetwork.settings.dns_enabled = true;
    };
  };
```

**Comment by chewblacka** [comment]
Just for reference mine is:

    virtualisation = {
      podman = {
        enable = true;
        dockerCompat = true;
      };
    };
  
The only thing I can think of is to try removing the `oci-containers.backend` line to see if that is what is causing the issue?

**Comment by wyndon** [comment]
Found the culprit. I recently tried Deepin which uses dde-daemon. dde-daemon creates `/usr/share/uadp`. Removing `/usr/share` altogether makes podman work again.

A fix was introduced in https://github.com/NixOS/nixpkgs/pull/229924 but got reverted in https://github.com/NixOS/nixpkgs/commit/8e91f7c70d8ac339fda384f0bf029b02ca171700 for some reason. @wineee ?

**Comment by wineee** [comment]
Sorry, this is a mistake. I lost a patch when upgrading dde-daemon, should fix in https://github.com/NixOS/nixpkgs/pull/315021
