### ISSUE TITLE
glibc-2.26 breaks c2hs Haskell code generator

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#31411]
This issue breaks all Haskell packages that use `c2hs`, like `alsa-mixer`: https://hydra.nixos.org/build/63775150

**Comment by dezgeg** [comment]
Probably glibc upgrade fallout...

**Comment by NickHu** [comment]
This also breaks xmonad

**Comment by ikervagyok** [comment]
@NickHu sorry, closing my issue.
@mdorman please rename this issue to include `c2hs` in the title, as that's the piece causing this issue. this seems to be the place to look for a solution: https://github.com/haskell/c2hs/issues/192

**Comment by vcunat** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=NEWS;hb=HEAD

> On ia64, powerpc64le, x86-32, and x86-64, the math library now implements 128-bit floating point [...]

**Comment by corngood** [comment]
#31498 has my local fix, in case it helps someone get unblocked.
