### ISSUE TITLE
Floorp PWA desktop files assume floorp is installed to /usr/bin

### ISSUE THREAD

**Issue by VictorGamerLOL** [NixOS/nixpkgs#314115]
### Describe the bug
When installing a PWA using the Floorp browser (experimental toggle in settings), the installed desktop file uses /usr/bin/floorp as the path for the browser to run said PWA.

### Steps To Reproduce
1. Install Floorp
2. Enable experimental PWAs in settings
3. Install a PWA, e.g. Github or Excalidraw
4. Close the newly spawned PWA window
5. Try to launch the same PWA from your DE's application launcher

### Expected behavior
The PWA opens.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/51715529/daf4e414-622d-485a-9a0f-bcd721e6c581)

### Additional context
[upstream bug report](https://github.com/Floorp-Projects/Floorp/issues/1176), using flakes, installed via `home.packages`

### Notify maintainers

@christoph-heiss 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1-zen1, NixOS, 24.05 (Uakari), 24.05.20240521.5710852`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by christoph-heiss** [comment]
Thanks for reporting! As well as the upstream report!

I can look into it what we can do as I get time. But as I'm the only maintainer for Floorp and currently pretty much out of time due to university and $dayjob, I cannot promise any timeline unfortunately. But happy to review patches, of course, if you'd like to fix it yourself.

Can you provide such a generated `.desktop` file for further investigation?

**Comment by VictorGamerLOL** [comment]
@christoph-heiss sure, one such generated desktop file with the example of excalidraw can be found [here](https://paste.rs/SB0r6) (github doesn't allow for drag and drop of .desktop files)

**Comment by AtaraxiaSjel** [comment]
@christoph-heiss
Hello! I don't have experience maintaining and modifying large packages like Firefox (floorp), and I currently don't have much free time. However, I've discovered how floorp generates the .desktop file for PWA applications:

https://github.com/Floorp-Projects/Floorp-core/blob/2a5754a557f69bb4a68cec00f650ec47004c7057/browser/base/content/modules/ssb/LinuxSupport.mjs#L47

Maybe it will be helpful to you.

**Comment by christoph-heiss** [comment]
> However, I've discovered how floorp generates the .desktop file for PWA applications:
> 
> https://github.com/Floorp-Projects/Floorp-core/blob/2a5754a557f69bb4a68cec00f650ec47004c7057/browser/base/content/modules/ssb/LinuxSupport.mjs#L47
> 
> Maybe it will be helpful to you.

Thanks, that is indeed helpful! Should be relatively easy patchable by us then, from the looks of it.

**Comment by VictorGamerLOL** [comment]
@christoph-heiss upstream has [changed that line](https://github.com/Floorp-Projects/Floorp/issues/1176#issuecomment-2184604674) and now it will use the path it was in at the time of creating the PWA. It may not be too big of an issue if what they say about fixing it in the next version is true but now the patching will probably fail.
