### ISSUE TITLE
opensubdiv doesn't compile

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#31426]
## Issue description

opensubdiv-3.3.0 fails to compile. Relevant output:

```
[ 87%] Built target osd_gpu_obj
[ 89%] Building NVCC (Device) object opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
/nix/store/xd2mlzvlgmskbyyb33lz2vdq15k74xpr-glibc-2.26-75-dev/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"

/nix/store/xd2mlzvlgmskbyyb33lz2vdq15k74xpr-glibc-2.26-75-dev/include/bits/floatn.h(73): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/nix-build-opensubdiv-3.3.0.drv-0/tmpxft_00007876_00000000-6_cudaKernel.cpp1.ii".
CMake Error at osd_dynamic_gpu_generated_cudaKernel.cu.o.cmake:264 (message):
  Error generating file
  /tmp/nix-build-opensubdiv-3.3.0.drv-0/source/build/opensubdiv/CMakeFiles/osd_dynamic_gpu.dir/osd/./osd_dynamic_gpu_generated_cudaKernel.cu.o
```

### Steps to reproduce

build opensubdiv-3.3.0 from source.

## Technical details

* System: 18.03pre119292.cfafd6f5a8 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre119910.27831cbd86"
* Sandboxing enabled: false

**Comment by cillianderoiste** [comment]
I can reproduce this error when cuda is enabled.

**Comment by cillianderoiste** [comment]
Related issue: caffe2/caffe2/issues/1194 
It seems to be a problem with cuda 3.3.0 and glibc 2.26

**Comment by SomeoneSerge** [comment]
Evaluating nixpkgs-unstable with [these](https://github.com/SomeoneSerge/nixpkgs-unfree/blob/2a18afff5689f8df6c481da95484e93dea70f491/configs.nix#L2) arguments, `opensubdiv` build with cuda support, specifically with cuda 10.2: https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fc6knggf4rffvm24vd6b1il2cm8l9azs2-opensubdiv-3.4.4.drv?via-job=5db289ae-240a-40c3-95c3-9eb0566ce090
