### ISSUE TITLE
Build failure: Journalwatch NixOS module

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#314365]
### Steps To Reproduce

1. Add `services.journalwatch.enable = true;` to the NixOS configuration.
2. Use nixos-rebuild to build NixOS.

### Build log

```
       error: attribute 'journalwatch' missing

       at /nix/store/ahw94rjmyxb9ylz5kzxmj47g88srxhbr-source/nixos/modules/services/logging/journalwatch.nix:243:24:

          242|         StateDirectoryMode = "0750";
          243|         ExecStart = "${pkgs.python3Packages.journalwatch}/bin/journalwatch mail";
             |                        ^
          244|         # lowest CPU and IO priority, but both still in best-effort class to prevent starvation

```

### Additional context

According to the Nixpkgs search, there should be the packages python312Packages.journalwatch and python311Packages.journalwatch

in the Nixpkgs unstable branch. I just checked the master branch and I haven't been able to find those. I could only find pkgs.journalwatch.

That's fine, but then it means the journalwatch module needs to be updated. Perhaps this is related to #313450

### Metadata

I won't add the Metadata since I'm in the process of building NixOS, so the result would be incorrect anyway.

I'm on Nixpkgs commit 1388fbc714d01ec8280585c31fb6073a8fa590d6

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Breakage caused by #313450. Please have a look at #314422 and let me know if that works.

**Comment by matthiasbeyer** [comment]
Ran into this as well, the PR looks good and seems to fix the issue. Backport should land soon. Thank you all!
