### ISSUE TITLE
~/.config/dunst/dunstrc has no influence on pasystray notifications

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#31430]
## Issue description
I have the following [`~/.config/dunst/dunstrc`](https://pastebin.com/7HTWRptj) generated with `home-manager`

pasystray notification theme
![2017-11-09-11 44 07-screenshot](https://user-images.githubusercontent.com/7573215/32598865-79b4e662-c543-11e7-86d2-5c927ae9c7c6.png)

right theme
![2017-11-09-11 47 54-screenshot](https://user-images.githubusercontent.com/7573215/32598993-d8a6ed6e-c543-11e7-916a-ff914106f88c.png)

### Steps to reproduce
Just install pasystray

Check right theme with 
```
 ●  nix-shell -p libnotify alsaUtils

[nix-shell:~/projects/dunsted-volume]$ notify-send -i audio-volume-medium text

```

## Technical details

* System:  (NixOS: `nixos-version`) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by bebehei** [comment]
@srghma dunst maintainer here. I guess, you haven't set the `urgency_low` and `urgency_critical` sections. For me it seems, that your notifications sent via `pasystray` are sent with the `low` urgency hint.

To reproduce, does `notify-send -u low notification low` and `notify-send normal notification` yield different results?

**Comment by srghma** [comment]
@bebehei hi, tnx for answer

> To reproduce, does notify-send -u low notification low and notify-send normal notification yield different results?

yes

then I suppose its home-manager issue, closing
