### ISSUE TITLE
fetchsvn strips trailing slash from URL

### ISSUE THREAD

**Issue by earldouglas** [NixOS/nixpkgs#31441]
## Issue description

I want to use fetchsvn to retrieve the source for ebook2cw, but it fails due to a redirect cycle error:

```nix
src = fetchsvn {
  url = "http://svn.fkurz.net/ebook2cw/tags/${name}/";
  sha256 = "0n2p1i8cnnl2y3cdw8knx1vvs39sid45fr59p6f4vrprmb37l9yq";
};
```
The problem is that the SVN server requires that trailing slash, responding with an HTTP 302 if it's missing, while fetchsvn seems to strip the trailing slash.  After a few redirects, the build detects the redirect cycle and fails. 

I think the problem might be related to [this line](https://github.com/NixOS/nixpkgs/blob/60dcb9cc01c047126e5702cdb4bf81187cb92000/pkgs/build-support/fetchsvn/default.nix#L13).

### Steps to reproduce

Replace the `fetchurl` block in #31416 with the above `fetchsvn` block, and attempt to install with `nix-env -f /path/to/nixpkgs -i ebook2cw`.

## Technical details

* System: NixOS 17.03.1931.8b8977f9ff (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: 17.03.1931.8b8977f9ff
* Sandboxing enabled: No

**Comment by orivej** [comment]
Their SVN server seems unusable anyway:

```sh
$ svn ls http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2/                                                                                                   Redirecting to URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2':
Redirecting to URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2':
svn: E195019: Redirect cycle detected for URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2'

$ svn ls http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2                                                                                                    Redirecting to URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2':
Redirecting to URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2':
svn: E195019: Redirect cycle detected for URL 'http://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2'
```

**Comment by earldouglas** [comment]
Oh interesting; maybe this isn't `fetchsvn`'s issue at all.

**Comment by orivej** [comment]
This works:
```
svn ls svn://svn.fkurz.net/ebook2cw/tags/ebook2cw-0.8.2
```

**Comment by earldouglas** [comment]
Oh, great!  I've updated #31416 to use `fetchsvn` accordingly.
