### ISSUE TITLE
Add --pure --impure in nix-build to avoid changing system-wide useSandbox

### ISSUE THREAD

**Issue by kuznero** [NixOS/nixpkgs#31440]
## Issue description

Add `--pure` / `--impure` in `nix-build` to avoid changing system-wide `useSandbox` all the time.

## Technical details

* System: 17.09.2029.ab36c74390 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 17.09.2029.ab36c74390
* Sandboxing enabled: true

**Comment by kuznero** [comment]
Can I please be assigned to it as I would like to try to implement it myself?

**Comment by globin** [comment]
This should be opened in https://github.com/nixos/nix

**Comment by kuznero** [comment]
@globin thanks, re-opened on `nixos/nix`
