### ISSUE TITLE
Bluetooth not working (No default controller available)

### ISSUE THREAD

**Issue by Ate329** [NixOS/nixpkgs#314425]
### Describe the bug
The Bluetooth is not working and I tried to use bluetoothctl it says "No default controller available". It was working before with the same laptop but I reinstalled the system few weeks ago.

### Steps To Reproduce
1. ```sudo bluetoothctl```
2. ```power on```
3. ```scan on```

### Expected behavior
It should scan the bluetooth devices.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/74974216/41ebbfef-f46b-490b-8ba5-b413f92778e1)
Bluetooth service is on and the device is not blocked by rfkill.
![image](https://github.com/NixOS/nixpkgs/assets/74974216/73bd7e2c-34d0-4058-88ea-2dbbcc7b3809)

### Additional context
The configuration for Bluetooth
```nix
  hardware.bluetooth = {
    enable = true; # enables support for Bluetooth
    powerOnBoot = true; # powers up the default Bluetooth controller on boot
    
    /*
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true;
      };
    };
    */
  };
  
  services.blueman.enable = true; # pairing
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.05 (Uakari), 24.05.20240521.5710852`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixpkgs, unstable"`
 - nixpkgs: `/nix/store/qzjidyx3fip413vg7by6ibl22lwizc68-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by suptimal** [comment]
i have the same bug in kernel 6.9, seems to be related with MediaTek chips

related discussion in arch forum:
https://bbs.archlinux.org/viewtopic.php?id=296026

```
[nix-shell:~]$ dmesg | grep firmware
[   14.654407] bluetooth hci0: Direct firmware load for mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin failed with error -2
[   14.654410] Bluetooth: hci0: Failed to load firmware file (-2)
[   14.654575] Bluetooth: hci0: Failed to set up firmware (-2)
```

Bus 001 Device 005: ID 0e8d:0608 MediaTek Inc. Wireless_Device
```
[nix-shell:~]$ lsusb -d 0e8d:0608 -v 

Bus 001 Device 005: ID 0e8d:0608 MediaTek Inc. Wireless_Device
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.10
  bDeviceClass          239 Miscellaneous Device
  bDeviceSubClass         2 [unknown]
  bDeviceProtocol         1 Interface Association
  bMaxPacketSize0        64
  idVendor           0x0e8d MediaTek Inc.
  idProduct          0x0608 Wireless_Device
  bcdDevice            1.00
  iManufacturer           5 MediaTek Inc.
  iProduct                6 Wireless_Device
  iSerial                 7 000000000
```

**Comment by Ate329** [comment]
Thanks for letting me know about that!! I just downgrade my kernal version to 6.8 and it worked!
![image](https://github.com/NixOS/nixpkgs/assets/74974216/9cb9fc29-acad-4e26-a023-7d5f543d0388)
So ig this is a kernal issue?
Hope it will be fixed soon

**Comment by Ate329** [comment]
This issue can be solved by downgrading the kernal to previous version.
```nix
boot.kernelPackages = pkgs.linuxPackages_6_8;
```
 Thus closing this issue.

**Comment by Ate329** [comment]
This issue has been fixed in the latest kernel version.
