### ISSUE TITLE
Postfix is currently broken

### ISSUE THREAD

**Issue by pngwjpgh** [NixOS/nixpkgs#31442]
## Issue description

Postfix 2.3.2 currently fails to build complaining about a missing library seemingly related to NIS (i'm taking this from the yp-prefix).

[Relevant Hydra build](https://hydra.nixos.org/build/63707252)

**Comment by dezgeg** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/b306298bdcf87f354025b2272c0eee3facae43cf
