### ISSUE TITLE
mod_php pcre groups are broken with pcre.jit = true

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#31451]
## Issue description

    <?php
      preg_match('/(42)/', '42', $result);
      var_dump($result);
    ?>

Should dump, among other things, "42", but instead results in no match at all. This appears to happen whenever groups are used at all, but simple matches work (eg. '/\d\d/' or simply '/42/' will match '42')

This seems quite severe.

### Steps to reproduce

I've prepared a [nixos-test in a gist](https://gist.github.com/srhb/2d9f5354cdf16c96ec3356f4c5383303). It should fail when `pcre.jit` is set to `true` (the bug) and succeed when set to `false`.

## Technical details

* System: 18.03.git.292f605 (Impala)
* Nix version: 1.11.15
* Nixpkgs version: 292f605 (nixos-unstable)
* Sandboxing enabled: true

**Comment by pbogdan** [comment]
I don't fully understand what might be the full implications of doing that but FWIW building PHP against Nix provided `pcre` package (rather than the one bundled with PHP) fixes this particular issue.

**Comment by srhb** [comment]
Following the suggestions in #31499, [this patch](https://gist.github.com/srhb/c01fb0117e9aee6291be147e41cb8520) indeed does fix the issue.

I am unsure whether we should prefer applying that over using our own pcre.

**Comment by pbogdan** [comment]
Can confirm, I rebuilt PHP with (mostly the same) upstream patch from https://github.com/php/php-src/commit/5ef10d08ec2d0823fb21ad189dacfb43d900a0b5 and that clears the issue for me as well, but am also not sure what would be the preferred solution :/.
