### ISSUE TITLE
Package request: mvmv

### ISSUE THREAD

**Issue by Semnodime** [NixOS/nixpkgs#314603]
**Project description**

**Metadata**

* homepage URL: https://memverge.com/memoryviewer/
* source URL: 
* license: 
* platforms: linux, docker

**Comment by vinnymeller** [comment]
whoops i didnt see you closed this, if you still want it in nixpkgs a pr is here: https://github.com/NixOS/nixpkgs/pull/314658

otherwise you can copy the derivation and i'll close the pr :+1:
