### ISSUE TITLE
services.mullvad-vpn wipes out all network access

### ISSUE THREAD

**Issue by AlexChalk** [NixOS/nixpkgs#314694]
### Describe the bug

After a recent update (~10am May 25th EST) on nixos-unstable channel, `services.mullvad-vpn` makes it impossible to connect to a network. 

Connections via wifi, ethernet, and bluetooth all display as `full` connectivity in nmcli, but no hostnames or ip addresses resolve, in any application. Rolling backing to a prior build does not fix the the problem.

To get internet back (thank you to https://unix.stackexchange.com/a/719780):
- Hit `e` on the bootloader menu.
- Hit `Ctrl+e` (to go to end of prompt) and type ` rescue` (with space).
- Enter sudo password when prompted.
- Run `systemctl start network-online.target`.
- Edit `/etc/nixos/configuration.nix` and comment out `services.mullvad-vpn`.
- `nixos-rebuild switch`
- Reboot

### Steps To Reproduce

**n.b. This is not fun to rollback** (see above, the typical way via the bootloader doesn't work), so maybe don't do this on your primary system.

1. Make sure `sudo nix-channel --list` includes `nixos https://nixos.org/channels/nixos-unstable`
2. `sudo nix-channel --update`
3. Add to `configuration.nix`:
```nix
services.mullvad-vpn = {
  enable = true;
  package = pkgs.mullvad-vpn;
};
```
4. `sudo nixos-rebuild switch`.
5. Your network access should be gone.

### Expected behavior
`services.mullvad-vpn` does not disable network access. 

### Additional context

[mullvad-vpn.nix](https://github.com/NixOS/nixpkgs/blob/bfb7a882678e518398ce9a31a881538679f6f092/nixos/modules/services/networking/mullvad-vpn.nix) has not been updated recently, and it wasn't causing the issue for me as recently as May 23rd. 

The timing for this PR is a closer match, so it could have introduced the issue: https://github.com/NixOS/nixpkgs/pull/312499. A reviewer mentions they didn't test it as a daemon, and it's probably the daemon that breaks things (as I lost internet without using the gui or cli).

However, this doesn't explain why booting into an older system generation didn't fix the problem. I wondered if maybe `mullvad-daemon` self-updates once installed (similar to `dropboxd`), which would decouple the app version from nixos generations, but the timing for the most recent release doesn't match: https://github.com/mullvad/mullvadvpn-app/releases. However, this could be an explanation if there's a delay between mullvad's github releases and when they push OTA updates.

### Notify maintainers

@arcuru
@ymarkus
@Br1ght0ne
@ataraxiasjel
@athre0z 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.11 (Vicuña), 24.11pre630835.bfb7a882678e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixos-hardware, nixos-stable-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arcuru** [comment]
Copy/pasting from a different comment: 
https://github.com/NixOS/nixpkgs/issues/281102#issuecomment-1892733083

In the mullvad gui, under VPN settings, what do you have set for:

    Local Network Sharing
    Lockdown mode

You probably want Local Network Sharing -> Enabled and Lockdown mode -> Disabled.

I suspect mullvad may be changing those settings on update. And it does look like the Mullvad package was updated recently in #312499

**Comment by AlexChalk** [comment]
Hi @arcuru, I'm done with mullvad at this point 😅, but I'll close as that other issue describes my behaviour. 

I'd really like an equivalent to the `allowUnfree` flag for packages that can push silent breaking updates like this, but that's out of scope here.
