### ISSUE TITLE
My Emacs installation emits a warning

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#314602]
### Describe the bug

The message below appears while running Emacs:

> 
> ⛔ Warning (emacs): The ‘:bind-into’ with a map minibuffer-mode-map is considered unreliable, and will be deprecated.
> ⛔ Warning (emacs): The ‘:bind-into’ with a map isearch-mode-map is considered unreliable, and will be deprecated.
> 

### Steps To Reproduce

> [user@system:~]$ emacs 

### Expected behavior

No warning.

### Additional context

My configuration for HM and NixOS:

https://github.com/atorres1985-junkyard/etc/

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

> error:
>        … while calling the 'import' builtin
>          at «string»:1:18:
>             1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
>              |                  ^
> 
>        … while realising the context of a path
> 
>        … while calling the 'findFile' builtin
>          at «string»:1:25:
>             1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
>              |                         ^
> 
>        error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
> 

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marsam** [comment]
I think it's because setup.el [deprecated passing a map to `:bind-into`](https://git.sr.ht/~pkal/setup/commit/30c03935774e7c34cc4de87dcf1f88ea09c190a1)

I believe you can fix it in your configuration with:
```diff
--- a/home-configs/anderson/emacs/profiles/dumped/2024-03-29/org-literate/configuracao.org
+++ b/home-configs/anderson/emacs/profiles/dumped/2024-03-29/org-literate/configuracao.org
@@ -1150,7 +1150,7 @@ maps)= [fn:lnk-yt-gojOZ3k1mmk]
 
   (setup vertico
     (:if-package vertico)
-    (:bind-into minibuffer-mode-map
+    (:bind-into minibuffer
      "C-l" #'vertico-directory-delete-word
      "M-g" #'vertico-multiform-grid
      "M-q" #'vertico-multiform-flat
@@ -1184,7 +1184,7 @@ maps)= [fn:lnk-yt-gojOZ3k1mmk]
      [remap repeat-complex-command] #'consult-complex-command
      ;; Remaps for `Info-mode'.
      [remap Info-search] #'consult-info)
-    (:bind-into isearch-mode-map
+    (:bind-into isearch
       "TAB" #'consult-line))
 
   (global-unset-key (kbd "<insert>"))
```

**Comment by AndersonTorres** [comment]
Nice, I will close this as concluded, then.
