### ISSUE TITLE
do not know how to unpack source archive ...

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#31464]
## Issue description
I am trying to integrate luarocks and nix to manage lua packages. Thus I try to download "*.src.rock" files which are zip files that contains a tar.gz + the lua *.rockspec.

For instance doing
```
diff --git a/pkgs/top-level/lua-packages.nix b/pkgs/top-level/lua-packages.nix
index f233ae43ad1..00d8eb16896 100644
--- a/pkgs/top-level/lua-packages.nix
+++ b/pkgs/top-level/lua-packages.nix
@@ -528,7 +528,8 @@ let
     version = "0.12";
 
     src = fetchurl {
-      url = "http://www.inf.puc-rio.br/~roberto/lpeg/${name}.tar.gz";
+      url="https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock";
+      # url = "http://www.inf.puc-rio.br/~roberto/lpeg/${name}.tar.gz";
       sha256 = "0xlbfw1w7l65a5qhnx5sfw327hkq1zcj8xmg4glfw6fj9ha4b9gg";
     };
 

```
followed by `nix-env -iA lua52Packages.lpeg -f ~/nixpkgs --show-trace` outputs
```
building path(s) ‘/nix/store/9vjdyj1vqnrcbb4b1gkfsjsdxrnws7hn-lua5.2-lpeg-0.12’
unpacking sources
unpacking source archive /nix/store/pgsjjr7b3v9axhg951qq8b2ak1y8r94i-lpeg-1.0.1-1.src.rock
do not know how to unpack source archive /nix/store/pgsjjr7b3v9axhg951qq8b2ak1y8r94i-lpeg-1.0.1-1.src.rock
builder for ‘/nix/store/srxxawnyc4619lzl0058lcpsbz43i2sp-lua5.2-lpeg-0.12.drv’ failed with exit code 1

```
As recommende on #nixos I tried using the name component of fetchzip to no avail. Apparently I could redefine an unpackCmd to bypass this but I don't get why the unzip fails, I wish there was a clearer error.
$ file lpeg-1.0.1-1.src.rock gives `lpeg-1.0.1-1.src.rock: Zip archive data, at least v2.0 to extract`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.8, NixOS, 18.03.git.eafd703 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(teto): `""`
 - channels(root): `"nixos-unstable-18.03pre118381.4068703502, nixos-18.03pre118381.4068703502"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by orivej** [comment]
The error without the message is returned from here: https://github.com/NixOS/nixpkgs/blob/84fb41dd2698321b3ab3b04b5620cad2796f7eef/pkgs/stdenv/generic/setup.sh#L617
As you can see, only a few extensions are supported by default. Here is how to support a new extension: https://github.com/NixOS/nixpkgs/blob/84fb41dd2698321b3ab3b04b5620cad2796f7eef/pkgs/tools/archivers/p7zip/setup-hook.sh

**Comment by teto** [comment]
Thqt's helpful thanks ! how would you advise me to proceed ? have luarocks install an unpackCmdHook like this one ?
https://github.com/NixOS/nixpkgs/blob/84fb41dd2698321b3ab3b04b5620cad2796f7eef/pkgs/tools/archivers/p7zip/setup-hook.sh#L1-L5
or should I just override unpackCmd in buildLuaPackage (in my fork). Like python it's possible that buildLuaPackage ends up dealing with several kinds of lua packages so the first solution seems more sexy to me but maybe there are other suggestions.

**Comment by orivej** [comment]
I didn't mention another option, you can define `fetchrock` by overriding `postFetch` in `fetchurl`, like this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchzip/default.nix#L17 . If it produces a directory in `$out`, `setup.sh` will use it and won't complain that it does not know how to unpack.

**Comment by teto** [comment]
I've added a setupHook in luarocks but it doesn't seem to trigger (It's not easy to debug hooks in nixos, I've added some more logging in stdenv). So I figure the setupHook triggers only for dependant inputs so I tried to write fetchrock so that it adds luarocks (and thus its unpack hook)
```
  fetchrock = fetchzip.overrideDerivation (
  {nativeBuildInputs, ...} @ args:
  removeAttrs args [ nativeBuildInputs] // { nativeBuildInputs= nativeBuildInputs ++ [ luarocks ];}
  );
```
but this fails with
```
error: while evaluating the attribute ‘src’ of the derivation ‘lpeg-0.12’ at /home/teto/nixpkgs2/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating the attribute ‘overrideDerivation’ at /home/teto/nixpkgs2/lib/customisation.nix:87:9:
overrideDerivation not yet supported for functors
```
Usually I would use overrideAttrs but fetchzip doesn't have that. I am not sure I get this part of techzip/default.nix either, seems like it binds one of the variables (aka create a partial ?)
```
 # Hackety-hack: we actually need unzip hooks, too
(x: {nativeBuildInputs = x.nativeBuildInputs++ [unzip];})
```

**Comment by orivej** [comment]
`fetchzip` is not a derivation, it is a function that returns a derivation. The basic `fetchrock` may look like this:
```nix
{ url, sha256 }:
lib.overrideDerivation (fetchzip ({
  postFetch = ''your custom unpacker'';
}))
```

I have not tried it, please tell if you need more assistance.

**Comment by teto** [comment]
nix-repl says otherwise
:t fetchzip
a set
also I don't think postFetch helps since it is called after the unpackFile
command that will trigger the setup abort. I keep trying




2017-11-11 21:55 GMT+09:00 Orivej Desh <notifications@github.com>:

**Comment by teto** [comment]
I went the easy way and just copy/pasted the unzip one
```
# This function downloads and unpacks an archive file, such as a zip
# or tar file. This is primarily useful for dynamically generated
# archives, such as GitHub's /archive URLs, where the unpacked content
# of the zip file doesn't change, but the zip file itself may
# (e.g. due to minor changes in the compression algorithm, or changes
# in timestamps).

{ lib, fetchurl, fetchzip, unzip, luarocks }:

{ # Optionally move the contents of the unpacked tree up one level.
  stripRoot ? true
, url
, extraPostFetch ? ""
, ... } @ args:

lib.overrideDerivation (fetchzip args )
# Hackety-hack: we actually need unzip hooks, too
(x: {nativeBuildInputs = x.nativeBuildInputs++ [luarocks];})

```
That now works but hopefully once I get a PR ready, that can be better expressed.

Thanks for your help !
