### ISSUE TITLE
Ipython with Python 3.4 not building

### ISSUE THREAD

**Issue by ashgillman** [NixOS/nixpkgs#31465]
## Issue description

ipython doesn't build on 3.4 as it can't find something called python_version

[stdout.txt](https://github.com/NixOS/nixpkgs/files/1460118/stdout.txt)

## Steps to reproduce

    nix-build --no-out-link -E 'with import <nixpkgs> {}; python34.withPackages (ps: with ps; [ipython])'

## Technical details

    System: Ubuntu 16.04
    Nix version: 1.11.5
    Nixpkgs version: 17.09: 2d1d381b81adab7f2bbf056f1591f6f7288262ae AND nixos-unstable:  2a894cd2d14e0858d4942cf3d15c188372c3a121

**Comment by FRidh** [comment]
Fixed on master with 1806559d0502ad5aeb936b2438bccf504bcee8aa and 17.09 with 68efaeab7bcd886d5673f4b348912321d668c9fa.

**Comment by ashgillman** [comment]
Thank you very much :)
