### ISSUE TITLE
node or yarn is broken on nixos-unstable, can't install pacakges,  /bin/sh: bad interpreter: Text file busy

### ISSUE THREAD

**Issue by anpin** [NixOS/nixpkgs#314713]
### Describe the bug
After updating a flake to latest nixos-unstable branch today yarn is not able to install packages.

### Steps To Reproduce

```console
nix-shell -I nixpkgs=channel:nixos-unstable -p nodejs yarn --run 'mkdir -p /tmp/test && cd /tmp/test && yarn init -y && yarn add esbuild && node -e "console.log(require(\"esbuild\"));"'
```
```
yarn init v1.22.22
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.02s.
yarn add v1.22.22
warning package.json: "test" is also the name of a node core module
info No lockfile found.
warning test@1.0.0: "test" is also the name of a node core module
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /tmp/test/node_modules/esbuild: Command failed.
Exit code: 126
Command: node install.js
Arguments:
Directory: /tmp/test/node_modules/esbuild
Output:
/bin/sh: /run/user/1000/yarn--1716678098721-0.18406973672680782/node: /bin/sh: bad interpreter: Text file busy
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
### Expected behavior
yarn install succeeds 

### Additional context
Running against older version of nixpkgs works as well as  `nix build` for this app

### Notify maintainers

@offlinehacker @screendriver @marsam

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.11 (Vicuña), 24.11.20240525.539e326`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(a): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/a/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wackbyte** [comment]
I am also experiencing this.

**Comment by robert-elles** [comment]
Same issue here

**Comment by anpin** [comment]
Reverting both yarn and node to commits from last year doesn't solve the issue

**Comment by marsam** [comment]
maybe it's an issue with uring(?). 
Can you try using `export UV_USE_IO_URING=0` to confirm it?

**Comment by eliraz-refael** [comment]
I can confirm that using `export UV_USE_IO_URING=0` works and solves the issue for me, at least.

**Comment by ncn-ends** [comment]
Had the same problem and `xport UV_USE_IO_URING=0` worked for me as well. Thank you

**Comment by ivan770** [comment]
With kernel 6.9.3 available on `nixos-unstable` this problem should no longer occur.

**Comment by anpin** [comment]
would love to try, but after rebasing to latest nixos-unstable today my system fails to start :(

**Comment by doronbehar** [comment]
I'm closing as this is seems fixed.
