### ISSUE TITLE
Update request: nixos-artwork.wallpapers.*

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nixpkgs#314837]
Missing new wallpapers.

- Package name: nixos-artwork.wallpapers.*
- Latest released version: N/A

- Current version on the unstable channel: N/A
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

`maintainers` is missing from `meta`.
https://github.com/NixOS/nixpkgs/blob/18b5737723b8d188fb664ab60d2508f045266329/pkgs/data/misc/nixos-artwork/wallpapers.nix#L36-L41

@samuelgrf 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
Uff, the last time they were meaningfully updated was 4 years ago… :worried:
