### ISSUE TITLE
texlive-scripts-2016 scripts she bang are not patched: make sandboxed build failed

### ISSUE THREAD

**Issue by mickours** [NixOS/nixpkgs#31482]
## Issue description
The scripts from ``texlive-scripts-2016`` contained she bangs that are not patched:
```
/nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/rungs.tlu:1:#!/usr/bin/env texlua
/nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/test-tlpdb.tlu:1:#! /usr/bin/env texlua
/nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/texconf.tlu:1:#! /usr/bin/env texlua
/nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/lua/texlive/getopt.tlu:1:#! /usr/bin/env texlua
/nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/lua/texlive/tlpdb.tlu:1:#! /usr/bin/env texlua
```
This makes XeLatex build like defined here (https://github.com/NixOS/nixpkgs/issues/24485#issuecomment-290758573) fails with:
```
[12] (./slides.aux)/nix/store/p5a497xrq431qir8652ajlnkbyigqjyg-texlive-combined-2016/bin/rungs: /nix/store/b91n38zij31kvgggckp2261vkna5lxz1-texlive-scripts-2016/scripts/texlive/rungs.tlu: /usr/bin/env: bad interpreter: No such file or directory
```

### Steps to reproduce

I don't know how to trigger the call of this scripts exactly, but in should fail in any sandboxed environment that call these scripts. 

## Technical details

* System: NixOS: 18.03pre119383.eafd703a63 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre119383.eafd703a63
* Sandboxing enabled: build-use-sandbox = true

**Comment by dtzWill** [comment]
Is this still an issue on master (which has texlive 2017)?

**Comment by mickours** [comment]
Yes, still there. You check it using grep:
```
grep -Rn "usr/bin/env" /nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017
/nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017/scripts/texlive/rungs.tlu:1:#!/usr/bin/env texlua
/nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017/scripts/texlive/test-tlpdb.tlu:1:#! /usr/bin/env texlua
/nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017/scripts/texlive/texconf.tlu:1:#! /usr/bin/env texlua
/nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017/scripts/texlive/lua/texlive/getopt.tlu:1:#! /usr/bin/env texlua
/nix/store/jix2s1zdq4r0jc4363aa2dcyz3szzi0q-texlive-scripts-2017/scripts/texlive/lua/texlive/tlpdb.tlu:1:#! /usr/bin/env texlua
```

**Comment by dtzWill** [comment]
Hmm, using the linked MWE works fine for me.  I notice `slides.aux` above--can you post a new MWE that demonstrates the issue?

-----

Actually, ha!
I found this in my one of my own local repositories for my slides (I notice `slides.aux` in your first post):

```
    # This shouldn't be needed, but 'rungs.tlu' wants this, triggered when tried to include eps
    inherit (pkgs.texlive) collection-luatex;
```

So, that should at least give you a reasonable workaround; it was enough to point me to the problem.

I'll be submitting a PR to address this shortly.

**Comment by mickours** [comment]
It only happen sometimes when xelatex decides internally to use one of the impacted scripts.
I don't know how to trigger this with a simple example, I tried but without success...
