### ISSUE TITLE
Update request: tinymist 0.11.9 → 0.11.10

### ISSUE THREAD

**Issue by slashformotion** [NixOS/nixpkgs#314855]
- Package name:
- Latest released version: 0.11.10

- Current version on the unstable channel: 0.11.9
- Current version on the stable/release channel: none

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@GaetanLepage you updated this package last, I don't know how to update this package, but if you tell how to do it, i can do it myself.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
Done this morning in #314789 :)

**Comment by slashformotion** [comment]
Hmm, I couldn't find this PR for some reason. I must have accidentally adjusted the filters. Sorry for the inconvenience.

**Comment by GaetanLepage** [comment]
> Hmm, I couldn't find this PR for some reason. I must have accidentally adjusted the filters. Sorry for the inconvenience.

No worry !
