### ISSUE TITLE
Update request: temurin-bin-21 21.0.1 → 21.0.3

### ISSUE THREAD

**Issue by gabrieljones** [NixOS/nixpkgs#314922]
- Package name: temurin-bin-21
- Latest released version: 21.0.3

- Current version on the unstable channel: not present
- Current version on the stable/release channel: 21.0.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by smancill** [comment]
Updated by #314377
