### ISSUE TITLE
attribute ‘RSymphony’ missing on darwin

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#31508]
## Issue description

I get this error:
```
error: attribute ‘RSymphony’ missing, at /nix/store/zfiwrns4xm1anh2bv487k98psmh6gq7b-nixpkgs-18.03pre119383.eafd703a63/nixpkgs/pkgs/development/r-modules/default.nix:77:8
```

while trying to evaluate nixpkgs.rPackages (```nix-env -qa -A nixpkgs.rPackages```).

/cc @hamishmack @peti @domenkozar 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
macOS

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.15

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
18.03pre119383.eafd703a63

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
no

**Comment by teto** [comment]
have  the same problem but on linux
