### ISSUE TITLE
Package request: xwayland-satellite

### ISSUE THREAD

**Issue by jonseppanen** [NixOS/nixpkgs#315111]
**Project description**

This package allows running x-org-only apps in a wayland-only environment rootfully. Like steam in niri, for example.

**Metadata**

* homepage URL: https://github.com/Supreeeme/xwayland-satellite
* source URL: https://github.com/Supreeeme/xwayland-satellite
* license: MPL2
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tulilirockz** [comment]
Requires #269138

**Comment by KiaraGrouwstra** [comment]
this seems added in d38f87d88a4fc5a63a9162157a086c377e96ad2d.
that said, its [systemd support](https://github.com/Supreeeme/xwayland-satellite#systemd-support) appears TODO.

**Comment by tv42** [comment]
The integration tests work fine in the nix build chroot, you just need `xwayland` in `nativeBuildInputs` and

```nix
          preCheck = ''
            # Integration tests want to actually talk Wayland
over unix domain sockets.
            export XDG_RUNTIME_DIR="/tmp"
          '';
```

**Comment by tv42** [comment]
Also, the way it's packaged in d38f87d88a4fc5a63a9162157a086c377e96ad2d makes xwayland-satellite crap out unless you by chance happen to have Xwayland in PATH. You want something like

```nix
          postInstall = ''
            wrapProgram $out/bin/xwayland-satellite \
              --prefix PATH : ${pkgs.lib.makeBinPath (with pkgs; [ xwayland ])}
          '';
```

**Comment by Pandapip1** [comment]
Closing, as the package has been added and @tv42's fix seems to have been applied.
