### ISSUE TITLE
Unable to apply a overlay to my system, unsure if bug or unclear documentation.

### ISSUE THREAD

**Issue by thyTwilightGoth** [NixOS/nixpkgs#315193]
### Describe the bug
Following the documentation as best as I could understand it, I attempted to apply an overlay in my configuration.nix file. What I expected was my overlay to apply, instead I am getting an error in modules.nix.

### Steps To Reproduce
1. Follow the documentation to use nixpkg.overlay: [https://wiki.nixos.org/wiki/Overlays](https://wiki.nixos.org/wiki/Overlays)
2. Add the overlay to configuration.nix
3. Watch as you get an error in modules.nix on line 320 char's 9 and 18

### Expected behavior
My overlay applies without issue

### Screenshots
![Screenshot_20240527_140630](https://github.com/NixOS/nixpkgs/assets/14948037/b65a9151-3f2e-4d15-82d3-4e6a72791966)
Yes I know it is messy, I'll clean it up eventually.
![Screenshot_20240527_140659](https://github.com/NixOS/nixpkgs/assets/14948037/421b1242-06fa-43c8-9d59-e50c57d34b03)

### Notify maintainers
@stuebinm

### Metadata
```
these 6 paths will be fetched (0.75 MiB download, 10.19 MiB unpacked):
  /nix/store/my4dqv1w8pd9nsibl2cz2dkqwpayy22l-file-5.45
  /nix/store/8zkvw6pp16pzm6likh1grk28y9q9gp0f-gnu-config-2023-09-19
  /nix/store/wnyzkpp94dg9s4iky7pd5lrx5x4blq2s-gnumake-4.4.1
  /nix/store/556d870m1xjnym3jnsp9bvjgph4cclrj-patchelf-0.15.0
  /nix/store/1li91c82qsx7gias5jypzw9ypwjrqc6i-stdenv-linux
  /nix/store/v1z5idckqpjs263pxvxmhfx5wxyybhjq-update-autotools-gnu-config-scripts-hook
copying path '/nix/store/8zkvw6pp16pzm6likh1grk28y9q9gp0f-gnu-config-2023-09-19' from 'https://cache.nixos.org'...
copying path '/nix/store/my4dqv1w8pd9nsibl2cz2dkqwpayy22l-file-5.45' from 'https://cache.nixos.org'...
copying path '/nix/store/wnyzkpp94dg9s4iky7pd5lrx5x4blq2s-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/556d870m1xjnym3jnsp9bvjgph4cclrj-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/v1z5idckqpjs263pxvxmhfx5wxyybhjq-update-autotools-gnu-config-scripts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/1li91c82qsx7gias5jypzw9ypwjrqc6i-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 23.11 (Tapir), 23.11.7313.9d29cd266ceb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
```
` - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 23.11 (Tapir), 23.11.7313.9d29cd266ceb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Edit: Made sure the hyperlink worked properly.

**Comment by stuebinm** [comment]
the error tells you there's no `lib` defined when you use it (it is also not in `lib/modules.nix`; nix traces are read from bottom to top: the final error site is the one at the end, which is inside your config). Have you added it to the top-level `{pkgs, lib, ...}:` argument list of you module? Otherwise, it will not be in scope. Unfortunately, that line is not included in your screen shot.

As a side note: when opening such issues, please provide your errors & configs as text listings, not screenshots. This'll make them easier to go & search through (and also prevents unintentionally leaving out such details).

Also, I am somewhat mystified at how you decided that I was maintainer of any of the things you are dealing with here. I am not, even if I'm answering now since I just happened to have time & nothing else to do.

> Follow the documentation to use nixpkg.overlay: [https://wiki.nixos.org/wiki/Overlays](https://github.com/NixOS/nixpkgs/issues/url)

I am also not sure why you thought adding a wrong link here was appropriate.

**Comment by thyTwilightGoth** [comment]
Then it was a case of unclear documentation since none of it directly mentioned the ```lib``` addition needed a the top. I did not realize how the url insert worked, if the complaint is about the website I used, that is the only documentation I found that is online besides the manual, which also, did not explain clearly to me what was going wrong. Neither did searching the internet come up with a reason I was having a ```lib``` error.

Thanks for your time and have a good day.

**Comment by stuebinm** [comment]
the complaint was about you setting a link to `https://github.com/NixOS/nixpkgs/issues/url`, then setting its markdown text content to `https://wiki.nixos.org/wiki/Overlays` (the latter is actually the correct wiki page, but not where that link goes if someone clicks it)

**Comment by thyTwilightGoth** [comment]
> the complaint was about you setting a link to `https://github.com/NixOS/nixpkgs/issues/url`, then setting its markdown text content to `https://wiki.nixos.org/wiki/Overlays` (the latter is actually the correct wiki page, but not where that link goes if someone clicks it)

That makes sense, was an accident.
