### ISSUE TITLE
Unable to use Podman Quadlets at the user level

### ISSUE THREAD

**Issue by Reputable2772** [NixOS/nixpkgs#315158]
### Describe the bug
Unable to use Podman's quadlets feature for a user, since the service unit files are not generated by systemd.

### Steps To Reproduce
1. Place a quadlet file in `~/.config/containers/systemd/` (say, `caddy.container`)
2. Run `systemctl --user daemon-reload`
3. Run `systemctl --user status caddy.service`. Systemd says that no unit files were found.

### Expected behavior
Caddy service should have been generated and its status displayed.

### Additional context
This issue is caused by not symlinking the `podman-user-generators` provided by the `podman` package to `/etc/systemd/user-generators`. Does not occur at the system level, since `podman-system-generators` is already symlinked to `/etc/systemd/system-generators`

Fix:
```
environment.etc."/etc/systemd/user-generators/podman-user-generator".source = "${pkgs.podman}/lib/systemd/user-generators/podman-user-generator";
```

### Notify maintainers
@vdemeester @saschagrunert

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240521.3eaeaeb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - nixpkgs: `/nix/store/57rsy3z79kvxah2l4j13bjwpsgxkbhby-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dawidd6** [comment]
Confirmed the quadlet systemd user generator is not found in /etc/systemd. I'm gonna take this one and try to come up with a fix in `systemd` NixOS module.
