### ISSUE TITLE
Package request: cmake-lint

### ISSUE THREAD

**Issue by multivac61** [NixOS/nixpkgs#315133]
**Project description**

Fork of https://github.com/richq/cmake-lint to continue maintenance. cmakelint parses CMake files and reports style issues.

**Metadata**

* homepage URL: https://github.com/cmake-lint/cmake-lint
* source URL: https://github.com/cmake-lint/cmake-lint
* license: apache 2
* platforms: vim plugin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marsam** [comment]
I think you can use the following:
```nix
# pkgs/by-name/cm/cmake-lint/package.nix
{ lib, fetchFromGitHub, python3, testers, cmake-lint }:

python3.pkgs.buildPythonApplication rec {
  pname = "cmake-lint";
  version = "1.4.3";
  pyproject = true;

  src = fetchFromGitHub {
    owner = "cmake-lint";
    repo = "cmake-lint";
    rev = version;
    hash = "sha256-/OuWwerBlJynEibaYo+jkLpHt4x9GZrqMRJNxgrDBlM=";
  };

  nativeBuildInputs = [
    python3.pkgs.setuptools
  ];

  pythonImportsCheck = [ "cmakelint" ];

  nativeCheckInputs = [
    python3.pkgs.pytest-cov
    python3.pkgs.pytestCheckHook
  ];

  passthru.tests = {
    version = testers.testVersion {
      package = cmake-lint;
    };
  };

  meta = {
    description = "Static code checker for CMake files";
    homepage = "https://github.com/cmake-lint/cmake-lint";
    changelog = "https://github.com/cmake-lint/cmake-lint/blob/${src.rev}/CHANGELOG.md";
    license = lib.licenses.asl20;
    maintainers = [ ];
    mainProgram = "cmakelint";
  };
}
```
