### ISSUE TITLE
Package request: violet

### ISSUE THREAD

**Issue by stv0g** [NixOS/nixpkgs#315126]
**Project description**

Violet is a lightweight STUN/TURN server ([RFC8489](https://www.rfc-editor.org/rfc/rfc8489.html) and [RFC8656](https://www.rfc-editor.org/rfc/rfc8656.html)) written in C without dependencies, based on [libjuice](https://github.com/paullouisageneau/libjuice).

**Metadata**

* homepage URL:
* source URL: https://github.com/paullouisageneau/violet
* license: gpl2
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by heisfer** [comment]
Shouldn't this issue be closed?

**Comment by stv0g** [comment]
Yes sorry I forgot
