### ISSUE TITLE
sudo/capabilities are badly broken on nixos-unstable

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#31516]
## Issue description

```sh
peter@dolores:~ $ sudo ls
sudo: /nix/store/3xsjm8rfpy0ysfjs1pcybj33fsigszgp-wrapper.c:203: main: Assertion `!(st.st_mode & S_ISUID) || (st.st_uid == geteuid())' failed.
[1]    13981            sudo ls

peter@dolores:~ $ ./ping
cannot raise the capability into the Ambient set
: Operation not permitted
```

I'm trying to figure out what was the latest working version.

### Steps to reproduce

1. Upgrade to latest nixos-unstable

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.12, NixOS, 18.03.git.03fb63f4fa3M (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre117327.3fe7cddc30"`
 - channels(peter): `""`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`

**Comment by gebner** [comment]
sudo works for me on the latest unstable:
```
[gebner:~/tmp] $ sudo ls
[sudo] password for gebner:
README.md
```

I'm on `98fcc3bd5d`, which seems to be the latest nixos-unstable channel update.  I couldn't find your `03fb63f4fa3` commit on nixpkgs, do you have local changes that could cause this issue?

**Comment by peterhoeg** [comment]
Very strange, I cannot reproduce it now either. ```nix-store --verify --check-contents``` doesn't reveal anything either.
