### ISSUE TITLE
Build failure: pkgMusl.python311

### ISSUE THREAD

**Issue by rnburn** [NixOS/nixpkgs#315266]
### Steps To Reproduce

I set up example flake that reproduces the issue here:

https://github.com/rnburn/nix-musl-py/

I got the error after running `nix develop` using that flake.

### Build log

I added the error I got here
https://github.com/rnburn/nix-musl-py/blob/main/error.txt

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/y11cs26gb9b1irv5hk776mra7hgy80bl-nix-info
copying path '/nix/store/y11cs26gb9b1irv5hk776mra7hgy80bl-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.10-76060610-generic, Pop!_OS, 22.04 LTS, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/62ca8xfz3n92p57sdds15r4s07kyls6i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
`pkgsMusl.python311` is building at master.

You should test packages in isolation before reporting breakage.

Then, report breakage of the broken packages only.

From the log you reported, breakage seems to come from `python3.11-h2`:
> got build log for '/nix/store/qh7brwmhl404l5vv454i6zmz2gcps8cq-python3.11-h2-4.1.0.drv' from 'daemon'

Git clone nixpkgs and try to build the failing package specifically.

I have successfully built:

> nix build .#pkgsMusl.python311.pkgs.h2

So I'm not sure what is wrong.

Regarding your project. That's not a good way to report problems. While I understand that is convenient to you, for us here at nixpkgs. It is vague and leads to waste of time.

**Comment by eclairevoyant** [comment]
closing as insufficient information. feel free to reopen once requested details are available.
