### ISSUE TITLE
LaTeX Error: File `utf8x.def' not found.

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#31520]
## Issue description
I'm getting this error when trying to make pfd book from `The Software Foundations` ([download here](https://softwarefoundations.cis.upenn.edu/lf-current/index.html))

```sh
 ~/Downloads/lf   master ●✚  make all.pdf
"coqdoc" -toc -interpolate -utf8 -pdf -R "." Top -o all.pdf `"coqdep" -c -sort -suffix .v Preface.v Basics.v Induction.v Lists.v Poly.v Tactics.v Logic.v IndProp.v Maps.v ProofObjects.v IndPrinciples.v Rel.v Imp.v ImpParser.v ImpCEvalFun.v Extraction.v Auto.v Postscript.v Bib.v PrefaceTest.v BasicsTest.v InductionTest.v ListsTest.v PolyTest.v TacticsTest.v LogicTest.v MapsTest.v IndPrinciplesTest.v AutoTest.v PostscriptTest.v BibTest.v`
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/NixOS.org) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2016/03/31> patch level 1

(./coqdoc181a3f.tex
(/nix/store/c59m217jgfan6yg6ldncgmaxdlcmf80n-texlive-combined-context-2016/shar
e/texmf/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class

(/nix/store/c59m217jgfan6yg6ldncgmaxdlcmf80n-texlive-combined-context-2016/shar
e/texmf/tex/latex/base/size12.clo))
(/nix/store/c59m217jgfan6yg6ldncgmaxdlcmf80n-texlive-combined-context-2016/shar
e/texmf/tex/latex/base/inputenc.sty

! LaTeX Error: File `utf8x.def' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)

Enter file name:
! Emergency stop.
<read *>

l.158 \endinput
               ^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on coqdoc181a3f.log.
Couldn't run LaTeX successfully
make: *** [Makefile:179: all.pdf] Error 1
```

Where this file should come from?

### Steps to reproduce
Download, cd, install `gnumake` and `coq`, try `make all.pdf` with either installed `tetex`, `texlive-combined-basic-2016`, `texlive-combined-context-2016`

## Technical details

* System:  (NixOS: `nixos-version`) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by vcunat** [comment]
I don't know a nice way to find what files are in what packages.  In this case this seems to work:
```
$ nix-shell -p gnumake coq 'texlive.combine { inherit (texlive) scheme-small ucs preprint cm-super; }' -Q
$ make all.pdf
```

Well, I do still have the 2016 archive of http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb.xz so I can search through it and map files to package names, but it's not a too nice way.

**Comment by BjornMelgaard** [comment]
@vcunat wow thanks, it worked

I just don't understand which package I should use

**Comment by maresb** [comment]
To be explicit, `utf8x` is included in `ucs`: https://ctan.org/pkg/ucs

Thanks for the issue and solution!
