### ISSUE TITLE
liblldb.so.18.1 shared library dependencies not correctly set

### ISSUE THREAD

**Issue by danobi** [NixOS/nixpkgs#315214]
### Describe the bug
```
$ ldd /nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1 | rg "=>" | awk '{print $3}' | xargs realpath
/usr/lib/libz.so.1.3.1
/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/libpython3.11.so.1.0
/usr/lib/liblua5.3.so.5.3.6
/usr/lib/libpanelw.so.6.4
/usr/lib/libncursesw.so.6.4
/usr/lib/libformw.so.6.4
/usr/lib/libxml2.so.2.12.6
/usr/lib/libedit.so.0.0.72
/usr/lib/libdl.so.2
/nix/store/92g7nfqk2g4yzy56lfrla3w89i61vnkg-clang-18.1.5-lib/lib/libclang-cpp.so.18.1
/nix/store/xpw2cabpd7vg67gakv727rz0gz9k84dy-llvm-18.1.5-lib/lib/libLLVM.so.18.1
/usr/lib/libstdc++.so.6.0.32
/usr/lib/libm.so.6
/usr/lib/libgcc_s.so.1
/usr/lib/libc.so.6
/usr/lib/liblzma.so.5.6.1
/usr/lib/libicuuc.so.74.2
/nix/store/kbg5m7fyi1w23fyfmxjhhzcbd577rpg0-libffi-3.4.6/lib/libffi.so.8.1.4
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/librt.so.1
/usr/lib/libicudata.so.74.2
```

I expect that these dependencies should resolve to /nix/store/ and not to /usr/lib/.

### Steps To Reproduce

FWIW, I am working on adding LLVM 18 support to bpftrace CI. (We are loving nix's role in our CI, btw).

I'm not sure if enough information is contained in the store path I shared above. But if not, I have a reproducer here: https://github.com/danobi/bpftrace/tree/nix_llvm18-nixpkgs . Just run `nix build`. You should see the following failure:

```
$ git rev-parse HEAD
4e8414c021d9d4ebd1c19106b87ab069b56a9742
$ nix build
$ ./result/bin/bpftrace
./result/bin/bpftrace: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory
```
I discovered lldb is related through LD_DEBUG=all:

```
$ LD_DEBUG=all ./result/bin/bpftrace
[..]
   2726159:     file=libicuuc.so.74 [0];  needed by /nix/store/hcag2qn4njvps4wpy7fnjb20y80fynni-lldb-18.1.5-lib/lib/../../../../lib/libxml2.so.2 [0]
   2726159:     find library=libicuuc.so.74 [0]; searching
[..]
```

### Expected behavior
lldb.so dynamic dependencies to resolve into nix store.

### Notify maintainers

(apologies if I got the list wrong)

@dtzWill
@ericson2314
@lovek323
@qyliss
@RossComputerGuy
@rrbutani
@sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7-arch1-2, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/home/dxu/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paparodeo** [comment]
paths look ok on ubuntu.
```console
$ which ldd
/bin/ldd
$ ldd /nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1 | \rg "=>" | awk '{print $3}' | xargs realpath
/nix/store/lv6nackqis28gg7l2ic43f6nk52hb39g-zlib-1.3.1/lib/libz.so.1.3.1
/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib/libpython3.11.so.1.0
/nix/store/x5mpg1pjazhvja8aq0yxig2zgz51i9c1-lua-5.3.6/lib/liblua.so.5.3.6
/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib/libpanelw.so.6.4
/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib/libncursesw.so.6.4
/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib/libformw.so.6.4
/nix/store/kf7fzax0av9him9m4zcmbqmihh5108wq-libxml2-2.12.7/lib/libxml2.so.2.12.7
/nix/store/bmjckrv5ryxahvkldr47jyx7zmlrcan3-libedit-20230828-3.1/lib/libedit.so.0.0.72
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/libdl.so.2
/nix/store/92g7nfqk2g4yzy56lfrla3w89i61vnkg-clang-18.1.5-lib/lib/libclang-cpp.so.18.1
/nix/store/xpw2cabpd7vg67gakv727rz0gz9k84dy-llvm-18.1.5-lib/lib/libLLVM.so.18.1
/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib/libstdc++.so.6.0.32
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/libm.so.6
/nix/store/0rxb3ixzk4zaqivc9s795m0a3679wbw2-gcc-13.2.0-libgcc/lib/libgcc_s.so.1
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/libc.so.6
/nix/store/4n8fsrg6kslmnq5g2xsrs6vmpqfbyz2m-readline-8.2p10/lib/libreadline.so.8.2
/nix/store/kbg5m7fyi1w23fyfmxjhhzcbd577rpg0-libffi-3.4.6/lib/libffi.so.8.1.4
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/librt.so.1
```

**Comment by danobi** [comment]
I tried building on my other arch computer and I get the same failure.

However, on my fedora 39 machine, it succeeds.

But perhaps more concerning is that our github actions built binaries are failing too: https://github.com/bpftrace/bpftrace/blob/master/INSTALL.md#appimage-install

The workflow that builds it is here: https://github.com/bpftrace/bpftrace/blob/master/.github/workflows/binary.yml

I think default GHA runners use ubuntu, so that is very odd.

**Comment by RossComputerGuy** [comment]
Not reproducible on latest commit with aarch64-linux.

**Comment by danobi** [comment]
Debugged a little further. Seems like RPATH is not correctly set:

```
$ readelf -d /nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1 | rg runpath
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/xpw2cabpd7vg67gakv727rz0gz9k84dy-llvm-18.1.5-lib/lib:$ORIGIN/../../../../lib:/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib:/nix/store/x5mpg1pjazhvja8aq0yxig2zgz51i9c1-lua-5.3.6/lib:/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib:/nix/store/lv6nackqis28gg7l2ic43f6nk52hb39g-zlib-1.3.1/lib:/nix/store/bmjckrv5ryxahvkldr47jyx7zmlrcan3-libedit-20230828-3.1/lib:/nix/store/kf7fzax0av9him9m4zcmbqmihh5108wq-libxml2-2.12.7/lib:/nix/store/92g7nfqk2g4yzy56lfrla3w89i61vnkg-clang-18.1.5-lib/lib:/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib:/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib]
```

Note how `$ORIGIN/../../../../lib` is the second entry. This is probably what's triggering the resolution into the host.

**Comment by danobi** [comment]
Looking at the log (via `$ nix log /nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1`), I see this cmake log:

```
-- Set non-toolchain portion of runtime path of "/nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1.5" to "/nix/store/xpw2cabpd7vg67gakv727rz0gz9k84dy-llvm-18.1.5-lib/lib:$ORIGIN/../../../../lib"
```

So cmake is doing something funny here

**Comment by RossComputerGuy** [comment]
> Note how `$ORIGIN/../../../../lib` is the second entry. This is probably what's triggering the resolution into the host.

I do see that on aarch64-linux but things resolve right.
```
 0x000000000000001d (RUNPATH)            ライブラリの runpath: [/nix/store/dz4w1qs5gnxhwx7cwy1yj0yymx81wy85-llvm-18.1.6-lib/lib:$ORIGIN/../../../../lib:/nix/store/czlizmr5dmpxi7ysqknxys82776hldgk-python3-3.11.9/lib:/nix/store/7dbk3ikvlaqs8q8sfm63g9isl85cksk2-lua-5.3.6/lib:/nix/store/phifyhnbqbj37arma514hj8ri47mys76-ncurses-6.4/lib:/nix/store/67zz1fxgn27y2726blaghi26vl6gd1ry-zlib-1.3.1/lib:/nix/store/vibzkb1dx0c48wkc1irrqfi9dzdjlfnp-libedit-20230828-3.1/lib:/nix/store/3lh41b95f2zxdir8d6chdfblkqbmfcqn-libxml2-2.12.7/lib:/nix/store/i74c8hj71pqrgxqykz4nh8p4h0s2iiri-clang-18.1.6-lib/lib:/nix/store/27fg1mkiymj2b344j80kygsbxfcdl5qi-glibc-2.39-52/lib:/nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib]
```

**Comment by danobi** [comment]
@RossComputerGuy , perhaps your host system has the correct version of the dependency installed? 

I found the string in cmake source: https://github.com/Kitware/CMake/blob/124e50abbd335f3a6b70846ee2a50dc66015a951/Source/cmFileCommand.cxx#L1060

Trying to find lldb cmake sources now

**Comment by RossComputerGuy** [comment]
> perhaps your host system has the correct version of the dependency installed?

I'm on NixOS and I only did `nix build github:NixOS/nixpkgs/nixos-unstable#lldb_18`.

**Comment by paparodeo** [comment]
> Debugged a little further. Seems like RPATH is not correctly set:
> 
> ```
> $ readelf -d /nix/store/2033wdzw97yc2j0s51fa1q6max99i6a3-lldb-18.1.5-lib/lib/liblldb.so.18.1 | rg runpath
>  0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/xpw2cabpd7vg67gakv727rz0gz9k84dy-llvm-18.1.5-lib/lib:$ORIGIN/../../../../lib:/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib:/nix/store/x5mpg1pjazhvja8aq0yxig2zgz51i9c1-lua-5.3.6/lib:/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib:/nix/store/lv6nackqis28gg7l2ic43f6nk52hb39g-zlib-1.3.1/lib:/nix/store/bmjckrv5ryxahvkldr47jyx7zmlrcan3-libedit-20230828-3.1/lib:/nix/store/kf7fzax0av9him9m4zcmbqmihh5108wq-libxml2-2.12.7/lib:/nix/store/92g7nfqk2g4yzy56lfrla3w89i61vnkg-clang-18.1.5-lib/lib:/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib:/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib]
> ```
> 
> Note how `$ORIGIN/../../../../lib` is the second entry. This is probably what's triggering the resolution into the host.

oof -- that's pretty bad. it is adding /lib to the RPATH!!!!

**Comment by RossComputerGuy** [comment]
This issue could be because you're on a system using FHS. `$ORIGIN` is unset so that evals to an empty string. The series of `../` makes the path go to the parent of `/` which it doesn't do and just resolves as `/`. So that results in it pulling from `/lib`>

**Comment by RossComputerGuy** [comment]
> oof -- that's pretty bad. it is adding /lib to the RPATH!!!!

Yeah, that's what I suspected

**Comment by paparodeo** [comment]
llvm17 has a similar issue
```console
$ patchelf --print-rpath /nix/store/s5rqgqdl84q3bg44gn61zfi39036xhrf-lldb-17.0.6-lib/lib/liblldb.so|xargs -d ':' -n 1
$ORIGIN/..//nix/store/s5rqgqdl84q3bg44gn61zfi39036xhrf-lldb-17.0.6-lib/lib
/nix/store/ax9wbqknwawnl21kvkp8l6jn2r6q0l90-llvm-17.0.6-lib/lib
$ORIGIN/../../../../lib
/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib
/nix/store/x5mpg1pjazhvja8aq0yxig2zgz51i9c1-lua-5.3.6/lib
/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib
/nix/store/lv6nackqis28gg7l2ic43f6nk52hb39g-zlib-1.3.1/lib
/nix/store/bmjckrv5ryxahvkldr47jyx7zmlrcan3-libedit-20230828-3.1/lib
/nix/store/kf7fzax0av9him9m4zcmbqmihh5108wq-libxml2-2.12.7/lib
/nix/store/wxxgsgjxbnkkyczgf8lkbfrsqiywm8bi-clang-17.0.6-lib/lib
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib
/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib
```

**Comment by danobi** [comment]
Here's the root cause: https://github.com/llvm/llvm-project/blob/d4ff9615a1531f4a466b7d1fb0f175e3ae489289/lldb/source/API/CMakeLists.txt#L147-L153

**Comment by RossComputerGuy** [comment]
> Here's the root cause: https://github.com/llvm/llvm-project/blob/d4ff9615a1531f4a466b7d1fb0f175e3ae489289/lldb/source/API/CMakeLists.txt#L147-L153

Sweet, I'll get started on a PR fixing this. If you can find any other affected versions, lmk.

**Comment by paparodeo** [comment]
> > Here's the root cause: https://github.com/llvm/llvm-project/blob/d4ff9615a1531f4a466b7d1fb0f175e3ae489289/lldb/source/API/CMakeLists.txt#L147-L153
> 
> Sweet, I'll get started on a PR fixing this. If you can find any other affected versions, lmk.

looks like it is an issue all the way back to llvm12.

```console
$ nix-build -A llvmPackages_12.lldb.lib
/nix/store/bls4l47mjga4s869vvqppkh6s1n27fhr-lldb-12.0.1-lib
$ patchelf --print-rpath result-lib/lib/liblldb.so|xargs -d ':' -n 1
$ORIGIN/..//nix/store/bls4l47mjga4s869vvqppkh6s1n27fhr-lldb-12.0.1-lib/lib
///nix/store/wn3s8rxc7zv00ibj9gsj8f353yj4849s-llvm-12.0.1-lib/lib
$ORIGIN/../../../../lib
/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/lib
/nix/store/x5mpg1pjazhvja8aq0yxig2zgz51i9c1-lua-5.3.6/lib
/nix/store/j4m3lwhh4x0bzilvi77d512ahry775nq-ncurses-6.4/lib
/nix/store/bmjckrv5ryxahvkldr47jyx7zmlrcan3-libedit-20230828-3.1/lib
/nix/store/kf7fzax0av9him9m4zcmbqmihh5108wq-libxml2-2.12.7/lib
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib
/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib/lib
/nix/store/qhfk7hvngljfi8bck3b7rskl69h5xk8g-clang-12.0.1-lib/lib
```
