### ISSUE TITLE
Update request: losslesscut-bin 3.58.0 → 3.61.1

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#315306]
- Package name: [losslesscut-bin](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=losslesscut)
- Latest released version: [3.61.1](https://github.com/mifi/lossless-cut/releases/tag/v3.61.1)

- Current version on the unstable channel: 3.58.0
- Current version on the stable/release channel: 3.58.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ShamrockLee

**Comment by ShamrockLee** [comment]
I'm going to submit a PR recently.
