### ISSUE TITLE
GLFW 3.4 does not work correctly with wayland

### ISSUE THREAD

**Issue by roman3pm** [NixOS/nixpkgs#315397]
### Describe the bug
Recently, I used `glfw-wayland` for my little project on OpenGL, and it worked fine. However, after the `glfw` `3.4` update, my application refuses to run with an error `code 65537: "The GLFW library is not initialized"`. This definitely seems to be an issue with the new version. For comparison, `glfw-wayland` `3.3.8` from `nixos-23.11` works flawlessly without any tinkering required.

### Steps To Reproduce
I use this flake configuration
```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { nixpkgs, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      makeShell = pkgs.mkShell.override { stdenv = pkgs.clangStdenv; };
    in
    {
      devShells.${system}.default = makeShell {
        name = "env";
        nativeBuildInputs = with pkgs; [
          cmake
          clang-tools
        ];
        buildInputs = with pkgs; [
          glfw-wayland
          glm
          assimp
        ];
      };
    };
}
```

### Notify maintainers

@getchoo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.11 (Vicuña), 24.11.20240524.bfb7a88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(roz): `"home-manager"`
 - nixpkgs: `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
We maybe should make this into a broader tracking issue for the glfw fallout.

There's a `libwayland-client` issue encountered in https://github.com/NixOS/nixpkgs/pull/303682/commits/a4ebe70f13c1f9d422d73bfab8fdbd203d4d64b7:

```"
❯ unset DISPLAY
~ 
❯ nix run github:NixOS/nixpkgs/master#tracy
Error 65544: Wayland: Failed to load libwayland-client
terminate called without an active exception
Aborted (core dumped)
```

There are variants of "the platform does not setting ..." error:

- https://github.com/NixOS/nixpkgs/pull/293296#issuecomment-2002562523 and https://github.com/NixOS/nixpkgs/pull/310073
- ```
  ❯ nix run github:NixOS/nixpkgs/a4ebe70f13c1f9d422d73bfab8fdbd203d4d64b7#tracy
  Error 65548: Wayland: The platform does not support setting the window position
  Failed to initialize OpenGL loader!
  Segmentation fault (core dumped)
  ```

**Comment by eclairevoyant** [comment]
please provide an MWE

**Comment by roman3pm** [comment]
I haven't used the unstable branch for a while. I just tried it and it seems that the `libwayland-client` fix mentioned above has solved the problem. I apologize for not paying attention to this earlier. Thanks!
