### ISSUE TITLE
Bash relocation GLIBC error

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#31541]
## Issue description

`zsh` seems to throw this error but otherwise seems to function as normal. `steam` hits the same error and is broken though.

### Steps to reproduce

```
$ zsh
/nix/store/h404wfcz8rzzlq8vr4z7plcijwzfci72-bash-4.4-p12/bin/bash: relocation error: /nix/store/mjx71lmnlf4psm9942djjcd8b56hyk8b-glibc-2.26-75/lib/libpthread.so.0: symbol __mmap, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

## Technical details

* System: 18.03.git.7ebacd1 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: 18.03pre120031.7ebacd1a43
* Sandboxing enabled: yes

**Comment by orivej** [comment]
Do you see the same error if you run `LD_LIBRARY_PATH= zsh`?

**Comment by NickHu** [comment]
Yes

**Comment by NickHu** [comment]
I realised this is caused by my `LD_PRELOAD`

```
 ❯ echo $LD_PRELOAD
/nix/store/ilj8ck1zld2n762i45zw8sp2cl517y0j-rxvt-unicode-with-perl-with-unicode3-9.22/lib/urxvt/rxvtwcwidth.so
```

I'm using the rxvtwcwidth patch found here https://aur.archlinux.org/packages/rxvt-unicode-wcwidthcallback/; it used to work just fine, so I wonder what changed.

**Comment by vcunat** [comment]
The library gets preloaded with all its dependencies (I think), replacing all of them in the process that you run.  Manually replacing libs in such ways is easy to get wrong.  Even our nixos solution for libGL and friends causes problems sometimes.
