### ISSUE TITLE
bumblebee does not switch opencl drivers

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#31558]
## Issue description
If I use bumblebee with nvidia driver, I cannot use opencl using optirun. The opencl interface is not found. 

### Steps to reproduce
- enable bumblebee
- run 
`optirun hashcat -I`
- no opencl interface is found

## Technical details
System: 18.03pre120031.7ebacd1a43 (Impala)
Nix version: nix-env (Nix) 1.11.15
Nixpkgs version: "18.03pre120031.7ebacd1a43"
Sandboxing enabled: build-use-sandbox = false

**Comment by gnidorah** [comment]
Not a fix, but you may try this solution instead #33624

**Comment by d4g** [comment]
I dont't know if its not a bit of an overkill to start a separate xserver to use opencl for the nvidia card.
I't prefer that someone would fix the nixos bumble bee and opencl management.

**Comment by Patryk27** [comment]
Hi,

I've managed to get Bumblebee + OpenCL on Nvidia working using:
```nix
{ config, pkgs, ... }: {
  boot.kernelModules = [
    "nvidia-uvm"
  ];

  environment.systemPackages = [
    pkgs.cudatoolkit
    config.boot.kernelPackages.nvidia_x11.bin
    config.boot.kernelPackages.nvidia_x11.settings
  ];

  environment.variables = {
    OPENCL_VENDOR_PATH = "${pkgs.linuxPackages.nvidia_x11}/etc/OpenCL/vendors";
  };

  hardware.bumblebee.enable = true;

  # Copy-pasted from /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/hardware/video/nvidia.nix
  services.udev.extraRules =
    ''
      KERNEL=="nvidia", RUN+="${pkgs.runtimeShell} -c 'mknod -m 666 /dev/nvidiactl c $$(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'"
      KERNEL=="nvidia_modeset", RUN+="${pkgs.runtimeShell} -c 'mknod -m 666 /dev/nvidia-modeset c $$(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 254'"
      KERNEL=="card*", SUBSYSTEM=="drm", DRIVERS=="nvidia", RUN+="${pkgs.runtimeShell} -c 'mknod -m 666 /dev/nvidia%n c $$(grep nvidia-frontend /proc/devices | cut -d \  -f 1) %n'"
      KERNEL=="nvidia_uvm", RUN+="${pkgs.runtimeShell} -c 'mknod -m 666 /dev/nvidia-uvm c $$(grep nvidia-uvm /proc/devices | cut -d \  -f 1) 0'"
      KERNEL=="nvidia_uvm", RUN+="${pkgs.runtimeShell} -c 'mknod -m 666 /dev/nvidia-uvm-tools c $$(grep nvidia-uvm /proc/devices | cut -d \  -f 1) 0'"
      '';
}
```
You can then do:
```
$ optirun nix-shell -p clinfo
$ sudo modprobe nvidia-uvm
$ clinfo
```
:-)

I'm not that proficient in Nix, so I can't tell whether it's worth submitting into the repository (or whether it's a correct solution in the first place), but - ya know - _works for me_ ™.
