### ISSUE TITLE
CoolerControl v1.2.2: daemon does not detect the nvidia proprietary drivers.

### ISSUE THREAD

**Issue by Vilsol** [NixOS/nixpkgs#315594]
### Describe the bug
CoolerControl does not detect Nvidia GPU when enabled via options

### Steps To Reproduce
1. Nvidia GPU with proprietary drivers (version 555, but might not matter)
2. `programs.coolercontrol.enable = true;`
3. `programs.coolercontrol.nvidiaSupport = true;`
4. `journalctl -u coolercontrold` spits out error about missing `nvidia-smi` and `nvidia-settings`

### Expected behavior
CoolerControl to detect Nvidia GPU

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/1759390/372f28f0-4ece-4eb9-b823-9797c42d5238)

### Additional context
Logging output:

```console
May 22 21:27:04 cortex coolercontrold[143375]: Logging Level: INFO
May 22 21:27:04 cortex coolercontrold[143375]: Initializing...
May 22 21:27:04 cortex coolercontrold[143375]: Configuration file check successful
May 22 21:27:07 cortex coolercontrold[143375]: Communication established with Liqctld.
May 22 21:27:07 cortex coolercontrold[143375]: Initialized Liquidctl Devices: ["Corsair Lighting Node Pro"]
May 22 21:27:07 cortex coolercontrold[143375]: Initialized CPU Devices: ["Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"]
May 22 21:27:07 cortex coolercontrold[143375]: Error communicating with nvidia-smi. If you have a Nvidia card with proprietary drivers, nvidia-smi and nvidia-settings are required.
```

---

If I manually stop the systemd process and start `sudo coolercontrold` it detects the requested binaries correctly, which makes me think that the coolercontrold binary just doesn't search the correct paths.

### Notify maintainers

@codifryed @OPNA2608

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240526.e2dd4e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(vilsol): `""`
 - channels(root): `"nixos-23.11, nixos-unstable, nixpkgs-unstable"`
 - nixpkgs: `/nix/store/62ca8xfz3n92p57sdds15r4s07kyls6i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
> the coolercontrold binary just doesn't search the correct paths

The tools should be on PATH if you check the generated service file.

```nix
    # Nvidia support
    (lib.mkIf cfg.nvidiaSupport {
      systemd.services.coolercontrold.path = with config.boot.kernelPackages; [
        nvidia_x11 # nvidia-smi
        nvidia_x11.settings # nvidia-settings
      ];
    })
```

And restarting the daemon would support that I think, since it shouldn't pick up any new paths from the env AFAIU.

> ```
> Error communicating with nvidia-smi. If you have a Nvidia card with proprietary drivers, nvidia-smi and nvidia-settings are required.
> No GPU devices detected
> ```

I'm pretty sure the second part of that message comes from `nvidia-smi` itself.

https://gitlab.com/coolercontrol/coolercontrol/-/blob/029cbe9a8a8bb26c0b8d4a9404a871e60a800e67/coolercontrold/src/repositories/gpu_repo.rs#L189-196
https://gitlab.com/coolercontrol/coolercontrol/-/blob/029cbe9a8a8bb26c0b8d4a9404a871e60a800e67/coolercontrold/src/repositories/utils.rs#L70-126

So `nvidia-smi` might not like whatever state your system is in whenever `coolercontrold` first launches?

I sadly don't have any nvidia system to test this with… I think if you try something like this you could delay the service startup to check if the above guess is correct?

```nix
systemd.services.coolercontrold.serviceConfig.ExecStartPre = "${lib.getExe' pkgs.coreutils "sleep"} 10";
```

(Or override the package with an overlay and patch it into the service that way if this doesn't work the way I think it does)

**Comment by Vilsol** [comment]
Restarting the service does not work, as that throws out the same identical error.

After adding that to my config, rebuilding and restarting the service, I get this output:
```console
● coolercontrold.service - CoolerControl Daemon
     Loaded: loaded (/etc/systemd/system/coolercontrold.service; enabled; preset: enabled)
    Drop-In: /nix/store/j0sjhvl62mhl4q2kaw445pzn4kj4f669-system-units/coolercontrold.service.d
             └─overrides.conf
     Active: active (running) since Wed 2024-05-29 15:55:06 EEST; 51s ago
    Process: 246351 ExecStartPre=/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin/sleep 10 (code=exited, status=0/SUCCESS)
   Main PID: 246614 (coolercontrold)
         IP: 0B in, 0B out
         IO: 0B read, 8.0K written
      Tasks: 18 (limit: 75809)
     Memory: 23.6M (peak: 25.0M)
        CPU: 348ms
     CGroup: /system.slice/coolercontrold.service
             └─246614 /nix/store/racw52cqg7llndjqgndj3mr14nd7njav-coolercontrold-1.2.2/bin/coolercontrold

May 29 15:55:18 cortex coolercontrold[246614]: Initialized CPU Devices: ["Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"]
May 29 15:55:18 cortex coolercontrold[246614]: Error communicating with nvidia-smi. If you have a Nvidia card with proprietary drivers, nvidia-smi and nvidia-settings are required.
May 29 15:55:18 cortex coolercontrold[246614]: No GPU Devices detected
May 29 15:55:18 cortex coolercontrold[246614]: Initialized GPU Devices: []
May 29 15:55:18 cortex coolercontrold[246614]: Error reading temperature value from: "/sys/class/hwmon/hwmon5"/temp1_input - No data available (os error 61)
May 29 15:55:18 cortex coolercontrold[246614]: Initialized Hwmon Devices: ["nvme1", "acpitz", "nvme0"]
May 29 15:55:18 cortex coolercontrold[246614]: Initialized Custom Sensors: []
May 29 15:55:18 cortex coolercontrold[246614]: Applying all saved device settings
May 29 15:55:18 cortex coolercontrold[246614]: API bound to IPv4 and IPv6 addresses: 127.0.0.1:11987, [::1]:11987
May 29 15:55:18 cortex coolercontrold[246614]: Daemon successfully initialized
```
which looks like sleep succeeded, but not sure how that would help so I did this instead:
```nix
systemd.services.coolercontrold.serviceConfig.ExecStartPre = "${lib.getExe' config.boot.kernelPackages.nvidia_x11_beta "nvidia-smi"} -L";
```

Which I either did wrong, but it seems to print the GPU fine?
```console
$ journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value coolercontrold.service`
May 29 16:04:22 cortex nvidia-smi[340429]: GPU 0: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-0bb60bf8-aed8-cafd-fbf1-bf60e4024959)
May 29 16:04:22 cortex coolercontrold[340431]: Logging Level: INFO
May 29 16:04:22 cortex coolercontrold[340431]: Initializing...
May 29 16:04:22 cortex coolercontrold[340431]: Configuration file check successful
May 29 16:04:33 cortex coolercontrold[340431]: Communication established with Liqctld.
May 29 16:04:34 cortex coolercontrold[340431]: Initialized Liquidctl Devices: ["Corsair Lighting Node Pro"]
May 29 16:04:34 cortex coolercontrold[340431]: Initialized CPU Devices: ["Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz"]
May 29 16:04:34 cortex coolercontrold[340431]: Error communicating with nvidia-smi. If you have a Nvidia card with proprietary drivers, nvidia-smi and nvidia-settings are required.
May 29 16:04:34 cortex coolercontrold[340431]: No GPU Devices detected
May 29 16:04:34 cortex coolercontrold[340431]: Initialized GPU Devices: []
May 29 16:04:34 cortex coolercontrold[340431]: Error reading temperature value from: "/sys/class/hwmon/hwmon5"/temp1_input - No data available (os error 61)
May 29 16:04:34 cortex coolercontrold[340431]: Initialized Hwmon Devices: ["nvme0", "acpitz", "nvme1"]
May 29 16:04:34 cortex coolercontrold[340431]: Initialized Custom Sensors: []
May 29 16:04:34 cortex coolercontrold[340431]: Applying all saved device settings
May 29 16:04:34 cortex coolercontrold[340431]: API bound to IPv4 and IPv6 addresses: 127.0.0.1:11987, [::1]:11987
May 29 16:04:34 cortex coolercontrold[340431]: Daemon successfully initialized
```

But that made me realize one difference. I am on beta drivers, but as per your code block, you pull in the stable ones... Could that be the distinguishing factor? In which case, maybe it might be better if it pulled in the field `hardware.nvidia.package` rather than hardcode to stable drivers?

**Comment by OPNA2608** [comment]
> If I manually stop the systemd process and start `sudo coolercontrold` it detects the requested binaries correctly

Oh sorry, I thought that read "restart coolercontrold".

> I am on beta drivers, but as per your code block, you pull in the stable ones... Could that be the distinguishing factor?

Maybe.

> In which case, maybe it might be better if it pulled in the field `hardware.nvidia.package` rather than hardcode to stable drivers?

*Likely*.
