### ISSUE TITLE
Build failure: difftastic

### ISSUE THREAD

**Issue by SolidRhino** [NixOS/nixpkgs#315634]
### Steps To Reproduce

1. nix shell nixpkgs#difftastic (on macOS Sonoma 14.5)

### Build log

[log](https://gist.github.com/SolidRhino/bb41f7de71609d11c19baf65695f19fb)

### Additional context

This problem occurs on macOS Sonoma 14.5 after the removal of the patch for mimalloc.

### Notify maintainers

@matthiasbeyer
@figsoda
@ethancedwards8 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Extracting the actual error:

```
warning: libmimalloc-sys@0.1.24: In file included from c_src/mimalloc/src/static.c:24:
warning: libmimalloc-sys@0.1.24: In file included from c_src/mimalloc/src/random.c:198:
warning: libmimalloc-sys@0.1.24: /nix/store/xillssqgyfw8bzda8mqq2wd4k1nbqxmd-Libsystem-1238.60.2/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
warning: libmimalloc-sys@0.1.24: typedef CCCryptorStatus CCRNGStatus;
```
