### ISSUE TITLE
Build failure: bitwarden-cli (aarch64-darwin)

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixpkgs#315667]
### Steps To Reproduce

```console
$ nix build github:nixos/nixpkgs#bitwarden-cli --print-build-logs
```

### Build log

https://gist.github.com/n8henrie/45020d467d57f3283bbe7b9ea57b1d13

### Notify maintainers

@dotlambda

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.4`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/x44yrfrlx00rsbab7lqc5f71qwjazb56-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by n8henrie** [comment]
I tried adding `xcrun` to inputs but then seems to run into https://github.com/NixOS/nixpkgs/issues/261820 when building argon2, which in turn may be fixed by https://github.com/NixOS/nixpkgs/pull/262124.

**Comment by dotlambda** [comment]
> I tried adding `xcrun` to inputs

To me the logs look like xcrun is only run if an error occurs.

**Comment by khaneliman** [comment]
Still running into this? Looks like it still builds for me on master.

**Comment by n8henrie** [comment]
Nope, seems to be resolved.

**Comment by duckpuppy** [comment]
I'm still seeing this build failure on nixpkgs/master as of today.

**Comment by dotlambda** [comment]
@duckpuppy No it's a different error message: #339576
