### ISSUE TITLE
Calamares Install Error with Swapon (MacBook Air 7,2 with 120GB SSD & 8GB Ram)

### ISSUE THREAD

**Issue by Kha1r0** [NixOS/nixpkgs#315741]
### Describe the bug
Using Calamares to install NixOS from USB with all the default settings, specifically automatic partitioning with a swap partition with hibernate.
See https://termbin.com/1ab6 for more detail.
I have tried checksumming, different USB Drives, USB Ports, different Formatting of the SSD beforehand. 
It has also worked before, maybe 2-3 months ago.

### Steps To Reproduce
1. Download default x86 GNOME iso
2. checksum
3. flash with balena etcher macOS
4. boot into it
5. select pretty much all the defaults, specifically automatic formatting with swap with hibernate
6. click install
7. fails after about 10s

### Expected behavior
a normal install.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/115714947/0814a4cb-b757-4611-b3f3-58f09c231c78)

### Additional context
-

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
(Note that this is from the live environment)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.91, NixOS, 23.11 (Tapir), 23.11.7313.9d29cd266ceb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11.7313.9d29cd266ceb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
reported upstream in https://github.com/NixOS/calamares-nixos-extensions/issues/34
