### ISSUE TITLE
Update request: cbqn 0.5.0 → 0.7.0

### ISSUE THREAD

**Issue by IGJoshua** [NixOS/nixpkgs#315768]
- Package name: cbqn
- Latest released version: 0.7.0

- Current version on the unstable channel: 0.5.0
- Current version on the stable/release channel: 0.4.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@AndersonTorres @sternenseemann @Synthetica9 @shnarazk @Detegr 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Closed a week ago at 

https://github.com/NixOS/nixpkgs/pull/314614
