### ISSUE TITLE
washed out colors on nixos-unstable starting from  33d1e75 

### ISSUE THREAD

**Issue by cschierig** [NixOS/nixpkgs#315876]
### Describe the bug
My laptop display's colors are washed out/brighter since [33d1e75](https://hydra.nixos.org/eval/1806313). The previous hydra build [2057814](https://hydra.nixos.org/eval/1806252) is still working.

colord seems to be starting normally. Gnome Settings also shows the color profile in the color management section.

I would be happy to narrow the issue down to a specific commit, but I haven't figured out how to pin the flake input to a nixpkgs commit which hasn't a hydra build.

### Steps To Reproduce
1. Log into gnome
2. colors are washed out, especially greens.

### Expected behavior

The colors should look the same after upgrading.

### Additional context

I'm using a Lenovo Yoga running Gnome 46 on wayland. The bug is also present on X11.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
Console output from the working rev:

[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240512.2057814`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

Console output from the broken rev:

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cschierig** [comment]
Seems to be fixed on master

**Comment by EricTheMagician** [comment]
I'm having the same issue on 24.05 and switching to unstable fixed it.
Though I would rather stay on 24.05.
