### ISSUE TITLE
Godot should be built with gcc-5 instead of 6

### ISSUE THREAD

**Issue by orivej** [NixOS/nixpkgs#31584]
@jascase901 commented on [Mon Nov 13 2017](https://github.com/NixOS/nix/issues/1675)

<http://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html>

> Known issues with GCC 6
> There are known optimisation issues when using GCC 6 (both to compile for X11 and to cross-compile for Windows with MinGW). Until those issues are fixed in Godot’s source, or the compiler is made more forgiving again, it is advised not to use GCC 6 to compile Godot as release builds will trigger crashes.
> If your distribution provides GCC 6 by default (e.g. Arch or Ubuntu 16.10), you may have to install an older version or Clang (both should be provided in the repositories). You can then force the use of another compiler version via the CC and CXX scons arguments (e.g. scons p=x11 CC=gcc-5 CXX=g++-5 if your distribution provides those binaries in its PATH). You can also use llvm=yes instead to force the usage of Clang over GCC.

I noticed a crash in my godot project related to this issue.

    gdb --args godot.x11.tools.64 -e

0x00007ffff516222d in \_<sub>dynamic</sub><sub>cast</sub> ()
   from /nix/store/y5ac95kk3nb52si8zcyznjrfb45720hk-gcc-6.4.0-lib/lib/libstdc++.so.6

If I rebuild godot with gcc-5, and load godot in a pure nixshell then the crash no longer happens.

    nix-shell -i nixpkgs=~/nixpkgs -p godot --pure # fixes the crash
    nix-shell -i nixpkgs=~/nixpkgs -p godot #still crashes

this is the the default.nix I am using  I also upgraded to 2.1.4-stable and will make a pull request once I clean it up.

    { stdenv, fetchFromGitHub,gcc5, scons, pkgconfig, libX11, libXcursor
    , libXinerama, libXrandr, libXrender, freetype, openssl, alsaLib
    , libpulseaudio, mesa_glu, zlib }:
    
    stdenv.mkDerivation rec {
      name    = "godot-${version}";
      version = "2.1.4-stable";
    
      src = fetchFromGitHub {
        owner  = "godotengine";
        repo   = "godot";
        rev    = version;
        sha256 = "0d2zczn5k7296sky5gllq55cxd586nx134y2iwjpkqqjr62g0h48";
      };
    
      buildInputs = [
        gcc5 scons pkgconfig libX11 libXcursor libXinerama libXrandr libXrender
        freetype openssl alsaLib libpulseaudio mesa_glu zlib
      ];
    
      patches = [ ./pkg_config_additions.patch ];
    
      enableParallelBuilding = true;
    
      buildPhase = ''
        scons platform=x11 prefix=$out -j $NIX_BUILD_CORES  target=release_debug 
      '';
    
      installPhase = ''
        mkdir $out/bin -p
        cp bin/godot.* $out/bin/
      '';
    
      meta = {
        homepage    = "https://godotengine.org";
        description = "Free and Open Source 2D and 3D game engine";
        license     = stdenv.lib.licenses.mit;
        platforms   = stdenv.lib.platforms.linux;
      };
    }

**Comment by prusnak** [comment]
Closed via https://github.com/NixOS/nixpkgs/pull/31587
