### ISSUE TITLE
`citrix_workspace`: only `citrix-setlog` is in PATH

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#315861]
After running:
```bash
NIXPKGS_ALLOW_UNFREE=1 nix-shell -p citrix_workspace
```
Only `citrix-setlog` is added to PATH.

![image](https://github.com/NixOS/nixpkgs/assets/78746991/b17de7f1-518e-4606-bada-cf40a936a59a)

### Steps To Reproduce
1. Download and add  `linuxx64-24.2.0.65.tar.gz` to nix store as explained in the derivation.
2. `NIXPKGS_ALLOW_UNFREE=1 nix-shell -p citrix_workspace`
3. Observe no way to launch citrix workspace since Desktop entry is missing and there is no citrix_workspaces binary on PATH.

### Expected behavior
`citrix-workspace` binary added to PATH or a new Desktop file added.

If I install `citrix_workspace` using system config I can access `Citrix Workspaces` desktop file. But not when I temporarily install it using `nix-shell -p`.

### Notify maintainers
@michaeladler

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.2, NixOS, 24.11 (Vicuña), 24.11.20240527.9ca3f64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/b2xy0gk6sd3fc8zamarfzach5f3wpkvi-source
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hakan-demirli** [comment]
I using Hyprland window manager. So, if this is not an issue on gnome/kde when it is installed using `nix-shell` then I messed up something while I was configuring my desktop environment.

**Comment by michaeladler** [comment]
Seems to be working just fine:

```sh
$ ls -al $(nix-build --no-out-link '<nixpkgs>' -A citrix_workspace)/bin/
total 168
dr-xr-xr-x 1 root root   402 Jan  1  1970 .
dr-xr-xr-x 1 root root    22 Jan  1  1970 ..
-r-xr-xr-x 2 root root 20056 Jan  1  1970 citrix-setlog
lrwxrwxrwx 2 root root    35 Jan  1  1970 .citrix-setlog-wrapped -> ../opt/citrix-icaclient/util/setlog
-r-xr-xr-x 2 root root 20056 Jan  1  1970 configmgr
lrwxrwxrwx 2 root root    38 Jan  1  1970 .configmgr-wrapped -> ../opt/citrix-icaclient/util/configmgr
-r-xr-xr-x 2 root root 20056 Jan  1  1970 conncenter
lrwxrwxrwx 2 root root    39 Jan  1  1970 .conncenter-wrapped -> ../opt/citrix-icaclient/util/conncenter
-r-xr-xr-x 2 root root 20056 Jan  1  1970 ctx_rehash
lrwxrwxrwx 2 root root    39 Jan  1  1970 .ctx_rehash-wrapped -> ../opt/citrix-icaclient/util/ctx_rehash
-r-xr-xr-x 2 root root 20056 Jan  1  1970 selfservice
lrwxrwxrwx 2 root root    35 Jan  1  1970 .selfservice-wrapped -> ../opt/citrix-icaclient/selfservice
-r-xr-xr-x 2 root root 20056 Jan  1  1970 storebrowse
lrwxrwxrwx 2 root root    40 Jan  1  1970 .storebrowse-wrapped -> ../opt/citrix-icaclient/util/storebrowse
-r-xr-xr-x 2 root root 20056 Jan  1  1970 wfica
lrwxrwxrwx 2 root root    29 Jan  1  1970 .wfica-wrapped -> ../opt/citrix-icaclient/wfica
```

**Comment by hakan-demirli** [comment]
Thank you. I didn't know how to check binaries exported by the derivation. Looks like they don't start with `citrix` prefix which is what I was expecting.
