### ISSUE TITLE
exfat-nofuse: does not build on aarch64

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#31595]
## Issue description

Trying to build `exfat-nofuse` on aarch64 results in:
```
fatal error: ../../arm/include/asm/opcodes.h: No such file or directory
 #include <../../arm/include/asm/opcodes.h>
```
(see hydra https://hydra.nixos.org/build/63839331/nixlog/1 )

If somebody could give a hint on how to fix this or saw similar issues in other packages i'd love to make this work again. Main issue is that i essentially get 5 mails from hydra every now and then which state "exfat-nofuse build failed"

### Steps to reproduce

on `aarch64` (raspi3 for example)
```
nix-shell -p linuxPackages_4_9.exfat-nofuse
```

## Technical details

 - system: `"aarch64-linux"`                                                                                                                          
 - host os: `Linux 4.13.5, stockholm/NixOS, unknown/18.03.git.809cf38 (Impala)`                                                                       
 - multi-user?: `yes`                                                                                                                                 
 - sandbox: `yes`                                                                                                                                     
 - version: `nix-env (Nix) 1.11.15`                                                                                                                   
 - channels(root): `"nixos-18.03pre-git"`                                                                                                             
 - nixpkgs: `/var/src/nixpkgs`

**Comment by dezgeg** [comment]
There's a packaging bug such that all external kernel modules fail to build on aarch64, but then there's also one presumably upstream bug that I don't know how to fix.

**Comment by dezgeg** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/commit/eb857611378576f96022867a9fd15a7a841e518c.

**Comment by dezgeg** [comment]
Got fixed.

**Comment by makefu** [comment]
awesome, thanks!
