### ISSUE TITLE
pam_ssh_agent_auth allowing users to define own ssh pubkey

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#31611]
Security impact: passwordless programmatic elevation of privileges via `sudo` to sudo-defined level.

## Issue description

In [the manpage](http://pamsshagentauth.sourceforge.net/) it says that if `~` or `%h` are used, they enable `allow_user_owned_authorized_keys_file`.

We are using `~`, so that means that if you are using `security.pam.enableSSHAgentAuth = true;`, any program running as a user can use sudo by changing the `~/.authorized_keys` file.

I propose we replace `%` by `/users/%U` or somehow disable `allow_user_owned_authorized_keys_file`.

### Steps to reproduce

```
151 $ ssh-agent bash
140 $ sudo -v
[sudo] password for wmertens:
^C

141 $ ssh-keygen -f test
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in test.
Your public key has been saved in test.pub.

142 $ cat test.pub >> .ssh/authorized_keys
143 $ ssh-add test
Identity added: test (test)

144 $ sudo -v
145 $ sudo -l
Matching Defaults entries for wmertens on cap-new:
    env_keep+=TERMINFO_DIRS, env_keep+=TERMINFO, env_keep+=SSH_AUTH_SOCK

User wmertens may run the following commands on cap-new:
    (ALL : ALL) SETENV: ALL
```

## Technical details

* System: 17.03.1840.88604ee33a (Gorilla)

Relevant setting is at https://github.com/NixOS/nixpkgs/blob/ea35bc94bf0efd28e39cf4e8212f7df5b6e78aba/nixos/modules/security/pam.nix#L260

/cc @edolstra

**Comment by orivej** [comment]
Does this work when the user does not belong to the `wheel` group?

**Comment by globin** [comment]
cc @grahamc, @fpletz, @domenkozar, @rbvermaa

**Comment by wmertens** [comment]
It will give you whatever permissions your user can receive via `sudo`.

**Comment by fpletz** [comment]
The authorized_keys paths should probably be configurable anyway but the default is pretty bad. I think we should just remove the `~` paths. This breaks backward-compatibility but I'm not sure how to disable `allow_user_owned_authorized_keys_file` after reading the man page.

This is also probably worth a CVE. Opinions? /cc @grahamc

**Comment by wmertens** [comment]
Well, it looks like we can keep most backwards-compatibility by changing ~
to /home/%U, but that won't catch non-default homedirs.

However, personally I would love to only allow ssh keys from /etc. That's
what I was assuming when I enabled it…

**Comment by wmertens** [comment]
So uhm - kind of disappointing how this is lingering…

**Comment by wmertens** [comment]
See #32178 for an example fix. I image we should also put it in the changelog, and it's not something we can just merge into stable…

**Comment by wmertens** [comment]
@fpletz @globin shall I just merge #32178? How do I mark it as a breaking change? What should we do about our stable branches?

**Comment by wmertens** [comment]
I just thought of a backwards-compatible way to fix this: make a new setting `enablePAMSSHAuth` with the secure configuration, and make the `enableSSHAgentAuth` setting deprecated with a warning on every evaluation. Makes sense? @fpletz @GrahamcOfBorg

**Comment by sometimes-i-send-pull-requests** [comment]
I maintain a multi-user installation of NixOS where I initially create users with one public key they provide me, and thereafter they are free to add their own keys. In my installation, it is intentional that users are able to add their own keys, and sudo needs to follow along. So, if this behavior is changed, it is important to me that there's a way to change it back to the way it is currently, as in my installation, this is intended behavior. (I even submitted PR #23435 to fix this behavior when it broke once.)

Aside from my own use case, I also have qualms about making this change default in general. The root of my objection stems from the inconsistency it would introduce with how OpenSSH handles keys. As a user, I expect that if I turn on PAM SSH authentication, then it will use the same set of keys that OpenSSH uses for authentication. If we now say that configured keys are inherently more trustworthy than user-specified keys (which is reasonable), but apply that only to sudo and not also login to the system in general, that is inconsistent and _looks_ like a bug (even if it is not really a bug, and was an intentional design decision because of this issue).

I agree that this ought to be configurable because I can certainly see some administrators wanting the ability to turn this off. It should also be configurable independently of how OpenSSH chooses which keys to use. It can even default to allowing only configured keys rather than user-provided keys, as long as OpenSSH uses the same default. But, I do think those two defaults need to match, because anything else looks strange and inconsistent.

**Comment by wmertens** [comment]
Ok so the difference is that for me, strictly the specified key should be
allowed to sudo, and for you, any key that ssh accepts is ok. It should
definitely be configurable then, but I still think the default should be
strict.

**Comment by sometimes-i-send-pull-requests** [comment]
Sure, I can get behind that. As long as it's configurable! I still think there is something to be said for consistency (&rArr; locking down OpenSSH by default too then) but that is a lesser concern.

**Comment by benaryorg** [comment]
The code referred to (in the opening comment):

```
"auth sufficient ${pkgs.pam_ssh_agent_auth}/libexec/pam_ssh_agent_auth.so file=~/.ssh/authorized_keys:~/.ssh/authorized_keys2:/etc/ssh/authorized_keys.d/%u"} 
```

Should have an option (boolean) that removes the `~/.ssh/authorized_keys:~/.ssh/authorized_keys2` part.
That way you can configure the authentication to only use the system-supplied keys.

**Comment by bricewge** [comment]
Two other PAM modules seems to suffer the same vulnerability: `security.pam.yubico` and `security.pam.enableOTPW`.

**Comment by wmertens** [comment]
I just noticed in the logs that pam_ssh_agent_auth refuses to use my ~/.ssh keys because they have the wrong owner, so looks like it's fixed?

@bricewge could you confirm

**Comment by Majiir** [comment]
**I can still reproduce this vulnerability on 23.05.**

The [current implementation](https://github.com/NixOS/nixpkgs/blob/9d56365451588555cb21a50f28dbeac6c2d628d0/nixos/modules/security/pam.nix#L530) uses `config.services.openssh.authorizedKeysFiles` which [defaults to](https://github.com/NixOS/nixpkgs/blob/9d56365451588555cb21a50f28dbeac6c2d628d0/nixos/modules/services/networking/ssh/sshd.nix#L544-L545) `%h/.ssh/authorized_keys:/etc/ssh/authorized_keys.d/%u`.

**Comment by wrvsrx** [comment]
After https://github.com/NixOS/nixpkgs/pull/255547 has been merged, now we can use following config as workaround.

```nix
  security.sudo.extraConfig = ''
    # Keep SSH_AUTH_SOCK so that pam_ssh_agent_auth.so can do its magic.
    Defaults env_keep+=SSH_AUTH_SOCK
  '';
  security.pam.services =
    let
      serviceCfg = service: {
        rules.auth.ssh-agent-custom = {
          control = "sufficient";
          # order = config.security.pam.services.${service}.rules.auth.u2f.order + 10;
          modulePath = "${pkgs.pam_ssh_agent_auth}/libexec/pam_ssh_agent_auth.so";
          settings.file = "/etc/ssh/authorized_keys.d/%u";
        };
      };
    in
    lib.flip lib.genAttrs serviceCfg [ "sudo" "i3lock" ];
```

**Comment by musjj** [comment]
@wrvsrx

Thanks, this looks a nice solution.

I'm doing this, which seems to work just fine:

```nix
services.openssh.authorizedKeysFiles =
  lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
```

I guess the downside is that you can no longer specify authorized keys in `~/.ssh`, but IMO this seems more secure in general. Any other possible downsides I'm not seeing?

**Comment by wrvsrx** [comment]
@musjj As far as I know, there isn't any other downsides. However, IMO it's a big downside that a normal user can't determine which ssh key should be used to connect to its account.

**Comment by Et7f3** [comment]
In the [man](https://linux.die.net/man/8/pam_ssh_agent_auth) I see allow_user_owned_authorized_keys_file ? shouldn't we set it ? so we don't hardcode config path but if you want to allow ~/.ssh they need to be owned by root

**Comment by musjj** [comment]
@Et7f3 

It also says this:

> allow_user_owned_authorized_keys_file
>     A flag which enables authorized_keys files to be owned by the invoking user, instead of root. This flag is enabled automatically whenever the expansions %h or ~ are used.

I wonder if it can be manually overridden, even when there's a `%h` or `~`?

**Comment by VAWVAW** [comment]
> I'm doing this, which seems to work just fine:
> 
> ```nix
> services.openssh.authorizedKeysFiles =
>   lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
> ```

I just use

```nix
security.pam.sshAgentAuth.authorizedKeysFiles = lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
```

This still allows to login with user writable keys but not to use them for privilege elevation.

**Comment by musjj** [comment]
Yeah, the option didn't exist when I wrote that. But it looks like that the new option pretty much solves this issue.

All that's left is setting a saner default for `authorizedKeysFiles`: https://github.com/NixOS/nixpkgs/pull/277626
