### ISSUE TITLE
ZeroTierOne does not build on Raspberry Pi 2

### ISSUE THREAD

**Issue by anderslundstedt** [NixOS/nixpkgs#31612]
## Issue description

ZeroTierOne does not build on Raspberry Pi 2.

### Steps to reproduce

`nix-env -i zerotierone`

### Result:

    installing ‘zerotierone’
    these derivations will be built:
      /nix/store/1adhiqlzd5gv2xcal9s1r65lvgbf38w5-zerotierone.drv
    building path(s) ‘/nix/store/4ivpqanzcb1y9rizvkkc5f81q240g3wa-zerotierone-man’, ‘/nix/store/c515ms2da3k1d7p6rcb60c83sar9f5b9-zerotierone’
    unpacking sources
    unpacking source archive /nix/store/x104mg4z60x256l5qdv6c5ya82iqj50q-1.2.4.tar.gz
    source root is ZeroTierOne-1.2.4
    setting SOURCE_DATE_EPOCH to timestamp 1493059283 of file ZeroTierOne-1.2.4/zerotier-one.spec
    patching sources
    configuring
    patching script interpreter paths in ./doc/build.sh
    ./doc/build.sh: interpreter directive changed from "/bin/bash" to "/nix/store/4jhga1mzfvpvdfr65d8ya5sm7iy65jcq-bash-4.4-p12/bin/bash"
    no configure script, doing nothing
    building
    build flags: SHELL=/nix/store/4jhga1mzfvpvdfr65d8ya5sm7iy65jcq-bash-4.4-p12/bin/bash
    make-linux.mk:162: *** FATAL: architecture could not be determined from gcc -dumpmachine: C_MACH.  Stop.
    builder for ‘/nix/store/1adhiqlzd5gv2xcal9s1r65lvgbf38w5-zerotierone.drv’ failed with exit code 2
    error: build of ‘/nix/store/1adhiqlzd5gv2xcal9s1r65lvgbf38w5-zerotierone.drv’ failed

### Probably related

https://github.com/zerotier/ZeroTierOne/issues/601

## Technical details

* System: NixOS `18.03pre120031.7ebacd1a43 (Impala)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: `"18.03pre120031.7ebacd1a43"`
* Sandboxing enabled: `build-use-sandbox = false`

**Comment by atopuzov** [comment]
PR for the fix https://github.com/zerotier/ZeroTierOne/pull/654
