### ISSUE TITLE
Docker images built through `pkgsCross`+`pkgsMusl` contain build host artifacts

### ISSUE THREAD

**Issue by jcaesar** [NixOS/nixpkgs#316114]
### Describe the bug
The docker images built e.g. like `nixpkgs#pkgsCross.armv7l-hf-multiplatform.pkgsMusl.dockerTools.examples.layered-image` unnecessarily contain a native `bash` and `linux-headers`, causing roughly 10 MB of bloat (which isn't much, but given the size of the entire image is only 16 MB, it's more bloat than load in this case).

### Steps To Reproduce
1. `nix build github:NixOS/nixpkgs?rev=39ffb04fefd3aea37bd0b3b7ba474c607d66b376#legacyPackages.x86_64-linux.pkgsCross.armv7l-hf-multiplatform.pkgsMusl.dockerTools.examples.layered-image`
2. `nix log /nix/store/wd9h80z25qsxrmvn2s2a6jzjl235g49c-layered-image.tar.gz.drv`
3. See layer 2-7, which are unnecessary.

### Expected behavior
arm images should not contain headers or x86 executables.

### Additional context
The cause is quickly tracked down
```
➜ nix eval -vL --raw --expr 'let 
  nixpkgs = builtins.getFlake "github:NixOS/nixpkgs/39ffb04fefd3aea37bd0b3b7ba474c607d66b376";
  pkgs = import nixpkgs { system = "x86_64-linux"; };
  info = pkgs.closureInfo { rootPaths = [ pkgs.pkgsCross.aarch64-multiplatform-musl.coreutils ]; };
in pkgs.lib.readFile "${info}/store-paths"'
… # bunch of paths that shouldn't be there, e.g. linux-headers, see next command

➜ nix why-depends /nix/store/gr9bmfr2jw9bk4g346h7s6qslj6w6maq-coreutils-aarch64-unknown-linux-musl-9.5 /nix/store/qmy4xjnf8zirvx1zq6ddg8fqzg87lfxy-linux-headers-6.7
/nix/store/gr9bmfr2jw9bk4g346h7s6qslj6w6maq-coreutils-aarch64-unknown-linux-musl-9.5
└───/nix/store/2ql7sg72r2ryqgcifzkj894q4z5vz0ap-gmp-with-cxx-aarch64-unknown-linux-musl-6.3.0
    └───/nix/store/jqmkwhcg08ilaj0n07jr68z3gw5ibg9k-aarch64-unknown-linux-musl-gcc-13.2.0-lib
        └───/nix/store/gj8i2ag65dgph4pi89bc34ziaklp2bi4-aarch64-unknown-linux-musl-gcc-13.2.0-libgcc
            └───/nix/store/r5fxr6v5g7bll3x2m9hsxwg3p4acnl8g-musl-aarch64-unknown-linux-musl-1.2.3-dev
                └───/nix/store/qmy4xjnf8zirvx1zq6ddg8fqzg87lfxy-linux-headers-6.7

➜ nix shell nixpkgs#radare2 -c rabin2 -zz /nix/store/gj8i2ag65dgph4pi89bc34ziaklp2bi4-aarch64-unknown-linux-musl-gcc-13.2.0-libgcc/lib/libgcc_s.so.1 | grep /nix/store
…
3240 0x00068889 0x0000099a 98  99   .debug_line_str ascii   /nix/store/r5fxr6v5g7bll3x2m9hsxwg3p4acnl8g-musl-aarch64-unknown-linux-musl-1.2.3-dev/include/bits
```
i.e., the debug information in libgcc is referencing a dev lib

One possible but improper fix is
```patch
diff --git a/pkgs/development/compilers/gcc/common/libgcc.nix b/pkgs/development/compilers/gcc/common/libgcc.nix
index a7de840adc8d..42edea641ec0 100644
--- a/pkgs/development/compilers/gcc/common/libgcc.nix
+++ b/pkgs/development/compilers/gcc/common/libgcc.nix
@@ -7,6 +7,7 @@
 , enableShared
 , targetPlatform
 , hostPlatform
+, buildPackages
 , withoutTargetLibc
 , libcCross
 }:
@@ -156,5 +157,8 @@ in
     #
     + ''
       patchelf --set-rpath "" $libgcc/lib/libgcc_s.so.${libgcc_s-version-major}
+    ''
+    + lib.optionalString (targetPlatform != hostPlatform) ''
+      ${lib.getExe' buildPackages.binutils-unwrapped-all-targets "strip"} --strip-debug $libgcc/lib/libgcc_s.so.${libgcc_s-version-major}
     '');
 }))]))
```

I suspect that a correct fix would either handle `$libgcc` in `pkgs/development/compilers/gcc/common/strip-attributes.nix` or modify `updateDebugListPaths` from `pkgs/development/compilers/gcc/common/libgcc.nix`, but this is not something I have any means to figure out.

### Notify maintainers

@trofi or maybe @ghost

### Metadata

```console
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), j_428906d_20240529004935`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/mzxd9sjqsa5828ag2arhj78nqasyxbbc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Nice one! Let's see if I can find the attribute for that `musl` instance to look closer. It's definitely not one of these two:

```
$ nix path-info -r $(nix-build -A pkgsCross.aarch64-multiplatform.pkgsMusl.musl)
/nix/store/f4j5w38v315jahfg1bifwg6yzqzb8cyi-musl-aarch64-unknown-linux-musl-1.2.3
$ nix path-info -rsSh $(nix-build -A pkgsCross.aarch64-multiplatform.pkgsMusl.stdenv.cc.libc)
/nix/store/chajrzn23i49lv3arl88kazcdm9201gy-musl-aarch64-unknown-linux-musl-1.2.3          3.8M    3.8M
```

Which probably means `layered-image` does something unusual.

> /nix/store/gj8i2ag65dgph4pi89bc34ziaklp2bi4-aarch64-unknown-linux-musl-gcc-13.2.0-libgcc

(To state the obvious) It's a `libgcc` output for a `gcc` cross-compiler (and not a standalone `libgcc` derivation). It uses a problematic `lib/libgcc_s.so.1` layout that does not match upstream's `gcc` which usually assumes host libraries.  The assumption is hidden in `common/strip-attributes.nix`:

```
  # $lib (host != target):
  # `- <TARGET>/lib/*.{la,so}: TARGET
  #
  # $lib (host == target):
  # `- lib/*.{la,so}: HOST
```

I'll have a look.

**Comment by trofi** [comment]
Probably this attribute:

```
$ nix path-info -r $(nix-build -A pkgs.pkgsCross.aarch64-multiplatform-musl.stdenv.cc.cc.libgcc)
/nix/store/1q9vc0lq7qjlfjz47mfmlzdf86c543jy-xgcc-13.2.0-libgcc
/nix/store/yfp7dr8m7zi7kxk49wd714gwvhb105hf-libunistring-1.1
/nix/store/ic63ay0py10fyryaw7345k4ps32da33w-libidn2-2.3.7
/nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52
/nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26
/nix/store/chajrzn23i49lv3arl88kazcdm9201gy-musl-aarch64-unknown-linux-musl-1.2.3
/nix/store/4pi3kp3hlpgzp0g44kgn4zdnz8d4ar6r-musl-aarch64-unknown-linux-musl-1.2.3-bin
/nix/store/qmy4xjnf8zirvx1zq6ddg8fqzg87lfxy-linux-headers-6.7
/nix/store/r5fxr6v5g7bll3x2m9hsxwg3p4acnl8g-musl-aarch64-unknown-linux-musl-1.2.3-dev
/nix/store/gj8i2ag65dgph4pi89bc34ziaklp2bi4-aarch64-unknown-linux-musl-gcc-13.2.0-libgcc
```

For comparison `glibc` one is a standalone `libgcc` derivation:

```
$ nix path-info -r $(nix-build -A pkgs.pkgsCross.aarch64-multiplatform.stdenv.cc.cc.libgcc)
/nix/store/kimql93z5whx29s8h27fil9bwxnckxwn-libgcc-aarch64-unknown-linux-gnu-13.2.0
```

**Comment by trofi** [comment]
It feels like the cheapest fix here could be is to move `libgcc` output creation `preFixupLibGccPhase` from `preFixupPhases` list to `postFixupPhases` as `fixupPhases` does the actual stripping (via `fixupOutputHooks+=(_doStrip)`).

**Comment by trofi** [comment]
Managed to do it in a non-invasive way as https://github.com/NixOS/nixpkgs/pull/316334. Please give it a try.

**Comment by jcaesar** [comment]
Thank you, that does indeed remove the x86 binaries and linux headers from the docker images I tried building (for armv7l, aarch64, and riscv64).
