### ISSUE TITLE
Crystal nix derivation broken?

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#31622]
## Issue description
https://github.com/crystal-lang/crystal/issues/5279

### Steps to reproduce
With my nix derivation.

```Nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "crystal";

  src = fetchFromGitHub {
    owner   = "crystal-lang";
    repo    = "crystal";
    rev     = "c9fac5645af477f1be5aedf885e3cd8202cb4803";
    sha256  = "0syb63m8jk32493whv2d712dl7j5mhxmd86ga0z5d6pk5zmdxdpc";
  };

  buildInputs = [
    llvm_5
    pcre
    boehmgc
    libevent
    openssl
  ];

  meta = with stdenv.lib; {
    description = "The Crystal Programming Language";
    platforms = platforms.linux;
  };
}
```
```
nix-shell
make
.build/crystal path_to_example_code
./example_binary
```

With installed crystal package from nixpkgs.
default.nix
```Nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "test";
  src = ./test.cr;

  buildInputs = [
    crystal
    openssl
    zlib
  ];

  buildCommand = ''
    crystal build --no-color $src -o $out
  '';
}
```

test.cr
```Crystal
require "http"

HTTP::Server.new("::", 3030,
	HTTP::WebSocketHandler.new do |test|
		ws = HTTP::WebSocket.new("::", "/")
		spawn do
			ws.run
		end
	end
).listen
```
Run
```
nix-build
```
Can't compile code. Logs - https://gist.github.com/MrSorcus/8235111bf53e283388c3d6013804f08e

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`18.03pre120031.7ebacd1a43 (Impala)`
* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.15`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"18.03pre120031.7ebacd1a43"`
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
`build-use-sandbox = false`

**Comment by sifmelcara** [comment]
Hello, I just tried your example using the crystal comes from nixpkgs and cannot reproduce your problem.
Here is the `default.nix` I used:
```nix
with (import ((import <nixpkgs> {}).fetchFromGitHub {
       owner = "NixOS";
       repo = "nixpkgs";
       rev = "7ebacd1a43d7112c75555414d968be9fc4c564a4";
       sha256 = "0qr0iivkmcgngj6d88p5paa85532vsfgmaf4a15c5mgwy6dndpy6";
    }) {} );
stdenv.mkDerivation {
  name = "test";
  src = builtins.toFile "test.cr" ''
    require "http"

    HTTP::Server.new("::", 3030,
      HTTP::WebSocketHandler.new do |test|
        ws = HTTP::WebSocket.new("::", "/")
        spawn do
          ws.run
        end
      end
    ).listen
  '';

  buildInputs = [
    crystal
    openssl
    zlib
  ];

  buildCommand = ''
    crystal build --no-color $src -o $out
  '';
}
```
The `./result` binary seems fine. It starts a server and listening at port 3030.

**Comment by RX14** [comment]
I think just `ECR.embed("/path/to/empty/file")` would be a minimal reproduction for the crystal part of the code. It involves compiling and running a crystal program to process the ecr template while compiling the main example above.

**Comment by MrSorcus** [comment]
@sifmelcara Your default.nix doesn't work for me. I think that trouble not in crystal or nixos/nixpkgs.
I will try later with clean installed nixos.

**Comment by MrSorcus** [comment]
Can't reproduce.

**Comment by MrSorcus** [comment]
I found a problem. It's `/tmp` with `noexec`.
Removing "noexec" solved this problem.
