### ISSUE TITLE
Package request: 2ship2harkinian

### ISSUE THREAD

**Issue by qubitnano** [NixOS/nixpkgs#316326]
**Project description**

It's Shipwright but for Majora's Mask

**Metadata**

* homepage URL: https://github.com/HarbourMasters/2ship2harkinian
* source URL: https://github.com/HarbourMasters/2ship2harkinian
* license: cc0, unfree
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qubitnano** [comment]
I've got it to build, but the audio is all garbled and it crashes after a few seconds on the main menu. Will check against staging-next as upstream builds their binaries with SDL 2.30.3

**Comment by shuniki** [comment]
> I've got it to build, but the audio is all garbled and it crashes after a few seconds on the main menu. Will check against staging-next as upstream builds their binaries with SDL 2.30.3

For me it works flawlessly. Downloaded the appimage and used appimage-run though

**Comment by boomshroom** [comment]
My initial experiences were exactly what both prior comments described. Identical audio glitches and crash when building manually; flawless execution with the prebuilt appimage and appimage-run. Obviously I'd prefer to get the former working as well as the latter, but at least we know it is capable of running at all under the right conditions. We just need to figure out what exactly those conditions are.

**Comment by shuniki** [comment]
> My initial experiences were exactly what both prior comments described. Identical audio glitches and crash when building manually; flawless execution with the prebuilt appimage and appimage-run. Obviously I'd prefer to get the former working as well as the latter, but at least we know it is capable of running at all under the right conditions. We just need to figure out what exactly those conditions are.

It may have something to do with the software they're using. For example they use OpenGL for rendering, so digging into what they use for audio and then tinkering with it might help. I can't remember it off the top of my head, but it's certainly in the context menu if you emulate majora.

**Comment by shuniki** [comment]
Weirdly enough, after installing home-manager with it, the appimage-run method sort of breaks it. It asks for the rom to be put in your home directory but then can't find it. Weird.

**Comment by shuniki** [comment]
> Weirdly enough, after installing home-manager with it, the appimage-run method sort of breaks it. It asks for the rom to be put in your home directory but then can't find it. Weird.

Using sudo on appimage-run gave a horrendous audio "host is down" error. I had to close kitty to stop it.

**Comment by shuniki** [comment]
> > Weirdly enough, after installing home-manager with it, the appimage-run method sort of breaks it. It asks for the rom to be put in your home directory but then can't find it. Weird.
> 
> Using sudo on appimage-run gave a horrendous audio "host is down" error. I had to close kitty to stop it.

My bad, ALSA gave that error. It can't launch sdl_openaudio.

**Comment by shuniki** [comment]
> > > Weirdly enough, after installing home-manager with it, the appimage-run method sort of breaks it. It asks for the rom to be put in your home directory but then can't find it. Weird.
> > 
> > Using sudo on appimage-run gave a horrendous audio "host is down" error. I had to close kitty to stop it.
> 
> My bad, ALSA gave that error. It can't launch sdl_openaudio.

Doing it without sudo simply crashes it with an error message to send it to the discord.

**Comment by shuniki** [comment]
> > > > Weirdly enough, after installing home-manager with it, the appimage-run method sort of breaks it. It asks for the rom to be put in your home directory but then can't find it. Weird.
> > > 
> > > Using sudo on appimage-run gave a horrendous audio "host is down" error. I had to close kitty to stop it.
> > 
> > My bad, ALSA gave that error. It can't launch sdl_openaudio.
> 
> Doing it without sudo simply crashes it with an error message to send it to the discord.

Moved it back to documents. Cd'd into it. No sudo. Works!!! I was probably being stupid or something lmao

**Comment by keenanweaver** [comment]
I'm using steam-run instead of appimage-run and it's working great with no obvious issues, but I'm by no means a Zelda expert.

`nix-shell -p steam-run.out --run 'cd /path/to/appimage && steam-run ./2ship.appimage'`

![image](https://github.com/NixOS/nixpkgs/assets/37268985/a9d27d07-fa14-42c9-b2ef-0b9bc3eb16b6)

**Comment by qubitnano** [comment]
I've been able to reproduce this crash on Fedora 40. It's a slightly different traceback than building on NixOS, but involves the audio stack. Let's see what upstream thinks.

**Comment by qubitnano** [comment]
2ship doesn't segfault when built with  `hardeningEnable = [ "pie" ];` :satisfied:
Please test https://github.com/NixOS/nixpkgs/pull/317889

**Comment by boomshroom** [comment]
Just built the pull request. Appears to run flawlessly.
