### ISSUE TITLE
darling: fails to operate correctly if installed using nix-shell

### ISSUE THREAD

**Issue by jee-mj** [NixOS/nixpkgs#316584]
### Describe the bug

darling doesn't work if it's installed using nix-shell. This issue should be addressed as a user might just want to use it temporarily.

### Steps To Reproduce
1. `nix-shell -p darling`
2. `darling --version`

### Expected behavior
Return the version

### Output
```sh
[nix-shell:~]$ darling --version
Sorry, the `/nix/store/w6i4ihxxjbbdd8yb0kvxlgl1fx0nrgl2-darling-unstable-2024-02-03/bin/darling` binary is not setuid root, which is mandatory.
Darling needs this in order to create mount and PID namespaces and to perform mounts.
```

### Additional context
There is complexity from the permission requirements behind darling.

#### @zhaofengli

Greetings,

We may have spoke before about this issue. I have spoke to someone about the limitations of darling in the context of NixOS in the past. There are tools which are built using proprietary software which only provide outputs for Windows or MacOS.

Could you please advise whether this bug can or should be fixed or not? I spoke to someone about this a long time ago when looking at a solution for this Application and then determining the issue to be fixed with a custom installation of Wine. It may have been yourself.

Anyway, the issue with the Application I'm talking about is out of scope, but I think it's valid for someone to want a functional copy of `darling` by issuing a simple `nix-shell -p darling` or `nix run nixpkgs#darling exec <COMMAND>`.

I can confirm that the `options` method of configuring a system through `configuration.nix` works. I think maybe it should be renamed, and we have a `darling` named package that works for running dynamically such that the code below works?

`nix run nixpkgs#darling exec <COMMAND>`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nix-shell:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zhaofengli** [comment]
Sadly this is an upstream limitation that can't be easily fixed on our end. SUID binaries cannot exist in the Nix store so we need to deploy the wrapper during system profile activation.

**Comment by eclairevoyant** [comment]
This isn't a bug. Per nix's design setuid bits are not set in the store, that's why we have a module with a setuid wrapper instead: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/nixos/modules/programs/darling.nix#L14

Or you can run it as root with all the associated implications.
