### ISSUE TITLE
Build failure: haskellPackages.ghcup

### ISSUE THREAD

**Issue by jawadcode** [NixOS/nixpkgs#316585]
### Steps To Reproduce

1. build *haskellPackages.ghcup*

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'ghcup-0.1.22.0'
         whose name attribute is located at /nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'ghcup-0.1.22.0'

         at /nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source/pkgs/stdenv/generic/make-derivation.nix:385:7:

          384|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          385|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          386|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       error: Package ‘haskus-utils-variant-3.4’ in /nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source/pkgs/development/haskell-modules/hackage-packages.nix:142677 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
```

### Additional context

I noticed this package was also broken on the 23.05 channel, which I was using before i switched my nixpkgs over to unstable.

### Notify maintainers

Not sure what the instructions mean (my git-fu isn't very good) and it is unclear from the ghcup section of https://raw.githubusercontent.com/NixOS/nixpkgs/nixos-unstable/pkgs/development/haskell-modules/hackage-packages.nix who the maintainers are.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cdepillabout** [comment]
I believe @maralorn had `ghcup` working within Nixpkgs at one point.  But I believe it was dropped because most people wouldn't have a use for getting `ghcup` within Nixpkgs.

Since ghcup isn't usable on NixOS, it would only make sense for people who use Nix on other Linux distros.  Of course, since you're already using Nix, it is usually not too hard to just get GHC and other tools from Nix itself, rather than having to go through ghcup.

That said, it is always better to have more things compiling than less things, so if you (or anyone else) wants to fix this, I imagine we would accept a PR getting it working.

**Comment by maralorn** [comment]
Correct.

ghcup does not distribute a ghc variant which works under nixpkgs. Nixos users should install ghc via Nix. Users of other distros should use the standard ghcup installer, imo.

**Comment by jawadcode** [comment]
I had almost forgotten about this issue, I have moved on from using GHCUp and now just install Stack, HLS, GHC and Cabal manually, I'm planning to switch to IOHK's Haskell.nix overlay soon. I guess this issue is no longer relevant given that GHCUp is antithetical to how NixOS works.
