### ISSUE TITLE
appimage-run does not work on recent app images

### ISSUE THREAD

**Issue by crabdancing** [NixOS/nixpkgs#316579]
### Describe the bug
appimage-run is supposed to be able to run appimages-in-general, but it fails on the [IceStudio](https://github.com/FPGAwars/icestudio) AppImage file.

### Steps To Reproduce
1. Pull AppImage file (icestudio-0.11-linux64.AppImage):
```sh
wget "https://github.com/FPGAwars/icestudio/releases/download/v0.11/icestudio-0.11-linux64.AppImage"
```
2. Attempt to run latest `appimage-run` against it:
```sh
nix run "github:nixos/nixpkgs#appimage-run" "./icestudio-0.11-linux64.AppImage"
```
3. The script says:
```
Not an AppImage file
```

### Expected behavior

Expected it to run IceStudio.

### Notify maintainers

Not sure who's in charge of this. @SuperSandro2000 or @l0b0, maybe?

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 23.11 (Tapir), 23.11.20240421.a5e4bbc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nixPath`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Something is off with that appimage file and the magic header is missing:

```
 ▶ LC_ALL=C readelf -h ~/icestudio-0.11-linux64.AppImage
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
```

compared to a working app image file

```
 ▶ LC_ALL=C readelf -h Bitwarden-Connector-2024.3.2-x86_64.AppImage
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 41 49 02 00 00 00 00 00
```
