### ISSUE TITLE
nodejs: missing bash shell completion

### ISSUE THREAD

**Issue by giggio** [NixOS/nixpkgs#316507]
## Issue description

The `nodePackages_latest.nodejs` package (and the related ones) don't offer Node.js completions, only Npm's. At least for bash Node offers it through `node --completion-bash`.
I'd like this bash completion to be added.

### Steps to reproduce
Install Node, see that there is no completion in the completions dir (I'm using home-manager, so that'd be `~/.nix-profile/share/bash-completion/completions/`).

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-31-generic, Ubuntu, 24.04 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/giggio/.nix-defexpr/channels/nixpkgs`
```

## Notify maintainers

@goibhniu @cko

**Comment by superherointj** [comment]
Fixed by #316691
