### ISSUE TITLE
Freshrss does not do initial configuration automatically

### ISSUE THREAD

**Issue by jhakonen** [NixOS/nixpkgs#316624]
### Describe the bug
When Freshrss is first taken into use the service presents configuration wizard where it asks for language and complains of invalid file permissions. The service should configure these automatically, but it does not.

### Steps To Reproduce
1. Enable freshrss with
```
services.freshrss = {
    enable = true;
    baseUrl = "http://<MY_DOMAIN_HERE>";
    authType = "none";
    virtualHost = "<MY_DOMAIN_HERE>";
};
```
2. Do nixos rebuild
3. Open "http://<MY_DOMAIN_HERE>" to web browser
4. Freshrss's web page opens to configuration wizard 

### Expected behavior
Freshrss's web page should open to the "Main stream" page.

### Additional context
This can be fixed by manually starting `freshrss-config.service` which does the configuration. It does not get started automatically when you first enable freshrss though, with no indication that you should start it yourself. Which led in my case to much wasted hours and frustration.

Example output from rebuild:
```
[nas-toolbox:rebuild] restarting sysinit-reactivation.target
[nas-toolbox:rebuild] reloading the following units: dbus.service
[nas-toolbox:rebuild] restarting the following units: nginx.service
[nas-toolbox:rebuild] the following new units were started: freshrss-updater.timer, phpfpm-freshrss.service, rsync-backup-freshrss.timer, sysinit-reactivation.target, systemd-tmpfiles-resetup.service
```
^-- No `freshrss-config.service` at the list of new started units

### Notify maintainers
@etu @Stunkymonkey @mattchrist

### Metadata
```console
░▒▓ jhakonen@nas-toolbox │ ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.20240531.805a384`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05"`
 - nixpkgs: `/nix/store/i1aw9jjgxcvyd642s12kw3iasmarwd42-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mattchrist** [comment]
@jhakonen: Can you see if adding the following configuration fixes this for you?
```
    systemd.services.freshrss-config = {
      restartIfChanged = true;
      serviceConfig.RemainAfterExit = true;
    };
```

**Comment by jhakonen** [comment]
Hi, seems that it does indeed fix it. :+1: 

Tested this by starting from scratch:
1. Removed freshrss's nix configuration
2. Ran nixos rebuild
3. Tried accessing freshrss's web page and got 404 error
4. Moved `/var/lib/freshrss` to another location
5. Added freshrss's nix configuration back in and applied your fix
6. Ran nixos rebuild again
7. Tried accessing freshrss's web page and got the expected main stream page

Also another side benefit is that it is now possible to change admin's password via `services.freshrss.passwordFile`. Previously it required also running of `freshrss-config.service` manually afterwards.
