### ISSUE TITLE
 quickemu 4.9.4 `ERROR! You have insufficient RAM to run windows in a VM`

### ISSUE THREAD

**Issue by me00001** [NixOS/nixpkgs#316689]
`ERROR! You have insufficient RAM to run windows in a VM`
Unable to run windows after this update, Using the older version solves the problem.

_Originally posted by @me00001 in https://github.com/NixOS/nixpkgs/issues/310409#issuecomment-2124147179_

**Comment by eclairevoyant** [comment]
How much ram did you allocate?

**Comment by me00001** [comment]
> How much ram did you allocate?

4GB
