### ISSUE TITLE
kdePackages.plasma-workspace: wrapQtApp hook broke libexec/plasma-sourceenv.sh

### ISSUE THREAD

**Issue by natsukagami** [NixOS/nixpkgs#316784]
### Describe the bug

Plasma supports setting session environment variables by putting them into `$XDG_CONFIG_DIR/plasma-workspace/env` as bash scripts: https://userbase.kde.org/Session_Environment_Variables

Looking at [how it is implemented](https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/startplasma.cpp#L133), it seems like it's explicitly calling `/bin/sh {path-to-plasma-sourceenv.sh} {script files}`. 

However due to us running `wrapQtAppsHook` on all scripts in `/libexec` (since #181465), `plasma-sourceenv.sh` is now a binary file, and sourcing it with `/bin/sh` is now failing. This causes session variables not to run at all.

### Steps To Reproduce
1. Put some script into a `.sh` file in `$XDG_CONFIG_DIR/plasma-workspace/env/`. Say
```sh
export SHOULD_BE_ONE=1
```
2. Start a Plasma session.
3. Try to observe the environment variable: `echo $SHOULD_BE_ONE`.

### Expected behavior
It should be exported.

### Notify maintainers

@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240531.805a384`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(nki): `""`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `not found`
```
(I'm using a flake)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Well this is fun. And we don't even have a way to skip individual targets in wrapQtAppsHook...

**Comment by natsukagami** [comment]
> And we don't even have a way to skip individual targets in wrapQtAppsHook...

Is this something we would want to have? 

I think the other way we can close this is to patch `startkde` so that it no longer runs the `.sh` through `/bin/sh`, but since `plasma-sourceenv.sh` seems to dump all environment variables to pass into the Plasma session I'm not sure keeping the script wrapped is a good idea.

**Comment by K900** [comment]
That's definitely easier, I'm just not entirely sure how correctly it'll work with weird shells... Though I guess /bin/sh is already assumed POSIX.

**Comment by K900** [comment]
@natsukagami are you interested in looking into this further? I probably won't have the spoons to write up a patch for the next few days at least.

**Comment by natsukagami** [comment]
Sure, I will have a look should I have some spare time ^^
