### ISSUE TITLE
gnome-clocks: 'playbin' element not found

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#316781]
### Describe the bug
Gnome clocks fails to play alarm. Emits following error:
`
(org.gnome.clocks:7621): GStreamer-Play-ERROR **: 05:20:00.109: GstPlay: 'playbin' element not found, please check your setup
Trace/breakpoint trap (core dumped)
`

### Steps To Reproduce
1. ```nix shell nixpkgs#gnome.gnome-clocks```
2. `gnome-clocks`
3. set an alarm for 1 min later and wait.
4. observe the crash

### Additional context
I use Hyprland not gnome. If it is expected for clocks to not work in other desktop environments, I am sorry for the noise.

### Notify maintainers

@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.2, NixOS, 24.11 (Vicuña), 24.11.20240527.9ca3f64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/b2xy0gk6sd3fc8zamarfzach5f3wpkvi-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Thanks for reporting. Sounds like we forgot to add GStreamer to buildInputs
in the previous bump (
https://gitlab.gnome.org/GNOME/gnome-clocks/-/merge_requests/253 in GNOME
45). It works on GNOME Shell because it leaks GStreamer into environment,
making this issue.

The sound theme can be removed.

**Comment by JohnRTitor** [comment]
Please test #324495
