### ISSUE TITLE
Package request: pywal16

### ISSUE THREAD

**Issue by vavakado** [NixOS/nixpkgs#316746]
**Project description**
Fork of now deprecated dylanaraps/pywal that adds support for generating 16 colors
**Metadata**

* homepage URL: https://github.com/eylles/pywal16
* source URL: https://github.com/eylles/pywal16
* license: mit
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
You can also try [stylix](https://github.com/danth/stylix) (declarative) or [wallust](https://codeberg.org/explosion-mental/wallust) (imperative) if you haven't already

**Comment by Moraxyc** [comment]
@vavakado please test #316805
