### ISSUE TITLE
google-cloud-sdk can't install on macOS

### ISSUE THREAD

**Issue by lufia** [NixOS/nixpkgs#31679]
## Issue description
Installation for *google-cloud-sdk-177.0.0* fails with **assertion failed at xx/pkgs/os-specific/linux/systemd/default.nix:9:1**

I've used this sdk version 161.0.0 until today.

```
$ nix-env -i google-cloud-sdk --show-trace
installing ‘google-cloud-sdk-177.0.0’
error: while evaluating the attribute ‘installPhase’ of the derivation ‘google-cloud-sdk-177.0.0’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating ‘makeSearchPath’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/strings.nix:84:28, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/tools/admin/google-cloud-sdk/default.nix:6:16:
while evaluating anonymous function at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/strings.nix:85:32, called from undefined position:
while evaluating the attribute ‘postPatch’ of the derivation ‘google-compute-engine-20170914’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating the attribute ‘__sandboxProfile’ of the derivation ‘python2.7-python-systemd-234’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:98:11:
while evaluating ‘unique’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/lists.nix:455:12, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:127:75:
while evaluating ‘concatMap’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/lists.nix:102:18, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:81:13:
while evaluating anonymous function at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:81:28, called from undefined position:
while evaluating ‘getOutput’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/attrsets.nix:450:23, called from undefined position:
while evaluating anonymous function at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:63:15, called from undefined position:
while evaluating the attribute ‘systemd’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/top-level/all-packages.nix:13030:3:
while evaluating ‘callPackageWith’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/customisation.nix:113:35, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/top-level/all-packages.nix:13030:13:
while evaluating ‘makeOverridable’ at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/customisation.nix:72:24, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/customisation.nix:117:8:
while evaluating anonymous function at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/os-specific/linux/systemd/default.nix:1:1, called from /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/lib/customisation.nix:74:12:
assertion failed at /nix/store/qmv6v2l87mmzsdcvnqqwi3lys821gchm-nixpkgs-18.03pre120393.eac38d0b1e/nixpkgs/pkgs/os-specific/linux/systemd/default.nix:9:1
```

### Steps to reproduce

1. `nix-channel --update`
2. `nix-env -i google-cloud-sdk --show-trace`

## Technical details

System: macOS 10.13.1
Nix version: 1.11.15
Nixpkgs version: 18.03pre116369.14cbeaa892
Sandboxing enabled: false

**Comment by ilya-kolpakov** [comment]
For some reason `google-cloud-sdk` pulls `google-compute-engine` which is a Python package for (Linux) hosts deployed on GCE (https:://github.com/GoogleCloudPlatform/compute-image-packages).

It is definitely a mistake side `google-cloud-sdk` is purely a client library.

**Comment by abbradar** [comment]
That was because some SDK commands when ran on a guest tried (and failed) to import compute-engine libraries - I don't remember which ones exactly though. Maybe we should make it a conditional dependency for Linux? 
-- 
Nikolay.

**Comment by ilya-kolpakov** [comment]
What do you think about 
1) making it optional and off by default
2) installing it with the google-compute-engine dependency when building a GCE image

I think this is the best solution.

**Comment by abbradar** [comment]
Yeah, sounds good, all guests are expected to use that profile anyway.
-- 
Nikolay.

**Comment by ilya-kolpakov** [comment]
Is there a specific profile for gce images in nixpkgs? I could not find one in [nixos/modules/profiles](https://github.com/NixOS/nixpkgs/tree/3855b7977c3f987d6c09bc809e33073d64956f72/nixos/modules/profiles)

We need to somehow make the gce-enabled package default on GCE images (e.g. by creating an overlay and enabling it in GCE config). Installing it is not enough. All the dependent packages would pull the default version from `nixpkgs` and use it instead.

**Comment by abbradar** [comment]
@ilya-kolpakov [nixos/modules/virtualisation/google-compute-config.nix](https://github.com/NixOS/nixpkgs/blob/3855b7977c3f987d6c09bc809e33073d64956f72/nixos/modules/virtualisation/google-compute-config.nix) - it's placed wrongly. I can't check my Google instance right now but I think that file was imported into my configuration when I did rebuilds from the guest.

**Comment by ilya-kolpakov** [comment]
@abbradar Sent you an email. I think it is made unnecessarily complicated. Basically one needs to pass the right config to [nixos/lib/make-disk-image.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-disk-image.nix) and the result is the gce image. 

@lufia This won't be fixed immediately in the master branch. You can build `google-cloud-sdk` without `google-compute-engine`, I checked. I can make an temporary overlay (repo) containing the fixed package from which you can build if need be.

**Comment by ilya-kolpakov** [comment]
Or maybe @abbradar has write permissions? If we agree on disabling that dependency by default we can fix it very quickly.

**Comment by lufia** [comment]
@ilya-kolpakov thank you for your fix.

**Comment by abbradar** [comment]
Uhhh, GitHub didn't get my email here for some reason, so going to repost it:

> Yeah, given that I was the one who introduced that dependency by default in first place I feel we can just push an update which disables it by default and enables in GCE guest configuration.
> 
> I'm yet again very time-constrained till the end of the week but I'll try to prepare something soon.

@ilya-kolpakov Did you get my email or is there a problem too? It's strange because GitHub usually has no problem with using email to post.
