### ISSUE TITLE
Caching for inadyn service not working

### ISSUE THREAD

**Issue by kpine** [NixOS/nixpkgs#316756]
### Describe the bug

inadyn enabled via `services.inadyn` doesn't cache the discovered IP address. Therefore every time the service runs it forces an update with the DDNS provider.

### Steps To Reproduce

Enable inadyn service, e.g.:

```nix
{ config, lib, pkgs, ... }:

{
  services.inadyn = {
    enable = true;
    interval = "*:0/5";
    settings.provider."default@myprovider".include = ../myprovider.secret;
  };
}
```

Review the service logs and observe that it forces an update with the DDNS provider every time it runs, even when the IP address is the same.

Notice the `/var/cache/inadyn` cache directory is empty. 

### Expected behavior

With the above config there should be a file `default@myprovider-<hostname>.cache` created after the first run with the IP address as contents. When the service runs again at the specified interval and the IP address is the same, it should not update the DDNS provider.

### Screenshots
N/A

### Additional context

The relevant service definition is:

https://github.com/NixOS/nixpkgs/blob/778a1f2c47fe5a43e43264d23efc7118553aec5f/nixos/modules/services/networking/inadyn.nix#L203-L207

According to [systemd docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#%24RUNTIME_DIRECTORY) the `$CACHE_DIRECTORY` env var is the absolute path defined by `CacheDirectory=`, so it is `/var/cache/inadyn` not `/var/cache`. Therefore the command line is setting inadyn's cache directory configuration to `/var/cache/inadyn/inadyn`, which doesn't exist, and it silently ignores the missing directory. `ExecStart` should then be:

```nix
          ExecStart = ''${lib.getExe pkgs.inadyn} -f ${configFile} --cache-dir ''${CACHE_DIRECTORY} -1 --foreground -l ${cfg.logLevel}'';
```

Manually overriding `ExecStart` is working for me.

```nix
{ config, lib, pkgs, ... }:

let
  cfg = config.services.inadyn;
in
{
  services.inadyn = {
    enable = true;
    interval = "*:0/5";
    configFile = ../cloudflare.cfg;
    #settings.provider."default@myprovider".include = ../myprovider.secret;
  };

  systemd.services.inadyn.serviceConfig = {
    ExecStart = lib.mkForce ''${lib.getExe pkgs.inadyn} -f ${cfg.configFile} --cache-dir ''${CACHE_DIRECTORY} -1 --foreground -l ${cfg.logLevel}'';
  };
}
```
### Notify maintainers

@lunik1 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.81, NixOS, 24.05 (Uakari), 24.05.675.805a384895c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by flokli** [comment]
@kpine thanks for the investigation, this sounds right to me! Would you mind opening a PR doing the proposed change, and link it from here? Happy to take a look :+1:

**Comment by lunik1** [comment]
Thanks for the report. I won't be able to make a PR for a couple of days so it would be great if @kpine could. I think this should also be backported to 24.05.
