### ISSUE TITLE
`ratbagctl` (from `libratbag`) fails to run

### ISSUE THREAD

**Issue by GsakuL** [NixOS/nixpkgs#316701]
### Describe the bug
it's impossible to use `ratbagctl` due to an import error:
```console
[user@system:~]$ ratbagctl info
Traceback (most recent call last):
  File "/nix/store/4x1mm4cm6a891yyl1a9ky08fxril160h-libratbag-0.17/bin/ratbagctl", line 36, in <module>
    from gi.repository import Gio, GLib, GObject
  File "/nix/store/czg030czd0sc7vmwjf71afhd9zskf5n2-python3-3.11.9-env/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gio, introspection typelib not found

[user@system:~]$
```

### Steps To Reproduce
1. set `services.ratbagd.enable = true;`
2. try to run eg `ratbagctl info` 

### Expected behavior
ratbagctl "shows something". (i.e. current mouse hardware/mapping etc.)

### Screenshots
(no gui, cli only)

### Additional context
I (may) need `ratbagctl` because it has infos/options that are not yet fully implemented in `piper`

### Notify maintainers
@mvnetbiz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/316717
