### ISSUE TITLE
startplasmacompositor broken on Wayland session, calls start_kdeinit_wrapper from wrong package

### ISSUE THREAD

**Issue by Pneumaticat** [NixOS/nixpkgs#31686]
## Issue description

startplasmacompositor starts startplasma in `plasma-workspace`, which tries to start `start_kdeinit_wrapper` but fails.

https://github.com/NixOS/nixpkgs/blob/b8abd97c3b19f172c21c9d4bb0a3357c89f3b587/pkgs/desktops/plasma-5/plasma-workspace/plasma-workspace.patch#L533 suggests it should run `start_kdeinit_wrapper` from the `kinit` package, but no. On my computer, I see `LD_BIND_NOW=true /nix/store/y70hv6w5p7yrm18782qyrfrxvx37pim0-plasma-workspace-5.11.3/lib/libexec/kf5/start_kdeinit_wrapper --kded +kcminit_startup`, which is a path that does not exist. I'm quite confused as to why it picks the wrong directory here.

### Steps to reproduce

Run startplasmacompositor on latest Nixpkgs.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.0-rc3, NixOS, 18.03.git.c7dd4db (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

(Custom nixpkgs based off of aeff3080d02ce6ac2b2ad0b0029c1388eab2d8c7 -- it doesn't touch Plasma packages)

**Comment by gnidorah** [comment]
Broken for me too.
> Run startplasmacompositor on latest Nixpkgs.

To note here that it worked in the past at the time https://github.com/NixOS/nixpkgs/issues/30649 was filled

/cc @ttuegel

**Comment by Pneumaticat** [comment]
After some inspection, I think this occurs because the plasma-workspace patch hasn't been updated to plasma 5.11.3 (or rather 5.11.4 now), so the `startplasma.cmake` file fails to patch. Thus, it ends up calling start_kdeinit_wrapper from the wrong directory. This can probably be fixed by regenerating the patch by [following the instructions](https://github.com/NixOS/nixpkgs/blob/b8abd97c3b19f172c21c9d4bb0a3357c89f3b587/pkgs/desktops/plasma-5/plasma-workspace/default.nix#L56-L66).
