### ISSUE TITLE
Pantheon's global QT_QPA_PLATFORMTHEME affects other environments, breaks Lomiri

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#316991]
### Describe the bug

https://github.com/NixOS/nixpkgs/blob/cb8b6a5d00464c268db7452e698ea6094649e9bd/nixos/modules/services/x11/desktop-managers/pantheon.nix#L272-L275

If both Lomiri and Pantheon are enabled, then this globally-set envvar breaks Lomiri:

```
2024-06-02T22:54:35.179158+02:00 Carlos lomiri[597145]: /run/current-system/sw/bin/Xwayland
2024-06-02T22:54:35.319812+02:00 Carlos lomiri[597145]: [2024-06-02:22:54:35.318] Using mirserver qt platform
2024-06-02T22:54:35.319846+02:00 Carlos lomiri[597145]: [2024-06-02:22:54:35.319] Not using nested server, using null mir cursor
2024-06-02T22:54:35.321341+02:00 Carlos lomiri[597145]: [2024-06-02:22:54:35.321] qtmir.screens: ScreensModel[ScreensModel(0x246c3a0)]::ScreensModel()
2024-06-02T22:54:35.389632+02:00 Carlos .lomiri-wrapped[597145]: cannot open display: 
2024-06-02T22:54:35.414733+02:00 Carlos systemd[591136]: lomiri.service: Main process exited, code=exited, status=1/FAILURE
```

### Steps To Reproduce
1. `services.xserver.desktopManager.pantheon.enable = true`
2. `services.desktopManager.lomiri.enable = true`
3. Sort out the lightdm greeter preference
4. Try to launch into Lomiri
5. Get booted back to the DM

### Expected behavior
Both DEs should be able to co-exist without workarounds.

### Screenshots
n/a

### Additional context

This can be worked around by setting this envvar to an empty value.
```nix
environment.variables.QT_QPA_PLATFORMTHEME = "";
```
...but then this breaks how Qt apps are displayed in Pantheon.

Maybe there is a way to apply this preference in a session-specific manner?

Or Qt's [list of GTK environments](https://invent.kde.org/qt/qt/qtbase/-/blob/c6feed7e1d8b8ed991a81878c78bb361f038eaf6/src/gui/platform/unix/qgenericunixthemes.cpp#L1491-1496) could be patched to acknowledge Pantheon?

Or Pantheon could be patched to indicate `Pantheon:GNOME`, which should then be properly picked up by Qt? But maybe not considering GNOME as a generalisation of Pantheon is done by them on purpose.

### Notify maintainers

@NixOS/pantheon 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.675.805a384895c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(bt1cn): `"unstable"`
 - channels(root): `"nixos-24.05, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
> ...but then this breaks how Qt apps are displayed in Pantheon.

Ugh, we can call it "leave the decision to user" 🙃 

<sub>*P.s.: I mentioned the Qt status quo in https://github.com/elementary/default-settings/pull/295, and it looks like they really only want to support the [`xdgdesktopportal`](https://invent.kde.org/qt/qt/qtbase/-/tree/6.6/src/plugins/platformthemes/xdgdesktopportal) theme (well, there is the elementary-files file chooser), though I guess doing that globally can lead to [another bad story](https://github.com/elementary/default-settings/pull/215)* 🙃  </sub>
