### ISSUE TITLE
Package request: openscap

### ISSUE THREAD

**Issue by EyesofBucket** [NixOS/nixpkgs#316981]
**Project description**

The oscap program is a command line tool that allows users to load, scan, validate, edit, and export SCAP documents.

**Metadata**

* homepage URL: http://www.open-scap.org
* source URL: https://github.com/OpenSCAP/openscap
* license: lgpl-2.1
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RoGreat** [comment]
Related to #81418.

**Comment by pluiedev** [comment]
WIP attempt — Perl and Python bindings are broken and a lot of the deps here are probably not necessary, pending investigation https://gist.github.com/pluiedev/47a5a726141569eebec976a4c9eb7e26

**Comment by Tochiaha** [comment]
#326745

**Comment by Tochiaha** [comment]
https://search.nixos.org/packages?channel=unstable&show=openscap&from=0&size=50&sort=relevance&type=packages&query=openscap
