### ISSUE TITLE
grafana broken on `{aarch64, x864_64}-darwin`

### ISSUE THREAD

**Issue by shivaraj-bh** [NixOS/nixpkgs#316954]
### Describe the bug
I understand that is [broken due to `util-linux` workaround](https://github.com/NixOS/nixpkgs/blob/dd4f5b7133c27c628cea26aee9dbe8342612620c/pkgs/servers/monitoring/grafana/default.nix#L159-L161). Creating this issue to see if we can find a solution for `darwin` too.

### Notify maintainers
@offlinehacker @fpletz @WilliButz @globin @Ma27 @Frostman 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
First of all, as a workaround you should be able to use Grafana from 24.05 where we decided to not ship v11 yet, so it's still buildable for Darwin.

> Creating this issue to see if we can find a solution for darwin too.

I think it's super-questionable in the first place that `nx` just fails when being executed in a CI environment w/o a proper tty.

I won't have the time for another side-quest here, but if you have time for it, I'd recommend to try fixing `nx` (https://github.com/nrwl/nx/issues/22445) and make sure it gets added into Grafana (though we may be able to sneak a newer `nx` into the build in one way or another when there's a fix accepted upstream).
