### ISSUE TITLE
`pnpm.configHook` / `npmHooks.npm{Install,Build}Hook`: Support `pnpm-workspace.yaml` projects

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#316908]
Per the issue mentioned here:

https://github.com/NixOS/nixpkgs/pull/290715#issuecomment-2144543728

And [the docs](https://nixos.org/manual/nixpkgs/unstable/#javascript-pnpm-sourceRoot) (link will be correct once https://github.com/NixOS/nixpkgs/pull/290715 reaches the channels).

We need to think about a way to support projects that use `pnpm-workspace.yaml`.

cc @Scrumplex .

**Comment by nathanscully** [comment]
I did a test for workspaces using the exiting build and linked it in #290715 the other week: https://github.com/NixOS/nixpkgs/pull/290715#issuecomment-2118801278. It's probably non-ideal as its using the inbuilt pnpm filter spread syntax (` pnpm run --filter server... build`) but it does work. 
Not sure if we can get away just documenting that for now rather than having to change the tooling to much to get the first PR in.

**Comment by doronbehar** [comment]
For `bash-language-server`, I tried in the `buildPhase`:

```
pnpm --filter server run compile
pnpm run --filter server compile
```

And all of them gave me:

```
No projects matched the filters in "/build/source"
```

Which is peculiar... Running without a `--filter server` gave me the same errors as using `npmHooks.npmBuildHook` gave me...

**Comment by nathanscully** [comment]
This seems to work for me. Can you try it? Might need to move around the out folders but it builds. 

```
{
  lib,
  stdenv,
  fetchFromGitHub,
  pnpm_9,
  nodejs,
  npmHooks,
  writeScriptBin,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "bash-language-server";
  version = "5.3.3";

  src = fetchFromGitHub {
    owner = "bash-lsp";
    repo = "bash-language-server";
    rev = "server-${finalAttrs.version}";
    hash = "sha256-4+imeVjosEspFhWzjtUp2IZx7aZIx56g8M03V3dEGVs=";
  };

  nativeBuildInputs = [
    nodejs
    pnpm_9.configHook
  ];
  pnpmDeps = pnpm_9.fetchDeps {
    inherit (finalAttrs) pname version src;
    hash = "sha256-W7BrUh0tGoG5vTuR3hXDbUTJFDiKET+QvIvCwewfZ2I=";
  };
  preBuild = ''
    rm -r vscode-client
    substituteInPlace tsconfig.json \
      --replace '{ "path": "./vscode-client" },' ""
  '';
  postBuild = ''
    pnpm run compile
    pnpm --offline deploy --frozen-lockfile  --ignore-script  --filter=bash-language-server server-deploy
  '';
  installPhase = ''
    cp -r server-deploy $out
  '';
})
```


```
$ node result/out/cli.js
Usage:
  bash-language-server start             Start listening on stdin/stdout
  bash-language-server -h, --help        Display this help and exit
  bash-language-server -v, --version     Print the version and exit

Environment variables:
  BASH_IDE_LOG_LEVEL                     Set the log level (default: info)

Further documentation: https://github.com/bash-lsp/bash-language-server
```

**Comment by doronbehar** [comment]
Wow Thanks @nathanscully ! The main insight you bring, is that the argument `--filter` gets, is not the name of the directory of the subproject, but the `name` (defined in the folder's `package.json`) - which wasn't clear for me when reading pnpm's docs (https://pnpm.io/filtering ). The PR for `bash-language-server` is ready now at https://github.com/NixOS/nixpkgs/pull/317954 .

I conclude that we need a `pnpm.installHook` that will take care of such details (related to https://github.com/NixOS/nixpkgs/issues/317927 ).

**Comment by nathanscully** [comment]
No worries. I ran into the same issue earlier when I picked up using pnpm. Glad I could help.

**Comment by GetPsyched** [comment]
Pinging people subscribed to this issue about #323493 being merged. I myself was waiting for pnpm workspaces support and had no idea that it was already added a month ago.

Unsure if this issue includes additions other than workspaces support, but if not, should probably be closed.

**Comment by doronbehar** [comment]
Thanks @GetPsyched for writing here, indeed I forgot to close this!
