### ISSUE TITLE
Path in android-udev-rules

### ISSUE THREAD

**Issue by lebel** [NixOS/nixpkgs#31704]
## Issue description

Should the path of $out/**lib**/udev/rules.d/51-android.rules be $out/**etc**/udev/rules.d/51-android.rules ?
Currently, the file doesn't appear in my /etc/udev/rules.d and is nowhere to be found on the system to be used by udev, it seems.

### Steps to reproduce

Install the package in /etc/nixos/configuration.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2055.c19136c4c9 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2055.c19136c4c9"`
 - channels(lebeld): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by lebel** [comment]
See related PR:   https://github.com/NixOS/nixpkgs/pull/31705

**Comment by Mic92** [comment]
solution see https://github.com/NixOS/nixpkgs/pull/31705#issuecomment-344660035
