### ISSUE TITLE
nss lookups on many non-NixOS distros broken after glibc upgrade (whoami: "cannot find name for user ID", openssh (ssh): "no user exists for uid", emacs:  "user has no home directory")

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#31700]
## Issue description

E.g. Arch Linux has this in `/etc/nsswitch.conf`:
````
passwd: compat mymachines systemd
````

... but `libnss_compat` is no longer included with glibc (it's apparently at https://github.com/thkukuk/libnss_compat instead).

### Steps to reproduce

````
$ nix-build -A coreutils
$ ./result/bin/whoami
./result/bin/whoami: cannot find name for user ID 1000
````
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.53-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(tmtynkky): `"nixpkgs-18.03pre120393.eac38d0b1e"`
 - nixpkgs: `/home/tmtynkky/.nix-defexpr/channels/nixpkgs`

**Comment by vcunat** [comment]
Hmm, it's no longer included, but perhaps we might combine the builds of glibc and libnss_compat into the same set of outputs &ndash; then things might work as before.

**Comment by dezgeg** [comment]
Yup.

Though, now you somehow need to run autoconf on that during bootstrapping...

**Comment by dudebout** [comment]
One manifestation of this issue is emacs failing to load the user's configuration with the error message:
```
Error (initialization): User USERNAME has no home directory
```

(posting this here in case people try to search for this error message)

**Comment by greyson** [comment]
Is there a workaround (trying to get nixops deployment working)?

**Comment by dudebout** [comment]
If you are not using the compatibility mode offered by `nsswitch.conf(5)`, you can edit `/etc/nsswitch.conf` and replace `compat` by `files`.

**Comment by orivej** [comment]
035b5892457d7d198090dc6a68cac2b99d2fec52 should fix this when it reaches master. See https://bugs.archlinux.org/task/54592.

**Comment by asymmetric** [comment]
@orivej What's the easiest way to check when that happens?

**Comment by orivej** [comment]
This issue will be closed then :)
(Now we are waiting for the jobs queued at https://hydra.nixos.org/eval/1412641 to finish in order to merge.)
