### ISSUE TITLE
Collision between gotools and coreutils

### ISSUE THREAD

**Issue by mikefaille** [NixOS/nixpkgs#31708]
## Issue description
`link` binary is on collision when we espect having `gotools` and `coreutil` in same env.  

Here is the error :

```
collision between `/nix/store/vp8y0rh8rq7vikbbrpf28jfym79xq9z8-coreutils-8.28/bin/link' and `/nix/store/j533xdkapn8bmp2j3sd94sqpkrhwz0gg-gotools-20160519-9ae4729-bin/bin/link'
created 12464 symlinks in user environment
```

### Steps to reproduce

Just configure `gotools` and `coreutils` in the same env.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.10, NixOS, 17.09.1922.21bb269a32 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(michael): `"nixos-17.09-17.09.2055.c19136c4c9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by copumpkin** [comment]
What would you propose doing to improve this? If they both contain the same binary we can change the precedence of one of them but that just hides the other. This is one of those cases where `nix-shell` makes a lot more sense to me.

**Comment by mikefaille** [comment]
@copumpkin 
I dont retrieve `link` in official gotools documentation : 
https://godoc.org/golang.org/x/tools

in debian's gotools pkg : 
https://packages.debian.org/sid/amd64/golang-golang-x-tools/filelist

In centos gotools pkg (nor in fedora 26 one too) : 
https://centos.pkgs.org/7/epel-x86_64/golang-googlecode-tools-devel-0-1.0.hgd32b5854c941.el7.noarch.rpm.html

Then, I asking myself, do we really need `link` from gotools ? I will search little bit deeper.

**Comment by mikefaille** [comment]
@copumpkin  Got it. 
`link` from gotools is already provided from `go tool link`. I really think that `go` toolchain won't use `link` directly. (base on centos/fedora/debian gotools packaging and how we can use `link` from `go tool` command)

**Comment by FliegendeWurst** [comment]
This was fixed at some point
