### ISSUE TITLE
gtk2-x11 ignores system-wide configuration

### ISSUE THREAD

**Issue by ChengCat** [NixOS/nixpkgs#31702]
## Issue description
As indicated by a strace, gtk2-x11 doesn't look in `/etc/gtk-2.0/gtkrc` for a system-wide configuration, but look in `${pkgs.gtk2-x11}/etc/gtk-2.0/gtkrc` instead.

I expect the system-wide configuration file `/etc/gtk-2.0/gtkrc` to work. GTK+ 2 should accept `<SYSCONFDIR>/gtk-2.0/gtkrc` as described in https://developer.gnome.org/gtk2/stable/gtk2-Resource-Files.html, and I expect `<SYSCONFDIR>` to be `/etc`.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.60, NixOS, 17.09.1997.1a8a95e879 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(cheng): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/221019 should fix this
