### ISSUE TITLE
Package request: auto-editor

### ISSUE THREAD

**Issue by johannesCmayer** [NixOS/nixpkgs#317015]
Auto-Editor is a command line application for automatically editing video and audio by analyzing a variety of methods, most notably audio loudness.

**Metadata**

* homepage URL: https://auto-editor.com/
* source URL: https://github.com/WyattBlue/auto-editor
* license: The Unlicense
* platforms: linux (I'd guess also darwin and windows as it's all python)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
Latest `auto-editor` requires `pyav==12.1.0`, so another package update is required (latest we have is 11.0.0).
Also, it pulls in a dep for a statically compiled FFmpeg, `ae-ffmpeg`.

Project TOML can be found [here](https://github.com/WyattBlue/auto-editor/blob/master/pyproject.toml#L11-L14)
