### ISSUE TITLE
Build failure: radicale

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#317147]
### Steps To Reproduce

1. build *radicale*

### Build log

```
building '/nix/store/075v927xjvm6xkwmv2ymrwf65m8spnsa-source.drv'...
error: hash mismatch in fixed-output derivation '/nix/store/075v927xjvm6xkwmv2ymrwf65m8spnsa-source.drv':
         specified: sha256-OUwznn71xl8oWkw90fT1NYYZOuD83k+B5zLhygp1VQQ=
            got:    sha256-t2722mLnbxDAG1xBCfz+VBnKr0BDnYmabb2q8IXC+eE=
error: 1 dependencies of derivation '/nix/store/76279y0g3m6s601gwiq9ck2n4vsglf96-radicale-3.2.1.drv' failed to build
```

```
$ nix log /nix/store/075v927xjvm6xkwmv2ymrwf65m8spnsa-source.drv
warning: unknown experimental feature 'configurable-impure-env'
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/075v927xjvm6xkwmv2ymrwf65m8spnsa-source.drv^*'
got build log for '/nix/store/075v927xjvm6xkwmv2ymrwf65m8spnsa-source.drv' from 'daemon'

trying https://github.com/Kozea/Radicale/archive/v3.2.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
^M100  148k  100  148k    0     0   748k      0 --:--:-- --:--:-- --:--:--  748k
unpacking source archive /build/v3.2.1.tar.gz
```

### Additional context

at quick glance I think they rereleased tarballs with more changes, files inside are from today

### Notify maintainers

@dotlambda @erictapen

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-xanmod1, NixOS, 24.11 (Vicuña), 24.11.20240529.1f1bda9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-lixpre20240530-ce82067`
 - nixpkgs: `/nix/store/kz3km8qja6jqbglisd3bq7f69r6zknj8-source`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by erictapen** [comment]
Yeah, looks like upstream changed the release afterwards. I didn't even know you can do that on GitHub.

https://github.com/NixOS/nixpkgs/pull/316952#issuecomment-2147207479

**Comment by dawidd6** [comment]
You can just delete the tag, create a new one with the same name and do a force push. Some projects do this, some don't.

**Comment by dotlambda** [comment]
Can someone revert https://github.com/NixOS/nixpkgs/pull/316952/commits/c234b47cc71ff528357f0d60d5153432fc4a1a2a for now?
