### ISSUE TITLE
Error while building Sage

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#31714]
## Issue description
The newly-fixed Sage package fails to build 😢. @timokau 
```
The following package(s) may have failed to build (not necessarily
during this run of 'make all'):

* package: xz-5.2.2
  log file: /nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/sage-root/logs/pkgs/xz-5.2.2.log
  build directory: /nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/var/tmp/sage/build/xz-5.2.2
```
Here's the log:
```
Found local metadata for xz-5.2.2
Using cached file /nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/sage-root/upstream/xz-5.2.2.tar.gz
xz-5.2.2
====================================================
Setting up build directory for xz-5.2.2
Finished extraction
No patch files found in ../patches
****************************************************
Host system:
Linux localhost 4.9.46 #1-NixOS SMP Wed Aug 30 08:24:43 UTC 2017 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=/nix/store/p9ikv82r4vyp51mlan01vrncg0fp3pmn-gfortran-6.4.0/bin/gcc
COLLECT_LTO_WRAPPER=/nix/store/p9ikv82r4vyp51mlan01vrncg0fp3pmn-gfortran-6.4.0/libexec/gcc/x86_64-unknown-linux-gnu/6.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: 
Thread model: posix
gcc version 6.4.0 (GCC) 
****************************************************
WARNING: spkg-install is not executable, making it executable
/nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/sage-root/build/bin/sage-spkg: ./spkg-install: /usr/bin/env: bad interpreter: No such file or directory

real    0m0.001s
user    0m0.000s
sys     0m0.000s
************************************************************************
Error installing package xz-5.2.2
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the log file
  /nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/sage-root/logs/pkgs/xz-5.2.2.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/var/tmp/sage/build/xz-5.2.2 and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/var/tmp/sage/build/xz-5.2.2' && '/nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/sage-root/sage' --sh)
When you are done debugging, you can type "exit" to leave the subshell.
************************************************************************
```

### Steps to reproduce
Build `sage` on rev `b8f7027360855faee9d72956092be2e030a12a5f`.

## Technical details
```
assignments/presentation > nix-shell -p nix-info --run "nix-info -m"
error: undefined variable ‘nix-info’ at (string):1:66
(use ‘--show-trace’ to show detailed location information)
```
However,
```
nix-env (Nix) 1.11.14
```
and I'm building from nixpkgs rev `b8f7027360855faee9d72956092be2e030a12a5f`.

**Comment by timokau** [comment]
The error suggests that you don't have `/usr/bin/env`, is that true?

**Comment by siddharthist** [comment]
@timokau No. I have sandboxing turned on, though.

**Comment by timokau** [comment]
Me too

I tried reproducing it, but `nix-build --option build-use-sandbox true ~/nix/sage-test -A sage` on the ref you specified is actually a noop (its already in my store). Do you know if its possible to force a rebuild?

**Comment by siddharthist** [comment]
Hmm, I don't know.

**Comment by timokau** [comment]
Can you gist the whole bild log? Especially the first part, where `patchShebangs` is executed.

**Comment by flokli** [comment]
@timokau For me, this fails at brial build due to pkgconfig not being available: https://gist.githubusercontent.com/flokli/7dda9a5d3372f1cfbbe56fe594c0db0d/raw/61cce7b27bad405205fa1f3b8b5eef7bb1c2118c/sage.build.log

**Comment by timokau** [comment]
This seems to be the same issue: The line where the failure happens is
```
[brial-0.8.7] checking pkg-config is at least version 0.9.0... ./configure: /nix/store/iyc1xdwsik5lw3j5s76vc94bvqdq4fcg-sage-8.0/bin/pkg-config: /usr/bin/env: bad interpreter: No such file or directory
```
I think this occurs when sage uses dependencies it built itself and which have `/usr/bin/env` shebang lines hard coded. Since `patchShebangs` is only run once before the build, those are not patched.

The weird thing is that it worked for me, even in a sandbox.

As for a fix, I will try to inject a `patchShebangs` after each spkg build. `bin/sage-spkg` seems to be a good candidate for that. I am currently testing if it still builds for me with that patch, if it does I will push it (for one of you to test).

**Comment by flokli** [comment]
@timokau Did your build finish?

**Comment by timokau** [comment]
No, not yet. I ran into some problems.
I'll let you know when it is.

**Comment by timokau** [comment]
I'm short on time lately and have not found the right place to inject the patch into the build process yet.
I'll certainly not work on this till monday, so it will take a bit more time.

**Comment by timokau** [comment]
Just a quick update: This won't be a priority for me for a little longer. It might get pushed into january. Sorry about that.

If anybody else wants to get their hands dirty I'm happy to help.

**Comment by siddharthist** [comment]
@timokau Thanks for your work so far 😄 Sage is a huge pain to build, I'm glad it's in better shape than it was a few months ago.

**Comment by timokau** [comment]
I updated to 8.1 and hopefully fixed the issue. I'm still not quite sure why it worked fine for me the whole time: I thought `nix-build --option build-use-sandbox true` was supposed to get rid of "well works for me" problems.

Anyways, could you test https://github.com/timokau/nixpkgs/tree/sage-fix-shebangs @siddharthist?

**Comment by siddharthist** [comment]
Yeah, even with sandboxing on, I get the following error: https://gist.github.com/siddharthist/9351b741f82652248e8dfb0cf4569fe3 

Weird 😞. Maybe there's something peculiar about how I'm building? Here's what I executed:
```bash
git remote add timokau https://github.com/timokau/nixpkgs
git fetch --all
git checkout timokau/sage-fix-shebangs
nix-build --option build-use-sandbox true -A sage . &> sage.log
```

**Comment by timokau** [comment]
Doing it exactly that way works on my system, seems like sandboxing is inconsistent.

That error should be resolved now (I think I introduced it by removing an old line I thought was redundant). Please pull and try again.

**Comment by siddharthist** [comment]
I get a different error now! 🎆 https://gist.github.com/siddharthist/ab4bcf08e472903ec5c024775bc01e71

For completeness, here's what I did:
```bash
git fetch --all && 
  git reset --hard timokau/sage-fix-shebangs && 
  nix-build --option build-use-sandbox true -A sage . &> sage.log
```

**Comment by timokau** [comment]
Apparently sage adds some boilerplate, including a shebang, to the `spkg-install` files at build-time. That should be patched now.

Third time's the charm.

**Comment by timokau** [comment]
Nevermind, I figured out how to reproduce the error myself (`--option` doesn't have any effect, I have to set `nix.useSandbox` gobally).

I've already fixed another issue (shebangs need to be patched immediately after extraction, not just after each package is built). I'll iterate until it works for me (and then hopefully for you, too).

**Comment by timokau** [comment]
It works!

The PR is here: https://github.com/NixOS/nixpkgs/pull/34291
And in case somebody can't wait for it to land in unstable, here's the commit cherry-picket on top of the latest unstable: https://github.com/timokau/nixpkgs/tree/sage-fix-shebangs-unstable

**Comment by timokau** [comment]
This can be closed.
