### ISSUE TITLE
k3s: using tailscale vpn option fails

### ISSUE THREAD

**Issue by rksm** [NixOS/nixpkgs#317223]
### Describe the bug

Setting up k3s with tailscale ([k3s docs](https://docs.k3s.io/networking/distributed-multicloud#integration-with-the-tailscale-vpn-provider-experimental))

via

```nix
services.k3s = {
  # ...
  extraFlags = "--vpn-auth=name=tailscale,joinKey=...";
};
```

Currently fails at two points:

1. With the setup above, starting k3s fails with

```
msg="tailscale up failed: : exec: \"tailscale\": executable file not found in $PATH"
```

This can be fixed with

```nix
systemd.services.k3s.path = [ pkgs.tailscale ];
```

2. Even after changing the path, the [flannel PostStartupCommand](https://github.com/k3s-io/k3s/blob/79ba10f5ec88a2458b44f67d009b4ee071918e4d/pkg/agent/flannel/setup.go#L43) fails with:

```
flannel exited: failed to register flannel network: failed to run command: tailscale set --accept-routes --advertise-routes=$SUBNET Err: exec: \"sh\": executable file not found in $PATH
```

I was first mistaken thinking it complaints about the tailscale bin again but it actually cannot find the `sh` bin (via this invocation [here](https://github.com/flannel-io/flannel/blob/b469eaea226f1a03383b5adaf0c6df5e49360f8f/pkg/backend/extension/extension.go#L84) ). E.g. adding `bash` to `systemd.services.k3s.path` does *not* help here. The only way I was able to fix it was to add the `bash` package to the [`k3sRuntimeDeps`](https://github.com/NixOS/nixpkgs/blob/8be0d8a1ed4f96d99b09aa616e2afd47acc3da89/pkgs/applications/networking/cluster/k3s/builder.nix#L266). Afterwards everything worked as expected.

### Steps To Reproduce
Setting up k3s like

```
services.k3s = {
  enable = true;
  extraFlags = "--vpn-auth=name=tailscale,joinKey=...";
};
```

### Expected behavior
k3s starts successfully and flannel can setup the tailscale network (check `journalctl -u k3s`).

### Notify maintainers

@euank @yajo @Mic92

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240530.6132b0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/l4wskml8vcs49mg6w9la715cx10sviwh-source`
```

**Comment by yajo** [comment]
> This can be fixed with
> 
> ```nix
> systemd.services.k3s.path = [ pkgs.tailscale ];
> ```

I think this is more or less expected, right?

To fix it, we could have a new option in the k3s module to enable tailscale, but I'm not sure if it's worth it.



> The only way I was able to fix it was to add the `bash` package to the [`k3sRuntimeDeps`](https://github.com/NixOS/nixpkgs/blob/8be0d8a1ed4f96d99b09aa616e2afd47acc3da89/pkgs/applications/networking/cluster/k3s/builder.nix#L266). Afterwards everything worked as expected.

In this case I think we can just add `bash` to that list by default.

WDYT @eunak @Mic92 ?

**Comment by euank** [comment]
Thanks for reporting the issue and workarounds you found!

Adding bash as a runtime dependency of k3s makes sense to me, happy to review/approve a PR for that!

I think the "tailscale in the k8s service path" being the user's responsibility is fine, and if we ever add a specific module option for tailscale, that could add it automatically.

I'd rather not pull in the tailscale binary by default for everyone if we can avoid it, and having the user add it to the service path themselves seems like a decent compromise there.
