### ISSUE TITLE
Package request: debase

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixpkgs#317240]
**Project description**

debase is a TUI for drag-and-drop manipulation of Git commits:

> ![screenshot](https://raw.githubusercontent.com/toasterllc/debase/8d45caff9e716172224903eb5717b13638220f18/readme-copy.gif)

**Metadata**

* homepage URL: https://toaster.llc/debase
* source URL: https://github.com/toasterllc/debase
* license: proprietary
* platforms: Linux, macOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jeremyschlatter** [comment]
I've been playing around with packaging it.

Here's what I have so far:

```nix

{ darwin
, fetchFromGitHub
, iconv
, lib
, libgit2
, ncurses
, stdenv
, cmake
, python3
, zlib
, useNixDeps ? true
}:
stdenv.mkDerivation rec {
  pname = "debase";
  version = "2";

  src = (fetchFromGitHub {
    owner = "toasterllc";
    repo = "debase";
    rev = "v${version}";
    hash = "sha256-b1JbIwiSJxqpKiIexEZc2X0TDHxtFPcw95qCUxjFFUc=";
    fetchSubmodules = true;
    leaveDotGit = true;
  }).overrideAttrs {
    GIT_CONFIG_COUNT = 1;
    GIT_CONFIG_KEY_0 = "url.https://github.com/.insteadOf";
    GIT_CONFIG_VALUE_0 = "git@github.com:";
  };

  patches = [
    ./debase-no-git.patch
    ./debase-no-xcrun.patch
  ] ++ lib.optionals useNixDeps [
    ./debase-no-vendored-deps.patch
  ];

  buildInputs = (if useNixDeps then [
    libgit2
    ncurses
  ] else [
    iconv
    zlib
  ]) ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.Foundation
  ];

  nativeBuildInputs = lib.optionals (!useNixDeps) [
    cmake
    python3
  ];

  dontUseCmakeConfigure = true;

  installPhase = ''
    mkdir -p $out/bin
    cp build-${if stdenv.isDarwin then "mac" else "linux"}/release/debase $out/bin
  '';

  enableParallelBuilding = true;

  makeFlags = [
    "ARCHS=${
    if stdenv.isx86_64 then
      "x86_64"
    else if stdenv.isAarch64 then
      "arm64"
    else
      abort "unsupported system: ${stdenv.system}"
    }"
  ];
};

```
[debase-no-vendored-deps.patch](https://github.com/user-attachments/files/15597974/debase-no-vendored-deps.patch)
[debase-no-xcrun.patch](https://github.com/user-attachments/files/15597976/debase-no-xcrun.patch)
[debase-no-git.patch](https://github.com/user-attachments/files/15597980/debase-no-git.patch)

This packages debase two different ways: one with debase's vendored `ncurses` and `libgit2`, and one with nix's `ncurses` and `libgit2`. The parameter `useNixDeps` switches between them.

Both versions are building and running for me on my aarch64-darwin laptop.

Using the nix deps seems better, but debase has made a few patches to its copy of ncurses that are necessary to support its drag-and-drop features. I'm looking into that now to see if there is a good way to use nix's ncurses while still supporting those features. Using nix's libgit2 just seems to be a straightforward win, though.

**Comment by jeremyschlatter** [comment]
I've looked at the patches that debase made to ncurses, and they are significant enough that it seems worthwhile to use debases's vendored copy of ncurses instead of using nix's ncurses.

So here is a derivation that builds debase using debase's vendored ncurses and nix's libgit2:

```nix
{ darwin
, fetchFromGitHub
, lib
, libgit2
, stdenv
}:
stdenv.mkDerivation rec {
  pname = "debase";
  version = "2";

  src = (fetchFromGitHub {
    owner = "toasterllc";
    repo = "debase";
    rev = "v${version}";
    hash = "sha256-b1JbIwiSJxqpKiIexEZc2X0TDHxtFPcw95qCUxjFFUc=";
    fetchSubmodules = true;
    leaveDotGit = true;
  }).overrideAttrs {
    GIT_CONFIG_COUNT = 1;
    GIT_CONFIG_KEY_0 = "url.https://github.com/.insteadOf";
    GIT_CONFIG_VALUE_0 = "git@github.com:";
  };

  patches = [
    ./debase-no-git.patch
    ./debase-no-xcrun.patch
    ./debase-no-vendored-libgit2.patch
  ];

  buildInputs = [
    libgit2
  ] ++ lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.Foundation
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp build-${if stdenv.isDarwin then "mac" else "linux"}/release/debase $out/bin
  '';

  enableParallelBuilding = true;

  makeFlags = [
    "ARCHS=${
    if stdenv.isx86_64 then
      "x86_64"
    else if stdenv.isAarch64 then
      "arm64"
    else
      abort "unsupported system: ${stdenv.system}"
    }"
  ];
};
```

[debase-no-xcrun.patch](https://github.com/user-attachments/files/15597976/debase-no-xcrun.patch)
[debase-no-git.patch](https://github.com/user-attachments/files/15597980/debase-no-git.patch)
[debase-no-vendored-libgit2.patch](https://github.com/user-attachments/files/15598801/debase-no-vendored-libgit2.patch)

I tested it on my aarch64-darwin laptop and it builds and runs and supports drag and drop.

**Comment by eclairevoyant** [comment]
Due to the unresolved issue of the bundled http-parser (possibly security risk) and the fact that it's still unlicensed (hence redistribution or even patching may not be appropriate), I'd hold off on packaging this.

**Comment by jeremyschlatter** [comment]
The bundled http-parser issue is easy to resolve. It is part of libgit2, but as demonstrated in the packages I provided above and in the linked (closed) PR, you can use nixpkgs' libgit2 instead, which is up to date and no longer uses http-parser.

I agree the lack of license is still an issue, though.

**Comment by eclairevoyant** [comment]
The linked PR doesn't build on linux, but fair enough, the license is really what gives me pause.

**Comment by jeremyschlatter** [comment]
Whoops, I see I broke the PR on linux during the review process. FWIW I just pushed a fix.
