### ISSUE TITLE
hyprland: hyprctl version missing

### ISSUE THREAD

**Issue by bnlrnz** [NixOS/nixpkgs#317234]
### Describe the bug
hyprland is no longer able to present its version. Some other tools depend on getting this version for parsing hyprctl outputs.
[This commit](https://github.com/NixOS/nixpkgs/commit/23d1b8e4fececf2c83875812c0920c3ecd933976#diff-f466618ed484517008b9ba6835831b232aced0d90cd7499d31b819dcb7cf99b1L67-L75) removed the inserted version info.

If/When solving this issue there could also be a problem with a newly introduced placeholder as mentioned in [this comment](https://github.com/NixOS/nixpkgs/pull/309075#discussion_r1593987493).

### Steps To Reproduce
`hyprctl version` or `hyprctl version -j` does not show the current version of hyprland.

### Expected behavior
`hyprctl version` or `hyprctl version -j` shows the current version of hyprland.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/11310385/6d39ad53-7c74-4838-b59b-130453132026)

### Notify maintainers
@wozeparrot @fufexan 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.05 (Uakari), 24.05.803.b3b2b28c1daa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fufexan** [comment]
Right, when I downgraded Hyprland I forgot to consider that the commit which picked up environment variables for version substitution was no longer included.
How bad is the situation? If it's very important I can make a quick PR later. Otherwise, I would prever waiting for the next version.

**Comment by bnlrnz** [comment]
Thanks for your quick response and work overall.

For me, it is not very urgent - next version would be fine. But I don't know about others.

**Comment by gbirke** [comment]
I'm not sure what you mean by "next version" - I'm using NixOS and tend to be conservative and use the version of Hyprland that comes with the latest stable release (currently 24.05). If I had to wait until November (24.11 release) that would be a bummer (but still nothing you'd need to lose sleep over). A few weeks would be fine for me.

**Comment by fufexan** [comment]
@gbirke I'm referring to the next Hyprland release. It will be backported to 24.05.
