### ISSUE TITLE
Package request: python3Packages.python-logging-loki

### ISSUE THREAD

**Issue by Zygmut** [NixOS/nixpkgs#317302]
**Project description**

Python logging handler for Loki

**Metadata**

* homepage URL: [https://github.com/greyzmeem/python-logging-loki](https://github.com/greyzmeem/python-logging-loki)
* source URL: [https://github.com/greyzmeem/python-logging-loki](https://github.com/greyzmeem/python-logging-loki)
* license: mit
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Moraxyc** [comment]
@Zygmut please test https://github.com/NixOS/nixpkgs/pull/317319

**Comment by Zygmut** [comment]
Thanks for waiting @Moraxyc, I've tested the module by checking the examples provided by the author. As far as those, the module works. Should I provide any type of evidence of some sorts?

**Comment by Moraxyc** [comment]
@Zygmut no, thanks.
Just wait for a committer to merge it then.
