### ISSUE TITLE
Update request: cargo-insta 1.33.0 → 1.39.0

### ISSUE THREAD

**Issue by MichaelOultram-pexip** [NixOS/nixpkgs#317404]
- Package name: cargo-insta
- Latest released version: 1.39.0

- Current version on the unstable channel: 1.33.0
- Current version on the stable/release channel: 1.33.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Suspected issue**
It appears that this package should have been updated automatically by https://github.com/nix-community/nixpkgs-update, but this has been failing since 1.33.0 as the Cargo.lock file has been removed from the repo.

https://nixpkgs-update-logs.nix-community.org/cargo-insta/2024-06-05.log
https://github.com/mitsuhiko/insta/pull/410

**Notify maintainers**

@figsoda @oxalica @matthiasbeyer 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oxalica** [comment]
The upstream lockfile seems outdated, we may need to manually lock it in nixpkgs which may not be ideal. I opened https://github.com/mitsuhiko/insta/issues/498

**Comment by emilazy** [comment]
Would it be acceptable if I PR’d an update with a vendored lock file for now, pending resolution of https://github.com/mitsuhiko/insta/issues/498? The current version is missing features I’d like to use, but I don’t really know what the standards are for Rust packaging in Nixpkgs.

**Comment by a-kenji** [comment]
I have an update to the unstable version in: #332299.

Insta added back a lock file, but the version with that is not released yet.

**Comment by MichaelOultram** [comment]
Should this bug be closed now? cargo-insta is `1.40` on unstable.
