### ISSUE TITLE
[vcpkg] Binaries compiled using vcpkg cannot be ran since libstdc++ is not found

### ISSUE THREAD

**Issue by gracicot** [NixOS/nixpkgs#317553]
### Describe the bug
vcpkg patch the RPATH of executables for all tool ports. The problem is that it patches rpath in a way that makes libstdc++ not found, since paths from the nix store seems to be removed.

### Steps To Reproduce
1. `nix shell nixpkgs#vcpkg`
2. `vcpkg install gperf --x-install-path=./vcpkg_installed`
3. Run the gperf executable found in `vcpkg_installed`

See in the `vcpkg install` output:
```
Adjusted RPATH of '/root/.vcpkg/root/packages/gperf_aarch64-linux-clang/tools/gperf/gperf' (From '/app/test123/outputs/out/lib:/nix/store/i69jll18a0an6z14dq71b49xdl8kcqhk-glibc-2.39-5/lib:/nix/store/k0cqy1zwwzjxqcn4fgbjrclr32nbl263-gcc-13.2.0-lib/lib:/nix/store/0x7jwnqfz1d9sciz7nxff0c6hxrcn61m-gcc-13.2.0-libgcc/lib' -> To '$ORIGIN:$ORIGIN/../../lib'
```

See executable fail running:
```
gperf: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

### Expected behavior

Nix paths should not be removed from RPATH

### Additional context
[This function](https://github.com/microsoft/vcpkg/blob/a4275b7eee79fb24ec2e135481ef5fce8b41c339/scripts/cmake/z_vcpkg_fixup_rpath.cmake#L1) might need to be patch to keep nix paths for libstdc++. If anyone with good knowledge of how the nix gcc wrapper and clang wrapper works, that would be incredibly helpful to fix this issue.

Also, see ldd output:
```
ldd ./vcpkg_installed/<triplet>/tools/gperf/gperf
        linux-vdso.so.1 (0x0000ffff9982d000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/i69jll18a0an6z14dq71b49xdl8kcqhk-glibc-2.39-5/lib/libm.so.6 (0x0000ffff99700000)
        libgcc_s.so.1 => /nix/store/c7lp1frzvsa603v9gj97i5alyxslf927-xgcc-13.2.0-libgcc/lib/libgcc_s.so.1 (0x0000ffff996c0000)
        libc.so.6 => /nix/store/i69jll18a0an6z14dq71b49xdl8kcqhk-glibc-2.39-5/lib/libc.so.6 (0x0000ffff99510000)
        /nix/store/i69jll18a0an6z14dq71b49xdl8kcqhk-glibc-2.39-5/lib/ld-linux-aarch64.so.1 (0x0000ffff997f0000)
```

Weirdly, libc, libgcc_s and libm are all found, but not libstdc++

### Notify maintainers

Of course I know the maintainers. He's me. And @Guekka :)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.5.0-15-generic`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.0`
 - channels(root): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jrobsonchase** [comment]
I'm also seeing this happen with a crate2nix-built project after a nixpkgs bump from cf8cc1201be8bc71b7cbbbdaf349b22f4f99c7ae to b2852eb9365c6de48ffb0dc2c9562591f652242a. Seems that previously, libstdc++ and libgcc_s were resolved as `libstdc++.so.6 => /nix/store/f1ii69v7p27z1r5zybmlbld3bdzm6a5f-gcc-13.2.0-lib/lib/libstdc++.so.6 (0x00007fcb23600000)` and `libgcc_s.so.1 => /nix/store/f1ii69v7p27z1r5zybmlbld3bdzm6a5f-gcc-13.2.0-lib/lib/libgcc_s.so.1 (0x00007fcb2415c000)`, but now libgcc_s is `libgcc_s.so.1 => /nix/store/5k2fkrnnp9w7kjvf7s0ancb5rlnml100-xgcc-13.3.0-libgcc/lib/libgcc_s.so.1 (0x00007f5fb3bdb000)` while libstdc++ isn't found.
