### ISSUE TITLE
openssh: "No user exists for uid"

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nixpkgs#31762]
## Issue description

`ssh` is unusable, at least outside NixOS.

### Steps to reproduce

Expected (at d473ef2ed2):

```
$ $(nix-build --no-out-link --attr openssh)/bin/ssh git@github.com; echo $?
PTY allocation request failed
Hi phunehehe! You've successfully authenticated, but GitHub does not provide shell access.
Shared connection to github.com closed.
1
```

Actual (at 76ed35a42d -- tip of master as of now):

```
$ $(nix-build --no-out-link --attr openssh)/bin/ssh git@github.com; echo $?
No user exists for uid 1000
255
```

## Technical details

I use this script:

```
$ cat test.sh 
#!/usr/bin/env bash
openssh=$(nix-build --no-out-link --attr openssh) || exit 125
"$openssh/bin/ssh" git@github.com
[[ $? == 1 ]]
```

and bisect like this:

```
git bisect start 76ed35a42d d473ef2ed2 --
git bisect run ./test.sh
```

The first known "bad" commit is c8c6a1edb5. The last known "good" commits are 25f080ca4a and 21806cfb83 (there are 2 because c8c6a1edb5 is a merge commit). The commits in between are untestable because of build failures.

Here are the possible first "bad" commits:

  - c8c6a1edb5bea5763957bb7c2b2df029b0954743 Merge #31209: cc-wrapper: Fix if dynamicLinker not found
  - f245fe9c502b90cd3f68862ad7aa309537264ccf Merge #28622: glibc-2.26
  - 3a63fc1258bcd4576e20af36ad683f18224da0e5 Remove trailing line
  - 2ed054885b9f52868dae3571a85bb75b3c1eddcf Remove the unnecessary second conditional
  - d3895ced1083f3dbbb2117bf4bba7ce7de70d86d Merge pull request #31119 from peterhoeg/u/lg
  - 62e18a947b88124e2728ec846ff9f90542cc77ed libgit2: delete obsolete patch
  - 225a05906c3a9b4a9d59d00d10cbf7b86d7fc881 julia_05: use libgit2_0_25
  - 2fb0edd085ea83a66e88de209806be720fb53244 git-series: fix build after "source" name change
  - 2b9975c2440c1f6250a7b41194f8b72c66270458 gitg: 3.24.0 -> 3.26.0
  - 711f260f71a4b54f28296fc89a2e0c854b72eff2 libgit2-glib: 0.25.0 -> 0.26.0
  - 43934459fa82b99abab5565fac537922aecf08ce pythonPackages.pygit2: 0.25.1 -> 0.26.0
  - ce1b0c05a52f70fbf03c277018384c9bac3fdf56 libgit2: 0.25.1 -> 0.26.0
  - 1aef6f40bbbe3348986058a12898e57afd4c0ba6 libgit2: fix hash
  - 9bb67d5c1e546968fa3d195f0bcad82414243566 glibc: 2.25-49 -> 2.26-75
  - 0c01c58aec109d856aeb09fc3479b4af902174a2 gcc6: fix build with new glibc, by upstream patches
  - 5f3b84e979a85765fd2f05b302d75b24b285f930 cc-wrapper: disable POSIX compatibility
  - 3e9daece1d1ed6919061f965bc9acea5c6f68a3b nixos/cc-wrapper: Fix bug if dynamicLinker not found

**Comment by orivej** [comment]
This is quality debugging! Indeed, this is caused by `glibc: 2.25-49 -> 2.26-75`. We are tracking it in #31700. In the meantime, there is a workaround: https://github.com/NixOS/nixpkgs/issues/31700#issuecomment-345051762.

**Comment by phunehehe** [comment]
Thanks, I searched for "ssh" but didn't think about searching for the error message :blush:

**Comment by orivej** [comment]
I've added the error messages right after reading your ticket, so that other users could find it.

**Comment by knedlsepp** [comment]
Experiencing this issue using gitFull from 18.03 on a Ubuntu host. Is this really fixed?

**Comment by chrissound** [comment]
Experiencing this on Nixos 19.09 with something like:
```
{
  nixpkgs ? import <nixpkgs> {}
}:(import (nixpkgs.pkgs.fetchgitPrivate {
        url = "ssh://git@gitlab.com/trycatchchris/blog.git";
        rev = "4d127272689a5bc172e82529132b91e5943bb16f";
        sha256 = "04dqda1rdf18fv037vi2vw4apx9zgwdr29rz0gmrw8amgvycdz6v";
      }) {})
```

Thought it worked the other day?
