### ISSUE TITLE
urh package unable to be installed with uhd support

### ISSUE THREAD

**Issue by victorhooi** [NixOS/nixpkgs#317649]
### Describe the bug
I'm getting collision errors when trying to install the urh package with uhd support.

### Steps To Reproduce
1. I'm on macOS 14.4.1, and using [this template](https://github.com/dustinlyons/nixos-config) as my starter template (uses nix-darwin, home-manager etc.)
2. I've added the following to ~/nixos-config/modules/shared/packages.nix:
```
urh
(urh.override { USRPSupport = true; })
]
```
4. I then run `nix run ./#build-switch`

### Expected behavior
The `urh` package should install with `uhd` support enabled.

### Screenshots
I get the following error when running build-switch:
```
❯ nix run ./#build-switch
warning: Git tree '/Users/foo/nixos-config' is dirty
Running build-switch for aarch64-darwin
Starting build...
warning: Git tree '/Users/foo/nixos-config' is dirty
error: builder for '/nix/store/p28jhkibpj822j660dgb27w2vxkf5dyw-system-path.drv' failed with exit code 255;
       last 1 log lines:
       > error: collision between `/nix/store/fz61idkkjgk4bnyjpk9vn3yvbvvcp7d1-urh-2.9.6/bin/.urh_cli-wrapped' and `/nix/store/c8nps5q2z4cv3wd9nspashz5prwg6v04-urh-2.9.6/bin/.urh_cli-wrapped'
       For full logs, run 'nix log /nix/store/p28jhkibpj822j660dgb27w2vxkf5dyw-system-path.drv'.
error: 1 dependencies of derivation '/nix/store/b1cwid91iv61dwcrjg4abzpbghns1hh4-darwin-system-24.11.20240529.ad57eef+darwin4.c0d5b8c.drv' failed to build
```

### Notify maintainers

@r-ryantm @sikmir @AndersonTorres 

### Metadata
I'm sorry - this command doesn't seem to be working for me =(:

```
❯ nix-shell -p nix-info --run "nix-info -m"
error:
       … while calling the 'import' builtin
         at «string»:1:18:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at «string»:1:25:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)


```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
you have `urh` twice in your config, just install one of those packages. that's generally what collisions indicate.

**Comment by AndersonTorres** [comment]
@victorhooi was your problem solved?

**Comment by victorhooi** [comment]
Yes - this was user error =(.

(Apologies - I am quite new to Nix, so I didn't realise that the override line itself also installs `urh`. I had perhaps naively assumed you'd need to define urh fine, then the override. For context, the original helpful suggestion [here](https://www.reddit.com/r/NixOS/comments/1d99m36/how_do_you_enable_optional_featuresdependencies/), but the misuse was mea culpa).
