### ISSUE TITLE
Build failure: virt-manager-qt

### ISSUE THREAD

**Issue by LogicalOverflow** [NixOS/nixpkgs#317729]
### Steps To Reproduce

1. build *virt-manager-qt* on 24.05 (or, I assume, unstable)

### Build log

Full log: https://hydra.nixos.org/build/260898426/nixlog/4

```
-- Checking for module 'qtermwidget5'
--   No package 'qtermwidget5' found
CMake Error at /nix/store/pb69k0zwhxg6kf9ifz13x1wjs6a9vmf0-cmake-3.29.2/share/cmake-3.29/Modules/FindPkgConfig.cmake:634 (message):
  The following required packages were not found:

   - qtermwidget5
```

### Additional context

Bisecting the build yields 9ee17ce743b4ba53878fcad5639f6b3ee057177a from #313122  as the first bad commit. It updates `lxqt.qtermwidget` from `1.4.0` to `2.0.0`.

### Notify maintainers

@peterhoeg @romildo 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dawidd6** [comment]
Relevant upstream commit: https://github.com/lxqt/qtermwidget/commit/b1fa777750627dc746cd4fc6ef9758cc3f160ffa
