### ISSUE TITLE
Package request: python311Packages.signxml

### ISSUE THREAD

**Issue by rameshboini** [NixOS/nixpkgs#317787]
**Project description**

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
code at https://pypi.org/project/signxml/
license is `asl20`
homepage at https://xml-security.github.io/signxml/

in the future please fill out whochever fields are possible/known.

**Comment by fabaff** [comment]
Is already [available](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=signxml).

**Comment by rameshboini** [comment]
I should have filled in the title, request was for to add in 23.11. YES its available in 24.05

https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=signxml

**Comment by eclairevoyant** [comment]
23.11 won't be supported in 3 weeks; it's best to migrate off.
