### ISSUE TITLE
Package request: atticd

### ISSUE THREAD

**Issue by jzbor** [NixOS/nixpkgs#317732]
**Project description**

Attic is a self-hostable Nix Binary Cache server backed by an S3-compatible storage provider. It has support for global deduplication and garbage collection.

**Metadata**

* homepage URL: https://docs.attic.rs/
* source URL: https://github.com/zhaofengli/attic
* license: apache2
* platforms: Linux

---

While the attic client program is packaged as part of nixpkgs this is not the case for the other attic binaries atticd and atticadm. While trying to install attic on a low-memory ARM-system I hit the resource limits with the attic build process. Packaging as part of nixpkgs would allow for the binary to be cached while the nixos module may still be out-of-tree as part of the attic flake.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jzbor** [comment]
Related: #232532

**Comment by pluiedev** [comment]
Isn't this already packaged in [attic-server](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/at/attic-server/package.nix)?

**Comment by jzbor** [comment]
Hm you are right. Now I wonder why the build is not cached/why the cache is not used. Maybe it's an issue with the attic module...

**Comment by jzbor** [comment]
It seems though, as if `attic-server` does not build  in hydra under `aarch64-linux`:
```
[jzbor@desktop-i5] ~ hydra-check attic-server --channel 24.05 --arch aarch64-linux             
Build Status for nixpkgs.attic-server.aarch64-linux on 24.05
⚠ This job is not a member of the latest evaluation of its jobset. This means it was removed or had an evaluation error.
```

**Comment by Shawn8901** [comment]
The linked pr should fix the issue. the used override to set the `mainProgram` did nuke the meta attr, including the `plattforms`.
