### ISSUE TITLE
Slack segfaults during startup after upgrading (4.37.101 -> 4.38.121)

### ISSUE THREAD

**Issue by twz123** [NixOS/nixpkgs#317708]
### Describe the bug

Updated my system from 9ddcaffecdf098822d944d4147dd8da30b4e6843 to a2e1d0414259a144ebdc048408a807e69e0565af today and noticed Slack crashing. In contrast, VSCodiuim as another example of an Electron app works without problems.

Bisecting quickly identified the version bump as the first bad commit: #312293.

### Steps To Reproduce
1. `NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:NixOS/nixpkgs/5206a34313ad#slack` (crashes)
2. `NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:NixOS/nixpkgs/5aab418b48c7#slack` (works)

### Expected behavior
Slack 4.38.121 works.

### Screenshots

Last output on the console:

```text
[06/06/24, 12:24:48:881] info: Store: MAIN_WINDOW_SHOWN
[06/06/24, 12:24:48:882] info: Store: UPDATE_SETTINGS {
  "mainWindowSettings": {
    "fullScreen": false,
    "maximized": false,
    "bounds": {
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1032
    }
  }
}
[06/06/24, 12:24:48:882] info: Store: CLEAR_NOTIFICATIONS
[0606/122448.957828:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0606/122448.958457:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0606/122448.958698:ERROR:process_memory_range.cc(75)] read out of range
Segmentation fault
```

### Additional context
I'm on Wayland, if that matters.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 23.11 (Tapir), 23.11.20240604.a2e1d04`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - nixpkgs: `/home/twieczorek/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by twz123** [comment]
Note that this also happens for me when using the original bump from #312017 (github:NixOS/nixpkgs/68fc12548b69#slack), whereas the current nixos-24.05 version works (github:NixOS/nixpkgs/0b8e7a1ae5a9#slack). Maybe some other fix needs to be backported as well?

**Comment by twz123** [comment]
Alright, seems to be #313206. Can that still be backported to 23.11?

**Comment by teutat3s** [comment]
Thanks for reporting. Should be fixed by https://github.com/NixOS/nixpkgs/pull/317712.

**Comment by twz123** [comment]
Thanks!
