### ISSUE TITLE
Update request: cosmic-files 2024-02-28 → master?

### ISSUE THREAD

**Issue by atomicptr** [NixOS/nixpkgs#317752]
- Package name: cosmic-files
- Latest released version: Does not really have releases (yet), so presumably latest master?
- Current version on the unstable channel: 2024-02-28
- Current version on the stable/release channel: 2024-02-28

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ahoneybun 
@nyabinary

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ahoneybun** [comment]
It's updated a few times but not every time since development is still being done on it.

**Comment by atomicptr** [comment]
Well aware of that, it has been a few months and I feel like the huge amount of changes cosmic-files has seen since then would warrant an update :)

**Comment by ahoneybun** [comment]
New PR:

https://github.com/NixOS/nixpkgs/pull/319065

**Comment by ahoneybun** [comment]
@atomicptr it was merged recently so should be in master of nixpkgs.
