### ISSUE TITLE
Package request: Proton Pass Linux client

### ISSUE THREAD

**Issue by xusiai** [NixOS/nixpkgs#317799]
**Project description**

Native Linux desktop client for accessing your Proton Pass vault. 

**Metadata**

* homepage URL: https://proton.me/pass/download
* source URL: https://github.com/protonpass
* license: n/a
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
I see repos for iOS, Android and Web builds, but not the Windows/macOS/Linux ones. Are you sure these are actually open-source? Building from the provided .deb is an option but is discouraged if building from source is viable

**Comment by chewblacka** [comment]
> I see repos for iOS, Android and Web builds, but not for the Windows/macOS/Linux ones. Are you sure these are actually open-source? Building from the provided .deb is an option but is discouraged if building from source is viable

[According to Proton](https://old.reddit.com/r/ProtonPass/comments/1d9gyvj/proton_pass_is_now_available_on_macos_safari_and/l7e07sh/) the source code for the Proton Pass linux client is here:
https://github.com/ProtonMail/WebClients/tree/main/applications/pass-desktop

**Comment by pluiedev** [comment]
Hmmm... looks like they use Yarn but don't ship their own yarn.lock file. We might have to vendor that, which is *annoying* but not impossible to do

**Comment by pluiedev** [comment]
Unfortunately, building from source doesn't seem like a viable option right now — the Yarn infrastructure in Nixpkgs currently is very shoddy and frankly, nobody knows Yarn well enough to make it work reliably. Upstream uses both a monorepo structure and v2 lockfiles, neither of which are really natively supported in Nixpkgs right now (see #254369). Unpacking the upstream .deb file seems like the only way forward
