### ISSUE TITLE
gnome collides with pipewire

### ISSUE THREAD

**Issue by betalars** [NixOS/nixpkgs#317754]
### Describe the bug
When setting [services.xserver.desktopManager.gnome.enable](https://search.nixos.org/options?channel=unstable&show=services.xserver.desktopManager.gnome.enable&from=0&size=50&sort=relevance&type=packages&query=gnome) to true, I get an error stating "Using PipeWire as the sound server conflicts with PulseAudio. This option requires `hardware.pulseaudio.enable` to be set to false"

This is despite gnome supporting pipewire.

### Additional context
[my configuration](https://gitlab.com/betalars/hier-gibt-es-nix-zu-sehen)

### Ideas to resolve
I do not know if this is a nix architecture fail. Something something nix options cannot know if other options are set and plasma needs some sort of audio server.

If this is the case, I would recommend implementing a better error message at least.

But I then don't understand, why this would work on plasma. Maybe you can look into their package and find out how they resolved it.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240531.57610d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by betalars** [comment]
okay more context:

this issue disappears when I disable plasma6

However now it says:
 > To use Flatpak you must enable XDG Desktop Portals with xdg.portal.enable.
and I understand that even less, because I do not use flatpack.

**Comment by eclairevoyant** [comment]
please post the full error message when reporting errors

**Comment by betalars** [comment]
with plasma6:

```
error:
       … while calling the 'head' builtin

         at /nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - Using PipeWire as the sound server conflicts with PulseAudio. This option requires `hardware.pulseaudio.enable` to be set to false
```

without plasma6
```
error:
       … while calling the 'head' builtin

         at /nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - To use Flatpak you must enable XDG Desktop Portals with xdg.portal.enable.

```

**Comment by eclairevoyant** [comment]
in the first case, disable pulseaudio:

```nix
hardware.pulseaudio.enable = false;
```

in the second case, you enabled flatpak:

https://gitlab.com/betalars/hier-gibt-es-nix-zu-sehen/-/blob/master/configuration.nix?ref_type=heads#L187

hence the error tells you the prerequisite option to set:

```nix
xdg.portal.enable = true;
```

and if you enable some wayland compositor or DE, that should be enabled for you already. For example, with gnome:

https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/x11/desktop-managers/gnome.nix#L283

**Comment by betalars** [comment]
Oh okay sorry for the user error and thanks to @eclairevoyant for catching that. I was really sure about never having had this enabled and I should have bothered to look it up myself.

**Comment by betalars** [comment]
Anyways ... I think a slightly better error message could help here.

I think it is counter intuitive that you have to explicitly disable pulse to enable pipewire in gnome.
That is also not needed for plasma.

**Comment by pluiedev** [comment]
The problem here is that PipeWire is an alternate implementation of PulseAudio, and that [GNOME enables PulseAudio by default]. So to enable PipeWire, PulseAudio has to be disabled first. I get that the error message is not that intuitive but I wonder how exactly we could improve it...

**Comment by betalars** [comment]
Okay I think I am going to close this then and make a new issue that just asks for a better error message.
