### ISSUE TITLE
Update request: nexusmods-app 0.4.1 → 0.5.2

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#317852]
- Package name: nexusmods-app
- Latest released version: 0.5.2

- Current version on the unstable channel: N/A
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Make sure to follow [upstream package maintainers documentation](https://github.com/Nexus-Mods/NexusMods.App/blob/main/docs/Contributing.md#for-package-maintainers).

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MisileLab** [comment]
I think it should be on packaging request, not out-of-date package update.

**Comment by MattSturgeon** [comment]
@MisileLab it was packaged in https://github.com/NixOS/nixpkgs/pull/270372 at v0.4.1, it just [hasn't made nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=270372) yet.

**Comment by l0b0** [comment]
Blocked:

```console
❯ nix-shell maintainers/scripts/update.nix --argstr package nexusmods-app

this derivation will be built:
  /nix/store/jq9mmjkarxdylc3w1rskhmfgm1adl9z3-packages.json.drv
building '/nix/store/jq9mmjkarxdylc3w1rskhmfgm1adl9z3-packages.json.drv'...

Going to be running update for following packages:
 - nexusmods-app-0.4.1

Press Enter key to continue...
Running update for:
 - nexusmods-app-0.4.1: UPDATING ...
 - nexusmods-app-0.4.1: ERROR

--- SHOWING ERROR LOG FOR nexusmods-app-0.4.1 ----------------------

cp: cannot stat '/tmp/deps-nexusmods-app-e6jxVa/home/.nuget/packages/*': No such file or directory


--- SHOWING ERROR LOG FOR nexusmods-app-0.4.1 ----------------------
The update script for nexusmods-app-0.4.1 failed with exit code 1
```

**Comment by TornaxO7** [comment]
well, now `0.6.0` is out https://github.com/Nexus-Mods/NexusMods.App/releases/tag/v0.6.0 xD

**Comment by l0b0** [comment]
Closing in favour of #331150.
