### ISSUE TITLE
Package request: canard

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#317837]
**Project description**
 Canard. A command line TUI client for the journalist RSS aggregator. 

**Metadata**

* homepage URL: https://github.com/mrusme/canard
* source URL: https://github.com/mrusme/canard
* license: gpl3
* platforms: linux, darwin
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Moraxyc** [comment]
@hakan-demirli please test #318317
