### ISSUE TITLE
Package request: journalist

### ISSUE THREAD

**Issue by hakan-demirli** [NixOS/nixpkgs#317832]
**Project description**
Journalist is an RSS aggregator that can sync subscriptions and read/unread items across multiple clients without requiring a special client-side integration. Clients can use Journalist by simply subscribing to its personalized RSS feed.

**Metadata**

* homepage URL: https://github.com/mrusme/journalist/tree/master
* source URL: https://github.com/mrusme/journalist/tree/master
* license: gpl3
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Moraxyc** [comment]
@hakan-demirli please test  #318324
