### ISSUE TITLE
inkscape: cannot find libxml2 when using inkex.py

### ISSUE THREAD

**Issue by geplus** [NixOS/nixpkgs#31800]
Hi,
with lots of svg files, I have dis warning that made me unable to work with inkscape, becaus it appears again and again when I close it:

"The fantastic lxml wrapper for libxml2 is required by inkex.py and therefore this extension. Please download and install the latest version from http://cheeseshop.python.org/pypi/lxml/, or install it through your package manager by a command like: sudo apt-get install python-lxml".
(see #3449)
Of course, I've installed python-lxml, but this does not resolve the issue.
If this is a normal message, please make it less annoyng, enabling an option for stop it.

Example image: https://image.flaticon.com/icons/svg/39/39639.svg
Os: Manjaro Linux 64x

**Comment by bjornfor** [comment]
Which nixpkgs version are you on? (I'm on NixOS 17.09 and was able to open and close your linked image without that error message.)

**Comment by geplus** [comment]
Resolved on my system installing python2-lxml package

**Comment by khenter** [comment]
@geplus , python2-lxml resolved issue too. TX.
