### ISSUE TITLE
Update request: nchat 3.67 → 4.86

### ISSUE THREAD

**Issue by lcoogan** [NixOS/nixpkgs#318085]
- Package name: nchat
- Latest released version: 4.86

- Current version on the unstable channel: 3.67
- Current version on the stable/release channel: 3.67

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

The only PR open is a bot update for an outdated version that was never merged. 

**Notify maintainers**

@sikmir 

-----

Note for maintainers: Please tag this issue in your PR.

I've gotten the newest package to build with this config and command:

```nix
{ lib, stdenv,  fetchFromGitHub, cmake, gperf
, file, ncurses, openssl, readline, sqlite, zlib
, AppKit ? null, Cocoa ? null, Foundation ? null
}:

stdenv.mkDerivation rec {
  pname = "nchat";
  version = "4.86";

  src = fetchFromGitHub {
    owner = "d99kris";
    repo = "nchat";
    rev = "v${version}";
    hash = "sha256-ju9FabCxh/OvEFZee6ZzJEG5RpaCwR297SFk7leKnhA=";
  };

  postPatch = ''
    substituteInPlace lib/tgchat/ext/td/CMakeLists.txt \
      --replace "get_git_head_revision" "#get_git_head_revision"
  '';

  nativeBuildInputs = [ cmake gperf ];

  buildInputs = [
    file # for libmagic
    ncurses
    openssl
    readline
    sqlite
    zlib
  ] ++ lib.optionals stdenv.isDarwin [ AppKit Cocoa Foundation ];

  cmakeFlags = [
    "-DHAS_WHATSAPP=OFF" # go module build required
  ];

  meta = with lib; {
    description = "Terminal-based chat client with support for Telegram and WhatsApp";
    mainProgram = "nchat";
    homepage = "https://github.com/d99kris/nchat";
    license = licenses.mit;
    maintainers = with maintainers; [ sikmir ];
    platforms = platforms.unix;
  };
}
```
```sh
$ nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix {}"
```

I don't know nix yet. I'm just hacking my way around

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Steinhagen** [comment]
This issue is resoved in https://github.com/NixOS/nixpkgs/pull/345606.
