### ISSUE TITLE
feishu now has compatibility issues under some Wayland sessions

### ISSUE THREAD

**Issue by MakiseKurisu** [NixOS/nixpkgs#318035]
As found by @BillHuang2001 in https://github.com/NixOS/nixpkgs/pull/311904#issuecomment-2151430465, feishu now will crash in Wayland environment.

I'm running Hyprland and @pluiedev is likely on KDE due to the usage of [Konsole](https://github.com/NixOS/nixpkgs/pull/311904#issuecomment-2114824442). However, I'm able to run AUR feishu-bin 7.15.13-1 on KDE Plasma 6 on my work computer running Arch, so something is probably wrong on our end.

Both pluiedev and I set `$NIXOS_OZONE_WL` so here are some result when messing with arguments passed to .feishu-wrapped:

* `--ozone-platform-hint=auto` (which is injected by `$NIXOS_OZONE_WL`) will default to `--ozone-platform=wayland` for Wayland session, and setting the latter argument will cause feishu to crash without any window created.
* Adding `--ozone-platform=x11` can override `--ozone-platform-hint=auto`, but the program would still crash on Hyprland if:
  * resizing the window (Segmentation fault)
  * mouse enter and exit the window once (Segmentation fault)
  * mouse enter alone does not crash the program (I need to do this so feishu window is active and can be closed by my Hyprland keybind), but closing the window does
* `--enable-features=WaylandWindowDecorations`, `--enable-features=UseOzonePlatform,WaylandWindowDecorations`, and `--enable-wayland-ime` does not help with the crash (kinda obvious).

So I take a look at the `coredumpctl info`, which is more interesting now:

```
                Stack trace of thread 30637:
                #0  0x00007fe87adee820 wl_proxy_get_version (libwayland-client.so.0 + 0x8820)
                #1  0x00007fe86800ca65 im_module_init (im-wayland.so + 0x4a65)
                #2  0x00007fe87bbe5aab gtk_im_module_load (libgtk-3.so.0 + 0x1e5aab)
```

For some reason, despite we set `--ozone-platform=x11`, it is still trying to read IME from Wayland. I'm using Fcitx5 on both NixOS and my working Arch system.

Just to rule out some obvious possibility, `NIXOS_OZONE_WL= WAYLAND_DISPLAY= .feishu-wrapped" --ozone-platform=x11` does not help with the crash. What works is `GTK_IM_MODULE= .feishu-wrapped" --ozone-platform=x11`. I tried to use the IME and it works fine.

I checked my `$GTK_IM_MODULE` which is set to `wayland` by default. Running feishu with `GTK_IM_MODULE=fcitx` instead is also fine.

So here you have it: `GTK_IM_MODULE=` and `--ozone-platform=x11` are currently needed at least if you are using Hyprland & Fcitx5.

Here is a dirty hack from my own config:

```nix
    systemPackages = with pkgs; [
      ((feishu.override (previous: {
        commandLineArgs = (previous.commandLineArgs or "") +
          " --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=x11 --enable-wayland-ime";
      })).overrideAttrs (previous: {
        installPhase = previous.installPhase + ''

          sed -i "s/export XDG_DATA_DIRS/export XDG_DATA_DIRS; GTK_IM_MODULE=; export GTK_IM_MODULE/" $out/opt/bytedance/feishu/feishu
        '';
      }))
    ];
```

**Comment by pluiedev** [comment]
On KDE, just unsetting `NIXOS_OZONE_WL` worked for me. I think the bug with Fcitx5 on Hyprland is an entirely different problem, down to the fact that somehow GTK3 tries to load a IM module from a null pointer when `GTK_IM_MODULE` is set to `wayland`. I ran into that problem a long time ago when I was still using Hyprland with 1Password, and it's the exact same problem. I think I even filed a bug in Chromium's bug tracker about it, lemme see if I can find it
