### ISSUE TITLE
Package request: tomboy-ng

### ISSUE THREAD

**Issue by nguxx** [NixOS/nixpkgs#318021]
**Project description**

tomboy-ng is a note taking app that works and syncronises between Linux, Windows and MacOS. It will also Sync to a private Github repository allowing access to any device with a browser. It features a rich text markup, printing, spell check, backup and snapshot capability. Undo and Redo. Import and export (plain text, RFT, MarkDown). It has Tomboy's automatic linking between notes, searching abilities, NoteBooks and a similar interface. Change a note's title by just editing the title in the edit window.

**Metadata**

* homepage URL: https://github.com/tomboy-notes/tomboy-ng
* source URL: https://github.com/tomboy-notes/tomboy-ng/tree/master/source
* license: MIT License
* platforms:  linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
Building instructions: https://github.com/tomboy-notes/tomboy-ng/wiki/Building-tomboy-ng
