### ISSUE TITLE
Build failure: nyx

### ISSUE THREAD

**Issue by Layer-09** [NixOS/nixpkgs#318027]
### Steps To Reproduce

1. Add nyx as package.
2. Run nyx by itself or with flags.

### Build log

```
Traceback (most recent call last):
  File "/nix/store/448af4xx2al196xsh8q7wamk14mcjz6h-nyx-2.1.0/bin/.nyx-wrapped", line 6, in <module>
    from nyx.__init__ import main
  File "/nix/store/448af4xx2al196xsh8q7wamk14mcjz6h-nyx-2.1.0/lib/python3.11/site-packages/nyx/__init__.py", line 767, in <module>
    import nyx.panel.log
  File "/nix/store/448af4xx2al196xsh8q7wamk14mcjz6h-nyx-2.1.0/lib/python3.11/site-packages/nyx/panel/log.py", line 69, in <module>
    NYX_LOGGER = log.LogBuffer(log.Runlevel.DEBUG, yield_records = True)
                 ^^^^^^^^^^^^^
AttributeError: module 'stem.util.log' has no attribute 'LogBuffer'
```

### Notify maintainers

@offlinehacker 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-xanmod1, NixOS, 24.11 (Vicuña), 24.11.20240603.4a4ecb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/fjs1x9gz2n1dvjqcyyl6qsw110qxc2zn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dawidd6** [comment]
https://github.com/torproject/nyx/issues/15

**Comment by Layer-09** [comment]
> pushed a commit to gentoo/gentoo that referenced this issue on Mar 6, 2022

That time frame sure is disheartening.

**Comment by iblech** [comment]
Closed as completed; but I can reproduce the original issue. @Layer-09, do you know the current state of affairs?

**Comment by Layer-09** [comment]
The nyx project is deprecated, and the last commit was from two years ago. The original issue in their repo has not seen a solution and probably never will, @iblech.

With that in mind, I suppose this would be the ideal time to ping somebody and request the removal of this broken package. Perhaps @dawidd6 or @offlinehacker are aware of the correct way to go about this.

**Comment by Layer-09** [comment]
[Tor Metrics](https://metrics.torproject.org/rs.html) and [TorMap](https://tormap.org) provide an easy way to find details about your relay, though not to the extent of a monitoring application such as nyx.

If you're interested in seeing details per session, you may use **systemctl status tor.service** to see the total of internet data you contributed (e.g. 60GB) until that moment. The internet panel in **btop** allows you to see how much data you contribute per second.

Other than that, there is **Wireshark** if you want analyze internet traffic thoroughly, @iblech.

**Comment by iblech** [comment]
Thank you for your comprehensive answer, @Layer-09, very much appreciated!
