### ISSUE TITLE
Update request: monado 2024-01-02 → 2024-06-07

### ISSUE THREAD

**Issue by AnnoyingRain5** [NixOS/nixpkgs#318177]
- Package name: monado
- Latest released version: 2024-06-07 (24.0.0)

- Current version on the unstable channel: 2024-01-02
- Current version on the stable/release channel: 2024-01-02

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Scrumplex 
@expipiplus1
@prusnak

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
PR in #318203

**Comment by AnnoyingRain5** [comment]
Thank you!
