### ISSUE TITLE
Firefox ignores value of widget.use-xdg-desktop-portal.file-picker

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#318109]
### Describe the bug
Firefox uses the gtk file picker instead of the portal one, even with widget.use-xdg-desktop-portal.file-picker set to 1 and widget.use-xdg-desktop-portal set to true

### Steps To Reproduce
1. Install firefox
2. set the above settings
3. select the open file dialogue

### Expected behavior
On kde using the qt file picker

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.160, NixOS, 24.11 (Vicuña), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(me): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nonetrix** [comment]
I'm having kinda odd issues as well but I haven't touched my config in a while

https://github.com/user-attachments/assets/d4648c4b-2e19-47b7-a8f1-9577beb739ee

File picker isn't working at all for me even though I have the following set:

```nix
{pkgs, ...}: {
  xdg.portal = {
    xdgOpenUsePortal = true;
    enable = true;
    configPackages = [pkgs.xdg-desktop-portal-gtk pkgs.xdg-desktop-portal-kde pkgs.xdg-desktop-portal-hyprland];
    config = {
      common = {
        default = [
          "hyprland;gtk"
        ];
        "org.freedesktop.impl.portal.FileChooser" = [
          "kde"
        ];
      };
    };
  };

  # Fix for https://github.com/NixOS/nixpkgs/issues/189851
  systemd.user.extraConfig = ''
    DefaultEnvironment="PATH=/run/wrappers/bin:/etc/profiles/per-user/%u/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
  '';
}
```
And I have tried setting it only for Hyprland too

**Comment by nonetrix** [comment]
Sorry didn't realize this was closed my dumb
