### ISSUE TITLE
Update request: gnomeExtensions.easyScreenCast 1.7.1 → 1.9.0

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#318151]
- Package name: gnome-shell-extension-EasyScreenCast
- Latest released version: 1.9.0

- Current version on the unstable channel: 1.7.1
- Current version on the stable/release channel: 1.7.1

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

The latest version installed from extensions.gnome.org is usable on NixOS. Hopefully it can be unbroken in nixpkgs.

**Notify maintainers**

@doronbehar 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
I'm surprised people still use it, since Gnome has this functionality builtin... Anyway: https://github.com/NixOS/nixpkgs/pull/318328

**Comment by SamLukeYes** [comment]
> I'm surprised people still use it, since Gnome has this functionality builtin

The builtin screen cast functionality does not handle audio. This extension can record audio without having to install OBS Studio.
