### ISSUE TITLE
vcv-rack: Could not initialize GLFW

### ISSUE THREAD

**Issue by atimofeev** [NixOS/nixpkgs#318205]
### Describe the bug
vcv-rack fails to launch:
```
terminate called after throwing an instance of 'rack::Exception'
  what():  Could not initialize GLFW
```

### Steps To Reproduce
1. Use NixOS `24.05` (or `unstable`), which comes with `vcv-rack v2.4.1`
2. Install `vcv-rack` with ` home.packages = with pkgs; [ vcv-rack ];`\
Or with `environment.systemPackages = with pkgs; [ vcv-rack ];`
4. Execute `Rack`

### Expected behavior
`vcv-rack` launches

### Additional context
`vcv-rack` had no issues launching on `23.11`, which has version `2.4.0`.

### Notify maintainers

@nathyong
@jpotier
@ddelabru

### Metadata

```console
[atimofeev@milaptop:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3-zen1, NixOS, 24.05 (Uakari), 24.05.20240606.9b5328b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/x887lkxvgnrrcfgrzz351qhfvvrkm80x-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by atimofeev** [comment]
Found this [PR](https://github.com/NixOS/nixpkgs/pull/306692), which also mentions GLFW initialization error.
How to hack around this issue with derivation modifications?
Still, I believe this should be fixed via some long-term solution at some point.

**Comment by atimofeev** [comment]
I've just discovered that this only happens on Wayland. 
X11 has no issues launching the app.

Not sure if this is connected, but I also have issue with `gwe` on Wayland:
https://github.com/NixOS/nixpkgs/issues/319117

**Comment by eclairevoyant** [comment]
should be fixed by #323510

**Comment by atimofeev** [comment]
Fixed in current master branch.

**Comment by 44100hertz** [comment]
I'm still having this issue...
