### ISSUE TITLE
Update request: beets 1.6.0 → 2.0.0

### ISSUE THREAD

**Issue by antonmosich** [NixOS/nixpkgs#318327]
- Package name: beets
- Latest released version: 2.0.0

- Current version on the unstable channel: 1.6.0
- Current version on the stable/release channel: 1.6.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@aszlig 
@doronbehar 
@lovesegfault 
@pjones 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/318334

**Comment by jwillikers** [comment]
Why is the version of the `beet` command still outputting `1.6.1`?

**Comment by antonmosich** [comment]
Upstream forgot to change the version number for the 2.0.0 tag. The latest version (for which there already is a PR, see #358086) should have the correct version number.
