### ISSUE TITLE
 Laptop enters suspend even when in use

### ISSUE THREAD

**Issue by PassiveLemon** [NixOS/nixpkgs#318397]
### Describe the bug
 Laptop enters suspend even when in use, about every 5 minutes. Whether media is playing or I'm using the keyboard/mouse does not appear to matter, it will still suspend.

### Steps To Reproduce
I do not know how to reproduce it. Heres my logind config:
```nix
services = {
  logind.extraConfig = ''
    HandlePowerKey=suspend-then-hibernate
    HandlePowerKeyLongPress=poweroff
    HandleLidSwitch=suspend-then-hibernate
    HandleLidSwitchExternalPower=suspend-then-hibernate
    HandleLidSwitchDocked=suspend-then-hibernate
    HoldoffTimeoutSec=5s
    IdleAction=suspend
    IdleActionSec=300s
  '';
};
systemd = {
  sleep.extraConfig = "HibernateDelaySec=1h";
};
```
I also have thermald and powerManagement enabled.

### Expected behavior
Laptop does not suspend when used, and will only suspend after being idle for x time.

### Screenshots
N/A

### Additional context
Framework 13 AMD 7040 series.
The suspensions appear to happen every 5 minutes which would align with the IdleActionSec of 300s (5 minutes) but I'm using the system, like watching videos or whatever and it will still proceed to suspend.

In trying to test battery saving methods, I did run powertop (calibrate and autotune) and I noticed this issue after the fact but I believe powertop settings don't stay across boots so I don't think that caused it? DPMS does not seem to have any effect.

Already tried asking around in 2 Discord servers and on Reddit, along with many searches but haven't had any luck.

### Notify maintainers
Not sure who to notify.

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.2-zen1, NixOS, 24.05 (Uakari), 24.05.20240605.0b8e7a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/axfhzzkixwwdmxlrma7k8f65214acvml-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eliasp** [comment]
The same started happening here as well a few days ago on unstable - displays turn off after 60 secs, even when watching a movie.
The only thing to prevent this is to wiggle the mouse or press keys on the keyboard.

There were no changes the any power management/screensaver settings here, neither in my NixOS configuration, nor interactively in my Plasma 6.0.5 session.

Still trying to figure out where this is coming from.

**Comment by PassiveLemon** [comment]
Ive done a little more digging into journalctl and it appears that systemd.logind is the one starting the suspensions with
```
systemd-logind[1041]: System idle. Will suspend now.
```

**Comment by PassiveLemon** [comment]
This appears to be an issue of my WM not managing idle state or something similar. Since this appears to be unrelated to NixOS, other than the logind configuration option, I will close this.

**Comment by Syndamia** [comment]
Sorry for necrobumping, I had a similar issue to that of eliasp when using Firefox. In my case, the solution was to downgrade Firefox, it seems that newer versions (I don't know from which exactly, but it definitely doesn't happen with versions <=121.0) or a newer version of a dependency (of those newer firefox versions) causes the browser to not signal to the OS/DE when a video is playing.

**Comment by pwaller** [comment]
There are other reports of this on gnome-settings-daemon: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/771 (Repeated suspend loop on resume). I've been experiencing this problem for a while on my nvidia machine, and I do have nvidia power management enabled.

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/611 (Suspend in multiseat not working correctly: One seat causes the entire installation to go into suspend mode).
