### ISSUE TITLE
Update request: flutter 3.22.0 → 3.22.2

### ISSUE THREAD

**Issue by Henry-Hiles** [NixOS/nixpkgs#318344]
- Package name: flutter
- Latest released version: 3.22.2
- Current version on the unstable channel: 3.22.0
- Current version on the stable/release channel: 3.22.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NixOS/flutter 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
I can get this later today

**Comment by Henry-Hiles** [comment]
> I can get this later today

Thank you!

**Comment by RossComputerGuy** [comment]
@Henry-Hiles #318396

**Comment by Henry-Hiles** [comment]
I'll test that tomorrow thanks!
