### ISSUE TITLE
`systemd.sysusers.enable` breaks `hashedPasswordFile`

### ISSUE THREAD

**Issue by TheRealGramdalf** [NixOS/nixpkgs#318365]
### Describe the bug

After enabling `systemd.sysusers.enable` ([ref](https://github.com/TheRealGramdalf/nixos/blob/3205ce68975aad8247c8202c4c01e41d2b257c21/config/hosts/aerwiar/configuration.nix#L5-L11)) while enabling `hashedPasswordFile`, attempting to `nixos-rebuild boot --flake .#` fails with `cat: /persist/secrets/passwdfile.gramdalf: No such file or directory`

### Steps To Reproduce
1. Enable `systemd.sysusers.enable`
2. Add a `normalUser` with a `hashedPasswordFile` ([ref](https://github.com/TheRealGramdalf/nixos/blob/3205ce68975aad8247c8202c4c01e41d2b257c21/flake.nix#L57-L62))
3. Attempt to `nixos-rebuild boot --flake .#`

### Expected behavior
The `hashedPasswordFile` is used, but not added to `/nix/store`

### Additional context

The suggested `nix log` only gives a single error line, complaining that the file doesn't exist. Copy/pasting the `cat` command works, I assume this to be due to the nix build environment being sanitized, with limited access to the filesystem as a whole. 
The source comes from this [part of the file](https://github.com/NixOS/nixpkgs/blob/e8057b67ebf307f01bdcc8fba94d94f75039d1f6/nixos/modules/system/boot/systemd/sysusers.nix#L44C1-L48C6), which attempts to read the `hashedPasswordFile` at build time rather than activation (which was the previous behavior)
Semi related to https://github.com/NixOS/nixpkgs/issues/307159

### Notify maintainers

@nikstur  @NickCao 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix on  main [$!?]
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuña), 24.11.20240531.57610d2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/5jgh89kgmrb687c254wxdac4cj5hqjw8-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by con-f-use** [comment]
Here's a reproducing VM.
```nix
{ pkgs, config, ... }:

{
  users.mutableUsers = false;
  users.users.root.hashedPassword = "";
  services.getty.autologinUser = "root";

  systemd.sysusers.enable = true;
  users.users."main" = {
    isNormalUser = true;
    group = "main";
    # Starvm once, create this file, uncommend, re-build & restart vm
    # hashedPasswordFile =  "/var/lib/secrets/mainpw";
  };
  users.groups."main" = {};

  system.stateVersion = config.system.nixos.release;
  virtualisation.vmVariant = {
    virtualisation = {
      mountHostNixStore = true;
      writableStoreUseTmpfs = false;
    };
  };
}
# Build with:
#   NIXOS_CONFIG="$PWD/configuration.nix" nixos-rebuild build-vm --max-jobs auto --builders '' 
#   # ...you might need `nix-shell -p nixos-rebuild` as it's only installed on NixOS
# Run with:
#   ./result/bin/run-*-vm &
```

**Comment by nikstur** [comment]
This only happens when `mutableUsers = false` because we currently statically (i.e. at build time) generate /etc/passwd and friends. It cannot read a hashedPasswordFile from outside the Nix store in this scenario.

**Comment by con-f-use** [comment]
I'd say that's a pretty big deal.

**Comment by nikstur** [comment]
> It used to work, it's dangerous, so it should be reverted

It cannot have ever worked with systemd-sysusers. There is nothing to revert. If you want to old behaviour you simply do not enable sysusers.

My comment also simply explained why what happens happens. I never said that it shouldn't be fixed. 

Additionally, systemd-sysusers does not attempt to entirely emulate what the users-groups.pl script does. It most likely will never be able to.

systemd-sysusers is experimental right now, which is clearly indicated in the option description.
