### ISSUE TITLE
Package request: Orca Slicer Beta [v2.1.0-beta]

### ISSUE THREAD

**Issue by SelfhostedPro** [NixOS/nixpkgs#318386]
**Project description**
3d Printer Slicing Software

I know you have an entry for the stable version but there's quite a few cool features that come out in beta and may take a while before coming into a stable build. I have tried to override/overlay with no luck with that due to gcc errors that I'm not familiar enough to fix so I'd also be up to asking for help there in the appropriate channels.

[here](https://github.com/SelfhostedPro/nix-system/blob/main/pkgs/orca-beta/default.nix) is how I was trying to do my custom package.

**Metadata**

* homepage URL: https://github.com/SoftFever/OrcaSlicer
* source URL: https://github.com/SoftFever/OrcaSlicer/tree/v2.1.0-beta
* license: AGPL-3.0 license 
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by EBADBEEF** [comment]
In case anyone else finds it useful, I use the released appimage binary because building from source is pretty challenging, using cmake ExternalProject_Add to fetch deps from URLs.

Here is my nix file for the appimage:
```
{ lib , stdenv , fetchurl , appimageTools
, webkitgtk
}:
let
  version = "2.1.0-beta";
in appimageTools.wrapType2 {
  pname = "orca-slicer";
  inherit version;

  src = fetchurl {
    url = "https://github.com/SoftFever/OrcaSlicer/releases/download/v${version}/OrcaSlicer_Linux_V${version}.AppImage";
    hash = "sha256-fkpd+jiotd3P5BycyE/GO5jN2eNlE7s2sB8sbjAjgjY=";
  };

  extraPkgs = pkgs: with pkgs; [ webkitgtk ];

  profile = ''
    export GST_PLUGIN_SYSTEM_PATH_1_0=/usr/lib/gstreamer-1.0
  '';
}
```

**Comment by oddlama** [comment]
Orca slicer has been updated to 2.1.1 in nixpkgs so this can be closed. We can update to beta in the future if it makes sense for a particular release.
