### ISSUE TITLE
Laptop won't suspend, just locks up

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#31831]
[configuration.nix.txt](https://github.com/NixOS/nixpkgs/files/1485680/configuration.nix.txt)
[hardware-configuration.nix.txt](https://github.com/NixOS/nixpkgs/files/1485681/hardware-configuration.nix.txt)
[lshw.txt](https://github.com/NixOS/nixpkgs/files/1485682/lshw.txt)

## Issue description

When I close the lid on my new Dell laptop it doesn't properly suspend but instead the screen just goes blank, the keyboard backlight stays on, and the laptop becomes completely unresponsive. Note that the laptop fan remains on. Opening the laptop lid, pressing keys on the keyboard, or pressing the power button does not wake the laptop up.

When I first got the laptop suspend to ram did work. I hadn't tried suspending the laptop in some time but now when I try it no longer works. I don't have my entire nixos boot history available as I cleaned out old boot entries, so I can't find an old revision which works.

Of note is that the laptop is a dual boot with windows 10 and last time I checked suspend/resume worked on that. I also didn't bother to create a swap partition as the laptop has 16GB of ram so I cannot test the hibernate feature.

### Steps to reproduce
Either close the laptop lid, or select "Suspend to RAM" from the KDE system menu and the screen will go black, the keyboard backlight will remain on, and the laptop fan will remain on. The laptop will become completely unresponsive even when pressing the power button. A hard reboot is required.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2034.78eed74497 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2034.78eed74497"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

I have attached some files which may be of use.

**Comment by aanderse** [comment]
Here is the tail end of the journalctl log prior to attempting to suspend the laptop last weekend.

[journalctl.txt](https://github.com/NixOS/nixpkgs/files/1485691/journalctl.txt)

**Comment by octalsrc** [comment]
I have this same problem with a Dell laptop I've been using for a year, but for me it is rare (about 19/20 times closing the lid successfully suspends) so I haven't gotten around to hunting for solutions.

**Comment by danbst** [comment]
If you really have time, then go through https://wiki.ubuntu.com/DebuggingKernelSuspend

I found a buggy driver for Lenovo Z510 suspend problem with it (https://github.com/NixOS/nixos-hardware/blob/a64cf32a57850f204a90d15e6d981a51710f3243/lenovo/ideapad/z510.nix#L8-L10)

**Comment by octalsrc** [comment]
This problem hasn't reoccurred for my laptop in several months, so I'm assuming some update has fixed it.

**Comment by aanderse** [comment]
Installed NixOS unstable (soon to be 18.09) and can confirm I no longer have this issue.

Thanks for commenting on this thread.

**Comment by aanderse** [comment]
Spoke too soon. Issue reappeared after adding the following:

``boot.blacklistedKernelModules = [ "i2c-hid" ];``

Note that without this module being blacklisted the touchpad on my dell won't work.
Rolling this change back allows me to suspend & resume again, though not use the touchpad.
