### ISSUE TITLE
pcloud high data usage while idle

### ISSUE THREAD

**Issue by VanDoge** [NixOS/nixpkgs#318494]
### Describe the bug
pcloud uses a lot of bandwidth while supposed to be idle

### Steps To Reproduce
1. install pclaud with patch https://discourse.nixos.org/t/pcloud-gives-segmentation-fault/31330/5?u=patryk27 mentioned in https://github.com/NixOS/nixpkgs/issues/226339
2. at least 2 rebuilds with it already installed

### Expected behavior
minimal background data usage

### Screenshots
https://imgur.com/DXLd9ud

### Additional context
it takes a while till the data usage ramps up
seams not to happen on other other distros.
i checked with fedora and opensuse using appimage 

### Notify maintainers

@Patryk27

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.1135.9b5328b7f761`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Patryk27** [comment]
Hi, sorry for late answer, notification got lost - to be fair, I'm not sure what can be causing this behavior; the Nix version doesn't do any fancy things (it mostly unpacks the archive and prepares it for Nix to consume), we don't add any changes to the source code etc.

Is it still happening to you after this couple of weeks?

**Comment by VanDoge** [comment]
> Hi, sorry for late answer, notification got lost - to be fair, I'm not sure what can be causing this behavior; the Nix version doesn't do any fancy things (it just unpacks the archive and prepares it for Nix to consume), we don't add any changes to the source code etc.
> 
> Is it still happening to you after this couple of weeks?

the issue seam to be file indexing fixed it by exempt */pclaoud from indexing

**Comment by Patryk27** [comment]
I see, interesting!

Hope you don't mind me closing this issue, then - I don't think there's much we can do from Nix/NixOS's side here.
