### ISSUE TITLE
wpsoffice: can not convert to pdf

### ISSUE THREAD

**Issue by plokid** [NixOS/nixpkgs#318452]
### Describe the bug
can not use export to pdf function

### Steps To Reproduce
1. new a doc/docx file
2. export to pdf

### Expected behavior
successfully export to pdf

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/72876162/fe4f30cb-4dff-42bd-9f8f-8d58e5ae89c3)

### Additional context
There might be a explain: https://forums.debiancn.org/t/topic/3930

### Notify maintainers
@mlatus @th0rgal @rewine @pokon548

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.2-zen1, NixOS, 24.11 (Vicuña), 24.11.20240529.ad57eef`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qgbn0imyridkb9527v6gnv6z3jzzprb9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pokon548** [comment]
Reproducible on my side. Will try to investigate and push a pr if feasible

**Comment by eclairevoyant** [comment]
pretty sure we already handle the `libtiff.so.5` dependency:

https://github.com/NixOS/nixpkgs/blob/b7ad06c253087c39fa0a73a3291f7075f55019fd/pkgs/applications/office/wpsoffice/default.nix#L121-L122

as mentioned in the thread, can you try running `export QT_DEBUG_PLUGINS=1` followed by `wpspdf` (or applicable command) to confirm thi actual cause?

**Comment by pokon548** [comment]
I have tried to run `wpspdf` with `export QT_DEBUG_PLUGINS=1`, here is the log: https://pastebin.mozilla.org/VCTNSYa5. 
Seems like there is nothing to do about `libtiff.so`, maybe something else is broken in otherwise.

**Comment by pokon548** [comment]
Never mind. When I tried to create `libtiff.so` link to `libtiff.so.6` on somewhere and running wpspdf with `LD_LIBRARY_PATH=/path/to/libtiff-so-link wps`, it works. 
Maybe the workaround is not working as expected.

**Comment by pokon548** [comment]
@plokid Can you try this pr https://github.com/NixOS/nixpkgs/pull/318500 and see whether this fix this issue for you?

**Comment by plokid** [comment]
@pokon548 还是有问题，我这边直接crash了。把测试的文件发给你。你试试
[测试文件.zip](https://github.com/user-attachments/files/15751888/default.zip)

**Comment by plokid** [comment]
又测试了下，是文件里有图片就崩溃

**Comment by pokon548** [comment]
> 又测试了下，是文件里有图片就崩溃

Fixed in latest push. Feel free to drop a message if further issues appear.

**Comment by plokid** [comment]
ok, it works fine for me
