### ISSUE TITLE
mdadm services are missing

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#31840]
## Issue description
mdadm comes with a few systemd services, in particular one for running "mdadm --monitor --scan" (email you in case something happens to the RAID array). We should have those services in NixOS.

**Comment by bjornfor** [comment]
There actually are some mdadm services in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/swraid.nix. They seem to be incomplete copies from upstream. For example, we lack the monitoring service and the service that starts raid arrays even if they're degraded.

For now I use this workaround:

```
  # Run array, even if degraded (hardcoded hack.. better use upstream systemd unit).
  boot.initrd.preLVMCommands = ''
    mdadm --run /dev/md127
  '';

  # Upstream also has a service like this, but it's not in NixOS yet.
  systemd.services.raid-monitor = {
    description = "Mdadm Raid Monitor";
    wantedBy = [ "multi-user.target" ];
    after = [ "postfix.service" ];
    serviceConfig.ExecStart = "${pkgs.mdadm}/bin/mdadm --monitor --scan";
  };

  environment.etc."mdadm.conf".text = ''
    MAILADDR root
  '';
```

One problem I found is that upstream units/services depends on systemd for assembling arrays etc. NixOS starts systemd _after_ it has found the rootfs. So if your rootfs is on a raid array, ... well :-)

**Comment by bjornfor** [comment]
Seems relevant: https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

**Comment by bjornfor** [comment]
NixOS uses upstream mdadm systemd services since version 19.09. Closing.

But I still think NixOS lack some mdadm support in the initrd that other distros have, so I'm running with this snippet to ensure degraded arrays can be used for rootfs:

```
  boot.initrd.preLVMCommands = ''
    for dev in /dev/md*; do
        if [ -b "$dev" ]; then
            mdadm --run "$dev"
        fi
    done
  '';
```

But that is for another issue.

**Comment by nh2** [comment]
> But that is for another issue. About the initrd.

@bjornfor Shouldn't we file one for that?

**Comment by bjornfor** [comment]
@nh2: Good idea. New issue here: https://github.com/NixOS/nixpkgs/issues/72608.

Coincidentally, this issue was created just 2 days ago: https://github.com/NixOS/nixpkgs/issues/72401 (systemd in initramfs)

**Comment by nh2** [comment]
> NixOS uses upstream mdadm systemd services since version 19.09. Closing.

Looks like there is some problem with that: #72394
