### ISSUE TITLE
lz4: missing CMake configuration files

### ISSUE THREAD

**Issue by Scrumplex** [NixOS/nixpkgs#318509]
### Describe the bug
The `lz4` package does not ship with CMake configuration files (`$dev/lib/cmake/lz4/lz4Config.cmake` and more) which are needed for some CMake project to build properly.

### Steps To Reproduce
1. `nix build nixpkgs#lz4.dev`

### Expected behavior
`lz4` should contain the following files:
```
lib/cmake/lz4/lz4Config.cmake
lib/cmake/lz4/lz4ConfigVersion.cmake
lib/cmake/lz4/lz4Targets-none.cmake
lib/cmake/lz4/lz4Targets.cmake
```

### Additional context
Upstream provides multiple build scripts to build lz4. We are currently using the Makefiles that seem to be the primary way to build lz4. But in addition, lz4 provides [`build/cmake/CMakeLists.txt`](https://github.com/lz4/lz4/blob/5e677416164c9f1102ba6bd708698a20d32ff6a3/build/cmake/CMakeLists.txt), which among building lz4 itself also generates the files needed for other CMake packages.

Most distributions use the Make build script as the primary way of building lz4:

- [Alpine](https://git.alpinelinux.org/aports/tree/main/lz4/APKBUILD?id=33283848034c9885d984c8e8697c645c57324938#n23): Make
- [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/lz4/-/blob/d2286936f674abfe520d0226187c536360b987ba/PKGBUILD#L18): CMake
- [Debian](https://salsa.debian.org/debian/lz4/-/blob/29801e9fc1760e5f1add90f3a60a415d1d4ec76f/debian/rules#L31) Make
- [Fedora](https://src.fedoraproject.org/rpms/lz4/blob/38adfa2654028a73de3b841dd97c91504fd230fa/f/lz4.spec#_50) Meson
- [openSUSE](https://build.opensuse.org/projects/openSUSE:Factory/packages/lz4/files/lz4.spec?expand=1): Make
- [Solus](https://github.com/getsolus/packages/blob/27fb7374e7034ddbb8dbfe117a0fd1d1b5694472/packages/l/lz4/package.yml#L14): Make
- [Void Linux](https://github.com/void-linux/void-packages/blob/8229cd9220e9674a6f28d51fc3dab0f34abdb776/srcpkgs/lz4/template#L7): Make

I have noticed that the derivation has some conditions for MinGW, and it seems like they wouldn't work with CMake, so by switching to CMake as is might break MinGW builds.

### Notify maintainers

Last person who touched lz4 is @szlend. Though this problem wasn't caused by them :D

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3-zen1, NixOS, 24.11 (Vicuña), 24.11.20240607.051f920`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1`
 - channels(scrumplex): `""`
 - nixpkgs: `/etc/nix/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
As there are a few comments regarding MinGW by them, I am cc'ing @Ericson2314

**Comment by SuperSandro2000** [comment]
fixed with linked issue
