### ISSUE TITLE
Dotty in conflict with Scala

### ISSUE THREAD

**Issue by karolchmist** [NixOS/nixpkgs#31858]
## Issue description

I've [added](https://github.com/NixOS/nixpkgs/pull/31478) a new package `dotty` to nixpkgs, which represents the new version of Scala 3.0. 

It works great when installed, but unfortunately causes a conflict with previous versions of Scala.

Is it acceptable, given that we try to install different versions of Scala compiler? 

If not, I would be happy to fix this problem but I don't know how to proceed... Can anyone give me some hints?

## Steps to reproduce

```
nix-env -i scala
nix-env -i dotty
```

Output :
```
installing ‘dotty-0.4.0-RC1’
building path(s) ‘/nix/store/7cd0ff9hva3fs9rgvhsz85bghp98hvkh-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/vxzl4i68vgrfmdhrfcj61cs8b4iazfiq-dotty-0.4.0-RC1/lib/scala-xml_2.12-1.0.6.jar’ and ‘/nix/store/kyl3d46lgrqs9c2zk1q2j074d37l7rqv-scala-2.12.4/lib/scala-xml_2.12-1.0.6.jar’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/kjbgvv335b7n393iykzmgaj557xjwana-user-environment.drv’ failed with exit code 2
error: build of ‘/nix/store/kjbgvv335b7n393iykzmgaj557xjwana-user-environment.drv’ failed
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03.git.35e52ff (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(karol): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by FRidh** [comment]
1. With Nix one typically does not install compilers into a profile, but instead writes Nix expressions
2. Are all the files that are present in the store path also needed in the profile? If not, one could e.g. create a derivation that symlinks `/bin` and you could then install that derivation in your profile.

**Comment by karolchmist** [comment]
Thanks @FRidh for your comment. Dotty is a new experimental version of Scala, so I guess people might install it to play around with the REPL etc. 

So I decided to make a wrapped version of dotty that exposes only its bin folder.
