### ISSUE TITLE
KeePass does not work with TLSv1.2

### ISSUE THREAD

**Issue by lluchs** [NixOS/nixpkgs#31859]
## Issue description

KeePass is run with the rather ancient Mono 4.0.4.4 which supports TLSv1.0 only. Servers are starting to disallow that TLS version which breaks KeePass's synchronization feature.

Possible solutions:
 - change the default `mono` to something more recent (apparently TLSv1.2 support was added in [Mono 4.8.0](http://www.mono-project.com/docs/about-mono/releases/4.8.0/)?)
 - allow changing Mono version in `buildDotnetPackage`
 - continue building with Mono 4.0.4.4, but run KeePass.exe with Mono 5.0 instead

### Steps to reproduce

Try to use KeePass's synchronization feature with a HTTPS server that doesn't allow TLSv1.0.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.12.13, NixOS, 18.03pre120540.b8f7027360 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - channels(lukas): `"stable-17.03.1463.81fceb2554"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

 cc @amorsillo @obadz @joncojonathan @jraygauthier (keepass maintainers)

**Comment by joncojonathan** [comment]
Having taken a quick look I can see that Keepass requires `buildDotNetPackages` which in turn calls `mono`.  `mono` in `all-packages.nix` is set to `mono40`.  I'm going to look at changing this on the Keepass package to use `mono50` instead.

**Comment by joncojonathan** [comment]
This builds OK on my machine for Keepass v2.3.7.

**Comment by joncojonathan** [comment]
PR https://github.com/NixOS/nixpkgs/pull/34360 pointed out there was `mono54`, which is more up to date than the mono50 I initially targeted.  I'd forgotten it existed (I first researched this a month ago).  

I'm looking at building this with `mono54` at the moment.

**Comment by joncojonathan** [comment]
@lluchs This change was just merged, does it provide the functionality you require?  You may need to be on the unstable channel.

**Comment by lluchs** [comment]
Thanks for handling this issue. I can confirm that the change fixes the TLSv1.2 issue.

Unfortunately, synchronization via HTTP still doesn't work, but that seems to be an upstream issue with Mono 5.4 which I also see on Arch Linux. I'm going to report that there and hopefully it will be fixed in a future version of KeePass or Mono.
