### ISSUE TITLE
nexusmods-app won't start .desktop file

### ISSUE THREAD

**Issue by Ithvr** [NixOS/nixpkgs#318567]
### Describe the bug
I am unable to start nexusmods-app outside of ruining the executable file directly in the nix store folder (from the console).
I do not have any shortcut in the start menu (in KDE), and there is no path setup in for the console.
I do see that the .desktop file do set itself up under .local/share/applications/, btu I am getting the impression that it only deals with the URL handler.

### Steps To Reproduce
1. See description  

### Expected behavior
Being able to start for a shortcut or path.

### Additional context
I have tested both the free and nonfree version

### Notify maintainers
@l0b0 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console

 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11pre636273.051f920625ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MattSturgeon** [comment]
> I do see that the .desktop file do set itself up under .local/share/applications/, but I am getting the impression that it only deals with the URL handler.

That is the intended purpose of that file, yes. However I think it can lead to issues when there's multiple desktop entries of the same name (in different locations).

Thankfully, the newer versions will not install a desktop entry at runtime. Instead the nix package will include a desktop entry that handles both launching and the URL mimetype.

However you'll still have to manually remove the old `~/.local/share/applications/com.nexusmods.app.desktop` as it will override the new version's desktop entry.

**Comment by MattSturgeon** [comment]
Now that 0.6.1 had made it to nixos-unstable, I'm curious if this issue is resolved?

Note that the upgrade notes mentioned in https://github.com/NixOS/nixpkgs/pull/331150 are also required; in particular you must "uninstall" any app state before upgrading:
```
NexusMods.App uninstall-app
```

And you'll also need to remove the old desktop entries:
```
rm ~/.local/share/applications/*nexus*.desktop
```

**Comment by Ithvr** [comment]
@MattSturgeon Ah, I was waiting for 6.1 to hit unstable. The new version seems to have solved the issue.
Thank you for your hard work updating Nexus Mods.

**Comment by l0b0** [comment]
> gui does not start for me

Nothing we can do without more information. Please file a new issue with all the details mentioned in the template.
