### ISSUE TITLE
Update request: gajim 1.8.4 → 1.9.0

### ISSUE THREAD

**Issue by FlitPix** [NixOS/nixpkgs#318790]
- Package name: gajim
- Latest released version: [1.9.0](https://dev.gajim.org/gajim/gajim/-/commit/dcf82b29337f0b93239caa77b67b29e299d664a2)

- Current version on the unstable channel: 1.8.4
- Current version on the stable/release channel: 1.9.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@7c6f434c 
@abbradar 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jpds** [comment]
Probably a trivial update if you'd like to put in a PR: https://github.com/NixOS/nixpkgs/pull/266664/files

**Comment by FlitPix** [comment]
Attempting this, I'm struggling with the hash.

I ran this: `nix-prefetch-url https://gajim.org/downloads/1.9/gajim-1.9.0.tar.gz`
But the resulting hash was not in the same format as in that PR you linked. What's the correct way to generate the hash?

**Comment by jpds** [comment]
Ah: #318836
