### ISSUE TITLE
Can`t use any password during install

### ISSUE THREAD

**Issue by AldebaraanMKII** [NixOS/nixpkgs#318752]
### Describe the bug
There is restrictions on the initial password during install.

### Expected behavior
User should be able to use any password when installing the OS, no matter how short or simple.

**Comment by eclairevoyant** [comment]
How are you setting the password?

**Comment by AldebaraanMKII** [comment]
> How are you setting the password?

During install. People should be able to set any password, no matter the length or strength.

**Comment by AldebaraanMKII** [comment]
> > During install.
> 
> Please be more specific, there's multiple ways to set passwords. Repeating your previous comment isn't an answer to an ask for more info

The default way to set password through the calamares installer.

**Comment by eclairevoyant** [comment]
If it's regarding calamares, that'd have to be requested in a separate repo - https://github.com/nixos/calamares-nixos-extensions

**Comment by AldebaraanMKII** [comment]
> If it's regarding calamares, that'd have to be requested in a separate repo - https://github.com/nixos/calamares-nixos-extensions

Very well. Thanks.
