### ISSUE TITLE
Update request: river 0.3.2 → 0.3.3

### ISSUE THREAD

**Issue by LordMZTE** [NixOS/nixpkgs#318743]
- Package name: river
- Latest released version: 0.3.3

- Current version on the unstable channel: 0.3.2
- Current version on the stable/release channel: 0.3.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@adamcstephens
@moni-dz
@rodrgz

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
0.3.3 is only a zig 0.13 compatibility release. It’s blocked by https://github.com/NixOS/nixpkgs/pull/317861

**Comment by JohnRTitor** [comment]
#317861 has been merged, this is not blocked anymore.
