### ISSUE TITLE
mopidy-youtube can't find gst-stream-error-quark

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#31870]
## Issue description

mopidy-youtube doesn't work. I added it to `mopidy.extensionPackages` in my system configuration. It fails like this:

```
INFO     Searching YouTube for query 'search query'
WARNING  Could not find a Opus decoder to handle media.
WARNING  GStreamer warning: gst-stream-error-quark: No decoder available for type 'audio/x-opus, rate=(int)48000, cha
ERROR    GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
```

[Here is my whole system declaration at this point.](https://github.com/mekeor/config/blob/1f646f351a88c2fa2199405b491999ab6dc02cce/nix/system.nix)

### Steps to reproduce

Add something like this to your system declaration:

```nix
{
  # ...
  services = {
    mopidy = {
      enable = true;
      extensionPackages = [
        pkgs.mopidy-local-sqlite
        pkgs.mopidy-musicbox-webclient
        pkgs.mopidy-youtube
      ];
    };
  };
  # ...
}
```

The mopidy-musicbox-webclient should provide a web interface at `localhost:6680`. In search, you can search a video from YouTube. Click to try to play it.

## Technical details

I'm using the current stable branch.

## Useful links

- [declaration of mopidy-youtube as nixpkg](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/mopidy-youtube/default.nix)
- [declaration of mopidy as nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/mopidy/default.nix)

**Comment by mekeor** [comment]
I was thinking maybe mopidy-youtube can't find `gst-stream-error-quark` (which is included in `gst-plugins-bad`, or more specifically, it needs version 1.0, thus `gst_all_1.gst-plugins-bad`) because the mopidy-youtube package doesn't specify `gst_all_1.gst-plugins-bad` as buildInput. It only uses this:

```nix
pythonPackages.buildPythonApplication rec {
  # ...
  propagatedBuildInputs = with pythonPackages; [ mopidy pafy ];
  # ...
}
```

I was thinking that maybe we have to specify `gst_all_1.gst-plugins-bad` explicitely as buildInput. That's why I tried the following snippet in my system declaration without success:

```nix
{
  nixpkgs = {
    overlays = [ (self: super: {
      mopidy-youtube = super.mopidy-youtube.overrideAttrs (oldAttrs: rec {
        buildInputs = super.mopidy-youtube.buildInputs
          ++ [ super.gst_all_1.gst-plugins-bad ];
      });
    })];
  };
}
```

**Comment by jtojnar** [comment]
You would need to add `gst-plugins-bad` to `mopidy`, not `mopidy-youtube`. The issue was most likely fixed by https://github.com/NixOS/nixpkgs/pull/24688.
