### ISSUE TITLE
Locked Screen with the plasma desktop (Intel/AMD) ISO cant get unlocked

### ISSUE THREAD

**Issue by LRahlff** [NixOS/nixpkgs#318782]
### Describe the bug
Once the screen locks (due to inactivity or shortcut) the screen cant get unlocked, because the authentication fails (i cant type no password in the password field)

### Steps To Reproduce
1. Download the iso (plasma, Intel/AMD)
2. Put it on the Ventoy-Stick
3. Boot from it
4. Lock the screen with Meta+L or wait until the screen is locked
5. Try to unlock the screen

### Expected behavior
I would expect to get to the last screen (maybe as with the gnome desktop) without the login prompt.

### Metadata
ISO name: nixos-plasma6-24.05.1135.9b5328b7f761-x86_64-linux
If you really need it, i would restart the computer again and check it

**Comment by chewblacka** [comment]
This is a Plasma 6 bug apparently. If you have an empty password it won't let you unlock the screen. The work around is here:

https://old.reddit.com/r/NixOS/comments/1d9fm5k/locked_out_of_nixos_installer/

**Comment by eclairevoyant** [comment]
For posterity and accessibility, there's a couple workarounds:

> A workaround is to go to a tty using e.g. ctrl+alt+f4, log in as the nixos user, and then use the command `loginctl unlock-session [your-session-id]`. If you don't know your session id, you can get it using `loginctl list-sessions`.

> Switch to a tty, set a password for the user `nixos` with `passwd` and then when you switch back to the lockscreen you can use that password to login.

Pick whichever you find easier

**Comment by rardiol** [comment]
I had what seems to be a similar issue with an installed system. Plasma6 autolocked an user account with no password despite lightdm allowing login.  `security.pam.services.kde.allowNullPassword = true` seems to fix the issue. Maybe it should be added to default NixOS's KDE config? Why is everyone saying it's a KDE bug?

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/321944
