### ISSUE TITLE
oauth2_proxy should not require adminEmail and serviceAccountJSON

### ISSUE THREAD

**Issue by tylerjl** [NixOS/nixpkgs#31883]
## Issue description

Howdy! The module for oauth2_proxy includes options to set the flags

```
--google-admin-email
--google-service-account
```

However, these options are used for some advanced settings if you want to restrict access based on Google Groups users ([see their related documentation](https://github.com/bitly/oauth2_proxy#restrict-auth-to-specific-google-groups-on-your-domain-optional)). These options (`services.oauth2_proxy.google.adminEmail` and `services.oauth2_proxy.google.serviceAccountJSON`) should just be optional and interpolate if set/not null when using the Google provider.

### Steps to reproduce

Attempt to use the `oauth2_proxy` module with `services.oauth2_proxy.google.serviceAccountJSON` and `services.oauth2_proxy.google.adminEmail` unset; the module requires them to be set while oauth2_proxy itself will use them if present, but not necessarily required for the Google provider.

**Comment by knl** [comment]
This doesn't apply anymore, after the refactoring prior to 19.03.
