### ISSUE TITLE
nixpkgs does not evaluate

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#31884]
## Issue description
While trying to do some query on packages, I found the following:
```
  ### Evaluating the entire Nixpkgs naively will fail, make failure fast
  AAAAAASomeThingsFailToEvaluate = throw ''
    Please be informed that this pseudo-package is not the only part of
    Nixpkgs that fails to evaluate. You should not evaluate entire Nixpkgs
    without some special measures to handle failing packages, like those taken
    by Hydra.
  '';
```
I'm puzzled here - why's that OK for nixpkgs NOT to evaluate?

I've fixed all the places that prevented it from evaluation (not very many) and got done what I wanted. Those were not very much (less than 20 files)

There were several different kinds of failures:
- package not supported. Usually done with `package = throw ''whoops not supported'';`
- package should only be cross compiled, `assert targetPlatform != buildPlatform;`
- asserts fail before `mkDerivation`, `{ stdenv, feature, ...}: assert feature; stdenv.mkDerivaiton ...`
- asserts in passthru (however this is specific for my usecase)
- license acceptanse, `if !licenseAccepted the throw ... else assert licenseAccepted`

In all cases except cross compilation I was able to move throw/assert inside derivation, which still didn't allow build, but allowed evaluate more.

### Steps to reproduce

This should get all customizations, that are turned by default to true. For example, if you have
```
{ stdenv, someFeature ? true }: stdenv.mkDerivation ...
```
then this expression should get all such features that are enabled for each package and produce a list:
```
[ "package1.someFeature" "package2.someOtherFeature" ... ]
```

```bash
export NIXPKGS_ALLOW_INSECURE=1
export NIX_PATH=nixpkgs=$HOME/dev/nixpkgs
nix-instantiate --eval -E '(
let
    pkgs = import <nixpkgs> { config = { allowBroken = true; allowUnfree = true; }; };
    lib = pkgs.lib;
    passthrued = lib.mapAttrs (name: value: if builtins.isAttrs value then value.passthru or null else {}) pkgs;
in
    lib.concatLists (lib.mapAttrsToList (name: passthru: lib.mapAttrsToList (pname: value: name + "." + pname) (lib.filterAttrs (n: v: builtins.isBool v && v) passthru))
        (lib.filterAttrs (n: v: v != null)passthrued))
)' --strict
```

Unfortunately, this //query// breaks hard.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.53, NixOS, 18.03.pre.3fe7cdd (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5619_346aeee1`
 - nixpkgs: `/home/danbst/dev/nixpkgs` (6bacc7342aea6995a20ebdc21ca80687c679841e)

**Comment by danbst** [comment]
ping @7c6f434c @grahamc, can you shed the light on this?

**Comment by orivej** [comment]
This idea originated here: https://botbot.me/freenode/nixos/2017-09-30/?msg=91752741&page=3

> I've fixed all the places that prevented it from evaluation (not very many) and got done what I wanted. Those were not very much (less than 20 files)

Could you submit the PR or show the changes?

> In all cases except cross compilation I was able to move throw/assert inside derivation, which still didn't allow build, but allowed evaluate more.

So, you were not able to fix the evaluation without some changes that can not be commited?

**Comment by danbst** [comment]
@orivej Good point
https://github.com/NixOS/nixpkgs/pull/32019

**Comment by vcunat** [comment]
I'm not sure what exactly you want, but typically one uses `tryEval` to catch `throw`s and some other evaluation problems.  We have some places in nixpkgs using it, e.g. `<nixpkgs/pkgs/top-level/release-lib.nix>` used for Hydra's jobsets.

**Comment by danbst** [comment]
Example of query:
```
NIXPKGS_ALLOW_INSECURE=1
nix eval "(let pkgs = import <nixpkgs> { 
    config.allowBroken = true; config.allowUnfree = true;
 }; 
lib = import <nixpkgs/lib>; 
in lib.mapAttrs (k: v: v.name or \"\") pkgs)"
```
`tryEval` won't help much in this case.

**Comment by vcunat** [comment]
Apparently it does.  Hydra does evaluate all packages, so does <nixpkgs/maintainers/scripts/rebuild-amount.sh>, and neither experiences this problem.

**Comment by 7c6f434c** [comment]
@danbst on every platform there are packages that assert (in different ways, too) that this platform is not suitable. Acknowledging this explicitly means that there won't be reports of random exotic packages creating hard-to-understand failures.

Why enumerating the attribute names, then `tryEval` on getting every attribute, and possibly some recursion won't work?

**Comment by 7c6f434c** [comment]
I wonder if the fixes you tried are enough for evaluating Nixpkgs naively, or for recursing into `pythonPackages`/`nodePackages` too.

**Comment by danbst** [comment]
@vcunat I don't quite get how Hydra can evaluate this one
https://github.com/NixOS/nixpkgs/blob/bdce7d3a04ea3ebaebe033da13e3c6651845e45f/pkgs/applications/science/machine-learning/sc2-headless/default.nix
Does it use some undocumented Nix feature to ignore `throw` and `assert`?

Here is what goes on when one tries to use `.override`:
```
$ nix eval "(with import <nixpkgs> {}; builtins.attrNames (sc2-headless.override {licenseAccepted = true;}))"
error: You must accept the Blizzard® Starcraft® II AI and Machine Learning License at
https://blzdistsc2-a.akamaihd.net/AI_AND_MACHINE_LEARNING_LICENSE.html
by setting nixpkgs config option 'sc2-headless.accept_license = true;'
```

Wait, but I have actually set `licenseAccepted = true;`! With my change this becomes:

```
$ nix eval "(with import ./. {}; builtins.attrNames (sc2-headless.override {licenseAccepted = true;}))"
[ "__ignoreNulls" "all" "args" "buildInputs" "builder" "configureFlags" "drvAttrs" "drvPath" "installPhase" "meta" "name" "nativeBuildInputs" "out" "outPath" "outputName" "outputUnspecified" "override" "overrideAttrs" "overrideDerivation" "passthru" "preFixup" "propagatedBuildInputs" "propagatedNativeBuildInputs" "src" "stdenv" "system" "type" "unpackCmd" "userHook" "version" ]
$ nix build "(with import ./. {}; sc2-headless)"
error: You must accept the Blizzard® Starcraft® II AI and Machine Learning License at
https://blzdistsc2-a.akamaihd.net/AI_AND_MACHINE_LEARNING_LICENSE.html
by setting nixpkgs config option 'sc2-headless.accept_license = true;'
```

@7c6f434c good point. Haven't thought about these collections. Well, small step at a time then

**Comment by danbst** [comment]
@7c6f434c on second thought, yes, probably tryEval would suite my needs. I'd just ignore non-evaluating expressions. But I really do want for `.override` to work, and making it work for all packages makes great progress towards full nixpkgs evaluation.

It will still be unbuildable, which is reasonable.

**Comment by 7c6f434c** [comment]
>@7c6f434c on second thought, yes, probably tryEval would suite my needs. I'd just ignore non-evaluating expressions. But I really do want for `.override` to work, and making it work for all packages makes great progress towards full nixpkgs evaluation.

Well, an override with removal of `broken` _and_ a patch could even work.

I agree that allowing an override of `meta.broken` would be nice, although not enough for your task (`throw` about unsupported platforms need to be handled separately); I don't have any design ideas for that.

**Comment by manveru** [comment]
This seems to work for me.

```nix
let
  pkgs = import <nixpkgs> {
    config.allowBroken = true;
    config.allowUnfree = true;
  };
  lib = import <nixpkgs/lib>;
  tryEval = builtins.tryEval;
in
  lib.mapAttrs (k: v:
    let name = (tryEval v.name or "");
    desc = (tryEval v.meta.description or "");
    in {
      name = name.value;
      description = desc.value;
    }
  ) pkgs
```

**Comment by danbst** [comment]
@manveru yes, except that it won't work for some packages (`sc2-headless`, as in example above)

```
sc2-headless = { description = false; name = false; };
```

**Comment by manveru** [comment]
Yeah, while that's unfortunate, for me it's the same as if the package didn't exist if it fails to evaluate even the most basic metadata... would it even install on any machine?

**Comment by danbst** [comment]
@manveru For many packages - yes, those are broken/deprecated. But for `sc2-headless` - no, it fails because user hasn't accepted license.

**Comment by Ekleog** [comment]
(triage) Closing as this appears to have been superseded by https://github.com/NixOS/nixpkgs/issues/36229
