### ISSUE TITLE
Upgrade to 18.03pre120540.b8f7027360 breaks Xorg under VirtualBox

### ISSUE THREAD

**Issue by juselius** [NixOS/nixpkgs#31889]
## Issue description
Upgrading from 18.03pre120398.aeff3080d0 to 18.03pre120540.b8f7027360 breaks X11 when running under VirtualBox. X11 fails to load the vboxvideo module due to mismatching ABI major versions:
```
Nov 21 09:25:31 curry display-manager[1010]: (EE) vboxvideo: module ABI major version (20) doesn't match the server's version (23)
Nov 21 09:25:31 curry display-manager[1010]: (II) UnloadModule: "vboxvideo"
Nov 21 09:25:31 curry display-manager[1010]: (II) Unloading vboxvideo
Nov 21 09:25:31 curry display-manager[1010]: (EE) Failed to load module "vboxvideo" (module requirement mismatch, 0)
```

### Steps to reproduce
1. Run NixOS unstable under (64bit) VirtualBox 5.2 (or 5.1.3) on Windows 1709
2. ``$ sudo nixos-rebuild switch --upgrade``
3. reboot
4. X11 fails to start

## Technical details
(This is the current _working_ system, after the rollback from 18.03pre120540.b8f7027360)

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03pre120398.aeff3080d0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - channels(jonas): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dezgeg** [comment]
Maybe all that needs to be done is to drop this line?

````
diff --git a/nixos/modules/services/x11/xserver.nix b/nixos/modules/services/x11/xserver.nix
index 7d544e153e9..e54a7c49bdd 100644
--- a/nixos/modules/services/x11/xserver.nix
+++ b/nixos/modules/services/x11/xserver.nix
@@ -548,8 +548,6 @@ in
           knownVideoDrivers;
       in optional (driver != null) ({ inherit name; modules = []; driverName = name; } // driver));
 
-    nixpkgs.config.xorg = optionalAttrs (elem "vboxvideo" cfg.videoDrivers) { abiCompat = "1.18"; };
-
     assertions = [
       { assertion = config.security.polkit.enable;
         message = "X11 requires Polkit to be enabled (‘security.polkit.enable = true’).";
````

**Comment by juselius** [comment]
Perhaps. It's worth a try, at least. How do I install/override system modules in configuration.nix, using my local nixpkgs repo?

**Comment by dezgeg** [comment]
Git clone, make the change, then `sudo nixos-rebuild switch -I nixpkgs=/path/to/local/nixpkgs`.

**Comment by vcunat** [comment]
That's strange.  The log claims that server running is 1.19 and you attempt to load vboxvideo for 1.18, i.e. that's exactly the thing that the line is trying to fix by installing 1.18 server instead if you specify `"vboxvideo"` in `videoDrivers` (the line you're about to delete).

**Comment by vcunat** [comment]
Even after the update I see the newest driver is for server 1.18.  Apparently something is interfering with the option attempting to switch your system to 1.18 instead of the default 1.19, though it's suspicious it started just when vbox is updated.

**Comment by dezgeg** [comment]
I think apparently the real problem is that we're using the vboxvideo driver at all, upstream claims the modesetting driver should be used nowadays: https://www.virtualbox.org/ticket/16052

**Comment by juselius** [comment]
@dezgeg I had missed the -I flag in the nixos-rebuild man page! I must say it's pretty well hidden from view... Thanks!

**Comment by vcunat** [comment]
Then I wonder why they [just now published](https://lists.x.org/archives/xorg-announce/2017-December/002828.html) their driver into X.org repo...

**Comment by hussein-aitlahcen** [comment]
I'm experiencing the same issue, any simple workaround ?

**Comment by matthewbauer** [comment]
Is this still an issue on 18.03? IIRC we included a fix for this.

**Comment by jhillyerd** [comment]
Still seeing on 18.09:

```
[  6418.659] (II) Module vboxvideo: vendor="Oracle Corporation"
[  6418.659]    compiled for 1.18.0, module version = 1.0.1
[  6418.659]    Module class: X.Org Video Driver
[  6418.659]    ABI class: X.Org Video Driver, version 20.0
[  6418.659] (EE) vboxvideo: module ABI major version (20) doesn't match the server's version (23)
[  6418.659] (II) UnloadModule: "vboxvideo"
[  6418.659] (II) Unloading vboxvideo
[  6418.659] (EE) Failed to load module "vboxvideo" (module requirement mismatch, 0)
[  6418.659] (II) LoadModule: "modesetting"
[  6418.660] (II) Loading /nix/store/bkjfsrkx18ydy27v95y9vnp17vkvcbn5-xorg-server-1.19.6/lib/xorg/modules/drivers/modesetting_drv.so
[  6418.660] (II) Module modesetting: vendor="X.Org Foundation"
[  6418.660]    compiled for 1.19.6, module version = 1.19.6
[  6418.660]    Module class: X.Org Video Driver
[  6418.660]    ABI class: X.Org Video Driver, version 23.0
[  6418.660] (II) LoadModule: "vboxmouse"
[  6418.660] (WW) Warning, couldn't open module vboxmouse
[  6418.660] (II) UnloadModule: "vboxmouse"
[  6418.660] (II) Unloading vboxmouse
[  6418.660] (EE) Failed to load module "vboxmouse" (module does not exist, 0)
```

**Comment by ggPeti** [comment]
Right, same here. Acceleration does not work and I'm seeing the same EE lines as above. [OpenIndiana has released an updated vboxvideo compatible with ABI version 23](https://www.openindiana.org/2017/11/11/virtualbox-video-driver-compatible-with-xorg-1-19-5-available/), I'd appreciate any pointers in how to port this to NixOS.

**Comment by matthewbauer** [comment]
Yeah we use the official Guest Additions ISO. I guess we could build it from source, but I wonder if there is some issue preventing VirtualBox from support 1.19? Closing this for now. You can track VirtualBox's support here:

https://www.virtualbox.org/ticket/17070

**Comment by ggPeti** [comment]
But it's still an issue "for now", so what's the point in closing this? Pretending it's not there won't make it go away for real. Btw that linked virtualbox issue is clearly a different one based on the log lines, and hasn't been touched in 10 months, so not quite sure what you're suggesting.

**Comment by juselius** [comment]
I gave up and switched to vmware. A good deal better user experience overall.

**Comment by vcunat** [comment]
It's possible that the driver would just work if we [compiled it ourselves ](https://lists.x.org/archives/xorg-announce/2017-November/002827.html).  Another option might be to default to `"modesetting"`.  Still, I know really nothing about virtualbox, so it's hard for me to move it forward.

**Comment by juselius** [comment]
I spent some time trying to get custom compiled guest additions to work properly, but never managed to get anywhere with it.

**Comment by vcunat** [comment]
Can someone test _running_ with https://github.com/NixOS/nixpkgs/pull/50280?  (Applied in the vbox guest.)

**Comment by ggPeti** [comment]
Pardon for the nagging, but how can I test that patch? I don't see an option in nixos-rebuild to use a local directory, neither in nix-channel.

**Comment by vcunat** [comment]
@ggPeti `nixos-rebuild -I nixpkgs=/path/to/tree`

**Comment by jhillyerd** [comment]
the rebuild above is missing the `switch` command.  More verbosely, if you already have nixpkgs checked out in $HOME/nixpkgs:
```
cd nixpkgs/
git remote -vv add vcunat https://github.com/vcunat/nixpkgs.git
git fetch vcunat
git checkout -b vboxvideo vcunat/p/vboxvideo
cd
sudo nixos-rebuild -I nixpkgs=$HOME/nixpkgs/
```

I'm building it now...

**Comment by juselius** [comment]
A small remark, unrelated to this issue. The ``-I nixpkgs=...`` is very useful, and also undocumented. I have numerous times tried to solve some problem, failed, only to later find out that the documentation is out of sync with the implementation. I normally expect ``--help`` to give me terse, current and up to date information. Redirecting to an outdated man page is less than optimal. Sorry for being off topic.

**Comment by vcunat** [comment]
I intentionally omitted the rest of the command.  You may put different things in there, e.g. I personally prefer `boot` to `switch` for larger changes (and changes requiring X restart feel larger).
