### ISSUE TITLE
Meshtastic CLI client doesn't work: ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#318938]
### Describe the bug
Running the meshtastic CLI (python3Packages.meshtastic) fails with this error:

```
saiko@invader ~ % nix shell nixpkgs#python3Packages.meshtastic
saiko@invader ~ % meshtastic 
Traceback (most recent call last):
  File "/nix/store/ryjs2hwqdlk1sb49v9wkhjz4iqdyjbfb-python3.11-meshtastic-2.3.4/bin/.meshtastic-wrapped", line 6, in <module>
    from meshtastic.__main__ import main
  File "/nix/store/ryjs2hwqdlk1sb49v9wkhjz4iqdyjbfb-python3.11-meshtastic-2.3.4/lib/python3.11/site-packages/meshtastic/__init__.py", line 81, in <module>
    from meshtastic import (
  File "/nix/store/ryjs2hwqdlk1sb49v9wkhjz4iqdyjbfb-python3.11-meshtastic-2.3.4/lib/python3.11/site-packages/meshtastic/util.py", line 16, in <module>
    import packaging.version as pkg_version
ModuleNotFoundError: No module named 'packaging'
```

It works if you run it using `nix-shell -p python3Packages.packaging python3Packages.meshtastic`.

### Steps To Reproduce
1. Run `${python3Packages.meshtastic}/bin/meshtastic`.

### Expected behavior
The program runs correctly.

### Notify maintainers

@fabaff 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.28, NixOS, 24.05 (Uakari), 24.05.20240501.e166a07`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Seems like just adding `packaging` to the dependencies works
