### ISSUE TITLE
Hostname being set too late during bootup causes mismatching log metadata.

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#318907]
### Describe the bug
Hostname being unset (resulting in `localhost`) causes issues for logging. Specifically, with journald, the same boot (identified by `_BOOT_ID` (see systemd.journal-fields(7)) has both `_HOSTNAME=localhost` and `_HOSTNAME=<intended hostname>` with the switch happening at the rootfs pivot of the boot.

#### Why does this matter?
This makes filtering by hostname difficult. Even more so, when doing log aggregation from multiple machines, filtering by hostname will yield incomplete results. Instead one must build a pipeline that makes looks up all boot_ids of a hostname and querying all those instead.

### Steps To Reproduce
1. boot
2. inspect `journalctl -o cat --output-fields=_BOOT_ID,_HOSTNAME -b`
3. see behavior described above

### Expected behavior
journal contains the the same `_HOSTNAME` as long as it not changed by the user.

Hostname should be generally available, even during early boot(?).

### Screenshots
N/A

### Additional context
I'm filing this as a bug instead of a pull request because I'm not sure if there are any unintended consequences of doing this. Aside from the usual https://xkcd.com/1172/. **Hoping for your input here.**

There's a reference in the docs giving an example of setting the hostname by hand: https://github.com/NixOS/nixpkgs/blob/e2dd4e18cc1c7314e24154331bae07df76eb582f/nixos/modules/system/boot/systemd/initrd.nix#L163 (from 5653209ed95985034bbb43bb63e04190639477a0). Why this was chosen as an example and not just standard behavior, I don't know.

### Notify maintainers

CC/FYI @dasJ , @roberth who added the example/was tagged in the commit.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
╰$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240607.051f920`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- channels(root): `""`
- channels(...): `""`
- nixpkgs: `/nix/store/3dr5pyja36lvvrszhzffww1jwyrx6i09-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by roberth** [comment]
> Why this was chosen as an example and not just standard behavior, I don't know.

Me neither. I don't see a reason not to have that file. @dasJ may be more knowledgeable, but I'd say go for it.
Also systemd-based initrd is somewhat young, so I feel like the probability for spacebar heating is somewhat low.

**Comment by dasJ** [comment]
I think the main reason was to have the initrds be more substitutable between different hosts as this would be a difference between all of them (when having different systems with only different hostnames).

I'm not sure how well adding the hostname file would work. My memory is a bit fuzzy on the details (I did a lot of other projects at that time) but I think an issue was that when journald starts up, it imports the kernel logs BEFORE the hostname was set (causing the pre-systemd lines to be mapped to localhost). An alternative implementation that would probably solve that as well (if it's still/even an issue) would be adding the `hostname=` kernel parameter rather than adding the fiel to the initrd.

**Comment by roberth** [comment]
> I think the main reason was to have the initrds be more substitutable between different hosts as this would be a difference between all of them (when having different systems with only different hostnames).

> set `systemd.hostname` on the kernel cmdline

It seems this is the best choice then, but maybe also

> adding the `hostname=` kernel parameter

as that's more standard and picked up even earlier in the boot process. Unless you're running an old kernel though. ([<5.19?](https://www.phoronix.com/news/Linux-Kernel-Hostname-Set))
We could just set both.

**Comment by dasJ** [comment]
Why not? Most people use https://github.com/nix-community/lanzaboote for that which signs whatever UKI you have locally with a local key

**Comment by dasJ** [comment]
Yes, that's the downside. Although, the cmdline is only baked into the UKI which is not in the nix store anyway. This way we could substitute the initrd and have differing hostnames.

I must mention, however, that I personally don't care about the substitutability of the initrd. My main focus was to keep the state as it was before, but if people decide it's time to change that, I'm not opposed to that ;)
