### ISSUE TITLE
Mesa 24.0.7 Breaks FFXIV running via XIVLauncher on Intel Arc GPU's

### ISSUE THREAD

**Issue by thyTwilightGoth** [NixOS/nixpkgs#318914]
### Describe the bug
When running FFXIV through XIVLauncher when your Mesa version is 24.0.7 on an Intel Arc GPU it appears that certain duties cause the game to crash

### Steps To Reproduce
1. Have a Intel Arc GPU
2. Run FFXIV Through XIVLauncher as normal
3. Queue for the duty "The Dead Ends" seems to pretty consistently cause the crash within the first few secs.

### Expected behavior
The game runs as normal

### Additional context
The error in the console that shows up in a couple variations, but the reason for the error is always the same:
```
err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
```
It is always ``` VK_ERROR_DEVICE_LOST ```

And ocasinally the game runs long enough to invoke an error:
```
a fatal directx error has occurred 11000001
```
There are a couple variations of this error, but they all seem related and have been an issue since the Stormblood Expansion and might be a bug in the game itself that the devs have yet to fix.

I will also be making a bug report on the Mesa project. I am mostly wondering if temporarily if Mesa 23.1.9 could be packaged with XIVLauncher for the time being or if another fix is feasible.

### Notify maintainers
@witchof0x20 
@wegank 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-xanmod1, NixOS, 24.05 (Uakari), 24.05.1135.9b5328b7f761`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05, nixos-prev-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-xanmod1, NixOS, 24.05 (Uakari), 24.05.1135.9b5328b7f761`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05, nixos-prev-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thyTwilightGoth** [comment]
Mesa Project Bug Report (Link might not work for whatever reason): [https://gitlab.freedesktop.org/mesa/mesa/-/issues/11314](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11314)

**Comment by Alanazane** [comment]
My brother has been experiencing a very similar crash for a while now across different duties with his Arc a750 on both nobara and NixOS (this doesn't seem to be at all specific to NixOS).
While trying to investigate this I did find this potentially similar i915 kernel driver [issue](https://gitlab.freedesktop.org/drm/i915/kernel/-/issues/10549) with the same ecode we had `i915 0000:03:00.0: [drm] GPU HANG: ecode 12:1:85dff5fb.`
