### ISSUE TITLE
rustc: package build troubles

### ISSUE THREAD

**Issue by akru** [NixOS/nixpkgs#31896]
## Issue description

I try to build [parity](https://github.com/airalab/airalab-channels/blob/nixos-unstable/pkgs/applications/altcoins/parity/beta.nix) package with latest rust & cargo but have troubles in build stage:

```
building path(s) ‘/nix/store/7f6pm324bwnq69lwmq8m19cm43cbimgv-parity-1.8.3’
unpacking sources
unpacking source archive /nix/store/kr5andf56d7ishrzl2520c2bz5vf9jb8-source
source root is source
patching sources
configuring
building
Running cargo build --release
error: failed to load source for a dependency on `serde_derive`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to update replaced source `registry https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to decode `.cargo-checksum.json` of bn v0.4.4

Caused by:
  invalid type: unit value, expected a string at line 1 column 1899
builder for ‘/nix/store/b3579h9x9pc4akz7798hyb9339ra0617-parity-1.8.3.drv’ failed with exit code 101
error: build of ‘/nix/store/b3579h9x9pc4akz7798hyb9339ra0617-parity-1.8.3.drv’ failed
```

In my opinion vendorizing stage is broken cause [my port](https://github.com/airalab/airalab-channels/commit/39efddbc1bcf44b2f1f1b85eb840f7767d2418a8) to latest rust & cargo version works.

### Steps to reproduce

```bash
$ git clone https://github.com/airalab/airalab-channels
$ cd airalab-channels
$ nix-build -A parity-beta
```

## Technical details

 - system: `"x86_64-linux"`                                                                                                            
 - host os: `Linux 4.9.61, NixOS, 18.03pre120540.b8f7027360 (Impala)`                                                                  
 - multi-user?: `yes`                                                                                                                  
 - sandbox: `no`                                                                                                                       
 - version: `nix-env (Nix) 1.11.15`                                                                                                    
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`                                                                                 
 - channels(akru): `"aira"`                                                                                                            
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by yrashk** [comment]
I have the same issue.

**Comment by ckauhaus** [comment]
The error is hard to reproduce for an outsider. I cloned to repo and tried it on current master, but it started to compile rustc from scratch which is definitively not the case for vanilla master. I think there is too much going on in airalab-channels.

Please try to provider a smaller example that reproduces the error precisely.

An improved bug report will help the maintainers to fix the problem. Thanks :-)

**Comment by akru** [comment]
Fixed by package source patch in https://github.com/NixOS/nixpkgs/pull/34441
