### ISSUE TITLE
lua dependencies not seen for vim plugins built with buildNeovimPlugin

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#318925]
### Describe the bug

Neovim does't see the dependencies of some plugins, for instance luasnip and jsregexp and reported here https://github.com/NixOS/nixpkgs/pull/311386 and  https://github.com/NixOS/nixpkgs/issues/306367 (there are other occurrences that we can link to this ticket).

### Steps To Reproduce
add luasnip to neovim plugins and notice that checkhealth warns about missing jsregexp.

### Expected behavior
No warning

### Additional context
I solved the problem locally some time ago by creating a lua env with the closure of all vim plugins but it's not upstreamable IMO, not efficient nor clean.
I started writing a test to see how it worked on master and saw jsregexp was loaded into the packpath as a lua plugin. That's because of https://github.com/NixOS/nixpkgs/pull/311386 and is a red herring.
My current plan is:
1. to customize  vimUtils.packDir to aggregate the different propagated-build-inputs from the various plugins
2. and call `addToLuaPath` (a variant I have that loads propagatedBuildInputs as well) on the packpath dir.
3. wrap neovim with LUA_PATH and LUA_CPATH generated by this call.

NB: https://github.com/NixOS/nixpkgs/pull/311386 made me realize that packDir will pull transitive deps in the packdir regardless of if they are vim plugins. I think we should only include vim plugins in the closure to avoid mistakes but I will let that for the future as it could break stuff.

### Notify maintainers
cc @teto

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
Current attempt https://github.com/NixOS/nixpkgs/pull/319325

**Comment by BirdeeHub** [comment]
Isn't this what the extraLuaPackages option is for?

**Comment by teto** [comment]
fixed now that the PR reaches nixos-unstable \o/
The listing of propagatedbuildinputs in the packpath dir lets us wrap neovim with plugin executable dependencies too though that's not done yet.

**Comment by BirdeeHub** [comment]
https://github.com/lovesegfault/nixpkgs/blob/9b2e62243919d17b76d7a708e691cf4086e78802/pkgs/applications/editors/vim/plugins/overrides.nix

So to clarify, we can add propagatedBuildInputs into these now? or do we just put them in the normal dependencies key and it figures out whats a library and whats a plugin?

**Comment by teto** [comment]
for now it just wraps lua libraries
https://github.com/NixOS/nixpkgs/blob/56d6da9252d433938ad9ae53b7c50f8bab10482e/pkgs/applications/editors/neovim/wrapper.nix#L174
but one could wrap executables, python dependencies etc. Just a matter of reading the propagated-build-inputs file in finalPackdir and select what we want to wrap.

**Comment by BirdeeHub** [comment]
Im just trying to figure out how a plugin author would go about declaring these. Would you just put it in dependencies in overrides.nix? [So, this dependencies list is what is added to propagated-build-inputs?](https://github.com/teto/nixpkgs/blob/665f3f694bfc6c2f3a95a98b1abf71d2961879bb/pkgs/applications/editors/vim/plugins/overrides.nix#L868-L870)

Or is jsregexp also declared somewhere else as a propagatedBuildInput and thats just extra?

**Comment by BirdeeHub** [comment]
I agree that being able to specify required binaries and libraries for plugins in nixpkgs that would then properly be wrapped is very cool, after all I made an entire framework where thats a large part of why it exists. But if every single one is also getting added to the packpath that feels a little messy, hence the question, can we use propagatedBuildInputs in those overrides instead so that they can still be resolved via this mechanism without ending up in the packDir

**Comment by BirdeeHub** [comment]
Tested it out. You can in fact add it to propagatedBuildInputs instead of dependencies and it still works.

Maybe I can go through and move all the non-plugin dependencies in the dependencies lists in that file into propagatedBuildInputs so that they no longer show up in that packDir? or would that make vim users mad?
