### ISSUE TITLE
Build failure: nanoflann

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#319037]
### Steps To Reproduce

1. build `nanoflann`

### Build log

https://gist.github.com/SomeoneSerge/a7d7908d266db9e6db5027504c93f2f4

```
/build/source/include/nanoflann.hpp:358:29: error: 'uint32_t' does not name a type
  358 |     typename AccessorType = uint32_t>
      |                             ^~~~~~~~
/build/source/include/nanoflann.hpp:53:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   52 | #include <functional>
  +++ |+#include <cstdint>
   53 | #include <istream>
...
/build/source/examples/pointcloud_adaptor_example.cpp:102:9: error: template argument 4 is invalid
/build/source/examples/pointcloud_adaptor_example.cpp:106:5: error: 'my_kd_tree_t' was not declared in this scope
  106 |     my_kd_tree_t index(3 /*dim*/, pc2kd, {10 /* max leaf */});
      |     ^~~~~~~~~~~~
/build/source/examples/pointcloud_adaptor_example.cpp:106:61: error: expected primary-expression before ')' token
  106 |     my_kd_tree_t index(3 /*dim*/, pc2kd, {10 /* max leaf */});
      |                                                             ^
/build/source/examples/pointcloud_adaptor_example.cpp:107:5: error: 'index' was not declared in this scope
  107 |     index.buildIndex();
```

### Additional context

- Nanoflann (including 1.5.5) doesn't seem to support gcc13?
- Blocker for https://github.com/NixOS/nixpkgs/pull/256115 / https://github.com/NixOS/nixpkgs/pull/224262

### Notify maintainers

@AndersonTorres 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
f53d6a0d9e0b1c0183782cb3264f4d8c5a52225a
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
Oh, I was wrong, there's no issue in 1.5.5: the alice-vision PR overrides nanoflann's src to 1.4.X

**Comment by adisbladis** [comment]
Nanoflann builds just fine on master & releases.
