### ISSUE TITLE
Package request: Safing.io

### ISSUE THREAD

**Issue by ajmasia** [NixOS/nixpkgs#319023]
**Project description**
Portmaster is a free and open-source application firewall that does the heavy lifting for you. Restore privacy and take back control over all your computer's network activity. 

**Metadata**

* homepage URL: https://safing.io/ 
* source URL: https://github.com/safing
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...
* other: https://wiki.safing.io/en/Portmaster/Install/Linux#manual-install-and-launching

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Duplicate:
https://github.com/NixOS/nixpkgs/issues/242409
https://github.com/NixOS/nixpkgs/issues/227913
https://github.com/NixOS/nixpkgs/issues/174194

There is this PR which is still in draft:
https://github.com/NixOS/nixpkgs/pull/264454
