### ISSUE TITLE
dependency missing in python312Packages.remi

### ISSUE THREAD

**Issue by lutzberger** [NixOS/nixpkgs#319021]
Using python312Packages.remi, the error comes:

 File "/nix/store/14xscarxvgxya6bqmf79bwxg5221f5pw-python3.12-remi-2022.7.27/lib/python3.12/site-packages/remi/__init__.py", line 34, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

the python package pkg_resources is not in nix available in nix. Dependency is missing.

**Comment by wegank** [comment]
I've transferred the issue to NixOS/nixpkgs/issues/319021, since it's not really about the web interface, but rather a packaging issue.

**Comment by zoechi** [comment]
Looks similar to #316531 
Perhaps it can be fixed with the same approach.

**Comment by lutzberger** [comment]
indeed, it is the same problem.
