### ISSUE TITLE
python3Packages.tuya-device-sharing-sdk: Discuss downgrade to version 0.1.9

### ISSUE THREAD

**Issue by pathob** [NixOS/nixpkgs#319067]
Hi @aciceri @mweinelt

I would like to discuss the following issue with you.

## Issue description

The python library tuya-device-sharing-sdk is currently packaged as version 0.2.0 [(link)](https://github.com/NixOS/nixpkgs/blob/8f5f49d8ad22689611fcbb62b1a79124a35cf67d/pkgs/development/python-modules/tuya-device-sharing-sdk/default.nix#L12), and used only by the Home Assistant component "Tuya". This works because of the way nixpkgs is currently "allocating" dependencies for official Home assistant components [(link)](https://github.com/NixOS/nixpkgs/blob/8f5f49d8ad22689611fcbb62b1a79124a35cf67d/pkgs/servers/home-assistant/component-packages.nix#L4716), totally ignoring version constraints of the component itself [(link)](https://github.com/search?q=repo%3Ahome-assistant%2Fcore%20tuya-device-sharing-sdk&type=code).

I have packaged the custom component tuya-local with version 2024.5.2 for nixpks [(link)](https://github.com/NixOS/nixpkgs/blob/8f5f49d8ad22689611fcbb62b1a79124a35cf67d/pkgs/servers/home-assistant/custom-components/tuya_local/default.nix) that recently also added tuya-device-sharing-sdk as a dependency with a "hard constraint" on version 0.1.9 also [(link)](https://github.com/make-all/tuya-local/commit/8896547f6af5ea6f3252256e0dc94cc4e54aa983#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) and the change got released with version 2024.6.0. As far as I know I cannot make nixpkgs build tuya-local with the new version 2024.6.0 because of the version mismatch of the tuya-device-sharing-sdk dependency, at least not without patching the version constraints.

But in general, we should probably ask whether we really want to provide version 0.2.0 of the tuya-device-sharing-sdk library in nixpkgs. This version got "released" from a dev branch [(link)](https://github.com/tuya/tuya-device-sharing-sdk/tree/dev) and the maintainers of both, the official Tuya component and the custom tuya-local components obviously don't want to use this version.

My suggestion would be to downgrade the version to version 0.1.9 that is actually requested by its dependents.

What do you think? I'm willing to provide the PR.

Thanks!

**Comment by mweinelt** [comment]
Fine with me.

**Comment by aciceri** [comment]
I'm out of home these weeks so I will not be able to test it but your points seems reasonable, I'm perfectly fine with you sending a PR.

Jun 11, 2024 5:44:34 PM Patrick Hobusch ***@***.***>:
