### ISSUE TITLE
SearXNG service: "Special Queries" preferences page is blank

### ISSUE THREAD

**Issue by seangenabe** [NixOS/nixpkgs#319040]
### Describe the bug

The user's Special Queries preferences page is blank.

### Steps To Reproduce

1. Enable the searx service:

```nix
let
  port = 8999;
in
{
services.searx = {
  enable = true;
  settings = {
    server.port = port;
    server.secretkey = "notsosecretkey";
  }
};
}
```

### Expected behavior

The Special Queries page should be filled in.

![image](https://github.com/NixOS/nixpkgs/assets/5626884/c83f4fa7-c923-41fc-96e1-79c4342e6a7e)

### Screenshots

The empty Special Queries preferences page.
![image](https://github.com/NixOS/nixpkgs/assets/5626884/4d32b890-a15c-4a19-893a-39f0d87dd123)

### Additional context

While investigating this problem I noticed that the `lib/python3.11/site-packages/searx/answerers` directory is blank (save for `__init__.py` and `__pycache__`) while this directory should have something in [the same upstream commit](https://github.com/searxng/searxng/tree/18fb701be225560b3fb1011cc533f785823f26a4/searx/answerers). I'm not sure if this is related.

### Notify maintainers

@SuperSandro2000 @999eagle @rnhmjoj

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.26, NixOS, 24.11 (Vicuña), 24.11pre636273.051f920625ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(REDACTED): `"home-manager"`
 - channels(sean): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> While investigating this problem I noticed that the `lib/python3.11/site-packages/searx/answerers` directory is blank (save for `__init__.py` and `__pycache__`) while this directory should have something in [the same upstream commit](https://github.com/searxng/searxng/tree/18fb701be225560b3fb1011cc533f785823f26a4/searx/answerers). I'm not sure if this is related.

Good catch! I think they are missing the __init__.py. Let me test that out.
