### ISSUE TITLE
Build failure: rtl88x2bu

### ISSUE THREAD

**Issue by everypizza1** [NixOS/nixpkgs#319097]
### Steps To Reproduce

1. build rtl88x2bu

### Build log

[Gist (log very long)](https://gist.github.com/everypizza1/6cdffc843eb6d8175540f4a7f5d7dbd3)

### Additional context

None

### Notify maintainers

@otavio 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.05 (Uakari), 24.05.1135.9b5328b7f761`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by otavio** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/318297.
