### ISSUE TITLE
Termite: allow users to disable client-side decorations

### ISSUE THREAD

**Issue by mckinley-olsen-oc** [NixOS/nixpkgs#31906]
## Issue description
GTK+3 on Wayland does not allow disabling of client-side decorations. See [here](https://bugzilla.gnome.org/show_bug.cgi?id=776290)
It is possible, however, to manually configure GTK+3 applications to not be decorated; this would be a very useful option in Termite, where the inclusion of CSD looks quite noisy. See [example](https://bug776290.bugzilla-attachments.gnome.org/attachment.cgi?id=342245)
There should be a configuration option exposed to the user to disable the presence of client-side decorations.

### Steps to reproduce
Using a wayland window manager (e.g. Sway), run Termite and observe the decoration added above the main display area (See [example](https://bug776290.bugzilla-attachments.gnome.org/attachment.cgi?id=342245))

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03pre120398.aeff3080d0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120398.aeff3080d0"`
 - channels(me): `"nixos-18.03pre120540.b8f7027360"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by gnidorah** [comment]
Should be fixed once https://github.com/NixOS/nixpkgs/pull/31400 will go from staging to master and up to the channels

**Comment by colemickens** [comment]
This can be closed, I think, either via GTK features or new Wayland CSD protos.
