### ISSUE TITLE
Build failure: Obsidian

### ISSUE THREAD

**Issue by ArtemChandragupta** [NixOS/nixpkgs#319068]
### Steps To Reproduce

1. build *Obsidian*

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/3h85946vxpk5npnaqwd9fhcnl3dx3qbf-obsidian-1.6.3.tar.gz.drv':
         specified: sha256-Eq2cUXjp0XdVeR4t3oG2DUtsKOp3e3nPMMhznUc4BmE=
            got:    sha256-ho8E2Iq+s/w8NjmxzZo/y5aj3MNgbyvIGjk3nSKPLDw=
error: 1 dependencies of derivation '/nix/store/mw3s597jmh5vj246zv4a5j5ryd0js647-obsidian-1.6.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0hrzz3ysa17pzrbr02h7gv5f86cq1g97-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2z273dbkpwlzcckbbxfjlrf7zv6m474w-nixos-system-nixos-24.11.20240609.c7b821b.drv' failed to build
```

### Additional context

On nixpkgs unstable. Firstly encountered ten minutes ago or something.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240607.051f920`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3dr5pyja36lvvrszhzffww1jwyrx6i09-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jarrodsfarrell** [comment]
Until this is fixed, currently using this for my `home-manager` configuration. Translate as needed for system-level installs.
```nix
{ config, pkgs, lib, ... }:
let
  nixpkgs_24_05_stable = import (fetchTarball {
    name = "nixpkgs-24.05-stable";
    url = "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz";
    sha256 = "1lr1h35prqkd1mkmzriwlpvxcb34kmhc9dnr48gkm8hh089hifmx";
  }) {
    # If necessary
    config.allowUnfreePredicate = pkg:
      builtins.elem (lib.getName pkg) [
        "obsidian"
      ];
  };
in
{
  home.packages = with pkgs; [
    # ...
    nixpkgs_24_05_stable.obsidian
    # ...
  ];
}
```

**Comment by w-lfchen** [comment]
should be fixed by #318699

**Comment by s2514** [comment]
> Until this is fixed, currently using this for my `home-manager` configuration. Translate as needed for system-level installs.
> 
> ```nix
> { config, pkgs, lib, ... }:
> let
>   nixpkgs_24_05_stable = import (fetchTarball {
>     name = "nixpkgs-24.05-stable";
>     url = "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz";
>     sha256 = "1lr1h35prqkd1mkmzriwlpvxcb34kmhc9dnr48gkm8hh089hifmx";
>   }) {
>     # If necessary
>     config.allowUnfreePredicate = pkg:
>       builtins.elem (lib.getName pkg) [
>         "obsidian"
>       ];
>   };
> in
> {
>   home.packages = with pkgs; [
>     # ...
>     nixpkgs_24_05_stable.obsidia
>     # ...
>   ];
> }
> ```

Bless you I am very new to NixOS and programming this would have taken me ages to figure out on my own. I am not using home-manager I am on a fairly vanilla NixOS install with nixos-unstable enabled I had to define lib to get it to work in configuration.nix for some reason?
```
{ config, pkgs, ... }:

let
  # Import 32-bit packages
  i686Pkgs = import <nixpkgs> { system = "i686-linux"; };

  #temp obsidian workaround for nixos-unstable https://github.com/NixOS/nixpkgs/issues/319068
  nixpkgs_24_05_stable = import (fetchTarball {
    name = "nixpkgs-24.05-stable";
    url = "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz";
    sha256 = "1lr1h35prqkd1mkmzriwlpvxcb34kmhc9dnr48gkm8hh089hifmx";
  }) {
        #if needed
    config.allowUnfreePredicate = pkg:
      builtins.elem (lib.getName pkg) [
        "obsidian"
     ];
  };
  lib = nixpkgs_24_05_stable.lib;

in
{

    environment.systemPackages = with pkgs; [
        #other programs
        nixpkgs_24_05_stable.obsidian
        #other packages
];
```

Thanks again I really appreciate this you saved me a lot of time.

**Comment by l0b0** [comment]
A quick search didn't reveal an explanation, so I've [asked on their forum](https://forum.obsidian.md/t/was-the-1-6-3-tag-moved/83517).

**Comment by s2514** [comment]
> A quick search didn't reveal an explanation, so I've [asked on their forum](https://forum.obsidian.md/t/was-the-1-6-3-tag-moved/83517).
> 
> Does anyone have the original https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.3/obsidian-1.6.3.asar.gz for comparison?

I think they just changed the one line https://github.com/NixOS/nixpkgs/pull/318699/commits/2265a2fb24739a0c693da3ca16898c17ca855c5e

If I understand correctly they removed `hash = if stdenv.isDarwin then "sha256-o5ELpG82mJgcd9Pil6A99BPK6Hoa0OKJJkYpyfGJR9I=" else "sha256-Eq2cUXjp0XdVeR4t3oG2DUtsKOp3e3nPMMhznUc4BmE=";`

and changed it to `    hash = if stdenv.isDarwin then "sha256-o5ELpG82mJgcd9Pil6A99BPK6Hoa0OKJJkYpyfGJR9I=" else "sha256-ho8E2Iq+s/w8NjmxzZo/y5aj3MNgbyvIGjk3nSKPLDw=";`

which (again if I understand correctly) works on stable but isn't in unstable yet (w_ifchen posted how to check https://nixpk.gs/pr-tracker.html?pr=318699

**Comment by l0b0** [comment]
> I think they just changed the one line [2265a2f](https://github.com/NixOS/nixpkgs/commit/2265a2fb24739a0c693da3ca16898c17ca855c5e)

No, I meant why 1.6.3 changed *upstream*.

**Comment by pluiedev** [comment]
Looks like upstream just rereleased 1.6.3 to "deal with build problems related to electron." Honestly, they should just use a patch release for that — Semver exists for a reason...

**Comment by w-lfchen** [comment]
> A quick search didn't reveal an explanation, so I've [asked on their forum](https://forum.obsidian.md/t/was-the-1-6-3-tag-moved/83517).
> 
> Does anyone have the original https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.3/obsidian-1.6.3.asar.gz for comparison?

i probably still have it in my nix store somewhere

**Comment by skoove** [comment]
im still new to nix so sorry if its silly, can i exclude something from being built? i need to rebuild but obsidian is stopping everything from being built

**Comment by s2514** [comment]
> @s2514 regarding your first question about `lib`: note the first line `{ config, pkgs, lib, ... }:` this is a function head and therefore declares its arguments, here we have one argument which is a set that has to contain the entries `config`, `pkgs` and `lib` (the `...` means there may be be more entries in the set that will be passed as an argument to the function, but those are ignored) since your first line is missing the `lib` in the argument set, you didn't have `lib` in scope your `let-in`-block works, as you are now extracting the `lib` from you `nixpkgs_24_05_stable` binding. this is fine here, but you might want to add lib to the arguments so that you don't have to concern yourself with where you get it from as nix will then automatically take care of that for you
> 
> regarding your second message (and a bit more): you are correct in your assessment about what changed! obsidian released version 1.6.3 (this was updated in #318054) and since it's closed-source, we use their release tarballs when packaging it. The cause of a bit of confusion and this issue is the fact that due to build issues, the tarball has been changed which caused its hash to be different (this is exactly what hash functions are supposed to do, you can read up on the basics of them [here](https://en.wikipedia.org/wiki/Hash_function), they are an important thing in computer science, generally speaking. since nix values reproducibility a lot, we use a hash that is not solely based on the tarball itself (it's a bit more complicated) to determine whether a build input has changed. since this is the case here, the hash had to be updated, which happened in #318699. to be precise, it happened in commit [2265a2f](https://github.com/NixOS/nixpkgs/commit/2265a2fb24739a0c693da3ca16898c17ca855c5e) which you correctly deduced, this commit was requested to be merged into master with the accompanying pull request (this can be seen at the top). however, most users of nix don't target the master branch. doing so would mean that you'd have to build every program from source which you don't want to do. the nix foundation offers a service called [hydra](https://github.com/NixOS/hydra) which periodically builds all packages. the status can be observed [here](https://hydra.nixos.org), but it's very confusing due to its complexity, this is why tools such as https://nixpk.gs exist, where you can simply check how the status of a given pull request is. if a pull request has made it into nixos-unstable, that means that whatever it changed it is available from the nixos foundation binary cache so that you don't have to build it yourself. once the pr has made it into nixos-unstable, you'll simply have to update your channel and if you then rebuild your system, you'll have an updated and working version of obsidian!
> 
> i hope this explanation was helpful, of course there is way more to pretty much every part of this, but i've tried to connect the important bits to your questions and to give a baseline understanding of the things that have happened here. if there are any questions left, feel free to ask. we're always happy about new people being interested in this amazing project, no matter how immensely complex everything may seem at a first glance. i sincerely hope you were able to learn something from this admittedly lengthy text, that you'll have a good time learning nix and that you have a nice day ❤️

Thank you for taking the time to explain this!  I didn't notice that lib wasn't declared in my config that makes more sense.

For the hash, can you explain and/or direct me to a resource for understanding how nix generates the hash? I thought it used a has of the tarball but now I think my understanding there is incomplete.

As for what happened I want to check my understanding. Are you saying that the reason it broke was because a change was made to obsidian 1.6.3 which changed the hash, you created this pr with the updated hash about an hour later (thanks for that too btw that was fast as hell), and now people on every branch besides nixos-unstable are able to get it because the binaries haven't been compiled for the new hash yet on nixos-unstable?

**Comment by nyanotech** [comment]
For understanding how nix hashes things, the place to start is probably [here](https://nixos.wiki/wiki/Nix_Hash).

> As for what happened I want to check my understanding. Are you saying that the reason it broke was because a change was made to obsidian 1.6.3 which changed the hash, you created this pr with the updated hash about an hour later

exactly; normally people wouldn't push an updated copy of something over an existing version (as opposed to bumping the version number to go with it).

and, well, I wasn't deliberately fast, I just happened to pick that time to bump my machine up to nixpkgs master, and then ran into the hash mismatch error, and started digging from there; wrong place at the right time 😛 

> and now people on every branch besides nixos-unstable are able to get it (because the binaries haven't been compiled for the new hash yet on nixos-unstable?)

Someone earlier had linked https://nixpk.gs/pr-tracker.html?pr=318699 which shows the unstable branches, but there's also the branches and associated channels for, eg, non-unstable nixos, which I think are typically updated separately (if they're updated at all, rather than waiting for the next nixos version).

**Comment by w-lfchen** [comment]
> and now people on every branch besides nixos-unstable are able to get it (because the binaries haven't been compiled for the new hash yet on nixos-unstable?)

the other branches are still working because the versions there are older, the unstable branches are the most up-to-date branches that are built by hydra.
1.6.3 is currently only available on unstable since it has not been backported into a stable release

**Comment by w-lfchen** [comment]
fix is now in nixos-unstable
