### ISSUE TITLE
sqlitebrowser fails to start in nix-shell

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#31913]
## Issue description

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted

```

### Steps to reproduce

`nix-shell -p sqlitebrowser --run sqlitebrowser`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.0, NixOS, 18.03pre120398.aeff3080d0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120398.aeff3080d0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bjornfor** [comment]
I think this is a common/known issue with the current Qt packaging in nixpkgs.

**Comment by orivej** [comment]
Yes, this is #30551. There is a workaround and the description of the cause, but no solution yet.
