### ISSUE TITLE
gwe: NV-CONTROL X extension not found

### ISSUE THREAD

**Issue by atimofeev** [NixOS/nixpkgs#319117]
### Describe the bug
I have nvidia-prime system, with working `nvidia-settings` (though pretty bare-bones), `nvidia-offload` command, and games are even automatically launched on dGPU, but `gwe` app fails to run.

I've also tried legacy drivers (470), but got very bad desktop performance with no changes to this issue.

### Steps To Reproduce
1. Apply this config:
```nix
  environment.systemPackages = with pkgs; [ nvtopPackages.full gwe glxinfo ];
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    nvidiaSettings = true;
    modesetting.enable = true;
    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };
```
2. Launch `gwe`.

### Expected behavior
`gwe` launches without errors

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/39891735/671fa86e-7e6e-42e0-b949-62b68190de18)

### Additional context

I'm using Gnome 46.2 on Wayland.

Example of working nvidia-offload:
```console
❯ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
❯ nvidia-offload glxinfo | grep "OpenGL renderer"
OpenGL renderer string: NVIDIA GeForce MX150/PCIe/SSE2
```

### Notify maintainers

@IvarWithoutBones 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3-zen1, NixOS, 24.05 (Uakari), 24.05.20240606.9b5328b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/x887lkxvgnrrcfgrzz351qhfvvrkm80x-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by atimofeev** [comment]
Similar issue in https://github.com/NixOS/nixpkgs/issues/187543

**Comment by atimofeev** [comment]
https://gitlab.com/leinardi/gwe/-/issues/133 

Can't reproduce this on X11, must be Wayland-exclusive issue,

**Comment by thunze** [comment]
I don't think GWE even supports Wayland yet.

https://gitlab.com/leinardi/gwe/-/issues/125
https://gitlab.com/leinardi/gwe/-/merge_requests/80

**Comment by atimofeev** [comment]
Indeed, not a nix issue here.
