### ISSUE TITLE
KCM Modules Unable to Open Directly From Plasma 6 Application Launcher or KRunner after KDE Frameworks 6.3.0 Update

### ISSUE THREAD

**Issue by HippieMitch** [NixOS/nixpkgs#319184]
### Describe the bug
After the KDE Frameworks 6.3.0 update, I can no longer launch kcm modules by searching for them in Application Launcher or KRunner.  I can open them directly with "systemsettings kcm_about-distro" in a terminal with no issues.  I can also access them by opening systemsettings first and then clicking the particular kcm module I'm trying to access.  I'm having issues getting any usable information about this bug because it launches successfully through the terminal.  If this is upstream please let me know and I'll submit this over on the KDE Bugtracker.

### Steps To Reproduce
1. Log in to KDE Plasma 6.
2. Press the Meta key and type "About This System" and hit enter.
3. Observe that the systemsettings icon shows in task manager and then closes after a few seconds.  Nothing is launched.

### Expected behavior
I press the Meta key, type "About This System", hit enter, and see the kcm_about-distro module load displaying information about the system.

### Notify maintainers
@ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000 @ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240609.c7b821b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/rljkm6h18fjvavm6l17jiil8glphc44f-source`
```

---

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/319299

**Comment by HippieMitch** [comment]
Sorry, I've been crazy busy at work.  I just got to test this myself and it did work in my case as well. Thanks for the quick update!
