### ISSUE TITLE
Update request: systemd 255.6 → 256.2

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#319328]
- Package name: [systemd](https://systemd.io/)
- Latest released version: [256.2](https://github.com/systemd/systemd/releases/tag/v256.2)

- Current version on the unstable channel: [255.6](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/systemd/default.nix#L887)
- Current version on the stable/release channel: [255.6](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/os-specific/linux/systemd/default.nix#L887)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by flokli** [comment]
See https://github.com/NixOS/nixpkgs/pull/307068
