### ISSUE TITLE
Update request: tokyonight-gtk-theme unstable-2023-05-31 → unstable-2024-06-12

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#319382]
- Package name: tokyonight-gtk-theme
- Latest released version: unstable-2024-06-12

- Current version on the unstable channel: unstable-2023-05-31
- Current version on the stable/release channel: unstable-2023-05-31

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Madouura @garaiza-93 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by D3vil0p3r** [comment]
@luftmensch-luftmensch can you give a look also to this? It is pretty similar to gruvbox theme.

**Comment by luftmensch-luftmensch** [comment]
> @luftmensch-luftmensch can you give a look also to this? It is pretty similar to gruvbox theme.

I'll give it a try, but I think there will be some things to do on the derivation since the overall structure of the repository has changed since the last update

**Comment by D3vil0p3r** [comment]
@luftmensch-luftmensch any news?

**Comment by Frontear** [comment]
Interesting, and the updateScript doesn't work either.

**Comment by greed-d** [comment]
Any update on this?

**Comment by mrgiles** [comment]
This package has been updated in [PR#326675](https://github.com/NixOS/nixpkgs/pull/326675)
