### ISSUE TITLE
Update request: lief 0.13.2 → 0.14.1

### ISSUE THREAD

**Issue by gmacon** [NixOS/nixpkgs#319358]
- Package name: lief
- Latest released version: 0.14.1

- Current version on the unstable channel: 0.13.2
- Current version on the stable/release channel: 0.13.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Lassulus @GenericNerdyUsername 

I briefly looked at this at work; I discovered that the build system has changed in 0.14. It's now PEP-517 and uses the scikit-build-core to create a custom backend.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jfvillablanca** [comment]
Closing since the package is already updated. As of writing, this is the latest commit: d465c58549dc4
