### ISSUE TITLE
btrfs-assistant failed to use in nix-shell

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#319577]
### Describe the bug

btrfs-assistant failed to use in nix-shell

### Steps To Reproduce

```
$ nix-shell -p btrfs-assistant                                                                                                       1 ↵
wrapQtAppsHook qtHostPathHook: qtPluginPrefix is unset. hint: add qt6.qtbase to buildInputs
bash: qtPluginPrefix: parameter null or not set
```

### Expected behavior

nix-shell should success

### Notify maintainers

@khaneliman 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"                                                                                      1 ↵
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240605.cb86704`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/7dp7c6j1yxl28m41cn3s9y3ni20x69yq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment]
I fixed the nix-shell -p error but the application doesn't run properly. Looking into if we need to do some env variable nonsense because of the way the application works.
