### ISSUE TITLE
Package request: nodePackages.pgraphs

### ISSUE THREAD

**Issue by aphelionz** [NixOS/nixpkgs#319584]
**Project description**

This package implements parsers and serializers to convert between labeled property graph formats and databases. For example, I'm trying to transliterate a JSONCanvas file from Obsidian to other formats.

Thank you!

**Metadata**

* homepage URL: https://www.npmjs.com/package/pgraphs#json-canvas
* source URL: https://github.com/pg-format/pgraphs
* license: MIT
* platforms: NodeJS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Note for packagers: `buildNpmPackage` with `pkgs/by-name` should be preferred over `nodePackages`.
