### ISSUE TITLE
Build failure: dosbox-staging-0.81.1 (aarch64-darwin)

### ISSUE THREAD

**Issue by matteo-pacini** [NixOS/nixpkgs#319617]
### Steps To Reproduce

- Checkout `nixpkgs` at `release-24.05` on a `aarch64-darwin` system.
- `nix-build -A dosbox-staging`

OR 

`nix shell nixpkgs#dosbox-staging`

(Tested also on `master`, same issue)

### Build log

```
[...]
Found pkg-config: YES (/nix/store/b5hlaiv3vg8qgr3vhsw78cjh5s2zrph9-pkg-config-wrapper-0.29.2/bin/pkg-config) 0.2>
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency atomic found: NO (tried pkgconfig, framework and cmake)
Checking if "compiler supports atomic types using external library" with dependency atomic: links: YES
Library dl found: YES
Library stdc++fs found: NO
Dependency threads found: YES unknown (cached)
Run-time dependency iir found: YES 1.9.4
Run-time dependency opusfile found: YES 0.12

meson.build:674:15: ERROR: Automatic wrap-based subproject downloading is disabled
```

### Additional context

N/A

### Notify maintainers

@AndersonTorres @JoshuaFern 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ofalvai** [comment]
I see this is no longer relevant on `aarch64-darwin`, but noticed that `x86_64-darwin` still fails to build, so I made a fix: https://github.com/NixOS/nixpkgs/pull/353160
