### ISSUE TITLE
Sunshine package typo

### ISSUE THREAD

**Issue by Garulf** [NixOS/nixpkgs#319686]
I was debugging an issue I was having using the sunshine package on the unstable branch where I may have encountered an unintended typo.

Might be related to: https://github.com/NixOS/nixpkgs/issues/305891

https://github.com/NixOS/nixpkgs/blob/57d6973abba7ea108bac64ae7629e7431e0199b6/pkgs/servers/sunshine/default.nix#L51

**Comment by eclairevoyant** [comment]
* what is the typo?
* what issue are you facing?

**Comment by Garulf** [comment]
Sorry I was corrected the `'` character on stdenv is intentional. Closing.
