### ISSUE TITLE
Wine crashes on opengl/direct3d apps when using proprietary nvidia driver

### ISSUE THREAD

**Issue by xzfc** [NixOS/nixpkgs#31989]
## Issue description

May be related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766028 (same symptom: crashes on opengl/direct3d apps, but does not crash when using strace).

### Steps to reproduce

My `configuration.nix`: https://pastebin.com/raw/KwrG7C9K

```bash
nix-shell -p wine wget
# I've using Win32 version of glxgears as sample app
wget http://www2.cs.uidaho.edu/~jeffery/win32/wglgears.exe
wine wglgears.exe
```

Then the window "The program wglgears.exe has encountered a serious problem and needs to close" appears. Program Error Details: https://pastebin.com/raw/5LUiviA6.

### Does not reproduce on

- `strace wine wglgears.exe`
- `gdb --batch wine -ex 'run wglgears.exe'`
- `wine wglgears.exe` using nouveau driver
- `wine wglgears.exe` with intel video driver (another machine)
- running gvim using wine
- native `glxgears`

## Technical details
Output of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03pre120540.b8f7027360 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - channels(alice): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
Doesn't reproduce for me, with binary nvidia drivers on nixos 18.03 (somewhere) + wine-2.0.2.

**Comment by xzfc** [comment]
After some research I've found that Archlinux recently have same problem and it was fixed by removing `-z,now` from LDFLAGS.
https://bugs.winehq.org/show_bug.cgi?id=43530#c24
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/wine&id=ada0c32d9441c4857e789ad2bb3a0d7e1198b849

Fixed for me by adding `hardeningDisable = [ "bindnow" ];` ([patch](https://github.com/xzfc/nixpkgs/commit/04f33baba121e0fc790579c74607bf775c2d596c)). Tested only `wineUnstable`.

**Comment by jcumming** [comment]
Works for me! Thanks for tracking this down @xzfc .
