### ISSUE TITLE
Documentation: sec-pkgs.makeSetupHook-usage-example unclear

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#320047]
## Problem

The [makeSetupHook-usage-example](https://nixos.org/manual/nixpkgs/unstable/#sec-pkgs.makeSetupHook-usage-example) in the nixpkgs manual has this example:
https://github.com/NixOS/nixpkgs/blob/6ac8e043110f12bdf1c315e478cd9cf3d50f5987/doc/build-helpers/special/makesetuphook.section.md?plain=1#L17-L28
But it isn't clear how this is supposed to be used. `propagatedBuildInputs` suggests that the hook is self-contained in its dependency, but this example fails to build:

```nix
{ pkgs ? import <nixpkgs> { } }:

let
  inherit (pkgs) writeScript;
  myHook = pkgs.makeSetupHook {
      name = "run-hello-hook";
      propagatedBuildInputs = [ pkgs.hello ];
      substitutions = { shell = "${pkgs.bash}/bin/bash"; };
  } (writeScript "run-hello-hook.sh" ''
      #!@shell@
      hello
  '');
in
  pkgs.stdenv.mkDerivation {
    name = "foobar-test";
    dontUnpack = true;
    nativeBuildInputs = [ myHook ];
    dontBuild = true;
    installPhase = ''
      echo "foobar" > $out
    '';
  }
```
With `hello: command not found`

@Artturin 

## Proposal

Give a minimal example usage of it.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/320107
