### ISSUE TITLE
Update request: papers 45.0-unstable-2024-03-27 → 46.1

### ISSUE THREAD

**Issue by nadir-ishiguro** [NixOS/nixpkgs#320048]
- Package name: papers
- Latest released version: 46.1

- Current version on the unstable channel: 45.0-unstable-2024-03-27
- Current version on the stable/release channel: 45.0-unstable-2024-03-27

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

Sorry for pinging so many people, but the gnome team is listed as maintainers and I didn't just want to randomly pick one.

@Jo-Blade @bobby285271 @hedning @jtojnar @dasj19

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
Should be resolved when #320100 is merged.
