### ISSUE TITLE
git-annex does't work if git is not in the path

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#32011]
## Issue description
If you have installed git-annex but didn't install git, then git-annex doesn't work correctly:
```
$ git-annex info
git-annex: git: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
Even though there is little reason to use git-annex without git, the [git-annex assistant](https://git-annex.branchable.com/assistant/) may be such a use case.
I guess we need to patch the git-annex source to call `${git}/bin/git` instead of `git`, e.g. in [Git/Command/Batch.hs](https://git.kitenet.net/index.cgi/git-annex.git/tree/Git/Command/Batch.hs).

I discovered this while working on #30411.
There, the problem seems to disappear when I add `gitMinimal` to `propagatedBuildInputs`, which I don't understand since this can't magically patch git-annex.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 18.03pre120540.b8f7027360 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - channels(rschuetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dotlambda** [comment]
If someone could at least tell me whether this is expected behaviour or indeed a bug, I could try to work on fixing it.
@mdorman @peti @nc6

**Comment by peti** [comment]
This is expected behavior.

**Comment by FRidh** [comment]
> This is expected behavior.

Do we want it to lookup `git` from `PATH`? If so, why? Why not patch it to point directly to `git`? The reason I am asking is because of #32167. If a Python package depends on `git-annex`, but `git-annex` does a `PATH` lookup to find `git`, then there is no way of packaging a Python *module* that includes a hard reference to `git`.

**Comment by peti** [comment]
> Do we want it to lookup git from PATH? If so, why?

We have different variants of `git` and there's no one obvious choice that should be hard-coded. So far, the absence of a hard-coded path hasn't been an issue. People who install `git-annex` usually install `git`, too.

> If a Python package depends on `git-annex`, but `git-annex` does a `PATH` lookup to find `git`, then there is no way of packaging a Python *module* that includes a hard reference to `git`.

You could depend on a version of git-annex has a wrapper script to configure `$PATH` in such a case. You could also patch the python module to expose the hard-coded `git` version in `$PATH`.

**Comment by FRidh** [comment]
> You could depend on a version of git-annex that has a wrapper script to configure $PATH in such a case. 

@dotlambda this is indeed a workable solution for #32167

**Comment by dotlambda** [comment]
I don't see any advantage over putting `gitMinimal` into `propagatedBuildInputs`.
