### ISSUE TITLE
libvirt KVM guest stopped working after upgrade to `nixos-24.05`

### ISSUE THREAD

**Issue by fedeinthemix** [NixOS/nixpkgs#320215]
### Describe the bug
I'm using a windows 11 guest created and launched via `virt-manager`.  The VM works fine on nixos-23.11, but after upgrade to nixos-24.05 the VM doesn't boot anymore. When I launch it, the console remains black with no messages and virt-manager shows a high CPU activity.

Here my virtualization configuration
```nix
{ config, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    virt-manager
    virt-viewer
    spice spice-gtk
    spice-protocol
    win-virtio
    win-spice
    virtiofsd
  ];

  virtualisation = {
    libvirtd = {
      enable = true;
      qemu = {
        swtpm.enable = true;
        ovmf.enable = true;
        ovmf.packages = [ pkgs.OVMFFull.fd ];
      };
    };
    spiceUSBRedirection.enable = true;
  };
  services.spice-vdagentd.enable = true;
}
```

### Notify maintainers
@fpletz @globin @lovesegfault 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.05 (Uakari), 24.05.1409.cc54fb41d137`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(beffa): `""`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fedeinthemix** [comment]
According to https://www.libvirt.org/news.html this may have been fixed in 10.2 and 10.3.

**Comment by ccat3z** [comment]
It may caused by a change in ovmf. After resetting nvram by deleting `/var/lib/libvirt/qemu/nvram/*.fd` everything works fine on my host.

**Comment by fedeinthemix** [comment]
That's it! Thank you very much.

**Comment by Lindenk** [comment]
I'm having the same issue and clearing the nvram doesn't seem to change anything

**Comment by MisguidedEmails** [comment]
> I'm having the same issue and clearing the nvram doesn't seem to change anything

Similar here. It also only seems to occur with `OVMFFull` and not the regular `OVMF` package. If you build the package without SecureBoot support it seems to work fine. I haven't troubleshooted further to see if it's my machine/setup, an upstream problem, or nixpkgs-specific yet
