### ISSUE TITLE
Package request: vscode-extensions.sdras.night-owl

### ISSUE THREAD

**Issue by pladypus** [NixOS/nixpkgs#320240]
**Project description**

A VS Code theme for the night owls out there. Now introducing Light Owl theme for daytime usage. Decisions were based on meaningful contrast for reading comprehension and for optimal razzle dazzle. ✨

**Metadata**

* homepage URL: https://open-vsx.org/extension/sdras/night-owl
* source URL: https://github.com/sdras/night-owl-vscode-theme
* license: mit
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
Have a look in:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/

Read the README.md:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/README.md

Edit:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/extensions/default.nix

Build as:

> nix build .#vscode-extension.publisher-name.extension-name

**Comment by superherointj** [comment]
> I'm getting stuck on the value for `hash` that I'm suppose to use. Based on the other extensions I'm confident I'm not just using the commit hash but I'm not sure where the sha256 values are coming from. Do you have any additional information on this?

When you try to build it will generate the hash for you, so you copy and paste it.

(What you have to do is just to erase the hash so it gets recomputed.)

**Comment by superherointj** [comment]
@pladypus Did it work for you? In case yes, consider upstreaming.
