### ISSUE TITLE
marble virtual globe fails to start due to problem with Qt plugin

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#32025]
## Issue description

I installed marble by putting the package into the "packages" section of my unprivileged user account, then tried to start marble, and got the following error:
> This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
> Reinstalling the application may fix this problem.
fish: “marble-qt” terminated by signal SIGABRT (Abort)

Installing marble system wide by adding it to environment.systemPackages fixed the issue. 

### Steps to reproduce

Add marble to packages section of an (unprivileged) user, but not to systemPackages. 
Start marble (from console in my case). 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.0, NixOS, 18.03pre120540.b8f7027360 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by orivej** [comment]
I'm sorry that you have encountered this problem, you can find the description of the cause and some workarounds at the end of #30551, subscribe to that issue to be notified of the solution.
