### ISSUE TITLE
Update request: xen 4.15.1 → 4.18.1

### ISSUE THREAD

**Issue by Orisphera** [NixOS/nixpkgs#320335]
- Package name: xen
- Latest released version: 4.18.1

- Current version on the unstable channel: 4.15.1
- Current version on the stable/release channel: 4.15.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@radhus
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TanvirOnGH** [comment]
@Orisphera Can you please update the title to this `Update request: xen 4.15.1 → 4.18.1`

**Comment by radhus** [comment]
@Orisphera sorry, not using Xen anymore. Too much of an hassle to keep up-to-date :cry:

**Comment by SigmaSquadron** [comment]
You're in luck! #324693
