### ISSUE TITLE
Update request: spacedrive 0.2.14 → 0.3.1

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#320338]
- Package name: spacedrive
- Latest released version: [0.3.1](https://github.com/spacedriveapp/spacedrive/releases/tag/0.3.1)

- Current version on the unstable channel: 0.2.14
- Current version on the stable/release channel: 0.2.14

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@DataHearth @heisfer @mikaelfangel @stepbrobd

Note for maintainers: Please tag this issue in your PR.

**Comment by DataHearth** [comment]
I can take care of this tomorrow or Tuesday 👍
