### ISSUE TITLE
netdata: ipfs check not working

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32059]
## Issue description

I configured IPFS on my server. Netdata should be able to monitor it.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/netdata/default.nix

Maybe python is completely missing and maybe also other (optional) dependencies.

cc @lethalman

### Steps to reproduce

1. install netdata service
2. install ipfs service
3. see if IPFS is shown in netdata

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.52, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by kevlar1818** [comment]
I similarly cannot get the python plugin `smartd_log` to work. I added python to my configuration.nix, and I can start the plugin manually without errors, but when netdata starts the `python.d.plugin` it errors out, saying Python is not available. @davidak did you check `/var/log/netdata/error.log`?

**Comment by davidak** [comment]
Yes, that is the issue here. It has to be added to the package definition.

```
2017-06-18 02:40:03: netdata: INFO: PLUGINSD: '/nix/store/y34mf0d68wgx3h1wm1igc510np7w0qc0-netdata-1.5.0/libexec/netdata/plugins.d/node.d.plugin' thread exiting
/nix/store/y34mf0d68wgx3h1wm1igc510np7w0qc0-netdata-1.5.0/libexec/netdata/plugins.d/python.d.plugin: line 2: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found
```

**Comment by kevlar1818** [comment]
I started looking into how to fix this, and from I've gathered I thought I could simply add `python` to `buildInputs`. This does not work, however, and I continue to get the error @davidak mentioned just above.

I'm happy to fix this if I can get some clarification on the work that needs to be done.

**Comment by williammpratt** [comment]
@kevlar1818 https://stackoverflow.com/questions/31659527/what-is-the-meaning-of-sha256-in-nixpkgs-fetchgit-where-does-the-value-come-fro

**Comment by davidak** [comment]
Maybe the python path needs to be substituted in the python plugin scripts of netdata?

**Comment by kevlar1818** [comment]
@davidak I'm not precisely sure what you mean. The top line of this file is the culprit: https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin

Again, if anyone can chime in, I'm happy to make the changes. I'm just at a bit of a loss as to where to start on the NixOS side.

**Comment by jtojnar** [comment]
Closing in favour of #33366.

**Comment by Mic92** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/50459
