### ISSUE TITLE
Package request: python-octaviaclient

### ISSUE THREAD

**Issue by dwalrond** [NixOS/nixpkgs#320529]
**Project description**

Octavia client for OpenStack Load Balancing

This is an OpenStack Client (OSC) plugin for Octavia, an OpenStack Load Balancing project.

This depends upon nixpkg: `python-openstackclient`.

**Metadata**

* homepage URL: https://docs.openstack.org/python-octaviaclient/latest/
* source URL: https://opendev.org/openstack/python-octaviaclient
* license: apache
* platforms: python / cross platform

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Vinetos** [comment]
I will look at this
