### ISSUE TITLE
Update request: sayonara 1.7.0-stable3 -> 1.10.0-stable1

### ISSUE THREAD

**Issue by VanDoge** [NixOS/nixpkgs#320551]
### package out of date
maintainer seams to be not active 

- Package name: sayonara
- Latest released version: 1.10.0-stable1

- Current version on the unstable channel: 1.7.0-stable3
- Current version on the stable/release channel:1.7.0-stable3

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** @deepfire

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
please edit the title to provide more info

**Comment by iynaix** [comment]
#285110 seems to work fine
