### ISSUE TITLE
Update request: graphite-cli 1.3.6 → 1.3.7

### ISSUE THREAD

**Issue by lukas-mertens** [NixOS/nixpkgs#320504]
- Package name: graphite-cli
- Latest released version: 1.3.7

- Current version on the unstable channel: 1.3.6
- Current version on the stable/release channel: 1.3.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@r-ryantm 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
Fixed by #320574
