### ISSUE TITLE
Bcachefs boot decryption wont work with initrd.systemd enabled

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#320540]
### Describe the bug

If `initrd.systemd.enable = true` the boot process doesn't ask for a decryption password anymore. It does work with the scripted initrd implementation without further configuration

### Steps To Reproduce
1. NixOS installation with Bcachefs encrypted rootfs
2. Set `boot.initrd.systemd.enable = true`
3. Reboot

### Expected behavior
Should ask for a decryption password to continue booting

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.05 (Uakari), 24.05.20240531.805a384`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/store/i1aw9jjgxcvyd642s12kw3iasmarwd42-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
So many issues are popping up like #317901

@ElvishJerricco, as a systemd maintainer you might be interested

Can anyone else confirm? I feel like this is a nixpkgs issue rather than a upstream one

**Comment by ElvishJerricco** [comment]
This is very likely a _duplicate_ of #317901 but we need to see the actual nixos configs from @onny to know for sure.

**Comment by onny** [comment]
> This is very likely a _duplicate_ of #317901 but we need to see the actual nixos configs from @onny to know for sure.

you're right, i was using the full device path which didn't work. switching to UUID schema fixed it
