### ISSUE TITLE
Build failure: vscode-js-debug

### ISSUE THREAD

**Issue by archie-judd** [NixOS/nixpkgs#320507]
Hi, I'm getting the following error, when I try to install the `vscode-js-debug` package:
```
/nix/store/5gl8z4mxbfx4x4r5lamq9ccv4n7l6f1i-stdenv-linux/setup: line 118: jq: command not found
```
It seems `stdenv-linux` is expecting `jq`, which is not there. It seems similar to this *old* issue, which was resolved by adding `jq` to `buildInputs`:

https://github.com/NixOS/nixpkgs/issues/53405

Mentioning the init PR for this package: https://github.com/NixOS/nixpkgs/pull/305824

### Steps To Reproduce
I tried installing using a minimal flake:
```
{
  inputs = { nixpkgs.url = "github:nixos/nixpkgs/master"; };
  outputs = { self, nixpkgs }:
    let pkgs = nixpkgs.legacyPackages."x86_64-linux";
    in {
      devShells."x86_64-linux".default = pkgs.mkShell {

        buildInputs = [ pkgs.vscode-js-debug ];

      };
    };
}
```

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/q55q0yy6z5mjp1a3j2drxkykng9fd8wf-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
/nix/store/5gl8z4mxbfx4x4r5lamq9ccv4n7l6f1i-stdenv-linux/setup: line 118: jq: command not found
/nix/store/5gl8z4mxbfx4x4r5lamq9ccv4n7l6f1i-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240613.e9ee548`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qqwr649pc0qprc9lw2fmdsi1km6p7q2h-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zeorin** [comment]
Fix PR: https://github.com/NixOS/nixpkgs/pull/320877.

**Comment by archie-judd** [comment]
> Fix PR: https://github.com/NixOS/nixpkgs/pull/320877.

Thanks, it's working for me now!
