### ISSUE TITLE
Cairomm library has the wrong include paths

### ISSUE THREAD

**Issue by StijnDW** [NixOS/nixpkgs#32079]
## Issue description

This might just be me not understanding how to develop c++ programs with nixos.
Nevertheless here goes:

My program includes the Cairomm library.
But it fails to compile with the following error:
```
In file included from ../cairosurface/CairoContext.h:5:0,
                 from CairoSurface.cpp:3:
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include/cairomm-1.0/cairomm/cairomm.h:34:27: fatal error: cairommconfig.h: No such file or directory
 #include <cairommconfig.h>
```

### Steps to reproduce

Try to compile any program that uses cairomm like so:
```
#include <cairomm-1.0/cairomm/cairomm.h>
```

The problem seems to be that GCC uses the include path:
```
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include
```
However all the cairomm headers are under:
```
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include/cairomm-1.0/cairomm/
```
And cairomm assumes your include path is:
```
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include/cairomm-1.0/
```
So all cairomm header refer to the other headers like so:
```#include <cairomm/device.h>```
But that can't work, it needs to be
```#include <cairomm-1.0/cairomm/device.h>```
Or the include path in nixos needs to be changed such that it becomes:
```
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include/cairomm-1.0/
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.65, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(stijn): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by StijnDW** [comment]
As a little illustration, this fails to compile:
```
nix-shell -p cairomm -p cairo -p gcc
g++ main.c
```
```
#include <cairomm-1.0/cairomm/cairomm.h>
#include <stdio.h>

int main()
{
    printf("Hello World");
    return 0;
}
```
```
In file included from main.c:1:0:
/nix/store/iv4n9f1lmq1is9v4bdh08g5aa94qj05a-cairomm-1.12.0-dev/include/cairomm-1.0/cairomm/cairomm.h:34:27: fatal error: cairommconfig.h: No such file or directory
 #include <cairommconfig.h>
                           ^
compilation terminated.
```

**Comment by dezgeg** [comment]
This is wrong:
````
#include <cairomm-1.0/cairomm/cairomm.h>
````
As can be seen from https://www.cairographics.org/documentation/cairomm/reference/image-surface_8cc-example.html, that should be just:
````
#include <cairomm/cairomm.h>
`````
 You're supposed to use pkgconfig to get the correct include paths.

````
$ nix-shell -p gcc cairomm pkgconfig
$ g++ $(pkg-config --cflags cairomm-1.0) -c test.cpp
$ g++ $(pkg-config --libs cairomm-1.0) test.o -o test
````

**Comment by StijnDW** [comment]
I was unaware of pkgconfig.
Using that gets me the correct include paths.
Thanks!

**Comment by loganbnielsen** [comment]
I'm new to how this works but my issue seems similar so I think here is a reasonable place to ask.

I downloaded `cairomm-1.16.1` and am trying to run `examples/text/text-rotate.cc`. I added the `data` folder  to a (newly created) `PKG_CONFIG_PATH` environment variable.

When I run `"g++ `pkg-config --cflags --libs cairomm-1.16` examples/text/text-rotate.cc " I get  `fatal error: cairommconfig.h: No such file or directory`

Any suggestions?

**Comment by Stekke** [comment]
Hey, you need to let nix set that `PKG_CONFIG_PATH` environment variable for you.
Unfortunately this doesn't seem to happen if you just request a shell with the pkg-config package.
But it does work if you write a nix expression. Put the following in a file called `shell.nix`
```
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "env";
  nativeBuildInputs = [ pkg-config ];
  buildInputs = [ cairomm ];
}
```
If you now run `nix-shell` then you should get a shell that has `PKG_CONFIG_PATH` set automatically.
Now you can compile like so:
```
g++ `pkg-config --cflags --libs cairomm-1.0` examples/text/text-rotate.cc
```

Note that the default gives you cairomm version 1.14.3
If you want version 1.16 instead then use `buildInputs = [ cairomm_1_16 ];`
You will also need to compile with c++ 17 std, like so:
```
g++ -std=c++17 `pkg-config --cflags --libs cairomm-1.16` examples/text/text-rotate.cc
```

The wiki has more info about using pkg-config: https://nixos.wiki/wiki/C#pkg-config
