### ISSUE TITLE
julia-mono 0.055 breaks Xft-based programs

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#320702]
### Steps To Reproduce
1. add `julia-mono` to `fonts.packages`
2. run `xterm -fn 'xft:JuliaMono'`
3. witness the Xlib error:
    ```
    X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
    Major opcode of failed request:  139 (RENDER)
    Minor opcode of failed request:  20 (RenderAddGlyphs)
    Serial number of failed request:  83
    Current serial number in output stream:  892
    ``` 

### Additional context
Reverting to 0.054 fixes the issue.

### Notify maintainers
@suhr

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment]
Upstream changelog: https://github.com/cormullion/juliamono/compare/v0.054...v0.055

**Comment by suhr** [comment]
See also: https://github.com/googlefonts/noto-emoji/issues/183.

**Comment by suhr** [comment]
The future version of julia-mono should fix this issue, so keep it open for now.
