### ISSUE TITLE
Enhancement: setting powerMangement.enable when generating hardware config on a laptop

### ISSUE THREAD

**Issue by betalars** [NixOS/nixpkgs#320885]
### Describe the ~~bug~~ Issue

The first thing you read on [the wiki article about laptops](https://wiki.nixos.org/wiki/Laptop) is to enable PowerManagment. 

And I do ask myself:
Could this just be added to the by `nixos-generate-config` on install?

I am sure in some cases you would want this option to be disabled on a laptop. But I feel like most users would want that to just work.

### Additional Context
I am also going to open an issue with the same question over on nixos hardware, because I feel like this might also be a sensible place to enable this option in the background.

### Notify maintainers
@roberth @figsoda  

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
n-g-c is just a suggestion in most cases, it's not necessarily a final config. If you're talking more about discoverability, would a comment suggesting "enable this on laptops" suffice?

**Comment by betalars** [comment]
User Error.
Somehow the hardware-module line got lost in my configuration and I did not check this,

**Comment by betalars** [comment]
> would a comment suggesting "enable this on laptops" suffice?

That would still be good.
