### ISSUE TITLE
Package request: pinokio

### ISSUE THREAD

**Issue by GivEN29** [NixOS/nixpkgs#320847]
**Project description**
The elevator pitch:
```
Pinokio is a browser that lets you install, run, and programmatically control ANY application, automatically.
```

But it's mostly used to install and run AI applications pretty easily, the creator made this video: https://youtu.be/mB_bZC8pMDA
Which is the same as on the homepage.

**Metadata**

* homepage URL: https://pinokio.computer/
* source URL: https://github.com/pinokiocomputer/pinokio
* license: MIT
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I created a PR https://github.com/NixOS/nixpkgs/pull/323643 based on this packaging request.
