### ISSUE TITLE
Update request: lemmy-{server,ui} 0.19.3 → 0.19.4

### ISSUE THREAD

**Issue by nothendev** [NixOS/nixpkgs#320849]
- Package name: lemmy-server, lemmy-ui
- Latest released version: 0.19.4
- Current version on the unstable channel: 0.19.3
- Current version on the stable/release channel: 0.19.3
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@happysalada @billewanick

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
I dont have a lot of time now, but ill gladly help get a PR merged if anyone is interested in making one.

**Comment by marius851000** [comment]
This PR upgraded lemmy to 0.19.5, so this issue may be closed. https://github.com/NixOS/nixpkgs/pull/325683
