### ISSUE TITLE
Update request: cargo-binstall 1.6.9 → 1.7.1

### ISSUE THREAD

**Issue by cig0** [NixOS/nixpkgs#320938]
- Package name: cargo-binstall
- Latest released version: 1.7.1

- Current version on the unstable channel: 1.6.9
- Current version on the stable/release channel: 1.6.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

/cc @figsoda 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
This is blocked until #320250 is merged, as cargo-binstall 1.7.0+ requires rust 1.79.0 or later.

**Comment by cig0** [comment]
@pyrox0 I'm closing this PR to reduce the noise.
