### ISSUE TITLE
Package request: mapscii

### ISSUE THREAD

**Issue by Postboote1** [NixOS/nixpkgs#321045]
**Project description**

This is a fun terminal programm for using maps in the terminal. Its just that. Google Maps in your terminal.

**Metadata**

* homepage URL: https://github.com/rastapasta/mapscii?tab=readme-ov-file
* source URL:https://github.com/rastapasta/mapscii?tab=readme-ov-file
* license: MIT License

                 Copyright (c) 2017 Michael Straßburger
                 Copyright (c) 2019 The MapSCII authors
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
@Postboote1 I think we already have this ?

https://search.nixos.org/packages?type=packages&query=MapSCII

**Comment by Postboote1** [comment]
Just seen it 
Sorry was a typo
