### ISSUE TITLE
Gource broken on MacOS, looking for 'Foundation/Foundation.h'

### ISSUE THREAD

**Issue by gschjetne** [NixOS/nixpkgs#32105]
## Issue description

Building Gource fails with the following output:

```
libtool: compile:  cc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"SDL2_image\" -DVERSION=\"2.0.2\" -DLOAD_BMP=1 -DLOAD_GIF=1 -DLOAD_LBM=1 -DLOAD_PCX=1 -DLOAD_PNM=1 -DLOAD_SVG=1 -DLOAD_TGA=1 -DLOAD_XCF=1 -DLOAD_XPM=1 -DLOAD_XV=1 -I. -g -O2 -I/nix/store/dk1jn8m66rmxvkrqy11slrw46agv52yz-SDL2-2.0.7-dev/include/SDL2 -I/nix/store/dk1jn8m66rmxvkrqy11slrw46agv52yz-SDL2-2.0.7-dev/include/SDL2 -D_THREAD_SAFE -c IMG_ImageIO.m  -fno-common -DPIC -o .libs/IMG_ImageIO.o
IMG_ImageIO.m:17:10: fatal error: 'Foundation/Foundation.h' file not found
#include <Foundation/Foundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Steps to reproduce

`$ NIXPKGS_ALLOW_BROKEN=1 nix-env -i gource`

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(schjetne): `"nixpkgs-18.03pre121255.45a85eaceb"`
 - nixpkgs: `/Users/schjetne/.nix-defexpr/channels/nixpkgs`

**Comment by jtojnar** [comment]
Could you try adding Foundation as a dependency and see it it is works? See for example here: https://github.com/NixOS/nixpkgs/blob/676b2ef431fb6bd047b23cedac2bed0d58997c47/pkgs/development/compilers/mono/generic.nix#L17
