### ISSUE TITLE
Quarto cant compile typst document, because unexpected version is used

### ISSUE THREAD

**Issue by Charging1948** [NixOS/nixpkgs#321006]
### Describe the bug
Quarto version `1.4.555` expects to use binary of `typst` with version `0.10.0`. 
In the `nix`-packaged version of `quarto` the newest version of `typst` is used.
At the time of writing the newest version of `typst` is `0.11.1`.

Perhaps this is also a problem with the other binaries that are being replaced, but i only encountered bugs with `typst`.
`typst` is relatively new, so i guess it is a lot more likely that it introduces breaking changes.

`quarto` tracks required versions of programs inside [quarto-cli/configuration](https://github.com/quarto-dev/quarto-cli/blob/1f5fd5e7f70f4aa0ed38ab3d21d8fa8914aa63c7/configuration) file.

### Steps To Reproduce
1. Create `qmd`-file with this content:
```qmd
---
title: hello
author: me
format: 
  typst: 
    columns: 1
    number-sections: true
---

# Header

some text

# Another Header

gonna put an image here - 

![an image with a caption]({{< placeholder >}}){#fig-idk fig-align="center"}

i cannot reference the image in typst like this:

reference @fig-idk - this errors out

a weak work around that isn't really a work around is removing the reference:

some caption here referencing [@fig-idk]{.content-visible when-format="pdf"}
```
2. replace `{{< placeholder >}}` with a valid image path
3. compile with `quarto preview [FILE]`

### Expected behavior
The document should be compiled into a `pdf`-file, without errors.

### Additional context

Initial discussion about problem: https://github.com/quarto-dev/quarto-cli/discussions/9921#discussioncomment-9807151.
Resolution of above discussion: https://github.com/quarto-dev/quarto-cli/issues/10047

Error message when compiling above example with current `quarto`-package:

```
pandoc 
  to: typst
  output-file: test.typ
  standalone: true
  default-image-extension: svg
  wrap: none
  citeproc: false
  number-sections: true
  
metadata
  section-numbering: 1.1.a
  columns: 1
  title: hello
  author: me
  
[typst]: Compiling test.typ to test.pdf...error: cannot access fields on type auto
    ┌─ test.typ:108:26
    │
108 │   let sup = it.supplement.text.matches(regex("^45127368-afa1-446a-820f-fc64c546b2c5%(.*)")).at(0, default: none)
    │                           ^^^^
```

### Notify maintainers

@MrTarantoga @minijackson 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.4, NixOS, 24.11 (Vicuna), 24.11.20240616.b60ebf5`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.22.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
Ah, unfortunately we will have to wait until Quarto 1.5 is released to have typst 0.11 support… Right now I can't figure out which patches to apply to get typst 0.11 support, and I don't think we can downgrade typst either.

You could always use a fixed version of nixpkgs before the typst upgrade, if you need that feature right now.

**Comment by Charging1948** [comment]
I was afraid that this is not easily solvable. Thanks for looking into this.
Would it be feasible to maintain a typst-version that is compatible with quarto?

Typst will surely introduce more breaking changes in the future, even after the release of Quarto 1.5.

The least that we could do is document, that there could be issues with typst support.
Perhaps on https://wiki.nixos.org?

**Comment by minijackson** [comment]
Usually, for stable channels this isn't a big issue because breaking changes are not backported. So if we have a stable channel with Quarto and Typst working, it should stay that way. 24.05 was released recently, so it's bad timing, unfortunately.

It's technically possible to make a quarto-compatible typst package, but I'm not sure what this would mean security-wise to maintain an older version of typst. Typst is not stable yet, so I guess people should expect it?

**Comment by Charging1948** [comment]
I agree, thank you!
