### ISSUE TITLE
deja-dup unable to open webbrowser

### ISSUE THREAD

**Issue by thyol** [NixOS/nixpkgs#321041]
### Describe the bug
Deja-dup can not open webbrowser.

### Steps To Reproduce
1. setup nixos (without gnome)
2. `nix-shell -p deja-dup`
3. deja-dup
4. Setup backup with Google Account
5. Click Grant Access
6. See error message "No Apps available", "No apps installed that can open \"Fwww.googleapis.com[....]".

### Expected behavior
Instead of step 6, a webbrowser is openend.

### Notify maintainers
@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.05 (Uakari), 24.05.1503.752c634c09ce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05, nixos-unstable-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
What desktop environment do you use? Perhaps https://discourse.nixos.org/t/nautilus-not-working-properly-due-to-missing-path-in-dbus/38824

**Comment by thyol** [comment]
Thank you! It was indeed not a bug in deja-dup module, but with my sway config.

```
dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway --all
systemctl --user import-environment PATH
systemctl --user restart xdg-desktop-portal.service
```
