### ISSUE TITLE
Backport request: neovim-0.10.0

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#321051]
### Describe the bug
It appears that the transition from neovim 0.9 to 0.10 has renamed the widely-used `vim.loop` Lua interface to `vim.uv`. Sadly, at least two plugins (`dropbar.nvim`, `neogit`) have transitioned to this new interface without allowing for a migration period.

While neovim 0.10 was only released in May, I believe this breakage might warrant backporting to 24.05.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
This is too big of a change for a backport I think. It's easier to pin dropbear and neogit to their working versions.

**Comment by natsukium** [comment]
Updates that include breaking changes are unacceptable.

see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases
> Minor versions with new functionality, but no breaking changes

see also https://github.com/NixOS/nixpkgs/pull/313359
