### ISSUE TITLE
Build failure: xdg-desktop-portal

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#321135]
### Steps To Reproduce

1. build xdg-desktop-portal

### Build log

[hydra can reproduce](https://hydra.nixos.org/build/263563746/log/tail)

### Notify maintainers

@jtojnar 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240618.dce10c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/a80hj7rpd44dfp0nwwcrn989kv8f6sg1-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Unfortunately, I am unable to reproduce locally.

There was an upstream fix for some tests https://github.com/flatpak/xdg-desktop-portal/commit/740e3754829677e549e3bbae519a4726e6ca2e43 in but then I would expect Hydra to fail on the other portals test mentioned in https://github.com/flatpak/xdg-desktop-portal/issues/1278.

If someone is able to reproduce, could you please extract `/build/source/build/meson-logs/testlog.txt` from the build directory?

**Comment by MisileLab** [comment]
> Unfortunately, I am unable to reproduce locally.
> 
> There was an upstream fix for some tests [flatpak/xdg-desktop-portal@740e375](https://github.com/flatpak/xdg-desktop-portal/commit/740e3754829677e549e3bbae519a4726e6ca2e43) in but then I would expect Hydra to fail on the other portals test mentioned in [flatpak/xdg-desktop-portal#1278](https://github.com/flatpak/xdg-desktop-portal/issues/1278).
> 
> If someone is able to reproduce, could you please extract `/build/source/build/meson-logs/testlog.txt` from the build directory?

I can't reproduce, hydra also can't reproduce now.
I'll close issue.
