### ISSUE TITLE
Update request: meilisearch 1.8.2 → 1.8.3

### ISSUE THREAD

**Issue by koalazub** [NixOS/nixpkgs#321218]
Package name: meilisearch

Latest released version: 1.8.2

Current version on the unstable channel: 1.8.2

Current version on the stable/release channel: 1.8.2

- [x] Checked the nixpkgs pull requests

Notify maintainers

@happysalada 

Note for maintainers: Please tag this issue in your PR.

Extra info: 

This was only just announced and here is the patch note: 

> Why would you need to upgrade to v1.8.3?
We recommend all v1.8 users upgrade to v1.8.3, as this patch release includes an important fix preventing a memory leak that would ultimately cause a crash.

Didn't mean to put you to work only 3 days later!

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by LudovicoPiero** [comment]
#321593
