### ISSUE TITLE
Cannot install just Symbols Only Nerd Font

### ISSUE THREAD

**Issue by auroraanna** [NixOS/nixpkgs#321263]
### Describe the bug
the nerdfonts packages allows it's fonts attribute to be overriden so that you can only install some fonts patches with the Nerd Font symbols, not all patched fonts. However, you cannot just install the Symbols Only Nerd Font because installing nerdfonts will install all patched nerdfonts (and presumably also the Symbols Only Nerd Font which i can't test because it keeps running out of memory trying to build the whole nerdfonts package) and installing `(nerdfonts.override { fonts = [ ]; })` will also install the whole thing.

### Expected behavior
`(nerdfonts.override { fonts = [ "Symbols Only" ]; })` builds.

### Notify maintainers

@doronbehar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240616.b60ebf5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
There is `NerdFontsSymbolsOnly`, which is probably what you want:
https://github.com/NixOS/nixpkgs/blob/d603719ec6e294f034936c0d0dc06f689d91b6c3/pkgs/data/fonts/nerdfonts/shas.nix#L51
At least there does not seem to be anything else similar in upstream releases list:
https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.1

**Comment by doronbehar** [comment]
Yea so it seems to me that the main problem with this expression is that it may run out of memory if you want to choose only a single font - I too remember experiencing something similar in the past... @auroraanna could you share please exactly what expression failed to build for you do to a memory issue? I bet the memory issue you encountered can be reproduced on your machine with:

```sh
nix build --print-build-log --impure \
  --expr 'with (builtins.getFlake "nixpkgs").legacyPackages.${builtins.currentSystem};
    nerdfonts.override {
      fonts = [
        "NerdFontsSymbolsOnly"
    ];
  }'
```

**Comment by auroraanna** [comment]
@doronbehar no, that command runs just fine. it runs out of memory trying to build all nerd fonts (i.e. just the nerdfonts package, no override).

**Comment by auroraanna** [comment]
@ghpzin huh, i think i might've only search for "Symbols Only" because was expecting it to have spaces like font names usually do…

**Comment by auroraanna** [comment]
i guess the running out of memory issue is just an issue with my machine then

**Comment by doronbehar** [comment]
Yes the memory issues are related to this BTW: https://github.com/NixOS/nix/issues/7154 I personally set this in my config:

```nix
    # Ideally this should be true, but:
    # https://github.com/NixOS/nix/issues/7154
    boot.tmp.useTmpfs = false;
    # Use a tmpdir with unlimited space (as opposed to /tmp)
    systemd.services."nix-daemon".environment.TMPDIR = "/nix/tmp";
    systemd.tmpfiles.rules = [
      "d /nix/tmp 770 root nixbld" # Don't use it
    ];
```
