### ISSUE TITLE
Update request: tpnote 1.24.2 → 1.24.3

### ISSUE THREAD

**Issue by getreu** [NixOS/nixpkgs#321337]
Package name: tpnote

Latest released version: 1.24.3

Current version on the unstable channel: 1.24.2

Current version on the stable/release channel: 1.24.2

Change log:

Enhance the HTML clipboard configuration options

This release extends the `html_to_markup` filter by adding a `default=`
parameter in case the filter fails, its result is the empty string, or if
the filter is disabled for a certain markup language with the configuration
variable `extensions.1`.

The `clipboard` variable is replaced by the variables `txt_clipboard` and
`html_clipbaord`. They both represent the clipboard's text content. The
difference is, that the `html_clipboard` carries HTML formatting along the
text, while `txt_clipboard` holds the plain text only.

**Comment by Frontear** [comment]
From my quick test this can not be built until rustc is upgraded to 1.79, which will likely be a massively breaking change.

**Comment by getreu** [comment]
I downgraded the mentioned dependencies and release v1.24.4. This compiles with rustc 1.77.2 and above.

**Comment by getreu** [comment]
@Frontear Could you check again?

**Comment by Frontear** [comment]
Compilation succeeds, and software from an extremely basic level works as well. I'll submit a PR up

**Comment by getreu** [comment]
Sorry, forgot to push. Its done now.

**Comment by Frontear** [comment]
Will look into pushing later tonight, assuming someone doesnt beat me to it :)
