### ISSUE TITLE
Set `services.scrutiny.collector.enable` to `true` by default if Scrutiny is enabled

### ISSUE THREAD

**Issue by poperigby** [NixOS/nixpkgs#321388]
It's a bit confusing to have Scrutiny be basically broken by default, because the collector systemd unit isn't enabled, so it isn't scanning any drives. Shouldn't this be enabled by default if `services.scrutiny.enable` is `true`?

**Comment by eclairevoyant** [comment]
You can have the collector running on one machine and web app on another, as with any other client-server model.

BTW when creating issues about a module, you'll want to tag the applicable maintainers:
https://github.com/NixOS/nixpkgs/blob/3ed0e6824c1a677493e86904a9f7472fcef5b46a/nixos/modules/services/monitoring/scrutiny.nix#L216

**Comment by poperigby** [comment]
> You can have the collector running on one machine and web app on another, as with any other client-server model.

True, but I think that's less likely than someone running both on the same machine, and people who want that setup can just set `collector.enable` to `false`. I think it being set to `true` by default is a better out of the box experience, as it will "just work." For example, InfluxDB is enabled by default for this module to make it work out of the box, but you could have your own InfluxDB instance that you want to connect to, so you would just disable it in this module.

> BTW when creating issues about a module, you'll want to tag the applicable maintainers:

Sorry about that.

@jnsgruk

**Comment by poperigby** [comment]
@jnsgruk Sorry for the delay. I made a PR: 329069

**Comment by jnsgruk** [comment]
Now complete, thanks for the PR!
