### ISSUE TITLE
TeamViewer 15.49.2: Window for remote connection does not appear

### ISSUE THREAD

**Issue by leon-erd** [NixOS/nixpkgs#321333]
### Describe the bug
Using teamviewer with `services.teamviewer.enable = true;` I can not connect to remote hosts.

The connection is established, but the window does not appear. If i try to connect to the same host again, I receive the message that I already have a connection open.

TeamViewer is working as expected on EndeavourOS.

### Steps To Reproduce
1. Open TeamViewer
2. Connect to any host
3. Window for password appears
4. Window for connected host does not appear
5. Connect to the same host again
6. Message "you are already connected" appears
7. On the host computer it says that Im connected

### Additional context
It seems like its the same bug as https://github.com/NixOS/nixpkgs/issues/300937

I also get the same errors in my log file [teamviewer.log](https://github.com/user-attachments/files/15919414/teamviewer.log)
```
$ cat ~/.local/share/teamviewer15/logfiles/TeamViewer15_Logfile.log
...
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/ClientWindow/RCClientRemoteScreenWindow.qml:176:2: Type RemoteControlToolbar unavailable, Errorcode=11
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/ClientWindow/RemoteControlToolbar.qml:14:1: Type ToolbarContainer unavailable, Errorcode=11
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/ClientWindow/RCClient/ToolbarContainer.qml:51:2: Type PerryRoundangle unavailable, Errorcode=11
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryRoundangle.qml:7:1: Type PerryDropShadowItem unavailable, Errorcode=11
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryDropShadowItem.qml:26:16: Type PerryDropShadow unavailable, Errorcode=11
2024/06/20 21:39:47.672  2932  2932 GW2!! QML load error: qrc:/ui/QuickCommon/Style/PerryDropShadow.qml:1:1: module "QtGraphicalEffects" is not installed, Errorcode=11
...
```

### Notify maintainers
@ifurther @jagajaga @jraygauthier @gador

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240618.c00d587`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/pfqbxdicyksnqda6h5xv285sx7vamwzd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gador** [comment]
@leon-erd please try the linked PR and report back if this solved your issue. Thanks

**Comment by leon-erd** [comment]
I can confirm that it work!!! :partying_face: 
Thanks for the fast reply :))
However, I'm now getting a commercial use restriction 
![swappy-20240621_133405](https://github.com/NixOS/nixpkgs/assets/99900077/e25611c2-8cb3-4a5b-9773-3c4416712cfb)
I dont know if this has anything to do with nixpkgs or if its just because I tried to connect many times now. On the teamviewer website I have requested to remove my restriction lets see how it goes ;)

**Comment by gador** [comment]
> I can confirm that it work!!! 🥳 Thanks for the fast reply :)) 

yay!

> However, I'm now getting a commercial use restriction !I dont know if this has anything to do with nixpkgs or if its just because I tried to connect many times now. On the teamviewer website I have requested to remove my restriction lets see how it goes ;)

I am pretty sure this is independent of NixOS. I had this in the past as well (independent of NixOS). I don't know how teamviewer tries to detect commercial use. But glad to here it works!

**Comment by leon-erd** [comment]
@gador I would really like to learn more about packaging programs for nixpkgs so I can contribute more myself.
Do you have any recommendations on how to learn the different options for mkDerivation, the different phases, wrapping programs and libraries, etc.? I feel like the documentation is basically non-existend.
If anything comes to mind (including workshops, etc.) feel free to just send me an email [leonvincenterd@web.de](mailto:leonvincenterd@web.de) (this issue is probably the wrong place to discuss this)

**Comment by gador** [comment]
Hi @leon-erd 
awesome! 
I'm just gonna answer you here for anyone who is also interested:
- There is a handbook (https://nixos.org/manual/nixpkgs/unstable) which has a whole chapter about contributing to `nixpkgs` 
- There is https://discourse.nixos.org which helps a lot (just search for it or ask a question there)
- It helped me a lot to look at how other packages are packed. Just clone `nixpkgs` and look at how similar services or programs are packaged
- There is a matrix https://matrix.to/#/#community:nixos.org

Generally just start small. Find some nixpkgs which you'd like to see upgraded and update the version and hash and build it locally in your nixpkgs repo and submit a pull request ;-)

If you still have trouble, just ask again on discourse (Im [gador](https://discourse.nixos.org/u/gador/summary) there, too) and we'll go from there :+1:
