### ISSUE TITLE
gitlab update script broken

### ISSUE THREAD

**Issue by yayayayaka** [NixOS/nixpkgs#321491]
### Describe the bug
The gitlab [`update.py`](https://github.com/NixOS/nixpkgs/blob/892cdcec93565f63c8419acc834f83c6b6dac4c9/pkgs/applications/version-management/gitlab/update.py#L2) script depends on `nix-universal-prefetch`, which was removed by 578d7e717848de3259baa52262a9267a9cdf6277 in #321436.

### Steps To Reproduce
1. `cd pkgs/applications/version-management/gitlab; ./update.py update-all`

### Expected behavior
The update scripts succeeds.

### Notify maintainers
(myself)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mic92** [comment]
Also looks like nix-update could be used here.

**Comment by Mic92** [comment]
Ok. looks like switching to nix-update would require some other major refactoring because the update.py writes out some json file out. But here is a simpler approach: https://github.com/NixOS/nixpkgs/pull/322179
