### ISSUE TITLE
SDDM not localized when using Plasma 6

### ISSUE THREAD

**Issue by niknetniko** [NixOS/nixpkgs#321520]
### Describe the bug
SDDM is not localized when using Plasma 6. I have configured it to be in another language, and all of Plasma and other programs respect it, except SDDM.

### Steps To Reproduce
1. Set the locale of the system to something, e.g. `i18n.defaultLocale = "nl_BE.UTF-8";`
2. Use Plasma (6).
3. Observe that SDDM is still in English.

### Expected behavior
SDDM is shown in my language.

### Additional context

My config contains:

```nix
i18n.defaultLocale = "nl_BE.UTF-8";
i18n.supportedLocales = ["en_GB.UTF-8/UTF-8" "nl_BE.UTF-8/UTF-8" "fr_BE.UTF-8/UTF-8"];
```
and
```console
$ cat /etc/locale.conf 
LANG=nl_BE.UTF-8
```

### Notify maintainers

@abbradar @ttuegel @k900

(not sure if it is the package or the NixOS module that causes the issue)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(niko): `"android-nixpkgs"`
 - channels(root): `"android, nix-ld, nixos"`
 - nixpkgs: `/nix/store/pfqbxdicyksnqda6h5xv285sx7vamwzd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
how did you configure/install sddm?

**Comment by Daviteusz** [comment]
I also have sddm in English

My setup:

```nix
[...]
  boot = { 
    [...]
    plymouth.enable = true;
  };
  services.displayManager.sddm = {
    enable = true;
    #wayland.enable = true;
    settings = {
      General = {
       DisplayServer = "x11-user";
      };
    };
  };
  services.desktopManager.plasma6.enable = true;
  
  environment.systemPackages = with pkgs; [
    kdePackages.ktexteditor
    kdePackages.kate
  ]

  i18n = {
    defaultLocale = "pl_PL.UTF-8";
    supportedLocales = [ "pl_PL.UTF-8/UTF-8" ];
  };
  console = {
    font = "Lat2-Terminus16";
    keyMap = "pl";
  };
[...]
```

Terminal outputs
```bash
$ cat /etc/locale.conf 
LANG=pl_PL.UTF-8

$ locale
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

**Comment by niknetniko** [comment]
> how did you configure/install sddm?

Very minimally, and similar to Daviteusz:

```nix
services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
};
services.desktopManager.plasma6.enable = true;
```

**Comment by DocBrown101** [comment]
It seems that it will always stay that way :(

**Comment by K900** [comment]
Does it reproduce if you run `sddm-greeter --test-mode` from your user environment?

**Comment by niknetniko** [comment]
> Does it reproduce if you run `sddm-greeter --test-mode` from your user environment?

It does not for me: when run like this, SDDM is fully localized.

I have tried both the Qt5 and Qt6 version, like this:

```console
# Qt6
nix shell nixpkgs#kdePackages.sddm
sddm-greeter-qt6 --test-mode
# Qt5
nix shell nixpkgs#libsForQt5.sddm
sddm-greeter --test-mode
```

**Comment by isti115** [comment]
Hmm, this may or may not be related to this issue, but instead of potentially creating a duplicate, I thought that first I'd mention it here, that as far as I can tell, the variables provided through the`GreeterEnvironment` configuration parameter should be separated by commas, not spaces, so this line seems to be incorrect, which might be the reason why `SDDM` doesn't get the correct locale.
https://github.com/NixOS/nixpkgs/blob/33895f7dbd752469ac4d7fdc7d203980f593976e/nixos/modules/services/display-managers/sddm.nix#L47

**Comment by K900** [comment]
@peterhoeg are you sure that's necessary?

**Comment by K900** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/337749

**Comment by niknetniko** [comment]
That indeed seems to have fixed it. Thanks K900!
