### ISSUE TITLE
Logseq won't install anymore with electron 28

### ISSUE THREAD

**Issue by relief-melone** [NixOS/nixpkgs#321540]
### Describe the bug
Logseq cannot be installed anymore because of the electron version being used has reached EOL. Previously this could be mitigated by adding the version to permittedInsecurePackages. However this does not work anymore

### Steps To Reproduce
1. add Logseq to user packages and electron to the permittedInsecurePackages
```nix
{ pkgs, ...}:{
  users.users.my-user.packages = with pkgs; [
    logseq
  ];

   nixpkgs.config.permittedInsecurePackages = [ 
    # I tried all different types of the packages as you can see
    "electron_28"
    "electron-28.3.3"
    "electron_28.3.3"
    "electron_27"
    "electron_27.3.11"
    "electron"
  ];
 
}
```
2. Rebuild
`sudo nixos-rebuild switch`

3. See it fail
```
 error: Package ‘electron-28.3.3’ in /nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source/pkgs/development/tools/electron/binary/generic.nix:36 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 28.3.3 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) for `nixos-rebuild` you can add ‘electron’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron"
              ];
            }
```

### Expected behavior
The permitted insecure package should be accepted and the system should be built

### Workaround
You can still install by allowing insecure packages without limits (in my case as a flake) with
`sudo NIXPKGS_ALLOW_INSECURE=1  nixos-rebuild switch --flake . --impure`
however this is not ideal because obviously you don't have control anymore about what packages you still allow

**Comment by eclairevoyant** [comment]
fyi the string to use is `"electron-28.3.3"`, see #320370

**Comment by relief-melone** [comment]
with nixpkgs commit 2893f56de08021cffd9b6b6dfc70fd9ccd51eb60 the output also now suggests to permit package `"electron-28.3.3". however doing so does not work unfortunately. The error message persists even with having it allowed

**Comment by eclairevoyant** [comment]
Sounds like you're passing pkgs incorrectly or something then, please provide the full config or an MWE

**Comment by relief-melone** [comment]
I'd never say never but the config hasn't changed in ages and worked well with when electron 27.x was still in use.  So this is basically the whole file

```nix
{ pkgs, vars, ...}:
{
  users.users.${vars.main_user} = {

    packages = with pkgs; [
      #...
      logseq
      #...
    ];
  };

  nixpkgs.config.permittedInsecurePackages = [ 
    "electron-28.3.3"
  ];
}

```

**Comment by eclairevoyant** [comment]
I'm asking for the entire config, not just one file. Can't repro your issue otherwise.

**Comment by relief-melone** [comment]
You can find my repo here 

https://gitlab.com/relief-melone/nixos-config

The file in particular is in 

*modules/user/user-packages.nix*

**Comment by eclairevoyant** [comment]
Okay, I don't see any extra instances of nixpkgs anywhere. But I did finally notice that you have underscores (`electron_28.3.3`) instead of dashes (`electron-28.3.3`).

**Comment by eclairevoyant** [comment]
Also I found some other issues, you might consider applying the following patch:

```diff
diff --git a/flake.nix b/flake.nix
index 046b391..40bdafc 100644
--- a/flake.nix
+++ b/flake.nix
@@ -55,19 +55,14 @@
         inherit credentials;
         inherit nixvim;
         home-manager = inputs.home-manager;
-        lib = nixpkgs.lib;
       };
 
     in
     {
       # Razer Blade Advanced bought in 2022
       "relief-melone-rba" = 
-      let
-        system = "x86_64-linux";
-      in
       nixpkgs.lib.nixosSystem 
       {
-        inherit system;
         inherit specialArgs; 
 
         modules = base_modules ++ [
```

**Comment by relief-melone** [comment]
will check out the patch. Forgot to mention though that the branch I am testing this stuff now is not main but feature.webdav. Sorry for the confusion.

**Comment by ehmry** [comment]
Would it make more sense to write a nixos module for running the web service locally than it would to package the chromeshit?

**Comment by aktaboot** [comment]
I run logseq on latest electron (31.4.0) and it works fine except that I am (still) hitting #264885 which is upstream issue

I guess this is no longer an issue ? can you confirm @relief-melone

**Comment by relief-melone** [comment]
Problem disappeared in one of the latest releases. Can't pin point which one because I had been building with the env var for some time.
Now it works as expected again. Thanks 👍
