### ISSUE TITLE
Package request: gruvbox-material-gtk-theme

### ISSUE THREAD

**Issue by RytikulaMoff** [NixOS/nixpkgs#321553]
**Project description**

A GTK theme based on the Gruvbox colour palette. 

**Metadata**

* homepage URL: https://www.pling.com/p/1681313/
* source URL: https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme
* license: GPL-3.0
* platforms: Linux

---
![Gruvbox-GTK-Theme Showcase](https://github.com/NixOS/nixpkgs/assets/128254101/8a363b1b-f1d4-41b4-9357-309e789d9ef7)

**Comment by donovanglover** [comment]
How does this compare to [`gruvbox-gtk-theme`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/gr/gruvbox-gtk-theme/package.nix#L33)? Looks like a duplicate.

**Comment by RytikulaMoff** [comment]
> How does this compare to [`gruvbox-gtk-theme`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/gr/gruvbox-gtk-theme/package.nix#L33)? Looks like a duplicate.

The one provided on [NixOS packages search](https://search.nixos.org/packages?channel=24.05&show=gruvbox-dark-gtk&from=0&size=50&sort=relevance&type=packages&query=gruvbox-dark) site leads to an entirely [different GTK theme](https://github.com/jmattheis/gruvbox-dark-gtk) by a different creator, made with Oomox. Maybe I should file this as a different issue then?
