### ISSUE TITLE
Bad 4K experience in installer and first run

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32159]
## Issue description
Installer should detect a 4K screen and modify the font and default configuration.nix to apply this. For instance KDE can handle high pixel configurations too and by default such settings should be used.  

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
I don't think *graphical* font needs changing.  *If* DPI is detected correctly, fonts should be sized correctly.  We would have to look more closely into the underlying problems of the respective desktop environments.

Let's close this and continue discussion on https://github.com/NixOS/nixpkgs/issues/12345
