### ISSUE TITLE
services.mattermost.plugins doesn't install the plugins?

### ISSUE THREAD

**Issue by happyalu** [NixOS/nixpkgs#321536]
I'm using `services.mattermost.plugins` to add a few tar.gz archives. I see that those get added to `/var/lib/mattermost/data/plugins` on the host after deployment. However, the mattermost module also sets in the config file, the path `/var/lib/mattermost/plugins/server` as the plugin directory (which I think expects unzipped plugin directory). But the archives don't appear to get unzipped.

I am unable to see where the plugin can be enabled from the console too.

In this commit: https://github.com/NixOS/nixpkgs/commit/7cf6855c7f0e17fa3bb3699f951844ec79668654 there used to be a "mattermost plugin add" call; not sure if removing that has changed anything. However, I see that the latest mattermost (9.5.6) also doesn't have a "plugin" command anymore. 

Maybe I'm missing something in getting those plugins used.

cc @numinit -- it seems you authored few of the commits related to the plugins, perhaps you might be able to help with what I'm doing wrong.

**Comment by numinit** [comment]
https://github.com/NixOS/nixpkgs/pull/208181/files#diff-fc1d668ec69d281b8651a551c3da1427024102e0ae309bbed67aab750d6ab4d8R42

Check out this test in this (currently stalled) PR for an example.

**Comment by happyalu** [comment]
Thanks. I think I'm doing something similar to that test when adding plugins. But somehow I'm missing the "unpack plugins" step to populate the $pluginDir/server directory.. Will look more carefully again; ---
But are you suggesting that this PR is necessary to get the plugins working again? Or plugins should be working with 24.05 already?

**Comment by numinit** [comment]
They should work correctly.

**Comment by happyalu** [comment]
Ok, good to know. I'll try debugging this in a vm (maybe my existing config.json is interfering with something). But looking at the derivation, I still am not sure what  takes the archives from [data/plugins](https://github.com/NixOS/nixpkgs/blob/dd457de7e08c6d06789b1f5b88fc9327f4d96309/nixos/modules/services/web-apps/mattermost.nix#L293) and unpacks them into [plugins/server](https://github.com/NixOS/nixpkgs/blob/dd457de7e08c6d06789b1f5b88fc9327f4d96309/nixos/modules/services/web-apps/mattermost.nix#L81). Is that a default path in mattermost? I can't find a reference to `data/plugins` in my config anywhere, and mattermost system console doesn't seem to find any info about the plugins present in that directory.

**Comment by happyalu** [comment]
Hmm. I'm using s3 as the filestore, that probably might explain why the local data/plugins isn't being used

**Comment by happyalu** [comment]
That was it. I had to add this to make it work. Thanks for your help, @numinit 
```
 systemd.services.mattermost.serviceConfig.ExecStartPre = lib.mkAfter [
    "${pkgs.awscli}/bin/aws s3 sync --delete ${config.services.mattermost.statePath}/data/plugins/ s3://MY_S3_BUCKET/plugins/"
  ];
```

I'll close the issue now.

**Comment by numinit** [comment]
Ah, that totally explains things.
