### ISSUE TITLE
Package request: Cloneable

### ISSUE THREAD

**Issue by Tanvir1337x** [NixOS/nixpkgs#321583]
**Project description**

The all-in-one website downloader tool for offline browsing, archiving, backups, and more.

**Metadata**

* homepage URL: https://cloneable.app
* source URL: https://github.com/CloneableApp/Cloneable
* license: gpl3
* platforms: unix, linux, darwin, windows

## Note

Making this request early. Downloadable binaries are currently not available, but will be soon.

**Comment by myclevorname** [comment]
The version of node.js used to build the program, which is v16.13.1, is EOL. Please ask the upstream developer to update the node.js version.

**Comment by TanvirOnGH** [comment]
It's been a while and got no response from upstream. Project isn't receiving updates.
