### ISSUE TITLE
Touchpad configuration T570

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32158]
## Issue description

I would like to be able to move over half the distance of the synaptics touchpad in order to move over the full width of my 4K screen.

Additionally, if someone has any pointers ( ^-^ ) to make the hardware work as intended, that would be great.  

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by orivej** [comment]
You may set `services.xserver.libinput.enable = true` (and leave `services.xserver.synaptics.enable` unset) and configure the touchpad in your desktop settings (if libinput does not solve your problem outright).

**Comment by williammpratt** [comment]
I tried the former (it was the first thing I tried), but that resulted in no working mouse pointer at all.

The mouse pointer I have now working is one without any multi-touch features where scrolling happens on the right side of the pad. 

After I upgraded to the latest kernel, I was able to have a larger min and max speed, so the most important problem has been resolved.

**Comment by williammpratt** [comment]
`services.xserver.libinput.enable = true;` and configuring the touchpad via `systemsettings5` works fine when you configure the scrollspeed with kernel 4.13.4. The 17.09 kernel doesn't seem to work well.

**Comment by orivej** [comment]
> The mouse pointer I have now working is one without any multi-touch features where scrolling happens on the right side of the pad.

Try `services.xserver.libinput.naturalScrolling = true`.

> The 17.09 kernel doesn't seem to work well.

In what way?

**Comment by williammpratt** [comment]
min and maxspeed had a smaller range in the Plasma5 configuration widget with that kernel.

**Comment by orivej** [comment]
Thanks for the info! Is this issue resolved now?

**Comment by williammpratt** [comment]
I was able to setup two-finger scrolling via the Plasma5 widget combined with the above configuration. I am satisfied :)

Closing.
