### ISSUE TITLE
Firefox not compliant with General Data Protection Regulation

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32160]
## Issue description
By default " Allow Firefox to install and run studies"  is enabled. This should be disabled.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.61, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
Nixpkgs follows upstream for this.  Each user can easily set the preference, though not on nix level ATM.  Until there's a consensus against this, I wouldn't touch it.

**Comment by williammpratt** [comment]
You are a Dutch entity `The NixOS Foundation is a registered non-profit organisation at the Chamber of commerce (Kamer van Koophandel) in Utrecht, The Netherlands. The KvK number is 63520583. ` as such you might want to follow upstream, but it would just be against the law.

The Mozilla Corporation is an American entity and doesn't need to abide by those rules.

**Comment by vcunat** [comment]
First, I'm no lawyer.  The relation to the foundation is rather loose, I believe, but the infrastructure will be mostly in the EU anyway (and nixpkgs did e.g. turn a blind eye on some software patents).  @williammpratt: can you provide some (trustworthy) reference claiming that the Firefox default is against EU law?

**Comment by williammpratt** [comment]
@vcunat See https://www.whitecase.com/publications/article/chapter-8-consent-unlocking-eu-general-data-protection-regulation

**Comment by orivej** [comment]
Firefox asks the user to consent to contribute statistics, this is not a silent default.

**Comment by edolstra** [comment]
FWIW, the NixOS Foundation has nothing to do with this since it doesn't hold the copyright to NixOS/Nixpkgs and doesn't distribute it.

**Comment by williammpratt** [comment]
@orivej They already put the checkmark in by default. That's against the law, even if you then press "OK".

@edolstra Please forward this to the legal entity controlling cache.nixos.org then.

**Comment by orivej** [comment]
Since "Allow Nightly to send technical and interaction data to Mozilla" is unchecked and disabled in our Firefox builds, it is not clear that the enabled "Allow Firefox to install and run studies" will send Mozilla any data (that will not be sent when it is disabled), at least without your permission. [Here](https://medium.com/@mgrimes/shield-studies-go-faster-bet-smarter-1010ae8d8e) is the description of this feature:

> Shield Studies allow us to give newly graduated features from Test Pilot to small representative populations of the Firefox Release audience. These users will get a chance to use these features for a period of time and then be asked to provide feedback on the experience.

Your unsubstantiated claim that "Firefox leaks data" due to this feature seems groundless.

**Comment by williammpratt** [comment]
@orivej 
 ```Shield Studies can only collect Type 1 and 2 data. This is the same type of basic interaction data we collect by default as stated in our privacy policy. ```

Read their privacy policy and you will see what I mean. GDPR regulations are much stricter than you probably imagine.

**Comment by orivej** [comment]
Indeed, but GDPR "shall apply from 25 May 2018", and Mozilla will release a compliant Firefox by that time. (If it is not compliant now: I can't judge yet.) [Here](https://blog.mozilla.org/netpolicy/2016/05/25/the-countdown-is-on-24-months-to-gdpr-compliance/) they say:

> Any business that markets goods or services to users in the EU will be subject to compliance, regardless of whether their business is located in the EU.
> We will continue to track the implications of the GDPR over the next 24 months as it comes into force, and will stay engaged with any opportunities to work out the final details.

**Comment by grahamc** [comment]
Seems sufficient to me, thank you @orivej.
