### ISSUE TITLE
Package request: Brasero

### ISSUE THREAD

**Issue by DDrozdzz-1066** [NixOS/nixpkgs#321717]
**Project description**
A free and open-source disc-burning program for Unix-like operating systems

**Metadata**

* homepage URL: https://wiki.gnome.org/Apps/Brasero
* source URL: https://gitlab.gnome.org/GNOME/brasero
* license: GNU General Public License
* platforms: unix, linux,

**Comment by TanvirOnGH** [comment]
@DDrozdzz-1066 It's already present. I can find two packages: `brasero` and `brasero-original`. 
See: https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=Brasero

**Comment by matteo-pacini** [comment]
@DDrozdzz-1066 closing as per @TanvirOnGH 's comment above
