### ISSUE TITLE
Package request: cavalcade

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#321764]
**Project description**

Python wrapper for [C.A.V.A.](https://github.com/karlstav/cava) utility with his own drawing window, gui settings and basic audio player functions. ([Video demo](https://www.youtube.com/watch?v=wAZ6MnVueNY))

**Metadata**

* homepage URL: https://github.com/worron/cavalcade
* source URL: https://github.com/worron/cavalcade
* license: gpl3
* platforms: linux

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/330067
