### ISSUE TITLE
`flutter323` does not actually provide the beta version

### ISSUE THREAD

**Issue by manuel-plavsic** [NixOS/nixpkgs#321798]
### Describe the bug
`flutter323` does not actually provide the beta version; instead, it provides flutter 3.22.

### Steps To Reproduce
1. run `flutter --version`. For me, the output is:
   ```
    ❯ flutter --version
    Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
    Framework • revision nixpkgs000 () • 1970-01-01 00:00:00
    Engine • revision edd8546116
    Tools • Dart 3.4.3 • DevTools 2.34.3
    ```  
2. however, `dart --version` correctly outputs `Dart SDK version: 3.5.0-180.3.beta (beta) (Wed Jun 5 15:06:15 2024 +0000) on "linux_x64"`.
3. I tried running `flutter clean`, but it did not help.
4. `which flutter` shows `/nix/store/6yrk78xybaj11akan3pfx1mwzi0zm7di-flutter-wrapped-3.23.0-0.1.pre-sdk-links/bin/flutter`

### Notify maintainers

@RossComputerGuy 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
CC @NixOS/flutter

**Comment by RossComputerGuy** [comment]
Do other Flutter versions report right? This issue looks very strange as we write the version during build time directly into the Flutter derivation.

**Comment by manuel-plavsic** [comment]
`flutter319` results in something similar...

```
❯ flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision nixpkgs000 () • 1970-01-01 00:00:00
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

```
❯ dart --version
Dart SDK version: 3.3.2 (stable) (Tue Mar 19 20:44:48 2024 +0000) on "linux_x64"
```

 I am starting to believe the problem might be on my side. I am not a Nix expert, do you have some commands I can run to troubleshoot this further?

**Comment by RossComputerGuy** [comment]
Yeah, you can use `nix repl` to try and evaluate what's going on. Check the unwrapped attribute in Flutter and see what the `buildPhase` has in it.

**Comment by manuel-plavsic** [comment]
When using `nix shell nixpkgs#flutter323`, then I get the expected flutter version:

```
❯ flutter --version
Flutter 3.23.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision nixpkgs000 () • 1970-01-01 00:00:00
Engine • revision bb10c54666
Tools • Dart 3.5.0-180.3.beta • DevTools 2.36.0
```

However, when using `nix develop` together with `flutter323` or `flutter319` in my project's flake, the wrong flutter version is shown.

**Comment by RossComputerGuy** [comment]
Using both versions in the same dev shell?

**Comment by manuel-plavsic** [comment]
I see what happened now. I just changed the flutter version in `buildInputs` of my flake.nix. However, I didn't think to change

```
FLUTTER_ROOT = flutter;
DART_ROOT = "${flutter}/bin/cache/dart-sdk";
```

to

```
FLUTTER_ROOT = flutter323;
DART_ROOT = "${flutter323}/bin/cache/dart-sdk";
```

Now everything works, thanks for your help.
