### ISSUE TITLE
catppuccin-cursors incorrect symlinks with home-manager

### ISSUE THREAD

**Issue by Dokkae6949** [NixOS/nixpkgs#321781]
### Describe the bug
The `Catppuccin-{color}-{variant}-Cursors` symlink inside of `~/.icons` is incorrect.
Well.. It is not directly incorrect. Rather the symlink at the location it's pointing to is incorrect.
Meaning `~/.icons ---> .../homa-manager-files/.icons -/-> .../catppuccin-cursors/share/icons`

The link between:
`.../homa-manager-files/.icons -/-> .../catppuccin-cursors/share/icons`
is broken as it points to a folder that doesn't exist. (it should link to an all lower case folder)

### Steps To Reproduce
1. Install catppuccin-cursors with home-manager
2. Select / Apply the cursors in your display manager.
3. It doesn't work / It will fallback to the default cursor as it can't find the catppuccin ones.

### Expected behavior

The catppuccin cursors should be used by the window manager.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/90514461/40675406-6004-4966-bc1c-5c8e94331287)

### Additional context
I'm using `Hyprland` with `hyprcursor` but also have everything setup for xcursor usage.

### Notify maintainers

@isabelroses 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3-zen1, NixOS, 24.11 (Vicuña), 24.11.20240605.e8057b6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(kurisu): `""`
 - nixpkgs: `/nix/store/8s55w0927lh3mdbkxf434zb0c5hqsz8z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
How did you install and configure it?

**Comment by Dokkae6949** [comment]
Using home-manager by settings:

```nix
let
  cursor-theme = "Catppuccin-Mocha-Dark-Cursors";
  cursor-package = pkgs.catppuccin-cursors.mochaDark;
in
{
  # ....

  home.sessionVariables = {
    NIXOS_OZONE_WL = "1";
    ANDROID_SDK_ROOT = "/home/kurisu/Android/Sdk";
    ANDROID_HOME = "/home/kurisu/Android/Sdk";
    XCURSOR_THEME = cursor-theme;
    # and some other variable (similar to xcursor) for Hyprlands hyprcursor.
    # tho I don't know it's exact name and I forgot to push it to gh so I can't look it up now
  };

  home.pointerCursor = {
    name = cursor-theme;
    package = cursor-package;
    size = 24;

    x11.enable = true;
    gtk.enable = true;
  };

  gtk = {
    enable = true;
    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
  };
  
  # ....
}
```

**Comment by eclairevoyant** [comment]
In that case it seems like your config should be updated?

```nix
home.pointerCursor.name = "catppuccin-mocha-dark-cursors";
```

**Comment by isabelroses** [comment]
lower case :)

**Comment by Dokkae6949** [comment]
Whoops that might make sense >.>

**Comment by Aleksanaa** [comment]
Yeah. Catppuccin developers are doing that all the time 😅

**Comment by eclairevoyant** [comment]
Same thing happened [with catppuccin-gtk](https://github.com/NixOS/nixpkgs/issues/298926#issuecomment-2018201465). As I mentioned there, sure we could standardise case/naming/etc within nixpkgs, but it'd be even more confusing for a new user to read the upstream code/docs and find that nixpkgs is doing something completely different. Hence I'd suggest we (continue to) follow upstream.

**Comment by isabelroses** [comment]
Catppuccin is standardizing on lowercase and american spellings, so we should just follow that imho

**Comment by eclairevoyant** [comment]
There is no standard; we just use whatever upstream calls it and don't rename anything in nixpkgs.
