### ISSUE TITLE
Update request: Plausible 2.0.0 → 2.1.0 or newer

### ISSUE THREAD

**Issue by techyporcupine** [NixOS/nixpkgs#321814]
- Package name: Plausible
- Latest released version: 2.1.1

- Current version on the unstable channel: 2.0.0
- Current version on the stable/release channel: 2.0.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@xanderio 

-----

Note for maintainers: Please tag this issue in your PR.

---

Note from author of issue: Looks iike from 2.0.0 to 2.1.0 there have been some larger changes made, so documentation may also need updating.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xanderio** [comment]
We're already tracking this in https://github.com/NixOS/nixpkgs/issues/314768
