### ISSUE TITLE
Default to the new Amazon NTP service on our AMIs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#32187]
[As of today](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html), AWS automatically provides NTP over the unroutable 169.254.169.123 address, so I think we should just default our NTP settings to point there for our AMIs.

@edolstra any objections?

**Comment by joelthompson** [comment]
Note this won't work (yet) on C5 or M5 instance types.
