### ISSUE TITLE
Running `dbt init` in nix shell fails due to file permissions.

### ISSUE THREAD

**Issue by hohmannr** [NixOS/nixpkgs#321808]
### Describe the bug

When running `nix-shell` with the package `dbt` and then initializing a dbt project with `dbt init` it fails with the following error:

```
17:32:56  Running with dbt=1.7.13
Enter a name for your project (letters, digits, underscore): test
17:32:58  Encountered an error:
[Errno 13] Permission denied: 'dbt_project.yml'
17:32:58  Traceback (most recent call last):
  File "/nix/store/632m9n7b5pcd7vx5d189bjrmcwkk20j4-python3.11-dbt-core-1.7.13/lib/python3.11/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/632m9n7b5pcd7vx5d189bjrmcwkk20j4-python3.11-dbt-core-1.7.13/lib/python3.11/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/632m9n7b5pcd7vx5d189bjrmcwkk20j4-python3.11-dbt-core-1.7.13/lib/python3.11/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/nix/store/632m9n7b5pcd7vx5d189bjrmcwkk20j4-python3.11-dbt-core-1.7.13/lib/python3.11/site-packages/dbt/task/init.py", line 340, in run
    self.create_new_project(project_name, profile_name)
  File "/nix/store/632m9n7b5pcd7vx5d189bjrmcwkk20j4-python3.11-dbt-core-1.7.13/lib/python3.11/site-packages/dbt/task/init.py", line 285, in create_new_project
    with open("dbt_project.yml", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'dbt_project.yml
```
When checking the directory with `ls -lavh` this is the result:

```
dr-xr-xr-x 1 rapha rapha  146 Jan  1  1970 my_demo_project
```

### Steps To Reproduce
1. `nix-shell -p dbt`
2. `dbt init my_demo_project`

### Expected behavior
Should create the project as expected and not error out.

### Notify maintainers

@mausch
@tjni

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/i1p0gshica1cnyzj5yc7hn342j3vws53-nix-info
copying path '/nix/store/i1p0gshica1cnyzj5yc7hn342j3vws53-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - nixpkgs: `/home/rapha/.nix-defexpr/channels/nixpkgs
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
It is most likely because this:
https://github.com/dbt-labs/dbt-core/blob/2bae05b8ed5c4e02c0575fc0a99e52ca6e4a8234/core/dbt/task/init.py#L53-L62
takes this directory (shipped inside package):
https://github.com/dbt-labs/dbt-core/tree/2bae05b8ed5c4e02c0575fc0a99e52ca6e4a8234/core/dbt/include/starter_project
and copies it over to where you run `dbt init`.
After that it tries to write something to `dbt_project.yml` inside that copy:
https://github.com/dbt-labs/dbt-core/blob/2bae05b8ed5c4e02c0575fc0a99e52ca6e4a8234/core/dbt/task/init.py#L287-L288

With `nix` source of that directory is inside `/nix/store` with no write permissions, so it is copied that way:
```text
ll /nix/store/7dkdnl4hbh9nbf88i999lllqcb6i0rdx-python3.11-dbt-core-1.7.14/lib/python3.11/site-packages/dbt/include/
dr-xr-xr-x    - root  1 Jan  1970 global_project/
dr-xr-xr-x    - root  1 Jan  1970 starter_project/
.r--r--r-- 1.5M root  1 Jan  1970 index.html
.r--r--r-- 4.8k root  1 Jan  1970 README.md
```

**Comment by hohmannr** [comment]
Thanks for the analysis. I will raise an issue with dbt.
