### ISSUE TITLE
Spotify cannot add source for local files

### ISSUE THREAD

**Issue by leon-erd** [NixOS/nixpkgs#321857]
### Describe the bug
When adding a local directory to spotify client, it always fails due to missing gsettings schema(s) and spotify crashes.
This issue is the same as the one from 2021 https://github.com/NixOS/nixpkgs/issues/120070.
Works as expected on arch based distros indicating that this an issue with nixpkgs

### Steps To Reproduce
1. run spotify
2. open Settings
3. turn on Show Local Files
4. click ADD A SOURCE button

### Expected behavior
Open a file chooser to select which directory to be added.

### Additional context
```
/home/leon/.nix-profile/bin/spotify: /nix/store/pqlfvq6nm4vq3cpd0f3wdl43wdvj958f-curl-8.8.0/lib/libcurl-gnutls.so.4: no version information available (required by /home/leon/.nix-profile/bin/spotify)
/nix/store/902fsnn62xgj3ljh092i9f9zb7k3j5jv-spicetify-Dribbblish/share/spotify/.spotify-wrapped: /nix/store/pqlfvq6nm4vq3cpd0f3wdl43wdvj958f-curl-8.8.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/902fsnn62xgj3ljh092i9f9zb7k3j5jv-spicetify-Dribbblish/share/spotify/.spotify-wrapped)
/nix/store/902fsnn62xgj3ljh092i9f9zb7k3j5jv-spicetify-Dribbblish/share/spotify/.spotify-wrapped: /nix/store/pqlfvq6nm4vq3cpd0f3wdl43wdvj958f-curl-8.8.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/902fsnn62xgj3ljh092i9f9zb7k3j5jv-spicetify-Dribbblish/share/spotify/.spotify-wrapped)

(spotify:132796): Gtk-WARNING **: 01:33:24.189: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(spotify:132796): GLib-GIO-CRITICAL **: 01:33:24.223: g_settings_schema_source_lookup: assertion 'source != NULL' failed
/proc/self/exe: /nix/store/pqlfvq6nm4vq3cpd0f3wdl43wdvj958f-curl-8.8.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)

(spotify:132796): GLib-GIO-ERROR **: 01:33:54.117: No GSettings schemas are installed on the system
[1]    132796 trace trap (core dumped)  spotify
```

### Notify maintainers
@eelco @ftrvxmtrx @sheenobu @mudri @timokau @Ma27 @jtojnar @freyacodes @BlankParticle @Gerg-L @mjoerg @Artturin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240618.c00d587`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/pfqbxdicyksnqda6h5xv285sx7vamwzd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
I can't actually reproduce the issue, but I do see some inherent packaging issues that I attempted to address. Can you test the linked PR?

**Comment by freyacodes** [comment]
I also cannot reproduce the issue. However, I have never actually had local files appear after I have added their directories (without crashing).

**Comment by leon-erd** [comment]
@eclairevoyant Yes your PR solves the issue!!! Thanks a lot for the fast reply :)
I would really like to learn more about packaging programs for nixpkgs so I can contribute more myself.
Do you have any recommendations on how to learn the different options for mkDerivation, the different phases, wrapping programs and libraries, etc.? I feel like the documentation is basically non-existend.
If anything comes to mind (including workshops, etc.) feel free to just send me an email leonvincenterd@web.de (this issue is probably the wrong place to discuss this)
