### ISSUE TITLE
Gnome: Keyboard layout issues since 3.26

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#32195]
## Issue description
I do not know how to describe this or how to pinpoint this issue.

But, probably since gnome 3.26 I have weird issues regarding keyboard layouts.

Some keys (mostly special keys) register as other keys than expected.

| Key Pressed | Event Registred | Comment |
| ----------- | ---------------------- | ------- |
| Left Arrow | ISO_Level3_Shift | Captured by xev |
| Down Arrow | Super_R | Captured by xev |
| Up Arrow | Screenshot | Not actually captured by xev, but that's the effect |
| Right Arrow | NoSymbol | Captured by xev |
| ISO_Level3_Shift | KP_Enter | Captured by xev |
| Page Up | / | Captured by xev |
| Page Down | Menu | Captured by xev |

I can also note here: Both my keyboards works as expected outside of gnome (tty for example). I haven't tested with other window environments.

### Steps to reproduce

Running on the latest checkout of nixos-unstable. Which happens to be on this commit at the moment: 4cbbecc85dbc5a040f2e4111093d30337718996a

This machines config is here: https://github.com/etu/nixconfig/blob/master/hosts/phouchg/configuration.nix
Here is my configs related to non-graphical stuff (like creating users and such): https://github.com/etu/nixconfig/blob/master/profiles/common.nix
Here is my configs related to graphical stuff not related to gnome: https://github.com/etu/nixconfig/blob/master/profiles/common-graphical.nix
Here is my configs related to gnome: https://github.com/etu/nixconfig/blob/master/profiles/desktop-gnome.nix

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.2, NixOS, 18.03.git.4cbbecc85dbM (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre120398.aeff3080d0"`
 - nixpkgs: `/etc/nixos/nixpkgs`

cc @jtojnar (probably?)

**Comment by jtojnar** [comment]
We are using libinput for handling keyboard events (https://github.com/NixOS/nixpkgs/pull/31995) and it does not like `Option "XkbRules" "base"`. You can remove the whole Xorg configuration block in https://github.com/etu/nixconfig/blob/deabec5bfd7210a8b3d607a16ed4874dc60025aa/profiles/desktop-gnome.nix#L14-L26, the GSettings override should be sufficient for both GNOME session and GDM thanks to #31683.

**Comment by etu** [comment]
@jtojnar Oh, thanks. That works. 👍
