### ISSUE TITLE
NixOS WiFi configuration

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32196]
## Issue description
`[   41.705588] iwlwifi 0000:04:00.0: Direct firmware load for iwlwifi-8265-33.ucode failed with error -2`

I would be happy to hear about any kernel version where it does work. I tried `boot.kernelPackages = pkgs.linuxPackages_latest;` too.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 17.09.2182.7f6f0c49f0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by orivej** [comment]
If it works with another Linux distribution, could you attach its dmesg?

**Comment by williammpratt** [comment]
I don't know whether it works with another Linux distribution.

**Comment by orivej** [comment]
Could you post the complete `dmesg | grep iwlwifi` from NixOS here?

**Comment by orivej** [comment]
Ah, first of all try setting `hardware.enableRedistributableFirmware = true`.

**Comment by williammpratt** [comment]
```
[   41.700386] iwlwifi 0000:04:00.0: enabling device (0000 -> 0002)
[   41.705588] iwlwifi 0000:04:00.0: Direct firmware load for iwlwifi-8265-33.ucode failed with error -2
[   41.705605] iwlwifi 0000:04:00.0: Direct firmware load for iwlwifi-8265-32.ucode failed with error -2
[   41.713910] iwlwifi 0000:04:00.0: loaded firmware version 31.560484.0 op_mode iwlmvm
[   41.779694] iwlwifi 0000:04:00.0: Detected Intel(R) Dual Band Wireless AC 8265, REV=0x230
[   41.888521] iwlwifi 0000:04:00.0: base HW address: redacted
[   42.439521] iwlwifi 0000:04:00.0 wlp4s0: renamed from wlan0
```
`iwlist scan` doesn't return anything. 

```
lsmod| grep iwlwifi
iwlwifi               217088  1 iwlmvm
cfg80211              503808  3 iwlmvm,iwlwifi,mac80211
```

**Comment by orivej** [comment]
`loaded firmware version 31.560484.0 op_mode iwlmvm` means that the firmware is successfully loaded. `iwlist scan` performs a scan only when you run it under `sudo`.

**Comment by williammpratt** [comment]
` wlp4s0    Interface doesn't support scanning : Network is down`

This is using wpa_supplicant.

**Comment by williammpratt** [comment]
Just in case, I rebooted without a direct ethernet connection and then I got the exact same response.

**Comment by orivej** [comment]
I'm not familiar with using wpa_supplicant directly, but `ifconfig wlp4s0 up` should solve this hurdle. Consider `networking.supplicant` configuration option which seems to provide some basic automation, or maybe NetworkManager (it has a terminal config tool `nmtui`).

**Comment by williammpratt** [comment]
`SIOCSIFFLAGS: Operation not possible due to RF-kill`

**Comment by williammpratt** [comment]
After `rfkill unblock wifi` it was unblocked and I can now ping devices via the wireless network.

This is a bug, because I shouldn't be required to make such imperative changes to network configuration.

**Comment by orivej** [comment]
You could have accidentally toggled rfkill via a button on your keyboard.

**Comment by williammpratt** [comment]
I checked and Fn + F8 on the laptop keyboard toggles the state displayed by `rfkill list`.

Are you sure that `nixos-rebuild switch` calls rfkill unblock wifi when wireless is enabled?

**Comment by orivej** [comment]
It does not and it should not.
