### ISSUE TITLE
gamemode: D-Bus error

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#321951]
### Describe the bug
GameMode is not starting on latest unstable.

### Steps To Reproduce
1. add `programs.gamemode.enable = true;` to config
2. run `gamemode -t`

### Expected behavior

It runs the gamemode test

### Screenshots

```
┌───────────────────>
│keenan in ~
❌130 ❄️ zsh ›
└─>gamemoded -t
: Loading config
Loading config file [/nix/store/yq6wdz71bi66x5h44l4isdd35jm2iwix-gamemode-1.8.1/share/gamemode/gamemode.ini]
Loading config file [/etc/gamemode.ini]
: Running tests

GameMode ERROR: D-Bus error: Could not call method 'QueryStatus' on 'com.feralinteractive.GameMode': Could not activate remote peer 'com.feralinteractive.GameMode': activation request failed: unknown unit
ERROR: gamemode_query_status failed: D-Bus error: Could not call method 'QueryStatus' on 'com.feralinteractive.GameMode': Could not activate remote peer 'com.feralinteractive.GameMode': activation request failed: unknown unit!
ERROR: is gamemode installed correctly?
```

### Additional context

[My config for gamemode is here](https://github.com/keenanweaver/nix-config/blob/main/modules/apps/gamemode/default.nix). Not sure if I've changed something that causes the error.

### Notify maintainers

@kira-bruneau 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.6, NixOS, 24.11 (Vicuna), 24.11.20240622.a71e967`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/yqy82fn77fy3rv7lpwa9m11w3a2nnqg5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
@keenanweaver Are you still running into this problem? I can't seem to reproduce it on my machine.

**Comment by keenanweaver** [comment]
> @keenanweaver Are you still running into this problem? I can't seem to reproduce it on my machine.

I am; not really sure what I've done to break it. I'm on `24.11.20240719.1d9c2c9`. 

If it's only me, I'm fine with closing the issue as I rarely use gamemode anymore.

**Comment by kira-bruneau** [comment]
Is `gamemoded.service` running?

```
systemctl status --user gamemoded.service
```

**Comment by keenanweaver** [comment]
> Is `gamemoded.service` running?
> 
> ```
> systemctl status --user gamemoded.service
> ```

It is not, in fact it doesn't exist at all. Weird!

```
┌───────────────────>
│keenan in ~
❄️ zsh ›
└─>stat /home/keenan/.config/systemd/user/gamemoded.service
  File: /home/keenan/.config/systemd/user/gamemoded.service -> /nix/store/1swkkkxrzdprhx49lflbwmsq3m13i056-gamemode-1.8.1/share/systemd/user/gamemoded.service
  Size: 95              Blocks: 8          IO Block: 4096   symbolic link
Device: 0,56    Inode: 27553060    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/  keenan)   Gid: (  100/   users)
Access: 2024-07-20 08:18:02.515303277 -0500
Modify: 2024-05-31 10:19:31.467153888 -0500
Change: 2024-05-31 10:19:31.467153888 -0500
 Birth: 2024-05-31 10:19:31.467153888 -0500

┌───────────────────>
│keenan in ~
❄️ zsh ›
└─>cat /nix/store/1swkkkxrzdprhx49lflbwmsq3m13i056-gamemode-1.8.1/share/systemd/user/gamemoded.service
cat: /nix/store/1swkkkxrzdprhx49lflbwmsq3m13i056-gamemode-1.8.1/share/systemd/user/gamemoded.service: No such file or directory
```

I do see the service here:
```
┌───────────────────>
│keenan in ~
❄️ zsh ›
└─>cat /nix/store/4pzdvjjlh9ly35lqm2jfj59qdmyv4vq1-unit-gamemoded.service/gamemoded.service
[Unit]

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/zshzrwn4zc9132jyz9xp11jr9agb4aqk-glibc-locales-2.39-52/lib/locale/locale-archive"
Environment="PATH=/nix/store/vzyp37b7sx71a65940dja16scb4s1l6v-pkexec"
Environment="TZDIR=/nix/store/k6vxnriwl3ywpmlmvif3zr418j7dwm1n-tzdata-2024a/share/zoneinfo"
ExecStart=
ExecStart=/run/wrappers/bin/gamemoded

[Install]
WantedBy=default.target
```

**Comment by kira-bruneau** [comment]
Oh that's really weird, it shouldn't even need to load it from `~/.config/systemd/user`. It looks like something else added that file?

The gamemode module uses `/etc/systemd/user/gamemoded.service` and it looks like it was just being overridden by what was in `~/.config/systemd/user`.
