### ISSUE TITLE
Mullvad-vpn "APP IS OUT OF SYNC" after 24.05 upgrade

### ISSUE THREAD

**Issue by mariaa144** [NixOS/nixpkgs#321971]
### Describe the bug
After upgrading to 24.05 I get a "APP IS OUT OF SYNC Please quit and restart app" error on the Mullvad GUI

### Steps To Reproduce
1. Update from 23.11 to 24.05 while having `mullvad-vpn` installed and configured.

### Expected behavior
The Mullvad GUI says "App out of sync Please quit and restart app" but seems to work normally otherwise.

### Screenshots
![Screenshot from 2024-06-22 13-20-54](https://github.com/NixOS/nixpkgs/assets/105451387/1c72aa14-ecde-4d47-bab4-f099ce9a62e8)

### Notify maintainers
@Br1ght0ne @ymarkus @ataraxiasjel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.05 (Uakari), 24.05.20240619.dd457de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(david): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/2lvj8bm21ymxra61dqrc4xpzr8njgywj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ymarkus** [comment]
I'm unable to reproduce sadly. Could you please send some more information, like your `configuration.nix` where you define mullvad?
Have you restarted the service or your machine?

**Comment by cole-h** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/322188 to update `mullvad`. However, I'm not sure how much influence it has over the `mullvad-vpn` GUI, so that still might not fix the issue.

**Comment by mariaa144** [comment]
I followed the wiki and added `services.mullvad-vpn.package = pkgs.mullvad-vpn;` and now I don't have `mullvad` installed anymore and I don't have the error anymore on my app.

https://nixos.wiki/wiki/Mullvad_VPN

**Comment by ymarkus** [comment]
Should we add a comment to both mullvad packages so they are updated together? Or is this a minor issue?
