### ISSUE TITLE
Package request: taggui

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#321938]
**Project description**

Cross-platform desktop application for quickly adding and editing image tags and captions, aimed towards creators of image datasets for generative AI models like Stable Diffusion.

**Metadata**

* homepage URL: https://github.com/jhc13/taggui
* source URL: https://github.com/jhc13/taggui
* license: gpl3
* platforms: linux, windows

**Comment by Sigmanificient** [comment]
Without a `setup.py` it is a bit of a mess to package

**Comment by Ethorbit** [comment]
> Without a `setup.py` it is a bit of complex to package

I have ported taggui v1.33.0 to [my Nix packages flake](https://github.com/Ethorbit/nix-packages).

---
Package: [taggui](https://github.com/Ethorbit/nix-packages/blob/main/pkgs/applications/editors/taggui/default.nix)

Dependencies that were missing from the nix repo, which I ported as well:
* [gptqmodel](https://github.com/Ethorbit/nix-packages/tree/main/pkgs/development/python-modules/gptqmodel/default.nix)
* [device-smi](https://github.com/Ethorbit/nix-packages/blob/main/pkgs/development/python-modules/device-smi/default.nix)
* [logbar](https://github.com/Ethorbit/nix-packages/blob/main/pkgs/development/python-modules/logbar/default.nix)
* [tokenicer](https://github.com/Ethorbit/nix-packages/tree/main/pkgs/development/python-modules/tokenicer/default.nix)
* [random-word](https://github.com/Ethorbit/nix-packages/tree/main/pkgs/development/python-modules/random-word/default.nix)
 ---

Feel free to import the flake and add:
```nix
environment.systemPackages = [ ethorbit.taggui ];
```

**Comment by Ethorbit** [comment]
> Maybe send a pr to contribute it to nixpkgs!

I would, but I don't have enough experience with Nix to confidently contribute to nixpkgs yet.

I'm hoping someone can refine it and make a pull request.

**Comment by Sigmanificient** [comment]
I can help you get through it 😄
