### ISSUE TITLE
gpt4all-cuda: No cuda acceleration

### ISSUE THREAD

**Issue by VeilSilence** [NixOS/nixpkgs#321928]
### Describe the bug
Greetings.
I'm trying to run gpt4all in cuda acceleration, but there is no option for CUDA acceleration in app. 
Launching from terminal give me this error:failed to initialize CUDA: CUDA driver is a stub library

### Steps To Reproduce
1. install gpt4all-cuda
2. Settings -> Applictiation->Device 
3. In device section, there is only CPU and Auto

### Expected behavior
Cuda device should be detectable.

### Additional context
Exporting `LD_LIBRARY_PATH="/run/opengl-driver/lib"` resolve this issue and gpt4all detect cuda device.

### Notify maintainers
@drupol
@Polygon

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.22.0pre20240422_5ecd820`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
I'm sorry I won't be able to help since I don't particularly use it anymore and I don't have any NVidia devices.

**Comment by VeilSilence** [comment]
> I'm sorry I won't be able to help since I don't particularly use it anymore and I don't have any NVidia devices.

Understandable.  
Maybe @NixOS/cuda-maintainers can take are look here then, because not only this app affected by this bug as far as i can see.

**Comment by VeilSilence** [comment]
Small overlay wrapper in case anyone have this issue also:
```Nix
      (self: super: {
        gpt4all-cuda = super.gpt4all-cuda.overrideAttrs (oldAttrs: rec {
          postInstall =
            ''
              wrapProgram $out/bin/chat \
                --set LD_LIBRARY_PATH "/run/opengl-driver/lib"
            ''
            + (oldAttrs.postInstall or "");
        });
      })
      
```

Probably something similar required for amd card.

**Comment by SomeoneSerge** [comment]
Hi @VeilSilence, thanks for reporting the issue and finding the fix. Could you please submit a PR? Instead of using the wrapper you can add `autoAddDriverRunpath` to the package's `nativeBuildInputs` (best in the part of the list conditioned on `cudaSupport`).

> Probably something similar required for amd card.

That's the nice thing about ROCm: nothing of the sort is required; you can just link the driver directly, no need to play hide-n-seek with nvidia. However I don't see any `rocmPackages` references in the gpt4all expression or in the upstream repo, I'm not sure they support ROCm. One could still use the cuda version with amd devices, via `${zluda}/lib` in `LD_LIBRARY_PATH`

**Comment by VeilSilence** [comment]
> Hi @VeilSilence, thanks for reporting the issue and finding the fix. Could you please submit a PR? Instead of using the wrapper you can add `autoAddDriverRunpath` to the package's `nativeBuildInputs` (best in the part of the list conditioned on `cudaSupport`).
> 
> > Probably something similar required for amd card.
> 
> That's the nice thing about ROCm: nothing of the sort is required; you can just link the driver directly, no need to play hide-n-seek with nvidia. However I don't see any `rocmPackages` references in the gpt4all expression or in the upstream repo, I'm not sure they support ROCm. One could still use the cuda version with amd devices, via `${zluda}/lib` in `LD_LIBRARY_PATH`

https://github.com/NixOS/nixpkgs/issues/298997 guy have same issue, but with AMD card.
About sumbiting a PR. I don't feel confident enough in nixos to do such thing for now.

**Comment by SomeoneSerge** [comment]
> About sumbiting a PR. I don't feel confident enough in nixos to do such thing for now.

Do as you feel is best for you, but do know that we'd guide you and that the entry threshold is meant to be kept low

**Comment by haras-unicorn** [comment]
@SomeoneSerge added the PR that adds `autoAddDriverRunpath` if `cudaSupport` is enabled in #342251 if you could take a look at it pls.
