### ISSUE TITLE
ZeroTier One: ERROR: unable to parse local.conf (root element is not a JSON object)

### ISSUE THREAD

**Issue by ca5ua1** [NixOS/nixpkgs#322083]
### Describe the bug
ZeroTier systemd service fails with following error at nixos unstable:
```
zerotier-one[50525]: ERROR: unable to parse local.conf (root element is not a JSON object)
systemd[1]: zerotierone.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: zerotierone.service: Failed with result 'exit-code'.
systemd[1]: zerotierone.service: Scheduled restart job, restart counter is at 5.
systemd[1]: zerotierone.service: Start request repeated too quickly.
systemd[1]: zerotierone.service: Failed with result 'exit-code'.
systemd[1]: Failed to start ZeroTierOne.
```
By checking that local.conf, we can see funny thing, it's literal 'null':
```
nixos ➤ sudo cat /var/lib/zerotier-one/local.conf  
null
```
Here is quick fix: 
```
services.zerotierone.localConf = { 
  settings = { 
    softwareUpdate = "disable";
  };
};
```
### Steps To Reproduce
1. Don't have any `services.zerotierone.localConf` options
2. Start/restart zerotier service

### Notify maintainers

@sjmackenzie 
@zimbatm 
@ehmry 
@obadz 
@danielfullmer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.6-zen1, NixOS, 24.11 (Vicuna), 24.11.20240622.9693852`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixpkgs"`
 - channels(casual): `""`
 - nixpkgs: `/home/casual/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cmm** [comment]
the fix: https://github.com/NixOS/nixpkgs/pull/321984
(still have to manually remove the `local.conf` symlink from `/var/lib/zerotier-one` though)

**Comment by Mic92** [comment]
Fix was merged.

**Comment by KenMacD** [comment]
While I'm sure this fixes new runs, it still requires manual intervention for existing installs. Unfortunately this isn't possible if a server is only available over zerotier. Any chance of fixing being added for existing installs?

**Comment by Mic92** [comment]
Maybe a systemd-tmpfiles rule that deletes this file that is only enable `lib.mkIf services.zerotierone.localConf == null`?

**Comment by Mic92** [comment]
Probably makes sense to have this anyway because removing your settings, won't delete the json file.

**Comment by Mic92** [comment]
> While I'm sure this fixes new runs, it still requires manual intervention for existing installs. Unfortunately this isn't possible if a server is only available over zerotier. Any chance of fixing being added for existing installs?

Can you test https://github.com/NixOS/nixpkgs/pull/323785 ?

**Comment by KenMacD** [comment]
@Mic92: not looking to bug you, just in case you didn't see it, I did comment on the PR. I look forward to seeing it merged. (My fallback plan is to wait for the eventual `collect-garbage` to break the symlink.)
