### ISSUE TITLE
Should we run `.../node-packages/generate.sh` in batches instead of on every new package?

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#322064]
Should we run [`pkgs/development/node-packages/generate.sh`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/generate.sh) in batches instead of on every new package?

Currently:
* The script takes about four hours to run ([source](https://github.com/NixOS/nixpkgs/issues/229475)).
* It can cause merge conflicts whenever a new `nodePackages` package is merged. ([look at all of these closed `nodePackages` PRs that had merge conflicts!](https://github.com/NixOS/nixpkgs/issues?q=label%3A%222.status%3A+merge+conflict%22+nodePackages+is%3Aclosed))
* The same updates are performed many times when multiple PRs adding to `nodePackages` are filed, wasting compute time.

If this is a bad idea, please tell me :) I'm not very familiar with `nodePackages`.

## Proposal

Run `node-packages/generate.sh` on a weekly (or other time period) basis (either manually or automatically), instead of instructing developers to run it when adding a new package.

Discourage developers from running the script when adding a new package.

### Considerations

Would the Node team become overwhelmed by this?

Should we automate the proposed process (sans merging)?

Is this even worth formalizing, considering that we [are actively phasing out packages in `nodePackages`](https://github.com/NixOS/nixpkgs/issues/229475)?

## Maintainers

Pinging @NixOS/node.

**Comment by tomodachi94** [comment]
An alternative would be to modify `generate.sh` to support generating specific attributes, but I'm not sure how difficult this would be to implement.

**Comment by pyrox0** [comment]
I don't think this should be formalized, as we should be working to remove as many packages as possible from `node-packages` into the main set, or drop those that are unused. For instance, why is bower still listed? It's been unmaintained for many years now(last commit was 2 years ago), and thus I feel it should be dropped. Doing any sort of regular maintainence on the set is a hassle, and I think setting up CI for it only encourages the migration to take longer than it has to.

**Comment by SuperSandro2000** [comment]
node2nix doesn't support running this in batches or parallel. 

Also see previous comment

**Comment by tomodachi94** [comment]
> node2nix doesn't support running this in batches or parallel.

Yes, I'm aware.

> ## Proposal
> Run node-packages/generate.sh on a weekly (or other time period) basis (either manually or automatically), instead of instructing developers to run it when adding a new package.

But I agree that we should probably freeze the package set (except for package removals).
