### ISSUE TITLE
Package request: stremio-shell

### ISSUE THREAD

**Issue by TGHx** [NixOS/nixpkgs#322065]
**Project description**

Stremio offers a secure, modern and seamless entertainment experience. With its easy-to-use interface and diverse content library, including 4K HDR support, users can enjoy their favorite movies and TV shows across all their devices. 

**Metadata**

* homepage URL: https://www.stremio.com/
* source URL: https://github.com/Stremio/stremio-shell
* license: gpl3+
* platforms: Linux, Mac, Windows, Android

**Comment by Steinhagen** [comment]
stremio-shell is already packaged in nixos under the name: stremio
https://search.nixos.org/packages?channel=unstable&show=stremio

**Comment by d4rk** [comment]
Can we close this issue since the requested package already exists?

**Comment by Steinhagen** [comment]
The package is already in nixpkgs and is up-to-date.
