### ISSUE TITLE
GNOME cartridges: games not appearing in search

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#322013]
### Describe the bug
As of Cartridges v2.6 it should be possible to have games listed in GNOME Cartridges appear in search

### Steps To Reproduce
1. Install GNOME + Cartridges
2. Add a game to Cartridges
3. Search for that game in GNOME's search

### Expected behavior
The game should be listed in the search results

### Additional context
I have enabled Cartridge's search provider in GNOME settings

### Notify maintainers
@getchoo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
i'm not very familiar with gnome search providers, but after taking a quick look at the package's output path it seems it is installed  correctly to `$out/share/gnome-shell/search-providers/page.kramo.Cartridges.SearchProvider.ini`; fields like the DesktopId and ObjectPath seem to be correct as well. given that it also shows up in gnome's settings, i lean towards this possibly being an upstream bug?

i'm going to be switching back to gnome after trying out plasma 6 for the last few months, so i'll be able to do some better testing then. thanks for letting me know about this!
