### ISSUE TITLE
Plasma5/KScreen Scale Display button does not work in all cases

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32219]
## Issue description
Pressing the "Scale Display button" has no effect for the smallest of the two configured screens. 

![image](https://user-images.githubusercontent.com/33880204/33474550-7aa35e66-d67b-11e7-9926-6f14ef2d3de1.png)

The result is that I cannot configure independent sizes for the two displays, which results in either really big displayed characters and buttons on the physically larger (but lower resolution) screen or really small characters and buttons on the physically smaller (but higher resolution) screen. 

### Steps to reproduce
Have a multi-monitor setup
All configuration is done via kscreen.
Press the Scale Display button.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bkchr** [comment]
That is no bug of NixOS. The X-Server does not support independent scaling per screen, just one scaling for all screens. You will need to wait for wayland.
