### ISSUE TITLE
Update request: zola 1.18.0 → 1.19.0

### ISSUE THREAD

**Issue by heitorPB** [NixOS/nixpkgs#322195]
- Package name: Zola
- Latest released version: 1.19.0

- Current version on the unstable channel: 1.18.0
- Current version on the stable/release channel: 1.18.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dali99 @0x4A6F @dywedir 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
This is blocked on #320250 being merged, as some of its dependences rely on rust 1.79.0

**Comment by heitorPB** [comment]
PR with the upgrade: https://github.com/NixOS/nixpkgs/pull/325370

**Comment by donovanglover** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/332403
