### ISSUE TITLE
Cannot initialize PostgreSQL with an empty but existing data directory

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#3221]
We want to run PostgreSQL on a separate drive, so /var/db/postgresql already exists. However, the pre-start script only runs if the data directory doesn't exist at all, and thus PostgreSQL cannot start up without manual help.

**Comment by danbst** [comment]
Should be fixed in master https://github.com/NixOS/nixpkgs/commit/b21fd5d066baadb06ca8e9a2accfcb4e94c60a09

**Comment by grahamc** [comment]
This looks like it should definitely be fixed, @ocharles. Can you confirm, or should we close it?

**Comment by Mic92** [comment]
I think this issue can be closed now.
