### ISSUE TITLE
Package request: qBittorrent-Enhanced-Edition

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#322158]
**Project description**

An unofficial version of qBittorrent featuring community enhancements such as: automatic banning of Xunlei, QQ, Baidu, Xfplay, DLBT, and Offline downloader; an option to automatically ban unknown peers from China; automatic updating of public trackers list; an option to automatically ban BitTorrent media player peers; and peer whitelisting/blacklisting.

**Metadata**

* homepage URL: https://github.com/c0re100/qBittorrent-Enhanced-Edition
* source URL: https://github.com/c0re100/qBittorrent-Enhanced-Edition
* license: gpl2/gpl3, See [copying](https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_6_x/COPYING)
* platforms: unix, linux, darwin, windows

**Comment by Guanran928** [comment]
It is currently available in berberman's flake: https://github.com/berberman/flakes
