### ISSUE TITLE
Build failure: nixosTests.installed-tests.pipewire (pipewire)

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#322148]
### Steps To Reproduce

At master:
1. nix build .#nixosTests.installed-tests.pipewire

### Build log

```
>   File "/nix/store/sffpwqark4h2969lwniqicnfpzvqsmc7-nixos-test-driver-1.1/lib/python3.11/site-packages/test_driver/machine.py", line 611, in succeed
       >     raise Exception(f"command `{command}` failed (exit code {status})")
       > Exception: command `gnome-desktop-testing-runner  -d '/nix/store/wkw7lszrap1x9hbca4snflcn6vr6lc15-pipewire-1.0.7-installedTests/share'` failed (exit code 2)
```
Logs: https://termbin.com/kvnc

### Additional context

- Test is failing for master.

(Opening issue to track issue until resolution.)

### Notify maintainers

CC @kranzes @k900

**Comment by K900** [comment]
It's a known thing, our VMs don't have sound outputs.

**Comment by superherointj** [comment]
> It's a known thing, our VMs don't have sound outputs.

Can't it be marked broken?
