### ISSUE TITLE
Package request: gopeed

### ISSUE THREAD

**Issue by Tanvir1337x** [NixOS/nixpkgs#322155]
**Project description**

Gopeed (full name Go Speed), a high-speed download manager, supports (HTTP, BitTorrent, Magnet) protocol, and supports all platforms. It is also a highly customizable that supports implementing more features through integration with [APIs](https://docs.gopeed.com/dev-api.html) or installation and development of [extensions](https://docs.gopeed.com/dev-extension.html).

**Metadata**

* homepage URL: https://gopeed.com/
* source URL: https://github.com/GopeedLab/gopeed
* license: gpl3
* platforms: linux, darwin, windows, ios, android, docker, web

**Comment by ByteSudoer** [comment]
@TanvirOnGH  I created a PR https://github.com/NixOS/nixpkgs/pull/322431 based on this packaging request. you can wait for it to be merged or use the already created derivation.
