### ISSUE TITLE
Telegraf extraConfig is not recursively merged

### ISSUE THREAD

**Issue by lopsided98** [NixOS/nixpkgs#32217]
## Issue description

Telegraf's `extraConfig` option has type `attrs` rather than being a submodule. This attrset is simply converted to TOML to generate the configuration file. Since the configuration consists of a number of nested sets, unexpected behavior occurs when options are set in multiple modules. The set is only merged one level deep, whereas options that use submodules are recursively merged. This makes it impossible to override a single plugin option.

I am currently working around this problem by using `recursiveUpdate` to merge the options, but I think this solution has problems with option priorities and orders.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 18.03pre121706.b9347167822 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121706.b9347167822"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by makefu** [comment]
I can confirm this issue, i tried to have multiple extraConfig entries from different `imports` and only the first one applies.

**Comment by sorpaas** [comment]
What would break if we simply change `types.attr` to use `lib.recursiveUpdate`? I believe that should just work and fix this issue?

**Comment by makefu** [comment]
still important for me!

**Comment by bgamari** [comment]
I have also observed this.

**Comment by makefu** [comment]
in 20.09 a similar issue got solved with the home-assistant config, maybe a similar change could be applied to telegraf?

/cc @Mic92

**Comment by Mic92** [comment]
This was fixed in 8edc4619abc884d97583c1ec714c9f7c795fbbac
