### ISSUE TITLE
Update request: wash-cli 0.24 → 0.29

### ISSUE THREAD

**Issue by cowboyai** [NixOS/nixpkgs#322292]
- Package name: wash-cli
- Latest released version: 0.29
- Current version on the unstable channel: 0.24
- Current version on the stable/release channel: 0.24
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
only 0.24->0.28 is available... https://github.com/NixOS/nixpkgs/pull/315370
for 0.29, the maintainers now have wash-cli as part of the mono-repo which will take a different approach to get the right part of the repository for wash-cli which is now in https://github.com/wasmCloud/wasmCloud/tree/main/crates/wash-cli
I don't know how to do this without a bunch of pre and postfetch nonsense, I am sure someone does.

**Comment by JohnAZoidberg** [comment]
> for 0.29, the maintainers now have wash-cli as part of the mono-repo which will take a different approach

Not a problem actually, we fetch it from crates.io, not the github repo.
