### ISSUE TITLE
Build failure: paperless

### ISSUE THREAD

**Issue by MartiniMoe** [NixOS/nixpkgs#322212]
### Steps To Reproduce

1. build nixos config with paperless; see my config [here](https://git.sr.ht/~martinimoe/nixos-config/tree/main/item/nixos/caprica/paperless.nix)
2. building fails with `FAILED src/paperless_tesseract/tests/test_parser.py::TestParser::test_rtl_language_detection - AssertionError: 'ةﯾﻠﺧﺎدﻻ ةرازو' not found in '\u202bال\u202c\n\u202bا\u202c...`

### Build log

https://gist.github.com/MartiniMoe/6dce558ffc12c0b09d77e43e7b8758de

### Additional context

It used to build and run fine before updating my flake inputs today.

### Notify maintainers

@lukegb @erikarvstedt @leona-ya 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1, NixOS, 24.05 (Uakari), 24.05.20240615.752c634`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/mcwr2j04fikfsrsaq76f4bviinvl6zql-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
Should be fixed by #322190, which you can track here: https://nixpk.gs/pr-tracker.html?pr=322190
