### ISSUE TITLE
qbittorrent-nox: missing meta.mainProgram

### ISSUE THREAD

**Issue by Mojken** [NixOS/nixpkgs#322456]
*No bug so skipping the steps-to-reproduce stuff and all that. It works as it is, but throws a warning.*

Needed for things like lib.getExe, which is a common pattern in systemd services - something very reasonable to assume people would want for a package like this.

https://github.com/NixOS/nixpkgs/blob/e4509b3a560c87a8d4cb6f9992b8915abf9e36d8/pkgs/applications/networking/p2p/qbittorrent/default.nix#L92-L99

Suggested fix:
`mainProgram = "qbittorrent-nox";`

@Anton-Latukha  @kashw2

**Comment by eclairevoyant** [comment]
feel free to send a PR yourself :) it's not restricted to maintainers

**Comment by kashw2** [comment]
As qbittorrent has three varients in nixpkgs (`qbittorrent-nox`, `qbittorrent-qt` and `qbittorrent`). I'm not sure what one we want to specify as the actual main program. We could use the same logic we use to separate the pnames.

**Comment by Mojken** [comment]
> As qbittorrent has three varients in nixpkgs (`qbittorrent-nox`, `qbittorrent-qt` and `qbittorrent`). I'm not sure what one we want to specify as the actual main program. We could use the same logic we use to separate the pnames.

Oh, wow, I didn't even notice they were the same package. I mean, we should be able to figure it out using something like `qbittorrent${lib.optionalString (!guiSupport) "-nox"}`, right? Maybe something extra for -qt as well?
