### ISSUE TITLE
Build cargo-vendor from source

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#32254]
Since https://github.com/NixOS/nixpkgs/commit/491e5d8649e8587654a81baf119e3b66bce65102 rustc works on aarch64, but cargo doesn't because we depend on binary releases of cargo-vendor (https://github.com/alexcrichton/cargo-vendor/releases) but upstream doesn't provide binaries for non-x86.

**Comment by andir** [comment]
Any ideas on how to get started with this? We probably have to (semi) manually keep track of the dependencies (of one version)?

Once the first version exists we could probably refer to that as some kind of bootstrap stage to build newer versions of `cargo-vendor` using itself?

**Comment by dezgeg** [comment]
I've learned since that there's a tool called carnix (https://github.com/NixOS/nixpkgs/pull/31150) that would probably help here.

**Comment by dezgeg** [comment]
Fixed since #33980 was merged.
