### ISSUE TITLE
Build failure: `python3Packages.flax`

### ISSUE THREAD

**Issue by aryanjassal** [NixOS/nixpkgs#322586]
### Steps To Reproduce

1. build `pkgs.python312Packages.flax`

### Build log

```console
[user@system:~]$ nix develop
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'od-devshell'
         whose name attribute is located at /nix/store/244kjyilbmi4mr3lpgk95wc18v9w73wh-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildInputs' of derivation 'od-devshell'

         at /nix/store/244kjyilbmi4mr3lpgk95wc18v9w73wh-source/pkgs/stdenv/generic/make-derivation.nix:378:7:

          377|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          378|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          379|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: ipython-genutils-0.2.0 not supported for interpreter python3.12
```

Detailed build log: [gist](https://gist.github.com/aryanjassal/b43e3a996bbcbce86fc70f9bbd1f187c)

### Additional context

This was happening with commit `9c513fc6fb75142f6aec6b7545cb8af2236b80f5` (latest `nixpkgs-unstable` as of writing this) and `2893f56de08021cffd9b6b6dfc70fd9ccd51eb60` (latest `nixos-unstable` as of writing this). After changing the branch to `906320ae02f769d13a646eb3605a9821df0d6ea2` (latest `nixos-23.11` as of writing this), the issue went away. The packages are also not marked as "broken" either. The broken commits are dated 24th June and 25th June respectively, where the working commit is dated 23rd June.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, Dell Precision 3480, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
FYI if you want to use python 3.11 you'd have to explicitly use `python311Packages`.

**Comment by aryanjassal** [comment]
> FYI if you want to use python 3.11 you'd have to explicitly use `python311Packages`.

I tried using `python311Packages`, `python312Packages` and even `python3Packages` but this issue remained on the two broken commits.

**Comment by eclairevoyant** [comment]
The error (and the code shat generates it) specifically mention that the dependency is not available for python 3.12, so that's impossible for you to have the same error with pyshon311Packages.

**Comment by aryanjassal** [comment]
> The error (and the code shat generates it) specifically mention that the dependency is not available for python 3.12, so that's impossible for you to have the same error with python311Packages.

Ah, I wasn't clear in the description. I get a similar error, but with python311Packages instead of 312. I will update thr issue to better reflect this

**Comment by aryanjassal** [comment]
The `python311Packages` issue was actually due to a much older commit, as I can't see this issue when I'm trying to compile it now.

Instead, I get this error similar to [this](https://github.com/NixOS/nixpkgs/issues/296737#issuecomment-2185472893).

Even though the issue is not related to `python311Packages.flax` anymore, it still exists for `python312Packages.flax`, and the package isn't marked broken either.

**Comment by eclairevoyant** [comment]
> I get this error similar to [this](https://github.com/NixOS/nixpkgs/issues/296737#issuecomment-2185472893).

Which is already being discussed under #321920.

> it still exists for `python312Packages.flax`, and the package isn't marked broken either

It pretty explicitly tells you that python 3.12 is unsupported for the `ipython-genutils` dependency, not sure what more can be done here?

**Comment by aryanjassal** [comment]
> It pretty explicitly tells you that python 3.12 is unsupported for the `ipython-genutils` dependency, not sure what more can be done here?
I looked at the package information on [mynixos.com](https://mynixos.com) and it stated that the `python312Packages.flax` was not broken, which is why I was confused. My proposed solution would be to simply change the metadata to reflect that.

> btw, neither of these errors are related to flax.
I guess you're right about that. This issue is no longer about `python3Packages.flax`'s build failure, so I will be closing it then.

**Comment by eclairevoyant** [comment]
> I looked at the package information on [mynixos.com](https://mynixos.com) and it stated that the `python312Packages.flax` was not broken

https://github.com/NixOS/nixpkgs/blob/59b1aef59071cae6e87859dc65de973d2cc595c0/pkgs/development/python-modules/ipython-genutils/default.nix#L16-L17 is what indicates that the package isn't available for a certain python interpreter version. mynixos isn't an official tool, so we don't have control over how they display that information, but ultimately the most straightforward way to know if some package's dependency tree is buildable, is to try to build it.
