### ISSUE TITLE
bash-language-server is missing

### ISSUE THREAD

**Issue by MOIS3Y** [NixOS/nixpkgs#322582]
### Describe the bug

```console
nix-shell -p bash-language-server 
```
Does not install the package, the same thing happens if you add it to the configuration

<details>
    <summary>Error</summary>
error:
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/rljkm6h18fjvavm6l17jiil8glphc44f-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/rljkm6h18fjvavm6l17jiil8glphc44f-source/pkgs/stdenv/generic/make-derivation.nix:378:7:

          377|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          378|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          379|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       error: undefined variable 'bash-language-server'

       at «string»:1:107:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (bash-language-server) ]; } ""
             |                                                                                                           ^                                                                        
</details>

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"                                              
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.11 (Vicuña), 24.11.20240609.c7b821b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/rljkm6h18fjvavm6l17jiil8glphc44f-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=+bash-language-server

**Comment by MOIS3Y** [comment]
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=+bash-language-server

Needs to be removed :)

**Comment by eclairevoyant** [comment]
You have to pick the channel you're actually using, whether 24.05 or unstable, and use the attribute mentioned in that channel.
