### ISSUE TITLE
Build failure: wrangler

### ISSUE THREAD

**Issue by dezren39** [NixOS/nixpkgs#322571]
### Steps To Reproduce

1. run nixos flake build, with nixpkgs/master, which worked yesterday and doesn't today
2. build fails on workerd fixed derivation that is pulled from npm

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/ycbcryc6xbvrlqg9ndfn30gvrrm9jqzj-workerd-linux-64-1.20240610.1.tgz.drv':
         specified: sha512-E8mj+HPBryKwaJAiNsYzXtVjKCL0KvUBZbtxJxlWM4mLSQhT+uwGT3nydb/hFY59rZnQgZslw0oqEWht5TEYiQ==
            got:    sha512-2zDcadR7+Gs9SjcMXmwsMji2Xs+yASGNA2cEHDuFc4NMUup+eL1mkzxc/QzvFjyBck98e92rBjMZt2dVscpGKg==
```

### Additional context

may relate to #319134 based on commit histor

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 user  nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.35, NixOS, 24.11 (Vicuna), 24.11.20240625.e6e4cd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - nixpkgs: `/nix/store/2365ibi8vdmml11l7sdiclpi2hanxn5n-source`
```

I do have a bunch of experimental flags enabled, they could impact something..
```
"auto-allocate-uids"
"ca-derivations"
"cgroups"
"dynamic-derivations"
"fetch-closure"
"flakes"
"git-hashing"
"nix-command"
"parse-toml-timestamps"
"read-only-local-store"
"recursive-nix"
"verified-fetches"
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dezren39** [comment]
@SuperSandro2000 @lelgenio @a-kenji can you please review

**Comment by SuperSandro2000** [comment]
#322573
