### ISSUE TITLE
Build failure: kanidm on 24.05

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#322598]
### Steps To Reproduce

1. build kanidm from the nixos-24.05 branch

### Build log

```
       [...]
       > thread 'main' panicked at cargo-auditable/src/rustc_wrapper.rs:101:39:
       > called `Option::unwrap()` on a `None` value
       > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > error: could not compile `kanidmd_lib` (lib)
       For full logs, run 'nix log /nix/store/ymg5qcqxi6q7llhq6hhl5sfa7y3f6xp5-kanidm-1.2.3.drv'.

```

### Additional context

N/A

### Notify maintainers

@adamcstephens  @erictapen @Flakebi 

### Metadata

nixpkgs https://github.com/NixOS/nixpkgs/commit/8572fec8e05e690cfb8941717f048d037f2b684e

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
How much memory do you have?

**Comment by adamcstephens** [comment]
Ok, I finally got in and yes the last x86 job timed out. I've restarted it.

https://hydra.nixos.org/build/264008590

**Comment by adamcstephens** [comment]
Hydra succeeded this time, so this should now be cached again. I'm going to close because I assume the build failure is lack of sufficient memory.
