### ISSUE TITLE
Nextcloud upgrade from 28 to 29 fails because of the Files app

### ISSUE THREAD

**Issue by gianmarcogg03** [NixOS/nixpkgs#322621]
### Describe the bug
When I try to upgrade from Nextcloud 28 to 29, it fails and the nextcloud-setup service gives this error: `UnexpectedValueException: The files of the app "files" were not correctly replaced before running the update`.

### Steps To Reproduce
1. Set the package version from 28 to 29
2. Rebuild the system

### Expected behavior
Nextcloud should upgrade fine.

### Notify maintainers
@schneefux @bachp @globin @Ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.675.805a384895c6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
Just a bunch of notes:

* The error happens if the compatibility check of Nextcloud against the files app fails (i.e. if files is only compatible with older/newer nextclouds than available).
* The NC version detected here comes from `version.php` in Nextcloud. I.e. when a new Nextcloud is running nextcloud-setup, the version should be correct: https://github.com/nextcloud/server/blob/b77c151f5bc041c089e5f07e3df5f9c1e3c1f1d7/lib/private/legacy/OC_Util.php#L274
* This is probably happening in the `occ upgrade`-command. This `cd`s into the `webroot` storepath, i.e. the newly deployed Nextcloud.

So, for now, I'd rule out a weird timing issue (not 100% sure though).

@gianmarcogg03 there are multiple directories with Nextcloud apps installed. You can find those listed in your `/var/lib/nextcloud/config/config.php` below `apps_paths`. Can you check please if there are multiple directories containing a directory `files`? If so, can you check the `appinfo/info.xml` of each and share the tags inside `<dependencies>`?

**Comment by gianmarcogg03** [comment]
The app paths are `/nix/store/yw3sh97ajpnnw1nxmdc8hzba8xw5afhr-nextcloud-28.0.5-with-apps/apps` and `/nix/store/yw3sh97ajpnnw1nxmdc8hzba8xw5afhr-nextcloud-28.0.5-with-apps/store-apps`. The files app directory is present only in the first app path, although both have other app directories for extensions to the files app (such as files_external, files_fulltextsearch, files_rightclick, etc.) if that has any impact on this problem.

**Comment by Ma27** [comment]
They still are even though you switched to Nextcloud 29? I think we found the problem then.

Can you please check if `systemd-tmpfiles` has any mentions of unsafe path transitions?

**Comment by gianmarcogg03** [comment]
There's unsafe path transitions on `/srv/nextcloud` and `/srv/nextcloud/config` (I have my state directory in this custom `/srv` directory instead of the normal `/var/lib`, is this a problem?).

**Comment by Ma27** [comment]
@gianmarcogg03 which user owns `/srv/nextcloud`?

systemd-tmpfiles will refuse to create directories owned by another user unless the parent directories are owned by the same user or root.

**Comment by gianmarcogg03** [comment]
My user owns `/srv` and the `nextcloud` user owns `/srv/nextcloud`.

**Comment by Ma27** [comment]
This is precisely the problem, `/srv` must be owned by either root or nextcloud. See https://github.com/systemd/systemd/issues/19618#issuecomment-843273818 for a more detailed explanation.

**Comment by kfiz** [comment]
@Ma27 Having the same issue trying to upgrade from 28 to 29. No unsafe path transitions though. In my attempts to fix this I backed up my nextcloud folder and tried a clean installation. To my surprise this also didn't work:
```
Jan 09 03:13:34 nixos nextcloud-setup-start[775403]: Cleaning up apps; these are now bundled in the webroot store-path!
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: Nextcloud is not installed - only a limited number of commands are available
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: Cannot write into "apps" directory.
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: This can usually be fixed by giving the web server write access to the apps directory or disabling the App Store in the config file.
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: An unhandled exception has been thrown:
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: Exception: Environment not properly prepared. in /nix/store/qwacbgnfpj9zv8vfvygcyj8w8q1fnlcw-nextcloud-29.0.10/lib/private/Console/Application.php:>
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: Stack trace:
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: #0 /nix/store/qwacbgnfpj9zv8vfvygcyj8w8q1fnlcw-nextcloud-29.0.10/console.php(101): OC\Console\Application->loadCommands(Object(Symfony\Component\Co>
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: #1 /nix/store/qwacbgnfpj9zv8vfvygcyj8w8q1fnlcw-nextcloud-29.0.10/occ(11): require_once('/nix/store/qwac...')
Jan 09 03:13:34 nixos nextcloud-setup-start[775406]: #2 {main}
Jan 09 03:13:34 nixos systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
Jan 09 03:13:34 nixos systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
Jan 09 03:13:34 nixos systemd[1]: Failed to start nextcloud-setup.service.
```
I'm a bit lost now. Any hints?

**Comment by Ma27** [comment]
Hmm, with the logs you showed me I can't really say what went wrong.

Is your Nextcloud installed at the default location or anywhere else?
Can you show me which permissions the files & folders in your data directory have?
Also, sharing your NixOS config for Nextcloud might help.

**Comment by kfiz** [comment]
> Hmm, with the logs you showed me I can't really say what went wrong.
> 
> 
> 
> Is your Nextcloud installed at the default location or anywhere else?
> 
> Can you show me which permissions the files & folders in your data directory have?
> 
> Also, sharing your NixOS config for Nextcloud might help.
> 
> 

I disabled apps and then it worked. Not sure how state is managed related to apps, but we seem to be missing something in the upgrade of these.
