### ISSUE TITLE
rename mbpfan to macfan

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32266]
It does not only work on MacBook Pros, but also on Macbooks and probably other Mac hardware.

So i suggest to rename it to macfan, similar to thinkfan.

cc @cstrahan

**Comment by cstrahan** [comment]
My only concern is that it might be less grep-able, if people already know about the upstream package’s name. Then again, if we consider the NixOS module to be it’s own abstract thing, and treat the underlying package as just an implementation detail, I’d understand.

I’ll defer to the other Mac users. Off the top of my head: @copumpkin, @LnL7, what are our thoughts?

**Comment by davidak** [comment]
Ah, right. Then i suggest it upstream.

**Comment by davidak** [comment]
So, my suggestion to rename the package was closed, what i fully understand.

We could still rename our service. To find it in a search for "mbpfan", the package name should be included in the description for `.enable`. Same for "applesmc module".

**Comment by yegortimoshenko** [comment]
> We could still rename our service. To find it in a search for "mbpfan", the package name should be included in the description for .enable. Same for "applesmc module".

No, `services` namespace follows convention that attribute name equals to the actual demon name. It's not for abstract configuration.

> So i suggest to rename it to macfan, similar to thinkfan.

`thinkfan` is misleading, too: it is a generic fan control program that was originally written on ThinkPad hardware.

It is possible to abstract away all fan control into `hardware.fan.*` module. Both `mbpfan` and `thinkfan` have very little hardware-specific code; actually, `thinkfan` [has none](https://github.com/vmatare/thinkfan):

```
Thinkfan is a simple, lightweight fan control program. Originally designed
specifically for IBM/Lenovo Thinkpads, it now supports any kind of system via
the sysfs hwmon interface (/sys/class/hwmon). It is designed to eat as little
CPU power as possible.
```

While `mbpfan` does hardcode SMC handling: https://github.com/dgraziotin/mbpfan/blob/master/src/mbpfan.c#L258

However, I don't see the point. I have several MacBooks running NixOS and I don't notice any difference between native Linux fan control and macOS fan control. Besides that, fan control (as any hardware control) should be managed at kernel level and not in userspace.

**Comment by davidak** [comment]
@yegortimoshenko i had problems with my macbook that it get's very hot and the fan doesn't go faster. so i looked for a solution.

So we can leave the name as is but improve the description to make the purpose a little bit more clear. I will propose a PR.
