### ISSUE TITLE
python: How to make result of overridePythonAttrs overridable?

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#32263]
## Issue description

The currently recommended way of overriding Python packages seem to be using ``overridePythonAttrs`` function of ``buildPythonPackage``. Unfortunately, ``overridePythonAttrs`` does not seem to be overridable by itself. If I manage to chain multiple ``overridePythonAttrs`` (e.g. with fixed-points overlays) I get ``attribute 'overridePythonAttrs' missing``.

Yet, ``overrideDerivation`` was overridable.

Am I missing something? Would it be hard to make ``overridePythonAttrs`` overridable?

### Steps to reproduce

Works

    with import <nixpkgs> {};                                                       
                                                                                
    (pythonPackages.pillow.overrideDerivation(old: {                                
      name = "pillow-override";                                                     
    })).overrideDerivation(old: {                                                   
    })

Does not

    with import <nixpkgs> {};                                                       
                                                                                
    (pythonPackages.pillow.overridePythonAttrs(old: {                                
      name = "pillow-override";                                                     
    })).overridePythonAttrs(old: {                                                   
    })

**Comment by datakurre** [comment]
I tried to look into how this is done for ``overrideAttrs``, but this seem be still beyond my Nix skills.

**Comment by FRidh** [comment]
Could you test https://github.com/NixOS/nixpkgs/pull/32318.
