### ISSUE TITLE
Update request: teams-for-linux 1.4.27 → 1.7.4

### ISSUE THREAD

**Issue by xdinterface** [NixOS/nixpkgs#322636]
- Package name: teams-for-linux
- Latest released version: 1.7.4

- Current version on the unstable channel: 1.4.27
- Current version on the stable/release channel: 1.4.27

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@muscaln 
@lilyinstarlight
@QJoly 
@chvp 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ShamrockLee** [comment]
@ Julien76 How do you package teams-for-linux 1.7.4?

The upstream moves back to NPM `package-lock.json` in IsmaelMartinez/teams-for-linux#1284 and in release 1.6.0, meaning we must rewrite this package's Nix expression.

**Comment by Julien76** [comment]
@ShamrockLee,
I tried building using npm or converting the npm lock file to a yarn.lock but every time the build was failing due to some electron dependency issues.

So in the end, I built it against the appImage as follow:

```nix
{
  pkgs,
  lib,
  ...
}: let
  teams-for-linux-updated = pkgs.appimageTools.wrapType2 rec {
    name = "teams-for-linux";
    src = pkgs.fetchurl {
      url = "https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.7.4/teams-for-linux-1.7.4.AppImage";
      hash = "sha256-A4RgpUeC8W5aHEZ/CrjZIVYvkynpfs015Kxo2XlNtlE=";
    };

    desktopItems = [
      (pkgs.makeDesktopItem {
        inherit name;
        exec = name;
        icon = name;
        desktopName = "Microsoft Teams for Linux";
        comment = meta.description;
        categories = ["Network" "InstantMessaging" "Chat"];
      })
    ];

    meta = {
      description = "Unofficial Microsoft Teams client for Linux";
      mainProgram = name;
      homepage = "https://github.com/IsmaelMartinez/teams-for-linux";
      license = lib.licenses.gpl3Only;
      maintainers = with lib.maintainers; [muscaln lilyinstarlight qjoly chvp];
      platforms = lib.platforms.unix;
    };
  };
in {
  home.packages = with pkgs; [
    teams-for-linux-updated
  ];

  xdg.desktopEntries."teams-for-linux" = {
    name = "Microsoft Teams for Linux";
    comment = "Team communication and collaboration software";
    icon = "teams-for-linux";
    type = "Application";
    exec = ''env XDG_CURRENT_DESKTOP="" ${pkgs.teams-for-linux}/bin/teams-for-linux %U'';
    categories = ["Network" "InstantMessaging" "Chat"];
    terminal = true;
  };

  # Add the configuration file for teams-for-linux
  xdg.configFile."teams-for-linux/config.json".source = ./config.json;
}
```

please not that I'm quite new to Nix and I might have done something wrong while trying to build with npm or yarn. Also I used this expression with home-manager so I'm not sure how it'll work without it.

**Comment by michelealbrigo** [comment]
Bumping this up, because since today, unstable is not building anymore with teams-on-linux package, because it carries version 29.4.6 of electron, now marked as EOL.

```
Known issues:
        - Electron version 29.4.6 is EOL
```

Workaround available by permitting it as insecure package.

**Comment by VincentBerthier** [comment]
I have the same problem unfortunately.

**Comment by DamienCassou** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/337868.
