### ISSUE TITLE
Package request: libavutil

### ISSUE THREAD

**Issue by myclevorname** [NixOS/nixpkgs#322768]
**Project description**

The libavutil library is a utility library to aid portable multimedia programming. It contains safe portable string functions, random number generators, data structures, additional mathematics functions, cryptography and multimedia related functionality (like enumerations for pixel and sample formats). It is not a library for code needed by both libavcodec and libavformat. 

**Metadata**

* homepage URL: https://ffmpeg.org/libavutil.html
* source URL: https://git.ffmpeg.org/ffmpeg
* license: MIT
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
`libavutil` seems to already be in `ffmpeg.dev` if I'm not mistaken
