### ISSUE TITLE
curlFull,curlHTTP3: unable to make HTTP3 requests, "installed libcurl version doesn't support this"

### ISSUE THREAD

**Issue by amyipdev** [NixOS/nixpkgs#322711]
### Describe the bug
HTTP3 support in curl appears to have regressed, and it is not possible to make HTTP3 requests on a standard curlFull or curlHTTP3 installation. It fails with:

```console
curl -vk --http3 https://127.0.0.1:4433
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
```

### Steps To Reproduce
1. Install `curlFull` or `curlHTTP3`
2. Run `curl --http3 https://some.http3.site/` (in my case, it was `curl -vk --http3 https://localhost:4433/`)
3. Observe failure

### Expected behavior
An HTTP3 request should be dispatched to the intended target.

### Screenshots
*All content that would be in screenshots was posted directly.*

### Additional context
I tried installing nghttp3 and ngtcp2 manually alongside curlFull and curlHTTP3, to no avail.

### Notify maintainers

@lovek323 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11pre641786.d603719ec6e2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Guanran928** [comment]
Seems to be working fine for me, on d603719ec6e294f034936c0d0dc06f689d91b6c3:

```
flake on  staging [$!?⇕]
❯ nix build github:NixOS/nixpkgs/d603719ec6e294f034936c0d0dc06f689d91b6c3#curlHTTP3

flake on  staging [$!?⇕] took 27s
❯ result-bin/bin/curl --http3-only https://ny4.dev/
<!DOCTYPE html><html lang="en"><head>...
```

**Comment by amyipdev** [comment]
If I use `nix-shell` it works today (didn't work before) but having it be installed through my nixos config (which is using home-manager) doesn't work... odd (and no, I don't have another _explicit_ curl installation)
