### ISSUE TITLE
Update request: pcloud 1.14.5 → 1.14.6

### ISSUE THREAD

**Issue by VanDoge** [NixOS/nixpkgs#322763]
- Package name: pcloud
- Latest released version: 1.14.6

- Current version on the unstable channel: 1.14.5
- Current version on the stable/release channel: 1.14.5

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Patryk27 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luftmensch-luftmensch** [comment]
It seems that I was already updated to the latest version (https://github.com/NixOS/nixpkgs/commit/27e96ecbef451500f3b5710c817c2906ddd126d2)

**Comment by Patryk27** [comment]
Yeah, I've already updated pcloud a couple of days ago, so it's both in `master` and `nixos-unstable` now - if you're using Flakes, try running `nix flake update` etc. 🙂 

I'm closing this issue, but feel free to re-open it if you find any problems with the upgrade.
