### ISSUE TITLE
ibus-mozc not starting (possibly libc-related)

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#32273]
## Issue description

As of a few days ago on nixos-unstable, switching to Mozc in IBus does not change the input method to IBus. When running `ibus-daemon -rxv`, the error message is the following.

```
/nix/store/0115hc0qrbam4cn1dy2578sxa5k70lij-ibus-mozc-2.20.2673.102/lib/ibus-mozc/ibus-engine-mozc: relocation error: /nix/store/s7dw1yngwiskqa2ac1bkc6m9g7740agg-glibc-2.25/lib/libresolv.so.2: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

(ibus-ui-gtk3:2647): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: Timeout was reached

(ibus-ui-gtk3:2647): IBUS-WARNING **: panel.vala:951: Switch engine to mozc-jp failed.
```

### Steps to reproduce

1. Start IBus in a non-Mozc input method.
2. Switch to Mozc using keyboard or panel menu.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03.git.4e7deb7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `""`
 - nixpkgs: `/home/james/nixpkgs`

**Comment by vcunat** [comment]
Most likely mismatching versions of some packages.  Impure plugins like ibus are sensitive to some kind of changes.  I would try force-updating all related packages (and NixOS) to the same channel revision.

**Comment by laMudri** [comment]
Sorry, how can I force-update things? I have all of my global packages installed via a single `buildEnv` called `everything`, which I usually update by running `nix-env -iA g.everything`.

**Comment by vcunat** [comment]
That should do it.  Is that from the same channel as your NixOS?

**Comment by laMudri** [comment]
I'm fairly sure it is, and I've rebooted since updating. Just some things to check that it is:
```
$ echo $NIX_PATH
/home/james:nixos-config=/etc/nixos/configuration.nix:nixpkgs=/home/james/nixpkgs
$ sudo nixos-rebuild build -k 
[sudo] password for james: 
building Nix...
building the system configuration...
$ nix-env -iA g.everything
replacing old ‘everything’
installing ‘everything’
downloading ‘https://static.rust-lang.org/dist/channel-rust-stable.toml’... [0/0 KiB, 0.0 KiB/s]
building path(s) ‘/nix/store/m4i6knvzxhjfnwk45j0g865j6w0l92rw-user-environment’
created 8 symlinks in user environment
```
Plus OP's technical details.

**Comment by yegortimoshenko** [comment]
Can't reproduce:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.5, NixOS, 18.03.git.4d25209 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"overlay, nixos-18.03pre121925.3eccd0b11d1"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by laMudri** [comment]
Config error. My `ibus` package was from an old verson of nixpkgs.
