### ISSUE TITLE
Build failure: go-1.22.4 with [Musl]

### ISSUE THREAD

**Issue by Thiago-Assis-T** [NixOS/nixpkgs#322760]
### Steps To Reproduce

1. nix build nixpkgs#pkgsMusl.go

### Build log
This is the last bit, as it looks like a version problem didn't add more. If need be, I'll add more.
```
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 30
file size                   (blocks, -f) unlimited
pending signals                     (-i) 125764
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 125764
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
/build/go/src /build/go
Building Go cmd/dist using /nix/store/zgn3hsnp6zb8yl425b6dpw60amqp67b2-gccgo-wrapper-12.3.0. (go1.18 gccgo (GCC) 12.3.0 linux/amd64)
found packages main (build.go) and building_Go_requires_Go_1_20_6_or_later (notgo120.go) in /build/go/src/cmd/dist
```

### Additional context

I'm using musl:
```
  nixpkgs.hostPlatform = {
    system = "x86_64-linux";
    config = "x86_64-unknown-linux-musl";
  };
```

apparently the go bootstrap is different on musl because go.dev does not provide binaries for musl systems, so we bootstrap via gccgo, which gets outdated from time to time (and apparently that just happened)
### Notify maintainers
@kalbasit 
@Mic92 
@zowoq 
@qbit 
@mfrw 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
.nixos on  main [!⇡] 
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240624.fc07dc3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/r5clili0iqprbn4dnngkywsgxm51a5cw-source`
```
The channel is showing 23.11 because the iso i used was 23.11, however i'm using a flake with 24.05 as input.
this happend while i was trying to go to musl...

---

Afterword:
@yu-re-ka is helping me out here, but i'm clearly not that smart for this bug report, so any problems and mistakes here can be pointed out, and i'll do my best to help out

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Thiago-Assis-T** [comment]
> > Steps To Reproduce
> > Steps to reproduce the behavior:
> > ```
> > build go-1.22.4
> > ```
> 
> this is not a valid reproducer

sorry, now i think it's more accurate

**Comment by Thiago-Assis-T** [comment]
> This is still a rather low quality bug report.
> 
>     * what nixpkgs version are you building from? your metadata shows both a 24.05 and 23.11 version being present on your system
> 
>     * what _attribute_ is exactly failing to build? this can be slightly difficult to figure out but helps immensely. if you can not figure it out, provide your full system config which pulls in the broken dependency instead.
> 
> 
> It happens that I can tell that from the context that this would happen when building the attribute `pkgsMusl.go_1_22` from nixpkgs commit [72f92f5](https://github.com/NixOS/nixpkgs/commit/72f92f567f50917f0f5c12c1a94dbaeb5a012074), but ideally you would provide this information to make the life of the person who is looking into your issue in their free time easier.
> 
> You should also add some indication of the musl (e.g. `pkgsMusl.` or `[musl]` to the issue title, because otherwise the go maintainers will get a heart attack when they see this in their notifications ;)

How can I check the failing attribute? 

and the full system config, just like the link to my config repo? didn't understant that part

**Comment by Thiago-Assis-T** [comment]
Ha! Did it!

**Comment by zowoq** [comment]
@yu-re-ka I think https://github.com/NixOS/nixpkgs/commit/d391f7ee13e1b6a1ff618b196c53f57c8ae9d6b9 works, can you please confirm?

**Comment by zowoq** [comment]
Yes, they are static since 1.21. https://github.com/NixOS/nixpkgs/pull/322825

**Comment by Thiago-Assis-T** [comment]
Guys, I'm not familiar with how this works, i saw that the pr was merged to staging, im assuming it goes

staging -> unstable-small -> unstable -> 24.05-small -> 24.05

is that correct? and if so, how long from one branch to another?

**Comment by Thiago-Assis-T** [comment]
ooooh i see
