### ISSUE TITLE
`canberra-boot` and systemd services are missing from `libcanberra`

### ISSUE THREAD

**Issue by muni-corn** [NixOS/nixpkgs#322774]
### Describe the bug

`canberra-boot`, which is offered by most Linux distributions where `libcanberra` is installed, is not present in NixOS. Its systemd services aren't available either. I'd like to be able to have an easy way to play sounds on boot and shutdown and this seems like the usual way to do it on other Linux distributions :grin: 

### Steps To Reproduce
1. Install `libcanberra` (whether via `nix-env`, `environment.systemPackages` option, etc)

### Expected behavior
`canberra-boot` should be available and executable.
systemd services such as `canberra-system-bootup.service`, `canberra-system-shutdown.service`, and `canberra-system-shutdown-reboot.service` should be available to enable.  

### Notify maintainers

@RossComputerGuy 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240622.a71e967`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - nixpkgs: `/nix/store/yqy82fn77fy3rv7lpwa9m11w3a2nnqg5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
Probably a NixOS module would be good so it'll be easy to customize.

**Comment by eclairevoyant** [comment]
That doesn't really have a bearing on this PR, as this would still need to be built anyway.

**Comment by muni-corn** [comment]
woot! thank you for your work on this! i'm so excited to get this working on my PC

**Comment by eclairevoyant** [comment]
FYI it'll take a couple of weeks to end up in unstable, and you'll then have to add it to `systemd.packages` as well, but it should work at that point.
