### ISSUE TITLE
atom-1.22.0: `apm publish` doesn't work

### ISSUE THREAD

**Issue by lierdakil** [NixOS/nixpkgs#32297]
## Issue description

Atom's `apm publish` stores credentials using [`keytar`](https://www.npmjs.com/package/keytar) package, which depends on `libsecret`. `libsecret` is apparently out of scope for `apm` in Nix though.

### Steps to reproduce

Install Atom (`nix-env -i atom`), then try to publish any package. Depending on version, different errors will be reported, but ultimately it will fail.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.11-gentoo, Gentoo, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `""`
 - channels(livid): `"nixpkgs-18.03pre121853.e53ebf3a31e"`
 - nixpkgs: `/home/livid/.nix-defexpr/channels/nixpkgs`

**Comment by Mic92** [comment]
Maybe adding `libsecret` here can help: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/env.nix#L7

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/75417d878164de6d936e38b052834cd5ba57b2c6
