### ISSUE TITLE
Update request: prusa-slicer 2.7.4 → 2.8.0

### ISSUE THREAD

**Issue by k3d3** [NixOS/nixpkgs#322910]
- Package name: prusa-slicer
- Latest released version: 2.8.0

- Current version on the unstable channel: 2.7.4
- Current version on the stable/release channel: 2.7.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@moredread @tweber @tmarkus

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by VuiMuich** [comment]
There is a request in the [upstream issue #12980](https://github.com/prusa3d/PrusaSlicer/issues/12980) requesting the return of the tarball.

**Comment by k3d3** [comment]
OrcaSlicer appears to also not distribute tarballs - though I'm not sure how far the two have deviated from each other, would [this PR](https://github.com/NixOS/nixpkgs/pull/324086) help at all?

**Comment by WizardUli** [comment]
> 👀 A big issue they did was they've stopped releasing tarballs so now the only way that it can be packaged is via the AppImage, and there's some complications in the mix now they they also include WebKit in the software.

WTF? What does *pre-built binary tarballs* have to do with prusa-slicer in nixpkgs?
prusa-slicer in nixpkgs is being build from source code fetch directly via `fetchFromGitHub` **as it should**!
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/prusa-slicer/default.nix

**Comment by Rose-David** [comment]
2.8.0 has been merged now, this issue can be closed.
