### ISSUE TITLE
haskellPackages.arbtt: man pages missing

### ISSUE THREAD

**Issue by martinvonwittich** [NixOS/nixpkgs#323030]
### Describe the bug

I've added `haskellPackages.arbtt` to my `environment.systemPackages`. `arbtt` itself works fine:

```
martin@desktop ~ % arbtt-dump | head -n1
2024-06-26 11:56:36 (0ms inactive):
```

But the man pages are all missing:

```
martin@desktop ~ % man arbtt-dump
No manual entry for arbtt-dump
martin@desktop ~ % man -k arbtt
arbtt: nothing appropriate.
```

As far as I can tell, upstream provides them in DocBook format: https://github.com/nomeata/arbtt/blob/master/doc/arbtt.xml and also provides a Makefile to build them: https://github.com/nomeata/arbtt/blob/52a00557fff1606152f78ebf7292780430ba884d/doc/Makefile
so this should hopefully be easily fixable.

### Steps To Reproduce

1. Install `haskellPackages.arbtt`.
1. Attempt to read a man page for any of the `arbtt*` binaries.

### Expected behavior
Man pages should be provided.

### Notify maintainers

@rvl

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
martin@desktop ~ % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.05 (Uakari), 24.05.20240531.63dacb4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/wzx1ba5hqqfa23vfrvqmfmkpj25p37mr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rvl** [comment]
Thanks for reporting @martinvonwittich. I have opened PR #323117 to fix it.
