### ISSUE TITLE
Update request: `lua` 5.2 → 5.4

### ISSUE THREAD

**Issue by C0Florent** [NixOS/nixpkgs#323016]
- Package name: `lua`
- Latest released version: 5.4

- Current version on the unstable channel: 5.2
- Current version on the stable/release channel: 5.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@teto 

-----

Note for maintainers: Please tag this issue in your PR.

---

I discovered the package was out of date when trying to run an mGBA script (mGBA has support for lua scripting since 0.10, we are now at 0.13), and it wouldn't work. After some investigation, I found out that the script was using bitwise operators which are only supported since lua 5.3 (released in 2015!), while the current nix-packaged version in 5.2, released in 2011

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
`pkgs.lua5_4` exists

**Comment by C0Florent** [comment]
That's my bad then I guess. I'm just checking if it works for my use case and then I guess I'll close as not planned if it's fine

**Comment by C0Florent** [comment]
Thanks for helping, I managed to get the `mgba` package to use `lua5_4` instead of the default `lua` (which the 5.2 version), by writing (in the list of packages for my user)
```nix
(mgba.override { lua = pkgs.lua5_4_compat; })
```
instead of the previous `mgba` (this rebuilt the `mgba` package locally by the way)

It was quite a challenge to do on my first day using NixOS, but I got it to work eventually. Thanks again!

**Comment by Frontear** [comment]
Glad to hear it all worked out, cheers!
