### ISSUE TITLE
Booting into profile with amdgpu-pro shows only black screen

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#32306]
## Issue description

Thanks to e001bd2c2f698037c6968608523c609cddac813b I can finally build amdgpu-pro, but it only displays a black screen. Viewing journalctl's results afterwards doesn't show anything suspicious, it tries repeatedly to start xorg, but fails and gives up. Similar thing happened on ubuntu using amdgpu-pro 17.40 - although I don't remember what was actually the problem -, which could be overcome by using one of these answers: https://askubuntu.com/questions/880523/cant-login-after-installing-amdgpu-pro-16-60  , namely `amdgpu-pro-install --compute`. I'm not sure what does the `compute` option does differently, but maybe it can help. Here is my journalctl 's results from the relevant boot (removed many unrelated line): https://gist.github.com/Mounium/2db8cf66df7ce72848e722b5d99238c4

### Steps to reproduce

Setting services.xserver.videoDrivers to [ "amdgpu-pro" ] using the previously mentioned commit. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03pre-git (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121843.4e7deb7100b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by tomodachi94** [comment]
`amdgpu-pro` was removed by https://github.com/NixOS/nixpkgs/pull/320228. It was unmaintained.
