### ISSUE TITLE
Package request: BoilR

### ISSUE THREAD

**Issue by Metigoth** [NixOS/nixpkgs#323075]
BoilR automatically adds (almost) all your games to your Steam library (including image art).

It uses the Steam 3rd party shortcuts feature and does not require you to set up anything. The goal is that you do not have to leave your Steam library to launch games from other launchers/stores, so that you can find all the games that you have available. Optionally, you can set up BoilR to automatically download artwork from [SteamGridDB](https://www.steamgriddb.com/).

**Metadata**

* homepage URL: https://github.com/PhilipK/BoilR
* source URL: https://github.com/PhilipK/BoilR/releases
* license: apache
* platforms: linux, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Added in #247991
