### ISSUE TITLE
Update request: betterbird 115.9 → 115.12

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#323169]
- Package name: betterbird
- Latest released version: 115.12

- Current version on the unstable channel: 115.9
- Current version on the stable/release channel: 115.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SuperSandro2000

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Could you create a PR, please?

**Comment by Thatoo** [comment]
I can try but I don't understand what file is the hash of line 39 from?

**Comment by Aleksanaa** [comment]
> I can try but I don't understand what file is the hash of line 39 from?

You just delete it (let it be `hash = "";`) and run the build, it will fail with the right hash.

Before submitting PRs you may also read https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md.

**Comment by Thatoo** [comment]
Thank you.
@SuperSandro2000 I opened it here : https://github.com/NixOS/nixpkgs/pull/323760

**Comment by SuperSandro2000** [comment]
#339019
