### ISSUE TITLE
Update request: xivlauncher 1.0.8→ 1.1.0

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#323149]
- Package name: xivlauncher
- Latest released version: [1.1.0](https://github.com/goatcorp/XIVLauncher.Core/releases/tag/1.1.0)

- Current version on the unstable channel: 1.0.8
- Current version on the stable/release channel: 1.0.8

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@sersorrel @witchof0x20 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ciferkey** [comment]
1.0.9 also released yesterday but I don't see a PR or issue for it.

Quite likely there will be sever more releases as they work on fixes for the new expansion that dropped today.

**Comment by sersorrel** [comment]
1.0.9 (which is recent enough to successfully download and play Dawntrail) was merged to master yesterday, and 24.05 today; we're at the mercy of Hydra for that to show up in the release channels. Hopefully that will be fairly soon.

I'll get around to 1.1.0 at some point – it fixes repair, but that's it, and I'm currently enjoying the new expansion.

**Comment by ciferkey** [comment]
Ah! I didn't see 1.0.9 got in when I search! Enjoy Dawntrail!
