### ISSUE TITLE
vimPlugins.specs-nvim does not work in Neovim 0.10

### ISSUE THREAD

**Issue by axelkar** [NixOS/nixpkgs#323168]
### Describe the bug
Specs-nvim does not work in Neovim 0.10 and the author has not updated the upstream version.
The derivation should point to the updated fork instead: https://github.com/cxwx/specs.nvim/tree/main

### Steps To Reproduce
1. Use specs-nvim with Neovim 0.10
2. Trigger specs-nvim
3. It errors
4. https://github.com/edluffy/specs.nvim/issues/31

### Additional context

Should I have used the out-of-date packaging report issue template instead?

### Notify maintainers

@teto

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by axelkar** [comment]
What does no pb mean? I'll make a PR

**Comment by GaetanLepage** [comment]
> What does no pb mean? I'll make a PR

I guess that it means "go for it, let's switch to the fork".
