### ISSUE TITLE
borgbackup: extraCreateArgs (and other args) are broken

### ISSUE THREAD

**Issue by necauqua** [NixOS/nixpkgs#323262]
### Describe the bug

`extraCreateArgs` escapes the args, breaking them because they are not expanded by bash, being passed from systemd through an env var. Easier to understand with the repro:

### Steps To Reproduce
1. Set up a borgbackup job `test` with `extraCreateArgs = [ "--exclude-caches" ]`
2. `systemctl cat borgbackup-job-test` will have a line `Environment="extraCreateArgs='--exclude-caches'"` 
3. `systemctl start borgbackup-job-test` will then fail with `borg create: error: argument ARCHIVE: "'--exclude-caches'": No archive specified`
4. Manually setting extraCreateArgs correctly in the `preHook` works around the issue.

### Expected behavior
It should work as expected, I assume the same issue applies to other extraArgs parameters.

### Notify maintainers

@dotlambda
<!--

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 24.11 (Vicuna), 24.11.20240624.2893f56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - channels(necauqua): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/vsbi6gfwf2bdamw0d0d9xndb1rrxfnbk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pcarrin2** [comment]
I'm having the same issue with setting extraArgs. A crappy workaround could be to process the arguments in the bash script, removing the literal single quotes around them. But it seems like the root of the problem is upstream with how the systemd service is created.

**Comment by Scrumplex** [comment]
See #332319
