### ISSUE TITLE
Update request: git-credential-manager 2.4.1 → 2.5.0

### ISSUE THREAD

**Issue by aucub** [NixOS/nixpkgs#323242]
- Package name: git-credential-manager
- Latest released version: 2.5.0

- Current version on the unstable channel: 2.4.1
- Current version on the stable/release channel: 2.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@999eagle 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kashw2** [comment]
In my limited knowledge of the dotnet ecosystem in Nixpkgs, this may be currently blocked by https://github.com/git-ecosystem/git-credential-manager/issues/1636 and https://github.com/git-ecosystem/git-credential-manager/issues/1636. I'll continue to look into this though

**Comment by 999eagle** [comment]
opened a pr for the update: #324142
