### ISSUE TITLE
Build failure: awslambdaric

### ISSUE THREAD

**Issue by RobFisherAtSky** [NixOS/nixpkgs#323226]
### Steps To Reproduce

1. build python311Packages.awslambdaric

e.g.:
```nix
packages.dockerImage = pkgs.dockerTools.buildLayeredImage {
  name = "my-lambda-image";
  tag = "latest";
  contents = with pkgs; [
    [
      (python.withPackages (p: with p; [
        awslambdaric
```

### Build log

```
...
Successfully built awslambdaric-2.0.10-cp311-cp311-linux_x86_64.whl
Finished creating a wheel...
Finished executing pypaBuildPhase
buildPhase completed in 2 minutes 33 seconds
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for awslambdaric-2.0.10-cp311-cp311-linux_x86_64.whl
  - simplejson~=3.17.5 not satisfied by version 3.19.2
```

### Additional context

I'm using a flake to build a docker image with awslambdaric to deploy in a AWS Lambda. I'm on NixOS unstable. I attempted to override doChecks to false but that did not help.

There is a [previous commit](https://github.com/NixOS/nixpkgs/commit/48bf15f8592557172f4003ab95829314c508340d) where the simplejson version changed.

More recently, upstream has relaxed the version requirements: https://github.com/aws/aws-lambda-python-runtime-interface-client/commit/3a7d01e2d6e0c0f11e8bac4ef631ed1eceef7932

### Notify maintainers

@austinbutler
@mweinelt

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
󱆃 ❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/kjhgwsnn7wkacncxhrcgc4mx0v82kbdf-nix-info
copying path '/nix/store/kjhgwsnn7wkacncxhrcgc4mx0v82kbdf-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.0-41-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/rhg90jpryc286xn9xjy6qjiaap6pjgdc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by austinbutler** [comment]
Thanks, https://github.com/NixOS/nixpkgs/pull/323651 should fix it.
