### ISSUE TITLE
Documentation: package with unfree license - option c does not work

### ISSUE THREAD

**Issue by bramtechs** [NixOS/nixpkgs#323230]
## Problem

Following option C seems to not work.
nix-shell does not register the added option.

![image](https://github.com/NixOS/nixpkgs/assets/95661609/c3cd7d44-be95-4d1a-b820-8a6092f2ca68)

### shell.nix
```nix
{ pkgs ? import <nixpkgs> { config.android_sdk.accept_license = true; }, doom ? import <doomhowl> {} }:

let
    androidSdk = pkgs.androidenv.androidPkgs_9_0.androidsdk;
in
pkgs.mkShell
  {
    stdenv = pkgs.llvmPackages_18.libcxxStdenv;

    buildInputs = with pkgs; [
      doom.raylib
      doom.smalldeflate-cli
      llvmPackages_18.clangUseLLVM
      lldb
      janet
      rsync
      python3

      # mobile dev
      glibc
      jdk17
      androidSdk
      android-tools
    ];

    # override the aapt2 that gradle uses with the nix-shipped version
    GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdk}/libexec/android-sdk/build-tools/28.0.3/aapt2";
  }
```
### configuration.nix
```
{ config, lib, pkgs, callPackage, ... }:

{
 ....nix
  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.allowUnfreePredicate = _: true;
 ... 
}

```

### Versions
```
nix (Nix) 2.18.2
NixOS 24.05.1409.cc54fb41d137 (Uakari) x86_64
```

## Checklist

- [X] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [X] checked [open documentation issues] for possible duplicates
- [X] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Your system configuration has nothing to do with the shell; they are two different instances of nixpkgs. You have to follow the directions in the error correctly, you did option b which doesn't apply here.

**Comment by bramtechs** [comment]
Thanks for the explanation.
