### ISSUE TITLE
18.03 Zero Hydra Failures - aarch64 edition

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#32326]
See [the generic description](https://github.com/NixOS/nixpkgs/issues/36453).   This mainly makes a place to discuss aarch64-specific issues for ZHF.

As of https://hydra.nixos.org/eval/1430755, there are 263 aarch64-specific failures (here the exact criterion is: never succeeded in the trunk jobset on aarch64, is currently succeeding on x86_64, is not broken only due to failing dependencies):

- [ ] [a2jmidid](https://hydra.nixos.org/build/68006464)
- [ ] [aegisub](https://hydra.nixos.org/build/68383940): bundles luajit, needs marking x86-only
- [ ] [aften](https://hydra.nixos.org/build/67916598)
- [ ] [aircrack-ng](https://hydra.nixos.org/build/68606431): calls SSE builtins
- [ ] [altcoins.go-ethereum](https://hydra.nixos.org/build/68541765)
- [ ] [ams-lv2](https://hydra.nixos.org/build/68018386)
- [ ] [angelscript_2_22](https://hydra.nixos.org/build/67658213)
- [ ] [ao](https://hydra.nixos.org/build/68013029)
- [ ] [artyFX](https://hydra.nixos.org/build/68024988)
- [ ] [atlas](https://hydra.nixos.org/build/67644271)
- [ ] [audacity](https://hydra.nixos.org/build/68382194)
- [ ] [avy](https://hydra.nixos.org/build/68022517)
- [ ] [awless](https://hydra.nixos.org/build/68541034)
- [ ] [bcachefs-tools](https://hydra.nixos.org/build/68580033)
- [ ] [bcftools](https://hydra.nixos.org/build/67677356)
- [ ] [beignet](https://hydra.nixos.org/build/68006655)
- [ ] [betaflight](https://hydra.nixos.org/build/67815914)
- [ ] [blackmagic](https://hydra.nixos.org/build/67998931)
- [ ] [bonfire](https://hydra.nixos.org/build/68611182)
- [ ] [bootil](https://hydra.nixos.org/build/67646613)
- [ ] [bowtie2](https://hydra.nixos.org/build/68012255)
- [ ] [bud](https://hydra.nixos.org/build/67997985)
- [ ] [buildbot](https://hydra.nixos.org/build/68611215)
- [ ] [c3d](https://hydra.nixos.org/build/67995155)
- [ ] [cde](https://hydra.nixos.org/build/67667899)
- [ ] [chez](https://hydra.nixos.org/build/67650258): x86 compiler
- [ ] [cl](https://hydra.nixos.org/build/67997909)
- [ ] [clisp](https://hydra.nixos.org/build/67892004)
- [ ] [coyim](https://hydra.nixos.org/build/68537121)
- [ ] [cxxtools](https://hydra.nixos.org/build/67654729)
- [ ] [deadbeef](https://hydra.nixos.org/build/68005653)
- [ ] [devpi-client](https://hydra.nixos.org/build/68598256)
- [ ] [dgraph](https://hydra.nixos.org/build/68534190)
- [ ] [distrho](https://hydra.nixos.org/build/68286655)
- [ ] [doodle](https://hydra.nixos.org/build/68533203)
- [ ] [dwarf-fortress-packages.dwarf-therapist-original](https://hydra.nixos.org/build/68383448)
- [ ] [eduke32](https://hydra.nixos.org/build/68010975)
- [ ] [eid-mw](https://hydra.nixos.org/build/68536596)
- [ ] [emulationstation](https://hydra.nixos.org/build/68016486)
- [ ] [enlightenment.efl](https://hydra.nixos.org/build/68381519)
- [ ] [eq10q](https://hydra.nixos.org/build/68000728)
- [ ] [ezquake](https://hydra.nixos.org/build/68599941)
- [ ] [firebird](https://hydra.nixos.org/build/67672022)
- [ ] [firebirdSuper](https://hydra.nixos.org/build/67677992)
- [ ] [flashrom](https://hydra.nixos.org/build/68381504)
- [ ] [freerdp_legacy](https://hydra.nixos.org/build/68383358)
- [ ] [fribid](https://hydra.nixos.org/build/68016764)
- [ ] [ghq](https://hydra.nixos.org/build/68537526)
- [ ] [gitAndTools.ghq](https://hydra.nixos.org/build/68547756)
- [ ] [glucose](https://hydra.nixos.org/build/67669841)
- [ ] [gmp4](https://hydra.nixos.org/build/67653694)
- [ ] [gnustep.libobjc](https://hydra.nixos.org/build/68032098)
- [ ] [go-ethereum](https://hydra.nixos.org/build/68536781)
- [ ] [go_1_8](https://hydra.nixos.org/build/68539514)
- [ ] [gocryptfs](https://hydra.nixos.org/build/68545873)
- [ ] [gogs](https://hydra.nixos.org/build/68537040)
- [ ] [gprolog](https://hydra.nixos.org/build/67670704): compiler without aarch64 support
- [ ] [gravit](https://hydra.nixos.org/build/68020496)
- [ ] [gromacsDoubleMpi](https://hydra.nixos.org/build/68607267)
- [ ] [gromacsMpi](https://hydra.nixos.org/build/68606648)
- [ ] [grub2_xen](https://hydra.nixos.org/build/67996938)
- [ ] [gsl](https://hydra.nixos.org/build/67674646)
- [ ] [haka](https://hydra.nixos.org/build/68481727)
- [ ] [hardinfo](https://hydra.nixos.org/build/68003288): needs upgrade, latest tag is from 2009 but there's recent activity in git
- [ ] [hdf4](https://hydra.nixos.org/build/67916463)
- [ ] [hound](https://hydra.nixos.org/build/68537544)
- [ ] [hping](https://hydra.nixos.org/build/67658756)
- [ ] [i7z](https://hydra.nixos.org/build/68384836)
- [ ] [imatix_gsl](https://hydra.nixos.org/build/67661145)
- [ ] [imv](https://hydra.nixos.org/build/68000759)
- [ ] [inform7](https://hydra.nixos.org/build/67652138)
- [ ] [ipfs](https://hydra.nixos.org/build/68536857)
- [ ] [john](https://hydra.nixos.org/build/68538804)
- [ ] [kbfs](https://hydra.nixos.org/build/68539898)
- [ ] [kcov](https://hydra.nixos.org/build/67923576)
- [ ] [kitty](https://hydra.nixos.org/build/68383293)
- [ ] [kiwix](https://hydra.nixos.org/build/68237003)
- [ ] [kubernetes-helm](https://hydra.nixos.org/build/68541529)
- [ ] [lean2](https://hydra.nixos.org/build/67933973)
- [ ] [lenmus](https://hydra.nixos.org/build/68016202)
- [ ] [lensfun](https://hydra.nixos.org/build/67929065)
- [ ] [libagar_test](https://hydra.nixos.org/build/68384120)
- [ ] [libantlr3c](https://hydra.nixos.org/build/67656730)
- [x] [libb2](https://hydra.nixos.org/build/67673740) (https://github.com/NixOS/nixpkgs/pull/40362)
- [ ] [libibverbs](https://hydra.nixos.org/build/67676947)
- [ ] [liblbfgs](https://hydra.nixos.org/build/67665472)
- [ ] [libretro.desmume](https://hydra.nixos.org/build/68384279)
- [ ] [libretro.dolphin](https://hydra.nixos.org/build/68385818)
- [ ] [libretro.mame](https://hydra.nixos.org/build/68384176)
- [ ] [libretro.mupen64plus](https://hydra.nixos.org/build/68385390)
- [ ] [libretro.parallel-n64](https://hydra.nixos.org/build/68383668)
- [ ] [libretro.ppsspp](https://hydra.nixos.org/build/68381643)
- [ ] [libretro.reicast](https://hydra.nixos.org/build/68383523)
- [ ] [libretro.scummvm](https://hydra.nixos.org/build/68384957)
- [ ] [libsForQt5.qca-qt5](https://hydra.nixos.org/build/68385409)
- [ ] [libsForQt510.qca-qt5](https://hydra.nixos.org/build/68381609)
- [ ] [libsnark](https://hydra.nixos.org/build/67995698): has x86 inline assembly
- [ ] [libstdcxx5](https://hydra.nixos.org/build/67685265)
- [ ] [linuxPackages.evdi](https://hydra.nixos.org/build/68545071)
- [ ] [linuxPackages.openafsClient](https://hydra.nixos.org/build/68539080)
- [ ] [linuxPackages.sysdig](https://hydra.nixos.org/build/68546926)
- [ ] [linuxPackages_4_14.evdi](https://hydra.nixos.org/build/68543211)
- [ ] [linuxPackages_4_14.openafsClient](https://hydra.nixos.org/build/68541754)
- [ ] [linuxPackages_4_14.sysdig](https://hydra.nixos.org/build/68537314)
- [ ] [linuxPackages_4_15.sysdig](https://hydra.nixos.org/build/68483026)
- [ ] [linuxPackages_4_4.bbswitch](https://hydra.nixos.org/build/68541473)
- [ ] [linuxPackages_4_4.openafsClient](https://hydra.nixos.org/build/68537823)
- [ ] [linuxPackages_4_4.rtl8723bs](https://hydra.nixos.org/build/68536115)
- [ ] [linuxPackages_4_4.sysdig](https://hydra.nixos.org/build/68537266)
- [ ] [linuxPackages_4_9.evdi](https://hydra.nixos.org/build/68546433)
- [ ] [linuxPackages_4_9.openafsClient](https://hydra.nixos.org/build/68546702)
- [ ] [linuxPackages_4_9.sysdig](https://hydra.nixos.org/build/68538989)
- [ ] [linuxPackages_hardened.sysdig](https://hydra.nixos.org/build/68482814)
- [ ] [linuxPackages_latest.sysdig](https://hydra.nixos.org/build/68482870)
- [ ] [linuxPackages_latest_xen_dom0.sysdig](https://hydra.nixos.org/build/68482674)
- [ ] [llvm_35](https://hydra.nixos.org/build/68606970)
- [ ] [looking-glass-client](https://hydra.nixos.org/build/68600217)
- [ ] [ltrace](https://hydra.nixos.org/build/67649573)
- [ ] [luaffi](https://hydra.nixos.org/build/67675128)
- [ ] [lxdvdrip](https://hydra.nixos.org/build/67678559)
- [ ] [meshlab](https://hydra.nixos.org/build/68382261)
- [ ] [metersLv2](https://hydra.nixos.org/build/67999894)
- [ ] [mimetic](https://hydra.nixos.org/build/67649033)
- [ ] [minetest](https://hydra.nixos.org/build/68382136)
- [ ] [minisat](https://hydra.nixos.org/build/67649516)
- [ ] [mitscheme](https://hydra.nixos.org/build/68002767)
- [ ] [mitschemeX11](https://hydra.nixos.org/build/68026820)
- [ ] [mixxx](https://hydra.nixos.org/build/68383934)
- [ ] [mkcl](https://hydra.nixos.org/build/67649034)
- [ ] [mongodb](https://hydra.nixos.org/build/67997361)
- [ ] [mono48](https://hydra.nixos.org/build/68545564)
- [ ] [mono50](https://hydra.nixos.org/build/68539444)
- [ ] [mono54](https://hydra.nixos.org/build/68542268)
- [ ] [mplayer](https://hydra.nixos.org/build/68384901)
- [ ] [mps](https://hydra.nixos.org/build/67671684)
- [ ] [mupen64plus](https://hydra.nixos.org/build/67995719)
- [ ] [muscle](https://hydra.nixos.org/build/68363131)
- [ ] [mysql55](https://hydra.nixos.org/build/67920583)
- [ ] [nanoflann](https://hydra.nixos.org/build/67923933)
- [ ] [neovim-unwrapped](https://hydra.nixos.org/build/67912755)
- [ ] [neuron](https://hydra.nixos.org/build/67654359)
- [ ] [neuron-full](https://hydra.nixos.org/build/68606671)
- [ ] [neuron-mpi](https://hydra.nixos.org/build/68607017)
- [ ] [non](https://hydra.nixos.org/build/68004660)
- [ ] [nova-filters](https://hydra.nixos.org/build/67999969)
- [ ] [nvidia-texture-tools](https://hydra.nixos.org/build/67911758)
- [ ] [obs-studio](https://hydra.nixos.org/build/68381898)
- [ ] [ogre1_9](https://hydra.nixos.org/build/68023147)
- [ ] [open-wbo](https://hydra.nixos.org/build/67650709)
- [ ] [openbabel](https://hydra.nixos.org/build/67998333)
- [ ] [opencollada](https://hydra.nixos.org/build/67929705)
- [ ] [opencolorio](https://hydra.nixos.org/build/67921686)
- [ ] [opencpn](https://hydra.nixos.org/build/68015785)
- [ ] [openlibm](https://hydra.nixos.org/build/67677697)
- [ ] [openmvg](https://hydra.nixos.org/build/67937789)
- [ ] [openmvs](https://hydra.nixos.org/build/68381666)
- [ ] [openspades](https://hydra.nixos.org/build/68383121)
- [ ] [palemoon](https://hydra.nixos.org/build/68535671)
- [ ] [pgf_graphics](https://hydra.nixos.org/build/67920709)
- [ ] [picoc](https://hydra.nixos.org/build/67662682)
- [ ] [pjsip](https://hydra.nixos.org/build/67655461)
- [ ] [plink-ng](https://hydra.nixos.org/build/67664011)
- [ ] [plugin-torture](https://hydra.nixos.org/build/67996727)
- [ ] [pommed_light](https://hydra.nixos.org/build/67912479)
- [ ] [pond](https://hydra.nixos.org/build/68541137)
- [ ] [posterazor](https://hydra.nixos.org/build/68018744)
- [ ] [primusLib](https://hydra.nixos.org/build/67995283)
- [ ] [prometheus](https://hydra.nixos.org/build/68537388)
- [ ] [protobuf2_5](https://hydra.nixos.org/build/67684470): 2.x doesn't support aarch64
- [ ] [psi](https://hydra.nixos.org/build/68381567)
- [ ] [python27Packages.binaryornot](https://hydra.nixos.org/build/68025726)
- [ ] [python27Packages.cherrypy](https://hydra.nixos.org/build/68035519)
- [ ] [python27Packages.imread](https://hydra.nixos.org/build/68020028)
- [ ] [python27Packages.joblib](https://hydra.nixos.org/build/68038606)
- [ ] [python27Packages.neuron](https://hydra.nixos.org/build/67685460)
- [ ] [python27Packages.neuron-mpi](https://hydra.nixos.org/build/68606940)
- [ ] [python27Packages.pandas](https://hydra.nixos.org/build/68606835)
- [ ] [python27Packages.pyamf](https://hydra.nixos.org/build/68019726)
- [ ] [python27Packages.pytorch](https://hydra.nixos.org/build/68027533)
- [ ] [python27Packages.scikitlearn](https://hydra.nixos.org/build/68001516)
- [ ] [python27Packages.scrapy](https://hydra.nixos.org/build/68043839)
- [ ] [python27Packages.vmprof](https://hydra.nixos.org/build/68040251)
- [ ] [python36Packages.bayespy](https://hydra.nixos.org/build/68606800)
- [ ] [python36Packages.binaryornot](https://hydra.nixos.org/build/68020244)
- [ ] [python36Packages.cherrypy](https://hydra.nixos.org/build/68030072)
- [ ] [python36Packages.imread](https://hydra.nixos.org/build/68026031)
- [ ] [python36Packages.joblib](https://hydra.nixos.org/build/68027723)
- [ ] [python36Packages.neuron](https://hydra.nixos.org/build/67669659)
- [ ] [python36Packages.neuron-mpi](https://hydra.nixos.org/build/68607142)
- [ ] [python36Packages.pandas](https://hydra.nixos.org/build/68607319)
- [ ] [python36Packages.pyocr](https://hydra.nixos.org/build/68385972)
- [ ] [python36Packages.pytorch](https://hydra.nixos.org/build/68040199)
- [ ] [python36Packages.scikitlearn](https://hydra.nixos.org/build/67995740)
- [ ] [python36Packages.scrapy](https://hydra.nixos.org/build/68028183)
- [ ] [python36Packages.vmprof](https://hydra.nixos.org/build/68044108)
- [ ] [qdigidoc](https://hydra.nixos.org/build/68600088)
- [x] [qt5.qtwebengine](https://hydra.nixos.org/build/68538915)
- [x] [qt510.qtwebengine](https://hydra.nixos.org/build/68537298)
- [x] [qt59.qtwebengine](https://hydra.nixos.org/build/68547957)
- [ ] [qtpfsgui](https://hydra.nixos.org/build/68384777)
- [ ] [qtractor](https://hydra.nixos.org/build/68384051)
- [ ] [quantumminigolf](https://hydra.nixos.org/build/67997315)
- [ ] [radare](https://hydra.nixos.org/build/67937319)
- [ ] [rethinkdb](https://hydra.nixos.org/build/68008779)
- [ ] [rkrlv2](https://hydra.nixos.org/build/67995592)
- [ ] [rocksdb](https://hydra.nixos.org/build/67919216)
- [ ] [rocksdb_lite](https://hydra.nixos.org/build/67933812)
- [ ] [rucksack](https://hydra.nixos.org/build/67932009)
- [ ] [sbcl](https://hydra.nixos.org/build/68286762)
- [ ] [serfdom](https://hydra.nixos.org/build/68540393)
- [ ] [setbfree](https://hydra.nixos.org/build/67996971)
- [ ] [simplescreenrecorder](https://hydra.nixos.org/build/68384590)
- [ ] [slade](https://hydra.nixos.org/build/68003495)
- [ ] [softether](https://hydra.nixos.org/build/67681300)
- [ ] [softether_4_18](https://hydra.nixos.org/build/67649321)
- [ ] [softether_4_20](https://hydra.nixos.org/build/67645359)
- [ ] [sorcer](https://hydra.nixos.org/build/68000591)
- [ ] [spidermonkey_1_8_5](https://hydra.nixos.org/build/67646519)
- [ ] [srelay](https://hydra.nixos.org/build/67665577)
- [ ] [stag](https://hydra.nixos.org/build/67650102)
- [ ] [stella](https://hydra.nixos.org/build/67997678)
- [ ] [stepmania](https://hydra.nixos.org/build/68381917)
- [ ] [supercollider](https://hydra.nixos.org/build/68606423)
- [ ] [supercollider_scel](https://hydra.nixos.org/build/68607130)
- [ ] [sysprof](https://hydra.nixos.org/build/67995798)
- [ ] [tdesktop](https://hydra.nixos.org/build/68383825)
- [ ] [tennix](https://hydra.nixos.org/build/67998648)
- [ ] [terraform_0_8](https://hydra.nixos.org/build/68546390)
- [ ] [texstudio](https://hydra.nixos.org/build/68382779)
- [ ] [textadept](https://hydra.nixos.org/build/68013828)
- [ ] [the-powder-toy](https://hydra.nixos.org/build/68018106)
- [ ] [tightvnc](https://hydra.nixos.org/build/67937042)
- [ ] [tome4](https://hydra.nixos.org/build/68026374)
- [ ] [torch](https://hydra.nixos.org/build/68385494)
- [ ] [trezord](https://hydra.nixos.org/build/68023363)
- [ ] [tup](https://hydra.nixos.org/build/68018008): needs upgrade, upstream now has aarch64 support
- [ ] [twister](https://hydra.nixos.org/build/68383299)
- [ ] [uhub](https://hydra.nixos.org/build/67914654)
- [ ] [uim](https://hydra.nixos.org/build/68384326)
- [ ] [unicon-lang](https://hydra.nixos.org/build/67924520): x86-only compiler I think
- [ ] [v8_3_14](https://hydra.nixos.org/build/67995674)
- [ ] [v8_3_16_14](https://hydra.nixos.org/build/67995571)
- [ ] [v8_6_x](https://hydra.nixos.org/build/67929875)
- [ ] [vapoursynth](https://hydra.nixos.org/build/68607061)
- [ ] [vboot_reference](https://hydra.nixos.org/build/67924864)
- [ ] [vc](https://hydra.nixos.org/build/67932094)
- [ ] [vc_0_7](https://hydra.nixos.org/build/67922225)
- [ ] [voxelands](https://hydra.nixos.org/build/68012110)
- [ ] [wavegain](https://hydra.nixos.org/build/67654859)
- [ ] [welle-io](https://hydra.nixos.org/build/68382296)
- [ ] [x42-plugins](https://hydra.nixos.org/build/68017989)
- [ ] [xe-guest-utilities](https://hydra.nixos.org/build/67663490)
- [ ] [xfce.xfce4-battery-plugin](https://hydra.nixos.org/build/68006124)
- [ ] [xfce.xfce4_battery_plugin](https://hydra.nixos.org/build/68010334)
- [ ] [xfce4-12.xfce4-battery-plugin](https://hydra.nixos.org/build/68016604)
- [ ] [xfce4-12.xfce4_battery_plugin](https://hydra.nixos.org/build/68008022)
- [ ] [xgboost](https://hydra.nixos.org/build/67679698)
- [ ] [xmlrpc_c](https://hydra.nixos.org/build/67679825)
- [ ] [xonsh](https://hydra.nixos.org/build/67999674)
- [ ] [yap](https://hydra.nixos.org/build/67669461)
- [ ] [yarp](https://hydra.nixos.org/build/67917228)
- [ ] [yate](https://hydra.nixos.org/build/68385504)
- [ ] [zam-plugins](https://hydra.nixos.org/build/68013031)

(I'm re-using this as a scratchpad for some notes on why the packages are failing; that is for the unticked "needs marking x86-only" ones I just haven't got around to writing a patch yet, feel free to be faster than me to commit).

**Comment by vcunat** [comment]
- aegisub: luajit-2.1 [does support aarch64](https://hydra.nixos.org/job/nixpkgs/trunk/luajit.aarch64-linux).  Maybe it won't be hard to unbundle.

**Comment by volth** [comment]
```longview``` - x86-only. Anyway it works only on Linode VPS and they all are x86 so far

**Comment by volth** [comment]
far2l: https://github.com/NixOS/nixpkgs/pull/32396

**Comment by volth** [comment]
- [ ] chromium - also failed (Hydra does build it only for x86, so we see no failure)

**Comment by vcunat** [comment]
Hmm, at this rate of almost four thousand failing jobs (and no fast progress), we might need some script to exclude aarch64 automatically for packages that remain failing at the end of the month.

**Comment by dezgeg** [comment]
I think the single biggest cause is every single Haskell package failing, due to some old GHC not supporting AArch64, disabling the platform for that should cut a couple of thousand easily.

**Comment by vcunat** [comment]
@peti ^^ in case you have some simple idea how to work around the problem.

**Comment by volth** [comment]
It is the same on ```i686-linux``` and probably on ```armv7```
Number of non-Haskell packages depends on Haskell via ```pandoc``` to generate documentation. Sacrificing the documentation on the platforms where Haskell doesn't work would unbreak the packages (https://github.com/NixOS/nixpkgs/issues/36969)

**Comment by peti** [comment]
@vcunat, I pushed 736189fe74817fd848edd00fd720aa82af1bc2b0, which hopefully will make a difference.

**Comment by vcunat** [comment]
The final ghc build timeouted on Hydra.  I tried twice on the community machine, but it always segfaulted after a few hours.

**Comment by c00w** [comment]
kbfs is broken because it uses a vendored keybase client which doesn't support arm (the non vendored one does). I'll send them a PR to get it fixed.

**Comment by Thra11** [comment]
{qt5,qt511,qt59}.qtwebengine are now passing: https://hydra.nixos.org/eval/1475582

**Comment by Mic92** [comment]
I think we need a new working list for 18.09.

**Comment by vcunat** [comment]
We should have a hydra jobset for that in less than a week.

**Comment by vcunat** [comment]
Thanks for all the fixes in 18.03 round! (I'm late, I know.)

The next ZHF iteration: https://github.com/NixOS/nixpkgs/issues/45962
