### ISSUE TITLE
Update request: pot 2.7.9 → 3.0.5

### ISSUE THREAD

**Issue by aucub** [NixOS/nixpkgs#323241]
- Package name: pot
- Latest released version: 3.0.5

- Current version on the unstable channel: 2.7.9
- Current version on the stable/release channel: 2.7.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@linsui 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
https://github.com/pot-app/pot-desktop#环境要求
https://github.com/NixOS/nixpkgs/pull/320250
