### ISSUE TITLE
Update request: hardinfo 0.x -> 2.x (new upstream)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#323355]
I got this message from (new) upstream:

```
We have rebooted the hardinfo program (System information and benchmark) that has not had any releases for >10 years as community edition hardinfo2.

Please update hardinfo to hardinfo2.

Project www - https://hardinfo2.org/

GitHub - https://github.com/hardinfo2/hardinfo2
See README.md for nix configuration.

Release 2.1.11: (Base for all distros)
https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.11
PS: It needs lots of nix updates, as you had a very old version from before Berlios was shut down, the last 15 years it was hosted here https://github.com/lpereira/hardinfo and is now moved to the above community github as you can read in the README.md (Top warning - moving to hardinfo2/hardinfo2).
```

**Notify maintainers**
(I'm the only listed maintainer. Help wanted.)

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
No sure why I get a segfault while trying to use `hardinfo2`

**Comment by hwspeedy** [comment]
Changed the following:
removed the patch for distro /etc/os-release and added new patch that disables binreloc:

```
diff --git a/config.h.cmake b/config.h.cmake
index 08ae529..0a5d812 100644
--- a/config.h.cmake
+++ b/config.h.cmake
@@ -39,6 +39,6 @@
   #endif
 #endif	/* HARDINFO2_DEBUG */
 
 #define HAS_LINUX_WE 1
 
 #cmakedefine01 HAS_LIBSENSORS
```

**build & run**
running on ubuntu 20.04.4 LTS as root:
nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
./result/bin/hardinfo2

themes are not working - but started:
![image](https://github.com/user-attachments/assets/270a35cc-981b-4a3a-ab9c-3ba13bc911da)

**Comment by hwspeedy** [comment]
How do I add QT5 build requirements:  libqt5opengl5-dev qtbase5-dev, that are needed for next stable (rev="refs/heads/master")?

**Comment by hwspeedy** [comment]
Just installed **Nixos** for the first time - works great!

Don't know why the /etc/os-release from nix is not made available to build - It should be...

Patch for no /etc/os-release when nix building on nixos (Will be submitted to master later)

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d529473..50fb49d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -68,20 +68,26 @@ set(PACKAGE_LIBSOUP2_MINVERSION 2.42)
 set(PACKAGE_LIBGLIB2_MINVERSION 2.24)

 #########################CPack PACKAGING SETUP###############################
+if(EXISTS "/etc/os-release")
+  file(STRINGS /etc/os-release distro REGEX "^NAME=")
+  file(STRINGS /etc/os-release disversion REGEX "^VERSION_ID=")
+  file(STRINGS /etc/os-release disversioncode REGEX "^VERSION_CODENAME=")
+else()
+  set(distro "Linux")
+  set(disversion "99")
+  set(disversioncode "Linux")
+endif()
 set(RPM 0)
-file(STRINGS /etc/os-release distro REGEX "^NAME=")
 string(REGEX REPLACE "NAME=" "" distro "${distro}")
 string(REGEX REPLACE "\"" "" distro "${distro}")
 string(REGEX REPLACE "/" "" distro "${distro}")
 string(REGEX REPLACE " " "" distro "${distro}")
-file(STRINGS /etc/os-release disversion REGEX "^VERSION_ID=")
 string(REGEX REPLACE "VERSION_ID=" "" disversion "${disversion}")
 string(COMPARE EQUAL "${disversion}" "" result)
 if(result)
   #sid/rawhide with no version - use project name
   message("-- Found no distro version - Using codename")
-  file(STRINGS /etc/os-release disversion REGEX "^VERSION_CODENAME=")
-  string(REGEX REPLACE "VERSION_CODENAME=" "" disversion "99_${disversion}")
+  string(REGEX REPLACE "VERSION_CODENAME=" "" disversion "99_${disversioncode}")
 endif()
 string(REGEX REPLACE "\"" "" disversion "${disversion}")
 string(REGEX REPLACE "/" "" disversion "${disversion}")
```

**Comment by bjornfor** [comment]
> Don't know why the /etc/os-release from nix is not made available to build - It should be...

It's due to the Nix build sandbox which is intentionally isolating build processes from the host OS, to help with reproducible/reliable builds.

**Comment by hwspeedy** [comment]
Yes, that part is so great - super system.

But how to add the /etc/os-release to the sandbox?

**Comment by hwspeedy** [comment]
Patch to detect NixOS distribution

```
diff --git a/modules/computer/os.c b/modules/computer/os.c
index c8bee8d..849a68a 100644
--- a/modules/computer/os.c
+++ b/modules/computer/os.c
@@ -457,6 +457,7 @@ detect_distro(void)
         { DB_PREFIX "distro-release", "fl" },
         { DB_PREFIX "vine-release", "vine" },
         { DB_PREFIX "PartedMagic-version", "pmag" },
+        { DB_PREFIX "NIXOS", "nixos", "NixOS Linux" },
          /*
          * RedHat must be the *last* one to be checked, since
          * some distros (like Mandrake) includes a redhat-relase
```

![image](https://github.com/user-attachments/assets/8cb4f1fb-5e8c-48ab-9609-afc5c9b37f81)

**Comment by hwspeedy** [comment]
Patch for missing theme:

```
diff --git a/shell/callbacks.c b/shell/callbacks.c
index 07900e9..0d8a7af 100644
--- a/shell/callbacks.c
+++ b/shell/callbacks.c
@@ -145,7 +145,7 @@ void cb_disable_theme()
 {
     Shell *shell = shell_get_main_shell();
     // *shelltree=shell->tree;
-    char theme_st[200];
+    char theme_st[400];
     GKeyFile *key_file = g_key_file_new();
 #if GTK_CHECK_VERSION(3, 0, 0)
     GtkCssProvider *provider;
@@ -185,9 +185,9 @@ void cb_disable_theme()
 #if GTK_CHECK_VERSION(3, 0, 0)
     if(params.theme>0){//enable
        if(params.darkmode){
-          sprintf(theme_st,"window.background {background-image: url(\"/usr/share/hardinfo2/pixmaps/bg%d_dark.jpg\"); background-repeat: no-repeat; background-size:100%% 100%%; }",params.theme);
+          sprintf(theme_st,"window.background {background-image: url(\"%s/pixmaps/bg%d_dark.jpg\"); background-repeat: no-repeat; background-size:100%% 100%%; }",params.path_data,params.theme);
        }else{
-           sprintf(theme_st,"window.background {background-image: url(\"/usr/share/hardinfo2/pixmaps/bg%d_light.jpg\"); background-repeat: no-repeat; background-size:100%% 100%%; }",params.theme);
+          sprintf(theme_st,"window.background {background-image: url(\"%s/pixmaps/bg%d_light.jpg\"); background-repeat: no-repeat; background-size:100%% 100%%; }",params.path_data,params.theme);
        }
        gtk_css_provider_load_from_data(provider, theme_st, -1, NULL);
        if(shell->window) gtk_style_context_add_provider(gtk_widget_get_style_context(shell->window), GTK_STYLE_PROVIDER(provider), GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
```

**Comment by hwspeedy** [comment]
**SUCCESS**

**The following patches are added to hardinfo2 master/Next Release:**
1. PACKAGING fix for distros without /etc/os-release
https://github.com/hardinfo2/hardinfo2/commit/bd5ef6c6eca0a8ff5b53987a765d331c46a5b84e

2. FIX Disabled binreloc for all distros
https://github.com/hardinfo2/hardinfo2/commit/cf3bda721086b1d865d9874cff26da408e0e67d0

3. FIX Added NixOS distro detection
https://github.com/hardinfo2/hardinfo2/commit/93795c46b3dee6218d3ddeec3312dc768c57ac41

4. FIX hardcoded theme datadirs fixed
https://github.com/hardinfo2/hardinfo2/commit/96d27e70fa410408a0740bde1172dc15668e8c13

**Seams working fine now**

@bjornfor @Sigmanificient 

1. Please continue work on submitting the nix file for 2.1.11 thanx
   Note 4 patches for 2.1.11 are in the previous messages.

2. Please if you could also help getting nix ready for next release with service and QT5 OpenGL.
How do I add QT5 build requirements to nix file: libqt5opengl5-dev qtbase5-dev, that are needed for next stable/master repo (rev="refs/heads/master")?

/hwspeedy

**Comment by bjornfor** [comment]
@hwspeedy: Nice progress!

> How do I add QT5 build requirements to nix file: libqt5opengl5-dev qtbase5-dev, that are needed for next stable/master repo (rev="refs/heads/master")?

grepping nixpkgs? I couldn't find libqt5opengl5-dev equivalent, but I think qtbase5-dev is made available by adding `qt5.qtbase` to buildInputs. Or if you want the exact dev output: `lib.getDev qt5.qtbase`.

**Comment by bjornfor** [comment]
@hwspeedy: I tested the [nix_hardinfo2.tgz](https://github.com/user-attachments/files/16728161/nix_hardinfo2.tgz) expression and it results in mostly empty GUI. I'm running Wayland. Are you on X11?

**Comment by bjornfor** [comment]
> @hwspeedy: I tested your [nix_hardinfo2.tgz](https://github.com/user-attachments/files/16728161/nix_hardinfo2.tgz) expression and it results in mostly empty GUI. I'm running Wayland. Are you on X11?

Sorry, I didn't test _exactly_ that expression (I pointed src to a local source repo). When I run it exactly as it it works.

**Comment by bjornfor** [comment]
Updated Nix expression that fetches hardinfo2 from the master branch, applies a one-line patch, and enables opengl benchmark:

```nix
{
  lib,
  stdenv,
  fetchFromGitHub,
  cmake,
  pkg-config,
  gtk3,
  json-glib,
  lerc,
  libdatrie,
  libepoxy,
  libnghttp2,
  libpsl,
  libselinux,
  libsepol,
  libsoup_3,
  libsysprof-capture,
  libthai,
  libxkbcommon,
  pcre2,
  sqlite,
  util-linux,
  wrapGAppsHook,
  xorg,
  libsForQt5,
}:

stdenv.mkDerivation rec {
  pname = "hardinfo2";
  version = "2.1.11+dev";

  src = fetchFromGitHub {
    owner = "hardinfo2";
    repo = "hardinfo2";
    rev = "96d27e70fa410408a0740bde1172dc15668e8c13";  # master @ Fri Aug 23 13:26:19 2024 +0200
    hash = "sha256-pi+OtaQqAcFhr/I2yhtp8xVdM+8kGfc/M4RelBgNW08=";
  };
  #src = ~/inbox/hardinfo2;

  patches = [
    (builtins.toFile "hardinfo2.patch" ''
      diff --git a/CMakeLists.txt b/CMakeLists.txt
      index 9f55890..b419c77 100644
      --- a/CMakeLists.txt
      +++ b/CMakeLists.txt
      @@ -550,7 +550,7 @@ configure_file(hardinfo2.desktop.cmake ''${CMAKE_BINARY_DIR}/hardinfo2.desktop @ON
       
       if(HARDINFO2_SERVICE)
           #cannot use CMAKE_INSTALL_LIBDIR due to distros with dual lib (arch)-gnu-linux,lib64
      -    set(CMAKE_INSTALL_SERVICEDIR "/usr/lib")
      +    set(CMAKE_INSTALL_SERVICEDIR "/usr/lib" CACHE PATH "Path where the systemd service file gets installed")
           message("ServiceDir=" ''${CMAKE_INSTALL_SERVICEDIR})
       
           if(''${HARDINFO2_SYSTEMV})

    '')
  ];

  nativeBuildInputs = [
    cmake
    libsForQt5.wrapQtAppsHook
    pkg-config
    #wrapGAppsHook  # TODO: unneeded? remove?
  ];

  buildInputs = [
    gtk3
    json-glib
    #lerc  # TODO: unneeded?
    libdatrie
    libepoxy
    libnghttp2  # TODO: still not found -- cmake warns
    libpsl
    libselinux
    libsepol
    libsoup_3  # TODO: still not found -- cmake warns
    libsysprof-capture
    libthai
    #libxkbcommon  # TODO: unneeded?
    #pcre2  # TODO: unneeded?
    #sqlite  # TODO: unneeded?
    util-linux
    xorg.libXdmcp
    xorg.libXtst
    libsForQt5.qtbase
  ];

  hardeningDisable = [ "fortify" ];

  cmakeFlags = [
    (lib.cmakeFeature "CMAKE_INSTALL_DATAROOTDIR" "${placeholder "out"}/share")
    (lib.cmakeFeature "CMAKE_INSTALL_SERVICEDIR" "${placeholder "out"}/lib")
  ];

  meta = {
    description = "System Information and Benchmark for Linux Systems ";
    homepage = "http://www.hardinfo2.org";
    license = with lib.licenses; [
      gpl2Plus
      gpl3Plus
      lgpl2Plus
    ];
    maintainers = with lib.maintainers; [ ];
    platforms = lib.platforms.unix;
    mainProgram = "hardinfo2";
  };
}
```

**Comment by hwspeedy** [comment]
Okay, I used single user mode, so thats why, no sandbox... thanx for info.

Great, I will try masterbuild, thanx.

Recommended packages are probably missing. See README.md for info.

**Comment by bjornfor** [comment]
> Updated Nix expression that fetches hardinfo2 from the master branch, applies a one-line patch, and enables opengl benchmark:

TODO: hardinfo2 shells out to a bunch of tools (iperf3, lsmod, ...); they should be specified by the Nix package.

**Comment by hwspeedy** [comment]
Building from master finishes and can be installed - YES, Good job!

**TODO for next release**
1) as we know from above the recommended packages are not installed. **(IMPORTANT TO 2.1.11)**

2) OpenGL testbench is compiled, but opengl plugins are not installed
test the compiled app: 
./result/lib/hardinfo2/modules/qgears2
./result/lib/hardinfo2/modules/qgears2 -gl
result:
qt.qpa.plugin: Cloud not find the Qt platform plugin "xcb" in ""

2) Service is not enabled and started

3) Service does not work correctly - it should modprobe 3 SPD modules (Does not happen). Should put a read of iomem and ioports into /tmp/ - they are empty - size=0.

**Comment by hwspeedy** [comment]
2) 
Okay, NixOS is something new for me - with sandboxing apps. Really demanding for my poor brain after 1 days use of NixOS :)

"GPU OpenGL Drawing" test in hardinfo2 program is working! (Bottom)
But you cannot call the program directly in store - not working - and fine...

So 2 is closed.

**Comment by bjornfor** [comment]
> 3. Service is not enabled and started
> 
> 4. Service does not work correctly - it should modprobe 3 SPD modules (Does not happen). Should put a read of /proc/iomem and /proc/ioports into /tmp/ - they are empty - size=0.

I looked at the service and I'm not sure that's something I'd like to run on a multi-user system, without first learning more about the info it exposes. (I guess the files are only readable by root for a reason?)

Anyway, fixing (and enabling) the service happens at the NixOS level, not at the package level, so I don't think it's a blocker for packaging hardinfo2.

**Comment by hwspeedy** [comment]
I am not sure about that - They use potential harmfull functions in kernel to gain the io/mem ranges that needs uid=0 - so it's probably more a question of not putting too much code into the kernel or lack of time to make a read only version - interrupts, dma are readonly. Device trees shows io/mem ranges readonly.

The SPD modules are going towards autoloading and uses auto probe for now. The old eeprom is not loaded as that is deprecated way.

The DMI tables are to read number of dimm memory modules, no secret in DMI as far as I can see.

Let me know what you find out, thanx.

**Comment by Sigmanificient** [comment]
@bjornfor  I see that you are using `libsForQt5.wrapQtAppsHook`, but using it instead of the `wrapGAppsHook`, I get  `No GSettings schemas are installed on the system`

**Comment by bjornfor** [comment]
> Without `wrapGAppsHook`, I get `No GSettings schemas are installed on the system` at startup.

Thanks for testing. I switched from gtk to qt hook because I assumed the app was being rewritten in qt, due to a comment above. If the qt/opengl stuff works with the gtk hook alone then great! (Otherwise we can use both hooks too, but avoid double wrapping.)

**Comment by hwspeedy** [comment]
Version 2.1.14 released with patches for Nix/NixOs + more: https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.14

**Comment by hwspeedy** [comment]
What is the status of updating hardinfo (remove) to hardinfo2 2.1.14 in NixPkgs/NixOS?

**Comment by bjornfor** [comment]
I haven't had time/energy to look at it, but I can probably review PRs.

**Comment by hwspeedy** [comment]
Hi @bjornfor,

Hardinfo2 - Released 2.1.17 today.

Can be build on NixOS with -DHARDINFO_SERVICE=0 and -DHARDINFO_LIBSOUP3=0

Choice libsoup 2.4 or 3 does not matter - it is all for support of the distro's choice. And Nix seams to like libsoup2.4.

[build.sh.txt](https://github.com/user-attachments/files/17216054/build.sh.txt)
[default.nix.txt](https://github.com/user-attachments/files/17216055/default.nix.txt)
PS: Remove .txt from files and run ./build.sh

**Note: That I am installing the package dependencies in the build.sh batch file: (PLEASE FIXME)**
sysbench: is needed to run standard sysbench benchmarks.
udisks2: is needed to provide NVME++ informations.
dmi-decode: is needed to provide DMI informations.
mesa-utils: is needed to provide opengl and run standard sysbench benchmarks.
lsscsi: gives information about hard drives.
lm-sensors: is needed to provide sensors values.
xdg-utils: xdg_open is used to open your browser for bugs, homepage & links.
iperf3: iperf3 is used to benchmark internal network speed.
fwupd: fwupd is used to read and display information about firmware in system.
Service: Service loads SPD modules (at24/ee1004/spd5118) to display SPD info for your DIMMs memory. Show addresses for iomem+ioports.
xrandr/x11-xserver-utils: xrandr is used to read monitor setup
vulkan-tools: vulkaninfo is used to display vulcan information.

**NOTE: in nix, iperf3 is packaged with binary name iperf3d - hence "internal network benchmark" does not work!**

**Comment by hwspeedy** [comment]
**iperf3 fix:** 
install package iperf instead of iperf3d.

**Comment by boustanihani** [comment]
Im getting the following error when I add the package to my config:
`error: undefined variable 'hardinfo2'`

**Comment by bjornfor** [comment]
@boustanihani: The package is available in nixos-24.11 and later. If you get that error you are probably using a too old nixpkgs, or have some kind of configuration issue (e.g. forgetting `with pkgs;`?).

**Comment by boustanihani** [comment]
I am using `nixos-24.11`

**Comment by boustanihani** [comment]
Now it worked, seems it needs time to get recognized :)
