### ISSUE TITLE
rawtherapee-git: outdated, can it be removed?

### ISSUE THREAD

**Issue by andir** [NixOS/nixpkgs#32337]
## Issue description

[rawtherapee-git](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/rawtherapee/dev.nix) hasn't received an update in well above a year since it has been introduced. The stable version [rawtherapee](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/rawtherapee/default.nix) has received multiple updates in the same timeframe - and ships are more recent version.

Additionally the current `-git` version which is marked as `dev` is breaking on newer gcc versions. (see #31747)

So I am asking the maintainers (@viric @jcumming @2chilled @the-kenny) (or anyone else with "authority"):
 - Can the `-git` version can be removed?
 - Or: Will it receive updates?

**Comment by the-kenny** [comment]
👍 for removing it.
