### ISSUE TITLE
kdenlive: "Cannot find your MLT profiles, please give the path"

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#323309]
### Describe the bug

Confusing message on first run
![image](https://github.com/NixOS/nixpkgs/assets/848000/808c0ed4-a67a-4c22-aa87-d25e5335d5a9)

### Steps To Reproduce
1. Start kdenlive

### Expected behavior
No error

### Screenshots
See above

### Additional context
Running from terminal gives the following messages:

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
MESA: warning: Support for this platform is experimental with Xe KMD, bug reports may be ignored.
Could not detect package type, probably default? App dir is "/nix/store/nza2l4sr31bw6clww3vdl644dyc20456-kdenlive-24.05.1/bin"
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
profilePath from KdenliveSetting::mltPath:  "/nix/store/b7f98vz0nnglxgml64ifc0kz3kz3ddj3-mlt-7.22.0/share/mlt-7/profiles"
profilePath from appDir/../share:  "/nix/store/nza2l4sr31bw6clww3vdl644dyc20456-kdenlive-24.05.1/share/mlt-7/profiles"
meltPath from KdenliveSetting::meltPath:  "/nix/store/p1g8vgrq1hcv7zvbq8n8y4vh83pwrx11-mlt-7.24.0/bin/melt"
profilePath from KdenliveSetting::mltPath:  "/usr/local/share/mlt-7/profiles"
profilePath from appDir/../share:  "/nix/store/nza2l4sr31bw6clww3vdl644dyc20456-kdenlive-24.05.1/share/mlt-7/profiles"
meltPath from KdenliveSetting::meltPath:  "/nix/store/p1g8vgrq1hcv7zvbq8n8y4vh83pwrx11-mlt-7.24.0/bin/melt"
```

and I should point out, `/nix/store/b7f98vz0nnglxgml64ifc0kz3kz3ddj3-mlt-7.22.0/share/mlt-7/profiles` doesn't even exist

### Notify maintainers
@turion

### Metadata
Tested on Nixpkgs revision 2893f56de08021cffd9b6b6dfc70fd9ccd51eb60 on x86_64-linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by turion** [comment]
I can reproduce something similar in a VM:

![image](https://github.com/NixOS/nixpkgs/assets/303489/caae1e59-09c9-42dc-8fda-929de3745b73)

@tobiasBora do you think this is a duplicate of https://github.com/NixOS/nixpkgs/issues/209923?

**Comment by K900** [comment]
This is a separate issue that should have been fixed.

**Comment by eclairevoyant** [comment]
Seems fixed.

**Comment by Ember-ruby** [comment]
i'm having this issue, latest unstable, kdePackages.kdenlive package, and MLT installed

**Comment by Ember-ruby** [comment]
![Image](https://github.com/user-attachments/assets/f66aac96-6595-461b-9095-c351e5b6020a)

**Comment by K900** [comment]
Works fine here. Try removing your ~/.config/kdenliverc.

**Comment by Ember-ruby** [comment]
looks like the config had the MLT path set to a previous nix store location
