### ISSUE TITLE
Build failure: libtransmission_4 on x86_64-darwin

### ISSUE THREAD

**Issue by al3xtjames** [NixOS/nixpkgs#323464]
### Steps To Reproduce

1. `nix build 'nixpkgs#libtransmission_4'`

### Build log

https://gist.github.com/al3xtjames/fee8d1d160e245b35ab85037f9f853c4

### Additional context

I suspected this had something to do with the version passed to `CMAKE_OSX_DEPLOYMENT_TARGET`, but bumping it didn't make a difference.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Lix, like Nix) 2.90.0-rc1-pre20240615-253546d`
 - nixpkgs: `/nix/store/rhg90jpryc286xn9xjy6qjiaap6pjgdc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ofalvai** [comment]
FYI this builds fine on the current `staging-next`, so I think can be closed once the current staging cycle completes

**Comment by al3xtjames** [comment]
Thanks for the heads up! I can confirm that `nix build 'github:NixOS/nixpkgs/staging-next#libtransmission_4'` succeeds. I think the SDK refactor fixed it.

**Comment by al3xtjames** [comment]
I'm closing this as [the SDK changes have been merged into nixpkgs-unstable](https://nixpk.gs/pr-tracker.html?pr=346043) and libtransmission_4 builds again.
