### ISSUE TITLE
Plasmashell allocates >260GB of VIRT

### ISSUE THREAD

**Issue by williammpratt** [NixOS/nixpkgs#32352]
## Issue description
@ttuegel  Plasmashell unexpectedly allocates >260GB of VIRT. 

![image](https://user-images.githubusercontent.com/33880204/33618103-eaa83718-d9e1-11e7-828f-5b7724e91452.png)

### Steps to reproduce
Just run plasmashell for a day and use it. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
Why is that unexpected?

**Comment by FRidh** [comment]
Its an upstream issue https://bugs.kde.org/show_bug.cgi?id=387128

**Comment by williammpratt** [comment]
I switched to xfce4, until this is fixed, because Plasma5 is unusable in this version. If someone knows of a version of Plasma5 that I can run that is in a binary cache without this issue, I can switch back to Plasma5.

**Comment by orivej** [comment]
@williammpratt Could you explain in what way is plasma unusable, without guessing why it is so? (I use it quite successfully; its virtual memory usage is up to 5GB in my case.)

**Comment by orivej** [comment]
One thing that might (or might not) help is to configure the tray to hide icons with frequent animations, including the notifications icon. (I didn't do this, but it is automatically hidden.)

**Comment by williammpratt** [comment]
plasmashell uses 80% of a core continuously after hours of use to the point that it throttles the CPU. I use an instant messaging application which displays popups on a regular basis. Not having this instant messaging capability is not an option for me.

It introduces noticable lag in the UI.

**Comment by grahamc** [comment]
Seems to be an upstream issue.
