### ISSUE TITLE
add example for docker-containers option

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32366]
## Issue description

`docker-containers` has no example value. please add one so one knows how to use it.

cc @copumpkin 

### Steps to reproduce

https://nixos.org/nixos/options.html#docker-containers

**Comment by kevlar1818** [comment]
Friendly bump! I'm looking to start some containers on boot, and I feel like this might be the place?

**Comment by copumpkin** [comment]
This was an experimental feature that I merged by accident. It's been backed out of master but I didn't realize it was in 17.09 too. It shouldn't affect anything for users. See https://github.com/NixOS/nixpkgs/pull/26075 for more details.

**Comment by davidak** [comment]
It is not present anymore in 18.03, so this issue is fixed.

@kevlar1818 have a look at https://github.com/NixOS/nixpkgs/issues/37553
