### ISSUE TITLE
Update request: pluggy 1.4.0 → 1.5.0

### ISSUE THREAD

**Issue by nils-van-zuijlen** [NixOS/nixpkgs#323787]
- Package name: pluggy
- Latest released version: 1.5.0

- Current version on the unstable channel: 1.4.0
- Current version on the stable/release channel: 1.4.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dotlambda 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nils-van-zuijlen** [comment]
When using other packages installed in a virtualenv that use recent pytest, they crash because some variables do not exist. Using pluggy 1.5.0 fixes it.

**Comment by dotlambda** [comment]
fixed by fixed by https://github.com/NixOS/nixpkgs/pull/306354
