### ISSUE TITLE
Update request: nodejs_20 20.12.2 → 20.15.0

### ISSUE THREAD

**Issue by lukas-mertens** [NixOS/nixpkgs#323764]
- Package name: nodejs_20
- Latest released version: 20.15.0

- Current version on the unstable channel: 20.12.2
- Current version on the stable/release channel: 20.12.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

https://github.com/NixOS/nixpkgs/pull/323119 exists but is already outdated

**Notify maintainers**
@cillianderoiste 
@cko 
@aduh95 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
already done 

https://github.com/NixOS/nixpkgs/pull/321292

you can track merge progress https://nixpk.gs/pr-tracker.html?pr=321292
