### ISSUE TITLE
Hyprland not listed on GDM

### ISSUE THREAD

**Issue by Septias** [NixOS/nixpkgs#323888]
### Describe the bug
I can no longer select Hyprland on GDM. 

### Steps To Reproduce
Enable gdm, gnome and hyprland. Hyprland on home manager.

### Expected behavior
Hyprland should show up on GDM.

### Additional context
My config: https://github.com/Septias/nixos-config

### Notify maintainers

@fufexan

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.35, NixOS, 24.05 (Uakari), 24.05.20240624.fc07dc3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/r5clili0iqprbn4dnngkywsgxm51a5cw-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
You have to enable hyprland's nixos module.

**Comment by Septias** [comment]
Solvd, ty
