### ISSUE TITLE
Update request: openssh 9.7p1 → 9.8p1 (critical vulnerability in sshd on glibc systems)

### ISSUE THREAD

**Issue by Kyubai** [NixOS/nixpkgs#323809]
- Package name: openssh
- Latest released version: 9.8p1 
- Current version on the unstable channel: 9.7p1
- Current version on the stable/release channel: 9.7p1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Conni2461 

-----

There is a critical vulnerability in ssh
https://www.openssh.com/releasenotes.html
https://thehackernews.com/2024/07/new-openssh-vulnerability-could-lead-to.html

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ivan770** [comment]
Duplicate. #323753
