### ISSUE TITLE
Update request: nodejs_22

### ISSUE THREAD

**Issue by slinkynexus** [NixOS/nixpkgs#323896]
https://github.com/NixOS/nixpkgs/blob/e2dd4e18cc1c7314e24154331bae07df76eb582f/pkgs/development/web/nodejs/v22.nix#L11

The current version of nodejs is 22.3.0, as referenced here:
https://nodejs.org/en/download/package-manager

**Comment by eclairevoyant** [comment]
Actually looks like it's already updated as of two weeks ago: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/nodejs/v22.nix#L11

Ensure to use the nixpkgs-unstable or nixos-unstable channel
