### ISSUE TITLE
Build failure: mindustry

### ISSUE THREAD

**Issue by nikitax44** [NixOS/nixpkgs#323856]
### Steps To Reproduce

1. `nix build 'nixpkgs#mindustry'` on nixos-unstable branch

### Build log

https://gist.github.com/nikitax44/9196ed6995755a3b7eb1fe5693393f6a

### Additional context

first bad commit: 48d567fc7b299de90f70a48e4263e31f690ba03e

### Notify maintainers

@chkno @fgaz @TheKostins

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240629.2741b4b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/g83ji892byw4wd81rmb14v69yrhq408s-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
`minindustry` is building at `master`. Please, always test software in master. There is nothing to be done here.
