### ISSUE TITLE
How to build minimal ISO without X11?

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#32383]
## Issue description
I don't understand why libX11 used in installation-cd-minimal.nix?
And how to disable X11 or any other unwanted packages?
Thanks for answer.

### Steps to reproduce
https://gist.github.com/MrSorcus/0eeedcf404be472ae0e1d0a2b9c42429 - nix derivation.
nix-build -A config.system.build.isoImage -I nixos-config=./nixos_cd_iso.nix ./default.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.65, NixOS, 18.03pre121732.cc1d7a358f5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121732.cc1d7a358f5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by andir** [comment]
Try setting `environment.noXlibs = true`.
At least pam (depends on xauth) and dbus depend on X11.
