### ISSUE TITLE
Wallpaper previously working via "services.xserver.desktopManager.wallpaper.mode" quit working after update.

### ISSUE THREAD

**Issue by cabbott008** [NixOS/nixpkgs#323923]
### Describe the bug
Though the associated feh command works fine in the terminal, this option has stopped working despite no changed to the wallpaper was made. If I manually set it, the wallpaper requires manual setting again upon reboot.

I have talked to other users who can no longer get this option to work either. This issue persists on all three machines that I manage.

https://github.com/NixOS/nixpkgs/commits/nixos-24.05/nixos/modules/services/x11/desktop-managers/default.nix

### Steps To Reproduce
1. ... Reboot
2. ...
3. ...

### Expected behavior
Wallpaper to display as it did previously.

### Notify maintainers
@jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 ```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240629.2741b4b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/g83ji892byw4wd81rmb14v69yrhq408s-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
What desktop environment do you use?

Personally, I would just remove the option as I think it is a hack that does not compose well with different DEs, resulting in issues like this.

**Comment by cabbott008** [comment]
Thank you for your reply.

I use Qtile. This option was working great on all three computers for my whole time on NixOS until a recent update. I can fix it in a variety of ways, of course, but wanted to do it "the Nix-way." 

I think we should either make the option reliable or depreciate the option. Or, at a minimum, make a note in the documentation to its limited-use cases and maybe link to another method.

Thanks again. I hope to learn enough that someday I can understand the inner workings sufficiently that I could efficiently diagnose what the cause it and assess what it would take to fix it.

**Comment by jtojnar** [comment]
I vaguely recall someone saying years ago that feh works by drawing in the X server root window. So if anything does that for whatever reason too, the background will be overwritten.

I would recommend preferring DE/WM-native way of setting wallpaper when available since if the above is true, feh is inherently unreliable.

I found this for Qtile: https://old.reddit.com/r/Ubuntu/comments/jv0v3d/comment/hj719oc/

**Comment by cabbott008** [comment]
> I would recommend preferring DE/WM-native way of setting wallpaper when available since if the above is true, feh is inherently unreliable.

I went with your recommendation and integrated the wallpaper with Qtile directly.

Thank you.

I still think a note or depreciation of the option could be in order.

Thanks again.

**Comment by jtojnar** [comment]
> I still think a note or depreciation of the option could be in order.

That would be nice but we would probably want to plan a removal and I am not aware of anyone maintaining the xserver module. Plasma already stopped using it and I am hoping to do the same for GNOME as soon as I can.
