### ISSUE TITLE
Python nix-shell instructions not working

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#32399]
## Issue description

I read these instructions but they don't work:
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.md#load-environment-from-nix-expression
Python isn't found in the created environment.

### Steps to reproduce

Write `shell.nix` file with content:

```
with import <nixpkgs> {};
python3.withPackages (ps: [ps.numpy])
```

Activate the shell with `nix-shell` in the same directory as `shell.nix` is located. Running `python` gives error `python: command not found`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03.git.3eccd0b (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by andir** [comment]
This is a duplicate of #32372?

**Comment by jluttine** [comment]
Yes.
