### ISSUE TITLE
solvespace: Opening a file dialog crashes Solvespace on KDE Plasma

### ISSUE THREAD

**Issue by justthinkering** [NixOS/nixpkgs#32393]
## Issue description

Using any of the following file menu commands opening a file dialog window will crash Solvespace on KDE Plasma:

 - Open...
 - Save
 - Save As...
 - Export Image...
 - Export 2d View...
 - Export 2d Section...
 - Export 3d Wireframe...
 - Export Triangle Mesh...
 - Export Surfaces...
 - Import...

If Solvespace is started from a konsole, one gets the following error message after the program crash:

```
(solvespace:5311): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap
```

A similar, maybe the same, problem was already discussed in solvespace/solvespace#215, but could not be solved. In addition, other programs experience(d) similar problems in NixOS, e.g., #24943.

### Steps to reproduce

 - Install Solvespace by adding `solvespace` to the list of `environment.systemPackages` in `/etc/nixos/configuration.nix` and running `sudo nixos-rebuild switch`
 - Log in KDE Plasma
 - Open a Konsole
 - Run `solvespace`
 - Open a file dialog by, e.g., selecting File -> Save...

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 17.09.2281.b4a0c011e81 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by williammpratt** [comment]
You opened the issue originally in the right location. The author of solvespace should fix his program to report a specific error message and not crash inside one of its dependent libraries. 

This is not a NixOS problem. Solvespace is developed on a particular operating system and as a result it only is portable to that system. If you want to make the program work on NixOS, you need to fix the program. The observed behaviour does not warrant a change in NixOS.

The solvespace people refer to "Building on Linux". This seems to suggest that they think it is portable across Linux systems, while it obviously is not. Portable code runs *unmodified* and *without patches* across a wide range of *nix based systems. 

I suggest you run it inside a Docker container or inside a Debian VM until they fix it.

**Comment by grahamc** [comment]
For what it is worth, williammpratt's attitude here is not representative of the NixOS community's attitude toward other software. The user has since been blocked from the NixOS organization.

**Comment by Mic92** [comment]
Looks like `wrapGAppsHook` is missing in the derivation.

**Comment by Mic92** [comment]
I added this hook here: 9c89e52ff20fc0f569afe8126e7f442ca575a676

**Comment by orivej** [comment]
This issue was rediscovered in #32651. Backported in 3bee0c2f618df4197bc146259109adbf70a999d2.
