### ISSUE TITLE
Package request: hydrasect

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#323985]
**Project description**

Prioritize commits evaluated by Hydra when bisecting Nixpkgs

**Metadata**

* homepage URL: https://git.qyliss.net/hydrasect
* source URL: https://git.qyliss.net/hydrasect
* license: EUPL-1.2
* platforms: unix, linux, darwin, ...

**Comment by eclairevoyant** [comment]
According to https://github.com/NixOS/nixpkgs/pull/220380#issuecomment-1892855869, hydrasect  doesn't work, as https://channels.nix.gsc.io/ hasn't been updated since the 23.05 days. I'll close this out for now.

**Comment by eclairevoyant** [comment]
Feel free to PR, blt the package request would I guess still stay closed (see #425040)
