### ISSUE TITLE
Package request: paperlib

### ISSUE THREAD

**Issue by raj-magesh** [NixOS/nixpkgs#323933]
**Project description**

An open-source academic paper management tool.

**Metadata**

* homepage URL: https://paperlib.app/en/
* source URL: https://github.com/Future-Scholars/paperlib
* license: GPL-3.0 license
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ByteSudoer** [comment]
I created a PR https://github.com/NixOS/nixpkgs/pull/323958 based on this packaging request.
