### ISSUE TITLE
service.cfdyndns fails with "missing field `multiple_railguns_allowed` at line 1 column 513"

### ISSUE THREAD

**Issue by NeoTheFox** [NixOS/nixpkgs#323969]
### Describe the bug
cfdyndns seems to have an issue during normal execution.
This issue is fixed [upstream](https://github.com/nrdxp/cfdyndns/commit/a05d04660cbcba894748b7751ef2e6a85bc277a0), but requires a package version bump to v0.2.1

```
Jul 02 10:55:07 server1 systemd[1]: Started CloudFlare Dynamic DNS Client.
Jul 02 10:55:08 server1 cfdyndns-start[76304]:  INFO  cfdyndns::ip > **********
Jul 02 10:55:09 server1 cfdyndns-start[76304]: Error: error decoding response body: missing field `multiple_railguns_allowed` at line 1 column 513
Jul 02 10:55:09 server1 systemd[1]: cfdyndns.service: Main process exited, code=exited, status=1/FAILURE
Jul 02 10:55:09 server1 systemd[1]: cfdyndns.service: Failed with result 'exit-code'.
```

### Steps To Reproduce
1. Enable cfdyndns on a NixOS 24.05

### Expected behavior
The process executes and exits with no errors

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.2355.d032c1a6dfad`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(neothefox): `""`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NeoTheFox** [comment]
@stuebinm forgot to ping you

**Comment by eclairevoyant** [comment]
Root cause seems to be https://github.com/cloudflare/cloudflare-rs/issues/236

**Comment by stuebinm** [comment]
@NeoTheFox that package has a defined maintainer list. I am not one of them. Please do not ping people just because they show up in git logs if there is a well-defined list of maintainers. thanks.

**Comment by nrdxp** [comment]
I pushed an update PR that should fix it, can't merge though, my merge rights were revoked for no good reason, and can't ask for them back or I'll get permabanned (by precedent)
