### ISSUE TITLE
support autojump in zsh

### ISSUE THREAD

**Issue by cheecheeo** [NixOS/nixpkgs#3239]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/autojump/default.nix#L28 notes that this is a fixme.

**Comment by jagajaga** [comment]
cc @domenkozar @phunehehe

**Comment by phunehehe** [comment]
I use Nix as a package manager in Ubuntu, so I can't really test this. In Ubuntu, [the package](http://packages.ubuntu.com/trusty/all/autojump/filelist) drops the file in `/usr/share/autojump/autojump.zsh`, and the user is expected to change `zshrc` on their own.

**Comment by zimbatm** [comment]
I think the best approach would be to generate an `autojump-share` script that returns the path to `"$out/share/autojump"`. Then it would work in the cases where it's installed in a random profile too. As long as it's on the PATH you can use `source "$(autojump-share)/autojump.sh"`

**Comment by zimbatm** [comment]
PR ^
