### ISSUE TITLE
Package request: nicstat

### ISSUE THREAD

**Issue by juliusrickert** [NixOS/nixpkgs#324060]
**Project description**

nicstat is a tool similar to iostat, but for network interfaces.
Originally written by [Brendan Gregg](https://www.brendangregg.com/) for Solaris. Ported to [Linux by Tim Cook](https://web.archive.org/web/20160331125836/https://blogs.oracle.com/timc/entry/nicstat_the_solaris_and_linux).

**Metadata**

* homepage URL: https://nicstat.sourceforge.io/
* source URL: https://github.com/scotte/nicstat (There may be better-suited sources. This one's been updated after the SourceForge version.)
* license: Artistic License 2.0
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by juliusrickert** [comment]
Re: [Brendan Gregg presenting about nicstat](https://www.youtube.com/watch?v=FJW8nGV4jxY&t=46m21s)

**Comment by okvik** [comment]
Hey. I remember this tool from Solaris so gave it a shot. It's trivial to build if you ignore their build system and just compile it manually.

I don't want to PR and maintain this myself so here's the code. Feel free to go through the process of submitting it yourself if you so desire.

```
{ lib
, stdenv
, fetchFromGitHub
}:

stdenv.mkDerivation rec {
  pname = "nicstat";
  version = "unstable-2018-05-09";

  src = fetchFromGitHub {
    owner = "scotte";
    repo = "nicstat";
    rev = "1fbe28198b49a2062b0c928554f93db33cb288c3";
    hash = "sha256-7+11K9636dGeW0HaaH6OJF5Wy4CXYXfoaZOVfhHK6kg=";
  };

  buildPhase = ''
    runHook preBuild

    $CC -O2 nicstat.c -o nicstat

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -d "$out/bin"
    install -m 755 nicstat "$out/bin"

    install -d "$out/share/man/man1"
    install -m 644 nicstat.1 "$out/share/man/man1"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Network traffic statistics utility for Solaris and Linux";
    homepage = "https://github.com/scotte/nicstat";
    changelog = "https://github.com/scotte/nicstat/blob/${src.rev}/ChangeLog.txt";
    license = licenses.artistic2;
    maintainers = with maintainers; [ ];
    mainProgram = "nicstat";
    platforms = platforms.all;
  };
}
```

**Comment by okvik** [comment]
Ok. I added you as a maintainer.
