### ISSUE TITLE
Package request: prettier-plugin-go-template

### ISSUE THREAD

**Issue by jukremer** [NixOS/nixpkgs#324008]
**Project description**

Prettier plugin for go template files eg. for the Hugo static site generator.

This is an NPM package.

**Metadata**

* homepage URL: https://github.com/NiklasPor/prettier-plugin-go-template
* source URL: https://github.com/NiklasPor/prettier-plugin-go-template
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by janurskremer** [comment]
If I understand correctly, this should be as easy as adding `prettier-plugin-go-template` to [node-packages.json](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages.json) and running `generate.sh`. Unfortunately my hardware, and especially my internet speed, don't allow me to do this locally. Is there a way around this?
