### ISSUE TITLE
Rename Python package dns to dnspython

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#32404]
`dnspython` Python package is named `dns` in nixpkgs. Should be renamed to `dnspython` because that is the name of the package in PyPI. Keep the old name available for backwards compatibility until 18.09. Raise deprecation warning if using `dns` instead of `dnspython`.

I would have done this but I couldn't find information on how to do this kind of deprecation.

**Comment by FRidh** [comment]
Inside python-packages.nix we have no support for deprecations. Therefore, the one and only way is:

1. rename attribute from `dns` to `dnspython`
2. add alias `dns = self.dnspython`; along with a date the alias was added
3. search & replace occurrences.
4. remove the alias after the next release
