### ISSUE TITLE
Package request: nixpkgs-staging-bisecter

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#324093]
**Project description**

 minimize rebuilds when bisecting through mass rebuilds 

**Metadata**

* homepage URL: https://github.com/symphorien/nixpkgs-staging-bisecter
* source URL: https://github.com/symphorien/nixpkgs-staging-bisecter
* license: [n/a](https://github.com/symphorien/nixpkgs-staging-bisecter/issues/1)
* platforms: unix, linux, darwin, ...

**Comment by eclairevoyant** [comment]
> `nixpkgs-staging-bisecter` only supports commands starting by `nix-build`

> The first run will run the specified nix-build command with `--dry-build` on all commits in the git bisect range to determine rebuild counts, so this will be very slow

> If you change the behavior of the command during the bisection (in my example by changing `temp/vm.nix`) you must invalidate the cache by nuking `$XDG_CACHE_HOME/bisecter`.

Seems like there are a lot of footguns and problems, is this software actually useful?

**Comment by KiaraGrouwstra** [comment]
> `nixpkgs-staging-bisecter` only supports commands starting by `nix-build`

i think this one is mostly about appending `--dry-run` to commands, making it at least surmountable (as evidenced by their readme example to use this `nixos-rebuild`).

overall tho, perhaps @symphorien would be in a better position to comment here.
