### ISSUE TITLE
CrashPlan service unable to backup

### ISSUE THREAD

**Issue by xvapx** [NixOS/nixpkgs#32401]
## Issue description
CrashPlan has stopped renewing home subscriptions, [forcing crashplan for home users to either upgrade to crashplan for small business or change to another backup service][1].
Crashplan for small business seems to be incompatible with the old crashplan backup engine.
The remaining crashplan for home accounts can be active until October 23, 2018, so we should maintain the current version for anybody using it, and we should make the new version avaliable too.

[New version setup instructions][2]
[New version requeriments][3]
[New version detailed linux setup][4]

[1]:https://www.crashplan.com/en-us/consumer/nextsteps/
[2]:https://support.code42.com/Administrator/Small_Business/Get_started_with_CrashPlan_for_Small_Business/Set_up_CrashPlan_for_Small_Business
[3]:https://support.code42.com/Administrator/Small_Business/Get_started_with_CrashPlan_for_Small_Business/CrashPlan_for_Small_Business_requirements
[4]:https://support.code42.com/CrashPlan/6/Get_started/Install_the_Code42_app#Linux

### Steps to reproduce

1 - Have a CrashPlan for small business account
2 - Install the crashplan service
3 - Open the crashplan application 
4 - Be unable to insert license key

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.67, NixOS, 18.03pre-git (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.03.1947.d77e0969a78"`
 - nixpkgs: `/nix/store/gn305q15l2sbr82p06qz5ray53s5ji9n-master.tar.gz`

**Comment by xvapx** [comment]
I'll try to make a nix expression for the new version.

**Comment by xvapx** [comment]
I'm testing an expression now, it seems to be working, if anyone is interested it can be found at [this branch](https://github.com/xvapx/nixpkgs/tree/crashplanSB).
It needs to be run by a user able to write to /usr/local and a bunch of open TCP ports, which can be found [here](https://support.code42.com/Administrator/6/Planning_And_Installing/TCP_and_UDP_ports_used_by_the_Code42_platform).
I'm planning to test it a little, fix some minor details, and add some options to the service, and then i'll make a PR.

**Comment by xvapx** [comment]
@sztupi @domenkozar @jerith666

**Comment by jerith666** [comment]
Good work so far, thanks!  I'm probably not going to move to the SB version, though, so will likely not be able to help out with it on NixOS.  :(

**Comment by xvapx** [comment]
@jerith666 Thanks! Don't worry, it's already working, I believe I'll just have to fix some details ;)

**Comment by xvapx** [comment]
Already working, PR #32761
