### ISSUE TITLE
Cant upgrade to unstable nixos

### ISSUE THREAD

**Issue by Isukiipko** [NixOS/nixpkgs#324116]
### Describe the bug
So im upgrading nixos to unstable (from 24.05) and i get a bunch of errors i cant seem to fix

### Steps To Reproduce
1. add the unstable nixos channel using `sudo nix-channel --add https://channels.nixos.org/nixos-unstable nixos`
2. upgrade to the new nixos channel `nixos-rebuild switch --upgrade`

### Expected behavior
Just update and get good to go with the unstable release

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/173860581/b21a0d3e-05d5-4258-9f20-3295816d5569)

### Additional context
i had already screwed "something" (??) up which is evident in these errors from earlier when all i did was rebuild the config 
![image](https://github.com/NixOS/nixpkgs/assets/173860581/f6d6f4a6-ca6c-45c6-b21b-84a222058575)

[isukiipko@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)

---

**Comment by Isukiipko** [comment]
im considering just reinstalling nixos from scratch because i think i broke something real hard.

**Comment by purepani** [comment]
The error in the second picture is caused by a package that was broken in `nixpkgs`, mindustry. I believe a fix has been implemented and has already reached the unstable channel, if you can update the channels.

**Comment by Isukiipko** [comment]
i did do nixos-rebuild with sudo, i just forgot to add it there, for some reason, anyways, i did update the channels, and i even deleted the mindustry pkg, still, 
![image](https://github.com/NixOS/nixpkgs/assets/173860581/2c4ddec3-1df3-4455-be40-c96aa7d3fcb8)
this error keeps happening whenever i rebuild config/try to upgrade

**Comment by Isukiipko** [comment]
Update: It has been solved, idk what i did, i literally just redid the exact same commands i have already done for the past week (i have been trying to solve this issue since like 9 days) and now it just magically worked, idk what i did, i guess i should close this issue, i think the solver for this issue is that somehow i forgot typing `sudo` somewhere, thats pretty much it.

**Comment by purepani** [comment]
Mindustry should be fixed in the nixos-unstable channel now if you want to readd it.
