### ISSUE TITLE
Bruno tabs show unnecessary scrollbar on Darwin systems making the UI to look bad

### ISSUE THREAD

**Issue by alienman5k** [NixOS/nixpkgs#324176]
### Describe the bug
When a request is open in a tab a scrollbar-width: thin; is applied to the globalStyle.css. This is making the UI to look pretty ugly and it is more noticeable using dark color theme (see attached file for reference)

### Steps To Reproduce
1. Install bruno app on MacOS systems
2. Open installed bruno App
3. Change bruno to dark color scheme
4. Open or create a new Request
5. Notice how there is some white background around the tab.

### Expected behavior
The scrollbar css should not be there, even the css in bruno mentions that is intended for non darwin systems:
https://github.com/usebruno/bruno/blob/bd61e453eeba2155647bf7abe9757a43398d601f/packages/bruno-app/src/globalStyles.js#L171

### Screenshots
<img width="475" alt="Screenshot 2024-07-02 at 3 51 53 PM" src="https://github.com/NixOS/nixpkgs/assets/64812999/0e3f042f-bb36-4f9c-9d30-84add668e12c">

### Notify maintainers
@gepbird @kashw2 @lucasew @mattpolzin @water-sucks

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.4`
 - channels(imarmole): `"home-manager, nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/Users/imarmole/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alienman5k** [comment]
I've been able to fix this locally by doing a substitute, but I think it would be better to add a patch instead and remove the content on this lines:

**Comment by gepbird** [comment]
I was pretty sure it's an upstream issue until I checked it on different machines

Happens on NixOS with dwm and GNOME too:

![2024-07-03_11-31](https://github.com/NixOS/nixpkgs/assets/29818440/c1f3ebd0-a26e-46d0-94cb-eb955533bbe9)

Doesn't happen on Arch with Xfce.

**Comment by gepbird** [comment]
This issue doesn't exist with the prebuilt AppImage on NixOS.

Also, they forgot to update the package version: we are building from the v1.19.0 tag, but running the binary built from source will say it's 1.18.0 because that's in the [package.json](https://github.com/usebruno/bruno/blob/v1.19.0/packages/bruno-electron/package.json#L2). BUT running the prebuilt AppImage says displays the correct 1.19.0 version. Why is the prebuilt and the source so different?

**Comment by gepbird** [comment]
I found the cause of this issue: mismatched electron versions. We are building with electron_30, upstream is building with electron_24 (which is EOL). The latest electron where this issue wasn't introduced yet is 28, but it is also EOL.

**Comment by alienman5k** [comment]
Thanks @gepbird that means then the best course of action is to log a bug on bruno and hope they are willing to move to a newer version that is not EOF.

**Comment by gepbird** [comment]
> In the meantime, do you think is viable to have a patch to remove the css part causing the issue? I can share what I did to have my local version working (but I am not expert on Nix)

Yes, a PR with a CSS patch would be welcome, feel free to ask for help with Nix if you get stuck :)

**Comment by alienman5k** [comment]
I created the PR https://github.com/NixOS/nixpkgs/pull/324697

Let me know if something seems odd to change or fix, thanks in advance.

**Comment by jwetzell** [comment]
> This issue doesn't exist with the prebuilt AppImage on NixOS.
> 
> Also, they forgot to update the package version: we are building from the v1.19.0 tag, but running the binary built from source will say it's 1.18.0 because that's in the [package.json](https://github.com/usebruno/bruno/blob/v1.19.0/packages/bruno-electron/package.json#L2). BUT running the prebuilt AppImage displays the correct 1.19.0 version. Why is the prebuilt and the source so different?

The prebuilt binaries on the `usebruno/bruno` repo are built from a private repo and include features not present in the public repo.
