### ISSUE TITLE
`thinkfan` fails to run

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#324253]
### Describe the bug
I've set up `thinkfan` like this in my `configuration.nix`:
```
  services.thinkfan = {
    enable = true;
    levels = [
      [
        0
        0
        58
      ]
      [
        1
        56
        60
      ]
      [
        2
        57
        62
      ]
      [
        3
        58
        64
      ]
      [
        6
        59
        66
      ]
      [
        7
        60
        85
      ]
      [
        "level auto"
        80
        32767
      ]
    ];
  };
```

However, its systemd service fails to launch it:
```
● thinkfan.service - thinkfan 1.3.1
     Loaded: loaded (/etc/systemd/system/thinkfan.service; enabled; preset: enabled)
    Drop-In: /nix/store/yr8zffj823y98i9hi8kw77a5v250vrdg-system-units/thinkfan.service.d
             └─override.conf, overrides.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-07-03 09:58:15 CEST; 241ms ago
    Process: 8726 ExecStart=/nix/store/hq5b3588xsz9xy4y0ypl7ddbffgii1zj-thinkfan-1.3.1/sbin/thinkfan $THINKFAN_ARGS (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 10ms
```

When i run it in the terminal, i get:
```
thinkfan                                                                            

ERROR: /etc/thinkfan.conf: No such file or directory
```

### Steps To Reproduce
1. see above

### Additional context
I'm running it on a Lenovo IdeaPad 16

### Notify maintainers

@kallistoteles @jian-lin @kouyk @rnhmjoj @domenkozar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jian-lin** [comment]
I guess the reason is that the needed [kernel module parameters][1] fails to set.  You can verify that by `cat /sys/module/thinkpad_acpi/parameters/fan_control`.

Reboot you system and it should be fixed.

[1]: https://github.com/NixOS/nixpkgs/blob/1ac95914ce44c081e46e3c1662b351324dcf5098/nixos/modules/services/hardware/thinkfan.nix#L234

**Comment by rnhmjoj** [comment]
The configuration looks ok, but you may have to specify the sensor. Please, post the output of `journalctl -u thinkfan`.

**Comment by jian-lin** [comment]
OK, my guess is wrong then.

From the log, it seems like a user config error instead of a Nixpkgs error:  You need to specify the sensor using `services.thinkfan.sensors` instead of relying on its default value.

**Comment by rnhmjoj** [comment]
> System monitors like btop show my cpu temperature just fine, so i don't know why thinkfan can't read them

There are several interfaces for reading the temperature sensor and controlling the fans. The one thinkfan uses by default is mostly relevant to older thinkpads, newer models such as the one you have yourself use a more streamlined on. You should read the example configuration from upstream: 

https://github.com/vmatare/thinkfan/blob/master/examples/thinkfan.yaml
