### ISSUE TITLE
Package request: Suncord

### ISSUE THREAD

**Issue by Tanvir1337x** [NixOS/nixpkgs#324344]
**Project description**

Suncord is a fork of [Vencord](https://github.com/Vendicated/Vencord) with many extra plugins included.

**Metadata**

* homepage URL: https://github.com/verticalsync/Suncord
* source URL: https://github.com/verticalsync/Suncord
* license: gpl3
* platforms: linux

**Comment by TanvirOnGH** [comment]
https://github.com/NixOS/nixpkgs/pull/329818#issuecomment-2259429672
