### ISSUE TITLE
Update request: protonmail-desktop 1.03 → 1.04

### ISSUE THREAD

**Issue by freekvh** [NixOS/nixpkgs#324342]
- Package name: protonmail-desktop 
- Latest released version: 1.04

![image](https://github.com/NixOS/nixpkgs/assets/12241293/40735041-ee3d-4b1a-be42-96516eb8f4a3)

- Current version on the unstable channel:
- Current version on the stable/release channel: 1.03

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@SebTM @rsniezek ~@dotlambda~

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> * Current version on the unstable channel:

maybe check before you file an issue: https://github.com/NixOS/nixpkgs/pull/322434

**Comment by freekvh** [comment]
Apologies, I thought I had (because it is explicitly asked in the issue file ui) and didn't run into it... Anyway, thanx for maintaining this. One question thought, I was in the process of opening a PR but I could reproduce the format of your sha256 string, I used `sha256 proton-mail_1.0.4_amd64.deb` this produces a string that does not look like your `hash = "sha256-opavVpXQmA/VDZ+K/k0NJFwQHUUJhg+bUm/w8Ertopw=";` line... How do I generated that string?

**Comment by dotlambda** [comment]
> Anyway, thanx for maintaining this.

I am not. Another thing that's incorrect.

**Comment by dotlambda** [comment]
> How do I generate that string?

Make hash empty and then run `nix-build`.

**Comment by freekvh** [comment]
> > Anyway, thanx for maintaining this.
> 
> I am not. Another thing that's incorrect.

Ok, again apologies, saw you committed to 1.01 [here](https://github.com/NixOS/nixpkgs/commits/nixos-24.05/pkgs/by-name/pr/protonmail-desktop/package.nix) so assumed you were a maintainer. How can one find the official maintainers? Some people are [listed on nixpackages](https://search.nixos.org/packages?channel=24.05&show=protonmail-desktop&from=0&size=50&sort=relevance&type=packages&query=protonmail-desktop), but it's sometimes difficult to link those names to GitHub profile names.

Thanks for answering my questions!
