### ISSUE TITLE
Build wineWow by default

### ISSUE THREAD

**Issue by alpakido** [NixOS/nixpkgs#32435]
### Steps to reproduce

```
$ nix-shell -p wine --run 'env WINEARCH=win64 WINEPREFIX=$(mktemp -d) wine /dev/null'
wine: WINEARCH set to win64 but '/run/user/1000/tmp.rCVRFbzbyt' is a 32-bit installation.
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"overlay, nixos-18.03pre121925.3eccd0b11d1"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by orivej** [comment]
The default wine is the `wine32` build: https://github.com/NixOS/nixpkgs/blob/f2f524a31c14a516ab84a0819019cdd3a8d7dc07/pkgs/top-level/all-packages.nix#L19798. You may choose `wine64` and `wineWow` instead (but in my limited and possibly obsolete experience `wineWow` does not run as well as `wine32` or at all).

**Comment by yegortimoshenko** [comment]
I agree that 32-bit Wine has better compatibility, but in some cases you want 64-bit Wine prefix. The problem with `wineWow` is that complete build matrix is not available: e.g. there is no `wineUnstableWow`.

**Comment by yegortimoshenko** [comment]
Another problem is that, I think, most other distributions ship Wine with both `win32` and `win64` prefix support by default.

**Comment by jokogr** [comment]
I use `wine.override { wineBuild = "wineWow"; }` as mentioned in the [wiki](https://nixos.wiki/wiki/Wine).

**Comment by ikervagyok** [comment]
@yegortimoshenko is there any progress on this? what blocks switching the default to a `wow`-build? or just add a wine{,-staging,-unstable}-wow package to `all-packages.nix` until it can be the default? 

@jokogr  i've used this, but rebuild wine twice for a `wow`-build locally is time consuming. i believe it should be coming from the mirrors when there are more than a few people using/requesting it.

**Comment by ikervagyok** [comment]
any news?

**Comment by gnidorah** [comment]
@ikervagyok ok, opened pr https://github.com/NixOS/nixpkgs/pull/43065

**Comment by gnidorah** [comment]
@orivej
> but in my limited and possibly obsolete experience wineWow does not run as well as wine32 or at all

Many 3A games are now playabl thx to dxvk project like witcher 3 or far cry 5. And these do require winewow

**Comment by yegortimoshenko** [comment]
Still we should consider building winewow by default (and have `wine` attr point to that). I don't know of any regressions that this might cause as long as one creates a 32-bit Wine prefix.

**Comment by gnidorah** [comment]
@ikervagyok 
The first step fixed these issues
> i've used this, but rebuild wine twice for a wow-build locally is time consuming. i believe it should be coming from the mirrors when there are more than a few people using/requesting it.

> The problem with wineWow is that complete build matrix is not available: e.g. there is no wineUnstableWow

What about 
> after looking at this again, would it make sense to let winetricks also depend on config.wine.release and config.wine.build, so people using a non-default wine only depend on one version?

Just override winetricks package, its a shell script, so building is zero time:
`winetricks.override { wine = wineWowPackages.staging; }`

**Comment by ikervagyok** [comment]
@gnidorah i am already doing this, as i have a gaming environment and `config.wine.*` doesn't work in `buildFHSUserEnv`. ;)

**Comment by nh2** [comment]
Hi, I'm currently using `(wineStaging.override { wineBuild = "wineWow"; })` as explained on https://nixos.wiki/wiki/Wine but that rebuilds Wine from source on every update which takes forever.

Is this still the right way to do it?

What's the difference between this and the `wineWowPackages.staging` mentioned above?

**Comment by nh2** [comment]
`wineWowPackages.staging` seems to work just fine for me. Should the wiki be update?

**Comment by gnidorah** [comment]
@nh2 Yes, sure!

**Comment by nh2** [comment]
I've updated the wiki, writing:

```
    # support both 32- and 64-bit applications
    wineWowPackages.stable

    # support 32-bit only
    # wine

    # support 64-bit only
    # (wine.override { wineBuild = "wine64"; })

    # wine-staging (version with experimental features)
    # wineWowPackages.staging
```

Please let me know if there are remaining mistakes in it.

**Comment by enolan** [comment]
Still relevant, bot. I was bit by this today.

**Comment by acertain** [comment]
It'd be nice to be able to get `wineWowPackages.full.override { wineRelease = "staging"; }` pre-built somehow. `wineWowPackages.staging` (built by hydra) is based on `wineWowPackages.base`, which is missing stuff.

Maybe `nixpkgs.wine-staging` should be updated to be based on wineWow?

**Comment by acertain** [comment]
`wineWowPackages.stagingFull` now exists, so I think this can be closed
