### ISSUE TITLE
Plasma 6.1 system settings pages fail to load without kdePackages.kirigami 

### ISSUE THREAD

**Issue by mksafavi** [NixOS/nixpkgs#324364]
### Describe the bug
window management section of system settings app doesn't work without installing the kirigami package.
It showed a series of `Failed to load QML file` errors pointing to /kirigami/... directories. 
Installing `kdePackages.kirigami` solved the issue.
Shouldn't this be included in the Plasma default packages? 

### Screenshots
working state:
![image](https://github.com/NixOS/nixpkgs/assets/50653293/c114bd1b-7a9f-4f28-8b72-3d47ed2ee7ad)
error:
![image](https://github.com/NixOS/nixpkgs/assets/50653293/025954de-9356-4550-94f9-601ceb33ffc6)

### Notify maintainers

@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.6, NixOS, 24.11 (Vicuna), 24.11.20240624.2893f56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.0`
 - nixpkgs: `/nix/store/bi5zxc0v5g6ylygdwyqzh280sccg3ykb-source`

```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
It should definitely be included in the default Plasma install. Can you post your configuration?

**Comment by mksafavi** [comment]
> It should definitely be included in the default Plasma install. Can you post your configuration?

I think this the only kde related config that I have:
```
  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;
```
I added this to install the package:
```
users.users.mk.packages = with pkgs; [
      kdePackages.kirigami
    ];
  };
```

**Comment by K900** [comment]
That sounds wrong. How are you starting your session? Just normal SDDM? What shell are you using/

**Comment by mksafavi** [comment]
> That sounds wrong. 

Oh. Is there something wrong with my configs?

> How are you starting your session? Just normal SDDM? What shell are you using/

yeah. just normal sddm, running on wayland. my interactive shell is fish but my default shell is bash so everything is executed on bash.

**Comment by Shawn8901** [comment]
> It should definitely be included in the default Plasma install. Can you post your configuration?

Do you mean via module? If yes: it is added to the sddms extra packages https://github.com/NixOS/nixpkgs/blob/00d80d13810dbfea8ab4ed1009b09100cca86ba8/nixos/modules/services/desktop-managers/plasma6.nix#L255 , but beside that I can not ses it.

**Comment by K900** [comment]
No, it should be in the wrapper for systemsettings. I'll double check.

**Comment by FlorianFranzen** [comment]
@K900 Any update on this?

**Comment by K900** [comment]
It should be fixed upstream now.
