### ISSUE TITLE
Build Failure: Azure Data Studio

### ISSUE THREAD

**Issue by muardle** [NixOS/nixpkgs#324407]
### Describe the bug
The src URL ([here](https://github.com/NixOS/nixpkgs/blob/4166ce0a51082e3263e4d9c1448278d4feb50546/pkgs/applications/misc/azuredatastudio/default.nix#L81)) for Azure Data Studio redirects to latest version (1.48.1), not the specified version (1.44.1), leading to build failure due to hash mismatch. i.e. `https://azuredatastudio-update.azurewebsites.net/1.44.1/linux-x64/stable` redirects to `https://download.microsoft.com/download/d/6/f/d6f2673f-5240-4605-8e7d-5b6c49d188e8/azuredatastudio-linux-1.48.1.tar.gz`.

### Steps To Reproduce
1. Run `nix build nixpkgs#azuredatastudio`

### Expected behavior
Specified version of Azure Data Studio should be downloaded, verified and installed.

### Console output
```console
error: hash mismatch in fixed-output derivation '/nix/store/arswf9swq328bzxgim8z1657g6rijjas-azuredatastudio-1.44.1.tar.gz.drv':
         specified: sha256-6kEV331kt+/7/uWKZmTTkJX4P06CfxC8Ogq052qlUEg=
            got:    sha256-JDNdMy0Wk6v2pMKS+NzSbsrffaEG2IneZO+K9pBFX48=
error: 1 dependencies of derivation '/nix/store/20asqykxg7mnjm8kyyp6c3m40fp9hm3v-azuredatastudio-1.44.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l47p3rgl6nmzcc5zfpyd52id5c2q6k6w-nix-shell-env.drv' failed to build
```

### Notify maintainers

@xavierzwirtz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Locorock** [comment]
Apparently it changed again? 
I'm getting this when building it on the latest unstable:
┃ error: hash mismatch in fixed-output derivation '/nix/store/3fi8nwmlmzlzx21p7j3zz9kgwb15vgni-azureda…
┃          specified: sha256-JDNdMy0Wk6v2pMKS+NzSbsrffaEG2IneZO+K9pBFX48=
┃             got:    sha256-0LCrRUTTe8UEDgtGLvxVQL8pA5dwA6SvZEZSDILr7jo=
