### ISSUE TITLE
Move fetchFromGitHub & friends to pkgs/build-support/

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#32440]
## Issue description

fetchFromGitHub, fetchFromBitbucket, fetchFromSavannah, fetchFromGitLab, and fetchFromRepoOrCz are currently implemented directly in all-packages.nix, which is a bit messy.  It would be better for them to exist where the rest of the fetch* family of functions live, in pkgs/build-support.

**Comment by xaverdh** [comment]
I can't find the commit in which this was changed, but this seems to be fixed as of [now](https://github.com/NixOS/nixpkgs/blob/cb3c214602e25826ed53edb1bc00876903a483fd/pkgs/top-level/all-packages.nix#L306), so the issue can probably be closed.

**Comment by bhipple** [comment]
This is indeed done.
