### ISSUE TITLE
qadwaitadecorations doesn't work under Sway

### ISSUE THREAD

**Issue by dukzcry2** [NixOS/nixpkgs#324525]
### Describe the bug
Under Sway environment qadwaitadecorations plugins don't load 

### Steps To Reproduce
1. environment.systemPackages = with pkgs; [ qadwaitadecorations qadwaitadecorations-qt6 ];
2. environment.variables.QT_WAYLAND_DECORATION = "adwaita";
3. qt.enable = true;

### Expected behavior
Plugin is loaded, theme applied

### Additional context
When running `env QT_DEBUG_PLUGINS=1 <app>` there is no trace of loading wayland-decoration-client/libqadwaitadecorations.so

### Notify maintainers

@SamLukeYes

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.20240531.805a384`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/i1aw9jjgxcvyd642s12kw3iasmarwd42-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SamLukeYes** [comment]
> Plugin is loaded, theme applied

To my understanding,
- The theme adwaita-qt was deprecated without an official successor
- QAdwaitaDecorations is a successor to QGnomePlatform, but only a window decoration style without affecting Qt themes

I'm not familiar with Sway, and have no idea if window decorations are even applicable on Sway. If you're looking for an adwaita-like *theme* for Qt, QAdwaitaDecorations is probably not what you're looking for.

**Comment by dukzcry2** [comment]
@samlukeyes Thank you much for explanation!
