### ISSUE TITLE
Build failure: sky

### ISSUE THREAD

**Issue by seanrmurphy** [NixOS/nixpkgs#324612]
### Steps To Reproduce

1. `nix shell --impure nixpkgs#sky`

### Build log

```
error: builder for '/nix/store/k22yi4mnininads2qnlsg189d7z7l15l-sky-archlinux-2.1.7801-1-x86_64.pkg.tar.zst.drv' failed with exit code 1;
       last 10 log lines:
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: tel.red
       > Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: tel.red
       > Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: tel.red
       > Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: tel.red
       > error: cannot download sky-archlinux-2.1.7801-1-x86_64.pkg.tar.zst from any mirror
       For full logs, run 'nix log /nix/store/k22yi4mnininads2qnlsg189d7z7l15l-sky-archlinux-2.1.7801-1-x86_64.pkg.tar.zst.drv'.
error: 1 dependencies of derivation '/nix/store/qdzi8zbn6y6kzgbj5m1k7d93r6kqpbw3-sky-2.1.7801.drv' failed to build
```

### Additional context

- I was building the `skypilot` project, which generates an executable called `sky` and I was just checking if there is a conflict with another package

- the `sky` package downloads a binary artifact from:

https://tel.red/repos/archlinux/sky-archlinux-${version}-1-x86_64.pkg.tar.zst

See [here](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/networking/instant-messengers/sky/default.nix#L21C12-L21C89).

The domain `tel.red` has expired:

![image](https://github.com/NixOS/nixpkgs/assets/540360/c4fb8a60-ea01-4adf-98b2-488a7119b857)

### Notify maintainers

@wucke13

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
🕙 18:29:11 ✖  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.05 (Uakari), 24.05.20240619.dd457de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/2lvj8bm21ymxra61dqrc4xpzr8njgywj-source`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
#328920
