### ISSUE TITLE
py3status: Module vpn_status could not be loaded (cannot import name GLib, introspection typelib not found)

### ISSUE THREAD

**Issue by Susticle** [NixOS/nixpkgs#324796]
### Describe the bug

The vpn_status module is not executed, an error occurs (see below).

**Your py3status version**
`py3status version 3.57 (python 3.11.9) on i3`

**To Reproduce**

1. Add module `vpn_status`

2. Configure module like this:
```
vpn_status {
        cache_timeout = 10
}
```
3. Run py3status: ```py3status```

  The status bar does not display the vpn status but the word "vpn_status". Clicking on this cycles through error messages which also can be found in the log file:

```
2024-07-01 15:26:15 INFO Module `vpn_status` could not be loaded (cannot import name GLib, introspection typelib not found)
2024-07-01 15:26:15 INFO cannot import name GLib, introspection typelib not found
```
### Expected behavior
The output of the ```vpn_status``` module should be displayed.

### Additional context

- Running NixOS 24.05. There might be a connection to the update to this version but I'm not sure. (see [here](https://discourse.nixos.org/t/python-glib-introspection-fails/47391/13))
- The same error is given with the mpris module.
- Running a nix-shell ```nix-shell -p python311Packages.pygobject3``` and running `py3status` in this shell seems to work fine.
- I see the same behaviour on both machines I own.
- I'm not a pro when it comes to NixOS but I'll try to answer all questions that might pop up.

### Notify maintainers

There is no maintainer listed.

@mweinelt I saw you in the history. Maybe you can help?

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.05 (Uakari), 24.05.2310.7dca15289a1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/home/lars/.nix-defexpr/channels/nixpkgs`
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/359630
