### ISSUE TITLE
nix on gentoo: uim and gtk+

### ISSUE THREAD

**Issue by lierdakil** [NixOS/nixpkgs#32491]
Sorry if it's the wrong place to ask this question, but I'm kinda stuck here.

So, I'm using `nix` on Gentoo Linux to manage part of my environment, and I'm running into a problem regarding UIM.

So, gtk+ installed by nix isn't aware of neither uim installed via portage globally, nor uim installed into nix profile. I would believe it boils down to `immodules`/`immodules.cache` not being updated (either properly or at all).

All the usual suspects, like
```
GTK_IM_MODULE=uim
XMODIFIERS=@im=uim
```
are in place.

I tried hacking my way around that, but had no luck at all. I mean, I can add path to `im-uim.so` into `immodules.cache` by hand, but I'd have to do that manually on every other update, which I obviously want to avoid. Automating that somehow proved to be too hard for me.

Any advice is appreciated.

**Comment by Mic92** [comment]
I have never used uim. This is what nixos does when you enable the module: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/i18n/input-method/uim.nix

The module also depends on https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/i18n/input-method/default.nix

Maybe a module in [home-manager](https://github.com/rycee/home-manager/) could be written to achieve the same.

**Comment by lierdakil** [comment]
Ultimately I was able to achieve the behavior I wanted by using `xim` as the input method and uim's xim bridge, but this is obviously a rather indirect way of going about it. 

A more straightforward solution would be to run something similar to [this](https://github.com/NixOS/nixpkgs/blob/4fb4d2f407878b0e49161df001e022ea52307ab3/nixos/modules/i18n/input-method/default.nix#L14) whenever uim is updated, but I couldn't figure a way to do that, at least not without root permissions.

It's entirely possible I'm missing something obvious, since I'm just not familiar enough with Nix. FWIW, I'm managing nix packages via a custom environment, which looks something like this in my `config.nix`:
```nix
{
  packageOverrides = pkgs: with pkgs; {
    /* some overrides... */
    myPackages = buildEnv {
      name = "my-packages";
      paths = [
        uim
        /* other packages ... */
      ];
    };
  };
}
```
If there's some way to run a command that writes to `/nix/store/...-my-packages/etc` after the environment is more or less built, please let me know.

**Comment by orivej** [comment]
> If there's some way to run a command that writes to `/nix/store/...-my-packages/etc` after the environment is more or less built, please let me know.

`buildEnv` has `postBuild` argument.

**Comment by lierdakil** [comment]
Woah, that works! Thanks, @orivej! It turns out it was me being an idiot, after all.

For posterity,

```nix
{
  packageOverrides = pkgs: with pkgs; {
    myPackages = buildEnv {
      name = "my-packages";
      paths = [
        uim
        /* other packages... */
      ];
      postBuild = ''
      mkdir -p $out/etc/gtk-2.0/
      GTK_PATH=${uim}/lib/gtk-2.0/ ${gnome2.gtk.dev}/bin/gtk-query-immodules-2.0 > $out/etc/gtk-2.0/immodules.cache

      mkdir -p $out/etc/gtk-3.0/
      GTK_PATH=${uim}/lib/gtk-3.0/ ${gnome3.gtk.dev}/bin/gtk-query-immodules-3.0 > $out/etc/gtk-3.0/immodules.cache
      '';
    };
  };
}
```
Note, I assume both `gnome2.gtk` and `gnome3.gtk` are pulled in as dependencies by something. I have no idea what happens if they aren't.
