### ISSUE TITLE
gdm-fingerprint "bad jump in stack"

### ISSUE THREAD

**Issue by clayts** [NixOS/nixpkgs#324940]
### Describe the bug
Fingerprint-based authentication no longer works with gdm on my inspiron laptop, for example on the lock screen. Attempting to do so results in gdm acting as if the fingerprint is not recognised, and the gdm-fingerprint pam module producing a "bad jump in stack" error in the logs.

### Steps To Reproduce
Simply enabling gdm and fprintd is enough to cause this issue for me.

### Expected behavior
gdm recognises fingerprints correctly and allows the user to login or unlock the screen.

### Additional context
This was working fine for me until about a week ago. Reverting /etc/pam.d/gdm-fingerprint to an older state seems to solve the problem. Perhaps this commit is involved? [9d41fe6fcc4df838a56b1cfb2512b65e5e655958](https://github.com/NixOS/nixpkgs/commit/9d41fe6fcc4df838a56b1cfb2512b65e5e655958)

### Notify maintainers
@amaxine @JohnRTitor 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`
```

**Comment by JohnRTitor** [comment]
Fixed in #324347.
