### ISSUE TITLE
GNOME: switch to PipeWire and remove PulseAudio default

### ISSUE THREAD

**Issue by zh4ngx** [NixOS/nixpkgs#325003]
https://github.com/NixOS/nixpkgs/blob/e7e44e00ee9a4a1a39bf43b2515c31ef05f62209/nixos/modules/services/x11/desktop-managers/gnome.nix#L258

Per [this guide](https://nixos.wiki/wiki/PipeWire#Controlling_the_ALSA_devices) NixOS is on PipeWire now. No reason for gnome to keep using pulse.

**Comment by JohnRTitor** [comment]
CC @NixOS/gnome

**Comment by jtojnar** [comment]
> Per [this guide](https://nixos.wiki/wiki/PipeWire#Controlling_the_ALSA_devices) NixOS is on PipeWire now

I do not see how you got that from the guide.

I think switching to PipeWire is desirable but someone will need to do that. Something like https://github.com/NixOS/nixpkgs/pull/181350 would be a good first step.

**Comment by eclairevoyant** [comment]
FYI the "For 24.05 and newer" bit is referring to the `configPackages` option, not PW overall.

**Comment by jtojnar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/339209
