### ISSUE TITLE
How does fetchpatch handle exludes?

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#32504]
## Issue description
I was trying to `pkgs/development/haskell-modules/configuration-common.nix` to include a patch for #32377. But then I doscovered that `stack.yaml` is included in the patch but isn't part of the tarball uploaded to Hackage. Therefore I added it to `excludes`:
```
gitit = appendPatch super.gitit (pkgs.fetchpatch {
    name = "hoauth2-version.patch";
    url = https://github.com/jgm/gitit/pull/608.patch;
    sha256 = "0mdqa9w1p6cmli6976v4wi0sw9r4p5prkj7lzfd1877wk11c9c73";
    excludes = [ ".travis.yml" "stack.yaml" ];
  });
```
But it still didn't work.
I had a look at the `fetchpatch` function and it seems to use `filterdiff -x stack.yaml`. But if I apply this to the patch, the lines
```
diff --git a/stack.yaml b/stack.yaml
index c331e7f6..89648094 100644
```
are still present even though the real diff is suppressed.
Is there a way to make `fetchpatch` and `filterdiff` work such that I'm able to apply the filtered patch even if the file `stack.yaml` is not present?
If you think that's `filterdiff`'s fault, I'll leave a message on their mailing list.

### Steps to reproduce
You can use https://github.com/dotlambda/nixpkgs/commit/f423df9875d28e43587c9d135645e6d00037cec5 and try to build `haskellPackages.gitit`.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121925.3eccd0b11d1"`
 - channels(rschuetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dotlambda** [comment]
It miraculously started working as soon as I published this issue.

**Comment by globin** [comment]
You have to change the hash manually after adding `excludes` currently to invalidate the old one currently..

**Comment by dotlambda** [comment]
That makes sense, thank you!
