### ISSUE TITLE
Update request: PDF4QT 1.3.7 → 1.4.0

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#325092]
- Package name: PDF4QT
- Latest released version: 1.4.0
- Current version on the unstable channel: 1.3.7
- Current version on the stable/release channel: 1.3.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Aleksanaa 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
Sorry for the ignorance. Repology didn't prompt me to update. I will try to update it tomorrow.

**Comment by Thatoo** [comment]
@Aleksanaa is it possible to backport to 24.05?
