### ISSUE TITLE
minimal iso does not include git

### ISSUE THREAD

**Issue by iynaix** [NixOS/nixpkgs#325170]
### Describe the bug
The nixos minimal iso doesn't include `git`, which causes `nixos-install` to fail when fetching a remote flake source or any `fetchgit`  calls within a configuration.

### Steps To Reproduce
1. Boot minimal installation media
2. Proceed with standard installation steps until nixos-install
3. `nixos-install --flake github:user/repo#host` fails

### Expected behavior
`git` should be included in the minimal iso. For a distro that prides itself on being reproducible from text files, it feels like unnecessary friction having to `nix-shell` for something as basic and ubiquitous as git.

### Additional context
This has been brought up before in #78127, but was rejected [after a discussion in nixos-dev](https://logs.nix.samueldr.com/nixos-dev/2020-01-21#2991326). Maybe it's time to revisit this decision?

### Notify maintainers
N/A

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iblech** [comment]
To inform our decision, our git package is reproducible, so adding git to the minimal iso wouldn't render the iso less reproducible.

**Comment by bjornfor** [comment]
> Steps to reproduce the behavior:
>
> 1. Boot minimal installation media
> 2. Proceed with standard installation steps until nixos-install
> 3.  nixos-install --flake github:user/repo#host fails

Does the minimal iso enable Flakes? I would have expected that command to error out, and hint that Flakes is an experimental feature.

**Comment by iynaix** [comment]
nixos-install works with flakes out of the box, nothing else does. I'm not really sure why, but I ain't complaining :P
