### ISSUE TITLE
Update request: mesa 24.1.1 → 24.1.3

### ISSUE THREAD

**Issue by urioTV** [NixOS/nixpkgs#325129]
- Package name: Mesa
- Latest released version: 24.1.3

- Current version on the unstable channel: 24.1.1
- Current version on the stable/release channel: 24.0.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@primeos 
@vcunat 

-----

Note for maintainers: Please tag this issue in your PR.

Current version has some bugs like not being able to run Cyberpunk 2077.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
24.1.2 was on nixpkgs master, already when you opened this.  .3 will come soon.  It's not a small rebuild, so it takes a bit of time because of https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging

**Comment by JohnRTitor** [comment]
.3 is in staging, will come to `master` and nixos-unstable in its due time.

**Comment by OPNA2608** [comment]
> .3 is in staging

Can you link a PR / commit? I can only find .2 on staging / master.

**Comment by vcunat** [comment]
It wasn't there; now it is: 5a56b5dfb19b1b2db9360a3bc1dd98c7cc42b331
