### ISSUE TITLE
Are `cargoShortTarget` and `rustcTarget` wrong for wasi32?

### ISSUE THREAD

**Issue by surma** [NixOS/nixpkgs#325289]
### Describe the bug

When targeting wasi32, `cargoShortTarget` yields a string that `cargo` rejects, and `rustcTarget` yields a string that `rustc` ejects. This prevents successful cross-compilation of Rust.

### Steps To Reproduce
Here are the values for `cargoShortTarget` and `rustcTarget` when cross-compiling to `wasi32`:

```
nix-repl> :l <nixpkgs>
Added 21838 variables.

nix-repl> pkgs.pkgsCross.wasi32.stdenv.hostPlatform.rust.cargoShortTarget
"wasm32-unknown-wasi"

nix-repl> pkgs.pkgsCross.wasi32.stdenv.hostPlatform.rust.rustcTarget
"wasm32-unknown-wasi"
```

However, the accepted values for rustc’s `--target` flag are:

```console
$ rustc --print target-list
# ... snip ...
thumbv8m.main-none-eabi
thumbv8m.main-none-eabihf
wasm32-unknown-emscripten
wasm32-unknown-unknown
wasm32-wasi                   # <- !!!!
wasm32-wasi-preview1-threads
wasm64-unknown-unknown
x86_64-apple-darwin
x86_64-apple-ios
# ... snip ...
```

Cargo’s `--target` flag accepts the same values as `rustc`. 

I.e. **Both `rustc` and `cargo` will error when you pass `--target wasm32-unknown-wasi` rather than `--target wasm32-wasi`.**

### Expected behavior
It seems expected that when targeting `wasm32-unknown-wasi`, that `rustcTarget` and `cargoShortTarget` yield “wasm32-wasi".

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/aljws65b829v641ldns0w0189a3z0hg4-DarwinTools-1
  /nix/store/3bj2c590msmkn6qpc3q3z5jayki83afn-nix-info
copying path '/nix/store/aljws65b829v641ldns0w0189a3z0hg4-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/3bj2c590msmkn6qpc3q3z5jayki83afn-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.23.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oxalica** [comment]
See #146274
