### ISSUE TITLE
Tribler Unstable ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by crftbt** [NixOS/nixpkgs#325282]
### Describe the bug
The latest version of Tribler in the Unstable branch fails to start.

```
$ tribler 
INFO:__main__:Run Tribler: Namespace(torrent='', core=False, gui_test_mode=False, allow_code_injection=False, trace_exception=False, trace_debug=False, testnet=False, chant_testnet=False, trustchain_testnet=False, tunnel_testnet=False)
INFO:__main__:Root state dir: /home/craft/.Tribler
Traceback (most recent call last):
  File "/nix/store/naj9h3xwri8l8w6qvcbsww71lgz4iwxm-tribler-7.14.0/src/run_tribler.py", line 125, in <module>
    main()
  File "/nix/store/naj9h3xwri8l8w6qvcbsww71lgz4iwxm-tribler-7.14.0/src/run_tribler.py", line 117, in main
    from tribler.gui.start_gui import run_gui
  File "/nix/store/naj9h3xwri8l8w6qvcbsww71lgz4iwxm-tribler-7.14.0/src/tribler/gui/start_gui.py", line 7, in <module>
    from PyQt5.QtCore import QSettings
ModuleNotFoundError: No module named 'PyQt5.sip'
```

### Steps To Reproduce
1. Install tribler on unstable branch
2. launch tribler in terminal

### Expected behavior
Expect Tribler to launch.

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11pre647193.9f4128e00b0a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

**Comment by crftbt** [comment]
Currently failing to build. #325297 unrelated?

$ sudo nixos-rebuild switch --upgrade-all
unpacking channels...
unpacking channels...
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: pony-0.7.17 not supported for interpreter python3.12

**Comment by superherointj** [comment]
> error: pony-0.7.17 not supported for interpreter python3.12

The right way to test is to clone master repo. And do:

> nix build .#tribler

Which is certainly building:

![image](https://github.com/user-attachments/assets/16a28eef-4a12-4def-a773-cbef7682284e)

Your system configuration isn't using `master`, eventually it reaches `unstable`, etc.
