### ISSUE TITLE
chrootenv: setuid wrappers don't work

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#32536]
## Issue description

See https://github.com/NixOS/nixpkgs/pull/31182#issuecomment-350533160 (@vcunat):

> BTW (hijacking this thread a little), the steam sandbox blocks network for me. Even the old chroot binaries that used to work won't work anymore (and this PR doesn't fix it). I suspect it's triggered by newer kernel (4.14 ATM but was broken with 4.13 as well), but I haven't confirmed that yet. When I run all the sandbox except for steam command, I get
> ```
> $ ping nixos.org
> ping: socket: Operation not permitted
> ```

### Steps to reproduce

I have the same problem on Linux 4.14. To reproduce, run:

```
$ cd nixpkgs/pkgs/build-support/build-fhs-userenv
$ nix-shell -p gnumake gcc --run 'make chrootenv'
$ ./chrootenv ping nixos.org
ping: socket: Operation not permitted
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"overlay, nixos-18.03pre121925.3eccd0b11d1"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by yegortimoshenko** [comment]
I'll look into the issue. Interestingly enough, Steam (including networking) works just fine.

**Comment by yegortimoshenko** [comment]
The problem is also reproducible in Steam chrootenv via `steam-run`:

```
$ steam-run ping nixos.org
ping: socket: Operation not permitted
```

And `curl` works just fine!

```
$ ./chrootenv curl http://v.cunat.cz/
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
[...]
```

**Comment by yegortimoshenko** [comment]
OK, the problem here is that setuid wrappers don't work inside chrootenv:

```
$ ./chrootenv /run/wrappers/bin/ping ya.ru
ping: socket: Operation not permitted
```

`ping` uses raw sockets (`SOCK_RAW`) which require root setuid.

**Comment by vcunat** [comment]
`steam` doesn't work for me.  That's how I first discovered it.

**Comment by yegortimoshenko** [comment]
Interesting, it does for me. I'm on the latest nixos-unstable, w/ `linuxPackages_latest`.

Could you paste your `nix-info`?

**Comment by vcunat** [comment]
```
$ nixos-version
18.03.git.cdde22a (Impala)
$ nix-info 
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.12pre5779_cd74a55a, channels(root): "nixos-17.09pre111447.a7c8f5e419", channels(admin): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

I wondered why noone else has complained.  The kernel is 4.14.4, but I had the problem with at least some 4.13.x as well, with nixos on earlier master.

**Comment by vcunat** [comment]
This might be closer to the root cause:
> Aborting HTTP request because we received a response with a content-length over 64M and we are not streaming[2017-12-10 11:33:27] Error: Download of package (webkit_ubuntu12) failed after 0 bytes (200).

**Comment by yegortimoshenko** [comment]
Something might be broken in master but not in `nixos-unstable`, I'll build cdde22aef5c126e4474f3ecb67c32507db5a3138 and see if Steam still works (probably not).

**Comment by Mic92** [comment]
Note that newer kernels changed the behavior of setuid in user namespaces: https://lwn.net/Articles/532593/
It is now possible to apply `setuid` flags in usernamespaces.
We also set capabilities for `ping` not `setuid` since two releases.

**Comment by vcunat** [comment]
@yegortimoshenko: that's not some recent change in nixpkgs steam itself, as I can't run the old /nix/store/...steam paths that used to work before.

**Comment by yegortimoshenko** [comment]
I can't reproduce: 

> system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.15, channels(root): "overlay, nixos-18.03pre121925.3eccd0b11d1", channels(chronos): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by vcunat** [comment]
My issue seems to have been caused by me having relocated the big parts via symlinks, which stopped working at some point.  I was just confused by the behavior and console reporting errors that didn't look even remotely related.

**Comment by yegortimoshenko** [comment]
Can't reproduce anymore (and seemingly, @vcunat can't either).
