### ISSUE TITLE
package request: moonscript

### ISSUE THREAD

**Issue by edanaher** [NixOS/nixpkgs#32530]
## Issue description

In the process of trying to install pgmoon, I discovered than moonc wasn't available.  Indeed, I can't find any reference in nixpkgs to [Moonscript](https://moonscript.org/) except for an emacs mode.

I can probably package this up, but I'm shocked to find that it's not already available; it's fairly obscure, but Nix has pretty good coverage.  So I'll check to see if I'm just missing it (or if anyone has a nix expression for it handy) before spending the effort on it.

### Steps to reproduce

`cd nixpkgs; grep -Ri moonscript`

## Technical details

_Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results._

```
edanaher@kroen:~/nixpkgs$ nix-shell -p nix-info --run nix-info -m
error: undefined variable ‘nix-info’ at (string):1:66
```
Odd....
```
edanaher@kroen:~/nixpkgs$ nixos-version 
17.09pre105622.f0fac3b578 (Hummingbird)
edanaher@kroen:~/nixpkgs$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"18.03pre117327.3fe7cddc30"
```

**Comment by yegortimoshenko** [comment]
> ```
> edanaher@kroen:~/nixpkgs$ nix-shell -p nix-info --run nix-info -m
> error: undefined variable ‘nix-info’ at (string):1:66
> ```

`nix-info -m` should be in double quotes, otherwise shell interprets it as multiple arguments.
