### ISSUE TITLE
Package request: electron_31

### ISSUE THREAD

**Issue by yayayayaka** [NixOS/nixpkgs#325428]
Cross platform desktop application shell

**Metadata**

* homepage URL: https://electronjs.org/
* source URL: https://github.com/electron/electron
* license: MIT
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Windowsxd** [comment]
Any progress?

**Comment by yayayayaka** [comment]
We're working on it.

**Comment by nyabinary** [comment]
> We're working on it.

Any updates on this end?
