### ISSUE TITLE
Bumblebee not working with Steam?

### ISSUE THREAD

**Issue by therealpxc** [NixOS/nixpkgs#32550]
## Issue description
How should I tell whether Bumblebee is working correctly with the steam chroot? When I try to run a game (LISA, incidentally), I see the following in the terminal output:

```
GL Vendor    : Intel Open Source Technology Center
GL Renderer  : Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)
GL Version   : 3.0 Mesa 17.1.8
GLSL Version : 1.30
```

But by themselves, `optirun` seems to work correctly:
```
$ optirun glxinfo |grep vendor
server glx vendor string: VirtualGL
client glx vendor string: VirtualGL
OpenGL vendor string: NVIDIA Corporation
```

And so does `primusrun`:
```
$ primusron glxinfo |grep vendor
server glx vendor string: NVIDIA Corporation
client glx vendor string: primus
OpenGL vendor string: NVIDIA Corporation
```

My NixOS Bumblebee configuration is as follows:
```
  hardware.bumblebee.enable = true;
  hardware.bumblebee.group = "video";
  hardware.bumblebee.connectDisplay = true;
  boot.extraModprobeConfig = "bbswitch load_state=-1 unload_state=1";

```

The laptop is a [ThinkPad 25](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t25-type-20k7).

### Steps to reproduce
Run LISA through Steam on an NVIDIA Optimus laptop like mine and look at the terminal output.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 17.09.git.fa662e29c0cM (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - nixpkgs: `/etc/nixos/pkgsets/nixpkgs/nixpkgs`

**Comment by srhb** [comment]
Sorry, I completely missed the fact that this was a question about the chroot.

**Comment by therealpxc** [comment]
Do we have a version of Steam that doesn't use a chroot or FHSUserEnv?

**Comment by therealpxc** [comment]
I am launching Steam, and then the games from Steam. Is that the wrong way to do things?

**Comment by srhb** [comment]
No, that's just fine! Are you launching steam with primusrun or optirun? Otherwise you might want to use [this method](https://support.steampowered.com/kb_article.php?ref=6316-GJKC-7437) to selectively enable the GPU for some games -- that's what I do.

**Comment by srhb** [comment]
Oh, I almost forgot that you probably want to enable primus in the steam-chrootenv with an overlay or override. Something like:

    mySteam = pkgs.steamPackages.steam-chrootenv.override {
      withPrimus = true;
    };

**Comment by therealpxc** [comment]
I'd tried to enable it by adding `steam.primus = true;` to my Nixpkgs config, but I think that's an outdated way of doing things. It caused the `steam` package to get rebuilt, but I'm not really sure it did what I wanted.

I've tried running `steam` with both `optirun` and `primusrun`, and got the same results both times.

The selective method is a good idea; the game I've mentioned in this ticket is not one that really requires 3D acceleration. I'll give this other stuff a try when I get home.

**Comment by therealpxc** [comment]
So I took a look at the source and played around a bit, and I can see now that `withPrimus` serves to put `primusrun` into the FHS environment and that's about it. I also see one can pass an `extraPkgs` function to add other packages into the FHS environment as well. 

I've used the following in my `configuration.nix` (I have an overlay, but it's shared between hosts and my multimedia PC runs Steam on NixOS but of course has nothing to do with Optimus):

```
  nixpkgs.config.packageOverrides = superPkgs: {
    steam = superPkgs.steam.override {
      withPrimus = true;
      extraPkgs = p: with p; [
        glxinfo        # for diagnostics
        nettools       # for `hostname`, which some scripts expect
        bumblebee      # for optirun
      ];
    };
  };
```

It's now clear that `primusrun` and `optirun` can work perfectly well inside the Steam chroot, provided that they are there. But neither of them wraps the FHSUserEnv properly. I think this would be really good to add to whatever Bumblebee documentation we have.

Here are the examples of what I mean in the paragraph above. First, with `optirun`:

```
$ optirun steam-run glxinfo |grep vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Intel Open Source Technology Center
$ steam-run optirun glxinfo |grep vendor
server glx vendor string: VirtualGL
client glx vendor string: VirtualGL
OpenGL vendor string: NVIDIA Corporation
```

and for `primusrun`:
```
$ primusrun steam-run glxinfo |grep vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Intel Open Source Technology Center
$ steam-run primusrun glxinfo |grep vendor
server glx vendor string: NVIDIA Corporation
client glx vendor string: primus
OpenGL vendor string: NVIDIA Corporation

```

I think it would be good to add some documentation on this, either to the Steam section of the Nixpkgs documentation, or maybe some Bumblebee documentation for NixOS.

Thanks for pointing me in the right direction, @srhb!

**Comment by samueldr** [comment]
Assuming a similar resolution as to this:

 - https://github.com/NixOS/nixpkgs/issues/63940#issuecomment-535916425

(I wouldn't have known how to phrase it.)

Closing.
