### ISSUE TITLE
nixos/macos-builder: prevents other modules from depending on stateVersion

### ISSUE THREAD

**Issue by nbraud** [NixOS/nixpkgs#325610]
### Describe the bug
Making the `openssh` module depend on `stateVersion` causes an [evaluation failure] on ofborg.

As a result, it becomes much harder to change anything in this module — or any other used in `profiles/macos-builder.nix` — without risk of breaking things on extant installs.

[evaluation failure]: https://gist.github.com/GrahamcOfBorg/ddcd43987a6ce4cddfcdfbf24522ec39

### Steps To Reproduce
1. modify the `openssh` module to have an option's default value depend on `stateVersion` ;
   this should also work with any other module enabled in that profile, including any module which is enabled by default
2. `nix-instantiate -A darwin.linux-builder`
3. evaluation fails

### Expected behavior
It should be possible to use `stateVersion` in NixOS modules to minimize the impact of breaking change, *especially* for “core” modules which are enabled-by-default or necessary to administer many systems (such as `ssh`, `sudo`, etc.)

### Additional context
This issue is blocking for #309025.
There is no documented rationale for making `macos-builder.nix` fail when there's a dependency on `stateVersion`.

### Notify maintainers
No documented maintainer.  Semi-frequent commiters seem to be @Enzime, @Gabriella439, and @roberth.

### Metadata
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `""`
 - nixpkgs: `/run/current-system/config/3rd-party/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by roberth** [comment]
Hi @nbraud,

I'm sorry about the unclear error message. I've opened https://github.com/NixOS/nixpkgs/pull/325674 to explain it. Does that help?
