### ISSUE TITLE
Update request: vaultwarden 1.30.5 → 1.31.0

### ISSUE THREAD

**Issue by jlbribeiro** [NixOS/nixpkgs#325679]
- Package name: **vaultwarden**
- Latest released version: **1.31.0** (**[GitHub release](https://github.com/dani-garcia/vaultwarden/releases/tag/1.31.0)**, **[commit changelog](https://github.com/dani-garcia/vaultwarden/compare/1.30.5...1.31.0)**)

- Current version on the unstable channel: 1.30.5
- Current version on the stable/release channel: 1.30.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**: @dotlambda @SuperSandro2000 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kylernocturnalnerd** [comment]
Damn someone beat me to it lol

**Comment by colonelpanic8** [comment]
vaultwarden seems borken to me, at least in aarch builds. anyone else seeing this?
