### ISSUE TITLE
Plasma: libQt5Qml segfault at startup

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#32577]
## Issue description
```
[  31.062620] QQmlThread[1225]: segfault at 0 ip 00007fe3449e13ea sp 00007fe32acb5ea0 error 4 in libQt5Qml.so.5.9.1[7fe3448d4000+3e0000]
```

### Steps to reproduce
On Linux 4.14.2, NixOS, 18.03.git.8bc0bf6 specify 
`services.xserver.desktopManager.plasma5.enable = true;`

The 5.9.1 version shouldn't be used in this case. It should be using at least 5.10.x.

**Comment by bkchr** [comment]
Could you please do the following: https://github.com/NixOS/nixpkgs/issues/32072#issuecomment-347005740

@ttuegel any idea why this is still happening?

**Comment by ttuegel** [comment]
> The 5.9.1 version shouldn't be used in this case. It should be using at least 5.10.x.

I think you are confusing the Plasma version with the Qt version. You are using Qt 5.9.1.

> any idea why this is still happening?

Not yet.

**Comment by ttuegel** [comment]
@coretemp 
Could you try removing the QML cache and restarting Plasma? Qt < 5.9.2 has a severe cache invalidation bug; this could be a symptom. Run `rm -fr $HOME/.cache/*/qmlcache` to delete the cache.

**Comment by coretemp** [comment]
@ttuegel Thank you. With that line of code it works.

**Comment by ttuegel** [comment]
> After a reboot it crashes, even if I had run rm -fr $HOME/.cache/*/qmlcache before running systemctl restart display-manager.

Just making sure I understand correctly: if you remove the cache and run `nixos-rebuild switch`, then it works, but if you reboot, it crashes even if you remove the cache? That's *weird*.

Are you still using `NixOS 18.03.git.8bc0bf6`? Since you reported this issue, there has been an unstable channel update that carries Qt 5.9.3 which doesn't have the cache bug at all. I'm not sure that would help you, though, because it seems like something is happening on top of the cache bug.

**Comment by coretemp** [comment]
With this script, if I use 17.09, I can login after a reboot. When I use version 3168fcd07b79977f9c864d1fca36a241ea860f11 I am able to see a black screen with a visible mouse pointer after a reboot, but that's it (even after waiting minutes).

```
#!/bin/sh

rm -fr /home/coretemp/.cache/*/qmlcache &&
NIXPKGS=/home/coretemp/src/nixpkgs-release
VERSION=17.09 # 3168fcd07b79977f9c864d1fca36a241ea860f11 # master #17.09  # master # 17.09 # master
cd "$NIXPKGS" && 
sudo-u coretemp git checkout master && 
sudo-u coretemp git pull &&
sudo-u coretemp git checkout "$VERSION" &&
cd / && 
nixos-rebuild --show-trace -I nixpkgs=$NIXPKGS switch
```

**Comment by ttuegel** [comment]
> When I use version 3168fcd I am able to see a black screen with a visible mouse pointer after a reboot, but that's it (even after waiting minutes).

So you don't even get a login prompt?

**Comment by coretemp** [comment]
@ttuegel I do get a login prompt and I can enter username/password, but I don't get a usable session.

**Comment by coreyoconnor** [comment]
I think I've encountered the same issue. Though I did not save any log output.

1. login to plasma 5 session
2. see KDE loading screen
3. blank screen (only background color). Mouse visible. No other output.

Removing the .cache files and logging in again did restore functionality.

Interestingly, prior to this I was using Plasma 5 on a much smaller screen (1024x768) on integrated graphics while I configured a discrete GPU. Perhaps either the change in GPU or resolution is not handled by QML appropriately?

**Comment by bkchr** [comment]
@ttuegel I observed the bug again, on my PC and Laptop. It occurred after switching to Plasma 5.12 on the next reboot. Removing the directory fixed it again.

**Comment by coreyoconnor** [comment]
I suspect this, #34051 and #32170 are all the same issue.

**Comment by adisbladis** [comment]
@bkchr No I didn't experience this. Looking at my logs it seems I have never hit this issue on this machine.

**Comment by dtzWill** [comment]
Since folks seem to not be able to reproduce this reliably, here's a trivial change to `sddm.nix` that demonstrates the problem described in #35013:

https://github.com/dtzWill/nixpkgs/tree/feature/demonstrate-issue-35013

One-liner to invoke the test against this branch:

```console
NIX_PATH=nixpkgs=https://github.com/dtzWill/nixpkgs/archive/feature/demonstrate-issue-35013.tar.gz nix-build '<nixpkgs/nixos/tests/sddm.nix>' -A default
```

You've reproduced it if the test loops on OCR'ing the screen for the expected input.

The important part of the change is enabling plasma5, the other changes are just cleanup ("none" is now the default).
-----

I have not tried removing or inspecting my system's cache, but presumably the above demonstrates it's an issue beyond that?

Hopefully the above works for everyone so we can move forward resolving this issue :+1:

**Comment by dtzWill** [comment]
Misc thought while poking around: could https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/sddm.nix#L20 be made conditional? Seems like a waste to regenerate cache every boot, especially now that sddm is using 5.10 by default?

**Comment by coretemp** [comment]
@dtzWill The files are owned by nixbld1:nixbld on my machine, which means that I cannot view them easily (i.e., I assume the point of this was to share a configuration and issue with a wider audience that doesn't require the others to perform work (other than downloading the Internet)). Anyway, I copied the file as root after 5 minutes or so, and then I was able to see there was still a login screen visible, which I suspect indeed confirms what you have been seeing.

It would be better if the screenshots would all be saved as opposed to all of them being overwritten or if a VNC session would be available, so that you can see the behavior in real-time. 

It's enough to show without doubt there is an issue, though. Despite the small constructive criticism above, I think this is quite cool example of modern engineering.

**Comment by peterhoeg** [comment]
Most likely due to #177720 so tracking it there.
