### ISSUE TITLE
Build failure: floorp-unwrapped-11.14.1

### ISSUE THREAD

**Issue by rlad78** [NixOS/nixpkgs#325785]
### Steps To Reproduce

1. build floorp _or_ floorp-unwrapped

### Build log
https://gist.githubusercontent.com/rlad78/3c4f7536ea76b236ed600c57297425d5/raw/49ff286fe7837985be6fd8266172a62a77b35311/gistfile1.txt

### Additional context

The important bit at the end of the log:
```console
Running phase: profilingPhase
...
Running "pip check" to verify compatibility between the system Python and the "mach" site.
Running "pip check" to verify compatibility between the system Python and the "common" site.
Site not up-to-date reason: "/build/source/objdir/_virtualenvs/common" does not exist
Traceback (most recent call last):
  File "/build/source/./build/pgo/profileserver.py", line 19, in <module>
    from mozrunner import CLI, FirefoxRunner
  File "/build/source/testing/mozbase/mozrunner/mozrunner/__init__.py", line 6, in <module>
    import mozrunner.base
  File "/build/source/testing/mozbase/mozrunner/mozrunner/base/__init__.py", line 6, in <module>
    from .browser import BlinkRuntimeRunner, GeckoRuntimeRunner
  File "/build/source/testing/mozbase/mozrunner/mozrunner/base/browser.py", line 11, in <module>
    from ..application import DefaultContext, FirefoxContext
  File "/build/source/testing/mozbase/mozrunner/mozrunner/application.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

### Notify maintainers

@christoph-heiss

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by VincentBerthier** [comment]
Yep, got the same.

**Comment by hacker1024** [comment]
It probably needs something like https://github.com/NixOS/nixpkgs/commit/8df5e0af6e390c17e680a7ae00240ad065509a88

**Comment by christoph-heiss** [comment]
> It probably needs something like [8df5e0a](https://github.com/NixOS/nixpkgs/commit/8df5e0af6e390c17e680a7ae00240ad065509a88). For now, I've just added this overlay:
> 
> ```nix
> self: super: {
>   floorp-unwrapped = super.floorp-unwrapped.override ({ buildMozillaMach, ... }: { buildMozillaMach = args: (buildMozillaMach args).override { python3 = self.python311; }; });
> }
> ```

Yep, seems like the cause/fix. I'll send the update to v11.15.0 soon anyway and include this fix as necessary.

The package in the binary cache is fine though, so if you just pull it from there instead of rebuilding this massive thing you'd be just fine too.
