### ISSUE TITLE
Build failure: thefuck 3.32

### ISSUE THREAD

**Issue by isabelroses** [NixOS/nixpkgs#325799]
### Steps To Reproduce

1. use nixpkgs-unstable
2. build thefuck

### Build log

https://gist.github.com/isabelroses/ae50c2cd2bfc469c35efce193b541604

### Notify maintainers

@marcusramberg

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0-devpre20240707_d461cc1
System type: x86_64-linux
Additional system types:
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/isabel/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/isabel/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/isabel/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/isabel/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/isabel/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/2s37fjh67f3p4k2ga5cmn1mi173z2lld-lix-2.91.0-devpre20240707_d461cc1/share`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by isabelroses** [comment]
Seems fixable by moving to an unstable rev https://github.com/nvbn/thefuck/commit/0420442e778dd7bc53bdbdb50278eea2c207dc74

**Comment by isabelroses** [comment]
Also related https://github.com/nvbn/thefuck/issues/1444.

**Comment by mayersj1** [comment]
Same behavior here on MacOS using home-manager.

**Comment by marcusramberg** [comment]
I'm currently on vacation, so a bit limited time.  I guess our options are either pinning it to python11 until there's a release, moving to unstable or adding that commit as a patch.

**Comment by JohnRTitor** [comment]
This happened due to recent shift to Python 3.12 in Nixpkgs.

> Seems fixable by moving to an unstable rev [nvbn/thefuck@0420442](https://github.com/nvbn/thefuck/commit/0420442e778dd7bc53bdbdb50278eea2c207dc74)

Mind backporting it then?
