### ISSUE TITLE
Update request: graphite-cli 1.3.9 → 1.3.10

### ISSUE THREAD

**Issue by lukas-mertens** [NixOS/nixpkgs#325797]
- Package name: graphite-cli
- Latest released version: 1.3.10

- Current version on the unstable channel: 1.3.9
- Current version on the stable/release channel: 1.3.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@diegs 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luftmensch-luftmensch** [comment]
It seems that it was already updated in #325426
