### ISSUE TITLE
Build failure: phpactor

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#325776]
### Steps To Reproduce

1. build *phpactor*

### Build log

```
Package league/uri-parser is abandoned, you should avoid using it. No replacement was suggested.
```
https://hydra.nixos.org/build/264952873/nixlog/4

### Additional context

Started bisecting it, the bad commit is in a staging merge: 91594d11a2248ebe00f45f6b9be63fe264bb74e1.

### Notify maintainers

@patka-123 @NixOS/php 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240708.655a58a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mdevlamynck** [comment]
It seems that when installing the bash completion it fails running the binary phpactor on the line `#!/usr/bin/env php` : it doesn't find php. Building the package on `nixos-24.05` triggers the same error but apparently it does not crash `installShellCompletion`. Indeed on nixos-unstable `installShellCompletion` now checks the output : https://github.com/NixOS/nixpkgs/blob/16e401f01842c5bb2499e78c1fe227f939c0c474/pkgs/build-support/setup-hooks/install-shell-files.sh#L223. So I guess the shell completion does not work on nixos-24.05 and now generate a build failure on nixos-unstable.
