### ISSUE TITLE
fail2ban module seems broken due to Python 3.12 use

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#325884]
### Describe the bug
Seems to be related to this bug upstream which has been fixed : https://github.com/fail2ban/fail2ban/issues/3755

### Steps To Reproduce
1. Just upgrade with the fail2ban module enabled
2. Run into the issue

### Expected behavior
fail2ban service should not fail and should be running.

### Additional context

```bash
     Active: failed (Result: exit-code) since Tue 2024-07-09 17:20:57 CEST; 26min ago
   Duration: 622ms
       Docs: man:fail2ban(1)
    Process: 14006 ExecStart=/nix/store/7isxvz0z77rcrcjj5h1ahp516s6a7z7d-fail2ban-1.0.2/bin/fail2ban-server -xf>
   Main PID: 14006 (code=exited, status=255/EXCEPTION)
         IP: 0B in, 0B out
        CPU: 594ms

Jul 09 17:20:57 licht-vm systemd[1]: Started Fail2Ban Service.
Jul 09 17:20:57 licht-vm fail2ban-server[14006]: 2024-07-09 17:20:57,688 fail2ban.configreader   [14006]: WARNI>
Jul 09 17:20:57 licht-vm fail2ban-server[14006]: 2024-07-09 17:20:57,825 fail2ban                [14006]: ERROR>
Jul 09 17:20:57 licht-vm systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Jul 09 17:20:57 licht-vm systemd[1]: fail2ban.service: Failed with result 'exit-code'.
```

```
[14006]: WARNING 'allowipv6' not defined in 'Definition'. Using defaul>
-09 17:20:57,825 fail2ban                [14006]: ERROR   No module named 'asynchat'
```

### Notify maintainers

@edolstra @jasoncarr0 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.2539.49ee0e94463a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"agenix, home-manager-24.05.tar.gz, nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
see also #325803 as ref as the other is closed, ill also close this. The other issue also  contains workarounds until the mentioned pr hits unstable.
