### ISSUE TITLE
Build failure: git-cola

### ISSUE THREAD

**Issue by aucub** [NixOS/nixpkgs#325804]
### Steps To Reproduce

1. build *git-cola*

### Build log

```
error: builder for '/nix/store/7h7l4i58l833iw038n5zrvvrdrk8is70-git-cola-4.8.0.drv' failed with exit code 139;
       last 10 log lines:
       >   File "/nix/store/jrc5vsl77kzmwn9d1lm5yrzgn5rg6s12-python3.12-pluggy-1.5.0/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
       >   File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 178 in main
       >   File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/_pytest/config/__init__.py", line 206 in console_main
       >   File "/nix/store/6m4rxk7rn1ncads8mfjp55hxphzyfr2j-python3.12-pytest-8.2.2/lib/python3.12/site-packages/pytest/__main__.py", line 7 in <module>
       >   File "<frozen runpy>", line 88 in _run_code
       >   File "<frozen runpy>", line 198 in _run_module_as_main
       >
       > Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets (total: 3)
       > /nix/store/b97hl3z8rghhg383amz2fb744cla18m1-pytest-check-hook/nix-support/setup-hook: line 53:   969 Segmentation fault      (core dumped) /nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/bin/python3.12 -m pytest --ignore="qtpy/" --ignore="contrib/win32"
       > /nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 1641: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/7h7l4i58l833iw038n5zrvvrdrk8is70-git-cola-4.8.0.drv'.
```

### Notify maintainers
@bobvanderlinden

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240708.655a58a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobvanderlinden** [comment]
I'm not at a laptop for the coming weeks, so I'm not able to look into it.

A segfault inside pytest doesn't sound like something git-cola specific, but not sure. If someone else wants to take a look in the meantime, that would be much appreciated 👍👍

**Comment by Mrmaxmeier** [comment]
I've also run into this and have opened https://github.com/NixOS/nixpkgs/pull/325893.
`git-cola` runs with the updated PyQt5 version.

**Comment by dschrempf** [comment]
I link a few related issues:
- https://github.com/NixOS/nixpkgs/issues/325946

**Comment by bobvanderlinden** [comment]
I was able to workaround this problem by overriding the python version to be 3.11 instead of 3.12:

```
(pkgs.git-cola.override { python3Packages = pkgs.python311.pkgs; })
```

The proper patch (https://github.com/NixOS/nixpkgs/pull/325893) is already in staging-next (https://github.com/NixOS/nixpkgs/pull/328673), so it shouldn't be too long before it lands on master and nixpkgs-unstable.

**Comment by vcunat** [comment]
In about a week, probably.
