### ISSUE TITLE
pythonPackages."check-manifest": How to wrap it properly?

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#32589]
A Python question.

Package ``check-manifest`` relies on making shell call ``python setup.py sdist`` where python is the interpreter used to run check-manifest itself. With the current Nixpkgs Python setup, the dependencies of check-manifest are only set within the main process and do not propagate when it does shell call to Python.

``` bash
$ nix-build "<nixpkgs>" -A pythonPackages."check-manifest"
/nix/store/dqcbigpnxc2arwvqsg0932c4zbmid2bz-python2.7-check-manifest
$ result/bin/check-manifest
['/nix/store/779afy6nqwpwav76r92djbk652f0d3g0-python-2.7.14/bin/python2.7', 'setup.py', 'sdist', '-d', '/tmp/check-manifest-UD8HKT-sdist'] failed (status 1):
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import find_packages
ImportError: No module named setuptools
```

Obviously this does work in nix-shell where PYTHONPATH is patched to include all the dependencies (and it propagates in Python to shell calls by default):

```
$ nix-shell -p pythonPackages."check-manifest" --run "check-manifest"
lists of files in version control and sdist match
```

Is there better way than overriding the package to set PYTHONPATH?

``` nix
.overridePythonAttrs(old: {
  postInstall = ''
    for prog in $out/bin/*; do
      wrapProgram $prog \
        --prefix PYTHONPATH : "$PYTHONPATH" \
        --prefix PATH : "$out/bin:$PATH"
    done
  '';
});
```

**Comment by FRidh** [comment]
- Modules need to be patched to include references like absolute paths or fixed environment variables.
- Executables can instead be wrapped as that is often more convenient (although e.g. wrapPythonProgrmas does both patching and wrapping).

In this case the best solution is to replace `python setup.py sdist` with `${python.interpreter} setup.py sdist`, either with `substituteInPlace` or a proper patch file.

**Comment by datakurre** [comment]
@FRidh Thanks you.

Now I understood that this cannot be automatic because "check-manifest" is used to execute arbitrary setup.py, which could include any imports. By default it uses the current python in path, which makes it work in normal properly in normal virtualenvs.

Yet, for my I own use, I can assume that setup.py always only requires setuptools.

I assume, ``python.buildEnv`` is the correct way to create a custom interpreter with required packages to use in substituteInPlace (and possibly to add that into propagatedBuildInputs to ensure it not being garbage collected). At least this worked for me...

``` nix
let cm_python = python.withPackages(ps: [ ps.setuptools ]); in
self: super: {
  "check-manifest" = "check-manifest".overridePythonAttrs(old: {
    postPatch = ''
      substituteInPlace check_manifest.py --replace "..." "\"${cm_python.interpreter}\""
    '';
  });
}
```
