### ISSUE TITLE
SoftEther VPN is broken

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#32581]
## Issue description

```
$ nix-shell -p softether --run vpnclient
/home/chronos/.nix-profile/bin/vpnclient: line 2: /var/lib/softether/vpnclient/vpnclient: No such file or directory
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.4, NixOS, 18.03.git.cdde22a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"overlay, nixos-18.03pre121925.3eccd0b11d1"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by volth** [comment]
It seems you forget to add in the configuration

```perl
        services.softether.vpnclient.enable = true;
```

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/softether.nix#L134-L147

**Comment by gnidorah** [comment]
@yegortimoshenko Yep it should be polished to be simpler. Something like this works
```nix
services.softether = {
  enable = true;
  vpnclient.enable = true;
};
```
Next
```
# does needed stateful dir initialization, otherwise only triggered by network.target
sudo systemctl start vpnclient
```

**Comment by volth** [comment]
BTW, version 5.1 is released recently.
Maybe it is time to upgrade.
I am not using ```softether``` now, so cannot test

**Comment by gnidorah** [comment]
@volth package sole maintainer @rick68 bumped it to version 4.25 just 7 days ago. Maybe he has any plans on 5.x?

**Comment by volth** [comment]
Ah, right, 4.x is still the "stable" branch
