### ISSUE TITLE
Knot-dns backup gives error: (unknown system error)

### ISSUE THREAD

**Issue by ser** [NixOS/nixpkgs#325996]
### Describe the bug
Backup does not work correctly

### Steps To Reproduce
```
$ knotc zone-backup +backupdir /var/spool/backup
error:  (unknown system error)
```

### Expected behavior
Expected is to create a backup.

### Additional context
There is nothing more in logs, even with `debug` level enabled.

### Notify maintainers

@vcunat 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-31-generic, NixOS, 24.11 (Vicuna), 24.11pre650378.655a58a72a66`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by salzmdan** [comment]
Could you show us the output from `strace knotc zone-backup +backupdir /var/spool/backup` ?

**Comment by ser** [comment]
As far as I can understand `knotc` is a client to `knotd` only, and that error message comes from `knotd` process - and I have no idea how to strace a server process in Nix :)

**Comment by salzmdan** [comment]
You are right, but still the error can come from knotc itself.

**Comment by vcunat** [comment]
strace can attach to any process that's running already, if you have sufficient permissions
```bash
sudo strace -p "$(pidof knotd)"
```

**Comment by ser** [comment]
That's cool, I had no idea that it's possible!

```
strace: Process 3919 attached
restart_syscall(<... resuming interrupted read ...>) = 0
poll([{fd=38, events=POLLIN}], 1, 5000) = 1 ([{fd=38, revents=POLLIN}])
accept4(38, NULL, NULL, SOCK_NONBLOCK)  = 39
recvmsg(39, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\20\0\vzone-backup\21\0\0\32\0\21/var/spool/"..., iov_len=262144}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 43
sendmsg(6, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/journal/socket"}, msg_namelen=30, msg_iov=[{iov_base="PRIORITY=6", iov_len=10}, {iov_base="\n", iov_len=1}, {iov_base="MESSAGE=info: control, received "..., iov_len=53}, {iov_base="\n", iov_len=1}, {iov_base="SYSLOG_IDENTIFIER=", iov_len=18}, {iov_base="knotd", iov_len=5}, {iov_base="\n", iov_len=1}], msg_iovlen=7, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 89
newfstatat(AT_FDCWD, "/var/spool/backup", {st_mode=S_IFDIR|0755, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/lib/knot", {st_mode=S_IFDIR|0700, st_size=368, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/lib/knot/catalog/data.mdb", 0x7ffe52a401a0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/var/lib/knot/journal/data.mdb", {st_mode=S_IFREG|0660, st_size=176128, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/lib/knot/keys/data.mdb", {st_mode=S_IFREG|0660, st_size=69632, ...}, 0) = 0
mkdir("/var/spool/backup", 0770)        = -1 EEXIST (File exists)
newfstatat(AT_FDCWD, "/var/spool/backup", {st_mode=S_IFDIR|0755, st_size=0, ...}, 0) = 0
newfstatat(AT_FDCWD, "/var/spool/backup/knot_backup.label", 0x7ffe52a40050, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/var/spool/backup/lock.knot_backup", O_RDONLY|O_CREAT|O_EXCL, 0660) = -1 EROFS (Read-only file system)
sendmsg(6, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/journal/socket"}, msg_namelen=30, msg_iov=[{iov_base="PRIORITY=3", iov_len=10}, {iov_base="\n", iov_len=1}, {iov_base="MESSAGE=error: backup init faile"..., iov_len=56}, {iov_base="\n", iov_len=1}, {iov_base="SYSLOG_IDENTIFIER=", iov_len=18}, {iov_base="knotd", iov_len=5}, {iov_base="\n", iov_len=1}], msg_iovlen=7, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 92
sendmsg(39, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\20\0\vzone-backup\21\0\0\22\0\24unknown sys"..., iov_len=66}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 66
recvmsg(39, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0", iov_len=262144}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 1
close(39)                               = 0
poll([{fd=38, events=POLLIN}], 1, 5000) = 0 (Timeout)
poll([{fd=38, events=POLLIN}], 1, 5000^Cstrace: Process 3919 detached

```
So it looks that `knotd` process thinks that directory `/var/spool/backup` is read only.

**Comment by dvasek-nic** [comment]
The error EROFS means that the **file system** is mounted read only. You are right that that error isn't handled by Knot and you would get `unknown system error` only. We will fix that.

Bear in mind that the directory specified by the `+backupdir` parameter is the backup itself (a Knot backup is a directory hierarchy), it **isn't** a directory into which you want create various backups.

**Comment by ser** [comment]
I'm sorry, I don't understand the second part. According to https://www.knot-dns.cz/docs/3.3/html/operation.html#online-backup a user can specify an empty directory when he want to create a backup. As far as I can understand, some nixos policies are preventing the `knotd` process from writing into the directory which user specifies at his will. Do I understand it incorrectly?

**Comment by dvasek-nic** [comment]
Yes, you can specify any directory - either already existing (it should be empty) or a directory which is to be created. My impression was that it isn't your goal to create a single backup as `/var/spool/backup`, it just looks unusual.

**Comment by ser** [comment]
OK, so it was an empty directory which was created for a backup, sorry for confusion. 

Thank you for working on this.

**Comment by vcunat** [comment]
Ah, systemd hardening probably.  The NixOS unit specifies `ProtectSystem = "strict";` 🤦🏽 

My _personal_ opinion is that we have permissions for this, but some people just prefer to restrict everything and only add exceptions once issues are encountered.

**Comment by vcunat** [comment]
I think this is possible to override in NixOS config by
```nix
  systemd.services.knot.serviceConfig.ProtectSystem = lib.mkForce "true";
```

**Comment by ser** [comment]
> `systemd.services.knot.serviceConfig.ProtectSystem = lib.mkForce "true";`

```
$ knotc zone-backup +backupdir /var/spool/backup
OK
```

Is it the final solution, can I safely keep it nixos configuration?

**Comment by vcunat** [comment]
There's nothing unsafe about it, at least in the sense that it's "normal" not to have ProtectSystem at all.  I think I'll suggest this option for default in NixOS systemd.services.knot.

**Comment by ser** [comment]
Thank you, so my problem is solved, thank you for fantastic help!
