### ISSUE TITLE
Build failure: bpftune

### ISSUE THREAD

**Issue by HippieMitch** [NixOS/nixpkgs#325910]
### Steps To Reproduce

1. Update flake.lock and perform a nixos-rebuild.

### Build log

```
> make[1]: *** [Makefile:173: ip_frag_tuner.bpf.o] Error 1
> make[1]: *** [Makefile:173: route_table_tuner.bpf.o] Error 1
> make[1]: *** [Makefile:173: neigh_table_tuner.bpf.o] Error 1
> clang: error: unsupported option '-fzero-call-used-regs=used-gpr' for target 'bpf'
> make[1]: *** [Makefile:173: netns_tuner.bpf.o] Error 1
> make[1]: *** [Makefile:173: net_buffer_tuner.bpf.o] Error 1
> make[1]: Leaving directory '/build/source/src'
> make: *** [Makefile:41: srcdir] Error 2
> make: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/build/source/docs'

```

Full Log:
[bpftune-build-error.log](https://github.com/user-attachments/files/16147942/bpftune-build-error.log)

### Additional context
This is a clang build error related to the unsupported option '-fzero-call-used-regs=used-gpr'.  This seems to be affecting other packages as well.  Could be related to a recent change in clang.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240708.655a58a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/yzkx7gx2cn73dh3c7zg5rvgkp3yli1cd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pokon548** [comment]
Seems like it is already fixed in https://github.com/NixOS/nixpkgs/pull/325587

**Comment by HippieMitch** [comment]
Thank you.

**Comment by t4ccer** [comment]
Builds on master (54bc082f5a7219d122e74fe52c021cf59fed9d6f) for me as well
