### ISSUE TITLE
How to create UEFI-only LiveCD?

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#32590]
## Issue description
How to create ISO image without BIOS-mode? Only with UEFI-mode.

ISO will be installed on remote server.
But ISO image loaded in bios-mode.
So i can't install it with UEFI.

Hardware has support UEFI, but not load live cd in UEFI-mode.
Maybe the is no problem with hybrid booting? But with priority in BIOS?

```
Initializing machine ID from random generator.
Created "/boot/EFI".
Created "/boot/EFI/systemd".
Created "/boot/EFI/BOOT".
Created "/boot/loader".
Created "/boot/loader/entries".
Copied "/nix/store/87zlbb64md8bvsqmjggjj57q4wg13jvv-systemd-234/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/87zlbb64md8bvsqmjggjj57q4wg13jvv-systemd-234/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Not booted with EFI, skipping EFI variable setup.
setting up /etc...
```

**Comment by zsedem** [comment]
Usually you should have multiple boot options in BIOS for the Live CD, one UEFI and one legacy. Are you sure you selected an EFI boot ? Your output does not like it.

**Comment by MrSorcus** [comment]
My fault. I forgot enable UEFI in bios. Sorry and thank you.
