### ISSUE TITLE
"конструктор таблиц" in LibreOffice Base table designer window title

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#32596]
## Issue description

The window title of the LibreOffice Base (the database application in that office suite) table designer contains Russian terms, even though neither the database nor my NixOS configuration refer to the Russian language in any way.

### Steps to reproduce

In a NixOS configured for German (Switzerland)
```nix
{ config, pkgs, ... }:

{
  # ...
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "de_CH-latin1";
    defaultLocale = "de_CH.UTF-8";
  };
  # ...
  services.xserver.layout = "ch,de";
  # ...
  services.xserver.localectlFix.enable = true;
  # ...
}
```

1. Launch **LibreOfficeDev Base**
    (`/run/current-system/sw/bin/sbase` &rarr; `/nix/store/10xqxd0rh3xs3hksy4063a9agk7jgx5k-libreoffice-5.2.6.2/bin/sbase`)
2. You are greeted with the Database wizard. Click the **Fertigstellen** button. (Probably "Finish" in English.)
3. You are prompted where to store the database. Choose a location and name, e.g. `/tmp/MyDB.odb`
4. Now you see the application's main window. It's title reads
   > MyDB.odb - LibreOfficeDev Base

   ![screenshot-base](https://user-images.githubusercontent.com/97746/33885817-c46e0a10-df44-11e7-8e8b-140a346220a9.png)

   In the **Aufgaben** section, click **Tabelle in der Entwurfsansicht erstellen&hellip;**
5. This opens a new window, the table designer

#### Expected

The table designer window title is in German (and _maybe_ some English).

#### Observed

The table designer window title reads
> MyDB.odb : Tabelle1 - LibreOfficeDev Base: конструктор таблиц

![screenshot-base-table-designer](https://user-images.githubusercontent.com/97746/33885864-ec25b5c6-df44-11e7-9603-d1155fba7b00.png)

("Tabelle" is German for "[database / spreadsheet] table", so that part is fine.)

"конструктор таблиц" **seems to be Russian** and to mean "table designer".

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 17.09.2281.b4a0c011e81 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by das-g** [comment]
Complete `/etc/nixos/configuration.nix`:
```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ./localectl-fix.nix
    ];

  boot.loader.grub.device = "/dev/sda";
  boot.initrd.luks.devices = [
    {
      name = "lvm";
      device = "/dev/sda2";
    }
  ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "de_CH-latin1";
    defaultLocale = "de_CH.UTF-8";
  };

  # Set your time zone.
  time.timeZone = "Europe/Zurich";

  # List packages installed in system profile. To search by name, run:
  # $ nix-env -qaP | grep wget
  environment.systemPackages = with pkgs; [
    git
    git-cola
    nix-repl
    gnupg
    firefox
    thunderbird
    owncloud-client
    qgis
    libreoffice
    tdesktop
    pgadmin
    mysql-workbench
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.bash.enableCompletion = true;
  # programs.mtr.enable = true;
  # programs.gnupg.agent = { enable = true; enableSSHSupport = true; };

  # List services that you want to enable:
  services.postgresql.enable = true;
  services.postgresql.package = pkgs.postgresql;
  services.postgresql.authentication = pkgs.lib.mkForce ''
    # File generated by Nix config; Do not edit!

    # TYPE	DATABASE	USER    	ADDRESS 	METHOD
    local	all     	postgres	        	trust
    local	all     	all     	       		md5
    host	all     	all     	samehost	md5
    '';
  services.mysql.package = pkgs.mariadb;
  services.mysql.enable = true;

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "ch,de";
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.localectlFix.enable = true;

  # Enable touchpad support.
  # services.xserver.libinput.enable = true;

  # Enable the KDE Desktop Environment.
  # services.xserver.displayManager.sddm.enable = true;
  # services.xserver.desktopManager.plasma5.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  # users.extraUsers.guest = {
  #   isNormalUser = true;
  #   uid = 1000;
  # };
  users.extraUsers.das-g = {
    isNormalUser = true;
    home = "/home/das-g";
    description = "Raphael Das Gupta";
    extraGroups = ["wheel" "networkmanager"];
  };
  programs.vim.defaultEditor = true;
  programs.command-not-found.enable = true;

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "17.09"; # Did you read the comment?

}
```

complete `/etc/nixos/localectl-fix.nix` (see https://github.com/NixOS/nixpkgs/issues/14318#issuecomment-309250231):
```nix
{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.services.xserver;
  fcfg = cfg.localectlFix;
in {
  options.services.xserver.localectlFix = 
    { enable = mkEnableOption "Enables localectl fix.";
    };

  config = mkIf fcfg.enable {
    environment.etc = mkAssert cfg.enable ''
      X11 must be enabled for the fix to work.
    '' { "X11/xorg.conf.d/00-keyboard.conf".text = ''
          Section "InputClass"
            Identifier "Keyboard catchall"
            MatchIsKeyboard "on"
            Option "XkbRules" "base"
            Option "XkbModel" "${cfg.xkbModel}"
            Option "XkbLayout" "${cfg.layout}"
            Option "XkbOptions" "${cfg.xkbOptions}"
            Option "XkbVariant" "${cfg.xkbVariant}"
          EndSection
        '';
       };
  };
}
```

**Comment by joachifm** [comment]
@7c6f434c might know more

**Comment by 7c6f434c** [comment]
As a native Russian speaker, I confirm this caption does mean «table constructor».

As one of the people bumping LibreOffice and fixing its build, I fail to understand why this effect can happen.

(Apparently LibreOffice Base needs even more stuff from DE than LibreOffice Calc/Writer; I have just tried to reproduce and hit various Bigger Problems on a system with no DE and very minimalistic DBus «system» instance)

**Comment by orivej** [comment]
This also happens with `LANG=en_US.UTF-8`.

**Comment by luzpaz** [comment]
@das-g can you still reproduce this ?

**Comment by das-g** [comment]
> @das-g can you still reproduce this ?

No, looks fine now:

![bildschirmfoto von 2019-03-07 13-47-02](https://user-images.githubusercontent.com/97746/53957783-8e40b200-40df-11e9-9185-d8a7c701f2a9.png)

(This is with `/nix/store/nfclqk9bhp06lq4x051y8f6syf977gcl-libreoffice-6.0.7.3/bin/sbase`)

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2308.343abf7730f (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2308.343abf7730f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by das-g** [comment]
Just out of curiosity: What caused this issue and how was it fixed?
