### ISSUE TITLE
Build failure: ceph

### ISSUE THREAD

**Issue by olafkfreund** [NixOS/nixpkgs#325974]
### Steps To Reproduce

1. build ceph-18.2.1

### Build log

      > -- Found Lua: /nix/store/08zyyd4wzvsxpcfr70g8cwfa81mfqrsy-lua- 
      5.4.6/lib/liblua.so;/nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52/lib/libm.so (found suitable version "5.4.6", 
      minimum required is "5.3")
       > -- Found Cython: 0.29
       > CMake Error at /nix/store/ll2b6cslly4v30im7qk34f9y21ziiz1i-cmake-3.29.6/share/cmake-3 
      .29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
       >   Could NOT find uring (missing: URING_LIBRARIES)
       > Call Stack (most recent call first):
       >   /nix/store/ll2b6cslly4v30im7qk34f9y21ziiz1i-cmake-3.29.6/share/cmake- 
      3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
       >   cmake/modules/Finduring.cmake:11 (find_package_handle_standard_args)
       >   src/blk/CMakeLists.txt:61 (find_package)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/z4l2j2dky74andgny0lkn2shdrvccppx-ceph-18.2.1.drv'.
       error: 1 dependencies of derivation '/nix/store/pl39g7jnz6bnfzhb5d4f5nnrdydyn9cp-system-path.drv' failed to build
       error: 1 dependencies of derivation '/nix/store/ns94x5b42rcdgyf3pc60rvw8b0zs0kq0-nixos-system-razer- 
      24.11.20240708.655a58a.drv' failed to build
┏━ 1 Errors: 
 ⋮ 
┃        >   Could NOT find uring (missing: URING_LIBRARIES)
┃        > Call Stack (most recent call first):
┃        >   /nix/store/ll2b6cslly4v30im7qk34f9y21ziiz1i-cmake-3.29.6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:…
┃        >   cmake/modules/Finduring.cmake:11 (find_package_handle_standard_args)
┃        >   src/blk/CMakeLists.txt:61 (find_package)
┃        >
┃        > 
┃        > -- Configuring incomplete, errors occurred!
┃        For full logs, run 'nix log /nix/store/z4l2j2dky74andgny0lkn2shdrvccppx-ceph-18.2.1.drv'.
┣━ Dependency Graph:
┃          ┌─ ⏸ X-Restart-Triggers-dbus waiting for 1 ⚠
┃       ┌─ ⏸ unit-dbus.service
┃       │        ┌─ ⚠ ceph-18.2.1 failed with exit code 1 after ⏱ 34s in configurePhase
┃       │     ┌─ ⏸ system-path
┃       │  ┌─ ⏸ X-Restart-Triggers-polkit
┃       ├─ ⏸ unit-polkit.service
┃    ┌─ ⏸ system-units
┃ ┌─ ⏸ etc
┃ ⏸ nixos-system-razer-24.11.20240708.655a58a
┣━━━ Builds          
┗━ ∑ ⏵ 0 │ ✔ 3 │ ⏸ 16 │ ⚠ Exited after 1 build failures at 01:39:30 after 1m13s
Error: 
   0: Command exited with status Exited(1)
```

### Metadata
- system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
please search recent issues and PRs: https://github.com/NixOS/nixpkgs/issues?q=in%3Atitle+ceph

fixed in https://github.com/NixOS/nixpkgs/pull/325059
