### ISSUE TITLE
Build failure: fava

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#325945]
### Steps To Reproduce

1. build fava

### Build log

```
error: builder for '/nix/store/v7fvpx477mapij2p71pivvyh2bjblfml-fava-1.27.3.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'fava-1.27.3.dist-info/top_level.txt'
       > adding 'fava-1.27.3.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Successfully built fava-1.27.3-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for fava-1.27.3-py3-none-any.whl
       >   - beancount<3,>=2.3.5 not satisfied by version 3.0.0
       For full logs, run 'nix log /nix/store/v7fvpx477mapij2p71pivvyh2bjblfml-fava-1.27.3.drv'.
```

### Additional context

There is a newer upstream release tag but it seems to still require beancount 2.3.6

### Notify maintainers

@bhipple 

### Metadata

NixOS Unstable via flakes.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Fava is not compatible with Beancount v3 yet: https://github.com/beancount/fava/issues/1831

**Comment by lunik1** [comment]
Should beancount v2 be packaged separately? It is still recommended by beancount's README.

**Comment by kilianar** [comment]
I believe the README is not up to date with the latest release. The section discussing the various branches was added four years ago and hasn't been updated since. Martin Blais, the main author, mentioned in the [announcement of v3 on Google Groups](https://groups.google.com/g/beancount/c/iTdRuvZnE4E/m/o9V91WfgFQAJ):

> You should not use v2 anymore.

However, it might be reasonable to retain v2 temporarily to ensure fava continues to work until it supports beancount v3.

**Comment by bhipple** [comment]
Should be resolved by https://github.com/NixOS/nixpkgs/pull/327531
