### ISSUE TITLE
Package request: Kubernetes Dashboard

### ISSUE THREAD

**Issue by Darwhe** [NixOS/nixpkgs#326050]
**Project description**

Kubernetes Dashboard is a general purpose, web-based UI for Kubernetes clusters. It allows users to manage applications running in the cluster and troubleshoot them, as well as manage the cluster itself.
<img src="https://github.com/NixOS/nixpkgs/assets/175192776/ae30caf5-8f98-468e-ad92-11e9344f452f">

**Metadata**

* [homepage URL](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard)
* [source URL](https://github.com/kubernetes/dashboard)
* license: apache2.0
* platforms: unix

**Comment by Darwhe** [comment]
Since only Helm based installation is supported now, maybe it could be packaged as a [plugin](https://search.nixos.org/packages?&query=kubernetes-helm) for it to work with k3s as well.

**Comment by superherointj** [comment]
I don't understand this request. Is this a Nix package? K3s already support any Helm chart. So?

**Comment by superherointj** [comment]
ping @Darwhe

**Comment by superherointj** [comment]
Reporter hasn't followed up. And doesn't make sense.
