### ISSUE TITLE
NixOS AMI doesn't boot on c5.9xlarge instance

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#32612]
## Issue description
The NixOS 17.09 AMI fails to become accessible via ssh when booted on a c5.9xlarge instance.  even after several minutes the attempts to connect fail with "Connection refused".

### Steps to reproduce
1. Launch `ami-6f669d15` in `us-east-1` on `c5` hardware
2. Wait a few minutes
3. Attempt to login via `ssh`; note that attempts fail with `Connection refused`. Also notice that nothing is emitted to the system log. Taking a screenshot suggests we at least made it into the kernel as the last message is `Booting the kernel.`

**Comment by domenkozar** [comment]
@edolstra are we missing `ena` or something similar?

**Comment by edolstra** [comment]
This was fixed by 54da9cc944ee871517162a0918e9e3a24e17bce5 but we still need to regenerate AMIs.
