### ISSUE TITLE
fail2ban < 1.1.0 broken by python3 >= python-3.12

### ISSUE THREAD

**Issue by ppenguin** [NixOS/nixpkgs#326139]
### Steps To Reproduce
1. rebuild a `nixos` configuration that uses `fail2ban` current (i.e. < `1.1.0`) from `nixos-unstable`
2. observe it fails to start because `python-asynchat` is deprecated on `python-3.12`

### Expected behavior
Existing `nixos` configs using `fail2ban` keep working after updates.

### Additional context
Workaround forcing depend on `python-3.11` works:

```nix
  nixpkgs.overlays = [
    (final: prev: {
      fail2ban = prev.fail2ban.override {python3 = prev.python311;};
    })
  ];
```

Will probably put up a PR for bump to `fail2ban-1.1.0` to fix this properly.

### Notify maintainers

@lovek323 @edolstra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
https://github.com/NixOS/nixpkgs/issues/325803
