### ISSUE TITLE
Can't build Go binaries with CGO disabled

### ISSUE THREAD

**Issue by pierrebeaucamp** [NixOS/nixpkgs#32617]
## Issue description
I'm building a fairly large Go project using `buildGoPackage` and generated dependencies using `go2nix`. The projects builds fine. However, in an effort to build static Go binaries instead of dynamically linked ones, I disabled CGO by adding  `CGO_ENABLED=0;` to my nix expression. This breaks the build: It fails with:
```
go install net: open /nix/store/g7di6q71fzz48sryfp0y2k7il2lazi2b-go-1.9.2/share/go/pkg/linux_amd64/net.a: permission denied
```

### Steps to reproduce
Build a Go package with the following `default.nix`:
```
{ pkgs ? import <nixpkgs> {}}:

pkgs.buildGoPackage rec {
  name = "myGoPackage-${version}";
  version = "1.0.0";
  src = ./.;

  CGO_ENABLED=0;

  goPackagePath = "github.com/pierrebeaucamp/myGoPackage";
  goDeps = ./deps.nix;
}
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121925.3eccd0b11d1"`
 - channels(pierrebeaucamp): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

This is most likely caused by using `go install` in `buildGoPackage`. `go install` is known to cause problems when used in combination with `CGO_ENABLED=0`, see https://github.com/golang/go/issues/18981
I don't know why `go install` was chosen over `go build`.

**Comment by orivej** [comment]
The Go packaging was made with the expectation that each library is a separate Nix derivation, and has not been updated after only self contained Go packages were left. (`go install` would have prevented recompilation of the source.) AFAIK you can work around that with:
```
preBuild = ''
  buildFlagsArray+=(-pkgdir "$TMPDIR")
''
```

**Comment by pierrebeaucamp** [comment]
Unfortunately your preBuild hook didn't change anything and the compilation still fails with the same error. However, I was able to make _some_ progress using:

```
CGO_ENABLED=0;
buildFlags = "-pkgdir=$TMPDIR";
```

This seems to trigger a successful rebuild of the standard library (including `net`), however a lot of our dependencies are now failing. For example:

```
golang.org/x/text/unicode/norm
# golang.org/x/text/unicode/norm
go/src/golang.org/x/text/unicode/norm/normalize.go:15:2: can't find import: "golang.org/x/text/transform"
```
```
golang.org/x/crypto/bcrypt                                                                                         
# golang.org/x/crypto/bcrypt                                                                                       
go/src/golang.org/x/crypto/bcrypt/bcrypt.go:15:2: can't find import: "golang.org/x/crypto/blowfish"
```

**Comment by orivej** [comment]
I can not reproduce this. `CGO_ENABLED = 0;` and my `preBuild` are enough to statically build an application using `golang.org/x/text/unicode/norm`.

**Comment by pierrebeaucamp** [comment]
Oh, I'm so sorry. Your pre-build hook works just fine. I had I typo when adding the hook to my nix expression (I wrote `prebuild` instead of `preBuild`).

Thanks for the help, your suggestion solves all of my problems. Again, I'm very sorry that I didn't pay more attention and made you trying to reproduce my issue.
