### ISSUE TITLE
Build failure: nodejs_20

### ISSUE THREAD

**Issue by agj** [NixOS/nixpkgs#326150]
### Steps To Reproduce

I ran `nix develop --print-build-logs` with the following `flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };

  outputs = {
    self,
    nixpkgs,
  }: let
    pkgs = import nixpkgs {system = "x86_64-darwin";};
  in {
    devShell."x86_64-darwin" = pkgs.mkShell {
      buildInputs = with pkgs; [
        nodejs_20
      ];
    };
  };
}
```

### Build log

[Console output.](https://gist.github.com/agj/7282fda50c4d94751be7b47fd2bf7a9c)

### Additional context

- I'm on macOS Monterey (12.7.5).
- Once the `__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` warnings start showing, it starts looping and the process never exits.

### Notify maintainers

@cillianderoiste @aduh95

Thank you, friends, for your work and help. 🙏

### Metadata

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(Ale): `"nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tie** [comment]
>Once the \_\_ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ warnings start showing, it starts looping and the process never exits.

Looking at the logs you’ve provided (https://gist.github.com/agj/7282fda50c4d94751be7b47fd2bf7a9c), I don’t see any particular spot where it starts looping (but it does print the warning for many different files being compiled) 🧐

**Comment by aduh95** [comment]
https://github.com/NixOS/nixpkgs/pull/327653 is fixing the issue for me on aarch64 Sonoma (14.5)

**Comment by tie** [comment]
Yeah, the PR above refactors Node.js package build process (and also makes it much faster). I’ve added this issue to the list that the PR fixes to keep track of it.

**Comment by agj** [comment]
@tie The first time, when I noticed the problem, I let it run for a few hours but it was going nowhere. After that, while writing this issue, I let it run only for a bit and saved that log. Might be that it wasn't in fact looping, but it was at least taking much longer than it should.

That said, the issue is fixed now for me, so I'm closing this. Also, I tried earlier building from the above PR's branch, and it attempted to build the world for 14 hours and then failed some tests and aborted… If @tie you're interested, I can add more info in the PR.

**Comment by tie** [comment]
> Also, I tried earlier building from the above PR's branch, and it attempted to build the world for 14 hours and then failed some tests and aborted… If @tie you're interested, I can add more info in the PR.

@agj, yes, thanks, I’d appreciate your feedback on that (especially if the failing tests are in nodejs package).
