### ISSUE TITLE
Build failure: ananicy-cpp

### ISSUE THREAD

**Issue by Andy3153** [NixOS/nixpkgs#326288]
### Steps To Reproduce

1. build *ananicy-cpp*

### Build log

```
       > -- Build files have been written to: /build/source/build
       > cmake: enabled parallel building
       > cmake: enabled parallel installing
       > Running phase: buildPhase
       > build flags: -j16 SHELL=/nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash
       > [  4%] [clang] Building BPF object: ananicy_cpp
       > clang: error: unsupported option '-fzero-call-used-regs=used-gpr' for target 'bpf'
       > make[2]: *** [libananicycpp_bpf/CMakeFiles/ananicy_cpp_bpf_c.dir/build.make:78: libananicycpp_bpf/ananicy_cpp.bpf.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:125: libananicycpp_bpf/CMakeFiles/ananicy_cpp_bpf_c.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
please seaach recent issues, #325908 was resolved

**Comment by Andy3153** [comment]
god i'm so sorry, why is it that when i search for an issue prior to making one i never find one. sorry again

**Comment by eclairevoyant** [comment]
`in:title ananicy-cpp` would include recently closed issues and PRs:

https://github.com/NixOS/nixpkgs/issues?q=in%3Atitle+ananicy-cpp+
