### ISSUE TITLE
esbuild update broke rust-analyzer vs code plugin

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#326264]
### Describe the bug

There was this (automatic?) commit: https://github.com/NixOS/nixpkgs/commit/646989cee43b9a7c26934ceceae50e475bf83321

After this, the vscode rust-analyzer extension still builds but it fails at runtime, saying it can't find required modules (i.e. missing dependencies).

This is strange because it's supposed to have dependencies bundled in at build time. After a lot of hair-pulling, I narrowed this down the the bundler update (esbuild).

### Steps To Reproduce

First, check out master. I am on 212defe037698e18fc9521dfe451779a8979844c.

Then build the vscode extension and check out the part of the log where it bundes into out/main.js:

```console
$ nix -L build .#vscode-extensions.rust-lang.rust-analyzer --no-link 2>&1 | grep out/main.js
rust-analyzer> > esbuild ./src/main.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node --target=node16 --minify
rust-analyzer>   out/main.js  74.6kb
```

Note this 74.6kb figure. It is _wrong_ as we'll shortly see.

Now checkout older esbuild, i.e. right before the mentioned commit above and then build the extension again.

```console
$ git checkout 646989cee43b9a7c26934ceceae50e475bf83321^ -- pkgs/development/tools/esbuild

$ nix -L build .#vscode-extensions.rust-lang.rust-analyzer --no-link 2>&1 | grep out/main.js
rust-analyzer> > esbuild ./src/main.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node --target=node16 --minify
rust-analyzer>   out/main.js  424.1kb
```

This is what we want to see when the dependencies are actually bundled and things are working.

I haven't taken the time to bisect esbuild itself to see what caused the change, but as-is, the vscode plugin is broken. I don't know about other plugins, this is the only one I noticed.

### Notify maintainers

This was an automated commit... The maintainers on esbuild are @Lucus16 @undefined-moe and @ivan .

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by undefined-moe** [comment]
Confirmed it's related to esbuild's different bundling behavior in 0.22 (https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0220)
While 0.23 reverts this change, i think bumping version for esbuild are likely going to solve this issue.
