### ISSUE TITLE
Build failure: python3Packages.ctranslate2

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#326348]
### Steps To Reproduce

nix build nixpkgs#python3Packages.ctranslate2

### Build log

```
error: Package ‘python3.12-tensorflow-2.16.1’ in /nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source/pkgs/development/python-modules/tensorflow/bin.nix:212 is marked as broken, refusing to evaluate.
```

### Notify maintainers

 @mweinelt 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
I added a commit that disable tensorflow tests in https://github.com/NixOS/nixpkgs/pull/326337
