### ISSUE TITLE
Build failure: rocm-llvm-compiler-rt-6.0.2

### ISSUE THREAD

**Issue by Sw3d15h-F1s4** [NixOS/nixpkgs#326394]
### Steps To Reproduce

1. have a NixOS system configuration with an AMD gpu
2. enable `hardware.amdgpu.initrd.enable = true;` and `hardware.amdgpu.opencl.enable = true;`
3. have `services.xserver.videoDrivers = ["amdgpu"];`
4. `nix flake update`
5. `nixos-rebuild switch --flake <path-to-flake>`

### Build log

```
error: builder for '/nix/store/x0cc4afsyk5m2ly5lhg2mycwqbg2zarb-rocm-llvm-compiler-rt-6.0.2.drv' failed with exit code 1;
       last 10 log lines:
       > lit: /nix/store/yz7yczcfpipg2gdbs5xm9pxxl84h1pq7-python3.12-lit-18.1.7/lib/python3.12/site-packages/lit/TestingConfig.py:152: fatal: unable to parse config file '/build/source/compiler-rt/test/lit.common.cfg.py', traceback: Traceback (most recent call last):
       >   File "/nix/store/yz7yczcfpipg2gdbs5xm9pxxl84h1pq7-python3.12-lit-18.1.7/lib/python3.12/site-packages/lit/TestingConfig.py", line 140, in load_from_path
       >     exec(compile(data, path, "exec"), cfg_globals, None)
       >   File "/build/source/compiler-rt/test/lit.common.cfg.py", line 519, in <module>
       >     from distutils.version import LooseVersion
       > ModuleNotFoundError: No module named 'distutils'
       >
       > FAILED: CMakeFiles/check-runtimes /build/source/runtimes/build/CMakeFiles/check-runtimes
       > cd /build/source/runtimes/build && /nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/bin/python3.12 /nix/store/yz7yczcfpipg2gdbs5xm9pxxl84h1pq7-python3.12-lit-18.1.7/bin/.lit-wrapped -sv --show-xfail --show-unsupported /build/source/runtimes/build/compiler-rt/test/builtins/TestCases /build/source/runtimes/build/compiler-rt/test/builtins/Unit/X86_64LinuxConfig
       > ninja: build stopped: subcommand failed.
```

### Additional context

Unable to update system due to this issue. I'm no nix packaging expert, but looks to me like `distutils-extra` or `distlib` python nix packages might need to be included.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240629.2741b4b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/g83ji892byw4wd81rmb14v69yrhq408s-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CreeperCatcherD** [comment]
I have the same problem. I ran ```nix flake update``` at about 4:00 PM CST to update my flake.lock to the latest nixos unstable and after running ```sudo nixos-rebuild switch --flake .#laptop``` I got the same error that led me here. What fixed it for me was to remove ```pkgs.rocm-opencl-icd``` from my configuration.nix, so that appears to be the culprit.

**Comment by eclairevoyant** [comment]
please check for existing issues especially the pinned ones: #325907

follow https://nixpk.gs/pr-tracker.html?pr=325909 for updates
