### ISSUE TITLE
Build failure: lollypop

### ISSUE THREAD

**Issue by wrenix** [NixOS/nixpkgs#326377]
### Steps To Reproduce

1. build *lollypop*

### Build log

```
Known issues:
        - youtube-dl is unmaintained, migrate to yt-dlp, if possible
```

### Notify maintainers

@lovesegfault @zendo

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11pre651108.feb2849fdeb7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by okin** [comment]
The error message I get is:
```
error: Package ‘python3.11-youtube-dl-2021.12.17’ in /nix/store/64wk111iqis2dqcpcsa41g0x3vmp2xhi-nixos-24.05/nixos/pkgs/tools/misc/youtube-dl/default.nix:84 is marked as insecure, refusing to evaluate.
```
