### ISSUE TITLE
Update request: oxidized 0.29.1 → 0.30.1

### ISSUE THREAD

**Issue by sebvonhelsinki** [NixOS/nixpkgs#326308]
- Package name: oxidized
- Latest released version: 0.30.1

- Current version on the unstable channel: 0.29.1
- Current version on the stable/release channel: 0.29.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@nicknovitski 
@n0emis 
@vidister 
@johannwagner 
@yu-re-ka 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scriptkiddi** [comment]
https://github.com/NixOS/nixpkgs/pull/326313
