### ISSUE TITLE
Some Python 3.12 packages segfault on import PyQt5

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#326333]
Example of `pyqtgraph`:

```
$ nix-shell -p "python3.withPackages(ps: [ps.pyqtgraph ps.pyqt5])" -I nixpkgs=.
$ python3 
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyqtgraph as pg
fish: Job 1, 'python3' terminated by signal SIGSEGV (Address boundary error)
```

nixpkgs 5955103284a98d5a21f4360754b16c539e799022

@doronbehar @k0ral

-----

Other example: `curvefitgui` ([backtrace reported upstream here](https://github.com/moosepy/curvefitgui/issues/2)).

----- 

Interestingly, this doesn't fail:

```
nix shell --impure \
  --expr '
    with builtins.getFlake "nixpkgs";
    with legacyPackages.${builtins.currentSystem};
    python312.withPackages(ps: [ps.pyqt5])' \
  --command python -c 'import PyQt5.QtWidgets'
```

**Comment by doronbehar** [comment]
Hello and thanks for the report! It is a general issue of Python 3.12 and PyQt5 I also encountered with other packages, for example:

https://github.com/moosepy/curvefitgui/issues/2

I wasn't sure whether to create a bug report regarding this, as this is usually avoidable, and also PyQt5 is deprecated for a long time. What does bother me, is that I don't know if the issue happens on other Linux distributions.

I'd advice to you to switch to PyQt6.

**Comment by doronbehar** [comment]
Then you can switch to Python 3.11 .

**Comment by doronbehar** [comment]
OK apparently upstream and downstream experienced this issue as well:

https://www.riverbankcomputing.com/pipermail/pyqt/2023-October/045542.html

https://github.com/NixOS/nixpkgs/pull/325893

I will try to remember to close this issue once the above PR will reach branch `master`.

**Comment by doronbehar** [comment]
The pyqt5 update https://github.com/NixOS/nixpkgs/pull/325893 has reached branch `master`. I'm closing this.
