### ISSUE TITLE
Build failure: python3.12-dasbus-unstable

### ISSUE THREAD

**Issue by carschandler** [NixOS/nixpkgs#326465]
### Steps To Reproduce

`nix develop` on this `flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { nixpkgs, ... }:
    let
      python_package = "python3";
      pypkgs = ps: with ps; [
        dasbus
      ];
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
      py = pkgs.${python_package}.withPackages pypkgs;
    in
    {
      devShells.x86_64-linux.default = pkgs.mkShell {
        packages = [
          py
        ];
      };
    };
}
```

### Build log

https://gist.github.com/carschandler/8d67df6cc751eb06e43ae6b39ec5b53d

### Additional context

Discovered as a result of `nwg-panel`'s dependency on the package

### Notify maintainers

@moni-dz

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/5w7nhyvrgsa81h0kyifmbl6j97hvlzh5-source`
```

^^ But this is misleading because the nixpkgs version I am trying to build from is not that version since this happened after I updated my flake.lock so the new version hasn't been pinned yet for me

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nephalemsec** [comment]
Any current bypass for this in the meantime? I've tried overriding to disable tests to no avail.

**Comment by pbsds** [comment]
failure matches https://hydra.nixos.org/build/265219417, working version now builds on hydra https://hydra.nixos.org/build/267295013
