### ISSUE TITLE
firefox out of date on release-17.09; needs newer rust version

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#32655]
## Issue description

The latest version of Firefox depends on a newer version of rust, so it is not as easy as usual to bump it on the `release-17.09` channel. See #31706.

Firefox is [currently at version 56.0.2](https://github.com/NixOS/nixpkgs/blob/release-17.09/pkgs/applications/networking/browsers/firefox/packages.nix#L9) in `release-17.09`; lots of security vulnerabilities have been patched in newer versions of firefox.

**Comment by avodonosov** [comment]
Please note that in the FF 57 in the unstable channel currently fails to build on 32 bit platform - #32074.

Can we hope that stable won't break 32bit support of FireFox?

**Comment by pbogdan** [comment]
FWIW firefox has been updated to 57.0.2 in the latest release of nixos-17.09 channel.

**Comment by avodonosov** [comment]
And it supports 32 bit - I'm writing this from a 32 bit firefox 57.0.2 installed from the nixos 17.09 channel.

FWIW, nixos unstable still fails to install firefox 32 bit.

Thanks a lot - the issue seem to be resolved.

**Comment by vcunat** [comment]
Right, I had tested those, and it's in channel now.
