### ISSUE TITLE
virt-viewer: Upgrade to version 6

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#32658]
## Issue description
virt-viewer version 6 is out for a month now and adds many features.
Please update the package to version 6.
There also seems to be a bug in version 5 regarding audio passthrough via spice, which only occours in virt-viewer and not in spicy or virt-manager.

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121925.3eccd0b11d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### Device details
 - device: `20J6S0DM00 ThinkPad T470p`
 - cpu: `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`
 - gpu: `Intel Corporation Device 591b (rev 04)`

**Comment by xeji** [comment]
virt-viewer 6.0 is in nixos-unstable now.

**Comment by c0bw3b** [comment]
6.0 and even 7.0 by now
