### ISSUE TITLE
azure-cli-extensions: Expose `mkAzExtension`

### ISSUE THREAD

**Issue by haras-unicorn** [NixOS/nixpkgs#326519]
Nixpkgs can't possibly have all versions of all Azure CLI extensions in it. Maybe a user wants to install a specific version of an extension. For instance, I wanted to try and package the SSH extension but found that `mkAzExtension` is not exposed, so I ended up just copying it. I think it would be beneficial to expose [`mkAzExtension`](https://github.com/NixOS/nixpkgs/blob/feb2849fdeb70028c70d73b848214b00d324a497/pkgs/tools/admin/azure-cli/default.nix#L41) to users.

**Comment by katexochen** [comment]
Not sure what peoples expectations are regarding the stability of exposed builders, but otherwise I don't see a problem exposing this through `azure-cli.passthru`. I can do some testing and open a PR.

_Also, feel free to ping maintainers of a package for such issues, I didn't notice this issue for a month._

**Comment by haras-unicorn** [comment]
> Also, feel free to ping maintainers of a package for such issues, I didn't notice this issue for a month.

sry i forgot about that

> Not sure what peoples expectations are regarding the stability of exposed builders

imo mean same as any other builder - stuff could break if u update and if there is an update it is expected that there is a reasonable warning/error

**Comment by katexochen** [comment]
Thinking about this again, actually there isn't much magic about `mkAzExtension`. I'd assume that `.meta` isn't widely used outside of nixpkgs, so packaging an extension that isn't available in nixpkgs is as easy as 

```nix
myExt = python3.pkgs.buildPythonPackage {
    pname = "";
    version = "";
    format = "wheel";
    src = fetchurl {
        url = "";
        sha256 = "";
    }
}
```

You can just put that into `azure-cli.withExtensions [ myExt ]` and it will work as expected.

**Comment by katexochen** [comment]
Closing this as of my previous comment and no additional feedback. Please let me know if there still things unclear about adding out-of-tree extensions. :)

**Comment by haras-unicorn** [comment]
Sorry I forgot to write an answer. The extension I wanted eventually made its way to nixpkgs. Hopefully others that stumble upon this issue find your comment helpful.
