### ISSUE TITLE
[Ansel] Missing entry in gnome app launcher

### ISSUE THREAD

**Issue by JalilArfaoui** [NixOS/nixpkgs#326676]
### Describe the bug
Ansel installs well, and can be launch from console with `ansel`… but it does not appear in Gnome’s application menu, nor it cannot be find in Gnome launcher search

### Steps To Reproduce
1. add `ansel` to `systemPackages` from channel 24.05 or from unstable
2. try to launch it or to find it in applications menu

### Expected behavior
Like every other application (and Darktable), I expect to find Ansel in the application menu, launcher search, and so on

### Notify maintainers

@eclairevoyant 
@r-ryantm 
@jtojnar 
@OPNA2608 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.2411.706eef542dec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
I don't know anything about gnome, but there's definitely a desktop file in the correct spot:

```
$ ls $(nix build nixpkgs#ansel --print-out-paths --no-link)/share/applications
photos.ansel.app.desktop

$ ls $(nix build github:nixos/nixpkgs/nixos-24.05#ansel --print-out-paths --no-link)/share/applications
photos.ansel.app.desktop
```

**Comment by jtojnar** [comment]
The desktop file is broken:

```
Exec=/nix/store/my6w0pxrvqix2prc3afllp5g2pkn2l3r-ansel-0-unstable-2024-06-29//nix/store/my6w0pxrvqix2prc3afllp5g2pkn2l3r-ansel-0-unstable-2024-06-29/bin/ansel %U
TryExec=/nix/store/my6w0pxrvqix2prc3afllp5g2pkn2l3r-ansel-0-unstable-2024-06-29//nix/store/my6w0pxrvqix2prc3afllp5g2pkn2l3r-ansel-0-unstable-2024-06-29/bin/ansel
```

Sounds like the upstream build system is broken – see https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path

**Comment by eclairevoyant** [comment]
Good catch, thanks. I've sent a PR #326688
