### ISSUE TITLE
Build failure: pyload-ng

### ISSUE THREAD

**Issue by Darkflicker** [NixOS/nixpkgs#326632]
### Steps To Reproduce

1. build **pyload-ng**

### Build log

```
error:
       … while evaluating the attribute 'out.drvPath'

         at /nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source/lib/customisation.nix:351:13:

          350|             outputSpecified = true;
          351|             drvPath = assert condition; drv.${outputName}.drvPath;
             |             ^
          352|             outPath = assert condition; drv.${outputName}.outPath;

       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: js2py-0.74 not supported for interpreter python3.12
```

### Additional context

-

### Notify maintainers

@ruby0b

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ruby0b** [comment]
Thank you for notifying me, the failure is caused by the `js2py` lib not yet working on python 3.12.
Apparently the git upstream of pyload replaced it with `dukpy` which I'm packaging in #326984, so once that's done I'll get around to updating pyload (will probably have to switch to the git version since they rarely upload new releases to pypi).

For now you can override the python version as a workaround: `(pyload-ng.override { python3 = pkgs.python311; })`

**Comment by Darkflicker** [comment]
> Thank you for notifying me, the failure is caused by the `js2py` lib not yet working on python 3.12. Apparently the git upstream of pyload replaced it with `dukpy` which I'm packaging in #326984, so once that's done I'll get around to updating pyload (will probably have to switch to the git version since they rarely upload new releases to pypi).
> 
> For now you can override the python version as a workaround: `(pyload-ng.override { python3 = pkgs.python311; })`

The override works great. Thanks!
