### ISSUE TITLE
Build failure: haskellPackages.llvm-tf

### ISSUE THREAD

**Issue by thielema** [NixOS/nixpkgs#326648]
### Steps To Reproduce

In a flake I get this build error:
~~~~
       error: Package ‘llvm-tf-16.0’ in /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/development/haskell-modules/hackage-packages.nix:194254 is marked as broken, refusing to evaluate.
~~~~

However, with `NIXPKGS_ALLOW_BROKEN=1` the package `llvm-tf` can be built. Maybe it is a failure in the tests? How can I find the build logs? I try searching in:

https://hydra.nixos.org/jobset/nixpkgs/haskell-updates#tabs-jobs

I can find some packages containing “llvm” in the name, but nothing matches “llvm-tf”. :-(

### Notify maintainers

@maralorn @sternenseemann 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-22-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/thielema/.nix-defexpr/channels/nixpkgs`
```

**Comment by maralorn** [comment]
It is quite common for packages being broken at one time and getting marked broken, but we have no automatism to detect when they start working without intervention again.
The build error in question is linked in the .../broken.yaml file in nixpkgs:

```
  - llvm-tf # failure in job https://hydra.nixos.org/build/233211770 at 2023-09-02

**Comment by thielema** [comment]
On Fri, 12 Jul 2024, maralorn wrote:

> It is quite common for packages being broken at one time and getting marked broken, but we have no automatism to detect when
> they start working without intervention again.
> The build error in question is linked in the .../broken.yaml file in nixpkgs:
>
>   - llvm-tf # failure in job https://hydra.nixos.org/build/233211770 at 2023-09-02

Thanks a lot! That's quite long ago. Can we simply unbreak the package? I 
remember, the last time I tried to remove it from broken.yaml, but that 
file was automatically generated.

**Comment by maralorn** [comment]
The file is not automatically generated. Lines just get automatically added sometimes. We can just remove the line and run `maintainers/scripts/haskell/regenerate-hackage-packages.sh`

**Comment by thielema** [comment]
On Fri, 12 Jul 2024, maralorn wrote:

> The file is not automatically generated. Lines just get automatically added sometimes.

aha, although confusing

> We can just remove the line and run 
> maintainers/scripts/haskell/regenerate-hackage-packages.sh

yes, please

**Comment by maralorn** [comment]
Done in f55d58cfa1c8
