### ISSUE TITLE
Ardour won't build on the latest unstable.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#32676]
## Issue description

During the upgrade from ``18.03pre121925.3eccd0b11d1`` to ``18.03pre122666.afe9649210c``, ardour refused to build, giving the error ``libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9``, see https://hastebin.com/uronupeqan.coffeescript

### Steps to reproduce

install ardour in ``18.03pre122666.afe9649210c``

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.3, NixOS, 18.03pre122666.afe9649210c (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre122666.afe9649210c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

cc @cillianderoiste @fps

**Comment by orivej** [comment]
This was fixed in 04fcbefd81d6459675c84ce857e36dcb5f464057. You may check if a package is known to be broken or fixed at e.g. https://hydra.nixos.org/jobset/nixpkgs/trunk/jobs-tab?filter=ardour

**Comment by magnetophon** [comment]
@orivej Thanks a lot!
