### ISSUE TITLE
yewtube: runtime failure

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#326862]
### Describe the bug

```
Traceback (most recent call last):
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/qr6xq92s3yill44gxj2wabcdfp9ir0l8-yewtube-2.10.5/lib/python3.12/site-packages/mps_youtube/streams.py", line 196, in _preload
    get_size(ytid, stream['url'], preloading=True)
                   ~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

when selecting a video

### Steps To Reproduce
1. run `yt`
2. search for a video (`/searchstring`)
3. type in 1 and press enter

### Expected behavior
no error

### Screenshots
n/a

### Additional context
seems related to the python 3.12 changes, but I didn't bisect

### Notify maintainers

@fgaz @k0ral 

### Metadata
tested on current master (4c68bf5473a8e87ffd94322cc3e79a449311325b)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
It was working fine with `mpv` (which also uses `yt-dlp` in my setup).
In any case... it seems to be working now, sorry for the noise.

**Comment by eclairevoyant** [comment]
The ghosts have returned...

Here's an example:
1. search `user bobbialthoff`
2. play the first video

yewtube errors at both steps

`mpv https://www.youtube.com/watch?v=_hQWw95rjm8` and `yt-dlp https://www.youtube.com/watch?v=_hQWw95rjm8` work fine

**Comment by fgaz** [comment]
The upstream issue seems to be https://github.com/mps-youtube/yewtube/issues/1280

**Comment by eclairevoyant** [comment]
In that I surmise they're not using yt-dlp at all, and trying to roll their own extraction mechanism, in which case we'd eventually have to drop the package.

**Comment by fgaz** [comment]
It does use yt-dlp. However I think the issue is the [youtube-search-python](https://github.com/alexmercerind/youtube-search-python) dependency, which is sadly [unmaintained](https://github.com/alexmercerind/youtube-search-python/issues/189). Yewtube can't get to the point where it calls yt-dlp because it fails at the search stage.

**Comment by fgaz** [comment]
:O it started working again on its own
