### ISSUE TITLE
steam fails to start (on 17.09)

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#32687]
## Issue description

This may well be a user error on my part but suddenly steam fails to start on my system with the errors below. AFAICT no system configuration changes occurred between last successful run of steam and the one producing the errors.
I would appreciate any help on how to debug this further.

```
cp: cannot create regular file '/host/shared/.local/share/Steam/bootstrap.tar.xz': Permission denied
Running Steam on nixos 17.09.2241.f9390d652f9 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Pins potentially out-of-date, rebuilding...
mkdir: cannot create directory ‘/nix/store/m4q3f0r3rgd6f8qwxhfx31hzbwifkjs8-steam-fhs/steamrt/pinned_libs_32’: Read-only file system
mkdir: cannot create directory ‘/nix/store/m4q3f0r3rgd6f8qwxhfx31hzbwifkjs8-steam-fhs/steamrt/pinned_libs_64’: Read-only file system
/host/shared/.local/share/Steam/steam.sh: line 874: /steamrt/run.sh: No such file or directory
Error: You are missing the following 32-bit libraries, and Steam may not run:
libgobject-2.0.so.0
libglib-2.0.so.0
libgio-2.0.so.0
libgtk-x11-2.0.so.0
libpulse.so.0
libgdk_pixbuf-2.0.so.0
libva.so.1
libbz2.so.1.0
libz.so.1
libvdpau.so.1
libva.so.1
libva-x11.so.1
Error:
You are missing the following 32-bit libraries, and Steam may not run:
libgobject-2.0.so.0
libglib-2.0.so.0
libgio-2.0.so.0
libgtk-x11-2.0.so.0
libpulse.so.0
libgdk_pixbuf-2.0.so.0
libva.so.1
libbz2.so.1.0
libz.so.1
libvdpau.so.1
libva.so.1
libva-x11.so.1
Press enter to continue: 
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
Failed to load steamui.so - dlerror(): libgobject-2.0.so.0: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
[2017-12-14 23:43:50] Startup - updater built Dec 12 2017 21:27:37
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-12-14 23:43:50] Checking for update on startup
[2017-12-14 23:43:50] Checking for available updates...
[2017-12-14 23:43:51] Download skipped: /client/steam_client_ubuntu12 version 1513197415, installed version 1513197415
[2017-12-14 23:43:51] Nothing to do
[2017-12-14 23:43:51] Verifying installation...
[2017-12-14 23:43:51] Performing checksum verification of executable files
[2017-12-14 23:43:52] Verification complete
[2017-12-14 23:43:54] Shutdown
```
### Steps to reproduce

```
$ steam
````

## Technical details

- system: `"x86_64-linux"`        
 - host os: `Linux 4.13.16, NixOS, 17.09.2241.f9390d652f9 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2356.cb751f9b1c3, unstable-18.03pre120540.b8f7027360"`
 - channels(pbogdan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by yegortimoshenko** [comment]
See [10.6.2. How to play](https://nixos.org/nixpkgs/manual/#sec-steam-play) in Nixpkgs manual.

**Comment by ldesgoui** [comment]
I'm running into the same issue after the December 13th Steam Client update: http://store.steampowered.com/news/35534/

**Comment by yegortimoshenko** [comment]
I see.  I would guess it's an instance of #31384 and #31512 has to be backported to 17.09.

**Comment by jugaltheshah** [comment]
I'm having this issue as of just now. Worked fine earlier in the day. I believe it's the same issue. Here's what I see when running from console:

Manjaro steam native configuration found!
Running Steam on manjarolinux 17.1pre3 64-bit
STEAM_RUNTIME is disabled by the user
Error: You are missing the following 32-bit libraries, and Steam may not run:
libvdpau.so.1
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
Failed to load steamui.so - dlerror(): libvdpau.so.1: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1513197415)
Installing breakpad exception handler for appid(steam)/version(1513197415)
[2017-12-14 22:52:49] Startup - updater built Dec 12 2017 21:27:37
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-12-14 22:52:49] Checking for update on startup
[2017-12-14 22:52:49] Checking for available updates...
[2017-12-14 22:52:49] Download skipped: /client/steam_client_ubuntu12 version 1513197415, installed version 1513197415
[2017-12-14 22:52:49] Nothing to do
[2017-12-14 22:52:49] Verifying installation...
[2017-12-14 22:52:49] Performing checksum verification of executable files
[2017-12-14 22:52:50] Verification complete
[2017-12-14 22:53:00] Shutdown

**Comment by ldesgoui** [comment]
Thanks! Installing steam from the PR's branch did work out just fine

**Comment by yegortimoshenko** [comment]
Could someone with commit access backport #31512? Normally @abbradar would do that for Steam, but he's in hospital (get well!).

/cc @Mic92 @grahamc @orivej

**Comment by yegortimoshenko** [comment]
Fix is backported, this now can be closed.

**Comment by yegortimoshenko** [comment]
@pbogdan I've made another attempt, now in `release-17.09` branch. Please try it out.

**Comment by pbogdan** [comment]
@yegortimoshenko thank you! Steam now starts and trying few games all of them appear to be working well so far.

I will go ahead and close this ticket now, thanks again for your help and the fix.

PS. I hacked around empty web views (like the store) by adding `nss` and `nspr` to ` overridePkgs` in https://github.com/NixOS/nixpkgs/blob/15d3d68a5ea819dd82784a9a44cfe26ed5eb74cd/pkgs/games/steam/runtime-wrapped.nix#L83 but I'm not sure if that's the right way to do it. But I suppose that's a different issue.

**Comment by yegortimoshenko** [comment]
@pbogdan I'll open a pull request with this `nss` and `nspr`. Thank you!
