### ISSUE TITLE
Package request: osxphotos

### ISSUE THREAD

**Issue by stv0g** [NixOS/nixpkgs#326869]
**Project description**

Python app to work with pictures and associated metadata from Apple Photos on macOS. Also includes a package to provide programmatic access to the Photos library, pictures, and metadata.

**Metadata**

* homepage URL: 
* source URL: https://github.com/RhetTbull/osxphotos
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
This was the most complex package i ever tried to write :sweat_smile: 
- #326978
