### ISSUE TITLE
Update request: flatpak 1.14.6 → 1.15.8

### ISSUE THREAD

**Issue by devurandom** [NixOS/nixpkgs#326906]
- Package name: flatpak
- Latest released version: 1.15.8
  - I am particularly interested in this fix that resolves symlink issues: https://github.com/flatpak/flatpak/pull/5749

- Current version on the unstable channel: 1.14.6
- Current version on the stable/release channel: 1.14.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
  - There is https://github.com/NixOS/nixpkgs/pull/322485, but that updates only to 1.14.8.

**Notify maintainers**

@getchoo 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Those are pre-releases. And we do not use the vendored bubblewrap anyway – it will need to be updated separately.
