### ISSUE TITLE
Build failure: emojione

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#326959]
### Steps To Reproduce

1. `nix-build -A emojione` on current master, 9665639708ae46177c4b71a3550cf43d577c6c46

### Build log

https://gist.github.com/l0b0/bf338fbde6ed5cb53ebed4dd9f1260d1

### Notify maintainers

@abbradar

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9, NixOS, 24.11 (Vicuna), 24.11pre652179.7e7c39ea35c5`
- multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by l0b0** [comment]
I wouldn't remind it being removed, if there's a useful alternative. I don't know of a good way to get complete coverage over emojis, and so far I've installed emojione, nerdfonts, noto-fonts, stix-two, and twemoji-color-font, none of which seem to cover any of the other emoji code points completely.

**Comment by LuNeder** [comment]
Potentially related: #325909 and #253751

Potential fix: https://github.com/NixOS/nixpkgs/pull/325909/files
