### ISSUE TITLE
Build failure: djlint

### ISSUE THREAD

**Issue by hackeryarn** [NixOS/nixpkgs#326925]
### Steps To Reproduce

1. build *djlint*

### Build log

```
...
OK
/build/source
Finished executing pypaBuildPhase
Running phase: pythonRuntimeDepsCheckHook
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for djlint-1.34.1-py3-none-any.whl
  - regex<2024.0.0,>=2023.0.0 not satisfied by version 2024.5.15
```

### Additional context

Happy to help out with this. I am just unsure of the best practice to downgrade a single package like needed.

### Notify maintainers

@traxys 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by traxys** [comment]
I believe this has been fixed in #325651
