### ISSUE TITLE
Build failure: xsser (nose-1.3.7 not supported for interpreter python3.12)

### ISSUE THREAD

**Issue by D3vil0p3r** [NixOS/nixpkgs#326943]
### Describe the bug
xsser installation returns the following error:
```
...
error: nose-1.3.7 not supported for interpreter python3.12
```

### Notify maintainers

@emilytrau 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, Athena OS, 24.11 (Vicuna), 24.11pre652179.7e7c39ea35c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos, nixpkgs"`
 - nixpkgs: `/home/athena/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/325968
