### ISSUE TITLE
Rust build support doesn't use `NIX_LDFLAGS` in link flags

### ISSUE THREAD

**Issue by kira-bruneau** [NixOS/nixpkgs#326944]
### Describe the bug

I was trying to use `NIX_LDFLAGS` instead of `LD_LIBRARY_PATH` in ukmm to link extra runtime libraries, but ukmm would silently fail to start: https://github.com/NixOS/nixpkgs/pull/325139#discussion_r1676954757. I noticed that a bunch of other packages were defining `RUSTFLAGS` to handle this, so I just ended up using that instead, but it was surprising to see that `NIX_LDFLAGS` wouldn't work.

### Steps To Reproduce
1. Create a rust package with `NIX_LDFLAGS` set
2. Notice that the libraries listed in `NIX_LDFLAGS` don't actually get linked in resulting binaries

### Expected behavior

`NIX_LDFLAGS` should link extra libraries in rust like it does with packages built with c.

### Notify maintainers

@zowoq @winterqt @figsoda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.6, NixOS, 24.05 (Uakari), 24.05.20240623.e4509b3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/h5hhc58qp2rcv0f3d9di6569pxrpsi1j-source`
```

**Comment by nbdd0121** [comment]
I believe this is another case caused by https://github.com/rust-lang/rust/pull/124129

**Comment by kira-bruneau** [comment]
I don't think this is a regression, it just looks like it was something that wasn't considered when the rust builder was created.

It seems like all other packages that use the same workaround I used for ukmm were merged before https://github.com/rust-lang/rust/pull/124129:
- [`asusctl`](https://github.com/NixOS/nixpkgs/commit/4c976baa028c1e3b6bea17c398cd76f807a4a990#diff-111b3f9fb395f3b1f8e350b2e8aac48a508b7e35a842d8760f02d860e7ace866R76-R83)
- [`cosmic-applets`](https://github.com/NixOS/nixpkgs/commit/4309990c6fffe6c810d6aba0b12ecb350970f0c4#diff-3af8f13ff2c5c37b8fb9ee0c792081d0f08b5d0dfda0af6c454ed50a78f79132R47-R53)
- [`cosmic-comp`](https://github.com/NixOS/nixpkgs/commit/b3b7a4ee505a5c67a04d96408c1c9101cc3d634b#diff-e23bb192588b46aae680473921356df5d2730642f52573f7bbf9c87f16c3d39aR35-R43)
- [`cosmic-edit`](https://github.com/NixOS/nixpkgs/commit/209b3dd0d8cfe87ccf14d1b4f71ccb5540f4d887#diff-344b4eb851b791a6e1462913d360854ec7069731cdc2d7489efe250cae62d9e4R82-R91)
- [`cosmic-panel`](https://github.com/NixOS/nixpkgs/commit/038c9e5bafb8c75e218fcf18cf974482a3ab6ba1#diff-ab760698835e12a6d66563ad2caeca0834db8a9a1385f012c9e281ee51dcc25eR39-R45)
- [`cosmic-store`](https://github.com/NixOS/nixpkgs/commit/fcd8d511fbf63926f924cf8a89f2ddfdd4470146#diff-7f8cb4f0596b3ba70ce56df6451b6bd3822876cbd75a4c5f191ab34d74709ddcR65-R73)
- [`cosmic-term`](https://github.com/NixOS/nixpkgs/commit/4d2152d75f59ef1f10f112b0ee6528d3732929d6#diff-7f3c8a7ff13ddeb77e80b6673ffe127118579849688c1f82d446c530f4e5ae71R75-R82)
- [`cosmic-workspaces-epoch`](https://github.com/NixOS/nixpkgs/commit/ee2d9390c3494a01041adb401fb583ef25d5755e#diff-1196f526a4d896ad26b57abd631849d5a3df1161a2794d600f9787862358ca31R43-R51)
- [`xdg-desktop-portal-cosmic`](https://github.com/NixOS/nixpkgs/commit/f6b3cb4a266046c1ad9445a569c1546806cec706#diff-9660ff47e93fc683d7c4a1649e5c181dffa75f2a519f4ae242a2d0c9730cec16R38-R46)

**Comment by nbdd0121** [comment]
Cosmic ones use dlopen so they require the no-as-needed flag to have the libraries added even without any symbol reference.

What I have observed is that with Rust nightly even referenced symbols will not have rpath set properly. I guess what I see is a different bug with similar symptom.

**Comment by yrns** [comment]
FWIW, I use `NIX_LDFLAGS = "-rpath ${lib.makeLibraryPath buildInputs}";` and it seems to work for Rust binaries.

**Comment by kira-bruneau** [comment]
@yrns Oh weird, do you have an example? I just tried doing that with ukmm again, and it's still not working, but maybe there's some hook/other dependency that I'm missing?

Here's the derivation I tried for ukmm with `NIX_LDFLAGS`:

```
nix derivation show .#ukmm
```

```json
{
  "/nix/store/509wijbz6njgpwjjy5n5m1frda1hqkrq-ukmm-0.15.0.drv": {
    "args": [
      "-e",
      "/nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh"
    ],
    "builder": "/nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash",
    "env": {
      "NIX_LDFLAGS": "-rpath /nix/store/5mb70vg3kdzkyn0zqdgm4f87mdi0yi4i-libglvnd-1.7.0/lib:/nix/store/4fgxx1rc4x9vzzylyd192nkzb2ahva1p-libxkbcommon-1.7.0/lib:/nix/store/h1ydpxkw9qhjdxjpic1pdc2nirggyy6f-openssl-3.3.2/lib",
      "PKG_CONFIG_ALLOW_CROSS": "0",
      "__structuredAttrs": "",
      "buildInputs": "/nix/store/wjpikbgivasi62j96csmdf5w00kkwnf9-libglvnd-1.7.0-dev /nix/store/6dir2ya69y1lr1shf95wh8gr0d1svd90-libxkbcommon-1.7.0-dev /nix/store/pp2zf8bdgyz60ds8vcshk2603gcjgp72-openssl-3.3.2-dev",
      "builder": "/nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash",
      "cargoBuildFeatures": "",
      "cargoBuildNoDefaultFeatures": "",
      "cargoBuildType": "release",
      "cargoCheckFeatures": "",
      "cargoCheckNoDefaultFeatures": "",
      "cargoCheckType": "release",
      "cargoDeps": "/nix/store/13nv3f5r4r6y1gijjwayc2lglls447wh-cargo-vendor-dir",
      "cargoTestFlags": "--all",
      "checkFlags": "--skip=gui::tasks::tests::remerge --skip=pack::tests::pack_mod --skip=project::tests::project_from_mod --skip=tests::read_meta --skip=unpack::tests::read_mod --skip=unpack::tests::unpack_mod --skip=unpack::tests::unzip_mod --skip=bnp::test_convert",
      "cmakeFlags": "",
      "configureFlags": "",
      "configurePhase": "runHook preConfigure\nrunHook postConfigure\n",
      "depsBuildBuild": "",
      "depsBuildBuildPropagated": "",
      "depsBuildTarget": "",
      "depsBuildTargetPropagated": "",
      "depsHostHost": "",
      "depsHostHostPropagated": "",
      "depsTargetTarget": "",
      "depsTargetTargetPropagated": "",
      "doCheck": "1",
      "doInstallCheck": "",
      "mesonFlags": "",
      "name": "ukmm-0.15.0",
      "nativeBuildInputs": "/nix/store/38cffsqqx823crf1i4bcf6zz1qz1hgpd-cmake-3.30.5 /nix/store/0d4m43yp69lrm8imxbqgl9zxjwwz52jw-pkg-config-wrapper-0.29.2 /nix/store/0nmsi40rfxgv5r2c7673c9lv42rxvpb3-wrap-gapps-hook /nix/store/vyyrhvjd30x2mkmvjy6qc25lrpsx3xh1-auditable-cargo-1.83.0 /nix/store/jaqg4a9kdp2szqnswxizn60zhbg7q22n-cargo-build-hook.sh /nix/store/m8f1hgzp2aa6rgkf82c3r2j03lvmapqc-cargo-check-hook.sh /nix/store/7p2gx5daa4vnqcl4276acl06099n83qg-cargo-install-hook.sh /nix/store/394bbrkpyr7viwp942pkr92cz7k64066-cargo-setup-hook.sh /nix/store/ss0yarz4m14gcskw73makm0glkm5aj9a-rustc-wrapper-1.83.0",
      "out": "/nix/store/mcqrl0b4py57a006mp7q2n2wcihigk8q-ukmm-0.15.0",
      "outputs": "out",
      "patches": "",
      "pname": "ukmm",
      "postUnpack": "eval \"$cargoDepsHook\"\n\nexport RUST_LOG=\n",
      "propagatedBuildInputs": "",
      "propagatedNativeBuildInputs": "",
      "src": "/nix/store/9icmhij8x8kq04pp2mis4i21098j1k1z-source",
      "stdenv": "/nix/store/d0gfdcag8bxzvg7ww4s7px4lf8sxisyx-stdenv-linux",
      "strictDeps": "1",
      "system": "x86_64-linux",
      "version": "0.15.0"
    },
    "inputDrvs": {
      "/nix/store/2qglsdxggm5033zb8nib4q07ng82yckv-cargo-check-hook.sh.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/30w5namr5bbg6zs0nfifw752s45ngd2b-auditable-cargo-1.83.0.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/5w1gxbwa8ixsvhfrgf9xilh3jg69dsd2-rustc-wrapper-1.83.0.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/asnfc1fbhcpnrhnk4kkrs5zrb5gdf5qs-stdenv-linux.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/cr5fwgmhs43bb4cn38dxq085k68iklwl-libglvnd-1.7.0.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "dev",
          "out"
        ]
      },
      "/nix/store/f90qwklsn9pgx3arlmizh60zdwx48c7l-source.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/fg5phv5vlsr5yjpzn8kx51r0pipfhh0w-cargo-setup-hook.sh.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/gcindcflcp4jway4igjy500yaccm9bxv-cmake-3.30.5.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/hgrb9180br5gxj1k3v6cm3w0s2k74yfy-cargo-install-hook.sh.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/mwf8p4j7j6zyii3khpvb7hpg0i9pxy3s-cargo-vendor-dir.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/nnpgwwk2h5b3j4zg2lafjkb4xra4gb7x-pkg-config-wrapper-0.29.2.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/nw8mwm6wb25n9dgq61klw5d3ymfz4gf4-openssl-3.3.2.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "dev",
          "out"
        ]
      },
      "/nix/store/q68v2ljr3cd4670yhssw7qf7z5nbax4n-wrap-gapps-hook.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/vlbyybhm6y33iw43l9swa9y1v13lyjvd-libxkbcommon-1.7.0.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "dev",
          "out"
        ]
      },
      "/nix/store/vrx8z3fnwbcfggqhjmj1hz4szfw59fwh-bash-5.2p37.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      },
      "/nix/store/xqpz37816780dr8syh2k40d1ickwn2cc-cargo-build-hook.sh.drv": {
        "dynamicOutputs": {},
        "outputs": [
          "out"
        ]
      }
    },
    "inputSrcs": [
      "/nix/store/v6x3cs394jgqfbi0a42pam708flxaphh-default-builder.sh"
    ],
    "name": "ukmm-0.15.0",
    "outputs": {
      "out": {
        "path": "/nix/store/mcqrl0b4py57a006mp7q2n2wcihigk8q-ukmm-0.15.0"
      }
    },
    "system": "x86_64-linux"
  }
}
```

**Comment by yrns** [comment]
You're right, it doesn't work. I was using `dontPatchELF = true`. Weirdly, it works in a dev shell when building manually.

**Comment by kira-bruneau** [comment]
Oh wait... I think it's because the rust build links with `--as-needed` by default, this works using `NIX_LDFLAGS`:

```nix
NIX_LDFLAGS = [
  "--push-state,--no-as-needed"
  "-lEGL"
  "-lwayland-client"
  "-lxkbcommon"
  "--pop-state"
];
```

I think this might be the culprit: https://github.com/NixOS/nixpkgs/blob/5048836ab7a6de47e490a6e6259b15822d5f5753/pkgs/development/compilers/rust/rustc.nix#L99-L105

I'm not 100% sure, but I think `--push-state` requires a comma, and without it, the `--as-needed` flag is leaking out of the scope is was intended to be used in.

**Comment by kira-bruneau** [comment]
Oh sorry never mind. The `NIX_LDFLAGS` for rustc should only apply to rustc, not everything built with rustc. I'm still not quite sure why it defaults to `--as-needed` though :thinking:

**Comment by nbdd0121** [comment]
Rust always add `--as-needed` for linking: https://github.com/rust-lang/rust/blob/6d3db555e614eb50bbb40559e696414e69b6eff9/compiler/rustc_codegen_ssa/src/back/link.rs#L2304

**Comment by kira-bruneau** [comment]
Oh thanks @nbdd0121! That clears it up! I'll close this then since it was just a misunderstanding.
