### ISSUE TITLE
nixpkgs unstable breaks stackage 7.XX

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#32704]
```
$ stack build --nix
...
error: attribute ‘ghc801’ missing, at (string):1:70
```

GHC801 was removed in 398b36431d6f08b4b9902a8e2d2d4eb0bd34e435

The easiest fix would be to alias `ghc801` to `ghc802`, but going forward we should discuss what is our advertised API for downstream package managers.

cc @peti

**Comment by gebner** [comment]
See also #29791

**Comment by domenkozar** [comment]
Ah :(

**Comment by domenkozar** [comment]
The codebase between ghc801 and ghc802 is merely identical, the overhead maintaining either one or both is negligable.

**Comment by peti** [comment]
Personally, I would like to remove all ghc versions except for the last 3 major releases, i.e. 8.2.2, 8.0.2, and 7.10.3. Anything beyond that is madness, i.e. there is no healthy relationship between the amount of effort that's necessary to do it and the number of people who actually use any of that old code.

If anyone feels like maintaining additional releases and package sets, then I'd like that to occur in an overlay, but not in Nixpkgs itself.

**Comment by gebner** [comment]
> The easiest fix would be to alias ghc801 to ghc802

Unfortunately this breaks many packages that have a version bound on ghc:
```
± stack build intero
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for haskeline-0.7.2.3:
    directory-1.3.0.0 from stack configuration does not match >=1.1 && <1.3 (latest matching version is 1.2.7.1)
needed due to intero-0.1.19 -> haskeline-0.7.2.3
In the dependencies for intero-0.1.19:
    ghc-8.0.2 from stack configuration does not match >=7.8 && <8.0.2
needed since intero is a build target.
Some potential ways to resolve this:
  * Recommended action: try adding the following to your extra-deps in /home/gebner/tip-tools/stack.yaml:
- directory-1.2.7.1
  * Set 'allow-newer: true' to ignore all version constraints and build anyway.
  * You may also want to try using the 'stack solver' command.
Plan construction failed.
```

**Comment by peti** [comment]
Personally, I am willing to support the last 3 major GHC releases in `haskell.compiler.ghcXYZ` plus an accompanying package set in `haskell.packages.ghcXYZ` that builds "mostly". Anything beyond that has to be done by someone else, preferably in an overlay. 

In particular, Nixpkgs does not try to support any old LTS package sets. We tried that in the past, and it's too much effort.
