### ISSUE TITLE
Qemu cannot build on macOS due to case insensitive filenames

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#32701]
The symptom:

```
$ nix-build '<nixpkgs-next>' -A qemu
these derivations will be built:
  /nix/store/15nva20ix2444sxpd868hf07waz7mz34-qemu-2.10.1.drv
building path(s) ‘/nix/store/6hl1k17kzzb2x85bzwmz7a5jqh79hbyd-qemu-2.10.1’
unpacking sources
unpacking source archive /nix/store/1q6b9pz9g0qb5lp5jakxd3q3yi3agm7a-qemu-2.10.1.tar.bz2
tar: qemu-2.10.1/roms/u-boot/scripts/Kconfig: Cannot open: File exists
tar: Exiting with failure status due to previous errors
```

This started happening a few months ago because there is a directory named `kconfig` under scripts as well.

**Comment by vcunat** [comment]
IMHO this would better be suited as upstream bug.

**Comment by dezgeg** [comment]
Someone already reported there (since they bundle u-boot sources for some reason and the bad file is coming there, and it's reported & fixed in U-Boot).

**Comment by jwiegley** [comment]
From their tracker: https://bugs.launchpad.net/qemu/+bug/1714750
