### ISSUE TITLE
Polybar built with mpd support doesn’t have mpd support

### ISSUE THREAD

**Issue by iambeingtracked** [NixOS/nixpkgs#327025]
### Describe the bug
Polybar built with `mpdSupport = true` doesn't actually have mpd support. Same thing with pulseaudio.

`polybar --version` returns:
```
Features: +alsa -curl -i3 -mpd +network(libnl) -pulseaudio +xkeyboard
```

### Steps To Reproduce
1. Have this in your configuration.nix: |
```
environment.systemPackages = with pkgs; [
(polybar.override {
    mpdSupport = true;
    pulseSupport = true;
})
...
];
```

### Expected behavior
`polybar --version` should return:
```
Features: +alsa -curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

### Additional context
I thought that it might be the OOM killer, after which I adjusted my machine to have 8 gigabytes of memory and it still doesn't have mpd and pulseaudio support.

### Notify maintainers
@afldcr
@Br1ght0ne
@ckiee
@moni-dz

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.05 (Uakari), 24.05.20240707.1948467`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/home/maksim/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iambeingtracked** [comment]
Also see: https://discourse.nixos.org/t/polybar-built-with-mpd-support-doesnt-have-mpd-support/48870

**Comment by eclairevoyant** [comment]
I can't reproduce this on master (0ea5202cc3194421983e6ef5ef1b2f5f8c48b1f4):

```
$ nix-build -E '(import ./. {}).polybar.override { mpdSupport = true; }' && result/bin/polybar --version
/nix/store/09fyw7avlblmp2pk49xrhgkc89by1crd-polybar-3.7.1
polybar 3.7.1

Features: +alsa -curl -i3 +mpd +network(libnl) -pulseaudio +xkeyboard
```

**Comment by iambeingtracked** [comment]
Solved on discourse: https://discourse.nixos.org/t/polybar-built-with-mpd-support-doesnt-have-mpd-support/48870/8
