### ISSUE TITLE
Update request: gnomeExtension.switcher → 42

### ISSUE THREAD

**Issue by devvythelopper** [NixOS/nixpkgs#327157]
Since I doubt you are actually updating gnome's extensions by hand, I'm wondering why this is not available yet... Is there a process for the current release to update fitting gnome extensions for the shell version that is selected?

**Comment by trzpiot** [comment]
Most GNOME extensions are updated via a [Python script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/update-extensions.py) (switcher included). However, the script must be executed, reviewed and merged manually. Unfortunately, this takes time.

There is a PR open (https://github.com/NixOS/nixpkgs/pull/335820) that updates the extensions. So lets wait and see. :)

**Comment by honnip** [comment]
Version 42 doesn't seem to exist? 
I have checked EGO and source https://github.com/daniellandau/switcher/blob/4fbc637be70bda6222e1c9399b1abb2c47f0cab9/metadata.json
