### ISSUE TITLE
Duplicate Konqueror Packages

### ISSUE THREAD

**Issue by hawl1** [NixOS/nixpkgs#327196]
There is multiple Konqueror packages on nixpkgs, one of them not being updated.

https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=konqueror

**Comment by chewblacka** [comment]
This is as intended for plasma 5 and plasma 6. Same for other kde packages, e.g. konsole. I think plasma 5 will get removed at some point.

**Comment by hawl1** [comment]
> This is as intended for plasma 5 and plasma 6. Same for other kde packages, e.g. konsole. I think plasma 5 will get removed at some point.

so this isnt really an issue?

**Comment by hawl1** [comment]
i think its not an issue since theyll be removed, so, sorry for useless issue
