### ISSUE TITLE
Build failure: nvidia-x11-555.58.02-6.9.9.drv

### ISSUE THREAD

**Issue by hasrthur** [NixOS/nixpkgs#327116]
### Steps To Reproduce

try to build nixos with latest kernel and stable nvidia

```nix
services.xserver.videoDrivers = [ "nvidia" ];
  hardware.graphics.enable = true;
  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    open = false;
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
  };

boot.kernelPackages = pkgs.linuxPackages_latest;
```

`hardware-configuration.nix`

```nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

```

### Build log

log [gist](https://gist.github.com/hasrthur/68a726b147a8da5f22c0086d716123e7)

### Notify maintainers

@kiskae @edwtjo

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
Cannot reproduce, ran the command `NIXPKGS_ALLOW_UNFREE=1 nix build --impure nixpkgs/nixos-unstable#linuxPackages_latest.nvidiaPackages.stable -L` and it successfully built `nvidia-x11-555.58.02-6.9.9`.

However looking at your logs this error is very suspicious and makes me think the problem does not exist in the nvidia driver.

> /build/NVIDIA-Linux-x86_64-555.58.02/kernel/nvidia-uvm/uvm_gpu_replayable_faults.c:599:18: internal compiler erro
r: Segmentation fault

**Comment by hasrthur** [comment]
Thank you for quick response! Can this be connected with the fact that I didn't enable X11 but only wayland? 

If not what else can I do to identify the problem?

**Comment by Kiskae** [comment]
> Thank you for quick response! Can this be connected with the fact that I didn't enable X11 but only wayland?
> 
> If not what else can I do to identify the problem?

No, the failure is happening way before the nixos configuration becomes relevant.

Two things you can try is:
1. `nix store verify --all` to check that nothing in your nix store is corrupted
2. trying the build again and seeing if the failure is consistent, but considering it involves a segfault I doubt that.

**Comment by hasrthur** [comment]
@Kiskae you were right - the problem is on my side: I disabled xmp1 for the memory in the bios and I managed to install both latest kernel and stable nvidia drivers. 
```console
❯ uname -a
Linux nixos 6.9.9 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jul 11 10:51:24 UTC 2024 x86_64 GNU/Linux

~
❯ cat /etc/current-system-packages | grep nvidia
nvidia-settings-555.58.02
nvidia-x11-555.58.02-6.9.9
```

Thank you for your help!
