### ISSUE TITLE
nixos/ydotool: Unknown key name 'ProtectUser' in section 'Service'

### ISSUE THREAD

**Issue by wentasah** [NixOS/nixpkgs#327156]
### Describe the bug

Systemd [service definition for ydotoold](https://github.com/NixOS/nixpkgs/blob/f12ee5f64c6a09995e71c9626d88c4efa983b488/nixos/modules/programs/ydotool.nix#L62) contains undefined directive `ProtectUser`. This results in the following warning in the journal:

    systemd[1]: /etc/systemd/system/ydotoold.service:31: Unknown key name 'ProtectUser' in section 'Service', ignoring.

### Steps To Reproduce
1. Define `programs.ydotool.enable = true;` in a NixOS config
2. Start the `ydotoold` service.
3. Run `journalctl -u ydotoold` as root and observe the above warning.

### Expected behavior
No warning. Did you mean some other `Protect*` directive?

### Notify maintainers

@quantenzitrone

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.05 (Uakari), 24.05.20240712.f12ee5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/2hmc93ki0rvz6d20lmbscqw32612p8an-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MatthewCash** [comment]
They probably meant to set the `DynamicUser` hardening option, but I would expect that option to cause the service to fail since root is required to access `/dev/uinput`.

**Comment by quantenzitrone** [comment]
I don't really know what I meant with this option
PrivateUsers maybe, but that is already included
