### ISSUE TITLE
`nix.settings.preallocate-contents` is not enabled by default

### ISSUE THREAD

**Issue by DaniD3v** [NixOS/nixpkgs#327210]
## Issue description
The documentation for states that this option decides
 > Whether to preallocate files when writing objects with known size.

This sounds like it should be enabled by default.

Are there any downsides to enabling this?
In that case they should definitely be documented.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.05 (Uakari), 24.05.20240712.f12ee5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `""`
 - nixpkgs: `/nix/store/2hmc93ki0rvz6d20lmbscqw32612p8an-source`
```

**Comment by eclairevoyant** [comment]
Per [the nix reference manual](https://nix.dev/manual/nix/2.22/command-ref/conf-file.html#conf-preallocate-contents), `preallocate-contents` is false by default in nix. We should not have surprising defaults downstream in nixpkgs, so changing the default should be discussed upstream in [the nix repo](https://github.com/NixOS/nix).

**Comment by DaniD3v** [comment]
sry I'll go open an issue there
