### ISSUE TITLE
Build failure: fprintd-tod

### ISSUE THREAD

**Issue by JohannHoepfner** [NixOS/nixpkgs#327268]
### Steps To Reproduce

1. build *fprintd-tod*

### Build log

[https://gist.github.com/JohannHoepfner/5d6805bef7ae6bfca59d669bdddad288](https://gist.github.com/JohannHoepfner/5d6805bef7ae6bfca59d669bdddad288)

### Notify maintainers

@hmenke

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9, NixOS, 24.11 (Vicuna), 24.11.20240712.7e7c39e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hmenke** [comment]
Fix queued https://github.com/NixOS/nixpkgs/pull/327289
