### ISSUE TITLE
Matrix-Synapse seems to not build (fails in running tests) on unstable

### ISSUE THREAD

**Issue by Limvot** [NixOS/nixpkgs#32729]
## Issue description
Building my config that worked on an earlier version of unstable (/nix/store/38fyswipv3ny
07a1h101aa68fr824855-nixos-system-nixos-18.03pre121253.2f1a818d00) and on 17.09 no longer works on current unstable, failing with the following

```
checking for references to /tmp/nix-build-python2.7-matrix-synapse-ldap3-0.1.2.drv-0 in /nix/store/zracqqpzaq16lvricmsdi95rn35yvz8k-python2.7-matrix-synapse-ldap3-0.1.2...
running install tests
running test
running egg_info
writing requirements to matrix_synapse_ldap3.egg-info/requires.txt
writing matrix_synapse_ldap3.egg-info/PKG-INFO
writing top-level names to matrix_synapse_ldap3.egg-info/top_level.txt
writing dependency_links to matrix_synapse_ldap3.egg-info/dependency_links.txt
reading manifest file 'matrix_synapse_ldap3.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'matrix_synapse_ldap3.egg-info/SOURCES.txt'
running build_ext
tests.test_simple (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: tests.test_simple (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_simple
Traceback (most recent call last):
  File "/nix/store/pjxvh01jhjm9m62lwm5vbnn0ml5xd35s-python-2.7.14/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/nix/store/pjxvh01jhjm9m62lwm5vbnn0ml5xd35s-python-2.7.14/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python2.7-matrix-synapse-ldap3-0.1.2.drv-0/source/tests/__init__.py", line 5, in <module>
    from ldaptor.inmemory import fromLDIFFile
ImportError: No module named ldaptor.inmemory


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
builder for ‘/nix/store/syzdwr18pf0lzbv2lx5idhbwaarby326-python2.7-matrix-synapse-ldap3-0.1.2.drv’ failed with exit code 1
```

### Steps to reproduce

Use Synapse on unstable.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2378.af7e47921c4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre122666.afe9649210c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Let me know if there's anything else I can do! (long time user, first time reporter :) )

**Comment by Taeradan** [comment]
I am facing the same issue, with :

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.65, NixOS, 18.03pre121925.3eccd0b11d1 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre123588.ade98dc442e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by eqyiel** [comment]
this is already fixed in https://github.com/NixOS/nixpkgs/pull/33008

**Comment by dotlambda** [comment]
@Limvot Can this be closed?
