### ISSUE TITLE
networkmanagerapplet doesn't find icons as user package

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nixpkgs#32730]
## Issue description

I have installed `networkmanagerapplet` as user package, but I get errors like these and an red error icon in my tray bar:
```
(nm-applet:1517): Gtk-WARNING **: Could not find the icon 'nm-signal-75'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(nm-applet:1517): nm-applet-WARNING **: failed to load icon "nm-signal-75": Icon 'nm-signal-75' not present in theme Adwaita

(nm-applet:1517): nm-applet-WARNING **: failed to load icon "nm-signal-50": Icon 'nm-signal-50' not present in theme Adwaita

(nm-applet:1517): nm-applet-WARNING **: failed to load icon "nm-secure-lock": Icon 'nm-secure-lock' not present in theme Adwaita

(nm-applet:1517): nm-applet-WARNING **: failed to load icon "nm-signal-25": Icon 'nm-signal-25' not present in theme Adwaita
```

When installed globally via `environment.systemPackages` everything is fine.

The difference doesn't make sense to me, because all icons are linked, e.g.:
```
$> ll /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-*
lrwxrwxrwx 1 root root 120 Jan  1  1970 /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-00.png -> /nix/store/2mbyli3izyrk55c0nc0phssk0gg4qd6s-network-manager-applet-1.4.6/share/icons/hicolor/22x22/apps/nm-signal-00.png
lrwxrwxrwx 1 root root 120 Jan  1  1970 /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-25.png -> /nix/store/2mbyli3izyrk55c0nc0phssk0gg4qd6s-network-manager-applet-1.4.6/share/icons/hicolor/22x22/apps/nm-signal-25.png
lrwxrwxrwx 1 root root 120 Jan  1  1970 /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-50.png -> /nix/store/2mbyli3izyrk55c0nc0phssk0gg4qd6s-network-manager-applet-1.4.6/share/icons/hicolor/22x22/apps/nm-signal-50.png
lrwxrwxrwx 1 root root 120 Jan  1  1970 /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-75.png -> /nix/store/2mbyli3izyrk55c0nc0phssk0gg4qd6s-network-manager-applet-1.4.6/share/icons/hicolor/22x22/apps/nm-signal-75.png
lrwxrwxrwx 1 root root 121 Jan  1  1970 /etc/per-user-pkgs/tobias/share/icons/hicolor/22x22/apps/nm-signal-100.png -> /nix/store/2mbyli3izyrk55c0nc0phssk0gg4qd6s-network-manager-applet-1.4.6/share/icons/hicolor/22x22/apps/nm-signal-100.png
```

### Steps to reproduce

```nix
{ pkgs, ...}:
{
  users.users.tobias.packages = with pkgs; [ networkmanagerapplet ];
}
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2378.af7e47921c4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2378.af7e47921c4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
For icons to be loaded `/etc/per-user-pkgs/tobias/share` would have to be added to `XDG_DATA_DIRS` variable. Though the `$out/share` is already added to the variable in the wrapper (see the content of `$(nix-build -A networkmanagerapplet)/bin/nm-applet`). Could you try running `strace nm-applet`?

**Comment by Gerschtli** [comment]
On `strace nm-applet` I get:
https://gist.github.com/Gerschtli/4a35a52faa9b8b090379e387a83ec5bb

My current setup:
```
$> echo $XDG_DATA_DIRS                    
/run/opengl-driver/share:/etc/per-user-pkgs/tobias/share:/home/tobias/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

**Comment by Gerschtli** [comment]
Anyone hear, who can help?

**Comment by jtojnar** [comment]
What desktop environment do you use? What is the output `strings /proc/$(pidof nm-applet)/environ | grep XDG_DATA_DIRS`?

**Comment by Gerschtli** [comment]
I'm using [dwm](https://dwm.suckless.org/) as wm. For more system info see host `argon` in https://github.com/Gerschtli/nixos-configurations

```sh
$> strings /proc/$(pidof nm-applet)/environ | grep XDG_DATA_DIRS
XDG_DATA_DIRS=/nix/store/d4iccmmp44q7xcjfjd0yxc5p8m92cqsm-network-manager-applet-1.4.6/share:/nix/store/mqcr7a7n0ry92dsw71hza7sy1026kyyx-gtk+3-3.22.21/share/gsettings-schemas/gtk+3-3.22.21:/nix/store/5x8lx5ky716gjyqfiv0kb2wmga4ivvcn-gsettings-desktop-schemas-3.24.0/share/gsettings-schemas/gsettings-desktop-schemas-3.24.0:/nix/store/d4iccmmp44q7xcjfjd0yxc5p8m92cqsm-network-manager-applet-1.4.6/share/gsettings-schemas/network-manager-applet-1.4.6:/run/opengl-driver/share:/run/opengl-driver-32/share:/etc/per-user-pkgs/tobias/share:/home/tobias/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

**Comment by vitiral** [comment]
This also happens when attempting to start networkmanagerapplet as a service:

```
  systemd.user.services."network-manager-applet" = {
    enable = true;
    description = "Start the network manager applet";
    wantedBy = [ "default.target" ];
    serviceConfig.Type = "forking";
    serviceConfig.Restart = "always";
    serviceConfig.RestartSec = 2;
    serviceConfig.ExecStart = "${pkgs.networkmanagerapplet}/bin/nm-applet";
    environment = {
       XDG_DATA_DIRS = "${pkgs.networkmanagerapplet}/bin/nm-applet/share";
    };
  };
```

> Note: Adding the `XDG_DATA_DIRS` to the environment did **not** resolve the issue.

The service works fine, but the icon is a red-error icon even though wifi is connected.

Would love some help if anyone has any ideas!

**Comment by andir** [comment]
I can confirm the same on my 17.09 and my unstable machine. It is a bit annoying :/ The dir in XDG_DATA_DIRS contains the NM specific icons for the `hicolor` theme.

When I observe the log for my network-manager-applet I can see:

> failed to load icon "nm-stage03-connecting03": Icon 'nm-stage03-connecting03' not present in theme Adwaita

Switching my theme configuratio to `hicolor` didn't help at all.

I ended up configuring the `home-manager` settings for `gtk` (`gtk.iconTheme = { package = pkgs.hicolor_icon_theme; name = "hicolor"; };`) and now the icons work for me...

That solution is probably not how it should be but maybe someone find this information helpful.

**Comment by Gerschtli** [comment]
Can't reproduce this error on 18.03. Therefore I'm closing this issue

**Comment by bgamari** [comment]
I am still seeing this on 18.03, for the record.

**Comment by dustinlacewell** [comment]
Still seeing this as well

![image](https://user-images.githubusercontent.com/53952/45469164-ffce1380-b6ed-11e8-84b8-13994de47564.png)

**Comment by CarlosMChica** [comment]
I do see the same issue and have installed both `hicolor-icon-theme` and `gnome2.gnome_icon_theme` as suggested in this other possibly related issue https://github.com/NixOS/nixpkgs/issues/43836

**Comment by jtojnar** [comment]
`hicolor-icon-theme` does not really contain any icons, and `gnome2.gnome_icon_theme` is extremely outdated, possibly not containing the needed icons. Can you try installing `gnome3.adwaita-icon-theme` or some other modern theme?

**Comment by CarlosMChica** [comment]
Same result.

**Comment by Gerschtli** [comment]
I don't have an icon theme installed and with my config ( https://github.com/Gerschtli/nixos-configurations/blob/master/configuration-argon.nix ) it's working perfectly fine..

**Comment by endgame** [comment]
I had this problem also, but `nm-applet` issued warnings about missing hicolor icons when run from a terminal, and installing `hicolor-icon-theme` fixed it.

**Comment by xanderio** [comment]
I'm still facing this issue when running via `nm-applet --indicator` with waybar under wayland.

My configuration https://github.com/xanderio/nix-dotfiles

```
Apr 10 10:34:21 nixos waybar[2615]: [2022-04-10 10:34:21.432] [error] Item 'nm-applet': Icon 'nm-signal-100' not present in theme Adwaita
Apr 10 10:34:21 nixos waybar[2615]: [2022-04-10 10:34:21.449] [error] Item 'nm-applet': Icon 'nm-signal-100' not present in theme Adwaita
```

**Comment by nblock** [comment]
> I'm still facing this issue when running via `nm-applet --indicator` with waybar under wayland.

@xanderio In case you are missing parts of the icons/checkboxes - try to remove: 

```css
border: none;
border-radius: 0;
min-height: 0;
```
from https://github.com/xanderio/dotfiles/blob/main/home/desktop/wayland/waybar/style.css

**Comment by jlbribeiro** [comment]
In case someone stumbles upon this issue in 2023:
I was also missing the icon on my `waybar`'s applet tray, when enabling `nm-applet` via `services.network-manager-applet.enable = true;` (in `home-manager`). Installed icon themes, etc., and that didn't solve it.

Installing `pkgs.networkmanagerapplet` (also in `home-manager`), in addition to enabling the service, made the icon appear correctly; I'm unsure why (I'm very new to NixOS, but I was under the impression that enabling the service was [installing the same package implicitly](https://github.com/nix-community/home-manager/blob/8c66b46a86afa21763766ef97d7c8be5f3954e2b/modules/services/network-manager-applet.nix#L36)), and whether this is the right approach.

**Comment by jtojnar** [comment]
> I was under the impression that enabling the service was [installing the same package implicitly](https://github.com/nix-community/home-manager/blob/8c66b46a86afa21763766ef97d7c8be5f3954e2b/modules/services/network-manager-applet.nix#L36)

No, it does not. One of the benefits of the Nix model is that dependencies do not need to be installed globally for software to be able to use them, they just need to be present in the Nix store, which is what Nix ensures.

The `systemd.user.services.network-manager-applet` home-manager option basically just creates a single Nix store derivation with a `.service` file and `home-manager` then places it in the correct place in your profile where systemd can see it, nothing more.

So if you want your session to pick up icons from a package, you need to explicitly install it to the session (e.g. with `home.packages` option). It would be sensible for `services.network-manager-applet.enable` option to do it for you. Possible reasons why it does not include:

- Everybody using nm-applet had it already installed some other way they did not notice the hm module was not installing it.
- Or they had an icon theme installed, which included the icon.
- Or if they did not, they did not care enough about the missing icon.
- Installing it has other downsides (e.g. it will be started twice due to autostart files in the package).

**Comment by jlbribeiro** [comment]
@jtojnar Thanks for your explanation; I had gotten the impression that referring `${pkgs.some_package}/bin/some_bin` somewhere in a derivation (like a path) would implicitly install said package. (In this case I guess `nm-applet` actually getting executed [without being explicitly installed] "supported" that perception.)

> - Installing it has other downsides (e.g. it will be started twice due to autostart files in the package).

I was afraid of exactly that, but tried it "out of desperation" :P So far, looks _ok_.

Although I just noticed it was actually missing the "disconnected" one (but showing the "connected to WiFi bars"); installing `hicolor-icon-theme` installed the missing one.
