### ISSUE TITLE
Update request: pulsar 1.117.0 → 1.118.0

### ISSUE THREAD

**Issue by slavachertanovo** [NixOS/nixpkgs#327332]
- Package name: pulsar
- Latest released version: 1.118.0
- Current version on the unstable channel: 1.117.0
- Current version on the stable/release channel: 1.117.0
- [v] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

 @bryango

**Comment by bryango** [comment]
Sorry I'm super busy these days... I'll try to get back to this as soon as possible. In the meantime, please try the `updateScript` of this package if you can, and see if the resulting package build fine. Thank you!

**Comment by slavachertanovo** [comment]
i am not familiar with updateScript and not really urgently need the latest Pulsar version, but i think update request is a good way to keep actual nixpkgs's packages version.
