### ISSUE TITLE
cpupower-gui is broken

### ISSUE THREAD

**Issue by coffeeispower** [NixOS/nixpkgs#327397]
### Describe the bug
cpupower-gui just doesn't start at all after adding to configuration and rebuilding. It seems like it relies on a systemd service called `cpupower-gui-helper`, however it doesn't appear on `systemctl list-units` at all and you can't start it.

### Screenshots
![imagem](https://github.com/user-attachments/assets/82f2bedd-450d-4c14-88b4-9980f0eeb73b)

### Notify maintainers
@unode

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-configuration on  flakes [$!] via ❄️  impure (nix-shell-env) 
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.05 (Uakari), 24.05.20240609.2819fff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/giq1qbcwfx5gq0g9jf6id0b3m55a860j-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by unode** [comment]
Do you have [`services.cpupower-gui.enable`](https://search.nixos.org/options?channel=24.05&show=services.cpupower-gui.enable&from=0&size=50&sort=relevance&type=packages&query=cpupower) set?

**Comment by coffeeispower** [comment]
@unode I didn't know that was a thing sorry

**Comment by unode** [comment]
No worries. Some software in nixpkgs, especially that which require system services often has such configuration that enables said services.

Um abraço!
