### ISSUE TITLE
Update request: rustc/cargo 1.78 → 1.79

### ISSUE THREAD

**Issue by techhazard** [NixOS/nixpkgs#327312]
- Package name: rust  programming language (rustc / cargo)
- Latest released version: [1.79.0](https://releases.rs/docs/1.79.0/) on june 13th.

- Current version on the unstable channel: 1.78.0 (both rustc and cargo)
- Current version on the 24.05 channel:  1.77.2 (both rustc and cargo) 

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Havvy @figsoda @Mic92 @tjni @winterqt @zowoq 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

This would be most appreciated, thanks in advance!

**Comment by Mic92** [comment]
Already in staging: https://github.com/NixOS/nixpkgs/pull/320250

**Comment by techhazard** [comment]
I'm not sure how I missed that, I guess I only searched for open PR/issues?
Thanks :+1:
