### ISSUE TITLE
Wireshark can't capture packets when running as normal user

### ISSUE THREAD

**Issue by C0D3-M4513R** [NixOS/nixpkgs#327368]
### Steps To Reproduce
1. Add `programs.wireshark.enable = true;` and `programs.wireshark.package = pkgs.wireshark;` to your system and add yourself to the `wireshark` group.
2. Try to capture anything, when starting wireshark on your user account (not root). It doesn't work

### Expected behavior
Capturing packets works from my current user.

### Screenshots
![image](https://github.com/user-attachments/assets/5369b709-aa63-49d0-b9ab-123795554bc0)

### Additional context

I expected dumpcap to have an owner of `wireshark` and to have it's capabilities set as per https://github.com/NixOS/nixpkgs/blob/nixos-24.05/nixos/modules/programs/wireshark.nix.

```
[nix-shell:~]$ ls -l $(which wireshark)
lrwxrwxrwx 1 root root 76 Jan  1  1970 /run/current-system/sw/bin/wireshark -> /nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/wireshark

[nix-shell:~]$ ls -ahl /nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/*{wireshark,dumpcap}*
-r-xr-xr-x 1 root root 20K Jan  1  1970 /nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/dumpcap
-r-xr-xr-x 1 root root 20K Jan  1  1970 /nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/wireshark
[nix-shell:~]$ sudo getcap -v /nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/dumpcap
/nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/dumpcap

[nix-shell:~]$ 
```

Simply running wireshark as root also doesn't solve the issue, because I am testing a custom plugin (I didn't code it, I simply fixed some compilation errors). The custom plugin loads successfully on my user, but doesn't on root. (yes, I installed it both on root and on my user) 

### Notify maintainers

@bjornfor 
@fpletz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32-rt32, NixOS, 24.05 (Uakari), 24.05.20240619.dd457de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/2lvj8bm21ymxra61dqrc4xpzr8njgywj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dawidd6** [comment]
I believe (basing on code) `dumpcap` should be first found in PATH in `/run/wrappers` directory and there the binary/script/wrapper should be owned by wireshark group and have those needed caps set.

**Comment by fpletz** [comment]
Weird, this works for me on unstable and I don't see any relevant changes to the wireshark module since the 24.05 release. What is the result of `which dumpcap` on your system and does `/run/wrappers/bin/dumpcap` exist?

**Comment by C0D3-M4513R** [comment]
After a couple of reboots the file permissions and caps suddenly changed to what you'd expect.

`which dumpcap` points to `/run/wrappers/bin/dumpcap`.
`/run/wrappers/bin/dumpcap` previously was a symlink to `/nix/store/56wlcg8nixrcsrgyc0dqfpm0r72ylnwb-wireshark-qt-4.2.5/bin/dumpcap` (similar to wireshark) with `root:root` owner and no caps.

now it is just a direct binary afaict, and it owned by `root:wireshark` with the appropriate caps.

Idk why just rebooting fixed this. I did not even do any rebuilding/updating at all.
