### ISSUE TITLE
Cantata crashes with incompatible Qt version error

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#32735]
## Issue description

Cantata crashes:

```
Cannot mix incompatible Qt library (version 0x50902) with this library (version 0x50903)
Aborted
```

### Steps to reproduce

On latest nixos-unstable:

```
nix-shell -p cantata --run cantata
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.2, NixOS, 18.03pre122666.afe9649210c (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre122666.afe9649210c"`
 - channels(m): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by orivej** [comment]
It's surprising that you have Qt 5.9.2 given that Nixpkgs provided 5.9.1 before the upgrade to 5.9.3, but this should be #30551.

**Comment by matthiasbeyer** [comment]
As this seems to be related to #30551, I'm closing this issue.
