### ISSUE TITLE
dotnet: fetchDeps now requires project files, breaking azure-functions-core-tools

### ISSUE THREAD

**Issue by Smaug123** [NixOS/nixpkgs#327489]
### Describe the bug

I believe https://github.com/NixOS/nixpkgs/commit/b5447275d2d3314e85880357f9ea4828c7070610#diff-85d3cfd845d109ea11a8b1b45fc62bedd5d6f320185b8608ca1da8362c92b69fR285 converted the following generated line of Bash:

```bash
declare -a projectFiles=(  )
```
into:

```bash
declare -a projectFiles=( '' )
```

`projectFiles` [is not set](https://github.com/NixOS/nixpkgs/blob/b2c1f10bfbb3f617ea8e8669ac13f3f56ceb2ea2/pkgs/development/tools/azure-functions-core-tools/default.nix#L24-L49), so it's `null`, and `toString (lib.toList null)` is the empty string; but when escaped, it became `''`.

The result is that the passthru does not generate a lockfile.

### Expected behavior
After I manually change the two `( '' )` into `()` in the definitions of `projectFiles` and `testProjectFiles`, I successfully start getting a NuGet restore.

### Screenshots

Failing passthru:

```
> /nix/store/aqxnndibdh3msmbm8y8ymbyphw5gwchd-fetch-deps
Will write lockfile to /Users/patrick/Documents/GitHub/nixpkgs/pkgs/development/tools/azure-functions-core-tools/deps.nix
Restoring project...
Cannot find a manifest file.
For a list of locations searched, specify the "-d" option before the tool name.
No tools were restored.
cp: cannot stat '/var/folders/tq/sx8_b6p91nz72q7_kgk1vgp80000gn/T/deps-azure-functions-core-tools-2oeGo1/home/.nuget/packages/*': No such file or directory
cp: cannot stat '/var/folders/tq/sx8_b6p91nz72q7_kgk1vgp80000gn/T/deps-azure-functions-core-tools-2oeGo1/home/.nuget/packages/*': No such file or directory
Succesfully restored project
Writing lockfile...
```

### Notify maintainers

@corngood @tie 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tie** [comment]
Hm, that is weird. Note that `projectFiles` cannot be null.

https://github.com/NixOS/nixpkgs/blob/3d1c1c0fceff9c91ec88ca56d58d340bf0c91439/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L93-L94

**Comment by tie** [comment]
This should be `lib.escapeShellArgs` (plural).

https://github.com/NixOS/nixpkgs/blob/3d1c1c0fceff9c91ec88ca56d58d340bf0c91439/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L230-L231

```
nix-repl> lib.escapeShellArg []
"''"
nix-repl> lib.escapeShellArgs []
""
```

**Comment by Smaug123** [comment]
🤦 I even checked the implementation of `lib.escapeShellArg` and discovered that it's secretly a function `'a -> string` rather than `string -> string` as documented, and didn't make the connection. I clearly need to go to sleep.
