### ISSUE TITLE
sway unset LD_LIBRARY_PATH if this var is not exposed at build-time

### ISSUE THREAD

**Issue by ne-sted** [NixOS/nixpkgs#32755]
## Issue description

https://github.com/swaywm/sway/blob/master/CMakeLists.txt#L58:L60
https://github.com/swaywm/sway/blob/master/sway/main.c#L328:L332

Because of this i.e. `alacritty` does not work under `sway`.

### Steps to reproduce
```sh
~ printenv LD_LIBRARY_PATH # before sway
/run/opengl-driver/lib
~ sway
~ if [ -z ${LD_LIBRARY_PATH} ]; then echo "var is unset"; fi # under sway
var is unset
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.11.0, NixOS, 18.03pre122666.afe9649210c (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre122666.afe9649210c"`
 - channels(ne-sted): `"nixos-18.03pre122691.ea15e436939"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ne-sted** [comment]
@gnidorah could you please take a look?

**Comment by gnidorah** [comment]
@ne-sted 
Also
https://github.com/swaywm/sway/blob/master/sway/sway-security.7.txt#L30
https://github.com/hwoarang/uClibc/blob/master-metag/ldso/man/ld.so.8#L19 (our sway module uses setuid wrapper)
I can't figure anything smarter than just https://github.com/gnidorah/nixpkgs/commit/822e78927d0e6e16ba5b849bd45b6b1f1c618175. Will go as part of https://github.com/NixOS/nixpkgs/pull/32285
/cc @primeos
