### ISSUE TITLE
docker_27 update (27.0.2 -> 27.0.3) only includes cli hash, not moby package

### ISSUE THREAD

**Issue by guoard** [NixOS/nixpkgs#327692]
### Describe the bug
In this [PR](https://github.com/NixOS/nixpkgs/pull/324194), the docker_27 version was updated from `27.0.2` to `27.0.3`, but only the hash of the CLI was updated, not the `moby` package.

How was this built? The hash for the `moby` version `27.0.3` should be `sha256-xinRILDSuubAAJh/dmpaU3csTf0VgukJIfSUkcHpa28=`.

### Expected behavior
The value of the `mobyHash` variable in `docker_27` should be updated.

### Additional context
Here's how I installed Docker in my `/etc/nixos/configuration.nix` file:

```nix
  virtualisation.docker = {
    enable = true;
    package = unstable.docker_27;
    liveRestore = false;
  };
```

I'm not sure if it's relevant, but when I run the `docker info` command, I see this output:

```bash
Client:
 Version:    27.0.2

Server:
 Server Version: 27.0.3
```

This is odd because it should be the other way around!

### Notify maintainers
@offline
@vdemeester
@periklis
@teutat3s

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

- system: `"x86_64-linux"`
- host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.2780.53e81e790209`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.4`
- channels(root): `"nixos-24.05, unstable"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
> How was this built?

It's to do with how FODs work in nix and nixpkgs; this would be ultimately looked at in some PRs. But we should also have the update script corrected (r-ryantm is an update bot).
