### ISSUE TITLE
`services.gitlab`: Allow using `services.gitlab.registry` without specifying certificate

### ISSUE THREAD

**Issue by Chaostheorie** [NixOS/nixpkgs#327635]
### Describe the bug

The current NixOS module for GitLab, available under `services.gitlab`, requires one to specify an SSL certificate for GitLab's container registry.

This doesn't reflect GitLab's own configuration, to the extent that the registry can be configured without HTTPS.

This is specifically a problem when one tries to serve a GitLab registry behind a TLS-terminating reverse proxy.
Such a setup is IME rather common when running GitLab + GitLab registry on a single server behind, e.g., NGINX.

### Steps To Reproduce
1. Enable GitLab and specifically the registry: `services.gitlab.registry.enable`
2. Observe that checks will fail because `services.gitlab.registry.{issuer,certFile,keyFile}` are used and not optional

### Expected behavior

Make `services.gitlab.registry.{issuer,certFile,keyFile}` optional with `lib.types.nullOr` and default as `null`.
Afterward, adjust GitLab module to:
1. skip creating service for setting file permissions for registry certificates and
2. Adjust checks to reflect the new requirement set

It should be noted that specifying any of `services.gitlab.registry.{issuer,certFile,keyFile}` probably should require all of them.

### Notify maintainers

Pinging members of GitLab team based on `meta.maintainers`:
@globin @krav @talyz @yayayayaka 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Chaostheorie** [comment]
I seem to have misunderstood the use of keyFile and certFile.

**Comment by purefan** [comment]
@Chaostheorie I am having problems setting up my gitlab-registry with NixOS and perhaps I too am confused about the use of keyFile and certFile, would you please share your config if you got it working? I just posted [this question](https://discourse.nixos.org/t/gitlab-registry-and-certfile/54947) on discourse. I am trying to set up gitlab + gitlab registry behind nginx and only gitlab registry is failing me right now
