### ISSUE TITLE
gnutls-3.6.1 checks fail on CentOS 7

### ISSUE THREAD

**Issue by dylex** [NixOS/nixpkgs#32767]
## Issue description

The `p11-kit-trust.sh` test fails because it finds the wrong (system) `p11-kit-trust.so` (it's hard-coded to look in various places but not the right `p11_kit` dependency):

```
located /usr/lib64/pkcs11//p11-kit-trust.so
/dev/shm/gnutls-3.6.1/src/.libs/lt-p11tool: Relink `/mnt/home/sw/nix/store/bn7mlvf2ri8790a9ig5c4pqbvjg07vsr-autogen-5.18.12-lib/lib/libopts.so.25' with `/mnt/home/sw/nix/store/r29bw2xi7gsb59q98blc4pmcl1hw1h58-glibc-2.26-75/lib/libpthread.so.0' for IFUNC symbol `system'
p11-kit: couldn't load module: /usr/lib64/pkcs11//p11-kit-trust.so: libfreebl3.so: cannot open shared object file: No such file or directory
pkcs11_add_provider: PKCS #11 initialization error.
/dev/shm/gnutls-3.6.1/src/.libs/lt-p11tool: Relink `/mnt/home/sw/nix/store/bn7mlvf2ri8790a9ig5c4pqbvjg07vsr-autogen-5.18.12-lib/lib/libopts.so.25' with `/mnt/home/sw/nix/store/r29bw2xi7gsb59q98blc4pmcl1hw1h58-glibc-2.26-75/lib/libpthread.so.0' for IFUNC symbol `system'
p11-kit: couldn't load module: /usr/lib64/pkcs11//p11-kit-trust.so: libfreebl3.so: cannot open shared object file: No such file or directory
pkcs11_add_provider: PKCS #11 initialization error.
Exporting failed (1)
FAIL p11-kit-trust.sh (exit status: 1)
```

### Steps to reproduce

Build gnutls on CentOS7 with `p11-kit-trust` rpm installed.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-693.5.2.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`

**Comment by vcunat** [comment]
Well, if you used sandboxing (like you claim i details), the package wouldn't see `/usr/**` paths.

**Comment by dylex** [comment]
Interesting, yeah, I'm **not** using sandboxing. I'm not sure why nix-info thinks I am.
