### ISSUE TITLE
hunspell support for german spelling

### ISSUE THREAD

**Issue by mboujong** [NixOS/nixpkgs#32777]
## Issue description

modify nixpkgs/pkgs/development/libraries/hunspell/dictionaries.nix

add mkDictFromGitHub
add de-de

### Steps to reproduce

mkDictFromGitHub =
    { shortName, srcs, shortDescription, longDescription, dictFileName }:
    stdenv.mkDerivation rec {
      name = "hunspell-dict-${shortName}-wooorm-${version}";
      version = "20161207";

      inherit srcs;

      phases = ["unpackPhase" "installPhase"];
      sourceRoot = ".";
      # Copy files stripping until first dash (path and hash)
      unpackCmd = "cp $curSrc \${curSrc##*-}";
      installPhase = ''
        # hunspell dicts
        install -dm755 "$out/share/hunspell"
        install -m644 ${dictFileName}.dic "$out/share/hunspell/"
        install -m644 ${dictFileName}.aff "$out/share/hunspell/"
        # myspell dicts symlinks
        install -dm755 "$out/share/myspell/dicts"
        ln -sv "$out/share/hunspell/${dictFileName}.dic" "$out/share/myspell/dicts/"
        ln -sv "$out/share/hunspell/${dictFileName}.aff" "$out/share/myspell/dicts/"
      '';

  de-de = mkDictFromGitHub {
    shortName = "de-de";
	dictFileName = "de_DE";
    	shortDescription = "German";
	longDescription = ''Korrektur der Rechtschreibung für deutsche Sprache'';
    srcs = [
      (fetchurl {
        url = "https://github.com/wooorm/dictionaries/blob/master/dictionaries/de/index.aff";
        sha256 = "c8e3160dc0cedd0f17c2a0d02644a7042ef30e73e8b86e37d8cbb7f55e7e5c4a";
      })
      (fetchurl {
        url = "https://github.com/wooorm/dictionaries/blob/master/dictionaries/de/index.dic";
        sha256 = "b35f89c991e3dfb81ca7bb38f88ab6f02cb9cf7a226cfc424abc0e06502fb287";
      })
    ];

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2378.af7e47921c4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(marc): `""`
 - channels(root): `"nixos-17.09.2378.af7e47921c4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
The dictionaries seem to come from here: https://www.j3e.de/ispell/igerman98/index_en.html

They can be built from source using the following expression but `ispell` needs to be packaged for `buildhash` command

```
--- a/pkgs/development/libraries/hunspell/dictionaries.nix
+++ b/pkgs/development/libraries/hunspell/dictionaries.nix
@@ -1,6 +1,6 @@
 /* hunspell dictionaries */
 
-{ stdenv, fetchurl, fetchFromGitHub, unzip, coreutils, bash, which, zip }:
+{ stdenv, fetchurl, fetchFromGitHub, unzip, coreutils, bash, which, zip, ispell }:
 
 
 let
@@ -168,8 +168,63 @@
       };
     };
 
+  mkDictFromJ3e =
+    { shortName, shortDescription, dictFileName }:
+    stdenv.mkDerivation rec {
+      name = "hunspell-dict-${shortName}-j3e-${version}";
+      version = "20161207";
+
+      src = fetchurl {
+        url = "https://j3e.de/ispell/igerman98/dict/igerman98-${version}.tar.bz2";
+        sha256 = "1a3055hp2bc4q4nlg3gmg0147p3a1zlfnc65xiv2v9pyql1nya8p";
+      };
+
+      buildInputs = [ ispell ];
+
+      phases = ["unpackPhase" "installPhase"];
+      installPhase = ''
+        make hunspell/${dictFileName}.aff hunspell/${dictFileName}.dic
+        # hunspell dicts
+        install -dm755 "$out/share/hunspell"
+        install -m644 hunspell/${dictFileName}.dic "$out/share/hunspell/"
+        install -m644 hunspell/${dictFileName}.aff "$out/share/hunspell/"
+        # myspell dicts symlinks
+        install -dm755 "$out/share/myspell/dicts"
+        ln -sv "$out/share/hunspell/${dictFileName}.dic" "$out/share/myspell/dicts/"
+        ln -sv "$out/share/hunspell/${dictFileName}.aff" "$out/share/myspell/dicts/"
+      '';
+
+      meta = with stdenv.lib; {
+        homepage = https://www.j3e.de/ispell/igerman98/index_en.html;
+        description = shortDescription;
+        license = with licenses; [ gpl2 gpl3 ];
+        maintainers = with maintainers; [ mboujong ];
+        platforms = platforms.all;
+      };
+    };
+
 in {
 
+  /* GERMAN */
+
+  de-de = mkDictFromJ3e {
+    shortName = "de-de";
+    shortDescription = "German (Germany)";
+    dictFileName = "de_DE";
+  };
+
+  de-at = mkDictFromJ3e {
+    shortName = "de-at";
+    shortDescription = "German (Austria)";
+    dictFileName = "de_AT";
+  };
+
+  de-ch = mkDictFromJ3e {
+    shortName = "de-ch";
+    shortDescription = "German (Switzerland)";
+    dictFileName = "de_CH";
+  };
+
   /* ENGLISH */
 
   en-us = mkDictFromWordlist {
```

**Comment by mboujong** [comment]
Thanks for your additions.

Greeting mboujong

**Comment by timor** [comment]
Is there a PR for this somewhere?

**Comment by jtojnar** [comment]
No, feel free to open it.
