### ISSUE TITLE
raylib: Audio doesn't work on Linux

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#327747]
### Describe the bug
When using an application built against the raylib library on Linux, audio doesn't work.

### Steps To Reproduce
1. `nix shell nixpkgs#raylib-games`
2. `wave_collector`

### Expected behavior
When playing the game there should be audio. 

### Additional context
The game logs the following to the terminal, indicating it was unable to initialize the audio device:

```
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / Null
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   44100 -> 44100
INFO:     > Periods size:  1323
```

I played `wave_collector` with a patched version of raylib to confirm that the game does indeed feature audio. 

The audio patch was removed in #284378

### Notify maintainers

@adamlwgriffiths

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.11 (Vicuna), 24.11.20240701.c5bcace`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/d3bbbbb6sicylbivzzv5lw74xsrk0wyw-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamlwgriffiths** [comment]
Hey Emmanuel,
Unfortunately I don't have any time to act as maintainer for Nix at the moment or in the foreseeable future.

**Comment by emmanuelrosa** [comment]
OK, no problem @adamlwgriffiths 

The solution is known, but the question is whether anyone else can reproduce this.
For what it's worh, I had the same issue with a non-raylib application which uses miniaudio.
