### ISSUE TITLE
Package request: toolong

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#327706]
**Project description**

A terminal application to view, tail, merge, and search log files (plus JSONL). 

**Metadata**

* homepage URL: https://github.com/Textualize/toolong
* source URL: https://github.com/Textualize/toolong
* license: MIT
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/327803
