### ISSUE TITLE
Package request: no-more-secrets

### ISSUE THREAD

**Issue by bonds** [NixOS/nixpkgs#327709]
**Project description**

A command line tool that recreates the famous data decryption effect seen in the 1992 movie Sneakers. 

**Metadata**

* homepage URL: https://github.com/bartobri/no-more-secrets
* source URL: https://github.com/bartobri/no-more-secrets
* license: GPL 3.0
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
@bonds it's already in Nixpkgs:

https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/misc/nms/default.nix#L19

https://search.nixos.org/packages?type=packages&query=nms

**Comment by bonds** [comment]
Awesome, thanks for letting me know! Sorry for the SPAM then. I searched the packages using 'no-more-secrets' and 'nomoresecrets' and 'libnms' but someone didn't think to try nms. :|

**Comment by matteo-pacini** [comment]
@bonds Did the same actually, and could not find it  😅 - glad to help!
