### ISSUE TITLE
Package request: krdpserver

### ISSUE THREAD

**Issue by LeaderbotX400** [NixOS/nixpkgs#327717]
**Project description**

RDP server by the KDE team that ties in nicely to Plasma 6

**Metadata**

* homepage URL: https://invent.kde.org/plasma/krdp
* source URL: https://github.com/KDE/krdp
* license: BSD-2-Clause
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qwqawawow** [comment]
There is [unstable channel](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=krdp)
`nix shell  nixpkgs#kdePackages.krdp -c krdpserver --help`
