### ISSUE TITLE
`ModuleNotFoundError: No module named 'asyncore'` when using auto-cpufreq

### ISSUE THREAD

**Issue by sukhmancs** [NixOS/nixpkgs#327754]
### Describe the bug
When using `auto-cpufreq`, an error occurs: `ModuleNotFoundError: No module named 'asyncore'`.

### Steps To Reproduce
1. Enable `auto-cpufreq`

### Expected behavior
The `auto-cpufreq` tool should run without any errors, and the `asyncore` module should be found and used properly.

### Additional context
Additional logs: https://privatebin.net/?86b146232ad1c856#HJJ6dFyoQm3UosFftGsJZEFZt9AgFxiagDkMxdD4dvHy

### Notify maintainers
@adamlwgriffiths 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9, NixOS, 24.11 (Vicuna), 24.11.20240712.7e7c39e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.22.0pre20240705_1b14f2e`
 - nixpkgs: `/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source`
```

**Comment by eclairevoyant** [comment]
#325685

**Comment by sukhmancs** [comment]
This does not resolve the issue. Auto-cpufreq is still producing the same error, even after I updated the inputs.

**Comment by eclairevoyant** [comment]
You have to wait for the branch to advance, see nixpk.gs to know when it does
