### ISSUE TITLE
Installing fish and atuin via Nix on macOS - unknown command error when starting fish or running any commands

### ISSUE THREAD

**Issue by victorhooi** [NixOS/nixpkgs#327750]
### Describe the bug
I've installed `atuin` and `fish` on my macOS machine via Nix - and I'm struggling with what seems to be some kind of path issue when I try to set `fish` as the default shell via `chsh`.

Every time I open up the shell, or try to run a command - I get around 20 lines printed about `atuin` being an unknown command.

I'm completely at wits end on how to solve this =(.

### Steps To Reproduce
1. Using the Nix templates from [here](https://github.com/dustinlyons/nixos-config) - this uses nix-darwin and home-manager. (I'm a Nix newbie).
2. Install fish and atuin, by adding the respective stanzas to my home-manager configuration. (Gist of my home-manager configurations - [here](https://gist.github.com/victorhooi/0b5afaf207532c1c067437bb8d329d55) and [here](https://gist.github.com/victorhooi/ffd1ecbf3f9093c2b97307db720cdeb1) - the first link is the one with fish/atuin defined).
3. Run `nix run ./#build-switch` (should be [this script](https://github.com/dustinlyons/nixos-config/blob/main/apps/aarch64-darwin/build-switch
4. Add `/Users/foobar/.nix-profile/bin/fish` to `/etc/shells`
5. Call `chsh -s /Users/foobar/.nix-profile/bin/fish` to set fish as the default shell
6. Open up a new macOS Terminal window, with fish as the default shell

As soon as the terminal opens, you get an error message like this:

```
Last login: Tue Jul 16 22:17:15 on ttys004
fish: Unknown command: atuin
- (line 1): 
atuin uuid
^~~~^
in command substitution
	called on line 1 of file -
from sourcing file -
	called on line 43 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
- (line 1): Unknown command
set -gx ATUIN_SESSION (atuin uuid)
                      ^~~~~~~~~~~^
from sourcing file -
	called on line 43 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```
Also, each time you run a command at the shell - the same error lines get printed.

The errors occur when `fish` is set to the default shell (via chsh).

If `zsh` (default shell in macOS) is set as the default shell - you don't get these errors.

Here is the PATH for `zsh`, when `zsh` is the default shell.

```
❯ env | grep SHELL
SHELL=/bin/zsh
STARSHIP_SHELL=zsh

~ 
❯ env | grep PATH
PATH=/Users/foobar/.local/share/bin:/Users/foobar/.npm-packages/bin:/Users/foobar/bin:/Users/foobar/.pnpm-packages/bin:/Users/foobar/.pnpm-packages:/Users/foobar/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/opt/puppetlabs/bin
```

And then if you invoke fish from within zsh - no errors - here is the path then:

```
❯ env | grep PATH
PATH=/Users/foobar/.local/share/bin:/Users/foobar/.npm-packages/bin:/Users/foobar/bin:/Users/foobar/.pnpm-packages/bin:/Users/foobar/.pnpm-packages:/Users/foobar/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/opt/puppetlabs/bin
```

Here is the path when `fish` is the default shell (which is when the errors occur):
```
PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/opt/puppetlabs/bin:/Applications/Wireshark.app/Contents/MacOS
```

### Expected behavior
When opening up the fish shell, there should not be any error messages about atuin being an unknown command

### Additional context
I also tried to ask for help on home-manager, and on r/NixOS - 

https://github.com/nix-community/home-manager/issues/5486
https://www.reddit.com/r/NixOS/comments/1d6u9xr/cant_setup_fish_and_atuin_via_homemanager_on/

However, it's possible I didn't ask in the right way, or missed something - as 

### Notify maintainers

@adamcstephens @cole-h @happysalada @r-ryantm @afh @Sigmanificient @wegank @Lurkki14 @hmajid2301 @natsukium @pbsds @msladecek @pyrox0 @pSub @mfrw @quantenzitrone @stuebinm @0x4A6F @martinetd @chewblacka @Ma27 @RaitoBezarius @devusb @h7x4 @pennae 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
error:
       … while calling the 'import' builtin
         at «string»:1:18:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at «string»:1:25:
            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

~ 
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
You're missing the Nix paths in your fish env. e.g. `/Users/foobar/.nix-profile/bin:/nix/var/nix/profiles/default/bin`

**Comment by victorhooi** [comment]
@adamcstephens Thanks for the tip - I confess I'm still super confused on the correct way to handle this in Nix though.

My naive assumption was that as fish was installed via Nix - it would have done something to setup the paths correctly. Is that an incorrect assumption?

If so, what would be the correct way of setting this then, in a Nix-managed system on macOS?

I believe the ~/.config/fish/config.fish file is auto-generated by home-mananger - so I can't do it there.

And as well as where to set it - what should I set that path to?

I did see this at the top of my .zshrc:
```
if [[ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  . /nix/var/nix/profiles/default/etc/profile.d/nix.sh
fi
```
so is the idea that I somehow source the `/nix/var/nix/profiles/default/etc/profile.d/nix.fish` file? (Out of curiosity - what puts that file there, and manages that file?)

I also tried googling, which led me to threads like [this](https://github.com/LnL7/nix-darwin/issues/122) - but reading through those just confused me even more =(...

Or I found packages like [this](https://github.com/lilyball/nix-env.fish) - but not sure if that's required?

And the Nix [wiki page for fish shell](https://nixos.wiki/wiki/Fish) doesn't mention anything about setting the path.

**Comment by adamcstephens** [comment]
> so is the idea that I somehow source the `/nix/var/nix/profiles/default/etc/profile.d/nix.fish` file? (Out of curiosity - what puts that file there, and manages that file?)

yep! exactly. :) I do this [explicitly](https://codeberg.org/adamcstephens/dotfiles/src/commit/e14f35f6e9a9cb9174016948c512c0db364e0dec/apps/fish/init.fish#L10-L12) in my config. 

I suspect that the profile `/nix/var/nix/profiles/default/` comes from the installer based on its contents (just nix).
