### ISSUE TITLE
Channels for versions below 15.09 are broken

### ISSUE THREAD

**Issue by sevcsik** [NixOS/nixpkgs#32784]
## Issue description

Channels for 13.10, 14.04, 14.12 return 404 with a CloudFlare error page.

### Steps to reproduce

Go to https://nixos.org/channels/
Try to download the versions mentioned in the description.

## Technical details

n/a

**Comment by copumpkin** [comment]
cc @edolstra

**Comment by vcunat** [comment]
To be clear, one needs really good reasons to use that much old channels.  For now you can use branches from https://github.com/nixos/nixpkgs-channels &ndash; binaries themselves should be still obtainable from the cache automatically.

**Comment by orivej** [comment]
For the record @sevcsik tried the old channels to upgrade from 14.04 to unstable: https://botbot.me/freenode/nixos/2017-12-18/?msg=94772225

**Comment by sevcsik** [comment]
Yes, unfortunately RamNode ships a 14.04 ISO only, and this made it was a bit baffling to me as a newcomer why `nix-channel --update` didn't work, as it failed with a rather cryptic error.

**Comment by c0bw3b** [comment]
Closing, by now those channels are _really_ outdated
