### ISSUE TITLE
NSS version is too old for steam

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#32781]
## Issue description

I have just updated to NixOS 17.09 commit 29dc5c1851a1e7a76450024e183d29154b187432. After the update I found out that all browser based tabs in steam don't work. This error message is printed:

```
[1218/015939.018445:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
```

A quick grep in nixpkgs shows that steam runtime is using libnss 3.19.2. So that might be the cause of the problem.

### Steps to reproduce

Install NixOS commit 29dc5c1851a1e7a76450024e183d29154b187432. Run steam. Open STORE or COMMUNITY tab.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 17.09.git.29dc5c1 (Hummingbird)`

**Comment by yegortimoshenko** [comment]
The solution is in https://github.com/NixOS/nixpkgs/issues/32687#issuecomment-352141355. Sorry for not getting to that earlier.

**Comment by sorokin** [comment]
I tried your patch and can confirm that it fixes the issue.
