### ISSUE TITLE
Build failure: zerotierone

### ISSUE THREAD

**Issue by Herschenglime** [NixOS/nixpkgs#327834]
### Steps To Reproduce

1. build *zerotierone* 1.14.0

### Build log

The build process spits out a ton of compiler warnings, but as far as I can tell the actual issue is from the following:
```
error: failed to get `serde` as a dependency of package `smeeclient v0.1.0 (/build/source/rustybits/smeeclient)`

Caused by:
  failed to load source for dependency `serde`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to update replaced source registry `crates-io`

Caused by:
  failed to parse manifest at `/build/cargo-vendor-dir/windows_i686_gnu-0.52.4/Cargo.toml`

Caused by:
  virtual manifests must be configured with [workspace]
make: *** [make-linux.mk:441: zeroidc] Error 101
make: *** Waiting for unfinished jobs....
```

A full gist can be found here: https://gist.github.com/Herschenglime/cfb66d846838af3797970becf2034b52

### Additional context

I'm not super comfortable with rust so I'm not sure where the error is coming from, but I'm at least pretty sure that this wasn't an issue on nixos 23.11 before I upgraded to 24.05.

### Notify maintainers

@sjmackenzie 
@zimbatm 
@ehmry 
@obadz 
@danielfullmer 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.05 (Uakari), 24.05.20240619.dd457de`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by applePrincess** [comment]
I think this is fixed by #335676. And I can build zerotierone on the current HEAD(2becde3c1913fc74dec4108a067bfb5f5b93096b)
