### ISSUE TITLE
wechat-uos: cannot launch: Segmentation fault

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#327860]
### Describe the bug
Segmentation fault prevents `wechat-uos` from launching.

### Steps To Reproduce
1. Install wechat-uos from master branch
2. Run command `wechat-uos`

```
[0717/011423.570562:ERROR:directory_reader_posix.cc(42)] opendir /home/ulysses/.xwechat/crashinfo/attachments/87ea53f2-53b6-4bcd-9fd8-2b455a4eb49d: No such file or directory (2)
/nix/store/b8j5hyg6pwa0ww3c48lamw2k3ayv6d87-wechat-uos-launcher: line 14:  6973 Segmentation fault      (core dumped) /nix/store/5jklq1cc6pskky719gh0f64sz9nlafwj-wechat-uos-1.0.0.241/opt/apps/com.tencent.wechat/files/wechat
```

### Expected behavior
WeChat launches.

### Additional context
1d2d850e works, so it is NOT #309435 that broke the package.

### Notify maintainers

@pokon548 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.97, NixOS, 24.05 (Uakari), 24.05.2580.194846768975`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Guanran928** [comment]
https://matrix.to/#/!cacbMwUwsLZ6GKac:nichi.co/$g614RgC4xlu3GtyIPmf1mCBe0VEZmQwt-EKSq1Rj3rw?via=nixos.org&via=nichi.co&via=matrix.org

Seems to be caused by missing `libxcb-icccm.so.4`

**Comment by Cryolitia** [comment]
I can determine that 655a58a72a6601292512670343087c2d75d859c1 is bad and  00d80d13810dbfea8ab4ed1009b09100cca86ba8 is good.

Since there is a Python package build failure between these two commits, bisect is almost impossible.

`strace` result seems to not support missing `libxcb-icccm.so.4`

coredump backtrace:

```
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex-base.S:81
No locals.
#1  0x000063592f4f027c in ?? ()
No symbol table info available.
#2  0x000063592f4f2c56 in ?? ()
No symbol table info available.
#3  0x000063592f4f92b9 in ?? ()
No symbol table info available.
#4  0x000063592f1f1ce3 in ?? ()
No symbol table info available.
#5  0x000063592f1f32f5 in ?? ()
No symbol table info available.
#6  0x000063592efedeb6 in ?? ()
No symbol table info available.
#7  0x000063592edbcf33 in ?? ()
No symbol table info available.
#8  0x00007b2fa5c74a42 in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {135443649660608, -4459628139538850994, -1176, 
                0, 135443660137296, 135444594868224, 3765830529785748302, 3765990445290052430}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007b2fa5cf405c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.
```

**Comment by Cryolitia** [comment]
After building for days, I can now determine, it is #316761 that broken wechat-uos. The last commit that could run on master is ecefb310fea47a3373349139c7c4fc50ec21c82e

![image](https://github.com/user-attachments/assets/4d9ae629-b6c3-4b8a-9459-5536a4953ac0)

Also CC @xddxdd
