### ISSUE TITLE
please update nikola

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32797]
## Issue description

The nikola version in 17.09 has a bug that makes it unusable.

Please backport v7.8.10!

/cc @FRidh

**Comment by FRidh** [comment]
That's for the package maintainer.
cc @jluttine

**Comment by FRidh** [comment]
@davidak Even better, you can open a PR yourself.

**Comment by jluttine** [comment]
I don't know how to backport stuff from unstable to stable, I just use unstable..

**Comment by davidak** [comment]
I also havn't done this but looked into the documentation.

https://nixos.org/nixpkgs/manual/#idm140737317027664

@jluttine do you want to try it? Else i can try it this evening.

**Comment by jluttine** [comment]
Thanks for the link. I can't do it right now, at some point I could look into it, but please feel free to do it yourself.
