### ISSUE TITLE
Update request: fakeroot 1.29 → 1.35.1

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#327931]
- Package name: fakeroot
- Latest released version: 1.35.1

- Current version on the unstable channel: 1.29
- Current version on the stable/release channel: 1.29

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

https://github.com/NixOS/nixpkgs/pull/271462 updates to 1.32.2 but appears to be stalled.

The sources and patches for 1.29 do not exist anymore.

**Notify maintainers**
@viric 
@Trundle 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
Might be relevant:
- https://github.com/NixOS/nixpkgs/pull/271462
