### ISSUE TITLE
atom: problems with git integration

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32794]
## Issue description

I tried to push with the integrated git features but got this error:

```
linux-ssh: Linux ssh wrapper invoked with arguments: [git@github.com
/tmp/github-1171118-31016-1gkey41.4oge8hyqfr/linux-ssh-wrapper.sh: line 20: /nix/store/b8z56lybj4xrxmplgfdhvvgfqv2nbw8g-atom-1.23.1/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git: No such file or directory
linux-ssh: using SSH command [ssh]
fatal: cannot run pack-objects: No such file or directory
fatal: git pack-objects failed: No such file or directory

```
### Steps to reproduce

1. install `atom`
1. open Folder with git repository
1. make some changes, commit and try to push
1. instead of pushing, you get this error

## Technical details

 - Atom: 1.12.1
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 18.03.git.2c5c48e (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jboesl** [comment]
Got the same issue here.
