### ISSUE TITLE
Convert remaining GNOME packages to meson

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#32803]
https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting

Porting package usually consists of:
1. Adding `meson` and `ninja` to `nativeBuildInputs`
2. Removing old build system (for autotools, it would be `autoreconfHook`, `autoconf`, `automake`, `libtool`)
3. Convert `configureFlags` and `makeFlags` to `mesonFlags` (`--enable-foo` usually corresponds to `-Dfoo=true` but you should check `meson_options.txt` in the root of the project)
4. Meson discourages magic dependency detection (i.e. `--enable-foo=auto`), you might need to add some dependencies that were forgotten previously.
5. Some packages might need patching shebangs in install scripts ([example](https://github.com/NixOS/nixpkgs/blob/5de6ee22d1286b8b87b8dae56a1310f4b43af81e/pkgs/desktops/gnome-3/core/gnome-bluetooth/default.nix#L21-L24))

Taken from #29392

+ [x] ~~gnome-color-manager~~ (not packaged)
+ [x] ~~gnome-screenshot~~ (only unstable 3.25 available)
+ [x] ~~geocode-glib~~ (only unstable 3.25 available)
+ [ ] ~~gom~~ aka GObject Data Mapper (not packaged)
+ [ ] ~~graphene~~ (not packaged)
+ [x] ~~gnome-todo~~ (not packaged)
+ [ ] ~~gnome-multi-writer~~ (not packaged)
+ [x] ~~jsonrpc-glib~~ (not packaged)
+ [x] ~~libdazzle~~ (not packaged)
+ [x] ~~gnome-builder~~ (not packaged)
+ [ ] ~~gnome-recipes~~ (not packaged)
* [x] atk (still supports autotools)
* [ ] clutter-gtk (still supports autotools)
* [x] gdk-pixbuf (still supports autotools)
* [x] gstreamer (still supports autotools)
* [x] gst-plugins-bad (still supports autotools)
* [x] gst-plugins-base (still supports autotools)
* [x] gst-plugins-good (still supports autotools)
* [ ] gtk+ (still supports autotools)
* [ ] pango (still supports autotools)
* [x] gnome-backgrounds (still supports autotools)
* [x] shotwell

**Comment by Anton-Latukha** [comment]
Many Mason-able GNOME packages have this build error:
```
building '/nix/store/drvand8lzj2smwvbz4nb0jhirrq204yb-grilo-0.3.4.drv'...
unpacking sources
unpacking source archive /nix/store/dxf5khhs9yybqg02pffaxxpl9nx9qp32-grilo-0.3.4.tar.xz
source root is grilo-0.3.4
setting SOURCE_DATE_EPOCH to timestamp 1503589772 of file grilo-0.3.4/AUTHORS
patching sources
configuring
meson flags: --buildtype=release         --libdir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/lib --libexecdir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/libexec         --bindir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/bin --sbindir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/sbin         --includedir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/include         --mandir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/share/man --infodir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/share/info         --localedir=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4/share/locale         --prefix=/nix/store/cwjw59ivvx4x73cc3ca1sswlbzn1s8y8-grilo-0.3.4
Error during basic setup:

Neither directory contains a build file meson.build.
builder for '/nix/store/drvand8lzj2smwvbz4nb0jhirrq204yb-grilo-0.3.4.drv' failed with exit code 1
```

**Comment by Anton-Latukha** [comment]
So far I ported:
- [x] `at-spi2-atk`
- [x] `at-spi2-core`
- [x] `clutter-gtk`

In https://github.com/NixOS/nixpkgs/pull/41365.

**Comment by jtojnar** [comment]
Updated in https://github.com/NixOS/nixpkgs/pull/45950, thanks.
