### ISSUE TITLE
Package pipewire

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#32805]
Initial work is [done](https://github.com/jtojnar/nixpkgs/tree/pipewire) but it still needs to be tested somehow.

**Comment by etu** [comment]
I'm a bit unsure of what pipewire is, when reading about it it seems really abstract. But is it really needed to get gnome to run on wayland?

**Comment by jtojnar** [comment]
It is required for things like remote desktop or screen recording.
