### ISSUE TITLE
Build failure: python3Packages.langchain, langchain-core, etc. builds don't match the version number

### ISSUE THREAD

**Issue by sarahec** [NixOS/nixpkgs#328033]
[langchain](https://github.com/langchain-ai/langchain) is used to build generative AI clients. It contains a large number of components each of which is released on its own cadence. This means that some components have higher version numbers than others at a given time.

But an error in the last set of commits has set these all to the [the same version](https://search.nixos.org/packages?channel=unstable&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%22python312Packages%22%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=relevance&type=packages&query=langchain) >= the versions released since. 
This blocks updating the packages to their actual versions.

## How to reproduce

Compare the version numbers in source/Hydra (0.2.9) to the current releases below.

| Component | Listed release | Release built | Current release | Notes |
| --------- | ----------- | -------------------- | --------------- | ----- |
| langchain |  0.2.9 | 0.2.5 | 0.2.9 | cannot update to latest |
| langchain-community | 0.2.9 | 0.2.5 | 0.2.7 | cannot update to latest|
| langchain-text-splitters | 0.2.9 | 0.2.2 | 0.2.2 | mis-labeled, should revert |
| langchain-core | 0.2.9 | 0.2.9 | 0.2.20 | Can update | 
| langchain-chroma | 0.2.9 | 0.1.2 | 0.1.2 | mis-labeled, should revert |

## Root cause

The code is in a monorepo with individual releases for each specific component. Each release of the monorepo is tied to a specific component, for example, release `langchain==0.25` is used to build langchain; `langchain-core==0.29` to build langchain-core; etc. There's no way to sync these all to the same number, they are disparate releases by design. 

The last commits replaced the specific release checkout for each component with [langchain-core==0.29 release](https://github.com/langchain-ai/langchain/releases/tag/langchain-core%3D%3D0.2.9). This had the effect of inflating some version numbers without a corresponding release.

## Proposed solution

Revert the following commits:
* [python3Packages.langchain: 0.2.5 -> 0.2.9](https://github.com/NixOS/nixpkgs/commit/e48ecbdc286f21afd2a558216d393d4d239e3c5b)
* [python3Packages.langchain-community: 0.2.5 -> 0.2.9](https://github.com/NixOS/nixpkgs/commit/b1cf23fb33aba8972aa169febfca8a74f9044232)
* [python3Packages.langchain-text-splitters: 0.2.1 -> 0.2.9](https://github.com/NixOS/nixpkgs/commit/e53887a6b32c7bdc1f17d51bdad80c1f39394c96)
* [python3Packages.langchain-chroma: 0.1.1 -> 0.2.9](https://github.com/NixOS/nixpkgs/commit/13f08ccd518e99bdc6767c10e1f9df56dec5cd64)

Then bump the version numbers correctly on langchain (0.2.5 -> 0.2.9), langchain-community (0.2.5 -> 0.2.7), and langchain-core (0.2.9 -> 0.2.20).

I could submit a PR but I'm not sure about rolling versions back in Hydra and reverting commits in PRs.

### Notify maintainers

@mweinelt for patch reversion
@natsukium as listed maintainer

Note: I'm willing to join these as a maintainer. I'm also preparing to bring in `langgraph`

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[sec@dervish:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.11 (Vicuna), 24.11.20240709.feb2849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-23.05"`
 - channels(sec): `""`
 - nixpkgs: `/nix/store/xr9wjzx0cdnwkmhzz74h8lphgn5jmyv3-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
This was part of a bulk update of python packages, and the version was determined programatatically from the update script used for all Python packages.

I'll leave this with the maintainer.

**Comment by sarahec** [comment]
Thank you for the quick response.

**Comment by natsukium** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/328207
