### ISSUE TITLE
Migrate away from outdated vala versions

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#32800]
## Issue description

We currently have `vala_0_23`, `vala_0_26`,  `vala_0_26` and `vala_0_28` in our repository that are no longer maintained upstream.

The current versions maintained upstream are: `0.34.13`, `0.36.8` and `0.38.4`

related to #32795

**Comment by Mic92** [comment]
I talked with downstream and they recommend to set `0.38.4` as default vala version.

**Comment by jtojnar** [comment]
- `vala_0_23`:
    - [x] `ccnet`
    - [ ] `finalterm` also builds with 0.26, unmainained there is also a fork but it does not [build](https://github.com/jtojnar/nixpkgs/tree/finalterm)
    - [x] `giv`
    - [x] `gmpc`
    - [x] `libappindicator`
    - [x] `libindicate`
    - [x] `libosinfo`
    - [ ] `libunity` also builds with 0.26, hideously outdated
    - [ ] `midori` also builds with 0.34
    - [x] `seafile-shared`
    - [ ] `synapse` also builds with 0.34
- `vala_0_26`:
    - [ ] `vanubi` also builds with 0.28
- `vala_0_28`:
    - [x] `shotwell`
    - [x] `valum`
- `vala_0_34`:
    - [x] `deepin-terminal`
    - [x] `gencfsm`
    - [x] `libskk`

So now we have

* `vala_0_26`:
    * `finalterm`
    * `libunity`
* `vala_0_28`:
    * `vanubi`
* `vala_0_34`:
    * `midori`
    * `synapse`

allowing us to drop `vala_0_23`.

If we want to get rid of more, we can move all of them to `vala_0_26`.

**Comment by Mic92** [comment]
Is `libunity`still a thing? Did not ubuntu dropped `unity` development?

**Comment by jtojnar** [comment]
I do not know, the last update was [in 2012](https://launchpad.net/libunity/) and it does not seem to be used anywhere in nixpkgs, it is probably okay to drop it.

**Comment by Mic92** [comment]
I would say it is safe to do so.

**Comment by jtojnar** [comment]
Actually, why not just change  `finalterm` and `vanubi` to `vala_0_38` and mark them with `meta.broken = true`?
