### ISSUE TITLE
solvespace release-17.09

### ISSUE THREAD

**Issue by nickbeljaev** [NixOS/nixpkgs#32819]
## Issue description
Absent white char fild for numeric input

### Steps to reproduce
release-17.09
run solvespace
draw any object (for example select cirlcle from left panel or click c and grag left mouse)
set dim for it (select circle with left mouse then select distance/diametr from left panel or click d)
double left mouse on dim fild - must be open white fild with editable black char, but white fild absent - otherwise it works correctly - can be edited in blind.

## Technical details
As there are absent white fields of the drop-down menu, can be suggested that this is the same bug from gtk3 (solvespace gtk2 ver does not have such bugs)
If drag left mouse on fild it stay be normal (white fild black char), after rel left mouse fild stay black

system: "x86_64-linux", 
multi-user?: yes, 
version: nix-env (Nix) 1.11.15, 
channels(root): "nixos-17.09.2378.af7e47921c4", 
nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by jtojnar** [comment]
Works fine for me both on 0bb77b83e66b852c699db2522e6116c03450552d (nixos-17.09-small) and nixos-17.09 (af7e47921c4), both on Openbox and IceWM, using the config you [provided](https://github.com/NixOS/nixpkgs/pull/32651#issuecomment-352218885).

![screenshot from 2017-12-19 16-19-12](https://user-images.githubusercontent.com/705123/34163929-6a12f7b2-e4d8-11e7-9561-322611b97def.png)
![screenshot from 2017-12-19 16-24-33](https://user-images.githubusercontent.com/705123/34164242-514662ea-e4d9-11e7-900f-4b252982d011.png)

**Comment by nickbeljaev** [comment]
@jtojnar So there is some local cause in my system. I weel be think. Thank You for check.
![solvespace - new sketch _002](https://user-images.githubusercontent.com/32425481/34166733-b95047e0-e4f0-11e7-9f79-474bd3893651.png)

**Comment by nickbeljaev** [comment]
@jtojnar Not having good ideas I'm install new release-17.09 (from file https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.2378.af7e47921c4/nixos-minimal-17.09.2378.af7e47921c4-x86_64-linux.iso) in vbox, with solvespace in system configuration.nix. 
When load solvespace it work correct by it version was 2.1 (see screenshot), then check version nixos and it was 17.03 (see screenshot) but in configuration.nix set 17.09 (see screenshot). We see that using setup file 17.09 with 17.09 in configuration realy set 17.03. Please, check real version nixos in Your qemu, this important for my next steps.
![selection_003](https://user-images.githubusercontent.com/32425481/34171107-3f2cbc4c-e4fe-11e7-974e-705938bbf3e1.png)
![selection_004](https://user-images.githubusercontent.com/32425481/34171142-5e3ed110-e4fe-11e7-90f7-873d36f002a5.png)
![selection_005](https://user-images.githubusercontent.com/32425481/34171150-6872b0f2-e4fe-11e7-904e-a6b0c73d11b5.png)

**Comment by jtojnar** [comment]
I built the VM using `nixos-rebuild build-vm -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/af7e47921c481c3b1677e6b25755760a8ff9c411.tar.gz -I nixos-config=slvspac.nix` so it definitely is 17.09:

![screenshot from 2017-12-19 20-57-29](https://user-images.githubusercontent.com/705123/34176160-425bf6e8-e4ff-11e7-8db0-1bee978983df.png)

I am not familiar with the VirtualBox image, perhaps you need to update the system with `sudo nix-channel -u && sudo nix-env -u`.

**Comment by nickbeljaev** [comment]
@jtojnar Jan, please, do one more test - click open in Your solvespace. I got a clean 17.09 and it has a  solvespace 3.0 workload with a visible menu and white fields of sizes, but it suffers from an old error - it crashes on the clik File -> Open, check it out please.

PS Do You have an explanation why the prog installed in the clean 17.09 differs from the program installed exactly in 17.09 in which it was previously build from a local tree?
I come up with one explanation - some libraries are not reinstalled at the same time.

**Comment by jtojnar** [comment]
@nickbeljaev The fix is not yet in `nixos-17.09` so it will crash. You can see how old the channels are here: https://howoldis.herokuapp.com/. You can either wait for the channel build to complete or use `nixos-17.09-small` which already has the fix included.

Not sure what you mean by “installed exactly”.

**Comment by nickbeljaev** [comment]
I mean installed with eq procedure "nix-env -iA nixos.solvespace". My `English` supported with google and may be trrible. :) I weel read Your link tomorrow. Much needs to be understood.

**Comment by orivej** [comment]
@nickbeljaev I could have tried reproducing this in VirtualBox, but since you already did, could you share your image (VirtualBox > File > Export Appliance)?

**Comment by nickbeljaev** [comment]
@orivej You can [get](https://drive.google.com/open?id=1rVguG5hFtO2MYPbxs5HYLM7Ej7ddMnLX) it  user `nick` -> nopassw, `su` -> passwd `123`, this 17.03 maked from  17.09 setup This not reproduce at my home, I check 3 times that setup file was 17.09. This strange but not critical, maybe you should not waste time on it.
As for my adventures with the solvespace, I find why not the reproducibility of my situation. I'm build some programs from the master branch (it was silly - now I understand). So my system is something between 17.03 and unstable, surprising that the system has stability on the main points. I could not find a way to return the system to one of the standard branches without destroying, in January I will have time for a full reinstall. So far I'm using solvespsce2.3 (3.0 while not full working) with very much gratitude to its creators. I feel the same to the NixOs team :) I will definitely deal with the solvespace3.0 issue after I return the system to 17.09.

**Comment by nickbeljaev** [comment]
Hi, @orivej I'm reinstall nixos17.09 with format disk, today it's clear 17.09, but I see this issuse in default solvespace (black fild + black char instead white fild + black char). Have not idea whay this issuse not reproductive. Maybe it's in a cursed place :) I'm return to solvespace2x localy, it's enough.

**Comment by jtojnar** [comment]
@nickbeljaev
1. Is the crash from file chooser dialogue fixed?
2. Could you share the output of `nix-shell -p nix-info --run "nix-info -m"` of this sysetm?

**Comment by nickbeljaev** [comment]
Hi,@jtojnar
1. Yes, it was fixed in last year
2. Why `nix-shell -p nix-info --run "nix-info -m"` instead `nix-info -m`?
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2378.af7e47921c4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
It looks like you are using an old version of the channel, where the fix is not available yet. Could you update the channel `sudo nix-channel -u` before installing the solvespace program?

**Comment by nickbeljaev** [comment]
@jtojnar 
`# nix-channel --update` 
`$ nix-env -iA nixos.solvespace` 
`$ solvespace -> Segmentation fault`

**Comment by nickbeljaev** [comment]
@jtojnar 
After first try install default solvespace in clear system and reproductive issuse, I'm build solvespace2x from local tree because needs it. That in last experiment my system was not clear.

**Comment by nickbeljaev** [comment]
Hi, @jtojnar 
I'm rollback and realy update channel with nixos-rebuild (in last time I'm not implement nixos-rebuild, sorry)
now it's `17.09.2816.ae24fad5abf (Hummingbird)`
after `nix-env -iA nixos.solvespace` this issuse live.

**Comment by whitequark** [comment]
Maintainer of SolveSpace here. The menu issue *might* be a SolveSpace bug related to how its own OpenGL operations interact with GTK3 OpenGL rendering, but I could never track it down no matter how hard I tried. Could also be a GTK3 bug, though that's less likely. So this is not necessarily a packaging bug.
