### ISSUE TITLE
Carla package segfault

### ISSUE THREAD

**Issue by bendi-github** [NixOS/nixpkgs#328241]
### Describe the bug
When trying to run the `carla` executable from the carla package, it segfaults.

### Steps To Reproduce
1. `nix run nixpkgs#carla`

### Additional context
`strace`-ing the binary reveals that the segfault occurs when carla tries to create a directory inside the nix store
`mkdir("/nix/store/a7zdk1rdvc5a4sxpyhfpax794qy15kms-carla-2.5.8/share/carla/widgets/__pycache__", 0777) = -1 EROFS (Read-only file system)`

### Notify maintainers
@minijackson 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.11 (Vicuna), 24.11.20240716.ad0b5ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/70y8v9qfn34sdfsnwh3l9772lk4rpfiy-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
If you have the same segfault as me, this is most likely due to https://github.com/NixOS/nixpkgs/issues/326333, which is fixed by https://github.com/NixOS/nixpkgs/pull/325893, which hasn't reached `master` or `nixos-unstable`, yet.

Doing a `strace` of `nix run 'nixpkgs/master#carla'` on my system, I don't see the failing `mkdir`, but with GDB I can see that the segfault comes from PyQt 5.15.9 code.

Is that the same for you?

**Comment by bendi-github** [comment]
The backtrace I get with GDB matches the one in #326333, so I assume they are indeed related.

**Comment by eclairevoyant** [comment]
In that case you can check https://github.com/NixOS/nixpkgs/branch_commits/520ba7d7b118d7b59836573bc2e9fe55390c1cbc to see what branches contain the fix (currently only `staging` does).

**Comment by vale981** [comment]
@eclairevoyant did you mean:

https://nixpk.gs/pr-tracker.html?pr=325893

**Comment by doronbehar** [comment]
Closing as https://github.com/NixOS/nixpkgs/pull/325893 has reached branch `master`.
