### ISSUE TITLE
Why is the default docker version still at 24?

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#328275]
## Issue description

Today one of my containers wouldn't start after I updated the docker-compose file and it was due to the docker engine being too old to support a certain feature.

Easy enough to fix in config but is there a specific reason the `docker` attribute points at `docker_24` rather than `docker_27`?

Last time the attr was touched was https://github.com/NixOS/nixpkgs/commit/2318de70529d5b15293037943e470c1d77c4cb2c

@offlinehacker @vdemeester @periklis @teutat3s @otavio @guoard

**Comment by teutat3s** [comment]
The reason is basically this: https://github.com/moby/moby/pull/46772

Quoting a recent comment in that PR:
> Right now we're in the fun state where I, a Moby maintainer and Docker employee, don't even know which versions are actively "supported" which isn't a great state to be in.
