### ISSUE TITLE
firefly-iii-setup fails with incorrect cipher or incorrect key length

### ISSUE THREAD

**Issue by litchipi** [NixOS/nixpkgs#328395]
### Describe the bug

When installing firefly-iii on an empty system, the systemd service `firefly-iii-setup` fails, giving this error message:
```
 Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.
 at vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:62
    58▕
    59▕         if (! static::supported($key, $cipher)) {
    60▕             $ciphers = implode(', ', array_keys(self::$supportedCiphers));
    61▕
 ➜  62▕             throw new RuntimeException("Unsupported cipher or incorrect key length. Supported ciphers are: {$ciphers}.");
    63▕         }
    64▕
    65▕         $this->key = $key;
    66▕         $this->cipher = $cipher;
     +24 vendor frames
 25  app/Exceptions/Handler.php:208
     Illuminate\Auth\AuthManager::__call("check", [])
     +3 vendor frames
 29  artisan:35
     Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Steps To Reproduce
1. On a blank machine, configure
```
  services.firefly-iii = {
    enable = true;
    settings.APP_KEY_FILE = "/appkeyfile";
  };

  system.activationScripts.setup_keyfile = ''
    echo "mysecretpassword" > /appkeyfile
    chown firefly-iii:firefly-iii /appkeyfile
  '';
```
2. Boot the machine, the service `firefly-iii-setup` should appear failed

(Note that I encountered the bug originally when the `APP_KEY_FILE` already existed on the system before enabling firefly-iii, so I consider it out of cause of the bug)

I created a very simple debug bench for it, feel free to use it in order to reproduce the bug, or debug it.
Just run `nix run` on the branch `debug_firefly` of the repo https://github.com/litchipi/nixos-service-builder

### Expected behavior

Should succeed, and setup firefly-iii out of the box

### Notify maintainers

@savyajha 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.162, NixOS, 24.05 (Uakari), 24.05.20240714.53e81e7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/hkv63lvykwr520xf8yv2gcw3s78fjfpd-source`
```

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by savyajha** [comment]
@litchipi Can you retry this with the app key "TesTestTestTestTestTestTestTest"? Akaik it needs to be 32 characters.

**Comment by litchipi** [comment]
@savyajha Thank you for your quick answer to my stupid issue.
Couldn't this be worth a nix eval-time assertion ? I'm sure I'm not the only one who doesn't read properly the option descriptions

**Comment by savyajha** [comment]
The issue is that since the file is read at runtime and not at eval time that wouldn't work. However we can put in a runtime check, that's not too difficult. I'll put it in the next update whenever that happens.

Also, not a stupid issue at all. :)

**Comment by litchipi** [comment]
Ok, I leave it to your good hands then, thanks for the quick answer :smiley:
