### ISSUE TITLE
 libsForQt5.qtstyleplugin-kvantum provides no programs

### ISSUE THREAD

**Issue by Daviteusz** [NixOS/nixpkgs#328386]
### Describe the bug
[libsForQt5.qtstyleplugin-kvantum v1.1.2](https://search.nixos.org/packages?channel=unstable&show=libsForQt5.qtstyleplugin-kvantum&from=0&size=50&sort=relevance&type=packages&query=kvantum) provides no programs while [kdePackages.qtstyleplugin-kvantum v1.1.2 ](https://search.nixos.org/packages?channel=unstable&show=libsForQt5.qtstyleplugin-kvantum&from=0&size=50&sort=relevance&type=packages&query=kvantum) provides kvantummanager and kvantumpreview

### Steps To Reproduce
1. Install libsForQt5.qtstyleplugin-kvantum and check if kvantum manager is installed

### Expected behavior
Kvantum manager should be installed while installing libsForQt5.qtstyleplugin-kvantum

### Screenshots
![obraz](https://github.com/user-attachments/assets/cc8c0394-47be-46df-92c9-4b849a1c94ff)
![obraz](https://github.com/user-attachments/assets/47d37dd3-ce12-4cb3-9042-627f1befe1c2)

### Additional context
I'm using plasma5 and I need install two packages to get Kvantum Manager
```nix
 environment.systemPackages = with pkgs; [
    kdePackages.qtstyleplugin-kvantum
    libsForQt5.qtstyleplugin-kvantum
  ];
```

### Notify maintainers
@romildo @Scrumplex 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9, NixOS, 24.11 (Vicuna), 24.11.20240714.693bc46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
With Kvantum version 1.1.0, most components are now only built for Qt 6.

See https://github.com/tsujan/Kvantum/releases/tag/V1.1.0

You will have to install both if you want to use this on Plasma 5.

**Comment by Daviteusz** [comment]
Ok, thanks, I should check released packages changelog next time.
