### ISSUE TITLE
Build failure: python312Packages.distorm3

### ISSUE THREAD

**Issue by kennystrawnmusic** [NixOS/nixpkgs#328346]
### Steps To Reproduce

Steps to reproduce the behavior (replace `/dev/sda` with the disk you're trying to install NixOS onto):
1. `fdisk /dev/sda`
2. `mkfs.vfat -F32 /dev/sda1`
3. `mkfs.bcachefs /dev/sda2`
4. `mount -t bcachefs /dev/sda2 /mnt`
5. `mkdir /mnt/boot`
6. `mount -t vfat /dev/sda1 /mnt/boot`
7. `nixos-generate-config --root /mnt`
8. `wget -O /mnt/etc/nixos/configuration.nix https://gist.github.com/kennystrawnmusic/05e6bcea71e2d08f2414b9681b2b0de8/raw/ce55548890583f5b498404d8ba7cc55768ed369a/configuration.nix`
9. `nixos-install -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/staging.tar.gz -I nixos=https://github.com/NixOS/nixpkgs/archive/staging.tar.gz`

### Build log

```
building the configuration in /mnt/etc/nixos/configuration.nix...
error:
       … while calling the 'head' builtin
         at /mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'
         at /mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/lib/modules.nix:821:9:
          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `system.systemBuilderArgs':

       … while evaluating definitions from `/mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/nixos/modules/system/activation/activatable-system.nix':

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating definitions from `/mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating definitions from `/mnt/nix/store/g6k7p7d1480l6d307sqbcklfszva6g1s-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc.dbus-1.source':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: distorm3-3.5.2 not supported for interpreter python3.12

```

### Additional context

Actually used staging tarballs to test the supposed #325968 fix; still having problems despite that

### Notify maintainers

@fabaff 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/realkstrawn93/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kennystrawnmusic** [comment]
For those curious, the disk I have Arch on is `/dev/nvme0n1` — so no, I'm not trying to overwrite Arch with NixOS as some might suspect with the way the disks in the reproduction steps are.

**Comment by eclairevoyant** [comment]
Don't see any mention of distorm3 in https://github.com/NixOS/nixpkgs/pull/325968. Anyway the reason is here: 

https://github.com/NixOS/nixpkgs/blob/7007e50ce479626f45d65f0de2f22be18c40ea90/pkgs/development/python-modules/distorm3/default.nix#L17

Upstream seems dead for 3 years though

**Comment by kennystrawnmusic** [comment]
Unrelated but libunistring is failing due to a GNU mirror problem; see #328452
