### ISSUE TITLE
Build failure: diffoscope

### ISSUE THREAD

**Issue by panchoh** [NixOS/nixpkgs#328350]
### Steps To Reproduce

1. build *diffoscope*

### Build log

[Full log](https://gist.github.com/panchoh/d39606af28786e3c34e8ebc7283bc506)

```
❯ nix build .#diffoscope
error: builder for '/nix/store/gy75y3hyqci2cwr1xzvbp230fwabwzb3-diffoscope-271.drv' failed with exit code 1;
       last 10 log lines:
       > tests/comparators/test_jpeg_image.py:87: AssertionError
       > ----------------------------- Captured stderr call -----------------------------
       > WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
       >
       > =========================== short test summary info ============================
       > FAILED tests/comparators/test_jpeg_image.py::test_has_visuals - assert 1 == 2
       >  +  where 1 = len([<Difference Image content -- Image content []>])
       >  +    where [<Difference Image content -- Image content []>] = <Difference /build/diffoscope-271/tests/data/test1.jpg -- /build/diffoscope-271/tests/data/test2.jpg [<Difference Image content -- Image content []>]>.details
       > = 1 failed, 679 passed, 38 skipped, 5 deselected, 1 xfailed, 1 xpassed in 52.00s =
       > /nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 1641: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/gy75y3hyqci2cwr1xzvbp230fwabwzb3-diffoscope-271.drv'.
```

### Additional context

From what I read in the build log, it seems that ImageMagick v7 has changed its cli interface a bit.  Maybe we can depend on  `imagemagick6` until upstream catches up.

### Notify maintainers

@dezgeg @danielfullmer @raitobezarius

### Metadata

Build failure still present at c3e7bd26c8e281a677d444913663e1244d5e9d66.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240716.ad0b5ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
seems like easy fix

**Comment by s0me1newithhand7s** [comment]
as i found, this error isn't nixpkgs related as o found "convert" option [here](https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/master/tests/comparators/test_jpeg_image.py?ref_type=heads#L83) and error is pointing on both **WARNING** and **FAILED** while `diffoscope` is running `test_jpeg_image.py`. i feel like this issue needs to be created inside `diffoscope` repository on salsa.

**Comment by panchoh** [comment]
I'll report this issue upstream. Currently waiting for the salsa admins to approve my request to create an account there.

I also tried the quick fix of replacing `imagemagick` with `imagemagick6` in the derivation ([1](https://github.com/NixOS/nixpkgs/blob/ef1525d313ebb81803193719a74d053f52e88975/pkgs/tools/misc/diffoscope/default.nix#L40), [2](https://github.com/NixOS/nixpkgs/blob/ef1525d313ebb81803193719a74d053f52e88975/pkgs/tools/misc/diffoscope/default.nix#L216)), but it seems that there is a whole bunch of [vulnerabilities](https://github.com/NixOS/nixpkgs/blob/ef1525d313ebb81803193719a74d053f52e88975/pkgs/applications/graphics/ImageMagick/6.x.nix#L123) in the legacy ImageMagick v6 series.

**Comment by nh2** [comment]
> as i found, this error isn't nixpkgs related as o found "convert" option [here](https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/master/tests/comparators/test_jpeg_image.py?ref_type=heads#L83)

Stable link: https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/82bbacbf0060a1b89cde5b5c950f754935757605/tests/comparators/test_jpeg_image.py#L83

**Comment by bjornfor** [comment]
Ugh, this breakage also hit nixos-24.05 branch (the stable channel).

**Comment by panchoh** [comment]
I've just reported this [upstream](https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/384).
Thanks for the feedback, folks.

**Comment by s0me1newithhand7s** [comment]
> I've just reported this [upstream](https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/384).
> Thanks for the feedback, folks.

np!

**Comment by panchoh** [comment]
Chris Lamb has fixed the issue (haven't tested it yet, though).

**Comment by bjornfor** [comment]
> Ugh, this breakage also hit nixos-24.05 branch (the stable channel).

Oh, it was a very small (imagemagic) update too: d35a2e8d0297d8cc30d1b3a6d2c6a5b66a3cb044 (magemagick: 7.1.1-34 -> 7.1.1-35)

**Comment by panchoh** [comment]
> > Ugh, this breakage also hit nixos-24.05 branch (the stable channel).
> 
> Oh, it was a very small (imagemagic) update too: [d35a2e8](https://github.com/NixOS/nixpkgs/commit/d35a2e8d0297d8cc30d1b3a6d2c6a5b66a3cb044) (magemagick: 7.1.1-34 -> 7.1.1-35)

I find it a bit confusing since they state that they follow SemVer (can be seen at the top of the changelog you shared), and yet, most of their releases fall in the "prerelease" category (X.Y.Z-N)  according to [SemVer](https://semver.org/spec/v2.0.0.html#spec-item-9), which indicates that (and I quote): "A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version."

So, it follows that we cannot freely track changes to ImageMagick, or else we might break stuff. Not very SemVer friendly, IMHO.

**Comment by panchoh** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/324888, yay!, so closing.

**Comment by bjornfor** [comment]
> Fixed by https://github.com/NixOS/nixpkgs/pull/324888, yay!, so closing.

Yay!

Technically it was commit 9eae9c20350ad5b133bdfd63d27a2029a5734a79 that fixed the build failure (by skipping the broken test). We should revert that hotfix now that diffoscope is updated.

**Comment by bjornfor** [comment]
The hotfix (disable broken test) is already backported to NixOS 24.05: https://github.com/NixOS/nixpkgs/pull/330982
