### ISSUE TITLE
Build failure: wayland (with environment.noXlibs)

### ISSUE THREAD

**Issue by lions-tech** [NixOS/nixpkgs#328397]
### Steps To Reproduce

1. Create flake.nix
2. Copy content from https://gist.github.com/lions-tech/a34548a39363dc370aa12a35fdf54aad
3. `nix build .`

### Build log

https://gist.github.com/lions-tech/a34548a39363dc370aa12a35fdf54aad (scroll down)

### Additional context

This problem first occured when I tried upgrading a NixOS system to 24.05. The overlay applied is from `environment.noXlibs = true`. `hardware.opengl.enable = true` will per default use drivers from the `mesa` package, which in turn needs `wayland`. 

With the overlay applied however, wayland will fail to build: doxygen fails to generate the documentation because it cannot find some fonts. doxygen depends on the `graphviz` package, which in turn needs `gd`. If the `gd` derviation is built with `withXorg = false`, it will exclude fontconfig.

The combination of the aforementioned two options is useful for WSL configurations, for which X11 is not necessary, but OpenGL is beneficial.

### Notify maintainers
@primeos @codyopel @alyssais 

### Metadata

flake.lock:
```
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1721226092,
        "narHash": "sha256-UBvzVpo5sXSi2S/Av+t+Q+C2mhMIw/LBEZR+d6NMjws=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "c716603a63aca44f39bef1986c13402167450e0a",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-24.05",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Did you try overriding wayland using `withDocumentation = false`?

**Comment by SuperSandro2000** [comment]
Yes, thats on purpose and won't be fixed. If you require wayland to be built, then noXlibs is not for you. Packages that require wayland need an overlay to have the optional dependency be removed. If it cannot be removed, the package is incompatible with noXlibs.

**Comment by lions-tech** [comment]
> Yes, thats on purpose and won't be fixed. If you require wayland to be built, then noXlibs is not for you. Packages that require wayland need an overlay to have the optional dependency be removed. If it cannot be removed, the package is incompatible with noXlibs.


I would be okay with that, if it weren't for the option collision. As I already explained, I think, using those options in combination is a common use case.
