### ISSUE TITLE
locale support in nix-shell --pure

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#32848]
## Issue description
In nix-shell --pure using:

`LC_NUMERIC=en_US printf "%s %'.f\n" "10" "20"` gives a warning 
` warning: setlocale: LC_NUMERIC: cannot change locale (en_US): No such file or directory`

Is there any mechanism to use locales on NixOS, other systems with Nix installed (Macs/Debian/Ubuntu/Windows?) in nix-shell?

locale is part of `glibc`. Is glibc working on a modern Mac?

If `locale-gen` is present, then it should be possible to properly configure the locales from within the nix-shell environment.

Related issue: https://github.com/NixOS/nixpkgs/issues/21820

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
On Linuxes you can do this:
```
$ nix-shell --pure -p glibcLocales
$ LC_NUMERIC=en_US printf "%s %'.f\n" "10" "20"
10 20
```

**Comment by vcunat** [comment]
To explain, the default `glibc` package doesn't contain locale data &ndash; that's separate and `--pure` isn't supposed to see OS data.

**Comment by coretemp** [comment]
Slightly related, how can I display all packages that work on a Mac? Or display all that do not work on a Mac?

**Comment by vcunat** [comment]
`nix-env -qa` &ndash; it's supposed to filter based on the settings (platform, allowed licenses, broken-ness, etc.)

**Comment by vcunat** [comment]
You can add `--argstr system x86_64-darwin` if you're running the command on a different platform.
