### ISSUE TITLE
[gnome-boxes][NixOS Installer] 'The screen is too small to display the installer'

### ISSUE THREAD

**Issue by kidq330** [NixOS/nixpkgs#328520]
### Describe the bug
When trying to spin up a new NixOS 23.11 (GNOME Installation CD) VM on Ubuntu using gnome-boxes, the installer greets me with the warning: 'The screen is too small to display the installer'. Despite going to settings and changing resolution to 1920x1080, the warning remains.

### Steps To Reproduce
1. On Ubuntu 22.04, using gnome-boxes, create a NixOS vm by choosing the `NixOS 23.11 (GNOME Installation CD)` image
2. Choose the standard installer

### Expected behavior
No warning, or warning disappears when changing screen resolution / installer window size

### Screenshots
![Screenshot from 2024-07-19 22-50-45](https://github.com/user-attachments/assets/e9dd60ba-f142-4402-b93f-8a5b6d720184)

### Metadata

```console
[nixos@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.96, NixOS, 23.11 (Tapir), 23.11.7870.205fd4226592`

 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-23.11.7870.205fd4226592"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
23.11 isn't supported anymore, and the calamares installer is maintained in a separate repo: https://github.com/NixOS/calamares-nixos-extensions/

If you can repro this on 24.05 feel free to file an issue there.

**Comment by eclairevoyant** [comment]
Also did you try closing the existing window after chaning the resolution and relaunching thne installer?

**Comment by kidq330** [comment]
> Also did you try closing the existing window after changing the resolution and relaunching the installer?

Yep, that worked. Didn't think to check whether a newer stable version is out, thanks!
