### ISSUE TITLE
Package request: ghi

### ISSUE THREAD

**Issue by amacfie** [NixOS/nixpkgs#328699]
**Project description**

ghi is a command-line tool for working with GitHub issues written in Ruby. The original repo is https://github.com/stephencelis/ghi but according to the README there, it is currently maintained in a fork, which is the source URL below.

**Metadata**

* homepage URL: N/A
* source URL: https://github.com/drazisil/ghi
* license: mit
* platforms: platforms where Ruby runs

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
![image](https://github.com/user-attachments/assets/24361961-8349-4bfe-ae6b-24272be83b84)

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/328736
