### ISSUE TITLE
Update request: markdown-oxide 0.0.21 → 0.23.1

### ISSUE THREAD

**Issue by jukremer** [NixOS/nixpkgs#328893]
- Package name: markdown-oxide
- Latest released version: 0.23.1

- Current version on the unstable channel: 0.0.21
- Current version on the stable/release channel: 0.0.21

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@linsui 
I tried to do this on my own but the build failed. The license change too to GPL v3.

```
Validating consistency between /private/tmp/nix-build-markdown-oxide-0.23.1.drv-0/source/Cargo.lock and /private/tmp/nix-build-markdown-oxide-0.23.1.drv-0/cargo-vendor-dir/Cargo.lock
437,447d436
< name = "fuzzydate"
< version = "0.2.2"
< source = "registry+https://github.com/rust-lang/crates.io-index"
< checksum = "7265f35cc1f40c655aad829323a1daef5f21fd38904f6ed9bd5ec3df3cbd851c"
< dependencies = [
<  "chrono",
<  "lazy_static",
<  "thiserror",
< ]
<
< [[package]]
639c628
< version = "0.22.0"
---
> version = "0.1.0"
644d632
<  "fuzzydate",

ERROR: cargoHash or cargoSha256 is out of date

Cargo.lock is not the same in /private/tmp/nix-build-markdown-oxide-0.23.1.drv-0/cargo-vendor-dir

To fix the issue:
1. Set cargoHash/cargoSha256 to an empty string: `cargoHash = "";`
2. Build the derivation and wait for it to fail with a hash mismatch
3. Copy the "got: sha256-..." value back into the cargoHash field
   You should have: cargoHash = "sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=";
```

I tried setting cargoHash/cargoSha256 to an empty string but the build failed with the same output.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
There is no cargoHash/cargoSha256. You need to update the Cargo.lock file.
