### ISSUE TITLE
Package request: Mullvad Browser

### ISSUE THREAD

**Issue by helldotrs** [NixOS/nixpkgs#328801]
**Project description**

The Mullvad Browser is a privacy-focused web browser developed in a collaboration between [Mullvad VPN](https://mullvad.net/) and the [Tor Project](https://www.torproject.org/)

**Metadata**

* homepage URL: https://mullvad.net/en/browser
* source URL: https://github.com/mullvad/mullvad-browser
* license: Mozilla Public License V2
* platforms: linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Already available as `mullvad-browser`
