### ISSUE TITLE
steam / steam-run: make it possible / document how to override steamrt dependencies

### ISSUE THREAD

**Issue by uwap** [NixOS/nixpkgs#32881]
## Issue description
Many games on steam come with certain dependencies and I think it is not always the right choice to "force" a depdency onto all steam users under nixos. Is there a way to override the FHS used in steam-run and steam to add new dependencies?

If so: There is no documentatin about it.
If not: There should be.

**Comment by uwap** [comment]
cc @abbradar

**Comment by yegortimoshenko** [comment]
> Many games on steam come with certain dependencies and I think it is not always the right choice to "force" a depdency onto all steam users under nixos.

It is almost always right. I would want for Steam to work out of the box. If you know any games that are missing dependencies, please tell.

You can add dependencies via `extraPkgs` option, see https://github.com/NixOS/nixpkgs/pull/26190.

Here is a practical example:

```
nix-build -E "with import <nixpkgs> {}; steam.override { extraPkgs = [ pkgs.dosbox ]; };
```

... will build Steam with `dosbox` in chrootenv.

**Comment by uwap** [comment]
@yegortimoshenko Thank you very much!

You are probably right regarding having steam games work out of the box. I came across a game requiring gtk3. Which should be added to the multiPackages list then.

The extraPkgs option should be documented somewhere.

**Comment by yegortimoshenko** [comment]
What game is it?

**Comment by uwap** [comment]
screeps

**Comment by uwap** [comment]
doesn't seem to run even with libgtk3. Still debugging.

**Comment by uwap** [comment]
So, for anyone else encountering this problem:
screeps requires a handful of libraries the steam runtime already ships, but it requires a newer version of it. So my solution is to set the launch options for it in steam to 
```
LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH %command%
```

And to put the following in my configuration.nix:
```
nixpkgs.config.packageOverrides = pkgs: {
    steam = pkgs.steam.override {
      extraPkgs = pkgs: with pkgs; [
        gnome3.gtk
        zlib
        dbus
        freetype
        glib
        atk
        cairo
        gdk_pixbuf
        pango
        fontconfig
        xorg.libxcb
      ];
    };
  };
```

This adds libraries that are not automatically given through the steam package and overrides some of the libraries used by the steam runtime.

This is a dirty hack. Is there a reason the steam runtime uses such old versions of libraries?

**Comment by abbradar** [comment]
@uwap Steam Runtime uses Ubuntu 12.04 as a base for its libraries -- all games are supposed to be compatible with it. If any game doesn't work it's a game bug. I guess Valve won't update those libraries easily as all current games depend on their versions -- maybe Runime would be versioned depending on a game in the future.

Try `steam.override { nativeOnly = true; }` -- this will force Steam to drop Runtime and use libraries from nixpkgs instead. Beware as a lot of games break that way but if you manage to fix some please send PRs!

**Comment by matthew-piziak** [comment]
@uwap I've tried your solution and `** ERROR ** Missing library libz.so.1` still appears. My `LD_LIBRARY_PATH` is `/run/opengl-driver/lib` on NixOS.

My steam.nix looks like this. Do you know what I might be doing wrong?
```
{ config, pkgs, ... }:

{
  nixpkgs.config.packageOverrides = pkgs: {
    steam = pkgs.steam.override {
     extraPkgs = pkgs: with pkgs; [
         zlib
       ];
     };
  };
}
```

**Comment by uwap** [comment]
@matthew-piziak You need to set the LD_LIBRARY_PATH to `/lib:$LD_LIBRARY_PATH` before starting the game with steam-run or set `LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH %command%` as launch option for the game in steam. Otherwise it will take the zlib from the steam runtime, which has an older version of zlib.

**Comment by uwap** [comment]
@matthew-piziak To start a game with steam-run I recommend using `steam-run bash` to get a shell first and then run `export LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH` before normally executing the game's executable

**Comment by matthew-piziak** [comment]
@uwap Interesting! Where do I find the game's executable if I've installed it from the Steam store?

**Comment by uwap** [comment]
You can find it in ~/.local/share/steam

**Comment by matthew-piziak** [comment]
@uwap Thank you! I have installed `steam-run` and `zlib` in my `environment.systemPackages`.

However, I still get a `Missing library libz.so.1` error when I try to launch the game's executable:
```
~/.local/share/Steam/steamapps/common/Dead Cells $ steam-run bash
bash-4.4$ export LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH
bash-4.4$ ./deadcells.sh
** ERROR ** Missing library libz.so.1
** ERROR ** Missing library libz.so.1
** ERROR ** Missing library libasound.so.2
** ERROR ** Missing library libpulse-simple.so.0
** ERROR ** Missing library libpulse.so.0
** ERROR ** Missing library libX11.so.6
** ERROR ** Missing library libXext.so.6
** ERROR ** Missing library libXcursor.so.1
** ERROR ** Missing library libXinerama.so.1
** ERROR ** Missing library libXi.so.6
** ERROR ** Missing library libXrandr.so.2
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libXxf86vm.so.1
** ERROR ** Missing library libwayland-egl.so.1
** ERROR ** Missing library libwayland-client.so.0
** ERROR ** Missing library libwayland-cursor.so.0
** ERROR ** Missing library libxkbcommon.so.0
** ERROR ** Missing library libasound.so.2
** ERROR ** Missing library libpulse-simple.so.0
** ERROR ** Missing library libpulse.so.0
** ERROR ** Missing library libX11.so.6
** ERROR ** Missing library libXext.so.6
** ERROR ** Missing library libXcursor.so.1
** ERROR ** Missing library libXinerama.so.1
** ERROR ** Missing library libXi.so.6
** ERROR ** Missing library libXrandr.so.2
** ERROR ** Missing library libXss.so.1
** ERROR ** Missing library libXxf86vm.so.1
** ERROR ** Missing library libwayland-egl.so.1
** ERROR ** Missing library libwayland-client.so.0
** ERROR ** Missing library libwayland-cursor.so.0
** ERROR ** Missing library libxkbcommon.so.0
** ERROR ** Missing library libstdc++.so.6
** ERROR ** Missing library libz.so.1
sh: notify-send: command not found
src/module.c(272) : FATAL ERROR : Failed to load library fmt.hdll
```

**Comment by matthew-piziak** [comment]
If I run `steam-run bash` first, I get this strange error:
```
~/.steam/steam/steamapps/common/Dead Cells $ steam-run bash
bash-4.4$ /run/current-system/sw/bin/steam-run ./deadcells.sh
/nix/store/28xgy33kx88zhqsamwnwjvhz76f5w2ik-chrootenv: symbol lookup error: /nix/store/28xgy33kx88zhqsamwnwjvhz76f5w2ik-chrootenv: undefined symbol: g_strv_contains
bash-4.4$ 
```

**Comment by jb55** [comment]
so here's a fun issue:

SteamVR requires qt5, and that's not in the runtime. So I add it to extraPkgs and try to run ./vrmonitor:

```
./vrmonitor: /steamrt/amd64/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /nix/store/ifz527a2bm8bbgc083c80afjd6m393sa-libpng-apng-1.6.34/lib/libpng16.so.16)
```

I thought this was weird... it's looking for libpng16 instead of the runtime version (libpng12). Turns out qt5 was built with libpng16, which tries to pull in zlib 1.2.11 but ends up getting the steam-runtime version (1.2.9).

So it looks like I need to have a custom build of qt5 overriden with libpng12? Tedious. Going to try a pure native build first.

**Comment by jb55** [comment]
native seemed to work. vive seems to be working. woot!

**Comment by fghibellini** [comment]
The issue with Dead Cells is that the `deadcells.sh` script sets `LD_LIBRARY_PATH=.`.

I managed to make it run like so:
```
$ cd ~/.local/share/Steam/steamapps/common/Dead\ Cells
$ steam-run bash
$ export LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH
$ cat > deadcells.sh <<EOF
cat deadcells.sh
#!/bin/bash

(
  cd "$( dirname "${BASH_SOURCE[0]}" )"
  export LD_PRELOAD=
  export LD_LIBRARY_PATH=.:/lib:$LD_LIBRARY_PATH
  ./deadcells detect.hl
  ./deadcells
)
EOF
$ echo "588650" > steam_appid.txt # https://steamdb.info/app/588650/
$ ./deadcells.sh
```

Is there any way to fix this long-term ?

**Comment by yegortimoshenko** [comment]
https://github.com/NixOS/nixpkgs/pull/31263 is one potential long-term fix. Alternatively, I believe it could be possible to fix using [`libglvnd`](https://github.com/NVIDIA/libglvnd) similarly to how Flatpak runtime does it.

**Comment by zeorin** [comment]
@fghibellini that didn't work for me, but
```
#!/bin/bash

(
	cd "$( dirname "${BASH_SOURCE[0]}" )"
	export LD_PRELOAD=
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
	./deadcells detect.hl
	./deadcells
)
```
did work.

**Comment by Peter-Crawley** [comment]
> So, for anyone else encountering this problem:
> screeps requires a handful of libraries the steam runtime already ships, but it requires a newer version of it. So my solution is to set the launch options for it in steam to
> 
> ```
> LD_LIBRARY_PATH=/lib:$LD_LIBRARY_PATH %command%
> ```
> 
> And to put the following in my configuration.nix:
> 
> ```
> nixpkgs.config.packageOverrides = pkgs: {
>     steam = pkgs.steam.override {
>       extraPkgs = pkgs: with pkgs; [
>         gnome3.gtk
>         zlib
>         dbus
>         freetype
>         glib
>         atk
>         cairo
>         gdk_pixbuf
>         pango
>         fontconfig
>         xorg.libxcb
>       ];
>     };
>   };
> ```
> 
> This adds libraries that are not automatically given through the steam package and overrides some of the libraries used by the steam runtime.
> 
> This is a dirty hack. Is there a reason the steam runtime uses such old versions of libraries?

thanks for this, it helped me get stellaris to run properly.

**Comment by timhae** [comment]
For the current Dead Cells version I had to override the steam `libpng` package in addition to the modifications of the shell script

**Comment by Atemu** [comment]
Much of this is out of date.

We don't really have a place for official documentation on package-specific overrides or even generator/wrapper functions that I know of. 

It is documented at https://nixos.wiki/wiki/Steam#Adding_missing_dependencies though, so I'd consider this done.

If you want official documentation on packages override options open an issue on having that in general.
