### ISSUE TITLE
Get rid of poppler_qt4

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#32883]
Recently released [poppler 0.62](https://poppler.freedesktop.org/releases.html) removes the QT4 support.

For now, we will split the package and keep `popper_qt4` on 0.61.

**Comment by orivej** [comment]
It is still used so it should remain at an older version.

**Comment by vcunat** [comment]
It's used just in two packages, apparently (`frescobaldi` and `open-pdf-presenter`).  Hopefully those can be soon migrated to Qt5.  Otherwise we can keep old version for `poppler_qt4` only and keep updating the rest...

**Comment by orivej** [comment]
Those are only python dependents. It is also referenced from calligra, texstudio, texmaker, qpdfview, diffpdf.

**Comment by orivej** [comment]
Yeah. (I meant that `poppler_qt4` should remain at an older version, while `poppler` can be decoupled and upgraded.)

**Comment by dtzWill** [comment]
#34676 moves diffpdf away from poppler_qt4, FWIW.

**Comment by Ma27** [comment]
currently working on a fix for `frescobaldi` package as its latest version uses qt5 now, so poppler_qt4 isn't needed anymore

**Comment by jtojnar** [comment]
I opened a pull request updating [qpdfview](https://github.com/NixOS/nixpkgs/pull/37986), which makes open-pdf-presenter the last thing depending on `poppler_qt4` (via the python library). Since it is abandoned, it is not likely to be updated. Do we remove it?

**Comment by Ma27** [comment]
almost done, need some rest for now, PR for `frescobaldi` will come tomorrow :)

**Comment by jtojnar** [comment]
Finally getting rid of this in  #39896.
