### ISSUE TITLE
`rustdesk` derivation dependency from GitHub no longer exists (user deleted their account)

### ISSUE THREAD

**Issue by ndom91** [NixOS/nixpkgs#328884]
### Describe the bug

When attmepting to install `rustdesk` from `nixpkgs-24.05` I'm receiving an error about `"https://github.com/fufesou/rdev" not found..`.

When manually attempting to visit [the repo](https://github.com/fufesou/rdev) it seems its totally gone. Same for the user.

### Steps To Reproduce

1. Add `rustdesk` to system packages and execute a rebuild-switch, for example.

### Expected behavior

- Rustdesk installs successfully

### Additional context

Here's the derivation from `nixpkgs`: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/remote/rustdesk/default.nix#L61

Notice the `rdev` dependency. It seems to be a vendored Cargo crate 

### Notify maintainers

@ocfox @leixb 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.7, NixOS, 24.05 (Uakari), 24.05.20240702.706eef5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/0z4i8wyg3ymm7kkb1gk2wyh08x230c6z-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Upstream fixed it in https://github.com/rustdesk/rustdesk/pull/8772, no release yet.
