### ISSUE TITLE
Package request: key-rack

### ISSUE THREAD

**Issue by izzthedude** [NixOS/nixpkgs#328877]
**Project description**

Key Rack allows to view and edit keys, like passwords or tokens, stored by apps. It supports Flatpak secrets as well as system wide secrets

**Metadata**

* homepage URL: https://gitlab.gnome.org/sophie-h/key-rack
* source URL: https://gitlab.gnome.org/sophie-h/key-rack
* license: gpl3
* platforms: linux
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Guanran928** [comment]
This is already available in the unstable channel: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=key-rack
