### ISSUE TITLE
Build failure: pipewire with gstreamerSupport = false;

### ISSUE THREAD

**Issue by filakhtov** [NixOS/nixpkgs#328854]
### Steps To Reproduce

1. Set `gstreamerSupport = false;` for the pipewire package, e.g.:
```nix
(self: super: {
  pipewire = (super.pipewire.override {
    gstreamerSupport = false;
  });
})
``` 
2. Try building it

### Build log
[Full build log here](https://github.com/filakhtov/test-proof-artifacts/blob/652fbf3109ed04d845d60709e051c81fc4daaeac/gh/nixos/nixpkgs/328854/build.log)
```
error: builder for '/nix/store/wgrafxy52bl43wh76bl4cgxn3x1v2psk-pipewire-1.0.7.drv' failed with exit code 1;
       last 10 log lines:
       > Run-time dependency libcanberra found: YES 0.30
       > Run-time dependency libusb-1.0 found: YES 1.0.27
       > Run-time dependency libcap found: YES 2.69
       > Run-time dependency glib-2.0 found: YES 2.80.2
       > Run-time dependency gio-2.0 found: YES 2.80.2
       > Dependency glib-2.0 skipped: feature gstreamer disabled
       >
       > meson.build:371:6: ERROR: Problem encountered: `gstreamer-device-provider` is enabled but `glib-2.0` was not found.
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/wgrafxy52bl43wh76bl4cgxn3x1v2psk-pipewire-1.0.7.drv'.
error: 1 dependencies of derivation '/nix/store/q08x7jj3gqjafvcd79zgai1qzm7qsxpm-SDL2-2.30.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/js3n9p4ilnrlkxkjb2mlqr1wz2faygbr-gnome-remote-desktop-46.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7ldsfimg20ddd57979czfc78ad6qhib8-gnome-shell-46.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b8gh76bwmnf1dsi856maj8mlfddibdkb-google-chrome-126.0.6478.182.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8sr5k8bxxaqcr2bsn8c1vqj57gfgrpdh-hwdb.bin.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gvwfailabl0izry6823md1pc6ip58z5f-mutter-46.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gfksa8xyg319qrdbd3s550nj93j0z3h9-openal-soft-1.23.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wcc3y9cwc1wyz51lafj19a07ifl2yxxd-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gxslyy7g1di8jazfffl9krm6py82p9jp-nixos-system-heliodor-24.05.20240719.0c53b6b.drv' failed to build
```

### Additional context

This can be fixed by either making sure that `gstreamerSupport` flag controls the `gstreamer-device-provider` Meson option in addtion to the `gstreamer`, or by exposing a new option to control the `gstreamer-device-provider` directly.

### Notify maintainers
ping @kranzes @k900 👋🏻 let me know which of the options above you guys prefer and I can open up a PR to fix as well.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.05 (Uakari), 24.05.20240719.0c53b6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - nixpkgs: `/nix/store/qszplw617r895nbcprgyj139c9a3r0xs-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Can we just remove that option instead?

**Comment by filakhtov** [comment]
Sorry do you mean set the `gstreamer-device-provider` to always be false or completely remove the `gstreamerSupport` as an option? Because I prefer the abilitiy to turn as many unnecessary dependencies as practically possible on my system (better stability and security).

**Comment by K900** [comment]
Remove the `gstreamerSupport` option, yes, because we can't realistically maintain the exponential explosion of possible flag combinations.

**Comment by eclairevoyant** [comment]
I made two PRs: https://github.com/NixOS/nixpkgs/pull/328996 and https://github.com/NixOS/nixpkgs/pull/328999

Feel free to pick whichever PR looks better to you

**Comment by eclairevoyant** [comment]
arg removed in #328999

**Comment by alyssais** [comment]
> because we can't realistically maintain the exponential explosion of possible flag combinations.

How much maintenance burden does this actually cause? IMO the package options are one of Nixpkgs strengths (one of the things that attracted me, after I stopped working on Homebrew because package options started to be removed entirely), and they're critical for people working on systems where size matters.

**Comment by alyssais** [comment]
To expand a bit, I don't think that package maintainers should generally be expected to support all combinations of options, but I also don't think they should block people who want to from doing so.  Just _having_ the flags there shouldn't cause any problems for package maintainers that don't want to maintain the flags, and it's fine IMO to respond to issues about flags not working by asking people to adopt the flag and send a patch.

**Comment by eclairevoyant** [comment]
No one's _blocking_ people from overriding.

It's just a bad idea to have some flags we haven't even looked at in months and pretend we support them by including them in the expression. Or in other words, keeping the flags is shipping broken code if people don't maintain them.

**Comment by alyssais** [comment]
The enableSystemd flag had clearly been looked at recently, because there was a commit from me fixing it, and yet it was removed anyway.
