### ISSUE TITLE
Horizontal lines displayed in Konsole

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#32889]
## Issue description
When I press "arrow-down" in vim to go to the next line in rapid succession, I see horizontal lines as in the screenshot. 

Emacs also has redraw issues where pressing "arrow down" in that it switches the buffer displayed.

### Steps to reproduce
Start konsole
`vim ./nixos/modules/services/editors/emacs.nix`
Press and hold <arrow down> .

## Workaround
Use gnome-terminal

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

![rendering_problem](https://user-images.githubusercontent.com/34454443/34205155-a2aac3da-e581-11e7-8e85-0d299253ab55.png)

**Comment by orivej** [comment]
What font are you using?

**Comment by coretemp** [comment]
Monospace size 9.0

**Comment by orivej** [comment]
Monospace is a generic name. What does `fc-match Monospace` say?

**Comment by coretemp** [comment]
`Hack-Regular.ttf: "Hack" "Regular"`

**Comment by nixy** [comment]
Not sure if this is helpful, but I had experienced this using the Fira fonts a while back.

I haven't experienced this recently (so for me this seems to be resolved).

@coretemp Is this still happening for you?

**Comment by coretemp** [comment]
Yes, this is still happening. To reproduce this I only had to start konsole this time.

**Comment by nixy** [comment]
I'll try to reproduce this later tonight (not at a NixOS system right now), but this may just be a konsole issue.

It looks like the following bugs may be related and this may simply be an issue with how konsole handles scaling.

https://unix.stackexchange.com/questions/414836/ugly-horizontal-lines-displayed-in-text-not-part-of-document
https://bugs.kde.org/show_bug.cgi?id=373232

**Comment by coretemp** [comment]
I only read the second link and all those comments seemed spot on. I am also using a scaling factor, for example.

**Comment by orivej** [comment]
For the reference, to work around this, set Scale to 1 in System settings > Display and monitor > Displays > Scale display, and set `services.xserver.dpi` or System settings > Fonts > Fonts > Force fonts DPI to your real or desired DPI.

When this DPI is much larger than 100, LibreOffice overscales everything, and the workaround for that is to launch it with DPI set to 96.

**Comment by JohnRTitor** [comment]
Closed. If this is still an issue, this should probably be reported upstream.
