### ISSUE TITLE
Package request: argc v1.19.0

### ISSUE THREAD

**Issue by rupurt** [NixOS/nixpkgs#328983]
A Bash CLI framework, also a Bash command runner.

The current version in nixpkgs is v1.14.0

**Metadata**

* homepage URL: https://github.com/sigoden/argc
* source URL: https://github.com/sigoden/argc
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qwqawawow** [comment]
https://github.com/NixOS/nixpkgs/pull/324665
