### ISSUE TITLE
Build failure: ddcci-driver with 6.10 kernel

### ISSUE THREAD

**Issue by leoluk** [NixOS/nixpkgs#328909]
### Steps To Reproduce

Build `kernelPackages.ddcci-driver` with `linuxPackages_latest`.

### Build log

```
building '/nix/store/nrbbghbrgl7jmbh08mdxxfrs9hn8j03d-ddcci-driver-6.10-0.4.4.drv'...
error: builder for '/nix/store/nrbbghbrgl7jmbh08mdxxfrs9hn8j03d-ddcci-driver-6.10-0.4.4.drv' failed with exit code 2;
       last 10 log lines:
       >  1827 |         .class          = I2C_CLASS_SPD,
       >       |                           ^~~~~~~~~~~~~
       >       |                           I2C_CLASS_HWMON
       > make[4]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/scripts/Makefile.build:244: /build/source/ddcci/ddcci.o] Error 1
       > make[3]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/Makefile:1934: /build/source/ddcci] Error 2
       > make[2]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/Makefile:240: __sub-make] Error 2
       > make[2]: Leaving directory '/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/build'
       > make[1]: *** [Makefile:38: ddcci.ko] Error 2
       > make[1]: Leaving directory '/build/source/ddcci'
       > make: *** [Makefile:28: ddcci] Error 2
       For full logs, run 'nix log /nix/store/nrbbghbrgl7jmbh08mdxxfrs9hn8j03d-ddcci-driver-6.10-0.4.4.drv'.
error: 1 dependencies of derivation '/nix/store/s30x3v6c96r03rmy5vfdxfmq251j82f0-linux-6.10-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wksvj8ylyplj1gbkwrccsknwrdh3nc1p-nixos-system-leowork-24.05.20240719.0c53b6b.drv' failed to build
```

### Additional context

Looks like `I2C_CLASS_SPD` was next on the chopping block: https://github.com/torvalds/linux/commit/e61bcf42d290e73025bab38e0e55a5586c2d8ad5

Related: https://github.com/NixOS/nixpkgs/pull/309948, #297312

I don't know anything about the i2c subsystem, can we simply use `I2C_CLASS_HWMON` instead?

### Notify maintainers

 @kiike

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by squalus** [comment]
https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/issues/44

**Comment by hughobrien** [comment]
I've added a wiki section if anyone would like to review https://wiki.nixos.org/wiki/Backlight#External_Monitors

**Comment by fpletz** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/354241.
