### ISSUE TITLE
Stop cursor blinking in gnome-terminal

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#32892]
## Issue description
I wanted to stop cursor blinking in gnome-terminal, so I ended up learning about gsettings via https://wiki.gnome.org/Apps/Terminal/FAQ.

In order to configure gnome programs, gsettings is required. 

The module specifying services.gnome3.gnome-terminal-server.enable should automatically install the package providing gsettings, if there is one.

### Steps to reproduce

```
command-not-found gsettings 
`gsettings: command not found`
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
`gsettings` utility is a part of `glib.dev` but I do not think it should be enabled by default – most options can be changed in Terminal preferences, only the advanced ones require the tool. If user wants to tweak the hidden option, they can be expected to install `gsettings` utility or `dconf-editor` (graphical frontend for GSettings).

**Comment by coretemp** [comment]
How do I configure command-not-found gsettings to return glib.dev? 

man command-not-found returns there is no manpage. 
command-not-found --help says it's an invalid option.

**Comment by jtojnar** [comment]
`command-not-found` gets its data from https://github.com/NixOS/nixpkgs/blob/9df79de1a115920bd96a7d4e66bc3782865c8146/nixos/modules/programs/command-not-found/command-not-found.nix#L38

Not sure why dev output is not indexed but we should probably move the `gsettings` file to `binOuput`.
