### ISSUE TITLE
Python: switch to wheel format

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#329]
It has been accepted as *the* binary format for Python.

See:

- https://pypi.python.org/pypi/wheel/0.15.0
- http://www.python.org/dev/peps/pep-0427/

Basically we switch from *bdist_egg* to *bdist_wheel*.

**Comment by FRidh** [comment]
There's a [proposal](https://mail.scipy.org/pipermail/numpy-discussion/2015-October/074086.html) at the numpy discussion mailing list to break `python setup.py install` and instead requiring `pip install`. I thought it might be relevant for this discussion.

**Comment by domenkozar** [comment]
Yeah, we should move to `pip` and use wheels asap. It would fix a lot of bugs. Now that I'm working on Nix+Python, I might get a chance to do that.

**Comment by domenkozar** [comment]
As #11086 is practically ready, I'm happy to close this after 2 years ;)
