### ISSUE TITLE
dejavu-fonts outputHash fails with non-standard NIX_STORE_DIR

### ISSUE THREAD

**Issue by dylex** [NixOS/nixpkgs#32909]
## Issue description

Because dejavu-fonts includes an absolute symlink into dejavu-fonts-minmal, its outputHash depends on NIX_STORE_DIR. If this is set to something other than `/nix/store`, the check fails:

```
building path(s) '/mnt/home/sw/nix/store/5cc7abs1dxcfmqwrizixvwywyibs1c9s-dejavu-fonts-2.37'
output path '/mnt/home/sw/nix/store/5cc7abs1dxcfmqwrizixvwywyibs1c9s-dejavu-fonts-2.37' has r:sha256 hash '13nayl6lmgg0nhmmanbh6aq76w0cb0i342k3nkcls3yyhzb4rhmd' when '1nf0h15p8yvjx36syq1034i3hix99lm8p54iyjw8dpa19i9jfkmd' was expected
```

Perhaps this should be a relative symlink, though I'm not entirely sure why it needs to be a symlink at all rather than a copy.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-693.5.2.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - version: `nix-env (Nix) 1.11.15`

**Comment by volth** [comment]
symlink is just to save little space, copy would work too
