### ISSUE TITLE
Update request: zed-editor 0.141.3 → 0.144.4

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#329079]
- Package name: [zed-editor](https://zed.dev/)
- Latest released version: [0.144.4](https://github.com/zed-industries/zed/releases/tag/v0.144.4)

- Current version on the unstable channel: [0.141.3](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ze/zed-editor/package.nix#L178)
- Current version on the stable/release channel: [0.135.2](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/ze/zed-editor/package.nix#L145)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GaetanLepage
@niklaskorz

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by niklaskorz** [comment]
Draft PR is at #324549
