### ISSUE TITLE
Update request: lnd 0.18.0 → 0.18.2

### ISSUE THREAD

**Issue by bleetube** [NixOS/nixpkgs#329019]
- Package name: lnd
- Latest released version: 0.18.2
- Current version on the unstable channel:0.18.0
- Current version on the stable/release channel: 0.17.5-beta

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@cypherpunk2140 @prusnak I would love to learn how to update a package like this. I will try to figure it out, but here's where I am at so far:

I tried changing the version and updated the hashes using sha256sum command. I got incorrect hash errors and running the compiled binary showed that it was still building 0.18.0! Complete and total failure.

```
nix-shell -p $(nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}') --run "./result/bin/lnd --version"
...
       error: invalid SRI hash '131ngxxj2q0wr0lipd1n1s8mzj86r8z830g4rmb7822dzvaa8nnv'
lnd version 0.18.0-beta commit=
```

Here's `default.nix`:
```
{ buildGoModule
, fetchFromGitHub
, lib
, go
, tags ? [ "autopilotrpc" "signrpc" "walletrpc" "chainrpc" "invoicesrpc" "watchtowerrpc" "routerrpc" "monitoring" "kvdb_postgres" "kvdb_etcd" ]
}:

buildGoModule rec {
  pname = "lnd";
  version = "0.18.2-beta";

  src = fetchFromGitHub {
    owner = "lightningnetwork";
    repo = "lnd";
    rev = "v${version}";
    hash = "sha256-131ngxxj2q0wr0lipd1n1s8mzj86r8z830g4rmb7822dzvaa8nnv";
  };

  vendorHash = "sha256-1ismmnly60b3d0zyk7qpdbbk6zwc2jr8q5vlj1m6lxg9d28iyg6b";

  subPackages = [ "cmd/lncli" "cmd/lnd" ];

  inherit tags;

  meta = with lib; {
    description = "Lightning Network Daemon";
    homepage = "https://github.com/lightningnetwork/lnd";
    license = licenses.mit;
    maintainers = with maintainers; [ cypherpunk2140 prusnak ];
  };
}
```

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by prusnak** [comment]
> I tried changing the version and updated the hashes using sha256sum command.

Replace some random characters in the existing hashes for 0.18.0 and change the version to 0.18.2

The build will tell you which hashes should be used

**Comment by prusnak** [comment]
updated in PR https://github.com/NixOS/nixpkgs/pull/329127

**Comment by bleetube** [comment]
@prusnak thanks! I hate to trouble you, but I still seem stuck on why my `nix-build` command is still giving me lnd 0.18.0 instead of 0.18.2, any advice?

```sh
nix-shell -p $(nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}' --pure) --run "./result/bin/lnd --version" --pure
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'lnd-0.18.2-beta'
         whose name attribute is located at /nix/store/7v1w7191pad8rz4v9dj7xlfcs2kz2m08-nixos-23.11/nixos/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'configurePhase' of derivation 'lnd-0.18.2-beta'

         at /nix/store/7v1w7191pad8rz4v9dj7xlfcs2kz2m08-nixos-23.11/nixos/pkgs/build-support/go/module.nix:157:5:

          156|
          157|     configurePhase = args.configurePhase or (''
             |     ^
          158|       runHook preConfigure

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: invalid SRI hash '131ngxxj2q0wr0lipd1n1s8mzj86r8z830g4rmb7822dzvaa8nnv'
lnd version 0.18.0-beta commit=

cat default.nix 
{ buildGoModule
, fetchFromGitHub
, lib
, go
, tags ? [ "autopilotrpc" "signrpc" "walletrpc" "chainrpc" "invoicesrpc" "watchtowerrpc" "routerrpc" "monitoring" "kvdb_postgres" "kvdb_etcd" ]
}:

buildGoModule rec {
  pname = "lnd";
  version = "0.18.2-beta";

  src = fetchFromGitHub {
    owner = "lightningnetwork";
    repo = "lnd";
    rev = "v${version}";
    hash = "sha256-131ngxxj2q0wr0lipd1n1s8mzj86r8z830g4rmb7822dzvaa8nnv";
  };

  vendorHash = "sha256-1ismmnly60b3d0zyk7qpdbbk6zwc2jr8q5vlj1m6lxg9d28iyg6b";

  subPackages = [ "cmd/lncli" "cmd/lnd" ];

  inherit tags;

  meta = with lib; {
    description = "Lightning Network Daemon";
    homepage = "https://github.com/lightningnetwork/lnd";
    license = licenses.mit;
    maintainers = with maintainers; [ cypherpunk2140 prusnak ];
  };
}
```

**Comment by prusnak** [comment]
@bleetube not sure how you obtained those hashes ... does it work with hashes from my PR?

**Comment by bleetube** [comment]
@prusnake thanks for clarifying and providing correct hashes. but why  is nix-build is giving me the old version

**Comment by bleetube** [comment]
@prusnak  thanks for clarifying and providing correct hashes. but why  is nix-build is giving me the old version
