### ISSUE TITLE
Build failure: rapid-photo-downloader

### ISSUE THREAD

**Issue by dcarosone** [NixOS/nixpkgs#329288]
### Steps To Reproduce

`nix build nixpkgs#rapid-photo-downloader`

### Build log

```
error: builder for '/nix/store/bh89z3syz1477rahakn5dy395608cy2c-rapid-photo-downloader-0.9.34.drv' failed with exit code 139;
       last 25 log lines:
       > calling 'fixupOutput' function hook '_doStrip'
       > stripping (with command strip and flags -S -p) in  /nix/store/2yw75vxwbwcfy0zmp0hxai35bv9g2rfd-rapid-photo-downloader-0.9.34/lib /nix/store/2yw75vxwbwcfy0zmp0hxai35bv9g2rfd-rapid-photo-downloader-0.9.34/bin
       > calling 'fixupOutput' function hook 'wrapQtAppsHook'
       > evaling 'fixupOutput' string hook 'if [ -z "${dontPatchELF-}" ]; then patchELF "$prefix"; fi'
       > shrinking RPATHs of ELF executables and libraries in /nix/store/wa6knpl2s391falpga12pppxw2xfxfg8-rapid-photo-downloader-0.9.34-dist
       > evaling 'fixupOutput' string hook 'if [[ -z "${noAuditTmpdir-}" && -e "$prefix" ]]; then auditTmpdir "$prefix"; fi'
       > checking for references to /build/ in /nix/store/wa6knpl2s391falpga12pppxw2xfxfg8-rapid-photo-downloader-0.9.34-dist...
       > evaling 'fixupOutput' string hook 'if [ -z "${dontGzipMan-}" ]; then compressManPages "$prefix"; fi'
       > calling 'fixupOutput' function hook '_moveLib64'
       > calling 'fixupOutput' function hook '_moveSbin'
       > calling 'fixupOutput' function hook '_moveSystemdUserUnits'
       > calling 'fixupOutput' function hook 'patchShebangsAuto'
       > patching script interpreter paths in /nix/store/wa6knpl2s391falpga12pppxw2xfxfg8-rapid-photo-downloader-0.9.34-dist
       > calling 'fixupOutput' function hook '_pruneLibtoolFiles'
       > calling 'fixupOutput' function hook '_doStrip'
       > evaling implicit 'postFixup' string hook
       > Rewriting #!/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/bin/python3.12 to #!/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4
       > wrapping `/nix/store/2yw75vxwbwcfy0zmp0hxai35bv9g2rfd-rapid-photo-downloader-0.9.34/bin/rapid-photo-downloader'...
       > calling 'postFixup' function hook 'pythonRemoveTestsDir'
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > calling 'postFixup' function hook '_makeSymlinksRelativeInAllOutputs'
       > calling 'postFixup' function hook '_multioutPropagateDev'
       > Running phase: installCheckPhase
       > /nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 1643:   814 Segmentation fault      (core dumped) $out/bin/rapid-photo-downloader --detailed-version
       For full logs, run 'nix log /nix/store/bh89z3syz1477rahakn5dy395608cy2c-rapid-photo-downloader-0.9.34.drv'.
```

### Additional context

The test that's failing here (to run the version) was added after the last build failure (see #207166), and seems to have done its job.

This has been failing for ~2 weeks or so. I assume due to python changes elsewhere since the package hasn't been touched in months.

### Notify maintainers

*none*

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0-dev-pre20240722-73c013a
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/dan/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/dan/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/dan/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/dan/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/6j6l75m3ymv1r6g1lrr5sjqb19qwmyhx-gnome-settings-daemon-46.0/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/llq8caxs0hjhm4vbws9rb6gj96y3bshb-lix-2.91.0-dev-pre20240722-73c013a/share`
 - nixpkgs: `/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source`

(the same failure also occurs with nix 2.18.5 as the builder)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
I belive this will be fixed by #325893 which is still afaik only on staging-next.

**Comment by dcarosone** [comment]
Thanks; indeed that looks very plausible.  Will track that PR merge, and close this when I can confirm.

**Comment by dotlambda** [comment]
It does build on staging-next.
