### ISSUE TITLE
Build failure: tuxedo-keyboard

### ISSUE THREAD

**Issue by SebRut** [NixOS/nixpkgs#329383]
### Steps To Reproduce

1. build tuxedo-keyboard within `nixos-rebuild --switch --upgrade-all`

### Build log

https://gist.github.com/SebRut/483911182d7b4f16c1754c7e256f8c08

### Notify maintainers

@blanky0230 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.5, NixOS, 24.11 (Vicuna), 24.11.20240620.d603719`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/xfpiyfgf6y30fxk5ngv0cjn474qfr3sj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SebRut** [comment]
Downgrading the kernel to 6.9 fixes the build. As `tuxedo-keyboard` is deprecated long fix could be something like `tuxedo-drivers` from https://github.com/NixOS/nixpkgs/pull/293017.

**Comment by xaverdh** [comment]
This should help: 
[fix-dot-owner.patch](https://github.com/user-attachments/files/16394088/fix-dot-owner.patch)

The upstream issue is [here](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/issues/182)
