### ISSUE TITLE
Update request: curl-impersonate 0.6.1 → 0.7.0 (yifeikong fork)

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#329301]
- Package name: curl-impersonate
- Latest released version: 0.7.0 (https://github.com/yifeikong/curl-impersonate fork)

- Current version on the unstable channel: 0.6.1
- Current version on the stable/release channel: 0.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

This was also discussed earlier in #285618 but the original upstream had bumped their version in time, hence the switch didn't happen. Now, however, the original hasn't had activity in 4 months, while the fork had a release last month and activity a couple weeks ago.

**Notify maintainers**

@deliciouslytyped

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by deliciouslytyped** [comment]
I don't have the mental capacity to look at this right now.

**Comment by eclairevoyant** [comment]
Do you mean you'd like to be removed from curl-impersonate specifically? Or do you want to be removed from the list across all of nixpkgs (I see you marked as maintainer for `debugedit` as well)?

**Comment by GGG-KILLER** [comment]
About this, the yifeikong fork isn't a perfect replacement as they've gotten rid of Firefox support.

I'm working on getting that fork building but ideally it should only be used for yt-dlp.
