### ISSUE TITLE
Build failure: step-cli

### ISSUE THREAD

**Issue by gauravjuvekar** [NixOS/nixpkgs#329329]
### Steps To Reproduce

1. build step-cli

### Build log

```
$ nix build github:NixOS/nixpkgs?rev=f95383724b9f736ff986c848a82b8f220ce1406f#step-cli --verbose
these 3 derivations will be built:
  /nix/store/w00x7fj5zmcmvpa8zcg4wrwcr2a9abh6-source.drv
  /nix/store/bbir65jdlw1xklrgzyc0jriynz2my07b-step-cli-0.27.2-go-modules.drv
  /nix/store/dlph1gwfz8ilwwmw3z4gmx06kfz0ay1r-step-cli-0.27.2.drv
building '/nix/store/w00x7fj5zmcmvpa8zcg4wrwcr2a9abh6-source.drv'...
error: hash mismatch in fixed-output derivation '/nix/store/w00x7fj5zmcmvpa8zcg4wrwcr2a9abh6-source.drv':
         specified: sha256-lM42KlTgOch6AwQIzvjQNH1wVfFikVI9rVgH2/2KyJE=
            got:    sha256-9w7rUtlLa1kl9oVboWZWj4eoZh+pPdGsEEQDWYdEMns=
error: 1 dependencies of derivation '/nix/store/dlph1gwfz8ilwwmw3z4gmx06kfz0ay1r-step-cli-0.27.2.drv' failed to build
```

### Additional context

Not sure what happened. Did upstream force-push update the tag?

### Notify maintainers

@isabelroses
@NickCao  

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240723.2874fc4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/3azana74br85nvlq2zrcbc29rq8hsmxw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by isabelroses** [comment]
seems to have built fine for me on latest, being 996ec7cce165075f1c1e6d9550630264a5773deb. 
`nix build -L github:nixos/nixpkgs/996ec7cce165075f1c1e6d9550630264a5773deb#step-cli`
