### ISSUE TITLE
typo in `pkgs/pkgs-lib/formats/hocon/default.nix`: `mkSubstition` should be `mkSubstitution`

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#329439]
https://github.com/NixOS/nixpkgs/blob/4ce93feb8424279f6420a8ab0fa657673db75a8f/pkgs/pkgs-lib/formats/hocon/default.nix#L73-L76C36

@h7x4

**Comment by eclairevoyant** [comment]
Next time please feel free to create a PR directly
