### ISSUE TITLE
Update request: joplin 2.14.1 → 3.0.13

### ISSUE THREAD

**Issue by mildebrandt** [NixOS/nixpkgs#329581]
- Package name: joplin
- Latest released version: 3.0.13

- Current version on the unstable channel: 2.14.1
- Current version on the stable/release channel: 2.14.1

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

No listed maintainer, and I'm unsure how to look up the last committer/author for nodejs applications. Nodejs applications seem to be a different beast that I'm unfamiliar with.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Zoriot** [comment]
Latest version is [3.0.15](https://github.com/laurent22/joplin/releases/tag/v3.0.15). A update would be very great.

**Comment by Zoriot** [comment]
#336324

**Comment by r-vdp** [comment]
>  #336324

That's the desktop application, this issue was about the CLI application, which was updated in https://github.com/NixOS/nixpkgs/pull/330568.

**Comment by mildebrandt** [comment]
Great, thanks!
