### ISSUE TITLE
Haskell "stack" package doesn't update to 1.6.1

### ISSUE THREAD

**Issue by eschnett** [NixOS/nixpkgs#32955]
## Issue description

I believe that the Haskell "stack" package is at version 1.6.1 in nixpkgs-unstable. I have confirmed this by looking at the Nix channel repository on Github (in the `nixpkgs-unstable` branch), where the version number 1.6.1. However, locally I only have version 1.5.1, which is missing a few crucial bug fixes.

### Steps to reproduce

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

```
$ nix-channel --update
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre122585.b212125b541/nixexprs.tar.xz’...
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre122585.b212125b541/nixexprs.tar.xz’... [5823/9422 KiB, 5817.2 KiB/s]
unpacking channels...
```

```
$ nix-env --upgrade
```
[no output]

```
$ ~/.nix-profile/bin/stack --version | head -n1
Version 1.5.1 x86_64
```

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/sgqgphi83sy17ifijjcgvzl4p1cp24p2-DarwinTools-1
  /nix/store/y23k84515l03j01jrdyp4ls8b1bms0yv-nix-info
fetching path ‘/nix/store/sgqgphi83sy17ifijjcgvzl4p1cp24p2-DarwinTools-1’...

*** Downloading ‘https://cache.nixos.org/nar/0xww4pk0w6d9gh3j2clmp0hx8kf94pzp2k99h54raidb6wf0s1ni.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/sgqgphi83sy17ifijjcgvzl4p1cp24p2-DarwinTools-1’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4648  100  4648    0     0   4648      0  0:00:01 --:--:--  0:00:01 22133

fetching path ‘/nix/store/y23k84515l03j01jrdyp4ls8b1bms0yv-nix-info’...

*** Downloading ‘https://cache.nixos.org/nar/0sa0vfimafqz6n0pxhpsmws24qlb27bwalcbkv53a770yx7gwghp.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/y23k84515l03j01jrdyp4ls8b1bms0yv-nix-info’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1680  100  1680    0     0   1680      0  0:00:01 --:--:--  0:00:01  8275

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.3.0, macOS 10.13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(eschnett): `"nixpkgs-18.03pre122585.b212125b541"`
 - channels(root): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/eschnett/channels/nixpkgs`
```

Also:
```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

As you see, the output of `nix-channel --list` and the actual channel differ. Is this to be expected? Is the respective channel `nixpkgs-18.03pre122585.b212125b541` the current one? If not, how can I update?

This is MacOS, and I've had a few problems installing Nix. The default install doesn't quite work. It subscribes me to a channel that is managed by `root`, and I cannot issue any Nix commands since I don't have write permissions to `/nix`. My remedy was (as I am told by Google) to set `NIX_REMOTE=daemon`, and to manually remove the symbolic link to root's channel in my `.nix-defexpr` directory.

**Comment by orivej** [comment]
You need dba09a202b69540be3c1780a9fde04ff84551aa2 and nixpkgs-unstable channel is not there yet: https://howoldis.herokuapp.com/
You can override the channel for one operation with `nix-env -f https://github.com/NixOS/nixpkgs/archive/master.tar.gz -iA stack`.

**Comment by eschnett** [comment]
Thank you! This worked. https://howoldis.herokuapp.com/ is exactly what I was looking for.
