### ISSUE TITLE
Build failure: quirc

### ISSUE THREAD

**Issue by chr314** [NixOS/nixpkgs#329642]
### Steps To Reproduce

1. `sudo nixos-rebuild switch --upgrade-all`

### Build log

```
ln: failed to create symbolic link '/nix/store/igc14rpxdci0pjw4yw7x2amx4qxwia6k-quirc-1.2/lib/libquirc.so': File exists
/nix/store/5r0df66ikad3xw06azlqvswcvncll8wa-stdenv-linux/setup: line 193: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/2qfkvyq0ccnbw4bb91q83rx9pcd96ad1-quirc-1.2.drv' failed with exit code 1
```

### Additional context

Just trying to update the system
Using unstable

### Notify maintainers

@toonn

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11pre655136.1d9c2c9b3e71`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixos-stable-23.11, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by toonn** [comment]
This should've been fixed by #328915, has that not made it to the channel you're using?

**Comment by chr314** [comment]
I'm using unstable, i see that the patch its not there yet https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/graphics/quirc/default.nix#L58

just have to wait a little bit

thanks

**Comment by Turmaxx** [comment]
Apparently we are facing the same issue, my issue #329871. I'm also on the unstable channel.
