### ISSUE TITLE
haskellPackages.cabal-helper build failed on current master

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#32969]
## Issue description
Example error:

    Setup.hs:87:60: error:
        • Couldn't match expected type ‘UnitId’
                      with actual type ‘PathTemplate’
        • In the third argument of ‘substPathTemplate’, namely
            ‘(progPrefix lbi)’
          In the expression:
            substPathTemplate (packageId pd) lbi (progPrefix lbi)
          In an equation for ‘progprefix’:
              progprefix = substPathTemplate (packageId pd) lbi (progPrefix lbi)
      |
    87 |         progprefix = substPathTemplate (packageId pd) lbi (progPrefix lbi)
      |                                                            ^^^^^^^^^^^^^^

Here it is full log : [cabal-helper.log](https://github.com/NixOS/nixpkgs/files/1581975/cabal-helper.log)

### Steps to reproduce
    nix-shell -p haskellPackages.cabal-helper -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz 2> cabal-helper.log

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.71, NixOS, 18.03.git.ab623d8 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre123130.1bc288591ea"`
 - channels(wizzup): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

---

`cabal-helper` seem to [support](https://gitlab.com/dxld/cabal-helper/pipelines/15274061/builds) ghc 8.2  but I can't find `cabal-helper` on [lts-10](https://www.stackage.org/lts-10.0), should it be marked as broken?

I would love to try patching but I don't know the process. If there is any example for me to study, please tell me.

**Comment by turion** [comment]
Looking at [this issue](https://github.com/DanielG/ghc-mod/issues/909), I would have thought that this is rather related to cabal 2.0, but I don't understand it.

When I do the following steps, I can build it (manually) without errors:
```
cabal get cabal-helper
cd cabal-helper-0.7.3.0
cabal sandbox init
cabal install --only-dependencies
cabal build
```

So somehow when installing the derivation, the environment must be set up incorrectly somehow.

**Comment by turion** [comment]
The problem seems to be that cabal-helper has a `Custom-Setup` section that restricts to `Cabal<1.25`, but this restriction is not respected by nix. See here: https://hackage.haskell.org/package/cabal-helper-0.7.3.0/src/cabal-helper.cabal

**Comment by turion** [comment]
Well, here is something that doesn't work: Adding the following lines to `nixpkgs/pkgs/development/haskell-modules/configuration-ghc-8.2.x.nix`:

```nix
# cabal-helper-0.7.3.0 needs Cabal<1.25
  cabal-helper = overrideCabal super.cabal-helper (drv: {
       setupHaskellDepends = [
         self.base self.Cabal_1_24_2_0 self.containers self.directory self.filepath
         self.process self.template-haskell self.transformers
       ];
  });
```

**Comment by turion** [comment]
Part of the problem is that nix doesn't really invoke cabal to build the package. I.e., try the following:

```
nix-shell -p haskell.compiler.ghc821
cabal get cabal-helper
cd cabal-helper-0.7.3.0
ghc Setup.hs
```
This will fail with the same error, since ghc doesn't care about the `Cabal` library version.

**Comment by Synthetica9** [comment]
This is caused by:

```
commit d5676b04331efa730aa86c6a3c6cc0769b44a1e1
Author: Peter Simons <simons@cryp.to>
Date:   Tue Dec 19 15:54:30 2017 +0100

    switch "haskellPackages" to GHC 8.2.2 for LTS 10.x

:040000 040000 fe2ba67a117cb639b4d7049a889ca8a95acd49f1 8b5cb71bb5b483bccc8aa436b8154a55524e3f13 M   pkgs
```

Found with git bisect.

```
git bisect start master master~1000
git bisect run nix-build . -A haskellPackages.cabal-helper
```

**Comment by turion** [comment]
Yes, that's to be expected. GHC 8.2.2 selects a newer version of the `Cabal` library, without checking whether `cabal-helper` builds with it correctly. I guess this would be resolved if `cabal-helper` updated to version `0.8` on hackage. Otherwise, we'd have to hack the derivation quite a lot to depend on an older `Cabal` library version.

**Comment by wanggang1** [comment]
any suggested solution with this issue?  thanks

**Comment by wizzup** [comment]
The problem is gone. No longer reproducible. I am closing this issue.

**Comment by wanggang1** [comment]
@wizzup I'm seeing a similar issue with the configuration I have.  I was able to build Haskell environment couple of months ago with the same NIx configuration, but now I see this issue.  Here is my configuration and error messages, https://gist.github.com/wanggang1/ad1b2c582a3bf0763538041be2221670.  My nix channel is https://nixos.org/channels/nixpkgs-unstable.  Any help would be greatly appreciated, thanks!

**Comment by turion** [comment]
@wanggang1 have you updated channels? In up to date `nixos-unstable` (which is behind `nixpkgs-unstable`), you should get `cabal-helper-0.8.0.0`, which doesn't have the bug anymore.

**Comment by wanggang1** [comment]
@turion We config our development environment with ~/.nixpkgs, not using NixOS.  So by just adding channel nixos-unstable, it could not pick up cabal-helper-0.8.0.0, here is our ~/.nixpkgs/config.nix file and errors when run nix-env -iA nixpkgs.haskellEnv, https://gist.github.com/wanggang1/7267f31fb3591b469bcbd1f2990a9a4f.  Should we config our environment in a different way so we could uses channel nixos-unstable?  Thanks for help!

**Comment by turion** [comment]
@wanggang1 nixpkgs always contains all changes from nixos, if I'm not mistaken. So you can use nixpkgs, that's no problem. (The advantage of nixos is that there is continuous integration, i.e. all packages are tested and built before something is pushed to the channel.)

What you need to do is update your channel, something like `nix-channel --update`, depending on your exact configuration. If you do that, and rerun the command you mentioned, it should not complain about `cabal-helper` anymore.
