### ISSUE TITLE
Build failure: nomachine-client - hash mismatch

### ISSUE THREAD

**Issue by RemcoSchrijver** [NixOS/nixpkgs#329713]
### Steps To Reproduce

1. build nomachine-client

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/8l9aq5mhv2629wn2sc2zzs3cvg33hl4i-nomachine_8.4.2_1_x86_64.tar.gz.drv':
         specified: sha256-r4yRmnMd6uNay7CqmyqYj9F6huoqD8eBby+oDNk1T34=
            got:    sha256-Ba4kzbyj/MblReoqPyBg9nDhD/MP76T/dT+D7UP4nIE=
error: 1 dependencies of derivation '/nix/store/pa7gpxgm3j0wn8jq64gb8c6ay862b55q-nomachine-client-8.4.2.drv' failed to build
```

### Additional context

Seems like nomachine changed their tar file.

### Notify maintainers

@talyz 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.05 (Uakari), 24.05.20240521.3eaeaeb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/57rsy3z79kvxah2l4j13bjwpsgxkbhby-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by miketth** [comment]
It seems that NoMachine has removed the `tar.gz` from their website and the link is now a redirect to the homepage. The new latest version is `8.13.1_1`.

**Comment by thibaultmol** [comment]
? this url works
https://download.nomachine.com/download/8.13/Linux/nomachine_8.13.1_1_x86_64.tar.gz
