### ISSUE TITLE
google-chrome-{beta,unstable}: error while loading shared libraries: libatk-bridge-2.0.so.0

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#32978]
## Issue description

```
$ google-chrome-beta 
/nix/store/rlw2lzkwn0zf9hfmvhkdm8cqzimhlc8z-google-chrome-beta-64.0.3282.24/share/google/chrome-beta/google-chrome-beta: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
```

Same issue with ```google-chrome-unstable```

```google-chrome-stable``` works well

### Steps to reproduce

install and run ```google-chrome-beta```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.71, NixOS, 18.03.530+ (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5810_5d5b931f`
 - nixpkgs: `/nix/store/rqwcwpqglbw602gpb1252kl19vqsacwh-nixpkgs-master`

**Comment by volth** [comment]
Seems like autoclosing (when PR contains "Fixes #XXXXX") is broken

**Comment by joachifm** [comment]
The PR doesn't fix the issue?

**Comment by volth** [comment]
sorry, I misunderstood how Github works

**Comment by YorikSar** [comment]
This issue still there in 17.09. It seems #33062 needs to be cherry-picked there too (it applies cleanly).

**Comment by aljones15** [comment]
Glad to know this is fixed but I upgrade nix-os yesterday and the current versions of google-chorme-stable and beta both give this error.
