### ISSUE TITLE
Update request: `zed-editor` 0.141.3 → 0.145.1

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#329783]
- Package name: `zed-editor`
- Latest released version: `0.145.1`

- Current version on the unstable channel: `0.141.3`
- Current version on the stable/release channel: `0.135.2`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@GaetanLepage @niklaskorz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperKenVery** [comment]
+1, would love to use remote develop!

**Comment by GaetanLepage** [comment]
Let's first wait for https://github.com/NixOS/nixpkgs/pull/324549 (currently on `staging-next`) to land on `master`. I will then take care of updating to the latest version.
