### ISSUE TITLE
Package and provide service module for Baikal

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#32971]
## Issue description

I would like to have [baikal](https://github.com/sabre-io/Baikal) as a nixos service. This issue exists mainly to push myself to package it. Feel free to help me out, though!

Also: I have no experience with PHP packaging (and little with service stuff) so I appreciate any help!

**Comment by ambroisie** [comment]
@matthiasbeyer unless my search.nixos.org-fu is failing me, I cannot find this module.

Did you end up packaging it and adding the module, or did you close this issue after deciding against it?

**Comment by matthiasbeyer** [comment]
Well... this was more than 5 years ago. I honestly do not remember! :laughing:
