### ISSUE TITLE
Package request: Nitroshare

### ISSUE THREAD

**Issue by theshatterstone** [NixOS/nixpkgs#329717]
**Project description**

A cross-platform network file transfer application.
It's a simple file transfer app with Linux support.
And the only app I'm missing on NixOS.

**Metadata**

* homepage URL: https://nitroshare.net
* source URL: https://github.com/nitroshare/nitroshare-desktop
* license: MIT
* platforms: Linux, Darwin & Windows

**Comment by eclairevoyant** [comment]
It hasn't had a release in 7 years, is this really safe for a network-connected app? Any reason more maintained options like `syncthing` don't work for you?

**Comment by theshatterstone** [comment]
@eclairevoyant I'll admit I didn't even realise this! I guess I'll just switch to warpinator. Turns out it has an Android version! Closing this.
