### ISSUE TITLE
Rendering crashing in kdenlive (again)

### ISSUE THREAD

**Issue by RuRo** [NixOS/nixpkgs#329747]
### Describe the bug

Rendering a project in Kdenlive with default rendering settings leads to the following error:

```
[libprotobuf ERROR /build/source/src/google/protobuf/descriptor_database.cc:642] File already exists in database: opencv-caffe.proto
[libprotobuf FATAL /build/source/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
what(): CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
```

### Steps To Reproduce

1. ```
    nix run github:nixos/nixpkgs/68c9ed8bbed9dfce253cc91560bf9043297ef2fe#kdePackages.kdenlive
    ```
    (`68c9ed8b...` is the latest revision of `nixpkgs/nixos-unstable` at the moment of writing this)

2. Add any clip to the timeline (for example, drag in an image)

3. Click "Render..." > "Render to File"

You might need to use `plasma5` as your desktop manager to reproduce this issue. There is [a discourse thread](https://discourse.nixos.org/t/rendering-crashing-in-kdenlive-in-24-05/46391) claiming that this crash doesn't happen on Plasma 6. I am using Plasma 5, but I am currently unable to verify if Plasma 6 would fix this issue (Plasma 6 is broken for me for unrelated reasons).

### Expected behavior

Render should succeed.

### Additional context

See issue #293315 for the previous instance of this problem.

### Notify maintainers

@ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000 @ttuegel

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RuRo** [comment]
`kdePackages` is plasma6? Wow, that's quite a foot gun. Shouldn't it be called `plasma6Packages`?

Also, `nix run github:nixos/nixpkgs/68c9ed8bbed9dfce253cc91560bf9043297ef2fe#plasma5Packages.kdenlive` fails with the same error.

**Comment by K900** [comment]
It really should not matter, and `kdePackages` will (once `plasma5Packages` is entirely gone) be whatever versions upstream ships.

**Comment by RuRo** [comment]
@K900 it seems that the problem either wasn't fixed or has resurfaced again?

I was able to reproduce the exact same error with
```sh
nix run github:nixos/nixpkgs/a58bc8ad779655e790115244571758e8de055e3d#plasma5Packages.kdenlive
```
and
```sh
nix run github:nixos/nixpkgs/a58bc8ad779655e790115244571758e8de055e3d#kdePackages.kdenlive
```
(where `a58bc8ad...` is the latest revision of `nixpkgs/nixos-unstable` at the moment of writing this)

**Comment by K900** [comment]
Please try again after the staging-next merge (which should make its way to unstable in a few hours).

**Comment by RuRo** [comment]
I will.

Could you explain why staging-next is relevant in this case, though? I am just curious.

I checked using https://nixpk.gs/pr-tracker.html and in the github UI directly, and it seems that the changes from #330346 should be already present in revision `a58bc8ad...`.

**Comment by K900** [comment]
staging-next reshuffles protobuf versions again.

**Comment by RuRo** [comment]
I wasn't sure which staging-next merge you were originally talking about, so I tried the same thing with commits c3aa7b8938b17aebd2deecf7be0636000d62a2b9 (current nixos-unstable), 2b6097bbb8d67750ee6ffe621fd954c9444febb3 (current staging-next) and 199d21a8330f681f71436014375ea9cd5b0dc6e9 (current master) and I am still getting the same error.

Can you reopen this issue, or should I open a new one?

**Comment by K900** [comment]
That sounds very wrong because you have defaults from two different kdenlive versions in there.

**Comment by RuRo** [comment]
> That sounds very wrong because you have defaults from two different kdenlive versions in there.

I can tell you that I've never touched `kdenliverc` prior to this debugging session. I didn't even know it existed. Those lines seem to be automatically populated on demand. Most likely, these lines were simply generated at different times, and so they picked up different paths to the "current" version of `kdenlive`.

Also, the fact that these paths are different **from each other** is mostly irrelevant in this case. The real problem is that they are cached once and aren't updated when a different version of `kdenlive` is used.

**Comment by markasoftware** [comment]
I can confirm the same issue and fix as @ruro -- after upgrading kdenlive and melt, kdenlive saved an old path to `kdenlive_render` in `~/.config/kdenliverc` and removing that line allowed me to render again.
