### ISSUE TITLE
cassandra cqlsh is not working

### ISSUE THREAD

**Issue by pallix** [NixOS/nixpkgs#329864]
### Describe the bug

The `cqlsh` CLI tool provided by the `cassandra` package throws a Python related error when executed. 

```
> nix shell nixpkgs#cassandra
> cqlsh

Python Cassandra driver not installed, or not on PYTHONPATH.
You might try "pip install cassandra-driver".

Python: /nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/bin/python3
Module load path: ['/nix/store/0lvxvbpdnz78gm1ph8n7ymh3jv3zfvis-cassandra-4.1.2/bin', '/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python311.zip', '/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11', '/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/lib-dynload', '/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/site-packages']

Error: No module named 'cassandra'
```

### Steps To Reproduce

1. > nix shell nixpkgs#cassandra
2. > cqlsh

### Expected behavior

I expect the CLI tool to run without throwing a Python error

### Additional context

I'm testing with nixpkgs unstable.

### Notify maintainers

@roberth @turion @neosimsim 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pallix** [comment]
@@roberth any chance you could have a look at the problem?

**Comment by turion** [comment]
CC @ris

**Comment by risicle** [comment]
Suggest you use `wrapPythonPrograms` for `cqlsh` instead of plain `wrapProgram`, and supply the `cassandra-driver` in its pythonpath - grep nixpkgs to see usage examples.

Though I suggest taking note of the dependency footprint the `cassandra-driver` package will add to this.

**Comment by pallix** [comment]
Thanks. I have created a PR with a fix that work locally for me. I won't be available for the next weeks so feel free to improve and merge it without me if you have time.
