### ISSUE TITLE
lightdm: Shutdown and restart buttons no longer available in GTK greeter

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#32984]
## Issue description

As of Nixpkgs 32a00e92906cc59372d06d50e2f04eae74661995 the ability to shutdown and restart NixOS from the lightdm GTK greeter is unavailable.

Here's what the greeter looked like before:
![nixos-good-afe9649210c](https://user-images.githubusercontent.com/13485450/34306132-90edd0d0-e70f-11e7-93db-03b9825db7fa.png)

And here's what it looks like after:
![nixos-bad-1bc288591ea](https://user-images.githubusercontent.com/13485450/34306149-a90f9108-e70f-11e7-9dfb-3fc14c9acbe3.png)

### Steps to reproduce

1. `git clone https://github.com/NixOS/nixpkgs`
2. `cd nixpkgs`
3. `git checkout 32a00e92906cc59372d06d50e2f04eae74661995`
4. `cp /etc/nixos/configuration.nix ~./`
5. Edit copy of `configuration.nix` so that `lightdm` is enabled. Here's an example:

```
{ config, lib, pkgs, ... }:

{
  networking.networkmanager.enable = true;
  boot.loader.systemd-boot.enable = true;
  networking.hostName = "lightdm-test";

   i18n = {
     consoleFont = "Lat2-Terminus16";
     consoleKeyMap = "us";
     defaultLocale = "en_US.UTF-8";
   };

  time.timeZone = "US/Eastern";
   environment.systemPackages = with pkgs; [
   ];

  services.xserver = {
  	enable = true;
  	layout = "us";
	windowManager.i3.enable = true;
	displayManager.lightdm.enable = true;
  };

  users.users.emmanuel = {
    isNormalUser = true;
  };

  system.stateVersion = "18.03";
}
```
6. `export NIXPATH=nixpkgs=$PWD:nixos-config=$PWD/configuration.nix:/nix/var/nix/profiles/per-user/root/channels`
7. `nixos-rebuild build-vm`
8. `./result/bin/run-lightdm-test-vm`

NOTE: I identified the commit using `git bisect` and `nixos-rebuild build-vm`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 18.03pre123130.1bc288591ea (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre123130.1bc288591ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by codyopel** [comment]
This is an upstream change in lightdm-gtk-greeter.

Fix via config: https://github.com/triton/triton/commit/22da0de58fa49148845f3dcedfcd869b601ba098

**Comment by vcunat** [comment]
Closely related: https://github.com/NixOS/nixpkgs/pull/33032

**Comment by emmanuelrosa** [comment]
#33032 was merged 👍
