### ISSUE TITLE
Update request: libplacebo 6.338.2 → 7.349.0

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#329857]
- Package name: [libplacebo](https://code.videolan.org/videolan/libplacebo)
- Latest released version: [7.349.0](https://code.videolan.org/videolan/libplacebo/-/tags/v7.349.0)

- Current version on the unstable channel: [6.338.2](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/libplacebo/default.nix#L72)
- Current version on the stable/release channel: [6.338.2](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/libraries/libplacebo/default.nix#L72)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@primeos 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Sigmanificient** [comment]
https://github.com/NixOS/nixpkgs/pull/324213
