### ISSUE TITLE
livebook: doesn't work as a service

### ISSUE THREAD

**Issue by q60** [NixOS/nixpkgs#329869]
### Describe the bug
`livebook` doesn't seem to work as a module

### Steps To Reproduce
1. follow livebook service [example](https://nixos.org/manual/nixos/stable/#module-services-livebook-basic-usage)
2. enter any env variables or use environment file with any variables
3. `nixos-rebuild switch`

first of all, its systemd unit does not appear to start by default. so i did `systemctl --user daemon-reload` and `systemctl --user start livebook.service`

but it doesn't work, i can't access it either by IP or by domain, which is set up in my nginx configuration as a reverse proxy. some strange things happen while the unit is active [1st screenshot]. also there's nothing in the journal except info messages about the unit itself
as i see it, livebook fails to start, but the service is active because *something* is going on with `/dev/urandom` inside this `..livebook-wrapped-wrapped` wrapper script

i tried to make it work several different ways: from using `environment` option instead of my environment file to writing my very own systemd unit in NixOS configuration file, also using home-manager like so:
```nix
  # ...
  systemd.user.services = {
    livebook = {
      Install = { WantedBy = [ "default.target" ]; };

      Service = {
        ExecStart = "${pkgs.livebook}/bin/livebook start";
        KillMode = "mixed";
        Restart = "always";
        EnvironmentFile = "/var/lib/livebook.env";
      };
    };
  };
  # ...
```

but that doesn't work too. surely i tried starting livebook manually - `LIVEBOOK_PORT=3333 LIVEBOOK_PASSWORD=pretty_password LIVEBOOK_DATA_PATH=/var/www/livebook livebook start`

and it works as expected [2nd screenshot]

### Expected behavior
1. livebook module/service works and is accessible
2. custom systemd livebook unit works and is accessible

### Screenshots

| ![screen 1](https://github.com/user-attachments/assets/0fb05205-9673-4494-a0ad-e63fb0ff097e) |
|----------------------------------------------------------------------------------------------|
| ![screen 2](https://github.com/user-attachments/assets/4d08309f-5bf4-40bf-86e3-e4a4b4da0342) |

### Additional context
NixOS 24.05.3214.575f3027caa1 (Uakari) x86_64 running on a VPS

### Notify maintainers

cc @Munksgaard 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.05 (Uakari), 24.05.3214.575f3027caa1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Munksgaard** [comment]
@q60: Thank you for reporting this issue. I am ashamed to admit that I have actually known about this for a while now, without doing anything about it. Now that someone else is having problems with the service, I'll prioritize getting something done soon.

I'm not actually sure what's going wrong, but it seems like the service hangs in the `tr` command. As far as I remember it ends up using 100% cpu and just loop forever. I'll try to take a look at it later this week.

**Comment by Munksgaard** [comment]
@scvalex Perhaps you have encountered this issue as well?

**Comment by scvalex** [comment]
I've seen this before and I think it was because livebook was trying to generate a `LIVEBOOK_COOKIE` in some weird way.

This is my current configuration which works:

```
      services.livebook = {
        enableUserService = true;
        package = pkgs.livebook;
        environmentFile = "/home/scvalex/repo/infra/secrets/passwords/livebook";
        extraPackages = with pkgs; [ gnumake gcc git ];
      };
```

```
LIVEBOOK_PASSWORD = "a long string which is my password"
LIVEBOOK_NODE = "livebook"
LIVEBOOK_PORT = 30123
LIVEBOOK_IFRAME_PORT = 30124
LIVEBOOK_COOKIE = "livebook"
```

@q60 Could you try manually setting a `LIVEBOOK_COOKIE` in your service setup, please?

**Comment by q60** [comment]
@Munksgaard a screenshot from `btop` filtering cpu usage ![image](https://github.com/user-attachments/assets/a87d643a-9fbf-40f5-be7c-e6118d9d6c35)
not so much is used

@scvalex i've tried setting up a cookie and you can see it works - https://livebook.hiiaka.xyz/ :pleading_face:
thanks!!!! >~<

**Comment by scvalex** [comment]
The issue seems to have been described and debugged here: https://github.com/livebook-dev/livebook/issues/2691

The solution is to set `IgnoreSIGPIPE=false` in the systemd service configuration.  I'll mint a PR.
