### ISSUE TITLE
fetchurl: warn on GitHub/GitLab ref archives

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#32999]
`fetchurl` should warn on fetches of ref archives, telling to use `fetchFromGitHub` or `fetchFromGitLab` instead. I'm not sure whether it's better to place warning in the builder or use `lib.warn`, probably having it in the builder would be enough.

See #32997.

**Comment by yegortimoshenko** [comment]
See #32997.

**Comment by orivej** [comment]
> `fetchurl` should warn on fetches of unstable archives

Correction: only if `postFetch` is empty. (Archive fetchers are implemented as `fetchurl { postFetch = ...; }`.

> I'm not sure whether it's better to place warning in the builder or use `lib.warn`

The latter is better because everyone will notice it during full eval, and it can be added and changed without a mass rebuild.

**Comment by vcunat** [comment]
EDIT3: not a mass rebuild :-)  They're fixed-output derivations, and the output is kept the same.  (Derivation hash changes, but output path is the same and the change doesn't "propagate".)

**Comment by exFalso** [comment]
Just saw this warning, why is fetchFromGitHub preferred? I'm currently using fetchurl because it's simply faster, especially with repos with many commits

**Comment by yegortimoshenko** [comment]
@exFalso `fetchurl` `sha256` is a checksum of `.tar.gz` archive rather than checksum of its contents. When GitHub drops `.tar.gz` archive from its cache and rebuilds it, its checksum changes, despite the fact that contents (and as a result, contents checksum) stays the same. If you prefer `fetchurl`-like interface, use `fetchzip`, otherwise use `fetchFromGitHub` ^^

**Comment by kvtb** [comment]
This is totally misleading warning.

1. `fetchurl` of "https://github.com/*/archive/*" keeps the tarball packed while `fetchFromGitHub` does unpack it 
2. as a side effect unpacking to Nix Store erases timestamps on the source files, breaking `$SOURCE_DATE_EPOCH` logic (https://github.com/NixOS/nixpkgs/issues/112595)

I could say that `fetchurl` behaves better in both aspects and should be preferred.
Anyway, `fetchFromGitHub` is not a replacement of `fetchurl`, they are much too different.

---

`.tar.gz` hashes is definitively is the issue to solve, probably the non-determenism has to be removed after download such tarballs (like `fetchpatch` removes  non-determenism in `.patch` files downloaded from Github)
