### ISSUE TITLE
Build failure: gitbutler

### ISSUE THREAD

**Issue by matyas-cimbulka** [NixOS/nixpkgs#329918]
### Steps To Reproduce

1. export NIXPKGS_ALLOW_UNFREE=1
2. nix build --impure nixpkgs#gitbutler

### Build log

[Build log](https://gist.github.com/matyas-cimbulka/6689756c8c90cfe5f6ac9a890a3ba9ff)

### Additional context

Build fails regardles of how its triggered. I tried installing using configuration.nix, home-manager, nix profile, nix build and nix run.

### Notify maintainers

@getchoo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/afawjm6nv8m5aagkcqxlxgrr5qpyh6cm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
Should be fixed in https://github.com/NixOS/nixpkgs/pull/328302

**Comment by matyas-cimbulka** [comment]
Awesome! Thank you.
