### ISSUE TITLE
GDM crash

### ISSUE THREAD

**Issue by matteo-pacini** [NixOS/nixpkgs#330027]
### Describe the bug

- Ran a nix flake update on my configs, and updated my laptop (Razer Laptop / NVIDIA)
- GDM is not starting anymore - I get a white screen saying that an error has occurred

### Expected behavior

GDM should start

### Screenshots

Got this bit from the logs:

```
Jul 25 23:05:08 CauldronLake org.gnome.Shell.desktop[1613]: /nix/store/d5r60vc12j7y0la5qlcjk7mln9ddyj8m-mutter-46.2/libexec/mutter-x11-frames: error while loading shared libraries: /nix/store/7z8rhb5irj1fzymp4xz5062ydpqhynim-vulkan-loader-1.3.283.0/lib/libvulkan.so.1: file too short
Jul 25 23:05:08 CauldronLake .gnome-shell-wr[1586]: Failed to load shared library '/nix/store/1m8xb8g1qkrz9nigy2qb3jm0fjadb9xy-gtk4-4.14.4/lib/libgtk-4.so.1' referenced by the typelib: /nix/store/7z8rhb5irj1fzymp4xz5062ydpqhynim-vulkan-loader-1.3.283.0/lib/libvulkan.so.1: file too short
Jul 25 23:05:08 CauldronLake .gnome-shell-wr[1586]: JS ERROR: GLib.Error g-invoke-error-quark: Could not locate gdk_set_allowed_backends: /nix/store/7z8rhb5irj1fzymp4xz5062ydpqhynim-vulkan-loader-1.3.283.0/lib/libvulkan.so.1: file too short
                                                    @resource:///org/gnome/shell/ui/environment.js:379:1
Jul 25 23:05:08 CauldronLake .gnome-shell-wr[1586]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
Jul 25 23:05:08 CauldronLake gnome-session[1558]: gnome-session-binary[1558]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
Jul 25 23:05:08 CauldronLake gnome-session-binary[1558]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
```

### Additional context

Configs: https://github.com/matteo-pacini/nixos-configs/tree/master/hosts/CauldronLake
Hardware bit: https://github.com/matteo-pacini/nixos-configs/blob/master/hosts/CauldronLake/hardware.nix

NVIDIA version seems to be the same between the healthy and failing generation - `v550.78`.
Rolling back kernel to 6.8 didn't fix the issue.

### Notify maintainers

@NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.10, NixOS, 24.05 (Uakari), 24.05.20240722.575f302`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/114462g9fhfa5ck1ssribfdh7wlk9m1s-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
file too short sounds to me like something is corrupted. Could you please [verify the path](https://nix.dev/manual/nix/2.18/command-ref/nix-store/verify-path)?

**Comment by matteo-pacini** [comment]
Thank you @jtojnar , running a full `nix-store --verify --check-contents --repair` fixed all the issues
