### ISSUE TITLE
Build failure: pkgsLLVM.makeBinaryWrapper

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#330059]
### Steps To Reproduce

1. build *something which uses `makeBinaryWrapper`* (easily `perl.withPackages []`)

### Build log

```
clang: error: unable to execute command: Executable "ld" doesn't exist!
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Notify maintainers

No maintainers, blame says @tie last made a modification.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tie** [comment]
>No maintainers, blame says @tie last made a modification.

Hm, I can’t recall changing anything remotely related to LLVM and/or wrapper stuff recently. Which file(s) are you referring to?
