### ISSUE TITLE
Package request: rsbuild

### ISSUE THREAD

**Issue by LennyLizowzskiy** [NixOS/nixpkgs#330102]
The Rspack-based build tool

Rsbuild provides rich build features, including the compilation of TypeScript, JSX, Sass, Less, CSS Modules, Wasm, and others. It also supports Module Federation, image compression, type checking, PostCSS, Lighting CSS, and more.

**Metadata**

* homepage URL: https://rsbuild.dev/
* source URL: https://github.com/web-infra-dev/rsbuild
* license: MIT
* platforms: NPM & Rust package

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by charludo** [comment]
Is this actually completed?

**Comment by LennyLizowzskiy** [comment]
from my understanding it should be installed as dev-package in a project and be used through npx or an alternative

**Comment by charludo** [comment]
> from my understanding it should be installed as dev-package in a project and be used through npx or an alternative

Ahhhh, alright. Makes sense, thanks.
