### ISSUE TITLE
kpcli: missing KDBX4 support

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#330177]
### Describe the bug
When i try to open a .kdbx file generated by `keepassxc`, i'm getting:
```
Perl module File::KDBX is required for KDBX4 support.
Without it, KDBX4 files can only be imported.
 - To import a KDBX v4 file, use the import command.
 - For details, see: help import
```

Can you please add this module to the package?

### Steps To Reproduce
1. `kpcli --kdb=filename.kdbx`

### Notify maintainers
@j-keck

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240725.5ad6a14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #348984
