### ISSUE TITLE
Feature request: `allowUnreproducibleOptimizations` nixpkgs config option

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#330124]
## Rationale

Bit-for-bit reproduciblity is a sensible default, especially considering that nix uses a binary cache by default. However, some users would prefer to either get additional performance (python, for example, gains 10-15% real-world-performance faster with PGO, and up to 40% better scores in synthetic benchmarks) or better battery life (such as with my case).

## Proposed Solution

A nixpkgs config option, `allowUnreproducibleOptimizations`, which can be used by derivations as the default value for parameters like:

https://github.com/NixOS/nixpkgs/blob/da8fd5be9f9ae454e56fe8ef69931cff19f30920/pkgs/development/interpreters/python/cpython/default.nix#L67

**Comment by MrQubo** [comment]
This has potential of causing huge builds. Maybe it would be better to combine this with `impureUseNativeOptimizations`?

**Comment by BaerLKR** [comment]
Is there even a difference?
Sorry if I don't quite understand the concepts but from what I have read about `impureUseNativeOptimizations` it should have the same effect as the changes made in the pull request linked above

**Comment by Pandapip1** [comment]
Oh, I didn't realize `impureUseNativeOptimizations` existed. Thanks!

**Comment by MrQubo** [comment]
It's different. `impureUseNativeOptimizations` adds compilation flags like `-march=native`.
What @Pandapip1 proposed is to add option to enable profile-guided optimizations.

**Comment by Pandapip1** [comment]
I'm pretty sure `impureUseNativeOptimizations` enables PGO.

**Comment by MrQubo** [comment]
I'm pretty sure it doesn't.
It only adds `-march=native` flag:
https://github.com/NixOS/nixpkgs/blob/9c038d91edcf42ade2e4bc87a054068dbdba4f71/pkgs/stdenv/adapters.nix#L290-L300

**Comment by Pandapip1** [comment]
@MrQubo that seems like a flaw with `impureUseNativeOptimizations` then, as it really should enable PGO by default. I'm not experienced enough with PGO to know where to start modifying that though.
