### ISSUE TITLE
nixos-generate-config: enable tp_smapi for old ThinkPads

### ISSUE THREAD

**Issue by lukateras** [NixOS/nixpkgs#33026]
See: http://www.thinkwiki.org/wiki/Tp_smapi

**Comment by volth** [comment]
"If you are installing on a recent Thinkpad that has an Ivy Bridge or newer processor (X230, T430, T530, etc.), tp_smapi will not work."

Although X220 seems to be quite popular here

**Comment by zarelit** [comment]
Since it's hard to detect all the possible hardware correctly I'd rather delegate this to the user. Maybe it could be worth mentioning  [nixos-hardware](https://github.com/NixOS/nixos-hardware) and its usage in the NixOS manual

**Comment by yegortimoshenko** [comment]
It's rather easy, and the proper place to do it is in `nixos-generate-config`. We already do that in `nixos-hardware`, and it's less than ideal.

**Comment by zarelit** [comment]
I meant in general, not in the specific case, for example in #3303 I can't think of a reliable way to detect if the system is a laptop or not.
I agree that the place to generate a configuration according to the underlying system is `nixos-generate-config`, now that I read the source I recognize that it already does hardware recognition. Maybe it's worth looking into a way to integrate it with the knowledge inside `nixos-hardware`.

Without going too off-topic, I have a X200 with libreboot on it, so tp_smapi does not work. Is there a way to detect this condition?

**Comment by yegortimoshenko** [comment]
> I meant in general, not in the specific case, for example in #33033 I can't think of a reliable way to detect if the system is a laptop or not.

```
cat /sys/devices/virtual/dmi/id/chassis_type 
```

List of chassis type IDs: 
https://github.com/jhcloos/flashrom/blob/5ccc913c9d445b4c9e5611b2fa54bb73ea7c9676/dmi.c#L79

> Without going too off-topic, I have a X200 with libreboot on it, so tp_smapi does not work. Is there a way to detect this condition?

I envy you. Could you show me your `dmesg`?

**Comment by zarelit** [comment]
> `cat /sys/devices/virtual/dmi/id/chassis_type `

The more you learn...  

> Could you show me your dmesg?

Sure, sent it via email

**Comment by bjornfor** [comment]
And, as far as I can tell, the table that shows the meaning of the integer values in ```/sys/devices/virtual/dmi/id/chassis_type``` is here:

http://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.1.1.pdf

(Look for "System Enclosure or Chassis Types".)

An alternative is using dmidecode, if you have permissions:

```
$ sudo dmidecode -s chassis-type
Desktop
```

**Comment by yegortimoshenko** [comment]
@zarelit: At the very least it's possible to identify that you are using coreboot, which is roughly the same as libreboot plus some blobs: https://github.com/coreboot/coreboot/blob/1a9035988addfbe89ed708fe3c91bf6cc54befdb/src/drivers/i2c/at24rf08c/lenovo_serials.c#L199

Match against DMI in `dmesg` and it will be there. coreboot blobs do not include anything ThinkPad-related, so behavior (and bugs) should be identical to libreboot in this case, including defunct `tp_smapi`.
