### ISSUE TITLE
Build failure: k3d

### ISSUE THREAD

**Issue by mjgallag** [NixOS/nixpkgs#330264]
### Build log

https://nixpkgs-update-logs.nix-community.org/k3d/2024-07-20.log

### Notify maintainers

@kuznero @jlesquembre @ngerstle @jk @ricochet

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qwqawawow** [comment]
close as PR https://github.com/NixOS/nixpkgs/pull/331081
