### ISSUE TITLE
`services.asusd.enable` installs the wrong `supergfxctl package

### ISSUE THREAD

**Issue by Ciflire** [NixOS/nixpkgs#330225]
### Describe the bug
Dependency version mismatch, this I believe is causing an issue where `rog-control-center` does not open
This also creates two entry of that software if `asusd` is enabled and `asusctl` is installed, one of those version will work though i could no find which one

### Steps To Reproduce
1. add `services.asusd.enable = true`to your configuration 
2. notice `supergfxctl` version is 5.2.1
3. remove previous line, add `asusctl` to your packages
4. notice `supergfxctl` version is 5.2.3

### Expected behavior
As `asusd` is based on `asusctl` I expect the dependencies to be met, as `supergfxctl` is a dependency of asusctl I expect to version of the dependency and the version installed by `asusd` to be the same

This could be easily resolved by updating the `supergfxctl` package but this could be an issue again in the future if the version don't match

### Additional context
[`asusd` enables the service](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/asusd.nix#L100)
[`supergfxd `service definition](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/supergfxd.nix#L33)
[`asusd` used asusctl](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/asusd.nix#L11)
[`asusctl` depends on `supergfxctl` 5.2.3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/system/asusctl/default.nix#L33)

### Notify maintainers
@K900 
@aacebedo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixpkgs"`
 - channels(ciflire): `""`
 - nixpkgs: `/nix/store/afawjm6nv8m5aagkcqxlxgrr5qpyh6cm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
That's really not how it works. The `supergfxctl` package tracks latest upstream tags: https://gitlab.com/asus-linux/supergfxctl/-/tags, and is independent from the `supergfxctl` _crate_ used by `asusctl`.
