### ISSUE TITLE
Build failure: couchdb3

### ISSUE THREAD

**Issue by albi005** [NixOS/nixpkgs#330281]
### Steps To Reproduce

1. build couchdb3

### Build log

https://gist.github.com/albi005/43c4a0d846b294383775d0cb4f785531

### Notify maintainers

@lostnet 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240725.5ad6a14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/xblysc3prg1zqsi59fr36nj6wdiqryzp-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Error from `spidermonkey_91` dependency:
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.spidermonkey_91.x86_64-linux
https://hydra.nixos.org/build/265215129
```text
configure flags: --prefix=/nix/store/p9q8b224jaz5aiqh217bda1n2smyk5wk-spidermonkey-91.13.0 --with-intl-api --with-system-icu --with-system-nspr --with-system-zlib --enable-optimize --enable-readline --enable-release --enable-shared-js --disable-debug --disable-jemalloc --disable-strip --disable-tests --host=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu
/build/firefox-91.13.0/python/mozbuild/mozbuild/configure/__init__.py:915: SyntaxWarning: invalid escape sequence '\.'
  RE_MODULE = re.compile("^[a-zA-Z0-9_\.]+$")
Traceback (most recent call last):
  File "/build/firefox-91.13.0/obj/../js/src/../../configure.py", line 22, in <module>
    from mozbuild.configure import (
  File "/build/firefox-91.13.0/python/mozbuild/mozbuild/configure/__init__.py", line 13, in <module>
    from six.moves import builtins as __builtin__
ModuleNotFoundError: No module named 'six.moves'
```

Relevant commit from fedora (where previous patch for it comes from):
https://src.fedoraproject.org/rpms/mozjs91/c/8a18628bc2df64c5c8421e0c868ebe420de641b5
suggests that it does not work with python 3.12 and should probably pin to python 3.11.
