### ISSUE TITLE
"ar: command not found" in cross-compiling glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by telent** [NixOS/nixpkgs#33023]
## Issue description

When cross-building anything (e.g. GNU Hello) it stops with the message

```
/nix/store/65l6hr8snf4v823f974k97jc65i7bhvf-bash-4.4-p12/bin/bash: ar: command not found            
make[2]: *** [Makefile:135: /tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-0/build/sunrpc/librpc_compat_pic.a] Error 127            
make[2]: *** Waiting for unfinished jobs....                                    
make[2]: Leaving directory '/tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-0/glibc-2.26/sunrpc'                 
make[1]: *** [Makefile:215: sunrpc/subdir_lib] Error 2                          
make[1]: Leaving directory '/tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-0/glibc-2.26'                        
make: *** [Makefile:9: all] Error 2     
note: keeping build directory ‘/tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-0’                                
builder for ‘/nix/store/dzjfk7nklc4hbvwc7nq8jkghdz8y3q5x-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv’ failed with exit code 2                   
cannot build derivation ‘/nix/store/svl5d7mnfw08iif7mvw3qmdw8mdj6ygi-armv6l-unknown-linux-gnueabihf-gcc-cross-wrapper-6.4.0-armv6l-unknown-linux-gnueabihf-stage-final.drv’: 1 dependencies couldn't be built                                   
cannot build derivation ‘/nix/store/5x9lzs3d8gc29za2xc80ckls9ab4nfjv-stdenv.drv’: 1 dependencies couldn't be built      
cannot build derivation ‘/nix/store/xfaldyq4zn097p8vypp77dj80f4v4v2r-hello-2.10-
armv6l-unknown-linux-gnueabihf.drv’: 1 dependencies couldn't be built           

```

### Steps to reproduce

Checkout nixpkgs master (or any version since 8e557ed2)  and add this file to the top-level nixpkgs directory

```
$ cat foo.nix
let armHost =  import ./default.nix {
       crossSystem = (import ./lib ).systems.examples.raspberryPi;
    };
    dontCheck = p : s : s.lib.overrideDerivation p (a: {
      doCheck = false ;
    });
in rec {
  armHello = dontCheck armHost.pkgs.hello armHost;
}
```

Now run `nix-build ./foo.nix -A armHello` and watch it fail

## Technical details

I've done a bit of poking around and in all honesty I'm not sure if the problem is with the packaging or the upstream (or me, even).  `AR` is set correctly in the shell environment:

```
[dan@loaclhost:/tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-1]$ ( . env-vars && echo $AR )
armv6l-unknown-linux-gnueabihf-ar
```

but something in the glibc Makefile maze overrides it

```
[dan@loaclhost:/tmp/nix-build-glibc-2.26-75-armv6l-unknown-linux-gnueabihf-armv6l-unknown-linux-gnueabihf.drv-1/build]$ grep AR config.make 
AR = ar
```

I suspect (though am not 100%, it was quite late at night) that glibc may have been using the build `ar` instead of the host `ar` for a long time but only recently has it disappeared from the path.

## Affected versions

* `git bisect` says this behaviour was introduced in 8e557ed2c58e6ce48a8d05dbc57ef84e98b4cecd "bintools-wrapper: Init"
* it still exists in 857a71cbc51017ad660316f860a6fccf1a700c67
* `nix-build (Nix) 1.11.13`

> Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
[dan@loaclhost:~/src/nixwrt-bisecting]$ nix-shell -p nix-info --run "nix-info -m"
error: undefined variable ‘nix-info’ at (string):1:66
(use ‘--show-trace’ to show detailed location information)
```
?

My understanding  of the Nix cross-compilation environment is frankly a bit weak and I might of course just be Doing It All Wrong - any advice to that effect would also be gratefully received.

**Comment by telent** [comment]
Not sure of etiquette for tagging individual developers, but suspect that @Ericson2314 may be well placed to have a look at this

**Comment by Ericson2314** [comment]
This is fixed with https://github.com/NixOS/nixpkgs/pull/26805. Cross compilation is completely unreliable until that lands.

**Comment by Ericson2314** [comment]
And tagging me is perfectly fine.

**Comment by telent** [comment]
Thanks.  I rebased/cherry-picked my actual tree (mips32 embedded stuff) onto said branch and it's working much better  - and has allowed me to significantly clean up the derivation for the kernel.  I look forward to seeing your branch land.

FWIW my work is at https://github.com/obsidiansystems/nixpkgs/compare/02726a2...telent:nixwrt-cross-elegant if you're interested, and contains a few trivial-with-hindsight cross-compilation fixes you might want to look at -

* 04aa606fcd1a56553fbc7fbd5395844d1b306a1a kmod
* 05e07c29ae8de8aa8dc7b31670bdf6d3ed36850e xz
* 35f8b1cfb9c42784831f2eedca208f574b333ebb make-squashfs
* https://github.com/obsidiansystems/nixpkgs/commit/349c78ecfeb720b0f4f1183bf479176ee9611d51#diff-0af3f7dc69c45dcfdaf23aa86c252808 zlib (caution, also some cruft in this commit)
* 29fbc08f7af2c5aeb8ade025acf32dc09c880656 hello

I guess the question is, would you like these as a PR against master, or to cherry-pick them into your branch (perhaps makes it easier for you to avoid conflicts), or should I hold them until after your merge?  Let me know.

---

Next step is working out why my libc has gcc and linux headers as runtime dependency, but that's a separate issue.

```
[dan@loaclhost:~/src/nixwrt]$ nix-store -q --references /nix/store/cmaafly9mrpvdl2z9cl228k9xnfkmfa6-glibc-2.26-75-mipsel-unknown-linux-gnu-mipsel-unknown-linux-gnu |cat
/nix/store/ibxd54g3h666g2dljp5f1vr2jzs5qc39-gcc-6.4.0-mipsel-unknown-linux-gnu-stage-static
/nix/store/z81llg5qxxfjyf4s5y4hdnbpyrd91sz7-linux-headers-4.4.10-mipsel-unknown-linux-gnu
/nix/store/cmaafly9mrpvdl2z9cl228k9xnfkmfa6-glibc-2.26-75-mipsel-unknown-linux-gnu-mipsel-unknown-linux-gnu
```

**Comment by Ericson2314** [comment]
Oh sorry I should

**Comment by Ericson2314** [comment]
So feel free to rebase your changes on the second one instead, @bgamari and I should be able to encorperate it there ahead of the first being merged.

**Comment by flokli** [comment]
@Ericson2314 Could you add this bug to https://github.com/NixOS/nixpkgs/projects/8 ?

**Comment by Ericson2314** [comment]
#26805 has landed in staging
