### ISSUE TITLE
homeassistant: aiohttp_fast_zlib: zlib_ng not available, performance degraded

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#330377]
### Describe the bug

Getting the following warning in the home assistant log. It doesn't seem that bad, but still wanted to hear your opinion and see if there's any solution for this.

Logger: aiohttp_fast_zlib
Bron: components/http/__init__.py:201
Eerst voorgekomen: 23 juli 2024 om 22:46:45 (1 gebeurtenissen)
Laatst gelogd: 23 juli 2024 om 22:46:45
zlib_ng and isal are not available, falling back to zlib, performance will be degraded.

### Steps To Reproduce
1. Do a fresh install of home-assistant.
2. Go through the initial setup flow.

### Expected behavior

Dependencies are included by default.

### Additional context

https://github.com/mindavi/nixos-configuration/tree/master/machines/aqua/modules/home-assistant.nix

### Notify maintainers

@fabaff @mweinelt @dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

TBD, now on my phone looking at the home-assistant UI. But in general, running unstable at a recent channel update (<5d ago). See also the linked config which is flake-based.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
https://www.home-assistant.io/integrations/isal

Can you try enabling `services.home-assistant.config.isal = {}`?

**Comment by eil047** [comment]
So simple! Please add this to the Core installation instructions?

**Comment by mweinelt** [comment]
What instructions where?

**Comment by eil047** [comment]
Here [https://www.home-assistant.io/installation/raspberrypi-other#install-home-assistant-core](url) I would say?

**Comment by mweinelt** [comment]
That is not our install guide.

**Comment by eil047** [comment]
Okay, sorry it helped me out anyway
