### ISSUE TITLE
Duplicate Package: neocities & neocities-cli

### ISSUE THREAD

**Issue by Infinidoge** [NixOS/nixpkgs#330321]
I'm not really sure how it happened, however we have 2 copies of the Neocities CLI: One from #250985, and another from #290514. After formatting the nix files in each, the only differences are:
- Description
- Maintainers
- Platforms (`neocities-cli` lists `platforms.unix`)
- Gemfile lock platform/bundled-with version (`neocities` is bundled-with `2.1.4`, `neocities-cli` has `x86_64-linux` added as a platform and is bundled-with  `2.5.5`)

`neocities` is older, while `neocities-cli` is newer and slightly more complete, as it seems.

One should be removed, with the other aliased to it.

### Notify maintainers

CC @dawoox as the maintainer of the other Neocities package.

**Comment by surfaceflinger** [comment]
this happened before, https://github.com/NixOS/nixpkgs/issues/300651
i wonder if there are more cases like this rn

**Comment by stupidcomputer** [comment]
I'll take care of this -- it seems like `neocities-cli` is out of date so might as well take care of that, too.
