### ISSUE TITLE
switcheroo: Error While Processing: "cannot generate command"

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#330390]
### Describe the bug
Switcheroo fails with the error in the title. This does not happen in the Flatpak version (tested).

### Steps To Reproduce
(the formats might not matter, but I've specified them just in case)
1. Open a PNG file in Switcheroo
2. Convert to a JPEG file.
3. Select the output filename.
4. Error should happen.

### Expected behavior
The image should convert without any errors.

### Screenshots
![A screenshot of the error message in the title](https://github.com/user-attachments/assets/bd768a6d-9129-4b89-846f-69a5e83bb16f)

### Notify maintainers
@michaelgrahamevans

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11pre657537.5ad6a14c6bf0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by michaelgrahamevans** [comment]
Oops, I had `imagemagick` in my path when I originally packaged and tested this. I have added it as a dependency in https://github.com/NixOS/nixpkgs/pull/331334 and tested it with `nix-shell --pure` this time.

Thank you for trying the flatpak and reporting it here first instead of upstream :slightly_smiling_face:
