### ISSUE TITLE
easytag needs dconf as dependency

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#33043]
## Issue description
I had installed `easytag` without dconf and I couldn't do anything, even the UI glitches
(for example I couldn't `Show Scanner -> Fill Tag`)

### Steps to reproduce
Install `easytag` without `dconf` package on the same system. ( I'm not fit with sandboxes so I cant "simulate" the problem yet )

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 17.09.2430.ed3b1bc8448 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2430.ed3b1bc8448"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### Fixing it ?

After I installed `dconf` using the `configuration.nix` like it was described in #2448 or #30866, it works
like it should. So I guess `dconf` should be a dependency of this package.

**Comment by jtojnar** [comment]
`gnome3.dconf` is a system service that needs to be added to `services.dbus.packages` by your desktop environment. If you create your own environment, you will need to add it yourself (adding `programs.dconf.enable = true;` to `configuration.nix` should work). Nix does not contain a mechanism for representing a dependency on a service.
