### ISSUE TITLE
Package request: bpytop

### ISSUE THREAD

**Issue by J4GL** [NixOS/nixpkgs#330461]
**Project description**

Resource monitor that shows usage and stats for processor, memory, disks, network and processes.

**Metadata**

* homepage URL: https://github.com/aristocratos/bpytop
* source URL: https://github.com/aristocratos/bpytop
* license: Apache-2.0
* platforms: Linux, windows, macos, bsd

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
bpytop was removed in favor of btop.

https://github.com/NixOS/nixpkgs/blob/c79442c70e287d810c97ccdcfb61a8466d640369/pkgs/top-level/aliases.nix#L163
