### ISSUE TITLE
check-by-name fails when editing a merged PR

### ISSUE THREAD

**Issue by paparodeo** [NixOS/nixpkgs#330543]
### Describe the bug

I edited the PR description to match the committed changes and list the testing done. The PR was already merged and branch deleted but i wanted the PR to be accurate to what the change was at merge time. 

https://github.com/NixOS/nixpkgs/actions/runs/10127461463

note the format check also fails https://github.com/NixOS/nixpkgs/actions/runs/10127461462 as does the tidy check https://github.com/NixOS/nixpkgs/issues/330546

PR https://github.com/NixOS/nixpkgs/pull/318226

```
Run # This checks for mergeability of a pull request as recommended in
Checking whether the pull request can be merged
GitHub is still computing whether this PR can be merged, waiting 5 seconds before trying again (4 retries left)
Checking whether the pull request can be merged
GitHub is still computing whether this PR can be merged, waiting 10 seconds before trying again (3 retries left)
Checking whether the pull request can be merged
GitHub is still computing whether this PR can be merged, waiting 20 seconds before trying again (2 retries left)
Checking whether the pull request can be merged
GitHub is still computing whether this PR can be merged, waiting 40 seconds before trying again (1 retries left)
Checking whether the pull request can be merged
GitHub is still computing whether this PR can be merged, waiting 80 seconds before trying again (0 retries left)
Checking whether the pull request can be merged
Not retrying anymore. It's likely that GitHub is having internal issues: check https://www.githubstatus.com/
Error: Process completed with exit code 1.
```

### Steps To Reproduce
idk maybe.
1. create PR
2. merge PR
3. delete branch
4. edit PR description

### Expected behavior

0 failures, the PR already merged

### Notify maintainers

@philiptaron @infinisil 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
I don't think there's an easy way to fix it, but I also don't think we need to, since this is mostly cosmetic

**Comment by infinisil** [comment]
Something for GitHub to fix, please upvote: https://github.com/orgs/community/discussions/35058 :D

**Comment by paparodeo** [comment]
> I don't think there's an easy way to fix it, but I also don't think we need to, since this is mostly cosmetic

true. tho it looks like my change failed tests -- now marked with red X -- but the change passed eval and should be well tested (cmake change with patches to cmake and meson) and built almost 40% of attributes that have cmake in `nativeBuildInputs` as well as stdenv on darwin. i upvoted the github issue. thanks for taking a look -- feel free to close.

**Comment by philiptaron** [comment]
The future always has a few rough edges. Thanks for the report @paparodeo and thanks for the "upstream" link to GitHub @infinisil.
