### ISSUE TITLE
check-nixf-tidy fails after editing a PR description from merged pr

### ISSUE THREAD

**Issue by paparodeo** [NixOS/nixpkgs#330546]
### Describe the bug
similar to issue https://github.com/NixOS/nixpkgs/issues/330543

I edited the PR description to match the committed changes and list the testing done. The PR was already merged and branch deleted but i wanted the PR to be accurate to what the change was at merge time.

https://github.com/NixOS/nixpkgs/actions/runs/10127461468

PR https://github.com/NixOS/nixpkgs/pull/318226
```
Run actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
Syncing repository: NixOS/nixpkgs
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/626e9042-efc1-4715-a57f-617847f255e7' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/nixpkgs/nixpkgs
Deleting the contents of '/home/runner/work/nixpkgs/nixpkgs'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=2 origin +refs/pull/318226/merge:refs/remotes/pull/318226/merge
  Error: fatal: couldn't find remote ref refs/pull/318226/merge
  The process '/usr/bin/git' failed with exit code 128
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=2 origin +refs/pull/318226/merge:refs/remotes/pull/318226/merge
  Error: fatal: couldn't find remote ref refs/pull/318226/merge
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=2 origin +refs/pull/318226/merge:refs/remotes/pull/318226/merge
  Error: fatal: couldn't find remote ref refs/pull/318226/merge
  Error: The process '/usr/bin/git' failed with exit code 128
```

### Steps To Reproduce
dk maybe.
1. create PR
2. merge PR
3. delete branch
4. edit PR description

### Expected behavior
checks either don't run or don't fail.

### Notify maintainers

@Aleksanaa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
Same underlying cause as https://github.com/NixOS/nixpkgs/issues/330543
