### ISSUE TITLE
Bitwig Vulkan 

### ISSUE THREAD

**Issue by DaKingof** [NixOS/nixpkgs#330577]
Vulkan is not working. I have to hit cntl-enter and search for advanced settings and change the engine to OpenGL as a fallback. I've asked on the unofficial discord and nobody seems to have Vulkan working that has responded.

In my logs I get this error when attempting to use Vulkan:

```
[2024-7-27 23:46:53.652 skia info] Using "AMD Radeon RX 6700 XT" vulkan physical device
[2024-7-27 23:46:53.676 skia info] GPU context created
[2024-07-27 23:46:53.688 package-manager info] Finished scanning for available packages
[2024-7-27 23:46:53.788 skia error] vkGetPhysicalDeviceSurfaceCapabilitiesKHR failed: ErrorSurfaceLostKHR
[2024-7-27 23:46:53.788 skia error] failed to create a GPU accelerated window surface, fallback to software presentation
[2024-7-27 23:46:53.813 skia error] vkGetPhysicalDeviceSurfaceCapabilitiesKHR failed: ErrorSurfaceLostKHR
[2024-7-27 23:46:53.813 skia error] failed to create a GPU accelerated window surface, fallback to software presentation
```

@kkoniuszy

-->
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.11 (Vicuna), 24.11.git.68c9ed8bbed9M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos'

**Comment by DaKingof** [comment]
Also, to add, it seems this library wasn't added to the derivation either...not that it fixes my Vulkan issue, but it may be causing some other issues!
![image](https://github.com/user-attachments/assets/b6a396d9-bef6-431f-9694-4c76254966ef)

**Comment by kkoniuszy** [comment]
> Also, to add, it seems this library wasn't added to the derivation either...not that it fixes my Vulkan issue, but it may be causing some other issues!

Bitwig bundles its own `libxcb-imdkit.so.1` for some reason, see `46db845jdqgwx6wm7pj5z381ysmgcgly-bitwig-studio-5.2/libexec/lib/bitwig-studio/libxcb-imdkit.so.1`. I'm not sure if it's just the original version that could be replaced with the nixpkgs one, or does it have some unofficial patches.    

-----

The Vulkan stuff works for me.

```
[2024-7-28 9:49:35.948 info] resolving Bitwig Graphics JNI
[2024-7-28 9:49:35.948 info] successfuly resolved Bitwig Graphics JNI
[2024-7-28 9:49:35.950 skia info] checking if Vulkan is available...
[2024-7-28 9:49:35.980 skia info] Using "AMD Radeon RX 6800 XT (RADV NAVI21)" vulkan physical device
[2024-7-28 9:49:35.998 skia info] Vulkan is available
[2024-07-28 09:49:35.999 windowing-system-core info] Initializing graphics backend using skia-vulkan
[2024-07-28 09:49:35.999 skia-graphics info] Initializing Skia graphics backend using vulkan
[2024-7-28 9:49:35.999 skia info] begin skia initialization
[2024-7-28 9:49:36.007 skia info] skia Library initialized
[2024-7-28 9:49:36.007 skia info] selected rendering backend: 3
```

and a few seconds later it creates the GPU context succesfully

```
[2024-7-28 9:49:40.491 skia info] about to create GPU context: 3
[2024-07-28 09:49:40.510 package-manager info] Finished scanning for available packages
[2024-7-28 9:49:40.520 skia info] Using "AMD Radeon RX 6800 XT (RADV NAVI21)" vulkan physical device
[2024-7-28 9:49:40.542 skia info] GPU context created
```

We have a similar setup, so I'm not sure what's going on:

 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1-nixos-cachy-bore-rt, NixOS, 24.11 (Vicuna), 24.11.20240726.7613bd7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nix/path/nixpkgs`

**Comment by kkoniuszy** [comment]
I Just noticed that your GPU name in the logs is a bit odd. Mine has the ` (RADV NAVI21)` suffix, and as far as I remember it always showed up like that in applications. Yours doesn't – are you using the RADV driver from Mesa, or is there a chance you're using the proprietary amdvlk one?

**Comment by DaKingof** [comment]
> I Just noticed that your GPU name in the logs is a bit odd. Mine has the ` (RADV NAVI21)` suffix, and as far as I remember it always showed up like that in applications. Yours doesn't – are you using the RADV driver from Mesa, or is there a chance you're using the proprietary amdvlk one?

You are right! I received a similar error when checking:
```
 vulkaninfo | grep 'Driver Name'
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/wis0bx9jxzcklxpmh1lhsg325g70wxns-mesa-24.1.2-drivers/lib/libvulkan_virtio.so. Skipping this driver.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/wis0bx9jxzcklxpmh1lhsg325g70wxns-mesa-24.1.2-drivers/lib/libvulkan_dzn.so. Skipping this driver.
```

So I dug and found this variable to force RADV:
```
VK_ICD_FILENAMES = "${pkgs.mesa.drivers}/share/vulkan/icd.d/radeon_icd.x86_64.json";
```

after that it seems my issue may be resolved.  Thanks for your help. I've been trying to get this working since Beta 1. :0)

**Comment by kkoniuszy** [comment]
Yeah, amdvlk usually has inferior performance and compatibility compared to radv. It would probably be best to disable `hardware.amdgpu.amdvlk.enable` and make wrapper scripts for applications that actually need amdvlk - you can just point them to amdvlk's icd via that environment variable. 

Using the NixOS config option will link the icd to /run/opengl-driver or something like that, which might cause problems for various applications that would be fine with radv.

**Comment by DaKingof** [comment]
> Yeah, amdvlk usually has inferior performance and compatibility compared to radv. It would probably be best to disable `hardware.amdgpu.amdvlk.enable` and make wrapper scripts for applications that actually need amdvlk - you can just point them to amdvlk's icd via that environment variable.
> 
> Using the NixOS config option will link the icd to /run/opengl-driver or something like that, which might cause problems for various applications that would be fine with radv.

Ahh!!! That makes so much sense. I was using amdvlk to mess around with some local language models and never disabled those packages so I guess my system was defaulting to that. I'll definitely make some notes in my config to make sure I do this instead next time because I wasn't aware of the difference. This truly was a huge assist man. TYSM.

**Comment by kkoniuszy** [comment]
Hm, do you need the entire amdvlk package for LLMs? I think you can just install the AMD ROCm libraries, they should work fine with RADV.

**Comment by DaKingof** [comment]
I'm not sure if you do or not. Rocm for is needed for sure, but I was fiddling around until I got it to work and I landed on that those packages/settings so I didn't want to mess with it and break it. I'm sure I'll fiddle around with them again once some more dependable models are released that I can run. Currently none really work for my use cases so I sort of abandoned my projects for the moment.

**Comment by DaKingof** [comment]
I didn't think that was possible with these drivers cause I figured they were sort of tied to the kernel and couldn't be dynamically loaded but I guess not! I'll definitely look into it in the future because this sure did cause a lot of problems I wasn't aware of until now. Thank you again for your insight and these tips....so very helpful.  Bless!
