### ISSUE TITLE
How to override some arguments in qemu package.

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#33056]
## Issue description
```Nix
nixpkgs.config.packageOverrides = pkgs: {
  qemu_kvm = pkgs.qemu_kvm.override {
    sdlSupport = false;
    pulseSupport = false;
    vncSupport = false;
    spiceSupport = false;
    xenSupport = false;
    usbredirSupport = false;
  };
};

virtualisation.libvirtd = {
  enable = true;
  enableKVM = true;
};
```

It doesn't work...

But this working (only qemu_kvm package, without virtualisation.libvirtd):

```Nix
environment.systemPackages = with pkgs; [
  (
    qemu_kvm.override {
      sdlSupport = false;
      pulseSupport = false;
      vncSupport = false;
      spiceSupport = false;
      xenSupport = false;
      usbredirSupport = false;
    }
  )
];
```

Why?

**Comment by jokogr** [comment]
Could you post the error?

I have noticed at least two spelling errors, it's "virtuali**s**at**i**on.libvirtd", not "virtualizaton.libvirtd".

**Comment by MrSorcus** [comment]
You right. But in configuration.nix no this error.
https://gist.github.com/MrSorcus/199b99741cecec61d44876d745b42865 - qemu_kvm without virtualisation.libvirtd
https://gist.github.com/MrSorcus/4ba7bc0baf174c66256c13f5b9db6540 - with virtualisation.libvirtd

**Comment by yegortimoshenko** [comment]
Better use `nixpkgs.overlays`:

```
{
  nixpkgs.overlays = [(final: previous: {
    qemu_kvm = previous.qemu_kvm.override {
      sdlSupport = false;
      pulseSupport = false;
      vncSupport = false;
      spiceSupport = false;
      xenSupport = false;
      usbredirSupport = false;
    };
  })];

  virtualisation.libvirtd = {
    enable = true;
    enableKVM = true;
  };
}
```

**Comment by MrSorcus** [comment]
Doesn't work. Still depends on X11 and other(spice, sdl)

**Comment by MrSorcus** [comment]
Hmm... Looks like a libvirt depend on xen, which depends on something with X11 dependency...
Thanks.
