### ISSUE TITLE
Update request: nuclear 0.6.30 → 0.6.31

### ISSUE THREAD

**Issue by JeppeX** [NixOS/nixpkgs#330635]
- Package name: nuclear
- Latest released version: 0.6.31
- Current version on the unstable channel: 0.6.30
- Current version on the stable/release channel: 0.6.30

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@NotAShelf 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NotAShelf** [comment]
Made a PR, would appreciate it if you tested it - I don't use nuclear very often at the moment.
