### ISSUE TITLE
Package request: box86

### ISSUE THREAD

**Issue by Tarinaky** [NixOS/nixpkgs#330750]
**Project description**

Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM

**Metadata**

* homepage URL: https://box86.org/
* source URL: https://github.com/ptitSeb/box86
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
I recall I saw this on reddit yesterday. The problem here I guess is we are lacking armv7 test machines, and even armv7 toolchains doesn't work so well sometimes (right?) so we are completely blind about whether it really works or not

**Comment by surfaceflinger** [comment]
You don't need armv7 machines for that, just userland that can be ran by aarch64, there's a PR here https://github.com/NixOS/nixpkgs/pull/318623

I've been trying to run CS:S dedicated server using it few months ago, box86 worked, can't say that abt CS:S tho, there were warnings about some unimplemented stuff :p

**Comment by Yeshey** [comment]
> You don't need armv7 machines for that, just userland that can be ran by aarch64, there's a PR here #318623
> 
> I've been trying to run CS:S dedicated server using it few months ago, box86 worked, can't say that abt CS:S tho, there were warnings about some unimplemented stuff :p
> 
> You just crossbuild things for i686 linux and you can then refer to pkgs.box86 in a module

Did you manage to run the server? 
I was trying to run steam in nixOS but couldn't get it to work (https://github.com/ptitSeb/box86/issues/968)

Was suspecting it was a box86 issue, cuz i was trying in the oracle server with (i think) ARMv8 architecture

**Comment by surfaceflinger** [comment]
> Did you manage to run the server?

It was printing stuff out and client actually exchanged some data but then server stopped responding.
I don't think you can run Steam, pretty sure it needs 64 bit environment now. If you want to run dedicated servers from Steam then use [fetchsteam](https://github.com/nix-community/steam-fetcher) instead

**Comment by Aleksanaa** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/318623. Feel free to open further bug reports if it's not working.
