### ISSUE TITLE
Package request: mpv-discord

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#330795]
**Project description**

A cross-platform Discord Rich Presence integration for mpv with no external dependencies. (MPV Userscript)

**Metadata**

* homepage URL: https://github.com/tnychn/mpv-discord
* source URL: https://github.com/tnychn/mpv-discord
* license: mit
* platforms: unix, linux, darwin, windows

**Comment by bddvlpr** [comment]
I've already [packaged this personally](https://github.com/bddvlpr/resonance/blob/main/pkgs/mpv-discord/default.nix) but haven't PR'ed this to nixpkgs yet. Will probably do this when I get home from vacation next week.
