### ISSUE TITLE
system-config-printer: displays warnings when started

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#33075]
## Issue description
This is just a minor issue, and likely an upstream issue:

```
(system-config-printer.py:4825): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(system-config-printer.py:4825): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(system-config-printer.py:4825): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(system-config-printer.py:4825): Gtk-WARNING **: Allocating size to GtkToolItem 0x2965f20 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

### Steps to reproduce
I used 68bcfb32699b32f802c797f8629b4d507cd1b10a and I tested that system-config-printer can at least start and display some part of Cups configuration. 

## Technical details
I run a stable 17.09 system (latest available) with system-config-printer coming from master.

**Comment by bjornfor** [comment]
Yes, that looks like upstream issues. If you have the time, please notify them.

**Comment by coretemp** [comment]
Last commit to master of upstream: Date: 2015-04-23 15:23:02 UTC. 

I don't think there still is an upstream.

**Comment by teto** [comment]
Have you ever run a gtk program that doesn't vomit warnings ?! lucky you :p

**Comment by coretemp** [comment]
Yes, the ones I have written myself or all of them in which I have had a hand.

**Comment by coretemp** [comment]
This should be fixed upstream.
