### ISSUE TITLE
palemoon: enable devltools by default?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [NixOS/nixpkgs#33078]
## Issue description + Steps to reproduce

When installing Pale Moon via `nix-env -i palemoon`, the Element Inspector, Network Monitor, and all the rest are missing.

## Technical details

According to https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux,

> Make sure [`.mozconfig`] contains at least the following for a build that is similar to official builds:
>````
>[…]
>ac_add_options --enable-devtools
>[…]
>````

While I'm sure that, given enough knowledge of Nix, this could be overridden by the end-user, it should be configured by default like the official builds..such an important piece of the browser should not be left out by default, especially when it's part of the official build configuration.

**Comment by rnhmjoj** [comment]
Thank you, you are completely right: we should follow these recommendations.
I must have missed some option when I first package pale moon.
