### ISSUE TITLE
Build failure: php-simplexml

### ISSUE THREAD

**Issue by rylee-randall** [NixOS/nixpkgs#330793]
### Steps To Reproduce

1. Use nixpkgs 18cb69fb9baa1c4e425b425aff44089d8c4fbb15
2. Add `home.packages = [pkgs.easyeffects];` to home manager (assume installation method is irrelevant) 

### Build log

https://gist.githubusercontent.com/rylee-randall/f422eaf6ed5e154823ed115dc40087fb/raw/26552356705a6a91efb8b689d7bba70601dbf666/gistfile1.txt

### Additional context

None.

### Notify maintainers

@aanderse
@drupol
@ma27
@piotrkwiecinski
@talyz

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.11 (Vicuna), 24.11.20240712.7e7c39e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Maybe this is related to https://github.com/NixOS/nixpkgs/pull/330299

**Comment by drupol** [comment]
Can you post the error logs please?

**Comment by rylee-randall** [comment]
A gist of the build log is linked in the template, are there other logs you need?

**Comment by drupol** [comment]
> A gist of the build log is linked in the template, are there other logs you need?

Yes, I didn't see it while replying with the phone. Thank you.
