### ISSUE TITLE
floorp: regression regarding PWA functionality

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#330733]
https://github.com/NixOS/nixpkgs/blame/b73c2221a46c13557b1b3be9c2070cc42cf01eb3/pkgs/applications/networking/browsers/floorp/default.nix#L41

This line actually results in the following (taken from the debugger):
![image](https://github.com/user-attachments/assets/bf9a632d-47cc-4c65-b5b0-8360ab091c68)
with the variable `floorp` obviously being undefined.

Judging by the comment this is probably meant to be in quotes.

@christoph-heiss

**Comment by christoph-heiss** [comment]
Fixed by #330737.
