### ISSUE TITLE
gitea does not include `git-upload-pack`

### ISSUE THREAD

**Issue by nixupp** [NixOS/nixpkgs#330885]
### Describe the bug
When I installed and configured gitea I noticed that I could not clone the repo using ssh.
```
$ git clone gitea@host:3000/repo.git
Cloning into 'repo'...
bash: line 1: git-upload-pack: command not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
### Steps To Reproduce
1. Install gitea with my config
2. Add a user with ssh acces to gitea, create empty repo
3. Try to clone repo through ssh

### Expected behavior
Repo clones.

### Additional context
My config file is below:
```nix
{ config, pkgs, ... }:
let
  httpPort = 3000; # default is 3000
  sshPort = 22;
in
{
  services.gitea = { enable = true;
    appName = "myName";
    stateDir = "/path/to/dir";
    settings = {
      server = {
        HTTP_PORT = httpPort;
        SSH_PORT = sshPort;
      };
    };
  };

  networking.firewall = {
    allowedTCPPorts = [ httpPort sshPort ];
  };
}
```
### Fix
Adding 
```
  environment.systemPackages = with pkgs; [
    git
  ];
```
to the recipe fixed the problem
### Notify maintainers
@Ma27 @techknowlogick @SuperSandro2000 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.05 (Uakari), 24.05.3346.8c5066250910`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
We should probably add git to the systemd units path. Maybe git minimal is already enough?

**Comment by SuperSandro2000** [comment]
We already do that https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/gitea.nix#L528 so the issue is on your side.

> Add a user with ssh acces, create empty repo

You can't just add any user. The gitea user should be used which works on my end without extra configuration. You obviously also need to enable services.openssh

**Comment by nixupp** [comment]
I meant the gitea user.

After rebuilding without the git package it works...
IDK what's happening but I'm fine with that.
