### ISSUE TITLE
Update request: pdm 2.15.4 → 2.17.1

### ISSUE THREAD

**Issue by yajo** [NixOS/nixpkgs#330844]
- Package name: pdm
- Latest released version: 2.17.1

- Current version on the unstable channel: 2.15.4
- Current version on the stable/release channel: 2.15.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cpcloud

This update brings in some improvements relevant for nix projects such as dream2nix, like https://github.com/pdm-project/pdm/commit/c190e1439cf88cfa06bbf20ee01b1f0d6dfeabbb, where you can now specify the python and OS versions for the lock file you want to generate.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jfvillablanca** [comment]
closing this since this package is already updated in unstable to 2.19.1
971c0ce509f87
