### ISSUE TITLE
Package request: Typst preview

### ISSUE THREAD

**Issue by jthulhu** [NixOS/nixpkgs#330827]
**Project description**

Typst preview permits live previewing of Typst documents.

**Metadata**

* homepage URL: [Enter-tainer/typst-preview](https://github.com/Enter-tainer/typst-preview)
* source URL: [Enter-tainer/typst-preview](https://github.com/Enter-tainer/typst-preview)
* license: mit
* platforms: cross platform

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
typst-preview has been superseded by tinymist.

https://github.com/NixOS/nixpkgs/blob/b34ee7d48436cb46343de9daf5abdc3bcab0dec3/pkgs/top-level/aliases.nix#L1437

**Comment by donovanglover** [comment]
cc @GaetanLepage @drupol
