### ISSUE TITLE
amdgpu - radv is not a conformant Vulkan implementation,testing use only.

### ISSUE THREAD

**Issue by Martin-Lndbl** [NixOS/nixpkgs#330899]
### Describe the bug
Vulkan drivers for my AMD R9 390 aren't working.  `vulkaninfo` finds my graphics card but prints following warnings:
```console
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/wis0bx9jxzcklxpmh1lhsg325g70wxns-mesa-24.1.2-drivers/lib/libvulkan_dzn.so. Skipping this driver.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/wis0bx9jxzcklxpmh1lhsg325g70wxns-mesa-24.1.2-drivers/lib/libvulkan_virtio.so. Skipping this driver.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
...

Instance Layers: count = 3
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1

Devices:
========
GPU0:
	apiVersion         = 1.3.278
	driverVersion      = 24.1.2
	vendorID           = 0x1002
	deviceID           = 0x67b1
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Radeon R9 390 Series (RADV HAWAII)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 24.1.2
	conformanceVersion = 0.0.0.0
	deviceUUID         = 00000000-0100-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
	apiVersion         = 1.3.278
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 17.0.6, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 24.1.2 (LLVM 17.0.6)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3234-2e31-2e32-000000000000
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```
I didn't notice until I tried running godot4 again after 6 months (it was working then). Now it wasn't able to use my graphics card, due to following warnings:
```console
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 4.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 144507584
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 6.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 144507584
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Vulkan devices:
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
  #0: AMD AMD Radeon R9 390 Series (RADV HAWAII) - Unsupported, Discrete
  #1: Unknown llvmpipe (LLVM 17.0.6, 256 bits) - Supported, CPU
```
As far as I know, xwayland enforces DRI3, but I also tried setting it "the X way" in `/etc/X11/xorg.conf.d/20-amdgpu.conf` without any effect.

### Steps To Reproduce
1. Setup
 * CPU: Intel Xeon E3-1231 v3 (has no internal graphics card)
 * Graphics card: AMD Radeon R9 390 Series (RADV HAWAII)
 * Hyprland
2. Run `vulkaninfo --summary`

### Additional context
* Im using wayland + Hyprland
* Parts of my nixos config, that could be relevant:
```nix
 boot.initrd.kernelModules = [ "amdgpu" ];
 boot.kernelParams = [ "radeon.cik_support=0" "amdgpu.cik_support=1" ];
 hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };

```
Edit: Removing the `boot.kernelParams` results in vulkaninfo not finding the graphics card and printing following error:
```console
ERROR: [../src/amd/vulkan/radv_physical_device.c:1944] Code 0 : Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
``` 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by higherorderfunctor** [comment]
I am seeing the same on unstable with a 380 trying to run `wezterm`, `vkcube-wayland`, and `vulkaninfo`.  Currently at work so cannot grab logs.  I am using `amdvlk`.  I am also using the latest kernel which may be a variable to consider.  I can try testing using the default unstable kernel when home.

```nix
  hardware.amdgpu.amdvlk = {
    enable = true;
    supportExperimental.enable = true;
    settings = {
      AllowVkPipelineCachingToDisk = 1; # ~/.cache/AMD/VkCache
      ShaderCacheMode = 1;
      IFH = 0;
      EnableVmAlwaysValid = 1;
      IdleAfterSubmitGpuMask = 1;
    };
  };

  boot = {
    kernelPackages = pkgs.linuxPackagesFor pkgs.linux_latest;
    initrd.kernelModules = [ "amdgpu" ];
  };
```

**Comment by Martin-Lndbl** [comment]
Thanks for the tip @JohnRTitor. Unfortunately this only adds another warning to the `vulkaninfo` output:
```console
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/f4xmg76b4rrp83ghxixwc7zgrb7dv3kd-amdvlk-2024.Q2.3/lib/amdvlk64.so. Skipping this driver.
```

This applies as well when adding the package manually (as specified in the [NixOs Manual](https://nixos.org/manual/nixos/unstable/index.html#sec-gpu-accel-vulkan-amd)):
```nix
hardware.graphics.extraPackages = [
    pkgs.amdvlk
];
```

I also want to note that the following part of my config wasn't necessary when it worked 6 months ago even though the R9 390 is using the GCN2 instruction set.
```nix
boot.kernelParams = [ "radeon.cik_support=0" "amdgpu.cik_support=1" ];
```

**Comment by matteo-pacini** [comment]
Not sure it's related, but it may - getting the same error on a 6800XT (`vulkan: No DRI3 support detected - required for presentation`) without the `testing` error part.

Used to work on kernel 6.9.11 - mesa 24.1.2
Stopped working with same error on 6.9.12 - mesa 24.1.4 (nothing vulkan-related launches)

Errors I'm getting:
- `mangohud` tries to use NVIDIA dynamic libraries, despite them not being present
- `vulkaninfo` cannot find the ICDs (?)

**Comment by Atemu** [comment]
Please try something simpler than Godot to confirm Vulkan generally works such as vkcube. It might be doing something more fancy than regular instance creation; perhaps refusing to use non-compliant drivers. Make sure `vkcube` doesn't fall back to lavapipe (software renderer) though.

Do not use AMDVLK (like, generally) and especially not on old GPUs. AMD does not support these cards anymore and you're increasingly unlikely to see support for them working in newer versions of their official drivers.  
The only upside of AMDVLK is that it has a slight edge over RADV in ray-tracing but that doesn't matter if half of your games don't work properly and break in confusing ways. Also, your ancient cards can't do RT to begin with so that's a moot point anyways.  
If you have AMDVLK enabled and don't exactly know what you're doing, please disable it immediately.

RADV (mesa) does support these old cards but doesn't always implement all features. See for instance https://www.phoronix.com/news/RADV-NGG-RDNA3-ESO-Option where `VK_EXT_shader_object` wasn't implemented for your class of card.  
It being marked as non-conformant would be news to me though. It was even officially VK 1.2 conformant with the R9 390 and a selection of similarly old cards back in 2022 (it's on the Khronos site). Either Mesa developers have decided to also no longer fully support it or this is a bug in mesa.

I currently don't see any evidence that this is a bug in NixOS however, so I'm going to close this. Feel free to continue discussing but the proper channel for this would probably be the [Mesa issue tracker](https://gitlab.freedesktop.org/mesa/mesa/-/issues).

**Comment by Atemu** [comment]
@higherorderfunctor please note that your GPU is an entirely different architecture to the R9 390; gfx7/GCN2 vs. gfx8/GCN3. AMD's naming is extremely confusing and just bafflingly bad here.
