### ISSUE TITLE
Package request: harper

### ISSUE THREAD

**Issue by Feel-ix-343** [NixOS/nixpkgs#330920]
**Project description**

Performant grammar checker for developers

**Metadata**

* homepage URL:https://writewithharper.com/
* source URL:https://github.com/elijah-potter/harper
* license: apache 2.0
* platforms: all

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dit7ya** [comment]
I can add a PR if someone wants to become the maintainer. Looks pretty straight-forward to me.


`nix-init` gave me this output and it builds.
```
{ lib
, rustPlatform
, fetchFromGitHub
}:

rustPlatform.buildRustPackage rec {
  pname = "harper";
  version = "0.9.0";

  src = fetchFromGitHub {
    owner = "elijah-potter";
    repo = "harper";
    rev = "v${version}";
    hash = "sha256-LPDs+PUgHzrAT6Y3+YyA0FDbqyc31+cZR5v262kFxRI=";
  };

  cargoHash = "sha256-5go9yQwhZ19mGIfaBEeswbElcW9Z1hSi5+XN1Lc/3SU=";

  meta = with lib; {
    description = "The Grammar Checker for Developers";
    homepage = "https://github.com/elijah-potter/harper";
    license = licenses.asl20;
    maintainers = with maintainers; [ ];
    mainProgram = "harper";
  };
}
```

**Comment by Sigmanificient** [comment]
I can maintain that

**Comment by poperigby** [comment]
Yeah I could also maintain this. I already have a local package for it.

**Comment by poperigby** [comment]
@Feel-ix-343 you can close this now. It was merged: https://github.com/NixOS/nixpkgs/pull/335659
