### ISSUE TITLE
nixos-rebuild repl broken with channels

### ISSUE THREAD

**Issue by MrQubo** [NixOS/nixpkgs#330904]
### Describe the bug

`nixos-rebuild repl` doesn't work with channel configuration.

### Steps To Reproduce
1. `nixos-rebuild repl`
Output:
```console
❯ nixos-rebuild repl
building Nix...
Welcome to Nix 2.18.5. Type :? for help.

error: '<nixpkgs/nixos>' is not a valid URL
```

### Additional context

Only with channels.

### Notify maintainers

@Profpatsch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32-hardened1, NixOS, 24.05 (Uakari), 24.05.3164.63d37ccd2d17`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(nix): `""`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-hardware, nixos-unstable, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MrQubo** [comment]
That should be enough to fix it, I think?
```diff
diff --git a/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh b/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
index 03b2dbfbeb66..5b17b7d1cacb 100755
--- a/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
+++ b/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
@@ -592,7 +592,7 @@ if [ "$action" = repl ]; then
     if [[ -z $buildingAttribute ]]; then
         exec nix repl --file $buildFile $attr "${extraBuildFlags[@]}"
     elif [[ -z $flake ]]; then
-        exec nix repl '<nixpkgs/nixos>' "${extraBuildFlags[@]}"
+        exec nix repl --file '<nixpkgs/nixos>' "${extraBuildFlags[@]}"
     else
         if [[ -n "${lockFlags[0]}" ]]; then
             # nix repl itself does not support locking flags
```

**Comment by Atemu** [comment]
Did you try it and did it work? If so, feel free to shoot a PR with that patch.

**Comment by MrQubo** [comment]
`nix repl --file '<nixpkgs/nixos>'` works for me. I didn't check any other flag combinations though. But I guess working sometimes is better than working never.

**Comment by Atemu** [comment]
It'd be great if you could create a PR then :)
