### ISSUE TITLE
vesktop: opening links does't work for Firefox in Wayland.

### ISSUE THREAD

**Issue by decromo** [NixOS/nixpkgs#330916]
### Describe the bug
Nothing happens when clicking on a link when using Firefox in a normal Wayland session. If Firefox is not running, it will not launch.

### Steps To Reproduce
1. Start a Wayland session;
2. Have Firefox as your default browser;
3. Click on any link in Vesktop. 

### Expected behavior
Firefox would open the desired webpage.

### Additional context
- Clicking on links does not output any error, not unlike #78961; however that is about the official client and the specified fix does not apply for Vesktop.
- Setting another browser works as expected (verified with `chromium`).
- I am running _Firefox_ in Xwayland (`MOZ_ENABLE_WAYLAND=0` envvar). Running it natively in Wayland makes no difference.
- Interestingly, running _Vesktop_ with `--ozone-platform=x11` resolves this issue: links open right away both on Xwayland Firefox and on Wayland Firefox; if Firefox wasn't running, it will also start up and open the desired webpage.
- The Flatpak release of Vesktop does not suffer from this issue, hence why I thought it was an issue for `nixpkgs`.
- My system is running KDE Plasma 6.1.3, links open fine in Firefox when xdg-open 'ed or when clicked on from any other application.

### Notify maintainers
@getchoo
@Scrumplex
@vgskye
@pluiedev

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.11-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
Do you have an xdg portal configured? I believe this is essential for this type of thing

**Comment by pluiedev** [comment]
Can't reproduce. Do you have XDG configured properly? (e.g. `xdg-utils` is installed/`xdg-open` exists, XDG portal is set correctly, etc.)

**Comment by Scrumplex** [comment]
It might also be interesting to see if there is any log output when you try to reproduce this issue.

I had a similar issue with Firefox using Steam before, as Steam's runtime was conflicting with some dynamically loaded library of Firefox, which was evident by starting Steam in a terminal.

**Comment by decromo** [comment]
> Do you have an xdg portal configured? I believe this is essential for this type of thing

Yeah, relevant NixOS config: 
```
# XDG Desktop Portals
  xdg.portal = {
    enable = true;
    config.common.default = "kde";
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };
```
> Can't reproduce. Do you have XDG configured properly? (e.g. `xdg-utils` is installed/`xdg-open` exists, XDG portal is set correctly, etc.)
> 
> EDIT: Here's a working example on my machine: https://youtu.be/0rf_Hq3WDKw

I think it's set correctly, but I'm not too brushed up on XDG:
```
$ nix-store --query --requisites /run/current-system | grep xdg-utils
/nix/store/p5cvdpnby7ix97cf498n670b7nxwwdnh-xdg-utils-1.2.1
/nix/store/pksajprgby78kldq6qfw21k4scm9v2cq-xdg-utils-1.2.1
```
Running `xdg-open example.com` also works as expected.
Are you in a Wayland session? It would be a much more weird issue than I expected if it really happens only on my system.


> It might also be interesting to see if there is any log output when you try to reproduce this issue.
> 
> I had a similar issue with Firefox using Steam before, as Steam's runtime was conflicting with some dynamically loaded library of Firefox, which was evident by starting Steam in a terminal.

Nope, can't get any errors in the terminal. It just fails silently.
I tried making a video showing everything that I get with the steps in my report:

https://github.com/user-attachments/assets/7fe9ef41-0f0f-4591-baa9-2dc8c74b0949

Hope it helps.

**Comment by CrystalSplitter** [comment]
Hi, I've been encountering this issue with the latest vesktop, and I'm not sure how to fix it. I currently have the portal set up as so:

```nix
  # For opening links in external xdg-open browsers
  # See https://github.com/NixOS/nixpkgs/issues/330916#issuecomment-2260781383
  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
    config.common.default = "kde";
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };
```

And yet, it only opens in the internal vesktop electron browser. I have `xdg-utils` installed; `xdg-open` works correctly outside of `vesktop`.

---

```
crystal@seafoam ~> nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/5ds20jm3x2s4z7wn3581r6lc9ybmh45b-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.23, NixOS, 25.05 (Warbler), 25.05.20250412.2631b0b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/crystal/.config/nix/nix.conf:/nix/store/n4p9523zdb0xn7r0dca4gvk96hzf15g9-plasma-workspace-6.3.4/etc/xdg/nix/nix.conf:/nix/store/86m53r69hym0828673rm2dl6figiczzj-kglobalacceld-6.3.4/etc/xdg/nix/nix.conf:/nix/store/d1kl80pfswcr0p7nvrv32wlr05b88261-baloo-6.12.0/etc/xdg/nix/nix.conf:/home/crystal/.config/kdedefaults/nix/nix.conf:/nix/store/n4p9523zdb0xn7r0dca4gvk96hzf15g9-plasma-workspace-6.3.4/etc/xdg/nix/nix.conf:/nix/store/86m53r69hym0828673rm2dl6figiczzj-kglobalacceld-6.3.4/etc/xdg/nix/nix.conf:/nix/store/d1kl80pfswcr0p7nvrv32wlr05b88261-baloo-6.12.0/etc/xdg/nix/nix.conf:/nix/store/n4p9523zdb0xn7r0dca4gvk96hzf15g9-plasma-workspace-6.3.4/etc/xdg/nix/nix.conf:/nix/store/86m53r69hym0828673rm2dl6figiczzj-kglobalacceld-6.3.4/etc/xdg/nix/nix.conf:/nix/store/d1kl80pfswcr0p7nvrv32wlr05b88261-baloo-6.12.0/etc/xdg/nix/nix.conf:/home/crystal/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/crystal/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/crystal/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/crystal/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/b9b8mvcrbq5dy1xb4n5y59hc8axj0yzf-lix-2.91.1/share`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/store/5ds20jm3x2s4z7wn3581r6lc9ybmh45b-source`
```

Yes, this is with wayland.
