### ISSUE TITLE
Guake package not producing executables (`No module named 'distutils'`)

### ISSUE THREAD

**Issue by heywoodlh** [NixOS/nixpkgs#330913]
### Steps To Reproduce
1. `nix build "github:nixos/nixpkgs/nixpkgs-unstable#guake"`
2. Observe lack of `./result/bin` directory with executables

In contrast this command works as expected: `nix build "github:nixos/nixpkgs/nixos-24.05#guake"`

### Expected behavior

Create `bin` directory with executables to invoke Guake.

### Screenshots
Observe that nixpkgs 24.05 has `guake` and `guake-toggle` in the "Programs provided" section.

<img width="989" alt="image" src="https://github.com/user-attachments/assets/14a15290-8e73-489d-928f-e65bd54bfc9e">

And unstable does not despite both claiming to have version 3.10 of Guake:

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/fc6429c5-290d-4141-938e-2c033128d85c">

And both branches provide the same package definition.

### Notify maintainers

@msteen

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Seems like the cause is the below. Oddly the command fails but the build doesn't.

```
guake> writing byte-compilation script '/build/tmpf7gwsunn.py'    guake> /nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/bin/python3 /build/tmpf7gwsunn.py                                 guake> Traceback (most recent call last):                         guake>   File "/build/tmpf7gwsunn.py", line 1, in <module>        guake>     from distutils.util import byte_compile                guake> ModuleNotFoundError: No module named 'distutils'           guake> error: command '/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/bin/python3' failed with exit code 1              guake> setup.py install failed, you may need to run "sudo git config --global --add safe.directory '*'"                             guake> /nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash: line 1: update-desktop-database: command not found         guake> Could not run update-desktop-database, are you root?
```
