### ISSUE TITLE
Werkzerg reloader crashes due to Nix wrapped scripts

### ISSUE THREAD

**Issue by samdroid-apps** [NixOS/nixpkgs#33093]
## Issue description

Werkzerg (a python framework; used by Flask for example) has a function that reloads the server while you are developing it.  This crashes on NixOS, since it is wrapped as a shell script:

```
 * Serving Flask app "main"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin/flask", line 2
    export PATH=/nix/store/839vm39v1wnb6zw0hn66g834n08735yg-python3-3.6.3/bin:/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin:/nix/store/wl6gn1ll6zfxpv3k7a6aq7sdq47f0xzx-python3.6-setuptools-36.4.0/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax
```

Werkzerg tried to reload the app based on `sys.argv[0]`; however, this is mangled by NixOS and does not point to the real python script.

### Steps to reproduce

Using flask (aka. `nix-env -i python3.6-Flask`)

Create a file `main.py`:

```python3
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello World'
```

Attempt to run it with the reloader:

```
FLASK_APP=main.py flask run --reloader
```

Currently, it will crash with the error as above:

```
 * Serving Flask app "main"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
  File "/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin/flask", line 2
    export PATH=/nix/store/839vm39v1wnb6zw0hn66g834n08735yg-python3-3.6.3/bin:/nix/store/ya4r3zvl1abad8rkql804q9slhbp3n5d-python3.6-Flask-0.12.2/bin:/nix/store/wl6gn1ll6zfxpv3k7a6aq7sdq47f0xzx-python3.6-setuptools-36.4.0/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 17.09.2281.b4a0c011e81 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2281.b4a0c011e81"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by teozkr** [comment]
As a workaround until this is fixed properly, `FLASK_ENV=development python -m flask run` seems to work fine, while `FLASK_ENV=development flask run` crashes with this bug.

**Comment by dotlambda** [comment]
@samdroid-apps If you want, you can make a PR which adds the upstream fix (https://github.com/pallets/werkzeug/pull/1242) as a patch to our Werkzeug expression.

**Comment by davidism** [comment]
Werkzeug 0.15 was released with @samdroid-apps's fix for this.
