### ISSUE TITLE
Build failure: python3Packages.opentelemetry-instrumentation-asgi

### ISSUE THREAD

**Issue by xanderio** [NixOS/nixpkgs#331056]
### Steps To Reproduce

1. build python3Packages.opentelemetry-instrumentation-asgi

### Build log

https://hydra.nixos.org/build/267486666/nixlog/2

### Notify maintainers

@natsukagami @de11n @invokes-su 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukagami** [comment]
I believe you wanted to mention @natsukium

**Comment by luochen1990** [comment]
OpenWebUI  depends on this, and also failed to build.

**Comment by robertosw** [comment]
Just to link these two issues:  An issue in the source repo has been created a few days ago: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2776
