### ISSUE TITLE
Build failure: pycdio

### ISSUE THREAD

**Issue by myclevorname** [NixOS/nixpkgs#331094]
### Steps To Reproduce

1. build pycdio on staging, staging-next

### Build log

https://gist.github.com/myclevorname/6c1b4f51b687e636992afea2a6d531bd

### Additional context

On master and unstable, the package fails due to nose, which is not the topic of this bug report. This prevents the build of whipper, unfortunately.

### Notify maintainers

N/A

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
Linked PR was meged
