### ISSUE TITLE
Build failure: sequoia-sq

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#331093]
### Steps To Reproduce

1. build `sequoia-sq`

### Build log

Observed: https://github.com/SamLukeYes/nixos/runs/28108268281

Full checkPhase log (copied from Garnix): https://gist.github.com/SamLukeYes/069ae0b2d7ebd6882ceec6086ae27b55

### Notify maintainers
@minijackson @doronbehar 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/8mqds79bdc5745bfc8y3fym845dag9pp-nixpkgs-patched-b73c222`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/331099

**Comment by SamLukeYes** [comment]
> #331099

The checkPhase still fails with this PR applied, but it is a different error:

```
command=`cd "/build/.tmp0lUbIe" && SQ_CERT_STORE="/build/.tmp0lUbIe/cert-store" SQ_KEY_STORE="/build/.tmp0lUbIe/key-store" "/build/source/target/x86_64-unknown-linux-gnu/release/sq" "key" "generate" "--userid" "Alice <alice@example.org>"`
code=1
stdout=""
stderr=```
Error: While creating /homeless-shelter/.local/share/sequoia/revocation-certificates
Caused by:
    Permission denied (os error 13)
```

https://garnix.io/commit/bfb245cba346be48e93a44e9553fbd43e6bbe721

**Comment by doronbehar** [comment]
Thanks for the report (I thought I rebuilt it successfully before I opened the PR). Now [it](https://github.com/NixOS/nixpkgs/pull/331099) should be ready now (the failing test is skipped, and an upstream issue was created).
