### ISSUE TITLE
Package request: screen-pipe

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#331110]
**Project description**

Library to build personalized AI powered by what you've seen, said, or heard. Works with Ollama. Alternative to Rewind.ai. Open. Secure. You own your data. Rust. Has both CLI and desktop app.

**Metadata**

* homepage URL: https://screenpi.pe
* source URL: https://github.com/louis030195/screen-pipe
* license: mit
* platforms: unix, linux, darwin, windows

**Comment by dit7ya** [comment]
I am somewhat interested in this package and started a PR but I am super busy these days to thoroughly test the package. If anyone can do that, that would be awesome.
