### ISSUE TITLE
Can't set custom fonts in NixOS 24.05 / Gnome 46 because Gnome can't locate the fonts

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixpkgs#331103]
### Describe the bug
Setting anything but the default Gnome font (Cantarell 11) results in Gnome glitching out and not displaying fonts in many areas. This is with fontdir enabled.

### Steps To Reproduce
Enter in terminal `gsettings set org.gnome.desktop.interface font-name 'Source Code Pro'` with that font installed.

### Expected behavior
Gnome using the new font

### Screenshots
Fonts don't render anywhere, this also glitches out the UI.

Overview
![image](https://github.com/user-attachments/assets/091fe6f9-5ce1-4256-ae99-1aa7f688e210)

Quicksettings
![image](https://github.com/user-attachments/assets/745d7b70-3a5a-487b-bc3e-e05cc8f8e91b)

### Additional context
This issue (regression?) started happening in 24.05. I am not sure if NixOS 24.05 is the cause, or a change that Gnome introduced with Gnome 46.

### Notify maintainers
@bobby285271 
@hedning 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.9, NixOS, 24.05 (Uakari), 24.05.2780.53e81e790209`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05"`
 - channels(usernamereplaced): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
CC @jtojnar

**Comment by jtojnar** [comment]
The `font-name` setting needs to include font size:

https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/blob/af331306e60f8d3d15be7af7161f33e950f16787/schemas/org.gnome.desktop.interface.gschema.xml.in#L129

**Comment by ahydronous** [comment]
Thanks for clarifying!
Now I'm not sure if this still classifies as a bug, or if it is just (yet another) breaking change by Gnome..

**Comment by JohnRTitor** [comment]
The issue here can be marked "resolved" then, if anything it should go to upstream

**Comment by FeliciousX** [comment]
> The `font-name` setting needs to include font size:
> 
> https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/blob/af331306e60f8d3d15be7af7161f33e950f16787/schemas/org.gnome.desktop.interface.gschema.xml.in#L129

thank you for this @jtojnar , I have been debugging for weeks on why my GNOME UI breaks when I update.. it's missing the font size!
