### ISSUE TITLE
Build failure: hurl

### ISSUE THREAD

**Issue by drnfc** [NixOS/nixpkgs#331169]
### Steps To Reproduce

1. build hurl

### Build log

```
error: builder for '/nix/store/nacay3y1psg62nrmck1xwhg19hmf32cx-hurl-4.3.0.drv' failed with exit code 101;
       last 10 log lines:
       >    |     |
       >    |     field in this variant
       >    |
       > help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
       >    |
       > 35 |     GenericError(()),
       >    |                  ~~
       >
       > error: could not compile `hurl` (lib) due to 7 previous errors
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/nacay3y1psg62nrmck1xwhg19hmf32cx-hurl-4.3.0.drv'.
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.1, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Upstream issue:
https://github.com/Orange-OpenSource/hurl/issues/3057
It seems like to build it on rust 1.79 it needs a patch from:
https://github.com/Orange-OpenSource/hurl/pull/2923
https://github.com/Orange-OpenSource/hurl/commit/d51c275fc63d1ee5bbdc6fc70279ec8dae86a9c1.patch
(that is not in any release tag yet)
