### ISSUE TITLE
fixed bug upstream in unreleased wee-slack should be incorporated

### ISSUE THREAD

**Issue by nipsy** [NixOS/nixpkgs#331131]
### Describe the bug
As described in https://github.com/wee-slack/wee-slack/issues/930, the current stable release of wee-slack is breaking against the Slack API.  I just ran into this earlier today with NixOS.  As the fix hasn't been released officially in any sort of stable release, it looks like a manual patch might be necessary against the currently stable release in the short term.

### Steps To Reproduce
1. Install wee-slack.
2. Attempt to connect to an already configured Slack team when starting weechat.
3. Python error is thrown.

### Expected behavior
It should connect without error.

### Notify maintainers

@WilliButz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/332514
