### ISSUE TITLE
Package request: plymouth-theme-charge

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#331108]
**Metadata**

* homepage URL: https://rockylinux.pkgs.org/8/rockylinux-devel-x86_64/plymouth-theme-charge-0.9.4-11.20200615git1e36e30.el8.x86_64.rpm.html
* source URL: https://dl.rockylinux.org/pub/rocky/8/Devel/x86_64/os/Packages/p/plymouth-theme-charge-0.9.4-11.20200615git1e36e30.el8.x86_64.rpm
* license: GPLv2+
* platforms: linux

![charge](https://github.com/user-attachments/assets/49f5e69a-b6ec-4f3d-812f-2f3c7e5031cf)

**Comment by KCynk** [comment]
> It's not that hard to package, but where is the source repo? I'd rather not package from RPMs.

I hope this will help @JohnRTitor 
https://gitlab.com/redhat/centos-stream/rpms/plymouth/-/tree/c9s
https://git.rockylinux.org/staging/rpms/plymouth/-/tree/r8

**Comment by SuperSandro2000** [comment]
That is just the charge theme with some changed settings.
https://gitlab.com/redhat/centos-stream/rpms/plymouth/-/blob/c10s/plymouth.spec?ref_type=heads#L267

You can copy that by using boot.plymouth.themePackages and boot.plymouth.theme 

See https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/system/boot/plymouth.nix#L14 for an example how to package a plymout theme pkgs.plasma5Packages.breeze-plymouth
