### ISSUE TITLE
Build failure: texinfo

### ISSUE THREAD

**Issue by brianmcgillion** [NixOS/nixpkgs#331204]
### Steps To Reproduce

1. Attempt to cross-compile texinfo
2. During configurePhase it will fail

### Build log

```
configure:36441: error: in `/tmp/texinfo/texinfo-7.1':
configure:36443: error: cannot run test program while cross compiling
```

### Notify maintainers

@oxij @afh 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.2, NixOS, 24.11 (Vicuna), 24.11.20240728.52ec9ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/bcghcr9qwqmanpds017w75mcqda4fgab-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by brianmcgillion** [comment]
https://github.com/NixOS/nixpkgs/pull/328919 addresses the issue, though the cross-tests error, was a red herring.

**Comment by afh** [comment]
Thanks for reporting and investigating, @brianmcgillion, much appreciated. Glad that this resolved.
