### ISSUE TITLE
Build failure: Darktable 4.8.1

### ISSUE THREAD

**Issue by rob-mur** [NixOS/nixpkgs#331311]
### Steps To Reproduce

1. build darktable 4.8.1 on unstable using x86-linux system

### Build log

```
[gist link](gist.github.com/rob-mur/85b860753f0abe41098fc5fa5bcba51e) as log is large
```

### Additional context

None

### Notify maintainers

@flosse 
@mrVanDalo 
@paperdigits 
@freyacodes 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`


```

---

**Comment by freyacodes** [comment]
I don't see the actual error in the log, but it seems like the failure which was resolved by #331096. It has yet to hit unstable
