### ISSUE TITLE
Build failure: php81Extensions.dom

### ISSUE THREAD

**Issue by waltmck** [NixOS/nixpkgs#331388]
### Steps To Reproduce

1. Install NixOS on Asahi Linux (Apple M2).
2. Use the latest `nixpkgs-unstable` (revision `c00d587b1a1afbf200b1d8f0b0e4ba9deb1c7f0e`).
3. Build a system that depends on php81Extensions.dom, or one of its downstream packages

### Build log

https://gist.github.com/waltmck/ae50988c27c517bf19ffeaa94481cb8d

### Additional context

Notably, pipewire is downstream via `lsp-plugins` so this causes its build to fail.

### Notify maintainers

 @aanderse @drupol @Ma27 @piotrkwiecinski @talyz 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.9.9-asahi, NixOS, 24.11 (Vicuna), 24.11.20240701.00d80d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/j4jzjbr302cw5bl0n3pch5j9bh5qwmaj-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
> Notably, pipewire is downstream via `lsp-plugins` so this causes its build to fail.

already fixed
