### ISSUE TITLE
Update request: cargo,clippy,rustc,rustfmt 1.79 → 1.80

### ISSUE THREAD

**Issue by theoparis** [NixOS/nixpkgs#331429]
- Package name: rustc, cargo
- Latest released version: 1.80

- Current version on the unstable channel: 1.79
- Current version on the stable/release channel: 1.77.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Havvy @figsoda @Mic92 @tjni @winterqt @zowoq

-----

Note for maintainers: Please tag this issue in your PR.

---

See https://releases.rs/docs/1.80.0/, there are new stabilized APIs such as LazyLock that some rust projects are already migrating to.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zh4ngx** [comment]
awaiting this for #330764

**Comment by GaetanLepage** [comment]
The PR has been merged in `staging-next`: https://github.com/NixOS/nixpkgs/pull/332153

**Comment by theoparis** [comment]
I think this can be closed now, as https://nixpkgs-tracker.ocfox.me/?pr=332153 says it is in all of the major branches.
