### ISSUE TITLE
Package request: servo

### ISSUE THREAD

**Issue by theoparis** [NixOS/nixpkgs#331459]
**Project description**

**Metadata**

* homepage URL: https://servo.org
* source URL: https://github.com/servo/servo/
* license: MPL-2.0
* platforms: linux (not sure about other platforms due to the x11 and udev dependencies)

Depends on #331429 and https://github.com/servo/servo/pull/32896

I have already tried to package servo myself here: https://github.com/tinted-software/nix-packages/blob/main/servo.nix
However, I ran into an issue with the predefined.rs file here: https://github.com/servo/stylo/blob/f7d72a956de1e2e7455a03964af72fbbec4a9158/atoms/build.rs#L25
The atoms build.rs file tries to include a file which doesn't exist at that path. With nix it seems to be exist under `../style-0.0.1` instead of `../style` 🤔 

I would be willing to make a PR once Rust 1.80 is supported in nixpkgs, but I have no idea how to fix the above issue atm. Additionally, servo does not have any releases or tags for some reason. So I'd assume that the best way to package it would be to follow the llvmPackages_git approach: `servo-{date}"

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sagudev** [comment]
cc servo's nix's wizards: @delan @mukilan

**Comment by eclairevoyant** [comment]
seems like there was a pr for this: #220648
but would need some updates

**Comment by supinie** [comment]
I am currently working on packaging this for Summer of Nix, should hopefully have a PR out in a few days.

**Comment by supinie** [comment]
taking a little longer than we had hoped, apologies. Opened a draft PR [here](https://github.com/NixOS/nixpkgs/pull/337781) so you can track progress.
