### ISSUE TITLE
mkDerivation stdenv regression: folder named `doc` removes itself from $out. Breaking change or unintenionally?

### ISSUE THREAD

**Issue by hsjobeki** [NixOS/nixpkgs#331472]
### Describe the bug

If the source of mkderivation contains a folder `doc` in the top-level directory

`$src/doc` this now gets removed.

### Steps To Reproduce
1.

create a source which has folder `doc` in it

```sh
test
├── build.nix
└── doc
    └── file

```

2.
```nix
# build.nix
let
  nixpkgs = import <nixpkgs> {};
in
  pkgs.stdenv.mkDerivation {
    name = "example";
    src = ./.;
    buildPhase = ''
      cp -r . $out
      ls -la $out
      # -> Prints doc
      # -> This likely removed in one of the following stdenv phases, I didn't yet debug.
    '';
  }
  ```

### Expected behavior

I didn't expect the hooks to remove the folder. As this didn't happen with versions of nixpkgs 7 days ago.

### Notify maintainers

Not sure who is in charge, probably

@Ericson2314 ?
@Qyriad  ?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by picnoir** [comment]
This is done by the `move-docs.sh` fixup hook. I don't see any recent change around that. Not sure why it was not triggered before.

**Comment by hsjobeki** [comment]
Seems it was triggered before. I experience this bug, because nixpkgs now exports the nixpkgs-manual as a package.

 nixpkgs-manual = callPackage ../../doc/doc-support/package.nix { };
  

I preproces the nixpkgs source in a derivation, before evaluating it.


Closing this issue.  Since it is intentional behavior.
