### ISSUE TITLE
Update request: todoist-elecron 8.10.1 → 9.7.2

### ISSUE THREAD

**Issue by JalilArfaoui** [NixOS/nixpkgs#331559]
- Package name: todoist-electron
- Latest released version: 9.7.2
- Current version on the unstable channel: 8.10.1
- Current version on the stable/release channel: 8.10.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@kylesferrazza
@pokon548 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR to update: #348835
