### ISSUE TITLE
GNU Octave has lost its GUI?

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#33160]
## Issue description

When I first tried GNU Octave on NixOS maybe a year ago, it had a GUI.

When I run GNU Octave now, it doesn't show a GUI, whether I run it from `dmenu_run` or in the command-line as `octave` or even `octave --force-gui`. In the last case, it doesn't even mention that it's ignoring the `--force-gui` option.

### Steps to reproduce

Run GNU Octave. For comprehensiveness, run it from a GUI and in the command-line as `octave` and `octave --force-gui`.

## Technical details

 - system: `"x86_64-linux"`                                                                                                                                                                                        
 - host os: `Linux 4.13.9, NixOS, 18.03pre123588.ade98dc442e (Impala)`                                                                                                                                             
 - multi-user?: `yes`                                                                                                                                                                                              
 - sandbox: `yes`                                                                                                                                                                                                  
 - version: `nix-env (Nix) 1.11.16`                                                                                                                                                                                
 - channels(root): `"nixos-18.03pre123588.ade98dc442e"`                                                                                                                                                            
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by nixy** [comment]
I'm not terribly familiar with the history here, but it looks like octave has [optional parameters](https://github.com/NixOS/nixpkgs/commit/37e6b8ec80935108ae8ab9b35f99c2587aeb32ca) for QT that would provide a GUI.

I'm guessing these are only provided by default in the `octaveFull` package? Do you have `octave` or `octaveFull` installed in your environment?

**Comment by 8573** [comment]
Ah, yes, I had overlooked `octaveFull`; thanks.

Having installed `octaveFull` rather than `octave`, Octave starts its GUI if I run it in the command-line (with or without `--force-gui`), but trying to run it with `dmenu_run` still doesn't work, with no messages in the journal or `/var/log/X.0.log`.

**Comment by fusion809** [comment]
I want the GUI too, how do I install octaveFull? `nix-env -i octaveFull` returns: `error: selector 'octaveFull' matches no derivations` so I'm not sure what I'm meant to do here.

**Comment by fusion809** [comment]
Nvm I merely needed to use `nix-env -f '<nixos-unstable>' -iA octaveFull` to get GNU Octave 4.4.1 with a GUI.
