### ISSUE TITLE
nuget-to-nix silently fails, making updating dotnet packages impossible

### ISSUE THREAD

**Issue by TomaSajt** [NixOS/nixpkgs#331648]
### Describe the bug

The changes made in https://github.com/NixOS/nixpkgs/pull/327651 cause `nuget-to-nix` fail on my system.
Please do check that it also fails for you.

### Steps To Reproduce
1. try to regenerate any dotnet package's deps:
  e.g. run `$(NIXPKGS_ALLOW_UNFREE=1 nix-build -A osu-lazer.fetch-deps)`
3. see that it stops after saying `Writing lockfile...` (which is not the final thing it shoud output)

### Expected behavior
The lockfile gets generated

### Cause
This probably didn't happen to the people testing out if this worked, so I'm wondering what I might be doing differently.

AFAICT the issue was with the call to `curl`. The command returns an exit code of `23`, but it still outputs the result to the console.

The issue was probably this:
https://stackoverflow.com/questions/16703647/why-does-curl-return-error-23-failed-writing-body

I have a fix that works for me:
```patch
diff --git a/pkgs/build-support/dotnet/nuget-to-nix/nuget-to-nix.sh b/pkgs/build-support/dotnet/nuget-to-nix/nuget-to-nix.sh
index 2754bfc32d7b..205e788f487f 100755
--- a/pkgs/build-support/dotnet/nuget-to-nix/nuget-to-nix.sh
+++ b/pkgs/build-support/dotnet/nuget-to-nix/nuget-to-nix.sh
@@ -33,9 +33,8 @@ for index in "${sources[@]}"; do

     remote_sources+=($index)

-    base_address=$(
-    curl --compressed --netrc -fsL "$index" | \
-      jq -r '.resources[] | select(."@type" == "PackageBaseAddress/3.0.0")."@id"')
+    json=$(curl --compressed --netrc -fsL "$index" || true)
+    base_address=$(echo "$json" | jq -r '.resources[] | select(."@type" == "PackageBaseAddress/3.0.0")."@id"')
     if [[ ! "$base_address" == */ ]]; then
       base_address="$base_address/"
     fi
```

### Notify maintainers
@corngood 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by corngood** [comment]
I'm struggling to reproduce this.  I tried `osu-lazer` on linux, and some other packages on both linux and darwin.

> see that it stops after saying Writing lockfile... (which is not the final thing it shoud output)

Do you mean `Succesfully wrote lockfile to ...`?

**Comment by TomaSajt** [comment]
Now that I'm looking at the PR more closely, I'm not sure if that the problem is with the PR, just assumed it was. Sorry about that.
However it did fail for me when I was trying it on PC. However, I currently don't have a lot of internet access, so I can't really test it further.

I haven't tested this on my laptop, but I'll try to do so and report back when I can.

I'll be home in about 3 days, so until then there's no rush to fix it, since I can't use my main PC.

Might have been some one time issue.
Sorry for the bad timing of opening this issue before going away.

**Comment by TomaSajt** [comment]
> > see that it stops after saying Writing lockfile... (which is not the final thing it shoud output)
> 
> Do you mean `Succesfully wrote lockfile to ...`?
It stopped during the `nuget-to-nix` call, so it didn't reach the part where it printed `Succesfully wrote lockfile to ...`,

**Comment by corngood** [comment]
I just asked because I don't see `Writing lockfile` anywhere in the code.

It's possible there's some rare situation where `jq` doesn't read all the output from `curl`.  It might even be connection dependent.  I probably wouldn't want to ignore errors from curl, but reading the whole thing into a temporary file might be a good idea, or just specifically ignoring exit code 23.

**Comment by TomaSajt** [comment]
> I just asked because I don't see `Writing lockfile` anywhere in the code.

Oh... it looks like the PR mentioned above removed this line
https://github.com/NixOS/nixpkgs/pull/327651/files#diff-65a0ad17dfac5f83c898e0233b5825c2c9c8ab3da2589ae6ec04f465ba9590c7L100

So I guess that the issue wasn't related to the PR.

I assumed the culprit was that PR, since it was what touched the file last. The PR's probably fine, then

It looks like the branch I was testing on somehow didn't get rebased on the latest master. (I thought I did).

---
Now I tried running this with the current master branch on my laptop and it worked fine.

I'll do some more experimenting, but probably this issue is a false-alert.

**Comment by TomaSajt** [comment]
I tested it before and after the PR's changes on my laptop and it seems to work fine in both cases.
I'll share if the problem still persists on my main PC in 3 days.
Until then, I'll close this issue. If anything comes up, I'll reopen.

**Comment by corngood** [comment]
Okay, sounds good.  I do think there's probably a legit problem here.  It could depend on the exact source being used, timing, connection quality, etc.  We can leave it for a bit and see how rare it is.

**Comment by ghpzin** [comment]
Not sure about recent changes (including linked PR), but I remember having similar experience while running `fetch-deps` script a while ago (around April 2024).
It stopped at that same point with `Writing lock file...`
If you restart - it may finish successfully or stop at that same point again.
So by restarting it over and over it finished eventually.
