### ISSUE TITLE
Package request: apparmor-d

### ISSUE THREAD

**Issue by cynicsketch** [NixOS/nixpkgs#331645]
**Project description**

Full set of AppArmor profiles (~ 1500 profiles)

**Metadata**

* homepage URL: https://apparmor.pujol.io/
* source URL: https://github.com/roddhjav/apparmor.d
* license: gpl2
* platforms: linux

---

Note: Should be built in [enforce mode](https://apparmor.pujol.io/enforce/), since there's no point to installing MAC profiles that don't actually confine anything. We don't need to worry about "breaking the system on the initial install" since a user can just go back to the previous generation if things break.

**Comment by JohnRTitor** [comment]
I packaged it initially in https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ro/roddhjav-apparmor-rules/package.nix#L33.

However I do not use this much, feel free to send a PR.

**Comment by cynicsketch** [comment]
Ah, ok! Closing issue since it's already packaged. I might send a PR in the future when I learn nix a bit better.

**Comment by JohnRTitor** [comment]
The main challenge is that the repo has a lot of hardcoded paths like `/usr`, `/opt` which are not available in NixOS. Re implementing the packaging should account for that.

**Comment by ryan4yin** [comment]
@JohnRTitor Does this mean that this package is now unusable on NixOS?

**Comment by JohnRTitor** [comment]
No, see the above comment, and the package should be built in enforce mode, which is not being done at the moment.
