### ISSUE TITLE
Package request: Azure CLI Extension - storage-preview

### ISSUE THREAD

**Issue by RoastBeefKazenzakis** [NixOS/nixpkgs#331605]
**Project description**

Microsoft Azure Command-Line Tools Storage-preview Extension

**Metadata**

* homepage URL: https://github.com/Azure/azure-cli-extensions
* source URL: https://github.com/Azure/azure-cli-extensions
* license: mit
* platforms: unix, linux, windows

---
This package is distinct from the `azure-cli-extensions.storage-blob-preview` package that is already in 24.05 and unstable. It enables azcopy utility in the azure-cli, which is useful for interacting with large storage accounts in Azure.

**Comment by RoastBeefKazenzakis** [comment]
Code for extension [here:](https://github.com/Azure/azure-cli-extensions/tree/main/src/storage-preview)

**Comment by katexochen** [comment]
@RoastBeefKazenzakis please give https://github.com/NixOS/nixpkgs/pull/335765 a try and leave some feedback. :)
