### ISSUE TITLE
`services.tor.settings.ORPort` does not allow for flags

### ISSUE THREAD

**Issue by nixupp** [NixOS/nixpkgs#331759]
### Describe bug
According to the torrc manpage ORPort's syntax is like this:
`ORPort [address:]PORT|auto [flags]`
However, from what I understand, we only allow for a single option, so if I wanted
`ORPort 1234 NoListen`
It's impossible to do.
Right now I can get 
```
ORPort 1234
ORPort NoListen
```
by doing `ORPort = [ 1234 "NoListen" ];

I see no way to use FLAGS :<

### Notify maintainers
@JulienMalka 
I hope this is the right person to ping.

### Metadata
```console
$ tor --version
Tor version 0.4.8.11.
This build of Tor is covered by the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.en.html)
Tor is running on Linux with Libevent 2.1.12-stable, OpenSSL 3.0.14, Zlib 1.3.1, Liblzma 5.4.7, Libzstd 1.5.6 and Glibc 2.39 as libc.
Tor compiled with GCC version 13.2.0
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.05 (Uakari), 24.05.3444.cf05eeada35e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JulienMalka** [comment]
You meant to ping @ju1m :)

**Comment by ju1m** [comment]
@nixupp, indeed the rendering of the documentation [is quite uninformative](https://search.nixos.org/options?channel=24.05&show=services.tor.settings.ORPort&from=0&size=50&sort=relevance&type=packages&query=ORPort):

> 16 bit unsigned integer; between 0 and 65535 (both inclusive) or value "auto" (singular enum) or list of (16 bit unsigned integer; between 0 and 65535 (both inclusive) or value "auto" (singular enum) or (submodule))

One has to [check the source](https://github.com/NixOS/nixpkgs/blob/05405724efa137a0b899cce5ab4dde463b4fd30b/nixos/modules/services/security/tor.nix#L128) to see that `submodule` refers here to an attrset like that:
```nix
settings.ORPort = [ { addr=null; port=1234; NoListen=true; } ]
```
Which sets this in `torrc`:
```
ORPort 1234 NoListen
```

I'm closing the issue, feel free to repoen if something is not working as expected (eg. if the port is not correctly opened in `networking.firewall`).
Note also that `settings.ORPort = mkForce [];` unless `relay.enable == true`.
