### ISSUE TITLE
Build failure: nix-du

### ISSUE THREAD

**Issue by MinerSebas** [NixOS/nixpkgs#331748]
### Steps To Reproduce

1. build nix-du on unstable

### Build log

https://gist.github.com/MinerSebas/c86ddfca4672b2fa411636fb0c25f77c

### Notify maintainers

@symphorien 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 sebastian@obelix  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.11 (Vicuna), 24.11.20240731.9f918d6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - nixpkgs: `/nix/store/7v6l2v247fmdgfpbs3w91mf6rinai4yk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Upstream issue - https://github.com/symphorien/nix-du/issues/23
Commit that should have fixed it:
https://github.com/symphorien/nix-du/commit/09076c868cd4ae730ee0e27c5ff69ee1cdd5d298
New tag with it - `v1.2.1` (from yesterday):
https://github.com/symphorien/nix-du/compare/v1.2.0...v1.2.1

**Comment by symphorien** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/331856
