### ISSUE TITLE
`security.acme.certs.<name>.dnsProvider = "acme-dns"` permissions error

### ISSUE THREAD

**Issue by TRPB** [NixOS/nixpkgs#331805]
### Describe the bug

This feels like it should be a simple fix but I couldn't determine the exact cause. It feels more like a packaging issue than a lego issue as the root cause is filesystem permissions.

### Steps To Reproduce

1. Enable acme with the `acme-dns` provider.

Doing so requires setting `ACME_DNS_STORAGE_PATH_FILE` which is a file containing the a path of the storage file to use:

```
$ echo "https://auth.domain.tld" > /etc/acme/base
$ echo "/etc/acme/storage.json" >  /etc/acme/storagepath
```

Then setting the relevant options in nix config:

```
  security.acme.acceptTerms = true;
  security.acme.certs."domain.tld" = {
    email = "user@domain";
    group = "nginx";
    dnsProvider = "acme-dns";
    credentialFiles = {
      ACME_DNS_API_BASE_FILE = "/etc/acme/base";
      ACME_DNS_STORAGE_PATH_FILE = "/etc/acme/storagepath";
    };
  };
```

When the service starts it gives the error

```
[domain.tld] acme: error presenting token: Failed to write storage file: open /etc/acme/storage.json: read-only file system
```

I have verified that the server gives the expected response when calling the `/register` endpoint as described in the readme: https://github.com/joohoi/acme-dns 

The issue is when lego tries to store the response it gets in the specified storage file. I have tried the following:

1. `chmod 777 /etc/acme`
2. `chown acme /etc/acme`
3. `chown acme /etc/acme && chmod 600 /etc/acme`
4. `chown root /etc/acme` then setting `security.acme.useRoot = true;`
5. Manually running the registration step and placing the json response in `/etc/acme/storage.json` and trying all the various permissions above on the directory and file. It gives the error `acme: error presenting token: Failed to write storage file: open /etc/acme/storage.json: permission denied` instead.
6. Moving the directory and file to `/tmp` and verifying the permissions are `777`.

It doesn't seem to matter what permissions I set, the file is unwritable. 777 would be a very bad idea but should work for testing.

### Expected behavior

It should have permissions to create the file after registration on the server.

@aanderse 
@arianvp 
@emily-is-my-username 
@flokli 
@m1cr0man 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.05 (Uakari), 24.05.20240801.a918b46`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `not found`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by m1cr0man** [comment]
I believe this is due to systemd protections configured on the service unit (acme-$domain.service). Is it possible for you to place those 2 config files under /var/lib/acme instead and give it a shot?

**Comment by TRPB** [comment]
Aha! Thank you, that works!

It would definitely be worth putting that in the documentation for `credentialFiles`, would have saved me an hour

**Comment by m1cr0man** [comment]
Certainly, I have a little list of docs updates that I will flush out to a PR when next I update the module 🙂
