### ISSUE TITLE
Windows Cross Compilation

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#33182]
It used to work somewhat, I broke it.

TODO say something
------------
CC @taktoa @DavidEGrayson @bnikolic @elitak @domenkozar

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/33167 gets us closer.

**Comment by bnikolic** [comment]
I seem to be finding with the windows cross compilation that nativeBuildInputs are cross compiled as well as the buildInputs. Am I doing something wrong?

**Comment by Ericson2314** [comment]
@bnikolic that's really really weird? Especially if you are still on a branch using https://github.com/NixOS/nixpkgs/pull/26805 .

**Comment by bnikolic** [comment]
@Ericson2314 I've traced the root of this: nativeBuildInputs are respected when callPackage is used  as for example in all-packages.nix. However if an expression is put directly (say in all-packages.nix) it does not seem to be respected and all inputs are built for the target architecture

**Comment by Ericson2314** [comment]
@bnikolic ah yes that is true, and sadly by design. Use `buildPackages.foo` instead of `packages.foo`. The splicing I do in `callPackage` is a rather gross hack for backwards compat, but just a world without that is also rather verbose. Something like `p: with p; [ ... ]` as the argument (c.f. @nbp's https://github.com/NixOS/rfcs/pull/3) is a potential good solution.

**Comment by orivej** [comment]
@bnikolic You may also use `callPackage` without files, e.g. `my-package = callPackage ({ stdenv }: stdenv.mkDerivation ...) { }`

**Comment by matthewbauer** [comment]
I think this has been fixed.

https://hydra.nixos.org/build/78784001
