### ISSUE TITLE
recoll: build is failing

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#331807]
### Describe the bug

`recollindex` fails with the following error:

```
Traceback (most recent call last):
  File "/nix/store/hq1gx88hki29prnq7gd70mzrdwdqlfyb-recoll-1.36.0/share/recoll/filters/rcljoplin.py", line 44, in <module>
    from recoll import recoll
ModuleNotFoundError: No module named 'recoll'
:2:index/indexer.cpp:255::ConfIndexer: JOPLIN: /nix/store/hq1gx88hki29prnq7gd70mzrdwdqlfyb-recoll-1.36.0/share/recoll/filters/rcljoplin.py index failed with status 100
:3:rcldb/rcldb.cpp:2060::Db::waitUpdIdle: total xapian work 43 mS
:3:index/recollindex.cpp:948::recollindex: exiting: Fri Aug  2 16:52:02 2024
```
Possibly a regression of #311619?

### Steps To Reproduce

`recollindex`

I also tried `nix-shell -p python312 recoll --run recollindex` and got the same result.

### Expected behavior
The command should run without errors.

### Additional context

Possibly a regression of #311619?

### Notify maintainers

@jcumming 
@ehmry

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.96, NixOS, 23.11 (Tapir), 23.11.7870.205fd4226592`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ehmry** [comment]
@jcumming: broken by #323527?

**Comment by ehmry** [comment]
@mhwombat: Are you using 1.36.0 or 1.39.1? We recently updated.

**Comment by mhwombat** [comment]
@ehmry I'm using what's currently in unstable.

```
❯ recoll -v
Recoll 1.36.0 + Xapian 1.4.24
```

**Comment by superherointj** [comment]
The PR title is not proper. Please, fix it.

**Comment by superherointj** [comment]
> @ehmry I'm using the older version. I'll switch to unstable, which is what I normally run.
> 
> ```
> ❯ recoll -v
> Recoll 1.36.0 + Xapian 1.4.24
> ```

Whenever opening an issue certify to test from `master` or you'll be making invalid claims.

**Comment by superherointj** [comment]
`recoll` builds successfully at master.
