### ISSUE TITLE
Package request: alpaca-proxy

### ISSUE THREAD

**Issue by 1nv0k32** [NixOS/nixpkgs#331982]
**Project description**

It's a forward proxy with PAC file support.

**Metadata**

* homepage URL: https://github.com/samuong/alpaca
* source URL: https://github.com/samuong/alpaca
* license: apache version 2.0
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
(I took that name)

**Comment by 1nv0k32** [comment]
I'm gonna package it soon and create PR.
