### ISSUE TITLE
john: missing "binaries"

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#33190]
## Issue description
@danielfullmer  with john-jumbo some binary are not installed. For example, unshadow is missing.
However, john behaves like busybox, so just `ln -s $(which john) ./unshadow` creates a working unshadow command. Shouln't this, as long as other binaries, be available?

(OT: I'm tagging you @danielfullmer  as you are the latest one who changed this package. the meta maintainer is @offline, could you add/replace him?)

Thanks, Nicolò

**Comment by danielfullmer** [comment]
Hi Nicolò, I just opened a PR to fix these extra utilities. #33257

I actually don't want to volunteer to maintain this package since I use it very infrequently. I just had some free time this weekend, so I went ahead and fixed this.

**Comment by danielfullmer** [comment]
A fix for this was merged into master as 24e8c382afcccf714171bddc238ce0eed17effb8

**Comment by nico202** [comment]
Thanks!
