### ISSUE TITLE
Update request: protonvpn-gui 4.3.0 → 4.3.3

### ISSUE THREAD

**Issue by franzmondlichtmann** [NixOS/nixpkgs#331927]
Protonvpn-gui has issues with connecting to a vpn server, in the sense that I need to manually enter a private key to unlock the vpn server. Entering a private key manually is not needed and not recommended from proton vpn official developers. I hope that a new version update will fix this problem.

- Package name: protonvpn-gui
- Latest released version:  4.3.3 stable

- Current version on the unstable channel: 4.3.0
- Current version on the stable/release channel: 4.3.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@WolfangAukang 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by franzmondlichtmann** [comment]
I solved the problem, gnome-keyring is apparently a hidden dependency. But please update nontheless!

**Comment by Steinhagen** [comment]
The package was updated to version 4.4.4 in: https://github.com/NixOS/nixpkgs/pull/334674
