### ISSUE TITLE
Package request: python312Packages.diagrams-as-code

### ISSUE THREAD

**Issue by techie2000** [NixOS/nixpkgs#331981]
**Project description**

Declarative configurations using YAML for drawing cloud system architectures.

**Metadata**

* homepage URL: https://pypi.org/project/diagrams-as-code/
* source URL: https://github.com/dmytrostriletskyi/diagrams-as-code?tab=readme-ov-file#vs-code
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment]
Was addressed with https://github.com/NixOS/nixpkgs/pull/332017
