### ISSUE TITLE
Update request: github-runner: 2.317.0 -> 2.318.0

### ISSUE THREAD

**Issue by newAM** [NixOS/nixpkgs#332041]
- Package name: github-runner
- Latest released version: 2.318.0

- Current version on the unstable channel: 2.317.0
- Current version on the stable/release channel: 2.317.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers** @veehaitch @newam @kfollesdal @aanderse @zimbatm

-----

Note for maintainers: Please tag this issue in your PR.

I got the package updated but a ton of tests fail.  Hopefully there's a .net expert here that can help out.

Feel free to use any part of this in a PR: https://github.com/newAM/nixpkgs/commit/6e83ac1b0d4119139e6b89b342959d4c0c5da5f1

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by azahi** [comment]
[v2.319.0](https://github.com/actions/runner/releases/tag/v2.319.0) is out now.
