### ISSUE TITLE
python.pkgs.scikitlearn: Can't install on i686

### ISSUE THREAD

**Issue by rouanth** [NixOS/nixpkgs#33202]
## Issue description
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/scikitlearn/default.nix#L11
specifies that `scikitlearn` shouldn't be installed on i686. But the issue that is referenced as the rationale has been closed for a long time, and it seems that there should be no problems with installing the package on i686. Either way, the comment on why the package doesn't work on i686 is obsolete.
### Steps to reproduce

Try to install `scikitlearn` using any available method. For example, include
```
environment.systemPackages = with pkgs; [
(python.withPackages(ps: with ps; [scikitlearn]))
]
```
in `configuration.nix` and run `nixos-rebuild switch`.

## Technical details

```
 - system: `"i686-linux"`
 - host os: `Linux 4.9.71, NixOS, 17.09.2476.53e6d671a96 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(roots): `"nixos-17.09.2484.3aec59c99ff"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by FRidh** [comment]
i686 is no longer supported since 17.09. Also, this package is in need of a maintainer, since I will no longer maintain it. PR's are more than welcome to fix the i686 support.

**Comment by FRidh** [comment]
Out of curiosity I just tested on master and I get one test failure while building a dependency, pillow.
```
======================================================================
FAIL: TestFontPcf.test_high_characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/Pillow-4.3.0/Tests/test_font_pcf.py", line 59, in test_high_characters
    self._test_high_characters(message)
  File "/build/Pillow-4.3.0/Tests/test_font_pcf.py", line 55, in _test_high_characters
    self.assert_image_equal(image, compare)
  File "/build/Pillow-4.3.0/Tests/helper.py", line 85, in assert_image_equal
    msg or "got size %r, expected %r" % (a.size, b.size))
AssertionError: got size (770, 22), expected (765, 22)
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 2644
PIL.PngImagePlugin: DEBUG: STREAM 'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM 'IDAT' 41 1400
--------------------- >> end captured logging << ---------------------
```

**Comment by globin** [comment]
I agree with @FRidh, we have decided to not have first-class support for i686-linux, but we always welcome patches fixing stuff :)

As mentioned sklearn might be working but pillow has test failures on i686, we'd welcome a patch fixing that!
