### ISSUE TITLE
Some python programs are in python-modules

### ISSUE THREAD

**Issue by Aleksanaa** [NixOS/nixpkgs#332191]
### Problem

I just discovered that in `pkgs/development/python-modules`:

```
=> grep -r 'mainProgram' . | wc -l
1210

=> find . -maxdepth 1 -type d | wc -l
7526
```

So 1210 out of 7526 python modules have a `mainProgram`. And also a lot of them (most?) don't have a `toPythonApplication` in top-level.

So now we have 3 approaches to package a python application:

1. use `python3Packages.buildPythonApplication`, and put it in `pkgs/by-name`.
2. use `buildPythonPackage` and put in `pkgs/development/python-modules`, and add a `toPythonApplication` entry in all-packages.nix
3. use `buildPythonPackage` and put in `pkgs/development/python-modules`, and let users write `python3Packages.foo`

### Solution

If the upstream documentation doesn't mention it can be used as a python module, then only 1 is correct. If upstream doesn't mention but there do have some examples, then `toPythonModule` should be used (but we can also tolerate `toPythonApplication` and put in `python-modules`).

If it's primarily used as a module, but also has some useful executables, then 2 is correct. If it's only used as a python module, or the executable doesn't have external use cases (for example, is serving the needs of the module), then only 3 is correct.

This should be explicitly documented and anti-patterns should be removed

**Comment by Aleksanaa** [comment]
ping @natsukium @fabaff

**Comment by AndersonTorres** [comment]
Hum, my suspects about `git-filter-repo` have some basis...

**Comment by fabaff** [comment]
`mainProgram` was added automatically (in most cases) with https://github.com/NixOS/nixpkgs/pull/297084. I assume that most of the 1210 hits were coming for that PR.

**Comment by dotlambda** [comment]
I don't think having a top-level alias is a necessity. If any of those are *only* tools and don't provide an API, they should be removed from `python3Packages`. But having `mainProgram` is not a sufficient condition.
