### ISSUE TITLE
Package request: `services.open-webui` for 24.05

### ISSUE THREAD

**Issue by nixupp** [NixOS/nixpkgs#332260]
Ollama is a big project and I think having a nice UI in the stable repos would make nix even better.

I can help with the PR but I am new to nix and don't really understand the git workflow and all

Pinging the package maintainer: @shivaraj-bh 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by shivaraj-bh** [comment]
Current master is broken for `open-webui` (see https://github.com/NixOS/nixpkgs/pull/331504#issuecomment-2265003770). However, I don’t think that should a problem while backporting `open-webui` to `24.05`, as [asgiref is still on 3.7.2 there](https://github.com/NixOS/nixpkgs/blob/bda052c9d934a49b30274b140dcd500624687f7d/pkgs/development/python-modules/asgiref/default.nix#L13).

**Comment by shivaraj-bh** [comment]
Backport PR for `open-webui` 0.2.4: https://github.com/NixOS/nixpkgs/pull/332412

**Comment by shivaraj-bh** [comment]
https://github.com/NixOS/nixpkgs/pull/332412

**Comment by shivaraj-bh** [comment]
To track the progress of backporting to latest `open-webui`, see: https://github.com/NixOS/nixpkgs/pull/332915

**Comment by nixupp** [comment]
I love this, thanks!!
