### ISSUE TITLE
Angry IP Scanner fails to start

### ISSUE THREAD

**Issue by ToasterUwU** [NixOS/nixpkgs#332320]
### Describe the bug
When opening Angry IP Scanner, i get an error message about it trying to load the "SWT" library, but failing to do so because im trying to use a binary made for a "different OS or CPU"

### Steps To Reproduce
1. Install Angry IP Scanner
2. Start
3. Error popup message appears

### Expected behavior
Should just start and work

### Screenshots
![image](https://github.com/user-attachments/assets/e9722adb-323a-46bb-9d01-617db96701ff)

### Additional context
Nothing

### Notify maintainers
@kylesferrazza 
@totoroot 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1-zen1, NixOS, 24.11 (Vicuna), 24.11.20240731.9f918d6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/7v6l2v247fmdgfpbs3w91mf6rinai4yk-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kylesferrazza** [comment]
Closed in https://github.com/NixOS/nixpkgs/pull/338234
