### ISSUE TITLE
callCabal2nix doesn't work anymore

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#33235]
## Issue description

`cabal2nix: NoHackageTarballFound`

### Steps to reproduce

Use callCabal2nix anywhere

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5810_5d5b931f`
 - channels(root): `"nixpkgs-18.03pre120540.b8f7027360"`
 - nixpkgs: `/Users/judet/.nix-defexpr/nixpkgs`

**Comment by globin** [comment]
cc @domenkozar, @peti, @shlevy

**Comment by peti** [comment]
Cc: https://github.com/NixOS/cabal2nix/issues/319

**Comment by nmattia** [comment]
@peti when can we expect 2.7.2 to land in Nixpkgs?

**Comment by peti** [comment]
master @ 81581ba38100d3a626a8caeb015dd3f8866c3398 has the new version.

**Comment by nmattia** [comment]
wonderful, thanks a lot!

**Comment by idontgetoutmuch** [comment]
But
```
bash-3.2$ cabal2nix --version
cabal2nix 2.8
bash-3.2$ cabal2nix cabal://mtl
cabal2nix: NoHackageTarballFound
```

**Comment by shlevy** [comment]
@idontgetoutmuch You need to run `cabal update` first.

**Comment by idontgetoutmuch** [comment]
```
bash-3.2$ cabal update
Downloading the latest package list from hackage.haskell.org
bash-3.2$ cabal2nix cabal://mtl
cabal2nix: NoHackageTarballFound
```

**Comment by idontgetoutmuch** [comment]
OTOH if I do `cabal fetch` and ungzip and untar I get
```
bash-3.2$ cabal2nix .
{ mkDerivation, base, stdenv, transformers }:
mkDerivation {
  pname = "mtl";
  version = "2.2.1";
  src = ./.;
  libraryHaskellDepends = [ base transformers ];
  homepage = "http://github.com/ekmett/mtl";
  description = "Monad classes, using functional dependencies";
  license = stdenv.lib.licenses.bsd3;
}
```

**Comment by shlevy** [comment]
@peti?

**Comment by domenkozar** [comment]
is cabal version 1 or 2?

**Comment by idontgetoutmuch** [comment]
```
bash-3.2$ which cabal
/Users/dom/.nix-profile/bin/cabal
bash-3.2$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library 
```

**Comment by peti** [comment]
@idontgetoutmuch, where does your `cabal2nix` binary come from and what is its version?

**Comment by idontgetoutmuch** [comment]
@peti sorry not to have replied - I can no longer reproduce.

**Comment by peti** [comment]
That probably was an old version of  `cabal2nix` that didn't know how about `01-index.tar` used by `cabal-install` version 2.x.

**Comment by idontgetoutmuch** [comment]
@peti thanks - if you have time, I have a reproducible problem with `callCabal2nix` atm: https://github.com/NixOS/nixpkgs/issues/70250
