### ISSUE TITLE
Build failure: python313Packages.cython

### ISSUE THREAD

**Issue by amyipdev** [NixOS/nixpkgs#332407]
### Steps To Reproduce

1. Have a config that implicitly pulls Cython.
2. Use Python 3.13.
3. Observe failure.

### Build log

I lost the build log but can provide the config which generates the issue.

Take https://github.com/amyipdev/nixos-config and replace all instances of `python312` with `python313`. You need to add in a `hardware-configuration.nix` for this to work, and a `platform.nix` of the following schema:

```nix
{
  hostName = "someHostname";
  stateVersion = "23.11";
  # format: Interface-1,1234x5678,100x300,1
  # interface,resolution,offset,scale
  monitors = [
    "DP-1,1920x1080,5490x880,1"
    # other monitors here, Hyprland format
  ];
}
```

### Additional context

This build failure cascades down into a Python build failure, which causes other build failures, and eventually stops the build. Just replacing `python313` with `python312` everywhere in my config fixes this.

### Notify maintainers

No current maintainers.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.2, NixOS, 24.11 (Vicuna), 24.11pre661606.d04953086551`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
`python313Packages.cython` builds fine on master. Please provide an easy way to reproduce this.

**Comment by amyipdev** [comment]
I provided my config. Note, I did just push a patch which changes the needed elements of `platform.nix`, but otherwise these issues should be reproducible.

**Comment by dotlambda** [comment]
Your config doesn't have the word cython in it. You could at least post the output of `nixos-rebuild --show-trace`.

**Comment by amyipdev** [comment]
Cython gets built as a dependent package; thought that was obvious.

**Comment by dotlambda** [comment]
> Cython gets built as a dependent package; thought that was obvious.

Dependent package of what?
