### ISSUE TITLE
Non-merged Plasma themes

### ISSUE THREAD

**Issue by medovuxa** [NixOS/nixpkgs#33245]
## Issue description

- [x] Kvantum theme engine https://github.com/NixOS/nixpkgs/pull/27593
- [x] "KDE 2" window decoration https://github.com/NixOS/nixpkgs/pull/33173
- [x] Arc full theme https://github.com/NixOS/nixpkgs/pull/33208

Calling Plasma maintainer @ttuegel

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by gnidorah** [comment]
@ttuegel Thank you much! And happy New Year!

**Comment by medovuxa** [comment]
@ttuegel Thank you much! And happy New Year!
