### ISSUE TITLE
Package request: catnap

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#332645]
**Project description**

A highly customizable systemfetch written in nim.

**Metadata**

* homepage URL: https://catnap-fetch.xyz
* source URL: https://github.com/iinsertNameHere/catnap
* license: mit
* platforms: linux

**Comment by eclairevoyant** [comment]
but why tho
do we not have enough *fetch scripts? afetch, owofetch, hayabusa, maxfetch, fastfetch, neofetch, hyfetch, yafetch, bunnyfetch, leaf, cpufetch, screenfetch, disfetch, bfetch, fet-sh ...

even for nim specifically (not that the language should matter so much) we have `nitch`

**Comment by s0me1newithhand7s** [comment]
> but why tho do we not have enough *fetch scripts? afetch, owofetch, hayabusa, maxfetch, fastfetch, neofetch, hyfetch, yafetch, bunnyfetch, leaf, cpufetch, screenfetch, disfetch, bfetch, fet-sh ...
> 
> even for nim specifically (not that the language should matter so much) we have `nitch`

and we don't want to transform nixpkgs into fetches junkyard
