### ISSUE TITLE
Build failure: mymcplus

### ISSUE THREAD

**Issue by iam-angel-val** [NixOS/nixpkgs#332624]
### Steps To Reproduce

1. build mymcplus

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'shell'
         whose name attribute is located at /nix/store/7v6l2v247fmdgfpbs3w91mf6rinai4yk-source/pkgs/stdenv/generic/make-derivation.nix:334:7

       … while evaluating attribute 'buildInputs' of derivation 'shell'

         at /nix/store/7v6l2v247fmdgfpbs3w91mf6rinai4yk-source/pkgs/stdenv/generic/make-derivation.nix:381:7:

          380|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          381|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          382|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: wxpython-4.2.1 not supported for interpreter python3.12
```

### Additional context

The problem is simply that the package depends on the latest wxpython, which is incompatible with mymcplus' code.
I built the 24.05 version of the package (as opposed to the unstable version) and it built just fine. I was also able to launch the gui by creating a shell with python311Packages.wxpython, so I think this could be fixed by chaning pythonPackages in the package source to python311Packages.

### Notify maintainers

@Stunkymonkey @lasers 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.43, NixOS, 24.11 (Vicuna), 24.11.20240731.9f918d6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/7v6l2v247fmdgfpbs3w91mf6rinai4yk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
#326142 might fix this as well

**Comment by smancill** [comment]
It's building:

https://hydra.nixos.org/job/nixpkgs/trunk/mymcplus.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/mymcplus.x86_64-linux
