### ISSUE TITLE
Dictionary warnings during GNOME Evolution startup

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#332736]
### Describe the bug

The following messages appear repeatedly attached to a ".evolution-wrap" unit in `journalctl`:

> Impossible to create an Enchant dictionary for the language code 'de'.

and

> e_spell_dictionary_check_word: assertion 'enchant_dict != NULL' failed

### Steps To Reproduce
1. Add `'de'` to `(builtins.elemAt config.programs.dconf.profiles.user.databases 0).settings."org/gnome/evolution/mail".composer-spell-languages`
2. `sudo nixos-rebuild switch`
3. Start GNOME Evolution

### Expected behavior

No such error.

### Additional context

These messages show up as belonging to a unit called ".evolution-wrap", but unfortunately that string doesn't show up anywhere in the list of user or system services, nor do any of the logs for the services containing "evolution" contain these messages.

There doesn't seem to be any information about what the values in this list should be, beyond "[dictionary language codes](https://gitlab.gnome.org/GNOME/evolution/-/blob/f2cc29c73aeaa40f42c82e60ea7ef1451f320352/data/org.gnome.evolution.mail.gschema.xml.in#L151-155)".

I've also tried values "de_DE" and "en_US", with the same results.

---

Update: Even after setting `composer-spell-languages = mkEmptyArray type.string;` I still get messages like this:

> Impossible to create an Enchant dictionary for the language code 'en'.

Despite not selecting any languages I had to also set `composer-inline-spelling = false;` to avoid this warning. But now of course I have no spell checking.

### Notify maintainers

@bobby285271 @hedning @jtojnar @dasj19

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.2, NixOS, 24.11 (Vicuna), 24.11pre661606.d04953086551`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
How did you install the spell checker dictionaries?

Evolution uses gspell, which uses Enchant, so you will need to install one of the dictionaries for it.

At least hunspell dictionaries like `hunspellDicts.de_DE` should just work in `environment.systemPackages` since hunspell data directory is in `environment.pathsToLink`:

https://github.com/NixOS/nixpkgs/blob/4c33e4b301d5a6e8d2ce95e5047b6d92f793971d/nixos/modules/config/system-path.nix#L155

**Comment by l0b0** [comment]
> How did you install the spell checker dictionaries?

I'm installing [aspell](https://gitlab.com/engmark/root/-/blob/745d876092644dbd755b64bdaefdb0593a31ca0e/modules/gui.nix#L806-813) and [hunspell](https://gitlab.com/engmark/root/-/blob/745d876092644dbd755b64bdaefdb0593a31ca0e/modules/gui.nix#L40-46) dictionaries

> Evolution uses gspell, which uses Enchant, so you will need to install one of the dictionaries for it.

*Another* spell checking framework?

> At least hunspell dictionaries like `hunspellDicts.de_DE` should just work in `environment.systemPackages` since hunspell data directory is in `environment.pathsToLink`:
> 
> https://github.com/NixOS/nixpkgs/blob/4c33e4b301d5a6e8d2ce95e5047b6d92f793971d/nixos/modules/config/system-path.nix#L155

I mean, there's a list of "Unknown (de)", "Unknown (de_DE)", etc. dictionaries shown in Evolution, but it still fails just as much.

**Comment by AlisterH** [comment]
I'm not using Evolution (or German dictionaries), but I see the same "Impossible to create an Enchant dictionary for the language code..." error when trying to use mousepad with aspell dictionaries.  Using hunspell dictionaries instead works.

**Comment by l0b0** [comment]
FYI: Moved to Thunderbird, so I won't be following up on this issue. Please open a new issue if you encounter this.
