### ISSUE TITLE
Bug: ventoy - `ventoy-gui` doesn't run

### ISSUE THREAD

**Issue by chewblacka** [NixOS/nixpkgs#332703]
### Describe the bug
When enabling the GUI under either the `ventoy` or `ventoy-full` package, running `ventoy-gui` doesn't work.

### Steps To Reproduce
1. Install ventoy with GUI enabled, e.g. ` (ventoy.override { withGtk3 = true; })` or using `withQt5 = true`
2. run `ventoy-gui` which is now in the path
3. Nothing happens. Shell shows command has exited with an error but no error messages displayed.

### Expected behavior
`ventoy-gui` should open and run, or at least give an error message.

### Additional context
This is somewhat of a duplicate of https://github.com/NixOS/nixpkgs/issues/282036, but am re-doing since that issue was primarily about how to install, and didn't notify maintainer.

### Notify maintainers
@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240719.1d9c2c9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - channels(user): `""`
 - nixpkgs: `/nix/store/l6spwdi1xs20q24fqfi3xwxx0d2x9q2m-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
based on `strace`:

```
getcwd("/nix/store/8lf3xv4pgnbccm6zv0yzijg8pmzyk1gd-ventoy-1.0.99/share/ventoy", 4096) = 71                                         getuid()                                = 1001                    getppid()                               = 884672                  getpid()                                = 884675                  openat(AT_FDCWD, "log.txt", O_RDWR|O_CREAT|O_APPEND, 0666) = -1 EROFS (Read-only file system)
```

**Comment by eclairevoyant** [comment]
Whoever wants to fix it will need to know the cause, which the logs point at.

**Comment by balataca** [comment]
Hello @chewblacka, I had the same issues as you after installing ventoy or ventoy-full:

* No desktop file created
* Unable to run `ventoy-gui` command, also I couldn't get any output.

To fix this issues I just had to add these options to the package:
```
environment.systemPackages = with pkgs; [
    (ventoy.override {
      defaultGuiType = "gtk3";
      withGtk3 = true;
    })
];
```

I am using GNOME as my DE, so that's why I used `gtk3`, but if you use kde for example you have to change this to:
```
environment.systemPackages = with pkgs; [
    (ventoy.override {
      defaultGuiType = "qt5";
      withQt5 = true;
    })
];
```

**Comment by chewblacka** [comment]
Note to myself (and anyone else). There isn't a bug here. The intended way to choose your gui type (e.g. gtk3) is:

    (ventoy.override { defaultGuiType = "gtk3"; })

if you do instead 

    (ventoy.override { withGtk3 = true; })

then e.g. the correct `buildInputs` won't be loaded as they depend on the user boolean `defaultGuiType` not the internal boolean `withGtk3`. Hence it won't work. I must have been asleep when I opened this issue.

Closing due to user error (mine).

**Comment by boustanihani** [comment]
This works for me:
```
(ventoy-full.override {
      defaultGuiType = "gtk3";
      withGtk3 = true;
})
```

If I only do this:
```
(ventoy-full.override {
      defaultGuiType = "gtk3";
})
```

Then I get the following error:
```
       error: assertion '((defaultGuiType == "gtk3") -> withGtk3)' failed

       at /nix/store/a41pwzpr2zqqc7djgrlc5w1vg504dwqa-nixos-24.05/nixos/pkgs/by-name/ve/ventoy/package.nix:37:1:

           36| assert lib.elem defaultGuiType [ "" "gtk3" "qt5" ];
           37| assert defaultGuiType == "gtk3" -> withGtk3;
             | ^
           38| assert defaultGuiType == "qt5" -> withQt5;
```

**Comment by chewblacka** [comment]
> Does this mean that we always need to set both variables?

You are correct. My mistake. Currently both variables need to be set otherwise it errors. I've put in a PR which would change this so only `defaultGuiType` needs to be set by the user. IMHO this simplifies the user experience without any untoward downsides that I can see.

**Comment by chewblacka** [comment]
> Is it not possible to automate the gui type?

If you mean change the default so it includes a gui, then sure this is possible. But you would need to make a good argument / case for it with the package maintainer. I recommend opening another PR if you feel strongly about it and can justify your case, as this one will be closed soon and marked completed.
