### ISSUE TITLE
Pretix gives "Unknown Host" error

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#332779]
### Describe the bug
When using the pretix module, we're getting an "Unknown Host" page. All requests get logged as "bad request". I found [this issue](https://github.com/pretix/pretix/discussions/2601#discussioncomment-2624107), and the first comment under it pointed to the Host header nginx is sending to pretix.

Adding the following fixes the problem, but I don't know enough about pretix or nginx to say whether this should be added to the pretix module, or if it's something specific to our setup.

```
services.nginx.virtualHosts.${services.pretix.nginx.domain} = {
  locations."/".extraConfig = ''
    proxy_set_header Host $host;
  '';
};
```

The configuration is private. I can make a minimal reproduction of the problem if that's helpful, but I figured before I put in that effort the maintainer might understand what's going on just from this much.

### notify maintianers
@mweinelt 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Have you set `services.pretix.nginx.domain`?

**Comment by Radvendii** [comment]
Yes

**Comment by mweinelt** [comment]
And `services.pretix.settings.pretix.url`?

**Comment by Radvendii** [comment]
Yep, that's set to the right thing too. We basically have
```
let
  hostName = tickets.example.com;
in
services.pretix = {
  nginx.domain = hostName;
  settings.pretix.url = "https://${hostName}";
};
```

And navigating to `https://<hostName>` clearly connects to pretix, since we get the unknown hostname page from pretix. I also checked the generated pretix config file and it has the `[pretix]` section with `url=https://<hostName>` set

**Comment by mweinelt** [comment]
How about `recommendedProxySettings`?

**Comment by Radvendii** [comment]
That's the one. We have it disabled :woman_facepalming: 

Thanks, sorry for the noise!
