### ISSUE TITLE
Package request: meteor

### ISSUE THREAD

**Issue by kcoderhtml** [NixOS/nixpkgs#332795]
**Project description**

It's a conventional commits git helper that has a gorgeous TUI

**Metadata**

* homepage URL: https://github.com/stefanlogue/meteor
* source URL: https://github.com/stefanlogue/meteor
* license: mit
* platforms: unix, linux, darwin, (basicaly anything with go)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
Name conflicts with [`meteor`](https://search.nixos.org/packages?channel=unstable&show=meteor&size=1).

**Comment by kcoderhtml** [comment]
I think renaming it to meteor-git would solve that
