### ISSUE TITLE
Some Steam games using Steamworks fail to connect

### ISSUE THREAD

**Issue by wizardlink** [NixOS/nixpkgs#332990]
### Describe the bug

As the title entails, certain games, namely Ground Branch, Dungeon Defenders and Grocery Store Simulator fail to gather information from Steam, such as my friend list or trigger the overlay's invite window.

I cannot for the life of me understand why, I have attempted to wipe Steam's local contents to no avail and ended up re-installing my system which has fixed my issue. Here's the caveat of all this: My laptop which has basically the same configuration (minus the services and open ports) does not presents the same issues, this issue only has occurred after weeks of use so I am now unsure whether it is a problem with NixOS or Steam - however as I mentioned, cleaning files from Steam does not fixes the issue so I'm inclined to think it's an issue in the NixOS side.

### Steps To Reproduce
I do not know how to reproduce this behaviour, but [my configuration is public](https://github.com/wizardlink/linuxware) if that helps.

### Expected behavior
I should be able under these games to connect to Steam's API and invite friends, inside them my hostname usually gets assigned as my username.

### Screenshots
![image](https://github.com/user-attachments/assets/af360950-836b-456a-86b9-c40556192ca8)
> (Ground Branch) I should be able to see servers here, friends are able to see a few. Same case in Dungeon Defenders.

![image](https://github.com/user-attachments/assets/84e0fd74-7615-49b7-b6f4-12e79876ff21)
> (Grocery Store Simulator) My name should not be my hostname and the icon not white - the invite friends should also open the steam overlay.

### Additional context
- [Ground Branch logs](https://drive.proton.me/urls/MM7E17NP08#9vznpH6ClT5s)
- [Grocery Story Simulator logs](https://github.com/user-attachments/files/16524631/steam-2961880.log)

### Notify maintainers
@atemu @eclairevoyant @k900 @mkg20001 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1-zen1, NixOS, 24.11 (Vicuna), 24.11.20240802.d049530`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/920a6ivyd50598z8djw9x3mr33gys0j5-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wizardlink** [comment]
I apologise for the lack of context, I truly don't know where to go from here. If I can get directions on how to debug this it would be be greatly appreciated.

**Comment by eclairevoyant** [comment]
```
$ rg -i '\bport\b' steam-16900.log        
249272:2596.793:0130:0134:warn:seh:OutputDebugStringW L"[2024.03.23-07.34.26:378][807]LogNet: Created socket for bind address: 0.0.0.0 on port 7777\r\n"
249278:2596.793:0130:0134:warn:seh:dispatch_exception L"[2024.03.23-07.34.26:378][807]LogNet: Created socket for bind address: 0.0.0.0 on port 7777\r\n"
249404:2596.793:0130:0134:warn:seh:OutputDebugStringA "[2024.03.23-07.34.26:378][807]LogNet: Created socket for bind address: 0.0.0.0 on port 7777\r\n"
249408:2596.793:0130:0134:warn:seh:dispatch_exception "[2024.03.23-07.34.26:378][807]LogNet: Created socket for bind address: 0.0.0.0 on port 7777\r\n"
249806:2596.795:0130:0134:warn:seh:OutputDebugStringW L"[2024.03.23-07.34.26:380][807]LogNet: GameNetDriver IpNetDriver_2147480525 IpNetDriver listening on port 7777\r\n"
249812:2596.795:0130:0134:warn:seh:dispatch_exception L"[2024.03.23-07.34.26:380][807]LogNet: GameNetDriver IpNetDriver_2147480525 IpNetDriver listening on port 7777\r\n"
249938:2596.795:0130:0134:warn:seh:OutputDebugStringA "[2024.03.23-07.34.26:380][807]LogNet: GameNetDriver IpNetDriver_2147480525 IpNetDriver listening on port 7777\r\n"
249942:2596.795:0130:0134:warn:seh:dispatch_exception "[2024.03.23-07.34.26:380][807]LogNet: GameNetDriver IpNetDriver_2147480525 IpNetDriver listening on port 7777\r\n"
```

Seems like you need port 7777 opened up.

**Comment by wizardlink** [comment]
That's for hosting a dedicated server, doesn't impedes me from finding servers or opening one through UPnP. o7

**Comment by eclairevoyant** [comment]
In that case, I'd try removing all the log lines with `:trace:` and looking at the remaining lines for errors. Sorry, don't think I can help further since I don't have your games, hardware, or knowledge about the logs.

**Comment by wizardlink** [comment]
My main question really is how to reset the "state" of Steam, considering that removing Steam local files did not solve the issue but re-installing the system with the same configuration does.

**Comment by eclairevoyant** [comment]
Nix/nixpkgs/NixOS does not control how Steam stores its state, so that's not really a question for this repo.

**Comment by wizardlink** [comment]
I understand that, just weird how removing every trace of Steam doesn't fixes the issue - so I had to assume it could've been a NixOS problem. Will be closing this issue then.
