### ISSUE TITLE
php: buildComposer does not output vendorHash

### ISSUE THREAD

**Issue by mark-boute** [NixOS/nixpkgs#332989]
### Describe the bug
When building this derivation, no vendorHash is logged. Meaning the build never gets past the check stage.

package.nix:
```nix
{ lib, php83, fetchFromGitHub }:

php83.buildComposerProject (finalAttrs: {
  pname = "ppelican-panel";
  version = "v1.0.0-beta7";

  src = fetchFromGitHub {
    owner = "pelican-dev";
    repo = "panel";
    rev = finalAttrs.version;
    hash = "sha256-h0+6rDy7U24XEdqAnfd8Q77VE8Ji2llSxy/vQawPQw4=";
  };

  php83 = php83.buildEnv {
    extensions = ({ enabled, all }: enabled ++ (with all; [
      gd
      mysqli
      mbstring
      bcmath
      xml
      curl
      zip
      intl
      sqlite3
    ]));
  };

  # The composer vendor hash
  vendorHash = lib.fakeHash;
})
```

### Steps To Reproduce
1. run `nix-build` in folder containing package.nix
2. Composer starts installing a bunch of packages
3. See error without vendor hash.

### Expected behavior
I expect an output containing the actual vendor hash.

### Screenshots
![image](https://github.com/user-attachments/assets/662356f3-645c-4240-b9cd-69f40589d44d)

### Additional context
I am trying to package https://pelican.dev/

### Notify maintainers

@drupol

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.20240805.883180e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/79j6vc975md1w3f2fgli3xw657zyxxyc-source`
```

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
Hello,

The red message explains clearly the reasons. This issue has to be fixed upstream.

To verify by yourself, just clone the project and do `composer validate`.

If you don't want to let upstream know about the issue, you can disable the validation by adding the attribute `composerStrictValidation = true;` but I don't recommend that.

**Comment by mark-boute** [comment]
Hi, thank you for the fast response!

The lock file seems outdated indeed, it just didn't seem to affect my install attempt on a Ubuntu system.

For now `composerStrictValidation = false;` resolved my issue, will be posting an issue upstream.

Thanks a lot!
