### ISSUE TITLE
`digikam` won't start with `QT_QPA_PLATFORM=wayland` anymore

### ISSUE THREAD

**Issue by jnsgruk** [NixOS/nixpkgs#332981]
### Describe the bug
I used to be able to run Digikam like so:

```
nix shell unstable#digikam unstable#exiftool -c digikam
```

But for a few days now, I've been getting the following error:

```
❯ nix shell unstable#digikam unstable#exiftool -c digikam
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

zsh: abort (core dumped)  nix shell unstable#digikam unstable#exiftool -c digikam
```

I'm running Hyprland, and setting `QT_QPA_PLATFORM=wayland` in my session. I can force the app to run by setting `QT_QPA_PLATFORM=xcb`, though things are very ugly!

### Steps To Reproduce

```
nix shell unstable#digikam unstable#exiftool -c digikam
```

### Expected behavior

The app should launch, respecting the configured theme.

### Notify maintainers

@emilazy - I can see you're not listed as a maintainer, though I also see a lot of commits against `digikam` - I hope it's okay to ping!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/l0992b1shksi7k8w1x6wzi61zbs48vck-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jnsgruk** [comment]
@eclairevoyant I also noticed you doing some work on qt apps - not sure if you'll have an opinion here? :)

**Comment by jnsgruk** [comment]
I've gone back through the commits, building Digikam each time, and the last working commit seems to be https://github.com/NixOS/nixpkgs/commit/282f3440bb8965669df136c05291fcf90b7915c2, before the transition to 8.4.0 and qt6.

**Comment by eclairevoyant** [comment]
I know this sounds really stupid, but this can be worked around by adding `qt6.qtwayland` to a package set.

It could be added to the `digikam` expression, but it might make more sense to add it to the qt wrapper.

**Comment by emilazy** [comment]
Wait, does that mean that Qt 6 applications don’t work with Wayland out of the box? 🤔

That’s very strange if so, and does indeed seem like something better handled in a wrapper than in every leaf package.

**Comment by eclairevoyant** [comment]
> Wait, does that mean that Qt 6 applications don’t work with Wayland out of the box? 🤔

Well they do work, they will just run in an X window rather than native Wayland.

**Comment by eclairevoyant** [comment]
PS exiftool should no longer be required in a day or two: https://nixpkgs-tracker.ocfox.me/?pr=332614
