### ISSUE TITLE
babashka v1.3.191 breaks when running print-deps --format classpath

### ISSUE THREAD

**Issue by bennyandresen** [NixOS/nixpkgs#333029]
### Steps To Reproduce
Steps to reproduce the behavior at the moment:
```
$ nix run github:nixos/nixpkgs/nixos-unstable#babashka -- --version
babashka v1.3.191
$ nix run github:nixos/nixpkgs/nixos-unstable#babashka -- print-deps --format classpath
Clojure tools not yet in expected location: /nix/store/bgvczncbcr3gidd8bk38kl1l2a655fn3-babashka-1.3.190/clojure_tools/clojure-tools-1.11.3.1463.jar
Exception in thread "main" java.io.FileNotFoundException: /nix/store/bgvczncbcr3gidd8bk38kl1l2a655fn3-babashka-1.3.190/clojure_tools/TRANSACTION_START (Read-only file system)
        at java.base@22.0.2/java.io.FileOutputStream.open0(Native Method)
        at java.base@22.0.2/java.io.FileOutputStream.open(FileOutputStream.java:289)
        at java.base@22.0.2/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
        at clojure.java.io$fn__11619.invokeStatic(io.clj:230)
[...]
```
### Expected behavior
```
$ nix run github:nixos/nixpkgs/release-24.05#babashka -- --version
babashka v1.3.190
$ nix run github:nixos/nixpkgs/release-24.05#babashka -- print-deps --format classpath
src:/home/benny/.gitlibs/libs/babashka/babashka.core/52a6037bd4b632bffffb04394fb4efd0cdab6b1e/src:/home/benny/.m2/repository/babashka/babashka.curl/0.1.2/babashka.curl-0.1.2.jar:/home/
benny/.m2/repository/babashka/fs/0.4.19/fs-0.4.19.jar:/home/benny/.m2/repository/babashka/process/0.5.21/process-0.5.21.jar:[...]
```

### Additional context
This also affects the downstream package `clojure-lsp` when running `clojure-lsp diagonistics`

Please note the clojure-tools location in the Exception trace in v1.3.191 is attempting to load the clojure-tools in v1.3.190.
So I think this issue disappears when babashka releases an additional version that is packaged in nixpkgs when clojure-tools isn't bumped upstream.

### Notify maintainers
@DerGuteMoritz @bhougland18 @thiagokokada @jlesquembre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.05 (Uakari), 24.05.20240805.883180e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(benny): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/79j6vc975md1w3f2fgli3xw657zyxxyc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DerGuteMoritz** [comment]
> So it appears that babashka reads some environmental variable to try to access clojure-tools under the current babashka store path.

This is controlled via `DEPS_CLJ_TOOLS_DIR` which the wrapper script sets a default value pointing to the correct version [here](https://github.com/nixos/nixpkgs/blob/d04953086551086b44b6f3c6b7eeb26294f207da/pkgs/development/interpreters/babashka/wrapped.nix#L38). Do you happen to have that variable set in your environment? FWIW, I don't have it set and `nix run github:nixos/nixpkgs/nixos-unstable#babashka -- print-deps` works for me.

> Is that worth fixing? If so, does anyone have an idea how?

One could instead hardcode the location to the correct one but that would then not allow for providing a different `clojure-tools` version anymore, of course. But I suppose that's a rarely used feature so maybe fine? Thoughts?

**Comment by bennyandresen** [comment]
Oh that's pretty embarassing. Sorry for the pings everyone and thanks a lot @DerGuteMoritz.

I do have `DEPS_CLJ_TOOLS_DIR` set, but unintentionally. I have a wrapper script that handles my virtual terminals based on current virtual desktop, screen, etc. that's written in babashka and my shell inherits `DEPS_CLJ_TOOLS_DIR` that way.
