### ISSUE TITLE
Update request: Sherlock v0.14.4 → Sherlock v0.15.0

### ISSUE THREAD

**Issue by returnofblank** [NixOS/nixpkgs#333082]
- Package name: sherlock
- Latest released version: v0.15.0

- Current version on the unstable channel: 0-unstable-2024-06-09
- Current version on the stable/release channel: 0-unstable-2024-05-15

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@applePrincess 

Some extra info: Current version of sherlock may be broken potentially because it's outdated.
```
➜ sherlock test1
A problem occurred while checking for an update: list index out of range
ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json'.
```

The link is broken.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ryand56** [comment]
I'll work on updating this. Current sherlock version is also broken for me.
