### ISSUE TITLE
Update request: edgedb 5.1.0 → 5.2.3

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#333057]
- Package name: edgedb
- Latest released version: 5.2.3

- Current version on the unstable channel: 4.1.1
- Current version on the stable/release channel: 5.1.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@kirillrdy  @ahirner 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MisileLab** [comment]
reference: https://github.com/edgedb/edgedb-cli/tags

**Comment by ahirner** [comment]
https://github.com/NixOS/nixpkgs/pull/333155
