### ISSUE TITLE
Update request: flutter 3.22.x → 3.24.0

### ISSUE THREAD

**Issue by manuel-plavsic** [NixOS/nixpkgs#333197]
- Package name: flutter (stable, but also beta)
- Latest released version: 3.24.0

- Current version on the unstable channel: 3.22.2 (beta `flutter323` version: 3.23.0)
- Current version on the stable/release channel: 3.22.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@RossComputerGuy

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
CC @NixOS/flutter 

#324717 has been a blocker for updates since it affects the update script but it is close to being ready.

**Comment by RossComputerGuy** [comment]
Yeah, I hope to have it done soon. It's close. Unfortunately, I just don't always have enough time.

**Comment by Henry-Hiles** [comment]
> Yeah, I hope to have it done soon. It's close. Unfortunately, I just don't always have enough time.

Yeah, of course! Take your time :)

**Comment by Jonas-Sander** [comment]
Hey, since the blocker is merged, how is it looking with updating the flutter version? :) No worries, if you're too busy right now

**Comment by RossComputerGuy** [comment]
> how is it looking with updating the flutter version?

I plan on doing that on my next day off work which will be Thursday.
