### ISSUE TITLE
Package request: equibop

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#333175]
**Project description**

A custom Discord App (a fork of [Vesktop](https://github.com/Vencord/Vesktop)) aiming to provide better performance and improve linux support. [Equicord](https://github.com/Combatmaster331/Equicord) (an enhanced version of [Vencord](https://github.com/Vendicated/Vencord)) is preinstalled. 

**Metadata**

* homepage URL: https://github.com/Equicord/equibop
* source URL: https://github.com/Equicord/equibop
* license: gpl3
* platforms: linux

**Comment by h4rldev** [comment]
+1

**Comment by FormunaGit** [comment]
+1

**Comment by NotAShelf** [comment]
I'll try tackling this. Should be simple, in theory.

**Comment by NotAShelf** [comment]
https://github.com/NixOS/nixpkgs/pull/349863 for those tracking this issue.
