### ISSUE TITLE
Package request: Dbeaver for Darwin

### ISSUE THREAD

**Issue by mmorley0395** [NixOS/nixpkgs#333226]
**dbeaver-bin for Darwin**

In 23.11, darwin was part of the dbeaver default.nix. It seems that that was removed or omitted in 24.05. I am a pretty new nix user otherwise would attempt to add darwin myself

* [dbeaver homepage](https://dbeaver.io/):
* platforms: linux, darwin,

---

**Comment by luftmensch-luftmensch** [comment]
Reading the [definition](https://github.com/NixOS/nixpkgs/blob/cb9a96f23c491c081b38eab96d22fa958043c9fa/pkgs/by-name/db/dbeaver-bin/package.nix#L104) I see `darwin` listed as supported platform. Am I missing something?

**Comment by mmorley0395** [comment]
Sorry-- I was looking [here](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/db/dbeaver-bin/package.nix). Was in the 24.05 tag because that's where my system is. Apologies! Will close this, thanks for your time
