### ISSUE TITLE
qrtool repo was deleted

### ISSUE THREAD

**Issue by YDX-2147483647** [NixOS/nixpkgs#333254]
- Package name: qrtool
- Latest released version: 0.11.4

- Current version on the unstable channel: 0.11.4
- Current version on the stable/release channel: 0.10.10

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@philiptaron

---

qrtool 0.11.4 was [just released on 2024-08-04 to crates.io](https://crates.io/crates/qrtool/versions), and was updated in #332314, but now https://sorairolake.github.io/qrtool/book/index.html (homepage), https://github.com/sorairolake/qrtool (repo) and even @sorairolake (owner) become 404 Not Found.

I have no idea what have happened…

Besides, `nix-shell -p qrtool` still works.

**Update**
https://gitlab.com/sorairolake/qrtool

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by philiptaron** [comment]
Sad!

I'm camping for the next week... but unless the package and author reappears, we'll need to delete it, sadly.

**Comment by YDX-2147483647** [comment]
Could we wait for one or two weeks? It looks like that @sorairolake is fine, but GitHub somehow locks the account.

https://x.com/sorairolake/status/1821349135384985957

> GitHubのアカウントに何故かフラグが立ったから異議申し立てした
>
> Translate: My GitHub account was flagged for some reason, so I protested.

> 返信まで結構時間がかかるかもしれないけど、解除されれば良いのだが
>
> Translate: It may take a while to get a response, but I hope it will be resolved.

**Comment by philiptaron** [comment]
Yes, I received an email and will update the source to https://gitlab.com/sorairolake/qrtool later today.

**Comment by philiptaron** [comment]
I've opened #334670 to resolve this issue.

**Comment by sorairolake** [comment]
Hi,

The flag has been removed from my account a few hours ago, so this change can be reverted.
