### ISSUE TITLE
Package request: window.h

### ISSUE THREAD

**Issue by ahmedalqaisi000** [NixOS/nixpkgs#333380]
**Project description**

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TanvirOnGH** [comment]
@ahmedalqaisi000 you haven't provided any source to the package

**Comment by quantenzitrone** [comment]
metadata is missing
