### ISSUE TITLE
Update request: clolcat 1.1 → lolcat-c 1.5

### ISSUE THREAD

**Issue by SpidFightFR** [NixOS/nixpkgs#333577]
- Package name: [clolcat 1.1](https://github.com/IchMageBaume/clolcat/releases/tag/1.1)
- Latest released version: [lolcat-c 1.5](https://github.com/jaseg/lolcat/releases/tag/v1.5)

- Current version on the unstable channel: [clolcat 1.1](https://github.com/IchMageBaume/clolcat/releases/tag/1.1)
- Current version on the stable/release channel: [clolcat 1.1](https://github.com/IchMageBaume/clolcat/releases/tag/1.1)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
Hey @felipeqq2  :wave: 

-----

Note for maintainers: Please tag this issue in your PR.
---

Note regarding this issue: I recommend switching from clolcat to lolcat(-c) as the later one is still updated as of today, in comparison of the first one that saw it's last update in 2021.
Thus, the new one fixes a lot of issues, notably, an issue when fastfetch is thrown into lolcat-c.
This update shouldn't be hard to make. As for the name perhaps it should be better to change it, or make a new package altogether ?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by felipeqq2** [comment]
Hey @SpidFightFR! As this is a new package, I don't think it's appropriate to just update `clolcat` to `lolcat-c`. We can add a new package (as noted in your comment), and _possibly_ remove `clolcat`.

Please note that:

1. There is an open PR to add `lolcat-c` to nixpkgs (#225482).
2. There were some discussions on the existence of multiple lolcats (https://github.com/NixOS/nixpkgs/issues/258479#issuecomment-1742486263).

**Comment by felipeqq2** [comment]
Is the issue with fastfetch present in `clolcat`, or just oldest versions of `lolcat-c`?

**Comment by SpidFightFR** [comment]
> Hey @SpidFightFR! As this is a different package, I don't think it's appropriate to just update `clolcat` to `lolcat-c`. We can add a new package (as noted in your comment), and _possibly_ remove `clolcat`.
> 
> Please note that:
> 
> 1. There is an open PR to add `lolcat-c` to nixpkgs (#225482).
> 2. There were some discussions on the existence of multiple lolcats (https://github.com/NixOS/nixpkgs/issues/258479#issuecomment-1742486263).

Hey thanks for your answer, and the links!

I subbed to the first pr, although it seems stalled...
Should i close this issue in the meantime?

**Comment by SpidFightFR** [comment]
> Is the issue with fastfetch present in `clolcat`, or just oldest versions of `lolcat-c`?

Hey i'm really sorry but i totally missed that question.

I hope you're doing great.

Indeed this bug occurred in clolcat and older versions of lolcat-c but it got fixed in v1.5.

This is why i was interested in the package in the first place.

**Comment by felipeqq2** [comment]
Hey @SpidFightFR !

Thanks for your answer (I also forgot about this issue...). I honestly don't know how to deal with this, and will ping the matrix chat for more input.

Reporting this bug to upstream is also a possibility, though I don't think it'll be fixed.

**Comment by felipeqq2** [comment]
> `lolcat-c` isn't a fork of `clolcat`, right? if they're just totally separate packages, then the GH issue seems misplaced, should be closed. [...]

I'll be closing this issue. If you want, you can update the aforementioned PR to add `lolcat-c` and ask for a review, based on the fact that it does fix a `clolcat` bug.
