### ISSUE TITLE
arbtt doesn't build on unstable

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#33363]
## Issue description
arbtt package doesn't build with `Encountered missing dependencies: time >=1.1 && <1.8`, and time's version is 1.8.3. It seems pretty obvious to fix, but I don't know anything about haskell and I'm not familiar with the structure of hackage-packages.nix to create anithing other than a dirty fix.

### Steps to reproduce
`nix-env -iA nixos.haskellPackages.arbtt` or enable the service on  310ad43 or nixpkgs-unstable.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by michaelpj** [comment]
I ran into this yesterday. The issues is with the `bytestring-progress` dep. I raised https://github.com/acw/bytestring-progress/issues/7 and the author has fixed it, so hopefully this will sort itself out with the next hackage update.

**Comment by iblech** [comment]
Thanks, @michaelpj! I'm curious, did you also notice the problem about the screen saver library? I ran into this problem after locally fixing the issue with the bytestring-progress package, see #33375.

**Comment by michaelpj** [comment]
Drat, no. Hm, I thought I got it to build locally after my fix, but perhaps not. Not sure quite what to do about that.

**Comment by rvl** [comment]
Not sure yet why this broke but...

It's possible to work around this in `configuration-nix.nix`

```
  X11 = overrideCabal super.X11 (drv: {
    librarySystemDepends = drv.librarySystemDepends ++ [ pkgs.xorg.libXScrnSaver ];
  });
```

And I have made a PR on cabal2nix for this.

**Comment by iblech** [comment]
Thanks! (Especially for pointing me to `PostProcess.hs`, I didn't know that before.)

So we just have to wait for your pull request to be merged. :-)

**Comment by rvl** [comment]
@iblech I would add an override for now because there a few steps before the fix will appear in nixos-unstable -- 1. PR merged, 2.the regular update with hackage2nix, 3. channel update.
