### ISSUE TITLE
netdata: All python plugins broken

### ISSUE THREAD

**Issue by kevlar1818** [NixOS/nixpkgs#33366]
## Issue description

In NixOS, netdata fails to start the python script that runs all of its python plugins. This completely breaks all [40+ python plugins](https://github.com/firehol/netdata/tree/master/python.d) netdata provides.

See also: #32059 

### Steps to reproduce

* Enable the netdata service and rebuild the NixOS configuration. 
* Check netdata's log for the failure

    `grep ERROR /var/log/netdata/error.log`

* Notice a line similar to:

    `/nix/store/i0grak2af5vn06x7hmby81n1jjp1mx96-netdata-1.9.0/libexec/netdata/plugins.d/python.d.plugin: line 3: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found`

* A visual inspection of the netdata Web UI confirms there are no functioning python plugins.

**Note:** I have already tried adding `python` to the netdata `buildInputs`. This has not seemed to help.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.10, NixOS, 18.03.git.c98eb9e (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124007.4fe3297686b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
You might want to add it to [`path`](https://nixos.org/nixos/options.html#systemd.services.%3Cname%3E.path) attribute of the [systemd service](https://github.com/NixOS/nixpkgs/blob/abcb639df1682cbf65a007174b8be78cb6428d52/nixos/modules/services/monitoring/netdata.nix#L49-L67). Or even better, patch the [plugin loader](https://github.com/firehol/netdata/blob/c9f57acfc98aba2a660522c1e35412706a181dba/plugins.d/python.d.plugin#L2-L3) to use python:

```diff
--- a/plugins.d/python.d.plugin
+++ b/plugins.d/python.d.plugin
@@ -1,6 +1,4 @@
-#!/usr/bin/env bash
-'''':; exec "$(command -v python || command -v python3 || command -v python2 ||
-echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
+#!/usr/bin/env python3
 
 # -*- coding: utf-8 -*-
 # Description:
```

**Comment by kevlar1818** [comment]
@jtojnar Thanks for the advice. I'll give these a shot later today.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/50459

**Comment by Mic92** [comment]
I also backported it.

**Comment by Mic92** [comment]
I just noticed I also forgot to add https://github.com/Mic92/dotfiles/blob/master/nixos/vms/modules/netdata.nix#L78

**Comment by Mic92** [comment]
This one makes it finally work: https://github.com/NixOS/nixpkgs/pull/50509
