### ISSUE TITLE
Build failure: taskwarrior3

### ISSUE THREAD

**Issue by Buttars** [NixOS/nixpkgs#333777]
### Steps To Reproduce

1. nix-shell -p taskwarrior3

### Build log
https://gist.github.com/Buttars/b524dadd042c4ea1a81c2c61a7b2773b

### Notify maintainers

@marcweber @oxalica @mlaradji

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[~cf/nix-config]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.35, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Try updating to the latest `nixos-unstable` release, which has the fix from https://github.com/NixOS/nixpkgs/pull/331377
