### ISSUE TITLE
runInLinuxVM broken on unstable

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#33378]
## Issue description

Can't use runInLinuxVM?

### Steps to reproduce

```
nix build '(with import (fetchTarball channel:nixos-unstable) {}; vmTools.runInLinuxVM hello)'
builder for '/nix/store/7amq4whfdhr71skwl3310h90j1c0jmwr-hello-2.10.drv' failed with exit code 1; last 5 log lines:
  WARNING: Image format was not specified for '/dev/null' and probing guessed raw.
           Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
           Specify the 'raw' format explicitly to remove the restrictions.
  qemu-system-x86_64: -drive file=/dev/null,if=virtio,cache=unsafe,werror=report: Failed to get "consistent read" lock
  Is another process using the image?
[0 built (1 failed)]
error: build of '/nix/store/7amq4whfdhr71skwl3310h90j1c0jmwr-hello-2.10.drv' failed
```

compared to:

```
$ nix build '(with import (fetchTarball channel:nixos-17.09) {}; vmTools.runInLinuxVM hello)'
....
$ ls -l result
lrwxrwxrwx 1 will users 54 Jan  3 10:58 result -> /nix/store/0b8p7nsx45fhcd1kcnanfr8c79qzsbn3-hello-2.10
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12dtz5844_776d853`
 - channels(will): `"allvm, unstable"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dezgeg** [comment]
Yeah, I think QEMU on master/unstable doesn't like `/dev/null` passed as a device. Or maybe it happened if `/dev/null` was passed multiple times.

**Comment by dtzWill** [comment]
Hmm, okay.  Could it be related to host OS? I wouldn't expect so but some other machines don't have this problem and they're running 17.09 instead...

**Comment by dezgeg** [comment]
Could be. Maybe this '"consistent read" lock' what QEMU uses is only supported on new kernels?
