### ISSUE TITLE
autoPatchelfHook adds incorrect rpath dependency on packaged libc outputs

### ISSUE THREAD

**Issue by squalus** [NixOS/nixpkgs#333710]
### Describe the bug
The `osquery.toolchain` package contains compiler toolchain binaries (like `clang`) and libc libraries to be used by the compiler outputs.  When `autoPatchelfHook` is run on the package, it incorrectly adds the internal libc directory to the rpath of the compiler binaries. This causes the compiler binaries to break with an error message like this:

```
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
```

This problem was introduced in https://github.com/NixOS/nixpkgs/pull/307068 / https://github.com/NixOS/nixpkgs/commit/80be92660efcdacbaae1afd1d5d46c88968956ee.

This was done because the systemd package wanted to use `autoPatchelfHook` to add `.note.dlopen` dependencies to its rpath. But using `autoPatchelfHook` to do this had an undesired side effect of removing glibc from the rpath (for a reason I don't yet understand). So `autoPatchelfHook`s previous behavior to ignore libc dependencies was changed.

### Potential solutions

1. Add a flag to autoPatchelfHook telling it to leave libc in the rpath if it's found. Enable this only on systemd.
2. Revert the libc change to autoPatchelfHook altogether, and instead modify findLibs and make-initrd-ng to automatically check libc.

Either solution would restore the old libc behavior of autoPatchelfHook for everyone else. The former would then add different code for systemd, and the latter would change a couple other programs to account for lacking this new behavior

@ElvishJerricco @flokli

**Comment by ElvishJerricco** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/332617
