### ISSUE TITLE
Package request: streamcontroller

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#333746]
**Project description**

> The Linux app for the [Elgato Stream Deck](https://www.elgato.com/de/de/s/welcome-to-stream-deck).

As discussed in https://github.com/NixOS/nixpkgs/issues/311673 `streamdeck-ui` is now EOL and the dev's have moved their effort to `streamcontroller`.

As per the [docs](https://streamcontroller.github.io/docs/latest/common_problems/) in order for it to work specific [udev rules](https://raw.githubusercontent.com/StreamController/StreamController/main/udev.rules) need to be set up. We can probably do something similar to what we do for the `streamdeck-ui` expression:

https://github.com/NixOS/nixpkgs/blob/21cc704b5e918c5fbf4f9fff22b4ac2681706d90/pkgs/applications/misc/streamdeck-ui/default.nix#L46-L62

**Metadata**

* homepage URL: https://core447.com/
* source URL: https://github.com/StreamController/StreamController
* license: GPL3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sifmelcara** [comment]
For people who subscribed to this issue: I opened #335545 to add streamcontroller
