### ISSUE TITLE
bluetooth.target is enabled even hardware.bluetooth.enable is false

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#333885]
### Describe the bug
bluetooth.target is enabled even hardware.bluetooth.enable is false

### Steps To Reproduce
```
[kcynk@87a9f8f3b6a231:~] grep -i bluetooth /etc/nixos/configuration.nix
  hardware.bluetooth.enable = false;
  
[kcynk@87a9f8f3b6a231:~] systemctl status bluetooth.target
● bluetooth.target - Bluetooth Support
     Loaded: loaded (/etc/systemd/system/bluetooth.target; linked; preset: enabled)
     Active: active since Sun 2024-08-11 10:18:55 CEST; 40min ago
 Invocation: b26809f8f7b546499693a09ff1de0b28
       Docs: man:systemd.special(7)
```

### Screenshots
![Screenshot from 2024-08-11 11-03-58](https://github.com/user-attachments/assets/ef0511e7-a018-485c-9d67-963147aefa58)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[kcynk@87a9f8f3b6a231:~] sudo nix-shell -p nix-info --run "nix-info -m"
Place your finger on the fingerprint reader
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux
copying path '/nix/store/1r32fki5z5ivgaikgh8pq0r6vz3b0jpj-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11pre664135.5e0ca22929f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ck3d** [comment]
The bluetooth.target is part of systemd:
https://github.com/systemd/systemd/blob/main/units/bluetooth.target

And udev depends on this target:
https://github.com/systemd/systemd/blob/main/rules.d/99-systemd.rules.in#L60

The target should be installed to avoid unwanted side effects.

**Comment by KCynk** [comment]
@ck3d @dotlambda 
Thanks for explanation, but there is also one attribute inside setting of bluetooth.target

[Unit]
Description=Bluetooth Support
Documentation=man:systemd.special(7)
**StopWhenUnneeded=yes**

StopWhenUnneeded=Takes a boolean argument. If true, this unit will be stopped when it is no longer used. Note that, in order to minimize the work to be executed, systemd will not stop units by default unless they are conflicting with other units, or the user explicitly requested their shut down. If this option is set, a unit will be automatically cleaned up if no other active unit requires it. Defaults to false.

```
[kcynk@87a9f8f3b6a231:~] systemctl list-dependencies bluetooth.target --all --reverse
bluetooth.target
● └─sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d10-1\x2d10:1.0-bluetooth-hci0.device
[kcynk@87a9f8f3b6a231:~]
```
From my understanding bluetooth.target is active because sys-device is active but from my point of view should be disabled because we disable it by hardware option  
```
  hardware.bluetooth.enable = false;
```

**Comment by ck3d** [comment]
hardware.bluetooth.enable enables user space services and do not alter the udev configuration. You have a bluetooth device, which fits to following udev rude:
https://github.com/systemd/systemd/blob/main/rules.d/99-systemd.rules.in#L60

This leads a to device unit file, which depends on bluetooth.target.

I do not see, why we should patch a udev rule, which is installed on all distributions. Any patch can cause side effects, which leads to possible other problems.
