### ISSUE TITLE
Failing to boot on Raspberry Pi 3 from nixos-sd-image-24.11pre664135.5e0ca22929f3-aarch64-linux.img.zst

### ISSUE THREAD

**Issue by edeetee** [NixOS/nixpkgs#333865]
### Describe the bug
Raspberry Pi 3 is not completing boot from nixos-sd-image-24.11pre664135.5e0ca22929f3-aarch64-linux.img.zst.
It shows the rainbow boot screen.

### Steps To Reproduce
1. Download and extract the aarch64 image
2. Copy to sdcard using `dd if=nixos-sd-image-24.11pre664135.5e0ca22929f3-aarch64-linux.img of=/dev/disk4`
3. Start Raspberry Pi

### Expected behavior
Pi should boot

### Additional context
My pi is booting fine with Raspbian OS.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by timschumi** [comment]
As an additional datapoint, the latest stable NixOS image (24.05.3787) works fine. I'll try and bisect down to when it broke.

**Comment by timschumi** [comment]
Broken with a1717b84563fcad9230c78e52618b06dd38f35ff.

**Comment by timschumi** [comment]
Broken between U-Boot 2024.07-rc2 and U-Boot 2024.07-rc3. Checking [this](https://github.com/u-boot/u-boot/compare/v2024.07-rc2...v2024.07-rc3) of commits next, as well as the latest release candidate.

**Comment by timschumi** [comment]
Bisected down to u-boot/u-boot@713c9d3f941407221abbf09916e53bb7d8f88783. A fix for NixOS is proposed in #333947, testing would be much appreciated (especially on other hardware).

**Comment by bobrippling** [comment]
As further data point, I believe this bricked my rpi4 nix install - did you ever see an issue about a flattened device tree?

**Comment by K900** [comment]
Please elaborate.

**Comment by timschumi** [comment]
A Raspberry Pi 4B booted just fine for me without issue, at least prior to my proposed change. I strongly doubt that the fix would affect other hardware, but I'm building a disk image just as I'm writing this to make sure.

**Comment by bobrippling** [comment]
> A Raspberry Pi 4B booted just fine for me without issue, at least prior to my proposed change. I strongly doubt that the fix would affect other hardware, but I'm building a disk image just as I'm writing this to make sure.

Ah yes - I wasn't very clear, I'm curious about if you saw any other error than the rainbow screen

----

> Please elaborate.

I see the boot process making it to u-boot, which then bails out with:

```
ERROR: Did not find a cmdline Flattened Device Tree
```
after having loaded the kernel and initrd.

This error happens for each kernel I have installed, then u-boot falls back to a network boot (which I don't have setup). Unfortunately I didn't see this before as I boot the pi headlessly, so it kept falling back to an old, good kernel, until that kernel got dropped by an update

**Comment by K900** [comment]
This probably means our kernel is too big, again, and we need to do #174762 again, again.

**Comment by bobrippling** [comment]
Gotya, thanks for the issue link. I think in that case I'll go with the UEFI boot option if this could be problematic in the future for u-boot

**Comment by bobrippling** [comment]
As a note - I flashed a fresh nixos-sdcard image (`24.05.1503.752c634c09ce-aarch64`) and it boots fine. Could it be the firmware on my old install was never updated by nix? I'd attempted to copy across uboot and co with the same result/error

**Comment by timschumi** [comment]
NixOS does not update the firmware by default. However, that should mean that both U-Boot and the DTBs remained untouched.

**Comment by bobrippling** [comment]
> NixOS does not update the firmware by default. However, that should mean that both U-Boot and the DTBs remained untouched.

That matches up with what I found, I guess it must've been the kernel changing, and needing a more recent DTB

> This probably means our kernel is too big, again, and we need to do #174762 again, again.

About this - is there a way to find out if the latest image failed to boot and that u-boot fell back to a backup?
