### ISSUE TITLE
ssh client: remove DSA key support

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#33381]
## Issue description

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/ssh.nix#L192-L194

ssh-dss was deprecated in 2015. Server support was removed in 17.03. It might be time to remove them client-side, and also from examples.

**Comment by aneeshusa** [comment]
cc me as openssh maintainer to look at this later

**Comment by vcunat** [comment]
Probably fixed by update #48784

**Comment by alyssais** [comment]
This is still being set through the NixOS option default.
