### ISSUE TITLE
Firefox (Librewolf) ignores the wrapper settings

### ISSUE THREAD

**Issue by acid-bong** [NixOS/nixpkgs#333873]
### Describe the bug
In my NixOS config, I disabled `speech-dispatcher` integration, thus removing it from my system closure. Last Sunday I updated and built my system, but `nvd` showed that `speech-dispatcher` is back in the closure. No settings were changed.

### Steps To Reproduce
Config in question: https://codeberg.org/acidbong/nixos/src/branch/master/modules/desktop/default.nix#L106-L112

1. build the system from the provided config
2. update the inputs
3. build again (rename the old `result` link, so it doesn't get overwritten)
4. compare the outputs with `nvd`

### Expected behavior
`speech-dispatcher` shouldn't be back in the closure.

### Extra info
Possible culprit: https://github.com/NixOS/nixpkgs/commit/8e7a0982431b8ad99070695221bdb2d317e08030#diff-3c9ade456e415bf908ea34b59cd484eee8e408773f651677b8f2eeeaa7de24f1

### Notify maintainers
- Librewolf: @dotlambda @squalus 
- Firefox wrapper: @mweinelt @lovesegfault 
- @K900 in case

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.42, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
You probably need to set `services.speechd.enable = false;`, it's enabled by default on graphical setups now.

**Comment by acid-bong** [comment]
Got it, thanks a lot. Sorry to the rest of the folks for pinging
