### ISSUE TITLE
glibPreFixupPhase is not run when glib appears after hicolor_icon_theme in dependences

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#33388]
## Issue description

I am writing a derivation for a new package where `hicolor_icon_theme` is in `nativeBuildInputs` and `gtk3` (which depends on `glib`) is on `buildInputs`. With that `preFixupPhases` mentions only `hicolorPreFixupPhase`, and `glibPreFixupPhase` is just missing.

As a consequence the glib schemas for the application is not taken into account by `wrapGAppsHook` and execution of the application fails.

I have noticed that `glibPreFixupPhase` only appears in `preFixupPhases` if the `hicolor_icon_theme` dependence appears after the `gtk3` dependence in the derivation.

It may be related to how the functions are added to `preFixupPhases`:

- [for `glib`](https://github.com/NixOS/nixpkgs/blob/d2e8c20911161ea06602d99a413437304b01b598/pkgs/development/libraries/glib/setup-hook.sh#L25):
``` bash
preFixupPhases+=(glibPreFixupPhase)
```
- [for `hicolor_icon_theme`](https://github.com/NixOS/nixpkgs/blob/d2e8c20911161ea06602d99a413437304b01b598/pkgs/data/icons/hicolor-icon-theme/setup-hook.sh#L20):
``` bash
preFixupPhases="$preFixupPhases hicolorPreFixupPhase"
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.10, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by romildo** [comment]
Changing the `glib` setup hook to use the same style used in the `hicolor_icon_theme` setup hook fixes the issue for me.
``` bash
preFixupPhases="$preFixupPhases glibPreFixupPhase"
```

**Comment by joachifm** [comment]
Looks like the PR to fix this has been merged
