### ISSUE TITLE
Documentation for how to add to rubyLibs using overriding

### ISSUE THREAD

**Issue by joelteon** [NixOS/nixpkgs#3339]
I'd like to maintain a list of ruby gems of specific versions for some of my projects, but I don't want to modify my nixpkgs. Unfortunately I can't figure out how to modify the packages in rubyLibs. I can override individual packages but, unlike (say) haskellPackages, I can't modify the set itself to add new members. `haskellPackages.override` takes an `extension` argument, but `rubyLibs.override` doesn't do the same, and I'm not clever enough to figure out why; it seems that I can only override the arguments that rubyLibs was called with (stdenv, fetchurl, and so on).

Help!

**Comment by benley** [comment]
that became  #4677 which is now merged, so this bug can probably be closed.

**Comment by iElectric** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/issues/5985
