### ISSUE TITLE
Build failure: fprintd

### ISSUE THREAD

**Issue by philipwilk** [NixOS/nixpkgs#333946]
### Steps To Reproduce

1. build fprintd 1.94.3

### Build log

https://gist.github.com/philipwilk/f0267008a77c47e373d53ba80dd6b4c7

### Additional context
Fails in tests

### Notify maintainers

@abbradar 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[philip@nixos-thinkcentre-tiny:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.0, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/store/afawjm6nv8m5aagkcqxlxgrr5qpyh6cm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Built successfully on my machine on both current master (`25e9685b9aaf0ea1b3654a1909711399a3b0020f`) and `68c9ed8bbed9dfce253cc91560bf9043297ef2fe`.
But your build and 2 builds on hydra in the past month failed on same test:
https://hydra.nixos.org/build/268452290
https://hydra.nixos.org/build/264762179

Seems to be this issue:
https://gitlab.freedesktop.org/libfprint/fprintd/-/issues/129
and `test_removal_during_enroll` is just flaky.

**Comment by philipwilk** [comment]
Is it possible for us to skip this specific test? I've had fprintd fail to build multiple times because of flakey tests and it's getting quite annoying.

**Comment by ghpzin** [comment]
As far as I know not possible without patching out that test or skipping full test suite:
https://github.com/mesonbuild/meson/issues/6999
But considering how frequent these are it may be a time for patching it out.
