### ISSUE TITLE
stdenv.isNixos

### ISSUE THREAD

**Issue by RAVENz46** [NixOS/nixpkgs#333977]
**Is your feature request related to a problem? Please describe.**

I am currently rewriting my config file to make it more modular.
I plan to share modules not only with nixos, but also with other linux distributions, darwin, etc., but in doing so, there are some modules that are used or work only on certain platforms.
Basically, we can use `stdenv.isLinux`, etc., but there does not seem to be a good way to do this if we want to use nixos only.
It seems puzzling that there is no way to specify nixos when such parameters are currently available. 

```console
nix-repl> stdenv.hostPlatform
{ aesSupport = false; avx2Support = false; avx512Support = false; avxSupport = false; canExecute = «lambda @ /nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source/lib/systems/default.nix:78:20»; config = "x86_64-unknown-linux-gnu"; darwinArch = "x86_64"; darwinMinVersion = "10.12"; darwinMinVersionVariable = null; darwinPlatform = null; darwinSdkVersion = "10.12"; efiArch = "x64"; emulator = «lambda @ /nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source/lib/systems/default.nix:299:20»; emulatorAvailable = «lambda @ /nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source/lib/systems/default.nix:297:29»; extensions = { ... }; fma4Support = false; fmaSupport = false; gcc = { ... }; hasSharedLibraries = true; is32bit = false; is64bit = true; isAarch = false; isAarch32 = false; isAarch64 = false; isAbiElfv2 = false; isAlpha = false; isAndroid = false; isArmv7 = false; isAvr = false; isBSD = false; isBigEndian = false; isCompatible = «lambda @ /nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source/lib/systems/default.nix:82:22»; isCygwin = false; isDarwin = false; isEfi = true; isElf = true; isFreeBSD = false; isGenode = false; isGhcjs = false; isGnu = true; isILP32 = false; isJavaScript = false; isLinux = true; isLittleEndian = true; isLoongArch64 = false; isM68k = false; isMacOS = false; isMacho = false; isMicroBlaze = false; isMinGW = false; isMips = false; isMips32 = false; isMips64 = false; isMips64n32 = false; isMips64n64 = false; isMmix = false; isMsp430 = false; isMusl = false; isNetBSD = false; isNone = false; isOpenBSD = false; isOr1k = false; isPower = false; isPower64 = false; isRedox = false; isRiscV = false; isRiscV32 = false; isRiscV64 = false; isRx = false; isS390 = false; isS390x = false; isSparc = false; isSparc64 = false; isStatic = false; isSunOS = false; isUClibc = false; isUnix = true; isVc4 = false; isWasi = false; isWasm = false; isWindows = false; isi686 = false; isiOS = false; isx86 = true; isx86_32 = false; isx86_64 = true; libDir = "lib64"; libc = "glibc"; linker = "bfd"; linux-kernel = { ... }; linuxArch = "x86_64"; parsed = { ... }; qemuArch = "x86_64"; rust = { ... }; rustc = { ... }; sse3Support = false; sse4_1Support = false; sse4_2Support = false; sse4_aSupport = false; ssse3Support = false; system = "x86_64-linux"; ubootArch = "x86_64"; uname = { ... }; useAndroidPrebuilt = false; useLLVM = false; useiOSPrebuilt = false; }
```

**Describe the solution you'd like**

If it is not technically difficult, I would like to see this feature implemented.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
> there are some modules that are used or work only on certain platforms.

Not sure if you meant _modules_ here, but if you do, you can declare a module [class](https://nixos.org/manual/nixpkgs/stable/index.html#module-system-lib-evalModules-param-class) as follows:

```nix
{
  _class = "nixos";
  options = <...>;
  config = <...>;
}
```

If you meant packages (perhaps because you mentioned `stdenv.isLinux`): it's generally regarded as a good thing that the same package set runs on NixOS as well as on Debian, Fedora, etc.
If we were to add a Nixpkgs `config` item to distinguish NixOS, we'd have to give up on this property, and potentially increase the number of hydra.nixos.org builds significantly to build separate variations for NixOS vs other distros.

**Comment by RAVENz46** [comment]
Sorry for my bad English.
I didn't know `_class` argument, it will help me, Thanks!
However `_class` seems to be applied entire modules and I wanna do like this.
It's **NOT** my purpose something like `meta.platforms = lib.platforms.nixos` in packages' derivations.

```nix
{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.example;
in
{
  options = <...>;
  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      #somepackages
    ] ++ optionals stdenv.isNixos [
      #nixosOnlyPackages
    ];

    programs.nixosOnly = pkgs.stdenv.isNixos;
  };
}

**Comment by RAVENz46** [comment]
@eclairevoyant and @TanvirOnGH don't like so I gave up and make my own option instead.
I'm not Nix expert and IDK why is it a bad idea but I don't care it anymore.

**Comment by RAVENz46** [comment]
#96715
#94937

**Comment by RAVENz46** [comment]
@nbraud  Sorry, I don't know cause I'm not a nix expert.
