### ISSUE TITLE
Update request: Heroic 2.14.1 → 2.15.1

### ISSUE THREAD

**Issue by JonBoyleCoding** [NixOS/nixpkgs#333956]
- Package name: heroic
- Latest released version: 2.15.1

- Current version on the unstable channel: 2.14.1
- Current version on the stable/release channel: 2.14.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aidalgol 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aidalgol** [comment]
Need to wait for https://github.com/NixOS/nixpkgs/pull/333907 to be merged, because upstream depends on Electron 31, but the latest currently in nixpkgs is 30.

**Comment by s0me1newithhand7s** [comment]
> Need to wait for #333907 to be merged, because upstream depends on Electron 31, but the latest currently in nixpkgs is 30.

you can make draft PR and wait :D

**Comment by Henry-Hiles** [comment]
Also does UMU need to be packaged for this release?

**Comment by aidalgol** [comment]
Actually, given that [UMU provides a flake](https://github.com/Open-Wine-Components/umu-launcher#nixos), and Heroic can download a working version, just without the latest fixes, I am opting to *not* package UMU in nixpkgs.
