### ISSUE TITLE
signal-desktop beta build is broken

### ISSUE THREAD

**Issue by ixmatus** [NixOS/nixpkgs#33401]
## Issue description
The `signal-desktop` beta derivation depends on a pre-built deb package that no longer exists.

## Technical details

https://hydra.nixos.org/build/66165023

**Comment by ixmatus** [comment]
CC: @benley (I don't have the ability to assign this)

**Comment by iblech** [comment]
Hey @benley, I just needed the fix for myself and therefore figured I could as well push it. Hope you don't mind.

**Comment by benley** [comment]
I don't mind at all! Thank you for doing that.
