### ISSUE TITLE
Chromium suddenly installed on system update

### ISSUE THREAD

**Issue by Familex** [NixOS/nixpkgs#334008]
### Describe the bug
I don't have chromium in my system flake, but on recent update it appeared in system path.

I tried to bisect a specific commit: in ad80525b035676e0e39e4372cae2bf6f63f4f877 it not present, but in d4961abbcab3b72fa30b0f3ee0e2e8c858a8f63d it does.
But it didn't make sense to me, because it is python library update.

I inspected it with `nix-tree`, and it doesn't seem to be a dependency.

### Steps To Reproduce
- `nix flake update --override-input nixpkgs github:nixos/nixpkgs/d4961abbcab3`
- `sudo nixos-rebuild test`

### Expected behavior
Should not.

### Screenshots
Here is I switch between adjacent commits and chromium appears.

![image](https://github.com/user-attachments/assets/a7bed5d8-4fc7-4d20-bb44-865286f33eeb)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.11 (Vicuna), 24.11.20240809.d4961ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/nix/store/znxkpcwydayfhscc8liwf35hhzpk61hx-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
It's due to #333240 which means you have chromium enabled in your config

**Comment by Familex** [comment]
Ok, I found it (by directly disabling option), it was stylix, it has `programs.chromium.enable = true` by default... (https://github.com/danth/stylix/blob/master/modules/chromium/nixos.nix)

**Comment by Familex** [comment]
@eclairevoyant thanks for help!

**Comment by emilylange** [comment]
The change been reverted in #334726 and will reach the `unstable` channel in a few days.

Refer to #334726 and related PRs for why this has been reverted.
