### ISSUE TITLE
Build failure:  'lisp-modules' in the nixpkgs

### ISSUE THREAD

**Issue by NoidoDev** [NixOS/nixpkgs#334006]
### Steps To Reproduce

1. build nixos-rebuild switch --upgrade
2. unpacking channels...
3. building Nix...
4. building the system configuration...

### Build log

```
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Lisp packages have been redesigned. See 'lisp-modules' in the nixpkgs manual.
```

### Additional context

I didn't upgrade to a new version for a while, because I didn't know how. I wondered why I don't get new upgrades, but didn't find the information. I just added the 24.05 channel recently and tried to upgrade. I've looked up  'lisp-modules' in the nixpkgs but don't know how this would help. 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
these 14 paths will be fetched (57.31 MiB download, 261.94 MiB unpacked):
  /nix/store/jlw40q2bndc4db7iqzn6r2sz2r7kj4h4-binutils-2.41
  /nix/store/kf0i9b8a1xcw4qr7d534gcjgfwbkc1xk-binutils-2.41-lib
  /nix/store/xcind1c9z66qg6g8xvj8ckz8dnp6r80q-binutils-wrapper-2.41
  /nix/store/3ji6m6fkahmkc7jnl5av2d9c1ln04wij-expand-response-params
  /nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0
  /nix/store/q6afjcz9h6ybcrai8w4z4k6ld7yqi9nd-gcc-wrapper-13.2.0
  /nix/store/rzs2mn1lv3dsiyilygfz9vv1p8r36jvn-glibc-2.39-52-dev
  /nix/store/6prgv8896ga5bpf7qj24h3zlj0hc1101-gmp-6.3.0
  /nix/store/arihzc3ifwwfzkz1b05saxlgky1wpyip-isl-0.20
  /nix/store/m7k7c75pjg7wkqkwdl5z23g09cl14dk5-libmpc-1.3.1
  /nix/store/xcrmfzp8ldq0zf5akk0yn3wr4b02wfvf-linux-headers-6.7
  /nix/store/zygg9zndlqljyr7x2hgk3rqw4167ig04-mpfr-4.2.1
  /nix/store/qmqfklivzcv14gn4ydmshzza8fp7faaj-nix-info
  /nix/store/61h5fgmxl3biljwbhxvr55qkxsp44yla-stdenv-linux
copying path '/nix/store/qmqfklivzcv14gn4ydmshzza8fp7faaj-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/3ji6m6fkahmkc7jnl5av2d9c1ln04wij-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/6prgv8896ga5bpf7qj24h3zlj0hc1101-gmp-6.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/xcrmfzp8ldq0zf5akk0yn3wr4b02wfvf-linux-headers-6.7' from 'https://cache.nixos.org'...
copying path '/nix/store/kf0i9b8a1xcw4qr7d534gcjgfwbkc1xk-binutils-2.41-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/zygg9zndlqljyr7x2hgk3rqw4167ig04-mpfr-4.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/arihzc3ifwwfzkz1b05saxlgky1wpyip-isl-0.20' from 'https://cache.nixos.org'...
copying path '/nix/store/jlw40q2bndc4db7iqzn6r2sz2r7kj4h4-binutils-2.41' from 'https://cache.nixos.org'...
copying path '/nix/store/m7k7c75pjg7wkqkwdl5z23g09cl14dk5-libmpc-1.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/rzs2mn1lv3dsiyilygfz9vv1p8r36jvn-glibc-2.39-52-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/xcind1c9z66qg6g8xvj8ckz8dnp6r80q-binutils-wrapper-2.41' from 'https://cache.nixos.org'...
copying path '/nix/store/q6afjcz9h6ybcrai8w4z4k6ld7yqi9nd-gcc-wrapper-13.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/61h5fgmxl3biljwbhxvr55qkxsp44yla-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.96, NixOS, 23.11 (Tapir), 23.11.7870.205fd4226592`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eclairevoyant** [comment]
Please share your config

**Comment by NoidoDev** [comment]
[configuration.nix.save.txt](https://github.com/user-attachments/files/16589904/configuration.nix.save.txt)
Okay, some details have been removed. But the error is not in the config. The reported error is outside.

**Comment by NoidoDev** [comment]
I think I resolved it myself by switching back to the old repository. I thought I didn't get updates there for a while, but now I do, and the error went away.

**Comment by NoidoDev** [comment]
I don't get upgrades with the channel of version 23, so I tried again, and still get the same error. I asked here now:
https://discourse.nixos.org/t/error-lisp-packages-have-been-redesigned/51204

**Comment by eclairevoyant** [comment]
Again, you need to share your config.

**Comment by 7c6f434c** [comment]
The reported error is outside due to the use of deprecated-before now-dropped old lisp module system, you probably have something using lispPackages or lispPackagesFor or lispPackagesNg in your config, and to translate it to `clisp.withPackages` (most probable replacement) there is a need to see what is being translated.

**Comment by NoidoDev** [comment]
Thanks, I was confused about it being a Nix issue, but I will try to deactivate all Lisp related packages and re-install them later.

**Comment by NoidoDev** [comment]
Thanks. It has been resolved. It had nothing to do with NixPKGS. Sorry for the fuss. 

I jumped from “error with Lisp” to the idea that this must be related to the OS userland itself, because I had this idea in the back of my head that it is written in Lisp. I know how Lisp looks like, so I know the nix-config isn’t Lisp, but I somehow thought it was used under the hood. Because I first wanted to use Guix.

Anyways. It was just some packages I needed to deactivate, now it works. It was most likely one of those:
#emacsPackages.sqlite
#lispPackages.sqlite
