### ISSUE TITLE
Private Per User Journals in `/var/log` have the wrong owners/permissions

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#3341]
I've recently tried out the systemd user instances via `systemctl --user` in order to manage user specific services and processes.

However upon trying to access user specific journald logs:

```
journalctl --user
```

Or

```
journalctl --user-unit=randomservice
```

It keeps coming back with: "No journal files were found."

I've checked that `/var/log/journal/67a1c96e3cc34c208ceb252d71cfab5d` contains 2 files: 

```
system.journal
user-1000.journal
```

However both are owned by root.

By running `sudo chown operator user-1000.journal`, I was able to then run `journalctl --user` and acquire my per user journal.

I think NixOS should be making sure that the per user journals are actually owned by the users, so they can actually access them.

**Comment by Profpatsch** [comment]
Since `journalctl --user` shows output, this has since been fixed. Close @jagajaga
