### ISSUE TITLE
Package request: opener

### ISSUE THREAD

**Issue by Tanvir1337x** [NixOS/nixpkgs#334106]
**Project description**

Open URL in your local web browser from the SSH-connected remote environment.

**Metadata**

* homepage URL: https://github.com/superbrothers/opener
* source URL: https://github.com/superbrothers/opener
* license: mit
* platforms: linux, darwin

**Comment by s0me1newithhand7s** [comment]
> `label:"6.topic: golang"`

i can't add topics - can you add it?
