### ISSUE TITLE
OpenCL "Clover" Mesa drivers not being picked up by tooling

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [NixOS/nixpkgs#334189]
### Describe the bug
For Clover-supported \(non-ROCm-supported\) hardware, `clinfo` isn't picking up on the drivers that `mesa.opencl` exposes.

### Steps To Reproduce
1. Install NixOS 24.05 on any system with a TeraScale 3 or older AMD GPU — that is, any system using the `radeon` driver
2. ```bash
   nix-shell -p clinfo mesa mesa.opencl strace
   ```
3. Observe that the necessary libraries **really have been built**:
   ```bash
   find ${buildInputs} \( -name 'libMesaOpenCL.so' -o -name 'pipe_*.so' \)
   ```
4. Observe that `clinfo` checks for these libraries *only* within `"/nix/store/…-ocl-icd-2.3.2/lib/"` — so fails to find the Clover drivers, resulting in 0 available OpenCL platforms:
   ```bash
   strace clinfo 2>&1 | grep -E '(libOpenCL.so|pipe_*.so|Number of platforms)'
   ```

### Expected behavior
I expected clinfo to correctly pick up the presence of these drivers, which are available in Ubuntu as ["mesa-opencl-icd"](https://packages.ubuntu.com/noble/amd64/mesa-opencl-icd/filelist) and are available in Arch as ["opencl-clover-mesa"](https://archlinux.org/packages/extra/x86_64/opencl-clover-mesa/#pkgfiles).

### Additional context
- https://github.com/NixOS/nixpkgs/issues/62933
- I do not currently have access to any GCN 1 or newer AMD GPU, so I cannot check whether [`rocmPackages.clr.icd`](https://github.com/NixOS/nixpkgs/blob/24.05/pkgs/development/rocm-modules/6/clr/default.nix#L157) would have resolved this error.
  * \(For good measure, I tried the "Steps to reproduce" again including that package anyway; it did not affect the results.\)
- My TeraScale 2 GPU *is* working with OpenGL, reporting renderer string `AMD TURKS (DRM 2.50.0 / 6.6.44, LLVM 17.0.6)`.

### Notify maintainers

@sbruder  
@Madouura  
@K900

### Metadata
```console
[lain@CNU352DG8J-nxo:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.3690.21cc704b5e91`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
How are you enabling the driver?

**Comment by JamesTheAwesomeDude** [comment]
> How are you enabling the driver?

The driver seemed to be enabled — at least well enough for OpenGL — incidentally by `services.desktopManager.plasma6.enable` at the OS-level.

The wiki did not suggest any other flags or options that might be needed for OpenCL. https://nixos.wiki/wiki/AMD_GPU

**Comment by K900** [comment]
You want `hardware.opengl.extraPackages = [ mesa.opencl ]`

**Comment by JamesTheAwesomeDude** [comment]
I see... after adding `hardware.opengl.extraPackages = [ pkgs.mesa.opencl ];` to my hardware configuration file and rebooting, `clinfo` is functioning!

-----

Why did this *not* work when the very same package was only included with my original `nix-shell` command? What's different about `nixos-rebuild`?

**Comment by K900** [comment]
The OpenCL loader is looking at a fixed location.

**Comment by JamesTheAwesomeDude** [comment]
I've added this to the wiki; the existing page says it's got a focus on GCN1 and newer GPUs, but there wasn't any existing page for AMD GPUs generally, or for OpenCL, or for the "radeon" driver.

https://nixos.wiki/wiki/AMD_GPU#Older_GPUs_.28TeraScale.29

**Comment by K900** [comment]
https://wiki.nixos.org/wiki/NixOS_Wiki is the official wiki.
