### ISSUE TITLE
Update request: swayimg 2.3 → 3.1

### ISSUE THREAD

**Issue by SymphonySimper** [NixOS/nixpkgs#334142]
- Package name: swayimg
- Latest released version: [3.1](https://github.com/artemsen/swayimg/releases/tag/v3.1)

- Current version on the unstable channel: 2.3
- Current version on the stable/release channel: 2.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@MatthewCroughan 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by idlip** [comment]
Can be closed by #337114
