### ISSUE TITLE
Meltdown and Spectre patches for NixOS

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#33414]
## Issue description
A quick skim of the commit log seems to indicate that these patches are not in NixOS 17.09. Can someone confirm/deny?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 17.09.2281.b4a0c011e81 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(vaibhavsagar): `"nixpkgs-unstable-18.03pre121255.45a85eaceb"`
 - channels(root): `"nixos-17.09.2356.cb751f9b1c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by grahamc** [comment]
The release-17.09 and unstable branches both have the updating the Latest kernel (4.14.11) 1e129a3f9934ae62b77475909f6812f2ac3ab51f / dd396efe68b66be8e0b252a875c64f98f4e312cb which I _believe_ does, include the KPTI / KAISER patches.

The nixos-17.09 channel has been updated to include the patch, but Unstable has not yet updated.

As far as I know, upstream 4.9 and 4.4 do not include these patches yet, and NixOS hasn't applied the patches either. If you'd like to help please do :)

**Comment by grahamc** [comment]
To be clear: You can get the patched kernel via:

```
boot.kernelPackages = pkgs.linuxPackages_latest;
```

**Comment by rnhmjoj** [comment]
The patch for meltdown is called KPTI and should have been merged in kernel 4.15rc6 and backported to 4.14.11, which is in nixpkgs since 1e129a3f9934ae62b77475909f6812f2ac3ab51f.

It seems there are no patches for spectre yet. No single patch will mitigate this attack anyway.

**Comment by rnhmjoj** [comment]
I think we should track the spectre patches as they are released.
Updates for [chromium](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca) and [Firefox](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/) should come soon.

**Comment by Ekleog** [comment]
https://twitter.com/olesovhcom/status/948886345547644928 and CESA-2018:0007 (for CentOS) appear to imply that there are microcode updates that are available for mitigating at least part of spectre, if I understand correctly?

**Comment by rnhmjoj** [comment]
Firefox updates: https://github.com/NixOS/nixpkgs/pull/33456

**Comment by edolstra** [comment]
Master and 17.09 now have updated 4.4, 4.9 and 4.14 kernels containing KPTI.

**Comment by edolstra** [comment]
Once the 17.09 channel updates, I'll generate new AMIs.

**Comment by fpletz** [comment]
I'm currently working on the microcode updates. Intel has not released updates yet but Red Hat has already released them.

**Comment by qrilka** [comment]
Any hint why `nixos-unstable` is still on commit from the 2nd of January?

**Comment by rnhmjoj** [comment]
@qrilka [Failing](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents) tests.

**Comment by grahamc** [comment]
nixos-17.09 and nixos-17.09-small now have KPTI patches on 4.4, 4.9, and 4.14.

**Comment by bendlas** [comment]
Users of chromium 63 (current stable) should enable the site isolation flag, until 64 is stable
https://support.google.com/faqs/answer/7622138#chrome

**Comment by concatime** [comment]
@fpletz Intel released the microcode. Take a look at https://downloadcenter.intel.com/download/27431/Linux-Processor-Microcode-Data-File.
I tried to apply manually, and realised that there is not `/lib/firmware`… lol

**Comment by vcunat** [comment]
Nixos-unstable now has the kernel updates, etc.  Microcode was just now updated on both branches: https://github.com/NixOS/nixpkgs/pull/33684

**Comment by aij** [comment]
I see the microcode update got cherry picked to nixos-17.09 too (ea1cf952861bbf03b3a4c29c4050a943dd73ffbc), but there is still nothing on 
nix-security-announce.

What's the expected timeline for security announcements?

**Comment by gnidorah** [comment]
Considering that these patches have impact on performance:
https://access.redhat.com/articles/3311301
https://twitter.com/grsecurity/status/947260475305213953
We may land linuxPackages_weak (reference to linuxPackages_hardened_copperhead :sweat_smile:) someday with all them disabled

**Comment by CMCDragonkai** [comment]
@gnidorah do those tunables work on NixOS as well?

**Comment by CMCDragonkai** [comment]
@gnidorah do those tunables work on NixOS as well?

**Comment by CMCDragonkai** [comment]
@gnidorah do those tunables work on NixOS as well?

**Comment by gnidorah** [comment]
@CMCDragonkai "nopti" should work, however Grsecurity states that it doesn't disable KPTI completely https://twitter.com/grsecurity/status/947260475305213953 Need to check that.
AFAIR other patches have not been mainlined yet (it's just some vendors like Red Hat applied them earlier), but should have similar knobs.

**Comment by falsifian** [comment]
Is KPTI disabled by default? It seems to be on my system (release-17.09)::

    james angel-nixos ~ $ dmesg|grep isolation
    [    0.000000] Kernel/User page tables isolation: disabled
    james angel-nixos ~ $ uname -r
    4.9.75

If this isn't just some quirk of my own setup, should we consider enabling it by default? I had assumed I was safe after just updating, until I decided to double-check.

**Comment by falsifian** [comment]
Er, sorry for the noise. I have an AMD CPU; I guess it's not needed.

**Comment by gnidorah** [comment]
NixOS landed kernels 4.9.77 and 4.14.14 which brought Spectre V2 mitigation (retpoline). However:

>  For full support you also need to be building the kernel with a newer GCC compiler containing -mindirect-branch=thunk-extern support. The GCC changes landed in GCC 8.0 yesterday and is in the process of potentially being back-ported to GCC 7.3.

**Comment by fpletz** [comment]
I've reverted the intel microcode update because Intel recommends to stop deployment of the updated microcode as it introduces unexpected system behaviour on many platforms.

See https://security-center.intel.com/advisory.aspx?intelid=INTEL-SA-00088&languageid=en-fr.

**Comment by concatime** [comment]
Dear intel.
