### ISSUE TITLE
linuxPackages.nvidia-x11 fails to compile for kernel 4.9.74

### ISSUE THREAD

**Issue by kierdavis** [NixOS/nixpkgs#33410]
## Issue description

Log when compiling:

```
  CC [M]  /tmp/nix-build-nvidia-x11-384.98-4.9.74.drv-0/kernel/nvidia-uvm/uvm8_va_block.o
/tmp/nix-build-nvidia-x11-384.98-4.9.74.drv-0/kernel/nvidia-uvm/uvm8_va_block.c:1:36: fatal error: linux/sched/task_stack.h: No such file or directory
 #include <linux/sched/task_stack.h>
                                    ^
compilation terminated.
```

My guess is that it's related to #33284.

### Steps to reproduce

`nix-build '<nixpkgs>' -A linuxPackages.nvidia_x11`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2378.af7e47921c4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.15`
 - channels(kier): `""`
 - channels(root): `"nixos-17.09.2600.0b30c1dd4c6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

- nixpkgs version: 0b30c1dd4c638e318957fc6a9198cf2429e38cb5
- `linuxPackages.kernel.version`: 4.9.74
- `linuxPackages.nvidia_x11.version`: 384.98

**Comment by yegortimoshenko** [comment]
Our NVidia patch has to be ifdef'd, looks like `task_sched.h` has only been recently introduced: https://github.com/torvalds/linux/commits/b24413180f5600bcb3bb70fbed5cf186b60864bd/include/linux/sched/task_stack.h

**Comment by ebzzry** [comment]
I also have this.

**Comment by yegortimoshenko** [comment]
Fixed in 90412f5fbc5448387c086b4cc42b7bac9d7ca238.

**Comment by vcunat** [comment]
Ah, I should've checked for this.

**Comment by kierdavis** [comment]
Working now, thanks!
