### ISSUE TITLE
EBS root volume resizing doesn't work on m5.* instances

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#33417]
## Issue description

After deploying a NixOS machine with
```
      deployment.ec2.instanceType = "m5.large";
      deployment.ec2.ebsInitialRootDiskSize = 30;
```
the root filesystem is only 2 GB:
```
/dev/disk/by-label/nixos  2.0G  765M  1.1G  42% /
```
though the disk has the correct size:
```
# cat /proc/partitions 
...
 259        0   31457280 nvme0n1
 259        1    2096128 nvme0n1p1
```

NixOS 17.09.2356.cb751f9b1c3, AMI ID ami-d40185ad.

The probable fix is that we need to point `grow-partition.nix` at the right device. From the boot log:
```
Jan 04 11:06:48 localhost stage-1-init: skipping unknown device type /dev/xvd[abcde]*
```

**Comment by pbogdan** [comment]
Possibly related https://github.com/NixOS/nixpkgs/issues/33092

**Comment by greglearns** [comment]
Has this gotten solved? I've run into the same issue after installing Nix 2.0 and the newest nixops 2 days ago, spinning up a m5large.

**Comment by copumpkin** [comment]
@edolstra a little confused at what's going on. If I look at the code that produces the message you pasted, it's definitely wrong and needs to be updated to support the NVME devices, but also isn't responsible for resizing partitions:

https://github.com/NixOS/nixpkgs/blob/eddf30cc93e1b778b6bc10d0eb1bb175385d034f/nixos/modules/virtualisation/amazon-image.nix#L94-L109

On the other hand, the partition resizing code seems fairly innocent:

https://github.com/NixOS/nixpkgs/blob/eddf30cc93e1b778b6bc10d0eb1bb175385d034f/nixos/modules/system/boot/grow-partition.nix#L31-L39

Meaning that it looks up the disk by label and resizes whatever that ends up being.

I did also spot this other place that needs updating for grub in particular, but that doesn't seem like it would prevent disk resizing:

https://github.com/NixOS/nixpkgs/blob/eddf30cc93e1b778b6bc10d0eb1bb175385d034f/nixos/modules/virtualisation/amazon-image.nix#L47

**Comment by copumpkin** [comment]
Ah, I think the issue is described in detail in https://github.com/NixOS/nixpkgs/issues/33092
