### ISSUE TITLE
Update request: ALVR 20.6.1 → 20.9.1

### ISSUE THREAD

**Issue by Titaniumtown** [NixOS/nixpkgs#334314]
- Package name: ALVR
- Latest released version: 20.9.1

- Current version on the unstable channel: 20.6.1
- Current version on the stable/release channel: 20.6.1

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@PassiveLemon 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NyCodeGHG** [comment]
relevant: #308097
