### ISSUE TITLE
Relicense yarn2nix under MIT

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixpkgs#334374]
Hi there! I’m sorry to bother you with a ping. We realized that [we’ve been vendoring GPLv3 code in Nixpkgs for years](https://github.com/NixOS/nixpkgs/issues/334267) in the form of `yarn2nix-moretea`. All of our Nix expressions are meant to be MIT‐licensed, so this is a big problem, especially as packages using `mkYarnPackage`/`mkYarnModules` may count as derivative works, potentially jeopardizing the licence status of Nixpkgs as a whole.

We would therefore like to get permission from all contributors to this code to relicense their changes under the MIT license used for Nixpkgs. If you have any questions or concerns about this, please ask them in https://github.com/NixOS/nixpkgs/issues/334267 so that this issue can purely be for tracking the sign‐offs we’ve received.

**To agree to the relicensing, please reply to this issue with the following verbatim text:**

> I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

* [x] @moretea
* [x] @zimbatm
* [x] @manveru
* [x] @nicknovitski
* [x] @nightkr
* [x] @petabyteboy (confirmed via email)
* [x] @albertov
* [x] @phryneas
* [x] @Lassulus
* [x] @adrian-gierakowski 
* [x] @thatsmydoing
* [x] @chekoopa
* [x] @fmnxl
* [x] @chpatrick
* [x] @lheckemann
* [x] @nh2
* [x] @dasJ
* [x] @srghma
* [x] @sbjorn
* [x] @betaboon
* [x] @yurrriq
* [x] @johnchildren
* [x] @dywedir
* [x] @frontsideair
* [x] @pedropombeiro
* [x] @philiptaron
* [x] @JulienMalka
* [x] @SuperSandro2000
* [x] @GuillaumeDesforges
* [x] @Smona
* [x] @ncfavier
* [x] @sumnerevans
* [x] @roberth
* [x] @purefn
* [x] @tbaggaley
* [x] @jtojnar
* [x] @AmineChikhaoui
* [x] @ShamrockLee
* [x] @yu-re-ka
* [x] @Ma27
* [x] @Stunkymonkey
* [ ] @gebner
* [x] @egasimus
* [x] @infinisil
* [ ] @volth (GitHub account is gone, although as this was just a treewide `rec` removal with no other changes it’s unlikely to be copyrightable)
* [x] @WilliButz

Authors of unmerged pull requests in the old repository (just in case we ever take code from them):

* [x] @michaelpj
* [x] @thefloweringash
* [ ] @chawki008
* [x] @Akii
* [ ] @eqyiel
* [x] @jluttine
* [x] @chrismwendt
* [x] @coltfred

(I have not checked for unmerged PRs to this part of Nixpkgs yet because it’s a pain.)

**Comment by emilazy** [comment]
Apparently I can only ping so many people at once; @eqyiel @jluttine @chrismwendt @coltfred please look at the original issue text, sorry!

**Comment by pedropombeiro** [comment]
I agree to license all of my past contributions to mayflower/yarn2nix-moretea, nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by johnchildren** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by philiptaron** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by Akii** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by infinisil** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by WilliButz** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by frontsideair** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by dywedir** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by sumnerevans** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by yurrriq** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by nightkr** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by chpatrick** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by nh2** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by chekoopa** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by thefloweringash** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by nicknovitski** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by ShamrockLee** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by zimbatm** [comment]
I agree to license all of my past contributions to [https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix](https://github.com/mayflower/yarn2nix-moretea,%C2%A0https://github.com/nix-community/yarn2nix), and the pkgs/development/tools/yarn2nix-moretea directory of [https://github.com/NixOS/nixpkgs under](https://github.com/NixOS/nixpkgs%C2%A0under) the MIT license used by Nixpkgs.

**Comment by Smona** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by Lassulus** [comment]
I agree to license all of my past contributions to [mayflower/yarn2nix-moretea](https://github.com/mayflower/yarn2nix-moretea), [nix-community/yarn2nix](https://github.com/nix-community/yarn2nix), and the pkgs/development/tools/yarn2nix-moretea directory of [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) under the MIT license used by Nixpkgs.

**Comment by betaboon** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by Ma27** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by phryneas** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by moretea** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by chrismwendt** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by Stunkymonkey** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by adrian-gierakowski** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by michaelpj** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by srghma** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by jluttine** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by SuperSandro2000** [comment]
I don't care, do whatever is necessary.

**Comment by sbjorn** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by lheckemann** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by emilazy** [comment]
@manveru @albertov @purefn @jtojnar @AmineChikhaoui @gebner @egasimus @chawki008 @eqyiel Just another gentle ping; if you could check the original post at <https://github.com/NixOS/nixpkgs/issues/334374#issue-2463254042> and respond as requested it’d help us resolve this licensing issue.

**Comment by manveru** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by albertov** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by AmineChikhaoui** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by purefn** [comment]
I agree to license all of my past contributions to https://github.com/mayflower/yarn2nix-moretea, https://github.com/nix-community/yarn2nix, and the pkgs/development/tools/yarn2nix-moretea directory of https://github.com/NixOS/nixpkgs under the MIT license used by Nixpkgs.

**Comment by jtojnar** [comment]
I agree to license all of my past contributions to [mayflower/yarn2nix-moretea](https://github.com/mayflower/yarn2nix-moretea), [nix-community/yarn2nix](https://github.com/nix-community/yarn2nix), and the pkgs/development/tools/yarn2nix-moretea directory of [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) under the MIT license used by Nixpkgs.

**Comment by infinisil** [comment]
While it wouldn't hurt to get approval from the last 4 people, I don't think we need that to move ahead:
- gebner only authored https://github.com/NixOS/nixpkgs/commit/b184f8f883eb95ba4519b22987d5d6776e2c1dcd, a minimal change that I don't think would be copyrightable
- egasismus only authored https://github.com/NixOS/nixpkgs/commit/4ef1e5b8de3831c566806312f74a38e82306eb07, another minimal change that I don't think would be copyrightable
- chawki008 only authored a PR that was never merged: https://github.com/nix-community/yarn2nix/pull/86
- eqyiel also only authored a PR that was never merged: https://github.com/nix-community/yarn2nix/pull/54

**Comment by emilazy** [comment]
Yeah, I agree those changes aren’t copyrightable. I did email the authors of them but I’ll proceed with opening a PR to do the relicensing now.

**Comment by emilazy** [comment]
Thanks so much to everyone for helping get this done so quickly, and for your contributions to the Nixpkgs Node.js ecosystem 💜
