### ISSUE TITLE
Monero

### ISSUE THREAD

**Issue by Saiv46** [NixOS/nixpkgs#334345]
### Describe the bug
`--confirm-external-bind` parameter missing
```
E --rpc-bind-ip permits inbound unencrypted external connections. Consider SSH tunnel or SSL proxy instead. Override with --confirm-external-bind
```

### Steps To Reproduce
```
{
  services.monero = {
    enable = true;
    dataDir = "/srv/monero";
    rpc = { address = "::"; };
  };
}
```

### Expected behavior
Monero node must start, or an option must be present to override this error.

### Notify maintainers
- @rnhmjoj

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment]
did you try this?
```
extraConfig = ''
  confirm-external-bind=1
'';
```

**Comment by Saiv46** [comment]
Thank you!
