### ISSUE TITLE
kdeconnect: Mounting phone's filesystem relies on `sshfs`

### ISSUE THREAD

**Issue by nixy** [NixOS/nixpkgs#33442]
## Issue description

KDE connect relies on sshfs to mount a device's filesystem for browsing. This isn't a dependency of kde-connect so attempts to use this feature will mysteriously (to the end-user) fail.

Likely resolution is that sshfs should be added as propagated input

### Steps to reproduce

1. Pair a device
2. Try to browse it's filesystem
3. Get notification that `sshfs` failed to start

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 17.09.2610.d83c8080d1e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(andrew): `"nixpkgs-18.03pre123609.93829f1b031"`
 - channels(root): `"nixos-17.09.2610.d83c8080d1e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bkchr** [comment]
I thought the same sometime ago and created a pull request (https://github.com/NixOS/nixpkgs/pull/27806).

**Comment by nixy** [comment]
Interesting. I can see the arguments for and against making this a service or module, but I don't understand why adding `sshfs` as a dependency would be a problem?

Is there some huge issue with closure size in KDE connect? Sure it isn't "essential for operation" but this still amounts to an undeclared dependency breaking a subset of functionality. Isn't this what Nix is supposed to fix?

I would like to be able to ask a friend to install software on Nix without having to explain caveats about undeclared dependencies to them...

**Comment by bkchr** [comment]
Yeah, at least the sshfs dependency would be nice. Maybe we could start another try. 

@FRidh What would you say about a new pr, where `sshfs` is made an optional dependency?

**Comment by FRidh** [comment]
My argument in #27806:

> `kdeconnect` can indeed use `sshfs` but I don't think we should make this a required dependency as its not essential for its operation, its just for a certain feature. By installing the program yourself, it ends up on your path and it will function. Yet at the same time, its a tiny package that is added.

This is still *my* opinion.

> This isn't a dependency of kde-connect so attempts to use this feature will mysteriously (to the end-user) fail.

Is there no notification *at all* that it fails to call `sshfs`? If that's the case, then I think we should either improve that message or simply add `sshfs`.

The implementation would be as in the referred PR a wrapped executable.

**Comment by nixy** [comment]
It provides a notification (at least in plasma) through the notifications systems, but the wording of it is along the lines of `sshfs failed to start` which doesn't imply that sshfs is missing. I think it's confusing enough that adding it as a dependency is reasonable.

There are other issues about getting this program to work neatly (the whole firewall thing, but that's a hornet's nest). I'll test the above PR when I get a chance, but if anyone else wants to test it first be my guest.

**Comment by BuonHobo** [comment]
Sorry to reopen this issue. Today I tried to use this feature in KDE Connect and it gave me that error (Arch Linux).
I solved by installing sshfs with no issues, but I thought it was supposed to be a dependency now?

**Comment by athulkrishna2015** [comment]
Yes me too

**Comment by npit** [comment]
Same here. Installing `sshfs` resolves this, and gives you read access to the exposed device filesystem location(s).

**Comment by peterhoeg** [comment]
I'll take a look at this unless somebody beats me to it!

**Comment by peterhoeg** [comment]
The module does now wrap sshfs, so this can be closed.

**Comment by Mrtao233** [comment]
> Sorry to reopen this issue. Today I tried to use this feature in KDE Connect and it gave me that error (Arch Linux). I solved by installing sshfs with no issues, but I thought it was supposed to be a dependency now?

yes,I reinstall it and it work！！！！！！！

**Comment by marek2001** [comment]
Again on arch linux i get the same error. sshfs wasn't installed.
