### ISSUE TITLE
Package request: vscode-extensions.vscode-nim

### ISSUE THREAD

**Issue by Dixxe** [NixOS/nixpkgs#334548]
**Project description**

Vscode extension that adds nim language server support

**Metadata**

* homepage URL: https://nim-lang.org/
* source URL: https://github.com/nim-lang/vscode-nim
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
can you name this request as [this](https://github.com/NixOS/nixpkgs/issues/334229) one?

**Comment by s0me1newithhand7s** [comment]
also seems like https://github.com/NixOS/nixpkgs/issues/332411 is exisiting for same thing. isn't it?

**Comment by Dixxe** [comment]
Yea it is
