### ISSUE TITLE
systemctl --user does not work

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#33451]
## Issue description
`systemctl --user status                                                                                   ~
Failed to read server status: Process org.freedesktop.systemd1 exited with status 1
 systemctl --user status                                                                                   ~
Failed to read server status: Process org.freedesktop.systemd1 exited with status 1
`
Log entry in journalctl -xe:

`-- Reboot --
Jan 05 10:15:30 dagNix pulseaudio[982]: GetManagedObjects() failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
Jan 05 10:15:30 dagNix xsession[937]: 26
Jan 05 10:15:30 dagNix xsession[937]: Failed to import environment: Process org.freedesktop.systemd1 exited with status 1
Jan 05 10:15:30 dagNix xsession[937]: Failed to start graphical-session.target: Process org.freedesktop.systemd1 exited with status 1
Jan 05 10:15:30 dagNix xsession[937]: See user logs and 'systemctl --user status graphical-session.target' for details.`

Also the startup of the xserver takes a lot of time, after slim accepts the password.

### Steps to reproduce
- Log in to system

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.10, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124015.f59a0f7f1a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
 - nix-channel: `https://nixos.org/channels/nixos-unstable`

### Device details
 - device: `20DLCTO1WW ThinkPad S1 Yoga 12`
 - cpu: `Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz`
 - gpu: `Intel Corporation HD Graphics 5500 (rev 09)`

**Comment by d4g** [comment]
I did some further research and I think I found out what this is about.
When the network manager has an error on stratup, the whole systemd for the user is shutdown and fails.
The network manager on the other hand, does fail if for example a network device that it should ignore is not available at all. I think this is bonkers.

**Comment by peterhoeg** [comment]
Without more details, it's impossible to say what this is about. Please re-open if the problem persists.
