### ISSUE TITLE
nautilus-sendto 3.8.6 fails to build on NixOS

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#33458]
## Issue description
Trying to switch to current trunk a1a3aea fails at nautilus-sendto.

```
...
meson: enabled parallel building
building
build flags: -j1 -l1
[1/3] Compiling C object 'src/nautilus-sendto@exe/nautilus-sendto.c.o'.
[2/3] Linking target src/nautilus-sendto.
[3/3] Generating nautilus-sendto.metainfo.xml_merge with a custom command.
FAILED: src/nautilus-sendto.metainfo.xml 
/nix/store/4wqa1whb42khic67rv9jgip30nxmaii8-python3-3.6.4/bin/python3.6m /nix/store/b9f2218hq9h5vg9k1589xvqzhdmh6gxq-meson-0.44.0/bin/meson --internal msgfmthelper ../src/nautilus-sendto.metainfo.xml.in src/nautilus-sendto.metainfo.xml xml /tmp/nix-build-nautilus-sendto-3.8.6.drv-0/nautilus-sendto-3.8.6/po
msgfmt: cannot locate ITS rules for ../src/nautilus-sendto.metainfo.xml.in
Warning: You are using 'ANSI_X3.4-1968' which is not a Unicode-compatible locale.
You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
Please switch to a UTF-8 locale for your platform.
ninja: build stopped: subcommand failed.
```
Maybe upstream bug? Doesn't seem to be nix-specific

### Steps to reproduce
Either nixos-rebuild to aforementioned trunk or nix-build/nix-env nautilus-sendto on the same revision.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by jtojnar** [comment]
cc @orivej

**Comment by hedning** [comment]
Did a bisect from `channels/nixos-unstable` (f59a0f7f1a6d968e0e05bd7d3188f32f17eb226f) to 83110ac0be3eb0d58f1b9f8cd61a3186df5d8151 with `nix-build -A gnome3.nautilus-sendto` (first manual and then scripted to make sure). First bad commit seems to be 4d2b7638173afb4c0f0c12a43654bcff5c9500ab, which is the merge commit of #26805.

cc @Ericson2314 in case he knows of an obvious fix :)

**Comment by Ericson2314** [comment]
Oh envHooks is no more. I should grep for this and fox accordingly. Weird I didn't see this when comparing Hydra evals.

**Comment by hedning** [comment]
Pretty sure that `gnome3.gnome-screenshot` suffers from the same problem btw.

**Comment by srhb** [comment]
#33524 may be the right fix here,if gobjectintrospection isn't actually necessary.

**Comment by jtojnar** [comment]
Yes.

**Comment by vcunat** [comment]
Ah, so on staging we will probably be able to revert d3ad52a58 and 2a1425d8b...

**Comment by srhb** [comment]
@vcunat Only d3ad52a58eb3e4513f962eb059918579d6813a39 is on staging, so I've gone ahead and reverted that, so we can tell if the gettext change was sufficient. :smile:

**Comment by vcunat** [comment]
Both packages are now worked around on master and fixed in staging.
