### ISSUE TITLE
Package request: ludisavi

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#334589]
**Project description**

Backup tool for PC game saves 

**Metadata**

* homepage URL: https://github.com/mtkennerly/ludusavi
* source URL: https://github.com/mtkennerly/ludusavi
* license: mit
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luftmensch-luftmensch** [comment]
It seems that it has already been [packaged](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/backup/ludusavi/default.nix#L93)

**Comment by griffi-gh** [comment]
oops, my bad;
(a quick search on nixpkgs did not return anything..)
