### ISSUE TITLE
waydroid service cannot be manually stopped completely (automatically starts again)

### ISSUE THREAD

**Issue by AleXoundOS** [NixOS/nixpkgs#334687]
### Describe the bug
`waydroid-container` systemd service cannot be stopped completely. It starts again automatically right after being stopped.

### Steps To Reproduce
```nix
virtualisation.waydroid.enable = true;
```

```console
$ systemctl stop waydroid-container
```

### Expected behavior
`waydroid-container` gets stopped completely after `systemctl stop waydroid-container`.

### Screenshots
```console
$ sudo journalctl -b -u waydroid-container -e
Aug 14 14:01:01 v16 systemd[1]: Stopping Waydroid Container...
Aug 14 14:01:26 v16 systemd[1]: waydroid-container.service: Deactivated successfully.
Aug 14 14:01:26 v16 systemd[1]: waydroid-container.service: Consumed 498ms CPU time, 61.5M memory peak, 0B memory swap peak, read 24.7M from disk, written 0B to disk, no IP traffic.
Aug 14 14:01:26 v16 systemd[1]: Started Waydroid Container.
```

### Additional context
```systemd
$ systemctl cat waydroid-container.service
# /etc/systemd/system/waydroid-container.service
[Unit]
Description=Waydroid Container

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/9dij3pl4dkdxmxhasjw1pa9hzqv4rjlp-glibc-locales-2.39-52/lib/locale/locale-archive"
Environment="PATH=/nix/store/ysqx2xfzygv2rxl7nxnw48276z5ckppn-coreutils-9.5/bin:/nix/store/36rvynxwln7iz0qq3k1v3r1mna8bma8s-findutils-4.9.0/bin:/nix/store/d9xr7s3z0r8rf0ba22q6ilqv68agymdb-gnugrep-3.11/bin:/nix/store/7xwbkzfrs6flyvjyvd23m8r2mlnycinq-gnused-4.9/bin:/nix/stor>
Environment="TZDIR=/nix/store/jyh52p2cxrjn8r4ywdv2am5pjkj1xcqa-tzdata-2024a/share/zoneinfo"
ExecStart=/nix/store/qvki6wzc69hs5vs00x0ayk615rl7d10b-waydroid-1.4.2/bin/waydroid -w container start
ExecStop=/nix/store/qvki6wzc69hs5vs00x0ayk615rl7d10b-waydroid-1.4.2/bin/waydroid container stop
ExecStopPost=/nix/store/qvki6wzc69hs5vs00x0ayk615rl7d10b-waydroid-1.4.2/bin/waydroid session stop

[Install]
WantedBy=multi-user.target
```

`waydroid container stop` in `ExecStopPost` causes the systemd service to start again.

```nix
systemd.services.waydroid-container.serviceConfig.ExecStopPost =
  pkgs.lib.mkForce "";
```
Allows the systemd service to stop completely without further automatic start. But this way it skips `waydroid session stop` step.

### Notify maintainers

@CajuM, @c-h-johnson

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.05 (Uakari), 24.05.20240711.a046c12`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.2`
 - nixpkgs: `/nix/store/2k0r4pk0hzjzk9iwyi61xc0z4qv791j9-source`
```

**Comment by CajuM** [comment]
Waydroid now uses the following systemd service by default: https://github.com/waydroid/waydroid/blob/main/systemd/waydroid-container.service guess ExecStop and ExecStopPost are redundant.

**Comment by AleXoundOS** [comment]
_I fixed my post, where `ExecStopPost` was missing (because I overridden it). So, `waydroid session stop` actually causes systemd service to start again._

**Comment by AleXoundOS** [comment]
> Waydroid now uses the following systemd service by default: https://github.com/waydroid/waydroid/blob/main/systemd/waydroid-container.service guess ExecStop and ExecStopPost are redundant.

Yeah, [since 1.4.0 waydroid version, `ExecPost` and `ExecStopPost` directives are removed from waydroid-container.service](https://github.com/waydroid/waydroid/commit/d53da44f7292b3c9acd00b316a6fb248a9dd96d8#diff-2d908a3d79f4759882f3f4fb7e5e0cb838008b6702093b298b536992b06b8b93L6-L7). Currently, version 1.4.2 is the latest in nixpkgs.
