### ISSUE TITLE
`cinny-desktop` : Failed to load.

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#334631]
### Describe the bug
`cinny-desktop` : Fails to load after logging in
"Failed to load. WebAssembly.Module doesn't parse at byte 0: module doesn't start with '\0asm'"

### Steps To Reproduce
1. Install the `cinny-desktop` package
2. Log into a Matrix account
3. App fails to start with error mentioned before

### Expected behavior
-

### Screenshots
![Screenshot_20240814_160359](https://github.com/user-attachments/assets/3f9d74ed-a36a-4333-96c4-46d2e31e920e)

### Additional context
-

### Notify maintainers

@Qyriad 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.11 (Vicuna), 24.11.20240809.5e0ca22`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.24.0pre20240723_fb450de2`
 - nixpkgs: `/nix/store/0jr2kk95c34c0b6yxi75q4fqgb43kqkm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
![image](https://github.com/user-attachments/assets/b023d8e6-de23-4531-87d5-3365309478c8)

seems like the wasm file is missing outright for some reason

**Comment by Qyriad** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/331078
