### ISSUE TITLE
Build failure: wezterm

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#334650]
### Steps To Reproduce

1. build wezterm with today's master branch (I'll be able to find the exact commit later)

### Build log

```
building '/nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv'...
note: keeping build directory '/tmp/nix-build-wezterm-20240203-110809-5046fc22.drv-16/build'
error: builder for '/nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling native-tls v0.2.11
       >    Compiling line-wrap v0.1.1
       >    Compiling cairo-sys-rs v0.18.0 (/build/source/deps/cairo)
       >    Compiling x11 v2.21.0
       >    Compiling quick-xml v0.31.0
       >    Compiling quick-xml v0.30.0
       >    Compiling wayland-commons v0.29.5
       > For more information about this error, try `rustc --explain E0282`.
       > error: could not compile `time` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv'.
```

```
error[E0282]: type annotations needed for `Box<_>`
  --> /build/cargo-vendor-dir/time-0.3.31/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling toml_edit v0.19.15
   Compiling memoffset v0.9.0
   Compiling fixed v1.24.0
   Compiling rustc-demangle v0.1.23
   Compiling safemem v0.3.3
   Compiling scoped-tls v1.0.1
   Compiling native-tls v0.2.11
   Compiling line-wrap v0.1.1
   Compiling cairo-sys-rs v0.18.0 (/build/source/deps/cairo)
   Compiling x11 v2.21.0
   Compiling quick-xml v0.31.0
   Compiling quick-xml v0.30.0
   Compiling wayland-commons v0.29.5
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### Notify maintainers

@SuperSandro2000 @mimame

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.4, NixOS, 24.11 (Vicuna), 24.11.20240814.29aa9e9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - nixpkgs: `/nix/store/5d90zrvwna6sxi32sqvdhi0d665kka44-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by spiage** [comment]
build error came with https://github.com/NixOS/nixpkgs/pull/332764

```console
root in /etc/nixos 
❯ nix build github:nixos/nixpkgs/2ed49f0b547406c3b9b7b3c865e08fdecf3bdbae#wezterm --rebuild

root in /etc/nixos took 3m48s 
❯ nix build github:nixos/nixpkgs/57d0d4a8f3025e2b902d2b4403bcece26ad1ea74#wezterm --rebuild

root in /etc/nixos took 3m24s 
❯ nix build github:nixos/nixpkgs/9ccfa877218074582ff21fe950944fa0a7240248#wezterm --rebuild
error: some outputs of '/nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv' are not valid, so checking is not possible

root in /etc/nixos took 14s 
❯ nix run github:nixos/nixpkgs/9ccfa877218074582ff21fe950944fa0a7240248#wezterm
error: builder for '/nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling safemem v0.3.3
       >    Compiling line-wrap v0.1.1
       >    Compiling cairo-sys-rs v0.18.0 (/build/source/deps/cairo)
       >    Compiling quick-xml v0.30.0
       >    Compiling serde_derive v1.0.196
       >    Compiling thiserror-impl v1.0.56
       >    Compiling tracing-attributes v0.1.27
       > For more information about this error, try `rustc --explain E0282`.
       > error: could not compile `time` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/l4ha5w08li3dj3s5jf0qr9rl7pd1f3pn-wezterm-20240203-110809-5046fc22.drv'.
```

**Comment by SuperSandro2000** [comment]
I tried this exactly on staging-next at the time and it didn't fail....

I'll probably going to patch the time update because wezterm is currently reworking Wayland support a lot and in the days after a release usually several bugs are discovered.

**Comment by SuperSandro2000** [comment]
#334818

**Comment by spiage** [comment]
I'll test it ASAP, after this =)
![image](https://github.com/user-attachments/assets/e170b218-7ba4-4707-bcad-ae34098dcb8f)
Is there any option to let the package to be built alone?
I have 128Gb of memory, but usually two of them can force OOM, so I have to use swap :)

**Comment by spiage** [comment]
I know about -jN, but I mean something like build_parallel = false;

**Comment by spiage** [comment]
My current memory load, while this three packages are building
![image](https://github.com/user-attachments/assets/258134bc-b9f2-4aa9-86e5-65a65c14aa79)

**Comment by zierf** [comment]
A failed update originally led me to the issue [Rust 1.80.0 breaks some packages](https://github.com/NixOS/nixpkgs/issues/332957#issuecomment-2273039711) and then to the [Merge-Request #334818](https://github.com/NixOS/nixpkgs/pull/334818).

Has this change changed anything about the basic functionality of WezTerm? At least for me it has destroyed the font display, only boxes are displayed instead of letters.

Here is a screenshot, on the left with the version from the previous [Revision #957d95fc](https://github.com/NixOS/nixpkgs/blob/957d95fc8b9bf1eb60d43f8d2eba352b71bbf2be/pkgs/applications/terminal-emulators/wezterm/default.nix) for my System Flake compared to [Revision #91b4c602](https://github.com/NixOS/nixpkgs/blob/91b4c602cc51732ec0d3a491684cd03f20773dec/pkgs/applications/terminal-emulators/wezterm/default.nix) on the right and my broken Starship prompt.

![20240815_201621](https://github.com/user-attachments/assets/fe27b9ec-7546-41e9-b229-02b6cd24d4ae)

**Comment by SuperSandro2000** [comment]
> Has this change changed anything about the basic functionality of WezTerm?

I highly doubt it. The time crate has hopefully not so much influence on font rendering. There is probably something else off. I have that bug now locally, too.
Graphic rendering is just such a disaster....

**Comment by SuperSandro2000** [comment]
Their matrix channel hinted me at a potential wgpu issue. For me setting ``front_end = "WebGpu"`` worked around this.
