### ISSUE TITLE
tigervnc doesn't build on unstable

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#33463]
## Issue description

The build of tigervnc stops with the following error:

      CC       glxscreens.lo
    glxscreens.c:46:26: fatal error: compositeext.h: No such file or directory
     #include "compositeext.h"
                              ^
    compilation terminated.

The offending file is https://github.com/XQuartz/xorg-server/blob/master/glx/glxscreens.c#L46 (which is not part of the tigervnc repository, but is nevertheless unpacked by the Nix build description under `unix/xserver`). Indeed, the file `compositeext.h` isn't contained in the directory in which `glxscreens.c` is located.

The build can be fixed be either of the following steps:

* Manually remove the import of `compositeext.h`. It doesn't appear to be needed (the build works, but I didn't do any testing).

* Manually copy `compositeext.h` from `unix/xserver/composite/` to `unix/xserver/glx/`. This workaround is obviously a hack and should instead be properly dealt with by setting appropriate include paths.

I don't have time to investigate further. From the little I know, this problem might have to be propagated upstream (to the maintainers of xorg).

### Steps to reproduce

Try to install tigervnc.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.7, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124626.a1a3aeaa8f8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by iblech** [comment]
Cc @viric.

**Comment by dtzWill** [comment]
Curiously [this change](8aecafcf5e53c1511a567b4d6e3a11b573d6b9aa) switched `--disable-glx` to `--enable-glx` but makes no mention of it.

Some quick testing shows that:

* `--enable-composite` and `--enable-glx` => success
* `--disable-composite` and `--disable-glx` => success

I'm not sure which is the right way to go, but both fix the build.

Related: will submit PR for enabling parallel building here too

**Comment by dtzWill** [comment]
Eep, my bad for not including magic-issue-closing language in the commit message.

This should be fixed by the (recently merged) PR mentioned above,
which will be included the next time `unstable` channel advances.

**Comment by iblech** [comment]
@dtzWill: Thank you! I'll close this issue then. Incidentally, Arch folks also compile with `--enable-glx`: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/tigervnc Curiously, they don't seem to have `--enable-composite`. I wonder whether their build is therefore broken as well.

**Comment by dtzWill** [comment]
Hmm. They don't disable it either, not sure.  I suspect it is enabled by default when asking for glx since it's apparently required.  They do include 'compositeproto' as a build dep, not sure if we do as well.

**Comment by dtzWill** [comment]
Hmm. They don't disable it either, not sure.  I suspect it is enabled by default when asking for glx since it's apparently required.  They do include 'compositeproto' as a build dep, not sure if we do as well.
