### ISSUE TITLE
aws-vault exec runs `bash` instead of `bashInteractive`

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#334665]
### Describe the bug
aws-vault exec runs `bash` instead of `bashInteractive`:
```
teto$ aws-vault exec --no-session awssandbox
Starting subshell /nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash, use `exit` to exit the subshell
bash: shopt: progcomp: invalid shell option name
bash: set: vi: invalid option name
bash: /home/teto/.config/bash/bashrc.sh: No such file or directory
bash: builtin: complete: not a shell builtin
bash: builtin: complete: not a shell builtin
bash: builtin: complete: not a shell builtin
bash: builtin: complete: not a shell builtin
bind: command not found
bind: command not found
bind: command not found
```
I found the dependency via:
```
➜ nix why-depends --precise /nix/store/1bpzv22wkvab1clk7i0dpb8ljzm38s2p-aws-vault-7.2.0 /nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash
/nix/store/1bpzv22wkvab1clk7i0dpb8ljzm38s2p-aws-vault-7.2.0
└───bin/aws-vault: …#! /nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/bash -e.PATH=${…
```

### Expected behavior
have `aws-vault exec` launch bashInteractive

### Additional context
I hoped adding bashInteractive to buildInputs would let `patchShebangs` use it but it doesn't seem to be the case :'( How can I have patchShebang use bashInteractive instead of bash ?

### Notify maintainers

@zimbatm 

### Metadata
nixos-unstable

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zimbatm** [comment]
It should work if you `export PATH=${bashInteractive}/bin:$PATH` before calling patchSehbangs.

The issue is that by default, the PATH comprises all the inputs, lexicographically ordered by their store path. AKA sorted by the hashes.

**Comment by teto** [comment]
not sure why but it seems to work fine now :s also the bash I see was added by wrapProgram, not patchShebangs. Closing for now. Ty for answer
