### ISSUE TITLE
bashburn write problem

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#33464]
## Issue description
I can read but not write audio cds with bashburn. 
Maybe it is a misconfiguration of bashburn? 
the (0,0,0) is strange, but it seems to want that?
```
|-(Setup)                           (Current value)
|   0) CD-Writer                    (0,0,0)
|   1) CD-Reader Device File        (/dev/sr0)
|   2) CD-Reader Mount Point        (<Change me>)
|   3) Speed                        (-1)
|   4) Blanking Type                (fast)
|   5) Number of Devices            (1)
|   6) Burn Directory               (/home/mcd/tmp/burn)
|   7) CD Label                     (BashBurn CD/DVD)
|   8) Author                       (<Change me>)
|   9) Description                  (Burnt with BashBurn)
|  10) Normalize                    (no)
|  11) Driver options               ()
|  12) FIFO directory               (/tmp)
|  13) Delete temp after burn       (no)
|  14) Allow overburn               (no)
|  15) Set the Bitrate              (192)
|  16) Language                     (English)
|  17) DAO/TAO                      (-tao)
|  18) Gap between tracks           (-pad)
```
```
+----------------+ INFORMATION +----------------+

The writer is supposed to be entered as 0,0,0 for SCSI
or /dev/hdX for IDE writers (Where X is a driver letter).
For auto-detect, enter auto. To cancel, just press [ENTER].
The current setting is: /dev/sr0, and below is a list
of possible writers on your system (According to /etc/fstab).
```
### Steps to reproduce
```
+----------------+
| BashBurn 3.1.0 |
+----------------+
|
|-(Audio Menu)
|  0) Burn Audio from Mp3s/Oggs/Wavs/FLACs
|  1) Burn Audio Directly
|  2) Copy Audio CD [CD to CD]
|  3) Copy Audio CD [CD to harddrive]
|  4) Burn M3U Playlist
|  5) Create MP3s from Wavsa
|  6) Create Oggs from Wavs
|  7) Create FLACs from Wavs
|  8) Create MP3s from CD
|  9) Create Oggs from CD
| 10) Create FLACs from CD
| 11) Back

|
	Your Choice? [0-11] |> 0
No *.mp3 audio files found
No *.ogg audio files found
No *.flac audio files found
*.wav being used...
Not using Normalize...
Not enabling overburn...
GNU xorriso 1.4.8 : RockRidge filesystem manipulator, libburnia project.

xorriso : FAILURE : -as cdrecord: Surplus track source 'track02.cdda.wav'
xorriso : NOTE : First and only track source is 'track01.cdda.wav'
xorriso : NOTE : Giving up for -eject whole -dev ''
xorriso : FAILURE : -as cdrecord: Job could not be performed properly.
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
Burning failed.
Hit any key to continue : 
```
the burn directory contains `track{01..20}.cdda.wav`.

maybe it's a wrong/old parameter passed to xorriso (which acts like cdrecord et al.)?

## Technical details
bashburn 3.1.0

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.68, NixOS, 17.09.2476.53e6d671a96 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(mcd): `""`
 - channels(root): `"nixos-17.09.2498.a9ffb7b0b5a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by castilma** [comment]
It works after installing cdrkit and pointing the cdburning command from
`/nix/store/vld9x3hl7qwks5vng62fqa164mgg000h-xorriso-1.4.8/bin/xorriso -as cdrecord` to `/home/mcd/.nix-profile/bin/cdrecord`.

I think this is either a bug in xorriso (not mimicking cdrecord correctly), or bashburn expecting some older parameters, which were removed (from cdrecord and xorriso), to exist.

@nckx Can you check where the problem is?

**Comment by scdbackup** [comment]
Hi,

man xorriso says:
"Note that xorriso does not write audio CDs [...]"

man xorrecord (which describies xorriso -as cdrecord):
"xorrecord produces a single session with a single data track which 
 consists  of  blocks  with  2048 bytes  each."

If you want to burn CD audio tracks and/or multiple tracks per session 
by a libburn based command line tool, use cdrskin.
(Of course, wodim and cdrecord are good choices for CD media. With DVD
and BD i'd strongly recommend to use growisofs or a libburn based program.)

Have a nice day :)

Thomas
