### ISSUE TITLE
mount can't find systemd-ask-password

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#33475]
When I try to mount a password-protected CIFS drive on my NixOS system, I get the following error message:

~~~
# mount /mnt/fritz.nas
sh: systemd-ask-password: command not found
~~~

Now, after that error, `mount` proceeds to ask  for a password anyway (probably through some means available as a fallback), but still this doesn't seem right. The requested tool is installed and available in `$PATH`:

~~~
# type -p systemd-ask-password
systemd-ask-password is /run/current-system/sw/bin/systemd-ask-password
~~~

Is it possible that `mount` doesn't have that `$PATH` configured for some reason?

**Comment by scalavision** [comment]
me too

**Comment by FRidh** [comment]
Noticed the same issue just now.

In `nixos/modules/system/boot/systemd.nix` it says

```
# Default path for systemd services.  Should be quite minimal.
          path =
            [ pkgs.coreutils
              pkgs.findutils
              pkgs.gnugrep
              pkgs.gnused
              systemd
            ];
          environment.PATH = config.path;
```
and `systemd` has `systemd-ask-password`.

**Comment by peti** [comment]
This issue has been fixed.
