### ISSUE TITLE
`vmTools.runInLinuxVM` fails upon `__structuredAttrs = true`, complaining `mkdir: missing operand`

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#334705]
### Describe the bug

When passing a derivation with `__structuredAttrs = true` to `vmTools.runInLinuxVM` and building the resulting derivation, the build fails with a confusing error message:

```
mkdir: missing operand
Try 'mkdir --help' for more information.
```

### Steps To Reproduce
1. Run
```sh
nix-build --no-out-link --expr "with (import ./. { }); vmTools.runInLinuxVM (hello.overrideAttrs { __structuredAttrs = true; })"
```
3. See error.

### Expected behavior
Derivations with `__structuredAttrs = true` modified by `vmTools.runInLinuxVM` build without error.

### Additional context
I checked all the `mkdir` commands inside `pkgs/build-support/vm`, none of which seems to have a possibly-missing path.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.37, NixOS, 24.05 (Uakari), 24.05.20240707.1948467`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/k251vbbhlk91xwjkxnma7g545i5avhah-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
2016: "Huh, need to fix this properly" 🙃

**Comment by ShamrockLee** [comment]
I finally found a way to print the Bash xtrace:

```
❯ nix-build --no-out-link --expr "with (import ./. { }); lib.overrideDerivation (vmTools.runInLinuxVM (hello.overrideAttrs (previousAttrs: {  __structuredAttrs = true; }))) (drv: { args = [ ''-x'' ] ++ drv.args; })"
this derivation will be built:
  /nix/store/m56vwisrf5npi8v15y8r7q1rv1k82lax-hello-2.12.1.drv
building '/nix/store/m56vwisrf5npi8v15y8r7q1rv1k82lax-hello-2.12.1.drv'...
+ export
+ PATH=/nix/store/cnknp3yxfibxjhila0sjd1v3yglqssng-coreutils-9.5/bin
+ mkdir xchg
+ mv saved-env xchg/
+ eval ''
+ '[' '' = 1 ']'
+ cat
+ mkdir -p -m 0700
mkdir: missing operand
Try 'mkdir --help' for more information.
error: builder for '/nix/store/m56vwisrf5npi8v15y8r7q1rv1k82lax-hello-2.12.1.drv' failed with exit code 1;
       last 10 log lines:
       > + export
       > + PATH=/nix/store/cnknp3yxfibxjhila0sjd1v3yglqssng-coreutils-9.5/bin
       > + mkdir xchg
       > + mv saved-env xchg/
       > + eval ''
       > + '[' '' = 1 ']'
       > + cat
       > + mkdir -p -m 0700
       > mkdir: missing operand
       > Try 'mkdir --help' for more information.
       For full logs, run 'nix log /nix/store/m56vwisrf5npi8v15y8r7q1rv1k82lax-hello-2.12.1.drv'.
```

The line of `mkdir` missing the operand originally read `mkdir -p -m 0700 $out` slipped over my radar because I thought "$out" would never be empty.

https://github.com/NixOS/nixpkgs/blob/aa5646ff3b45bb04fbc9b56c7e88263623308455/pkgs/build-support/vm/default.nix#L277

**Comment by yfyf** [comment]
Are there maybe possible workarounds for this issue? I was hoping to use `unsafeDiscardReferences` to speed up building disk images using `runInLinuxVM`, but this prevents it unfortunately.
