### ISSUE TITLE
Enhancement: declaratively specify gcroots in NixOS

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nixpkgs#33486]
## Issue description

A NixOS option of the form nix.gc.roots = [ ] would be a nice way to give a list of packages / derivations that won't be garbage collected.  The packages listed there would be added to the /nix/var/nix/gcroots directory on each nixos-rebuild.

Workaround until then: symlink /nix/var/nix/gcroots/foo to /etc/gcroots, and then put the things you want to not be garbage collected in /etc/gcroots with environment.etc.

**Comment by FRidh** [comment]
I think what you want is given by `system.extraDependencies`.

**Comment by volth** [comment]
```system.extraDependencies``` adds the packages to the closure, which has size limit due to peak ```nix``` memory consumption linearly depends on closure size.
For example, if you add 30 other closures to ```system.extraDependencies``` just to save them from GC, it would work, but ```nix``` would require 10-20Gb of RAM.to handle it.

**Comment by abathur** [comment]
Closing since it sounds like FRidh answered the question, but I'm happy to reopen if you don't agree.
