### ISSUE TITLE
Package request: Update kicad-unstable version

### ISSUE THREAD

**Issue by multivac61** [NixOS/nixpkgs#334877]
**Project description**

There have been significant changes on the kicad master branch, e.g., adding `protobuf` as a dependency. Please update the `kicad-unstable` version (last updated in February).

@evils

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by uzytkownik** [comment]
I requested it in issue #327181 BTW. You may close this one as duplicate.

**Comment by uzytkownik** [comment]
I created a pull request #335314 if you want to check it out.

**Comment by multivac61** [comment]
Closing as duplicate of #327181
