### ISSUE TITLE
Build failure: Veloren

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#334931]
### Steps To Reproduce

1. Build `veloren` on any `system` after the Rust toolchain was updated to `1.80.0`
2. See failure with the `time` crate

### Build log

See [Hydra](https://hydra.nixos.org/build/269604964/nixlog/1).

### Additional context

* Tracked upstream: https://gitlab.com/veloren/veloren/-/issues/2005
* Broader issue tracked locally: #332957

### Notify maintainers

@rnhmjoj and myself

### Metadata

See [information available in Hydra](https://hydra.nixos.org/build/269604964).

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment]
It seems the only problem is the `time` package thing, besides a bunch of new warnings.
I'm still building, though...
