### ISSUE TITLE
nixos/tests/blivet: times out

### ISSUE THREAD

**Issue by pbogdan** [NixOS/nixpkgs#33496]
## Issue description

This test doesn't appear to have succeeded in the last few months:

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.blivet.x86_64-linux

### Steps to reproduce

```
$ nix-build nixos/release-combined.nix -A nixos.tests.blivet
```

The test hangs on current master and 17.09.

/cc @aszlig

**Comment by flokli** [comment]
@aszlig the blivet tests still seem to be broken.

WDYT about removing the nixos test alltogether?

**Comment by worldofpeace** [comment]
They've been broken for a while @flokli, we could just mark the test as broken.

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/78927, let's actually remove. It has been broken for longer.

**Comment by pbogdan** [comment]
With #78927 merged this can be now closed @worldofpeace?

**Comment by flokli** [comment]
Yeah, let's close this. There's no test anymore that can time out :laughing:

**Comment by aszlig** [comment]
@flokli: Thanks!
