### ISSUE TITLE
ceph 18.2.4 still broken with cryptsetup/dmcrypt

### ISSUE THREAD

**Issue by benaryorg** [NixOS/nixpkgs#334975]
### Describe the bug
The fix rolled out in #334275 lacks the third patch (https://github.com/ceph/ceph/commit/607eb34b2c278566c386efcbf3018629cf08ccfd) described in #334227. Without that patch it is still not possible to use ceph-volume with a dmcrypt'd volume.

### Steps To Reproduce
1. `ceph-volume lvm activate` on a bluestore OSD using LUKS

### Expected behavior
Volume is activated.

### Additional context
As [described in the original issue thread](https://github.com/NixOS/nixpkgs/issues/334227#issuecomment-2285317255) there is still a stack trace that can be fixed by applying the above (and in the other issue thread) mentioned patch.

### Notify maintainers

- @nh2
- @adevress @alexanderkjeldaas @johanot @krav

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix run nixpkgs#nix-info -- -m 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.45, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/yj1w6dachan720i1m4037jllrf2r5xrb-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nh2** [comment]
@benaryorg 

Is there any chance you could add a NixOS VM test that exercises cryptsetup/dmcrypt?

Then your setup would be guarded by that for any future NixOS changes.

**Comment by benaryorg** [comment]
@nh2
> Is there any chance you could add a NixOS VM test that exercises cryptsetup/dmcrypt?
> 
> Then your setup would be guarded by that for any future NixOS changes.

That's on my todo list for when I have enough spoons, but it is there and I will probably get to it within the next few weeks.
