### ISSUE TITLE
Package request: home-manager modules for gnome-console like for gnome-terminal

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#334938]
Package request: home-manager modules for gnome-console like for gnome-terminal
https://mynixos.com/search?q=gnome-terminal
https://mynixos.com/search?q=gnome-console

**Comment by MatthewCash** [comment]
Issues related to home-manager should be files in their repo's issue tracker.

https://github.com/nix-community/home-manager/issues/new/choose
