### ISSUE TITLE
Package request: YARG

### ISSUE THREAD

**Issue by Kommynct** [NixOS/nixpkgs#334960]
**Yet Another Rhythm Game, open source variant of clonehero**

**Metadata**

* homepage URL: https://github.com/YARC-Official/YARG
* source URL: https://github.com/YARC-Official/YARG
* license: LGPL-3.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
I got it working in my NUR repo: https://gitlab.com/kira-bruneau/nur-packages/-/blob/bec4c163c7aa1d9f3f8ad11eaed8f27454d26b21/pkgs/by-name/ya/yarg/package.nix

I just wanted to try it out a bit before submitting a PR here - I just need to find that guitar and make sure it still works :sweat_smile:

**Comment by kira-bruneau** [comment]
Ok... I'm remembering why it's been so long since I've played clonehero now. The knockoff wiimote I have now doesn't work with the guitar, so I just ordered an official one.

I'm going to hold opening a PR still until I can actually play the game.

**Comment by Kommynct** [comment]
unrelated, I do recommend trying out this guys controllers, I love mine: https://www.etsy.com/listing/1061091736/mini-guitar-for-clone-hero-guitar-hero

they're usually only 30$ and you don't have to rely on aging tech, mechanical switches and all.

**Comment by natervader** [comment]
Just to chime in about YARG - could not get it running using YARC but it opened using your binary. I couldn't get bindings for my Riffmaster to work properly. Likely just an issue with the game itself to be honest but figured I'd chime in with it. I'll probably try out my other controllers tomorrow.

**Comment by natervader** [comment]
Really late on my reply but tested with a PS2 controller, works as expected.

**Comment by kira-bruneau** [comment]
Ok thanks @natervader! I still haven't been able to get it working with my old wiitar, but I'll open a new PR for it!
