### ISSUE TITLE
Update request: heroic 2.14.1 → 2.15.1

### ISSUE THREAD

**Issue by dakota-marshall** [NixOS/nixpkgs#335028]
- Package name: heroic
- Latest released version: 2.15.1

- Current version on the unstable channel: 2.14.1
- Current version on the stable/release channel:  2.14.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aidalgol 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
isn't similar issue exist?

**Comment by s0me1newithhand7s** [comment]
yep, you can close this issue as https://github.com/NixOS/nixpkgs/issues/333956 exist.

**Comment by dakota-marshall** [comment]
Sorry, apparently I don't know how to search these issues correctly...
