### ISSUE TITLE
Build failure: nix-init

### ISSUE THREAD

**Issue by iynaix** [NixOS/nixpkgs#335007]
### Steps To Reproduce

1. build *nix-init*

### Build log

[nix-init.log](https://gist.github.com/iynaix/69b9dd0317eadc20277ca6b2781b0556)

### Additional context

Unsetting `LIBGIT2_NO_VENDOR` appears to fix the build, I'm not sure if this is the right fix.

### Notify maintainers

@figsoda 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240811.a58bc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/h60m1fwahjd2mv6gsg77ji3vb4gpj4dk-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
https://github.com/NixOS/nixpkgs/pull/335035
