### ISSUE TITLE
nixos/nebula: undefined variable in meta.maintainers

### ISSUE THREAD

**Issue by yunfachi** [NixOS/nixpkgs#335077]
### Steps To Reproduce

```bash
nix repl <<< "(($(curl https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/services/networking/nebula.nix)){config={}; lib={};pkgs={};}).meta.maintainers"
```

### Log
[ error: undefined variable 'numinit'

       at «string»:273:24:

          272|
          273|   meta.maintainers = [ numinit ];
             |                        ^

### Additional context

it seems that `with maintainers;` has been forgotten in https://github.com/NixOS/nixpkgs/commit/de5e0cf11be284dde72ff6297fc410a9e74502ab .

### Notify maintainers

@numinit 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by numinit** [comment]
Oof, how did that happen 😅

Thanks for the report!

**Comment by numinit** [comment]
#335191
