### ISSUE TITLE
nixos/timesyncd: does not use the NTP servers advertised by DHCP

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#335050]
### Describe the bug
`timesyncd` does not use the NTP servers advertised by DHCP.

### Steps To Reproduce
1. Boot a NixOS machine in a network advertising NTP servers by DHCP
2. Observe that `timesyncd` uses the NTP servers configured with `services.timesyncd.servers`:

    ```shell
    [root@mymachine:~]# cat /etc/systemd/timesyncd.conf
    [Time]
    NTP=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org 2.nixos.pool.ntp.org 3.nixos.pool.ntp.org
    
    
    [root@mymachine:~]# timedatectl show-timesync
    LinkNTPServers=10.199.1.2 10.199.1.3 10.200.1.10
    SystemNTPServers=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org 2.nixos.pool.ntp.org 3.nixos.pool.ntp.org
    FallbackNTPServers=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org 2.nixos.pool.ntp.org 3.nixos.pool.ntp.org
    ServerName=0.nixos.pool.ntp.org
    ServerAddress=185.175.56.95
    RootDistanceMaxUSec=5s
    PollIntervalMinUSec=32s
    PollIntervalMaxUSec=34min 8s
    PollIntervalUSec=1min 4s
    NTPMessage={ Leap=0, Version=4, Mode=4, Stratum=2, Precision=-26, RootDelay=991us, RootDispersion=869us, Reference=4D28E279, OriginateTimestamp=Fri 2024-08-16 07:18:40 UTC, ReceiveTimestamp=Fri   2024-08-16   07:18:40 UTC, TransmitTimestamp=Fri 2024-08-16 07:18:40 UTC, DestinationTimestamp=Fri 2024-08-16 07:18:40 UTC, Ignored=no, PacketCount=1, Jitter=0 }
    Frequency=-2844436
    
    [root@mymachine:~]# timedatectl timesync-status
           Server: 185.175.56.95 (0.nixos.pool.ntp.org)
    Poll interval: 1min 4s (min: 32s; max 34min 8s)
             Leap: normal
          Version: 4
          Stratum: 2
        Reference: 4D28E279
        Precision: 1us (-26)
    Root distance: 1.364ms (max: 5s)
           Offset: -9.797ms
            Delay: 12.210ms
           Jitter: 0
     Packet count: 1
        Frequency: -43.403ppm
    ```

### Expected behavior
`timesyncd` should use the NTP servers advertised by DHCP.

### Additional context

This is because the servers explicitly set in `NTP=` (see `man timesyncd.conf(5)`) take precedence over NTP servers advertised by DHCP.

A simple workaround is to set `services.timesyncd.servers = [];`.

Since the `0.nixos.pool.ntp.org`, `1.nixos.pool.ntp.org`, `2.nixos.pool.ntp.org` and `3.nixos.pool.ntp.org` are already set as compile-time fallback servers, why is not `[]` the default value for `services.timesyncd.servers`?

Another solution would be to modify the module to achieve the equivalent of:
```nix
services.timesyncd = {
  servers = [];
  extraConfig = ''
    FallbackNTP=${lib.concatStringsSep " " config.networking.timeServers}
  '';
};
```

### Notify maintainers

@flokli @blitz @andir @cdepillabout 

### Metadata
Running NixOS 24.05 with systemd 255 (255.6).

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (nix-info) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by flokli** [comment]
This looks like a good idea. Can you send a PR, and maybe update the option description?

**Comment by flokli** [comment]
No, I did not, but the fallback approach seems nicer. Please copy (and update) the release note entry from here, though.

**Comment by flokli** [comment]
I meant to close https://github.com/NixOS/nixpkgs/pull/335802, not this issue. Sorry for the noise.
