### ISSUE TITLE
obs browser source does not draw anything

### ISSUE THREAD

**Issue by TheAwesome98-Real** [NixOS/nixpkgs#335155]
### Describe the bug
in obs, the browser source doesn't draw anything. if you have a browser source in a scene, it is just transparent, and if you have a docked browser source, it doesn't draw anything (for example, just after obs starts you will see the window that was behind it)

### Steps To Reproduce
1. open obs
2. add a browser source
3. you can't see anything

### Expected behavior
it should show things

### Screenshots
![image](https://github.com/user-attachments/assets/73877730-fa1c-4fd6-b85b-98333694ffb5)

### Additional context
i have an amd gpu and am using x11 not sure if either of those things are relevant

### Notify maintainers
@eclairevoyant
@jb55
@materusPL
@fpletz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[lily@dawn:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.3914.c3d4ac725177`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fpletz** [comment]
Unfortunately already known bug. WIP fix is in this PR: https://github.com/NixOS/nixpkgs/pull/317589. I will revisit that soon.

**Comment by TheAwesome98-Real** [comment]
oddly enough it randomly started working. it may have been switching to mate as opposed to lxqt that fixed it. either way i should close this since it's a duplicate anyway

**Comment by fpletz** [comment]
That is even more weird. :slightly_frowning_face:
