### ISSUE TITLE
Package request: bruno-cli

### ISSUE THREAD

**Issue by jtara1** [NixOS/nixpkgs#335270]
**Project description**
cli for bruno

cli alternative to bruno, the IDE for testing APIs

**Metadata**

* homepage URL: https://docs.usebruno.com/
* source URL: https://github.com/usebruno/bruno/tree/main/packages/bruno-cli
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by greg-hellings** [comment]
The existing [bruno package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix) includes only the graphical application. There is also a CLI interface that is available from the same source.

The current build process does create the bru executable at node_packages/.bin/bru, but it only includes a reference to the source folder calling its run command. I tried to create a PR to package the CLI executable in a separate output, but I could not figure out how to get an executable version that wasn't just a symlink back to the original file.

**Comment by gepbird** [comment]
I'll try to do this in a few hours/days, thanks for bumping this!

Even if they are built from the same source, I think we should create a different derivation for it. I'm looking at the output of `bruno` and I all the files look related to the GUI application, so sharing those files with `bruno-cli` wouldn't help with disk space. Maybe with build time it would be more efficient, but I (and presumably most end users and some maintainers) am not familiar with making a package produce multiple outputs where the user can choose which outputs he wants. And merging `bruno` and `bruno-cli` into one package would cause other `bruno` users to download extra files which they'll probably never use.

I'd love to hear other maintainers' opinions on how we should split the GUI and the CLI app. cc @mattpolzin @lucasew @kashw2 @water-sucks @redyf
