### ISSUE TITLE
cockroachdb relicense 23.1 series

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#335274]
## Issue description

Cockroachdb releases 23.1 and newer will stop using BSL and instead use the proprietary CockroachDB licenses. Please update `meta.licenses` to reflect that.

> With the introduction of version 24.3 in November, we are retiring our Core offering and introducing a new Enterprise licensing structure for self-hosted users, also applied to new patch releases of versions 23.1 and later. This new structure will provide all users with the robust database capabilities found previously only in the self-hosted Enterprise license. CockroachDB will remain entirely source code available. Note that there will be no change for customers of our cloud platform.

https://www.cockroachlabs.com/blog/enterprise-license-announcement/

## Maintainers

@rushmorem @thoughtpolice @neosimsim

**Comment by neosimsim** [comment]
@mweinelt IIUC BSL is not replaced but CockroachDB license is now added on top.
