### ISSUE TITLE
MACVLAN test fails since 0e7358002679ad7f35d2bd99977b9f0e403d4de2

### ISSUE THREAD

**Issue by Magnap** [NixOS/nixpkgs#33527]
## Issue description

The `nixos.tests.networking.scripted.macvlan` test fails on Hydra and since it's part of `nixos:trunk-combined:tested `, it's holding back `nixos-unstable`.
I bisected through the changes in [the earliest build where it started failing](https://hydra.nixos.org/build/67073527) and it appears that [the above-mentioned commit](https://github.com/NixOS/nixpkgs/commit/0e7358002679ad7f35d2bd99977b9f0e403d4de2) is to blame, as it's the first bad commit.
For completeness, I checked [the commit immediately prior](0ea0e3cf719e2a238ecd5e9918cc30e2b642cce4) and the test succeeds there.

### Steps to reproduce

    git checkout 0e7358002679ad7f35d2bd99977b9f0e403d4de2
    nix-build -A nixos.tests.networking.scripted.macvlan nixos/release-combined.nix

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.11, NixOS, 18.03pre124015.f59a0f7f1a6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-stable-17.09.2631.0653b73bf61, nixos-18.03pre124015.f59a0f7f1a6"`
 - channels(magnap): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Magnap** [comment]
For context, the changes on `nixos-unstable` that are being held back by this include the patches for #33414, which is why I was looking into this in the first place.

**Comment by fpletz** [comment]
@Magnap Thanks for reporting and for your investigative work this. I'll look into it.

In the future, please also mention the author of the commit. I only found this issue by chance.

**Comment by fpletz** [comment]
Reverted for now.

**Comment by Magnap** [comment]
Thanks for looking into it! I apologize for not mentioning you, I didn't have full confidence in having found the actual cause, so I didn't want to make it seem like I was blaming anyone. If there have been no regressions since [build 67244365](https://hydra.nixos.org/build/67244365) of `tested`, `nixos-unstable` should be able to advance now 😃

**Comment by Magnap** [comment]
The test now succeeds in [the latest build](https://hydra.nixos.org/build/67346645#tabs-summary).

**Comment by fpletz** [comment]
Thanks! I will try to update dhcpcd soon though because we should have the newest version for 18.03 but will check all tests first (only checked dhcp).
