### ISSUE TITLE
Update request: vscode 1.92.1 → 1.92.2

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#335356]
- Package name:`vscode`, `vscode-fhs`
- Latest released version: 1.92.2

- Current version on the unstable channel: 1.92.1
- Current version on the stable/release channel: 1.92.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@eadwu @Synthetica9 @bobby285271 @JohnRTitor 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Fixed in #334921

**Comment by Anifyuli** [comment]
Thanks Mister. I forget to check closed PR for `vscode` updates
