### ISSUE TITLE
Build failure: Pureref

### ISSUE THREAD

**Issue by wramzo** [NixOS/nixpkgs#335376]
hello, when I want to install the pureref, I get an error like this. When I execute the command specified in the error, I continue to get the same error.

### Build log:

```
[ramzo@nixos:/etc/nixos]$ nix-store --add-fixed sha256 /home/ramzo/PureRef-2.0.0_x64.appimage 
/nix/store/apnnd6bp9iac9wn2sxf049vcpvg62bmp-PureRef-2.0.0_x64.appimage
```

```
[ramzo@nixos:/etc/nixos]$ sudo nixos-rebuild switch
these 19 derivations will be built:
---
***
Unfortunately, we cannot download file PureRef-1.11.1_x64.Appimage automatically.
Please go to https://www.pureref.com/download.php to download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 PureRef-1.11.1_x64.Appimage
or
  nix-prefetch-url --type sha256 file:///path/to/PureRef-1.11.1_x64.Appimage

***

error: builder for '/nix/store/ga1h6s2d74xr313cibgly2fig8kbsqfa-PureRef-1.11.1_x64.Appimage.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/zcb97l11icjw2mdb8g15m84azxh7szcz-pureref-1.11.1-extracted.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9ricq9ms4x7823rc5ncin025gqs1gfn7-pureref-1.11.1-init.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dwpx4yrhxjlbqxdxpadmfbn81014i3sm-pureref-1.11.1-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jcsrgci6a7czc0k78lg3myz3apz1y978-pureref-1.11.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rsppfl8x4a2qn2gn8k5vhx6l9qmxy84x-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mfw81fkb4gvqdhxy5jmlpq3j7d7dgpcq-nixos-system-nixos-23.11.7777.7144d6241f02.drv' failed to build
```

**Comment by ghpzin** [comment]
Your downloaded file:
`PureRef-2.0.0_x64.appimage`
File mentioned in warning:
`PureRef-1.11.1_x64.Appimage`
Seems like you can change downloaded version at the top left on pureref website.

Also you are using EOL version of nixos (`nixos-23.11.7777.7144d6241f02`), you may want to update to one of the current version (`nixos-24.05` or `nixos-unstable`).
`pureref` was converted to autodownload a while ago, thought current version is still `1.11.1`

**Comment by ElnuDev** [comment]
(I am the maintainer of pureref) Jumping on this issue, but even with 1.11.1 the pureref package is now broken. It seems like the pureref team has silently changed the binary for the old version.

```
error: hash mismatch in fixed-output derivation '/nix/store/i7qx0faca3fnznkxh0mq9rd8b372zx3c-PureRef-1.11.1_x64.Appimage.drv':
         specified: sha256-da/dH0ruI562JylpvE9f2zMUSJ56+T7Y0xlP/xr3yhY=
            got:    sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
```

I'll try and put together a PR to bump pureref to the latest 2.0.2 today.

@wramzo In future please ping maintainers when opening an issue as mentioned in the issue template, thanks!

**Comment by ElnuDev** [comment]
@wramzo 2.0.2 should be merged soon https://github.com/NixOS/nixpkgs/pull/338039
