### ISSUE TITLE
Update request: kodi 21.0 → 21.1

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#335370]
- Package name: kodi
- Latest released version: 21.1
- Current version on the unstable channel: 21.0
- Current version on the stable/release channel: 21.0
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@aanderse  
@cpages  
@dschrempf  
@edwtjo  
@minijackson  
@peterhoeg  
@sephalon

Release: https://github.com/xbmc/xbmc/releases/tag/21.1-Omega

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aanderse** [comment]
thanks for the ping! i am on it in the next day or two
