### ISSUE TITLE
Haskell `shellFor`: native libraries are no longer found

### ISSUE THREAD

**Issue by amesgen** [NixOS/nixpkgs#335387]
## Issue description

Suppose you have a project with some native dependency like
```cabal
extra-libraries: z
```
and try to `cabal build` inside of a `shellFor` like this:
```nix
shellFor {
  packages = p: [ p.stuff ];
  buildInputs = [ pkgs.zlib ];
  nativeBuildInputs = [ pkgs.cabal-install ];
}
```
Before #296645, this worked fine, but since #296645, building fails:
```
Error: [Cabal-4345]
Missing dependency on a foreign library:
* Missing (or bad) C library: z

Error: [Cabal-7125]
Failed to build stuff-0.1.0.0. The failure occurred during the configure step.
```

### Steps to reproduce

Minimal reproducible example is in https://github.com/amesgen/stuff/tree/nixpkgs-haskell-shellFor-gcc-bug

```console
 $ git clone https://github.com/amesgen/stuff --single-branch --branch nixpkgs-haskell-shellFor-gcc-bug && cd stuff
 $ nix flake metadata . | grep 'nixpkgs-.*:'
├───nixpkgs-bad: github:NixOS/nixpkgs/c20c714d7cdf582c9c9db6bdac37c407d33d1789
└───nixpkgs-good: github:NixOS/nixpkgs/3259cf03626f8fd2f54c67becd531b9276885a64
 $ nix develop .#good -c bash -c 'cabal clean; cabal build'
# works fine
 $ nix develop .#bad -c bash -c 'cabal clean; cabal build'
# fails with
Error: [Cabal-4345]
Missing dependency on a foreign library:
* Missing (or bad) C library: z
```

## Technical details

I only tested this on `x86_64-linux`.

Running `nix-diff` for the example above
```console
 $ nix build --no-link .#devShells.x86_64-linux.good .#devShells.x86_64-linux.bad
 $ nix-diff $(nix eval --raw .#devShells.x86_64-linux.good) $(nix eval --raw .#devShells.x86_64-linux.bad)
```
shows that `/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0` is missing from `allowedRequisites` and `defaultNativeBuildInputs`. Indeed, adding `gcc` to the `shellFor` resolves the problem:
```diff
diff --git a/flake.nix b/flake.nix
index 823cd66..cf47ff5 100644
--- a/flake.nix
+++ b/flake.nix
@@ -17,7 +17,7 @@
         in
         hsPkgs.shellFor {
           packages = p: [ p.stuff ];
-          buildInputs = [ pkgs.zlib ];
+          buildInputs = [ pkgs.zlib pkgs.gcc ];
           nativeBuildInputs = [ pkgs.cabal-install ];
         };
     in
```

**Comment by amesgen** [comment]
cc @Stunkymonkey @maralorn

**Comment by maralorn** [comment]
Interesting. Especially since we decided against using runCommandNoCC but somehow arrived at similar behavior.

Sorry we broke this.

I wonder what the best fix is. Should shellFor just always add the GCC dep? Or should gcc maybe become a runtime dependency of cabal-install since apparently that's actually what's going on here?

**Comment by sternenseemann** [comment]
`runCommand == runCommandNoCC`.

```nix
  # Docs in doc/build-helpers/trivial-build-helpers.chapter.md
  # See https://nixos.org/manual/nixpkgs/unstable/#trivial-builder-runCommand
  runCommand = name: env: runCommandWith {
    stdenv = stdenvNoCC;
    runLocal = false;
    inherit name;
    derivationArgs = env;
  };
```

**Comment by maralorn** [comment]
That’s an explanation, thank you! Now the question: What is the correct way to get gcc into scope? I guess the most pragmatic way is to just add it as a dependency of runCommand, but it feels like that is a bit wrong.

**Comment by sternenseemann** [comment]
`runCommandCC` should work…

**Comment by maralorn** [comment]
Still not convinced, that’s a clean solution. But yeah, I’ll do that.

**Comment by sternenseemann** [comment]
Why wouldn't that be a clean solution? The C compiler is part of `stdenv`, so we need to make sure the environment also uses the default `stdenv` that actually has one.

**Comment by maralorn** [comment]
I just wasn’t sure whether every shell should contain stdenv. But I guess that’s kinda stupid.
