### ISSUE TITLE
Update request: osu-lazer 2024.731.0 → 2024.817.0

### ISSUE THREAD

**Issue by creeperkafasi** [NixOS/nixpkgs#335437]
- Package name: osu-lazer
- Latest released version: 2024.817.0

- Current version on the unstable channel: 2024.731.0
- Current version on the stable/release channel: 2024.521.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@gepbird 
@thiagokokada 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/335097 and https://github.com/NixOS/nixpkgs/pull/335262. Please wait a few hours/days for these to reach unstable.

**Comment by creeperkafasi** [comment]
> Done in #335097 and #335262. Please wait a few hours/days for these to reach unstable.

Sorry, I was tired and forgot to check closed issues as well. Thanks for the clarification.
Closing this issue.

**Comment by creeperkafasi** [comment]
Closing this issue.
