### ISSUE TITLE
python.pkgs.numpy: update to 1.14.0

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#33559]
## Issue description

Updating to 1.14.0 causes some breakage.

- h5py: https://github.com/h5py/h5py/issues/969
- datashape: https://github.com/blaze/datashape/issues/232

**Comment by jyp** [comment]
This issue is stalling updating to tensorflow 1.5.

**Comment by FRidh** [comment]
I won't upgrade numpy until at least h5py has resolved the issue. Preferably datashape is fixed as well before we update, but the datashape repo is not that active anymore.

**Comment by jyp** [comment]
@FRidh Fair enough, I opened #34418 anyway so interested people can find the branch easily. Hopefully h5py won't take too long to update.

**Comment by FRidh** [comment]
Fix for h5py 5009e062a6f7d4e074cab0fcb42a780ac2b1d7d4

**Comment by FRidh** [comment]
1.14.0 is in staging. Note that it may take some time for staging to reach master. Also, by then it will likely be 1.14.1 anyway in which case these issues here don't matter anymore.

**Comment by dotlambda** [comment]
Should we mark datashape as broken? The tests that fail look like they really shouldn't fail:
https://github.com/blaze/datashape/blob/6cef7af5abc8b7eef4867bb85eb03eb2cf28f83d/datashape/tests/test_user.py#L8-L16

**Comment by FRidh** [comment]
Upstream datashape/blaze does not seem very active anymore so marking them as broken may make sense to do.  However, the tools do work just fine, so in this case I'm of the opinion we should simply disable the (specific) tests.

**Comment by FRidh** [comment]
Numpy is in, so closing.
