### ISSUE TITLE
Flatpaks not working with KDE Discover

### ISSUE THREAD

**Issue by natwat123** [NixOS/nixpkgs#335696]
### Describe the bug
I added discover and flatpak to the config after installing installing v24.05. Packages were initially showing up in Discover but it stopped working all of as sudden.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. I added to kdePackages.discover and flatpak to environment.systemPackages = with pkgs within configuration.nix.
2. Used sudo nixos-rebuild and rebooted my PC.
3. Opened Discover and pressed add flathub.
4. Browsed the available flatpaks and closed the app.
5. I reopened Discover and was greeted by an "NixOS is not configured for installing apps through Discover"
6. I opened Discover settings to install my prefer module as directed but it's blank.

### Expected behaviour
When doing this on v23 it worked with no issue. The apps would install and run fine.

### Screenshots
![Screenshot_20240818_212856](https://github.com/user-attachments/assets/eb9f8380-ba97-471a-99b7-f65299e51697)
![Screenshot_20240818_230748](https://github.com/user-attachments/assets/f7435a19-6119-4e51-a81d-bcfc8247b121)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.33, NixOS, 24.05 (Uakari), 24.05.1409.cc54fb41d137`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
> I added to kdePackages.discover and flatpak to environment.systemPackages = with pkgs within configuration.nix

What happens if instead you enable flatpaks with:

    services.flatpak.enable = true; 

in your `configuration.nix`?

**Comment by eclairevoyant** [comment]
https://github.com/KDE/discover/blob/6254dd2e71c6ee847817ca05eedc5801f837548a/discover/DiscoverObject.cpp#L180-L182 indicates there's no discover backend available, which means you need to  make one available. Most likely this should be sorted by the instructions above.

**Comment by natwat123** [comment]
This worked thanks.
