### ISSUE TITLE
GDM provides a fingerprint login even if it's disabled via security.pam.services.login.fprintAuth

### ISSUE THREAD

**Issue by adityarsuryavamshi** [NixOS/nixpkgs#335681]
### Describe the bug

Previously fingerprint auth could be disabled only for login via `security.pam.services.login.fprintAuth`. But currently even if it is set to false, gdm still allows for logging in with fingerprint.

### Steps To Reproduce
1. Use GDM as the displaymanager
2. Enable fingerprint with `services.fprintd.enable = true` (along with the necessary drivers)
3. Disable fingerprint for login with `security.pam.services.login.fprintAuth = false`

### Expected behavior

GDM should only allow for login via password and not allow to login with fingerprint

### Screenshots

N/A

### Additional context

I think this affects other display managers also, I tried `ly` and two different greeters with `greetd` but they could be disabled independently by setting `security.pam.services.<dm_name>.fprintAuth = false`. But with gdm this doesn't work.

### Notify maintainers

@eclairevoyant , @jtojnar , @bobby285271
Unsure who is the right maintainer for this, but tagging last couple of committers. Please tag the right person, if these are not the right maintainers. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.11 (Vicuna), 24.11pre668102.a0d6390cb3e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adityarsuryavamshi** [comment]
I think the issue is because of this PR https://github.com/NixOS/nixpkgs/pull/321591/ from @JohnRTitor .
In particular due to https://github.com/NixOS/nixpkgs/blob/a0d6390cb3e82062a35d0288979c45756e481f60/nixos/modules/services/x11/display-managers/gdm.nix#L330-L332.               
I'm guessing this enables gdm-fingerprint `mkIf config.services.fprintd.enable`, i.e, it unconditionally enabled gdm-fingerprint if fprintd is enabled without considering additional cases where login.fprintAuth is true.                 
That also probably explains why this is present with other display managers maybe?

**Comment by eclairevoyant** [comment]
I don't know anything about GDM; as the file mentions:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/gdm.nix#L60

you meant to tag @NixOS/gnome

**Comment by JohnRTitor** [comment]
`config.security.pam.services.login.fprintAuth` does not control whether GDM fingerprint login enabled for GDM. 
https://github.com/NixOS/nixpkgs/blob/67c501fcd095bbbc08372ec23d7b61c13b3d86c8/nixos/modules/services/x11/display-managers/gdm.nix#L330

In fact is already disabled as it would cause issues for fingerprint login, GDM implements it differently.

I believe you can disable it by setting the `gdm-fingerprint` pam config to a empty string.

```
security.pam.services.gdm-fingerprint.text = lib.mkForce "";
```

**Comment by adityarsuryavamshi** [comment]
I've verified that the workaround of setting gdm-fingerprint pam to empty works.       
I think I was under the impression that `login` refers to all types of login including via display managers, not particularly to the login command which seems to be the case, which does make sense.
Closing the issue, thanks @JohnRTitor !

**Comment by agvantibo-again** [comment]
> I believe you can disable it by setting the `gdm-fingerprint` pam config to a empty string.

Is there a way to disable gdm-fingerprint and not get a fingerprint-related error every login? I've included this line in my system configuration, and now every login attempt GDM would show me a message that fingerprint authentication has failed.
