### ISSUE TITLE
azure-cli: `user ... does not exits in MSAL token cache`

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#335750]
### Describe the bug

Trying to run an action with azure-cli that requries authentication, az will fail to read the cached authentication token from the token cache:

```
User 'xxx' does not exist in MSAL token cache. Run `az login`.
```

This is due to a version mismatch of `python312Packages.msal`.

https://github.com/NixOS/nixpkgs/pull/335225 will update the package, I checked that the authentication works afterwards.

### Notify maintainers

That's me! @katexochen 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source````
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gordon-BP** [comment]
I also experience this issue with `azure-cli`, as well as with `azure-cli-extensions`. Thanks for adding the fix!
