### ISSUE TITLE
Firefox crashes on wayland with NVIDIA due egl-wayland update and related sync issue

### ISSUE THREAD

**Issue by oddlama** [NixOS/nixpkgs#335791]
### Describe the bug

Firefox crashes on wayland when using an NVIDIA card through egl-wayland. This issue has been partially addressed upstream and on other distributions, some patches are available. Refer to:

- https://gitlab.freedesktop.org/mesa/mesa/-/issues/11541
- https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/issues/7

### Steps To Reproduce
1. Launch firefox on wayland with egl-wayland (NVIDIA)
2. Toggle fullscreen -> crash

### Notify maintainers

@edolstra @lovesegfault @mweinelt 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
```
firefox-unwrapped> In file included from Unified_cpp_webrender_bindings0.cpp:29:
firefox-unwrapped> /build/firefox-129.0.1/gfx/webrender_bindings/RenderCompositorEGL.cpp:162:13: error: use of undeclared identifier 'MozContainerSurfaceLock'
firefox-unwrapped>   162 |   UniquePtr<MozContainerSurfaceLock> lock;
firefox-unwrapped>       |             ^
firefox-unwrapped> /build/firefox-129.0.1/gfx/webrender_bindings/RenderCompositorEGL.cpp:164:23: error: no member named 'LockSurface' in 'mozilla::widget::GtkCompositorWidget'
firefox-unwrapped>   164 |     lock = gtkWidget->LockSurface();
firefox-unwrapped>       |            ~~~~~~~~~  ^
```

```nix
(fetchpatch {
  name = "nvidia-egl-wayland-compat.patch";
  url = "https://hg.mozilla.org/mozilla-central/raw-rev/eb230ecdf8eb";
  hash = "sha256-IaLltxf5W1WEzxvbi10wphqXVQPtBiLc2zlk38CIiz4=";
})
```

The patch does not apply on any of the source builds we have. Will have to recheck tomorrow.
