### ISSUE TITLE
Build failure: libmd

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#335730]
### Steps To Reproduce

1. build libmd

### Build log

```
--- sha512c.o ---
-error=int-in-bool-context -Wno-error=memset-elt-size -Wno-error=noexcept-type -Wno-error=nonnull -Wno-error=pointer-compare -Wno-error=stringop-overflow -Wno-error=aggressive-loop-optimizations -Wno-error=cast-function-type -Wno-error=catch-value -Wno-error=multistatement-macros -Wno-error=restrict -Wno-error=sizeof-pointer-memaccess -Wno-error=stringop-truncation -Wno-return-type -Wno-system-headers -Wno-system-headers -Wno-address-of-packed-member  -Wno-unused-result    -I/legacy/usr/include -Werror=implicit-function-declaration -Werror=implicit-int  -Werror=return-type -Wundef -DHAVE_NBTOOL_CONFIG_H=1 -I/build/libmd-filtered-src/tools/build/cross-build/include/linux -D_GNU_SOURCE=1 -I/build/libmd-filtered-src/tools/build/cross-build/include/common -c /build/libmd-filtered-src/sys/crypto/sha2/sha512c.c -o sha512c.o
/build/libmd-filtered-src/sys/crypto/sha2/sha512c.c:45:10: fatal error: machine/ifunc.h: No such file or directory
   45 | #include <machine/ifunc.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [sha512c.o] Error code 1
```

### Additional context

Found when trying to use `pkgsCross.x86_64-freebsd` on aarch64-linux.

### Notify maintainers

@primeos

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.05 (Uakari), 24.05.20240719.0c53b6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/home/ross/.cache/nixpkgs-review/pr-335703/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
`pkgsCross.x86_64-freebsd.libmd` build both on `master` (e876aa267749fc5c51625dd71a2cc53b744d0857) and `release-24.05` (382146388d2707567518d1206e0e9b723c24bca4), can you clarify what exact command was run and on what nixpkgs revision?

**Comment by RossComputerGuy** [comment]
I did a regular nix build for `pkgsCross.x86_64-freebsd.llvmPackages.compiler-rt` in a nixpkgs-review for #335703

**Comment by eclairevoyant** [comment]
Builds fine for me on both `master` and on that `freebsd-compiler-rt-again` branch :thinking:

**Comment by artemist** [comment]
The actual problem is in the native `freebsd.libmd` on aarch64-linux, before doing any sort of cross builds.

Setting `BOOTSTRAPPING` fixes this since it disables using intrinsics. That's probably the right approach here, I'll submit a PR once I know there aren't any other similar issues to fix
