### ISSUE TITLE
Update request: pcsx2 2.1.17 → 2.1.98

### ISSUE THREAD

**Issue by damiankorcz** [NixOS/nixpkgs#335956]
- Package name: pcsx2
- Latest released version: 2.1.98

- Current version on the unstable channel: 2.1.17
- Current version on the stable/release channel: 1.7.5587

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@AndersonTorres @hrdinka @GovanifY @matteo-pacini

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
As you wish:
https://github.com/NixOS/nixpkgs/pull/336420
