### ISSUE TITLE
Package request: Zen browser

### ISSUE THREAD

**Issue by nonetrix** [NixOS/nixpkgs#335984]
**Project description**

Zen browser is a Firefox based browser somewhat like Vivaldi or Floorp

**Metadata**

* homepage URL: https://www.zen-browser.app/
* source URL: https://github.com/zen-browser/desktop
* license: Mozilla Public License 2.0
* platforms: Linux, MacOS, Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by edmundmiller** [comment]
Looks like a duplicate? https://github.com/NixOS/nixpkgs/issues/327982

**Comment by nonetrix** [comment]
Sorry Github issue search is useless how did that not even come up?
