### ISSUE TITLE
Package request: Phidget

### ISSUE THREAD

**Issue by seofernando25** [NixOS/nixpkgs#335946]
**Project description**

Phidgets are building-blocks for sensing and control using a computer, tablet, or phone. Phidgets enable your software application to interact with the physical world.

**Metadata**

* homepage URL: https://www.phidgets.com/
* source URL: 
 - https://www.phidgets.com/docs/OS_-_macOS
 - https://www.phidgets.com/docs/OS_-_Linux

* license: LGPL-3.0-or-later and BSD-2-Clause and BSD-3-Clause
* platforms: Linux, Darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mksafavi** [comment]
Hi.
Could you try https://github.com/NixOS/nixpkgs/pull/337398 this to see if it works for you? 
It only contains the `libphidget22` and `libphidget22extra`

**Comment by seofernando25** [comment]
Thank you I didn't see this!

**Comment by mksafavi** [comment]
> Thank you I didn't see this!

Let's keep the issue open until it's merged.

Let me know if you could test it and whether it worked or not.
