### ISSUE TITLE
Package request: Goverlay 0.7.1 -> 1.2

### ISSUE THREAD

**Issue by mateowoetam** [NixOS/nixpkgs#335978]
Update request: Goverlay 0.7.1 -> 1.2

  -  Package name: Goverlay
  - Latest released version: 0.7.1

   - Current version on the unstable channel: 0.7.1
   - Current version on the stable/release channel: 0.7.1
   
- [x]   Checked the nixpkgs pull requests (there is a failed pull request to v0.9.1)

* homepage URL: https://github.com/benjamimgois/goverlay
* source URL: https://github.com/benjamimgois/goverlay/
* license: GPL-3.0
* platforms: linux

 **Notify maintainers**

**@kira-bruneau** 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
Currently, the latest version depends on libqt6pas which isn't packed in nixpkgs, but should once #324035 is merged.
