### ISSUE TITLE
Unable to update suwayomi-server by setting package field

### ISSUE THREAD

**Issue by Zettexe** [NixOS/nixpkgs#335933]
### Describe the bug
Unable to update suwayomi-server by setting package field as such:
```
suwayomi-server = {
  enable = true;
  package = pkgs.unstable.suwayomi-server;
};
```

### Steps To Reproduce
1. Set package to unstable
2. Service is not updated

### Expected behavior
Suwayomi Server should be running using the unstable package

### Notify maintainers

@RatCornu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.20240704.c0d0be0`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
How do you know it's not updated?

**Comment by Zettexe** [comment]
Says the server version in the WebUI, also the script that systemd runs is pointing to v1.0.0

**Comment by Zettexe** [comment]
Not sure what more information you need but, this repo has my entire nix config as it is currently https://codeberg.org/Zettexe/nixos-desktop-config

**Comment by RatCornu** [comment]
I checked your configuration and everything seemed alright, but I found out that you updated your flakes input before I committed the version 1.1.1 of suwayomi-server into nixpkgs! You can update your inputs with `nix flake update`, or just the unstable input with `nix flake update nixpkgs-unstable`. Hope that will solve it!

**Comment by Zettexe** [comment]
Yep, that was the issue. Guess I somehow managed to catch that it was updated on search.nixos.org but not my local machine.
