### ISSUE TITLE
element-desktop: warning: "Element does not support this browser"

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#335955]
### Describe the bug
After updating to 1.11.74 on the stable channel (24.05),
the following warning appears when launching Element desktop:

> Element does not support this browser
>
> If you continue, some features may stop
> working and there's a risk that you may lose
> data in the future. Update your browser to
> continue using Element.
>
> [Learn more] [Dismiss]

This is not blocking, but implies that something may break in the future (?)

### Steps To Reproduce
1. Start `element-desktop` on the stable channel.
2. Notice warning.

### Expected behavior
No warning.

### Screenshots
![17241132794171](https://github.com/user-attachments/assets/01f59629-b9e3-48e8-abcd-01f5d2e3403f)

### Additional context
- `element-desktop` 1.11.74
- running with `electron` 30.3.1

### Notify maintainers
- @Ma27
- @fadenb
- @mguentner
- @Ralith
- @dali99
- @sumnerevans
- @NickCao
- @teutat3s

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.20240817.c42fcfb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/i1aw9jjgxcvyd642s12kw3iasmarwd42-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teutat3s** [comment]
This warning should go away once https://github.com/NixOS/nixpkgs/pull/333907 and https://github.com/NixOS/nixpkgs/pull/336018 are merged and built by hydra:
https://nixpk.gs/pr-tracker.html?pr=333907
https://nixpk.gs/pr-tracker.html?pr=336018
