### ISSUE TITLE
`boot.tmp.cleanOnBoot` is `false` by default, whereas user expectation is that NixOS cleans on boot (`true`).

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixpkgs#336089]
### Describe the bug
By default, `/tmp` is not cleaned on boot, which is not what users expect because now it is not temporary storage.

### Steps To Reproduce
1. Reboot
2. `/tmp` is not cleared

### Expected behavior
`/tmp` should be cleaned on boot by setting `boot.tmp.cleanOnBoot` to `true` by default. For niche usecases, it can still be configured by users to be `false`.

### Additional context
Virtually every other distro cleans /tmp/ on every boot. We should not do things that users do not expect. `/tmp` not being, well, temporary, is such an unexpected thing.

### Notify maintainers
@SuperSandro2000 @stuebinm 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheAwesome98-Real** [comment]
technically the user would expect /tmp to actually be a tmpfs, but this isn't a great idea on nixos since nix uses it for temporary files and can break if the tmpfs runs out of space

**Comment by ahydronous** [comment]
You are totally right!
I did a quick bit of searching and I found this little blurb on lobste.rs

```

**Comment by TheAwesome98-Real** [comment]
oh, that's a good idea! does `tmp.cleanOnBoot` clean `/var/tmp` in that case, then?

**Comment by ahydronous** [comment]
It does not, but it isn't supposed to either. `/var/tmp` isn't meant to be cleaned automatically, and according to the File Hierarchy System is suppose to be for large temporary files that aren't cleaned on boot.
Perhaps Nix its garbage collection will automatically remove the entries, I am not sure.

**Comment by SuperSandro2000** [comment]
Can you send a PR which changes the default and a release notes entry?

**Comment by ahydronous** [comment]
https://github.com/NixOS/nixpkgs/pull/338181

Here is the PR, but I am not sure how to make a release note or how to get that in the proper place..

**Comment by ahydronous** [comment]
The above draft PR has some good reasonings why /tmp on a tmpfs works better than cleaning boot on every boot cycle. Closing this for now.
