### ISSUE TITLE
Package request: stylix

### ISSUE THREAD

**Issue by dieBakterie** [NixOS/nixpkgs#336016]
**Project description**

**Metadata**

* homepage URL: https://stylix.danth.me/
* source URL: https://github.com/danth/stylix.git
* license: mit
* platforms: unix, linux, darwin, nix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
why? you can use `flake` with stylix.

**Comment by NobbZ** [comment]
`stylix` is much more than a package, and I think that including it into nixpkgs/NixOS directly, requires much more work than just adding a "build recipe" and a module. There is also a lot of documentation to transfer over (we don't want to repeat the yarn2nix debacle, don't we).

If this really is a wanted thing, then in my opinion the stylix maintainer (@danth) has to be a big part of the work.

I also think that a tight integration slows down the potential of stylix, as its further development will have to be tied to the nixpkgs release cycle.

**Comment by s0me1newithhand7s** [comment]
> `stylix` is much more than a package, and I think that including it into nixpkgs/NixOS directly, requires much more work than just adding a "build recipe" and a module. There is also a lot of documentation to transfer over (we don't want to repeat the yarn2nix debacle, don't we).
> 
> If this really is a wanted thing, then in my opinion the stylix maintainer (@danth) has to be a big part of the work.
> 
> I also think that a tight integration slows down the potential of stylix, as its further development will have to be tied to the nixpkgs release cycle.

+ `stylix` and `home-manager` integration..

**Comment by NobbZ** [comment]
Oh, there is HM integration? That would probably not be coverable by the direct NixOS integration, so yes, that would still remain in an external repository and therefore would cause some split effort.

**Comment by s0me1newithhand7s** [comment]
> Oh, there is HM integration? That would probably not be coverable by the direct NixOS integration, so yes, that would still remain in an external repository and therefore would cause some split effort.

yep, `stylix` [works](https://stylix.danth.me/options/hm.html) with `home-manager` - and i suppose that adding it into `nixpkgs` may and will break this.

**Comment by s0me1newithhand7s** [comment]
> It's that i'm tried anything in the docs to add/install stylix and norhing worked. Sorry for the trouble and the late reply. I haven't really thought before opening this issue and i'm kinda new to NixOS.Sorry again for the trouble.

no, it's alr to ask help, but not in this kind. if you seek for help with `flake`s, `stylix` and etc - welcome to the discord server, matrix space. you can close this issue and feel free to join us. :D

**Comment by dieBakterie** [comment]
Thanks and sorry for the trouble would be nice to have this in the nixpkgs but din't knew it's this problematic. Will close this then for now.
