### ISSUE TITLE
Update request: mupdf 1.23.6 → 1.24.8

### ISSUE THREAD

**Issue by sents** [NixOS/nixpkgs#336153]
- Package name: MuPDF
- Latest released version: 1.24.8

- Current version on the unstable channel: 1.23.6
- Current version on the stable/release channel: 1.23.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

This would be nice because it is required to update zathuras mupdf plugin (#334368) which in turn 
would make zathura stop segfaulting if zooming or scrolling too fast on pdfs.

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Already updated, please search PRs next time.
#332385
