### ISSUE TITLE
Warp-taskbar crashes because GTK or does not find its files.

### ISSUE THREAD

**Issue by pxp9** [NixOS/nixpkgs#336280]
### Describe the bug
Warp-taskbar does not open beacuse a GTK assertion.

### Steps To Reproduce

I am using a `flake.nix` with the nixpkgs inputs are on master branch.

```nix
nixpkgs.url = "github:nixos/nixpkgs/master";
```

Also I have tried with `nixos-unstable` branch.

1.  Put the following snippet in you conf

```nix
systemd.packages = [ pkgs.cloudflare-warp ]; # for warp-cli
systemd.targets.multi-user.wants = [ "warp-svc.service" ]; # causes warp-svc to be started automatically
services.cloudflare-warp.enable = true;

environment.systemPackages = [ pkgs.cloudflare-warp ]; # for warp-svc
```
or

```nix
environment.systemPackages = [ pkgs.cloudflare-warp ]; # for warp-svc
```

### Expected behavior

The expected behavior when you install the package `cloudflare-warp` is that you can open `warp-taskbar` program (2nd conf snippet). As you can see in first screenshot, it complains about a folder. Probably because conf of this program is not binded to `/usr`.

As it is explained in this issue #323580.

for some reason this behavior is different if you enable `warp` service (1st conf snippet).

### 2nd conf behavior

![image](https://github.com/user-attachments/assets/5933cb23-5345-4e73-b28d-c11833a2dda0)

#### A capture of the journal

![image](https://github.com/user-attachments/assets/f20e4fc9-1cfd-462e-a3d4-bd7a30849d6d)

### Additional context
this a new issue because @marcusramberg wants to close previous one #213177.

### Notify maintainers

@marcusramberg 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pxp9** [comment]
behavior of the service is different in master branch and nixos unstable for some reason

## nixos unstable behavior.

Service launches but `warp-taskbar` not.

![image](https://github.com/user-attachments/assets/0c365cdd-d636-4d9f-93c5-bd4229597d64)

## nixos master behavior

Services not launches as you can see in the `journal` screenshot.

**Comment by marcusramberg** [comment]
You'll have to use the included warp-taskbar user service which works around the hard-coded `/usr` bindings. I have a PR up to bump cloudflare-warp to the latest release btw, https://github.com/NixOS/nixpkgs/pull/336116

**Comment by pxp9** [comment]
could you do a mini conf snippet ?

> You'll have to use the included warp-taskbar user service which works around the hard-coded `/usr` bindings. I have a PR up to bump cloudflare-warp to the latest release btw, #336116

**Comment by marcusramberg** [comment]
> could you do a mini conf snippet ?
> 
> > You'll have to use the included warp-taskbar user service which works around the hard-coded `/usr` bindings. I have a PR up to bump cloudflare-warp to the latest release btw, #336116

I guess it depends on how you manage user config. 

You can just `systemctl --user enable --now warp-taskbar` tho.

**Comment by pxp9** [comment]
I have managed to enable and start it but i dont know how it works. There is no any logo as your screenshot of the previous issue.

![image](https://github.com/user-attachments/assets/2c7de4a0-414d-4e50-b7d4-df4602694a13)

**Comment by pxp9** [comment]
Also , how is the proper way to do it with home-manager ?

**Comment by pxp9** [comment]
when i try to register with warp-cli

this happens

![image](https://github.com/user-attachments/assets/5a27ade5-b711-4171-add5-95629aabde6a)

**Comment by marcusramberg** [comment]
Not sure about home-manager, but you can enable the user unit from your nixos configuration like this:

```
  systemd.packages = [ pkgs.cloudflare-warp ];
  systemd.user.services.warp-taskbar.wantedBy = [ "graphical.target" ];
```

^^ This might be a good candidate for inclusion in the warp module, @treyfortmuller ?

The other problems (not being able to open a browser/not getting the widget) seems like problems with your wm configuration and not cloudflare-warp. I've tested it to work in both gnome and hyprland.

**Comment by pxp9** [comment]
how do you make it work in gnome ??

What do you think I miss configured ?

**Comment by marcusramberg** [comment]
Did you enable the AppIndicator Support extension? The registration issue seems to be related to not having configured a default browser somehow. At least both of those work for me without issue, I haven't done anything special. I was under the assumption that you were using a more bare-bones wm based on the Couldn't register callback error above. Anyways, I'm going to close this as desktop configuration support kinda falls outside of the cloudflare-warp package.

This opens a browser just fine for me:

![image](https://github.com/user-attachments/assets/ce4ae919-4c01-4923-99b2-1aa5e15cfa43)

**Comment by pxp9** [comment]
Hi, I have researched , once i have installed AppIndicator Support extension and enabled in gnome extensions.

I got this behavior

it could not write something, somewhere in the filesystem but it actually register and it is working. As you can see in the image.

but now the app is working.

> when i try to register with warp-cli
> 
> this happens
> 
> ![image](https://private-user-images.githubusercontent.com/48651252/359871186-5a27ade5-b711-4171-add5-95629aabde6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTA5NjIsIm5iZiI6MTcyNDYxMDY2MiwicGF0aCI6Ii80ODY1MTI1Mi8zNTk4NzExODYtNWEyN2FkZTUtYjcxMS00MTcxLWFkZDUtOTU2MjlhYWJkZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE4MzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYzUyODIyZWM4NDU2NWRkYWRjM2NmYjNlZTg0YmU0YWFiNGEyNGM2ZDI0NzJhOTFkNjQ4NmYwMzY5MzA0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydMNniAW36Opf86I9UpyXbutStbYgE3RLp83ZVEqTyA)


I think i might have something more missconfigured.

Thanks for your assitance.
