### ISSUE TITLE
Package request: Ente Auth 

### ISSUE THREAD

**Issue by Brojan96** [NixOS/nixpkgs#336291]
**Project description**

Ente's 2FA app. An end-to-end encrypted, cross platform and free app for storing your 2FA codes with cloud backups. Works offline. You can even use it without signing up for an account if you don't want the cloud backups or multi-device sync.

**Metadata**

* homepage URL: [https://auth.ente.io](https://auth.ente.io)
* source URL: [https://github.com/ente-io/ente/tree/main/auth](https://github.com/ente-io/ente/tree/main/auth)
* license:  AGPL-3.0 license
* platforms: linux, windows, android, ios, apple silicon macOS, web

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by universish** [comment]
**Ente Auth**

**Project description**

Authenticator App

It is the only authenticator program that works on all desktop and mobile platforms. It is a very useful application as it works on all operating systems and all platforms, and also works on the web. Moreover, since the database is in the cloud, there is no need to back up or restore from backup.

**Metadata**

    homepage URL: https://ente.io/auth/
    source URLs: https://github.com/ente-io/ente/tree/main/auth ; https://github.com/flathub/io.ente.auth
    download URLs: https://github.com/ente-io/ente/releases?q=tag%3Aauth-v4 ; https://ente.io/auth/ ; https://github.com/flathub/io.ente.auth ; https://flathub.org/apps/io.ente.auth ; https://f-droid.org/tr/packages/io.ente.auth/
    license: AGPL-3.0
    platforms: gnu-linux, gnu-linux libre, flathub, net (ms's), darwin (apple's), android, web
    distribution format of software: appimage, flatpak, rpm, deb, pacman, dmg, exe, apk
    OSs: GNU/Linux distros, GNU/Linux Libre distros, Windows, MacOS, iOS, android OS (f-droid and play store), web

**Comment by MithicSpirit** [comment]
@universish it has already been added. If you're on a stable release, you'll have to wait until the next one for it to be included, or bring it in from unstable.

**Comment by universish** [comment]
not added. not yet published, not yet distributed. can you give me a url to verify your claim?

The topic was already opened, I opened it again, but I added detailed metadata data because the previous topic contained very insufficient information.

**Comment by MithicSpirit** [comment]
> not added. not yet published, not yet distributed. can you give me a url to verify your claim?

[Here](https://search.nixos.org/packages?channel=unstable&show=ente-auth) and [here](https://nixpk.gs/pr-tracker.html?pr=339059). It was in #339059, which was merged 3 weeks ago, so it has already been distributed on the nixos-unstable channel (which lags roughly 3 days behind master). From the discussion in #350413, it seems like this package won't be backported, so you'll have to wait until 24.11 if you want it in a stable release (though you can manually pull in a dep from nixpkgs-unstable if you want it sooner).

**Comment by universish** [comment]
sorry, I searched for a stable version. unstable didn't come to mind.
