### ISSUE TITLE
superfluous dependency on zfs-util of grub

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#33628]
At the moment grub2 has unconditional dependency on zfs. See file pkgs/tools/misc/grub/2.0x.nix:
```
 , zfsSupport ? true
```

I believe this is wrong, because there is a configuration option:

boot.loader.grub.zfsSupport
Whether GRUB should be built against libzfs. ZFS support is only available for GRUB v2. This option is ignored for GRUB v1.
Type: boolean
Default: false

Even when the option is false, grub depends on zfs-util.

I believe grub configuration should respect configuration option.

**Comment by volth** [comment]
it is addressed in https://github.com/NixOS/nixpkgs/pull/30192
