### ISSUE TITLE
doctest-haskell wrapper

### ISSUE THREAD

**Issue by aavogt** [NixOS/nixpkgs#3363]
doctest-haskell doesn't know about extra packages installed like ghc/ghci etc. do. This wrapper makes a bin/doctest-wrapper that knows about them:
```
{ stdenv, makeWrapper, doctest, ghc }:
stdenv.mkDerivation {
  name = "doctest-wrapper";
  buildInputs = [makeWrapper];
  propagatedBuildInputs = [doctest ghc];
  unpackPhase = "true";
  inherit doctest;
  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    makeWrapper $doctest/bin/doctest $out/bin/doctest-wrapper --add-flags "\$(${ghc.GHCGetPackages} ${ghc.version} \"\$(dirname \$0)\")"
  '';
}
```
as with ghc, should this wrapper be called doctest?

Another problem is that doctest is sometimes used with a `Test.DocTest.doctest :: [String] -> IO ()`. Those extra flags aren't added there, so maybe they should be added at some other point?

**Comment by peti** [comment]
Configuring the shell variables

    export NIX_GHC="$HOME/.nix-profile/bin/ghc"
    export NIX_GHCPKG="$HOME/.nix-profile/bin/ghc-pkg"
    export NIX_GHC_DOCDIR="$HOME/.nix-profile/share/doc/ghc/html"
    export NIX_GHC_LIBDIR=$(ghc --print-libdir)

allows `doctest` to pick up any 3rd-party libraries that are installed with ghc.
