### ISSUE TITLE
Update request: UV 0.2.37 → 0.3.0

### ISSUE THREAD

**Issue by spott** [NixOS/nixpkgs#336347]
- Package name: uv
- Latest released version: 0.3.0

- Current version on the unstable channel: 0.2.37
- Current version on the stable/release channel: 0.1.45

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GaetanLepage 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by spott** [comment]
So sorry, I looked, but didn't find it.

Thanks for being so prompt!

**Comment by GaetanLepage** [comment]
No worry ! Enjoy :)
