### ISSUE TITLE
Build failure: fakeroot (on darwin)

### ISSUE THREAD

**Issue by codyps** [NixOS/nixpkgs#336344]
### Steps To Reproduce

1. build fakeroot on a x86_64-darwin or aarch64-darwin system

### Build log

https://hydra.nixos.org/build/269425908/nixlog/1

https://hydra.nixos.org/build/269425908

### Additional context

Fails for me locally, and appears to be failing in hydra since 2024-07-28 10:31:11

### Notify maintainers

No maintainers, adding folks who have touched this at some point:

@Trundle @trofi @NickCao 

### Metadata

(fails on hydra, but also fails for me locally, including info on my machine)

```console
cody@u3 nixpkgs % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Looks like a bad UTF-8 input:

```
/private/tmp/nix-build-fakeroot-1.32.2.drv-0/source/doc /private/tmp/nix-build-fakeroot-1.32.2.drv-0/source
 (97 entries)
Malformed encoding while reading from file 
/private/tmp/nix-build-fakeroot-1.32.2.drv-0/source/doc/../doc/po4a/addendum
.1.es with charset UTF-8: UTF-8 "\xF3" does not map to Unicode at 
/nix/store/zav1d1llficb5fm9di820lwk3f9qhgms-perl5.38.2-po4a-0.71/lib/perl5/s
ite_perl/Locale/Po4a/TransTractor.pm line 619.
```

It is in `ISO8859-1`:

```
$ cat ./doc/po4a/addendum.1.es | iconv -f ISO8859-1 -t UTF-8
PO4A-HEADER:mode=after;position=AUTORES;beginboundary=.SH
.SH TRADUCTOR
Traducción de Rubén Porras Campo <debian\-l10n\-spanish@lists.debian.org>
```

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/commit/4093e7179346b3226137fb3790c72ab34c1cf872 was applied to `linux` only. Chances are it will fix darwin as well.

**Comment by trofi** [comment]
Attempting to apply unconditionally as:
- https://github.com/NixOS/nixpkgs/pull/336408

**Comment by codyps** [comment]
resolved by https://github.com/NixOS/nixpkgs/pull/336408
