### ISSUE TITLE
Build failure: flashprint

### ISSUE THREAD

**Issue by Jamalam360** [NixOS/nixpkgs#336318]
### Steps To Reproduce

1. build flashprint

### Build log

```
trying http://www.ishare3d.com/3dapp/public/FlashPrint-5/FlashPrint/flashprint5_5.8.4_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download flashprint5_5.8.4_amd64.deb from any mirror
```

### Additional context

The [flashprint download page](https://flashforge.com/pages/software-flashprint) links to `http://10.90.239.17/products/firmware/FDM/FlashPrint/FlashPrint_5.8.7/flashprint5_5.8.7_amd64.deb` (I tried to do a reverse DNS lookup on that, but I don't think that IP is associated to any domain name), whereas the current derivation uses `http://www.ishare3d.com/3dapp/public/FlashPrint-5/FlashPrint/flashprint5_5.8.4_amd64.deb`. Perhaps this could be solved by simply using the link that the flashforge website uses.

### Notify maintainers

@ianliu 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by applePrincess** [comment]
As of 86576d96a894b hence the current HEAD (at the time of commenting: 4de4818c1ffa76d57787af936e8a23648bda6be4) builds flashprint-5.8.6. I have checked it builds locally, can you confirm on your side?

**Comment by Jamalam360** [comment]
apologies, for some reason my flake inputs weren't updated to that yet despite running flake update pretty much daily. working now
