### ISSUE TITLE
Invidious fails to load

### ISSUE THREAD

**Issue by Ahwxorg** [NixOS/nixpkgs#336358]
### Describe the bug
Invidious does not load images or videos

### Steps To Reproduce
1. Define `services.invidious.enable = true;` in your configuration
2. Navigate to a YouTube video on Invidious
3. It does not load

### Expected behavior
It works; videos load, no issues.

### Screenshots
![image](https://github.com/user-attachments/assets/650e5676-63ac-4c93-b80b-1bc2239d6fcf)

### Additional context
[Try it yourself](https://video.liv.town/feed/popular)

### Notify maintainers

@999eagle @GaetanLepage @sbruder @pbsds 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ > nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.39, NixOS, 24.11 (Vicuna), 24.11.20240818.8a33541`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/d9gbq853jvbccrz5g3y0irbwgc57w137-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ahwxorg** [comment]
![image](https://github.com/user-attachments/assets/f5fb7754-e224-4928-b203-4ae6b4fda9c3)
Popular feed does not show anything either.

**Comment by 999eagle** [comment]
hi, yes this is very likely due to youtube blocking invidious instances (see also https://github.com/iv-org/invidious/issues/4734 for a similar (or potentially the same) issue). currently, invidious master can be made to work with some configuration and when running `inv_sig_helper`, but there hasn't been a new upstream release yet with the changes.

@GaetanLepage what do you think? should we package the master branch again (and also `inv_sig_helper` to make it work)?

**Comment by Ahwxorg** [comment]
ah okay, thank you!

**Comment by GaetanLepage** [comment]
> hi, yes this is very likely due to youtube blocking invidious instances (see also [iv-org/invidious#4734](https://github.com/iv-org/invidious/issues/4734) for a similar (or potentially the same) issue). currently, invidious master can be made to work with some configuration and when running `inv_sig_helper`, but there hasn't been a new upstream release yet with the changes.
> 
> @GaetanLepage what do you think? should we package the master branch again (and also `inv_sig_helper` to make it work)?

On my end, the subscription feed is displaying ok. However, I cannot watch any video:
![image](https://github.com/user-attachments/assets/fa859c26-a784-41b5-b7de-3aa804bed83e)

I have recently tried to use the master branch, but it didn't help, so I don't know.
I haven't try `inv_sig_helper` though...

**Comment by GaetanLepage** [comment]
A few days ago, I asked upstream rather they were considering a new release.
They want to work on a few more things before doing so, but it is definitely planned.

**Comment by isker** [comment]
A release has been cut: https://github.com/iv-org/invidious/releases/tag/v2.20241110.0

**Comment by GaetanLepage** [comment]
> A release has been cut: https://github.com/iv-org/invidious/releases/tag/v2.20241110.0

I started https://github.com/NixOS/nixpkgs/pull/355086.
