### ISSUE TITLE
Package request: protonhax

### ISSUE THREAD

**Issue by Creationsss** [NixOS/nixpkgs#336330]
**Project description**

Protonhax is a utility designed to manage Proton configurations for Steam games on Linux. It allows users to customize and control game-specific settings, helping to optimize the gaming experience when using Proton to run Windows games on Linux.

**Metadata**

* homepage URL: https://github.com/jcnils/protonhax
* source URL: https://github.com/jcnils/protonhax.git
* AUR package URL: https://aur.archlinux.org/packages/protonhax
* license: [BSD 3-Clause](https://github.com/jcnils/protonhax/blob/main/LICENSE)
* platforms: Linux

**Comment by bddvlpr** [comment]
Duplicate of #334957
