### ISSUE TITLE
Pepper Flash Download Error for Chromium

### ISSUE THREAD

**Issue by melsigl** [NixOS/nixpkgs#33648]
## Issue description

Enabling `enablePepperFlash` for Chromium in nixos' configuration file leads to 404 error due to wrong URL. Seems like either version or URL changed. 

Could be a reocurring problem as this has been reported with issue #30308.

### Steps to reproduce
in `/etc/nixos/configuration.nix`:
```
nixpkgs.config.chromium = {
  enablePepperFlash = true;
};
```
leads to the following error while running `nixos-rebuild switch`
```
trying https://fpdownload.adobe.com/pub/flashplayer/pdc/28.0.0.126/flash_player_ppapi_linux.x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (22) The requested URL returned error: 404 Not Found
error: cannot download flash_player_ppapi_linux.x86_64.tar.gz from any mirror
builder for ‘/nix/store/f62srdklkll7vxicqpziv20cmzih4sd6-flash_player_ppapi_linux.x86_64.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/8pc18f626h9fxa5yg2hxnkvzpsgl0s8m-flashplayer-ppapi-28.0.0.126.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/ldnwi6nnhfxqm1vsnlgm7yff71l760hc-gdm-password.pam’
cannot build derivation ‘/nix/store/nqhaaiy8r6qfbz4w96n6nvrc0nc7yk8p-chromium-63.0.3239.108.drv’: 1 dependencies couldn't be built
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 17.09.2631.0653b73bf61 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2652.3ff874c06af"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

can anyone look into it? thanks

**Comment by balsoft** [comment]
https://fpdownload.adobe.com/pub/flashplayer/pdc/28.0.0.137/flash_player_ppapi_linux.x86_64.tar.gz seems to be the correct one. Maybe PR?

**Comment by melsigl** [comment]
thanks for the reference @balsoft!

**Comment by joachifm** [comment]
The referenced PR has been merged, I take it that it fixes the issue.
