### ISSUE TITLE
(all?) rust projects need hashes updated, broken by recent change

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#33647]
## Issue description

https://github.com/NixOS/nixpkgs/commit/0af2c5891bfccfe5a6e8ba67e95c5852c45529d2

Breaks all rust projects I use, likely all in (and out) of the nixpkgs tree. `grep`ing for "cargoSha256" shows there are 49 instances in-tree, most of which were not updated with the change.

### Steps to reproduce

* Try to build any rust project in tree (`ripgrep`, `fd`, etc)
* Error due to wrong hash
* Discover someone pushed blatant breakage to master and be sad

**Comment by dtzWill** [comment]
Depending on what you're doing you'll either get an error about wrong cargo hash or an error like:

```
ERROR: file not found: /nix/store/0glffj6hyfaqq9qd44xgfbjnrsa4f46p-ion-1.0.5-vendor/.config
try updating the cargoSha256
```

(Which you can confirm is a hash problem by building `project.cargoDeps --check` instead of `project`)

**Comment by pbogdan** [comment]
FWIW the need to update all `cargoSha256` was acknowledged in the PR - https://github.com/NixOS/nixpkgs/pull/31982#issuecomment-354119816 Seems like it got merged before that got implemented though...

**Comment by dtzWill** [comment]
Sorry for being grumpy about this.  Everyone makes mistakes, certainly myself included.

Embracing that is why I've been content doing everything via PR, even when it is thoroughly tested.

It seems like we can do better re:process, especially for a project like this where everything is reproducible and such :).

**Comment by dtzWill** [comment]
> FWIW the need to update all cargoSha256 was acknowledged in the PR - #31982 (comment) Seems like it got merged before that got implemented though...

Thanks! I couldn't find the PR (or a merge commit, maybe I'm blind), maybe someone pushed the commits unintentionally? I'm happy to see it was known by the author, sounds like an accident or oversight. O:).

**Comment by orivej** [comment]
> I couldn't find the PR (or a merge commit, maybe I'm blind)

I abhor this practice of merging without merge commits (especially for PRs with multiple commits), but you can copy the complete hash into the GitHub search field to find the PR among the issues that mention it. The fact that the committer is different from the author (see "zimbatm committed with globin" in 0af2c5891bfccfe5a6e8ba67e95c5852c45529d2) is a clue that the commit came from a PR.

**Comment by dtzWill** [comment]
Looks like this has been reverted on master (https://github.com/NixOS/nixpkgs/commit/7c5430c27c910e35805530d563352911690c7c57), closing!
