### ISSUE TITLE
incus 6.4.0 can't find skopeo

### ISSUE THREAD

**Issue by frdiener** [NixOS/nixpkgs#336613]
### Describe the bug
With incus 6.4.0 from nixpkgs-unstable:
The incus deamon is missing a path to a skopeo (and bossibly umoci) binary.

``` console
[user@system:~]$ incus launch docker:hello --ephemeral
Launching the instance
Error: Failed instance creation: Failed getting remote image info: OCI container handling requires "skopeo" be present on the system
```

### Steps To Reproduce
1. Install incus and skopeo
2. add an oci remote: e.g. `incus remote add docker https://docker.io protocol=oci`
3. launch an oci container from the added remote: e.g. `incus launch docker:hello -e`

### Expected behavior
incus finds the skopeo binary, converts the docker image and launches the container.

### Notify maintainers

@adamcstephens

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.05 (Uakari), 24.05.20240821.224042e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/rc7vhx0w0hxz170r88i0s04n5b9rwqa9-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
6.4 isn't available on stable release, and thus 24.05 has not received the necessary module updates. Stable users are highly encouraged to stay on the default LTS. For now if you want the latest releases you'll want to use unstable.

https://github.com/NixOS/nixpkgs/blob/28922c4421b4a8d8f583913607da4f6db59e65a2/nixos/modules/virtualisation/incus.nix#L59
