### ISSUE TITLE
Knotes does not save setting changes made in main 'configure knotes' window

### ISSUE THREAD

**Issue by iamstonecutter** [NixOS/nixpkgs#336665]
### Describe the bug
When I right-click the KNotes tray icon and select 'Configure KNotes,' I try to adjust settings, for example like those in the 'Display' tab, but the changes don't apply. After reopening the 'Configure Knotes' window, the settings revert to their default values continuously.

The only way I can successfully change display settings is by right-clicking the top bar of an open, saved note, selecting 'Preferences,' and modifying the display settings for that specific note individually.

### Steps To Reproduce
1. Right click Knotes tray icon and go to 'configure knotes'
2. Try to change 'display tab' visual settings and apply them.
3. Check notes to see the changes do not apply.

### Expected behavior
All settings in 'configure knotes' should apply on first attempt.

### Additional context
This issue of settings not saving appears to be in most of the 'configure knotes' tabs.
This is occurring on both `kdePackages.knotes` stable and unstable. 

### Notify maintainers
@ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000 @ttuegel

**Comment by K900** [comment]
KNotes is unmaintained upstream, and has in fact been dropped from KDE Gear in 24.08.

**Comment by K900** [comment]
There's the Plasma sticky notes widget and Marknote.

**Comment by K900** [comment]
https://invent.kde.org/sysadmin/release-tools/-/merge_requests/53

**Comment by K900** [comment]
Not really, I don't use either.
