### ISSUE TITLE
Emacs tramp sudo does not work

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#3368]
In Emacs, when I try to open a file with tramp + sudo, Emacs becomes unresponsive. I have to unfreeze it with `C-g`. The *Messages* buffer contains:

```
Tramp: Waiting for prompts from remote shell
Tramp: Sending Password
Tramp: Waiting for prompts from remote shell
Tramp: Sending command `exec sudo -u root -s -H -p Password:'
Tramp: Opening connection for root@localhost using sudo...done
```

I can run the command `sudo -u root -s -H -p Password:` in a terminal just fine, it opens a shell with root privileges.  I have added the following line in my `init.el` file as explained in the wiki (https://nixos.org/wiki/Emacs_configuration):

```elisp
(add-to-list 'tramp-remote-path "/run/current-system/sw/bin")
```

But this does not help at all.

On IRC, both @ewemoa and @goibhniu say they can reproduce the problem.

**Comment by eskimor** [comment]
Just for others stumbling upon this, the fix on the emacs side is documented here:
http://www.emacswiki.org/emacs/TrampMode#toc6

**Comment by peti** [comment]
This issue has been fixed in NixOS a while ago; we now recognize tramp environments and use a simpler prompt.
