### ISSUE TITLE
`mamba` is not usable

### ISSUE THREAD

**Issue by Sigmanificient** [NixOS/nixpkgs#336892]
### Steps To Reproduce
1. `nix-shell -p mamba`
2. `mamba -qy install pytest`

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
[...]
```

### Notify maintainers

 @magnetophon  @orivej 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - channels(root): `"nixos-23.05"`
 - channels(sigmanificient): `""`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TanvirOnGH** [comment]
Yep, it's broken.

![image](https://github.com/user-attachments/assets/b7779c60-cc9e-4638-9ad8-46780761d592)

```nix
~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5-xanmod1, NixOS, 24.11 (Vicuna), 24.11pre668759.8a3354191c0d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by magnetophon** [comment]
You are assuming this is the package manager.
It is not, it is a midi keyboard: https://github.com/brummer10/Mamba
