### ISSUE TITLE
nixos-rebuild's use of ssh -t corrupts terminal output when run in parallel

### ISSUE THREAD

**Issue by Cnly** [NixOS/nixpkgs#336967]
### Describe the bug

When running multiple nixos-rebuild in parallel to deploy to remote machines, the terminal output can become corrupt because the  multiple `ssh -t` processes invoked by nixos-rebuild set the terminal to raw mode and cannot properly set it back. The output looks like the following image (it's not my screenshot but is basically the same thing), where linefeeds are there but carriage returns are gone, and key strokes like ^C also stop working:

![Corrupted terminal output](https://i.sstatic.net/kWn5G.png)

### Steps To Reproduce

Run multiple nixos-rebuild to deploy to multiple remote machines in parallel.

Or just run `ssh -t` with strace so you can see it's setting the terminal to raw mode:

`strace -vfe trace=ioctl ssh -t <host>` (pay attention to the `TCSETSW` ioctl calls)

### Expected behavior

The output shouldn't become unreadable and the terminal should remain usable.

### Additional context

Currently nixos-rebuild always adds the `-t` flag for target host commands:

https://github.com/NixOS/nixpkgs/blob/591f081df866332c300735ff089a559bc9ff4cbc/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L231-L235

If that flag is removed, everything works as expected, but I'm not sure how exactly sudo or other things will be affected.

Maybe we can add a `--no-ssh-tty` option to nixos-rebuild so users who are sure they don't want `-t` can get rid of it? If this sounds good or we have a better solution, I'm happy to open a PR for it.

### Notify maintainers

According to git blame, I'll request a comment from @roberth.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by roberth** [comment]
According to https://github.com/NixOS/nixpkgs/commit/09fd207cb8a6a1e654cdc9dc49610ebd456fe05d, we may need the tty for other things than `sudo`, so we do not have sufficient info for disabling the tty flag automatically.

Sounds ok to me. Make sure to document it in the man page.

**Comment by Cnly** [comment]
@roberth thanks for the input! I'll open a PR once I get it ready.

**Comment by Cnly** [comment]
Hi @roberth, do you have some time to review the PR? :)
