### ISSUE TITLE
Package request: Zen Browser

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [NixOS/nixpkgs#336965]
**Project description**
> Zen Browser is a privacy-focused browser built for speed and security. It offers features like multitasking with split views, workspaces, and a compact mode for smaller screens. Zen Browser aims to provide a browsing experience that prioritizes user experience and privacy.

It’s an opensource alternative to the [Arc Browser](https://arc.net/).

**Metadata**
* homepage URL: https://www.zen-browser.app/
* source URL: https://github.com/zen-browser/desktop
* license: MLP-2.0
* platforms: Linux, Mac, and Windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TanvirOnGH** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/327982

**Comment by Tygo-van-den-Hurk** [comment]
@TanvirOnGH you’re right, sorry. I don’t know how but I must have missed it when I searched for already existing requests. That’s my bad.
