### ISSUE TITLE
Build failure: lix on x86_64-darwin

### ISSUE THREAD

**Issue by eilvelia** [NixOS/nixpkgs#337036]
### Steps To Reproduce

Using `nix.package = pkgs.lix;` on nix-darwin builds lix from source and eventually fails with:

```console
[----------] Global test environment tear-down
[==========] 248 tests from 53 test suites ran. (585 ms total)
[  PASSED  ] 245 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] compress.compressWithUnknownMethod
[  FAILED  ] decompress.decompressInvalidInputThrowsCompressionError
[  FAILED  ] Config.applyConfigInvalidThrows

 3 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS


stderr:
Using configuration: seed=6325455801096409188



Summary of Failures:

3/5 lix:check / libexpr-unit-tests  FAIL            0.40s   exit status 1
2/5 lix:check / libstore-unit-tests FAIL            0.58s   exit status 1
5/5 lix:check / libcmd-unit-tests   FAIL            0.65s   exit status 1
1/5 lix:check / libutil-unit-tests  FAIL            0.72s   exit status 1

Ok:                 1   
Expected Fail:      0   
Fail:               4   
```

The build on hydra also doesn't work: https://hydra.nixos.org/build/270128529 (seems to fail for both lix 2.91 and lix 2.90 now)

A temporary workaround is to do `pkgs.lix.overrideAttrs { doCheck = false; doInstallCheck = false; }`.

### Additional context

Related: #334269

### Notify maintainers

@RaitoBezarius @Qyriad @lf-

### Metadata

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/f5ykynf933aab7nd1arqz6dm79hdh91q-source`
```

nixpkgs ae815cee91b417be55d43781eb4b73ae1ecc396c

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vcunat** [comment]
Also on aarch64-darwin in nixpkgs 24.05:
https://hydra.nixos.org/build/272142889
