### ISSUE TITLE
rstudioWrapper is broken

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#33702]
## Issue description
rstudio installed via `nixpkgs.rstudioWrapper` is broken.

### Steps to reproduce
```
$ nix-shell -p rstudioWrapper --pure --run rstudio
This application failed to start because it could not find 
or load the Qt platform plugin "xcb" in "".

Reinstalling the application may fix this problem.
```
The same goes for installing `rstudioEnv` as described in the [manual](https://nixos.org/nixpkgs/manual/#rstudio).
The following does however work:
```
$ nix-shell -p rstudio --pure --run rstudio
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.74, NixOS, 17.09.2630.81373e421e8 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(sepp): `"nixos-17.09-17.09.2498.a9ffb7b0b5a, nixpkgs-17.09.2498.a9ffb7b0b5a"`
 - channels(root): `""`
 - nixpkgs: `/nix/store/k6jyklha15pssnnjnpdzqlgnm5a8gn06-nixexprs.tar.xz`

**Comment by knedlsepp** [comment]
Ping @ehmry @changlinli @ciil

**Comment by knedlsepp** [comment]
Problems seems to be due to qt being missing in $PATH for rstudioWrapper.
The command:
```
diff <(nix-shell -p rstudio --run env) <(nix-shell -p rstudioWrapper --run env) | grep "PATH"
```
shows that `/nix/store/x5c1z4v2kyxwl2dgh7r08jq2zxsaar02-qt-5.9.1/bin` is on the $PATH for rstudio, but not for rstudioWrapper.
Interestingly enough, installing rstudio via: `nix-env -iA nixpkgs.rstudio` also installs all kinds of `qt` commands like `qmake`, but `rstudioWrapper` doesn't.

**Comment by knedlsepp** [comment]
I'm uncertain if this is the right solution, but moving qt to `propagatedBuildInputs` of rstudio seems to make it work.
```
  propagatedBuildInputs = [ qt5.full qt5.qtwebkit qt5.qtwebchannel ];
```
I suppose that making qt5 a dependency of `rstudioWrapper` might also work. Which one is the right solution?

**Comment by ciil** [comment]
I don't have regular internet access until (hopefully) early next week, so I won't be able to look into it before then. This qt issue might be related to #30551. Could you try again with the workaround from https://github.com/NixOS/nixpkgs/issues/30551#issuecomment-346319767 ?

**Comment by changlinli** [comment]
I'll try to give this a gander sometime this week.

**Comment by joncfoo** [comment]
I have confirmed that adding `propagatedBuildInputs = [ qtbase qtwebkit qtwebchannel ];` to default.nix does indeed allow rstudio to start as expected.

**Comment by joncfoo** [comment]
update: the wrapper seems to be working fine
