### ISSUE TITLE
Update request: bottles 51.11 → 51.13

### ISSUE THREAD

**Issue by urioTV** [NixOS/nixpkgs#337077]
- Package name: Bottles
- Latest released version: 51.13

- Current version on the unstable channel: 51.11
- Current version on the stable/release channel: 51.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@psydvl 
@SCOTT-HAMILTON 

-----

Note for maintainers: Please tag this issue in your PR.

You cannot download new versions of runners in old Bottles version. You can do this manually however it may be tedious.
And of course new version fixes some bugs.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
51.13 is now available in unstable.
