### ISSUE TITLE
Build failure: aws-sam-cli v1.120

### ISSUE THREAD

**Issue by ElrohirGT** [NixOS/nixpkgs#337137]
### Steps To Reproduce

1. nix develop --impure 'github:SanitasUVG/Sanitas?ref=fix/patient-general-data-refactoring'

### Build log
[Gist Log](https://gist.github.com/ElrohirGT/78db5078f2442455396f4bbdb78e320d)

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/f3aab4dd-b98f-405b-acbb-4509bf6e5c41">

### Additional context
I just tried to update using `nix flake update` and it fails to enter the devShell now.

### Notify maintainers
@lo1tuma 
@anthonyroussel 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by axelknock** [comment]
With #303877 build now succeeds.

**Comment by ElrohirGT** [comment]
Hmm.... I still have the same error, I created a branch just so that you can reproduce it yourself!
```bash
nix develop --impure "github:SanitasUVG/Sanitas/test/samcli-build-fail"
```

It's really weird since it works when I try to run:
```bash
nix-shell -p aws-sam-cli
```

And the version that I install above is 1.120:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/9e3697ca-a2df-4a22-b2f2-e2d6c5e4179e">

**Comment by gautaz** [comment]
@ElrohirGT, I had the issue on my flake using nixpkgs master and a `nix flake update` resolved the issue yesterday.

Looking at your `flake.lock`:

```nix
    "nixpkgs": {
      "locked": {
        "lastModified": 1692808169,
        "narHash": "sha256-x9Opq06rIiwdwGeK2Ykj69dNc2IvUH1fY55Wm7atwrE=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "9201b5ff357e781bf014d0330d18555695df7ba8",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

You are using `nixpkgs-unstable` and not `master`.
As the fix [probably got merged](https://nixpk.gs/pr-tracker.html?pr=303877) on `nixpkgs-unstable` only a few hours ago, could you retry?

**Comment by ElrohirGT** [comment]
You're right! It works now, thank you!
