### ISSUE TITLE
darktable-2.4.0 is missing lua support

### ISSUE THREAD

**Issue by Sitwon** [NixOS/nixpkgs#33710]
## Issue description
The darktable-2.4.0 package has Lua support disabled. It was enabled in darktable-2.2.5. This does not appear to be intentional, since https://github.com/NixOS/nixpkgs/commit/9c621d7773a033cbec03e58a4c793fcc6a422a17 shows no changes other than version number and maintainers.

### Steps to reproduce
Install Darktable.
```$ nix-env -i darktable-2.4.0```
Check for Lua support.
```$ darktable --version
this is darktable 2.4.0
copyright (c) 2009-2017 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  ...
  Lua support disabled
  ...
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
584 bmendis@galleon:~ 0 $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-104-generic, Ubuntu, 16.04.3 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(bmendis): `"nixpkgs-18.03pre125021.73a01aa028c"`
 - nixpkgs: `/home/bmendis/.nix-defexpr/channels/nixpkgs`
```

**Comment by LebedevRI** [comment]
Note that in darktable-2.4.0 we switched to lua-5.3 from lua-5.2
