### ISSUE TITLE
Update request: flutter 3.22.2 → 3.24.1

### ISSUE THREAD

**Issue by CodeThomnics** [NixOS/nixpkgs#337181]
- Package name: flutter
- Latest released version: 3.24.1

- Current version on the unstable channel: 3.22.2
- Current version on the stable/release channel: 3.22.2

- [ X ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
CC @RossComputerGuy

**Comment by RossComputerGuy** [comment]
Already being done #336650
