### ISSUE TITLE
Update request: yandex-browser 24.4.1.915-1 → 24.7.1.1120-1

### ISSUE THREAD

**Issue by sanchpet** [NixOS/nixpkgs#337166]
- Package name: yandex-browser
- Latest released version: 24.7.1.1120-1
- Current version on the unstable channel: 24.4.1.915-1
- Current version on the stable/release channel: 24.4.1.915-1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dan4ik605743
@ionutnechita

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Steinhagen** [comment]
This will be resolved by https://github.com/NixOS/nixpkgs/issues/337166.
