### ISSUE TITLE
Plasma 6 - Copy within Qemu/KVM guest not transfered to host clipboard

### ISSUE THREAD

**Issue by MarkTurney** [NixOS/nixpkgs#337207]
### Describe the bug
When text is copied within a Qemu/KVM guest Plasma 6 NixOS VM, that copied text is not automatically transferred to the host clipboard.

I have confirmed that text is copied to host when using a Plasma 5 NixOS VM and the latest Gnome NixOS VM.

### Steps To Reproduce
1. Download and install the latest Plasma 6 NixOS ISO into a Qemu/KVM VM using virt-manager.
2. Install the Qemu guest integration and spice-vdagent services into the NixOS installation by adding the following content to Nix configuration.
```bash
  # Add these service entries to /etc/nixos/configuration.nix
  services.spice-vdagentd.enable = true;
  services.qemuGuest.enable = true;
```
4. Update Nix and reboot.
```bash
sudo nixos-rebuild switch
sudo reboot
```
5. Attempt to copy text within the Qemu/KVM VM and paste the text into the host.  You will notice that the host clipboard is not modified and the text that is pasted on the host is the text that previously was resident within the host clipboard.

### Expected behavior
Text that is copied within a Plasma 6 NixOS Qemu/KVM VM should automatically be transferred to the host clipboard when the associated VM guest services are installed.

The reproduction steps were followed using Plasma 5 and the latest Gnome Nix ISO and they worked as expected in both of these cases.

### Additional context
Text that is copied in the host is properly transferred into the Plasma 6 VM's clipboard.

### Notify maintainers
@K900

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.05 (Uakari), 24.05.4169.797f7dc49e0b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
You're probably using the Wayland session, which the QEMU tools don't work with. Use the X11 session.

**Comment by MarkTurney** [comment]
Hello K900,

I am using all of the default settings which include these:

```bash
  # Enable the X11 windowing system.
  # You can disable this if you're only using the Wayland session.
  services.xserver.enable = true;

  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };
```

The first block of /etc/sddm.conf is:

```bash
[General]
DefaultSession=plasma.desktop
DisplayServer=x11
GreeterEnvironment=LANG=C.UTF-8 QT_WAYLAND_SHELL_INTEGRATION=layer-shell
HaltCommand=/run/current-system/systemd/bin/systemctl poweroff
InputMethod=
Numlock=none
RebootCommand=/run/current-system/systemd/bin/systemctl reboot
```

I have also tried to enable Wayland to see if that would fix the problem, but it did not.

Please tell me if there are any other configuration options that you think might help diagnose or solve the problem.

I appreciate the help K900!

**Comment by K900** [comment]
The default session for Plasma 6 is Wayland. You want to explicitly choose the X11 session.

**Comment by MarkTurney** [comment]
Hello K900,

That was it, I really really appreciate your help!

For anyone that has experienced the same problem as myself, when greeted with the Plasma 6 login screen, you have to choose "Plasma (X11)" option from the "Desktop Session:" selection at the bottom left hand side of the login screen before signing in.
