### ISSUE TITLE
Update request: ArmCord 3.2.8 → 3.3.0

### ISSUE THREAD

**Issue by SelfMadeSystem** [NixOS/nixpkgs#337234]
- Package name: armcord
- Latest released version: 3.3.0

- Current version on the unstable channel: 3.2.8
- Current version on the stable/release channel: 3.2.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wrmilling 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wrmilling** [comment]
Unstable is currently waiting on Electron 32 to be added to nixpkgs to be able to update to 3.3.0. 

We may be able to update Stable before then since it is using the compiled packages. 

@SelfMadeSystem Which are you running currently (Stable vs Unstable)?

**Comment by SelfMadeSystem** [comment]
I'm currently using unstable.

**Comment by wrmilling** [comment]
Got it, once we have electron 32 available it should be a fairly quick package / release.

**Comment by water-sucks** [comment]
I attempted to package this using Electron 31 since that's available, and it seems to be working stably. I looked at the ArmCord source and it doesn't look like it relies on anything Electron 32-specific, so I'll try to put out a PR.
