### ISSUE TITLE
Package request: lazy.vim

### ISSUE THREAD

**Issue by kirosharlequin** [NixOS/nixpkgs#337228]
**Project description**

i've spent the last day trying to get lazyvim working but since there isn't any nix way to do it, the biggest dependency for any neovim config is lazy.vim, the package manager.

**Metadata**

* homepage URL: https://lazy.folke.io/
* source URL: https://github.com/folke/lazy.nvim
* license: [Apache-2.0 license](https://github.com/folke/lazy.nvim#Apache-2.0-1-ov-file)
* platforms: unix, linux, darwin, WSL

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
It's available: https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=lazy-nvim . A research on lazy.nvim returns nothing which is annoying though :/

**Comment by teto** [comment]
note that lazy.nvim resets the packpath which might conflict which nix installed vim plugins so you may have to tweak the default lazy.nvim config. If you search `lazy.nvim nixpkgs` you will find many results.
