### ISSUE TITLE
Predictable interface names are gone on unstable 

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#33738]
## Issue description
After rebooting into current unstable (f607771d0f5e4fa905afff1c772febd9f3103e1a) interface names have reverted to old style (eth0, ...) despite nixos-option networking.usePredictableInterfaceNames reporting the set value as true.

I'm using linuxPackages_latest, which is 4.14.12, but I'm not sure it's relevant.

## Technical details
```
$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.12pre5810_5d5b931f, channels(root): "", nixpkgs: /home/sarah/src/nixpkgs
```
nixpkgs version: f607771d0f5e4fa905afff1c772febd9f3103e1a

**Comment by symphorien** [comment]
I am also affected, but with linux 4.9.75.
```
$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.16, channels(root): "nixos-18.03pre125026.f607771d0f5", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

**Comment by clefru** [comment]
Potential culprit: https://github.com/NixOS/nixpkgs/commit/470f5ef40932321f09936d64888d8652d43b880c

**Comment by Nadrieril** [comment]
Same here, on `nixpkgs-unstable` from a few days ago. The `80-net-setup-link.rules` is present as expected, but I still have `eth0` and the like. If it helps anyone, here are the contents of that file for me:
```
SUBSYSTEM!="net", GOTO="net_setup_link_end"
IMPORT{builtin}="path_id"
ACTION!="add", GOTO="net_setup_link_end"
IMPORT{builtin}="net_setup_link"
NAME=="", ENV{ID_NET_NAME}!="", NAME="$env{ID_NET_NAME}"
LABEL="net_setup_link_end"
```

**Comment by srhb** [comment]
I believe it was reverted in 788c5195f36fe101ecbf016137e017655063bc6b, so we should be fine once the unstable channel bumps.

**Comment by vcunat** [comment]
Perhaps we don't have enough NixOS tests yet.

Let's close.  We can reopen in the unlikely case this wasn't the culprit.

**Comment by symphorien** [comment]
I just made a PR to add such a test :)
