### ISSUE TITLE
services.phpfpm.phpOptions is ignored

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixpkgs#33741]
## Issue description

Parameter services.phpfpm.phpOptions is ignored. According to documentation it supposed to append configuration options to php.ini file.

### Steps to reproduce

Add
`services.phpfpm.phpOptions = ''`
`  cgi.fix_pathinfo = 0;`
` '';`

to .nix file and build. Look for generated php.ini file - option is not set. Also this command
`$ php-fpm -i | grep pathinfo` outputs
>  cgi.fix_pathinfo => 1 => 1

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 17.09.2630.81373e421e8 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(aleksejs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by srhb** [comment]
Can you provide an example that demonstrates the issue? According to the module, the modified php.ini file is passed to php-fpm through `ExecStart` in the generated systemd `phpfpm-${pool}` unit:

```
ExecStart = "${cfg.phpPackage}/bin/php-fpm -y ${cfgFile} -c ${phpIni}";
```

**Comment by ivanovsaleksejs** [comment]
After updating channel and all packages this problem disappeared.
