### ISSUE TITLE
Build failure: surrealdb

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#337553]
### Steps To Reproduce

1. `nix build nixpkgs/a24a4fd31612a05c5b2d0e1d4ab928cbebcb5f42#surrealdb --impure`

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/6v1r4fsk7r28y8c0zd4wb3bv50d3znyy-surrealdb-1.5.4-vendor.tar.gz.drv':
         specified: sha256-5qIIPdE6HYov5EIR4do+pMeZ1Lo3at39aKOP9scfMy8=
            got:    sha256-b0KmL6RQevO7oLPZCgUc4EUkgv99DbMFD/RkE/fwAHw=
```

### Additional context

Happens on nixos-unstable, master, and on the commit that was made in the latest surrealdb PR. It consistently produces the same hash as prior to https://github.com/NixOS/nixpkgs/pull/336144 on x86_64-linux and aarch64-linux.

### Notify maintainers

@siriobalmelli @sikmir @happysalada 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.11 (Vicuna), 24.11.20240824.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/dkr84n4bkmflc6kh8yrdwrvn2ca5vwyh-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
Hey so sorry about this, i was sure i had checked ofborg before merging.

**Comment by happysalada** [comment]
Does anyone have bandwidth to make a PR ?

**Comment by gepbird** [comment]
@happysalada I can make a PR soon (later today) with the other hash, I was just curious how did @siriobalmelli get that hash.
