### ISSUE TITLE
python grpcio doesn't build on darwin

### ISSUE THREAD

**Issue by joestein** [NixOS/nixpkgs#33765]
## Issue description
Getting an error trying to build grpcio 1.7.3 on darwin

make: Circular /private/var/folders/4k/jpntp1hn6b7c9ymh7v044b9h0000gn/T/nix-build-python2.7-grpcio-1.7.3.drv-0/grpcio-1.7.3/libs/opt/libares.a <- /private/var/folders/4k/jpntp1hn6b7c9ymh7v044b9h0000gn/T/nix-build-python2.7-grpcio-1.7.3.drv-0/grpcio-1.7.3/libs/opt/libz.a dependency dropped.
ar: illegal option -- /
usage:  ar -d [-TLsv] archive file ...
       	ar -m [-TLsv] archive file ...
       	ar -m [-abiTLsv] position archive file ...
       	ar -p [-TLsv] archive [file ...]
       	ar -q [-cTLsv] archive file ...
       	ar -r [-cuTLsv] archive file ...
       	ar -r [-abciuTLsv] position archive file ...
       	ar -t [-TLsv] archive [file ...]
       	ar -x [-ouTLsv] archive [file ...]
make: *** [Makefile:8459: /private/var/folders/4k/jpntp1hn6b7c9ymh7v044b9h0000gn/T/nix-build-python2.7-grpcio-1.7.3.drv-0/grpcio-1.7.3/libs/opt/libares.a] Error 1

### Steps to reproduce
```
with import <nixpkgs> { };

let
  my_grpcio = python27.pkgs.buildPythonPackage rec {
    pname = "grpcio";
    version = "1.7.3";

    src = python27.pkgs.fetchPypi {
      inherit pname version;
      sha256 = "1wkrxj1jmf2dyx207fc9ysyns9h27gls3drgg05mzdckjqr5lnl6";
    };

    buildInputs = [ python27Packages.protobuf python27Packages.enum34 python27Packages.futures python27Packages.six ];

    meta = with stdenv.lib; {
      description = "HTTP/2-based RPC framework";
      license = lib.licenses.bsd3;
      homepage = "https://grpc.io/grpc/python/";
      maintainers = with maintainers; [ tbd ];
    };
  };
in
stdenv.mkDerivation {
    name = "grpc";
    buildInputs = [ my_grpcio ];
}
```
nix-shell grpcio.nix

## Technical details
 - system: `"x86_64-darwin"`
 - host os: `Darwin 15.6.0, macOS 10.11.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.8`
 - channels(joestein): `"nixpkgs-18.03pre125021.73a01aa028c"`
 - nixpkgs: `/Users/joestein/.nix-defexpr/channels/nixpkgs`

**Comment by dajmaki** [comment]
Try: `preBuild = "unset AR";`

**Comment by joestein** [comment]
Thanks @dajmaki that worked to get past the AR error, fighting another error now with libtool 
`libtool:   error: unrecognised option: '-no_warning_for_no_symbols'`
but progressing along again. Thanks!!!

**Comment by joestein** [comment]
This derivation works now
`with import <nixpkgs> { };

let
  custom = rec {

    gflags = pkgs.gflags.overrideDerivation (old: rec {
          prePatch = "mv BUILD BUILD.bazel";
        });
      

    grpc = pkgs.grpc.overrideDerivation (old: rec {
        prePatch = "mv BUILD BUILD.bazel";
          buildInputs = [ gflags ];
        });
    
    my_grpcio = python27.pkgs.buildPythonPackage rec {
      pname = "grpcio";
      version = "1.7.3";

      src = python27.pkgs.fetchPypi {
        inherit pname version;
        sha256 = "1wkrxj1jmf2dyx207fc9ysyns9h27gls3drgg05mzdckjqr5lnl6";
      };    
      nativeBuildInputs = [ cmake pkgconfig ];
    
      cmakeFlags =
      [ "-DgRPC_ZLIB_PROVIDER=package"
        "-DgRPC_CARES_PROVIDER=package"
        "-DgRPC_SSL_PROVIDER=package"
        "-DgRPC_PROTOBUF_PROVIDER=package"
        "-DgRPC_GFLAGS_PROVIDER=package"
      ];
      
      enableParallelBuilds = true;

      buildInputs = [ zlib c-ares c-ares.cmake-config openssl protobuf gflags darwin.cctools python27Packages.protobuf python27Packages.enum34 python27Packages.futures python27Packages.six ];

      preBuild = "unset AR";

      meta = with stdenv.lib; {
        description = "HTTP/2-based RPC framework";
        license = lib.licenses.bsd3;
        homepage = "https://grpc.io/grpc/python/";
        maintainers = with maintainers; [ tbd ];
      };
    };
  };
in stdenv.mkDerivation {
    name = "grpceio";
    buildInputs = [  custom.my_grpcio ];
}
`
