### ISSUE TITLE
Update request: zotero 7.0.0 → 7.0.3

### ISSUE THREAD

**Issue by sstubbs** [NixOS/nixpkgs#337737]
- Package name: zotero
- Latest released version: 7.0.3

- Current version on the unstable channel: 7.0.0
- Current version on the stable/release channel: 6.0.35

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by toonn** [comment]
Closing because #338458 was merged.
