### ISSUE TITLE
Update request: rio 0.1.7 → 0.1.10

### ISSUE THREAD

**Issue by zh4ngx** [NixOS/nixpkgs#337778]
- Package name: rio
- Latest released version: 0.1.10

- Current version on the unstable channel: 0.1.7
- Current version on the stable/release channel: 0.0.39

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@TornaxO7 @otavio @oluceps
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TornaxO7** [comment]
will do a PR this evening
