### ISSUE TITLE
Enabling Steam  with `programs.steam.enable` now fails due to path collision in `environment.systemPackages`

### ISSUE THREAD

**Issue by Lunaphied** [NixOS/nixpkgs#337768]
### Describe the bug

Somehow simply enabling `programs.steam.enable = true` seems to cause both the module's modified Steam package and the unmodified package to end up in the environment. This causes a collision and somehow the resolution picks the derivation with a broken symlink. Installing Steam by just putting `config.programs.steam.package` in `environment.systemPackages` doesn't cause this issue but also fails to setup the correct environment for Steam the way the module does.

### Steps To Reproduce
1. Set `programs.steam.enable = true`
2. Rebuild config
3. Observe errors about environment collision and dangling symlink

### Expected behavior
The broken derivation isn't added to `environment.systemPackages` and Steam is properly added to the system path without a dangling symlink.

### Notify maintainers

@Atemu @eclairevoyant @K900 @mkg20001

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240824.d0e1602`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20240825-b688438
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/lunaphied/.config/nix/nix.conf:/nix/store/fx0df5i0v2dnz49kr5kf2hnx68rq7cr1-plasma-workspace-6.1.4/etc/xdg/nix/nix.conf:/nix/store/vxb0919cds2c2zzghbf2xzw1077kx4zc-kglobalacceld-6.1.4/etc/xdg/nix/nix.conf:/nix/store/spg7y4a8h9f9djmx0m634qzwhc5396c5-baloo-6.5.0/etc/xdg/nix/nix.conf:/home/lunaphied/.config/kdedefaults/nix/nix.conf:/nix/store/fx0df5i0v2dnz49kr5kf2hnx68rq7cr1-plasma-workspace-6.1.4/etc/xdg/nix/nix.conf:/nix/store/vxb0919cds2c2zzghbf2xzw1077kx4zc-kglobalacceld-6.1.4/etc/xdg/nix/nix.conf:/nix/store/spg7y4a8h9f9djmx0m634qzwhc5396c5-baloo-6.5.0/etc/xdg/nix/nix.conf:/nix/store/fx0df5i0v2dnz49kr5kf2hnx68rq7cr1-plasma-workspace-6.1.4/etc/xdg/nix/nix.conf:/nix/store/vxb0919cds2c2zzghbf2xzw1077kx4zc-kglobalacceld-6.1.4/etc/xdg/nix/nix.conf:/nix/store/spg7y4a8h9f9djmx0m634qzwhc5396c5-baloo-6.5.0/etc/xdg/nix/nix.conf:/home/lunaphied/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/lunaphied/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/lunaphied/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/lunaphied/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/f6xsyl4z3jkpq8qgn7m08zm9vcjh6s0p-lix-2.92.0-dev-pre20240825-b688438/share`
 - channels(root): `""`
 - nixpkgs: `/nix/store/ia1zpg1s63v6b3vin3n7bxxjgcs51s2r-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
What do you mean by "unmodified package"? Where is it coming from, and where's the collision?
I don't encounter any such behavior.

**Comment by Lunaphied** [comment]
It looks like adding `config.services.udev.packages` to `environment.systemPackages` causes this particular breakage

**Comment by eclairevoyant** [comment]
Why would you need to do that?

**Comment by Lunaphied** [comment]
It's just a convenience to add packages that have udev definitions to the environment. It's not a precondition of anything working. I just got caught out by this unexpected result.

**Comment by eclairevoyant** [comment]
That's not how you enable udev rules.
You enable them by adding packages to `services.udev.packages`.

**Comment by Lunaphied** [comment]
This isn't intended to enable the udev rules, it's intended to add programs with udev rules into the system path if they aren't in it default

**Comment by eclairevoyant** [comment]
Then use `environment.systemPackages = map lib.lowPrio config.services.udev.packages` or something if you want the udev package to lose out. Either way, this isn't something we're going to support.
