### ISSUE TITLE
palemoon: .desktop not executable, doesn't include icon in file.

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#33770]
## Issue description
I installed Pale Moon and I noticed it didn't show up in KDE, I checked the usr/share/applications/palemoon.desktop file and it is missing both the +x bit and the icon name. (Possibly missing the icon itself)

### Steps to reproduce
Install Pale Moon.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.11.0, NixOS, 18.03pre125026.f607771d0f5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre125026.f607771d0f5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
The desktop item is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/palemoon/default.nix#L23). There is indeed no icon but I don't know what the icon name is.
I don't use a DE so I never tested it. I'll see this weekend.

**Comment by rnhmjoj** [comment]
Ok, I figured it out.
