### ISSUE TITLE
Package request: MatrixZulipBridge

### ISSUE THREAD

**Issue by lomenzel** [NixOS/nixpkgs#337806]
**Project description**

A Zulip puppeting bridge for Zulip. similar to mautrix-signal etc.

**Metadata**

* homepage URL: https://github.com/GearKite/MatrixZulipBridge
* source URL: https://github.com/GearKite/MatrixZulipBridge
* license: agpl 3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rrcomtech** [comment]
See #337953
