### ISSUE TITLE
Update request: calligra 3.2.1 → 4.0.0

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#337989]
- Package name: calligra
- Latest released version: 4.0.0

- Current version on the unstable channel: 3.2.1
- Current version on the stable/release channel: 3.2.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ebzzry @zraexy

-----
https://invent.kde.org/office/calligra/-/tags/v4.0.0

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
Github moment.

Completed in #344930.
