### ISSUE TITLE
Build failure: kdePackages.breeze-icons

### ISSUE THREAD

**Issue by drishal** [NixOS/nixpkgs#337941]
### Steps To Reproduce

1.just add kdePackages.breeze-icons to home.packages or environment.systemPackages

### Build log

```
error: builder for '/nix/store/4dsg9k9xym4b2yv7jjvxcwk92v2g4qm3-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/7vcz5xwa48dymc5ph92qm83zrkzgi6p4-breeze-icons-6.5.0/share/icons/breeze/actions/12/object-fill.svg' and `/nix/store/sgwz86ng93zil1car1il4jcqwycqjlb7-papirus-icon-theme-20240501/share/icons/breeze/actions/12/object-fill.svg'
```

### Notify maintainers
@ilya-fedin @K900 @LunNova @mjm

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.6-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240824.d0e1602`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/ia1zpg1s63v6b3vin3n7bxxjgcs51s2r-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
That's not a package build failure, you have two icon sets with conflicting names.

**Comment by drishal** [comment]
> That's not a package build failure, you have two icon sets with conflicting names.

but then why is papirus icons conflicting with breeze icons ? that's the most confusing part.
Does this mean I cannot have breeze cursor but with papirus icon theme ?

**Comment by K900** [comment]
I don't know, ask the Papirus upstream, I guess.
