### ISSUE TITLE
Build failure: Kitty

### ISSUE THREAD

**Issue by Tiecoon** [NixOS/nixpkgs#337987]
### Steps To Reproduce

1. build kitty on aarch64-darwin targeting nixpkgs current master (6f8da97) and nixpkgs-unstable

### Build log

```
error: builder for '/nix/store/awnxsi0x2wap2wb0pqlgbrjsxdsilm4g-kitty-0.36.1.drv' failed with exit code 1;
        last 10 log lines:
        > applying patch /nix/store/pq4w6nf0p1wrcwqmy1v4c1xybz2m11w4-disable-test_ssh_bootstrap_with_different_launchers.patch
        > patching file kitty_tests/ssh.py
        > Hunk #1 succeeded at 150 (offset -16 lines).
        > Running phase: updateAutotoolsGnuConfigScriptsPhase
        > install: skipping file '/dev/fd/63', as it was replaced while being copied
        > Running phase: configurePhase
        > install: skipping file '/dev/fd/63', as it was replaced while being copied
        > Running phase: buildPhase
        > install: skipping file '/dev/fd/63', as it was replaced while being copied
        > The font 'Symbols NERD Font Mono' was not found on your system, please install it
        For full logs, run 'nix log /nix/store/awnxsi0x2wap2wb0pqlgbrjsxdsilm4g-kitty-0.36.1.drv'.
```

### Additional context

Possibly due to nerdfont package variations on darwin

nerdfonts added by #336332 

### Notify maintainers

@fpletz @leiserfg 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
  - system: "aarch64-darwin"
  - host os: Darwin 23.5.0, macOS 14.5
  - multi-user?: yes
  - sandbox: no
  - version: nix-env (Nix) 2.18.4
  - channels(root): "nixpkgs"
  - nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
isn't it like https://github.com/NixOS/nixpkgs/issues/335016?

**Comment by s0me1newithhand7s** [comment]
> No, while that issue is in the logs, the issue here is about the line
> 
> ```
> > The font 'Symbols NERD Font Mono' was not found on your system, please install it
>         For full logs, run 'nix log /nix/store/awnxsi0x2wap2wb0pqlgbrjsxdsilm4g-kitty-0.36.1.drv'.
> ```

hm, can you `(nerd fonts.override {fonts = ["Symbols"];})` or smth like it? ik how much NERD Fonts can weight, so i'm currently using `(nerd fonts.override {fonts = ["Iosevka"];})` :D

**Comment by Tiecoon** [comment]
https://github.com/NixOS/nixpkgs/pull/336332/files is the merge that broke this, it does try to add nerd font symbols, I suspect its a font name mismatch as I have the nerd font symbols but without the all caps NERD. I have not confirmed this yet.

**Comment by leiserfg** [comment]
Maybe in darwin the font is not searched with fontconfig? Sorry, but I don't have a mac to test.

**Comment by leiserfg** [comment]
I found out how to fix it, I will make a pr soon.

**Comment by leiserfg** [comment]
Guys, can you test if this one works in darwin?
https://github.com/NixOS/nixpkgs/pull/338033

**Comment by tmillr** [comment]
> No, while that issue is in the logs, the issue here is about the line
> 
> ```
> > The font 'Symbols NERD Font Mono' was not found on your system, please install it
>         For full logs, run 'nix log /nix/store/awnxsi0x2wap2wb0pqlgbrjsxdsilm4g-kitty-0.36.1.drv'.
> ```

https://github.com/kovidgoyal/kitty/blob/8eb0b556b7651036f804b034c3960cd52a04c5e3/setup.py#L857

It seems that the font file needs to be put in `./fonts`.

**Comment by leiserfg** [comment]
> It seems that the font file needs to be put in `./fonts`.

That's basically my PR

**Comment by Tiecoon** [comment]
Thanks! the proposed merge (leiserfg/nixpkgs/fix-kitty-nerfont) fixes it on my side
