### ISSUE TITLE
Feature Request: configurable `LLVM_ENABLE_ASSERTIONS` flag

### ISSUE THREAD

**Issue by cospectrum** [NixOS/nixpkgs#338065]
## Description

[LLVM_ENABLE_ASSERTIONS](https://llvm.org/docs/CMake.html#llvm-enable-assertions) variable can be turned `ON` in `Release` mode, and as far as I know, it's not the same as `CMAKE_BUILD_TYPE=Debug`. 
Feature can be implemented with backward compatibility in [libllvm](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/compilers/llvm/common/llvm/default.nix#L42).
This feature will allow you to use `LLVM` in both fast and safe mode.

**Comment by cospectrum** [comment]
I noticed that https://github.com/NixOS/nixpkgs/pull/342040 introduced the way to add extra cmake flags to llvm in `unstable` branch. 
So now it should possible to pass `LLVM_ENABLE_ASSERTIONS` or any other cmake flag and it will be applied without problems. Am I right? @pwaller

**Comment by pwaller** [comment]
Yep, should work.

**Comment by cospectrum** [comment]
> Yep, should work.

In that case, thank YOU very much! I'm closing the problem.
