### ISSUE TITLE
Update request: paperless-ngx 2.11.4 → 2.11.6

### ISSUE THREAD

**Issue by poperigby** [NixOS/nixpkgs#338000]
- Package name: `paperless-ngx`
- Latest released version: 2.11.6
- Current version on the unstable channel: 2.11.4
- Current version on the stable/release channel: 2.10.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@lukegb @gador @erikarvstedt @leona-ya 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gador** [comment]
See #336797
