### ISSUE TITLE
Burpsuite integrated browser doesn't work (unstable channel, version 2024.6.6)

### ISSUE THREAD

**Issue by l3g0l4s-exe** [NixOS/nixpkgs#338013]
### Describe the bug
In Burpsuite unstable (current version 2024.6.6) the integrated chromium browser doesn't work.

### Steps To Reproduce
1. Open Burpsuite.
2. Go to "Intercept" tab in the "Proxy" section.
3. Click on "Open browser" button.

### Expected behavior
When you click "Open browser" button on "Proxy" section the integrated chromium browser should start.

### Additional context
The bug is not present in stable version (2024.1.1.4).

### Notify maintainers
@benno

### Metadata
```
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240824.d0e1602`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/ia1zpg1s63v6b3vin3n7bxxjgcs51s2r-source`
 ```
---

**Comment by cryptoluks** [comment]
Hey @l3g0l4s-exe,

For me adding `mesa`  to `targetPkgs` fixed the browser issue, see my PR https://github.com/NixOS/nixpkgs/pull/340953.

Cheers

**Comment by l3g0l4s-exe** [comment]
Thanks @cryptoluks!

I'll wait for the merge into nixpkgs.

**Comment by l3g0l4s-exe** [comment]
@cryptoluks I checked after your PR was merged but the browser still doesn't spawn :(

**Comment by cryptoluks** [comment]
> @cryptoluks I checked after your PR was merged but the browser still doesn't spawn :(

Which commit did you try? Since the last issue, the browser has had a new requirement related to a `udev` dependency.

Please refer to [this pull request](https://github.com/NixOS/nixpkgs/pull/350961) and [this issue](https://github.com/NixOS/nixpkgs/issues/351081).

Replacing `libudev0-shim` with `udev` seems to resolve the issue in more recent versions.

**Comment by l3g0l4s-exe** [comment]
Hi @cryptoluks, I was using the #350767. However I updated to #350961 and now the built-in browser works!

I can close the issue, thanks @cryptoluks, @rhysmdnz, @ttrssreal and @Mindavi.
