### ISSUE TITLE
Mirrored Boot option for systemd-boot

### ISSUE THREAD

**Issue by Astralchroma** [NixOS/nixpkgs#338017]
For a system where redundancy is a goal, it may be preferable to have multiple EFI System Partitions across multiple drives, so that if one drive fails, there is still a usable EFI System Partition.

While this can be accomplished using `mdadm` using an older metadata version, it is somewhat of a hack and shouldn't be used as a go-to solution.

NixOS does provide the capacity to mirror /boot when using GRUB (see `boot.loader.grub.mirroredBoots`), however the option is not available for `systemd-boot`, which I would prefer to use.

This shouldn't be too difficult to implement given that `systemd-boot`'s `bootctl` supports installing to alternate directories using the `--esp-path` option.

**Comment by eclairevoyant** [comment]
See #246897 for prior art
