### ISSUE TITLE
Update request: meli 0.8.6 → 0.8.7

### ISSUE THREAD

**Issue by devurandom** [NixOS/nixpkgs#338191]
- Package name: meli
- Latest released version: 0.8.7

- Current version on the unstable channel: 0.8.6
- Current version on the stable/release channel: 0.8.5

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@0x4A6F, @matthiasbeyer

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by devurandom** [comment]
Release notes: https://git.meli-email.org/meli/meli/releases/tag/v0.8.7

This will not fix https://github.com/NixOS/nixpkgs/issues/332957#issuecomment-2278578811, since `time` is still at `v0.3.28` in meli 0.8.7.  It was only updated in https://git.meli-email.org/meli/meli/commit/6b05279a0987315c401516cac8ff0b016a8e02a8, which is not part of any release yet.

**Comment by matthiasbeyer** [comment]
Sure, do you want to PR an update?

**Comment by devurandom** [comment]
> Sure, do you want to PR an update?

I created https://github.com/NixOS/nixpkgs/pull/338258.  It builds, but tests failed locally with "`m4` executable not found in PATH".  In addition to fixing that I also need to work through https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md.

**Comment by devurandom** [comment]
> Sure, do you want to PR an update?

https://github.com/NixOS/nixpkgs/pull/338258 is done from my point of view, apart from some error in the ofborg-eval-darwin job that I can't explain and don't know how to solve: https://github.com/NixOS/nixpkgs/pull/338258#issuecomment-2322562064
