### ISSUE TITLE
Nikola: included media directive needs micawber (Python Module)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#33825]
## Issue description

While building a static website and also in the final result appears this warning:

`In order to use the media directive, you must install the "micawber" Python package.`

Example: https://davidak.de/blog/175-davideo-design/

cc @jluttine

### Steps to reproduce

```
nix-shell -p python36Packages.Nikola
nikola build
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.11, NixOS, 17.09.2610.d83c8080d1e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(davidak): `""`
 - channels(root): `"nixos-17.09.2631.0653b73bf61"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FRidh** [comment]
Seems like an *optional* dependency to me. In that case, you could package this optional dependency and add it to the closure with `python.withpackages`.

**Comment by davidak** [comment]
@FRidh was there a general decision what should be considered optional and not set as dependency?

In this case it is needed for a built-in feature that is not usable without it.

https://getnikola.com/handbook.html#built-in-shortcodes

So the software is not fully usable and we have to provide documentation how a user could still use it.

`python.withpackages` works great, but might be a bit complicated for users who just want to `nix install nikola` and use it.

**Comment by FRidh** [comment]
It's up to the maintainer of the expression to decide what to include. The minimum-required dependencies are included.

**Comment by jluttine** [comment]
I'm open to including more dependencies or making their inclusion easier (how?). If you have good ideas for a guideline on what dependencies to include and what not, feel free to suggest. Now it's just required dependencies.

On February 14, 2018 10:19:52 PM GMT+02:00, Frederik Rietdijk <notifications@github.com> wrote:
>It's up to the maintainer of the expression to decide what to include.
>The minimum-required dependencies are included.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/issues/33825#issuecomment-365732635

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by FRidh** [comment]
With `python.withPackages` you can add whatever you need to the closure.

**Comment by davidak** [comment]
It's a general discussion how we want Nix packages and NixOS to be. Everything-included (like the 3,7 GB texlive) vs minimal (vim + 218 vimPlugins). That's nothing we 3 should discuss and decide in this issue and it should be consistent in any package, to have the best user expereance.

I will ask on IRC if there was such discussion and decision in the past and if not write to the mailinglist. Maybe that way we can find a good solution.
