### ISSUE TITLE
Allow specific versions of playwright browsers

### ISSUE THREAD

**Issue by voidus** [NixOS/nixpkgs#338255]
I am maintaining a project that installs playwright via python package management independent of nix. Since installing browsers via playwright is a pain, we've been setting `PLAYWRIGHT_BROWSERS_PATH` in our devShell with great success.

The downside here is that our playwright version is now subject to the version in nixpkgs. Usually that is not causing much issues, but since playwright 1.38 depends on greenlet 2, which isn't compatible with python 3.12, we're seeing some annoying ripple effects.

It would be great if the playwright browsers code could be restructured in a way that allowed me to specify the version that I need, something like  `PLAYWRIGHT_BROWSERS_PATH = playwright-driver.browsersForVersion "1.46.0"`.

There are multiple PRs in flight that touch this code, so I didn't want to try it myself right now, but it seems doable as far as I can tell and would benefit projects like mine greatly.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
The goal of nixpkgs is to be a comprehensive package collection and distribution, not to provide all possbile versions of a package.

**Comment by voidus** [comment]
Thank you for spelling it out for me, that makes a lot of sense.
