### ISSUE TITLE
Wrong timezone in Proton

### ISSUE THREAD

**Issue by Damianu** [NixOS/nixpkgs#338266]
### Describe the bug

Games ran via steam using proton seem to have wrong timezone.

Games tested:
- Rimworld shows 20:00 instead of 22:00 (I am GMT+2 so it's showing GMT instead of my timezone)
- Valve's Deadlock shows that matchmaking closes at 2am instead of 3am (That one is weird as its only 1h offset?)

### Steps To Reproduce
1. Set timezone, IE ``time.timeZone = "Europe/Warsaw"``
2. Launch any game displaying real clock on steam via proton compatibility layer
3. Time should be wrong

### Expected behavior
Game should display same time as my system

### Additional context
timedatectl displays correct information:
```console
❯ timedatectl
               Local time: czw 2024-08-29 22:47:53 CEST
           Universal time: czw 2024-08-29 20:47:53 UTC
                 RTC time: czw 2024-08-29 20:47:53
                Time zone: Europe/Warsaw (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
❯ steam-run timedatectl
               Local time: czw 2024-08-29 22:47:58 CEST
           Universal time: czw 2024-08-29 20:47:58 UTC
                 RTC time: czw 2024-08-29 20:47:58
                Time zone: Europe/Warsaw (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
### Notify maintainers
@jagajaga 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.3, NixOS, 24.11 (Vicuna), 24.11.20240809.5e0ca22`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/0jr2kk95c34c0b6yxi75q4fqgb43kqkm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kraust** [comment]
Add `unset TZ` to your launch command.

Pretty sure this is a known issue on certain Proton Prefix and not exclusive to NixOS.

**Comment by Damianu** [comment]
Thank you, it worked.
It didn't occur on Arch that's why I assumed it's nix related.
Any place where I can find out more about this issue?

**Comment by Atemu** [comment]
If this is an upstream issue, we don't need to duplicate it here.

**Comment by sersorrel** [comment]
_is_ this an upstream issue? (and which upstream? wine, valve, ...) I'd like a link to something I can subscribe to, if there's anything public. in any case, we have an issue open since the start of this year for a problem that may or may not be the same: #279893

**Comment by Damianu** [comment]
Well if it helps anyone here's my hacky fix that doesn't require env -u TZ for every game:
```nix
    programs.steam.package = pkgs.steam.override {
      extraBwrapArgs = [ "--unsetenv TZ" ];
    };
  };
```

As for it being an upstream issue... I couldn't find any unsolved bug reports in wine/proton about this.

**Comment by Atemu** [comment]
If you can demonstrate that this issue is exclusive to NixOS it's on us to solve of course.

It does look like a duplicate though, so please redirect discussion to that thread.
