### ISSUE TITLE
Update request: input-leap unstable-2023-12-27 → v3.0.1

### ISSUE THREAD

**Issue by Zombiefleischer** [NixOS/nixpkgs#338230]
- Package name: input-leap
- Latest released version: v3.0.1

- Current version on the unstable channel: unstable-2023-12-27
- Current version on the stable/release channel: unstable-2023-12-27

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@KoviRobi @phryneas @Twey @shymega 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by shymega** [comment]
Input Leap has no release yet, and I'm not comfortable with it being packaged as a Git release right now. I would rather we waited. There is _no_ ETA for a release.

**Comment by shymega** [comment]
Development is ramping up again. I guess we could bump the version - but I would like to add a warning that it's built from Git mainline.

There's some breaking changes to the derivation, including filename changes - such as the XDG desktop file.

**Comment by YoshiRulz** [comment]
They released today. https://github.com/input-leap/input-leap/releases/tag/v3.0.0

**Comment by Zombiefleischer** [comment]
They released [v3.0.1](https://github.com/input-leap/input-leap/releases/tag/v3.0.1) with more packages. Until this is updated, I will try the flatpak version.
