### ISSUE TITLE
Package request: lsb_release with name corrected

### ISSUE THREAD

**Issue by MrAwesome1996** [NixOS/nixpkgs#338287]
**Project description**

There is an existing package for lsb_release but it is incorrectly named "lsb-release". Note the _dash_ (-) instead of an _underscore_ (_). This led me on a wild goose chase trying to figure out why, even though the package exists, I kept getting " error: undefined variable 'lsb_release' " on attempt to rebuild.

**Metadata**

Duplicate the contents of   [pkgs/os-specific/linux/lsb-release](https://github.com/NixOS/nixpkgs/tree/a0d6390cb3e82062a35d0288979c45756e481f60/pkgs/os-specific/linux/lsb-release)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Can you explain what you're trying to do? The package follows our naming conventions.

**Comment by MrAwesome1996** [comment]
Sorry, maybe I'm wrong here. Often, the name of the package is the same as the name of the program it's meant to install, so I was sure it was by accident that the package name uses a dash while the program name uses an underscore. It's a subtle difference that took me a long time to notice when I was trying to add lsb_release to my configuration (I kept adding "lsb_release" which does _not_ exist. I should have added "lsb-release").

My thinking with this request was to leave the existing package as-is so as not to break anybody's configuration, but add another where the package has the exact same name as the program (with an underscore). 

If I'm mistaken and there's a good reason for the difference, then apologies for the erroneous request. Maybe instead it would be helpful to highlight the subtle difference in the package description?

**Comment by SuperSandro2000** [comment]
Generally we normalize package names to replace capital letters by lower cased ones and special characters with dashes.

You can find packages via the search https://search.nixos.org/packages?channel=unstable&query=lsb_release
