### ISSUE TITLE
Provide more assistance for users to find SSL certificates (the "unable to get local issuer certificate" problem)

### ISSUE THREAD

**Issue by kevinburke** [NixOS/nixpkgs#3382]
This caused me a big headache yesterday. A solution (for git) is to install cacert and then run GIT_SSL_CAINFO=$HOME/.nix-profile/etc/ca-bundle.crt, but when running outside nixos that environment variable isn't set and there's no warning/indication that you'd need to set anything. 

Basically this means curl/git are broken out of the box.

A nice thing would be to print "Curl has installed but no SSL certificates are currently available, which means all SSL operations will fail. To add SSL certificates, install the cacert package, then set CURL_CA_BUNDLE=$HOME/.nix-profile/etc/ca-bundle.crt in your environment", in bright red, when curl is installed, and a similar message for git.

It would also be nice if the packages just shipped with a certificate list.

**Comment by zimbatm** [comment]
Right now for example nix's curl and wget don't read the Darwin keychain and I'm forced to provide my own SSL_CERT_FILE (aka install nss-cacert) if I want to access any https website. If I do, I don't benefit from the system-wide certs that I installed to access my company's internal services.

I believe a better solution would be to define a system-wide CA store for NixOS and configure OpenSSL to use the host's CA store by default (also on other systems). In NixOS's configuration.nix you would also have a ssl_ca list option to manage the list of certs available in the store. Eg: `ssl_ca = pkgs.cacert.certs - ["china"]`).

**Comment by vcunat** [comment]
> I believe a better solution would be to define a system-wide CA store

We do have that already, at least on NixOS. BTW, I had created an issue for related stuff #8247.

**Comment by chris-martin** [comment]
I've been using nixos for ~6 months and just today encountered this problem with git for the first time. Any idea what changed?

**Comment by laMudri** [comment]
@chris-martin me too. Installing `cacert` didn't seem to help. I don't think it was caused by upgrading anything.

**Comment by zimbatm** [comment]
Added to the 16.03 milestone because we're going to get endless reports if this isn't fixed

**Comment by lally** [comment]
Yup, same here.  ~6 months, then a `stack build` failed getting a github https URL due to this.

**Comment by chris-martin** [comment]
I'm finding that anything I run in `nix-shell` doesn't have certs, but the same packages installed either as `systemPackages` or with `nix-env` work.

**Comment by lally** [comment]
My hacky fix was to put `export GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt` in my .bashrc.

**Comment by mitchty** [comment]
My fix for git clone over https on OS X was to do the following:
```
git config --global http.sslcainfo ~/.nix-profile/etc/ca-bundle.crt
```

It is slightly annoying as it worked fine in February when cloning from https repos without the config change to git.

**Comment by vcunat** [comment]
@chris-martin: the nix-shell problem is something different, I believe. See https://github.com/NixOS/nixpkgs/pull/13445#issuecomment-199190972.

**Comment by rnhmjoj** [comment]
Any update?

**Comment by Pitometsu** [comment]
When I try to just clone something via https:
```
fatal: unable to access 'https://github.com/robbyrussell/oh-my-zsh.git/': SSL certificate problem: unable to get local issuer certificate
```
But via ssh it work.

**Comment by Pitometsu** [comment]
@lally confirm, your hacky fix `GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt` work for me, thanks!

**Comment by spacekitteh** [comment]
can this be fixed properly?

**Comment by spinningarrow** [comment]
Just hit this while playing with Nix. Is this still planned? Looks like it is not included in the 16.03 milestone any more.

**Comment by ivan-m** [comment]
I'm not sure if this is related, but I have the case of an internally hosted Git server where I get this same error when using git/curl, but `openssl s_client -connect domain.com:443` is successful; specifying `~/.nix-profile/etc/ssl/certs/ca-bundle.crt` doesn't make a difference.

(The `openssl` call reveals that the certificate is signed by Go Daddy, which is indeed present in `ca-bundle.crt`.  Using the macOS curl works.)

**Comment by steshaw** [comment]
Ran into this problem today in a nix-shell FHS environment where my build git clones over https. The solution was similar to [this comment](https://github.com/NixOS/nixpkgs/issues/3382#issuecomment-197314856); added cacert to `targetPkgs` and defined `GIT_SSL_CAINFO` in the `fhs.nix`:

```nix
# ...
{
  name = "fhs";
  targetPkgs = pkgs: with pkgs; [
    # ...
    cacert
    # ...
  ];

  # ...
  profile = ''
    PS1="\n$PS1\n\$ "
    export GIT_SSL_CAINFO=~/.nix-profile/etc/ssl/certs/ca-bundle.crt
  '';
  # ...
}
```

**Comment by aisamu** [comment]
Ran into this on OSX (10.14.6) as well, the fix was an adjustment of @mitchty's  https://github.com/NixOS/nixpkgs/issues/3382#issuecomment-198990799

```
git config --global http.sslcainfo ~/.nix-profile/etc/ssl/certs/ca-bundle.crt
```

**Comment by SkyWriter** [comment]
Nice to stumble upon it 6 years after the initial discovery. Still lurking and still causing trouble. For me it was a per project nix-shell and direnv

**Comment by domenkozar** [comment]
Things have improved since, what's really had about this issue is that it needs to be reproducible. Or at the very least, list exact steps and details that led to it.

**Comment by Dav1d23** [comment]
I don't know if it is related, but...

I have a shell.nix like this

`
with import <nixpkgs> {};
stdenv.mkDerivation rec {
  name = "env";

  buildInputs = [
    rustup
    pkgconfig openssl cacert curl
    SDL2 SDL2_ttf
  ];
}
`

and I'm trying to build a cargo project with SDL2 and the "bundled" feature. That is, cargo.toml looks like

`
[dependencies]
sdl2 = {version = "0.34", features=["ttf", "bundled"]}
`

when I try to build, I got

`
   Compiling sdl2-sys v0.34.2
error: failed to run custom build command for `sdl2-sys v0.34.2`

Caused by:
  process didn't exit successfully: `/.../target/debug/build/sdl2-sys-601f99ba1cf727da/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Command 'curl' failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
', /.../.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-sys-0.34.2/build.rs:53:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

Is it related in some ways? Is there a way to get around this issue? (Using NixOs but quite noob in this regard)

**Comment by teto** [comment]
probably look at pkgs/build-support/docker/default.nix that exports `SSL_CERT_FILE = "${cacert.out}/etc/ssl/certs/ca-bundle.crt";`

**Comment by SuperSandro2000** [comment]
I am doing a PR today or in the next days which will fix most issues mentioned in this issue and you only need to set the following envs for the nix-daemon:

```
[Service]
Environment=NIX_GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt
Environment=NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```

**Comment by SuperSandro2000** [comment]
See https://github.com/NixOS/nixpkgs/pull/138011

**Comment by cyounkins** [comment]
Please note that curl reporting `unable to get local issuer certificate` can mean that the bundle was found, but something with the certificates still doesn't work. To distinguish, pass `CURL_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt` as an environment variable to `curl`. That path is appropriate for NixOS but I'm not sure how to find the correct path in other environments.

**Comment by nerosnm** [comment]
I just ran into this too. Setting `CURL_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt` did solve the problem, but is a really annoying thing to have to do just to run `curl`.

**Comment by Izorkin** [comment]
After update curl  to 7.82 http3 connection not working:
```
curl --http3 -v https://cloudflare.com
*   Trying 2606:4700::6810:85e5:443...
* Connect socket 5 over QUIC to 2606:4700::6810:85e5:443
* error setting certificate verify locations:  CAfile: none CApath: none
*   Trying 2606:4700::6810:84e5:443...
* Connect socket 6 over QUIC to 2606:4700::6810:84e5:443
* error setting certificate verify locations:  CAfile: none CApath: none
*   Trying 104.16.133.229:443...
* Connect socket 0 over QUIC to 104.16.133.229:443
* error setting certificate verify locations:  CAfile: none CApath: none
*   Trying 104.16.132.229:443...
* Connect socket 7 over QUIC to 104.16.132.229:443
* error setting certificate verify locations:  CAfile: none CApath: none
* Closing connection 0
curl: (96) error setting certificate verify locations:  CAfile: none CApath: none
```

It worked for me with this patch:
```diff
diff --git a/pkgs/tools/networking/curl/default.nix b/pkgs/tools/networking/curl/default.nix
index c032ba61c12..700111e1eaf 100644
--- a/pkgs/tools/networking/curl/default.nix
+++ b/pkgs/tools/networking/curl/default.nix
@@ -107,10 +107,8 @@ stdenv.mkDerivation rec {
   configureFlags = [
       # Build without manual
       "--disable-manual"
-      # Disable default CA bundle, use NIX_SSL_CERT_FILE or fallback
-      # to nss-cacert from the default profile.
-      "--without-ca-bundle"
-      "--without-ca-path"
+      "--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt"
+      "--with-ca-path=/etc/ssl/certs"
       (lib.enableFeature c-aresSupport "ares")
       (lib.enableFeature ldapSupport "ldap")
       (lib.enableFeature ldapSupport "ldaps")
```

Can this fix be added to NixOS?

**Comment by deliciouslytyped** [comment]
@vcunat was this closed erroneously? Your commit looks like it's just darwin?

**Comment by vcunat** [comment]
I just did the staging workflow, merging this to master indirectly.  I haven't reviewed this particular change.

**Comment by SuperSandro2000** [comment]
> @vcunat was this closed erroneously? Your commit looks like it's just darwin?

Yes which is intentional. The compile flags are workarounds which are only required for darwin and break things on linux.

**Comment by deliciouslytyped** [comment]
Then this should be reopened. I can't reopen it.

**Comment by kevincox** [comment]
Can you explain what is still lacking that makes you think this isn't closed?

**Comment by deliciouslytyped** [comment]
Maybe I missed something but I thought this was a problem on all platforms and the above commit only fixed it on darwin?

**Comment by kevincox** [comment]
The above commit (https://github.com/gador/nixpkgs/commit/a3125da673250ce9d5ca2e2ce3f152db96cc303c) affected all platforms **but** darwin.
