### ISSUE TITLE
Can't get rid of `eurosign`

### ISSUE THREAD

**Issue by dpc** [NixOS/nixpkgs#33847]
## Issue description

I've installed NixOs, and no matter what I do, I always get `eurosign:e` in my `setxkbmap` options which breaks polish letter `ę` on the polish keyboard layout. I really enjoy that letter, and I'm missing it a lot, while euro symbol is useless to me, and if you ask me it was a bad idea to create euro currency in the first place.

```
dpc@spinlock ~> setxkbmap -query 
rules:      evdev
model:      pc104
layout:     pl,us
variant:    ,
options:    eurosign:e
```

I can do `setxkbmap -option ''` which is the only way to get rid of that option at runtime, it seems. But it will come back after logout/reboot.

I've tried

```
  services.xserver.enable = true;
  services.xserver.layout = "pl";
  services.xserver.xkbOptions = "";
```

and it doesn't seem to do anything.

Adding more options, just adds them to `eurosign:e`.

I also tried:

```
  # https://github.com/NixOS/nixpkgs/issues/14318#issuecomment-332214410
  services.xserver.desktopManager.gnome3.extraGSettingsOverrides = ''
    [org.gnome.desktop.input-sources]
    sources=[('xkb', 'cz+qwerty')]
    xkb-options=['']
  '';
```

but it doesn't help. `xkb-options=['']` generates compile time error, which I don't understand (but I'm a Nix noob, so there's that).

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 18.03pre125026.f607771d0f5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(dpc): `""`
 - channels(root): `"nixos-18.03pre125026.f607771d0f5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jtojnar** [comment]
What is the output of

    nix-shell -p gnome3.dconf --run "dconf read /org/gnome/desktop/input-sources/xkb-options"

**Comment by dpc** [comment]
```
[I] dpc@spinlock ~> nix-shell -p gnome3.dconf --run "dconf read /org/gnome/desktop/input-sources/xkb-options"
['eurosign:e']
```

**Comment by jtojnar** [comment]
Okay, you can use `nix-shell -p gnome3.dconf --run "dconf reset /org/gnome/desktop/input-sources/xkb-options"`.

**Comment by dpc** [comment]
@jtojnar Oh, I see what happened now. Thank you for help! It worked perfectly.


I don't know if this stickiness of settings should be addressed or not. My problem is solved, so depending on your judgment please close/leave open the issue.

**Comment by jtojnar** [comment]
We will need https://github.com/NixOS/nixpkgs/issues/54150 to prevent stickiness.
