### ISSUE TITLE
librewolf: defaults to google search engine

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nixpkgs#338439]
### Describe the bug
Default search engine is Google instead of DuckDuckGo.

### Steps To Reproduce
1. Delete ~/.librewolf
2. Start LW browser

### Expected behavior
Default search should be DDG, and google shouldn't even be available, per https://librewolf.net/docs/faq/#how-do-i-add-a-search-engine

### Notify maintainers

@dotlambda @squalus 

### Metadata

Tested using 33b95d073c3de8866da1f3e3d0c23c61f4e5205e

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by squalus** [comment]
I have seen this too. Maybe related? https://codeberg.org/librewolf/issues/issues/1965

**Comment by eclairevoyant** [comment]
I doubt that issue is related, since that issue is setting it to ddg (LW's default) not google (FF's? default).

**Comment by eclairevoyant** [comment]
Yeah, seems to be a nixpkgs issue.

Nixpkgs build:
![2024-08-30_16-56](https://github.com/user-attachments/assets/749342d0-7c80-405a-b3c5-265700884090)

vs librewolf-bin, which I packaged in the PR above:
![2024-08-30_16-54](https://github.com/user-attachments/assets/d3ee0ae0-407a-4f7b-8c8d-3fea259a1e8a)

**Comment by dotlambda** [comment]
Why did you close this?

**Comment by eclairevoyant** [comment]
I've left nixpkgs, please feel free to create a new issue if it's still a concern.

**Comment by dotlambda** [comment]
> I've left nixpkgs

Left for what, if I may ask?

**Comment by Artturin** [comment]
> > I've left nixpkgs
> 
> Left for what, if I may ask?

https://github.com/NixOS/nixpkgs/pull/341075

**Comment by dotlambda** [comment]
@eclairevoyant You can unsubscribe from your own issue. No need to close it.

**Comment by eclairevoyant** [comment]
This shows up in my list of open issues, I'd rather this stay closed, thanks! Copy-pasting the description should be minimal effort.
