### ISSUE TITLE
Python3-3.6.4 could not download from any binary cache

### ISSUE THREAD

**Issue by bryaan** [NixOS/nixpkgs#33852]
## Issue description

Version 17 and 18 tested and affected.  Initial system build/install, build with Gnome enabled.

https://cache.nixos.org/0cwxmyjyh1cr3xss6dqsrpmhcmwk89p4zkr59jpds1171z52k8p8.nar.xz
failed downloading from any binary cache.

Install fails.  :(
![screen shot 2018-01-14 at 3 18 15 am](https://user-images.githubusercontent.com/2250179/34914202-ae08d236-f8db-11e7-8de5-d34c4fc18859.png)

Is there any way to specify nixos to build from source when it can't download from binary caches?

**Comment by vcunat** [comment]
> Is there any way to specify nixos to build from source when it can't download from binary caches?

`--fallback`

**Comment by bryaan** [comment]
@vcunat Doesn't seem to be working with nixos-install nor does `--option fallback true`

**Comment by vcunat** [comment]
I didn't think of that.  It _should_ work with `nix-*` commands and `nixos-rebuild`.

**Comment by bryaan** [comment]
@vcunat It isn't working.  Fails with same error.  So is this itself another bug?

**Comment by vcunat** [comment]
Your log shows download of https://cache.nixos.org/nar/0cwxmyjyh1cr3xss6dqsrpmhcmwk89p4zkr59jpdsll7lz52k8p8.nar.xz and that does seem to work OK itself.  I would suspect some transient network error.  On my side `nix-build` on the very same python path does respect `--fallback` and retries from source (I disconnected network so it couldn't download the binary directly).

**Comment by bryaan** [comment]
Ok, finally the package does seem to be working.  I haven't been using nix build.  Would you be able to point me towards a set of steps that would mimick the function of nixos-install using the other commands?

**Comment by vcunat** [comment]
It's not that easy, unfortunately.  I suppose it would be easiest to copy the `nixos-install` script end edit the `nix-build` commands within.  Or install some minimal system and then use `nixos-rebuild` with a full configuration.

**Comment by bryaan** [comment]
Maybe should have looked at nixos-install script in first place.  Looks like they use nix-env for install and the fallback command must go in `extraBuildFlags`.  Will try it out later and report back.  That is if my inexplicable network error persists at home.

**Comment by bryaan** [comment]
So the nixos-install script uses nix-env but clearly isn't passing the needed variables from invocation to it.  This seems like a good PR.

OTOH I continue to receive the same error.  Even though the file linked above is now downloading fine.  You can see in the attached image that there are a few files below that also fail to download, so it must be those are now failing.  

All this really makes me question how install must be for anyone serious about this.  Could it be that unstable really means unusable?  But I was getting some other errors with 17 as well.

**Comment by bryaan** [comment]
Got it working somewhat:

After install finished:
reboot

Then login and:
sudo sed -i 's/text\.nix/graphical.nix/' /etc/nixos/configuration.nix
sudo nixos-rebuild switch

Now do one final reboot or gnome will logout after login:
reboot

Working Gnome Desktop.

I think this ticket should stay open as there are some outstanding issues in my opinon.

1. nixos-install and nixos-rebuild should allow the `--fallback` and `--keep-going` commands.  And likely more that make sense from the other nix* commands.

2. How could it be my workaround works?  How could the initial install be different when using the exact same config input? That's got to violate nixos's core principal - same input => same ouput!

**Comment by vcunat** [comment]
Unstable isn't unusable at all; it's more about the fact that it's constantly changing.  Download problems don't seem to be common.

1. 👍 
2. your input config is **not** the same.  You did the `sed` command.

**Comment by bryaan** [comment]
Actually the configs I am comparing are the same.  The first config has graphical.nix (Gnome) enabled, but will always fail with that python error.  Now I modify that script to do a text.nix install; that is the only change.  Install works, I get to a boot screen, I run the `sed` command now to switch back to the graphical.nix install, and now the set of config files *is* exactly the same as the non-working original.

Quite sure this shouldn't be happening.

**Comment by FRidh** [comment]
Just tested on current unstable, and all arguments are being passed along so closing.
