### ISSUE TITLE
virtmanager: Namespace LibvirtGLib not available

### ISSUE THREAD

**Issue by lschuermann** [NixOS/nixpkgs#33854]
## Issue description
I just did a fresh installation of NixOS and I am on the unstable channel. When starting `virt-manager` I'm getting the following error message:
```
[nix-shell:~]$ virt-manager 
Traceback (most recent call last):
  File "/nix/store/f0qsv1lmwdfzlbahsscqnqdilriz5xlg-virt-manager-1.4.3/share/virt-manager/virt-manager", line 32, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/nix/store/p6fnhmmvr28ziv19c37hr9n6vkcy25an-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available
```

This happens when installed as a system-package, in the user environment and in the nix shell.

The package works as expected in a `nix-shell` based on the 17.09 release:
`nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.09.tar.gz -p virtmanager`

### Steps to reproduce
Install `pkgs.virtmanager` on a NixOS system with the `unstable` channel selected.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 18.03pre125026.f607771d0f5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5810_5d5b931f`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/33754

**Comment by lschuermann** [comment]
Oh, okay, must have missed that PR. I'll guess we'll just use the old release's version until the fix reached the unstable channel.
