### ISSUE TITLE
Build failure: betterbird

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#338611]
### Steps To Reproduce

1. build *betterbird*

### Build log

https://gist.github.com/KiaraGrouwstra/5dbf7d82a7fad6401a2d6d49114a1d7c

### Notify maintainers

@SuperSandro2000

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.11 (Vicuna), 24.11.20240831.192e740`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`
 - nixpkgs: `/run/current-system/nixpkgs`
 ```

**Comment by SuperSandro2000** [comment]
I don't see any error, so likely your machine is just to weak. You can try reducing cores/max-jobs for nix.

**Comment by xinyangli** [comment]
I think job on hydra also failed, which cause a rebuild on my laptop. See https://hydra.nixos.org/build/271133091. Not sure if I'm making any mistake here?

**Comment by SuperSandro2000** [comment]
There the error is: 

error[E0635]: unknown feature `stdsimd`

which means we need to update betterbird to be hopefully based on a newer thunderbird version which supports a newer rust version

**Comment by SuperSandro2000** [comment]
#339019
