### ISSUE TITLE
Kongress won't start

### ISSUE THREAD

**Issue by lomenzel** [NixOS/nixpkgs#338765]
### Describe the bug
there seem to be missing dependencies for kdePackages.kongress

### Steps To Reproduce
```console
Steps to reproduce the behavior:
➜   nix run nixpkgs\#kdePackages.kongress
qt.qml.typeregistration: Invalid QML element name "Conference"; value type names should begin with a lowercase letter
Calendar  "state-of-the-map-europe-2024"  loaded succesfully
Calendar  "state-of-the-map-europe-2024"  loaded succesfully
QQmlApplicationEngine failed to load component
qrc:/qt/qml/org/kde/kongress/Main.qml:98:9: Type MapView unavailable
qrc:/qt/qml/org/kde/kongress/MapView.qml:11:1: module "QtLocation" is not installed
qrc:/qt/qml/org/kde/kongress/MapView.qml:10:1: module "QtPositioning" is not installed
qrc:/qt/qml/org/kde/kongress/MapView.qml:11:1: module "QtLocation" is not installed
qrc:/qt/qml/org/kde/kongress/MapView.qml:10:1: module "QtPositioning" is not installed
➜   
```

### Expected behavior
open the app

### Additional context
i am at unstable channel. kongress version 24.08.0
the older version at libsForQt5.kongress still works

### Notify maintainers

@ilya-fedin 
@K900
@LunNova
@mjm
@NickCao
@SuperSandro2000
@ttuegel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
➜   nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0-rc5, NixOS, 24.11 (Vicuna), 24.11.20240828.71e91c4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(leonard): `""`
 - channels(root): `"nixos-23.11, nixpkgs-unstable"`
 - nixpkgs: `/nix/store/887hpp8a2i99n9jjwcvz6qkhhhqsvzkg-source`

```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
#338788
