### ISSUE TITLE
firefox-bin: autoupdate to be disabled

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#33884]
## It does not work anyway, only annoys with popups:

![](http://i.imgur.com/RPoC38D.png)

**Comment by jtojnar** [comment]
Maybe this could work? Did not test it though.

https://github.com/jtojnar/nixpkgs/commit/9f2cb862834b94f0fc04ee31cd68ae2d7d2ae0df

**Comment by volth** [comment]
@jtojnar this would work only on fresh installs, where no previous settings found and the defaults is used to create a new profile, right?

**Comment by jtojnar** [comment]
I am not sure but [this article](https://mike.kaply.com/2012/03/15/customizing-firefox-default-preference-files/) seems to suggest they are loaded every time, so it should work unless the user changed the settings.

`patchPhase` is not listed in `phases` attribute, though.

**Comment by globin** [comment]
Generally using `phases` should be avoided, we have `dontBuild` etc. and also defaults that shouldn't configure, build etc. if not necessary.

**Comment by peterhoeg** [comment]
Refer this (this)[https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences#Preferences_files] for all the gory details of the mozilla preference system.

**Comment by schuppentier** [comment]
The arch guys seem to compile this out with a `.mozconfig` option: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/firefox#n109

**Comment by jtojnar** [comment]
@schuppentier this is an issue for package of Mozilla's binary release – we do not compile it.

**Comment by schuppentier** [comment]
Whoops, I'm sorry for that useless comment

**Comment by jtojnar** [comment]
Maybe this: https://www.mozilla.org/en-US/firefox/63.0a1/releasenotes/#changed

**Comment by coreyoconnor** [comment]
@jtojnar That looks about right. A quick read indicates it should be easy enough to add to the required policy file to the firefox derivation. Trying...

**Comment by coreyoconnor** [comment]
Looks to work as expected. Preferences indicate updates are disabled by administrator.

![image](https://user-images.githubusercontent.com/34317/46034113-a8984d80-c0b4-11e8-9ee4-44945238353c.png)
