### ISSUE TITLE
Package request: micro-headless (or similar)

### ISSUE THREAD

**Issue by giorgiga** [NixOS/nixpkgs#338934]
The current `micro` package depends on wayland/x11, making its use in servers unnecessarily cumbersome.

This is nothing a simple overlay can't help with,

```nix
nixpkgs.overlays = [ (final: prev: {
 micro-clionly = prev.micro.override {
  withXclip = false;
  withWlClipboard = false;
 };
}) ];
```

but that requires building the package from source and is yet another thing to learn for newbies (plus, some may not notice the dependencies and inadvertently end up putting wayland on their servers... ask me how I know :wink:).

Would a separate `micro-headless` (or similar name) package be worth it? 
(possibly, together with some `programs.micro` options?)

`micro` mantainers: @AndersonTorres @pbsds

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
We have no explicit policy prohibiting green aliases. I will create something about this.

On the other hand I do not see why creating a dedicated NixOS module for it - at least not now. You can merely throw it at environment.systemPackages and the effect will be the same.

**Comment by pbsds** [comment]
concurrent effort ^

**Comment by AndersonTorres** [comment]
/\ I would suggest a huge load of modifications in your idea, so here is my implementation:  #339368
