### ISSUE TITLE
Update request: datafusion 33.0.0 → 41.0.0

### ISSUE THREAD

**Issue by guhou** [NixOS/nixpkgs#338955]
- Package name: datafusion-cli
- Latest released version: 41.0.0

- Current version on the unstable channel: 33.0.0
- Current version on the stable/release channel: 33.0.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Current version of `datafusion-cli` transitively depends on an old version of the `time` crate, which [breaks on Rust 1.80.0](https://github.com/NixOS/nixpkgs/issues/332957). Since the issue is well and truly fixed upstream, might as well bump the version.

**Notify maintainers**

- @happysalada

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
I would love to help, but my laptop just broke down. If anyone makes a PR, id be happy to help merge it.

**Comment by guhou** [comment]
I made a version bump branch last night, but I was hitting some test failures, and I haven't had a chance to investigate further yet.

**Comment by FliegendeWurst** [comment]
This was done in #344658
