### ISSUE TITLE
Package request: flutter324

### ISSUE THREAD

**Issue by garylkz** [NixOS/nixpkgs#338916]
**Project description**

Flutter SDK version 3.24 is released on Aug 6th. 

**Metadata**

* homepage URL: https://flutter.dev/
* source URL: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.1-stable.tar.xz
* license: bsd3
* platforms: windows, linux, macOS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
Already been PR'd #336650
