### ISSUE TITLE
Apostrophe doesn't render LaTeX blocks in Preview

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [NixOS/nixpkgs#338968]
### Describe the bug
Apostrophe doesn't render LaTeX in Preview Mode, as expected. Instead of rendering maths equations (like `\frac{p}{q}`) as equations, it escape them while surrounding them with either parenthesis or square brackets.

### Steps To Reproduce
1. Declare `pkgs.apostrophe` in `environment.systemPackages`
2. Open Apostrophe's tutorial
3. Open Preview Mode using CTRL+P
4. Navigate to the `Math` section
5. See the equations made in LaTeX escaped instead of rendered with Pandoc LaTeX

### Expected behavior
It should render the equations and any symbols written between `$` or `$$` with pandoc LaTeX, for example showing `\frac{p}{q}` as a fraction and not `\(\frac\{p\}\{q\}\)`

### Screenshots
In editing:
![image](https://github.com/user-attachments/assets/a6775aa4-0862-40ac-8d36-c26ce6ec9f04)

In preview:
![image](https://github.com/user-attachments/assets/4065d1ae-0628-433f-9c43-2ec3300ba8d6)

### Additional context
This behavior is reproducible on both Apostrophe 3.0 and 3.1. (ie. NixOS 24.05 and NixOS 24.11 (unstable)

I also tried installing alongside Apostrophe `pandoc` and `tex-live.scheme-full` and `tex-live.scheme-medium` to no avail.

### Notify maintainers

@aleksana
@sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240804.cb9a96f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4cpakzyvfw1rmm9v5i3387x6jd2h1v86-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
The case is probably due to temp file path.

**Comment by Zhaith-Izaliel** [comment]
I'm not sure what you mean by that? 

If I understand correctly, you're saying this might be happening due to the file being stored in `/tmp` right?
However Apostrophe exhibits this behavior with files already saved in a directory outside of `/tmp` (e.g. in `$HOME/Documents/test.md`)

Can you reproduce the behavior?

**Comment by Aleksanaa** [comment]
Latex rendering is done by regex matching latex expressions and transforming them into pictures by texlive (what a strange decision). Presumably something happened after the image was generated, since the dependency should be satisfied. I was busy with other things when I last wrote this comment, and I'll check it out later today

**Comment by Aleksanaa** [comment]
This is very possibly due to some Flatpak assumptions that normally happen from python devs

**Comment by Aleksanaa** [comment]
`inline_preview.py` is dead code. `latex_to_PNG.py` is dead code. The math rendering should be done by pandoc converting `$$` to `\(\)` and letting mathjax render.
