### ISSUE TITLE
invalid generated fonts.conf

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#338908]
### Describe the bug
49d33d4a6b15330b492a194edc4b67fb20a15fa1

this sed command is not escaped properly

```
sed "5i <include ignore_missing="yes">/etc/fonts/conf.d</include>" -i $dst/../fonts.conf
```

which generates a line like this:

```xml
<include ignore_missing=yes>/etc/fonts/conf.d</include>
```

which is missing double quotes around `yes`

### Notify maintainers

@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yshui** [comment]
error reported by fontconfig:

```
Fontconfig error: "/etc/fonts/fonts.conf", line 5: not well-formed (invalid token)
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
```

**Comment by griffi-gh** [comment]
Can confirm, getting the same issue.

**Comment by griffi-gh** [comment]
also broke my fonts in most of my applications

**Comment by eclairevoyant** [comment]
fixed in b5574c71bec95159d5342c19f6d5221b68c2aaee (#338815)

**Comment by yshui** [comment]
even with this problem fixed my fonts are still messed up...

**Comment by zoechi** [comment]
@eclairevoyant might be #338933
