### ISSUE TITLE
Remove LoveIsGrief from maintainers list

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#339089]
I'm not really active in the nix community anymore after the whole fiasco with that defense contractor and the kicking of that maintainer (can't remember his name... john anduril?). It's not like my PRs added anything important and probably nobody but me uses my packages.

Biggest issue to me is that nix is still on github, but yeah. I'm a nobody to the community nor does being a maintainer in nix really mean anything, so please remove me. I wanna delete my github account anyway.

Edit: just realised that my account will become ghost. This is "LoveIsGrief" that will need removal.

**Comment by khaneliman** [comment]
Just create a PR?

**Comment by JohnRTitor** [comment]
It's Johnringer and yes it's controversial.

**Comment by SigmaSquadron** [comment]
If you're still checking this issue, don't forget that you can still contribute by sending patch files to the NixOS discourse through email, and we'd welcome you back any time!
