### ISSUE TITLE
Build failure: surrealist-2.0.6

### ISSUE THREAD

**Issue by BridgerB** [NixOS/nixpkgs#339056]
### Steps To Reproduce

Attempt to build surrealist version 2.0.6 on NixOS 24.11.
The build fails during the build phase.

### Build log

```
error: builder for '/nix/store/9z32j3nnlb3gndx4bl5k9bsmvqnv5xl2-surrealist-2.0.6.drv' failed with exit code 1;
       last 10 log lines:
       >    |
       > 83 |     let items: Box<_> = format_items
       >    |              ++++++++
       >
       >    Compiling tauri-macros v1.4.3
       >    Compiling open v3.2.0
       > For more information about this error, try `rustc --explain E0282`.
       > error: could not compile `time` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       >     Error failed to build app: failed to build app
       For full logs, run 'nix log /nix/store/9z32j3nnlb3gndx4bl5k9bsmvqnv5xl2-surrealist-2.0.6.drv'.
```

### Additional context

I reported a similar issue here:
https://github.com/NixOS/nixpkgs/issues/336907

### Notify maintainers

@MDM23

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20240831.12228ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/bd4fmzws6n5542khxbifbkr6nrygi232-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
another #332957 failure
