### ISSUE TITLE
Add which to stdenv

### ISSUE THREAD

**Issue by myclevorname** [NixOS/nixpkgs#339152]
When attempting to package [Ndless](https://github.com/ndless-nspire/Ndless), I have to add `which` to the nativeBuildInputs. I ran into issues packaging it because some Makefiles used `which`, and I assumed it was part of `stdenv`. I would like it to get added to `stdenv`.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by winterqt** [comment]
I'd recommended adding it to `nativeBuildInputs`, or patch the calls out. The needs of one package isn't a good reason to increase stdenv's footprint even more.
