### ISSUE TITLE
Release Schedule for 24.11

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#339153]
| | Date | Branches Affected | Events |
|-|--------|----------------------------|------------|
|✔️ | Sep, 27 | - | Ask ecosystems for desired changes, in "Feature Freeze" |
|✔️ | Oct, 11 | All branches | Restrict breaking changes to Release Critical Packages |
|✔️ | Oct, 25 |All branches| Restrict all breaking changes: allow only non-breaking updates and Desktop Manager changes |
|✔️ | Oct, 30 | `master` | (Day before ZHF) merge `staging-next` into `master`, prep for ZHF |
|✔️ | Nov, 1 | `master` | Begin ZHF, Focus on minimizing regressions in PRs targeting `master` |
|✔️ | Nov, 6 | `master` | Merge first `staging-next` fixes into master; begin second `staging-next` cycle |
|✔️ | Nov, 8 | `staging` | Unrestrict all breaking changes; new changes will not be present in `master` before branch-off |
|✔️ | Nov, 12 | `master` | Merge second `staging-next` fix cycle |
|✔️ | Nov, 13 | `staging-next` | Unrestrict all breaking changes; new changes will not be present in `master` before branch-off |
|✔️ | Nov, 14 | `master`, `release-24.11` | Perform Branch-off, create release channels, create new beta / unstable tags |
|✔️ | Nov, 15 | `master`, `release-24.11` | ZHF transitions to "backporting" workflow |
|✔️ | Nov, 16 | `release-24.11` | Prepare for release, finish remaining issues |
| | Nov, 30 | `release-24.11` | Release! Also, ZHF ends |
| | Dec, 6 | - | Release Retrospective Meeting |

*Note*: Dates reflected are in [AoE (Anywhere on Earth) time](https://www.timeanddate.com/time/zones/aoe).

**Comment by ivan** [comment]
@jopejoe1 accidental unpin?

**Comment by RossComputerGuy** [comment]
@jopejoe1 Why the unpin? We keep the release schedule up for every release until the release is done.

**Comment by jopejoe1** [comment]
I did not even realize that I unpinned this, until you pinged me.

**Comment by myclevorname** [comment]
Can you make this issue only closeable by the release managers? I have the permissions to close this, and I hope no one accidentally closes this.

**Comment by emilazy** [comment]
No, that’s not possible. I suggest not closing it.

**Comment by hacscred** [comment]
#296953 should be tagged a release blocker.

**Comment by RossComputerGuy** [comment]
@hacscred Seems like that problem has already been fixed.

**Comment by aviallon** [comment]
> Can you make this issue only closeable by the release managers? I have the permissions to close this, and I hope no one accidentally closes this.

GitHub permissions model is not very fine grained.

**Comment by hacscred** [comment]
> @hacscred Seems like that problem has already been fixed.

It hasn't.

**Comment by dzmitry-lahoda** [comment]
I found that some of staging-next commits are cached https://releases.nixos.org/nixos/unstable/nixos-24.11pre689866.c31898adf5a8/git-revision . How often it cached and how long it lives? (I see couple dozens commits for 24.11pre). How I can track staging-next caches in my flake as they go to release?

**Comment by RossComputerGuy** [comment]
> How often it cached and how long it lives?

You might want to ask in the staging matrix chat.

**Comment by RossComputerGuy** [comment]
We're in the feature freeze, only non breaking changes now.

**Comment by dotlambda** [comment]
I created the [`backport staging-24.11`](https://github.com/NixOS/nixpkgs/labels/backport%20staging-24.11) label because current staging won't be merged into 24.11. Maybe that could be mentioned in the release manual but I guess the label doesn't make too much sense since the branch doesn't exist yet.

**Comment by aviallon** [comment]
Missing reference to current staging-next merge request: https://github.com/NixOS/nixpkgs/pull/354201

**Comment by Mic92** [comment]
Would be good to get nix 2.18 out of the nixos closure for the next release so we only have one nix version: https://github.com/NixOS/nixpkgs/pull/355745

**Comment by aviallon** [comment]
How does one properly override the kernel source with NixOS 24.11?
Before, I overrode `pkgs.linuxKernel.kernels.xanmod.main` with `override`, now it seems like I need to use `pkgs.linuxKernel.kernels.linux_xanmod_latest.overrideAttrs` instead.
I have issues though with `modDirVersion` being wrong while being set in my `overrideAttrs` (whereas it worked before).

**Comment by jficz** [comment]
possibly a stupid question but is there a release notes draft available somewhere?

**Comment by juliusrickert** [comment]
Both the [nixos:release-24.05](https://hydra.nixos.org/jobset/nixos/release-24.05#tabs-configuration) jobset and the [nixos:release-24.11](https://hydra.nixos.org/jobset/nixos/release-24.11#tabs-configuration) jobset have a negative _check interval_ of -129600 (-36 hours). The check interval of the [nixos:release-24.05](https://hydra.nixos.org/jobset/nixos/release-24.05#tabs-configuration) jobset changed from 129600 to -129600 within the last day, while the [nixos:release-24.11](https://hydra.nixos.org/jobset/nixos/release-24.11#tabs-configuration) jobset had a negative check interval for a few days now. Jobsets of older releases still have a [positive](https://hydra.nixos.org/jobset/nixos/release-23.11#tabs-configuration) [value](https://hydra.nixos.org/jobset/nixos/release-23.05#tabs-configuration).

Do you think this is intentional? For five days, the `release-24.11` branch has not been evaluated.

**Comment by vcunat** [comment]
I've been managing these manually now.  More 24.11 evals at this point didn't seem worth the delay of https://github.com/NixOS/nixpkgs/pull/356895 and thus the whole release.

**Comment by TheRealGramdalf** [comment]
If it's too late already it's too late, but I've been trying to get #357105 merged and backported before release. Is that still realistically possible, or would there be additional evals for the backport PR that would delay things?
I'm fine either way, but I'd like to know since if it's been missed I'll need to edit the PR.

**Comment by RossComputerGuy** [comment]
Forgot to mention this yesterday, if it isn't clear or anyone hasn't been on the staging matrix, we have had to delay 24.11 and let a staging cycle go through. There was a regression in curl which broke things and we didn't want it to cause a major impact.

**Comment by Thatoo** [comment]
>  let a staging cycle go through.
@RossComputerGuy may i ask what does that mean and thus how long does a "cycle" last (more or less)?

**Comment by RossComputerGuy** [comment]
Basically we have to wait for #356895, @vcunat might have an idea for how long that'll take. It mostly depends on how fast our builders are able to go through things.

**Comment by vcunat** [comment]
I'm afraid I'd estimate that the next weekend we'll have the binaries and channel including this.

**Comment by llakala** [comment]
> Forgot to mention this yesterday, if it isn't clear or anyone hasn't been on the staging matrix, we have had to delay 24.11 and let a staging cycle go through. There was a regression in curl which broke things and we didn't want it to cause a major impact.

Maybe make an announcement on Discourse saying the same thing?

**Comment by RossComputerGuy** [comment]
The 24.11 1st staging cycle completed. Thank you @vcunat for getting that through. Saturday, Nov 30th, might end up being the day we get the release out. But that doesn't stop anyone from using it right now, we have the channels up but there's that curl netrc issue plus other possible issues ZHF and others have worked through.

**Comment by vcunat** [comment]
To be clear, only the `nixos-23.11-small` channel contains that rebuild right now, but the big ones should follow soon.

**Comment by vcunat** [comment]
`nixos-24.11` updated.

**Comment by osbm** [comment]
When does the iso file on the https://nixos.org/download/ gets updated? Is it a manual process?

**Comment by RossComputerGuy** [comment]
We just got the infrastructure changes merged 30 seconds ago so I assume that makes it happen. The homepage updates are coming in the next 30 seconds as well.

**Comment by AyushmanOfficial** [comment]
Well if i run sudo nix-channel --update then sudo nixos-rebuild switch --upgrade nothing happens??

**Comment by sebaszv** [comment]
Were you already using the 24.11 beta channel, or were you using the 24.05 channel?

**Comment by RossComputerGuy** [comment]
We released! https://discourse.nixos.org/t/nixos-24-11-released/56811

**Comment by AyushmanOfficial** [comment]
> @AyushmanOfficial
> 
> Were you already using the `nixos-24.11` beta channel, or were you using the `nixos-24.05` channel? They are separate channels, so you would need to _change_ to the `nixos-24.11` channel, not update.
> 
> https://nixos.wiki/wiki/Nix_channels
> 
> Here are the instructions for updating from the NixOS manual. Check if you perhaps missed something.
> 
> https://nixos.org/manual/nixos/stable/#sec-upgrading

My bad for the mistake all i did was ran those two commands i read the docs and understoond that i have to add the repo then rebuild
