### ISSUE TITLE
Update request: stirling-pdf 0.26.1 → 0.28.3

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#339229]
- Package name: `stirling-pdf`
- Latest released version: 0.28.3
- Current version on the unstable channel: 0.26.1
- Current version on the stable/release channel: 0.23.1
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

I wasn't sure how to do the update correctly, having never touched Gradle packaging.

**Notify maintainers**
@TomaSajt

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ambroisie** [comment]
Urgh, somehow I messed up my search, I think I accidentally looked for issues instead of PR, as #335873 is already open... Sorry about that.

**Comment by TomaSajt** [comment]
Thanks for merging :)

> I wasn't sure how to do the update correctly, having never touched Gradle packaging.

There was a big rework of the gradle packaging process using the new `mitm-cache` helper program.
The PR's `update.sh` shows an example of how update the cache.
