### ISSUE TITLE
Update request: rqbit 6.0.0 → 7.0.1

### ISSUE THREAD

**Issue by ToasterUwU** [NixOS/nixpkgs#339231]
- Package name: rqbit
- Latest released version: 7.0.1

- Current version on the unstable channel: 6.0.0
- Current version on the stable/release channel: 5.6.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cafkafk 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ToasterUwU** [comment]
@cafkafk if you have any ideas, let me know and i can try them. Otherwise feel free to make a PR yourself and ping me to review it.

**Comment by ToasterUwU** [comment]
Ok, i checked and it requires to go into the subfolder thats needed, than use npm install, before running the actual build command.. I have no idea how to realize that in Nix.

**Comment by Daru-san** [comment]
I am trying to update via pr #350989. Still in progress but getting somewhere.
