### ISSUE TITLE
Update request: gdlv 1.10.0 → 1.12.0

### ISSUE THREAD

**Issue by Zettexe** [NixOS/nixpkgs#339294]
- Package name: gdlv
- Latest released version: 1.10.0

- Current version on the unstable channel: 1.10.0
- Current version on the stable/release channel: 1.10.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@mmlb 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mmlb** [comment]
Whoops looks like my notification settings for gdlv went away so I did not see these new releases. Will update, thanks for the ping!
