### ISSUE TITLE
czkawka - missing ffmpeg dependency (used for comparing videos)

### ISSUE THREAD

**Issue by edermats32** [NixOS/nixpkgs#339308]
### Describe the bug
The czkawka package is missing ffmpeg as a dependency.
https://github.com/NixOS/nixpkgs/blob/6cc3e274c947096556c57d2b05dad5acda395b74/pkgs/by-name/cz/czkawka/package.nix

If ffmpeg is not found you get this error when trying to compare video files:
```
############### ERRORS(2) ###############
Cannot find proper installation of FFmpeg
Similar Videos don't work currently with snap, if you want help look at - ⁨https://github.com/snapcrafters/ffmpeg/issues/73⁩
```
Ignore the snap part, it throws this error when it can't find ffmpeg, regardless if snap or not.

### Steps To Reproduce
1. Don't have ffmpeg installed on you system.
2. Try comparing videos in czkawka
3. czkawka throws error
4. Install ffmpeg
5. No error. Just works.

### Expected behavior
No error. Just works.

### Additional context
First issue I've reported here, hopefully I'm doing this right. 

### Notify maintainers
@AndersonTorres 
@yanganto 
@0x4A6F 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.46, NixOS, 24.05 (Uakari), 24.05.4169.797f7dc49e0b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Before I propose any changes, let me know a thing or two.
When you install both ffmpeg and czkawka, then czkawka finds ffmpeg, correct?

**Comment by edermats32** [comment]
Correct. It finds it no problem.
