### ISSUE TITLE
Read only nix store coupled with NPM global installations

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#3393]
If you have a readonly `/nix/store`, and you try `npm install -g X`, it fails because npm tries to install its global packages into its prefix which is set to `/nix/store/....node-X.X.X/`.

I know that you can install global node packages using `nix-env -i 'node-whatever'`, but is this "non-functionality" intended? (if so it would be great to document these things, it changes the workflow of a lot of programming environments)

I'm thinking that Nix makes a lot of global mutability impossible, but then without global installations, Nix would have to maintain a list of node packages that anyone would ever want, and multiply that by every other programming language with "global" packages.

If Nix + Npm2Nix is intended to be able to replace NPM, and thus become the __one true package manager__, then wouldn't Nix need to support local installations in the same vein as NPM's node_modules, and PHP Composer's vendor directory?

One more thing, there's a possibility that one could install global node_modules in the home directory outside of the immutable `.nix-profile`. http://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

**Comment by sobrecarga** [comment]
npm2nix works on global packages? npm already manages dependencies. Sure, nix is much more powerful, but I think it's best to use npm to manage npm packages.

I'm using vagrant with the following provision script, to use the latest version of nodejs and to install the coffee repl. You may use it.

```bash
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update
nix-env -i nodejs git
nix-collect-garbage
npm config set prefix \'~/mutable_node_modules\'
npm install -g coffee-script
ln -s ~/mutable_node_modules/bin/ ~/bin
```

**Comment by garbas** [comment]
would solution to this be to wrap npm with ``NPM_CONFIG_PREFIX=$HOME/.node_modules``?

**Comment by garbas** [comment]
would solution to this be to wrap npm with ``NPM_CONFIG_PREFIX=$HOME/.node_modules``?

**Comment by garbas** [comment]
would solution to this be to wrap npm with ``NPM_CONFIG_PREFIX=$HOME/.node_modules``?

**Comment by CMCDragonkai** [comment]
I understand Nix better now. :-)
