### ISSUE TITLE
GlamorousToolkit does not work with the recent image

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#339328]
### Describe the bug

GT prints the the following into terminal instead of opening the UI: https://gist.github.com/suhr/6fcac39f88d5f15241f879f280d2888b

### Steps To Reproduce
1. Download the recent image with `GlamorousToolkit-GetImage`
2. Run `GlamorousToolkit --image GlamorousToolkit.image`

### Notify maintainers

@akgrant43

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.4, NixOS, 24.11 (Vicuna), 24.11.20240814.c3aa7b8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.2`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/store/sfycwi72zfjsspidinx56ajaiffpyh17-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by akgrant43** [comment]
Right... recent versions of `patchelf`, i.e. 0.12 and later, fail on the GT VM executable, see https://github.com/NixOS/patchelf/issues/546 .

If I can figure out how to use `patchelf` 0.11 in the [derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/glamoroustoolkit/default.nix) I'll be able to update the build.  Any hints appreciated :-)

**Comment by akgrant43** [comment]
This should be resolved once https://github.com/NixOS/nixpkgs/pull/339546 is merged.

**Comment by akgrant43** [comment]
After accidentally causing a mass ping, the PR is replaced by https://github.com/NixOS/nixpkgs/pull/339709.

**Comment by akgrant43** [comment]
Hi @suhr,
Can you try running the GT VM from NixOS master branch?
This should be resolved now.
(I know there's a 1.1.1 VM, I'll submit the PR soonish).
Thanks!
Alistair

**Comment by suhr** [comment]
Yes, it now works.
