### ISSUE TITLE
OneDriveGui 1.0.3 not compatible with OneDrive 2.5.0-rc3 on unstable 

### ISSUE THREAD

**Issue by michelealbrigo** [NixOS/nixpkgs#339480]
### Describe the bug
A recent update on unstable broke compatibility between OneDriveGui and OneDrive client.

### Steps To Reproduce
1. Update unstable to current version ( 12228ff1752d )
2. Have a OneDrive profile configured in OneDriveGui
4. Open OneDriveGui window

### Expected behavior
OneDriveGui correctly recognizing the cli client

### Screenshots
![Screenshot from 2024-09-04 10-19-31](https://github.com/user-attachments/assets/da36a825-3c96-4f09-b5b5-eee623ff8fa1)

### Additional context
After some investigation on their respective repos, it appears that OneDriveGui 1.0.3 is not compatible with OneDrive 2.5.x, now in rc (and in Nixos unstable) so this is going to stay broken until OneDriveGui releases their 1.1.0 version. There's an open issue on their repository...
https://github.com/bpozdena/OneDriveGUI/issues/114
which points to an alpha release of the new gui...
https://github.com/bpozdena/OneDriveGUI/tree/v1.1.0-alpha0
...so it might be of interest to package that one on unstable.

### Notify maintainers

@afh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.02 MiB download, 0.06 MiB unpacked):
  /nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux
copying path '/nix/store/ffr5qkpiyl0bdz15w1b8hmqnclw6938h-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.11 (Vicuna), 24.11pre674318.12228ff1752d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abraunegg** [comment]
FYI , v2.5.0 will GA 16th September 2024 AEST
