### ISSUE TITLE
Libreoffice crash when pressing F1

### ISSUE THREAD

**Issue by Edwolt** [NixOS/nixpkgs#339532]
### Describe the bug
When pressing F1, the program crashes and opend the document recover dialog

### Steps To Reproduce
1. Open a libreoffice app (libreoffice writer, libreoffice calc, libreoffice impress, ...)
2. Hit F1
3. The app exhibt the document recover dialog

### Expected behavior
Open the help dialog

### Screenshots
![image](https://github.com/user-attachments/assets/66d42d2b-d81d-4160-adc3-f210309345a1)

### Notify maintainers
@raskin

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.47, NixOS, 24.05 (Uakari), 24.05.20240827.36bae45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qubitnano** [comment]
Works with `libreoffice-fresh`

**Comment by Edwolt** [comment]
Thank you, it is working in libreoffice fresh

**Comment by Edwolt** [comment]
Thank you, it worked.
