### ISSUE TITLE
Akku commands print warnings from Guile

### ISSUE THREAD

**Issue by rc-zb** [NixOS/nixpkgs#339501]
### Describe the bug
Akku prints a series of warnings in the format of
```console
WARNING: (guile-user): imported module (rnrs) overrides core binding `<something>'
```
each time its sub-commands get invoked.

### Steps To Reproduce
1. `nix profile install nixpkgs/nixos-unstable#akku`
2. `akku version` (or `akku --help` or some other Akku commands; I haven't test them all, though)
3. the program prints
```console
~ 
❯ akku version
WARNING: (guile-user): imported module (rnrs) overrides core binding `newline'
WARNING: (guile-user): imported module (rnrs) overrides core binding `display'
WARNING: (guile-user): imported module (rnrs) overrides core binding `error'
WARNING: (guile-user): imported module (rnrs) overrides core binding `read'
WARNING: (guile-user): imported module (rnrs) overrides core binding `map'
1.1.0
```

### Expected behavior
If Akku works well, then it is insignificant what bindings are overrided by some modules, and the warning messages should be trimmed.

### Screenshots
![Screenshot_20240904_171449](https://github.com/user-attachments/assets/ee74dc25-2cd6-4658-8d58-0c8b96852c66)

### Notify maintainers
@nagy @konst-aa

### Metadata
```console
~ 
❯ nix shell nixpkgs/nixos-unstable#nix-info --command nix-info -m
error: attribute 'currentSystem' missing

       at «string»:1:1:

            1| builtins.currentSystem
             | ^
 - system: `0`
 - host os: `Linux 6.6.47, NixOS, 24.05 (Uakari), 24.05.20240830.6e99f2a`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by konst-aa** [comment]
Yeah, akku works well enough to nixify its packages (akkuPackages attrset). I'll take a look at suppressing warnings in the next week. Thank you for reporting this!

**Comment by konst-aa** [comment]
So, there was a PR: https://gitlab.com/akkuscm/akku/-/merge_requests/7, merged Feb 8, 2021. We're using v1.1.0, released on Feb 6. I bumped akku to `1.1.0-unstable-2024-03-03`, which removed the `guile-user` warnings, but not `guile: warning: failed to install locale`. Working on it

**Comment by konst-aa** [comment]
Oh, whoops, that's on my end. I didn't have the locale environment variables
