### ISSUE TITLE
`dwl` fails to build in custom flake

### ISSUE THREAD

**Issue by shymega** [NixOS/nixpkgs#339520]
### Describe the bug

Derivation `dwl` does not pass correct arguments to `wayland-scanner`.

### Steps To Reproduce
1. Build the modified `dwl` package in my Flake:
2. `nix run github:shymega/shypkgs-public#dwl`
3. Wait for it to download from Codeberg and build.
4. You will then see that `wayland-scanner` is not being passed the correct arguments.

### Expected behavior

For `dwl` to build.

### Screenshots

No screenshots, but I have a log I've attached to the issue.

### Additional context

Logs:

[dwl-build.log](https://github.com/user-attachments/files/16869908/dwl-build.log)

### Notify maintainers

cc: @AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.48, NixOS, 24.05 (Uakari), 24.05.20240830.6e99f2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Sounds like an issue with your flake, not nixpkgs. Builds just fine on `master`, `nixos-unstable`, and `nixos-24.05`.

**Comment by shymega** [comment]
I'm not sure why it's an issue with my Flake - I was wondering if it was `pkg-config` related. I'll have another look.

**Comment by shymega** [comment]
With the nature of how `dwl` is configured, I suppose reproducibility is dependent on how each user uses it.

What I was curious about, was the lines in the output.

> dwl>    `pkg-config --variable=pkgdatadir wayland-protocols`/staging/cursor-shape/cursor-shape-v1.xml cursor-shape-v1-protocol.h
dwl> usage: wayland-scanner [OPTION] [client-header|server-header|private-code|public-code] [input_file output_file]

I haven't modified protocols in my Flake, which is why I opened an issue. However, the fact `wayland-scanner` is outputting help, suggests to me there's a problem with the arguments passed.

**Comment by shymega** [comment]
OK, so I've fixed the `wayland-scanner` issue by *not* overriding `src`. That doesn't seem right to me, alas.

The next issue is a segfault. I'm not sure if that's Nixpkgs or `dwl` related.

**Comment by eclairevoyant** [comment]
> I'm not sure why it's an issue with my Flake

Because you're not using the `dwl` in nixpkgs, you're using your own package expression, as the nature of dwl is of course to "bring your own code"; why would this relate to nixpkgs?

Also `dwl` is already on `v0.7` in nixpkgs, there's no reason to override the `src`.

The segfault depends on whatever patches you've added and if they're written correctly, etc.

**Comment by shymega** [comment]
>> I'm not sure why it's an issue with my Flake
>
>Because you're not using the `dwl` in nixpkgs, you're using your own package expression, as the nature of dwl is of course to "bring your own code"; why would this relate to nixpkgs?

Point taken. Apologies. I will be closing this issue, as I think it's
relating to `dwl` upstream.

>Also `dwl` is already on `v0.7` in nixpkgs, there's no reason to override the `src`.

It's in v0.7 in master - not unstable, or 24.05. That was why I overrode
it.

>The segfault depends on whatever patches you've added and if they're written correctly, etc.

Yep.

I'll close this issue for now.

**Comment by shymega** [comment]
Just an update: I tried the below command to use `dwl` 0.7 from Nixpkgs unstable.

```shell
$ nix run -L github:nixos/nixpkgs/nixos-unstable#dwl
ac: Unknown GPU, using 0 for raster_config
Cannot find target for triple amdgcn-- Unable to find target for this triple (no targets are registered)
zsh: segmentation fault (core dumped)  nix run -L github:nixos/nixpkgs/nixos-unstable#dwl
```

I still think it's specific to my system, but I wanted to get some input from anyone using a 780M AMD iGPU, to compare notes.

I will not be re-opening this issue at this moment.
