### ISSUE TITLE
Package request: cypress (darwin platform)

### ISSUE THREAD

**Issue by lukas-mertens** [NixOS/nixpkgs#339554]
**Project description**

Cypress is one of the most popular e2e testing tools. We already packaged aarch64-linux + x86-64-linux, but not darwin. Binaries for all platforms are available, see https://cdn.cypress.io/desktop/ => should be easy to do
**Metadata**

* homepage URL: https://cypress.io
* source URL: https://cdn.cypress.io/desktop/

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kolaente** [comment]
I've had a stab at this (with help from Perplexity): https://github.com/kolaente/nixpkgs/commit/9430213318b0aff1be830417e9a4cfff6cbf45b8

Unfortunately, it does not seem to work properly, when I run the built package there's an error stating "this package is broken". I've never packaged something for darwin before, no Idea how to fix this. Happy to take pointers.

**Comment by kolaente** [comment]
Turns out this is a quarantine thing.

Apparently there's an option in the setting in the privacy options where you can allow opening these "untrusted" binaries, once done it will show "hey this is broken, do you want to open it" and if you click yes, it opens.

I guess I'll send a PR then

**Comment by kolaente** [comment]
PR is up: https://github.com/NixOS/nixpkgs/pull/342798
