### ISSUE TITLE
Borgbackup missing FUSE dependency on Darwin

### ISSUE THREAD

**Issue by starptr** [NixOS/nixpkgs#339659]
### Describe the bug
Using `borg mount` fails on an arm Mac machine I have:
```
Runtime Error: borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3,llfuse.
```

### Steps To Reproduce
1. Install `borgbackup`
2. Mount a repo with `borg mount REPO MOUNTPOINT`

### Expected behavior
Borg should successfully mount the repo. (Although I have not tried it myself, the current borg package distributed in Homebrew appears to do so successfully, according to https://github.com/borgbackup/borg/issues/5522.)

### Notify maintainers

@dotlambda @globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.2.0, macOS 14.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
macOS does not ship a FUSE driver. You must install one yourself.

Last time I used a mac the only driver available was osxfuse which is a proprietary kernel extension, so I noped out of that.  
I saw a NFS-based implementation a while ago but I don't know what became of that.

Nix manages userspace components. Kernel components are only touched via NixOS and that's not a thing on macOS.
