### ISSUE TITLE
Package request: NextCloud app richdocumentscode

### ISSUE THREAD

**Issue by britter** [NixOS/nixpkgs#339798]
**Project description**

This app provides a built-in Collabora CODE server with all of the document editing features of Collabora Online. It makes it easier to use NextCloud as an online office suite, because no additional service needs to be deployed.

**Metadata**

* homepage URL: https://apps.nextcloud.com/apps/richdocumentscode
* source URL: https://github.com/CollaboraOnline/richdocumentscode
* license: apache-2.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
c.f. https://github.com/NixOS/nixpkgs/issues/218878

**Comment by winterqt** [comment]
This looks like a dupe of the above issue, no?

**Comment by britter** [comment]
@winterqt I guess, although the other issue lacks a reference to the richdocumentscode app that's required to run the built-in code server in NextCloud.
