### ISSUE TITLE
Update request: coin3d 4.0.2 → 4.0.3

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#339784]
- Package name: coin3d
- Latest released version: 4.0.3
- Current version on the unstable channel: 4.0.2
- Current version on the stable/release channel: 2022-07-27
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@gebner  
@viric

https://github.com/coin3d/coin/releases/tag/v4.0.3  
Release Notes: https://github.com/coin3d/coin/blob/eab55e722d219cbf025f6b9ef7669e1015160728/RELNOTES#L11-L30

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mdorman** [comment]
So this update was made in 28000247e4ca9bc61ac60c66ff9f228df4d94c8b, but unfortunately there is currently a complaint about a hash mismatch that renders it unbuildable:

```
error: hash mismatch in fixed-output derivation '/nix/store/cryjqhbbc9kp0l9bil1pbxm7knc244vl-source.drv':
         specified: sha256-EeLfIu+InGy56zqjhbNle4hPjQmzwqzHA4ODBMjb9kg=
            got:    sha256-dUFmcUOdNc3ZFtr+Hnh3Q3OY/JA/WxmiRJiU2RFSSus=
```

@r-ryantm it seems like you may be responsible for the problematic update.  Thoughts?

**Comment by natsukium** [comment]
Feel free to submit your PR.
I suspect the upstream force-pushed the tag.

**Comment by ormandj** [comment]
https://github.com/NixOS/nixpkgs/pull/342221

**Comment by luzpaz** [comment]
Great. Thanks for all the effort. Closing ticket as resolved :pray:
