### ISSUE TITLE
Setup script fails with '$'\r': command not found' error, preventing package builds

### ISSUE THREAD

**Issue by Bitbitti** [NixOS/nixpkgs#339726]
I'm encountering a persistent error when trying to build packages on NixOS. The error occurs in the Nix setup script, specifically on line 1579: /nix/store/bc0as359y5y067dfp7afrq1f011m9ny3-stdenv-linux/setup: line 1579: $'\r': command not found
This error is preventing me from building packages, including a custom Canon printer driver package.

### System Information:
- NixOS version: 24.05.4169.797f7dc49e0b (Uakari)

### Steps to Reproduce:
1. Create a custom package derivation (in my case, a Canon printer driver)
2. Attempt to build the package using `nixos-rebuild switch`
3. The build fails with the above error

### Full Error Output:
building '/nix/store/q0qfr9f72n8gf26wcnd87wq5i2kn502c-canon-cups-ufr2-custom-5.70.drv'...
Running phase: unpackPhase
/nix/store/bc0as359y5y067dfp7afrq1f011m9ny3-stdenv-linux/setup: line 1579: $'\r': command not found
error: builder for '/nix/store/q0qfr9f72n8gf26wcnd87wq5i2kn502c-canon-cups-ufr2-custom-5.70.drv' failed with exit code 127
error: 1 dependencies of derivation '/nix/store/j95fimzqbq8qja80h6fn2vlmg6979807-X-Restart-Triggers-systemd-udevd.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8la17r5zbv3q4w09plqswh8x7ynqdl8v-cups-progs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jjwj0b0k1i2d22lr28lr3hbj8l36y3r2-hwdb.bin.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fwrn6w0915rhm6jwg6lqqih7fd7223ca-unit-script-add-canon-printer-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f5ria032hpr3h40mmlxk0xv20krzrv0i-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lml2y7gpy1qdw9klcryyylig4xxxam75-nixos-system-nixos-24.05.4169.797f7dc49e0b.drv' failed to build
### Things I've Tried:
1. Updating Nix and NixOS to the latest version
2. Modifying the package derivation to use `dos2unix` on all files
3. Using `gnutar` instead of the default `tar` for extraction
4. Running `nix-store --verify --check-contents` and `nix-store --repair`
5. Adjusting the use of `find`, `xargs`, and `dos2unix` in the derivation

None of these attempts have resolved the issue. The error persists in the Nix setup script itself, suggesting it might be a core Nix issue rather than a problem with my specific derivation.

### Additional Information:
- The error seems to be related to a carriage return character ('\r') in the setup script
- This issue is preventing me from building not just my custom package, but also seems to affect system rebuilds

### Questions:
1. Is this a known issue with the Nix setup script?
2. Are there any workarounds or fixes that can be applied at the user level?
3. Could this be related to how Nix is handling line endings in its core scripts?

Any assistance or insight into this issue would be greatly appreciated. Thank you for your time and effort in addressing this problem.

### Additional Information:
- The error seems to be related to a carriage return character ('\r') in the setup script
- This issue is preventing me from building not just my custom package, but also seems to affect system rebuilds
- The content of lines 1574-1584 in the setup script (/nix/store/bc0as359y5y067dfp7afrq1f011m9ny3-stdenv-linux/setup) is:

  ```bash
      local startTime=$(date +"%s")
      # Evaluate the variable named $curPhase if it exists, otherwise the
      # function named $curPhase.
      eval "${!curPhase:-$curPhase}"
      local endTime=$(date +"%s")
      showPhaseFooter "$curPhase" "$startTime" "$endTime"
These lines appear to be correct and do not contain visible carriage return characters.

The error occurs specifically on line 1579, which is:
eval "${!curPhase:-$curPhase}"

**Comment by Bitbitti** [comment]
### Additional Information:
- The error seems to be related to a carriage return character ('\r') in the setup script
- This issue is preventing me from building not just my custom package, but also seems to affect system rebuilds
- The content of lines 1574-1584 in the setup script (/nix/store/bc0as359y5y067dfp7afrq1f011m9ny3-stdenv-linux/setup) is:

  ```bash
      local startTime=$(date +"%s")
      # Evaluate the variable named $curPhase if it exists, otherwise the
      # function named $curPhase.
      eval "${!curPhase:-$curPhase}"
      local endTime=$(date +"%s")
      showPhaseFooter "$curPhase" "$startTime" "$endTime"

**Comment by ghpzin** [comment]
Could you include custom package you are trying to build.

**Comment by ghpzin** [comment]
Your `pstoufr2cpca` script does something weird and package should not build as is, because this:
```bash
    cp ${./pstoufr2cpca} $out/lib/cups/filter/
    chmod +x $out/lib/cups/filter/pstoufr2cpca
```
it needs to be:
```bash
    cp ${./pstoufr2cpca} $out/lib/cups/filter/pstoufr2cpca
    chmod +x $out/lib/cups/filter/pstoufr2cpca
```
`${./pstoufr2cpca}` would interpolate to store path,so if you cp as you do it would become something like `0nvb5i5baka2hjba4nd0v43dm932mwck-pstoufr2cpca` and next chmod would fail.

About your error thought, I think something has windows newlines which nix can't handle.
Considering it builds fine for me by copy-pasting your code (and fixing problem above), I assume it's in `.nix` file for that package you wrote.

The only ref I could find:
https://stackoverflow.com/questions/78183326/how-to-fix-nix-build-failure-due-to-a-file-using-the-windows-way-to-break-line

**Comment by Artturin** [comment]
> The error occurs specifically on line 1579, which is:
eval "${!curPhase:-$curPhase}"

This indicates there's a problem in your phases. Closing this but you can get support in other channels.
