### ISSUE TITLE
Update request: flutter 3.24.1 → 3.24.3

### ISSUE THREAD

**Issue by kjxbyz** [NixOS/nixpkgs#339816]
- Package name:flutter
- Latest released version:3.24.3

- Current version on the unstable channel:3.24.1
- Current version on the stable/release channel:3.22.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
Done in #346732
