### ISSUE TITLE
Skip rebuilding VirtualBox?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#33984]
## Issue description
When VirtualBox is part of the system configuration, it can take a long time to build from source. When one of the dependencies is updated, it's rebuild, but what is a good way or perhaps workflow to only rebuild VirtualBox when I actually want to. I haven't wanted to upgrade VirtualBox for a long time.

**Comment by jtojnar** [comment]
That is what channels are for. The binary cache should contain packages obtained via channels. You can combine packages from different channels, see https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F
