### ISSUE TITLE
aria2 module not working

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#33991]
Is it possible that somebody forgot to put the aria2.nix line into nixos/modules/module-list.nix

I can't use:
`services.aria2.enable = true;`

and I don't see aria2 entry in module-list-nix

when I try to rebuild I get:
`error: The option services.aria2' defined in /etc/nixos/configuration.nix' does not exist.`

**Comment by jtojnar** [comment]
Indeed it looks like it was forgotten https://github.com/NixOS/nixpkgs/pull/25181.

For now, you can add `<nixpkgs/nixos/modules/services/networking/aria2.nix>` to `imports` attribute in your configuration.

cc @indiscipline
