### ISSUE TITLE
[request] readline module

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#33993]
## Issue description
I have improved my local inputrc and was looking to merge the changes systemwide but I couldn't find a way to do so. I looked as how to change /etc/inputrc but it doesn't seem possible right now:
https://nixos.org/nixos/options.html#readline returns no result.
A quick grep shows `nixos/modules/programs/bash/inputrc` but my understanding is that inputrc is a readline file and not bash so it could deserve a separate module (with enhanced vi mode/emacs mode)

## Technical details

nixos-unstable

**Comment by manveru** [comment]
You can always use this approach for example:

    environment.etc."inputrc".text = ''
      set editing-mode vi
      set bell-style none

      set meta-flag on
      set input-meta on
      set convert-meta off
      set output-meta on
    '';

It'll override the default option default that bash sets. Generally there are no explicit "options" for simply writing files in /etc, you simply set them.

**Comment by teto** [comment]
sorry forgot about this issue. This is indeed what I have been doing. One could argue that a module could propose nicer defaults as well as "enable vi-mode" but that might be overengineering. Closing this then.
