### ISSUE TITLE
Sway display scaling is broken when using flakes

### ISSUE THREAD

**Issue by sburris0** [NixOS/nixpkgs#339933]
### Describe the bug
This may seem like a sway bug, but I am reporting it here because the heart of the problem is a flake-built configuration is behaving differently than a non-flake configuration.

I've been using sway for a long time without any issues on a laptop connected to a usb-c hub via HDMI to a second monitor. I have this second monitor configured with `output DP-5 scale 1.5 resolution 3840x2160@59.996Hz position 1440,0`. Lately, I've been trying to convert my non-flake config into a flake. When I boot a configuration built from a flake (using the same version of sway (1.9) and nixos (24.05)), my second monitor does not work. I notice that somehow this seems to revolve around configuring output scale. It also seemed to not allow changing away from `3840x2160 @ 30.000 Hz` to `3840x2160 @ 59.996 Hz`

There are two facets of the same misbehavior:
1. There is no output on the second monitor and sway reports the following error:
```
[wlr] [types/output/swapchain.c:109] Swapchain for output 'DP-5' failed test
[sway/config/output.c:525] Failed to commit output DP-5
```

I tried using the git version of sway via nix-community/nixpkgs-wayland (a related-looking issue was fixed) and the error is different but the behavior is the same, no output on the second monitor.

2. Scaling seems to be broken
I can remove the output configuration for this monitor from my config and there is output on the display. I check `swagmsg -t get_outputs`, and see that the second monitor has a scale of `1.0`. If I had the configuration back, reload sway, and check again, it is still `1.0`. 

It seems like something is blocking scaling, which is only a fatal issue when first starting sway.

### Steps To Reproduce
1. Build a configuration from a flake with sway and no display manager
2. Configure scaling on a second monitor in sway's config
4. Boot into the generation
5. Log in and type `sway`
6. Observe second monitor not having any output, and error in tty once it exits.

### Expected behavior
I expect sway to be able to output to my second monitor in a flake-built configuration where it does in a non-flake configuration.

### Additional context
It is somewhat strange to me that the monitor is listed as "DP-5" despite being connected via HDMI cable/ports, but this has always been the case.

### Notify maintainers
@primeos @colemickens (apologies if I should be pinging flake devs that I am unaware of)

### Metadata

```console
- system: `"x86_64-linux"`
- host os: `Linux 6.9.3, NixOS, 24.05  (Uakari), 24.05.20240721.63d37cc`
- multi-user?: `yes`
- version: `nix-env (Nix 2.18.5`
- channels(root): `"home-manager, nixos-24.05, nixos-hardware, nixpkgs-unstable"`
- nixpkgs: `/nix/store/lzhqf5y9dcgfkg5f7f96jjc814pgrsqy-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
> the heart of the problem is a flake-built configuration is behaving differently than a non-flake configuration.

I'm certain that's not the case.
There's something different between your old and new config, and you'd need to post both (in, say, a git repo) for someone to compare and assist you.

**Comment by eclairevoyant** [comment]
Btw, there should not be any "conversion" you do when switching to flakes.
All you do is create one extra file, `flake.nix`, then generate its corresponding lockfile, which should take all of about 5 minutes.
I've provided some instructions in https://github.com/eclairevoyant/flake-migration/blob/main/nixos.md

**Comment by colemickens** [comment]
Hey @sburris0, not to pile on but @eclairevoyant is right. Done correctly, a conversion to flake should result in effectively no change to evaluated derivations and their outputs. Something else must be afoot here, and I also agree that it will be hard to track down without being able to glance through your pre-post conversion Nix config. Best of luck, there's lots of helpful people in Matrix if you want something more real-time.

**Comment by Artturin** [comment]
Use nvd to diff the closures

**Comment by sburris0** [comment]
Yeah turns out a new non-flake build has the same problem. Some update caused an issue. Going to close this, may open a new issue later.
