### ISSUE TITLE
gprof2dot does not run when installed with nix-env (ImportError: No module named gprof2dot)

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#33997]
## Issue description

`gprof2dot` runs correctly inside `nix-shell -p gprof2dot`. But if it’s installed with `nix-env -iA nixos.gprof2dot`, it fails with `ImportError: No module named gprof2dot`.

The relevant difference is that `nix-shell` puts `/nix/store/fd6g76g205clp2m3mjs13k1gqknw6sf0-gprof2dot-2015-04-27/site-packages` in `PYTHONPATH`. Presumably this should be taken care of by the binary wrapper, but isn’t.

### Steps to reproduce

This works:

```
$ nix-shell -p gprof2dot --run 'gprof2dot --help'
Usage: 
        gprof2dot [options] [file] ...
```

This does not:

```
$ nix-env -iA nixos.gprof2dot
installing ‘gprof2dot-2015-04-27’

$ gprof2dot --help
Traceback (most recent call last):
  File "/nix/store/fd6g76g205clp2m3mjs13k1gqknw6sf0-gprof2dot-2015-04-27/bin/.gprof2dot-wrapped", line 8, in <module>
    from gprof2dot import main
ImportError: No module named gprof2dot
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.13, NixOS, 17.09.2731.92d088e891e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2731.92d088e891e, nixos-unstable-18.03pre123130.1bc288591ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
Cc: @FRidh

**Comment by FRidh** [comment]
Pushed fbaf5fd6772a935ba9d40283fefec4bd374a8a3f to master and 780d1c451083b458cc86e7fc8a8ceb4721e4c5ea to 17.09.
