### ISSUE TITLE
python312Packages.simpleaudio crash

### ISSUE THREAD

**Issue by amacfie** [NixOS/nixpkgs#339907]
### Describe the bug

simpleaudio in python312Packages crashes after playing a sound. It works in python311Packages

### Steps To Reproduce

`shell.nix`:
```
{ pkgs ? import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/59b1aef59071cae6e87859dc65de973d2cc595c0.tar.gz";
  sha256 = "0kla405dbqmgbpq59svgbfv7q01z2nnpmq8q2x614r9rrfwfyyrn";
}) {} }:

pkgs.mkShell {
  packages = [
    (pkgs.python312.withPackages (ps: [
      ps.simpleaudio
    ]))
  ];
}
```

Run
```
nix-shell
python
import simpleaudio as sa
w = sa.WaveObject.from_wave_file("w.wav")
w.play()
<simpleaudio.shiny.PlayObject object at 0x7f0bab03dbb0>
Segmentation fault (core dumped)
```

### Notify maintainers

@lucus16

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.48, NixOS, 24.05 (Uakari), 24.05.4469.6e99f2a27d60`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matteo-pacini** [comment]
I think it's coming from upstream: https://github.com/hamiltron/py-simple-audio/issues/72

Possibly fixed here: https://github.com/wasertech/py-simple-audio/pull/1
