### ISSUE TITLE
Oracle JDK 8 gets upgraded to Oracle JDK 9 on `nix-env -u`

### ISSUE THREAD

**Issue by phdoerfler** [NixOS/nixpkgs#34005]
## Issue description & Steps to reproduce

Install Oracle JDK 8:

    $ nix-env -i oraclejdk-8u151

Accept license etc… wait a few days until a new update to 8 is out. Show that no other JDK is installed other than 8:

    $ nix-env -q | grep oracle
    oraclejdk-8u151

Now upgrade all packages:

    $ nix-env -u

nix tries to install oracle JDK *9*:

```
Unfortunately, we cannot download file jdk-9.0.4_linux-x64_bin.tar.gz automatically.
Please go to http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html to download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 jdk-9.0.4_linux-x64_bin.tar.gz
or
  nix-prefetch-url --type sha256 file:///path/to/jdk-9.0.4_linux-x64_bin.tar.gz

```

Since I explicitly installed JDK 8 and not 9 I expect nix to only upgrade JDK 8 to a newer version of JDK 8 (e.g. from `8u151` to `8u161`).

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.77, NixOS, 17.09.2799.d9a2891c32e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(philipp): `""`
 - channels(root): `"nixos-17.09.2799.d9a2891c32e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by coretemp** [comment]
Does this help?

```
If there are multiple derivations matching a name in args that have
           the same name (e.g., gcc-3.3.6 and gcc-4.1.1), then the derivation
           with the highest priority is used. A derivation can define a
           priority by declaring the meta.priority attribute. This attribute
           should be a number, with a higher value denoting a lower priority.
           The default priority is 0.
```

and 

```
     The upgrade operation creates a new user environment, based on the
       current generation of the active profile, in which all store paths are
       replaced for which there are newer versions in the set of paths
       described by args. Paths for which there are no newer versions are left
       untouched; this is not an error. It is also not an error if an element
       of args matches no installed derivations.
```
As for how to make upgrades only upgrade within the same major version, which is the behavior you seem to want to have, I don't know.

**Comment by plchldr** [comment]
`nix-env -i [name]` apparently searches in all package names for `name` and in case of multiple results choses one for you. If you want a bit more control in this case, you can use `nox`:
```
>nox oraclejdk-8u151                                                                                                                                                 
Refreshing cache
1 oraclejdk-8u151 (nixos.oraclejdk)
2 oraclejdk-8u151 (nixos.oraclejdk8)
Packages to install:
```
So I'm assuming that you actually installed the first attribute, but that shouldn't have changed recently .. did you perhaps override it somehow?

**Comment by lheckemann** [comment]
`nix-env -u` has the same problem as `nix-env -i` without `-A`. See https://nixos.wiki/wiki/FAQ/nix- env_-iA for details; if you want to have a declarative specification of which packages to have installed, I'd suggest creating an overlay like [LnL's](https://gist.github.com/LnL7/570349866bb69467d0caf5cb175faa74) and running `nix-rebuild` to update your software.

**Comment by phdoerfler** [comment]
so this is not a bug but… working as expected?

**Comment by coretemp** [comment]
@phdoerfler Yes, it's working as designed and documented.
