### ISSUE TITLE
Virtmanager fails to launch

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#34000]
## Issue description

For a few days (maybe 2 weeks or so), virtmanager refuses to start.

Starting from Kicker the icons shows up for a short while, then disappears.

Starting from the terminal I get this feedback:

```
virt-manager
Traceback (most recent call last):
  File "/nix/store/4kl3dca1vrci6hhipnn1l699k662szbv-virt-manager-1.4.3/share/virt-manager/virt-manager", line 32, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/nix/store/p6fnhmmvr28ziv19c37hr9n6vkcy25an-python2.7-pygobject-3.26.1/lib/python2.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available
```

### Steps to reproduce

Use Nixos Unstable and add virtmanager to the list of system installed packages.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.13, NixOS, 18.03pre125130.3a763b91963 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(hyper): `"nixos-18.03pre123638.1258d9a4914"`
 - channels(root): `"nixos-18.03pre125130.3a763b91963"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/issues/33854 and https://github.com/NixOS/nixpkgs/pull/33754
