### ISSUE TITLE
Update request: `osu-lazer` 2024.817.0 → 2024.906.1

### ISSUE THREAD

**Issue by BachErik** [NixOS/nixpkgs#340082]
- Package name: `osu-lazer`
- Latest released version: `2024.906.1`

- Current version on the unstable channel: `2024.817.0`
- Current version on the stable/release channel: `2024.521.2`

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@gepbird @thiagokokada

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by deviantsemicolon** [comment]
This is high priority and should be done ASAP :3
