### ISSUE TITLE
Documentation: define the differences in `valgrind` and `valgrind-light` on search.nixos.org

### ISSUE THREAD

**Issue by goyalyashpal** [NixOS/nixpkgs#340107]
[valgrind-3.23.0]: https://valgrind.org/ "valgrind-3.23.0"

[vg]: https://search.nixos.org/packages?show=valgrind "Default-channel"
[vg-nix]: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/tools/analysis/valgrind/default.nix#L118 "Nix package source for valgrind"
[mrs]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+valgrind-light 

- Package name: valgrind-light
- Latest released version: [valgrind-3.23.0]

## Problem

* Searching for [valgrind][vg] on search.nixos.org/packages shows `valgrind` as well as `valgrind-light`.
* But both these look _exactly_ same except for their package name.
* and the reason for these being different packages is not at all communicated.

Further looking in:
* the "Source" button for both refers to the exact [same file][vg-nix]
  i.e. maybe the differences in light/normal version does NOT matter for Nix

searching the [MRs], it seems that:
+ several other things use valgrind-light in their build process, and
+ their build process might be used outside of nix too, where the light/normal distinction matters
+ and the `valgrind-light` exists only to cater to those packages

## Proposal

* If above observation is correct, then it should be said in description (of say `valgrind-light`) that:

  > In context of nix-pkgs, `valgrind-light` is same as `valgrind`. If you are unsure about which one to use, pick the `valgrind`.

* Or else, if there is some other reason for existence of both these, then that should be put in the corresponding description.
* Or else, if `valgrind-light` used to exist for some reason, but is no longer relevant anymore, then it should be removed.

## Checklist

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

- [x] Not Applicable
  checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions
- [x] Checked the [nixpkgs pull requests][mrs]

**Notify maintainers/last updaters**

@edolstra @trofi @alyssais 

-----

Note for maintainers: Please tag this issue in your PR.

---

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

Add a :+1: [reaction] to [issues you find important].

**Comment by trofi** [comment]
Looking at the current definition of `valgrind-light` the only difference is no `gdb` hardcoding as a dependency (`gdb` is usually not needed for non-interactive use like tests): https://github.com/NixOS/nixpkgs/blob/f6330df71841e65bdb2e0afd196b6fd88f0a1c6b/pkgs/top-level/all-packages.nix#L19126

**Comment by goyalyashpal** [comment]
> \<... link ...>

ohww, didn't know there's yet another thing modifying the package description. 


```nix
  valgrind-light = res.valgrind.override { gdb = null; };
```


[lldb-mi-repo]: https://github.com/lldb-tools/lldb-mi "lldb-mi"
[nix-pkgs]: https://search.nixos.org/packages?show=lldb-mi "search.nixos.org/packages"

> the only difference is no `gdb` hardcoding as a dependency (`gdb` is usually not needed for non-interactive use like tests)

so, would that be useful to someone who's not using `gdb` otherwise?
as i might have been that "someone", had the <tt>[lldb-mi][lldb-mi-repo]</tt> been available in [nix-pkgs] :smiley: :laughing:

**Comment by eclairevoyant** [comment]
Well `valgrind-light` can override the `meta.description` too, that would resolve this issue.
