### ISSUE TITLE
No audio with tor-browser-bundle-bin-7.0.11

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#34012]
## Issue description
Was using tor-browser-bundle-bin-7.0.7 based on firefox 52.4. Everything worked as expected once using:
```
torbrowserWithAudio = pkgs.torbrowser.override {
      audioSupport = true;
      mediaSupport = true;
    };
```
Upgraded to tor-browser-bundle-bin-7.0.11 based on firefox 52.5. Video is still present but audio is gone.
I also see the bar-pop-up informing that I should have pulseaudio to play audio.

I don't have pulseaudio on the system and at least with 7.0.7 everything worked fine.
I'm aware that the pulseaudio issue has more to do with Firefox but I was under the impression that the pulseaudio-only change was introduced with Firefox 52.0, meaning 52.4 should already be affected but it seems like it wasn't. Not sure how it works there...

On another system I've managed to use `apulse` to have sound without pulseaudio. This required [patching](https://github.com/i-rinat/apulse#per-app-rpath-trick) one of the libs in Firefox.
Could something like this be made available in the nix expression so we could have:
```
torbrowserWithAudio = pkgs.torbrowser.override {
      audioSupport = true;
      useApulseAudioWorkaround = true;
      mediaSupport = true;
    };
```
----

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.75, NixOS, 17.09.git.2223d06 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.1547.2231575a7d"`
 - channels(unode): `"nixos-unstable-18.03pre117690.ab2cc75f78"`
 - nixpkgs: `/var/nixpkgs-channels/nixos-17.09`
```

**Comment by joachifm** [comment]
The version in master uses apulse already, those changes are not currently backported to 17.09, however.

**Comment by unode** [comment]
Thanks for the info, I see the new `pulseaudioSupport` attribute.
I'll pull this to my master branch for testing and report if it works.

**Comment by unode** [comment]
I can confirm master works as expected. Feel free to close this or later once backported.

**Comment by joachifm** [comment]
It's good to know that it works for somebody other than me :) Thanks for testing. I'll probably backport eventually.
