### ISSUE TITLE
Plasma5 forces "breeze" theme for SDDM

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#34027]
## Issue description
When using Plasma5 as desktop manager, it is impossible to set a theme for SDDM via services.xserver.displayManager.sddm.theme because "breeze" is hard-coded in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/plasma5.nix on line 194-196

I am not sure, if there is a technical reason why "breeze" is hard-coded there, but if there isn't, it shouldn't be.

### Steps to reproduce
Set
`  services.xserver.desktopManager.plasma5.enable = true;
`
and 
`services.xserver.displayManager.sddm.theme = "maledives";` or any other pre-installed SDDM theme

`nixos-rebuild`

`error: The unique option services.xserver.displayManager.sddm.theme is defined multiple times, in /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/services/x11/desktop-managers/plasma5.nix and /etc/nixos/configuration.nix.
`

### Technical details

The option is hard-coded on 17.09 aswell as on master, so I guess this does not matter.

**Comment by michaelpj** [comment]
That's odd, it's set using `mkDefault` which should mean that it just gets overridden by any other setting. Not sure what's going wrong there.

**Comment by va1entin** [comment]
Sorry, it seems my firefox had a caching issue, which is why it did not show me the `mkDefault`. After clearing my cache it was suddenly there. Anyway thanks for clearing that up!

**Comment by michaelpj** [comment]
To be clear, that means it does work when you set it manually?

**Comment by va1entin** [comment]
I am currently on 17.09 and plasma5.nix sets the value without mkDefault on that branch, unlike the plasma5.nix on master. I switched to nixos-unstable yesterday, but it broke my entire KDE so I couldn't check so far.

**Comment by michaelpj** [comment]
Makes sense, thanks for checking!

**Comment by plchldr** [comment]
I'm not sure whether it's clear, but all [mkDefault](https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L486) does is tagging the value with a lower priority than default. So if you want to stay on stable, an easy workaround would be using [mkForce](https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L487) to increase the priority of your theme.

**Comment by va1entin** [comment]
@plchldr Thanks for the clarification. mkForce does the trick in 17.09 👍
