### ISSUE TITLE
Update request: polars 0.20.15 → 1.6.0

### ISSUE THREAD

**Issue by computerscience-person** [NixOS/nixpkgs#340233]
- Package name: python3Packages.polars
- Latest released version: 1.6.0

- Current version on the unstable channel: 0.20.15
- Current version on the stable/release channel: 0.20.15

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

- @happysalada

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
There is a PR pending and one of the polars maintainers is helping actually. You can follow the PR or have a look as well if you want to help.
