### ISSUE TITLE
docker containers can't access Nvidia GPUs without virtualisation.docker.enableNvidia even though the option is deprecated

### ISSUE THREAD

**Issue by enolan** [NixOS/nixpkgs#340386]
There's a deprecation warning on `virtualisation.docker.enableNvidia` that tells you to turn on `hardware.nvidia-container-toolkit` instead. But if you only turn on the latter you get:

```console
enolan@chonk ~> docker run --gpus all --rm nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Whereas if you turn on both you get:
```console
enolan@chonk ~> docker run --gpus all --rm nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi
Sat Sep  7 21:38:28 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2080        Off |   00000000:01:00.0  On |                  N/A |
| 26%   38C    P5             16W /  225W |     343MiB /   8192MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

It also works with only `enableNvidia`.

### Expected behavior
It should work with `hardware.nvidia-container-toolkit` enabled alone. Or the deprecation warning should be removed and the documentation updated if this is somehow expected behavior.

### Notify maintainers

There's no `meta.maintainers` field but @ereslibre @con-f-use have touched docker stuff in the last year.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.05 (Uakari), 24.05.4639.6f6c45b5134a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - channels(enolan): `"unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ereslibre** [comment]
Hello @enolan,

Thank you for your report. You can have both options enabled, `virtualisation.docker.enableNvidia` and `hardware.nvidia-container-toolkit` as you mention.

We are going to improve the manual with the documentation on this so it's more clear. We still have to work on this; `deprecated` might be too strong of a word, and maybe we should CDI is recommended rather than `virtualisation.docker.enableNvidia` is deprecated.

- When you set `virtualisation.docker.enableNvidia`, you can access the GPU's through the 
Nvidia runtime wrapper, like:

```shell-session
# Argument is --gpus
$ docker run --rm -it --gpus all ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

You can choose specific GPU's:

```shell-session
# Argument is --gpus
$ docker run --rm -it --gpus '"device=0,1"' ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

- When you use `hardware.nvidia-container-toolkit`, you can access the GPU's through the CDI mechanism, like this:

```shell-session
# Argument is --device
$ docker run --rm -it --device=nvidia.com/gpu=all ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

```shell-session
# Argument is --device
$ podman run --rm --device=nvidia.com/gpu=all ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

You can choose specific GPU's:

```shell-session
# Argument is --device (can be repeated)
$ docker run --rm -it --device=nvidia.com/gpu=0 --device=nvidia.com/gpu=1 ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

```shell-session
# Argument is --device (can be repeated)
❯ podman run --rm -it --device=nvidia.com/gpu=0 --device=nvidia.com/gpu=1 ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

As an extra, Podman (despite not having `virtualisation.podman.enableNvidia` set), also supports mapping the `--gpus` option to CDI out of the box, so that this works too:

```shell-session
$ podman run --rm -it --gpus=all ubuntu:latest nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-c475e08b-0cc5-f5aa-4326-99699429b449)
GPU 1: NVIDIA GeForce RTX 2080 SUPER (UUID: GPU-5cca1a6f-7cee-b649-40f0-2d3ecb0aa207)
```

We have to improve the manual to include all this information. Please, let us know if something is not clear enough with this explanation!

**Comment by enolan** [comment]
OK, that makes sense. To summarize, there are two methods of accessing
Nvidia GPUs inside Docker containers, `--gpus`, which is older and Nvidia
specific and `--device`, which is newer and lets you access anything that
implements the CDI spec, including Nvidia GPUs.
`virtualisation.docker.enableNvidia` turns on the former and
`hardware.nvidia-container-toolkit` makes the GPUs accessible as CDI
devices. And if you're using `podman` then `--gpus` will use the CDI
interface if `hardware.nvidia-container-toolkit` is turned on.

If that sounds right we successfully communicated :)

**Comment by ereslibre** [comment]
> If that sounds right we successfully communicated :)

You described it perfectly :)

Please, close the issue if everything is fine! As I said, we are working on improving the documentation on this. Thanks!
