### ISSUE TITLE
Update request: osu-lazer 2024.906.1 → 2024.906.2

### ISSUE THREAD

**Issue by deviantsemicolon** [NixOS/nixpkgs#340393]
- Package name: osu-lazer-bin
- Latest released version: 2024.906.2

- Current version on the unstable channel: 2024.817.0(will be 2024.906.1 soon)
- Current version on the stable/release channel: 2024.512.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@gepbird 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Seems like the package was updated to `2024.906.2` but the PR title wasn't updated, so the [merge commit](https://github.com/NixOS/nixpkgs/commit/7f9021100c3cfb006b0745a478ad6e00a02ad1b3) has the incorrect version.

**Comment by gepbird** [comment]
Sorry about that, I always forget to update the PR title.
