### ISSUE TITLE
Package request: python3Packages.psycopg-pool

### ISSUE THREAD

**Issue by sarahec** [NixOS/nixpkgs#340355]
The latest version of `python3Packages.langgraph-checkpoint-postegres` exposes a new dependency on `python3Packages.psycopg-pool`. We have an existing python3Packages.psycopg that builds psycopg-pool but doesn't appear to export it.

Out of an abundance of caution, I want to ask: should I duplicate the existing setup to build psycopg-pool standalone (and make it a dependency of the psycopg build), or is there something else I should do?

@mweinelt your thoughts please?

P.S. This is a blocker for #340224 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
You can just referene `psycopg.optional-dependencies.pool`.

**Comment by sarahec** [comment]
You are a rock star. Thank you so much.

**Comment by mweinelt** [comment]
And no we have attributes for `psycopg-pool`and `psycopg-c` as well.
