### ISSUE TITLE
nixos-install --chroot option

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#34033]
Reposting from: https://github.com/NixOS/nixpkgs/commit/186c120bed6b5d4a9b1549159aa567005402000c#commitcomment-26939448

@copumpkin This --chroot option is a bit strange. It enabled me to rebuild my corrupted boot partition by basically setting up my OS while booted in via USB NixOS distro. However before I could I actually run nixos-rebuild, I needed to create /run/user/0. Perhaps this --chroot option should also do this as well. Otherwise it cannot create the temporary files/directories for running nixos-rebuild.

I also had to be careful with NIXOS_CONFIG setting (because the configuration.nix) may not be at the default position. And afterwards NIX_PATH when invoking the nixos-rebuild.

**Comment by lheckemann** [comment]
Perhaps systemd-nspawn would be a better option for entering the system properly?

**Comment by pvgoran** [comment]
The nixos-install's man page mentions the `--chroot` option, but it isn't currently implemented! This is quite confusing. Can we merge the code that re-enables it (https://github.com/NixOS/nixpkgs/commit/186c120bed6b5d4a9b1549159aa567005402000c)?

Luckily, there is now the separate `nixos-enter` utility that has the same functionality. So I suppose the proper course of actions would be to re-enable `nixos-install --chroot` but add a deprecation warning that points to `nixos-enter`.

**Comment by CMCDragonkai** [comment]
@pvgoran Do you use `nixos-enter` while booted inside the USB NixOS after running `nixos-install`? It might be useful to use to run some pre-initilisation before rebooting after installing.

**Comment by pvgoran** [comment]
@CMCDragonkai I run `nixos-enter` after `nixos-install` from a working NixOS in order to prepare a fresh, runnable NixOS tree for transfer to a different machine. (I also manually create `/tmp` because of #39140.)

**Comment by lheckemann** [comment]
FWIW I removed the `--chroot` option from the docs in 152454d9875cc1df645c5aa01ec41451d985199f (#39798)

**Comment by Ekleog** [comment]
Closing, as AFAIU the issue no longer exists as the option itself no longer exists.
