### ISSUE TITLE
Build failure: grass - db patch is failing on Darwin

### ISSUE THREAD

**Issue by imincik** [NixOS/nixpkgs#340475]
### Steps To Reproduce

1. build *grass*

### Build log

```
grass> patching file db/drivers/mysql/db.c
grass> Hunk #1 FAILED at 52.
grass> 1 out of 1 hunk FAILED -- saving rejects to file db/drivers/mysql/db.c.rej
```

### Notify maintainers

@NixOS/geospatial 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sikmir** [comment]
Patch should be removed, see https://github.com/OSGeo/grass/pull/3325
