### ISSUE TITLE
plasma5: Empty panel displayed 

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34051]
## Issue description
Pressing the rightmost button (with the three horizontal lines) in the screenshot below creates the empty grey panel instead of a panel with some buttons that allow you to do various actions. 
 
![image](https://user-images.githubusercontent.com/34454443/35160073-675173a6-fd3c-11e7-8da3-fe767e6a0ba8.png)

### Steps to reproduce
Unknown, I just used Plasma5 for a few hours, then wanted to use this feature and found it didn't work.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by coreyoconnor** [comment]
Try removing the cache directory for your user. EG: `rm -rf ~/.cache` IIRC there is an existing issue with old QML caches blocking KDE from loading properly.

To get plasma 5 desktops log:

1. restart
2. log into plasma
3. (wait until failure)
4. `journalctl -b 0 -t xsession`

**Comment by peterhoeg** [comment]
Probably safe to close this given the amount of fixes that have gone in since.

**Comment by peterhoeg** [comment]
Most like related to https://github.com/NixOS/nixpkgs/issues/177720
