### ISSUE TITLE
KDiskMark complains about missing .service files

### ISSUE THREAD

**Issue by Ember-ruby** [NixOS/nixpkgs#340705]
### Describe the bug
KDiskMark fails to run tests, showing the error `The name dev.jonmagon.kdiskmark.helperinterface was not provided by any .service files`

### Steps To Reproduce
1. install KDiskMark
2. run it
3. try to start a benchmark 

### Expected behavior
The benchmark should successfully run

### Additional context
Potentially relevant; https://github.com/JonMagon/KDiskMark/issues/85

### Notify maintainers

@symphorien 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2, NixOS, 24.05 (Uakari), 24.05pre604424.d8fe5e6c92d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/d1bbviiqxg3qiw8jyw41b1albw5n5m0c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by symphorien** [comment]
How did you install kdiskmark ?

It must be installed in `environment.systemPackages` in `/etc/nixos/configuration.nix`. nix-env will not work, neither home-manager.

the automatic report says you are on an unreleased version of nixos 24.05, is it true?

**Comment by Ember-ruby** [comment]
> How did you install kdiskmark ?
> 
> It must be installed in `environment.systemPackages` in `/etc/nixos/configuration.nix`. nix-env will not work, neither home-manager.

well, i guess i missed that note, thanks, had it in user packages

> the automatic report says you are on an unreleased version of nixos 24.05, is it true?

what do you mean? i use unstable nixos if that's what you're asking

**Comment by Luflosi** [comment]
Running it via `nix run nixpkgs#kdiskmark` also results in the same error.

**Comment by symphorien** [comment]
yes. Again, kdiskmark needs privileges to work, and these privileges are only granted when installed  in /etc/nixos/configuration.nix. nix-env will not work, neither home-manager, nor nix run, as these are unprivileged.
