### ISSUE TITLE
Update request: musescore 4.3.0 → 4.4.1

### ISSUE THREAD

**Issue by Allyri** [NixOS/nixpkgs#340716]
- Package name: musescore
- Latest released version: 4.4.1

- Current version on the unstable channel: 4.4.0
- Current version on the stable/release channel: 4.3.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@vandenoever
@doronbehar

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
It took me a few seconds to realise you are requesting a backport of all the updates... Here you go (untested):

https://github.com/NixOS/nixpkgs/pull/340719
