### ISSUE TITLE
Update request: vault-bin 1.16.2 → 1.17.5

### ISSUE THREAD

**Issue by nipr-jdoenges** [NixOS/nixpkgs#340821]
- Package name: vault-bin
- Latest released version: 1.17.5

- Current version on the unstable channel: 1.16.2
- Current version on the stable/release channel: 1.16.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@balsoft 
@offlinehacker 
@PsyanticY 
@Chili-Man 
@techknowlogick 
@mkaito 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by techknowlogick** [comment]
I've created PR https://github.com/NixOS/nixpkgs/pull/341233 to resolve this. Likely, the robot stopped working due to upstream changing the contents of the ZIP.
