### ISSUE TITLE
Build failure: ghidra

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#340883]
### Steps To Reproduce

1. build *ghidra*

### Build log

[hydra can produce](https://hydra.nixos.org/build/271733175)

### Notify maintainers

@roblabla @vringar 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.9, NixOS, 24.11 (Vicuna), 24.11.20240909.dbb8828`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0yxz367jcdrhd6695wha6y52i3za3xr4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by liff** [comment]
I think this was broken by the [recent Gradle update](https://github.com/NixOS/nixpkgs/pull/327853#issuecomment-2241186440). Should be fixed [by next Ghidra release](https://github.com/NationalSecurityAgency/ghidra/issues/6724#issuecomment-2231850966).

**Comment by roblabla** [comment]
The "fix" was just a change in build instruction https://github.com/NationalSecurityAgency/ghidra/commit/30628db2d09d7b4ce46368b7522dc315e7b245c5 :^).

I'll prepare a PR to fix it.
