### ISSUE TITLE
overrideAttrs and overlays don't play well together (overrides get invoked twice)

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#34086]
## Issue description

@michaelpj @Ericson2314 If you do an overrideAttrs in a overlay, it gets applied twice.

### Steps to reproduce

Here is an example.  Say we wanted to overlay gnupatch to pass "--disable-merge" to the configure routine.  We would write the following overlay (i.e., put this in *~/.config/nixpkgs/overlays/gnupatch.nix*)

```nix
self: super:  {
  gnupatch = super.gnupatch.overrideAttrs (old: {
    configureFlags = old.configureFlags or [] ++ [ "--disable-merge" ];
  });
}
```

But look what happens when we evaluate it

```bash
nix-instantiate --eval --expr '(import <nixpkgs> {}).gnupatch.configureFlags'
```
```nix
[ "--disable-merge" "--disable-merge" ]
```

Adding `trace` calls shows that the close passed to `overlayAttrs` get invoked twice even though the overlay itself only gets invoked once.

```nix
builtins.trace "overlay invoked" (
  self: super: {
    gnupatch = builtins.trace "gnupatch invoked" (
      super.gnupatch.overrideAttrs (builtins.trace "override invoked" (
        old: {
          configureFlags = builtins.trace (old.configureFlags or []) (
            old.configureFlags or [] ++ [ "--disable-merge" ]
          );
        }
      ))
    );
  }
)
```

```bash
nix-instantiate --eval --expr '(import <nixpkgs> {}).gnupatch.configureFlags'
```
```nix
trace: overlay invoked
trace: gnupatch invoked
trace: gnupatch invoked
trace: override invoked
trace: override invoked
trace: [ ]
trace: [ "--disable-merge" ]
[ "--disable-merge" "--disable-merge" ]
```

It is almost as if `overrideAttrs` has somehow pulled in the final desired `gnupatch` expression (i.e., the already overriden one) and then applied the override to it again (giving it twice applied) despite the fact that it was taken from the prior `gnupatch` expression (i.e., `super.gnupatch.overrideAttr`).

Note that this isn't a simple case of `self` and `super` being mixed up.  Switching them gives an infinite recursion error as expected.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

> - system: `"x86_64-linux"`
> - host os: `Linux 4.9.72, NixOS, 17.09.2484.3aec59c99ff (Hummingbird)`
> - multi-user?: `yes`
> - sandbox: `no`
> - version: `nix-env (Nix) 1.12pre5788_e3013543`
> - channels(root): `"nixos-17.09.2484.3aec59c99ff"`
> - channels(tyson): `""`
> - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by twhitehead** [comment]
Just noticed my overlay invoked trace above is actually a file loaded trace.  Moved it down into the overlay function itself to fix this

```nix
builtins.trace "file loaded" (
  self: super: builtins.trace "overlay invoked" ({
    gnupatch = builtins.trace "gnupatch invoked" (
      super.gnupatch.overrideAttrs (builtins.trace "override invoked" (
        old: {
          configureFlags = builtins.trace (old.configureFlags or []) (
            old.configureFlags or [] ++ [ "--disable-merge" ]
          );
        }
      ))
    );
  })
)
```

```bash
nix-instantiate --eval --expr '(import <nixpkgs> {}).gnupatch.configureFlags'
```
```nix
trace: file loaded
trace: overlay invoked
trace: overlay invoked
trace: gnupatch invoked
trace: gnupatch invoked
trace: override invoked
trace: override invoked
trace: [ ]
trace: [ "--disable-merge" ]
[ "--disable-merge" "--disable-merge" ]
```

and we see the overlay is actually being twice.

This makes more sense.  Perhaps it is as simple as the overlay stack accidentally being duplicated somewhere?  I think I was wrong to think it had something to do with `overlayAttrs` as the traces indicate the overlay is being  applied twice even without `overlayAttrs`.

```nix
builtins.trace "file loaded" (
  self: super: builtins.trace "overlay invoked" ({
    gnupatch = "move along";
  })
)
```

```bash
nix-instantiate --eval --expr '(import <nixpkgs> {}).gnupatch'
```
```nix
trace: file loaded
trace: overlay invoked
trace: overlay invoked
"move along"
```

Cheers!  -Tyson

**Comment by Ericson2314** [comment]
@nbp you have any idea what's going on?

**Comment by nbp** [comment]
I have no idea what might be wrong here.  From my point of view the only way this could happen is if the overlay is listed twice, or included twice.

Trying locally with an old version of Nixpkgs does not reproduce the issue:
```
trace: file loaded
trace: overlay invoked
"echo"
```

But I can reproduce it with a recent master of Nixpkgs:
```
trace: file loaded
trace: overlay invoked
trace: overlay invoked
"echo"
```

So, I confirm that this is a regression in Nixpkgs, which is not the expected behaviour.

**Comment by twhitehead** [comment]
Another data point that, unfortunately, just makes things even more confusing (at least in my mind).

Here is a  modified version that explicitly counts the number of times things aggregate.  Both inside a `overrideAttrs` and outside of `overrideAttrs` in an overlay.

```nix
builtins.trace "file loaded" (
  self: super: builtins.trace "overlay invoked" ({
    gnupatch = super.gnupatch.overrideAttrs (old: {
      count = old.count or 0 + 1;
    });
    count = super.count or 0 + 1;
  })
)
```

```bash
nix-instantiate --eval --expr '(import <nixpkgs> { }).count'
```
```nix
trace: file loaded
trace: overlay invoked
trace: overlay invoked
1
```

```bash
nix-instantiate --eval --expr '(import <nixpkgs> { }).gnupatch.count'
```
```nix
trace: file loaded
trace: overlay invoked
trace: overlay invoked
2
```

So it seems that, while the overlay is indeed evaluated twice, the two evaluations are only aggregated inside of `overrideAttrs`.  Very strange indeed.

**Comment by twhitehead** [comment]
@nbp What old  version of nixpkgs do you have that doesn't exhibit this issue?  I tried all the way back to 17.03-beta\~1836 without find anything (using the `overlay = ...` option get around the change to *~/.config/nixpkgs* without).  Before then I can't get overlays to work at all.  With a working commit version it would be pretty trivial to `git bisect` it.  Thanks!

**Comment by twhitehead** [comment]
Another data point.  An insightful one this time I hope.  I tried building a `test` attribute up bit by bit in _all-packages.nix_ to track this down and couldn't replicate the problem.

After much head scratching, I finally discovered that this only happens (in my limited testing) with the tools used by `stdenv`.  That is, if we do the following override

```nix
builtins.trace "file loaded" (
  self: super: builtins.trace ("overlay invoked: ${toString ((super.count or 0) + 1)}") ({
    count = (super.count or 0) + 1;

    gnupatch = super.gnupatch.overrideAttrs (old: { count = (old.count or 0) + 1; });
    gawk = super.gawk.overrideAttrs (old: { count = (old.count or 0) + 1; } );
    bzip2 = super.bzip2.overrideAttrs (old: { count = (old.count or 0) + 1; } );

    atop = super.atop.overrideAttrs (old: { count = (old.count or 0) + 1; } );
    strace = super.strace.overrideAttrs (old: { count = (old.count or 0) + 1; } );
    vim = super.vim.overrideAttrs (old: { count = (old.count or 0) + 1; } );
  })
)
```

the `stdenv` tools  set (the first ones) all give the unexpected `2`

```bash
nix-instantiate --eval --expr '(import <nixpkgs> { }).gnupatch.count'
nix-instantiate --eval --expr '(import <nixpkgs> { }).gawk.count'
nix-instantiate --eval --expr '(import <nixpkgs> { }).gzip.count'
```
```nix
trace: file loaded
trace: overlay invoked: 1
trace: overlay invoked: 1
2
```

while the non-`stdenv`  set (the second ones) all give the expected `1`

```bash
nix-instantiate --eval --expr '(import <nixpkgs> { }).atop.count'
nix-instantiate --eval --expr '(import <nixpkgs> { }).strace.count'
nix-instantiate --eval --expr '(import <nixpkgs> { }).vim.count'
```
```nix
trace: file loaded
trace: overlay invoked: 1
trace: overlay invoked: 1
1
```

**Comment by twhitehead** [comment]
Another data point.  It seems to somehow come from/through the `stdenvOverrides` stage.  If I comment out this stage in _stage.nix_, then I stop seeing the double count from `stdenv` packages.

**Comment by twhitehead** [comment]
Okay, I think I may have wrapped my head around this one.  The final bootstrap stage (provide by _stdenv/linux/default.nix_) provides the following `stdenv.overrides`overlay to the `stdenvOverrides` overlay (provide by _stage.nix_) which passes the previous  stages `stdenv` tools through.  

```nix
      overrides = self: super: {
        inherit (prevStage)
          gzip bzip2 xz bash coreutils diffutils findutils gawk
          glibc gnumake gnused gnutar gnugrep gnupatch patchelf
          attr acl paxctl zlib pcre;
      } // lib.optionalAttrs (super.targetPlatform == localSystem) {
        # Need to get rid of these when cross-compiling.
        inherit (prevStage) binutils binutils-raw;
        gcc = cc;
      };
```

The problem with this is the  previous stages `stdenv` tools  have  already had the overlay stack  applied to them.  Bringing them forward into the next stage results in the all the overlay stack following `stdenvOverrides` (which is currently `[ configOverrides ] ++ overlays`) being applied to them again.

Note that this is  actually a general issue for the whole bootstrapping `stdenv.overrides`  overlay system.  Any tools brought forward from the previous stage via the `stdenv.overrides` is going to suffer  from this and windup with the remainder of the overlay stack applied again to them.

Possibly `stdenvOverrides`  should always be at the end of overlays list in _stage.nix_.  If  it is only used to bring packages forward, this could be valid as previous packages will already have the overlays applied to them.    I don't  know if this is correct, but I'll submit a pull request.
