### ISSUE TITLE
typo : pythonImportCheck instead of pythonImportsCheck

### ISSUE THREAD

**Issue by nim65s** [NixOS/nixpkgs#340809]
### Describe the bug

4 packages have the `pythonImportCheck` attribute, which is a typo for `pythonImportsCheck`

### Steps To Reproduce
1. `rg pythonImportCheck`
2. see 4 packages:

```
pkgs/development/python-modules/pyfunctional/default.nix
37:  pythonImportCheck = "pyfunctional";

pkgs/development/python-modules/python-ffmpeg/default.nix
22:  pythonImportCheck = [ "ffmpeg" ];

pkgs/development/python-modules/pyairports/default.nix
22:  pythonImportChecks = [ "pyairports" ];

pkgs/development/python-modules/geoparquet/default.nix
37:  pythonImportCheck = "geoparquet";
```

### Expected behavior

no result

### Notify maintainers

- [ ] pyfunctional & geoparquet: @Sigmanificient
- [ ] python_ffmpeg: @roshaen 
- [ ] pyairports: @cfhammill 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
I do wish we used `lib.strings.levenshteinAtMost` or such to warn about typos in derivation attrs

**Comment by eclairevoyant** [comment]
> I do wish we used `lib.strings.levenshteinAtMost` or such to warn about typos in derivation attrs

Or at least had a CI check for things like this
