### ISSUE TITLE
dnsmasq : warning: interface enp193s0f3u1 does not currently exist but the interface is shown in ip a output

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#340870]
### Describe the bug
The service shows this warning : 
> warning: interface enp193s0f3u1 does not currently exist 

But the interface is shown in `ip a` output :
```
9: enp193s0f3u1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 9c:bf:0d:00:3f:d5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::290b:f14c:6566:99c2/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

### Steps To Reproduce
1. declare dnsmasq service enabled and in settings set interface=<existing-interface>

- dnsmasq-local.nix

```nix
{pkgs, config, ...}:

{
  services.dnsmasq = {
    enable = true;
    settings = { 
      dhcp-range = [ "192.168.0.2,192.168.0.254" ];
      interface = "enp193s0f3u1";
      # DNS servers
      # QUAD9
      # 0dns.eu
      server = [
        "9.9.9.9"
        "193.110.81.0"
        "185.253.5.0"
      ];
    };
  };
}

```

### Expected behavior
Should work as intended 

### Additional context
I have libvirtd enabled as well, I'm not sure if there is a dnsmasq running from it (when using `virsh net-start default`

The Ethernet port is a Framework Expansion card plugged into the Framework directly through USB-C.

### Notify maintainers
@edolstra @fpletz @globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.8, NixOS, 24.05 (Uakari), 24.05.4736.68e7dce0a653`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"agenix, home-manager-24.05.tar.gz, nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
Documentation is also out of date `bind-interfaces` seems to no longer exists.

**Comment by AkechiShiro** [comment]
I suspect that some of the systemd hardening is hiding the interface but I'm not sure that is right since no one has ever run into this issue before most likely

**Comment by AkechiShiro** [comment]
Using `wlp1s0`, the WIFI's interface is found and properly bound and now it is working...

Maybe there is some kind of race condition between some network service and the dnsmasq service

> DHCP, sockets bound exclusively to interface enp193s0f3u1

**Comment by Slabity** [comment]
`dnsmasq` will wait for `network.target` to be reached before it's started, but that only ensures at least 1 interface is up, not specifically the interface you are looking for.

The warning is benign though, and `dnsmasq` will simply attach itself to that interface once it's actually available. This is probably the behavior you want if you're just trying to set it up as a basic DHCP server.

If you do need `dnsmasq` to wait until that interface is up though, you can either add a `requires` for the service file to wait for that interface. Something like `systemd.services.dnsmasq.requires = [ "sys-subsystem-net-devices-enp193s0f3u1.device" ];`

**Comment by AkechiShiro** [comment]
Thanks for the analysis and solution provided @Slabity 

I'm closing thos issue since it doesn't seem to be a real issue
