### ISSUE TITLE
Typo in oauth2_proxy expression

### ISSUE THREAD

**Issue by joseph-long** [NixOS/nixpkgs#34095]
It appears that `--github-org` is there twice, rather than `--github-org` and `--github-team` as appropriate. See

https://github.com/NixOS/nixpkgs/blob/83fdd2699c5352416b4b97cb306d5039f2ad5ec2/nixos/modules/services/security/oauth2_proxy.nix#L25

**Comment by FRidh** [comment]
cc @jml

**Comment by JohnAZoidberg** [comment]
This has been abstracted and the commandline options are now generated by the config attribute names. -> Fixed
See: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/security/oauth2_proxy.nix#L81

**Comment by knl** [comment]
As noted before, this has been fixed.
