### ISSUE TITLE
Update request: librewolf 129.0 → 130.0

### ISSUE THREAD

**Issue by BasileusErwin** [NixOS/nixpkgs#340993]
**Title:** Update request: librewolf 129.0 → 130.0

- **Package name:** librewolf
- **Latest released version:** 130.0  
  [Search results:](https://search.nixos.org/packages?channel=24.05&type=packages&query=librewolf)
- **Current version on the unstable channel:** 129.0  
  [Search results:](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=librewolf)
- **Current version on the stable/release channel:** 130.0  
  [Search results:](https://search.nixos.org/packages?channel=24.05&type=packages&query=librewolf)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@dotlambda 
@squalus

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
[Already on `master`](https://github.com/NixOS/nixpkgs/pull/340115). Please wait for it to [trickle down](https://nixpk.gs/pr-tracker.html?pr=340115) to `nixos-unstable`.

There is, however, an `r-ryantm` update available for [`130.0-1 -> 130.0-3`](https://github.com/NixOS/nixpkgs/pull/340882).
