### ISSUE TITLE
wechat-uos: OpenSSL 1.1 is end of life

### ISSUE THREAD

**Issue by kaleocheng** [NixOS/nixpkgs#340954]
the package wechat uos is still using OpenSSL 1.1 https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/we/wechat-uos/package.nix#L176 which is end of life on 2023/09/11, so  it is marked as insecure now. 

not sure if we need to wait for wechat-uos or we can just bump it up in here. 

@pokon548 @xddxdd 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pokon548** [comment]
> not sure if we need to wait for wechat-uos or we can just bump it up in here.

As far as I know, only `libuosdevicea.so` from https://github.com/NixOS/nixpkgs/blob/07a86f74421333e7fd379fbce416bf982523887e/pkgs/by-name/we/wechat-uos/package.nix#L240C53-L240C69 depends on OpenSSL 1.1. Seems like we may replace it with [stub implementation](https://aur.archlinux.org/packages/wechat-universal) to completely independent with 1.1.

**Comment by Cryolitia** [comment]
Would it be offensive if I could submit a patch about it now.

**Comment by pokon548** [comment]
> Would it be offensive if I could submit a patch about it now.

Feel free to do so. I would be happy to review your pr :)
