### ISSUE TITLE
nixos-rebuild fails: No space left on device

### ISSUE THREAD

**Issue by KaiLemke** [NixOS/nixpkgs#34091]
[end_build.log](https://github.com/NixOS/nixpkgs/files/1649290/end_build.log)
## Issue description

Hi all,

I'm just wondering, why my workstation fails to update with message 

> No space left on device 

while I cannot see what device should be full.

Compare: 

> └──# df
> Filesystem      Size  Used Avail Use% Mounted on
> devtmpfs        195M     0  195M   0% /dev
> tmpfs           1.9G   14M  1.9G   1% /dev/shm
> tmpfs           972M  4.9M  967M   1% /run
> tmpfs           1.9G  300K  1.9G   1% /run/wrappers
> /dev/sda1       284G  151G  119G  56% /
> tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
> tmpfs           1.9G   40M  1.9G   3% /tmp
> tmpfs           389M  4.0K  389M   1% /run/user/1000
> 
> └──# free -m
>               total        used        free      shared  buff/cache   available
> Mem:           3885         768        2015          65        1101        2866
> Swap:          9832          14        9818
> 

And the last lines of the build log attached.

btw: I am also wondering why it regularly starts compiling packages like libreoffice which should be very common and I am using a stable branch. Shouldn't such packages usually be precompiled in cache.nixos.org?

### Steps to reproduce

> nixos-rebuild test -vvvv --fast 2>&1

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.12, NixOS, 17.09.2683.360089b3521 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2826.5141f28405e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ryantm** [comment]
Hi! 

My guess would be you are exhausting your /tmp directory because I doubt 2 GB is enough to build libreoffice.

It looks like the build on hydra failed yesterday but succeeded today. https://hydra.nixos.org/job/nixos/release-17.09/nixpkgs.libreoffice.x86_64-linux maybe try again? If you are still having to build pkgs like that, maybe post your configuration.nix so we can see if you are modifying the derivations.

Ryan

**Comment by va1entin** [comment]
My machine also began building LibreOffice itself today, but well after the job succeeded again. It succeeded 11h ago, but when I do a `nix-shell -p libreoffice` right now it builds it, instead of using the cache.

**Comment by KaiLemke** [comment]
[pkgs.nix.txt](https://github.com/NixOS/nixpkgs/files/1649350/pkgs.nix.txt)
I started the job just before posting this.

I don't think, I am modifying libreoffice, but have a look at my pkgs.nix

**Comment by peterhoeg** [comment]
The ```No space left on device```  error is expected if you actually run out of space when trying to compile a large package in ```/tmp```. If you are seeing this for other reasons, please re-open.

**Comment by nh2** [comment]
Related: #31133
