### ISSUE TITLE
Package request: nodePackages.@ui5/cli

### ISSUE THREAD

**Issue by DerArkeN** [NixOS/nixpkgs#340952]
**Project description**

OpenUI5 Tooling CLI from SAP

**Metadata**

* homepage URL: https://sap.github.io/ui5-tooling/stable/pages/CLI/
* source URL: https://www.npmjs.com/package/@ui5/cli
* license: Apache-2.0 license
* platforms: node
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
This can easily be packaged using `buildNpmPackage` by symlinking `npm-shrinkwrap.json` to `package-lock.json`.

**Comment by DerArkeN** [comment]
i tried to do some research on this but tbh i have no clue what you are talking about

**Comment by dotlambda** [comment]
Just do
```
postPatch = ''
  ln -s npm-shrinkwrap.json package-lock.json
```
