### ISSUE TITLE
Update Cava to 0.6.0

### ISSUE THREAD

**Issue by StijnDW** [NixOS/nixpkgs#34090]
There have been a few releases since the 0.4.2 release that is currently in nixpkgs.
I have tried to update the version number to 0.6.0 and the sha256 to `01maaq5pfd4a7zilgarwr1nl7jbqyrvir6w7ikchggsckrlk23wr`
Unfortunately that results in a compilation failure:
`gcc: error: /usr/local/lib: No such file or directory`

The cava package comes from github: https://github.com/karlstav/cava/releases
And is defined by the nix package: nixpkgs/pkgs/applications/audio/cava/default.nix

**Comment by ryantm** [comment]
@StijnDW Maybe you can test my PR to see if the application works for you.

**Comment by StijnDW** [comment]
@ryantm Hi, your PR works correctly. Thank you!
