### ISSUE TITLE
Package Request: PokeMMO

### ISSUE THREAD

**Issue by averynoir** [NixOS/nixpkgs#340987]
**Project description**: PokeMMO is a multiplayer online game where players can explore various regions from Pokémon games, battle with others, and trade Pokémon in a persistent online world.

**Metadata**

* **homepage URL**: [https://pokemmo.eu/](https://pokemmo.eu/)
* **source URL**: Closed source (can be downloaded from [official site](https://pokemmo.eu/downloads/))
* **license**: Proprietary
* **platforms**: linux, unix, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
Oh I had this packaged a while ago in my NUR: https://github.com/kira-bruneau/nur-packages/commit/f65a6756dfa99f891ffde7bf17d79f4852161dfc, I'll open a PR for it!
