### ISSUE TITLE
Vivadi stable is newer than Vivaldi unstable.

### ISSUE THREAD

**Issue by iamstonecutter** [NixOS/nixpkgs#341044]
I was eagerly waiting for a Vivaldi update, especially after noticing a pull request was opened last week. Being on the unstable channel, I expected the update to hit the repo sooner. However, it seemed to be taking much longer than usual, so I decided to dig into the issue.

Today, I finally discovered the reason behind the delay, and it seems rather backwards. Based on the screenshots below, the latest update was pushed to the stable channel, while the unstable channel is still lagging behind. This doesn't make much sense unless there's something I'm missing here. I also checked for any new pull requests on Vivaldi, but there doesn't seem to be any open.

Is this an error, or is there an explanation for this?

![Screenshot_20240910_090540](https://github.com/user-attachments/assets/b772f4b4-a807-40df-aeb1-6e63a5378421)
![Screenshot_20240910_090527](https://github.com/user-attachments/assets/8d9384c8-f40e-41b1-8d46-e4103f6d751c)

**Comment by SigmaSquadron** [comment]
Please use the issue template next time.

CC @otwieracz @badmutex

**Comment by eclairevoyant** [comment]
Channel's blocked, just wait. Follow https://nixpkgs-tracker.ocfox.me/?pr=338489 for updates.
