### ISSUE TITLE
Update request: lightningcss 1.26.0 → 1.27.0

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#341154]
- Package name: lightningcss
- Latest released version: 1.27.0

- Current version on the unstable channel: 1.26.0
- Current version on the stable/release channel: 🤷 

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@toastal

-----

Note for maintainers: Please tag this issue in your PR.

Bumping the hash to `sha256-YOTFyIDQIdqnrbXtnnY5U32rk9/fZ+1NcSb3slgkxZU=` from `1.27.0` tag, failed to get to the `cargoHash` phase about vendored dependencies. I don’t really know Rust’s packaging system to understand what these errors mean. Log trying to build: https://paste.sr.ht/~toastal/1248ac6f417bb6181dbb8bc4987a35eca7b6bc24

Again, since the color mixing regression <https://github.com/parcel-bundler/lightningcss/issues/685> persists so I still can’t upgrade past 1.23.x personally so it is hard to be motivated to maintain versions I can’t use.

@JohnRTitor you helped out with the previous patch, perhaps you have some insight?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

[^no-ms-gh]

[^no-ms-gh]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by JohnRTitor** [comment]
I usually run update scripts for packages like these.

```nix
 nix-shell maintainers/scripts/update.nix --argstr package lightningcss
```

`nix-update-script` did its job perfectly, even updated the `cargoHash`.
