### ISSUE TITLE
How to resolve recursive library/test dependencies in Haskell?

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#34110]
Suppose I have two packages: `lib` and `test-util`. The `test-util` library depends on the `lib` library and the tests of `lib` depend on the `test-util` library. I have created [an example of such a project](https://github.com/kirelagin/haskell-cycle-test) and it works just fine with `stack test`.

`stack2nix` (or `cabal2nix`) produces an expression that separates the dependencies into `libraryHaskellDepends` and `testHaskellDepends` but then the builder [concatenates everything together](https://github.com/NixOS/nixpkgs/blob/e4f3fe051e4becd7d42201fa98619c2179908b45/pkgs/development/haskell-modules/generic-builder.nix#L172) and it results in a cycle.

Would it be possible to produce separate derivations for the library and for its tests and then probably combine them into a single derivation to preserve the old behaviour?

**Comment by kirelagin** [comment]
Bump! Any idea on how this can be solved?
(@peti)

**Comment by peti** [comment]
You can pass the `lib` build a version of `test-util` that has its test suite disabled, i.e.

    lib = callPackage ./lib.nix { test-util = dontCheck self.test-util; };
    test-util = callPackage ./test-util.nix { };

This will use an untested version of `test-util` to build a tested `lib`, and then that version will be used to build a tested `test-util`.

**Comment by kirelagin** [comment]
Hm, I’m not sure how this can help, as `test-util` doesn’t have any tests anyway. It consist only of a library and it is its library that depends on `lib`.

**Comment by Ericson2314** [comment]
@peti's trick is indeed the proper short-term solution. But I maintain that in the long term, separate per-component derivations is the way to go.
