### ISSUE TITLE
Update request: freecad 0.21.2 → 1.0RC

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#341214]
- Package name: FreeCAD
- Latest released version: 1.0RC
- Current version on the unstable channel: 0.21.2
- Current version on the stable/release channel: 0.21.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@viric  
@gebner  
@AndersonTorres

### Relevant notes

* https://blog.freecad.org/2024/09/10/the-first-release-candidate-of-freecad-1-0-is-out/
* https://wiki.freecad.org/FreeCAD_1.0_Development_Cycle
* https://github.com/FreeCAD/FreeCAD/tree/releases/FreeCAD-1-0

<details><summary><b>Expand to see list of minimum supported 3rd party library versions</b></summary>

![Screenshot_20240911_120247](https://github.com/user-attachments/assets/9e1a0ee6-6866-4217-b0d7-ce3c24f63e0b)

</details>
It is unorthodox to request an RC (moving target) build but since there is 3rd party dependency complexity the thought of 'this may be a good moment to start porting FC to 1.0' on nix is relevant. The 1.0 release still has some release blockers. Perhaps the nix build will be ready in time for the 1.0 release if efforts start now? 

Related:  
* #284524

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luzpaz** [comment]
CC @pinpox  
Thanks for your effort to package Ondsel, would you be interested in helping to build FreeCAD 1.0RC ?

**Comment by pinpox** [comment]
> CC @pinpox Thanks for your effort to package [Ondsel](https://github.com/NixOS/nixpkgs/issues/284524), would you be interested in helping to build FreeCAD 1.0RC ?

Yes! I'm interested in freecad 1.0 as I plan on using it myself. I didn't follow up on the ondsel package as I never found out how to install the plugins (see comments), but maybe freecad 1.0 is easier do package.

**Comment by srounce** [comment]
Hi, I've had this working for a while, opened #343592 that fixes the build.

**Comment by ein-shved** [comment]
@pinpox I've started to work on packaging of freecad with modules, see #347776
