### ISSUE TITLE
chromium + enableWideVine segfaults

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#34123]
## Issue description

When running a `chromium`, built with `enableWideVine`, it segfaults:

This is a follow-up to https://github.com/NixOS/nixpkgs/issues/22333 and https://github.com/NixOS/nixpkgs/pull/29640

### Steps to reproduce

`$(nix-build --no-out-link -E '(import <nixpkgs {}).chromium.override{enableWideVine=true;}')/bin/chromium --user-data-dir=/tmp/chrwd`

https://gist.github.com/bendlas/894e15a3561837ed55a322ff818b15ea

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.13, NixOS, 18.03pre-git (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): https://github.com/bendlas/nixpkgs/commit/ff09961f9bfe8be47b3d0744a531b54576dc240f
 - nixpkgs: `/etc/nixos/pkgs`

**Comment by bendlas** [comment]
Here is an strace of a run: https://gist.github.com/bendlas/8de183bcaed9f8a1bd2d3633ba785b1a

**Comment by mmahut** [comment]
Any update on this?

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/60833
