### ISSUE TITLE
Package request: alist

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [NixOS/nixpkgs#341249]
**Project description**
A file list/WebDAV program that supports multiple storages, powered by Gin and Solidjs.

**Metadata**

* homepage URL:https://alist.nn.ci/
* source URL:https://github.com/alist-org/alist
* license: [AGPL-3.0 license](https://github.com/alist-org/alist#AGPL-3.0-1-ov-file)
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alist

**Comment by qwqawawow** [comment]
close when https://github.com/NixOS/nixpkgs/pull/309156

**Comment by genga898** [comment]
Refer to https://github.com/NixOS/nixpkgs/pull/355716

**Comment by Moraxyc** [comment]
Actually alist is already available in nixpkgs.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/al/alist/package.nix

It may take some time for the alist module to be added to nixpkgs.
