### ISSUE TITLE
Latest version of jay (wayland compositor) segfaults

### ISSUE THREAD

**Issue by tuxinal** [NixOS/nixpkgs#341373]
### Describe the bug
currently running the latest version of jay on the metal backend produces a segfault

### Steps To Reproduce
1. execute `jay run`

### Expected behavior
The compositor starts up as usual

### Notify maintainers
@dit7ya 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.49, NixOS, 24.05 (Uakari), 24.05.20240907.68e7dce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, nixos-unstable, sops-nix"`
 - nixpkgs: `/nix/store/32y945fdcfh1j5b8zv677vw7np9r7bbw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dit7ya** [comment]
Hi, thanks for reporting. Unfortunately, my current machine is a `darwin` one, so I cannot get to the bug soon. Feel free to open a PR if you happen to find a fix.

**Comment by tuxinal** [comment]
no problem! i'll try to see what i can do

**Comment by tuxinal** [comment]
i'm going to write down some of the stuff i've been able to figure out so far here.
one thing of note is that i _am_ using an nvidia gpu. despite this compiling jay manually (notably, with packages from the nixos-24.05 branch, not nixos-unstable) and running it works just fine. but running the package from nixpkgs (unstable and master) results in a segfault during launch. 
so i tried changing out the dependencies i use in my manual build to ones from nixpkgs unstable and i'm pretty sure this is caused by a bug in newer versions of mesa (at least past 24.0.7)

i don't think this issue has much to do with nix anymore. i'll close this and try filing a bug report to mesa.
