### ISSUE TITLE
Enable oracle server jre and other oracle java binaries for nix

### ISSUE THREAD

**Issue by bledari** [NixOS/nixpkgs#34131]
## Issue description
Cannot install official java.

So, I guess I'm not the only one who wants official java on his machine. Make it possible and easy and production ready, please.

### Steps to reproduce
nix-env -iA nixos.oraclejre  (or oracleserverjre)

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

Gives error I am using virtualbox nix image

**Comment by phdoerfler** [comment]
@bledari Have you tried installing java like I outlined here? https://github.com/NixOS/nixpkgs/issues/34005

**Comment by bledari** [comment]
@phdoerfler yes, I have to dowload manually oracle jre or jdk, no server jre support.

I'm just saying the command I get from nixos package site is not correct, you should update it with a gist/script/whatever workaround. Java is the most important tech so better support it as it should. I understand oracle is in the way but nevertheless it can be done. If you support /provide workaround for server jre that would be good for nix.

**Comment by taku0** [comment]
Try `nix-env -iA nixos.oracleserverjre9`.

**Comment by aanderse** [comment]
@bledari any remaining questions or can thisbe closed?

**Comment by tomodachi94** [comment]
oracleserverjre no longer exists and is EOL, closing.
