### ISSUE TITLE
dockerTools.buildImage sometimes fails to build the image

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#34137]
An Hydra server builds some Docker images by using `dockerTools.buildImage` on 17.09. It sometimes fails to build the image with the following log message:
```
Unpacking base image...
Adding layer...
tar: Removing leading `/' from member names
tar: /nix/store: file changed as we read it
tar: Removing leading `/' from hard link targets
builder for ‘/nix/store/092rh1dq17zck0txi4wq01g9y1v996dgq-docker-image-control.tar.gz.drv’ failed with exit code 1
```
If I manually restart the build, it works...
It seems to me it is failing there https://github.com/NixOS/nixpkgs/blob/release-17.09/pkgs/build-support/docker/default.nix#L492.

I noticed the `layer` attribute is `passthru` in the build derivation. I don't understand why it is done like this, and if it could explain this strange error. This attribute set is set here https://github.com/NixOS/nixpkgs/blob/release-17.09/pkgs/build-support/docker/default.nix#L432.

Why the `layer` attribute is in the `passthru` attribute set?
Any other idea why it sometime fails?

Note I'm not able to reproduce this issue while it often occurs on my Hydra server.

**Comment by lo1tuma** [comment]
I’ve experienced this problem as well. We build quite a lot of docker images using the nixpkgs `dockerTools.buildImage` which is triggered by our Jenkins, but it happens only sometimes, most of the time the builds succeed.

**Comment by lo1tuma** [comment]
Seems like that `layer` was added to `passthru` in #19024, but without explanation. So maybe @adnelson still knows the reason for this change and can help?
