### ISSUE TITLE
db.sqlite atomic protection?

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [NixOS/nixpkgs#341308]
## Issue description
I have a suggestion for NixOS, but ill first explain why this is a problem. 
Recently I came across an issue where, while rebuilding, db.sqlite was interrupted and it didnt get to finish updating, that had to be the case because I came up with several issues, an example being 
```
[spiderunderurbed@daspidercave:/nix/var/nix/db]$ sudo nixos-rebuild switch --impure
error: executing SQLite statement 'pragma synchronous = normal': unable to open database file, unable to open database file (in '/nix/var/nix/db/db.sqlite')
```
and deleting old generations:
```
[spiderunderurbed@daspidercave:/nix/var/nix/db]$ sudo nix-env --delete-generations old
error: executing SQLite statement 'pragma synchronous = normal': unable to open database file, unable to open database file (in '/nix/var/nix/db/db.sqlite')

[spiderunderurbed@daspidercave:/nix/var/nix/db]$
 ```
Same thing happened with garbage collection, shells or anything else communicating with the nix daemon.

I looked for how to solve this issue, found all these resources:
https://discourse.nixos.org/t/nix-store-sqlite-db-corruption/22841 
https://github.com/NixOS/nix/issues/3091

The issue on github lead to the conclusion that reinstalling from scratch was most likely the solution, or fixing the sql file, this would be tedious and in some cases impossible. So, I dont know if nixos can be considered atomic (updates properly or not at all), but i think the SQL file should have protections as this is not the first time it happened and probably wont be the last. So I am suggesting that whatever happens to the sql file be atomic, where there is a staging form of the sql file, and if the configuration is successful it override the stable version of the sql, If the sql file's size is big then some deduplication can be done. 

I am unaware of alot of inner-workings of nixos, so this might be a thing but if it is, I dont think such a safeguard helped.
### Steps to reproduce

Its a rare issue, if the nix-daemon is interrupted while its writting to the sql file you will certainly get the error.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
(I cant run but this issue should be present if you are ever unlucky updating)

**Comment by ghpzin** [comment]
I doubt there is anything on `nixpkgs` side that can help with this.
`nix`, `nix-daemon` and `/nix/var/nix/db/db.sqlite` are handled by https://github.com/NixOS/nix, same as the issue you linked.

**Comment by SpiderUnderUrBed** [comment]
Filed this issue in the correct repo:
https://github.com/NixOS/nix/issues/11500
