### ISSUE TITLE
doc: NixOS manual does not mention that secure boot must be disabled for ISOs to boot

### ISSUE THREAD

**Issue by Tritlo** [NixOS/nixpkgs#341310]
### Describe the bug
When trying to boot the NixOS ISOs, it fails to boot (Framework 13 AMD 7640)

### Steps To Reproduce

1. Download NixOS ISO image (Graphical GNOME Intel/AMD or Minimal)
2. Copy to USB drive with Balena Etcher
3. Insert into Laptop USB port and try to boot

### Expected behavior

I expect the OS to boot from the drive

### Additional context

The laptop is completely fresh, the SSD empty.
I later tried with the Ubuntu 24.04.01 ISO, same process with BalenaEtcher, worked fine.

Additionally: it seems that the partition table is wonky. I had to use DiskGenius to be able to use the drive again. Happened both on a 128 Gb USB A drive and a 256 Gb USB C drive (both Kingston)

### Metadata

N/A

**Comment by NyCodeGHG** [comment]
Secure Boot is enabled by default on Framework Laptops, did you disable Secure Boot?
Ubuntu is signed and can be booted with active secure boot, NixOS is not.

**Comment by Tritlo** [comment]
That's probably it! There's no mention of this in the manual though.

**Comment by Atemu** [comment]
That's the actual issue here.
