### ISSUE TITLE
frigate: enabling frigate module causes *excessive* eval RAM usage (and OOMs)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#341424]
### Steps To Reproduce

I apply this diff to one of my NixOS hosts (an `aarch64-multiplatform` being cross-compiled on `x86_64-linux`), then try to eval it:

```nix
{
  config = {
    # ...
    services.frigate.enable = true;
    services.frigate.hostname = "frigate.mickens.us";
    # ...
  };
}
```

But it eats up ~18GB+ of RAM (hard to say with zram, etc), and eventually OOMs.

This is on top of: `1355a0cb` (current nixos-unstable)

Not sure if there's some other `nginx` setup that's needed, but if so, there should probably be some asserts or something. Anyway, this is quite odd. Can't say I've ever seen anything quite like this.

cc: @mweinelt 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Likely a duplicate of https://github.com/NixOS/nixpkgs/issues/338231

**Comment by colemickens** [comment]
Wow thanks @mweinelt ! Closing and tracking that.
