### ISSUE TITLE
Upgrading pytest has broken multiple packages

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#34143]
## Issue description

On unstable, I'm not able to build the following Python packages: `pytest-cram`, `nbstripout` and `pytest-flake8`. I suppose this is related to an upgrade of pytest.

### Steps to reproduce

For instance,

```
nix-shell -p pythonPackages.pytest-cram
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.76, NixOS, 18.03.git.3a763b9 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by FRidh** [comment]
`pytest` move quite fast but plugins often not. This is something that simply happens on `unstable`. The last month or so before 18.03 I intend to "freeze" it.

**Comment by jluttine** [comment]
I think at least `pytest-flake8` is still broken. I reported it upstream and have been waiting for an answer: https://github.com/tholo/pytest-flake8/issues/44. Just thought I'd share this information in case someone else is wondering it.
