### ISSUE TITLE
All Unigine benchmarking tools fail to build

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#341436]
**All Unigine benchmarking tools fail to build:**
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/graphics/unigine-valley/
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/graphics/unigine-heaven/
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/graphics/unigine-tropics/
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/graphics/unigine-sanctuary/
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/graphics/unigine-superposition/

Errors:
```
error: cannot download Unigine_Superposition-1.1.run from any mirror
error: builder for '/nix/store/vdmvwcl8z74gf9qgdi599xrdzs6rc9zk-Unigine_Superposition-1.1.run.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/mis2j7phb6sllf1rhh1zgcgb19rx3x9k-unigine-superposition-1.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xv858szxiiz8c9pm3lz47afy7zam2nbk-Superposition.drv' failed to build
```

```
trying https://assets.unigine.com/d/Unigine_Heaven-4.0.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (35) Recv failure: Connection reset by peer
error: cannot download Unigine_Heaven-4.0.run from any mirror
error: builder for '/nix/store/dw78jxssijyj7b8wvf2m8n3bzwk5s9hz-Unigine_Heaven-4.0.run.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/xy4l5iwwwqkpxsvk981n4sw20nbdz1fd-unigine-heaven-4.0.drv' failed to build
```

![Bildschirmfoto vom 2024-09-12 21-56-03](https://github.com/user-attachments/assets/2c9af860-0b83-46a6-b927-ca578b82f204)

**Comment by Atemu** [comment]
The links are working for me.

I suspect they simply had a little outage on the download site when you were attempting to download.

cc @barinov274
