### ISSUE TITLE
Hyprscroller not detected by Hyprland

### ISSUE THREAD

**Issue by quantum9Innovation** [NixOS/nixpkgs#341476]
### Describe the bug
When using the Hyprscroller package provided by nixpkgs-unstable, recent changes have resulted in the package not being detected by Hyprland.

### Steps To Reproduce
1. Pass Hyprscroller package (from nixpkgs-unstable) as Hyprland plugin in NixOS configuration
2. Hyprland will report error "hyprscroller plugin not found"

### Expected behavior
Hyprscroller should be detected and work with the latest version of Hyprland, as it did before recent updates.

### Additional context
Hyprscroller was previously working with Hyprland v0.43 on my system, so I'm guessing this issue was caused by a recent update of the Hyprscroller package (specifically https://github.com/NixOS/nixpkgs/pull/340620). Not sure exactly why this caused an issue.

### Notify maintainers

@donovanglover

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240906.574d1ea`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/5w3dp0m37794iffsbm9vd9f1xmmhda6i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by quantum9Innovation** [comment]
The exact error text produced by Hyprland is "Failed to load the following plugins: `/nix/store/sxc0hgg7nvjby0xp8anpipr50iqigdyp-hyprscroller-0-unstable-2024-09-06/lib/libhyprscroller.so`"

**Comment by quantum9Innovation** [comment]
I just rebooted and it seems Hyprscroller is working perfectly. I think this is most likely an error related to how Home Manager restarts active services/modules after a rebuild.

**Comment by donovanglover** [comment]
I usually use `nixos-rebuild boot` instead of `switch` to avoid issues like this after running `nix flake update nixpkgs`
