### ISSUE TITLE
Documentation: podman 容器开机自启动 Podman container booting and self-booting

### ISSUE THREAD

**Issue by eqfae** [NixOS/nixpkgs#341589]
## Problem

重启后容器需要手动切换到root启动
Containers need to be manually switched to root boot after reboot
```
podman-compose up -d
```
通过systemd自启Self-boot via systemd
```
podman generate systemd --name your-container-name --files --new

sudo mv container-your-container-name.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable container-your-container-name.service
sudo systemctl start container-your-container-name.service
```
但我想手动修改系统相关会被rebuild覆盖  怎么用nix flake配置呢
But I want to manually change the system-related changes that will be overwritten by rebuild How do I configure it with nix flake?
## Checklist

- [ ] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [ ] checked [open documentation issues] for possible duplicates
- [ ] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qwqawawow** [comment]
For information
https://discourse.nixos.org/t/running-a-docker-compose-file-automatically/24663/2
``` nix
systemd.services.my-docker-compose = {
    script = ''
      docker-compose -f ${./path-to/docker-compose.yml}
    '';
    wantedBy = ["multi-user.target"];
    # If you use podman
    after = ["podman.service" "podman.socket"];
    # If you use docker
    # after = ["docker.service" "docker.socket"];
};
```
https://github.com/aksiksi/compose2nix
Looking for other solutions

**Comment by eqfae** [comment]
nice
