### ISSUE TITLE
`sudo systemctl soft-reboot` doesnt work

### ISSUE THREAD

**Issue by Alper-Celik** [NixOS/nixpkgs#341564]
### Describe the bug
`sudo systemctl soft-reboot` doesnt work, it gives 
``` Call to Reboot failed: Access denied ```

### Steps To Reproduce
1. run `sudo systemctl soft-reboot`

### Expected behavior
it should perform a soft reboot

### Additional context
#268521 

### Notify maintainers
@NixOS/systemd 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.50, NixOS, 24.11 (Vicuna), 24.11.20240910.1355a0c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos"`
 - channels(alper): `""`
 - nixpkgs: `/nix/store/qpg5mwsind2hy35b9vpk6mx4jimnypw0-source`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arianvp** [comment]
https://github.com/NixOS/nixpkgs/pull/309911

**Comment by Alper-Celik** [comment]
oh, sorry i didnt noticed pr

**Comment by MithicSpirit** [comment]
Works for me. I belive fixed with #514100.

**Comment by NyCodeGHG** [comment]
I'm not sure if this issue should be closed, considering soft-reboot can't boot into a new generation.

**Comment by Alper-Celik** [comment]
> I'm not sure if this issue should be closed, considering soft-reboot can't boot into a new generation.

well i guess it is a good point, i am reopening it at least for now. tho maybe it should be on its own issue ?

**Comment by MithicSpirit** [comment]
> I'm not sure if this issue should be closed, considering soft-reboot can't boot into a new generation.

This issue description does not mention anything about how it should behave with new generations. IMO that should be a separate issue.

**Comment by NyCodeGHG** [comment]
I would expect something which says "reboot" to be able to boot into a new generation after doing `nixos-rebuild boot`

**Comment by Alper-Celik** [comment]
as i understnd currently only nixos-rebuild switch changes the soft-reboot s target generation https://github.com/NixOS/nixpkgs/pull/514100#issuecomment-4446497537 , so we need nixos-rebuild boot to change the target genaration of the soft-reboot make it work as expected. 

tho it is still better than not having it, switch might not be able to upgrade everything like the dbus-broker switch and doing switch + soft-reboot can be used to upgrade user space fully

**Comment by MithicSpirit** [comment]
I rely on soft-reboot *not* requiring me to use `nixos-rebuild boot`. I use it to test out new generations without committing them to my boot entries. It would be fine for me if soft-reboot used the generation from either `nixos-rebuild test` or `nixos-rebuild boot`, based on which was most recently used (this boot).

Ideally there would be a way to have the new generation not applied immediately (`nixos-rebuild test`) nor added to the bootloader (`nixos-rebuild boot`), but rather only applied at the next soft-reboot. Maybe something like a `--soft-reboot` flag could be added for both `test` and `switch` to enable this behavior.

**Comment by arianvp** [comment]
> I rely on soft-reboot not requiring me to use nixos-rebuild boot. I use it to test out new generations without committing them to my boot entries. It would be fine for me if soft-reboot used the generation from either nixos-rebuild test or nixos-rebuild boot, based on which was most recently used (this boot).

I am not following at all. How are you using soft-reboot to test out new generations?   There is no behavior implemented today to allow that

**Comment by MithicSpirit** [comment]
> I am not following at all. How are you using soft-reboot to test out new generations?   There is no behavior implemented today to allow that

`sudo nixos-rebuild test && sudo systemctl soft-reboot` seems to be working fine for me.

**Comment by arianvp** [comment]
ah so you activate the new generation before soft-rebooting instead of after soft-rebooting. Gotcha

**Comment by MithicSpirit** [comment]
Correct. Ideally this wouldn't be the case: I wished it activated it during the soft-reboot, rather than right before (and without changing bootloader entries).
