### ISSUE TITLE
Importing multiple versions of python using new syntax

### ISSUE THREAD

**Issue by bryaan** [NixOS/nixpkgs#34165]
I would like to install some python 3.5 and 2.7 libs alongside each other, but this file is invalid.  What is the right way to do it?

```nix
with import <nixpkgs> {};

python35.withPackages (ps: with ps; [ numpy toolz ])
python27.withPackages (ps: with ps; [ setuptools ])
```

**Comment by FRidh** [comment]
How do you want to install this? NixOS `configuration.nix` or `nix-env -i`? Or do you want this working with `nix-shell` or `nix run`?

In case of `configuration.nix` you can simply add each line to `environment.systemPackages`. With `nix-env` you could install each line separate. If, however, you would want to `nix-env -i` a file like this, you could put the derivations in a list:
```nix
with import <nixpkgs> {};

[
    (python36.withPackages (ps: with ps; [ numpy toolz ]))
    (python27.withPackages (ps: with ps; [ setuptools ]))
]
```
Often people put them together in a dedicated derivation (using `stdenv.mkDerivation`), although when taking this direction `buildEnv` is preferred:
```nix
with import <nixpkgs> {};

buildEnv {
    name = "pythons";
    paths = [
        (python36.withPackages (ps: with ps; [ numpy toolz ]))
        (python27.withPackages (ps: with ps; [ setuptools ]))
   ];
}
```

**Comment by FRidh** [comment]
Question is I think answered and no response so I'm closing this.

**Comment by bryaan** [comment]
Sorry for late reply, yes that looks like a working plan. Thanks
