### ISSUE TITLE
Gotenberg Core dumped on service start

### ISSUE THREAD

**Issue by rathmerdominik** [NixOS/nixpkgs#341605]
### Describe the bug
Gotenberg crashes immediately on startup

### Steps To Reproduce
Enter the following into your nix config:

```
services.gotenberg = {
    enable = true;
}
```

### Expected behavior
It not crashing but starting up normally

### Screenshots
![image](https://github.com/user-attachments/assets/d2f8aee3-50c7-422b-9a35-ac777a172eb2)

### Additional context
Gotenberg was to be used in conjunction with paperless-ngx.
[Here](https://github.com/rathmerdominik/nixie/blob/main/servers/xenon/paperless-ngx.nix) is the entire file

### Notify maintainers
@pyrox0 @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[dominik@xenon:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.50, NixOS, 24.11 (Vicuna), 24.11.20240910.1355a0c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qpg5mwsind2hy35b9vpk6mx4jimnypw0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
Are there any more logs from the Gotenberg service? Or is the coredump all that's available?

**Comment by rathmerdominik** [comment]
> Are there any more logs from the Gotenberg service? Or is the coredump all that's available?

Sadly that is all.
The service log literally doesn't say *anything*.
There you only see that the service started and immediately exited.

This log i got by typing ```sudo journalctl -xef```

**Comment by pyrox0** [comment]
Sorry for the slow response, but I looked at this and figured out the issue. Could you test this and see if it fixes your problem?
