### ISSUE TITLE
Change "Cypress" binary to lowercase "cypress"

### ISSUE THREAD

**Issue by EricWardner** [NixOS/nixpkgs#341662]
### Steps To Reproduce
1. Install cypress package
2. Try to run cypress
3. Realize the package was installed as "Cypress"

### Expected behavior
`cypress` should work lower case, in line with how it is installed in other common operating systems

### Notify maintainers
@lukas-mertens 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment]
Upstream does refer to the executable using the lowercase, so we should probably change this: https://docs.cypress.io/guides/getting-started/opening-the-app#Adding-npm-Scripts

**Comment by EricWardner** [comment]
https://github.com/NixOS/nixpkgs/pull/341694
