### ISSUE TITLE
Prometheus 2.x support for 18.03

### ISSUE THREAD

**Issue by bachp** [NixOS/nixpkgs#34166]
## Issue description

Prometheus 2 contains several [breaking changes](https://prometheus.io/docs/prometheus/2.1/migration/).

Most relevant to NixOS are:
1. Command line parameters changed
2. New storage engine

---

1. can be dealt with in the module and should not affect the user.

2. however makes the data incompatible and there seems to be no possibility of migrating the data.

The question is now how can we handle this for 18.03.

1. Just replace Prometheus 1.8 with Prometheus 2.1 and set the storage location to one different from the 1.x version. 1.x => `/var/lib/prometheus/metrics` 2.x => `/var/lib/prometheus/data`.
2. Make both Prometheus version available and allow the user to select which one to use. Again with the storage folders different as above.
3. Same as 2. but make the choice depend on `system.stateVersion`

/cc @benley @fpletz

**Comment by benley** [comment]
Ouch, the lack of a data migration path from v1 to v2 stinks.  Maybe we could introduce a separate `prometheus_2` service and keep both available in tandem for a release cycle, with deprecation warnings?  Or rename the current prometheus to `prometheusLegacy` (or something), introduce v2 as the new `prometheus` service, and use the `stateVersion` option to require user intervention before continuing - either by switching to prometheusLegacy and keeping their data, or by bumping stateVersion to 18.03 and dropping their old prometheus 1.8 data.  If we put the v2 data in a different directory it would be up to the user to delete the old data once they're ready, as you suggested.

**Comment by bachp** [comment]
Another possibility would be to implement the possibility to run both in parallel like suggested [here](https://prometheus.io/docs/prometheus/2.1/migration/#storage). But I'm not sure if this is worth the effort and doesn't cause more confusion than it helps.

**Comment by bachp** [comment]
This is addressed by https://github.com/NixOS/nixpkgs/commit/78f50651f99ebdc566b843cfcde3408db023467d

**Comment by uvNikita** [comment]
@bachp Thanks for fixing it. I probably missing something, but how to specify that I want to use Prometheus 2.0 in `services.prometheus`? I was trying to override `pkgs.prometheus`, but it doesn't look like `pkgs.prometheus_2` exists in nixpkgs at the moment. I'm using 18.03.

**Comment by mmlb** [comment]
@bachp I too would like to run prometheus as a service. That commit doesn't seem to change that `services.prometheus` refers to `prometheus_1` right? I think the issue should be re-opened.

**Comment by bachp** [comment]
I think it is already being adressed by https://github.com/NixOS/nixpkgs/pull/49802

**Comment by mmlb** [comment]
thanks!
