### ISSUE TITLE
Nix does not use binary cache for LibreOffice

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#34164]
## Issue description
NixOS builds LibreOffice from source even though it exists in the binary cache. Even though the jobs for libreoffice are succeeding [on hydra](https://hydra.nixos.org/job/nixos/release-17.09/nixpkgs.libreoffice.x86_64-linux) for a few days, my system keeps building libreoffice when I start a nix-shell with it or add it to my sys configuration.
Since I haven't heard from anyone else about this, I think I might be the only one having this issue. In this case I'd like to kindly ask for help, since I updated nix-channel multiple times, this does not happen with any other package I tested and I don't know what causes this.

### Steps to reproduce
nix-shell -p libreoffice

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 17.09.2826.5141f28405e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2826.5141f28405e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vcunat** [comment]
`libreoffice` on your claimed revision (5141f28) did **failed** on Hydra: https://hydra.nixos.org/eval/1427782?filter=libreoffice&compare=1427693&full=#tabs-aborted

You are not the only one with that issue: https://groups.google.com/forum/#!topic/nix-devel/yvuWUlhlqSM

You may want e.g. `nix-channel --rollback`, temporarily.

**Comment by va1entin** [comment]
Thanks for the clarification! Learning something new about Nix* everyday 👍

**Comment by vcunat** [comment]
Now 17.09 updated, after a small nudge.
