### ISSUE TITLE
Build failure: mininet

### ISSUE THREAD

**Issue by Elfahor** [NixOS/nixpkgs#341875]
### Steps To Reproduce

1. build nixpkgs#mininet

### Build log

```
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: SHELL=/nix/store/izpf49b74i15pcr9708s3xdwyqs4jxwl-bash-5.2p32/bin/bash PREFIX=\$\(out\) mnexec
gcc -Wall -Wextra  \
-DVERSION=\"`PYTHONPATH=. python -B bin/mn --version 2>&1`\" mnexec.c -o mnexec
<command-line>: warning: missing terminating " character
mnexec.c: In function 'main':
<command-line>: error: missing terminating " character
mnexec.c:208:28: note: in expansion of macro 'VERSION'
  208 |             printf("%s\n", VERSION);
      |                            ^~~~~~~
mnexec.c:208:35: error: expected expression before ')' token
  208 |             printf("%s\n", VERSION);
      |                                   ^
make: *** [Makefile:50: mnexec] Error 1
```

### Additional context

The same build error unsurprisingly appears both when trying to build the package with `nix build` and when trying to enable the NixOS module. 

### Notify maintainers

@teto 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11.20240911.4f807e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/2pw5bsq1r80lcvvh2wp89m142nln1zpl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
I dont use this software anymore sry. I can merge a patch though

**Comment by elisesouche** [comment]
@teto #346470 fixes this

**Comment by teto** [comment]
merged ty
