### ISSUE TITLE
chrome-gnome-shell doesn't work

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#34184]
## Issue description

Gnome-Shell integration with `chrome-gnome-shell` doesn't work.

### Steps to reproduce

Open Firefox or Chromium, browse to http://extensions.gnome.org. Page says extension is installed but native host connector isn't running, even when `chrome-gnome-shell` is installed with `nix-env`.

### Things tried

See comments at the end of #26981

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.77, NixOS, 17.09.2826.5141f28405e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(user): `""`
 - channels(root): `"nixos-17.09.2826.5141f28405e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
Please read the description of the package:

https://github.com/NixOS/nixpkgs/blob/d9aebebaf5b9b87ff67432d29ac5f283dc9948d0/pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix#L30

**Comment by neilmayhew** [comment]
Thanks for the info. That's very helpful.

I hadn't seen the instructions in the description because I'm on `17.09` and these extra configuration options are only in in `staging` and `master`. Am I out of luck for getting `chrome-gnome-shell` working on `17.09`?

I assume I could install a version of `firefox` from `master`, but I don't think I'd be able to have `chrome-gnome-shell` run as a service without running NixOS itself from `master`.

**Comment by jtojnar** [comment]
You can definitely run services from different paths. For example, if you register `unstable` channel to your path, you can use the following configuration.nix.

```nix
  imports = [
    …
    <unstable/nixos/modules/services/desktops/gnome3/chrome-gnome-shell.nix>
  ];

  # Disable the module from the main channel
  disabledModules = [ "desktops/gnome3/chrome-gnome-shell.nix" ];

  services.gnome3.chrome-gnome-shell.enable = true;

  nixpkgs.config.firefox.enableGnomeExtensions = true;

  nixpkgs.config.packageOverrides = super: {
    firefox = unstable.firefox;
    # Not sure if this is necessary, or the module picks up the package from the channel
    chrome-gnome-shell = unstable.chrome-gnome-shell;
  };
```

**Comment by eqyiel** [comment]
@neilmayhew maybe have a look at the diff here: https://github.com/NixOS/nixpkgs/pull/31743

It's the commit that adds support for Browserpass (another native messaging extension) to Firefox.  According to this, you can override the Firefox wrapper with `extraNativeMessagingHosts`.

**Comment by jtojnar** [comment]
@eqyiel that one is also only on unstable.

**Comment by eqyiel** [comment]
@jtojnar my bad!

**Comment by neilmayhew** [comment]
@jtojnar Unfortunately, that isn't working for me.

I added `<unstable>` by running `sudo nix-channel --add https://nixos.org/channels/nixos-unstable unstable` and ran `sudo nix-channel --update`.

I then put your code snippet into `/etc/nixos/configuration.nix` (merging the `imports` with the existing one that contains just `./hardware-configuration.nix`) and ran `nixos-rebuild build`.

It says, _undefined variable ‘unstable’_ for the two places it's used in `/etc/nixos/configuration.nix`.

I'm also thinking that this part must be wrong:

```nix
{
  imports = [
    <unstable/nixos/modules/services/desktops/gnome3/chrome-gnome-shell.nix>
  ];
}
```

because that would merge `chrome-gnome-shell.nix` (a package) with `./hardware-configuration.nix` (a NixOS configuration).

I've fiddled around with this a bit but haven't been able to make it work yet. If you have any further pointers, I'd appreciate it.

Currently, I have:

```nix
{ config, pkgs, options, ... }:

let
  unstable = import <unstable>;
in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Disable the module from the default channel
  disabledModules = [ "desktops/gnome3/chrome-gnome-shell.nix" ];

  services.gnome3.chrome-gnome-shell.enable = true;

  nixpkgs.config.firefox.enableGnomeExtensions = true;

  nixpkgs.config.packageOverrides = super: {
    firefox = unstable.firefox;

    # Not sure if this is necessary, or the module picks up the package from the channel
    chrome-gnome-shell = unstable.chrome-gnome-shell;
  };

  # ...
}
```

It fails with:

```
$ nixos-rebuild build
building Nix...
building the system configuration...
error: The option `services.gnome3.chrome-gnome-shell' defined in `/etc/nixos/configuration.nix' does not exist.
```

**Comment by neilmayhew** [comment]
I got it to build a profile, with the following configuration:

```nix
{ config, pkgs, options, ... }:

let
  unstable = import <unstable> {};
in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      <unstable/nixos/modules/services/desktops/gnome3/chrome-gnome-shell.nix>
    ];

  # Disable the module from the default channel
  disabledModules = [ "desktops/gnome3/chrome-gnome-shell.nix" ];

  services.gnome3.chrome-gnome-shell.enable = true;

  nixpkgs.config.firefox.enableGnomeExtensions = true;

  nixpkgs.config.packageOverrides = super: {
    firefox = unstable.firefox;

    # Not sure if this is necessary, or the module picks up the package from the channel
    chrome-gnome-shell = unstable.chrome-gnome-shell;
  };

  # ...
}
```

but the web page still says, "native host connector is not detected". Building the profile brought in a lot of gnome and GTK stuff, so it does seem to be using things from unstable. I started firefox from the command line, using an empty profile with just the GNOME Shell integration extension installed.

Thanks for your help with this, but I'm going to put it on hold for now. Hopefully it'll work for me in 18.03.

**Comment by svsdep** [comment]
Works just fine with the latest unstable and a following config:
```nix
environment.systemPackages = with pkgs; [
  firefox
];

nixpkgs.config.firefox.enableGnomeExtensions = true;
```
