### ISSUE TITLE
Package dbeaver using source build

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#34182]
This issue is a followup from the [last comment of PR 34129](https://github.com/NixOS/nixpkgs/pull/34129#issuecomment-359419653)

> @samueldr While I think that this version bump PR is fine (thanks!) we should ideally build everything we can from source.
> I would really appreciate if we could change this derivation to use the source rather than pre-built binaries.

* * *

`dbeaver` is built exactly like eclipse is built. Its upstream build is using maven tooling, which few packages seem to do properly, and the attempt I made initially doesn't seem to want to build properly (with my experience with nix). There is one dependency in the maven dependency which seems troublesome to package (with the complete unfamiliarity I have with maven).

 * https://github.com/NixOS/nixpkgs/blob/d30f5f8a2e3511d8b88f2c03334fff13b9c2ff44/pkgs/applications/editors/eclipse/build-eclipse.nix

I would happily want to help and get help with getting a complete from-source build of dbeaver, but it *definitely* is out of my current skill set.

Here's my initial attempt I tried before looking at the eclipse package and seeing it trusted upstream binary builds:

 * https://gitlab.com/samueldr/nixos-configuration/blob/4f0ddd6b25082ebb69a80c0f42af2bba687b56e0/overlays/samueldr/pkgs/applications/misc/dbeaver/__source-based.nix

The tycho bundle external bit makes using the existing maven patterns harder; I don't know maven, and it seems that adding it using `mvn install:install-file` isn't enough for it to work the way this maven use is done.

* * *

Ideally, some kind of framework for software built the same way eclipse is may be needed for this to be built with the sources, and this would probably allow building eclipse from sources too. This may even apply for other software, I don't know if there's anything else packaged (or not packaged) that is using the eclipse frameworks for its UI.

**Comment by Mic92** [comment]
This might work: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/exhibitor/default.nix#L14
