### ISSUE TITLE
Update request: tailscale 1.72.1 → 1.74.0

### ISSUE THREAD

**Issue by LeaderbotX400** [NixOS/nixpkgs#341868]
- Package name: Tailscale
- Latest released version: 1.74.0

- Current version on the unstable channel: 1.72.1
- Current version on the stable/release channel: 1.66.4

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by LeaderbotX400** [comment]
Closed by #341474

**Comment by mfrw** [comment]
Closed via:
- https://github.com/NixOS/nixpkgs/pull/341474
