### ISSUE TITLE
Update request: Joplin-Desktop 2.14.17 → 3.0.14

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#341977]
- Package name: Joplin
- Latest released version: 3.0.14

- Current version on the unstable channel: 3.0.15
- Current version on the stable/release channel: 2.14.17

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@HugoReeves 
@qjoly 

-----

Note for maintainers: Please tag this issue in your PR.

I cannot synchronize with the joplin server I self-host as you can see in the screenshot. It says I must have version 3.0 minimum.

![Screenshot_20240914_214559](https://github.com/user-attachments/assets/cbef72d4-083d-4307-8573-f52cd774e92c)

**Comment by FliegendeWurst** [comment]
I think the update to Joplin 3.x will not be backported (it is a breaking change). In the meantime you can switch to the unstable channel or wait for NixOS 24.11.

**Comment by FliegendeWurst** [comment]
> > I think the update to Joplin 3.x will not be backported (it is a breaking change). In the meantime you can switch to the unstable channel or wait for NixOS 24.11.
> 
> Do you mind elaborating on why it's a breaking change?

It looks like Version 3.x will only synchronize with 3.x servers. Therefore it will break anyone running a 2.x server.
