### ISSUE TITLE
Slow nixos-rebuild (1h+) for XMonad

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#34208]
## Issue description
I've installed Nixos about 6 months ago or so, a week ago I tried running `nixos-rebuild --upgrade switch`  and I swear it got to nearly an hour and was still not done.

I've run it again today, about 30 minutes have passed (and still going...) the output can be viewed here: https://github.com/chrissound/nixconfig/blob/master/stderrnix.txt

How can I diagnose why this is taking so long? 

My nix configuration files can also be found in that repo. In addition I also have installed many programs via `nix-env -i example` - if this potentially has any impact?

```
nix-shell -p nix-info --run "nix-info -m" --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘shell’ at /nix/store/fpvbcxgqirhzb131gkqy7y0ay29dbpqz-nixos-17.03.1947.d77e0969a78/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating ‘optionals’ at /nix/store/fpvbcxgqirhzb131gkqy7y0ay29dbpqz-nixos-17.03.1947.d77e0969a78/nixos/lib/lists.nix:185:21, called from /nix/store/fpvbcxgqirhzb131gkqy7y0ay29dbpqz-nixos-17.03.1947.d77e0969a78/nixos/pkgs/stdenv/generic/default.nix:271:16:
while evaluating ‘chooseDevOutputs’ at /nix/store/fpvbcxgqirhzb131gkqy7y0ay29dbpqz-nixos-17.03.1947.d77e0969a78/nixos/lib/attrsets.nix:463:22, called from /nix/store/fpvbcxgqirhzb131gkqy7y0ay29dbpqz-nixos-17.03.1947.d77e0969a78/nixos/pkgs/stdenv/generic/default.nix:228:22:
undefined variable ‘nix-info’ at (string):1:66
```

**Comment by erictapen** [comment]
Hello Chris,

for some reason you are building GHC. That package needs some time, even
on the build farm. On the NixOS hydra, it took 2 hours recently.

https://hydra.nixos.org/build/67751340

You could let that run through, it will eventually result in a working
system (unless your RAM is too small to build it).

Question is now, why do you need to build GHC? Do you overwrite it in
your config?

Best,
Justin

Quoting Chris Stryczynski (2018-01-24 00:05:38)

**Comment by rnhmjoj** [comment]
It's building GHC from source and all that depends on it however I don't see any override or anything else in your configuration that should require it.
I don't know, If I were you I would try switching to 17.09 and see if it still happens.

**Comment by chrissound** [comment]
I'm not sure if it's something I need. I'm a bit surprised it's building ghc though - I can't see it mentioned anywhere in my configs?

Potentially due to the use of XMonad?

**Comment by rnhmjoj** [comment]
It's definitely that.

**Comment by rnhmjoj** [comment]
Doesn't XMonad use GHC to compile its configuration? You probably need it, the question is why Nix is not taking it from the binary cache.
Try also checking the store for [corruption](https://nixos.org/nixos/manual/index.html#sec-nix-store-corruption).

**Comment by chrissound** [comment]
I've copied my config to a VM, booted with the Nixos minimal image, and the install was significantly quicker. 

Running `nixos-rebuild --upgrade switch` now returns instantly (probably because it installed the latest packages from the install script?).

Anyway, super grateful this is fixed :).
