### ISSUE TITLE
wpa_supplicant secretsFile changes wrt special characters

### ISSUE THREAD

**Issue by ahuston-0** [NixOS/nixpkgs#342140]
### Describe the bug

I swapped over to the new secretsFile spec for wifi secrets (as per @rnhmjoj). I've put the diff for the config below. `net1` has special characters in the password and connected before I did the swap, `net2` does not have special characters in the password and is still working.

```nix
diff --git a/systems/artemision/wifi.nix b/systems/artemision/wifi.nix
index d431ffa..f02107c 100644
--- a/systems/artemision/wifi.nix
+++ b/systems/artemision/wifi.nix
@@ -6,23 +6,23 @@ in
 {
   networking.wireless = {
     enable = true;
-    environmentFile = config.sops.secrets."wifi-env".path;
+    secretsFile = config.sops.secrets."wifi-env".path;
     userControlled.enable = true;
     networks = {
       "net1" = {
-        psk = "@PASS_net1@";
-        priority = 90;
+        pskRaw = "ext:PASS_net1";
+        priority = 100;
       };
       "net2" = {
-        psk = "@PASS_net2@";
-        priority = 100;
+        pskRaw = "ext:PASS_net2";
+        priority = 90;
       };
...
```

### Steps To Reproduce
1. swap from `networking.wireless.environmentFile` to `networking.wireless.secretsFile`
2. change the external password references from `psk` to `pskRaw`
3. restart wpa_supplicant
4. `net2` connects but `net1` doesnt

### Expected behavior

I should be able to swap to the new config option and my passwords should still work as expected.

### Notify maintainers

Already tagged earlier in the issue

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
/nix/store/91d27rjqlhkzx7mhzxrir1jcr40nyc7p-stdenv-linux/setup: line 226: sopsImportKeysHook: command not found
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7-zen1, NixOS, 24.11 (Vicuna), 24.11.20240913.345c263`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.6`
 - nixpkgs: `/nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rnhmjoj** [comment]
Uhm, If your password has special characters, did you unescape them? 

Previously we used `environmentFile` for secrets, which is bound by the rules of `EnvironmentFile` setting of systemd, so some characters had to be escaped (see `EnvironmentFile=` from the `systemd.exec(5)` man page). `secretsFile` instead interprets any character literally.

**Comment by Patricol** [comment]
This also broke for me.

Password starts with `$`, includes the symbols `!#$%&`, works if given directly as `networking.wireless.networks.SSID.psk` and is not escaped in the ext_password_backend file. (`networking.wireless.secretsFile`) Other networks without special characters in their passwords work correctly.

The error is `WPA: 4-Way Handshake failed - pre-shared key may be incorrect`; and debug logs suggest that `ext:` is working; WPA does grab the psk from the `ext_password_backend` file.

The format of the content of `networking.wireless.secretsFile` is:
```
psk_ssid=PASSWORD
```
The password is also 63 characters long, which causes a length-related error when I also tried `psk_ssid="PASSWORD"` as a sanity check. (`EXT PW: Unexpected PSK length 65 in external storage`)

Using `\` to escape the `$`s in the password was also not a fix; but did not trigger a length error, which means the `\` are being handled as special characters; which makes me think that other symbols are too.

`psk_ssid='PASSWORD'` also does not trigger a length error. This is definitely not actually taking the raw contents between `=` and `\n`; it's being processed somewhere.

**Comment by Patricol** [comment]
Using `\` to escape every symbol (`!#$%&`) also gives `WPA: 4-Way Handshake failed - pre-shared key may be incorrect` and not `EXT PW: Unexpected PSK length * in external storage`.

Using `\` to escape every single character gives `EXT PW: Unexpected PSK length [NUMBER] in external storage`; where NUMBER is hilariously way more than 64 and way less than 126. After some more experimentation, escaping `#` as `\#` comments out the rest of the password, but includes the `\` right before the `#` based on length. Can't make this shit up.

**Comment by rnhmjoj** [comment]
> Using \ to escape the $s in the password was also not a fix; but did not trigger a length error, which means the \ are being handled as special characters; which makes me think that other symbols are too.

I'm pretty sure there are no characters being interpreted specially: if you look at the [implementation](https://w1.fi/cgit/hostap/tree/src/utils/ext_password_file.c#n100) it's literally splitting the line at `=` symbol and taking the second part, that's it. Unless, it's done somewhere else, but then I guess it should do the same when putting it directly the configuration.

**Comment by Patricol** [comment]
Did you see my next comment? the `\#` handling is pretty damning; even if it is on the wpa_supplicant side.

**Comment by Patricol** [comment]
This seems to be a `wpa_supplicant` bug rather than a NixOS bug, but NixOS should imo at least allow using the old secure method until this is fixed.

**Comment by rnhmjoj** [comment]
Oh god, you're right: `wpa_config_get_line` does all sort of stuff:
```
  /* Skip white space from the beginning of line. */
  /* Skip comment lines and empty lines */
  /* Remove # comments unless they are within a double quoted string. */
  /* Remove trailing white space. */
```

**Comment by rnhmjoj** [comment]
It seems it's interpreting your passphrase as a raw PSK. Try to double quote it.

**Comment by ahuston-0** [comment]
I need to test (super busy work week so it might take me a minute) but I'm reasonably sure I already tried that and it also failed

**Comment by Patricol** [comment]
Narrowing it down more:

`#` is active (meaning it comments out the rest of the psk), whether escaped with `\` or not, unless enclosed in `""`; but the `""` are still treated literally.

(Examples below contain 70 numbers; to pad and reach the error. Desired output would be `length 75`.)

`psk_ssid=1234567890123456789012345678901234567890123456789012345678901234567890#blah` gives `Unexpected PSK length 70`.
`psk_ssid="1234567890123456789012345678901234567890123456789012345678901234567890#blah"` gives `Unexpected PSK length 77`.
`psk_ssid='1234567890123456789012345678901234567890123456789012345678901234567890#blah'` gives `Unexpected PSK length 71`.
`psk_ssid=\"1234567890123456789012345678901234567890123456789012345678901234567890#blah\"` gives `Unexpected PSK length 79`.
`psk_ssid=1234567890123456789012345678901234567890123456789012345678901234567890"#blah` gives `Unexpected PSK length 71`(!).
`psk_ssid=1234567890123456789012345678901234567890123456789012345678901234567890"#"blah` gives `Unexpected PSK length 77`.

**Comment by Patricol** [comment]
double quote meaning `"` on each side, right? Not `''` or `""` on each side? If the former; then it won't work for me, because enclosing in `""` brings the length to 65; which breaks things with a length error.

It would be amusing if that actually works for others with shorter passwords; so there's even more processing that happens after that processing; and between them the psk can be rejected based on length even though the length can be changed by later processing.

**Comment by rnhmjoj** [comment]
> # is active (meaning it comments out the rest of the psk), whether escaped with \ or not, unless enclosed in ""; but the "" are still treated literally.

You're overcomplicating it: it's just parsing the line as if it were in the configuration file. If the value after the `=` is double quoted it's an passphrase (between 8 and 64 ASCII characters), if not it's a raw PSK (64 hex digits).

**Comment by Patricol** [comment]
> If the value after the `=` is double quoted it's an passphrase (between 8 and 64 ASCII characters), if not it's a raw PSK (64 hex digits).

Is that consistent with `psk_ssid="12345678901234567890123456789012345678901234567890123456789012345678901234"` erroring with `Unexpected PSK length 66`? If the quotes just cause the value to be interpreted as a passphrase; they shouldn't be counted against the maximum length.

Also:
> If the value after the = is [not] double quoted it's [...] a raw PSK (64 hex digits).

isn't consistent with other non-#-containing passwords succeeding with the `psk_ssid=PASSWORD` format.

**Comment by Patricol** [comment]
`psk_ssid=RAW_64_CHAR_PSK_FROM_WPA_PASSPHRASE` works.

Thank you @rnhmjoj for the raw PSK mention; I didn't know that specifying that was an option. It's not ideal, but it's not like my SSID changes frequently, so it'll work.

We need to add a line about this in the option description though; warning people to use a raw PSK from `wpa_passphrase` if they believe symbols like `#` are giving them problems.

**Comment by rnhmjoj** [comment]
I can confirm the behaviour is indeed inconsistent. The problem appears to be due to the reuse of the code that parses wpa_supplicant.conf for loading the passwords. I guess they just did not think it through, also the format of this file is also not documented enywhere.

I have a fix in https://github.com/NixOS/nixpkgs/pull/342792 if you want to test. I tried the most insane passphrase and it works fine.

**Comment by ahuston-0** [comment]
> I can confirm the behaviour is indeed inconsistent. The problem appears to be due to the reuse of the code that parses wpa_supplicant.conf for loading the passwords. I guess they just did not think it through, also the format of this file is also not documented anywhere.
> 
> I have a fix in https://github.com/NixOS/nixpkgs/pull/342792 if you want to test. I tried the most insane passphrase and it works fine.
> 

Alrighty I just tried it and initial results, it appears to be working? I'll try a few different networks but this is the one I was having issues with so I think I'm good. Lmk if you want me to say the same on the PR

**Comment by rnhmjoj** [comment]
> im guessing i'm hitting an issue since # is considered a comment character. is there an easy way to escape that for the purposes of the password?

Are you sure you're testing with the patch applied? With it `#` starts a comment only if it's the first character on a line.

**Comment by rostby** [comment]
Is there a way to mask the SSID like the previous .env file method?

**Comment by rnhmjoj** [comment]
@rostby that's a good point. Unfortunately this mechanism only applies to passwords.
If you don't want to expose passwords *and* SSIDs to local users you could do this:

  1. Define your networks using wpa_supplicant.conf syntax in some `networks.conf` file
    ```
    # networks.conf
    network={
      ssid="mynetwork"
      psk="mypassword"
    }
    ```
  2. set `networking.wireless.allowAuxiliaryImperativeNetworks`. This makes wpa_supplicant load `/etc/wpa_supplicant.conf` *in addition* to the configuration generated by NixOS.

  3. Install `networks.conf` in /etc/wpa_supplicant.conf` with whatever you use to handle secrets. (It should have permissions 400 and ownership root:root)

**Comment by glwbr** [comment]
Hi, I'm still experiencing issues, my password also had special characters but even after applying the patch and updating my system, the `wpa_supplicant` is unable to connect using the generated `psk` stored in my secret file. I tested manually adding the network and setting the `psk` directly in `wpa_cli`, and it connects successfully. However, it doesn't work when I try to use the secret file. I'm utilizing `sops-nix`. 

Here’s a snippet from my `secrets.yaml`:

```yaml
example_entry: example_secret
wireless: |
    name_sufix=psk
```

```shell
$ ls -l
-r-------- 1 root root 230 out 10 14:02 wireless
```

Then in my config:

```nix
# wireless.nix 
{config, ...}: {
  sops.secrets.wireless = {
    sopsFile = ../secrets.yaml;
    neededForUsers = true;
  };

  networking.wireless = {
    enable = true;
    fallbackToWPA2 = false;

    secretsFile = config.sops.secrets.wireless.path;

    networks = {
      # ....other networks

      "A_SSID" = {
        psk = "AnExamplePasswordThatMakesItConnect";
        # pskRaw = "ext:name_sufix";
      };
    };

    # Imperative
    allowAuxiliaryImperativeNetworks = true;
    userControlled = {
      enable = true;
      group = "network";
    };

    extraConfig = ''
      update_config=1
    '';
  };

  # Ensure group exists
  users.groups.network = {};
  systemd.services.wpa_supplicant.preStart = "touch /etc/wpa_supplicant.conf";
}
```

This worked with the old syntax `@name_sufix@` maybe I'm messing up with the new syntax? Can you guide me on this?

**Comment by auroraanna** [comment]
i can't find anything on how wpa_supplicant's external secrets work. i got PSKs working but not having the password for a WPA-EAP network be an external secret.

**Comment by rnhmjoj** [comment]
@glwbr Sorry for the late reply, I can  think of two possibilities:

1. You didn't apply the patch correctly, or you didn't at all. Now I'm sure it has [reached](https://nixpk.gs/pr-tracker.html?pr=342792) nixos-unstable, so can you update the channel and try again?

2. You did not unescape some of the characters that were considered special in the `environmentFile`. The format of `secretsFile` is now just `ssid=psk`, with absolutely no special processing of any kind. Just type the password as it is.

**Comment by rnhmjoj** [comment]
@auroraanna In `secretsFile` just write `enterprise_pw=mypasswordhere`, as is, no escaping of any kind.
In `configuration.nix` you need something like this for WPA-EAP:
```nix
networking.wireless.networks."enterprise".auth = ''
  key_mgmt=WPA-EAP
  eap=PEAP
  identity="myuser@example.com"
  password=ext:enterprise_pw
'';
```
> I can't find anything on how wpa_supplicant's external secrets work.

As usual with hostapd/wpa_supplicant, there's not much to find. The `ext:` syntax is mentioned briefly in the example wpa_supplicant.conf file (linked in the manual page `wpa_supplicant(5)`). Some more context is found in this [commit message](https://w1.fi/cgit/hostap/commit/?id=e680a51e94a33591f61edb210926bcb71217a21a).

If you tell me what wasn't clear I can try to improve the NixOS release notes and the description of `secretsFile`.

**Comment by glwbr** [comment]
@rnhmjoj Hey, thanks! It worked after the nixpkg update.

**Comment by auroraanna** [comment]
@rnhmjoj the description of secretsFile is adequate, it's just that it didn't work for me back then because the patch hadn't gotten into nixos-unstable yet.

**Comment by rnhmjoj** [comment]
Ok, great!
