### ISSUE TITLE
gdal binary not built correctly for Mac OS X (dyld: … image not found)

### ISSUE THREAD

**Issue by wereHamster** [NixOS/nixpkgs#34216]
## Issue description

I'm trying to install gdal so that I can use its `ogr2ogr` command line tool. It appears that the binary which was built by hydra is not built correctly, as the command fails because it can't find a library. See below.

### Steps to reproduce

```
$ nix-shell -p gdal --command ogr2ogr                                                                                                                                                                8:53
dyld: Library not loaded: /nix/store/mms1hs2h4z75q4hr87lck23b9ccssjz6-mariadb-connector-c-2.3.4/lib/libmariadb.2.dylib
  Referenced from: /nix/store/3mxgcc7205nv4izy7ms19dxryx7jqx73-gdal-2.2.3/bin/ogr2ogr
  Reason: image not found
```

The path is wrong, the correct path would be: /nix/store/mms1hs2h4z75q4hr87lck23b9ccssjz6-mariadb-connector-c-2.3.4/lib/mariadb/libmariadb.2.dylib. Note the extra `mariadb/` folder inside `lib/`.

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 15.6.0, macOS 10.11.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(tomc): `"nixpkgs-18.03pre125997.a8d0b805b19"`
 - nixpkgs: `/Users/<me>/.nix-defexpr/channels/nixpkgs`

**Comment by LnL7** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/34345
