### ISSUE TITLE
urlview not working on OSX

### ISSUE THREAD

**Issue by pjan** [NixOS/nixpkgs#34210]
## Issue description
urlview is not opening links in browser on OSX / Darwin

### Steps to reproduce
1) `echo "https://google.com" | urlview`
2) select the link & 2 times CR
3) should open the url in the browser but it doesn't

## Technical details
not relevant

In homebrew, this is solved by patching the source with setting the `default command` to `open` ([ref](https://github.com/Homebrew/homebrew-core/blob/master/Formula/urlview.rb#L23)).

**Comment by matthewbauer** [comment]
One thing you can do while this is broken is create a ```~/.urlview``` file with:

```
COMMAND open %s
```

**Comment by LnL7** [comment]
Patching the default sounds reasonable to me.
