### ISSUE TITLE
ipvsadm missing

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34226]
## Issue description
The program described by this man page https://linux.die.net/man/8/ipvsadm is not available in master.

### Steps to reproduce
ag ipvsadm

**Comment by dtzWill** [comment]
Poked at this, looks like it needs `libnl1` which [was removed in 2012](https://github.com/NixOS/nixpkgs/commit/5553546c212152a9cea72e1398b088cda78c7b8b) because it was old and krufty even back then (note the patches required).

That seems like a bit of a show-stopper, unfortunately.

**Comment by coretemp** [comment]
Thanks!

Is there a replacement for `ipvsadm` that I am missing? `IPVS` is still a part of the Linux kernel.

**Comment by dtzWill** [comment]
Enjoy! LMK if you're able to actual test it or know how to employ the tools :+1:.

**Comment by coretemp** [comment]
@dtzWill I plan to do that tomorrow. I hope the tools will tell me the crucial information I need to make it work.

**Comment by coretemp** [comment]
@dtzWill This works great and should be merged. It told me something unexpected, but that's good.
