### ISSUE TITLE
nixos: some systemd options are too strict

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#342337]
### Describe the bug
For example, systemd.services.NAME.serviceConfig.ReadWritePaths doesn't
support "-" or "+" qualifiers, unlike upstream systemd (see `man systemd.exec`).

### Expected behavior
NixOS systemd options should allow everything that upstream allows.

### Additional context
I tried to fix the issue myself but got lost in the abstractions :-)

### Notify maintainers
@NixOS/systemd 

### Metadata
NixOS 24.05

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ElvishJerricco** [comment]
> For example, systemd.services.NAME.serviceConfig.ReadWritePaths doesn't support "-" or "+" qualifiers, unlike upstream systemd (see man systemd.exec).

Why do you say this? I'm able to build a system with that just fine, on both 24.05 and unstable.

**Comment by bjornfor** [comment]
> Why do you say this? I'm able to build a system with that just fine, on both 24.05 and unstable.

I got an error message saying the value wasn't a path (when prefixing a path with "-"). But now I'm unable to reproduce :cry: Must have been PEBCAK. Sorry for the noise.
