### ISSUE TITLE
Inconsistent interface names in VMs

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34233]
## Issue description

When using NixOS 39cd40f on a libvirtd VM (via NixOps), there is one networking device less than in VirtualBox and the name is different too. 

In the libvirtd VM, I have:
`enp0s2` and `lo`. 

In VirtualBox I have `enp0s3`, `enp0s8`, and `lo`.

### Steps to reproduce
Launch example from NixOps manual in VirtualBox and libvirtd respectively and run `ifconfig`.

**Comment by zimbatm** [comment]
this is to be expected. `enp0s2` is derived from the network interface metadata and both virtualization technologies emulate different hardare.
