### ISSUE TITLE
poor quality of aria2 package

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#34241]
## Issue description

if you activate the service with
`  services.aria2.enable = true;`

1. there is no webui 
which is fair its not in the main package

2. the service only listens locally 
it makes no sense to me because:
```
    networking.firewall = mkIf cfg.openPorts {
      allowedUDPPortRanges = config.services.aria2.listenPortRange;
      allowedTCPPorts = [ config.services.aria2.rpcListenPort ];
    };
```

it opens by itself the firewall ports which could be a security whole, except the service don't listen to other interfaces

so you have to add 
` services.aria2.extraArguments = "--rpc-listen-all";`

to be able to connect to that service.

I think it should NOT open the port by default in the firewall but add the --rpc-listen-all paramenter as default?

Then the client situation, I already told there is no webui, so you need a non-web client, the cli client which many ui clients also depends on is aria2rpc which is actually in the package under /share/doc... 

- but its not in some environment path
- its not executable, and
- its based on ruby so the dependencies for that get not installed.

The only way to use this as a service with nixos is with the uGet package I guess, if it not also depends on aria2rpc.

Not to mention the problem that its currently not in the plugins.nix file imported so you can't install it easily.

**Comment by spiderbit** [comment]
The first thing would be probably to move the aria2rpc file to /bin and make it executable? any suggestions how you can do that?

then add ruby modules:
 'xmlrpc/client'
 'pp'
 'optparse'
to the package

then add the --rpc-listen-all to the execstart default line.

Also import aria2 in the modules.nix file

**Comment by spiderbit** [comment]
well I guess the firewall thing is not open if you not set:
openPorts = true

so I guess its no security problem?

**Comment by peterhoeg** [comment]
The ports are only opened if configure to do so, so this isn't a security issue.

Having it listen only locally isn't really a problem per se, but I agree it would be much neater with a mechanism to configure what it should be listening on.

Do you feel like taking a stab at a PR?

**Comment by spiderbit** [comment]
Maybe if I find time... have to make it work for me first, the openport thing is one thing, but that there is basicly NO client to use it makes not much sense.

Why install a daemon you can't control :D I mean yes you can use uGet with it, but first thats not very obvious and 2nd if you use a gui for downloading you likely don't need a daemon anyway.

Thats the bigger problem and I found no good workaround for that yet, have to modify the package that it exposes the aria2rpc package and requires its ruby dependencies.

**Comment by indiscipline** [comment]
Yep, the module is probably of poor quality, however, as it is now it works as intended and does not do any obvious harm in the default configuration.

> there is no webui

You're free to use any of the available. There's at least one that definitely works and seems to be maintaned: http://ariang.mayswind.net/ There's a hosted latest version, if you're not inclined to host yours: http://ariang.mayswind.net/latest/

> the service only listens locally

Which is the indended default behaviour. Download manager is predominately a desktop service, however, it can be used on a file server by opening the ports and connecting to it via some client.

> Why install a daemon you can't control :D I mean yes you can use uGet with it, but first thats not very obvious and 2nd if you use a gui for downloading you likely don't need a daemon anyway.

But you can? In the case of using Aria2 for downloading and seeding torrent files it's perfectly reasonable to launch the UI (either web or desktop) on demand and have the daemon work in the background.

The real problem at the moment is that the module doesn't load the saved session on launch. It can be loaded by adding the ``--input-file`` option[1].

[1] https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-i

**Comment by spiderbit** [comment]
The reference Implementation that is delievered with the service:
"aria2rpc"

should be either included or added to a separate package. its like delivering mpd without mpc. No Distro I know of did that.

**Comment by peterhoeg** [comment]
@spiderbit if you have some tangible suggestions (or even better PRs addressing said suggestions) please reopen as this is too vague to be actionable.

**Comment by Stunkymonkey** [comment]
is someone is interested in the GUI please have a look at my PR: #221539
