### ISSUE TITLE
nix-build of a Docker image misplaces env symlink

### ISSUE THREAD

**Issue by Llammissar** [NixOS/nixpkgs#34240]
## Issue description
When I build a new image that includes `pkgs.coreutils`, the resulting tree doesn't have /usr/bin/env (or, indeed, /usr at all).  This breaks pretty much everything written since people learned to use /usr/bin/env to portably find interpreters.  A normal NixOS install has this symlink, so I think it's entirely reasonable to expect it in an image too.

### Steps to reproduce
Build this image:
```
  repro = buildImage {
    name = "repro";
    tag = "latest";
    contents = [
      pkgs.sysvinit
      pkgs.bashInteractive
      pkgs.coreutils
    ];
    config = {
      Cmd = ["/sbin/init"];
    };
  };
```
Load, run, and get a shell in the resulting image and you can see
```
bash-4.4# type env
env is hashed (/bin/env)
bash-4.4# ls /usr
ls: cannot access '/usr': No such file or directory
```

## Technical details
Not sure if it's relevant to this case, but here's the other details
```
[6s] jwe29@jwe29-desktop ~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 3.13.0-107-generic, Ubuntu, 14.04.5 LTS, Trusty Tahr`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(jwe29): `"nixpkgs-18.03pre125190.2f6b88551ba"`
 - nixpkgs: `/home/jwe29/.nix-defexpr/channels/nixpkgs`
```
(Yes, it's an old release.  Not my choice.)

**Comment by jbgi** [comment]
workaround: https://github.com/NixOS/nixpkgs/issues/48462#issuecomment-429889629

**Comment by louwers** [comment]
Still relevant.

**Comment by louwers** [comment]
This can be closed actually: http://ryantm.github.io/nixpkgs/builders/images/dockertools/#sssec-pkgs-dockerTools-helpers-usrBinEnv
