### ISSUE TITLE
`steam-run` fails to start Team Fortress 2 dedicated server (regression)

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#342481]
### Describe the bug
The Team Fortress 2 dedicated server (**not** the in-game server) stopped launching through `steam-run` after https://github.com/NixOS/nixpkgs/pull/340710.  Here is the log:
```
$ steam-run ./srcds_run -console -game tf -nobreakpad -nominidumps -norestart -strictportbind +sv_pure 2 +map cp_sunshine +sv_lan 1
Auto detecting CPU
Using default binary: ./srcds_linux

WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
  Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.

Using shader api: shaderapiempty_srv.so
Loaded 11596 VPK file hashes from /tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 11596 VPK file hashes from /tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 480 VPK file hashes from /tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 480 VPK file hashes from /tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 1344 VPK file hashes from /tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1344 VPK file hashes from /tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 2878 VPK file hashes from /tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 2878 VPK file hashes from /tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 2878 VPK file hashes from /tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 1232 VPK file hashes from /tf2/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /tf2/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /tf2/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 450 VPK file hashes from /tf2/hl2/hl2_misc.vpk for pure server operation.
Loaded 450 VPK file hashes from /tf2/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /tf2/platform/platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /tf2/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
Could not load: replay_srv.so
FATAL ERROR: Could not load: replay_srv.so
```
So what happened with `replay_srv.so`? Well…:
```
$ lddtree bin/replay_srv.so 
bin/replay_srv.so (interpreter => None)
    libtier0_srv.so => None
    libvstdlib_srv.so => None
    libcurl-gnutls.so.4 => None ← now missing!
    libm.so.6 => None
    libdl.so.2 => None
    libstdc++.so.6 => None
    libpthread.so.0 => None
    ld-linux.so.2 => None
    libc.so.6 => None
```
Emphasis mine.

### Steps To Reproduce

0. [Download the TF2 dedicated server](https://wiki.teamfortress.com/wiki/Linux_dedicated_server#Download_the_Server) (no Steam account needed, & substitute `steamcmd.sh` with steamcmd from nixpkgs)
1. Run the TF2 dedicated server with `steam-run`, e.g. with: `steam-run ./srcds_run -console -game tf +sv_lan 1 +map cp_granary` (`s/srcds_run/srcds_run_64/` for the 64-bit dedicated server, which this also occurs with)

### Expected behavior
The server should start.

### Notify maintainers
@K900 (made the change)

Not sure who the other maintainers of the whole `steam-run` thing are.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.9, NixOS, 24.11 (Vicuna), 24.11pre681973.99dc8785f6a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
You really want to run it through steamcmd, so it sets up the Steam runtime.

**Comment by 0n-s** [comment]
Typo? steamcmd is its own program, it can't be used to run other stuff AFAIK.

**Comment by K900** [comment]
It can, use `+app_run <app ID>`

**Comment by 0n-s** [comment]
I will test that in a bit (had to re-download the entire server for some reason), but one issue is that I don't think this can be used to run multiple servers on the same machine, as steamcmd, when it's not installing into a different directory (which I believe is necessary for `app_run` to work, otherwise it gives me a "Missing configuration" error) only allows for one copy of the game on the same machine.

The "Missing configuration" error might affect the version installed in "~/.steam" too, though, I will report back on that in a bit.

**Comment by 0n-s** [comment]
Yep, just as I thought:
```
$ steamcmd +app_run 232250
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726260406
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 84 msec
OK
ERROR! AppId 232250 launch failed (Missing configuration)
```
So you can't really use steamcmd for this.

**Comment by K900** [comment]
You could explicitly use something like `steam-run ~/.steam/root/ubuntu12_32/steam-runtime/run.sh -- path/to/your/game --more --flags` to use the Steam runtime. This should work at least for the `LD_LIBRARY_PATH` runtime.

**Comment by 0n-s** [comment]
That works, thank you. It would be nice if this were documented, though.

**Comment by K900** [comment]
That's not really the correct solution, the correct solution is to figure out why steamcmd isn't working and fix that, because newer games will also use different runtimes that require different kinds of setup, and Steam is the only thing in the chain that knows the right way to start each one.

**Comment by 0n-s** [comment]
Oh, so this is even _more_ of a hack, not a solution, got it. If you need any help with testing, I can help for the program in question.

**Comment by K900** [comment]
Just out of curiosity, can you try running it through steamcmd on https://github.com/NixOS/nixpkgs/pull/341219 ?

**Comment by 0n-s** [comment]
```
$ NIXPKGS_ALLOW_UNFREE=1 nix shell --impure --override-flake nixpkgs 'github:K900/nixpkgs/steamus-yeetus' 'nixpkgs#steam' 'nixpkgs#steamcmd'
$ steamcmd +app_run 232250
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726260406
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 82 msec
OK
ERROR! AppId 232250 launch failed (Missing configuration)

**Comment by jackwilsdon** [comment]
You can get a bit further than "Missing configuration" by logging in with `+login anonymous`, but then you get "Invalid application configuration" when trying to run the server.

It seems like this is because the dedicated server doesn't have any launch options in its configuration and I'm not sure if there's anything that can be done to set them via `steamcmd` (there's `app_set_config` but I can't seem to get that to set the launch executable).

Compare: https://steamdb.info/app/440/config/ with https://steamdb.info/app/232250/config/ (you can also see these using `app_info_print <appid>`).

**Comment by 0n-s** [comment]
`app_set_config` only has presets, basically. This is only really used for Half-Life 1 mods (Counter-Strike 1.6, etc.), which all use the base installation of Half-Life 1 & apply this so-called config to it to set the mod. You can't use it to set arguments, to my understanding.

**Comment by Atemu** [comment]
Given that the correct solution is to get the game to use the steam runtime as intended, I don't think there's anything actionable for Nixpkgs to do here.
