### ISSUE TITLE
Update request: firefoxpwa 2.12.3 → 2.12.4

### ISSUE THREAD

**Issue by tiecia** [NixOS/nixpkgs#342413]
- Package name: firefoxpwa
- Latest released version: 2.12.4

- Current version on the unstable channel: 2.12.1
- Current version on the stable/release channel: 2.12.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@pasqui23
@adamcstephens
@camillemndn

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Partially done already https://github.com/NixOS/nixpkgs/pull/341378
