### ISSUE TITLE
Redundant option for specifying ip address?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34257]
## Issue description
There is
`networking.interfaces.<name?>.ipAddress` and
`networking.interfaces.<name?>.ip4.address` and
`networking.interfaces.<name?>.ip6.address`.

If there exists a relationship between these, perhaps the documentation could mention this?

It's my current understanding that in the case of an IPv4 address `networking.interfaces.<name?>.ipAddress` is the same as `networking.interfaces.<name?>.ip4.address`. Can someone confirm?

### Steps to reproduce
`man configuration.nix`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
Yes, using `ipAddress` or `ipv6Address` is equivalent to adding another entry in the list `ip{4,6}`.
`ipAddress` basically exists for historical reasons as `ip4.*.address` was added later to allow to multiple addresses on the same NIC.

The network interfaces module is rather messy, If you are interested I made an attempt to clean it up a bit in #27688.

**Comment by wizzup** [comment]
I've got this warning on `nixos-rebuild` recently (using `nixos-unstable` channel)

~~~~
trace: warning: The option `ipAddress' defined in `/etc/nixos/configuration.nix' has been changed to `ipv4.addresses' that has a different type. Please read `ipv4.addresses' documentation and update your configuration accordingly.
~~~~

Do I have to do anything ? The [manual](https://nixos.org/nixos/manual/index.html#sec-ipv4) doesn't seem to be updated yet. (or am I reading the wrong one?)

**Comment by rnhmjoj** [comment]
The PR has been merged. In 18.03 the only options will be `networking.interfaces.<name?>.ipv{4,6}.addresses`.
