### ISSUE TITLE
Package request: zen-browser

### ISSUE THREAD

**Issue by joelflaig** [NixOS/nixpkgs#342574]
**Project description**
Firefox-based, privacy-focused, fully customisable browser.

**Metadata**

* homepage URL: https://zen-browser.app/
* source URL: https://github.com/zen-browser/desktop
* releases URL: https://github.com/zen-browser/desktop/releases
* license: Mozilla Public License 2.0
* platforms: generic linux, macos aarch, macos x64

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by idlip** [comment]
#327982
