### ISSUE TITLE
Gamescope totally broken

### ISSUE THREAD

**Issue by radek-stasta** [NixOS/nixpkgs#342512]
### Describe the bug
Current version of Gamescope (3.15.9) is totally broken on my system, freezing, not refreshing image, mouse flickering, creating some weird square in the middle of monitor about 200x200px big where the mouse is locked. Everything broken. Don't know if this is the right place to report this or should I report it upstream.

### Steps To Reproduce
1. Install gamescope from unstable
2. Try to run any game

### Expected behavior
I had no problems with this version and I expect to work as it was then
```
    programs.gamescope = {
      enable = true;
      package = pkgs.gamescope.overrideAttrs (
        finalAttrs: oldAttrs: {
          version = "3.14.29";
          src = pkgs.fetchFromGitHub {
            owner = "ValveSoftware";
            repo = "gamescope";
            rev = "refs/tags/${finalAttrs.version}";
            fetchSubmodules = true;
            hash = "sha256-q3HEbFqUeNczKYUlou+quxawCTjpM5JNLrML84tZVYE=";
          };
        }
      );
    };
```
### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240913.345c263`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source`

Video here: https://streamable.com/ls8zm0 (for 2 days only, will reupload if necesary)

**Comment by winterqt** [comment]
cc @K900
