### ISSUE TITLE
seabios: build non-CSM version for use by incus, lxd, etc?

### ISSUE THREAD

**Issue by srd424** [NixOS/nixpkgs#342650]
#291963 removed CSM support from OVMF because upstream had removed/deprecated it. However we currently only seem to build a CSM-compatible version of seabios, which is of no use now OVMF will not use it. Could we build a normal non-CSM version instead for use by incus, lxd, and any other packages that don't grab a prebuilt version from somewhere?

This seems to be the config that incus upstream uses for their debian / ubuntu packages:
https://github.com/zabbly/incus/blob/032a0da6f606c53e393cd98b952582bde1507462/.github/workflows/builds.yml#L455-L468
(though note apparent typo of `>` instead of `>>` on one line)

@AndersonTorres @adamcstephens @RaitoBezarius

**Comment by adamcstephens** [comment]
How does this benefit incus at all? I’m not understanding the current problem affecting it.

**Comment by srd424** [comment]
Ah, sorry, I should have explained the use case. I'm migrating incus VMs from a non-NixOS environment to incus under NixOS, and some of them don't have UEFI support. For the moment I've used some hacks to override the firmware search path, but if we could build a non-CSM version of seabios we could add it to the incus module (maybe as an option, but seabios is tiny and shouldn't have a runtime closure as it's self-contained, so making it optional might be overkill.)

**Comment by adamcstephens** [comment]
I’m curious how you got non-UEFI VMs in incus. I didn’t realize that was a thing. :)

Anyway I’m happy to help integrate on the incus side as it’s probably just another firmware to expose, but I don’t know anything about seabios. If it’s just some build config changes, maybe it’s easiest to open a PR in draft for discussion?

**Comment by srd424** [comment]
> I’m curious how you got non-UEFI VMs in incus. I didn’t realize that was a thing. :)

`security.secureboot = false` and `security.csm = true` instance options seem to do it - I'm not sure it's a hugely well documentated capability! (Despite the option name, it doesn't use CSM in recent versions for the above reasons.)

Anderson's PR looks good - to add it to incus it just seems to need a symlink to `seabios.bin` dropped in the link farm directory that has already the OVMF files?

**Comment by adamcstephens** [comment]
> Anderson's PR looks good - to add it to incus it just seems to need a symlink to `seabios.bin` dropped in the link farm directory that has already the OVMF files?

Yeah I suspect that’s where incus is looking for it. We should probably also add a test case to the incus virtual-machine test which creates a BIOS VM using the config you shared, and ensures it boots.
