### ISSUE TITLE
vagrant: Adding image failed with "The executable 'bsdtar' was not found"

### ISSUE THREAD

**Issue by rcherrueau** [NixOS/nixpkgs#34264]
## Issue description
Since vagrant is built from source, I got the following error when I try to add an image:

```
The executable 'bsdtar' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

I am on the latest nixos-unstable.

### Steps to reproduce
Install vagrant from nixos-unstable (especially, 8c3553b). Then,

```bash
$ vagrant init
$ sed -i '15s/base/generic\/alpine36/' Vagrantfile # Pick a box you never downloaded, e.g. alpine36
$ vagrant up                                                                                                                      
... 
==> default: Adding box 'generic/alpine36' (v1.3.40) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/generic/boxes/alpine36/versions/1.3.40/providers/virtualbox.box
The executable 'bsdtar' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

## Workaround
Install `libarchive` to make bsdtar available.

```bash
$ nix-shell -p libarchive  
]$  vagrant up
...
==> default: Adding box 'generic/alpine36' (v1.3.40) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/generic/boxes/alpine36/versions/1.3.40/providers/virtualbox.box
==> default: Successfully added box 'generic/alpine36' (v1.3.40) for 'virtualbox'!
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.77, NixOS, 18.03pre126063.95880aaf062 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre126063.95880aaf062"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Pinging @aneeshusa as he was the one writing this derivation.

**Comment by aneeshusa** [comment]
I had `bsdtar` globally installed so I didn't catch this; #34347 has a fix.
