### ISSUE TITLE
question: Nix expression to obtain configured IPv4 DHCP address

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34266]
## Issue description

Is is possible to write a NixOS expression, which obtains the IPv4 address of a given virtual networking interface configured via DHCP? 

It would be particularly nice if  `(builtins.head config.networking.interfaces.virtualinterface.ip4).address` would work, but AFAIK it will just return an empty string when it is configured as such. 

If this is not possible, how can I inject the output obtained into e.g. running an executable like `ip` into a service configuration value again? Running a command like `ip` is not "functional".

The reason I'd like DHCP to assign an IP address for the virtual interface is because the set of IP addresses available might not be known in general.
         
## Technical details

Currently interested in 17.09 release branch

**Comment by rnhmjoj** [comment]
The NixOS configuration is first evaluated and then a system is generated based on it. The address of a DHCP interface is not defined at this point and can change at any later time, how would Nix now that before the system is even running?

Depending of what you are trying to do, yes, calling `ip addr` might work. You mean it's not "functional" in the sense of being a side effect/not deterministic? You will be simply declaring a shell command that will be executed at "runtime", much like the `main` of an Haskell program: the Nix configuration is still deterministic.

**Comment by coretemp** [comment]
In the case of `keepalived` a virtual ip address needs to be defined which is not being used yet, but if the real_servers get their IP via DHCP, it doesn't seem obvious how to make something that works in different cloud environments, on virtual networks, and physical networks without introducing a lot of complexity. 

I need an operation, which creates some virtual ip, but I don't particularly care which one as long as it can be routed. 

The keepalived module seems to be unusable in its current form then, because of the above problem.
