### ISSUE TITLE
Build failure: jetbrains.gateway

### ISSUE THREAD

**Issue by ekisu** [NixOS/nixpkgs#342613]
### Steps To Reproduce

1. build *jetbrains.gateway*

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/fqqyfcxcwfy7jgry6anri77a29h2m81f-JetBrainsGateway-2024.2.1.tar.gz.drv':
         specified: sha256-vEAnwzIgBNBBVx7eSfHcNlbXq87Pa965yqsZEmTmD8s=
            got:    sha256-q5baqet17YgiMLKzi+Tzo3x0pmdUcAPOJMelE0ok4ow=
```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.49, NixOS, 24.11 (Vicuna), 24.11.20240910.1355a0c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager-23.05.tar.gz, musnix, nixos-23.05, nixos-unstable"`
 - channels(eki): `""`
 - nixpkgs: `/nix/store/qpg5mwsind2hy35b9vpk6mx4jimnypw0-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
It downloads correctly over here. Do you have some weird proxy configured?

**Comment by ekisu** [comment]
Huh, seems to work now for me too. I wonder what happened :thinking:
