### ISSUE TITLE
Add fmod to pkgs.fmod

### ISSUE THREAD

**Issue by IQubic** [NixOS/nixpkgs#34279]
## Issue description
When writting a derivation that requires fmod as a dependecy you can't just add fmod to the derivations inputs on the first line. That's becuase who ever added fmod to nixpkgs didn't do it correctly. 

Here is the fmod derivation that was added:
https://github.com/NixOS/nixpkgs/blob/1cb3831f1c64ad9b64db1565572b9c737bae0707/pkgs/games/zandronum/fmod.nix

However, this person didn't add fmod to pkgs.fmod, and instead does an explicit callPackage to add to scope it like this:
https://github.com/NixOS/nixpkgs/blob/1cb3831f1c64ad9b64db1565572b9c737bae0707/pkgs/games/zandronum/default.nix#L8

In my opinion this is an oversight that should be fixed up.

**Comment by jtojnar** [comment]
Does creating a standalone package even make sense? According to their [licensing FAQ](https://www.fmod.com/licensing#faq), it is not even permitted.

**Comment by IQubic** [comment]
If it's not permitted, in thehen how do we have stuff like this fmod derivation in the first place

**Comment by jtojnar** [comment]
Perhaps Zandrodrum has been given an exception? Either way it is an internal library not to be used by others so putting it here makes sense.

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/issues/10213

**Comment by arianvp** [comment]
I think we can close this.  This seems to have been. Deliberate choice to remove it from the public package set.
