### ISSUE TITLE
Update request: crow-translate 2.11.1 → 3.0.0

### ISSUE THREAD

**Issue by x-di** [NixOS/nixpkgs#342889]
- Package name:crow-translate
- Latest released version:3.0.0

- Current version on the unstable channel:2.11.1
- Current version on the stable/release channel:2.11.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@sikmir 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sikmir** [comment]
> The project has migrated under the KDE umbrella, and development will continue at https://invent.kde.org/office/crow-translate.
