### ISSUE TITLE
Recursive nix?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#34284]
I know that this has been discussed many times before but I am not sure about the conclusion...

I want to build a JSON description of the nixpkgs collection with Nix. This would be a Nix derivation that runs `nix-env`. Is this possible?

Here is what I tried:

```
with import ./pkgs.nix {};

let nixpkgs = fetchTarball https://github.com/NixOS/nixpkgs/archive/66b4de79e3841530e6d9c6baf98702aa1f7124e4.tar.gz; in

runCommand "nixpkgs-json" { nativeBuildInputs = [ nix ]; }
  ''
    echo "running nix-env..."
    nix-env --show-trace -f ${./pkgs.nix} -qa --attr-path --drv-path --description --meta --json
  ''
```

and this produced the error:

```
running nix-env...
error: creating directory ‘/nix/var’: Permission denied
builder for ‘/nix/store/biy4h4igcswn81a188vv0q2b1ra9fw4x-nixpkgs-json.drv’ failed with exit code 1
```

**Comment by 7c6f434c** [comment]
I think specifically for this case (you do not build, you just evaluate) you can override `NIX_STATE_DIR`  and maybe something else like that (read about environment variables in `man nix-env`)…

**Comment by sjmackenzie** [comment]
@7c6f434c racket2nix isn't doing so well over here: https://github.com/fractalide/racket2nix/issues/226 Could you explain what you mean when you say override `NIX_STATE_DIR` please?

**Comment by 7c6f434c** [comment]
I mean exporting (in the Unix process environment variable sense) `NIX_STATE_DIR` and similar variables as listed in the manpages to point to an alternative writeable location for store and metadata. This does mean full rebuild, but if you only need to evaluate Nix expressions without running the build, it shouldn't be a problem.

**Comment by sjmackenzie** [comment]
Yeah seems `nix-instantiate` are masking issues https://github.com/fractalide/racket2nix/issues/226#issuecomment-432888117

**Comment by edolstra** [comment]
For an example of the environment variables you need to run Nix inside a Nix build: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/make-tarball.nix

**Comment by sjmackenzie** [comment]
@clacke  ^^

**Comment by clacke** [comment]
@sjmackenzie Wow, ok, cool. Putting the Nix store in the build directory makes Nix like any other command. Makes sense. Won't be useful for actually running recursive Nix, but in our case we're not actually doing that on purpose. In whatever way we're accidentally running Nix, this could possibly be used to work around it.

**Comment by clacke** [comment]
There was no way to call `nix-instantiate` to get `builtins.storeDir` without destroying the data about where the store dir actually is. :-)

Luckily I could rephrase the problem so I didn't need to know where the store is.

**Comment by brainrape** [comment]
Doesn't look like anything new can come from here, closing.
Thank you for your contribution.
