### ISSUE TITLE
lgogdownloader 3.12: terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by stephanschindel** [NixOS/nixpkgs#342829]
### Describe the bug
An assertion is called when trying to download a game from GOG.

### Steps To Reproduce
1. lgogdownloader --login
2. lgogdownloader --game some_game --download

### Expected behavior
Downloading the game assets.

### Additional context

```console
$ lgogdownloader --game wolfenstein_the_old_blood --download --language de
Getting game names (7/7) 38 / 38
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace
Aborted (Speicherabzug geschrieben)
```

### Notify maintainers

@0x4A6F
@LudovicoPiero 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.51, NixOS, 24.05 (Uakari), 24.05.4997.086b448a5d54`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by LudovicoPiero** [comment]
Can you try `nix run github:ludovicopiero/nixpkgs/lgogdownloader/fix-tidy#lgogdownloader -- --game wolfenstein_the_old_blood --download --language de`. I moved the html-tidy to buildInputs.

**Comment by LudovicoPiero** [comment]
Wait, I just realized that you're using stable channel. Try `nix run github:nixos/nixpkgs/nixos-unstable#lgogdownloader -- --game wolfenstein_the_old_blood --download --language de` if this one fixed the issue, I will bump the lgogdownloader on stable channel.

**Comment by stephanschindel** [comment]
Hi there, yes, the unstable version is working fine! That seems to fix the issue.

**Comment by stephanschindel** [comment]
@LudovicoPiero can you bump the stable version?

Thanks!
