### ISSUE TITLE
btrbk: Executable in sbin only

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#34290]
## Issue description

The btrbk executable is only installed to the sbin directory. Therefore that it isn't available in the standard PATH.

If I understand it correctly, normally binaries in sbin are are moved to bin and sbin is linked to bin in the fixup phase. As btrbk is wrapped though in the fixup phase, that isn't done. (See e.g. https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/build-support/setup-hooks/move-sbin.sh)

I'll try to fix this later.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 17.09.2859.8b181d50556 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.12pre5788_e3013543`
 - channels(root): `"nixos-17.09-small, nixos-unstable-18.03pre121484.ff7be8f807d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by fpletz** [comment]
Fixed by #34396.
