### ISSUE TITLE
Nix Planify Package using the wrong package version.

### ISSUE THREAD

**Issue by codeiimon** [NixOS/nixpkgs#342939]
### Describe the bug
Currently, the Planify package on the unstable branch claims to be on the 4.11.2. But when I open the application and check the about section, the about section states that its on the 4.8. I can also confirm this as many of the bug fixes in the later versions are not here (such as overdue tasks not showing up in the Today view).

### Steps To Reproduce
1. Install the Planify package from the unstable branch
2. Open the Planify app and check the "About" section.

### Expected behavior
For it to use the correct version.

### Screenshots
![image](https://github.com/user-attachments/assets/7f8321f0-312a-4e4b-a737-97fa20b79397)

### Additional context
None I can think of.

### Notify maintainers
 @bobby285271 
@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/xfhkjnpqjwlf6hlk1ysmq3aaq80f3bjj-stdenv-linux
copying path '/nix/store/xfhkjnpqjwlf6hlk1ysmq3aaq80f3bjj-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05.20240609.2819fff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/giq1qbcwfx5gq0g9jf6id0b3m55a860j-source`

```

A bit of clarification, even though it says my system is on 24.05, I've installed Planify in a way that the package uses the unstable branch.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Running
```sh
nix-build -A planify && ./result/bin/io.github.alainm23.planify
```
will show version 4.11.2 in the about section. You must have installed planify from somewhere else.

**Comment by codeiimon** [comment]
So, in case anyone is wondering, the issue was I just needed to update the flake lock file, which can be done with `sudo nix flake update`. Then you just rebuild your nix system.
