### ISSUE TITLE
Xmake is broken

### ISSUE THREAD

**Issue by rennsax** [NixOS/nixpkgs#342966]
### Describe the bug

Xmake on Nixpkgs has several issues:

1. It's non-deterministic. On x86_64 Linux `nix run nixpkgs#xmake -- --version`:

```
xmake v2.9.4+20240729, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

Here the timestamp is 20240729, which is related to the build date.

2. It's totally unavailable on aarch64 macOS:

```text
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'xmake-2.9.1'
         whose name attribute is located at /nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source/pkgs/stdenv/generic/make-derivation.nix:333:7

       … while evaluating attribute 'buildInputs' of derivation 'xmake-2.9.1'

         at /nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source/pkgs/stdenv/generic/make-derivation.nix:380:7:

          379|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          380|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          381|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       error: Package ‘tbox-1.7.5’ in /nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source/pkgs/development/libraries/tbox/default.nix:30 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```

`buildInputs` specified [here](https://github.com/NixOS/nixpkgs/blob/99dc8785f6a0adac95f5e2ab05cc2e1bf666d172/pkgs/development/tools/build-managers/xmake/default.nix#L26-L34) are not compatible with aarch64 macOS. At least, `tbox` and `xmake-core-sv` are unavailable.

3. It acts abnormally on Linux.

```console
$ nix shell nixpkgs#xmake
$ xmake create -l c -P ./hello
create hello ...
error: cannot open file: xmake.lua, Not access because it is busy
$ cd hello && xmake
error: ./xmake.lua:7: unexpected symbol near '$'
checking for platform ... linux
checking for architecture ... x86_64
error: ./xmake.lua:7: unexpected symbol near '$'
```

### Expected behavior

It should be deterministic and usable. For example,

```console
$ ./result/bin/xmake --version
xmake v2.9.5+19800101, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

And basic xmake commands should work normally.

### Additional context

My simple derivation works properly on macOS. May I create a PR for discussing?

### Notify maintainers

@wineee 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
> 1. It's non-deterministic.

This is false. Try and rebuild today and you will see that it's the same date. This is due to the usage of `SOURCE_DATE_EPOCH` which is set to the youngest mtime of a file in the tarball which corresponds with the release date in most cases.

> 2\. It's totally unavailable on aarch64 macOS:

This is not an issue of the xmake package but the tbox one. Please create a packaging request for that package on Darwin.

> ```
> error: cannot open file: xmake.lua, Not access because it is busy
> ```

That smells like a packaging bug. Could you `strace -f -e file xmake ...` to figure out where it's trying to `openat()` that file?

The rest is likely caused by the unusccessful project init.

> My simple derivation works properly on macOS. May I create a PR for discussing?

Simple derivation of what exactly?

You are always free to create draft PRs.

**Comment by rennsax** [comment]
> This is false. Try and rebuild today and you will see that it's the same date. This is due to the usage of `SOURCE_DATE_EPOCH` which is set to the youngest mtime of a file in the tarball which corresponds with the release date in most cases.

So it's not necessary to build all binary with `SOURCE_DATE_EPOCH=315532800` like `setup.sh` does [here](https://github.com/NixOS/nixpkgs/blob/b7a0ca2c5b62ccab2b20b4ac148b4275d32b9647/pkgs/stdenv/generic/setup.sh#L534-L540)? Just need to ensure `SOURCE_DATE_EPOCH` is the same when realizing each derivation?

> That smells like a packaging bug.

> You are always free to create draft PRs.

Thanks, let's in the new PR.

**Comment by Atemu** [comment]
> So it's not necessary to build all binary with `SOURCE_DATE_EPOCH=315532800` like `setup.sh` does [here](https://github.com/NixOS/nixpkgs/blob/b7a0ca2c5b62ccab2b20b4ac148b4275d32b9647/pkgs/stdenv/generic/setup.sh#L534-L540)? Just need to ensure `SOURCE_DATE_EPOCH` is the same when realizing the derivation?

Correct. We just need a constant date encoded in binaries rather than whatever `time()` spits out at build-time to gain reproducibility. It doesn't matter which date that is.

(For the Nix store's mtime normalisation it's different as that's global for all derivations rather than a per-derivation attribute.)

**Comment by rennsax** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/343185
