### ISSUE TITLE
hledger package does not install man pages or other user documention

### ISSUE THREAD

**Issue by ajgrf** [NixOS/nixpkgs#34301]
## Issue description

The hledger package in nixpkgs does not include its man pages or other end-user documentation. You can only get its Hackage documentation. I counted the following missing manpages:

* hledger(1)
* hledger_csv(5)
* hledger_journal(5)
* hledger_timeclock(5)
* hledger_timedot(5)

There is also some other documentation which would be nice to include but is probably not essential. I had a hard time determining from the source how it is generated or installed, though.

Maintainer: @peti

**Comment by peti** [comment]
The documentation *is* installed. It's just that hledger puts them into strange locations where system tools can't find them. Check out:

~~~
$ hledger help -h
help [OPTIONS] [MANUAL]
  show any of the hledger manuals, choosing the most suitable viewer (info,
  man, a pager, or stdout). With no argument, list the manuals.

     --info   show the manual with info
     --man    show the manual with man
     --pager  show the manual with $PAGER or less
     --cat    show the manual on stdout
~~~

The command `hledger help --man hledger`, for example, gives you the man page for hledger itself.

It's not a pretty solution. I'll see whether I'll find a way to make those documents visible to system tools without breaking hledger's internal viewer.
