### ISSUE TITLE
package avogadro is broken

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#34307]
## Issue description
Avogadro fails to start with: `avogadro: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`
This problem exists for 17.09 as well as on master (d085af7b7d1365d830b22327b744440b92205c2d). The error can be fixed by using `makeWrapper` to start the binary with `libX11` in the `LD_LIBRARY_PATH`. However, the program then segfaults immediately. Updating avogadro to version 1.2.0 gives the same result.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-97-generic, Linux Mint, 18.1 (Serena)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(markus): `"nixpkgs-17.09.2867.46301566ec7"`

The problem persists when run on NixOS 17.09

**Comment by FRidh** [comment]
Related PR https://github.com/NixOS/nixpkgs/pull/31876

**Comment by fusion809** [comment]
Issue still exists and this repo still provides an outdated version of Avogadro, 1.2.0 is out. Also worthwhile noting that Avogadro2 is available.

**Comment by markuskowa** [comment]
I tried all available versions in Feb. 2018. I couldn't get a single one of them to work on NixOS (segfault on start). I will give it another try and see if any of the them is working now.

**Comment by JohnAZoidberg** [comment]
`nix-shell -p avogadro --run avogadro` opens a GUI program for me on NixOS unstable (`nixos-20.03pre202088.e89b21504f3`).
Can you reproduce?

**Comment by JohnAZoidberg** [comment]
But we've still got 1.1.1 when there's 1.2.0.
