### ISSUE TITLE
Package request: iproute2mac

### ISSUE THREAD

**Issue by aSapien** [NixOS/nixpkgs#343050]
**Project description**

CLI wrapper for basic network utilities on macOS, inspired by iproute2 on Linux systems – ip and bridge commands

**Metadata**

* homepage URL: https://github.com/brona/iproute2mac
* source URL:
* license: mit
* platforms: darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by viraptor** [comment]
It's already packaged at https://github.com/NixOS/nixpkgs/blob/039db25806f936e6a4ad3ab3efd0689a8cc7c23e/pkgs/os-specific/darwin/iproute2mac/default.nix#L5

You need to reference it as `darwin.iproute2mac` though.
