### ISSUE TITLE
broken icons on `kdePackages.dolphin`

### ISSUE THREAD

**Issue by zspher** [NixOS/nixpkgs#343063]
### Describe the bug

Icon custom themes aren't applied in qt6 dolphin. I have tested with `dracula-icon-theme`, `papirus-icon-theme` & `colloid-icon-theme`

When switching back to the qt5 version of dolphin, the custom icon theme is applied.

### Steps To Reproduce

1. apply the ff. config in homemanager

```
gtk.iconTheme.package = pkgs.colloid-icon-theme;
gtk.iconTheme.name = "Colloid-Dark";
platformTheme.name = "qtct";
```

2. choose colloid dark in `qt6ct`
3. open dolphin

### Expected behavior

dolphin uses the custom icon theme

### Notify maintainers

@K900 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.51, NixOS, 24.11 (Vicuna), 24.11.20240913.345c263`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Make sure you have `qtsvg` installed if you want to use SVG icon themes.

**Comment by zspher** [comment]
figured it out
not a nixos issue

to solve this, set icon theme in `~/.config/kdeglobals`

```
[Icons]
Theme=Colloid-Dark
```
