### ISSUE TITLE
Update request: nix 2.18.5 -> 2.24.7

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#343147]
- Package name: nix
- Latest released version: 2.24.7

- Current version on the unstable channel: 2.18.5
- Current version on the stable/release channel: 2.18.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---
@edolstra @lovesegfault @Artturin 

- Critical issue that blocked the upgrade: https://github.com/NixOS/nix/issues/11547
- Not fixed issues: https://github.com/NixOS/nix/issues/10431, https://github.com/NixOS/nix/issues/11098

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MisileLab** [comment]
> [nixpk.gs/pr-tracker.html?pr=335342](https://nixpk.gs/pr-tracker.html?pr=335342)

It reverted because critical issue existed https://github.com/NixOS/nixpkgs/pull/343032

**Comment by MisileLab** [comment]
> @MisileLab It will be updated when the problem was solved. I don't think an issue here is helpful. Update request is for the package which is out-of-dated for so long.

That issue is fixed, that's why I opened issue.

**Comment by DataHearth** [comment]
@MisileLab It has been merge indeed, but reverted right away because a segfault bug => #343032

**Comment by MisileLab** [comment]
> @MisileLab It has been merge indeed, but reverted right away because a segfault bug => #343032

https://github.com/NixOS/nix/issues/11547
That bug reported and fixed

**Comment by Aleksanaa** [comment]
https://github.com/NixOS/nixpkgs/pull/343187

**Comment by Aleksanaa** [comment]
Will try another bump after several days

**Comment by quatquatt** [comment]
> Will try another bump after several days

Maybe time to bump?

**Comment by kirillrdy** [comment]
nix version has been bumped to 2.24. it's currently in staging-next

https://github.com/NixOS/nixpkgs/pull/343421
https://github.com/NixOS/nixpkgs/pull/343421/commits/9a94e073bfc38ad5dcb1d5f35e9c6fbb3886ead4

**Comment by MisileLab** [comment]
staging-next merged
