### ISSUE TITLE
Update request: dart-sass 1.77.6 → 1.79.2

### ISSUE THREAD

**Issue by yunfachi** [NixOS/nixpkgs#343290]
Currently, `dart-sass` is outdated, which makes it hard to work with tailwindcss cli, due to the removal of commas in colors
- Package name: dart-sass
- Latest released version: 1.79.2

- Current version on the unstable channel: 1.77.6
- Current version on the stable/release channel: 1.77.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@lelgenio 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lelgenio** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/352249
