### ISSUE TITLE
Update request: python311Packages.triton 2.1.0 → 3.1.0

### ISSUE THREAD

**Issue by Jonas-Finkler** [NixOS/nixpkgs#343218]
- Package name: python311Packages.triton
- Latest released version: 3.1.0

- Current version on the unstable channel: 2.1.0
- Current version on the stable/release channel: 2.1.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@SomeoneSerge @Madouura

-----

Note for maintainers: Please tag this issue in your PR.

---

Hi, 
I noticed, that pytorch expects a more recent version of triton. 
When compiling for cuda, it tries to import `triton.compiler.compiler.triton_key`, which is not implemented in triton-2.1.0.
The error can be reproduced with the following script
```python
import torch 

@torch.compile
def test_function(x):
    return torch.mean(x)

x = torch.rand((100, 100)).to("cuda")
print(test_function(x))
```
Which raises the exception
```shell
ImportError: cannot import name 'triton_key' from 'triton.compiler.compiler'
```
The latest release tag in the [triton github repository](https://github.com/triton-lang/triton) is 2.1.0.
However, branches for later versions exist up to release/3.1.x.
[Pypi](https://pypi.org/project/triton/) currently packages version 3.0.0.

The packaging of triton is rather complicated and I did not manage to get anything even close to working. 
It would be great if someone with more experience could have a look at this.   

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> The latest release tag in the [triton github repository](https://github.com/triton-lang/triton) is 2.1.0.
> However, branches for later versions exist up to release/3.1.x.
> [Pypi](https://pypi.org/project/triton/) currently packages version 3.0.0.

Please open an upstream issue requesting tags for more recent releases.

**Comment by Jonas-Finkler** [comment]
There is already an upstream issue (https://github.com/triton-lang/triton/issues/3535) but without much progress. 
But I realized, that there is already a [pull request for updating to 3.0.0](https://github.com/NixOS/nixpkgs/pull/328247). 
No idea how I could miss this. Sorry for the noise.

**Comment by SomeoneSerge** [comment]
The PR hasn't been merged yet, keeping this open

**Comment by SomeoneSerge** [comment]
https://github.com/NixOS/nixpkgs/pull/328247 merged, https://github.com/NixOS/nixpkgs/pull/349159/ on the way

**Comment by graham33** [comment]
Looks like https://github.com/NixOS/nixpkgs/pull/349159 was merged, so I think this can be closed.
