### ISSUE TITLE
Update request: SweetHome3D 7.3 → 7.5

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#343279]
- Package name: SweetHome3D
- Latest released version: 7.5
- Current version on the unstable channel: 7.3
- Current version on the stable/release channel: 7.3
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@edwtjo

Release Notes: http://www.sweethome3d.com/blog/2024/08/21/sweet_home_3d_7_5_by_space_mushrooms.html

Note: there are open tickets :  
* #71752
* #303646
* #278518

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR to update: #347910
