### ISSUE TITLE
Update request: mathematica 14.0.0 → 14.1.0

### ISSUE THREAD

**Issue by quatquatt** [NixOS/nixpkgs#343316]
(Note: this may be a somewhat more complex upgrade, as Wolfram has moved to using the Wolfram Installer for everything. Not sure if that'll affect the actual package, though.)

- Package name: mathematica
- Latest released version: 14.1.0

- Current version on the unstable channel: 14.0.0
- Current version on the stable/release channel: 14.1.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@herberteuler  @rafaelrc7 
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by quatquatt** [comment]
Also, I'm not currently able to find a link with the old installer for 14.0.0. Wolfram may have taken it down, making it seemingly impossible to install this package right now. If anyone knows an archive of it, please let me know.

**Comment by quatquatt** [comment]
Found a direct link: 

https://account.wolfram.com/dl/Mathematica?version=14.0&platform=Linux&downloadManager=false

If you're signed into your wolfram account, this will work. This works for using mathematica until the package update.

**Comment by herberteuler** [comment]
I will take a look at this later in October. I apologize for the delay.
