### ISSUE TITLE
Documentation: kitty themeFile

### ISSUE THREAD

**Issue by omarcresp** [NixOS/nixpkgs#343304]
## Problem

I updated the home manager config and i found this warning
trace: warning: The option `programs.kitty.theme' defined in `/nix/store/5s6z8fd6v15lpcxf5k3syl6swsdqfcxj-source/home.nix' has been changed to `programs.kitty.themeFile' that has a different type. Please read `programs.kitty.themeFile' documentation and update your configuration accordingly

but i cant find any info related to this themeFile change anywhere. 

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by janonymousm** [comment]
Have a look at this: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.kitty.themeFile

**Comment by omarcresp** [comment]
wow, awesome thanks. I havent use this github io yet i'll bookmark it, thanks
