### ISSUE TITLE
Package request: atom-editor zen-browser gdm-settings

### ISSUE THREAD

**Issue by Pri700** [NixOS/nixpkgs#343329]
**Project description**

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qwqawawow** [comment]
There is gdm-settings and no zen browser
github atom-editor was already removed.

**Comment by dotlambda** [comment]
One issue per package and fill in the issue template.
