### ISSUE TITLE
`nbqa` is missing from `python3Packages`

### ISSUE THREAD

**Issue by RuRo** [NixOS/nixpkgs#343369]
### Describe the bug

I am not sure, if there is a reason for this, but `nbqa` seems to be packaged differently from other similar python applications. For example, you can install `black` both as a standalone CLI tool via `pkgs.black` and as a python package in a proper python environment with

```nix
pkgs.python3.withPackages (pyPkgs: [
    pyPkgs.black
    # add extra dependencies here
  ]
  # install optional dependencies for blackd
  # ++ pyPkgs.black.optional-dependencies.d
)
```

This doesn't seem to work for `nbqa`, because while `pkgs.nbqa` does exist, `pkgs.python3Packages.nbqa` doesn't.

### Steps To Reproduce

```sh
nix build github:nixos/nixpkgs/c04d5652cfa9742b1d519688f65d1bbccea9eb7e#python3Packages.nbqa
# error: flake 'github:nixos/nixpkgs/c04d5652cfa9742b1d519688f65d1bbccea9eb7e' does not provide attribute 'packages.x86_64-linux.python3Packages.nbqa', 'legacyPackages.x86_64-linux.python3Packages.nbqa' or 'python3Packages.nbqa'
#        Did you mean nbval?
```

### Expected behavior

`nbqa` should be made available as a generic python package (eg in `pkgs.python3Packages.nbqa`).

### Notify maintainers

@l0b0

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Pandapip1** [comment]
This is because `nqba` is packaged using `buildPythonApplication`, rather than `buildPythonPackage`. This is an easy fix.

**Comment by dotlambda** [comment]
This is how it's supposed to be since you don't run `import nbqa`
