### ISSUE TITLE
nix-zsh-completions only works when installed in the profile

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#34333]
## Issue description
I have ``environment.systemPackages = [ nix-zsh-completions ];`` in my config.
When I type ``nix-env -TAB`` I get no completion, or completion of a filename containing ``-``.
When I run ``nix-env -f $NIXPKGS -iA nix-zsh-completions``, open a new shell and try again, it works as expected.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 18.03.git.cb8ff8f (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(bart): `""`
 - channels(root): `"nixos-18.03pre126246.a4f433c03cc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by hedning** [comment]
What's your `$fpath`? It should contain `/run/current-system/sw/share/zsh/site-functions`, if not the completion scripts won't be loaded when it's installed from the system. Though it's weird since the `fpath` should be setup correctly by default.

As an aside, you shouldn't need to include `nix-zsh-completions` manually as it's added by default when `programs.zsh.enable` is true.

**Comment by magnetophon** [comment]
Yes, that path is in my ``$fpath``.

```
 echo $fpath                                                                                                                                                                                                           [17:08:37]
/home/bart/.zprezto/modules/prompt/functions /home/bart/.zprezto/modules/archive/functions /home/bart/.zprezto/modules/git/functions /home/bart/.zprezto/modules/completion/external/src /home/bart/.zprezto/modules/helper/functions /home/bart/.zprezto/modules/utility/functions /usr/local/share/zsh/site-functions /nix/store/yczxdamr3qjqv7csy68gbfi9ns2a13b9-zsh-5.4.2/share/zsh/site-functions /nix/store/yczxdamr3qjqv7csy68gbfi9ns2a13b9-zsh-5.4.2/share/zsh/5.4.2/functions /run/current-system/sw/share/zsh/site-functions /run/current-system/sw/share/zsh/5.4.2/functions /run/current-system/sw/share/zsh/vendor-completions /nix/var/nix/profiles/default/share/zsh/site-functions /nix/var/nix/profiles/default/share/zsh/5.4.2/functions /nix/var/nix/profiles/default/share/zsh/vendor-completions /home/bart/.nix-profile/share/zsh/site-functions /home/bart/.nix-profile/share/zsh/5.4.2/functions /home/bart/.nix-profile/share/zsh/vendor-completions /etc/profiles/per-user/bart/share/zsh/site-functions /etc/profiles/per-user/bart/share/zsh/5.4.2/functions /etc/profiles/per-user/bart/share/zsh/vendor-completions
```

Anything else I can check?

**Comment by magnetophon** [comment]
Odd, I don't even have `` /run/current-system/sw/share/zsh``.

In my config, I have:
``programs.zsh.enable = true;``
``users.defaultUserShell = pkgs.zsh;``
``users.shell = pkgs.zsh;``

I recently tried commenting out a few of those, to get rid of redundancy, but ended up with an unbootable system, so I put it all back.

Here is my full config:
https://github.com/magnetophon/nixosConfig/blob/master/common.nix

**Comment by hedning** [comment]
Ah, you've set `programs.zsh.enableCompletion` to false, just delete the line (it defaults to true) and you should be fine.

**Comment by magnetophon** [comment]
@hedning Yup, that was it.  I could have figured that out myself; sorry for wasting your time.

Thanks!
