### ISSUE TITLE
Include optional bumblebee/optirun package in steam's "chrootenv.nix"

### ISSUE THREAD

**Issue by StijnDW** [NixOS/nixpkgs#3434]
Steam is proprietary software and its installation is a bit weird.
The full explanation is here:
http://sandervanderburg.blogspot.nl/2013/09/composing-fhs-compatible-chroot.html
Is makes use of the following 2 packages:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/steam/steam.nix
https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/steam/chrootenv.nix

This works well for desktops but not for laptops with nvidia "optimus" technology.
The problem is that the program "optirun" (you get it by enabling "hardware.bumblebee.enable" in /etc/nixos/configuration.nix) is not included in the chroot environment.
Optirun is needed to get GPU acceleration in games.

I suspect that the "pkgs" variable in chrootenv.nix optionally needs "optirun", but I'm not sure.

**Comment by ktosiek** [comment]
Can you set `steam.primus = true` in ~/.nixpkgs/config.nix and try again?

**Comment by StijnDW** [comment]
I don't know if it is because of the new steam package (in nixos 15) or because of your suggestion, but it is working now. Thanks!

**Comment by cpages** [comment]
I'm closing this since it looks like it's fixed. Feel free to reopen if that's not the case.

**Comment by Ericson2314** [comment]
So on my machine, `optirun` works but `primusrun` doesn't (assuming I am setting things up right). So I guess there should be config support for either? Maybe a way to substitute any such wrapper?
