### ISSUE TITLE
Cannot build and deploy the new Xen Dom0 module

### ISSUE THREAD

**Issue by hehongbo** [NixOS/nixpkgs#343522]
### Describe the bug
The final merged version of #324911 isn't building.

### Steps To Reproduce
Just build with the initial configuration that `nixos-generate-config` would give on a UEFI machine, along with:
```nix
  boot.initrd.systemd.enable = true;

  virtualisation.xen = {
    enable = true;
    dom0Resources = {
      maxVCPUs = 4;
      memory = 1024;
    };
  };
```

### Expected behavior
Build successfully and boot into Dom0 on next reboot.

### Screenshots
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/6bb4ccc4-ad75-4ed7-8f79-153db8a709f6">

### Additional context
During the progress of #324911, the issue isn't happening as of `ad37ca0`. Might be a regression happened in the last few commits before it's merged.

### Notify maintainers
@SigmaSquadron 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11pre683289.c04d5652cfa9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
Whoops. That's my bad. Will make a PR in a few.
