### ISSUE TITLE
steam: DOTAUNDERLORS

### ISSUE THREAD

**Issue by james007tia** [NixOS/nixpkgs#343594]
**Project description**

Dota underslords dont run in nixos  fix please 

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NotAShelf** [comment]
This is not the correct way to report a bug. Please open a [bug repot](https://github.com/NixOS/nixpkgs/issues/new?assignees=&labels=0.kind%3A+bug&projects=&template=bug_report.md&title=) instead.

**Comment by Steinhagen** [comment]
I gave it a try using the unstable branch and Underlords seem to work just as expected.

![Underlords-Unstable](https://github.com/user-attachments/assets/13e8712a-73d7-4c98-9f12-e4f0e1eff223)

Can you provide more information regarding the errors observed? If those are not relevant enough, maybe your system info and your config might come in handy.

**Comment by SigmaSquadron** [comment]
Nixpkgs already has like 17 billion issues. We can close invalid issues like this one, especially since Steam works for everyone else; this is most likely a network or other state issue with the user's machine.

**Comment by tomodachi94** [comment]
Closing per above.
