### ISSUE TITLE
firewall.service failure on upgrade

### ISSUE THREAD

**Issue by deejayem** [NixOS/nixpkgs#343533]
### Describe the bug
When running `nixos-rebuild switch` on 24.05 I got the following error:

```
Job for firewall.service failed.                                                                                                                         
See "systemctl status firewall.service" and "journalctl -xeu firewall.service" for details.
```

I don't get an error if I run it again.

```
$ systemctl status firewall.service
...
Sep 21 15:41:12 djmuk2 systemd[1]: Reloading Firewall...
Sep 21 15:41:12 djmuk2 firewall-reload[218635]: Warning: Extension policy revision 0 not supported, missing kernel module?
Sep 21 15:41:12 djmuk2 firewall-reload[218635]: iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain nixos-fw-rpfilter
Sep 21 15:41:12 djmuk2 firewall-reload[218565]: Failed to reload firewall... Stopping
Sep 21 15:41:12 djmuk2 systemd[1]: firewall.service: Control process exited, code=exited, status=1/FAILURE
Sep 21 15:41:12 djmuk2 systemd[1]: Reload failed for Firewall.
```

journalctl doesn't appear to show any extra information.

I have the following in my config:
```
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      113
      2222
    ];
  };
```
I also have `services.sshguard.enable = true;`

### Notify maintainers

I'm not sure who to tag here. @izorkin is listed as maintainer for nftables, and @fpletz for iptables. Sorry if you aren't the right people to tag.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 24.05 (Uakari), 24.05.5197.944b2aea7f0a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(djm): `"home-manager-23.05.tar.gz, unstable"`
 - channels(root): `"nixos-24.05, sops-nix"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Izorkin** [comment]
Probably some module in the kernel is missing:
https://github.com/NixOS/nixpkgs/blob/944b2aea7f0a2d7c79f72468106bc5510cbf5101/nixos/modules/services/networking/firewall-iptables.nix#L117-L138

Try disabling these rules.

**Comment by deejayem** [comment]
@Izorkin thank you for the response. How do I disable them?

I see https://github.com/NixOS/nixpkgs/blob/944b2aea7f0a2d7c79f72468106bc5510cbf5101/nixos/modules/services/networking/firewall-iptables.nix#L43 but I can't see how to set `kernel.features`.

**Comment by deejayem** [comment]
My config is very simple, so I'm not sure what I could change to try to track this down. Even with just `networking.firewall.enable` set to true, and no other firewall config, I get the error. And I don't have any kernel-related configuration.

It looks like this block should be enabled by default thought, if I understand the line I linked to earlier, and this one correctly: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/generic.nix#L105

Obviously most people aren't experiencing this issue though, so I'm confused about what's happening.

**Comment by deejayem** [comment]
I do have this in the auto-generated hardware-configuration.nix:
```
  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "xen_blkfront"
  ];
  boot.initrd.kernelModules = [ "nvme" ];
```

I get the error on three different VPSs, but not on my laptop. Could it be related to virtualization somehow?

**Comment by Izorkin** [comment]
I'm not getting the error reproduced on my virtual machine.
Need a full configuration.

**Comment by deejayem** [comment]
See configuration.nix and hardware-configuration.nix in this directory: https://codeberg.org/djm/dotfiles/src/branch/master/nix-conf/machines/djmuk2

(The same issue happens with djmuk1 and edrahil, whose configurations can be seen in the parent directory too, but they aren't very different).

**Comment by Izorkin** [comment]
Try the nixpkgs-unstable branch and kernel 6.6 or/and disable `services.openiscsi`.

**Comment by deejayem** [comment]
It returns `CONFIG_IP_NF_MATCH_RPFILTER=m`.

Only one of the systems affected has openiscsi enabled, and one of the others is already running 6.6, but I can try unstable on one of them tomorrow.

**Comment by Izorkin** [comment]
> It returns `CONFIG_IP_NF_MATCH_RPFILTER=m`.

I have the same thing

Try it:
```
  networking.firewall.checkReversePath = true/false;
```

**Comment by deejayem** [comment]
If I set it to false, the service starts successfully.

**Comment by deejayem** [comment]
Rebooting fixed the issue completely (regardless of `networking.firewall.checkReversePath`). Thank you for your help/sorry for the noise.
