### ISSUE TITLE
rustdesk-flutter misses some shared libraries (--tray flag doesn't work)

### ISSUE THREAD

**Issue by Andrew15-5** [NixOS/nixpkgs#343631]
### Describe the bug

I installed rustdesk-flutter from unstable nixpkgs and tried to run `rustdesk --tray` (which I do on other OS):

```
thread '<unnamed>' panicked at /build/cargo-vendor-dir/libappindicator-sys-0.9.0/src/lib.rs:41:5:
Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I then used this instead:

```nix
(rustdesk-flutter.overrideAttrs (previous: {
  postFixup = (previous.postFixup or "") + ''
    patchelf --add-rpath "${libayatana-appindicator}/lib" "$out/app/rustdesk"
  '';
}))
```

https://github.com/NixOS/nixpkgs/blob/944b2aea7f0a2d7c79f72468106bc5510cbf5101/pkgs/applications/networking/remote/rustdesk/default.nix#L152-L154

But the missing libraries error didn't go away. Maybe they must be copied to "$out/app/lib/"?

Package introduced: https://github.com/NixOS/nixpkgs/pull/286129.

### Steps To Reproduce
1. `nix shell nixpkgs#rustdesk-flutter`
2. `rustdesk --tray`

### Expected behavior
The RustDesk app should start and add an icon to the system tray.

### Additional context
I'm in the process of configuring NixOS flake with home-manager.

### Notify maintainers

@dasj @ShamrockLee

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.51, NixOS, 24.05 (Uakari), 24.05.20240916.086b448`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qkzr5clkyq7j6n43qs5ff73in6c3wacv-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ShamrockLee** [comment]
Thank you for letting me know that RustDesk is available in Nixpkgs. However, I don't have prior experience using or developing this package.

How may I help with this issue?

**Comment by Andrew15-5** [comment]
> Thank you for letting me know that RustDesk is available in Nixpkgs. However, I don't have prior experience using or developing this package.

I mentioned you because you come up in the git blame: https://github.com/NixOS/nixpkgs/blame/71ade9dfb57c26717fe3b973c046e56fdc318145/pkgs/by-name/ru/rustdesk-flutter/package.nix#L66.

> How may I help with this issue?

It looks like it has been already resolved. :)
