### ISSUE TITLE
nginx -t -c: default configuration configured to write to read-only fs

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34378]
## Issue description
nginx: [alert] could not open error log file: open() "/nix/store/hb8dy23a4qkkxx3y3m70wqsn2vyfk56n-nginx-1.12.1/logs/error.log" failed (30: Read-only file system)

### Steps to reproduce

add nginx to `environment.systemPackages` and run

```
nginx -t -c /nix/store/kxgbapyyrxg0q4jxbxnnk0kj0cbrvrn8-nginx.conf
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by fpletz** [comment]
Solution: Default to logging to stderr so that the error log is fed into journald.

**Comment by flokli** [comment]
@fpletz, you're talking about building nginx with `NGX_HTTP_LOG_PATH` and `NGX_ERROR_LOG_PATH` set to `syslog:server=unix:/dev/log,tag=nginx,nohostname,severity=info` and `syslog:server=unix:/dev/log,tag=nginx,nohostname,severity=error` respectively?

**Comment by flokli** [comment]
Ok, seems this currently isn't really supported in configurePhase: https://trac.nginx.org/nginx/ticket/1783#ticket

**Comment by tbenst** [comment]
Just hit this trying to deploy Hydra using [simple-hydra](https://github.com/ElvishJerricco/simple-hydra).

On nixpkgs from Dec 3, nginx worked, but on latest master it does not. Reverting https://github.com/NixOS/nixpkgs/commit/2a413da57efc4c2009c984c63def8e9060771269 fixes. @Izorkin could you take a look? Thank you!

```
   services.nginx = {
      enable = true;
      recommendedProxySettings = true;
      virtualHosts."${hostName}" = {
        forceSSL = true;
        enableACME = true;
        locations."/".proxyPass = "http://0.0.0.0:${toString config.services.hydra.port}";
      };
    };
```

```
> journalctl -xe -u nginx
-- A start job for unit nginx.service has begun execution.
-- 
-- The job identifier is 150585.
Dec 22 03:54:01 hydra-server jdf8k5jc38ny3zfshcnxxiw52l9h8x4b-unit-script-nginx-pre-start[18157]: nginx: [alert] could not open error log file: open() "/var/spool/nginx/logs/error.log" failed >
Dec 22 03:54:01 hydra-server jdf8k5jc38ny3zfshcnxxiw52l9h8x4b-unit-script-nginx-pre-start[18157]: 2019/12/22 03:54:01 [warn] 18158#18158: could not build optimal types_hash, you should increas>
Dec 22 03:54:01 hydra-server jdf8k5jc38ny3zfshcnxxiw52l9h8x4b-unit-script-nginx-pre-start[18157]: nginx: the configuration file /nix/store/1xq12ig3ppbn4kc8fvyy3ny6dxa2izw7-nginx.conf syntax is>
Dec 22 03:54:01 hydra-server jdf8k5jc38ny3zfshcnxxiw52l9h8x4b-unit-script-nginx-pre-start[18157]: 2019/12/22 03:54:01 [emerg] 18158#18158: open() "/var/spool/nginx/logs/access.log" failed (13:>
Dec 22 03:54:01 hydra-server jdf8k5jc38ny3zfshcnxxiw52l9h8x4b-unit-script-nginx-pre-start[18157]: nginx: configuration file /nix/store/1xq12ig3ppbn4kc8fvyy3ny6dxa2izw7-nginx.conf test failed
Dec 22 03:54:01 hydra-server systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStartPre= process belonging to unit nginx.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
```

**Comment by Izorkin** [comment]
@tbenst please run this command and recheck - `chown -R nginx:nginx /var/spool/nginx`

**Comment by flokli** [comment]
@tbenst this issue is about the default `nginx`' config file pointing to a read-only location.

I'll comment in https://github.com/NixOS/nixpkgs/pull/56255 to keep this one focused.

**Comment by flokli** [comment]
Since a19800fb48b52079c55d88c9f6137f58e8d97918, nginx has been configured with explicitly set `http-log-path`, `htt-error-log-path` etc, which default to `/var/log/nginx/….log`.

This seems to be mostly consistent with "out-of-the-box behaviour" on other distributions.

Of course, this folder needs to be writable by the user executing nginx, and most of the time, you'd want to pass a custom configuration file to nginx anyways, but the defaults should be sane:

```
$(nix-build -A nginx)/bin/nginx -T
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
nginx: the configuration file /nix/store/hd9ds94kq4d80qlrylqs3dhw1rlr6xlp-nginx-1.18.0/conf/nginx.conf syntax is ok
2020/09/27 15:33:44 [emerg] 29921#29921: open() "/var/log/nginx/nginx.pid" failed (2: No such file or directory)
nginx: configuration file /nix/store/hd9ds94kq4d80qlrylqs3dhw1rlr6xlp-nginx-1.18.0/conf/nginx.conf test failed
```

Closing this issue.
