### ISSUE TITLE
SDDM astronaut theme does not work (not qt6 compatible?)

### ISSUE THREAD

**Issue by mdietrich16** [NixOS/nixpkgs#343702]
Using SDDM from NixOS-unstable and sddm-astronaut-theme also from NixOS-unstable do not work together. Neither setting the theme in the SDDM module configuration nor trying `sddm-greeter --test-mode --theme /run/current-system/sw/share/sddm/themes/sddm-astronaut-theme/` works, SDDM starts but shows the default theme with the following error message in red:

```
The current theme cannot be loaded due to the errors below, please select another theme.
file:///run/current-system/sw/share/sddm/themes/sddm-astronaut-theme/Main.qml: Library import requires a version
```

### Steps To Reproduce
1. Update to newest nixos-unstable
2. Set
```nix
    services.displayManager = {
      defaultSession = "hyprland";
      sddm = {
        enable = true;
        wayland.enable = true;
        # theme = "sddm-astronaut-theme";
      };
    };
    environment.systemPackages = with pkgs; [
      sddm-astronaut
      sddm-sugar-dark
      sddm-chili-theme
    ];

``` 
somewhere in config.
3. Reboot (or run `sddm-greeter --test-mode --theme /run/current-system/sw/share/sddm/themes/sddm-astronaut-theme/`)
4. ...
5. Profit! No, actually the default theme shows up with a big red error message.

### Expected behavior
Astronaut theme should appear.

### Additional context
The other themes I installed work, i.e. sddm-sugar-dark and sddm-chili-theme.

### Notify maintainers
@DaniD3v

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240919.c04d565`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by DaniD3v** [comment]
The problem is that `sddm-astronaut` is only qt6 compatible and you're using qt5.

The `package` snippet should enable sddm on your system. 
```nix
services.displayManager.sddm = {
  package = pkgs.kdePackages.sddm; # qt6 sddm version
};
```

You'll also need to add the theme to extraPackages to make sddm inherit the right dependencies
```nix
  extraPackages = [sddm-astronaut];
```

Note that the new command is `sddm-greeter-qt6`.

I should probably add an error message if you try to set the theme to `sddm-astronaut-theme` with qt5 sddm but the problem is that I'm only maintaining the theme and not the nix module.

You also need to match nixpkgs version so if you use stable sddm it won't work at all.

I know it kinda sucks that you have to install this package differently...
The sddm theme situation is a bit ugly rn. No promises but I'll probably fix it up sooner or later.

Could you tell me if it works now?

**Comment by mdietrich16** [comment]
Yes, those additions (well, prepend `with pkgs; ` to the `extraPackages` braces) totally fixed it! Thanks for the quick response.
Can you give me a quick hint how I can change the background image for the theme?

**Comment by DaniD3v** [comment]
You can have a look at the sddm file of my [dotfiles](https://github.com/DaniD3v/system-dotfiles/blob/master/common%2Fsddm.nix).

At the overrides you can also change the theme. Don't know the exact option for it but it should be the same as normally configuring sddm.

**Comment by mdietrich16** [comment]
I tried
```nix
  sddm-astronaut = pkgs.sddm-astronaut.override {
    themeConfig = {
      Background = ../../.config/pictures/wallhaven-pastel-island.png;
    };
  };
```
but I get the following error: `evaluation aborted with the following error message: 'generators.mkValueStringDefault: this value is not supported: "/nix/store/3r7b1hdr39nr6z09a431f91jqvz1d3rg-source/.config/pictures/wallhaven-pastel-island.png"'`
I guess passing in a Nix store path is not valid.

**Comment by DaniD3v** [comment]
Pretty sure that's just because nixOS expects you to pass in a string/bool/number and you're passing in a Path.

This snippet will probably work
```nix
  sddm-astronaut = pkgs.sddm-astronaut.override {
    themeConfig = {
      Background = toString ../../.config/pictures/wallhaven-pastel-island.png;
    };
  };
```

toString also keeps the gc info so you don't need to worry about your wallpaper derivation being collected.

**Comment by Nekomi-ch** [comment]
Remember to put the picture in somewhere global  (Not within home directory)

found about it the hard way
