### ISSUE TITLE
Build failure: swift 5.8

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#343707]
### Steps To Reproduce

1. build `swift` (reproduced on M1 darwin)

### Build log

https://gist.github.com/lunik1/3b15453bb1c9340f1a38e83f0d78cfff

### Notify maintainers

@dtzWill @trepetti @dduan @Trundle @stephank 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NotAShelf** [comment]
This is a known issue on Darwin, please see https://github.com/NixOS/nixpkgs/issues/327836

**Comment by lunik1** [comment]
Ah thanks, I had only just started seeing it. Must be pulling in swift as a dependency for some reason...
