### ISSUE TITLE
xautolock service failed to execute locker

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#34371]
## Issue description

Hello, recently I found xautolock service failed to auto lock on my computer. (Not sure how long it has been broken)

`locker = "slock"` and `locker = "i3lock -i /path/to/img"` do not work anymore because the binary file `slock` (and `i3lock`) cannot be found in the `PATH`. (`PATH` env var used by the xautolock service)

Use `locker = "${pkgs.i3lock}/bin/i3lock -i /path/to/img"` instead of `locker = "i3lock -i /path/to/img"` and `locker = "/run/wrapper/bin/slock"` instead of `locker = "slock"` can fix the issue.

However, I think we should warn our xautolock service users that their xautolock is broken and need to use absolute path to refer to locker. Without the warning, users may keep assuming their computer will auto lock (This is very dangerous).

Or we should find out which commit causes this issue then apply a workaround to make it work again.

@Ma27 @WilliButz any ideas?

**Comment by sifmelcara** [comment]
Part of `configuration.nix`:
```
  environment.systemPackages = (import ./common-packages.nix pkgs) ++
  ( with pkgs; [
    chromium
    i3lock
  ]); 
    services.xserverxautolock = {
      enable = true;
      time = 1;
      locker = "i3lock";
    };
```


```
$ systemctl --user status xautolock.service 
● xautolock.service - xautolock service
   Loaded: loaded (/nix/store/nqkcdhh4nzcl8b236ia99fvp5x7cq3z6-unit-xautolock.service/xautolock.service; static; vendor preset: enabled)
   Active: active (running) since Mon 2018-01-29 12:37:47 CST; 5min ago
 Main PID: 31034 (xautolock)
   CGroup: /user.slice/user-1000.slice/user@1000.service/xautolock.service
           └─31034 /nix/store/f47jmnz6hmwh6q979vhgbczj5sf2nfi4-xautolock-2.2/bin/xautolock -noclose -time 1 -locker i3lock

Jan 29 12:37:47 Altocumulus systemd[30966]: Started xautolock service.
Jan 29 12:39:08 Altocumulus xautolock[31034]: /bin/sh: line 0: exec: i3lock: not found
Jan 29 12:40:09 Altocumulus xautolock[31034]: /bin/sh: line 0: exec: i3lock: not found
Jan 29 12:41:10 Altocumulus xautolock[31034]: /bin/sh: line 0: exec: i3lock: not found
Jan 29 12:42:11 Altocumulus xautolock[31034]: /bin/sh: line 0: exec: i3lock: not found
```

**Comment by Ma27** [comment]
hi, I’m truly sorry for your bad experience! I hope that I’ll find some more time in the afternoon to do some investigation to quickly resolve this issue  :)

**Comment by sifmelcara** [comment]
A quick workaround is to add `/run/wrappers/bin:/run/current-system/sw/bin` to `PATH`, right?
One of the reason that I opened this issue is, I'm curious if `locker = "i3lock -i /path/to/img"` still works for you? If that is the case, there may have something wrong in my NixOS.

**Comment by rnhmjoj** [comment]
I can think of two solutions:
1. add a `lockerPackage option, we use this to add the package to `xautolock.path` so relative paths will work.
2. add a check for binary is in PATH or absolute path exists and warn the user in case it results in "command not found". Like it's [done](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/udev.nix#L82) for udev.

What do you think?

**Comment by sifmelcara** [comment]
@rnhmjoj 
I think the `lockerPackage` solution if a little bit imperfect because it cannot work if user uses `slock`, which requires to be executed using `/run/wrappers/bin/slock`. (because it requires setuid)
However, I'm quite satisfied with the second solution. Thank you for providing such great idea!
