### ISSUE TITLE
Mise shell autocompletion fails

### ISSUE THREAD

**Issue by viraptor** [NixOS/nixpkgs#343832]
### Describe the bug

When trying to tab-complete mise, I get

```
$ mise <tab> 
Error: usage CLI not found. This is required for completions to work in mise.
See https://usage.jdx.dev for more information.

Error: usage CLI not found. This is required for completions to work in mise.
See https://usage.jdx.dev for more information.

Error: usage CLI not found. This is required for completions to work in mise.
See https://usage.jdx.dev for more information.
```

### Steps To Reproduce
Try to autocomplete mise command.

### Notify maintainers

@konradmalik

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(viraptor): `"home-manager-23.11.tar.gz, nixpkgs-23.11"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/viraptor/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by viraptor** [comment]
I'd go with the third. I can't see any benefit in getting people to jump through hoops to get the behaviour expected by default in tools.
If there are some benefits to not including it, you could also make it opt-out with an option.

If you add a wrapper on `mise` it doesn't have to be in the general path either, just for that tool.

**Comment by konradmalik** [comment]
Ok, first part is packaging `usage` - https://github.com/NixOS/nixpkgs/pull/343947
After this is merged, I'll be able to wrap `mise` to use it.
