### ISSUE TITLE
Documentation: using cuda-maintainers cache in a flake

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#343816]
## Problem
When building `torch` with CUDA enabled, I'm trying to use the `cuda-maintainers` cache in a standalone flake (I use nixos though).
After reading the CUDA nixos wiki page and googling around, here's what I think could work:
```nix
{
  description = "Torch cuda flake using cuda-maintainers cachix";

  nixConfig = {
    extra-substituters = [ "https://cuda-maintainers.cachix.org" ];
    extra-trusted-public-keys = [
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
    ];
  };

  inputs.nixpkgs.url = "nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      pkgs = import nixpkgs {
        system = "x86_64-linux";
        config.allowUnfree = true;
      };
    in
    {
      devShell.x86_64-linux =
        with pkgs;
        mkShell {
          venvDir = "./.venv";
          buildInputs = [
            (pkgs.python3.withPackages (
              ps: with ps; [
                (torch.override { cudaSupport = true; })
                # openai-triton-cuda
              ]
            ))
            pkgs.virtualenv
            pkgs.python3Packages.venvShellHook
          ];
          postVenvCreation = ''
            unset SOURCE_DATE_EPOCH
          '';
        };
    };
}
```
And in order to be sure that I was using a version of nixpkgs that the binary cache has built I went [on the nixpkgs-cuda-ci page](https://hercules-ci.com/github/SomeoneSerge/nixpkgs-cuda-ci), selected [the most recent successful job](https://hercules-ci.com/github/SomeoneSerge/nixpkgs-cuda-ci/jobs/12755), then at the [hashes for nixpkgs](https://github.com/SomeoneSerge/nixpkgs-cuda-ci/commit/83ce0e1fac89356854bb1ab762636dcdfd3ce30d) and used:
```bash
nix flake lock --override-input nixpkgs github:NixOS/nixpkgs/daf7bb95821b789db24fc1ac21f613db0c1bf2cb
```
to lock `nixpkgs` to the version that was used for the build.

However, when actually building the flake, after having confirmed the usage of the substituter and the public key, I still see nix trying to build torch instead of just downloading.

@NixOS/cuda-maintainers @SomeoneSerge could you pinpoint what I am doing wrong here?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zowoq** [comment]
> tensorflow gives 404 on cachix

Not sure why wasn't pushed but it is in the cache now.

```
$ /nix/store/63hlbwc0z676wyg1gh428s0rw5y7qq0f-cachix-1.7.4-bin/bin/cachix push nix-community /nix/store/9a5mdcn70zppn34mrc19hi0rxs7n4yyx-python3.11-tensorflow-gpu-2.13.0
Pushing 4 paths (204 are already present) using zstd to cache nix-community ⏳
```

**Comment by meditans** [comment]
Thank you @SamueleFacenda, switching my cache to the nix-community hydra instance worked.
For posterity, here are the relevant steps. The nix flake:

```nix
{
  description = "Torch cuda flake using nix-community cachix";

  nixConfig = {
    extra-substituters = [ "https://nix-community.cachix.org" ];
    extra-trusted-public-keys = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  outputs =
    { self, nixpkgs }:
    let
      pkgs = import nixpkgs {
        system = "x86_64-linux";
        config.allowUnfree = true;
        config.cudaSupport = true;
      };
    in
    {
      devShell.x86_64-linux =
        with pkgs;
        mkShell {
          venvDir = "./.venv";
          buildInputs = [
            (pkgs.python3.withPackages (
              ps: with ps; [ torch ]
            ))
            pkgs.virtualenv
            pkgs.python3Packages.venvShellHook
          ];
          postVenvCreation = ''
            unset SOURCE_DATE_EPOCH
          '';
        };
    };
}
```
and one should set the `nixpkgs` input via:
```
nix flake lock --override-input nixpkgs github:NixOS/nixpkgs/$HASH
```
where $HASH is the used revision for the `nixpkgs` input in the hydra build (which can be seen [from here](https://hydra.nix-community.org/eval/71410#tabs-inputs)
