### ISSUE TITLE
go_1_23 is not exported for non-Darwin systems

### ISSUE THREAD

**Issue by kampka** [NixOS/nixpkgs#343923]
In #321916 `go_1_23` was added and exported through `all-packages.nix` for Darwin, but not for non-Darwin systems.

Not sure this is an oversight or intentional.

@kalbasit @katexochen @Mic92 @zowoq

**Comment by katexochen** [comment]
What do you mean by "not exported"? If I do 

```
nix build .#go_1_23
```

On a recent nixpkgs master commit I can build the package on x86_64-linux.

**Comment by kirillrdy** [comment]
@kampka greetings,  `go_1_23` is certainly available on on all `go.meta.platforms`, perhaps your channel is not up to date ?

**Comment by kampka** [comment]
I was mainy going off of `nix search nixpkgs go_1_23` and I'm unsure how `all-packages` works nowadays. 
Looks like it's just not propagated yet.

**Comment by kirillrdy** [comment]
```
nix search nixpkgs go_1_23
* legacyPackages.x86_64-linux.go_1_23 (1.23.1)
  Go Programming language
```

all-packages still works same way, nothing changed there, maybe something else is at hand, what platform/system are you ? and maybe `nix-info -m`

**Comment by kampka** [comment]
```
❯ nix search nixpkgs go_1_23
error: no results for the given search term(s)!

~ 
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.05 (Uakari), 24.05.20240830.6e99f2a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - nixpkgs: `/nix/store/1h99qq6970gkx3j0m9w4yrrl9y99y1nk-source`
```

My current understanding is that the tarball cache for nix flakes expires every hour or so. Is that still the case?

**Comment by kirillrdy** [comment]
i think taball cache more than an hour, but I could be wrong.  `go_1_23` has been on unstable for a few weeks now, so it must be something else

our of curiosity, on my system

```
nix registry list | grep nixpkgs
system flake:nixpkgs path:/nix/store/yqnfkr9pwy2kja1qnvinzlggc6pi7vyh-source
global flake:nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable
```

maybe on you version of nix, nixpkgs is being evaluated as your nixos nixpkgs

can  you try something like `nix search github:nixos/nixpkgs go_1_23` and likewise install is via `nix profile install github:nixos/nixpkgs#go_1_23`

**Comment by kampka** [comment]
```
nix registry list | grep nixpkgs
system flake:nixpkgs path:/nix/store/1h99qq6970gkx3j0m9w4yrrl9y99y1nk-source
global flake:nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable
```

Definitely somewhat odd
`nix search github:nixos/nixpkgs go_1_23` find the correct version, so the tarball pulled via `nix search nixpkgs ...` seems to be outdated and not updating.

**Comment by kirillrdy** [comment]
ok, sounds like a nix bug, if you can come up with reproducible steps please file a bug to nixos/nix

**Comment by kampka** [comment]
Switching to [Lix](https://lix.systems) fixed this. Thanks for your help.
