### ISSUE TITLE
Update unity3d to 2017.3.0

### ISSUE THREAD

**Issue by velovix** [NixOS/nixpkgs#34399]
Unity has introduced the 2017 cycle, with the latest release being 2017.3.0. The current version for the unity3d package is 5.6.1.

@jb55 who is marked as the maintainer for this package.

**Comment by mattfredwill** [comment]
The installation procedure for Unity3d > 2017.3.0 has changed, you now need to run a small binary they provide, which downloads the actual files.

Taking a look at the 2018.1.0b8 version, the downloader seems to fetch an [ini](http://beta.unity3d.com/download/ee2fb9f9da52/unity-2018.1.0b8-linux.ini) that contains a list of components with urls that are publicly accessible. 

Not sure what the best way to package the new versions is, as it seems like we either need to download the components individually and put them together on our end, or patch and run the installer which I'm not sure if thats compatible with nix packaging?

**Comment by Hinidu** [comment]
I'll probably will need to upgrade to Unity3d 2017.4 soon for my working project. I've downloaded the main archive specified in `ini` file and it's content looks pretty similar to the archive embedded into shell script for Unity3d 5. So perhaps it would be pretty simple to update nix-expression for Unity3d 2017. I'm not too experienced with nix packaging but I will try to do that myself and notify all of you if I will succeed or where I will stuck.

**Comment by patroclos** [comment]
@Hinidu did you make any progress on this?

**Comment by Hinidu** [comment]
@patroclos not yet, we suspended upgrade of our project to newer version. Though it became more urgent lately because there is the bug on Android 8 that won't be fixed in version 5.6. So I think we will upgrade in next 3 or 4 weeks.

**Comment by Hinidu** [comment]
@patroclos We've updated our project to Unity 2017.4 and I'm trying to update Unity on my machine right now and found your comment https://github.com/zeit/pkg/issues/321#issuecomment-408297777
I'm getting the same error now. Did you resolve that issue somehow?
