### ISSUE TITLE
should `system.autoUpgrade` still exist?

### ISSUE THREAD

**Issue by Frontear** [NixOS/nixpkgs#343996]
There have been a few issues that pop up in unofficial community spaces about how autoUpgrade would break their systems. The most recent of which was that because their configuration was not in the default location, their system lost some unique configuration changes.

Now while I havent confirmed exactly how true this is, I think in general an option like this serves to be more problematic on a system like NixOS more than anything. There are also other concerning cases, such as a system that has both auto upgrade and auto gc enabled, imagine having an update bump and then a gc soon after..

**Comment by Frontear** [comment]
You raise a fair point, though I do genuinely still think an option like this shouldn't exist. I imagine the overwhelming majority of NixOS users do not use this option.

Furthermore, given https://github.com/NixOS/nixpkgs/issues/347315, it's fairly evident that this module is not tested for actual "functionality". Who knows when and how long it's been broken, maybe its a user-specific issue, the point is that I don't believe it is given enough attention to warrant keeping it around. If users want to setup automatic upgrades, they should prefer setting up imperative services or timers, and not a module within nixpkgs!

**Comment by emilazy** [comment]
It’s actually really common to use this option on servers and I’m not sure why you think it’s so marginal.

**Comment by Frontear** [comment]
As I was writing out a response, I started to backtrack on my above thoughts. I forget to consider that ultimately, this type of thing is **opt-in**, and anyone who chooses to do so, does so at their own discretion. Breakages can happen upgrading manually or automatically, so I guess my point is a bit moot.

Anyways I realize I'm arguing a nonsensical POV. I don't agree with automatic upgrades, but that's an entirely personal opinion, and it doesn't make sense on a broader scale. Furthermore, the _choice_ to opt into automatic upgrades is ultimately a personal one, and finally, there are realistically no issues an automatic upgrade would have that a manual upgrade wouldn't. If your system is going to break, it will break, and even then, we just get to roll back to a fixed state.

Closing 👋

<details>
<summary>What I was typing, for those curious</summary>
From my own experience and from what I see on the Discourse, GitHub issues, Matrix etc. upgrades have chances to cause regressions in people's working configuration. Just recently we had the whole NVIDIA and Linux 6.11 issue which broke a lot of people's configurations, we've had plenty of even larger-scale issues before that (looking at the Rust regressions), and then we've also had smaller regressions that only affect a smaller group yet deserve equal consideration. For the most part I also presume these users upgraded manually, only because there is usually no evidence of them suggesting otherwise (though admittedly that presumption itself is biased).

In a rolling distribution like NixOS, encouraging automatic upgrades seems to be akin to shooting oneself in the foot. To be fair, it's great that at least on NixOS a broken system can be rolled back from very easily thanks to generations, but I still believe that the practice shouldn't be encouraged. Everyone has unique configurations and its downright impossible to catch every single possible issue and regression that squeezes past our already comprehensive testing suite.
</details>

**Comment by Echaleon** [comment]
> As I was writing out a response, I started to backtrack on my above thoughts. I forget to consider that ultimately, this type of thing is **opt-in**, and anyone who chooses to do so, does so at their own discretion. Breakages can happen upgrading manually or automatically, so I guess my point is a bit moot.
> 
> Anyways I realize I'm arguing a nonsensical POV. I don't agree with automatic upgrades, but that's an entirely personal opinion, and it doesn't make sense on a broader scale. Furthermore, the _choice_ to opt into automatic upgrades is ultimately a personal one, and finally, there are realistically no issues an automatic upgrade would have that a manual upgrade wouldn't. If your system is going to break, it will break, and even then, we just get to roll back to a fixed state.
> 
> Closing 👋
> What I was typing, for those curious

In my use case at least, these are on my servers, and I have a small service that runs after the auto upgrade that copies the flake.lock file to a persistent and shared repo after update. As all my servers are running impermanent root by default anyways, in the catastrophic case, I can copy the few persistent directories over, drop my configs in, and copy the last working flake in if the system somehow completely hoses itself. Otherwise they just roll and I don't have to worry about them. I would completely agree that autoUpgrades on the unstable branch is a bad idea though.

**Comment by voronind-com** [comment]
You can autoUpgrade without updating the lock file. This way you only pull your own configuration changes.
