### ISSUE TITLE
stub-ld does not throw `ENOENT` like missing ld.so

### ISSUE THREAD

**Issue by ntkme** [NixOS/nixpkgs#344080]
### Describe the bug

While it's good that stub-ld does give user some human friendly information, the behavior has diverged from the actual behavior of missing ld.so, that stub-ld does not "throw" an ENOENT error in `execve` syscall.

### Steps To Reproduce
1. Calling `exec()`  on a foreign executable in ruby programming language.

### Expected behavior
`exec()` foreign executables in ruby should throw `Errno::ENOENT` with stub-ld, after printing the human friendly message to stderr.

It might be tricky that stub-ld need to be implemented in a way that's more close to the how a real ld.so works, but should be feasible.

### Additional context

The `sass-embedded` ruby gem relies on `ENOENT` to be thrown in order to detect NixOS and launch the correct elf interpreter. However, this no longer works since the introduction of `stub-ld`. See https://ntk.me/2023/06/04/invoking-ld-linux-so/

### Notify maintainers

@tejing1

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tejing1** [comment]
Oof. I was afraid there'd be a fringe case incompatibility like this. Unfortunately I'm not really knowledgeable enough about the details of how `execve` actually interacts with `ld.so` to know how to fix it. Or if it's even possible.

If a normal `ld.so` is capable of triggering that error condition, then it should certainly be possible to make the stub do so as well, in theory. Are we certain that it can?

**Comment by ntkme** [comment]
> Are we certain that it can?

I double checked the man page of `execve`, and the answer is probably not... So it seems the error is raised by `execve` not ld.so, that if ld.so exists, `execve` simply won't throw the same error.

> ENOENT The file pathname or a script or ELF interpreter does not exist.

**Comment by Atemu** [comment]
Would it be possible to simply throw ENOENT ourselves and just have it bubble up to the caller of execve?

**Comment by tejing1** [comment]
I don't think so. I'm not super clear on the structure here, but I suspect the ENOENT has to be produced before the process is replaced. By the time `ld.so` is running, it's too late to return ENOENT back to the calling code, because the calling code is gone.

If my understanding it correct, there should be no way to fix this while retaining stub-ld functionality, short of patching the kernel.

**Comment by ntkme** [comment]
> If my understanding it correct, there should be no way to fix this while retaining stub-ld functionality, short of patching the kernel.

Yes. I'm ok to close it as won't fix, as I managed to come up with a workaround: https://github.com/sass-contrib/sass-embedded-host-ruby/pull/235/files
