### ISSUE TITLE
IPTSD: Option "services.iptsd.config.Touch" is called "Touchscreen" in v3

### ISSUE THREAD

**Issue by xieve** [NixOS/nixpkgs#344002]
### Describe the bug
The option `services.iptsd.config.Touch` declared [here](https://github.com/NixOS/nixpkgs/blob/9357f4f23713673f310988025d9dc261c20e70c6/nixos/modules/services/hardware/iptsd.nix#L21) is invalid in IPTSD v3, because it has been renamed `Touchscreen` to differentiate it from `Touchpad`. It does not have any effect.

### Steps To Reproduce
1. Add to configuration
```nix
services.iptsd = {
  enable = true;
  config.Touch = {
    DisableOnStylus = true;
    DisableOnPalm = true;
  };
};
```
2. Observe that neither option is effective.

### Expected behavior
I expected the options to work as documented.

### Additional context
You can find the relevant commit in IPTSD [here](https://github.com/linux-surface/iptsd/commit/a82807ae4d94714cb95a2ef1f4ed6893107fefa6) or consult the sample configuration file that is linked in the docstring for `services.iptsd.config` to confirm.

I would suggest that that link is updated to a permalink pointing to the version that is built by the nix package, instead of pointing to the latest.

Further, I would suggest that all options in `services.iptsd.config` be removed, due to the following reasons:
- There are far more options than currently documented
- The fact that some of them are, while others aren't, can potentially be confusing
- As one can see here, they are subject to change
- Other packages that implement a subset of available options similar to this follow a pattern where you can find those options in the "root" of the module options, e.g. `services.*`, and additionally have an attribute set option called `extraConfig` or similar that is empty by default

### Notify maintainers

@dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5, NixOS, 24.11 (Vicuna), 24.11.20240919.c04d565`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
> There are far more options than currently documented

That's why it's a `freeformType`. See https://github.com/NixOS/rfcs/pull/42.

**Comment by dotlambda** [comment]
> I would suggest that that link is updated to a permalink pointing to the version that is built by the nix package, instead of pointing to the latest.

That would require the documentation to built with access to packages which is discouraged.

**Comment by dotlambda** [comment]
> Observe that neither option is effective.

They should still be effective: https://github.com/linux-surface/iptsd/commit/a82807ae4d94714cb95a2ef1f4ed6893107fefa6#diff-e44a9efb23b83082a47e537baba837e84d2327ff3779da425942972e7a0e84d7R188

**Comment by xieve** [comment]
> That would require the documentation to built with access to packages which is discouraged.
Ah, okay, that makes sense.

> They should still be effective
Damn it, that means I need to fiddle with the other options... Sorry about that.

Thanks for the quick response :)

**Comment by xieve** [comment]
> Observe that neither option is effective.

It's the other way around: 
```nix
services.iptsd.config.Touchscreen = {
  DisableOnStylus = true;
  DisableOnPalm = true;
};
```
This has no effect! Since the declaration of the default values comes first. That's where my confusion came from.

Is there a good way to avoid this? Maybe set those options at the end of the ini, instead of the beginning? I assume it is parsed top-down and re-declarations are ignored.
