### ISSUE TITLE
Update request: terraform-docs 0.17.0 → 0.19.0

### ISSUE THREAD

**Issue by nipr-jdoenges** [NixOS/nixpkgs#344066]
- Package name: terraform-docs
- Latest released version: 0.19.0

- Current version on the unstable channel: 0.18.0
- Current version on the stable/release channel: 0.17.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@zimbatm 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ocfox** [comment]
Wait until #342429 is merged into the master.
