### ISSUE TITLE
Iosevka: missing all fonts besides sans-serif version

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#344082]
### Describe the bug
`iosevka` (not necessarily `iosevka-bin`, did not check) does not package any of Iosevka besides the sans serif version.

### Steps To Reproduce
1. Install `iosevka`.
2. `fc-list|grep -E 'Iosevka Slab|Iosevka Aile|Iosevka Etoile'`

### Expected behavior
`iosevka` package should have all the fonts in the Iosevka family.

### Notify maintainers
@ttuegel
@rileyinman
@lunik1

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11pre684053.9357f4f23713`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lunik1** [comment]
This is by design for the `iosevka` package. It is intended for use with a private build plan, and will just build the default configuration when one is not supplied.

**Comment by 0n-s** [comment]
Unexpected, but good point.

**Comment by lunik1** [comment]
There's a fair argument to add a `iosevka-etoille-bin` (et al.) package, though. Or add an `etoille` etc. output to the existing `iosevka-bin` package.
