### ISSUE TITLE
`vscode-fhs` starts with wmclass set as `code-url-handler`

### ISSUE THREAD

**Issue by ahydronous** [NixOS/nixpkgs#344035]
### Describe the bug
VSCode starts with its wmclass set wrong, which causes various bugs like being unable to be pinned to the dash, and opening new windows under a separate icon instead of under its "main" icon.

![image](https://github.com/user-attachments/assets/348cbe92-71c6-42e6-921e-f5a80f83a09a)

### Steps To Reproduce
1. Open VSCode
2. Try to pin it
3. Open a window

### Expected behavior
VSCode should be able to be pinned, and windows should nest under the icon properly.

### Additional context
See: https://github.com/VSCodium/vscodium/issues/1414 and https://github.com/microsoft/vscode/issues/129953 for the same issue. I am assuming this also affects the `vscode`, `vscodium` and `vscodium-fhs` NixOS packages.

The Microsoft issue contains references to workarounds/fixes/patches.

### Notify maintainers
@eadwu 
@Synthetica9 
@bobby285271 
@Enzime 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
normal vscode package does that too.

**Comment by onnyyonn** [comment]
> on kde, you can override the desktop file with a window rule to make it group with the pinned icon properly.

@griffi-gh can you please elaborate on how to do that?

**Comment by griffi-gh** [comment]
> on kde, you can override the desktop file with a window rule to make it group with the pinned icon properly.
> 
> @griffi-gh can you please elaborate on how to do that?

@onnyyonn 
![image](https://github.com/user-attachments/assets/225b65a1-222e-4255-a46b-16960ab4c007)
Create a window rule like this
Set desktop file name to vscode's `.../share/applications/code.desktop` (in my case, `/etc/profiles/per-user/user/share/applications/code.desktop`)

or, with plasma-manager:
```nix
    {
      description = "vscode-desktop-file";
      match.window-class = "code code-url-handler";
      apply.desktopfile = "/etc/profiles/per-user/user/share/applications/code.desktop";
    }
```
you may want to use actually specify path to the vscode package instead of hard-coding it tho!

**Comment by Luflosi** [comment]
This should be fixed in https://github.com/microsoft/vscode/pull/231472. I believe version 1.95.0 includes this fix. Vscodium has only been updated two days ago and should be available in the cache in the following days.
Please reopen if this is still a problem.

**Comment by onnyyonn** [comment]
I am on vscode 1.100.2 and this is still a problem.
