### ISSUE TITLE
package request: rpl

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34413]
## Issue description
http://rpl.sourceforge.net (text replacement tool)

### Steps to reproduce
ag http://rpl.sourceforge.net nixpkgs

**Comment by dotlambda** [comment]
How about doing that yourself? A simple `buildPythonApplication` and copying the man page to the right place (in `postInstall`) should do the trick.
See https://nixos.org/nixpkgs/manual/#building-packages-and-applications and grep for `pythonPackages.callPackage` in https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix.

**Comment by teto** [comment]
it is already packaged :)

**Comment by coretemp** [comment]
@teto Thanks, I found it in in `master`. 

`ag 'pname = "rpl'` will find it for those wondering.
