### ISSUE TITLE
Update request: svp 4.5.210-2 → 4.6.263

### ISSUE THREAD

**Issue by rafal11ck** [NixOS/nixpkgs#344148]
- Package name: svp
- Latest released version: 4.6.263

- Current version on the unstable channel: 4.5.210-2
- Current version on the stable/release channel: 4.5.210-2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@xddxdd 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by rafal11ck** [comment]
New version solves https://github.com/NixOS/nixpkgs/issues/295429
https://www.svp-team.com/forum/viewtopic.php?id=7092
and makes https://github.com/NixOS/nixpkgs/pull/295503 obsolete.

**Comment by xddxdd** [comment]
Opened PR #344152
