### ISSUE TITLE
Package broken: affine  0.16.0 

### ISSUE THREAD

**Issue by f0rdprefect** [NixOS/nixpkgs#344156]
### Describe the bug

After the welcome screen I get just a white screen with some error messages:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'status')
TypeError: Cannot read properties of undefined (reading 'status')
    at G (file://./js/1067.7520c752.js:2930:509808)
    at af (file://./js/npm-react.7166c062.js:9:58409)
    at i (file://./js/npm-react.7166c062.js:9:119367)
    at oF (file://./js/npm-react.7166c062.js:9:99023)
    at file://./js/npm-react.7166c062.js:9:98890
    at oM (file://./js/npm-react.7166c062.js:9:98897)
    at oS (file://./js/npm-react.7166c062.js:9:95649)
    at ow (file://./js/npm-react.7166c062.js:9:94204)
    at E (file://./js/npm-react.7166c062.js:33:1364)
    at T (file://./js/npm-react.7166c062.js:33:1894)
    at file://./js/vendor.68479ded.js:84:96161
    at d (file://./js/vendor.68479ded.js:84:96271)
    at p (file://./js/vendor.68479ded.js:84:96372)
```

### Steps To Reproduce

1. in case already run: `rm -rf ~/.config/AFFiNE`
2. `nix run nixpkgs#affine`
3. click through  welcome screen  

### Expected behavior

Working app

### Additional context

not sure if relevant:wayland / hyprland session. Other Electron apps work fine.

### Notify maintainers
@ri-char , @redyf 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240921.9357f4f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/y6205wq8hxvpqvl8l9d1n9xah01kg0lq-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by redyf** [comment]
Thanks for letting us know, I'm currently testing the package to see what's causing it. The weird thing is that it was working when I made the PR for v0.16.0.

**Comment by f0rdprefect** [comment]
Meanwhile I tried the appimage provided by affine. It is v0.17.0 and  is working fine. Maybe upstream does not support older versions as they are moving quite fast as far as I can see?

**Comment by redyf** [comment]
I believe you're right as v0.17.0 worked for me aswell, however instead of using an appimage I just bumped the current version to v0.17.0. I'll make a PR for it soon
