### ISSUE TITLE
plasma[56]: SDDM wayland session with no home requires `/bin/bash`

### ISSUE THREAD

**Issue by hexlic** [NixOS/nixpkgs#344185]
### Describe the bug
SDDM scripts executed when a new session with a new home is created point to /bin/bash which does not exist.

### Steps To Reproduce
1. Set up plasma 5 or 6 like this :
```nix
   ## plasma 5, X11
  services = {
    displayManager.sddm.enable = true;
    xserver = { enable = true;
      desktopManager.plasma5.enable = true;
    };
  };
```
```nix
# plasma 6, wayland
services = {
  desktopManager.plasma6.enable = true;
  displayManager.sddm.enable = true;
  xserver.enable = true;
};
```
2. set up logging in like this (sddm)
``` nix
  security.pam.services.login.makeHomeDir = true;
  services.displayManager.sddm.settings = {
    Auth.AuthMethod = "pam";
  };
```
3. Try to login as user that has no home
4. Session crashes: `share/sddm/scripts/wayland-session: line 16: /bin/bash: No such file or directory`
5. Come back to SDDM (effectively loops back to point 3)

### Expected behavior
One of
- `/bin/bash` is linked to real bash for compilance
- sddm scripts use a more flexible bash shebang
so that the home gets created, and session launches.

### Additional context
Authentication is handled via LDAP and `nss_pam_ldapd`

#### Workaround
I have fixed this by adding this to my configuration:
```nix
system.activationScripts.binbash = {
  deps = [ "binsh" ];
  text = "[ -z /bin/bash ] && ln -s /bin/sh /bin/bash";
};
```
### Notify maintainers
Taken from git log, I hope it's right
@K900 @SuperSandro2000

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.5197.944b2aea7f0a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
SDDM uses `$SHELL`: https://github.com/sddm/sddm/blob/4ec29a8bba033d475f197693fac6cb0c383a1da2/data/scripts/wayland-session#L4

Your PAM module presumably sets it to /bin/bash which is wrong.

**Comment by SuperSandro2000** [comment]
From personal experience I cannot recommend envfs. Last time I tried to use it, it broke agetty.

**Comment by hexlic** [comment]
> SDDM uses `$SHELL`: https://github.com/sddm/sddm/blob/4ec29a8bba033d475f197693fac6cb0c383a1da2/data/scripts/wayland-session#L4
> 
> Your PAM module presumably sets it to /bin/bash which is wrong.

Who should I ping then?

> You can probably work around this by enabling services.envfs.

I just need it for one symlink, I think setting an option for this might be overkill for me.

**Comment by K900** [comment]
I don't think there's anyone to ping, you just need to set the right login shell for your users in your LDAP.

**Comment by hexlic** [comment]
I see.
Then what should it point to on nixos?

**Comment by K900** [comment]
`/run/current-system/sw/bin/bash` probably

**Comment by hexlic** [comment]
That would not work on anything other than nixos...
Maybe modifying the script to point to do `ln -s /bin/sh /run/current-system/sw//bin/bash` would be better?

**Comment by K900** [comment]
You could use `/bin/sh`, I guess, or maybe you can figure out how to make the NSS module make this conditional. I don't really know, either way, this is not an SDDM bug.
