### ISSUE TITLE
Update request: temurin-bin-21 21.0.3 → 21.0.4

### ISSUE THREAD

**Issue by Zoriot** [NixOS/nixpkgs#344217]
- Package name: temurin-bin
- Latest released version: [21.0.4+7-LTS](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.4%2B7)

- Current version on the unstable channel: 21.0.3
- Current version on the stable/release channel:  21.0.1 (temurin-bin-21 doesn't show up, would be nice if both be backported)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@taku0 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
Done in #337620
