### ISSUE TITLE
security.acme

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#34422]
## Issue description

we are creating `security.acme` records from two modules:

* nixcloud.email
* nixcloud-webservices

my original idea was that they could share the certificates but the `security.acme` won't merge my configurations and bails out with:

## config from module a

```security.acme.certs = {
    "example.com" = {
      webroot = "/var/lib/acme/acme-challenge";
      domain = "example.com";
      extraDomains = { "lastlog.de" = null; };
    };
  };
```

## config from module b

```  security.acme.certs = {
    "example.com" = {
      webroot = "/var/lib/acme/acme-challenge";
      domain = "example.com";
    };
  };

```

## the error message

```
nix-repl> :p config.security.acme.certs."example.com"
{ _module = { args = { name = "example.com"; }; check = true; }; allowKeysForGroup = false; domain = «error: The unique option `security.acme.certs.example.com.domain' is defined multiple times, in `/etc/nixos/configuration.nix' and `/h}
```

# question & current solution

i wonder if certificate sharing can even work with the way `security.acme` is designed at the moment. 

so for now, until someone can teach me otherwise, i will just issue a new certificate per abstraction which means:

* more certificates to handle
* faster exceeding or using up the certificate pool (let's encrypt issues 4/week for a single domain IIRC)

**Comment by zimbatm** [comment]
agreed this is weird, I would expect the submodule to recursively merge.

**Comment by zimbatm** [comment]
the answer is probably somewhere in here: https://github.com/NixOS/nixpkgs/blob/71631a922b4005497fe3b93fdfe5899e2f6d7a2c/lib/types.nix#L263
the submodule system is quite hard to read

**Comment by qknight** [comment]
@zimbatm thanks for your insight. (just wanted to point this out and see if i was right or missed something).

**Comment by qknight** [comment]
@zimbatm i've figured the merging issue out:

with this code i was able to merge the 'domain' properly. 

```
  myDomain = mkOptionType {
    name = "myDomain";
    merge = mergeEqualOption;
  };
...
  certOpts = { name, ... } @ toplevel: {
    options = {
      domain = mkOption {
        type = myDomain;
        description = "Domain to fetch certificate for (defaults to the entry name)";
      };
```

**note: **
* mergeEqualOption can be found in `<nixpkgs>/lib/options.nix` and is used by `types.bool`
* other attributes, as `email` for instance, also need this 'special' type to merge correctly
