### ISSUE TITLE
SSH does not recognise RemoteCommand directive in config file

### ISSUE THREAD

**Issue by RdN-MSF** [NixOS/nixpkgs#34427]
## Issue description
According to [the release notes](https://www.openssh.com/txt/release-7.6) SSH recognises the `RemoteCommand` directive since version 7.5. Using this, however, throws the following error:

`.ssh/config: line 24: Bad configuration option: remotecommand`
`.ssh/config: terminating, 1 bad configuration options`

On Arch Linux, using SSH 7.6, this option works fine.

### Steps to reproduce

Add the following to `.ssh/config`:

`RequestTTY Force`
`RemoteCommand watch "date"`

And then run `ssh localhost`. The expected behaviour is to get an SSH session with the watch command, but on NixOS this gives the aforementioned error.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.15, NixOS, 17.09.2875.c2b668ee726 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2875.c2b668ee726"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Infinisil** [comment]
The feature got added in 7.6, *not* 7.5 (you even linked to 7.6's release notes). And the 17.09 channel still uses version 7.5, so it all makes sense.

**Comment by RdN-MSF** [comment]
You're completely right, I misread the release notes. Thanks for taking the effort to reply anyway.
