### ISSUE TITLE
Update request: keyd 2.4.3 → 2.5.0

### ISSUE THREAD

**Issue by alfarelcynthesis** [NixOS/nixpkgs#344339]
- Package name: keyd
- Latest released version: 2.5.0
- Current version on the unstable channel: 2.4.3
- Current version on the stable/release channel: 2.4.3
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

This is mostly for homerow mod support.

**Notify maintainers**

@peterhoeg 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AlfarelSynthesis** [comment]
If you can't get to this, I can probably figure out contributing at some point, but not immediately :)

**Comment by peterhoeg** [comment]
I really should be removed from the maintainer for keyd as I am not using it. I'm not going to work on this.
