### ISSUE TITLE
Alias render-markdown is still in vim-plugins

### ISSUE THREAD

**Issue by pejaab** [NixOS/nixpkgs#344302]
### Describe the bug
Building the [render-markdown](https://github.com/MeanderingProgrammer/render-markdown.nvim/) nvim plugin currently results in an error.

```
error:
     
  … while evaluating the attribute 'value'
       
  at /nix/store/5n0kgjjm07z3gvz912i5gviig1qh4d4w-source/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       … while calling the 'addErrorContext' builtin

         at /nix/store/5n0kgjjm07z3gvz912i5gviig1qh4d4w-source/lib/modules.nix:821:17:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |                 ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Alias render-markdown is still in vim-plugins
```

### Steps To Reproduce
1. `nix --extra-experimental-features "nix-command flakes" build nixpkgs#vimPlugins.render-markdown`

### Expected behavior
`render-markdown` builds

### Additional context
Under [NixOS Search](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.render-markdown&from=0&size=50&sort=relevance&type=packages&query=render-markdown) it's called `render-markdown`, while in [generated.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vim/plugins/generated.nix) it's called `render-markdown-nvim`

### Notify maintainers

 Probably @GaetanLepage attempting to fix with 29a41744f6edef5dd8cc44132861e74134cc3272?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GaetanLepage** [comment]
Yes, the [fix](https://github.com/NixOS/nixpkgs/pull/343557) has been merged and should land in the stable channels soon.
https://nixpkgs-tracker.ocfox.me/?pr=343557

**Comment by pejaab** [comment]
Thanks for confirming that it's fixed! 🙏 I wasn't aware of this tracker.
