### ISSUE TITLE
`systemd --user enable` links to `/nix/store/**` directly rather than to `/etc/systemd/user/*`

### ISSUE THREAD

**Issue by UlyssesZh** [NixOS/nixpkgs#344371]
### Describe the bug
When I run `systemctl --user enable foo.service`, a symlink is created at `~/.config/systemd/user/foo.service` pointing to `/nix/store/*-unit-foo.service/foo.service`. However, if the service is updated with a `nixos-rebuild` command, that `/nix/store` path would be pointing to an old version of the service file. Therefore, a better link target should be `/etc/systemd/user/*`, which is updated after running `nixos-rebuild`.

### Steps To Reproduce
Add the following in `configuration.nix`:

```nix
systemd.user.services.foo = {
  script = "echo 'version 1'";
  wantedBy = [ "default.target" ];
};
```

Then run

```sh
sudo nixos-rebuild switch
systemctl --user enable foo.service
grep version $(grep -oP '(?<=^ExecStart=).*' ~/.config/systemd/user/foo.service)
```

This will output `echo 'version 1'`. Now, change the `echo 'version 1'` in `configuration.nix` to `echo 'version 2'`, and run

```sh
sudo nixos-rebuild switch
grep version $(grep -oP '(?<=^ExecStart=).*' ~/.config/systemd/user/foo.service)
```

This will still output `echo 'version 1'` while the expected result is `echo 'version 2'`. If we run

```sh
grep version $(grep -oP '(?<=^ExecStart=).*' /etc/systemd/user/foo.service)
```

instead, then the result will be `echo 'version 2'`, which is expected.

### Expected behavior
Already explained above.

### Notify maintainers

@flokli @kloenk 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.111, NixOS, 24.05 (Uakari), 24.05.5218.23cbb250f3bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
> ```shell
> systemctl --user enable foo.service
> ```

Why are you running this command? This is imperative and redundant as you've already enabled the service in your declarative config.

While it's not ideal for it to work like this, it should be expected for this to happen as it's imperative config atop of your declarative one.

I don't think that's a use-case that NixOS should cater to.

**Comment by UlyssesZh** [comment]
I see.

Since you said I already enabled the service in the config, then what does `systemd.user.services.foo.enable` do?

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/blob/1925c603f17fc89f4c8f6bf6f631a802ad85d784/nixos/lib/systemd-unit-options.nix#L54-L66

**Comment by UlyssesZh** [comment]
Ah `enable` is true by default, I see. Thank you.
