### ISSUE TITLE
Update request: vimPlugins.cord-nvim 2024-07-19 → 2025-09-25

### ISSUE THREAD

**Issue by Eveeifyeve** [NixOS/nixpkgs#344406]
- Package name: vimPlugins.cord-nvim
- Latest released version:  2025-09-25

- Current version on the unstable channel:2024-07-19
- Current version on the stable/release channel: NONE

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: @redyf 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Eveeifyeve** [comment]
I could look doing a pr that updates the package.

**Comment by redyf** [comment]
No worries :+1: https://github.com/NixOS/nixpkgs/pull/344478

**Comment by Eveeifyeve** [comment]
Nvm all good if you need me to I can try and test it on macos.

**Comment by Eveeifyeve** [comment]
I also suggest doing an update script so the @r-ryantm bot updates based on new commits on the new branch.

**Comment by redyf** [comment]
> Nvm all good if you need me to I can try and test it on aarch64-darwin.

That would be great 🙏

**Comment by Eveeifyeve** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/344478 Merged.
