### ISSUE TITLE
Override version in overlay

### ISSUE THREAD

**Issue by ktf** [NixOS/nixpkgs#34452]
## Issue description

Maybe I've a too naive understanding of nix, however when I try to override the version of a given package using the following overlay:

```nix
self: super:
{
  myZlib = super.zlib.override { version = "v1.2.8"; };
}
```

I get:

```
error: anonymous function at /nix/store/kj7mjqng86c59kaqyx5rzf75i9gdizfk-nixpkgs-17.09pre116788.0adc0668b37/nixpkgs/pkgs/development/libraries/zlib/default.nix:1:1 called with unexpected argument ‘version’, at /nix/store/kj7mjqng86c59kaqyx5rzf75i9gdizfk-nixpkgs-17.09pre116788.0adc0668b37/nixpkgs/lib/customisation.nix:74:12
```

### Steps to reproduce

In `nix-repl`:

```
:l <nixpkgs>
zlib.override { version = "v1.2.8"; }
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixpkgs-17.09pre116788.0adc0668b37"`
 - channels(ktf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by Infinisil** [comment]
Example of what will work:

```nix
self: super:
{
  myZlib = super.zlib.overrideAttrs (old: rec {
    name = "zlib-1.2.8";
    src = fetchurl {
      url = "http://www.zlib.net/fossils/${name}.tar.gz";
      sha256 = "039agw5rqvqny92cpkrfn243x2gd4xn13hs3xi6isk55d2vqqr9n";
    };
  });
}
```

**Comment by ktf** [comment]
thanks!
