### ISSUE TITLE
Package request: Gren

### ISSUE THREAD

**Issue by mags-issues** [NixOS/nixpkgs#344528]
**Project description**

Quoting from [gren-lang.org](https://gren-lang.org):

> Gren is a functional programming language with carefully managed side-effects and a strong static type system.

**Metadata**

* homepage URL: https://gren-lang.org/
* source URL: https://github.com/gren-lang/compiler
* license: [BSD-3-Clause](https://github.com/gren-lang/compiler/blob/main/LICENSE)
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
Seems like, other than the top 2 lines, the License text is exactly the same as the BSD-3-Clause License (bsd3)
Also: https://github.com/gren-lang/compiler/blob/acda43a69583a826d74a12314f67186cc5d3a805/package.json#L28

**Comment by mags-issues** [comment]
Yeah, you're right! Just saw the same in `gren.cabal` now.

**Comment by TomaSajt** [comment]
By the way, I have managed to package it, but haven't had the time to open a PR. I'll probably do it later today.

**Comment by mags-issues** [comment]
Oh, thank you! I just got it running as a flake, but very new to Nix and excited to compare how you did it 🙏

**Comment by TomaSajt** [comment]
I've never packaged a haskell app before this, so this was new for me too.
It seems that letting cabal2nix generate a package is the most used way currently.

**Comment by turion** [comment]
Note that you could also ask upstream to put gren on Hackage. That way it would get packaged and updated semi-automatically, as part of the haskell updates workflow.

**Comment by blaix** [comment]
The latest version of gren is distributed via npm. The latest haskell binary is not meant to be used directly, so if the nix package is updated you'll get a binary that won't work. I have a flake that installs the npm package here: https://github.com/gren-lang/nix/blob/main/flake.nix

I'd like to get gren into the official nix package registry but I'm not sure where to start. Any chance you could point me in the right direction for replacing the auto-generated package in https://github.com/NixOS/nixpkgs/pull/344666 ?

**Comment by TomaSajt** [comment]
After much struggle I have managed to bootstrap the latest `gren` from source by using an older prebuilt gren.
See https://github.com/NixOS/nixpkgs/pull/381895
