### ISSUE TITLE
Package request: Zen-Browser

### ISSUE THREAD

**Issue by Evren-os** [NixOS/nixpkgs#344533]
**Project description**

Zen is a Firefox-based browser focused on performance and customization. It's a new browser that was released a few months ago and gained popularity quickly

**Metadata**

* homepage URL: https://zen-browser.app/
* source URL: https://github.com/zen-browser/desktop
* license:  MPL 2,0
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by honnip** [comment]
Closing as duplicate #327982
