### ISSUE TITLE
Update request: anydesk 6.3.2 → 6.3.3

### ISSUE THREAD

**Issue by tannerlegvold** [NixOS/nixpkgs#344558]
- Package name: anydesk
- Latest released version: 6.3.3

- Current version on the unstable channel: 6.3.2
- Current version on the stable/release channel: 6.3.2

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@cheriimoya 
@shyim 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

-----------------------------------------------------

A brief note:
Currently Anydesk is not working for me on my NixOS system, a few days ago it started crashing when I try to open it. [The same issue is affecting other Linux distros](https://www.reddit.com/r/openSUSE/comments/1fl5j9h/anydesk_does_not_start_since_this_morning_i_did/): openSUSE, Arch, and the Steam Deck. According to the reddit post, the solution is to update to version 6.3.3. Thanks all.

**Comment by iago-costa** [comment]
Same problem for me

**Comment by cheriimoya** [comment]
> Same problem for me

Its already merged, you just need to wait a little bit longer until the new version is available in nixpkgs unstable

**Comment by tannerlegvold** [comment]
If you run this snippet in the terminal
```
NIXPKGS_ALLOW_UNFREE=1 nix run --extra-experimental-features 'flakes nix-command' --impure github:nixos/nixpkgs/ccc4ef55e3a40f3bcd92396a8ba932a13071cfca#anydesk
```
it should download and run AnyDesk 6.3.3. Its what I've been using and will use until the package is in nixpkgs unstable.
