### ISSUE TITLE
leksah doesn't build

### ISSUE THREAD

**Issue by razvan-panda** [NixOS/nixpkgs#34451]
## Issue description

> Linking dist/build/test-tool/test-tool ...
> [105 of 115] Compiling GI.WebKit2.Structs.Credential ( GI/WebKit2/Structs/Credential.hs, dist/build/GI/WebKit2/Structs/Credential.o )
> [106 of 115] Compiling GI.WebKit2.Structs.NavigationAction ( GI/WebKit2/Structs/NavigationAction.hs, dist/build/GI/WebKit2/Structs/NavigationAction.o )
> running tests
> [107 of 115] Compiling GI.WebKit2.Structs.ScriptDialog ( GI/WebKit2/Structs/ScriptDialog.hs, dist/build/GI/WebKit2/Structs/ScriptDialog.o )
> Running 1 test suites...
> Test suite test-tool: RUNNING...
> [108 of 115] Compiling GI.WebKit2.Structs.UserScript ( GI/WebKit2/Structs/UserScript.hs, dist/build/GI/WebKit2/Structs/UserScript.o )
> [109 of 115] Compiling GI.WebKit2.Structs.UserStyleSheet ( GI/WebKit2/Structs/UserStyleSheet.hs, dist/build/GI/WebKit2/Structs/UserStyleSheet.o )
> [110 of 115] Compiling GI.WebKit2.Structs ( GI/WebKit2/Structs.hs, dist/build/GI/WebKit2/Structs.o )
> [111 of 115] Compiling GI.WebKit2.Constants ( GI/WebKit2/Constants.hs, dist/build/GI/WebKit2/Constants.o )
> [112 of 115] Compiling GI.WebKit2.Callbacks ( GI/WebKit2/Callbacks.hs, dist/build/GI/WebKit2/Callbacks.o )
> [113 of 115] Compiling GI.WebKit2.Objects.WebContext ( GI/WebKit2/Objects/WebContext.hs, dist/build/GI/WebKit2/Objects/WebContext.o )
> [114 of 115] Compiling GI.WebKit2.Objects ( GI/WebKit2/Objects.hs, dist/build/GI/WebKit2/Objects.o )
> ### Failure in src/IDE/Utils/CabalPlan.hs:37: expression `:{
>   eitherDecodeStrict' (BS.pack
>     "{\
>     \   \"cabal-lib-version\" : \"1.24.0.0\",\
>     \   \"cabal-version\" : \"1.24.0.0\",\
>     \   \"install-plan\" : [\
>     \      {\
>     \         \"type\" : \"pre-existing\",\
>     \         \"components\" : {\
>     \            \"lib\" : {\
>     \               \"depends\" : [\
>     \                  \"array-0.5.1.1\",\
>     \                  \"base-4.9.0.0\"\
>     \               ]\
>     \            }\
>     \         },\
>     \         \"id\" : \"Cabal-1.24.0.0\"\
>     \      },\
>     \      {\
>     \         \"id\" : \"QuickCheck-2.9.1-ec9a1c39266d75ed2c3314f6e846a8f11853eff43fc45db79c7256d9bfd94602\",\
>     \         \"components\" : {\
>     \            \"lib\" : {\
>     \               \"depends\" : [\
>     \                  \"base-4.9.0.0\",\
>     \                  \"containers-0.5.7.1\",\
>     \                  \"random-1.1-fe6ccf72ebd63a2d68570bb45b42bd08df5570c6151cb9af54907d40ef9af454\"\
>     \               ]\
>     \            }\
>     \         },\
>     \         \"flags\" : {\
>     \            \"templatehaskell\" : true\
>     \         },\
>     \         \"type\" : \"configured\"\
>     \      }\
>     \   ]\
>     \}") :: Either String PlanJson
> :}'
> expected: Right (PlanJson {pjPlan = [PlanItem {piId = "Cabal-1.24.0.0", piType = "pre-existing", piComps = [(ComponentLib,fromList ["array-0.5.1.1","base-4.9.0.0"])]},PlanItem {piId = "QuickCheck-2.9.1-ec9a1c39266d75ed2c3314f6e846a8f11853eff43fc45db79c7256d9bfd94602", piType = "configured", piComps = [(ComponentLib,fromList ["base-4.9.0.0","containers-0.5.7.1","random-1.1-fe6ccf72ebd63a2d68570bb45b42bd08df5570c6151cb9af54907d40ef9af454"])]}]})
>  but got: Right (PlanJson {pjPlan = [PlanItem {piId = "Cabal-1.24.0.0", piType = "pre-existing", piComps = [(ComponentLib,fromList ["array-0.5.1.1","base-4.9.0.0"])]},PlanItem {piId = "QuickCheck-2.9.1-ec9a1c39266d75ed2c3314f6e846a8f11853eff43fc45db79c7256d9bfd94602", piType = "configured", piComps = [(ComponentLib,fromList ["base-4.9.0.0","containers-0.5.7.1","random-1.1-fe6ccf72ebd63a2d68570bb45b42bd08df5570c6151cb9af54907d40ef9af454"])]}], pjCabalVersion = "1.24.0.0", pjCabalLibVersion = "1.24.0.0", pjCompilerId = Nothing, pjOS = Nothing, pjArch = Nothing})
> Examples: 6  Tried: 6  Errors: 0  Failures: 1
> Test suite test-tool: FAIL
> Test suite logged to: dist/test/leksah-server-0.16.2.0-test-tool.log
> 0 of 1 test suites (0 of 1 test cases) passed.
> builder for ‘/nix/store/lpa8cj1j345imvsjyvwvyqq771m9gcqf-leksah-server-0.16.2.0.drv’ failed with exit code 1
> cannot build derivation ‘/nix/store/savffw378x3glalpdg4p1jbxy79v35hj-ghc-8.0.2-with-packages.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/z09iwcp48r1dx0kqgh3hw0wy8pgs7w5w-leksah.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/3cp4wrxsy1b6majfd1zzjjvcvmxqpydb-system-path.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/cp3n9b2sig96x7vb1mb2k8mli7dyk405-nixos-system-nixos-17.09.2875.c2b668ee726.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/cp3n9b2sig96x7vb1mb2k8mli7dyk405-nixos-system-nixos-17.09.2875.c2b668ee726.drv’ failed

## Technical details

>  - system: `"x86_64-linux"`
>  - host os: `Linux 4.9.78, NixOS, 17.09.2875.c2b668ee726 (Hummingbird)`
>  - multi-user?: `yes`
>  - sandbox: `no`
>  - version: `nix-env (Nix) 1.11.16`
>  - channels(root): `"nixpkgs-unstable-18.03pre126020.931a0b8be80, nixos-17.09.2875.c2b668ee726, nixos-unstable-18.03pre118631.66b63d2f5a"`
>  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by puffnfresh** [comment]
The Leksah team has a Nix build here:

https://github.com/leksah/leksah#getting-leksah

**Comment by peti** [comment]
Closing in favor of https://github.com/NixOS/nixpkgs/issues/28931.
