### ISSUE TITLE
Package request: wgpu

### ISSUE THREAD

**Issue by sbancuz** [NixOS/nixpkgs#344689]
**Project description**

Rust implementation of the WebGPU standard, right now there is only a wgpu-utils that doesn't provide any header. This would provide headers to use for any other application.

Note: There is also another implementation (google dawn) of the standard with an open package request issue.

**Metadata**

* homepage URL:https://wgpu.rs/ , https://crates.io/crates/wgpu
* source URL:https://github.com/gfx-rs/wgpu
* license: mit + apache 2
* platforms: request for linux, but it should work for any other OS

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sbancuz** [comment]
Thanks!!!

**Comment by emilazy** [comment]
Reopening per https://github.com/NixOS/nixpkgs/pull/345248#issuecomment-2398728743.
