### ISSUE TITLE
Build failure: sby

### ISSUE THREAD

**Issue by g5pw** [NixOS/nixpkgs#344647]
### Steps To Reproduce

1. build *sby*

### Build log

[log](https://pastebin.com/Q1WWFKMZ)

### Additional context

Failure while trying to build `glasgow`.

### Notify maintainers

@thoughtpolice @rcoeurjoly

### Metadata

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/vyv637pn8fx0gs28pfqy5b3jkrmd7cvl-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ofalvai** [comment]
Looks like this is fixed, I can no longer reproduce the failure on aarch64-darwin on `master`

**Comment by g5pw** [comment]
Yep, looks fixed now, thanks!
