### ISSUE TITLE
boost-dev references bleed into boost binaries via header macros

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#34462]
## Issue description
When compiling a binary using boost, compilation embeds a path to boost-dev header files in the binary. I think that this is due to the use of `__FILE__` macros in code embedded in the header files directly. The result is a needless reference to the boost-dev output. This can increase closure size considerable, which is a problem with initrds.

I think that the `#line` pragma on the top of the boost header files should be mutated in the boost-dev output to something that the scanner doesn't recognize as a reference, for instance,
```
#line 1 "/nix/store/fl2bqzgij4ky6g84q2zfz40ypai4993c-boost-1.66_0-dev/include/boost/exception/detail/exception_ptr.hpp"
```
could be mutated to one of the following
```
#line 1 "/NIX/STORE/fl2bqzgij4ky6g84q2zfz40ypai4993c-boost-1.66_0-dev/include/boost/exception/detail/exception_ptr.hpp"
#line 1 "boost/include/boost/exception/detail/exception_ptr.hpp"
```

### Steps to reproduce
```
nix-build -A thin-provisioning-tools
nix-query -q --references result/
strings result/bin/pdata_tools | grep /nix/store
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.15, NixOS, 18.03.git.753efe6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/nixpkgs`

**Comment by edolstra** [comment]
This is caused by 76b590405a3e, which caused all headers files to have an absolute rather than relative path in `#line`.
