### ISSUE TITLE
Machine does not finish shutdown using `shutdown`

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#34476]
## Issue description
Shutting down my machine with `sudo shutown` or `sudo reboot` does not work - it hangs at "Reached target shutdown".

However, `systemctl poweroff` and `systemctl reboot` *do* work, somewhat surprisingly.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.77, NixOS, 18.03pre126246.a4f433c03cc (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre126246.a4f433c03cc"`
 - channels(michael): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Infinisil** [comment]
Does it hang indefinitely? Because I've had some occasions of it taking quiet a while (a couple minutes)

**Comment by michaelpj** [comment]
I confess that I haven't waited more than about a minute or two before giving up, so I'm not sure.

**Comment by rnhmjoj** [comment]
Maybe a service is taking too long to stop? systemd as a default timeout of 90s before it forces it to exit.
Do you see something like "A stop job is running..."?

**Comment by peterhoeg** [comment]
As mentioned in #35902 have you tried with ```services.acpid.enable = true;``` ?

**Comment by peterhoeg** [comment]
Assuming this is no longer an issue. Please reopen if that is not the case.
