### ISSUE TITLE
Hyprland from nixpkgs-unstable on 24.05

### ISSUE THREAD

**Issue by gesker** [NixOS/nixpkgs#344759]
### Describe the bug

Seeing identical behavior to this issue reported by [@Vetoes ](https://github.com/Vetoes) over in the main Hyprland repository on https://github.com/hyprwm/Hyprland/issues/7773

However, the library indicated at the very beginning of the [core dump](https://github.com/user-attachments/files/16994652/coredump_2723.txt), [aquamarine package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/aq/aquamarine/package.nix), does seem to be in included in the  [build/package.nix ](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/hy/hyprland/package.nix)file for Hyprland 43.0 here in the nixos-unstable branch.

1. Follow steps outlined in https://github.com/hyprwm/Hyprland/issues/7773

### Expected behavior

Bump version for Hyprland from 42.1 to 43.0 by referencing the nixos-unstable (`inputs.nixpkgs.follows`) in the flake and indicating prefixing `pkgs-unstable` to the package in the `programs.hyprland.package` attribute without issue.

### Screenshots

Core dump reported by @Vetoes is identical to the error received earlier today.

### Additional context

Same core dump if attempting to upgrade hyprland either via `nixos programs.hyprland` atrributes and/or via the `wayland.windowManager.hyprland` attributes made available by home-manager.

There does not appear to be an equivalent of the `aquamarine` in the [stable branch](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=aquamarine) search website as of the time of opening this issue. Adding the `aquamarine` package from nixos-unstable  to `home.packages = []` list did not appear to resolve the issue when attempting to bump the Hyprland version via home-manager.

### Notify maintainers

Mentioning @vaxry as appears active in this section of the nixpkgs repository. Also, just taking this as an opportunity to express gratitude for the Hyprland project. It is a significant value add and the efforts of those working on that project are very much appreciated. Thank you!

### Metadata
 `nix-shell -p nix-info --run "nix-info -m"` from PC/notebook is:

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.20240926.8f7b5c9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/2b208dddqm6p3dmjprmfb651rn1rj8ap-source`
```

relatively confident that gpu config is (mostly) correct as have been using Hyprland 42.1 for a number of months. Still, a copy of the gpu config pasted in below just in case it could be useful for this item. Some of the packages in my gpu.nix config may be superfluous from experimenting with that config file earlier this year but so far haven't gotten in the way.

```{ config, pkgs, ... }:

let
  optGpu-intel-bus-id = "PCI:1:0:0";
  optGpu-nvidia-bus-id = "PCI:0:2:0";
in
{
  nixpkgs.config.packageOverrides = pkgs: {
    intel-vaapi-driver = pkgs.intel-vaapi-driver.override { enableHybridCodec = true; };
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };
  environment.systemPackages = with pkgs; [
    nvidia-docker
    nvidia-system-monitor-qt
    nvidia-vaapi-driver
    nvtopPackages.full
    egl-wayland
    intel-media-driver # LIBVA_DRIVER_NAME=iHD
    intel-vaapi-driver # LIBVA_DRIVER_NAME=i965
    libGL
    libglvnd
    libva-utils
    libvdpau-va-gl
    mesa
    vaapiIntel
    vaapiVdpau
    vdpauinfo
    vulkan-tools
    vulkan-validation-layers
    wgpu-utils
  ];

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  boot = {
    extraModulePackages = [
      config.boot.kernelPackages.nvidia_x11 # Match nvidia driver package below
    ];
    blacklistedKernelModules = [
      "skx_edac" # Nvidia EDAC memory - error on this machine
    ];
    kernelModules = [ "nvidia" ];
    kernelParams = [
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
      "nvidia-drm.fbdev=1"
      "nvidia-drm.modeset=1"
    ];
    initrd.availableKernelModules = [
      "nvidia_modeset"
      "nvidia_uvm"
      "nvidia_drm"
    ];
  };

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    open = false;
    package = config.boot.kernelPackages.nvidia_x11;
    modesetting.enable = true; # Needed for DKMS
    nvidiaSettings = true; # Nvidia Settings GUI
    forceFullCompositionPipeline = false;
    nvidiaPersistenced = false;
    powerManagement.enable = true;
    powerManagement.finegrained = false;
    datacenter.enable = false; # default value is 'false'
    dynamicBoost.enable = false; # default value is 'false'
    prime = {
      sync.enable = false;
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      intelBusId = "${optGpu-intel-bus-id}";
      nvidiaBusId = "${optGpu-nvidia-bus-id}";
    };
  };
}
```

**Comment by Artturin** [comment]
Tag the package maintainers

**Comment by fufexan** [comment]
See https://github.com/hyprwm/aquamarine/issues/73#issuecomment-2351761132.

**Comment by Vetoes** [comment]
@fufexan 
unfortunately thats not work for me..

**Comment by fufexan** [comment]
That's vague. Do you get the same error, or a different one?

**Comment by Atemu** [comment]
Mixing channels is not supported by Nixpkgs, especially not for graphical applications. While it can work for leaf packages that do not have any hardware dependencies such as a GPU, it will almost certainly not work for system components such as a wayland compositor.

If you want the latest and greatest as soon as it becomes available, use nixos-unstable rather than NixOS stable. We will not be porting a newer version of libinput to 24.05 and it doesn't really make sense to port aquamarine either though that would at least be possible. 

In theory, you could port the newer libinput and aquamarine expressions yourself but that's a lot more effort than simply using nixos-unstable.

**Comment by Vetoes** [comment]
> That's vague. Do you get the same error, or a different one?

libinput dependency error.. coundnt fix it 
my flake
<details>
  <summary>flake.nix</summary>

```
{
  description = "A simple NixOS flake";

  inputs = {
# NixOS official package source, using the nixos-23.11 branch here
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";

    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    aquamarine = {
      type = "git";
      url = "https://github.com/hyprwm/aquamarine";
      ref = "refs/tags/v0.4.1";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/hyprland";
      ref = "refs/tags/v0.43.0";
      submodules = true;
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.aquamarine.follows = "aquamarine";
    };
  };

  outputs = { self, nixpkgs,nixpkgs-unstable,home-manager,stylix,...}@inputs:
   
    overlays = import ./overlays {inherit inputs outputs;};

    nixosConfigurations = {
      scv = nixpkgs.lib.nixosSystem {

      specialArgs={inherit  outputs inputs system ;};
 }
```
</details>

<details>
<summary>overlays</summary>

```
# This file defines overlays
{inputs, ...}: let
  addPatches = pkg: patches:
    pkg.overrideAttrs (oldAttrs: {
      patches = (oldAttrs.patches or []) ++ patches;
    });
in {
  # This one brings our custom packages from the 'pkgs' directory
  additions = final: _prev: import ../pkgs {pkgs = final;};

  # This one contains whatever you want to overlay
  # You can change versions, add patches, set compilation flags, anything really.
  # https://nixos.wiki/wiki/Overlays
  modifications = final: prev: {
    hyprland-patched = let
      libinput = prev.libinput.overrideAttrs (self: {
        name = "libinput";
        version = "1.26.0";
        src = final.fetchFromGitLab {
          domain = "gitlab.freedesktop.org";
          owner = "libinput";
          repo = "libinput";
          rev = self.version;
          hash = "sha256-mlxw4OUjaAdgRLFfPKMZDMOWosW9yKAkzDccwuLGCwQ=";
        };
      });
    in
      inputs.hyprland.packages.${prev.system}.hyprland.override {
        libinput = libinput;
        aquamarine = inputs.hyprland.inputs.aquamarine.packages.${prev.system}.aquamarine.override {
          libinput = libinput;
        };
        wayland-scanner = final.unstable.wayland-scanner;
      };
  };

  # When applied, the unstable nixpkgs set (declared in the flake inputs) will
  # be accessible through 'pkgs.unstable'
  unstable-packages = final: _prev: {
    unstable = import inputs.nixpkgs-unstable {
      inherit (final) system;
      config.allowUnfree = true;
    };
  };
}
```
</details>

<details>
<summary>configurations.nix </summary>

```
programs = {
	hyprland = {
		enable = true;
      package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
      portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;

		};
}

  nixpkgs = { 

    overlays =  [
      outputs.overlays.additions
      outputs.overlays.modifications
      outputs.overlays.unstable-packages
    ];

  config.allowUnfree = true;
  config.pulseaudio = true;

  };
```

</details>

<details>
<summary>error message</summary>


```
┏━ 1 Errors:
┃ error: builder for '/nix/store/xk1mjzkx3d6sqnjp2abpqig3h5rhnyv4-aquamarine-0.4.1+date=2024-09-07_e4a…
┃        last 10 log lines:
┃        >   The following required packages were not found:
┃        >
┃        >    - libinput>=1.26.0
┃        >
┃        > Call Stack (most recent call first):
┃        >   /nix/store/b893ksdqbdpzrdcmms59aq4fgqmh083w-cmake-3.29.2/share/cmake-3.29/Modules/FindPkg…
┃        >   CMakeLists.txt:24 (pkg_check_modules)
┃        >
┃        >
┃        > -- Configuring incomplete, errors occurred!
┃        For full logs, run 'nix log /nix/store/xk1mjzkx3d6sqnjp2abpqig3h5rhnyv4-aquamarine-0.4.1+date…
┣━ Dependency Graph:
┃    ┌─ ⏸ system-shutdown waiting for 1 ⚠ 1 ⏵
```
</details>

when i just use nixpkgs-unstable with hyprland

dependency error not occur but other error occur.. 

i just using v0.41.2 it works fine
