### ISSUE TITLE
Rewriting mk/build.mk in GHC HEAD derivation breaks developer workflow

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#34485]
## Issue description

I have a `shell.nix` file which inherits the build logic from the HEAD derivation along with additional development dependencies which I use to work on GHC. The motivation for doing this is so that all
the configure flags are set correctly and in one place rather than having to duplicate the logic locally. 

Some recent changes by @Ericson2314 broke this workflow as now running `configurePhase` overwrites my local `mk/build.mk`. I don't think the script should modify this file at all and instead directly set the necessary vars when running the commands which need them.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Ericson2314** [comment]
Oh it didn't occur to me to do everything in env vars. That's fine with me, just be consistent with all the GHC derivations.

**Comment by mpickering** [comment]
Recommended way now is to use https://github.com/alpmestan/ghc.nix
