### ISSUE TITLE
tailscaled: missing runtime dependency `su`

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#344803]
### Problem
https://github.com/NixOS/nixpkgs/blob/30439d93eb8b19861ccbe3e581abf97bdc91b093/pkgs/by-name/ta/tailscalesd/package.nix

The newer `tailscale drive` command has a dependency on `su` as can be observed with `journalctl -u tailscaled`:
```cmd
  Sep 27 06:36:47 elitebook tailscaled[1328]: can't find su command: exec: "su": executable file not found in $PATH
  Sep 27 06:36:47 elitebook tailscaled[1328]: user server /nix/store/gq0q640pl49hla6l00ny0r3fif5bj3x3-tailscale-1.74.0/bin/.tailscaled-wrapped stopped with error "System administrator" is root, will try again in 16ms
```

In tailscale the relevant code is at https://github.com/tailscale/tailscale/blob/cab2e6ea677865f50e3ccfb526603d9f36c9dce8/drive/driveimpl/remote_impl.go#L418

An issue of another NixOS user on tailscale might get solved by this too: https://github.com/tailscale/tailscale/issues/13285

I would make a PR, but I believe that `su` is a bit special and requires extra care, so I'd like to get a second opinion first.

### Maintainer
@SuperSandro2000

**Comment by Frontear** [comment]
That IS a special problem. Afaik `pkgs.shadow` provides `bin/su`, though it will not have it with the `setuid` bit. On NixOS this is usually handled by `security.wrappers`, and on other distros this is usually baked into their package. This poses a problem since we'd need a reference to `su` from outside of the `/nix/store` context..

**Comment by Mikilio** [comment]
Yeah, so I was thinking of maybe solving this in the module instead. There we could use the wrapper...

**Comment by SuperSandro2000** [comment]
The su binaries with setuid bit lives in NixOS at ``/run/wrappers/bin/su``.

So we probably want to add that path to the PATh variable.

**Comment by Frontear** [comment]
> Yeah, so I was thinking of maybe solving this in the module instead. There we could use the wrapper...
> 
> I would just add it to the PATH of the systemd service.

Correct yeah. I don't think anything can or should be done about using this package on a non-nixos distro for now. It should resolve the PATH fine anyways as long as its FHS compliant
