### ISSUE TITLE
Update request: go 1.22 → 1.23

### ISSUE THREAD

**Issue by MarkusZoppelt** [NixOS/nixpkgs#344827]
- Package name: go
- Latest released version: go 1.23.1

- Current version on the unstable channel: 1.22.7
- Current version on the stable/release channel: 1.22.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@kalbasit @Mic92 @zowoq @qbit @mfrw 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by MarkusZoppelt** [comment]
> I think go 123 is already in nixpkgs but not the default.

How does the default change? Happy to open a PR when you point me to the right file.

**Comment by zowoq** [comment]
Was done in https://github.com/NixOS/nixpkgs/pull/342429.

https://nixpk.gs/pr-tracker.html?pr=342429
