### ISSUE TITLE
Update request: piper 0.7 → 0.8

### ISSUE THREAD

**Issue by e-tho** [NixOS/nixpkgs#344887]
- Package name: piper
- Latest released version: 0.8

- Current version on the unstable channel: 0.7
- Current version on the stable/release channel: 0.7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mvnetbiz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by myclevorname** [comment]
I will tackle this issue, but `nixpkgs-review` is currently running.
