### ISSUE TITLE
Package request: ollama-python

### ISSUE THREAD

**Issue by DADA30000** [NixOS/nixpkgs#344899]
**Project description**

Python library for interacting with ollama (package it please :) )

**Metadata**

* homepage URL: https://github.com/ollama/ollama-python
* source URL: https://github.com/ollama/ollama-python
* license: MIT
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by theobori** [comment]
It already exists.

See https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/ollama/default.nix.

**Comment by DADA30000** [comment]
> It already exists.
> 
> See https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/ollama/default.nix.

oh thanks!
