### ISSUE TITLE
Lyx does not have any kind of document available.

### ISSUE THREAD

**Issue by kakuzade** [NixOS/nixpkgs#34498]
## Issue description

I am referring to document classes in Document / settings. Not even the standard article.

### Steps to reproduce

I installed lyx from the unstable channel of NixOS, in my user profile: `$ nix-env -iA nixos.lyx`. Then I installed `texlive.combined.scheme-full`; I thought that it solved the lyx problem, but it was not like that.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2875.c2b668ee726 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(miguel): `"nixos-unstable-18.03pre126709.71631a922b4"`
 - channels(root): `"nixos-17.09.2875.c2b668ee726"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by vcunat** [comment]
I believe you forgot _Tools / Reconfigure_ after installing TeX.

**Comment by kakuzade** [comment]
Thanks! In ArchLinux this step is not necessary.

**Comment by vcunat** [comment]
I suspect it wouldn't be necessary if you installed TeX before the first run of LyX.
