### ISSUE TITLE
[24.05] nixos/regreet: Unclear NixOS rebuild failure wiith `regreetd` package.

### ISSUE THREAD

**Issue by shymega** [NixOS/nixpkgs#344915]
### Describe the bug

I updated my Flake lockfile for 24.05, and started having this error:

```shell
error: The option `programs.regreet.cursorTheme' does not exist. Definition values:
       - In `/nix/store/k5zm4zdrgbn0483a4pxgz1pb49a266hm-modules/regreet/nixos.nix':
           {
             _type = "if";
             condition = false;
             content = {
               name = "Vanilla-DMZ";
           ...
```

I've disabled `greetd` and switched back to GDM, but no joy. I can't get any other context, even with `--show-trace`. Due to restrictions, I am unable to release the source code to my NixOS flake.

I'm not actually sure what commit caused this regression, but when I did have `greetd` enabled, I used `gtkgreet`.

### Steps To Reproduce

Unable to provide sources at this time.

### Expected behavior

The NixOS configuration is to build correctly.

### Screenshots

Logs provided above.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.48-xanmod1, NixOS, 24.05 (Uakari), 24.05.20240925.759537f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by shymega** [comment]
Apologies for not being able to provide configuration. I can try to extract sources if requested.

**Comment by Atemu** [comment]
It'd be best if you did that. Give us the minimal config that makes the error appear.

**Comment by shymega** [comment]
It's a very complex config. Even a minimal config would take a while to create.

However, I've rolled back the Nixpkgs inputs, and I've got a known working Flake on [this](https://github.com/NixOS/nixpkgs/commit/23cbb250f3bf4f516a2d0bf03c51a30900848075) 24.05 commit. There's no issues building on that commit. All of my configs use 24.05 as a base, and `greetd` is enabled in conjunction with the linked SHA-1.

**Comment by shymega** [comment]
Yep, will do as soon as I'm back at my workstation. Thank you, apologies for any confusion with my tests.

**Comment by Atemu** [comment]
You're going to have to figure out which part of your config sets the option anyways btw.

**Comment by Atemu** [comment]
I just noticed that the option set here does not exist on 24.05 yet. It's obviously going to fail if you try to set it. (Note that the module system intentionally checks for options definitions even if you "disable" them via `mkIf`.)

This looks like an error in your config to me.

**Comment by shymega** [comment]
Right, but I don't have any settings relating to `regreetd`. That's what is puzzling. Attached is my greetd config:

Can we re-open this?

[default.nix.txt](https://github.com/user-attachments/files/17169278/default.nix.txt)

**Comment by Atemu** [comment]
I am not able to repro this issue by including that config into mine (modulo duplicate settings).

Please cut your config down to the *minimum* config that actually reproduces the issue. In that process you're likely going to find an error in your config.

I'd start by grepping your config for `cursorTheme`. If it's any more than 0 results, there's your issue.

I closed this issue because the issue you're seeing could not possibly be caused by NixOS 24.05 because the option simply does not exist in that version. Attempting to use a non-existant option is user error no matter how you look at it.

**Comment by aswan89** [comment]
@shymega If you are using stylix it looks like your problem is being caused by the interaction of nixpkgs updates and stylix's inclusion of said updates: https://github.com/danth/stylix/issues/577

**Comment by shymega** [comment]
Sorry for my silence. I was preparing a [repo](https://github.com/shymega/nixos-flake-regreetd-example) which has two branches for working out where the issue is - but, I would _never_ have guessed it was Stylix.

It does appear to build now, thank you for the heads-up @aswan89! I think there's a lesson to be learned on my side here - cut down on dependencies.

I think we can close this as *Resolved*, given we've found a fix.

**Comment by Atemu** [comment]
This never was a nixpkgs issue to begin with.

**Comment by shymega** [comment]
Fair enough. Apologies.
