### ISSUE TITLE
zoom-us-6.2.0.1855 fails to display "Schedule" window and sidebar stuck "Loading sidebar"

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#344931]
### Describe the bug
Zoom 6.2.0 includes a UI redesign. After login clicking the "Schedule" icon in the main window should display a dialog but none is visible. Instead a window seems to appear and immediately disappear (possibly crashing). No error is shown or printed to the console. The sidebar panel also seems to be stuck in "loading" mode and spin endlessly.

### Steps To Reproduce
1. Start Zoom
2. Login
3. In the main window notice the "Loading sidebar" message that spins endlessly
4. Click the "Schedule" icon
5. A window to schedule a new meeting should appear but none is visible

### Expected behavior
In the case of the sidebar, some information should be shown or at best the spinner should stop.
The "Schedule" icon should open a new window but none is shown.

### Screenshots
![screenshot_2024-09-27_20-32-54_210376969](https://github.com/user-attachments/assets/377eeb42-b287-4a4f-b252-68d1e8f25f89)

### Additional context
Version 6.2.0 seems to include a new set of binaries. There is now a `ZoomWebviewHost` file in `/opt/zoom`.
This file has the following missing dependencies:
```
(...)
	libcef.so => not found
	libffmpeg.so => not found
(...)
	libQt5Gui.so.5 => not found
	libQt5Core.so.5 => not found
```

of which `libcef.so` is bundled in `/opt/zoom/cef`
Qt is also bundled under `/opt/zoom/Qt/lib/`.

and wasn't patched for NixOS:

```
Could not start dynamically linked executable: ./ZoomWebviewHost
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

I wasn't able to test this but it's possible that this component is required for the above functionality.

### Notify maintainers

@danbst @tadfisher 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.7, NixOS, 24.05 (Uakari), 24.05.git.5c0e82d553a9M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/var/nixpkgs-channels/nixos`
```
But I'm using the latest [zoom-us 6.2.0.1855](https://github.com/NixOS/nixpkgs/commit/9b25ef61b50af7c6873a3f05960d15b5c6e5e9af) recipe from unstable because the stable version of Zoom requested to be updated today.
I also tried installing the latest Zoom version (6.2.2.2028) but the symptoms are identical to 6.2.0.1855.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nvmd** [comment]
Hi @unode!

It's not clear from your issue description, which Zoom version worked for you before, regarding "Schedule" and sidebar? And also out of curiosity, did the screen share work if you're on Wayland?
For me none of the versions newer than 6.0.2.4680 (6.1.something) actually worked.

I guess the naming suggests that `ZoomWebviewHost` binary and the sidebar _should_ somehow be related, but, unfortunately, its successful or failed startup doesn't seem to directly affect the issue with "Schedule" and the sidebar.

I've managed to fix the errors visible in the log file using the latest version 6.2.3.2056 – "Schedule" window still doesn't open and the sidebar doesn't load.

Flathub's version 6.2.2.2028 also has the same problem.

**Comment by unode** [comment]
Hi @nvdm,

6.0.2.4680 works for me. Both the schedule window and the sidebar load normally.

6.2.0.1855 and 6.2.2.2028 have the issue described above. 

The only issue I have with 6.0.2 (has been there for quite some versions and I learned to work around it) is that the schedule dialog does allow selecting time and dates until a time zone is selected. So I used to always start with the time zone and then everything worked as expected.

I wondered if Zoom expects some locale env setting or some other library to identify what is the system timezone, but never got around to solve it. The workaround was annoying but not terribly so.

I'm not on Wayland.

**Comment by dschrempf** [comment]
I can confirm the sidebar issue.

I also can not share my screen anymore since the last update (I have version 6.2.0 (1855) now). Screen sharing starts to work, but then Zoom does something weird and all goes black.

**Comment by unode** [comment]
I can't replicate the screen sharing issue with `6.2.2 (2028)` but I have:

```
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      jack.enable = true;
      extraConfig.pipewire = {
        "01-properties" = {
          "context.properties" = {
            "link.max-buffers" = 16;  # version < 3 clients can't handle more than this
            "log.level"        = 2;   # https://docs.pipewire.org/page_daemon.html
            "module.x11.bell"  = false;
          };
        };
      };
    };
```
in my system config.

Thanks for PR link.

**Comment by unode** [comment]
After trying out #344377 I confirm that that fix solves both the loading sidebar and the schedule window issues.

**Comment by unode** [comment]
A fix was merged to master so closing.

**Comment by kendal-pioneer** [comment]
I'm still seeing this on current AppImage and Edge snap
