### ISSUE TITLE
rustup package that just packages rustup

### ISSUE THREAD

**Issue by stevenroose** [NixOS/nixpkgs#344976]
The `rustup` package (maintainer @Mic92) also packages cargo, rustc and a whole bunch of other rust tools. There doesn't seem to be a way to install rustup alongside nixpkgs's own cargo and rustc..

I don't like the patched cargo version that rustup provides, that will read into rust-toolchain.toml files and unsollicitedly install toolchains etc. I want to use nixpkgs's cargo, but I want to have rustup available to easily build certain projects with other toolchain version manually, like `rustup run 1.29.0 cargo build` for example. This doesn't seem possible with the current `rustup` package provided.

Using home-manager, I can do something like this to overcome this, but it's an annoying workaround:
```
	home.shellAliases = {
		rustup = "${pkgs.rustup}/bin/rustup";
	};
```

**Comment by Mic92** [comment]
You can put the following into `environment.systemPackages` or home-manager:


```
(pkgs.runCommand "rustup" {} ''
  mkdir $out/bin
  ln -s ${lib.getBin rustup}/bin/rustup $out/bin/rustup
'')
```

**Comment by Mic92** [comment]
Usually I also would not recommend installing devtools globally. You very often need also tools like c-compiler and linkers. It's better to load these in a nix-shell as they also need other environments to be set.
