### ISSUE TITLE
Xorg using software rendering with nvidia drivers in NixOS unstable.

### ISSUE THREAD

**Issue by TheMuso** [NixOS/nixpkgs#345017]
### Describe the bug
When updating to nixos-unstable commit 1925c603 and rebooting, my GNOME desktop using Xorg was not rendering as I previously remembered it. For example, switching workspaces didn't show the sliding animation that one would expect to see, rather the workspace changed as if there was no animation at all.

The xorg.xdriinfo utility reports that swrast was being used for direct rendering. Yes, I am ware the NVIDIA drivers do not use DRI, and xorg.xdriinfo normally reports as such when the NVIDIA drivers are fully functioning.  

### Steps To Reproduce
1. With recent NVIDIA hardware present in your system, Update to 1925c603, making sure your configuration installs and uses the nvidia-x11 driver as per the Nix OS wiki.
2. Try to use an application that uses OpenGL for rendering. a 3D rendered desktop like GNOME or KDE should be sufficient.
3. Start a nix shell with "nix-shell -p xorg.xdriinfo", and run xdriinfo to see that software rasterization is being used. 

### Expected behavior
OpenGL applications render correctly.

### Additional context
After looking through the nixos-unstable branch commit history, I found commit 6663591. I created a local branch, reverted that commit, and updated my flake to use the newly created branch. After a reboot, GNOME behaves correctly, and xdriinfo reports no direct rendering support, as it should.  

### Notify maintainers
@kiskae @edwtjo

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[themuso@barton:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20240928.8d1ec5c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `""`
 - nixpkgs: `/nix/store/13lzd03yc1jdgv47nygm3sq1spvp3xyl-source`
```

**Comment by TheMuso** [comment]
I should probably add that I have the same problem both on production and latest driver versions.

**Comment by 3rd** [comment]
Same for me, `nvidia-smi` shows only an xorg-server process that doesn't use any resources.

**Comment by Herschenglime** [comment]
Hello @TheMuso, would you be able to link the commit that you reverted or share the commands that you used so that people with this issue can use up-to-date packages without the issue for the time being?

Thanks for your help!

**Comment by TheMuso** [comment]
The commit I reverted is https://github.com/nixos/nixpkgs/commit/6663591207ae050bfa8421923b981369be4cad48.

In order to prepare a branch with the reverted commit, this is what I did.

1. Make sure you have a local clone of nixpkgs.
2. Check out the nixos-unstable branch under a different local name to be used in your flake. "git checkout -b nixos-unstable-nvidia-revert origin/nixos-unstable"
3. Revert the above commit. "git revert 6663591207ae050bfa8421923b981369be4cad48".
4. Edit your flake.nix to point to the local copy of nixpkgs. "nixpkgs.url = "git+file:///home/themuso/git/nixos/nixpkgs";"
5. Update flake.lock. "nix flake lock --update-input nixpkgs"
6. Rebuild your flake.

**Comment by Kiskae** [comment]
Looking at the diff that @K900 created before it was merged, I suspect the root problem is this:

```patch
- │  ├─ libglxserver_nvidia.so.1 → libglxserver_nvidia.so.560.35.03
- │  ├─ libglxserver_nvidia.so → libglxserver_nvidia.so.560.35.03
```

The nvidia installer manifest includes that last symlink:
> libglxserver_nvidia.so 0000 GLX_MODULE_SYMLINK extensions/ libglxserver_nvidia.so.560.28.03 MODULE:opengl

So presumably the nvidia xorg driver cannot load the `libglxserver_nvidia` extension, thus breaking libGLX support and causing the problem you're seeing.

**Comment by K900** [comment]
Hmm, I thought I added unversioned symlinks for all dylibs.

**Comment by K900** [comment]
Oh, I guess it doesn't have a soname. Wow, this is messed up.

**Comment by thegleich** [comment]
Same for me, additionally blue and red colors channels in `google-chrome` are switched for me

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/345316

**Comment by xokdvium** [comment]
> Please test https://github.com/NixOS/nixpkgs/pull/345316

This fix works for me

**Comment by thegleich** [comment]
> Please test #345316

Works for me too. Also the colors are normal once again. Thanks!

**Comment by TheMuso** [comment]
The fix works for me too. Thanks.
