### ISSUE TITLE
Adw-gtk3 window title bar look transparrent in Electron-based apps

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#345084]
### Describe the bug
In latest version of Adw-gtk3, window title bar on Electron-based app be weird transparent

### Steps To Reproduce
1. Update Adw-gtk3 to latest version (from Nixpkgs)
2. Apply it as usual
3. Open Electron based app
4. Window title bar be weird transparent

### Expected behavior
It looks as usual

### Screenshots
I show screenshots from my installed Electron-based apps, VS Code & YouTube Music by th-ch
![image](https://github.com/user-attachments/assets/65b35f51-8da7-4bc4-a71c-bb495496d49b)
![image](https://github.com/user-attachments/assets/77a33f84-df95-4d8c-bc67-936c51275a56)

### Additional context
I haven't idea sources of this bugs

### Notify maintainers
@ciferkey @r-ryantm 

### Metadata
```console
[anifyuli@ThinkPad-X280:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240923.30439d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Anifyuli** [comment]
Based on upstream issue, it needs GTK 4.16 for v5.4 version. I wish it can solved soon as possible

**Comment by ciferkey** [comment]
This [PR](https://github.com/NixOS/nixpkgs/pull/333911) for Gnome 47 needs to merge first.

**Comment by Diegopyl1209** [comment]
![image](https://github.com/user-attachments/assets/f0a09540-fa43-4b42-a0e8-1cbd42927f8f)

**Comment by surfaceflinger** [comment]
Maybe we could just revert #343703 and update it again once GNOME 47 is merged?

**Comment by Anifyuli** [comment]
> Maybe we could just revert #343703 and update it again once GNOME 47 is merged?

I override it on my configurations and it works properly
