### ISSUE TITLE
Add immich version configuration option

### ISSUE THREAD

**Issue by ISibboI** [NixOS/nixpkgs#345040]
Currently, immich does not expose a version field in NixOS. This means, that users always are forced to use the packaged version in NixOS. However, it is unclear how immich handles upgrades between far-away versions. Compare for example to nextcloud, which allows updates only one version at a time, and hence exposes a version field to allow the user to update gracefully.

Should immich do the same?

@jvanbruegge 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Nextcloud has a `package` option and so does immich. If there ever is a problem with upgrades we can set its default based on `system.stateVersion`.
