### ISSUE TITLE
shotwell broken by gexiv2 upgrade

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#34512]
## Issue description

The shotwell package was broken by the update to gexiv2 in effa9e40457e801577b672dadbcc169fd1ad20a3

### Steps to reproduce

`nix-env -e shotwell`

The failure you get is:

```
error: Package `gexiv2' not found in specified Vala API directories or GObject-Introspection GIR directories
```

I suspect that if hydra were on-line right now you could get the same detail from there.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by dtzWill** [comment]
Ha! Well at least we came to the same conclusion :).

@jtojnar : there's a shotwell update available (https://github.com/NixOS/nixpkgs/commit/3d6b1270b9c64813465f5d849be2a3a3c54cb768) if you wanna grab that while you're in these parts :).
