### ISSUE TITLE
Update request: oh-my-posh 23.12.0 → 23.20.3

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#345221]
- Package name: oh-my-posh
- Latest released version: 23.20.3

- Current version on the unstable channel: 19.29.0
- Current version on the stable/release channel: 23.15.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@lucperkins 
@urandom2 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by NovaViper** [comment]
Now it's updated to 23.15.1!

**Comment by NovaViper** [comment]
Saw it got updated by #351256, closing because it resolves this issue!
