### ISSUE TITLE
Package request: visualjj (VSCode extension for jujutsu)

### ISSUE THREAD

**Issue by drupol** [NixOS/nixpkgs#345246]
**Project description**

A VSCode extension for [JuJutsu](https://github.com/martinvonz/jj)

**Metadata**

* homepage URL: https://www.visualjj.com/
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by l-d-s** [comment]
@drupol I think this has a non-free license.

**Comment by drupol** [comment]
Yes. (https://github.com/NixOS/nixpkgs/blob/179fd3100c72549e88b5d853e3e8dd57844e8e0f/pkgs/applications/editors/vscode/extensions/visualjj.visualjj/default.nix#L40)

**Comment by l-d-s** [comment]
> Yes.

@drupol sorry I missed this!
