### ISSUE TITLE
Wireplumber audio profile changes when opening some apps such as Discord and Helldivers

### ISSUE THREAD

**Issue by NateWright** [NixOS/nixpkgs#345313]
### Describe the bug
Audio device will reconnect when joining a discord voice channel.

### Steps To Reproduce
1. Be on nixos unstable
2. Launch application that records microphone.

### Expected behavior
Launch applications do not cause audio to reconnect and profiles stay the same.

### Screenshots
![image](https://github.com/user-attachments/assets/d0e5b06f-4685-48a1-84f6-e4496c958521)
![image](https://github.com/user-attachments/assets/0cddce20-a150-47c0-93c3-fd7eab81e2dc)

### Additional context
Seems to be related to this bug https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/634#note_2380391
Didn't happen before latest wireplumber update.

### Notify maintainers
@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11.20240926.1925c60`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Is this happening on a Bluetooth device?

**Comment by NateWright** [comment]
No it is not. I have an Focusrite audio interface which does audio in and out.

**Comment by NateWright** [comment]
I added the wrong link. This is a similar issue to mine. It looks like he is using a razer barracuda. 
https://bbs.archlinux.org/viewtopic.php?id=299486

**Comment by K900** [comment]
Please report this upstream.

**Comment by NateWright** [comment]
Upstream bug
