### ISSUE TITLE
private-gpt: tensorflow-2.13.0 not supported for interpreter python3.12

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#345475]
### Describe the bug

![image](https://github.com/user-attachments/assets/38b928ca-9295-4d96-8b83-7fa4f26af1cf)

### Reproduce steps:

1. `nix-shell -p private-gpt`

@GaetanLepage

**Comment by GaetanLepage** [comment]
Yes, unfortunately, we have an outdated version of `tensorflow` in nixpkgs.
Nobody  seems to have the necessary time and/or skills to tackle this highly non-trivial task.

In the meantime, we can maybe pin `private-gpt`'s python to 3.11, but this is a flaky, short-term solution.
I don't know for how long 3.11 will be supported.

At some point, we might just use the binary version of `tensorflow` by default `tensorflow-bin`.

**Comment by luochen1990** [comment]
![image](https://github.com/user-attachments/assets/0749d75b-d8f5-4479-9279-fc56f47d24dd)

With python 3.11 is also not working :(

**Comment by GaetanLepage** [comment]
> With python 3.11 is also not working :(

Well, that's another problem...

**Comment by luochen1990** [comment]
Is it possible to make tensorflow optional?  since as a recommended usage, the model is running in Ollama or something else, and this project is just a frontend.

**Comment by Tungsten842** [comment]
> Is it possible to make tensorflow optional? since as a recommended usage, the model is running in Ollama or something else, and this project is just a frontend.

You can solve this issue by disabling keras in wandb for python 3.12 or bigger.

**Comment by Pandapip1** [comment]
Looks like tensorflow was updated to point to tensorflow-bin (https://github.com/NixOS/nixpkgs/pull/345658). This no longer has a build failure.
