### ISSUE TITLE
Update request: [BACKPORT] Ryujinx 1298 → 1398

### ISSUE THREAD

**Issue by Redhawk18** [NixOS/nixpkgs#345410]
- Package name: Ryujinx
- Latest released version: 1398

- Current version on the unstable channel: 1398
- Current version on the stable/release channel: 1298

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@06kellyjac
@artemist 

-----

Note for maintainers: Please tag this issue in your PR.
backport
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
Done in #346714
