### ISSUE TITLE
Package request: parpd

### ISSUE THREAD

**Issue by stv0g** [NixOS/nixpkgs#345461]
**Project description**

parpd is a Proxy ARP Daemon and complies with [RFC 1027](http://tools.ietf.org/html/rfc1027).

**Metadata**

* homepage URL: https://github.com/NetworkConfiguration/parpd
* source URL: https://github.com/NetworkConfiguration/parpd
* license: bsd-2clause
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #346418
