### ISSUE TITLE
Package request: choparp

### ISSUE THREAD

**Issue by stv0g** [NixOS/nixpkgs#345460]
**Project description**

choparp is a proxy ARP daemon. It listens for ARP requests on a network interface, and sends ARP replies with a specified MAC addresses when the requested IP addresses matches a user-provided list.

**Metadata**

* homepage URL: https://github.com/quinot/choparp
* source URL: https://github.com/quinot/choparp
* license: bsd-3clause
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #346415
