### ISSUE TITLE
Package request: wush  (might be usefull to someone)

### ISSUE THREAD

**Issue by denver-cfman** [NixOS/nixpkgs#345568]
**Project description**
wush is a command line tool that lets you easily transfer files and open shells over a peer-to-peer WireGuard connection. It's similar to [magic-wormhole](https://proofpointisolation.com/browser?url=https%3A%2F%2Fgithub.com%2Fmagic-wormhole%2Fmagic-wormhole)

**Metadata**

* homepage URL: https://github.com/coder/wush
* source URL: https://github.com/coder/wush
* license: Creative Commons Zero v1.0 Universal
* platforms: linux, darwin,

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by winterqt** [comment]
Already packaged, just not in 24.05.
