### ISSUE TITLE
Package request: rime-ls

### ISSUE THREAD

**Issue by deeengan** [NixOS/nixpkgs#345612]
Allows librime/rime to be used as a language server in text editors (like VIM, Helix, etc.)

**Metadata**

* homepage URL: https://github.com/wlh320/rime-ls
* source URL: https://github.com/rime/librime
* license: BSD 3-Clause
* platforms: ubuntu, arch, nixOS, macOS, Windows
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by definfo** [comment]
I've written a problematic package definition here [rime-ls](https://github.com/definfo/nur-packages/blob/master/pkgs/rime-ls/default.nix).
Known issue: rime data customization is broken. I am trying to fix it :(
