### ISSUE TITLE
chatterino2: no window decoration in Gnome on non NixOS

### ISSUE THREAD

**Issue by kabessao** [NixOS/nixpkgs#345644]
### Describe the bug
Building Chatterino2 on Gnome in a non NixOS system gives me an application that doesn't have window decorations in any of it's windows.

### Steps To Reproduce
1. in any Gnome system that isn't NixOS ( haven't tested on nixos with gnome itself ) install chatterino2 either by nix-env, nix-shell, or with home-manager

### Expected behavior
I expect that the application could have window decorations.
I know Gnome has that whole thing about expecting applications to provide the window decoration, but I've heard that there are ways to make it happen. Sorry in advance if that's not really the case.

### Screenshots
Here's a side by side print of a working chatterino application (left) against the one installed through home-manager (right):
![image](https://github.com/user-attachments/assets/9fd8ecc5-83b0-4bea-bf24-e54b963f1580)

In here you can see that even in other windows, like the config screen, also has no window decorations.
![image](https://github.com/user-attachments/assets/caac8f2c-4e6b-4d95-885d-e0d31a100fbb)

### Additional context
I'm using Nobara Linux 40, Gnome 46.4, and I've installed this in a fresh install of Home-Manager so I can learn Nix and migrate to NixOS in the future.

I have tested with different versions of nix repos and still no luck

### Notify maintainers
@rexim @0Supa 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0-201.fsync.fc40.x86_64, Nobara Linux, 40 (GNOME Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.1`
 - channels(root): `"home-manager, nixpkgs, oldnix-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 0Supa** [comment]
This doesn't seem like an issue with the package itself. Could you see if https://github.com/NixOS/nixpkgs/issues/339608#issuecomment-2331172290 fixes your issue?

**Comment by kabessao** [comment]
I tried and it's still the same
![image](https://github.com/user-attachments/assets/b0f8b2e2-2525-4b95-9c7a-b9cbe9b35088)

**Comment by kabessao** [comment]
quick update, I've been trying different versions from here:
https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=chatterino2

Turns out that version 2.4.6 works as expected, with window decoration and everything
```shell
nix-shell -p chatterino2 -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e89cf1c932006531f454de7d652163a9a5c86668.tar.gz
```
while the latest version doesn't
```shell
nix-shell -p chatterino2 -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/05bbf675397d5366259409139039af8077d695ce.tar.gz
```
here's another side to side comparison. version 2.4.6 (left) and the latest version 2.5.1 (right), now both from nixpkgs.
![image](https://github.com/user-attachments/assets/7e72c8c9-c4b3-4807-a9b1-d04a1616366c)

**Comment by kabessao** [comment]
From what I could understand, with my rather small understanding of nix code, the newest version is adding the `qt6.qtwayland` package, while the version 2.4.6 does not include that.

And sure enough, the older version is running under xwayland, and because of that it works, while the newest version is running natively on wayland, and because Gnome doesn't do window decoration you'll see none in it.

**Comment by kabessao** [comment]
Did more tests by following the build instructions in here 
https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_LINUX.md

When building inside a Fedora 39 distrobox and following the instructions specifically for Fedora 39 I get a working chatterino, with window decorations and everything. 

When building inside a nix shell following the instructions described specifically for NixOS I get a chatterino app with no window decorations.

**Comment by kabessao** [comment]
I was able to make the latest chatterino work as expected by overriding it's attributes to use `qt5.qtbase`:
```nix
  nixpkgs.overlays = [
    (final: prev: {
      chatterino2 = prev.chatterino2.overrideAttrs (oldAttrs: {
          buildInputs = with pkgs;[
            boost
            openssl
            libsecret
            pkg-config

            qt5.qtbase

            qt6.full
            qt5.full
            qt5.qtwayland
          ];
          cmakeFlags = [];
      });
    })
  ];
```
and most likely this works because it's running on xWayland.
![image](https://github.com/user-attachments/assets/265239b8-67e9-420d-94f3-bc2e5425916d)

**Comment by kabessao** [comment]
Right, so for my last test I booted a NixOS image and ran Chatterino inside it and it works there just fine. Another thing 

So I guess NixOS has some fix for gnome or something that I'm not aware of which is not present when you install it through nix in other linux distros.
![image](https://github.com/user-attachments/assets/c08133b5-883d-4218-b11d-6057c2d16e69)

for now I think the best course of action is to close this issue, since it's not really a problem on how the application is packaged in nixpkgs, tho at the very least this issue got me to understand more about nix in general.
