### ISSUE TITLE
stable: Derivation for python2 odfpy is broken

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#34561]
## Issue description

The build of `nixpkgs.python27Packages.odfpy.x86_64-linux` on stable is as of now broken, as seen on hydra. https://hydra.nixos.org/jobset/nixos/release-17.09

This means, that I cannot install any environments which depend on this package.
This includes for example calibre or texlive.combined.scheme-full, which is quite a deal breaker.

I guess the problem might just go away by disabling tests in the package, but I am not sure.

### Steps to reproduce

`nix-env -iA nixos.python27Packages.odfpy`

fails.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
- system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2857.cee2f856766 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(maralorn): `""`
 - channels(root): `"unstable-18.03pre126508.8ecadc12502, nixos-17.09.2875.c2b668ee726"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/issues/33362#issuecomment-362845308. A fix should end up in your channel within a day or so.

**Comment by maralorn** [comment]
I am sorry. I really tried to search for an existing ssue. I didn't try hard enough though …

**Comment by FRidh** [comment]
No problem! It was marked as closed as well.
