### ISSUE TITLE
Impossible to pass signal account UUID using environment variable to `mollysocket` module

### ISSUE THREAD

**Issue by amalgame21** [NixOS/nixpkgs#345768]
### Describe the bug
Impossible to pass signal account UUID using environment variable to `mollysocket`

### Steps To Reproduce
1. `echo "MOLLY_ALLOWED_UUIDS=['uuid-of-signal-account']" > /run/secret/mollysocket`
2. set `environmentFile = /run/secret/mollysocket` in mollysocket
3. error message in journal: `Config parse error: invalid type: found string "['uuid-of-signal-account']", expected a sequence for key "ALLOWED_UUIDS" in 'MOLLY_' environment variable(s)`

### Expected behavior
mollysocket accept the environment variable

### Notify maintainers
@dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20240930.1719f27`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.6`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
What about `MOLLY_ALLOWED_UUIDS=["uuid-of-signal-account"]`?

**Comment by amalgame21** [comment]
> What about `MOLLY_ALLOWED_UUIDS=["uuid-of-signal-account"]`?

Oops, it works, my bad.
Thanks so much for your help!
