### ISSUE TITLE
Update request: python312Packages.typer 0.12.3 → 0.12.5

### ISSUE THREAD

**Issue by padhia** [NixOS/nixpkgs#345707]
- Package name: python312Packages.typer
- Latest released version:  0.12.5

- Current version on the unstable channel: 0.12.3
- Current version on the stable/release channel: 0.12.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@winpat 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/pull/345326, 3cb2de74e60ca662bff9a283cde68b27e54e35b0
