### ISSUE TITLE
darwin: racket broken since 6.10 introduced back in August

### ISSUE THREAD

**Issue by clacke** [NixOS/nixpkgs#34576]
## Issue description

racket does not build on MacOS. I git-bisected, and the commit that introduced the issue is:

`8dc06a23856292fc148d430b1cc88c723aa8b639`
`Sat Aug 26 18:35:40 2017 +0200`
`racket: 6.9 -> 6.10`

The error looks different now from how it looked back then. Back then it passed `configure` and later got a link error. Now it fails already in `configure`.

### Steps to reproduce

```
$ nix-build -A racket '<nixpkgs>'
[ . . . ]
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-racket-6.11.drv-1/racket-6.11/src/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for ‘/nix/store/sasd6rvr4zx22xg0zd5wfpydymcxf2l4-racket-6.11.drv’ failed with exit code 77
error: build of ‘/nix/store/sasd6rvr4zx22xg0zd5wfpydymcxf2l4-racket-6.11.drv’ failed```
```

config.log:

```
[ . . . ]
configure:3680: checking whether the C compiler works
configure:3702: gcc    conftest.c  >&5
/nix/store/pk7pbzir6kxwzqb4n5wasqjs9fvl1nx9-gcc-wrapper-7.2.0/bin/as: assembler (clang) not installed
configure:3706: $? = 1
configure:3744: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define USE_SINGLE_FLOATS 1
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
[ . . . ]
```

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(clacke): `"nixpkgs-18.03pre126020.931a0b8be80"`
 - nixpkgs: `/Users/clacke/.nix-defexpr/channels/nixpkgs`

**Comment by clacke** [comment]
And indeed it can be reproduced even without trying to build racket itself:

```
$ nix-shell --pure -A pkgs.racket --run "gcc -x c -o /dev/null - <<<'
int main() {
  return 0;
}
'"
/nix/store/pqkkw8wrxygzvy8imf69vd6l8bnc6pvm-gcc-wrapper-7.3.0/bin/as: assembler (clang) not installed
```

Is this simply some buildInput missing?

**Comment by clacke** [comment]
Simply reverting `pkgs/development/interpreters/racket/default.nix` does no good.

**Comment by LnL7** [comment]
Builds on darwin should use clang instead of gcc, unless it's really necessary.

**Comment by LnL7** [comment]
This is the actual build problem that go introduced a few versions back.

```
clang -o racketcgc main.o  libracket.a libmzgc.a ../rktio/librktio.a  -ldl -lm
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_CFLocaleCopyCurrent", referenced from:
      _rktio_system_language_country in librktio.a(rktio_convert.o)
  "_CFLocaleGetIdentifier", referenced from:
      _rktio_system_language_country in librktio.a(rktio_convert.o)
  "_CFRelease", referenced from:
      _rktio_system_language_country in librktio.a(rktio_convert.o)
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
      _rktio_strcoll_utf16 in librktio.a(rktio_convert.o)
  "_CFStringCompare", referenced from:
      _rktio_strcoll_utf16 in librktio.a(rktio_convert.o)
  "_CFStringCreateMutableCopy", referenced from:
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
  "_CFStringCreateWithBytes", referenced from:
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
      _rktio_strcoll_utf16 in librktio.a(rktio_convert.o)
  "_CFStringGetCString", referenced from:
      _rktio_system_language_country in librktio.a(rktio_convert.o)
  "_CFStringGetCharacters", referenced from:
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
  "_CFStringGetLength", referenced from:
      _rktio_system_language_country in librktio.a(rktio_convert.o)
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
  "_CFStringLowercase", referenced from:
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
  "_CFStringUppercase", referenced from:
      _rktio_recase_utf16 in librktio.a(rktio_convert.o)
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by clacke** [comment]
It seems that if gcc is really necessary, it simply doesn't work. Not gcc 7, not gcc 6, and gcc 5 doesn't even compile (doesn't apply patches cleanly  #33722 ). I'm trying to find out when that (gcc 6 and 7) happened too, but in the meantime I will see if I can get racket built with clang.

**Comment by clacke** [comment]
Oh, I see. There is a gccStdenv which actually does work. I'll try that first.

**Comment by LnL7** [comment]
FYI. This is the patch I used to get past the gcc error, gccStdenv could be used but isn't necessary here.

```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 92f81ee2861..5a48bcfc3d6 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -6987,7 +6987,7 @@ with pkgs;
     # racket 6.11 doesn't build with gcc6 + recent glibc:
     # https://github.com/racket/racket/pull/1886
     # https://github.com/NixOS/nixpkgs/pull/31017#issuecomment-343574769
-    stdenv = overrideCC stdenv gcc7;
+    stdenv = if stdenv.cc.isGNU then overrideCC stdenv gcc7 else stdenv;
   };
 
   rakudo = callPackage ../development/interpreters/rakudo {
```

**Comment by clacke** [comment]
Thanks, I should have looked here again while investigating. I finally found that same line as the cause why it was using gcc. :-)

I got it compiling, with a correctly used gcc 7. Rather than the minimal patch, I made a gcc7Stdenv so that the next person doing this is less likely to break darwin again. Also it's necessary to add CoreFramework --
 that's what originally broke racket 6.10.

I will remove gcc for racket on darwin in a second commit. But there's also a test in one of the racket packages that breaks, and I will investigate why before I make any PR.

**Comment by LnL7** [comment]
@clacke Great! It seemed to work fine with clang tho, did that not work?

**Comment by clacke** [comment]
Getting this with both gcc and clang:

```
raco setup: --- summary of errors ---
raco setup: error: during building docs for <pkgs>/racket-doc/scribblings/reference/reference.scrbl
raco setup:   examples: exception raised in example
raco setup:     error: "bytes-convert: contract violation\n  expected: bytes-converter?\n  given: #f\n  argument position: 1st\n  other arguments...:\n   #\"ABCD\""
make[1]: *** [Makefile:178: install-3m] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-racket-6.12.drv-4/racket-6.12/src/build'
```

**Comment by clacke** [comment]
bisecting on `nix-build -E 'with import ./. {}; (racket.override { inherit stdenv; }).overrideDerivation (drv: { NIX_LDFLAGS = "-framework CoreFoundation"; buildInputs = drv.buildInputs ++ [ darwin.apple_sdk.frameworks.CoreFoundation ]; })'`.

**Comment by clacke** [comment]
Partially solved by #35285 , but for full `racket` to build, I need to find why `pkgs/racket-doc/scribblings/reference/reference.scrbl` fails.

**Comment by clacke** [comment]
bisecting on `nix-build -E 'with import ./. {}; (racket.override { inherit stdenv; }).overrideDerivation (drv: rec { name = "racket-${version}"; version = "6.9"; src = fetchurl { url = "http://mirror.racket-lang.org/installers/${version}/${name}-src.tgz"; sha256 = "1cd218ee2ba1dc683de858a866c6666eb72a11adee8d1df6cdd59c5c5a47b714"; }; })'`

... as 6.9 breaks in the same place on a recent nixpkgs, but built back in August. Supplying the unmodified stdenv fixes the gcc breakage.

**Comment by clacke** [comment]
It was the lack of a `libiconv`. Patch incoming.

**Comment by LnL7** [comment]
Oh! Great find, never really crossed my mind that the CFLocale* CFString* symbols might not be from CoreFoundation.

**Comment by clacke** [comment]
Oh no, they were from CoreFoundation. This is not about the link error, that's already solved and that's why racket-minimal builds.

But if I include `libiconv` in `buildInputs`, `(bytes-open-converter "UTF-8" "UTF-16")` will return a byte-converter. If I don't, it will return `#f` and break the example in the documentation. Even if libiconv is in `LD_LIBRARY_PATH`. I haven't looked at the exact configure output to understand why. There are lots of things in `LD_LIBRARY_PATH` that aren't in `buildInputs` and that seems to be fine.

**Comment by clacke** [comment]
I guess it has to end up in `CFLAGS` and that happens if it is in `buildInputs`?

**Comment by clacke** [comment]
The stuff in LD_LIBRARY_PATH, is that for racket code that loads libraries dynamically through ffi?

**Comment by clacke** [comment]
Answering myself to not leave anyone hanging: No. Racket loads dynamic libraries during runtime by looking at its `config.rktd`, symbol `lib-search-dirs`. I don't know why Linux and Darwin differ, but on Darwin, this is not initialized with either `DYLD_LIBRARY_PATH` nor `LD_LIBRARY_PATH`, and Darwin Racket does not look there when running. I will do something about this in a separate issue, this one can stay closed.
