### ISSUE TITLE
Update request: krita 5.2.3 → 5.2.6

### ISSUE THREAD

**Issue by callyral** [NixOS/nixpkgs#345760]
- Package name: krita
- Latest released version: 5.2.6

- Current version on the unstable channel: 5.2.3
- Current version on the stable/release channel: 5.2.2

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@abbradar
@sifmelcara

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sifmelcara** [comment]
cc the other maintainer @nek0 

I tried simply updating the version and removing the outdated patch file we have, but I hit a lot of error message like this
```
/build/krita-5.2.6/build/plugins/extensions/pykrita/sip/_tmp/krita/sipkritapart0.cpp: In member function 'virtual bool sipManagedColor::event(QEvent*)':
/build/krita-5.2.6/build/plugins/extensions/pykrita/sip/_tmp/krita/sipkritapart0.cpp:4373:28: error: too few arguments to function
 4373 |     sipMeth = sipIsPyMethod(&sipGILState, &sipPyMethods[0], SIP_NULLPTR, sipName_event);
```

I won't have time/equipment to look into this in the next 1-2 weeks, can someone else take a look?

**Comment by nek0** [comment]
The updated version including the patchfile builds fine, so I guess it's not as outdated as initially assumed.
