### ISSUE TITLE
Build failure: adding xdg-desktop-portal-gtk conflicts with GNOME's implementation

### ISSUE THREAD

**Issue by freelock** [NixOS/nixpkgs#345733]
### Steps To Reproduce

1. Set the following options:
```
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
```

### Build log

```
building the system configuration...
error: builder for '/nix/store/bywyrsnljzzln4csq9gk6585zhifcshy-user-units.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/jk674blqjdyjzbq3c2gwczapawxalz3m-user-units/xdg-desktop-portal-gtk.service': File exists
       For full logs, run 'nix log /nix/store/bywyrsnljzzln4csq9gk6585zhifcshy-user-units.drv'.
error: 1 dependencies of derivation '/nix/store/jyq18m9bv9y2gyjn57y6pcj513azmnsc-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1xwqgshgpjns6fh4f5v540nqkg55h5zv-nixos-system-valhalla-24.11.20240929.06cf0e1.drv' failed to build
```

### Additional context

It looks like xdg-desktop-portal-gtk was added in https://github.com/NixOS/nixpkgs/commit/c4c3b41d4a6de7c2dc5e5ee4d2220447ce1de204

... I think Gnome modifies this package somehow, creating the conflict. This only breaks if you try to install both Gnome and Plasma6 simultaneously.

### Notify maintainers

@K900 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/jvr4c9nb6xzw365px5gxh34sk88fqa7w-nix-info
copying path '/nix/store/jvr4c9nb6xzw365px5gxh34sk88fqa7w-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240929.06cf0e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/home/john/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
This is kind of normal, GNOME uses a different build of xdg-desktop-portal-gtk, so there's not much we can do here really. If you really want to have both, maybe run them in specializations.

**Comment by freelock** [comment]
I'm not really using Gnome very often, but rebuilding without it, I've lost a bunch of fonts in GTK apps... any suggestions?

**Comment by K900** [comment]
Install whatever fonts you need?

**Comment by JohnRTitor** [comment]
Causes issue in sway, hyprland, other Wayland compositors as well. CC @jtojnar

**Comment by jtojnar** [comment]
I think it should be fine to just enable all the portals in x-d-p-gtk unconditionally, now that the portal selection is configurable.

**Comment by Frontear** [comment]
I have been thinking of an alternative implementation:

1. Create a new `options.xdg.portal.gtk.{enable, package}`
2. Enable it in all relevant locations rather than directly adding

Benefits here would be overall deduplication, though in cases of GNOME/standalone compositor it WILL favor gnome. Honestly thats not something I can reasonably think of a fix for that doesnt include manually checking _every single module_ possible.

**Comment by Frontear** [comment]
The main reason I added the `.package` option was for GNOME/Cinnamon/Deepin, all of which override the default `xdg-desktop-portal-gtk` derivation
