### ISSUE TITLE
snapper: Doesn't take snapshots

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#34595]
## Issue description
I'm using snapper on btrfs and it doesn't seem to take automatic snapshots, even though the services seem to be running and the timer is working. I'm not sure what other info I can give you.

It does, however, take snapshots manually.

### Steps to reproduce
Install snapper, add configuration to whatever.nix.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2905.c1d9aff56e0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2905.c1d9aff56e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by markuskowa** [comment]
Can you post your config (the part with the snapper config)?

**Comment by Chiiruno** [comment]
`services.snapper.configs."root".subvolume = "/";`

**Comment by markuskowa** [comment]
Try adding the following to your config:  
```
services.snapper.configs.root.extraConfig = ''
  TIMELINE_CREATE="yes"
'';
```
According to the man page (snapper-configs) the default is `no` for time line snapshots.

**Comment by Chiiruno** [comment]
That did it, thanks.
