### ISSUE TITLE
goldwarden: desktop file missing icon

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#345901]
### Describe the bug
Goldwarden doesn't have an icon in XDG app launchers.

### Steps To Reproduce
1. Install goldwarden
2. Open an app launcher & find it

### Expected behavior
Goldwarden should have an icon.

### Screenshots
![Goldwarden in GNOME's app launcher, with a generic icon](https://github.com/user-attachments/assets/35e54848-de5c-4d3e-bf94-be65ce222fe4)

### Notify maintainers
@arthsmn

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0, NixOS, 24.11 (Vicuna), 24.11pre687049.06cf0e1da420`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kilianar** [comment]
The [desktop file](https://github.com/quexten/goldwarden/blob/main/gui/com.quexten.Goldwarden.desktop) we install specifies `Icon=com.quexten.Goldwarden`, but the actual icon is installed at `$out/share/icons/hicolor/scalable/apps/goldwarden.svg`. It seems that the icon isn't being recognized because the icon name in the desktop file doesn't match the name of the installed icon file.

**Comment by 0n-s** [comment]
Yeah, this is actually an upstream bug, it seems. I'll take it up with them momentarily.

**Comment by 0n-s** [comment]
Well, that PR is merged now; maintainer should keep this in mind for next update.

This should be closed when the issue is actually solved in nixpkgs.

**Comment by Atemu** [comment]
As this is an upstream bug, we don't need to track it.
