### ISSUE TITLE
Lima not supporting vz in Mac - works when compiled manually

### ISSUE THREAD

**Issue by josvazg** [NixOS/nixpkgs#346006]
### Describe the bug

The lima **nix** package is unable to use `vz` in Mac due to some build tooling being stale regarding the MacOS SDK version it "sees".

### Steps To Reproduce
1. Use nix package lima in a current Mac (Eg a M1) with SDK 15.0 
2. Try to start a VM using `vz`.
3. See it fail: `FATA[0000] vm driver 'vz' needs macOS 13 or later (Hint: try recompiling Lima if you are seeing this error on macOS 13) `
4. Compile manually on the same machine (repository: https://github.com/lima-vm/lima cmd: `make binaries`)
5. See that binary work where the nix one failed.

### Expected behavior

I would expect the nix package would work with `vz` just like the manual compilation does.

### Additional context

Was trying to write a flake to reproduce and debug. This is what I found out:
- The [lima Makefile would disable `vz` explicitly](https://github.com/lima-vm/lima/blob/master/Makefile#L23) depending on the output of `xcrun` tool.
- The `xcrun` tool run by the nix package is within the nix package `xcbuild` [which replaces xcrun with a script wrapper](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/xcbuild/wrapper.nix)
- Such script seems to be stalled in the past at `MacOS11.0.sdk`

Seems the script itself is dynamic. Does it mean it basically depends on what version of MacOS X is running it?
Is there any easy known workaround to get this nix package working with `vz`?

### Notify maintainers

@r-ryantm 
@wegank

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
Might this be related to the recent darwin PR improving tooling for building?

I cannot for the life of me remember the PR, but I know its there somewhere

**Comment by josvazg** [comment]
I am a nix newbie, I can't figure out why the `xcbuild` package choses an old version of Mac SDK libraries. The way it is written, the wrapper mentioned would work if if was compiled with a version 13 or later of the SDK. But I cannot figure out why it is using older libraries.
There [original repo that package is based from is archived in GH](https://github.com/facebookarchive/xcbuild/tree/dbaee552d2f13640773eb1ad3c79c0d2aca7229c), which is problematic, but not sure is fatal.

**Comment by wegank** [comment]
Let's recheck after #346043 lands...

**Comment by emilazy** [comment]
After https://github.com/NixOS/nixpkgs/pull/346043, all that will need to be done is adding `apple-sdk_13` (or whatever) to `lima`’s `buildInputs`.

**Comment by cmacrae** [comment]
i happened to stumble across this while looking for something completely unrelated, but i've been using Lima from nixpkgs with `vz` VMs just fine for the past week :)

**Comment by josvazg** [comment]
> i happened to stumble across this while looking for something completely unrelated, but i've been using Lima from nixpkgs with `vz` VMs just fine for the past week :)

how? Just installed it again and it is on version 0.22.0, and I still get the same error:
```shell
FATA[0000] vm driver 'vz' needs macOS 13 or later (Hint: try recompiling Lima if you are seeing this error on macOS 13)
```

Anything special to do to get it working?

**Comment by josvazg** [comment]
Tried https://github.com/NixOS/nixpkgs/pull/354552 but it does not work. Apple SDK 11.3 is still used instead of Apple 15 as I tried to force.
Anyone know how to fix it?

**Comment by josvazg** [comment]
When #355729 appears in unstable I will test and close this issue

**Comment by josvazg** [comment]
It is working in `unstable` already:

```shell
[nix-shell:~]$ limactl --version
limactl version 1.0.1

[nix-shell:~]$ limactl list
NAME       STATUS     SSH            VMTYPE    ARCH       CPUS    MEMORY    DISK      DIR
test       Stopped    127.0.0.1:0    vz        aarch64    4       4GiB      100GiB    ~/.lima/test

[nix-shell:~]$ limactl start test
...
INFO[0000] Starting the instance "test" with VM driver "vz" 
...
INFO[0001] [hostagent] [VZ] - vm state change: running  
...
INFO[0015] READY. Run `limactl shell test` to open the shell. 
```

Thanks!
