### ISSUE TITLE
Cannot install gnumake man-pages to profile

### ISSUE THREAD

**Issue by Meizikyn** [NixOS/nixpkgs#34608]
GNU Make does not install man pages into the active profile.

### Steps to reproduce
If, for example installing GNU Make via.
`nix-env -iA nixos.gnumake`
`nix-env -iA nixos.gnumake.man`

nix-env reports successful install, I even have the man-pages in my /nix/store
`/nix/store/gx70gyfwdkqf5vlicm9dwaqyklxqzzax-gnumake-4.2.1-man`

but these pages are not in my ~/.nix-profile

configuration.nix is default:
`programs.man.enable = true;`

Have I installed these incorrectly, or require an additional config line?

**Comment by doronbehar** [comment]
Hey, this is kind of old. I'm experiencing the same behaviour with `nixos.gnumake.info` and I can't see them linked in my `~/.nix-profile/share/info`. [I've opened a thread on the forums](https://discourse.nixos.org/t/cant-find-a-way-to-install-gnumake-info-files-to-user-environment/3534). Could you please share what is the reason you closed this?
