### ISSUE TITLE
google-chrome: fails to initialise vulkan implementation due to missing libvulkan.so.1

### ISSUE THREAD

**Issue by JohnRTitor** [NixOS/nixpkgs#346197]
### Describe the bug

If Vulkan in Chrome is enabled via CLI args or `chrome://flags`, Chrome still fails to launch it's vulkan implementation, falling back to OpenGL.

### Steps To Reproduce

```
google-chrome-stable --use-vulkan --enable-features=Vulkan
```

Or directly run:
```
NIXPKGS_ALLOW_UNFREE=1 nix run --impure nixpkgs#google-chrome  -- --use-vulkan --enable-features=Vulkan
```

### Expected behavior
Vulkan is enabled, and working.

### Screenshots
Output from `chrome://gpu`:
![image](https://github.com/user-attachments/assets/e3a454c0-cba1-4546-b4f9-4f60597749a1)

### Additional context

Relevant logs from the terminal.
```
[216457:216457:1003/211719.770352:ERROR:vulkan_instance.cc(112)] Failed to load 'libvulkan.so.1': libvulkan.so.1: cannot open shared object file: No such file or directory
[216457:216457:1003/211719.770434:ERROR:gpu_init.cc(1209)] Failed to create and initialize Vulkan implementation.
```

### Notify maintainers

CC @jnsgruk, Chrome Maintainer
CC @K900 Vulkan maintainer
CC @emilylange Chromium maintainer who helped me a lot with Chrome related packaging issues :)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.1-cachyos, NixOS, 24.11 (Vicuna), 24.11.20241001.27e30d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/masum/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/masum/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/masum/.nix-profile/etc/xdg/nix/nix.conf:/home/masum/.local/state/nix/profile/etc/xdg/nix/nix.conf:/home/masum/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/masum/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cfl6rqw64ndbh2m0qapg410jf4xmycia-lix-2.91.0/share`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source
 
````

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
We do [copy all the needed files](https://github.com/NixOS/nixpkgs/blob/27e30d177e57d912d614c88c622dcfdb2e6e6515/pkgs/by-name/go/google-chrome/package.nix#L213-L214) from the deb package.

And `libvulkan.so.1` exists in `$out/share/google/chrome/`.

**Comment by JohnRTitor** [comment]
Finally figured out the issue, bundled `libvulkan.so.1` was not working properly.
Replacing it with vulkan loader's libvulkan worked like [electron-bin](https://github.com/NixOS/nixpkgs/blob/27e30d177e57d912d614c88c622dcfdb2e6e6515/pkgs/development/tools/electron/binary/generic.nix#L141-L143). Commited part of https://github.com/NixOS/nixpkgs/pull/346215.

**Comment by jnsgruk** [comment]
Nice work, thank you!
