### ISSUE TITLE
Package request: wlock

### ISSUE THREAD

**Issue by yzhou216** [NixOS/nixpkgs#346111]
**wlock: Itsy-bitsy sessionlocker**

wlock is a itsy-bitsy sessionlocker for Wayland compositors that support the `ext-session-lock-v1` protocol; an effective port of slock to Wayland, merging the alternate color patch to give a sense of feedback.

**Metadata**

* homepage URL: https://codeberg.org/sewn/wlock
* source URL: https://codeberg.org/sewn/wlock
* license: gpl3+
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #347893
