### ISSUE TITLE
Lamdu editor packaging

### ISSUE THREAD

**Issue by razvan-panda** [NixOS/nixpkgs#34620]
@peti I packaged Lamdu and its dependencies (with lots of help from cleverca22 - Michael Bishop) and I'm wondering where I could place the nix expressions into?

2 of the dependencies were libraries built with C/++ so they went under `pkgs/development/libraries`, freetype-gl and AntTweakBar:

https://github.com/NixOS/nixpkgs/pull/34556 and https://github.com/NixOS/nixpkgs/pull/34540

Rest of the dependencies are all Haskell packages:
  - AlgoW https://github.com/lamdu/Algorithm-W-Step-By-Step
  - lamdu-calculus https://github.com/lamdu/lamdu-calculus
  - nodejs-exec https://github.com/lamdu/nodejs-exec
  - graphics-drawingcombinators https://github.com/lamdu/graphics-drawingcombinators
  - bindings-freetype-gl https://github.com/lamdu/bindings-freetype-gl

Lamdu would go under `pkgs/applications/editors/lamdu/default.nix` I assume.
But I do not know where I could add these other packages to the nixpkgs hierarchy since they are Haskell packages and most Haskell packages seem to be automatically generated.

Lamdu has over 1300 stars on GitHub so I think it would be useful to get it packaged: 

https://github.com/lamdu/lamdu

http://www.lamdu.org/

**Comment by razvan-panda** [comment]
@peti Here are the nix expressions, not yet packaged for nixpkgs: https://github.com/lamdu/lamdu/pull/85/files

**Comment by peti** [comment]
I think it doesn't matter much where those Nix files are located in the Nixpkgs tree. You can put them wherever you feel is appropriate.

The easiest solution from a packaging point-of-view would be to upload libraries to Hackage. Then they'd be packaged for Nix automatically.
