### ISSUE TITLE
`sssd`-based auth not working in Ubuntu 17.10

### ISSUE THREAD

**Issue by sgraf812** [NixOS/nixpkgs#34624]
## Issue description

I'm having the same symptoms as the infamous #31700 at work, e.g. 

```
$ whoami
whoami: cannot find name for user ID 29805
```

Only that it's for a different reason. This is my `/etc/nsswitch.conf`:

```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files sss
group:          files sss
shadow:         files sss

hosts:          files dns myhostname
networks:       files 

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis sss
```

I strongly suspect it's due to `sss` entries, which entails some communication with the non-`nix`-managed `sssd` process I guess. I tried installing `sssd` and `openldap` (not sure if that's related), but haven't found out how to configure them properly. Also I would rather have the tools communicate with the infrastructure that is already in place.

### Steps to reproduce

1. Install Ubuntu 17.10 on a machine and configure authentication by `sssd`, whatever that entails. We're using Kerberos and AFS here, not sure how to make them work together.
2. Notice that `/usr/bin/whoami` works as expected, but `whoami` from `nix`-installed `coreutils` fails in the above fashion. Same goes for `ssh`, `git` etc.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-32-generic, Ubuntu, 17.10 (Artful Aardvark)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(sgraf): `"nixpkgs-18.03pre126798.42b9b8f7c86"`
 - nixpkgs: `/afs/info.uni-karlsruhe.de/user/sgraf/.nix-defexpr/channels/nixpkgs`

**Comment by dezgeg** [comment]
It might work if you enabled nscd on the Ubuntu. Though I'm not sure how well two different glibc versions manage to talk to each other with the nscd protocol.

**Comment by sgraf812** [comment]
Using `nscd` seems to work, thanks!

**Comment by dezgeg** [comment]
Good to have confirmation that it works.
