### ISSUE TITLE
Update request: zed-editor 0.154.3 → 0.155.2

### ISSUE THREAD

**Issue by kcoderhtml** [NixOS/nixpkgs#346456]
- Package name: zed-editor
- Latest released version: 0.155.2

- Current version on the unstable channel: 0.154.3
- Current version on the stable/release channel: not in stable yet

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GaetanLepage @niklaskorz 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kcoderhtml** [comment]
i'm willing to bump the version

**Comment by GaetanLepage** [comment]
> i'm willing to bump the version

Sure, go for it.
It is no more complicated than running `nix-update --commit zed-editor`.

**Comment by niklaskorz** [comment]
The package was already updated, please look for merged PRs next time: https://github.com/NixOS/nixpkgs/pull/345995

**Comment by kcoderhtml** [comment]
oops; super sorry about that. This is my first time trying to package something.

**Comment by niklaskorz** [comment]
To be fair, it's a common confusion that merged PRs take a few days to land in unstable.
