### ISSUE TITLE
Envision - fails to build profile for WMR with missing dependencies message

### ISSUE THREAD

**Issue by aqxa1** [NixOS/nixpkgs#346546]
### Describe the bug
After installing and enabling the envision module, and launching the application, the WMR profile cannot be built with this error message:
`Missing dependencies:
bc, fmt, fmt-dev, git-lfs, gtest, libepoxy, lz4-dev, tbb
`

and when run from console:
```
Warning (nosuid detection): could not get stat on path /home/clack/.local/share/envision/prefixes/wmr_default
Warning (nosuid detection): could not get stat on path /home/clack/.local/share/envision/prefixes/wmr_default
Warning (nosuid detection): could not get stat on path /home/clack/.local/share/envision/prefixes/lighthouse_default
Warning (nosuid detection): could not get stat on path /home/clack/.local/share/envision/prefixes/wmr_default
Failed to remove path /home/clack/.local/share/envision/basalt/build
Failed to remove path /home/clack/.local/share/envision/monado/build
Failed to remove path /home/clack/.local/share/envision/opencomposite/build

```
The last three lines occur after clicking "Build Profile".

The other profiles seem to build properly, but I don't have the hardware to test those.

### Steps To Reproduce
1. Install and enable envision module
2. Launch `envision`
3. Select "WMR - Envision Default" in drop down and click "Build Profile"

### Expected behavior
WMR profile builds successfully

### Notify maintainers
@Pandapip1

### Metadata
  ```
- system: `"x86_64-linux"`
 - host os: `Linux 6.9.12, NixOS, 24.11 (Vicuna), 24.11.20241001.27e30d1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source`

```

**Comment by Pandapip1** [comment]
Can repro. Will work on a fix.

**Comment by Pandapip1** [comment]
Oh, and CC @Scrumplex

**Comment by Pandapip1** [comment]
Oddly enough, I'm now having issues with envision saying that it's missing `boost`, despite building Monado WMR just fine. As such, envision will be wrapped to run with the `-d` option permanently set.

**Comment by OneGraund** [comment]
Just had the same issue. `-d` flag did help 
OS: Arch Linux 
Kernel: Linux 6.17.5-arch1-1
