### ISSUE TITLE
Update request: mmex Version: 1.6.3 → v1.8.0

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#346653]
- Package name: mmex
- Latest released version:

- Current version on the unstable channel: 1.6.3
- Current version on the stable/release channel: 1.6.3

https://search.nixos.org/packages?channel=unstable&show=mmex&from=0&size=50&sort=relevance&type=packages&query=mmex)

![Screenshot from 2024-10-05 14-06-44](https://github.com/user-attachments/assets/0ebb9146-51c8-48f6-9f76-1f78653ed69b)

**Comment by FliegendeWurst** [comment]
PR: #349736
