### ISSUE TITLE
Make pulseaudio optional for fluidsynth

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#3466]
fluidsynth allows pulseaudio (and many other things) to be optional. It'd be great if we could turn off pulseaudio. `mpd` package should also be ammended to pass through its own `pulseaudioSupport` flag to it: currently even if pulseaudioSupport is set to false for mpd, it gets pulled in by fluidsynth anyway

cc fluidsynth package maintainers @cillianderoiste and @lovek323

**Comment by Profpatsch** [comment]
@Fuuzetsu you can aways patch the packages if something bothers you, you know. :)

pa-support in fluidsynth has been optional for quite some time (except on darwin).
There is even a nixpkgs option, `pulseaudioSupport` that can be set in the config file.
