### ISSUE TITLE
Package request: Thunderbird Beta

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#346604]
**Project description**

This is the beta version of Thunderbird which is often equipped with some extra features and generally very stable. 

This belongs in the nix unstable channel.

**Metadata**

* homepage URL: https://thunderbird.net

**Comment by Steinhagen** [comment]
Probably this won't be needed if the current nixpkgs version will be renamed ESR and the release version will be the latest stable release.

**Comment by vcunat** [comment]
I'd hope that we got this well covered by `thunderbird-latest` which follows roughly the schedule of Firefox again.
