### ISSUE TITLE
Package request: Actual Budget

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#346655]
**Actual Budget is a super fast and privacy-focused app for managing your finances**

* homepage URL: https://actualbudget.org/
* source URL: https://github.com/actualbudget/actual
* license:  MIT license 
* platforms: linux

**Comment by Gaelan** [comment]
I think this is a duplicate of https://github.com/NixOS/nixpkgs/issues/269069 ?

**Comment by oddlama** [comment]
Yes, this is a duplicate. Closing in favor of the existing issue
