### ISSUE TITLE
NixOS Installer broken on nvidia multimonitor setup

### ISSUE THREAD

**Issue by useEffects** [NixOS/nixpkgs#346621]
1. Try to install latest nixos using the iso in nvidia multi monitor setup

Can see display manager service getting started at the boot, immediately goes to a crashed out screen. I was able to install nixos by unplugging monitors connected to my GPU, but then after installing I was able to use only one of the two monitors connected to the GPU at the same time and not both. Monitor connected to cpu worked fine.

I was using gnome on xorg only

**Comment by JohnRTitor** [comment]
Try on Wayland, Xorg has bad multimonitor support anyway.

**Comment by useEffects** [comment]
wayland seems to be working, the maintainers can close the issue if needed.
