### ISSUE TITLE
services.timesyncd.servers doesn't do anything

### ISSUE THREAD

**Issue by thequailman** [NixOS/nixpkgs#34671]
## Issue description

Specifying options via `services.timesyncd.servers` doesn't change /etc/systemd/timesyncd.conf.  Specifying servers in `services.ntp.servers` is the only way.

### Steps to reproduce

```
  services = {
    ntp.servers = [ "10.1.1.1" ]; # Working
    timesyncd.servers = [ "10.1.1.1" ]; # Not working
  };
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.2955.76614894f34 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2955.76614894f34"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by rnhmjoj** [comment]
cc @edolstra @Mic92 
I think `timesyncd.servers` is the intended option and `ntp` is probably a typo.
It's trivial to fix but it's been there for a while so it could cause to silently ignore someone configuration.
