### ISSUE TITLE
protonmail-bridge-gui won't accept --minimize argument in xdg.autostart entry

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#346799]
### Describe the bug
When adding `protonmail-bridge-gui` to home-manager for the purpose of `xdg.autostart`, I cannot add the argument `--minimize` in order to ensure that `protonmail-bridge-gui` minimizes on first boot of NixOS.

### Steps To Reproduce
1. Create an `xdg.autostart` entry for `protonmail-bridge-gui` and add `--minimize` at the end of the exec string.
2. Reboot

### Expected behavior
I would expect `protonmail-bridge-gui` to minimize on boot when adding the `--minimize` argument, like other applications do.

### Notify maintainers
@daniel-fahey

**Comment by daniel-fahey** [comment]
Hi @LinuxMason I wasn't sure how to reproduce this in full. You might like to share any relevant `home-manager` and other configuration snippets. I couldn't find in the [Home Manager Manual](https://nix-community.github.io/home-manager/) how to declaratively configure a custom XDG Autostart entry, unless I'm misunderstanding you?

I was otherwise able to reproduce the failure outside of XDG Autostart / Home Manager to launch `protonmail-bridge-gui` with the undefined `--minimize` flag:

```
[daniel@laptop:~]$ protonmail-bridge-gui --minimize
INFO[Oct 10 09:33:09.196] bridge-gui starting
INFO[Oct 10 09:33:09.196] Using Qt 6.7.2
INFO[Oct 10 09:33:09.203] lock file created /home/daniel/.cache/protonmail/bridge-v3/bridge-v3-gui.lock
INFO[Oct 10 09:33:09.203] bridge-gui executable: protonmail-bridge-gui
INFO[Oct 10 09:33:09.203] Command-line invocation: --minimize
INFO[Oct 10 09:33:09.203] New Sentry reporter - id: [redacted].
DEBU[Oct 10 09:33:09.209] Bridge executable path: /nix/store/z1vn2zlqgljd02fixvzvsfj56pv1828g-protonmail-bridge-gui-3.13.0/lib/bridge
INFO[Oct 10 09:33:09.210] Launching bridge process with command "/nix/store/z1vn2zlqgljd02fixvzvsfj56pv1828g-protonmail-bridge-gui-3.13.0/lib/bridge" --grpc --parent-pid 28165 --minimize --launcher protonmail-bridge-gui --session-id 20241010_093309196
INFO[Oct 10 09:33:09.210] Retrieving gRPC service configuration from '/home/daniel/.config/protonmail/bridge-v3/grpcServerConfig.json'
Incorrect Usage: flag provided but not defined: -minimize

NAME:
   ProtonMailBridge - Proton Mail IMAP and SMTP Bridge

USAGE:
   ProtonMailBridge [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --cpu-prof, -p               Generate CPU profile (default: false)
   --trace-prof, -t             Generate Trace profile (default: false)
   --mem-prof, -m               Generate memory profile (default: false)
   --log-level value, -l value  Set the log level (one of panic, fatal, error, warn, info, debug)
   --grpc, -g                   Start the gRPC service (default: false)
   --cli, -c                    Start the command line interface (default: false)
   --noninteractive, -n         Start the app in non-interactive mode (default: false)
   --log-imap value             Enable logging of IMAP communications (all|client|server) (may contain decrypted data!)
   --log-smtp                   Enable logging of SMTP communications (may contain decrypted data!) (default: false)
   --help, -h                   show help
ERRO[Oct 10 09:33:09.457] Failed to initialize bridge                   SentryID="XuwNxBmqgze/cl8Cb9qceMHLHGQu6v+dbhES83eD6UI=" appName=ProtonMailBridge args="[/nix/store/z1vn2zlqgljd02fixvzvsfj56pv1828g-protonmail-bridge-gui-3.13.0/lib/bridge --grpc --parent-pid 28165 --minimize --launcher protonmail-bridge-gui --session-id 20241010_093309196]" build= error="flag provided but not defined: -minimize" revision=v3.13.0 runtime=linux tag= version=3.13.0
time="2024-10-10 09:33:09.457" level="debug" msg="Locations stopped"
reportID: [redacted] Captured exception :waitAndRetrieveServiceConfig(): Bridge failed to start.
```

You can instead use the [(undocumented) `--no-window` flag](https://github.com/ProtonMail/proton-bridge/blob/df78e292341043b196c2aba812fc48d2c2e8501b/internal/frontend/bridge-gui/bridge-gui/CommandLine.cpp#L29). It's not quite the same exactly as starting the program actually minimised, but is pretty close.

Also while looking into your issue I also discovered that when ticking the "Open on startup" checkbox in the GUI's settings, it creates a new file at `~/.config/autostart/ProtonMailBridge.desktop`:

```
[daniel@laptop:~]$ cat ~/.config/autostart/ProtonMailBridge.desktop 
[Desktop Entry]
Type=Application
Name=ProtonMailBridge
Exec="/etc/profiles/per-user/daniel/bin/protonmail-bridge-gui" "--no-window"
X-GNOME-Autostart-enabled=true
```

That looks like it will work after a dry-run with `dex`:

```
[daniel@laptop:~]$ nix-shell -p dex --run 'dex -ad'
Executing command: /etc/profiles/per-user/daniel/bin/protonmail-bridge-gui --no-window
...
```

**Comment by daniel-fahey** [comment]
If you can share your configuration and show this isn't an upstream issue about `protonmail-bridge-gui` not accepting the `--minimize` flag I'll re-open.

**Comment by daniel-fahey** [comment]
If you can share your configuration and show this isn't an upstream issue about `protonmail-bridge-gui` not accepting the `--minimize` flag I'll re-open.
