### ISSUE TITLE
swi-prolog 6.6.3 on Darwin crashes with Abort trap: 6

### ISSUE THREAD

**Issue by kowey** [NixOS/nixpkgs#3468]
This is on MacOS X 10.9 (Mavericks).
My swi-prolog 6.4.1 was working fine, I think

I notice a lot of this sort of build output:

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't process non-object and non-archive file: /nix/store/1xy4vrm1nrqjfx8zm0m07drbbakx09q3-swi-prolog-6.6.3/lib/swipl-6.6.3/xpce/prolog/lib/Xserver.pl
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't process non-object and non-archive file: /nix/store/1xy4vrm1nrqjfx8zm0m07drbbakx09q3-swi-prolog-6.6.3/lib/swipl-6.6.3/xpce/README
    patching script interpreter paths
    /nix/store/1xy4vrm1nrqjfx8zm0m07drbbakx09q3-swi-prolog-6.6.3/lib/swipl-6.6.3/customize/edit: interpreter directive changed from "/bin/sh -f" to "/nix/store/85h1r887x7raf97l1invbm9zg1c1sfxr-bash-4.2-p45/bin/sh -f "
    /nix/store/1xy4vrm1nrqjfx8zm0m07drbbakx09q3-swi-prolog-6.6.3/lib/swipl-6.6.3/doc/packages/examples/http/debian-init-script: interpreter directive changed from "/bin/sh" to "/nix/store/85h1r887x7raf97l1invbm9zg1c1sfxr-bash-4.2-p45/bin/sh  "
    building path(s) `/nix/store/kf907jfhyyaxzklml5d5kscip2x851j0-user-environment'
    created 1523 symlinks in user environment

**Comment by gridaphobe** [comment]
@kowey can you try again on master? `swipl` doesn't crash for me, but I also don't know what you were doing when it crashed :)

**Comment by joachifm** [comment]
No response for over a year, closing
