### ISSUE TITLE
systemctl privilages lost when enabling emacs daemon

### ISSUE THREAD

**Issue by AveryLychee** [NixOS/nixpkgs#34698]
## Issue description

when the emacs daemon is enabled, and then the system is rebooted, users will lose privilages to type certain commands and be required to authenticate, for example `systemctl shutdown` or `udiskctl mount <something>` will require the user to enter their password (which they shouldn't have to)

### Steps to reproduce

* add `services.emacs.enable = true;` to `/etc/nixos/configuration.nix`.
* reboot
* attempt to use systemctl commands

## Technical details

I cannot provide technical details, since I am not running NixOS right now, however this issue did affect me on several different versions of 17.03 before I figured out the cause.

**Comment by FliegendeWurst** [comment]
Not an issue anymore
