### ISSUE TITLE
Please update to uriparser 0.8.5

### ISSUE THREAD

**Issue by hartwork** [NixOS/nixpkgs#34697]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by adisbladis** [comment]
Pushed in https://github.com/NixOS/nixpkgs/commit/dda6f491923fc02312e01bcb0265324cbf41833e

**Comment by hartwork** [comment]
Cool, thanks!
