### ISSUE TITLE
Update request: persepolis 4.0.1 → 5.0.1

### ISSUE THREAD

**Issue by Lord-Valen** [NixOS/nixpkgs#346951]
- Package name: `persepolis`
- Latest released version: 5.0.1
- Current version on the unstable channel: 4.0.1
- Current version on the stable/release channel: 4.0.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@iFreilicht

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iFreilicht** [comment]
I'll have a look, thank you for reminding me!

**Comment by iFreilicht** [comment]
I did a basic update in #347117, but video downloads are still broken (just like they currently are). Please have a look, I'll try to get them fixed soon.
