### ISSUE TITLE
Firefox noncompliant with GDPR

### ISSUE THREAD

**Issue by hacscred** [NixOS/nixpkgs#347185]
### Describe the bug
Firefox (Thunderbird as well) enables GDPR incompatible telemetry. Since, it's not reasonable to build firefox multiple times, just disabling it by default is the legally safe option. 

See
https://techcrunch.com/2024/09/25/mozilla-hit-with-privacy-complaint-in-eu-over-firefox-tracking-tech/

### Steps To Reproduce
I didn't see any issue mentioning Firefox and gdpr, which makes it incredibly unlikely for the maintainer to have corrected this already for possibly an unreleased version of Firefox. 

I also didn't see any comments in the source code mentioning GDPR, suggesting it is unmanaged. 

### Expected behavior
Don't show any nagging screen (only wasting the time of people everywhere who just want to use Firefox) on startup, but just disable telemetry. I'd patch out the entire feature, but that might be controversial. If that's bad for branding, just call it Iceweasel or NixFox. 

### Notify maintainers

@lovesegfault @hexa

**Comment by winterqt** [comment]
Correcting ping: @mweinelt

**Comment by mweinelt** [comment]
Feel free to take this upstream.

**Comment by rnhmjoj** [comment]
Besides this PPA thing, the official firefox contains hopeless amounts user-hostile garbage ("experiments", ads in the homepage, google safebrowsing, proprietary add-ons, more telemetry etc.)
If you find any of these things annoying, you should probably use librewolf (already packaged).

**Comment by hacscred** [comment]
It's unclear what you want to take upstream, since there are multiple independent issues. 

One of them is how the "feature" should work (I think, as long as Firefox is not bug free there is no reason for user data, because they can still do work without user data; their false argument is that they need user data to make Firefox better). 

Another is that since computers are used by multiple people, it would be impossible to collect consent from everyone, which technically voids the concept of asking for permission or agreeing to anything. 

Subconclusion I, distributing any software for which no contract is signed of the form I will never allow anyone to use this account besides myself for every application collecting telemetry, is incompatible with GDPR. 

Principle: Nixpkgs should not make illegal behavior easy, because this is incompatible with legislation in The Netherlands, where the foundation is located. 

Subconclusion II, Firefox (and other telemetry gathering software) should not be distributed. 

The technical question then becomes whether the installation is just modified at run-time (if this is even possible) or whether because of branding issues something with a different name should be distributed like Iceweasel.   

PS I understand this message might be a shock to many organizations wishing to use telemetry 

Conclusion, the legally safest option is disabling telemetry in the code by patching it out and removing the branding. Every other solution would require consent from Mozilla and/or complex legal issues potentially exposing the foundation to many long legal conflicts. 

Taking it upstream would mean asking people without a working understanding of GDPR (@joepie91 in one of the threads got some weak commitment, but I don't think it's enough in general as explained above) about something we (at least I do) to already be noncompliant. I don't have any questions for them; nixpkgs could collaborate with other distributions to agree to follow those, but I generally don't ask others when I already know what to do, which I believe I have more than adequately explained. 

(The technical solution selected eventually is not of great interest to me personally. )

In a broader sense, the real legal fun (read: nightmare for anyone with telemetry and without a wall of legalese) begins when applying this to closed source products with telemetry. I hadn't considered this before, but if e.g. Chrome currently even collects one timestamp "to improve the product" they are probably breaching GDPR.

**Comment by justinlovinger** [comment]
I second mweinelt. Nixpkgs is not in the habit of modifying package defaults for users preferences. This is an upstream issue. As for legality, Nixpkgs is not legally responsible for the GDPR compliance of the packages it provides. _We_ are not storing any data packages may collect.

**Comment by hacscred** [comment]
@justinlovinger First if all this is not a democracy. 

Secondly, you are assuming that if the foundation doesn't collect the data, it's not doing anything wrong. There's no evidence of that assertion being true. 

Regardless, this is an issue that should be handled by the foundation, not by a maintainer.

**Comment by hacscred** [comment]
@joepie91, I am not saying such NixOS options could not be useful, but I argued that the "show it once" has no valid implementation, because you can't assume a single user account is used by just one user. Yes, I understand that everyone in tech would think that's "not how you so it", but there's no legal requirement to have multiple user accounts on a computer. 

So, while you might consider it to be a reasonable compromise the fact of the matter is that your legal opinion is clouded by too much technical experience about how things should be in some technological utopia. 

If the logical conclusion (which I might add was not disputed) is applied, the problem is solved in nixpkgs for the Firefox package or some Iceweasel variant until upstream breaks it. I already suggested the possibility of collaboration with other distributions. As such, your way of portraying me, is dishonest. 

What you are doing is expanding scope for an issue that's already complicated enough as it is. 

So, while you are claiming without proof that it's not productive my approach is goal directed; a single patch would turn it off for everyone and it would be solved for the next months. To automate it, I suspect even a LLM can modify the code given the right entry point to produce a patch to remove the telemetry. I also think it's not productive to discuss people being productive or not, especially given such a weak support for your position. 

I mentioned your name, because I thought it was relevant, but you don't seem to understand your judgement has been clouded by bias. I did imply that it's in principle a good thing that you engaged with them, but where you go wrong is that you speak as if your opinion holds legal value. If you do have an opinion consistent with the law, feel free to share it, but right now you are just being used as a tool by a large corporation despite thinking you are doing good. 

Mozilla will do whatever they can get away with and you basically give them an excuse to break the law and tell a judge in a decade "we thought it was OK and there was a discussion with users and even joepie, who we listened to and even removed the dark patterns. Aren't we good boys?". 

Let's say there's a shared NixOS installation in a retirement home and someone wants to look up a recipe for cookies using a browser. Let's further assume they have had some brain injury and can't even remember a password anymore. Do you think such people would actively consent to telemetry or go to the settings every single time to opt-out? Of course not.  

Telemetry has been the Wild West, but the party is over. 

Finally, it's not much of a fight, since nobody even challenged my line of reasoning.

**Comment by joepie91** [comment]
Well, if you insist on writing a long post of insults and accusations instead of taking my advice (as someone who is actually familiar with the processes here), then there's nothing left for me to do here.

I've told you how to get this problem solved effectively. If you choose to ignore that, that's your call, but then the consequences are also yours.

**Comment by K900** [comment]
Enough, y'all.
