### ISSUE TITLE
Build failure: liquibase

### ISSUE THREAD

**Issue by shyuen** [NixOS/nixpkgs#347153]
### Steps To Reproduce

1. Use a NixOS Flake that refrences the unstable branch build with `liquibase` as one of the `environment.systemPackages`.
2. Run a `nixos-rebuild switch`.
3. Get an error regarding `/nix/store/5qax6r6kxi4spn5bc7qjpgglxb9kvhxp-liquibase-4.29.2.drv`, please see Build log below.

### Build log

```
error: builder for '/nix/store/5qax6r6kxi4spn5bc7qjpgglxb9kvhxp-liquibase-4.29.2.drv' failed with exit code 1;
       last 3 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/v12lcsjxsq3n4lgi8za3k9mqc8pak59b-liquibase-4.29.2.tar.gz
       > unpacker produced multiple directories
       For full logs, run 'nix log /nix/store/5qax6r6kxi4spn5bc7qjpgglxb9kvhxp-liquibase-4.29.2.drv'.
error: 1 dependencies of derivation '/nix/store/0axj206cqqnd0kqd9qji9704yrrcc10c-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kb8yfknl9krrnxs6ddg5bzwk48501kcj-nixos-system-nixos-24.11.20241004.bc947f5.drv' failed to build
```

### Additional context

From what I can tell, there's no update to Liquibase since my system already has version `2.29.2` from an earlier `nixos-rebuild switch` that I ran last week.  I can confirm that removing `liquibase`  from `environment.systemPackages` allows me to update my system without errors.

### Notify maintainers

[John Soo](https://github.com/jsoo1) <[jsoo1@asu.edu](mailto:jsoo1@asu.edu)>

**Comment by Princemachiavelli** [comment]
Confirmed fixed in #346148, might take a few days to reach nixos-unstable. nixos-24.05 is not affected.
