### ISSUE TITLE
dhcpcd does not start if defaultGateway6 is set (18.03 regression)

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#34716]
## Issue description

```dhcpcd``` does not start if either ```defaultGateway``` or ```defaultGateway6``` is set statically:
https://github.com/NixOS/nixpkgs/blob/7fb90db6960832cf16fa806d6e59fc6ab3cd0456/nixos/modules/services/networking/dhcpcd.nix#L158-L163

On scaleway.com cloud, IPv4 address is assigned via DHCP while IPv6 should be configured statically.

Static ```defaultGateway6``` prevents ```dhcpcd``` to start and obtain IPv4 address.

@fpletz for https://github.com/NixOS/nixpkgs/commit/b1799084147b0b862eeffd7b4bb526de09fd34a5

**Comment by rnhmjoj** [comment]
How would you fix this? Add dhcpcd to the network-online target unless both `defaultGateway` and `defaultGateway6` or are you suggesting to revert this entirely?

**Comment by volth** [comment]
As a quick workaround, I just set ```systemd.services.dhcpcd.wantedBy = [ "network-online.target" ];``` in my configuration

It might be more accurate to check only ```defaultGateway``` without ```defaultGateway6``` (assuming IPv6 is either configured statically or may use other means for router discovery than DHCP)

**Comment by fpletz** [comment]
Fixed by #34716.
