### ISSUE TITLE
Package request: xp-pen-tablet

### ISSUE THREAD

**Issue by HangedFool** [NixOS/nixpkgs#347116]
**Project description**

XP-Pen (Official) Linux utility (New UI driver) Version 4.04

edit: I was confusing the source url, this should be the most up to date and correct

**Metadata**

* homepage URL: https://www.xp-pen.com
* source URL: https://download01.xp-pen.com/file/2024/08/XPPenLinux4.0.4-240815.tar.gz
* license: Proprietary
* platforms: unix, linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by HangedFool** [comment]
I saw that we currently have xp-pen-deco, the legacy driver, and xp-pen-g430-driver, the driver for the star series of tablets, but we don't have the modern tablet drivers

**Comment by gepbird** [comment]
Until someone packages it, you may want to try an open source alternative: OpenTabletDriver.

It supports [these](https://opentabletdriver.net/Tablets?search=xp-pen) XP-Pen devices.

To try it, put `hardware.opentabletdriver.enable = true;` in your config, rebuild and reboot.

**Comment by gepbird** [comment]
cc @virchau13 since you maintain a similar package

**Comment by HangedFool** [comment]
My tablet, an artist pro (gen 2), is not supported by OpenTabletDriver, but still, thanks for the suggestion. I am hopeful that someone will package it as it is the only package I use that is not on Nix (I currently am running nix in a vm, but I am hoping to make it my main distro when I have more free time to make the change)

**Comment by HangedFool** [comment]
I don't know if this would help, but I feel it may be helpful that this package is on the [AUR](https://aur.archlinux.org/packages/xp-pen-tablet). That being said, the one on the AUR is the 4.0.0 version not the 4.0.4 version, so it is not the most up to date.

**Comment by gepbird** [comment]
I'm attempting to package this, can you help me with getting the source?

The source url you provided gives an access denied for me: https://download01.xp-pen.com/file/2024/08/XPPenLinux4.0.4-240815.tar.gz

The download link from the AUR package works: https://www.xp-pen.com/download/file.html?id=2854&pid=1016&ext=gz

On their website https://www.xp-pen.com/download, there are many devices which have different downloads for the seemingly same software, some examples:
- https://www.xp-pen.com/download/artist-pro-19-gen-2.html: XPPenLinux4.0.4-240815.tar.gz (downloads)
- https://www.xp-pen.com/download/artist-22-plus.html: XPPenLinux3.4.9-240607.tar.gz (access denied)
- https://www.xp-pen.com/download/innovator-16.html: XPPenLinux3.4.9-240607.tar.gz (downloads)

Where can we download the most up-to-date driver?

**Comment by HangedFool** [comment]
Oh, sorry, It works for me so I don't know what's up what is up with that. That being said this [link](https://www.xp-pen.com/download/artist-pro-14-gen-2.html ) should take you to where the direct download is,just scroll down to "XPPenLinux4.0.4-240815.tar.gz"

**Comment by gepbird** [comment]
> Oh, sorry, It works for me so I don't know what's up what is up with that. That being said this [link](https://www.xp-pen.com/download/artist-pro-14-gen-2.html) should take you to where the direct download is,just scroll down to "XPPenLinux4.0.4-240815.tar.gz"

Thanks, I'll use that page as a reference when updating!
I assume you don't get access denied because you have an account.

**Comment by HangedFool** [comment]
Also, I haven't tested this yet, but a very kind person on [reddit](https://www.reddit.com/r/NixOS/comments/1g0q72t/how_hard_is_it_to_package_something_for_nix/) gave me this. I hope that it can be used to assist you.
--------------------------------------------------------------------------------------------------------------
Using the examples I've quickly thrown together a package that launches the UI at least. I can't test further since I don't have the hardware, so it may need additional wrappers like some of the other packages have.

```
{
  fetchzip,
  stdenvNoCC,
  autoPatchelfHook,
  makeWrapper,
  wrapQtAppsHook,
  libusb1,
}:
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "xp-pen-artist-pro-driver";
  version = "4.0.4-240815";

  src = fetchzip {
    # url = "https://www.xp-pen.com/download/file.html?id=3325&pid=990&ext=gz";
    url = "https://download01.xp-pen.com/file/2024/08/XPPenLinux${finalAttrs.version}.tar.gz";
    name = "xp-pen-artist-pro-driver";
    hash = "sha256-NVO9VaUmcQDI4rL76BBQDmII8vpmmo9qgcGetv6CIFE=";
  };

  postPatch = ''
    substituteInPlace App/etc/xdg/autostart/xppentablet.desktop App/usr/share/applications/xppentablet.desktop \
      --replace-fail "Exec=/usr/lib/pentablet/PenTablet.sh" "Exec=${placeholder "out"}/bin/PenTablet"

    substituteInPlace App/etc/xdg/autostart/xppentablet.desktop App/usr/share/applications/xppentablet.desktop \
      --replace-fail "Icon=/usr/share/icons/hicolor/256x256/apps/xppentablet.png" "Icon=xppentablet"
  '';

  nativeBuildInputs = [
    autoPatchelfHook
    wrapQtAppsHook
    makeWrapper
  ];

  dontBuild = true;
  dontWrapQtApps = false;

  buildInputs = [
    libusb1
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out/{opt,bin}
    cp -r App/usr/lib/pentablet/{conf,doc,UI} $out/opt
    cp -r App/lib $out/lib
    cp App/usr/lib/pentablet/PenTablet $out/bin
    cp -r App/usr/share $out

    runHook postInstall
  '';
})
```

Note that when building this package you have to use pkgs.libsForQt5.callPackage instead of pkgs.callPackage
