### ISSUE TITLE
Package request: vimPlugins.blink-cmp

### ISSUE THREAD

**Issue by Daholli** [NixOS/nixpkgs#347276]
**Project description**

blink.cmp is a completion plugin with support for LSPs and external sources while updating on every keystroke with minimal overhead (0.5-4ms async). It achieves this by writing the fuzzy searching in SIMD to easily handle >20k items. It provides extensibility via hooks into the trigger, sources and rendering pipeline. Plenty of work has been put into making each stage of the pipeline as intelligent as possible, such as frecency and proximity bonus on fuzzy matching, and this work is on-going.

**Metadata**

* homepage URL: https://github.com/Saghen/blink.cmp
* source URL: https://github.com/Saghen/blink.cmp
* license: MIT
* platforms: linux, darwin, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vinnymeller** [comment]
added MIT license to the proj FYI

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/348105
