### ISSUE TITLE
Update request: fwupd: 1.9.25 → 2.0.0

### ISSUE THREAD

**Issue by antonmosich** [NixOS/nixpkgs#347248]
- Package name: fwupd
- Latest released version: 2.0.0

- Current version on the unstable channel: 1.9.25
- Current version on the stable/release channel: 1.9.19

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@r-vdp 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by r-vdp** [comment]
Yeah, it's on my list, but it will take a bit more time because I need to adapt our nix expression to upstream the  changes.

**Comment by antonmosich** [comment]
Completed in #351772
