### ISSUE TITLE
The mixer doesn’t open on MuseScore

### ISSUE THREAD

**Issue by kugland** [NixOS/nixpkgs#347391]
### Describe the bug
It is not possible to open the mixer window in the latest version (4.4.2) of MuseScore in nixpkgs unstable. It seems to be some incompatibility with the Qt version.

### Steps To Reproduce
1. Open MuseScore.
2. Create a new score.
3. Try clicking on the button “Mixer.”

### Expected behavior
The Mixer should open normally.

### Notify maintainers

@doronbehar @vandenoever 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.32-hardened1, NixOS, 24.05 (Uakari), 24.05.20241004.6e6b3dd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - channels(user): `""`
 - nixpkgs: `/nix/store/ymskzig3is4dpkj43sa4q17vcsq0bf5b-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kugland** [comment]
https://github.com/musescore/MuseScore/issues/24885

**Comment by cbjeukendrup** [comment]
More specifically, this is logged as https://github.com/musescore/MuseScore/issues/24866; there is no fix for that issue yet, while the 4.4.3 release is already imminent, so most likely the fix will go into 4.5.

**Comment by cbjeukendrup** [comment]
It looks like this duplicates https://github.com/NixOS/nixpkgs/issues/343456

**Comment by doronbehar** [comment]
Thanks @cbjeukendrup for joining the discussion :). Indeed this is a duplicate and https://github.com/NixOS/nixpkgs/issues/343456 has a few more details there, so I'll close this.
