### ISSUE TITLE
Should INSTALL_BASE be used instead of PREFIX for buildPerlPackage?

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#34735]
I'm not too familiar with the perl ecosystem but as far as I can tell, things that have a Makefile.PL use MakeMaker, and the documentation says INSTALL_BASE is the more "PREFIX" of the two?:
http://search.cpan.org/~bingos/ExtUtils-MakeMaker-7.30/lib/ExtUtils/MakeMaker.pm#INSTALL_BASE

https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/perl-modules/generic/builder.sh#L28

**Comment by abathur** [comment]
Closing. Account gone and no other issue interactions.
