### ISSUE TITLE
Update request: svt-av1-psy 2.2.1 → 2.2.1-A

### ISSUE THREAD

**Issue by IncredibleLaser** [NixOS/nixpkgs#347481]
- Package name: svt-av1-psy
- Latest released version: 2.2.1-A
- Current version on the unstable channel: 2.2.1
- Current version on the stable/release channel: none
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Currently using the latest version using an overlay with the hash "sha256-oCs8ZSfiqmAv2go6fa51l/Kt2pb1qdvuHtACRT2xGrw=".

**Notify maintainers**
@JohnRTitor 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
PRs welcomed. Else I'll probably update it tomorrow.

**Comment by IncredibleLaser** [comment]
See https://github.com/NixOS/nixpkgs/pull/347543

**Comment by IncredibleLaser** [comment]
Of course, less than a day after, a new version is released (2.2.1-B).

Personally, I don't care too much about that update, as the improvements affect me little to none. Just wanted to mention it still.

**Comment by gianni-rosato** [comment]
I think it is probably worth updating for every major release of SVT-AV1-PSY. The new `--noise-norm-strength` is disabled by default for tunes 0, 1, 2, & 4, but enabled on Tune 3 and does (in my opinion) make a decent difference there

**Comment by gianni-rosato** [comment]
Gotcha, good to know the update system works that way.

You're right, I do use Arch - how'd you know? A close friend just recently switched to Nix and I was wondering if we were on there at all, and was pleasantly surprised to find this. Thanks for submitting SVT-AV1-PSY here!
