### ISSUE TITLE
R help.start() fails with 'invalid browser name, check options("browser").'

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#34748]
## Issue description

```
$ R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> help.start()
Error in help.start() : invalid browser name, check options("browser").
> options("browser")
$browser
[1] ""

```

## Technical details

    $ nix-shell -p nix-info --run "nix-info -m" -I nixpkgs=/home/mmchenry/git/nixos/nixpkgs
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.73, NixOS, 18.03.git.52d3c7d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-16.09pre78848.9549257"`
 - channels(mmchenry): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

(most recent upstream commit is f59a0f7f)

**Comment by jerith666** [comment]
cc @peti

**Comment by jerith666** [comment]
(I'm a total R newbie, just trying to run through the tutorial, sorry if I'm missing something obvious! :) )

**Comment by peti** [comment]
I think the error message pretty much says it all:

> Error in help.start() : invalid browser name, check options("browser").

So you might want to run `options(browser="firefox")` to set that value appropriately for your system. Personally, I use the following `~/.Rprofile` file:

~~~
.First <- function() {
    options(repos=structure(c(CRAN="http://cran.rstudio.com/")))
    options(browser="firefox")
    options(pdfviewer="evince")
    options(width=250)
    options(defaultPackages=c(getOption("defaultPackages"), "data.table"))
}
~~~

**Comment by jerith666** [comment]
Ah, yep, that fixed it.  I thought that it was expecting something it the environment or a system-wide config file to have specified the browser, and that this was a hole in the way R was packaged for nix.  Sorry for the false alarm, and thanks for the quick response!  :)

**Comment by coretemp** [comment]
@jerith666 If you want to improve the situation for users, you could file a request at the R developers, because this is just an awful user experience. We could patch R to do something intelligent and I *think* this is what Debian does, but it would be better if upstream R implemented something like if there is no browser set, use `xdg-open` on Linux.

**Comment by jerith666** [comment]
Their [bugtracker](https://bugs.r-project.org/bugzilla3/) is closed to outside submissions.  I sent the following message to their [mailing list](https://stat.ethz.ch/mailman/listinfo/r-devel), but it hasn't shown up yet.

```
         As a brand new R user, I recently tried following the instructions at https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Getting-help for how to get help.  I tried running help.start() and it failed with:

> help.start()
Error in help.start() : invalid browser name, check options("browser").
> options("browser")
$browser
[1] ""

        The output of 'options("browser")' looked very cryptic to me, so I tried the only thing I'd seen so far in the manual, which was:

> options("browser") <- "firefox"
Error in options("browser") <- "firefox" :
  target of assignment expands to non-language object

        For anyone even passably familiar with R, I'm sure that my mistake would be obvious, but getting from the above to the necessary invocation:

> options(browser="firefox")
> options("browser")
$browser
[1] "firefox"
> help.start()
starting httpd help server ... done
If the browser launched by 'firefox' is already running, it is *not*
    restarted, and you must switch to its window.
Otherwise, be patient ...

        ... was only accomplished by filing a misdirected bug report against my OS packager[1].

        The suggestion from the maintainer there, which seems like a good one to me, is to default to options(browser="xdg-open") on linux.

        A further suggestion is to replace the text 'invalid browser name, check options("browser")' with something like 'invalid browser name, use options(browser="firefox") to fix'.

        I'm not subscribed to the list, so if you need more info, please CC me on reply.
```
