### ISSUE TITLE
One-Click Installation bad link in documentation

### ISSUE THREAD

**Issue by razvan-flavius-panda** [NixOS/nixpkgs#34745]
See https://nixos.org/nix/manual/#sec-one-click

If you click on http://hydra.nixos.org/jobset/nixpkgs/trunk/channel/latest it shows:

![](https://i.imgur.com/e6OTkXq.png)

Does `One-Click Installation` still work? And what is the valid link for it?

**Comment by grahamc** [comment]
One click installations are an all-but-dead feature of Nix.

**Comment by razvan-panda** [comment]
@grahamc Should they be removed from the documentation then? I read about them from Nix Pills:

https://nixos.org/nixos/nix-pills/automatic-runtime-dependencies.html#idm140737316135584

**Comment by grahamc** [comment]
Indeed! Let's leave this ticket open to help cover that.

**Comment by iFreilicht** [comment]
I think this is still important. I just read about this in Nix Pills as well and wanted to learn more. It sounded like an interesting alternative to flatpak/appimage/snap. If this feature has been dead for over two years, it should be at least removed from Nix Pills.

**Comment by iFreilicht** [comment]
@razvan-flavius-panda I think you can close this issue. The stable manual does not mention one-click installation anymore.

**Comment by jtojnar** [comment]
This was fixed in Nix manual by https://github.com/NixOS/nix/commit/15c035c13f3c452ffef3960e97bd0e9b38d98ec2 but we still need to remove it from nix-pills: https://github.com/NixOS/nix-pills/pull/184
