### ISSUE TITLE
Package request: OpenAudible

### ISSUE THREAD

**Issue by Brojan96** [NixOS/nixpkgs#347502]
**Project description**

A cross-platform desktop application for downloading and managing your Audible audiobooks.

**Metadata**

* homepage URL: https://openaudible.org/
* source URL: https://github.com/openaudible/openaudible/releases
* license: Apache License Version 2.0
* platforms: linux, macos, windows

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Shawn8901** [comment]
There is that https://github.com/kurogeek/nix-openaudible which might already help you. as far as i can see the github repo just contains an out of source version (see readme in the openaudible repo and the hint in my linked repo)

**Comment by quatquatt** [comment]
There's some relevant context [here](https://github.com/kurogeek/nix-openaudible/issues/1#issuecomment-2241986000).

I had a bad experience getting OpenAudible working, while Libation worked perfectly for me. If there is real demand for adding OpenAudible, we could do it, but I feel it may not be worth the effort, when from my understanding Libation is a far better alternative.

**Comment by Shawn8901** [comment]
Tested out Libation, which is definitely a nice looking tool and is also already in nixpkgs

**Comment by Brojan96** [comment]
Didn't know about libation, I will take a look at it.
