### ISSUE TITLE
Update request: gitea 1.22.2 → 1.22.3

### ISSUE THREAD

**Issue by jlbribeiro** [NixOS/nixpkgs#347508]
- Package name: **gitea**
- Latest released version: **1.22.3** (**[GitHub release](https://github.com/go-gitea/gitea/releases/tag/v1.22.3)**, **[compare to v1.22.2](https://github.com/go-gitea/gitea/compare/v1.22.2...v1.22.3)**)

- Current version on the unstable channel: **1.22.2**
- Current version on the stable/release channel: **1.21.11**

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@ma27 @techknowlogick @SuperSandro2000

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
It would be appreciated if you could open a PR right away :)

**Comment by jlbribeiro** [comment]
@SuperSandro2000 Apologies, that was my intent as soon as I arrived to my personal laptop, just wanted to ensure it got tracked (as it contains a security fix).

**Comment by jlbribeiro** [comment]
(just saw you've added the security + backport labels, appreciated :) )
