### ISSUE TITLE
Update request: libtorch-bin 2.3.0 → 2.4.1

### ISSUE THREAD

**Issue by DaniD3v** [NixOS/nixpkgs#347512]
- Package name: `libtorch-bin`
- Latest released version: `2.4.1`

- Current version on the unstable channel: `2.3.0`
- Current version on the stable/release channel: `2.3.0`

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@junjihashimoto 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Luz** [comment]
Hi,
I've seen there is version 2.5.0 and I've just blindly updated the hashes, now the package builds, but I did not test it yet.
https://github.com/Luz/nixpkgs/tree/libtorch-bin
Do you know how to check if its working well? I saw there is a test file, but I have no clue at how to run it.

**Comment by junjihashimoto** [comment]
https://github.com/NixOS/nixpkgs/pull/350526

**Comment by DaniD3v** [comment]
> Do you know how to check if its working well?

Nope sorry I don't actually need it anymore.
Thanks for updating anyways tho!

I'll close this for now.
