### ISSUE TITLE
/etc/nix/path is not generated by nixos-rebuild

### ISSUE THREAD

**Issue by voidzero** [NixOS/nixpkgs#347607]
### Describe the bug

My system builds and boots correctly from my flake, but `/etc/nix/path` is not generated, and as a consequence scripts that have `#!nix-shell -I /etc/nix/path` do not work anymore.

### Steps To Reproduce
1. `nixos-rebuild build --flake '.#'`
2. `ls result/etc/nix/`
3. Output as follows: `nix.conf  registry.json`

### Expected behavior
The path /etc/nix/path directory should exist, and it should contain symlinks to /etc/static/nix/path, that point to the right path to the nix store. Example:

```
~ $ ls -1l /etc/static/nix/path/
total 6
lrwxrwxrwx 2 root root 50 Jan  1  1970 agenix -> /nix/store/5mg8m013dk1dv3sl934ki6nbldgv23yf-source
lrwxrwxrwx 2 root root 50 Jan  1  1970 hardware -> /nix/store/mad6lfrg6hd540gfgiy15xa5fcgh9g1a-source
lrwxrwxrwx 2 root root 50 Jan  1  1970 home-manager -> /nix/store/hxhym8c5xz6dxkl3d9yppiwlnzk3khn7-source
lrwxrwxrwx 2 root root 50 Jan  1  1970 nixpkgs -> /nix/store/1h99qq6970gkx3j0m9w4yrrl9y99y1nk-source
lrwxrwxrwx 2 root root 50 Jan  1  1970 nixpkgs-unstable -> /nix/store/887hpp8a2i99n9jjwcvz6qkhhhqsvzkg-source
lrwxrwxrwx 2 root root 50 Jan  1  1970 self -> /nix/store/h1a05n4cwxmqljjbfy58pakkvaadis7p-source
```

### Additional context
NixOS 24.05 x86_64-linux

The error below, `cannot remove '/tmp/env-vars': Operation not permitted`, is also a new thing that started to occur on all iterations of nix-shell. That file is mode 700 and owned by root. A bug for it was filed here: https://github.com/NixOS/nix/issues/11470

### Notify maintainers

@Profpatsch 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
install: cannot remove '/tmp/env-vars': Operation not permitted
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.53-hardened1, NixOS, 24.05 (Uakari), 24.05.20241006.ecbc1ca`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/5cypwijbjdxmr4i7ckpq1in7f09547fc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by voidzero** [comment]
As a workaround I wrote a script that generates these based on the info from the file that is being sourced by /etc/profile:

```zsh
#!/usr/bin/env zsh

umask 022

if [[ -d /etc/nix/path ]]
then
        echo "Directory /etc/nix/path already exists."
        exit 1
fi

# Obtain NIX_PATH
NIX_PATH_LINE=$(grep -m1 NIX_PATH $(awk '/nix\/store\S+set-environment/ {print $2}' /etc/profile))

# Extract the value of NIX_PATH
NIX_PATH_VALUE=${NIX_PATH_LINE#*NIX_PATH=}
NIX_PATH_VALUE=${NIX_PATH_VALUE//\"/}  # Remove the double-quotes

mkdir -p /etc/nix/path

# Function that creates symlinks
create_symlink() {
    local name=$1
    local path=$2
    if [[ -n $path ]]; then
        # we need the path to ln, probably because /tmp/env-vars is a read-only file that cannot be read/deleted by nix-shell atm.
        /run/current-system/sw/bin/ln -sfn "$path" "/etc/nix/path/$name"
        echo "Symlink created: /etc/nix/path/$name -> $path"
    fi
}

# Iterate over every component in NIX_PATH
echo $NIX_PATH_VALUE | tr ':' '\n' | while read -r component; do
    name=${component%%=*}
    path=${component#*=}
    create_symlink "$name" "$path"
done

echo "Symlink creation complete."
```

**Comment by hacscred** [comment]
Can you quote the documentation where it says that any guarantee is made regarding /etc/nix/path?

**Comment by voidzero** [comment]
I searched and searched, but no, I can't. But thanks for letting me do that. I now see that I have set that path in my old flake setup, and when migrating my old flake over to a new flake, I neglected to add this to the new flake setup.

Beg your pardon, thanks for your time and I'll close this bug.
