### ISSUE TITLE
Update request: pydantic 2.8.2 → 2.9.2

### ISSUE THREAD

**Issue by josh-newman** [NixOS/nixpkgs#347628]
- Package name: pydantic
- Latest released version: 2.9.2

- Current version on the unstable channel: 2.8.2
- Current version on the stable/release channel: 2.6.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@wd15 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
part of https://github.com/NixOS/nixpkgs/pull/345326

**Comment by josh-newman** [comment]
Thanks. I'm not familiar with nixpkgs updates but I'm happy to close this issue and follow that PR if that simplifies things.

**Comment by kirillrdy** [comment]
you can keep it open, until it reaches master, otherwise maybe some one else will create similar issue
