### ISSUE TITLE
ec2-data: /etc/ssh owned by "755"

### ISSUE THREAD

**Issue by basbebe** [NixOS/nixpkgs#347672]
### Describe the bug
#340489 seems to have introduced two lines that apply a `chown` where a `chmod` seems to have been intended.

This makes VMs using that module unavailable via SSH since permissions are incorrect.

### Steps To Reproduce
1. Build NixOS config using unstable branch and ec2-data (e.g. openstack-config)
2. Switch
3. check permissions of `/etc/ssh`

### Expected behavior
`/etc/ssh` and `root/.ssh` should be owned by root and have permissions of 0755 / 0700

### Notify maintainers

@r-vdp 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by r-vdp** [comment]
Oh that's my fault, I'll make a PR to fix that. Thanks for reporting.

**Comment by WilliButz** [comment]
> Authentication refused: bad ownership or modes for directory /etc/ssh

Quoting the sshd log message in case anyone else is looking for why they locked themselves out of their boxes

**Comment by arianvp** [comment]
Thanks for the fix
