### ISSUE TITLE
Keycloak upgrade needs a "build" before it'll work

### ISSUE THREAD

**Issue by dkowis** [NixOS/nixpkgs#347658]
### Describe the bug

I have keycloak installed from nixpkgs, and when the version upgraded, it no longer starts, because it wants another `kc.sh build`

### Steps To Reproduce
1. install keycloak
2. have keycloak update without changing any options (but stuff within keycloak changed)
3. keycloak no longer starts :(

### Expected behavior
Keycloak should start.

### Screenshots
Keycloak changed some of it's settings, and it needs a new build, and I'm not sure how to force it:
```
Oct 09 22:45:34 keycloak keycloak-start[72858]: The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.db, kc.http-relative-path
```

### Notify maintainers

@ngerstle
@talyz 
@NickCao 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.05 (Uakari), 24.05.20241007.1bfbbbe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/a2gnsay8asfn2kqghz12nhw196cnmf8h-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dkowis** [comment]
Maybe get it to 26, since that's supposed to be supported longer, as per their [blog](https://www.keycloak.org/2024/10/release-updates) I know that's way more than a backport, but it gets us to "their stable" and should be less disruptive.

**Comment by NickCao** [comment]
> Maybe get it to 26

That would certainly breaks the system of everyone using hostname v1.

**Comment by NickCao** [comment]
Closed via https://github.com/NixOS/nixpkgs/pull/323480
