### ISSUE TITLE
furnace: missing zenity/kdialog dependency

### ISSUE THREAD

**Issue by mrtnvgr** [NixOS/nixpkgs#347757]
### Describe the bug

Can't save in furnace if zenity or kdialog is not installed.

### Steps To Reproduce
1. Run furnace without zenity or kdialog installed

### Expected behavior
Zenity or kdialog should be given to the furnace, based on which DE is installed (in case of WMs, the smallest thing)

### Screenshots
![20241010_22h24m06s_grim](https://github.com/user-attachments/assets/f6b1f156-f449-433b-a7c0-ffdf7fa984a9)

### Additional context

...

### Notify maintainers

@OPNA2608 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41-rt37, NixOS, 24.11 (Vicuna), 24.11.20240728.52ec9ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(user): `""`
 - nixpkgs: `/nix/store/bcghcr9qwqmanpds017w75mcqda4fgab-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by OPNA2608** [comment]
> Can't save in furnace if zenity or kdialog is not installed.

You can use the built-in file dialogue, the error tells you how to switch to it.

> Zenity or kdialog should be given to the furnace, based on which DE is installed (in case of WMs, the smallest thing)

This is just not possible unless we make separate `furnace` packages for wrapping with zenity or wrapping with kdialog. And if we do that, then you would need to check every package you install that uses a mechanism like this to make sure you've installed the variant matching your environment.

I can ask on Matrix, but I think usually the package maintainer just picks one of the two, i.e. zenity, and makes that the only option. Our DEs don't seem to install zenity/kdialog either? :confused:
