### ISSUE TITLE
Build failure: lua-language-server-3.11.1 x86_64-darwin

### ISSUE THREAD

**Issue by khaneliman** [NixOS/nixpkgs#347742]
### Steps To Reproduce

1. build lua-language-server on x86_64-darwin

### Build log

```
       > FAILED: luamake
       > ditto build/macos/bin/bootstrap luamake 1>/dev/null
       > /bin/sh: ditto: command not found
       > [36/37] Copy bee.lua/bootstrap/main.lua build/macos/bin/main.lua
       > FAILED: build/macos/bin/main.lua
       > ditto bee.lua/bootstrap/main.lua build/macos/bin/main.lua 1>/dev/null
       > /bin/sh: ditto: command not found
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/hfqhaqnbjzhiy01b412jgivvphjriax1-lua-language-server-3.11.1.drv'.
```

### Additional context

Discovered in downstream test https://github.com/nix-community/nixvim/pull/2399

### Notify maintainers

@figsoda @gepbird @sei40kr 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment]
Hmm.. might just be a remote builder issue. I was just able to run the build on my macbook.

**Comment by gepbird** [comment]
I'm not sure why it can't find ditto, it is marked as a build input.

But something is definitely not right, on hydra it times out after 2h 37m when running bee.lua tests: https://hydra.nixos.org/build/274693787.
Previous successful builds took 1-2 minutes.

I don't have a darwin machine to test with, should we disable tests?

**Comment by khaneliman** [comment]
Might want to just disable tests on darwin until a better solution is found.

**Comment by khaneliman** [comment]
@gepbird Gonna close this, it seems like it was a transient issue on hydra and my replication of the errors were from weirdness with it having an impure dependency and remote building. https://hydra.nixos.org/build/274929146
