### ISSUE TITLE
[request] vlc 3.0

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#34774]
## Issue description

VLC 3.0 is out: https://www.videolan.org/vlc/releases/3.0.0.html

Would be nice to have it in nixpkgs, can't say if it makes sense to make it "default" or just optional for now, but either way!

**Comment by nico202** [comment]
See #35124

**Comment by gnidorah** [comment]
Also https://github.com/NixOS/nixpkgs/pull/39037

**Comment by lheckemann** [comment]
#35124 is merged, so I believe this can be closed.
