### ISSUE TITLE
Package request: mdpls

### ISSUE THREAD

**Issue by Daholli** [NixOS/nixpkgs#347794]
**Project description**

mdpls is a [language server](https://microsoft.github.io/language-server-protocol/) that provides a live HTML preview of your markdown in your browser.

mdpls is powered by [aurelius](https://github.com/euclio/aurelius), which also powers [vim-markdown-composer](https://github.com/euclio/vim-markdown-composer).

**Metadata**

* homepage URL: https://github.com/euclio/mdpls
* source URL: https://github.com/euclio/mdpls
* license: Default Gihub Licence
* platforms: all

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by llakala** [comment]
Seems to already exist here: 
https://github.com/NixOS/nixpkgs/issues/313749

**Comment by Daholli** [comment]
Alright closing this issue
