### ISSUE TITLE
Python applications to fix before release

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#34775]
## Issue description

Certain Python applications keep breaking on Unstable because they pin their dependencies. This requires effort to fix each and every time. Unless someone steps up for it, it seems like a better solution to simply mark them as broken until we approach a NixOS release and the Python package set has stabilized again.

## List of packages

- flexget (https://github.com/NixOS/nixpkgs/pull/34771)
- mitmproxy

**Comment by rnhmjoj** [comment]
Is there is still no way to make python ignore the version pinning?

**Comment by rnhmjoj** [comment]
Would you accept something like this
```
patchPhase = ''
  sed 's/>=\([0-9]\.\?\)\+\( \?, \?<\([0-9]\.\?\)\+\)\?//' -i setup.py
'';
```

mitmproxy builds and passes all the tests once the constaints are removed.

**Comment by FRidh** [comment]
@rnhmjoj that's something for in https://github.com/NixOS/nixpkgs/issues/21278.

**Comment by FRidh** [comment]
Note the intention of this issue is to be more general, it is not just due to the pinning.

**Comment by FRidh** [comment]
18.03 has been released, closing.
