### ISSUE TITLE
Update flexget

### ISSUE THREAD

**Issue by tari** [NixOS/nixpkgs#34785]
## Issue description

Flexget is currently broken. Per #34775, it should be updated before the next release. I did some work to update it for the current breakage, but stalled on hitting test failures.

I had to unpin a number of dependencies (which will likely change before the next nix release anyway). The functionality of `pytest-catchlog` is now built in to pytest, so `pytest-catchlog` should no longer be a build input.

**Comment by Ma27** [comment]
see #34775 
I tried to fix it some weeks ago, however I failed due to several weird test failures as well.
