### ISSUE TITLE
Package request: totp-cli

### ISSUE THREAD

**Issue by rlue** [NixOS/nixpkgs#347820]
**Project description**

CLI OTP client written in Go, 

**Metadata**

* homepage URL: https://yitsushi.github.io/totp-cli/
* source URL:https://github.com/yitsushi/totp-cli
* license: MIT
* platforms: linux, darwin, etc.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #348086
