### ISSUE TITLE
Update request: discord 0.70 → 0.71

### ISSUE THREAD

**Issue by 0JAY0** [NixOS/nixpkgs#347858]
Package name: discord
Latest released version: 0.0.71
Current version on the unstable channel: 0.0.70
Current version on the stable/release channel: 0.0.67
Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Notify maintainers
@Scrumplex
@Artturin
@jopejoe1

**Comment by Scrumplex** [comment]
Seems like our update scripts are broken as Discord changed their CDN urls. I will push a PR in a moment with the update URLs and update scripts
