### ISSUE TITLE
ghcjs fails to build

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#34783]
## Issue description

GHCJS doesn't compile, it hangs at the dependency `semigroups`:

```
installing 'ghcjs-0.2.0'
these derivations will be built:
[...]
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/9g6r044s7dcya8ah1f72x4j7c64p4p9z-system-filepath-0.4.14 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/jqyjhi63hrzgdqqiqwib89kf0gcgnb85-system-filepath-0.4.14-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-system-filepath-0.4.14.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/9g6r044s7dcya8ah1f72x4j7c64p4p9z-system-filepath-0.4.14/lib/ghc-7.10.3/system-filepath-0.4.14 --enable-split-objs --disable-library-profiling --disable-executable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-lib-dirs=/nix/store/ddg0a5z77y6c98490hpm7jnx04f5h9na-ncurses-6.0-20171125/lib --extra-lib-dirs=/nix/store/b13jslrp58nx88jzy1yv28ffh2qdnnh0-gmp-6.1.2/lib --extra-lib-dirs=/nix/store/ddg0a5z77y6c98490hpm7jnx04f5h9na-ncurses-6.0-20171125/lib
Configuring system-filepath-0.4.14...
Setup: At least the following dependencies are missing:
semigroups >=0.11 && <0.19

builder for ‘/nix/store/3n0zx6slc27zf8kf6yi9xj5bzzmw6i76-system-filepath-0.4.14.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/6vp59h2yr38iywx8lnpckrni6x9kfcjw-ghcjs-0.2.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6vp59h2yr38iywx8lnpckrni6x9kfcjw-ghcjs-0.2.0.drv’ failed
```

### Steps to reproduce

Go to a directory with nixpkgs at nixos-unstable. Run `nix-env -f . -iA haskell.compiler.ghcjs`.

## System details

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.1.39, NixOS, 18.03.git.5452697 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5732_fd10f6f2`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`
 - channels(turion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by shlevy** [comment]
What does this error message have to do with `contravariant`?

**Comment by turion** [comment]
@shlevy right, nothing, it seems. Don't know, I could swear there was an issue with `contravariant` before. Edited, thanks.

**Comment by crisoagf** [comment]
I'm not sure how the haskell stack fully works in NixOS, so I may be barking at the wrong tree here, but I believe the issue is with cabal2nix, that, for some reason, is not listing semigroups in the dependencies of system-filepath. (Perhaps because of a missing "--compiler" flag, as referred in  NixOS/cabal2nix#257 ?)

**Comment by turion** [comment]
@crisoagf I don't fully understand it, but I believe this is just because `semigroups` got merged into `base` starting with GHC 8, and maybe `ghcjs` used to be `7.10.*` still. (That this situation would cause a problem still shows that something is wrong, but it's not so clear what.) Either way, there is now `ghcjs-8.2.0.1` in `nixos-unstable`, so I think this can be closed.
