### ISSUE TITLE
Update request: `gnome-shell` 46.4 → 46.5

### ISSUE THREAD

**Issue by Anifyuli** [NixOS/nixpkgs#347838]
- Package name: gnome-shell
- Latest released version: 46.5

- Current version on the unstable channel: 46.4
- Current version on the stable/release channel: 46.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@bobby285271 @hedning @jtojnar @dasj19

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
We are working on GNOME 47 bump in #333911, we do not have the resources to bump to 46.5.
