### ISSUE TITLE
Using prebuilt CLR binaries?

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#34781]
I'm trying to run a binary built using dotnet/CLR, and when running the binary I get the following errors:
```
Failed to load ��U, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/nix/store/2mg9396a7bgpiqk77v0j28pipnn8isc8-boxcli-1.1.1/lib/libcoreclr.so'
```
Is there a Nixpkgs package that contains libunwind.so.8? 
Doing
```shell
patchelf --set-rpath ${lib.makeLibraryPath [libunwind]} $out/lib/box
```
did not work for me. (And, looking around the package in /nix/store, I can't seem to find the `so.8` file anywhere.)

**Comment by FRidh** [comment]
You could use https://github.com/bennofs/nix-index to search for the library.

**Comment by jb55** [comment]
I was able to package a .NET core program here: https://gist.github.com/jb55/b8b49893e18b61fb8c3ea3c924358278#file-default-nix-L9

I'm also building a tool to automate this: https://github.com/jb55/dotnet2nix which is still a work in progress

**Comment by jonringer** [comment]
probably not relevant anymore, but you will most likely need to do `dontPatchelf = true;` as well, otherwise the fixup phase may affect it.
