### ISSUE TITLE
Formalize creation of the stdenv team

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#347955]
Rather than having people just jump in and do whatever with stdenv, it might be best to have a team dedicated to reviewing PR's, improving, and maintaining the stdenv and the core logic behind it.

## Why not wait for the Steering Committee?

Because this is just focusing on the creation, all work involving the actual organization is something the SC should be involved in. I'm only looking for the team to be created.

## What files are relevant?

Mainly files in `pkgs/stdenv` and `lib/systems`.

## Who can join?

Anyone who is wanting to be involved in the work with stdenv is open.

## Who owns the stdenv team?

For now, whoever creates the team will own it until the SC is able to figure that out. If they wish for the original creator to still own the team, that is fine..

## What about existing PR's touching stdenv?

The hope is the stdenv team will work through these. It may be up to the SC to decide how to prioritize. Until then, I guess the stdenv will discuss amongst each other to work out what should be worked on.

## Where would discussion and work take place?

[#stdenv:nixos.org](https://matrix.to/#/#stdenv:nixos.org) on Matrix.

## CC on raising awareness amongst people who have had prior involvement 

@Mic92 @philiptaron @Ericson2314 @vcunat @sternenseemann @reckenrode

**Comment by RossComputerGuy** [comment]
A PR has been made to add the team into nixpkgs: #347959

**Comment by vcunat** [comment]
I believe I'm over-committed already.

**Comment by RossComputerGuy** [comment]
Good

**Comment by philiptaron** [comment]
As https://github.com/NixOS/nixpkgs/pull/347959 is merged, I think this now is complete. Please re-open if you think there are additional things to do!
