### ISSUE TITLE
buildGoModule workspace support

### ISSUE THREAD

**Issue by HannesGitH** [NixOS/nixpkgs#347998]
**Project description**

`go` supports `go.work` workspaces and with normal go everything works fine, but i cant figure out how to `buildGoModule` within a workspace as the dependencies are defined in the `go.work` and not the `go.mod` of each module..

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tomodachi94** [comment]
This appears to be a duplicate of https://github.com/NixOS/nixpkgs/issues/347998. Please reopen this issue if I am incorrect.

**Comment by HannesGitH** [comment]
@tomodachi94 could you please link the correct issue, this is a duplicate of? cou currently linked it to itself ;D
