### ISSUE TITLE
cheat: incorrect zsh completion functions

### ISSUE THREAD

**Issue by rennsax** [NixOS/nixpkgs#347925]
### Describe the bug

The Zsh completion function provided by [cheat/cheat](https://github.com/cheat/cheat) upstream has some problem. I address it in [cheat/cheat#756](https://github.com/cheat/cheat/pull/756) but the maintainer has not replied yet.

Should we fix the problem in Nixpkgs side? So long I've used [an overlay](https://github.com/rennsax/dotfiles/blob/a557a43e4ab04061e59f1d1e055399c22a21863c/overlays/default.nix#L3-L5) to achieve this.

### Notify maintainers

@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/7pj89i5nz4c3w983d759likgf47grmn6-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mic92** [comment]
We can have this patch in nixpkgs. Just make a prs

**Comment by rennsax** [comment]
I will. One question: which way do you suggest to add the patch? A plain patch file with conventional name, or via `fetchpatch`?

**Comment by Mic92** [comment]
Fixed https://github.com/NixOS/nixpkgs/pull/347943
