### ISSUE TITLE
Libreoffice `.desktop` files not installed in user environment

### ISSUE THREAD

**Issue by samdroid-apps** [NixOS/nixpkgs#34806]
## Issue description

The libreoffice `.desktop` files do not appear to be properly installed in the user path.  This creates the following problems:

* Libreoffice not listed in the gnome shell overview
* can not use the "open with" libreoffice feature, for example to open a download in firefox

### Steps to reproduce

Add `libreoffice-fresh` to user environment

Open gnome shell overview, notice libreoffice is not listed

## Analysis

Running `find` on the environment, we can see that libreoffice's desktop files are not linked into the environment:

```
> find /etc/per-user-pkgs/sam/share | grep office
/etc/per-user-pkgs/sam/share/gsettings-schemas/collected-for-libreoffice
/etc/per-user-pkgs/sam/share/gsettings-schemas/collected-for-libreoffice/glib-2.0
/etc/per-user-pkgs/sam/share/gsettings-schemas/collected-for-libreoffice/glib-2.0/schemas
/etc/per-user-pkgs/sam/share/icons/soffice.ico
```

Visiting the libreoffice path (aka `cd $(dirname $(readlink $(which libreoffice)))`), we can see that `/share/applications` is linked to `/lib/libreoffice/share/xdg`.  That contains the expected `.desktop` files.

However, these files are never linked into the user environment.

I believe that the [buildenv builder](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/builder.pl) is broken by `applications` being a symlink, as it iterates over the whole collection of files with their real paths (rather than with the symlink).  But I'm not amazing with perl; so that is just speculation.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.2961.3d985c45905 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(sam): `""`
 - channels(root): `"nixos-17.09.2961.3d985c45905"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
On 6c064e6b1f3, I can see the desktop files under `~/.nix-profile/share/applications` when I install LibreOffice using `nix-env -f '<nixpkgs>' -iA libreoffice-fresh`:

```
$ la ~/.nix-profile/share/applications/ | grep libreoffice
lrwxrwxrwx  1 root root   95 Jan  1  1970 base.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/base.desktop
lrwxrwxrwx  1 root root   95 Jan  1  1970 calc.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/calc.desktop
lrwxrwxrwx  1 root root   95 Jan  1  1970 draw.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/draw.desktop
lrwxrwxrwx  1 root root   98 Jan  1  1970 impress.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/impress.desktop
lrwxrwxrwx  1 root root   95 Jan  1  1970 math.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/math.desktop
lrwxrwxrwx  1 root root   97 Jan  1  1970 qstart.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/qstart.desktop
lrwxrwxrwx  1 root root  102 Jan  1  1970 startcenter.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/startcenter.desktop
lrwxrwxrwx  1 root root   97 Jan  1  1970 writer.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/writer.desktop
lrwxrwxrwx  1 root root  101 Jan  1  1970 xsltfilter.desktop -> /nix/store/aigkflj6qimc6gl3naqwx7xk1np99ipz-libreoffice-6.0.2.1/share/applications/xsltfilter.desktop
```

I can see them in the GNOME Shell Applications menu as well. What is missing, however, are icons. I suppose that is because the expression [replaces](https://github.com/NixOS/nixpkgs/blob/f148c5c4a1ffa353836bfd18a94d457acf83bd36/pkgs/applications/office/libreoffice/default.nix#L187) `Icon=libreofficedev6.0-`, while the files contain `Icon=libreoffice6.0-`.

cc @7c6f434c

**Comment by jtojnar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/1cb0cfba0197e305a39fdafc92f4d8e6d5f220a3#diff-59f30d5fac3f23fc5d24fd476803c5beR187
