### ISSUE TITLE
Update request: lenovo-legion 0.0.12 → current master

### ISSUE THREAD

**Issue by CHN-beta** [NixOS/nixpkgs#348022]
- Package name: lenovo-legion-app & lenovo-legion-module
- Latest released version: 0.0.18, but a patch in master is needed for kernel 6.11

- Current version on the unstable channel: 0.0.12
- Current version on the stable/release channel: 0.0.12

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

@ulrikstrid 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CHN-beta** [comment]
Simply updating src does not work, `substituteInPlace` in `postPatch` will fail.

**Comment by i-am-logger** [comment]
i'll try to work on it... the v0.0.18 isn't a release yet... 

i started to expedrience ```/build/source/kernel_module/legion-laptop.c:6058:19: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
       >  6058 |         .remove = legion_remove,```

**Comment by i-am-logger** [comment]
https://github.com/NixOS/nixpkgs/pull/348177

**Comment by CHN-beta** [comment]
> no kernel 6.11 patch yet...

This issue seems has been resolved on current master, through this pr: https://github.com/johnfanv2/LenovoLegionLinux/pull/251

**Comment by i-am-logger** [comment]
awesome, missed that. well... i made the PR for 0.0.18

I wonder why my nix patch didn't work as I did the same...
