### ISSUE TITLE
Update request: littlegptracker 0-unstable-2020-11-26 → 1.4.2

### ISSUE THREAD

**Issue by mrtnvgr** [NixOS/nixpkgs#348275]
**Littlegptracker has been forked by [djdiskmachine](https://github.com/djdiskmachine/littlegptracker).**
It's being actively maintained and promises not to introduce breaking changes.
I don't insist on this fork, but I'm informing you about it :)

- Package name: `littlegptracker`
- Latest released version: _1.4.2_
- Current version on the unstable channel: `0-unstable-2020-11-26`
- Current version on the stable/release channel: `0-unstable-2020-11-26`
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@fgaz

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fgaz** [comment]
Yes I'm aware, I actually helped a bit with the forking process. I was waiting for [some licensing stuff](https://github.com/NixOS/nixpkgs/issues/81815#issuecomment-1907882336) before switching the package. That's all cleared up now, so I'll make the change soon. Thanks for the reminder!
