### ISSUE TITLE
patch code-cursor to remove double window header

### ISSUE THREAD

**Issue by poyhen** [NixOS/nixpkgs#348282]
### Describe the bug
![image](https://github.com/user-attachments/assets/39139e1c-f867-4b35-95dd-d8ed611b1254)
https://github.com/getcursor/cursor/issues/837

### Steps To Reproduce
1. run cursor (possibly on gnome)

### Expected behavior
to not have the extra gnome header
![image](https://github.com/user-attachments/assets/89301ea0-8b56-41c7-ba94-674bf22f9068)

### Additional context
i am new to nix and tried to modify the package.nix for code-cursor. i achieved to patch it according to instructions on (https://github.com/getcursor/cursor/issues/837#issuecomment-2326443145) but i failed to update the update script to match url and outputHash 

here is my package.nix
```
{
  lib,
  stdenvNoCC,
  fetchurl,
  appimageTools,
  makeWrapper,
  writeScript,
}:
let
  pname = "cursor";
  version = "0.41.3";
  appKey = "230313mzl4w4u92";
  src = appimageTools.extract {
    inherit pname version;
    src = fetchurl {
      url = "https://download.todesktop.com/230313mzl4w4u92/cursor-0.41.3-build-240925fkhcqg263-x86_64.AppImage";
      hash = "sha256-WtfyiNGnUn8g1HR0TQPyn3SMJmjqe+otAYeyokMIO+w=";
    };

    #workaround for https://github.com/getcursor/cursor/issues/837
    postExtract = ''
      substituteInPlace $out/resources/app/out/vs/code/electron-main/main.js \
        --replace ',minHeight' ',frame:false,minHeight'
    '';
  };
in
stdenvNoCC.mkDerivation {
  inherit pname version;

  src = appimageTools.wrapAppImage { inherit version pname src; };

  nativeBuildInputs = [ makeWrapper ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out/
    cp -r bin $out/bin

    mkdir -p $out/share/cursor
    cp -a ${src}/locales $out/share/cursor
    cp -a ${src}/resources $out/share/cursor
    cp -a ${src}/usr/share/icons $out/share/
    install -Dm 644 ${src}/cursor.desktop -t $out/share/applications/

    substituteInPlace $out/share/applications/cursor.desktop --replace-fail "AppRun" "cursor"

    wrapProgram $out/bin/cursor \
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}} --no-update"

    runHook postInstall
  '';

  passthru.updateScript = writeScript "update.sh" ''
    #!/usr/bin/env nix-shell
    #!nix-shell -i bash -p curl yq coreutils gnused common-updater-scripts
    set -eu -o pipefail
    latestLinux="$(curl -s https://download.todesktop.com/${appKey}/latest-linux.yml)"
    version="$(echo "$latestLinux" | yq -r .version)"
    filename="$(echo "$latestLinux" | yq -r '.files[] | .url | select(. | endswith(".AppImage"))')"
    url="https://download.todesktop.com/${appKey}/$filename"
    currentVersion=$(nix-instantiate --eval -E "with import ./. {}; code-cursor.version or (lib.getVersion code-cursor)" | tr -d '"')

    if [[ "$version" != "$currentVersion" ]]; then
      hash=$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url "$url")")
      update-source-version code-cursor "$version" "$hash" "$url" --source-key=src.src
    fi
  '';

  meta = {
    description = "AI-powered code editor built on vscode";
    homepage = "https://cursor.com";
    license = lib.licenses.unfree;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
    maintainers = with lib.maintainers; [ sarahec ];
    platforms = [ "x86_64-linux" ];
    mainProgram = "cursor";
  };
}
```
after wrestling for a few days i hope the maintainer can help

### Notify maintainers
@sarahec 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-cachyos, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sarahec** [comment]
Thanks for spotting this! I'll update the derivation.

**Comment by sarahec** [comment]
After digging into the code (and the other 115 packages that use app images), there's no good way to do this. The solution is to push on the cursor team.

I'm sorry I can't fix it from this end.

**Comment by jottr** [comment]
@sarahec can you elaborate why this is not fixable on the package level before I attempt it myself?  
I had the same idea as @poyhen and would prefer not to wait for an (unlikely?) fix from upstream.

**Comment by sarahec** [comment]
IIRC, `src` gives you a read-only squashfs (as per the AppImage spec). Perhaps you could unpack it, alter the one file, and build a new squashfs.

I'm concerned about what happens if this fix then breaks, say, KDE or XFCE? That's why I believe it should be an upstream fix from the Cursor team. (If they were shipping open source it would be a different story -- the community could supply the patch.)

**Comment by sarahec** [comment]
i will add that if anyone adds this patch that you should add yourself to the package maintainers.

**Comment by sarahec** [comment]
A safer alternative would be to add an option to use the native titlebar -- see https://forum.cursor.com/t/double-title-bars-on-ubuntu-appimage/1316/3

**Comment by jottr** [comment]
> A safer alternative would be to add an option to use the native titlebar -- see https://forum.cursor.com/t/double-title-bars-on-ubuntu-appimage/1316/3

That's the first thing I tested. Sadly, this still results in significant loss of screen real estate, which becomes an issue on smaller screens.  
Maybe one could simply add an option to the module that allows the users to enable the patch if desired.

**Comment by sarahec** [comment]
Ultimately, the proper fix needs to come from cursor. I doubt their business model is sustainable if they keep shipping half-baked releases. But let's continue to think about how to package a patch.

> Maybe one could simply add an option to the module that allows the users to enable the patch if desired.

I think the smartest way to do this would be to create a `code-cursor-gtk` derivation that takes its `src` from `code-cursor`, then patches and repackages the AppImage. You can set the platform as linux-only. 

That way, you get updates whenever the parent package updates and we de-risk the generic code-cursor build. In fact, Darwin-{x86,ARM} was just added to the package today so it makes even more sense to have a custom package for the patched version.

**Comment by sund3RRR** [comment]
I fix `code-cursor` on NixOS this way:
```nix
  nixpkgs.overlays = [
    (final: prev: {
      code-cursor = (
        let
          appimageContents = prev.appimageTools.extractType2 {
            inherit (prev.code-cursor) version pname;
            src = prev.code-cursor.sources.${config.nixpkgs.hostPlatform.system};
            postExtract = ''
              find $out -type f -name '*.js' \
                -exec grep -l ,minHeight {} \; \
                -exec sed -i 's/,minHeight/,frame:false,minHeight/g' {} \;
            '';
          };
        in
        prev.appimageTools.wrapAppImage {
          inherit (prev.code-cursor) pname version;
          src = appimageContents;

          nativeBuildInputs = [ prev.makeWrapper ];

          extraInstallCommands = ''
            mkdir -p $out/share/cursor $out/share/applications/
            cp -a ${appimageContents}/locales $out/share/cursor
            cp -a ${appimageContents}/usr/share/icons $out/share/
            install -Dm 644 ${appimageContents}/cursor.desktop -t $out/share/applications/

            substituteInPlace $out/share/applications/cursor.desktop --replace-fail "AppRun" "cursor"

            wrapProgram $out/bin/cursor \
              --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime=true}} --no-update"
          '';

          passthru = prev.code-cursor.passthru;
        }
      );
    })
  ];
```
