### ISSUE TITLE
[nixos-24.05] Neochat crashes after startup

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#348243]
### Steps To Reproduce
1. Install neochat, with
```
    permittedInsecurePackages = [
      "olm-3.2.16"
    ];
```
3. start neochat
4. Window opens, but it crashes after some seconds

### Expected behavior

Neochat runs fine

### Notify maintainers

@peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, NixOS, 24.05 (Uakari), 24.05.git.a3f9ad65a0bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/var/src/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
Does it work fine on 24.11?

**Comment by matthiasbeyer** [comment]
Do you mean nixos-24.11? Because that's not released it, is it?

**Comment by Atemu** [comment]
The current nixos-unstable is 24.11.

**Comment by matthiasbeyer** [comment]
Hm, it is working on stable as of a3f9ad65a0bf298ed5847629a57808b97e6e8077 so I guess I'll close this :eyes:
