### ISSUE TITLE
localsend: fails to launch

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#348345]
### Describe the bug
localsend hangs on startup. The window never shows up. Here is a log:
```
$ localsend_app 

** (localsend_app:115217): WARNING **: 23:54:20.320: gtk.dart: failed to call method: No engine to send to

** (localsend_app:115217): WARNING **: 23:54:20.320: gtk.dart: failed to call method: No engine to send to

** (localsend_app:115217): WARNING **: 23:54:20.320: gtk.dart: failed to call method: No engine to send to

** (localsend_app:115217): WARNING **: 23:54:20.328: gtk.dart: failed to call method: No engine to send to
```

### Steps To Reproduce
1. Run `localsend_app`.

### Expected behavior
LocalSend should run.

### Additional context
Unreproducible with Flatpak (tested).

This bug wasn't present with this derivation a few months ago; not sure about when exactly.

Reproducible with either `programs.localsend.enable` or `localsend` in `systemPackages`.

### Notify maintainers
@sikmir
@linsui
@pandapip1

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.02 MiB download, 0.06 MiB unpacked):
  /nix/store/91d27rjqlhkzx7mhzxrir1jcr40nyc7p-stdenv-linux
copying path '/nix/store/91d27rjqlhkzx7mhzxrir1jcr40nyc7p-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11pre690827.5633bcff0c61`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ben9986** [comment]
I can't repro this. Starts just fine for me in nix-shell and from systemPackages. I'm on Plasma 6, what DE/WM are you using? Are you on the latest version for your channel?
```
- system: `"x86_64-linux"`
 - host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240928.19d2ec0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager, nixos"`
 - channels(ben): `"home-manager-23.05.tar.gz"`
 - nixpkgs: `/nix/store/398hb0mcjwzrlv1jha7cv7lzvmcqwryz-source`
```

**Comment by 0n-s** [comment]
> I'm on Plasma 6, what DE/WM are you using? Are you on the latest version for your channel?

GNOME, & yes.

**Comment by aucub** [comment]
The same issue occurs on the gnome channel, affecting both GNOME/Hyprland. GNOME Wayland produces the same log output, while GNOME Xorg/Hyprland does not generate any logs.

**Comment by Ben9986** [comment]
Also tested on plasma 6 X11, works fine for me. Also works fine on hyprland for me, with plasma6 still installed. Could be a weird interaction with gnome. xdg-portal-gtk/gnome? 

I'll leave for someone who can repro to investigate

**Comment by Pandapip1** [comment]
I am currently on COSMIC (which I switched to from GNOME yesterday), and I also can't launch localsend_app, and (apparently) just like with hyprland, there aren't any logs.

**Comment by aucub** [comment]
> I can't repro this. Starts just fine for me in nix-shell and from systemPackages. I'm on Plasma 6, what DE/WM are you using? Are you on the latest version for your channel?我无法重现这个。在 nix-shell 和 systemPackages 中对我来说启动得很好。我使用的是 Plasma 6，您使用什么 DE/WM？您的频道使用的是最新版本吗？
> 
> ```
> - system: `"x86_64-linux"`
>  - host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240928.19d2ec0`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.18.8`
>  - channels(root): `"home-manager, nixos"`
>  - channels(ben): `"home-manager-23.05.tar.gz"`
>  - nixpkgs: `/nix/store/398hb0mcjwzrlv1jha7cv7lzvmcqwryz-source`
> ```
Your system built on 20240928 is an outdated version. After the removal of Flutter 3.13, Localsend was updated to an unstable version last week.

**Comment by aucub** [comment]
> I can't repro this. Starts just fine for me in nix-shell and from systemPackages. I'm on Plasma 6, what DE/WM are you using? Are you on the latest version for your channel?
> 
> ```
> - system: `"x86_64-linux"`
>  - host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240928.19d2ec0`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.18.8`
>  - channels(root): `"home-manager, nixos"`
>  - channels(ben): `"home-manager-23.05.tar.gz"`
>  - nixpkgs: `/nix/store/398hb0mcjwzrlv1jha7cv7lzvmcqwryz-source`
> ```

Your system built on 20240928 is an outdated version. After the removal of Flutter 3.13, Localsend was updated to an unstable version last week.

**Comment by initialencounter** [comment]
> an unstable version last week.

Which wersion was stable wersion?  I just want make it  work, even it is oldest wersion, could you teach me?

**Comment by aucub** [comment]
> > an unstable version last week.
> 
> hi @aucub ! Which wersion was stable wersion? I just want make it work, even it is oldest wersion, could you teach me?

Localsend 1.15.4, compiled with Flutter 3.13, such as the version e0464e47880a69896f0fb1810f00e0de469f770a from nixkgs, runs smoothly on my device.

**Comment by Ben9986** [comment]
> Your system built on 20240928 is an outdated version. After the removal of Flutter 3.13, Localsend was updated to an unstable version last week.

yeh sorry ignore me. I could have sworn I updated my flake yesterday. Apparently not.

**Comment by 0n-s** [comment]
@RossComputerGuy (as author of https://github.com/NixOS/nixpkgs/pull/346732)

**Comment by RossComputerGuy** [comment]
This might be reproducible upstream if their Flatpak uses Flutter 3.24. We're using the prebuilt engine here so we don't have much control over it. I've looked over upstream's issue tracker and this has happened in the past before for them but there could be a potential issue which is the same as this one.

> Localsend was updated to an unstable version last week.

Flutter 3.24 is actually from the stable channel from Flutter.

**Comment by RossComputerGuy** [comment]
Also, I get this on aarch64-linux:
```
(localsend_app:216761): Gtk-WARNING **: 07:48:26.625: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
Gdk-Message: 07:48:26.699: Unable to load nw-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load n-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load ne-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load w-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load e-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load sw-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load s-resize from the cursor theme
Gdk-Message: 07:48:26.699: Unable to load se-resize from the cursor theme
```

If I launch with `GTK_DEBUG=interactive`, go into `MyApplication`, find the window object in properties, and then go into the properties and toggle `visible` to `true` then the window shows up.

**Comment by aucub** [comment]
> This might be reproducible upstream if their Flatpak uses Flutter 3.24. We're using the prebuilt engine here so we don't have much control over it. I've looked over upstream's issue tracker and this has happened in the past before for them but there could be a potential issue which is the same as this one.
> 
> > Localsend was updated to an unstable version last week.
> 
> Flutter 3.24 is actually from the stable channel from Flutter.

The upstream Localsend project does not have a version like 1.15.4-unstable-2024-09-25; version 1.15.4 is the latest stable release from upstream. It makes sense to remove outdated Flutter versions, and as a result, Localsend needs to be updated to the unstable version. However, these updates do indeed affect users, such as those using the nixos-unstable channel.

**Comment by RossComputerGuy** [comment]
> The upstream Localsend project does not have a version like 1.15.4-unstable-2024-09-25;

I thought you were mentioning Flutter versions, not localsend versions.

I believe I did find the issue, https://github.com/localsend/localsend/blob/main/app/linux/my_application.cc#L58 needs to use `gtk_widget_show` and not realize.

**Comment by aucub** [comment]
This modification resolved my issue.

**Comment by RossComputerGuy** [comment]
Good to hear, I believe this issue was found because recent Flutter versions are having changes to the view stuff to handle multiview applications. Likely was using `gtk_widget_show` on the window in the past inside the view class. The Linux Flutter application template does use `gtk_widget_show` around where the window or view is grabbed so as long as applications don't change that part, it should be fine.

I don't have time to make a PR until later today but if someone wishes to, I can at least review it before I have time to make one. Fun fact, a change I removed for Yubioauth Flutter can be dropped in:

```
substituteInPlace linux/my_application.cc \
      --replace-fail "gtk_widget_realize(GTK_WIDGET(window));" "gtk_widget_show(GTK_WIDGET(window));"
```

**Comment by 0n-s** [comment]
> If I launch with `GTK_DEBUG=interactive`, go into `MyApplication`, find the window object in properties, and then go into the properties and toggle `visible` to `true` then the window shows up.

Can confirm this solves the issue for me.

**Comment by initialencounter** [comment]
> > If I launch with `GTK_DEBUG=interactive`, go into `MyApplication`, find the window object in properties, and then go into the properties and toggle `visible` to `true` then the window shows up.
> 
> Can confirm this solves the issue for me.

https://github.com/user-attachments/assets/7abe85f4-686b-4bd0-bb05-3cf2efd9607a


me too. 谢谢你!  Thank you!

**Comment by RossComputerGuy** [comment]
> 谢谢你! Thank you!

どういたしまして！You're welcome.

I've opened #348579 to fix this

**Comment by 0n-s** [comment]
> I've opened #348579 to fix this since I was able to find a moment to open a PR.

It's prudent to send a similar PR to upstream first.

**Comment by RossComputerGuy** [comment]
I'm aware, I plan on upstreaming it tonight after work. I made this PR over ssh on my phone.

**Comment by Pandapip1** [comment]
> I've opened https://github.com/NixOS/nixpkgs/pull/348579 to fix this since I was able to find a moment to open a PR.

You scooped me :|

**Comment by RossComputerGuy** [comment]
> You scooped me :|

Heh sorry, you can make the upstream PR since idk when I'll have the time to try and do it. I likely won't be able to get to it until like 7PM PST.

**Comment by Pandapip1** [comment]
https://github.com/localsend/localsend/pull/1898 submitted
