### ISSUE TITLE
Build failure: steam(?)

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#348369]
### Steps To Reproduce

1. `programs.steam.enable = true;`

### Build log

[log here](https://gist.github.com/surfaceflinger/a506cc495605a62742d2569ba5f429e2)

### Additional context

not actually steam but idk at which package to point.

full config is

```
programs.steam = {
  enable = true;
  dedicatedServer.openFirewall = true;
  extest.enable = true;
  extraCompatPackages = [ pkgs.proton-ge-bin ];
  extraPackages = with pkgs; [
    steamtinkerlaunch
    protontricks
    winetricks
  ];
  gamescopeSession.enable = true;
  localNetworkGameTransfers.openFirewall = true;
  remotePlay.openFirewall = true;
};
```

### Notify maintainers

I can see that @K900 made [some bigger changes](https://github.com/NixOS/nixpkgs/commit/a3ccb7f562a93826ad0112adf20dc7f697b7713e) to steam few days ago 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.65d98cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/nat/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/nat/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/nat/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/nat/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/0nrvyvki12xmq6ccidgrin0k0c9hf136-gnome-settings-daemon-46.0/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cfl6rqw64ndbh2m0qapg410jf4xmycia-lix-2.91.0/share`
 - nixpkgs: `/nix/store/y4rmd9g036gmgz5xjiplw1zcbi16fqdr-source`
```

nixpkgs commit from which i tried to build steam is https://github.com/NixOS/nixpkgs/commit/564451a037500d67b2c798ef7bddf43772ab6096

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
OK, so this is actually a bug in our pixman packaging, but also, you somehow have something that pulls in `pixman.dev` in your `hardware.graphics.packages`, so maybe try getting rid of whatever that is.

**Comment by K900** [comment]
The actual core issue is fixed by https://github.com/NixOS/nixpkgs/pull/348483.

**Comment by surfaceflinger** [comment]
>you somehow have something that pulls in pixman.dev in your hardware.graphics.packages, so maybe try getting rid of whatever that is.

weird, I use nixos-hardware for gpu

**Comment by JohnRTitor** [comment]
nixos-hardware is a repo of set of modules designed for specific hardwares. The modules themselves may import `pixmap` in your `hardware.graphics`, even if you explicitly did not do so in your configuration. Either way, this should be fixed when the channels are updated.

**Comment by surfaceflinger** [comment]
>nixos-hardware is a repo of set of modules designed for specific hardwares. The modules themselves may import pixmap in your hardware.graphics, even if you explicitly did not do so in your configuration.

yes, that's what I meant, I just wouldn't expect this to occur in nixos-hardware

**Comment by surfaceflinger** [comment]
This seems to be caused by having `protontricks` in `programs.steam.extraPackages` but `programs.steam.protontricks.enable` works fine. If that's expected then close this

**Comment by K900** [comment]
I'm going to close this since the underlying issue should also be fixed on -next now.
