### ISSUE TITLE
treewide: use https addresses where possible

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#34836]
In my social circle, it's considered slightly inpolite to use http instead of https addresses. :-) Therefore I thought to give rewriting of all http addresses in the nixpkgs repository a go, just as an experiment; the result can be found in pull request #30906.

(I'm not trying to start a religious war and don't particularly care. Of course the issue is not really an issue for NixOS since we verify sha256sums. Still we could gain street creds if we could proclaim that "NixOS doesn't contain a single http link".)

The referenced pull request is too large to review and test, see the discussion over there. I appreciate any pointers on how we could go on. The script I used to rewrite http addresses to https addresses after a positive check is online: https://github.com/luga-ev/website/blob/master/rewrite-http-to-https.pl

**Comment by matthewbauer** [comment]
Closing in favor of #13809.
