### ISSUE TITLE
VirtualBox Extension Pack checksum mismatch

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#34846]
## Issue description

VirtualBox build crashes with error on extension pack SHA checksum mismatch.

```
VBoxExtPackHelperApp: error: The extension pack file has changed (SHA-256 mismatch)
VBoxExtPackHelperApp: info: Validating extension pack '/nix/store/6dq7gw9a87kwa2k6d9q2x0xf8y7cgh1c-Oracle_VM_VirtualBox_Extension_Pack-5.1.32-120294.vbox-extpack' ('Oracle VM VirtualBox Extension Pack')...
rcExit=1
builder for ‘/nix/store/66l7lb17h15dh09b6djqnf5i8dgfvcaq-virtualbox-5.1.32.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dldswdagfc4sv225vsb4jj3snj0v9wcx-nixos-system-ckopo-nix-17.09.2987.59890bb1351.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/dldswdagfc4sv225vsb4jj3snj0v9wcx-nixos-system-ckopo-nix-17.09.2987.59890bb1351.drv’ failed
```

Extension pack file was prefetched using a link provided by license message and its checksum matches with [site-listed](https://www.virtualbox.org/download/hashes/5.1.32/SHA256SUMS). 

```
21258910250c89f6d7062cd96e53a8d855e9f8bb6a011c18de760dc5b869c68e  /nix/store/6dq7gw9a87kwa2k6d9q2x0xf8y7cgh1c-Oracle_VM_VirtualBox_Extension_Pack-5.1.32-120294.vbox-extpack
```

### Steps to reproduce

 - have this in your `configuration.nix`
 ```
virtualisation.virtualbox.host.enable = true;
nixpkgs.config.virtualbox.enableExtensionPack = true;
```
 - run `# nixos-rebuild switch` (has done it with `--upgrade` key)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2905.c1d9aff56e0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2987.59890bb1351"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by markuskowa** [comment]
Same problem here 

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2875.c2b668ee726 (Hummingbird)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2987.59890bb1351"`
 - channels(markus): `"nixpkgs-17.09.2955.76614894f34"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by krgn** [comment]
I also have the same problem. I tried patching in virtualboxn (and the 4.1.15 kernel) from unstable in an overlay, but now I sadly get this error:

```
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```
Is there any other way I can override this so I can rebuild my system?

**Comment by JanBessai** [comment]
I think the hash needs to be changed [here](
https://github.com/NixOS/nixpkgs/blob/9b726af6bd33349a2435e2b251f9b6d4b83adc82/pkgs/applications/virtualization/virtualbox/default.nix#L22) to 
`21258910250c89f6d7062cd96e53a8d855e9f8bb6a011c18de760dc5b869c68e` as mentioned above.

**Comment by chekoopa** [comment]
@JanBessai Yes. I'd make it by myself, but have no idea what to do here so nothing would be broken. ~.~

**Comment by jfrankenau** [comment]
I guess this issue can be closed now.

**Comment by chekoopa** [comment]
Yes, now VirtualBox builds well.

// btw, though has to stay on this channel version, as got new issues, such as audio jitter and big lags (a Spectre core patch?!). that's a different story to tell.
