### ISSUE TITLE
patch urls of  calibre package are not found

### ISSUE THREAD

**Issue by stubbfel** [NixOS/nixpkgs#34848]
https://github.com/NixOS/nixpkgs/blob/5db4e631bdabe17c3b76f541f529ab348628c99b/pkgs/applications/misc/calibre/default.nix#L21-L23
 the url for  the disable_plugins.patch seems not exists any more:

>  wget http://bazaar.launchpad.net/~calibre-packagers/calibre/debian/download/head:/disable_plugins.py-20111220183043-dcl08ccfagjxt1dv-1/disable_plugins.py
> --2018-02-11 16:25:11--  http://bazaar.launchpad.net/~calibre-packagers/calibre/debian/download/head:/disable_plugins.py-20111220183043-dcl08ccfagjxt1dv-1/disable_plugins.py
> Auflösen des Hostnamens bazaar.launchpad.net (bazaar.launchpad.net)… 91.189.95.84
> Verbindungsaufbau zu bazaar.launchpad.net (bazaar.launchpad.net)|91.189.95.84|:80 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
> 2018-02-11 16:25:11 FEHLER 404: Not Found.

same result for no_updates_dialog.patch

https://github.com/NixOS/nixpkgs/blob/5db4e631bdabe17c3b76f541f529ab348628c99b/pkgs/applications/misc/calibre/default.nix#L26-L28

> wget http://bazaar.launchpad.net/~calibre-packagers/calibre/debian/download/head:/no_updates_dialog.pa-20081231120426-rzzufl0zo66t3mtc-16/no_updates_dialog.patch
> --2018-02-11 16:31:27--  http://bazaar.launchpad.net/~calibre-packagers/calibre/debian/download/head:/no_updates_dialog.pa-20081231120426-rzzufl0zo66t3mtc-16/no_updates_dialog.patch
> Auflösen des Hostnamens bazaar.launchpad.net (bazaar.launchpad.net)… 91.189.95.84
> Verbindungsaufbau zu bazaar.launchpad.net (bazaar.launchpad.net)|91.189.95.84|:80 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
> 2018-02-11 16:31:27 FEHLER 404: Not Found.

may is launch id  calibre-packagers is not available anymore

**Comment by dotlambda** [comment]
I was able to find the first patch over at the Gentoo repos: https://gitweb.gentoo.org/repo/gentoo.git/plain/app-text/calibre/files/calibre-disable_plugins.patch?id=866442b713d66e517d2f97277653e207f78234d7

**Comment by AndersonTorres** [comment]
In the url provided, there is a bunch of patches. Maybe we can try them!

https://gitweb.gentoo.org/repo/gentoo.git/plain/app-text/calibre/files/

**Comment by AndersonTorres** [comment]
Hey @dotlambda , are you using an outdated version of calibre? You are quoting [version 3.7.0](
https://github.com/NixOS/nixpkgs/blob/5db4e631bdabe17c3b76f541f529ab348628c99b/pkgs/applications/misc/calibre/default.nix#L8) and my local Calibre is 3.14 - while the master is [3.16](https://github.com/NixOS/nixpkgs/blob/596a03e002312b0c4c392d6722cdd0e485f24da9/pkgs/applications/misc/calibre/default.nix#L8). 

Try to update your local Nixpkgs channels, or use the unstable or the master branches, and return if something about these patches happens.
