### ISSUE TITLE
Enabling TCP stream to PulseAudio does not configure the firewall

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#34852]
## Issue description

Hello and thank you for this wonderful project! Now for the issue, I feel like setting `hardware.pulseaudio.tcp.enable = true` should make the firewall allow the default port for PulseAudio TCP streaming (4713).

### Steps to reproduce

- Have the following config:
```nix
{
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = []; # or anything without 4713

  pulseaudio = {
    enable = true;

    tcp = {
      enable = true;
      anonymousClients.allowAll = true;
    };
  };
}
```

- Try to have stream from another computer
- See that it won't work :'-(

Adding 4713 to `networking.firewall.allowedTCPPorts` does fix the problem.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.2987.59890bb1351 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2987.59890bb1351"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by srhb** [comment]
Generally, services do not open the firewall, with a few exceptions (notably sshd) and rely instead of the user making an active decision to put a hole in it. I think this is working as intended.

**Comment by minijackson** [comment]
Oh I see, it's because I saw that enabling sshd opened the port that I thought that it was the standard behavior. My bad, then.

**Comment by 7c6f434c** [comment]
`sshd` case is special because accidentally blocking SSH can be very hard to fix.

**Comment by roberth** [comment]
You could add an [`openFirewall`](https://nixos.org/nixos/options.html#openfirewall) option to open the port if tcp is enabled, so the user doesn't have to bother with the exact port number and firewall option.

**Comment by Ekleog** [comment]
(triage) @minijackson Do you want to keep this issue open until a `openFirewall` option makes it in, or should this issue be closed?

**Comment by minijackson** [comment]
@Ekleog No, I don't think this issue needs to stay open. I'll maybe make a PR for `openFirewall`, but I don't think this is an issue per se.
