### ISSUE TITLE
Adding vlan support in openvswitch

### ISSUE THREAD

**Issue by netixx** [NixOS/nixpkgs#34851]
## Issue description
I am trying to setup a openvswitch switch attached to a physical (trunk) interface and multiple tagged internal interfaces, that act as gateways for each vlan defined in my network (which is connected to the physical interface).

The current implementation for openvswitch `networking.vswitchs.interfaces` does not allow definition of vlan and other interface properties (such as type) (see [this](http://docs.openvswitch.org/en/latest/faq/configuration/) for openvswitch configuration details).

I am currently in the process of implementing those features in nixos and I need help determining the input format for this feature.

I have two proposals:
```
networking.vswitchs.test.interfaces=[
  {
    name="int";
    vlan=10;
    type="internal";
  }
];
```
or
```
networking.vswitchs.test.interfaces={
  int={
    vlan=10;
    type="internal";
  };
};
```

I now that those two options are possible for `networking.interfaces`, but I don't how it works because my knowledge of nix is limited.

Also, I think I should retain compatibility with the original interface `networking.vswitchs.test.interfaces=["int"]` but I may need help doing so.

As a bonus, I think it would be nice to support other openvswitch options on ports and interfaces (such as `vlan_mode`), but I don't know if nixos favours specific options with multiple simple implementations or generic options with a single more complex implementation. For example, is it better to add options for `vlan` and `type` specifically or a generic attributeset that would be translated as is in `ovs-vsctl` commands.

See [this](http://docs.openvswitch.org/en/latest/faq/vlan/) for example of vlan configuration.

Can someone help me find the best format ?
Thank you
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by netixx** [comment]
reading of #1800 seems to bring insight in favour of the second solution. But how do we keep backwards compatibility with previous input format ?

**Comment by volth** [comment]
```openvswitch``` in ```nixpkgs``` is outdated and partially broken (for example the ipsec-related stuff).
I guess you may feel free to update and refactor it as you like.

**Comment by netixx** [comment]
Thank you for this information. I guess I don't have to worry about backwards compatibility then!

Is it a requirement for the interface to be compatible/swappable in some way with other similar features (such as regular bridges) ?

**Comment by netixx** [comment]
This issue is resolved in the reference PR, at least when using system-networkd as network configuration deamon.

**Comment by netixx** [comment]
merged in upstream nixpkgs
