### ISSUE TITLE
Update request: deno 1.46.3 → 2.0.0

### ISSUE THREAD

**Issue by jaydanurwin** [NixOS/nixpkgs#348599]
- Package name: Deno
- Latest released version:
-  2.0.0
- Current version on the unstable channel: 1.46.3
- Current version on the stable/release channel: 1.44.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@06kellyjac

Thank you!

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 06kellyjac** [comment]
Hello. Deno 2 has been merged, it just hasn't reached unstable yet.

#347484

I dont plan on backporting 2 for a few reasons.

1. Stable is always fairly behind on Deno so for latest I would advise pulling in deno from unstable.
2. Deno 2 introduces breaking changes which is against our policy for backports (might also require a rust backport)
3. 24.11 will be released in the near future

Thanks :)
