### ISSUE TITLE
Additional CA trust certificates to be used in other packages

### ISSUE THREAD

**Issue by jensbin** [NixOS/nixpkgs#34855]
## Issue description
Additional CA trust certificates added with ```security.pki.certificates``` as in (https://nixos.org/nixos/options.html#security.pki.certificates), are added to the system truststore (```/etc/static/ssl/certs/ca-certificates.crt```), but not to packages depending on ```${cacert}```.

### Steps to reproduce
Add an additional CA certificate trust using ```security.pki.certificates = [ (builtins.readFile myca.pem) ];```
Add pkgs ```citrix_receiver```.

```
[~] $ grep "MIIFVjCCAz6gAwIBAgIBATANBgkqhkiG9w0BAQsFADA8MQswCQYDVQQGEwJDSDEP" /etc/pki/tls/certs/ca-bundle.crt 
MIIFVjCCAz6gAwIBAgIBATANBgkqhkiG9w0BAQsFADA8MQswCQYDVQQGEwJDSDEP
[~] $ readlink /run/current-system/sw/bin/wfica
/nix/store/igbk08llylxdvpyp0glxfrjrs4ap80w2-citrix-receiver-13.8.0/bin/wfica
[~] $ grep "MIIFVjCCAz6gAwIBAgIBATANBgkqhkiG9w0BAQsFADA8MQswCQYDVQQGEwJDSDEP" /nix/store/igbk08llylxdvpyp0glxfrjrs4ap80w2-citrix-receiver-13.8.0/opt/citrix-icaclient/keystore/cacerts/*
[~] $ 
```

Software like ```citrix_receiver``` using an independent CA truststore. The behavior is reproducible with the nix package ```citrix_receiver```. The package executes in the post install:
```
awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "cert." c ".pem"}' < ${cacert}/etc/ssl/certs/ca-bundle.crt
```

## Technical details

Unfortunately I haven't had a look how this is currently implemented, neither I am sure what should the proper implementation be.
Some options are:
1. cacert module adds additional CA certificates defined with ```security.pki.certificates```
2. packages use the system truststore ```/etc/pki/tls/certs/ca-bundle.crt``` instead of ```${cacert}/etc/ssl/certs/ca-bundle.crt```
3. packages using it's own truststore, needs to define additional CA trusts in the packages

**Comment by jensbin** [comment]
Can anybody point into the right direction where ```security.pki.certificates``` (```modules/security/ca.nix```) is getting applied? It seems not to be in ```pkgs/data/misc/cacert/default.nix```.

**Comment by vcunat** [comment]
You can't directly access nixos attributes from within nixpkgs.  There's a problem in portability, as packages don't have to run on nixos, and CA stores are on different locations in different distributions.  I'm not aware of a good general solution, but there might be some.

As you can see e.g. in manual for `security.pki.certificates`, the nixos module is implemented in `<nixpkgs/nixos/modules/security/ca.nix>`.

**Comment by jensbin** [comment]
Thanks for the input @vcunat.

Hi @obadz, @a1russell, @FRidh
Would you agree to change the ```citrix_receiver``` package behavior to use the system truststore ```/etc/pki/tls/certs/ca-bundle.crt``` instead of ```${cacert}/etc/ssl/certs/ca-bundle.crt``` to respect additional added CA trusts?

**Comment by FRidh** [comment]
@jensbin I don't know. This is a bigger issue, see e.g. https://github.com/NixOS/nixpkgs/issues/24911.

**Comment by obadz** [comment]
@jensbin, I don't have a strong view, but agree with @FRidh that there should be one canonical way to get root certs on nixpkgs/nixos.

**Comment by Ekleog** [comment]
(triage) I think this is a duplicate of https://github.com/NixOS/nixpkgs/issues/8247
