### ISSUE TITLE
buck2: crashes on aarch64 with a 16k page size

### ISSUE THREAD

**Issue by theoparis** [NixOS/nixpkgs#348698]
### Describe the bug

On aarch64 systems such as Asahi Linux, or Raspberry pi 5 devices that use a 16k page size buck2 will not run due to jemalloc.

```
<jemalloc>: Unsupported system page size
memory allocation of 64 bytes failed
```

### Steps To Reproduce

On an aarch64 host system with a 16k size, run:

```
nix run 'github:nixos/nixpkgs/master#buck2'
```

### Expected behavior

The `buck2` command and the `buck2 init` command should work.

### Notify maintainers

@thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

```
 - system: `"aarch64-linux"`
 - host os: `Linux 6.11.0-400.asahi.fc40.aarch64+16k, Fedora Linux Asahi Remix, 40 (KDE Plasma), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/mln6wr5z539qgldmsm4j1k8k0dm19yvz-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by theoparis** [comment]
Hmm, this seems to be have been reported in https://github.com/facebook/buck2/issues/91 already 😕

**Comment by theoparis** [comment]
There also seems to be a environment variable called `JEMALLOC_SYS_WITH_LG_PAGE` which can be set to 16 🤔

**Comment by thoughtpolice** [comment]
This should be fixed by https://github.com/NixOS/nixpkgs/pull/348911, which includes https://github.com/facebook/buck2/pull/693
