### ISSUE TITLE
Package request: SCons

### ISSUE THREAD

**Issue by Arya-Elfren** [NixOS/nixpkgs#348628]
**Project description**

SCons is an Open Source software construction tool. Think of SCons as an improved, cross-platform substitute for the classic Make utility with integrated functionality similar to autoconf/automake and compiler caches such as ccache. In short, SCons is an easier, more reliable and faster way to build software.

**Metadata**

* homepage URL: https://scons.org/
* source URL: https://github.com/SCons/scons
* license: mit
* platforms: Linux, other POSIX systems (including AIX, BSD systems, HP/UX, IRIX and Solaris), Windows 7/8/10, MacOS, and OS/2

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
I believe scons has been packaged for a long time.
See https://search.nixos.org/packages?query=scons

**Comment by Arya-Elfren** [comment]
Damn, it didn't appear when I searched earlier. User error I guess. Sorry.
