### ISSUE TITLE
Build failure: palemoon-bin

### ISSUE THREAD

**Issue by shollander** [NixOS/nixpkgs#348623]
### Steps To Reproduce

1. `nix-shell -p palemoon-bin`

### Build log

```
these 2 derivations will be built:
  /nix/store/wp806xs71ph7yqskii6g0q94ps7vha91-source.drv
  /nix/store/13zmh1w7bk91limva2xpzrrwkdn2x5m0-palemoon-bin-33.1.1.drv
building '/nix/store/wp806xs71ph7yqskii6g0q94ps7vha91-source.drv'...

trying https://rm-eu.palemoon.org/release/palemoon-33.1.1.linux-x86_64-gtk3.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 404

trying https://rm-us.palemoon.org/release/palemoon-33.1.1.linux-x86_64-gtk3.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download source from any mirror
error: builder for '/nix/store/wp806xs71ph7yqskii6g0q94ps7vha91-source.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/13zmh1w7bk91limva2xpzrrwkdn2x5m0-palemoon-bin-33.1.1.drv' failed to build

```

### Notify maintainers
@OPNA2608 

### Metadata

```console
[nix-1:~/runner]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.16, Ubuntu, 20.04.2 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.0pre20230808_c0e6466`
 - channels(runner): `"nixpkgs, nixpkgs-stable-21_11-21.11.tar.gz, nixpkgs-stable-22_05-22.05.tar.gz, nixpkgs-stable-22_11-22.11.tar.gz, nixpkgs-stable-23_05-23.05.tar.gz, nixpkgs-stable-23_11-23.11.tar.gz, nixpkgs-stable-24_05-24.05.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/home/runner/.nix-defexpr/channels/nixpkgs-stable-24_05`

```

**Comment by OPNA2608** [comment]
Your channel seems really outdated. We bumped away from 33.1.1 in mid-June, stable currently has 33.4.0.1 (unstable should too, but it seems like the channel hasn't received that bump yet).

Upstream does not keep downloads for old versions on their main download server forever. There is [an archive server for older Pale Moon releases](https://www.palemoon.org/archived.shtml), but I'm not sure if upstream would appreciate it if we add that as an automatic fallback download source:

![image](https://github.com/user-attachments/assets/305acbaa-b7c0-41cd-81b3-5171aee8af95)
![image](https://github.com/user-attachments/assets/4d1e2a42-ef05-40a6-abcb-b1f1ef0fd5a6)

I think the solution here is to update your channel so you can use the latest (and secure) Pale Moon version. If you *need* to use this old version, navigate the archive server to the `palemoon-33.1.1.linux-x86_64-gtk3.tar.xz` archive, copy the link, then run
```
nix-prefetch-url --unpack 'insert copied url here'
```

This will download the old version and register it in the store. `nix-shell -p palemoon-bin` will then use the already-downloaded content.

**Comment by shollander** [comment]
I am supposed to be on the stable 24.05 channel. I am not sure why it's out of date. I'll have to look into that.
Thanks for the tip about downloading archived versions.

Thanks for your help!
