### ISSUE TITLE
sioyek fails to launch

### ISSUE THREAD

**Issue by RishiVora** [NixOS/nixpkgs#348694]
### Describe the bug
I am on the unstable branch and sioyek (alpha build) fails to launch with the following error.
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, eglfs, minimal, minimalegl, vnc, offscreen, vkkhrdisplay, xcb.

Aborted (core dumped)
```

### Steps To Reproduce
1. Create an ephemeral shell with sioyek: `nix-shell -p sioyek` or simply add to config
2. Try to launch sioyek: `sioyek`

### Additional context
I am running Niri WM. So I tried installing plasma6 with `services.desktopManager.plasma6.enable = true` and now when I add sioyek to configuration, it works. Without that, it fails.

### Notify maintainers
@xyven1 @podocarp @stephen-huan 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by stephen-huan** [comment]
Possibly related to https://github.com/NixOS/nixpkgs/pull/283813#issuecomment-2039042378. Does the following overlay fix the issue?

```nix
final: prev:

{
  sioyek = prev.sioyek.overrideAttrs (previousAttrs: {
    buildInputs = previousAttrs.buildInputs ++ [ final.qt6.wayland ];
  });
}
```

**Comment by RishiVora** [comment]
used `kdePackages.qtwayland` instead of `qt6.wayland` and it worked :+1:
