### ISSUE TITLE
wrong localtime and UTC times

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#34874]
## Issue description
I have my system configured to
```
  time.timeZone = "Asia/Tokyo";
  time.hardwareClockInLocalTime = false; # by default false
```
but when I ask for the day, there seems to be something wrong, my local time should be 14:04 and UTC 5am (14h -9h)  yet it displays:
```
$ timedatectl                                                                                                                                              
      Local time: lun. 2018-02-12 23:04:03 JST
  Universal time: lun. 2018-02-12 14:04:03 UTC
        RTC time: lun. 2018-02-12 14:04:03
       Time zone: Asia/Tokyo (JST, +0900)
 Network time on: n/a
NTP synchronized: no
 RTC in local TZ: no
```
my locale shows but I don't think it interferes as LC_TIME should just change  the way time is formatted rather than  its value.                                                                                                                                       
```
LANG=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=
...
```
It seems like much software relies on /etc/timezone but this file doesn't exist for mee
I found the file /etc/zoneinfo/localtime, I am not sure how to interpret it but I am concerned by the GMT0 I see
```
cat /etc/zoneinfo/localtime                                                                                                                               
TZif2GMTTZif2�GMT
GMT0

```

## Technical details

I am basically on nixos-unstable with sandbox on
e860b651d6e297658e960c165fd231dbc0de1f9b
and I use home-manager (I haven't seen any setting thsat should interfere but you never know..)

**Comment by jtojnar** [comment]
You are setting `hardwareClockInLocalTime` to `false` but your hardware clock (RTC), in fact, uses your local time. Just set the time correctly, it will also update your hardware clock.

If you dual boot with Windows, you will also need to [let it know about UTC RTC](https://superuser.com/questions/975717/does-windows-10-support-utc-as-bios-time), in order not to change it back.

**Comment by teto** [comment]
I am quite sure that must be it thanks. I'll fix the windows part and I once I've checked it fixes the problem will close this.

**Comment by manveru** [comment]
@teto how did it go?

**Comment by teto** [comment]
not so well but I believe I messed up the windows config. I'll try again. Meanwhile I close this as I believe the solution is good, I just failed the execution this one time :)
