### ISSUE TITLE
Heroic Games Launcher desktop icon blurry 

### ISSUE THREAD

**Issue by nadir-ishiguro** [NixOS/nixpkgs#348764]
### Describe the bug

I've noticed that the desktop icon for Heroic Games Launcher is very low resolution. At least that's the case on Gnome, I haven't tried any other desktop environments.

This has been the case for at least the last few months. Hadn't used the application before.

### Steps To Reproduce
1. Install Heroic Games Launcher by adding it to your NixOS or home-manager configuration and switching to it.
2. Search for Heroic and/or add it to your dash.
3. Not a single high res desktop icon to be seen.

### Expected behavior
Seeing the a high res version of the desktop icon.

### Screenshots
![Screenshot from 2024-10-15 13-08-37](https://github.com/user-attachments/assets/449d2ff3-3656-4fa0-a585-e246104a0d16)
![Screenshot from 2024-10-15 13-09-00](https://github.com/user-attachments/assets/4d60be11-652c-4e97-bf7e-a705c30299fe)

### Notify maintainers

@aidalgol

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-cachyos, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
Just tried this on kde and it shows a non-fuzzy hires icon as expected.

**Comment by aidalgol** [comment]
Sounds like an issue with GNOME not picking the scaleable icon for some reason.
Pinging the @NixOS/gnome maintainers.

**Comment by jtojnar** [comment]
🤷‍♀️ Maybe the issue is that the package is installing [128×128 icon](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/flatpak/com.heroicgameslauncher.hgl.png) as 512×512:

https://github.com/NixOS/nixpkgs/blob/8609d17447964810e17fcf2d80dc30439d3bc01e/pkgs/games/heroic/default.nix#L93

**Comment by Steinhagen** [comment]
Can you check if the PR fixes your problem?
