### ISSUE TITLE
Update request: immich 1.117.0 → 1.118.0

### ISSUE THREAD

**Issue by poperigby** [NixOS/nixpkgs#348829]
- Package name: immich
- Latest released version: 1.118.0
- Current version on the unstable channel: 1.117.0
- Current version on the stable/release channel: N/A
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@jvanbruegge 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jvanbruegge** [comment]
The update was released just 6h ago. Give the people some time... :roll_eyes:

**Comment by poperigby** [comment]
There's no rush. I'm just getting it on the issue tracker.
