### ISSUE TITLE
`'targetPlatforms' missing` when `nixos-rebuild` with `nixpkgs` >= `nixos-unstable` in flake

### ISSUE THREAD

**Issue by minhtrancccp** [NixOS/nixpkgs#348832]
### Describe the bug
`nixos-rebuild [test|switch]` fails with the error of `attribute 'targetPlatforms' missing` for my machine, whose configurations include rust-based apps and `nixpkgs` input in `flake.nix` set to `github:nixos/nixpkgs/nixos-unstable` or `github:nixos/nixpkgs`

### Steps To Reproduce
1. set up `flake.nix` with `inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";`
2. `sudo nixos-rebuild test`

### Additional context
this error did not occur when `nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";`
[log from `nixos-rebuild test --show-trace` ](https://rentry.co/wkq6zvom)

### Notify maintainers
@alyssais 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alyssais** [comment]
Are you using a rustc from somewhere other than Nixpkgs?  I don't think this is a problem inside Nixpkgs, but I could be wrong!

**Comment by fehnomenal** [comment]
I got the same problem. Seems to be related to COSMIC. If I disable it (`services.desktopManager.cosmic.enable = false;`) the error goes away.

**Comment by alyssais** [comment]
Does that mean you're using the cosmic overlay, which uses some non-Nixpkgs rustc?

**Comment by fehnomenal** [comment]
Yeah, exactly. If I understand correctly, they build a custom rust platform in the flake:

https://github.com/lilyinstarlight/nixos-cosmic/blob/a1e3c25b1d6fb0a88a5bbb61cc4bd502439a68ff/flake.nix#L20-L25

**Comment by minhtrancccp** [comment]
seems like that's the case for me as well, as i'm trying to use an overlay with custom rust too:

https://github.com/oppiliappan/statix/blob/d324490e45bcda1b664f28b6f88da8580deda76b/flake.nix#L39

**Comment by alyssais** [comment]
Please report to wherever your rustc comes from.  They should provide `targetPlatforms` and `badTargetPlatforms` attributes listing which platform doubles their rustc can build for.

**Comment by nicolas-guichard** [comment]
I'm also hitting this, using fenix with:
```
pkgs = nixpkgs.legacyPackages.${system}.extend fenix.overlays.default;

rustToolchain = pkgs.fenix.combine (with pkgs.fenix; [
  stable.toolchain
  targets.wasm32-unknown-unknown.stable.rust-std
]);

buildRustPackage =
  (pkgs.makeRustPlatform {
    cargo = rustToolchain;
    rustc = rustToolchain;
  })
  .buildRustPackage;
```

This broke as of https://github.com/NixOS/nixpkgs/commit/0852f8eb8481cfa310a131017a0e73f2333c8bba.

**Comment by tianze0926** [comment]
In my case I had been including wezterm in my flake, which uses `nixos-unstable` while wezterm uses `nixpkgs-unstable`. And removing the `inputs.nixpkgs.follows` statement fixed the error:
```diff
--- a/flake.nix
+++ b/flake.nix
@@ -2,10 +2,7 @@
   description = "My personal NUR repository";
   inputs = {
     nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
-    wezterm = {
-      url = "github:wez/wezterm?dir=nix";
-      inputs.nixpkgs.follows = "nixpkgs";
-    };
+    wezterm.url = "github:wez/wezterm?dir=nix";
   };
   outputs = { self, nixpkgs, ... } @ inputs:
     let
```

**Comment by lilyinstarlight** [comment]
Yeah COSMIC uses rustc from rust-overlay while the rustc in NixOS stable is still too old. I'll take a look at what can fix that downstream

**Comment by minhtrancccp** [comment]
> Please report to wherever your rustc comes from. They should provide `targetPlatforms` and `badTargetPlatforms` attributes listing which platform doubles their rustc can build for.

per the maintainer's response, i will close this issue. if anyone else faces the same error, check if any of the flakes has `rustPlatform*`, and report the issue to the rust input of that flake.
