### ISSUE TITLE
Build failure: distrho

### ISSUE THREAD

**Issue by bendi-github** [NixOS/nixpkgs#348871]
### Steps To Reproduce

1.  `nix build https://github.com/NixOS/nixpkgs/archive/refs/heads/master.zip#distrho`

### Build log

https://gist.github.com/bendi-github/c2e07355f4078f8188a7d900a204f914

### Notify maintainers

@cillianderoiste 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
It seems the same issue is present in the `helm` package, (invalid pointer conversion in JUCE)

**Comment by TheRedstoneDEV-DE** [comment]
Update: I did manage to successfully build Distrho-Ports manually, by setting up a nix-shell environment with all of the dependencies. It wasn't a really problematic issue, just a type mismatch with the new version of the freetype font (library) in the rather old JUCE 5 library, that is used for Distrho-Ports and some other audio plugins. I opened an [issue](https://github.com/DISTRHO/JUCE/issues/24) and a draft [PR](https://github.com/DISTRHO/JUCE/pull/23) at the according repository. 
I hope it gets resolved soon, so we can move on to updating the nixpkg for it.
(I personally moved to stable for now, so I can still use the plugin)

**Comment by SigmaSquadron** [comment]
So, I've been targeting `distrho` for this release's ZHF, and just adding the `-fpermissive` flag is enough to fix the build for now. Still, considering the last release of `-ports` was in 2021, I'm inclined to just drop the package as unmaintained upstream.
