### ISSUE TITLE
file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#348970]
### Describe the bug
       … while calling anonymous lambda
         at /etc/nixos/overlays-compat/overlays.nix:6:7:
            5|
            6| self: super:
             |       ^
            7| with super.lib;

       … while calling the 'foldl'' builtin
         at /etc/nixos/overlays-compat/overlays.nix:13:3:
           12|   # Apply all overlays to the input of the current "main" overlay
           13|   foldl' (flip extends) (_: super) overlays self    # 也可用
             |   ^
           14|

       … while calling the 'import' builtin
         at /etc/nixos/overlays-compat/overlays.nix:10:15:
            9|   # Load the system config and get the `nixpkgs.overlays` option
           10|   overlays = (import <nixpkgs/nixos> { }).config.nixpkgs.overlays; # nixpkgs/nixos
             |               ^
           11| in

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at /etc/nixos/overlays-compat/overlays.nix:10:22:
            9|   # Load the system config and get the `nixpkgs.overlays` option
           10|   overlays = (import <nixpkgs/nixos> { }).config.nixpkgs.overlays; # nixpkgs/nixos
             |                      ^
           11| in

       error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)

### Steps To Reproduce
follow by https://nixos.wiki/wiki/Overlays  Section Applying overlays automatically ：On the system level
sudo nixos-rebuild switch --flake '/etc/nixos#prehonor' --impure --show-trace

### Expected behavior
 file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, NixOS, 24.11 (Vicuna), 24.11.20241014.a3c0b3b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/home/prehonor/.nix-defexpr/channels/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
Flakes don't support taking stuff from NIX_PATH impurely. You're supposed to pass flake inputs explicitly.
