### ISSUE TITLE
edl: package includes proprietary vendor binaries, yet is not marked unfree

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#348931]
### Describe the bug

The vast majority of [loaders in the `edl` package](https://github.com/bkerler/Loaders/) are of unknown origin, and were not provided "under license" for use for the project.

The package should have been licensed as unfree.

The NixOS cache now is holding hundreds of unlicensed proprietary, binaries. It *probably* should be cleaned given the number of intellectual property holders involved.

I'm filing the issue as a courtesy.

¯\\\_(ツ)\_/¯

(oh, also, the license of the project changed since back then.)

### Notify maintainers

@lorenz @xddxdd 

also @SuperSandro2000  who merged in #216708.

**Comment by winterqt** [comment]
License change done in #348934.

**Comment by winterqt** [comment]
Note that the package was also [unilaterally relicensed to GPL](https://github.com/bkerler/edl/commit/b227c4c17e34470818fd36c9a2cef65bd5395773), yikes.

**Comment by ttlns** [comment]
> The vast majority of [loaders in the `edl` package](https://github.com/bkerler/Loaders/) are of unknown origin, and were not provided "under license" for use for the project

There is also an unknown binary executable `fastpwn` packaged with the project.

See https://github.com/bkerler/edl/issues/727
