### ISSUE TITLE
Plasma 6 External Display Hard Lockup

### ISSUE THREAD

**Issue by alexyao2015** [NixOS/nixpkgs#348953]
### Describe the bug
I have plasma6 enabled with Wayland on NixOS 24.05.20241007.1bfbbbe.

The below steps causes a full hard display lockup that requires a hard reboot (press and hold power button). I've observed that the processes continue running in the background (e.g. audio from video continues playing) even while the display, mouse, and keyboard (not even caps/num lock work) are completely frozen. Sysrq commands also do not function in this state. 

I have reproduced this on two different laptop models (LG Gram 16Z90S and HP ProBook 455 G9) both on NixOS. I have tried Solus linux with plasma 6.1.5 and do not see this issue either. Additionally, I have upgrade to nix unstable and also continue to see this same issue. 

### Steps To Reproduce
0. Use wayland. This does not occur in x11.
1. Attach external display to laptop. I am using an HDMI cable.
2. Disable all other displays in kde using "Display Configuration"
3. Unplug HDMI cable from laptop.
4. Plug HDMI cable back in.
5. Attempt to drag an existing window or open a new window and drag it. Specifically dragging the window is what causes the hard lockup.

### Expected behavior
No hard lockup/freezing

### Additional context

Ref: https://bugs.kde.org/show_bug.cgi?id=494619

Nix config

```
services.xserver.enable = false;
services.displayManager.sddm.enable = true;
services.desktopManager.plasma6.enable = true;
services.displayManager.defaultSession = "plasma";
services.displayManager.sddm.wayland.enable = true;
```

### Notify maintainers

@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 24.05 (Uakari), 24.05.20241014.c0b1da3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/wdk3xa0vwx7swjdl1samf1bccvyyzfc1-source`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
That is very strange. Can you try a newer kernel than 6.10? Can you also try the latest nixos-unstable? That should have Plasma 6.2.1 and Qt 6.8.

**Comment by alexyao2015** [comment]
I am unable to reproduce on a clean install with my same config. Since this now looks like something is wrong with the contents of my home directory and not a packaging issue, I will close this.

**Comment by alexyao2015** [comment]
Discovered the actual cause of the bug here. I was using the kzones plugin. After turning it off, I no longer experienced this behavior.

**Comment by alexyao2015** [comment]
@K900 Could you give this a try with the `kdePackages.kzones` installed from nix unstable? I am able to reproduce it on wayland with the extension installed.

**Comment by K900** [comment]
If this only happens with a specific script, it should probably be reported to that script's upstream.

**Comment by alexyao2015** [comment]
Hmm okay I've already reported it here https://github.com/gerritdevriese/kzones/issues/109
