### ISSUE TITLE
Build failure: teleport

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#348922]
### Steps To Reproduce

1. build `teleport_14`, `teleport_15`, or `teleport` = `teleport_16`

### Build log

```
link: github.com/segmentio/parquet-go/hashprobe/aeshash: invalid reference to runtime.aeskeysched
```

https://hydra.nixos.org/build/274252696
https://hydra.nixos.org/build/274252825
https://hydra.nixos.org/build/274709033

### Additional context

- #342429
- parquet-go/parquet-go#142
- gravitational/teleport#45473

### Notify maintainers

@arianvp @justinas  @sigma @tomberek @freezeboy @techknowlogick

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, NixOS, 24.11 (Vicuna), 24.11.git.42a12a0551a5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by winterqt** [comment]
N.B. this is x86_64 only because of https://github.com/segmentio/parquet-go/blob/5d42db8f0d4728c31759068f08da15df44c6cc7f/hashprobe/aeshash/aeshash_amd64.s.
