### ISSUE TITLE
Build failure: haskellPackages.unordered-containers checks are freezing

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#349053]
### Steps To Reproduce

~~No idea how to track it down yet because it doesn't happen with `nix build .#pkgsi686Linux.haskellPackages.unordered-containers` or `nix build .#haskellPackages.unordered-containers`~~

~~Possible to reproduce by cloning https://github.com/surfaceflinger/flake, reverting `7e302a5031895b779f0e813d736142ba15402730` and running `nixos-rebuild build --flake .#blahaj`~~

possible to reproduce by building `obs-vkcapture` without nixpkgs commit d7198131df8707823cdbe1ac3d370939ddb26df0

### Build log

```
unordered-containers> [10 of 10] Linking dist/build/unordered-containers-tests/unordered-containers-tests
unordered-containers> Running phase: checkPhase
unordered-containers> Running 1 test suites...
unordered-containers> Test suite unordered-containers-tests: RUNNING...
unordered-containers> All
unordered-containers>   Properties
unordered-containers>     Data.HashMap.Lazy
unordered-containers>       instances
unordered-containers>         Eq
unordered-containers>           ==:                              OK
unordered-containers>             +++ OK, passed 100 tests.
```

### Additional context

https://github.com/haskell-unordered-containers/unordered-containers/issues/491
Someone else also spotted it in https://discourse.nixos.org/t/help-using-overlays-with-flake-parts/54321

Maybe the package could get rolled back to an older version or if it works fine after building, just turn off checks for now?

### Notify maintainers

idk for now

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.65d98cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/nat/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/nat/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/nat/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/nat/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/0nrvyvki12xmq6ccidgrin0k0c9hf136-gnome-settings-daemon-46.0/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cfl6rqw64ndbh2m0qapg410jf4xmycia-lix-2.91.0/share`
 - nixpkgs: `/nix/store/y4rmd9g036gmgz5xjiplw1zcbi16fqdr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by HyperCrusher** [comment]
This was also happening on my system, could build the package fine but when the checks came it would freeze at the same step.

**Comment by surfaceflinger** [comment]
Can confirm that #349081 helped, but ig this package is still problematic for now and might break something again until the upstream issue is fixed or is somehow worked around in nixpkgs

**Comment by Hannes1909** [comment]
Can confirm, unordered-container tests did hang for me at:

```
Test suite unordered-containers-tests: RUNNING...
All
  Properties
    Data.HashMap.Lazy
      instances
        Eq
```

Disabling obs-vkcapture in home-manager did the trick. Thanks!

**Comment by ashleyghooper** [comment]
I've had this issue for a while due to wanting to run the i686 version of `etlegacy`, which mysteriously pulls in haskell/unordered-containers.

I was using an overlay with `doCheck = false` but that's no longer working, as now the entirety of haskell seems to require compilation, and the `hackage-security` tests are failing on my system.

**Comment by fliiiix** [comment]
I tried to patch the overflow mention in the upstream issue and got the tests passing with that on 64bit but adding the patch to nix and building it 32bit did not a lot still hangs.

Full disclaimer im not a haskell program nor do i fully understand how the haskell stuff is packaged in nix.

```
From 4612dc3147b6f2da3fa76927b04acf78f02f811f Mon Sep 17 00:00:00 2001
From: fliiiix <hi@l33t.name>
Date: Wed, 30 Oct 2024 09:08:08 +0100
Subject: [PATCH] wip: fix haskel

---
 .../haskell-modules/configuration-common.nix        |  2 ++
 .../haskell-modules/hackage-packages.nix            |  2 ++
 .../patches/unordered-containers-overflow.patch     | 13 +++++++++++++
 3 files changed, 17 insertions(+)
 create mode 100644 pkgs/development/haskell-modules/patches/unordered-containers-overflow.patch

diff --git a/pkgs/development/haskell-modules/configuration-common.nix b/pkgs/development/haskell-modules/configuration-common.nix
index ac803a879211..b267faaf31f3 100644
--- a/pkgs/development/haskell-modules/configuration-common.nix
+++ b/pkgs/development/haskell-modules/configuration-common.nix
@@ -1382,6 +1382,8 @@ self: super: {
   # Fix build with attr-2.4.48 (see #53716)
   xattr = appendPatch ./patches/xattr-fix-build.patch super.xattr;
 
+  unordered-containers = appendPatch ./patches/unordered-containers-overflow.patch super.unordered-containers;
+
   esqueleto =
     overrideCabal
       (drv: {
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index 8439316bbc99..77eb7ba2ccd3 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -322110,6 +322110,8 @@ self: {
        ];
        description = "Efficient hashing-based container types";
        license = lib.licenses.bsd3;
+       #TODO
+       #doCheck = false;
      }) {};
 
   "unordered-containers-rematch" = callPackage
diff --git a/pkgs/development/haskell-modules/patches/unordered-containers-overflow.patch b/pkgs/development/haskell-modules/patches/unordered-containers-overflow.patch
new file mode 100644
index 000000000000..fbc43eb40469
--- /dev/null
+++ b/pkgs/development/haskell-modules/patches/unordered-containers-overflow.patch
@@ -0,0 +1,13 @@
+Index: unordered-containers/tests/Util/Key.hs
+===================================================================
+--- unordered-containers.orig/tests/Util/Key.hs
++++ unordered-containers/tests/Util/Key.hs
+@@ -56,7 +56,7 @@ moreCollisions :: Int -> Int
+ moreCollisions w = fromIntegral (w .&. mask)
+ 
+ mask :: Int
+-mask = sum [bit n | n <- [0, 3, 8, 14, 61]]
++mask = sum [bit n | n <- [0, 3, 8, 14, 31]]
+ 
+ keyToInt :: Key -> Int
+ keyToInt (K h x) = h * fromEnum x
-- 
2.34.1

```

**Comment by AnthonyUtt** [comment]
Currently seeing this issue on both `unstable` and `unstable-small` channels, seems to be coming from `haskellPackages.ShellCheck`, which is littered all over my system flake. I haven't been able to update for a few weeks now, going to try out overriding `unordered-containers` in an overlay and see if that fixes it for now. Will update back here later.

**Comment by IamTheCarl** [comment]
I am encountering this issue as I try to build an installer image for a 32bit system.
I do not have obs-vkcapture installed. My environment is running in an LXC container (it's a build grunt) so I'm wondering if it's something in the kernel that causes the issue.

Here is the output of `nix-shell -p nix-info --run "nix-info -m"`.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12-4-pve, NixOS, 24.05 (Uakari), 24.05.6668.e8c38b73aeb2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by AnthonyUtt** [comment]
Update: after figuring out that another host built with the same flake was not having any issues, I was able to narrow down my issue to `v4l-utils`, which I had included as an extra lib for a couple of programs (Lutris and Bottles). Removing that lib has allowed me to build my system properly again.

**Comment by IamTheCarl** [comment]
I do not have v4l-utils installed, however I do find it interesting that now two of the packages discovered to cause this problem have something to do with video capture. I am wondering if there is a common dependency between those two (I could see obs depending on v4l in general) causing the issue. Searching through the dependency tree manually, I didn't find v4l-utils in obs-vkcapture's dependencies, but my search wasn't exhaustive.

v4l-utils has a dependency on libjpeg, which I did find on my system. I didn't find any of v4l-utils' other dependencies on my system.

**Comment by surfaceflinger** [comment]
#359690 got merged and should be available in unstable soon https://nixpk.gs/pr-tracker.html?pr=359690

@sternenseemann maybe it should also get backported to 24.11?
