### ISSUE TITLE
Plasma 6.2 HEIC/HEIF image support broken

### ISSUE THREAD

**Issue by mrbrownt** [NixOS/nixpkgs#349152]
### HEIF/HEIC image support is gone
- HEIF/HEIC image support is missing from  plasma 6.2, my desktop now crashes as I had a HEIC image set for each of them. 
- Gwenview is no longer able to open HEIC images

### Expected behavior
HEIF/HEIC images should load like they did in plasma 6.1.5

### Notify maintainers
@K900

**Comment by K900** [comment]
Known issue with Qt 6.8, will be fixed in the next staging cycle.
