### ISSUE TITLE
System Monitor Sensor Freeze

### ISSUE THREAD

**Issue by alexyao2015** [NixOS/nixpkgs#349162]
### Describe the bug
Creating a system monitor widget on a panel with the type application causes the plasma to freeze. Rebooting doesn't help either. On boot, the entire workspace completely freezes. The only way to fix this is to switch to another user and manually edit `~/.config/plasma-org.kde.plasma.desktop-appletsrc` to remove the widget.

This does not occur on Solus Linux with 6.1.5 of plasma.

I've also reproduced this on a fresh nixos install with a minimal config

```
services.xserver.enable = true;
services.displayManager.sddm.enable = true;
services.desktopManager.plasma6.enable = true;
services.displayManager.defaultSession = "plasma";
services.displayManager.sddm.wayland.enable = true;
```

### Steps To Reproduce
1. Add a system monitor widget to your panel
2. Configure the widget and change the display style to "Applications grid"
3. Observe complete system freeze

### Expected behavior
No lockup

### Notify maintainers
@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 24.05 (Uakari), 24.05.20241014.c0b1da3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/wdk3xa0vwx7swjdl1samf1bccvyyzfc1-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Again, have you tested this on unstable?

**Comment by alexyao2015** [comment]
Okay huge improvement on unstable. No issues there. Sorry about the false reports.
