### ISSUE TITLE
Package request: vscode-php-debug

### ISSUE THREAD

**Issue by vyxn** [NixOS/nixpkgs#349132]
**Project description**
PHP Debug Adapter for Visual Studio Code 🐞⛔ 

**Metadata**

* homepage URL: https://github.com/xdebug/vscode-php-debug
* source URL: https://github.com/xdebug/vscode-php-debug
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
This is already available under [`vscode-extensions.xdebug.php-debug`](https://search.nixos.org/packages?channel=24.05&show=vscode-extensions.xdebug.php-debug).

**Comment by vyxn** [comment]
Thank you very much, I looked for it before and couldn't find it with its full name.
