### ISSUE TITLE
nixos-rebuild: unknown option `-I'

### ISSUE THREAD

**Issue by cilki** [NixOS/nixpkgs#349182]
### Describe the bug
The nixos-upgrade service seems to be passing an `-I` option to nixos-rebuild:

```console
Oct 16 21:17:17 dev-1798 systemd[1]: Starting NixOS Upgrade...
Oct 16 21:17:26 dev-1798 nixos-upgrade-start[88190]: /nix/store/m1s6xipa01v1vpaa3j33hmkvh84bd8mz-nixos-rebuild/bin/nixos-rebuild: unknown option `-I'
Oct 16 21:17:26 dev-1798 systemd[1]: nixos-upgrade.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 21:17:26 dev-1798 systemd[1]: nixos-upgrade.service: Failed with result 'exit-code'.
Oct 16 21:17:26 dev-1798 systemd[1]: Failed to start NixOS Upgrade.
Oct 16 21:17:26 dev-1798 systemd[1]: nixos-upgrade.service: Consumed 5.045s CPU time, 1G memory peak, 32.3M incoming IP traffic, 59.1K outgoing IP traffic.
```

### Expected behavior
No errors about unknown flags and the upgrade completes successfully.

### Additional context
The upgrade service has been working fine for about 60+ generations. I haven't made any changes to configuration.nix recently, so this seems to have arisen from a recent upgrade. This system is on the unstable channel.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11pre685764.1925c603f17f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
Bug is being tracked. Cant find the PR rn but when I do I'll link it

**Comment by ryardley** [comment]
I am not sure if this should be in a different issue but all of a sudden this is now failing when it used to work:

```
nixos-rebuild switch -I ./system/configuration.nix
```

Is there another deprecation issue here? What is the workaround?

**Comment by Atemu** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/348886
