### ISSUE TITLE
Prismlauncher: does not open

### ISSUE THREAD

**Issue by bendi-github** [NixOS/nixpkgs#349238]
### Describe the bug
Prismlauncher does not open. Launching packs via the command line `prismlauncher --launch` works.

### Steps To Reproduce
One of:
- Run prismlauncher installed via system configuration on a flake-based system 
```nix
 environment.systemPackages = with pkgs; [
    (prismlauncher.override {
      jdks = [
        jdk21
        jdk8
        jdk17
      ];
```
- `nix run nixpkgs#prismlauncher`
- `nix run https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-24.05.zip#prismlauncher` 

### Expected behavior
Prismlauncher opens and works as expected

### Error Message
`QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
QLocalSocket::setServerName() called while not in unconnected state`

### Notify maintainers
@Minion3665 @Scrumplex @getchoo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241014.a3c0b3b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/xnjw9gmfmpppdj6bxpw6cfkspc3h6xwl-source`
```

`prismlauncher --version`
```console
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
PrismLauncher 8.4
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by C0D3-M4513R** [comment]
I have the same issue. How did you fix this?
