### ISSUE TITLE
install: cannot remove '/tmp/env-vars': Operation not permitted message on every `nix-shell` invocation

### ISSUE THREAD

**Issue by paparodeo** [NixOS/nixpkgs#349206]
### Describe the bug
if `/tmp/env-vars` exists and is not owned by the current user `nix-shell` prints an error message:
```
install: cannot remove '/tmp/env-vars': Operation not permitted
```

### Steps To Reproduce

```
$ nix-shell -p bash --command exit
$ ssh another-user@localhost 'nix-shell -p bash --command exit'
install: cannot remove '/tmp/env-vars': Operation not permitted
```

### Expected behavior
no error message is printed, per user temporary files do not use common paths

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
install: cannot remove '/tmp/env-vars': Operation not permitted
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-45-generic, Ubuntu, 22.04.5 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
https://github.com/NixOS/nix/issues/11470
