### ISSUE TITLE
Decent Sampler VST Error

### ISSUE THREAD

**Issue by Byteingpython** [NixOS/nixpkgs#349256]
### Describe the bug
The Decent Sampler VST-Plugin cannot be loaded by my DAW (Bitwig Studio). Bitwig gibes me the following Error Messages

> com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 2 plug-in /run/current-system/sw/lib/vst/DecentSampler.so: libnghttp2.so.14: cannot open shared object file: No such file or directory

> com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 3 plug-in /run/current-system/sw/lib/vst3/DecentSampler.vst3: libnghttp2.so.14: cannot open shared object file: No such file or directory

### Steps To Reproduce
1. Install Bitwig Studio and Decent Sampler
2. In Bitwig go to Settings -> Plug-ins and click on "Show plug-in errors" at the bottom

### Notify maintainers

@adam248 

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

**Comment by chewblacka** [comment]
`decent-sampler` appears not to be building at the moment because internet archive (where it stores its icon) is in read-only mode. Might be the source of the issue?

**Comment by Byteingpython** [comment]
For me this error is not resolved. Bitwig still shows me the following errors:

```
/run/current-system/sw/lib/vst/DecentSampler.so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 2 plug-in /run/current-system/sw/lib/vst/DecentSampler.so: libnghttp2.so.14: cannot open shared object file: No such file or directory
-------------------------------------------------------------------

/run/current-system/sw/lib/vst3/DecentSampler.vst3

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load VST 3 plug-in /run/current-system/sw/lib/vst3/DecentSampler.vst3: libnghttp2.so.14: cannot open shared object file: No such file or directory
-------------------------------------------------------------------
```

**Comment by chewblacka** [comment]
I can't seem to replicate the error. When I go to "Show plug-in errors" it is blank.

Is there something else I need to do?

**Comment by chewblacka** [comment]
Ok I realized I had to manually add the `/run/current-system/sw/lib/vst/` and `/run/current-system/sw/lib/vst3` folders inside the plugin-locations option within bitwig. Am getting the same error.

**Comment by chewblacka** [comment]
It's actually a `bitwig-studio` issue not a `decent-sampler` issue per se. `bitwig-studio` was missing the `libnghttp2` library needed to read the `decent-sampler` vst files. I've put in a PR to `bitwig-studio` which fixes the issue (tested as working).
