### ISSUE TITLE
nvidia_x11 override via overlay not possible

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#34938]
## Issue description
I like to backport nvidia_x11 module from nixos-unstable to nixos-17.09.

### Steps to reproduce
Import following NixOS module and run "nixos-rebuild boot" the new version is not available.
```
{ ... }: {
  nixpkgs.overlays = [(self: super: {
    linuxPackages = super.linuxPackages // {
      nvidia_x11 = super.linuxPackages.nvidia_x11.overrideAttrs (s: rec {
        version = "390.25";
        name = (builtins.parseDrvName s.name).name + "-" + version;
        src = super.fetchurl {
          url = "https://download.nvidia.com/XFree86/Linux-x86_64/${version}/NVIDIA-Linux-x86_64-${version}.run";
          sha256 = "0whsls1mm6vkll5qmxnyz8vjgspp1rmqpsampgi83k62n514c08r";
        };
      });
    };
  })];

  nixpkgs.config.allowUnfree = true;

  services.xserver.videoDrivers = [ "nvidia" ];
}
```

## Technical details
Approach is to override nvidia_x11 via overlay.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09pre117270.59890bb1351 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by FRidh** [comment]
I think you have to use `.extend` instead:
```
linuxPackages = super.linuxPackages.extend(selfLinux: superLinux {
  nvidia_x11 = superLinux.linuxPackages....
}
```

**Comment by ck3d** [comment]
Again what learned, thanks!
