### ISSUE TITLE
Reference to `elixir` is not substitued in `elixir-ls` launch script

### ISSUE THREAD

**Issue by thomaseizinger** [NixOS/nixpkgs#349446]
### Describe the bug

I am trying to use `elixir-ls` within `zed` and it fails to launch with:

```
/nix/store/sq172vrw9sai9yqjk2ph44qmrngnjyv5-elixir-ls-0.21.1/lib/launch.sh:108: command not found: elixir
```

That particular line corresponds to this line here in the upstream repository:

https://github.com/elixir-lsp/elixir-ls/blob/3a77d8c899c9dc7f94c9b4345b2eb24f99a62c7c/scripts/launch.sh#L117

And indeed, when I look at what is in my Nix store in that script, I see the following:

```bash
# ... other lines omitted

echo "" | elixir "$SCRIPTPATH/quiet_install.exs" >/dev/null || exit 1
#         ^^^^^^ This fails.

# ... other lines omitted
```

It appears as though the following needs to be extended to also replace this reference to `elixir` with an absolute path:

https://github.com/NixOS/nixpkgs/blob/dc2e0028d274394f73653c7c90cc63edbb696be1/pkgs/development/beam-modules/elixir-ls/default.nix#L57-L60

### Steps To Reproduce
1. Install zed from their repository (`zed-editor.url = "github:zed-industries/zed/nightly";` and `zed-editor.packages.${pkgs.system}.default`
2. Install `elixir-ls`
3. Attempt to edit an Elixir file

### Expected behavior

The Elixir language server to get started.

### Notify maintainers

@ankhers @Br1ght0ne @DianaOlympos @gleber @happysalada @minijackson @yurrriq

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.05 (Uakari), 24.05.20241009.d51c286`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager-23.11.tar.gz, nixos-23.11, nixos-hardware"`
 - nixpkgs: `/nix/store/m1szqwijms610n6325mwjswslha4nd92-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thomaseizinger** [comment]
Possibly related: https://github.com/NixOS/nixpkgs/issues/276573

**Comment by yurrriq** [comment]
I doubt I can be much help here. What is `zed`?

**Comment by thomaseizinger** [comment]
> I doubt I can be much help here. What is `zed`?

Zed is an editor: https://zed.dev/

**Comment by happysalada** [comment]
I think youve correctly identified the problem. Would you be willing to test your fix and submut a PR ? We would be happy to help get it merged

**Comment by thomaseizinger** [comment]
> I think youve correctly identified the problem. Would you be willing to test your fix and submut a PR ? We would be happy to help get it merged

I am happy to send a PR if I get some guidance on how implement this in a Nix-idiomatic way! (I am still a Nix beginner).

I looked at the other substitutions and they all check for entire paths which doesn't work here I think and the word "elixir" occurs in other places in the script too!

Are there more sophisticated "patching tools" we can use?

**Comment by thomaseizinger** [comment]
I guess what we could do is match on the entire line including `echo "" | `?

**Comment by happysalada** [comment]
Exactly matching on a larger part is indeed the easiest solution in this case.
Let me know if you need anything else.

**Comment by thomaseizinger** [comment]
How would I test this? This is the flake that I am using: https://github.com/firezone/firezone/blob/main/scripts/nix/flake.nix

**Comment by thomaseizinger** [comment]
I opened a PR here: https://github.com/NixOS/nixpkgs/pull/349985. Still working on testing this.

**Comment by happysalada** [comment]
In your flake, you replace nixpkgs url with the url of your PR, and then you should have the elixir-ls that you built

**Comment by thomaseizinger** [comment]
> In your flake, you replace nixpkgs url with the url of your PR, and then you should have the elixir-ls that you built

I managed it with the following:

```nix
      pkgs-unstable' =
        (import nixpkgs {
          system = "x86_64-linux";
        }).applyPatches
          {
            name = "nixpkgs-patched";
            src = inputs.nixpkgs;
            patches = [
              (builtins.fetchurl {
                url = "https://github.com/NixOS/nixpkgs/commit/e592a523114e3f2d02d61717e4cb9c514710c3db.patch";
                sha256 = "1wdfa9a4fgzkhr8v59vv4wy5qhx8d8b7f43prjm8z2jp8r00slj6";
              })
              (builtins.fetchurl {
                url = "https://github.com/NixOS/nixpkgs/commit/435051f990d1cbf724a8973e6d8449f686cba18f.patch";
                sha256 = "0jasncsm472xadf6fssl7y5nsyzq28bbp3y99z71jnlxg6g1vhgp";
              })
            ];
          };
      pkgs-unstable = import pkgs-unstable' {
        system = "x86_64-linux";
      };
```
