### ISSUE TITLE
Update request: libspelling 0.2.1 → 0.4.3

### ISSUE THREAD

**Issue by Integral-Tech** [NixOS/nixpkgs#349477]
- Package name: libspelling
- Latest released version: 0.4.3

- Current version on the unstable channel: 0.2.1
- Current version on the stable/release channel: 0.2.1

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@chuangzhu 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
(for possible merge conflicts, 0.4.2 is on [staging-next](https://github.com/NixOS/nixpkgs/commits/staging-next/pkgs/development/libraries/libspelling/default.nix))

**Comment by Integral-Tech** [comment]
Is it ready to merge now?

> (for possible merge conflicts, 0.4.2 is on [staging-next](https://github.com/NixOS/nixpkgs/commits/staging-next/pkgs/development/libraries/libspelling/default.nix))
