### ISSUE TITLE
Documentation: nixfmt error shows an invalid command

### ISSUE THREAD

**Issue by viraptor** [NixOS/nixpkgs#349424]
## Problem

When some change [fails the formatting rules](https://github.com/NixOS/nixpkgs/actions/runs/11361780921/job/31602219282?pr=348978#step:7:51), the error says:
```
Some new/changed Nix files are not properly formatted
Please go to the Nixpkgs root directory, run `nix-shell`, then:
nixfmt 'pkgs/development/interpreters/gauche/boot.nix'
If you're having trouble, please ping @NixOS/nix-formatting
```
But running nix-shell in root is not possible:
```
$ nix-shell
error:
       … while calling the 'throw' builtin

         at /Users/viraptor/src/nixpkgs/pkgs/top-level/all-packages.nix:106:36:

          105|   ### Evaluating the entire Nixpkgs naively will fail, make failure fast
          106|   AAAAAASomeThingsFailToEvaluate = throw ''
...
```

## Proposal

Fix the error message to be possible to run.

@NixOS/nix-formatting 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
Cannot reproduce, and can't know what's the problem for you since you didn't include the full error :sweat_smile: 

Also, CI [checks that the `shell.nix` file works](https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/check-shell.yml) and that's [not failing](https://github.com/NixOS/nixpkgs/actions/workflows/check-shell.yml).

**Comment by viraptor** [comment]
I realised I checked out an ancient branch 🤦 
Let me close this then...
