### ISSUE TITLE
Build failure: pyreqwest-impersonate

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#349432]
### Build log

https://hydra.nixos.org/build/274261734

Looks like missing a NEEDED of libstdc++?

### Notify maintainers

@drupol 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
I tried to fix it in #349616 (pyreqwest-impersonate has been renammed PRIMP), without luck so far. Do you have a clue?

**Comment by yshui** [comment]
at the moment i just manually patch in the required rpath/needed:

```
          ${final.patchelf}/bin/patchelf --add-rpath ${final.gcc-unwrapped.lib}/lib --add-needed libstdc++.so.6 $out/lib/python3.12/site-packages/pyreqwest_impersonate/pyreqwest_impersonate.cpython-312-x86_64-linux-gnu.so
```

it's very hacky but it works. i don't quite know how to make `autoPatchelfHook` to add `libstdc++`. maybe there's a more idiomatic way of doing this but idk.

**Comment by drupol** [comment]
I have no clue on how to fix this gracefully... sorry :( I'll leave the PR open, hopefully someone will chime in at some point.

**Comment by drupol** [comment]
I pushed some changes based on your fix, it works, and I would have hoped we could have a better solution :(
