### ISSUE TITLE
matrix-synapse requires pynacl==0.3.0

### ISSUE THREAD

**Issue by Necronian** [NixOS/nixpkgs#34959]
## Issue description

pynacl was updated from 0.3.0 to 1.2.1 however matrix-synapse depends on pynacl==0.3.0 and therefore will no longer build.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 18.03pre127302.e860b651d6e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127867.6acfa356ddc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bachp** [comment]
The best solution might be to backport https://github.com/matrix-org/synapse/pull/2888 if it gets accepted.
