### ISSUE TITLE
Build failure: PureRef

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#349517]
### Steps To Reproduce

It looks like the key mechanism has changed, you can test it like this:

```bash
$ key="$(curl "https://www.pureref.com/download.php" --silent | grep '%3D%3D' | cut -d '"' -f2)"

$ echo $key
C0TwqEx6ZwDnS9l0W4rKVQ%3D%3D

$ curl -L "https://www.pureref.com/files/build.php?build=LINUX64.Appimage&version=2.0.3&downloadKey=$key" --output PureRef-2.0.3_x64.Appimage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

$ file PureRef-2.0.3_x64.Appimage
PureRef-2.0.3_x64.Appimage: empty
```

### Notify maintainers
@ElnuDev 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
Looks like they now hand out a "bad" download key if your user agent is cURL. Clearing the UA seems to work:

```shell
$ key=$(curl -H "User-Agent:" "https://www.pureref.com/download.php" --silent | grep '%3D%3D' | cut -d '"' -f2)                                                      
$ curl -L "https://www.pureref.com/files/build.php?build=LINUX64.Appimage&version=2.0.3&downloadKey=$key" --output PureRef-2.0.3_x64.Appimage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 28.7M  100 28.7M    0     0  18.3M      0  0:00:01  0:00:01 --:--:-- 28.6M
$ file PureRef-2.0.3_x64.Appimage 
PureRef-2.0.3_x64.Appimage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

**Comment by musjj** [comment]
Yeah, adding a user agent fixes it. It looks like they do the same thing in the AUR package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pureref

**Comment by ElnuDev** [comment]
I'm getting very frustrated with the way pureref distributes their software. If I remember correctly, a while back they broke the derivation by changing the binary without a version update, now this. I'm honestly tempted just to contact them at this point, if they're specifically blocking out requests from cURL then perhaps they're under the impression that nixpkgs traffic is bots/malicious. Their download key system is annoying as hell to begin with.

@jackwilsdon I'll try to get together a PR that clears the UA post later today or tomorrow. Maybe to future-proof it we should just put in a Chrome one just to play it safe.

**Comment by husjon** [comment]
I was about to install pureref and found the same issue, I was about to start looking into creating a PR but then found this issue.


@ElnuDev Although not ideal would it be an alternative to do something similar as what is done with the DisplayLink drivers by prefetching the binary into the store?
See https://nixos.wiki/wiki/Displaylink for reference.

Nix file in charge of checking for the pre-existing file is here https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/displaylink/default.nix#L33-L54

I could give it a shot by implementing it this way as an alternative.
