### ISSUE TITLE
syncthing-inotify is deprecated

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#34957]
## Issue description

Apparently `syncthing-intofy` is now deprecated[1] and its functionality included in the main syncthing package. I'd do a PR to "fix" this in nixpkgs myself, but I'm not sure how to deal with this kind of situation. For now `syncthing-inotify` still works, but its probably a good idea to switch to the "blessed" solution before 18.03.

@peterhoeg

[1] https://github.com/syncthing/syncthing-inotify

**Comment by peterhoeg** [comment]
Indeed it is. The nice way to handle this would be something like:

a) drop the -inotify package
b) add an "ExecStartPre" script that runs sed against the config file if ```useInotify``` is enabled and replaces ```fsWatcherEnabled="false"``` with ```fsWatcherEnabled="true"```.
c) update the description for ```useInotify``` option to reflect the situation

If you take a stab at a PR, please ping me on it and I'll help out.

**Comment by timokau** [comment]
> a) drop the -inotify package

Won't just dropping thep ackage lead to errors while updating? Isn't there
something like a deprecated flag that would just give a warning?

> b) add an "ExecStartPre" script that runs sed against the config file if useInotify is enabled and replaces fsWatcherEnabled="false" with fsWatcherEnabled="true".

Its a bit scary to just overwrite those options.
If somebody has enabled this for some folders and disabled it for others, his config will be irrevocably lost once he triggers `useInotify`.
But maybe its still the best option.

**Comment by Moredread** [comment]
As a user of that package I rather have that option deprecated with having to enable fsWatcherEnabled myself (and an explanation how to do that).

I personally would find it more annoying to have my config touched by NixOS when I don't expect it, than to have the inotify feature turned off after switching to a new channel.

I think it would be very confusing if only this one option was controlled by a NixOS option.

**Comment by timokau** [comment]
Synthing apparently plans to offer an [option that does basically the same](https://github.com/syncthing/syncthing/blob/89f929b4b0a8cdd5a6fe2a3803d6da7772611596/gui/default/syncthing/core/syncthingController.js#L1744): Simply set the `fsWatcherEnabled` Option `true` for all folders.

Since its also an option that you'd generally set for all folders anyways (at least I'd think so), maybe its a good idea in this case. It would probably be less confusing than just having `useInotify` be a noop. Then people would think inotify is used when it is not anymore.

What do you think @Moredread ?

**Comment by Moredread** [comment]
A noop would be worse, you're right.

**Comment by peterhoeg** [comment]
Please keep in mind that the nixos module only kicks in for the "run syncthing as a system service" and not for any normal users so we are only going to modify user config files if:

a. ```services.syncthing.enable``` and ```services.syncthing.useInotify``` are both true, **and**
b. A user runs another copy of syncthing in parallel to the system-wide instance and uses the systemd unit

For the ```syncthing as a system service``` which is what we configure using the nixos module, it makes sense that ```useInotify``` actually does enable inotify.

**Comment by timokau** [comment]
I just tried to implement this, but ran into difficulties. I'm running the syncthing module as a user, configured like this:

```
services.syncthing = {
    enable = true;
    useInotify = true;
    user = "timo";
};
```

Which means that the config file from my home directory is used. So we can't count on the config file being global. I think to correctly locate the config we'd pretty much have to implement the whole xdg logic.

**Comment by fpletz** [comment]
Unfortunately I don't use syncthing anymore and maybe I'm forgetting something, but couldn't we just remove `useInotify` with `mkRemovedOptionModule` and add a notice there how to enable inotify? This will print a warning on evaluation that useInotify won't have an effect anymore. This should then also be mentioned in the release notes.

**Comment by timokau** [comment]
I didn't know about `mkRemovedOptionModule`, that does seem like the best option.

But if we go that route we should wait for the next synthing update because I think the new "native" way is not yet accessible in the user interface.

**Comment by bjornfor** [comment]
> I think the new "native" way is not yet accessible in the user interface.

I'm not sure if this is the final place for turning on/of inotify, but it is available now under Settings -> Advanced -> [Your folder] -> FS Watcher Enabled (checkbox)

**Comment by peterhoeg** [comment]
> Which means that the config file from my home directory is used. So we can't count on the config file being global. I think to correctly locate the config we'd pretty much have to implement the whole xdg logic.

Referring to ```%h/.config/syncthing/config.xml``` in the context of a systemd unit should refer to the right file. But I'm learning towards @fpletz's suggestion here - this way there are no surprises.

**Comment by timokau** [comment]
> Referring to %h/.config/syncthing/config.xml in the context of a systemd unit should refer to the right file.

Really? Wouldn't the config be in `/etc/xdg` or something like that if it runs under root?

> But I'm learning towards @fpletz's suggestion here - this way there are no surprises.

And how should we deal with the `synthing-inotify` package then? Is there somthing similar to `mkRemovedOptionModule` for packages?

**Comment by peterhoeg** [comment]
> Wouldn't the config be in /etc/xdg or something like that if it runs under root?

Possible, but nobody should be running this as root.

> And how should we deal with the synthing-inotify package then?

We cannot deal gracefully with someone adding it to ```environment.systemPackages``` but if they do```services.syncthing.useNotify``` it's pretty straight forward.

**Comment by timokau** [comment]
I've deprecated `useInotify`  and removed `syncthing-inotify` in #35432.
