### ISSUE TITLE
Update request: openai-whisper-cpp 1.7.0 → 1.7.1

### ISSUE THREAD

**Issue by rodfersou** [NixOS/nixpkgs#349626]
- Package name: openai-whisper-cpp
- Latest released version: 1.7.1

- Current version on the unstable channel: 1.7.0
- Current version on the stable/release channel: 1.5.4

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@r-ryantm
@Artturin

-----

Note for maintainers: Please tag this issue in your PR.

Hello folks, great work here,

I would also like to add the `server` command line. There are a few new commands available, and it's not included in the package.

https://github.com/NixOS/nixpkgs/blob/7881fbfd2e3ed1dfa315fca889b2cfd94be39337/pkgs/tools/audio/openai-whisper-cpp/default.nix#L87-L89

![image](https://github.com/user-attachments/assets/5b1459ad-912a-4559-b9df-6362e36a860a)

Many thanks for considering my request.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/349647

**Comment by Artturin** [comment]
I'm not the maintainer for this package https://search.nixos.org/packages?channel=unstable&show=openai-whisper-cpp&from=0&size=50&sort=relevance&type=packages&query=openai-whisper-cpp

@dit7ya @hughobrien You should look in to using cmake for the package, it installs the libs too.
