### ISSUE TITLE
kde-open5 outputs an error

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34964]
## Issue description

```
kde-open5 'https://www.google.com'
Couldn't start kuiserver from org.kde.kuiserver.service: QDBusError("org.freedesktop.DBus.Error.Spawn.ExecFailed", "Failed to execute program org.kde.kuiserver: No such file or directory")
```

### Steps to reproduce
Use systemsettings5 to configure URL opening with the default option.

`kde-open5 'https://www.google.com'`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by peterhoeg** [comment]
This works for me on unstable. Any chance you can try there?

**Comment by coretemp** [comment]
I don't have a safe way to switch between stable and unstable, because configuration files might be overwritten in non-compatible ways (I wouldn't be able to switch back to stable). 

I am also not sure whether it's easy to write a script that backs up *all* KDE related configuration and allows for a restore. 

Perhaps it could be tested in a VM, but I don't have that setup either (for NixOS at least).

**Comment by peterhoeg** [comment]
Are you familiar with ```nixos-rebuild build-vm```? You can do something like this:

```sh
nixos-rebuild build-vm \
              -I nixos-config=path_to_a_minimal_config \
              -I nixpkgs=your_checked_out_nixpkgs
```

**Comment by peterhoeg** [comment]
@coretemp hasn't been active in a while, but if somebody experiences this problem, please reopen.
