### ISSUE TITLE
Update request: typst 0.11.1 → 0.12.0

### ISSUE THREAD

**Issue by 9p4** [NixOS/nixpkgs#349650]
- Package name: typst
- Latest released version: [0.12.0](https://github.com/typst/typst/releases/tag/v0.12.0)

- Current version on the unstable channel: 0.11.1
- Current version on the stable/release channel: 0.11.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@drupol @figsoda @kanashimia 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jfvillablanca** [comment]
https://github.com/NixOS/nixpkgs/pull/349652 resolves this issue
