### ISSUE TITLE
CUPS on NixOS [Chrome stopped to print]

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#34963]
## Issue description

Chrome stopped to print someday on nixos-unstable

1. Both Chrome and Firefox look for `/run/cups.sock` socket but our CUPS module only creates `/run/cups/cups.sock`
2. We only listen at `127.0.0.1` by default, but both Chrome and Firefox probe `::1` first. Firefox then fallbacks to `127.0.0.1` but Chrome by some reason doesn't and so it never prints.

### Steps to reproduce

Printing doesn't work in Chrome out of box.
After adding
`services.printing.listenAddresses = [ "::1:631" "127.0.0.1:631" ]`
to config it starts to work again.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.16, NixOS, 18.03.git.6acfa35 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127867.6acfa356ddc"`
 - nixpkgs: `/home/gnidorah/tmp/nixpkgs`

**Comment by emmanuelrosa** [comment]
Do you still have the NixOS generation for which printing *does* work? That would make it a lot easier to find the commit which caused the change.

**Comment by gnidorah** [comment]
@emmanuelrosa Unfortunately no, I've discovered this issue too lately. I don't print often.
