### ISSUE TITLE
Firefox GUI Crash

### ISSUE THREAD

**Issue by alexyao2015** [NixOS/nixpkgs#349678]
### Describe the bug
Upon opening the system file selector, Firefox crashes.

I use KDE and want to pin firefox to the taskbar. If I pin a shortcut other than the wrapped firefox, KDE will treat it as a separate app and create a new icon. Directly opening the wrapped version either using KDE or the terminal will put firefox into the state where it can crash upon opening the file selector

### Steps To Reproduce
1. Open Firefox directly from the wrapped executable. I am using the terminal in this case. 
`$ /nix/store/x8ggv18v7w248881f7nci7inyfjg7w0v-firefox-132.0b5/bin/.firefox-wrapped`
2. Open the extensions page, click the settings wheel, then click install add-on from file.
3. Observe crash

### Expected behavior
No crash

### Additional context
I understand that this problem occurs when firefox isn't launched with the correct environment variables because it isn't launched through the wrapper. If it is possible to make KDE group the wrapper and the wrapped versions on the taskbar, that would fix this issue. Right now, if I want to not experience a crash, I have two icons on my taskbar (one with the wrapped firefox and one with the unwrapped firefox post launch).
![image](https://github.com/user-attachments/assets/29a85037-9589-4bc9-b211-a1d0db0a6e58)

### Notify maintainers

@linsui

Since this is also partially a KDE issue
@K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 24.11 (Vicuna), 24.11.20241013.d4f247e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/mh44x1mn53d0cgzlq89xl78aciwxrhpv-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
I have no such issues here, so it's likely specific to the devedition package. Can you try the normal Firefox package?

**Comment by alexyao2015** [comment]
Hmm I tried this again in a VM and don't seem to have this on either the firefox packages... Will make sure to test in a VM first next time. I guess I'll go through the debugging process again.

**Comment by Ember-ruby** [comment]
I can reproduce this, at least on my system (latest nixos unstable, plasma 5, Firefox 128 esr), this state can be triggered by pinning an open window of Firefox to the task manager, instead of pinning the start menu shortcut
