### ISSUE TITLE
A possible solution for screen tearing on nVidia

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#34977]
This is more of a request for feedback than a proper issue. If you're *not* using nVidia, then this issue is probably uninteresting.

## Issue description

A lot has been said about screen tearing on nvidia. "It won't be fixed until Wayland", or "This one weird flag will prevent it", or...

None of it ever works great, but it's possible I've found something that works. At a minimum, it's eliminated screen tearing for the specific configuration I'm running; which, after years spent attempting and failing to do, is a wonderful thing.

The particular solution is described in more detail in http://www.thelinuxrain.com/articles/got-tearing-with-proprietary-nvidia-try-this, but in short, to test it:

- Add https://github.com/Baughn/machine-config/blob/master/modules/nvidia.nix to configuration.nix
- Do something that would cause tearing. You may already have something in mind. If not, https://www.youtube.com/watch?v=5xkNy9gfKOg should work.

What I'd like to do is find out if this is a universal solution. If so, then I believe we should set that setting unconditionally -- as the article says, it's a miniscule drop in performance, in exchange for a much better experience. I can't confirm the overall usefulness without hearing back from other users, though.

### Steps to reproduce

Buy an nVidia card. Use the proprietary driver. Do essentially anything where tearing would be noticable.

This may not 'work' on KDE5 with the OpenGL compositor, but often it does. It's always worked on XFCE for me.

**Comment by peterhoeg** [comment]
I can confirm that the video shows tearing but after adding 
```
services.xserver.screenSection = ''
    Option "metamodes" "nvidia-auto-select +0+0 { ForceCompositionPipeline = On }"
  '';
``` 

things are much better.

This is with KDE.

**Comment by Baughn** [comment]
With XFCE, this config causes the screen to freeze on login. It can be worked around by switching to a tty and back, once, but it's not great.

**Comment by ElvishJerricco** [comment]
This worked for me in NixOS 17.09 but not NixOS 18.03.

**Comment by KireevArtur** [comment]
@peterhoeg's config works again on Nvidia 410. On 390 it didn't work.

**Comment by ElvishJerricco** [comment]
Is it possible to use 410 on NixOS 18.09?

**Comment by Baughn** [comment]
This is really obsoleted by Nvidia-on-Wayland; there's no point in trying to solve it on Xorg at this point.
