### ISSUE TITLE
Package request: conduwuit

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#349738]
**Project description**

a featureful fork of matrix server conduit

**Metadata**

* homepage URL: https://conduwuit.puppyirl.gay/
* source URL: https://github.com/girlbossceo/conduwuit
* license: apache-2
* platforms: unix, linux, darwin, ...

**Comment by surfaceflinger** [comment]
it's already packaged https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/co/conduwuit/package.nix
