### ISSUE TITLE
Update request: glab 1.40.0 → 1.48.0

### ISSUE THREAD

**Issue by ricardogaspar2** [NixOS/nixpkgs#349735]
- Package name: glab
- Latest released version: `1.48.0`
   - see: https://gitlab.com/gitlab-org/cli/-/releases

- Current version on the unstable channel: `1.47.0` 
   - see:  https://search.nixos.org/packages?channel=unstable&show=glab&from=0&size=50&sort=relevance&type=packages&query=glab
- Current version on the stable/release channel: `1.40.0`
  - see: https://search.nixos.org/packages?channel=24.05&show=glab&from=0&size=50&sort=relevance&type=packages&query=glab 

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@freezeboy 
-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ricardogaspar2** [comment]
@khaneliman @freezeboy thank you for updating this. 
I Tried to update my home-manager (still using the unstable channel) but it's still reporting as the 1.47.
Even removed and installed again to make sure:

```
$ glab --version
Current glab version: 1.47.0
A new version of glab has been released: 1.47.0 -> v1.48.0
https://gitlab.com/gitlab-org/cli/-/releases/v1.48.0
```

**Comment by khaneliman** [comment]
I see it in unstable:
https://nixpk.gs/pr-tracker.html?pr=349813

I see it locally as the correct version:
```bash
, glab --version                       
Current glab version: 1.48.0

**Comment by ricardogaspar2** [comment]
Thank you @khaneliman. It was actually an issue with my configs and the channels.
It's working now.
I'll open a new request since gitlab updated the version to 1.49.
