### ISSUE TITLE
docker basics don't work on 17.09

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34978]
## Issue description

I see the following warning in the logs and the simplest Dockerfile doesn't work:
```
dockerd[1392]: time="2018-02-14T21:34:21.715068209+01:00" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc4+dev
```
### Steps to reproduce
User is in group docker and `virtualization.<snip>.docker.enable = true;` is in configuration.nix.

Dockerfile:

```
from ubuntu:latest
# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
```

build script
```
docker build -t ubuntu_test_box .
```

Running the built container:
```
docker run ubuntu_test_box
```

`docker ps -a | grep ubuntu_test_box`:
```
24da0c037771        ubuntu_test_box     "bash"                   11 minutes ago      Exited (0) 11 minutes ago                       goofy_lewin
```
The exit happens without user interaction, i.e. it crashed.

Expected result is a container that stays up until it is terminated.

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Baughn** [comment]
Can we see your entire configuration.nix?

The correct flag to set should be `virtualisation.docker.enable = true;`, but possibly that was different on 17.09. Try it, though?

**Comment by coretemp** [comment]
These are the only parts containing docker (next to the extraGroups "docker" entry).
```
virtualisation.docker.enable = true;
virtualisation.docker.enableOnBoot = true;
```

**Comment by LnL7** [comment]
I'm useing docker on my work machine without any problems, this looks like normal behaviour given the commands you are running. This command will probably do what you're expecting.
```
docker run -it ubuntu_test_box
```

If you don't want the container to exit and you run bash you'll want to tell docker to attach stdin, otherwise bash will just exit. Similarly you'll want to use `-t` for interactive use, bash isn't very usable without a tty.
```
$ docker run --help
...
  -i, --interactive                    Keep STDIN open even if not attached
  -t, --tty                            Allocate a pseudo-TTY
```
