### ISSUE TITLE
Build failure: python312Packages.insightface

### ISSUE THREAD

**Issue by ovitus** [NixOS/nixpkgs#349896]
nixpkg 27e30d177e57d912d614c88c622dcfdb2e6e6515

As per InsightFace Python library documentation:

**_For insightface<=0.1.5, we use MXNet as inference backend.
Starting from insightface>=0.2, we use onnxruntime as inference backend._**

onnxruntime is already included and since mxnet is a broken package, once this input is removed, the build is successful.

@oddlama

**Comment by dotlambda** [comment]
`python3.pkgs.insightface` does build perfectly fine on master

**Comment by ovitus** [comment]
It might've been because I have CUDA support enabled in my system config and that's what's broken in the MXNet package.

**Comment by dotlambda** [comment]
Maybe you should write better issues. There's an issue template for a reason.

**Comment by dotlambda** [comment]
Then I don't see a reason for this issue to remain open.
