### ISSUE TITLE
services.nginx.virtualHosts.<name>.rejectSSL does not work with angie or tengine

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#349873]
### Describe the bug

Setting `services.nginx.virtualHosts.<name>.rejectSSL` when `services.nginx.package` is `angie` or `tengine` causes the following failed assertion:

```
       error:
       Failed assertions:
       - services.nginx.virtualHosts.<name>.rejectSSL requires nginx version
       1.19.4 or above; see the documentation for services.nginx.package.
```

But both Angie and Tengine should support that  option:
https://en.angie.software/angie/docs/configuration/modules/http/http_ssl/?ra=yes#ssl-reject-handshake
https://github.com/alibaba/tengine/blob/master/CHANGES#L430

### Steps To Reproduce
1. Setup an nginx virtualhost with `rejectSSL = true` and set `services.nginx.package` to e.g. `angie` or `tengine`

### Expected behavior
This should not fail assertions as the configuration is supported and the nginx module explicitly states these forks are can be used.

### Additional context
afaict this is _not_ supported by openresty

### Notify maintainers

NGINX
@fpletz
@RaitoBezarius
@dasJ 
@Conni2461 

Angie/Tengine
@Izorkin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.50, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.8`
 - channels(lunik): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Izorkin** [comment]
Fixed - https://github.com/NixOS/nixpkgs/pull/350224
