### ISSUE TITLE
gnome3.gnome-disk-utility unable to find parted

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#34999]
## Issue description
I ran gnome3.gnome-disk-utility via `nix-shell -p gnome3.gnome-disk-utility --run gnome-disks`.
I tried formatting a usb drive (by selecting it on the left, then selected "Format Disk" in the hamburger menu. After pressing the "Format…" button and asking for final confirmation, gnome-disk-utility complains about being unable to find parted. Passing `-p parted` to `nix-shell` doesn't help either.

![screenshot](https://user-images.githubusercontent.com/183879/36248925-671f878a-1239-11e8-8b5c-267d3c52708f.png)

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.18, NixOS, 18.03.git.e860b65 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127302.e860b651d6e"`
 - channels(flokli): `"nixpkgs-unstable-18.03pre123927.5be70c39f3e, nixpkgs-18.03pre123927.5be70c39f3e, nixos-18.03pre123927.5be70c39f3e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jtojnar** [comment]
GNOME Disk Utility is just a frontend to `udisks2`. It could be fixed by patching the library but the version we have packaged is quite old and the new one uses [`libblockdev-part`](http://storaged.org/libblockdev/) instead of `parted`. Updating `pkgs/os-specific/linux/udisks/2-default.nix` should help.

Actually, there are some instances of `parted` calls, the following should fix them:

Running

```ShellSession
git clone git@github.com:storaged-project/udisks.git
cd udisks
for f in $(git grep -l 'parted --script'); do sed -i 's~parted --script~@parted@ --script~g' "$f"; done
for f in $(git grep -l '/sbin/mdadm'); do sed -i 's~/sbin/mdadm~@mdadm@~g' "$f"; done
for f in $(git grep -l '/sbin/blkid'); do sed -i 's~/sbin/blkid~@blkid@~g' "$f"; done
sed -i 's~/bin/sh~@sh@~g' data/80-udisks2.rules
for f in $(git grep -l '/bin/sed'); do sed -i 's~/bin/sed~@sed@~g' "$f"; done
for f in $(git grep -l '/bin/true'); do sed -i 's~/bin/true~@true@~g' "$f"; done
for f in $(git grep -l '/bin/sleep'); do sed -i 's~/bin/sleep~@sleep@~g' "$f"; done
for f in $(git grep -l '/bin/false'); do sed -i 's~/bin/false~@false@~g' "$f"; done
git diff | filterdiff --strip=0 --clean > ~/Projects/nixpkgs/pkgs/os-specific/linux/udisks/fix-paths.patch
```

followed by adding the patch to the `udisks2` expression:

```nix
patches = [
  (substituteAll {
    src = ./fix-paths.patch;
    parted = "${parted}/bin/parted";
    mdadm = "${mdadm}/bin/mdadm";
    blkid = "${utillinux}/bin/blkid";
    sh = "${sh}/bin/sh";
    sed = "${gnused}/bin/sed";
    true = "${coreutils}/bin/true";
    sleep = "${coreutils}/bin/sleep";
    false = "${coreutils}/bin/false";
  })
];
```

**Comment by jtojnar** [comment]
@flokli could you please check if #35551 fixes your problem?

**Comment by flokli** [comment]
I checked, but it seems there's more paths that need to be changed in `src/udiskslinuxfsinfo.c` (currently complains about missing `mkfs.vfat`).

Will add a follow-up commit.
