### ISSUE TITLE
update postgresql from version 15 to 16

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#349915]
sudo -u postgres pg_upgrade -b "$(nix build --no-link --print-out-paths nixpkgs#postgresql_15.out)/bin" -B /run/current-system/sw/bin -d /data/psql -D /data/psql16

Performing Consistency Checks
-----------------------------
Checking cluster versions                                     ok

*failure*
Consult the last few lines of "/data/psql16/pg_upgrade_output.d/20241020T122653.893/log/pg_upgrade_server.log" for
the probable cause of the failure.

connection to server on socket "/home/prehonor/temp/.s.PGSQL.50432" failed: Permission denied
	Is the server running locally and accepting connections on that socket?

could not connect to source postmaster started with the command:
"/nix/store/2v4jx6xr8n4a4djaw0501cw65sykni15-postgresql-15.8/bin/pg_ctl" -w -l "/data/psql16/pg_upgrade_output.d/20241020T122653.893/log/pg_upgrade_server.log" -D "/data/psql" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/home/prehonor/temp'" start
Failure, exiting

sudo cat /data/psql16/pg_upgrade_output.d/20241020T124027.016/log/pg_upgrade_server.log
-----------------------------------------------------------------
  pg_upgrade run on Sun Oct 20 12:40:27 2024
-----------------------------------------------------------------

command: "/nix/store/2v4jx6xr8n4a4djaw0501cw65sykni15-postgresql-15.8/bin/pg_ctl" -w -l "/data/psql16/pg_upgrade_output.d/20241020T124027.016/log/pg_upgrade_server.log" -D "/data/psql" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/tmp'" start >> "/data/psql16/pg_upgrade_output.d/20241020T124027.016/log/pg_upgrade_server.log" 2>&1
waiting for server to start....[78554] FATAL:  could not access file "timescaledb": No such file or directory
[78554] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.

**Comment by dotlambda** [comment]
I'll close this issue because your logs are illegible, you didn't use the issue template, and didn't ping maintainers.
