### ISSUE TITLE
Package request: NixOS module `send`

### ISSUE THREAD

**Issue by 74k1** [NixOS/nixpkgs#350025]
**Project description**

Simple, private file sharing. A maintained fork of https://github.com/mozilla/send

The CLI-tool is already available in nixpkgs: https://search.nixos.org/packages?show=ffsend
I'm requesting a NixOS module / service.

**Metadata**

* homepage URL: https://send.vis.ee/
* source URL: https://gitlab.com/timvisee/send / https://github.com/timvisee/send
* license: MPL-2.0
* platforms: unix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Moraxyc** [comment]
package: https://github.com/NixOS/nixpkgs/pull/350931

I'm trying to write the module, please wait. Once completed, it will be submitted in another PR

**Comment by Moraxyc** [comment]
@74k1  Please test whether the package is functional
