### ISSUE TITLE
new xen option fails to work

### ISSUE THREAD

**Issue by gador** [NixOS/nixpkgs#350051]
### Describe the bug

`virtualisation.xen.enable = true` does not enable xen. 

### Steps To Reproduce
1. add `virtualisation.xen.enable = true;` to the config
2. reboot

### Expected behavior

`xl list` or `xl info` (or any other `xl` command) should work, no errors should show in the boot log

### Additional context

`xl info` returns
```
xencall: error: Could not obtain handle on privileged command interface: No such file or directory
libxl: error: libxl.c:102:libxl_ctx_alloc: cannot open libxc handle: No such file or directory
cannot init xl context
```

Boot log shows:
```
systemd-modules-load[128]: Failed to insert module 'xenfs': No such device
[..]
xen-qemu-dom0-disk-backend.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
[..]
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_gntdev': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_gntalloc': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_blkback': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_netback': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_pciback': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'evtchn'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'gntdev'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'netbk'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'blkbk'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'xen-scsibk'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'usbbk'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'pciback'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_acpi_processor': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to find module 'blktap2'
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_wdt': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_acpi_processor': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_privcmd': No such device
Okt 20 17:38:54 framework kernel: Rounding down aligned max_sectors from 4294967295 to 4294967288
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xen_scsiback': No such device
Okt 20 17:38:54 framework systemd-modules-load[1273]: Failed to insert module 'xenfs': No such device
```
My config includes `lanzaboote`, `zfs` and `impermanence`configs. My kernel is the `pkgs.linuxPackages` one. My `kernelParams` are ` [ "boot.shell_on_fail" "mem_sleep_default=deep" "nvme.noacpi=1" ];`

`/proc/xen` does not exist.

Should I have done something different? Is there a specific kernel I should have used?

### Notify maintainers

@NixOS/xen-project 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241020.c351235`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(wogan): `""`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/b1r7mk0hgd88fdspwwj97rsa8ppqj7ci-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
Hi there! Thank you for your interest in the Xen hypervisor.

The logs seem to indicate you have not booted into a Xen kernel. You've mentioned you're using Lanzaboote; are you also using [this experimental PR](https://github.com/nix-community/lanzaboote/pull/387) that implements Xen support for Lanzaboote? That PR should be considered unstable at this point; for the best experience, try switching to `systemd-boot`.

**Comment by gador** [comment]
@SigmaSquadron thanks for the (very) quick reply!

I didn't know it was different, nor did I know `lanzaboote` had this experimental PR! 
For now I'll stay with `lanzaboote` and watch the PR closely. As soon as it is merged I'll give it another try. Thanks for all your work towards xen-dom0!

**Comment by gador** [comment]
I've got my system running with `xen` with help from @CertainLach (thanks!)

Unfortunately it seems my system (framework 13 inch 11th gen) is quite unstable with `xen`. I had to hard reset 4 times by now (in about 1 hour!) It seems temperature control isn't working and the CPU overheats. I also don't get temperature measurements when booted in `xen`.

**Comment by SigmaSquadron** [comment]
Not much we can do about that, unfortunately. Xen is notoriously picky when it comes to hardware compatibility. You may want to report this to upstream Xen.

**Comment by CertainLach** [comment]
Qubes branch has many compatibility fixes as part of qubes-vmm-xen package, it might make sense to use xen from this package on laptop, even if not using qubes itself.

Your issue, however, sounds like something to be fixed by "cpufreq=xen:hwp=off" kernel cmdline argument (As per workaround from qubes-issues)

**Comment by gador** [comment]
Thanks for the pointer. I went down the [rabbit](https://github.com/QubesOS/qubes-issues/issues/4604) [hole](https://github.com/QubesOS/qubes-issues/issues/8825) with qubes-issues and tried your option (where xen complains about non knowing the option `hwp=off` and it isnt documented in the official [xen docs](https://xenbits.xen.org/docs/4.19-testing/misc/xen-command-line.html#cpufreq)) until I added "cpufreq=none" and my system worked, again. Until I plugged in the power. Then it frooze.
I guess I give xen another try once https://github.com/NixOS/nixpkgs/pull/341429 has been merged.

**Comment by SigmaSquadron** [comment]
welcome to xen on non-server hardware :)

**Comment by gador** [comment]
Yeah I know. Thanks for all you work towards xen and qubes! I used qubes extensively before and really look forward to playing with it in combination with nixos :-)
