### ISSUE TITLE
Enhancement: Add HiDPI support to gohufont

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#35003]
## Issue description
gohufont package is missing the new HiDPI versions with 22px and 28px. This would be usefull, especially if you want to share a screen or show a terminal on a projector.
Those variations have been added by the author of the font:

https://github.com/hchargois/gohufont/tree/master/hidpi

### Steps to reproduce
Use gohufont.

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 18.03pre126063.95880aaf062 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre126063.95880aaf062"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### Device details
 - device: `20J6S0DM00 ThinkPad T470p`
 - cpu: `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`
 - gpu: `Intel Corporation Device 591b (rev 04)`

**Comment by d4g** [comment]
@Epitrochoid

**Comment by Epitrochoid** [comment]
All of my current NixOS installations now are headless so I don't have a great way of updating and testing this. Updating this should be fairly straightforward though as it is an incredibly simple package. The file `pkgs/data/fonts/gohufont/default.nix` just needs to be updated with the variable `url` pointing to the package location and `sha256` as the sha256 hash of the file the url points to.

**Comment by rnhmjoj** [comment]
All the hdpi variants fail to convert with bdf2psfm so it's not that easy. I'm trying to unstard what's the problem: apparently bdf2psf complains the font has zero width.

**Comment by rnhmjoj** [comment]
Also bdftopcf reports the sizes of the 22 and 28 versions as 17 and 0.

**Comment by rnhmjoj** [comment]
I opened an issue at https://github.com/hchargois/gohufont/issues/7

**Comment by 7c6f434c** [comment]
@d4g Does the 2.1 version match your expectations?

**Comment by d4g** [comment]
Still waiting for it to be on unstable for testing.

**Comment by 7c6f434c** [comment]
By the way, it is not too complicated to install a single package from `master`, you would just replace `gohufont` with `((import /path/to/checked/out/nixpkgs {}).gohufont)`

**Comment by rnhmjoj** [comment]
HiDPI versions have been in gohufont for a long time, now.
