### ISSUE TITLE
sh: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by universish** [NixOS/nixpkgs#350071]
```
~$ sudo sh <(curl -L https://nixos.org/nix/install) --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[s  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4267  100  4267    0     0   5879      0 --:--:-- --:--:-- --:--:--  5879

Sorry, try again.
[sudo] password for m*****: 
sh: /dev/fd/63: No such file or directory
```

OS: fedora 40 workstation (gnome).

**Comment by jackwilsdon** [comment]
`sudo` closes file descriptors other than stdin/stdout/stderr. Try it without `sudo` (the install instructions recommend running it without): https://nixos.org/download/

**Comment by universish** [comment]
$ sh <(curl -L https://nixos.org/nix/install) --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4267  100  4267    0     0   5479      0 --:--:-- --:--:-- --:--:-- 16932
downloading Nix 2.24.9 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.24.9/nix-2.24.9-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.vrdy8wJPVC'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  7826k      0  0:00:02  0:00:02 --:--:-- 7823k
Note: a multi-user installation is possible. See https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation
Switching to the Multi-user Installer

---- oh no! --------------------------------------------------------------------
Nix does not work with selinux enabled yet!
see https://github.com/NixOS/nix/issues/2374

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community

**Comment by universish** [comment]
curl -L https://nixos.org/nix/install | sh -s -- --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4267  100  4267    0     0   4916      0 --:--:-- --:--:-- --:--:-- 18797
downloading Nix 2.24.9 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.24.9/nix-2.24.9-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.nHtGyr0gwm'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  7077k      0  0:00:03  0:00:03 --:--:-- 7078k
Note: a multi-user installation is possible. See https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation
Switching to the Multi-user Installer

---- oh no! --------------------------------------------------------------------
Nix does not work with selinux enabled yet!
see https://github.com/NixOS/nix/issues/2374

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community

**Comment by universish** [comment]
there is no solution for fedora. multi-user installation on fedora is not possible due to SElinux. I'm merging and closing the issue since the thread has already been opened.
https://github.com/NixOS/nix/issues/2374

**Comment by universish** [comment]
See also:
https://github.com/NixOS/nix/issues/11689
