### ISSUE TITLE
KDE Plasma Ksplash stuck

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#350182]
### Describe the bug
After updating plasma from 6.2.0 to 6.2.1, it takes over 30-40 seconds to load instead of like 3-5

### Steps To Reproduce
1. Update to latest nixos-unstable
2. Observe painfully long kde splash screen

### Expected behavior
Plasma should start in a couple of seconds

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@K900 (?)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.4, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20240920_ca3fc169`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
Seems like shell starts normally, but 
`Oct 21 10:46:59 dell-pc (-session)[10419]: plasma-ksplash-ready.service: Unable to locate executable '-session': No such file or directory`

**Comment by griffi-gh** [comment]
```# /run/current-system/sw/share/systemd/user/plasma-ksplash-ready.service
[Unit]
Description=KSplash "ready" Stage
Wants=plasma-core.target
After=plasma-core.target
PartOf=graphical-session.target

[Service]
Type=oneshot
ExecStart= --session --reply-timeout=1 --type=method_call --dest=org.kde.KSplash /KSplash org.kde.KSplash.setStage string:ready
Slice=session.slice
```

**Comment by griffi-gh** [comment]
ksplash service is broken

**Comment by griffi-gh** [comment]
Maybe fixed by https://github.com/NixOS/nixpkgs/commit/ed8c856ebfc87f211e60c1699e091c39540e93b1?

**Comment by griffi-gh** [comment]
Hacky workaround: (assuming `dbus-send` is in `/etc/profiles/per-user/user/bin/dbus-send`)
```
 home.file."/home/user/.config/systemd/user/plasma-ksplash-ready.service.d/override.conf" = {
    # fix bug where splash screen doesn't disappear
    text = ''
      [Service]
      ExecStart=/etc/profiles/per-user/user/bin/dbus-send --session --reply-timeout=1 --type=method_call --dest=org.kde.KSplash /KSplash org.kde.KSplash.setStage string:ready
    '';
  };
```

**Comment by K900** [comment]
Should be fixed in the next channel update.
