### ISSUE TITLE
[installer] "The installer adds a LaunchDaemon to mount your Nix volume: org.nixos.darwin-store Can I remove it? [y/n]" seems contradictory

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#350107]
## Issue description
While running the [installation process](https://nixos.org/download/) on macOS 15.0.1 (24A348) with a pre-existing (but broken) Nix install, I'm prompted:
```
...
The installer adds a LaunchDaemon to mount your Nix volume: org.nixos.darwin-store
Can I remove it?
[y/n]
```
which seems contradictory. On the one hand the installer says it will be adding a LaunchDaemon, but then it asks whether it has permission to "remove it".

### Steps to reproduce
Run `sh <(curl -L https://nixos.org/nix/install)` on macOS 15.0.1 (24A348) with a pre-existing nix install.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

not currently possible -- current nix install is broken

**Comment by Atemu** [comment]
This is a nix issue. Could someone with the appropriate permissions transfer this to https://github.com/NixOS/nix?
