### ISSUE TITLE
pkgs.ccid lacks proper files for pcscd usage

### ISSUE THREAD

**Issue by ShadowRZ** [NixOS/nixpkgs#350129]
### Describe the bug

`pkgs.ccid` 1.6.1 is lacking these important files for pcscd usage:

* `etc/reader.conf.d/libccidtwin`
* `pcsc/drivers/serial/libccidtwin.so`

### Steps To Reproduce
1. `nix build 'nixpkgs#ccid'`
2. `tree -f ./result`

### Expected behavior

The files mentiond above is avaliable for usage in pcscd

A proper build of `pkgs.ccid` for reference:

```
@ nix build 'github:NixOS/nixpkgs/e08704965a52919348d9dba3570baf9c57befdf9#ccid'
@ tree -f ./result
./result
├── ./result/etc
│   └── ./result/etc/reader.conf.d
│       └── ./result/etc/reader.conf.d/libccidtwin
├── ./result/lib
│   └── ./result/lib/udev
│       └── ./result/lib/udev/rules.d
│           └── ./result/lib/udev/rules.d/92_pcscd_ccid.rules
└── ./result/pcsc
    └── ./result/pcsc/drivers
        ├── ./result/pcsc/drivers/ifd-ccid.bundle
        │   └── ./result/pcsc/drivers/ifd-ccid.bundle/Contents
        │       ├── ./result/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
        │       └── ./result/pcsc/drivers/ifd-ccid.bundle/Contents/Linux
        │           └── ./result/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
        └── ./result/pcsc/drivers/serial
            └── ./result/pcsc/drivers/serial/libccidtwin.so

12 directories, 5 files
```

### Additional context

I believe this is the base bug of #349249

People usually configures `scdaemon` in GnuPG with `disable-ccid`, per the manpage, it's required so GnuPG would use PC/SC driver (and thus pcscd) for smartcard communication. However with the files mentiond above missing, pcscd wouldn't be able to detect any smartcards thus identified no smartcards

### Notify maintainers

Cc @FliegendeWurst @anthonyroussel

### Metadata

```console
@ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.3-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #350153
