### ISSUE TITLE
mesa:  radeon icd and libvulkan_radeon not in the drivers derivation

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#35010]
## Issue description

If I install `mesa_noglu` I would expect the radeon vulkan drivers to be included by default. The source code also seems to say this:

https://github.com/NixOS/nixpkgs/blob/dd57c6379333b3e841b947786b14d5cd586f8c4a/pkgs/development/libraries/mesa/default.nix#L47

but when I look in the derivation output,  only `libvulkan_intel` and  `share/vulkan/icd.d/intel_icd.x86_64.json` are created.   Mesa usually also builds `libvulkan_radeon` and `share/vulkan/icd.d/radeon_icd.json`

### Steps to reproduce
1. Go on a machine with a ryzen CPU and a Radeon GPU ( Though probably not neccessery, the vulkan radeon driver should always be built according to the nix derivation)

2. This will fail:
```
nix-shell -p mesa_noglu vulkan-loader --run "vulkaninfo"
```

**Comment by arianvp** [comment]
The `PKGBUILD` for arch linux is very similar to the Nix derivaiton... and that does expose `libvulkan_radeon`:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mesa

Is `enableRadv`  set to `false` somewhere implicitly in `nixpkgs`?

**Comment by msteen** [comment]
> Is `enableRadv` set to `false` somewhere implicitly in `nixpkgs`?

That would depend on at what commit your nixpkgs repo currently is.
- [At `master` it currently is set to `true` by default](https://github.com/NixOS/nixpkgs/blob/64a4a69929815d13c44de40dcdda006caf1e1464/pkgs/development/libraries/mesa/default.nix#L7).
- [At `release-17.09` it currently is set to `false` by default](https://github.com/NixOS/nixpkgs/blob/b2e7bb5ee80303ec6d0671085f5da424014a601f/pkgs/development/libraries/mesa/default.nix#L7).

**Comment by arianvp** [comment]
Oh good catch! let me try master

**Comment by arianvp** [comment]
```
nix-shell -p mesa_noglu vulkan-loader --run "vulkaninfo"

```

Works on master!

**Comment by vcunat** [comment]
I expect this isn't suitable for backporting to 17.09.
