### ISSUE TITLE
gpclient refers to /usr/bin/gpservice

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#350111]
### Describe the bug
Error trying to launch GUI.

### Steps To Reproduce
1. `gpclient launch-gui`
2. Observe failure

### Expected behavior
Should open GUI

### Screenshots

```
# gpclient launch-gui
[2024-10-20T23:01:11Z INFO  gpclient::cli] gpclient started: 2.3.7 (2024-10-12)
[2024-10-20T23:01:11Z INFO  gpclient::launch_gui] Log file: /home/brian/.local/share/gpclient/gpclient.log
[2024-10-20T23:01:11Z INFO  gpclient::launch_gui] Service exited with status: exit status: 127

# cat /home/brian/.local/share/gpclient/gpclient.log
Error accessing /usr/bin/gpservice: No such file or directory
``

### Additional context
Add any other context about the problem here.

### Notify maintainers

<!--
Please @ people who are in the `meta.maintainers` list of the offending package or module.
If in doubt, check `git blame` for whoever last touched something.
-->

@Binary-Eater 


### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by brianmay** [comment]
I can't find any package in nixos unstable that provides `gpservice`. It use to be provided by `globalprotect-openconnect`.

**Comment by brianmay** [comment]
I am somewhat unclear why the `services.globalprotect` option was removed in nixos unstable.

**Comment by brianmay** [comment]
Never mind, I finally found in the release notes:

```
Legacy package globalprotect-openconnect 1.x and related module globalprotect-vpn were dropped. Two new packages gpauth and gpclient from the 2.x version of the GlobalProtect-openconnect project are added in its place. The GUI components related to the project are non-free and not packaged.
```

I guess that might be why `services.globalprotect` was dropped. Is there any information here what happened? Did they recently change there license or something?

I found the magical incarnation of the gpclient command line that appears to work.

**Comment by saipavanc** [comment]
Has there been any development on this issue? If not this package, is there an alternative to connect to vpn, maybe an alternate package?

**Comment by brianmay** [comment]
The release notes are lacking IMHO. They say what has changed and why, but not what nixos users must change.

Anyway delete this:

```
services.globalprotect = {enable = true;};
```

Add this:

```
environment.systemPackages = with pkgs; [
    gpauth
    gpclient
  ];
```

I am still not clear if I need both, but I think I do.

Then start the VPN with a command like:

```
sudo  gpclient --fix-openssl  connect  <endpoint>
```

At least this is sufficient for my needs :-)

I notice that there still is a [services.globalprotect](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/nixos/modules/services/networking/globalprotect-vpn.nix) settings, but I think this relies on the gpservice binary that doesn't exist anymore(???), so maybe the nixos module should get dropped entirely?

**Comment by saipavanc** [comment]
Thank you very much for the clarification. I was wondering what I could do, but did not find anything at all to help. This finally was progress. Still not complete yet, I tried the following:
```
sudo  gpclient --fix-openssl connect <portal> --browser brave
[2024-11-30T08:30:27Z INFO  gpclient::cli] gpclient started: 2.3.9 (2024-11-20)
[2024-11-30T08:30:27Z INFO  gpapi::portal::prelogin] Portal prelogin with user_agent: PAN GlobalProtect
[2024-11-30T08:30:27Z INFO  gpapi::portal::prelogin] Perform prelogin, user_agent: PAN GlobalProtect
[2024-11-30T08:30:28Z INFO  gpauth::cli] gpauth started: 2.3.9 (2024-11-20)
[2024-11-30T08:30:28Z INFO  gpauth::cli] Fixing OpenSSL environment
[2024-11-30T08:30:28Z INFO  gpapi::process::browser_authenticator] Launching browser: brave
[2024-11-30T08:30:28Z INFO  gpauth::cli] Please continue the authentication process in the default browser
[2024-11-30T08:30:28Z INFO  gpauth::cli] Listening authentication data on port 45389
[2024-11-30T08:30:28Z INFO  gpauth::cli] If it hangs, please check the logs at `/tmp/gpcallback.log` for more information

```
I am able to finish the SAML authentication, but the terminal is stuck on this command. Is there anything I can do to fix this? I looked at the log, and it has nothing by the port number in one line.

**Comment by Binary-Eater** [comment]
Related PRs

- https://github.com/NixOS/nixpkgs/pull/316526
- https://github.com/NixOS/nixpkgs/pull/355758

**Comment by brianmay** [comment]
For the new v2 packages - which it looks like you are using - my understanding is that you have to use CLI tools only, the GUI cannot be packaged.

The old v1 packages were replaced and can still be used as before. Not tested...

**Comment by Yeshey** [comment]
> For the new v2 packages - which it looks like you are using - my understanding is that you have to use CLI tools only, the GUI cannot be packaged.
> 
> The old v1 packages were replaced and can still be used as before. Not tested...

I see, thanks! It looks like the problem is that the GUI has some elements that are not open source? 
The old version packaged under `globalprotect-openconnect` is hitting a `marked as insecure` error in nixOS 25.11: https://discourse.nixos.org/t/unable-to-install-package-due-to-insecure-dependency-refusing-to-evaluate/70363 
But the CLI does work reliably.

**Comment by brianmay** [comment]
>I see, thanks! It looks like the problem is that the GUI has some elements that are not open source?

Yes, I believe this is correct. Unfortunately. Information on what happened in rather vague though.

Apparently you have to pay now to access the GUI parts: https://github.com/yuezk/GlobalProtect-openconnect/issues/559
