### ISSUE TITLE
Unable to rebuild flake - system76-power fails to install sysfs-class

### ISSUE THREAD

**Issue by NickyTope** [NixOS/nixpkgs#350115]
### Describe the bug
I'm on nixpkgs/nixos-unstable with a system76 Oryx

I have set `hardware.system76.enableAll = true` in my configuration which has been working great!

After performing a `nix flake update` however I can no longer rebuild and get the following error:

```error: builder for '/nix/store/6ang6g3hkygpymgz6kggl3bvamxvyh17-system76-power-1.1.23.drv' failed with exit code 101;
       last 10 log lines:
       > error: failed to get `sysfs-class` as a dependency of package `system76-power v1.1.23 (/build/source)`
       >
       > Caused by:
       >   failed to load source for dependency `sysfs-class`
       >
       > Caused by:
       >   Unable to update https://github.com/pop-os/sysfs-class#ab63e7f6
       >
       > Caused by:
       >   can't checkout from 'https://github.com/pop-os/sysfs-class': you are in the offline mode (--offline)
       For full logs, run 'nix log /nix/store/6ang6g3hkygpymgz6kggl3bvamxvyh17-system76-power-1.1.23.drv'.
```

I am not running the rebuild in offline mode though..
My rebuild command is just: `sudo nixos-rebuild switch --flake ~/code/nixos-config`

I have set `hardware.system76.power-daemon.enable = false;` to test and can rebuild just fine (but I obviously lose the features of the power daemon).

If there's a better place for me to log this, let me know!

### Steps To Reproduce
1.  set hardware.system76.enableAll = true (using unstable channel)
2. nix flake update
3. rebuild

### Expected behavior
Successful rebuild switch

### Additional context
flake here: https://github.com/NickyTope/nixos-config

### Notify maintainers
@Mic92 
@jwoudenberg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.48, NixOS, 24.11 (Vicuna), 24.11.20240831.12228ff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/bd4fmzws6n5542khxbifbkr6nrygi232-source`
```

**Comment by NickyTope** [comment]
Have been trying to find any other reference to this one found that @ahoneybun referenced the same thing here: https://github.com/NixOS/nixpkgs/pull/342921#issuecomment-2419897067 although that PR is unrelated.. and @sjmonson stated that an update is on the way.

Any help or pointing in the right direction would be amazing !!

**Comment by ahoneybun** [comment]
The update to system76-power was just merged and should fix this.

**Comment by sjmonson** [comment]
The `system76-power` update was merged yesterday but has not made it to the nixpkgs-unstable branch. Ref: #349351

**Comment by NickyTope** [comment]
Many thanks for all the hard work! problem resolved
