### ISSUE TITLE
Unzip support in the generic builder

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#3502]
Generic builder [has support for `.zip`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L458), but `unzip` is not in path by default.

~~~
/nix/store/kf8rnvkprmcxyh5s7ssg0iw51z5cyvn9-stdenv/setup: line 466: unzip: command not found
~~~

I feel that having to add `unzip` to `buildInputs` by hands in this case isn’t quite right.

**Comment by domenkozar** [comment]
this was in master for a long time
