### ISSUE TITLE
Haskell packages are installing "LICENSE" in /share/doc

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#35024]
## Issue description

This is causing me some issues with collisions. Basically Haskell stuff like that found in "haskellPackages" are installing a "LICENSE" file. Because all haskell packages have it they end up causing collisions in the profile.

This is happening on MacOS right now, at least.

/cc @peti

**Comment by mpickering** [comment]
How do you reproduce this?

**Comment by matthewbauer** [comment]
This is the shortest example of what happens:

```
$ nix-build -E 'with import <nixpkgs> {}; buildEnv { name = "test"; paths = (with haskellPackages; [ hlint cabal-install hoogle ]); extraOutputsToInstall = [ "doc" ]; }'
these derivations will be built:
  /nix/store/lcr1icgb19b9n7clfidcdl1j05idrmnc-test.drv
building '/nix/store/lcr1icgb19b9n7clfidcdl1j05idrmnc-test.drv'...
collision between `/nix/store/2631yg65iv7868v9773vsly4m3dv0yzc-cabal-install-2.0.0.1-doc/share/doc/LICENSE' and `/nix/store/n9jq7gsa1vy77b4jpdydk547m7h1gwc4-hlint-2.1-doc/share/doc/LICENSE'
builder for '/nix/store/lcr1icgb19b9n7clfidcdl1j05idrmnc-test.drv' failed with exit code 25
error: build of '/nix/store/lcr1icgb19b9n7clfidcdl1j05idrmnc-test.drv' failed
```

**Comment by matthewbauer** [comment]
@peti Any ideas how this is coming up? It's kind of annoying & we can just add a rm $out/share/doc/LICENSE postInstall unless there is a better solution.

**Comment by peti** [comment]
The problem we have moving that file into a less generic location is that we don't know its name. These files are by no means always called "LICENSE"; it might as well be "COPYING" or whatever.

I'll check whether it's easy to make Cabal put those files into a better location from the outset.

**Comment by peti** [comment]
Test-building https://github.com/peti/nixpkgs/commit/9e08d2f98f4dc5be3686b92e46f0b80aaa17d729 ...
