### ISSUE TITLE
rquickshare: "Cannot create EGL context: invalid display"

### ISSUE THREAD

**Issue by jdev082** [NixOS/nixpkgs#350315]
### Describe the bug
Upon attempting to launch rquickshare, the window only shows briefly. It fails to load, and crashes.

```
$ rquickshare

Gtk-Message: 14:03:49.670: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:03:49.670: Failed to load module "window-decorations-gtk-module"
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

### Steps To Reproduce
1. Install rquickshare through your method of choice
2. Attempt to run rquickshare from the terminal

### Expected behavior
Application opens and displays properly

### Additional context
Bug was previously reported by another user on the project's issues page: https://github.com/Martichou/rquickshare/issues/220

### Notify maintainers
@luftmensch-luftmensch 

# Environment
Testing was done using the COSMIC desktop environment alpha. The program was running in Xwayland.
NVIDIA Driver:  560.35.03

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jdev082** [comment]
Has been reproduced on other symptoms. Therefore, this is an issue with the program itself.

**Comment by yajo** [comment]
It's working if we download the legacy flavor of the app, and it's set as the official fix upstream, so there's actually something to do here: https://github.com/NixOS/nixpkgs/pull/367605
