### ISSUE TITLE
Build failure: ripgrep-all

### ISSUE THREAD

**Issue by Samasaur1** [NixOS/nixpkgs#350367]
### Steps To Reproduce

1. build ripgrep-all

### Build log

<https://gist.github.com/Samasaur1/3a9b67fdcca24e4ccede859cdd480153>

### Notify maintainers

@zaninime @Ma27 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NotAShelf** [comment]
Looks like this is a Darwin exclusive issue - ripgrep-all builds fine on x86_64 and aarch64 Linux.

**Comment by taranlu-houzz** [comment]
Same issue here, also on macOS.

**Comment by Ma27** [comment]
Does anybody have an idea how the `rga-fzf-open.dSYM` ends up in there? And is this even needed or just an artifact that ends up there for no real reason?

If the latter is actually the case, we could also just `rm` it before creating the wrappers.
