### ISSUE TITLE
builtins.isFunction returns false on primop and primop-app

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#35037]
builtins.isFunction is returning false for primop and primop-app type values.

`builtins.isFunction builtins.isFunction => false`
`builtins.isFunction (builtins.replaceStrings []) => false`

I don't see any value in builtins.isFunction only returning true for non-primop lambdas. Most people would probably expect it to check if something was any kind of lambda.

Here's the cause of the issue:
https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L270-L275
https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L247-L251

Workaround: `isLambda = x: builtins.typeOf x == "lambda";`

**Comment by lheckemann** [comment]
I think this should be in nix, not nixpkgs?

**Comment by ledettwy** [comment]
@lheckemann  oops... duh, thanks
