### ISSUE TITLE
ocaml fails to build on hydra aarch64-darwin

### ISSUE THREAD

**Issue by paparodeo** [NixOS/nixpkgs#350394]
### Describe the bug

ocaml build is failing on hydra but curiously succeeds when building locally... previous versions (ocaml_5_1) are not cached so assume fail to build on hydra but not sure how to access hydra page.

https://hydra.nixos.org/job/nixpkgs/trunk/ocaml.aarch64-darwin
https://hydra.nixos.org/build/275103717

```
[...]
File "_none_", line 1:
Error: I/O error: dllunixbyt.so_The boot compiler cannot load DLLs: No such file or directory
make[3]: *** [Makefile:558: debugger/ocamldebug] Error 2
make[3]: *** Waiting for unfinished jobs....
File "_none_", line 1:
Error: I/O error: dllunixbyt.so_The boot compiler cannot load DLLs: No such file or directory
make[3]: *** [Makefile:544: ocamldoc/ocamldoc] Error 2
```

### Notify maintainers

@NixOS/ocaml
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

```
ProductName:            macOS
ProductVersion:         15.0.1
BuildVersion:           24A348
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by boborbt** [comment]
I have the same problem on my macos machine... any hint about how to fix it?

Here is the output of: `nix-shell -p nix-info --run "nix-info -m"`

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by ulrikstrid** [comment]
I think this is a flakyness issue, cc @anmonteiro

**Comment by anmonteiro** [comment]
The build command causes this. In our overlays we don’t have the flakiness issue and we build OCaml with `make defaultentry`. There’s no need to run `make bootstrap`

**Comment by sbhal** [comment]
Having same issue
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/r2hk87rfvc5fpfbl2bj64a3x7mcq9f6c-source`
```

```
building the system configuration...
error: builder for '/nix/store/0r78nqfmxpd7xm0c6wj07iva6v0xsfb3-nix.conf.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/jx269gjzw9s9lx07bxz9ixb1agqm8i2c-etc.drv' failed to build
error (ignored): error: cannot unlink '/private/tmp/nix-build-ocaml-5.2.0.drv-2/ocaml-5.2.0': Directory not empty
error: 1 dependencies of derivation '/nix/store/rxc0gczyq01265rh9nmvhiays9lzjq6l-darwin-system-24.11.20241029.807e915+darwin4.e56d80b.drv' failed to build
```

**Comment by rtetley** [comment]
I think I'm having the same issue in my CI (https://github.com/coq/vscoq/actions/runs/11609185822/job/32325939115)

**Comment by paparodeo** [comment]
> The build command causes this. In our overlays we don’t have the flakiness issue and we build OCaml with `make defaultentry`. There’s no need to run `make bootstrap`

changing to `defaultentry` is easy enough:

```diff
diff --git a/pkgs/development/compilers/ocaml/Makefile.nixpkgs b/pkgs/development/compilers/ocaml/Makefile.nixpkgs
index 2d6457852fc9..52bf27d28a88 100644
--- a/pkgs/development/compilers/ocaml/Makefile.nixpkgs
+++ b/pkgs/development/compilers/ocaml/Makefile.nixpkgs
@@ -12,5 +12,5 @@ nixpkgs_world:
 
 nixpkgs_world_bootstrap_world_opt:
 	$(MAKE) world
-	$(MAKE) bootstrap
+	$(MAKE) defaultentry
 	$(MAKE) world.opt
```

I can setup a PR tho I have no idea what the difference in targets mean

**Comment by anmonteiro** [comment]
> > The build command causes this. In our overlays we don’t have the flakiness issue and we build OCaml with `make defaultentry`. There’s no need to run `make bootstrap`
> 
> changing to `defaultentry` is easy enough:
> 
> I can setup a PR tho I have no idea what the difference in targets mean


it'd rather be

```diff
diff --git a/pkgs/development/compilers/ocaml/Makefile.nixpkgs b/pkgs/development/compilers/ocaml/Makefile.nixpkgs
index 2d6457852fc9..52bf27d28a88 100644
--- a/pkgs/development/compilers/ocaml/Makefile.nixpkgs
+++ b/pkgs/development/compilers/ocaml/Makefile.nixpkgs
@@ -12,5 +12,5 @@ nixpkgs_world:  
 nixpkgs_world_bootstrap_world_opt:
-	$(MAKE) world
-	$(MAKE) bootstrap
- 	$(MAKE) world.opt
+	$(MAKE) defaultentry
```
