### ISSUE TITLE
Package request: legacylauncher / TL legacy

### ISSUE THREAD

**Issue by Sk7Str1pe** [NixOS/nixpkgs#350327]
**Project description**

minimal minecraft launcher
**Metadata**

* homepage URL: https://llaun.ch/ru
* source URL: https://llaun.ch/source
* license: ??? mit ???
* platforms: unix, linux, darwin, ...

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
This could easily get us into legal trouble with Mojang, so I'm opposed to such a thing.

**Comment by Sk7Str1pe** [comment]
why prismlauncher packaged then

**Comment by Frontear** [comment]
Prism isnt a cracked launcher. That would be the main difference

**Comment by FliegendeWurst** [comment]
Duplicate of #336763
