### ISSUE TITLE
minetest: Minetest has begun the process of changing to Luanti

### ISSUE THREAD

**Issue by Faeranne** [NixOS/nixpkgs#350344]
A few days ago the Minetest devs announced they are changing the name of the project to Luanti.  https://blog.minetest.net/2024/10/13/Introducing-Our-New-Name/  
No breaking changes are being made (thankfully) so this is more to point out that nixpkgs should probably start looking at the steps to deprecate the `minetest` package names and start pointing them to `luanti` or the like, as well as updating git references to point to the new org location and what not.

## maintainers
@PyroLagus 
@fpletz
@fgaz

**Comment by fgaz** [comment]
[5.10 is out](https://github.com/minetest/minetest/releases/tag/5.10.0), but we are in feature freeze, so we'll have to wait for the 24.11 branch-off
