### ISSUE TITLE
Package request: Ente ( or ente-photos or photos-desktop )

### ISSUE THREAD

**Issue by universish** [NixOS/nixpkgs#350362]
**Ente**
ente-photos
photos-desktop

**Project description**

A free, open source software that allows you to store photos encrypted in the cloud. It works on all desktop, mobile and web platforms.

**Metadata**

* homepage URL: https://ente.io/
* github homepage URL: https://github.com/ente-io
* source URLs: https://github.com/ente-io/ente ; https://github.com/ente-io/photos-desktop 
* download URLs: https://github.com/ente-io/ente/releases ; stable and for desktop: https://github.com/ente-io/photos-desktop/releases/tag/v1.7.5 ; photos-desktop: https://github.com/ente-io/photos-desktop/releases ; stable and for all platforms: https://ente.io/download ; apk: https://f-droid.org/tr/packages/io.ente.photos.fdroid/ ; apk: https://github.com/ente-io/ente/releases/tag/photos-v0.9.49 ; photos-app apk: https://github.com/ente-io/photos-app/releases
* license: AGPL-3.0
* platforms: gnu-linux libre, gnu-linux, darwin (apple's), net (ms's), android, web
* OSs: gnu-linux libre distros, gnu-linux distros, windows, macOS, iOS, android, web browsers
* distribution formats of software: deb, rpm, pacman, appimage, apk, dmg, exe
* under development flathub source URL: https://github.com/ente-io/flathub
* under development distribution formats of software: flatpak
* web platform's source URL: https://github.com/ente-io/photos-web
* web platform URL: https://web.ente.io/
* app mobil platform source URL: https://github.com/ente-io/photos-app

**Comment by universish** [comment]
https://github.com/NixOS/nixpkgs/pull/346534

**Comment by surfaceflinger** [comment]
https://github.com/NixOS/nixpkgs/issues/292641
