### ISSUE TITLE
Update request: slint-lsp 1.5.1 → 1.8.0

### ISSUE THREAD

**Issue by PaulDance** [NixOS/nixpkgs#350459]
- Package name: `slint-lsp`
- Latest released version: 1.8.0

- Current version on the unstable channel: 1.5.1
- Current version on the stable/release channel: 1.5.1

- [x] Checked the [nixpkgs pull requests for `slint-lsp`](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+slint-lsp+is%3Aopen)

The build maintenance seems to have fallen out of date with the upstream version. Indeed, from the [latest build logs](https://nixpkgs-update-logs.nix-community.org/slint-lsp/2024-10-14.log), it seems the package is attempted to be built with testing code while dev-dependencies are not included somehow. It might be related to a change in features or other compilation options.

It seems [their build process](https://github.com/slint-ui/slint/blob/master/.github/workflows/slint_tool_binary.yaml) is not as simple as `cargo build`, so should be worth comparing to the current Nix side. Also, as the upstream project provides [official builds](https://github.com/slint-ui/slint/releases) for all supported platforms, it might be easier to simply download and extract the adequate `slint-lsp-*` archive rather than recompiling the whole program.

**Notify maintainers**

@xgroleau

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xgroleau** [comment]
Not sure why @r-ryantm didn't updated it automatically, but see #351029

**Comment by PaulDance** [comment]
Thanks for the quick response!

> Not sure why @r-ryantm didn't updated it automatically

The build it automatically attempted at each update [previously failed](https://nixpkgs-update-logs.nix-community.org/slint-lsp/2024-10-14.log).

> but see #351029

The `doCheck = false;` you added there is probably what should fix it, if I understand things correctly.

**Comment by PaulDance** [comment]
Since you didn't mention the current issue in the PR's description, it wasn't closed automatically: I guess it can now be closed?

**Comment by xgroleau** [comment]
Closed as #351029

**Comment by PaulDance** [comment]
Cool, thanks a bunch!
