### ISSUE TITLE
Gitab registry: always using port 5000, ignoring the service config port

### ISSUE THREAD

**Issue by MatthieuBarthel** [NixOS/nixpkgs#350428]
### Describe the bug
By default the gitlab registry port is set to 4567 in [services.gitlab.registry.port](https://search.nixos.org/options?channel=24.05&show=services.gitlab.registry.port&from=0&size=50&sort=relevance&type=packages&query=services.gitlab.registry), but in my tests the registry always uses port 5000, whatever is configured.

### Steps To Reproduce

Enable the registry with any port, except 5000: 
```nix
{
  services.gitlab = {
    enable = true;
    registry = {
      enable = true;
      port = 4567;
      certFile = config.sops.secrets.gitlab_registry_cert.path;
      keyFile = config.sops.secrets.gitlab_registry_key.path;
      externalAddress = "registry.example.com";
      externalPort = 443;
    };
  };
}
```

Verify:
```sh
$ curl -I http://localhost:4567
curl: (7) Failed to connect to localhost port 4567 after 0 ms: Couldn't connect to server

$ curl -I http://localhost:5000
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Tue, 22 Oct 2024 08:28:28 GMT
```

### Expected behavior
Should use the port configured :)

### Notify maintainers

@globin @krav @talyz @yayayayaka

Thanks again <3

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.05 (Uakari), 24.05.20241017.4eb33fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/z7j461v8da67nwrad4xz50dx2l5wk0wz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by purefan** [comment]
have you opened the port in `networking.firewall.allowedTCPPorts` ?

**Comment by MatthieuBarthel** [comment]
No because I use nginx as a proxy, but in the "steps to reproduce" I run the queries directly from the host:

```sh
$ curl -I http://localhost:4567
curl: (7) Failed to connect to localhost port 4567 after 0 ms: Couldn't connect to server

$ curl -I http://localhost:5000
HTTP/1.1 200 OK
```
