### ISSUE TITLE
Note for upgrading slic3r-prusa3d

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#35059]
For future reference if someone should decide to upgrade slic3r-prusa3d: when upgrading to a version after 1.39.0 (which are currently in beta or alpha), there needs to be a patch applied to use the glib version of a header file instead of the kernel version (which isn't available at that path with nix), i.e. something like

```
prePatch = ''
  sed -i 's|"/usr/include/asm-generic/ioctls.h"|<asm-generic/ioctls.h>|g' xs/src/libslic3r/GCodeSender.cpp
'';
```

I guess upstream had issues with the glib version, but the glib version of ioctls.h on my 17.09 nixos is identical to the one provided by the kernel package, so that the patch above shouldn't change anything.

An updated version of the derivation is in my repo at https://github.com/Moredread/nixos-config/blob/910afd203abd27ba269d96d6c8d0fcebdcef4470/home/pkgs/slic3r-prusa3d.nix

@thorstenweber83 as a maintainer that should be interesting for you :)

**Comment by thorstenweber83** [comment]
thanks for the heads-up!
highly appreciated  :thumbsup:

**Comment by jfrankenau** [comment]
ef83f9ed3950c57d8ef99387a960112814e85852 has been merged so this issue can be closed.
