### ISSUE TITLE
Ruff missing python library

### ISSUE THREAD

**Issue by baloo** [NixOS/nixpkgs#350608]
### Describe the bug

The ruff packaging is missing the python library part (https://github.com/astral-sh/ruff/tree/main/python).

This is a dependency of packages like https://github.com/businho/pytest-ruff 

### Steps To Reproduce
1. nix-build . -A ruff

### Expected behavior

Have `ruff/__main__.py` in one of the outputs

### Notify maintainers

@GaetanLepage @figsoda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by baloo** [comment]
Arguably, the ruff/__main__.py will need to be patched to point to the ruff binary we just built.

I'd be happy to make the work here, I think the easiest way to go is to move ruff to `pkgs/development/python-modules/` and make it a `maturin` lib.
This cause breakage because that move ruff from to the top-level to `python3Packages.ruff` and stuff, but nothing that can't be fixed with an alias?

Anyway, I'm opening a bug to gather thoughts :)

**Comment by baloo** [comment]
I threw a quick PR together with what I have in mind:
https://github.com/NixOS/nixpkgs/issues/350608

**Comment by kalekseev** [comment]
I would leave ruff as it is - top level package and build separate ruff python pacakge that uses the top-level ruff package. Is there any problem with that approach?

**Comment by baloo** [comment]
Then it exists in the top-level `ruff` and `python312Packages.ruff`, `python311Packages.ruff` etc.
I think this can cause confusion, but more importantly, I don't know how to refer to the top-level one from the python namespace.
So I can't just reuse top-level's src like `inherit (ruff) src`.
```
# pkgs/development/python-modules/ruff/default.nix
{
   buildPythonPackage,
   ruff,
}:

buildPythonPackage rec {
  pname = "ruff";
  
  inherit (ruff) src;
}
```
Here that would cause infinite recursion.

We could name the python package something else, but what would be that name then?

**Comment by GaetanLepage** [comment]
> I would leave ruff as it is - top level package and build separate ruff python pacakge that uses the top-level ruff package. Is there any problem with that approach?

I agree, moving ruff does not look like a good solution.
Especially, it is built using the `buildRustPackage` builder and not `buildPython{Package,Application}`.

**Comment by baloo** [comment]
> Especially, it is built using the `buildRustPackage` builder and not `buildPython{Package,Application}`.

Yeah, that is essentially what maturin does. Rust gets build by the `buildPythonPackage`. Try my PR to see for yourself.

**Comment by kalekseev** [comment]
> Here that would cause infinite recursion.
> 
> We could name the python package something else, but what would be that name then? We could also just bring in `pkgs` and use `pkgs.ruff` to access the top-level, I guess.


How about `toPythonModule`? https://github.com/NixOS/nixpkgs/blob/035417ccc7b7b80d4bdc889d5a899a37458f65ba/doc/languages-frameworks/python.section.md?plain=1#L342-L359

**Comment by baloo** [comment]
I don't know how that helps. the base package side-steps maturin entirely. The base module will not build the python files or build `pyc` until we move to maturin.
 
 We could use `toPythonModule`, but we'll still need to move from buildRust to buildPython + maturin (and not move from `pkgs/by-name` to `pkgs/development/python-modules` and not need the alias).

**Comment by kalekseev** [comment]
If user install ruff using your deriviation will nix pull enitre python env or only ruff binary?

**Comment by baloo** [comment]
It will pull python, no other library. But you're using ruff, you should already have python?

**Comment by kalekseev** [comment]
> It will pull python, no other library. But you're using ruff, you should already have python?

That's enough for me to be against that change. Consider example I run ruff in CI to lint python code, I don't need python or anything else just ruff binary and I want to build nix env as fast as possible. Pulling python env in this example is just a waste of resourcers.

**Comment by baloo** [comment]
then we can split that in a postInstall and make multiple outputs.

**Comment by GaetanLepage** [comment]
> That's enough for me to be against that change. Consider example I run ruff in CI to lint python code, I don't need python or anything else just ruff binary and I want to build nix env as fast as possible. Pulling python env in this example is just a waste of resourcers.

I agree and feel quite uncomfortable with unnecessarily entangle the `ruff` package with the python package set.
Maybe a new derivation could be written that re-uses the `src` from `pkgs.ruff`.

**Comment by baloo** [comment]
Are there any other concern? This one is easy to fix.

**Comment by baloo** [comment]
with a split of the binary:
```
/nix/store/4c5xs9gbsp8qz23a1zwbfyd05s4byyns-python3.12-ruff-0.7.0-bin
├───/nix/store/sl141d1g77wvhr050ah87lcyz2czdxa3-glibc-2.40-36
│   ├───/nix/store/4hcdxyjf9yiq7qf3i4548drb6sjmwa1v-xgcc-13.3.0-libgcc
│   ├───/nix/store/jwsdpq2yxw43ixalh93z726czz7bay2j-libidn2-2.3.7
│   │   ├───/nix/store/w19cxz37j5nrkg8w80y91bga89310jgi-libunistring-1.2
│   │   │   └───/nix/store/w19cxz37j5nrkg8w80y91bga89310jgi-libunistring-1.2 [...]
│   │   └───/nix/store/jwsdpq2yxw43ixalh93z726czz7bay2j-libidn2-2.3.7 [...]
│   └───/nix/store/sl141d1g77wvhr050ah87lcyz2czdxa3-glibc-2.40-36 [...]
├───/nix/store/y3kdn61k93rq2jx1lj2x72lnsk0l92qh-gcc-13.3.0-lib
│   ├───/nix/store/lw294qfdnf29lhxqwzy9byrmx975rvn9-gcc-13.3.0-libgcc
│   ├───/nix/store/sl141d1g77wvhr050ah87lcyz2czdxa3-glibc-2.40-36 [...]
│   └───/nix/store/y3kdn61k93rq2jx1lj2x72lnsk0l92qh-gcc-13.3.0-lib [...]
└───/nix/store/sw3qrkzm853niy313h5zx7dp19kpn4nh-jemalloc-5.3.0
    ├───/nix/store/sl141d1g77wvhr050ah87lcyz2czdxa3-glibc-2.40-36 [...]
    ├───/nix/store/717iy55ncqs0wmhdkwc5fg2vci5wbmq8-bash-5.2p32
    │   ├───/nix/store/sl141d1g77wvhr050ah87lcyz2czdxa3-glibc-2.40-36 [...]
    │   └───/nix/store/717iy55ncqs0wmhdkwc5fg2vci5wbmq8-bash-5.2p32 [...]
    ├───/nix/store/y3kdn61k93rq2jx1lj2x72lnsk0l92qh-gcc-13.3.0-lib [...]
    └───/nix/store/sw3qrkzm853niy313h5zx7dp19kpn4nh-jemalloc-5.3.0 [...]
    ```

**Comment by baloo** [comment]
Let me know if https://github.com/NixOS/nixpkgs/pull/350654 is a better option for you.

**Comment by GaetanLepage** [comment]
This looks good to me.
Maybe, hearing about @SuperSandro2000 's opinion could be valuable before merging this significant change.

**Comment by SuperSandro2000** [comment]
I looked at the PR but I didn't have time to read the entire thread.

**Comment by GaetanLepage** [comment]
> I looked at the PR but I didn't have time to read the entire thread.

Thank you very much. My intention was to ping you on the PR actually.
