### ISSUE TITLE
Build failure: linuxKernel.packages.linux_hardened.kernel

### ISSUE THREAD

**Issue by Conni2461** [NixOS/nixpkgs#350681]
### Steps To Reproduce

1. `NIX_PATH= nix-build . -A linuxKernel.packages.linux_hardened.kernel`
2. patch doesn't apply
### Build log

```
these 2 derivations will be built:
  /nix/store/hj3xm8k28zaf1apzgckvdp0n8r5d140m-linux-config-6.6.53.drv
  /nix/store/fnvx91ks9ywx325wgrgli3jmay12dq26-linux-6.6.53.drv
building '/nix/store/hj3xm8k28zaf1apzgckvdp0n8r5d140m-linux-config-6.6.53.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/25k6zgnmjzgfblfyl9w96400kbvdk3pn-linux-6.6.53.tar.xz
source root is linux-6.6.53
setting SOURCE_DATE_EPOCH to timestamp 1727706315 of file linux-6.6.53/virt/lib/irqbypass.c
Running phase: patchPhase
applying patch /nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch
patching file net/bridge/br_private.h
Hunk #1 succeeded at 51 with fuzz 2 (offset 12 lines).
applying patch /nix/store/mbz5gln1q4swlzmqs2399br98qjif9kn-request-key-helper.patch
patching file security/keys/request_key.c
Hunk #1 succeeded at 117 (offset 3 lines).
applying patch /nix/store/9kcpsj3kbx249nd7bz8lg0kyqv0y4h9c-?id=306ed1728e8438caed30332e1ab46b28c25fe3d8
patching file net/netfilter/xt_NFLOG.c
Hunk #1 FAILED at 79.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/xt_NFLOG.c.rej
patching file net/netfilter/xt_TRACE.c
Hunk #1 FAILED at 49.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/xt_TRACE.c.rej
patching file net/netfilter/xt_mark.c
Hunk #1 FAILED at 62.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/xt_mark.c.rej
error: builder for '/nix/store/hj3xm8k28zaf1apzgckvdp0n8r5d140m-linux-config-6.6.53.drv' failed with exit code 1;
```

### Additional context

Happens on release-24.05 and on current master after a netfilter fix was cherry-picked in https://github.com/NixOS/nixpkgs/pull/350500 and https://github.com/NixOS/nixpkgs/pull/350639

Change can be found in this commit: https://github.com/NixOS/nixpkgs/pull/350500/commits/7f3092416aeb3a50c7a5301dce051ea3198716c5

### Notify maintainers

Not sure who is actually responsible for hardended kernel. @Ma27  

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[simon@mare nixpkgs] $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, helsinki/NixOS, 24.05 (Uakari), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `""`
 - channels(simon): `""`
 - nixpkgs: `/home/simon/.nix-defexpr/channels/nixpkgs`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
Fix part of #350757.

**Comment by voidzero** [comment]
Thanks for fixing. Please forgive my lack of understanding but when will this be available in 24.05? I just did a `nix flake update` but it still occurs to me so I guess it's not promulgated to 24.05 yet.

**Comment by Ma27** [comment]
It should be in nixos-24.05 by now: https://nixpk.gs/pr-tracker.html?pr=351145

**Comment by voidzero** [comment]
Oh, that's very handy, thanks. Can confirm: it just allowed me to run nixos-rebuild without issues.
