### ISSUE TITLE
Raspberry 4 boot fails with rpi4 kernel, systemd-boot, UEFI

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#350689]
### Describe the bug
After rebuilding with some hardware and boot upgrades (see below), my Raspberry 4 fails to boot using the linux_rpi4 kernel. Latest kernel (6.11 as of now) works.

Booting to a generation with these changes, it doesn't even get to stage 1 of the NixOS boot process, this is the only thing I see:
```
EFI stub: Booting Linux Kernel...
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
EFI stub: Generating empty DTB
EFI stub: Exiting boot services...
```

### Previous configuration

I had an HDD with MBR partition table with an ext4 partition. I didn't change the bootloader, so it was using U-Boot. I'm also using the [raspberry-pi-4 module](https://github.com/NixOS/nixos-hardware/tree/ecfcd787f373f43307d764762e139a7cdeb9c22b/raspberry-pi/4) from nixos-hardware. This worked well.
```nix
{
  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" ];
    loader = {
      grub.enable = false;
      generic-extlinux-compatible.enable = true;
    };
  };

  # this is also set from nixos-hardware
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_rpi4;

  system.stateVersion = "23.05";
}
```

### New configuration

I've got a new SSD, put a GPT partition table on it and made a main btrfs partition and a vfat boot partition, and installed NixOS on it.

After cloning the previous configuration and enabling systemd-boot, I ran into this error: `The option system.build.installBootLoader is defined multiple times.` (related: https://github.com/NixOS/nixpkgs/issues/173948). To fix this I disabled `boot.generic-extrlinux-compatible`.
I also updated `system.stateVersion`, the hardware config.

After making these changes to the previous configuration, rebuilding, and rebooting, the latest boot entry fails with the aforementioned EFI stub messages.

Changing the kernel to the latest (non-rpi) fixed this issue.

```nix
{
  boot = {
    supportedFilesystems = [ "btrfs" ];
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot.enable = true;
      # systemd-boot and this tries to install bootloader, disable this
      generic-extlinux-compatible.enable = lib.mkForce false;
    };
  };

  # rpi kernel set from nixos-hardware fails with EFI stub error on boot
  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_latest;

  system.stateVersion = "24.05";
}
```

Full diff between previous and new config: https://github.com/ymstnt-com/raspi-dotfiles/compare/96aae2d3b44dcf32665f83fb0394c565cb5cc12e...f8fb07b50601dbe0ac74844743e617e2051a2b31

### Expected behavior
This should work with rpi4 kernel, or at least throw some useful errors.

### Notify maintainers

I couldn't find who is the official maintainer and searched for people who contributed to similar lower-level stuff, feel free to ignore if it's not related to you.

 @ElvishJerricco @Majiir  @arianvp @K900 @spiage

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

NOTE: I ran this on the latest kernel where this is not an issue.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
install: cannot remove '/tmp/env-vars': Operation not permitted
 - system: `"aarch64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: aarch64-linux
Additional system types: 
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/gep/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/gep/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/gep/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/gep/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/40i0syl2n33kakvlk24ymmg1vr6nhh0f-lix-2.91.0/share`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Please don't use vendor kernels.

**Comment by ElvishJerricco** [comment]
How are you booting the RPi4 with UEFI? That's not a standard part of the pi and there's multiple ways to do it, so it's a relevant detail.

Though whenever you see no output following `EFI stub: Exiting boot services...`, it usually means it is actually booting fine but the kernel just isn't using the right console. So try to e.g. connect to it over ssh or something, and/or use a `console=` kernel param to get it to output to the right console.

**Comment by ymstnt** [comment]
We are using [pftf/RPi](https://github.com/pftf/RPi) which provides installable builds of [official EDK2 Raspberry Pi 4 UEFI firmware](https://github.com/tianocore/edk2-platforms/tree/master/Platform/RaspberryPi/RPi4).

When this "error" happens, the Raspberry does not boot, which means we can't connect over SSH, nor using a monitor and keyboard.

We haven't tried the `console=` param though, but considering SSH doesn't work and the Raspberry doesn't appear online, I'd say it really gets stuck at the boot process.

**Comment by ElvishJerricco** [comment]
Sounds like a very early kernel panic then. I've had my fair share of experiences with that sort of problem with UEFI implementations on the RPi and I haven't learned much about how to deal with them. Suffices to say this is not a configuration that the RPi kernel devs support, so mainline might be worth a try. But, like I said, getting kernels to reliably boot on the available UEFI implementations for the RPi4 is rather painful.

**Comment by gepbird** [comment]
Thanks, we will be using the mainline kernel, so far we have no issues with it.

**Comment by aleks-sidorenko** [comment]
I'v used  [pftf/RPi4](https://github.com/pftf/RPi4) with `kernelPackages = pkgs.linuxPackages_latest;` with `systemd` bootloader and it worked, however before I have tried with `nixos-hardware.raspberry-pi."4"`, which uses ` kernelPackages = lib.mkDefault pkgs.linuxKernel.packages.linux_rpi4;` it failed with same error message `EFI stub: Exiting boot services...`.
I'v just removed `nixos-hardware.raspberry-pi."4"` and defined rpi config from scratch, however maybe it will work with `nixos-hardware.raspberry-pi."4"`  if you just `kernelPackages = lib.mkForce pkgs.linuxPackages_latest;`
I will try to test that too
