### ISSUE TITLE
Update request: cargo-hakari 0.9.28 → 0.9.33

### ISSUE THREAD

**Issue by david7a68** [NixOS/nixpkgs#350749]
- Package name: cargo-hakari
- Latest released version: 0.9.33
- Current version on the unstable channel: 0.9.30
- Current version on the stable/release channel: 0.9.28
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

There appears to be a partial update at #331244

**Notify maintainers**

@figsoda

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nartsisss** [comment]
https://github.com/NixOS/nixpkgs/pull/346942
