### ISSUE TITLE
Package request: Factorio Space Age

### ISSUE THREAD

**Issue by Sgiath** [NixOS/nixpkgs#350739]
**Project description**

There already is Factorio 1.x base game in the packages, the base game was updated to to 2.x on 2024-10-21 and I believe just simple udpdate would sufice. But also an addon "Space Age" was released on the same day which would probably require separate package or some update to the base game? Not sure

**Metadata**

* homepage URL: https://factorio.com/
* source URL: not applicable 
* license: unfree
* platforms: unix, linux, darwin

Pinging Factorio base game package maintainers: @Baughn @elitak @erictapen @priegger @lukegb

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lukegb** [comment]
It's already packaged at master as factorio-space-age. There's a backport in flight for 24.05 but it hasn't landed yet.

**Comment by Sgiath** [comment]
Sorry, I only checked on https://mynixos.com/search?q=factorio and clicked the link for the package file, but it references specific commit, so when I looked around I didn't see it because I wasn't on latest `master` 🤦🏻
