### ISSUE TITLE
zed editor ldconfig issue

### ISSUE THREAD

**Issue by deng232** [NixOS/nixpkgs#350810]
### Steps To Reproduce
open zed in terminal

### Expected behavior
zed open

### Additional context
terminal output:
```
.... (repeat outputs)
/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libVkLayer_MESA_overlay.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_dzn.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_lvp.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libVkLayer_INTEL_nullhw.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libEGL_mesa.so.0.0.0 is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libGLX_mesa.so.0 is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_virtio.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_intel_hasvk.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_nouveau.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libGLX_mesa.so.0.0.0 is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libGLX_mesa.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_radeon.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libEGL_mesa.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libEGL_mesa.so.0 is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_intel.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libVkLayer_MESA_overlay.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_dzn.so is truncated

/nix/store/vpsla1ivhavzd4fmi95yzmgb4g9rd072-glibc-2.40-36-bin/bin/ldconfig: file /run/opengl-driver-32/lib/libvulkan_lvp.so is truncated

bwrap: Creating new namespace failed: nesting depth or /proc/sys/user/max_*_namespaces exceeded (ENOSPC)
```
config:
```
  zed-fhs = pkgs.buildFHSUserEnv {
    name = "zed";
    targetPkgs = pkgs:
      with pkgs; [
        zed-editor
        nodejs_22
        nodePackages_latest.vscode-json-languageserver
        nixd
        nixpkgs-fmt
        tree-sitter-grammars.tree-sitter-bash
        bash-language-server
      ];
    runScript = "zed";
  };
```

### Notify maintainers
@GaetanLepage 
@niklaskorz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241018.4c2fcb0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/riqkpszjqk02bi1wppfg8ip5xvh102qd-source`
 ```

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by niklaskorz** [comment]
If you're using an FHS, you don't need to add the language servers yourself. Zed should be able to download its own language servers and run them.
Is there anything missing from our provided FHS wrapper for the packages you need?

**Comment by niklaskorz** [comment]
@deng232 From the looks of it, your log is from building the FHS env, not running zed-editor, right?

**Comment by VanCoding** [comment]
I'm having the same output when opening VSCode now. It still opens, though.

**Comment by deng232** [comment]
> @deng232 From the looks of it, your log is from building the FHS env, not running zed-editor, right?

Thabnks. Didn't realize it was being fhs packed recently. closing now

**Comment by saygo-png** [comment]
@deng232 How did you solve this? i have the same issue

**Comment by niklaskorz** [comment]
> @deng232 How did you solve this? i have the same issue

![xkcd 979: Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

They were referring to our `zed-editor.fhs` wrapper which is already included in nixpkgs, instead of defining their own fhs wrapper.

**Comment by SuperSandro2000** [comment]
Those are just warnings, things should work anyway.

**Comment by hermann-p** [comment]
Hm. I had been using `zed-editor` from unstable. A couple of weeks ago it started showing the gl-errors and would no longer start. After updating yesterday it shows the `bwrap: Creating new namespace failed: nesting depth or /proc/sys/user/max_*_namespaces exceeded (ENOSPC)`, without opening up. Did anyone ever get it to start recently?

**Comment by niklaskorz** [comment]
> Hm. I had been using `zed-editor` from unstable. A couple of weeks ago it started showing the gl-errors and would no longer start. After updating yesterday it shows the `bwrap: Creating new namespace failed: nesting depth or /proc/sys/user/max_*_namespaces exceeded (ENOSPC)`, without opening up. Did anyone ever get it to start recently?

Working fine on both NixOS 24.11 and on unstable:

![Screenshot from 2024-12-03 11-58-39](https://github.com/user-attachments/assets/80b19750-cb6c-41c4-9d64-2e9b6a130fdd)
![Screenshot from 2024-12-03 12-00-14](https://github.com/user-attachments/assets/00e4f5f1-d41f-4663-a7f2-c2016c31b8c0)
