### ISSUE TITLE
Update request: serd 0.30.16 -> 0.32.2

### ISSUE THREAD

**Issue by simonhollingshead** [NixOS/nixpkgs#350876]
- Package name: serd
- Latest released version: 0.32.2

- Current version on the unstable channel: 0.30.16
- Current version on the stable/release channel: 0.30.16

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
linked PRs got merged
