### ISSUE TITLE
vscode cpptools extensions not working

### ISSUE THREAD

**Issue by juliendehos** [NixOS/nixpkgs#35088]
## Issue description

The vscode cpptools extension is linked to `/lib64/ld-linux-x86-64.so.2`. 
```
$ file ~/.vscode/extensions/ms-vscode.cpptools-0.15.0/bin/Microsoft.VSCode.CPP.Extension.linux 
/home/dehos/.vscode/extensions/ms-vscode.cpptools-0.15.0/bin/Microsoft.VSCode.CPP.Extension.linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=4ab2b1c13cd195245e581b35901048f97acd1dda, not stripped
```

So the extension fails when editing a C++ file with vscode:
```
[Error - 10:41:56 AM] Starting client failed Launching server using command /home/.../.vscode/extensions/ms-vscode.cpptools-0.15.0/bin/Microsoft.VSCode.CPP.Extension.linux failed.
```

This issue has been reported in the vscode repo (https://github.com/Microsoft/vscode-cpptools/issues/1345) but I think it is more a packaging problem.

**Comment by ftpman** [comment]
I had this problem on Raspbian Desktop and, I solved it by installing AMD64 version of libc (`sudo apt-get install libc6-dev:amd64`), because `uname -r` returned 4.9.0-4-amd64, but `libc` was i386, VS Code was i386 and cpptools extension is amd64.

Before I only had /lib/ld-linux.so.2 and now I have /lib64/ld-linux-x85-64.so.2

**Comment by jcrben** [comment]
If you use `vscode-with-extensions` and https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/cpptools/default.nix then you can get it to work. Still haven't figured out if this means that I need to manage all my vscode extensions in nix tho.

I have this in my packageOverrides (pinnedPkgs is my thing):

```
      vscodeCpp = pinnedPkgs.vscode-with-extensions.override {
        vscodeExtensions = with vscode-extensions; [ ms-vscode.cpptools ];
      };
```

**Comment by danbst** [comment]
Alternative solution - https://discourse.nixos.org/t/vscode-extensions-setup/1801

This issue should be closed, as `cpptools` works in NixOS
