### ISSUE TITLE
steamcmd/steam-run - bwrap: Can't chdir to ...:  No such file or directory

### ISSUE THREAD

**Issue by diniamo** [NixOS/nixpkgs#350983]
### Describe the bug

Steamcmd has stopped working, and instantly quits with the error in the title. I haven't changed anything in the module, so updating nixpkgs must've been the cause.

I use it here: https://github.com/diniamo/niqs/blob/7b9af8e855f6664cb1b8ba5a3c09140776a3658f/modules/server/satisfactory.nix#L46-L52

### Steps To Reproduce
1. Set up a similar service to what I have linked above
2. Run it
3. See the error

### Expected behavior

Steamcmd works like before.

### Notify maintainers

@K900 - Not sure, but it looks like you have commits that could be relevant (both on steamcmd and steam-run)
@tadfisher - steamcmd maintainer

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.14, NixOS, 24.11 (Vicuna), 24.11.20241023.68783af`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-devpre20240914_7272582
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/diniamo/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/diniamo/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/diniamo/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/diniamo/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/wm6c3bsrcsp7snbnp2kwq718j1fniwis-lix-patched-2.92.0-devpre20240914_7272582/share`
 - nixpkgs: `/nix/store/min6i7ikkf4dhgppbpd2gpd1a8279rj9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Please post the full error log.

**Comment by diniamo** [comment]
This is all I have:
```
Oct 24 19:51:51 diniamo-SERVER systemd[1]: Starting Satisfactory dedicated server...
Oct 24 19:51:51 diniamo-SERVER satisfactory-pre-start[1611]: bwrap: Can't chdir to /var/lib/satisfactory: No such file or directory
Oct 24 19:51:51 diniamo-SERVER systemd[1]: satisfactory.service: Control process exited, code=exited, status=1/FAILURE
Oct 24 19:51:51 diniamo-SERVER systemd[1]: satisfactory.service: Failed with result 'exit-code'.
Oct 24 19:51:51 diniamo-SERVER systemd[1]: Failed to start Satisfactory dedicated server.```

**Comment by diniamo** [comment]
Could you link the PR?

**Comment by diniamo** [comment]
Tested, closing.
