### ISSUE TITLE
Build failure: nushell_plugins_net

### ISSUE THREAD

**Issue by mayersj1** [NixOS/nixpkgs#350952]
### Steps To Reproduce

1. build nushell_plugins_net
2. Error: 

building '/nix/store/p8r34r2facdxm8bmpf3s6bq1905frvpf-nushell_plugin_net-1.8.0-vendor.tar.gz.drv'...
error: hash mismatch in fixed-output derivation '/nix/store/p8r34r2facdxm8bmpf3s6bq1905frvpf-nushell_plugin_net-1.8.0-vendor.tar.gz.drv':
         specified: sha256-3FMalpgKYZ4xM2fHXTFOVu5I8yS06K1bDiKg4we7jF4=
            got:    sha256-bsrpdQS0wA3T0jZTG476sSkMRngEAOjgr4wX7svyMP4=

### Build log

```
nix build github:nixos/nixpkgs/nixpkgs-unstable#nushell_plugins_net
error: flake 'github:nixos/nixpkgs/nixpkgs-unstable' does not provide attribute 'packages.aarch64-darwin.nushell_plugins_net', 'legacyPackages.aarch64-darwin.nushell_plugins_net' or 'nushell_plugins_net'

```

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/nix/store/v6r3n8gkyv0p9qwlvjc1k0lkiyb0712l-source`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by happysalada** [comment]
Hey this was fixed a couple of days ago and should land on unstable by the end of the week.
Im closing this for now, but please reopen if this is not working in one week

**Comment by mayersj1** [comment]
What commit/PR was this fixed in?

**Comment by happysalada** [comment]
https://github.com/NixOS/nixpkgs/pull/351440
