### ISSUE TITLE
Package request: Sonusmix

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#350986]
**Project description**

A tool to easily route and manage audio devices in Pipewire. It intends to enable the same features and workflows as [Voicemeeter](https://vb-audio.com/Voicemeeter/) or [Pulsemeeter](https://github.com/theRealCarneiro/pulsemeeter), but with a more intuitive interface, and while making it as easy as possible to combine with other Pipewire audio apps.

**Metadata**

* homepage URL: https://codeberg.org/sonusmix/sonusmix
* source URL: https://codeberg.org/sonusmix/sonusmix
* license: Mozilla Public License Version 2.0
* platforms: Linux
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dacid44** [comment]
We have a `default.nix` written that afaik does work, but I'm not familiar with submitting stuff to nixpkgs. https://codeberg.org/sonusmix/sonusmix/src/commit/7369dab35f38174854f18f41cfb4452391948599/default.nix
