### ISSUE TITLE
Opensnitch runtime error due to Python package not currently in nixpkg repo

### ISSUE THREAD

**Issue by guttermonk** [NixOS/nixpkgs#350923]
### Describe the bug
On unstable, when I run “opensnitch-ui” I get the following error:
```
/nix/store/dyjz8kf7id22i9js6lkknq71pvm3z1i6-python3.11-protobuf-5.28.2/lib/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at ui.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
Traceback (most recent call last):
  File "/nix/store/0k12vibb7qw546nw3wpwvys1zaz9yz3v-opensnitch-ui-1.6.6/bin/.opensnitch-ui-wrapped", line 42, in <module>
    from opensnitch.service import UIService
  File "/nix/store/0k12vibb7qw546nw3wpwvys1zaz9yz3v-opensnitch-ui-1.6.6/lib/python3.11/site-packages/opensnitch/service.py", line 16, in <module>
    from opensnitch import ui_pb2_grpc
  File "/nix/store/0k12vibb7qw546nw3wpwvys1zaz9yz3v-opensnitch-ui-1.6.6/lib/python3.11/site-packages/opensnitch/ui_pb2_grpc.py", line 19, in <module>
    raise RuntimeError(
RuntimeError: The grpc package installed is at version 1.64.1, but the generated code in ui_pb2_grpc.py depends on grpcio>=1.66.1. Please upgrade your grpc module to grpcio>=1.66.1 or downgrade your generated code using grpcio-tools<=1.64.1.
```
The latest version of [grpcio 2](https://search.nixos.org/packages?channel=unstable&show=python312Packages.grpcio&from=0&size=50&sort=relevance&type=packages&query=grpcio) available is v1.64.1. How would I go about getting grpcio v1.66.1 or later in NixOS?

I also tried installing [grpc](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=grpc) (v1.66.1) and [python313](https://search.nixos.org/packages?channel=unstable&show=python313&from=0&size=50&sort=relevance&type=packages&query=python313) to no avail.

### Steps To Reproduce
1. Switch from 24.05 to 'unstable'
2. Run `opensnitch-ui`

### Notify maintainers
@onny 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241020.1997e4a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/dyzl40h25l04565n90psbhzgnc5vp2xr-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by oldshensheep** [comment]
Once [this pull request](https://github.com/NixOS/nixpkgs/pull/350432) is merged into unstable, it should work. For now, you'll need to write an overlay for opensnitch-ui. I'll just wait.

**Comment by scraptux** [comment]
#350432 merged successfully and the changes are now in the unstable branch. I was able to run opensnitch-ui without errors, therefore closing this issue.

**Comment by Dietr1ch** [comment]
Was this verified?


I just got some trouble with a package, I'm guessing that other dependencies might be necessary,

```log
Feb 02 16:29:31 potato systemd[1389]: Started Opensnitch ui.
Feb 02 16:29:32 potato opensnitch-ui[2311]: Traceback (most recent call last):
Feb 02 16:29:32 potato opensnitch-ui[2311]:   File "/nix/store/yl0g1b9g25nnyi84v34li7ly0y2f5cq2-opensnitch-ui-1.6.7/bin/.opensnitch-ui-wrapped", line 42, in <module>
Feb 02 16:29:32 potato opensnitch-ui[2311]:     from opensnitch.service import UIService
Feb 02 16:29:32 potato opensnitch-ui[2311]:   File "/nix/store/yl0g1b9g25nnyi84v34li7ly0y2f5cq2-opensnitch-ui-1.6.7/lib/python3.11/site-packages/opensnitch/service.py", line 15, in <module>
Feb 02 16:29:32 potato opensnitch-ui[2311]:     import opensnitch.proto as proto
Feb 02 16:29:32 potato opensnitch-ui[2311]:   File "/nix/store/yl0g1b9g25nnyi84v34li7ly0y2f5cq2-opensnitch-ui-1.6.7/lib/python3.11/site-packages/opensnitch/proto/__init__.py", line 19, in <module>
Feb 02 16:29:32 potato opensnitch-ui[2311]:     from packaging.version import Version
Feb 02 16:29:32 potato opensnitch-ui[2311]: ModuleNotFoundError: No module named 'packaging'
```

**Comment by scraptux** [comment]
This seems to be fixed by #372352.
Please check whether your current revision includes the mentioned PR.

**Comment by Dietr1ch** [comment]
Thanks! Then it should be just that `nixos-unstable` hasn't caught up yet.

**Comment by thenbe** [comment]
@Dietr1ch You can tell whether `nixos-unstable` has caught up or not using this tool: https://nixpk.gs/pr-tracker.html?pr=372352. It has caught up, you likely need to run `nix flake update` (or update the channel if you're not using flakes) and then rebuild your system to pull the latest `nixos-unstable`.
