### ISSUE TITLE
Steam: UpdateUI: skip show logodlmopen steamui.so failed: /lib32/libcairo.so.2: undefined symbol: pixman_image_set_dither

### ISSUE THREAD

**Issue by cublae** [NixOS/nixpkgs#351023]
### Describe the bug
Steam won't launch, gives steamui.so error on last commit if enabled via program.steam.

### Steps To Reproduce
1. Update flake.lock
2. Run steam
3. See the error

### Expected behavior
Successful launch of Steam

### Steam logs
```
UpdateUI: skip show logodlmopen steamui.so failed: /lib32/libcairo.so.2: undefined symbol: pixman_image_set_dither
Failed to load steamui.so - dlerror(): (null)
[2024-10-24 23:35:13] Shutdown
```
### Notify maintainers
@K900

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Please post your configuration.

**Comment by pyrox0** [comment]
my configuration has the same issue, all I do is `programs.steam.enable = true`.

My nixpkgs input to my flake is `github:nixos/nixpkgs/cabaf14d3e69c9921d7acedf5d7d60bb2b90be02`(a commit on nixpkgs-unstable, which is the branch I follow.

**Comment by K900** [comment]
Can you try running `steam --reset`?

**Comment by pyrox0** [comment]
Word of warning to anyone else following this thread: That command resets your steam installation, including deleting any games you have downloaded, and logging you out. Just so you're aware!

**Comment by K900** [comment]
It should not delete your games, AFAIK? It does log you out though.

**Comment by pyrox0** [comment]
I can no longer find `~/.local/share/Steam/steamapps` or `~/.steam/steam/steamapps`, which is where games are installed.

**Comment by pyrox0** [comment]
Launching after a `steam --reset` and waiting for it to install the update, the same error occurs.

**Comment by K900** [comment]
That's very strange. Can you also post your `hardware.graphics` configuration?

**Comment by pyrox0** [comment]
```nix
hardware.graphics = {
  enable = true;
  extraPackages = [
    pkgs.gamescope
    pkgs.libva
    pkgs.libvdpau
    pkgs.libvdpau-va-gl
    pkgs.mangohud
    pkgs.mesa
    pkgs.vaapiVdpau
  ];
  extraPackages32 = [
    pkgs.gamescope
    pkgs.mangohud
    pkgs.mesa
  ];
};
```

**Comment by K900** [comment]
Yeah that's definitely wrong. The stuff from `extraPackages32` needs to be 32-bit versions, i.e. `pkgs.pkgsi686Linux.gamescope`, etc. We've been brainstorming an assertion for that but Nvidia is kind of a problem for Complicated Reasons. Also, mesa should definitely not be there, and neither should libva or libvdpau.

**Comment by pyrox0** [comment]
That's strange, none of this has been problematic in the past, and I use the AMD iGPU on my CPU, no Nvidia hardware.

**Comment by K900** [comment]
Other people use Nvidia, and blowing them up with an assertion is the problem. Also, if you're not using Nvidia, you can get rid of all the other vdpau-related things too.

**Comment by cublae** [comment]
Oh, i missed this moment, I will try soon to download from ```pkgsi686Linux```

**Comment by cublae** [comment]
Is solved my problem, thanks
