### ISSUE TITLE
Build failure: tailwindcss

### ISSUE THREAD

**Issue by ppom0** [NixOS/nixpkgs#351137]
Hi all!

It seems like I can't build tailwindcss with an extra plugin.
The issue seem to be node-package wide.

Here it is:

### Steps To Reproduce

`shell.nix`
```nix
let pkgs = import <nixos-unstable> {};
in pkgs.mkShell {
  name = "tailwind";
  buildInputs = [
    (pkgs.pkgs.tailwindcss.overrideAttrs (old: {
      plugins = [ pkgs.pkgs.nodePackages."@tailwindcss/typography" ];
    }))
  ];
  src = null;
  shellHook = "";
} 
```

### Build log

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'tailwind'
         whose name attribute is located at /nix/store/zlb6mx5dc6qsb66397k0szgb34lzq5x5-nixos-unstable/nixos-unstable/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildInputs' of derivation 'tailwind'

         at /nix/store/zlb6mx5dc6qsb66397k0szgb34lzq5x5-nixos-unstable/nixos-unstable/pkgs/stdenv/generic/make-derivation.nix:383:7:

          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'utillinux' has been renamed to/replaced by 'util-linux'
```

### Additional context

I think it's related to this line, which was for 20.09. Maybe useless now?

https://github.com/NixOS/nixpkgs/blob/e0464e4/pkgs/development/node-packages/node-env.nix#L7

Maybe related issue: https://github.com/NixOS/nixpkgs/issues/350738

### Notify maintainers

because it's node-packages wide: @Luflosi 
because it targets tailwindcss: @adamcstephens

**Comment by FliegendeWurst** [comment]
Probably also fixed by #350815

**Comment by adamcstephens** [comment]
If there's a node issue, it's unrelated to tailwindcss. https://github.com/NixOS/nixpkgs/blob/7eabf557d4fd5e7195cb3e372304ffdeb04170a9/pkgs/development/tools/tailwindcss/default.nix

**Comment by ppom0** [comment]
Oh, that's right. I thought I was adding the typography myself, but it's actually already integrated in the bundle. Thanks!
