### ISSUE TITLE
datadog-agent: incompatible with Go > 1.21, needs update

### ISSUE THREAD

**Issue by katexochen** [NixOS/nixpkgs#351119]
> Heads up that this PR breaks datadog-agent as re-introduces the issue in https://github.com/NixOS/nixpkgs/issues/299469

_Originally posted by @ryanrasti in https://github.com/NixOS/nixpkgs/issues/344622#issuecomment-2433332686_

maintainers: @thoughtpolice @domenkozar

**Comment by katexochen** [comment]
Newer versions support Go 1.22, but update seems non-trivial.

**Comment by Smona** [comment]
I have 7.56.2 working with Go 1.22 and with a few existing issues fixed [here](https://github.com/NixOS/nixpkgs/compare/master...Smona:nixpkgs-upstream:upgrade-datadog?expand=1), I just need to do a little more testing and fix the commits then i can put it up.
