### ISSUE TITLE
Update request: marp-cli 3.4.0 → 4.0.0

### ISSUE THREAD

**Issue by delvinru** [NixOS/nixpkgs#351203]
- Package name: marp-cli
- Latest released version: 4.0.0

- Current version on the unstable channel: 3.4.0
- Current version on the stable/release channel: 3.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@GuillaumeDesforges @marcusramberg 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GuillaumeDesforges** [comment]
marp-cli does not use yarn anymore, so we can use the [standard nixpkgs npm packaging](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#adding-and-updating-javascript-packages-in-nixpkgs-javascript-adding-or-updating-packages) and remove the old one.
