### ISSUE TITLE
Build failure: helm

### ISSUE THREAD

**Issue by Byteingpython** [NixOS/nixpkgs#351395]
### Steps To Reproduce

1. build helm

### Build log

https://gist.github.com/Byteingpython/df6d8d0a7e7988f079ca0463d7f4faa9

### Notify maintainers

@magnetophon 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
Fixed by #350450 - already merged but not on `nixos-unstable` yet: https://nixpk.gs/pr-tracker.html?pr=350450
