### ISSUE TITLE
Clojure doesn't list all dependencies on classpath

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#35136]
https://travis-ci.org/hackberryhike/hackberryhike.com/builds/343076733
https://travis-ci.org/hackberryhike/hackberryhike.com/builds/343080956 (after adding `org.clojure/data.json` to `deps.edn`)

This has happened after 77fead018146843ae8dce908af0c6d9404c8c87e and 8ac63bd82c1e1a4c22f363d8ffb6546bb5ae18f5. Probably the version bump.

Can I revert this? /cc @bendlas

**Comment by yegortimoshenko** [comment]
Indeed, it's the version bump causing this. Given that this is a critical bug, I think it should be reverted to the last working version, sadly (I think the new version supports Git for fetching deps).

**Comment by bendlas** [comment]
I'm trying to get to a minimal reproducible case for this, to put into a tools.deps ticket.
The weird thing is, that your stack trace says `java.lang.ClassNotFoundException: com.google.javascript.jscomp.CompilerOptions`. Might this be some issue with a common dependency of google-closure-compiler and data.json?

Personally, I'd also be interested in how, this thing I've been working on, [dwn](https://github.com/webnf/dwn) handles this resolution. Unfortunately, it doesn't have a deps.edn reader, right now ...

**Comment by bendlas** [comment]
hm, no there is definitely something fishy with tools.deps. It finds the jar, but doesn't find the jar's dependencies:
```
[nix-shell:~/checkout/hackberryhike.com]$ clj -Stree
org.clojure/data.json 0.2.6
org.clojure/clojure 1.9.0
  org.clojure/core.specs.alpha 0.1.24
  org.clojure/spec.alpha 0.1.143
org.clojure/data.zip 0.1.2
com.cognitect/transit-cljs 0.8.239
  com.cognitect/transit-js 0.8.846
org.clojure/clojurescript clojurescript/target/clojurescript-0.0-SNAPSHOT.jar
commons-io/commons-io 2.5
rum/rum 0.10.8
  sablono/sablono 0.7.7
org.clojure/data.xml 0.2.0-alpha2
reagent/reagent 0.8.0-alpha2
  cljsjs/react-dom 15.6.2-0
  cljsjs/react 15.6.2-0
  cljsjs/react-dom-server 15.6.2-0
  cljsjs/create-react-class 15.6.2-0
org.clojure/core.async 0.3.441
  org.clojure/tools.analyzer.jvm 0.7.0
    org.clojure/tools.analyzer 0.6.9
    org.clojure/tools.reader 1.0.0-beta4
    org.clojure/core.memoize 0.5.9
      org.clojure/core.cache 0.6.5
        org.clojure/data.priority-map 0.0.7
    org.ow2.asm/asm-all 4.2
```

**Comment by bendlas** [comment]
cc https://github.com/NixOS/nixpkgs/pull/35140

**Comment by bendlas** [comment]
So, the issue seems to be, that tools.deps always returns the empty vector, when asked for the dependencies of a jar: https://github.com/clojure/tools.deps.alpha/blob/6e3a59326b952ee19848d5508aefdb9575fc133a/src/main/clojure/clojure/tools/deps/alpha/extensions/local.clj#L37

Can you help me find the code path, by which this has worked on `1.9.0.273`, so that we can file a regression?

**Comment by yegortimoshenko** [comment]
Sure! Going to bisect it.

**Comment by bendlas** [comment]
Hm, the corresponding place in tools.deps 0.2.196, would also return the empty vector for a jar: https://github.com/clojure/tools.deps.alpha/blob/fef31343afb61bbd05885d09218578831f4b43f8/src/main/clojure/clojure/tools/deps/alpha/providers/local.clj#L28

weird

**Comment by yegortimoshenko** [comment]
This is clearly a mistake on my part, local jars can't have dependencies and I relied on some. Meaning, it was not a degradation but a fix. Sorry for the noise.
