### ISSUE TITLE
firehol 3.1.5: package doesn't include firehol program by default 

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#35139]
The firehol derivation has a parameter `onlyQOS ? true`. 
So by default, the firehol package only includes `fireqos` (traffic shaping tool) but not `firehol` (firewall).

This is not really what a user expects from a package called "firehol".

I propose changing the default to `onlyQOS ? false` (or eliminate the parameter altogether) to make the `firehol` program available without override. No significant impact on build time or storage, just  few extra files.

/cc maintainer: @geistesk

**Comment by geistesk** [comment]
While writing this package I was only interested in `fireqos` and added this parameter to keep the package smaller. Setting it to `true` by default seems to be a bad decision. Changing it to `false` seems fine for me.
Please excuse my late response.

**Comment by xeji** [comment]
Thank you  for your reply. So let's change the default to `false`. I will add this change to my open pull request #35121.
