### ISSUE TITLE
Build failure on `staging-next`: `virtualboxHardened`

### ISSUE THREAD

**Issue by Yarny0** [NixOS/nixpkgs#351413]
### Steps To Reproduce

1. checkout out [current `staging-next`](https://github.com/NixOS/nixpkgs/tree/1889ebd947f76f0df7d5c4b3fd524749efc0e337).
2. build `virtualboxHardened`

### Build log

[see hydra](https://hydra.nixos.org/build/276246009)

### Additional context

Bisection from [a working commit](https://github.com/NixOS/nixpkgs/tree/9ddc3313c87d0caf403c5a844ba4fcb7c8ec3c83) yielded [a merge commit](https://github.com/NixOS/nixpkgs/tree/fdc64cfee0a86eeede2d7f8b7ccab1ef7442ad96) as the offender.  However, [both](https://github.com/NixOS/nixpkgs/tree/6d8e83ba5dcd0f710695b83b180de1f8448e82e5) [parents](https://github.com/NixOS/nixpkgs/tree/10c5d46352fdfcebde9877138c3e9a3a31a0160a) each on its own do *not* break `virtualboxHardened`.

Bisecting and combining both parent branches down to their merge base commit then uncovered these commits:

* https://github.com/NixOS/nixpkgs/commit/4c6b6c0c5d1ac0ac0e81c94d020d3f89d6615931
* https://github.com/NixOS/nixpkgs/commit/51b89f240633af946daed1c8319e66557f0286b6

If *one* of these commits is reverted on the current `staging-next`, `virtualboxHardened` is fixed.

I can't really grasp how these these commits interact and/or influence VirtualBox.

### Notify maintainers

@friedrichaltheide
@svanderburg
@blitz

Also notifying authors of offending commits: @trofi @skeuchel

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by skeuchel** [comment]
The `os2.h` file comes from the `open-watcom-bin` package. For some reason the header file is not installed anymore. @blitz (maintainer of the `open-watcom-bin`) do you have any insights on what might be happening here? 

Also note that the same compile error was mentioned in https://github.com/NixOS/nixpkgs/issues/300483.

**Comment by emilazy** [comment]
This is blocking the channel, so I’ve opened https://github.com/NixOS/nixpkgs/pull/352603 to remove it as a blocker.

**Comment by Yarny0** [comment]
Thank you @emilazy and @skeuchel, you are my heroes!

P.S.: I tested [both](https://github.com/NixOS/nixpkgs/pull/352609) [PRs](https://github.com/NixOS/nixpkgs/pull/352610) (together, cherry-picked only recent [`staging-next`](https://github.com/NixOS/nixpkgs/tree/a37eba4c96ca51a50a2fb9ce70729f928a18034a)): `virtualboxHardened` builds and all `nixosTests.virtualbox` tests pass.
