### ISSUE TITLE
Using python library with dependencies from another application

### ISSUE THREAD

**Issue by rvolosatovs** [NixOS/nixpkgs#35149]
## Issue description
I want to use a `neovim` [plugin](https://github.com/raghur/vim-ghost), written in Python. The plugin has a dependency on https://github.com/dpallot/simple-websocket-server.
How can I make the dependency available at runtime to the plugin?

Simply installing the dependency using `pip` failed with an error about `setuptools`.

The only solution I can think of is starting `neovim` from a `nix-shell`. Is there a more elegant way to do this?

**Comment by dotlambda** [comment]
You can override `extraPython(3)Packages`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/neovim/wrapper.nix

**Comment by rvolosatovs** [comment]
Thanks!
