### ISSUE TITLE
Enabling freetype inside fonts makes everything go into infinite loop somewhere.

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#3515]
If I uncomment the `freetype` font in this block:

```
  fonts = {
    enableFontConfig = true;
    enableFontDir = true;
    enableGhostscriptFonts = true;
    fonts = with pkgs; [
      corefonts
      dejavu_fonts
      # freetype # causes applications to grind CPU at start without
      # actually starting them
      inconsolata
      source-han-sans-japanese
      source-han-sans-korean
      source-han-sans-simplified-chinese
      source-han-sans-traditional-chinese
      ubuntu_font_family
    ];
  };
```

then `nixos-rebuild switch` and try to start up an application, it will not start. It will instead show up on the process list as using up my CPU, in full if it can. I confirmed this behaviour with `dwb` and `rxvt_unicode` but I'm sure anything loading fonts will do. Considering it occurs with two distinct applications, the problem seems to lie in font itself. While `freetype` itself should go inside systemPackages, it doesn't seems like it should spin up and do nothing if the user makes a mistake and puts it in fonts.

**Comment by ttuegel** [comment]
This should no longer be an issue with the new fontconfig update. Please re-open if it continues to be a problem.

**Comment by Fuuzetsu** [comment]
I just hit the same symptoms on master, again. I ran another do-nothing `nixos-rebuild switch` and it fixed itself. I don't know.
