### ISSUE TITLE
Rust Rover cannot find `libjvm.so`

### ISSUE THREAD

**Issue by NightEule5** [NixOS/nixpkgs#351524]
### Describe the bug
Rust Rover doesn't start, as it searches for `libjvm.so` in the wrong directory. When run in command line:

```
Cannot start the IDE
Cannot start the runtime

Caused by:
    0: Failed to load 'libjvm.so'
    1: /nix/store/w8l5vclykfzkghb9l4za5rzl5v2l2dm6-jetbrains-jdk-jcef-17.0.7-b829.16/lib/server/libjvm.so: cannot open shared object file: No such file or directory

Please try to reinstall the IDE.
For support, please refer to https://jb.gg/ide/critical-startup-errors
```

At some point, `libjvm.so` moved to `lib/openjdk/lib/server/` without changing the path in Rust Rover. I tried IDEA, and it works just fine. This issue seems to be limited to Rust Rover specifically. The version on the stable 24.05 channel does work.

### Steps To Reproduce
1. Install latest unstable `jetbrains.rust-rover` package
2. Run it

### Expected behavior
Rust Rover should start as expected

### Notify maintainers

@GenericNerdyUsername 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.4, NixOS, 24.05 (Uakari), 24.05.20241023.32e940c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.20.3`
 - nixpkgs: `/home/night/.nix-defexpr/channels/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
Cannot reproduce on the latest master commit, ran with `nix run github:NixOS/nixpkgs#jetbrains.rust-rover` and it works fine (at least, the IDE opens, I didn't test beyond that).

Could you test with a more updated version of Nixpkgs and let us know if this is still an issue? Preferrably, providing an exact commit and exact steps to reproduce would be appreciated.

**Comment by NightEule5** [comment]
> Cannot reproduce on the latest master commit, ran with `nix run github:NixOS/nixpkgs#jetbrains.rust-rover` and it works fine (at least, the IDE opens, I didn't test beyond that).
> 
> Could you test with a more updated version of Nixpkgs and let us know if this is still an issue? Preferrably, providing an exact commit and exact steps to reproduce would be appreciated.

Well that's interesting. I ran the latest version with `nix run`, and it worked. When I tried running the version that was broken again, it works now too. I'll try updating my build to the newest version and clean old builds to see if that changes

**Comment by NightEule5** [comment]
Everything works fine now
