### ISSUE TITLE
Build failure: gbenchmark 32bit

### ISSUE THREAD

**Issue by fliiiix** [NixOS/nixpkgs#351625]
### Steps To Reproduce

1. nix-build -A gbenchmark --argstr system i686-linux

### Build log

```
-- Performing Test HAVE_PTHREAD_AFFINITY -- success
CMake Error at CMakeLists.txt:343 (find_package):
  Could not find a package configuration file provided by "GTest" with any of
  the following names:

    GTestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "GTest" to CMAKE_PREFIX_PATH or set
  "GTest_DIR" to a directory containing one of the above files.  If "GTest"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

### Additional context

CMake requires gtest to configure even if test do not run.
This is a combination of:
- dd4290f5802fc4e7c96e93452dedfe4bf9b71321 by @K900 disabling checks for 32bit
- 449f466945ccedb675c6e8060f4a2b03ef9d4766 by @emilazy devendoring gtest 

I guess the easy fix is to move `gtest` just into `nativeBuildInputs`. 
Or patch the find_package in case of a 32bit build.

Or enable tests on 32bit? Maybe the newer version fixed the precision issues?
I don't have a real 32bit system to test but at least the test run with 
`nix-build -A gbenchmark --argstr system i686-linux` on a 64bit system (see metadata).

Mostly looking for advice i can propose a fix for all 3 scenarios if needed. 
@abbradar This pr should/could be closed right https://github.com/NixOS/nixpkgs/pull/335907 i was a bit confused by it, since the version on master is already 1.9.0.

### Notify maintainers

@K900, @emilazy, @abbradar

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-45-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/home/l33tname/.nix-defexpr/channels/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilazy** [comment]
Was this not fixed by https://github.com/NixOS/nixpkgs/pull/349788?

**Comment by fliiiix** [comment]
ahh well :sweat_smile: 

![image](https://github.com/user-attachments/assets/e3d60ff5-a04c-420a-9e92-ab9ec1c60c52)

I was working on other things in the meantime before i had time to dig into this issue again an report it.
