### ISSUE TITLE
Update request: Jellyfin 10.9.11 → 10.10.0

### ISSUE THREAD

**Issue by Titaniumtown** [NixOS/nixpkgs#351607]
- Package name: Jellyfin
- Latest released version: [10.10.0](https://github.com/jellyfin/jellyfin/releases/tag/v10.10.0)

- Current version on the unstable channel: 10.9.11
- Current version on the stable/release channel: 10.9.11

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@nyanloutre @minijackson @purcell @jojosch 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by justinas** [comment]
Once this is done, we can also bump `jellyfin-ffmpeg` to v7.

https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v7.0.2-5

> * 7.0 version is NOT fully compatible with Jellyfin 10.9.z.
> * Downstream should wait until Jellyfin 10.10.z is released before upgrading to this version.


https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v7.0.2-4

**Comment by justinkb** [comment]
I've done this locally (not the jellyfin-ffmpeg thing yet), it's pretty straightforward, the only thing to keep in mind is it has a new optional dependency that grabs native binaries for dart sass, which won't work for nix, but you only have remove the sass-embedded* stuff in node_modules in preBuild for jellyfin-web to fix that
