### ISSUE TITLE
ACME v2 [support for wildcard certificates]

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#35168]
## Issue description

Let's Encrypt should roll out new protocol version with subdomain wildcards support on February 27, 2018 https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html
So plan is
- [ ] support ACME v2 in `acme` service
- [ ] don't use `services.nginx.virtualHosts.<name>.serverName` for certificate names, instead always use just `services.nginx.virtualHosts.<name>`, that's because `serverName` may contain regular expression and not just name.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by volth** [comment]
related https://github.com/NixOS/nixpkgs/issues/34941

**Comment by domenkozar** [comment]
And it's live: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by gnidorah** [comment]
Sadly for wildcard certificates generation they currently only support dns-01 challenge mechanism, and that means client at each regeneration adds TXT record with new token (via DNS hoster API). And that's
1. not secure solution
2. requires support from DNS hoster
Would be great if they come with more practical solution

**Comment by leo60228** [comment]
ACMEv1 is now deprecated. You cannot enable it on new systems.

**Comment by flokli** [comment]
The acme NixOS module was migrated to use the ACMEv2 endpoint in https://github.com/NixOS/nixpkgs/pull/71291 (master) and https://github.com/NixOS/nixpkgs/pull/71953 (19.09), closing this issue.

DNS-01 challenge is worked on in https://github.com/NixOS/nixpkgs/pull/77578, please test!
