### ISSUE TITLE
makeWrapper doesn't work with set +u

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nixpkgs#35164]
If a calling script has the bash +u option set (which errors when you try to evaluate an undefined variable), calling makeWrapper fails with `/nix/store/kys8yd91kifj8di5pjhaxhf6hgamxqcz-hook/nix-support/setup-hook: line 107: flagsBefore: unbound variable`.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/72347

**Comment by FliegendeWurst** [comment]
Fixed in #148279
