### ISSUE TITLE
[Vim sqlite-lua] Insert of sqlite binary is not a string

### ISSUE THREAD

**Issue by Lewenhaupt** [NixOS/nixpkgs#351754]
The sqlite-lua override is incorrect and doesn't work because the substitution does not place the path as a string in the file causing an error when loading the sqlite/defs.lua file. This is the line that I have in my store: `path = vim.g.sqlite_clib_path or /nix/store/g2i5j8i0bwfih7hg2wbc15k2969bckn3-sqlite-3.46.0/lib/libsqlite3.so`.
I think it's simply a missing wrap of the `${lib.escapeShellArg libsqlite}` value.
https://github.com/NixOS/nixpkgs/blob/86e78d3d2084ff87688da662cf78c2af085d8e73/pkgs/applications/editors/vim/plugins/overrides.nix#L2018
@khaneliman

**Comment by khaneliman** [comment]
Thanks for reporting. I'll take a look real quick.

**Comment by khaneliman** [comment]
Does the PR resolve this for you?

**Comment by Lewenhaupt** [comment]
@khaneliman let me check! But it looks like it should work.

**Comment by khaneliman** [comment]
Looks like I came across this being broken during a nixvim tests, too... just forgot to come back to it. https://github.com/nix-community/nixvim/blob/a20fbbc4b9665ec215e7bea061a1d64f6fd652ce/tests/test-sources/plugins/by-name/yanky/default.nix#L63-L65 Looks like it fixes that test when I point at the PR branch. Thank you very much for identifying the issue!

**Comment by Lewenhaupt** [comment]
Yeah seems my build now works properly :) Thanks for the quick response!
