### ISSUE TITLE
vimPlugins.magma-nvim-goose: migrate to magma-nvim

### ISSUE THREAD

**Issue by trueNAHO** [NixOS/nixpkgs#351703]
The [`vimPlugins.magma-nvim-goose`](https://github.com/NixOS/nixpkgs/commit/85c1280f0e3c5ff1cb6a47e051b4481e22c1f67d) package should be deprecated in favor of a new `vimPlugins.magma-nvim` package, as its current `src` (https://github.com/WhiteBlackGoose/magma-nvim-goose) was [archived on 2023/07/03](https://github.com/WhiteBlackGoose/magma-nvim-goose/commit/9a626aab63361d027541d023707f82e28d7f872c) in favor of its [upstream repository](https://github.com/dccsillag/magma-nvim).

This deprecation also affects the [`programs.nixvim.plugings.magma-nvim` NixVim plugin](https://github.com/nix-community/nixvim/blob/bb0e3892a27efdc6f9c1771927f513577cb1c671/plugins/by-name/magma-nvim/default.nix).

---

Cc: @GaetanLepage

**Comment by GaetanLepage** [comment]
Thanks for reporting this.
I opened a PR.
