### ISSUE TITLE
Build failure: Linux kernel on riscv64

### ISSUE THREAD

**Issue by jayay** [NixOS/nixpkgs#351811]
### Steps To Reproduce

1. Get a StarFive VisionFive 2
2. Install NixOS on an SD-Card
3. Rebuild the whole system using `nixos-rebuild boot`

### Build log

```
...
  AR      built-in.a
  AR      vmlinux.a
  LD      vmlinux.o
/nix/store/nv091px0zlim9iysqrg6hsg06509kg69-binutils-2.43.1/bin/ld: fs/proc/base.o: invalid string offset 139784 >= 139700 for section `.strtab'
/nix/store/nv091px0zlim9iysqrg6hsg06509kg69-binutils-2.43.1/bin/ld: final link failed
make[2]: *** [../scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 1
make[1]: *** [/build/linux-6.11.4/Makefile:1138: vmlinux_o] Error 2
make: *** [../Makefile:224: __sub-make] Error 2
error: builder for '/nix/store/62n7r206nh0a6vfpw76l8b04d5bjnl37-linux-6.11.4.drv' failed with exit code 2
...
```

### Additional context

I did set `boot.kernelPackages = pkgs.linuxPackages_latest;` but it happens as well with the default kernel. I am on NixOS unstable. I am not cross-compiling, but building on the device.

### Notify maintainers

@ericson2314 
@K900 

### Metadata

```
 - system: `"riscv64-linux"`
 - host os: `Linux 6.11.3, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by skeuchel** [comment]
I have successfully built 6.11.4 and 6.11.6 on my system. That is for vanilla rv64gc. Are you using any march / mtune flags?

**Comment by jayay** [comment]
@skeuchel huh, that's weird. Just to be clear: you're building the kernel from nix on the device itself? 

I didn't enable any additional compiler flags, no.

**Comment by skeuchel** [comment]
> @skeuchel huh, that's weird. Just to be clear: you're building the kernel from nix on the device itself?
> 
> I didn't enable any additional compiler flags, no.

Yes, natively on a risc-v device, just that it was a pioneer instead of a visionfive 2. 

I had the same binutils path `/nix/store/nv091px0zlim9iysqrg6hsg06509kg69-binutils-2.43.1` a while ago, so yeah it seems the toolchain is the same. However, I could not find a nixpkgs revision where `linuxPackages_latest.kernel` would be `/nix/store/62n7r206nh0a6vfpw76l8b04d5bjnl37-linux-6.11.4.drv`. Did you have any `kernelPatches` configured? If you post the revision and more of your config I could try to build that exact derivation.

**Comment by jayay** [comment]
@skeuchel I've been trying to rebuild my system a bunch of times now and these bugs were not reproducible but appeared all over the place (but in different files or packages).

I stumbled upon [this thread on the Debian mailing list](https://lists.debian.org/debian-riscv/2024/10/msg00007.html) discussing the bug and decided to abandon my current NixOS install and rebuild it with kernel 6.12, where the bug might be fixed.

Closing this, since it's not a NixOS problem
