### ISSUE TITLE
Can we tune "ghc -j" by passing appropriate +RTS flags?

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#35205]
## Issue description

`nixpkgs`' Haskell builder currently invokes GHC with `-j $CORES`. While at first glance this may seem reasonable, I would argue that this does more harm than good in most cases, especially on larger machines. The problem is that parallel Haskell programs generally scale poorly without at least some amount of RTS tuning.

Specifically, garbage collection synchronization tends to be very expensive with large core counts. GHC's runtime system recently grew the `+RTS -qn` [flag](https://downloads.haskell.org/~ghc/8.2.1/docs/html/users_guide/runtime_control.html#rts-flag--qn) for this reason. To make matters worse, the heap nursery is by default sized to fit in cache, which results in very frequent GC.

While it's hard to make any general statements regarding efficient runtime configurations, I suspect the following policy would be better than the status quo:

 * Set `+RTS -qn` to `max($CORES, 6)`; this caps the number of capabilities that will be used for parallel garbage collection, reducing the cost of GC synchronization.
 * If `$CORES > 1` then set `-+RTS -A 32M`; this increases the size of the nursery, trading some cache locality for fewer GC pauses.

Note, however, that this prescription is derived from intuition, not measurement.

**Comment by Profpatsch** [comment]
cc @peti

**Comment by peti** [comment]
> This prescription is derived from intuition, not measurement.

IMHO, this is exactly the kind of prescription that should be derived from *measurement*, not intuition. I don't really want to hard-code any magic constants into our generic builder unless there's non-trivial evidence that these settings improve the performance in *all* realistic setups, i.e. for hydra.nixos.org as well as for other people who are running builds on their private machines.

**Comment by domenkozar** [comment]
I plan to give this a try and get some measurements.

**Comment by domenkozar** [comment]
I hope with https://www.youtube.com/watch?v=7_ig6r2C-d4 we can give @bgamari a bit more credibility here to make the right call (that can be properly measured some day if someone wants).

@bgamari should we increase nursery with each core? Something like `+RTS -A (32 * $CORES)M`

**Comment by peti** [comment]
We don't need to give anyone credibility to make the right call because we can *measure* whether it's the right call or not. There is no need to appeal to authority here.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/53674/files

**Comment by peti** [comment]
I think https://github.com/NixOS/nixpkgs/issues/53665 addressed this issue for now.
