### ISSUE TITLE
gthumb 3.6.0: requires shared-mime-info to display pictures

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#35216]
## Issue description

gThumb 3.6.0 does not display any pictures in directories unless I also install shared_mime_info.
Missing dependency?

/cc maintainer: @mimadrid 

### Steps to reproduce

install gthumb  but not shared_mime_info. Browse to any directory containing pictures. No pictures shown. Works fine after installing shared_mime_info.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 18.03.git.1353ba4 (Impala)`

 - multi-user?: `yes`

 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127921.9b25b9347d9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mimadrid** [comment]
Sorry @xeji, too busy this week.
This bug is related to #12280 
I've already do a pull request, please check if that solve it

**Comment by xeji** [comment]
Thank you @mimadrid ,  #35456 works fine for me.
