### ISSUE TITLE
Update request: warp-terminal 0.2024.10.15.08.02.stable_03 → 0.2024.10.23.14.49.stable_00

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#352183]
- Package name: [warp-terminal](https://www.warp.dev/)
- Latest released version: [0.2024.10.23.14.49.stable_00](https://docs.warp.dev/getting-started/changelog#id-2024.10.24-v0.2024.10.23.14.49)

- Current version on the unstable channel: [0.2024.10.15.08.02.stable_03](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/wa/warp-terminal/package.nix#L103)
- Current version on the stable/release channel: [0.2024.10.08.08.02.stable_02](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/wa/warp-terminal/package.nix#L103)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@emilytrau
@imadnyc
@DontEatOreo
@johnrtitor

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by DontEatOreo** [comment]
Hey @ProxyVT warp-terminal is already updated to `0.2024.10.23.14.49.stable_00` on Oct 24, 2024, you can find the PR here: https://github.com/NixOS/nixpkgs/pull/350987

You can track when it's going to arrive to unstable over here: https://nixpk.gs/pr-tracker.html?pr=350987

**Comment by ProxyVT** [comment]
> Hey @ProxyVT warp-terminal is already updated to `0.2024.10.23.14.49.stable_00` on Oct 24, 2024, you can find the PR here: #350987
> 
> You can track when it's going to arrive to unstable over here: https://nixpk.gs/pr-tracker.html?pr=350987

Oh sorry, my bad. Should be more careful next time)
