### ISSUE TITLE
Installing Plasma Browser Integration does not add its native messaging hosts to the ./mozilla/native-messaging-hosts directory

### ISSUE THREAD

**Issue by fynn-kropp** [NixOS/nixpkgs#352248]
### Describe the bug
The wiki pages for [Firefox](https://wiki.nixos.org/wiki/Firefox#Tips) and [KDE Plasma](https://wiki.nixos.org/wiki/KDE) state that the steps required to install Firefox and enable the Plasma Browser Integration are to 
1. Install KDE Plasma (either 5 or 6, this did not make a difference in testing) via the steps listed [here](https://wiki.nixos.org/wiki/KDE#Installation).
2. Install Firefox by adding `programs.firefox.enable = true` to either the system config or Home Manager.
3. Add the Firefox extension to the browser [here](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/).

Following these steps, the plugin reports "Failed to connect to the native host", the same way that can be seen in #281710. The fixes in that issue, as well as similar ones, did not resolve the issue. Neither did the instruction on the Firefox wiki page to add `programs.firefox.nativeMessagingHosts.packages = [ pkgs.plasma5Packages.plasma-browser-integration ];` since this is already included by default with the Plasma installation and causes the build to fail. Instead, the required fix was to manually copy the `org.kde.plasma.browser_integration.json` file from the Plasma Browser Integration package in `nix/store/{plasma-browser-integration-6.0.5}/lib/mozilla/native-messaging-hosts` to `{user}/.mozilla/native-messaging-hosts`.

### Steps To Reproduce
1. Install KDE Plasma 5 or 6 per the wiki instructions.
2. Install Firefox per the wiki instructions.
3. Install the Firefox Plasma Browser Integration extension.
4. Get "Failed to connect to the native host" error since the `org.kde.plasma.browser_integration` application cannot be found (because there is no `org.kde.plasma.browser_integration.json` file in the relevant folder).
5. Copy the `org.kde.plasma.browser_integration.json` file from the package source into the `{user}/.mozilla/native-messaging-hosts` directory.
6. Plasma Browser Integration now works as expected.

### Expected behavior
It seems like `org.kde.plasma.browser_integration.json` should be moved to the above mentioned folder during the installation/build process, as appears to have been the case in the past.

### Additional context
The version of KDE Plasma (i.e. 5 or 6) and the way it was installed (system config or Home Manager) did not make a difference in testing. I have not tested any other Firefox extensions that require native hosts, so I can't say if there are more packages that are affected.

#### Qt / KDE Team (as listed [here](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix#L859))
@ilya-fedin 
@k900
@LunNova 
@mjm
@nickcao
@SuperSandro2000
@ttuegel

### Metadata

``` bash
[floppy@nixos:~/.mozilla/native-messaging-hosts]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.6043.64b80bfb316b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
What Firefox version are you using?

**Comment by SuperSandro2000** [comment]
> Install the Firefox Plasma Browser Integration extension.

This is done automatically.

**Comment by SuperSandro2000** [comment]
You linked the old wiki, the instructions there might be outdated.

Also we have zero integration with home-manager and don't provide any support regarding it's settings.

**Comment by fynn-kropp** [comment]
> What Firefox version are you using?
I'm using the most recent "default" Firefox version that you get by setting `programs.firefox.enable = true`. That should be Version 131.0.3. The Plasma Browser Integration package version is 6.0.5.


> You linked the old wiki, the instructions there might be outdated.
> 
> Also we have zero integration with home-manager and don't provide any support regarding it's settings.
You're totally right, that's my bad. I've updated the links to the new wiki. The instructions have stayed the same, though, so that should not have made a difference.
Regarding Home Manager, I'm not using it for this. As mentioned above, I've installed Firefox via the system config rather than via Home Manager. I just saw people mentioning it as a solution in the issue I linked earlier, so I wanted to pre-empt that by saying that I tested it and it didn't change anything.

**Comment by K900** [comment]
I believe this should be fixed on unstable, can you test that?

**Comment by fynn-kropp** [comment]
Give me a minute, will do.

**Comment by fynn-kropp** [comment]
Just to clarify, do you mean the nightly Firefox build or on NixOS Unstable?

**Comment by K900** [comment]
NixOS unstable.

**Comment by fynn-kropp** [comment]
Alright, sorry it took so long. I fully uninstalled Firefox, upgraded to NixOS unstable and reinstalled Firefox. As far as I can tell, it does indeed work. Although interestingly, there is still no `org.kde.plasma.browser_integration.json` in `~.mozilla/native-messaging-hosts`. Since it works anyway, I assume there's some symlinking going on that didn't work in the stable version? Either way, it's definitely fixed on the unstable branch.

**Comment by K900** [comment]
That is normal, the native messaging hosts are injected through the wrapper.

**Comment by fynn-kropp** [comment]
> That is normal, the native messaging hosts are injected through the wrapper.

Makes sense! Thank you for your help :)
Does that mean there is something that's not working correctly with the wrapper in the stable version then?

**Comment by K900** [comment]
The wrapper was refactored pretty heavily in unstable, which fixed many edge cases.

**Comment by fynn-kropp** [comment]
Fair enough. I guess manually copying the .json is at least a workaround for the stable branch until it's updated down the line. Unless there's a better solution I'm not aware of.

**Comment by SuperSandro2000** [comment]
While we are talking about wrappers, it is still broken when using firefox-bin. Can we merge https://github.com/NixOS/nixpkgs/pull/303562 to fix that?
