### ISSUE TITLE
Package request: suyu 

### ISSUE THREAD

**Issue by blueve-cloud** [NixOS/nixpkgs#352260]
**Project description**
Switch emulator for linux. 

**Metadata**

* homepage URL: https://suyu.dev
* source URL: https://git.suyu.dev/suyu/suyu
* license: mit, bsd, gpl2+ , ...
* platforms: linux 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
duplicate of #293811

**Comment by griffi-gh** [comment]
meanwhile you can use the [suyu nix flake](https://git.suyu.dev/suyu/nix-flake)

**Comment by nartsisss** [comment]
> duplicate of #293811
