### ISSUE TITLE
Package request: `synchrony`

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#352355]
**Project description**

Javascript cleaner & deobfuscator 

**Metadata**

* homepage URL: https://github.com/relative/synchrony
* source URL: https://github.com/relative/synchrony
* license: gpl3
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #352833
