### ISSUE TITLE
Feature Request: pulseaudio-dlna

### ISSUE THREAD

**Issue by poelzi** [NixOS/nixpkgs#35231]
## Issue description

Please provide nix package for pulseaudio-dlna.

https://github.com/masmu/pulseaudio-dlna

This would allow chromecast support on nixos.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2905.c1d9aff56e0 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2905.c1d9aff56e0"`
 - channels(poelzi): `"nixos-17.09-17.09.2964.3e349a2b98b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mogorman** [comment]
This looks cool, ill try to build it

**Comment by mogorman** [comment]
built it here https://github.com/NixOS/nixpkgs/pull/35245

I need to test it on my own box though

**Comment by mogorman** [comment]
@poelzi works on my box. this is a really cool piece of software thanks for the suggestion

**Comment by poelzi** [comment]
thank you very much for packaging it. very speedy :) :+1:
