### ISSUE TITLE
nvidia updates need backported due to CVE‑2024‑0126

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#352445]
CVE‑2024‑0126 was fixed in 550.127.05.

Reached unstable in https://github.com/NixOS/nixpkgs/pull/350529 but hasn't been fixed in 24.05 yet.

See https://nvidia.custhelp.com/app/answers/detail/a_id/5586 for list of patched versions.

**Comment by LunNova** [comment]
cc @kiskae @edwtjo

**Comment by Kiskae** [comment]
Updating the nvidia driver is a breaking change and I'm not sure it qualifies under the exceptions: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#changes-acceptable-for-releases

Perhaps @NixOS/security has guidance for this situation?

**Comment by LunNova** [comment]
Looks like there's a patched 535.xx version available too: `535.216.01`

**Comment by mweinelt** [comment]
No hardware support should be dropped, ideally. But as the 535 versions seems to have received a bump as well, are we good?

**Comment by Kiskae** [comment]
> No hardware support should be dropped, ideally. But as the 535 versions seems to have received a bump as well, are we good?

I was more referring that if you switch the nvidia driver on a running system, it breaks all the userspace nvidia libraries due to version mismatches. Updating drivers within the same major revision shouldn't drop hardware support.

Didn't realize we had the legacy 535 driver available, so that needs to be updated on master as well.

**Comment by mweinelt** [comment]
> it breaks all the userspace nvidia libraries due to version mismatches

So all that is needed is a reboot? I think security trumps the necessity of a reboot.

**Comment by Kiskae** [comment]
In that case the security problem can be patched by backporting https://github.com/NixOS/nixpkgs/pull/350529 and https://github.com/NixOS/nixpkgs/pull/352468. The 565 branch isn't available on the stable releases.
