### ISSUE TITLE
firefox: adb debugging in the browser is broken

### ISSUE THREAD

**Issue by pwall2222** [NixOS/nixpkgs#352417]
### Describe the bug
Firefox `about:debbuging` for debugging android devices using `adb` is broken, since Firefox tries to install an [xpi](https://ftp.mozilla.org/pub/labs/devtools/adb-extension/linux64/), that contains dynamically linked, modified version of adb. 

### Steps To Reproduce
1. Open Firefox (preferably from the command line, to see errors)
2. Go to `about:debbuging`
3. Click `Enable USB Devices`
4. (Optionally) Plug-in an Android device with `USB Debugging` enabled
5. Error printed on TTY

### Expected behavior
`adb` getting executed properly.

### Additional context
The `adb` "extension" get's extracted to `Local Directory` of a profile, `$HOME/.cache/mozilla/firefox/$PROFILE`
In `firefox-unwrapped` the side panel `USB enabled` never turns into a check, but in `firefox-bin` it does. Neither of them work though.

### Notify maintainers

@lovesegfault 
@mweinelt 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.6043.64b80bfb316b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
I don't think we can fix this short of making every instance of firefox run inside of an FHS container and I don't think it's reasonable to do that.

The firefox should not ship a dynamically linked binary; that's not in any way portable. I see that as a bug in their field.

You could run firefox inside of an fhsenv such as `steam-run{,-free}` yourself though or use nix-ld.

**Comment by pwall2222** [comment]
Could we have any sort of workaround like an option to symlink adb to the place where it would get downloaded or some shenanigans like that, or is this out of scope for nixpkgs?

**Comment by Atemu** [comment]
You could install `adb` into your global system path and then place a symlink to that in your profile I guess. Really though, firefox' ADB support should use the system ADB or provide a portable executable (i.e. statically linked).

I didn't even know Firefox had ADB support. What would you do with it?

**Comment by pwall2222** [comment]
![image](https://github.com/user-attachments/assets/e406b1c2-f9fe-4d59-a9d7-3bc8c9c3f736)
