### ISSUE TITLE
Build failure: qctools

### ISSUE THREAD

**Issue by lorinder** [NixOS/nixpkgs#352418]
### Steps To Reproduce

1. build qctools (e.g. `nix shell 'nixpkgs#qctools'` will do).

### Build log

Here is the [build log](https://gist.githubusercontent.com/lorinder/fd8dd2ff033507262ca4520aec912687/raw/cc66d22eebb985bd38f70c8299522c0d80de1ae3/log.txt).

### Additional context

Using nixos-unstable.  Looks like it doesn't build against newer `ffmpeg`.  So far the only errors I've seen are struct fields whose names have changed in libav*, though I haven't checked carefully.

### Notify maintainers

Maintainer appears to be @orivej.

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11pre698452.75e28c029ef2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/redacted/.nix-defexpr/channels/nixpkgs`
```

**Comment by FliegendeWurst** [comment]
PR: #352439
