### ISSUE TITLE
Update request: fractal 8 → 9

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#352513]
- Package name: Fractal
- Latest released version: 9

- Current version on the unstable channel: 8
- Current version on the stable/release channel: 7

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

um... Teams.gnome.maintainers

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by honnip** [comment]
@NixOS/gnome

there's also a build failure on nixos-unstable ([log](https://gist.github.com/honnip/5bbcfd0801d2484d85c992f0a91b83a4))

**Comment by Thatoo** [comment]
A merge request is on the way : https://github.com/NixOS/nixpkgs/pull/352922
