### ISSUE TITLE
Cross glibc retains references to static gcc

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#35251]
(and through it, the native stdenv)

**Comment by shlevy** [comment]
@Ericson2314 Any ideas here?

**Comment by dtzWill** [comment]
Can you give an example of what you mean? What does `nix why-depends` say?

**Comment by shlevy** [comment]
> $ nix why-depends /nix/store/dpm7mia5w73bazhdp208qxq8k5l4wwvy-glibc-2.27-riscv64-unknown-linux-gnu/ /nix/store/rq593rsgmzl8mbx4khjx0gla3ws6nyn3-gcc-7.3.0-riscv64-unknown-linux-gnu-stage-static/
> /nix/store/dpm7mia5w73bazhdp208qxq8k5l4wwvy-glibc-2.27-riscv64-unknown-linux-gnu
> ╚═══lib/Scrt1.o: …...................../nix/store/rq593rsgmzl8mbx4khjx0gla3ws6nyn3-gcc-7.3.0-riscv64-unknown-linux…
>     => /nix/store/rq593rsgmzl8mbx4khjx0gla3ws6nyn3-gcc-7.3.0-riscv64-unknown-linux-gnu-stage-static

**Comment by Ericson2314** [comment]
Ahhh. I bet this relates to how I had to nuke more refs in make-bootstrap-tools when I combined the native and cross versions.

I'm on my phone, so try `git log`ing that to see what I changed and then look there.

**Comment by shlevy** [comment]
@Ericson2314 Nothing obvious popping out, sorry

**Comment by dtzWill** [comment]
... why does Scrt1.o have path references/strings, anyway?

This may be specific to glibc 2.27 and/or gcc 7, which aren't used by other cross configurations... at least on master.

**Comment by dtzWill** [comment]
(this doesn't happen on, say, aarch64-musl, at least that's what I remember from poking at this last night... :))

**Comment by dtzWill** [comment]
Context for question on Scrt1.o: crt files are small (tiny! they're linked into all the things), usually defining a symbol or two .... for example on musl Scrt1 is a differently built crt1 with source like this:
https://git.musl-libc.org/cgit/musl/tree/crt/crt1.c

Hardly something you'd expect to retain the path of the compiler it was built with.  I wonder if that happens with glib 2.27 on non cross or other archs?

**Comment by shlevy** [comment]
Doesn't appear to happen on non-cross based on the `glibc-2.27` branch

**Comment by Ericson2314** [comment]
debug info, I'd think. Cross stuff has less stripping sometimes.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/36948 probably also fixes this?

**Comment by goertzenator** [comment]
I ran into this in #53424 and after some experimentation landed here.

I commented out the glibc [`dontStrip = true`](https://github.com/NixOS/nixpkgs/blob/staging/pkgs/development/libraries/glibc/common.nix#L212) line and all the extra dependencies fell away.  Closure size went from 300M to 28M.  So yes, it is debug info.

**Comment by lopsided98** [comment]
Do we actually need to disable stripping anymore? Tracing back through git blame and the history of the glibc package, it seems like this might have initially been added by https://github.com/NixOS/nixpkgs/commit/c6b526495bc37e63b43c3fc17705cefac81fa904 in 2009 and was carried through all the updates since then. It wouldn't surprise me if it was no longer necessary, but someone should check if anything breaks.

**Comment by goertzenator** [comment]
There is a [reference to cross-arm breakage](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/glibc/default.nix#L82-L89), but I have no idea if that is still valid or not.

**Comment by lopsided98** [comment]
This was fixed by #59787.
