### ISSUE TITLE
Package request: Sticky Notes

### ISSUE THREAD

**Issue by 4r7if3x** [NixOS/nixpkgs#352690]
**Project description**

Sticky Notes is a simple sticky notes app for GNOME. It allows you to create notes and format them.

**Metadata**

* homepage URL: https://flathub.org/apps/com.vixalien.sticky
* source URL: https://github.com/vixalien/sticky
* license: MIT
* platforms: Linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/blob/2315372573dbb8b26543ecf28a6b8e5c0222a349/pkgs/by-name/st/sticky-notes/package.nix#L23

**Comment by 4r7if3x** [comment]
okay guys, my bad! I had to look into the unstable packages as well...
