### ISSUE TITLE
Building an oci container image with babashka results in > 600 megabyte image

### ISSUE THREAD

**Issue by Ramblurr** [NixOS/nixpkgs#352635]
### Describe the bug

Building an OCI container image that includes babashka results in an unexpectedly large image size of over  600MB (the .tar.gz). 

The image contains many unnecessary dependencies like openjdk 21, GTK3, systemd, cups, and ICU that aren't required for babashka's core functionality.

### Steps To Reproduce
1. Create a minimal nix file with this content:
```nix
    { pkgs ? import <nixpkgs> { } }:
    pkgs.dockerTools.buildLayeredImage {
      name = "babashka-test";
      tag = "latest";
      fromImage = null;
      contents = [
        pkgs.dockerTools.usrBinEnv
        pkgs.dockerTools.binSh
        pkgs.babashka
      ];
    }
```

2. Build the image: `nix-build`
3. `ls -alh $(readlink result)` -> the resulting tar.gz iz over 600 M
4. Load and analyze with dive: `sudo docker load < result; sudo dive babashka-test:latest`

### Expected behavior
The container image should only include babashka and its essential runtime dependencies, resulting in a much smaller image size (likely <100MB).

I can download and extract babashka from https://github.com/babashka/babashka/releases (the `babashka-1.12.194-linux-amd64-static.tar.gz`) and get a self contained binary that is 65M.

### Screenshots
Using dive, the final layer shows many unnecessary dependencies:

<details>
<summary>🖼️ Screenshot: Largest packages from Just the final layer (click)</summary>

![image](https://github.com/user-attachments/assets/bd28eba4-f070-4904-9231-8b69edbe1ed4)

</details>

<details>
<summary>🖼️ Screenshot: The largest packages from all the layers (click)</summary>

![image](https://github.com/user-attachments/assets/70ee5f86-7dc3-45cf-84f2-b1efae0616e7)

</details>

### Notify maintainers

@bandresen
@bhougland
@DerGuteMoritz
@jlesquembre
@thiagokokada

**Comment by jlesquembre** [comment]
could you try with `babashka-unwrapped` instead on `babashka`?

**Comment by Ramblurr** [comment]
Wow. `babashka-unwrapped` produces a tarball of 46M, compared to `babashka` which produces 624M.

What is the difference? I thought the wrapped version just provided readline functionality?

**Comment by jlesquembre** [comment]
> https://www.bundesschatz.at/haeufige-fragen

The JDK. Babashka requires a java installation to resolve and download dependencies

**Comment by Ramblurr** [comment]
> > https://www.bundesschatz.at/haeufige-fragen
> 

Hah, a fellow Austrian resident! I  was looking into bundesschatz myself the other day... copy jpaste error?

> The JDK. Babashka requires a java installation to resolve and download dependencies

Hm ok, that makes sense, I was wondering why the JDK was being dragged along.

**Comment by jlesquembre** [comment]
Yep, copy/paste error, too many things in parallel
