### ISSUE TITLE
ncurses: file removed from server

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#35264]
## Issue description

The file `ncurses-6.0-20171125.tgz` has been removed from `https://invisible-mirror.net/archives/ncurses/current/`. 

- Nixpkgs master

cc @dtzWill

**Comment by FRidh** [comment]
@dezgeg I saw you modified `ncurses` on staging (3d24ae9b4426bb8adfcb08de57be21fdf0a377f8). Is it possible to use the GNU mirror instead?

**Comment by dtzWill** [comment]
I don't think we can use gnu mirrors for this unless it's an actual release (not a snapshot). See what's available [here](ftp://ftp.gnu.org/gnu/ncurses/) to see what I mean.

(cc #34477)

**Comment by FRidh** [comment]
There is also a 6.0 on the GNU mirror. If 6.1 is problematic we can maybe use that. In any case, we need to make a change because the current one has been removed. While this poses no issue for users with `/nix/store`, it does for people with custom store location.

**Comment by dezgeg** [comment]
I found Alpine mirroring the version we have, so it should be temporarily fixed in ce8bd325e671712deea2e99f7c2a5232e7272ea7. But, hopefully the switch to 6.1 can be made soon so that won't be needed anymore.

**Comment by FRidh** [comment]
Thanks!

**Comment by FRidh** [comment]
Just encountered the issue again. The Alpine host seems to be down now as well.

I saw there is a mirror on GitHub, and found a commit corresponding to this version
https://github.com/mirror/ncurses/commit/8d3ea9021573747ecd129228ba7782a03243f62c

The tarball of the following link however has a different hash
https://github.com/mirror/ncurses/archive/8d3ea9021573747ecd129228ba7782a03243f62c.tar.gz

Even so, if this issue persists I think we should use this mirror instead and take the mass-rebuild for granted.

**Comment by FRidh** [comment]
The Alpine mirror is up again.

**Comment by dezgeg** [comment]
@edolstra shouldn't the tarball mirroring script handle these cases? Is it stuck somewhere perhaps?

**Comment by FRidh** [comment]
Isn't it ran manually? (https://github.com/NixOS/nixpkgs/issues/11782)
