### ISSUE TITLE
Crash when accessing settings in the APK

### ISSUE THREAD

**Issue by yousafsahu11** [NixOS/nixpkgs#352673]
I encountered a bug in the APK that causes the app to crash when I attempt to access the settings menu.

To reproduce the issue, I[ downloaded the APK](https://wasuppgb.org/) file from the provided link and installed it on my Pixel 4 running Android 12. After launching the app, I navigated to the main menu and tapped on the settings option. Upon doing so, the app crashes immediately without any error message.

I expected the settings menu to open smoothly, but instead, the app closes unexpectedly. This issue has been consistent, occurring every time I try to access the settings.

The app version is 1.0.0, and I have attached a screenshot of the home screen before the crash for your reference. If there's any additional information or logs you need, please let me know.

**Comment by Atemu** [comment]
Wrong issue tracker mate.
