### ISSUE TITLE
Gwenview/KImageFormats: HEIF unsupported

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#352619]
### Describe the bug
Even though KImageFormats supports HEIC/HEIF images, NixOS build of Gwenview won't open them

### Steps To Reproduce
1. Open any HEIC/HEIF image in Gwenview

### Expected behavior
Gwenview should support opening HEIC/HEIF files but fails with an error.

### Screenshots
![image](https://github.com/user-attachments/assets/3c04c776-f8bc-4251-b798-7153b48a1fb6)

### Additional context
- I tried installing `kdePackages.kimageformats` as system package but that didn't help.
- Thumbnails in Dolphin *do* work
- Opening the image in Gwenview *doesn't*

### Notify maintainers

@NixOS/qt-kde @getchoo @K900

### Metadata

---

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20240920_ca3fc169`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`
 
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Fixed with the latest staging merge.

**Comment by griffi-gh** [comment]
Yeah, already noticed that it works with package from master branch...
![image](https://github.com/user-attachments/assets/3eb75d27-27aa-4131-93d3-cd7d1c298195)
It creates this warning every time though? kinda weird

**Comment by K900** [comment]
This is fine.
