### ISSUE TITLE
Package request: brave for darwin

### ISSUE THREAD

**Issue by fbettag** [NixOS/nixpkgs#352692]
Brave is already in nixpkgs, but i've spent the past 12 hours trying to get brave to package for darwin aarch64.

I'd pretty much appreciate if someone could package it for darwin as i'm not able enough (apparently).

[here](https://github.com/fbettag/nixpkgs/commit/84760e3e928acc08d28fc06c7f0ab0c864d5cfcc) is my attempt. at least the fetching of checksums worked

**Comment by fbettag** [comment]
thanks @matteo-pacini

**Comment by matteo-pacini** [comment]
@fbettag happy to help!

I'm keeping this open until the PR is merged - so we don't lose track of it
