### ISSUE TITLE
nixos/home-assistant: I can't parse a string in “ui_lovelace.yaml” with an exclamation mark in it.

### ISSUE THREAD

**Issue by specter42** [NixOS/nixpkgs#352651]
### Describe the bug
I can't parse a string in “ui_lovelace.yaml” with an exclamation mark. If I use an exclamation mark, the whole string is put in apostrophe.
### Steps To Reproduce

services.home-assistant.lovelaceConfig = {    
  button_card_templates = "!include_dir_merge_named \"custom_components/ui_lovelace_minimalist/lovelace/\"";
 ...
  };

gives

  button_card_templates: '!include_dir_merge_named "custom_components/ui_lovelace_minimalist/lovelace/"'

### Expected behavior
  button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/lovelace/"

### Additional context
I guess the problem is here: https://github.com/NixOS/nixpkgs/blob/cd3e8833d70618c4eea8df06f95b364b016d4950/nixos/modules/services/home-automation/home-assistant.nix#L17C5-L17C69

### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.20240927.f651414`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/2vmkhm30kdnics1bnj9zgblh9yr4cpyw-source`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
cc @mweinelt

**Comment by mweinelt** [comment]
> I guess the problem is here: [cd3e883/nixos/modules/services/home-automation/home-assistant.nix#L17C5-L17C69](https://github.com/NixOS/nixpkgs/blob/cd3e8833d70618c4eea8df06f95b364b016d4950/nixos/modules/services/home-automation/home-assistant.nix#L17C5-L17C69)

No, that is the solution. The problem is that we only apply that to the homeassistant.yaml.

**Comment by specter42** [comment]
What a great community! Thank you very much!

**Comment by Atemu** [comment]
@specter42 could you test https://github.com/NixOS/nixpkgs/pull/352746 and report whether it works for you?

**Comment by specter42** [comment]
Will test it tonight and report

**Comment by specter42** [comment]
OK, I feel a bit stupid, but I'm not sure if I really installed the pr. Currently the fix is not working for me. 
services.home-assistant.lovelaceConfig = {
...
button_card_templates = “!include_dir_merge_named \”custom_components/ui_lovelace_minimalist/lovelace/\“”;
...
};
is still entered in the ui_lovelace.yaml:
button_card_templates: '!include_dir_merge_named “custom_components/ui_lovelace_minimalist/lovelace/”'
I'm pretty new to nixos and the likelihood that the error is on my end I think is pretty high. So, I use flakes and install the pr via overlay.
flake.nix:
home-assistant-pr.url = “github:NixOS/nixpkgs/pull/352746/head”;
overlay:
home-assistant = final: _prev: {
home-assistant-pr = import inputs.home-assistant-pr { inherit (final) system; };
};
nixpkgs = {

overlays = [

...
outputs.overlays.home-assistant
...
];
};

homeassistant.nix:
services.home-assistant = {
...    
    package = pkgs.home-assistant-pr.home-assistant;
...
};

**Comment by mweinelt** [comment]
Copy [this file](https://raw.githubusercontent.com/NixOS/nixpkgs/0924dfae805a4f18646a72b20842cedfe472c856/nixos/modules/services/home-automation/home-assistant.nix) into your tree. It is the home-assistant module, so call it e.g. `module.nix`.

Then configure

```nix
{
  disabledModules = [ "services/home-automation/home-assistant.nix" ];

  imports = [ ./module.nix ];

 services.home-assistant = {
   ...
  };
```

**Comment by specter42** [comment]
Thank you for your help. The string is now correctly written to ui_lovelace.yaml. Unfortunately, what no longer works is building my custom components with buildHomeAssistantComponent. 

error: A definition for option `services.home-assistant.customComponents' is not of type `list of package that is a Home Assistant component'. Definition values:
- In `/nix/store/d6cm94id81yw1n4zg91x7mk6k89jway2-source/nixos/_mixins/services/homeassistant.nix':
{
ui_lovelace_minimalist = <derivation python3.12-UI-Lovelace-Minimalist-ui_lovelace_minimalist-1.3.10>;
}


Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by mweinelt** [comment]
The `buildHomeAsssistantComponent` function on unstable sets `passthru.isHomeAssistantComponent = true`.
