### ISSUE TITLE
Update request: sway 1.9 → 1.10

### ISSUE THREAD

**Issue by waduhek** [NixOS/nixpkgs#352618]
- Package name: sway
- Latest released version: 1.10

- Current version on the unstable channel: 1.9
- Current version on the stable/release channel: 1.9

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@primeos @Synthetica9

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ryand56** [comment]
Updated in #351752

**Comment by waduhek** [comment]
My apologies, guess I didn't check the PRs well enough. Closing this.
