### ISSUE TITLE
haskell-modules/lib: rename doJailbreak

### ISSUE THREAD

**Issue by chreekat** [NixOS/nixpkgs#35278]
I am slowly learning what "jail" is being "broken" by brute rote, but perhaps a better description could ease this for people.

```
ignoreDependencyBounds
dontIgnoreDependencyBounds
```

**Comment by chreekat** [comment]
Yup, still important. Only nixpkgs uses the word 'jailbreak' to mean ignoring Cabal version bounds. Cabal itself uses `--allow-newer` and `--allow-older`.

I also don't see "jailbreak" in the nixpkgs manual, so we should document it (or whatever better name is used).

**Comment by cdepillabout** [comment]
I'll close this in favor of https://github.com/NixOS/nixpkgs/pull/126674.

**Comment by chreekat** [comment]
I still think it's valuable to get rid of the word "jailbreak", but I agree having it documented is a step forward.

**Comment by sternenseemann** [comment]
The problem is more or less that renaming is not really an option, since we have committed ourselves to excellent backwards compatibility in `haskell.lib`. Adding another name for something may just increase the confusion.

**Comment by chreekat** [comment]
That sounds reasonable :)
