### ISSUE TITLE
NixOS 24.11 - Zero Hydra Failures

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#352882]
Hello, this is your NixOS 24.11 ("*Vicuna*") release managers, [Tristan Ross](https://github.com/RossComputerGuy) & [Weijia Wang](https://github.com/wegank).

Today kicks off our CI failure mitigation party known as Zero Hydra Failures (ZHF). The goal is to reduce the amount of Hydra failures as much as possible before the release on November 22nd. I hope to see many builds fixed, especially relating to aarch64-linux and both Darwin systems (especially after the rework).

There's two important dates which are related:
- 2024-11-14: Branch off
- 2024-11-22: 24.11 release

Full timeline is at: https://github.com/NixOS/nixpkgs/issues/339153

## The mission

Every time we plan to do a release, we take time to stabilize the master branch and later on the release branch. Our goal here is to reduce the number of failing jobs on the `nixpkgs:trunk` `nixos:trunk-combined` jobsets as much as possible before branch-off. We call this the "Zero Hydra Failure" campaign.

Besides aiming for zero failed jobs, we also strive to again provide all packages that were available in the previous release.

Changes need to always target the `master` branch. Take note that the branch-off will occur on 2024-11-14, after which ZHF changes will need to be tagged with the `backport: release-24.11` label to land in the stable release.

## Jobsets

The relevant jobsets to check for failing jobs are:

- [nixos:trunk-combined](https://hydra.nixos.org/jobset/nixos/trunk-combined) (Linux packages & NixOS tests)
- [nixos:trunk](https://hydra.nixos.org/jobset/nixpkgs/trunk) (Linux & Darwin packages)

#### Eval reports

Evaluation reports provide a structural overview of the most impactful failing builds. They originated at https://github.com/nix-community/nix-review-tools and were automated over at https://github.com/malob/nix-review-tools-reports.

1. Navigate to https://malob.github.io/nix-review-tools-reports/
2. Open the relevant jobset
3. Browse the latest reports for build failures
![](https://md.darmstadt.ccc.de/uploads/upload_7bab0fdf57d45370e48ba62b43dfbc13.png)
4. Follow the links to the build failure on hydra

#### ZERO Hydra Failures

The platform automatically crawls Hydra and lists packages by maintainer and lists the most important dependencies (failing packages with the most dependants). It also graphs the general trend per platform.

1. Navigate to https://zh.fail

For the record, we started ZHF here:

```
Latest Linux evaluation (completely built):	1809719 on 2024-11-01 08:02:16 (UTC)
Latest Darwin evaluation (completely built):	1809682on 2024-10-31 05:59:10 (UTC)
Failing builds on aarch64-darwin:	1541
Failing builds on aarch64-linux:	1554
Failing builds on x86_64-darwin:	1701
Failing builds on x86_64-linux:	2058
Total failed builds	6854
```

#### Check on packages you maintain

1. Clone nixpkgs and checkout the `master` branch
2. Run 
   ```
   nix-build maintainers/scripts/build.nix --argstr maintainer <name>
   ```
#### Hydra
Hydra is nixpkgs CI platform, where all active branches are built and pushed into the cache, after which channels can originate from its build results.

1. Open the [nixpkgs:trunk](https://hydra.nixos.org/jobset/nixpkgs/trunk) jobset
2. Select the latest evaluation
![](https://md.darmstadt.ccc.de/uploads/upload_968849d97f3c7aea84d173d36f360eac.png)
4. Directly failing jobs are marked with a red cross, while transitively failing ones are greyed out. 
![](https://md.darmstadt.ccc.de/uploads/upload_fb4efdad788e6f904fee43b6ebb40701.png)
5. Use the search form to scope the package list to things relevant to you and that you can test.
![](https://md.darmstadt.ccc.de/uploads/upload_885e122fe1c5ee6dda9b8b3eeffae267.png)

### Submit fixes

6. Search through PRs to make sure noone provided a fix yet. If there is one, please take the time and help review the change.

7. If there is no open PR, troubleshoot why it's failing and fix it.

8. Pull Request the fix against the `master` branch and wait potential review & change requests
    - If your PR causes more than ~500 rebuilds, it is generally preferred to target `staging` to avoid compute churn for users on `master`.

### Backporting

**After 2024-11-22**

9. Apply the relevant backport label to land the fix in the release branch
    - Changes to `master` get backported into `release-24.11`
    - Changes to `staging` get backported into `staging-24.11`

10. If the backport action fails, follow the [manual backporting steps](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes). Make sure to use `git cherry-pick -x <rev>` on all commits intended for backport.
    - @jonringer created a [video covering the backport process](https://www.youtube.com/watch?v=4Zb3GpIc6vk).

---

**Always link back** to this issue by mentioning the issue number in the description of your pull request:
```
ZHF: #352882
```

If your PR receives no reviews or does not get merged, feel free to
- add the `0.kind: ZHF Fixes` label, so people can better browse these fixes
- request or mention @NixOS/nixos-release-managers on the PR

## Broken packages
Everything we cannot fix in time will need to be marked broken on the respective platforms, so that Hydra will not retry builds over and over, thereby wasting compute resources.

Set `meta.broken` and add a reference and/or explanation, like this:

```nix
meta = {
  # ref to issue/explanation
  broken = stdenv.isDarwin; # only broken on darwin
  # broken = true; # broken on all platforms.
};
```

# Orphaned Packages

You can read about failing packages without a maintainer here: https://zh.fail/failed/by-maintainer/_.html (orphaned packages).

If you're new to NixOS, adopting an orphaned package is a great way to get involved and contribute to the community. By doing so, you'll not only help improve the overall quality of the NixOS ecosystem, but you'll also gain valuable experience working with Nix, the language and tool that powers the package management system.

By adopting an orphaned package, you'll be taking on a responsibility that can be both challenging and rewarding. You'll need to understand the package's code and dependencies, make sure it builds and works correctly, and respond to any issues or pull requests that come up. This process can be a great learning experience, as you'll be exposed to a wide variety of programming languages and libraries.

Moreover, by adopting an orphaned package, you'll be making a tangible impact on the NixOS community. Your contributions will be greatly appreciated by users who depend on that package, and you'll be helping to ensure that NixOS releases are as stable and up-to-date as possible.

# Closing

This is a great way to help NixOS, and it is a great time for new contributors to start their nixpkgs adventure. 🥳

As with the [feature freeze](https://github.com/NixOS/nixpkgs/issues/344920), please keep the discussion here to a minimum so we don't ping all maintainers (although relevant comments can of course be added here if they are directly ZHF-related) and ping one of the release managers (@RossComputerGuy, @wegank) in the respective issues.

**Comment by RossComputerGuy** [comment]
`release-24.11` has been branched off so remember to also add the `backport release-24.11` to your Pull Requests :tada:

**Comment by paparodeo** [comment]
https://malob.github.io/nix-review-tools-reports/ could use an entry for the 24.11 branch

**Comment by RossComputerGuy** [comment]
We released! https://discourse.nixos.org/t/nixos-24-11-released/56811
