### ISSUE TITLE
Build failure: stalwart-mail.webadmin

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#352874]
### Steps To Reproduce

1. `nix build .#stalwart-mail.webadmin`

### Build log

```
error: builder for '/nix/store/snfda1ymaya1m3lygfd602iqlwnm7njf-webadmin-0.1.17.drv' failed with exit code 1;
       last 10 log lines:
       > error from build pipeline
       >
       > Caused by:
       >     0: error from asset pipeline
       >     1: couldn't find application wasm-bindgen
       > Error: error from build pipeline
       >
       > Caused by:
       >     0: error from asset pipeline
       >     1: couldn't find application wasm-bindgen
```

__Full log__: https://gist.github.com/pacien/c1c93a36f6af51496ae75e53217b9ed7

### Additional context

/

### Notify maintainers

@onny @Shawn8901 

### Metadata

Failing on master at 'github:NixOS/nixpkgs/807e9154dcb16384b1b765ebe9cd2bba2ac287fd'.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xanderio** [comment]
Currently bisecting this

**Comment by xanderio** [comment]
The cause is the version bump of wasm-bindgen-cli in #349729.

**Comment by xanderio** [comment]
@onny why are we using `trunk-ng` and not `trunk`? This seems to be a fork of `trunk` but at least in nixpkgs it hasn't been update.

**Comment by Shawn8901** [comment]
Fyi: Not sure why I am pinged/listed here as maintener, I am not listed as maintener neither for stalwart, the web admin nor the module, tho I am a stalwart user.

**Comment by onny** [comment]
> @onny why are we using `trunk-ng` and not `trunk`? This seems to be a fork of `trunk` but at least in nixpkgs it hasn't been update.

back then i had more success with `trunk-ng`, but not sure if this is still the case. we might want to switch back to `trunk` if it is the tooling used upstream

**Comment by xanderio** [comment]
Switching this `trunk` gives us a better error message :D

```
couldn't find the required version (0.2.93) of the application wasm-bindgen (found: 0.2.95), unable to download in offline mode
```

**Comment by orzklv** [comment]
+1

```
building the system configuration...
error: builder for '/nix/store/3p6brxrhjc23praqq959km0wvmj2bh0q-webadmin-0.1.17.drv' failed with exit code 1;
       last 10 log lines:
       > error from build pipeline
       >
       > Caused by:
       >     0: error from asset pipeline
       >     1: couldn't find application wasm-bindgen
       > Error: error from build pipeline
       >
       > Caused by:
       >     0: error from asset pipeline
       >     1: couldn't find application wasm-bindgen
       For full logs, run 'nix log /nix/store/3p6brxrhjc23praqq959km0wvmj2bh0q-webadmin-0.1.17.drv'.
error: 1 dependencies of derivation '/nix/store/3plag6xpz00xqd6yg88zpyhpdd4md4dl-stalwart-mail.toml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qldpljhcs6ixbkz9hb8ggp6091vj56j4-unit-stalwart-mail.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fz0jkkv7s4naka94bdirfy8hhpyf4nx5-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2py6jl87z6a6nqmzvdz9caqx0kv6bxk7-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b90fipwdfhvd3q5rf51w15cvs1xp877l-nixos-system-Kolyma-1-24.05.20241030.080166c.drv' failed to build
```

**Comment by xanderio** [comment]
Ok so the problem is that `wasm-bindgen` crate, which the application uses and the `wasm-bindgen-cli` are required to be the exact same version. I'll create a PR to pin this for the webadmin derivation and will switch to trunk

**Comment by xanderio** [comment]
Use this as a workaround until the PR this the relevant branches.

```nix
    nixpkgs.config.packageOverrides = pkgs: {
      stalwart-mail = pkgs.stalwart-mail.overrideAttrs (old: {
        passthru.webadmin = pkgs.stalwart-mail.webadmin.override {
          wasm-bindgen-cli = pkgs.wasm-bindgen-cli.override {
            version = "0.2.93";
            hash = "sha256-DDdu5mM3gneraM85pAepBXWn3TMofarVR4NbjMdz3r0=";
            cargoHash = "sha256-birrg+XABBHHKJxfTKAMSlmTVYLmnmqMDfRnmG6g/YQ=";
          };
        };
      });
    };
```

**Comment by orzklv** [comment]
@xanderio I'm very sorry for disturbing you, I'm still experiencing the issue. If you have some spare time, can you check my configuration please?
https://github.com/kolyma-labs/instances/blob/main/nixos/kolyma-1/services/mail.nix

**Comment by xanderio** [comment]
@orzklv You need to override the correct package. https://github.com/kolyma-labs/instances/blob/main/nixos/kolyma-1/services/mail.nix#L39

**Comment by orzklv** [comment]
@xanderio Thank you very much!
