### ISSUE TITLE
Spotify app deauthorizes me every reboot

### ISSUE THREAD

**Issue by nukdokplex** [NixOS/nixpkgs#352888]
### Describe the bug
About 3-4 weeks i am facing issue with Spotify application (pkgs.spotify). App just asks me to sign in every time i boot and that is very annoying. BUT if i close spotify and open it again without any reboots it will not ask to sign in and just bring me to my music. 
### Steps To Reproduce
1. Install NixOS with home-manager as module and add to home.packages (or even to system environment.packages it doesn't matter) spotify package
2. Open spotify and sign in using browser
5. Close spotify gracefully and reboot
6. Login to your account, open spotify and it asks to sign in again... **bruh**

### Expected behavior
Spotify not asks me to sign in every reboot

### Screenshots
![image](https://github.com/user-attachments/assets/3f0f38b5-52d5-4f39-9c48-6f3ddaea73c6)

### Additional context
I have already tried:
1. Removed spicetify (i use this one: [github:Gerg-L/spicetify-nix](https://github.com/Gerg-L/spicetify-nix))
2. Many times i removed those directories: ~/.cache/spotify and ~/.config/spotify. Signed in again then
3. Successfully overrided attributes of pkgs.spotify to bump version. (Tried latest stable and edge at the moment), nothing changed
 
### Notify maintainers
@ftrvxmtrx @sheenobu @timokau @Ma27 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
Do you use something like impermanence which might remove relevant state after a reboot?

**Comment by nukdokplex** [comment]
@Ma27 I have several symlinks in my home configuration:
```nix
xdg.userDirs = {
    enable = true;
    desktop = "${config.home.homeDirectory}/desktop";
    documents = "${config.home.homeDirectory}/documents";
    download = "${config.home.homeDirectory}/download";
    music = "${config.home.homeDirectory}/music";
    pictures = "${config.home.homeDirectory}/pictures";
    publicShare = "${config.home.homeDirectory}/public_share";
    templates = "${config.home.homeDirectory}/templates";
    videos = "${config.home.homeDirectory}/videos";
  };

home.file = lib.mkIf (osConfig.networking.hostName == "sleipnir") {
    "dotssh-dir-symlink" = {
      target = ".ssh";
      source = config.lib.file.mkOutOfStoreSymlink "/data/passport/ssh";
    };
    "music-dir-symlink" = {
      target = "music";
      source = config.lib.file.mkOutOfStoreSymlink "/data/archive/music";
    };
    "pictures-dir-symlink" = {
      target = "pictures";
      source = config.lib.file.mkOutOfStoreSymlink "/data/archive/pictures";
    };
    "videos-dir-symlink" = {
      target = "videos";
      source = config.lib.file.mkOutOfStoreSymlink "/data/archive/videos";
    };
    "documents-dir-symlink" = {
      target = "documents";
      source = config.lib.file.mkOutOfStoreSymlink "/data/archive/documents";
    };
  };
```
but it's only on one of my hosts, this problem appearing on all of my hosts

**Comment by nukdokplex** [comment]
@Ma27 i am sorry, now i figured out that you are talking about [github:nix-community/impermanence](https://github.com/nix-community/impermanence). no, i don't use this at all

**Comment by Atemu** [comment]
Are you able to reproduce it inside of a vm (`nixos-rebuild build-vm`)?

**Comment by nukdokplex** [comment]
@Atemu yes, that issue reproduces on slightly modified version of nixos configuration (just to make vm start properly).
[Original configuration](https://github.com/nukdokplex/daac/blob/ada14593bc0f6f89f33cff7812909f3aaf2a0697/instances/hosts/sleipnir/default.nix), [VM configuration](https://github.com/nukdokplex/daac/blob/ada14593bc0f6f89f33cff7812909f3aaf2a0697/instances/hosts/sleipnir-vm/default.nix)

**Comment by nukdokplex** [comment]
Something has been changed (it is not spotify update) between 18536bf04cd71abd345f9579158841376fdd0c5a and 4aa36568d413aca0ea84a1684d2d46f55dbabad7 nixpkgs and spotify now does not loses my authorization between boots. Or maybe it was home-manager update? You can check my [flake.lock update commit](https://github.com/nukdokplex/daac/commit/30a85372bbc94b195e5b069ffbb88384c7813592). If you have any idea what's changed and worked out - you are welcome!
