### ISSUE TITLE
Build failure: GitKraken 10.4.1 hash mismatch failure on darwin

### ISSUE THREAD

**Issue by kevinkrouse** [NixOS/nixpkgs#352944]
### Steps To Reproduce

1. build GitKraken 10.4.1 on darwin

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/n1rr6vmij4bg52zr7n4mym26vsmsz7q6-source.drv':
         specified: sha256-21VwDFw2dyySoc4NC/RR3k/VtksqaZ5vkdx0z5MKqLc=
            got:    sha256-fPvEItavxFwUbk3WsTBvzRMu7fjnm5HxybEueHn//Q4=
error: 1 dependencies of derivation '/nix/store/l7dp2442ssrpf8yj3sb54b3layxmi54a-gitkraken-10.4.1.drv' failed to build
```

### Additional context
I believe this was caused by the change in #350785.

### Notify maintainers
cc @nicolas-goudry 

### Metadata
```sh
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.8`
 - channels(kevink): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/lryfc8mhk1czqsa421di2y5nzz5c3b8m-source`
```
 
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nicolas-goudry** [comment]
Oops, I'm really sorry about that.

Will take a look at it in a bit!

Thanks for reporting.

**Comment by nicolas-goudry** [comment]
Don’t know how I messed up the hash part, other hashes are correct.

Again, sorry about that. PR opened: #352981
