### ISSUE TITLE
Build failure: nixosTests.gitlab

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#352963]
`nixosTests.gitlab` is blocking the `nixos-unstable` channel since the last staging-next merge https://github.com/NixOS/nixpkgs/pull/348827

Log e.g.: https://hydra.nixos.org/build/276947171

At a glance, maybe changes in `pkgs/development/interpreters/ruby` `pkgs/development/ruby-modules`

### Notify maintainers

@globin @yayayayaka (though already notified [in chat](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$Z6BlZ9eFbUrMPvt3_rXdHzgpoveDE8HJFXFwfz1UMzM?via=nixos.org&via=matrix.org&via=nixos.dev))

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by itepastra** [comment]
I've started bisecting for the commit that broke the test, but the large rebuilds make it quite slow

```
git bisect start
# status: waiting for both good and bad commits
# bad: [f00f17fe6a4d5d94ac704e922426e476c3b6c29e] signal-desktop: 7.29.0 -> 7.31.0; signal-desktop-beta: 7.30.0-beta.2-> 7.32.0-beta.1 (#352218)
git bisect bad f00f17fe6a4d5d94ac704e922426e476c3b6c29e
# status: waiting for good commit(s), bad commit known
# skip: [807e9154dcb16384b1b765ebe9cd2bba2ac287fd] icu76: 76.1rc -> 76.1 (#351275)
git bisect skip 807e9154dcb16384b1b765ebe9cd2bba2ac287fd
# status: waiting for good commit(s), bad commit known
# good: [807e9154dcb16384b1b765ebe9cd2bba2ac287fd] icu76: 76.1rc -> 76.1 (#351275)
git bisect good 807e9154dcb16384b1b765ebe9cd2bba2ac287fd
# bad: [0c016abe52679d4adabf4bd4779e20fb5bfb90c1] python3Packages.python-dbusmock: 0.32.1 -> 0.32.2
git bisect bad 0c016abe52679d4adabf4bd4779e20fb5bfb90c1
# bad: [1fbde8aa6d02bbbb5a91e477e731fc1349a33938] python3Packages.empy: 4.1 -> 4.2
git bisect bad 1fbde8aa6d02bbbb5a91e477e731fc1349a33938
```

**Comment by vcunat** [comment]
We did it again by merging with @anthonyroussel's 0855ae2c46c
