### ISSUE TITLE
`pip-on-top` GNOME extension doesn't work

### ISSUE THREAD

**Issue by 4r7if3x** [NixOS/nixpkgs#352920]
### Describe the bug

The GNOME extension doesn't do what it's made for.

### Steps To Reproduce

1. Install `pip-on-top` GNOME extension via Home-Manager:

    ```nix
    { ... }:

    {
      home.packages = with pkgs; [
        gnomeExtensions.pip-on-top
      ];
    }
    ```

2. Enable the extension.
3. Enable "Show on all workspaces" in the extension settings.
4. Open the web browser, Firefox in my case.
5. Open YouTube and play a video.
6. Change your browser tab.
    - **NOTE:** This too is a problem. Switching Workspaces alone or Changing Windows won't turn on the Picture-in-Picture mode.

### Expected behavior

After following the steps above, the Picture-in-Picture mode of the browser should be automatically turn on and continue to show you the playing video in a pop-up window.

### Notify maintainers

@honnip @Rafostar

### Metadata

```bash
[user@host:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241023.2768c7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/jsy7c2d1alj2gkxj36h794kk43d5601l-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Rafostar** [comment]
> Switching Workspaces alone or Changing Windows won't turn on the Picture-in-Picture mode (..) the browser should be automatically turn on and continue to show you the playing video in a pop-up window

The extension is not for turning on PiP automatically, nor for making normal browser tabs PiP windows. The sole purpose of the extension is to keep PiP windows on top and (optionally) on all workspaces. This was needed for Wayland session, cause unlike Xorg, it does not have such protocol implemented to do so. You still have to click the PiP button in browser.

**Comment by 4r7if3x** [comment]
@Rafostar My bad, I've been busy minded and didn't think about this right. It's been some time since last I set this up the way I wanted. In combination with using you GNOME extension, I also had to enable "Picture-in-Picture: auto-open on tab switch" setting of Firefox itself. I appreciate your answer though.
