### ISSUE TITLE
Vesktop wont't get indexed by Raycast on MacOS

### ISSUE THREAD

**Issue by frostplexx** [NixOS/nixpkgs#353069]
### Steps To Reproduce
1. Install vesktop
2. Launch Raycast and wait a few seconds
3. Vesktop will not show up

### Expected behavior
Vesktop should get correctly picked up by Raycast, similar to any other packages.

### Screenshots
<img width="689" alt="image" src="https://github.com/user-attachments/assets/46156ec1-8f63-42be-bbef-e00a05fd6f38">

### Additional context
The Vesktop bundle has `.App` as an extention which seems to get ignored by Raycast. The correct extension should be `.app` with a lowercase "a" (see other apps in the screenshot).

### Notify maintainers

@getchoo
@Scrumplex
@vgskye
@pluiedev

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/Users/daniel/.nix-defexpr/channels/nixpkgs`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
CC @DontEatOreo, raycast maintainer
