### ISSUE TITLE
llvm and clang conflict

### ISSUE THREAD

**Issue by sheijk** [NixOS/nixpkgs#3530]
When installing both LLVM and clang 3.4.2 their address sanitizer libraries will produce a conflict:

> $ nix-env -i llvm clang
> installing `llvm-3.4.2'
> installing`clang-3.4.2'
> building path(s) `/nix/store/l62v8mw36k5nb98bh858jnw2sznz7bir-user-environment'
> collision between`/nix/store/ds8h69qpsrfgcl1b3in2i5ccnx8iy6gh-clang-3.4.2/lib/clang/3.4.2/lib/linux/libclang_rt.asan-x86_64.a' and `/nix/store/2hkdqic3b2wylfbgvbiap8f6p5s6a020-llvm-3.4.2/lib/clang/3.4.2/lib/linux/libclang_rt.asan-x86_64.a'; use`nix-env --set-flag priority NUMBER PKGNAME' to change the priority of one of the conflicting packages
> builder for `/nix/store/gn01rp1d2f4qhphqmyqghwwgi5yln4yq-user-environment.drv' failed with exit code 255
> error: build of`/nix/store/gn01rp1d2f4qhphqmyqghwwgi5yln4yq-user-environment.drv' failed

This is on Debian Jessie/sid. Followed the steps on http://nixos.org/nixpkgs/download.html to install package channel:

> $ nix-channel --add http://nixos.org/channels/nixpkgs-unstable
> $ nix-channel --update

From looking at the list of packages I got a feeling there is a different way to get both llvm and clang but I couldn't figure it out (nixpkgs.llvmPackages.clang, etc.)

**Comment by Profpatsch** [comment]
(triage) @sheijk can you try again with a recent system?

**Comment by Profpatsch** [comment]
No repsonse, so close @zimbatm

**Comment by jbeigel** [comment]
This seems to be a problem (still or again):

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
$ nix-channel --update
$ nix-env -i llvm clang
installing ‘llvm-5.0.0’
installing ‘clang-4.0.1’
building path(s) ‘/nix/store/x16jdwb45rbmmwk9bc4j1am38xb1rily-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/ih7789h668y8xng78gav67rg8qklwg7s-clang-4.0.1/lib/LLVMgold.so’ and ‘/nix/store/05pgn9brj0v8rg54dqbw9vwvk1jab9bg-llvm-5.0.0/lib/LLVMgold.so’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/qhd1dn569dy7dqf7xgcrqgs7jvrk8s30-user-environment.drv’ failed with exit code 2
error: build of ‘/nix/store/qhd1dn569dy7dqf7xgcrqgs7jvrk8s30-user-environment.drv’ failed
```

**Comment by matthewbauer** [comment]
This appears to be fixed:

```
warning: there are multiple derivations named 'llvm-8.0.1'; using the first one
warning: there are multiple derivations named 'clang-7.1.0'; using the first one
installing 'llvm-8.0.1'
installing 'clang-7.1.0'
these paths will be fetched (127.23 MiB download, 630.13 MiB unpacked):
  /nix/store/2xrspa4s53dil43nfwixrx2k2xfjzd17-clang-7.1.0-python
  /nix/store/54bn99pcf7smzzw95a2mxgaxf1bz1g83-llvm-8.0.1-python
  /nix/store/782wdzc1r9m5asmlz0983sm8s68lkxfl-clang-7.1.0-lib
  /nix/store/di3k5bxzaqcn8mvcv0dsgqskapk5yjyb-clang-7.1.0
  /nix/store/qz4s1lnaz4p2ywwnhd36s6pbpy0qqczx-llvm-7.1.0-lib
  /nix/store/z62gw313nyslapbw3mhrlsxm18hb7a41-llvm-8.0.1
copying path '/nix/store/2xrspa4s53dil43nfwixrx2k2xfjzd17-clang-7.1.0-python' from 'https://cache.nixos.org'...
copying path '/nix/store/54bn99pcf7smzzw95a2mxgaxf1bz1g83-llvm-8.0.1-python' from 'https://cache.nixos.org'...
copying path '/nix/store/z62gw313nyslapbw3mhrlsxm18hb7a41-llvm-8.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/qz4s1lnaz4p2ywwnhd36s6pbpy0qqczx-llvm-7.1.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/782wdzc1r9m5asmlz0983sm8s68lkxfl-clang-7.1.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/di3k5bxzaqcn8mvcv0dsgqskapk5yjyb-clang-7.1.0' from 'https://cache.nixos.org'...
building '/nix/store/qlj3921mbkr2rcb9dirjadsx6p8h728l-user-environment.drv'...
created 492 symlinks in user environment
```
