### ISSUE TITLE
Update request: musescore 4.4.2 → 4.4.3

### ISSUE THREAD

**Issue by callumjohnspiller** [NixOS/nixpkgs#353006]
- Package name: musescore
- Latest released version:

- Current version on the unstable channel: 4.4.2
- Current version on the stable/release channel: 4.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@vandenoever 
@doronbehar 
@orivej 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Hmm I wonder how come GitHub didn't notify me of the upstream release.. You are invited to test https://github.com/NixOS/nixpkgs/pull/353207 . Will backport it to release branches manually afterwards.
