### ISSUE TITLE
Update request: static-web-server 2.33.0 -> 2.33.1

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#353190]
- Package name: static-web-server
- Latest released version: 2.33.1

- Current version on the unstable channel: 2.33.0
- Current version on the stable/release channel: 2.24.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@figsoda 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
PR: #353280

**Comment by misuzu** [comment]
https://nixpk.gs/pr-tracker.html?pr=353280
https://nixpk.gs/pr-tracker.html?pr=361561
