### ISSUE TITLE
haskell: extraLibraries behaves really strangely depending on number of elements

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#3531]
If we have an expression with `extraLibraries = [ gsl ];` then we get 

```
Setup: Missing dependency on a foreign library:
* Missing C library: gsl
```

It turns out that extraLibraries only works if there are at least two elements. So for example `extraLibraries = [ gsl gsl ];` works.

**Comment by peti** [comment]
Does this issue still exist? Which package did you try to build in order to re-produce thisL

**Comment by Fuuzetsu** [comment]
Hm, I do not remember. Foolish of me to not include test case. I will close for now and if I remember to play with this in the future then I will reopen or make a new issue.
