### ISSUE TITLE
pitivi: proxymanager error

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#35318]
## Issue description

I get this errors when i start Pitivi:

```
[davidak@X230:~]$ nix-shell --pure -p pitivi --command pitivi

** (.pitivi-wrapped:32692): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Missing soft dependency:
- pycanberra not found on the system
    -> enables sound notifications when rendering is complete

(.pitivi-wrapped:32692): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
ERROR 07:44:45 proxymanager      <ProxyManager at 0x7fb322b3c120> __init__: Not supporting any proxy formats! (../../nix/store/q83spj4cxqqzs6r83sjh4rnbndnmsplj-pitivi-0.96/lib/pitivi/python/pitivi/utils/proxy.py:123)
```

### Steps to reproduce

see above

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.3001.395fe7f8bcb (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(davidak): `""`
 - channels(root): `"nixos-17.09.3001.395fe7f8bcb, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
When i open the import media dialog i get this message very often:

```
(.pitivi-wrapped:1575): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process ?dbus-launch? (No such file or directory)
```

I can't find any mp4 when only "supported formats" are displayed, but i can import them when i search for "all file types".

I get this message on console when i pull a imported mp4 to the timeline:

```
/nix/store/g4i2k60sb4g0q9gk2p5sjc142sqnmhcp-python3.6-matplotlib-2.0.2/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/nix/store/q83spj4cxqqzs6r83sjh4rnbndnmsplj-pitivi-0.96/lib/pitivi/python/pitivi/timeline/previewers.py", line 913, in _modulateRate
    assert res
AssertionError
```

After some cuts the GUI hangs, the process has 100% cpu utilization and strace shows this over and over again:

```
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=14, events=POLLIN}, {fd=20, events=POLLIN}, {fd=29, events=POLLIN}, {fd=36, events=POLLIN}, {fd=38, events=POLLIN}, {fd=53, events=POLLIN}, {fd=58, events=POLLIN}], 10, 27039) = 1 ([{fd=3, revents=POLLIN}])
```

I had to kill it.

Next try, i was able to import that mp4, cut it and start export. I get the message

```
(.pitivi-wrapped:3489): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object->refcount > 0' failed
```

After some seconds it hangs again, GUI not responding.

![screenshot_2018-02-22_08-27-03](https://user-images.githubusercontent.com/91113/36525435-4c3ddf18-17aa-11e8-9651-95a5fa7cfff8.png)

Next try, export as OGG works. When it's finished i got the message

```
ERROR 08:29:49 freedesktoporgsystem <FreedesktopOrgSystem at 0x7fc5980c6af8> desktopMessage: desktopMessage: Failed displaying notification: Failed to execute child process \u201cdbus-launch\u201d (No such file or directory) (../../nix/store/q83spj4cxqqzs6r83sjh4rnbndnmsplj-pitivi-0.96/lib/pitivi/python/pitivi/utils/system.py:211)
```

Might be due to `pycanberra` missing like displayed at start.

When i click "play" on the render dialog, i get this error:

```
Traceback (most recent call last):
  File "/nix/store/q83spj4cxqqzs6r83sjh4rnbndnmsplj-pitivi-0.96/lib/pitivi/python/pitivi/render.py", line 309, in _playRenderedFileButtonClickedCb
    subprocess.Popen(["xdg-open", self.main_render_dialog.outfile])
  File "/nix/store/z1avajv6hrjcx9nb07x9nd6cklb45w2r-python3-3.6.4/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/z1avajv6hrjcx9nb07x9nd6cklb45w2r-python3-3.6.4/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'
```

Every export worked (tested mkv, mov, ogv and webm). NixOS was not able to play sound after i opened one in VLC. VLC on macOS was able to play the files. After i played a youtube video in Chromium, audio worked again on NixOS, also in VLC. desktop linux is still strange.

I would consider Pitivi usable when you save after every action to prevent loosing work when it hangs. That might be a general pitivi issue, not related to NixOS. I tested it very often in the past and it has always crashed or hangs. But getting better and better. :)

**Comment by jtojnar** [comment]
The `xdg-open` calls is no longer there in 0.98, we should probably upgrade.

**Comment by davidak** [comment]
@jtojnar that might also fix some stability issues.

**Comment by davidak** [comment]
NixOS stable has version 0.99. I can't reproduce any of the mentioned issues.

Pitivi seems usable now!

NixOS unstable already has the next version 0.999.
