### ISSUE TITLE
nixos-firewall-tool: broken with nf_tables

### ISSUE THREAD

**Issue by 6543** [NixOS/nixpkgs#353129]
### Describe the bug
use nftables over iptables on your system and try to use the [`nixos-firewall-tool`](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/ni/nixos-firewall-tool/nixos-firewall-tool.sh) to open a port temporary ...

### Steps To Reproduce
1. set `networking.nftables.enable = true;` on your nixos
2. open a shell with `nixos-firewall-tool` (`nix shell nixpkgs#nixos-firewall-tool`)
3. try to use it e.g. `sudo nixos-firewall-tool show`, `sudo nixos-firewall-tool open tcp 3000`, ...

### Expected behavior
working ports etc...

### Screenshots
![image](https://github.com/user-attachments/assets/1f228236-cc52-4f2d-8a83-efe629182f5d)

### Notify maintainers

@clerie

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1-zen1, NixOS, 24.05 (Uakari), 24.05.20241031.a500034`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
 - nixpkgs: `/nix/store/c73xqpp5pfzfiqfz5d89bn945fqdhgx1-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 6543** [comment]
```
nft add rule inet nixos-fw input-allow tcp dport 3234 accept comment "added_by_nixos-firewall-tool"
```
```
nft -a list chain inet nixos-fw input-allow | grep added_by_nixos-firewall-tool
```

**Comment by 6543** [comment]
looks like https://github.com/NixOS/nixpkgs/commit/cabbab19e21814cb41a4d2aff474924e511aaa31 solved it already ... can we backport it?

**Comment by nbdd0121** [comment]
This is known, which is why nixos-firewall-tool is not added to system packages if you use nftables.

Given that 24.11 is close, I think we probably shouldn't backport it.

**Comment by 6543** [comment]
should we have this issue open and backport it after 24.11 is out?
or close it and mark it as solved?

**Comment by nbdd0121** [comment]
What do you mean by backport after 24.11 is out? https://github.com/NixOS/nixpkgs/pull/324615 will be in 24.11.

If we don't backport to 24.05 then there's nothing to act.
