### ISSUE TITLE
Package request: Niri

### ISSUE THREAD

**Issue by partisani** [NixOS/nixpkgs#353193]
**A scrollable-tiling Wayland compositor.**

**Metadata**

* homepage URL: [github](https://github.com/YaLTeR/niri)
* source URL: [github](https://github.com/YaLTeR/niri)
* license: GNU General Public License v3.0
* platforms: unix(?), linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by niklaskorz** [comment]
Niri is [already packaged](https://search.nixos.org/packages?channel=unstable&size=50&sort=relevance&type=packages&query=Niri) and even has a [module](https://search.nixos.org/options?channel=unstable&show=programs.niri.enable&from=0&size=50&sort=relevance&type=packages&query=Niri).

**Comment by partisani** [comment]
~~i am so fu----- dumb~~ i forgot to seach in unstable
