### ISSUE TITLE
Update request: Jellyfin 10.9.11 → 10.10.0

### ISSUE THREAD

**Issue by WesfunOfficial** [NixOS/nixpkgs#353281]
- Package name: Jellyfin
- Latest released version: 10.10.0

- Current version on the unstable channel: 10.9.11
- Current version on the stable/release channel: 10.9.11

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@nyanloutre 
@minijackson 
@purcell 
@jojosch 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by itepastra** [comment]
Happened in #351966
