### ISSUE TITLE
Cocoa problems when trying to build gst-plugins-bad-1.12.3 on macOS / Darwin

### ISSUE THREAD

**Issue by Kaali** [NixOS/nixpkgs#35322]
## Issue description

I'm working towards adding Darwin support for gstreamer. But I cannot compile gst-plugins-bad because of Apple SDK/framework build errors. Compiler output can be read here https://gist.github.com/Kaali/0b9e8fecd5a35989e9ae968d059ffa96

### Steps to reproduce

Apply patch from here: https://gist.github.com/Kaali/483236da1407c750f305533fe8e25983

Run `nix-build -A mopidy`. mobidy is the final application I'm working towards, but I think it's not really important for this issue, just that something requires gst-plugins-bad.

## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(kaali): `""`
 - channels(root): `"nixpkgs-18.03pre127302.e860b651d6e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by matthewbauer** [comment]
Thanks for working on this!

Some things that can help:

- add ```-fno-objc-arc```  to NIX_COMPILE_CFLAGS/NIX_LDFLAGS
- try applying patches and configureFlags from [MacPorts](https://github.com/macports/macports-ports/blob/master/gnome/gstreamer1-gst-plugins-bad/Portfile) and [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-bad.rb)
- try setting NIX_DEBUG=true in the environment to get what the actual Clang call is (there's probably a flag there that shouldn't be there)

Also gst-plugins-bad might not actually be needed by mopidy. You could try temporarily disabling it to see how mopidy deals with it (we sometimes disable dependencies only on Darwin with ```++ stdenv.lib.optional stdenv.isDarwin gst-plugins-bad``` in buildInputs).

**Comment by Kaali** [comment]
gst-plugins-bad adds `-fobjc-arc` which probably means that it wants to use ARC. I guess disabling it would leak memory?

I probably could disable gst-plugins-bad, but I'm learning my way around Nix on macOS, and will probably want to build ARC enabled software later on. What is the difference that makes this a problem with Nix and not when building manually with XCode provided toolchain?

**Comment by LnL7** [comment]
10.10, but yes we're kind of stuck with an older CF until apple releases the sources.

**Comment by Kaali** [comment]
I compared Apple SDK headers included in Nix and the newest in macOS. The headers are too old to be able to build gst-plugins-bad with Cocoa enabled.

**Comment by matthewbauer** [comment]
Fixed: https://hydra.nixos.org/job/nixpkgs/trunk/gst_all_1.gst-plugins-bad.x86_64-darwin

**Comment by matthewbauer** [comment]
Fixed: https://hydra.nixos.org/job/nixpkgs/trunk/gst_all_1.gst-plugins-bad.x86_64-darwin
