### ISSUE TITLE
plex-desktop: Unable to find /usr/share/libdrm/amdgpu.ids

### ISSUE THREAD

**Issue by detroyejr** [NixOS/nixpkgs#353227]
### Describe the bug

A few users of plex-desktop have reported that the app fails to launch under certain circumstances when it can't find `/usr/share/libdrm/amdgpu.ids`.

I expect we can fix this by [adding `libdrm` to the list of target packages in `buildFHSEnv`,](https://github.com/detroyejr/nixpkgs/commit/af1c63445618013230711ebe86d1440e3d74f7d6) but I haven't been able to test this since I'm not experiencing this issue myself. If you're having this problem, let me know and we can try to get this fixed.

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nayrsirhc** [comment]
I am experiencing this issue happy to work together to test and fix this

**Comment by detroyejr** [comment]
Can you build and run the result here?

```bash
export NIXPKGS_ALLOW_UNFREE=1
nix build github:detroyejr/nixpkgs/plex-libdrm-fix#plex-desktop --impure
result/bin/plex-desktop
```

**Comment by nayrsirhc** [comment]
Your fix does indeed remove this error
```bash
# Nixpkgs plex as example
nix build nixpkgs#plex-desktop --impure
   result/bin/plex-desktop
/usr/share/libdrm/amdgpu.ids: No such file or directory
Error: Unable to set up server: sqlite3_statement_backend::loadOne: attempt to write a readonly database (N4soci10soci_errorE)

# Fixed version

```bash
nix build github:detroyejr/nixpkgs/plex-libdrm-fix#plex-desktop --impure
   result/bin/plex-desktop
Error: Unable to set up server: sqlite3_statement_backend::loadOne: attempt to write a readonly database (N4soci10soci_errorE)
```

I am however left with this error afterwards sadly
`Error: Unable to set up server: sqlite3_statement_backend::loadOne: attempt to write a readonly database (N4soci10soci_errorE)`

Which seems has some relation to the sqlllite dbs  here which do all seem to have read only permissions
```bash
ls ~/.local/share/plex/Plex\ Media\ Server/Plug-in\ Support/Databases/ -l
.r--r--r-- crispy users 311K Mon Nov 18 08:19:50 2024  com.plexapp.plugins.library.db
.r--r--r-- crispy users  32K Mon Nov 18 08:19:50 2024  com.plexapp.plugins.library.db-shm
.r--r--r-- crispy users   0B Mon Nov 18 08:19:50 2024  com.plexapp.plugins.library.db-wal
```

Ran this 
```bash
chmod a+w ~/.local/share/plex/Plex\ Media\ Server/Plug-in\ Support/Databases/*
```

Waiting for it to start up at the moment but I think this last part is unrelated to what you are trying to fix here, so I can confirm your fix does work and fixes the issue described
