### ISSUE TITLE
Package request: nicegui

### ISSUE THREAD

**Issue by belamu** [NixOS/nixpkgs#353349]
**NiceGUI**

NiceGUI is a browser-based frontend framework in Python.
Quite simple to use (but probably with a huge overhead on underlying code).

**Metadata**

* homepage URL: https://nicegui.io/
* source URL: https://github.com/zauberzeug/nicegui ; [pypi](https://pypi.org/project/nicegui/)
* license: mit
* platforms: linux, darwin

**Comment by belamu** [comment]
Also asked for support [over at NiceGUI](https://github.com/zauberzeug/nicegui/discussions/3942)

**Comment by pluiedev** [comment]
May be fixed with #352189

**Comment by belamu** [comment]
Ah! I didn't check the pull requests, my bad. Thank you for noticing.
