### ISSUE TITLE
Update request: mealie 1.12.0 → 2.1.0

### ISSUE THREAD

**Issue by jukremer** [NixOS/nixpkgs#353395]
- Package name: mealie
- Latest released version: 2.1.0

- Current version on the unstable channel: 1.12.0
- Current version on the stable/release channel: 1.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@litchipi 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by litchipi** [comment]
I'll look into it once I get a bit more personal time, but as it's a major version release, it might take a while to get everything rolling without bug
