### ISSUE TITLE
Update request : Apostrophe 3.1 → 3.2

### ISSUE THREAD

**Issue by nbCloud91** [NixOS/nixpkgs#353316]
- Package name: Apostrophe
- Latest released version: 3.2

- Current version on the unstable channel: 3.1
- Current version on the stable/release channel: 3.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

cc @Aleksanaa

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
Please test. There's a bug on my side and I'm not sure if it's because of my theme or something

**Comment by nbCloud91** [comment]
I tested this, with Wayland, the app fails to launch with this error:
```
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Gdk-Message: 21:31:23.019: Error 71 (Protocol error) dispatching to Wayland display.
```

When I run `env WAYLAND_DISPLAY="" apostrophe`, the app runs all right. But the popup LaTeX previews and spell checking is not working.

I also notice a slight flicker, is this what you were referring to?
[Kooha-2024-11-03-22-13-05.webm](https://github.com/user-attachments/assets/240f79b6-149c-4429-9e03-d3e2d406199c)

**Comment by nbCloud91** [comment]
Okay that failing to launch under Wayland was because of some other issue, updating to NVIDIA beta drivers solved it.
