### ISSUE TITLE
Build failure: azure-cli 2.65.0

### ISSUE THREAD

**Issue by misaelaguayo** [NixOS/nixpkgs#353468]
### Steps To Reproduce

1. On Mac, run home-manager switch 
running home-manager, pulling azure-cli latest version 2.65.0 getting issue with 

### Build log

```
 >     import nacl.signing
 > ModuleNotFoundError: No module named 'nacl'
 For full logs, run 'nix-store -l /nix/store/rfkpbbr8aqz2cnfnqdz751dkbyz8gfm0-python3.12-fabric-3.2.2.drv'
```

### Additional context

I tried to build `fabric/default.nix` and I was getting the same error, so I think the fabric `default.nix` is missing a python dependency of `pynacl`. 
I was able to make the change and build `fabric`, but after that was not able to figure out how to build `azure-cli`

### Notify maintainers

@katexochen 

### Metadata

---

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.0.0, macOS 15.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by katexochen** [comment]
Did you try with latest unstable? unstable was just bumped and include the fix.

**Comment by misaelaguayo** [comment]
Ahh, got it. I was on `nixpkgs-unstable` which doesn't have that change yet but i've switched over to `nixos-unstable`. Thanks! I think this ticket can be closed, so I'll do that now
