### ISSUE TITLE
Non deterministic build failure: zynaddsubfx

### ISSUE THREAD

**Issue by nipsy** [NixOS/nixpkgs#353482]
### Steps To Reproduce

1. Select package zynaddsubfx for installation in current nixos-unstable.
2. Run rebuild and it fails.

### Build log

```
unpacking 1 channels...
building the system configuration...
error: builder for '/nix/store/iaf4hq11dvj1zk2l0i1xy5ilv76wsk1x-zynaddsubfx-3.0.6.drv' failed with exit code 8;
       last 25 log lines:
       >
       > # Statistics
       >
       > Ports:
       > * checked (and not disabled): 803
       > * disabled: 6
       >
       > Time (incl. IO wait):
       > * total: 5s
       > * per port (checked or disabled): 6.18ms
       >
       > # Port checker test summary
       >
       > **FAILURE!**
       >
       > Error: port-checker has returned 1.
       >
       >
       > 98% tests passed, 1 tests failed out of 54
       >
       > Total Test time (real) =   9.23 sec
       >
       > The following tests FAILED:
       >         53 - PortChecker (Failed)
       > Errors while running CTest
       For full logs, run 'nix log /nix/store/iaf4hq11dvj1zk2l0i1xy5ilv76wsk1x-zynaddsubfx-3.0.6.drv'.
error: 1 dependencies of derivation '/nix/store/ilf5jvpc8na67qp6z8z39sfgwq3aj3z1-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8z9b0d3si0fijxv4pbbrbgwigwa7nscx-nixos-system-arrakis-24.11.20241102.7ffd9ae.drv' failed to build
```

Full build failure log at https://gist.github.com/nipsy/eb88b5fa1bfcdeb61c8fc583f19abf02.

### Notify maintainers

@kira-bruneau 

### Metadata

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
```

**Comment by itepastra** [comment]
I'm unable to reproduce the failure with `nix-store --realise /nix/store/iaf4hq11dvj1zk2l0i1xy5ilv76wsk1x-zynaddsubfx-3.0.6.drv` (with or without `--check`)

**Comment by nipsy** [comment]
Odd.  In case it ends up being relevant:

```
% sed -n '/^processor.*: 0$/,/^$/p' /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 33
model name      : AMD Ryzen 7 5800X 8-Core Processor
stepping        : 0
microcode       : 0xa20102b
cpu MHz         : 2200.000
cache size      : 512 KB
physical id     : 0
siblings        : 16
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic
cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass srso ibpb_no_ret
bogomips        : 7586.07
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

**Comment by itepastra** [comment]
Does running the `nix-store` command I sent above work for you or not?

**Comment by nipsy** [comment]
Whelp, that's odd.  I switched to a different AMD system (6900HS laptop) and it didn't have issues.  And then after some other messing about on this original system where it failed, it's now working fine (even though the futzing about didn't have anything to do with zynaddsubfx or anything related I can think).

Anyway, not sure if the normal approach here is to close this as completed or as not planned, so I'll go with the former for now.  Let me know if that's not the correct method.

**Comment by itepastra** [comment]
you don't have the issue anymore, so I'd say it's completed as well.

**Comment by kira-bruneau** [comment]
Oh thanks for reporting this @itepastra! Based on the source of the test, it looks like it sleeps for 3 seconds before testing the port, and if if can't connect, it'll fail: https://github.com/zynaddsubfx/zynaddsubfx/blob/3.0.6/src/Tests/check-ports.rb#L18-L21.

So it's not deterministic, but it's unlikely it'll fail.

It might make sense just to disable the test in the nix build, but it would be ideal to fix this upstream.

**Comment by kira-bruneau** [comment]
I'm going to re-open this, because I want to keep track of the issue.

**Comment by kira-bruneau** [comment]
Oh wait a second, this was fixed about a year ago: https://github.com/zynaddsubfx/zynaddsubfx/commit/ef392d964724236d7c845ff0e5529eed077fbe98

There just hasn't been a release since then. I think I might just backport the fix for the test then.

**Comment by itepastra** [comment]
I wonder if a patch like this would fix it

```patch
tree f2134e4b626be613780f6ebf3b9b54d697c7c060
parent be9fc502748c8b19fc4ab67751428734549d958b
author Noa Aarts <noa@voorwaarts.nl> Sun Nov 3 23:37:43 2024 +0100
committer Noa Aarts <noa@voorwaarts.nl> Sun Nov 3 23:37:43 2024 +0100

fix check ports undeterministic result if the computer is too slow

diff --git a/src/Tests/check-ports.rb b/src/Tests/check-ports.rb
index b39a1c0a..0a368e73 100755
--- a/src/Tests/check-ports.rb
+++ b/src/Tests/check-ports.rb
@@ -14,11 +14,10 @@ Open3.popen3(my_path + "/../zynaddsubfx -O null --no-gui") do |stdin, stdout, st
   while line=stderr.gets do 
     # print "line: " + line;
     if /^lo server running on (\d+)$/.match(line) then
-      sleep 3 # give zyn more time to setup
-      port_checker_rval = system(my_path + "/../../rtosc/port-checker 'osc.udp://localhost:" + $1 + "/'")
-      if port_checker_rval != true then
-        puts "Error: port-checker has returned #{$?.exitstatus}."
-        rval=1
+      loop do
+        sleep 1 # don't hot loop as much
+        port_checker_rval = system(my_path + "/../../rtosc/port-checker 'osc.udp://localhost:" + $1 + "/'")
+        break if port_checker_rval != true
       end
       begin
         # Check if zyn has not crashed yet
```

**Comment by kira-bruneau** [comment]
Hmm actually it's not so simple to backport, it requires updating one of the submodules too.

@itepastra It seems like that patch ends up in an infinite loop, since it won't break if it succeeds. Maybe it would be more reliable if we added multiple retries, but I think it'd be simpler to just disable it until the next release.

**Comment by itepastra** [comment]
> Hmm actually it's not so simple to backport, it requires updating one of the submodules too.
> 
> @itepastra ~It seems like that patch ends up in an infinite loop, since it won't break if it succeeds~ Looks like you updated the condition. Although even with that change, I think a potentially hanging test would be worse than a failing test. Maybe it would be more reliable if we added a condition for the number of retries, but I think it'd be simpler to just disable it until the next release.

Agreed tbh, I could make it retry some amount, but I think disabling is indeed better
