### ISSUE TITLE
Steam crashes

### ISSUE THREAD

**Issue by Reikott** [NixOS/nixpkgs#353405]
### Describe the bug
Trying to open Steam results in it crashing and it a bunch of errors being generated.

### Steps To Reproduce
1. Try to run Steam

### Expected behavior
Steam running properly.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.6, NixOS, 24.11 (Vicuna), 24.11.20241102.7ffd9ae`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `""`
 - nixpkgs: `/nix/store/zq2axpgzd5kykk1v446rkffj3bxa2m2h-source`

[Error.txt](https://github.com/user-attachments/files/17610848/Error.txt)
![Crash](https://github.com/user-attachments/assets/447e955a-2a9a-40c6-902f-62925d8561db)

**Comment by Reikott** [comment]
The issue seems simlar to this one: https://github.com/NixOS/nixpkgs/issues/266260

**Comment by 500InternalError** [comment]
Same here. I have and amd igpu and nvidia gpu, what's interesting is that by launching steam with `nvidia-offload steam`, it doesn't crash anymore.

**Comment by Reikott** [comment]
I tried launching steam using nvidia-offload. It did not work. Although it did open a window this time. Just to tell me that Steamwebhelper is not responding. So not much progress.
![Webhelper](https://github.com/user-attachments/assets/4b856241-ed96-47d1-a271-8e65353bfb64)

**Comment by Reikott** [comment]
And yes. I tried all of the options in that window. Still doesn't work.

**Comment by amadejkastelic** [comment]
The attr lib is missing, temp fix:
```nix
programs.steam = {
    enable = true;
    package = pkgs.steam.override {
      extraPkgs = pkgs:
        with pkgs; [
          gamemode
          config.programs.hyprland.package
          hyprshade
          attr
        ];
    };
};
```

**Comment by 500InternalError** [comment]
Try this:
```
    steam = {
      enable = true;
      # workaround for steam
      package = pkgs.steam.override {
        extraLibraries = pkgs: [ pkgs.xorg.libxcb ];
        extraPkgs =
          pkgs: with pkgs; [
            attr
            xorg.libXcursor
            xorg.libXi
            xorg.libXinerama
            xorg.libXScrnSaver
            libpng
            libpulseaudio
            libvorbis
            stdenv.cc.cc.lib
            libkrb5
            keyutils
            gamemode
          ];
      };
```
It works for me

**Comment by Reikott** [comment]
It worked by adding extraLibraries = pkgs: [ pkgs.xorg.libxcb ];

**Comment by Atemu** [comment]
Please make sure to ping us maintainers!

cc @K900 @mkg20001

Could you check whether https://github.com/NixOS/nixpkgs/pull/351928 fixed this? It should be in unstable shortly. (https://nixpk.gs/pr-tracker.html?pr=351928)

**Comment by 500InternalError** [comment]
> Please make sure to ping us maintainers!
> 
> cc @K900 @mkg20001
> 
> Could you check whether #351928 fixed this? It should be in unstable shortly. (https://nixpk.gs/pr-tracker.html?pr=351928)

Works for me! Thanks

**Comment by Reikott** [comment]
> Please make sure to ping us maintainers!
> 
> cc @K900 @mkg20001
> 
> Could you check whether #351928 fixed this? It should be in unstable shortly. (https://nixpk.gs/pr-tracker.html?pr=351928)

I just updated my system. Steam works fine now. Problem solved.

**Comment by Atemu** [comment]
Good to hear :)

**Comment by jtrees** [comment]
I'm still running into this issue (or a very similar one) with an amd gpu. The suggested workarounds do not work for me.

I'm on b681065d0919f7eb5309a93cea2cfa84dec9aa88 (24.11), running Hyprland (wayland).

**Comment by Atemu** [comment]
Please create a separate issue then.

**Comment by jtrees** [comment]
Yes, sir: https://github.com/NixOS/nixpkgs/issues/362525
