### ISSUE TITLE
Build failure: Jellyfin 10.10.0 & Jellyfin-ffmeg 7.0.2-5

### ISSUE THREAD

**Issue by WesfunOfficial** [NixOS/nixpkgs#353537]
### Steps To Reproduce

1. Be on NixOS 24.11pre698755.807e9154dcb1 (Vicuna) x86_64
2. Have Jellyfin & Jellyfin-ffmeg installed already
3. run sudo nixos-rebuild switch OR sudo nixos-rebuild switch --upgrade

### Build log
```
error: builder for '/nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/s13zkd4ln6pppk3za5hvl7iq47zk77pq-jellyfin-10.10.0.drv' failed to build
```

### Notify maintainers
**Jellyfin**
@nyanloutre 
@minijackson 
@purcell 
@jojosch 

**Jellyfin-FFMPEG**
@justinas 

Last person to commit to both
@dotlambda 
### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11pre698755.807e9154dcb1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gileri** [comment]
Without additional logs it's hard to be definitive, but I think your issue should be fixed since this PR : https://github.com/NixOS/nixpkgs/pull/353198

**Comment by WesfunOfficial** [comment]
> Without additional logs it's hard to be definitive, but I think your issue should be fixed since this PR : #353198

i did give a honest try to do a pastebin but they claim im posting "potentially offensive or questionable content" so it failed

**Comment by WesfunOfficial** [comment]
https://gist.github.com/WesfunOfficial/2c0fc1f77581798ec6caffb57782bb4c

**Comment by adamcstephens** [comment]
I'm seeing this same failure as the gist

```
error: builder for '/nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv' failed with exit code 2;
       last 25 log lines:
       > CC     libavcodec/libxevd.o
       > CC        libavcodec/libxeve.o
       > CC        libavcodec/libxvid.o
       > CC        libavcodec/libzvbi-teletextdec.o
       > CC    libavcodec/ljpegenc.o
       > CC       libavcodec/loco.o
       > CC   libavcodec/lossless_audiodsp.o
       > CC      libavcodec/lossless_videodsp.o
       > CC      libavcodec/lossless_videoencdsp.o
       > CC   libavcodec/lpc.o
       > CC    libavcodec/lscrdec.o
       > CC        libavcodec/lsp.o
       > CC    libavcodec/lzf.o
       > CC    libavcodec/lzw.o
       > CC    libavcodec/lzwenc.o
       > libavcodec/libxeve.c: In function 'get_conf':
       > libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
       >   199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
       >       |                           ^~~~~~
       > libavcodec/libxeve.c: In function 'libxeve_encode':
       > libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
       >   484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
       >       |                                        ^~~~~
       > make: *** [ffbuild/common.mak:82: libavcodec/libxeve.o] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv'.
```

**Comment by dotlambda** [comment]
Stop spamming this issue. If you read the comments you'd now this has been fixed on master.

**Comment by adamcstephens** [comment]
I’ll admit I missed the linked PR when first reading the issue. My additional comment was far from spam.
