### ISSUE TITLE
Build failure: Jellyfin 10.10.0 & Jellyfin-ffmeg 7.0.2-5 | More info provided this time

### ISSUE THREAD

**Issue by WesfunOfficial** [NixOS/nixpkgs#353545]
### Steps To Reproduce

1. Be on NixOS 24.11pre698755.807e9154dcb1 (Vicuna) x86_64
2. Have Jellyfin & Jellyfin-ffmeg installed already
3. run sudo nixos-rebuild switch OR sudo nixos-rebuild switch --upgrade

### Build log
https://gist.github.com/WesfunOfficial/2c0fc1f77581798ec6caffb57782bb4c

### Additional context

My Current Config: https://github.com/WesfunOfficial/homelab-config-nix/tree/main/nixos

### Notify maintainers
**Jellyfin**
@nyanloutre 
@minijackson 
@purcell 
@jojosch 

**Jellyfin-FFMPEG**
@justinas 

Last person to commit to both
@dotlambda 
### Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11pre698755.807e9154dcb1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Duplicate

**Comment by WesfunOfficial** [comment]
@dotlambda its a duplicate of a ticket you closed? seems silly to close

**Comment by dotlambda** [comment]
It's a duplicate of an issue that, as you can infer from a comment on that issue, has been fixed on master.
