### ISSUE TITLE
Package request: dut (fast disk usage calculator)

### ISSUE THREAD

**Issue by rlue** [NixOS/nixpkgs#353655]
**Project description**

From the author, [via Hacker News](https://news.ycombinator.com/item?id=40932492):

> "dut" is a disk usage calculator that I wrote a couple months ago in C. It is multi-threaded, making it one of the fastest such programs. It beats normal "du" in all cases, and beats all other similar programs when Linux's caches are warm (so, not on the first run). I wrote "dut" as a challenge to beat similar programs that I used a lot, namely pdu and dust.
>
> "dut" displays a tree of the biggest things under your current directory, and it also shows the size of hard-links under each directory as well. The hard-link tallying was inspired by ncdu[3], but I don't like how unintuitive the readout is. Anyone have ideas for a better format?
>
> There's installation instructions in the README. dut is a single source file, so you only need to download it and copy-paste the compiler command, and then copy somewhere on your path like /usr/local/bin.

**Metadata**

* homepage URL: https://codeberg.org/201984/dut
* source URL: https://codeberg.org/201984/dut
* license: GPL v3
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kek5chen** [comment]
cool program. @Frontear https://codeberg.org/201984/dut#specs :)

**Comment by Frontear** [comment]
This program already exists since 6066650cb46fd.

**Comment by rlue** [comment]
Good catch. I searched for it on https://search.nixos.org/packages, but neglected to try the `unstable` channel.

Thanks.
