### ISSUE TITLE
webex-44.8-0-.0404 fails to start

### ISSUE THREAD

**Issue by alazyworkaholic** [NixOS/nixpkgs#353682]
### Describe the bug
Webex silently fails to run.

### Steps To Reproduce
1. Install Webex by adding
```
{ config, lib, pkgs, ... }: let
unstable = import <nixos-unstable> { config = { allowUnfree = true; };};
in { environment.systemPackages = [ pkgs.webex ]; }
```
2. Notice that Webex does not appear in gnome's launcher.
3. Open a terminal, type `webex`. Nothing happens
4. type `strace -o webex-strace.txt webex`
[Uploading webex-strace.txt…]()

### Expected behavior
The webex application should start and display its application window on screen.

### Notify maintainers

@uvNikita 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.05 (Uakari), 24.05.5385.1719f27dd95f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by uvNikita** [comment]
Can you check if deleting WebexLauncher folder helps: `rm -rf ~/.local/share/WebexLauncher` ?

Webex has autoupdate "feature" that can prevent application to start.

**Comment by alazyworkaholic** [comment]
Webex started after removing that folder. Thanks.
