### ISSUE TITLE
GNU-cobol is not providing binaries

### ISSUE THREAD

**Issue by malikwirin** [NixOS/nixpkgs#353642]
### Describe the bug
The gnu-cobol package is not providing the binaries it says it would. `cobc`, `cob-config` and `cobcrun` are not available. When trying to package a simple hello world cobol programm I dont get an error message but also no results directory.

#### nix-shell
1. enter a nix shell with `nix-shell -p gnu-cobol`
2. use cobc binary
3. command not found

#### derivation
HelloWorld.cbl:
``` cobol
IDENTIFICATION DIVISION.
PROGRAM-ID.  HelloWorld.

PROCEDURE DIVISION.
    DISPLAY "Hello World!".
    STOP RUN.
```
default.nix
``` nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation {
  name = "hello-world-cobol";
  src = ./.;
  buildInputs = [ pkgs.gnu-cobol ];

  buildPhase = ''
    ${pkgs.gnu-cobol}/bin/cobc -x -free -o hello_world HelloWorld.cbl
  '';

  installPhase = ''
    mkdir -p $out/bin
    mv hello_world $out/bin/
  '';

  meta = {
    description = "Hello World Cobol program";
    license = pkgs.lib.licenses.mit;
    maintainers = with pkgs.stdenv.lib.maintainers; [ ];
  };
}
``` 

### Expected behavior
I should get an executable HelloWorld binary

### Screenshots
![Bildschirmfoto vom 2024-11-04 14-24-37](https://github.com/user-attachments/assets/6f3668fe-e66e-4b19-82a8-87256ca3bcbf)

### Additional context
I need this for uni.

### Notify maintainers

@ericsagnes @lovesegfault @xworld21 @chadac 

### Metadata

---
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.05 (Uakari), 24.05.20241018.4a3f2d3`
  - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/store/3dkd7jjg354lylv9s5lm3387f4yfls7y-source`
 
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lovesegfault** [comment]
That's because the package has multiple outputs and the binaries are in the `bin` output. If you put it in `nativeBuildInputs` instead of `buildInputs` it should work.

**Comment by Kek5chen** [comment]
> That's because the package has multiple outputs and the binaries are in the `bin` output. If you put it in `nativeBuildInputs` instead of `buildInputs` it should work.

While this is most likely the issue in the first mention. Shouldn't gnu-cobol provide these binaries in a nix-shell environment as shown in the screenshot?

**Comment by Kek5chen** [comment]
could you re-run with -v?

**Comment by malikwirin** [comment]
> could you re-run with -v?
> 
> Also could we please switch to code-tagged log output instead of screenshots? Think about the cli people please.

The reason for the freeze was it was trying to use a binary cache, who's domain (duckdns.org) seems to be blocked in uni network.

This is the new output after replacing `buildInputs` with `nativeBuildInputs` and disabling that substituter:
``` 
this derivation will be built:
  /nix/store/i7q1km2j9b2627rp0byv7gyw4azg99im-hello-world-cobol.drv
building '/nix/store/i7q1km2j9b2627rp0byv7gyw4azg99im-hello-world-cobol.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/pvnr6nv9v49cd3wywrczg31v9wrmw7zl-HelloWorld
source root is HelloWorld
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
/nix/store/479jddljb3spih04qb01qlyv39qb2zn9-stdenv-linux/setup: line 1585: cobc: command not found
error: builder for '/nix/store/i7q1km2j9b2627rp0byv7gyw4azg99im-hello-world-cobol.drv' failed with exit code 127;
       last 9 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/pvnr6nv9v49cd3wywrczg31v9wrmw7zl-HelloWorld
       > source root is HelloWorld
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > /nix/store/479jddljb3spih04qb01qlyv39qb2zn9-stdenv-linux/setup: line 1585: cobc: command not found
       For full logs, run 'nix log /nix/store/i7q1km2j9b2627rp0byv7gyw4azg99im-hello-world-cobol.drv'.
 ```

**Comment by Kek5chen** [comment]
Looks good. It seems the gnu-cobol package is a bit finicky with its outputs for the reason mentioned in the source. Try specifying the build output directly:

```nix
nativeBuildInputs = [ gnu-cobol.bin ];
```

**Comment by malikwirin** [comment]
> Looks good. It seems the gnu-cobol package is a bit finicky with its outputs for the reason mentioned in the source. Try specifying the build output directly:
> 
> ```nix
> nativeBuildInputs = [ gnu-cobol.bin ];
> ```
> 
> You can do the same in a shell
> 
> ```shell
> nix-shell -p gnu-cobol.bin
> ```

That worked, thank you a lot
