### ISSUE TITLE
Build failure: clickhouse

### ISSUE THREAD

**Issue by xanderio** [NixOS/nixpkgs#353775]
### Steps To Reproduce

1. build clickhouse on aarch64

### Build log

```
CMake Error at cmake/cpu_features.cmake:72 (MESSAGE):
  The build machine does not satisfy the minimum CPU requirements, try to run
  cmake with -DNO_ARMV81_OR_HIGHER=1
Call Stack (most recent call first):
  CMakeLists.txt:257 (include)
```
https://gist.github.com/xanderio/3295dc10debe52f94044a480a6dcb2f7

### Additional context

This seems to be limited to aarch64.

### Notify maintainers

@orivej @mbalatsko 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
https://github.com/ClickHouse/ClickHouse/pull/46803

Was this missed simply because both maintainers pcs and hydra are modern enough? Is it the same situation on x86_64 where checks for eg. sse4_2 pass but then it's removed by our toolchain wrappers anyway to enforce x86-64-v1?
