### ISSUE TITLE
Kernel 6.6.57+ io_uring stall ("yarn install takes indefinitely")

### ISSUE THREAD

**Issue by gador** [NixOS/nixpkgs#353709]
Update:

The root cause is due to a linux kernel regression on the _build_ system. The affected kernels are:
>- 6.6.56: succeeds
>- 6.6.57: fails
>- 6.6.58: fails
>- 6.6.59: fails
>- 6.6.59 (with f4ce3b5 reverted): succeeds
>- 6.11.6: succeeds

and the first one landed in nix in 0e4c64ff9cef5800c6a3f4838c66a918ceb61398

This kernel regression causes `npm` and `yarn` to hang and be unkillable. 

It has nothing to do with nix sandboxing, as I've first suspected.

---

### Describe the bug

Currently `yarn install` hangs at the step `linking dependencies...` 

### Steps To Reproduce
1.Try to build `pgadmin4` on master
2.Wait for `linking dependencies...`
3. ...

or just run `nix build  github:nixos/nixpkgs/71e91c409d1e654808b2621f28a327acfdad8dc2#pgadmin --rebuild`

### Expected behavior
`yarn install` should continue with the install process

### Additional context
I've noticed this issue on an unrelated small bugfix in `pgadmin4` which caused a rebuild, which did not work. (#353092). Ofborg worked just fine, which is why I merged this small fix, but the package never did build on my system. Neither does it currently on hydra (See e.g. https://hydra.nixos.org/build/277185860/nixlog/1)

I'm not sure what changed, since nothing substantially changed on the package. I've also tried to re-run the update script which resulted in exactly the same `yarn.lock`. 

Running `strace` or `lsof` did not result in any trace of the issue.

Also, interestingly, running `--check` on an older `nixos-unstable` `pgadmin4` derivation fails to build at the same step.

Is there anything in the nix builder, which changed sandbox or build behavior which stalled `yarn` ? 
I've looked at https://github.com/NixOS/nix/pull/10312 which changed stuff related to the sandbox and found an old unpatched nix version in `24.05` (which is running nix version 2.18.2 which according to https://github.com/NixOS/nix/security/advisories/GHSA-q82p-44mg-mgh5 hasn't been fixed, yet) and it does compile the current `pgadmin4` just fine!

This does not work with a patched nix version (doesn't matter whether its 2.18.4 or newer)

So the patch to fix the build-dir seems to have broken at least pgadmin.

### Notify maintainers

@roberth 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
I've had this issue too. It doesn't just hang, in goes into disk sleep. Meaning you can't kill it, not even by shutting down the system.

**Comment by gador** [comment]
Yes! Not even `sudo kill -9 $PID` does help. Only restarting the whole system works. I'm trying to disect, where it actually goes wrong, but I believe it has something to do with the new `chroot` safety feature from  https://github.com/NixOS/nix/commit/0e4baff868047f065749c9ba73556bf8d90fabf7

**Comment by gador** [comment]
I confirmed my suspicion.
I have the following diff on the current `2.24.10` version
```diff
diff --git a/src/libstore/unix/build/local-derivation-goal.cc b/src/libstore/unix/build/local-derivation-goal.cc
index 2a09e3dd4..baeae54f8 100644
--- a/src/libstore/unix/build/local-derivation-goal.cc
+++ b/src/libstore/unix/build/local-derivation-goal.cc
@@ -509,11 +509,11 @@ void LocalDerivationGoal::startBuilder()
     /* Create a temporary directory where the build will take
        place. */
     topTmpDir = createTempDir(settings.buildDir.get().value_or(""), "nix-build-" + std::string(drvPath.name()), false, false, 0700);
-#if __APPLE__
+//#if __APPLE__
     if (false) {
-#else
-    if (useChroot) {
-#endif
+//#else
+//    if (useChroot) {
+//#endif
         /* If sandboxing is enabled, put the actual TMPDIR underneath
            an inaccessible root-owned directory, to prevent outside
            access.
```
which basically reverts https://github.com/NixOS/nix/commit/0e4baff868047f065749c9ba73556bf8d90fabf7
and used this as `nix.package` in a VM to test the build. I then ran `nix build github:nixos/nixpkgs/nixos-unstable#pgadmin4 --rebuild -L` and it _did work_ !

Doing this on any newer nix version without the above diff fails. So this is exactly the reason. `yarn` (for whatever reason) does either not like the subdirectory `/build` (which is unlikely) or the permission `700`.

Not sure how to tackle this problem, though. It is unlikely that `pgadmin` is the only victim here. And that you have to restart the whole system to kill a bunch of `node yarn install ...` processes isn't cool either.

@thufschmitt any idea here? Also, in light of ZHF #352882 a bit of a pressing problem

**Comment by roberth** [comment]
I haven't seen this before. I'm not much of a darwin expert, but here's my thoughts.

The directory names got longer, and unix sockets have a very restricted length on darwin. Some software does not expect a long(er) TMPDIR and may not handle that correctly, leading to undefined/strange behavior.

Although `strace` didn't reveal much, it might be worth comparing a hanging run to a successful run, especially if the execution is deterministic, which makes a semi-automated comparison much easier.

Is each node in this chain of directories that makes up TMPDIR readable (+rx) by the sandboxed build process? If not, would it be ok to make it readable only by the build user? This is slightly less secure, but might be ok.

This could probably be fixed on either side, Nix or yarn. Could you open an issue on the https://github.com/NixOS/nix repo for the regression? It'd help to get more eyes on this. (I'd move the issue if it was clearly one or the other, fwiw)

Another practical note: @thufschmitt has changed jobs and isn't contributing actively to the Nix/NixOS ecosystem anymore.

**Comment by FliegendeWurst** [comment]
> I haven't seen this before. I'm not much of a darwin expert, but here's my thoughts.

I have the same issue on Linux. There is nothing really suspicous in `lsof` either.
```
pnpm    191060 nixbld1 cwd       DIR   0,36       40    407492 /build/source (deleted)
pnpm    191060 nixbld1 rtd       DIR  259,2     4096  41432658 /
... lots of /nix/store paths, anon_inode io_uring, pipes ...
```

**Comment by Shawn8901** [comment]
As I don't see it explicitly named: I think it is definitely not yarn only (pnpm is shown in the prev. comment). I had observed similar issue, when trying to build stalwart-mail.webadmin when trying to reproduce a recent build failure.
The said package uses npm (same symptoms: never finished, 0 activity, can't kill -9, shutdown blocked).

I was running a maybe 1-2 weeks old nixos-unstable.
Let me know if I should try to reproduce and gather some Infos.

**Comment by gador** [comment]
@roberth thanks for chiming in. This is a _non_  darwin issue. As it is only present when the code is executed on an non `APPLE` system. 
I can build `pgadmin` just fine on `2.24.9` on `aarch64-darwin`. My "patch" above just disables the `chroot` condition for all systems 

Also, even worse, when trying to build `pgadmin` on linux: Due to being unkillable, the system will not reboot nor shutdown! It will hang forever on a watchdog issue and the system needs to be powered down by hand. This can be a huge issue for bare-metal servers

**Comment by gador** [comment]
> Is each node in this chain of directories that makes up TMPDIR readable (+rx) by the sandboxed build process? 

AFAIS, yes. 
```
ls -la /tmp
drwx------  3 root  root     3 Nov  5 06:21 nix-build-pgadmin-8.11.drv-1
sudo ls -la /tmp/nix-build-pgadmin-8.11.drv-1
drwx------  5 nixbld1 nixbld  7 Nov  5 06:21 build
sudo ls -la /tmp/nix-build-pgadmin-8.11.drv-1/build
total 64
drwx------ 5 nixbld1 nixbld     7 Nov  5 06:21 .
drwx------ 3 root    root       3 Nov  5 06:21 ..
drwxr-xr-x 3 nixbld1 nixbld     3 Nov  5 06:21 .cache
-rw------- 1 nixbld1 nixbld 35469 Nov  5 06:21 env-vars
drwxr-xr-x 9 nixbld1 nixbld    19 Nov  5 06:21 source
drwxr-xr-x 3 nixbld1 nixbld     3 Nov  5 06:21 v8-compile-cache-1000
-rw-r--r-- 1 nixbld1 nixbld   160 Nov  5 06:21 .yarnrc
sudo ls -la /tmp/nix-build-pgadmin-8.11.drv-1/build/.cache/yarn/v6
[...]
drwxr-xr-x    3 nixbld1 nixbld    3 Nov  5 06:21 npm-yarn-audit-html-4.0.0-dc04c9cf83e758fd6d9efad8c96df1fc8c4bf30c
drwxr-xr-x    3 nixbld1 nixbld    3 Nov  5 06:21 npm-yauzl-2.10.0-c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9
drwxr-xr-x    3 nixbld1 nixbld    3 Nov  5 06:21 npm-yocto-queue-0.1.0-0294eb3dee05028d31ee1a5fa2c556a6aaf10a1b
drwxr-xr-x    3 nixbld1 nixbld    3 Nov  5 06:21 npm-yocto-queue-1.1.1-fef65ce3ac9f8a32ceac5a634f74e17e5b232110
drwxr-xr-x    3 nixbld1 nixbld    3 Nov  5 06:21 npm-zustand-4.5.4-63abdd81edfb190bc61e0bbae045cc4d52158a05
drwxr-xr-x    2 nixbld1 nixbld    2 Nov  5 06:21 .tmp
```

> This could probably be fixed on either side, Nix or yarn. Could you open an issue on the https://github.com/NixOS/nix repo for the regression?

done

**Comment by blurgyy** [comment]
Also seeing this on a x86-64 linux machine running hydra, the command `npm ci` runs forever and `kill -9` does nothing.

**Comment by gador** [comment]
@datafoo when was your last known good commit?

**Comment by gador** [comment]
I investigated further and I narrowed it down to something between these commits:

broken 4c2fcb090b1f3e5b47eaa7bd33913b574a11e0a0 2024-10-18 [1809433](https://hydra.nixos.org/eval/11809433)
good a3c0b3b21515f74fd2665903d4ce6bc4dc81c77c 2024-10-14 [1809364](https://hydra.nixos.org/eval/1809364)

Tested as the input for a NixOS VM with a fixed `nix.package = pkgs.nixVersions.nix_2_24;` and always trying to build `nix build -L --rebuild github:nixos/nixpkgs/nixos-unstable#pgadmin4` 
With the broken commit, this stalls. With the good commit this continues on and builds. Since the derivation to build is fixed (and so are all the inputs e.g. yarn or node), this obviously has something to do with the build environment. And this changed between those commits.

I haven't found an easy culprit with `git --diff`, yet.

**Comment by Garmelon** [comment]
On my system, manually (as in: typing it into my terminal) running `npm ci` in a repo also hangs the `npm ci` process. The build is not running through `nix`. The process is un-sigkill-able.

**Comment by donovanglover** [comment]
Possibly related:

- https://github.com/npm/cli/issues/4028#issuecomment-2441942581

Does [downgrading to npm 10.3.0](https://github.com/npm/cli/issues/7868#issuecomment-2453542554) work for you?

**Comment by donovanglover** [comment]
Bun and Deno seem to not be affected.

**Comment by gador** [comment]
@Garmelon I think this is an unrelated bug. What I described here is a bug in a build process from nix, which always uses the same `node` and `yarn` version and fails or succeeds depending on the host machine's NixOS version. This is why I suspect `nix` to be involved.
@donovanglover I cannot rule out a random hang on the build process. But as of know it consistently works or consistently fails depending on the commit of the build machine

**Comment by K900** [comment]
This is a kernel bug, specifically with io_uring.

**Comment by rbozan** [comment]
> This is a kernel bug, specifically with io_uring.
> 
> Edit: source: [lore.kernel.org/io-uring/2024110620-stretch-custodian-0e7d@gregkh/T#u](https://lore.kernel.org/io-uring/2024110620-stretch-custodian-0e7d@gregkh/T/#u)

I'm using this as a workaround for now:

```nix
boot.kernelPackages = pkgs.linuxPackages_latest;
```

**Comment by gador** [comment]
> This is a kernel bug, specifically with io_uring.
> 
> Edit: source: https://lore.kernel.org/io-uring/2024110620-stretch-custodian-0e7d@gregkh/T/#u

Thanks! I'm bisecting right now (which takes a long time), but since I'm rebuilding the kernel right now, this sounds about right!

**Comment by gador** [comment]
Bisect is done:
```
0e4c64ff9cef5800c6a3f4838c66a918ceb61398 is the first bad commit
commit 0e4c64ff9cef5800c6a3f4838c66a918ceb61398
Author: K900 <me@0upti.me>
Date:   Thu Oct 17 17:12:25 2024 +0300

    linux_6_6: 6.6.56 -> 6.6.57

 pkgs/os-specific/linux/kernel/kernels-org.json | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

So, yes, this is a kernel bug

**Comment by gador** [comment]
@K900 shall we revert this specific commit?

**Comment by K900** [comment]
No, a proper fix should be in the next batch of stable kernels.

**Comment by gador** [comment]
Ok. I'll keep the issue open until the next batch landed and for everyone looking for a quick fix https://github.com/NixOS/nixpkgs/issues/353709#issuecomment-2458957910 seems like a viable option (or reverting, or not updating)

**Comment by Tofandel** [comment]
Do you have a `/usr/bin/ldd` file in NixOS? This is what determines if yarn uses node's getReport (which is buggy and make the process hang, and not randomly, it's a realiable bug).

**Comment by Tofandel** [comment]
It's hardcoded in yarn berry: https://github.com/yarnpkg/berry/blob/f59bbf9f3828865c14b06a3e5cc3ae284a0db78d/packages/yarnpkg-core/sources/nodeUtils.ts#L26

Btw if you are not using yarn berry (which is 95% of the users of yarn) then getReport is not used at all either

**Comment by mweinelt** [comment]
What irks me is that this issue mixes up apparent darwin sandboxing issues and linux kernel regressions into one, because they both block the build in a similiar fashion apparently.

**Comment by gador** [comment]
> What irks me is that this issue mixes up apparent darwin sandboxing issues and linux kernel regressions into one, because they both block the build in a similiar fashion apparently.

Its not _darwin_ sandbox issues, but _linux_ and the linux kernel regression is the root cause. I closed the `nix` issues as soon as the root cause was known. If you read the comments it should become apparant, but I can add an "edit" to the original post for clarity

**Comment by Garmelon** [comment]
For completeness, there's also https://github.com/nodejs/node/issues/55587

**Comment by Eveeifyeve** [comment]
This occurs in a pnpm build in modrinth-app.

**Comment by Frontear** [comment]
+1 occurs in `jellyfin-web`, as reported by @SeamusFD. Haven't tested myself if rolling the kernel back/pushing ahead fixes it, but I can expect it probably does given this drv breaks for the same reasons as everything else here.

**Comment by Garmelon** [comment]
> 6.12.5

As far as I understand, the bug is not present in non-lts kernels, i.e. 6.11 or later.

It should hopefully be fixed in lts kernels 6.1.116 and 6.6.60.

**Comment by dkumza** [comment]
> > 6.12.5
> 
> As far as I understand, the bug is not present in non-lts kernels, i.e. 6.11 or later.
> 
> It should hopefully be fixed in lts kernels 6.1.116 and 6.6.60.

thanks i added latestet kernel to my config and I have no issues ! 
`boot.kernelPackages = pkgs.linuxPackages_latest;`

**Comment by gador** [comment]
A comment on this workaround: This only works for _non_ ZFS configs. The zfs config (at least the stable ones) rely on a kernel <= 6.11 so the only workaround here is a revert/rollback until 6.6.60 is released

**Comment by Ramblurr** [comment]
> A comment on this workaround: This only works for _non_ ZFS configs. The zfs config (at least the stable ones) rely on a kernel <= 6.11 

Wow thanks for this, I was just fighting with my config trying to make this work.

I see zfs_unstable supports 6.11 now, but when I tried to enable that on a test machine:

```
  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_6_11;
  boot.zfs.package = lib.mkForce pkgs.zfs_unstable;

# output:
error: Package ‘zfs-kernel-2.2.6-6.11.5’ in /nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source/pkgs/os-specific/linux/zfs/generic.nix:216 is marked as broken, refusing to evaluate.
``

I'm not sure why it's pulling in 2.2.6 when zfs_unstable is 2.3, but anyways that is off-topic here probably.

> .. so the only workaround here is a revert/rollback until 6.6.60 is released

Rolling back to LTS 6.1 isn't an option unfortunately. Do I understand right kernel 6.6.56 is the last-known-good? 

What would be the proper way to revert/rollback to 6.6.56?

**Comment by gador** [comment]
The way I did it, was to selectively revert the update commits on my own `nixpkgs` fork:
```
commit 614327d436779e271ad599da3673dd9a2a8df873
Author: Florian Brandes <florian.brandes@posteo.de>
Date:   Wed Nov 6 14:08:02 2024 +0100

    Revert "linux_6_6: 6.6.56 -> 6.6.57"

    This reverts commit 0e4c64ff9cef5800c6a3f4838c66a918ceb61398.

commit 4b7bc628a6d0bba9a94748d0acae013b5ee8dfff
Author: Florian Brandes <florian.brandes@posteo.de>
Date:   Wed Nov 6 14:07:53 2024 +0100

    Revert "linux_6_6: 6.6.57 -> 6.6.58"

    This reverts commit c0b43de177e6cc1ac03f6b6bab64b8f4aecce996.

commit 0fa02103f6b272d5c7c8d1be7bff70c8aa52b1f8
Author: Florian Brandes <florian.brandes@posteo.de>
Date:   Wed Nov 6 14:05:28 2024 +0100

    Revert "linux_6_6: 6.6.58 -> 6.6.59"

    This reverts commit 05b2afe1c8e9b43d05ca9f4b6bf6dba1222bc99a.
```

And of course you can revert your NixOS config to an older generation which worked and wait for the kernel update

**Comment by Eveeifyeve** [comment]
> This occurs in a pnpm build in modrinth-app.

As said before this is happening with pnpm not just yarn.

**Comment by K900** [comment]
Kernel 6.6.60 is merged now with a fix.
