### ISSUE TITLE
Flatpak broken after last update (OSTree/Curl error)

### ISSUE THREAD

**Issue by Radeox** [NixOS/nixpkgs#353878]
### Describe the bug
I'm on nixos-unstable of two of my pc's with similar hardware and the share pretty much the configuration but on one of them I get this error since this morning:

```bash
$ flatpak update
Looking for updates…

Nothing to do.
**
OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
Aborted (core dump creato)
```

### Steps To Reproduce
1. Enable flatpak service
2. Try any flatpak command (update/install/ecc...)

### Expected behavior
Flatpak should work normally like on the other pc

### Extra
My configuration if it could provide more context.

https://github.com/Radeox/dotfiles/tree/main/nixos

I'm using [nix-flatpak](https://github.com/gmodena/nix-flatpak) but I've already tested the configuration without the module without any luck.

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
This will be fixed with https://github.com/NixOS/nixpkgs/pull/353087.

**Comment by Gliczy** [comment]
Fixed on master.
