### ISSUE TITLE
`xcrun` shadows macOS development tools in `/usr/bin` in development shells

### ISSUE THREAD

**Issue by emilazy** [NixOS/nixpkgs#353875]
After the Darwin rework, `xcrun` is present in the standard environment. This means that executables like `/usr/bin/git` and `/usr/bin/python3` call out to it, and since we deliberately ignore `/usr/bin` in our `xcrun`, they fail even if the user has developer tools installed. This results in a bad user experience for Nix development shells.

We could fix this by, e.g., implementing a fallback where, if we cannot find a tool but otherwise would have found it in `/usr/bin` (indicating that `/usr/bin` is on the `$PATH`, so we’re presumably not in a hermetic build but some kind of development shell), we instead search for the tool inside a native toolchain and execute that.

cc @NixOS/darwin-core

**Comment by winterqt** [comment]
> We could fix this by, e.g., implementing a fallback where, if we cannot find a tool but otherwise would have found it in `/usr/bin` (indicating that `/usr/bin` is on the `$PATH`, so we’re presumably not in a hermetic build but some kind of development shell), we instead search for the tool inside a native toolchain and execute that.

This sounds fine to me, but maybe add a toggle to force the hermetic behavior even if we're in a dev shell?

**Comment by reckenrode** [comment]
I have a patch to fix this. It only falls back to the native toolchain if `/usr/bin` is in the path.

> This sounds fine to me, but maybe add an env var to force the hermetic behavior even if we're in a dev shell?

Even if `/usr/bin` is on the path? I think it would be surprising behavior that `/usr/bin/ls` would work but not `/usr/bin/git`.
