### ISSUE TITLE
Build failure: openvdb (dependency of bambu-studio, incompatible boost versions)

### ISSUE THREAD

**Issue by 2403772980ygy** [NixOS/nixpkgs#353863]
### Steps To Reproduce

1. build openvdb

### Build log

I think that the following lines is representative enough.

```
       last 25 log lines:
       > -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
       > -- Configuring for OpenVDB Version 12.0.0
       > -- Configuring for OpenVDB ABI Version 12
       > -- ----------------------------------------------------
       > -- ------------- Configuring OpenVDBCore --------------
       > -- ----------------------------------------------------
       > CMake Warning (dev) at openvdb/openvdb/CMakeLists.txt:112 (find_package):
       >   Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
       >   --help-policy CMP0167" for policy details.  Use the cmake_policy command to
       >   set the policy and suppress this warning.
       >
       > This warning is for project developers.  Use -Wno-dev to suppress it.
       > 
       > CMake Error at /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
       >   Could NOT find Boost: Found unsuitable version "1.79.0", but required is at
       >   least "1.80" (found
       >   /nix/store/p0a0h9zwmgqxn1vhl7ang0zxrrl1x60j-boost-1.79.0-dev/include, found
       >   components: iostreams regex)
       > Call Stack (most recent call first):
       >   /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
       >   /nix/store/irwcgpm8csj7br49jih6kdpqkaqya3vf-cmake-3.30.4/share/cmake-3.30/Modules/FindBoost.cmake:2409 (find_package_handle_standard_args)
       >   openvdb/openvdb/CMakeLists.txt:112 (find_package)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/fvig2bd6hfrh8njaplb84ia2f18h7mf7-openvdb-12.0.0.drv'.
```

### Notify maintainers

@guibou

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241030.d565bce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/9aq8y2y2v47626vy3nm5wmy5x2a39bdp-source`

---

**Comment by FliegendeWurst** [comment]
It builds on `master` and probably unstable too. Are you using any overrides?

**Comment by gautaz** [comment]
Same issue here.

I have just updated my flake which uses the nixpkgs master branch:

```console
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/169f5639532ae118919a2a384eef2661e1cf6228?narHash=sha256-YQ06F86gDzDlLU3xVbM49HNhqPV24TVGeGopemKDAmI%3D' (2024-11-05)
  → 'github:nixos/nixpkgs/71f04a2e549681c3690951418af046414a715b46?narHash=sha256-CFSH2IdTKbH6KR3cT4NmJABxqFkUFQ3Dmn3LopHjWWE%3D' (2024-11-06)
```

The commit https://github.com/NixOS/nixpkgs/commit/71f04a2e549681c3690951418af046414a715b46 dates back to less than an hour ago...

**Comment by 2403772980ygy** [comment]
> Same issue here.
> 
> I have just updated my flake which uses the nixpkgs master branch:
> 
> ```
> • Updated input 'nixpkgs':
>     'github:nixos/nixpkgs/169f5639532ae118919a2a384eef2661e1cf6228?narHash=sha256-YQ06F86gDzDlLU3xVbM49HNhqPV24TVGeGopemKDAmI%3D' (2024-11-05)
>   → 'github:nixos/nixpkgs/71f04a2e549681c3690951418af046414a715b46?narHash=sha256-CFSH2IdTKbH6KR3cT4NmJABxqFkUFQ3Dmn3LopHjWWE%3D' (2024-11-06)
> ```
> 
> The commit [71f04a2](https://github.com/NixOS/nixpkgs/commit/71f04a2e549681c3690951418af046414a715b46) dates back to less than an hour ago...

Despite the commit being dated back to (two hours, I guess), the last update for openvdb happened to be about 4 days ago. I don't think that package was broken for so long and remain unnoticed.

Nix does provide boost up to version 1.85, and I don't quite know which version matches boost.

**Comment by 2403772980ygy** [comment]
> It builds on `master` and probably unstable too. Are you using any overrides?

This is a dependency of bambu-studio, which overrides version of boost to 1.79

I guess this is why.

**Comment by gautaz** [comment]
Ah, that would explain, in fact this failure occurs during the build of orca-slicer which is a fork of bambu-studio AFAICT...

Good catch @2403772980ygy!

**Comment by Scrumplex** [comment]
I have opened #354038 to fix this. I was able to build orca-slicer without overriding openvdb, so it might not be needed anymore?

**Comment by 06kellyjac** [comment]
Yeah I also looked at this the other day and was confused because the default `boost` had been updated for quite a while on unstable.

it might be nice if any remaining packages which override openvdb add a prefix to the `pname` so it's clearer when reporting issues e.g. `bambu-studio-openvdb`
