### ISSUE TITLE
Package request: juicefs

### ISSUE THREAD

**Issue by liberodark** [NixOS/nixpkgs#353994]
**Project description**

 JuiceFS is a distributed POSIX file system built on top of Redis and S3. 

**Metadata**

* homepage URL: https://juicefs.com/
* source URL: https://github.com/juicedata/juicefs
* license: Apache-2.0 license 
* platforms: windows, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by svrana** [comment]
This is packaged as juicefs.
