### ISSUE TITLE
nginx: Check syntax also at nix evaluation time

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#35395]
https://github.com/NixOS/nixpkgs/pull/24664 added config file syntax checking using `nginx -t` in `preStart` of the systemd unit.

In https://github.com/NixOS/nixpkgs/pull/24664#issuecomment-366448476 @volth suggested to check it also at nix-evaluation time, thus failing even earlier. An [example](https://github.com/NixOS/nixpkgs/pull/32062) was provided for how to do it for Varnish, we'd have to do the same for nginx.

I think this is a great idea; this issue tracks doing that.

CC users from the other issue: @Mic92 @domenkozar @joachifm @volth

**Comment by volth** [comment]
I would also check ```sslCertificate``` at nix evaluation time issuing a warning if the certificate is expiring soon and panicking if it is already expired.

**Comment by nh2** [comment]
> I would also check `sslCertificate` at nix evaluation time issuing a warning if the certificate is expiring soon and panicking if it is already expired.

That sounds pretty impure though, does that even work when building in the sandbox, where time is stopped?

**Comment by volth** [comment]
I am not sure the check has any sense beyond the ```nixops```-like cases, say on Hydra or on the CI bot.
So it could be skipped in sandbox

**Comment by nh2** [comment]
> Or the time might be passed as an argument of the evaluation

This would certainly work.

I'd go step by step though: Keeping this issue about syntax validity (I think we all want that), and if we want time checks, put that into a different issue.

**Comment by edolstra** [comment]
Do you actually mean evaluation time, or build time? https://github.com/NixOS/nixpkgs/pull/32062 is a build time check.

Note BTW that build-time configuration file checks often break if they refer to directories or users that don't exist yet. E.g. `httpd -t` fails if the user account mentioned in `User` doesn't exist yet.

**Comment by Mic92** [comment]
And dns or hostnames in case of nginx

**Comment by nh2** [comment]
> Do you actually mean evaluation time, or build time?

Sorry, build time. Will update the description.

> Note BTW that build-time configuration file checks often break if they refer to directories or users that don't exist yet. E.g. httpd -t fails if the user account mentioned in User doesn't exist yet.

> And dns or hostnames in case of nginx. This could work in special cases, if the user takes care of it, but not in general. In other words, I could imagine an optional function that takes the configuration as input and returns a new store paths while checking the syntax - users would have to enable this feature and it would be required to disable sandboxes for this to work.

Good points. Let's make it optional then.

I also found that nginx supports two kinds of validity checks:

```
# /nix/store/rzssgadfwrsbclpksvcy1zx39m50ry7r-nginx-1.12.2/bin/nginx -t -c /nix/store/lk94mvs3pv1ns9qv7zg0fhm07c7sic25-nginx.conf
nginx: [alert] could not open error log file: open() "/nix/store/rzssgadfwrsbclpksvcy1zx39m50ry7r-nginx-1.12.2/logs/error.log" failed (30: Read-only file system)
nginx: the configuration file /nix/store/lk94mvs3pv1ns9qv7zg0fhm07c7sic25-nginx.conf syntax is ok
2018/06/27 17:03:54 [emerg] 31414#31414: open() "/nix/store/rzssgadfwrsbclpksvcy1zx39m50ry7r-nginx-1.12.2/logs/nginx.pid" failed (30: Read-only file system)
nginx: configuration file /nix/store/lk94mvs3pv1ns9qv7zg0fhm07c7sic25-nginx.conf test failed
```

Notice how it does do syntax checks (`syntax is ok`), and configuration sensibleness checks (`test failed`).

Also funny how without further configuration it seems to think `error.log` and `nginx.pid` are supposed to be in the nix store (of course that can't work).

**Comment by Mic92** [comment]
There could be a hook in switch-to-configuration that is runs in a mount namespace with the updated thew `/etc` mounted but without any other sandbox, which performs those syntax checks. This hook then could run before any old service is stopped.

**Comment by nh2** [comment]
> Notice how it does do syntax checks (syntax is ok), and configuration sensibleness checks (test failed).

I've had a quick look into the nginx source code; it doesn't right now give a super easy way to check only the syntax, and the function that parses the config (`ngx_conf_parse()`) cannot be called without initialisation of some other, rather global nginx stuff.

**Comment by Mic92** [comment]
I can easily imagine this, since every module can add additional keywords to the configuration.

**Comment by volth** [comment]
may this help ?
https://github.com/yandex/gixy

**Comment by nh2** [comment]
> may this help ?
> https://github.com/yandex/gixy

Hmm, this catches the most extreme syntax errors (like forgetting `}`), but doesn't seem to catch more basic syntax errors (forgetting `;`) and also doesn't seem to have any idea over what directives nginx supports (e.g. you can change `listen` to `listena` and it's happy with that.

It feels like we need to urge upstream to get a "pure" syntax checking feature in to do this well.

**Comment by globin** [comment]
Handled by gixy.

**Comment by gepbird** [comment]
I had a few instances where silly mistakes like forgetting a `;` or writing incorrect `try_files` directives took down nginx, because the configuration built fine, but `nginx -t` failed in the pre start. Seems like there are some cases that are not handled by gixy.

If `nginx -t` is still that impure that it's not feasible to use it at build time after gixy, we could revisit running it during switch-to-configuration.
