### ISSUE TITLE
Update request: libreoffice-fresh 24.8.0.3 → 24.8.2.1

### ISSUE THREAD

**Issue by AchmadFathoni** [NixOS/nixpkgs#353947]
- Package name: libreoffice-fresh
- Latest released version: 24.8.2.1

- Current version on the unstable channel: 24.8.0.3
- Current version on the stable/release channel: 24.2.5.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@K900 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
The maintainer of the package is @7c6f434c, not me.
