### ISSUE TITLE
Build failure: blender

### ISSUE THREAD

**Issue by Andy3153** [NixOS/nixpkgs#353961]
### Steps To Reproduce

1. build blender

### Build log
https://pastebin.com/DjzCSWxg

### Additional context

As far as I can see it's a different error from what #351902 is fixing and what #353861 is reporting

### Notify maintainers
@amarshall
@veprbl 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`
 ```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CrabbyDisk** [comment]
I am also having trouble building blender. The logs aren't identical but it seems to be failing at the same stage.
