### ISSUE TITLE
Package request: bruno-cli

### ISSUE THREAD

**Issue by greg-hellings** [NixOS/nixpkgs#353903]
The existing [bruno package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix) includes only the graphical application. There is also a CLI interface that is available from the same source.

The current build process does create the `bru` executable at `node_packages/.bin/bru`, but it only includes a reference to the source folder calling its run command. I tried to create a PR to package the CLI executable in a separate output, but I could not figure out how to get an executable version that wasn't just a symlink back to the original file.

**Metadata**

* homepage URL: https://www.usebruno.com/
* source URL:https://github.com/usebruno/bruno/tree/main/packages/bruno-cli
* license: mit
* platforms: all

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mattpolzin** [comment]
This duplicates https://github.com/NixOS/nixpkgs/issues/335270 although it does say a bit more about it that could be good in a comment on the original ticket.
