### ISSUE TITLE
Update request: ollama 0.3.12 → 0.4.0

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#354099]
- Package name: ollama
- Latest released version: [0.4.0](https://github.com/ollama/ollama/releases/tag/v0.4.0)

- Current version on the unstable channel: 0.3.12
- Current version on the stable/release channel: 0.1.38

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@abysssol @dit7ya @elohmeier 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
Resolved by #354969
