### ISSUE TITLE
Build failure: vte-0.78.0 on Darwin

### ISSUE THREAD

**Issue by Aehmlo** [NixOS/nixpkgs#354092]
### Steps To Reproduce

1. `nix build github:NixOS/nixpkgs/4aa36568d413aca0ea84a1684d2d46f55dbabad7#vte`

This fails for me on Darwin but works on NixOS. Looks to me like it's unrelated to #354048, but I haven't gotten very far.

### Build log

[Output of `nix-store -l /nix/store/xsqdbmcwa4rddh4a2qvnjq618hnzm16d-vte-0.78.0.drv`](https://gist.github.com/Aehmlo/027d104c8aa9e7f2ddba79dda38aafc2).

### Additional context

I am rebuilding my `home-manager` configuration using the Nixpkgs revision named above (4aa36568d413aca0ea84a1684d2d46f55dbabad7) with `programs.bash.enableVteIntegration = true;`

### Notify maintainers

@astsmtl @antono 

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.5.0, macOS 14.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(user): `""`
 - channels(root): `"nixpkgs-24.05"`
 - nixpkgs: `/nix/store/pq1m6x5ilkm3s841g0z0vyrqvmbxc21v-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aehmlo** [comment]
Looks like #353204 may fix this; will confirm once that propagates to `nixos-unstable`.

**Comment by khaneliman** [comment]
It does, I'm using an overlay in the meantime:
```nix
_: _final: prev: {
  # TODO: remove after https://github.com/NixOS/nixpkgs/pull/353204 is available
  vte = prev.vte.overrideAttrs (oldAttrs: rec {
    version = "0.78.1";
    src = prev.fetchFromGitLab {
      domain = "gitlab.gnome.org";
      owner = "GNOME";
      repo = "vte";
      rev = version;
      hash = "sha256-dVCvf4eTIJlrSzG6xLdKU47N9uAtHDwRrGkWtSmqbEU=";
    };
    nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ prev.fast-float ];
    patches = oldAttrs.patches or [ ] ++ [
      # build: Add fast_float dependency
      # https://gitlab.gnome.org/GNOME/vte/-/issues/2823
      (prev.fetchpatch {
        name = "0003-build-Add-fast_float-dependency.patch";
        url = "https://gitlab.gnome.org/GNOME/vte/-/commit/f6095fca4d1baf950817e7010e6f1e7c313b9e2e.patch";
        hash = "sha256-EL9PPiI5pDJOXf4Ck4nkRte/jHx/QWbxkjDFRSsp+so=";
      })
      (prev.fetchpatch {
        name = "0003-widget-termprops-Use-fast_float.patch";
        url = "https://gitlab.gnome.org/GNOME/vte/-/commit/6c2761f51a0400772f443f12ea23a75576e195d3.patch";
        hash = "sha256-jjM9bhl8EhtylUIQ2nMSNX3ugnkZQP/2POvSUDW0LM0=";
      })
      (prev.fetchpatch {
        name = "0003-build-Use-correct-path-to-include-fast_float.h.patch";
        url = "https://gitlab.gnome.org/GNOME/vte/-/commit/d09330585e648b5c9991dffab4a06d1f127bf916.patch";
        hash = "sha256-YGVXt2VojljYgTcmahQ2YEZGEysyUSwk+snQfoipJ+E=";
      })
    ];
  });
}
```
