### ISSUE TITLE
Kubernetes broken

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#35403]
## Issue description
#35330 broke building Kubernetes.

```
Detected go version: go version go1.10 linux/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.
```

`all-packages.nix` probably just needs a `go = go_1_9;`.

Edit: Please do make sure the K8s tests work.

**Comment by volth** [comment]
seems like the versions are compared lexicographicaly somewhere

**Comment by volth** [comment]
Another distro just removed the version check:
https://github.com/clearlinux-pkgs/kubernetes/blob/724a51af37ec57615cf5c2f77392b4919fe5888c/build.patch

**Comment by xeji** [comment]
Some Arch people suggested this patch
https://github.com/kubernetes/kubernetes/commit/fc37221db5d08eb9553273ad6202a2557cfde131.patch

I haven't tried it yet

**Comment by volth** [comment]
@xeji It seems to be already merged upstream 12 days ago: https://github.com/kubernetes/kubernetes/pull/58207

**Comment by xeji** [comment]
@volth successful build with that patch. will run the tests later

**Comment by xeji** [comment]
failed to build the tests in nixos/tests/kubernetes on master. looks like a separate issue, the tests are broken somehow.

I'll go ahead and make a PR for the version check patch anyway.
