### ISSUE TITLE
localsend: goes black after sending a file

### ISSUE THREAD

**Issue by 0n-s** [NixOS/nixpkgs#354044]
### Describe the bug
LocalSend's window fades to black after a file is sent.

### Steps To Reproduce
1. Go into the Send menu.
2. Pick a file & send it to another device.
3. Click Done.

### Expected behavior
I should be sent back to the Send menu.

### Screenshots
![A screenshot of the LocalSend window, all black](https://github.com/user-attachments/assets/ee780d78-c7a1-4680-937e-cf2c42362f43)

### Additional context
Not reproducible with Flatpak (tested).

### Notify maintainers

@sikmir
@linsui
@pandapip1

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 0n-s** [comment]
Nothing in the [changelog](https://github.com/localsend/localsend/blob/main/app/assets/CHANGELOG.md) seems to indicate that's the case…

But if it is, linking that PR here: https://github.com/NixOS/nixpkgs/pull/353481

**Comment by 0n-s** [comment]
Tested the PR on my end. It is indeed fixed with that version.

**Comment by Pandapip1** [comment]
This is because we had to move to unstable version because the version of Flutter that localsend was using was dropped from nixpkgs. It's likely that at some point a commit was introduced that caused this bug and a later commit fixed it. But no tag actually had said bug.

**Comment by 0n-s** [comment]
> This is because we had to move to unstable version because the version of Flutter that localsend was using was dropped from nixpkgs. It's likely that at some point a commit was introduced that caused this bug and a later commit fixed it. But no tag actually had said bug.

Ah, that would make sense.
