### ISSUE TITLE
Build failure: cemu

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#354078]
### Steps To Reproduce

1. build `cemu` (nixpkgs 4aa36568d413aca0ea84a1684d2d46f55dbabad7/latest `nixos-unstable`)

### Build log

```
cemu> /nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: /nix/store/09465jfdjm4lkddh5w1ih6q95vbmpmjh-glslang-15.0.0/lib/libglslang.so.15: error adding symbols: DSO missing from command line
cemu> collect2: error: ld returned 1 exit status
cemu> ninja: build stopped: subcommand failed.
error: builder for '/nix/store/icv7kx17adxsd6xcq1w50dcmyxs788h7-cemu-2.0-92.drv' failed with exit code 1;
```

### Additional context

N/A

### Notify maintainers

@zhaofengli @baduhai @AndersonTorres

### Metadata

---

nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241029.807e915`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20240920_ca3fc169`
 - nixpkgs: `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
Builds failing on Hydra too: https://hydra.nixos.org/build/277249337/nixlog/1

**Comment by baduhai** [comment]
#353870, which was just merged a few hours ago, fixes this.
