### ISSUE TITLE
Update nixpkgs.nix for Nix 2.0

### ISSUE THREAD

**Issue by kballard** [NixOS/nixpkgs#35413]
## Issue description

`nixpkgs.nix` is still 1.11.6, and `nixpkgs.nixUnstable` is still a 2.0 pre-release. Nix 2.0 was released yesterday but there's no way to upgrade to it.

### Steps to reproduce

Just look at https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix/default.nix.

**Comment by copumpkin** [comment]
See https://github.com/NixOS/nixpkgs/pull/34636

**Comment by vcunat** [comment]
We have open PR, let's close issue.
