### ISSUE TITLE
Package request:  lxqt-wayland-session

### ISSUE THREAD

**Issue by wineee** [NixOS/nixpkgs#354141]
**Project description**

The LXQt team announces the release of LXQt 2.1.0,  supports 7 Wayland sessions (with Labwc, KWin, Wayfire, Hyprland, Sway, River and Niri), has two Wayland back-ends in lxqt-panel (one for kwin_wayland and the other general)...
https://lxqt-project.org/release/2024/11/05/release-lxqt-2-1-0/

**Metadata**

* homepage URL: https://github.com/lxqt/lxqt-wayland-session
* source URL:  https://github.com/lxqt/lxqt-wayland-session
* license:   GNU Lesser General Public License v2.1
* platforms: unix, linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

@NixOS/lxqt

**Comment by JohnRTitor** [comment]
So LQXT is... @fufexan new Hypr DE?
