### ISSUE TITLE
Document the "overrides" attribute

### ISSUE THREAD

**Issue by chreekat** [NixOS/nixpkgs#35426]
I see this attribute used everywhere, and I have even cargo-culted it myself a few times. However, I don't know what it does, how it works, or how to find out. The only mention in the docs is in the Haskell section, where it is used without explanation. Can someone point me to implementation or elucidation?

Thanks. :)

**Comment by jcrben** [comment]
You're talking about the overrides attribute and not the function right? I'm not sure about an overrides attribute, but the overrides function is described athttps://github.com/NixOS/nixpkgs/blob/e349ccc77febd45abbd14be14f7de123ec4a4da2/nixos/doc/manual/configuration/customizing-packages.xml#L34 (https://nixos.org/nixos/manual/index.html#sec-customising-packages). Doesn't seem to be discussed in the Nix Package Manager Guide tho.

Could you link to this Haskell section you're talking about?

**Comment by chreekat** [comment]
The first example I could find quickly is in section 9.5.3.2. I believe if one greps around the sources, however, one will find a bunch of other examples, and not just for Haskell. (Sorry for my phone-brevity.)

**Comment by chreekat** [comment]
Found it: it's documented at https://nixos.org/nixpkgs/manual/#miscellaneous-topics

**Comment by jcrben** [comment]
That link doesn't go anywhere for me, and I couldn't find the docs on this. 

You might consider using a permanent link to the source tree in case anyone else stumbles upon this asking the question - you can hit the `Y` key to automatically get the last revision...

**Comment by chreekat** [comment]
Strange that the link doesn't work for you. Here's another that goes directly to the subsection:

https://nixos.org/nixpkgs/manual/#how-to-build-with-profiling-enabled

And here's the quote: "Every Haskell package set takes a function called overrides that you can use to manipulate the package as much as you please. "

In effect, `overrides` is to a haskell package set (i.e. `nixos.haskellPackages` or `nixos.haskell.packages.${compiler}`) as `overlays` is to nixpkgs itself. I think.

**Comment by chreekat** [comment]
For the record, I intend to see about patching up the Haskell section of the nixpkgs docs (section 9.5) once I've finished refactoring the particular package I'm working on.
