### ISSUE TITLE
k3s: flaky k3s multi-node test

### ISSUE THREAD

**Issue by rorosen** [NixOS/nixpkgs#354211]
### Describe the bug

The `multi-node` test runs into a timeout and fails without an apparent reason lately. It seems that failures aren't related to a specific k3s version but happens with any version on unstable.  

### Steps To Reproduce
1. `nix-build -A k3s_1_28.tests.multi-node`
2. `nix-build -A k3s_1_29.tests.multi-node`
3. `nix-build -A k3s_1_30.tests.multi-node`
4. `nix-build -A k3s_1_31.tests.multi-node`

### Expected behavior
The test passes reliably or fails with a reason.

### Additional context

If the test runs into a timeout, it prints error messages like the following:

```
agent # [ 1193.513817] k3s[793]: E0923 09:28:49.589402     793 kuberuntime_manager.go:1272] "Unhandled Error" err="container &Container{Name:test,Image:test.local/pause:local,Command:[socat TCP4-LISTEN:8000,fork EXEC:echo server],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{memory: {{20971520 0} {<nil>} 20Mi BinarySI},},Requests:ResourceList{memory: {{20971520 0} {<nil>} 20Mi BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-6bnql,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Never,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod test-nnnqf_default(eb0c063a-fd84-47d0-8cbf-f369882083fc): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars"
```

At least notified in:
- https://github.com/NixOS/nixpkgs/pull/343296
- https://github.com/NixOS/nixpkgs/pull/352182

### Notify maintainers

@NixOS/k3s

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by superherointj** [comment]
I suggest a new title for this issue:

> k3s: flaky k3s multi-node test
