### ISSUE TITLE
Setup hooks can be called multiple times (but inconsistently)

### ISSUE THREAD

**Issue by mutability** [NixOS/nixpkgs#354220]
### Describe the bug

If a particular package occurs more than once in the dependency graph, it's possible for the package setup hook to be called more than once, but not consistently (depends on the exact order that the graph is traversed).

This seems to be a bug in `pkgs/stdenv/generic/setup.sh` which attempts to deduplicate the dependency lists and call the setup hook exactly once, but gets it wrong in edge cases.

### Steps To Reproduce

flake to demonstrate the problem:

```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:  
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        setupHookScript = pkgs.writeScript "dependency-bug-hook.sh" ''
          let foo_counter=''${foo_counter:-0}+1
          echo "setup hook got called $foo_counter times" >&2
        '';
      in {
        packages = rec {
          setupHook = pkgs.makeSetupHook {
            name = "dependency-bug-hook";
          } setupHookScript;

          foo = pkgs.stdenv.mkDerivation {
            name = "dependency-bug-foo";
            dontUnpack = true;
            buildPhase = "mkdir $out";
            propagatedBuildInputs = [ setupHook ];
          };
            
          bar = pkgs.stdenv.mkDerivation {
            name = "dependency-bug-bar";
            dontUnpack = true;
            buildPhase = "mkdir $out";
          };

          # these two derivations _should_ be equivalent but are not

          okay = pkgs.stdenv.mkDerivation {
            # Works okay: setup hook is called exactly once
            name = "dependency-bug-okay";
            dontUnpack = true;
            buildInputs = [ bar setupHook foo ];
            buildPhase = "mkdir $out";
          };
          
          broken = pkgs.stdenv.mkDerivation {
            # Broken: setup hook is called twice
            name = "dependency-bug-broken";
            dontUnpack = true;
            buildInputs = [ setupHook foo bar ];
            buildPhase = "mkdir $out";
          };

        };
      }
    );
}
```

`nix build -L .#okay` reports:

```
building '/nix/store/2a23kamlgcxyhv52yfbf5was7akgakrg-dependency-bug-okay.drv'...
dependency-bug-okay> setup hook got called 1 times
dependency-bug-okay> Running phase: patchPhase
```

`nix build -L .#broken` reports

```
building '/nix/store/yl00yls645f7q9h0zf1r0qnnkpfgpzax-dependency-bug-broken.drv'...
dependency-bug-broken> setup hook got called 1 times
dependency-bug-broken> setup hook got called 2 times
dependency-bug-broken> Running phase: patchPhase
```

### Expected behavior

The setup hook should be called exactly once regardless of the order of dependencies.

### Additional context

I think this is the culprit:
https://github.com/NixOS/nixpkgs/blob/33970d0070b5b21acfc3a9b2b41830b4003d1b80/pkgs/stdenv/generic/setup.sh#L674-L679

This wants to match on a package name surrounded by spaces, but the first and last packages in the array won't have leading/trailing spaces.

It might be sufficient to just embed spaces around the expansion i.e. `" ${!varSlice-} "` (but I haven't had a chance to test this yet, given that it causes the world to rebuild)

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-40-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixpkgs-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by RossComputerGuy** [comment]
CC @NixOS/stdenv

**Comment by Artturin** [comment]
> It might be sufficient to just embed spaces around the expansion i.e. `" ${!varSlice-} "` (but I haven't had a chance to test this yet, given that it causes the world to rebuild)

`stdenv.override { setupScript = ./pkgs/stdenv/generic/setup.sh; }`
