### ISSUE TITLE
Build failure: pkgsCross.aarch64-multiplatform.samba

### ISSUE THREAD

**Issue by erdnaxe** [NixOS/nixpkgs#354261]
Cross-compiling samba on NixOS 24.05 works fine, but it is currently broken on master.

### Steps To Reproduce

1. build *pkgsCross.aarch64-multiplatform.samba*
2. the package build, but then nix errors out.

### Build log

```
error: output '/nix/store/sg3faxa8i2xfnvpls8bw6kbaqxscd4g3-samba-aarch64-unknown-linux-gnu-4.20.4' is not allowed to refer to the following paths:
         /nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7
```

### Additional context

Building on nixpkgs master a46925097143c5535a814c0d9ca53b29fb2a5d1d.

### Notify maintainers

@aneeshusa 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.6, NixOS, 24.11 (Vicuna), 24.11.20241102.7ffd9ae`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: aarch64-linux, i686-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jayay** [comment]
I can confirm this. I'm on Fedora aarch64 and trying to cross-compile NixOS for riscv64. It seems that the host Python is wired into the build output.

**Comment by Majiir** [comment]
x86 cross-compiling for armv7l is also affected, and now on NixOS 24.11 too.

**Comment by jayay** [comment]
There is a fix (https://github.com/NixOS/nixpkgs/pull/357988) on master now but not in 24.11 yet.
