### ISSUE TITLE
Build failure: libspelling-0.4.4

### ISSUE THREAD

**Issue by nbCloud91** [NixOS/nixpkgs#354260]
### Steps To Reproduce

1. build libspelling-0.4.4.drv

### Build log

```
error: builder for '/nix/store/qm0k33bdcx2645a20nvy5ag9x4m14qgs-libspelling-0.4.4.drv' failed with exit code 1;
       last 13 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/dclg16g3xmwa4c3447w6kymbz5nacwvj-source
       > source root is source
       > Running phase: patchPhase
       > applying patch /nix/store/89j44jyqjbk5a4k6am7jrmqsxvzchn55-source/build-aux/flatpak/libspelling_text_commits.patch
       > patching file lib/spelling-text-buffer-adapter.c
       > Hunk #1 succeeded at 52 with fuzz 2 (offset -14 lines).
       > Hunk #2 FAILED at 452.
       > Hunk #3 FAILED at 661.
       > Hunk #4 succeeded at 775 with fuzz 2 (offset -7 lines).
       > Hunk #5 FAILED at 864.
       > Hunk #6 FAILED at 992.
       > 4 out of 6 hunks FAILED -- saving rejects to file lib/spelling-text-buffer-adapter.c.rej
       For full logs, run 'nix log /nix/store/qm0k33bdcx2645a20nvy5ag9x4m14qgs-libspelling-0.4.4.drv'.
```

### Additional context

Apostrophe is pulling libspelling as dependency in my config.

### Notify maintainers

@bobby285271
@chuangzhu 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bobby285271** [comment]
> applying patch /nix/store/89j44jyqjbk5a4k6am7jrmqsxvzchn55-source/build-aux/flatpak/libspelling_text_commits.patch

Thanks for the issue, this patches actually comes from apostrophe and the build is fixed in https://github.com/NixOS/nixpkgs/commit/39c8fd647f2976d022cf01fac2d64a2136e0ac8e. You can track the fix in https://nixpk.gs/pr-tracker.html?pr=353328
