### ISSUE TITLE
Update request: Vagrant 2.4.1 → 2.4.3

### ISSUE THREAD

**Issue by JuanoD** [NixOS/nixpkgs#354352]
- Package name: Vagrant
- Latest released version: [2.4.3](https://github.com/hashicorp/vagrant/releases/tag/v2.4.3)
- Current version on the unstable channel: 2.4.1
- Current version on the stable/release channel: 2.4.1
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@tylerjl 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by tylerjl** [comment]
As noted in #362117, I'd appreciate someone kicking the tires on the updated package on Darwin to affirm it works as expected (building, starting a box, ideally a Windows RDP based provisioner to ensure that works)
