### ISSUE TITLE
Yaml timestamp strings are no longer quoted

### ISSUE THREAD

**Issue by JManch** [NixOS/nixpkgs#354336]
### Describe the bug
The recent remarshal update #348098 has changed how yaml timestamp strings are generated. Given the following Nix expression:
```nix
{ time = "22:30:00"; }
```
On 18536bf04cd71abd345f9579158841376fdd0c5a it's generated as
```yaml
time: '22:30:00'
```
Whilst on 4aa36568d413aca0ea84a1684d2d46f55dbabad7 it's generated as
```yaml
time: 22:30:00
```

I generate my Home Assistant config using Nix and this breaks the configuration in various places. For example, Adaptive Lighting expects a string of the form HH:MM:SS for `sunset_time` but, because it's unquoted in the generated yaml, Home Assistant interprets it as a timestamp and converts it to seconds since midnight.

I've tried quoting the timestamps in Nix but this just results in the yaml generator double quoting the strings. 

### Steps To Reproduce
```nix
with import <nixpkgs> { };
let
  before =
    (import (fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/18536bf04cd71abd345f9579158841376fdd0c5a.tar.gz";
    }) { }).formats.yaml { };

  after =
    (import (fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/4aa36568d413aca0ea84a1684d2d46f55dbabad7.tar.gz";
    }) { }).formats.yaml { };

  testCase = {
    time = "22:30:00";
  };
in
pkgs.runCommand "yaml-timestamp-test" { } ''
  cat ${before.generate "before.yaml" testCase} >> $out
  cat ${after.generate "after.yaml" testCase} >> $out
''
```

### Expected behavior
That it's possible to generate the following yaml with Nix:
```yaml
time: '22:30:00'
```

### Notify maintainers

@mweinelt 

### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Upstream changed the YAML implementation from PyYAML to ruamel-yaml, and that caused other fixtures of ours to complain. But neither ours nor their fixtures noticed this.

The yaml formatter in nixpkgs works by calling `json2yaml` on the JSON output of the given object. Ideally we can create a small reproducer for upstream, so that they can adjust the YAML output to resolve this.

**Comment by mweinelt** [comment]
Filed here: https://github.com/remarshal-project/remarshal/issues/52
