### ISSUE TITLE
python bibtexparser broken on unstable

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#35430]
## Issue description
python-bibtexparser is missing dependencies  

[ future pyparsing ];

### Steps to reproduce
nix-env -iA nixos.python3Packages.bibtexparser 

## Technical details

 - system: `"x86_64-linux"`                                                                                                                                                                      
 - host os: `Linux 4.14.20, NixOS, 18.03pre129076.831ef4756e3 (Impala)`                                                                                                                          
 - multi-user?: `yes`                                                                                                                                                                            
 - sandbox: `yes`                                                                                                                                                                                
 - version: `nix-env (Nix) 1.11.16`                                                                                                                                                              
 - channels(IITaudio): `"nixos-18.03pre129076.831ef4756e3, telegram-cli-2016-03-23, machine-0.9.0, gitlab-runner-1.10.4, california-0.4.0, entr-3.6, tmuxp-1.2.2, keybase-20170209.17b641d, kbfs-20170209.d1db463, non-2016-12-07, go-sct-20160529-1d6b5e0, freecad-0.16, antimony-0.9.2, librecad-2.1.3, lemonbar-xft-unstable-2016-02-17, pencil-2.0.21, python3.5-qnotero-1.0.0, ruby-2.3.3, gimp-2.8.20, chromium-56.0.2924.87, nix-repl-1.11.7-2016-02-28, gparted-0.26.1, screen-4.5.1, vmpk-0.5.1, a2jmidid-8, platformio, teensyduino-1.6.12, teensy-loader-cli-2.1, blender-2.78c, unetbootin-613, mediainfo-0.7.91, xournal-0.4.8, zip-3.0, graphviz-2.40.1, ffmpeg-3.2.4, vlc-2.2.4, okular-16.12.2, pdfmod-0.9.1, green-pdfviewer-nightly-2014-04-22, android-sdk-25.2.3, android-studio-2.2.3.0, zathura-with-plugins-0.3.7, openjdk-8u121b13, android-ndk-r10e, virtualbox-5.1.14, R-3.3.2-wrapper, aspell-dict-en-2016.06.26-0"`
 - channels(gitlab-runner): `"nixpkgs-18.03pre117013.aebdc892d6"`                                                                                                                                
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`                                                                                                                                          
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by nico202** [comment]
cc: @FRidh

**Comment by dotlambda** [comment]
Can you please try if this is fixed in staging?

**Comment by nico202** [comment]
```bash
git checkout origin/staging
nix-env -f . -iA python3Packages.bibtexparser
```

works
