### ISSUE TITLE
Package request: twig-language-server

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#354492]
**Project description**
Language server for Twig templates. 

**Metadata**

* homepage URL: https://github.com/kaermorchen/twig-language-server
* source URL: https://github.com/kaermorchen/twig-language-server
* license: none
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by genga898** [comment]
I built a derivation of it, could you test and see if it works
```nix
{
  lib,
  fetchFromGitHub,
  buildNpmPackage,
}:

buildNpmPackage rec {
  pname = "twig-language-server";
  version = "0.5.1";

  src = fetchFromGitHub {
    owner = "kaermorchen";
    repo = pname;
    rev = "refs/tags/v${version}";
    hash = "sha256-bW0siZudzqk/4XgVH6nNCOrpJ6WHTCZoHJC+aXnE5mM=";
  };

  npmDepsHash = "sha256-zbMjfdIXQf6oz6em0vkyvroijCb2MUioZjvZjkbuKc8=";

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    mkdir -p $out/node_modules
    mkdir -p $out/packages
    chmod +x $out/bin
    chmod +x $out/node_modules

    cp -R ./node_modules/twig-language-server $out/bin
    cp -R ./packages $out/
    cp -R ./node_modules/* $out/node_modules
    runHook postInstall
  '';

}
```
