### ISSUE TITLE
Build failure: cross aarch64 sudo

### ISSUE THREAD

**Issue by danielbarter** [NixOS/nixpkgs#354544]
### Steps To Reproduce

1. `nix build .#pkgsCross.aarch64-multiplatform.sudo`

### Build log
https://gist.github.com/danielbarter/6798a3d245271cb164c8abdb65dff1d4

### Additional context
Breakage is very recent. I have a CI job running which cross builds a minimal system daily from master, and error only appeared today.
### Metadata

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by danielbarter** [comment]
god, debuging this is a nightmare because https://github.com/NixOS/nixpkgs/blob/fce5494864ddbe25b10f484811a053012d188e1b/pkgs/tools/security/sudo/default.nix#L42 seems to break `nix-shell`! Commenting it out, I can get an environment where the build fails

**Comment by Gliczy** [comment]
Sorry for the regression.
Can you please try with https://github.com/NixOS/nixpkgs/pull/354575?
