### ISSUE TITLE
Update request: zfs_unstable 2.3.0-rc2 → 2.3.0-rc3

### ISSUE THREAD

**Issue by jpalharini** [NixOS/nixpkgs#354578]
- Package name: zfs_unstable
- Latest released version: 2.3.0-rc3

- Current version on the unstable channel: 2.3.0-rc2
- Current version on the stable/release channel: 2.2.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@amarshall 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jpalharini** [comment]
[Full release notes](https://github.com/openzfs/zfs/releases/tag/zfs-2.3.0-rc3)

This adds support for Direct IO (O_DIRECT), which can increase performance significantly in NVMe drives.

I'm happy to tackle this over the weekend (if I can figure out how, since I'm still a beginner in Nix-land).

**Comment by jpalharini** [comment]
> Note that 2.3.0-rc2 already has direct IO.

You are right! Thanks for pointing that out.

**Comment by Mic92** [comment]
merged.
