### ISSUE TITLE
Package request: nix-forecast

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#354590]
**Project description**

Check the forecast for today's Nix builds

**Metadata**

* homepage URL: https://github.com/getchoo/nix-forecast
* source URL: https://github.com/getchoo/nix-forecast
* license: mpl2
* platforms: unix, linux, darwin, ...

note the repo has an existing flake :)

  (also, pinging author @getchoo)

**Comment by getchoo** [comment]
Thanks for the interest :)
