### ISSUE TITLE
home-assistant extraComponents "discord" fails at runtime because of missing "pkg_resources" dependency

### ISSUE THREAD

**Issue by itepastra** [NixOS/nixpkgs#354790]
### Describe the bug
When `"discord"` is added to the extraComponents of the home-assistant service, and I try to add the discord integration on the web interface I get the following error:
```
Nov 09 16:03:29 nuOS hass[20873]: 2024-11-09 16:03:29.651 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration discord: No module named 'pkg_resources'
```

### Steps To Reproduce
1. enable `services.home-assistant` with `extraComponents = [ "discord" ];`
2. in the UI of home assistant, add the discord integration
3. observe the log

### Expected behavior
I expect the discord integration to ask me for my credentials and then work

### Screenshots
![image](https://github.com/user-attachments/assets/d2bfa57f-a40c-4dd1-bca0-26950127ba16)

### Additional context
I'm on nixos commit `54aac082a4d9bb5bbc5c4e899603abfb76a3f6d6`

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
Can you post the full logs?

**Comment by dotlambda** [comment]
The use of `pkg_resources` in nextcord was removed in https://github.com/nextcord/nextcord/commit/5d2eff1810edd76359b66f37f731537a520c3d2c#diff-f5864302ac363947ef8ca95ee6a8e2735184345661739d1573a5e60b0396e0d5L5 but that hasn't made it to a release yet.
