### ISSUE TITLE
Build failure: neovide 0.13.3 on aarch64-darwin

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#354889]
### Steps To Reproduce

1. Build `neovide` on `aarch64-darwin`

### Build log

https://gist.github.com/lunik1/cb0a4574df88ff0fa3e127d6153f3ab5

### Notify maintainers

@ck3d 

### Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Theaninova** [comment]
Also fails on x86_64

**Comment by pitkling** [comment]
This seems to be fixed by #354914 and can probably be closed? At least for me, `neovide` from `nixpkgs-unstable` builds again on all my platforms (`x86_64-darwin`, `aarch64-darwin`, `x86_64-linux`).

**Comment by Theaninova** [comment]
Can confirm, builds on x86_64-linux

**Comment by ck3d** [comment]
fixed on master
