### ISSUE TITLE
(nix.package = pkgs.nixUnstable) running basic nix-shell or nix-repl commands causes user to be logged out

### ISSUE THREAD

**Issue by vitiral** [NixOS/nixpkgs#35485]
## Issue description
Running [section 6.5 of nixpills](https://nixos.org/nixos/nix-pills/our-first-derivation.html#idm140737316376752) or even `nix-shell -p nix-info --run "nix-info -m"` causes the current user to be logged out.

### Steps to reproduce
```
$ nix-repl --version
nix-repl (Nix) 1.11.16
$ nix-shell -p nix-info --run "nix-info -m"
# ... user session crashes and I have to log back in
```

Let me know what logs you want. I didn't see anything in `journalctl -xe` that jumped out to me

## Technical details

> Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
> results.

I cannot do this, as my user is logged out when I do

**Comment by vitiral** [comment]
it is happening when I use `nixos-rebuild switch --upgrade` as well

**Comment by vitiral** [comment]
Also, I am using `nix.package = pkgs.nixUnstable;` and am using the new `nix` binary.

**Comment by vitiral** [comment]
Also, I am using `nix.package = pkgs.nixUnstable;` and am using the new `nix` binary.

Removing those lines, I can now get the technical details:

```
$ nix-shell -p nix-info --run "nix-info -m"                                                       1 ↵
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.20, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by hedning** [comment]
I'm unable to reproduce this at a4f433c03ccba743727e550edee80653ea3ad2ca.

Does this work to get the nix-info out (as it's hard to debug without the information)?
```
nix run nixpkgs.nix-info --command nix-info -m
```

**Comment by vitiral** [comment]
After switching back and running the suggested command:

```
# nix run nixpkgs.nix-info --command nix-info -m | tee output.log 
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.20, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by vitiral** [comment]
`nix-shell -p nix-info --run "nix-info -m"` no longer causes the logout behavior...

This doesn't either:
```
$ nix repl
nix-repl> :l <nixpkgs>
Added 8486 variables.

nix-repl> d = derivation { name = "myname"; builder = "${coreutils}/bin/true"; system = builtins.currentSystem; }

nix-repl> :b d
these derivations will be built:
  /nix/store/8qffj0frsd2ns9dcjskk0ga7d78b5rxr-myname.drv
building '/nix/store/8qffj0frsd2ns9dcjskk0ga7d78b5rxr-myname.drv'...
builder for '/nix/store/8qffj0frsd2ns9dcjskk0ga7d78b5rxr-myname.drv' failed to produce output path '/nix/store/b783ggvxbq41ksn2hj548fx5j7np73iq-myname'
error: build of '/nix/store/8qffj0frsd2ns9dcjskk0ga7d78b5rxr-myname.drv' failed
```

I have _no idea_ what was wrong

**Comment by lheckemann** [comment]
I suspect you might have put your user in the nixbld group. You *really shouldn't* do this — the nixbld group is for users that are used to execute builds, and nix will happily kill all these users' processes before starting a build.

**Comment by vitiral** [comment]
@lheckemann you're right... I did do that as well! That's totally it then!

The weird thing is that I _though_ I correctly removed that and did `nixos-rebuild switch` + reboot -- so I didn't think that that could be what was causing this. But it sounds like it totally is!
