### ISSUE TITLE
Package request: `tinyfetch`

### ISSUE THREAD

**Issue by luislve17** [NixOS/nixpkgs#354873]
**Project description**

Fetch tool to display system info
> "A simple fetch in C which is tiny and fast.. it takes 0.001 to 0.004s to fetch"

**Metadata**

* homepage URL: https://github.com/abrik1/tinyfetch
* source URL: https://github.com/abrik1/tinyfetch
* license: mit
* platforms: unix, linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by luislve17** [comment]
![image](https://github.com/user-attachments/assets/54e4cf4d-ce01-4b3b-903c-d0fa90718e32)

**Comment by pagedMov** [comment]
Opened a PR at  [#354927](https://github.com/NixOS/nixpkgs/pull/354927)

While that's being merged, [here](https://gist.github.com/pagedMov/2b4c95ec0c505936d31c97243b756020) is the derivation I wrote for it.
