### ISSUE TITLE
mitmproxy broken on unstable

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#35499]
## Issue description
Mitmproxy fails to build on unstable, due to a dependency issue.

### Steps to reproduce
- use unstable channel
- add mitmproxy to configuration.nix
- rebuild

> installing
/tmp/nix-build-python3.6-mitmproxy-unstable-2017-10-31.drv-0/source/dist /tmp/nix-build-python3.6-mitmproxy-unstable-2017-10-31.drv-0/source
> Processing ./mitmproxy-3.0.0-py3-none-any.whl
> Requirement already satisfied: passlib<1.8,>=1.6.5 in /nix/store/xfhw63awpz1cchnpfdwrf51yaya5sx1r-python3.6-passlib-1.7.1/lib/python3.6/site-packages (from mitmproxy==3.0.0)
> Requirement already satisfied: brotlipy<0.8,>=0.5.1 in /nix/store/7gy80zfzfbpd7s8a5ax5lahr8ha6849n-python3.6-brotlipy-0.7.0/lib/python3.6/site-packages (from mitmproxy==3.0.0)
> Requirement already satisfied: h2<4,>=3.0 in /nix/store/x6k1wixpaqr7hnii3ja7yk89fk5fnq9d-python3.6-h2-3.0.1/lib/python3.6/site-packages (from mitmproxy==3.0.0)
> Requirement already satisfied: hyperframe<6,>=5.0 in /nix/store/m3061m7c5hlg3b7g69z1wmg8ipkh5p19-python3.6-hyperframe-5.1.0/lib/python3.6/site-packages (from mitmproxy==3.0.0)
> Collecting pyOpenSSL<17.4,>=17.2 (from mitmproxy==3.0.0)
>  Could not find a version that satisfies the requirement pyOpenSSL<17.4,>=17.2 (from mitmproxy==3.0.0) (from versions: )
> No matching distribution found for pyOpenSSL<17.4,>=17.2 (from mitmproxy==3.0.0)
builder for ‘/nix/store/1r81mqcgswyixkliz674xrsz87y6dp1p-python3.6-mitmproxy-unstable-2017-10-31.drv’ failed with exit code 1
> cannot build derivation ‘/nix/store/w59529h909fa5z2idxss9wk5zlrgzh7a-system-path.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/5ky8sy4dw599k6zhgifyljm0ycfqpwnl-nixos-system-dagNix--18.03pre129076.831ef4756e3.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/5ky8sy4dw599k6zhgifyljm0ycfqpwnl-nixos-system-dagNix--18.03pre129076.831ef4756e3.drv’ failed

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.4, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
 - nix-channel: `https://nixos.org/channels/nixos-unstable`

### Device details
 - device: `20DLCTO1WW ThinkPad S1 Yoga 12`
 - cpu: `Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz`
 - gpu: `Intel Corporation HD Graphics 5500 (rev 09)`

**Comment by d4g** [comment]
@fpletz @kamilchm

**Comment by d4g** [comment]
Could be related to #34775

**Comment by FRidh** [comment]
Closing because of #35514
