### ISSUE TITLE
Update request: proton-pass 1.23.1 → 1.24.1

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#355097]
- Package name: Proton-Pass
- Latest released version: 1.24.1

- Current version on the unstable channel: 1.23.1
- Current version on the stable/release channel: N/A

- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@daniel-fahey 

-----

Note for maintainers: Please tag this issue in your PR.

A new version became available at the same time, I am not able to sign in to the previous version. 

I made a report @ https://github.com/NixOS/nixpkgs/issues/355095

**Comment by daniel-fahey** [comment]
I'm not a maintainer of the `proton-pass` package, see https://github.com/NixOS/nixpkgs/blob/029d6ef8b6d4183c8209f67a4bccf5d3c396cc8d/pkgs/by-name/pr/proton-pass/package.nix#L57-L61
