### ISSUE TITLE
Update request: Ironwail 0.7.0  → 0.8.0

### ISSUE THREAD

**Issue by lavenderdotpet** [NixOS/nixpkgs#355049]
- Package name: Ironwail
- Latest released version:

- Current version on the unstable channel: 0.7.0
- Current version on the stable/release channel: 0.7.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@necrophcodr @afh 

-----

Note for maintainers: Please tag this issue in your PR.

---

link to the latest GitHub release
https://github.com/andrei-drexler/ironwail/releases/tag/v0.8.0

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by necrophcodr** [comment]
@lavenderdotpet thanks for the ping, I hadn't noticed the new release just yet (but you were also quite quick to spot that!), but the PR is also ready to go. Now comes the waiting part!

**Comment by lavenderdotpet** [comment]
> @lavenderdotpet thanks for the ping, I hadn't noticed the new release just yet (you were also quite quick to spot that!), but the PR is also ready to go. Now comes the waiting part!

the dev posted about it in the Quake Mapping Discord and I hang out there a good bit 

if you are in that server and curious here is a direct link to the message https://discord.com/channels/464531227509260291/491346068886519828/1305248409309024400 

link to the server if you are not there https://discord.gg/Bqftq7wxqe
