### ISSUE TITLE
nixos/tests: broken for docker-tools and kubernetes

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#35505]
## Issue description

nixos/tests for docker-tools and kubernetes fail to build on current master b7a6c54851f09f24077c28713af94d4ba099ae38 

It looks like this is caused by dockerTools.tarsum being broken under go 1.10.

### Steps to reproduce

On current master (with go 1.10):

``nix-build  '<nixpkgs/nixos/tests/docker-tools.nix>' ``

Fails with:
```
...
building path(s) ‘/nix/store/dfdf7vjqnxs1j39b5iddjypqvacm9dlz-docker-layer-bash’
Adding contents...
Adding /nix/store/9xg3d7r173zzybgh8v4lhf3zcf0wx51g-bash-4.4-p12
Packing layer...
Computing layer checksum...
builder for ‘/nix/store/5hm53q5azg46p06vg9jn8yyryqdf24jp-docker-layer-bash.drv’ failed with exit code 1
...
```

Similar error for kubernetes test:
``nix-build '<nixpkgs/nixos/tests/kubernetes/default.nix>' -A dns``

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.20, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment]
Here's an example of what I think is wrong with dockerTools.tarsum. Given a tar file on stdin, it should print a checksum on stdout but results in an error:

```
$ /nix/store/imqk28cx0kc0y3br3qycqicq7yc8j4qm-tarsum < /tmp/test.tar
archive/tar: missed writing 399 bytes
```

**Comment by srhb** [comment]
Any idea what the Discard is doing? If I comment it out, it builds, but I'm not sure the hashes produced are correct.

	if _, err = io.Copy(ioutil.Discard, ts); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

**Comment by srhb** [comment]
@lethalman might know.

**Comment by srhb** [comment]
Oh, yeah, getting rid of that is definitely nonsense. Every hash will be the same. :)

**Comment by xeji** [comment]
@srhb : makes sense, let docker upstream take care of this.
