### ISSUE TITLE
Build failure: matugen

### ISSUE THREAD

**Issue by smb374** [NixOS/nixpkgs#355078]
### Steps To Reproduce

1. build *matugen* on unstable with `nix-shell -p matugen`

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/1nn8yqkcgds1frzkh4hxhbk3d0ifv2wd-source.drv':
         specified: sha256-SN4m0ka5VHLIQYTszhlCIB+2D+nyWMzJM5n5bZdkG/I=
            got:    sha256-l623fIVhVCU/ylbBmohAtQNbK0YrWlEny0sC/vBJ+dU=
error: 1 dependencies of derivation '/nix/store/ksbmi4ar7nzjd88zgq4py9a7kx9bkz27-matugen-2.4.0.drv' failed to build
```

### Notify maintainers

@LamprosPitsillos

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ben9986** [comment]
@nartsisss looks like upstream re-released V2.4.0 which changed the hash after you updated the package. Updating the source hash fixes it for me, builds fine

**Comment by nartsisss** [comment]
You're right, will fix it soon. Thanks
<img width="327" alt="image" src="https://github.com/user-attachments/assets/7b8d3764-ef14-417d-9194-1dc147b73e45">

**Comment by kmath313** [comment]
@NobbZ  are you able to merge this fix to unstable as well?

**Comment by NobbZ** [comment]
As #355091 went to `master`, I have no clue what you are asking.

**Comment by Ben9986** [comment]
> @NobbZ are you able to merge this fix to unstable as well?

You just need to wait for it to make its way through the build system there's not a way to force it. Its almost at unstable: 
https://nixpk.gs/pr-tracker.html?pr=355091

**Comment by kmath313** [comment]
Thanks Ben, I don't know how things progressed through the build system.
