### ISSUE TITLE
KDENetwork-Filesharing does not work as expected, share tab added but never loads

### ISSUE THREAD

**Issue by mlncn** [NixOS/nixpkgs#355008]
### Describe the bug

After installing KDE Network Filesharing, the share tab of folder properties in Dolphin shows a spinning gear … forever.

### Steps To Reproduce

1. Add `kdePackages.kdenetwork-filesharing` in `environment.systemPackages = with pkgs; [` and `nixos-rebuild switch`
2. Open Dolphin and right-click a folder to choose "Properties"
3. Press the Share tab

### Expected behavior

Folder sharing across networks works out of the box in KDE's default Dolphin file manager ***or*** there are clear instructions on how to enable it.

### Screenshots

![Screenshot_20241110_103125](https://github.com/user-attachments/assets/629d3f16-fa00-46f2-b665-c08c5c981e9b)

### Additional context

Fresh NixOS with Plasma install on a Framework 16 (AMD).  Not a VM.

Newbie first time doing anything with Nix.  Foolish, i know, but going pretty well so far.

### Notify maintainers

@K900 

### Metadata

`nix-shell -p nix-info --run "nix-info -m"`
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.05 (Uakari), 24.05.6122.080166c15633`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mlncn** [comment]
Oh also i meant to mention that i have not yet installed https://github.com/NixOS/nixos-hardware/tree/master/framework

Related issues are:

#290515 
#24913

I see in https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/kde/gear/kdenetwork-filesharing/default.nix#L6 that there is a comment:

```
  # We can't actually install samba via PackageKit, so let's not confuse users any more than we have to
  extraCmakeFlags = ["-DSAMBA_INSTALL=OFF"];
```

unfortunately for *this* user i remain confused even after reading this comment :joy:

Does it mean that if i install samba and/or do something here - https://nixos.wiki/wiki/Samba - that it will start working?

Would be very nice if what exactly should be done were somehow exposed after install on the share tab, or in a message during install, and/or on the package documentation.

**Comment by K900** [comment]
The nixos-hardware profiles should not be relevant here. I'm guessing you just need to enable Samba, and I'm guessing we should do that by default.

**Comment by mlncn** [comment]
[Searching for samba](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=samba) shows both **samba** and **samba4Full** (with the latter having a slightly larger package list) but the "source" link for both goes to https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/servers/samba/4.x.nix#L256 so i don't know how to further evaluate (nor do i know, clearly, how they get into the package listing with a set of dependencies!).  cc @aneeshusa

**Comment by K900** [comment]
I am looking into it, please give me some time.

**Comment by mlncn** [comment]
@K900 Here we are with `samba` added to the packages— a much clearer error, at least!

![Screenshot_20241110_115004](https://github.com/user-attachments/assets/3ba116c9-3054-4880-a01f-c89f212520ec)

**Comment by K900** [comment]
https://github.com/NixOS/nixpkgs/pull/355031 should fix everything I could find here, specifically:
- the page not loading
- the hint not displaying correctly
- the hint not telling you what to actually do
- adding user to group failing (still gets overridden on activation if `mutableUsers = false`, but that's a feature)
- smbpasswd failing

I can actually share things properly now.

**Comment by mlncn** [comment]
You fixed this bug faster than the files i wanted to share this way transferred to a thumb drive (my fallback approach)!

Is there any practical way for me to use/test the pull request directly from my system?  Found [Add instructions for reviewer in PR template by tobiasBora · Pull Request #242733 · NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/pull/242733), but i don't think it offers (proposed) guidance relevant to trying in in-use systems?

**Comment by K900** [comment]
You can set your nixpkgs channel/flake input to the branch in my fork.
