### ISSUE TITLE
gnirehtet

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#35515]
> This project provides reverse tethering over adb for Android: it allows devices to use the internet connection of the computer they are plugged on. It does not require any root access (neither on the device nor on the computer). It works on GNU/Linux, Windows and Mac OS.

https://github.com/Genymobile/gnirehtet

**Comment by symphorien** [comment]
I opened a PR packaging gnirehtet: https://github.com/NixOS/nixpkgs/pull/42373
