### ISSUE TITLE
Build failure: gitbutler

### ISSUE THREAD

**Issue by matyas-cimbulka** [NixOS/nixpkgs#355157]
### Steps To Reproduce

1. nix build --impure nixpkgs#gitbutler

### Build log

[Gist](https://gist.github.com/matyas-cimbulka/5ad393b33872801d71da31df0808ed79)

### Notify maintainers
@getchoo
@techknowlogick 

### Metadata

---
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by phsb5321** [comment]
Is there a solution for gitbutler breaking on NixOS?
