### ISSUE TITLE
versionCheckHook messed up with colored ascii art?

### ISSUE THREAD

**Issue by Aleksanaa** [NixOS/nixpkgs#355114]
> I just cannot get the versioncheckhook working with testkube. When running 'kubectl-testkube version' it displays some colored ASCII art before displaying the version so I think this might mess up the version parser.

_Originally posted by @mathstlouis in https://github.com/NixOS/nixpkgs/pull/353751#discussion_r1835858570_

**Comment by mathstlouis** [comment]
Sorry my mistake. It looks like 'kubectl-testkube version' runs an https call to 'https://api.github.com/repos/kubeshop/testkube/releases/latest' and fails when unreachable, not displaying current version.
Not a nix bug. Closing the issue.
