### ISSUE TITLE
`angryipscanner`: not actually broken? 

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#355412]
### Describe the bug
`angryipscanner` both builds and runs on my system with `NIXPKGS_ALLOW_BROKEN=1`

### Steps To Reproduce
1. Set `NIXPKGS_ALLOW_BROKEN=1`
2. build `angryipscanner`
3. run `ipscan`

### Expected behavior
N/A

### Screenshots

![image](https://github.com/user-attachments/assets/816fb6dc-767e-424c-8a4a-172d25134ae3)

### Additional context
N/A

### Notify maintainers

@kylesferrazza
@totoroot

### Metadata

---

 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.0pre20241101_2e5759e3`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kylesferrazza** [comment]
Ah, yep. We merged #338234 but never un-set the broken flag.
