### ISSUE TITLE
Package request: PolyGlot 

### ISSUE THREAD

**Issue by RowanBee** [NixOS/nixpkgs#355496]
**Project description**

PolyGlot is a tool that is designed to help in the design, creation, and publication of constructed languages, or "conlangs."

**Metadata**

* homepage URL: http://draquet.github.io/PolyGlot/index.html
* source URL: https://github.com/DraqueT/PolyGlot
* license: MIT
* platforms: Windows, Mac, Linux (deb)

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
There is a PR to add the package: #316541
