### ISSUE TITLE
kube-proxy is broken by iptables 1.6.1 -> 1.6.2

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#35544]
## Issue description
This is mostly a reminder to follow up on what upstream decides to do.

Since iptables 1.6.2, iptables-restore fails instead of ignoring erroneous arguments, specifically `-w5` which kube-proxy has been (erroneously) using instead of `-w 5`. This causes its firewall rules to fail along with k8s networking in general.

https://github.com/kubernetes/kubernetes/issues/58956

### Steps to reproduce
Run eg. the dns.multinode test.

**Comment by srhb** [comment]
More tracking links:

https://github.com/kubernetes/kubernetes/pull/60133

I might go ahead and patch this or include an older iptables-restore with kube-proxy if this doesn't get resolved upstream in time for 18.03

**Comment by cstrahan** [comment]
Resolved in #36739.
