### ISSUE TITLE
youki: features "systemd" is required for use as a runtime for docker

### ISSUE THREAD

**Issue by aviallon** [NixOS/nixpkgs#355531]
Suggestion:

https://github.com/NixOS/nixpkgs/blob/76612b17c0ce71689921ca12d9ffdc9c23ce40b2/pkgs/by-name/yo/youki/package.nix#L44-L47

 ```nix
cargoBuildFlags = [
   "-p" 
   "youki" 
   "--features" "systemd"
 ];
```

**Comment by aviallon** [comment]
@Builditluc thanks for your package, by the way!

**Comment by Builditluc** [comment]
@aviallon is this feature-flag optional or does it have to be set in order for youki to function at all?
