### ISSUE TITLE
Update request: dotnetCorePackages.*_9_0 `9.0.100-rc.2.24474.11` → `9.0.100`

### ISSUE THREAD

**Issue by qoh** [NixOS/nixpkgs#355500]
- Package name: dotnetCorePackages.{sdk_9_0, sdk_9_0_1xx, runtime_9_0, release_9_0, dotnet_9}
- Latest released version: 9.0.100
- Current version on the unstable channel: 9.0.100-rc.2.24474.11
- Current version on the stable/release channel: 9.0.100-preview.2.24157.14
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@kuznero 
@mdarocha 
@corngood 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by qoh** [comment]
Ref:
- https://devblogs.microsoft.com/dotnet/announcing-dotnet-9/
- https://dotnet.microsoft.com/en-us/download/dotnet/9.0

**Comment by Followin** [comment]
Seems like it hasn't been properly updated: https://github.com/corngood/nixpkgs/blob/fd3d60b2edbb0333c8ae925d053cf56d0438c379/pkgs/development/compilers/dotnet/9/release-info.json#L3
It still installs rc.2

**Comment by corngood** [comment]
@Followin those are the bootstrap artifacts required to build stage1 of the source-built sdk.  they are usually a release behind.

**Comment by Followin** [comment]
Oh, my bad, it seems like it just has only been merged to nixos-unstable but not to pkgs-unstable yet.
