### ISSUE TITLE
Package request: pay-respects

### ISSUE THREAD

**Issue by ALameLlama** [NixOS/nixpkgs#355631]
**Project description**

Similar to [thefuck ](https://github.com/nvbn/thefuck), This is used to fix typo's in commands but is still maintained

**Metadata**

* homepage URL: https://codeberg.org/iff/pay-respects
* source URL: https://github.com/iffse/pay-respects
* license: AGPL-3.0
* platforms: unix

**Comment by SigmaSquadron** [comment]
@marcusramberg should `thefuck` be dropped as unmaintained upstream and replaced with this?

**Comment by SigmaSquadron** [comment]
(I've also added the module tag as this will need a module to hook `f`'s init script into user shells.

**Comment by marcusramberg** [comment]
Let's start with adding this, and thefuck can be removed later if this is a good replacement?

**Comment by SigmaSquadron** [comment]
That's alright too. If `thefuck` won't be removed, then #355694 can sneak into 24.11.

**Comment by ALameLlama** [comment]
I've been using `pay-respects` on and off for a bit, it's nice but it's definity missing some of the rules that `thefuck` has. With more eyes on the project, I'm hoping people will help add missing rules to pad out anything they use frequently :D
