### ISSUE TITLE
Build failure: nodePackages_latest.nodejs

### ISSUE THREAD

**Issue by JohnRTitor** [NixOS/nixpkgs#355919]
## Steps To Reproduce

1. build `nodePackages_latest.nodejs` from master
## Build log

<details>

<summary>Build Log</summary>

```
┃        >   ...
┃        > ok 4059 known_issues/test-url-parse-conformance
┃        >   ---
┃        >   duration_ms: 56.50900
┃        >   ...
┃        > ok 4060 known_issues/test-vm-function-declaration-uses-define
┃        >   ---
┃        >   duration_ms: 36.65000
┃        >   ...
┃        > ok 4061 known_issues/test-vm-timeout-escape-nexttick
┃        >   ---
┃        >   duration_ms: 806.78800
┃        >   ...
┃        >
┃        > Failed tests:
┃        > out/Release/node /build/node-v23.2.0/test/parallel/test-os.js
┃        > make: *** [Makefile:558: test-ci-js] Error 1
┃        For full logs, run 'nix log /nix/store/ahgdyngidcphsmb7zn5b1lny589pyjdc-nodejs-23.2.0.drv'.
```

</details>

## Additional context

Found it while building `zed-editor` on master.

## Metadata

❯  nix-info -m                                                                                 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.7-cachyos, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/gg86rfp39vc7chqsszk32q7995hz4943-source`

## Notify maintainers

@aduh95 @Ma27 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aduh95** [comment]
> > Failed tests:
> ┃        > out/Release/node /build/node-v23.2.0/test/parallel/test-os.js

Could you share the output of this test?

**Comment by JohnRTitor** [comment]
Could you point me how to do that? I am not familiar with nodePackages, just got the log from the Nix build command.

**Comment by aduh95** [comment]
As it says on the output:

> For full logs, run 'nix log /nix/store/ahgdyngidcphsmb7zn5b1lny589pyjdc-nodejs-23.2.0.drv'.

From there, you can search for `not ok` (or for the test name, but I find `not ok` easier to remember).

**Comment by aduh95** [comment]
OK that's definitely interesting! Could you confirm if the test passes if you revert https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815?

**Comment by LiviaMedeiros** [comment]
Does niceness on NixOS work differently than on most Unix systems? The `os.constants.priority.PRIORITY_LOW` is `19`, there should be no numbers higher than that, and setting priority on same or lower level should be fine.

If it's indeed different, what's the returned value of `require('node:os').type()` on NixOS systems?

**Comment by aduh95** [comment]
> Well this patch does not apply. [JohnRTitor@24c5cc0](https://github.com/JohnRTitor/nixpkgs/commit/24c5cc0adbf278652bdbf5695674f824f7f20c23)

Ah right, my bad, that commit didn't make it into 23.2.0.
I reckon we have this test disabled on macOS, the comment says it's sandbox related: https://github.com/NixOS/nixpkgs/blob/4f93e624c544fb86e60cba7620c0d29083258809/pkgs/development/web/nodejs/nodejs.nix#L312-L314

In any case, we should probably amend the Node.js test to not fail on `EACCES`

**Comment by JohnRTitor** [comment]
Nice, can we cherry-pick the commit here or will it be part of a minor patch release?

**Comment by JohnRTitor** [comment]
Looks like this does not directly apply either, we will either need to rebase and vendor the patch or disable the test, while we wait for a release.

**Comment by aduh95** [comment]
Well you would need to first apply https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815 and confirm it's still an issue with that patch applies, then cherry-pick my commit on top of it. It should make its way to a future minor or patch release yes.

**Comment by JohnRTitor** [comment]
> Does niceness on NixOS work differently than on most Unix systems?

I don't think it is. But I am not entirely sure.

> If it's indeed different, what's the returned value of `require('node:os').type()` on NixOS systems?

@LiviaMedeiros 

![image](https://github.com/user-attachments/assets/9839f4b0-110c-4f15-9ab5-25f7c80d1340)

**Comment by JohnRTitor** [comment]
> Well you would need to first apply [nodejs/node@a094a81](https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815)

I mean this fails to apply. 🥲

diff --git a/pkgs/development/web/nodejs/v23.nix b/pkgs/development/web/nodejs/v23.nix
index a34e53375e69..6a5b7626eb54 100644
--- a/pkgs/development/web/nodejs/v23.nix
+++ b/pkgs/development/web/nodejs/v23.nix
@@ -53,5 +53,10 @@ buildNodejs {
       hash = "sha256-gmIyiSyNzC3pClL1SM2YicckWM+/2tsbV1xv2S3d5G0=";
       revert = true;
     })
+    # possible fix for https://github.com/NixOS/nixpkgs/issues/355919
+    (fetchpatch2 {
+      url = "https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815.patch?full_index=1";
+      hash = "sha256-Jwf5D/QvoKNN36IqWKnWYXIpHdkm/o1rmq+G+n05EG0=";
+    })
   ];
 }

**Comment by aduh95** [comment]
> > Well you would need to first apply [nodejs/node@a094a81](https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815)
> 
> I mean this fails to apply. 🥲
> 
> ```diff
> diff --git a/pkgs/development/web/nodejs/v23.nix b/pkgs/development/web/nodejs/v23.nix
> index a34e53375e69..6a5b7626eb54 100644
> --- a/pkgs/development/web/nodejs/v23.nix
> +++ b/pkgs/development/web/nodejs/v23.nix
> @@ -53,5 +53,10 @@ buildNodejs {
>        hash = "sha256-gmIyiSyNzC3pClL1SM2YicckWM+/2tsbV1xv2S3d5G0=";
>        revert = true;
>      })
> +    # possible fix for https://github.com/NixOS/nixpkgs/issues/355919
> +    (fetchpatch2 {
> +      url = "https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815.patch?full_index=1";
> +      hash = "sha256-Jwf5D/QvoKNN36IqWKnWYXIpHdkm/o1rmq+G+n05EG0=";
> +    })
>    ];
>  }
> ```

You need to fix the hash, you should get a different hash depending if you pass `revert=true` or not

**Comment by aduh95** [comment]
The hash you should be using is `sha256-5FZfozYWRa1ZI/f+e+xpdn974Jg2DbiHbua13XUQP5E=` for <https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815.patch?full_index=1>

**Comment by JohnRTitor** [comment]
Yeah I was just building the package. Looks like we need both https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815 and https://github.com/nodejs/node/pull/55863/commits/f60cc5871b3950a078356dbd30cb16ba64890916 for the test failure to be fixed.

**Comment by aduh95** [comment]
Can you clarify what's the behavior without https://github.com/nodejs/node/commit/f60cc5871b3950a078356dbd30cb16ba64890916? Same error as without https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815?

**Comment by JohnRTitor** [comment]
The test indeed failed with just https://github.com/nodejs/node/commit/a094a8166cd772f89e92b5deef168e5e599fa815 applied and needed https://github.com/nodejs/node/commit/f60cc5871b3950a078356dbd30cb16ba64890916 to work.

**Comment by LiviaMedeiros** [comment]
I guess we should indeed skip this test in case of `EACCES` since it identifies just as `Linux`, however normally this error shouldn't happen.

Does the following JS snippet throw?
```js
const os = require('node:os');
console.log(`initial priority: ${os.getPriority()}`);
console.log(`setting priority: ${os.constants.priority.PRIORITY_LOW}`);
os.setPriority(os.constants.priority.PRIORITY_LOW);
console.log(`new priority: ${os.getPriority()}`);
```
Or this in command line?
```bash
nice
renice --priority 19 $$
nice
```

**Comment by JohnRTitor** [comment]
![image](https://github.com/user-attachments/assets/6492aa2f-49cb-4543-9b8a-4fcf226014e0)

**Comment by LiviaMedeiros** [comment]
@JohnRTitor Thanks!
It seems that there's nothing out of ordinary in priority handling on NixOS. The test fix wasn't working, because the comparison was other way around. 😅 I'll open a PR with proper followup fix ASAP.
