### ISSUE TITLE
Internal compiler error (Segmentation fault) in GCC when building z3, qtwebengine

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#355935]
## Describe the bug

Build fails
```
during GIMPLE pass: local-fnsummary
In file included from gen/third_party/blink/renderer/core/inspector/inspector_jumbo_5.cc:18:
./../../3rdparty/chromium/third_party/blink/renderer/core/inspector/inspector_task_runner.cc: In function 'int snprintf(char*, size_t, const char*, ...)':
./../../3rdparty/chromium/third_party/blink/renderer/core/inspector/inspector_task_runner.cc:81:1: internal compiler error: Segmentation fault
   81 | }  // namespace blink
      | ^
0x1d35627 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x1d36547 internal_error(char const*, ...)
        ???:0
0xe588df crash_signal(int)
        ???:0
0xc16b35 fast_call_summary<ipa_call_summary*, va_heap>::get_create(cgraph_edge*)
        ???:0
0xc118e8 analyze_function_body(cgraph_node*, bool)
        ???:0
0xc14d1a compute_fn_summary(cgraph_node*, bool)
        ???:0
0xc15339 (anonymous namespace)::pass_local_fn_summary::execute(function*)
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```
See https://github.com/NixOS/nixpkgs/pull/327052#pullrequestreview-2430112333 for another failure.

## Steps To Reproduce

1. Build qtwebengine (or z3 from above)

## Expected behavior

No internal compiler error

## Additional context

I couldn't find anything about this upstream. Then again, Bugzilla is somewhat painful to search...

## Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.05 (Uakari), 24.05.20241109.fd66cd1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-21.05-21.05.1268.21b696caf39"`
 - channels(arne): `"nixos-21.05-21.05.1268.21b696caf39"`
 - nixpkgs: `/home/<me>/nixpkgs`

## Notify maintainers

gcc team: @synthetica9 @vcunat @ericson2314

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by numinit** [comment]
Tried switching z3 to LLVM and that came with its own problems...

**Comment by numinit** [comment]
This seems like a race condition in GCC. We were unable to reproduce it in https://github.com/NixOS/nixpkgs/pull/327052 eventually.

**Comment by FliegendeWurst** [comment]
Just got the error again for openjdk23-headless. This time I was using GCC 14
```
=== Output from failing command(s) repeated here ===
* For target hotspot_variant-server_libjvm_objs_jvmciCompilerToVMInit.o:
during GIMPLE pass: ealias
/build/source/src/hotspot/share/jvmci/jvmciCompilerToVMInit.cpp: In static member function ‘static JVMCIObjectArray CompilerToVM::initialize_intrinsics(JVMCIEnv*)’:
/build/source/src/hotspot/share/jvmci/jvmciCompilerToVMInit.cpp:512:1: internal compiler error: Segmentation fault
  512 | }
      | ^
0x20db3f4 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x20dbc29 internal_error(char const*, ...)
        ???:0
0xf7580f crash_signal(int)
        ???:0
0x11897b2 unify_nodes(constraint_graph*, unsigned int, unsigned int, bool)
        ???:0
0x1189b80 find_equivalent_node(constraint_graph*, unsigned int, unsigned int)
        ???:0
   ... (rest of output omitted)

* All command lines available in /build/source/build/linux-x86_64-server-release/make-support/failure-logs.
```

**Comment by FliegendeWurst** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78216 seems related, especially the last comment.

**Comment by FliegendeWurst** [comment]
And another, when building `python311Packages.openusd`. The bad (but also good) aspect of these is that they often disappear when re-running the same build. I might have to look into reporting this upstream.

<details>

```
/nix/store/kd1amvbva27hbqajakffvrhjcblz1npn-gcc-14-20241116/include/c++/14-20241116/bits/stl_vector.h:370:7: internal compiler error: Segmentation fault
  370 |       }
      |       ^
0x20db3f4 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x20dbc29 internal_error(char const*, ...)
        ???:0
0xf7580f crash_signal(int)
        ???:0
0x7df42b cp_gimplify_expr(tree_node**, gimple**, gimple**)
        ???:0
0xc67194 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ???:0
0xc67be8 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ???:0
0xc7698e gimplify_bind_expr(tree_node**, gimple**)
        ???:0
0xc68306 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ???:0
0xc6b91c gimplify_and_add(tree_node*, gimple**)
        ???:0
0x7df16c cp_gimplify_expr(tree_node**, gimple**, gimple**)
        ???:0
0xc67194 gimplify_expr(tree_node**, gimple**, gimple**, bool (*)(tree_node*), int)
        ???:0
0xc6bace gimplify_body(tree_node*, bool)
        ???:0
0xc6beba gimplify_function_tree(tree_node*)
        ???:0
0xac5737 cgraph_node::analyze()
        ???:0
0xac7eb7 analyze_functions(bool)
        ???:0
0xac8b7d symbol_table::finalize_compilation_unit()
        ???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```
</details>

**Comment by trofi** [comment]
[posting here the same thing as in matrix]

If the crashes are non-deterministic it might be hardware failure. I'd suggest running memtest just in case.

For example `cp_gimplify_expr()` is a conversion from C++ frontend representation to GIMPLE. Those should crash all the time if they go wrong. Other crashes are in other subsystems, like `unify_nodes()` or `compute_fn_summary()`. Them all being `SIGSEGV`s is suspicious (usually `gcc` internal asserts and produces slightly more meaning ful errors).

Thus I would explore hardware stability angle.

**Comment by FliegendeWurst** [comment]
I ran memtest and found 1 bit of bad RAM.. will get a replacement soon. Closing as hardware issue.

**Comment by numinit** [comment]
Aw shucks. :-(
