### ISSUE TITLE
Discord with Vencord not working/ app is damaged

### ISSUE THREAD

**Issue by ojsef39** [NixOS/nixpkgs#355950]
## Describe the bug

The Discord App is damaged when installed with Vencord.

Thanks in advance for looking into this :)

## Steps To Reproduce

1. Install Discord like this:
```nix
{ pkgs, lib, vars, ... }: 
{
  environment.systemPackages = with pkgs; [
    (discord.override {
      withVencord = true;
    })  # Discord with Vencord
  ];
}
```
2. Open Discord

## Expected behavior

I expected the app to open normally as described here:
https://github.com/NixOS/nixpkgs/issues/259297#issuecomment-1752114901

## Screenshots

<img width="254" alt="image" src="https://github.com/user-attachments/assets/40ad822b-5c3f-441c-a925-7931c4785fe8">

## Additional context

I tried different scenarios like installing both the override and discord, i removed every remains of discord and installed only discord and then afterward added the override and more, but everything i tried doesn't seem to work

## Metadata

```nix
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

## Notify maintainers
@Artturin 
@donatello 
@Infinidoge 
@jopejoe1 
@Scrumplex 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
CC @FlafyDev @NotAShelf @DontEatOreo for Vencord

I don't have a darwin machine to test this sadly.

**Comment by DontEatOreo** [comment]
Try to open it so it fails, then

System Settings -> Privacy -> Scroll all way down -> Open Anyway -> Enter your user password

**Comment by ojsef39** [comment]
> Try to open it so it fails, then
> 
> 
> 
> System Settings -> Privacy -> Scroll all way down -> Open Anyway -> Enter your user password

Thank you that worked, it opens now, but since it updated on launch there is no vencord.

Could you please update the discord package? Thank you very much in advance!

And i highly appreciate your fast responses! Didn't think i get an answer that fast lol

**Comment by DontEatOreo** [comment]
> Thank you that worked, it opens now, but since it updated on launch there is no vencord.

When you open Discord did it ask you to enter your password *(AFTER the prompt in system settings)* in order to update Discord?

If that's the case, then you will have to log out of your user, account log in, then `sudo nix store delete /nix/store/....-Discord` and rebuild your system to download Discord again

To avoid all of this mess in the future, make sure to run Discord first from the terminal *(by just running `discord`)* so it runs the Python script (https://github.com/NixOS/nixpkgs/blob/7421ff3aa29d1a7da7bf0302b9e640cab064fb67/pkgs/applications/networking/instant-messengers/discord/disable-breaking-updates.py) that adds `SKIP_HOST_UPDATE` to `settings.json` *(in `~/Library/Application\ Support/discord`)*, so you don't get "tricked" into accidentally updating Discord on Nix and breaking your Vencord install

**Comment by DontEatOreo** [comment]
> Could you please update the discord package?

There's already a PR (https://github.com/NixOS/nixpkgs/pull/355721)

**Comment by ojsef39** [comment]
> If that's the case, then you will have to log out of macOS, log in, then sudo nix store delete /nix/store/....-Discord and rebuild your system to download Discord again

Ahh I see, okay, I will try that :) Just got some issue about the store still being active (even after logout)

> To avoid all of this mess in the future, make sure to run Discord first from the terminal (by just running discord) so it runs the Python script (https://github.com/NixOS/nixpkgs/blob/7421ff3aa29d1a7da7bf0302b9e640cab064fb67/pkgs/applications/networking/instant-messengers/discord/disable-breaking-updates.py) that adds SKIP_HOST_UPDATE to settings.json (in ~/Library/Application\ Support/discord), so you don't get "tricked" into accidentally updating Discord on Nix and breaking your Vencord install

good to know, will do that, thanks for the info :)

**Comment by ojsef39** [comment]
So ive tried it now and it doesnt seem to work for me.
The issue is probably that i cant open discord again from the terminal after i hit "open anyway" in settings, i have to open it with the open button and then it will update

**Comment by ojsef39** [comment]
ah i see, you hit cancel, wait and then it starts but now i see this:
<img width="1573" alt="image" src="https://github.com/user-attachments/assets/ce944a88-f384-4914-b2f4-2fd987237b6f">
i guess thats related to https://github.com/NixOS/nixpkgs/issues/334141

maybe i should just use nixcord

**Comment by DontEatOreo** [comment]
> So ive tried it now and it doesnt seem to work for me. The issue is probably that i cant open discord again from the terminal after i hit "open anyway" in settings, i have to open it with the open button and then it will update

In that case, you can first open it via System Settings, and when you are prompted again for the password in Discord to update, just cancel it, close Discord, and then launch it from Terminal.

It should start with:

```console
[Nix] Disabling updates already done
[Vencord] Starting up...
[Vencord] Loading original Discord app.asar
...
```

I think the crash is related to discord updates, breaking some of Vencord's regex, it should be fix in v1.10.7

**Comment by ojsef39** [comment]
Okay, ill try again this evening because I didn't see that in the logs:
`[Nix] Disabling updates already done`

If that's not working, ill just use nixcord, it's more in style with nix anyway (declarative), I think, since with this, I have to have my vencloud container active, which I wouldn't need any more if I use nixcord

**Comment by DontEatOreo** [comment]
I feel like there is some missing part here that's causing the issue

But let's try this first:

1. Remove Discord entry from your nix config
2. Rebuild
3. Restart
4. Collect Garbage *(both WITH and WITHOUT SUDO)*
5. Add Discord again and rebuild again

Then, when you start Discord again from system settings, if ***Discord*** asks you to update, ***DO NOT*** and cancel the prompt for a password. Discord will force you to wait 10 seconds, and after that, it will restart itself and let you use it. At this point, you can shut down Discord and just start Discord from the terminal to trigger the Python script. Then you can again shut down Discord from terminal window and start it normally.

**Comment by ojsef39** [comment]
Thanks a bunch for the detailed instructions! I’ve tried everything you suggested, but I still can’t seem to make it work. It seems like the python script is not even being triggered.

I don't really know what's wrong with my config, but nixcord also won't work, tried the same steps for nixcord on two different machines. Pretty much the same issue there, when it opens, there is no vencord, the only difference is the nixcord app isnt broken

**Comment by DontEatOreo** [comment]
I'm not really sure how I can help you further, both nixpkgs and nixcord work fine, but I notice this:

https://github.com/ojsef39/nix-personal/blob/cc403ba411a148b8a7dad8f4632258f1262d60e0/hosts/darwin/system.nix#L33

Are those dotfiles, the ones you're using right now? If yes then you're using a completely different derivation *(in this case vanilla discord)* when launching Discord from the Dock...

**Comment by ojsef39** [comment]
> I'm not really sure how I can help you further, both nixpkgs and nixcord work fine, but I notice this:

No problem, thank you very much tho for all your help! I appreciate it a lot :)

> 
> Are those dotfiles, the ones you're using right now? If yes then you're using a completely different derivation *(in this case vanilla discord)* when launching Discord from the Dock...

Yes correct, i'm aware of that, i just didn't push the changes for the right app in the dock yet (or its in dev)

**Comment by ojsef39** [comment]
@DontEatOreo GREAT NEWS :) I fixed it.

So the issue was i have to follow nixpkgs like this…
```
    nixcord = {
      url = "github:kaylorben/nixcord";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

Apparently, my home manager version and nixpkgs version are mismatched, and i didn't get an error for that until i added the follow.
