### ISSUE TITLE
file: "bash" in string constants mistakingly replaced with path to bash package

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#35591]
## Issue description

![](http://i.imgur.com/vQlrgBq.png)

### Steps to reproduce

file a-script.sh

**Comment by dtzWill** [comment]
I think that's just because of the shebang, it'll print same for anything with a shebang ("a $interpreter_invocation script").

Checking locally it seems the full path is specified in the shebang:

```console
$ head -n1 $(which man)
#! /nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin/bash -e
```

**Comment by volth** [comment]
oh
