### ISSUE TITLE
clamav not able to scan

### ISSUE THREAD

**Issue by johanno** [NixOS/nixpkgs#355999]
## Describe the bug

clamscan does not work since clamav folder in share is missing!?

In 24.05 nixos

## Steps To Reproduce

1. nix-shell -p clamav
2. clamscan -i
4. `LibClamAV Error: cl_load(): No such file or directory: /nix/store/agiw2n1rhzxfhmykyf5m2b83jl8nknl2-clamav-1.3.1/share/clamav
ERROR: Can't get file status`

## Expected behavior

clamscan works

## Notify maintainers

@robberer 
@LeSuisse 
@Lurkki14 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Jasper-Ben** [comment]
see: https://github.com/NixOS/nixpkgs/issues/25785#issuecomment-301332175

**Comment by johanno** [comment]
I created a wiki entry since I first looked there for that information if there is a enable needed.

https://wiki.nixos.org/wiki/Clamav

Best case this info would be directly in search.nixos.org when you get the package.
