### ISSUE TITLE
KRunner fails to find installed dictionaries

### ISSUE THREAD

**Issue by Naxdy** [NixOS/nixpkgs#356113]
## Describe the bug

Since upgrading to Plasma 6.2, KRunner fails to find installed dictionaries in NixOS.

## Steps To Reproduce

1. Install KRunner and some dictionaries. In my case, I have `pkgs.kdePackages.krunner` in `environment.systemPackages` and the following dictionaries in my user's packages:
    ```nix
    users.users.naxdy.packages = builtins.attrValues {
      inherit (pkgs)
        aspell
        hunspell;

      inherit (pkgs.aspellDicts)
        de
        en
        en-computers
        en-science;

      inherit (pkgs.hunspellDicts)
        en_US
        en_US-large
        de_DE;
    };
    ```
2. Enable "Spell Checker" in KRunner's plugins
3. Open KRunner and type in "spell help"

## Expected behavior

KRunner confirms that the word "help" is spelled correctly.

## Screenshots

![image](https://github.com/user-attachments/assets/f0d33fd3-7034-4fa0-8def-dcd52a6322a6)

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Uakari) 24.42.20241107.3aea494`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/i7h0a3zw3nhv0fzyslfs2s4c476a4y9v-source`

## Notify maintainers

@ilya-fedin 
@K900 
@LunNova 
@mjm 
@NickCao 
@SuperSandro2000 
@ttuegel 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Can we somehow start krunner with strace and figure out where it wants to read the dicts from?

**Comment by Naxdy** [comment]
After a couple days of trying to navigate strace, I updated today and found that it's no longer an issue. This is on nixpkgs ref `ac35b104800bff9028425fec3b6e8a41de2bbfff` where it's fixed. If no one did anything on our end, I'm assuming it was upstream? Either way, issue is resolved.

**Comment by notjiatan** [comment]
I am encountering this issue again on 25.05
