### ISSUE TITLE
nix run doesn't set PYTHONPATH

### ISSUE THREAD

**Issue by mmerickel** [NixOS/nixpkgs#35627]
## Issue description

`nix-shell` properly sets `PYTHONPATH` but `nix run` does not. I'm sure this is a misunderstanding but it seems to be a regression in the new `nix run`.

### Steps to reproduce

```
~❯ nix-shell -p python3 python3.pkgs.numpy

[nix-shell:~]$ which python
/nix/store/lvyjha5gq7a0dllynjj9i21fk88kvs88-python3-3.6.4/bin/python

[nix-shell:~]$ python
Python 3.6.4 (default, Feb 19 2018, 17:16:57)
[GCC 4.2.1 Compatible Clang 5.0.1 (tags/RELEASE_501/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>>

[nix-shell:~]$ exit
~❯ nix run -f '<nixpkgs>' python3 python3.pkgs.numpy
bash-3.2$ which python
/nix/store/lvyjha5gq7a0dllynjj9i21fk88kvs88-python3-3.6.4/bin/python
bash-3.2$ python
Python 3.6.4 (default, Feb 19 2018, 17:16:57)
[GCC 4.2.1 Compatible Clang 5.0.1 (tags/RELEASE_501/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>>
```

## Technical details

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(michael): `""`
 - channels(root): `"nixpkgs-18.03pre129189.c2fbd472a4e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by FRidh** [comment]
> nix-shell properly sets PYTHONPATH but nix run does not. I'm sure this is a misunderstanding but it seems to be a regression in the new nix run.

The purpose of `nix-shell` and `nix run` is different. The former is used for development purposes and therefore runs a setup hook which sets up `PYTHONPATH`. The latter is solely for running applications and therefore does not.

> nix-shell -p python3 python3.pkgs.numpy

This usage of `nix-shell` is incorrect. While it typically worked because `PYTHONPATH` was set up, this is not the supported way of working. Instead, use 

> nix-shell -p 'python3.withPackages(ps: with ps; [ numpy ])'

Unfortunately `nix run` does not (yet) support the above way of creating a derivation.

**Comment by mmerickel** [comment]
Thanks for the example, I hadn't seen `python3.withPackages` anywhere before.

**Comment by FRidh** [comment]
The Nixpkgs manual documents how to use Python on Nix.

**Comment by haslersn** [comment]
> The purpose of `nix-shell` and `nix run` is different. The former is used for development purposes and therefore runs a setup hook which sets up `PYTHONPATH`. The latter is solely for running applications and therefore does not.

`nix` is the more modern command (allowing e.g. positional parameters with `nix run [..] -c`). I think there should also be a modern command (rework of `nix-shell`) for those development purposes you mentioned. It could for example be called `nix shell` (without dash) or `nix devenv`.
