### ISSUE TITLE
`nixpkgs.config.allowUnfree = true` noop after rebuild when `nix.channel.enable = false`

### ISSUE THREAD

**Issue by kjkent** [NixOS/nixpkgs#356209]
## Describe the bug

Using a flake-based NixOS config, so have set `nix.channel.enable = false`. Since doing so, running, say `nix-shell -p google-chrome` throws an error due to unfree license, advising to set `nixpkgs.config.allowUnfree = true`, which is already set.

This does not prevent `nixos-rebuild` from installing unfree software, just subsequent commands run on the rebuilt system.

Currently adding `NIXPKGS_ALLOW_UNFREE=1` to `environment.sessionVariables` as a workaround.

## Steps To Reproduce

1. Have the following in NixOS flake:
```Nix
 config = {
    nixpkgs.config.allowUnfree = true;
    nix = {
      channel.enable = false; # Unnecessary due to flake but enabled by default
      settings = {
        experimental-features = [
          "nix-command"
          "flakes"
        ];
```
2. Rebuild flake and run `nix-shell -p google-chrome`
3. Nix refuses to evaluate due to unfree license.

## Expected behavior

`nix-shell` allows the evaluation of unfree packages due to `nixpkgs.config.allowUnfree` being set to `true`.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
 
## Notify maintainers

@roberth 
@SuperSandro2000 

(Apologies, you guys seemed the best fit to tag as Sandro committed to nix.nix last and Robert most frequently -- apologies if in error)

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
> `nixpkgs.config.allowUnfree = true`

is only meant for the nixpkgs used inside the nixos configuration. It is not honored by nix-shell. Please read the entire error message to have all options available. Feel free to improve the message with a PR.

**Comment by kjkent** [comment]
@SuperSandro2000 thanks for the clarification -- I would say the current error text doesn't convey this fully. In the interests of making a PR to better it, here's the current text:

```text
a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "google-chrome"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
```

My question is: if **a** is temporary and **b** is not intended to cover the installed system, and **c** involves non-declarative config outside of the flake, _what is the correct way to set this option so it applies to the built system?_

**Comment by kjkent** [comment]
> My question is: if a is intended to be temporary and b is not intended to cover the installed system, and c involves non-declarative config outside of the flake, what is the correct way to set this option so it applies to the built system?

@SuperSandro2000 sorry to nudge you; any thoughts?

**Comment by roberth** [comment]
> so it applies to the built system?

It seems that you don't just want to apply it to the system, but to all the other things as well.
This is generally not something that Nix lets you do, because letting local (or otherwise circumstantial) configuration affect the evaluation or build would lead to different results, i.e. not be reproducible.
Granted, a mere fail/succeed preference like this seems harmless, but in order to avoid abuse of impure features like `builtins.getEnv`, it was disabled for flake-based commands.

**Comment by kjkent** [comment]
@roberth thanks for the info. 

I think my mental model of nixpkgs was like that of a configurable repository, and that when NixOS is being built, you're baking that nixpkgs, with its config and package set(or the build instructions for) into the system itself. And therefore allow_unfree on/off just dictates what packages are allowed.

I'm just a few months into using nix/NixOS regularly, so there's definitely more I need to learn!

Thanks 👍🏻
