### ISSUE TITLE
Update request: Surrealist 2.1.6 → 3.0.8

### ISSUE THREAD

**Issue by damccull** [NixOS/nixpkgs#356316]
## Package Information

- Package name: surrealist
- Latest released version: 3.0.8
- Current version on the unstable channel: 2.1.6
- Current version on the stable/release channel: 1.11.7

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@MDM23  

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
I do not maintain this package. That would be @MDM23

**Comment by damccull** [comment]
> I do not maintain this package. That would be @MDM23

I apologize. The template said to notify whoever last touched it if there was no listed maintainer, unless I misunderstood. I could not find a maintainer listed in the code. I'll fix the issue text.

**Comment by Mic92** [comment]
@damccull have you tried updating the package yourself?

**Comment by Mic92** [comment]
This gives you a starting point:

```
$ git clone https://github.com/NixOS/nixpkgs
$ cd nixpkgs
$ nix-shell -p nix-update --run 'nix-update --build --commit surrealist'
```

**Comment by damccull** [comment]
Thanks. I'll try to look into it this weekend too, though I'm not yet confident I'll be able to solve it :D

**Comment by MDM23** [comment]
@damccull Thank you for checking it out! :+1: Got it working yesterday, so I hope it didn't cause too much effort already on your side?

**Comment by damccull** [comment]
No, my kids distracted me and I hadn't got a chance to look into it yet. Thank you for your effort on getting this upgraded! I'm looking forward to seeing it hit my computer.
