### ISSUE TITLE
Update request: `sydbox` `1-2.2.0` → `3.28.2`

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#356580]
## Package Information

- Package name: `sydbox`
- Latest released version: `3.28.2`
- Current version on the unstable channel: `1-2.2.0`
- Current version on the stable/release channel: `1-2.2.0`

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@illdefined 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by illdefined** [comment]
I tried updating the package a while ago, but I ran into some difficulties with current versions of Rust.
