### ISSUE TITLE
devmon as distributed with udevil 0.4.4 is broken

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#35650]
## Issue description

- systemd service isn't referencing the correct binary
- investigate is devmon requires suid

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.4, NixOS, 18.03.git.66cd46f2d44M (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`
 - channels(peter): `""`
 - nixpkgs: `/home/peter/src/active/nixpkgs_unstable`

**Comment by Dema** [comment]
Can you elaborate a bit on what exactly is wrong? Steps to reproduce would be ideal.

**Comment by peterhoeg** [comment]
1. install udevil
2. look at <storepath>/lib/systemd/system/devmon.service

```
[Unit]
Description=devmon Service

[Service]
Type=simple
User=%i
# Set DISPLAY for popup dialogs
Environment=DISPLAY=:0
EnvironmentFile=/etc/conf.d/devmon
ExecStart=/usr/bin/devmon $ARGS 

[Install]
WantedBy=multi-user.target
```

**Comment by peterhoeg** [comment]
Although I've self-assigned it, somebody else is very welcome to grab this.

**Comment by erasmas** [comment]
I noticed the same issue yesterday when I tried devmon for automounting. devmon works fine when started manually but doesn't work as a systemd service. I couldn't find devmon service after running `nixos-rebuild switch` and `systemctl --type=service | grep devmon`.

**Comment by Artturin** [comment]
#128841
