### ISSUE TITLE
php.overrideAttrs throws an error for ({ }) and (final: prev: { }) overrides

### ISSUE THREAD

**Issue by Jaculabilis** [NixOS/nixpkgs#356639]
## Describe the bug

The `php` package [overrides the default `overrideAttrs` function](https://github.com/NixOS/nixpkgs/blob/0a14706530dcb90acecb81ce0da219d88baaae75/pkgs/development/interpreters/php/generic.nix#L153-L159), but it doesn't preserve the behavior of the default `overrideAttrs` with respect to which arguments are allowed. Only overrides of the form `prev: { ... }` work; `{ ... }` and `final: prev: { }` throw errors.

## Steps To Reproduce

Expected behavior with `hello`:

```
nix-repl> pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/0a14706530dcb90acecb81ce0da219d88baaae75.tar.gz") { }  

nix-repl> pkgs.hello.overrideAttrs { }
«derivation /nix/store/lrrywp3k594k3295lh92lm7a387wk0j9-hello-2.12.1.drv»

nix-repl> pkgs.hello.overrideAttrs (prev: { })
«derivation /nix/store/lrrywp3k594k3295lh92lm7a387wk0j9-hello-2.12.1.drv»

nix-repl> pkgs.hello.overrideAttrs (final: prev: { })
«derivation /nix/store/lrrywp3k594k3295lh92lm7a387wk0j9-hello-2.12.1.drv»
```

Behavior of `php`:

```
nix-repl> pkgs.php.overrideAttrs { }                  
error:
       … while calling a functor (an attribute set with a '__functor' attribute)

         at /nix/store/qsmvjnr03r913hmmkiis39jw6ls8d5jl-source/lib/customisation.nix:146:27:

          145|       # Change the result of the function call by applying g to it
          146|       overrideResult = g: makeOverridable (mirrorArgs (args: g (f args))) origArgs;
             |                           ^
          147|     in

       … while evaluating a branch condition

         at /nix/store/qsmvjnr03r913hmmkiis39jw6ls8d5jl-source/lib/customisation.nix:148:7:

          147|     in
          148|       if isAttrs result then
             |       ^
          149|         result // {

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attempt to call something which is not a function but a set

       at /nix/store/qsmvjnr03r913hmmkiis39jw6ls8d5jl-source/pkgs/development/interpreters/php/generic.nix:74:21:

           73|         in
           74|         fApplied // g attrs';
             |                     ^
           75|

nix-repl> pkgs.php.overrideAttrs (prev: { })
«derivation /nix/store/2j0bvq7zlf4s2fsrdyv55y0mr7zlpsjf-php-with-extensions-8.2.25.drv»

nix-repl> pkgs.php.overrideAttrs (final: prev: { })
error:
       … while calling a functor (an attribute set with a '__functor' attribute)

         at /nix/store/qsmvjnr03r913hmmkiis39jw6ls8d5jl-source/lib/customisation.nix:146:27:

          145|       # Change the result of the function call by applying g to it
          146|       overrideResult = g: makeOverridable (mirrorArgs (args: g (f args))) origArgs;
             |                           ^
          147|     in

       … while evaluating a branch condition

         at /nix/store/qsmvjnr03r913hmmkiis39jw6ls8d5jl-source/lib/customisation.nix:148:7:

          147|     in
          148|       if isAttrs result then
             |       ^
          149|         result // {

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is a function while a set was expected

```

## Expected behavior

All three forms of `overrideAttrs`, [as described in the manual](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideAttrs), should be supported.

## Additional context

I've never used PHP, I only ran into this because I'm trying to use an overlay to add something to every package's `meta` attribute.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.36, NixOS, 24.05 (Uakari), 24.05.20240701.d032c1a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/xjn3184743q0fxayzwrhil2i06pr61x8-source`

## Notify maintainers

@aanderse @drupol @Ma27 @patka-123 @talyz

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ma27** [comment]
Feel free to try it out and file a PR if that's the case.

**Comment by Jaculabilis** [comment]
[This patch](https://github.com/Jaculabilis/nixpkgs/commit/f7ab39e5253c9a8dd54cef748228976ffd0a8319) solves the immediate problem of `overrideAttrs` exploding:

```
nix-repl> pkgs = import ./. { }

nix-repl> pkgs.php
«derivation /nix/store/2j0bvq7zlf4s2fsrdyv55y0mr7zlpsjf-php-with-extensions-8.2.25.drv»

nix-repl> pkgs.php.overrideAttrs (prev: { })
«derivation /nix/store/2j0bvq7zlf4s2fsrdyv55y0mr7zlpsjf-php-with-extensions-8.2.25.drv»

nix-repl> pkgs.php.overrideAttrs (final: prev: { })
«derivation /nix/store/2j0bvq7zlf4s2fsrdyv55y0mr7zlpsjf-php-with-extensions-8.2.25.drv»

nix-repl> pkgs.php.overrideAttrs ({ })              
«derivation /nix/store/2j0bvq7zlf4s2fsrdyv55y0mr7zlpsjf-php-with-extensions-8.2.25.drv»
```

It's a little odd to me that what comes back from `pkgs.php` is actually a `php-with-extensions`, whereas the override receives just the `php` package found at `pkgs.php.unwrapped`:

```
nix-repl> (pkgs.php.overrideAttrs (final: prev: { meta = prev.meta // { potato = final.pname; }; })).meta.potato
"php"
```

I feel like this should actually be `overridePhpAttrs` so as not to shadow the stdenv `overrideAttrs` &mdash; but I'm not a maintainer, so my opinion doesn't count for much on that.
