### ISSUE TITLE
OBS Studio fails to use lossless audio

### ISSUE THREAD

**Issue by korrat** [NixOS/nixpkgs#356683]
## Describe the bug

When trying to use lossless audio with OBS through ffmpeg, an error message pops up "Failed to open AAC codec: Invalid argument". Checking the logs seems to point to the ffmpeg settings for the audio encoder.

Following the error message revealed https://github.com/obsproject/obs-studio/issues/11504, which seems to point to an added check in ffmpeg 7.1 as the likely culprit. However, that issue also notes that ffmpeg 7.1 is not (yet) supported by OBS.

## Steps To Reproduce

1. Configure OBS for lossless audio capture through ffmpeg (e.g., `FFmpeg PCM (32 Bit Float)`).
2. Click "Start recording"
3. Error message appears

## Expected behavior

OBS records lossless audio through a supported ffmpeg version.

## Additional context

I haven't been able to verify which version of ffmpeg OBS was actually linked against. The nix expression seems to use `ffmpeg` which is version `7.1` in my current checkout.

There are possible fixes for ffmpeg 7.1 support in https://github.com/obsproject/obs-studio/pull/11510 and https://github.com/obsproject/obs-studio/pull/11511.

## Metadata

```
- system: `"x86_64-linux"`
 - host os: `Linux 6.11.5, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `not found`
```

## Notify maintainers

@jb55 @materusPL @fpletz 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by korrat** [comment]
Overriding `obs-studio` to use `ffmepg_6` fixes the recording.

**Comment by kovreee** [comment]
hey korrat! can you explain how you fixed it? I am not really sure how to do that...

**Comment by korrat** [comment]
I have the following module in my home-manager config:

```
{pkgs}: let
  obs-studio = pkgs.obs-studio.override {ffmpeg = pkgs.ffmpeg_6;};
in {
  enable = true;
  package = obs-studio;

  plugins = builtins.map (pkg: pkg.override {inherit obs-studio;}) (with pkgs.obs-studio-plugins; [
    input-overlay
    obs-pipewire-audio-capture
    wlrobs
  ]);
}
```

The relevant line is line 2, where I'm overriding the `ffmpeg` input to the `obs-studio` package use `ffmpeg_6`.

I also override `obs-studio` for each plugin, just to be sure. I'm not certain that is required, but it makes things easier.
