### ISSUE TITLE
python2Packages: pathlib2, ipython (as a reverse-dependency) fail to build

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#35664]
## Issue description

On current `master` (formally: `ea299bdca8a88381a9bd6aba232481b0910dff7f`) pathlib2 on Python2 fails the testsuite.

### Steps to reproduce

`nix-build '<nixpkgs>' -A python2Packages.pathlib2`

## Technical details

The testsuite assumes that if `getpwall()` function for enumerating users is provided, it will actually work during the test. The build sandbox doesn't have `/etc/passwd`, so attempting to find a username to test home directory expansion fails.

Some options to fix: disable the testsuite; kill this specific test (via a patch or via replacing the condition «there is `getpwall`» with `False`)

@FRidh which is better? I think I prefer a sed call to replace the condition.

**Comment by FRidh** [comment]
Disabling the specific test is the preferred solution. Yep, sed or substituteInPlace.

**Comment by 7c6f434c** [comment]
Fixed in 754816b84b98afdc0727e13dd66e1698b097de6a
