### ISSUE TITLE
version bump request: QGIS 3

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#35669]
QGIS 3.0 Girnona [has been released](http://blog.qgis.org/2018/02/23/qgis-3-0-girona-is-released/).

We should provide a derivation for it. (For the time being, probably in parallel to the remaining LTR release 2.18.x, as upstream does
> not expect [3.x] to be as reliable as the 2.18 LTR just yet.

so the LTR might still be needed by some users.)

**Comment by mpickering** [comment]
This isn't trivial because QGIS 3 now uses Qt5. Many Qt5 packages don't build on darwin so I can't be of much help.

**Comment by mpickering** [comment]
See #38022

**Comment by lsix** [comment]
Hi,

adding `qgis3` (alongside `qgis2`) is definitely on my TODO list, hopefully before 19.03 feature freeze if I can arrange some time for that… (:crossed_fingers:) All the required dependencies should be in nixpkgs by now, it is just a matter of “doing it”.

The work in #38022 is for sure a good starting point. One should adapt what was proposed in 73ca16cedacdace146aeeb4de8aebe7184b56329

**Comment by lsix** [comment]
I have merged #56486 into master and backported it to `release-19.03`. QGIS 3 will be present in the next NixOS release (and should be soon in `unstable`).

I close this issue.
