### ISSUE TITLE
Update request: jellyfin{,-web} 10.10.1 → 10.10.2

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#356716]
## Package Information

- Package name: jellyfin/jellyfin-web
- Latest released version: 10.10.2
- Current version on the unstable channel: 10.10.1
- Current version on the stable/release channel: 10.9.11

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@nyanloutre @minijackson @purcell @jojosch 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by purcell** [comment]
Hey @ryantm, I've seen a few update requests recently for packages like and Sonarr recently — in the past, we'd normally receive update PRs automatically from the @r-ryantm bot: are we doing something wrong such that this has stopped?
