### ISSUE TITLE
Build failure: libretro.citra.src

### ISSUE THREAD

**Issue by zeuner** [NixOS/nixpkgs#356701]
## Steps To Reproduce

1. build `libretro.citra.src`

## Build log

<details>

<summary>Build Log</summary>

Multiple submodule fetch failures, e.g.:

```
Cloning into '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/dynarmic'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: clone of 'https://github.com/citra-emu/dynarmic.git' into submodule path '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/dynarmic' failed
Failed to clone 'externals/dynarmic' a second time, aborting
```

```
Cloning into '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/libressl'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: clone of 'https://github.com/citra-emu/ext-libressl-portable.git' into submodule path '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/libressl' failed
Failed to clone 'externals/libressl' a second time, aborting
```

```
Cloning into '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/soundtouch'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: clone of 'https://github.com/citra-emu/ext-soundtouch.git' into submodule path '/nix/store/607q4hrwwbawqlslbw21agvzff41pz2q-source/externals/soundtouch' failed
Failed to clone 'externals/soundtouch' a second time, aborting
```

</details>

## Additional context

This blocks building reverse dependencies like `retroarchFull`

It happens because the upstream revision requested from https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/emulators/retroarch/hashes.json#L198 links to nonexisting submodules:

https://github.com/libretro/citra/blob/2d67658e85de4767c0eefeb2829d710401c5c802/.gitmodules#L9

https://github.com/libretro/citra/blob/2d67658e85de4767c0eefeb2829d710401c5c802/.gitmodules#L15

https://github.com/libretro/citra/blob/2d67658e85de4767c0eefeb2829d710401c5c802/.gitmodules#L33

## Metadata

This does not depend on the local `nixpkgs` setup as long as it contains the `hashes.json` file pointing to broken revision.

## Notify maintainers

 
@thiagokokada @aanderse @edwtjo

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aanderse** [comment]
unfortunately at this point it seems most reasonable to remove this and wait for https://github.com/azahar-emu/azahar to receive a libretro port, i believe

i wouldn't trust substituting lime3ds in because i'm almost certain nixpkgs maintainers will remove that shortly too... which makes sense because the upstream went into archive mode

**Comment by thiagokokada** [comment]
Should be fixed in https://github.com/NixOS/nixpkgs/pull/357228, since I updated `libretro/citra` to use a newer commit that redirects to mirrors to the submodules that still exist.

We eventually need to replace `libretro/citra` with something more maintained, but this should fix the issue for now.
