### ISSUE TITLE
qtwebengine: build times?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#35688]
## Issue description

Look at: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.qt5.qtwebengine.x86_64-linux#tabs-charts 

Also, it doesn't seem to have finished evaluating recently, IIRC it caused my laptop to run out of memory yesterday :(.

Here's an aborted build where it took over 3 hours? https://hydra.nixos.org/build/70052485

Is this transient or the sign of something that needs fixing?

**Comment by vcunat** [comment]
Here are more details: https://hydra.nixos.org/job/nixpkgs/trunk/qt5.qtwebengine.x86_64-linux#tabs-charts

To me it seems like some significant change between 5.9 and 5.10.

**Comment by vcunat** [comment]
Aha :-D  https://doc.qt.io/qt-5.10/whatsnew510.html
> Updated to be based on Chromium 60.

**Comment by vcunat** [comment]
Hmm, it might still be a too-big jump.

**Comment by vcunat** [comment]
I can't see any non-finishes on Hydra.  The one you pointed to has succeeded, but the request for the build has been aborted in the meantime (Hydra won't cancel running steps due to this).

**Comment by dtzWill** [comment]
Okay, good to know! I'll just be patient then :).  Still, shame it's such a heavy dependency but I suppose that's the cost of progress....

**Comment by vcunat** [comment]
If they bundle half the world just as chromium, I wouldn't really call that approach a progress.

**Comment by dtzWill** [comment]
It finished! \o/ lol.

**Comment by dtzWill** [comment]
Job failed? :cry: 

https://hydra.nixos.org/build/70347972/nixlog/1

**Comment by dtzWill** [comment]
Completed in 25min? Not sure what changed, maybe just builder load or selection, but guess I can close this.
