### ISSUE TITLE
nix-build -A swift       BUILD FAILS

### ISSUE THREAD

**Issue by fragamus** [NixOS/nixpkgs#35689]
## Issue description

/tmp/nix-build-swift-4.0.3.drv-0/src/lldb/include/lldb/Utility/TaskPool.h:122:12: error: no member named 'bind' in namespace 'std'

### Steps to reproduce

git clone git@github.com:NixOS/nixpkgs.git
cd nixpkgs
nix-build -A swift

## Technical details

The hydra build has the same problem I had, which you can see at the end of the build log:

Build log: https://hydra.nixos.org/build/69887235/nixlog/1

Last successful build: https://hydra.nixos.org/build/69575672

**Comment by fragamus** [comment]
This seems to be related to the problem described here:

https://stackoverflow.com/questions/14261013/bind-is-not-a-member-of-std#14261068

**Comment by dtzWill** [comment]
Upstream bug report: https://bugs.swift.org/browse/SR-4838 -- maybe that patch'd do the trick?

**Comment by dtzWill** [comment]
:crying_cat_face: why is the failure so late in this mega-long build?! haha noooooo

Testing a fix now.
