### ISSUE TITLE
virt-viewer: Audio doesn't work

### ISSUE THREAD

**Issue by alex-robbins** [NixOS/nixpkgs#356839]
## Describe the bug

Audio playback seems to be broken with virt-viewer in nixpkgs dc460ec76. When I try to play audio in a VM, I don't hear anything. I see the following lines in virt-viewer's output:
```
(virt-viewer:5129): GSpice-CRITICAL **: 00:06:36.336: connect_channel: assertion 'p->rchannel == NULL' failed

(virt-viewer:5129): GSpice-WARNING **: 00:06:36.355: (../src/spice-session.c:2333):spice_session_channel_new: runtime check failed: (s->playback_channel == NULL)

(virt-viewer:5129): GSpice-CRITICAL **: 00:06:36.356: connect_channel: assertion 'p->pchannel == NULL' failed

(virt-viewer:5129): GSpice-WARNING **: 00:06:44.332: (../src/spice-session.c:2333):spice_session_channel_new: runtime check failed: (s->playback_channel == NULL)

(virt-viewer:5129): GSpice-CRITICAL **: 00:06:44.332: connect_channel: assertion 'p->pchannel == NULL' failed
```

This output and the issue were both absent in nixpkgs 1925c603f1. 

## Steps To Reproduce

1. Start virt-viewer and attempt to play audio in the guest
2. Observe the lack of audio and presence of error output

## Additional context

I am using pipewire.

## Metadata

> Please insert the output of running `nix-shell -p nix-info --run "nix-info -m"` below this line 

I'm using flakes so I don't think these commands work.

## Notify maintainers

@Atemu @7c6f434c 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
Please perform a first-parent bisect between these two commits.

**Comment by alex-robbins** [comment]
I'll give it a go, but won't have a chance until next week. (I haven't tried to use a local nixpkgs repo with flakes yet, so it will take what I hope is only 10 minutes of learning.)

---

In the meantime, I noticed that the steps to reproduce only seem to work one time after each reboot. After seeing the bug, if I close virt-viewer and start it again, audio *does* work. (The good news is that with the reboot, the bug does seem to be completely reproducible, as far as I can tell.)

Additionally, during this time when audio *is* working, when I ask the guest to hibernate (suspend-to-disk), I see two of the same error messages from above (one of each kind). Of course, at this time there's no audio playing, because the guest is going into hibernation. If I ask the guest to shut down instead of hibernate, I do not see the error messages in this case.

## Updated steps to reproduce

1. Reboot
1. Start virt-viewer and attempt to play audio in the guest
2. Observe the lack of audio and presence of error output
3. (Close virt-viewer, start it again, and note that the bug is no longer observable)

## Additional additional context
I am using pipewire. When the bug is active (i.e. audio should be playing but isn't), pavucontrol does not show virt-viewer in its playback tab like it normally would.

**Comment by 7c6f434c** [comment]
Standard questions: is this reboot or is relogin enough? Does the issue appear under a freshly created test user? 

(But I have never used sound with virt-viewer, I think)

**Comment by alex-robbins** [comment]
Good questions. I've learned two things since my last comment:

1. The buggy behavior is not predictably reproducible in the exact way that I thought. Unlike I said in my last comment, audio doesn't *always* start working again the second time I use virt-viewer after a reboot. As far as I can tell, there's no pattern to whether or when a buggy nixpkgs commit will suddenly start or stop working. The good news is that the bug seems very easy to trigger; if the commit is buggy, but you're not currently seeing the bug, it doesn't take long for it to pop up (in my experience so far).
2. The buggy behavior *is* observable with a freshly created user whose home directory starts out empty.

I've started a bisect. It might take a bit. I'm being extra careful not to get any false negatives in light of the fact the even buggy commits sometimes work for short stretches at a time.

Thanks for your patience.

**Comment by alex-robbins** [comment]
Bisect complete, fingering this as the first bad commit:

    43f502117020 qemu: 9.1.0 -> 9.1.1 (#350407)

I saw that qemu has since been updated to 9.1.2, so I tried that, and ... yeah, it works.

So, I'm closing this, as the issue disappears with the new qemu version.
