### ISSUE TITLE
Build failure: cava-0.10.2

### ISSUE THREAD

**Issue by Irgendeinwer** [NixOS/nixpkgs#356817]
## Steps To Reproduce

1. build *cava-0.10.2*

## Build log

<details>

<summary>Build Log</summary>

```
Using versionCheckHook
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: autoreconfPhase
@nix { "action": "setPhase", "phase": "autoreconfPhase" }
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
/nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
/nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:306: the top level
autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
```

</details>

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.7, NixOS, 24.11 (Vicuna), 24.11.20241111.dc460ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4r8s42c9mwfvgdlxv0izb1cmlzrsb5nz-source`

## Notify maintainers

@offlinehacker 
@mirrexagon 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ryan4yin** [comment]
Cava seems to have already been fixed by https://github.com/NixOS/nixpkgs/pull/355948, although the fix is not yet in nixos-unstable.

**Comment by simon-bueler** [comment]
fix in unstable now, no issue for me anymore
