### ISSUE TITLE
bug: neovide from nixpkgs-unstable fails on x86-64_linux

### ISSUE THREAD

**Issue by midirhee12** [NixOS/nixpkgs#356856]
## Describe the bug

Getting the following error from the nixpkgs-unstable version of neovide. Please revert the last week change for now and fix the change in the meantime:
```
       error: Package ‘cctools-1010.6’ in /nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-sourc
e/pkgs/by-name/cc/cctools/package.nix:167 is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-unknown-linux-gnu"
         package.meta.platforms = [
           "x86_64-darwin"
           "i686-darwin"
           "aarch64-darwin"
           "armv7a-darwin"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use a
n environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```

## Steps To Reproduce

1. add neovide from nixpkgs-unstable to package list on x86-64_linux
2. rebuild

## Expected behavior

Build and evaluate without failure.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.05 (Uakari), 24.05.20241116.e8c38b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05, nixos-hardware"`
 - nixpkgs: `/nix/store/ly4s3hw35dd1c2vsd694y2715pc1d2c1-source`

Although, I should add that I am using the package from the `nixpkgs-unstable` flake.

## Notify maintainers

@tjni @ck3d

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by iynaix** [comment]
Already fixed and merged: https://github.com/NixOS/nixpkgs/pull/356292

**Comment by midirhee12** [comment]
Lovely!
