### ISSUE TITLE
24.11: jetbrains.plugins.addPlugins no longer finds github-copilot

### ISSUE THREAD

**Issue by lostmsu** [NixOS/nixpkgs#356840]
## Describe the bug

I am unable to add official GitHub Copilot plugin to Rider (haven't tried with other JetBrains products):

> error: Could not resolve plugin github-copilot

## Steps To Reproduce

1. Config
```nix
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "rider"
      "rider-with-plugins"
    ];

   environment.systemPackages = with pkgs; [
    (jetbrains.plugins.addPlugins jetbrains.rider ["github-copilot" "nixidea"])
    ...
  ];
```

## Expected behavior

Configuration builds. Rider has GitHub Copilot plugin

## Additional context

I believe this is a regression since 24.05

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11beta708443.057f63b6dc1a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager, nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@Followin @wegank

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheToto** [comment]
The copilot plugin name is now `github-copilot-intellij`.

Seen in comments of https://github.com/NixOS/nixpkgs/pull/355566

**Comment by JohnRTitor** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/pull/355697 (they seemed to change it to what it was?)

But I am afraid if upstream changes the plugin name like this, we can't keep up announcing these breaking changes, since this is all automated

**Comment by lostmsu** [comment]
Seems to be fixed now.
