### ISSUE TITLE
`imhex`: EGL: Library not found

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#356975]
## Describe the bug

ImHex wont launch because of missing egl library

## Steps To Reproduce

N/A (Launch ImHex)

## Expected behavior

N/A

## Screenshots

![image](https://github.com/user-attachments/assets/5fdf5dba-c87a-4782-9e9d-14e706852ce0)

## Additional context

N/A

## Metadata

fetching path input 'path:/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 25.05 (Warbler), 25.05.20241115.5e4fbfb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/user/.config/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/nix/store/1c1x2ki3lz5k5nw5z0bl0glizgb0k0rb-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/user/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/user/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/user/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/user/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/kqpjnkkpv1drbnvrqbhnyd2ixy9dymzb-lix-2.91.1/share`
 - nixpkgs: `/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source`
 
## Notify maintainers

@kashw2
@cafkafk 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aktaboot** [comment]
yeah I'm hitting this aswell,
an easy workaround is to find a 'libglvnd' in the nix-store and set LD_LIBRARY_PATH
i.e. `LD_LIBRARY_PATH=/nix/store/wmm60qwckax108ffr8x1fm2xkzmm0vmh-libglvnd-1.7.0/lib/ && imhex`

**Comment by aktaboot** [comment]
#354761 this seems to be the culprit, setting the vulkan variable seems to force it to use vulkan which I don't have enabled, and it doesn't fallback to EGL,

**Comment by Scrumplex** [comment]
I think this is the same issue as #357732

Will be fixed in #358007
