### ISSUE TITLE
Update request: peertube 6.0.4 → 6.3.3

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#357286]
## Package Information

- Package name: peertube
- Latest released version: 6.3.3
- Current version on the unstable channel: 6.0.4
- Current version on the stable/release channel: 6.0.4

## Checklist

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@immae  
@Izorkin
@mohe2015
@stevenroose

https://github.com/Chocobozzz/PeerTube/releases/tag/v6.3.3

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ppom0** [comment]
This should be closed as peertube has been upgraded on unstable.
