### ISSUE TITLE
Build failure: cinny-desktop

### ISSUE THREAD

**Issue by Noodlez1232** [NixOS/nixpkgs#357406]
## Steps To Reproduce

1. build cinny-desktop

## Build log

<details>

<summary>Build Log</summary>

```
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/b8fly5g7gba7fnw1s83am9v1c5rgp3wd-source
source root is source/src-tauri
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/hrca7s044i3v9apn5w33mgxl36p7xird-cinny-desktop-4.2.3-vendor.tar.gz
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
substituteStream() in derivation cinny-desktop-4.2.3: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'tauri.conf.json')
substituteInPlace called without any files to operate on (files must come before options!)
```

</details>

## Additional context
This package doesn't seem to be checked by CI because of its security vuln in libolm. It seems they may be working towards fixing that, but for now, it is what it is I feel.

~~Also there seems to be an issue open for already existing problems with this package:~~ irrelevant issue

## Notify maintainers

@ryand56 @Qyriad 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ryand56** [comment]
Can reproduce, will fix soon

**Comment by Noodlez1232** [comment]
> Can't seem to fix this due to libayatana-appindicator not being found somehow?

This is because libappindicator-sys isn't being used anymore. It' just using the gtk3 bindings from here on out, apparently.

**Comment by Noodlez1232** [comment]
I'm actually trying out a patchelf approach right now.

**Comment by Noodlez1232** [comment]
Even though `libayatana-appindicator` is needed, I *cannot* get it to actually show anything once starting up (indicating it not finding the libayatana-appindicator binary)

**Comment by Noodlez1232** [comment]
Even checking the headers to see what symbols are needed, none of them are from any sort of libappindicator library.

**Comment by Noodlez1232** [comment]
Okay I got it building and running but with no system tray support.
