### ISSUE TITLE
Package request: television

### ISSUE THREAD

**Issue by unhitched9271** [NixOS/nixpkgs#357460]
## Project description

A blazingly fast general purpose fuzzy finder for your terminal written in Rust.
It is inspired by the neovim [telescope](https://github.com/nvim-telescope/telescope.nvim) plugin and is designed to be fast, efficient, simple to use and easily extensible. It is built on top of [tokio](https://github.com/tokio-rs/tokio), [ratatui](https://github.com/ratatui/ratatui) and the nucleo matcher used by the [helix](https://github.com/helix-editor/helix) editor.
## Metadata

* homepage URL: https://github.com/alexpasmantier/television
* source URL: https://github.com/alexpasmantier/television
* license: mit
* platforms: unix, linux, darwin, ...

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
See https://github.com/NixOS/nixpkgs/pull/357237

**Comment by unhitched9271** [comment]
Thank you!
