### ISSUE TITLE
curl: move to hyper backend

### ISSUE THREAD

**Issue by milibopp** [NixOS/nixpkgs#357409]
## Project description

Hyper and curl are [looking for Linux distributions](https://seanmonstar.com/blog/hyper-in-curl-needs-a-champion/) to ship curl with hyper as an HTTP backend. The work is almost done, but not quite and they want someone (a Linux distro, e.g.) to commit to shipping it.

We already include rustls as an optional dependency for curl. Supporting hyper-ffi seems fairly similar.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by milibopp** [comment]
cc @seanmonstar @lovek323

**Comment by milibopp** [comment]
Updated title according to [this suggestion](https://github.com/NixOS/nixpkgs/pull/357552#pullrequestreview-2448540153).

**Comment by niklaskorz** [comment]
> I asked about it on matrix yesterday and @K900 said that we can’t as curl is part of nixpkgs bootstrap, sadly

In what sense? That bootstrap can't have Rust dependencies?

**Comment by K900** [comment]
It can, in theory, but we'd have to pull Rust into the bootstrap, which is a long and rather painful process, or we'd need to have two differently behaving versions of curl in the bootstrap and the final system, which is also not great.

**Comment by niklaskorz** [comment]
Curl has officially removed hyper support: https://daniel.haxx.se/blog/2024/12/21/dropping-hyper/
