### ISSUE TITLE
Package request: Desktop app for Ente Photos

### ISSUE THREAD

**Issue by vinylen** [NixOS/nixpkgs#357531]
## Project description

Ente is according to their github:
> Fully open source, End to End Encrypted alternative to Google Photos and Apple Photos

They've open-sourced their entire stack 8 months ago. 

## Metadata

* homepage URL: https://ente.io/
* source URL: https://github.com/ente-io/ente/tree/main/desktop
* license: AGPL-3.0
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Part of https://github.com/NixOS/nixpkgs/issues/292641

**Comment by vinylen** [comment]
Closing in favour of #292641
