### ISSUE TITLE
Clicking on the weather button on gnome's calendar/notifications dropdown doesn't open Weather

### ISSUE THREAD

**Issue by stereomato** [NixOS/nixpkgs#357955]
## Describe the bug

Title
## Steps To Reproduce

1. Open the notifications/calendar dropdown
2. Click on the weather button/panel
3. Nothing happens

## Expected behavior

The weather app opens

## Additional context

journalctl -e
```
nov 21 13:05:15 hostname dbus-daemon[3062]: [session uid=1000 pid=3062] Activating service name='org.gnome.Weather' requested by ':1.11' (uid=1000 pid=3431 comm="/nix/store/36yjhzacpy971k4ahdlbk7ymabdgkkag-gnome-" label="kernel")
nov 21 13:05:15 hostname dbus-daemon[3062]: [session uid=1000 pid=3062] Activated service 'org.gnome.Weather' failed: Failed to execute program org.gnome.Weather: No such file or directory

```
## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.0, NixOS, 25.05 (Warbler), 25.05.20241119.23e89b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/c9wv7i0af6mysmy65x6nvyfw5izzxv4g-source`

## Notify maintainers

@jtojnar @bobby285271 @hedning @dasj19 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by poopsicles** [comment]
Clicking `Weather` in the application menu appears to give me the same logs,,,but running `gnome-weather` from a terminal works.

When run this way, both the Clock menu widget and Applications menu entry switch to it when clicked, but once it's closed, they give that same log about a missing service.

I can find the service though:

```
$ cat /run/current-system/sw/share/dbus-1/services/org.gnome.Weather.service
[D-BUS Service]
Name=org.gnome.Weather
Exec=gnome-weather --gapplication-service

$ file /run/current-system/sw/share/dbus-1/services/org.gnome.Weather.service
/run/current-system/sw/share/dbus-1/services/org.gnome.Weather.service: symbolic link to /nix/store/3859xf3xqmhrdkzs3si3szbr51y40cam-gnome-weather-47.0/share/dbus-1/services/org.gnome.Weather.service
```

But it's not in the DBus file generated by NixOS at `/etc/dbus-1/system.conf`:

```
$ grep -i weather /etc/dbus-1/system.conf
```

But there's tons other GNOME things in there...

**Comment by jtojnar** [comment]
This is regression caused by https://github.com/NixOS/nixpkgs/commit/dc278337657dcdfdf632109b0769384109a7ec0e. I thought @bobby285271 reverted it but I cannot find the revert commit now.

**Comment by bobby285271** [comment]
> I thought @bobby285271 reverted it

That is gnome-maps d37e098e8dc8ccf6562122b33d54f509c9b089f2. So yeah dc278337657dcdfdf632109b0769384109a7ec0e should be reverted with the same reason.
