### ISSUE TITLE
Update request: tree-sitter html grammar

### ISSUE THREAD

**Issue by idlip** [NixOS/nixpkgs#358157]
Hi all!

The html parser is very behind, which is causing SIGSEGV crash in neovim and emacs.
1. https://github.com/tree-sitter/tree-sitter-html/issues/102
2. https://yhetil.org/emacs-bugs/87y13uuk79.fsf@cassou.me/

The amaanq also suggest to update parser grammar.

@DamienCassou tagging you since you take care of tree sitter and grammar for emacs. Since you also faced the issue.

**Comment by DamienCassou** [comment]
I already fixed that in https://github.com/NixOS/nixpkgs/pull/355501 which has been merged into `staging`. I believe we just need to wait for `staging` to be merged back to `master`. I will close the issue. Feel free to reopen if you believe there is something more to do.

**Comment by idlip** [comment]
Sorry I missed it then. Got it. Thank you!
