### ISSUE TITLE
Out of memory error from Cairo when creating PDF from Xournal++

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#358284]
## Describe the bug

This has only happened for a single file, but is 100% reproducible.

Workaround:

1. Click the "Print" button
2. Select "Print to PDF"
3. Select output format "Postscript"
4. Click "Print"
5. Use `nix-shell --packages ghostscript_headless --run 'ps2pdf IN.ps OUT.pdf'` to convert to PDF

## Steps To Reproduce

1. Open a .xopp file in Xournal++
3. Click the "Export as PDF" button
4. Click "Save"

At this point I get the following error:

> Error while finalizing the Cairo surface
> Cairo error: out of memory

The broken output PDF is on the order of 200 kB. If I try to open it using Evince, it says "PDF document is damaged", with no further details.

Alternatively:

1. Open a .xopp file in Xournal++
2. Click the "Print" button
3. Select "Print to PDF"
6. Click "Print"

At this point I get no error message, but the output PDF is also broken.

## Expected behavior

The PDF file should be created successfully.

## Screenshots

![image](https://github.com/user-attachments/assets/026370c0-e8e4-44f9-a87c-6f787c1f6206)

## Additional context

Unfortunately the PDF has personal info, so I can't post it here. But some relevant pieces of information:

- I had to add some [font substitutions](https://gitlab.com/engmark/root/-/commit/0e1892040ef8c526669b7118d7efdb735601b571) for the contents to render properly. This is my best bet for what could be causing this issue.
- I am able to export other .xopp files to PDF without issues.
- The input PDF is less than 350 kB, and the .xopp file is less than 40 kB. The output PDF size after using the workaround above is 101 kB.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.62, NixOS, 25.05 (Warbler), 25.05beta710087.23e89b7da85c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager, nixos, nixos-hardware, nixos-stable-24.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

Ping @trofi @alyssais @figsoda  as recent contributors.

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ppenguin** [comment]
This appears to be caused by a regression introduced in September in `18.2.` and was alledgedly fixed [by this commit](https://gitlab.freedesktop.org/cairo/cairo/-/commit/b9eed915f9a67380e7ef9d8746656455c43f67e2).

I worked around this with an overlay (no time to do more this week):

```
final: prev: {
  cairo = prev.cairo.overrideAttrs (fattr: pattr: {
    src = prev.fetchFromGitLab {
      domain = "gitlab.freedesktop.org";
      owner = "cairo";
      repo = "cairo";
      rev = "33173d9f1a79a58d518ffbe0e597bd4ca9bf1464";
      sha256 = "sha256-9Upzj0SlEwwjQ6dtqrYAxDtBo3um3MXyRi8xQH0UFwk=";
    };
    buildInputs = pattr.buildInputs ++ [prev.lzo];
  });
}
```

This is still extremely painful due to `cairo` being very deep in your typical dep graph (so _huge_ rebuild)

:warn: Not confirmed yet, still building (hope I don't get an OOM on libreoffice or qtwebengine or some such)

If you have work to do, better get a `nixos-unstable` from about a week back I guess.

**Comment by trofi** [comment]
Great find! I proposed the `nixpkgs` PR with this patch as:
- https://github.com/NixOS/nixpkgs/pull/359029
