### ISSUE TITLE
Kitty - finder does not have permission to open null

### ISSUE THREAD

**Issue by YR-ZR0** [NixOS/nixpkgs#358208]
## Describe the bug

kitty terminal does not launch on MacOS Sequoia 15.1.1, launching the kitty.app file in any way results in 
`The application Finder/Dock does not have permission to open "(null)".`

## Steps To Reproduce

Steps to reproduce the behaviour:

1. define kitty as a package in your nix config
2. run `darwin-rebuild switch --flake flake.nix`
3. Attempt to launch kitty in any form using the app entry

## Expected behaviour

Kitty Launches successfully

## Additional context

Kitty was launching before the latest update to 15.1.1

There were some under-the-hood changes made to how Apple runs unsigned software
https://developer.apple.com/news/?id=saqachfa

Some steps tried were:
- running `codesign` to resign the app
- Running `xattr` to remove any kind of marker, such as the quarantine marker

## Metadata
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/69bhrhj8imx84l6zvdz0zmh3qc8ykwvd-source
```
## Notify maintainers
@Luflosi @rvolosatovs @tex @kashw2 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by carlossless** [comment]
Possibly same issue as what was addressed in https://github.com/NixOS/nixpkgs/pull/352795 ?

**Comment by carlossless** [comment]
@YR-ZR0 you should be able to just pull it from latest `nixpkgs-unstable`

**Comment by YR-ZR0** [comment]
Hi @carlossless, a `nix flake update` fixed the issue, thanks for helping on this issue.
