### ISSUE TITLE
LuaLaTex fails due to segmentation fault/missing lualatex.fmt

### ISSUE THREAD

**Issue by sondr3** [NixOS/nixpkgs#35839]
## Issue description
I've installed the full TeX Live (2017) package and I keep getting an error when I try to run it with LuaLaTeX. With PDFLaTeX and XeTeX it works fine, but I'm using some packages and scripts that only work with LuaLaTeX. When I run it I get this error:

```shell
Transcript written on lualatex.log.
sh: line 1: 24024 Segmentation fault      luatex -ini -jobname=lualatex -progname=lualatex lualatex.ini 1>&2 < /dev/null
mktexfmt [ERROR]: running `luatex -ini   -jobname=lualatex -progname=lualatex lualatex.ini >&2 </dev/null' return status 139
mktexfmt [ERROR]: return error due to options --strict
mktexfmt [INFO]: Disabled formats: 6
mktexfmt [INFO]: Not selected formats: 43
mktexfmt [INFO]: Failed to build: 1 (luatex/lualatex)
mktexfmt [INFO]: Total formats: 50
mktexfmt [INFO]: exiting with status 1
I can't find the format file `lualatex.fmt'!
```

If I run `lualatex -ini lualatex.ini` in the directory that I'm working in however the document compiles, but then I get another error:

```shell
fish: “lualatex MNF130WeeklyAssignment…” terminated by signal SIGSEGV (Address boundary error)
```

If I run it in Bash then I get a segmentation fault instead.

### Steps to reproduce
1. Install `nixos.texlive.combined.scheme-full`
2. Try to use LuaLaTeX on any .tex file
3. The errors occur

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```shell
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.82, NixOS, 17.09.3031.d09e425aea3 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3076.38d7371dddd, unstable-18.03pre129212.098c7f3d945"`
 - channels(sondre): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by dtzWill** [comment]
Can reproduce on master and staging.

Possibly this: https://www.tug.org/pipermail/tex-live/2017-June/040192.html
