### ISSUE TITLE
kicad — build error

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#35836]
## Issue description

When trying to install kicad, it tries to build it and says:

In file included from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/strconv.h:17:0,
                 from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/strvararg.h:20,
                 from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/string.h:46,
                 from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/memory.h:15,
                 from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/object.h:19,
                 from /nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/wx.h:15,
                 from /tmp/nix-build-kicad-4.0.7.drv-0/kicad-4.0.7/include/fctsys.h:28,
                 from /tmp/nix-build-kicad-4.0.7.drv-0/kicad-4.0.7/eeschema/tool_sch.cpp:30:
/nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/buffer.h: In member function 'virtual void SCH_EDIT_FRAME::ReCreateVToolbar()':
/nix/store/rsbfjjd3xgs7i5ggb2rjy0j19ryvwxly-wxwidgets-3.0.3.1/include/wx-3.0/wx/buffer.h:127:9: internal compiler error: Segmentation fault
         DecRef();
         ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [eeschema/CMakeFiles/eeschema_kiface.dir/build.make:3486: eeschema/CMakeFiles/eeschema_kiface.dir/tool_sch.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:997: eeschema/CMakeFiles/eeschema_kiface.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
builder for ‘/nix/store/i7syrigdh67fn81al0id3x02jdya3fj0-kicad-4.0.7.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/9bnv6c4lb0kkx861yj3d4zjccjc3j4jy-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/2al26s56add0qvr73y6g0al92kshsb5x-nixos-system-ivanych-17.09.3047.8bce347f02f.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/2al26s56add0qvr73y6g0al92kshsb5x-nixos-system-ivanych-17.09.3047.8bce347f02f.drv’ failed

Tried to build it several times and got approx the same but in different places.
Finally (after 3 builds by nixos-rebuild boot) — success.
Do not understand.

### Steps to reproduce

I install packages by putting it name in environment.systemPackages list.
I just tried to install kicad (by nixos-rebuild boot).

## Technical details
\# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.21, NixOS, 17.09.3047.8bce347f02f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3047.8bce347f02f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bjornfor** [comment]
I think "internal compiler error: Segmentation fault" is Linux killing the compiler due to OOM. Kicad builds for me on recent master (79a7f9524c9c7638cee213c67d88d3edba88bd38) and release-17.09 (c5bc83b503dfb29eb27c1deb0268f15c1858e7ce). 

(Perhaps you got it working after the reboot due to less memory being in use by other processes, than when the system had been running for a while?)

**Comment by comonoid** [comment]
At that moment, there was approx. 4—5Gb free memory (8Gb total)...
> Perhaps you got it working after the reboot

No...
Maybe there was (when build was successfull) even less (slightly) memory...
But i will watch more carefully, thanks!

**Comment by bjornfor** [comment]
Check the system log (journalctl ...). It should list some OOM stuff from the kernel if that's what happened.

**Comment by comonoid** [comment]
journalctl --since today — nothing suspicious...
I will try it with the next upgrade and watch for the memory very carefully
(there is an upgrade but zathura can't install it, i think there would be the next one pretty soon).

**Comment by comonoid** [comment]
Now 17.09.3099.ebe462bdc94
while (true) ; do cat /proc/meminfo | grep MemAvailable | sed "s/MemAvailable:    //"; sleep 0.1; done > freeMem.txt
and then sort it ;-)
Maybe awk would be more appropriate but "this" immediately came in mind ;-)

Minimum free (during nix-rebuild) memory was 3 934 984 kB.
All is ok...
Will try to repeat it with 3G memory free (there was more during that build) and watch...

Maybe it worth to close ticket...
And open it later...

**Comment by comonoid** [comment]
Don't know why ­— now it works for me...
Thanks!
