### ISSUE TITLE
Teamviewer fails to build

### ISSUE THREAD

**Issue by Krofek** [NixOS/nixpkgs#35850]
## Issue description

Upon installing the teamviewer package or enabling the teamviewer service it fails on build.

### Steps to reproduce

`nix-env -f "<nixpkgs>" -iA teamviewer`

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.66, NixOS, 18.03.git.090ccf6 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3, nixpkgs-17.09pre105126.efe12d6658"`
 - nixpkgs: `/etc/nixos/nixpkgs

**Comment by dtzWill** [comment]
Apparently this wants 32bit deps, and 32bit on NixOS has been deprecated.

The particular error does seem unexpected, though...
