### ISSUE TITLE
Package request: mysql/mysql-connector-cpp

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#358513]
## Project description

MySQL connector library for C++.

It is required for newer version of Perl [DBD-mysql](https://metacpan.org/dist/DBD-mysql/).

## Metadata

* homepage URL: https://github.com/mysql/mysql-connector-cpp
* source URL: https://github.com/mysql/mysql-connector-cpp
* license: GPLv2 with exceptions
* platforms: unix

cc maintainer of mariadb-connector @globin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TomaSajt** [comment]
AFAICT [libmysqlconnectorcpp](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=libmysqlconnectorcpp) is what you're looking for.

The source used is not the github one, but the repo layout seemed identical, so I'm assuming it's the same thing.

**Comment by FliegendeWurst** [comment]
You are probably right, thank you. I will check whether it works for the perl package.
