### ISSUE TITLE
f3d (from nixpkgs) watch option seems to be ignored when set from the configuration file

### ISSUE THREAD

**Issue by gautaz** [NixOS/nixpkgs#358655]
## Describe the bug

This is related to f3d-app/f3d#1726.
While investigating the issue, it seems that it only occurs for the f3d version from nixpkgs (master).

## Steps To Reproduce

1. Start viewing a 3MF file with f3d while using a configuration file enabling the `watch` option
2. Modify the 3MF file, nothing happens
3. press the up key, the modification is displayed

## Expected behavior

The nixpkgs version of f3d should update the view automatically when the 3MF file is modified.

## Screenshots

N/A

## Additional context

See f3d-app/f3d#1726.

As for the version of f3d I compiled myself which is not reproducing the issue, it was build in a nix-shell environment:
```nix
{pkgs ? import <nixpkgs> {}}:
pkgs.mkShell {
  name = "custom-f3d";
  buildInputs = with pkgs; [
    assimp
    cmake
    vtk
  ];
}
```

The build occurred on my platform (`hepao`) which is installed with [this flake](https://github.com/gautaz/phoenix).

## Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.62, NixOS, 25.05 (Warbler), 25.05.20241120.34d63c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

## Notify maintainers

@bcdarwin
@pbsds

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pbsds** [comment]
I think we can close this, since this is about functionality
