### ISSUE TITLE
keepalived: needs update

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#35867]
## Issue description
keepalived 1.42 is out with lots of fixes. 

This holds for `master`.

**Comment by dotlambda** [comment]
That would be a good opportunity for your first pull request :smile:

**Comment by pbogdan** [comment]
1.4.2 is in master as of few hours ago - https://github.com/NixOS/nixpkgs/commit/0eef30247515f107187a67b3d7325699abaa1fa2 (I presume that's the version coretemp was referring to).
