### ISSUE TITLE
Build failure: iptsd

### ISSUE THREAD

**Issue by ShawkMusic** [NixOS/nixpkgs#358627]
## Steps To Reproduce

1. run `sudo nixos-rebuild switch --upgrade`

## Build log

<details>

<summary>Build Log</summary>

```
warning: the following units failed: iptsd.service
× iptsd.service - IPTSD
     Loaded: loaded (/etc/systemd/system/iptsd.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Sun 2024-11-24 00:02:58 EST; 435ms ago
   Duration: 62ms
 Invocation: bd67c692499347059e2fc5197cd46b29
    Process: 8178 ExecStart=/nix/store/5xn3qp3bz6sq92m0pvsfxz9w8ypc0chr-unit-script-iptsd-start/bin/iptsd-start (code=exited, status=106)
   Main PID: 8178 (code=exited, status=106)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
   Mem peak: 2.4M
        CPU: 58ms

Nov 24 00:02:58 nix-surface systemd[1]: Started IPTSD.
Nov 24 00:02:58 nix-surface iptsd-start[8179]: [00:02:58.475] [warning] iptsd-find-hidraw is deprecated, please use iptsd-foreach
Nov 24 00:02:58 nix-surface iptsd-start[8213]: xargs: bash: No such file or directory
Nov 24 00:02:58 nix-surface iptsd-start[8215]: DEVICE is required
Nov 24 00:02:58 nix-surface iptsd-start[8215]: Run with --help for more information.
Nov 24 00:02:58 nix-surface systemd[1]: iptsd.service: Main process exited, code=exited, status=106/n/a
Nov 24 00:02:58 nix-surface systemd[1]: iptsd.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration

```

</details>

## Additional context

Using a Surface Pro 6, using `<nixos-hardware/microsoft/surface/surface-pro-intel>`

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.9, NixOS, 25.05 (Warbler), 25.05beta710087.23e89b7da85c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@tomberek @dotlambda 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dotlambda** [comment]
You're using an ancient version of nixos-hardware that doesn't include https://github.com/NixOS/nixos-hardware/commit/27487bcd12139b8b20442252e1fc3895d4394ce1.
