### ISSUE TITLE
Package request: Binary

### ISSUE THREAD

**Issue by keirlawson** [NixOS/nixpkgs#358773]
## Project description

Binary is a simple app that converts numbers between binary, decimal, hexadecimal and octal bases.

## Metadata

* homepage URL: https://apps.gnome.org/Binary/
* source URL: https://github.com/fizzyizzy05/binary
* license: gpl3
* platforms: linux

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Already exists as `binary`: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/bi/binary/package.nix
