### ISSUE TITLE
`heroic`: `gamescope` does not work

### ISSUE THREAD

**Issue by griffi-gh** [NixOS/nixpkgs#358847]
## Describe the bug

Games with gamescope enabled in heroic won't launch

## Steps To Reproduce

1. Enable gamescope in NixOS options (`programs.gamescope`, with renice wrapper enabled if that matters)
2. Enable gamescope upscaling for any game in Heroic (under the "Other" section)
3. Try to launch it (nothing happens)

## Expected behavior

Game should launch under Gamescope

## Screenshots

N/A

## Additional context

N/A

## Metadata

fetching path input 'path:/nix/store/c9wv7i0af6mysmy65x6nvyfw5izzxv4g-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.0, NixOS, 25.05 (Warbler), 25.05.20241119.23e89b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/user/.config/nix/nix.conf:/nix/store/yl21ai9izy3yvv2gdfb7yamn6mn76gll-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/nix/store/yl21ai9izy3yvv2gdfb7yamn6mn76gll-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/nix/store/yl21ai9izy3yvv2gdfb7yamn6mn76gll-plasma-workspace-6.2.3/etc/xdg/nix/nix.conf:/nix/store/ya7vhc1j80aq3vn643k2sq4i7c2vsqr1-kglobalacceld-6.2.3/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/user/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/user/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/user/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/user/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/user/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/fxd5sw0bdnffmv4cvpj1rl6kvpz93xqq-lix-2.91.1/share`
 - nixpkgs: `/nix/store/c9wv7i0af6mysmy65x6nvyfw5izzxv4g-source`
 
## Notify maintainers

@aidalgol 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by griffi-gh** [comment]
Seems to work without renice enabled?

**Comment by aidalgol** [comment]
I'm not sure why disabling `renice` is having an effect, but you need to add `gamescope` to the `heroic` FHS env.
```nix
    (heroic.override {
      extraPkgs = pkgs: [
        pkgs.gamescope
      ];
    })
```
(In addition to enabling it via the NixOS module, which you have already done.)  Could you please try this?

I know this needs to be documented somewhere; I'm just not sure where.  Perhaps just a page on the NixOS wiki.

**Comment by griffi-gh** [comment]
> I'm not sure why disabling `renice` is having an effect, but you need to add `gamescope` to the `heroic` FHS env.
> 
> ```nix
>     (heroic.override {
>       extraPkgs = pkgs: [
>         pkgs.gamescope
>       ];
>     })
> ```
> 
> (In addition to enabling it via the NixOS module, which you have already done.) Could you please try this?
> 
> I know this needs to be documented somewhere; I'm just not sure where. Perhaps just a page on the NixOS wiki.

because enabling the renice option moves the gamemode executeable to wrappers directory as an execute-only (non-world-readable) binary owned by root.  
for some reason that trips up heroic (but i can still launch it normally using the command)

**Comment by aidalgol** [comment]
Heroic wiki page added: https://wiki.nixos.org/wiki/Heroic_Games_Launcher
