### ISSUE TITLE
opencv3: pkg-config has a bogus path

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#35886]
## Issue description
The `.pc` file I get with opencv3 (opencv-3.4.0) on darwin begins like so,

```
# Package Information for pkg-config

prefix=/nix/store/q7chwknawcpzi427hqnhgk44r3qr26b0-opencv-3.4.0
exec_prefix=${prefix}
libdir=${exec_prefix}//nix/store/q7chwknawcpzi427hqnhgk44r3qr26b0-opencv-3.4.0/lib
includedir_old=${prefix}/include/opencv
includedir_new=${prefix}/include
```

This results in a non-existent `libdir` and so a warning during linking if the `pkg-config` flags get pulled into a build.

### Steps to reproduce

Build opencv3 on darwin.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
- system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixpkgs-18.03pre124071.310ad4345bb"`
 - nixpkgs: `/Users/acowley/src/nixpkgs`
```

**Comment by acowley** [comment]
I could fix this with `sed`. Something like,

```
sed 's|set(libdir      "\${exec_prefix}/${OPENCV_LIB_INSTALL_PATH}")|set(libdir      "${OPENCV_LIB_INSTALL_PATH}")|' -i ./cmake/OpenCVGenPkgconfig.cmake
```

would fix it I think, but perhaps someone has a better fix. I think the issue is that we want libraries to have install names of their full path, but some build tooling is expecting a relative path.

If the `sed`-style fix is okay, I can open a PR with that.

**Comment by bjornfor** [comment]
Ugh, same type of issue as in https://github.com/NixOS/nixpkgs/issues/35143. I wonder if we can validate the .pc files somehow, in the generic builder, to prevent issues like these. Iterate over standard .pc variables representing paths and check if they exist?

**Comment by acowley** [comment]
I guess that'd require a `pkg-config` evaluator of some sort to handle definitions and substitution. You can just about chop off the lines before `Name:`, run it through bash, and look at what variables are set. I took a very quick stab at this, and had a bit of trouble with other shell variables showing up, so we could whitelist which variables to look at as you suggest, or have a heuristic for path-like values.

**Comment by dezgeg** [comment]
Can't you just let pkg-config itself parse the files? :P

**Comment by bjornfor** [comment]
I saw pkg-config has a --validate flag, but it doesn't catch broken paths :-(

**Comment by acowley** [comment]
That would be easier, yes 😅

So we can do `pkg-config --libs-only-L opencv` and `pkg-config --cflags-only-I opencv` and check that those directories exist. Where would this test go? Also, the name registered with `pkg-config` isn't always easy to guess, so that might be mildly tricky. Perhaps making this opt-in with an e.g.  `checkPkgConfig="opencv";` attribute could trigger it.

-------

It turns out the `sed` for opencv would have to hit this line in a cmake file,

```
set(OPENCV_PC_LIBS
  "-L\${exec_prefix}/${OPENCV_LIB_INSTALL_PATH}"
  "${_modules}"
)
```

Should I PR the addition of a patch file to do that or is `sed` okay?

**Comment by matthewbauer** [comment]
Another option for this would be to just run the cc compiler and see if there is an error. For instance,

```
echo 'int main() {}' | cc `pkg-config --libs glib-2.0` -x c -
```

**Comment by bjornfor** [comment]
On second thought, wouldn't a command like that always succeed in a Nix build environment where glib is available, due to how Nix (or the standard builder) sets up include paths for the compiler?

**Comment by dezgeg** [comment]
But you don't get an compiler error if an include path in `-I` doesn't exist.

**Comment by bjornfor** [comment]
Assuming the test program adds a "#include <foo.h>" then?

**Comment by dezgeg** [comment]
How do you locate a file which is safe to include?

Keep in mind that some packages supply flags like `-I$dev/include/foo-pkg/foo-2.0` so you can't just pick a file from `$dev`.

**Comment by bjornfor** [comment]
Right. It may not be something that can be fully automated for all packages, but manually picking a header file to test per package, if the principle works, would at least prevent regressions like these.

**Comment by dezgeg** [comment]
I think the approach of iterating over the output of `pkg-config --cflags $foo` for every `foo` in `$dev/lib/pkgconfig/*.pc` and check if there is an `-I/some/absolute/path` where the directory doesn't exist is simple and effective enough.
