### ISSUE TITLE
uwsm: starting apps with uwsm have random paths added

### ISSUE THREAD

**Issue by MrSom3body** [NixOS/nixpkgs#358805]
## Describe the bug

After enabling uwsm programs that are started with `uwsm app -- program` have some nix paths added. This leads to running bash instead of bashInteractive in a terminal.

## Steps To Reproduce

1. Enable uwsm
2. Open terminal with `uwsm app --foot`
3. Try to run `bash`
4. See `bash: shopt: progcomp: invalid shell option name` and weird rendering

## Expected behavior

No new paths added.

## Screenshots

With uwsm app -- foot:
![image](https://github.com/user-attachments/assets/900e4155-cef3-472b-bb02-db149e7614b4)
![image](https://github.com/user-attachments/assets/a1aa8477-f94b-4691-a5ad-a0fa9d077b2f)

Should be:
![image](https://github.com/user-attachments/assets/b737160b-7445-44db-baef-9d6b939d3884)

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.8, NixOS, 25.05 (Warbler), 25.05.20241115.5e4fbfb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/karun/.config/nix/nix.conf:/nix/store/gqpgq34fbzmxaak73j7a1jkph5v3chav-stylix-kde-config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/karun/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/karun/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/karun/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/kqpjnkkpv1drbnvrqbhnyd2ixy9dymzb-lix-2.91.1/share`
 - channels(root): `"home-manager, nixos-24.05"`
 - nixpkgs: `/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source`

## Notify maintainers

@JohnRTitor @kai-tub 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
Yeah, it's because we are wrapping uwsm with bash and other packages, else it won't work because it won't find the dependencies at runtime (it's just a python script). https://github.com/NixOS/nixpkgs/blob/23e89b7da85c3640bbc2173fe04f4bd114342367/pkgs/by-name/uw/uwsm/package.nix#L66-L83

This however, leaks the dependencies to any of it's subprocesses/processes launched with it.

To be honest I really don't like the wrapping approach, but here's the fix anyway https://github.com/NixOS/nixpkgs/pull/358883
