### ISSUE TITLE
oraclejdk spectre/meltdown update 8u161 -> 8u162

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#35890]
## Issue description

http://www.oracle.com/technetwork/security-advisory/cpujan2018-3236628.html

### Steps to reproduce

We have 8u161.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by wucke13** [comment]
Judging from a quick search I came to the assumption that we have 8u172?
https://nixos.org/nixos/packages.html#8u1 . Maybe your system is outdated - if your provide the output of the command mentioned under "Technical details" in your issue we can know for sure.

**Comment by volth** [comment]
there is about  ```7u161``` and ```8u152```

**Comment by wucke13** [comment]
I am sorry to say that, but I do not understand what your about to say @volth . Java version `7 is on update 111 build 01`, and java 8 is on `update 172 build 02` according to the current nixos-stable repos.

**Comment by dtzWill** [comment]
Oh maybe we have them as "psu" variants?

Not sure what that's about, see no mention of CPU/PSU tags on the download site linked to by our expressions.
( http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html )

Oh, according to http://www.oracle.com/technetwork/java/javase/cpu-psu-explained-2331472.html
the CPU are odd numbers and PSU are evens.  So I guess these fixes aren't considered critical?

Shrug, okay! I just wanted to make sure we had whatever fixes we were supposed to.

TIL.
