### ISSUE TITLE
Hyper-V triggered shutdown does not work

### ISSUE THREAD

**Issue by ljani** [NixOS/nixpkgs#35902]
## Issue description
If I trigger a shutdown via `Stop-VM` on Hyper-V host, NixOS won't shut down. `sudo shutdown` on the guest works.

The shutdown message is successfully received and [logged](https://github.com/torvalds/linux/blob/v4.15/drivers/hv/hv_util.c#L177-L178), but nothing happens. I tracked Hyper-V's Integration Services to [call `orderly_poweroff`](https://github.com/torvalds/linux/blob/v4.15/drivers/hv/hv_util.c#L127-L130), but I'm not sure if it's ever called or what is the problem. Are there any other logs

### Steps to reproduce

- Install NixOS 18.03 guest on Hyper-V and set `virtualisation.hypervGuest.enable = true`
- Try triggering shutdown on the host by `Stop-VM` or via the shut down button in the GUI
- Wait

## Technical details

```
[jani@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.6, NixOS, 18.03pre129909.c5be8a4a236 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129909.c5be8a4a236"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

[jani@nixos:~]$ journalctl | grep graceful
Feb 27 23:06:30 nixos kernel: hv_utils: Shutdown request received - graceful shutdown initiated
```

Also tested on `Linux 4.14.22`.

**Comment by volth** [comment]
I would try ```services.acpid.enable = true```

**Comment by ljani** [comment]
@volth Thanks for the suggestion, but no luck.

**Comment by peterhoeg** [comment]
We run NixOS on a number of Hyper-V servers (2012, R2 and 2016) and are not seeing this problem. It is however, using 17.09. Can you by chance try with that? We haven't started testing 18.03 yet.

**Comment by ljani** [comment]
@peterhoeg I initially chose 18.03 because `virtualisation.hypervGuest.enable` was not available in 17.09, but I'll try 17.09 later this week.

**Comment by ljani** [comment]
@peterhoeg Hey, great, `Stop-VM` with 17.09 works! Here's my current config:

```
{ config, pkgs, options, ... }:

let
  unstable = import <nixos-unstable> {
    virtualisation.hypervGuest.enable = true;
  };
in {
  imports =
    [
      ./hardware-configuration.nix
    ];

# ...
}
```

So, this seems like a regression.

**Comment by peterhoeg** [comment]
>   virtualisation.hypervGuest.enable was not available in 17.09
>   So, this seems like a regression.

We are using 17.09 but with the HyperV bits backported - that explains it.

Are you using the latest kernel or 4.9?

**Comment by ljani** [comment]
@peterhoeg I was on 4.9, but I tested `kernelPackages = pkgs.linuxPackages_latest;` just now and it seems to work fine as well.

```
[jani@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 17.09.3099.ebe462bdc94 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(jani): `""`
 - channels(root): `"nixos-17.09.3099.ebe462bdc94"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by peterhoeg** [comment]
When 18.03 branches off, I'll be testing it on HyperV. I'll update this issue with findings.

**Comment by ljani** [comment]
@peterhoeg I saw your PRs related to Hyper-V, and I'm happy to report that this now works for me in 18.09. Many thanks!
