### ISSUE TITLE
rmapi 0.0.25 is broken, requesting backport to 24.11

### ISSUE THREAD

**Issue by jolars** [NixOS/nixpkgs#359111]
## Describe the bug

As suggested in https://github.com/NixOS/nixpkgs/pull/355090, rmapi 0.0.25 (current version in 24.11) is broken: 

```shell
$ rmapi
ERROR: 2024/11/10 23:41:20 main.go:77: failed to build documents tree, last error: request failed with status 410
```

## Steps To Reproduce

1. Install rmapi
2. run `rmapi` from the console

## Expected behavior

It should not give an error.

## Additional context

This error is known, see https://github.com/juruen/rmapi/issues/312 for instance. The version 0.0.27 in unstable works fine.

I think that https://github.com/NixOS/nixpkgs/pull/355090 should be back-ported to 24.11, since the package is otherwise unusable.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241116.057f63b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `""`
 - nixpkgs: `/nix/store/idq1bmwwy9rlkc21hccvx42wlwpxsx1f-source`

## Notify maintainers

@NickHu 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samueltardieu** [comment]
Backport is in #359148
