### ISSUE TITLE
wiki-js: ssl to database & dynamic user issue

### ISSUE THREAD

**Issue by ser** [NixOS/nixpkgs#359176]
## Describe the bug

There are two bugs I experience during my deployment:

1. There is no `ssl` option in settings.db which renders connection to a non-ssl postgresql server impossible.
2.  Dynamic user scenario for wiki-js makes providing `environmentFile` impossible in secure way using secrets, as it must be public for wiki-js to read the content.
 
## Notify maintainers

@ma27

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NyCodeGHG** [comment]
the `environmentFile` option is read by systemd, not wiki-js, so the file can (and should) only be readable by root

**Comment by Ma27** [comment]
> There is no ssl option in settings.db which renders connection to a non-ssl postgresql server impossible.

The settings attribute is freeform, so you should be able to just add the `ssl` setting.

So I don't see anything actionable here.

**Comment by ser** [comment]
OK, thanks, it was totally not clear from available documentation - I hope someone having similar questions will find this issue and your answers.
