### ISSUE TITLE
Build failure: PACKAGENAME

### ISSUE THREAD

**Issue by SullivanNagler** [NixOS/nixpkgs#359584]
## Steps To Reproduce

1. failed rebuild switch 

## Build log

<details>
<summary>Build Log</summary>
<pre>
sudo nixos-rebuild switch
this derivation will be built:
  /nix/store/3dswk0nq4qi89y24cqp3fm2ysw594kq7-nixos-rebuild.drv
these 2 paths will be fetched (0.02 MiB download, 0.07 MiB unpacked):
  /nix/store/x09cv5skyv8kcx8f0mjz429ap2k752nh-install-shell-files
  /nix/store/z50gnrdklgq4sfq59z2sw80mbnr9nrk3-stdenv-linux
copying path '/nix/store/x09cv5skyv8kcx8f0mjz429ap2k752nh-install-shell-files' from 'https://cache.nixos.org'...
copying path '/nix/store/z50gnrdklgq4sfq59z2sw80mbnr9nrk3-stdenv-linux' from 'https://cache.nixos.org'...
building '/nix/store/3dswk0nq4qi89y24cqp3fm2ysw594kq7-nixos-rebuild.drv'...
/nix/store/z50gnrdklgq4sfq59z2sw80mbnr9nrk3-stdenv-linux/setup: line 1072: /nix/store/andg6mzrnmz1nvfchgrzls6mw6xypl4j-nixos-rebuild/bin/nixos-rebuild: No such file or directory
error: builder for '/nix/store/3dswk0nq4qi89y24cqp3fm2ysw594kq7-nixos-rebuild.drv' failed with exit code 1
building Nix...
nix-instantiate: error while loading shared libraries: /nix/store/rlmyizjw96rfpi544511lqbsdqdjsrcb-keyutils-1.6.3-lib/lib/libkeyutils.so.1: file too short
building the system configuration...
nix-build: error while loading shared libraries: /nix/store/rlmyizjw96rfpi544511lqbsdqdjsrcb-keyutils-1.6.3-lib/lib/libkeyutils.so.1: file too short
</pre>

</details>

## Additional context
system.stateVersion = "24.11"; 

## Metadata

``` 
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.05 (Uakari), 24.05.6565.689fed12a013`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.11, nixos-save-24.05, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
Hello ! The gen 170 is okay not the next, i can not rebuild since :
![image](https://github.com/user-attachments/assets/43327f95-9df9-4c21-b6eb-85e56f4d49b5)

It’s been 3 month i’ve been using nixos, it’s possibly a skill issue.
Thx for the help,
Sullivan

**Comment by TomaSajt** [comment]
It would be helpful if you shared more information about your issue, like what do the logs show when failing and what's the trace?

If you look at the error logs shown by `sudo nixos-rebuild build --show-trace` you might get a better idea of what's causing the issue.
If you do not figure it out, please send the logs.

If you have your configs publicly available, it would also help if you shared a link to it.

**Comment by TomaSajt** [comment]
I'm not an expert on NixOS related failures, so I can't help a lot.

Is it on purpose that gen 171,172,173 has a lower linux kernel version?
Maybe you added something that overrides it (perhaps from nixos-hardware)?

Have you lost the working config?
If you have version control over your configs, you might be able to do some diff-ing.
