### ISSUE TITLE
"gnmic version" is incorrect

### ISSUE THREAD

**Issue by iwanb** [NixOS/nixpkgs#359543]
## Describe the bug

Running `gnmic version` does not return anything useful:
```
$ ./result/bin/gnmic version
version : dev
 commit : none
   date : unknown
 gitURL : 
   docs : https://gnmic.openconfig.net
```

## Steps To Reproduce

```
nix build github:NixOS/nixpkgs/nixos-unstable#gnmic
./result/bin/gnmic version
```

## Expected behavior

It should print the version of gnmic. Ideally the commit and date too, but that might be a bit more tricky.

It seems those flags should do that, but they apparently don't: https://github.com/NixOS/nixpkgs/blob/4633a7c72337ea8fd23a4f2ba3972865e3ec685d/pkgs/by-name/gn/gnmic/package.nix#L24

Upstream code: https://github.com/openconfig/gnmic/blob/main/pkg/app/version.go

## Notify maintainers

@vincentbernat 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vincentbernat** [comment]
The path to set version/commit/date has changed. I have made a PR to fix that.

**Comment by iwanb** [comment]
> The path to set version/commit/date has changed. I have made a PR to fix that.

Thank you!
