### ISSUE TITLE
Build failure: pixman (`armv7l` cross)

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#359616]
## Steps To Reproduce

`nix build nixpkgs#pkgsCross.armv7l-hf-multiplatform.pixman`

## Build log

[Build log](https://gist.github.com/Majiir/ff20b4e6a340e0e27f3be277282eb0cb)

## Additional context

- :red_circle: **Bisected the issue to https://github.com/NixOS/nixpkgs/pull/332582.**

- These builds succeed:
    
    `nix build nixpkgs#pixman`
    `nix build nixpkgs#pkgsCross.aarch64-multiplatform.pixman`

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.05 (Uakari), 24.05.20241104.d063c1d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
```

but tested with latest `master` at 6490fd94d60c5d666efb35bc1f022e7dfa379090.

## Notify maintainers

@trofi 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by trofi** [comment]
Before doing more digging do you have a chance to check if new `pixman` release just fixes it? https://github.com/NixOS/nixpkgs/pull/353959

**Comment by Majiir** [comment]
Ah, that does fix it, thanks!

**Comment by trofi** [comment]
Thank you for the test! My guess would be that one of these upstream commits fixed it:
- https://gitlab.freedesktop.org/pixman/pixman/-/commit/63ae6af9a6f1d4c62239b9883ada72f32e6b4fff
- https://gitlab.freedesktop.org/pixman/pixman/-/commit/add7c8db45f7a253a3a20b0be3a2bfb304fea894

**Comment by gcoremans** [comment]
Yes, that should fix it, the upstream issue is https://gitlab.freedesktop.org/pixman/pixman/-/issues/96 and the upstream fixing MR is https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/100 (I just ran into this myself)
