### ISSUE TITLE
Weird memory leak.

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#35963]
## Issue description
I'm not entirely sure what the issue is, I can't find anything in top that's showing this much memory usage, and all I have open is firefox, deluge, and a few other processes, which even if I close them the leak stays.
This only happens on NixOS, both stable and unstable, and I wish I could give more details but I'm unsure as what to give. I suspect it might have to do with the AMDGPU driver or X, but I'm probably wrong.

![screenshot_20180227_203341](https://user-images.githubusercontent.com/30435868/36766997-f118b240-1bfd-11e8-8de8-ba8456fc3171.png)

### Steps to reproduce
No idea.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.20, NixOS, 18.03pre129076.831ef4756e3 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3, nixpkgs-18.03pre129212.098c7f3d945"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Chiiruno** [comment]
Also, over time the display will freeze, thus why it may be related to the GPU (AMDGPU) driver, or X.
However, even after restarting X, the memory leak stays.

**Comment by rnhmjoj** [comment]
Try `ps aux --sort=-%mem | awk 'NR<=2{print $0}` to find which process is using the most memory.

**Comment by Chiiruno** [comment]
It still doesn't say, ran it with root and without the awk too to see if it was multiple processes. That's why I think the problem is in kernelspace and not userspace.

**Comment by rnhmjoj** [comment]
Maybe it's really amdgpu. See this: https://github.com/RadeonOpenCompute/ROCm/issues/176

**Comment by Chiiruno** [comment]
I'm on unstable, and currently whenever I log out the memory usage goes down when I log back in. (example: 12GiB RAM, 10GiB swap logout, still high, but around 6GiB RAM when log back in)

So, it appears to be a userspace issue for the most part now.

**Comment by Chiiruno** [comment]
I found the issue. For some reason my desktop slideshow on KDE was taking up ridiculous amounts of RAM without reporting it in the system monitor. I have a very large image folder that it pulls from.
This is an upstream KDE issue and as such I will close this issue.
