### ISSUE TITLE
Package request: tui-logger

### ISSUE THREAD

**Issue by i-am-logger** [NixOS/nixpkgs#359665]
## Project description
Logger with smart widget for the tui and ratatui crate
![image](https://github.com/gin66/tui-logger/raw/master/doc/demo_v0.6.6.gif?raw=true)

## Metadata

* homepage URL: https://github.com/gin66/tui-logger
* source URL: https://github.com/gin66/tui-logger
* license: mit, 
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thtrf** [comment]
Isn't this a Rust library?

**Comment by i-am-logger** [comment]
yes, built with rust, though an executable, not a lib

**Comment by thtrf** [comment]
No, it is a lib. There are no binaries available; you cannot install it with `cargo install`.

**Comment by pluiedev** [comment]
To add on top of that, there is no `src/main.rs` nor any `[[bin]]` entries in the Cargo.toml. There are example executables, but this is fundamentally just a library and you can use those just fine with Cargo natively without Nix.
