### ISSUE TITLE
Update request: PipeWire 1.2.6 → 1.2.7

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#359713]
## Package Information

- Package name: `pipewire`
- Latest released version: 1.2.7
- Current version on the unstable channel: 1.2.6
- Current version on the stable/release channel: 1.2.6

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@K900 @Kranzes

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
Currently on staging:

* #359284 (staging) ([PR tracker](https://nixpk.gs/pr-tracker.html?pr=359284))
* #359287 (staging-24.11) ([PR tracker](https://nixpk.gs/pr-tracker.html?pr=359287))

**Comment by hacker1024** [comment]
My bad, I couldn't find it in the PR list for some reason.
