### ISSUE TITLE
Migration to nerd-fonts fail 

### ISSUE THREAD

**Issue by khsoh** [NixOS/nixpkgs#359731]
## Describe the bug

The new commit: https://github.com/NixOS/nixpkgs/commit/de4dbc58fdeb84694d47d6c3f7b9f04a57cc4231
caused a problem with my nix-darwin configuration.nix file that had the following code:

```
  fonts.packages = with pkgs;
  [
    (nerdfonts.override { fonts = [ "FiraMono" ]; })
  ];
```

Building with `darwin-rebuild switch` reports the following error:

`error: nerdfonts has been separated into individual font packages under the namespace nerd-fonts`

I tried replacing `nerdfonts` with `nerd-fonts`.  That did not work - the error was:

`error: function 'anonymous lambda' called with unexpected argument 'fonts'`

## Steps To Reproduce

See description

## Expected behavior

`darwin-rebuild switch` should work.

## Screenshots

none
## Additional context

Running on macOS 15.1.1 (24B91)

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khsoh** [comment]
Found the fix:

```
fonts.packages = with pkgs;
  [
    nerd-fonts.fira-mono
  ];
```

I think this change in specification should be mentioned in the release notes.

**Comment by StanislausA** [comment]
> Found the fix:
> 
> ```
> fonts.packages = with pkgs;
>   [
>     nerd-fonts.fira-mono
>   ];
> ```
> 
> I think this change in specification should be mentioned in the release notes.

some direction fer da dawgs dem:
font name changes --> [pkgs/data/fonts/nerd-fonts/manifests/fonts.json](https://github.com/NixOS/nixpkgs/commit/de4dbc58fdeb84694d47d6c3f7b9f04a57cc4231#diff-5c995ea544bf5e1be34a7f2f973c7c48ee9ab73f3822dc20bebb30cde94f124e)

ie.
```
fonts.packages = [
    # from: (pkgs.nerd-fonts.override { fonts = [ "JetBrainsMono" ]; })
    # to: nerd-fonts.jetbrains-mono
  ];
```
