### ISSUE TITLE
Nexusmods-app doesn't create .desktop file

### ISSUE THREAD

**Issue by ShadowReaper420** [NixOS/nixpkgs#359833]
## Describe the bug

Hi, After installing Nexusmods-app from nixpkgs I am unable to run it from my app launcher or terminal.

## Steps To Reproduce

1. Install the package
2. Check your app launcher
3. It's not there....

## Expected behavior

For there to be a .desktop file and to able to launch the app

## Metadata

```

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240926.1925c60`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.7`
 - nixpkgs: `/nix/store/fpivx4sjcp2vk4rp9nhliln5cwcp3kc6-source`
```

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ShadowReaper420** [comment]
Okay idk why the maintainer ping got deleted but whatever @MattSturgeon

**Comment by MattSturgeon** [comment]
Have you ever had the nexusmods app installed before? Or has it been updated recently?

Currently they make breaking changes every update, so if there is any existing config left over from running the app in the past it will cause it to crash with no user-facing error message.

See [Why do I have to uninstall everything to update the app?](https://nexus-mods.github.io/NexusMods.App/users/faq/#why-do-i-have-to-uninstall-everything-to-update-the-app).

This shouldn't affect whether it has a desktop entry though.

---

For the desktop entry, have you tried refreshing the desktop entry database? This is done using `update-desktop-database` which is in the `desktop-file-utils` package. Alternatively, restarting or re-logging in should also work.

- Are you installing with nixos, home-manager, `nix profile`, etc?
- If using a configuration, are you activating it (e.g. `nixos-rebuild switch`)
- Does the desktop file show up in `/var/run/current-system/sw/share/applications/`? (for nixos)

**Comment by ShadowReaper420** [comment]
This is my first time installing nexusmods app, yes I rebuilt after adding it to my config, yes i rebooted after rebuild, no I am not installing it with home-manager, no there is no symlink in "/var/run/current-system/sw/share/applications/" also sorry for the late replay I was at dinner for the day.

**Comment by MattSturgeon** [comment]
I just double checked by installing into my nixos config and I'm unable to reproduce the issue on my end.

<details><summary>Details</summary>
<p>


If I add `environment.systemPackages = [ pkgs.nexusmods-app ]` to my nixos config and run `nixos-rebuild switch`, the desktop entry shows up and correctly launches the program.

It can be found in current-system:

```sh
$ realpath /var/run/current-system/sw/share/applications/com.nexusmods.app.desktop
/nix/store/7ccpwslwpnig1gfz99mbsq946bzb9vi9-nexusmods-app-0.6.3/share/applications/com.nexusmods.app.desktop
```

</p>
</details> 

> host os: `Linux 6.6.52, NixOS, 24.11 (Vicuna), 24.11.20240926.1925c60`

Your nixos version seems a little old (`20240926`, so 26th of September), for reference mine is `25.05.20241119.23e89b7` (19th of November).

Does updating your flake lock and/or channels resolve the issue?

**Comment by Henry-Hiles** [comment]
I have this issue on latest unstable. Reboot doesn't resolve.
