### ISSUE TITLE
Bibata-modern-classic main curser isbroken now

### ISSUE THREAD

**Issue by ArtemChandragupta** [NixOS/nixpkgs#359821]
## Describe the bug

After bibata cursors update, the pointing point of a main cursor in bibata-modern-classic moved to the right edge. Other cursor in this set are unaffected.

## Steps To Reproduce

1. Have bibata-modern-classic

## Expected behavior

I should be able to point with left-upper angle of the triangle

## Screenshots

The expected pointer is on the button - it should be changed to "arm".
![image](https://github.com/user-attachments/assets/109b963c-9548-46a2-add0-96a6d936c13a)

But it activates only when the right side of the cursor is on the button.
![image](https://github.com/user-attachments/assets/fa4daca3-2f6a-4fdc-9f84-34bf7c0d089f)

## Additional context

![image](https://github.com/user-attachments/assets/9c7f4d0e-8f00-41f6-9b2e-f29aa2cbf9f0)
Screenshot that shows the update. Before it was right.

## Notify maintainers

@rawkode 
@AdsonCicilioti

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
There is a PR opened with a fix https://github.com/NixOS/nixpkgs/pull/359604.

**Comment by RicArch97** [comment]
My goodness, i thought i was going crazy when i noticed the cursor having an offset haha. Glad there is a proposed fix!

**Comment by istudyatuni** [comment]
Off topic, but what's the app on the screenshot?

**Comment by istudyatuni** [comment]
And I guess this issue could be closed since linked PR is merged

**Comment by Gliczy** [comment]
Closing as the PR linked above has been merged.

@istudyatuni the program in the screenshot is `nvd`.

**Comment by ArtemChandragupta** [comment]
@istudyatuni i use [nh](https://github.com/viperML/nh).
