### ISSUE TITLE
Package request: vogl

### ISSUE THREAD

**Issue by hukasu** [NixOS/nixpkgs#359907]
## Project description
Valve's graphics profiler

## Metadata

* homepage URL: https://github.com/ValveSoftware/vogl
* source URL: https://github.com/ValveSoftware/vogl
* license: mit
* platforms: unix, linux, darwin, windows

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Hasn't been updated in literally 8 years and made obsolete by RenderDoc. Why not use that instead?
