### ISSUE TITLE
nixpkgs-24.05-darwin blocked due to capacity issues in previous staging cycle

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#360028]
The `nixpkgs-24.05-darwin` channel is 3 weeks behind today because it was excluded from the last staging-next-24.05 cycle due to capacity issues around the darwin infrastructure.

It is planned to catch up with the next staging-next-24.05 cycle, which should start sometime this weekend.

The communication around this was bad, and we need to do better in the future. I'm sorry.

**Comment by vcunat** [comment]
If I look right, the oldest missing changes were staged on November 7, so that's still not too bad IMHO at this point.

**Comment by vcunat** [comment]
Oh, I was looking wrong somehow.  c23b03c781d65 staged on September 14.  😱

**Comment by vcunat** [comment]
The stuff is being built now, but [thousands of builds fail newly](https://hydra.nixos.org/eval/1810272?compare=1809820#tabs-now-fail) (transitively) and even the channel [gets blocked](https://hydra.nixos.org/build/281091274) by a failure.

**Comment by vcunat** [comment]
It's not perfect, but I'd call it solved.  People are welcome to fix builds...
