### ISSUE TITLE
Build failure: atop (cross)

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#360024]
## Steps To Reproduce

`nix build nixpkgs#pkgsCross.aarch64-multiplatform.atop` or `nix build nixpkgs#pkgsCross.armv7l-hf-multiplatform.atop`

## Build log

[Build log](https://gist.github.com/Majiir/2557ca750adc7131be0df255de5c3cb0)

## Additional context

Bisected the breakage to https://github.com/NixOS/nixpkgs/pull/325704. I haven't bisected upstream yet.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.05 (Uakari), 24.05.20241104.d063c1d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`

## Notify maintainers

@7c6f434c @therishidesai 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Majiir** [comment]
I think the `atop` problem began in Atoptool/atop@8f79c7f8f065cd99e828d66e00ba3210d419ba8e. From the nix build log:

```
/run/current-system/sw/bin/bash: line 1: pkg-config: command not found
```

It turns out the binary is prefixed (e.g. `aarch64-unknown-linux-gnu-pkg-config`) when cross-compiling, so `pkg-config` can't be found.

But it looks like the prefixing was deliberately done in https://github.com/NixOS/nixpkgs/pull/292388. @NickCao Can you advise on the right approach here?

**Comment by NickCao** [comment]
Upstream should use the pkg-config binary specified in the `PKG_CONFIG` environment variable, and fallback to `pkg-config` by default.

**Comment by Majiir** [comment]
Thanks! It looks like that was already done in Atoptool/atop@eec97d53d3ed1c2cba036b90e4c7bd2409658080, but that alone didn't fix it, which confused my bisect. It looks like `pkg-config` has to be moved to `nativeBuildInputs`. https://github.com/NixOS/nixpkgs/pull/360488 fixes it.
