### ISSUE TITLE
pkgs.prometheus-unifi-exporter no longer exists

### ISSUE THREAD

**Issue by dev-null-undefined** [NixOS/nixpkgs#360179]
https://github.com/NixOS/nixpkgs/blob/4633a7c72337ea8fd23a4f2ba3972865e3ec685d/nixos/modules/services/monitoring/prometheus/exporters/unifi.nix#L60

**Comment by dotlambda** [comment]
It was removed in https://github.com/NixOS/nixpkgs/commit/826bef9b514bd5ceb5af55ccd79592778de03277. Let's remove the module as well: https://github.com/NixOS/nixpkgs/pull/360193
