### ISSUE TITLE
OpenTabletDriver-0.6.4.0 - Dotnet SDK 6.0.36 is EOL, please use 8.0 (LTS) or 9.0 (Current)

### ISSUE THREAD

**Issue by Hannes1909** [NixOS/nixpkgs#360369]
## Describe the bug

home manager switch refuses to evaluate, since dotnet-runtime-6.0.36 is marked as insecure

## Steps To Reproduce

HomeManager Config:
```
{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.opentabletdriver
  ];
}
```
1. home-manager switch
2. error: Package ‘dotnet-runtime-6.0.36’ in /nix/store/cv1ra2falylwgap7q9p501mn8shyg1b1-nixos/nixos/pkgs/development/compilers/dotnet/build-dotnet.nix:212 is marked as insecure, refusing to evaluate.

## Expected behavior

OpenTabletDriver should use 8.0 (LTS) or 9.0 (Current) version of dotnet-runtime instead of permitting old versions as an exception if possible

## Screenshots

No screenshots, just terminal output :)

## Additional context

The source file in question should be 

Lines 35, 37:
```
  dotnetInstallFlags = [ "--framework=net6.0" ];
  dotnet-sdk = dotnetCorePackages.sdk_6_0;
```

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05beta712559.4633a7c72337`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Notify maintainers

@gepbird
@thiagokokada
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by thiagokokada** [comment]
Fixed by: https://github.com/NixOS/nixpkgs/pull/360389.
