### ISSUE TITLE
Emacs fails with libgccjit.so: error invoking gcc driver

### ISSUE THREAD

**Issue by jcowgar** [NixOS/nixpkgs#360412]
## Describe the bug

When installing and then running Emacs, Warnings are emitted in Emacs:

```
⛔ Warning (native-compiler): libgccjit.so: error: error invoking gcc driver
⛔ Warning (native-compiler): /nix/store/ny5j2ay81dzl931yzfk2wds3k83ygxn0-emacs-30.0.92/share/emacs/site-lisp/site-start.el: Error Internal native compiler error: "failed to compile", "/Users/jeremy/.emacs.d/eln-cache/30.0.92-802b27dc/site-start-f0b9874f-8f4312e0.eln", "error invoking gcc driver"
```

Prior to execution, there is no `~/.emacs.d`, it is created on initial start. I ensured there was no `~/.config/emacs` as well. Fresh install, simply emacs.

This report includes screen shots of the emacs30 package, but I have tried straight emacs and emacs29 packages with the exact same result.

This is a warning here and emacs will continue to function however as you begin to add packages or attempt to install tree sitter grammar files, the same error occurs and thus emacs is unusable the moment you need a tree sitter grammar file to provide editing capability for a particular language.

## Steps To Reproduce

1. Add pkgs.emacs to configuration.nix

## Expected behavior

I expect Emacs to start with no warnings

## Screenshots

<img width="868" alt="Screenshot 2024-11-30 at 7 46 47 AM" src="https://github.com/user-attachments/assets/dc7528c9-2406-4c24-ad88-a4f7c5e665d8">

## Additional context

This is on a macOS system using nix-darwin and an aarch64 (M3).

## Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/7c2g8d7nzs52snmcf5fk5m4nwvnbkqqm-source`

## Notify maintainers

libgccjit maintainers: @Synthetica9, @vcunat, @Ericson2314 
emacs maintainers: @AndersonTorres, @adisbladis, @jwiegley, @lovek323, @matthewbauer
 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samueltardieu** [comment]
I can't reproduce it on Linux, I've tagged it as a Darwin specific issue.

**Comment by jcowgar** [comment]
> I can't reproduce it on Linux, I've tagged it as a Darwin specific issue.

Just as a note, when discussing the issue on discord, another on macOS user added emacs as a system package and received the same problem. So, very possible it is Darwin.

**Comment by bestlem** [comment]
In my emacs 29 in my setup code so not a simple case.
the error is slightly clearer that it is a Darwin issue. with the -lSystem error.

From *Async)native-compile-log*
```
Compiling /Users/mark/.emacs.d/site-lisp/Third-party-modified/lispy-mnemonic.el...
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/mark/.emacs.d/site-lisp/Third-party-modified/lispy-mnemonic.el: Error: Internal native compiler error failed to compile
Compilation finished.
```

**Comment by jasonjckn** [comment]
I too am able to reproduce this on Darwin with Nix release 24.11, using emacs-overlay and an M4
```
Compiling /Users/j/.emacs/fm30/.local/straight/build-30.0.92/inheritenv/inheritenv.el...
Warning (evil-collection): Make sure to set `evil-want-keybinding' to nil before loading evil or evil-collection.

See https://github.com/emacs-evil/evil-collection/issues/60 for more details.
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/inheritenv/inheritenv.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/inheritenv-4086f0b4-cde89279.eln", "error invoking gcc driver"
ld: library not found for -lSystem
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/evil-collection/modes/so-long/evil-collection-so-long.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/evil-collection-so-long-e0dc7c2b-74f4ddb9.eln", "error invoking gcc driver"
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/nix-mode/nix.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/nix-0f61d268-a1f916d0.eln", "error invoking gcc driver"
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/envrc/envrc.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/envrc-aa67a1ba-32efa594.eln", "error invoking gcc driver"
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/magit-section/magit-section.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/magit-section-cbff8b04-b828c58a.eln", "error invoking gcc driver"
Compilation finished.
Compiling /Users/j/.emacs/fm30/.local/straight/build-30.0.92/evil-nerd-commenter/evil-nerd-commenter.el...
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/evil-nerd-commenter/evil-nerd-commenter.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/evil-nerd-commenter-378efc80-57d2759d.eln", "error invoking gcc driver"
Compiling /Users/j/.emacs/fm30/.local/straight/build-30.0.92/smartparens/smartparens-html.el...
Compiling /Users/j/.emacs/fm30/.local/straight/build-30.0.92/evil-nerd-commenter/evil-nerd-commenter-sdk.el...
ld: library not found for -lSystem
ld: library not found for -lSystem
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/smartparens/smartparens-html.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/smartparens-html-1b1cbca5-f96d7805.eln", "error invoking gcc driver"
libgccjit.so: error: error invoking gcc driver
/Users/j/.emacs/fm30/.local/straight/build-30.0.92/evil-nerd-commenter/evil-nerd-commenter-sdk.el: Error Internal native compiler error: "failed to compile", "/Users/j/.emacs/fm30/.local/cache/eln/30.0.92-a3adebf0/evil-nerd-commenter-sdk-529dbf54-2e6052f7.eln", "error invoking gcc driver"
```

**Comment by jian-lin** [comment]
This issue is introduced in this staging cycle: https://github.com/NixOS/nixpkgs/pull/354201.

The [commit](7f2d3d2febedabd8f5c9761373c99b9dcfa917e1) before the merge of that PR does not have this issue while the merge [commit](7f2d3d2febedabd8f5c9761373c99b9dcfa917e1) of that PR does have this issue.

CC darwin experts @reckenrode @emilazy

**Comment by reckenrode** [comment]
Does it work if `SDKROOT` is exported from the Emacs wrapper ln Darwin?

**Comment by Godalin** [comment]
Same problem on MacOS:

- MacOS Version 14.6.1
- M3 processer
- Nix release 24.11
- nix-darwin 24.11
- just added the `emacs` package to home-manager

**Comment by reckenrode** [comment]
https://github.com/NixOS/nixpkgs/pull/361752 should fix the issue. Please test and let me know if it does not.
