### ISSUE TITLE
NixOS installer (still) cannot detect connection to internet

### ISSUE THREAD

**Issue by enoren5** [NixOS/nixpkgs#360593]
## Steps To Reproduce

1. Write latest 24.11 install media to USB (Gnome or Plasma)
2. Boot to live desktop environment. Auto installer appears showing error: 
> "This computer does not satisfy the minimum requirements for installing NixOS. Installation cannot continue. 

> The system is not connected to the Internet."

## Expected behavior

I'd expect to configure my internet connection. That should allow me to proceed with the "Location"/"Keyboard"/"Users" steps.  have the wireless network SSID and password. But it never reaches the network option select screen. 

## Screenshots

![PXL_20241130_224118813](https://github.com/user-attachments/assets/b1f2dcc3-67c9-4a83-ad08-52beff22323e)

## Additional context

My first stop would have been to ask on the forums first but when I searched Google for `nixos installer could not connect to the internet` I encountered someone with a similar issue from April 2024: https://github.com/NixOS/nixpkgs/issues/307036
At the time it seemed to be just a weird quirk with an easy fix/workaround. All the user had to do was close the installer and re-open it. That didn't work for me.

Also worth mentioning: When I try running `sudo systemctl start wpa_supplicant` and then `wpa_cli`, I get this error:

> could not connect to wpa_supplicant (nil) - re-trying nixos

It just gets stuck in a perpetual loop.

## Metadata

I ran `$ nix-shell -p nix-info --run "nix-info -m"` but I can't copy it over from my terminal in text form because I don't have a network connection yet so here is a photo of the output of that shell command I took with my cell phone:

![PXL_20241130_225722958](https://github.com/user-attachments/assets/53d1b996-4fbc-4aba-a995-2e96a6374543)

## Notify maintainers

Now the boilerplate suggests tagging the maintainers responsible by using the git blame feature. I am not sure how to do that.

---
Note for maintainers: Please tag this issue in your PR.
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by shelvacu** [comment]
Please correct me if I'm wrong, but it seems the installer *correctly* detected that you were not connected to the internet (you had not selected an SSID or anything). The issue here is that it was unclear how to proceed. Perhaps the title should be "NixOS GUI installer has no instructions on how to connect to wifi"

What you needed to do is click the wifi icon in the bottom right. The `wpa_supplicant` instructions only apply to the CLI install process, the GUI installer uses networkmanager and expects you to configure through the desktop interface.

**Comment by enoren5** [comment]
:facepalm: Hi. That clarifies. It's not a bug. This was my first time running Linux on WiFi. All these years I have had my Linux towers plugged into ethernet cabels.  As you suggested, I opened network manager in the bottom right task bar, connected to my network  with the correct password, and the issue went away. I have successfully installed NixOS.
