### ISSUE TITLE
Update request: protonmail-desktop 1.0.6 → 1.5.1

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#360886]
## Package Information

- Package name: protonmail-desktop
- Latest released version: 1.5.1
- Current version on the unstable channel: 1.0.6
- Current version on the stable/release channel: 1.0.4

## Notify maintainers

@rsniezek 
@SebTM 
@matteo-pacini

**Comment by chewblacka** [comment]
The build requirements for protonmail-desktop have changed. See this PR (approved and pending merger) which updates from 1.0.6 to 1.3.2:

https://github.com/NixOS/nixpkgs/pull/356737

**Comment by rsniezek** [comment]
> The build requirements for protonmail-desktop have changed. See this PR (approved and pending merger) which updates from 1.0.6 to 1.3.2:
> 
> #356737

Mentioned PR got udpated to  1.5.1 as well, works on linux.

**Comment by rsniezek** [comment]
done in #356737
