### ISSUE TITLE
GNOME does not support automatic brightness

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#360953]
## Describe the bug

I am using NixOS 25.05 on an older Retina MacBook Pro (MacBookPro11,1). Under my previous installation of Fedora Silverblue, I was able to toggle an automatic screen brightness feature out of the box under *Settings* > *Power* > *Power Saving.* This appears to be missing in NixOS.

## Steps To Reproduce

1. Install NixOS, GDM and GNOME
2. Attempt to use automatic brightness

## Expected behavior

Automatic brightness is available under the GNOME Desktop Environment.

## Additional context

On my MacBook, the contents of 

- `/sys/class/hwmon/hwmon2/device/light`
- `/sys/bus/iio/devices/iio:device0/in_illuminance_raw`

correlate with brightness when I put a flashlight near the ambient light sensor, so I think the kernel is already configured correctly. Maybe we just need a small tweak in Systemd/DBus/GNOME?

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 25.05 (Warbler), 25.05.20241130.4703b8d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/ghh70y72vgas7f7pb7fasvksa2h9yxxr-source`
```

## Notify maintainers

@NixOS/gnome 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by j0hax** [comment]
Works perfectly, thanks!

**Comment by jtojnar** [comment]
We should probably add it to `gnome.nix` like Plasma does.

**Comment by j0hax** [comment]
I was also considering adding it to my Laptop's module in nixos-hardware. `gnome.nix` directly works for me too, but not every platform has brightness sensors I reckon.
