### ISSUE TITLE
Tracking version on the channel

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#3609]
I remember there was a discussion on IRC about finding out the commit available on the unstable channel. Would it be possible to make things a little easier by setting up a branch (or maybe a tag?) for this commit and make the script that updates channels also update this branch (tag)?

**Comment by benley** [comment]
I would find this pretty useful too, as it would provide a good method for using nixpkgs unstable as an input to builds on private hydra instances.

**Comment by vcunat** [comment]
Yes, one such branch per channel might be useful to develop new things against (tags are supposed not to change location, but branch doesn't exactly capture what we need either). IIRC there were some discussions already about the branch solution, but I didn't follow it much.

I personally just go to http://nixos.org/channels/, choose a channel I like (perhaps inspecting the update dates), and then copy the hash from URL or h1.

**Comment by cstrahan** [comment]
While not it's not ideal, this is how I find the commit:

* `curl -L https://nixos.org/channels/nixos-unstable/src-url`
* In a browser, go to the url
* Click the "Inputs" tab
* See the "Revision" column

**Comment by spwhitt** [comment]
I've been maintaining a some channel tracking branches in my nixpkgs for a while now. The script which does it is located here: https://github.com/spwhitt/nix-channel-branches . If someone with push access wants to set this up that would be great. Otherwise everyone is welcome to use my branches or setup my script on your own repo.

**Comment by copumpkin** [comment]
:+1:

**Comment by peti** [comment]
Wouldn't tags be preferable over branches?

**Comment by vcunat** [comment]
@peti: tags are usually assumed not to move. Branches are assumed to move in a fast-forward manner, which is this use case. (Of course, you can force breaking both assumptions, but it won't behave nicely when pushing/pulling to other repos.)

**Comment by peti** [comment]
@vcunat, where does the assumption that tags don't move come from? IMHO, in a version control system like `git` that supports operations like `git rebase -i` and `git filter-branch` it's quite natural to assume that tags *can* move.

I've force-pushed tags to designate a certain (transient) state of a repository before, and I am not aware of any trouble this might cause. Why would other repositories care about that?

**Comment by vcunat** [comment]
@peti, my view: other than those differing assumptions (and resulting UI differences), I see no difference between tags and branches. Git docs claim that git pull won't update existing tags unless forced (man git-tag, section on re-tagging):

> However, Git does not (and it should not) change tags behind users back. So if somebody already got the old tag, doing a git pull on your tree shouldn’t just make them overwrite the old one.

**Comment by peti** [comment]
@vcunat, okay, good point. Thanks!

**Comment by peti** [comment]
Everyone, say hello to ...

- [channel/unstable](https://github.com/NixOS/nixpkgs/tree/channel/unstable)
- [channel/14.04](https://github.com/NixOS/nixpkgs/tree/channel/14.04)
- [channel/14.12](https://github.com/NixOS/nixpkgs/tree/channel/14.12)

Updated once per hour.

**Comment by copumpkin** [comment]
Beautiful, thanks! I also noticed https://github.com/NixOS/nixpkgs-channels appear recently, but github won't show me who did it. The only advantage I can think of to having a separate repository is that it gives us independent permissions (and conceivably only hydra needs to be able to push there)

**Comment by edolstra** [comment]
I just created it (because I don't want channel branches in the main repo).

**Comment by edolstra** [comment]
The nixpkgs-channels repo will be updated from the channel mirror script, so it wil be updated in sync with the channels themselves.

**Comment by vcunat** [comment]
Is it separate just to avoid people pushing into the branches (accidentally)?

**Comment by edolstra** [comment]
Yes, and to avoid duplicate commit notifications.

**Comment by edolstra** [comment]
To make this easier for users, we can add
```
git remote add channels git://github.com/NixOS/nixpkgs-channels.git
```
to `nixos-checkout`.

**Comment by domenkozar** [comment]
cool, we have separate git repos for this now
