### ISSUE TITLE
XMonad failed to start with sddm

### ISSUE THREAD

**Issue by 2403772980ygy** [NixOS/nixpkgs#360936]
## Describe the bug

After a recent update, xmonad failed to start with sddm.

## Steps To Reproduce

Actually I don't know if using startx normally works with NixOS......

Path 1:
1. Try to start xmonad with sddm

Path 2:
1. run `xmonad --recompile`
2. Try to start xmonad with xinit (I haven't tried this approach ever before, so I have no idea if this works. I'm executing this mainly to get logs.)

## Expected behavior

Xmonad starts like before.

## Screenshots

Sorry I can't take photos with my setup, I'll try my best to explain the things happened with the two approaches.

With Path 1, When it starts, the xmobar loads up with squares instead of normal font. After 1 second, the WM exits.

**I highly suspect the square thing is a direct result of the nerd-font upgrade, however, fc-match still matches the config in my .xmobarrc**

However, despite I don't think this is the major driving cause of the break, these coincided so well......

With Path 2, it gives me a black screen, with no xmobar entries. The last line log shows:

```
  61   │ [  1209.658] (II) LoadModule: "nv"
  62   │ [  1209.658] (WW) Warning, couldn't open module nv
  63   │ [  1209.658] (EE) Failed to load module "nv" (module does not exist, 0)
  64   │ [  1209.658] (II) LoadModule: "modesetting"
  65   │ [  1209.658] (II) Loading /nix/store/cwa9ihrzv9zcg6rci26g5kxj7lgm3110-xorg-server-21.1.14/lib/xorg/modu
       │ les/drivers/modesetting_drv.so
  66   │ [  1209.658] (II) Module modesetting: vendor="X.Org Foundation"
  67   │ [  1209.658]    compiled for 1.21.1.14, module version = 1.21.1
  68   │ [  1209.658]    Module class: X.Org Video Driver
  69   │ [  1209.658]    ABI class: X.Org Video Driver, version 25.2
  70   │ [  1209.658] (II) LoadModule: "fbdev"
  71   │ [  1209.658] (WW) Warning, couldn't open module fbdev
  72   │ [  1209.658] (EE) Failed to load module "fbdev" (module does not exist, 0)
  73   │ [  1209.658] (II) LoadModule: "vesa"
  74   │ [  1209.658] (WW) Warning, couldn't open module vesa
  75   │ [  1209.658] (EE) Failed to load module "vesa" (module does not exist, 0)


 183   │ [  1209.733] (EE) modeset(0): Failed to create pixmap
 184   │ [  1209.733] (EE) 
 185   │ Fatal server error:
 186   │ [  1209.733] (EE) failed to create screen resources(EE) 
 187   │ [  1209.733] (EE) 

```

I don't think the log above represent what is happening with Path 1, since Path 1 is started but crashed instantly after.

## Additional context

Nvidia drivers is fine, from outputs from lsmod and glxinfo when I'm running a Plasma DE.

I'm finding if there is a way to get the logs from the Path 1 exit. I may need to do some restarts so this may be in an comment.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241201.2c27ab2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/sgbj0n22b3p8rfvmp46c6qha0qax4wyd-source`

---

Note for maintainers: Please tag this issue in your PR.

---

**Comment by 2403772980ygy** [comment]
I do need help on how to get the xorg log with Path 1.

**Comment by Zer0-** [comment]
I was using lightdm (the default) and I cannot get X11 to start. I'm also using nouveau. Mine might be an unrelated issue, but I went to the xorg irc to get help and they told me to file a bug report for this. Attached is my X11 log, I will be filing a separate issue.
[x11.txt](https://github.com/user-attachments/files/17978769/x11.txt)

**Comment by 2403772980ygy** [comment]
I found out that using the default config can start, I'm adding xmobar to it and try again

**Comment by Titaniumtown** [comment]
@2403772980ygy I don't use xmonad, but your tip about `fc-cache -r` was invaluable for me. I couldn't get the fonts to properly display. Cheers!

**Comment by 2403772980ygy** [comment]
The `fc-cache -r` solved most of the problem for me. Closing.
