### ISSUE TITLE
Jellyfin IPv6 Incompatibility

### ISSUE THREAD

**Issue by Titaniumtown** [NixOS/nixpkgs#361204]
## Describe the bug

When IPv6 is enabled system-wide, Jellyfin fails to make http requests for metadata, and in-turn, populating any media.

## Steps To Reproduce

1. set `networking.enableIPv6` to true
2. Enable the Jellyfin module
3. Add media to Jellyfin
4. Observe the lack of the population of content in Jellyfin

## Expected behavior

From a nixpkgs perspective, a `throw` or warning should be thrown to alert the user of this issue. Took me a very long while to figure out the root cause.

## Additional context

https://github.com/jellyfin/jellyfin/issues/12255
https://github.com/lyarenei/jellyfin-plugin-listenbrainz/issues/107

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241201.ac35b10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/store/ab78nf3ad8ly49zfyd3igw3f2n5q7fz4-source`
 ```

## Notify maintainers

@nyanloutre @minijackson @purcell @jojosch

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mic92** [comment]
I don't understand: `networking.enableIPv6` is enabled by default and I don't have any issues in my jellyfin regarding this. I fee like your problem is not that NixOS option but something else.

**Comment by Titaniumtown** [comment]
Really? No http requests succeed for me and multiple errors are shown in the jellyfin logs (see the linked jellyfin issue). I'm very confused now.

**Comment by Mic92** [comment]
Maybe your ipv6 setup is broken and `networking.enableIPv6` just works around it. However this is not a proper fix because people with working ipv6 won't have this issue.

**Comment by Titaniumtown** [comment]
Yes, you were correct, it was a broken ipv6 config: https://git.gardling.com/titaniumtown/server-config/commit/71d2bb0cb334023ccf2a531b9e7b2ed0652a07fa

Thanks for the tip. I was so confused haha. I don't know much about ipv6 lol
