### ISSUE TITLE
nixos/gitlab: Reply by email

### ISSUE THREAD

**Issue by bengcooper** [NixOS/nixpkgs#36125]
## Issue description

In order to enable [Reply by email](https://docs.gitlab.com/ce/administration/reply_by_email.html) in GitLab you need to edit the Procfile or the systemd service, which I don't think is currently possible.

The output of `gitlab-rake gitlab:incoming_email:check` is:

```
Checking Reply by email ...

IMAP server credentials are correct? ... yes
Init.d configured correctly? ... no
  Try fixing it:
  Enable mail_room in the init.d configuration.
  For more information see:
  doc/administration/reply_by_email.md
  Please fix the error above and rerun the checks.
```

### Steps to reproduce

- Install GitLab service
- Run `gitlab-rake gitlab:incoming_email:check` as root

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.60, NixOS, 18.03pre124926.e5d9d61d652 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124926.e5d9d61d652"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by flokli** [comment]
@bengcooper reading up on [GitLab's documentation](https://docs.gitlab.com/ee/administration/incoming_email.html#installations-from-source), it seems this is configuration nowadays.

Can you get it working by adding the options mentioned in the docs to `services.gitlab.extraConfig`?

If so, we probably should add that as regular options into the gitlab module.

**Comment by flokli** [comment]
cc @globin @fpletz

**Comment by flokli** [comment]
I still think this is desirable. @petabyteboy, @talyz, can you take a look?
