### ISSUE TITLE
wpa_supplicant: can't get wifi up and running on RPI4

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#361239]
## Describe the bug

Immediately after upgrading from nixos24.05 to nixos24.11, wifi networking stopped. Before rebooting in fact. Rebooting to new kernel doesn't help.

Logs give a lot of message along the lines of "brcmfmac: brcmf_set_channel: set chanspec: 0xXXXX fail, reason -52"

This leads me to google search results like https://github.com/raspberrypi/linux/issues/6049 which blame wpa_supplicant 2.11 and say I should downgrade to wpa_supplicant 2.10.

Unfortunately I can't see any easy way of overriding the wpa_supplicant to 2.10 without downgrading back to nixos-24.05.

## Steps To Reproduce

1. Have working wifi on nixos 24.05
2. Upgrade to nixos 24.11

## Expected behavior

Networking should continue to work

## Metadata

 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.31, NixOS, 24.11 (Vicuna), 24.11.20241128.c71ad5c`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `not found`

(nixpkgs not found because there was no networking)

## Notify maintainers

@marcweber @ma27

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by brianmay** [comment]
Never mind, I was on completely the wrong track entirely.

This changed fixed it. 

```
-    networks = { PENGUINS.psk = "ext:PSK_PENGUINS"; };
+    networks = {PENGUINS.pskRaw = "ext:PSK_PENGUINS";};
```

The docs led me to believe that `pskRaw` is for hex format passwords only. But plan-text passwords also work fine.

**Comment by tennox** [comment]
@brianmay thanks for this tip! has resolved a driver crash for me at least - though I don't know why.
The `psk = ` format is suggested in the manual:
https://nixos.org/manual/nixos/stable/#sec-wireless

**Comment by brianmay** [comment]
The big problem with the examples from the manual is it involves putting the password in clear in the nix store.

Which maybe not always a big problem depending on how secret you want your wifi password to be, but I don't like it.

I do have a working config now, but joining all the pieces required is a bit of a pain. Particularly if you are new to nixos. And even now I can stuff up the secret key management, particularly when deploying new machines.

I use age in my flakes. My network config uses the following module:

```nix
{
  config,
  ...
}: {
  hardware.enableRedistributableFirmware = true;

  age.secrets."wireless.env".file = ../secrets/wifi_penguins.age;

  networking.wireless = {
    enable = true;
    interfaces = ["wlan0"];
    secretsFile = config.age.secrets."wireless.env".path;
    networks = {PENGUINS.pskRaw = "ext:PSK_PENGUINS";};
  };
}
```

Where the decrypted secret contains:

```console
$ agenix -d wifi_penguins.age
PSK_PENGUINS=xyz12345678
```

(no that isn't my password).

The `hardware.enableRedistributableFirmware` is often vital. Check that you set it; if not set it can cause problems on certain hardware that needs it, and I have a vague recollection RPI4 is one platform that needs it.
