### ISSUE TITLE
Update request: haruna 1.1.2 → 1.2.1

### ISSUE THREAD

**Issue by stereomato** [NixOS/nixpkgs#361270]
## Package Information

- Package name: Haruna
- Latest released version: 1.2.1
- Current version on the unstable channel: 1.1.2
- Current version on the stable/release channel: 1.1.2

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@jojosch @kashw2 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SpreadiesInSpace** [comment]
![Screenshot from 2024-12-05 04-57-14](https://github.com/user-attachments/assets/8c415888-4d33-4632-9d3d-ca64f19b21ba)

Sorry for bumping this here, but there currently seems to be a bug where icons do not show up when you install system-wide or for a user via configuration.nix. I am on 24.11 x86_64
