### ISSUE TITLE
installing sqitch from master on macOS fails

### ISSUE THREAD

**Issue by efx** [NixOS/nixpkgs#36139]
## Issue description

```
installing 'perl-App-Sqitch-0.9996'
error: while evaluating the attribute 'propagatedBuildInputs' of the derivation 'perl-App-Sqitch-0.9996' at /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'perl-IO-Pager-0.39' at /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute 'handled' at /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/stdenv/generic/check-meta.nix:203:3:
while evaluating 'handleEvalIssue' at /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/stdenv/generic/check-meta.nix:126:21, called from /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/stdenv/generic/check-meta.nix:204:10:
Package ‘util-linux-2.31.1’ in /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/os-specific/linux/util-linux/default.nix:71 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

### Steps to reproduce

1. add latest as channel:
```
$ nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz latest
$ nix-channel --update latest
```
2. run `nix-env -iA latest.perlPackages.AppSqitch --show-trace`

## Technical details
I think this is from this commit: https://github.com/NixOS/nixpkgs/pull/30798/commits/d8ef4d510bc80cb073aedf45767777ca8ed6d416#diff-7125c606898e1eb839ffc277a5eca467R7163
That propagated build input should not be activated for macOS.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.03pre129212.098c7f3d945"`
 - channels(me): `"latest"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by efx** [comment]
Would updating that line to `propagatedBuildInputs = stdenv.lib.optional stdenv.isLinux pkgs.utillinux.bin;` fix this? I am unable to test this because of another odd bug when running `nix-build -A perlPackages.AppSqitch` from a clone of this repo.

**Comment by LnL7** [comment]
Getting rid of linux specific dependencies like `utillinux` or `glibc` is usually a good first step. A bunch of commands from utillinux are available but spread across a bunch of smaller packages like `darwin.basic_cmds`, nix-index is pretty useful to help locate these.

**Comment by matthewbauer** [comment]
Has this been fixed? The more thing is definitely not an issue anymore.

**Comment by efx** [comment]
Seems to be fixed for me. I'll note that it used precompiled sources so am not fully sure.
