### ISSUE TITLE
`unstable.vscode` with `NIXOS_OZONE_WL=1` no longer accepts a file argument

### ISSUE THREAD

**Issue by hexclover** [NixOS/nixpkgs#361330]
## Describe the bug

The `code` command from the latest VSCode package, when used with `NIXOS_OZONE_WL=1`, can no longer be used to open a specifc file. This is because in https://github.com/NixOS/nixpkgs/commit/8ae2932d567cbe792ddfebd537be6fd66f594179, the `--enable-wayland-ime` is passed *before* the file argument in the wrapper. If the file argument is passed just before `--enable-wayland-ime` it works without problem.

## Steps To Reproduce

1. Install `vscode` from the unstable branch.
2. `export NIXOS_OZONE_WL=1`
3. `code /tmp/some-nonexistent-file`
4. VSCode just loads the previous session. The file argument has no effect.

## Expected behavior

A VSCode window should open, with a new tab called `/tmp/some-nonexistent-file`.

## Additional context

If the generated wrapper is like

```bash
exec -a "$0" "/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped"
${NIXOS_OZONE_WL:+${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime}}  "$@"
```

This works:

```bash
"/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped" --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations /tmp/bar --enable-wayland-ime
```

This doesn't:

```bash
"/nix/store/41ggnz98g8pikykphnf3fy06d0wp508q-vscode-1.95.3/bin/.code-wrapped" --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime /tmp/bar
```

It's unclear if other Electron software handles `--enable-wayland-ime` in this way. Since https://github.com/NixOS/nixpkgs/commit/8ae2932d567cbe792ddfebd537be6fd66f594179 is a treewide change maybe there are other packages that require a fix as well.

## Notify maintainers

@34j @eadwu @Synthetica9 @bobby285271 @JohnRTitor 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 34j** [comment]
I can confirm that
```shell
code --enable-wayland-ime /tmp/bar
```
does not work but
```shell
code --enable-wayland-ime=true /tmp/bar
```
so I would like to propose adding `=true`
