### ISSUE TITLE
Build failure: openvswitch

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#361320]
## Steps To Reproduce

1. build *openvswitch*

## Build log

https://gist.github.com/MisileLab/a1ffbbdc25ccaa5d09c995e9f4d39fcd

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 25.05 (Warbler), 25.05.20241202.7df3282`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/l8q3a8b82f4mjfh97k9vn1nhqmwxycyq-source`
```

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

@adamcstephens @kmcopper @netixx @xddxdd 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
This version built successfully by ofborg and hydra on both systems. Is this just a flaky test? Did you try more than once?

**Comment by Ben9986** [comment]
Also builds fine locally on my machine. can you try this again and report back

**Comment by MisileLab** [comment]
> Also builds fine locally on my machine. can you try this again and report back

built on my machine, I don't know why test failed (maybe I was compiling a bunch of program)
