### ISSUE TITLE
fish: Could not set up terminal

### ISSUE THREAD

**Issue by bbc2** [NixOS/nixpkgs#36146]
## Issue description

After logging into my host via SSH, I get the following output despite `rxvt_unicode.terminfo` being installed system-wide:

```
<W> fish: Could not set up terminal.
<W> fish: TERM environment variable set to 'rxvt-unicode-256color'.
<W> fish: Check that this terminal type is supported on this system.
<W> fish: Using fallback terminal type 'ansi'.
Welcome to fish, the friendly interactive shell
```
Subsequent invocations of fish (`fish`, `sudo -s`) are not affected unless `rxvt_unicode.terminfo` is removed (in which case the warning appears twice instead of once on initial SSH login).

### Steps to reproduce

Use the following configuration:

```
users.extraUsers.<username> = {
  shell = pkgs.fish;
  [...]
};
environment.systemPackages = with pkgs; [
  rxvt_unicode.terminfo
];
programs.fish.enable = true;
```

Then, connect to the machine using SSH from `urxvt` (rxvt-unicode) or `termite`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.84, NixOS, 17.09.3094.211309626af (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3094.211309626af"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bbc2** [comment]
I tried grabbing `fish` and `fish-foreign-env` from `unstable-18.03pre129076.831ef4756e3` but that didn't help.

**Comment by rembo10** [comment]
I'm getting the same thing, same setup, on nixos-unstable. Maybe @layus can help?

**Comment by layus** [comment]
Oh, I remember now. By default, it looks in "${ncurses}/share/terminfo".
/etc/terminfo is useless on NixOS. Just there for easy inspection and misleading users ;-).

**Comment by rembo10** [comment]
Cool, thanks for the help! I realized just after I posted that it was being reinitialized with the correct TERMINFO_DIRS. And if I ssh'd in tmux, it would work (tmux sets the $TERM=screen), so I knew it was reading something, I just wasn't sure what. 

But if I ssh'd into a Ubuntu box, I don't get the warnings - so maybe it's something we can fix in nixos? I can have a look.

**Comment by layus** [comment]
Setting TERMINFO_DIRS, that's the way we use to fix it. But fish being very interactive by nature, it initializes the terminal before reading event the most elementary config files. Usually, the shell is responsible for initializing the env vars, so we have a chicken and egg problem here. We need fish to parse and export TERMINFO_DIRS, but fish needs TERMINFO_DIRS to be configured before starting. All the shells handle this by delaying term setup until env vars are read. Fish did it for some time then this problem appeared. Bisection could find the culprit.

If we cannot / do not want to fix this upstream in fish, we can also 
1) add rxvt_unicode to ncurses. It must be the only term emulator that is not in upstream ncurses database. there is no reason to keep it lonely and isolated like that ;-)
2) We could wrap/patch fish in nixos to first parse the environment. The following would be enough. But do we want to wrap every fish invocation in sh ?

```bash
#!/nix/store/...-sh/bin/sh
exec /nix/store/...-fish/bin/fish "$@"
```

**Comment by layus** [comment]
Well, no, that is not enough. We need to detect if this is a login shell... But nonetheless, I do not think we want to wrap fish in another shell. Patchin could be a way to go. The current statu-quo is already the result from a patch I upstreamed to fish.

As for 1., I guess this tells it all: https://lists.gnu.org/archive/html/bug-ncurses/2009-10/msg00032.html

**Comment by wtdcode** [comment]
@layus Linking `~/.terminfo` to `/usr/share/terminfo` works well on OpenWrt. :)

**Comment by layus** [comment]
@bbc2 I guess we can close the issue as this is is an upstream bug, with a known workaround. Feel free to reopen if need be.
