### ISSUE TITLE
atuin postgresql collation error after upgrade

### ISSUE THREAD

**Issue by alazyworkaholic** [NixOS/nixpkgs#361481]
## Describe the bug
I had installed atuin in nixos 24.05 and just upgraded to 24.11.
Now the following messages repeat every few seconds in journalctl:
```
Dec 03 11:01:04 nixos postgres[81037]: [81037] WARNING:  database "atuin" has a collation version mismatch
Dec 03 11:01:04 nixos postgres[81037]: [81037] DETAIL:  The database was created using collation version 2.39, but the operating system provides version 2.40.
Dec 03 11:01:04 nixos postgres[81037]: [81037] HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE atuin REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
```

## Steps To Reproduce

1. Enable atuin service in nixos 24.05
2. Upgrade to nixos 24.11
3. Note errors in logs

## Expected behavior

I expect something to automatically modify the state of the atuin database when upgrading nixos such that there is no collation mismatch. Failing that, instructions for noobs on how to connect to the atuin database and update the collation version manually.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.710050.62c435d93bf0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager-24.11.tar.gz, nixos-24.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@SuperSandro2000 
@Sciencentistguy 
@0x4A6F 

---

Note for maintainers: Please tag this issue in your PR.

    @SuperSandro2000
    @Sciencentistguy
    @0x4A6F

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
This is not an error but just a warning and to resolve it just execute the mentioned command. A general fix in PostgreSQL was declined a while ago.

**Comment by alazyworkaholic** [comment]
@SuperSandro2000, no general fix is fine, but how does one run the command?
There is no readily accessible information in the readme, searching the atuin [forum](https://forum.atuin.sh/) or repo for [connect postgresql](https://github.com/atuinsh/atuin/issues?q=is%3Aissue+connect+postgresql) turns up no useful issues, and general googling got me nowhere.
`pgcli` looks like a suitable tool, but would you provide an example of how to connect to the atuin database (assuming the simplest default declarative local nixos install) and run the command?
