### ISSUE TITLE
Update request: _1password-gui 8.10.48 → 8.10.54

### ISSUE THREAD

**Issue by kpine** [NixOS/nixpkgs#361522]
In my testing the latest version seems to fix a crash (sigsegv) I was seeing with 8.10.48: https://1password.community/discussion/148424/trying-to-print-recovery-code-crashes-the-application

I used an overlay to install the latest.

```nix
{ pkgs, ... }:
{
  nixpkgs.overlays = [
    (final: prev: {
      _1password-gui = prev._1password-gui.overrideAttrs (
        finalAttrs: previousAttrs: {
          version = "8.10.54";
          src = pkgs.fetchurl {
            url = "https://downloads.1password.com/linux/tar/stable/x86_64/1password-${finalAttrs.version}.x64.tar.gz";
            hash = "sha256-kpFO59DPBCgD3EdYxq1tom/5/misBsafbsJS+Wj2l3I=";
          };
        }
      );
    })
  ];
}
```

## Package Information

- Package name: `_1password-gui`
- Latest released version: [8.10.54](https://releases.1password.com/linux/8.10/#1password-for-linux-8.10.54)
- Current version on the unstable channel: 8.10.48
- Current version on the stable/release channel: 8.10.48

## Checklist

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@khaneliman @timstott @savannidgerinel @SebTM 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SebTM** [comment]
Nice timing ;) https://github.com/NixOS/nixpkgs/pull/361520
