### ISSUE TITLE
Add updateScript passhru to packages hosted on GNOME servers

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#36150]
#### Why?
Adding the `updateScript` will allow us to get rid of the mindless part of updating – replacing versions and modifying hashes. This is especially important for package collections like `gnome3`, where many packages are updated at the same time.

#### How?
1. Make sure the `src` attribute will work when version attribute is changed. This usually means the url is in the form `mirror://gnome/sources/${pname}/${stdenv.lib.versions.majorMinor version}/${pname}-${version}.tar.xz`, where `pname` is the name without a version.

2. Add the following attribute to the package expression:

```nix
  passthru = {
    updateScript = gnome3.updateScript {
      packageName = "folks"; # This is the name of the FTP directory containing the package. It is used for looking up available versions.
      attrPath = "gnome3.folks"; # (optional) This is the attribute path used with `nix-build -A` and `update-source-version` script. Can be omitted if same as the `packageName`.
      versionPolicy = "none"; # (optional) By default the update script respects the [GNOME version policy](https://developer.gnome.org/programming-guidelines/stable/versioning.html.en#stable-unstable-versions) – odd minor versions are considered unstable and will be ignored. If a package does not use this policy, it can be disabled.
    };
  };
```

Original pull request: https://github.com/NixOS/nixpkgs/pull/33086/commits/4145f5e3b0effac8f2593f744626e9db28792fd5

#### What?

The following files can be updated:

```
$ comm -23 <(git grep -l mirror://gnome | sort) <(git grep -l updateScript | sort)
```

- [x] pkgs/applications/audio/easytag/default.nix
- [x] pkgs/applications/audio/rhythmbox/default.nix
- [ ] pkgs/applications/graphics/gthumb/default.nix
- [x] pkgs/applications/graphics/shotwell/default.nix
- [x] pkgs/applications/misc/orca/default.nix
- [ ] pkgs/applications/misc/pdfmod/default.nix
- [ ] pkgs/applications/networking/instant-messengers/ekiga/default.nix
- [ ] pkgs/applications/office/gnumeric/default.nix
- [x] pkgs/applications/version-management/meld/default.nix
- [x] pkgs/applications/video/pitivi/default.nix
- [ ] pkgs/data/documentation/gnome-user-docs/default.nix
- [x] pkgs/data/fonts/cantarell-fonts/default.nix
- [ ] pkgs/data/fonts/ttf-bitstream-vera/default.nix
- [x] pkgs/data/misc/mobile-broadband-provider-info/default.nix
- [ ] pkgs/desktops/gnome-2/bindings/gnome-python/default.nix
- [ ] pkgs/desktops/gnome-2/bindings/gnome-python-desktop/default.nix
- [ ] pkgs/desktops/gnome-2/bindings/libglademm/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-control-center/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-desktop/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-icon-theme/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-keyring/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-menus/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-panel/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-session/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gnome-settings-daemon/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/gtksourceview/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/libgnomekbd/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/libgweather/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/metacity/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/rarian/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/scrollkeeper/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/vte/default.nix
- [ ] pkgs/desktops/gnome-2/desktop/zenity/default.nix
- [ ] pkgs/desktops/gnome-2/platform/at-spi/default.nix
- [ ] pkgs/desktops/gnome-2/platform/GConf/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gconfmm/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gnome-common/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gnome-mime-data/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gnome-vfs/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gnome-vfs-monikers/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gtkglext/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gtkglextmm/default.nix
- [ ] pkgs/desktops/gnome-2/platform/gtkhtml/4.x.nix
- [ ] pkgs/desktops/gnome-2/platform/gtkhtml/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libart_lgpl/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libbonobo/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libbonoboui/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libglade/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomecanvas/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomecanvasmm/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomecups/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnome/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomeprint/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomeprintui/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgnomeui/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libgtkhtml/default.nix
- [ ] pkgs/desktops/gnome-2/platform/libIDL/default.nix
- [ ] pkgs/desktops/gnome-2/platform/ORBit2/default.nix
- [ ] pkgs/desktops/gnome-3/apps/gnome-nettool/default.nix
- [x] pkgs/desktops/gnome-3/apps/nautilus-sendto/default.nix
- [x] pkgs/desktops/gnome-3/core/caribou/default.nix
- [x] pkgs/desktops/gnome-3/core/dconf/default.nix
- [ ] pkgs/desktops/gnome-3/core/gconf/default.nix
- [ ] pkgs/desktops/gnome-3/core/gnome-menus/default.nix
- [x] pkgs/desktops/gnome-3/core/gnome-system-log/default.nix
- [x] pkgs/desktops/gnome-3/core/grilo/default.nix
- [x] pkgs/desktops/gnome-3/core/grilo-plugins/default.nix
- [x] pkgs/desktops/gnome-3/core/gsound/default.nix
- [x] pkgs/desktops/gnome-3/core/libcroco/default.nix
- [x] pkgs/desktops/gnome-3/core/libgdata/default.nix
- [x] pkgs/desktops/gnome-3/core/libgee/default.nix
- [x] pkgs/desktops/gnome-3/core/libgepub/default.nix
- [x] pkgs/desktops/gnome-3/core/libgnome-keyring/default.nix
- [x] pkgs/desktops/gnome-3/core/libgxps/default.nix
- [x] pkgs/desktops/gnome-3/core/libzapojit/default.nix
- [x] pkgs/desktops/gnome-3/core/rest/default.nix
- [ ] pkgs/desktops/gnome-3/core/vte/2.90.nix
- [x] pkgs/desktops/gnome-3/desktop/rarian/default.nix
- [ ] pkgs/desktops/gnome-3/extensions/chrome-gnome-shell/default.nix
- [x] pkgs/desktops/gnome-3/misc/california/default.nix
- [x] pkgs/desktops/gnome-3/misc/geary/default.nix
- [x] pkgs/desktops/gnome-3/misc/gexiv2/default.nix
- [x] pkgs/desktops/gnome-3/misc/gfbgraph/default.nix
- [x] pkgs/desktops/gnome-3/misc/gnome-video-effects/default.nix
- [x] pkgs/desktops/gnome-3/misc/libgames-support/default.nix
- [x] pkgs/desktops/gnome-3/misc/libmediaart/default.nix
- [ ] pkgs/development/compilers/vala/default.nix
- [x] pkgs/development/libraries/atk/default.nix
- [x] pkgs/development/libraries/atkmm/default.nix
- [x] pkgs/development/libraries/at-spi2-atk/default.nix
- [x] pkgs/development/libraries/at-spi2-core/default.nix
- [ ] pkgs/development/libraries/cairomm/default.nix
- [x] pkgs/development/libraries/clutter/default.nix
- [x] pkgs/development/libraries/clutter-gst/default.nix
- [x] pkgs/development/libraries/clutter-gtk/default.nix
- [x] pkgs/development/libraries/cogl/default.nix
- [ ] pkgs/development/libraries/gcab/default.nix
- [x] pkgs/development/libraries/gdk-pixbuf/default.nix
- [x] pkgs/development/libraries/glib/default.nix
- [x] pkgs/development/libraries/glibmm/default.nix
- [x] pkgs/development/libraries/glib-networking/default.nix
- [ ] pkgs/development/libraries/gmime/2.nix
- [ ] pkgs/development/libraries/gmime/3.nix
- [x] pkgs/development/libraries/gobject-introspection/default.nix
- [x] pkgs/development/libraries/goffice/0.8.nix
- [x] pkgs/development/libraries/goffice/default.nix
- [ ] pkgs/development/libraries/goocanvas/2.x.nix
- [ ] pkgs/development/libraries/goocanvas/default.nix
- [x] pkgs/development/libraries/gssdp/default.nix
- [ ] pkgs/development/libraries/gstreamer/gstreamermm/default.nix
- [ ] pkgs/development/libraries/gstreamer/legacy/gstreamermm/default.nix
- [ ] pkgs/development/libraries/gtk+/2.x.nix
- [x] pkgs/development/libraries/gtk+/3.x.nix
- [ ] pkgs/development/libraries/gtkmm/2.x.nix
- [x] pkgs/development/libraries/gtkmm/3.x.nix
- [ ] pkgs/development/libraries/gtk-sharp/2.0.nix
- [ ] pkgs/development/libraries/gtk-sharp/3.0.nix
- [ ] pkgs/development/libraries/gupnp-av/default.nix
- [ ] pkgs/development/libraries/gupnp/default.nix
- [ ] pkgs/development/libraries/gupnp-dlna/default.nix
- [ ] pkgs/development/libraries/gupnp-igd/default.nix
- [x] pkgs/development/libraries/gvfs/default.nix
- [ ] pkgs/development/libraries/hyena/default.nix
- [x] pkgs/development/libraries/json-glib/default.nix
- [x] pkgs/development/libraries/libchamplain/default.nix
- [ ] pkgs/development/libraries/libgnome-keyring/default.nix
- [x] pkgs/development/libraries/libgsf/default.nix
- [x] pkgs/development/libraries/libgtop/default.nix
- [x] pkgs/development/libraries/libgudev/default.nix
- [x] pkgs/development/libraries/libhttpseverywhere/default.nix
- [ ] pkgs/development/libraries/libnotify/default.nix
- [x] pkgs/development/libraries/librsvg/default.nix
- [x] pkgs/development/libraries/libsecret/default.nix
- [ ] pkgs/development/libraries/libsigcxx/1.2.nix
- [ ] pkgs/development/libraries/libsigcxx/default.nix
- [x] pkgs/development/libraries/libsoup/default.nix
- [ ] pkgs/development/libraries/libunique/default.nix
- [x] pkgs/development/libraries/libwnck/3.x.nix
- [ ] pkgs/development/libraries/libwnck/default.nix
- [ ] pkgs/development/libraries/libxklavier/default.nix
- [ ] pkgs/development/libraries/libxmlxx/default.nix
- [ ] pkgs/development/libraries/libxmlxx/v3.nix
- [ ] pkgs/development/libraries/opal/default.nix
- [x] pkgs/development/libraries/pango/default.nix
- [x] pkgs/development/libraries/pangomm/default.nix
- [ ] pkgs/development/libraries/pangox-compat/default.nix
- [ ] pkgs/development/libraries/ptlib/default.nix
- [x] pkgs/development/python-modules/pyatspi/default.nix
- [x] pkgs/development/python-modules/pygobject/3.nix
- [ ] pkgs/development/python-modules/pygobject/default.nix
- [ ] pkgs/development/python-modules/pygtk/default.nix
- [ ] pkgs/development/tools/documentation/gnome-doc-utils/default.nix
- [ ] pkgs/development/tools/documentation/gtk-doc/default.nix
- [x] pkgs/development/tools/misc/d-feet/default.nix
- [ ] pkgs/development/tools/misc/gob2/default.nix
- [ ] pkgs/misc/themes/gtk2/gtk-engine-murrine/default.nix
- [x] pkgs/tools/admin/gtk-vnc/default.nix
- [x] pkgs/tools/networking/gupnp-tools/default.nix
- [ ] pkgs/tools/networking/network-manager/0.9.8/default.nix
- [x] pkgs/tools/networking/network-manager-applet/default.nix
- [x] pkgs/tools/networking/network-manager/default.nix
- [x] pkgs/tools/networking/network-manager/fortisslvpn.nix
- [x] pkgs/tools/networking/network-manager/iodine.nix
- [x] pkgs/tools/networking/network-manager/openconnect.nix
- [x] pkgs/tools/networking/network-manager/openvpn.nix
- [x] pkgs/tools/networking/network-manager/pptp.nix
- [x] pkgs/tools/networking/network-manager/vpnc.nix
- [ ] pkgs/tools/security/polkit-gnome/default.nix

**Comment by Anton-Latukha** [comment]
- [x] `at-spi2-core`
- [x] `at-spi2-gtk`

**Comment by JohnAZoidberg** [comment]
Since the source is `mirror://gnome/sources/${pname}/${stdenv.lib.versions.majorMinor version}/${pname}-${version}.tar.xz` for pretty much all gnome packages shouldn't be make a function for that?

**Comment by jtojnar** [comment]
It might make sense. We are generally avoiding writing a custom fetch functions, as they obscure where is the file coming from, but one could argue that `mirror://` already does the same.

**Comment by jtojnar** [comment]
The remaining are mostly just dead projects.
