### ISSUE TITLE
many qt apps crash on launch??

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#36173]
## Issue description

Seems to be due to the 5.10.1 update, but I haven't personally checked if reverting that resolves the issue.

* lxterminal: #36160 
* VirtualBox gui
* okular
* snowman

... Probably most of them?

### Steps to reproduce

Using recent master:
```
$ nix run -f https://github.com/NixOS/nixpkgs/archive/798fb575c23d3f457fccfdf1e1e6b126894bd26e.tar.gz okular -c okular
zsh: segmentation fault (core dumped)  nix run -f  okular -c okular
$ # :(
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.6, NixOS, 18.03.git.77cf44f (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0dtz6016_e761dc3`
 - channels(will): `"allvm, nixos-1609-16.09.1943.25f4906da6, unstable-18.03pre129076.831ef4756e3"`
 - channels(root): `"nixos-18.03pre129076.831ef4756e3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by dtzWill** [comment]
Erm, you should probably install the packages first, otherwise they have trouble finding the xcb plugin or something.  But anyway still crashes.

**Comment by rnhmjoj** [comment]
I noticed it too yesterday when building an application (mkvtoolnix) using 5.10. It sometimes says `Cannot mix incompatible Qt library (version 0x50a00) with this library (version 0x50a01)` before dumping core. I figured out it was picking some Qt plugin from my nix profile.

**Comment by jtojnar** [comment]
Indeed, this happens with every QT update and it is caused by mixing QT library versions.

**Comment by dtzWill** [comment]
D'oh, okay.  Confirmed it works in a clean VM.  Thought it would just give an error if I was mixing things ("Cannot mix incompatible" or the xcb plugin error) instead of crashing, but if this is expected/normal then nevermind.

Sorry for the noise :3.

**Comment by jtojnar** [comment]
I do not think this is expected, there was some effort to fix this https://github.com/NixOS/nixpkgs/issues/15498 https://github.com/NixOS/nixpkgs/issues/17448 but as I understand it, it is very hard, or even impossible when you have installed QT applications using both `configuration.nix` and `nix-env`.

**Comment by dtzWill** [comment]
I'll take a look at those out of curiosity but I didn't mean to imply this was anyone's failing :).

Hey, quick question if you don't mind-- is it intended/expected for qt 5.10 to use qtwebkit 5.9?
Is that an oversight or intentional? Stumbled on it while trying to purge my profile of Qt apps... xD.

**Comment by jtojnar** [comment]
I have read various conflicting claims about API and ABI stability but I would not expect that. Though I am just a GNOME guy passing by, better ask someone who actually understands it.
