### ISSUE TITLE
Update request: terraform 1.10.0 → 1.10.1

### ISSUE THREAD

**Issue by jaudiger** [NixOS/nixpkgs#361861]
## Package Information

- Package name: terraform
- Latest released version: 1.10.1
- Current version on the unstable channel: 1.10.0
- Current version on the stable/release channel: 1.9.8

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@r-ryantm @Chili-Man @kalbasit @timstott @zimbatm @zowoq @techknowlogick @qjoly

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by techknowlogick** [comment]
created PR: https://github.com/NixOS/nixpkgs/pull/361915
