### ISSUE TITLE
hash mismatch in fixed-output derivation

### ISSUE THREAD

**Issue by jee-mj** [NixOS/nixpkgs#361931]
https://github.com/NixOS/nixpkgs/blob/55d15ad12a74eb7d4646254e13638ad0c4128776/pkgs/applications/audio/mixxx/default.nix#L66

```
         specified: sha256-foY4K1rSth0GUjM1xpctI3fpavVjGoPMnRN2tT4Lsqg=
            got:    sha256-YfpFRLosIIND+HnZN+76ZY0dQqEJaFkWZS84gZOCdfc=
```

https://github.com/mixxxdj/mixxx/releases/tag/2.4.2

**Comment by jee-mj** [comment]
@bfortz @benley

**Comment by benley** [comment]
I think this has been corrected in https://github.com/NixOS/nixpkgs/pull/361718
