### ISSUE TITLE
callCabal2nix default.nix is garbage collected

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#36190]
When using `callCabal2nix`, the resulting derivation has no gc link to the IFD'd `default.nix`. I think this should be added as a build time dependency so that `cabal2nix` doesn't get collected, and so you don't have to repeatedly wait for the derivation to be built. It's minor, but enough to be annoying.

**Comment by shlevy** [comment]
:+1: from me.

**Comment by peti** [comment]
I'm not sure whether I understand this correctly. You want to prevent the garbage collector from collecting a file that it *could* collect so that this file doesn't have to be re-built even though it *can* be re-built?

**Comment by shlevy** [comment]
@peti It would only be a  build-time dependency, and thus only kept if `keep-derivations` and `keep-outputs` are both true. Those settings indicate "I don't want to have to do any work to rebuild things I already have and I'll take the disk hit"

**Comment by peti** [comment]
Hmm, okay. That sounds fine.

**Comment by ncfavier** [comment]
Just pointing out that https://github.com/NixOS/nixpkgs/pull/36216 was reverted by https://github.com/NixOS/nixpkgs/pull/194753 to avoid rebuilds, but you can still explicitly add a GC root on `haskellPackages.foo.cabal2nixDeriver`.
