### ISSUE TITLE
Package request: shuttle

### ISSUE THREAD

**Issue by satler-git** [NixOS/nixpkgs#361954]
## Project description

nixpkgs already has `cargo-shuttle`.
but the package only outputs `cargo-shuttle` (without the `shuttle` command).

This is declared here.

https://github.com/NixOS/nixpkgs/blob/b681065d0919f7eb5309a93cea2cfa84dec9aa88/pkgs/by-name/ca/cargo-shuttle/package.nix#L45-L48

If you install by running `cargo install cargo-shuttle`, you will have both `cargo-shuttle` and `shuttle` commands.

Quoted from [shuttle.dev Docs](https://docs.shuttle.dev/getting-started/installation)
> After installation, you will have two commands: shuttle and cargo shuttle.
> `shuttle` is used for interacting with the NEW `shuttle.dev` platform.
> `cargo shuttle` is used for interacting with the `shuttle.rs` platform.
> This documentation covers the NEW `shuttle.dev` platform. Go to [docs.shuttle.rs](https://docs.shuttle.rs/) to view the docs for the shuttle.rs platform.

Note: nixpkgs already has a package named `shuttle` (this is not the same with both `cargo-shuttle` and `shuttle` commands), so the package name will be like `shuttle-cli` (If you package it differently from `cargo-shuttle`.).

## Metadata

* homepage URL: https://shuttle.dev/
* source URL: https://github.com/shuttle-hq/shuttle
* license: Apache-2.0
* platforms: unix, linux, darwin
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by satler-git** [comment]
I was confused and it's not declared there.

**Comment by catbrained** [comment]
I updated cargo-shuttle from 0.47.0 to 0.49.0 on my machine and I now have the *shuttle* command which uses the new shuttle.dev platform API.
The only thing I changed in the package was the `version` and the hashes. I skimmed the shuttle changelog, but I didn't find any mention of this change, so not sure when that happened.

Anyway, #361827 should close this.

**Comment by satler-git** [comment]
The `shuttle` binary has been merged and released in 0.48.0.

https://github.com/shuttle-hq/shuttle/blob/main/CHANGELOG.md#0480---2024-10-01

And #361827 has been marged, so I am closing it.

**Comment by kiike** [comment]
Thanks you all for the package. Using it for the shuttle xmas hunt and it's working great!
