### ISSUE TITLE
Update request: git-open 3.0.0 → 3.1.0

### ISSUE THREAD

**Issue by wolcen** [NixOS/nixpkgs#362099]
## Package Information

- Package name: git-open
- Latest released version: 3.1.0
- Current version on the unstable channel: 3.0.0
- Current version on the stable/release channel: 3.0.0

## Checklist

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@SuperSandro2000 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please create PRs instead of pinging me with tickets :)

**Comment by SuperSandro2000** [comment]
#362111

**Comment by wolcen** [comment]
Sorry! Still very new to NixOS (loving it so far). I did actually make an attempt, and while I found that you can empty the hash and use the error to get the updated one, I still couldn't figure out how actually run a test build of the package.

**Comment by SuperSandro2000** [comment]
Just clone the repo, run nix-build -A git-open and ./result/bin/git-open

**Comment by drakon64** [comment]
> Please create PRs instead of pinging me with tickets :)

If you don't want to be pinged about a package you maintain being outdated, consider removing yourself as a maintainer of that package.

**Comment by llakala** [comment]
> Just clone the repo, run nix-build -A git-open and ./result/bin/git-open
> 
> To check out PR I usually just use the provided gh command by the GitHub UI.

As an alternative, I personally recommend `git pr`, from [git-extras](https://github.com/tj/git-extras/blob/main/Commands.md#git-pr). I found out about it recently, and it's been really helpful.
