### ISSUE TITLE
systemd.timers.<name>.timerConfig description error

### ISSUE THREAD

**Issue by mfiano** [NixOS/nixpkgs#36210]
## Issue description

Should be man volume 5 for systemd.timer and 7 for systemd.time

### Steps to reproduce

https://nixos.org/nixos/options.html#timerconfig

## Technical details

None

**Comment by peterhoeg** [comment]
```nixos/modules/system/boot/systemd-unit-options.nix``` is the file if you're keen on doing a PR.
