### ISSUE TITLE
Clean, generic, language-agnostic cross-compilation-aware core build infrastructure

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#36217]
TODO @Ericson2314 fill this out

1. [ ] Make `mkDerivation` a wrapper that desugars the legacy input names as proposed above. No more `{propagated,}{Native,}BuildInputs` in bash.

2. [ ] Move away from autoconf terminology to `build`, `run`, `emit` (isomorphic renaming).

3. [ ] Make env hooks more coarse-grained, I see no use for the second axis for them.

Action item from https://github.com/NixOS/nixpkgs/issues/35543

**Comment by siraben** [comment]
Any updates on this?

**Comment by Ericson2314** [comment]
I would say I never filled this out, and the first steps are tracked in issue #28327 and PR #72074. Perhaps we want larger changes, but I'd say that hinges on larger cleanups of Nixpkgs in general.
