### ISSUE TITLE
Cannot boot with 6.12.2 kernel

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#362270]
## Describe the bug

Can not boot with 6.12.2 kernel, reboot cycled
I have 2 generations with 6.12.2 (https://github.com/NixOS/nixpkgs/issues/362160) but can boot only with 5e9ea2c build with 6.12.1

```
❯ ll /run/booted-system
lrwxrwxrwx 1 root root 82 дек  6 04:18 /run/booted-system -> /nix/store/0x5q4ymvqaf1y1xisww350bk1ag53ryk-nixos-system-a7-25.05.20241206.5e9ea2c

❯ uname -a
Linux a7 6.12.1 #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov 22 14:30:26 UTC 2024 x86_64 GNU/Linux


Version 23614 -> 23615:
  nixos-system-a7: 25.05.20241206.4f2613d → 25.05.20241206.5e9ea2c
```

This two not accessible:

```
Version 23615 -> 23616:
  cpupower: 6.12.1 → 6.12.2
  initrd-linux: 6.12.1 → 6.12.2, -48.0 KiB
  linux: 6.12.1, 6.12.1-modules → 6.12.2, 6.12.2-modules, +10.2 KiB
  nixos-system-a7: 25.05.20241206.5e9ea2c → 25.05.20241206.867db1d

Version 23616 -> 23617:
  nixos-system-a7: 25.05.20241206.867db1d → 25.05.20241206.5c9f897
```

## Metadata

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 25.05 (Warbler), 25.05.20241206.a9137d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/11m96cfjfvxnxwa5qvvmivzf1idii83i-source`

```

## Notify maintainers
@alyssais @K900 @philiptaron 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by spiage** [comment]
Now it is fine with 6.12.3

**Comment by philiptaron** [comment]
For reference, the PR that fixed it was this one:

- https://github.com/NixOS/nixpkgs/pull/362325
