### ISSUE TITLE
Xcodebuild license check fails inside builds on MacOs

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#36221]
## Issue description

I am building a project that tries to use `xcodebuild` for some stuff. Inside the build script, the following returns false, even though I have already accepted the Xcode license for all users:
```
/usr/bin/xcrun xcodebuild -license check
```

I tried things like puting `xcodeenv.xcodewrapper` as part of the `buildInputs` without success...

### Steps to reproduce

Write a derivation that includeds `/usr/bin/xcrun xcodebuild -license check` as part of its `buildCommand` and try to run it in NixOS.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
nix-shell -p nix-info --run "nix-info -m"
error: undefined variable ‘nix-info’ at (string):1:66
(use ‘--show-trace’ to show detailed location information)
```
???
```
nix-shell --version
nix-shell (Nix) 1.11.14
```
```
MacOS Sierra 10.12.6 (16G29)
xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
```

**Comment by matthewbauer** [comment]
In general we just remove this checks:

https://github.com/NixOS/nixpkgs/blob/e51a982fec5f2017ac8d8ee1594996e4349083c2/pkgs/development/libraries/qt-5/5.9/qtbase.patch#L456-L468

The ideal solution is to use Facebook's open source "xcbuild". I know that it doesn't always work well (some projects depend on weird xcodebuild configs). We can look into supporting native xcodebuild but remember that MacOS does not come with XCode installed by default.

**Comment by LnL7** [comment]
Using xcode and things like `/usr/bin` is also impure.
