### ISSUE TITLE
git credential-osxkeychain does not appear to work [ darwin ]

### ISSUE THREAD

**Issue by efx** [NixOS/nixpkgs#36223]
## Issue description
I installed `git` via `nix-env -iA latest.gitAndTools.gitFull`.
Everything installed fine, but my SSH credentials are not being cached correctly.
This appears to be a problem with `git credential-osxkeychain`.
Running `git credential-osxkeychain erase` hangs indefinitely. Any of the `git credential-osxkeychain` commands seem to hang too.
Using Apple's version of git available by `xcode-select --install` works as expected:
```
 git --version                 
git version 2.14.3 (Apple Git-98)
```

### Steps to reproduce

1. nix-env -iA latest.gitAndTools.gitFull
2. clone a private repo that requires your SSH key
3. enter the passphrase
4. clone another private repo and notice you still need to enter they passphrase

## Technical details
Note that `latest` is a channel I added with `nix-channel --add https://github.com/NixOS/nixpkgs/archive/master.tar.gz latest`
```
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.03pre129212.098c7f3d945"`
 - channels(efx): `"nixpkgs-latest, latest"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by LnL7** [comment]
I think we generally try to avoid macOS specific features like that since it usually depends on impure parts of the system like frameworks.

**Comment by efx** [comment]
This makes sense to me. Shouldn't we disable installing this when macOS users install git using nix though? That way we avoid confusion that it should work.

**Comment by LnL7** [comment]
Yeah that's a good idea.

**Comment by matthewbauer** [comment]
I cannot reproduce this. One thing that should happen when first doing this is that the dialog opens asking if the app can access your keychain. Perhaps this is not happening? Some AV or enterprise config profilsmes might disable this feature for unknown binaries.

**Comment by efx** [comment]
interesting @matthewbauer . I had first installed git using xcode-select, so I wonder if that could impact this. Also, our organization uses Jamf for device profile management. I'm not sure how to determine if that impacts this.

**Comment by uri-canva** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/15686
