### ISSUE TITLE
vmware video driver crashes loading GLX if 3D acceleration is on after upgrading to 24.11

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#362294]
## Describe the bug
After upgrading to 24.11 my VM in VMWare Workstation X11 wouldn't work (black screen). Further investigation uncovered segmentation fault in X11 when it was trying to load GLX (the log here https://github.com/NixOS/nixpkgs/issues/361095#issuecomment-2521882766). Turning off 3D acceleration in VMWare Workstation fixed the issue.

## Steps To Reproduce

1. Install VMWare Workstation and create NixOS VM
2. Set video driver to vmware
3. Turn on 3D acceleration

## Expected behavior

X11 starts

## Metadata

 
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.20241203.b681065`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/etc/channels/nixpkgs`

## Notify maintainers
@NickCao @kjeremy 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kjeremy** [comment]
Is your host nixos? I run nixos in a VM with a Windows 11 host and have had 3D acceleration off for a while because of other issues (VM freezes, random corruption etc.) that I've always attributed to the host for one reason or another.

Can you try a newer kernel? https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/vmwgfx has a number of changes since Linux 6.6.

**Comment by alexvorobiev** [comment]
I run VMWare Workstation 16 on windows 10. No issues with the 3D acceleration since forever. The upgrade to 24.11 is the first time I had to turn off the acceleration. Windows 11 has its hypervisor enabled for some security services which is incompatible with this version of VMWare. This is a company laptop with a standard configuration so I can neither demand tweaking the registry to get rid of the hypervisor (even though I know how to do that) nor updating to the next version of VMWare which is compatible with the hypervisor. Hence keeping Windows 10. I have never installed custom kernels in NixOS, will have to read up on that.

**Comment by kjeremy** [comment]
VMWare support told me to add the following to my VM's vmx file which fixed a number of graphical issues:

```ini
mks.enableDX12Renderer = "FALSE"
mks.enableGLRenderer = "TRUE"
```

I'm not sure if that will fix the crash or not but it's worth a shot.

**Comment by rudesome** [comment]
same issue here after upgrading to 24.11

Windows 10 and using VMWare workstation 17.5.2 to run a NixOS VM
Disabling `Accelerate 3D graphics` solved the issue, never had issues before with this option.

**Comment by alexvorobiev** [comment]
> VMWare support told me to add the following to my VM's vmx file which fixed a number of graphical issues:
> 
> ```ini
> mks.enableDX12Renderer = "FALSE"
> mks.enableGLRenderer = "TRUE"
> ```
> 
> I'm not sure if that will fix the crash or not but it's worth a shot.

It seems GLX is now happy!
```
Dec 09 10:31:23 nixos /nix/store/xr6cl3jy97mdaq7bc9mw4s3s1l51wa2v-gdm-47.0/libexec/gdm-x-session[2205]: (II) Initializing extension GLX
Dec 09 10:31:23 nixos /nix/store/xr6cl3jy97mdaq7bc9mw4s3s1l51wa2v-gdm-47.0/libexec/gdm-x-session[2205]: (II) AIGLX: Screen 0 is not DRI2 capable
Dec 09 10:31:23 nixos /nix/store/xr6cl3jy97mdaq7bc9mw4s3s1l51wa2v-gdm-47.0/libexec/gdm-x-session[2205]: (II) IGLX: Loaded and initialized swrast
Dec 09 10:31:23 nixos /nix/store/xr6cl3jy97mdaq7bc9mw4s3s1l51wa2v-gdm-47.0/libexec/gdm-x-session[2205]: (II) GLX: Initialized DRISWRAST GL provider for screen 0
```

But it looks like changes to the VM options in the Virtual Machine Settings window recreate the vmx file without preserving the change. Is there any way to make the two lines permanent?

**Comment by kjeremy** [comment]
They should be there, just reordered. This points to a bug on vmware's side (their dx12 engine is buggy) but they wouldn't change the default for me.

**Comment by tricktron** [comment]
If you still want to profit from 3D acceleration then you can downgrade the mesa version with an overlay to 23.1.9
```nix
# somewhere where you specify your overlays / additional pkgs
mesa-23_1_9 = (import (builtins.fetchTarball
{
    url    = "https://github.com/NixOS/nixpkgs/archive/eabe8d3eface69f5bb16c18f8662a702f50c20d5.tar.gz";
    sha256 = "sha256:1ghs47vph6m7w8abnhddqxa3sbswxv3j9xyxd4pz2xvww41r0drr";
}) { inherit (pkgs) system; }).mesa;
```
and then use its drivers with
```nix
# configuration.nix
hardware.graphics.package = pkgs.mesa-23_1_9.drivers; 
```

If you run VMware on a Windows Host then make sure to use the DirectX11 renderer because the virtualised SVGA II graphics card does not yet support DirectX12 as far as I know:

```bash
# vmx file
mks.enableVulkanRenderer = "FALSE" # disable vulkan renderer, only useful on linux hosts
mks.enableDX12Renderer = "FALSE" # disable dx12 renderer
mks.enableDX11Renderer = "TRUE" # enable dx11 renderer
mks.enableGLRenderer = "FALSE" # disable gl renderer

mks.dx11.allowBlacklistedDrivers = "TRUE" # may be needed if vmware does not like your driver, check mksSandbox.log for errors / more details
mks.dx11.allowUnsupportedDevices = "TRUE" # may be needed if vmware thinks your device is unsupported, check mksSandbox.log for errors / more details
mks.dx11.vendorID = 0x10de # only needed if you have multiple GPUs and you want to force vmware
#  to use a specific GPU for the rendering, e.g. in a laptop with a dedicated Nvidia GPU and 
# integrated Intel Graphics you might want to force vmware to use the Nvidia GPU.
# The vendor ID can be found in the mksSandbox.log file as well 
```
