### ISSUE TITLE
Is `nixUnstable` necessary to build Hydra?

### ISSUE THREAD

**Issue by ixmatus** [NixOS/nixpkgs#36230]
I ask because we've discovered, recently, that Hydra is using `nix-1.12pre5788_e3013543` when we expected it to be using `nix-1.11.16` from the pinned `nixpkgs-17.09` we use to build our Hydra configuration.

We noticed this is because of the [`nixUnstable`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/hydra/default.nix#L1) argument to the function which returns the Hydra derivation, introduced in 3e63180 almost two years ago.

CC: @domenkozar

**Comment by domenkozar** [comment]
Yes, Hydra is always using latest features of Nix as it sadly depends on Nix internals.

**Comment by ixmatus** [comment]
@domenkozar I understand that it depends on Nix internal library code, which I don't think is a problem, I just thought it odd that it depended on `nixUnstable`. I'd expect Hydra to track the stable version of Nix at all times since it is a CI tool.

If we overrode our Hydra installation to change `nixUnstable` to `nix`, what would that break?

**Comment by domenkozar** [comment]
Yes - Hydra uses Nix C++ api that has changed in nixUnstable. Right now it probably matches Nix 2.0 though :)

**Comment by ixmatus** [comment]
@domenkozar oh! I understand now and because the C++-ification of Nix has been underway for about two years (or more?) that is why `nixUnstable` has continued to be used for the last two years.

Okay. Thanks for cluing me in, I'm closing this since my question has been answered, thanks!
