### ISSUE TITLE
Update request: timeshift 24.06.3 → 24.06.5

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#362404]
## Package Information

- Package name: timeshift
- Latest released version: 24.06.5
- Current version on the unstable channel:  24.06.3
- Current version on the stable/release channel: 24.06.3

## Checklist

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@ShamrockLee  
@bobby285271

https://github.com/linuxmint/timeshift/blob/master/debian/changelog

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ShamrockLee** [comment]
I created a PR (#362439) to update it. Could you help me test it?

BTW, glad to know that people are using the Timeshift package. Does it work well on your system?

**Comment by ShamrockLee** [comment]
We may also need to investigate why the rryatm bot does not update it automatically.
