### ISSUE TITLE
Package request: cargo-aoc

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [NixOS/nixpkgs#362526]
## Project description

> _"cargo-aoc is a simple CLI tool that aims to be a helper for the [Advent of Code](https://adventofcode.com/). Implement your solution. Let us handle the rest."_
> - from their cargo page

Features
- Input downloading
- Running your solution
- Automatic benchmarking of your solution using [Criterion](https://github.com/japaric/criterion.rs)

## Metadata

* homepage URL: https://crates.io/crates/cargo-aoc
* source URL: https://github.com/gobanos/cargo-aoc
* license: None (MIT OR Apache-2.0 according to crates.io)
* platforms: unknown

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Defelo** [comment]
@Tygo-van-den-Hurk I created a pull request at #362859, maybe you could have a look at it?

**Comment by Tygo-van-den-Hurk** [comment]
I wouldn't mind, however I'm not intimately familiar with packaging. I'd like to get better at this so if you could give me some pointers of what you usually look at to check that'd be nice. Without some hand holding I won't be of much use I'm afraid.

**Comment by Defelo** [comment]
No problem! For starters you could verify that the package name, version, source (github repo), and metadata (description, homepage, license, ...) all match what you would expect. Then you could check that the package actually builds and works as intended, e.g. using `nix shell github:nixos/nixpkgs/pull/362859/merge#cargo-aoc` and then `cargo aoc ...`

**Comment by Tygo-van-den-Hurk** [comment]
Ah okay, got it! 
- All the metadata checks out, though I am personally confused with the license not being on the GH page.
- Checked if it builds and it does, also appears to function as normal!

**Comment by Defelo** [comment]
Great! About the license, for some reason they have put it into the cargo-aoc directory instead of the project root, so GitHub doesn't detect it automatically
