### ISSUE TITLE
Packaging Issue: avante-nvim plugin unable to find dependencies

### ISSUE THREAD

**Issue by nbCloud91** [NixOS/nixpkgs#362833]
## Issue Description
The avante-nvim plugin packaged in nixpkgs is unable to find its required dependencies (nui.nvim, plenary.nvim, dressing.nvim) despite them being properly declared in the package definition. This causes the plugin to fail during initialization.

## Steps to Reproduce

1. Add avante-nvim to neovim configuration in home-manager:

```nix
{
  programs.neovim = {
    enable = true;
    plugins = with pkgs.vimPlugins; [
      nui-nvim
      plenary-nvim
      dressing-nvim
      nvim-web-devicons
      {
        plugin = avante-nvim;
        type = "lua";
        config = builtins.readFile ./neovim/plugins/avante-config.lua;
      }
    ];
  };
}
```

2. Run neovim and check health status:

```viml
:checkhealth avante
```

## Current Behavior

Plugin fails to load with error:

```
Error detected while processing /home/niyor/.config/nvim/init.lua:
E5113: Error while calling lua chunk: module 'nui' not found
```
Health check shows missing dependencies despite them being installed:

```
avante.nvim ~
- ERROR Missing required plugin: MunifTanjim/nui.nvim
- ERROR Missing required plugin: nvim-lua/plenary.nvim
- ERROR Missing required plugin: stevearc/dressing.nvim
```

## Expected Behavior

Plugin should find its dependencies and load successfully
Health check should show all dependencies as present

## Investigation Details

Dependencies are properly declared in the package:

```nix
  dependencies = with self; [
  dressing-nvim
  nui-nvim
  nvim-treesitter
  plenary-nvim
];
```

Dependencies are present in nix store:
``` bash
ls -la /nix/store/zix9gqcdk1ziwqhiv003mb10n0f113c8-vimplugin-lua5.1-nui.nvim-0.3.0-1-unstable-2024-09-15/
```
Shows nui.nvim installed with proper structure.

## Attempted workarounds (none successful):

Manually adding dependencies to lua package path
Modifying neovim's runtimepath
Changing load order of plugins

## System Information

NixOS version: NixOS 25.05 (unstable)

Additional Notes
The issue appears to be in how the package's dependencies are being linked or made available to the plugin. The standard dependency declaration in the package definition isn't sufficient for the plugin to locate its required modules.
Possible Fix Direction
The package definition might need to be modified to ensure proper runtime path setup for the dependencies, similar to how other Neovim plugins with Lua dependencies are handled in nixpkgs.

## Notify maintainers

@ttrei 
@aarnphm 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ttrei** [comment]
I suspect the issue is in the `avante` healthcheck.

The check uses the `package.loaded` table to search for required plugin names:
https://github.com/yetone/avante.nvim/blob/4464b7f4ae26254cd506a354284a02129941e244/lua/avante/health.lua#L10-L23
https://github.com/yetone/avante.nvim/blob/4464b7f4ae26254cd506a354284a02129941e244/lua/avante/utils/init.lua#L28-L32

For me `:lua print(vim.inspect(package.loaded, { depth = 1 }))` shows some entries from all the required packages. I guess it indicates that they are actually loaded.
But the table doesn't contain entries with the exact names expected by `avante`.

**Comment by ttrei** [comment]
I cannot reproduce this:
```
Error detected while processing /home/niyor/.config/nvim/init.lua:
E5113: Error while calling lua chunk: module 'nui' not found
```

**Comment by ttrei** [comment]
btw, @nbCloud91, i'm pretty sure you don't have to specify the required dependencies in your config (`nui-nvim`, `plenary-nvim`, `dressing-nvim`).

**Comment by nbCloud91** [comment]
Thanks, that seems to be the case. Oh and that nui error detected was
because I was trying to require 'nui' needlessly.
