### ISSUE TITLE
Build failure: nixos/master after dab3496fa266e098d512accda47f2a80de40be73

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#362979]
## Steps To Reproduce

nixos-rebuild from nixos/master

## Build log

```
error:
       … while calling the 'head' builtin
         at /nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/lib/attrsets.nix:1574:11:
         1573|         || pred here (elemAt values 1) (head values) then
         1574|           head values
             |           ^
         1575|         else

       … while evaluating the attribute 'value'
         at /nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/lib/modules.nix:846:9:
          845|     in warnDeprecation opt //
          846|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          847|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `system.systemBuilderArgs':

       … while evaluating definitions from `/nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/nixos/modules/system/activation/activatable-system.nix':

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating definitions from `/nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating definitions from `/nix/store/cg1hv5zmplvj9bclk8h91ikrph4shaff-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc.dbus-1.source':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: gnome2.glib has been removed, please use top-level glib
```

## Metadata

❯ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.02 MiB download, 0.06 MiB unpacked):
  /nix/store/m1p78gqlc0pw3sdbz3rdhklzm0g26g96-stdenv-linux
copying path '/nix/store/m1p78gqlc0pw3sdbz3rdhklzm0g26g96-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.3, NixOS, 25.05 (Warbler), 25.05.20241207.4fbf61a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.2`
 - channels(root): `""`
 - nixpkgs: `/nix/store/whm3kz1s6vrysjz58aw92d4b4aqkzzja-source`

## Notify maintainers

@jtojnar @maralorn @sternenseemann 
#360908

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jtojnar** [comment]
Thanks for reporting. I guess https://github.com/NixOS/nixpkgs/pull/362985 should fix it.

**Comment by spiage** [comment]
@jtojnar 
I can confirm, it is correct fix
Version 23796 -> 23797:
  nixos-system-a7: 25.05.20241207.4fbf61a → 25.05.20241208.16c246b
