### ISSUE TITLE
steam: tray icon not visible on 24.11 (sway/waybar)

### ISSUE THREAD

**Issue by willat8** [NixOS/nixpkgs#363000]
## Describe the bug

I'm not seeing the tray icon anymore in sway/waybar on nixos 24.11. Was working on 24.05.

## Steps To Reproduce

With steam enabled like

```nix
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
    "steam-run"
    "steam-unwrapped"
  ];
  programs.steam.enable = true;
```

and sway enabled like

```nix
  programs.sway = {
    enable = true;
    wrapperFeatures.gtk = true;
    extraPackages = with pkgs; [
      waybar
...
```

starting Steam no longer displays the tray icon.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.710486.4dc2fc4e62db`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@Atemu

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
cc @K900 

Does it show in KDE?

Note that I don't actually use any bars.

**Comment by K900** [comment]
It does for me, yes.

**Comment by Atemu** [comment]
I'm also pretty sure it worked for me the one time I tried KDE.

@willat8 could you try another bar or at least show logs?

I don't know enough about how bars work in Linux to debug this though.

**Comment by willat8** [comment]
Ok, nothing to do with Steam after all (sorry). For others who might encounter this, #340874 now includes a systemd user unit if you have `programs.waybar.enable = true;`, like I had. But with sway it seems the proper way to launch waybar is still via `bar { swaybar_command waybar }`. The bar launched by the user unit isn't hooked up to the dbus session correctly (because it's not started by sway which is started with `dbus-run-session`). I assume this is why Steam isn't able to show the tray icon.

Solution for me was to remove `programs.waybar.enable = true;` to prevent the user unit from being installed, and revert back to launching with `bar { swaybar_command waybar }` in `~/.config/sway/config`.

**Comment by Atemu** [comment]
This would also be fixed if you used e.g. UWSM to launch your desktop in a way that is properly integrated w.r.t. user units.
