### ISSUE TITLE
Linux headers with hard-coded version

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#36319]
We have the following in `all-packages.nix`:

```
  inherit (callPackages ../os-specific/linux/kernel-headers { })
    linuxHeaders;
```

In there, we find that we have a hard-coded version of the kernel headers (currently 4.15).
Why would the kernel headers not be exposed through the used kernel?
Do people with a 4.9 kernel really want 4.15 kernel headers when developing?
What am I missing? :)

**Comment by vcunat** [comment]
Reopen if you think there's something actionable.
