### ISSUE TITLE
nix-serve doesn't work with nix 2.0

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#36321]
## Issue description

I've been using nix-serve (via configuring `services.nix-serve` in `configuration.nix`) to allow my laptop to pull packages I've built on my desktop.

After updating the nixos-unstable channel this morning and getting the release of nix 2.0, I noticed that nix-serve was consuming a lot of my CPU.

By running `journalctl -u nix-serve.service --boot` I see many thousands of messages like:

```
Mar 05 12:56:58 alyamar nix-serve[4123]: Error while loading /nix/store/5407lxlsxs6ffb1y9qp0v7z3wplg36gd-nix-serve-0.2-7e09caa/libexec/nix-serve/nix-serve.psgi: Can't locate Nix/Config.pm in @INC (you may need to install the Nix::Config module) (@INC contains: <<<huge list of paths omitted>>>) at at /nix/store/5407lxlsxs6ffb1y9qp0v7z3wplg36gd-nix-serve-0.2-7e09caa/libexec/nix-serve/nix-serve.psgi line 2.
```

I think the CPU usage is nix-serve constantly being started by systemd and immediately crashing. (I was getting weirdly inconsistent CPU usage with both gnome-system-monitor and top agreeing that my system was under a fair bit of load overall, but only top showing some usage from nix-serve; presumably  that's because no individual process was living long enough to consume many resources as far as gnome was concerned, but many thousands of them were being lumped together more effectively by top?)

I believe the `Nix::*` perl modules were previously provided by the derivation for nix itself, but they've been removed from nix as of version 2.0. Seems like `nix-serve` needs to be rewritten for 2.0?

If that's not something that can be done immediately, we should probably do something about the broken service burning CPU in the background.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.23, NixOS, 18.03pre130719.a66ce38acea (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130719.a66ce38acea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by volth** [comment]
```buildInputs``` should contain ```nix.perl-bindings```, not only ```nix``` (as for Nix1)

**Comment by cumber** [comment]
Oh great, I missed the separate perl-bindings derivation, was worried the perl support was just gone.

The 5s respawn delay looks like a good change.
