### ISSUE TITLE
latex: can't find cleveref.sty even though kpsewhich finds it

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#36325]
## Issue description

I am trying to write some latex in neovim with vimtex. 
https://github.com/lervag/vimtex/issues/1058

I have `texlive.combine ( cleveref )` installed through home manager
```
  texliveEnv = pkgs.texlive.combine {
    # tabularx is not available
    inherit (pkgs.texlive) scheme-small cleveref latexmk bibtex algorithms cm-super
    csvsimple subfigure  glossaries;
   };

  home.file.".latexmkrc".text =  ''
    $bibtex="${texliveEnv}/bin/bibtex"
    '';

 ... in my .config/nvim/init.vim generator
        let g:vimtex_compiler_latexmk.executable='${texliveEnv}/bin/latexmk'

```
In my document I have` \usepackage[]{cleveref}` yet running latexmk doesnt find cleveref.sty even though `/nix/store/y6bn4fly4w71w7nhhnsmsb6qgfmrm7hl-texlive-combined-2017/bin/kpsewhich cleveref.sty` finds it in `/nix/store/y6bn4fly4w71w7nhhnsmsb6qgfmrm7hl-texlive-combined-2017/share/texmf/tex/latex/cleveref/cleveref.sty`. On debian fixing kpsewhich used to fix all my tex problems but here kpsewhich works and the rest not which puzzles me a bit.

Lord @vcunat, tex master between the tex masters, any idea :) ?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.4, NixOS, 18.03.git.56ed054 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0pre5968_a6c0b773`
 - channels(teto): `"nixos-17.09.3047.8bce347f02f, nixos-unstable-18.03pre129076.831ef4756e3"`
 - channels(root): `"nixos-18.03pre127921.9b25b9347d9, nixos-unstable-18.03pre127921.9b25b9347d9"`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by vcunat** [comment]
And `latexmk` comes from this `texliveEnv`, right?  It can't be some other instance, by any chance?

**Comment by teto** [comment]
I thought of that too but the paths given by :VimtexInfo match, I have no latex/latexmk in PATH either.
```
  compiler: latexmk
    backend: nvim
    latexmk executable: /nix/store/y6bn4fly4w71w7nhhnsmsb6qgfmrm7hl-texlive-combined-2017/bin/latexmk
    output: /tmp/nvimgAIfnC/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
```

**Comment by teto** [comment]
arf it seems to work now. I haven't touched anything though :s

**Comment by teto** [comment]
Had a similar problem with another package. I think vimtex or latex maintains some kind of cache, so it was running with a latexmk from an old generation. Once I do :VimtexClean, it seems to work as expected. Sorry for the trouble.
