### ISSUE TITLE
Ollama service missing device for cuda compatibilit on wsl-nixos

### ISSUE THREAD

**Issue by cfhammill** [NixOS/nixpkgs#363357]
## Describe the bug

On wsl-nixos adding 

```
services.ollama = {
    enable = true;
    acceleration="cuda";
}
```

to configuration.nix results in an ollama service that fails to detect the gpu and does cpu only inference. Even after setting the recommended 

```
LD_LIBRARY_PATH = "/usr/lib/wsl/lib"
```

to the module's environment variables.

However, the ollama package run from a shell could detect and use the gpu. I determined this was due to the device allow list in the systemd unit and corrected it by setting

```
systemd.services.ollama.serviceConfig.DeviceAllow = lib.mkForce  [
            "/dev/dxg"
            # the rest of the allowlist from the service definition
          ];
```

which could be added to https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/ollama.nix#L217-L226

## Steps To Reproduce

1. Be on wsl-nixos
2. add
```
services.ollama = {
    enable = true;
    acceleration="cuda";
    loadModels=["llama3.1:8b"];
    environmentVariables={
      LD_LIBRARY_PATH = "/usr/lib/wsl/lib";
    };
};
```
to configuration.nix
3. watch `journalctl -u ollama --follow` where it claims it fails to detect the gpu
4. Try to run inference, observe it is slow
5. Add the systemd stanza above and see that it now detects the gpu

## Expected behavior

The service should use the gpu if hardware acceleration is enabled. Adding an additional wsl option to patch the device list (and maybe add the ld_library_path) would be acceptable. Or at least exposing an `extraDevices` options would be helpful.

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.167.4-microsoft-standard-WSL2, NixOS, 24.11 (Vicuna), 24.11.709933.c71ad5c34d51`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager-24.05.tar.gz, nixos-24.11, nixos-24.11-24.11, nixos-wsl"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Notify maintainers

@abysssol @onny

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
@mweinelt You seem to understand systemd's sandboxing pretty well. As far as you know, is the suggested fix (adding `"/dev/dxg"` to the ollama service's `DeviceAllow` list) a good idea, or could it cause unexpected issues? I don't really understand this.

**Comment by mweinelt** [comment]
Unlikely to cause issues. If added should have a comment, that this is necessary for running under WSL.
