### ISSUE TITLE
`nix-repl` is incompatible with nix 2.0

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#36331]
## Issue description

When having `nix-repl` installed in the system, updating nixos unstable fails because the package does not build.

Maybe we should print a proper error message from the `nix-repl` package for this.

### Steps to reproduce

Have `nix-repl` in `configuration.nix` and switching to latest unstable channel.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.19, NixOS, 18.03pre127921.9b25b9347d9 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre130719.a66ce38acea"`
 - channels(m): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthiasbeyer** [comment]
Seems to be fixed already.

**Comment by vcunat** [comment]
If you want nix-2.0, you probably want to use `nix repl` instead of `nix-repl`.

**Comment by matthiasbeyer** [comment]
I know. I had `nix-repl` installed before and the update failed because of it. That's why I reported this issue.

**Comment by vcunat** [comment]
I understand you now.  6fa864ed7fb
