### ISSUE TITLE
Package request: Pissandshittium Browser

### ISSUE THREAD

**Issue by BlueFox1616** [NixOS/nixpkgs#363362]
## Project description

A Browser that doesn't care
At Pissandshittium, we don't care how you use your browser. Nor do we care about anything in this browser. We're adding whatever the FUCK we want to the browser and no one can stop it.

## Metadata

* homepage URL: https://pissandshittium.org/
* source URL: https://github.com/Pissandshittium/pissandshittium
* license: unknown
* platforms: windows and linux but not packaged

---

Note for maintainers: Please tag this issue in your PR.

---

**Comment by SigmaSquadron** [comment]
Just what Hydra needs; another chromium build!

Since this is a joke browser, I'm not sure we should be expending builder resources on this.

**Comment by dotlambda** [comment]
We're not packaging a browser that hasn't seen a commit in a year.
