### ISSUE TITLE
NixOS manual list of configuration options might be nice as a tree

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#3633]
It's a massive list and has a natural hierarchical structure to it. Perhaps letting us collapse/expand it by default would make it easier to browse available settings.

**Comment by Profpatsch** [comment]
I suggest we close this until someone steps up and provides a good minimal working design implementation. @domenkozar

**Comment by zimbatm** [comment]
Closing because there is no clear actionable.
