### ISSUE TITLE
darwin: installing tmsu fails because of fuse buildInput

### ISSUE THREAD

**Issue by efx** [NixOS/nixpkgs#36346]
## Issue description
I cannot install tmsu on macOS using `nix-env -iA latest.tmsu`:
```sh
installing 'tmsu-0.7.0'
error: Package ‘fuse-2.9.7’ in /nix/store/p0ww35zx7jacxpsly5dxrz8r547krxsk-latest/latest/pkgs/os-specific/linux/fuse/common.nix:77 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```
I'd guess because `buildInputs` specifies fuse, while `platforms` indicates `all`:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/tmsu/default.nix#L59

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.03pre129212.098c7f3d945"`
 - channels(efx): `"nixpkgs-latest, latest"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by matthewbauer** [comment]
So we don’t have osxfuse packaged yet. This gets difficult because we don’t have a way to install kernel drivers yet.

@lnl7

**Comment by LnL7** [comment]
I have no idea how much work it would be to package [osxfuse](http://osxfuse.github.io/) or how useful the result is in practice.

**Comment by efx** [comment]
Interesting. I propose we modify platforms to be linux specific then.
