### ISSUE TITLE
Please update nvidiabl package to use madsherlock/nvidiabl fork that adds support for Kernels >= 4.0.0

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#36356]
## Issue description

The [`nvidiabl`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nvidiabl/default.nix) package points to guillaumezin/nvidiabl that is not maintained any more.

However there is a fork with an up-to-date driver that supports kernels >= 4.0.0 at https://github.com/madsherlock/nvidiabl

Would it be possible to update the nix package to use that repository?

Thanks!

### Steps to reproduce

N/A

## Technical details

```shell
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 17.09.3109.48a76ca6f57 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3109.48a76ca6f57"`
 - channels(user): `"unstable-18.03pre129189.c2fbd472a4e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by stefano-m** [comment]
Also mentioned in #35444

**Comment by abbradar** [comment]
In description of https://github.com/madsherlock/nvidiabl:

> /!\ Please note that I don't maintain this repository anymore, please have a look at forked projects. /!\

Can you recommend another repository?

**Comment by stefano-m** [comment]
@abbradar I think that that is just the original readme, if you look at a couple of lines above, it reads:

```
Original README from guillaumezin/nvidiabl below:
========================

/!\ Please note that I don't maintain this repository anymore, please have a look at forked projects. /!\
```

If you look at the repository, the latest activity was in September 2017:

https://github.com/madsherlock/nvidiabl/commits/master

Thanks

**Comment by yorickvP** [comment]
He's not merging my pull-request though. You can use https://github.com/yorickvp/nvidiabl, I use this myself.
