### ISSUE TITLE
Cannot install pythonPackages.credstash from nixos-unstable

### ISSUE THREAD

**Issue by lbodor** [NixOS/nixpkgs#36355]
## Issue description

Error: Could not find a version that satisfies the requirement cryptography<2.1,>=1.5 (from credstash==1.14.0)

### Steps to reproduce

`nix-env -iA nixos.pythonPackages.credstash`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.81, NixOS, 18.03pre127921.9b25b9347d9 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre130719.a66ce38acea"`
 - channels(lbodor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FliegendeWurst** [comment]
Build works on 21.11 and most likely unstable too.
