### ISSUE TITLE
package openstackclient-full should include pysocks

### ISSUE THREAD

**Issue by nipsy** [NixOS/nixpkgs#363644]
## Describe the bug

Since I'm apparently unable to divine the correct incantation to do this on my own as an overlay:

https://discourse.nixos.org/t/having-trouble-overriding-python-dependencies/57104

I'm requesting that the pysocks module be included in the openstackclient-full package to allow for working SOCKS proxy support while using openstackclient-full.

## Steps To Reproduce

1. Install package openstackclient-full.
2. `export ALL_PROXY=socks5h://localhost:8081`
3. Run any openstack command and receive the following error:

```
% openstack token issue
Failed to discover available identity versions when contacting https://${redacted_host}/v3. Attempting to parse version from URL.
Unexpected exception for https://${redacted_host}/v3/auth/tokens: Missing dependencies for SOCKS support.
```

## Expected behavior

SOCKS support should be available and working.

## Metadata

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241205.d0797a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source`
```

## Notify maintainers

@SuperSandro2000 @anthonyroussel @Vinetos

**Comment by SuperSandro2000** [comment]
This shows up nowhere inside the openstack projects https://github.com/search?q=org%3Aopenstack%20pysocks%20&type=code

Where is this coming from?

**Comment by nipsy** [comment]
It's not an OpenStack specific project.  It's simply https://pypi.org/project/PySocks/.

**Comment by SuperSandro2000** [comment]
Yeah, but we should know from where it is specifically coming and it is not directly referenced in openstack code but request which openstack uses.

**Comment by SuperSandro2000** [comment]
#363651

**Comment by nipsy** [comment]
Oh, I see.  Does that affect how the library is defined?  Is that why my overlay isn't working, because I should be doing that overlay against the requests package instead of the openstackclient-full package?

**Comment by nipsy** [comment]
Yep, PR works great!  Thanks for all your work and input.
