### ISSUE TITLE
matplotlib fails to install for python27 due to collision

### ISSUE THREAD

**Issue by enolan** [NixOS/nixpkgs#36368]
## Issue description

This is the same as #34223, but the fix there only applies to Python versions older than 3.3. 

### Steps to reproduce

I have added unstable as a second channel. If there's a cleaner way to do this let me know.

`
nix-shell -I nixpkgs=/nix/var/nix/profiles/per-user/enolan/channels/unstable -p 'python27.withPackages(ps: [ps.matplotlib])'`

Output is:
```
these derivations will be built:
  /nix/store/231dhrlssff3vigw8sqias3b33dwavd9-python-2.7.14-env.drv
building path(s) ‘/nix/store/c9lwjlqn07wm1x8phxsg4dqplvza68zk-python-2.7.14-env’
collision between `/nix/store/hwkkqrf5zv1y1bn4wxbndycbwh6daq3d-python2.7-backports.ssl_match_hostname-3.5.0.1/lib/python2.7/site-packages/backports/__init__.py' and `/nix/store/0s8fgwwr33wz9kws4xgpmilzhady4azf-python2.7-backports.functools_lru_cache-1.5/lib/python2.7/site-packages/backports/__init__.py'
builder for ‘/nix/store/231dhrlssff3vigw8sqias3b33dwavd9-python-2.7.14-env.drv’ failed with exit code 25
error: build of ‘/nix/store/231dhrlssff3vigw8sqias3b33dwavd9-python-2.7.14-env.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

It works correctly on 17.09.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(enolan): `"unstable-18.03pre130932.cc4677c36ee, nixos-17.09.3129.1dcd022f01b"`
 - channels(root): `"nixos-17.09.3129.1dcd022f01b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FRidh** [comment]
Correct. It works with Python 3 because of PEP 420. For 2.7 this error is expected behavior. The solution is in the manual:
> Python 2 namespace packages may provide __init__.py that collide. In that case python.buildEnv should be used with ignoreCollisions = true.

**Comment by enolan** [comment]
OK thanks. Is there a reason `ignoreCollisions = true` can't be the default for python versions < 2?

**Comment by FRidh** [comment]
There are valid reasons for not ignoring collisions, such as preventing having duplicate packages or other files in a single environment.

**Comment by ulysses4ever** [comment]
Is it possible to post a simple but complete workaround here? On unstable, I'm doing
```
nix-shell -p 'python2.withPackages (p: [p.matplotlib])'
```
and it fails with collisions. Where do I put `ignoreCollisions = true` to make it work?

**Comment by FRidh** [comment]
See `15.21.2.3.5. python.buildEnv function` in https://nixos.org/manual/nixpkgs/stable/.

**Comment by ulysses4ever** [comment]
Thanks.

I ended up creating a `shell.nix` with the following contents:
```
with import <nixpkgs> {};

(python2.buildEnv.override {
  extraLibs = with python2Packages; [ matplotlib ];
  ignoreCollisions = true;
}).env
```
and then running `nix-shell` in the same directory as the file.
