### ISSUE TITLE
bug(wyoming-faster-whisper): ValueError: This CTranslate2 package was not compiled with CUDA support

### ISSUE THREAD

**Issue by peperunas** [NixOS/nixpkgs#363601]
## Describe the bug

As per title, `wyoming-faster-whisper` fails when the device is set to `cuda`. I believe in the dependencies that pull `CTraslate` we need to add support to CUDA devices.

## Steps To Reproduce

```
    faster-whisper = {
      servers."home" = {
        enable = true;
        uri = "tcp://127.0.0.1:${toString whisperPort}";
        model = "large-v3";
        device = "cuda";
        language = "en";
      };
    };
```

## Additional context

```
Dec 09 14:50:29 architect wyoming-faster-whisper[1253525]:   File "/nix/store/12my1jkd4gdmaipcq7qgfmn68frp0vws-python3.12-faster-whisper-unstable-2024-07-26/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 145, in __init__
Dec 09 14:50:29 architect wyoming-faster-whisper[1253525]:     self.model = ctranslate2.models.Whisper(
Dec 09 14:50:29 architect wyoming-faster-whisper[1253525]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 09 14:50:29 architect wyoming-faster-whisper[1253525]: ValueError: This CTranslate2 package was not compiled with CUDA support
Dec 09 14:50:29 architect systemd[1]: wyoming-faster-whisper-home.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 14:50:29 architect systemd[1]: wyoming-faster-whisper-home.service: Failed with result 'exit-code'.
Dec 09 14:50:29 architect systemd[1]: wyoming-faster-whisper-home.service: Consumed 9.969s CPU time, 3G memory peak, 2.7G written to disk, 2.4G incoming IP traffic, 16.9M outgoing IP traffic.
```

## Notify maintainers

@happysalada 
@mweinelt 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mweinelt** [comment]
Likely an instance of https://github.com/NixOS/nixpkgs/issues/286028. Feel free to comment if loading nvidia_uvm doesn't fix the situation.

**Comment by peperunas** [comment]
`nvidia_uvm` is indeed loaded:

```
nvidia_drm            139264  46
nvidia_modeset       1671168  25 nvidia_drm
nvidia_uvm           3837952  6
nvidia              77504512  850 nvidia_uvm,nvidia_modeset
video                  77824  2 asus_wmi,nvidia_modeset
backlight              28672  3 video,asus_wmi,nvidia_modeset
```

**Comment by mweinelt** [comment]
Does it work when you restart wyoming-faster-whisper now?

**Comment by peperunas** [comment]
It was already loaded and no, even restarting does not fix it unfortunately.

**Comment by mweinelt** [comment]
> ValueError: This CTranslate2 package was not compiled with CUDA support

Sorry, I completely misread the error message. The wyoming-faster-whisper module only configures faster-whisper and expects that you enable `nixpkgs.config.cudaSupport` in your config.

Make sure to set up the nix-community cache to get the unfree cuda packages not available on cache.nixos.org though.

https://discourse.nixos.org/t/cuda-cache-for-nix-community/56038

**Comment by peperunas** [comment]
Hello Martin,

Thanks for the heads-up! I always passed `cudaSupport` on a per-package basis because rebuilding my entire system was either very long or some package failed building. I will try now with the binary cache and update on the results.

**Comment by peperunas** [comment]
Worked by rebuilding ctranslate2 to use CUDA and CuDNN.

This issue can be closed.

**Comment by gshpychka** [comment]
For posterity, you can use this overlay to enable CUDA and CuDNN for ctranslate2. `wyoming-faster-whisper` works with this applied:

```nix
nixpkgs.overlays = [
  (self: super: {
    ctranslate2 = super.ctranslate2.override {
      withCUDA = true;
      withCuDNN = true;
    };
  })
];
```
