### ISSUE TITLE
Package request: SASM

### ISSUE THREAD

**Issue by funkybooboo** [NixOS/nixpkgs#363707]
## Project description

SASM is a popular IDE for many types of assembly programming languages

## Metadata

* homepage [URL](https://dman95.github.io/SASM/english.html):
* source [URL](https://github.com/Dman95/SASM):
* license: gpl2+
* platforms: unix, linux, darwin, ...

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Please fill in the package name in the title, as well as the homepage & source URLs

**Comment by FliegendeWurst** [comment]
> Please fill in the package name in the title, as well as the homepage & source URLs

The URLs are present, they are formatted as markdown links.

**Comment by funkybooboo** [comment]
Sorry about missing the issue title. Thanks FliegendeWurst for fixing those pieces of information!

**Comment by funkybooboo** [comment]
I tried making the derivation myself, even got close to getting it built, but got confused with all the qt5 dependencies. Guess I'll leave it up to the pros, hahah. 

Thank you to whoever makes the derivation!

**Comment by funkybooboo** [comment]
Looks like this has already been requested.

https://github.com/NixOS/nixpkgs/issues/208858
