### ISSUE TITLE
Jupyter Notebook: no module named ipykernel_launcher

### ISSUE THREAD

**Issue by jwptrs** [NixOS/nixpkgs#36370]
## Issue description
[I 10:16:12.608 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
/nix/store/p1bp0kpmxi7nzrla7n7c4waqic0a2myk-python3-3.6.4/bin/python3.6m: No module named ipykernel_launcher

### Steps to reproduce
Installed Jupyter notebook, which starts normally. Executing Python code from inside the notebook however doesn't work.
Installed packages (from python36Packages):
- jupyter_core
- jupyter
- ipython
- ipykernel
- notebook

Issue both in stable and unstable channels.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-unstable-18.03pre130719.a66ce38acea, nixos-17.09.3129.1dcd022f01b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jwptrs** [comment]
Retried succesfully with the instructions from https://nixos.org/nixpkgs/manual/#python (section 9.11.1.1.2. Installing Python and packages).

**Comment by akavel** [comment]
@jwptrs What's the exact incantation you used to install and run jupyter notebook correctly? In the section you linked, I see some commands for building environments, but still not sure how to run jupyter... :/
