### ISSUE TITLE
Package request: PearAI

### ISSUE THREAD

**Issue by InSelfControll** [NixOS/nixpkgs#363781]
## Project description

PearAI is a code editor that have AI builtin.
## Metadata

* homepage URL: https://trypear.ai/
* source URL: https://github.com/trypear/pearai-app
* license: MIT license
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].
+1
[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nang-dev** [comment]
+1!

**Comment by pluiedev** [comment]
Duplicate of #355773
