### ISSUE TITLE
Package request: lla

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#363730]
## Project description

lla: A Modern Alternative to ls

## Metadata

* homepage URL: https://github.com/triyanox/lla
* source URL: https://github.com/triyanox/lla
* license: mit
* platforms: unix, linux, darwin

Also see discussion here: https://www.reddit.com/r/rust/comments/1h9vfbh/lla_an_ls_replacement_with_modern_features_rich/

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Already exists (I just packaged it!)
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ll/lla/package.nix#L40
