### ISSUE TITLE
kalarm not available

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#36376]
## Issue description
I installed

`kdeApplications.kalarmcal` by putting it in configuration.nix with the expectation of getting kalarm (or something similar) on PATH. 

That didn't happen. 

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Synthetica9** [comment]
Can confirm on my system.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - channels(synthetica): `"nixos-18.03pre119110.2ddcdcce26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
What makes you think there should be executables? `kalarmcal` is a library: https://packages.ubuntu.com/search?keywords=kalarmcal&searchon=names&suite=artful&section=all

**Comment by coretemp** [comment]
Thank you, in that case this becomes a package request. I had thought that KDE (or however it is called) was packaged completely already in NixOS.

**Comment by rittelle** [comment]
KDE applications are packaged partially (with a comment indicating how to package the rest if needed).
I was adding another package anyway, so I looked into KAlarm.
KAlarm depeds on `KF5KdepimDBusInterfaces` which I couldn't find in nixpkg and I'm not too familiar with the KDE frameworks.
If someone helps me with this issue I'll make a PR for KAlarm.

**Comment by rittelle** [comment]
As promised (although a bit later than intended): #38953

**Comment by Phreedom** [comment]
As of now, KAlarm is packaged and works
