### ISSUE TITLE
Cannot upgrade Emacs' nix-mode via emacsWithPackages

### ISSUE THREAD

**Issue by tazjin** [NixOS/nixpkgs#36372]
## Issue description

Adding a derivation for the `nix-mode` emacs package from [this repository](https://github.com/NixOS/nix-mode) or using the current package from `emacsPackagesNg.melpaPackages` and using it in an `emacsWithPackages` will still cause emacs to load an old version of `nix-mode`.

The reason for this is that somehow the derivation for Nix itself ends up containing a `nix-mode.el`, which is linked into `/run/current-system/`:

```
/r/c/s/s/e/site-lisp $ pwd
/run/current-system/sw/share/emacs/site-lisp
/r/c/s/s/e/site-lisp $ readlink nix-mode.el 
/nix/store/ny62xjh4jysdnw0pfpk52d1crvrr92vd-nix-1.11.16/share/emacs/site-lisp/nix-mode.el
```

As this folder comes first in the `load-path` configured in emacs, it will never load `nix-mode` from the derivation it's supposed to use it from.

I took a cursory look at how & why this folder is even set up, but couldn't quite figure out why this Lisp file from the nix derivation is treated differently than all other derivations containing Emacs code. 

Investigation continues & I have to find a workaround, but if anyone can shed some light on it that would be appreciated.

## Technical details

Derivation is [here](https://github.com/tazjin/nixos-config/commit/92ae9eed7a0a75a0e403227dbe2b436a20c231b3).

```
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.82, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3129.1dcd022f01b, nixos-unstable-18.03pre130719.a66ce38acea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by tazjin** [comment]
My workaround looks [like this](https://github.com/tazjin/nixos-config/commit/602b8b4ef06341fad4b60bc946d7406cafb321f8) and is basically removing the nix-mode files from the Nix derivation.

I'm not sure what the actual solution to this should be - there seem to be two competing ways for Emacs packages to be installed, one that involves building them in isolation and adding them to Emacs' `load-path` and one that results in them being linked into the system-wide `site-lisp` folder. The latter seems to only be used by `password-store` and `nix`.

Either way it is probably sensible to remove that old nix-mode from the Nix derivation.

**Comment by matthewbauer** [comment]
> Either way it is probably sensible to remove that old nix-mode from the Nix derivation

This is happening in Nix 2.0. It's kind of a mess now but your workaround seems good enough if you still need Nix 1.11.

**Comment by matthewbauer** [comment]
On the unstable channel, "nixStable" no longer has nix-mode.
