### ISSUE TITLE
Update request: qt 6.8.0 → 6.8.1

### ISSUE THREAD

**Issue by wineee** [NixOS/nixpkgs#363878]
## Package Information

- Package name: qt 6
- Latest released version: 6.8.1
- Current version on the unstable channel: 6.8.0
- Current version on the stable/release channel:  6.8.0

https://www.qt.io/blog/qt-6.8.1-released

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@NixOS/qt-kde @NickCao @K900 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Already in staging-next.
