### ISSUE TITLE
networking.firewall.enable = false kills NAT

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#36397]
## Issue description

```networking.firewall.enable = false;``` removes NAT rules from iptables.

This might be the feature, but it would be nice to have an option which disables the firewall (in the sense of "list of ports allowed to connect") only.

**Comment by danbst** [comment]
Yeah, in this sense it is better to rename `networking.firewall` to `networking.iptables`

But there exist also `networking.nat.*` set of options, which works even if firewall disabled

https://github.com/NixOS/nixpkgs/blob/release-17.09/nixos/modules/services/networking/nat.nix#L180-L195

**Comment by volth** [comment]
ah, so the problem is already addressed.
perhaps my issue was only in "setting ```networking.firewall.enable = false;``` followed by nixos-rebuild kills nat" because of some transition effect.
