### ISSUE TITLE
xen: dom0 boots with Linux 4.9 but not with 4.14

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#36398]
## Issue description

I use a qemu vm with xen (default version 4.5)  for testing xen. 
On current master 6b97544481160d8552e24e3ce31dfb13942712d0 , dom0 boots fine with kernel 4.9.86 (linuxPackages_4_9). 
With kernel 4.14 (current default), xen hypervisor starts but the system freezes with a black screen when booting dom0. No visible error messages, found nothing in the logs.

Edit: kernel 4.14 without xen works fine as well.

### Steps to reproduce

1. Create minimal qemu VM in virt-manager with `boot.kernelPackages = linuxPackages_4_9` and 
`virtualization.xen.enable = true;` Works fine.
2. Switch to default linux kernel 4.14 by commenting `boot.kernelPackages` line. dom0 doesn't boot anymore.

## Technical details

NixOS 18.09.git.6b97544 (x86_64)

**Comment by xeji** [comment]
@oxij - any idea what causes this?

**Comment by oxij** [comment]
No idea. I would try booting it with a serial tty output (qemu can print it directly to stdout) and loud kernel debug. Maybe that would help.

**Comment by xeji** [comment]
Issue is no longer reproducible on current master or 18.03 (with Linux 4.14.26). 
Looks fine with Xen 4.8 and 4.10.
I suspect this was caused by an earlier version of Linux 4.14. Closing.
