### ISSUE TITLE
pcloud 1.14.8 does no longer run using patchelf workaround

### ISSUE THREAD

**Issue by nadir-ishiguro** [NixOS/nixpkgs#364040]
## Describe the bug

pCloud hasn't been working out of the box for a while now because of an incompatibility with current patchelf. There's been a workaround available (thanks to @Patryk27)  that worked very well until now: https://gist.github.com/zarelit/c71518fe1272703788d3b5f570ef12e9. 

After the update to [1.14.8 that was recently merged](https://github.com/NixOS/nixpkgs/pull/356202) that doesn't seem to work for me any more. 

## Steps To Reproduce

1. Update to current nixos-unstable including pcloud 1.14.8
2. Try to run pcloud using the above mentioned patchelf workaround.
3. Running `pcloud` via terminal gets me this output:
```bash
Could not start dynamically linked executable: /nix/store/2p2lpvmcy9y61mzvgvjqq7zfcxln4x84-pcloud-1.14.8/app/pcloud
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

## Expected behavior

Pcloud 1.14.8 starts as 1.14.7 did before.

## Additional context

I manually switched back to 1.14.7 and everything works fine with current nixpkgs-unstable.

## Metadata

```bash
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.3-cachyos, NixOS, 25.05 (Warbler), 25.05.20241209.a73246e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/yw6kg4rb9v8s3ypjbpspig5r81m4lr5s-source`
 ```
 
## Notify maintainers

@Patryk27 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Patryk27** [comment]
Just for clarity: I'll take a look at it tomorrow 🙂

**Comment by nadir-ishiguro** [comment]
Please, no hurry and thank you!

**Comment by MarkRijckenberg** [comment]
I have the exact same issue in NixOS 25.05....
