### ISSUE TITLE
ghc 7.8.3 from nixpkgs emits readlink and compiler warnings on OS X 10.9.4 

### ISSUE THREAD

**Issue by Debilski** [NixOS/nixpkgs#3641]
$ echo 'main = putStrLn ""' > simple.hs

    $ ghc simple.hs
    [1 of 1] Compiling Main             ( simple.hs, simple.o )

    <no location info>:
        Warning: Couldn't figure out linker information!
                 Make sure you're using GNU gcc, or clang
    Linking simple ...
    readlink: illegal option -- f
    usage: readlink [-n] [file ...]

    $ readlink $(which ghc)
    /nix/store/0fkqnmgp8pyb62mdbj5sx6cyzk4zj75i-ghc-7.8.3-wrapper/bin/ghc

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

The ghc from the binary distribution compiles this without any problems or warnings.

When installing and compiling packages with `nix-env -i`, I’m not seeing any warnings or errors related to this. Am I just using it wrong by running ghc out of nix context?

(* As per https://github.com/NixOS/nixpkgs/issues/2689 I’ve replaced the haddock executable from nixpkgs with the one from the binary distribution.)

**Comment by peti** [comment]
I'm closing this issue because it's been inactive for a couple of months. Please re-open if this problem still exists.

**Comment by Debilski** [comment]
Last time I checked, the problem still existed. Due to other problems, though, I have not been looking into nixpkgs on OS X more thoroughly in the meantime.
