### ISSUE TITLE
Can't build 18.03 GCE image on 17.09 system

### ISSUE THREAD

**Issue by YorikSar** [NixOS/nixpkgs#36417]
## Issue description

When I try to build 18.03 GCE image on 17.09 system, I seem to run into the same issue as #36268:
```
nixpkgs % NIX_PATH=nixpkgs=$PWD BUCKET_NAME=nixos-images nixos/maintainers/scripts/gce/create-gce.sh
error: assertion failed at /src/nixpkgs/pkgs/build-support/closure-info.nix:11:1
(use ‘--show-trace’ to show detailed location information)
```
When I add `--show-trace` to `nix-build` call in `nixos/maintainers/scripts/gce/create-gce.sh`, I get this:
```
nixpkgs % NIX_PATH=nixpkgs=$PWD BUCKET_NAME=nixos-images nixos/maintainers/scripts/gce/create-gce.sh
error: while evaluating the attribute ‘preVM’ of the derivation ‘google-compute-image’ at /src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating anonymous function at /src/nixpkgs/pkgs/build-support/closure-info.nix:9:1, called from /src/nixpkgs/nixos/lib/make-disk-image.nix:116:17:
assertion failed at /src/nixpkgs/pkgs/build-support/closure-info.nix:11:1
```

So the problem comes from usage of `closureInfo` in `nixos/lib/make-disk-image.nix`. I tracked its creation to commit 9802da517fe4da41d68516029b01c5c1f175b3e4 from PR #34636. I tried to revert it, but it fails again with:
```
undefined variable ‘nixos-prepare-root’ at /src/nixpkgs/nixos/modules/installer/tools/tools.nix:78:21
``` 
If I revert 0f5d5970b28c9d85e7166f85ecfa3f86064d3f25 as well and adjust size of the image (1G appears to be too small now), image builds fine.

### Steps to reproduce

* Run `nixos/maintainers/scripts/gce/create-gce.sh` with pre-2.0 nix daemon.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 17.09.git.e0ac237 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3083.87c057a9c16"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by edolstra** [comment]
Yeah, this is not supported. You need to build using Nix 2.0.

**Comment by vcunat** [comment]
Right.  Too hard to fix disk images with nix-1.x properly, most likely, and 17.09 will get unsupported in several weeks anyway.

**Comment by vcunat** [comment]
I mean, if you find a good solution...

**Comment by YorikSar** [comment]
@vcunat So... Is it ok to not be able to build latest images on current stable version of NixOS? How is this issue different from #36268?

But anyhow, it seems all we need is to somehow get `.attrs.json` content for `closureInfo` from nix-1.x externally. Can't it be done using some `nix-store` magic?

**Comment by vcunat** [comment]
It's different because the other issue was relatively easy to solve.

**Comment by vcunat** [comment]
BTW, you may use nix-2.0 on 17.09.

**Comment by YorikSar** [comment]
@vcunat Oh, right, I see. I guess there's no point in figuring out a workaround then. Is it safe to use nix-2.0 on 17.09 though? Won't there be any incompatibilities?

**Comment by vcunat** [comment]
It will upgrade the DB, but later 1.11.x can work with that schema as well.

**Comment by vcunat** [comment]
So you can roll back as usual ;-)

**Comment by YorikSar** [comment]
Cool, thanks. I've added `nix.package = pkgs.nixStable2`, works just fine for now :)
