### ISSUE TITLE
Package request: Clapgrep

### ISSUE THREAD

**Issue by Thatoo** [NixOS/nixpkgs#364193]
## Project description

Clapgrep can currently search all sorts of text files, PDFs and Office documents, with more to come.

## Metadata

* homepage URL: https://flathub.org/apps/de.leopoldluley.Clapgrep
* source URL: https://github.com/luleyleo/clapgrep
* license: gpl3
* platforms:  linux

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by genga898** [comment]
This just got merged a couple of hours ago so maybe wait for the next unstable staging then you can use it. Here is the pr #360741
