### ISSUE TITLE
whatsapp-for-mac on aarch64-darwin does not build

### ISSUE THREAD

**Issue by CheezuzCrust** [NixOS/nixpkgs#364195]
## Describe the bug

When adding the package `pkgs.whatsapp-for-mac` to your nix-darwin config, it throws an http error. I am guessing something on whatsapp's side broke the package, but I could have also just done something stupid. If someone can clear this up for me I would be grateful.

## Steps To Reproduce

1. add pkgs.whatsapp-for-mac to your aarch64-darwin config
2. run darwin-rebuild switch --flake .#whatever
3. HTTP error

## Expected behavior

I expect the program to be downloaded and installed and that I can use it.

## Screenshots
here are the short logs:

```
building the system configuration...
error: builder for '/nix/store/3flg997m0nk18jwpsp8zcn3pbj7nlq1x-WhatsApp.app.drv' failed with exit code 1;
       last 16 log lines:
       >
       > trying https://web.whatsapp.com/desktop/mac_native/release/?version=2.24.11.85&extension=zip&configuration=Release&branch=relbranch
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 500
       > Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 500
       > Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 500
       > Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 500
       > error: cannot download WhatsApp.app from any mirror
       For full logs, run 'nix log /nix/store/3flg997m0nk18jwpsp8zcn3pbj7nlq1x-WhatsApp.app.drv'.
error: 1 dependencies of derivation '/nix/store/5cyjhm9bn9hn7ymz6qwxwvxp1cc03aqj-whatsapp-for-mac-2.24.11.85.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nci4h6fyf4k8kcp76mdd5kv2f1z9j2kc-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yyia9g87n26ihzr7s24imfsjblv2siif-darwin-system-25.05.20241208.dd51f52+darwin5.a35b08d.drv' failed to build
```

## Metadata

```
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/rml4w5lj8jxsnlddmy0r1bd4389fkdh7-source`
```

## Notify maintainers

@iivusly 

---

Note for maintainers: Please tag this issue in your PR.

---

**Comment by mettavi** [comment]
I'm seeing exactly the same error on x86_64-darwin.

**Comment by mettavi** [comment]
Hi, thanks for the update, but this change has not fixed the problem on x86_64-darwin.

**Comment by cogsandsquigs** [comment]
This error still is appearing on my end (aarch64-darwin), still with an HTTP 500 error. Any progress made, or has this been dropped?

**Comment by cogsandsquigs** [comment]
I think I've figured out the issue: the current version that nixpkgs is pulling seems to be outdated or perhaps missing (version 2.24.23.82). Meanwhile, homebrew pulls a newer, working version (version 2.25.2.80). See these two URLs:

What nixpkgs pulls from: [https://web.whatsapp.com/desktop/mac_native/release/?version=2.24.23.82&extension=zip&configuration=Release&branch=relbranch](https://web.whatsapp.com/desktop/mac_native/release/?version=2.24.23.82&extension=zip&configuration=Release&branch=relbranch)
What homebrew pulls from: [https://web.whatsapp.com/desktop/mac_native/release/?version=2.25.2.80&extension=zip&configuration=Release&branch=relbranch](https://web.whatsapp.com/desktop/mac_native/release/?version=2.25.2.80&extension=zip&configuration=Release&branch=relbranch)

**Comment by ernestha** [comment]
Can confirm the error still persists - or possible has reappeared.

**Comment by yaaax** [comment]
Hi,
I’m seeing that issue too.

**Comment by Felipe-9** [comment]
Just got this issue on aarch-darwin
