### ISSUE TITLE
Update request: linux-hardened 6.12

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#364251]
## Package Information

New tag/patch for Linux 6.12 came out! https://github.com/anthraxx/linux-hardened/releases/tag/v6.12.4-hardened1

- Package name: linuxKernel.kernels.linux_hardened
- Latest released version: 6.12.4
- Current version on the unstable channel: n/a - multiple
- Current version on the stable/release channel: n/a - multiple

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@fabianhjr

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabianhjr** [comment]
Hi, will have some time on sunday to look at this request. Thanks for the ping.

**Comment by surfaceflinger** [comment]
thanks!

**Comment by fabianhjr** [comment]
Had some time, could you help test https://github.com/NixOS/nixpkgs/pull/365214?
