### ISSUE TITLE
bookstack: missing `package` option

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#364343]
## Describe the bug

The `bookstack` service module is missing the conventional `package` option, making it apparently impossible to override the package being used. This also makes it difficult to patch the package without doing so globally for the whole system (which is currently preventing me from adding a syntax highlighting option).

## Steps To Reproduce

N/A

## Expected behavior

Should have a `services.bookstack.package` option that allows overriding the package that is used, as is the case for most other service modules.

## Screenshots

N/A

## Additional context

N/A

## Metadata

Command is not working on the affected system, but this affects at least latest stable (24.11).

## Notify maintainers

@ymarkus 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Please test #364347
