### ISSUE TITLE
Error deriving texlive with bussproofs following documentation

### ISSUE THREAD

**Issue by wchresta** [NixOS/nixpkgs#36443]
## Issue description
Trying to build a shell.nix to compile TeX document with texlive and bussproofs package.
Using the documentation at https://nixos.org/nixpkgs/manual/#sec-language-texlive I tried

/cc @vcunat 

### Steps to reproduce

Using the following shell.nix
```
$ cat shell.nix 
{ pkgs ? import <nixpkgs> {} }:

with pkgs;

let myTexLive = texlive.combine {
      inherit (texlive) bussproofs;
    };
in stdenv.mkDerivation rec {
  name = "env";
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = [ myTexLive
  ];
}
```

Will give this error when trying to start nix-shell:
```
$ nix-shell
these derivations will be built:
  /nix/store/vgs7xccf5djc4jwvrfrk9rjbrh6msa63-texlive-combined-2016.drv
  /nix/store/ik6am1lg3jm3pxzafk27cvfplmyqbnnm-env.drv
building path(s) ‘/nix/store/q2yzx50rqh3nd6zg54dsf05cicqk3q5q-texlive-combined-2016’
created 2 symlinks in user environment
/nix/store/nyvvbds5vp7i8g1n4wvgk89iwyj6bg4f-stdenv/setup: line 1023: cd: /nix/store/q2yzx50rqh3nd6zg54dsf05cicqk3q5q-texlive-combined-2016/share/texmf/scripts/texlive: No such file or directory
builder for ‘/nix/store/vgs7xccf5djc4jwvrfrk9rjbrh6msa63-texlive-combined-2016.drv’ failed with exit code 1
error: build of ‘/nix/store/vgs7xccf5djc4jwvrfrk9rjbrh6msa63-texlive-combined-2016.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

## Technical details

```
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.23, NixOS, 17.09.3101.fd1d76bb1a8 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(wchresta): `""`
 - channels(root): `"nixos-17.09.3101.fd1d76bb1a8, nixos-unstable-18.03pre127921.9b25b9347d9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by 7c6f434c** [comment]
I think you need to add `scheme-small` to the list, or something. The wrapper assumes that the combination is useful, for example, contains `tex` executable…

**Comment by wchresta** [comment]
That's it - the documentation confused me and this was not obvious; thought scheme-small was an optional package. Thanks!

**Comment by 7c6f434c** [comment]
Technically, `scheme-small` is optional in the sense that `scheme-medium` supersedes it (includes all its parts).

**Comment by vcunat** [comment]
It's meant that you get one `scheme-*` and then optionally add some particular collections and/or packages.

**Comment by wchresta** [comment]
Maybe we could add this to the mentioned documentation.

**Comment by 7c6f434c** [comment]
By the time you have posted this comment, we have already started discussing this addition on IRC. Checking that the manual actually builds after an addition.
