### ISSUE TITLE
18.03 Zero Hydra Failures (generic + x86_64-linux)

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#36453]
Let's make Impala the best release so far! :car: :deer:

We have: [the main jobset](https://hydra.nixos.org/jobset/nixos/release-18.03) starting around 1.5k failures, [x86_64-darwin](https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-18.03-darwin) around 0.9k, and the newbie [aarch64-linux](https://hydra.nixos.org/jobset/nixos/release-18.03-aarch64) lagging behind near 4k.  The numbers seem large, but one package may kill very many jobs...

### Steps to repeat
- Choose some package from those that fail on Hydra.  Hurry before the good ones have been taken!
- Find a fix.  That may mean simply restricting `meta.platforms`, in case the package inherently doesn't support what it has in there ATM.
- Typically the package was broken on master already.  You can verify that on Hydra - example URL: https://hydra.nixos.org/job/nixpkgs/trunk/bash.x86_64-linux  In that case base the fix on master and request backporting in the description of the pull request.
- Ping this issue from the PR, e.g. /cc ZHF #36453.  Do this also if you have some WIP.  Alternatively you may just post a note in this issue.  If the breakage is specific to darwin #36454 or aarch64 #32326, mention the respective issue instead.

The remaining packages will be marked as broken before the release (on the failing platforms), i.e. at the end of March.  /cc @NixOS/nixpkgs-committers, but **everyone** can fix the stuff.

**Comment by NeQuissimus** [comment]
The `statsd` test passes for me: https://gist.github.com/NeQuissimus/6243db2217a3c46fb28739e62ab502af#file-test_statsd-sh

**Comment by dtzWill** [comment]
`qttools` [build failure](https://hydra.nixos.org/build/70735998/nixlog/1) blocks lots of things--looks like a /bin/sh problem or otherwise missing some easy native deps.  Seems okay on master but don't see reason why, maybe builder-specific? Anyway worth fixing that as it blocks many other packages.

Other qt-related packages similarly fail, here's `qdirstat`: https://hydra.nixos.org/build/70737278/nixlog/1 .  Builds locally, suspect that machine needs an update to use a fixed/functioning /bin/sh.

**Comment by shlevy** [comment]
@dtzwill can't take a look right now, but I'd rather use patchshebangs in patch phase to fix /bin/sh deps

**Comment by vcunat** [comment]
The two tests succeeded after some restarts.

**Comment by xeji** [comment]
libosinfo: cannot reproduce the test failure in https://hydra.nixos.org/build/70734135 . same derivation hash builds ok in sandbox on release-18.03 here.

**Comment by shlevy** [comment]
@xeji restarting build

**Comment by xeji** [comment]
@shlevy thanks, was OK now

**Comment by xeji** [comment]
libav_12: error not reproducible, please restart https://hydra.nixos.org/build/70737417

**Comment by shlevy** [comment]
@xeji This is an impurity in the build, it's depending on `/bin/sh`. Probably the fix is `patchShebangs` during `postPatch`

**Comment by xeji** [comment]
@shlevy thanks, will give it a try

**Comment by pbogdan** [comment]
Just in case it helps - qt failures are reproducible on my system (17.09.3083.87c057a9c16 (Hummingbird) using nixStable2 daemon and client) when building from the git revision Hydra attempted. They  look to be related to https://github.com/NixOS/nixpkgs/blob/6fcf691545896b278cc8e6961af5db9331656f8c/pkgs/development/libraries/qt-5/5.10/qtbase.patch#L733 which expects `command` builtin in the shell that will execute that statement. From what I gather that statement eventually gets executed via qmake in https://github.com/qt/qtbase/blob/4ba535616b8d3dfda7fbe162c6513f3008c1077a/qmake/library/qmakebuiltins.cpp#L502 and due to use of `popen` is ran via `sh -c`. On my system sandbox `sh` lacks `command` builtin. Patching nix to provide a more feature-full sandbox `sh` appears to work, so does patching the `qtbase` patch to use `bash` explicitly.

This however rises the question of how those builds can be succeeding on different builders - I assumed they would all be running 17.09 with nixUnstable and 17.09 doesn't seem to have @dtzWill's patches that provide additional features for the sandbox `sh`?

**Comment by dezgeg** [comment]
> This is an impurity in the build, it's depending on /bin/sh. Probably the fix is patchShebangs during postPatch

No. If the same builds works in Nix 1.11 but not in Nix 2.0, we should fix Nix 2.0 instead. Otherwise we have massive reproducibility problem where nearly anything from say, nixpkgs 17.09 or 18.03 can't be built anymore on Nix 2.0!

**Comment by shlevy** [comment]
@dezgeg The build works on Nix 1.11 coincidentally, if the host system has an appropriate /bin/sh. Again, depending on /bin/sh is impure. If you want to make sure old things depending on that impurity work, you have to reproduce the impurity yourself, which can be done with e.g. `sandbox-paths`.

**Comment by shlevy** [comment]
Note, also, that even if you consider this a bug it has nothing to do with nix 2.0 itself, rather with the `sh` it is configured to use.

**Comment by dezgeg** [comment]
> The build works on Nix 1.11 coincidentally

There was nothing coincidental. With Nix 1.1,1 NixOS always configured it to use bash even inside the sandbox, and had done for _several years_. 

> Note, also, that even if you consider this a bug it has nothing to do with nix 2.0 itself, r

Just because you can theoretically configure it away when building Nix, who does that? The _default_ here is what's wrong.

**Comment by shlevy** [comment]
@dezgeg There *is* no default in Nix. It's in nixpkgs. That's what you want to "fix" if it's a bug. And the NixOS sandbox configuration did nothing for people outside of NixOS, *and* it caused real problems: https://github.com/NixOS/nixpkgs/issues/1424. 

The answer is not to depend on /bin/sh in builds. I wish we didn't even include it in the sandbox, but I lost that fight already.

**Comment by dezgeg** [comment]
Actually there was a default, and it was bash: https://github.com/NixOS/nix/blob/1.11-maintenance/src/libstore/build.cc#L1925

**Comment by shlevy** [comment]
(an alternative answer would be to let stdenv determine what counts as `/bin/sh` in the sandbox).

**Comment by shlevy** [comment]
@dezgeg That default basically only made sense if building from nixpkgs (otherwise it's unlikely you'd have BASH_PATH pointing to the nix store), so again this is a question of the nixpkgs config.

**Comment by Mic92** [comment]
@shlevy @dezgeg I think this discussion should be taken to a nix issue ticket instead.

**Comment by dezgeg** [comment]
More discussion for `/bin/sh` here: https://github.com/NixOS/nixpkgs/pull/36669

**Comment by timokau** [comment]
haskellPackages.changelogged is fixed on master but still needs to be backported to 18.03

**Comment by Ma27** [comment]
FYI I started fixing `aspino`, however this seems to be a bit more difficult as they patch another lib on upstream and their patches don't apply properly against the library versions we use at nixpkgs. Currently evaluating possible solutions (just spamming here to avoid duplicated work on this^^)

**Comment by peti** [comment]
All Haskell related evaluation and/or build errors are fixed. The only failing build that remains is `ihaskell`, which depends on some `qt` packages that don't compile: https://hydra.nixos.org/build/70876188. I don't know what do to about those, unfortunately.

**Comment by vcunat** [comment]
Great progress in the first week :tada:  especially on `x86_64-linux` where we're under 500 failures now.  At this rate this platform might get close to zero soon.  Darwin failures were reduced by more than a hundred, which isn't bad either.

**Comment by vcunat** [comment]
BTW, we now have the three usual 18.03 channels.

**Comment by Ma27** [comment]
@vcunat @fpletz thanks a lot for your work! Really looking forward to the new release!

**Comment by xeji** [comment]
For fails -= 2 please pick #36676 and #36935.

**Comment by gebner** [comment]
@xeji done

**Comment by xeji** [comment]
`s3ql`: version update in e3db2501f9ec fixes build, please pick.

**Comment by xeji** [comment]
Hydra evals of the release-18.03 job have failed today: 
`Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS`

**Comment by vcunat** [comment]
Lately Hydra evals of large jobsets often run into various limits.  Fortunately the failure rate isn't too high ATM.

**Comment by xeji** [comment]
To fix `nixos.tests.vault`, please pick 3aa3738bb2582f9142675c952f7e6e3621081c1e from master.

**Comment by Ma27** [comment]
#37717 fixes the build of `qpid-cpp` and is now ready to merge.

**Comment by xeji** [comment]
A few of the fixes mentioned above (plus some others) were merged into master but have not made it into 18.03 yet according to [latest hydra build](https://hydra.nixos.org/eval/1444077). As the release date is near, here's a little checklist to help ensure no existing fix is accidentally forgotten. Everyone please feel free to edit/check off.

- [ ] godot #34971
- [ ] gosmore #37285
- [ ] kmsxx #37653
- [ ] mythtv #37348 
- [ ] notary #36804
- [ ] opal #37776 
- [ ] s3ql https://github.com/NixOS/nixpkgs/commit/e3db2501f9ec3271d8dd0c76ea7938650cee5589
- [ ] telepathy-gabble #37702

**Comment by srhb** [comment]
Looks like 0d20e7db5ba8f563db35752da51976c8181be1df fixed telepathy-gabble. Marking that done.

**Comment by xeji** [comment]
... yes, looks like hydra is somehow still caching the old failure after 3 days. hope it will sort itself out.

**Comment by andir** [comment]
I just opened a PR (#37948) for an openssl version bump that should probably go into 18.03 some time soon. Since that trigers a mass-rebuild and would probably cause some delays with other stabilization efforts I'd like to hear some feedback from our release team (@vcunat @fpletz) about when and where to merge that into (staging-18.03?).

**Comment by fpletz** [comment]
These kinds of minor bumps should be pretty harmless even though they are mass rebuilds. People should use channels or the nixpkgs-channels repo anyways instead of using the `release-18.03` branch. So pushing to the 18.03 branch is fine.

**Comment by shlevy** [comment]
@fpletz we have staging-18.03 (and a jobset) for mass rebuilds... I definitely build from git quite a bit.

**Comment by Ma27** [comment]
currently working on fixing `frescobaldi` (and switching to `poppler_qt5` as the qt4 variant was abandoned) on the following branch: https://github.com/NixOS/nixpkgs/compare/master...Ma27:cleanup-frescobaldi

It requires some improvements (I'd like to have working test suites) before filing a PR

**Comment by xeji** [comment]
Many regressions in https://hydra.nixos.org/eval/1444338 . Looking for the cause.

**Comment by vcunat** [comment]
> ... yes, looks like hydra is somehow still caching the old failure after 3 days. hope it will sort itself out.

There's this "problem" for fixed-output derivations.  The hash didn't change, so it isn't re-attempted.

**Comment by xeji** [comment]
> There's this "problem" for fixed-output derivations. The hash didn't change, so it isn't re-attempted.

Luckily, that particular case was solved by an auto-bump from ryantm's script in the meantime...

**Comment by vcunat** [comment]
> Could someone please backport #38016, #38015 and #38002?

Pushed by Dezgeg.

**Comment by rnhmjoj** [comment]
monero-gui broke when monero was updated in 28c00f8f3b4b1f619a7c534767a5ef515ac42ee5.
They haven't created an official release yet so I'm trying to build master in the meantime but I run into some issues.

**Comment by xeji** [comment]
> The remaining packages will be marked as broken before the release (on the failing platforms), i.e. at the end of March.
@vcunat @fpletz what's the current plan/timeline for this?

**Comment by vcunat** [comment]
I thought I could get to pass through them during this week, probably on weekend, including a check that they fail on master as well, but certainly feel free to do it (anyone) and send a PR (master + pick to 18.03 later).  In my case it can also easily happen that something more urgent appears.

**Comment by xeji** [comment]
Thanks. I'll start a PR tonight and incrementally add to it. Feel free to take over any time.

**Comment by xeji** [comment]
While preparing #38702, I found some packages that don't currently build on hydra but seem to require further investigation. Here's a (dynamic) list for reference: 

- [ ] `buildbot`: fails on hydra, succeds locally

**Comment by domenkozar** [comment]
I've released stack2nix 0.2.1 to address version bump, once haskell packages are synced it should compile again.

**Comment by vcunat** [comment]
The next ZHF iteration: https://github.com/NixOS/nixpkgs/issues/45960
