### ISSUE TITLE
Java 6 on Nix (and IcedTea build purity)

### ISSUE THREAD

**Issue by auntieNeo** [NixOS/nixpkgs#3645]
I happen to be using some old Java software that requires version 6 of the Java API, but it doesn't look like there are any Java 6 runtimes in nixpkgs. So I'm looking into packaging such a runtime myself. From what I can tell, both OpenJDK6 and IcedTea6 are actively maintained, so security should not be a concern.

Both OpenJDK6 and IcedTea6 use build systems that only slightly differ from their Java 7/8 variants. At least that's what their build documentation suggests. Since both OpenJDK7 and IcedTea7 are already in nixpkgs, I'm trying to modify the existing nix expressions. I'm going to ask some questions here before I duplicate any effort.

The most difficult thing I'm running into is the bootstrap requirement for building OpenJDK. The OpenJDK documentation recommends using the official, proprietary JDK from Sun/Oracle. Debian's OpenJDK6 package says that it was built with IcedTea. IcedTea suggests using either GCC and the Eclipse Java Compiler or a pre-built install of IcedTea.

Nix actually uses OpenJDK to build IcedTea, and OpenJDK is built from an OpenJDK tarball located at http://tarballs.nixos.org/openjdk-bootstrap-x86_64-linux-2012-08-24.tar.xz. This seems a bit contrary to one of the original intents of IcedTea: providing a Java platform that can be built without proprietary tools. This issue might be silly, and to be honest I'll just be happy to have a JDK6. But for a distribution like NixOS that puts the build system into the hands of the users, it seems like a loss to have a mysterious tarball where it's not necessarily needed.
http://en.wikipedia.org/wiki/Icedtea#The_aims

Anyway, does anyone know where the bootstrap tarball came from? Is this solution just more practical? If I can figure out what I should use to bootstrap Java 6, I'll keep hacking at this.

**Comment by Profpatsch** [comment]
(triage) anything?

**Comment by grahamc** [comment]
I think the tarballs are to provide our own mirrors of frequently used software so we're not leaching, but I'm not 100% sure.

If you're still interested, please feel free to re-bump the issue and we could open it again.
