### ISSUE TITLE
Update request: python3 packages webexteamsdk 3.11-3.12 → /dev/null

### ISSUE THREAD

**Issue by chadillac** [NixOS/nixpkgs#364649]
## Package Information

- Package name: python311packages.webexteamssdk & python312packages.webexteamssdk
- Latest released version: 2.0.1
- Current version on the unstable channel: 2.0.1
- Current version on the stable/release channel: 2.0.1

## Checklist

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@fabaff appears to be the maintainer of both `webexteamssdk` and `webexpythonsdk`

---

Note for maintainers: Please tag this issue in your PR.

Cisco stopped packaging `webexteamssdk` @ v1.7 with Python 3.10, and with the move to 3.11+ have renamed the underlying library `webexpythonsdk` and moved to v2.  These changes include renaming directories in the site-packages path and introduces breaking changes in 3.11+ instances as `webexteamssdk` imports can't be found.

There is an existing `python311packages.webexpythonsdk` and `python312packages.webexpythonsdk` that should be used, and the `webexteamssdk` packages shouldn't be built or distributed beyond v1.7 or `python310packages.*`, as they're technically not packaged by Cisco and unsupported as well as functionally broken in practice.

https://pypi.org/project/webexteamssdk/
https://pypi.org/project/webexpythonsdk/

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fabaff** [comment]
#364651 will revert the update of `webexteamssdk`.

There is one `webexteamssdk` consumer left, if that is clean-up then we get rid of `webexteamssdk`.

**Comment by chadillac** [comment]
great, I searched PRs and didn't see that existing issue, sorry!
