### ISSUE TITLE
azure-functions-core-tools: 4.0.5455

### ISSUE THREAD

**Issue by ionutnechita** [NixOS/nixpkgs#364653]
Repo: https://github.com/Azure/azure-functions-core-tools

nixos-unstable: 4.0.5455
master: 4.0.5455

New version: 4.0.6610

Error:

Azure Functions Core Tools
Core Tools Version:       4.0.5455 (64-bit)
Function Runtime Version: 4.27.5.21554

[2024-12-12T16:36:02.837Z] Error: Worker was unable to load entry point "src/index.js": HTTP streaming requires Azure Functions Host v4.28 or higher.

**Comment by gepbird** [comment]
This package was updated in https://github.com/NixOS/nixpkgs/pull/361077, but it's not the latest version. Can you check if that fixed the error you're getting?

**Comment by Detegr** [comment]
It is the latest version actually, 6610. The PR title just has it wrong. The package was updated while the PR was open, I updated the version while fixing review comments but forgot to update the PR title.

**Comment by ionutnechita** [comment]
Ok. Thank you for support.

**Comment by ionutnechita** [comment]
I see, now azure-functions-core-tools 4.0.6610  is merged in master branch.

Thank you.

**Comment by ionutnechita** [comment]
I found new changes in [nixos-unstable-small](https://channels.nixos.org/nixos-unstable-small) channel. 
Is good now.

Will close this ticket.
