### ISSUE TITLE
Module request: programs.librewolf

### ISSUE THREAD

**Issue by bittner** [NixOS/nixpkgs#364819]
## Description

I would be nice to be able to (install and) configure Librewolf system-wide, e.g.

```nix
{
  programs.librewolf = {
    enable = true;

    policies = {
      Preferences = {
        "cookiebanners.service.mode.privateBrowsing" = 2; # Block cookie banners in private browsing
        "cookiebanners.service.mode" = 2; # Block cookie banners
      };
      ExtensionSettings = {
        "authenticator@mymindstorm" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/auth-helper/latest.xpi";
          installation_mode = "force_installed";
        };
      };
    };
  };
}
```

This way, it should be easy to switch from [Firefox](https://nixos.wiki/wiki/Firefox) to [Librewolf](https://nixos.wiki/wiki/Librewolf).

## Details

Currently, you can install Librewolf via `environment.systemPackages` and configure it only on a user-basis using the Home Manager module. As a workaround, it's possible to install and configure Firefox system-wide in addition, which results in Librewolf being configured the same way, e.g.

<details><summary>Installation example (click to expand)</summary>
<p>

```nix
{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    librewolf
  ];

  programs.firefox = {
    enable = true;

    policies = {
      DisableTelemetry = true;
      DisableFirefoxStudies = true;
      Preferences = {
        "browser.startup.page" = 3; # Open tabs from last session
        "cookiebanners.service.mode.privateBrowsing" = 2; # Block cookie banners in private browsing
        "cookiebanners.service.mode" = 2; # Block cookie banners
        "privacy.donottrackheader.enabled" = true;
        "privacy.fingerprintingProtection" = true;
        "privacy.resistFingerprinting" = true;
        "privacy.trackingprotection.emailtracking.enabled" = true;
        "privacy.trackingprotection.enabled" = true;
        "privacy.trackingprotection.fingerprinting.enabled" = true;
        "privacy.trackingprotection.socialtracking.enabled" = true;
      };
      ExtensionSettings = {
        "jid1-ZAdIEUB7XOzOJw@jetpack" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/duckduckgo-for-firefox/latest.xpi";
          installation_mode = "force_installed";
        };
        "uBlock0@raymondhill.net" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
          installation_mode = "force_installed";
        };
      };
    };
  };
}
```

</p>
</details>

## Notify maintainers

~@dotlambda~ @squalus

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by itepastra** [comment]
have you tried using the firefox config and then adding `programs.firefox.package = pkgs.librewolf;`? 
I think that might just do what you want to achieve

**Comment by bittner** [comment]
> have you tried using the firefox config and then adding `programs.firefox.package = pkgs.librewolf;`?

That was great advice! It works fine. This way you can install and configure Librewolf system-wide while not being forced to install Firefox, in addition. See [painless-software/nixos-config!6 (GitLab)](https://gitlab.com/painless-software/nixos-config/-/merge_requests/6) for a real-life example.

Note that I'm not experienced with Librewolf as a user, though, so I can't actually tell what works as it usually does and what not. Also, we have a few issues with the current state of the Librewolf package (e.g. #344417). The configuration at least behaves the same way it did with Firefox.

I would like to add this possibility to the [NixOS Wiki](https://nixos.wiki/wiki/Librewolf) as a suggestion. While this is not identical in terms of syntax to the Home Manager suggestion, it is as good as it gets for not having to implement any new feature. I hope that's fine.

**Comment by itepastra** [comment]
It has been added to the wiki, and I think the issue is resolved so I'll close it later today
![image](https://github.com/user-attachments/assets/aa98c854-b9f2-4002-8fa8-3077bbbec4e5)

**Comment by bittner** [comment]
I'm happy to close the issue, but I just want to emphasize again that I'm not 100% certain whether the result of this configuration code is optimal:

> Note that I'm not experienced with Librewolf as a user, though, so I can't actually tell what works as it usually does and what not. Also, we have a few issues with the current state of the Librewolf package (e.g. #344417). The configuration at least behaves the same way it did with Firefox.
