### ISSUE TITLE
Steam: all games say they are using 100+% cpu at all times(btop)

### ISSUE THREAD

**Issue by DaKingof** [NixOS/nixpkgs#364814]
All games that I open in Steam show +100%CPU usage on BTOP but none of my cores are being pushed on the main CPU display. This does not happen when the same games are open elsewhere like Heroic. I'm not sure if this is actually causing detrimental effects, but it is not expected behavior.

![image](https://github.com/user-attachments/assets/81405132-4f28-4090-93c0-f6a62079850f)

Open BTOP, and launch a game with Steam and click the application to see its details. It will always say it's at 100+% sometimes showing 4-500% usage.
 
I'm not sure exactly what is wrong, I tried looking at the logs and don't see anything that I would think does this, but I'm willing to poke around with some help to find the source of this issue as I don't want my hardware possibly being negatively affected. 

 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0-rt7, NixOS, 25.05 (Warbler), 25.05.git.a73246e2eM`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager, musnix, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

@K900

**Comment by Gliczy** [comment]
`btop` has an option to show the CPU load per core instead of accounting for all the cores.
If it is enabled and a program is multi-threaded, it may show that the CPU usage is above 100%.

**Comment by DaKingof** [comment]
Okay, thank you. So then it's just showing I am using 200% worth of power compared to a single core. Got it. I'm not sure why this overhead is so high though. It's strange cause it only happens as soon as I start a game and even with the recording feature disabled. I guess I will just chop it up to Steam wrapper being bloated or something. Thank you

**Comment by Gliczy** [comment]
Well, 200% of total CPU load is not that high with a 3900X. In the case of dota2, having 4 cores at 50% load would display a total of 200% CPU usage for it's process.

You also mentioned that some games were having higher CPU usage when launched with `steam` compared to `heroic`.
I haven't heard or experienced something like that, but, if you believe there is an issue here, could you please provide more information? 
Otherwise we can close this issue.

**Comment by Atemu** [comment]
Games using a few cores worth of CPU compute at runtime is expected behaviour.

If you can find a significant difference in CPU utilistation between a game running via steam or some other launcher in a comparable scenario, please open an issue on that.
