### ISSUE TITLE
nix build is unusable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#36489]
## Issue description

I want to replace uses of `nix-build` with new `nix build`, however there are two issues with it:
1. `nix build --no-link` should print output path, otherwise there is no much purpose in this flag.
2. ~~I see no equivalent to `nix-build '<nixpkgs>'`. I.e. to use default channel without need to explicitly specify channel version.~~ It's `nix build nixpkgs.<package>`. Would be better to add this to examples, like it done for `nix run`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by jtojnar** [comment]
1. https://github.com/NixOS/nix/issues/1930
2. The new syntax is actually pretty neat and consistent, you can use `nix build -f '<nixpkgs>' package1 package2`. I agree that documentation is somewhat lacking at the moment.

**Comment by gnidorah** [comment]
@jtojnar Thanks! I will stick to https://github.com/NixOS/nix/issues/1930 then.

**Comment by gnidorah** [comment]
@jtojnar BTW what is alternative to `nix-build -E 'expression'`?

**Comment by edolstra** [comment]
`nix build '(expression)'`

**Comment by gnidorah** [comment]
@edolstra Thanks!

**Comment by gnidorah** [comment]
Will `nix run` get shebang support to be used in scripts instead of nix-shell?

**Comment by bhipple** [comment]
@gnidorah `nix build --no-link` is usable again if you apply [this patch from this pull request](https://github.com/NixOS/nix/pull/1647) from last year; otherwise it's probably best to just stick to `nix-build` for now.
