### ISSUE TITLE
Module request: llama-cpp cuda

### ISSUE THREAD

**Issue by mcmah309** [NixOS/nixpkgs#364842]
## Description

llama-cpp with cuda support

current llama-cpp module: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/llama-cpp.nix
project flake file: https://github.com/mcmah309/llama.cpp/blob/master/.devops/nix/package.nix
ollama module as reference: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/ollama.nix

## Notify maintainers

@newAM 
@philiptaron 
@SomeoneSerge
@onny
@abysssol 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SomeoneSerge** [comment]
The `llama-cpp` package already exposes the `cudaSupport` parameter: https://github.com/NixOS/nixpkgs/blob/c98a4e03e70be11635313d562f88ec87e86d3e62/pkgs/by-name/ll/llama-cpp/package.nix#L11

The module can be configured to use CUDA-capable llama-cpp using the `package` option: https://github.com/NixOS/nixpkgs/blob/5d67ea6b4b63378b9c13be21e2ec9d1afc921713/nixos/modules/services/misc/llama-cpp.nix#L19

**Comment by philiptaron** [comment]
See above! 😄
