### ISSUE TITLE
nixos-install doesn't appear to idempotently set passwords

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#36493]
On 17.09 ISO. I tried running nixos-install multiple times trying different password settings for a declared user configuration.

Even when I removed everything and just said `password = "abc123";` and after `nixos-install`, reboot, I still couldn't login. (It is possible that something else I'm doing is wrong, because `hashedPassword` doesn't work either).

Another major problem is the fact that running `nixos-install` each time results in reinstalling everything. This is pretty annoying as it lengthens the debug cycle when you can't actually login to your target system. There should be a way to continue from where it left off inside the `/mnt/nix/store`.

**Comment by lheckemann** [comment]
This is expected behaviour:

>If the option users.mutableUsers is true, the password defined in one of the three options will only be set when the user is created for the first time.

Set users.mutableUsers to false if you want idempotency.

>Another major problem is the fact that running nixos-install each time results in reinstalling everything

This is a known bug in the installer (couldn't find the issue for it though) which should be fixed by #34636.

**Comment by CMCDragonkai** [comment]
It has always been false. I never mutable users to true. This problem is about nixos-install not installing a new password even when mutable users is false.

**Comment by CMCDragonkai** [comment]
Not relevant to me anymore.
