### ISSUE TITLE
awsume is missing 'setuptools' dependency

### ISSUE THREAD

**Issue by antoineco** [NixOS/nixpkgs#364969]
## Describe the bug

The `awsume` package requires setting up a shell alias. When this alias is not set, the following warning is printed while invoking the command:

```
Warning: the awsume shell script is not being sourced, please use awsume-configure to install the alias
```

If this instruction is followed and the `awsume-configure` command is invoked, an error is thrown: `No module named 'setuptools'`.

This seems to be due to Python 3.12 not shipping with `setuptools`, `distutils`, and other dependencies which used to be included in Python 3.10:
- https://github.com/trek10inc/awsume/issues/238

## Steps To Reproduce

1. `awsume-configure`

```
Traceback (most recent call last):
  File "/nix/store/01x7f9hc96rw5y2f13hlyrdiw93rr7d1-awsume-4.5.5/bin/.awsume-configure-wrapped", line 6, in <module>
    from awsume.configure.main import main
  File "/nix/store/01x7f9hc96rw5y2f13hlyrdiw93rr7d1-awsume-4.5.5/lib/python3.12/site-packages/awsume/configure/__init__.py", line 4, in <module>
    from awsume.configure import post_install
  File "/nix/store/01x7f9hc96rw5y2f13hlyrdiw93rr7d1-awsume-4.5.5/lib/python3.12/site-packages/awsume/configure/post_install.py", line 1, in <module>
    from setuptools.command.install import install
ModuleNotFoundError: No module named 'setuptools'
```

## Expected behavior

Command succeeds.

## Screenshots

\-

## Additional context

\-

## Metadata

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/rml4w5lj8jxsnlddmy0r1bd4389fkdh7-source`
 ```

## Notify maintainers

@nilp0inter

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
btw, you can also do eg.
```
programs.zsh.shellAliases.awsume = ". ${lib.getExe pkgs.awsume}";
```

**Comment by antoineco** [comment]
That's true, and to be honest I did set up the alias manually.

However adding the alias is not the only thing this command does; right now the shell completion  provided by the package is also broken because all the `_awsume` file contains is this line:

```sh
fpath=(~/.awsume/zsh-autocomplete/ $fpath)
```

Whereas running the `awsuse-configure` creates the actual destination, which contains:

```sh
#compdef awsume
_arguments "*: :($(awsume-autocomplete))"
```

I'll report that issue separately from the missing `setuptools`.
