### ISSUE TITLE
Update request: GlobalProtect-openconnect `1.4.6` → `2.3.9`

### ISSUE THREAD

**Issue by LeaderbotX400** [NixOS/nixpkgs#365050]
## Package Information

- Package name: GlobalProtect-openconnect
- Latest released version: `2.3.9`
- Current version on the unstable channel: `1.4.9`
- Current version on the stable/release channel: `1.4.9`

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Binary-Eater** [comment]
This is already done using the separate `gpclient` package.

See

* #316526
* #355758
