### ISSUE TITLE
rclone: fish completion does not work

### ISSUE THREAD

**Issue by ilyagr** [NixOS/nixpkgs#365135]
## Describe the bug

fish shell completion does not work

## Steps To Reproduce

1. Install `fish` via Homebrew on a Mac. (**Update:** Not sure whether it'd work with nixpkgs's fish or not. I would guess not, but I didn't check. In any case, I'd like it to work with my Homebrew-installed fish)
2. Open fish shell
3. Type `rclone <TAB>`
4. Observe that fish completes filenames instead of commands

## Expected behavior

You see completion for commands like `about`, `check`, etc.

## Additional context

The problem is that `fish` includes [completions for `rclone`](https://github.com/fish-shell/fish-shell/blob/master/share/completions/rclone.fish) that override the completions generated by `installShellCompletions` [here](https://github.com/NixOS/nixpkgs/blob/a3bb0569909138b08c704e518b27f46320ec1d6e/pkgs/applications/networking/sync/rclone/default.nix#L70).

**Update:** The actual problem seems to be that `rclone version` of Nix-built rclone starts with `rclone 1.68.2`, while fish expects `rclone v1.68.2` with a `v`. This should be fixed in a future fish, https://github.com/fish-shell/fish-shell/commit/cc8fa0f7808130ece03f1c2ac0c95f9ede2aaa1d.

<details><summary>My original, wrong, theory</summary>

Fish's built-in completions rely on `rclone complete fish -` command. However, my Nix-installed `rclone` does not support this:

```console
# **Update:** this is not a problem, `rclone completion fish -` works.
$ rclone completion fish
2024/12/14 00:20:13 CRITICAL: open /etc/fish/completions/rclone.fish: no such file or directory
```
</details>

I am not sure whether `fish` should change its behavior, I asked [on Matrix](https://matrix.to/#/!YLTeaulxSDauOOxBoR:matrix.org/$AYr9338g_Tt4xUU5yC6OtvxPHg1eDy-kO8yxs4O0bRI?via=matrix.org&via=gitter.im&via=one.ems.host). ~~However, there would be no problem if `rclone completion fish` worked with Nix-installed `rclone`.~~

**Workaround**: Delete `share/fish/completions/rclone.fish`, `/opt/homebrew/share/fish/completions/rclone.fish`, or the corresponding file on your system. This allows the nixpkgs `installShellCompletions`-installed completions in e.g. `~/.nix-profile/share/fish/vendor_completions.d` to work, and they work fine.

## Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/g9bw874w67bfsvg93szwnxxjxp4lphby-source`
```

## Notify maintainers

@SuperSandro2000 @tomfitzhenry

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ilyagr** [comment]
My original theory of this bug was wrong, so the bug description is now edited.

**Comment by SuperSandro2000** [comment]
Mixing things like that is likely to cause issues and not something that is really supported.
