### ISSUE TITLE
Package request: Rill

### ISSUE THREAD

**Issue by rupurt** [NixOS/nixpkgs#365269]
## Project description

Rill is a tool for effortlessly transforming data sets into powerful, opinionated dashboards using SQL. BI-as-code.

## Metadata

* homepage URL: https://www.rilldata.com/
* source URL: https://github.com/rilldata/rill
* license: apache-2.0
* platforms: unix, linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pluiedev** [comment]
Duplicate of #322741 — let's try to keep it in one issue

**Comment by rupurt** [comment]
My bad @pluiedev. Didn't check before :cry:
