### ISSUE TITLE
nixos-rebuild-ng: GC race condition with --build-host

### ISSUE THREAD

**Issue by jlamur** [NixOS/nixpkgs#365225]
## Describe the bug

There are two warnings when building with `--build-host`: `warning: you did not specify '--add-root'; the result might be removed by the garbage collector`.
The first time it is because you evaluate the config on the local host, then the second time on the build host when you realize.

The underlying problem is a race condition: the GC could delete the drv and the realization before you copy/activate them.

This problem exists in the legacy nixos-rebuild.

Relevant trace:
```
$ nixos-rebuild-ng -f default.nix -A bob switch --target-host bob --build-host bob -v
[...]
building the system configuration...
debug: nixos_rebuild.process: calling run with args=['nix-instantiate', PosixPath('default.nix'), '--attr', 'bob.config.system.build.toplevel', '-v'], kwargs={'stdout': -1}, extra_env=None
[...]
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[...]
debug: nixos_rebuild.process: calling run with args=['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/nixos-rebuild.ehxn453f/ssh-%n', '-o', 'ControlPersist=60', 'bob', '--', 'nix-store', '--realise', '/nix/store/1g3pbhalxk7gsg99jsj4kzjg0kpsyv7d-nixos-system-bob-24.11pre-git.drv', '-v'], kwargs={'stdout': -1}, extra_env=None
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[...]
```

## Notify maintainers

@thiagokokada

**Comment by thiagokokada** [comment]
This is only a problem for non-Flakes, in Flakes we use `nix build ` that doesn't trigger this warning.

> The underlying problem is a race condition: the GC could delete the drv and the realization before you copy/activate them.

The solution here would be to create a `TMPDIR` in the remote host and use `--add-root` to create a temporary root that should be deleted once the `nixos-rebuild` finishes. The reason I didn't do this is because this is slightly tricker than it looks, since we are talking in the remote host we can't use e.g.: Python's `TemporaryDirectory`.

**Comment by jlamur** [comment]
Note that I think that there is also a race condition when nixos-rebuild-ng copies to and from the remote host... I am not sure if that one is really fixable, I think that it would require to create a gc root on the remote host before the copy operation. That might be something that sould be implemented in `nix copy`, if possible? I am not sure...

I reported the other ones because they print warnings...

**Comment by jlamur** [comment]
> The reason I didn't do this is because this is slightly tricker than it looks, since we are talking in the remote host we can't use e.g.: Python's `TemporaryDirectory`.

I completely agree, it is far from trivial! For the local warning, a TemporaryDirectory is still usable, right?

> This is only a problem for non-Flakes, in Flakes we use `nix build ` that doesn't trigger this warning.

Speaking of that, isn't there a `--no-link` missing here? I just tried `nixos-rebuild-ng --flake whatever --build-host bob` and it created a `result` in my host home directory.
https://github.com/NixOS/nixpkgs/blob/c27b1c401ae659d20e4ed5bd6a50d31f7872fdce/pkgs/by-name/ni/nixos-rebuild-ng/src/nixos_rebuild/nix.py#L118-L129

**Comment by thiagokokada** [comment]
> > The reason I didn't do this is because this is slightly tricker than it looks, since we are talking in the remote host we can't use e.g.: Python's `TemporaryDirectory`.
> 
> I completely agree, it is far from trivial! For the local warning, a TemporaryDirectory is still usable, right?

Yes.


> > This is only a problem for non-Flakes, in Flakes we use `nix build ` that doesn't trigger this warning.
> 
> Speaking of that, isn't there a `--no-link` missing here? I just tried `nixos-rebuild-ng build --flake whatever --build-host bob` and it created a `result` in my host home directory.
> https://github.com/NixOS/nixpkgs/blob/c27b1c401ae659d20e4ed5bd6a50d31f7872fdce/pkgs/by-name/ni/nixos-rebuild-ng/src/nixos_rebuild/nix.py#L118-L129

I am replicating `nixos-rebuild` here, where it pass `--no-out` only in switch and boot.

**Comment by jlamur** [comment]
> it pass `--no-out` only in switch and boot.

Oh sorry I did not try that. Perfect then!
