### ISSUE TITLE
USB redirect broken in virt-viewer

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#36533]
## Issue description
USB redirect is brokoen in virt-viewer.
![selection_016](https://user-images.githubusercontent.com/723199/37160921-9a0d4ff6-22f1-11e8-9073-a39bd6a6090c.png)

Listing of directory shows the issue:
`/nix/store/rlkv757g7fmz05qfh1xpdg44zg2v2qfv-spice-gtk-0.34/bin/spice-client-glib-usb-acl-helper -> /run/wrappers/bin/spice-client-glib-usb-acl-helper
/nix/store/rlkv757g7fmz05qfh1xpdg44zg2v2qfv-spice-gtk-0.34/bin/spice-client-glib-usb-acl-helper.real
`
The symlink shows to itself instead of spice-client-glib-usb-acl-helper.real

### Steps to reproduce
- Open virt-viewer
- Connect to qemu/kvm/libvirt
- Try to redirect USB
- Read the error message

### NixOS details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
 - nix-channel: `https://nixos.org/channels/nixos-unstable`

### Device details
 - device: `20J6S0DM00 ThinkPad T470p`
 - cpu: `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`
 - gpu: `Intel Corporation Device 591b (rev 04)`

**Comment by d4g** [comment]
@fpletz

**Comment by xeji** [comment]
USB redirect requires a setuid wrapper (which cannot be included in the package), see #35214 .
Please activate this in `configuration.nix` as shown here: https://github.com/NixOS/nixpkgs/pull/35214#pullrequestreview-97783209 and test again.

**Comment by xeji** [comment]
Anyway, this should fail with an appropriate message if the setuid wrapper doesn't exist. 
@Mic92 has also suggested putting this into a nixos module.

**Comment by d4g** [comment]
It should not require a setuid wrapper, if the user is in the appropriate group and has read/write access to the devices.

If you read the error description, there is a problem with the symlink.
This was working on former versions of the package @xeji

**Comment by xeji** [comment]
I will look into it and fix the broken symlink.

**Comment by xeji** [comment]
Fixed in #37184. If you do not wish to use polkit authentication and the setuid wrapper, you can now build the package with `withPolkit = false;` and use custom udev rules instead. See comments in code of #37184.
