### ISSUE TITLE
zed-editor CLI does not work on darwin

### ISSUE THREAD

**Issue by uncenter** [NixOS/nixpkgs#365465]
## Describe the bug

I'm unable to use the zed-editor package's `zededitor` CLI on aarch64-darwin. If I run it with anything besides `--help`/`--version` - seemingly anything to do with launching the editor - fails; for example `zeditor`, `zeditor .`, `zeditor foo/bar` (all of which succeed when run with `zed` instead of `zeditor`).

I tried installing and using Zed's `zed` binary via the `cli: install` command in their command palette, which worked just fine.

## Steps To Reproduce

1. Build zed-editor on aarch64-darwin.
2. Run commands as listed above, notice the program hangs and no editor windows are opened or changed.

## Expected behavior

Should function the same as the binary from `cli: install` and open directories as new editor windows correctly.

## Additional context

```
$ zeditor --version
Zed 0.164.2 – /nix/store/rsk8zxhv3m64dpjjgsiv3h1l5shk9pkx-zed-editor-0.164.2/Applications/Zed.app
```

I see the following logs in the Zed log file:

```
2024-12-15T19:07:34.553346-05:00 [INFO] ========== starting zed ==========
2024-12-15T19:07:34.582962-05:00 [INFO] Opening main db
2024-12-15T19:07:34.585575-05:00 [INFO] Opening main db
2024-12-15T19:07:34.618909-05:00 [INFO] Got instance handshake
```

I see a Zed window icon appear on my dock temporarily after invoking the command but nothing after.

## Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.1.0, macOS 15.1.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/g9bw874w67bfsvg93szwnxxjxp4lphby-source`
 
## Notify maintainers

@GaetanLepage @niklaskorz 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by niklaskorz** [comment]
Can't reproduce, the CLI works for me on both nixpkgs-24.11 (Zed 0.161.2) and nixpkgs-unstable (Zed 0.165.4).

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/45bzbkwnyb6nikgc7jkrn7vjibhy4xhk-source`
