### ISSUE TITLE
proton-ge isn't automatically installed to steam

### ISSUE THREAD

**Issue by Kommynct** [NixOS/nixpkgs#365497]
## Describe the bug

If you install proton-ge-bin as an extracompatpackage for steam, it doesn't do anything

## Steps To Reproduce

programs.steam.extraCompatPackages = with pkgs; [ proton-ge-bin ];

go to steam settings > compatibility, notice proton-ge isn't listed

## Expected behavior

the most recent version of proton-ge should be listed as a compatibility tool. If that's not how that works, then the documentation needs updated, i got this information from: https://wiki.nixos.org/wiki/Steam

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by zimward** [comment]
Ping @NotAShelf @Shawn8901

**Comment by NotAShelf** [comment]
That is how I currently install proton ge, and it is available under GE-Proton. Can you please confirk that is *not* in the list of compatibility tools?

**Comment by Kommynct** [comment]
it's not there, and it's not there on a fresh install of nixos either.

https://gitlab.com/that1communist/dotfiles/-/blob/master/etc/nixos/sys.nix here's my configuration.nix if you want to verify i have it setup right... but i had to install it via protonup-qt to make it appear on the list.

**Comment by Shawn8901** [comment]
I see that you have stem added manually to your systemPackages https://gitlab.com/that1communist/dotfiles/-/blob/master/etc/nixos/sys.nix#L124 steam normally uses a wrapper and via said wrapper the proton stuff is injected. I suspect that you are running the non-wrapped steam.

**Comment by Shawn8901** [comment]
That is actually a dummy package, that gets altered by the module.
The module description does okayish give the hint to not use it by the description `Steam dependencies (dummy package, do not use)`. Still glad that we found the issue :slightly_smiling_face:
