### ISSUE TITLE
Package request: quickemu

### ISSUE THREAD

**Issue by eval-exec** [NixOS/nixpkgs#365513]
## Project description

Quickly create and run optimised Windows, macOS and Linux virtual machines

## Metadata

* homepage URL: https://github.com/quickemu-project/quickemu
* source URL: https://github.com/quickemu-project/quickemu
* license: MIT
* platforms: unix, linux, darwin
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
It's been in the repos since [2021](https://github.com/NixOS/nixpkgs/commits/49d656d258d13f142b011af0a893d431291e7b50/pkgs/development/quickemu/default.nix?browsing_rename_history=true&new_path=pkgs/by-name/qu/quickemu/package.nix&original_branch=nixos-unstable)
