### ISSUE TITLE
incus 6.8: CSM boot broken

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#365696]
## Describe the bug

When launching a CSM vm with incus 6.8 an error occurs

```
Error: Couldn't find one of the required UEFI firmware files: []
Try `incus info --show-log csm` for more info
```

## Steps To Reproduce

1. Enable incus
2. `incus init csm --vm --empty -c security.csm=true -c security.secureboot=false`
3. `incus start csm`

## Expected behavior

Starts correctly

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.64, NixOS, 25.05 (Warbler), 25.05.20241216.ffc4f78`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.3`
 - nixpkgs: `/etc/nix/path/nixpkgs`

## Notify maintainers

@NixOS/lxc 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
We're probably missing the necessary firmware in the linkfarm for the firmware https://github.com/NixOS/nixpkgs/blob/948a31b4b765c01f485c05bdeb12b2197f440d5a/nixos/modules/virtualisation/incus.nix#L84

OVMF doesn't support CSM afaik. We have SeaBIOS in tree but I'm not sure if upstream supports it. If they do we need to figure out the file names they look for and add it to the linkfarm.

**Comment by adamcstephens** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/365778 which should have a fix for this.
