### ISSUE TITLE
Linux Hardened Kernel unavailable config options from vanilla trakcing issue

### ISSUE THREAD

**Issue by fabianhjr** [NixOS/nixpkgs#365700]
### Tracking description

The following kernel common-config options have configuration issues on Hardened 6.12 and where lowered to mkDefault on common-config + option on hardened config:

- CONFIG_DRM_PANIC_SCREEN_QR_CODE
- CONFIG_RUST
- CONFIG_SCHED_CLASS_EXT

#### Reference Issue(s)/PR(s)

- #365214

### Follow-up issues/notes

Have to research why the options became unavailable on 6.12 hardened vs vanilla and if any followup change is required

#### Additional context

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
This seems to also be an issue with lqx https://github.com/NixOS/nixpkgs/issues/365136

**Comment by surfaceflinger** [comment]
SCHED_CLASS_EXT depends on DEBUG_INFO_BTF
CONFIG_DRM_PANIC_SCREEN_QR_CODE depends on CONFIG_RUST

but

DEBUG_INFO_BTF and RUST need GCC_PLUGIN_RANDSTRUCT to be disabled.

not sure if disabling GCC_PLUGIN_RANDSTRUCT will be good since it's a hardened kernel after all...

**Comment by surfaceflinger** [comment]
RANDSTRUCT seems to actually not be that random in nixpkgs, so perhaps we could turn it off? https://github.com/NixOS/nixpkgs/blob/cfeb7de067cb4fee49f7fef528e28d69c0dacb9a/pkgs/os-specific/linux/kernel/randstruct-provide-seed.patch#L9

**Comment by fabianhjr** [comment]
Thanks for researching and happy holidays, I think from what you gathered I would be more inclined on disabling RANDSTRUCT and re-enabling the options here.
