### ISSUE TITLE
[staging-next] Build failure: gnuradio (due to Numpy 2)

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#365721]
## Steps To Reproduce

1. build `gnuradio` on staging-next

## Build log

<details>

<summary>Build Log</summary>

```
178/267 Test #192: qa_correlate_access_code_XX_ts ...............***Failed    0.34 sec
......E
======================================================================
ERROR: test_payload_lengths (__main__.test_correlate_access_code_XX_ts.test_payload_lengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/gr-digital/python/digital/qa_correlate_access_code_XX_ts.py", line 104, in test_payload_lengths
    self._variable_payload_t(length)
  File "/build/source/gr-digital/python/digital/qa_correlate_access_code_XX_ts.py", line 77, in _variable_payload_t
    self.assertEqual(header[0] * 256 + header[1], header[2] * 256 + header[3])
                     ~~~~~~~~~~^~~~~
OverflowError: Python integer 256 out of bounds for uint8

----------------------------------------------------------------------
Ran 7 tests in 0.051s

FAILED (errors=1)
```

</details>

## Additional context

Seems related to https://numpy.org/neps/nep-0050-scalar-promotion.html

## Notify maintainers

@doronbehar @bjornfor @fpletz @jiegec 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by doronbehar** [comment]
Thanks for opening the issue and thanks for working on the `staging-next` merge! PR is at:

- https://github.com/NixOS/nixpkgs/pull/365839

I tested that patch on Nix's community builders and:

- On `aarch64-darwin` I encountered a build error with `pycairo` - shouldn't 
- On `x86_64-linux` it fixed the issue.

Please merge it unless you want to fix also the Darwin issues.
