### ISSUE TITLE
Envision fails to build profile for WiVRn with missing dependencies message

### ISSUE THREAD

**Issue by NIMFER** [NixOS/nixpkgs#365870]
## Describe the bug

Building any profile fails with a missing dependencies error on NixOS 24.11, just like #358664 on NixOS 24.05.
Monado, Envision and WiVRn are enabled in the nix configuration with these settings:
```nix
  services.monado = {
    enable = true;
    highPriority = true;
  };
  services.wivrn = {
    enable = true;
    openFirewall = true;
    autoStart = true;
  };
  programs.envision = {
    enable = true;
    openFirewall = true;
  };
```
## Steps To Reproduce

1. Install and enable envision module (as shown earlier)
2. Launch `envision`
3. Select any profile in drop down and click "Build Profile"

## Expected behavior

There shouldn't be any errors regarding missing dependencies, and profiles should build just fine.
 
### Lighthouse Driver
![Lighthouse Driver](https://github.com/user-attachments/assets/1ad8aeb7-78a2-4862-8ba5-95b0978aec64)
### OpenHMD
![OpenHMD](https://github.com/user-attachments/assets/69753f33-8b28-4468-9a62-3669e1d47fef)
### Simulated Driver
![Simulated Driver](https://github.com/user-attachments/assets/83a80502-a16d-4387-9444-8b822622fbfb)
### Survive
![Survive](https://github.com/user-attachments/assets/895c96a0-702e-4f8a-a38d-d005156e6401)
### WMR
![WMR](https://github.com/user-attachments/assets/5a700e48-9ec0-4d1a-b58c-aca4d1a2f447)
### WiVRn
![WiVRn](https://github.com/user-attachments/assets/94333b2c-2a07-47fb-a260-fd7988135475)

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.63, NixOS, 24.11 (Vicuna), 24.11.20241210.a0f3e10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/store/va0p2i72cm2ljwm084a0g6ji41s5qnyz-source`
```

## Notify maintainers

@Pandapip1

**Comment by Pandapip1** [comment]
Thankfully with https://gitlab.com/gabmus/envision/-/issues/144 partially implemented, I can start to add tests to catch this.

**Comment by Pandapip1** [comment]
...never mind. The envision CLI fails in a non-graphical environment.

**Comment by Pandapip1** [comment]
Opened https://gitlab.com/gabmus/envision/-/issues/160 and https://gitlab.com/gabmus/envision/-/issues/161. Will fix the missing dependency issue in the meantime.

**Comment by Pandapip1** [comment]
Resolved.
