### ISSUE TITLE
NixOS module renames break expected failure upon setting nonexistent options

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#36590]
## Issue description

`mkRenamedOptionModule` breaks error reporting of attempts to set nonexistent options.

### Steps to reproduce

1. Mistakenly set `virtualization.virtualbox.host.hardeningEnable = false;` in your `configuration.nix`
2. Run the usual `nixos-rebuild switch`
3. Check `/var/run/wrappers/bin`, expecting to *not* see the setuid wrappers for virtualbox there; instead, you *do* still see the setuid wrappers.

Did you catch the mistake at step 1? I've been trying to debug this for a couple hours now, and I just now realized what I got wrong: I should have spelled "virtualization" as "virtualisation" (note the "s" instead of "z").

Normally the module system would fail fast and loudly about setting a nonexistent option - you'd get a message along the lines of:

    error: The option `blah' defined in `/home/cstrahan/src/nixos-config/configuration.nix' does not exist.
    (use '--show-trace' to show detailed location information)

However, this one line is responsible for this not happening:

https://github.com/NixOS/nixpkgs/blob/341dd2a9ad49501cc4931174d087ba74c873a3b5/nixos/modules/rename.nix#L196

It would appear that `mkRenamedOptionModule` has this behavior: you can specify any nonexistent options rooted under the renamed namespace ("virtualization", in this case), and the module system will silently ignore that you screwed up, rather than letting you know how/why/where you screwed up.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 18.03.git.cc4677c (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0pre5968_a6c0b773`
 - channels(root): `"nixos-18.03pre120540.b8f7027360"`
 - channels(cstrahan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by JohnAZoidberg** [comment]
This is quite a big deal. Now was the second time for me that I spent at least an hour digging everywhere and coming to the conclusion that docker should be enabled with `virtualization.docker.enable` until I realized the spelling mistake.
We really need to do something about this!

The problem is not only that this option is ignored but because I have been developing with QEMU and other virtualization packages that all lie under `pkgs/{tools,applications}/virtualization/` I expected the module options to be spelled the same.

**Comment by edolstra** [comment]
I've fixed the bad rename, though this doesn't fix the underlying problem reported by @cstrahan.

**Comment by lheckemann** [comment]
still broken

**Comment by Infinisil** [comment]
Apparently this was fixed unintentionally with https://github.com/NixOS/nixpkgs/pull/82743!
