### ISSUE TITLE
kde taskbar not working

### ISSUE THREAD

**Issue by alper-han** [NixOS/nixpkgs#365920]
The processes opened on the Taskbar do not appear at all when I use wayland.
So I find it a bit more difficult to keep track of windows or switch between windows.

I last updated 2 weeks ago and this problem was not there.
The problem seems to be only on the wayland side. When I try with X11 this problem is not present.

Something in the last 2 weeks related to kde or wayland must have triggered this.

Nothing has changed on my side.
I am sharing my old flake.lock file and my current flake file

![Screenshot_20241217_180759](https://github.com/user-attachments/assets/18c5b59b-f8a6-46ab-b921-e786bad98904)

[locks.zip](https://github.com/user-attachments/files/18167494/locks.zip)

**Comment by tarneaux** [comment]
This doesn't really seem to be a Nix-specific issue. Please close this issue and file a bug report in the KDE issue tracker, providing the package versions.

Also avoid using full-caps titles for your issues, this just annoys people and doesn't make them want to respond to you more.

**Comment by tarneaux** [comment]
Thanks ! As a bonus, consider adding the KDE bug report link here in case someone else has the same issue and ends up here through web search results.
