### ISSUE TITLE
Build failure: tremor-rs

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#365909]
## Steps To Reproduce

1. build `tremor-rs` on staging-next (didn't try master)

## Build log

<details>

<summary>Build Log</summary>

```
error: elided lifetime has a name
    --> tremor-script/src/lexer.rs:1347:36
     |
807  | impl<'input> Lexer<'input> {
     |      ------ lifetime `'input` declared here
...
1347 |         F: Fn(Cow<'input, str>) -> Token,
     |                                    ^^^^^ this elided lifetime gets resolved as `'input`
     |
note: the lint level is defined here
    --> tremor-script/src/lib.rs:16:9
     |
16   | #![deny(warnings)]
     |         ^^^^^^^^
     = note: `#[deny(elided_named_lifetimes)]` implied by `#[deny(warnings)]`

error: elided lifetime has a name
    --> tremor-script/src/lexer.rs:1441:36
     |
807  | impl<'input> Lexer<'input> {
     |      ------ lifetime `'input` declared here
...
1441 |         F: Fn(Cow<'input, str>) -> Token,
     |                                    ^^^^^ this elided lifetime gets resolved as `'input`

error: could not compile `tremor-script` (lib) due to 2 previous errors
```

</details>

## Notify maintainers

@happysalada @akshatagarwl 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
Probably the fix is really simple: nuke `#![deny(warnings)]`

**Comment by happysalada** [comment]
Thank you for reporting. If you have time for a PR dont hesitate.
