### ISSUE TITLE
Build failure: sioyek on darwin (issue in QT dependencies?)

### ISSUE THREAD

**Issue by b-fein** [NixOS/nixpkgs#366069]
## Steps To Reproduce

1. build *sioyek*

## Build log

<details>

<summary>Build Log</summary>

```
       > /nix/store/l8n4jk7l60yb7jag3i17bz57s7rvf0rd-clang-wrapper-16.0.6/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch arm64 -isysroot /nix/store/bbwmxj5wv6nh3cydiyijp80zn30q5svf-apple-sdk-11.3/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11 -o sioyek.app/Contents/MacOS/sioyek  TouchSlider.o TouchCheckbox.o TouchListView.o TouchCopyOptions.o TouchRectangleSelectUI.o TouchRangeSelectUI.o TouchPageSelector.o TouchConfigMenu.o TouchTextEdit.o TouchSearchButtons.o TouchDeleteButton.o TouchHighlightButtons.o TouchSettings.o TouchAudioButtons.o TouchMarkSelector.o TouchDrawControls.o TouchMacroEditor.o TouchGenericButtons.o TouchMainMenu.o book.o config.o database.o document.o document_view.o input.o main.o main_widget.o pdf_renderer.o pdf_view_opengl_widget.o checksum.o new_file_checker.o coordinates.o sqlite3.o ui.o path.o utils.o mysortfilterproxymodel.o RunGuard.o OpenWithApplication.o fzf.o synctex_parser.o synctex_parser_utils.o macos_specific.o qrc_resources.o moc_TouchSlider.o moc_TouchCheckbox.o moc_TouchListView.o moc_TouchCopyOptions.o moc_TouchRectangleSelectUI.o moc_TouchRangeSelectUI.o moc_TouchPageSelector.o moc_TouchConfigMenu.o moc_TouchTextEdit.o moc_TouchSearchButtons.o moc_TouchDeleteButton.o moc_TouchHighlightButtons.o moc_TouchSettings.o moc_TouchAudioButtons.o moc_TouchMarkSelector.o moc_TouchDrawControls.o moc_TouchMacroEditor.o moc_TouchGenericButtons.o moc_TouchMainMenu.o moc_main_widget.o moc_pdf_renderer.o moc_ui.o moc_mysortfilterproxymodel.o moc_RunGuard.o moc_OpenWithApplication.o   -F/nix/store/y49q5fdmygz3jpwzxlrh0khqismcx89q-qtdeclarative-6.8.0/lib -F/nix/store/3la8b8fg6s9awj2adhqm1zvcq7v6jyyv-qtbase-6.8.0/lib -F/nix/store/sxnj63iybx2307i0mha8qm7yrn8n7kbm-qt3d-6.8.0/lib -F/nix/store/a2bdag3c252mn9ayny15c78991n2q26i-qtsvg-6.8.0/lib -F/nix/store/mb907xjzb0y16720qbj4a9aw4hsxpl8d-qtspeech-6.8.0/lib -F/nix/store/azzryfg5p4hfrpp2f33xr9zfa8lp4zcv-qtmultimedia-6.8.0/lib -ldl -L/private/tmp/nix-build-sioyek-2.0.0-unstable-2024-09-29.drv-0/source/mupdf/build/release -lmupdf -lgumbo -lharfbuzz -lfreetype -ljbig2dec -ljpeg -lopenjp2 -lz -framework QtQuickWidgets -framework QtQuick -framework QtOpenGLWidgets -framework QtOpenGL -framework QtWidgets -framework Qt3DInput -framework Qt3DCore -framework QtSvg -framework QtTextToSpeech -l/nix/store/azzryfg5p4hfrpp2f33xr9zfa8lp4zcv-qtmultimedia-6.8.0/lib/QtMultimedia.framework/Versions/A/QtMultimedia -framework QtMultimedia -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtQmlMeta -framework QtQmlModels -framework QtQmlWorkerScript -framework QtQml -framework QtNetwork -framework QtConcurrent -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL
       > ld: warning: directory not found for option '-L/private/tmp/nix-build-sioyek-2.0.0-unstable-2024-09-29.drv-0/source/mupdf/build/release'
       > ld: library not found for -l/nix/store/azzryfg5p4hfrpp2f33xr9zfa8lp4zcv-qtmultimedia-6.8.0/lib/QtMultimedia.framework/Versions/A/QtMultimedia
```

</details>

## Additional context

In #348045 there already has been some investigation regarding this issue. The Qmake project files for QtSpeech seem to pull in QtMultimedia for linking with an unnecessary `-l` argument.

https://github.com/NixOS/nixpkgs/pull/348045#issuecomment-2487411929 (`@booxter`)

> The immediate failure comes from the fact that the QtMultimedia framework is passed as: `-l/nix/store/nc8h7dspiyybxfd03g2iysnnr3iycc8j-qtmultimedia-6.8.0/lib/QtMultimedia.framework/Versions/A/QtMultimedia -framework QtMultimedia` and I think only the `-framework` is needed (I was able to link the file once I remove the `-l` argument from `Makefile`).
> 
> I think this `-l` argument comes from `/nix/store/5sb3jk5jagkx0lhj0szi1xj19scmgcbr-qtspeech-6.8.0/lib/QtTextToSpeech.framework/Resources/QtTextToSpeech.prl` or some other `prl` file
>
> […] Someone with some knowledge around `qmake` may have some insight...

## Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/g9bw874w67bfsvg93szwnxxjxp4lphby-source`

## Notify maintainers

@xyven1 @stephen-huan 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pitkling** [comment]
I investigated this and found what's causing the problematic `-l` argument in `/nix/store/5sb3jk5jagkx0lhj0szi1xj19scmgcbr-qtspeech-6.8.0/lib/QtTextToSpeech.framework/Resources/QtTextToSpeech.prl`. See my draft PR #348045 for details and a potential fix.

**Comment by pitkling** [comment]
The PR with the fix got merged and is currently in `staging` ([status](https://nixpk.gs/pr-tracker.html?pr=367206)) and backported to `staging-24.11` ([status](https://nixpk.gs/pr-tracker.html?pr=369629)), so I'm closing this.

**Comment by b-fein** [comment]
Thank you!
