### ISSUE TITLE
ceph-mgr dashboard module is missing one or more python dependencies and fails to run

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#36622]
## Issue description
```
  File "/nix/store/dvii6vvlq00pn6l2zza42ambbdxm9q41-ceph-12.2.2-lib/lib/ceph/mgr/dashboard/__init__.py", line 2, in <module>
    from module import *  # NOQA
  File "/nix/store/dvii6vvlq00pn6l2zza42ambbdxm9q41-ceph-12.2.2-lib/lib/ceph/mgr/dashboard/module.py", line 27, in <module>
    import cherrypy
ImportError: No module named cherrypy
```

### Steps to reproduce
Enable and provision ceph and a mgr daemon.

## Technical details
Ran on a modified nixos-unstable

**Comment by srhb** [comment]
@lejonet Race you. :-)

**Comment by lejonet** [comment]
Hehe, simple fix ;) and the steps to reproduce should include "enable dashboard module" because iirc it isn't enabled by default :)

**Comment by lejonet** [comment]
@srhb https://github.com/lejonet/nixpkgs/tree/ceph-%2336622 solves the issue ^^

**Comment by srhb** [comment]
Oh, I see. I was converting an old cluster, and of course the dashboard was enabled there. Sorry! :-)

**Comment by lejonet** [comment]
Iirc this was merged and resolved the 27th of March when @Mic92 merged my commit, so I'm closing this issue so that stalebot is happy
