### ISSUE TITLE
Package request: PhotoDemon Photo Editor

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#366201]
Please add PhotoDemon

A free portable photo editor focused on pro-grade features, high performance, and maximum usability.

Links:

https://github.com/tannerhelland/PhotoDemon

https://photodemon.org/

**Comment by pluiedev** [comment]
Isn't this Windows only?

**Comment by boustanihani** [comment]
Sorry you are absolutely right!

**Comment by pluiedev** [comment]
You can always use Wine, though ;)
