### ISSUE TITLE
Option to create shell.nix from nix-shell arguments

### ISSUE THREAD

**Issue by wchresta** [NixOS/nixpkgs#36634]
It is very easy to initiate a nix-environment through `nix-shell` that has a given set of derivations active. This is relatively easy to understand for new users and use right away. There are also a lot of tips and comments that rely on `nix-shell`'s arguments.

The step from giving a derivation name in the command line (`nix-shell -p python37`) to creating a well formatted `shell.nix` is not small. It would be helpful for new users if there was an option or command for the `nix-shell` command that turns the current arguments into an equivalent `shell.nix` that has the same effect.

That way, a user can not only quickly recreate a previous environment, but can also learn how shell.nix files are supposed to look like and how packages and environment are connected together. This can be seen as both, a quality of life feature, as well as a mini-tutorial for nix-derivations.

Example:
```
$ nix-shell -p "haskellPackages.ghcWithPackages (p: [p.lens p.JuicyPixels])"
[environment with ghc and lens, JuicyPixels]
$ nix-shell init -p "haskellPackages.ghcWithPackages (p: [p.lens p.JuicyPixels])"
Created shell.nix. You can use nix-shell without arguments now.
$ cat shell.nix
# nix-shell init -p "haskellPackages.ghcWithPackages (p: [p.lens p.JuicyPixels])"
{ pkgs ? import <nixpkgs> {} }:
with pkgs;

stdenv.mkDerivation rec {
  name = "env";
  buildInputs = [ (haskellPackages.ghcWithPackages (p: [p.lens p.JuicyPixels]))
                ];
}
$ nix-shell
[environment with ghc and lens, JuicyPixels]
```

```

**Comment by dtzWill** [comment]
Internally `nix-shell` generates an expression *anyway*, and while it may not be formatted "ideally" this seems like a straightforward option to add.

**Comment by FRidh** [comment]
This is a feature request for the Nix package manager and so an issue should be made there.

**Comment by wchresta** [comment]
https://github.com/NixOS/nix/issues/1967
