### ISSUE TITLE
Cannot use linuxPackages.nvidiaPackages.production due to misspelling "ssha256"

### ISSUE THREAD

**Issue by rlad78** [NixOS/nixpkgs#366350]
## Describe the bug

A recent commit fc1f9fe updated the production nvidia driver to 550.142, but the `persistencedSha256` attribute has a misspelling for sha256 that causes an error when trying to build a system using the driver.

```nix
    persistencedSha256 = "ssha256-yQFrVk4i2dwReN0XoplkJ++iA1WFhnIkP7ns4ORmkFA=";
```

## Steps To Reproduce

1. Configure a NixOS system to use `linuxPackages.nvidiaPackages.production` for its nvidia driver package.
2. Attempt to build the system.
3. Observe the follow error message:

```
 … while evaluating definitions from `/nix/store/563952p6ih60l9v31jkdkd2d1qayd3d2-source/nixos/modules/hardware/video/nvidia.nix':

 error: unknown hash algorithm 'ssha256', expect 'md5', 'sha1', 'sha256', or 'sha512'
```

## Expected behavior

The nvidia driver should build properly

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.57, NixOS, 24.11 (Vicuna), 24.11.20241017.b5cd423`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/7z1d5gzwhjxn9xx8d32pcak33pfyisk0-source`
 ```

## Notify maintainers

@Kiskae

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
You can temporarily use the `mkDriver` helper with the corrected hashes, until the fix reaches unstable.
