### ISSUE TITLE
opentabletdriver.fetch-deps crashes

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#366372]
## Describe the bug

Running `opentabletdriver.fetch-deps` script crashes after https://github.com/NixOS/nixpkgs/pull/362278

## Steps To Reproduce

1. checkout master (12e3af0008337ca2117950b4048364ce2292fdb9)
2. `$(nix-build -A opentabletdriver.fetch-deps)`
3. observe error: `/nix/store/vszbrq40jq530xf3022j9zwjanmpgc9d-wrap-gapps-hook/nix-support/setup-hook: line 31: !v: unbound variable`

## Expected behavior

No crash

## Additional context

Bisected to c94c5087cc19cc8339e2c4b3e7a1546f6e990fcc. Most likely only a few packages are affected that are using `wrapGAppsHook3`, no issues with for example `vrcadvert.fetch-deps` or `tone.fetch-deps`.

## Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-zen1, NixOS, 25.05 (Warbler), 25.05.20241213.3566ab7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/gep/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/gep/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/gep/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/gep/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/smghprxmwyp707kqljlm4fsxm7h5wd72-lix-2.91.1/share`
 - nixpkgs: `/nix/store/22r7q7s9552gn1vpjigkbhfgcvhsrz68-source`
```

## Notify maintainers

@GGG-KILLER 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
Applying this on master "fixes" this:
```diff
diff --git a/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh b/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
index 809f5c4b26d8..c65b666d9d9f 100644
--- a/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
+++ b/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
@@ -1,5 +1,5 @@
 # shellcheck shell=bash
-set -euo pipefail
+set -eo pipefail
 
 export PATH="@binPath@:$PATH"
```

I guess `wrapGAppsHook3` script needs to handle undefined variables in a better way.

**Comment by GGG-KILLER** [comment]
Oh, my bad, I thought that was something that was already happening on master.
Didn't notice that my changes caused it, I'll get a PR up ASAP.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/366556
