### ISSUE TITLE
nixos/ntpd: permission denied error

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#366475]
## Describe the bug

My `journalctl` reports every couple of hours:

```
ntpd[1158]: frequency file /var/lib/ntp/ntp.drift.TEMP: Permission denied
```

It doesn't give the error immediately when starting up but at integer intervals of an hour some time after that.

The `/var/lib/ntp` directory exists, but is owned by `root:root` and does not have write permissions for anyone but the `root` user.
The `ntpd` process is run by user `ntp`.

Note, my root partition gets reset after every reboot, so `/var/lib` and anything below it is freshly created.

## Steps To Reproduce

Have `services.ntp.enable = true;` with `nixpkgs` at https://github.com/NixOS/nixpkgs/commits/d3c42f187194c26d9f0309a8ecc469d6c878ce33, although I only noticed this just now and looking back through the logs it starts happening from October 28 onwards.

## Expected behavior

`ntpd` can create its required files.

## Metadata

```
 - system: `"aarch64-linux"`
 - host os: `Linux 6.6.51, NixOS, 25.05 (Warbler), 25.05.20241217.d3c42f1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs`
```

## Notify maintainers

@pyrox0, given the timing and the symptoms, I suspect https://github.com/NixOS/nixpkgs/pull/349633 might be related?

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
I also have an impermanence setup but can't seem to replicate this. I set the system time to an incorrect time, and it readjusted as expected after a while without error. The only thing I have in my setup (which you might not) is that I've got `/var/lib` on it's own btrfs subvolume, so it isn't deleted on boot.

**Comment by chewblacka** [comment]
Oops, I wasn't waiting long enough. Here it is:

    ntpd[917]: frequency file /var/lib/ntp/ntp.drift.TEMP: Permission denied

**Comment by SFrijters** [comment]
Thanks for checking again! I don't think I was very clear in my report - it doesn't give the error when starting up but at integer intervals of an hour some time after that.
