### ISSUE TITLE
rustdesk-server: Maintainer emails not working

### ISSUE THREAD

**Issue by kwinz** [NixOS/nixpkgs#366542]
## Describe the bug

The [rustdesk-server](https://search.nixos.org/packages?channel=unstable&show=rustdesk-server&from=0&size=50&sort=relevance&type=packages&query=rustdesk-server) package lists two maintainers.

The masqt.com domain email of Theodore does not have any MX entries so no emails can be delivered. This email should be removed or updated. And Gaël hasn't responded to two emails over more than 3 weeks.

It seems like the package maintainers are unavailable via the email address associated with the package.

## Expected behavior

I can reach the maintainers.

## Notify maintainers

@tjni @gaelreyrol

**Comment by gaelreyrol** [comment]
This is not how you are supposed to use issues and reach us through emails for such a demand is irrelevant. I am not at your disposal especially when your request is not about a problem with the derivation itself.

**Comment by kwinz** [comment]
So what is the proper way to report issues with this derivation's metadata, such as when the supposed maintainer email address' inbox simply doesn't exist?


From the public nix-env record:

```
 nix-env -qaP rustdesk-server --meta --json
{
  "nixos.rustdesk-server": {
[...]
      "maintainers": [
        {
          "email": "me@gaelreyrol.dev",
          "github": "gaelreyrol",
          "githubId": 498465,
          "keys": [
            {
              "fingerprint": "3492 D8FA ACFF 4C5F A56E  50B7 DFB9 B69A 2C42 7F61"
            }
          ],
          "matrix": "@Zevran:matrix.org",
          "name": "Gaël Reyrol"
        },
        {
          "email": "43ngvg@masqt.com",
          "github": "tjni",
          "githubId": 3806110,
          "keys": [
            {
              "fingerprint": "4384 B8E1 299F C028 1641  7B8F EC30 EFBE FA7E 84A4"
            }
          ],
          "matrix": "@tni:matrix.org",
          "name": "Theodore Ni"
        }
      ],
}
```

There is no 43ngvg@masqt.com. Sorry for taking your time, I tired to resolve this over Matrix chat before but didn't receive any replies.
