### ISSUE TITLE
nixos-rebuild: support `doas`

### ISSUE THREAD

**Issue by hauskens** [NixOS/nixpkgs#366527]
## Describe the bug

Running on a system where sudo is disabled and replaced with doas.
It is not possible to run nixos-rebuild with `--use-remote-sudo` without having the `doas-sudo-shim` package installed.
This works fine if `doas-sudo-shim` is installed.

```
nixos-rebuild test --flake .# --use-remote-sudo 
building the system configuration...
/nix/store/qj5gxld272jprjdvf83mp1ca5y211nvd-nixos-rebuild/bin/nixos-rebuild: line 218: sudo: command not found
/nix/store/qj5gxld272jprjdvf83mp1ca5y211nvd-nixos-rebuild/bin/nixos-rebuild: line 218: sudo: command not found
warning: error(s) occurred while switching to the new configuration
```

## Steps To Reproduce

 1. Disable sudo and enable doas with `security.sudo.enable = false` and `security.doas.enable = true`.
 2. Make sure `doas-sudo-shim` is **not** installed
 3. Run `nixos-rebuild` with `--use-remote-sudo`

## Notify maintainers
@Profpatsch `nixos-rebuild`

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by hauskens** [comment]
@thiagokokada 
FYI, Similar issue can be found on the new `nixos-rebuild-ng` package:
```
nixos-rebuild-ng test --flake .# --sudo                                 
building the system configuration...
[Errno 2] No such file or directory: 'sudo'
```

**Comment by Atemu** [comment]
Well yes, --use-remote-***sudo*** isn't going to work if you have no sudo.

This is a feature request, not a bug. If a shim already exists, I don't really see all that much point in adding complexity here however?

**Comment by hauskens** [comment]
Apologies, this is for sure a feature request, not a bug. 

Using `doas` has mostly worked fine for me over the years apart from some few cases where the shim is needed. 
Since the shim works fine as a workaround i agree its probably not worth adding any complexity. 


I would just like to point out that some projects provide a way for user to define what command to run for elevating the privileges. Such as in [deploy-rs](https://github.com/serokell/deploy-rs), you can set the option `sudo = "doas -u";`.
I'm guessing that approach would potentially support future users of systemd [run0](https://www.freedesktop.org/software/systemd/man/256/run0.html) too, but it's a really niche use case.

**Comment by Atemu** [comment]
Given how simple the interface for `sudo` is and how ubiquitous its usage is for purposes of privilege escalation is; anyone not using the `sudo` implementation will probably have to use the shim anyways at some point.
