### ISSUE TITLE
Nixos-unstable: Nerd fonts characters are blank in pkgs.nerd-fonts.jetbrains-mono

### ISSUE THREAD

**Issue by jkoking** [NixOS/nixpkgs#366979]
## Describe the bug
pkgs.nerd-fonts.jetbrains-mono is broken the characters added by nerd fonts to the jetbrains mono font do not appear.

## Steps To Reproduce

1. add pkgs.nerd-fonts.jetbrains-mono to your environment.
2. Change font to jetbrains mono nerd font in your terminal or text editor of choice.
3. Attempt to view a nerd fonts exclusive character

## Expected behavior
The nerd fonts characters should be a part of pkgs.nerd-fonts.jetbrains-mono 

## Screenshots

What my prompt looks like when using nixos unstable
![Screenshot_20241220_193241](https://github.com/user-attachments/assets/29606cae-7fa7-415a-9390-d2d06fb0fe56)

What my prompt looks like when using nixos 24-11
![Screenshot_20241220_204245](https://github.com/user-attachments/assets/9307b127-0daf-4809-8586-3634c7192460)

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5, NixOS, 25.05 (Warbler), 25.05.20241217.d3c42f1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/6zgbbqlr7nnfxpzkyj7fsl4fpg89jbw0-source`

## Notify maintainers
@doronbehar 
@rc-zb

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by extrange** [comment]
Just to add, Gnome Console cannot display any Nerd Font: 
![image](https://github.com/user-attachments/assets/84221fa3-6745-4e74-b222-fe5d58da6b79)

VSCode is able to however (`"terminal.integrated.fontFamily": "'JetBrainsMonoNL Nerd Font', 'Courier New', monospace",`)
![image](https://github.com/user-attachments/assets/04276e05-3813-4456-ad6a-44e0eb565859)

**Comment by jkoking** [comment]
Originally two programs that I tried and wouldn't display nerd fonts on the unstable branch were konsole and vscodium. Now konsole has decided that it will load the nerd fonts but vscodium still won't, but it will if I switch back to stable. This whole thing is just so bizarre.

**Comment by deepanchal** [comment]
I can confirm that running `fc-cache -rf` fixes the issue. My broken jetbrains fonts in alacritty, waybar, & anyrun were fixed by running that cmd. Thanks!

**Comment by normalcea** [comment]
- https://wiki.nixos.org/wiki/Fonts

> add pkgs.nerd-fonts.jetbrains-mono to your environment.

Simply adding font packages to `environment.systemPackages` isn't enough for them to show up in applications and they should be put in the `font.packages` option instead in the NixOS configuration.

**Comment by doronbehar** [comment]
I'm closing as this is clearly a support request and not an issue with Nixpkgs. Thanks for everyone that offered their help.
