### ISSUE TITLE
Immich not able to be acessed outside the localhost

### ISSUE THREAD

**Issue by Kidplayer666** [NixOS/nixpkgs#366934]
## Describe the bug

Despite setting the services.immich.openFirewall option to true, the port to 2283 to true, I am unable to access immich anywhere outside the host itself. Other services like jellyfin do work correctly, and I am able to use it on my laptop for example.

## Steps To Reproduce

this is the config i am using. Jellyfin does correctly show up on other machines, it is just immich that is failing
```
  services={
	immich={
	    enable=true;
	    mediaLocation="/mnt/discobackup/Immich/Library/";
	    openFirewall=true;
	    port=2283;
            host="localhost";
	};
	jellyfin={
		enable=true;
		openFirewall=true;
		user="someuser";
		dataDir="somewhere";
		configDir="somewhere/config";
		cacheDir="somewhere/cache";
	};
  };
  networking.firewall = {
	enable = true;
	allowedTCPPorts = [ 8096 2283 ];
	allowedUDPPortRanges = [
		{ from = 2000; to = 3000; }
		{ from = 8000; to = 8200; }
	];
  };
```

## Expected behavior
I was supposed to easily be able to access my Immich server on my local network but i do not seem to be able to do so
I also attempted to set the firewall manually but to no avail. 

## Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.66, NixOS, 25.05 (Warbler), 25.05beta723344.d3c42f187194`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/home/someuser/.nix-defexpr/channels/nixpkgs`

## Notify maintainers
@jvanbruegge

**Comment by fsnkty** [comment]
neither I or the other user you've mentioned seem to be maintainers for either the immich service module or package.

could you please explain why you've mentioned me.

**Comment by Kidplayer666** [comment]
Sorry, made a big mistake, will correct now. Clicked a jellyfin link instead of immich and did not realise it

**Comment by Razboy20** [comment]
@Kidplayer666 rather than host="localhost", use host="0.0.0.0".

**Comment by Kidplayer666** [comment]
> @Kidplayer666 rather than host="localhost", use host="0.0.0.0" to have Immich bind to all addresses.

Solved. Will close
