### ISSUE TITLE
Update request: mesa 24.2.6 → 24.3.2

### ISSUE THREAD

**Issue by MrGeniusProgrammer** [NixOS/nixpkgs#367049]
## Package Information

https://www.mesa3d.org/

- Package name: mesa
- Latest released version: 24.3.2
- Current version on the unstable channel: 24.2.6
- Current version on the stable/release channel: 24.2.6

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@K900 
@primeos 
@vcunat 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Already in staging-next.
