### ISSUE TITLE
qtwebengine is not being built with proprietary codecs

### ISSUE THREAD

**Issue by vonpost** [NixOS/nixpkgs#36729]
## Issue description
When building qtwebengine the proprietary codecs are disabled, even though in the `../qt-5/modules/qtengine.nix` file they are supposed to be enabled. 

Possible cause is this: http://code.qt.io/cgit/qt/qtwebengine.git/tree/dist/changes-5.10.0/?h=v5.10.0#n29
In other words the WEBENGINE_CONFIG interface has been removed in Qt 5.10 and according to the documentation the new method is to use `./configure` with `-proprietary-codecs`. 

### Steps to reproduce
Build qtwebengine from nixpkgs and then the configuration output will say

`Proprietary codecs ................................ no`

EDIT:

I can confirm that it was indeed the `WEBENGINE_CONFIG+=use_proprietary_codecs` that is the problem, it no longer exists. 

I managed to solve this by letting changing the `qmakeFlag=["-- -proprietary-codec"];` in `qtwebengine.nix`, but before I had to change the position of the flags in the mkDerivation as well since none of the `CONFIG+=<option>` can come after the flag. As I am fairly new to NixOS as well as not quite understanding the structure of the Qt modules I won't be making a pull request, but if someone else wants to use my hack you can find it here https://github.com/vonpost/nixpkgs/commit/94c2c9b9c5d14fff7c73159a40998752039d3f4d which should suffice until someone who actually knows what they are doing can fix this.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by laMudri** [comment]
Where did you find out that the answer was to add `-- -proprietary-codecs`? I'm trying to understand, in particular, what the `--` does, because this solution feels like doing an injection attack inside our own code :-S. @ttuegel, do you happen to know this sort of stuff about qtmake?

**Comment by vonpost** [comment]
I was just following the way it was done in the Arch AUR package for qtwebengine when they moved to Qt 5.10, you can see it here: https://git.archlinux.org/svntogit/packages.git/diff/trunk/PKGBUILD?h=packages/qt5-webengine&id=7b5e4be8076c2f4bbdb1343227c2ace9159e91ac

My interpretation is that usually qmake is configured prior to building and `--` enables adding configuration options at the moment of building (these are not interpreted as the normal options of qmake, which mostly are variable assignments like `WEBENGINE+=<option>`

**Comment by The-Compiler** [comment]
IIRC most distributions do that combined with using system-ffmpeg.

Examples:

- [Debian](https://salsa.debian.org/qt-kde-team/qt/qtwebengine/blob/master/debian/rules#L35-36)
- [Archlinux](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-webengine#n51)

**Comment by matthewbauer** [comment]
Ok thanks!

**Comment by Enzime** [comment]
I made a pull request already at #38606 which doesn't involve changing the `mkDerivation.nix` file just the `qtwebengine.nix`
