### ISSUE TITLE
Graphics corruption using amd gpu on kernel 6.12.x

### ISSUE THREAD

**Issue by dhwisema** [NixOS/nixpkgs#367298]
## Describe the bug

rainbow color artifacting randomly flashing up on screen

## Steps To Reproduce

hardware rx 6500m and rx 680m gpus and ryzen 9 6950 h processor

1.Use kernel 6.12.x
2. login to desktop
3. use device as normal flashing should start within a few minutes

## Expected behavior

no artifacting
## Screenshots

![IMG_0748](https://github.com/user-attachments/assets/f4030f02-4da3-4c69-a8c7-30dd76b0861e)

## Additional context

happens across gnome and kde so far and reverting to the latest lts kernel in the repo version 6.6.6 fixes the issue

## Metadata

howard@laptop ~> nix-shell -p nix-info --run "nix-info -m"
fetching path input 'path:/nix/store/b8l3ndracmly9kyylawrnk32lsrjfy3j-source'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5, NixOS, 24.11 (Vicuna), 24.11.20241220.1c6e20d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/howard/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/howard/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/howard/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/howard/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/howard/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/store/886qfi98h8b91lqdjf2nzxyqa3lnv8hl-gnome-settings-daemon-47.1/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/5fpjpa356qcpljidymbalqxq47yjp9lm-lix-2.91.1/share`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/b8l3ndracmly9kyylawrnk32lsrjfy3j-source`

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by xinyifly** [comment]
I would like to raise this issue because I suffer from some flicking issue on `AMD Ryzen 7 8840HS w/ Radeon 780M Graphics` , too. Occasionally when I'm visiting some pages in Firefox. And I already have 

```nix
{
  boot.kernelParams = [ "amdgpu.dcdebugmask=0x10" ];
}
```

But I think it's more of a driver issue that should be discussed in https://gitlab.freedesktop.org/drm/amd and there is a lot of discussions about this issue. Though it's not completely solved yet.

I don't know if nixpkgs will have any solution for this, especially for this issue occurs occasionally.

For me, reverting to Linux 6.6 is not an option because my `MEDIATEK Corp. Device 7925` requires at least Linux 6.8 to work.

**Comment by Atemu** [comment]
This does not sound like anything related to Nixpkgs. Please report and discuss this upstream.
