### ISSUE TITLE
Update request: local-ai 2.23.0 → 2.24.2

### ISSUE THREAD

**Issue by Kezerber** [NixOS/nixpkgs#367394]
## Package Information

- Package name: local-ai
- Latest released version: 2.24.2
- Current version on the unstable channel: 2.23.0
- Current version on the stable/release channel: 2.22.1

## Update Overview
- Backend deprecation: We’ve removed rwkv.cpp and bert.cpp, replacing them with enhanced functionalities in llama.cpp for simpler installation and better performance.
- New Backends Added: Introducing bark.cpp for text-to-audio and stablediffusion.cpp for image generation, both powered by the ggml framework.
- Voice Activity Detection (VAD): Added support for silero-vad to detect speech in audio streams.
- WebUI Improvements: Now supports API key authentication for enhanced security.
- Real-Time Token Usage: Monitor token consumption during streamed outputs.
- Expanded P2P Settings: Greater flexibility with new configuration options like listen_maddrs, dht_announce_maddrs, and bootstrap_peers.

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@onny @ck3d

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ck3d** [comment]
I add build type vulkan in a separate PR
