### ISSUE TITLE
nixpkgs Version of prismlauncher can't see libraries located in The mods directory

### ISSUE THREAD

**Issue by jkoking** [NixOS/nixpkgs#367452]
## Describe the bug
As near as I can tell the mod mcef downloads or contains operating system and architecture specific libraries. which then places in minecraft/mods/mcef-libraries/os_architecture after that the needed files are loaded using the Java method System.load

## Steps To Reproduce

1..Install the star technologies! Modpack from course forge
2.  Launch it.
3.  The game will crash after clicking continue on the enable narrator screen.

## Expected behavior

An instance should be able to load system binaries/libraries located in its own Minecraft folder

## Additional context

Function the mod crashes on https://github.com/CinemaMod/java-cef/blob/d5e3cece98755ff1e5af39261e6a486a5d9adb5d/java/org/cef/CefApp.java#L452

Specific mcef version source code: https://github.com/CinemaMod/mcef/tree/508c82e595c31eeb01e06d7f4b6aec6fa67aa29a

CinemaMod/java-cef is a sub module of mcef

## Metadata

- system: `"x86_64-linux"`
 - host os: `Linux 6.12.5, NixOS, 25.05 (Warbler), 25.05.20241217.d3c42f1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/6zgbbqlr7nnfxpzkyj7fsl4fpg89jbw0-source`

## Notify maintainers

@Minion3665
@Scrumplex
@getchoo 

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
This is because the Prism Launcher derivation in Nixpkgs does not include all libraries required by CEF to work. 

You can either configure https://github.com/nix-community/nix-ld, or override Prism Launcher as [described here](https://wiki.nixos.org/wiki/Prism_Launcher#Advanced) to add all missing libraries.

You can use `ldd` on the .so file to figure out which libraries you need.

**Comment by jkoking** [comment]
I've already tried  `additionalLibs`, `additionalPrograms`, and nix-dl they don't work because the mod isn't reading `LD_LIBRARY_PATH` or PATH` https://github.com/CinemaMod/java-cef/blob/d5e3cece98755ff1e5af39261e6a486a5d9adb5d/java/org/cef/CefApp.java#L452

**Comment by Scrumplex** [comment]
It is using `System.load` which in turns will use `dlopen`. It will work if configured correctly. nix-ld might not work, as the Java binary will probably use its linked ld-linux.so over the system's `nix-ld`

**Comment by jkoking** [comment]
Thank you for your assistance. I completely misunderstood how nix-dl works. For anyone who needs to figure out what darevations provide, which libraries [nix-index](https://github.com/nix-community/nix-index) is incredibly useful.  `nix-locate --top-level -w  file_name`
