### ISSUE TITLE
gfortran fails to build

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#36754]
## Issue description

Continuation of #36642.

To summarize: `gfortran` fails to build on my sandboxed nixos machine. Both `gfortran6` and `gfortran7`, 64 and 32 bit fail. The build is using Nix2 and the nixpkgs checkout f8926fbcc9e. Here's the build log:
https://gist.github.com/anonymous/8ddd36ad6fcf2e7dda216391a7a383ae

### Steps to reproduce

Check out f8926b and run `nix-build --check -A gfortran.cc`. Since the build works on hydra and @7c6f434c's machine it might not be reproducible.

Pinging the maintainers @viric @peti.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-17.09.3129.1dcd022f01b, pkgs-unstable-18.03pre130569.7a04c2ca296, unstable-18.03pre130932.cc4677c36ee"`
 - channels(timo): `"unstable-18.03pre117327.3fe7cddc30"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

**Comment by FRidh** [comment]
Extra datapoint, I was able to build it just fine.

But...I've seen this before, when I was building Nix with a custom store location and the required sandbox paths were incorrect/missing.

**Comment by 7c6f434c** [comment]
In the name of Nix 2.0 magic, I have started a no-cache `gfortran6` build in an empty store.

**Comment by pbogdan** [comment]
Fails for me as well on NixOS 17.09 with nixStable2 build host. As an experiment I ran `patchShebangs` over the whole gcc tree which fixed things for me. Could it be the feature-limited sandbox `/bin/sh` on 17.09 triggering an issue again? Also doesn't explain why the same is working on Hydra...

Actually - checking again now it looks like `patchShebangs` on just the configure script is sufficient to at least start the build.

**Comment by 7c6f434c** [comment]
Ah right, `/bin/sh` in the sandbox has been changed back and forth multiple times. Could someone with access to a failing build try if `patchShebangs` is enough for the full build success?

**Comment by pbogdan** [comment]
Trying now with:

```diff
diff --git a/pkgs/development/compilers/gcc/6/default.nix b/pkgs/development/compilers/gcc/6/default.nix
index df0c1578dae..db835a7409c 100644
--- a/pkgs/development/compilers/gcc/6/default.nix
+++ b/pkgs/development/compilers/gcc/6/default.nix
@@ -317,7 +317,9 @@ stdenv.mkDerivation ({
 
   NIX_LDFLAGS = stdenv.lib.optionalString  hostPlatform.isSunOS "-lm -ldl";
 
-  preConfigure = stdenv.lib.optionalString (hostPlatform.isSunOS && hostPlatform.is64bit) ''
+  preConfigure = ''
+    patchShebangs configure
+ '' + stdenv.lib.optionalString (hostPlatform.isSunOS && hostPlatform.is64bit) ''
     export NIX_LDFLAGS=`echo $NIX_LDFLAGS | sed -e s~$prefix/lib~$prefix/lib/amd64~g`
     export LDFLAGS_FOR_TARGET="-Wl,-rpath,$prefix/lib/amd64 $LDFLAGS_FOR_TARGET"
     export CXXFLAGS_FOR_TARGET="-Wl,-rpath,$prefix/lib/amd64 $CXXFLAGS_FOR_TARGET"
```

**Comment by timokau** [comment]
That fixes it for me :+1: 

`gfortran7` probably needs the same patch, maybe other things based on `gcc`/`wrapCC` (I'm not sure how all these parts work together).

Why isn't `patchShebangs` run by default by the way?

**Comment by 7c6f434c** [comment]
Is there a PR that I can just merge?

**Comment by 7c6f434c** [comment]
(Ah, I see, not yet)

**Comment by dtzWill** [comment]
See #36919 , although again fixing dependence on `/bin/sh` is best.  But there's no reason for us to ship a known-broken /bin/sh in the meantime.

**Comment by timokau** [comment]
Since I haven't experienced any issues for quite some while, I'm assuming something (#36919?) fixed this.
