### ISSUE TITLE
yarnConfigHook fails on Darwin, works on Linux if HOME is not writable

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#367586]
## Describe the bug

Error is:
```
Executing yarnConfigHook
yarn config v1.22.22
warning Skipping preferred cache folder "/tmp/home/Library/Caches/Yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/private/tmp/nix-build-yao-pkg-6.1.1.drv-0/.yarn-cache-352".
error Error: EACCES: permission denied, open '/tmp/home/.yarnrc'
info Visit https://yarnpkg.com/en/docs/cli/config for documentation about this command.
```

## Steps To Reproduce

1. Try to build e.g. #362297

I have seen this in lots of packages.

## Expected behavior

Should just work.

## Notify maintainers

none listed

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by khaneliman** [comment]
Have a few packages that I can't build right now due to this. Created a PR that resolved it for me locally if you want to test it out.
