### ISSUE TITLE
make a better gnome dock experience 

### ISSUE THREAD

**Issue by sjhaleprogrammer** [NixOS/nixpkgs#367504]
## Describe the bug

certain apps create sub processes which messes with the gnome dock

## Steps To Reproduce

1. some apps create subprocesses 

list of packages that i know currently do this:
discord
virt-manager
rog-control-center
themechanger

## Expected behavior

to not separate like this  

## Screenshots

![image](https://github.com/user-attachments/assets/998b9b26-cc98-4b1c-92f4-717cc47562c5)

## Metadata

``` 
➜ ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5, NixOS, 24.11 (Vicuna), 24.11.20241220.1c6e20d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/b8l3ndracmly9kyylawrnk32lsrjfy3j-source`

 ```

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by llakala** [comment]
Where was this completed?

**Comment by sjhaleprogrammer** [comment]
@llakala 
i moved to here
https://github.com/NixOS/nixpkgs/issues/368029 
i did more research
