### ISSUE TITLE
Module request: zenoh

### ISSUE THREAD

**Issue by bachp** [NixOS/nixpkgs#367602]
## Description

Configure a zenoh router including some commonly used plugins like MQTT, Filesystem, Webserver, etc.

## Notify maintainers

@ck3d @markuskowa

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by markuskowa** [comment]
I have started experimenting with a module out-of-tree here: https://github.com/markuskowa/nix-system/blob/master/modules/zenoh.nix

It is not ready for upstream yet.
