### ISSUE TITLE
No way to overwrite / remove engines from searX/NG?

### ISSUE THREAD

**Issue by vfosnar** [NixOS/nixpkgs#367641]
## Describe the bug

Hi, I'm trying to limit the default engines in my SearXNG instance, but I can only change configuration of the default ones. The best option so far is to disable all of them one by one by default but that doesn't disable them on the server and still allows users to re-enable them from the UI.

## Expected behavior

Make inheriting default configuration optional or add option to override default lists in SearXNG configuration.

## Screenshots

What I want it to look like (screen from my non-nix server)

![image](https://github.com/user-attachments/assets/fce39a31-c08b-4283-9e9b-57b3664a1c79)

## Notify maintainers

@rnhmjoj @999eagle 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 13621** [comment]
Hi, can you share your configuration? I can successfully disable engines by setting `inactive = true`, like so:

```nix
services.searx = {
  enable = true;
  settings = {
    use_default_settings = true;
    engines = [
       {
           name = "google";
           inactive = true;
       }
    ];
  };
};
```

**Comment by vfosnar** [comment]
Oh, didn't know `inactive` was an option. Found [this](https://github.com/searxng/searxng/discussions/3696) and wrongly assumed that's the only way. Thank you for your time<3
