### ISSUE TITLE
GTK/QT themes section of manual is out of date

### ISSUE THREAD

**Issue by jacobdillon** [NixOS/nixpkgs#36771]
## Issue description

The [GTK/Qt themes section](https://nixos.org/nixos/manual/#idm140737316495440) of the wiki seems out of date - the `gtk` attribute for `qt5.qtbase` does not exist.

### Steps to reproduce

Try to put `qt5.qtbase.gtk` in systemPackages and do a `nixos-rebuild`, errors with "attribute 'gtk' missing".

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 17.09.3145.df691948987 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(jad): `""`
 - channels(root): `"nixos-17.09.3145.df691948987"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by bricewge** [comment]
This is a duplicate of #20017.
