### ISSUE TITLE
Package request: nixpkgs-review-checks

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#367706]
## Project description

Adds additional checks and more information from build logs and outputs to the reports generated by nixpkgs-review.

## Metadata

* homepage URL: https://github.com/SuperSandro2000/nixpkgs-review-checks
* source URL: https://github.com/SuperSandro2000/nixpkgs-review-checks
* license: mit
* platforms: all

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ben9986** [comment]
@SuperSandro2000

**Comment by SuperSandro2000** [comment]
That repo is abandonware. I request to not package it.
