### ISSUE TITLE
Build failure: awscli2

### ISSUE THREAD

**Issue by kha20240826** [NixOS/nixpkgs#367876]
## Steps To Reproduce

I'm not a nix expert just an user that use it in github action CI/CD using https://github.com/workflow/nix-shell-action

When trying to run this action with `awscli2` since today/yesterday I got a build failure

https://github.com/kha20240826/nix-gaction-awscli/actions/runs/12480564894/job/34831595489

Apparently it is due to some `flit-core` package upgrade not matching the `awscli` requirement

`flit_core (required: ('>=3.7.1', '<3.9.1')) (version installed: 3.10.0)`

## Build log

All logs are available here
https://github.com/kha20240826/nix-gaction-awscli/actions/runs/12480564894/job/34831595489

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arianvp** [comment]
Broken by https://github.com/NixOS/nixpkgs/pull/354627

cc @mweinelt

**Comment by mweinelt** [comment]
```patch
diff --git a/pkgs/by-name/aw/awscli2/package.nix b/pkgs/by-name/aw/awscli2/package.nix
index d5b0118bf66b..6a4df356ef15 100644
--- a/pkgs/by-name/aw/awscli2/package.nix
+++ b/pkgs/by-name/aw/awscli2/package.nix
@@ -74,6 +74,7 @@ py.pkgs.buildPythonApplication rec {
 
   postPatch = ''
     substituteInPlace pyproject.toml \
+      --replace-fail 'flit_core>=3.7.1,<3.9.1' 'flit_core>=3.7.1' \
       --replace-fail 'awscrt>=0.19.18,<=0.22.0' 'awscrt>=0.22.0' \
       --replace-fail 'cryptography>=40.0.0,<43.0.2' 'cryptography>=43.0.0' \
       --replace-fail 'distro>=1.5.0,<1.9.0' 'distro>=1.5.0' \
```

I have to run, but this gets rid of the build-system pin.

**Comment by arianvp** [comment]
Thanks I'll try this out
