### ISSUE TITLE
Build failure: libgit2

### ISSUE THREAD

**Issue by masklinn** [NixOS/nixpkgs#367930]
## Steps To Reproduce

1. build gitstatus on darwin (10.14)

Building gitstatus signals
```
these 2 derivations will be built:
  /nix/store/wqc4pnbcyf0q5qhxvfk6bsalhia4w4da-libgit2-1.8.4.drv
  /nix/store/d5y3gjl03852a5h7ry3z9pmk73zxl86d-gitstatus-1.5.5.drv
```
and tries to build libgit2 anew? `nix-shell -p libgit2` fetches prebuilt (?) libgit2.

## Build log

https://gist.github.com/masklinn/335678c70f2ff26aec7fae806021c95f

## Additional context

This occurs trying to build/install zsh-powerlevel10k on darwin.

## Metadata

 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.25.3`
 - nixpkgs: `/nix/store/73cnf2k7mji95fcflvay15pdw4skhhk5-source`

## Notify maintainers

@mmlb @Hexa @SuperSandro2000

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SuperSandro2000** [comment]
Probably due to the clang update. Please send patches, I don't have a darwin.

**Comment by paparodeo** [comment]
the issue is the bundled zlib
https://hydra.nixos.org/build/282258408/nixlog/3

this is probably reproducible on linux using clang.

the fix is to unbundle zlib from the libgit2.a and then link `-lz` to the thing that uses `libgit2.a`

```diff
diff --git a/pkgs/by-name/gi/gitstatus/package.nix b/pkgs/by-name/gi/gitstatus/package.nix
index cc6037d16c21..c1482035044d 100644
--- a/pkgs/by-name/gi/gitstatus/package.nix
+++ b/pkgs/by-name/gi/gitstatus/package.nix
@@ -4,6 +4,7 @@
   stdenv,
   fetchFromGitHub,
   git,
+  zlib,
   zsh,
   runtimeShell,
 }:
@@ -18,11 +19,19 @@ stdenv.mkDerivation rec {
     sha256 = "sha256-b+9bwJ87VV6rbOPobkwMkDXGH34STjYPlt8wCRR5tEc=";
   };
 
-  env = lib.optionalAttrs stdenv.hostPlatform.isDarwin {
-    NIX_LDFLAGS = "-liconv";
+  env = {
+    NIX_LDFLAGS = toString (
+      [
+        "-lz"
+      ]
+      ++ lib.optional stdenv.hostPlatform.isDarwin "-liconv"
+    );
   };
 
-  buildInputs = [ (callPackage ./romkatv_libgit2.nix { }) ];
+  buildInputs = [
+    zlib
+    (callPackage ./romkatv_libgit2.nix { })
+  ];
 
   postPatch = ''
     sed -i '1i GITSTATUS_AUTO_INSTALL=''${GITSTATUS_AUTO_INSTALL-0}' gitstatus.plugin.sh
diff --git a/pkgs/by-name/gi/gitstatus/romkatv_libgit2.nix b/pkgs/by-name/gi/gitstatus/romkatv_libgit2.nix
index 9881bd480406..e1feb240c7b1 100644
--- a/pkgs/by-name/gi/gitstatus/romkatv_libgit2.nix
+++ b/pkgs/by-name/gi/gitstatus/romkatv_libgit2.nix
@@ -5,7 +5,6 @@ libgit2.overrideAttrs (oldAttrs: {
     "-DBUILD_CLAR=OFF"
     "-DBUILD_SHARED_LIBS=OFF"
     "-DREGEX_BACKEND=builtin"
-    "-DUSE_BUNDLED_ZLIB=ON"
     "-DUSE_GSSAPI=OFF"
     "-DUSE_HTTPS=OFF"
     "-DUSE_HTTP_PARSER=builtin" # overwritten from libgit2
```

**Comment by SuperSandro2000** [comment]
Can you PR that fix? Thanks!

**Comment by paparodeo** [comment]
> Can you PR that fix? Thanks!

https://github.com/NixOS/nixpkgs/pull/368052
