### ISSUE TITLE
Build failure: pamtester

### ISSUE THREAD

**Issue by gautaz** [NixOS/nixpkgs#367911]
## Describe the bug

While trying to rebuild `xsecurelock` on [current master (8ed7c61)](https://github.com/NixOS/nixpkgs/commit/8ed7c6127ed61492bfff8225e0ca7b3aa67b5b18), I stumbled upon this:

```console
error: builder for '/nix/store/8q3klkach25sykiqxyah25zkfray0ipj-pamtester-0.1.2.drv' failed with exit code 2;
       last 25 log lines:
       > configure: creating ./config.status
       > config.status: creating Makefile
       > config.status: creating src/Makefile
       > config.status: creating doc/Makefile
       > config.status: creating doc/pamtester.1
       > config.status: creating config.h
       > config.status: executing default-1 commands
       > Running phase: buildPhase
       > build flags: SHELL=/nix/store/5mh7kaj2fyv8mk4sfq1brwxgc02884wi-bash-5.2p37/bin/bash
       > make  all-recursive
       > make[1]: Entering directory '/build/pamtester-0.1.2'
       > Making all in src
       > make[2]: Entering directory '/build/pamtester-0.1.2/src'
       > gcc -DHAVE_CONFIG_H -I. -I. -I..     -Wall -c app.c
       > gcc -DHAVE_CONFIG_H -I. -I. -I..     -Wall -c expr_parser.c
       > expr_parser.c: In function 'pamtester_expr_parser_hdlr':
       > expr_parser.c:87:31: error: implicit declaration of function 'strtol'; did you mean 'strtok'? [8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Wimplicit-function-declaration8;;]
       >    87 |                         val = strtol(token_val, &next_ptr, 10);
       >       |                               ^~~~~~
       >       |                               strtok
       > make[2]: *** [Makefile:167: expr_parser.o] Error 1
       > make[2]: Leaving directory '/build/pamtester-0.1.2/src'
       > make[1]: *** [Makefile:168: all-recursive] Error 1
       > make[1]: Leaving directory '/build/pamtester-0.1.2'
       > make: *** [Makefile:312: all-recursive-am] Error 2
       For full logs, run 'nix log /nix/store/8q3klkach25sykiqxyah25zkfray0ipj-pamtester-0.1.2.drv'.
error: 1 dependencies of derivation '/nix/store/pzhhg2vhyip76fjv6d8gml3xf6r00mzm-xsecurelock-1.9.0.drv' failed to build
```

Is this due to a recent modification of the C toolchain?

## Steps To Reproduce

1. Use the master branch ([8ed7c61](https://github.com/NixOS/nixpkgs/commit/8ed7c6127ed61492bfff8225e0ca7b3aa67b5b18)) of `nixpkgs`
2. execute `nix-shell -p pamtester`

## Expected behavior

`pamtester` package build should succeed.

## Screenshots

N/A

## Additional context

N/A

## Metadata

❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 25.05 (Warbler), 25.05.20241224.8ed7c61`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`

## Notify maintainers

@abbradar

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by anund** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/368792

**Comment by gautaz** [comment]
Fix confirmed, thanks @anund :slightly_smiling_face:
