### ISSUE TITLE
Update request: util-linux 2.39.4 → 2.40.2

### ISSUE THREAD

**Issue by hustlerone** [NixOS/nixpkgs#367921]
## Package Information

- Package name: util-linux
- Latest released version: 2.40.2
- Current version on the unstable channel: 2.39.4
- Current version on the stable/release channel: 2.39.4

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers
@infinisil

---

Note for maintainers: Please tag this issue in your PR.

---

2.40.2 has some nice fixes like x-mounts on bcachefs

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by infinisil** [comment]
I'm not the maintainer, I just touched it for a treewide change. Perhaps @rhelmot?
