### ISSUE TITLE
Update request: greetd.regreet 0.1.1 → 0.1.2

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#367908]
## Package Information

- Package name: greetd.regreet
- Latest released version: 0.1.2
- Current version on the unstable channel: 0.1.1
- Current version on the stable/release channel: 0.1.1

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@fufexan 
---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fufexan** [comment]
You said you checked the PRs?
https://github.com/NixOS/nixpkgs/pull/367520

**Comment by Mikilio** [comment]
Oops
