### ISSUE TITLE
Resend the invitation to join the org

### ISSUE THREAD

**Issue by axelkar** [NixOS/nixpkgs#367953]
Hi! I got the invitation on the 10th but didn't notice it. Could someone resend it?

**Comment by SigmaSquadron** [comment]
Hi! I've [asked the GitHub org owners on your behalf](https://matrix.to/#/!DMULJFTtTWdmyAxeLd:nixos.org/$pVvxXHrbduhHdO7VDUdcqtg88fwUH32heisfJeOnPRo?via=nixos.org); you should get a new invite soon. Thank you for contributing to Nixpkgs!
