### ISSUE TITLE
Option to unsubscribe from Hydra Build Daemon emails

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#36811]
## Issue description

I (and many others) get many emails from Hydra Build Daemon informing me that a package which I'm listed a maintainer of (or even in the dependency chain!) has broken, or gone from broken to working, but there is no way to unsubscribe from these emails! Many of these emails are caused by things which are out of my control; frequently I get emails about a package going between broken and working due to the unreliability of the tests - there is nothing to fix in this case.

Just today I got 24 emails:

![image](https://user-images.githubusercontent.com/450276/37255600-73380ef0-2546-11e8-83e7-92af84b28951.png)

**Comment by 7c6f434c** [comment]
Related: https://github.com/nixos/hydra/issues/545

It is possible that https://hydra.nixos.org will just lose all email support.

**Comment by dtzWill** [comment]
FWIW: https://groups.google.com/forum/#!topic/nix-devel/zD0j_jSmRTc
