### ISSUE TITLE
lua 5.2 does not ship "loadstring" but on debian it does

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#36816]
## Issue description

On NixOS, I get this with lua 5.2:

```
$ lua
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> loadstring("1 + 1")
stdin:1: attempt to call global 'loadstring' (a nil value)
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
```

On debian (jessy and stretch) it works, though:

```
deagol ~ $ lua5.2 
   Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
   > loadstring( "1 + 1" )
   >
   > loadstring( "print( 'OK')" )()
   OK
```

(see also https://github.com/lumail/lumail/issues/348#issuecomment-372133003)

It seems that either debian ships some additional lua scripts which "automagically" fix this, or we do something wrong?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.19, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - channels(m): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthiasbeyer** [comment]
Pinging lua people: @lblasc

**Comment by 7c6f434c** [comment]
Hm, maybe you want `lua_5_2_compat`?

**Comment by teto** [comment]
yep you need lua 5.2 with compatibility enabled.

**Comment by lblasc** [comment]
Debian builds lua5.2 with:
CFLAGS= -Wall -Wextra -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)
CXXFLAGS= -Wall -Wextra -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCXXFLAGS)

Nix:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/lua-5/5.2.nix#L1

It is a option, so you should override lua package to enable compat just for this package, or use lua5.1/luajit.

**Comment by 7c6f434c** [comment]
Wait, why override manually when `lua_5_2_compat` is already provided?

**Comment by matthiasbeyer** [comment]
Thanks for clearing that for me.

I filed an update of the package in https://github.com/NixOS/nixpkgs/pull/32710 which changes lua to 5.1 - This issue documents how to use 5.2, so I guess it is resolved!

Thank you all!
