### ISSUE TITLE
ghcWithPackages and terminfo issues

### ISSUE THREAD

**Issue by aavogt** [NixOS/nixpkgs#3682]
Hello,

GHC-7.8.3 provides the terminfo package. So 

`haskellPackages.ghcWithPackages (x : [ x.terminfo])`

has a conflict between the `libHSterminfo-0.4.0.0.so` coming from the haskellPackages.terminfo and the haskellPackages.ghc.

To get around this I override the `haskellPackages.terminfo` package with one that does nothing:
```
 myHaskellPackages = haskellPackages.override { extension = self : super :
    let override = pk : extension :
          (builtins.getAttr pk super).override (x : { cabal = x.cabal.override { 
            extension = if builtins.isFunction extension then extension
                            else self : super : extension; } ; }) ;
   in { terminfo = override "terminfo" { installPhase = "mkdir -p $out/bin";}; }
 }
```
the terminfo that comes with ghc cannot find `libncursesw.so`. I think the `pkgs/development/compilers/ghc/7.8.3.nix` should have the path to ncurses hardcoded in ghc's package database:
```
 postInstall = ''
    sed -i "/library-dirs:/ i \            ${ncurses}/lib\ " \
        $out/lib/ghc-${version}/package.conf.d/terminfo*.conf
 '';
```

**Comment by peti** [comment]
This issue is fixed by a8076c76549a3f3db78ef6c839aec449636fe2e3 in the `haskellngPackages` package set.
