### ISSUE TITLE
There is no way to let nixpkgs.buildPackages.fetchurl which is curl to use proxy

### ISSUE THREAD

**Issue by 424778940z** [NixOS/nixpkgs#368285]
## Steps To Reproduce

It's never worked for me, here is what I have done:
1. Set environment vars http_proxy/all_proxy/etc. before nix-shell -vvv, NOT WORKING
2. Set environment for nix-daemen service or conf files, reload and restart, NOT WORKING
3. Set environment var NIX_CURL_FLAGS and curlOpts before nix-shell -vvv, NOT WORKING
4. Edit /nix/store/x0ag6np5wri37aiyzqaq676wnwfm52wx-nixpkgs/nixpkgs/pkgs/build-support/fetchurl/builder.sh, put curl options in the actual script, WORK

## Expected behavior

I expect curl used during nix-shell build actually RESPECT proxy settings, I spend HOURS to research how to get it done in a proper way, but there is no such document/option/api to make it happen, other than modify the actual shell script.

I can't understand why a simple network configuration could be this difficult to achive, and why there are so many different places I have to set the proxy, why it is not unified? Is this why your package called flakes?

## Screenshots
N/A

## Additional context
N/A

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-51-generic, Ubuntu, 24.04.1 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 7c6f434c** [comment]
Have you read `man nix.conf`? It specifically tells you about `impure-env` configuration value suitable for setting `https_proxy` for a builder (which has different environment compared to the daemon itself)

**Comment by 424778940z** [comment]
> Have you read `man nix.conf`

Well, no. It never shows in search result

I'm not daily drive a NixOS, it's just one of my work related project uses it as build environment.
I have googled for hours, but it never came up. I even saw the `impureEnvVars` in source and some search result, and try to set it in shell.nix, but cannot figure out how.

The problem remains:
1. there are still too many places the user have to set proxy for
2. document still sucks, expicially when it come to use nix-shell only, everything come back from search are either for nix developers or NixOS users. which none of them apply to nix-shell use case

The thing is, not everyone encounter this very common problem is a geek or Nix pro, and they most likely couldn't care less about how it works under the hood, they just want get the job done, just search "proxy" in this repo and the nix repo, see how many results come back.

I really hope Nix could offer a simple way to let everything go through a proxy, like almost any program on Linux, **use the xxx_proxy environment**, not to set it in three different config files, which location mentioned in "flaked" documents.

**Comment by 7c6f434c** [comment]
It is a real issue that while `https_proxy` search in Nix Manual on the webpage does find `nix.conf` section, simply `proxy` doesn't (as «proxy» in «https_proxy» is not considered a separate word)! And you are right that the lack of a single page listing all network purposes and proxy configuration rules for them is unfortunate.
