### ISSUE TITLE
materia-theme: check boxes broken (at least in Firefox)

### ISSUE THREAD

**Issue by nioncode** [NixOS/nixpkgs#36827]
## Issue description
Check boxes don't get rendered correctly. In the screenshot 'NixOS' was checked, all others unchecked, but you can not see any differences.

![37253415-bf97228c-2531-11e8-9b35-648368499fdb](https://user-images.githubusercontent.com/3159451/37257845-cd20146c-256e-11e8-9f7d-be2bd5e40684.png)

The issue came up before on the project's repo (https://github.com/nana-4/materia-theme/issues/182) and was caused by wrong permissions apparently.
I could not reproduce the issue on Arch Linux, so I suspect something going wrong with the packaging of nix. Other themes like arc or numix work without this issue and have similar package definitions though.
The suggested workaround in the original issue `cp -r /nix/store/*-materia-theme-*/share/themes/Materia* ~/.themes` works for me as well, but I'd rather have the theme installed in the nix-store.

/cc @Mounium 

### Steps to reproduce
1. `nix-env -i materia-theme firefox`
2. Open Firefox.
3. Visit a page with check boxes (basically any PR here).

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3146.084445b8f38 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-unstable-18.03pre130932.cc4677c36ee, nixos-17.09.3146.084445b8f38"`
 - channels(nion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
Did you configure gtk to use the theme? I think just installing the package won't do anything.
For instance I have
```nix
{
  environment.variables = rec {
    XDG_DATA_DIRS   = lib.mkForce "${pkgs.materia-theme}/share:$XDG_DATA_DIRS";
    GTK2_RC_FILES   = "${pkgs.materia-theme}/share/themes/Materia-dark/gtk-2.0/gtkrc";
  };

  environment.etc."xdg/gtk-3.0/settings.ini" = {
    mode = "444";
    text = ''
      [Settings]
      gtk-theme-name=Materia-light-compact
      gtk-icon-theme-name=Paper
      gtk-font-name=Noto Sans 12
    '';
  };

  environment.systemPackages = with pkgs; [
    gtk-engine-murrine
    paper-icon-theme
    gnome3.adwaita-icon-theme
  ];
}
```

**Comment by nioncode** [comment]
I did install the theme only for my user via `nix-env` and then selected it with `lxappearance` (which ultimately writes `~/.gtkrc-2.0` and `~/.config/gtk-3.0/settings.ini`).
Your solution led me to the issue though: when I export `XDG_DATA_DIRS` with the path to materia, the checkboxes work correctly.

That brings me to the following questions:
1) Why can't the theme find its files through `~/.nix-profile/share/themes/Materia` – which is properly exported in `XDG_DATA_DIRS` by default?
2) Is it possible to export the `XDG_DATA_DIRS` for a user only? Themes should not be configured globally for all users imo.

**Comment by rnhmjoj** [comment]
1. I tried setting `XDG_DATA_DIRS=$HOME/nix-profile/share/themes`and straced firefox. It's trying to open `~/.nix-profile/share/themes/applications`. I have no idea why or what does it mean.
2. Yes, `XDG_DATA_DIRS=$HOME/nix-profile/share` should work.

**Comment by nioncode** [comment]
Something seems to be wrong with Firefox not following symlinks.

Broken:
```
$ echo $XDG_DATA_DIRS
/run/opengl-driver/share:/etc/per-user-pkgs/nion/share:/home/nion/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
$ firefox
(/nix/store/2g3v5kdch5584cz31crhf11csvlcbsgr-firefox-unwrapped-58.0.2/lib/firefox-58.0.2/firefox:9845): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

Works:
```
$ environment=`realpath ~/.nix-profile` export XDG_DATA_DIRS=`echo $XDG_DATA_DIRS | sed "s:/home/nion/.nix-profile:$environment:"`                                                                            

$ echo $XDG_DATA_DIRS 
/run/opengl-driver/share:/etc/per-user-pkgs/nion/share:/nix/store/63xzv3dxjxqjxgh2fzii6fb590182xax-user-environment/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share

$ firefox
```

There are no error messages left (and the checkboxes get drawn correctly) when the symlink of `/home/nion/.nix-profile` gets replaced with the actual path it eventually points to (after following a few symlinks).

So is this an upstream issue in Firefox?

**Comment by rnhmjoj** [comment]
Can you try other gtk applications to be sure?

**Comment by nioncode** [comment]
Nautilus and redshift-gtk look fine.

**Comment by prusnak** [comment]
@nioncode Is this still a problem?

**Comment by nioncode** [comment]
@prusnak no, I don't think so. I had the above `XDG_DATA_DIRS` replacement in my `.xprofile` since two years, but I now removed it and everything seems to be working just fine without it.

**Comment by Tejeev** [comment]
It appears to be an issue in Snaps on xubuntu 18.04
