### ISSUE TITLE
NetworkManager doesn't start on boot

### ISSUE THREAD

**Issue by atinba** [NixOS/nixpkgs#368262]
## Describe the bug
After upgrading my flakes and rebuilding network manager doesn't start automatically on boot. Have to use `systemctl` to start it. 
It works atleast till `25.05.20241217.d3c42f1`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by atinba** [comment]
It's related to https://github.com/NixOS/nixpkgs/pull/365809

**Comment by DerRockWolf** [comment]
I ran into the same issue with one of my hosts.

Some other hosts were not affected because they are using k3s which has `network-online.target` in `wants` & `after`...

I now wonder why things like `sshd` don't have `wants` set. And then I also wonder what's the reason for starting the network stack not directly with `multi-user.target` when there are lots of units that depend on networking :thinking:

**Comment by Slabity** [comment]
> I now wonder why things like sshd don't have wants set. And then I also wonder what's the reason for starting the network stack not directly with multi-user.target when there are lots of units that depend on networking 🤔

SSH should probably depend on `network.target`, but not necessarily dependent on NetworkManager itself.

It looks like the reason the `multi-user.target` was removed is because you shouldn't need to wait for the network to be up at all before you're able to log into the console.

I *think* we want something like this:

```nix
systemd.services.NetworkManager = {
  wants = [ "network-pre.target" ];
  wantedBy = [ "network.target" ];
};
```

This ensures that NetworkManager doesn't start until after `network-pre.target` is done, doesn't block logins dependent on `multi-user.target`, and still allow services like `sshd` to rely on `network.target`.

**Comment by DerRockWolf** [comment]
> This ensures that NetworkManager doesn't start until after network-pre.target is done, doesn't block logins dependent on multi-user.target, and still allow services like sshd to rely on network.target.

Isn't one of the main problems that (most) services don't have `wants` set and mostly use `after` which only refers to startup/shutdown order and *not* dependencies.

And if there is nothing that `wants` NetworkManager (or `network.target` in your above example) then it also won't ever be started...

---

I'm also wondering why the change in https://github.com/NixOS/nixpkgs/pull/365809 was only done for NetworkManager.
dhcpcd for example is still `wantedBy` `multi-user.target`.

**Comment by Slabity** [comment]
> Isn't one of the main problems that (most) services don't have `wants` set and mostly use `after` which only refers to startup/shutdown order and _not_ dependencies.
> 
> And if there is nothing that `wants` NetworkManager (or `network.target` in your above example) then it also won't ever be started...

Even if you have no services that depend on the network target, that doesn't mean you don't want the network target reached. A laptop or workstation might have zero networking services available, but you don't want that fact to prevent users from logging into the console.

For me, Network Manager is something that should be started regardless of any other services. If I have `networkmanager.enable` set to `true`, I *always* want Network Manager to start, even if there are zero configured services dependent on it. I don't want other services waiting for it (unless they're dependent on networking).

**Comment by rnhmjoj** [comment]
> I'm also wondering why the change in #365809 was only done for NetworkManager.
> dhcpcd for example is still wantedBy multi-user.target.

There's nothing specific to NetworkManager in that PR: it's just that multi-user.target no longer wants network-online.target (which was nonsense), as probably as a side effect was pulling in NetworkManager.service.

In fact, the upstream unit has `WantedBy=multi-user.target` in the install section, but this is ignored in NixOS and needs to be specified manually (see https://github.com/NixOS/nixpkgs/issues/81138). It looks like someone missed it.

**Comment by rnhmjoj** [comment]
Can you test https://github.com/NixOS/nixpkgs/pull/368791?

**Comment by DerRockWolf** [comment]
> Can you test #368791?

Done :slightly_smiling_face: 

> For me, Network Manager is something that should be started regardless of any other services.

I agree, NetworkManager should definitely be started regardless. This is what #368791 does.

@rnhmjoj when should a unit specify `wants` and `after` `network-online.target`? Should this be done for all services that require networking (e.g., sshd)?

**Comment by rnhmjoj** [comment]
@DerRockWolf: see this: https://systemd.io/NETWORK_ONLINE/
In essence,

- network-pre.target for services configuring firewalls (to not let any traffic slip through)

- network.target to ensure a service can perform some clean up before the network is brought down

- network-online.target when a service fails to start if offline or doesn't detect when the network comes up

**Comment by arianvp** [comment]
This should be fixed on master now
