### ISSUE TITLE
nixos: /run/opengl-driver/lib/gbm/dri_gbm.so not available

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#368379]
## Describe the bug
Programs, such as Electron, expect that `/run/opengl-driver/lib/gbm/dri_gbm.so` is available. But on latest stable it doesn't happen.

## Steps To Reproduce

1. ls /run/opengl-driver/lib/gbm/dri_gbm.so
2. realise it doesn't exist (also some programs complain about it)

## Expected behavior
That specific file exists

## Metadata

```
fetching git input 'git+file:///home/lucasew/.dotfiles'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 24.11 (Vicuna), 24.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/lucasew/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/guix/current/etc/xdg/nix/nix.conf:/home/lucasew/.guix-home/profile/etc/xdg/nix/nix.conf:/home/lucasew/.guix-profile/etc/xdg/nix/nix.conf:/home/lucasew/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/lucasew/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/lucasew/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/lucasew/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/bimspgs3cpapsbz7a2vi690916fgrvs5-lix-2.91.1/share`
 - nixpkgs: `/nix/store/4hpdrd3qvj7nks3rrimqm2jdmcga8isc-source`
```

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lucasew** [comment]
> I also encountered this problem a few days ago and now the master branch has been fixed for me

Did anyone bisected the exact diff that solved that to be backported?

**Comment by lucasew** [comment]
I sent a NixOS test to check that https://github.com/NixOS/nixpkgs/pull/368393

**Comment by lucasew** [comment]
Seems like a hardware configuration problem.

- `i5 7200U`: Happens
- `Ryzen 5 5600G + RTX 3060`: Doesn't happen

**Comment by JohnRTitor** [comment]
CC @K900 mesa and libdbm maintainer

**Comment by K900** [comment]
That file is new in Mesa 24.3, which is currently only available on unstable. Don't mix channels.

**Comment by Skarlett** [comment]
I am receiving the same error, as the file does not exist. instead I have nvidia-dri_gbm.so. 

anyone figure out how to fix this?

**Comment by JohnRTitor** [comment]
Either, don't use any unstable packages, or just move to unstable completely.

**Comment by Skarlett** [comment]
I settled on `makeWrapper --set GBM_BACKEND nvidia-drm` for derivations that are looking for this file. Hope this helps anyone else running into this issue.

**Comment by lucasew** [comment]
> Either, don't use any unstable packages, or just move to unstable completely.

That's the kind of situation that makes me want to abandon NixOS. I am already moving as much as possible to Flatpak.

**Comment by Skarlett** [comment]
> > Either, don't use any unstable packages, or just move to unstable completely.
> 
> That's the kind of situation that makes me want to abandon NixOS. I am already moving as much as possible to Flatpak.

There maybe a misunderstanding. 

In this case JohnRTitor is correct that I am using unstable with stable mixed in, and also packaging my own source code along side of it. I hadn't realized until I thought about how my system was deployed, and the env I was working on.

The opengl/mesa-loader is controlled at the operating system level, where programs dynamically link into it to run graphical applications.
(flatpak will behave the same way).

Perhaps you find their answer distasteful, but it is objectively correct.

Feel free to reach out with anymore questions, or misunderstandings.
@lucasew
