### ISSUE TITLE
Color channels swapped in OpenGL applications after upgrade to NixOS 24.11

### ISSUE THREAD

**Issue by mario-holubar** [NixOS/nixpkgs#368424]
## Describe the bug

Upon upgrading my system to 24.11 and rebooting, the red and blue color channels are swapped in hardware accelerated applications. The rest of the system is unaffected.

The issue affects all users, on X11 and Wayland, and persists across reboots.
It disappears upon reverting to 24.05.

## Steps To Reproduce

1. Upgrade NixOS to 24.11 on Intel Meteor Lake hardware
2. Reboot

## Expected behavior

All programs work the same as before

## Screenshots

(The terminal is kitty)

24.05:
![Screenshot from 2024-12-26 22-47-42](https://github.com/user-attachments/assets/5827576a-c09a-4974-9943-c13b799b7af6)

24.11:
![Screenshot From 2024-12-26 22-46-07](https://github.com/user-attachments/assets/f2481693-1400-4844-aee6-fb5618f27f96)

## Additional context

I am on a Thinkpad X1 Carbon 12th gen with Intel Core Ultra 7 155U and no dedicated GPU.

lspci:
`00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Graphics] [8086:7d45] (rev 08)`

glxinfo:
```
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
    GLX_MESA_copy_sub_buffer, GLX_MESA_gl_interop, GLX_MESA_query_renderer,
    GLX_MESA_query_renderer, GLX_SGIS_multisample, GLX_SGIX_fbconfig,
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: llvmpipe (LLVM 17.0.6, 256 bits)
```

The MESA and glx errors show up on 24.05 and not on 24.11, but I was able to just ignore them. Nevertheless they might have the same root cause as this issue?

In my configuration.nix I have `hardware.opengl.enable = true;` and nothing else graphics related.

## Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 24.11 (Vicuna), 24.11.711934.4005c3ff7505`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
CC @K900 mesa maintainer

**Comment by K900** [comment]
If this is the upstream issue I think it is, it should be fixed in Mesa 24.2.8, which should be making it into the next staging-24.11 cycle.

**Comment by Atemu** [comment]
> `MESA: error: ZINK: failed to choose pdev glx: failed to create drisw screen GLX_MESA_copy_sub_buffer, GLX_MESA_gl_interop, GLX_MESA_query_renderer, GLX_MESA_query_renderer, GLX_SGIS_multisample, GLX_SGIX_fbconfig, Extended renderer info (GLX_MESA_query_renderer): OpenGL renderer string: llvmpipe (LLVM 17.0.6, 256 bits)`

This reads to me like you weren't using hardware acceleration at all previously?

You could probably revert to that state by forcing OpenGL rendering back to software rendering (llvmpipe).

**Comment by mario-holubar** [comment]
Oh my, you're right. I didn't even realize hahah

Did some more digging and found [this](https://discourse.nixos.org/t/nixos-of-intel-core-ultra/46970) and [this](https://discourse.nixos.org/t/proper-configuration-for-intel-meteor-lake-core-ultra-7-155h/52154) thread.
Added this to my config:
```
boot.kernelPackages = pkgs.linuxPackages_latest;
boot.initrd.kernelModules = ["xe"];
```
And it resolved the issues.

Maybe this should be added to the wiki for other Meteor Lake users.
