### ISSUE TITLE
nix-env -qas fails with "error: attribute ‘glibc’ missing"

### ISSUE THREAD

**Issue by wereHamster** [NixOS/nixpkgs#36848]
## Issue description

```
$ nix-env -qas 
error: attribute ‘glibc’ missing, at /nix/store/4svfi53kwcw06rww6bagxzm1fx2rnd01-nixpkgs-18.03pre130569.7a04c2ca296/nixpkgs/pkgs/applications/audio/baudline/default.nix:39:27
```

```
$ nix-env -qas --show-trace
error: while evaluating the attribute ‘buildCommand’ of the derivation ‘chatzilla-0.9.92’ at /nix/store/4svfi53kwcw06rww6bagxzm1fx2rnd01-nixpkgs-18.03pre130569.7a04c2ca296/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute ‘preConfigure’ of the derivation ‘firefox-unwrapped-58.0.2’ at /nix/store/4svfi53kwcw06rww6bagxzm1fx2rnd01-nixpkgs-18.03pre130569.7a04c2ca296/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute ‘cc.cc.gcc’ at /nix/store/4svfi53kwcw06rww6bagxzm1fx2rnd01-nixpkgs-18.03pre130569.7a04c2ca296/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:81:10:
attribute ‘gcc’ missing, at /nix/store/4svfi53kwcw06rww6bagxzm1fx2rnd01-nixpkgs-18.03pre130569.7a04c2ca296/nixpkgs/pkgs/applications/networking/browsers/firefox/common.nix:66:51
```

### Steps to reproduce

Run `nix-env -qas`.

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 15.6.0, macOS 10.11.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(tomc): `"nixpkgs-18.03pre130569.7a04c2ca296"`
 - nixpkgs: `/Users/tomc/.nix-defexpr/channels/nixpkgs`

**Comment by wereHamster** [comment]
Both are reliable, happen 100% of the time.

It's strange that the two commands show a different error, even though the difference between the two commands is `--show-trace`.

**Comment by matthewbauer** [comment]
You probably have allowBroken set to true? This might be fixable but I think that these kind of evaluation are fairly common.

**Comment by wereHamster** [comment]
How would I find out if I have allowBroken set?

**Comment by matthewbauer** [comment]
It would be in either ```~/.nixpkgs/config.nix``` or ```~/.config/nixpkgs/config.nix```. If both don't exist, then you haven't messed with it. Can you verify really quick that this still gives you the issue:

```
nix-env -qas --arg config '{allowUnfree = false; allowBroken = false;}' -f https://github.com/NixOS/nixpkgs/archive/7a04c2ca296c0698f1c7d5c17be7f931f77691f7.tar.gz --show-trace
```

On my machine this gives no errors.
