### ISSUE TITLE
Package request: ghostty

### ISSUE THREAD

**Issue by ttrei** [NixOS/nixpkgs#368414]
## Project description

> Ghostty is a terminal emulator that differentiates itself by being fast, feature-rich, and native.

## Metadata

* homepage URL: https://ghostty.org/
* source URL: https://github.com/ghostty-org/ghostty
* license: mit
* platforms: linux, darwin

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by flemzord** [comment]
https://github.com/NixOS/nixpkgs/pull/368404

**Comment by pluiedev** [comment]
PR's not merged yet — should leave the issue open for discoverability
