### ISSUE TITLE
Build failure: folly 2024.11.18 (and therefore watchman) stopped compiling on darwin

### ISSUE THREAD

**Issue by ilyagr** [NixOS/nixpkgs#368501]
## Steps To Reproduce

1. build folly 2024.11.18 (in unstable since a few days ago)

## Build log

See <https://gist.github.com/ilyagr/6563926a723ed3f6e8dd121e758cd9bd>

## Additional context

The build chugged along for a couple of minutes, then 2 instances of `clang++` took 2 *hours* at 100% CPU utilization (single core) before failing.

The problem is with some dependency, a few days ago the same version of folly compiled fine. (`github:NixOS/nixpkgs/nixpkgs-unstable` as of 2024-12-23 20:55 was the last successful time it compiled successfully for me)

I suspect #361878 maybe.

## Metadata

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.6.0, macOS 14.7.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/1jphxmkkqvz69yg0fq6z69dcpfkyy0l9-source`
```

## Notify maintainers

@emilazy
@techknowlogick
@K900 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by paparodeo** [comment]
hmm, for some reason I thought that `2024.11.8` didn't have the `char_types` issue, bummer. a fix + update is already in staging: https://github.com/NixOS/nixpkgs/pull/362234 but probably will take 2-4 weeks to make it into master.

**Comment by paparodeo** [comment]
to get master to build can disable tests as it is just the test not compiling which is causing the build to fail.

```
folly.overrideAttrs { doCheck = false; }
```

**Comment by emilazy** [comment]
I think let’s disable the tests on LLVM for now and revert it in `staging`; will try to put up a PR for that soon if nobody beats me to it. Sorry for being absent when this broke during `staging-next` or I’d have made sure it got fixed.

**Comment by emilazy** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/368576.

**Comment by ilyagr** [comment]
Wonderful, thank you both!
