### ISSUE TITLE
Build failure: python312Packages.debugpy after #365740

### ISSUE THREAD

**Issue by spiage** [NixOS/nixpkgs#368636]
## Steps To Reproduce

build python312Packages.debugpy after #365740 at nixpkgs/master

## Build log

```
  /nix/store/qjqc60gzd0hpzb0qhhvblys3i748i1hg-nixos-system-a7-25.05.20241227.e752b73.drv
building '/nix/store/d3vg6ya9b50dnh3mj5phk2jz1759lh1n-source.drv'...
error: hash mismatch in fixed-output derivation '/nix/store/d3vg6ya9b50dnh3mj5phk2jz1759lh1n-source.drv':
         specified: sha256-jq/0Z6Oo/9gjJlziYJIjIC5i9YMayUdPYSGTjnDL8yU=
            got:    sha256-C/cLUMQNmiLn3z93LOg++3WeDUihMR9O3XKouL4uPqw=
note: keeping build directory '/tmp/nix-build-source.drv-1/build'
error: 1 dependencies of derivation '/nix/store/ly0z5qr8lr35fzhf3vjybirkbsz0d8ab-python3.12-debugpy-1.8.11.drv' failed to build
```

## Notify maintainers

@kira-bruneau

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
Thanks @spiage!

Looks like I originally grabbed the source while 1.8.11 was still the HEAD commit :melting_face: 

```diff
diff -r /nix/store/zg3sg435gawa050z8pr2l3k8y0sdacni-source/src/debugpy/_version.py /nix/store/c78m61nhd2whyby19jgcag6wfalmji5a-source/src/debugpy/_version.py
28c28
<     git_refnames = " (HEAD -> main, tag: v1.8.11)"
---
>     git_refnames = " (tag: v1.8.11)"
```

`git_refnames` is dynamically set with [.gitattributes](https://github.com/microsoft/debugpy/blob/main/.gitattributes)

**Comment by spiage** [comment]
@kira-bruneau Sometime upstream can weep some commits under the carpet :)

**Comment by kira-bruneau** [comment]
Yeah, but this one is specifically caused by using `.gitattributes`, not a force push. I ran into a similar problem before with ccache: https://github.com/NixOS/nixpkgs/issues/316524#issuecomment-2143662429
