### ISSUE TITLE
LLVM-based cross compilation

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#36867]
LLVM is a much nicer for cross compilation. It has been multi-target for the vast majority, and its associated runtime libraries (e.g. compiler-rt, libcxx) are readily built separately from the compiler itself.

Unfortunately, our current packaging doesn't take advantage of either of these. We build compiler-rt in the same derivation as LLVM, and we pull everything from the same boostrappping stage, precluding cross compilation infra from working its magic.

I took a stab at this in https://github.com/obsidiansystems/nixpkgs/commit/acf2ed5bafc61345ddc1fa372225c8f479cb8cd8 (the top commit in https://github.com/obsidiansystems/nixpkgs/tree/split-compiler-rt). I should get around to at least rebasing that, but even in its current state that serves as a basic reference to what should be accomplished.

-----

CC @angerman @dtzWill

**Comment by Mic92** [comment]
Too bad it still cannot build the kernel: https://lwn.net/Articles/734071/

**Comment by eternaleye** [comment]
@Mic92: Um, to quote the article:

> This work has shown that the FUD surrounding using a new toolchain for the kernel is unfounded, Desaulniers said. It is working now, but there are a few asterisks. *Clang, the front end, can compile the kernel*, but the assembler and the linker from GNU Binutils are needed to complete the build process.

(emphasis mine)

Reducing the use of `gcc` down to using `gas` for the kernel (rather than the full stack for everything) is pretty big in its own right, and using binutils' `ld` will likely be needed in various cases for a while anyway as `lld` gets up to speed.

In addition, [this mail](https://lwn.net/Articles/739167/) from one month later claims that the `gas` requirement boils down to [this bug](https://bugs.llvm.org/show_bug.cgi?id=24487) affecting x86, and works on othe architectures (such as arm64).

Further improvement has likely occurred on the four months since then.

**Comment by Ericson2314** [comment]
Anyways, the point of this is to change how we package LLVM. Once we do that, we'll be able to *attempt* cross compiling any package we want, including Linux. Getting Linux to build with LLVM is an orthogonal concern.

**Comment by wmertens** [comment]
Does this mean your ultimate goal is to _only_ build Nixpkgs with LLVM? Because that seems untenable :-/

**Comment by eternaleye** [comment]
@wmertens I'd argue that using clang, libc++, etc. would count as a distinct cross target - one potentially easier/simpler/cleaner to bootstrap.

**Comment by Ericson2314** [comment]
@wmertens No. I want to support as many combinations as we can without a a soup of conditionals. What we choose to support via CI resources I'll happily leave to others. Compare to https://github.com/NixOS/rfcs/pull/23 not being about ditching glibc.

**Comment by Ericson2314** [comment]
@eternaleye Today, compiler and libc++ choices don't require a different platform name, but they could. libc ones do with `-musl` vs `-gnu`, for example, and in any event, the hashes will reflect the change like any other dependency change.

**Comment by matthewbauer** [comment]
@ericson2314 Can this be closed?
