### ISSUE TITLE
Samsung printer (splix) - NixOS [doesn't work with stock ppd] v/s Raspbian [works - generates good ppd]

### ISSUE THREAD

**Issue by husnoo** [NixOS/nixpkgs#36876]
## Issue description
I have a Samsung M2022W (usb) that works on a raspberrypi using raspbian (2017-11-29-raspbian-stretch-lite.img). I had to pick the ML-2160 driver in CUPS 2.2.1 as recommended by http://www.openprinting.org/printer/Samsung/Samsung-M2022W.

On NixOS (cups-2.2.2):
[nawal@heisenbug:~]$ nix-info
system: "x86_64-linux", 
multi-user?: yes, version: nix-env (Nix) 1.11.16, channels(nawal): "nixos-17.03-17.03.1082.4aab5c5798", channels(root): "nixos-17.09.3149.ae0b65aacc6", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

If I use 
`
    services.printing = {
        enable = true;
        drivers = [
                pkgs.splix
                pkgs.samsungUnifiedLinuxDriver
        ];
        extraConf = ''
        LogLevel debug
        '';
        extraFilesConf = ''
        FileDevice yes
        '';
    };
`
and pick the same driver, I get garbage printed out. I tried to track down the ppd on raspbian, but only found:
pi@raspberrypi:~ $ grep 2160 /usr/share/cups/drv/splix-samsung.drv
                    ModelName "ML-2160"
                    PCFileName "ml2160.ppd"
and /etc/cups/ppd/Samsung_M2020_Series.ppd
(i.e. it generated the ppd when I installed the printer apparently).

On nixos:
[nawal@heisenbug:~]$ find /nix/ | grep ppd$ | grep 2160
/nix/store/6f2zx8dl4w0kzgw3wj8f466mvkcgc3dc-samsung-UnifiedLinuxDriver-4.00.39/opt/share/ppd/ML-2160.ppd
/nix/store/nmp023llc8fix567f413a5rqbx4sw45g-cups-progs/share/cups/model/ML-2160.ppd

Having diffed them, I notice amongst a huge number of differences:

[nawal@heisenbug:~]$ diff /home/nawal/data/nixos/Samsung_M2020_Series.ppd /nix/store/nmp023llc8fix567f413a5rqbx4sw45g-cups-progs/share/cups/model/ML-2160.ppd | grep Version
< *FileVersion: "2.0.0"
> *FileVersion: "1.2"
< *PSVersion: "(3010.000) 0"
> *cupsVersion: 1.1
> *PSVersion:   "(3010.000) 550"
< *QPDL QPDLVersion: "3"
< *cupsVersion: 2.2

so raspbian is using a version "2.0.0" and "2.2" of something or other, whereas nixos is using a version "1.2" and "1.1" of similar things. I managed to get my printer to work by copying the ppd across, but I don't understand enough of cups (nor now have the inclination to learn) to figure out what's going on or how to make nixos do the right thing (i.e. in a word, print).

I thought this might be useful for someone else who wants to pick it up? Happy to hack around the raspbian if you need more info, or try out things if you need me to while the sd card contains raspbian.

**Comment by abbradar** [comment]
@husnoo Can you find out what package on Raspbian provides the driver? Have you installed proprietary Samsung driver there? If not, can you try removing `samsungUnifiedLinuxDriver`? It seems we have latest version of `splix` but not the latest of the proprietary driver but you don't seem to use it.

**Comment by husnoo** [comment]
I'll have a look tomorrow evening - how do i use the new splix without upgrading everything to the same commit?

**Comment by abbradar** [comment]
@husnoo Find out your current commit with `nixos-version` (look at the suffix), then clone nixpkgs repository (`git clone https://github.com/NixOS/nixpkgs`), checkout current commit (`git checkout commit_hash`), fetch my changes (`git fetch origin refs/pull/37048/head`) and cherry-pick my patch atop your current commit (`git cherry-pick 6b2d303b0624619c85377967d30fb00ab1cfc25e`). Then you can rebuild nixpkgs by `nixos-rebuild switch -I /path/to/repository`.

**Comment by husnoo** [comment]
I can confirm this works. Thanks for the detailed instructions and for fixing it so quickly!

NB: I had to do: 

`sudo nixos-rebuild switch -I nixpkgs=/home/nawal/data/tmp/nixpkgs`

(i.e. `-I nixpkgs=....`)

thanks
