### ISSUE TITLE
Package request: Ghostty

### ISSUE THREAD

**Issue by wegotoeleven** [NixOS/nixpkgs#368750]
## Project description

Ghostty is a terminal emulator that differentiates itself by being fast, feature-rich, and native. While there are many excellent terminal emulators available, they all force you to choose between speed, features, or native UIs. Ghostty provides all three.

## Metadata

* homepage URL: https://github.com/ghostty-org/ghostty
* source URL: https://github.com/ghostty-org/ghostty
* license: MIT License
* platforms: macOS, linux

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fmway** [comment]
Already merged. #368404
