### ISSUE TITLE
Package request: hardened-chromium

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#368837]
## Project description

A hardened chromium for desktop Linux inspired by Vanadium.

Depends on hardened_malloc which we have packaged. Not sure if in case of this browser it requires hardened_malloc for building or if it should be LD_PRELOADed.

## Metadata

* homepage URL: https://github.com/secureblue/hardened-chromium
* source URL: https://github.com/secureblue/hardened-chromium
* license: gpl2
* platforms: linux

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilylange** [comment]
Duplicate of #352131.

**Comment by surfaceflinger** [comment]
wtf, how did I miss that, sorry
