### ISSUE TITLE
gnome-shell-extension-clipboard-history / gnomeExtensions.clipboard-history does not work

### ISSUE THREAD

**Issue by mark-wiemer** [NixOS/nixpkgs#368998]
## Describe the bug

I've added `gnomeExtensions.clipboard-history` to my configuration.nix and validated it appears in `nixos-option environment.systemPackages` as `«derivation  /nix/store/zl6c3jqz4rxq1i8cl311wyh767mgc49y-gnome-shell-extension-clipboard-history-45.drv»`. My GNOME version is 47. 

However the advertised "Super+Shift+V" command does not work and there is no clipboard history icon in the system tray on the top right (using GNOME, of course). I can't figure out how to "activate" this extension at all when installed via configuration.nix

Note that installing from [Clipboard History - GNOME Shell Extensions](https://extensions.gnome.org/extension/4839/clipboard-history/) works as expected, but configuration.nix is not updated, and the goal is to install this in a reproducible way for future machines.

I'm very new to NixOS and Linux but I am a professional software dev, happy to provide additional details as needed.

## Steps To Reproduce

1. Add to configuration.nix:
    ```
    environment.systemPackages = with pkgs; [
      vim # Do not forget to add an editor to edit configuration.nix!
      gnomeExtensions.clipboard-history
    ];
    ```

1. `sudo nixos-rebuild switch`

    > Optionally, confirm the install via `nixos-option environment.systemPackages`

1. Try to run via the instructions from [clipboard history project readme](https://github.com/SUPERCILEX/gnome-clipboard-history?tab=readme-ov-file#tips)

## Expected behavior

1. Super+Shift+V does something and/or clipboard history icon appears in the "toolbar" near the top right

## Screenshots

![image](https://github.com/user-attachments/assets/b78aa207-7612-48ab-9c5c-1634c5704687)

## Additional context

n/a

## Metadata

```log
[markw@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.67, NixOS, 24.11 (Vicuna), 24.11.712007.d49da4c08359`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(root): `"home-manager-24.11.tar.gz, nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

<details><summary>configuration.nix</summary>

```nix
# configuration.nix

# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

# To apply changes, run `sudo nixos-rebuild switch`

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      <home-manager/nixos>
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "America/Los_Angeles";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable sound with pipewire.
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.markw = {
    isNormalUser = true;
    description = "Mark Wiemer";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
    #  thunderbird
    ];
  };

  # Install firefox.
  programs.firefox.enable = true;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  services.xserver.excludePackages = with pkgs; [
    xterm
  ];
  environment.gnome.excludePackages = with pkgs; [
    epiphany # web browser named "web"
  ];
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    wget
    discord
    protonvpn-gui
    vscodium
    git
    gnomeExtensions.clipboard-history
    obsidian
  ];
  home-manager.users.markw = { pkgs, ... }: {  
      # The state version is required and should stay at the version you
      # originally installed.
      home.stateVersion = "24.11";
      dconf.settings = {
        "org/gnome/desktop/peripherals/mouse" = { natural-scroll = true; };
        "org/gnome/desktop/interface" = {
          color-scheme = "prefer-dark";
      };
    };
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?

}
```

</details>

## Notify maintainers

@honnip 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by poopsicles** [comment]
hm, the [extensions.json](https://github.com/NixOS/nixpkgs/blob/634fd46801442d760e09493a794c4f15db2d0cbb/pkgs/desktops/gnome/extensions/extensions.json) appears to specify a version `45` (line 5006), but there's only a [`44`](https://github.com/SUPERCILEX/gnome-clipboard-history/blob/e84e26680d44e1de30e2cbbed9e01af80ddfc2ef/metadata.json#L3) upstream...

**Comment by honnip** [comment]
Hello. Can you try enabling it in the Extensions app? 

You can also do it with dconf settings. See https://github.com/honnip/dotfiles/blob/73477ee1e98e93bd7a45296b24212cb9e3c76069/home/honnip/modules/desktop/gnome.nix#L38-L41


>hm, the [extensions.json](https://github.com/NixOS/nixpkgs/blob/634fd46801442d760e09493a794c4f15db2d0cbb/pkgs/desktops/gnome/extensions/extensions.json) appears to specify a version 45 (line 5006), but there's only a [44](https://github.com/SUPERCILEX/gnome-clipboard-history/blob/e84e26680d44e1de30e2cbbed9e01af80ddfc2ef/metadata.json#L3) upstream...

I'm not sure why, but extensions.gnome.org says it's 45

**Comment by mark-wiemer** [comment]
@honnip Hmm, I removed the instance I installed from extensions.gnome.org and now I'm not seeing any extensions at all!

![gnome extensions shows "No Installed Extensions"](https://github.com/user-attachments/assets/20d2e484-2657-4f5f-a3d6-22d1f171c1a6)

That said, this is the only non-core extension I'm trying to use. Let me reboot my system as a sanity check.

**Comment by mark-wiemer** [comment]
Restarting worked! Closing this one :)

![Clipboard history as a GNOME system extension](https://github.com/user-attachments/assets/79c2086a-3529-42f8-9b35-d2be40e02591)

**Comment by mark-wiemer** [comment]
(I'll add that I'm not seeing the clipboard button in my toolbar, but that's fine, I don't want that anyway)

![GNOME toolbar without clipboard button](https://github.com/user-attachments/assets/78ccd01f-feaa-4950-a6ec-7d1c18142061)
