### ISSUE TITLE
NixOS package search: some packages do not show up in the search

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#36907]
*Edited.*

## Issue description

I tried searching for Core Fonts for NixOS with the online [package search](https://nixos.org/nixos/packages.html#corefonts), but entering "corefonts" did not return anything, and searching my other words, like "andale", didn't help.

I've found that some people were using `fonts.enableCoreFonts`, but it was not listed in the Options section of the NixOS manual.  I've spent some time trying to figure out if it was replaced by a different option, then i just tried it and it worked.

I first thought there was a problem with showing option like [`fonts.enableCoreFonts`](https://github.com/NixOS/nixpkgs/blob/a682ba23d49cd13c92922af3d5dc44efd60ae9e7/nixos/modules/config/fonts/corefonts.nix#L14) in [NixOS manual](https://nixos.org/nixos/manual/options.html#opt-fonts.enableDefaultFonts), but then it turned out (see the comment of @jfrankenau ) that this option was deprecated, and i had to just use `corefonts` package.

So, why is `corefonts` not showing up in search results?  How was i supposed to look for it correctly?

## Technical details

This is about the online [package search](https://nixos.org/nixos/packages.html) for NixOS 17.09.

**Comment by jfrankenau** [comment]
This is on purpose as the comment in the linked file explains.

**Comment by alexeymuranov** [comment]
Yes, indeed, i didn't noticed that. However i tried this option in the first place because i didn't find `corefonts` or anything similar with NixOS [package search](https://nixos.org/nixos/packages.html#corefonts).

**Comment by jfrankenau** [comment]
Packages that are unfree like `corefonts` are explicitly hidden from the package search. For more discussion on this topic see #17126.

**Comment by alexeymuranov** [comment]
Thanks, i'll follow that issue.
