### ISSUE TITLE
activitywatch installation fails with "setuptools not installed" (since update to 24.11 I assume)

### ISSUE THREAD

**Issue by ThiloBohr** [NixOS/nixpkgs#369053]
## Describe the bug

Running `sudo nixos-rebuild test --flake <path/to/my/flake>` fails with:
```
error: builder for '/nix/store/64ilr5h653mqg1ap913kmzn7iq6ky4d0-aw-qt-0.13.2.drv' failed with exit code 1;
       last 25 log lines:
       > Using pythonImportsCheckPhase
       > Sourcing python-namespaces-hook
       > Sourcing python-catch-conflicts-hook.sh
       > Running phase: qtPreHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/qkxj8gxhr4qmmw5599gmdpmxchd78gi0-source/aw-qt
       > source root is aw-qt
       > setting SOURCE_DATE_EPOCH to timestamp 315619200 of file aw-qt/tests/integration_tests.py
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > Executing pypaBuildPhase
       > Creating a wheel...
       > pypa build flags: --no-isolation --outdir dist/ --wheel
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built aw_qt-0.1.0-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for aw_qt-0.1.0-py3-none-any.whl
       >   - setuptools not installed
```

## Steps To Reproduce

See description.

## Expected behavior

Rebuild does not fail.

## Additional context

I assume this error appeared with the update from Nixos 24.05 to 24.11 - activitywatch was running fine before.

Also, `nix-shell -p activitywatch` works as expected i.e. I can successfully run aw-qt in the nix-shell.

## Metadata

```
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/yz7bhiif4qz46iv4za618903darbwqks-nix-info
copying path '/nix/store/yz7bhiif4qz46iv4za618903darbwqks-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.66-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241222.1807c2b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/home/thilo/.nix-defexpr/channels/nixpkgs`
```

## Notify maintainers

@huantianad

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Hunkarada** [comment]
I have same problem. I had updated to 24.11, and it worked fine, before some update +- 1-2 weeks ago, so I assume that this is not 24.11 commit.

**Comment by Marlinc** [comment]
I expect this gets fixed by https://github.com/NixOS/nixpkgs/pull/368560

**Comment by ThiloBohr** [comment]
Updated my system to current release-24.11 branch (which includes the merged commit from https://github.com/NixOS/nixpkgs/pull/368560) and can confirm that the commit fixed the build problem. Thanks @Marlinc !
