### ISSUE TITLE
rake out of date 

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#36912]
## Issue description

Latest version: 12.3.0 - October 25, 2017 (83 KB)

```
{
  rake = {
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "01j8fc9bqjnrsxbppncai05h43315vmz9fwg28qdsgcjw9ck1d7n";
      type = "gem";
    };
    version = "12.0.0";
  };
}
```

### Steps to reproduce
look in master

Where does that sha256 hash come from btw?

**Comment by alyssais** [comment]
Quoting the IRC bot:

> To get a sha256 hash of a new source, you can use the Trust On First Use model: use probably-wrong hash (for example: 0000000000000000000000000000000000000000000000000000) then replace it with the correct hash Nix expected.
