### ISSUE TITLE
Build failure: Bottles

### ISSUE THREAD

**Issue by BlueFox1616** [NixOS/nixpkgs#369252]
## Steps To Reproduce

1. build Bottles

## Build log

`sudo nixos-rebuild switch --flake /etc/nixos
[sudo] password for pantelis: 
building the system configuration...
error: builder for '/nix/store/bqfg2ljj6cmv8cppfhhn08c5zzmakzli-python3.12-patool-2.4.0.drv' failed with exit code 1;
       last 25 log lines:
       > =================================== FAILURES ===================================
       > __________________________ TestMime.test_nested_gzip ___________________________
       >
       > args = (<tests.test_mime.TestMime testMethod=test_nested_gzip>,), kwargs = {}
       >
       >     def newfunc(*args, **kwargs):
       >         if not testfunc(name):
       >             pytest.skip(f"{description} {name!r} is not available")
       > >       return func(*args, **kwargs)
       >
       > tests/__init__.py:44:
       > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
       > tests/test_mime.py:198: in test_nested_gzip
       >     self.mime_test_file("t.rar.gz", "application/x-rar", "gzip")
       > tests/test_mime.py:56: in mime_test_file
       >     self.mime_test(patoolib.mime.guess_mime_file, archive, mime, encoding, info)
       > tests/test_mime.py:38: in mime_test
       >     self.assertEqual(
       > E   AssertionError: 'application/gzip' != 'application/x-rar'
       > E   - application/gzip
       > E   + application/x-rar
       > E    : MIME type for archive `/build/source/tests/data/t.rar.gz' should be application/x-rar, but was application/gzip. Info: application/x-gzip
       > =========================== short test summary info ============================
       > FAILED tests/test_mime.py::TestMime::test_nested_gzip - AssertionError: 'application/gzip' != 'application/x-rar'
       > =========== 1 failed, 87 passed, 124 skipped, 6 deselected in 20.50s ===========
       For full logs, run 'nix log /nix/store/bqfg2ljj6cmv8cppfhhn08c5zzmakzli-python3.12-patool-2.4.0.drv'.
error: 1 dependencies of derivation '/nix/store/d1bhadx9561cqg0fgwhk745j6w4f4d9b-bottles-unwrapped-51.17.drv' failed to build
error: 1 dependencies of derivation '/nix/store/blw4pwy4j0acasw1i72ar9x39i6i2x7w-bottles.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dlrmfwy9w5fxmkgd1im86iajhbmsgvf6-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ibl3zjikjlfn83aq8fiy6ha5nkp7rfg2-nixos-system-nixos-25.05.20241227.634fd46.drv' failed to build`

## Metadata

It outputs nothing

## Notify maintainers @psydvl @SCOTT-HAMILTON @Gliczy 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Gliczy** [comment]
This is an issue with `patool`, it is fixed on master with https://github.com/NixOS/nixpkgs/pull/368882.
