### ISSUE TITLE
Update request: rakudo 2024.06 → 2024.12

### ISSUE THREAD

**Issue by habere-et-dispertire** [NixOS/nixpkgs#369244]
## Package Information

- Package name: rakudo
- Latest released version: 2024.12
- Current version on the unstable channel: 2024.06
- Current version on the stable/release channel: 2024.06

## Checklist

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

## Notify maintainers

@stigtsp , @thoughtpolice  

Thank you ❤️ both ❤️ !

**Comment by stigtsp** [comment]
@habere-et-dispertire Hi! I've made a PR to update rakudo: #369254
