### ISSUE TITLE
Build failure: bambu-studio

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#369370]
## Steps To Reproduce

1. build bambu-studio

## Build log

embedding this huge build log in github collapsable seems to break the other markdown somehow. 
so here is the log uploaded to a paste service: https://justpaste.it/hvfvq
the relevant line is mainly this: include/boost/math/cstdfloat/cstdfloat_limits.hpp:45:13: error: redefinition of 'class std::numeric_limits<__float128>'

## Additional context

related to https://github.com/NixOS/nixpkgs/pull/356812
bambu-studio seems to depend on boost 180 which doesn't build with gcc 14. https://github.com/boostorg/math/issues/992
upstream boost fixed version 185.

maybe this should be fixed in boost < 185 packages instead of  bambu-studio since this bug may happen in any software using some boost headers with boost <185 and gcc >= 14. 

## Metadata

nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5-xanmod1, NixOS, 25.05 (Warbler), 25.05.20241219.d70bd19`

 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - channels(chris): `""`
 - nixpkgs: `/nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source`
 
## Notify maintainers

bambu-studio
@zhaofengli
@dsluijk 
boost
@hjones2199

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ChrisOboe** [comment]
i applied this patch: https://patch-diff.githubusercontent.com/raw/boostorg/math/pull/993.patch from upstream boost to the nixpkgs boost180 used by bambo-studio. Now bambu-studio compiles but the linking fails: 

       > [100%] Linking CXX executable bambu-studio
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: warning: libtbb.so.2, needed by /nix/store/yh9dva4nxd6aqazbv2yrx2mb6zbq00ba-openvdb-12.0.0/lib/libopenvdb.so, may conflict with libtbb.so.12
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: warning: libboost_iostreams.so.1.86.0, needed by /nix/store/yh9dva4nxd6aqazbv2yrx2mb6zbq00ba-openvdb-12.0.0/lib/libopenvdb.so, may conflict with libboost_iostreams.so.1.80.0
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: warning: libglapi.so.0, needed by /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so, not found (try using -rpath or -rpath-link)
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_set_dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_dispatch_table_size'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_set_context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_get_proc_address'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_tls_Dispatch'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_tls_Context'
       > /nix/store/j7p46r8v9gcpbxx89pbqlh61zhd33gzv-binutils-2.43.1/bin/ld: /nix/store/frhp8rpzw7m95cnj74a7lb09mdwzzq7m-mesa-24.3.2-osmesa/lib/libOSMesa.so: undefined reference to `_glapi_add_dispatch'
       > collect2: error: ld returned 1 exit status
       
so there seems to be something more broken besides the gcc14 float128 thing.

**Comment by FliegendeWurst** [comment]
Commit d70bd19 is quite old, try updating. `bambu-studio` builds on master.

**Comment by FliegendeWurst** [comment]
It was fixed in #359120

https://nixpk.gs/pr-tracker.html?pr=359120

**Comment by ChrisOboe** [comment]
sorry for the bug report then.  i should have tried with master first instead of unstable-small
