### ISSUE TITLE
Build failure: rocm-llvm-libc-6.0.2

### ISSUE THREAD

**Issue by tecbeast42** [NixOS/nixpkgs#369360]
## Steps To Reproduce

1. build *rocm-llvm-libc-6.0.2*

## Build log

<details>

<summary>Build Log</summary>
<pre>
building the system configuration...
warning: download buffer is full; consider increasing the 'download-buffer-size' setting
error: builder for '/nix/store/axshsp2rv451cn9cqhn0djrcjdkr9l0b-rocm-llvm-libc-6.0.2.drv' failed with exit code 1;
       last 25 log lines:
       > [47/322] Building CXX object libc/src/math/generic/CMakeFiles/libc.src.math.generic.fminl.dir/fminl.cpp.o
       > [48/322] Building CXX object libc/src/math/generic/CMakeFiles/libc.src.math.generic.fmaxl.dir/fmaxl.cpp.o
       > [49/322] Building CXX object libc/src/math/generic/CMakeFiles/libc.src.math.generic.fmaxf.dir/fmaxf.cpp.o
       > [50/322] Building CXX object libc/src/math/generic/CMakeFiles/libc.src.math.generic.fdim.dir/fdim.cpp.o
       > [51/322] Building CXX object libc/src/math/generic/CMakeFiles/libc.src.math.generic.fdiml.dir/fdiml.cpp.o
       > [52/322] Building CXX object libc/src/__support/StringUtil/CMakeFiles/libc.src.__support.StringUtil.signal_to_string.dir/signal_to_string.cpp.o
       > [53/322] Building CXX object libc/src/__support/StringUtil/CMakeFiles/libc.src.__support.StringUtil.error_to_string.dir/error_to_string.cpp.o
       > [54/322] Building CXX object libc/src/__support/File/CMakeFiles/libc.src.__support.File.file.dir/file.cpp.o
       > [55/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.memchr.dir/memchr.cpp.o
       > [56/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.stpcpy.dir/stpcpy.cpp.o
       > [57/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.strchrnul.dir/strchrnul.cpp.o
       > [58/322] Building CXX object libc/test/UnitTest/CMakeFiles/LibcUnitTest.dir/LibcTest.cpp.o
       > FAILED: libc/test/UnitTest/CMakeFiles/LibcUnitTest.dir/LibcTest.cpp.o
       > /nix/store/7sqn5142gh5asri8aqxvsvib9ii37fyq-rocm-llvm-clang-unwrapped-wrapper-6.0.2/bin/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/libc -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=gnu++17 -MD -MT libc/test/UnitTest/CMakeFiles/LibcUnitTest.dir/LibcTest.cpp.o -MF libc/test/UnitTest/CMakeFiles/LibcUnitTest.dir/LibcTest.cpp.o.d -o libc/test/UnitTest/CMakeFiles/LibcUnitTest.dir/LibcTest.cpp.o -c /build/source/libc/test/UnitTest/LibcTest.cpp
       > /build/source/libc/test/UnitTest/LibcTest.cpp:16:10: fatal error: 'cassert' file not found
       > #include <cassert>
       >          ^~~~~~~~~
       > 1 error generated.
       > [59/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.mempcpy.dir/mempcpy.cpp.o
       > [60/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.strcat.dir/strcat.cpp.o
       > [61/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.bcopy.dir/bcopy.cpp.o
       > [62/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.strcpy.dir/strcpy.cpp.o
       > [63/322] Building CXX object libc/src/string/CMakeFiles/libc.src.string.stpncpy.dir/stpncpy.cpp.o
       > [64/322] Building CXX object libc/test/UnitTest/CMakeFiles/TestLogger.dir/TestLogger.cpp.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/axshsp2rv451cn9cqhn0djrcjdkr9l0b-rocm-llvm-libc-6.0.2.drv'.
error (ignored): error: cannot unlink '"/tmp/nix-build-rocm-llvm-compiler-rt-6.0.2.drv-0/build/source"': Directory not empty
error: 1 dependencies of derivation '/nix/store/3c83kgmacpw1sghcgwjq4gi1k0i5nrdi-rocm-llvm-clang-wrapper-6.0.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/39kmlhjz5nh425ks9q8dgm2vpfimfypy-clr-6.0.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/48qbxdv47k8q4fn65ddhi8n8a6sn1ncj-rocm-clang.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vgl7bd3vpgm39ypph4l4h302ha1mdvsb-stdenv-linux.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7k4j08l1zx3701arci1kpnfrr6phg385-ollama-0.5.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ic3mzsdgag9xapps48fxvma60dngjsd5-rocm-smi-6.0.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8ir7nk1rjdsf32xbpma1mxslhfdqy7r2-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/326g3b3ih50x9dj39242qlfchrwpglf6-unit-ollama.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rry048pmjbgjhrp5ml7bj1p6a1wqwn0c-nixos-system-threadbeast-workstation-25.05.20241229.88195a9.drv' failed to build
</pre>
</details>

## Additional context

GPU 7900 XTX
CPU Threadripper 7970X
current unstable channel

## Notify maintainers

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Please update the issue title

**Comment by aktaboot** [comment]
same as #368672 ?

**Comment by tecbeast42** [comment]
looks like it, I will close this for #368672
