### ISSUE TITLE
flashplayer: download link broken (404)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#36945]
## Issue description

```
trying https://fpdownload.adobe.com/get/flashplayer/pdc/28.0.0.161/flash_player_npapi_linux.x86_64.tar.gz
...
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download flash_player_npapi_linux.x86_64.tar.gz from any mirror
builder for ‘/nix/store/lrqdm648mcgrf8pxgr1p7wjl27q0vw72-flash_player_npapi_linux.x86_64.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/2ql5psqy2zq5mpnws77mg6d0vgf1m5bd-flashplayer-28.0.0.161.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/fj3x9ksfp5cs3bxr6ar5p294zyxh1n50-firefox-58.0.2.drv’: 1 dependencies couldn't be built
```

### Steps to reproduce

```
  environment.systemPackages = with pkgs; [
    firefoxWrapper
  ];

  nixpkgs.config = {

      firefox = {
       enableAdobeFlash = true;
      };
  };
```
as described here: https://nixos.wiki/wiki/Chromium

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3150.c7f415b5225 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(davidak): `""`
 - channels(root): `"nixos-17.09.3150.c7f415b5225, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
Same file in chromium.

```
error: cannot download flash_player_ppapi_linux.x86_64.tar.gz from any mirror
builder for ‘/nix/store/5amdfg30b87gjv0c7qkwh5b5m3w7yicb-flash_player_ppapi_linux.x86_64.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/1sz73bfa0zfhirm0k59in6q35bfklgi0-flashplayer-ppapi-28.0.0.161.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/r3nak39g2q14gw39bh8wi00wck786jcf-chromium-65.0.3325.146.drv’: 1 dependencies couldn't be built
```

**Comment by dtzWill** [comment]
Backported update to 17.09 in 7ca656d8930864518e48fcc6c5c35560af0c42d5 and to 18.03 in 37b31ea04fef1ad1ef63b4e62b7ae23c96431702 .  Should be in next channel update!

**Comment by dtzWill** [comment]
Hmm channel update blocked on busybox fix, somewhat ironically: https://hydra.nixos.org/build/71020865/nixlog/1

:(.

**Comment by sib-null** [comment]
Looks like the build is still stuck...my NixOS upgrade still fails on downloading flashplayer.

In general, how does one see the build status of a package on hydra?

**Comment by davidak** [comment]
The channel 17.09 is updated and the problem fixed.

Now i can play my favorite flash game again, [GemCraft Labyrinth](http://armorgames.com/gemcraft-labyrinth-game/10317).

Thanks @dtzWill for backporting the fix!

**Comment by ae-mo** [comment]
I have a similar problem in `20.09.2106.ae47c79479a (Nightingale)`, `x86_64-linux`.

```
trying https://fpdownload.adobe.com/pub/flashplayer/pdc/32.0.0.445/flash_player_ppapi_linux.x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download source from any mirror
error: --- Error ---------------------------------------------------------------------------------------------------------------------------- nix-build
builder for '/nix/store/xbdrnhj7rwschzq69pjbyqsmj8yy2n8p-source.drv' failed with exit code 1
```
