### ISSUE TITLE
buildRustPackage does not apply patches

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#36952]
## Issue description

I developed a overlay for my imag project. imag does not (yet) ship a `Cargo.lock` in its project repository, so I created a `Cargo.lock` and provided it as patch next to the overlay, with the intention to apply this patch to the repository before building it.

Unfortunately does `buildRustPackage` not apply this patch and thus the overlay does not work:

```
ERROR: The Cargo.lock file doesn't exist

Cargo.lock is needed to make sure that cargoSha256 doesn't change
when the registry is updated.
```

Can we please change `buildRustPackage` so that it applies the patches right after fetching the repository?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by BadDecisionsAlex** [comment]
I have the exact same issue. I am trying to find a workaround.
Did you ever find a solution?

**Comment by matthiasbeyer** [comment]
Nope, not yet, sorry.

**Comment by sbourdeauducq** [comment]
@BadDecisionsAlex @matthiasbeyer use ``cargoPatches``.

**Comment by asymmetric** [comment]
I think this can be closed, `cargoPatches` is the way to go.
