### ISSUE TITLE
bcc: broken on 32 bit platforms

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#36951]
## Issue description

```bcc```  uses int128 which is not supported by our 32-bit compilers

```
/tmp/nix-build-bcc-0.5.0.drv-0/source/src/cc/frontends/b/type_helper.h:39:35: error: '__uint128_t' was not declared in this scope
     case UINT128_T: return sizeof(__uint128_t);                                                                                 
                                   ^~~~~~~~~~~                                                                                   
```

**Comment by dtzWill** [comment]
Looks like they don't support 32bit, so i think that the only problem here is that `meta.platforms` is wrong?

https://github.com/iovisor/bcc/issues/873 and others.

**Comment by volth** [comment]
>  i think that the only problem here is that meta.platforms is wrong?

then yes
