### ISSUE TITLE
Question: Why doesn't overrideAttrs preserve passthru?

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#36987]
I bet there's a good reason, but I can't figure it out.

This will fail as a NixOS kernel, because there are assertions in place in the module system that look for certain features in `passthru`:

```
self: super: {
  linux = super.linux.overrideAttrs (oldAttrs: {
    # actual overrides
  });
}
```

Of course, we can always plumb it by hand...

```
self: super: {
  linux = let old = super.linux; in old.overrideAttrs (oldAttrs: {
    passthru = old.passthru;
    # actual overrides
  });
}
```

**Comment by teto** [comment]
I had the same problem when overriding the neovim wrapper. Would be cool to know :)

**Comment by dezgeg** [comment]
It's not actually `overrideAttrs` which is the problem but how the kernel expression is written. Typically the problem is modifying the result of `mkDerivation` in some way. E.g. try:

`test1.nix`:
````
{ stdenv }:

stdenv.mkDerivation {
  buildCommand = ''echo foo'';
  passthru.foo = 1;
}
````

`test2.nix`:
````
{ stdenv }:

(stdenv.mkDerivation {
  buildCommand = ''echo foo'';
  passthru.foo = 1;
}) // { foo = 2; }
````

`test0.nix`:
````
with import <nixpkgs> {};
rec {
  test1 = callPackage ./test1.nix {};
  test1' = test1.overrideAttrs (attrs: { buildCommand = ''echo bar''; });
  test2 = callPackage ./test2.nix {};
  test2' = test2.overrideAttrs (attrs: { buildCommand = ''echo bar''; });
}
````

And nix-repl:

````
Loading ‘test0.nix’...
Added 4 variables.

nix-repl> test1.foo
1

nix-repl> test1'.foo
1

nix-repl> test2.foo
2

nix-repl> test2'.foo
1
````

**Comment by srhb** [comment]
@dezgeg Doh, of course. Thank you for sorting out that misconception. I'd seen it before and made the wrong assumption. :)

**Comment by dezgeg** [comment]
You could make a bug for rewriting the kernel expression to be compatible with overrideAttrs, though.
