### ISSUE TITLE
xfce: processing3 and mucommander fail with "GLib-GIO-ERROR"

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#36982]
## Issue description

```processing3``` and ```mucommander``` (both are Java apps) crash on start with:

```(process:16395): GLib-GIO-ERROR **: No GSettings schemas are installed on the system```

There is no problem with Plasma5 and IceWM, only XFCE

Adding ```wrapGAppsHook``` does not help, the issue seems to be trickier that typical ones with the same symptom, involving java and opengl

### Steps to reproduce

```
# processing
```

## Technical details

```master``` + PR https://github.com/NixOS/nixpkgs/pull/36851

**Comment by balsoft** [comment]
Telegram-Desktop actually fails with the same error upon trying to change it's theme. I believe that it's related to https://github.com/NixOS/nixpkgs/issues/26560 .
