### ISSUE TITLE
grub: terminal_output console

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#37013]
## Issue description
I'm trying to set up serial console, and for that I need to change "terminal_output gfxterm" to "terminal_output console"  in grub conf. But it seems to be hardcoded in nixos/modules/system/boot/loader/grub/install-grub.pl  and if I replace it in Perl file, my change will be overwritten during update. Is there any good way to change that permanently on my server?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0pre5968_a6c0b773`
 - channels(lf): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by nixy** [comment]
You should be able to just add `terminal_output console` in `boot.loader.grub.extraConfig`.

I had to do something similar to this for the GRUB setup on Linode, this [guide](https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/) has a small example of grub config with additional `terminal_output` lines.

**Comment by Izorkin** [comment]
This method does not work. The first parameter "terminal_output gfxterm" is triggered.
