### ISSUE TITLE
asciidoc-full depends on Java

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#37045]
Since `jre` is provided by the non-free `oraclejdk` on aarch64, I'm not able to install asciidoc-full or any software that requires it to create e.g. the man pages.
Can we make `enableFop` an option different from `enableStandardFeatures`?

/cc @bjornfor

**Comment by bjornfor** [comment]
If making new granular options is fine, but I think enableStandardFeatures should still include java. (Or else the option is dishonest.)

Alternatively, can we switch to openjdk (assuming that works on aarch64)?

**Comment by dotlambda** [comment]
It was just recently changed to `oraclejdk` in https://github.com/NixOS/nixpkgs/pull/35510.
I'm fine with granular options, even though it will be quite some work to make packages not use `asciidoc-full` anymore.

**Comment by bjornfor** [comment]
Oh, so this problem is due to _licensing_, not wanting to use non-free software? I didn't pick up on that earlier.

How about adding a disableJava option, that has priority over enableStandardFeatures? Hm, this feels like a local solution to a global problem.

**Comment by dotlambda** [comment]
`disableJava` is a good idea! What do you think should be the default?

**Comment by bjornfor** [comment]
If enableStandardFeatures is true, you should get java. Setting disableJava then enables standard features except those requiring java.

I'm not sure if doing this (per package) is a good idea though. Isn't this the start of a new whack-a-mole game?

**Comment by dotlambda** [comment]
Yes, it's certainly not a perfect solution, but I can then use an overlay which sets `disableJava = true` for `asciidoc-full`.
Alternatively, we could set enable Java for x86 only by default.

**Comment by mpickering** [comment]
Perhaps it would be less confusing to have `enableJava = true` so the additive condition is positive.
