### ISSUE TITLE
QGIS problem with ~/.qgis2/qgis.db permissions

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#37042]
## Issue description

Upon installing qgis, and launching it on 17.09, and then shutting it down and relaunching, it gives an error saying:

```
Update of view in private qgis.db failed. table vw_srs already exists
```

The problem is that `~/.qgis2/qgis.db` has been given the wrong permissions. That is `r--r--r--` for some reason. The solution is to `chmod u+w ~/.qgis2/qg,is.db`.

This problem has been reported on QGIS issues before and they are just saying that the permissions need to be changed.

But I'm not sure if this is a problem in how qgis is packaged in nixos, or a problem within qgis.

**Comment by mpickering** [comment]
This doesn't happen for me on darwin.

**Comment by lsix** [comment]
Hi,

This problem have been fixed upstream (see https://github.com/qgis/QGIS/pull/7263) and will not be present in QGIS-3.

The fix has been backported in NixOS for QGIS-2.18 (https://github.com/NixOS/nixpkgs/pull/54554).

I close the issue.

**Comment by lopsided98** [comment]
I'm still running into this issue with QGIS 3.10.4.

**Comment by lsix** [comment]
@lopsided98 I’ll try to have a look ASAP.

I can reproduce the issue, note sure why the original fix does not cover it.

In the meantime you can `chmod -R u+w ~/.local/share/QGIS` as a work around.

**Comment by lopsided98** [comment]
Yes, manual chmod fixes it.

**Comment by lsix** [comment]
I created a PR upstream to fix the resurgence of the issue (https://github.com/qgis/QGIS/pull/37869)
