### ISSUE TITLE
ES_JVM_OPTIONS is ignored with Elasticsearch 6

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#37102]
Continued from https://github.com/NixOS/nixpkgs/commit/3230645c5a6572697f23b4a89c43003774adac09#r28103786

I'll try to find out what the fix is and then PR it.

CC @basvandijk

**Comment by nh2** [comment]
Another insight: This line https://github.com/NixOS/nixpkgs/blob/3230645c5a6572697f23b4a89c43003774adac09/nixos/modules/services/search/elasticsearch.nix#L169-L171 sets `ES_PATH_CONF` which is [still supported](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_packaging_changes.html#_literal_path_conf_literal_is_no_longer_a_configurable_setting), and here https://github.com/elastic/elasticsearch/blob/v6.1.2/distribution/src/main/resources/bin/elasticsearch#L25-L27 the `jvm.options` under `ES_PATH_CONF` is added to `ES_JVM_OPTIONS`, however [in `parse_jvm_options` that path is kicked out again if it doesn't exist](https://github.com/elastic/elasticsearch/blob/v6.1.2/distribution/src/main/resources/bin/elasticsearch#L19-L23), and on NixOS it doesn't exist: on NixOS the contents of that dir are like

```
# ls -lah /nix/store/l5h2ijhmcfg3rgq53n8879fp7cj15ixz-elasticsearch-config
total 92K
dr-xr-xr-x   3 root root   4.0K Jan  1  1970 .
drwxrwxr-t 559 root nixbld  72K Mar 15 12:00 ..
lrwxrwxrwx   1 root root     79 Jan  1  1970 elasticsearch.yml -> /nix/store/gbrv0mpvmmq16145kpdirbf98dbpsnqj-elasticsearch.yml/elasticsearch.yml
lrwxrwxrwx   1 root root     79 Jan  1  1970 log4j2.properties -> /nix/store/vamxp3gn7nw9xvyb6vzh1fvk1pdrlbfd-log4j2.properties/log4j2.properties
dr-xr-xr-x   2 root root   4.0K Jan  1  1970 scripts
```

so there's no `jvm.options` in there. Until now it was placed at a different path

```
ES_JVM_OPTIONS="/nix/store/7c06x54qs9ms85z86kkzl6dcxwx9i8lb-elasticsearch-6.1.2/config/jvm.options"
```

where `ES_JVM_OPTIONS` is the env var newly ignored in ES 6.

**Comment by nh2** [comment]
@basvandijk another question: In https://github.com/NixOS/nixpkgs/commit/3230645c5a6572697f23b4a89c43003774adac09#diff-2d12e9f116784c475c19d55f07fee064L8

```diff

   es5 = builtins.compareVersions (builtins.parseDrvName cfg.package.name).version "5" >= 0;
+  es6 = builtins.compareVersions (builtins.parseDrvName cfg.package.name).version "6" >= 0;
```

did you intend that for ES 6, both `es5 = true` and `es6 = true`? Because that is what happening.

So if in the current configs it says `if es5 ...`, that also applies to `es5`.

As a result, it's not clear to me what `else` branches like [this one](https://github.com/NixOS/nixpkgs/blob/3230645c5a6572697f23b4a89c43003774adac09/nixos/modules/services/search/elasticsearch.nix#L113) are for; are they for versions of Elasticsearch < 5?

**Comment by basvandijk** [comment]
> did you intend that for ES 6, both es5 = true and es6 = true?

Yes I think I did. The variables could better be named something like `esGE5` and `esGE6` as in Greater or Equal to.

**Comment by nh2** [comment]
According to https://github.com/NixOS/nixpkgs/pull/36456#issuecomment-379507293, this was fixed in https://github.com/NixOS/nixpkgs/pull/36456/commits/ae94825b4a1aa3c5a8344beb91a139467352f53b.
