### ISSUE TITLE
paraview needs numpy for Python Calculator filter

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#37118]
## Issue description

To use the Python Calculator filter in paraview, numpy is needed. If I try to use it with a freshly installed paraview I get:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/nix/store/d92k2xxkhxqy3r0wz432pg4jv7p90gm6-paraview-5.4.1/lib/paraview-5.4/site-packages/paraview/calculator.py", line 9, in <module>
    raise RuntimeError ("'numpy' module is not found. numpy is needed for "\
RuntimeError: 'numpy' module is not found. numpy is needed for this functionality to work. Please install numpy and try again.
```

I've tried to modify the derivation to include `pythonPackages.numpy` in the `buildInputs`, but it doesn't appear in the dependency list and the error persists:

```
$ nix-store --query --references $(which paraview)
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131
/nix/store/4zd34747fz0ggzzasy4icgn3lmy89pra-gcc-7.3.0-lib
/nix/store/wrljfs7v9l21gwh0gnnz159a4sc187mm-libICE-1.0.9
/nix/store/jy5wkghf5949bc3cqlr8c4jh4098xn7x-libSM-1.2.2
/nix/store/nhdz0xslz3p73k467lcakn8xspbg5kwv-libX11-1.6.5
/nix/store/01hk16xsvma9mvjyfz522y0yynkfn8fq-qtbase-5.10.1
/nix/store/1zqfiackp7v4pnic60sv9f6rp3ll5zyf-qttools-5.10.1
/nix/store/25j1sxq49nbgk3mkw3fgr1965a0qlwa9-libXext-1.3.3
/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14
/nix/store/7gkfw0hq9jpy92wlqlv67vgddpzj04ga-mesa-17.3.3
/nix/store/93mph3v3kl40dz4bfxp0y4cp0hrlf4n8-qtbase-5.10.1-bin
/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1
/nix/store/dw3hk31n2k3z4v9fgv0wa9x7jmzfv83y-qtx11extras-5.10.1
/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0
/nix/store/mnjhza4y211xkr311a2xygirndrqa7sd-libXt-1.1.5
/nix/store/w68c6s4vmhamcpj5bnm7gs8w6imn9igl-qtbase-5.10.1-dev
/nix/store/790sp9iy9ydci0cb03jkb5v84py1whlj-paraview-5.4.1
```

### Steps to reproduce

Apply a Python Calculator to a dataset and try to access the arrays, e.g. `inputs[0].PointData['foo'] `.

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/dzvh4f6ihkwg44mmf2awxg564k1s8khg-nix-info
copying path '/nix/store/dzvh4f6ihkwg44mmf2awxg564k1s8khg-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-116-generic, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(frijters): `"nixpkgs-18.03pre130569.7a04c2ca296"`
 - nixpkgs: `/home/frijters/.nix-defexpr/channels/nixpkgs`
```

**Comment by dotlambda** [comment]
I think you need to use
```
paraview.override {
  python = python.withPackages (ps: with ps; [ numpy ]);
}
```

**Comment by SFrijters** [comment]
But the Python Calculator functionality is a built-in thing for Paraview, shouldn't numpy be included by default? According to https://www.paraview.org/Wiki/ParaView/Binaries numpy is included in the official binary releases.

**Comment by dotlambda** [comment]
Ah sorry, I thought it was something optional. Feel free to open a PR and don't forget to ping @viric and @dguibert.

**Comment by SFrijters** [comment]
I probably need a bit of help here; I tried to fix it in the following way:

```
diff --git a/pkgs/applications/graphics/paraview/default.nix b/pkgs/applications/graphics/paraview/default.nix
index 42b69e24926..e9f833d757f 100644
--- a/pkgs/applications/graphics/paraview/default.nix
+++ b/pkgs/applications/graphics/paraview/default.nix
@@ -31,6 +31,8 @@ stdenv.mkDerivation rec {
     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
   '';
 
+  pythonWithNumpy = python.withPackages (ps: with ps; [ numpy ]);
+
   enableParallelBuilding = true;
 
   nativeBuildInputs = [
@@ -38,7 +40,7 @@ stdenv.mkDerivation rec {
   ];
 
   buildInputs = [
-    python
+    pythonWithNumpy
     libGLU_combined
     libXt
     qtbase
```

But at runtime, numpy is still not found (paste from the Python Shell inside Paraview):

```
Python 2.7.14 (default, Sep 16 2017, 17:49:51) 
[GCC 7.3.0] on linux2
>>> from paraview.simple import *
>>> import numpy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named numpy
>>> sys.path
['/nix/store/xs5hdy1l9dilg30ls3msdz49pyhhid2k-paraview-5.4.1/lib/paraview-5.4/site-packages/vtk', '/nix/store/xs5hdy1l9dilg30ls3msdz49pyhhid2k-paraview-5.4.1/lib/paraview-5.4/site-packages', '/nix/store/xs5hdy1l9dilg30ls3msdz49pyhhid2k-paraview-5.4.1/lib/paraview-5.4', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python27.zip', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/plat-linux2', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/lib-tk', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/lib-old', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/lib-dynload', '/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/site-packages']
```

The paths `sys.path` are not what I expected: `/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/site-packages`, but numpy is installed in the `-env` python path: `/nix/store/8z84948qcvmrfk29jl4bqpjaf80nqbyd-python-2.7.14-env/lib/python2.7/site-packages`. Maybe I misunderstand something about how the python environment is set up...

**Comment by dotlambda** [comment]
You might have luck adding `-DPYTHON_EXECUTABLE=${pythonWithNumpy.interpreter}` to `cmakeFlags`. See https://gitlab.kitware.com/paraview/paraview/blob/master/CMakeLists.txt#L563.
Btw, I think it's better to name it just `python` instead of `pythonWithNumpy`.

**Comment by SFrijters** [comment]
Thanks, I tried the above, but although I'm only seeing references to the `-env` path in the build logs, and even when looking inside the binaries with `ldd`, at runtime python still insists on using the non-`-env` path as its search path, so it still doesn't find the `numpy` module. Not sure what is going on there.

I also tried using just `python` as you suggested, but then I got a recursive definition `python = python.withPackages (ps: with ps; [ numpy ]);` and Nix freaked out. I probably misunderstood your suggestion.

**Comment by dotlambda** [comment]
That's strange. Maybe @FRidh can help.

Yeah, you're right. Didn't think about the recursion. You could do something like taking `python2` as argument instead of `python`.

**Comment by FRidh** [comment]
I think the reason it does not work is that they link into the Python library, resolving symbolic links on the way. I see two possible solutions here:
- Add numpy to PYTHONPATH
- Don't use withPackages to create symbolic links, but actually copy the contents of the packages into a new expression. This is not nice.

**Comment by SFrijters** [comment]
I've opened PR on this issue.
