### ISSUE TITLE
mpd: doesn't send audio to localhost on tcp

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#37131]
## Issue description
As per the [arch wiki](https://wiki.archlinux.org/index.php/Music_Player_Daemon/Tips_and_tricks#Local_.28with_separate_mpd_user.29).

> Mar 15 13:03:20 okinan mpd[4517]: exception: "Local Music Player Daemon" [pulse] failed to play: suspended
> Mar 15 13:03:20 okinan mpd[4517]: exception: "Local Music Player Daemon" [pulse] failed to play: suspended
> Mar 15 13:03:20 okinan mpd[4517]: exception: "Local Music Player Daemon" [pulse] failed to play: suspended
> Mar 15 13:03:20 okinan mpd[4517]: exception: Failed to open audio output

Related configuration:
`hardware.pulseaudio.extraConfig = "load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1";`

`services.mpd = {`
`  ...`
`  extraConfig = ''`
`    ...`
`    audio_output {`
`      type    "pulse"`
`      name    "Local Music Player Daemon"`
`      server  "127.0.0.1"`
`    }`
`  '';`
`};`

### Steps to reproduce
Install and enable mpd audio output to 127.0.0.1 for pulseaudio.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jfrankenau** [comment]
Does this happen for you on 17.09 as well? I've got the same setup there and it works fine.

**Comment by Chiiruno** [comment]
@jfrankenau I'll have to check, but now that you mention it, this did start with some sddm change and there being a new pulseaudio instance for sddm after and update.

**Comment by Chiiruno** [comment]
After a new install, now I'm getting this error message instead.
`player: Decoder is too slow; playing silence to avoid xrun`
