### ISSUE TITLE
Build nix: error: opening file '/proc/813/maps': Permission denied

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#37157]
Hello,

First, thank you for the great work. Then, I have an error when I try to build nix on my lab computer:

## Issue description

When I try to build nix, from nix, and a device where I don't have root access, that is on a NFS system, and though nix-user-chroot, it fails to pass tests with lots of errors like:

    running test tests/nix-build.sh... [FAIL]
    [....]
    error: opening file '/proc/813/maps': Permission denied

Full error: [error.txt](https://github.com/NixOS/nixpkgs/files/1817813/error.txt)

### Steps to reproduce

Because of [this bug](https://github.com/NixOS/nixpkgs/issues/29778), I need to compile it with special options. To do that, I bootstrap it on another computer, by using the formula:

```
let nix = (import <nixpkgs> {}).nix.overrideAttrs(oldAttrs: {
  prePatch = ''
    substituteInPlace src/libstore/local-store.cc \
    --replace '(eaName == "security.selinux")' \
    '(eaName == "security.selinux" || eaName == "system.nfs4_acl")'
  '';
});
in
  (import <nixpkgs> {}).callPackage <nixpkgs/nixos/lib/make-system-tarball.nix> {
    storeContents = [ { object = nix; symlink = "/nix"; }]; 
    contents = [];
}

```
and I build it using `nix-build formula.nix`. Then I send  the tar file contained in the `result/tarball` folder to the machine B. I untar it, put the `nix/` folder into a local folder, and using =nix-user-chroot=, I bind mount this local folder into /nix. Then, I manually move into the `/nix/store/*-nix-*/bin` hash folder, and I define the channel to use, and load the environment:

    . ../etc/profile.d/nix.sh
    ./nix-channel --add https://nixos.org/channels/nixpkgs-unstable
    ./nix-channel --update

And I try it, the last command works great:

    ./nix-env -i mbsync

And mbsync appear in the folders inside my path. But `nix-*` commands still do not appear in the binary files in the `PATH`. So I try to install nix again, disable the tests, and I edit `~/.config/nixpkgs/config.nix` into
```
{ 
  packageOverrides = pkgs: {
    nix = pkgs.nix.overrideAttrs(oldAttrs: {
      doCheck = false;
      prePatch = ''
        substituteInPlace src/libstore/local-store.cc \
          --replace '(eaName == "security.selinux")' \
                    '(eaName == "security.selinux" || eaName == "system.nfs4_acl")'
      '';
    });
  };
}

and I build it using

    ./nix-env -iA nixpkgs.nix

I don't know why, but it does not follow the `doCheck = false` assumption (while it compiles nix), and lot's of tests fail with the error:

    finding garbage collector roots...
    error: opening file '/proc/813/maps': Permission denied

(ex : `tests/nix-build.sh... [FAIL]`)
Finally, it "freeze" just after:

    running test tests/fixed.sh... [PASS]

And I need to abort after a few minutes.
## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

The first time I got errors because `nix-env` are not in my path (no idea why, because the installed programs with nix are already in my path), and after updating the path, I get:

```
$ ./nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-96-generic, Ubuntu, 16.04.3 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(lcolisson): `"nixpkgs-18.09pre132003.13e74a838db"`
 - nixpkgs: `/users/serv/me/.nix-defexpr/channels/nixpkgs`
```

**Comment by dtzWill** [comment]
This appears to be an issue for Nix, not nixpkgs.  The nix issue tracker is here: https://github.com/NixOS/nix/issues .  Please open an issue there so it gets the right attention.

Closing because this is the wrong tracker, but please do open an issue over there! :+1:

**Comment by tobiasBora** [comment]
Ok thank you, and sorry for the wrong issue report. For people interested, here is the new report : https://github.com/NixOS/nix/issues/1996
