### ISSUE TITLE
flip arguments in `haskell.lib`

### ISSUE THREAD

**Issue by angerman** [NixOS/nixpkgs#37177]
## Issue description

I'm running into this over and over again when working with haskell packages.
Many of the non-binary functions in pkgs/development/haskell-modules/lib.nix are of
the form
```
<verb><property(s)> = drv: x: ...
```
e.g. `enableCabalFlags` or `addExtraLibraries`.

This ends up as
```
enableCabalFlag (addExtraLibrary (dontHaddock (disableSharedLibraries myPackage)) someOtherPackage) "someFlag")
```
I'd rather we flip the arguments. That way currying them would work better as well.
```
enableCabalFlag "someFlag" (addExtraLibrary someOtherPackage (dontHaddock (disableSharedLibraries myPackage)))))
```
Another point to me is that this keeps the "do" and "what" together, which makes
reading this (especially when it get's a more complicated) much easier.

Yes, I'm aware this would be a breaking change.

**Comment by mpickering** [comment]
I agree with this but it would break a lot of code.

**Comment by coretemp** [comment]
I am also in favor, but you'd have to write a compiler if you don't want to upset people.

**Comment by peti** [comment]
I agree with that change in principle, too, but IMHO the practical cost of that change is far too high to be worth the benefit.

**Comment by expipiplus1** [comment]
How about creating a separate module for this `haskell-modules/lib/flipped.nix`. 

There's certainly a maintenance overhead in maintaining both modules, but being able to do: `fold [dontCheck (addBuildTool perl) markUnbroken] myPackage` might outweigh that burden?

It might even be the case that this flipped module could be generated automatically from `haskell-modules/lib.nix` (or vice versa).

**Comment by expipiplus1** [comment]
I've opened a PR which adds `lib-flipped` to `haskell`: https://github.com/NixOS/nixpkgs/pull/100732, as well as a little tool to do the flipping (much easier than going through 16 definitions by hand: https://github.com/expipiplus1/nix-flipper
