### ISSUE TITLE
Bot comments are distracting

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#37181]
## Issue description
I am interested in seeing issues which have comments on them, but the bot(s) also generate comments, but I am not interested in those. Doesn't GitHub have some interface to filter out such comments in the web UI?

One used to be able to easily identify issues which nobody responded to, but that operation is now gone.

**Comment by vcunat** [comment]
If it's about issues, the bot doesn't talk there AFAIK (only on PRs).  I don't think GitHub has any way.  The bot's account isn't even a special one.  /cc @grahamc.

**Comment by matthewbauer** [comment]
I agree w.r.t. @GrahamCOfBorg. It usually does 3 comments about the build status per PR.

> Doesn't GitHub have some interface to filter out such comments in the web UI?'

AFAIK, no option for "hiding" comments, but some APIs might give similar functionality. Two options I think might be doable:

- Add build updates to end of PR body text (needs permissions). Fairly straightforward but could conflict with user editing text manually.
- Use the "statuses API". This was already done for "eval" but not for "build" - don't know if there was a reason for doing this. You can provide text and a URL that accompanies this.

**Comment by 7c6f434c** [comment]
>- Use the "statuses API". This was already done for "eval" but not for "build" - don't know if there was a reason for doing this. You can provide text and a URL that accompanies this.

There is a reason not to use status API — the goal is to have straightforward «never merge on red status» rule, and builds can, at the very least, timeout.

**Comment by matthewbauer** [comment]
> the goal is to have straightforward «never merge on red status» rule, and builds can, at the very least, timeout

Ok, I see the issue now.

An ugly hack around this would be to always report a build as "success" but also provide text saying that the build failed and a link to the log.

**Comment by 7c6f434c** [comment]
Apparently there is another slightly less ugly huck worth investigating, so maybe in the medium run the situation will improve.

**Comment by rnhmjoj** [comment]
Maybe ofBorg could post a comment with the first build result and edit it later adding new results.

**Comment by 7c6f434c** [comment]
Comment editing requires keeping more state than ofBorg currently keeps, apparently. There is a hope to just use statuses with proper separation of blocking and nonblocking failures.

**Comment by matthewbauer** [comment]
> There is a hope to just use statuses with proper separation of blocking and nonblocking failures

This reminds me of the issue we used to have with Travis though: if one status "errors" then the whole PR fails. Here are the rules from GitHub:

```
Additionally, a combined state is returned. The state is one of:

failure if any of the contexts report as error or failure
pending if there are no statuses or a context is pending
success if the latest status for all contexts is success
```

From https://developer.github.com/v3/repos/statuses/

It seems kind of weird, but it looks like the only way a PR can have the "green checkmark" is when all checks succeed.

**Comment by 7c6f434c** [comment]
Even a third-state would be OK: yellow means some things require attention and judgement. But no…

**Comment by FRidh** [comment]
I completely agree. Because we don't control the GH UI, and OfBorg is still a work-in-progress I'm inclined to closing this issue though..

**Comment by Ekleog** [comment]
(triage) I don't think it's possible to do much better than is currently done (well, maybe editing a first post would make for less noise indeed, but it'd still be a comment so that wouldn't solve @coretemp's issue AFAIU).

But anyway, shouldn't this issue be in https://github.com/NixOS/ofborg ? :)

**Comment by vcunat** [comment]
Yes, it belongs there.  I should add that there's been change on GitHub in the meantime, and the new "checks" tab would probably be ideal for borg's comment.

**Comment by vcunat** [comment]
I opened https://github.com/NixOS/ofborg/issues/231
