### ISSUE TITLE
jetbrains.rider: debug mode doesn't work cause of hard-coded path to 'stat'

### ISSUE THREAD

**Issue by svsdep** [NixOS/nixpkgs#37251]
## Issue description
JetBrains Rider binary has hard-coded path to 'stat' -- /usr/bin/stat, util which is required for debugging of .Net Core applications.
Reported the issue to JetBrains with the details: https://youtrack.jetbrains.com/issue/RIDER-14393

### Steps to reproduce
1. Create .Net Core project from template.
2. Put a breakpoint in code.
3. Try to run it in debug mode.

**Comment by razvan-panda** [comment]
@svsdep For me Rider can not even open solution files - it shows as permanently loading.
I symlinked `stat` to see if that fixes the debugging issue but it just runs in another error.

**Comment by baracoder** [comment]
According to upstream this is fixed  in	2018.2 EAP8 182.4231.90
Did anyone try with this version?

**Comment by baracoder** [comment]
I have with 2018.2 which was released today, debug mode fails with a different message: `One or more errors occurred.` and no more details

**Comment by jdanekrh** [comment]
I think this can be closed as it was resolved upstream. I've filled a new issue https://github.com/NixOS/nixpkgs/issues/55435 for the "One or more errors occurred." error, which has different cause.

**Comment by razvan-flavius-panda** [comment]
I tested again with `jetbrains.rider` from `20.03` channel together with `dotnet-sdk` and placing a breakpoint and running it in debug mode works fine.
