### ISSUE TITLE
No manual entry for nixos-rebuild without the nixos manual service enabled

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#37282]
## Issue description

The manual entry for `nixos-rebuild` is missing without enabling the NixOS manual service. The reference manuals for all standard Nix and NixOS tools should be available by default and access to them should be unrelated to the generation of a customized manual. For example, I want access to all reference manuals, but I do not want the overhead of generating customized manuals, since I prefer to check the online manuals anyway.

### Steps to reproduce

In your `configuration.nix`:
```
services.nixosManual.enable = false;
```

Gives the following result: 
```
> man nixos-rebuild
No manual entry for nixos-rebuild
```

While this in your `configuration.nix`:
```
services.nixosManual.enable = true;
```

Gives the following result: 
```
> man nixos-rebuild
...
NAME
       nixos-rebuild - reconfigure a NixOS machine
...
```
## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.116, NixOS, 17.09.git.4daffb9 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0` (from nixos-unstable around 5 Mar)
 - channels(root): `""`
 - channels(matthijs): `""`
 - nixpkgs: `/wheel/fork/nixpkgs` (nixos-17.09 around 22 Feb)

**Comment by dje4321** [comment]
It would be helpful to be able to see what options are even available in nixos-rebuild without wasting space on a manual

**Comment by jpotier** [comment]
@dje4321 there's https://nixos.org/nixos/options.html if you have internet connection, otherwise you can also use a local and interactive approach with the `nixos-option` command.

**Comment by ivan** [comment]
In case anyone is confused about `services.nixosManual.enable` being gone: the option you need to have a man page for `nixos-rebuild` is now `documentation.nixos.enable`.

**Comment by samueldr** [comment]
I believe this is not an issue since #248701.

If this is wrong, feel free to re-open and/or comment about your observations.
