### ISSUE TITLE
qutebrowser spellcheck doesn't work

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#37307]
## Issue description
When I run:
```
/nix/store/h8j3b3la9pd0j2a4z5cx1w8k24371jkh-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py install en-US
```
I get:
```
Traceback (most recent call last):
  File "/nix/store/h8j3b3la9pd0j2a4z5cx1w8k24371jkh-qutebrowser-1.2.0/share/qutebrowser/scripts/dictcli.py", line 34, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.27-rt21, NixOS, 18.03.git.a619890 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(bart): `""`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
The scripts installed in `share/qutebrowser/scripts` have not been patched. I'm working on it.

**Comment by magnetophon** [comment]
@rnhmjoj Great, thanks!
