### ISSUE TITLE
stgit no longer available at gna.org

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#37339]
From stgit http://www.procode.org/stgit/
> Unfortunately, the original project page hosted at gna.org is no longer available. An earlier snapshot is still accessible via the Wayback Machine. In the meantime, the project page is being migrated to GitHub and the StGit mailing list to Google Groups.

The new code is at https://github.com/ctmarinas/stgit

cc maintainer @the-kenny

**Comment by c0bw3b** [comment]
Solved in fc03888

**Comment by ryantm** [comment]
Cool, I solved my own issue without noticing. Thanks @c0bw3b for tracking it down.

**Comment by vcunat** [comment]
`/archive/` tarballs from github are generated AFAIK, so I'd fear the hash won't be stable.

**Comment by c0bw3b** [comment]
Indeed @vcunat it's a pitfall that `nixpkgs-update` tool does not check. I'll open an issue on its repo.
