### ISSUE TITLE
Firefox Wrapper & Chromium have a very limited mime type list

### ISSUE THREAD

**Issue by benkolera** [NixOS/nixpkgs#37366]
## Issue description
Both firefox-wrapper and chromium seem to rely on the OS to get a list of extensions to mime types. On firefox-wrapper and chromium on nixos-17.09, neither browser can guess the mime type of an xlsx file.

xdg knows about the extension, but clearly neither browser consults that. 
```
$ xdg-mime query filetype ~/Downloads/foo.xlsx
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

### Steps to reproduce
Here is a small jsfiddle that can be used to show that the file upload form element returns a type for a pdf file but not an xlsx.

https://jsfiddle.net/q89vbo4q/31/

Copying /etc/mime.types from an ubuntu system to /etc/mime.types on my nixos system works around this issue for firefox but not chromium. Any thoughts from the people who know packaging firefox and chromium intimately?

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3159.c665fcca9e7 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3159.c665fcca9e7"`
 - channels(bkolera): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
I don't have a DE and so I have never used files associations but it seems pretty straightforward: just add more mime types [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/wrapper.nix#L89) and [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/default.nix#L44)

**Comment by benkolera** [comment]
That list appears to be the list of mime types that are linked to being
opened by a web browser. Say when you xdg-open a html file in a terminal or
click a file in your file browser.

This is a little different, isn't it? The information the browser needs is
information for a linking of *all* file extensions and mime types, not just
the mime types that are setup to be opened by a browser. The thing is, my
xdg-mime query shows that the system does know what which mime type an xlsx
is (and xdg-open knows how to open it with libre office) but the browser
just cannot find this information from NixOS (firefox is looking at
/etc/mime.types at least and I'm not sure where chromium is looking).

This is an issue for anyone in NixOS Chrome or firefox uploading files to a
web application which does some kind of javascript checking of the file
type before uploading if the type of file isn't something a browser cares
about like images/html/txt/pdf/etc. It may well be because I do not have a
DE either and the browsers are expecting to be able to talk to some other
file or api that isn't present / populated on my pure XOrg + XMonad system.
If we don't have any ideas, I may setup a separate setup with GNOME 3 or
something and see if that makes any difference. I'm not actually sure
whether the other DEs use xdg entirely or whether they mix in their own
stuff for file extensions.

We need to figure out where the browsers source this information and
whether it's configurable enough to weave in from Nix. If no one has any
ideas, I can do the detective work in the gecko/chromium code bases if
people want.

As per https://help.ubuntu.com/community/AddingMimeTypes, the mime.types
file has lines that look like the the following (and seems to be a fairly
large list and not tied to file-program associations [I got a mime.types
file off a ubuntu server and it still had xlsx even without any office
apps]). Given that that article seems to suggest that there are multiple
unrelated sources of this information (/etc/mime.types vs  /usr/share/mime/)
I guess that it's not surprising that FF and Chromium are different for
sourcing this list from the system.

application/x-python-code                       pyc pyotext/x-python
                                py

**Comment by benkolera** [comment]
I'd recommend closing this ticket. Relying on the browser to do mime type detection was flakey on pretty much every operating system so we just removed it entirely and went for a simple extension check.
