### ISSUE TITLE
thumbor doesn't work with Python 3

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#37362]
## Issue description

The expression at https://github.com/NixOS/nixpkgs/blob/0f6286cc4b82ab2568ed53f99977b54c8e67fc56/pkgs/development/python-modules/thumbor/default.nix is compatible with Python 3, but Thumbor itself does not support Python 3, see https://github.com/thumbor/thumbor/issues/1035. I think Thumbor should fail to build under Python 3 for now until it is actually supported.

### Steps to reproduce

https://github.com/thumbor/thumbor/issues/1035

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/37147

**Comment by FRidh** [comment]
cc @Ma27

**Comment by Ma27** [comment]
ouch, sorry!
Will file a patch in the afternoon:)

**Comment by vaibhavsagar** [comment]
I've opened https://github.com/NixOS/nixpkgs/pull/37363
