### ISSUE TITLE
psc-package fails to install on unstable

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#37374]
## Issue description

`psc-package` fails to install on unstable channel:

```
Setup: Encountered missing dependencies:
turtle ==1.3.*
```

### Steps to reproduce

`nix-env --install psc-package`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - channels(kai): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by marsam** [comment]
This is an issue in [psc-package](https://github.com/purescript/psc-package/pull/79), and [fixed in its master branch](https://github.com/purescript/psc-package/commit/cda2f0521c9d070d84d1a634454cc9b0aa05247f). You can use the following workaround meanwhile:
```nix
(psc-package.overrideAttrs (oldAttrs: {
  patches = [ (fetchpatch {
    url="https://github.com/purescript/psc-package/pull/79.patch";
    sha256="1ghlvp8bbaqfkca6j591smwbfjmn6yzib0khwbf9msfkzlcfcm9j";
  })];
}))
```

**Comment by marsam** [comment]
Closing because `psc-package` builds on `master` (b306b4cf1a9709dd8e671af6ebf75151e359e54f)
```
$ nix-build -A psc-package
/nix/store/srbm5b5a1vr4yh36001d8s8sz9cyw83v-psc-package-0.5.1
```
