### ISSUE TITLE
Download page should mention EC2 configuration via user data

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#37390]
The [download page](https://nixos.org/nixos/download.html) has handy links to launch EC2 instances, but it neglects to mention the coolest feature: That you can drop a NixOS config file into the user data when you launch, and it will automatically boot into that configuration. It is a shame to be omitting this from the documentation.

**Comment by matthewbauer** [comment]
I think this should go in nixos-homepage:

https://github.com/NixOS/nixos-homepage/blob/master/nixos/download.tt
