### ISSUE TITLE
browserpass 2.0.13 on NixOS 17.09

### ISSUE THREAD

**Issue by tiramiseb** [NixOS/nixpkgs#37426]
## Issue description

The browserpass extension broke backward compatibility with its host app, which must be upgraded in order to continue working.

In NixOS 17.09, the host app version has not been upgraded (see https://github.com/NixOS/nixpkgs/pull/37387 for the master branch).

### Steps to reproduce

Try to use the browserpass extension on NixOS 17.09...
You get message "Error: Native host has exited"

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by ysndr** [comment]
opened a PR (#37503) cherry-picking the named commit
