### ISSUE TITLE
Gsmartcontrol 0.8.7 -> 1.1.3 version bump needed, current package broken.

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#37444]
## Issue description
True issue: gsmartcontrol package needs version bump. Current version in 18.03 is from 2012 and does not support policykit/pkexec, hence failing to launch if none of the old gui "sudo" methods are installed.

-- -- -- --
**Original header for the record**: "Gsmartcontrol must implement pkexec method instead, currently requires legacy packages."

**Original issue for the record**:  
Currently gsmartcontrol is installed with a desktop file,  that launches it with user priviledges.
However root access for smartcontrol (smartmontools) to access hardware readouts like SMART table.

The desktop file in (/run/current-system/sw/share/applications/gsmartcontrol.desktop) calls the "/nix/store/0bk3hs34mwa8ss1q8w31cn2a6q5zj999-gsmartcontrol-0.8.7/bin/gsmartcontrol-root", which is a script that tries to guess the graphical "sudo" method.

However, the correct way is to invoke "pkexec" as its present by default and is current preferred way(?). Thus this application will need [policykit custom action](https://unix.stackexchange.com/questions/203136/how-do-i-run-gui-applications-as-root-by-using-pkexec)  and either gsmartcontrol-root should be modified with additional pkexec method (i think its a more flexible way), or completely replaced with pkexec method.

There is third way - to add requirement for gui-based sudo as dependency.

### Steps to reproduce
$ nix-env -i gsmartcontrol
launch gsmartcontrol from gui menu.

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.14.27, NixOS, 18.03pre131327.0e7c9b32817 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre131327.0e7c9b32817, nixos17.09-17.09.3159.c665fcca9e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
Polkit should be supported with GSmartControl 1.1.0, look at https://gsmartcontrol.sourceforge.io/home/

**Comment by cx405** [comment]
@jtojnar Oh, wow! The current package is from 2012!

**Comment by cx405** [comment]
@jtojnar Could I request backport of your fix to 18.03, when you have time, please? Its still 0.8.7 as of now.

**Comment by jtojnar** [comment]
Done.
