### ISSUE TITLE
extraGroups not working

### ISSUE THREAD

**Issue by cpakkala** [NixOS/nixpkgs#37590]
## Issue description
Any changes to users' extraGroups does not appear in /etc/group.  It used to work for me; I'm not sure what changed since adding my last group.  nixos-rebuild does not report any issues.

### Steps to reproduce
Add any new group to users.users.myuser.extraGroups and do a nixos-rebuild switch.

## Technical details                                                                                                               
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3189.fd016e362da (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3189.fd016e362da"`
 - channels(kyndig): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by cpakkala** [comment]
I was trying to add my user to the adbusers group and it turns out the group doesn't actually get created unless you set programs.adb.enable = true.  Setting extraGroups doesn't actually create a group, nor does it complain that the group doesn't exist when running nixos-rebuild.

**Comment by abhillman** [comment]
I ran into this -- note that despite running `nixos-rebuild switch`, one may need to re-login for groups to take effect in the given session.
