### ISSUE TITLE
Provide service configurations for Weston

### ISSUE THREAD

**Issue by campadrenalin** [NixOS/nixpkgs#3766]
Right now we have a Weston release, 1.5.0, in nixpkgs. But there is no easy way to do install that as a service, the way you can with other window managers (mind you Weston is a special case in many ways). We still ought to try to provide this.

**Comment by wmertens** [comment]
This is our oldest untouched issue. I will close this in the interest of removing clutter. I am sure that  other Weston users will come to the same conclusion and one of them might make it into a service.

If I am wrong I'm happy to reopen this, just respond.
