### ISSUE TITLE
simp_le is broken on nixos-unstable-small

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#37689]
## Issue description

`simp_le: error: unrecognized arguments: --tos_sha256 <hash>`

### Steps to reproduce

```nix
  services.nginx = {
    enable = true;
    virtualHosts.${host}.enableACME = true;
  };
```
Works at `cc4677c36ee8d880e881459ad114fd2224b3ac1c` (nixos-unstable)
Broken at `f83cbf20292cfde64e2df49bf0bd84338749c49e` (nixos-unstable-small)

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by wmertens** [comment]
Is this output from a test or from your application? See also https://github.com/NixOS/nixpkgs/pull/37493#issuecomment-375315734

**Comment by bachp** [comment]
For me the output is from the nginx `enableACME` option.

**Comment by wmertens** [comment]
Thanks for the pointers, I think I fixed it but I can't test it right now.

**Comment by gnidorah** [comment]
@wmertens Thank you!

**Comment by aszlig** [comment]
@wmertens: There is a VM test for [`acme`](https://github.com/NixOS/nixpkgs/blob/a0c525bd0a93fba70471392b8651882b52197788/nixos/tests/acme.nix) which you can use to test this. The error described here was already caught with that test, but it still seems that it's not yet entirely fixed:

```
webserver# [   16.370413] acme-example.com-start[781]: 2018-03-25 20:07:33,461:DEBUG:simp_le:1546: ('-v', '-d', 'example.com', '--default_root', '/var/lib/acme/acme-challenge', '--valid_min', '2592000', '-f', 'fullchain.pem', '-f', 'full.pem', '-f', 'key.pem', '-f', 'account_key.json') parsed as Namespace(account_key_public_exponent=65537, account_key_size=4096, cert_key_size=4096, default_root='/var/lib/acme/acme-challenge', email=None, help=False, integration_test=False, ioplugins=['fullchain.pem', 'full.pem', 'key.pem', 'account_key.json'], reuse_key=False, revoke=False, server='https://acme-v01.api.letsencrypt.org/directory', test=False, user_agent='simp_le/0.8.0', valid_min=2592000, verbose=True, version=False, vhosts=[Vhost(name='example.com', root=None)])
webserver# [   16.385653] acme-example.com-start[781]: 2018-03-25 20:07:33,470:DEBUG:simp_le:336: Loading fullchain.pem
webserver# [   16.387494] acme-example.com-start[781]: Not enough PEM encoded messages were found in fullchain.pem; at least 2 were expected, found 1.
webserver# [   16.390363] acme-example.com-start[781]: Debugging tips: -v improves output verbosity. Help is available under --help.
```

**Comment by aszlig** [comment]
@wmertens: Ah, okay, so this actually is a problem with the test itself, because we don't use an intermediate certificate there, fixing...

**Comment by wmertens** [comment]
yes I tried running that test through ofborg but the initial setup failed
somehow
