### ISSUE TITLE
quaternion seems to miss some (runtime) qt dependencies

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#37697]
## Issue description

quaternion outputs this when starting:

```
qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
qrc:///qml/chat.qml:2:1: module "QtQuick.Controls" is not installed
qrc:///qml/chat.qml:3:1: module "QtQuick.Controls.Styles" is not installed
```

Also, when clicking on a channel, the chat window stays blank (no messages shown). I think that's related to above output in some way(?).

### Steps to reproduce

`nix-shell -p quaternion --run quaternion` should do the trick, if not in a Qt environment anyways (like KDE). Maybe `--pure` can help here.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03pre130932.cc4677c36ee"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthiasbeyer** [comment]
Pinging @peterhoeg as quaternion maintainer.

**Comment by peterhoeg** [comment]
You need to install it in the global environment for it it work.

**Comment by matthiasbeyer** [comment]
Just to clearify: "global" as in `configuration.nix` or as in `nix-env -i`?

**Comment by matthiasbeyer** [comment]
Yeah so I installed it in `configuration.nix` and got this:

```
$ quaternion 
Debug:  false
Segmentation fault
```

:angry:

**Comment by matthiasbeyer** [comment]
Same with `cantata`.

**Comment by peterhoeg** [comment]
> Segmentation fault
> Same with cantata.

They both work fine here and have been for ages. I use cantata every day. Can you try using strace?

**Comment by matthiasbeyer** [comment]
Here you go with the last 5000 lines (because of file limit at pastebin, this is cantata):

https://pastebin.com/jZdaLMAH

**Comment by matthiasbeyer** [comment]
Am currently updating my thinkpad. Before the update, cantata worked. After the update (without reboot), cantata started as well. Cantata is here installed via `nix-env -IA nixos.cantata` and there is no update for it available... so I _assume_ that it works.

I just installed quaternion via `nix-env -iA nixos.quaternion` and it works, too.

**Comment by matthiasbeyer** [comment]
After that update, my telegram app crashes at startup. After `nix-env -u telegram-desktop` it works again.

**Comment by peterhoeg** [comment]
telegram-desktop is presumably a Qt application and with that in the user environment you ended up with conflicting Qt versions. I suggest you get rid of *all* Qt applications from the user environment and install them globally to avoid any unpleasant surprises.

**Comment by matthiasbeyer** [comment]
That seems to have fixed all my problems. Thanks for your support! :heart:
