### ISSUE TITLE
[Cross Compiling Haskell Packages] Split `Setup` into a separate derivation.

### ISSUE THREAD

**Issue by angerman** [NixOS/nixpkgs#37691]
When building haskell packges, we build the `Setup` binary, and in turn use it to build the package. And alternative would be to use `cabal-install`, which would in turn take care of running `Setup` or run the default for `build-type: Simple`.

This all is moot as long as we don't cross compile, as in that case it doesn't really make much of a difference.

Enter cross compiling: the `Setup` (or `cabal-install`) need to run (and be compiled for) the build machine. While the end product of the derivation is to run on the target of the ghc used.

What we now end up trying to do is, build the `Setup` in the derivation for the target, by swapping out the GHC and instead use the GHC that targets the build machine. As such the derivations environment ends up being some strange mixture of the build and target, and in some cases just falls apart.

To untangle this mess, I would like to propose to extract the building of the `Setup` into a separate derivation. This of course should be fully automated, as we do not want to have to create those for each haskell package.

Let us assume we have haskell package `x`. We split this into `x` and `x-Setup`. Now we build `x-Setup` with the `buildPackages` (this should hopefully; unless I'm mistaken) even automatically solve the issue of `setupBuildDepends` to come from the `buildPackages`.

Building the actual package then will end up just calling the `${buildPackages.x-Setup}/bin/Setup` from `x`.

**Comment by angerman** [comment]
I think a workable approach would be to give the `haskell-modules/generic-builder.nix` a mode. Say we have two modes: Setup, Package. By default the mode is `Package`, but to run the `Setup` we depend on the expression with mode set to `Setup`. I'll try to experiment with this.

**Comment by Ericson2314** [comment]
Yes!!! This is much better than the duplication I suggested to you as a stop gap. It also moves us closer to derivation-per-component, which we really ought to do.

**Comment by angerman** [comment]
I'm going to close this. I don't have time to fix this, and my focus is on https://github.com/input-output-hk/haskell.nix these days.
