### ISSUE TITLE
Bump flow 0.66.0->0.68.0

### ISSUE THREAD

**Issue by frontsideair** [NixOS/nixpkgs#37729]
## Issue description

It's more of a feature request than a bug. I've bumped flow in the past a few times, I haven't been able to do it this time. It's like a rabbit hole, `lwt_ppx` is required but it's not in `nixpkgs` and it doesn't have a separate tarball either so I couldn't initialize it. And I don't even know what it does and why it was split.

**Comment by vbgl** [comment]
Adding `lwt_ppx` to nixpkgs is no big deal. Let’s first merge #37850 which might interfere.

**Comment by frontsideair** [comment]
Good work! My first reaction was also upgrading `lwt` but I tried too hard to keep the existing structure. I agree with waiting until merge.

**Comment by vbgl** [comment]
@frontsideair: Please give a look at #37936.
