### ISSUE TITLE
nixpkgs.tomahawk.x86_64-linux broken with qtkeychain 0.8.0

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#37746]
## Issue description

The update to qtkeychain appears to have broken tomahawk. Here is the log:

https://hydra.nixos.org/build/71884942

Tomahawk probably needs this commit applied as a patch:

https://github.com/tomahawk-player/tomahawk/commit/00f602e10203b76fc28b4615868c567e6bd4ced4

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/72082
