### ISSUE TITLE
systemd 238 breaks my mouse

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#37744]
## Issue description

With systemd 238 installed, X no longer recognises my mouse. (A Mad Catz MMO 7.)

I've verified this through bisection; the offending commit is `2d2ab94cd2c74fe4d06391cb1ebd165439ee3d6d`

### Steps to reproduce

Check out the aforementioned commit. Build your system from it. You may need to enable gdm/gnome, and you may need this exact model of mouse.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.03.git.bccde8c4287 (Impala)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/etc/nix-system-pkgs`

**Comment by Baughn** [comment]
Here's the upstream bug: https://github.com/systemd/systemd/issues/8460

**Comment by vcunat** [comment]
Eww, so we just apply https://github.com/systemd/systemd/pull/8493 ?  /cc @fpletz.

**Comment by Baughn** [comment]
@vcunat I can confirm both that the patch restores basic mouse function, and that it makes some of my buttons stop working.

**Comment by abbradar** [comment]
I guess let's wait for what upstream has to say first -- if they won't respond quickly we'll have to merge at least an incomplete fix.

**Comment by Baughn** [comment]
I think we should merge the incomplete fix right away. This doesn't seem to be a regression -- I have so many buttons, I never noticed that some weren't working, as I only used them on Windows.

Meanwhile any other M.M.O. 7 users are currently out of luck.

**Comment by vcunat** [comment]
I believe we have all upstream fixes on master (and 18.03 was downgraded to systemd-237).  The details seem better discussed upstream.
