### ISSUE TITLE
dhall-nix install error: missing dependencies

### ISSUE THREAD

**Issue by sib-null** [NixOS/nixpkgs#37753]
## Issue description

When installing `dhall-nix`, a Haskell dependency, `hnix`, errors out with the following:
```
Configuring hnix-0.4.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:948:20 in Cabal-2.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:470:12 in Cabal-2.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:570:20 in Cabal-2.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:174:19 in Cabal-2.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:119:27 in Cabal-2.0.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
deriving-compat ==0.3.*
builder for ‘/nix/store/kk4518j7db7vrdg17h3idwr07lmr8clh-hnix-0.4.0.drv’ failed with exit code 1
```

### Steps to reproduce

1. `nix-env -i dhall-nix`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7, NixOS, 18.03pre130558.7270f2139ae (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.09pre133621.56fb68dcef4"`
 - channels(bill): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by brendanhay** [comment]
Similar issue installing `stack2nix` with identical system specs as above. Minimal reproduction via:

```
nix-env -iA nixos.haskellPackages.hnix
```

Using the `nixos-unstable` channel:

```
nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```

**Comment by mpickering** [comment]
Fixed here https://github.com/peti/nixpkgs/pull/88

**Comment by mpickering** [comment]
Merged now. This can be closed.

**Comment by mpickering** [comment]
Probably unstable isn't updated yet to include the change.

**Comment by sib-null** [comment]
Unstable channel is finally updated, 21 days after the fix is merged.  Unfortunately, the package still doesn't build due to dhall itself:
``
Setup: Encountered missing dependencies:
dhall ==1.12.*
``
