### ISSUE TITLE
haskell.packages.ghc841.either doesn't build

### ISSUE THREAD

**Issue by chisui** [NixOS/nixpkgs#37773]
## Issue description

`haskell.packages.ghc841.either` doesn't build.

This seems to be caused by changes introduced by PR [#36727](https://github.com/NixOS/nixpkgs/pull/36727)

### Steps to reproduce

Calling `nix-shell -p haskell.packages.ghc841.either` results in 

    error: attribute 'either_5' missing, at /nix/store/26pqxpg5hg7z2b3rwaxsakslbnwdmags-nixos-18.09pre133621.56fb68dcef4/nixos/pkgs/development/haskell-modules/configuration-ghc-8.4.x.nix:72:12
    (use '--show-trace' to show detailed location information)

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09pre133621.56fb68dcef4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(chisui): `""`
 - channels(root): `"nixos-18.09pre133621.56fb68dcef4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by chisui** [comment]
@deepfire, @peti do you know whats going on here?

**Comment by chisui** [comment]
@peti wouldn't reverting the change make it use version 4.5 again? The point of the PR was to bump the version of `either` to 5.

**Comment by peti** [comment]
Our default version of `either` is at version 5 now. This is why the override stopped working.
