### ISSUE TITLE
Building Nix from scratch with release-17.09 fails

### ISSUE THREAD

**Issue by ashgillman** [NixOS/nixpkgs#37828]
## Issue description
Building from scratch due to different Nix store directory

    builder for '/data/gil2a4/nix/store/5srarxzg2x68zw9jrbiqdrimj7z29gc8-perl-DBD-SQLite-1.54.drv' failed with exit code 2

Works fine once applying the newer fix here:
https://github.com/NixOS/nixpkgs/commit/d3f76d7747b990b252353c7a97905a26322aae9b#diff-bbdf323d5ff237ed00170e400a4420a0

I believe this commit should be rebased into release-17.09, thoughts?

### Steps to reproduce

    NIX_REMOTE=local NIX_CONF_DIR=$NIXROOT/etc/nix NIX_LOG_DIR=$NIXROOT/nix/var/log/nix NIX_STORE=$NIXROOT/nix/store NIX_STATE_DIR=$NIXROOT/nix/var nix-build -E 'with import "/home/gil2a4/dev/NixOS@github.com/nixpkgs" {}; nix.override { storeDir = "'$NIXROOT'/nix/store"; stateDir = "'$NIXROOT'/nix/var"; confDir = "'$NIXROOT'/etc"; }'

Where `NIXROOT` is not `/nix`

Tried with Nix 1.16 and 2.0

**Comment by matthewbauer** [comment]
Applied. Thanks!
