### ISSUE TITLE
liblapackWithAtlas test failing

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#37868]
## Issue description

Commit 4c28d80be (updating atlas from 3.10.2 to 3.10.3) broke the liblapack build. See the hydra log [here](https://nix-cache.s3.amazonaws.com/log/pw9qkv099wynrzczkx8f9hl23psczlh0-liblapack-3.4.1.drv).

The default nixpkgs liblapack is currently at version 3.4.1, although 3.5.0 is also packaged. The newest upstream release is 3.8.0. Probably updating to 3.8.0 would fix the problem, but since there's probably a reason 3.4.1 was kept around I thought I'd ask here instead of updating it myself.

There is no maintainer listed, but @peti used to be listed as maintainer and @adnelson as well as @7c6f434c touched it a couple of times too.

### Steps to reproduce

Build `liblapack` (or equivalently `liblapackWithAtlas`) on current master.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by 7c6f434c** [comment]
Not sure if the reason to keep older LAPACK is not yet obsolete, though (not sure — in either direction).

**Comment by pbogdan** [comment]
Merely passing by and noting that atlas upgrade was reverted in staging in 5ce31aa6b78 (for unrelated reasons).

**Comment by timokau** [comment]
Atlas was updated again in #39795, this is happening again. I created #40041 with the update.
