### ISSUE TITLE
No documentation for `placeholder` requiring nix v2

### ISSUE THREAD

**Issue by edanaher** [NixOS/nixpkgs#37875]
## Issue description

As noted other places, (#37863, #37693, #37779), nix v2 is now required.  However, how this was done is *not acceptable*.  I run nix-channel --update, and then can't install a package because of this.  I go "whoa, nixpkgs is broken, how did that make it through hydra?" and come here to see how many bugs have been filed about this.  Then I find that it's *by design*, and I now have to find one of the workarounds to upgrade nix when nix is broken. 

At the very least, there should be, as I vaguely recall in previous forced upgrades, a message explaining the situation and, ideally providing a workaround.  Users shouldn't have to come to github to find this out.

### Steps to reproduce

Use nix.  Upgrade.  Get frustrated.  File angry ticket.

Or, more precisely

```
edanaher@doyha:~$ nix-env --version
nix-env (Nix) 1.11.15
[ nix-channel --update as root in another shell ]
edanaher@doyha:~$ nix-env -i openvpn
error: undefined variable ‘placeholder’ at /nix/store/j8iww6hd3vdidmdf12bby6r84xfzqyxd-nixos-18.09pre133621.56fb68dcef4/nixos/pkgs/tools/misc/colord/default.nix:32:48
edanaher@doyha:~$ nix-env -i nix
error: undefined variable ‘placeholder’ at /nix/store/j8iww6hd3vdidmdf12bby6r84xfzqyxd-nixos-18.09pre133621.56fb68dcef4/nixos/pkgs/tools/misc/colord/default.nix:32:48
```

_editted to add line showing the upgrading nix also doesn't work_

**Comment by edanaher** [comment]
For the record, this worked on one of my machines:

```
$ nix-channel --rollback
$ nix-env -i nix
```

Another one hasn't been updated in too long, so even nix-unstable is an old 1.12pre that doesn't have  placeholder.  For that machine, I went into my nixpkgs checkout and checked out revision `cc4677c36ee` (from my other machine, since it should have decent hydra caches) and used that to bootstrap a useful nix.

That was a fun 20 minutes that I shouldn't have had to spend.

**Comment by matthewbauer** [comment]
I guess this is the reason we call it unstable😄. Hopefully the 17.09 channel still works.

It looks like @jtojnar has a PR to revert this which will hopefully be merged soon. In the meantime I suggest switching to the nixos-17.09 (or nixpkgs-17.09-darwin on macOS).

**Comment by matthewbauer** [comment]
Updating nixpkgs-unstable should fix this.

**Comment by edanaher** [comment]
Thanks!  Frustrated as I was, I understand that these things happen.  I trust that when the nix 2 upgrade is intentionally forced, it will be handled a bit more cleanly.

(Incidentally, would it be a good idea to have hydra build at least core packages using the previous version of nix as well as the newest, to automatically catch  these kinds of situations?)
