### ISSUE TITLE
webkitgtk-2.20: build broken on hydra

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#37878]
https://hydra.nixos.org/build/71902079/nixlog/1

**Comment by jtojnar** [comment]
It is succeeding for me most of the time, hydra also managed to build it in the past.

**Comment by matthewbauer** [comment]
Maybe try setting ```enableParallelBuilding = false;``` ? Not sure if it will help but it has helped with some derivations in the past.

**Comment by jtojnar** [comment]
@hedning managed to reproduce it even with parallel building disabled: https://github.com/NixOS/nixpkgs/pull/36893#issuecomment-373922664

**Comment by pbogdan** [comment]
Interestingly _lowering_ parallelism is what seems to trigger the issue for me. If I build with all cores (8) it seems to get past that part of the build all the time, I'm yet to see it succeed when building with a single core.

**Comment by hedning** [comment]
Can confirm that low parallelism is the problem. `nix build -f . webkitgtk --option cores 4` is building successfully, which is the first time it has worked for me.

> I'm yet to see it succeed when building with a single core.

That's consistent with what I've seen, not having it build successfully a single time (and it has always only used a single core).

**Comment by aristidb** [comment]
I also got the issue when doing a nixos-rebuild on my 2-core laptop, but it succeeded on the same laptop when using nix-build, which means that all cores are available for just webkitgtk.

This is the error message I got:

```

builder for '/nix/store/5a00rqavnjk83naq1h6mgmbdgc1v1f0r-webkitgtk-2.20.0.drv' failed with exit code 1; last 10 log lines:
                   from ../Source/JavaScriptCore/heap/Heap.h:33,
                   from ../Source/JavaScriptCore/heap/DeferGC.h:29,
                   from ../Source/JavaScriptCore/runtime/ConcurrentJSLock.h:28,
                   from ../Source/JavaScriptCore/bytecode/ArrayProfile.h:28,
                   from ../Source/JavaScriptCore/llint/LLIntOffsetsExtractor.cpp:28:
  ../Source/JavaScriptCore/API/JSHeapFinalizerPrivate.h:29:41: fatal error: JavaScriptCore/JSContextRef.h: No such file or directory
   #include <JavaScriptCore/JSContextRef.h>
                                           ^
  compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by hedning** [comment]
Would it make sense to add the stopgap fix suggested in https://bugs.webkit.org/show_bug.cgi?id=183788#c4? So something like this:
```diff
diff --git a/pkgs/development/libraries/webkitgtk/2.20.nix b/pkgs/development/libraries/webkitgtk/2.20.nix
index 8b44f11ee93..81e9b9855da 100644
--- a/pkgs/development/libraries/webkitgtk/2.20.nix
+++ b/pkgs/development/libraries/webkitgtk/2.20.nix
@@ -60,6 +60,12 @@ stdenv.mkDerivation rec {
   "-DENABLE_GTKDOC=OFF"
   ];
 
+  postConfigure = ''
+    # A stopgap for a non-deterministic build failure when using only one core
+    # Upstream bug: https://bugs.webkit.org/show_bug.cgi?id=183788#c4
+    # ninja JavaScriptCoreForwardingHeaders WTFForwardingHeaders
+  '';
+
   NIX_CFLAGS_COMPILE = optionalString stdenv.isDarwin " -lintl";

**Comment by LinuxCao** [comment]
Open the Source/JavaScriptCore/CMakeLists.txt file
Add the following in line 258:
add_dependencies(LLIntOffsetsExtractor JavaScriptCoreForwardingHeaders)

**Comment by jtojnar** [comment]
This will be no longer necesary with https://github.com/NixOS/nixpkgs/pull/45950
