### ISSUE TITLE
[nixos] Cannot set password after turning off users.mutableUsers

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#3788]
In NixOS, i have set `users.mutableUsers` to `false`, rebuilt the system, and on the next reboot i could only log in as **root** with empty password.  I tried to run `passwd`, but received the error message:

> passwd: cannot run `/nix/var/nix/profiles/default/bin/passwd': No such file or directory

**Comment by meteficha** [comment]
Why is this bug still open? (I'm new to Nix and browsing what needs to be done for the next stable.)

**Comment by edolstra** [comment]
Yeah, closing. It's not really clear what the actual issue is.
