### ISSUE TITLE
Firefox configuration problem

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#37898]
## Issue description
I can't turn off toolkit.telemetry.enabled in about:config.
[Relevant reddit post](https://www.reddit.com/r/firefox/comments/7a7dai/toolkittelemetryenabled/).
[Another relevant post](http://forums.mozillazine.org/viewtopic.php?f=23&t=3036082)
Apparently it's a build flag.

### Steps to reproduce
Install firefox, attempt to not have Mozilla up in your business.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.09pre133621.56fb68dcef4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by symphorien** [comment]
According to : https://medium.com/georg-fritzsche/data-preference-changes-in-firefox-58-2d5df9c428b5

> toolkit.telemetry.enabled: This preference is now locked to reflect prerelease or release builds (true and false respectively). 

If I run `nix run -f channel:nixos-18.03 firefox -c firefox` this preference is locked to true so this suggests that nixpkgs builds firefox as a prerelease version instead of a release version.

**Comment by 7c6f434c** [comment]
I wonder what happens if revert to non-official branding…

**Comment by 7c6f434c** [comment]
I think that this is because we do not set update channel, so it stays as default which is even nightlier than nightly for Telemetry needs. I am currently trying to perform a version bump to `59.0.2` and set `MOZ_UPDATE_CHANNEL=nixpkgs` to see if telemetry will panic and switch off (which would be the desired outcome…)

**Comment by xaverdh** [comment]
https://github.com/mozilla/policy-templates#disabletelemetry can do this perhaps?

**Comment by FliegendeWurst** [comment]
`toolkit.telemetry.enabled` is locked to false by now.
