### ISSUE TITLE
Unable to build OVA image; failed attempt to change modification time.

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#37923]
## Issue description

When trying to build an OVA image on `nixos-17.09`, the procedure seems to fail, when certain packages are in the closure. The error is repeatable on my system and issues the following error:

```

copying closure closure to /tmp/nix-build-nixos-ova-17.09.git.d16ffa1-x86_64-linux.drv-0/root...
...
warning: the group 'root' specified in 'build-users-group' does not exist
error: changing modification time of '/nix/store/cp3cxn5rgk56l9wi21d2byd3s9jpidna-python3.6-msgpack-python-0.4.7/lib/python3.6/site-packages/msgpack/__pycache__': Operation not permitted
builder for ‘/nix/store/dn82qprrhvxgad5z12jlfgyn4hw3d9vq-nixos-ova-17.09.git.d16ffa1-x86_64-linux.drv’ failed with exit code 1
error: build of ‘/nix/store/dn82qprrhvxgad5z12jlfgyn4hw3d9vq-nixos-ova-17.09.git.d16ffa1-x86_64-linux.drv’ failed

```

This might be related to #28768, but I understand the issue not enough to provide a fix.

### Steps to reproduce

Copy the following code to `reproduce-ova-fail.nix`:

```nix
{ nixpkgs ? <nixpkgs> }:

let
  pkgs = import nixpkgs {};

  imageModule = {
    imports = [ "${nixpkgs}/nixos/modules/virtualisation/virtualbox-image.nix" ];
    virtualbox.baseImageSize = 30 * 1024;
    environment.systemPackages = with pkgs;[
      python36Packages.msgpack
    ];
  };

in
{
  virtualbox-image = ((import "${nixpkgs}/nixos/lib/eval-config.nix" {
    system = "x86_64-linux";
    modules = [
      imageModule
    ];
  }).config.system.build.virtualBoxOVA);
}
```

Then build it with

```bash
nix-build reproduce-ova-fail.nix -I nixpkgs=/path/to/nixpkgs/on/nixos-17.09
```

This should result in the error message showed above.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.git.8b54eb7 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/home/justin/nixpkgs`

**Comment by erictapen** [comment]
What I should have mentioned: Not having `python36Packages.msgpack` in the closure leads to a successfull build.

**Comment by ocharles** [comment]
I am also seeing this, though not using `msgpack`. I do have something in `environment.systemPackages` though, so I wonder if that's part of the problem.

**Comment by erictapen** [comment]
I can't reproduce the issue anymore on `nixos-18.09` as well as on `nixos-unstable`.
