### ISSUE TITLE
Add tooltips with keyboard shortcuts to manual navigation buttons

### ISSUE THREAD

**Issue by thatdocslady** [NixOS/nixpkgs#3797]
@edolstra - please add tooltips/hovertext to the manual navigation buttons:

Previous (<browser modifier keys>+P)
Next (<browser modifier keys>+N)
Up (<browser modifier keys>+U)

The <browser modifier keys> element should be replaced by the actual combination as determined by the browser type and version.

**Comment by Profpatsch** [comment]
We don’t have any paging on the manuals, so I think this can be closed. cc @jagajaga

**Comment by grahamc** [comment]
Closing, ping if this should be reopened. Thanks, @Profpatsch.
