### ISSUE TITLE
gsmartcontrol and ario collide

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#37981]
## Issue description

I have `gsmartcontrol` installed

```
$ which gsmartcontrol
/home/m/.nix-profile/bin/gsmartcontrol
```

and wanted to install `ario`: 

```
$ nix-env -iA nixos.ario
installing 'ario-1.5.1'
building '/nix/store/rp77jbk9b8r597477gl6wdn0fcxy82k1-user-environment.drv'...
error: Packages '/nix/store/w1ns1nmfnydymswfqznqkckhgla4hfq0-gsmartcontrol-0.8.7/share/icons/hicolor/icon-theme.cache' and '/nix/store/ia576bhbypi1vhjgikyxyqx0g0vqy8d8-ario-1.5.1/share/icons/hicolor/icon-theme.cache' have the same priority '5'use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages ('0' being the highest priority)
builder for '/nix/store/rp77jbk9b8r597477gl6wdn0fcxy82k1-user-environment.drv' failed with exit code 1
error: build of '/nix/store/rp77jbk9b8r597477gl6wdn0fcxy82k1-user-environment.drv' failed
```

### Steps to reproduce

```
nix-env -iA nixos.gsmartcontrol
nix-env -iA nixos.ario
```

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.09pre133621.56fb68dcef4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.09pre133621.56fb68dcef4"`
 - channels(m): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
This happens when build scripts run ```gtk-update-icon-cache``` automatically. We never want this to happen in Nixpkgs because the cache will break immutability. Probably need a setup-hook to remove this automatically (it should be run automatically by ```system-path.nix``` for you).

**Comment by jtojnar** [comment]
`hicolor-icon-theme` does this.

**Comment by jtojnar** [comment]
I fixed this for gsmartcontrol in https://github.com/NixOS/nixpkgs/commit/9acdfbfd7280f7ae45411e2f3c005269dc053e78 but there are many packages that still contain the file.
