### ISSUE TITLE
Add systemd tgtd service

### ISSUE THREAD

**Issue by nyanloutre** [NixOS/nixpkgs#38012]
By looking at the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tgt) there is a service file that can be embedded with the package .

It would be nice to port that to the tgt nixpkg

I might do it myself if I find the time to learn the build system properly

**Comment by Mic92** [comment]
If the service is installed into `$out/etc/systemd/system`, it can be added in a nixos module like that: 
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/plymouth.nix#L86
