### ISSUE TITLE
gcc-unwrapped is wrapped?

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#38027]
## Issue description
nix-shell -p gcc-unwrapped gives me a shell with PATH:
```
/nix/store/y5rlyv6nz8134s687d95ysc2gakwx7am-patchelf-0.9/bin
/nix/store/rf7pnq8qk9bkjpl4s2pm5dm2pk4yqhrc-paxctl-0.9/bin
/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/bin
/nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/bin
/nix/store/6ca5dl2wy0nh37li1n4b152fcazsp3f6-glibc-2.26-131-bin/bin
/nix/store/cb3slv3szhp46xkrczqw7mscy5mnk64l-coreutils-8.29/bin
/nix/store/cmxaqb5cbzy4jk26na842n6hy1s4yn19-binutils-wrapper-2.28.1/bin
/nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin
/nix/store/6ca5dl2wy0nh37li1n4b152fcazsp3f6-glibc-2.26-131-bin/bin
/nix/store/cb3slv3szhp46xkrczqw7mscy5mnk64l-coreutils-8.29/bin
/nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/bin
/nix/store/cb3slv3szhp46xkrczqw7mscy5mnk64l-coreutils-8.29/bin
/nix/store/364b5gkvgrm87bh1scxm5h8shp975n0r-findutils-4.6.0/bin
/nix/store/cg3yhpr5hfr00y0aah23pgxiijpzl6nz-diffutils-3.6/bin
/nix/store/navldm477k3ar6cy0zlw9rk43i459g69-gnused-4.4/bin
/nix/store/s63b2myh6rxfl4aqwi9yxd6rq66djk33-gnugrep-3.1/bin
/nix/store/j79xs2j519bmvq0gihz8ff4nw5aj3vlh-gawk-4.2.0/bin
/nix/store/2p00w952ljb1172nsf3jm7nsjgsw5qpw-gnutar-1.30/bin
/nix/store/d7895h1an2pgcd6a3vx3yb5fbg786lci-gzip-1.9/bin
/nix/store/qqv6r9vkpb44rw5d8wyfpx64rgqzlvdm-bzip2-1.0.6.0.1-bin/bin
/nix/store/lhp5rw0dagi5mgqwr9i3x41240ba4ypz-gnumake-4.2.1/bin
/nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin
/nix/store/gd1mp76qr4zpbw3lccivhvi30b025x51-patch-2.7.6/bin
/nix/store/aakgkcvw6j54zg38zrn1w00sgxx0zj8b-xz-5.2.3-bin/bin
/home/mcd/bin
/run/wrappers/bin
/etc/profiles/per-user/mcd/bin
/home/mcd/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/run/current-system/sw/bin
```
notice the gcc-wrapper.
is this wanted behaviour?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.03pre131587.b6ddb9913f2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(mcd): `""`
 - channels(root): `"nixos-18.03pre131587.b6ddb9913f2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by 7c6f434c** [comment]
`nix-shell` gave you `stdenv` in addition to what you requested.

**Comment by castilma** [comment]
well, I requested gcc-unwrapped. But it also added gcc-wrapper. Does that come from the stdenv? I didn't expect gcc wrapper to be in there.

**Comment by castilma** [comment]
okay, so using nix-shell -p pkg with pkg in stdenv, you might get unexpected results. should nix see that and tell you, that you won't exactly get what you requested, or allow pkg to override the stdenv stuff(i.e. putting pkgs PATHs in front of stdenvs)?

**Comment by 7c6f434c** [comment]
nix-shell does what stdenv does. I guess you could use -I to use an expression that imports nixpkgs and replaces stdenv with stdenvNoCC post-factum.

**Comment by castilma** [comment]
my issue is, that this is unexpected behaviour. people are already talking about this in #18995. Therefore I close this issue.

**Comment by cstrahan** [comment]
@castilma That's a different issue - once that is resolved, there will _still_ be the wrapper, but it wont apply undesirable flags _outside_ of `nix-build`/`nix-shell`.

You could put something like this in a `shell.nix`:

```nix
let pkgs = import <nixpkgs> {};
in pkgs.stdenv.override {
  cc = gcc-unwrapped;
}
```

That will get you a completely unwrapped `gcc`. If you just want to disable the hardenings, something like this would do:

```
let
  pkgs = import <nixpkgs> {};
in pkgs.stdenv.mkDerivation {
  name = "shell-env";
}
```

> my issue is, that this is unexpected behaviour.

Not entirely, though I can see why it would be confusing (and there could probably be an improvement here): `nix-shell` is primarily concerned with dropping you into a shell capable of building a given package, precisely as `nix-build` would build it. For example, if I do `$ nix-shell -E '(import <nixpkgs> {}).hello'` that would give me a shell with all of the build dependencies on `$PATH` and such, just as they would be when building the `hello` package via `nix-build`. When you use `nix-shell`'s `-p` option, the packages you list are treated as build inputs to a dummy derivation, which in turn uses the default `stdenv` (which itself makes use of the wrapped `gcc`). When you specify `-p gcc-unwrapped`, you'll have both `gcc` (wrapped) and `gcc-unwrapped` on your `$PATH`.

We could consider adding another flag to specify which stdenv to use, so something along the lines of `$ nix-shell --stdenv 'stdenv.override { cc = gcc-unwrapped; /* or whatever */ }' -p gcc` could work, but that would be a separate issue.
