### ISSUE TITLE
After upgrading to (preview) NixOS 18.03, nix-repl fails

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#38137]
## Issue description

I upgrade to the current preview version of NixOS 18.03 and  `nix-repl` stopped working with the error:
> error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied

I've found a related issue #5713 about Zsh, so i tried:
```
export NIX_REMOTE=daemon
```
and indeed this fixed `nix-repl`.

I verified that the variable `NIX_REMOTE` is not defined in my user environment if i boot into `18.03pre`, but it is defined if i boot into `17.09`. (Currently i know nothing about what it does and how.)

I am using Bash.

### Steps to reproduce

In Bash:
```bash
nix-repl
echo $NIX_REMOTE
export NIX_REMOTE=daemon
nix-repl
```

## Technical details

```
§ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.03pre131587.b6ddb9913f2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3205.12512f25e9e"`
 - channels(root): `"nixos-18.03pre131587.b6ddb9913f2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by dtzWill** [comment]
This is expected and is due to upgrading Nix to 2.0 -- the NIX_REMOTE variable is no longer needed.

Nix also now has a repl builtin-- you can access it with `nix repl`.

Since `nix-repl` was merged into Nix proper, I'm not sure there's reason to worry about the old `nix-repl`?

**Comment by alexeymuranov** [comment]
Thanks for the explanation.  Indeed, `nix repl` works for me.  So, are you saying that `nix-repl` is not expected to work anymore?  If so, this can be closed.

**Comment by xeji** [comment]
This confused me too. Currently `nix-repl` has an explicit dependency on Nix 1:
` nix-repl = callPackage ../tools/package-management/nix-repl { nix = nix1; };`
 so it is unlikely to work after upgrading to Nix 2. 
We should consider dropping the `nix-repl` package altogether.

**Comment by masaeedu** [comment]
@dtzWill Is the documentation out of date here? It still says [here](https://nixos.org/nix/manual/#idm140737322481744) that in a multi-user install we're supposed to set that variable.

**Comment by Mic92** [comment]
nix pills no longer include `nix-repl` examples afaik.
