### ISSUE TITLE
acme: When enabling multiple new acme-using sites, `Failed to start Renew ACME Certificate` from account creation rate-limiting

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#38144]
> *This is both documenting the current issue and leaving a note for future implementation*

## Issue description

Using NixOS 17.09, the behaviour *should* be the same using 18.03 if doing nothing different, enabling multiple new acme-using sites or domains will result in, possibly, multiple failures:

```
Mar 30 14:07:38 HOSTNAME systemd[1]: Failed to start Renew ACME Certificate for example.com.
```

Those failures, as seen using `journalctl --unit acme-example.com.service`, stem from new registrations for new accounts:

```
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: 2018-03-30 18:08:10,566:DEBUG:acme.client:540: JWS payload:
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: {
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]:   "resource": "new-reg"
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: }
...
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: Connection: close
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: {
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]:   "type": "urn:acme:error:rateLimited",
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]:   "detail": "Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/",
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]:   "status": 429
Mar 30 14:08:10 HOSTNAME acme-example.com-start[25915]: }
```

Registrations, as [documented in the rate limits article](https://letsencrypt.org/docs/rate-limits/) are limited at a *maximum of 10 Accounts per IP Address per 3 hours*.

### Steps to reproduce

Enable ACME on multiple different domains, more than 10 should do the trick.

* * *

### Existing solutions

Starting with 18.03, it is possible to reduce the risks of hitting this limit using [useACMEHost](https://github.com/NixOS/nixpkgs/commit/41d252d7a4be12db7cec5a47468cee1024525eca). This setting allows re-using an existing ACME certificate, allowing one configured to handle multiple hosts to be used.

### Needed solution

[The integration guide for Let's Encrypt](https://letsencrypt.org/docs/integration-guide/#one-account-or-many) recommends using a single account.

> However, for most larger hosting providers we recommend using a single account and guarding the corresponding account key well. 

Adding *an option* to use one global account, and another option per-cert to specify accounts is probably the right solution. The default of those options *isn't decided yet*, and it's not my call anyway.

**Comment by NorfairKing** [comment]
+1

**Comment by NorfairKing** [comment]
still important to me

**Comment by NorfairKing** [comment]
still still important

**Comment by flosse** [comment]
> still important to me

:+1:

**Comment by m1cr0man** [comment]
This is definitely fixed in https://github.com/NixOS/nixpkgs/pull/106857 and https://github.com/NixOS/nixpkgs/pull/112145 :)
