### ISSUE TITLE
keepassx-community: Cannot mix incompatible Qt library

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#38148]
## Issue description

When starting `keepassxc` from the package `keepassx-community`, it aborts and throws an error message.

### Steps to reproduce

```
# nix-env -iA nixos.keepassx-community
# keepassxc
Cannot mix incompatible Qt library (version 0x50900) with this library (version 0x50901)
Aborted
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.1.39, NixOS, 18.03.git.ee74e26 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-18.03pre121670.4cbbecc85db"`
 - channels(turion): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by veprbl** [comment]
Perhaps this is related to #37864

**Comment by jtojnar** [comment]
Definitely the same bug. I think this might be the bug with most duplicates in the issue tracker.
