### ISSUE TITLE
nix-prefetch-git fails on /nix/var/nix/db is not writeable

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#38150]
## Issue description

milan@nixos> nix-prefetch-git https://github.com/PolicyStat/htmltreediff "fa1ca1450dc7c129f83c5ec85bfd1aa528db8b00"                                                     ~
Initialized empty Git repository in /tmp/git-checkout-tmp-xdq3newW/htmltreediff-fa1ca14/.git/
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 35 (delta 1), reused 18 (delta 1), pack-reused 0
Unpacking objects: 100% (35/35), done.
From https://github.com/PolicyStat/htmltreediff
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.8, NixOS, 18.09.git.5fabc51 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(milan): `"nixos-17.03pre96925.1c50bdd"`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`

**Comment by ck3d** [comment]
[Nix-prefetch-git](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch-scripts/default.nix#L16) (before 18.03) uses the default Nix version, which is 1.11. The module [nixos/modules/services/misc/nix-daemon.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix) removed settings for 1.11 version, because you are using the new Nix version.

Workaround:
* set environment variable NIX_REMOTE to daemon

**Comment by tex** [comment]
Thanks! Confirm that setting the variable helps. You say it is workaround. Is there something I should do to fix it properly? I'm using master head from nixpgs git repository - not using channels...

**Comment by ck3d** [comment]
Yes you are right, in your configuration, this problem should not occur. Hopefully somebody else could explain the reason.

**Comment by erikarvstedt** [comment]
Had the same error and it turned out it was caused by using the nix 1 version of `nix-prefetch-url` on a nix 2 host. Upgrading to nix 2 fixed it.
I guess this issue can be closed.

**Comment by tex** [comment]
How did you upgrade it?

**Comment by erikarvstedt** [comment]
I had a script that used `nix-prefetch-url` from an explicitly pinned down old version of nixpkgs. So I just updated the nixpkgs version in the script source.

**Comment by tex** [comment]
Thanks.
