### ISSUE TITLE
Package request: winff

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#38210]
## Issue description
Winff is a media transcoder, that supports very wide amount of formats.

https://github.com/winff  
https://www.biggmatt.com/winff/

**Comment by jtojnar** [comment]
WinFF is quite outdated (last release 2013), you may want to try [Curlew](https://github.com/chamfay/Curlew) (another ffmpeg frontend) or [Handbrake](https://handbrake.fr/) (package available).

**Comment by cx405** [comment]
@jtojnar  Thanks for the tips! Handbrake somehow manages to produce videos where SMplayer (mpv backend) fails find audio. I currently use KDEnlive in normal mode (not "recode the clip"), but its too slow for mass-recoding.

I also found Qwinff (http://qwinff.github.io/downloads.html), but its also relatively old, built against Qt4.

I noticed that there is also Arista (http://transcoder.org/) which appears to be still going.

**Comment by JohnAZoidberg** [comment]
Have you tried out the packages and came to a conclusion which one we should add?

**Comment by jtojnar** [comment]
Arista seems to be [dead](https://github.com/danielgtaylor/arista) as well so I would recommend either using the already packaged Handbrake, or packaging Curlew (though, apparently it is [licensed](https://github.com/chamfay/Curlew/issues/37) under a weird non-free license).

**Comment by JohnAZoidberg** [comment]
Yeah okay, I suggest closing this of nobody really wants another package.
The license of Curlew doesn't seem great and it hasn't been updated for a year either.

**Comment by jtojnar** [comment]
Yeah, if someone really wants some of these they can open a PR.

**Comment by cx405** [comment]
@jtojnar @JohnAZoidberg I actually want winff still, its one of the best universal transcoders. Handbrake is very different, it  has accents in quality video transcoding thus targets very few video formats. I would appreciate some universal media converter like winff.
