### ISSUE TITLE
Redshift service doesn't quite work

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#38216]
## Issue description

I can't make redshift work on NixOS. In particular, the `redshift.service` cannot be started.

### Steps to reproduce

I have the following in my `configuration.nix`:

```nix
# ...
{
  services.redshift = {
    enable = true;
    latitude = "52";
    longitude = "85";
  };
}
```

After `nixos-rebuild switch` I see no redshift effect and indeed it looks like it had trouble being loaded:

```
$ systemctl status redshift.service
* redshift.service
    Loaded: error (Reason: Invalid argument)
    Active: inactive (dead)

Mar 31 19:21:48 nixos systemd[1]: redshift.service: Service lack both ExecStart= and ExecStop= setting. Refusing.
```

## Technical details

* system: `x86_64-linux`
* host os: `Lniux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
* multi-user?: `yes`
* sandbox: `no`
* version: `nix-env (Nix) 2.0pre5889_c287d731`
* channels(mark): `"nixpkgs-18.09pre132003.13e74a838db"`
* nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mrkkrp** [comment]
Not sure if relevant, I'm trying to use it with XFCE desktop manager.

**Comment by rnhmjoj** [comment]
The situation with user services and Nix is far from polished: see this issue https://github.com/NixOS/nixpkgs/issues/17858. I haven't been following for a while so this could be outdated (but should work); in short you have to run 

```
$ systemctl --user start redshift
````
to start the service once, and if you want to enable it:

```
$ mkdir -p ~/.config/systemd/user/default.target.wants
$ touch ~/.config/systemd/user/default.target.wants/redshift.service 
```

**Comment by mrkkrp** [comment]
Yeah may that could work, but I'm trying to configure the system using only `configuration.nix`, declaratively. So I guess a proper fix is needed.

**Comment by rnhmjoj** [comment]
There is no way to do that unfortunately.

**Comment by Lassulus** [comment]
for me its working as a user service with just 
```
services.redshift = {
  enable = true;
  provider = "geoclue2";
};
```

when I check afterwards with `systemctl --user status redshift.service` I can see the service as running.
A restart of the user session might be necessary for the service to start though.

**Comment by mrkkrp** [comment]
OK, seems to work with `systemctl --user start redshift.service`. Closing.

**Comment by reinux** [comment]
I wonder why this doesn't start on its own when `enable = true` though?

**Comment by rnhmjoj** [comment]
This issue is from a long time ago when the graphical-sessions.target didn't exist (or wasn't working in NixOS, I don't remember exactly). This target is used to start services that require a running X server. You can check that redshift is now part of this target, so it will be started automatically:
```
λ systemctl --user list-dependencies graphical-session.target 
graphical-session.target
● ├─redshift.service
● └─basic.target
●   ├─paths.target
●   ├─sockets.target
●   │ ├─dbus.socket
●   │ ├─gpg-agent-ssh.socket
●   │ └─gpg-agent.socket
●   └─timers.target
```
If redshift is not starting for you, it must be another issue.

**Comment by reinux** [comment]
It did start when I explicitly made the `systemctl --user start` call, though. `enable` gives me this warning:

```
rei@udon ~/nixos (master)> systemctl --user enable redshift
Created symlink /home/rei/.config/systemd/user/redshift.service → /nix/store/vpxpr9adbrjx76zlbi1srjh5r5kzbsb9-unit-redshift.service/redshift.service.
The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
template units). This means they are not meant to be enabled or disabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/, .requires/, or .upholds/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.```
