### ISSUE TITLE
Geary 0.12.1: spell-checking language selection menu is empty

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#38256]
## Issue description

After upgrading to the pre-release version of NixOS 18.03, spell-checking in Geary started working, but the language selection menu in the composer is empty, so there is no way to change the language.

My home directory is shared between NixOS and Ubuntu, and i suppose because of the choices i made under Ubuntu, spell-checker in my Geary under NixOS currently recognizes French and Russian, but not English.

Here are the dictionaries i have manually installed:
```
§ nix-env -q "hunspell.*"
hunspell-1.6.2
hunspell-dict-en-gb-ise-wordlist-2014.11.17
hunspell-dict-en-us-wordlist-2014.11.17
hunspell-dict-fr-any-dicollecte-5.3
§ nix-env -q "aspell.*"
aspell-0.60.6.1
aspell-dict-en-2016.06.26-0
aspell-dict-fr-0.50-3
aspell-dict-ru-0.99f7-1
aspell-dict-uk-1.4.0-0
```

### Steps to reproduce

Start composing a new message and try to select or change spell-checking languages.

## Technical details

```
§ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.03pre131587.b6ddb9913f2 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(alexey): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3205.12512f25e9e"`
 - channels(root): `"nixos-18.03pre131587.b6ddb9913f2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Mic92** [comment]
Related to this: https://github.com/NixOS/nixpkgs/issues/14430

**Comment by alexeymuranov** [comment]
Could not reproduce in Geary 0.12.4 on NixOS 18.09, closing.
