### ISSUE TITLE
Cross-compiling openssl for mingw32 fails

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#38295]
## Issue description

Trying to cross-compile openssl for Win32 fails on configure. Apparently, `mingw64` exists, but `mingw32` doesn't.

    configure flags: --prefix=/nix/store/ngk18rgw21cjabs3my8in4h6jx2qkaqb-openssl-1.0.2o-i686-pc-
    mingw32 shared --libdir=lib --openssldir=etc/ssl
    Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [experimental-<cipher> ...] [-Dxxx] [-lxxx] [-
    Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] 
    [no-dso] [no-krb5] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--test-
    sanity] os/compiler[:flags]

    pick os/compiler from:
    ...

### Steps to reproduce

Issue the following

    nix-build -A openssl --arg crossSystem '(import <nixpkgs/lib>).systems.examples.mingw32'

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.12, NixOS, 18.09pre133621.56fb68dcef4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(philipp): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by pmiddend** [comment]
I can confirm that `./Configure mingw` works (so removing the `${toString cpu.bits}` part).

**Comment by Mic92** [comment]
Probably it has been only tested for 64-bit.

**Comment by matthewbauer** [comment]
Fixed in master.
