### ISSUE TITLE
Dfhack doesn't put its binaries on the `$PATH`

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixpkgs#38307]
## Issue description
The `dfhack` package contains two binaries: `dfhack` and `dfhack-run`. These are both contained in the derivation, but are not put on the `$PATH`.

### Steps to reproduce
Install `nixos.dwarf-fortress-packages.dfhack` from nixpkgs unstable. Try to run `dfhack`. Observe it can't find the executable.

List the files in the [derivation](https://gist.github.com/mkaito/8f103b13f0ce4cbf0b369327621d88c0). Observe the binaries are present at the root, instead of a `bin` folder.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09pre133621.56fb68dcef4 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(chris): `""`
 - channels(root): `"nixos-18.09pre133621.56fb68dcef4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by abbradar** [comment]
`dwarf-fortress-packages.dfhack` is not supposed to be used by a user; instead one should use flags in `dwarf-fortress` as you've done in you `hacked` derivation. For example,

```
environment.systemPackages = [ dwarf-fortress.override { enableDFHack = true; } ];
```

**Comment by mkaito** [comment]
That doesn't seem to work. It says "entry is not of type package".

**Comment by abbradar** [comment]
That's strange, it works for me:

```
> dwarf-fortress.override { enableDFHack = true; }'
/nix/store/0jpx3lm2b3bnwi1qg1mfxkp5ncwscxqk-dwarf-fortress-0.44.05
```

**Comment by mkaito** [comment]
Huh, that works for me too. I wonder why it doesn't work in `configuration.nix`.

**Comment by abbradar** [comment]
Ah, that's because of my mistake. It should be like this:

```
environment.systemPackages = [ (dwarf-fortress.override { enableDFHack = true; }) ];
```

Operation priorities!

**Comment by mkaito** [comment]
I feel like this should be better documented somewhere :stuck_out_tongue:
