### ISSUE TITLE
lxqt needs upower for support of "powerManagement.enable = true;" in configuration.nix

### ISSUE THREAD

**Issue by redfish64** [NixOS/nixpkgs#38317]
## Issue description

lxqt battery monitor doesn't work even with "powerManagement.enable = true;" enabled in the configuration

### Steps to reproduce

On a laptop with battery power, in configuration.nix, add the lines:

`services.xserver.lxqt.enable = true;powerManagement.enable = true;`

Run `nixos-rebuild switch`
 
After starting up lxqt, enable the battery watcher under main menu/Preferences/LXQt settings/Power Management

Battery watcher will complain no battery exists.

## Technical details

lxqt is unable to display battery usage without upower. Most other desktop managers tie upower to "powerManagement.enable = true;" by including the following line in their service:

  `services.upower.enable = config.powerManagement.enable;`

> $ grep services.upower.enable nixos/modules/services/x11/desktop-managers/*
> nixos/modules/services/x11/desktop-managers/enlightenment.nix:    services.upower.enable = config.powerManagement.enable;
> nixos/modules/services/x11/desktop-managers/gnome3.nix:    services.upower.enable = config.powerManagement.enable;
> nixos/modules/services/x11/desktop-managers/mate.nix:    services.upower.enable = config.powerManagement.enable;
> nixos/modules/services/x11/desktop-managers/plasma5.nix:      services.upower.enable = config.powerManagement.enable;
> nixos/modules/services/x11/desktop-managers/xfce.nix:    services.upower.enable = config.powerManagement.enable;

I think nixos/modules/services/x11/desktop-managers/lxqt.nix should have this line, too.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09.git.56fb68d (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(tim): `""`
 - channels(root): `"nixos-18.09pre133621.56fb68dcef4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment]
fixed in pull request.
