### ISSUE TITLE
K3b doesn't find libcdparanoia nor flac encoder

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#38325]
## Issue description

If Flac is installed, K3b should provide Flac encoder as an external audio encoder. See: https://forums.linuxmint.com/viewtopic.php?t=214318

`flac` is indeed a propagated build input of `k3b`:
https://github.com/NixOS/nixpkgs/blob/0fadb81af44fe7f43581a276d2ca863bdb64dd67/pkgs/applications/kde/k3b.nix#L25

So I suppose in principle it should work. However, could it be that `QStandardPaths::findExecutable( "flac" )` doesn't find the executable properly on NixOS: https://github.com/KDE/k3b/blob/0f2a154df5bd44cd7d441dfb9ad8ef3dac145582/plugins/encoder/external/k3bexternalencodercommand.cpp#L56

Any ideas how to fix?

### Steps to reproduce

- Open K3b.
- Go to Settings -> Configure K3B -> Plugins
- Find K3B External Audio Encoder and click on the Configure icon
- There should be Flac option on the list, but the list is empty.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09.git.7f291f8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2
```

**Comment by jluttine** [comment]
I copied the command from the K3b link in the original post:
```
flac -V -o %f --force-raw-format --endian=little --channels=2 --sample-rate=44100 --sign=signed --bps=16 -T ARTIST=%a -T TITLE=%t -T TRACKNUMBER=%n -T DATE=%y -T ALBUM=%m -
```

I added this as an external audio encoder. Tried to use it but the ripping stopped and showed an error immediately:
```
Could not load libcdparanoia.
```

**Comment by jluttine** [comment]
Here is a full log from the following steps:
- Launch K3b
- Choose the audio CD
- Choose start ripping
- Select Flac (that I have defined manually) as the format
- Start ripping
- Error is raised
- Close dialogs and exit K3b

[k3b.log](https://github.com/NixOS/nixpkgs/files/1867931/k3b.log)

**Comment by jluttine** [comment]
I tried adding `flac` and `cdparanoia` on the PATH by adding them on this line:
https://github.com/NixOS/nixpkgs/blob/0fadb81af44fe7f43581a276d2ca863bdb64dd67/pkgs/applications/kde/k3b.nix#L37

Still, the same error.

**Comment by jluttine** [comment]
I tried with other file formats too, I still get the same error that libcdparanoia could not be loaded.

**Comment by Mic92** [comment]
It probably uses dlopen to load `libcdparanoia`. Therefore it either needs to be added to LD_LIBRARY_PATH: https://github.com/NixOS/nixpkgs/pull/25412/files or added as required with patchelf: https://github.com/NixOS/nixpkgs/pull/37920

`propagatedBuildInputs` will not work here and is wrong.

**Comment by jluttine** [comment]
Thanks, I made a pull request. https://github.com/NixOS/nixpkgs/pull/38437
