### ISSUE TITLE
nixos-rebuild does not have documented verbosity options.

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#38355]
## Issue description

nixos-rebuild verbosity options do not match manual pages. Also no flag to be "quiet".

### Steps to reproduce

The manual pages say "-v 0 .. 5" , yet the ```nixos-rebuild --verbose 0``` itself rejects any provided number.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3205.12512f25e9e (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by nixy** [comment]
The manual page is a bit vague on this, but you don't pass the "level" of verbosity as an option. You specify -v x times, where x is the level of verbosity.

So for "talkative" (level 2), you would want to do nixos-rebuild -vv

IMO This could definitely be clearer in the documentation. Examples would help a lot here.

**Comment by andrewchambers** [comment]
Oh, in that case the documentation does not make sense:

```
0

    “Errors only”: only print messages explaining why the Nix invocation failed.
1

    “Informational”: print useful messages about what Nix is doing. This is the default.
```

If 1 is the default then it is impossible to get -v 0 ?

**Comment by andrewchambers** [comment]
closing, doesn't seem so important > /dev/null works for quietish.
