### ISSUE TITLE
systemd-boot customization for DSDT patch

### ISSUE THREAD

**Issue by joseph-long** [NixOS/nixpkgs#38352]
## Issue description

I'm setting up NixOS on a new Thinkpad X1 Yoga and trying to get all the machine-specific tweaks translated into Nix-ese. One particularly gnarly hack required is the [installation of a custom DSDT table](https://delta-xi.net/#056) to enable suspend-to-RAM.

It looks like I need to add a *second* initrd line to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L32 before the kernel initrd. (See https://wiki.archlinux.org/index.php/DSDT#Using_a_CPIO_archive .) However, I don't see a hook to customize that short of submitting a patch. Patching something that low-level for myself is one thing, but inserting a hook for everyone seems beyond my abilities :)

I guess this is a feature-request for the ability to customize the config file generated when the bootloader is installed, but also more generally a support request to see if there's another way to do it.

## Technical details
 system: `"x86_64-linux"`                                                                            
 - host os: `Linux 4.9.86, NixOS, 17.09.3205.12512f25e9e (Hummingbird)`                                
 - multi-user?: `yes`                                                                                  
 - sandbox: `no`                                                                                       
 - version: `nix-env (Nix) 1.11.16`                                                                    
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by joseph-long** [comment]
Cheers, I'll try the first option you listed. As you may have seen in my other issue, GRUB2 is not working for me for some reason... https://github.com/NixOS/nixpkgs/issues/38364

**Comment by joseph-long** [comment]
Thanks @symphorien! That (`boot.initrd.prepend`) seems to work, with one minor adjustment: I had to quote the path I put in that list.

```
[jdl@mercury:~]$ dmesg | grep ACPI | grep supports
[    0.204938] ACPI: (supports S0 S3 S4 S5)
```

:tada:

**Comment by benley** [comment]
@joseph-long could you elaborate a bit on how you got this working?  I've been trying to figure it out and have gotten stuck.  So far I have:

```nix
let patched_dsdt_initrd = pkgs.makeInitrd {
  compressor = "cat";
  contents = [
    { object = ./dsdt.aml;
      symlink = "kernel/firmware/acpi/dsdt.aml";
    }
  ];
}; in

{
  boot.kernelParams = [ "mem_sleep_default=deep" ];
  boot.initrd.prepend = [ "${patched_dsdt_initrd}/initrd" ];

  boot.loader.systemd-boot.enable = true;
}
```

and that doesn't seem to do the right thing, so I'm wondering what does.

**Comment by joseph-long** [comment]
Hm, I didn't use makeInitrd. Here's the system configuration that I last had: https://gist.github.com/joseph-long/5d301c4fae488890e41f8ebb63722465#file-configuration-nix-L38 (I'm currently using Kubuntu, so consider it untested with latest NixOS.)

I think the file referenced is a cpio archive as described here: https://delta-xi.net/#056

It turns out you can also load ACPI DSDT files in GRUB (*not* as CPIO archives) by storing them in the EFI partition and adding a line to your GRUB config, so that's what I'm doing now (since patching the initrd for Kubuntu seemed brittle).
