### ISSUE TITLE
Using postgis & postgresql inside a nix-shell

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#38369]
There's `pkgs.postgis` but it's designed to be used by NixOS services. https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/postgresql.nix

Is there a way to get postgresql and postgis working within a nix-shell? I'm guessing this requires manual setup of the postgresql database files (which may involve manual installation of postgis then).

**Comment by jtojnar** [comment]
Maybe take a look at [nixos-shell](https://github.com/chrisfarms/nixos-shell)

**Comment by johnchildren** [comment]
I've had some success re-wrapping postgresql in a new build environment. You need to call `CREATE EXTENSION` etc to actually install your extensions though, so you could probably add that as a shell hook?

```nix
  mypg = let pg = postgresql; in pkgs.buildEnv {
    name = "my-postgresql";
    paths = [ pg pg.lib ] ++ [
      # your extensions here
    ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild =
        ''
          rm $out/bin
          mkdir -p $out/bin
          cp --target-directory=$out/bin ${pg}/bin/{postgres,pg_config,pg_ctl,initdb,createdb}
          wrapProgram $out/bin/postgres --set NIX_PGLIBDIR $out/lib
        '';
  };
```

**Comment by CMCDragonkai** [comment]
@johnchildren When I try something like this:

```nix
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/831ef4756e372bfff77332713ae319daa3a42742.tar.gz) {}
}:
  let pg = pkgs.postgresql;
      mypg = pkgs.buildEnv {
        name = "mypostgresql";
        paths = [ pg pg.lib (pkgs.postgis.override { postgresql = pg; }) ];
        buildInputs = [ pkgs.makeWrapper ];
        postBuild = ''
          rm $out/bin
          mkdir -p $out/bin
          cp --target-directory=$out/bin ${pg}/bin/{postgres,pg_config,pg_ctl,initdb,createdb}
          wrapProgram $out/bin/postgres --set NIX_PGLIBDIR $out/lib
        '';
      };
  in
    pkgs.stdenv.mkDerivation {
      name = "locater";
      buildInputs = [ mypg ];
    }
```

There's  an error: 

```
error: while evaluating the attribute ‘buildInputs’ of the derivation ‘locater’ at /nix/store/1sdb620smqzfsx23xrgfj33x71b05fmc-831ef4756e372bfff77332713ae319daa3a42742.tar.gz/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating the attribute ‘pkgs’ of the derivation ‘mypostgresql’ at /nix/store/1sdb620smqzfsx23xrgfj33x71b05fmc-831ef4756e372bfff77332713ae319daa3a42742.tar.gz/pkgs/stdenv/generic/make-derivation.nix:148:11:
cannot convert a function to JSON
```

The culprit is: `(pkgs.postgis.override { postgresql = pg; })`. Maybe a bug in the postgis expression?

**Comment by CMCDragonkai** [comment]
Ok upgrading to the hash: `49a0ecc49b491c1f1a6f329d3d4fc9cf559b18aa` worked.

However your `postBuild` commands failed. I just copied the `postBuild` commands from https://github.com/NixOS/nixpkgs/blob/b2f53c76f83cbe91bb9c765b7a3aaaa50336d653/nixos/modules/services/databases/postgresql.nix and it worked.

I wonder what does it mean to remove `pg_config,postgres,pg_ctl`? And then copy the `postgres,pg_config,pg_ctl` from the `${pg}`. Why those programs in particular? What about all the other `pg_*` programs? Why are they not also removed and copied?

**Comment by CMCDragonkai** [comment]
For reference here is my working expression:

```nix
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/49a0ecc49b491c1f1a6f329d3d4fc9cf559b18aa.tar.gz) {}
}:
  with pkgs;
  let
    pg = (pg:
      buildEnv {
        name = "postgresql-and-plugins-${(builtins.parseDrvName pg.name).version}";
        paths = [ pg pg.lib (postgis.override { postgresql = pg; }) ];
        buildInputs = [ makeWrapper ];
        postBuild = ''
          mkdir -p $out/bin
          rm $out/bin/{pg_config,postgres,pg_ctl}
          cp --target-directory=$out/bin ${pg}/bin/{postgres,pg_config,pg_ctl}
          wrapProgram $out/bin/postgres --set NIX_PGLIBDIR $out/lib
        '';
      }
    );
  in
    stdenv.mkDerivation {
      name = "locater";
      buildInputs = [ (pg postgresql) ];
    }
```

**Comment by johnchildren** [comment]
Hmm, weird, well you shouldn't need all of those utilities at least, I just exposed them because I was using them to create databases in my shell. I had been using this with other extensions than postgis so there might have been a mismatch there? But it had seemed to work before with it available.

**Comment by CMCDragonkai** [comment]
That's just a straight copy from the nixos module for postgresql + postgis.

However I found that this morning things have stopped working.

```
postgres=# CREATE EXTENSION postgis;
ERROR:  could not open extension control file "/nix/store/2bx59fxqmygincx79k3kk2bxc0ngc0zp-postgresql-9.6.6/share/extension/postgis.control": No such file or directory
STATEMENT:  CREATE EXTENSION postgis;
ERROR:  could not open extension control file "/nix/store/2bx59fxqmygincx79k3kk2bxc0ngc0zp-postgresql-9.6.6/share/extension/postgis.control": No such file or directory
```

The control files are missing. Even after garbage collecting and rebuilding. PostGIS no longer works.

**Comment by CMCDragonkai** [comment]
Ok so I found out the problem. Within the nix shell. Postgresql 9.6.6 is being accessed for some reason:

```
> which postgres
/nix/store/2bx59fxqmygincx79k3kk2bxc0ngc0zp-postgresql-9.6.6/bin/postgres
> which pg_receivewal
/nix/store/68zmm91j2sa7pvnmjpjj6x0pk9pwsfdj-postgresql-and-plugins-10.1/bin/pg_receivewal
```

I'm using `postgresql100` now. And all those commands should not be pointing at postgresql 9.6.6. It should be pointing at the custom build environment `postgresql-and-plugins-10.1`.

But I noticed only some commands such as `pg_receivewal` are being symlinked to the current build environment. Doing tab on `pg_` shows most commands as not symlinks (suffixed with `@`).

This is quite confusing. Why are some commands still pointing to 9.6.6 and other commands are pointing to the custom buildenv? I don't even have postgresql installed outside of the nix-shell. What is brining in the 9.6.6 postgresql?

Also I checked that the custom buildenv does in fact have the extension control file.

**Comment by CMCDragonkai** [comment]
I just found the problem.

In my `shell.nix` I'm also bringing in `psycopg2` which propagates the `postgresql-9.6.6` dependency. Because for some reason `psycopg2` was ahead of my custom package environment, then `postgresql-9.6.6` binaries was placed ahead of it.

By removing `psycopg2`, it ended up working.

I found another issue discussing this problem of collisions between `psycopg2` and postgresql. https://github.com/NixOS/nixpkgs/issues/22311

I think 2 things should happen. `psycopg2` shouldn't need the binaries, only the libraries that it binds to. (It currently propagates the entire thing).

Secondly, is there a way to make psycopg2 to use my custom postgresql environment?

@FRidh

**Comment by CMCDragonkai** [comment]
@johnchildren I think I have an idea as to what the purpose of `cp --target-directory=$out/bin ${pg}/bin/{postgres,pg_config,pg_ctl}` is for. The custom build environment creates its own store path. It looks almost exactly the same the normal `postgresql` store path. Except that it now has its own `share/extensions` directory. That contains the postgis symlinks.

The `postBuild` command removes the symlinks to `pg_config`, `postgres`, `pg_ctl`, and instead copies the `postgres`, `pg_config`, `pg_ctl` into the custom build environment. However all the other `bin` commands that `postgresql` exports is still in the custom environment, it's just they are symlinks back to the normal `postgresql` store path.

I understand why this is needed for `postgres` since it later is applied to the `wrapProgram` command. But what is the point of removing the symlinks and copying over the commands of `pg_config` and `pg_ctl`? Wouldn't they still work as symlinks?

The only thing I can imagine is that by copying it to the custom build environment, the programs are aware of the postgis extension that is in the `share/extensions`. However I'm not sure what commands would need to be aware of the `postgis` extensions to work properly. Surely `pg_ctl` doesn't need to be aware of it.

Also the standard `postgresql` service expression also does the exact same thing, and it is meant to work across any kind of extensions, so it only copies over `postgres`, `pg_config` and `pg_ctl`, who made this choice and why?

**Comment by CMCDragonkai** [comment]
https://github.com/NixOS/nixpkgs/blob/b2f53c76f83cbe91bb9c765b7a3aaaa50336d653/nixos/modules/services/databases/postgresql.nix#L122-L136

**Comment by danbst** [comment]
It's now possible. See https://github.com/NixOS/nixpkgs/issues/65452 for an example

**Comment by danbst** [comment]
as for `psycopg2`, pg has to overriden there. Unfortunately, there isn't an easy way.
```
self: super: {
   python = super.python.override {
    self = self.python;
    packageOverrides = pself: psuper: {
      psycopg2 = psuper.psycopg2.override { postgresql = self.postgresql_11; };
    };
   };
}
```
Something like that. But I agree, `libpg` should be extracted to separate package.
