### ISSUE TITLE
home-assistant: add support for selecting the package / introduce latest variant

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#38363]
## Issue description

```home-assistant``` runs with a very aggressive release schedule - every 2 weeks which will make things "interesting" for stable.

I suggest we add a ```home-assistantLatest``` derivation that tracks the latest upstream and then makes the package configurable in the nixos module similarly to how it's done with nginx.

Cc: @dotlambda

**Comment by dotlambda** [comment]
How would `home-assistant` and `home-assistantLatest` differ on master?

Btw, I have not updated to 0.66 yet because a test is broken and I don't know why.

**Comment by peterhoeg** [comment]
> How would home-assistant and home-assistantLatest differ on master?

They would be the same.

**Comment by bjornfor** [comment]
I find the "home-assistantLatest" name confusing. I already expect "home-assistant" to be the latest, so what's that extra "*Latest" thing? If being the same on master, how do they differ on release branches?

**Comment by dotlambda** [comment]
I also do not think this is generally a good idea: Home Assistant has quite a lot of dependencies, which also would need to be kept up to date. Therefore, I suggest people who want to use the latest version can just add a channel and do:
```
unstable = import <nixos-unstable> { };
home-assistant = unstable.home-assistant;
```

**Comment by peterhoeg** [comment]
Thanks for the input guys.
