### ISSUE TITLE
gvfs build fails non-deterministcally on unstable

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#38378]
Upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=794549

Random hydra log: https://hydra.nixos.org/build/72338243/nixlog/1

We should probably switch back to autotools as suggested until it's fixed upstream? Or would turning parallel building off fix it too?

cc @jtojnar

**Comment by jtojnar** [comment]
Sounds good to me.
