### ISSUE TITLE
qbittorrent doesn't work

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#38376]
## Issue description

`qbittorrent` cannot start.

### Steps to reproduce

Install `qbittorrent` by adding it to `users.users.<name?>.packages` list, i.e. making it available only to a specific user. Do rebuild, login as that user. Start `qbittorrent`. If you are as lucky as I'm it won't start. If you start it from a terminal, you'll see the following:

```
$ qbittorrent
This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

Reinstalling the application may fix this problem.
Aborted
```

## Technical details

* system: `"x86_64-linux"`
* host os: `Linux 4.9.85, NixOS, 17.09.3129.1dcd022f01b (Hummingbird)`
* multi-user?: `yes`
* sandbox: `no`
* version: `nix-env (Nix) 2.0pre5889_c287d731`
* channels(mark): `"nixpkgs-18.09pre132003.13e74a838db"`
* nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
IIRC, this is the same issue as https://github.com/NixOS/nixpkgs/issues/37864

**Comment by Mic92** [comment]
QT libraries installed into the profile seems to diverge here.

**Comment by mrkkrp** [comment]
FTR, I updated the system and now applications like `qbittorrent` and `telegram` work. This may be closed?

**Comment by Mic92** [comment]
Yeah, this is SNAFU related how our qt plugins. I don't think there is an easy fix for that.
