### ISSUE TITLE
Need ABI for macOS

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#38402]
When using the quadruple form for Nix, how would you refer to the macOS/iOS libsystem ABI? Can't find any good reference to this but should be added for when cross-compiling actually works for macOS.

/cc @Ericson2314

**Comment by Ericson2314** [comment]
Apple doesn't do this, but instead puts trailing numbers on the ow name :/. See http://llvm.org/doxygen/Triple_8cpp_source.html

**Comment by matthewbauer** [comment]
Okay. I guess that makes sense. Does the platform parser correctly detect this?

**Comment by Ericson2314** [comment]
Not really.... It just has some ad-hoc synnonyms for macos. It could be better :).
