### ISSUE TITLE
EmojiOne color font appears black and white in IBus emoji chooser

### ISSUE THREAD

**Issue by joseph-long** [NixOS/nixpkgs#38413]
## Issue description

After enabling IBus and emojione in my NixOS config, I selected EmojiOne Color Regular as my emoji font. However in the font picker it shows up in black-and-white:

![image](https://user-images.githubusercontent.com/31168267/38281855-aa13bcbc-3761-11e8-93e3-45901180e863.png)

And when I use `Ctrl+Shift+e` to enter an emoji, the picker interface shows these emoji

![image](https://user-images.githubusercontent.com/31168267/38282022-958a1dd0-3762-11e8-8f34-2af553c6e233.png)

which appears to be a mix of emoji designs (possibly related to the [deja vu fonts](https://askubuntu.com/questions/722562/where-does-these-emojis-come-from)?)

### Steps to reproduce

In `configuration.nix` I have

```
  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "us";
    defaultLocale = "en_US.UTF-8";
    # Configure niche input methods
    inputMethod = {
      enabled = "ibus";
    };
  };
  # Fonts
  fonts.fonts = with pkgs; [
    noto-fonts-cjk
    emojione 
  ];

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "us";

  # Enable touchpad support.
  services.xserver.libinput.enable = true;

  # Enable the KDE Desktop Environment.
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3222.21693048d72 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.3222.21693048d72"`
 - channels(jdl): `"nixos-18.03-18.03pre131740.09bca91e3b5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
You might need some newer libraries https://github.com/NixOS/nixpkgs/pull/36371

**Comment by abbradar** [comment]
See also Twemoji issue: https://github.com/eosrei/twemoji-color-font/issues/29

**Comment by jtojnar** [comment]
EmojiOne font is available here: https://github.com/emojione/emojione/tree/master/extras/fonts#google-font---emojione-androidttf

I thought I had updated the nixpkgs package but cannot find the branch now.

**Comment by abbradar** [comment]
Didn't know it exists, cool! Let's keep this issue open then.

**Comment by jtojnar** [comment]
It would be nice if the ttf file used correct font name, though. See the upstream issue: https://github.com/emojione/emojione/issues/558
