### ISSUE TITLE
Programs can't resolve .local domains.

### ISSUE THREAD

**Issue by toonn** [NixOS/nixpkgs#38420]
## Issue description
Programs installed by nix can't resolve .local domains. I noticed this first with firefox but I also tested with opera (package has some permissions issues btw) and ping from inetutils. I opened a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1439780#c38) on the firefox bugtracker which has some more info on why exactly it doesn't work. Note the resolution works for anything not installed by nix.

### Steps to reproduce

1. Install a program that does DNS resolution through nix on non-nixos.
2. Try to access a .local domain on your local network.

## Technical details

`nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.7-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(toonn): `"nixpkgs-18.03pre130569.7a04c2ca296"`
 - nixpkgs: `/home/toonn/.nix-defexpr/channels/nixpkgs`
```

**Comment by Mic92** [comment]
`.local` is provided by an nss module, on nixos we use `nscd` to give all programs access to this. On Archlinux nss modules are installed into a fixed location instead, however you could enable `nscd.service` on archlinux as well.

**Comment by toonn** [comment]
Wow, that was a simple fix. Thanks : )
