### ISSUE TITLE
"Cannot compare values of different types" for environment.etc.subgid

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#3844]
Caused by #3100, specifically https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/users-groups.nix#L340. If the user has no uid, sortOn will abort. I'm not sure if a user not having a uid is valid, but I can do it easily just by declaring `users.extraUsers = { name = "znc"; }` (which I do in my nixops expression).

**Comment by joachifm** [comment]
Still a problem?

**Comment by Profpatsch** [comment]
triage: closing because no reply.
