### ISSUE TITLE
octave: abort when printing figure to pdf

### ISSUE THREAD

**Issue by tmplt** [NixOS/nixpkgs#38459]
## Issue description
When saving a plot figure to pdf in Octave, the program panics and aborts

### Steps to reproduce
```
$ octave --no-gui
octave:1> t = linspace(0,1);
octave:2> x = power(abs(t), 1/3);
octave:3> plot(t,x);
octave:4> print -dpdf output.pdf
warning: print.m: epstool binary is not available.
Some output formats are not available.
warning: called from
    __print_parse_opts__ at line 385 column 9
    print at line 315 column 8
error: gl2ps_print: support for gl2ps was unavailable or disabled when Octave was built
terminate called after throwing an instance of 'octave::execution_exception'
panic: Aborted -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
[1]    14326 abort      octave --no-gui
```
Reproducible with both `octave` and `octaveFull` from `nixos-unstable`. If the GUI is used, the program exits with signal 6.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.78, NixOS, 17.09.2873.4c3c0e824aa (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2873.4c3c0e824aa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Mic92** [comment]
Does `octaveFull` suffer from the same problem?

**Comment by Tmplt** [comment]
Yes, same problem with `octaveFull`.

**Comment by Mic92** [comment]
Requires https://www.archlinux.org/packages/extra/x86_64/gl2ps/ in `buildInputs`, which we have not packaged yet.

**Comment by S-NA** [comment]
@7c6f434c this should be reopened, octave lacks `gl2ps` in `buildInputs` so the issue still stands.
```
error: gl2ps_print: support for gl2ps was unavailable or disabled when Octave was built
error: called from
    __opengl_print__ at line 193 column 7
```
I think `gl2ps` should be included in both `octave` and `octaveFull`. Mainly so command line users can still save graphs to a file.

I can make the necessary changes eventually or if someone else wants to that would be nice.

**Comment by 7c6f434c** [comment]
Oops sorry
