### ISSUE TITLE
Missing dependencies for gramps

### ISSUE THREAD

**Issue by ivan-timokhin** [NixOS/nixpkgs#38463]
## Issue description

At launch, `gramps` complains that

```
Gdk, Gtk, Pango or PangoCairo typelib not installed.
Install Gnome Introspection, and pygobject version 3.12 or later.
Then install introspection data for Gdk, Gtk, Pango and PangoCairo

Gramps will terminate now.
```

…and terminates.

### Steps to reproduce

```
nix-shell -p gramps --run gramps
```
or
```
nix run -f channel:nixpkgs-unstable gramps -c gramps
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131792.becbe4dbe16 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131792.becbe4dbe16"`
 - channels(ivan): `"nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment]
I think `wrapGappsHook` missing for gramps.

**Comment by symphorien** [comment]
can you check if #38472 solves the issue ?
