### ISSUE TITLE
amd legacy catalyst-hd234k 

### ISSUE THREAD

**Issue by ivanbalashov239** [NixOS/nixpkgs#38460]
https://wiki.archlinux.org/index.php/Xorg#AMD
https://wiki.archlinux.org/index.php/AMD_Catalyst#Installing_the_driver

is there a way to install catalyst driver for old amd graphics?

**Comment by rnhmjoj** [comment]
Yes, there is. The driver is called "ati_unfree", so try setting:
```
services.xserver.videoDrivers = [ "ati_unfree" ];
nixpkgs.config.allowUnfree = true;
```

As you have probably noted there is no way to discover which video drivers are available, see issue https://github.com/NixOS/nixpkgs/issues/24801

**Comment by seniorivn** [comment]
@rnhmjoj
Havn't tried it yet,  but looks like it is just modern proprietary catalyst driver.  But I'm asking about legacy driver,  which requires old xorg and kernel

**Comment by rnhmjoj** [comment]
Ah, sorry. No, that variant it's not packaged os there's isn't any way. I don't know if anybody here could try to build and maintain it but it looks like it's a significant amount of work.
