### ISSUE TITLE
Bazel can't find ar

### ISSUE THREAD

**Issue by commandodev** [NixOS/nixpkgs#38471]
## Issue description

Bazel builds are failing for me with the latest version (`0.11.1`) installed from nixpkgs `HEAD`. I also had the same issue with `0.10.1`

### Steps to reproduce

```
git clone git@github.com:tweag/rules_haskell_examples.git
cd rules_haskell_examples
bazel build //vector
...
ERROR: /home/ben/dev/haskell/rules_haskell_examples/vector/BUILD:12:1: SkylarkAction vector/libHSvector-1.0.0.a failed (Exit 1)
src/main/tools/process-wrapper-legacy.cc:58: "execvp(/usr/bin/ar, ...)": No such file or directory
Target //vector:vector failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.966s, Critical Path: 9.34s
FAILED: Build did NOT complete successfully
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
⇒  nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/nhfgv0xxi9shl5lvl9jaf11vmm9zkv42-nix-info
fetching path ‘/nix/store/nhfgv0xxi9shl5lvl9jaf11vmm9zkv42-nix-info’...

*** Downloading ‘http://cache.nixos.org/nar/0m0hkzniw91kgh4vciarl0332phi8hzljw8n91548hkmghm1b305.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/nhfgv0xxi9shl5lvl9jaf11vmm9zkv42-nix-info’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1640  100  1640    0     0  11970      0 --:--:-- --:--:-- --:--:-- 11970

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3204.d16ffa15090 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.8`
 - channels(ben): `""`
 - channels(root): `"nixos-17.09.3204.d16ffa15090"`
 - nixpkgs: `/home/ben/dev/nixpkgs`
```
nixpkgs is at `9049f8a418b1d29f8066baec681684677fce28c7`

See also https://github.com/tweag/rules_haskell/issues/203

**Comment by Mic92** [comment]
This one needs a patch:

```
src/main/tools/process-wrapper-legacy.cc
```

You can replace it with `$AR` that is available in stdenv by using `substituteInPlace`:

```console
$ nix-shell -p hello --command 'echo $AR'
bash: /run/user/1000/env-vars: cannot overwrite existing file
ar
```

**Comment by Mic92** [comment]
Ok. the file does not contain this.

Maybe it is decided here somewhere:

https://github.com/bazelbuild/bazel/blob/832a0b193a9a098897781bc6298d0455b3913482/tools/cpp/unix_cc_configure.bzl#L103

**Comment by boothead** [comment]
This starts working again on a system that has have `nix-env -i binutils` run...

**Comment by Mic92** [comment]
Probably needs to be in path of bazel then.

**Comment by abbradar** [comment]
@boothead Have you tried adding it to `makeBinPath` in `installPhase`?

**Comment by boothead** [comment]
@abbradar I tried this with this commit: https://github.com/boothead/nixpkgs/commit/a791221178c0b1f7c076da234c193d2de93fda9d It doesn't seem to have made a difference.

**Comment by abbradar** [comment]
@boothead Hm, strange -- exactly this should work in principle. I'll give a better look later; not sure what happens.

**Comment by amckague** [comment]
Looks like patching scripts that generate scripts helps https://github.com/amckague/nixpkgs/commit/0326835055a5b4e2d2a1074e51e32b0d58136783#diff-4746b81564a01e241a84d455575437e7R89 I'm new to making this kind of change so any suggestions are welcome.

**Comment by amckague** [comment]
Related https://github.com/NixOS/nixpkgs/issues/24063

**Comment by timokau** [comment]
Pretty sure I found the root cause of this problem! Turns out bazel provides [default locations to standard tools](https://github.com/bazelbuild/bazel/blob/08d2c3d63770eadf54443e69f43d44c4f2551d46/tools/cpp/cc_toolchain_config.bzl#L1311) that some bazel rules use. The file I linked is actually auto-generated, which made debugging very confusing. I initially patched that file, without noticing that the build process would just override it with the old one. No idea why they check in the generated file.

Anyway, the tool location is ultimately determined by [this function](https://github.com/bazelbuild/bazel/blob/08d2c3d63770eadf54443e69f43d44c4f2551d46/tools/cpp/unix_cc_configure.bzl#L76) which just uses `which` to discover the tool locations. So all that is needed is to add `bintools` to the `buildInputs` of `bazel`.

I'll solve this as part of https://github.com/NixOS/nixpkgs/pull/63616.

**Comment by timokau** [comment]
I was a bit too quick, I'm still not able to properly fix the issue.

**Comment by Profpatsch** [comment]
Since we are now at bazel 1.1, is this issue fixed?

**Comment by camtauxe** [comment]
I am still encountering this issue with Bazel v5.4.0. Adding `bintools` or `binutils` to `buildInputs` or `defaultShellUtils` did not help. I think this issue needs to be re-opened.
