### ISSUE TITLE
Type coercion error in make-package-set while building

### ISSUE THREAD

**Issue by enterprisey** [NixOS/nixpkgs#38487]
## Issue description
When I run `nix-build` after cloning [jwiegley/hoogle-local][0], I get the error "value is a function where a list was expected". The stack trace blames [this line][1], character 24, which is the symbol `packages`.

### Steps to reproduce
1. Clone [jwiegley/hoogle-local][0].
2. Cd into the new directory and run `nix-build`.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-116-generic, Ubuntu, 16.04.3 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(daniel): `"nixpkgs-18.09pre134684.9049f8a418b"`
 - nixpkgs: `/home/daniel/.nix-defexpr/channels/nixpkgs`

[0]: https://github.com/jwiegley/hoogle-local
[1]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/make-package-set.nix#L200

**Comment by jwiegley** [comment]
I don't use `hoogle-local` anymore, not since `ghcWithHoogle` became a standard part of `haskellPackages`. I'd encourage building a nix environment (with `nix-shell` or `myEnvFun`) based on that instead.

**Comment by Mic92** [comment]
Should this not be an issue in `hoogle-local` instead of here?

**Comment by enterprisey** [comment]
> Should this not be an issue in hoogle-local instead of here?
That's a good point, my bad.
