### ISSUE TITLE
XFCE: "Lock screen" not working

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#38493]
## Issue description

this is a security issue

see behavior in this video: https://youtu.be/cyklxyVZ_iw

### Steps to reproduce

1. click on "Lock screen" in menu
2. nothing happens

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131768.a74969256b0 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/issues/38492#issuecomment-379335450

**Comment by davidak** [comment]
Right now it works. Was anything changed?

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131802.4b4bbce199d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.03, nixos-hardware, unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Narice** [comment]
@davidak have you succeeded in making it work?
I have the same problem right now (xfce+i3)
I thought it was because I was not using lightdm, but now that I have made the switch, I don't really understand what causes the issue :/

**Comment by Narice** [comment]
here is the utility that is launched:
```sh
# First test for the command set in the session's xfconf channel
LOCK_CMD=$(xfconf-query -c xfce4-session -p /general/LockCommand)

# Lock by xscreensaver or gnome-screensaver, if a respective daemon is running
for lock_cmd in \
    "$LOCK_CMD" \
    "xfce4-screensaver-command --lock" \
    "xscreensaver-command -lock" \
    "gnome-screensaver-command --lock"
do
    if [ ! -z "$lock_cmd" ]; then
        $lock_cmd >/dev/null 2>&1 && exit
    fi
done

# else run another access locking utility, if installed
for lock_cmd in \
  "xlock -mode blank" \
  "slock"
  do
    set -- $lock_cmd
    if command -v -- $1 >/dev/null 2>&1; then
        $lock_cmd >/dev/null 2>&1 &
	# turn off display backlight:
	xset dpms force off
        exit
    fi
done

# else access locking failed
exit 1
```
xfce4-screensaver-command doesn't exist, that is probably the problem here.
the LockCommand can be edited in Settings Manager -> Settings Editor -> xfce4-session -> general -> LockCommand

I however would prefer having the xfce standard lock as I'm sure it's really well integrated with it.

**Comment by Narice** [comment]
xfce4-screensaver-command is not packaged at all in nixpkgs :/

**Comment by Narice** [comment]
Just to add to the comment above about the LockCommand and it someone stumbles upon this issue in the future, the xfce default locker is lightlocker.
If you want to use that, then add the package in your nixos config and set the LockCommand to `light-locker-command -l`
Btw @davidak, pantheon does have a lightlocker installed by default, could the same be done for xfce?

**Comment by malteneuss** [comment]
> Just to add to the comment above about the LockCommand and it someone stumbles upon this issue in the future, the xfce default locker is lightlocker. If you want to use that, then add the package in your nixos config and set the LockCommand to `light-locker-command -l` Btw @davidak, pantheon does have a lightlocker installed by default, could the same be done for xfce?

Thanks, i was having the same issue with XFCE+XMonad, which blocked my laptop from going to sleep when closing the lid with a "None of the screen lock tools ran successfully, the screen will not be locked" popup. Adding 
```
  environment.systemPackages = with pkgs; [
   ...
    lightlocker # Session-locker for XFCE workaround
  ];
```
to my NixOS config and adding light-locker into the XFCE settings worked perfectly.

**Comment by bobby285271** [comment]
We have xfce4-screensaver packaged and shipped in default xfce installations these days and I expect `xflock4` to work. Please open a separate issue if that is not working.
