### ISSUE TITLE
container with privateNetwork fails to start if name is too long

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#38509]
## Issue description

1. make a declarative container, with a long name ("postgres-central" is long enough)
2. set `privateNetwork = true`
3. systemd shortens the ve-interface name and the scripts then fail to find it.

There should probably be an assertion for long container names.

**Comment by arianvp** [comment]
Running into the same issue here. With container name `consul-master-1`.  Renaming to `c1` fixed it.

**Comment by spiderbit** [comment]
stepped into that bug too, did cost me a afternoon to understand that I do nothing wrong but that this is a bug over different versions of nixos 17.09 and 18.03.

The config looked very basic so I could not believe that this basic functionality (have a container with private network enabled) could be broken.

**Comment by arianvp** [comment]
I have filed an issue upstream https://github.com/systemd/systemd/issues/10721

**Comment by flokli** [comment]
IIRC, there's a maximum length of interface names in the kernel, and [nixos' generation code](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/containers.nix#L205) tries to create interfaces with names longer than that.

`systemd-nspawn` generates network interfaces names limited to a maximum of 16 characters (including the null byte), they limit interface size to [IFNAMSIZ](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn-network.c#L185).

We have a similar assertion in `nixos/modules/tasks/network-interfaces.nix` - But not in the bash of `nixos/modules/virtualisation/containers.nix` setting up the containers…

A fix would be to also strip interface names generated to 15 characters, and maybe in the longer run move to generating containers using nspawn ;-)

**Comment by andir** [comment]
Just failing when we observe a name that is too long sound reasonable in this case.

If you decide to do some string magic to make them shorter / unique you are asking for more trouble down the road.. (Users will refer to the non-transformed string somewhere and it will fail anyway, …)

**Comment by arianvp** [comment]
> nd maybe in the longer run move to generating containers using nspawn ;-)

We already do this, and it's actually `systemd-nspawn` who is failing to assert this as well. Hence I filed an issue upstream

**Comment by flokli** [comment]
Ah, I misread the main issue description - sorry.

I'm still not very convinced we should simply fail on `privateNetwork = true`, because some (mostly internal) network interface names would be too long.

Can't we just adapt the documentation, documenting how interface names of containers with longer names will be shortened, and shorten it like systemd would?

This will only change interface names of containers which are currently broken anyhow, and would stop people from bumping into this.

**Comment by arianvp** [comment]
> As for the duplicates problem: How does nspawn handle this, if we let it generate interface names?
Nspawn crashes, see the upstream issue i filed

**Comment by Ekleog** [comment]
(triage) @arianvp 
> What I'm going to do is now change the NixOS module to limit names to 11 characters

Like @andir, I think this is the right way to go. Upstream appears [unwilling to change anything here](https://github.com/systemd/systemd/issues/10721#issuecomment-437816306), and we can actually prevent the user from even switching to a failing configuration by adding such an assertion, so the drawbacks are minimal.

**Comment by arianvp** [comment]
Thanks for the bump. Let's implement that then. I'll do that today

**Comment by kisik21** [comment]
Is https://github.com/systemd/systemd/pull/14467 somehow relevant for lifting the 11-character limitation? Feel free to close if it's not possible to incorporate.

**Comment by arianvp** [comment]
I think it is. We can lift the limit now probably.

**Comment by Patryk27** [comment]
I've prepared a PR - https://github.com/NixOS/nixpkgs/pull/100433 - that lifts this limit on kernels supporting altnames (which is 5.8+, from what I've managed to test).

Just for context: we need support for altnames, because all our container-setup & -cleanup scripts depend precisely on `ve-$containerName` to be available (which is not the case for containers with longer names, since the device's name might get mangled by systemd-nspawn).

**Comment by deliciouslytyped** [comment]
@Patryk27 @flokli https://github.com/NixOS/nixpkgs/commit/336ef2de99197dd9c07b302685dc9e6282fa5b55#diff-9f35243fa1e67cb77387bca245d3bc5011b08ed64326772fb9190a35df438cabR275 breaks building containers in containers (with extra-container at least) because the kernelPackages attribute doesn't exist:

```
$extra-container create container.nix --start --build-args --show-trace                                                                                                                                                  
Building containers...                                                                                                                                                                                                                        
error: while evaluating the attribute 'sources' of the derivation 'etc' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:12:5:                                                                          
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix:20:20, called from undefined position:
while evaluating the attribute 'source' at undefined position:                                                         
while evaluating 'g' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:294:19, called from undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:139:72, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:297:20:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:523:9:    
while evaluating the option `environment.etc.containers/dnsmasq.conf.source':                                          
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:555:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:549:9:   
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:648:7:   
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:17:
while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix':
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:607:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:536:137:
while evaluating the attribute 'condition' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:691:14:
while evaluating the attribute 'text' at undefined position:                                                           
while evaluating 'g' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:294:19, called from undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:139:72, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:297:20:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:523:9:
while evaluating the option `environment.etc.containers/dnsmasq.conf.text':
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:555:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:549:9:                                                                                                                          
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:648:7:                                                                                                                          
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:17:
while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/virtualisation/nixos-containers.nix':
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:607:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:536:137:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:390:44:
while evaluating the attribute 'path' at undefined position:                                                                                                                                                                                  
while evaluating 'g' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:294:19, called from undefined position:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:139:72, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:297:20:
while evaluating the attribute 'value' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:523:9:
while evaluating the option `containers.dnsmasq.path':
while evaluating the attribute 'mergedValue' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:555:5:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:549:9:
while evaluating the attribute 'values' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:648:7:
while evaluating anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:28, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:535:17:
while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/virtualisation/nixos-containers.nix':                                            
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:607:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:536:137:
while evaluating 'dischargeProperties' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:607:25, called from /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:613:11:
while evaluating the attribute 'content' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:691:14:
while evaluating the attribute 'config.system.build.toplevel' at /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/nixos/modules/system/activation/top-level.nix:294:5:
while evaluating 'foldr' at /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/lib/lists.nix:52:20, called from /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/nixos/modul
es/system/activation/top-level.nix:129:12:                                                                             
while evaluating 'fold'' at /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/lib/lists.nix:55:15, called from /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/lib/lists.n
ix:59:8:                                                   
while evaluating anonymous function at /nix/store/4nnwdin1z6qai7rshidrk584p476rng3-nixos-21.05pre281538.9e377a6ce42/nixos/nixos/modules/system/activation/top-level.nix:122:50, called from undefined position:
while evaluating the attribute 'assertion' at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/virtualisation/nixos-containers.nix:484:31:
while evaluating the attribute 'boot.kernelPackages.kernel.version' at undefined position:
attribute 'kernelPackages' missing, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/virtualisation/nixos-containers.nix:275:19
```

`nix repl` tab completes the following in a normal environment:
```
> x = import /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/lib/eval-config.nix {modules = [(import /etc/nixos/configuration.nix)]; }
nix-repl> x.config.boot.kernel
x.config.boot.kernel          x.config.boot.kernelModules   x.config.boot.kernelPackages  x.config.boot.kernelParams    x.config.boot.kernelPatches
```
and the following in a container:
```
> x = import /nix/store/8kigqgbq0xfzac8m0lnqjnmf2rnnqmj3-extra-container-0.6/bin/../share/extra-container/eval-config.nix <nixpkgs/nixos> ./container.nix 
nix-repl> x.config.boot.kernel
x.config.boot.kernel         x.config.boot.kernelModules  x.config.boot.kernelParams
```

**Comment by deliciouslytyped** [comment]
It looks like https://github.com/erikarvstedt/extra-container/blob/307366f0d4c651b8aa6dd6594b7070404aa8a8a7/eval-config.nix#L31 might be part of the issue.

**Comment by deliciouslytyped** [comment]
I'm a bit confused as to how one even would go about solving this, because kernel version is from the perspective of of a container, impure state independent of the container's configs. The impure state would have to be inspected no?

**Comment by arianvp** [comment]
I wonder if better behavior would be to just remove the check altogether...

**Comment by arianvp** [comment]
It seems that upstream actually changed their mind and now truncates to a random hash when the name is too long. So I think we can remove the check altogether properly now? If a longer name is used on an older kernel, systemd will use the hash of the name

https://github.com/systemd/systemd/pull/14467

**Comment by deliciouslytyped** [comment]
Well that seems the best but I think the check is also valid and useful thing, so I don't know what would be good...

**Comment by Patryk27** [comment]
@arianvp the issue is that [our scripts](https://github.com/NixOS/nixpkgs/blob/764448055551a4c664a1b0e2cecfc61731b32c5d/nixos/modules/virtualisation/nixos-containers.nix#L197) assume that a device named `ve-${containerName}` exists. On newer kernels (5.8+) it "just works" because systemd assigns altnames (so both `ve-${hash}` and `ve-${containerName}` exist and refer to the same interface), but it would fail on older kernels (where there's only `ve-${containerHash}`).

In order to drop the assertion safely, instead of relying on `ve-${containerName}`, we could retrieve this shortened, hashed name from systemd - but last time I checked it (when I was implementing https://github.com/NixOS/nixpkgs/pull/100433), I couldn't find an easy, reliable way to ask systemd "what's name of interface for container %s?".

**Comment by Patryk27** [comment]
@deliciouslytyped I've just checked and NixOS's containers-in-containers still work, it's only https://github.com/erikarvstedt/extra-container that, unfortunately, got broken in the process :-/

**Comment by deliciouslytyped** [comment]
It might not break during eval, but do the kernel version values even make sense?

**Comment by deliciouslytyped** [comment]
Can we add an option to disable this until there is a better solution?

**Comment by Patryk27** [comment]
@deliciouslytyped I think it should be possible to detect whether `kernelModules` are empty and, if so, automatically ignore the assertion; I'll try to prepare a patch today 🙂

**Comment by Patryk27** [comment]
@deliciouslytyped on a second thought, there's https://github.com/erikarvstedt/extra-container/pull/18, which I'd personally prefer as a less intrusive attempt than a workaround inside Nixpkgs; does that solution work for you, too?

**Comment by deliciouslytyped** [comment]
What of the issue that kernelVersion doesn't make sense in containers?

**Comment by Patryk27** [comment]
@deliciouslytyped ah, I see your point now (from that linked pull request):

> It's a value nixpkgs generates, instead of deriving it from the environment.

Yes, in this sense the best solution would be to check kernel version during `nixos-rebuild switch` (or a similar command); I started with an assertion, because I wasn't sure how to implement it otherwise 😛 

I'll try to come up with some solution, but pull requests changing that build-time assertion into a runtime one are more than welcome 🙂

**Comment by deliciouslytyped** [comment]
If you are really against reverting, I think merging a toggle in the interim as a bypass or something of the sort would be OK and give time to deal with a more proper fix.

Not to predicate fixing it on a bigger project - but the proper fix sounds like it might be worth a bigger project and PR.
