### ISSUE TITLE
Remove enchant1

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#38506]
Enchant 2 (now the default) is long supported by most packages.

The following packages need to be updated or removed:

- [x] gtkspell2 (dead): https://github.com/NixOS/nixpkgs/pull/211182
- [x] xiphos: https://github.com/NixOS/nixpkgs/pull/154796
- [x] subtitleeditor: #154146
- [ ] xneur: https://github.com/NixOS/nixpkgs/pull/211086 (contains the removal of enchant1)
- [x] gnome2.gtkhtml (dead): https://github.com/NixOS/nixpkgs/pull/210822
- [x] gnome2.gtkhtml4 (dead): https://github.com/NixOS/nixpkgs/pull/154796
- [x] gnome.gtkhtml (dead?): https://github.com/NixOS/nixpkgs/pull/210822
- [x] php.extensions.enchant: https://github.com/NixOS/nixpkgs/pull/211192

**Comment by omasanori** [comment]
This issue is still relevant.

**Comment by Stunkymonkey** [comment]
the list from @jtojnar is not up-to-date. e.g.  `pkgs/applications/video/subtitleeditor/default.nix` is already fixed

**Comment by jtojnar** [comment]
Updated the list.

**Comment by bobby285271** [comment]
Pushed the enchant1 removal commit to #211086
