### ISSUE TITLE
GHC compilation results are not deterministic

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#3851]
On staging we had recently about 1.5k haskell errors that looked like this http://hydra.nixos.org/build/13754221 (I checked a few and they looked all the same). The errors disappeared after a seemingly unrelated single commit 1f2b636ff62.

Looking at that closer... when I fetch the succeeding requisites from Hydra and build the single build referenced above myself, I do reproduce the error. However, when I only fetch stdenv from Hydra and build the rest myself, the build succeeds! It seems that ghc or something built with it succeeded to build impurely on Hydra, but it was broken in fact. That sounds really dangerous.

CC @peti.

**Comment by peti** [comment]
I'm closing this ticket because this issue is outside of our control. The GHC team is working on a fix. My understanding is that, according to @Fuuzetsu, the 7.10.x branch of the compiler improves the situation a lot.

**Comment by Fuuzetsu** [comment]
GHC team is not working on a fix AFAIK, I was ;). Correct that 7.10 improves situation a lot. The biggest issue I can predict is if two different boxes build their own GHC which will happen with 7.8.x or older and result in different core lib ABIs.

For all the other ABI failures, I kindly request that I'm forwarded the store path contents, build logs and basically everything people can.
