### ISSUE TITLE
FHS does not start if current directory is /

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#38525]
## Issue description

if current directory is ```/``` FHS fails with 
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory 
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory      
```

### Steps to reproduce

1. make a ```enter-fhs.nix```:
```
{ buildFHSUserEnv }:

buildFHSUserEnv {
  name = "xxx";
  targetPkgs = pkgs: [  ];
  runScript = ''$SHELL'';
}
```

2. build it
```nix-build -E "(import <nixpkgs> {}).callPackage ./enter-fhs.nix {}"```

3. Now you can enter FHS by running ```"result/bin/xxx"```

4. If you change the directory to / and then run the same ```xxx``` script again, it will fail with

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory 
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory      
```

## Technical details

current master

**Comment by volth** [comment]
Use case:
```systemd``` services have ```/``` as the default working dir, and there are services which require FHS (for example web-services made with Typesafe Activator)

**Comment by lheckemann** [comment]
As far as I can see, this doesn't actually cause any problems besides the error message, does it?

5dee69f7e0b5db11c84c88623e37270804c72a35 seems to fix it though.

**Comment by volth** [comment]
No, the FHS did not start if printed the message.
I will check the patch soon
