### ISSUE TITLE
Firefox package (59.0.2) is missing icon in 18.03

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#38536]
## Issue description
Firefox package in 18.03-stable contains no icon and none is displayed.  
This is because `/nix/store/4ps5j72qc21sib7m7h5mmm4zbj5i5q4f-firefox-59.0.2/share/icons/hicolor/128x128/apps/`  contains no files, but should contain `firefox.png` icon, because `/nix/store/4ps5j72qc21sib7m7h5mmm4zbj5i5q4f-firefox-59.0.2/share/applications/firefox.desktop` references `Icon=firefox` .

**Comment by jtojnar** [comment]
Perhaps https://github.com/NixOS/nixpkgs/pull/37636 needs backporting

**Comment by cx405** [comment]
@jtojnar  Indeed, that would solve the issue.  
`/run/current-system/sw/lib/firefox/browser/chrome/icons/default/` contains all the icon files (default{16,32,48,64,128}.png) in my live system, but they are linked to `/run/current-system/sw/lib/firefox/browser/icons/` (notice the absent "chrome") according to https://github.com/NixOS/nixpkgs/blob/staging-18.03/pkgs/applications/networking/browsers/firefox/wrapper.nix

Thank you very much for cross-finding this!

**Comment by alexeymuranov** [comment]
My Firefox icon disappeared still with 17.09. Today i restarted Gnome Shell, and icons for Chromium, Geary, and VLC are now gone too.

**Comment by vcunat** [comment]
Right, fixed for me as well; backported as eb5a7a5bf97.
