### ISSUE TITLE
Google compute engine image uses wrong MTU for eth0

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#38543]
## Issue description

The MTU of the ethernet should be set to 1460 on google cloud platform, but it is set to 1500. For me this has occasionally, but not always caused the ssh terminal to hang when lots of data is being printed, and I assume could be causing other people issues. 

from https://cloud.google.com/compute/docs/troubleshooting/general-tips -
```
The VPC network has a maximum transmission unit (MTU) of 1460 bytes for Linux images 
...
 For custom images, set the MTU to 1460 for custom Linux images and Windows Server images to avoid the increased latency and packet overhead caused by fragmentation.
```

### Steps to reproduce

Create a google compute engine nixos image from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/google-compute-image.nix

observe the mtu on eth0 is 1500.

Set the following:
```networking.interfaces.eth0.mtu = 1460;```  to fix the issue.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by wmertens** [comment]
I created #38605 based on what you wrote but didn't test it.

**Comment by andrewchambers** [comment]
Thanks, that fix was enough for me, though I don't know if it works in all situations, or if DHCP is not picking up some parameter like it is supposed to. I don't really know how to proceed with a fix for sure, but I thought I would document the issue.
