### ISSUE TITLE
How to override the default compiler

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#38552]
I'm looking to compile some packages using gcc 4.8. My original thought was to only override ```stdenv``` for C++ packages (I assumed that only C++ ABI will be incompatible between gcc7 and gcc4.8). This worked well until I've tried to build boost:
```nix
{ nixpkgs ? import <nixpkgs> {} }:

let
  stdenv = nixpkgs.overrideCC nixpkgs.stdenv nixpkgs.gcc48;
in
  {
    boost = nixpkgs.boost.override { inherit stdenv; };
  }
```
This clearly builds ```gcc-gnu-7.3.0``` configuration that is incompatible with the rest of my packages. This seems to be due to boost using ```buildPackages.stdenv.cc``` in ```nativeBuildInputs```, which I don't quite understand.

I've decided that I might need to do a global override (actually I would prefer it that way). My first thought was to use overlays:
```nix
{ nixpkgs ? import <nixpkgs> {} }:

let
  overlay = self: super: {
    stdenv = super.overrideCC nixpkgs.stdenv nixpkgs.gcc48;
  };
in
  import <nixpkgs> { overlays = [ overlay ]; }
```
This is ugly, but it fixes boost. Unfortunately this breaks ```pam```:
```
libtool: link: gcc -g -O2 -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -Wwrite-strings -Winline -Wshadow -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -o padout parse_l.o parse_y.o
parse_y.o: In function `memset':
/nix/store/cbr1j6vv0zss8x4dkv9i2rqqlwkc8fp9-glibc-2.26-131-dev/include/bits/string_fortified.h:67: undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
```
This is seems to be due to glibc being compiled with bootstrap-gcc which is version 7.3. I haven't figured out how to overcome this.

Does anybody have suggestions how I can compile packages with a different compiler?

**Comment by ashgillman** [comment]
Any luck with this @veprbl ?

**Comment by veprbl** [comment]
@ashgillman No progress on my side.

**Comment by ashgillman** [comment]
Bugger, thanks

--

Sent from my mobile. Please excuse brevity and any spelling mistakes.

Ashley Gillman
On 23 Jul. 2018, at 20:15, Dmitry Kalinkin <notifications@github.com<mailto:notifications@github.com>> wrote:

@ashgillman<https://github.com/ashgillman> No progress on my side.

**Comment by ashgillman** [comment]
I've had some luck with
```
  let
    nixpkgsFn = import <devpkgs>;
    # first instance
    pkgs = nixpkgsFn {};
    # second instance, using gcc49
    gcc49Pkgs = nixpkgsFn {
      config = {};
      overlays = [(self: super: {
        stdenv = super.overrideCC pkgs.stdenv pkgs.gcc49;
        inherit (pkgs) pam gcc48 gcc49 gcc5 gcc6 gcc7 gcc8;
      })];
    };
in
  ...
```

**Comment by matthewbauer** [comment]
This is tricky to fix. You could override the buildPackages as well:

```
{ nixpkgs ? import <nixpkgs> {} }:

let
  stdenv = nixpkgs.overrideCC nixpkgs.stdenv nixpkgs.gcc48;
in
  {
    boost = nixpkgs.boost.override {
      inherit stdenv;
      buildPackages = nixpkgs.buildPackages // { inherit stdenv; };
    };
  }
```

But this is definitely awkward. The main issue is that we always give listed dependencies preference in the path. You could also force boost to add the compiler on top of buildPackages.stdenv.cc:

```
{ nixpkgs ? import <nixpkgs> {system="x86_64-linux";} }:

let
  stdenv = nixpkgs.overrideCC nixpkgs.stdenv nixpkgs.gcc48;
in
  {
    boost = (nixpkgs.boost.override {
      inherit stdenv;
    }).overrideAttrs (o: {
      nativeBuildInputs = [nixpkgs.gcc48] ++ o.nativeBuildInputs;
    });
  }
```

/cc @Ericson2314

**Comment by Ericson2314** [comment]
Hmm I'd think the CC_FOR_BUILD and CC environment variables would be defined correctly on the native case, if only we could use full paths for them to not get screwed by PATH.

**Comment by matthewbauer** [comment]
Arent they just gcc?

**Comment by Ericson2314** [comment]
@matthewbauer yeah because we reverted that PR. Just saying this thing is perhaps closer in principle. I hope with your `disallowedRequisites` change, we get slightly closer to being able to redo the full path in env var change.

**Comment by matthewbauer** [comment]
But, we really need something a little less strict like ```ignoreRequisites``` or something. Lots of packages hardcode CC for debugging.

**Comment by Ericson2314** [comment]
@matthewbauer if we could nuke references in a `preCheck` hook, that would also be interesting.

**Comment by AleXoundOS** [comment]
This is still tricky and there is no clear comprehensive documentation for overriding compiler in various cases.

**Comment by vcunat** [comment]
That's because C++ does not have a stable ABI (contrary to C), so you can't freely mix different compiler versions (or even vendors).

**Comment by milahu** [comment]
yes. my point is, it works without patching nixpkgs

i guess that OP's `overrideCC` is wrong

```nix
{
  # OP -> linking errors
  stdenv = super.overrideCC nixpkgs.stdenv nixpkgs.gcc48;

  # works
  stdenv = gccStdenv;

  # maybe works
  stdenv = gcc48Stdenv;
  gcc48Stdenv = overrideCC gccStdenv buildPackages.gcc48;

  # all-packages.nix
  gcc8Stdenv = overrideCC gccStdenv buildPackages.gcc8;
  gccStdenv =
    if stdenv.cc.isGNU
    then stdenv
    else stdenv.override {
      cc = buildPackages.gcc;
      allowedRequisites = null;
      # Remove libcxx/libcxxabi, and add clang for AS if on darwin (it uses
      # clang's internal assembler).
      extraBuildInputs = lib.optional stdenv.hostPlatform.isDarwin clang.cc;
    };
```

**Comment by veprbl** [comment]
It would seem like a viable solution is described in
https://nixos.wiki/wiki/Using_Clang_instead_of_GCC#Globally.2C_in_a_package_repository_tree
