### ISSUE TITLE
LaTeX fonts not found

### ISSUE THREAD

**Issue by robertodr** [NixOS/nixpkgs#38562]
## Issue description

Upgrading to 18.03 broke compilation of a LaTeX publisher template:
```
kpathsea: Running mktexpk --mfmode / --bdpi 600 --mag 0+372/600 --dpi 372 Lato-Italic-T1-TLF--base
omktexpk: don't know how to create bitmap font for Lato-Italic-T1-TLF--base.
mktexpk: perhaps Lato-Italic-T1-TLF--base is missing from the map file.
kpathsea: Appending font creation commands to missfont.log.
```
### Steps to reproduce

The template is available [here](https://www.overleaf.com/latex/templates/template-for-submissions-to-international-journal-of-quantum-chemistry/pfnzxpxtmhyt) I have `texlive.combined.scheme-full` installed globally.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(roberto): `""`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by cmal** [comment]
Hi, @robertodr ！ Have you solved this?
I used `nix-env -iA texlive-combined-full` to install TeXLive, and `xelatex` cannot found font, either.
I've asked the tex community but it seems this is a problem only related to nix package.
The question I asked is here:
https://tex.stackexchange.com/questions/466318/fontspec-can-not-find-the-font-file-to-work-on-mac-os?noredirect=1#comment1172143_466318

**Comment by veprbl** [comment]
Can somebody provide minimal steps to reproduce?

I try:
1. Have `texlive.combined.scheme-full` installed using nix-env from the master branch of nixpkgs
2. Go to https://www.overleaf.com/latex/templates/template-for-submissions-to-international-journal-of-quantum-chemistry/pfnzxpxtmhyt , click "View source", copy that to test.tex
3. wget https://raw.githubusercontent.com/P1xt/gamedev-notes/master/wiley-article.cls
4. pdflatex test.tex

It compiles, I get a document.
