### ISSUE TITLE
mktemp from coreutils doesn't work on darwin

### ISSUE THREAD

**Issue by fkorotkov** [NixOS/nixpkgs#38578]
## Issue description

`mktemp` fails with `too few X's in template` on Darwin when tries to create a temporary directory.

### Steps to reproduce

```
$: nix-shell --packages coreutils --run "which mktemp && mktemp -d -t foo"
/nix/store/s28xb9v7xf6axvf4a3av2mnczws2hsdg-coreutils-8.29/bin/mktemp
mktemp: too few X's in template ‘foo’
```

## Technical details

```
$: nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/aiaqhmk1x114msypcykhi27n6iydrhjm-nix-info
  /nix/store/ln5498nmkjkv1ssa2x644czc7x1xwcx6-DarwinTools-1
copying path '/nix/store/ln5498nmkjkv1ssa2x644czc7x1xwcx6-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/aiaqhmk1x114msypcykhi27n6iydrhjm-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.09pre133932.ee28e35ba37"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

/cc maintainer @edolstra

**Comment by matthewbauer** [comment]
Is there a particular script that does this? AFAIK this is the GNU behavior of the template flag. You can just add 8 X's to get the same as in BSD mktemp:

```
nix-shell --packages coreutils --run "which mktemp && mktemp -d -t foo.XXXXXXXX"
```

**Comment by fkorotkov** [comment]
@matthewbauer yeah, that will work, but `mktemp` is invoked by `xcodebuild` which I don't have control of. I'm trying to run `xcodebuild` within `nix` for CI purposes.

I probably should add "as expected" to the title of the issue, since darwin's mktemp works differently:

```
fedor-mbp $: nix-shell --packages coreutils --run "/usr/bin/mktemp -d -t foo"
/var/folders/_r/wmcjfw296f56jrysrxtrx7sc0000gn/T/foo.2gpdXjVm
```

That was particularly surprising for me since `coreutils` is in the path by default and it took me a while to figure out that the error that I've seen was caused by a different `mktemp`. I'm not sure what is the right thing to do here 🤷‍♂️  At least there should be a workaround or maybe a package with darwin's `mktemp` so people can use it.

**Comment by matthewbauer** [comment]
If you really need it, they are currently included in the attribute ```darwin.shell_cmds``` but I doubt it works on Linux.

**Comment by fkorotkov** [comment]
@matthewbauer wow! Thank you for pointing to `darwin.shell_cmds`. Last question is how to exclude `coreutils` from `$PATH` in `nix-shell` since:

```
nix-shell --packages darwin.shell_cmds --run "echo \$PATH"
```

shows that `coreutils` comes first and therefore hides `shell_cmds` 😅

BTW thank you so much for your help! I've just started learning Nix and you help is priceless. 🙏

**Comment by fkorotkov** [comment]
@matthewbauer do you think it's reasonable to prioritize user defined packages in `$PATH`? In this case I can create a separate issue.

I'm closing this issue since `mktemp` from `darwin.shell_cmds` works.

**Comment by matthewbauer** [comment]
Yes i think you might need to override PATH to get it to work.

**Comment by matthewbauer** [comment]
So I actually think this is a Nixpkgs issue. It only happens with "coreutils" (we override gnumake all the time). So I wonder if there's something else going on?.
