### ISSUE TITLE
Waterfox added to nixpkgs

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#38617]
## Issue description
The whole firefox shebang is a little too complicated for me.
I would really appreciate it if someone could add waterfox to the repository.
Especially since Mozilla has some very unsavory defaults in terms of tracking.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.03.git.d306aba (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131807.489a14add9a, nixos-unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by wamserma** [comment]
@Chiiruno is this still relevant?

**Comment by leungbk** [comment]
Waterfox would be a great addition.

**Comment by mnajib** [comment]
Waterfox would be a great addition.

**Comment by SebTM** [comment]
I would also love to see Waterfox on NixOS 👍🏻 Maybe if I have some time I will try to get some basics done, but might not get it done/working alone...

**Comment by Madouura** [comment]
4 years...

**Comment by milahu** [comment]
there is librewolf since 5 months https://github.com/NixOS/nixpkgs/pull/151439

**Comment by Madouura** [comment]
Eh, good enough.
