### ISSUE TITLE
18.03: ntpd fails to shutdown properly

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#38627]
## Issue description
Whether during normal shutdown, or forced via "#systemctl stop ntpd", the service always hangs for 90 seconds and is then killed. It always hangs.

After boot into desktop, ntpd has this status:
```
# systemctl status ntpd
● ntpd.service - NTP Daemon
   Loaded: loaded (/nix/store/chpk0l1j19jbb9dg54vgyxfka5a11i1q-unit-ntpd.service/ntpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-04-09 08:21:41 CEST; 1h 21min ago
  Process: 614 ExecStart=ntpd -g -c /nix/store/2xpqypfsji8h1fsmc639wh8a5gdi1hdw-ntp.conf -u ntp:nogroup (code=exited, status=0/SUCCESS)
  Process: 601 ExecStartPre=/nix/store/idgqdvm7az9g98n7g1d4ni04nn98l9jw-unit-script/bin/ntpd-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 651 (ntpd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/ntpd.service
           ├─651 [ntpd]
           └─663 ntpd -g -c /nix/store/2xpqypfsji8h1fsmc639wh8a5gdi1hdw-ntp.conf -u ntp:nogroup

апр 09 08:21:34 nix01 ntpd[651]: Listen and drop on 1 v4wildcard 0.0.0.0:123
апр 09 08:21:34 nix01 ntpd[651]: Listen normally on 2 lo 127.0.0.1:123
апр 09 08:21:34 nix01 ntpd[651]: Listen normally on 3 lo [::1]:123
апр 09 08:21:34 nix01 ntpd[651]: Listening on routing socket on fd #20 for interface updates
апр 09 08:21:34 nix01 ntpd[651]: ntpdmain: seccomp_init(SCMP_ACT_KILL) succeeded
апр 09 08:21:34 nix01 ntpd[651]: ntpdmain: seccomp_load() succeeded
апр 09 08:21:41 nix01 systemd[1]: Started NTP Daemon.
апр 09 08:21:55 nix01 ntpd[651]: Listen normally on 4 eno1 192.168.2.142:123
апр 09 08:21:55 nix01 ntpd[651]: Listen normally on 5 eno1 [fe80::3a60:77ff:fe9c:2673%2]:123
апр 09 08:21:55 nix01 ntpd[651]: new interface(s) found: waking up resolver
```

After "# systemctl stop ntpd" which takes 90 seconds, "journalctl -x" shows this on service shutdown:
```
апр 09 03:32:37 nix01 systemd[1]: Stopping NTP Daemon...
-- Subject: Начинается остановка юнита ntpd.service
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Начат процесс остановки юнита ntpd.service.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: State 'stop-sigterm' timed out. Killing.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Killing process 651 (ntpd) with signal SIGKILL.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Killing process 660 (ntpd) with signal SIGKILL.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Main process exited, code=killed, status=31/SYS
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Failed with result 'timeout'.
апр 09 03:34:07 nix01 systemd[1]: Stopped NTP Daemon.
-- Subject: Завершена остановка юнита ntpd.service.
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Процесс остановки юнита ntpd.service был завершен.
```
which reminds of #21136, however this is 18.03 desktop system.

```
# systemctl status ntpd
● ntpd.service - NTP Daemon
   Loaded: loaded (/nix/store/chpk0l1j19jbb9dg54vgyxfka5a11i1q-unit-ntpd.service/ntpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2018-04-09 03:34:07 CEST; 11min ago
 Main PID: 651 (code=killed, signal=SYS)

апр 08 21:51:46 nix01 ntpd[651]: Listen normally on 4 eno1 192.168.2.142:123
апр 08 21:51:46 nix01 ntpd[651]: Listen normally on 5 eno1 [fe80::3a60:77ff:fe9c:2673%2]:123
апр 08 21:51:46 nix01 ntpd[651]: new interface(s) found: waking up resolver
апр 09 03:32:37 nix01 systemd[1]: Stopping NTP Daemon...
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: State 'stop-sigterm' timed out. Killing.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Killing process 651 (ntpd) with signal SIGKILL.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Killing process 660 (ntpd) with signal SIGKILL.
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Main process exited, code=killed, status=31/SYS
апр 09 03:34:07 nix01 systemd[1]: ntpd.service: Failed with result 'timeout'.
апр 09 03:34:07 nix01 systemd[1]: Stopped NTP Daemon.

```

## Technical details
- system: `"x86_64-linux"`
 - host os: `Linux 4.15.15, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131807.489a14add9a, nixos-master-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by cx405** [comment]
Updated.

**Comment by teto** [comment]
this happens to me again on unstable. Is this an upstream issue again or ?

**Comment by dhess** [comment]
> this happens to me again on unstable. Is this an upstream issue again or ?

I'm having the same issue. This is on a fairly recent nixpkgs.

**Comment by anoother** [comment]
I'm also experiencing this, on 20.09

**Comment by thoughtpolice** [comment]
If it's anything like the last problem, this is due to a seccomp failure (perhaps glibc internals changed, necessitating a change of filter logic once again...)

Can one of you please open a new issue so we can track this in 20.09 and CC me? Thanks

**Comment by FlorianFranzen** [comment]
@thoughtpolice This has been an issue for me as well on 20.09. Furthermore ntpd would just stop syncing all together just leaving a `kernel reports TIME_ERROR: 0x41: Clock Unsynchronized` in the logs. I switched to `timesyncd` for the time being and I lack the resources to investigate this any further at the moment.

**Comment by domenkozar** [comment]
I've just removed ntp so it's handled by systemd, but I hit this consistently on 21.05

**Comment by mrkkrp** [comment]
This happens on every shutdown an is very annoying.

**Comment by mrkkrp** [comment]
I ended up by switching to `chrony`. `ntpd` proved to be very unfriendly: it keeps saying `Clock Unsynchronized` but when I added an option to make the log more verbose (hoping to understand also what exactly happens during shut downs) it started to hang on startup so that systemd had to shut it down after a timeout. In addition to that if a process is started on its own it is very difficult to kill... No problems with `chrony`.

**Comment by zarelit** [comment]
@mrkkrp  same here, switched to `chrony` for the time being

**Comment by Fuuzetsu** [comment]
ntpd has been broken for my this way for the longest time, switching to `timesyncd` was trivial and appears to be working well

**Comment by pnmadelaine** [comment]
having the same issue at every shutdown on `nixos-unstable`
