### ISSUE TITLE
Google cloud image for 18.03 is not public.

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#38623]
## Issue description

Unable to download the public google cloud image, 

### Steps to reproduce
```
$ gsutil cp gs://nixos-images/nixos-image-18.03.131802.4b4bbce199d-x86_64-linux.raw.tar.gz ./
AccessDeniedException
```

Can confirm the other very outdated images are downloadable.

## Technical details

The bucket object is not world readable.

**Comment by andrewchambers** [comment]
Would really appreciate a fix to this, combined with #38608 I can't create a working vm.

**Comment by edude03** [comment]
Having the same issue

**Comment by rbvermaa** [comment]
Where did you get the link from? I think the URI should be: gs://nixos-cloud-images/nixos-image-18.03.131802.4b4bbce199d-x86_64-linux.raw.tar.gz

**Comment by rbvermaa** [comment]
I have removed that image, as the nixos-images bucket is an old bucket. Probably got upload accidentally, when the creation script referred to it still.

I tried generating a new image, however, that has issues connecting via ssh (nixops), as some code was removed from nixpkgs that downloads SSH host key from metadata in a2c900dc879f71a658a5f17d9d83f9e79b25787d. 

I might have time to look into that next week. Not sure yet what the correct way forward is.

**Comment by AmineChikhaoui** [comment]
I'll have look at the issue in nixops this weekend.

**Comment by edude03** [comment]
Is there a new 18.03 image now @AmineChikhaoui ? I can't seem to find a link to it in the nixpkgs repo.

**Comment by AmineChikhaoui** [comment]
@edude03 I think the issue preventing the image generation was fixed now. Otherwise, afaik @rbvermaa takes care of updating the images, so better ask him if there is anything else pending ?

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/issues/50259 (25 days ago) mentions an image from May 29 currently being present, after these comments, but still quite old, and for 18.03, 18.09 is still missing.
Closing this issue in favour of https://github.com/NixOS/nixpkgs/issues/50259 .
