### ISSUE TITLE
absence of /etc/iproute2/rt_tables

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#38638]
## Issue description

I need to do some source routing as explained in http://www.tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.rpdb.simple.html
My scripts create route aliases dynamically via

`echo "$NUM  $DEVICE_IFACE" >> /etc/iproute2/rt_tables`
but the file doesn't exist on nixos (well it is in /nix/store/28mwpyfh46m5l8wc3ia5p5cnnf90fvcx-iproute2-4.15.0/etc/iproute2/rt_tables) but ip will read from /etc/iproute2/rt_tables

As I want to edit it dynamically it can't be a module, but a package can't write in /etc so how can I copy /nix/store/28mwpyfh46m5l8wc3ia5p5cnnf90fvcx-iproute2-4.15.0/etc/iproute2/rt_tables to /etc/iproute2/rt_tables once, as a post-install step/nixos-rebuild ?

### Steps to reproduce

`strace -olog -f  ip route show table toto`
will give
```
7982  openat(AT_FDCWD, "/etc/iproute2/rt_tables", O_RDONLY) = -1 ENOENT (No such file or directory)
7982  open("/etc/iproute2/rt_tables.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
7982  write(2, "Error: argument \"toto\" is wrong:"..., 60) = 60
```

## Technical details
On nixos-unstable

**Comment by volth** [comment]
> As I want to edit it dynamically it can't be a module, but a package can't write in /etc so how can I copy /nix/store/28mwpyfh46m5l8wc3ia5p5cnnf90fvcx-iproute2-4.15.0/etc/iproute2/rt_tables to /etc/iproute2/rt_tables once, as a post-install step/nixos-rebuild ?

```
      environment.etc."iproute2/rt_tables.d" { text = "..."; mode = "0644"; }
```

```mode = "0644";``` forces /etc/iproute2/rt_tables to be a editable file instead of symlink to "/nix/store" which will be overwritten on each "nixos-rebuild"

---

This is not completely module-less solution. If you really need that, ```wrapProgram``` might help, something like
```
   wrapProgram $out/bin/ip --run ${lib.escapeShellArg ''
     [ -f /etc/iproute2/rt_tables ] || echo ${lib.escapeShellArg ''
        initial content
     ''} > /etc/iproute2/rt_tables 
   ''}
```

**Comment by teto** [comment]
thanks @volth . I like the 
`environment.etc."iproute2/rt_tables" = { text = "..."; mode = "0644"; };` (the second solution would erase my changes).
I would like to submit a PR that fixes this issue. Would adding your first suggestion to activationCommands when iproute is installed be ok ?

**Comment by teto** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/39536
