### ISSUE TITLE
Request documentation of official support policy and release lifetime documentation

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixpkgs#38631]
## Issue description

It would be nice if there were some official policy of when security/reliability patches end for each channel and when users are expected to upgrade. Also documentation explaining when/if the binary caches will stop working for very old channels.

For example on openbsd the two last releases (12 months) receive security and reliability fixes for the base system (kernel, openssh, base system utilities), but not for extra packages.

**Comment by andrewchambers** [comment]
I was reading the dev forum and people definitely mention dates and time windows, it just doesn't seem to be written down in the release notes or close to any of the download links,

**Comment by Profpatsch** [comment]
My ideas can be found here: https://nixos.wiki/wiki/User:Profpatsch#nixpkgs-support-matrix

**Comment by andrewchambers** [comment]
@Profpatsch That's exactly the sort of thing I was looking for, just with dates attached to each version.

As a new person, my perspective is that part of the issue is nixpkgs is developed in a volunteer and "on demand" basis. I know would is unrealistic to just assume writing a schedule magically makes the man power and organization available, so I guess it should be a very conservative set of commitments.

**Comment by vcunat** [comment]
For 18.03 I noted the support plans in the [release notes}(https://nixos.org/nixos/manual/release-notes.html#sec-release-18.03).

**Comment by vcunat** [comment]
I believe all release notes since then also start with stating the EOL.  I can't see anything actionable.  If you do, say so and we can reopen (and actually do something about it).
