### ISSUE TITLE
fetchzip does not set ownership / permissions on $out

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [NixOS/nixpkgs#38649]
see https://github.com/NixOS/nix/issues/2054

## Issue description

1. the following `nix` snippet:
```nix
    src = fetchzip {
      stripRoot = true;
      url = "http://download.scala-ide.org/sdk/lithium/e47/scala212/dev/update-site.zip" ;
      sha256 = "1kn9s0wl75i4372srdajcvaqwy723lbvlaad904f4i7r75w0w3si";
    };
```
2. produces error:
```bash
suspicious ownership or permission on '/nix/store/1mh4hzphspcm6qmn5wljg8r8q78i19ca-source'; rejecting this build output
```

3. inside the validation here:
https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L3059

4. due to `fetchzip does not set ownership / permissions  on $out` here:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchzip/default.nix#L46

5. and indeed, `*-source` has `rwx` for group `nixbld` as shown:
```bash
 ls -las /nix/store/1mh4hzphspcm6qmn5wljg8r8q78i19ca-source
total 556
  4 drwxrwxr-x   4 nixbld1 nixbld   4096 Jan  3 02:05 .
516 drwxrwxr-t 515 root    nixbld 524288 Apr  7 17:45 ..
  4 -rw-rw-r--   1 nixbld1 nixbld   2701 Jan  3 02:05 artifacts.jar
 20 -rw-rw-r--   1 nixbld1 nixbld  18952 Jan  3 02:05 content.jar
  4 drwxrwxr-x   2 nixbld1 nixbld   4096 Jan  3 02:05 features
  4 drwxrwxr-x   2 nixbld1 nixbld   4096 Jan  3 02:05 plugins
  4 -rw-rw-r--   1 nixbld1 nixbld   2304 Jan  3 02:05 site.xml
```
6. the following replacement `nix` is a `extraPostFetch/chmod` hack to make it work:
```nix
    src = fetchzip {
      stripRoot = true;
      url = "http://download.scala-ide.org/sdk/lithium/e47/scala212/dev/update-site.zip" ;
      sha256 = "1gdi95m14vjiwz76z0jq3bm340lsfzfnb1gjnviisi9dp7xvk81i";
      extraPostFetch = ''
        chmod go-w $out
      '';
    };
```
### Steps to reproduce

use `nix-shell`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.15-1-ARCH, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.09pre133640.ea145b68a01, nixpkgs-18.09pre134746.9430efbe49d"`
 - channels(user0): `"nixos, nixpkgs"`
 - nixpkgs: `/home/user0/.nix-defexpr/channels/nixpkgs`

**Comment by tinybeachthor** [comment]
Just had this same issue.
