### ISSUE TITLE
ZFS 0.7.7 leads to disappearing files

### ISSUE THREAD

**Issue by shosti** [NixOS/nixpkgs#38666]
## Issue description

See https://github.com/zfsonlinux/zfs/issues/7401 -- it looks like ZoL 0.7.7 has a bug that can lead to data loss. They seem to recommend rolling back to 0.7.6 until there's a fix available.

### Steps to reproduce

I was able to reproduce using this script: https://gist.github.com/trisk/9966159914d9d5cd5772e44885112d30

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(shosti): `""`
 - channels(root): `"nixos-18.03.131807.489a14add9a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by matthewbauer** [comment]
I think is makes sense to just revert it in 18.03 and just wait on nixpkgs-unstable until a fix is released.

Any objections? Relevant commit is 8c3cb029e0f4b771676d1e291f1316353ec9a0eb

**Comment by gebner** [comment]
This is now fixed via an upgrade to 0.7.8 on both master and stable branches: https://github.com/NixOS/nixpkgs/pull/38672
