### ISSUE TITLE
18.03 unknown error 4094 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#38673]
## Issue description
I tried to restore my boot section from a USB key with graphical 18.03 on it but I got disappointed by successive problems.

As advised on irc, I mounted /mnt & /mnt/boot, ran nixos-enter then nixos-rebuild boot but got this kind of error
![img_20180410_153652](https://user-images.githubusercontent.com/886074/38540604-74d9c70a-3cd7-11e8-856a-23109ee4bed6.jpg).
I decided to resort to nixos-install which produced the exact message in the screenshot.

I then tried the command (systemctl start display-manager) to start the graphical interface, X wouldn't launch because my screen is not appropriate (pretty standard `eizo screen`) ?! 
![img_20180410_141143](https://user-images.githubusercontent.com/886074/38541191-4c1edcae-3cd9-11e8-91eb-4693404a1e57.jpg)

Either I am uncredibly unlucky or there are some serious problems with 18.03 ? 

### Steps to reproduce
for me it was mounting my partitions on /mnt & /mnt/boot than running nixos-install

**Comment by dezgeg** [comment]
What filesystem is that? Google claims `Unknown error 4094` is filesystem-related trouble. Can you manually run the `stat` shell command on that path?

**Comment by teto** [comment]
I can't get access to these logs anymore, now nixos is installed closing
