### ISSUE TITLE
18.03 manual error : mkfs.fat doesn't have -L flag

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#38674]
## Issue description

1/
The manual contains this command https://nixos.org/nixos/manual/
`# mkfs.fat -F 32 -L boot /dev/sda3`
but it should be 
`# mkfs.fat -F 32 -n BOOT /dev/sda3`

as mkfs.fat doesn't accept the -L flag and it will warn when using lowercase

2/ the manual recommands `# mount /dev/disk/by-label/nixos /mnt` but this gives "unknown filesystem type LVM2_member` for lvm

3/ it says to mount a drive in /mnt/boot but the folder doesn't exist

4/ apparently nixos-generate-config doesn't setup the root filesystem with LLVM:
"the fileSystems option does not specify your root file system"

Other propositions:
- Add useOSProber in the nixos-generate-config

I know nixos targets more advanced users but I guess this can still be improved

**Comment by ckauhaus** [comment]
The LVM example is meant as an additional way to explore. Simply following the command in the order presented is not promising.

I'd suggest to leave out the logical volume setup code. Users with LVM knowledge probably know how to operate `pvcreate` and friends. For users without LVM knowledge this is probably misleading.

**Comment by teto** [comment]
thanks for the fixes !
