### ISSUE TITLE
Is there a way to build Bootstrap on NixOS?

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#38683]
## Issue description & Steps to reproduce

I tried to build bootstrap from sources following these instructions: https://getbootstrap.com/docs/4.1/getting-started/build-tools/. All went well until I executed

```
$ bundle install
```

At which point it encountered a dependency which requires `zlib`, namely `nokogiri` version 1.8.2. And that fails of course, because it can't find include files afaiu.

Is there a way to solve this?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.29, NixOS, 18.09pre133640.ea145b68a01 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.09pre133640.ea145b68a01"`
 - channels(mark): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mrkkrp** [comment]
From what I currently understand about Nix/NixOS, either bundler should be patched, or all gems should be pre-packaged so they will somehow be passed the correct `-I` flags and their rpaths will be set to paths from Nix store. Am not sure either of these options is implemented. Probably there is a way to make this work still?

**Comment by matthewbauer** [comment]
There definitely is room for improvement here. But, for something like this, it's common to just use nix-shell:

```
nix-shell -p nodejs ruby zlib libiconv
```

And things should install.

**Comment by mrkkrp** [comment]
OK, thinking about passing arguments to things like `ld` via environment variables, this starts to make sense.
