### ISSUE TITLE
Packaging up labelImg

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#38716]
The labelImg project is a Python GUI application using QT5.

I've got it working in a nix-shell. But I'm trying to write the default.nix for it.

```nix
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/49a0ecc49b491c1f1a6f329d3d4fc9cf559b18aa.tar.gz) {}
}:
  with pkgs;
  python3Packages.buildPythonApplication rec {
    # setting the format to other results in another problem
    # the system doesn't know how to setup the python dependencies
    format = "other";
    name = "labelImg-${version}";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/tzutalin/labelImg/archive/v${version}.tar.gz";
      sha256 = "126kc4r7xm9170kh7snqsfkkc868m5bcnswrv7b4cq9ivlrdwbm4";
    };
    propagatedBuildInputs = with python3Packages; [
      pyqt5
      lxml
    ];
    doCheck = false;
    buildPhase = ''
      make qt5py3
    '';
    installPhase = ''
      mkdir -p $out/bin
      cp -r data $out
      cp -r icons $out
      cp -r libs $out
      cp labelImg.py $out
      cp __init__.py $out
      cp resources.qrc $out
      cp resources.py $out
      makeWrapper $out/labelImg.py $out/bin/labelImg \
        --set QT_QPA_PLATFORM_PLUGIN_PATH ${qt5.qtbase.bin}/lib/qt-*/plugins/platforms
    '';
  }
```

The main problem is that it's not a normal `setup.py` installation. Instead the installation just runs it from source. So basically I need the normal behaviour of `buildPythonApplication` but without it trying to run the `setup.py`. That's according to the README.

However it does actually have a `setup.py`. If I remove my custom build instructions and remove the `format` key. Then it results in this error:

```
patching sources
configuring
building
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 8, in <module>
    readme = readme_file.read()
  File "/nix/store/p1bp0kpmxi7nzrla7n7c4waqic0a2myk-python3-3.6.4/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5389: ordinal not in range(128)
builder for ‘/nix/store/fs7d500z9y7snvlszc6wlzz7p79q80dr-labelImg-1.6.0.drv’ failed with exit code 1
error: build of ‘/nix/store/fs7d500z9y7snvlszc6wlzz7p79q80dr-labelImg-1.6.0.drv’ failed
```

This may be because the setup.py was written for python2 and not 3?

If I keep using my custom build instructions then I need something to maintain the python environment. I'm not sure how to do that.

**Comment by CMCDragonkai** [comment]
Alright I got it working with Python 2 and Qt4:

```nix
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/49a0ecc49b491c1f1a6f329d3d4fc9cf559b18aa.tar.gz) {}
}:
  with pkgs;
  python2Packages.buildPythonApplication rec {
    name = "labelImg-${version}";
    version = "1.6.0";
    src = fetchurl {
      url = "https://github.com/tzutalin/labelImg/archive/v${version}.tar.gz";
      sha256 = "126kc4r7xm9170kh7snqsfkkc868m5bcnswrv7b4cq9ivlrdwbm4";
    };
    propagatedBuildInputs = with python2Packages; [
      pyqt4
      lxml
    ];
    preBuild = ''
      make qt4py2
    '';
  }
```

This has no problems with finding QT plugins. But if we switch to python3 we would need to use qt5. If we are using qt5, we need to use the `makeWrapper` or `wrapProgram` and use `--set QT_QPA_PLATFORM_PLUGIN_PATH ${qt5.qtbase.bin}/lib/qt-*/plugins/platforms`. However the normal `buildPythonApplication` already wraps the original program. Is there a way to hook into that wrapper, or is the correct way to wrap the wrapper?

Anyway since the `setup.py` doesn't work in Python3, it doesn't seem like `python3.buildPythonApplication` is relevant atm.

One thing I learned was that `postInstall` isn't run automatically with a custom `installPhase`.

**Comment by FRidh** [comment]
> Is there a way to hook into that wrapper, or is the correct way to wrap the wrapper?

From the Nixpkgs manual:

> makeWrapperArgs: A list of strings. Arguments to be passed to makeWrapper, which wraps generated binaries. By default, the arguments to makeWrapper set PATH and PYTHONPATH environment variables before calling the binary. Additional arguments here can allow a developer to set environment variables which will be available when the binary is run. For example, makeWrapperArgs = ["--set FOO BAR" "--set BAZ QUX"].

**Comment by jtojnar** [comment]
The ascii error can be usually fixed by setting `LC_ALL` to UTF-8, see https://github.com/NixOS/nixpkgs/pull/38642#issuecomment-379771342

**Comment by CMCDragonkai** [comment]
Added pull requst at https://github.com/NixOS/nixpkgs/issues/38716. But I'm getting a strange message about `LC_ALL`.

**Comment by CMCDragonkai** [comment]
@jtojnar When I try to do that, I get back this error:

```
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

In the build logs.

**Comment by jtojnar** [comment]
That is just a warning, no idea why is it printed but it should not matter.

**Comment by CMCDragonkai** [comment]
PR is merged.
