### ISSUE TITLE
Package request: ibus-typing-booster

### ISSUE THREAD

**Issue by ninjarai4** [NixOS/nixpkgs#38721]
ibus-typing-booster is an ibus engine for several languages (including english) that allows text prediction and spellchecking, as well as input of unicode symbols and emoji.

https://mike-fabian.github.io/ibus-typing-booster/
https://github.com/mike-fabian/ibus-typing-booster

I've tried to make a derivation myself but I have had no luck getting it to show up in the ibus input method selector. It looks like it was originally a fork of ibus-table, which we already have packaged, so that may be a starting point. Note that text prediction requires some kind of integration with hunspell.

**Comment by Ma27** [comment]
seems quite usable. Just started packaging it, let's see how far I get :)
