### ISSUE TITLE
vim pager prevents the automatic update of  plugins requires typing 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#38748]
## Issue description

I tried adding 3 new vim plugins https://github.com/teto/nixpkgs/tree/vim-gutentags by running the command advised in `pkgs/misc/vim-plugins/default.nix`:
`nix-shell -I nixpkgs=. -p vimPlugins.pluginnames2nix --command "vim-plugin-names-to-nix </dev/null"`
but vim pager keeps asking for input:

```
fetching git://github.com/junegunn/vim-easy-align
-- More --
fetching git://github.com/thinca/vim-ft-diff_fold
-- More --
fetching git://github.com/lambdalisue/vim-gista
-- More --
fetching git://github.com/airblade/vim-gitgutter
-- More --

```
I don't believe this is the expected behavior ? Maybe a flag should be passed when starting vim to ensure pager doesn't wait for input (or use a stock vim).

Not sure who to ping ? /cc @MarcWeber

**Comment by dtzWill** [comment]
I've seen this too, I forget what I did to resolve it.  I believe the "</dev/null" is an attempt to address this, I'm not sure what the story is there (why doesn't it work, if it did previously?).

My shell history contains:

```console
$ nix run -I nixpkgs=$HOME/nixpkgs nixpkgs.vimPlugins.pluginnames2nix -c vim-plugin-names-to-nix </dev/null
```

Which is probably equivalent to what you're doing (err note how I set `nixpkgs=`, that's specific to my checkout location) if the `< /dev/null` is moved outside the quoted argument to `--command`? Might be worth trying that...

It seems to resolve the pager issue but it's still running so I haven't checked if at the end the new metadata is in a working vim instance or not...

**Comment by teto** [comment]
Thanks for confirming I am not crazy :) I haven't investigated yet, but I am curious why would need to run vim at all ? vimscript is not so reliable that we should rely on it. Maybe there is a valid reason but I am dubious.

**Comment by teto** [comment]
@mic92 I rebased the branch on master and ran `nix-shell -I nixpkgs=. -p vimPlugins.pluginnames2nix --command "vim-plugin-names-to-nix +'w result' +qall"` but I still have the problem

```
fetching https://github.com/google/vim-codefmt
fetching https://github.com/google/vim-jsonnet
-- More --
fetching https://github.com/google/vim-maktaba
-- More --
fetching https://github.com/gregsexton/gitv
```
also the ^C won't stop the update.

**Comment by Mic92** [comment]
cc @LnL7

**Comment by jcrben** [comment]
Blame points to https://github.com/NixOS/nixpkgs/commit/7d80c755e8b66ebfded9034a604c4660ee1c25c0

Ran into this too. I actually managed to get thru them all but now I don't know where I'm supposed to find this generated expression - anyone know?

The docs suggest running this command to generate a new expression, but we shouldn't have to fetch all these vim plugins to generate one new expression. Probably the instructions could be updated to say you should delete all but the new one in the meantime?
