### ISSUE TITLE
Kwin segfaults on trunk

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#38752]
## Issue description
kwin segfaults at e4fd05449ede28da9672e4b96021fb2a7a949f3e (current trunk). 

### Steps to reproduce
Running 18.03's plasma5 session and issuing `kwin_x11 --replace` segfaults, or after nixos-rebuilding into recent trunk and starting plasma5 I get no window decorations because failing kwin. Tried the last plasma 5.12.2 commit (unfortunately I didn't note which one exactly because it took so long to build), but it segfaulted as well. 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by Anton-Latukha** [comment]
I had the same behavior on migrating from 17.09 -> 18.03. At every login into 18.03 -> no window decorations.

I looked at logs closely couple of times, and found nothing on the topic.

By thinking - determined that kwin was failing.

After that in 18.03 session I ran `kwin_x11` once. KDE updated data somewhere, and it works smooth from that moment.

P.S.

With KDE I had a bunch of this kinds of problems on Arch Linux over years. So this is a KDE syndrome. Often when KDE updates to significant version - something major (kwin, plasmashell) falls at startup, until you run it once manually, and then system clicks into the stable state.

**Comment by bandresen** [comment]
I have the same issue. Booting into a fully nixos-unstable channel OS and running `kwin_x11` just results in an instant segfault, so for me it didn't do the necessary magic to fix it.

**Comment by lheckemann** [comment]
By "trunk" you mean 18.03?

**Comment by Mounium** [comment]
@lheckemann hydra continuous build system's nixpkgs/trunk "branch"

**Comment by Mounium** [comment]
The problem indeed seems to be non-nixos-specific, it worked with a newly created user , also removing every KDE specific config file fixed it (although strangely not at first try, I have tried to remove (backup) every file starting with a dot in my home directory and it took several trials, I even removed /var and /tmp , before I got it to work finally.) 

Please comment if it doesn't solve it for you, but I think I can close it here.

**Comment by Anton-Latukha** [comment]
As I said. This types of KDE issues are hard to track and bug-report to them.
If someone would have more issues, or have gathered information and syndrome - please go to KDE upstream.

With KDE, around this syndrome there are many different bugs happening literally for years in different manifestations.
