### ISSUE TITLE
sage brings its own curl in PATH

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#38777]
## Issue description
For some time I have had this kind of error
```
teto@jedha> git fetch upstream                                                                                                                                     fatal: unable to access 'https://github.com/nixos/nixpkgs.git/': Protocol "https" not supported or disabled in libcurl
```

I finally decide to investigate
```

teto@jedha> which curl                                                                ~
/home/teto/.nix-profile/bin/curl
teto@jedha> readlink -f $(which curl)                                                 ~
/nix/store/5i230cg5mixkdg6ah422fw783ahb2d27-sage-8.1/bin/curl
```
after running nix-env -e sage, everything works normally. The solution is a long shot but it is to package sage with nix dependencies rather than as a whole blob.

### Steps to reproduce
`nix-env -iA sage`
then tries to use curl on https

## Technical details
nixos-18.03.

**Comment by matthewbauer** [comment]
Could you file an issue with sage? We aren't doing anything from what I can tell that would be installing this.

**Comment by matthewbauer** [comment]
It's just way too many to list. We could go the Arch route[1] & only install what's needed but that seems like more work than it needs to be. Sage should be able to give us an install target.

[1]: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/sagemath#n166

**Comment by teto** [comment]
New sage in nix solves this
