### ISSUE TITLE
VisualVM has font issues

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#38793]
## Issue description

This is nearly identical to the issue to #29151, so maybe a fix similar to  #29634 will fix the issue. (Also, visualvm probably needs a version bump to the 1.4.x line).

### Steps to reproduce

Start `visualvm`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-38-generic, Ubuntu, 16.04.3 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(brandon): `"nixos-18.09pre133621.56fb68dcef4, nixpkgs-18.09pre133809.695897f799a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/brandon/channels/nixpkgs`

**Comment by bbarker** [comment]
I'll note that when I use a downloaded version of visual_vm directly from their site in the same environment, I don't have the issue.

**Comment by FliegendeWurst** [comment]
Looks good to me on NixOS 21.11.
