### ISSUE TITLE
nix-copy-closure invoked by nixops runs out of memory (OOM) on low mem systems

### ISSUE THREAD

**Issue by elitak** [NixOS/nixpkgs#38808]
## Issue description

When I run `nixops deploy`, some of my smaller systems (1GB ram VPSes) fail because the `nix-copy-closure` step runs out of memory. I've monitored the process and it indeed does consume over a GB while working. Adding some swap lets me work around the issue.

I didn't have this problem ever, using the master branch a month or two ago. Why daes `nix-copy-closure` suddenly consume so much memory? Why does it do so without considering maybe backing off or having a setting to limit its allocations. Is this a simple unintended regression? I can't understand why it would even need this much; it should be buffering compressed streams to disk, then unpacking them. That takes almost no memory.

### Steps to reproduce
1. Have low mem system (1GB or less, with no swap)
2. Do a big `nix-copy-closure --use-substitutes` onto it

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.28, NixOS, 18.09.git.50dad060420 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: (master)

**Comment by andrewchambers** [comment]
#1681 related?

**Comment by elitak** [comment]
If `nix-copy-closure` invokes `nix copy` or uses the same code, I suppose it could be a dupe. Again though, this only started happening a month or two ago on master, so that would indicate that something changed recently with `nix-copy-closure` in particular.

**Comment by lheckemann** [comment]
This is probably caused by the upgrade to nix 2.0, and its increased memory consumption on path imports in general (not just those performed by nix copy).

**Comment by lheckemann** [comment]
There is no good reason for this AFAIK. Comments on nixos/nix#1681 reference a couple of commits that should fix this, they're just not in 2.0.

**Comment by nh2** [comment]
I'm using this to boot my VMs initially into 17.09 instead, which has the old nix which doesn't have memory problems: https://github.com/NixOS/nix/issues/1988#issuecomment-394053753

That way I can use nixops again against AWS, at least for the initial deployment (my deployment then itself puts nix 2.0 on it which still has memory issues but at least that one you can patch easily).

Right now I'm still having problems with `error: out of memory`. I tried the nix on commit 54b1c596435b0aaf3a2557652ad4bf74d5756514 which has a couple memory fixes but it still fails when I upload stuff to the target machine via SSH (in this case, with the `libvirt` nixops backend). So maybe only the HTTP substituter code was fixed to stream to disk so far.

**Comment by nh2** [comment]
Here's a nix PR that works for my use case: https://github.com/NixOS/nix/pull/2206

With convenience to try the patch out: https://github.com/NixOS/nix/pull/2206#issuecomment-394130511

**Comment by nh2** [comment]
@elitak Do you still observe issues with nix 2.2?

With the above backport to `2.0.4` I highlight some of the commits that solved this issue for me (but that's concerning the RAM of the _source_ machine I run `nixops` on, not of the target machines I deploy to; for those there are some other fixes in the history and the target machines must also be running nix 2.2).

Related: Asking whether people still observe problems in https://github.com/NixOS/nix/issues/1681#issuecomment-506352361

**Comment by peterhoeg** [comment]
This is no longer the case with 20.03.
