### ISSUE TITLE
Syncserver compilation failed

### ISSUE THREAD

**Issue by Vskilet** [NixOS/nixpkgs#38830]
## Issue description
There is a problem when Nixos compile the serversyncstorage from mozilla. The problem is that syncserver use method .app of WSGIProxy2 but this method isn't available before 0.3

I will start to modified requirements.txt of mozservices and when it will be release, it would be great to change the version in : 
https://github.com/NixOS/nixpkgs/blob/7ebb82e04f17d96313f1d60c748f32a7f7bee9f6/pkgs/top-level/python-packages.nix#L10496

### Steps to reproduce
Enable syncserver in Nixos

You will have this output : 
https://hydra.nixos.org/build/72124841/log 

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131807.489a14add9a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by dotlambda** [comment]
> I will start to modified requirements.txt of mozservices and when it will be release, it would be grate to change the version in :

So you're suggesting to wait until a new version of https://github.com/mozilla-services/mozservices is released?
How will this affect the use of WSGIProxy2 instead of WSGIProxy? The package requiring the latter is https://github.com/mozilla-services/server-syncstorage.

**Comment by dotlambda** [comment]
I still don't understand you. Please try to explain in French or just open a PR as soon as you have a fix.

**Comment by t184256** [comment]
I don't understand him either, but [this](https://github.com/Vskilet/mozservices/commit/7a4649b5a0afa39c12de783c166b59d65391fde6) is probably what he aims to achieve.

**Comment by dotlambda** [comment]
> I don't understand him either, but this is probably what he aims to achieve.

However, it won't be enough because WSGIProxy also needs to be upgraded in https://github.com/mozilla-services/server-syncstorage/blob/149496f09b0ff8ba21cec1d107d2435cb1f584f7/setup.py#L11

@Vskilet Any progress?

**Comment by Vskilet** [comment]
Sorry guys for my bad explanation. 
@t184256 Yes that's it.
@dotlambda Maybe. I'm a beginner in python development. I need to progress a bit

**Comment by nico202** [comment]
bump? 

@Vskilet

**Comment by Vskilet** [comment]
I've not finish to do this ... but I'm on it

**Comment by dotlambda** [comment]
Any updates?

**Comment by Vskilet** [comment]
It's seems that my modifications aren't sufficient ... I don't known what we can do on this.
