### ISSUE TITLE
[18.03]: rustc fails to compile

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#38834]
## Issue description
I noticed this would happen in the git branch of release-18.03 too, but the channel just updated and I thought that issue would be gone.
Unfortunately, a similar issue still lurks that stops the entire system upgrade.
`error: Could not compile ``cssparser``.`
`warning: build failed, waiting for other jobs to finish...`
`error: build failed`

`command did not execute successfully: "/nix/store/y10wy2dns8k33r3nzpgl1z035s16866s-rustc-bootstrap-1.23.0/bin/cargo" "build" "--target" "i686-unknown-linux-gnu" "--release" "--frozen" "--manifest-path" "/tmp/nix-build-rustc-1.24.0.drv-0/rustc-1.24.0-src/src/tools/rustdoc/Cargo.toml"
expected success, got: exit code: 101`

`failed to run: /tmp/nix-build-rustc-1.24.0.drv-0/rustc-1.24.0-src/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:26:08
make: *** [Makefile:22: all] Error 1`
`builder for '/nix/store/0q2379wyyjz29v2i73v3mds34vqmbql1-rustc-1.24.0.drv' failed with exit code 2`
`cannot build derivation '/nix/store/amcslfj73zjzhhj9bcx5869gnxdvwpv0-librsvg-2.42.2.drv': 1 dependencies couldn't be built`
`cannot build derivation '/nix/store/d1dsy55sv7plc4phj7sa2prqqwyk3c9c-gst-plugins-bad-1.12.3.drv': 1 dependencies couldn't be built`
`cannot build derivation '/nix/store/4h3i5fign3xa2jr2x9rhd7n7mry2ynzp-wine-wow-3.3.drv': 1 dependencies couldn't be built`
`cannot build derivation '/nix/store/f2p6icy6drwx5vs5q67vy8jbgb4z058j-system-path.drv': 1 dependencies couldn't be built`
`cannot build derivation '/nix/store/n10f8hhygbjqikmz7z4g7ba10ijzi8yb-nixos-system-okinan-18.03.131950.1c52531bbe9.drv': 1 dependencies couldn't be built`
`error: build of '/nix/store/n10f8hhygbjqikmz7z4g7ba10ijzi8yb-nixos-system-okinan-18.03.131950.1c52531bbe9.drv' failed`

### Steps to reproduce
Attempt a system upgrade with updated channels as usual.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.03.git.40fd490 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Chiiruno** [comment]
Unfortunately it still doesn't compile.

**Comment by xvapx** [comment]
What error does it give?    
I'm using this setup currently in 18.03 and I rebuilt my system yesterday, so it should work.

**Comment by Chiiruno** [comment]
if I remember right, it got to stage 2 and then said something about a panic.
I don't remember if it was before or during the tests, but I don't think it got past the tests.

**Comment by Chiiruno** [comment]
Pinging the maintainers for help, since this (presumably) affects everyone who uses Firefox or WINE.
@madjar @cstrahan @wizeman @globin @wkennington

**Comment by Chiiruno** [comment]
Since the latest channel update, it gets to testing now. (Normal upgrade, not @xvapx workaround)
[Detailed failure log for rustc](https://github.com/NixOS/nixpkgs/files/1913886/rustc_log.txt)

**Comment by Chiiruno** [comment]
And now on a second attempt with the same conditions, it fails on compiling 'kuchiki'?
Here's a short [log](https://github.com/NixOS/nixpkgs/files/1913921/rustc_log.txt).

I really don't understand why rustc isn't compiling on the standard 18.03 stable release.

**Comment by Chiiruno** [comment]
NAILED IT!
I had a custom wine configuration and I assume it was causing the same problem that this pull #38308 was having.
Making sure gstreamer is NOT enabled in the wine override makes everything work again.
A WINE issue should probably be opened up about that.
