### ISSUE TITLE
rtkit fails to build on master

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#38848]
## Issue description

Was checking on how Gnome was doing on [trunk-combined](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents), and saw that the latest build had failed due to rtkit.

Did a bisect between a [good hydra build](https://hydra.nixos.org/eval/1447396) and a [bad](https://hydra.nixos.org/eval/1447501) build, and it looks like e4975973546912ce2d4dbc8469194364f4c2bbe6 is the offending commit (#38581).

Hydra log: https://nix-cache.s3.amazonaws.com/log/1r2rsh093nx2gw0w2r9hc384z8pgmaf0-rtkit-0.11.drv

**Comment by hedning** [comment]
Looks like it's being fixed:  #38847

**Comment by gebner** [comment]
This was just fixed by @aszlig in a7f600b.
