### ISSUE TITLE
Theano with CUDA support broken

### ISSUE THREAD

**Issue by smatting** [NixOS/nixpkgs#38850]
## Issue description

Theano with CUDA support is broken:

- the dependency `pkgs.linuxPackages.nvidia_x11` is missing from `Theano` and `libgpuarray` which results in Missing `libcuda.so` error when importing Theano in Python (see below)
- The wrapped `g++` which is used by Theano at runtime is not including/linking the necessary libraries which results in errors when you try to run a Theano model

### Steps to reproduce

NOTE: To be able to reproduce you need a machine with a NVIDIA GPU. To install the necessary kernel driver on Nixos make sure you have

```
services.xserver.videoDrivers = [ "nvidia" ];
nixpkgs.config.allowUnfree = true;
```
in your `configuration.nix`.

Create a `shell.nix`
```
with import <nixpkgs> {}; (python36.withPackages (ps: [(ps.Theano.override { cudaSupport=true; cudnnSupport = true;})])).env
```
Start a nix-shell from it: `$ nix-shell`

```sh
[nix-shell] $
[nix-shell] $ THEANO_FLAGS='device=cuda,floatX=float32,device=cuda,force_device=True' python3 -c 'import theano'

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/nix/store/vlxn4qd6s99i30p1l4phnvc1kcj7clyc-python3-3.6.4-env/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/nix/store/vlxn4qd6s99i30p1l4phnvc1kcj7clyc-python3-3.6.4-env/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/nix/store/vlxn4qd6s99i30p1l4phnvc1kcj7clyc-python3-3.6.4-env/lib/python3.6/site-packages/theano/gpuarray/__init__.py", line 99, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "libcuda.so": libcuda.so: cannot open shared object file: No such file or directory'
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03pre131740.09bca91e3b5 (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131953.cc95cbed4a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by SomeoneSerge** [comment]
- Build succeeds on nixpkgs-unstable: https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F13vzma3n1ahn2kvfpbgaxz3ra89p09bs-python3.10-Theano-1.0.5.drv?via-job=5db289ae-240a-40c3-95c3-9eb0566ce090
- And on nixos-21.11: https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F7sjwh11r3ig3qsvwqnhvss6vbnp6davi-python3.9-Theano-1.0.5.drv?via-job=8d5ec5c1-0777-48a0-8dff-18df056b0909
- Except for python 3.10: https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fp4wc82jckm5zxvbakqwb2imq16xvcp04-python3.10-Theano-1.0.5.drv?via-job=8d5ec5c1-0777-48a0-8dff-18df056b0909
