### ISSUE TITLE
KDE / KOrganizer Dependencies Missing

### ISSUE THREAD

**Issue by Meizikyn** [NixOS/nixpkgs#38887]
## Issue description
Kontact / KOrganizer / KDE-PIM, when installed, crashes upon use:
i.e. In KOrganizer, adding an event/task/journal, causes a crash. (see **Technical details**)

KOrganizer only works after installing everything from nixos.kdeApplications and nixos.kdeFrameworks 
`nix-env -iA nixos.kdeApplications nixos.kdeFrameworks`

I attempted to compare Debian's dependency graph for KOrganizer and install the equivalently named  packages in NixOS, to no avail. 

### Steps to reproduce
`nano /etc/nixos/configuration.nix`
Add korganizer to systemPackages, use Plasma5 as Desktop-Manager & SDDM as Display-Manager

`nixos-rebuild switch`
`korganizer`

Add new event, type Title, hit OK, crashes with output below

There is not a proper DrKonqi / KCrash report to associate with this, as neither system are considered dependencies of any other package, as far as I can tell, and must be installed manually.

## Technical details
TTY Output:
```
org.kde.pim.kidentitymanagement: IdentityManager: There was no default identity. Marking first one as default.
kf5.kservice.services: KServiceTypeTrader: serviceType "KOrganizer/Part" not found
org.kde.pim.kidentitymanagement: IdentityManager: There was no default identity. Marking first one as default.
org.kde.pim.incidenceeditor: free slot calculation: invalid range. range(  0 ) / mSlotResolutionSeconds( 900 ) =  0
terminate called after throwing an instance of 'Akonadi::PayloadException'
  what():  Akonadi::PayloadException: Wrong payload type (requested: sp(0)<QByteArray>; present: sp(2)<KCalCore::Incidence*>
org.kde.pim.akonadiserver: Protocol exception: Socket disconnected
```

`nix-shell -p nix-info --run "nix-info -m"` Results:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131802.4b4bbce199d (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(shor): `""`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Mic92** [comment]
After a long debugging session I found out that `kdeApplications.akonadi-mime` was missing.
In my case it was not only required to install it into my own profile (`~/.nix-profile`) but also in `environment.systemPackages` since it looked into `/run/current-system/sw/share/mime/types` before it checks the other directory.

**Comment by johnalotoski** [comment]
I confirm that following Mic92's suggestion to install kdeApplication.akonadi-mime in the environment.systemPackages fixes the Korganizer crashing issue when making calendar entries on my system too (18.03).  Doing so adds the following entries to /run/current-system/sw/share/mime/types:

application/x-vnd.akonadi.calendar.event
application/x-vnd.akonadi.calendar.freebusy
application/x-vnd.akonadi.calendar.journal
application/x-vnd.akonadi.calendar.todo
application/x-vnd.akonadi.collection.virtual
application/x-vnd.kde.contactgroup

Thanks for taking the time to figure out a solution Mic92!

John

**Comment by Meizikyn** [comment]
Still receiving this error message after above suggestion:
```
terminate called after throwing an instance of 'Akonadi::PayloadException'
  what():  Akonadi::PayloadException: Wrong payload type (requested: sp(0)<QByteArray>; present: sp(2)<KCalCore::Incidence*>
```

**Comment by pjones** [comment]
@ttuegel @vandenoever There doesn't seem to be any documentation on how to properly install KDE applications.  Would it make sense to have meta-packages like `kontact` that installed all necessary dependencies?

**Comment by Narice** [comment]
not stale

**Comment by marius851000** [comment]
I had the same issue. After having spend a bit too much time, I was able to isolate the issue.

(if this help someone: setting ``QT_LOGGING_RULES=org.kde.pim.akonadicore=true`` logged many useful information)

The issue is that kontact wasn't able to find the serializer for the agenda (in my case, todo element), more exactly it was missing the serializer for ``application/x-vnd.akonadi.calendar.todo``. This serializer seems to be present in ``akonadi-calendar``, so I added it to the system package (like the @Mic92 change), and it worked. It should be missing as a build input somewhere.

**Comment by alexdewar** [comment]
@ttuegel @vandenoever @nyanloutre 

Hi! Any ideas about this? This issue is biting me too. It seems like it *could* just be a simple case of missing dependencies but actually figuring out what those are is proving rather difficult...

**Comment by Obikawa** [comment]
This is frustrating. I just want to use the KDE PIM suite in peace.

```
$ kmail
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
We have an error during reading password  "Entry not found"
org.kde.pim.akonadicore: Job error:  "" for collection: QVector()
org.kde.pim.akonadicore: Job error:  "" for collection: QVector()
org.kde.pim.messagelist: Failed to load tags  ""
org.kde.pim.mailcommon: failed to retrieve tags  ""
```

Does the above contain any hint explaining why Akonadi fails to run properly?

**Comment by Zahrun** [comment]
As mentionned in https://discourse.nixos.org/t/kaddressbook-kontact-akonadi-cannot-add-address-book/25227 I am having issues with kontact and kaddressbook. 
In the first post @Meizikyn states that installing nixos.kdeApplications and nixos.kdeFrameworks helped, but in NixOS 22.11 I am not finding these. Can anyone help?

**Comment by SuperSandro2000** [comment]
Merging this into #266565
