### ISSUE TITLE
interfaceMonitor usability

### ISSUE THREAD

**Issue by edwtjo** [NixOS/nixpkgs#3891]
So networking.interfaceMonitor.enable breaks nixops activations since ifplugd fails, try enabling it and running nixos-rebuild.

I think the option networking.interfaceMonitor is confusing. It isn't clear that its primary usage is for running a shell script. We have useDHCP which works the same way, since dhcpcd reinitializes itself on iface changes. I don't know about static configurations, i.e. if ifplugd helps here(someone else might chime in).

I think it should be marked for removal or deprecation. Otherwise the ifplugd service needs to be updated.

**Comment by jagajaga** [comment]
Do we still have this problem?

**Comment by dezgeg** [comment]
Quite unlikely as it got removed in 6bd0c3fe9de1572f06ae0b44b6f0c96318246bd1 :P.

**Comment by matthiasbeyer** [comment]
Clearly something we should put into the release notes!
