### ISSUE TITLE
kde-gtk-config: GLib-GIO-ERROR **: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by ysndr** [NixOS/nixpkgs#38919]
## Issue description
when attempting to save gtk styles in KDE Settings module `kde-gtk-config` systemsettings will crash with following error:
```
Apr 13 18:28:11 nixos xsession[2505]: (systemsettings5:3557): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Apr 13 18:28:11 nixos kernel: traps: systemsettings5[3557] trap int3 ip:7f5ef02bed91 sp:7fffe52c4320 error:0 in libglib-2.0.so.0.5400.3[7f5ef026f000+112000]
```

what is interesting is that most settings will actually be saved while others (such as prefering gtk3 styles) wont.

### Steps to reproduce
1. open `systemsettings5 > Application Style > GNOME Application Style (GTK)` 
2. make changes 
3. hit apply
4. no point 4

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131954.2569e482904 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03, nixos-unstable-18.09pre133640.ea145b68a01"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
If you run application trying to access `GSettings`, it needs to have the necessary schemas in `XDG_DATA_DIRS`. See https://github.com/NixOS/nixpkgs/issues/16285#issuecomment-370205727 and the commit below that for more info.

**Comment by ysndr** [comment]
Thanks for the info

So adding wrapGAppsHook to native build inputs of kde-gtk-config should be enough?

**Comment by jtojnar** [comment]
If the package contains something that can be wrapped, sure.

**Comment by ttuegel** [comment]
That package does not contain anything which can be wrapped. We would have to include `kde-gtk-config` into `systemsettings` and then wrap that so that everyone using KDE pulls in GTK. Or ask whoever wrote `wrapGAppsHook` to make it act differently.

**Comment by jtojnar** [comment]
@ttuegel What do you mean by `wrapGAppsHook` acting differently? How?
