### ISSUE TITLE
latte-dock: customizations are not preserved after process ends

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#38938]
## Issue description
If I apply a customization(pin an app , etc) to latte-dock and then kill the program,
the customization appears to not be preserved when starting it again.
Making this application unusable.

### Steps to reproduce
![latte](https://user-images.githubusercontent.com/28888242/38769373-ffed9cfe-3fcf-11e8-9740-ed3671c3b795.gif)
1. start latte-dock
2. pin an app (it pins while running of course)
3. kill latte-dock
4. start latte-dock
4. app isn't pinned :(

This applies for any other setting also.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by psifidotos** [comment]
has been reported here: https://github.com/psifidotos/Latte-Dock/issues/980

as a workaround until the fix lands in master version you can do the following:

1. close Latte
2. change file permissions for all layouts in `~/.config/latte` and make them writeable from the user.
3. start Latte

**Comment by jnoortheen** [comment]
the issue is still there in recent versions 0.9.11

**Comment by psifidotos** [comment]
> the issue is still there in recent versions 0.9.11

check out that your latte layout files are not set to read-only in ~/.config/latte directory

**Comment by jnoortheen** [comment]
Yes that makes it working.

**Comment by Zahrun** [comment]
Not an issue anymore in latte-dock 0.10.77 (unstable 2023-03-31)

**Comment by Plarpoon** [comment]
I hope this won't count since it's so fresh but I have just done a fresh installation of NixOS and I am on the same exact version as @Zahrun (latte-dock 0.10.77 (unstable 2023-03-31)) but the problem is still present.

I could fix it exclusively by making all of my latte profiles readable as described in the workaround before. But the issue is still present unfortunately..

**Comment by Plarpoon** [comment]
Let me know if the issue can be re-opened otherwise I am more than willing to just create a new one instead, whatever bothers you the least 😃
