### ISSUE TITLE
osquery fails to build

### ISSUE THREAD

**Issue by vitiral** [NixOS/nixpkgs#38940]
## Issue description
I cannot install osquery on my system.

[logfile](http://pasted.co/851d2d2d)

### Steps to reproduce
- add `osquery` package to `environment.systemPackages` on nixos
- `nixos-rebuild build`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131807.489a14add9a, nixpkgs-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by Ma27** [comment]
ok, I came quite fast: https://github.com/Ma27/nixpkgs/commit/718d46988aaea51307665248533f2861f760918a

Currently failing at 88% as `ld` doesn't fine `daemonclient` and `lvm-internal`. Will investigate how to solve this %)

**Comment by Ma27** [comment]
@vitiral @cstrahan this is how far I got: https://github.com/Ma27/nixpkgs/tree/fix-osquery

Unfortunately the resulting binary fails with the following error (I don't know to fix):

```
ERROR: something wrong with flag 'flagfile' in file '/build/source/src/gflags.cc'.  One possibility: file '/build/source/src/gflags.cc' is being linked both statically and dynamically into this executable.
```
