### ISSUE TITLE
Update Rebar3 package

### ISSUE THREAD

**Issue by x80486** [NixOS/nixpkgs#38966]
I would be nice to bump/update `Rebar3`. We currently have version `3.4.3` (checked on `Apr 15, 2018`):

```shell
[gorre@uplink ~]$ nix-env -qa ".*rebar.*"
rebar-2.5.1
rebar3-3.4.3
rebar3-3.4.3
```

...and the latest release version (`3.5.0`) was in `Dec 22, 2017`.

## Technical details

```shell
[gorre@uplink ~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (2.01 MiB download, 10.61 MiB unpacked):
  /nix/store/277x7fwjlr0mfdbdhb0ri3d8yhdk94nq-bash-4.4-p19
  /nix/store/4x22cs2ldrss83q3cdw4p89i7kb08k6n-bash-4.4-p19-dev
  /nix/store/6cnl6afcbdrg8hn80192yg211il3ixy0-bash-4.4-p19-doc
  /nix/store/6kz2vbh98s2r1pfshidkzhiy2s2qdw0a-stdenv-linux
  /nix/store/a2j35nc1m40kz0dwl76qf120lagvkcgr-readline-7.0p3
  /nix/store/afz06vlnhc6il6f4jd82c8hs9g7jq8gn-bash-4.4-p19-man
  /nix/store/d6p7343j9ywfynr23998nkqndq0fc98a-bash-4.4-p19-info
  /nix/store/gxnh7h184sbgm571242yscgkw4wy8wvx-bash-4.4-p19-dev
  /nix/store/ks166vgkssxchp5dn9hzd5njaggw4nfl-bash-4.4-p19-doc
  /nix/store/nhfgv0xxi9shl5lvl9jaf11vmm9zkv42-nix-info
  /nix/store/pa465sfqgqgnicj1ishd7n2sqapqjsq7-bash-4.4-p19-man
  /nix/store/pf6afvy0mymgmpkjc5gnk3l5ppz99mv3-bash-4.4-p19-info
copying path '/nix/store/6cnl6afcbdrg8hn80192yg211il3ixy0-bash-4.4-p19-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/4x22cs2ldrss83q3cdw4p89i7kb08k6n-bash-4.4-p19-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ks166vgkssxchp5dn9hzd5njaggw4nfl-bash-4.4-p19-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/d6p7343j9ywfynr23998nkqndq0fc98a-bash-4.4-p19-info' from 'https://cache.nixos.org'...
copying path '/nix/store/pf6afvy0mymgmpkjc5gnk3l5ppz99mv3-bash-4.4-p19-info' from 'https://cache.nixos.org'...
copying path '/nix/store/afz06vlnhc6il6f4jd82c8hs9g7jq8gn-bash-4.4-p19-man' from 'https://cache.nixos.org'...
copying path '/nix/store/pa465sfqgqgnicj1ishd7n2sqapqjsq7-bash-4.4-p19-man' from 'https://cache.nixos.org'...
copying path '/nix/store/nhfgv0xxi9shl5lvl9jaf11vmm9zkv42-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/a2j35nc1m40kz0dwl76qf120lagvkcgr-readline-7.0p3' from 'https://cache.nixos.org'...
copying path '/nix/store/6kz2vbh98s2r1pfshidkzhiy2s2qdw0a-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/277x7fwjlr0mfdbdhb0ri3d8yhdk94nq-bash-4.4-p19' from 'https://cache.nixos.org'...
copying path '/nix/store/gxnh7h184sbgm571242yscgkw4wy8wvx-bash-4.4-p19-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.15-1-ARCH, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(gorre): `"nixpkgs-18.09pre134800.e42ae4e586c"`
 - nixpkgs: `/home/gorre/.nix-defexpr/channels/nixpkgs`
```

**PS:** I didn't know how do we usually "ask" for package updates, so I file an issue O:)

**Comment by jtojnar** [comment]
cc maintainer @gleber

**Comment by tazjin** [comment]
I've started taking a look at this. As a test I've only updated `rebar3-open` (the version that does not apply the hermeticity patch) and that is a pretty straightforward update.

Blockers currently seem to be:

1. The package index in the `erlang-nix` repository needs to be updated (see [here](https://github.com/erlang-nix/hex-pm-registry-snapshots) and in the file `hex-registry-snapshot.nix` in nixpkgs).

2. The hermeticity patch needs to be updated for the newest rebar3 version.

I'm going to take a look at how involved 2. is going to be, but the patch seems to be small and relatively simple. As for 1., it seems that only @gleber has the rights to update that repository so we'd need him to do it and/or set up an alternative mirror of the registry index.

Maybe there is even a better place to host this file?

**Comment by gleber** [comment]
@tazjin I am happy to assist with reviews, both here and in `erlang-nix` org. If someone is passionate about Erlang support, proves this via work executed in that direction and has good community, I am more than happy to give all the necessary right to take this over.

**Comment by gleber** [comment]
@tazjin, good point. @ericbmerritt is a second person in that org: https://github.com/orgs/erlang-nix/people/ericbmerritt

Maybe @ankhers would be interested to join that org and improve the bus factor?

**Comment by tazjin** [comment]
@gleber Ah, his membership isn't public - so to non-members of the org it looks like you are the only member :-)

**Comment by ankhers** [comment]
I would be more than happy to join and help out where I can.

**Comment by gleber** [comment]
@ankhers Invited!
