### ISSUE TITLE
plasma-workspace: pinned apps to taskmanager, when launched, have an additional launcher

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#38987]
## Issue description
I discovered this underlying behaviour whilst triaging [latte-dock](https://github.com/psifidotos/Latte-Dock/issues/993) where this is really apparent and annoying.

I'm going to make use of a screencast because it's more evident this way.

![peek 2018-04-16 00-54](https://user-images.githubusercontent.com/28888242/38790686-da82eff4-4110-11e8-913d-5c469f17aa6e.gif)

### Steps to reproduce
1. dnd an app from launcher to taskmanager or right click in launcher and select `pin to task manager`
2. :rocket:  it
3. See two launchers

Just to be very clear, this is a pinned app in the task manager. Not to the panel.
A pinned launcher to the panel would never disappear when launched.

I very suspect that this is only nixos specific because I haven't seen this anywhere else.

## Technical details
- system: `"x86_64-linux"`
- host os: `Linux 4.14.34, NixOS, 18.03.132006.6ba9b9c9fa2 (Impala)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.0`
- channels(root): `"nixos-18.03.132006.6ba9b9c9fa2"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixpkgs/pull/40893

**Comment by bkchr** [comment]
Will Plasma 5.13 solve your problem?

**Comment by worldofpeace** [comment]
@bkchr 
I would like to hope so :grin: 
Most likely not, I think this might need some patchwork from us to upstream.

**Comment by bkchr** [comment]
I think I solved your problem. Open Dolphin first, then in task manager, right click and choose "pin". Close dolphin, reopen with your pinned dolphin and it is not duplicated anymore.

**Comment by worldofpeace** [comment]
Yep, that is a work around I found while triaging latte-dock also.
Imagine how riddiclous that get's when you have lot's of apps to pin.

Obviously I could reproduce this with latte-dock which uses the same things as the taskmanager
and I noticed this:

If i dnd into the taskmanager this would be in that apps config
```
[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true
...
launchers59=file:///run/current-system/sw/share/applications/org.kde.ark.desktop
```

But if I did exactly what you suggested this would be in it:
```
[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true
...
launchers59=applications:org.kde.ark.desktop
```

**Comment by bkchr** [comment]
Where are this configuration files stored?

**Comment by worldofpeace** [comment]
Um these were specific to latte-dock, at ~/.config/latte/${something}

**Comment by Artturin** [comment]
Probably fixed?
