### ISSUE TITLE
libnatspec.x86_64-darwin can't find libiconv

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#39017]
With recent changes to libiconv, libnatspec should be able to find libiconv. Something is going wrong in the setup-hook, causing this build failure:

https://hydra.nixos.org/build/72732451/nixlog/1

/cc @Ericson2314

**Comment by Ericson2314** [comment]
Hmm it is a dependency. Maybe it's a borked configure script?

**Comment by matthewbauer** [comment]
Maybe... does it look like it's using a custom libtool?

```
/nix/store/r8bx3qf1bpncb14i9gzma4vr089pc3pv-bash-4.4-p19/bin/bash ../libtool  --tag=CC   --mode=link clang -I../lib -pedantic -Wall -funsigned-char   -o test_get_charset test_get_charset-test_get_charset.o ../lib/libnatspec.la 
```

**Comment by Ericson2314** [comment]
Nice sleuthing!
