### ISSUE TITLE
Eclipse: how to pass -javaagent

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#39015]
## Issue description
To add support for the [lombok](https://projectlombok.org/) service in Eclipse, I would like to be able to pass `-javaagent:lombok.jar` to the Eclipse ini file.

I don't believe this is possible with the provided `eclipses.eclipseWithPlugins` function.

I have been trying the following but it is obviously wrong:
```
    (eclipses.eclipseWithPlugins {
       eclipse = eclipses.eclipse-sdk-47;
       jvmArgs = [ "-javaagent:${pkgs.lombok.out}/share/java/lombok.jar" ];
       plugins = with eclipses.plugins; [ jdt yedit testng ];
    })
```
Thanks for your help.

**Comment by rycee** [comment]
I've been using Lombok in this way for quite a while. It is important to note that Lombok is quite particular about versions so it is very important that you use the same version that is used by Maven (or whatever build system you have). In my case I couldn't use the Nixpkgs version and instead use a specific version from inside my ~/.m2 directory though:

```
jvmArgs = [ "-javaagent:/home/rah/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar" ];
```

Which specific problem are you experiencing?

**Comment by PierreR** [comment]
It just does nothing. It seems to ignore completely the jvmArgs. After reading the author's comment from this [issue](https://github.com/rzwitserloot/lombok/issues/1650), I thought that using `jvmArgs` would not work.

**Comment by rycee** [comment]
Odd, I just tried it for a user whose Eclipse never has had Lombok installed. I added
```
jvmArgs = [ "-javaagent:${pkgs.lombok}/share/java/lombok.jar" ];
```
and it seems to have installed OK as shown in the About dialog box:

![2018-04-20-185909_886x496_scrot](https://user-images.githubusercontent.com/798147/39063998-1ddb5cd6-44cd-11e8-9569-7224e11f3d6c.png)

Indeed, I have since earlier added support for Lombok in the eclipse Home Manager module that uses [this exact method](https://github.com/rycee/home-manager/blob/9141d11a7d8f2293d52aa6eed840afe18b998a3e/modules/programs/eclipse.nix#L48-L49).

**Comment by PierreR** [comment]
@rycee I am not using `home-manager` but I might be in a short future. If it works there that's yet another incentive to do so. I have been willing to give it a shot for a long time but never had the time to investigate further.

**Comment by rycee** [comment]
In this case home manager doesn't do very much, the eclipse module is a very thin wrapper around the `eclipseWithPlugins` function :-)

**Comment by PierreR** [comment]
@rycee Oh jeez I am so sorry. I have looking for an icon all along whereas I need to scroll and check for the last line ... It does work !

Thanks so much for your patience and support !

**Comment by rycee** [comment]
No worries. Glad it works :-)
