### ISSUE TITLE
nixos-install fails with grub1

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#39025]
## Issue description

`nixos-install` fails with grub1, see [failed test on hydra](https://hydra.nixos.org/build/72901730), which is locally reproducible. The installation process looks ok until `grub-install` fails with multiple errors.

(not sure why we still support grub1, but it should work as long as we do...) 

### Steps to reproduce

`nix-build '<nixpkgs/nixos/tests/installer.nix>' -A grub1`

## Technical details

nixos `18.03.132008.ad771371fb2` , fails on master as well.

**Comment by dezgeg** [comment]
I think @edolstra said at some point that grub1 is only really needed for some EC2 images, is that still the case?

**Comment by xeji** [comment]
fixed in #46769
