### ISSUE TITLE
Remove legacy cross compilation stuff

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#39087]
## Issue description

A goal of mine for 18.09 is to get rid of some legacy cross compilation stuff. We can now use "crossSystem" to accomplish the same thing.

- [x] pkgs/development/compilers/arm-frc-linux-gnueabi-gcc/
- [ ] pkgs/development/misc/avr/
- [ ] pkgs/development/compiler/gcc-arm-embedded/
- [ ] pkgs/development/compilers/mentor/

We want to make sure we have easy alternatives for the above. This might include providing aliases if they are needed. Also we might want to have Hydra build toolchains for AVR and ARM embedded.

**Comment by bjornfor** [comment]
I added another entry: pkgs/development/compilers/mentor/. (Currently holds two old ARM toolchains.)
