### ISSUE TITLE
shutter: can't export screenshots

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#39103]
## Issue description
shutter can't export screenshots to web services such as imgur, the matching plugins take forver to load.

### Steps to reproduce
Take a screenshot, click` screenshot-> export` and try uploading image to an online service

/cc @bjornfor

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.12, NixOS, 18.09.git.f92f8aa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by bjornfor** [comment]
This might be due to 

```
$ shutter
...
### take screenshot
### select screenshot -> export and select a provider
*** unhandled exception in callback:
***   Can't locate Encode/Locale.pm in @INC (you may need to install the Encode::Locale module) (@INC contains: /nix/store/...
```

I don't know what the "matching plugins" are. Loading plugins at startup seems slow, but it's always been like that for me.

**Comment by teto** [comment]
I recently discovered shutter, (usually uses scrot + shell script) it is nice but it's not a huge concern, just thought I would let you know in case it is an easy fix.

**Comment by bjornfor** [comment]
I made some progress: 8a5b1425452e94db51398d0e31ec96a6e1817538. I think it's an upstream problem now (web APIs of upload providers have changed?). I don't plan to work anymore on this.

**Comment by teto** [comment]
thanks for trying. np

**Comment by chreekat** [comment]
>  Loading plugins at startup seems slow, but it's always been like that for me.

This was not typical behavior when I used shutter on Ubuntu. Do you know why it happens every time on NixOS?

**Comment by chreekat** [comment]
I've looked at it a little bit. The fact that the message is "updating plugin info" makes me wonder if it's trying to modify some file in the Nix store. Annoyingly—or perhaps happily—it stopped happening for me, so now I can't look into it any further. :P

**Comment by teto** [comment]
still annoying and valid but I dont care anymore

**Comment by chreekat** [comment]
Same, I use flameshot nowadays anyway.
