### ISSUE TITLE
[18.03]: rustc build broken on i686

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#39110]
## Issue description

`rustc` build appears to be broken on i686, resulting in a number of [hydra failures](https://hydra.nixos.org/eval/1449436). For example, look at `nixos.closures.xfce.i686-linux` or `nixos.tests.firefox.i686-linux` in linked hydra eval. 

## Technical details

`nixos-18.03.132050.0a97eb36be8`

--

/cc @Mic92

**Comment by Mic92** [comment]
cc @vcunat how much i686 do we still support?

**Comment by Mic92** [comment]
It runs out of memory while running tests. I will disable tests for rustc i686 as well.

**Comment by xeji** [comment]
Independent of this issue, we should have some sort of "official" i686 support policy and mark all unsupported packages as broken to get rid of those hydra jobs.

**Comment by vcunat** [comment]
Maybe it was just a transient problem.

Officially we currently don't "guarantee" i686 support (except for packages like wine).  It's more like there's not enough interest to keep it in a good shape, but certainly feel free to improve on that (anyone).  There are a few open issues, e.g. https://github.com/NixOS/nixpkgs/issues/36947
