### ISSUE TITLE
nix install script errors on high sierra 10.13.4 (17E199)

### ISSUE THREAD

**Issue by efx** [NixOS/nixpkgs#39115]
## Issue description
I can file this in https://github.com/NixOS/nix if more appropriate.
A recent high sierra update clobbered my nix install. I think this could be because it reset the system shell configurations. So I went to reinstall nix following the websites instruction.
The installation failed at the following step:
```
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo HOME=/var/root /nix/store/xmi4fylvx4qc79ji9v5q3zfy9vfdy4sv-nix-2.0/bin/nix-env -i /nix/store/d2ayiz3l18l06w67jmc4lgz8b0v1dls4-nss-cacert-3.34.1

to installing a bootstrapping SSL certificate just for Nix in to the default Profile

installing 'nss-cacert-3.34.1'
building '/nix/store/prp85yg27iy3xp7yrlnijzajwinmwhal-user-environment.drv'...
created 9 symlinks in user environment

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo HOME=/var/root NIX_SSL_CERT_FILE=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /nix/store/xmi4fylvx4qc79ji9v5q3zfy9vfdy4sv-nix-2.0/bin/nix-channel --update nixpkgs

to update the default channel in the default profile

unpacking channels...
dyld: Library not loaded: /nix/store/mzn9nskhyf6nn5nacwp851418x3b1z57-Libsystem-osx-10.11.6/lib/system/libsystem_c.dylib
  Referenced from: /nix/store/mzn9nskhyf6nn5nacwp851418x3b1z57-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: no suitable image found.  Did find:
        /nix/store/mzn9nskhyf6nn5nacwp851418x3b1z57-Libsystem-osx-10.11.6/lib/system/libsystem_c.dylib: open() failed with errno=4
        /nix/store/mzn9nskhyf6nn5nacwp851418x3b1z57-Libsystem-osx-10.11.6/lib/system/libsystem_c.dylib: stat() failed with errno=1
        /nix/store/mzn9nskhyf6nn5nacwp851418x3b1z57-Libsystem-osx-10.11.6/lib/system/libsystem_c.dylib: open() failed with errno=4
/nix/store/sgcz3d63ps5z3q80b4df8rjihvc1aawg-unpack-channel.sh: line 14: 45666 Abort trap: 6           mv * $out/$channelName
builder for '/nix/store/g8275jr7p7afq9j31g4h8s1h9743gzz7-nixpkgs-18.09pre137305.d91caac6c3e.drv' failed with exit code 134
error: build of '/nix/store/g8275jr7p7afq9j31g4h8s1h9743gzz7-nixpkgs-18.09pre137305.d91caac6c3e.drv' failed
error: program '/nix/store/xmi4fylvx4qc79ji9v5q3zfy9vfdy4sv-nix-2.0/bin/nix-env' failed with exit code 100
/var/folders/_3/wvs7d91d2ss55__qs6y6cbr80000gp/T/nix-binary-tarball-unpack.XXXXXXXXXX.UQyoILT4/unpack/nix-2.0-x86_64-darwin/install-darwin-multi-user: line 241: /bin/rm: Permission denied
/dev/fd/63: line 16: /bin/rm: Permission denied
bash-3.2$ nix-symlink-hook: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
```

### Steps to reproduce
1. have an existing nix install on macOS
1. follow the remove installation steps
1. run the nix install script `bash <(curl https://nixos.org/nix/install)`

## Technical details
nix is uninstalled atm so don't have nix-info stuff.

**Comment by matthewbauer** [comment]
Could you report the result of this command:

```
csrutil status
```

Thanks

**Comment by efx** [comment]
```
$ csrutil status
System Integrity Protection status: enabled.
```

**Comment by matthewbauer** [comment]
Also output of these two commands:

```
$ umask
$ spctl --status
```

We've had a few reports of issues on macOS installation but they can be hard to reproduce. Sometimes things like Gatekeeper will interfere in running unsigned binaries. This can be especially true with corporate Macs that have "Configuration Profiles" from JAMF. Eventually I want to start codesigning the installer (if it's possible to codesign a set of shell scripts).

https://github.com/NixOS/nix/issues/1980
https://github.com/NixOS/nix/issues/1727
https://github.com/NixOS/nix/issues/1684
https://github.com/NixOS/nix/issues/1582

**Comment by efx** [comment]
Thanks for looking into this @matthewbauer! We do use JAMF so I'd suspect that.
```
$ umask
022
$ spctl --status
assessments enabled
```

**Comment by matthewbauer** [comment]
Yep JAMF seems to be the biggest culprit of these things. There's probably things we can do to detect/workaround this though. Do similar installers like Homebrew, Chef, or Oh-my-zsh work out of the box?

It might actually have to do with the way we bundle our own libSystem for reproducibility reasons. Perhaps there is a way to avoid this?

**Comment by efx** [comment]
So homebrew has been working. It was previously installed to my machine:
```
 brew --version
Homebrew 1.6.1
Homebrew/homebrew-core (git revision fe1bd; last commit 2018-04-18)
```
Modifying system level paths with SIP seems like an uphill battle. I wonder if there could be a way to run the macOS installer for single users and install it entirely within their home directory? This could be an inordinate amount of work so am not sure if it is worth taking on. I like installers that operate entirely within the home directory given my working mac environment. I am quite restricted as to system level modifications, so keeping things isolated to my home directory makes installing packages easier.

**Comment by efx** [comment]
I confirmed that uninstalling JAMF and clearing system level nix installation artifacts let us run the installer successfully. Perhaps we should just exit the installer if JAMF is detected.

**Comment by matthewbauer** [comment]
It might good to at least warn when JAMF is installed. Of course ideally we want Nix to work with JAMF without any modifications.

**Comment by efx** [comment]
Definitely. Our administrator reinstalled JAMF and thus far I am using nix successfully.

**Comment by Ekleog** [comment]
Reading https://github.com/NixOS/nix/issues/1582, it sounds like this should be fixed now. Can anyone still reproduce?

**Comment by efx** [comment]
I'll close and reopen if I need to reproduce. I have a working installation so this is not a priority for me.
