### ISSUE TITLE
jbake version bump failed

### ISSUE THREAD

**Issue by moaxcp** [NixOS/nixpkgs#39132]
When I run jbake from unstable the executable exits with an error message. It prints

```
0 + n1 nixos # jbake

ERROR: JAVA_HOME is set to an invalid directory: /nix/store/psp8fy8mj9ldj93a795ldpzx9ryy09p2-oraclejdk-8u161

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

I believe the script now needs JAVA_HOME set instead of replacing use of the java command.

https://github.com/NixOS/nixpkgs/blob/2a258e6cef19ab352d8a9d6df9344a4fcd7eafca/pkgs/development/tools/jbake/default.nix#L15

**Comment by pSub** [comment]
Seems like you have already fixed it in 4115237312597b1ae944d24670a028ee6c6ccfef.
