### ISSUE TITLE
/nix/store/.links is 29G

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#39135]
## Issue description
```
du -h /nix/store/.links
29G	/nix/store/.links
```

What is this dir for?
Why is it so big?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.0, NixOS, 18.09.git.b6a6f26 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(bart): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by 7c6f434c** [comment]
It is used for `nix-store --optimise`. It contains content-hash-named hardlinks to all the files in the store for deduplication purposes. It uses approximately as much space as the entire store, but these are hardlniks to things that are in store anyway, so it is the same space, not additional space.

**Comment by magnetophon** [comment]
Thanks.
I ran ``nix-store --optimise`` and gained 12G.
.links is now 46G.
