### ISSUE TITLE
[requeste] gede: 2.0.4 -> latest (2.6.x?)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#39162]
## Issue description

Our gede seems rather old--can someone look at updating it? :grin:

Currently, latest is here:

http://acidron.com/gede/pmwiki.php?n=Blogge.2018-02-13-gede-2-6-1-0lambda15nd-2-4-3-0lambda15eleased

Probably makes sense to move to qt5 in the process, assuming that's no trouble.

**Comment by xeji** [comment]
The bump was trivial enough, also fixed a missing ctags dependency. But upstream explicitly say they want qt4, so I didn't try to move to qt5.

**Comment by jtojnar** [comment]
I think the download page is just outdated – the home page mentions QT5.

**Comment by xeji** [comment]
Let's get the bump merged first and look at qt5 later.

**Comment by dtzWill** [comment]
Agreed! (and that can happen as quickly as someone decides they want to look into it :+1:)

**Comment by xeji** [comment]
Already working on qt5. Stay tuned.
