### ISSUE TITLE
Cross-compiling LLVM fails because llvm-tblgen must be run.

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#39170]
## Issue description

Cross-compiling LLVM for aarch64 like so(with nixpkgs HEAD):

```
$ nix-build -E "with import ./default.nix {crossSystem = (import ./lib).systems.examples.aarch64-multiplatform;}; llvmPackages.llvm"
```

Eventually fails with

```
/nix/store/xn5gv3lpfy91yvfy9b0i7klfcxh9xskz-bash-4.4-p19/bin/bash: ../../../bin/llvm-tblgen: cannot execute binary file: Exec format error
```

Seems we need to use the host's`llvm-tblgen` when cross compiling.

### Steps to reproduce

`nix-build -E "with import ./default.nix {crossSystem = (import ./lib).systems.examples.aarch64-multiplatform;}; llvmPackages.llvm"`

**Comment by matthewbauer** [comment]
Related: #36867

**Comment by TravisWhitaker** [comment]
Also related: #33353

Got here by trying to cross-compile GHC.

**Comment by dtzWill** [comment]
Bah, yes this is a pain. cc @Ericson2314 @bgamari etc.

I'll check back later but for now consider searching the PR/issue history-- this has been discussed and a few workarounds of varying quality have been proposed along the way.

Maybe this will be the final motivation to polish one of those efforts and merge it! :)

One example, IIRC, can be found in some of the earlier "versions"  of my big musl PR.  LMK if you have questions or can't find what I mean.  Hopefully I'm remembering correctly :D.

https://github.com/NixOS/nixpkgs/pull/34645

**Comment by dtzWill** [comment]
Sorry for the delay.

I know I've approached this a few ways-- here's one that might have useful bits (this branch was never meant to be public, but just pushed in case useful... apologies for hackery and such O:))

https://github.com/dtzWill/nixpkgs/commits/experimental/cross-llvm

Relevant to this issue in particular, it tries to avoid having to do full builds of LLVM on the buildPlatform just to get the tables generated for the LLVM you care about-- in particular, introduces special derivations that build **just** tablegen.  I also added a dummy `llvm-config`-- which actually I think was explored in Nixpkgs at some point? Not sure.

Anyway hope this helps, LMK if you have any questions.

**Comment by Ericson2314** [comment]
If we can do that branch simultaneous with https://github.com/NixOS/nixpkgs/issues/36867 (build == host == target) LLVM, I'll be very very happy :).

**Comment by TravisWhitaker** [comment]
I ended up getting around this by just passing in the host's LLVM and depending on it when `buildPlatform != targetPlatform`.

@dtzWill is it really that bad to depend on the host's complete LLVM? It'll typically be in the binary cache, right?

**Comment by dtzWill** [comment]
It seems better than not working at all, that's for sure! :)

**Comment by TravisWhitaker** [comment]
This works for me: https://github.com/TravisWhitaker/nixpkgs/commit/50a647ebaee9cb3f1f94a309b042b3282b56b399

Although, I'm not sure this is the "right" way to build a cross-compile-friendly package, and maybe the "right" way to do it is changing in light of the work you guys are doing right now.

**Comment by Mic92** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/52031
However you will still have a problem, when your buildsystem relies on `llvm-config`.
