### ISSUE TITLE
Online package viewer shows [object Object] instead of maintainer

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#39217]
## Issue description

![screenshot_20180420_115824](https://user-images.githubusercontent.com/6344099/39045050-26a2eac2-4492-11e8-8ab8-f4b160b188b9.png)

### Steps to reproduce

https://nixos.org/nixos/packages.html

**Comment by edolstra** [comment]
Could you open this issue in the `nixos-homepage` repo please?

**Comment by ShalokShalom** [comment]
Sure
