### ISSUE TITLE
mxnet lies about its version

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#39235]
## Issue description
Despite the version 1.1.0 we appear to be using the hash and thus source for 0.11.0

The change was introduced in 3179002f610b8a58350e5837810cd724cf66165f

/cc @abbradar 

nixpkgs version c0c5571ec1a33a5109c122b8821eb15c36cbb1ec

**Comment by abbradar** [comment]
Exactly, I forgot it. Thanks, I'll look into.

**Comment by srhb** [comment]
@Hodapp87 I don't believe anything has been done to fix this. :)

**Comment by srhb** [comment]
Appears fixed ages aso
