### ISSUE TITLE
ImageMagick tarball is no longer available 6.9.9-34

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#39276]
## Issue description

NixPkgs master uses ImageMagick 6.9.9-34 which it wants to get from   https://github.com/ImageMagick/ImageMagick/archive/6.9.9-34.tar.gz but that file is no longer available.

### Steps to reproduce

nix-env -i ImageMagick

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.15, NixOS, 18.03.131807.489a14add9a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03, nixpkgs-18.03"`
 - channels(oever): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vandenoever** [comment]
Will that fix go into 18.03 as well?

**Comment by dotlambda** [comment]
Backported in b68697c3a49c7c4c65d214df26eaa5566882fab4.

**Comment by vandenoever** [comment]
Nixos 18.03 still tries to get https://github.com/ImageMagick/ImageMagick/archive/6.9.9-34.tar.gz

**Comment by dotlambda** [comment]
It can take a little time until the channel is updated.
