### ISSUE TITLE
qtmultimedia broken on darwin by gstreamer update

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#39289]
## Issue description

In #38149 @bkchr updated all the gstreamer plugins but they no longer build on darwin. This causes 
a lot of Qt packages to fail because gstreamer is a dependency of qtmultimedia. 

They fail to build because of added dependencies such as `wayland` and `libcap` which are not available on darwin. 

Please can we revert these patches until this issue is fixed?

Related: #36932 

cc @LnL7

**Comment by matthewbauer** [comment]
In general, I think we don't want to revert things on unstable just because things break. We call it unstable because we expect things on it to be unstable. The nixpkgs-18.03-darwin channel has [a working qt.qtmultimedia](https://hydra.nixos.org/build/72653518) (sadly qt.qtwebengine is still broken and we should definitely cherry-pick a fix if we can find a reliable one). I definitely agree it should be a high priority to fix and hopefully someone can look into it. But if we don't let things break no one will ever fix them.

**Comment by LnL7** [comment]
@bkchr I'm not sure if that will be enough, the gst plugin builds look pretty broken with meson.

**Comment by bkchr** [comment]
@LnL7 https://bugzilla.gnome.org/show_bug.cgi?id=781148 I think you are right. Maybe we need to disable meson on Mac OS.

**Comment by mpickering** [comment]
I think reverting is a good option still because this breaks a lot of packages, there is no clear fix and the patch wasn't tested at all by OfBorg when being reviewed.

**Comment by bkchr** [comment]
I would rather stick to autoconf on Mac, but not revert all the patches.

**Comment by matthewbauer** [comment]
Ok got gstreamer and gst-plugins-base working. qtmultimedia is currently building.

**Comment by LnL7** [comment]
I don't like conditionalizing builds like that for no good reason, but I guess if @matthewbauer already got it working we should just use it.

**Comment by matthewbauer** [comment]
> I don't like conditionalizing builds like that for no good reason

Oops! I didn't realize that. There is kind of a good reason in this case though. Not all of the plugins are necessary and most likely unused downstream. Cdparanoia and Xlib plugins were probably never used by Darwin apps anyway (see https://github.com/GStreamer/gst-plugins-base/blob/6a3640f36739c9869beaf05e83136e44492023e3/REQUIREMENTS).

Feel free to modify it though.

**Comment by mpickering** [comment]
Where is your patch @matthewbauer ?

Thanks for trying to fix this.

**Comment by matthewbauer** [comment]
The commit is 49d97c34958c1b31c509fe1cb52d97c998bd6184. Still looking into qtwebengine.

**Comment by LnL7** [comment]
@matthewbauer qtwebengine is not a new failure, check if it also works on 18.03 if you manage to fix it. I think I skipped over it with the ZHF review and forgot about it.

Thanks for all the work you've been doing recently!
