### ISSUE TITLE
python amqplib outdated

### ISSUE THREAD

**Issue by joehealy** [NixOS/nixpkgs#39299]
## Issue description

current package of amqplib is for version 0.6.1. This version does not support SSL connections. Version 1.0.2 supports SSL connections and was released in 2011.

The upgrade is trivial and available at:

https://github.com/joehealy/nixpkgs/commit/d891a0353c89a665447a9a00e453b83f90d5427c

I'm not sure how to do this as a pull request.

**Comment by costrouc** [comment]
Late but I have just opened a pull request that has version 1.0.2.

**Comment by cyounkins** [comment]
Looks like 1.0.2 is in, so can we close this?
