### ISSUE TITLE
qtwebengine: Can not play h264 video.

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#39334]
## Issue description
I'm using Falkon, which uses qtwebengine, and it is not compiled with the proprietary codecs.
Probably related to #36729
Is there something I can enable in my config?

### Steps to reproduce
Install a browser that uses qtwebengine and attempt to play a h264 video.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0, NixOS, 18.09pre135256.6c064e6b1f3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.09pre135256.6c064e6b1f3, nixpkgs-18.09pre137816.255a833e841"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by vonpost** [comment]
Like I said in #36729 the commit here vonpost/nixpkgs@94c2c9b fixes it. But it's a really ugly hack that requires you to rebuild Qt (which takes a while). If you desperately want h264 then that's an option until someone with more knowledge properly fixes this.
