### ISSUE TITLE
nixos/tests/keymap: non-deterministic failures

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#39330]
## Issue description

The `keymap` tests fail non-deterministically on hydra, which frequently delays nixos channels.
Applies to master and 18.03. These failures have occured since at least December 2017. 
Some recent examples: 

- master: https://hydra.nixos.org/build/72687103
- 18.03: https://hydra.nixos.org/build/73077967, https://hydra.nixos.org/build/73075854

I believe this is caused by fragile test cases rather than a real problem with the keymaps. Will investigate and try to improve the tests.

**Comment by Mic92** [comment]
Maybe they could be simplified somehow.

**Comment by srhb** [comment]
@xeji Cool! You might find some of the work and discussion here useful:

https://github.com/NixOS/nixpkgs/pull/33719

**Comment by xeji** [comment]
While we wait for Hydra I'll prepare a separate PR picking both changes to 18.03 and test it locally.

**Comment by srhb** [comment]
Aside from a cancellation that I don't think we should count, this looks really good. Let's go for 18.03. :)
