### ISSUE TITLE
Manual Chapter 2 has incorrect examples

### ISSUE THREAD

**Issue by mtthwjrgnsn** [NixOS/nixpkgs#39354]
## Issue description

The bullet points under Chapter 2, section 8 (the fdisk process) don't match up with what the real partitions are after write.

The last four lines of fdisk setup are relevant:

```
> x      # (enter expert mode)
> f      # (fix up the partition ordering)
> r      # (exit expert mode)
> w      # (write the partition table to disk and exit)
```

Earlier in the fdisk process, we create the partitions with the following numbering:

1. `/`
2. `swap`
3. `/boot`

*I believe* the `fix partition ordering` re-numbers the partitions based on their location within the partition label. Since the boot partition is at the front of the disk and our `/` partition is at the end, fdisk reorders the partitions as follows:

1. `boot/`
2. `swap`
3. `/`

The problem is when making the file systems. The manual still uses the **initial** partition numbers instead of the **new, ordered** numbers.

Thus:

```
# mkfs.ext4 -L nixos /dev/sda1
```

Creates an ext4 partition that is 512M big and is supposed to be boot. And:

```
# mkfs.fat -F 32 -n boot /dev/sda3
```

Creates a FAT32 partiton that's supposed to be our root labeled `nixos`.

Swap isn't affected being in the middle.

**Comment by fud** [comment]
I think the actual issue is that it's using gdisk commands not fdisk commands. If we change 

For partitioning: fdisk.

to

For partitioning: gdisk.

`# fdisk /dev/sda # (or whatever device you want to install on)
`
to

`# gdisk /dev/sda # (or whatever device you want to install on)
`

**Comment by samueldr** [comment]
Hi! Closing this issue since the partitioning instructions are now re-written for 18.09.

As far as the ordering of partitions is concerned, the newly re-written partitioning instructions were written to ensure it wouldn't be an issue.
