### ISSUE TITLE
icu: 60.x -> 61.1

### ISSUE THREAD

**Issue by srl295** [NixOS/nixpkgs#39388]
## Issue description

need icu 61.1 per https://github.com/NixOS/nixpkgs/pull/35294 discussion

### Steps to reproduce

nix-env -i icu61

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

Not able to paste that here, but it says nix-env (Nix) 2.0, 18.03.132021.c0c5571ec1a (Impala)

**Comment by JohnAZoidberg** [comment]
Was the original issue to have version 61 at all?
Currently we have 58, 59, 60, and 63.
The default version is 59, I guess we could think about making a newer one the default.

**Comment by srl295** [comment]
@JohnAZoidberg yes it was to add 61.  64.2 is now out

**Comment by teto** [comment]
closed by https://github.com/NixOS/nixpkgs/pull/60250 ?
