### ISSUE TITLE
krb5Full has lots of "non-dev" binaries in the dev output

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#39424]
Somehow it seems like `kinit` ended up in the `krb5Full.dev` output rather than its `.out` output, which seems unexpected to me. @vcunat I think you were the last one in that space. Was that intentional?

(this is true on both 18.03 and master as far as I can tell)

**Comment by kwohlfahrt** [comment]
@copumpkin - as part of that PR I'm moving the binaries back to the standard output because I had exactly the same issue. Specifically commit a772b51.
