### ISSUE TITLE
Alacritty using separate repository?

### ISSUE THREAD

**Issue by monokrome** [NixOS/nixpkgs#39446]
## Issue description

Alacritty is using a repository that is out-of-date and is not the actual alacritty repository. This seems dangerous, since I assume that most users will expect the package to be built from the package maintainer's distribution itself.

Installing alacritty uses the repository as defined here: 

https://github.com/NixOS/nixpkgs/blob/1b480c8538303f4e987278b259e0f0decd14bf18/pkgs/applications/misc/alacritty/default.nix#L40

The actual source repository for alacritty is at:

https://github.com/jwilm/alacritty

**Comment by Mic92** [comment]
This is not dangerous. All I did was replacing git dependencies by submodules in this commit https://github.com/Mic92/alacritty/commit/4987fb1e8e1cc31441a927eb60465618899f8c71
It is even mentioned in the comment above. Reason is that buildRustCrate cannot handle git dependencies at the moment.
I also would not call it out-dated it was last updated at 2018-03-04.

**Comment by monokrome** [comment]
@Mic92 I called it outdated because it wasn't up-to-date with `master` branch on Alacritty's actual repository
