### ISSUE TITLE
Enrich PATH of networkmanager dispatcher

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#39468]
## Issue description

I don't mean to spam the nix community (after irc and this post https://groups.google.com/forum/#!topic/nix-devel/lvRw1HF8i34 sorry), it's just that I wanted to ping maintainers @domenkozar @Phreedom  @rickynils  @obadz and don't know how to do on other channels.

My goal is to enrich the PATH environment variable of the transient nm-dispatcher service (which is empty here on nixos-unstable: `nixos-option systemd.services."nm-dispatcher".path`) with at least coreutils/iproute paths (else it makes sharing hooks between other distrib hard since I would have  to replace `ip` calls by `${pkgs.iproute}/bin/ip` or some related hack)

I don't know if I should add a path to the networkmanager service that oculd be inherited somehow by nm-dispatcher and what are the relations between dbus/systemd or if I should patch directly the "Network Manager Script Dispatcher Service" ?

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.16.0, NixOS, 18.09.git.ba64042 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - nixpkgs: `/home/teto/nixpkgs`

**Comment by FRidh** [comment]
How do you intend to share these "hooks"? Do you intend to install them system-wide? Or should users be able to install them themselves?

In case of the former, you would have to use Nix on NixOS. Then you have the possibility to make the substitution, or to extend `$PATH`. In case of the latter, extending `$PATH` would be the only solution.

**Comment by teto** [comment]
So I use this
```
    dispatcherScripts = [
      {
        source = hookUp;
        type = "up";
      }
      {
        source = hookDown;
        type = "down";
      }
    ];
```
with hookUp = ./myHook.sh since source. I don't mind copy/pasting 4/5 lines hooks and modifying them but as they grow in size it's a bother. I suppose I could rewrite them with
hook.sh:
```
IP=${IP:-ip}
$IP route add .....
```
and then do
```
    dispatcherScripts = [
      {
        source = writeScript hook.sh ''IP=${pkgs.iproute}/bin/ip'' + builtins.readfile ./raw_hook.sh;
        type = "up";
      }
    ];
```
but it seems convoluted to access a binary that your hooks are very likely to call.

**Comment by teto** [comment]
After lurking the irc channel, I successively discovered `systemctl edit` and `systemctl cat` which lead me to kinda understand the nixos systemd stuff using overrides (should definitely be in the doc). I fixed my problem with: https://github.com/NixOS/nixpkgs/pull/39142
