### ISSUE TITLE
ecryptfs: broken with lsof 4.90

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#39496]
## Issue description

`lsof: 4.98 -> 4.90` bump seems to have broken `ecryptfs` on master - it builds but does not work properly. Looks to me like this is a bug in `lsof`, see below. 

Edit: `nixos.tests.ecryptfs` is a blocker for the `nixos-unstable` channel.

`ecryptfs` upstream release is 2 yrs old.
A newer version of `lsof  4.91` is available, I'll try if a bump would solve this.

/cc @shlevy @dtzWill @dezgeg who did the most recent work on `lsof`.

### Steps to reproduce

Run the nixos test `nix-build nixos/tests/ecryptfs.nix` and check test log.
`ecryptfs` fails, claiming open files where there are none.

### Initial analysis

 `ecryptfs` calls `lsof +D /home/alice` on an empty home directory, and `lsof` returns:

```
    COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    sh        679 root    0r   CHR  229,0      0t0 8337 /dev/hvc0
    sh        679 root    1w   CHR  229,0      0t0 8337 /dev/hvc0
    sh        808 root    0r   CHR  229,0      0t0 8337 /dev/hvc0
    sh        808 root    1w   CHR  229,0      0t0 8337 /dev/hvc0
    .ecryptfs 810 root    1w   CHR  229,0      0t0 8337 /dev/hvc0
    sed       833 root    1w   CHR  229,0      0t0 8337 /dev/hvc0
```

Looks to me like a faulty `lsof` since `/dev/hvc0` is definitely not under `/home/alice`.

## Technical details

nixos-unstable-small 49d97c34958c1b31c509fe1cb52d97c998bd6184

**Comment by xeji** [comment]
`lsof 4.91` seems to fix this, `ecryptfs` test suceeds.

**Comment by xeji** [comment]
Fixed by #39497

**Comment by obadz** [comment]
Argl sorry for the duplicate. I searched for *open* issues :-(

**Comment by xeji** [comment]
well this was literally opened, fixed and closed within about 10 minutes :grinning:

**Comment by obadz** [comment]
A testament to the community's dynamism!
