### ISSUE TITLE
meson: cc.find_library doesn't work

### ISSUE THREAD

**Issue by yegortimoshenko** [NixOS/nixpkgs#39547]
See https://github.com/mesonbuild/meson/issues/217 and https://github.com/NixOS/nixpkgs/pull/39534. 

The issue is that unlike autoconf, meson does not automatically discover build inputs' `/lib`. This should be fixable via something like `LIBRARY_PATH = stdenv.lib.makeLibraryPath buildInputs;` inside the meson hook but I'm not entirely sure what implications of that would be.

/cc @jtojnar

**Comment by jtojnar** [comment]
Hmm, right, so meson uses linker so it recognises `LIBRARY_PATH` https://github.com/mesonbuild/meson/issues/217#issuecomment-210229040

I believe our student sets `LD_LIBRARY_PATH` or something, why does not the linker used by meson recognise it? 

How does `AC_CHECK_LIB` work?

**Comment by jtojnar** [comment]
It just might have been wrong library names: https://gitlab.gnome.org/GNOME/tracker-miners/commit/02497b42bab5ff4f2f5a9c956cec0057a2adc7e5 `tracker-miners` 2.0.5 build without manually setting `LIBRARY_PATH`.
