### ISSUE TITLE
gnome.tracker-miners: GStreamer extractor doesn't work

### ISSUE THREAD

**Issue by lukateras** [NixOS/nixpkgs#39545]
We might need to add `gst-plugins-good` to `buildInputs` in order to make that work.

/cc @jtojnar

**Comment by yegortimoshenko** [comment]
Also see #39534.

**Comment by sersorrel** [comment]
I feel like, based on the symptoms, this might be affecting me, though I'm not totally sure. If I drop an MP3 into ~/Music, it appears in Gnome Music just fine, but none of the FLACs in that directory show up at all.

In `tracker3 export -b org.freedesktop.Tracker3.Miner.Files`, the only thing recognised as `rdf:type <http://tracker.api.gnome.org/ontology/v3/nfo#Audio>` is that MP3.

I tried adding this to `nixpkgs.overlays`:

```nix
    (self: super: {
      gnome = super.gnome.overrideScope' (self': super': {
        tracker-miners = super'.tracker-miners.overrideAttrs (old: {
          buildInputs = (old.buildInputs or []) ++ [
            super.gst_all_1.gst-plugins-good
          ];
        });
      });
    })
```

and it definitely built something from source, but it doesn't appear to have achieved anything, even after a `systemctl --user stop tracker-miner-fs-3.service && rm -r ~/.cache/tracker3 && systemctl --user start tracker-miner-fs-3.service`.

I'm on NixOS 21.05.3065.b3083bc6933 (Okapi).

**Comment by jtojnar** [comment]
Maybe also `systemctl --user daemon-reload` to make sure the right service is used?

**Comment by sersorrel** [comment]
doesn't appear to help, sorry.
