### ISSUE TITLE
Unable to boot NixOS on MacBook, 2009, 64-bit

### ISSUE THREAD

**Issue by elaOnMars** [NixOS/nixpkgs#39550]
## Issue description
Booting of NixOS on a MacBook of 2009 (64-bit) is not possible.
I've tested several nix configurations.
Previously I have tried it with rEFInd. Then I have purged 
all traits of MacOSX to have a clean HDD for NixOS.

The installation on an AMD hardware with the same
ISO was successfully!

Issue https://github.com/NixOS/nixpkgs/issues/38477 could be related.

### Steps to reproduce
I've tested several nix configurations
as described thoroughly here:
https://gist.github.com/elaOnMars/7b1fbb6b3576ca82fb18e364081ef94d

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by vcunat** [comment]
It does seem this could be duplicate of the other issue which got fixed around the time you posted this issue.  I suggest you retry with a fresh 18.03 ISO.

**Comment by elaOnMars** [comment]
Thx for the hint! I'll test it later. What has been changed in the creation of the NixOS ISOs since my tests with NixOS 18.03.131807.489a14add9a?

**Comment by vcunat** [comment]
This is the commit I meant: e932b5be269

**Comment by samueldr** [comment]
If this particular problem is still an issue *for you*, please re-open the issue.

Anyone else with a *Macbook, 2009*, or *any other apple hardware*, please open a new issue, it is likely that the actual problem is different.

Thanks!
