### ISSUE TITLE
Shrink all-packages.nix

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#39561]
## Issue description

I think everyone agrees that all-packages.nix has become too difficult to maintain. I hope we can look into moving some of it into separate files. My goal would be to get it to under 15,000 lines which is the max GitHub will display. Right now it is 21,380 lines. This is related to #39169.

### Easy changes
- [ ] Merge common "inherit (x)" uses
- [ ] Move "nixpkgs.windows" attribute to its own file
- [ ] Move "nixpkgs.linuxPackagesFor" to its own file
- [ ] Move "nixpkgs.tests" to its own file
- [ ] Get rid of legacy "emacsPackagesGen" stuff (emacsPackagesNg has replaced it)
- [X] Move some aliases to aliases.nix
- [ ] Move fetchFromGitHub to its own file.

### Hard changes
- [ ] Move "stdenv" stuff to its own stdenv-packages.nix file
- [ ] Get rid of overrides in all-packages.nix (#39515)

**Comment by oxij** [comment]
- [ ] Autogenerate `pkgs/package-list.nix` and use that as a base for most of what `pkgs/top-level/all-packages.nix` now does.

**Comment by CMCDragonkai** [comment]
Maybe even alphabetically order it?
