### ISSUE TITLE
Remove duplicate packages from `nix-env -qa`

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#39563]
For some reason a few packages show up more than once in `nix-env -qa' with the same name and version. Some of them might have valid reasons but often it is just a bad alias in all-packages.nix. I want to look into removing the duplicates.

Result of `nix-env -qa | uniq -d | xargs -n1 echo " - [ ]"`:

 - [ ] android-sdk-25.2.2
 - [ ] awscli-1.10.51
 - [ ] bcc-git-2016-08-30
 - [ ] binutils-2.27
 - [ ] bugseverywhere-1.1.1
 - [ ] buildbot-0.9.0rc3
 - [ ] ceph-9.2.0
 - [ ] clang-wrapper-3.7.1
 - [ ] composer-1.2.0
 - [ ] construo-0.2.3
 - [ ] coreutils-8.25
 - [ ] curl-7.50.3
 - [ ] dbus-1.10.10
 - [ ] dejavu-fonts-2.37
 - [ ] django-pipeline-1.3.27
 - [ ] docker-compose-1.8.0
 - [ ] dwb-2016-03-21
 - [ ] fontforge-20160404
 - [ ] gazebo-6.5.1
 - [ ] gazebo-7.0.0
 - [ ] gdb-7.11.1
 - [ ] git-2.10.0
 - [ ] glib-2.48.2
 - [ ] glib-networking-2.46.1
 - [ ] gmp-6.1.1
 - [ ] gnumake-4.2.1
 - [ ] gnuplot-5.0.3
 - [ ] graphicsmagick-1.3.25
 - [ ] graphviz-2.38.0
 - [ ] gromacs-4.6.7
 - [ ] gst-python-1.8.2
 - [ ] hook
 - [ ] icdiff-1.7.3
 - [ ] icu4c-57.1
 - [ ] imagemagick-6.9.5-10
 - [ ] lgi-0.7.2
 - [ ] libc++-3.7.1
 - [ ] libc++abi-3.7.1
 - [ ] libcommuni-2016-08-17
 - [ ] libdbi-drivers-0.9.0
 - [ ] libdevil-1.7.8
 - [ ] liberation-fonts-2.00.1
 - [ ] libiberty-5.4.0
 - [ ] liblapack-3.4.1
 - [ ] liblapack-3.5.0
 - [ ] libpng-apng-1.6.23
 - [ ] libsoup-2.54.1
 - [ ] libva-1.7.2
 - [ ] libvirt-python-2.2.0
 - [ ] llvm-3.7.1
 - [ ] lua-5.2.3
 - [ ] lua-5.3.0
 - [ ] matita-0.5.8
 - [ ] mesa-8.0.5
 - [ ] mig-20100512
 - [ ] mjpegtools-2.1.0
 - [ ] mutt-1.7.0
 - [ ] ncurses-5.9
 - [ ] neuron-7.4
 - [ ] nghttp2-1.10.0
 - [ ] nix-1.11.4
 - [ ] nss-3.26
 - [ ] ocaml-4.02.3
 - [ ] ocaml-extlib-1.6.1
 - [ ] octave-4.0.1
 - [ ] openblas-0.2.19
 - [ ] openjdk-7u60b30
 - [ ] openntpd-5.7p4
 - [ ] patch-2.7.5
 - [ ] perl-5.22.2
 - [ ] php-imagick-3.4.0RC4
 - [ ] php-redis-2.2.7
 - [ ] php-xdebug-2.4.0RC3
 - [ ] phpcs-2.6.0
 - [ ] pinentry-0.9.7
 - [ ] pixman-0.34.0
 - [ ] pkg-config-0.29
 - [ ] pokerth-1.1.1
 - [ ] poppler-qt5-0.47.0
 - [ ] psutil-1.2.1
 - [ ] pulseaudio-9.0
 - [ ] pyblock-0.53
 - [ ] pycrypto-2.6.1
 - [ ] python-2.7.12
 - [ ] python-notify-0.1.1
 - [ ] python-recursive-pth-loader-1.0
 - [ ] python2.7-binwalk-2.1.1
 - [ ] python2.7-deform-2.0a2
 - [ ] python2.7-Django-1.10.1
 - [ ] python2.7-h5py-2.6.0
 - [ ] python2.7-more-itertools-2.2
 - [ ] python2.7-numpy-1.11.1
 - [ ] python2.7-pandas-0.18.1
 - [ ] python2.7-protobuf-2.6.1
 - [ ] python2.7-pycodestyle-2.0.0
 - [ ] python2.7-pygtk-2.24.0
 - [ ] python2.7-pytest-2.9.2
 - [ ] python2.7-scipy-0.18.0
 - [ ] python2.7-SQLAlchemy-1.0.15
 - [ ] python2.7-tensorflow
 - [ ] python2.7-zc.buildout-1.5.2
 - [ ] python2.7-zc.buildout-1.7.1
 - [ ] python2.7-zc.buildout-2.2.1
 - [ ] python3.5-binwalk-2.1.1
 - [ ] python3.5-deform-2.0a2
 - [ ] pyunbound-1.5.9
 - [ ] PyXAPI-0.1
 - [ ] qt-4.8.7
 - [ ] rebar3-3.1.0
 - [ ] rtmpdump-2015-01-15
 - [ ] samba-4.3.11
 - [ ] simutrans-120.1.1
 - [ ] smugline-20160106
 - [ ] stdenv-darwin
 - [ ] strongswan-5.5.0
 - [ ] sysdig-0.10.0
 - [ ] udiskie-1.5.1
 - [ ] unzip-6.0
 - [ ] vim_configurable-8.0.0005
 - [ ] w3m-0.5.3-2015-12-20
 - [ ] webkitgtk-2.4.11
 - [ ] wine-1.8.4
 - [ ] youtube-dl-2016.09.19
 - [ ] zulu1.8.0_66-8.11.0.1

**Comment by matthewbauer** [comment]
Most of these appear to be aliases. Is there a way to tell nix-env not to include them?

**Comment by ttdoucet** [comment]
Yes, same is 2021.  I think nix is amateur garbage.
