### ISSUE TITLE
Chromium meta error broke the bot testing pipeline

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nixpkgs#39575]
## Issue description

After issue: [Slow chromium build is blocking channels #39476](https://github.com/NixOS/nixpkgs/issues/39476)

And merge: [chromium: See if Hydra obeys a 24h meta.timeout #39570](https://github.com/NixOS/nixpkgs/issues/39570)

I submit changes to PR that is self-contained HandBrake package change: [handbrake: 1.0.7 -> 1.1.0, according changes #39512](https://github.com/NixOS/nixpkgs/issues/39512)

And now it falls with the error message due to meta issue in `chromium`:
```
error: while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/.gc-of-borg-outpaths.nix:35:12, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/attrsets.nix:199:52:
while evaluating the attribute 'aarch64-linux' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/attrsets.nix:185:41:
while evaluating anonymous function at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/release-lib.nix:94:6, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/attrsets.nix:282:43:
while evaluating 'hydraJob' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:162:14, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/top-level/release-lib.nix:94:14:
while evaluating the attribute 'outPath' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:178:13:
while evaluating the attribute 'outPath' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/lib/customisation.nix:147:13:
while evaluating the attribute 'handled' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/stdenv/generic/check-meta.nix:211:7:
while evaluating 'handleEvalIssue' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/stdenv/generic/check-meta.nix:128:28, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/stdenv/generic/check-meta.nix:212:14:
while evaluating 'handleEvalIssue' at /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/.gc-of-borg-outpaths.nix:21:37, called from /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/stdenv/generic/check-meta.nix:138:8:
evaluation aborted with the following error message: 'Package ‘chromium-66.0.3359.117’ in /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci/pkgs/applications/networking/browsers/chromium/browser.nix:48 has an invalid meta attrset:
	 - key 'timeout' is unrecognized; expected one of: 
	      ['available', 'badPlatforms', 'branch', 'broken', 'description', 'downloadPage', 'downloadURLRegexp', 'executables', 'homepage', 'hydraPlatforms', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'maintainers', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'repositories', 'schedulingPriority', 'tag', 'updateWalker', 'version'], refusing to evaluate.

'
```
### Steps to reproduce

Submit a PR or changes.
See what bot would return for evaluation stage "grahamcofborg-eval-check-meta — config.nix: checkMeta = true". 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

Please, @srhb take notice!

**Comment by srhb** [comment]
Thanks!

**Comment by Anton-Latukha** [comment]
https://github.com/NixOS/nixpkgs/pull/39512
In https://gist.github.com/GrahamcOfBorg/c9dffdc67ec4792e65c40b220a1b3378

And you can see same in any newest PRs.

Probably bot did getting Hydra code update.

**Comment by srhb** [comment]
Let's see if this pans out: https://logs.nix.ci/?key=nixos/nixpkgs.39512

**Comment by 7c6f434c** [comment]
@Anton-Latukha if you want to prevent other people from getting hit by such things, in two hours you probably could look at the ofborg README, look at the instructions to run the meta-check locally, find out how to actually do this with minimal changes (right now this doesn't seem to work as-is), and PR a documentation (and maybe `outpaths.nix` patch) against ofborg. Or maybe port meta checks to `maintainers/scripts/test-eval-release.sh` in nixpkgs…

**Comment by 7c6f434c** [comment]
(any partial progress described in an issue could be useful)

**Comment by 7c6f434c** [comment]
Sometimes checks pass now: https://github.com/NixOS/nixpkgs/pull/39576

**Comment by Anton-Latukha** [comment]
@7c6f434c 
Ok.

**Comment by srhb** [comment]
@Anton-Latukha Looks like we're going again! Thanks again, and thank you @7c6f434c ! :)

**Comment by 7c6f434c** [comment]
More precisely, the PR mentioned in this issues is now green.

Thanks for reporting, and thanks for your efforts to do something about local checks for this problem.

**Comment by Anton-Latukha** [comment]
Ok. Red alert passed.
Then I would go to sleep.

Local meta question involves deploying Hydra, creating jobset, starting it.
This part I know, can do in 2 hours.

Then understanding how Bot works, reading code in Rust (which is kryptonite right now, I totally not have a knowledge of Rust & currently brain charge to parse such lang). And then playing around with it.

I would dedicate my normal time to it.

**Comment by 7c6f434c** [comment]
>Then understanding how Bot works, reading code in Rust (which is kryptonite right now, I totally not have a knowledge of Rust & currently brain charge to parse such lang). And then playing around with it.

Hopefully only the nix code there really matters…

>I would dedicate my normal time to it.

Sure, no urgence

**Comment by Anton-Latukha** [comment]
Thank you all.
