### ISSUE TITLE
Add useful error message when /nix/var/nix/binary-cache-v3.sqlite is corrupted

### ISSUE THREAD

**Issue by alexanderkjeldaas** [NixOS/nixpkgs#3958]
I just got a corrupted binary-cache-v3 and it took a while to figure out what to do.

Basically this is what a user will see in this case:

``` shell
# nixos-rebuild -k --cores 16 switch 
building Nix...
building the system configuration...
download-from-binary-cache.pl: DBD::SQLite::st execute failed: database disk image is malformed at /nix/store/48syzm08vcmpcyf5klx7jfsjc8hgpz8m-nix-1.7/libexec/nix/substituters/download-from-binary-cache.pl line 363.
error: substituter `download-from-binary-cache.pl' died unexpectedly
```

Instead, the user should be instructed to run:

``` shell
sqlite3 /nix/var/nix/binary-cache-v3.sqlite "pragma integrity_check"
```

and/or delete that file.

**Comment by cleverca22** [comment]
ive also run into this issue once, its just a cache of what is on the cache, so the simplest thing is to auto-delete the database and retry

**Comment by Profpatsch** [comment]
triage: is this still an issue?
