### ISSUE TITLE
`azure-agent` needs to be updated to 2.2.x

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#39582]
## Issue description
`azure-agent` packages `walinuxagent` (legacy/binary name `waagent`): https://github.com/Azure/WALinuxAgent

It currently packages `waagent-2.0`. The currently supported versions are 2.2.x.

I need some advice. Previously `waagent` was a single executable python script, so packaging was relatively straight-forward.

I'd like to package the latest v2.2.25, which looks like more of a typical python package?

https://github.com/Azure/WALinuxAgent/tree/v2.2.25

But I tried wrapping it as a typical pythonPackage and instead it started executing the actual agent service (this may be due to how their repo/project is setup though... I do not know much about pythong packaging.)

**Comment by colemickens** [comment]
cc: @jbgi due to the recent Azure PR, just as an FYI.

**Comment by jbgi** [comment]
@colemickens We do have a slightly more recent version of waagent package. Did not have time to finish testing it so I did not open the PR. It is based on this branch: https://github.com/jbgi/WALinuxAgent/tree/nixos
Will push my nixpkgs branch shortly.

**Comment by jbgi** [comment]
@colemickens The minimal changes I did to package the above branch: https://github.com/jbgi/nixpkgs/commit/f05acadcdc0040ec5569205c4276dc57706496d6

**Comment by colemickens** [comment]
@jbgi thanks for sharing this. Do you just use the agent for initial provisioning, or is it used for extensions as well (I assume that most or all extensions wouldn't work on NixOS).

I'm just wondering, initial provisioning is pretty straightforward I think, I'm tempted to see if I can replace it with a simple bash script and get my images even smaller (and potentially more stable).

**Comment by jbgi** [comment]
@colemickens I had plan to use some extensions but never got to the point of getting any extension working (cf. https://github.com/Azure/custom-script-extension-linux/pull/123). so yeah mostly given up on using extensions for now.

**Comment by khssnv** [comment]
Anyone works on it?

**Comment by thpham** [comment]
Hello @khssnv 

Here is a try #56986 , but I would need some help to test this.

**Comment by siraben** [comment]
Any updates?

**Comment by colemickens** [comment]
My opinion? You couldn't possibly pay me to work, or work on packaging, Azure's agent. I rewrote my own in Rust and `nixos-azure` uses that going forward.

**Comment by MartinPotier** [comment]
https://www.wiz.io/blog/secret-agent-exposes-azure-customers-to-unauthorized-code-execution

We should be *very careful* when packaging and running root daemons.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/d2c3bf424abb78f3879f5a9f9983e85f1bbaa4aa/pkgs/applications/networking/cluster/waagent/default.nix#L24
