### ISSUE TITLE
Tensorboard results in error about html5lib when used with python 3.6m

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#39588]
## Issue description

Installing `tensorflow-tensorboard` gives this error:

```
error: html5lib-0.9999999 not supported for interpreter python3.6m
```

### Steps to reproduce

Using this shell.nix:

```
{
  pkgs ? import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/6c064e6b1f34a8416f990db0cc617a7195f71588.tar.gz) {}
}:
  with pkgs;
  let
    python = python36;
  in
    python.pkgs.buildPythonApplication {
      name = "testenv";
      buildInputs =  (with python.pkgs; [
        tensorflowWithCuda
        tensorflow-tensorboard
      ]);
    }
```

The hash is the current latest hash on `nixpkgs-unstable`.

@abbradar

**Comment by abbradar** [comment]
It is as said -- Tensorboard is not supported on Python 3.6. We hack around it allowing Tensorflow to be installed without Tensorboard in this case.
